### ISSUE TITLE
[LV] Use legacy cost model by default in 19.x

### ISSUE THREAD

**Issue by fhahn** [llvm/llvm-project#100093]
As discussed in https://github.com/llvm/llvm-project/pull/92555, use the legacy cost model by default in the 19.x release using the option added in https://github.com/llvm/llvm-project/pull/99536.

**Comment by fhahn** [comment]
cc @ayalz @nikic

**Comment by nikic** [comment]
Closing in favor of the PR https://github.com/llvm/llvm-project/pull/100097.
