### ISSUE TITLE
P1963R0: Fixing US 313

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#100039]
**Link:** https://wg21.link/p1963r0

**Comment by frederick-vs-ja** [comment]
I think this is "Nothing To Do".
- For legacy algorithms, P1963R0 reverted accidental precondition strengthening.
- For C++20 `ranges` algorithms that are not in `<memory>`, P1963R0 relaxed (probably unintended imposed) preconditions.

**Comment by ldionne** [comment]
I think I agree. There's also nothing we can actually check, except perhaps some overlap checks in the uninitialized algorithms but those were already preconditions anyway.
