### ISSUE TITLE
P2045R1: Missing Mandates for the standard library

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#100041]
**Link:** https://wg21.link/p2045r1

**Comment by frederick-vs-ja** [comment]
IIUC this is Nothing To Do. The paper just changed the style for specifying UB in some cases.

**Comment by ldionne** [comment]
I think I agree. I looked at everything moved to a "precondition" by that paper and they are either things we can't check, or they are for `atomic<shared_ptr>` which we don't implemented yet. We can add precondition tests when we add those classes.
