### ISSUE TITLE
__push_heap_front does two comparisons per step, only one is needed

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#10008]
|  |  |
| --- | --- |
| Bugzilla Link | [9636](https://llvm.org/bz9636) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dexonsmith,@mclow |

## Extended Description 
__push_heap_front is normally used to put in the correct position an element that was previously a leaf of a heap (as in the pop_heap implementation). Since that element was a leaf, it is likely that it will move down when placed in the root.

An optimization is to move down the empty space at the root by swapping it with the largest children. When the empty space becomes a leaf, the last element is moved to its place and moved up if necessary (push_heap).

The advantage is that only one comparison per step is needed to move the empty space down.

Wikipedia attributes the improvement to R. W. Floyd (http://en.wikipedia.org/wiki/Heapsort), but I could not find the original paper.

**Comment by Quuxplusone** [comment]
This is now https://reviews.llvm.org/D118003
