### ISSUE TITLE
[Flang] Cannot scan continuation lines with preprocessor marks

### ISSUE THREAD

**Issue by mjklemm** [llvm/llvm-project#100073]
When compiling the following reproducer, Flang emits an error message:

```
> flang-new -c ./reproducer.f90
error: Could not scan ./reproducer.f90
somepath/reproducer.F90:4:18: error: Unmatched ')'
           & param3)
                   ^
```

Reproducer:
```Fortran
subroutine sub()
    implicit none
    integer :: param1, param2, param3
    call something(param1, param2, &
# 4 "somepath/reproducer.F90"
         & param3)
    )
end subroutine sub
```

This used to work before commit 5d15f606da4cb4346465956d935a2842f8e86200 was merged.

**Comment by mjklemm** [comment]
@klausler Do you mind having a look at this and see if this is something that can be supported again?

**Comment by klausler** [comment]
How could that reproducer ever work?  It has one more right parenthesis than it has left parentheses.

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/100178
