### ISSUE TITLE
[Flang] Linker error when ``--offload-arch`` not specified when compiling with `target` construct

### ISSUE THREAD

**Issue by bhandarkar-pranav** [llvm/llvm-project#100209]
When compiling even a simple program with the OpenMP `target` construct, we get the following linker error when `--offload-arch` is not specified.
```
flang-new -O2 -fopenmp target_no_arch.f90
ld.lld: error: undefined symbol: __tgt_target_kernel
>>> referenced by FIRModule
>>>               /tmp/target_no_arch-5b3141.o:(_QQmain)
```

test file ->
```
$> cat target_no_arch.f90
program main
  integer :: a = 0
  !$omp target
  print *, a
  !$omp end target
end program main
```

**Comment by jhuber6** [comment]
`__tgt_target_kernel` comes from `libomptarget.so`, not `libomp.so`. When there's no `--offload-arch` or other offloading flags we don't implicitly link `-lomptarget`. However, the compiler front-end should not be emitting these runtime calls without an offloading language, see https://godbolt.org/z/hz5G7a4vz.

**Comment by skatrak** [comment]
> However, the compiler front-end should not be emitting these runtime calls without an offloading language, see https://godbolt.org/z/hz5G7a4vz.

Yes, that is what this PR prevents from being done to address the issue: #100156.
