### ISSUE TITLE
Flang build fails on GitHub Action Windows runners

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#100202]
I'm trying to do a release build with flang on the GitHub Actin Window runners and it is failing with this error:

```
FAILED: bin/bbc.exe 
C:\Windows\system32\cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=tools\flang\tools\bbc\CMakeFiles\bbc.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\LLVM\bin\lld-link.exe /nologo @CMakeFiles\bbc.rsp  /out:bin\bbc.exe /implib:lib\bbc.lib /pdb:bin\bbc.pdb /version:0.0 /machine:x64 /STACK:10000000 /INCREMENTAL:NO /subsystem:console && cd ."
LINK: command "C:\PROGRA~1\LLVM\bin\lld-link.exe /nologo @CMakeFiles\bbc.rsp /out:bin\bbc.exe /implib:lib\bbc.lib /pdb:bin\bbc.pdb /version:0.0 /machine:x64 /STACK:10000000 /INCREMENTAL:NO /subsystem:console /MANIFEST:EMBED,ID=1" failed (exit code 1) with the following output:

lld-link: error: undefined symbol: __udivti3
>>> referenced by FortranDecimal.lib(binary-to-decimal.cpp.obj):(public: __cdecl Fortran::decimal::BigRadixFloatingPointNumber<64, 16>::BigRadixFloatingPointNumber<64, 16>(class Fortran::decimal::BinaryFloatingPointNumber<64>, enum Fortran::decimal::FortranRounding))
>>> referenced by FortranDecimal.lib(binary-to-decimal.cpp.obj):(public: __cdecl Fortran::decimal::BigRadixFloatingPointNumber<113, 16>::BigRadixFloatingPointNumber<113, 16>(class Fortran::decimal::BinaryFloatingPointNumber<113>, enum Fortran::decimal::FortranRounding))
```

### How To Reproduce

```
cmake -G Ninja -S llvm -B /d/a/llvm-project/llvm-project/build \
         -DLLVM_RELEASE_ENABLE_PGO=OFF -DLLVM_RELEASE_ENABLE_LTO=OFF \
         -C clang/cmake/caches/Release.cmake \
         -DBOOTSTRAP_LLVM_PARALLEL_LINK_JOBS=1
```

**Comment by luporl** [comment]
This is a regression introduced a few days ago: https://lab.llvm.org/buildbot/#/builders/124/builds/78

Linaro is investigating it.
@omjavaid

**Comment by omjavaid** [comment]
I have posted a revert that fixes this issue. @tstellar Please confirm if it fixes the windows build for you.

**Comment by awson** [comment]
Same here.

But in my case the culprit was clang 19->20 transition, the nonexistent `.../lib/clang/19/lib/windows/clang_rt.builtins-x86_64.lib` stuck in `CMakeCache.txt`.

I've manually changed `19` to `20` and everything went okay after.

**Comment by tstellar** [comment]
PR #101344 will have the test results.

**Comment by tstellar** [comment]
I'm still seeing the same failure:

https://github.com/llvm/llvm-project/actions/runs/10182363159/job/28178523538

**Comment by omjavaid** [comment]
@tstellar I have tried a two stage build locally and it works fine on Windows 11 x86_64 box. I cant seem to read the cmake commandline on stage2 build in the GHA build logs found at:
https://github.com/llvm/llvm-project/actions/runs/10182363159/job/28178523538
Although rest of cmake log is available but the cmake invocations command is missing. Also in the cmake log I noticed that it fails to locate the clang_rt.builtins-x86_64.lib with message "Failed to find compiler-rt builtins library for "

It should say something like following: " Found compiler-rt builtins library: C:/work/llvm-dev/stage1/lib/clang/20/lib/windows/clang_rt.builtins-x86_64.lib
-

**Comment by tstellar** [comment]
@omjavaid Thanks for investigating.  I did not see that error message before.  I think think the problem is that we are not building compiler-rt for stage 1.  I'll try and see if that fixes it.

**Comment by tstellar** [comment]
@omjavaid Enabling compiler-rt in the stage1 build did fix the issue.  I've updated the PR now.
