### ISSUE TITLE
[Clang] `clang-linker-wrapper` does not forward `-fpass-plugin` to the LTO invocation

### ISSUE THREAD

**Issue by jhuber6** [llvm/llvm-project#100212]
Recent patches moved the LTO portion of the offloading compilation into the actual linker invocation. This means we aren't forwarding linker options to it correctly.

**Comment by aemerson** [comment]
What's the commit that introduced this failure? Normally we should revert changes that break tests instead of just XFAILing the test.

**Comment by jhuber6** [comment]
> What's the commit that introduced this failure? Normally we should revert changes that break tests instead of just XFAILing the test.

it was a change to how linking is done for offloading. I'm going to fix this tomorrow morning but didn't have the time, the users of this feature haven't upstreamed anything that relies on it so I figured it was fine. It's a simple patch to just forward some options.

**Comment by cachemeifyoucan** [comment]
@jhuber6 The comment references to this issue is in `linker-wrapper-passes.c` but that test is still XFAIL'ed with this issue closed?

The test is also failing on `release/19.x` branch since the XFAIL commit just miss the branch point.

**Comment by jhuber6** [comment]
I thought I landed this stuff after the fork date? That being said, I talked it over with @jdenny-ornl who was the one who wrote the test and decided that the use-case is invalid so it should probably just be deleted, I forgot to do that.

**Comment by cachemeifyoucan** [comment]
Deleting the test sounds fine to me but we shouldn't leave a XFAIL with a link to a closed issue :)

**Comment by jhuber6** [comment]
> Deleting the test sounds fine to me but we shouldn't leave a XFAIL with a link to a closed issue :)

Yeah, sorry, slipped my mind after I changed the linked patch to no longer remove the `XFAIL`. I guess I'll also wait and see what @jdenny-ornl says since it was originally his test-case.

**Comment by jdenny-ornl** [comment]
Yes, delete the test.  I would characterize the reason differently though: the high-level use case still seems valid, but the interface is shifting, and this test doesn't fit it anymore.

**Comment by jhuber6** [comment]
> Yes, delete the test. I would characterize the reason differently though: the high-level use case still seems valid, but the interface is shifting, and this test doesn't fit it anymore.

Yeah, worded that poorly, I meant the specific way it was implemented was invalid with shifting uses.
