### ISSUE TITLE
LWG2593: Moved-from state of Allocators

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#100220]
**Link:** https://wg21.link/lwg2593

**Comment by frederick-vs-ja** [comment]
Possibly nothing to do. I'm not aware of libc++ (or any other standard libaray implementaton) even provided such a weird allocator type which did't meet the strengthened requirement.

But the `test_allocator` in the test suits needs to be fixed.
https://github.com/llvm/llvm-project/blob/8b26c02caaa002edc2d70af9e6a8024c4b1343cf/libcxx/test/support/test_allocator.h#L121-L130
