### ISSUE TITLE
[RISCV][MC] RISCVMCInstrAnalysis::isCall for C extension

### ISSUE THREAD

**Issue by tianboh** [llvm/llvm-project#100308]
I noticed that `RISCVMCInstrAnalysis::isCall` considers JAL and JALR.
```C
  bool isCall(const MCInst &Inst) const override {
    if (MCInstrAnalysis::isCall(Inst))
      return true;

    switch (Inst.getOpcode()) {
    default:
      return false;
    case RISCV::JAL:
    case RISCV::JALR:
      return Inst.getOperand(0).getReg() != RISCV::X0;
    }
  }
```

Howerver, `C.J`, `C.JAL` and `C.JALR` can also be used to jump and its destination can be non `X0`. Is there any insight why we missing them?

Consider SPEC
![image](https://github.com/user-attachments/assets/f8cd7d2a-d630-451a-bb25-5a8c48f91ae4)

**Comment by topperc** [comment]
They have the `MCID::Call` flag set in the `MCInstrDesc` so the default implementation of `MCInstrAnalysis::isCall` already works.

```
    { 12475,    1,      0,      2,      6,      0,      1,      RISCVImpOpBase + 16,    7998,   0|(1ULL<<MCID::Call), 0x8ULL },  // Inst #12475 = C_JALR
    { 12474,    1,      0,      2,      4972,   0,      1,      RISCVImpOpBase + 16,    171,    0|(1ULL<<MCID::Call), 0x10ULL },  // Inst #12474 = C_JAL
```
