### ISSUE TITLE
CWG2813: extra move in calling of explicit object member function

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#100314]
This program
```
struct A {
    A() {}
    A(A&&) = delete;
    void f(this A) {}
};

int main() {
    A{}.f();
}
```
must be accepted per [CWG2813](https://cplusplus.github.io/CWG/issues/2813.html), and GCC does accept it, but not Clang unfortunately.

Online demo: https://gcc.godbolt.org/z/6x7PTsE4M

Related discussion: https://stackoverflow.com/q/78785176/7325599

**Comment by cor3ntin** [comment]
See https://github.com/llvm/llvm-project/pull/95112 @MitalAshok
