### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by oroppas** [llvm/llvm-project#10046]
|  |  |
| --- | --- |
| Bugzilla Link | [9674](https://llvm.org/bz9674) |
| Version | trunk |
| OS | Linux |

## Extended Description 
I've got

[ 60%] Building CXX object tools/gold/CMakeFiles/LLVMgold.dir/gold-plugin.cpp.o
/home/ryuta/devel/llvm/src/llvm/tools/gold/gold-plugin.cpp:53:3: error: ‘ld_plugin_get_view’ does not name a type
/home/ryuta/devel/llvm/src/llvm/tools/gold/gold-plugin.cpp: In function ‘ld_plugin_status onload(ld_plugin_tv*)’:
/home/ryuta/devel/llvm/src/llvm/tools/gold/gold-plugin.cpp:209:12: error: ‘LDPT_GET_VIEW’ was not declared in this scope
/home/ryuta/devel/llvm/src/llvm/tools/gold/gold-plugin.cpp:210:9: error: ‘get_view’ was not declared in this scope
/home/ryuta/devel/llvm/src/llvm/tools/gold/gold-plugin.cpp:210:29: error: ‘union ld_plugin_tv::<anonymous>’ has no member named ‘tv_get_view’
/home/ryuta/devel/llvm/src/llvm/tools/gold/gold-plugin.cpp: In function ‘ld_plugin_status claim_file_hook(const ld_plugin_input_file*, int*)’:
/home/ryuta/devel/llvm/src/llvm/tools/gold/gold-plugin.cpp:239:7: error: ‘get_view’ was not declared in this scope
/home/ryuta/devel/llvm/src/llvm/tools/gold/gold-plugin.cpp: In function ‘ld_plugin_status all_symbols_read_hook()’:
/home/ryuta/devel/llvm/src/llvm/tools/gold/gold-plugin.cpp:411:10: warning: unused variable ‘bufsize’
make[2]: *** [tools/gold/CMakeFiles/LLVMgold.dir/gold-plugin.cpp.o] Error 1
make[1]: *** [tools/gold/CMakeFiles/LLVMgold.dir/all] Error 2
make: *** [all] Error 2

I'm using binutils-2.21, which doesn't have ld_plugin_get_view yet.
Am I missing something?

Thanks.

**Comment by arsenm** [comment]
Old build issue
