### ISSUE TITLE
LWG3362: Strike `stop_source`'s `operator!=`

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#100433]
**Link:** https://wg21.link/lwg3362

**Comment by Zingam** [comment]
That one seems to be already done in b77e50e6aef5650d1ce0ce7ad1a41049395b9426:
https://github.com/llvm/llvm-project/blob/6f83477b00cc6d8e665105336de7c9be1880a00a/libcxx/include/__stop_token/stop_source.h#L79
