### ISSUE TITLE
LWG3395: Definition for three-way comparison needs to be updated (US 152)

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#100434]
**Link:** https://wg21.link/lwg3395

This is an update to [[intro.defs]](https://eel.is/c++draft/intro.defs), but I can't seem to find [defns.comparison] at all.

**Comment by frederick-vs-ja** [comment]
I believe this is Nothing to do. The section was removed by https://github.com/cplusplus/draft/commit/c76a8a7038907975eaaa0d0b61b6212abefc8895.
