### ISSUE TITLE
Request Commit Access For broxigarchen

### ISSUE THREAD

**Issue by broxigarchen** [llvm/llvm-project#100457]
Hi,

I am a AMDGPU backend developer and I am requesting a write access.

Thanks!

**Comment by asl** [comment]
@broxigarchen Per LLVM developer policy (https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access): 
> We grant commit access to contributors with a track record of submitting high quality patches. 

Will it be possible for you to provide a list of these contributions? Just list of PRs would be enough. For now https://github.com/llvm/llvm-project/pulls/broxigarchen shows only single unmerged PR.

**Comment by broxigarchen** [comment]
> @broxigarchen Per LLVM developer policy (https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access):
> 
> > We grant commit access to contributors with a track record of submitting high quality patches.
> 
> Will it be possible for you to provide a list of these contributions? Just list of PRs would be enough. For now https://github.com/llvm/llvm-project/pulls/broxigarchen shows only single unmerged PR. Furthermore, the commits in this PR was authored by someone else.

Hi Anton, please find the list of PR
https://github.com/llvm/llvm-project/pull/100442
https://github.com/llvm/llvm-project/pull/100849
https://github.com/llvm/llvm-project/pull/102198
https://github.com/llvm/llvm-project/pull/102942
https://github.com/llvm/llvm-project/pull/102620

**Comment by broxigarchen** [comment]
Hey just want to send a quick ping. Thanks!

**Comment by lattner** [comment]
hi @broxigarchen, it would be helpful if you could follow the developer policy (send an email, not file an issue).
