### ISSUE TITLE
`<algorithm>`:  unused `__find_end` implementation details

### ISSUE THREAD

**Issue by hewillk** [llvm/llvm-project#100569]
The two functions named `__find_end` in find_end.h are not called from anywhere, they are useless and should be removed.

https://github.com/llvm/llvm-project/blob/a79db96ec0decca4fe45579e039cf5589345b3ed/libcxx/include/__algorithm/find_end.h#L83-L184

**Comment by hewillk** [comment]
Note that there is a typo in line 179, namely `std::__invoke(*--__m2)`. But since this is dead code, we should just remove the whole function.

**Comment by frederick-vs-ja** [comment]
Would you like to kill this `__find_end` yourself? This seems to be NFC.
