### ISSUE TITLE
Crash dump

### ISSUE THREAD

**Issue by h1laryz** [llvm/llvm-project#100501]
[Info  - 5:41:04 AM] Connection to server got closed. Server will restart.
[Error - 5:41:04 AM] Request textDocument/documentSymbol failed.
[object Object]
[Error - 5:41:04 AM] Request textDocument/codeAction failed.
[object Object]
[Error - 5:41:04 AM] Request textDocument/documentLink failed.
[object Object]
[Error - 5:41:04 AM] Request textDocument/inlayHint failed.
[object Object]
[Error - 5:41:04 AM] Request textDocument/documentSymbol failed.
[object Object]
[Error - 5:41:04 AM] Request textDocument/semanticTokens/full failed.
[object Object]
I[05:41:04.959] clangd version 18.1.3 (https://github.com/llvm/llvm-project c13b7485b87909fcf739f62cfa382b55407433c0)
I[05:41:04.959] Features: linux+grpc
I[05:41:04.959] PID: 6343
I[05:41:04.959] Working directory: /home/h1lary/castaluck_game_server
I[05:41:04.959] argv[0]: /home/h1lary/.local/share/nvim/mason/bin/clangd
I[05:41:04.959] Starting LSP over stdin/stdout
I[05:41:04.960] <-- initialize(0)
I[05:41:04.967] --> reply:initialize(0) 7 ms
I[05:41:04.968] <-- initialized
I[05:41:04.970] <-- textDocument/didOpen
I[05:41:04.972] --> textDocument/publishDiagnostics
I[05:41:04.973] Loaded compilation database from /home/h1lary/castaluck_game_server/compile_commands.json
I[05:41:04.973] <-- textDocument/documentSymbol(1)
I[05:41:04.973] <-- textDocument/codeAction(2)
I[05:41:04.974] ASTWorker building file /home/h1lary/castaluck_game_server/include/gs/game/fsm/FsmFactory.hpp version 29 with command inferred from /home/h1lary/castaluck_game_server/src/gs/game/pg/PgDao.cpp
[/home/h1lary/castaluck_game_server/build_debug]
/usr/bin/c++ --driver-mode=g++ -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_CHRONO_DYN_LINK -DBOOST_ENABLE_ASSERT_HANDLER -DBOOST_LOCALE_DYN_LINK -DBOOST_STACKTRACE_BACKTRACE_DYN_LINK -DBOOST_STACKTRACE_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DCPPTRACE_DEMANGLE_WITH_CXXABI -DCPPTRACE_GET_SYMBOLS_WITH_LIBDWARF -DCPPTRACE_HAS_CXX_EXCEPTION_TYPE -DCPPTRACE_HAS_DL_FIND_OBJECT -DCPPTRACE_STATIC_DEFINE -DCPPTRACE_UNWIND_WITH_UNWIND -DFMT_LOCALE -DFMT_SHARED -DLIBASSERT_STATIC_DEFINE -DMOODYCAMEL_NO_THREAD_LOCAL -DPIC=1 -DUSERVER=1 -DUSERVER_NAMESPACE=userver "-DUSERVER_NAMESPACE_BEGIN=namespace userver { inline namespace v2_2_rc { " "-DUSERVER_NAMESPACE_END=} }" -D_GLIBCXX_ASSERTIONS -I/home/h1lary/castaluck_game_server/include -I/home/h1lary/castaluck_game_server/chaotic/include -I/home/h1lary/castaluck_game_server/build_debug/chaotic/src -isystem /usr/local/include/gen -isystem /usr/local/include/gen/proto -isystem /usr/local/include/cpptrace -isystem /usr/local/include/yasmine -g -fvisibility-inlines-hidden -pipe -g -gz -fPIC -fdata-sections -ffunction-sections -isystem -Wall -Wextra -Wpedantic -Werror -fno-omit-frame-pointer -fsanitize=undefined -fno-sanitize-recover=undefined -fsanitize=address -mcx16 -ftemplate-backtrace-limit=0 -Wdisabled-optimization -Winvalid-pch -Wimplicit-fallthrough -Wlogical-op -Wformat=2 -Wno-error=deprecated-declarations -Wno-useless-cast -Wno-gnu-zero-variadic-macro-arguments -fmacro-prefix-map=/home/h1lary/userver/build_debug/= -fmacro-prefix-map=/home/h1lary/= -c -std=c++20 -resource-dir=/home/h1lary/.local/share/nvim/mason/packages/clangd/clangd_18.1.3/lib/clang/18 -- /home/h1lary/castaluck_game_server/include/gs/game/fsm/FsmFactory.hpp
I[05:41:04.975] --> textDocument/clangd.fileStatus
I[05:41:04.976] Loaded compilation database from /home/h1lary/castaluck_game_server/build_debug/compile_commands.json
I[05:41:04.976] <-- textDocument/documentLink(3)
I[05:41:04.976] <-- textDocument/inlayHint(4)
I[05:41:04.977] --> window/workDoneProgress/create(0)
I[05:41:04.977] Enqueueing 8 commands for indexing
I[05:41:04.978] <-- reply(0)
I[05:41:04.978] --> $/progress
I[05:41:04.978] --> $/progress
I[05:41:05.177] <-- textDocument/foldingRange(5)
I[05:41:05.177] --> reply:textDocument/foldingRange(5) 0 ms
I[05:41:05.279] <-- textDocument/documentSymbol(6)
I[05:41:05.334] <-- textDocument/semanticTokens/full(7)
I[05:41:05.340] --> $/progress
I[05:41:05.340] --> $/progress
I[05:41:05.340] --> $/progress
I[05:41:05.340] --> $/progress
I[05:41:05.341] --> $/progress
I[05:41:05.341] --> $/progress
I[05:41:07.421] Built preamble of size 35640020 for file /home/h1lary/castaluck_game_server/include/gs/game/fsm/FsmFactory.hpp version 29 in 2.45 seconds
I[05:41:07.422] Indexing c++20 standard library in the context of /home/h1lary/castaluck_game_server/include/gs/game/fsm/FsmFactory.hpp
I[05:41:07.422] --> textDocument/clangd.fileStatus
I[05:41:07.422] --> textDocument/clangd.fileStatus
I[05:41:07.422] --> workspace/semanticTokens/refresh(1)
I[05:41:07.423] <-- reply(1)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	ASTMatcher: Matching 'cppcoreguidelines-owning-memory' against:
	CXXMethodDecl dl::slots::game::castaluck::fsm::FsmFactory::AsyncProcessInputNotifications : </home/h1lary/castaluck_game_server/include/gs/game/fsm/FsmFactory.hpp:78:3, line:100:3>
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  clangd    0x00000000004f680b
1  clangd    0x00000000004f464e
2  clangd    0x00000000004f7196
3  libc.so.6 0x00007f8c52161520
4  clangd    0x0000000000587e20
5  clangd    0x00000000025064e3
6  clangd    0x00000000024ffa3a
7  clangd    0x00000000024f6adf
8  clangd    0x00000000024f5ff8
9  clangd    0x0000000002508159
10 clangd    0x00000000024f00b1
11 clangd    0x00000000024ec9c0
12 clangd    0x00000000024ec103
13 clangd    0x00000000024ebdef
14 clangd    0x00000000024ea2ee
15 clangd    0x000000000171a5ba
16 clangd    0x0000000002537f4b
17 clangd    0x000000000253a7d2
18 clangd    0x000000000253a45b
19 clangd    0x0000000002537e0c
20 clangd    0x000000000173880c
21 clangd    0x0000000002537e0c
22 clangd    0x000000000250bcf2
23 clangd    0x000000000250f274
24 clangd    0x000000000250ff55
25 clangd    0x000000000250f27f
26 clangd    0x0000000002511a5b
27 clangd    0x000000000250f27f
28 clangd    0x0000000002511a5b
29 clangd    0x000000000250f27f
30 clangd    0x0000000002511a5b
31 clangd    0x000000000250f27f
32 clangd    0x0000000002511a5b
33 clangd    0x000000000250f27f
34 clangd    0x0000000002511a5b
35 clangd    0x000000000250f27f
36 clangd    0x0000000002514987
37 clangd    0x000000000250f27f
38 clangd    0x00000000024e9c2d
39 clangd    0x00000000014ad164
40 clangd    0x000000000152e9b1
41 clangd    0x000000000152e44b
42 clangd    0x000000000152adf3
43 clangd    0x0000000001529860
44 clangd    0x00000000016a22a1
45 libc.so.6 0x00007f8c521b3ac3
46 libc.so.6 0x00007f8c52245850
Signalled during AST worker action: Build AST
  Filename: /home/h1lary/castaluck_game_server/include/gs/game/fsm/FsmFactory.hpp
  Directory: /home/h1lary/castaluck_game_server/build_debug
  Command Line: /usr/bin/c++ --driver-mode=g++ -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_CHRONO_DYN_LINK -DBOOST_ENABLE_ASSERT_HANDLER -DBOOST_LOCALE_DYN_LINK -DBOOST_STACKTRACE_BACKTRACE_DYN_LINK -DBOOST_STACKTRACE_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DCPPTRACE_DEMANGLE_WITH_CXXABI -DCPPTRACE_GET_SYMBOLS_WITH_LIBDWARF -DCPPTRACE_HAS_CXX_EXCEPTION_TYPE -DCPPTRACE_HAS_DL_FIND_OBJECT -DCPPTRACE_STATIC_DEFINE -DCPPTRACE_UNWIND_WITH_UNWIND -DFMT_LOCALE -DFMT_SHARED -DLIBASSERT_STATIC_DEFINE -DMOODYCAMEL_NO_THREAD_LOCAL -DPIC=1 -DUSERVER=1 -DUSERVER_NAMESPACE=userver -DUSERVER_NAMESPACE_BEGIN=namespace userver { inline namespace v2_2_rc {  -DUSERVER_NAMESPACE_END=} } -D_GLIBCXX_ASSERTIONS -I/home/h1lary/castaluck_game_server/include -I/home/h1lary/castaluck_game_server/chaotic/include -I/home/h1lary/castaluck_game_server/build_debug/chaotic/src -isystem /usr/local/include/gen -isystem /usr/local/include/gen/proto -isystem /usr/local/include/cpptrace -isystem /usr/local/include/yasmine -g -fvisibility-inlines-hidden -pipe -g -gz -fPIC -fdata-sections -ffunction-sections -isystem -Wall -Wextra -Wpedantic -Werror -fno-omit-frame-pointer -fsanitize=undefined -fno-sanitize-recover=undefined -fsanitize=address -mcx16 -ftemplate-backtrace-limit=0 -Wdisabled-optimization -Winvalid-pch -Wimplicit-fallthrough -Wlogical-op -Wformat=2 -Wno-error=deprecated-declarations -Wno-useless-cast -Wno-gnu-zero-variadic-macro-arguments -fmacro-prefix-map=/home/h1lary/userver/build_debug/= -fmacro-prefix-map=/home/h1lary/= -c -std=c++20 -resource-dir=/home/h1lary/.local/share/nvim/mason/packages/clangd/clangd_18.1.3/lib/clang/18 -- /home/h1lary/castaluck_game_server/include/gs/game/fsm/FsmFactory.hpp
  Version: 29
[Error - 5:41:07 AM] The Clang Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 5:41:07 AM] Request textDocument/documentSymbol failed.
[object Object]
[Error - 5:41:07 AM] Request textDocument/codeAction failed.
[object Object]
[Error - 5:41:07 AM] Request textDocument/documentLink failed.
[object Object]
[Error - 5:41:07 AM] Request textDocument/inlayHint failed.
[object Object]
[Error - 5:41:07 AM] Request textDocument/documentSymbol failed.
[object Object]
[Error - 5:41:07 AM] Request textDocument/semanticTokens/full failed.
[object Object]

**Comment by EugeneZelenko** [comment]
Could you please provide reproducer, preferably on https://godbolt.org?
