### ISSUE TITLE
RISC-V: getSetCC compare same value is omit

### ISSUE THREAD

**Issue by wzssyqa** [llvm/llvm-project#100529]
I find this problem when I work on fminimumnum intrinsic.

See https://github.com/llvm/llvm-project/pull/96649

```
define dso_local float @f(float noundef %a, float noundef %b) local_unnamed_addr #0 {
entry:
  %0 = tail call float @llvm.minimumnum.f32(float %a, float %b)
  ret float %0
}
```
```
./bin/clang --target=riscv64-linux-gnu -S yy.ll -O2 -o -
        li      a0, 1
        bnez    a0, .LBB0_2
```

I tested with x86_64 and mips. Both of them work well.

The problem is that we cannot believe the `CMP A,A` always true. The value of `A` may be float NaN.
For NaN vs NaN, it will always false.

**Comment by topperc** [comment]
The code is using SETEQ rather than SETOEQ. SETEQ isn't an ordered compare.

**Comment by wzssyqa** [comment]
Thanks. So let's close it.
