### ISSUE TITLE
P0892R2: explicit(bool)

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#100597]
**Link:** [https://wg21.link/p0892r2#library](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0892r2.html#:~:text=%E2%80%94end%20note%5D-,Library,-In%2020.4.2.2%20%5Bfunctions)

**Comment by jkarns275** [comment]
Going to take a stab at this :)

**Comment by jkarns275** [comment]
This has already been implemented: https://github.com/llvm/llvm-project/blob/main/clang/lib/Parse/ParseDecl.cpp#L4428

**Comment by cjdb** [comment]
Thanks! Can you please update the status page and close this issue?

**Comment by jkarns275** [comment]
I just checked and it looks like the status page does indeed reflect this, as of clang-9 it has been implemented. I don't have permission to close issues otherwise I would :p

**Comment by cjdb** [comment]
This issue is tracking the libc++ component of this paper, not Clang's.

**Comment by jkarns275** [comment]
I see - apologies, I'm not very familiar with things around here :p. I will indeed try to make these changes then.

**Comment by Rajveer100** [comment]
@cjdb 
This feature was introduced way back in C++20 I believe and should have been implemented in `libcxx` as well, I see several instances of this being used, did you mean to highlight any specific places that may have been missed out?

**Comment by jkarns275** [comment]
@Rajveer100 I noticed that it is not implemented in `std::optional` yesterday. There may be a reason for it though as the new definitions including `explicit(bool)` were detailed in the synopsis.

**Comment by cjdb** [comment]
> @cjdb This feature was introduced way back in C++20 I believe and should have been implemented in `libcxx` as well, I see several instances of this being used, did you mean to highlight any specific places that may have been missed out?

libc++ is not C++20 feature complete, so it being introduced in C++20 doesn't indicate very much. This issue is open because the libc++ status page has not marked it as completed, and thus we either need to implement it or mark it as completed in our status page.

**Comment by philnik777** [comment]
I think this should just be marked as nothing to do, since the paper basically just replaces implementation magic with a language feature.

**Comment by cjdb** [comment]
> I think this should just be marked as nothing to do, since the paper basically just replaces implementation magic with a language feature.

That's my hope too. I didn't read the library section closely enough to confirm that it only changes things in C++17.

**Comment by ldionne** [comment]
Closing as Nothing To Do since this indeed doesn't require any changes in the library.
