### ISSUE TITLE
Website broken in nōn-text browsers

### ISSUE THREAD

**Issue by mirabilos** [llvm/llvm-project#100503]
![Screenshot in Firefox](https://github.com/user-attachments/assets/87ec2882-d867-4215-8b69-2eee7c57e56b)

In `lynx`, everything is fine, of course.

(No errors in the F12 development console.)

**Comment by tbaederr** [comment]
Looks fine here

**Comment by jcranmer-intel** [comment]
Based on my analysis, the only way to get the visual glitch you have is if the ex-height of your font is somehow computed as 0. (I played around with the stylesheet to try to get it to work, and only by replacing the values of `29ex` with `0` did I get something akin to your view).

It's not a problem with the website (this is using only basic CSS 1 and HTML 4.01 stuff); it's a problem with your web browser, go file an issue with them.
