### ISSUE TITLE
[NVPTX] DebugInfo/NVPTX/*.ll tests failing on Arm buildbots

### ISSUE THREAD

**Issue by ceseo** [llvm/llvm-project#100662]
NVPTX tests related to DebugInfo started failing on Arm buildbots:

DebugInfo/NVPTX/cu-range-hole.ll
DebugInfo/NVPTX/dbg-declare-alloca.ll
DebugInfo/NVPTX/debug-addr-class.ll
DebugInfo/NVPTX/debug-info.ll
DebugInfo/NVPTX/debug-loc-offset.ll

Logs at: https://lab.llvm.org/buildbot/#/builders/122/builds/308

Most likely caused by https://github.com/llvm/llvm-project/commit/e0649a5dfc6b859d652318f578bc3d49674787a4

**Comment by nikic** [comment]
Fixed by https://github.com/llvm/llvm-project/pull/101000.

**Comment by DavidSpickett** [comment]
Thanks @nikic !
