### ISSUE TITLE
IPSCCP pass wrong denormal constant optimization

### ISSUE THREAD

**Issue by hashemthomas1** [llvm/llvm-project#100661]
Hi,

I work on a target that supports denormal-fp-math=preserve-sign,preserve-sign mode and I've encountered the following bug:
https://godbolt.org/z/Tj78Y63KM

In the link I'm using x86 top of trunk compiler with the addition of the command line flag: 
-fdenormal-fp-math=preserve-sign,preserve-sign

As you can see, a wrong constant propagation happens as one of the operands is a denormal.
The output of the optimized function is a denormal when it's supposed to be 0.0f.

After debugging, I found out that the bug happens in IPSCCP pass when it tries to simplify a binary operation.
More specifically, in (/llvm-project/llvm/lib/Transforms/Utils/SCCPSolver.cpp):
```
void SCCPInstVisitor::visitBinaryOperator(Instruction &I)
```

The following line:
```
Value *R = simplifyBinOp(I.getOpcode(), V1, V2, SimplifyQuery(DL));
```
Initializes a SimplifyQuery instance  without a context, which results in a chain of function calls reaching the function
(/llvm-project/llvm/lib/Analysis/InstructionSimplify.cpp):
```
static Constant *foldOrCommuteConstant(Instruction::BinaryOps Opcode,
                                       Value *&Op0, Value *&Op1,
                                       const SimplifyQuery &Q)
```

In case a context is **not** given, the function:
```
ConstantFoldBinaryOpOperands(Opcode, CLHS, CRHS, Q.DL);
```
and doesn't flush inputs to zero when needed.

Otherwise, if a context **is** given the function:
```
ConstantFoldFPInstOperands(Opcode, CLHS, CRHS, Q.DL, Q.CxtI);
```
is called instead, performing a correct constant fold that flushes inputs to zero.

Therefore, I think that a possible solution would be to pass the context to the SimplifyQuery initialization in (/llvm-project/llvm/lib/Transforms/Utils/SCCPSolver.cpp):
```
Value *R = simplifyBinOp(I.getOpcode(), V1, V2, SimplifyQuery(DL, &I));
```

Note that even though EarlyCSE also calls the function SimplifyInstruction, 
we don't encounter this bug because the SimplifyQuery instance is initialized with context.

**Comment by dtcxzyw** [comment]
cc @arsenm

**Comment by arsenm** [comment]
denormal-fp-math does not guarantee that a denormal will be flushed. It only indicates the denormal may be flushed in the target floating point environment. The only operation where the flush is guaranteed is the llvm.canonicalize intrinsic.

The context should be passed there, but also the constant folding shouldn't be accounting for the denromal mode if it is.

**Comment by arsenm** [comment]
> I may have over-explained, but in short, what I meant to say is that equivalent pieces of code get optimized differently due to the missing context.

Different optimizations are to be expected. In theory you should get more with the passed context 
> 
> > The context should be passed there,
> 
> As we both agree on this, how do I proceed in raising the issue up? :)

Can you open a PR with your patch adding the context, and a test that shows a behavior difference?

**Comment by hashemthomas1** [comment]
Sure!
https://github.com/llvm/llvm-project/pull/100831
