### ISSUE TITLE
[Feature request] Make it possible to compile llvm only to the architectures I care about

### ISSUE THREAD

**Issue by amitdo** [llvm/llvm-project#100825]
I want to be able ti compile Clang and LLVM just to the AMD64 and AArch64 architectures.

So the request is to add ifdefs arround code blocks which are architecture-specific.

**Comment by asl** [comment]
Consider enabling only those backends that you need. You can find more information in the documentation (e.g. `LLVM_TARGETS_TO_BUILD` variable): https://llvm.org/docs/CMake.html#frequently-used-llvm-related-variables
