### ISSUE TITLE
clang-format 19-rc1 regression: member function pointers as template arguments

### ISSUE THREAD

**Issue by vogelsgesang** [llvm/llvm-project#100841]
In our internal code base, we have a function templated with a member function pointer.
Upgrading from clang-format-17 to 19.1.0-rc1, clang-format proposed the following change, which is incorrect / unexpected

```patch
-template <llvm::Value* (llvm::IRBuilderBase::*func)(llvm::Value*, llvm::Value*, const llvm::Twine&, bool, bool)>
+template <llvm::Value* (llvm::IRBuilderBase::* func)(llvm::Value*, llvm::Value*, const llvm::Twine&, bool, bool)>
 llvm::Value* LLVMTranslator::generateArithmetic(const IRBinaryOp& op) {
 ```

**Comment by rymiel** [comment]
Bisected to 579dc7f8441a8044b92bdfa6f0db2f91301c0eed. This looks intentional, though

**Comment by owenca** [comment]
> Bisected to [579dc7f](https://github.com/llvm/llvm-project/commit/579dc7f8441a8044b92bdfa6f0db2f91301c0eed). This looks intentional, though

Yeah, IMO it's a bug fix rather than a regression.

**Comment by tru** [comment]
Can this be closed or removed from the LLVM 19.x milestone_

**Comment by vogelsgesang** [comment]
Yes, given this was an intentional change, let's close it

**Comment by owenca** [comment]
Duplicate of #93678.
