### ISSUE TITLE
Merge #99276 to resolve the layering violation

### ISSUE THREAD

**Issue by chapuni** [llvm/llvm-project#100938]
/cherry-pick 25efb746d907ce0ffdd9195d191ff0f6944ea3ca 6d12b3f67df429bffff6e1953d9f55867d7e2469 5bf085921ec23e5fa1ea4a159c55a618a9299ce6

**Comment by h-vetinari** [comment]
/cherry-pick 25efb746d907ce0ffdd9195d191ff0f6944ea3ca 6d12b3f67df429bffff6e1953d9f55867d7e2469 5bf085921ec23e5fa1ea4a159c55a618a9299ce6

**Comment by chapuni** [comment]
@h-vetinari Thanks.
