### ISSUE TITLE
[llgo] Release archive does not contain llgo

### ISSUE THREAD

**Issue by xaionaro** [llvm/llvm-project#101]
Hello.

I've failed to build `llgo` (see https://github.com/llvm/llvm-project/issues/100), so I tried to just install a pre-built release (https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/clang+llvm-9.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz). However it appears it does not contain `llgo` binaries. Could `llgo` be added to releases?

**Comment by xgupta** [comment]
llgo is not in the repo anymore.
