### ISSUE TITLE
Incorrect Transformations by InstCombine due to wrong aliasing information in TypeBasedAliasAnalysis

### ISSUE THREAD

**Issue by vedantparanjape-amd** [llvm/llvm-project#101164]
Type Based Alias Analysis emits metadata nodes in the frontend, and an analysis pass in the middle-end does access tag matching to determine if two pointers alias or not. TBAA metadata is only attached to Load and Store Instructions.

But with the enhanced struct path TBAA (enabled by -new-struct-path-tbaa), the TBAA nodes are also added to memory aggregates that might cause two pointers to aliase due to their semantics. So, memcpy is usually tagged with TBAA nodes. This happens here in the Clang frontend.

https://github.com/llvm/llvm-project/blob/bd6e324b67cdadde2593327753e99782146d9bf8/clang/lib/CodeGen/CGExprAgg.cpp#L2200)
 
Even though memcpy is tagged with TBAA metadata nodes, the TypeBasedAliasAnalysis is not able to correctly find Alias Sets due to the TBAA node structure being slightly different. I have two testcases where AA returns NoAlias for a case with a Load and Memcpy when they actually are Alias/MayAlias.

Reproducer: https://godbolt.org/z/7vK714zWx

Referring to the godbolt testcase. Take a look at L15 in the IR tab, an Add %0, %1 is converted to a Add %0, %0, which in turn is converted to Shl %0, 1. As it thinks that %0 and %1 (Load which was eliminated) are the same data. But, since we have copied b into a, that’s not true. This happens as TBAA tells that %0 and %1 are NoAlias, which is wrong.

Confirmed the issue after discussion with author of enhanced TBAA (@kosarev)

This same issue was seen even in GVN, have created a detailed page to list the bugs: https://discourse.llvm.org/t/type-based-alias-analysis-giving-incorrect-aliasing-information-with-enhanced-tbaa-format/79455

**Comment by vedantparanjape-amd** [comment]
I tried to prove this as incorrect through alive2, but it seems to not support TBAA.

**Comment by dtcxzyw** [comment]
cc @fhahn

**Comment by antoniofrighetto** [comment]
Closing this as should be solved by https://github.com/llvm/llvm-project/commit/222d3b031f6bf39873550a34152b9d05b9b6578a.

**Comment by kosarev** [comment]
> Reproducer: https://godbolt.org/z/7vK714zWx

`a[i].b` now gets reloaded after the aggregate assignment:

```
define dso_local noundef i32 @f(t*, t*, int)(ptr nocapture noundef %a, ptr nocapture noundef readonly %b, i32 noundef %i) local_unnamed_addr #0 !dbg !10 {
entry:
    #dbg_value(ptr %a, !26, !DIExpression(), !30)
    #dbg_value(ptr %b, !27, !DIExpression(), !30)
    #dbg_value(i32 %i, !28, !DIExpression(), !30)
  %idxprom = sext i32 %i to i64, !dbg !31
  %arrayidx = getelementptr inbounds %struct.t, ptr %a, i64 %idxprom, !dbg !31
  %b1 = getelementptr inbounds nuw i8, ptr %arrayidx, i64 8, !dbg !32
  %0 = load i32, ptr %b1, align 4, !dbg !32
    #dbg_value(i32 %0, !29, !DIExpression(), !30)
  %arrayidx3 = getelementptr inbounds %struct.t, ptr %b, i64 %idxprom, !dbg !38
  tail call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 4 dereferenceable(12) %arrayidx, ptr noundef nonnull align 4 dereferenceable(12) %arrayidx3, i64 12, i1 false), !dbg !39
  %1 = load i32, ptr %b1, align 4, !dbg !44
  %add = add nsw i32 %1, %0, !dbg !45
    #dbg_value(i32 %add, !29, !DIExpression(), !30)
  ret i32 %add, !dbg !46
}
```

**Comment by vedantparanjape-amd** [comment]
It also fixes another testcase (caused due to gvn): https://godbolt.org/z/obGqMMh7E
