### ISSUE TITLE
clang format CompactNamespaces support for migrating to c++17 namespaces

### ISSUE THREAD

**Issue by bmaurer** [llvm/llvm-project#101245]
Clang format has a CompactNamespaces option that turns 

```
namespace A {
namespace B {
namespace C { 
...
} } }
```

into 

```
namespace A { namespace B { namespace C { 
...
} } }
```

Ideally, there'd be a configuration that would use c++17 support to format as:

```
namespace A::B::C { ... }
```

Clang format accepts the c++17 style, but does help not migrate to it.

**Comment by EugeneZelenko** [comment]
Clang-tidy do this migration. See https://clang.llvm.org/extra/clang-tidy/checks/modernize/concat-nested-namespaces.html. There are other `modernize` checks.
