### ISSUE TITLE
[DXIL] Specify buffer and handle related DXIL Ops and implement lowering to compile particle_life.hlsl  

### ISSUE THREAD

**Issue by bharadwajy** [llvm/llvm-project#101204]
DXC compilation of `particle_lide.hlsl` output contains the following handle and buffer related DXIL ops. 

CreateHandle (Opcode 57)
CbufferLoadLegacy (Opcode 59)
BufferLoad (Opcode 68)
BufferStore (Opcode 69)

1. Specify their properties in `DXIL.td` and 
2. Implement DXIL lowering support.

**Comment by damyanp** [comment]
This is already covered by:
- #91367 
- #91366
- #75833
