### ISSUE TITLE
clang rejects reusing names in unexported variables between modules

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#101396]
Given the following three translation units:

```c++
export module a;

constexpr int x = 0;

export void a() {
	(void)x;
}
```

```c++
export module b;

constexpr int x = 0;

export void b() {
	(void)x;
}
```

```c++
import a;
import b;
```

And compiling with

```shell
clang++ -std=c++23 -x c++-module -fmodule-output=a.pcm --precompile -c a.cpp
clang++ -std=c++23 -x c++-module -fmodule-output=b.pcm --precompile -c b.cpp
clang++ -std=c++23 -fmodule-file=a=a.pcm -fmodule-file=b=b.pcm -c c.cpp
```

causes clang to fail with

```console
In file included from c.cpp:1:
a.cpp:3:15: error: declaration 'x' attached to named module 'a' can't be attached to other modules
    3 | constexpr int x = 0;
      |               ^
b.cpp:3:15: note: also found
    3 | constexpr int x = 0;
      |               ^
1 error generated.
```

I believe this code should be accepted and have the same behavior as if `x` were declared `static` in both `module a` and `module b`. `x` has module linkage in both `module a` and `module b`. Because of that, and based on https://eel.is/c++draft/basic.link#8, the two declarations of `x` are not declaring the same entity and thus the error is incorrect.

**Comment by ChuanqiXu9** [comment]
This may be duplicated with https://github.com/llvm/llvm-project/issues/90154.

And I don't have an expectation that how and when this problem will be solved properly. It is somewhat fundamental.

The workaround suggestion may be: 1. use namespaces. 2.  Use static variable with Reduced BMI (https://clang.llvm.org/docs/StandardCPlusPlusModules.html#reduced-bmi).
