### ISSUE TITLE
clang does not support initializing constant reference member with literal

### ISSUE THREAD

**Issue by Ming-3364** [llvm/llvm-project#101347]
The following simple test is currently rejected by clang:

```c++
struct test {
  test() : x(0) {}
  const int &x;
} ;
```
Assigning a temporary value to a corresponding constant reference variable is allowed in C++. Accordingly, the test should be well-formed.

Both GCC and MSVC accept it:

[https://godbolt.org/z/dP7h4dG63](https://godbolt.org/z/dP7h4dG63)

**Comment by zygoloid** [comment]
This example violates https://eel.is/c++draft/class.base.init#8; clang is correct to reject it.
