### ISSUE TITLE
Clang rejects valid program involving point of instantiaion at end of file

### ISSUE THREAD

**Issue by ranaanoop** [llvm/llvm-project#101311]
The following valid program(afaik) is rejected by clang in c++20. [Demo](https://godbolt.org/z/sWfT97TPz)

```
#include <algorithm>
#include <vector>

struct Foo
{
};

struct FooArray
{
    std::vector<Foo> a;
};

bool operator<(const FooArray& a, const FooArray& b)
{
    return std::lexicographical_compare(std::begin(a.a), std::end(a.a), std::begin(b.a), std::end(b.a));
}

bool operator<(const Foo& a, const Foo& b)
{
    return false;
}
```

Note that clang in c++17 accepts this but in c+20 rejects it. A regression maybe?

**Comment by MitalAshok** [comment]
[[temp.point]p1](https://wg21.link/temp.point#1.sentence-2):

> Otherwise, the point of instantiation for such a specialization immediately follows the namespace scope declaration or definition that refers to the specialization.

There are two points of instantiation: The one after the definition of `bool operator<(const FooArray& a, const FooArray& b);`, and the one at the end of the translation unit.

[[temp.point]p7](https://wg21.link/temp.point#7.sentence-4):

> If two different points of instantiation give a template specialization different meanings according to the [one-definition rule](https://wg21.link/basic.def.odr), the program is ill-formed, no diagnostic required.

Clang is free to instantiate `std::lexicographical_compare<std::vector<Foo>::const_iterator, std::vector<Foo>::const_iterator>` at either point. This program seems to be ill-formed NDR because these two points differ.

The difference between C++17 and C++20 is that `lexicographical_compare` is now `constexpr`, which Clang seems to instantiate more eagerly: https://godbolt.org/z/qjPqG9ba5

**Comment by ranaanoop** [comment]
@MitalAshok  There is no ODR violation here. No different meaning as per odr.

**Comment by MitalAshok** [comment]
[[basic.def.odr]p(15.10)](https://wg21.link/basic.def.odr#15.10):

> In each such definition, the overloaded operators referred to, the implicit calls to conversion functions, constructors, operator new functions and operator delete functions, shall refer to the same function.

At the end-of-TU POI, the overloaded operator refers to the defined `operator<(const Foo&, const Foo&)`. At the first POI, it does not refer to the same function (since it doesn't refer to any function, overload resolution fails)

**Comment by AlanVoore** [comment]
@MitalAshok  But shouldn't [temp.inst](https://eel.is/c++draft/temp.inst#5) make this implementation specific? 

> Unless a function template specialization is a declared specialization, the function template specialization is implicitly instantiated when the specialization is referenced in a context that requires a function definition to exist or if the existence of the definition affects the semantics of the program[.](https://eel.is/c++draft/temp.inst#5.sentence-1)

**Comment by MitalAshok** [comment]
Also related: https://cplusplus.github.io/CWG/issues/2497.html

@AlanVoore Why would that make it implementation specific?  
My understanding is that `std::lexicographical_compare<std::vector<Foo>::const_iterator, std::vector<Foo>::const_iterator>` is not used in such a way that its definition is required here (i.e., you could have just had a forward declaration of the template). And even if it wasn't, that implicit instantiation still has two points of instantiation, which were IF-NDR.
