### ISSUE TITLE
[clang-format] Allow for Short namespaces to be on the same line

### ISSUE THREAD

**Issue by tiagomacarios** [llvm/llvm-project#101363]
[clang-format: Add "AllowShortNamespacesOnASingleLine" option](https://reviews.llvm.org/D11851)
Proposed adding a AllowShortNamespacesOnASingleLine option, but the patch did not make it in. Would it be possible for us to consider applying that patch or looking at other ways to accomplish the same functionality?

**Comment by mydeveloperday** [comment]
I would recommend supporting

`namespace A { namespace B { class C; }}`

as well as

`namespace A {  class C; }}`

**Comment by galenelias** [comment]
I am able to pick this up, however there are two edge case I'm not sure how to solve:

```cpp
// What happens if we format with '{BasedOnStyle: llvm, ColumnLimit: 30}'?
namespace A { namespace B { class C; }}

// Option 1
namespace A {
namespace B {
class C;
}
}

//Option 2 - I assume this one
namespace A {
namespace B { class C; }
}
```

**Comment by JessehMSFT** [comment]
Our main desire for `AllowShortNamespacesOnASingleLine` is to reduce the number of lines these declarations take up. I agree that **Option 2** most closely aligns with that goal.

We're also conscious that clang-tidy's [modernize-concat-nested-namespaces](https://clang.llvm.org/extra/clang-tidy/checks/modernize/concat-nested-namespaces.html#modernize-concat-nested-namespaces) could be a useful tool to prevent hitting column limits in this scenario.
