### ISSUE TITLE
Use LLVM VCS scripts and/or cmake modules instead of Subversion specific CMake module in clang CMake scripts

### ISSUE THREAD

**Issue by brycelelbach** [llvm/llvm-project#10142]
|  |  |
| --- | --- |
| Bugzilla Link | [9770](https://llvm.org/bz9770) |
| Version | trunk |
| OS | Linux |
| CC | @oscarfv,@pageexec |

## Extended Description 
The GetSourceVersion/GetRepositoryPath scripts or the LLVM/clang CMake module for retrieving git/svn version metadata should be used in lib/Basic/CMakeLists.txt instea of the Subversion CMake package.

**Comment by arsenm** [comment]
svn is no more
