### ISSUE TITLE
[HLSL][DirectX] Implement llvm.dx.getDimensions for buffers and lower it to the dxil op

### ISSUE THREAD

**Issue by damyanp** [llvm/llvm-project#101579]
AC:
* GetDimensions() methods added to the buffer types
* Add builtin, LLVM intrinsic and DXIL op
* Lowering to SPIR-V considered

**Comment by hekota** [comment]
Split into 2 tasks:
Front end: https://github.com/llvm/llvm-project/issues/112984
Back end: https://github.com/llvm/llvm-project/issues/112982

Closing as duplicate.
