### ISSUE TITLE
[RISCV] float to int conversion intrinsics are incorrectly enabled with Zvfhmin

### ISSUE THREAD

**Issue by topperc** [llvm/llvm-project#101526]
We have this code in SemaRISCV.cpp to disable f16 intrinsics without Zvfh.

```
      if (BaseType == BasicType::Float16) {                                      
        if ((Record.RequiredExtensions & RVV_REQ_Zvfhmin) == RVV_REQ_Zvfhmin) {  
          if (!TI.hasFeature("zvfhmin"))                                         
            continue;                                                            
        } else if (!TI.hasFeature("zvfh")) {                                     
          continue;                                                              
        }                                                                        
      } 
```

For the conversion intrinsics, the BaseType is integer, not floating point, so we miss this check if any of the source operands are Float16.

This causes a crash with Zvfhmin https://godbolt.org/z/Khfx8j6jW

CC: @jacquesguan @kito-cheng @rofirrim

**Comment by 4vtomat** [comment]
I guess it's checked in `checkRVVTypeSupport`, maybe we can remove this check?

**Comment by topperc** [comment]
> I guess it's checked in `checkRVVTypeSupport`, maybe we can remove this check?

The type checking checks Zvfhmin. So the intrinsics are incorrectly allowed with Zvfhmin.

**Comment by 4vtomat** [comment]
> Zvfhmin

Shouldn't. the float to int conversion be enabled with `Zvfhmin`? or it needs `Zvfh`?

**Comment by topperc** [comment]
> > The type checking checks Zvfhmin. So the intrinsics are incorrectly allowed with Zvfhmin.
> 
> Shouldn't. the float to int conversion be enabled with `Zvfhmin`? or it needs `Zvfh`?

Zvfhmin only includes vfncvt.f.f.w and vfwcvt.f.f.v.

**Comment by 4vtomat** [comment]
Oh, ok, let me fix it.
