### ISSUE TITLE
[Clang] Diagnose `extern "C++" int main()`

### ISSUE THREAD

**Issue by MitalAshok** [llvm/llvm-project#101512]
This currently just seems to be ignored (the name is not mangled).  
It is explicitly disallowed by https://eel.is/c++draft/basic.start.main#3.sentence-5

> The `main` function shall not be declared with a *linkage-specification*.

This includes

```cpp
extern "C++" { int main(); }
```

This is also technically ill-formed

```cpp
extern "C" int main();
```

but it seems to be used in some places:

https://github.com/llvm/llvm-project/blob/98e4413a38f286147b863a6ead9625228ab0ec7d/libc/startup/linux/do_start.cpp#L23
https://github.com/llvm/llvm-project/blob/98e4413a38f286147b863a6ead9625228ab0ec7d/libc/startup/gpu/nvptx/start.cpp#L15

So this should probably just be a warning, not an error.

**Comment by shafik** [comment]
Using code-blocks are usually better than just using backticks because they allow for easy copy and paste, especially if there is not godbolt link.

**Comment by shafik** [comment]
Looks like implementation accept this some with diagnostics, gcc gives a diagnostic w/ `-pedantic` we should probably as well.

**Comment by AaronBallman** [comment]
That's a very new GCC diagnostic -- 14.1 doesn't issue it. But I agree, Clang should accept and diagnose as an extension same as GCC here. This seems like a good first issue; in `CheckMain()` (https://github.com/llvm/llvm-project/blob/83e6d872cfbb98b0b1e9a5080afe1e1c8cf69237/clang/lib/Sema/SemaDecl.cpp#L12212) we need a new test for language linkage (`FD->getLanguageLinkage() != NoLanguageLinkage`) and issue a pedantic diagnostic.

**Comment by a-tarasyuk** [comment]
can I be assigned to this issue?

**Comment by AaronBallman** [comment]
> can I be assigned to this issue?

Absolutely!

**Comment by pinskia** [comment]
> That's a very new GCC diagnostic -- 14.1 doesn't issue it. But I agree, Clang should accept and diagnose as an extension same as GCC here. This seems like a good first issue; in `CheckMain()` (

Yes it was done in https://gcc.gnu.org/r15-762 . Mostly to support modules, because you cannot define main in a module either.

https://gcc.gnu.org/git/?p=gcc.git;a=blob_plain;f=gcc/testsuite/g%2B%2B.dg/parse/linkage5.C
https://gcc.gnu.org/git/?p=gcc.git;a=blob_plain;f=gcc/testsuite/g%2B%2B.dg/parse/linkage6.C

are the 2 new non-module testcases.

https://gcc.gnu.org/git/?p=gcc.git;a=blob_plain;f=gcc/testsuite/g%2B%2B.dg/modules/main-1.C

is the new module one.
