### ISSUE TITLE
Neither origin/release/19.x nor 19.1-rc1 passes `cmake` build step for macOS 14.5 w/ Apple Silicon M2

### ISSUE THREAD

**Issue by catull** [llvm/llvm-project#101503]
They both initially fail with 

```
.....
-- LIBC_CONF_MEMSET_X86_USE_SOFTWARE_PREFETCHING: OFF
-- LIBC_CONF_STRING_UNSAFE_WIDE_READ: OFF
-- LIBC_CONF_ENABLE_PID_CACHE: ON
-- LIBC_CONF_ENABLE_TID_CACHE: ON
-- Writing config doc to llvm-project/libc/docs/configure.rst
-- Set CPU features:
-- Compiler features available: float16
-- Performing Test LIBC_CC_SUPPORTS_PATTERN_INIT
-- Performing Test LIBC_CC_SUPPORTS_PATTERN_INIT - Success
-- Performing Test LIBC_CC_SUPPORTS_NOSTDLIBPP
-- Performing Test LIBC_CC_SUPPORTS_NOSTDLIBPP - Success
-- Performing Test LIBC_CC_SUPPORTS_NOSTDLIBINC
-- Performing Test LIBC_CC_SUPPORTS_NOSTDLIBINC - Success
CMake Error at llvm-project/libc/CMakeLists.txt:353 (message):

  llvm-project/libc/config/darwin/entrypoints.txt
  file not found.


-- Configuring incomplete, errors occurred!
```

Renaming the folder libc/config/darwin/**arm** => libc/config/darwin/**aarch64** gets past this hurdle.
Only to fail once more later on with:

```
-- Compiling and running to test HAVE_PTHREAD_AFFINITY
-- Performing Test HAVE_PTHREAD_AFFINITY -- failed to compile
-- Configuring done (41.8s)
CMake Error at llvm-project/libc/test/UnitTest/CMakeLists.txt:41 (add_dependencies):
  The dependency target "libc.src.__support.OSUtil.osutil" of target
  "LibcTest.unit" does not exist.
Call Stack (most recent call first):
  llvm-project/libc/test/UnitTest/CMakeLists.txt:52 (add_unittest_framework_library)


CMake Error at llvm-project/libc/test/UnitTest/CMakeLists.txt:46 (add_dependencies):
  The dependency target "libc.src.__support.OSUtil.osutil" of target
  "LibcTest.hermetic" does not exist.
Call Stack (most recent call first):
  llvm-project/libc/test/UnitTest/CMakeLists.txt:52 (add_unittest_framework_library)


-- Generating done (5.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

This behaviour is seen on:

- `main`
- `origin/release/19.x`
- `llvm-project-19.1.0-rc1.src.tar.xz`

**Comment by AaronBallman** [comment]
CC @jhuber6

**Comment by jhuber6** [comment]
I think `arm` and `aarch64` are different. But for whatever reason we only have entrypoints for `arm`. You can probably go ahead and copy that folder to `aarch64` and then add whatever entrypoints you can get to work.

**Comment by asl** [comment]
> I think `arm` and `aarch64` are different. But for whatever reason we only have entrypoints for `arm`. You can probably go ahead and copy that folder to `aarch64` and then add whatever entrypoints you can get to work.

Given that the default build is broken, should this platform just disabled by default?

**Comment by AaronBallman** [comment]
Yeah, this seems like something we need to work out-of-the-box for the release because of the build errors.

**Comment by michaelrj-google** [comment]
Given that we don't have consistent support for MacOS right now I'm fine with disabling it as a libc target for the release.

**Comment by jhuber6** [comment]
> Given that we don't have consistent support for MacOS right now I'm fine with disabling it as a libc target for the release.

I think the correct solution is to make a reasonable default is that if there's no file found under the expected name we just default to `set(LIBC_ENABLED_ENTRYPOINTS "")`.

**Comment by tru** [comment]
Do we need to fix this still? I haven't seen a PR for this yet?

**Comment by catull** [comment]
In `release/19.x` as of today, neither of the errors mentioned happens.

Interestingly, libc/config/darwin only contains a folder for `arm` and `x86_64`.
The cmake files must have been adapted for the build to pass.

Although I have not checked with llvm-project-19.1.0-rc2.src.tar.xz, I'll close this ticket.
