### ISSUE TITLE
2 errors given for multiple function definition declared at class scope.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#10153]
|  |  |
| --- | --- |
| Bugzilla Link | [9781](https://llvm.org/bz9781) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
given test.cpp:
class A {
   void foo(){}
   void foo(){}
};

clang  test.cpp
test.cpp(5) :  error: class member cannot be redeclared
   void foo(){}
        ^
test.cpp(4) :  note: previous declaration is here
   void foo(){}
        ^
test.cpp(5) :  error: redefinition of 'foo'
   void foo(){}
        ^
test.cpp(4) :  note: previous definition is here
   void foo(){}
        ^
2 errors generated.

there should be only 1 error here.

**Comment by Endilll** [comment]
Fixed in Clang 3.7
https://godbolt.org/z/njePGYzM8
