### ISSUE TITLE
Extending LLDB to work on AIX

### ISSUE THREAD

**Issue by Dhruv-Srivastava-IBM** [llvm/llvm-project#101657]
Hi Community Members, 

We have Implemented the necessary code changes required to run LLDB on AIX.

Since AIX wants to be the part of LLDB community, and want their feature enhancements to work with the Community
to extend support of LLDB to AIX as well, we would like to contribute changes required to run LLDB on AIX via a Pull Request.

Kindly let us know if we can. Once we raise the PR, also let us know if we can have a better design to the code changes from your experience, so that we can make it easy to maintain for you and AIX. We would like our code to be a part of the next release of the LLDB Project and actively involve in maintaining LLDB on AIX and the Community.

Thanks & Regards, 
Dhruv Srivastava
IBM

**Comment by asl** [comment]
You do not need a permission to open a PR provided that is follows LLVM's Contribution Guidelines: https://llvm.org/docs/Contributing.html#how-to-submit-a-patch

If you'd need to discuss something, you can always submit and RFC to LLVM's Discourse

**Comment by DavidSpickett** [comment]
> If you'd need to discuss something, you can always submit and RFC to LLVM Discourse

Yes, please start a thread in https://discourse.llvm.org/c/subprojects/lldb/8 going over what AIX is, your goals in doing this support, how it will be tested, who the code owners will be, link to some WIP changes and any other information you think will be helpful for us to understand the platform.

**Comment by Dhruv-Srivastava-IBM** [comment]
Okay Thanks for the inputs. 
I will start a conversation regarding the same on discourse and mention the details over there.
