### ISSUE TITLE
[clang] Crash on templated type with address space

### ISSUE THREAD

**Issue by jdoerfert** [llvm/llvm-project#101685]
Clang crashes with a TypeLocBuilder assertion when run on this code (https://godbolt.org/z/or16hfTzf), no other command line options necessary:

```
template <int AS>
using ASPtrTy = void [[clang::address_space(AS)]] *;

template <int AS>
struct EntryTy {
    ASPtrTy<AS> Base;
};
```
> clang::TypeLoc clang::TypeLocBuilder::pushImpl(clang::QualType, size_t, unsigned int): Assertion `TLast == LastTy && "mismatch between last type and new type's inner type"' failed.

**Comment by Sirraide** [comment]
We’re hitting this assertion here in (`TreeTransform::TransformDependentAddressSpaceType`):
```c++
assert(TLast == LastTy &&
         "mismatch between last type and new type's inner type");
```
Something seems pretty wrong here, because if I print the two types, I get:
```
LastTy: NULL TYPE
TLast: void
```

**Comment by Sirraide** [comment]
I think we might just be forgetting to pass along the `TLB` to `TransformType`. Doing that fixes this; gonna run the test suite to make sure nothing else breaks and then open a pr for this.
