### ISSUE TITLE
[Clang] `requires` clause with parameter pack expansion fails equivalence requirements for redeclarations

### ISSUE THREAD

**Issue by yuxuanchen1997** [llvm/llvm-project#101735]
Upstream clang currently rejects the following program:
```
#include <concepts>
#include <utility>

template <typename T>
class A {
  template <typename... Ts>
  void method(Ts&... ts)
    requires requires (T t) {
      { t.method(std::forward<Ts>(ts)...) } -> std::same_as<void>;
    };
};

template <typename T>
template <typename... Ts>
void A<T>::method(Ts&... ts)
  requires requires (T t) {
    { t.method(std::forward<Ts>(ts)...) } -> std::same_as<void>;
  } {}
```
The error message is: 
```
test.cc:15:12: error: out-of-line definition of 'method' does not match any declaration in 'A<T>'
   15 | void A<T>::method(Ts&... ts)
      |            ^~~~~~
1 error generated.
```
After getting rid of the `std::forward<Ts>(ts)...`, the error went away. 
On an older clang (17-18) this caused a crash. GCC and MSVC accepted this program. 

See Godbolt for backtrace: https://godbolt.org/z/YoKM3bzvK

**Comment by yuxuanchen1997** [comment]
If someone recognises this issue from the past and can point me to the patch that fixed the crash (but probably wrongfully rejected parameter pack expansions), I'd really appreciate that.

**Comment by zyn0217** [comment]
Probably https://github.com/llvm/llvm-project/pull/80594

**Comment by zyn0217** [comment]
Without headers:
```cpp
template <class, class>
concept True = true;

template <typename T>
class A {
  template <typename... Ts>
  void method(Ts&... ts)
    requires requires (T t) {
      { t.method(static_cast<Ts>(ts)...) } -> True<void>;
    };
};

template <typename T>
template <typename... Ts>
void A<T>::method(Ts&... ts)
  requires requires (T t) {
    { t.method(static_cast<Ts>(ts)...) } -> True<void>;
  } {}

```

**Comment by zyn0217** [comment]
I took a stab at it and I found it a bit annoying.

We profile the requires expressions to determine whether they're identical. So the problem occurs in the template parameter `Ts` referenced by `static_cast`. (In fact, `static_assert` merely gives a chance to refer  to template parameter packs; C style casts i.e. `(Ts)(ts)...` would run into the same problem)

We substitute the parameter pack with `SubstTemplateTypeParmPackType` if we're in an unexpanded context. `SubstTemplateTypeParmPackType` requires an `AssociatedDecl` that comes from the substituting template argument lists. The template arguments are collected by `getTemplateInstantiationArgs()`, so the `AssociatedDecl` for the out-of-line `A<T>::method()` and its inline declaration are not the same, although they should have shared one CanonicalDecl, which is the inline declaration; however this constraint checking is just used to determine if the out-of-line declaration is a redeclaration, which only then sets up the canonical declaration if the checking succeeds. Therefore, while checking, they had different CanonicalDecls which were themselves. Hence the false result in profiling and the bogus diagnostic.

**Comment by yuxuanchen1997** [comment]
> In fact, static_assert merely gives a chance to refer to template parameter packs;

You wanted to say `static_cast`, right?

**Comment by zyn0217** [comment]
Yeah, and sorry for the typo... (`static_assert` is always the first off the top of my head)

I think I will have a workaround for it - just let me run the libc++ tests to ensure they don't regress.

**Comment by zyn0217** [comment]
I began to understand why this is not the case for non-packs.

```cpp
template <typename T> class A {
  template <typename Ts>
  void method(Ts &ts)
    requires requires(T t) { t.method(static_cast<Ts>(ts)); };
};

template <class T>
template <typename Ts>
void A<T>::method(Ts &ts)
  requires requires(T t) { t.method(static_cast<Ts>(ts)); }
{}
```

Fundamentally, the `SubstTemplateTypeParmType` would have a canonical type `TemplateTypeParmType` that doesn't involve `AssociatedDecl`, so the two requires expressions would profile into the same result. While this is not the case for `SubstTemplateTypeParmPackType`, we still preserve the `SubstTemplateTypeParmPackType` as its canonical type, which means the AssociatedDecl would make a difference when hashing.

@mizvekov Is there any chance we could give up using the `Subst*` type as `SubstTemplateTypeParmPackType`'s canonical type? I mean, can we still use `TemplateTypeParmPackType` as the `Subst`'s canonical?

**Comment by mizvekov** [comment]
I don't think you can drop all that information from SubstTemplateTypeParmPackType's canonical type.
The type pack itself is essential, and if that becomes sugar it means it other parts of clang can assume it can
be lost without serious consequences.

By the point we are profiling the requires expression, we know everything else matches, right?
So if they are not identical, that's just an error, correct?

If so, could we set them as redeclarations earlier, before building the requires expression, and then. check that they match.
If they don't match, we then just set the redeclaration as invalid?

**Comment by zyn0217** [comment]
OK I figured out a solution here: We used to establish a `SubstTemplateTypeParmPackType` because we hold off the function parameter's expansion, which is because we have mapped the parameter pack to a non-pack expansion in the instantiation scope.

We should instantiate parameter packs to expansions prior to the substitution.
