### ISSUE TITLE
[clang++] Use of incomplete class in destructor `requires` concept fails

### ISSUE THREAD

**Issue by laverdet** [llvm/llvm-project#101832]
https://godbolt.org/z/Pz7KEj73e

```c++
#include <concepts>

class foo;

template <class T>
class bar {
		~bar()
			requires std::destructible<T>
		{}
};

int test(bar<foo>*) {
	return 0;
}

int main() {
	bar<foo>* ptr = nullptr;
	test(ptr);
	return 0;
}
```

```
$ /clang/bin/clang++ a.cc -std=c++23
/workspace/a.cc:6:7: error: no viable destructor found for class 'bar<foo>'
    6 | class bar {
      |       ^
/workspace/a.cc:18:2: note: in instantiation of template class 'bar<foo>' requested here
   18 |         test(ptr);
      |         ^
/workspace/a.cc:7:3: note: candidate function not viable: constraints not satisfied
    7 |                 ~bar()
      |                 ^
/workspace/a.cc:8:13: note: because 'foo' does not satisfy 'destructible'
    8 |                         requires std::destructible<T>
      |                                  ^
/usr/lib/gcc/aarch64-linux-gnu/14/../../../../include/c++/14/concepts:155:28: note: because '__detail::__destructible<foo>' evaluated to false
  155 |     concept destructible = __detail::__destructible<_Tp>;
      |                            ^
1 error generated.

$ /clang/bin/clang++ --version      
clang version 19.0.0git (https://chromium.googlesource.com/external/github.com/llvm/llvm-project 084e2b53d22c11e013b0a495b65d39aa7f934048)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /clang/bin
```

**Comment by MitalAshok** [comment]
`std::destructible<T>` is false because the type is incomplete.

The type has to be completed to do ADL for the unqualified call `test`. (Clang does accept `::test(ptr);` or `(test)(ptr);`)

`bar` has no viable prospective destructor.

https://eel.is/c++draft/class.dtor#4

> At the end of the definition of a class, overload resolution is performed among the prospective destructors declared in that class with an empty argument list to select the *destructor* for the class, also known as the *selected destructor*. The program is ill-formed if overload resolution fails.

I think this should be ill-formed. I've opened a GCC bug about this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116206

**Comment by pinskia** [comment]
> I think this should be ill-formed. I've opened a GCC bug about this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116206

It was already filed as https://gcc.gnu.org/bugzilla/PR113755

**Comment by laverdet** [comment]
Thank you for the insight Mital & Andrew!
