### ISSUE TITLE
[LLVM:] Optimization remarks are generated which aren't legal YAML

### ISSUE THREAD

**Issue by OfekShilon** [llvm/llvm-project#101839]
As a toy example this cpp source:
```cpp
#include <vector>

void f() {
   std::vector<float> buf(100);
   float * p = nullptr;
}
```
When built with clang (tested back until clang15) with the switches
```
-fsave-optimization-record -O2 -std=c++20
```

Generartes an opt.yaml file which includes the illegal document -

```
...
         prologepilog
Name:            StackSize
DebugLoc:        { File: example.cpp, Line: 3, Column: 0 }
Function:        _Z1fv
Args:
  - NumStackBytes:   '0'
  - String:          ' stack bytes in function '''
  - Function:        _Z1fv
  - String:          ''''
...
--- !Analysis
```

(the first `...` is part of the doc, and is expected to be followed by a `---` line).

You can verify e.g. by pasting the entire yaml contents into https://www.yamllint.com/

**Comment by OfekShilon** [comment]
The line
```
         prologepilog
```
Should just be
```
--- !prologepilog
```

**Comment by OfekShilon** [comment]
If the line
```
         prologepilog
```
was fixed to 
```
--- !prologepilog
```
This would have formed a valid YAML, but this isn't a documented opt-remark type and I'm not sure what was the intention here.  I imagine "Analysis" remark would be most suitable.

**Comment by tschuett** [comment]
```
> clang++ -fsave-optimization-record -O2 -std=c++20 -c tmp.cpp
```
gave me a valid tmp.opt.yaml, where tmp.cpp is your example.
```
--- !Passed
Pass:            inline
Name:            AlwaysInline
..
```


Question: you didn't show the full command-line?

**Comment by tschuett** [comment]
I was too fast:
```
...
--- !Analysis
Pass:            prologepilog
Name:            StackSize
DebugLoc:        { File: tmp.cpp, Line: 3, Column: 0 }
Function:        _Z1fv
Args:
  - NumStackBytes:   '8'
  - String:          ' stack bytes in function '''
  - Function:        _Z1fv
  - String:
```

The prologepilog section is valid YAML.

**Comment by OfekShilon** [comment]
Apologies - upon more investigation this was a compiler-explorer internal issue (simultaneous double write of the opt.yaml file). Closing.
