### ISSUE TITLE
Detect dangling references for C++20's Parenthesized Aggregate Initialization 

### ISSUE THREAD

**Issue by usx95** [llvm/llvm-project#101957]
```cpp
struct MyThing {
    const std::string& s;
};

MyThing makeThing(std::string s) {
    return MyThing(s);
}
```
https://godbolt.org/z/6335YcKMM

This also doesn't work for `gsl::Pointer` types like `string_view` instead of `const std::string&`. https://godbolt.org/z/8bcaxTqjY

This is different from https://github.com/llvm/llvm-project/issues/58985. This still only needs stmt-local analysis and has probably a simple fix.

**Comment by usx95** [comment]
Apparently using an braced init list in the return statement catches this issue:
```
struct MyThing {
    const std::string& s;
};

MyThing makeThing(std::string s) {
    return {s}; // clang warns here.
}
```
https://godbolt.org/z/Mnafoncbc

**Comment by hokein** [comment]
I think this is a missing feature -- where clang doesn't support detecting dangling issues for C++20's parenthesized aggregate initialization (the syntax like `MyThing(s)`). This is stated in the commit https://github.com/llvm/llvm-project/commit/9b4faa11c68be4b45ddf29acd575bb52a3c2fad7.

Per https://eel.is/c++draft/dcl.init#general-16.6.2.2, it would be nice if clang can catch these cases:

```
struct A {
  int a;
  int&& r;
};

int f();
int n = 10;


A a2(1, f());                   // well-formed, but dangling reference
A a4(1.0, 1);                   // well-formed, but dangling reference
A a5(1.0, std::move(n));        // OK
```

**Comment by Xazax-hun** [comment]
Wow this inconsistency with lifetime extension is really confusing. Great that we will have a warning for this now.
