### ISSUE TITLE
attributes not allowed in any order inside extern "C" {} block

### ISSUE THREAD

**Issue by bhaible** [llvm/llvm-project#101990]
With clang 18, in C++ mode, attributes at the beginning of a declaration or function definition are not allowed in any order inside an extern "C" {} block.

For comparison, outside of an extern "C" {} block, it's allowed.

See:
=============================== foo.cc =============================
```
extern "C" {

__attribute__ ((__warn_unused_result__)) [[__maybe_unused__]] int coox1 (int); // still error in clang 18
[[__maybe_unused__]] __attribute__ ((__warn_unused_result__)) int coox2 (int);

__attribute__ ((__warn_unused_result__)) [[__maybe_unused__]] static int coos1 (int x) { return x; }; // still error in clang 18
[[__maybe_unused__]] __attribute__ ((__warn_unused_result__)) static int coos2 (int x) { return x; };

}

__attribute__ ((__warn_unused_result__)) [[__maybe_unused__]] int foox1 (int); // error in clang < 16
[[__maybe_unused__]] __attribute__ ((__warn_unused_result__)) int foox2 (int);

__attribute__ ((__warn_unused_result__)) [[__maybe_unused__]] static int foos1 (int x) { return x; }; // error in clang < 16
[[__maybe_unused__]] __attribute__ ((__warn_unused_result__)) static int foos2 (int x) { return x; };
```
```
$ clang++ -S -Wall foo.cc
foo.cc:3:42: error: an attribute list cannot appear here
    3 | __attribute__ ((__warn_unused_result__)) [[__maybe_unused__]] int coox1 (int); // still error in clang 18
      |                                          ^~~~~~~~~~~~~~~~~~~~
foo.cc:6:42: error: an attribute list cannot appear here
    6 | __attribute__ ((__warn_unused_result__)) [[__maybe_unused__]] static int coos1 (int x) { return x; }; // still error in clang 18
      |                                          ^~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

For comparison, in C mode, the same attributes are allowed in any order since clang 17. See:
=================================== foo.c ==============================
```
__attribute__ ((__warn_unused_result__)) [[__maybe_unused__]] int coox1 (int); // error in clang < 17
[[__maybe_unused__]] __attribute__ ((__warn_unused_result__)) int coox2 (int); // error in clang < 17

__attribute__ ((__warn_unused_result__)) [[__maybe_unused__]] static int coos1 (int x) { return x; }; // error in clang < 17
[[__maybe_unused__]] __attribute__ ((__warn_unused_result__)) static int coos2 (int x) { return x; }; // error in clang < 17
```
```
$ clang -S -Wall foo.c
```
(no warning or error)

**Comment by cor3ntin** [comment]
@AaronBallman

**Comment by AaronBallman** [comment]
Huh, interestingly, it does parse correctly in a single `extern "C"` declaration, so the issue is specific to `extern "C"` blocks: https://godbolt.org/z/aon399d1E

**Comment by a-tarasyuk** [comment]
@AaronBallman It looks like the parser correctly processes attributes order like `__attribute__ ((__warn_unused_result__)) and [[__maybe_unused__]] in extern "C"`

https://github.com/llvm/llvm-project/blob/b7c7dbd473c0857d0d86b228e45ce5a0a68a1a1b/clang/lib/Parse/ParseDeclCXX.cpp#L376-L378

However, it does not handle these attributes properly when encountering a `l_brace`, it only supports `cpp11` attributes

https://github.com/llvm/llvm-project/blob/b7c7dbd473c0857d0d86b228e45ce5a0a68a1a1b/clang/lib/Parse/ParseDeclCXX.cpp#L428

**Comment by a-tarasyuk** [comment]
@AaronBallman It looks like the parser correctly processes attributes order like
```cpp
__attribute__ ((__warn_unused_result__)) [[__maybe_unused__]] extern "C"
```

https://github.com/llvm/llvm-project/blob/b7c7dbd473c0857d0d86b228e45ce5a0a68a1a1b/clang/lib/Parse/ParseDeclCXX.cpp#L376-L378

However, it does not handle these attributes properly when encountering a `l_brace`, it only supports `cpp11` attributes

https://github.com/llvm/llvm-project/blob/b7c7dbd473c0857d0d86b228e45ce5a0a68a1a1b/clang/lib/Parse/ParseDeclCXX.cpp#L428

@AaronBallman could you review https://github.com/llvm/llvm-project/pull/102864? Thanks

**Comment by bhaible** [comment]
Could you also add a test case, based on my original problem description? Without a test case, it's hard to guarantee there will be no future breakage, since a parser is not straightforward code.
```
extern "C" {
__attribute__ ((__warn_unused_result__)) [[__maybe_unused__]] int coox1 (int);
__attribute__ ((__warn_unused_result__)) [[__maybe_unused__]] static int coos1 (int x) { return x; };
}
```

**Comment by a-tarasyuk** [comment]
@bhaible sure. I've updated tests

**Comment by bhaible** [comment]
@a-tarasyuk Thanks. I had not seen that you already added new test cases in the first commit; apologies.
Now, line 41 (decl of `n`) is merely a duplicate of line 36 (decl of `l`); whereas line 42 (with the `static` function definition) is a useful addition.

**Comment by a-tarasyuk** [comment]
@bhaible The second test case checks whether both declarations that start with GNU attributes function correctly. @AaronBallman is it okay to keep this case or remove it?
