### ISSUE TITLE
Windows release packaging for 19.1.0-rc2 fails with `Internal compiler error #12345: error mmapping datablock to 5517122.`

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#101994]
On Windows:

```
git checkout llvmorg-19.1.0-rc2
cd ..
llvm-project\llvm\utils\release\build_llvm_release.bat --x64 --version=19.1.0-rc2
[...]
[2/3] Run CPack packaging tool...CPack: Create package using NSIS
CPack: Install projects
CPack: - Install project: LLVM []
CPack: Create package
CPack Error: Problem running NSIS command: "C:/Program Files (x86)/NSIS/makensis.exe" "C:/src/llvm_package_19.1.0-rc2/build64/_CPack_Packages/win64/NSIS/project.nsi"
Please check C:/src/llvm_package_19.1.0-rc2/build64/_CPack_Packages/win64/NSIS/NSISOutput.log for errors
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: LLVM

FAILED: CMakeFiles/package.util
cmd.exe /C "cd /D C:\src\llvm_package_19.1.0-rc2\build64 && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cpack.exe" --config ./CPackConfig.cmake"
ninja: build stopped: subcommand failed.
```

At the end of `NSISOutput.log`:

```
File: "llvm-objdump.exe" 31266816 bytes
File: "llvm-pdbutil.exe" 5612032 bytes
File: "llvm-profdata.exe"
Internal compiler error #12345: error mmapping datablock to 5517122.

Note: you may have one or two (large) stale temporary file(s) left in your temporary directory (Generally this only happens on Windows 9x).
```

This seems due to hitting the 2GB NSIS installer limit.

**Comment by omjavaid** [comment]
@zmodem I have used https://sourceforge.net/projects/nsisbi/ to get through this issue on Windows/AArch64.

**Comment by zmodem** [comment]
> @zmodem I have used https://sourceforge.net/projects/nsisbi/ to get through this issue on Windows/AArch64.

Thanks!

From that page:

> This version adds support for using a separate file for storing the install data, therefore allowing installer sizes up to a theoretical max size of 8EB (this is controlled by NSIS_CONFIG_EXTERNAL_FILE_SUPPORT, this is turned on by default).

That sounds like the installer will consist of two files, one .exe and one data file. Or is it possible to just get one big .exe file by disabling NSIS_CONFIG_EXTERNAL_FILE_SUPPORT? How do you run it?

**Comment by omjavaid** [comment]
> That sounds like the installer will consist of two files, one .exe and one data file. Or is it possible to just get one big .exe file by disabling NSIS_CONFIG_EXTERNAL_FILE_SUPPORT? How do you run it?

In my case the it was not installer size issue rather it was issue with a temporary file going beyond 2GB. So I just used it the way I use normal NSIS, didnt do any special configurations. Output was a single file about 525 MB. Unpacked and installed it just fine on the same machine.

From the error message you posted above, your issue looks similar. NSIS creates a temporary which cant go beyond 2GBs

**Comment by zmodem** [comment]
Great! I'll try nsisbi for rc3 which was just tagged.

**Comment by zmodem** [comment]
That worked nicely. The installer is here: https://discourse.llvm.org/t/llvm-19-1-0-rc3-tagged/80803/6

**Comment by zmodem** [comment]
A user reported a problem with the "nsisbi"-built rc3 installer: It can't be extracted by 7zip.

```
$ 7z l LLVM-19.1.0-rc3-win64.exe

7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20
 64-bit locale=en_US.UTF-8 Threads:8 OPEN_MAX:131072

Scanning the drive for archives:
1 file, 573008451 bytes (547 MiB)

Listing archive: LLVM-19.1.0-rc3-win64.exe


ERROR: LLVM-19.1.0-rc3-win64.exe : Cannot open the file as archive
```

(it works with LLVM-19.1.0-rc2-win64.exe)

It's a nice feature of NSIS installers that they can be extracted this way, and some users depend on it.

I'll switch back to regular NSIS and limited the number of targets built to reduce size.
