### ISSUE TITLE
Create a team for flang:openmp label

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#101975]
We want a new team to monitor the issues filed under the flang:openmp label (https://github.com/llvm/llvm-project/issues?q=is%3Aopen+is%3Aissue+label%3Aflang%3Aopenmp).

We currently have a similar one for Pull Requests. My assumption here is that the issues team and pr team are different. https://github.com/orgs/llvm/teams/pr-subscribers-flang-openmp

**Comment by tstellar** [comment]
Team created: https://github.com/orgs/llvm/teams/issues-subscribers-flang-openmp
