### ISSUE TITLE
[clang][armv8] Lack of optimisation in floating point constant

### ISSUE THREAD

**Issue by VirtualTim** [llvm/llvm-project#101946]
https://godbolt.org/z/KG9eETjWG
Example code:
```cpp
float getNum() {
    return ((0.299f * 222.0f) + (0.587f * 96.0f) + (0.114f * 117.0f));
}

double getNum2() {
    return ((0.299 * 222) + (0.587 * 96) + (0.114 * 117));
}
```

Compiling with the following: `-O3 -std=c++11` generates this:
**armv7-a (trunk)**
```asm
getNum():
  ldr r0, .LCPI0_0
  bx lr
.LCPI0_0:
  .long 1124602216

getNum2():
  ldr r0, .LCPI1_0
  ldr r1, .LCPI1_1
  bx lr
.LCPI1_0:
  .long 240518168
.LCPI1_1:
  .long 1080099373
```

**armv8-a (trunk)**
```asm
getNum():
  mov w8, #4456
  movk w8, #17160, lsl #16
  fmov s0, w8
  ret

.LCPI1_0:
  .xword 0x4061022d0e560418
getNum2():
  adrp x8, .LCPI1_0
  ldr d0, [x8, :lo12:.LCPI1_0]
  ret
```

Notice how in armv7 the float is stored as a constant precomputed `.long`, and the double is stored as 2x precomputed `.long`s.
In armv8 the double is now stored as a precomputed `.xword`, but the float is instead calculated at runtime.

For reference, this is how gcc (ARM GCC trunk) compiles this:
```asm
getNum():
  vldr.32 s0, .L3
  bx lr
.L3:
  .word 1124602216
getNum2():
  vldr.64 d0, .L6
  bx lr
.L6:
  .word 240518168
  .word 1080099373
```

**Comment by Kmeakin** [comment]
I think the assembly generated for AArch64 is optimal. 
Loading from global would take 16 bytes (8 bytes for the 64bit constant, 8 bytes for `ADR`,`LDR` instructions).
`MOV`, `MOVK`, `FMOV` takes 12 bytes, and the `MOV`+`MOVK` can be fused into one operation on many microarchitectures.
