### ISSUE TITLE
`__noop` not marked as constexpr

### ISSUE THREAD

**Issue by DanielJump** [llvm/llvm-project#102064]
https://godbo.lt/z/j1hG1YYqK

`constexpr int x = []{ __noop; return 0; }();`
flags: `-fms-extensions`

```
<source>:1:15: error: constexpr variable 'x' must be initialized by a constant expression
    1 | constexpr int x = []{ __noop; return 0; }();
      |               ^   ~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:1:23: note: subexpression not valid in a constant expression
    1 | constexpr int x = []{ __noop; return 0; }();
      |                       ^~~~~~
<source>:1:19: note: in call to '[] {
    __noop();
    return 0;
}.operator()()'
    1 | constexpr int x = []{ __noop; return 0; }();
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Compiler returned: 1
```

**Comment by AdiSin123** [comment]
Please assign me this issue. I would like to work on it and try and solve it, as a beginner coder. I will be very grateful to you.

**Comment by ofAlpaca** [comment]
@AdiSin123
I apologize for directly PR the issue you're assigned.
Are you still working on it?

**Comment by ofAlpaca** [comment]
@AdiSin123
You can set breakpoint on function `IntExprEvaluator::VisitBuiltinCallExpr` and see how it affects `Diag(DiagLoc, diag::err_constexpr_var_requires_const_init)` on clang/lib/Sema/SemaDecl.cpp .
Hope this give you some hint to follow up the issue.

**Comment by AdiSin123** [comment]
Thanks, I'll check it out. I am grateful for the very specific help you
provided, seriously.

**Comment by AdiSin123** [comment]
Also, if it is not too much of a bother, can I ask you some questions over
mail, regarding any particular part I am having difficulty understanding? I
promise to try everything I know first before asking.

**Comment by ofAlpaca** [comment]
@AdiSin123 
I'm also new to LLVM project.
We can discuss this issue through mail or here if you want to.
