### ISSUE TITLE
[clang] Clang 19 regression "no member named" in templated class method

### ISSUE THREAD

**Issue by vient** [llvm/llvm-project#102177]
```c++
template<class C>
class A {
  void call_f() {
      this->f();
  }
};
```
Compiles with Clang 18 but gives `error: no member named 'f' in 'A<C>'` with Clang 19 https://godbolt.org/z/vzjYf6Kxd

Caught while trying to compile code using simdjson
```
.conan2/p/simdjfa4aaa94b0935/p/include/simdjson.h:6101:13: error: no member named 'print_newline' in 'base_formatter<formatter>'
 6101 |       this->print_newline();
      |       ~~~~  ^
```
https://github.com/simdjson/simdjson/blob/v3.2.3/include/simdjson/dom/serialization.h#L59-L61

**Comment by DimitryAndric** [comment]
See also https://github.com/simdjson/simdjson/pull/2187, and https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=280590

**Comment by DimitryAndric** [comment]
Either f061a395ffb78215a23e0f503e8ea121ee3b13ad or 8009bbec59d1c5d47ae06c431647ebee6d886ff2 (both by @sdkrystian ) seems a likely cause, but not sure if this was the intended effect?

**Comment by MitalAshok** [comment]
Note that GCC15 also stops accepting this: https://godbolt.org/z/n1vrM44q5

Did this ever compile when the member function was used? `A<T>{}.call_f()` doesn't seem valid for any `T` so this does seem ill-formed (NDR)
