### ISSUE TITLE
[clang-format] Spacing with function pointer

### ISSUE THREAD

**Issue by prj-** [llvm/llvm-project#102102]
I'm not sure the spacing surrounding `&` is intentional or not?
```c
$ clang-format func.c
int main(int argc, char *argv) {
  func((void *)&a);
  func((void (**)(void)) & b);
  return 0;
}
```

**Comment by prj-** [comment]
This happens with both clang-format version 18 and version 20. If this is something that needs fixing, any hope that it gets ported to version 19 as well?

**Comment by prj-** [comment]
@owenca, this is broken again. Works OK with version 19.1.0, but with `Debian clang-format version 20.0.0 (++20240917111146+1e23a6142a82-1~exp1~20240917111312.2342)`, I get:
```c
$ clang-format foobar.c
int main() {
  if (type == NON_UNIFORM)
    return (PetscErrorCode(*)(void *, void *, PetscInt,
                              ...))&PCTFS_rvec_non_uniform;
  return 0;
}
$ clang-format-20 foobar.c 
int main() {
  if (type == NON_UNIFORM)
    return (PetscErrorCode(*)(void *, void *, PetscInt, ...)) &
           PCTFS_rvec_non_uniform;
  return 0;
}
```
It was OK with `20240831100704%2B8aa8c0590c09-1~exp1~20240831220720.2307`.

**Comment by owenca** [comment]
It seems the root cause is that the `l_paren` in `(*)` is not annotated as `FunctionTypeLParen`. Can you open an issue for this, @prj-?

**Comment by prj-** [comment]
I will do it no problem.

**Comment by prj-** [comment]
Cross-referencing https://github.com/llvm/llvm-project/issues/109146.
