### ISSUE TITLE
`#embed` crashes when used in a compound literal

### ISSUE THREAD

**Issue by zygoloid** [llvm/llvm-project#102248]
This valid C23 source file:

```c
char *p = (char[]){
#embed "/usr/bin/true"
};
```

[crashes clang](https://godbolt.org/z/9q5Wevsvo) somewhere in `InitListChecker::HandleEmbed`.

**Comment by zygoloid** [comment]
Presumably the issue is here:
https://github.com/llvm/llvm-project/blob/ce2a3d9042c95630f12b790bf201c4daf8941afb/clang/lib/Sema/SemaInit.cpp#L518-L519
An `InitializedEntity` doesn't necessarily have an associated declaration (but there is a `getType()` accessor...)

**Comment by zygoloid** [comment]
@Fznamznon Maybe something like this would work?
```diff
- ValueDecl *ArrDecl = Entity.getParent()->getDecl(); 
- auto *AType = SemaRef.Context.getAsArrayType(ArrDecl->getType()); 
+ auto *AType = SemaRef.Context.getAsArrayType(Entity.getParent()->getType()); 
```

**Comment by Fznamznon** [comment]
> @Fznamznon Maybe something like this would work?
> 
> ```diff
> - ValueDecl *ArrDecl = Entity.getParent()->getDecl(); 
> - auto *AType = SemaRef.Context.getAsArrayType(ArrDecl->getType()); 
> + auto *AType = SemaRef.Context.getAsArrayType(Entity.getParent()->getType()); 
> ```

Yes, it should. I'll create a patch, thank you for reporting this.
