### ISSUE TITLE
[clang] Clang 19 reports "arithmetic on a pointer to an incomplete type" where Clang 18 and GCC do not

### ISSUE THREAD

**Issue by vient** [llvm/llvm-project#102293]
https://godbolt.org/z/sYPWjWqbo

```cpp
struct _Destroy_aux {
  template <typename _ForwardIterator> static void __destroy(_ForwardIterator) {
    _ForwardIterator __first;
    ++__first;
  }
};

template <typename _ForwardIterator> void _Destroy(_ForwardIterator __last) {
  _Destroy_aux::__destroy(__last);
}

template <typename> struct allocator;

template <typename> struct allocator_traits;

template <typename _Tp> struct allocator_traits<allocator<_Tp>> {
  using pointer = _Tp *;
};

struct FileInfo;

struct __alloc_traits : allocator_traits<allocator<FileInfo>> {};

__alloc_traits::pointer _M_finish;

template <typename = int> struct vector {
  ~vector() { _Destroy(_M_finish); }
};

struct DatasetFactory {
  virtual ~DatasetFactory();
};

struct FileSystemDatasetFactory : DatasetFactory {
  vector<> v;
};
```
```
<source>:4:5: error: arithmetic on a pointer to an incomplete type 'FileInfo'
    4 |     ++__first;
      |     ^ ~~~~~~~
<source>:9:17: note: in instantiation of function template specialization '_Destroy_aux::__destroy<FileInfo *>' requested here
    9 |   _Destroy_aux::__destroy(__last);
      |                 ^
<source>:27:15: note: in instantiation of function template specialization '_Destroy<FileInfo *>' requested here
   27 |   ~vector() { _Destroy(_M_finish); }
      |               ^
<source>:34:8: note: in instantiation of member function 'vector<>::~vector' requested here
   34 | struct FileSystemDatasetFactory : DatasetFactory {
      |        ^
<source>:20:8: note: forward declaration of 'FileInfo'
   20 | struct FileInfo;
      |        ^
1 error generated.
```
Minified from Apache Arrow sources. Removing template from `vector` makes all compilers report the same error.

Is it a problem with Clang or with Arrow?

**Comment by cor3ntin** [comment]
All compilers do error if `FileSystemDatasetFactory` is actually used. Clang is a bit more eager in instantiating the destructor though, hence the variance that you observe.

https://godbolt.org/z/TTdWae7vK

**Comment by vient** [comment]
They error because a type is incomplete. In Arrow `FileSystemDatasetFactory` constructor is called only from a complementary .cpp file where a header with full definition of FileInfo is included, inside other static methods (constructor is protected). Again, I don't know what side is wrong here.

FileSystemDatasetFactory definition: https://github.com/apache/arrow/blob/apache-arrow-17.0.0/cpp/src/arrow/dataset/discovery.h#L204 - issue occurs with `std::vector<fs::FileInfo> files_` field.
Search for class name: https://github.com/search?q=repo%3Aapache%2Farrow+%2F%28%5E%7C%5CW%29FileSystemDatasetFactory%28%24%7C%5CW%29%2F+language%3AC%2B%2B&type=code - looks like other code exclusively uses static `Make` method of this class

**Comment by Endilll** [comment]
Bisected to 99500e8c08a4d941acb8a7eb00523296fb2acf7a (#77753)
CC @Fznamznon

**Comment by Fznamznon** [comment]
> (If the destructor is constexpr I think we might trigger instantiation, but I think it shouldn't be because the base class dtor is not.)

Seems like a classic case with clang's eager template instantiation? https://github.com/llvm/llvm-project/commit/99500e8c08a4d941acb8a7eb00523296fb2acf7a made clang to not care about constexprness of base class destructor.

**Comment by zygoloid** [comment]
I see. Maybe we can avoid triggering vtable instantiation due to a dtor that is not "effectively constexpr" (if it's either not constexpr or if it's noexcept and a member or base class dtor is not effectively constexpr), with a special-case note for when this causes constant evaluation failure.

**Comment by Fznamznon** [comment]
>  Maybe we can avoid triggering vtable instantiation due to a dtor that is not "effectively constexpr" (if it's either not constexpr or if it's noexcept and a member or base class dtor is not effectively constexpr), with a special-case note for when this causes constant evaluation failure.

Trying...

**Comment by vient** [comment]
Is it "done" if it is not backported
