### ISSUE TITLE
llc -combiner-alias-analysis reorders volatiles

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#10223]
|  |  |
| --- | --- |
| Bugzilla Link | [9851](https://llvm.org/bz9851) |
| Version | 2.9 |
| OS | Linux |
| Attachments | [Test case for reordering of volatiles.](https://user-images.githubusercontent.com/60944935/143743109-91241fe6-e676-4c8f-b7da-2eaa4c2b011a.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic,@sunfishcode |

## Extended Description 

llc reorders accesses to volatiles if -combiner-alias-analysis is enabled, although volatiles should not be reordered with regard to each other.

Testcase, which miscompiles at least for sparc and ppc32:
define i32 @&#8203;test() {
  %X = volatile load i32* inttoptr(i32 8 to i32*)
  %Y = volatile load i32* inttoptr(i32 12 to i32*)
  %Z = add i32 %Y, 1000
  ret i32 %Z
}

Correct code, from llc -march=ppc32
  lwz 3, 8(0)
  lwz 3, 12(0)
  addi 3, 3, 1000
  blr 

Miscompiled code, from llc -march=ppc32 -combiner-alias-analysis
  lwz 3, 12(0)
  lwz 4, 8(0)
  addi 3, 3, 1000
  blr

**Comment by arsenm** [comment]
Flag seems to have been renamed to -combiner-global-alias-analysis. I get the same result with and without it
```
define i32 @test() {
  %X = load volatile i32, i32* inttoptr(i32 8 to i32*)
  %Y = load volatile i32, i32* inttoptr(i32 12 to i32*)
  %Z = add i32 %Y, 1000
  ret i32 %Z
}
```
