### ISSUE TITLE
Should llvm-mc use section relocations against a section group?

### ISSUE THREAD

**Issue by smeenai** [llvm/llvm-project#102272]
llvm-mc for ELF [prefers relocations against a section to relocations against a symbol](https://github.com/llvm/llvm-project/blob/4b3bc46d1d794b8ed78b75ccd35a6cc30235bf31/llvm/lib/MC/ELFObjectWriter.cpp#L1189) for local symbols (to be precise, a relocation against an STB_LOCAL symbol will be emitted against the symbol's section's STT_SECTION symbol instead of the symbol itself). This can interact badly with COMDAT section groups:

```
$ cat foo.s
.section .text.foo,"axG",@progbits,foo,comdat
foo:
        retq

.text
.globl _start
_start:
        jmp     foo

$ cat otherfoo.s
.section .text.foo,"axG",@progbits,foo,comdat
foo:
        retq

$ llvm-mc --filetype=obj -o foo.o foo.s
$ llvm-mc --filetype=obj -o otherfoo.o otherfoo.s
$ ld.lld otherfoo.o foo.o
ld.lld: error: relocation refers to a discarded section: .text.foo
>>> defined in foo.o
>>> section group signature: foo
>>> prevailing definition is in otherfoo.o
>>> referenced by foo.o:(.text+0x1)
```

This is obviously a contrived example. On the one hand, using section groups with local symbols is pretty weird ([Fangrui's blog post](https://maskray.me/blog/2021-07-25-comdat-and-section-group) links to a [generic ABI discussion thread](https://groups.google.com/g/generic-abi/c/2X6mR-s2zoc) which goes into this). I can't imagine many real world uses (maybe if you put a local symbol in the same COMDAT section as a non-local symbol, but symbols usually go in their own COMDAT section), so maybe this is okay.

On the other hand, MC's justification seems a bit tenuous here. It says:

> // It is always valid to create a relocation with a symbol. It is preferable
> // to use a relocation with a section if that is possible. Using the section
> // allows us to omit some local symbols from the symbol table.

That makes sense for private (`.L` or LLVM's `private` linkage) symbols, but not for other local symbols (LLVM's `internal` linkage), since those will be included in the symbol table even if no relocations target them. Does MC's behavior still make sense in that case?

This isn't particularly important, but I ran into it and was curious what others though. CC @MaskRay in particular.

**Comment by MaskRay** [comment]
Interesting:)

> This is obviously a contrived example. On the one hand, using section groups with local symbols is pretty weird (Fangrui's blog post links to a generic ABI discussion thread which goes into this). I can't imagine many real world uses (maybe if you put a local symbol in the same COMDAT section as a non-local symbol, but symbols usually go in their own COMDAT section), so maybe this is okay.

I agree that a local group signature for COMDAT is weird.
I think it's discouraged due to ambiguity/confusion and inconsistency between with link.exe's IMAGE_SCN_LNK_COMDAT behavior. 

FTR, here is gas' behavior (implemented at some point before 1999, before https://sourceware.org/git/?p=binutils-gdb.git;a=blobdiff;f=gas/write.c;h=d0a9ac67a88ddf8f0ef05f85676f627e3ee28adb;hp=3a492343838b2c8e3b2aaaaf41b255576092b256;hb=7565ed77a1413dd7893b1ce127a576b6a2c99ced;hpb=aa8804e46ee31cc1d2e00f57467c8e5a4a84a273)
```
cat > a.s <<eof
.section .text.foo,"axG",@progbits,foo,comdat
.local foo
foo:
        ret

.section .text..Lfoo,"axG",@progbits,.Lfoo,comdat
.Lfoo:
        ret

.section .text.bar,"ax",@progbits
bar:

.text
.globl _start
_start:
        call foo
        call .Lfoo
        call bar
eof

as a.s -o a.o
```
```
% readelf -r a.o

Relocation section '.rela.text' at offset 0x158 contains 3 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000001  000100000002 R_X86_64_PC32     0000000000000000 foo - 4
000000000006  000200000002 R_X86_64_PC32     0000000000000000 .text..Lfoo - 4
00000000000b  000300000002 R_X86_64_PC32     0000000000000000 .text.bar - 4
```

`foo` has the STB_LOCAL binding but is not a temporary label (gas's `S_IS_LOCAL`?).
gas does not perform STT_SECTION conversion.

If a compelling use case emerges, adopting gas's rule could be considered. Otherwise, maintaining simplicity by omitting the rule might be preferable.

**Comment by smeenai** [comment]
Thanks for taking a look! I agree that gas's behavior is nice but it's also unnecessary to change this until we have an actual use case.

**Comment by smeenai** [comment]
https://github.com/llvm/llvm-project/pull/182725 adds an option which will make this work (though it still remains questionable).
