### ISSUE TITLE
[RISC-V] Inconsistent implied/required extension behavior for zabha/zvk*

### ISSUE THREAD

**Issue by patrick-rivos** [llvm/llvm-project#102249]
Zabha/Zvk currently requires the user to specify Zaamo/{V|Zve}.

Godbolt:
zabha: https://godbolt.org/z/bYrY8fzcv
zvk: https://godbolt.org/z/fqheWoM7d

This behavior doesn't seem to match the RISC-V spec:
Zabha spec: https://github.com/riscv/riscv-isa-manual/blob/d2999932625d2cab25bb2081f7da915411e65ad3/src/zabha.adoc?plain=1#L28-L29
Zvk* spec: https://github.com/riscv/riscv-isa-manual/blob/d2999932625d2cab25bb2081f7da915411e65ad3/src/vector-crypto.adoc?plain=1#L471-L473

"requires" is equivalent to "depends upon": https://github.com/riscv/riscv-v-spec/issues/723#issuecomment-949542444
"depends upon" seems to be specified behavior: https://github.com/riscv/riscv-isa-manual/blob/399c9a759eb4540a65c60e2cc236164821ff2346/src/naming.tex#L46

This behavior isn't consistent within LLVM:
[zcb "depends upon" zca](https://github.com/riscv/riscv-isa-manual/blob/d2999932625d2cab25bb2081f7da915411e65ad3/src/zc.adoc?plain=1#L130) and is implicitly added by llvm: https://godbolt.org/z/aoYGbaWvz

**Comment by lenary** [comment]
I think the Zabha issue will be solved by https://github.com/llvm/llvm-project/pull/115694

I'm not sure there's a PR open to fix `Zvk*` yet.

**Comment by topperc** [comment]
> I think the `Zabha` issue will be solved by https://github.com/llvm/llvm-project/pull/115694
> 
> 
> 
> I'm not sure there's a PR open to fix `Zvk*` yet.

Zvk was already fixed a week or two ago.

**Comment by tclin914** [comment]
> I think the `Zabha` issue will be solved by #115694
> 
> I'm not sure there's a PR open to fix `Zvk*` yet.

Zvk was fixed by https://github.com/llvm/llvm-project/commit/94e7d9c0bfe517507ea08b00fb00c32fb2837a82 and https://github.com/llvm/llvm-project/commit/f53889ffcad28bbc0faf671626cc90eb4e7da5a8.

**Comment by tclin914** [comment]
Zabha was fixed by: https://github.com/llvm/llvm-project/pull/115694
