### ISSUE TITLE
[llvm-lit] Environment variable not found in LLVM subproject with lit internal shell 

### ISSUE THREAD

**Issue by Harini0924** [llvm/llvm-project#102395]
Currently, an environment variable is not recognized within the LLVM subproject, resulting in test failures when using the lit internal shell.
**Error displayed:**
```
'JITDUMPDIR=/usr/local/google/home/harinidonthula/llvm-project/build/test/ExecutionEngine/JITLink/x86-64/Output/ELF_perf.s.tmp': command not found
```
This error indicates that the internal shell is misinterpreting environment variable assignments as commands, leading to these failures.

**Comment by vitalybuka** [comment]
@Harini0924 Patches descriptions should not contains "fixes: llvm#NNNN" if you are not intended to close the issue.
You can use something like "For issues: llvm#NNNN"

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
