### ISSUE TITLE
[AVR] Jumps are off by 2

### ISSUE THREAD

**Issue by Patryk27** [llvm/llvm-project#102436]
Hi,

Ever since https://github.com/llvm/llvm-project/commit/6859685a87ad093d60c8bed60b116143c0a684c7 (or, more precisely, https://github.com/llvm/llvm-project/commit/84428dafc0941e3a31303fa1b286835ab2b8e234), the AVR backend encodes jumps across basic blocks with an extra offset of 2.

That's related to this check:

https://github.com/llvm/llvm-project/blob/1919db907bc3e0541839992d903b6b875da98b04/llvm/lib/Target/AVR/MCTargetDesc/AVRAsmBackend.cpp#L521

... which wasn't triggered for basic blocks before, but it is now (i.e. `shouldForceRelocation()` returns `false` for such jumps now).

I'm working on a pure LLVM reproducer, but the original rustc issue has been reported [here](https://github.com/Rahix/avr-hal/issues/571) - if you compare the *.elf from older toolchain and the newer toolchain, you'll see that calls are alright, but jumps have an extra offset.

**Comment by Patryk27** [comment]
Alright, adding `Value -= 1;` here:

https://github.com/llvm/llvm-project/blob/57cd1000c9c93fd0e64352cfbc9fbbe5b8a8fcef/llvm/lib/Target/AVR/MCTargetDesc/AVRAsmBackend.cpp#L89

... seems to solve the problem.

**Comment by Patryk27** [comment]
Issue has been already solved, just forgot to add `closes xyz` to the commit message.

**Comment by benshi001** [comment]
Though https://github.com/llvm/llvm-project/commit/86a60e7f1e8f361f84ccb6e656e848dd4fbaa713 has been merged, the fix is incorrect, since the llvm-objdump still has problem, as I have indicated at https://github.com/llvm/llvm-project/pull/102936#discussion_r1741322197

**Comment by benshi001** [comment]
@Patryk27 If you are busy, please assign this issue to me. I will take a time to find a better solution later this month.

**Comment by Patryk27** [comment]
Ah, right, I forgot about it - feel free to take a stab at it.

**Comment by benshi001** [comment]
@Patryk27 Your fix is good! I have made a mistake, the output of both `llvm-mc -show-encoding` and `llvm-objdump -d` are correct.

**Comment by Patryk27** [comment]
Cool, thanks for checking! 🙂

**Comment by benshi001** [comment]
@Patryk27 Though your fix is good, there is still an underlying issue, which I have fixed by https://github.com/llvm/llvm-project/pull/109124. You are appreciated  to have a look.
