### ISSUE TITLE
'make check' fails by default when configured with --enable-shared

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#10253]
|  |  |
| --- | --- |
| Bugzilla Link | [9881](https://llvm.org/bz9881) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
All the tests under 'make check' fail with a message like this:

.../Release+Asserts/bin/opt: error while loading shared libraries: libLLVM-3.0svn.so: cannot open shared object file: No such file or directory

It only works as intended if you copy libLLVM-3.0svn.so into the system lib path, or set LD_LIBRARY_PATH manually:

LD_LIBRARY_PATH=<top_builddir>/Release+Asserts/lib make check

Should the build scripts do that kind of thing themselves? It should also prevent accidentally picking up an outdated, incompatible shared lib that might have been `make install`d from a previous build, which would give 'missing symbol' errors.

**Comment by arsenm** [comment]
Old autotools build
