### ISSUE TITLE
[AArch64] Crash on the Instruction Selection for llvm.aarch64.sve.tbl.nxv2f32

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#102559]
* Since commit 3f9005eb89, we support the intrinsic **lvm.aarch64.sve.tbl**, usual the type is just a legal type, so it can works fine.

* But we may still need promote this operator's operand to make it more reliable, now we don't support **llvm.aarch64.sve.tbl.nxv2f32**
    > fatal error: error in backend: Do not know how to promote this operator's operand

* test: https://gcc.godbolt.org/z/bh5KcWoYK
```
define void @_Z3fooPfPjS_i(ptr %dest, <vscale x 2 x i32> %wide.load1721) {
  %0 = tail call <vscale x 2 x float> @llvm.aarch64.sve.tbl.nxv2f32(<vscale x 2 x float> zeroinitializer,
                                                                    <vscale x 2 x i32> %wide.load1721)
  store <vscale x 2 x float> %0, ptr %dest, align 4
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 2 x float> @llvm.aarch64.sve.tbl.nxv2f32(<vscale x 2 x float>, <vscale x 2 x i32>)
```

* The declare of **AdvSIMD_SVE_TBL_Intrinsic**, it should support **llvm_anyvector_ty**
```
 class AdvSIMD_SVE_TBL_Intrinsic
    : Intrinsic<[llvm_anyvector_ty],
                [LLVMMatchType<0>,
                 LLVMVectorOfBitcastsToInt<0>],
                [IntrNoMem]>;
```

**Comment by davemgreen** [comment]
We don't usually support type legalization for intrinsics, it is assumed that they will already be of the a legal type.

Where is the tbl being generate from?

**Comment by vfdff** [comment]
Thanks for your suggestion. I'll add some checking before we use such intrinsics as we don't usually support type legalization for intrinsic.
The illegit type for **tbl** is geneated from LoopVectorize, because we doesn't always choose a legal type when I try optimizing for [PR100689](https://github.com/llvm/llvm-project/issues/100689)
