### ISSUE TITLE
Explicit Method Specialization with Constraints Fails to Compile

### ISSUE THREAD

**Issue by jcsq6** [llvm/llvm-project#102548]
Clang considers the requires clause as a part of the method signature, and naturally, you aren't able to put a requires clause on a fully specialized function. However, without the requires clause, clang considers it a different function. This makes it impossible to fully specialize methods. This also doesn't seem to be an issue when fully specializing a normal function that has a requires clause.

https://godbolt.org/z/Pqocnrafj

```
<source>:11:20: error: out-of-line definition of 'method' does not match any declaration in 'test<double>'
   11 | void test<double>::method()
      |                    ^~~~~~
<source>:7:7: note: member declaration nearly matches
    7 |         void method() requires(std::floating_point<T>);
      |              ^
1 error generated.
Compiler returned: 1
```

This code compiles on gcc.

**Comment by EugeneZelenko** [comment]
Compiles OK in `main`: https://godbolt.org/z/ah31zYs3n

**Comment by jcsq6** [comment]
I found this error on clang for arm64
```
clang --version
Homebrew clang version 18.1.8
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
```
