### ISSUE TITLE
GlobalIsel combiner with GIVariadic

### ISSUE THREAD

**Issue by tschuett** [llvm/llvm-project#102719]
https://github.com/llvm/llvm-project/pull/100563 motivated me that I wrote my first combine using GIVariadic.

See https://github.com/llvm/llvm-project/compare/main...tschuett:llvm-project:gisel-push-through-build-vector2?expand=1

The traditional buildvector_of_zext3 hits the exit in the match function. The modern buildvector_of_zext2 fails to hit the exit. I have feeling that the pattern does not match.

**Comment by tschuett** [comment]
The tests for the combiner infrastructure are CHECK-lines on td files.

Better testing could be a test combiner with cpp, td, and mir files.

**Comment by Pierre-vh** [comment]
I directly committed the fix because it was trivial.
I also agree it'd be nice to have a combiner test that actually runs, but it's difficult to setup
