### ISSUE TITLE
[libc++] inconsistent `is_integral<_BitInt(N)>` implementation

### ISSUE THREAD

**Issue by AngryLoki** [llvm/llvm-project#102767]
After optimization commit https://github.com/llvm/llvm-project/commit/5ade17e0ca8b11f57cb15a1bee6d30a3815d8cac pushed back in 2020, behavior of `is_integral<_BitInt(N)>` became inconsistent.
1) in libstdc++ `std::is_integral_v<_BitInt(N)>` is false
2) in libc++ `std::is_integral_v<_BitInt(N)>` is false when compiler has no `__is_integral` built-in
3) in libc++ `std::is_integral_v<_BitInt(N)>` is true when compiler has `__is_integral` built-in

This is caused by https://github.com/llvm/llvm-project/blob/main/libcxx/include/__type_traits/is_integral.h implementation
```c++
template <class _Tp> struct __libcpp_is_integral                     { enum { value = 0 }; };
template <>          struct __libcpp_is_integral<bool>               { enum { value = 1 }; };
template <>          struct __libcpp_is_integral<char>               { enum { value = 1 }; };
// ...other specializations...

#if __has_builtin(__is_integral)
    // __is_integral-based implementation, treating _BitInt(N) as integral
#else
    // __libcpp_is_integral-based implementation, treating _BitInt(N) as not integral
#endif
```

Here is example (causing failure in `ROCm/composable_kernel`):
```c++
#include <type_traits>

using int4_t  = _BitInt(4);
using f8_t    = _BitInt(8);
using bf8_t   = unsigned _BitInt(8);

// passes with stdlibc++, fails with clang+libc++
static_assert(!std::is_integral_v<int4_t>);
static_assert(!std::is_integral_v<f8_t>);
static_assert(!std::is_integral_v<bf8_t>);
```
Conformance view: https://godbolt.org/z/TcjPTrhGq

To my knowledge `_BitInt(N)` should not pass is_integral trait (maybe is some future standard we'll see this). 
Overall, I'd like to see consistent behavior (not depending on `__has_builtin(__is_integral)`).

**Comment by philnik777** [comment]
I'm not sure I understand the problem here. libc++ recognized `_BitInt` as an integral type, libstdc++ doesn't. Recognizing it as an integral type means that `_BitInt` should work anywhere integral types are supported, which may not be the case for libstdc++. It also happens to be the case that exactly the compilers that support `_BitInt` as an extension also support `__is_integral`.

**Comment by AngryLoki** [comment]
@philnik777 , point taken. I missed the fact that "exactly the compilers that support `_BitInt` as an extension also support `__is_integral`".

Still, the thing that happened is that libc++ added support of non-standard `_BitInt` type and then changed the behavior of `std::is_integral`, which causes compilation errors in other projects.

What are possible options?
1) keep status quo, adapt external projects for libc++, then in N years we may see `std::bit_int<N>` in core C++, which will equalize everything
2) maybe there are still ways to implements `std::is_integral` in libc++ so that it works exactly as described in standard?

**Comment by philnik777** [comment]
How exactly did we change the documented behaviour of `is_integral`? AFAICT the standard is actually pretty clear that we have to return true for `_BitInt` if we consider it an extended integer type, which I believe we do.

**Comment by AngryLoki** [comment]
Hm, I guess you are right. Also https://en.cppreference.com/w/cpp/types/is_integral mentions "any implementation-defined extended integer type". 

I think the solution could be adding `__has_builtin(__is_integral)`-based implementation into libstdc++ to equalize both standard libraries (also it will probably make libstdc++ build time faster, as noted in https://github.com/llvm/llvm-project/commit/5ade17e0ca8b11f57cb15a1bee6d30a3815d8cac). Closing this bug.

**Comment by mordante** [comment]
FYI `_BitInt` is part of C23, which is based on Clang's implementation of this type.

**Comment by AngryLoki** [comment]
Yes, and GCC-15 (nightly) already supports `_BitInt`, but only in C. There are no progress or discussions in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102989 to allow `_BitInt` in C++, but given that libstdc++ already has some code for clang extensions, maybe they will accept `__has_builtin(__is_integral)`-based implementation.
