### ISSUE TITLE
-std=gnu99 produces a warning when linking

### ISSUE THREAD

**Issue by b2405369-eadb-4fa3-8979-cbb816d5d5da** [llvm/llvm-project#10273]
|  |  |
| --- | --- |
| Bugzilla Link | [9901](https://llvm.org/bz9901) |
| Version | trunk |
| OS | Linux |

## Extended Description 
$ clang -std=gnu99 test.c -c
-> no warning
$ clang -std=gnu99 test.o
clang: warning: argument unused during compilation: '-std=gnu99'

When using Makefiles, how can we specify CFLAGS='-std=gnu99' only for building and not for the linking step ?

It's rather annoying to have lots of useless warning and not any way to even work around it.

**Comment by arsenm** [comment]
I don't see a warning today
