### ISSUE TITLE
LLVM 19.1.0-rc2 compilation issue while trying to build clang

### ISSUE THREAD

**Issue by subhakr** [llvm/llvm-project#102892]
Hi,
I trying to install LLVM-19.1.0-rc2 (https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.0-rc2)

OS: ubuntu22.04LTS
CPU architectiure: x86_64
RAM and intrenal space: 8GB and 256GB

and the commands i have used to compile

```
cmake -S llvm -B build -G Ninja  -DLLVM_ENABLE_PROJECTS="clang;lld" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DLLVM_USE_LINKER=lld 

ninja -C build check-llvm check-clang >> final_build_latest.txt 
```

my main moto is to install clang-19 from LLVM 19

i am unable to install clang19 and i am getting errors as in this file.PFA
[final_build_latest-01.txt](https://github.com/user-attachments/files/16581677/final_build_latest-01.txt)
[final_build_latest-02.txt](https://github.com/user-attachments/files/16581679/final_build_latest-02.txt)

please check the files.
in that file i have pushed all the errors and building process totally.

suggest me to build the clang-19 from llvm-19.

suggest me if i am doing any wrong with my used  commands

**Comment by subhakr** [comment]
Hi,
Can any one help me to solve this.

**Comment by xgupta** [comment]
If you replace `ninja -C build check-llvm check-clang >> final_build_latest.txt`  with `sudo ninja install`. It will install the clang. You don't need to run check-llvm or check-clang.

**Comment by xgupta** [comment]
This is your system issue, not an issue with llvm-project, hence closing. You can reach out on llvm discord or discourse forum if you need help in building llvm.
