### ISSUE TITLE
`xor r8d, r8d` followed by `setne r8b` is redundant

### ISSUE THREAD

**Issue by Validark** [llvm/llvm-project#102845]
```zig
export fn foo(unescaped_quotes: u64, unescaped_apostrophes: u64, newlines: u64, comment_starts: u64, line_string_starts: u64) extern struct { a: u64, b: u8 } {
    const all_ored = unescaped_quotes | unescaped_apostrophes | comment_starts | line_string_starts;
    const lsb = all_ored & (~all_ored +% 1);

    var bitstr: u64 = newlines;
    var id: u8 = 0;

    if ((unescaped_apostrophes & lsb) != 0) {
        bitstr = unescaped_apostrophes;
        bitstr &= bitstr -% 1;
        id = 1;
    }

    if ((unescaped_quotes & lsb) != 0) {
        bitstr = unescaped_quotes;
        bitstr &= bitstr -% 1;
        id = 2;
    }

    return .{ .a = @ctz(bitstr), .b = id };
}
```

Compiled for Zen 4, generates: ([Godbolt link](https://godbolt.org/z/51d9hfP5a))  (Ctrl+F in the assembly window for 'r8')

```asm
foo:
        mov     rax, rdi
        or      rcx, r8
        or      rax, rsi
        xor     r8d, r8d
        or      rax, rcx
        blsr    rcx, rsi
        neg     rax
        test    rax, rsi
        cmove   rcx, rdx
        setne   r8b
        blsr    rsi, rdi
        test    rax, rdi
        mov     edx, 2
        cmove   rsi, rcx
        cmove   rdx, r8
        tzcnt   rax, rsi
        ret
```

I believe the highlighted line should be removed.

```diff
foo:
        mov     rax, rdi
        or      rcx, r8
        or      rax, rsi
-       xor     r8d, r8d
        or      rax, rcx
        blsr    rcx, rsi
        neg     rax
        test    rax, rsi
        cmove   rcx, rdx
        setne   r8b
        blsr    rsi, rdi
        test    rax, rdi
        mov     edx, 2
        cmove   rsi, rcx
        cmove   rdx, r8
        tzcnt   rax, rsi
        ret
```

**Comment by topperc** [comment]
I believe its there to zero the upper 56 bits of r8. setne only updates the lower 8 bits of r8. On Intel CPUs, setne also has a dependency on the last writer of the upper 56 bits of r8 so that the lower 8 bits can be merged in. So the xor could also be to break that false dependency.

**Comment by Validark** [comment]
> I believe its there to zero the upper 56 bits of r8. setne only updates the lower 8 bits of r8. On Intel CPUs, setne also has a dependency on the last writer of the upper 56 bits of r8 so that the lower 8 bits can be merged in. So the xor could also be to break that false dependency.

Ah, yes, I forgot this is a quirk of the x86 ISA. So there is no way to do a `setne` that zeroes the upper bits in a single instruction? In that case, I'll close the issue.

**Comment by topperc** [comment]
> > I believe its there to zero the upper 56 bits of r8. setne only updates the lower 8 bits of r8. On Intel CPUs, setne also has a dependency on the last writer of the upper 56 bits of r8 so that the lower 8 bits can be merged in. So the xor could also be to break that false dependency.
> 
> Ah, yes, I forgot this is a quirk of the x86 ISA. So there is no way to do a `setne` that zeroes the upper bits in a single instruction? In that case, I'll close the issue.

I think something was added in new APX instructions but not before that.

**Comment by KanRobert** [comment]
Yes. SETZUCC can do that https://github.com/llvm/llvm-project/pull/96594

**Comment by Validark** [comment]
> Yes. SETZUCC can do that #96594

Thanks for working on that!
