### ISSUE TITLE
[IR] A question about the ordering of allocas

### ISSUE THREAD

**Issue by dtcxzyw** [llvm/llvm-project#102823]
See the following stack growth direction detection idiom: https://github.com/google/googletest/blob/ff233bdd4cac0a0bf6e5cd45bda3406814cb2796/googletest/src/gtest-death-test.cc#L1213-L1247

LLVM IR for `testing::internal::StackGrowsDown()`:
```
; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none) uwtable
define hidden noundef zeroext i1 @_ZN7testing8internal14StackGrowsDownEv() local_unnamed_addr #4 {
entry:
  %dummy.i = alloca i32, align 4
  %dummy = alloca i32, align 4
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %dummy.i)
  %cmp.i = icmp ult ptr %dummy.i, %dummy
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %dummy.i)
  ret i1 %cmp.i
}
```

Is it a well-defined behavior? If we swap these two allocas, does it produce the opposite result? If so, are we allowed to constant fold the pointer comparison based on `TargetFrameLowering::getStackGrowthDirection`?

I cannot find any information from LangRef.

cc @RKSimon @topperc @nikic

**Comment by nikic** [comment]
At least for non-dynamic allocas, there is not specified allocation order.

Note that the gtest code uses GTEST_NO_INLINE_ -- if the allocas are in different functions, then the check should be reliable in practice (but of course also not guaranteed).
