### ISSUE TITLE
[llvm-18.1.8] cmake configuration

### ISSUE THREAD

**Issue by astralchan** [llvm/llvm-project#102811]
version: [18.1.8](https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/llvm-18.1.8.src.tar.xz)
log: [cmake log](https://gist.github.com/astralchan/744e55e17a96189da36b1880b1053f49)

# Issue

When building from the llvm-18.1.8 source in release tarballs, CMakeLists.txt:6 looks for

* `Modules` directory instead of the existing `modules` directory
* a file `CMakePolicy.cmake` not contained within `modules` 

# Reproduce

```
curl -LO https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/llvm-18.1.8.src.tar.xz
tar -Jxf llvm-18.1.8.src.tar.xz
cd llvm-18.1.8.src
cmake -B llvm-build -DCMAKE_BUILD_TYPE=Release > LOG.txt 2>&1
```

Possibly related to [issue #65453](https://github.com/llvm/llvm-project/issues/65453).

**Comment by paperchalice** [comment]
Ensure your directory has the following layout:
```sh
.
├── cmake # from https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/cmake-18.1.8.src.tar.xz
└── llvm-18.1.8.src # from https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/llvm-18.1.8.src.tar.xz
```
You can also use https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/llvm-project-18.1.8.src.tar.xz which contains all subprojects.

**Comment by astralchan** [comment]
Thanks that fixed it - I didn't know about the cmake.src archive.
