### ISSUE TITLE
clang/lib/Sema/SemaOverload.cpp: 2 * boolean in compare ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#102912]
Static analyser cppcheck says:

1.

clang/lib/Sema/SemaOverload.cpp:512:26: style: Comparison of a variable having boolean value using relational (<, >, <= or >=) operator. [comparisonOfBoolWithBoolError]

Source code is 

      return (FromWidth < ToWidth + (FromSigned == ToSigned)) &&
             (FromSigned <= ToSigned);

I am pretty sure comparison operators don't apply to booleans.

2.

clang/lib/Sema/SemaOverload.cpp:545:44: style: Comparison of a variable having boolean value using relational (<, >, <= or >=) operator. [comparisonOfBoolWithBoolError]

Duplicate.

**Comment by MitalAshok** [comment]
This was previously effectively `!(FromSigned && !ToSigned)` before I changed it with #78112

I make sense of it as: If `From` is "more" signed than `To` then it fails the check, which maps nicely to the comparison operator. The old one was less readable for me, especially when De Morgan'd as `!FromSigned || ToSigned`.

This is personal opinion, Clang maintainers might disagree. It's a very easy NFC fix.

**Comment by AaronBallman** [comment]
FWIW, when I was reviewing those changes, I *definitely* had to spend a while to convince myself that code was correct, so it probably would be reasonable to rewrite it.
