### ISSUE TITLE
[flang][openmp] Bad code for index variable used in "shared" clause

### ISSUE THREAD

**Issue by psteinfeld** [llvm/llvm-project#102961]
Here's a reproducer:
```
program bug
  implicit none
  integer :: i, j
  i = 0
  j = 0
  !$omp parallel shared(i)
    !$omp sections
      do i=1,10
        j = j + i
      end do
    !$omp end sections
  !$omp end parallel
  print *, "i: ", i
  if ( i==11 ) then
    print *,'ok'
  else
    print *,'fail, i: ', i
  end if
end program
```
When I compile this program with the `-fopenmp` option and execute it, I get the output:
```
 i:  0
 fail, i:  0
```
When similarly compiled with gfortran and executed, I get:
```
 ok
```

**Comment by tblah** [comment]
@Leporacanthicus how does this look? https://github.com/llvm/llvm-project/compare/main...tblah:llvm-project:ecclescake/shared_loop_var
