### ISSUE TITLE
`decltype(lambda)` has internal linkage

### ISSUE THREAD

**Issue by vogelsgesang** [llvm/llvm-project#102918]
For the code below (also see https://godbolt.org/z/or53Y5c9j for a slightly more realistic example)

```cpp
#include <map>

using my_less = decltype([](int a, int b) { return a < b; });
using my_map = std::map<int, int, my_less>;

my_map foo();

int main() {
    std::cerr << foo().size() << std::endl;
}
```

`clang++ -std=c++23 -Werror` reports the error

```
In file included from <source>:1:
/app/util.hpp:6:8: error: function 'foo' has internal linkage but is not defined [-Werror,-Wundefined-internal]
    6 | my_map foo();
      |        ^
<source>:5:18: note: used here
    5 |     std::cerr << foo().size() << std::endl;
      |                  ^
1 error generated.
Compiler returned: 1
```

Not sure if this is expected or not. I would have expected this to work

**Comment by vient** [comment]
Aren't lambdas always linked internally because each lambda has a unique type, even if their signatures are the same?

Your code compiles when my_less is defined as `using my_less = std::function<bool(int, int)>;`

**Comment by vogelsgesang** [comment]
> Aren't lambdas always linked internally because each lambda has an unique unspecified type, even if their signatures are the same?

After re-reading [P0315R4: Lambdas in unevaluated contexts](https://wg21.link/p0315r4), I think you right
