### ISSUE TITLE
Incorrect parse of simple-declaration containing two type-name template-ids

### ISSUE THREAD

**Issue by be579e8c-b74b-475b-a126-3b8cefdd833c** [llvm/llvm-project#10309]
|  |  |
| --- | --- |
| Bugzilla Link | [9937](https://llvm.org/bz9937) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
The following parses incorrectly in Clang:
```c++
template<typename T>
struct A { };

namespace N {
A<int> A<int>();
}
```
The second "A<int>" should not belong to the decl-specifier-seq, but to the init-declarator, and be the declarator-id of the simple-declaration.

It can be argued what the better error message ("cannot combine with previous 'type-name' declaration specifier" as it is now, or "template specialization requires 'template<>'" as it would if clang would parse it correctly), but it should be considered:

- Is the existing diagnostic better than what we would get if we parsed it correctly? Are both equally bad?
- Can there be well-formed code that would be made ill-formed by the current parse? (I can't think of any).
- Is the advantage of having a better diagnostic worth parsing this and other (afaics) ill-formed code the way it's parsed?

I don't have strong opinions about this, but I thought I would open a PR about it, so it can be considered generally :)

**Comment by philnik777** [comment]
Fixed in Clang 3.5: https://godbolt.org/z/P9Pdxv5W8
