### ISSUE TITLE
Clang does not recognize(use) constexpr features

### ISSUE THREAD

**Issue by socketpair** [llvm/llvm-project#103019]
```cpp
#include <algorithm>
#include <array>
#include <string_view>

using namespace std;

int main1() {
    constexpr array<string_view, 2> x{{"name1", "name2"}};
    constexpr auto f1 = find(x.cbegin(), x.cend(), "name1") - x.cbegin();
    constexpr auto f2 = find(x.cbegin(), x.cend(), "name2") - x.cbegin();

    return f1 + f2;
}

int main2() {
    array<string_view, 2> x{{"name1", "name2"}};
    auto f1 = find(x.cbegin(), x.cend(), "name1") - x.cbegin();
    auto f2 = find(x.cbegin(), x.cend(), "name2") - x.cbegin();

    return f1 + f2;
}
```

`-std=c++23 -O3 -Wall -Wextra`

https://godbolt.org/z/vxsMEcWx9

As you can see, gcc is smarter.

**Comment by socketpair** [comment]
The previous message is just a suggestion (the compiler may or may not detect such things). This one I think a bug. gcc works correctly.

https://godbolt.org/z/oMef5fdbd

```cpp
#include <algorithm>
#include <array>
#include <string_view>

using namespace std;

class MyTuple {
   public:
    MyTuple() {}
    constexpr size_t operator[](const string_view& k) const {
        return find(x.cbegin(), x.cend(), k) - x.cbegin();
    }

   private:
    static constexpr array<string_view, 2> x{{"name1", "name2"}};
};

int main() {
    MyTuple t;

    return t["name1"];
}
```

**Comment by Sirraide** [comment]
So the first one just seems like a case of GCC’s optimiser doing a better job here (unless GCC is for some reason eagerly constant-evaluating everything here).

The second case isn’t a bug: a `constexpr` function *may*, but need not, be evaluated at compile-time. You’d have to e.g. make that `operator[]` `consteval` to force evaluation at compile-time.

**Comment by dtcxzyw** [comment]
You can constant fold this with a larger inlining threshold `-mllvm -inline-threshold=300`: https://godbolt.org/z/1s715qGET
