### ISSUE TITLE
LWG2921: packaged_task and type-erased allocators

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#103598]
**Link:** https://wg21.link/LWG2921

**Comment by ldionne** [comment]
This issue has already been implemented and was created for tracking purposes only.

**Comment by frederick-vs-ja** [comment]
This is not implemented currently. The ctors that should be removed are still there, and not guarded by (at least) `_LIBCPP_STD_VER <= 14`.
https://github.com/llvm/llvm-project/blob/ffcff4af59712792712b33648f8ea148b299c364/libcxx/include/future#L1609-L1611
https://github.com/llvm/llvm-project/blob/ffcff4af59712792712b33648f8ea148b299c364/libcxx/include/future#L1699-L1701

IIUC [LWG2921](https://cplusplus.github.io/LWG/issue2921) & [LWG2976](https://cplusplus.github.io/LWG/issue2976) were implemented in d42db7e083ee0edda327782aa122ad6474c126d1 but reverted later in a2f3c63282330be0226158cdfdc27c4c2aef9cdc, but the documentation wasn't correctly reverted.
