### ISSUE TITLE
[lld][clang] I think we need a wine PE header for ELF binaries

### ISSUE THREAD

**Issue by trcrsired** [llvm/llvm-project#103710]
Wine has this special ```__wine_spec_nt_header```

https://github.com/wine-mirror/wine/blob/master/tools/winebuild/spec32.c#L738

is that possible to make lld to print this out so that we can easily build linux .so that can be used in wine PE environment?

**Comment by trcrsired** [comment]
@MaskRay

**Comment by MaskRay** [comment]
You can compile this file and link it into the executable. I don't think the linker needs to have special support.

**Comment by trcrsired** [comment]
> You can compile this file and link it into the executable. I don't think the linker needs to have special support.

how to?

**Comment by trcrsired** [comment]
> You can compile this file and link it into the executable. I don't think the linker needs to have special support.

```
/* File generated automatically; do not edit! */
/* This file can be copied, modified and distributed without restriction. */


	.section ".init","ax"
	jmp 1f
__wine_spec_pe_header:
	.skip 69632
1:

	.data
	.balign 8
	.globl __wine_spec_nt_header
.L__wine_spec_rva_base:
	.long 0x4550
	.short 0x8664
	.short 0
```
I don't think this works out without the help of linker since I do not where the RVA is. That information is linker only
