### ISSUE TITLE
[DAG] SDPatternMatch - add m_FPToUI / m_FPToSI matchers

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#103872]
Add m_FPToUI / m_FPToSI matchers for ISD::FP_TO_UINT / ISD::FP_TO_SINT nodes to SDPatternMatch.h and suitable test coverage to SelectionDAGPatternMatchTest.cpp

**Comment by jf-botto** [comment]
Hi 👋 ,
I've recently been looking into SelectionDAG recently, would love to pick this up if possible?
