### ISSUE TITLE
install target performs compiling and linking

### ISSUE THREAD

**Issue by fb3a6188-6309-4303-b7f5-77463eed41bd** [llvm/llvm-project#10382]
|  |  |
| --- | --- |
| Bugzilla Link | [10010](https://llvm.org/bz10010) |
| Version | 2.9 |
| OS | Linux |
| CC | @atrick |

## Extended Description 
make install seems to be performing linking and compiling in this target after a complete build. While it works, I think this is wrong : The install target's only job should be putting various things in the right place.

For a packager this means that testing the install target takes ages, which isn't nice with large packages such as llvm.
To be correct, this should be fixed.

**Comment by arsenm** [comment]
Makefiles were removed
