### ISSUE TITLE
`if consteval` within function template enters wrong branch

### ISSUE THREAD

**Issue by malchera** [llvm/llvm-project#104230]
Consider the following, contrived example:
```c++
#include <cassert>
#include <iostream>

consteval auto increment(int n) { return n + 1; }
auto decrement(int n) { return n - 1; }

template <typename T>
constexpr auto ct_increment(T x) {
    if consteval {
        return increment(x);
    } else {
        return decrement(x);
    }
}

int main() {
    // a is const(expr) -> should be incremented
    constexpr auto a = ct_increment(0);
    std::cout << "a = " << a << std::endl;
    static_assert(a == 1);

    // b is non-const -> should be decremented
    auto b = ct_increment(0);
    std::cout << "b = " << b << std::endl;
    assert(b == -1);
}
```
The initialization of variable `b` is not a [manifestly constant-evaluated context](https://en.cppreference.com/w/cpp/language/constant_expression#Manifestly_constant-evaluated_expressions) and therefore `ct_increment` should run into the `else` branch, which should decrement `b`. However, `b` is incremented, which is unexpected.
The expected behavior can be observed when compiling with non-clang (in [this](https://godbolt.org/z/zKa9vodjj) godbolt example I've compiled with gcc, EDG and icx (the latter is LLVM-based and exhibits the same behavior).

I noticed that this bug seems to be related to the function template. If I convert it to a non-template function, correct results are compiled (see also the `#if` in line 6 of the godbolt link).

**Comment by cor3ntin** [comment]
Fixed by https://github.com/llvm/llvm-project/pull/91939
