### ISSUE TITLE
LWG3404: Finish removing subrange's conversions from pair-like

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#104282]
**Link:** https://wg21.link/LWG3404

**Comment by frederick-vs-ja** [comment]
This should be considered Complete in 13.0 together with the completion of `subrange` (9106047ee3dd93a250deb1ef34b890f486dee710, https://reviews.llvm.org/D102006).

BTW, currenltly [LWG3281](https://cplusplus.github.io/LWG/issue3281) is said Complete in 15.0, but I think 13.0 should be correct.
