### ISSUE TITLE
LWG3406: `elements_view::begin()` and `elements_view::end()` have incompatible constraints

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#104284]
**Link:** https://wg21.link/LWG3406

**Comment by ldionne** [comment]
This issue has already been implemented and was created for tracking purposes only.

**Comment by Zingam** [comment]
Is this a GitHub bug? I see this issue as opened in the GitHub project view?

![Image](https://github.com/user-attachments/assets/eb3b9cbb-b9a8-43dc-ab64-7ad3fd21d242)

**Comment by ldionne** [comment]
I think it's a Github bug. Github projects have a few quirks TBH.

**Comment by ldionne** [comment]
They have fixed it after I reported it to them. It should work now.
