### ISSUE TITLE
[HLSL] Use unmangled name in `dx.resources` metadata to match DXC

### ISSUE THREAD

**Issue by hekota** [llvm/llvm-project#104257]
For [sample shader](https://godbolt.org/z/eK4K71r1s)
```
RWBuffer<int> In : register(u0);
RWBuffer<int> Out : register(u1);

[numthreads(8,1,1)]
void main(uint GI : SV_GroupIndex) {
  Out[GI] = In[GI] * In[GI];
}
```

DXC writes the resource type name in metadata unmangled and the resource variable name is stored in the following node:

```
!dx.resources = !{!25}
...
!25 = !{null, !26, null, null}
!26 = !{!27, !29}
!27 = !{i32 0, %"class.RWBuffer<int>"* undef, !"In", i32 0, i32 0, i32 1, i32 10, i1 false, i1 false, i1 false, !28}
!28 = !{i32 0, i32 4}
!29 = !{i32 1, %"class.RWBuffer<int>"* undef, !"Out", i32 0, i32 1, i32 1, i32 10, i1 false, i1 false, i1 false, !28}
```

Clang writes mangled name that contains both the type and variable name:

```
!dx.resources = !{!35}
...
!36 = !{!37, !39}
!37 = !{i32 0, ptr @"?In@@3V?$RWBuffer@H@hlsl@@A", !"", i32 0, i32 0, i32 1, i32 10, i1 false, i1 false, i1 false, !38}
!38 = !{i32 0, i32 4}
!39 = !{i32 1, ptr @"?Out@@3V?$RWBuffer@H@hlsl@@A", !"", i32 0, i32 1, i32 1, i32 10, i1 false, i1 false, i1 false, !38}
```
Should Clang match DXC?

**Comment by bogner** [comment]
These artifacts come from the "old" way of handling DXIL resources, and should go away once we fully transition to the target extension type based approach. However, the field for a ["Pointer to a global constant symbol with the original shape of resource and element type"](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#metadata-resource-records) will need to be populated correctly, which is tracked by https://github.com/llvm/llvm-project/issues/75981
