### ISSUE TITLE
LWG3523: `iota_view::sentinel` is not always `iota_view`'s sentinel

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#104336]
**Link:** https://wg21.link/LWG3523

**Comment by frederick-vs-ja** [comment]
This was mostly implemented together with `iota_view` in LLVM 14.0 (7b20e05c714e273ebe89d713cec61e5a022bbac6, https://reviews.llvm.org/D107396).

https://github.com/llvm/llvm-project/blob/7b20e05c714e273ebe89d713cec61e5a022bbac6/libcxx/include/__ranges/iota_view.h#L312-L325

But the constraints for the 3rd overload were initially incorrect and then got corrected in LLVM 17.0 (868591501c61bc1aa56da537bab85cc67439f16d, https://reviews.llvm.org/D150206).

Now:
https://github.com/llvm/llvm-project/blob/22e55ba3293f72df84de509db821b4d8a2c4c55e/libcxx/include/__ranges/iota_view.h#L320-L330
