### ISSUE TITLE
Bogus pedantic warning when using offsetof(type, field[n])

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#10437]
|  |  |
| --- | --- |
| Bugzilla Link | [10065](https://llvm.org/bz10065) |
| Version | 2.9 |
| OS | MacOS X |
| Attachments | [test code showing bogus pedantic offsetof warning](https://user-images.githubusercontent.com/60944935/143743242-e366471d-b48e-4acd-a669-93660ebb4b3d.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @AaronBallman,@efriedma-quic,@tkremenek |

## Extended Description 
If you use an expression like

  offsetof(struct hello_s, stuff[99])

when compiling with -ansi -pedantic, you get a warning "using extended field designator is an extension".  The C89 standard says:

"The member-designator shall be such that given

         static  type t;

then the expression &(t.  member-designator ) evaluates to an address
constant."

I can't find anything which says this is any kind of extension.  And,  for what it's worth, gcc's pedantic mode doesn't complain.

Test code attached.

**Comment by philnik777** [comment]
Fixed in Clang 6: https://godbolt.org/z/KK7W4o5Ea
