### ISSUE TITLE
[flang][cuda] Using the -x cuda option switch to cc1 instead of fc1

### ISSUE THREAD

**Issue by clementval** [llvm/llvm-project#104483]
When trying to compile a cuda fortran example with `-x cuda`, `cc1` is picked but `fc1` should still be used.

**Comment by clementval** [comment]
@banach-space Do you have any idea where this switch is made?

**Comment by banach-space** [comment]
Roughly here:

* https://github.com/llvm/llvm-project/blob/15e1e3b234884eb19b30e230ff783a13b499686f/clang/lib/Driver/ToolChain.cpp#L870-L878

**Comment by clementval** [comment]
Thanks for the pointer @banach-space !
