### ISSUE TITLE
C++23 default comparisons is incorrectly accepted

### ISSUE THREAD

**Issue by marco-antognini-sonarsource** [llvm/llvm-project#104414]
Sibling issue of #104413.

According to https://eel.is/c++draft/class.compare#default-1, the following program should be rejected by Clang but it isn't.

```cpp
struct A {
  bool operator==(this const A, const A&) = default;
};
```

Reproducible at https://godbolt.org/z/reoWEExM7

See also https://stackoverflow.com/a/78808748/24103368 from @brevzin.

**Comment by MitalAshok** [comment]
This will be fixed by #100419. See the added test: https://github.com/llvm/llvm-project/pull/100419/commits/f30d062c9d943c999ac06585e48e253aed976c54#diff-d2d5d9c1a136acc78ff155c17579ea99c417696cb9deafcb5d840c4302251598R999-R1000
