### ISSUE TITLE
clang incorrectly permits odr-use

### ISSUE THREAD

**Issue by androm3da** [llvm/llvm-project#104450]
> § 6.3 One-definition rule
> If a local entity is odr-used in a declarative region which is not odr-usable, the program is ill-formed.

This example below seems ~similar to the one in https://eel.is/c++draft/basic.def.odr#example-2 but it's not rejected by clang.

```
$ cat ~/tmp/odr.cpp 
void foo(auto x) {
  struct F {
    void bar() { x = 0; }
  };
}

```

```
$ clang++ --version
clang version 18.1.8
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/mnt/workspace/install/clang-latest/bin

$ clang++ -c ~/tmp/odr.cpp -std=c++20 ; echo $?
0

```

gcc does reject this:
```
$ g++ -c ~/tmp/odr.cpp -std=c++20
/usr2/bcain/tmp/odr.cpp: In member function ‘void foo(auto:1)::F::bar()’:
/usr2/bcain/tmp/odr.cpp:3:18: error: use of parameter from containing function
    3 |     void bar() { x = 0; }
      |                  ^
/usr2/bcain/tmp/odr.cpp:1:15: note: ‘auto:1 x’ declared here
    1 | void foo(auto x) {
      |          ~~~~~^
$ g++ --version
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by pinskia** [comment]
Note clang only errors out when the function template is instantiated. e.g.:
```
template<class T>
void foo(T x) {
  struct F {
    void bar() { x = 0; }
  };
}
void f()
{
        foo(1);
}
```

foo is not errored out at definition time but only at instantiation time.
This is also true with auto type argument (since it is a short hand for the above really).

**Comment by AaronBallman** [comment]
Clang rejects once the template is instantiated which is conforming behavior: https://godbolt.org/z/dcdorqxKz (Clang doesn't do semantic analysis of templates when the analysis would involve a dependent type; it waits until the template is (partially) instantiated and then performs the analysis on whatever non-dependent code it can.)
