### ISSUE TITLE
[MIPS] `MIPSELFObjectWriter::sortRelocs()` makes compilation near-unusably slow for O32

### ISSUE THREAD

**Issue by alexrp** [llvm/llvm-project#104562]
Building and running the Zig standard library tests (with LLVM 18.1.8):

```console
❯ time zig4 build -j8 -Dno-lib -Dno-bin -fqemu test-std -Dtest-target-filter=mips64- -Dtest-target-filter=mips64el-
________________________________________________________
Executed in  209.15 secs    fish           external
   usr time   18.17 mins  361.00 micros   18.17 mins
   sys time    1.02 mins   64.00 micros    1.02 mins
❯ time zig4 build -j8 -Dno-lib -Dno-bin -fqemu test-std -Dtest-target-filter=mips- -Dtest-target-filter=mipsel- -Dtest-slow-targets
________________________________________________________
Executed in   66.50 mins    fish           external
   usr time  242.35 mins    5.87 millis  242.35 mins
   sys time    1.06 mins    0.30 millis    1.06 mins
```

As a result of this, we've had to disable MIPS O32 tests for local development and only run them in CI.

Attaching a debugger made it clear that the overwhelming majority of time is spent in `MIPSELFObjectWriter::sortRelocs()`. Specifically (and perhaps unsurprisingly) here:

https://github.com/llvm/llvm-project/blob/ef6760116fa2fa21f78e7a3b499f77e1a3eb7b92/llvm/lib/Target/Mips/MCTargetDesc/MipsELFObjectWriter.cpp#L468-L476

Some extra context:

```
(gdb) p Relocs.size()
$3 = 1412282
(gdb) p Remainder.size()
$4 = 439999
(gdb) p Sorted.size()
$5 = 1019010
```

We build the standard library tests as one big executable so we end up with a ton of relocations. Due to the size of the resulting LLVM IR, I can't easily post it here. :slightly_frowning_face:

**Comment by alexrp** [comment]
> and only run them in CI

We're unfortunately [reverting](https://github.com/ziglang/zig/pull/21125) even this. The extra load on CI machines across concurrent runs has caused the run times to jump from 2-3 hours to 6-7, resulting in frequent timeouts.

**Comment by MaskRay** [comment]
/cherry-pick bf5cd4220d20d0ee5533d55f463612fbe2980071 59721f2326988ece58fab183971f79b71f751b83

**Comment by MaskRay** [comment]
/cherry-pick bf5cd4220d20d0ee5533d55f463612fbe2980071 59721f2326988ece58fab183971f79b71f751b83

**Comment by alexrp** [comment]
FWIW, I'm happy to help by doing the cherry-pick manually and PRing it if you're pressed for time. :slightly_smiling_face:

**Comment by brad0** [comment]
> FWIW, I'm happy to help by doing the cherry-pick manually and PRing it if you're pressed for time. 🙂

If you can that would be great.
