### ISSUE TITLE
[HLSL] Write tests for space inside register annotation

### ISSUE THREAD

**Issue by bob80905** [llvm/llvm-project#104521]
Register annotations `register(u0, space1)`, may involve an optional space parameter. This parameter should be tested for when it may be invalid (for example, non-numeric suffixes, being placed as the first argument, etc)

**Comment by bob80905** [comment]
`clang\test\SemaHLSL\resource_binding_attr_error.hlsl` already has sufficient testing coverage for the space parameter. Closing because this isn't an issue.

**Comment by damyanp** [comment]
I don't see any tests in that file to validate that an error is generated if you try and set a register space on a global.
