### ISSUE TITLE
-mtune not supported to the assembler

### ISSUE THREAD

**Issue by nlewycky** [llvm/llvm-project#10451]
|  |  |
| --- | --- |
| Bugzilla Link | [10079](https://llvm.org/bz10079) |
| Version | unspecified |
| OS | Linux |
| CC | @asl |

## Extended Description 
$ clang -c -Wa,-mtune=i686 conftest.c
clang: error: unsupported argument '-mtune=i686' to option '-Wa,'

To my surprise, GNU as actually has this flag. I'm not sure if there's anything to wire it up to in MC (what does it actually do in GNU as?), but it'd be useful if we didn't error on it.

**Comment by MaskRay** [comment]
In GNU assembler, `-mtune=` is implemented for mips, ia64, visium, and x86.
In the x86 port `-mtune=` just decides the desired NOP sequence.
In the ia64 port `-mtune=` does some complex scheduling.

Unless more significant uses arise, I don't think `-mtune=` justifies an integrated assembler option.

(Clang does not support `-Wa,-mtune=`. I dropped a glibc use in [i386: Remove -Wa,-mtune=i686](https://sourceware.org/git/?p=glibc.git;a=commit;h=c5bec9d491c5d066dd238ccafcdec78cd4592e8e).)
