### ISSUE TITLE
Warn on attribute mismatch between prototype and body

### ISSUE THREAD

**Issue by jsonn** [llvm/llvm-project#10474]
|  |  |
| --- | --- |
| Bugzilla Link | [10102](https://llvm.org/bz10102) |
| Version | trunk |
| OS | Linux |
| CC | @AaronBallman,@pageexec |

## Extended Description 
clang doesn't warn for the following when compiling for i386:

__attribute__((__regparm__(3))) int test(int);

int test(int a)
{
	return a;
}

GCC warns on i386 and silently accepts it on amd64. The GCC behavior is more useful here IMO.

**Comment by philnik777** [comment]
Closing this, since this has been open for years without any response.
