### ISSUE TITLE
Regression in InstCombine Pass: Missing Simplification of icmp with Bitwise AND and llvm.assume Condition

### ISSUE THREAD

**Issue by RonDahan101** [llvm/llvm-project#104772]
In LLVM 18.1.0, instCombine considered the llvm.assume condition and managed to prove that the branch is always false.

https://godbolt.org/z/181GG7vvE

Now, instCombine fails to simplify the branch's condition.

https://godbolt.org/z/z4xMT533G

**Comment by lquinn2015** [comment]
Just finished bisecting this will look into it but it seems stuff around this patch getting apply/ remove and reapplied cause the regression still trying to understand the change made  @nikic 

05670b42f5b45710bfdba48dcb7e8c30c8c7478f

**Comment by nikic** [comment]
@RonDahan101  Did this pattern occur in real-world code?

**Comment by lquinn2015** [comment]
I was looking into this and am not to sure where to go it seems like the change i listed above allows for a simplification in the 

%iters = icmp ult i32 %and, 8         ---->      %iters = icmp ult i32 %add, 8

The bits you assume are on %and and not on %add so there likely needs to be changes made to to LazyValueInfo   or CorrelatedValuePropogation passes. I haven't been able to figure out what should change there. Still pretty new to this :/ but that is kind of where i got to

![image](https://github.com/user-attachments/assets/a5b04f06-2644-4c17-9877-9a59607025da)

**Comment by dtcxzyw** [comment]
https://alive2.llvm.org/ce/z/-hCC7E
