### ISSUE TITLE
Flang rejects named constant of derived type in pure procedure

### ISSUE THREAD

**Issue by everythingfunctional** [llvm/llvm-project#104796]
I documented the issue in [another repo](https://github.com/HPC-Bugs/reproducers/tree/main/compiler/Fortran/flang/constant-in-pure), but the following example is sufficient to reproduce the error.

```fortran
program example
    type :: my_type
        integer :: val
    end type
    print *, thing()
contains
    pure function thing()
        type(my_type) :: thing
        type(my_type), parameter :: constant = my_type(42)
        thing = constant
    end function
end program
```

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/104821

**Comment by everythingfunctional** [comment]
Thanks @klausler . Glad it was simple enough to fix.
