### ISSUE TITLE
After this patch it is very hard to build lldb (debug version) on Windows.

### ISSUE THREAD

**Issue by medismailben** [llvm/llvm-project#104895]
After this patch it is very hard to build lldb (debug version) on Windows.
We got the errors like the following
```
D:\llvm-project\lldb\source\Plugins\ScriptInterpreter\Python\Interfaces\ScriptedThreadPlanPythonInterface\ScriptedThreadPlanPythonInterface.cpp: 
fatal error C1041: cannot open program database 'D:\build-lldb\tools\lldb\source\Plugins\ScriptInterpreter\Python\Interfaces\ScriptedThreadPlanPythonInterface\CMakeFiles\lldbPluginScriptInterpreterPythonScriptedThreadPlanPythonInterface.dir\lldbPluginScriptInterpreterPythonScriptedThreadPlanPythonInterface.pdb'; 
if multiple CL.EXE write to the same .PDB file, please use /FS
```
Note MAX_PATH is 260 on Windows. But the length of the path to .pdb is 262.
It is necessary to use 7 chars or less folder in the root of a disk to build lldb (debug version) on Windows using Microsoft VC++. 
You must reduce the length of the paths.

_Originally posted by @slydiman in https://github.com/llvm/llvm-project/issues/101672#issuecomment-2289481324_

**Comment by Naville** [comment]
Yeah MSBuild still lacks long path support. Use another generator like Ninja instead

**Comment by AaronBallman** [comment]
It might be nice to rename `ScriptedThreadPlanPythonInterface.cpp` to something a bit less wordy; it would be nice if there was a post-commit buildbot that built lldb on Windows with MSVC (not ninja) to help catch this sort of thing to avoid regressions.
