### ISSUE TITLE
clang asserts with ffp-contract=fast-honor-pragmas

### ISSUE THREAD

**Issue by andykaylor** [llvm/llvm-project#104830]
When I use "#pragma STDC FP_CONTRACT DEFAULT" and compile with "-ffp-contract=fast-honor-pragmas", clang asserts.

```
float f(float a, float b, float c) {
    #pragma STDC FP_CONTRACT DEFAULT
    return a * b + c;
}
```

See:

https://godbolt.org/z/EqE6Kn6Wf

**Comment by shafik** [comment]
Looks like this unreachable was added in cb08558caa3ba by @yxsamliu

**Comment by andykaylor** [comment]
> Looks like this unreachable was added in [cb08558](https://github.com/llvm/llvm-project/commit/cb08558caa3bad69213b08e6361586491232c745) by @yxsamliu

Yes. I'm about to upload a fix.
