### ISSUE TITLE
Superfluous instructions when using `_mm_set_ss` with `-ffp-model=strict` on `x86_64`

### ISSUE THREAD

**Issue by jerryct** [llvm/llvm-project#104848]
When using the intrinics `_mm_set_ss` with `-ffp-model=strict` compiler flag
Clang generates two seemingly unrelated instructions (neither `eax` nor `xmm1` are used by `andps`)

```
        xor     eax, eax
        cvtsi2ss        xmm1, eax
        andps   xmm0, xmmword ptr [rip + .LCPI1_0]
```

reproducer: https://godbolt.org/z/3fj6ob345

For example when switching to `_mm_load_ps1` instead the instructions
are not generated:  https://godbolt.org/z/8G6vGEjxE

**Comment by DTeachs** [comment]
Can this be backported to 19.x since this is trivial and safe?

**Comment by RKSimon** [comment]
/cherry-pick 3b49d274e6f16d1c8db5f4557eb7866a4bafffa5 6dcce422ca06601f2b00e85cc18c745ede245ca6
