### ISSUE TITLE
[AMDGPU] InstCombine results in performance drop in ROCM's rocRAND library in MI100

### ISSUE THREAD

**Issue by vg0204** [llvm/llvm-project#104900]
Instruction folding done in #94887 causes performance drop in the benchmark testcase for normal-double distribution for mt19937 randomizer engine. {in AMD MI100 device }

The expected result should be : 

```
benchmark_rocrand_generate
rocRAND: 300100 Runtime: 60241133 Device: AMD Instinct MI100

mt19937:
  normal-double:
      Throughput =  264.408 GB/s, Samples =   33.051 GSample/s, AvgTime (1 trial) =    3.782 ms, Time (all) =   75.641 ms, Size = 134217728
```

But, the mentioned PR causing drop in throughput as follows :
```
benchmark_rocrand_generate
rocRAND: 300100 Runtime: 60241133 Device: AMD Instinct MI100

mt19937:
  normal-double:
      Throughput =  248.093 GB/s, Samples =   31.012 GSample/s, AvgTime (1 trial) =    4.031 ms, Time (all) =   80.615 ms, Size = 134217728
```

**Comment by vg0204** [comment]
@c8ef, as the instruction folding is being performed for an exponent-based instruction, it supposedly should be done only if approxFunc bit of fastMathFlag is set I feel. This solved the performance drop problem as I tried it locally for mentioned specific testCase. Will do it for entire benchmark test suite & will let you know!

**Comment by arsenm** [comment]
> @c8ef, as the instruction folding is being performed for an exponent-based instruction, it supposedly should be done only if approxFunc bit of fastMathFlag is set I feel. 

No, this does not require additional flags. It is an exact transformation (that only has the avoided overflow reassoc issue) 



> This solved the performance drop problem as I tried it locally for mentioned specific testCase. Will do it for entire benchmark test suite & will let you know!

This should be exact and always faster. I doubt this transform is directly responsible for the performance loss and more investigation is needed

**Comment by vg0204** [comment]
> > @c8ef, as the instruction folding is being performed for an exponent-based instruction, it supposedly should be done only if approxFunc bit of fastMathFlag is set I feel.
> 
> No, this does not require additional flags. It is an exact transformation (that only has the avoided overflow reassoc issue)
> 
> > This solved the performance drop problem as I tried it locally for mentioned specific testCase. Will do it for entire benchmark test suite & will let you know!
> 
> This should be exact and always faster. I doubt this transform is directly responsible for the performance loss and more investigation is needed. Do you have IR and ISA diffs?

Working on it to extract it

**Comment by vg0204** [comment]
The mainly observed IR pattern difference (immediately after instcombine pass incorporating mentioned intruction folding) is as follows :

Without the Idexp folding.
```
%30 = tail call { double, i32 } @llvm.frexp.f64.i32(double %add.i.i.i)
%31 = extractvalue { double, i32 } %30, 0
%32 = fcmp olt double %31, 0x3FE5555555555555
%33 = zext i1 %32 to i32
%34 = tail call double @llvm.ldexp.f64.i32(double %31, i32 %33)
%35 = extractvalue { double, i32 } %30, 1
%36 = sub nsw i32 %35, %33
```

With Idexp folding.
```
%30 = tail call { double, i32 } @llvm.frexp.f64.i32(double %add.i.i.i)
%31 = extractvalue { double, i32 } %30, 0
%32 = fcmp olt double %31, 0x3FE5555555555555
%.neg.i = sext i1 %32 to i32
%33 = select i1 %32, double 2.000000e+00, double 1.000000e+00
%34 = fmul double %31, %33
%35 = extractvalue { double, i32 } %30, 1
%36 = add i32 %35, %.neg.i
```

And  these are mathematically equivalent.

**Comment by vg0204** [comment]
As for the final ISA difference in assembly file, while those ldexp not folded gets translated into AMD's v_ldexp instruction, the others got folded translates into bunch of instruction along the lines of above mentioned IR.

Could it the case that the machine's specialized v_ldexp might perform better than folding llvm@ldexp and translating into machine instruction?

**Comment by arsenm** [comment]
> As for the final ISA difference in assembly file, while those ldexp not folded gets translated into AMD's v_ldexp instruction, the others got folded translates into bunch of instruction along the lines of above mentioned IR.

Post the diff of the actual ISA, preferably with IR you can also use to reproduce it

> 
> Could it the case that the machine's specialized (AMDGPU) v_ldexp might perform better than folding llvm@ldexp and translating the lowered IR into machine instruction?

ldexp is always the same number of cycles as fmul, and the select is also as cheap as the original extend

**Comment by vg0204** [comment]
Attached zip file contain IR immediately after instCombine pass for both with & without ldexp folding, & the diff between the final assembly.
[fail-after-instcombine.zip](https://github.com/user-attachments/files/16833331/fail-after-instcombine.zip)
[FinalAssemblyDiff.zip](https://github.com/user-attachments/files/16833336/FinalAssemblyDiff.zip)
[pass-after-instcombine.zip](https://github.com/user-attachments/files/16833337/pass-after-instcombine.zip)

**Comment by vg0204** [comment]
ping @arsenm

**Comment by vg0204** [comment]
> > ping @arsenm
> 
> It would be more helpful if you posted full the full IR not the -print-before (which adds the comments, and missing the global pieces needed for compilable IR), and the full ISA (not the diff)
> > > You mean the IR after every pass that transforms it?
> 
> In this case I think I see the issue in the ISA diff. The critical change is _ZN12rocrand_impl4hostL20generate_long_kernelINS0_23default_config_providerIL16r (and one other kernel) happened to go from 128 VGPRs to 129 VGPRs, so the occupancy dropped. These kernels probably should just be using an explicit occupancy bounds.
> 
> However I do see the codegen is worse in the f64 case, due to how the select gets broken up. I think we need to undo this transform in codegen, for f64. https://godbolt.org/z/Eb5csW35j
> 
> > > I see it! 
> This is essentially a non-constant variant of [29fff3e](https://github.com/llvm/llvm-project/commit/29fff3e2ab880449182626810c326d21944a88bf). The 32-bit select is cheaper than the 64-bit select (and 64-bit constants) both of which get split up

**Comment by vg0204** [comment]
> However I do see the codegen is worse in the f64 case, due to how the select gets broken up. I think we need to undo this transform in codegen, for f64. https://godbolt.org/z/Eb5csW35j

This is aligned with the fact the test facing the perf drop is of f64 type generating normal distribution. Should I attempt it locally to investigate whether it solves the perf drop problem?

**Comment by vg0204** [comment]
> It would be more helpful if you posted full the full IR not the -print-before (which adds the comments, and missing the global pieces needed for compilable IR), and the full ISA (not the diff)

Here in this zip file has the full IR & ISA for both the scenarios :
[rocRand-ldexp-ticket-info.zip](https://github.com/user-attachments/files/17163798/rocRand-ldexp-ticket-info.zip)

**Comment by arsenm** [comment]
Yes, write the new dag combine

**Comment by vg0204** [comment]
What's wrong with this Dag pattern match as it is giving compilation error i.e.,  Type set is empty for each HW mode in 'anonymous_34828'  & zext cannot be used in output pattern!
```
def : GCNPat<
  (any_fmul (f64 (VOP3Mods f64:$src0, i32:$src0_mods)), 
    (f64 (select i1:$cond, (f64 2), (f64 1)))),
  (V_LDEXP_F64_e64 i32:$src0_mods, VSrc_b64:$src0,
                   0, (i32 (zext i1:$cond)))
>;
```

**Comment by vg0204** [comment]
@arsenm, currently, I am writing pre-commit test for ldexp folding (for AMDGPU, as its not there), in order to test my DAG combine over it. So, I have a question on how you decide on what mtriples & mcpu it should be tested on considering  [29fff3e](https://github.com/llvm/llvm-project/commit/29fff3e2ab880449182626810c326d21944a88bf) test cases?

**Comment by arsenm** [comment]
> @arsenm, currently, I am writing pre-commit test for ldexp folding (for AMDGPU, as its not there), in order to test my DAG combine over it. So, I have a question on how you decide on what mtriples & mcpu it should be tested on considering [29fff3e](https://github.com/llvm/llvm-project/commit/29fff3e2ab880449182626810c326d21944a88bf) test cases?

Triple rarely matters, default to amdgcn-amd-amdhsa unless testing graphics calling conventions. 

For this should test a <= gfx9 and a gfx10 >=. The 9/10 threshold is relevant for the change in constant bus limit, and addition of vop3 literals

**Comment by vg0204** [comment]
@arsenm, I think for f16 also dagCombine might be needed https://godbolt.org/z/v1j1vxzqW ?

**Comment by arsenm** [comment]
> https://godbolt.org/z/v1j1vxzqW

Yes, the f16 constants are not 32-bit inline constants, so it's better to use the ldexp since it uses nicer integer values

**Comment by vg0204** [comment]
As you suggested to add bfloat case in its pre-commit tests (https://github.com/llvm/llvm-project/pull/111107), thought of testing it for bf16 as well. Can you once look & suggest the necessary as ASM is quite big got bf16.
https://godbolt.org/z/jdET15frY

**Comment by arsenm** [comment]
> https://godbolt.org/z/jdET15frY

First case looks better, the bfloat case is too far removed from the final instructions do to all the promotion handling

**Comment by vg0204** [comment]
> > https://godbolt.org/z/jdET15frY
> 
> First case looks better, the bfloat case is too far removed from the final instructions do to all the promotion handling

Sure
