### ISSUE TITLE
(in_file_option "-i") does not work

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#10490]
|  |  |
| --- | --- |
| Bugzilla Link | [10118](https://llvm.org/bz10118) |
| Version | 2.8 |
| OS | Linux |
| Attachments | [.inc](https://user-images.githubusercontent.com/60944935/143743296-dfa00604-efe0-4660-b8b2-0565fd20f60a.gz), [.td](https://user-images.githubusercontent.com/60944935/143743297-9761acb2-0b0e-4839-b392-e5bb0a6075c7.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Hi, 
  I would like to create compiler driver llvmc. But as soon as I use in file option, error is reported. I use the examples/Skeleton/Autogenerated.td file and the error is reported in Autogenerated.inc. 

Error looks like that:
AutoGenerated.inc: In member function ‘virtual int<unnamed>::assembler2::GenerateAction(llvmc::Action&, const llvmc::PathVector&, bool, const llvm::sys::Path&, const llvmc::InputLanguagesSet&, const llvmc::LanguageMap&) const’:
AutoGenerated.inc:92: error: expected ‘)’ before ‘;’ token
AutoGenerated.inc: In member function ‘virtual int<unnamed>::assembler2::GenerateAction(llvmc::Action&, const llvm::sys::Path&, bool, const llvm::sys::Path&, const llvmc::InputLanguagesSet&, const llvmc::LanguageMap&) const’:
AutoGenerated.inc:128: error: expected ‘)’ before ‘;’ token

I attach Autogenerated.td as well as Autogenerated.in

**Comment by asl** [comment]
llvmc is dead
