### ISSUE TITLE
Need warning group for "local declaration of 'foo' hides instance variable" warning

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#10494]
|  |  |
| --- | --- |
| Bugzilla Link | [10122](https://llvm.org/bz10122) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
See http://stackoverflow.com/questions/6311126/how-to-disable-the-local-declaration-of-foo-hides-instance-variable-warning ; it isn't possible to disable this warning at the moment.

**Comment by Endilll** [comment]
It's been under `-Wshadow` control for a while:
https://godbolt.org/z/MxojWdM4j
