### ISSUE TITLE
[HLSL] Emit dx.handle.fromBinding instead of dx.create_handle when resource is created 

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#105076]
Currently when we generate the constructor for resources in HLSLExternalSemaSource, we emit the `dx.create_handle` intrinsic. We need to update this to emit `dx.handle.fromBinding` instead as part of the transition to using target extension types for resources. The call to this intrinsic should capture the binding information from the `HLSLResourceBindingAttr` on the decl.

The decl with the binding information is not accessible from the resource constructor thought. The `dx.handle.fromBinding` calls need to be emitted for all resources at the beginning of the entry point function based on the resource binding information collected in task llvm/llvm-project#58051.

In the future, we'll need to handle cases where this should generate other handle creation functions like `dx.handle.fromHeap`, but that's out of scope of this task.

The `dx.create_handle` intrinsic will no longer be used after this and can be removed.

**Comment by damyanp** [comment]
Plan is to implement this using the "simple" way and tackle moving it to use constructors later.

@hekota: please create an issue tracking doing this with constructors / the more "right" way, and link it here.
