### ISSUE TITLE
[DirectX] Enable the Scalarizer pass in the DirectX backend

### ISSUE THREAD

**Issue by farzonl** [llvm/llvm-project#105178]
We need to do a few things here:
- [x]  Add the legacy pass scalarizer interface back
- [x]  Hook it up to the  DirectX backend
- [x]   Turn on the load store flag so loads and stores scalarize
- [x]  Update the non dx intrinsic test cases.

**Comment by davidcook-msft** [comment]
Will estimate after a final design is agreed upon.
