### ISSUE TITLE
llvm-as incorrectly flags multiple declarations as multiple definitions

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#10528]
|  |  |
| --- | --- |
| Bugzilla Link | [10156](https://llvm.org/bz10156) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
If a function is declared multiple times in bitcode, TOT now issues an error about it being multiply defined:

% echo "declare i1 @&#8203;foo()\ndeclare i1 @&#8203;foo()\n" | llvm-as
llvm-as: <stdin>:2:12: error: invalid redefinition of function 'foo'
declare i1 @&#8203;foo()
           ^
%

**Comment by arsenm** [comment]
This is correct, IR is not C and you're not supposed to be able to redeclare the same thing
