### ISSUE TITLE
P2874R2: Mandating Annex D Require No More

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#105377]
**Link:** https://wg21.link/P2874R2

**Comment by frederick-vs-ja** [comment]
Almost all changes in this paper are pure wording style improvements, except for the following:

> _Mandates_: The value type of `Source` and `InputIterator` is `char` or `char8_t`.

The _Mandates_ is split from the former _Requires_.

I believe this was completed in LLVM 12.0 by 6be11e35d5397ae1c117eb840a969585fdd7d08d (https://reviews.llvm.org/D90222).
