### ISSUE TITLE
Using address of global non-weak is tautologic

### ISSUE THREAD

**Issue by jsonn** [llvm/llvm-project#10541]
|  |  |
| --- | --- |
| Bugzilla Link | [10169](https://llvm.org/bz10169) |
| Version | trunk |
| OS | Linux |
| CC | @tkremenek,@seanm |

## Extended Description 
```c
int foo;

int main(void)
{
  return &foo ? 1 : 0;
}
```
gives a warning with GCC 4.5.

Possible exceptions are: section, weak or weakref attribute set. This warning triggered at least one real bug in the NetBSD code base, so it is useful to have.

**Comment by philnik777** [comment]
Fixed in Clang 3.5: https://godbolt.org/z/34YqWjhnh
