### ISSUE TITLE
Clang fails to compile correct program with consteval

### ISSUE THREAD

**Issue by socketpair** [llvm/llvm-project#105558]
https://godbolt.org/z/3o1G81ahn

```cpp

#include <array>
#include <iostream>
#include <ranges>
#include <string>

using namespace std;

template <size_t N>
consteval auto make_static(const string& str) {
    array<char, N> arr;
    str.copy(arr.data(), arr.size());
    return arr;
}

consteval string foo() { return string("some dynamic data") + " 42\n"; }

int main() {

// WORKS:
//    constexpr auto xxx = make_static<foo().size()>(foo());
//    cout << (xxx | ranges::to<string>());

   cout << (make_static<foo().size()>(foo()) | ranges::to<string>());

    return 0;
}
```

Clang fails to compile correct (I think yes :) program. GCC works. UB ?

**Comment by cor3ntin** [comment]
Note that this compiles with libc++ - we need a reduction to figure out what libstdc++ is doing

**Comment by Endilll** [comment]
I reduced the original example with the help of C-Reduce (https://godbolt.org/z/qv5TGWcj8):
```cpp
namespace std {

template < typename >
struct allocator {
  constexpr char *allocate() {
    return static_cast< char * >(operator new(0));
  }
};

struct __cxx11_basic_string {
  struct _Alloc_hider {
    char* _M_p;
  } _M_dataplus;
  
  constexpr __cxx11_basic_string() : _M_dataplus() {
    allocator< char > __a;
    _M_dataplus._M_p = __a.allocate();
  }
};

} // namespace std

consteval std::__cxx11_basic_string foo() {
  return {};
}

int main() {
  (void)foo();
}
```
One can go further and inline the allocator, but it changes the diagnostics, so decided to stop there.

**Comment by socketpair** [comment]
@Endilll so my example is correct? i.e. what I really need is for clang to create some byte array (string) based on constants at compile time. I'm not sure if std::string can be used for this purpose according to standards and requirements. If it works sometimes - then there is something like UB - i.e. it may or may not work. What solution is guaranteed to work? On one hand, expressions with `new` cannot be constant, but on the other hand, they work.

**Comment by MitalAshok** [comment]
@Endilll I don't think that's quite right because calling that function will never be a constant expression by itself because the destructor isn't called in the immediate-invocation. Something more like this would be closer: https://godbolt.org/z/Eaz918nTq

Which I think can be reduced to: https://godbolt.org/z/obzMses48

```c++
struct minimal_unique_ptr {
  int* p;
  constexpr minimal_unique_ptr(int* p) : p(p) {}
  minimal_unique_ptr(minimal_unique_ptr&&) = delete;
  constexpr ~minimal_unique_ptr() { delete p; }
};

consteval minimal_unique_ptr f(int i) {
  return minimal_unique_ptr(new int(i));
}

consteval void g(minimal_unique_ptr) {}
consteval void h(minimal_unique_ptr const&) {}

int main() {
  g(f(0)); // no error on both gcc and clang
  h(f(0)); // error on clang only
  h(minimal_unique_ptr(new int(0))); // no error on both gcc and clang
  // (last one is an error with clang if constructor is made consteval)
}
```

It seems like Clang doesn't consider binding to a temporary to be a subexpression of the immediate invocation `h(...)`, which doesn't look right.
