### ISSUE TITLE
Clang seemingly ignores `noinline` attribute

### ISSUE THREAD

**Issue by pkasting** [llvm/llvm-project#105578]
Clang seems to ignore `[[gnu::noinline]]` (and equivalent spellings) in at least some cases where gcc respects it. For example, when compiling the following code with `-O1`, Clang optimizes away the call to `F0()` in `F()`, while gcc does not:
```
[[gnu::noinline]] int F0() { return 0; }
int F1() { return 1; }

int F() {
  return F0() + F1();
}
```
Live example: https://godbolt.org/z/TaK5Gh485 (see generated assembly)

Curiously, with `-Os` both compilers inline the call. This seems like a bug to me also, but maybe I'm mistaken.

**Comment by pkasting** [comment]
Turns out this is due to constant-folding; see also https://stackoverflow.com/questions/54481855/clang-ignoring-attribute-noinline/54482070#54482070.

Changing the code to https://godbolt.org/z/caaj8KT9G makes this more clear.

**Comment by zmodem** [comment]
This comes  up regularly (I think most recently #98458).

There's been talk about implementing the `noipa` attribute (no inter-procedural analysis), which would prevent this kind of optimization, but that's currently stalled. I think the latest on that is https://reviews.llvm.org/D101011
