### ISSUE TITLE
[X86] llvm-mca reports wrong data for vpscatterqd, vscatterqps with -mcpu=skylake-avx512

### ISSUE THREAD

**Issue by mikolaj-pirog** [llvm/llvm-project#105675]
llvm-mca with -mcpu=skx (or skylake-avx512 or common-avx512) reports wrong data (1==latency==uops==throughtput) for theses asm instructions:

` vpscatterqd	ymmword ptr [rsp + zmm0 + 16] {k1}, ymm1`
` vscatterqps	ymmword ptr [rsp + zmm0 + 16] {k1}, ymm1`

For their xmmword and qword the numbers reported are fine. For other newer -mcpu options the numbers are also fine. The llvm-mca version is 20.0.0git.

**Comment by RKSimon** [comment]
we haven't gotten much llvm-mca test coverage for scatter - I'll get that added first

**Comment by goldsteinn** [comment]
I think this is causing https://lab.llvm.org/buildbot/#/builders/155/builds/1675 failure

**Comment by cjappl** [comment]
Put a revert up for review to try to unblock some of the build machines:

https://github.com/llvm/llvm-project/pull/105716

**Comment by cjappl** [comment]
Re-opened because I submitted that reversion, see: https://github.com/llvm/llvm-project/commit/e738c816f2079e2f0fdc395e53070cc1afd8bfac

**Comment by RKSimon** [comment]
Sorry for breakage, I'll get it fixed properly when I'm back in the office

**Comment by stefson** [comment]
can you maybe backport the fix to 19.x branch?

**Comment by RKSimon** [comment]
/cherry-pick 6ec4c9c3eb4a556f848dac37a2d6f0d46ecc6f02 7faf2c95a4f1c3148c891608ed516eda3c9d3eb4 cf6cd1fd67356ca0c2972992928592d2430043d2

**Comment by RKSimon** [comment]
/cherry-pick 3276ee30226de1572bde5bd3716a1d343bbb3657 6ec4c9c3eb4a556f848dac37a2d6f0d46ecc6f02 7faf2c95a4f1c3148c891608ed516eda3c9d3eb4 cf6cd1fd67356ca0c2972992928592d2430043d2
