### ISSUE TITLE
[HLSL] Update DXIL/SPIRV hybrid CodeGen tests to use a temp variable representing interchange target

### ISSUE THREAD

**Issue by pow2clk** [llvm/llvm-project#105710]
@farzonl suggested creating this issue to update some existing hybrid tests to leverage the regexp variables in filecheck to minimize duplication of CHECK lines. 

See https://github.com/llvm/llvm-project/blob/319c7a42ba2e5be56757d622747ba317d3b9e9ad/clang/test/CodeGenHLSL/builtins/dot.hlsl#L22-L30

**Comment by AmrDeveloper** [comment]
Interested, I can work on it

**Comment by pow2clk** [comment]
Hey great! I don't have a list of tests that might need this treatment, but they will all be in the same directory: https://github.com/llvm/llvm-project/tree/319c7a42ba2e5be56757d622747ba317d3b9e9ad/clang/test/CodeGenHLSL
