### ISSUE TITLE
[clang] Unexpected Initialization of Private Member in Clang

### ISSUE THREAD

**Issue by arvidjonasson** [llvm/llvm-project#105711]
## Description
When compiling C++11 code with Clang (versions 3.2 through 18.1), there's an unexpected behavior where a large array within a private member is initialized (using `memset`), while the same array in other contexts remains uninitialized.

## Minimal Reproducer
```cpp
struct UninitializedData {
  UninitializedData() noexcept {}
  unsigned long long size = 0;
  unsigned char arr[1024 * 1024];
};

class AsPublic {
public:
  UninitializedData data;
};

class AsPrivate {
private:
  UninitializedData data;
};

template<typename T>
void acceptAnything(T);

void testUninitializedData() {
    UninitializedData* p = new UninitializedData{};
    acceptAnything(p);
}

void testAsPublic() {
    AsPublic* p = new AsPublic{};
    acceptAnything(p);
}

void testAsPrivate() {
    AsPrivate* p = new AsPrivate{};
    acceptAnything(p);
}
```
## Assembly
```assembly
testUninitializedData():
        push    rax
        mov     edi, 1048584
        call    operator new(unsigned long)@PLT
        mov     qword ptr [rax], 0
        mov     rdi, rax
        pop     rax
        jmp     void acceptAnything<UninitializedData*>(UninitializedData*)@PLT

testAsPublic():
        push    rax
        mov     edi, 1048584
        call    operator new(unsigned long)@PLT
        mov     qword ptr [rax], 0
        mov     rdi, rax
        pop     rax
        jmp     void acceptAnything<AsPublic*>(AsPublic*)@PLT

testAsPrivate():
        push    rbx
        mov     edi, 1048584
        call    operator new(unsigned long)@PLT
        mov     rbx, rax
        mov     edx, 1048584
        mov     rdi, rax
        xor     esi, esi
        call    memset@PLT
        mov     rdi, rbx
        pop     rbx
        jmp     void acceptAnything<AsPrivate*>(AsPrivate*)@PLT
```
https://godbolt.org/z/93K1TE8Ph

## Expected Behavior
~~The `arr` member should remain uninitialized in all three test cases: `testUninitializedData()`, `testAsPublic()`, and `testAsPrivate()`.~~

EDIT: Upon further investigation, it is no longer clear to me whether the `arr` member should get initialized or not in this context. [GCC bug 112666](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=112666) suggests that their interpretation is that `arr` should be initialized in all but `testUninitializedData()`'s case. However, GCC's behaviour is not consistent in this regard (see: [GCC bug 116469](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116469)). Regardless of the intended standard, I would expect Clang to exhibit consistent behavior between private and public members, which is not currently the case.

## Actual Behavior
In Clang (versions 3.2 through 18.1), the `arr` member is initialized (using `memset`) only in the `testAsPrivate()` case. It remains uninitialized in the other two cases.

## Environment
- Compiler: Clang 3.2 through 18.1 (expected behaviour from Clang 3.1 and 3.0)
- Language: C++11

## Additional Context
GCC 6.1 and later does not initialize `arr` in any of the functions, while GCC 5.5 and earlier initialize `arr` in `testAsPublic`, `testAsPrivate` but not `testUninitializedData`.

The unexpected initialization could lead to performance issues, especially when dealing with large arrays or in performance-critical code where unnecessary initialization is undesirable.

## Questions
1. Is this behavior intentional or a bug?
2. If intentional, what's the rationale behind initializing private member arrays but not public ones?
3. If a bug, are there any known workarounds to prevent this initialization?

**Comment by efriedma-quic** [comment]
IRGen queries CXXConstructExpr::requiresZeroInitialization(), and if it's true, calls memset before running the constructor.  This is based off the rules to "value-initialize" an object (https://eel.is/c++draft/dcl.init#def:value-initialization).  As far as I can tell, everything is behaving correctly.

**Comment by arvidjonasson** [comment]
@efriedma-quic Thanks for the input. Can you confirm that zero initialization is not required when the sub object is public, as in the case of `testAsPublic()`? Thanks!

**Comment by AaronBallman** [comment]
Oh, I think I see what's going on here. It's the `{}` after the `new` which causes list initialization. And list initialization will defer to aggregate initialization (https://eel.is/c++draft/dcl.init#list-3.4) before value initialization (https://eel.is/c++draft/dcl.init#list-3.5). The private member makes the class not an aggregate (https://eel.is/c++draft/dcl.init.aggr#1.2).

For an aggregate, we wind up default initializing (which performs no initialization), and for a non-aggregate we wind up value initializing (which does zero initialization).

So I think this is expected behavior. The workaround is to drop the `{}` from the call to `new`: https://godbolt.org/z/dGen67bbE

**Comment by arvidjonasson** [comment]
@AaronBallman Thanks for a thorough explaination. This looks correct so I'll close this issue.
