### ISSUE TITLE
[clang-format] Ternary operator with unparenthesized comparison regression

### ISSUE THREAD

**Issue by joelhock** [llvm/llvm-project#105877]
clang-format version 18 would format this way:
```cpp
bool outofbounds = checklower ? a < b : a > b;
```
but version 19.1.0-rc3 formats instead:
```cpp
bool outofbounds = checklower ? a<b : a> b;
```
there is an easy workaround of putting parentheses around the comparisons, but it'd be nice to get the previous correct formatting.

**Comment by owenca** [comment]
Bisected to 834ac2e205dd8e492d6084a7952e68e19a1f54db. @rymiel
