### ISSUE TITLE
[clang-format] C-style cast with extra parentheses as first term of binary operator regression

### ISSUE THREAD

**Issue by joelhock** [llvm/llvm-project#105880]
clang-format version 18 would format this way:
```cpp
int result = ((int) a) - b;
```
but version 19.1.0-rc3 formats instead:
```cpp
int result = ((int) a) -b;
```
there is an easy workaround of removing the extra parentheses or using a c++-style cast like `static_cast<>`, but it'd be nice to get the previous correct formatting.

**Comment by owenca** [comment]
Bisected to 8c7a038f9029c675f2a52ff5e85f7b6005ec7b3e.
