### ISSUE TITLE
[C++20] [Modules] clang should find CNTTP type from partition even if not exported

### ISSUE THREAD

**Issue by ldalessa** [llvm/llvm-project#105882]
```c++
a.cpp
module mod:a;
struct A { consteval A(int) {} };

mod.cpp
export module mod;
import :a;
export template <A> struct B{};

main.cpp
import mod;
B<0> b; // CNTTP type A from mod:a is not exported, but should be found anyway
```

[godbolt](https://modules.godbolt.org/z/djE7fozdT)

* I have a module partition that defines a type, `A`, that is never exported. 
* I have a type `B` that _is_ exported and depends on `A` in CNTTP. 
* I have a client that imports the module, and instantiates `B` without explicitly naming `A`.

I believe that this should work. It _does_ work if `A` is not in a partition, and it works in gcc.

**Comment by ldalessa** [comment]
It's not just CNTTP that's the problem. If I simply return a value of a type from a partition that's not exported I run into the same challenge. I think it's _any_ transitive use of such a type from a partition.

```c++
a.cpp
module mod:a;
struct A {};

mod.cpp
export module mod;
import :a;
export struct B{
    A get() { return {}; }
};

main.cpp
import mod;
B b;
auto a = b.get(); // should be fine
```

[godbolt](https://modules.godbolt.org/z/W6hWeobbq)

**Comment by ldalessa** [comment]
This appears to be a misunderstanding on my part. For `A` to be reachable I guess it is necessary for `mod:a` to be a module interface unit, not just an implementation. I can fix this be exporting `mod:a` even though it has no exported objects.

```c++
a.cpp
export module mod:a; // export here, even though no exports
struct A {};

mod.cpp
export module mod;
export import :a; // export here necessary

export struct B{
    A get() { return {}; }
};

main.cpp
import mod;
B b;
auto a = b.get(); // should be fine
```

[godbolt](https://modules.godbolt.org/z/h84YPzsad)

**Comment by ChuanqiXu9** [comment]
Yeah, this is relevent: https://clang.llvm.org/docs/StandardCPlusPlusModules.html#reachability-of-internal-partition-units
