### ISSUE TITLE
[Clang] Error on pack indexing in return type

### ISSUE THREAD

**Issue by Sirraide** [llvm/llvm-project#105900]
Consider (https://godbolt.org/z/3ThcG9r9d):
```c++
template <typename... opts>
struct temp  {
    template <unsigned idx>
    static constexpr __SIZE_TYPE__ get_index() { return idx; }

    template <unsigned s>
    static auto x() -> opts...[get_index<s>()] {}
};
```

Attempting to call `x` like this
```c++
temp<void>::x<0>();
```
fails with the following (rather weird) error:
```
<source>:11:5: error: no matching function for call to 'x'
   11 |     temp<void>::x<0>(); // Error
      |     ^~~~~~~~~~~~~~~~
<source>:7:17: note: candidate template ignored: substitution failure [with s = 0]: array size is not a constant expression
    7 |     static auto x() -> opts...[get_index<s>()] {}
      |                 ^              ~~~~~~~~~
```

**Comment by Sirraide** [comment]
Apologies for this rather messy issue. I’m not sure whether these are two different bugs or not, but I haven’t managed to reduce this any further...

**Comment by zyn0217** [comment]
We need to push a constant evaluation context before recursing into transforming the IndexExpr:
https://github.com/llvm/llvm-project/blob/0916ae49b89db6eb9eee9f6fee4f1a65fd9cdb74/clang/lib/Sema/TreeTransform.h#L6667-L6672

This way, we could instantiate the function body of `get_index()` when building up a DeclRefExpr for the transformed CallExpr, which is necessary for the constant evaluation.

https://github.com/llvm/llvm-project/blob/0916ae49b89db6eb9eee9f6fee4f1a65fd9cdb74/clang/lib/Sema/SemaExpr.cpp#L17923-L17926

(In this case, the constant evaluator encounters an error that the constexpr function body is undefined, but unfortunately that error was dropped on the floor during the template parameter deduction)
