### ISSUE TITLE
Assertion `Proto && "Functions without a prototype cannot be overloaded"' failed

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#105962]
I think this is not a new one, but I noticed it today. 
C code is

```c
extern int test2();
#pragma weak test2 = test1
int test1() {        
	return test2(); 
}
```

clang says:

clang: /home/dcb40b/llvm/trunk/clang/lib/Sema/SemaOverload.cpp:6853: void clang::Sema::AddOverloadCandidate(clang::FunctionDecl*, clang::DeclAccessPair, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool, bool, bool, ADLCallKind, clang::ConversionSequenceList, clang::OverloadCandidateParamOrder, bool): Assertion `Proto && "Functions without a prototype cannot be overloaded"' failed.

Recent gcc seems happy with the code:

cvise $ ~/gcc/results/bin/gcc -c -g -O2 -Wall bug1047.c
cvise $ ~/gcc/results/bin/gcc -v
Using built-in specs.
COLLECT_GCC=/home/dcb40b/gcc/results/bin/gcc
COLLECT_LTO_WRAPPER=/home/dcb40b/gcc/results.20240823.asan.ubsan/libexec/gcc/x86_64-pc-linux-gnu/15.0.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../trunk/configure --prefix=/home/dcb40b/gcc/results.20240823.asan.ubsan --disable-multilib --disable-bootstrap --with-build-config=bootstrap-asan --with-build-config=bootstrap-ubsan --with-pkgversion=cb51e0b236c7d492 --enable-checking=df,extra,fold,rtl,yes --disable-doc --enable-languages=c,c++,fortran
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 15.0.0 20240823 (experimental) (cb51e0b236c7d492)

**Comment by shafik** [comment]
Duplicate: https://github.com/llvm/llvm-project/issues/35478
