### ISSUE TITLE
opt -passes="function-simplification<O1>" leaves debug info that the LLParser complains about

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#106042]
llvm commit: 7e6b1504c7cf
Reproduce with:
```
opt -passes="function-simplification<O1>" bbi-98372.ll -S -o - | opt -o /dev/null
```
Result:
```
opt: <stdin>:8:20: error: base element of getelementptr must be sized
    #dbg_value(ptr getelementptr inbounds ([1 x %union.anon], ptr @d, i32 0, i32 3), !7, !DIExpression(), !14)
```
The problem is that the output from function-simplification contains
```
#dbg_value(ptr getelementptr inbounds ([1 x %union.anon], ptr @d, i32 0, i32 3), !7, !DIExpression(), !14)
```
but there is no definition left of the type %union.anon. That type exists in the bbi-98372.ll input but I suppose it was removed in the output since there is no non-debug info use left. But this then makes other users of the output (e.g. opt or llc) error out.

[bbi-98372.ll.gz](https://github.com/user-attachments/files/16744959/bbi-98372.ll.gz)

**Comment by nikic** [comment]
This means that the new DbgRecords aren't handled in TypeFinder.

**Comment by jmorse** [comment]
Thanks for the find, we'll get on that ASAP

**Comment by jmorse** [comment]
Fix up for review in #106547

**Comment by jmorse** [comment]
I figure this is worth going into the release branch as it's a simple change but the error can break a workflow if someone runs into it.

**Comment by jmorse** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/25f87f2d703178bb4bc13a62cb3df001b186cba2
