### ISSUE TITLE
[HLSL] Add StructuredBuffer definitions to HLSLExternalSemaSource

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#106189]
Create the `StructuredBuffer` template in HLSLExternalSemaSource, which each contain a handle that will be lowered to a `dx.RawBuffer` target extension type with a struct as their type argument.

**Comment by damyanp** [comment]
Blocked on llvm/wg-hlsl#68.

**Comment by hekota** [comment]
Fixed by llvm/llvm-project#106316
