### ISSUE TITLE
False positive with class scope "static const" used with an object

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#10610]
|  |  |
| --- | --- |
| Bugzilla Link | [10238](https://llvm.org/bz10238) |
| Version | 2.9 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Hi, 

this little code gives me an "operand is a garbage value" warning:

struct Array {
	static const int size = 4;
};

bool fn(Array &a) {
	int s = a.size;
	return s>0;
}

If I remove the "int s = a.size" line, and change the end to "return a.size>0", I don't get a warning.

Or, If I change a.size to Array::size, I don't get a warning either.

**Comment by JOE1994** [comment]
No false positive warning as of `clang 19.1.0`:

https://godbolt.org/z/1GsjT6YPq
