### ISSUE TITLE
`lld-x86_64-win` / `llvm-clang-x86_64-expensive-checks-win` builds fail in CI

### ISSUE THREAD

**Issue by firewave** [llvm/llvm-project#106290]
https://lab.llvm.org/buildbot/#/builders/146/builds/970
https://lab.llvm.org/buildbot/#/builders/36/builds/1165

The builds fail because the worker `as-worker-93` is out of disk space:

```
fatal: Unable to create temporary file 'C:/a/lld-x86_64-win/llvm-project/.git/objects/pack/tmp_pack_XXXXXX': No space left on device
fatal: index-pack failed
```

CC'ing @gkistanova as the listed admin of the worker.

**Comment by gkistanova** [comment]
This issue has been resolved.
