### ISSUE TITLE
[LLDB] Hangs when connecting to lldb-server via script file on Windows

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#106282]
On Windows, LLDB hangs when using a script file, and that script file instructs LLDB to connect to a lldb-server process.

To reproduce:

In one terminal:
```
> lldb-server.exe g localhost:9090
```

In a second terminal:
```
> lldb.exe -b -s script.txt
```
where `script.txt` contains the following:
```
process connect --plugin gdb-remote connect://localhost:9090
attach error
```
The second line, `attach error`, is just to make it clear whether execution continued to the second statement, or hung on the first one.

If these two commands are executed in an interactive `lldb.exe` invocation, they work just as expected. But when executed via a script file, LLDB hangs on the first command and doesn't end up executing the second one.

This was reported downstream in https://github.com/mstorsjo/llvm-mingw/issues/401, but the same issue can be reproduced with LLDB built with MSVC as well.

**Comment by DavidSpickett** [comment]
Sounds a lot like https://github.com/llvm/llvm-project/issues/79430, have you tried this on Linux as well?

**Comment by mstorsjo** [comment]
> Sounds a lot like #79430, have you tried this on Linux as well?

I haven't, but that does indeed seem like the exact same thing. Let's close this then!
