### ISSUE TITLE
[lldb] build wformat for windows

### ISSUE THREAD

**Issue by trcrsired** [llvm/llvm-project#106217]
[2381/6957] Building CXX object tools/ll...Files/lldbHost.dir/common/Socket.cpp.obj
/home/cqwrteur/toolchains_build/llvm-project/lldb/source/Host/common/Socket.cpp:112:19: warning: format specifies type 'int' but the argument has type 'size_t' (aka 'unsigned long long') [-Wformat]
  111 |     return Status("WriteWithTimeout(WSAPROTOCOL_INFO) failed: %d bytes",
      |                                                               ~~
      |                                                               %zu
  112 |                   num_bytes);
      |                   ^~~~~~~~~
/home/cqwrteur/toolchains_build/llvm-project/lldb/source/Host/common/Socket.cpp:133:11: warning: format specifies type 'int' but the argument has type 'size_t' (aka 'unsigned long long') [-Wformat]
  132 |           "socket_pipe.ReadWithTimeout(WSAPROTOCOL_INFO) failed: % d bytes",
      |                                                                  ~~~
      |                                                                  % zu
  133 |           num_bytes);
      |           ^~~~~~~~~

**Comment by DavidSpickett** [comment]
This got fixed by de687eac24a3f4bac8b5ff9975f51ab98775f2d5. Thanks for taking the time to report.
