### ISSUE TITLE
Fake ambiguity between scoped redeclaration of class found via inline anonymous namespace

### ISSUE THREAD

**Issue by rjmccall** [llvm/llvm-project#10631]
|  |  |
| --- | --- |
| Bugzilla Link | [10259](https://llvm.org/bz10259) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
```cpp
// scoped declaration fails (correctly: [namespace.qual]p7) if namespace isn't inline
// works if namespace isn't anonymous
inline namespace {
  class A;
}

// if not scoped, ambiguity is real, no bug
class ::A {};
A a;
```

daysthatwere:trunk glamr$ clang -std=c++0x /tmp/red3.cpp 
/tmp/red3.cpp:5:1: error: reference to 'A' is ambiguous
A a;
^
/tmp/red3.cpp:4:9: note: candidate found by name lookup is 'A'
class ::A {};
        ^
/tmp/red3.cpp:2:9: note: candidate found by name lookup is '<anonymous namespace>::A'
  class A;
        ^
/tmp/red3.cpp:5:3: error: variable has incomplete type '<anonymous>::A'
A a;
  ^
/tmp/red3.cpp:2:9: note: forward declaration of '<anonymous>::A'
  class A;
        ^
2 errors generated.

**Comment by shafik** [comment]
This looks fixed: https://godbolt.org/z/o9veYxdzz if so please close.

**Comment by zwuis** [comment]
Doesn't reproduce since Clang 3.5.
Godbolt: <https://godbolt.org/z/KfP7rhvoj>
