### ISSUE TITLE
[clang-format] Incorrect formatting of MSVC interface keyword after clang-format v17.0.1

### ISSUE THREAD

**Issue by arthuraraujo-msft** [llvm/llvm-project#106386]
.clang-format:
```
Language: Cpp
PointerAlignment: Left
```
`
Formatting with v16.0.6:
```
interface MyInterface {
  virtual HRESULT Func(_In_ MyType* var) = 0;
};
```

Formatting with v17.0.1 (and with latest v18.1.8):
```
interface MyInterface { virtual HRESULT Func(_In_ MyType * var) = 0; };
```

Seems v17.0.1 stopped treating the MSVC keyword "interface" like the C++ keyword "class" as it used to. I haven't found a setting to specify which words should be treated as keywords either.
Switching "interface" to "class" returns the formatting to the expected format:

Formatting with v18.1.8:
```
class MyInterface {
  virtual HRESULT Func(_In_ MyType* var) = 0;
};
```

**Comment by owenca** [comment]
Bisected to 9db2a0454815979bc8e0f65e830ab9051b4ff5d2. You can add `Macros: [interface=class]` to your config since version 17.

**Comment by arthuraraujo-msft** [comment]
Thanks, @owenca!
