### ISSUE TITLE
Ineffectual bitwise or with constant emitted for mask operand of vperm(b|w|d|q|ps|pd)

### ISSUE THREAD

**Issue by cvijdea-bd** [llvm/llvm-project#106413]
Same thing as https://github.com/llvm/llvm-project/issues/106256, but also happens for the (avx2/avs512) permute[x]var intrinsics, while the PR https://github.com/llvm/llvm-project/pull/106377 seems to only fix it for (v)pshufb specifically.

Godbolt examples: https://godbolt.org/z/MsTcx7qYc

The vector permute intrinsics ignore all bits except the ones that match the required index size, e.g.:
- vpermb only uses 4, 5, 6 bits out of each mask byte element for 128, 256, 512 bit sized vectors respectively
- vpermw only uses 3, 4, 5 bits out of each 16-bit element in the mask
- etc.

The OR operations with unrelated bits should be optimzied out.

Probably applies to vpermt2 (e.g. _mm512_permutex2var_epi16) also, with 1 more bit used since they selected from two concatenated vectors.

cc @RKSimon

**Comment by RKSimon** [comment]
vpermilpd/vpermilps will need support as well  - vpermilpd is annoying as it doesn't use the lsb for the index

**Comment by RKSimon** [comment]
> Godbolt examples: https://godbolt.org/z/MsTcx7qYc

@cvijdea-bd Just so you know, the _mm_permutexvar_* intrinsics have the mask at arg0, while _mm256_permutevar intrinscis have it at arg1, and _mm_permutex2_ intrinsics have it in the middle. Just another thing to love about x86...........

**Comment by cvijdea-bd** [comment]
Yeah I noticed that while looking over your fix, great stuff...
