### ISSUE TITLE
[clang-format] [regression] formatting of macro not stable; oscillates between two ways

### ISSUE THREAD

**Issue by joelhock** [llvm/llvm-project#106418]
formatting of the `MEMBER` macro oscillates between the two ways shown below each time it is reformatted with 19.1.0-rc3 and also main as of 114ff99e93edd.  version 18 consistently chose the first one, fwiw.

empty  `.clang-format`

```cpp
struct MyStruct : Base {
  int foo;

#define MEMBER(NAME)                                                           \
  NAME { "" }
  MEMBER(bar);
};

struct MyStruct : Base {
  int foo;

#define MEMBER(NAME) NAME{""}
  MEMBER(bar);
};
```

**Comment by owenca** [comment]
> version 18 consistently chose the first one, fwiw.

Which version of 18?

**Comment by joelhock** [comment]
ah, sorry, what I said wasn't correct.  version 17.0.1 (e19b7dc36bc047) stably formatted this code, but version 18 and 19 do not.

**Comment by owenca** [comment]
Bisected it to 063e3fe648533004e6970ab767ece845e3c0afb1.

> version 18 consistently chose the first one, fwiw.

> version 17.0.1 (https://github.com/llvm/llvm-project/commit/e19b7dc36bc047b9eb72078d034596be766da350) stably formatted this code, but version 18 and 19 do not.

Actually, version 17.0.1 consistently chose the _second_ one.

**Comment by owenca** [comment]
0fa78b6c7bd43c2498700a98c47a02cf4fd06388 has been reverted by 3449ed8dece600f387357b71ff74ae4bc46828b6.
