### ISSUE TITLE
poor location for type mismatch diagnostic

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#10640]
|  |  |
| --- | --- |
| Bugzilla Link | [10268](https://llvm.org/bz10268) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor |

## Extended Description 
I got this today:

LinkModules.cpp:419:11: error: no matching function for call to
      'LinkAppendingVars'
      if (LinkAppendingVars(DGV, SGV, ValueMap, Error)) return true;
          ^~~~~~~~~~~~~~~~~
LinkModules.cpp:278:13: note: candidate function not viable: cannot convert
      from base class pointer 'llvm::GlobalValue *' to derived class pointer
      'llvm::GlobalVariable *' for 1st argument
static bool LinkAppendingVars(GlobalVariable *DstGV, GlobalVariable *SrcGV,
            ^

Why is it pointing to and underlining "LinkAppendingVars"?  It should point to the function and underline the "1st argument".  Likewise, the note should point to the first argument (DstGV) as well.

-Chris

**Comment by philnik777** [comment]
Closing, since there is no reproducer.
