### ISSUE TITLE
[InstCombine] Transform sub(select, select) into select when they have same conditions

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#106511]
* test: https://alive2.llvm.org/ce/z/An8eOd
```
define i32 @sub_select_select_src(i32 %a) {
  %cmp = icmp eq i32 %a, 0
  %lhs = select i1 %cmp, i32 1, i32 %a
  %rhs = select i1 %cmp, i32 9, i32 %a
  %res = sub nsw i32 %lhs, %rhs
  ret i32 %res
}
```

* we expect have the result after instCombine transform 
```
define i32 @sub_select_select_tgt(i32 %a) {
  %cmp = icmp eq i32 %a, 0
  %res = select i1 %cmp, i32 -8, i32 0
  ret i32 %res
}
```

**Comment by vfdff** [comment]
It seems a regression of llvm, https://gcc.godbolt.org/z/Wdq8s9saf
  > works fine with llvm 16.0

**Comment by pedroclobo** [comment]
Hi, I would like to work on this.

**Comment by nikic** [comment]
Can you please share which real-world code this affects?

**Comment by vfdff** [comment]
It come from the hot function **digits_2** of spec2017, 548.exchange2, related code snippet
```
  recursive subroutine digits_2(row)
  integer, intent(in) :: row
  integer :: i1, i2, i3, i4, i5, i6, i7, i8, i9, l(r), u(r), rnext, col
  logical :: OK
     
     !  call i32 @llvm.umax.i32(i32 %tmp, i32 1)
     where(sudoku1(row, :) /= 0)
        l = sudoku1(row, :)
         u = l
     elsewhere
         l = 1
        u = r
     end where

     rnext = ((row-1)/3+1)*3+1

  do i1 = l(1), u(1)
     if(block(row, 1, i1) <= 0) cycle
      ...
```

**Comment by nikic** [comment]
I believe that https://github.com/llvm/llvm-project/pull/65978 is an existing PR trying to address this issue (cc @davemgreen).

**Comment by vfdff** [comment]
Thank you very much. This does seem to be a duplicate question.

**Comment by vfdff** [comment]
This will be fixed with https://github.com/llvm/llvm-project/pull/107314
