### ISSUE TITLE
[clang] -Wpadded does not trigger any warnings, despite using same code as unit tests

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#106684]
Hi,

I copy-pasted [this unit test](https://github.com/llvm/llvm-project/blob/ce7c828e085563f29451ec5fac9626c76ebf70ee/clang/test/CodeGenCXX/warn-all-padded-packed-packed-non-pod.cpp#L9) into a standalone .cpp file, and enabled `-Weverything`. To my surprise, no warnings are generated. Why is that?

https://godbolt.org/z/sfPWqMv45

**Comment by carlosgalvezp** [comment]
Interestingly enough, if I add clang-tidy, then the warnings come out as `clang-diagnostic-error`. But they should come out of clang alone as well!
https://godbolt.org/z/63TMaMafn

**Comment by philnik777** [comment]
`-Wpadded` is checked when the layout of the struct is generated, so you have to use it: https://godbolt.org/z/3KsEhGKq8

**Comment by carlosgalvezp** [comment]
Ah great, thank you for the quick response!
