### ISSUE TITLE
[RISCV][SiFive] How to prevent reordering of VCIX instructions when using intrinsics and inline-asm?

### ISSUE THREAD

**Issue by michalt** [llvm/llvm-project#106700]
We've run into an interesting problem when writing some high-performance kernels that use the VCIX instructions.

In a few places we wanted to use both intrinsics and a small amount of inline assembly (it's performance critical and writing it manually was a noticeable win). This turns out to be tricky because the compiler reorders the intrinsics and the inline-asm block. VCIX instructions should not be reordered across each other, and this is accomplished through `VCIX_STATE` ([code](https://github.com/llvm/llvm-project/blob/1b32c3e2985f89900030289eaa44e3d92cab85af/llvm/lib/Target/RISCV/RISCVRegisterInfo.cpp#L147-L148), #77049). This works fine when using intrinsics, however, we couldn't find a way to indicate that `VCIX_STATE` gets clobbered by inline-asm.

Is this something that's possible and we just missed it? If not, what would be the best approach here?

@4vtomat @topperc @michaelmaitland Any suggestions would be very welcome! 🙂 

Simplified repro: https://godbolt.org/z/KcT3asrKa

![image](https://github.com/user-attachments/assets/c474a902-bc97-4a8b-a9bb-7e6e8b6020b5)

**Comment by topperc** [comment]
I think we need to add "vcix_state" to the list of registers in `RISCVTargetInfo::getGCCRegNames()` in clang

**Comment by 4vtomat** [comment]
Hi @michalt, thanks for filing this ticket, let me take this~

**Comment by michalt** [comment]
> Hi @michalt, thanks for filing this ticket, let me take this~

Awesome, thank you! 😀
