### ISSUE TITLE
Backport "[AVR] Fix parsing & emitting relative jumps"

### ISSUE THREAD

**Issue by aykevl** [llvm/llvm-project#106728]
/cherry-pick 86a60e7f1e8f361f84ccb6e656e848dd4fbaa713

This fix is critical to get the AVR backend working again. Without this fix, it's practically unusable because almost all branches have an off-by-one error (one word, 2 bytes). For more context, see https://github.com/llvm/llvm-project/issues/102436 and https://github.com/llvm/llvm-project/pull/102936.

CC @Patryk27

**Comment by Patryk27** [comment]
Should I prepare the backport myself or there's some magic llvm bot that'll do it? 😄

**Comment by aykevl** [comment]
Well there you see it, there's a magic LLVM bot for it :)
