### ISSUE TITLE
`__noop` should return 0

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#106713]
The new constexpr implementation is wrong.

https://github.com/llvm/llvm-project/blob/main/clang/test/CodeGen/builtin-ms-noop.cpp shows that `__noop` should return `0` and not nothing.

**Comment by tbaederr** [comment]
CC @ofAlpaca

**Comment by AaronBallman** [comment]
https://learn.microsoft.com/en-us/cpp/intrinsics/noop?view=msvc-170

> The compiler converts the __noop intrinsic to 0 at compile time.

**Comment by tbaederr** [comment]
> The argument list is parsed, but no code is generated for the arguments. 

Also: https://godbolt.org/z/51boqnKah
