### ISSUE TITLE
Update debug info assignment tracking docs with current status

### ISSUE THREAD

**Issue by jryans** [llvm/llvm-project#106873]
I noticed that the [assignment tracking docs](https://llvm.org/docs/AssignmentTracking.html) still say...

> Experimental work in progress. Enabling is strongly advised against except for development and testing.

...even though it's been enabled by default since https://github.com/llvm/llvm-project/commit/de6da6ad55d3ca945195d1cb109cb8efdf40a52a (2023-06 / LLVM 17).

@OCHyams, it would be great to update this with the correct current status, and also update the TODO list at the bottom where appropriate.

**Comment by OCHyams** [comment]
Good find, thanks; PR up here #106959.
