### ISSUE TITLE
`reverse-iteration` tests fail in the CI

### ISSUE THREAD

**Issue by firewave** [llvm/llvm-project#106855]
Although #106355 was fixed the tests still fail.

https://lab.llvm.org/buildbot/#/builders/110/builds/999

```
FAIL: LLVM::load.ll
FAIL: LLVM::full-cycle.ll
```

It turns out the other failures were masking previously introduced failures. They apparently started in https://lab.llvm.org/buildbot/#/builders/110/builds/728.

**Comment by mtrofin** [comment]
Sorry - just saw this now, my notifications must have a problem. I'll fix it in a bit.

**Comment by firewave** [comment]
Green now: https://lab.llvm.org/buildbot/#/builders/110/builds/1114.

Thanks!
