### ISSUE TITLE
LLVM allows usage of add instead of addi inside an inline assembly

### ISSUE THREAD

**Issue by mekosko** [llvm/llvm-project#106893]
When add is used with immediate values llvm just replaces add with addi without any errors and warnings.

https://godbolt.org/z/c145YddxK

**Comment by topperc** [comment]
This is intentional. binutils does the same thing. It's intended to support inline assembly with an "ri" contraint that allows either integer or register.

**Comment by jrtc27** [comment]
> This is intentional. binutils does the same thing. It's intended to support inline assembly with an "ri" contraint that allows either integer or register.

Indeed. Though worth noting that `%i` lets you conditionally append an "i" to the instruction based on the operand, so it's not required, just a lazy way to do it.

**Comment by arichardson** [comment]
Intended behaviour, closing this issue.
