### ISSUE TITLE
[Clang][X86_64] Clang build inl instruction in __asm__ error

### ISSUE THREAD

**Issue by Zhenhang1213** [llvm/llvm-project#106863]
error: invalid operand for instruction (inl) in X86_64, is clang-bug ? And gcc is ok. I haven't found any relevant materials

https://godbolt.org/z/7EMrG6968

**Comment by antoniofrighetto** [comment]
I think clang behaviour is correct. [From the manual](https://www.felixcloutier.com/x86/in), the I/O port addresses are either accessible via a byte-immediate or via dx register. This works correctly: https://godbolt.org/z/T4MG3G7o7.
