### ISSUE TITLE
"Class Template Argument Deduction for Alias Templates" Still not supported

### ISSUE THREAD

**Issue by MohammedAhmed381** [llvm/llvm-project#106839]
in this code
`
int main()
{
  std::array lTest = {1,2};
  return 0;
};
`
and it compiles fine
`1>------ Build started: Project: Test1, Configuration: Debug x64 ------
1>FileName.cpp(11,14): warning : unused variable 'lTest' [-Wunused-variable]
1>Test1.vcxproj -> C:\Users\moham\source\repos\Test1\x64\Debug\Test1.exe
1>Done building project "Test1.vcxproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 12:15 PM and took 07.160 seconds ==========`
Now when using templates alias
`
#include "AIOBCpp/CppLibs.h"

template<typename TContent, uint64_t tSize>
using Arr = std::array<TContent, tSize>;

int main()
{
  Arr lTest = {1,2};
  return 0;
};
`

this is the compiled output
`
1>------ Build started: Project: Test1, Configuration: Debug x64 ------
1>FileName.cpp(11,7): error : alias template 'Arr' requires template arguments; argument deduction only allowed for class templates
1>FileName.cpp(7,1): message : template is declared here
1>Done building project "Test1.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 12:17 PM and took 06.955 seconds ==========
`
And I tested the LLVM Version
`
#include "AIOBCpp/CppLibs.h"

int main()
{
  std::cout << __clang_version__;
  return 0;
};
`
and it was 18.1.8

**Comment by zyn0217** [comment]
The CTAD for alias templates patch was merged after the cut of 18 branch, so you should try 19 (not yet released) or trunk for it.
