### ISSUE TITLE
matrix types are underaligned

### ISSUE THREAD

**Issue by StreetwareGames** [llvm/llvm-project#106923]
I could be totally wrong here, but I don't think a 4x4 float matrix should have an alignment of 4 while the vector of 4 floats has an alignment of 16. I'd expect it to be 16 for both.

https://godbolt.org/z/xn1147raa

**Comment by fhahn** [comment]
The current draft specification leaves this decision implementation defined (https://clang.llvm.org/docs/MatrixTypes.html).

The current choice was motivated by making the type convenient to integrate into existing code that stores matrixes in plain arrays in C/C++.

**Comment by StreetwareGames** [comment]
alright. I'll just add `__attribute__((aligned(16)));` to work around this.
