### ISSUE TITLE
Incomplete support for -fplan9-extensions

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#10695]
|  |  |
| --- | --- |
| Bugzilla Link | [10323](https://llvm.org/bz10323) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
There are currently two issues with Clang's implementation of the Plan9 extensions:

- It must imply -fms-extensions so that a structure declared in a different scope can be used like an unnamed structure.
- When passing the pointer of a structure to another function, Clang doesn't select the correct member.

See also http://gcc.gnu.org/onlinedocs/gcc/Unnamed-Fields.html

#include <stdio.h>

struct s1 {
        int b;
};

struct s2 {
        int a;
        struct s1;
};

void f0(void *p) {
        printf("a=%p\n", p);
}

void f1(struct s1 *p) {
        printf("b=%p\n", &p->b);
}

void f2(struct s2 *p) {
        printf("a=%p b=%p\n", &p->a, &p->b);
        f0(p);
        f1(p);
}

int main(void) {
        struct s2 s;
        f2(&s);
        return 0;
}

**Comment by AaronBallman** [comment]
Clang does not support `-fplan9-extensions` as a feature flag, and I don't know that we intend to do so in the future. However, we will support any Plan 9 extensions that are needed for use with system headers or other important third-party libraries on a case by case basis. Closing as not planned.
