### ISSUE TITLE
Backport "[AVR] Fix 16-bit LDDs with immediate overflows (#104923)"

### ISSUE THREAD

**Issue by tronje** [llvm/llvm-project#106946]
/cherry-pick c7a4efa4294789b1116f0c4a320c16fcb27cb62c

I initially spotted and reported the bug here: https://github.com/Rahix/avr-hal/issues/573
Thanks to @Patryk27 there's a fix that has even been merged already, but I really need this to make its way into a Rust toolchain :slightly_smiling_face: 
So I did some digging and basically copied #106728 and am hereby requesting a backport of this into the release branch. Hope I'm doing this right! Thanks!

Edit: looks like I'm unable to set the correct milestone, any help? :pray:

**Comment by Patryk27** [comment]
fwiw, it needs to be cherry-picked into https://github.com/rust-lang/llvm-project (https://rustc-dev-guide.rust-lang.org/backend/updating-llvm.html) to actually land in rustc.

I was planning on doing that later, since we've gotta bundle that commit together with https://github.com/llvm/llvm-project/pull/106729 to actually get the codegen working.

**Comment by tronje** [comment]
> fwiw, it needs to be cherry-picked into https://github.com/rust-lang/llvm-project (https://rustc-dev-guide.rust-lang.org/backend/updating-llvm.html) to actually land in rustc.

Yeah I know, but the [dev guide](https://github.com/rust-lang/rustc-dev-guide/pull/2039/files) says to request a backport upstream first, so I figured I'd do that.

> I was planning on doing that later, since we've gotta bundle that commit together with #106729 to actually get the codegen working.

Ah okay; is there anything at all that I can do? :slightly_smiling_face:

**Comment by Patryk27** [comment]
Not sure, probably @aykevl can help us the most here - could you backport https://github.com/llvm/llvm-project/pull/104923? 😄

**Comment by aykevl** [comment]
Added the milestone, let's see whether it helps.
