### ISSUE TITLE
SLPVectorizer does not respect isFPVectorizationPotentiallyUnsafe()

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#106909]
SLPVectorizer currently incorrectly vectorizes FP instructions using ARM NEON (https://llvm.godbolt.org/z/c9866Yv13), which has non-IEEE compliant denormal flushing (https://github.com/llvm/llvm-project/issues/16648).

There is a isFPVectorizationPotentiallyUnsafe() TTI hook for this, which is checked by LoopVectorize, but not SLPVectorizer.

(Technically at fault here is the ARM backend for using NEON instructions for vector floating point ops, but LLVM currently handles this by preventing their implicit formation.)

**Comment by alexey-bataev** [comment]
I cannot find where LoopVectorizer uses isFPVectorizationPotentiallyUnsafe. Could you point exact line of code? Searching through the LLVM code base provides only declarations of the function, but I cannot find a single reference

**Comment by nikic** [comment]
Sure, the call is here: https://github.com/llvm/llvm-project/blob/84ed3c29e8583bdd704d0e2f7e7c3d1162c6181c/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp#L9878

See also the related code in https://github.com/llvm/llvm-project/blob/84ed3c29e8583bdd704d0e2f7e7c3d1162c6181c/llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp#L1001-L1004
