### ISSUE TITLE
[HLSL] inout/out ABI for array parameters

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#106917]
Basic `inout` and `out` parameter support is landed, however it doesn't currently work with `ArrayParameterType` arguments.

The following code should compile successfully:
```hlsl
void increment(inout int Arr[10]) {
  for (int I = 0; I < 10; I++)
    Arr[0] += 2;
}

export int call() {
  int A[10] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
  increment(A);
  return A[0];
}
```

**Comment by llvm-beanz** [comment]
Context: Array parameters are treated as a non-decaying array types. The current `[in]out` support incorrectly translates the parameter's base type to a restrict reference, which results in arrays being treated as arrays of references, instead of a reference to a non-decaying array.

We need to fix that and ensure that the code generation correctly handles the temporary values.

**Comment by spall** [comment]
looking at this

**Comment by damyanp** [comment]
Blocked on #109043.
