### ISSUE TITLE
IR expand: FMINIMUM/FMAXIMUM: Payload is missing if both are NaN

### ISSUE THREAD

**Issue by wzssyqa** [llvm/llvm-project#106942]
In llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp

```
  // Propagate any NaN of both operands
  if (!N->getFlags().hasNoNaNs() &&
      (!DAG.isKnownNeverNaN(RHS) || !DAG.isKnownNeverNaN(LHS))) {
    ConstantFP *FPNaN = ConstantFP::get(*DAG.getContext(),
                                        APFloat::getNaN(VT.getFltSemantics()));
    MinMax = DAG.getSelect(DL, VT, DAG.getSetCC(DL, CCVT, LHS, RHS, ISD::SETUO),
                           DAG.getConstantFP(*FPNaN, DL, VT), MinMax, Flags);
  }
```

**Comment by dtcxzyw** [comment]
I think it is ok to not use payloads from its inputs. See the “Preferred NaN” case in  https://llvm.org/docs/LangRef.html#behavior-of-floating-point-nan-values.

**Comment by dtcxzyw** [comment]
cc @arsenm @jcranmer-intel

**Comment by arsenm** [comment]
Preserving a payload is a nice to have, not required. It's not worth spending extra instructions to preserve one

**Comment by wzssyqa** [comment]
There is this sentence in IEEE754-2019  6.2.3

```
If two or more inputs are NaN, then the payload of the resulting NaN should be identical to the payload of
one of the input NaNs if representable in the destination format. This standard does not specify which of
the input NaNs will provide the payload.
```

**Comment by arsenm** [comment]
> should be identical

I thought in standardese "should" implies good idea but not mandatory, and "shall" implies mandatory

**Comment by arsenm** [comment]
> > should be identical
> 
> I thought in standardese "should" implies good idea but not mandatory, and "shall" implies mandatory

See 1.6, "one is recommended as particularly suitable, without mentioning or excluding others"

**Comment by wzssyqa** [comment]
Thanks.  So this report is invalid.
