### ISSUE TITLE
Use 'leave' instruction in epilogue to rewind frame

### ISSUE THREAD

**Issue by jrmuizel** [llvm/llvm-project#10691]
|  |  |
| --- | --- |
| Bugzilla Link | [10319](https://llvm.org/bz10319) |
| Version | trunk |
| OS | All |
| Blocks | llvm/llvm-bugzilla-archive#32858  |
| CC | @ammarfaizi2,@asl,@lattner,@filcab,@RKSimon,@stoklund |

## Extended Description 
llvm currently uses a sequence like:
000000000000003b	addq	$0x10,%rsp
000000000000003f	popq	%rbp
0000000000000040	ret

instead of the shorter:
000000000000003b	leave
000000000000003c	ret

that gcc usees.

**Comment by jyknight** [comment]
Dup of #32205.
