### ISSUE TITLE
Backport 7c4cffd9d8be424e9e9542be9aec3b5a6f69073e

### ISSUE THREAD

**Issue by devnexen** [llvm/llvm-project#106903]
I'd like to backport #106902 to the release/19.x branch.

/cherry-pick [7c4cffd](https://github.com/llvm/llvm-project/commit/7c4cffd9d8be424e9e9542be9aec3b5a6f69073e)

**Comment by EugeneZelenko** [comment]
/cherry-pick [7c4cffd](https://github.com/llvm/llvm-project/commit/7c4cffd9d8be424e9e9542be9aec3b5a6f69073e)

**Comment by nikic** [comment]
Closing in favor of PR https://github.com/llvm/llvm-project/pull/106908.
