### ISSUE TITLE
[clang][AVR] clang does not set `AVR_INTR` calling convention; should it?

### ISSUE THREAD

**Issue by alexrp** [llvm/llvm-project#106926]
I happened to notice that Clang does not set the `AVR_INTR` calling convention for interrupt functions on AVR:

https://github.com/llvm/llvm-project/blob/357bd61744bb8cc2b9b07447294fa977e5758550/clang/lib/CodeGen/Targets/AVR.cpp#L141-L145

Yet other targets do, e.g. MSP430:

https://github.com/llvm/llvm-project/blob/357bd61744bb8cc2b9b07447294fa977e5758550/clang/lib/CodeGen/Targets/MSP430.cpp#L82-L90

Is this intentional? Or should it be changed?

**Comment by benshi001** [comment]
Is it unnecessary to do that, since we do it in such way

https://github.com/llvm/llvm-project/blob/357bd61744bb8cc2b9b07447294fa977e5758550/llvm/lib/Target/AVR/AVRMachineFunctionInfo.h#L53

**Comment by alexrp** [comment]
Ah, ok, I see. Would it be worth doing it 'just in case'? (For example, if the backend is ever changed to check the call conv elsewhere.) If you think not, then I guess we can just close this. :slightly_smiling_face:

**Comment by aykevl** [comment]
There are tests that check this behavior: 
https://github.com/llvm/llvm-project/blob/main/llvm/test/CodeGen/AVR/interrupts.ll
So no, I don't think it's needed.
