### ISSUE TITLE
[SLP] Cannot getTypeInfo() on a type that is unsized!

### ISSUE THREAD

**Issue by DianQK** [llvm/llvm-project#107036]
I tried the following IR with SLP:

```llvm
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @foo(ptr %i) {
bb:
  %i1 = getelementptr i8, ptr %i, i64 4
  br label %bb2

bb2:                                              ; preds = %bb2, %bb
  %i3 = phi i32 [ %i6, %bb2 ], [ 0, %bb ]
  %i4 = phi i32 [ %i8, %bb2 ], [ 0, %bb ]
  store i32 %i3, ptr %i
  store i32 %i4, ptr %i1
  %i5 = trunc i32 0 to i1
  %i6 = select i1 %i5, i32 0, i32 0
  %i7 = trunc i32 %i4 to i1
  %i8 = select i1 %i7, i32 0, i32 0
  br label %bb2
}
```

It failed with an error output:`Ty->isSized() && "Cannot getTypeInfo() on a type that is unsized!"' failed`. It's getting the size returned by the `store i32 %i4, ptr %i1` instruction.​

https://llvm.godbolt.org/z/fMx9qMcfK

cc f6e01b9ece1e73f6eda6e1dbff3aa72e917f4007 @alexey-bataev

**Comment by dtcxzyw** [comment]
https://github.com/llvm/llvm-project/blob/2cbd1bc830861bc08f78fb6cc11747b82f66c4c6/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp#L16067

`U` is `store i32 %i4, ptr %i1`.

**Comment by DianQK** [comment]
Reverting f6e01b9ece1e73f6eda6e1dbff3aa72e917f4007 seems reasonable to me. What do you think? @alexey-bataev ^^

**Comment by alexey-bataev** [comment]
will fix it asap today

**Comment by DianQK** [comment]
/cherry-pick f381cd069965dabfeb277f30a4e532d7fd498f6e

Thanks for your quick fix!
