### ISSUE TITLE
[LLD][RISCV] Why LLD places global_pointer only by looking at sdata_begin

### ISSUE THREAD

**Issue by LukeZhuang** [llvm/llvm-project#107069]
In RISCV, lld places `global_pointer` by looking for sdata section, and place it at `sdata_begin + 0x800`, otherwise place it at `elfHeader + 0x800` (the following code is from lld/ELF/Writer.cpp in <4befe65c>):
```
    // RISC-V's gp can address +/- 2 KiB, set it to .sdata + 0x800. This symbol
    // should only be defined in an executable. If .sdata does not exist, its
    // value/section does not matter but it has to be relative, so set its
    // st_shndx arbitrarily to 1 (ctx.out.elfHeader).
    if (config->emachine == EM_RISCV) {
      if (!config->shared) {
        OutputSection *sec = findSection(".sdata");
        addOptionalRegular("__global_pointer$", sec ? sec : ctx.out.elfHeader,
                           0x800, STV_DEFAULT);
        // Set riscvGlobalPointer to be used by the optional global pointer
        // relaxation.
        if (config->relaxGP) {
          Symbol *s = symtab.find("__global_pointer$");
          if (s && s->isDefined())
            ctx.sym.riscvGlobalPointer = cast<Defined>(s);
        }
      }
    }
```
The issue is currently we have a program on our target machine that does not have .sdata section at all, thus I found it places global pointer at `0x10000 + 0x800`, which is pretty far away from the symbols we want to relax in .sbss section.

So I just wonder is there a reason that lld decides to place global pointer with this simple strategy? I saw GNU LD uses such way to calculate it in the default linker script:
```
__global_pointer$ = MIN(__SDATA_BEGIN__ + 0x800,
                        MAX(__DATA_BEGIN__ + 0x800, __BSS_END__ - 0x800));
```
Can LLD have the same behaviour as GNU LD in this case? Thanks!

**Comment by LukeZhuang** [comment]
Followup:
This is GNU LD does in ld/emulparams/elf32lriscv-defs.sh in binutils
```
# We must cover as much of sdata as possible if it exists.  If sdata+bss is
# smaller than 0x1000 then we should start from bss end to cover as much of
# the program as possible.  But we can't allow gp to cover any of rodata, as
# the address of variables in rodata may change during relaxation, so we start
# from data in that case.
OTHER_END_SYMBOLS="${CREATE_SHLIB-__BSS_END__ = .;
    __global_pointer$ = MIN(__SDATA_BEGIN__ + 0x800,
                            MAX(__DATA_BEGIN__ + 0x800, __BSS_END__ - 0x800));}"
```

**Comment by LukeZhuang** [comment]
ping

**Comment by topperc** [comment]
I think the only reason is that no  one has stepped up to do something better. lld is also missing GP relaxation for medany.

Recently small-data-limit was changed to default to 0 in clang.
