### ISSUE TITLE
Clang error when using a constexpr variable as NTTP default value in lambda expression.

### ISSUE THREAD

**Issue by ldalessa** [llvm/llvm-project#107048]
```c++
void foo()
{
    constexpr int x{};
    auto a = []<int=x>{};
}
```

Looks like a regression from 16 to 17, persists in 18 and current trunk. 

https://godbolt.org/z/TErqq79ao

**Comment by zyn0217** [comment]
Now only EDG accepts it. https://godbolt.org/z/h58Ko1rce

**Comment by zyn0217** [comment]
Probably, this has been turned into ill-formed according to [P2036R3](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2036r3.html#expr.prim.id.unqual):

> Otherwise (if P either precedes E’s function parameter scope or is in E’s parameter-declaration-clause), the program is ill-formed.

And clues from [P2579R0](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2579r0.pdf) could also prove this point:

> **Template Parameters**
> ```cpp
>   int x;
>   [x]<auto N = x> {}
> ```
> This is made ill-formed by P2036 and the proposed mitigation. [...]

But what confuses me is that we don't appear to diagnose such lambdas containing explicit captures; instead, we just give errors on lambda with no captures. (Which is OP's example)

@cor3ntin Could you confirm?

**Comment by ldalessa** [comment]
I want to mention that the real use case I have is in a decltype() for the lambda. I’m not sure if this changes any of the standardese associated with it. I can post a more sophisticated use when I get back to my computer.
