### ISSUE TITLE
Backport "[AVR] Fix parsing & emitting relative jumps" (try 2)

### ISSUE THREAD

**Issue by aykevl** [llvm/llvm-project#107081]
Let's try this again, now with both commits needed for a fix (that doesn't result in a test failure).

/cherry-pick 86a60e7f1e8f361f84ccb6e656e848dd4fbaa713
/cherry-pick a3816b5a573dbf57ba3082a919ca2de6b47257e9

**Comment by aykevl** [comment]
/cherry-pick 86a60e7f1e8f361f84ccb6e656e848dd4fbaa713 a3816b5a573dbf57ba3082a919ca2de6b47257e9

This was meant to include both commits. Maybe this syntax will work?

**Comment by aykevl** [comment]
Looks like this one does indeed work! The llvmbot has updated #107082 to include both commits.

**Comment by benshi001** [comment]
Though https://github.com/llvm/llvm-project/commit/86a60e7f1e8f361f84ccb6e656e848dd4fbaa713 has been merged, the fix is incorrect, since the llvm-objdump still has problem, as I have indicated at https://github.com/llvm/llvm-project/pull/102936#discussion_r1741322197
