### ISSUE TITLE
SLPVectorizer.cpp : Conditional Check for Idx Might Prevent TryToVectorize(Set.second) Execution in vectorizeStores()

### ISSUE THREAD

**Issue by Bruce0316** [llvm/llvm-project#107199]
In [llvm-project/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp](https://github.com/llvm/llvm-project/blob/llvmorg-19.1.0-rc3/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp), at line 16324, 
`auto It = Set.second.find(std::make_pair(Idx, *Diff));`
The comment explains that if *Diff is duplicated in the set, TryToVectorize(Set.second) should be executed.
However, the code also checks Idx. Does this mean that TryToVectorize(Set.second) might never be executed?

**Comment by alexey-bataev** [comment]
It will be attempted in the code after // Final vectorization attempt.
