### ISSUE TITLE
[clang][C++23] Redefinition in special cases

### ISSUE THREAD

**Issue by PolarLinda6** [llvm/llvm-project#107175]
```cpp
#include <print>

template<typename>
struct define_f {
  friend void f() {}
};

template<auto = [] {}>
struct A {};

struct B {
  template<typename T>
  consteval void func() {
    [[maybe_unused]] define_f<T> _{};
  }
} obj;

auto main() -> int {
  obj.func<decltype(A{})>();
  std::print(" ");
}
```

#### error message:

```txt
<source>:5:15: error: redefinition of 'f'
    5 |   friend void f() {}
      |               ^
<source>:14:34: note: in instantiation of template class 'define_f<A<(lambda at <source>:8:17){}>>' requested here
   14 |     [[maybe_unused]] define_f<T> _{};
      |                                  ^
<source>:19:7: note: in instantiation of function template specialization 'B::func<A<(lambda at <source>:8:17){}>>' requested here
   19 |   obj.func<decltype(A{})>();
      |       ^
<source>:5:15: note: previous definition is here
    5 |   friend void f() {}
      |         
```

#### Additional Information:

Version: clang version 18.1.8
compilation parameter: -std=c++23
Link: [godbolt](https://godbolt.org/z/MaW57hG8c)

PS: The code compiles successfully on gcc and msvc.

**Comment by zyn0217** [comment]
`std::print(" ")` is somehow necessary for the reproducer. Still don't know why.

**Comment by shafik** [comment]
Looks like the `consteval` and the lambda are required for this. It looks weird but I am sure the reduction will be enlightening. 

CC @cor3ntin

**Comment by frederick-vs-ja** [comment]
The `consteval` constructor of `std::format_string` (used in `std::print`) seems necessary to trigger the bug.

Reduced example ([Godbolt link](https://godbolt.org/z/1KWjbYjK4)):
```C++
struct my_basic_format_string {
  template<class T>
  consteval my_basic_format_string(const T&) {}
};

template<typename>
struct define_f {
  friend void AVeryLooooongName() {}
};

template<auto = [] {}>
struct A {};

struct B {
  template<typename T>
  consteval void func() {
    (void) define_f<T>{};
  }
};

auto main() -> int {
  B{}.func<decltype(A{})>();
#ifdef CONSTEVAL_CTOR
  (void) my_basic_format_string{""};
#endif
}
```

**Comment by PolarLinda6** [comment]
I encountered a special redefinition error again during the process of writing code. I extracted a demo.

Link: [godbolt](https://godbolt.org/z/xfM17vcMc)

PS: The code compiles successfully on gcc and msvc.

```cpp
template<typename>
void func();

template<typename>
struct define_func {
  template<typename>
  friend void func() {}
};

auto main() -> int {
  [[maybe_unused]] define_func<int> _{};
}
```

**Comment by zyn0217** [comment]
@PolarLinda6 I believe your case is unrelated to this bug because no constevals were involved. Can you file a new issue for that?

(In fact, the consteval case is a byproduct of the tree transform in `RemoveNestedImmediateInvocation`: `B::func()` was instantiated twice with different template arguments, and each of them instantiates the friend declaration individually.)

**Comment by PolarLinda6** [comment]
> @PolarLinda6 I believe your case is unrelated to this bug because no constevals were involved. Can you file a new issue for that?
> 
> (In fact, the consteval case is a byproduct of the tree transform in `RemoveNestedImmediateInvocation`: `B::func()` was instantiated twice with different template arguments, and each of them instantiates the friend declaration individually.)

Thanks for your answer. I have submitted a new question.
#107861
