### ISSUE TITLE
Clang permits implicit conversion to 'noreturn' function pointer in C

### ISSUE THREAD

**Issue by DougGregor** [llvm/llvm-project#10719]
|  |  |
| --- | --- |
| Bugzilla Link | [10347](https://llvm.org/bz10347) |
| Version | trunk |
| OS | All |

## Extended Description 
Clang accepts this code in C mode:

int add(int);

void f0(__attribute__((noreturn)) int (*)(int));
void f1() {
  f0(&add);
}

but it should not, since it is unsafe to treat a pointer to a possibly-returning function pointer as a function pointer that is known not to return. We properly diagnose this in C++ mode.

**Comment by philnik777** [comment]
This seems to be a duplicate of #7325. If you disagree, please reopen.
