### ISSUE TITLE
[cmake] CMake Error at /usr/lib/llvm-20/lib/cmake/llvm/LLVMExports.cmake:1920 (message): [cmake]   The imported target "LLVM" references the file [cmake]  [cmake]      "/usr/lib/llvm-20/lib/libLLVM.so.1" [cmake]  [cmake]   but this file does not exist. 

### ISSUE THREAD

**Issue by Zingam** [llvm/llvm-project#107116]
Since LLVM20 has been branched I have issues with installing LLVM20 with `llvm.sh`. I filed an initial issue here:

https://github.com/llvm/llvm-project/issues/99819 which I closed after I installed the missing packages manually.

Today after I apt upgraded I encountered the following error while configuring libc++:

> [cmake] CMake Error at /usr/lib/llvm-20/lib/cmake/llvm/LLVMExports.cmake:1920 (message):
[cmake]   The imported target "LLVM" references the file
[cmake] 
[cmake]      "/usr/lib/llvm-20/lib/libLLVM.so.1"
[cmake] 
[cmake]   but this file does not exist.

**Comment by dtcxzyw** [comment]
Ping.

**Comment by Zingam** [comment]
I'm closing this in connection with the linked one.
