### ISSUE TITLE
clang-format: `BasedOnStyle: Chromium` not respecting `InsertNewlineAtEOF: true`

### ISSUE THREAD

**Issue by thernstig** [llvm/llvm-project#107218]
```c
// main.c
#include <stdio.h>

/**
 * @brief Some info
 *
 * @param argc - The main `arg`
 * @param argv - The not main arg
 * @return int
 */
int main(int argc, char const* argv[]) {
  printf("Foo mains\n");
  return 0;
}
```

```yaml
# .clang-format
BasedOnStyle: Chromium
```

Note how `main.c` is missing a newline at the end of file. If i invoke the following it **does not** add a new line at the EOF (End Of File):

```sh
> clang-format -i src/main.c
```

If I change `.clang-format` to the following it **does** add a new line at EOF:

```yaml
BasedOnStyle: Chromium
InsertNewlineAtEOF: true
```

I cannot understand why, as Chromium has this set: https://chromium.googlesource.com/chromium/src/+/HEAD/.clang-format#13. Is this a bug?

**Version**
```sh
> clang-format --version
Ubuntu clang-format version 20.0.0 (++20240828064146+c43190f99445-1~exp1~20240828184310.1138)
```

**Comment by owenca** [comment]
> I cannot understand why, as Chromium has this set: https://chromium.googlesource.com/chromium/src/+/HEAD/.clang-format#13. Is this a bug?

Not a bug. The predefined styles follow the published style guides, not the .clang-format files they use. You can reopen this issue after getting https://chromium.googlesource.com/chromium/src/+/refs/heads/main/styleguide/styleguide.md updated.

**Comment by thernstig** [comment]
@owenca Is it not at least a documentation issue then? Neither https://clang.llvm.org/docs/ClangFormat.html nor https://clang.llvm.org/docs/ClangFormatStyleOptions.html mentions this. It is impossible for a user to know what is included in a predefined style then, unless of course one uses `--dump-config`. But that is not something everyone would think of.

I think at least this issue could be converted to a doc problem so that https://clang.llvm.org/docs/ClangFormat.html mentions this?

**Comment by owenca** [comment]
That wouldn't make any sense IMO because the onus is on the Chromium project to keep the Chromium style guide updated. See also [this comment](https://reviews.llvm.org/D147969#4256753) by @mydeveloperday.
