### ISSUE TITLE
[Aarch64] `st3` and `st4` should work on 2-byte and 4-byte vectors

### ISSUE THREAD

**Issue by Validark** [llvm/llvm-project#107248]
Currently, these two do not compile:

```llvm
; Function Attrs: nounwind uwtable nosanitize_coverage skipprofile
define dso_local void @st4(<2 x i8> %0, <2 x i8> %1, <2 x i8> %2, <2 x i8> %3, ptr align 1 nonnull %4) #0 {
5:
  call void @llvm.aarch64.neon.st4.v16i8.p0(<2 x i8> %0, <2 x i8> %1, <2 x i8> %2, <2 x i8> %3, ptr align 1 nonnull %4)
  ret void
}

; Function Attrs: nounwind uwtable nosanitize_coverage skipprofile
define dso_local void @st4(<4 x i8> %0, <4 x i8> %1, <4 x i8> %2, <4 x i8> %3, ptr align 1 nonnull %4) #0 {
5:
  call void @llvm.aarch64.neon.st4.v16i8.p0(<4 x i8> %0, <4 x i8> %1, <4 x i8> %2, <4 x i8> %3, ptr align 1 nonnull %4)
  ret void
}
```

It sounds to me like these are allowed though? https://developer.arm.com/documentation/dui0801/l/A64-SIMD-Vector-Instructions/ST4--vector--multiple-structures---A64-

Related https://github.com/llvm/llvm-project/issues/107099

EDIT: I can get the instruction I want using inline assembly, and LLVM doesn't stop me. https://zig.godbolt.org/z/bxq1jzbx5

```asm
        st4     { v0.2s, v1.2s, v2.2s, v3.2s }, [x0]
```

**Comment by davemgreen** [comment]
`<2 x i8>` are "illegal types" and the intrinsics generally only support the legal types (64bit and 128bit vectors under aarch64).

There isn't an instruction, as far as I understand, to store v2i8 elements like that. The .2s variant will be storing 32bit elements, which will be different in memory from what it sounds like you are after.

**Comment by Validark** [comment]
> `<2 x i8>` are "illegal types" and the intrinsics generally only support the legal types (64bit and 128bit vectors under aarch64).
> 
> There isn't an instruction, as far as I understand, to store v2i8 elements like that. The .2s variant will be storing 32bit elements, which will be different in memory from what it sounds like you are after.

Ohhhhh, right, it would have to be `.2b`, which is not allowed by the hardware.
