### ISSUE TITLE
[mlir][sparse] `disassemble` of COO returns incorrect shape of `%index` with Python bindings

### ISSUE THREAD

**Issue by mtsokol** [llvm/llvm-project#107202]
Hi! 

I noticed that in Python disassembling COO format, when `pos` and `index` shapes are dynamic returns an incorrect shape for `index`:

```mlir
%c0 = arith.constant 0 : index
%pos = tensor.empty(%c0) : tensor<?xindex>
%c0_0 = arith.constant 0 : index
%index = tensor.empty(%c0_0) : tensor<?x2xindex> 
```

The shape of `tensor<?x2xindex>` tensor is always `[0, 2]` where it should be `[3, 2]`. Here's a Python script that fully reproduces the issue:
https://gist.github.com/mtsokol/af61fd0c6fbe885cb7db417ba0e3800a

It works for the first return value `tensor<?xindex>` - the shape is `[2]`.

---

Tested on LLVM `19.1.0-rc3`

**Comment by aartbik** [comment]
The sparse tensor is

---- Sparse Tensor ----
nse = 3
dim = ( 3, 4 )
lvl = ( 3, 4 )
pos[0] : ( 0, 3 )
crd[0] : ( 0, 0, 1, 2, 1, 3 )
values : ( 1.1, 2.2, 3.3 )
----

and the lengths returned for the indices are 2 and 6 (2x3). The current assembler/disassembler works for statically known cases only (this is how Sparse JAX works, for PyTorch, we use another mechanism and allow for a non static number of nonzeros). So for now, the type should be tensor<3x2xindex> here.

**Comment by mtsokol** [comment]
Thank you!

I managed to solve it by using `sparse_tensor.number_of_entries` to define the first (dynamic) dimension of index:

```mlir
#sparse = #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed(nonunique), d1 : singleton), posWidth = 64, crdWidth = 64 }>

func.func @disassemble(%arg0: tensor<12x12xf64, #sparse>) -> (tensor<?xi64>, tensor<?x2xi64>, tensor<?xf64>, i64, i64, i64) attributes {llvm.emit_c_interface} {
  %0 = sparse_tensor.number_of_entries %arg0 : tensor<12x12xf64, #sparse>
  %c2 = arith.constant 2 : index
  %1 = tensor.empty(%c2) : tensor<?xi64>
  %2 = tensor.empty(%0) : tensor<?x2xi64>
  %3 = tensor.empty(%0) : tensor<?xf64>
  %ret_levels:2, %ret_values, %lvl_lens:2, %val_len = sparse_tensor.disassemble %arg0 : tensor<12x12xf64, #sparse> out_lvls(%1, %2 : tensor<?xi64>, tensor<?x2xi64>) out_vals(%3 : tensor<?xf64>) -> (tensor<?xi64>, tensor<?x2xi64>), tensor<?xf64>, (i64, i64), i64
  return %ret_levels#0, %ret_levels#1, %ret_values, %lvl_lens#0, %lvl_lens#1, %val_len : tensor<?xi64>, tensor<?x2xi64>, tensor<?xf64>, i64, i64, i64
}
```
