### ISSUE TITLE
Very weird concept checking inconsistency bug

### ISSUE THREAD

**Issue by strega-nil** [llvm/llvm-project#107215]
Note that this depends on libstdc++; I can't minimize the repro as I should not read libstdc++ code.

Here's the [godbolt](https://gcc.godbolt.org/z/Mdfaj968f).

```cxx
#include <span>
#include <iterator>

struct Incomplete;
int main() {
  using type1 = std::span<Incomplete>;
#ifdef WTF
  using type2 = type1::iterator; // when you touch any of `span`'s members, it makes this work
#endif // WTF
  using type3 = std::basic_const_iterator<
    std::reverse_iterator<
      __gnu_cxx::__normal_iterator<Incomplete*, std::span<Incomplete>>
    >
  >; // `type3` = `span<Incomplete>::const_reverse_iterator`; it's written this way in order to avoid instantiating `span<Incomplete>`'s members
}
```

**Comment by strega-nil** [comment]
Pinging @jwakely as this bug (and the equivalent bug in GCC, seems both compilers have the same bug) is the only reason that `span<Incomplete>` works in C++23 in libstdc++.

**Comment by jwakely** [comment]
Here it is with all libstdc++ code removed:

```c++
#include <iterator>

template<typename Iterator, typename>
class wrapped_iterator
{
  Iterator m_current;

  typedef std::iterator_traits<Iterator>		traits_type;

public:
  typedef typename traits_type::iterator_category iterator_category;
  typedef typename traits_type::value_type  	value_type;
  typedef typename traits_type::difference_type 	difference_type;
  typedef typename traits_type::reference 	reference;
  typedef typename traits_type::pointer   	pointer;

  reference operator*() const;
  pointer operator->() const;
  wrapped_iterator& operator++();
  wrapped_iterator operator++(int);
  wrapped_iterator& operator--();
  wrapped_iterator operator--(int);
  reference operator[](difference_type __n) const;
  wrapped_iterator& operator+=(difference_type __n);
  wrapped_iterator operator+(difference_type __n) const;
  wrapped_iterator& operator-=(difference_type __n);
  wrapped_iterator operator-(difference_type __n) const;
  bool operator==(wrapped_iterator const&) const = default;
  auto operator<=>(wrapped_iterator const&) const = default;
};

template<typename T>
struct span
{
  using iterator = wrapped_iterator<T*, span>;
  using reverse_iterator = std::reverse_iterator<iterator>;
  using const_iterator = std::const_iterator<iterator>;
  using const_reverse_iterator = std::const_iterator<reverse_iterator>;
};

struct Incomplete;
int main() {
  using type1 = span<Incomplete>;
  using niter = wrapped_iterator<Incomplete*, span<Incomplete>>;
#ifdef WTF
  using type2 = type1::iterator;
#endif // WTF
  using type3 = std::basic_const_iterator<std::reverse_iterator<niter>>;
}
```


When you use `basic_const_iterator<reverse_iterator<niter>>` it wants to check the associated namespaces of niter to do ADL for `iter_move`, which wants the associated namespaces of `span<Incomplete>` because that's a template argument of `niter`. If `span<Incomplete>` hasn't been instantiated yet it tries to complete it, which hits a constraint cycle. I haven't looked into exactly why the cycle happens.

Defining WTF causes the instantiation of `span<Incomplete>` to happen earlier, not as part of a constraint check. That instantiation completes successfully. When it's needed for the constraint checks, it's already complete.

**Comment by jwakely** [comment]
I don't think this is a Clang or GCC bug, you get exactly the same behaviour with MSVC:
https://gcc.godbolt.org/z/GExc4o4nd

I think what you're seeing is a consequence of how libstdc++ defines its `__normal_iterator` class template, with a second template argument, which the compiler wants to complete if possible when doing ADL. That's not a compiler bug.

**Comment by strega-nil** [comment]
Ooh, this is actually super helpful, thanks @jwakely. I apparently didn't look closely enough at the error from libstdc++; this means that we can likely get around this issue in libc++ as well. (It would still be nice not to be dealing with this)

**Comment by jwakely** [comment]
The error wasn't very helpful TBH. I just reduced the libstdc++ `__normal_iterator` and `span` implementations until I had a minimal reproducer, and observed that removing the second template parameter of `__normal_iterator` (or using `void` when instantiating it) got rid of the error.

**Comment by jwakely** [comment]
Maybe for libstdc++ it would make sense to write a partial specialization of `basic_const_iterator<__normal_iterator<I, C>>` that does all the constraint checks on `I` directly, so that we don't need to complete `C`. I don't know if something similar would help for libc++.

**Comment by jwakely** [comment]
No, that wouldn't work, because the constraint cycle happens when checking the `input_iterator` constraint for `basic_const_iterator`, and the primary template's constraints are checked even if an explicit/partial specialization matches.

**Comment by jwakely** [comment]
https://github.com/cplusplus/papers/issues/1264 would be nice here

**Comment by jwakely** [comment]
I'm going to test this change to `span` in libstdc++:

```diff
 template<typename T>
 struct span
 {
+  struct tag;
+  using iterator = wrapped_iterator<T*, tag>;
-  using iterator = wrapped_iterator<T*, span>;
```

This prevents the compiler from trying to complete `T` when doing ADL for `span<T>::iterator`, as described in [P2538R1](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2538r1.html).

**Comment by shafik** [comment]
CC @ldionne @mordante

**Comment by strega-nil** [comment]
This has been explained, so it's not a bug. Thanks @jwakely!
