### ISSUE TITLE
[flang] Error: INTEGER(KIND=-1) is not a supported type when disabling integer(KIND=16)

### ISSUE THREAD

**Issue by Renaud-K** [llvm/llvm-project#107341]
With the following test:
test.f90
```
integer(8) :: x
integer(Selected_Int_Kind(Range(x)+1)) y
end
```
flang-new errors when disabling integer(KIND=16)
`flang-new -fc1 -fdisable-integer-16 test.f90`

```
error: Semantic errors in test.f90
./test.f90:2:1: error: INTEGER(KIND=-1) is not a supported type
  integer(Selected_Int_Kind(Range(x)+1)) y
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by klausler** [comment]
The error is correct.  `RANGE(1._8)` is 307, and `SELECTED_REAL_KIND(307+1)` is -1 because there is no real kind with a precision of 308 bits.  `SELECTED_REAL_KIND(R=RANGE(1._8)+1)` produces 10 on x86-64.
