### ISSUE TITLE
[libc++] Recent change to libcxx/src/exception.cpp causes macro redefinition errors in Edge builds.

### ISSUE THREAD

**Issue by atulkatti** [llvm/llvm-project#107316]
The following commit defines LIBCPP_DISABLE_DEPRECATION_WARNINGS to libcxx/src/exception.cpp
https://github.com/llvm/llvm-project/pull/101830/commits/1e9c654671d32bdeed867d16889f6451135cdbdb 

However, Edge builds already built with LIBCPP_DISABLE_DEPRECATION_WARNINGS as we work towards removing some deprecated functions usage. This results in macro redefinition errors. Would it be OK to update exceptions.cpp definition to prevent errors like this in builds where this may have already been defined?

#ifndef LIBCPP_DISABLE_DEPRECATION_WARNINGS
#define LIBCPP_DISABLE_DEPRECATION_WARNINGS
#endif

**Comment by atulkatti** [comment]
I have opened a PR with a proposed fix. https://github.com/llvm/llvm-project/pull/107340

**Comment by ldionne** [comment]
We consider it "not a bug" since you shouldn't be building libc++ with arbitrary flags like this. Please see the discussion in https://github.com/llvm/llvm-project/pull/106719.
