### ISSUE TITLE
[Aarch64] inlining `uzp2` causes superfluous `ext` to be emitted

### ISSUE THREAD

**Issue by Validark** [llvm/llvm-project#107392]
This code ([Godbolt](https://zig.godbolt.org/z/b36bW8WM4)):

```zig
fn uzp2(x: @Vector(16, u8)) @Vector(16, u8) {
    return @shuffle(u8, x, undefined, [_]i32{1, 3, 5, 7, 9, 11, 13, 15, 1, 3, 5, 7, 9, 11, 13, 15});
}

fn fmov(x: @Vector(16, u8)) u64 {
    return @bitCast(@as([2]@Vector(8, u8), @bitCast(x))[0]);
}

export fn lower_uzp2(x: @Vector(16, u8)) u64 {
    return fmov(uzp2(x));
}
```

Compiles to this for the Apple M3:

```asm
lower_uzp2:
        uzp2    v0.16b, v0.16b, v0.16b
        fmov    x0, d0
        ret
```

However, if we inline both the `uzp2` and `fmov` functions (put an `inline` before `fn`), we get an extra `ext` instruction:

```asm
lower_uzp2:
        ext     v1.16b, v0.16b, v0.16b, #8
        uzp2    v0.8b, v0.8b, v1.8b
        fmov    x0, d0
        ret
```

Here is how Zig inlines these two:

```llvm
; Function Attrs: nounwind uwtable nosanitize_coverage skipprofile
define dso_local i64 @lower_uzp2(<16 x i8> %0) #0 {
1:
  %2 = alloca [16 x i8], align 8
  %3 = shufflevector <16 x i8> %0, <16 x i8> undef, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  store <16 x i8> %3, ptr %2, align 8
  %4 = getelementptr inbounds [2 x <8 x i8>], ptr %2, i64 0, i64 0
  %5 = load <8 x i8>, ptr %4
  %6 = bitcast <8 x i8> %5 to i64
  ret i64 %6
}
```

Also happens with this code:

```zig
export fn uzp2(x: @Vector(16, u8)) @Vector(8, u8) {
    return @shuffle(u8, x, undefined, [_]i32{ 1, 3, 5, 7, 9, 11, 13, 15 });
}
```

```llvm
; Function Attrs: nounwind uwtable nosanitize_coverage skipprofile
define dso_local <8 x i8> @uzp2(<16 x i8> %0) #0 {
1:
  %2 = shufflevector <16 x i8> %0, <16 x i8> undef, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  ret <8 x i8> %2
}
```

**Comment by davemgreen** [comment]
I believe https://github.com/llvm/llvm-project/pull/91328 might have helped here, I'm not sure how up-to-date the llvm codebase is in zig.

**Comment by Validark** [comment]
> I believe #91328 might have helped here, I'm not sure how up-to-date the llvm codebase is in zig.

Is there a godbolt playground that's up to date that has aarch64 as an emit target? It would be nice if I could just paste LLVM IR in somewhere to see if it's already been fixed.

**Comment by davemgreen** [comment]
I usually use the LLVM IR that is available on godbolt, and most llvm tools are cross-compilers by default so allow `-mtriple=aarch64`
https://godbolt.org/z/1Evn9aecz

**Comment by Validark** [comment]
> I usually use the LLVM IR that is available on godbolt, and most llvm tools are cross-compilers by default so allow `-mtriple=aarch64` https://godbolt.org/z/1Evn9aecz

I guess this is fixed then!
