### ISSUE TITLE
[AArch64] Does Apple m4 and Microsoft Surface Pro 11 (which is snapdragon x elite) support FeatureMTE?

### ISSUE THREAD

**Issue by trcrsired** [llvm/llvm-project#107351]
https://github.com/llvm/llvm-project/blob/aad699776496a80af5e062b446fe26a4313ff3e3/llvm/lib/Target/AArch64/AArch64Processors.td#L401

They do not have featuremte in the list. Am I missing something?

**Comment by efriedma-quic** [comment]
The feature lists are accurate as far as I know.

**Comment by trcrsired** [comment]
> The feature lists are accurate as far as I know.

so these cpus have no support of mte right?
