### ISSUE TITLE
Actions dependent on Tab key not working in Windows due to LLVM's LineEditor class (e.g. clang-query Tab auto-completion)

### ISSUE THREAD

**Issue by MichelleCDjunaidi** [llvm/llvm-project#107377]
As per https://github.com/llvm/llvm-project/pull/106672#issuecomment-2326442298, most of the Tab key actions relies on GNU read-line and as a result things like clang-query's Tab auto-completion doesn't work in Windows. LLVM currently has no fallback code for this.

**Comment by AaronBallman** [comment]
This isn't specific to clang-query, but is true of anything using LLVM's `LineEditor` class.
