### ISSUE TITLE
[flang] Many warnings issued from a module included by a use statement after disabling types

### ISSUE THREAD

**Issue by Renaud-K** [llvm/llvm-project#107337]
If you generate the ieee_arithmetic module while disabling types, there will be warnings. This could be expected and acceptable.
`flang-new -fc1 -fdisable-real-3 -fdisable-real-10 -fdisable-integer-16 ieee_arithmetic.f90 -fsyntax-only`

However, if you then compile a program, with the same compiler using this module, there will be warnings again.
ieee_main.f90
```
use ieee_arithmetic
end
```
`flang-new -fc1 -fdisable-real-3 -fdisable-real-10 -fdisable-integer-16 ieee_main.f90`
This however is no longer acceptable since there is nothing a user can do about them.

```
./ieee_arithmetic.mod:317:1: warning: REAL(KIND=3) is not an enabled type for this target
  real(3),intent(in)::y
  ^^^^^^^^^^^^^^^^^^^^^
./ieee_arithmetic.mod:389:1: warning: INTEGER(KIND=16) is not an enabled type for this target
  integer(16),intent(in)::radix
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/107421
