### ISSUE TITLE
Different formatting around type annotations with JS

### ISSUE THREAD

**Issue by kadircet** [llvm/llvm-project#107401]
a.js:
```
ctrl.onCopy(/** @type {!WizEvent}*/ (
    {event, targetElement: {el: () => selectedElement}}));
```

formatting after [this change](https://github.com/llvm/llvm-project/pull/93140) with `clang-format -style='{AlignAfterOpenBracket: AlwaysBreak}' a.js`
```
ctrl.onCopy(
    /** @type {!WizEvent}*/ (
        {event, targetElement : {el : () => selectedElement}}));
```

I can't really say this change looks like intended from the bug fix and code changes. Moreover,  these kind of type annotations seems to be [pretty common](https://github.com/search?type=code&auto_enroll=true&q=%22%28%2F**+%40type%22) so unless the change deliberately changing behavior here can we restore the old behavior ?

**Comment by kadircet** [comment]
cc @owenca @gedare @HazardyKnusperkeks

https://github.com/llvm/llvm-project/pull/93140 seems to be the change introducing this behavior

**Comment by owenca** [comment]
> I can't really say this change looks like intended from the bug fix and code changes. Moreover, these kind of type annotations seems to be [pretty common](https://github.com/search?type=code&auto_enroll=true&q=%22%28%2F**+%40type%22) so unless the change deliberately changing behavior here can we restore the old behavior ?

It looks like unintended, and I have no object to restoring the old behavior.
