### ISSUE TITLE
[mlir][vector] `vector::CombiningKind` uses wrong enum type in td

### ISSUE THREAD

**Issue by Hardcode84** [llvm/llvm-project#107448]
`vector::CombiningKind` currently uses `I32BitEnumAttrCaseBit` which cause enum to be generated like this:
```
enum class CombiningKind : uint32_t {
  ADD = 1,
  MUL = 2,
  MINUI = 4,
  MINSI = 8,
  MINNUMF = 16,
  MAXUI = 32,
  MAXSI = 64,
  MAXNUMF = 128,
  AND = 256,
  OR = 512,
  XOR = 1024,
  MAXIMUMF = 4096,
  MINIMUMF = 2048,
};
```
Which is most likely not what author intended, as those values are not supposed to be or'd together. Type should be `I32EnumAttrCase`.

**Comment by kuhar** [comment]
Do the gpu reduction kinds suffer from the same issue?

**Comment by Hardcode84** [comment]
`gpu::AllReduceOperation` is fine

**Comment by AmrDeveloper** [comment]
Interested, I will work on it
