### ISSUE TITLE
clang prints invisible black text on black background terminal

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#10757]
|  |  |
| --- | --- |
| Bugzilla Link | [10385](https://llvm.org/bz10385) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @jryans |

## Extended Description 
The compiler prints the text "note:" in black on my white-text-on-black-background terminal:

/tmp $ cat v.c
void g(void *);
void f(void) { void *volatile x; g(&x); }
/tmp $ clang -Wall -Wextra -Os -c v.c
v.c:2:36: warning: passing 'void *volatile *' to parameter of type 'void *' discards qualifiers
void f(void) { void *volatile x; g(&x); }
                                   ^~
v.c:1:14: note: passing argument to parameter here
void g(void *);
             ^
1 warning generated.
/tmp $

**Comment by cor3ntin** [comment]
`note:` is printed in grey, probably has been for a long time. I think we can close this
