### ISSUE TITLE
[clang] Clang must diagnose the use of [[lifetimebound]] annotation in void-returning functions

### ISSUE THREAD

**Issue by usx95** [llvm/llvm-project#107556]
https://godbolt.org/z/rcPnrWrr7

```cpp
#include <string>
struct S {
    void setS(const std::string& s [[clang::lifetimebound]]) { this->s = &s; }
    const std::string* s;
};

void foo() {
    S s;
    s.setS(std::string());
}
```

Lifetime analysis is currently not defined for parameters annotated with `[[lifetimebound]]` in void-returning function.
Current analysis only enforces that the annotated parameter outlives the **return** value. With no return value, this analysis is silently disabled.

**Comment by MitalAshok** [comment]
This is at least known about: https://github.com/llvm/llvm-project/blob/775f7f1c99562d0315be26aed7828e713bd3fc22/clang/test/SemaCXX/attr-lifetimebound.cpp#L4-L5

However, what about dependent void:

```c++
template<typename T>
std::add_lvalue_reference_t<const T> get_value(cached_function<T>& f [[clang::lifetimebound]]) {
  if (!f.has_value()) f.call_and_cache();
  return f.cached_value();
}
```

For `T = void`? The current behaviour of no extra analysis seems consistent

**Comment by changkhothuychung** [comment]
Can I pick this up? Can I have some more pointers what need to be done for this issue?
