### ISSUE TITLE
"External Clang Examples" web page should mention clang-tutor

### ISSUE THREAD

**Issue by hexagonrecursion** [llvm/llvm-project#107584]
The [External Clang Examples](https://clang.llvm.org/docs/ExternalClangExamples.html) page lists "... examples ... that might serve as useful guides (**or starting points**) from which to develop your own tools." (emphasis mine)

I think [clang-tutor](https://github.com/banach-space/clang-tutor) fits this definition and should be listed too. Clang-tutor provides a good tutorial on how to develop **out of tree** clang plugins - a topic that the official docs are quite sparse on

**Comment by shafik** [comment]
Thank you, that does sounds like a reasonable addition.
