### ISSUE TITLE
Memory allocated via `__builtin_operator_new` never starts its lifetime

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#107668]
This code should work:
```c++
namespace std {
  using size_t = decltype(sizeof(0));
  template<typename T> struct allocator {
    constexpr T *allocate(size_t N) {
      return (T*)::operator new(sizeof(T) * N);
    }
    constexpr void deallocate(void *p) {
      ::operator delete(p); // both-note {{std::allocator<...>::deallocate' used to delete pointer to object allocated with 'new'}}
    }
  };
}

constexpr int arrayAlloc() {
  int *F = std::allocator<int>().allocate(2);
  F[0] = 10;
  F[1] = 13;
  int Res = F[1] + F[0];
  std::allocator<int>().deallocate(F);
  return Res;
}
static_assert(arrayAlloc() == 23);
```
https://godbolt.org/z/a57f4vvMf

But the assignment to `F[0]` is currently diagnosed:
```
<source>:23:15: error: static assertion expression is not an integral constant expression
   23 | static_assert(arrayAlloc() == 23);
      |               ^~~~~~~~~~~~~~~~~~
<source>:17:8: note: assignment to object outside its lifetime is not allowed in a constant expression
   17 |   F[0] = 10;
      |   ~~~~~^~~~
<source>:23:15: note: in call to 'arrayAlloc()'
   23 | static_assert(arrayAlloc() == 23);
      |               ^~~~~~~~~~~~
```

(I used `::operator new` in the sample to please GCC, but using `__builtin_operator_new` has the same problem.

**Comment by MitalAshok** [comment]
That works at runtime because of implicit object creation, but in a constant expression no `int` object's lifetime would start (only the aggregate `int[2]`).

<http://eel.is/c++draft/allocator.members#5.sentence-2>:

> This function starts the lifetime of the array object, but not that of any of the array elements.

And `operator new` (`__builtin_operator_new` too) don't start any lifetimes themselves (except implicitly)

Is there a different reason you expect the lifetime of an `int` to begin?

**Comment by frederick-vs-ja** [comment]
Calls to allocating `operator new` are omitted in constant evaluation ([[expr.new]/15](https://eel.is/c++draft/expr.new#15)), so the restrictions in [[allocator.members]/5](https://eel.is/c++draft/allocator.members#5) override the general rule in [[intro.object]/14](https://eel.is/c++draft/intro.object#14) that `operator new` functions implicitly create objects.

Also, it's clarified [P2747R2](https://wg21.link/p2747r2) that `operator new` doesn't implicitly create objects in constant evaluation. I believe the wording change for [intro.object] in P2747R2 should be treated as (partial) resolution of [CWG2469](https://cplusplus.github.io/CWG/issues/2469.html) (and thus applied to older modes).

**Comment by tbaederr** [comment]
> Is there a different reason you expect the lifetime of an int to begin?

I just expected to be able to use the memory without a placement-new in the middle and if something works in GCC, I blame clang.

Sorry for the noise.
