### ISSUE TITLE
[RealtimeSanitizer] Problems with interceptor tests.

### ISSUE THREAD

**Issue by yingcong-wu** [llvm/llvm-project#107988]
I found some problems when running the recent added test for realtime sanitizer interceptor.

1. In my use case, I would enable `_FILE_OFFSET_BITS=64` by default, then the following test would fail because they don't have the 64bit version. 
```
RealtimeSanitizer-Unit::./Rtsan-x86_64-Test/RtsanOpenedFileTest/PreadDiesWhenRealtime
RealtimeSanitizer-Unit::./Rtsan-x86_64-Test/RtsanOpenedFileTest/PwriteDiesWhenRealtime
RealtimeSanitizer-Unit::./Rtsan-x86_64-Test/RtsanFileTest/CreatDiesWhenRealtime
RealtimeSanitizer-Unit::./Rtsan-x86_64-Test/RtsanFileTest/FcntlFlockDiesWhenRealtime
RealtimeSanitizer-Unit::./Rtsan-x86_64-Test/RtsanFileTest/FcntlSetFdDiesWhenRealtime
RealtimeSanitizer-Unit::./Rtsan-x86_64-Test/RtsanFileTest/FopenDiesWhenRealtime
RealtimeSanitizer-Unit::./Rtsan-x86_64-Test/RtsanFileTest/OpenDiesWhenRealtime
RealtimeSanitizer-Unit::./Rtsan-x86_64-Test/RtsanFileTest/OpenatDiesWhenRealtime
RealtimeSanitizer-Unit::./Rtsan-x86_64-Test/TestRtsanInterceptors/FcntlDiesWhenRealtime
```
Do we have plan to add the 64bit version of those functions to interceptors?

2. I use `Red Hat Enterprise Linux 9.0 (Plow)` and `Ubuntu 22.04 LTS`, and the following code will work fine with Ubuntu and will segment fault for the redhat.
```
#include <pthread.h>
int main() {
    pthread_t thread{};
    pthread_join(thread, nullptr);
    return 0;
}
```
Therefore test case PthreadMutexJoinDiesWhenRealtime would segment fault when I test it on the RedHat 9.

CC @cjappl.

**Comment by cjappl** [comment]
Thanks for reporting @yingcong-wu . I will check this out today and see what I can find. 

Also happy to review any PRs if you feel inspired to tackle either of these failures.

The interceptors are all defined in one place (rtsan_interceptors.cpp) and the tests are as well (rtsan_test_interceptors.cpp), so it should be easy to add what you need.

**Comment by cjappl** [comment]
I can reproduce the _FILE_OFFSET 64 issues, I will see what I can do to resolve those

**Comment by mgorny** [comment]
I'm also seeing that segfault on Gentoo, on glibc 2.39 and 2.40 systems.

On the glibc 2.40 system, I'm also seeing the following test failures (all with "failed to die" result):

```
  RealtimeSanitizer-Unit :: ./Rtsan-x86_64-Test/RtsanFileTest/OpenDiesWhenRealtime
  RealtimeSanitizer-Unit :: ./Rtsan-x86_64-Test/RtsanFileTest/OpenatDiesWhenRealtime
  RealtimeSanitizer-Unit :: ./Rtsan-x86_64-Test/RtsanOpenedFileTest/PreadDiesWhenRealtime
  RealtimeSanitizer-Unit :: ./Rtsan-x86_64-Test/RtsanOpenedFileTest/ReadDiesWhenRealtime
```

Do you want me to file a separate issue for what I believe to be glibc 2.40 regressions?

**Comment by cjappl** [comment]
Yes a separate issue would be great, thanks @mgorny

**Comment by cjappl** [comment]
I believe I have fixed both of these reported crashes. Please take a look at the associated PRs I've added you as reviewers to and see if that fixes your problems

**Comment by mgorny** [comment]
I've filed #108068 for the glibc 2.40 regressions.

**Comment by yingcong-wu** [comment]
Thank you @cjappl for such quick response. These two PR: https://github.com/llvm/llvm-project/pull/108040, https://github.com/llvm/llvm-project/pull/108057 solved my problems.

**Comment by cjappl** [comment]
Thank you for reporting! My partner and I will discuss about the _FILE_OFFSET fix, we need to align exactly on how the tests will run. (I would expect it only takes a couple days max to come to an agreement)

Please let me know if this is blocking your progress and we can merge quickly.

**Comment by cjappl** [comment]
@yingcong-wu both changes have now been submitted to main. Will you please check on latest main that everything is OK for you, and close this issue if so?

Thank you!

**Comment by yingcong-wu** [comment]
Thank you @cjappl , I think them work for me and I will close the issue now.
