### ISSUE TITLE
[abi] method parameter mangled as a substitution does not demangle correctly

### ISSUE THREAD

**Issue by VitaNuo** [llvm/llvm-project#108009]
While fiddling with the LLVM demangler, I noticed that in the following example 

```
template <typename T>
struct Bar{};

template <typename K>
struct Foo {
  template <typename T, template<typename U> typename S>
  void method(S<T> t, S<K> k);
};

void s() {
   Foo<int> k;
   Bar<int> i;
   Bar<bool> b;
   k.method(b, i);
}
```

the call `k.method(b, i)` is mangled as `_ZN3FooIiE6methodIb3BarEEvT0_IT_ES3_IiE`, which appears right (`Foo<int>::method<bool, Bar>(Bar<bool>, Bar<int>)`).
However, running the demangler

```
llvm-cxxfilt -n _ZN3FooIiE6methodIb3BarEEvT0_IT_ES3_IiE
```

produces `void Foo<int>::method<bool, Bar>(Bar<bool>, bool<int>)`.

`bool<int>` is obviously wrong and seems to stem from the `S3_` substitution.

**Comment by Michael137** [comment]
I do wonder why we don't mangle the second parameter as `T0_IiE`. Also, arent builtin types supposed to be excluded from being substitution candidates?

**Comment by ilya-biryukov** [comment]
Maybe there are problems with the mangler too, but given that GCC also mangles as `S3`, I suspect it's the demangler after all.
See https://gcc.godbolt.org/z/e9j4Mh79r

Note that GCC's demangler from compiler explorer actually demangles correctly too while Clang's demangler produces this error. I am not sure which ones they use (likely `c++filt`?)

**Comment by Michael137** [comment]
Yea what I meant was i find it surprising that the demangler considered `bool` a valid substitution candidate (i.e., something is adding it into the `Subs` table when it shouldn't). There seems to be some discrepancy between what Clang/GCC and the demangler consider a substitution. First instinct leans towards this being an issue with the demangler.

**Comment by VitaNuo** [comment]
The order I observe during mangling (with some parts rather confusing to me):

0. (S_) `ClassTemplateDecl` (`Foo`)
1. (S0_) `ClassTemplateSpecializationDecl` (`Foo<int>`)
2. (S1_)  `FunctionTemplateDecl` (`Foo<int>::method`)
3. (S2_) `ClassTemplateDecl` (`Bar` definition?)
4. (S3_) `TemplateTemplateParmDecl` (`Bar` in the `method` template params?)
5. (S4_) `TemplateTypeParmType` (`bool` in the `method` template params?)
6. (S5_) `TemplateSpecializationType` (`Bar<bool`)
7. (S6_) `TemplateSpecializationType` (`Bar<int>`)

Give the above order and assumptions, S3_ in mangling might be right (it substitutes the `Bar` in `Bar<int>` parameters with the `Bar` in `method` argument list that it's seen before).

Demangling might be building substitutions for `method` template arguments in the reverse order (`S3_` for `bool` and `S4_` for `Bar`), which might be causing this bug.

FWIW the order in the demangler seems to make more sense to me then, since `bool` is the first argument to `method` template, but in any case, they should at least agree.

**Comment by ilya-biryukov** [comment]
The `S4_` is actually a substitution for `T_`, which is coming from the template arguments of `method`.
(And happens to be `bool` in our case).
And `S3_` is not `Bar`, but a substitution for `T0_` (which happens to be `Bar` in our case).

I've checked the S4 specifically by using `bool` and `T` in further parameters and observing the mangling
https://gcc.godbolt.org/z/Eq6o3h6oK (note that `bool` stays `b`, but `T` substituted for bool gets replaced with `S4_`)

My theory is that the mangling is correct, but demanling seems to be getting confused either when adding or retrieving substitutions that involve `T`s or when resolving `Ts` into the actual types.

**Comment by Michael137** [comment]
> Demangling might be building substitutions for method template arguments in the reverse order (S3_ for bool and S4_ for Bar), which might be causing this bug.

Yea i think that's absolutely what happens. When parsing `T0_IT_E`, we would've first parsed `T_` and put it into the subs table (which here is `bool`). Then we put `Bar<bool>` into the table. So we ended up switching the order of `S3_` and `S4_`

**Comment by Michael137** [comment]
> Demangling might be building substitutions for method template arguments in the reverse order (S3_ for bool and S4_ for Bar), which might be causing this bug.

Yea i agree, (i think) that's absolutely what happens. When parsing `T0_IT_E`, we would've first parsed `T_` and put it into the subs table (which here is `bool`). Then we put `Bar<bool>` into the table. So we ended up switching the order of `S3_` and `S4_`.

**Comment by VitaNuo** [comment]
> So maybe the real issue is that we never add the basename as a subsitution.

I think this is correct. The code seems to add a substitution when parsing the type of the template argument (`bool`) and then the type of the method argument (`Bar<bool>`). It never adds a substitution after seeing a template template parameter name (`Bar`).
