### ISSUE TITLE
[llvm-dis][docs] Update the list of options on the file header

### ISSUE THREAD

**Issue by AmrDeveloper** [llvm/llvm-project#108069]
The current llvm-dis file mention only the help command on the header, should be updated with current available options.

https://github.com/llvm/llvm-project/blob/02c943a7ea7b798026baf34f108c18a5cde3821a/llvm/tools/llvm-dis/llvm-dis.cpp#L8-L16

Current options

https://github.com/llvm/llvm-project/blob/02c943a7ea7b798026baf34f108c18a5cde3821a/llvm/tools/llvm-dis/llvm-dis.cpp#L39-L85

- Make sure to not add hidden options

**Comment by txff99** [comment]
Hi, I can take a look

**Comment by MainakSil** [comment]
Hello,

I noticed this issue and would like to help resolve it. May I take this up and submit a pull request to update the header with the current available options?

Thank you!
