### ISSUE TITLE
[RISCV] RISCVMCInstLower not found

### ISSUE THREAD

**Issue by tianboh** [llvm/llvm-project#108141]
I want to lower my MachineInstr to MCInst on RISCV, and people told me I should check MCInstLower file. However, `RISCVMCInstLower.cpp ` is not in the project now. Is this file renamed or removed? How should I lower my MachineInstr to MCInst on RISCV?

**Comment by topperc** [comment]
It was merged into RISCVAsmPrinter.cpp. The separation didn't make a lot of sense. I can find the commit when I get back to my computer.

**Comment by jrtc27** [comment]
https://github.com/llvm/llvm-project/commit/11e5a0d290bac87f3290547fa2b0aaffc98a798e
