### ISSUE TITLE
[compiler-rt][nsan] Add an option to enable/disable comparison checking

### ISSUE THREAD

**Issue by alexander-shaposhnikov** [llvm/llvm-project#108435]
There are a few different potential approaches.
It might be easier to start with simply extending ```NSAN_OPTIONS``` with ```check_cmp``` and return early (in ```fCmpFailFT```) if the flag is false.
This is suboptimal in terms of performance, but might be more convenient / flexible.

**Comment by VaibhavRumale** [comment]
Hi, Can I work on this issue?

**Comment by alexander-shaposhnikov** [comment]
sure, sg

**Comment by alyyelashram** [comment]
Is someone still working on this or can I pick it up?
