### ISSUE TITLE
BPF store immediate instruction gated behind cpu=v4

### ISSUE THREAD

**Issue by brycekahle** [llvm/llvm-project#108457]
AFAICT the store immediate instruction `BPF_ST` has existed in the kernel since the original instruction set. Is there a reason this instruction is gated behind the `v4` cpu flag in LLVM? See https://github.com/llvm/llvm-project/commit/8f28e8069c4ba1110daee8bddc4d5049b6d4646e

**Comment by brycekahle** [comment]
@eddyz87

**Comment by eddyz87** [comment]
Enabling BPF_ST in codegen lead to a regression in BPF selftests, hence it was suggested to add a cpuv4 gate in order to avoid backwards compatibility issues, see discussion here:
https://lore.kernel.org/bpf/20221231163122.1360813-1-eddyz87@gmail.com/

**Comment by brycekahle** [comment]
Thanks for the context.
