### ISSUE TITLE
clang-format -n xyz.json ->  warning: code should be clang-formatted [-Wclang-format-violations]

### ISSUE THREAD

**Issue by skelutten** [llvm/llvm-project#108556]
clang-format -i xyz.json ->  silent and no changes done
clang-format -n xyz.json ->  warning: code should be clang-formatted [-Wclang-format-violations]

xyz.json:1.1 warning: code should be clang-formatted [-Wclang-format-violations]
{

Tested Clang 12.0.0 to Clang 18.1.8

**Comment by EugeneZelenko** [comment]
Could you please try 19 or `main` branch?

**Comment by owenca** [comment]
> clang-format -i xyz.json -> silent and no changes done clang-format -n xyz.json -> warning: code should be clang-formatted [-Wclang-format-violations]
> 
> xyz.json:1.1 warning: code should be clang-formatted [-Wclang-format-violations] {
> 
> Tested Clang 12.0.0 to Clang 18.1.8

Please provide a minimum reproducer if 19 or main still doesn't work for you.

**Comment by mydeveloperday** [comment]
What is in zyx.json? can you show us your .clang-format and that file please

**Comment by skelutten** [comment]
I tried with Clang 19.1 now with same result.

Used a file example.json with the content:
{
  "employee": {
    "name": "sonoo",
    "salary": 56000,
    "married": true
  }
}

clang-format  -i example.json
-> ok

clang-format  -n example.json 
example.json:1:1: warning: code should be clang-formatted [-Wclang-format-violations]
{
^

**Comment by skelutten** [comment]
And my .clang-format:
Language: Json
BasedOnStyle: Google

**Comment by owenca** [comment]
> Used a file example.json with the content:
> {
> "employee": {
> "name": "sonoo",
> "salary": 56000,
> "married": true
> }
> }

You need put the snippet in a code block to not lose the indentations:
```
{
  "employee": {
    "name": "sonoo",
    "salary": 56000,
    "married": true
  }
}
```

Otherwise, it would seem to work as expected:
```
$ clang-format example.json | diff example.json -
2,6c2,6
< "employee": {
< "name": "sonoo",
< "salary": 56000,
< "married": true
< }
---
>   "employee": {
>     "name": "sonoo",
>     "salary": 56000,
>     "married": true
>   }
```
