### ISSUE TITLE
Regression when formatting around `for` condition

### ISSUE THREAD

**Issue by kadircet** [llvm/llvm-project#108589]
formatted with `clang-format -style=Google a.ts`

actual formatting:
```
for await (
    const packageId of ops.api.iterateEmbeddedFiles(
        this.getFileId().getDriveFile(),
        )) {
}
```

expected formatting:
```
for await (const packageId of ops.api.iterateEmbeddedFiles(
    this.getFileId().getDriveFile(),
    )) {
}
```

**Comment by kadircet** [comment]
culprit seems to be ccae7b461be339e717d02f99ac857cf0bc7d17fc cc @owenca @gedare 

I can't really say expected is any better than actual formatting, but change seems to be unrelated to such code patterns, so it'd be preferred if we can preserve the existing behavior if this is incidental

**Comment by gedare** [comment]
> culprit seems to be [ccae7b4](https://github.com/llvm/llvm-project/commit/ccae7b461be339e717d02f99ac857cf0bc7d17fc) cc @owenca @gedare
> 
> I can't really say expected is any better than actual formatting, but change seems to be unrelated to such code patterns, so it'd be preferred if we can preserve the existing behavior if this is incidental

The `for await` is not being recognized as a type of `for` loop structure. The `await` is not known to the parser. Parsing this and treating it as a `for` loop should recover the expected behavior. I'll see if I can put something together today.
