### ISSUE TITLE
[HLSL][SPIRV] HLSL Entry points are not properly processed when targeting spirv

### ISSUE THREAD

**Issue by s-perron** [llvm/llvm-project#108567]
### Problem 1

If the entry point is [main](https://godbolt.org/z/K6T59sord), a new function is created to wrap around "main", which becomes the new entry point. Since the original function is already called "main", the entry point gets the name "main.1". This is what shows up in the `OpEntryPoint` instruction in the SPIR-V:

```
OpEntryPoint GLCompute %4 "main.1"
```

For DXIL, the original function is considered an internal function, and has its name mangled. This allow the actual entry point to get the name "main". See https://godbolt.org/z/oebKEKq1d.

### Problem 2

The `-E` option, which is used to identify an entry point other than main, is ignored. See https://godbolt.org/z/s5fP3661M. Note that csmain is viewed as an exported function, but not an entry point.

**Comment by michalpaszkowski** [comment]
Hi @s-perron! Thanks for bringing this up in the meeting last week! I think the solution with using Microsoft mangling for Vulkan would be the best option (as in your pull request). 

For reference, I am adding [a link to the OpenCL specification](https://www.khronos.org/files/opencl-spir-12-provisional.pdf) which requires SPIR to use extended Itanium mangling. This is also the mangling that Clang would use when feeding LLVM IR into the Khronos LLVM/SPIR-V Translator.

**Comment by s-perron** [comment]
The two problem have been fixed.
