### ISSUE TITLE
Warning for K&R declarations and definitions

### ISSUE THREAD

**Issue by jsonn** [llvm/llvm-project#10858]
|  |  |
| --- | --- |
| Bugzilla Link | [10486](https://llvm.org/bz10486) |
| Version | trunk |
| OS | Linux |
| CC | @efriedma-quic |

## Extended Description 
There is a lot of code still in the wild that uses K&R-style (non-)prototypes or definitions. It would be nice to have a non-default warning for this to make it easier to clean up larger code bases.

It would be even better to have an appropriate fixit.

**Comment by Endilll** [comment]
We warn about them by default since Clang 16: https://godbolt.org/z/KK9ddTc41
Details are available in [a Discourse thread](https://discourse.llvm.org/t/rfc-enabling-wstrict-prototypes-by-default-in-c/60521).
