### ISSUE TITLE
Different line breaking between type and name for paramters

### ISSUE THREAD

**Issue by kadircet** [llvm/llvm-project#108530]
a.ts, old formatting:
```
class Foo {
  private addGrammarCheckOneboxProductInfo(productInfo:
                                               {[key: string]: string;}) {}
}
```

`clang-format -style=Google a.ts`
```
class Foo {
  private addGrammarCheckOneboxProductInfo(
      productInfo: {[key: string]: string;}) {}
}
```

**Comment by kadircet** [comment]
ccae7b461be339e717d02f99ac857cf0bc7d17fc seems to be the culprit.

I am not really sure if the new formatting is better or worse, but it feels like this was an unintentional change and results in changes to certain existing files.

@owenca @gedare can you verify whether this is intended or incidental?

**Comment by gedare** [comment]
This is incidental, but I would also say that the old formatting was not intended either. Breaking between the type and name is generally avoided in the Cpp-like languages. This may not be handled very well for Typescript?

**Comment by kadircet** [comment]
SGTM, feel free to close as WAI then. It might still be worthwhile to add some unittests though (to make sure we don't change it to some other format incidentally in the future)
