### ISSUE TITLE
[flang][debug] Lower bound for assumed shape arrays is ignored.

### ISSUE THREAD

**Issue by abidh** [llvm/llvm-project#108633]
If an assumed shape array happens to have a lower bound, it is ignored by the generated debug info. See the example below.

```
subroutine show (arr)
  integer, dimension (-2:) :: arr
  arr(2) = 5
  print *, arr
 end subroutine show

program test
  interface
    subroutine show (arr)
      integer, dimension (:) :: arr
    end subroutine show
  end interface
  integer, dimension (15) :: arr
  arr = 7
  call show (arr)
  print *, arr
end program test
```

When stopped at line 4, this is what GDB shows 7 as the value of the arr(2) while it should have been 5.

```
(gdb) p arr(2)
$1 = 7
```

**Comment by pawosm-arm** [comment]
I suspect this is issue has something to do with the problem that I've observed. There is a difference in the gdb behavior for the gfortran and flang-new compiled binaries of the following Fortran program:

```
program test
  implicit none
  integer, dimension(-2:2,-3:3), target :: storage2d

  storage2d = -1
  call assumed_shape2d(storage2d)

contains

  subroutine assumed_shape2d(arr)
    implicit none
    integer :: arr(:,:)

    print *, arr(1,1)
  end

end program
```

With the breakpoint at line 14 (`print *, arr(1,1)`), although gdb is able to print the entire array contents, it requires different subscript ranges for the binaries compiled with gfortran and flang-new.
In case of gfortran-compiled binary, gdb allows using (1:5, 1:7) subscripts, in case of flang-new it expects the subscripts to be as defined in the main progran, (-2:2, -3:3). Apparently, the old classic-flang has replicated the gfortran's behavior, and now the tests I used for validating the classic-flang are failing on flang-new. Either flang-new is wrong, or gdb, classic-flang and the test case are wrong.

**Comment by pawosm-arm** [comment]
I wonder how far the problem with debugging the following lies from the one reported here:

```
program test
  implicit none
  integer, dimension(-2:2, -3:3), target :: storage2d
  integer, dimension(:, :), pointer :: pointer2d

  storage2d = -1
  pointer2d => storage2d(-1:1, -2:2)
  pointer2d = -7
  call automatic2d(5, 7, storage2d)

contains

  subroutine automatic2d(x, y, arr)
    implicit none
    integer :: x
    integer :: y
    integer :: arr(x, y)

    print *, arr
end

end program
```

With the breakpoint at line 19 (`print *, arr`), gdb is unable to print the contents of the array when this program was compiled with flang-new (no such problem when compiled with gfortran):

```
(gdb) print arr
$1 = <error reading variable: failed to get range bounds>
```
Also, as with the previous example, although the individual elements are somewhat accessible, the array subscript ranges are totally messed up.

**Comment by abidh** [comment]
> I wonder how far the problem with debugging the following lies from the one reported here:
> 
> ```
> program test
>   implicit none
>   integer, dimension(-2:2, -3:3), target :: storage2d
>   integer, dimension(:, :), pointer :: pointer2d
> 
>   storage2d = -1
>   pointer2d => storage2d(-1:1, -2:2)
>   pointer2d = -7
>   call automatic2d(5, 7, storage2d)
> 
> contains
> 
>   subroutine automatic2d(x, y, arr)
>     implicit none
>     integer :: x
>     integer :: y
>     integer :: arr(x, y)
> 
>     print *, arr
> end
> 
> end program
> ```
> 
> With the breakpoint at line 19 (`print *, arr`), gdb is unable to print the contents of the array when this program was compiled with flang-new (no such problem when compiled with gfortran):
> 
> ```
> (gdb) print arr
> $1 = <error reading variable: failed to get range bounds>
> ```
> 
> Also, as with the previous example, although the individual elements are somewhat accessible, the array subscript ranges are totally messed up.

This is issue #98879.

**Comment by abidh** [comment]
> I suspect this is issue which has something to do with the problem that I've observed. There is a difference in the gdb behavior for the gfortran and flang-new compiled binaries of the following Fortran program:
> 
> ```
> program test
>   implicit none
>   integer, dimension(-2:2,-3:3), target :: storage2d
> 
>   storage2d = -1
>   call assumed_shape2d(storage2d)
> 
> contains
> 
>   subroutine assumed_shape2d(arr)
>     implicit none
>     integer :: arr(:,:)
> 
>     print *, arr(1,1)
>   end
> 
> end program
> ```
> 
> With the breakpoint at line 14 (`print *, arr(1,1)`), although gdb is able to print the entire array contents, it requires different subscript ranges for the binaries compiled with gfortran and flang-new. In case of gfortran-compiled binary, gdb allows using (1:5, 1:7) subscripts, in case of flang-new it expects the subscripts to be as defined in the main progran, (-2:2, -3:3). Apparently, the old classic-flang has replicated the gfortran's behavior, and now the tests I used for validating the classic-flang are failing on flang-new. Either flang-new is wrong, or gdb, classic-flang and the test case are wrong.

It seems like the same problem as mentioned in the issue description. The debug info generated by flang-new is using lower bounds that were in the caller and now in the callee.
