### ISSUE TITLE
Clang with assertions crashes on invalid code `static_assert(true, ""`

### ISSUE THREAD

**Issue by zyn0217** [llvm/llvm-project#108687]
https://gcc.godbolt.org/z/1T39ex4db

```cpp
static_assert(true, ""
```

Uncovered by @dtcxzyw

**Comment by shafik** [comment]
So this looks like a regression: https://gcc.godbolt.org/z/h6GexT18E

**Comment by shafik** [comment]
> So this looks like a regression: https://gcc.godbolt.org/z/h6GexT18E

Looks like it crashes in trunk w/ `c++20` but crashes before trunk in `C++26` mode only but the backtraces look the same.
