### ISSUE TITLE
[libcxx][pstl][stdpar] What are the differences between libcxx/include/__pstl and pstl?

### ISSUE THREAD

**Issue by Ehu1** [llvm/llvm-project#108691]
Why does LLVM currently call std::for_each(std::execution::par, first, last, func) using the implementation under the include/__pstl directory in libcxx, rather than using the PSTL implementation in the LLVM library? Or, in other words, why was __pstl under the libcxx directory created? Are these two projects working on different things?

**Comment by ldionne** [comment]
The `<monorepo>/pstl` directory contains the original PSTL implementation contributed by Intel, which was intended to be shared between libc++ and libstdc++. When libc++ started working on PSTL more seriously last year, we realized that the dispatching mechanism was insufficient for our use cases, so we ended up reimplementing the functionality inside libc++.

As a result, libc++ no longer uses anything inside `<monorepo>/pstl`. I believe libstdc++ still imports those sources, but that should be clarified with the libstdc++ maintainers.

**Comment by Ehu1** [comment]
> The `<monorepo>/pstl` directory contains the original PSTL implementation contributed by Intel, which was intended to be shared between libc++ and libstdc++. When libc++ started working on PSTL more seriously last year, we realized that the dispatching mechanism was insufficient for our use cases, so we ended up reimplementing the functionality inside libc++.
> 
> As a result, libc++ no longer uses anything inside `<monorepo>/pstl`. I believe libstdc++ still imports those sources, but that should be clarified with the libstdc++ maintainers.

I understand this now, thank you for your reply!

**Comment by Ehu1** [comment]
> the dispatching mechanism was insufficient for our use cases

I want to gain a deeper understanding of what "the dispatching mechanism was insufficient for our use cases" means. Does this refer to the insufficiency of the execution policies, the limitations on CPUs or GPUs, or the inability to cover all of the std functions?

**Comment by ldionne** [comment]
The previous PSTL dispatching mechanism didn't make it easy to customize arbitrary algorithms, IIRC only the "base operations" were easily customizable. We now have that capability and we also gained the ability to stack backends so that each backend can implement what it wants to implement, but then defer to other backends.
