### ISSUE TITLE
Invalid llvm.fshl.i32 codegen on x86_64 (LLVM 18)

### ISSUE THREAD

**Issue by dnadlinger** [llvm/llvm-project#108722]
The following test program fails on Clang 18.1.0/x86_64 with -O1 and above:
```c
#include <assert.h>
#include <stdint.h>

uint32_t ror(uint32_t val, uint32_t amount) {
    return (val >> amount) | (val << (32 - amount));
}

__attribute__((noinline))
uint32_t bytesEqual(uint32_t val) {
    return ror(val, 8) == val;
}

int main() {
    assert(!bytesEqual(0x12345612));
}
```
See [on the Compiler Explorer here](https://godbolt.org/z/6aG3eh85M).

Clang 17 produces the following correct output:
```asm
bytesEqual(unsigned int):
        mov     ecx, edi
        rol     ecx, 24
        xor     eax, eax
        cmp     ecx, edi
        sete    al
        ret
```

Clang 18 replaces the computation with a `movzx` copying out the lower bytes, and a `shr` to just take the upper byte, i.e. comparing just those two:
```asm
bytesEqual(unsigned int):
        movzx   ecx, dil
        shr     edi, 24
        xor     eax, eax
        cmp     ecx, edi
        sete    al
        ret
```

(Reported by "user1234" on the LDC mailing list.)

**Comment by dnadlinger** [comment]
Both LLVM 17 and LLVM 18 end up with the same IR, so this appears to be an issue in the x86_64 backend concerning the `llvm.fshl.i32` codegen:
```llvm
define dso_local noundef i32 @_Z10bytesEqualj(i32 noundef %0) local_unnamed_addr {
  %2 = tail call i32 @llvm.fshl.i32(i32 %0, i32 %0, i32 24)
  %3 = icmp eq i32 %2, %0
  %4 = zext i1 %3 to i32
  ret i32 %4
}
```

**Comment by topperc** [comment]
CC: @goldsteinn I think this might be from ed7c97e0ad335eec8d65c00d8f963fea3455d4cf

**Comment by goldsteinn** [comment]
Will have fix up shortly.

**Comment by goldsteinn** [comment]
Fix at: https://github.com/llvm/llvm-project/pull/108767

**Comment by goldsteinn** [comment]
Sorry about all the assigned, meant to add you all as reviewers on the fix...

**Comment by goldsteinn** [comment]
Fix pushed in: https://github.com/llvm/llvm-project/commit/81279bf97f187eee0446af00d8ae9ec32a22e878

**Comment by goldsteinn** [comment]
/cherry-pick 81279bf97f187eee0446af00d8ae9ec32a22e878 1c378d2b145578948942512f9d6985e37659d013

**Comment by goldsteinn** [comment]
/cherry-pick 1c378d2b145578948942512f9d6985e37659d013 81279bf97f187eee0446af00d8ae9ec32a22e878

**Comment by dnadlinger** [comment]
Not sure how the process for this works, but the fix should probably be backported to 18.x as well, as this is a wrong-code regression in straight integer code (and looks like it might potentially affect crypto-related code as well).

**Comment by EugeneZelenko** [comment]
@dnadlinger: 18 is no longer maintained.
