### ISSUE TITLE
Clang 17/18 crashes with segmentation fault on compiling valid code.

### ISSUE THREAD

**Issue by Alexey104** [llvm/llvm-project#108778]
Compiling some code using C++20 features causes Clang 17.0.6/18.1.8 to crash with segmentation fault, while the same code compiles with Clang 16.0.6 or GCC. LLVM is obtained from ArchLinux repos via Pacman. Below is the minimal example I was managed to create to reproduce the issue:

[test.hpp.txt](https://github.com/user-attachments/files/17007478/test.hpp.txt)
[test.cpp.txt](https://github.com/user-attachments/files/17007479/test.cpp.txt)
[clang-output.txt](https://github.com/user-attachments/files/17007480/clang-output.txt)
[test-32f98a.cpp.txt](https://github.com/user-attachments/files/17007488/test-32f98a.cpp.txt)
[test-32f98a.sh.txt](https://github.com/user-attachments/files/17007489/test-32f98a.sh.txt)

**Comment by EugeneZelenko** [comment]
Could you please try 19 or `main` branch? https://godbolt.org should be helpful.

**Comment by Alexey104** [comment]
Thank you for your response, I will try to build from git when I have a bit more time and report back about the results.

**Comment by Alexey104** [comment]
OK, I built the latest `master` (20.0.0git) and I am unable to reproduce the problem anymore. I actually should've tried this before reporting a bug, sorry for the extra noise.
