### ISSUE TITLE
[flang][Semantics] Flang is unable to `use` a module it compiled

### ISSUE THREAD

**Issue by inaki-amatria** [llvm/llvm-project#108827]
- `flang-new` version is: `flang-new version 20.0.0git (https://github.com/llvm/llvm-project.git bafe3a4b0ca0e9294a18a9ec4fea8567cb98dabe)`
- Reduced test case:
```f90
! foo.f90
module foo
  use iso_c_binding, only : c_ptr, c_null_ptr

  implicit none

  private
  public :: foo_t

  type :: foo_t
    real(kind=4), dimension(:), contiguous, pointer :: buffer => null()
    type(c_ptr) :: c_ptr = c_null_ptr
  end type foo_t
contains
end module foo

! bar.f90
module bar
  use foo, only : foo_t

  implicit none

  private
  public :: bar_t

  type :: bar_t
    type(foo_t) :: buffer = foo_t()
  end type bar_t
end module bar

! main.f90
program main
  use bar
end program main
```
- `flang-new` invocation is: `flang-new foo.f90 bar.f90 main.f90`
- Expected behavior is: The code compiles successfully without errors.
- Actual behavior: Compilation fails with the following error:
```
bar.mod:9:47: error: Value in structure constructor of type 'REAL(4)' is incompatible with component 'c_ptr' of type 'c_ptr'
  type(foo_t)::buffer=foo_t(buffer=NULL(),c_ptr=c_ptr(__address=0_8))
                                                ^^^^^^^^^^^^^^^^^^^^
foo.mod:12:14: Declaration of 'c_ptr'
  type(c_ptr)::c_ptr=__builtin_c_ptr(__address=0_8)
               ^^^^^
bar.mod:9:53: error: Keyword '__address=' may not appear in a reference to a procedure with an implicit interface
  type(foo_t)::buffer=foo_t(buffer=NULL(),c_ptr=c_ptr(__address=0_8))
                                                      ^^^^^^^^^
```

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/108892

**Comment by pawosm-arm** [comment]
I'm still observing it in CP2K:

```
error: Semantic errors in dbt_types.F90
./cp_dbcsr_api.mod:321:1527: error: Value in structure constructor of type 'REAL(4)' is incompatible with component 'dist' of type 'dbcsr_distribution_obj'
  type(dbcsr_type_prv),private::prv=dbcsr_type_prv(prv=dbcsr_types$dbcsr_type(serial_number=-1_4,valid=.false._4,name="                                                                                ",data_area=dbcsr_data_obj(d=NULL()),index=NULL(),row_p=NULL(),col_i=NULL(),blk_p=NULL(),thr_c=NULL(),coo_l=NULL(),ro
w_blk_size=array_i1d_obj(low=NULL()),col_blk_size=array_i1d_obj(low=NULL()),row_blk_offset=array_i1d_obj(low=NULL()),col_blk_offset=array_i1d_obj(low=NULL()),local_rows=array_i1d_obj(low=NULL()),global_rows=array_i1d_obj(low=NULL()),local_cols=array_i1d_obj(low=NULL()),global_cols=array_i1d_obj(low=NULL()),has_loca
l_rows=.false._4,has_global_rows=.false._4,has_local_cols=.false._4,has_global_cols=.false._4,max_rbs=-1_4,max_cbs=-1_4,sparsity_id=-1_4,id_nr=-1_4,nblks=-1_4,nze=-1_4,nblkrows_total=-1_4,nblkcols_total=-1_4,nfullrows_total=-1_4,nfullcols_total=-1_4,nblkrows_local=-1_4,nblkcols_local=-1_4,nfullrows_local=-1_4,nfull
cols_local=-1_4,data_type=-1_4,replication_type=" ",symmetry=.false._4,negate_real=.false._4,negate_imaginary=.false._4,bcsc=.false._4,local_indexing=.false._4,list_indexing=.false._4,data_memory_type=dbcsr_memtype_type(mpi=.false._4,acc_hostalloc=.false._4,acc_devalloc=.false._4,acc_stream=acc_stream_type(dummy=1_
4),pool=NULL(),oversize_factor=1._8),index_memory_type=dbcsr_memtype_type(mpi=.false._4,acc_hostalloc=.false._4,acc_devalloc=.false._4,acc_stream=acc_stream_type(dummy=1_4),pool=NULL(),oversize_factor=1._8),buffers=dbcsr_block_buffer_obj(b=NULL()),wms=NULL(),dist=dbcsr_dist_prv_obj(d=NULL()),refcount=0_4,work_mutab
le=.false._4))
```

**Comment by pawosm-arm** [comment]
The CP2K regression (quoted above) has been introduced by this commit: https://github.com/cp2k/cp2k/pull/3438 after which the flang bug reported here starts to occur. @klausler do you have some spare capability to look into it?

**Comment by klausler** [comment]
> The CP2K regression (quoted above) has been introduced fairly recently by this commit: [cp2k/cp2k#3438](https://github.com/cp2k/cp2k/pull/3438) after which the flang bug reported here starts to occur. [@klausler](https://github.com/klausler) do you have some spare capability to look into it?

Do you have a smaller reproducing test case?

**Comment by pawosm-arm** [comment]
> > The CP2K regression (quoted above) has been introduced fairly recently by this commit: [cp2k/cp2k#3438](https://github.com/cp2k/cp2k/pull/3438) after which the flang bug reported here starts to occur. [@klausler](https://github.com/klausler) do you have some spare capability to look into it?
> 
> Do you have a smaller reproducing test case?

What would be your strategy of preparing such reproducer? I looked through all the types related to `dbcsr_type` and `dbcsr_distribution_obj` (`dbcsr_distribution_type`) all through CP2K and dbcsr sources and can't find anything `REAL(4)` (`REAL(KIND=real_4)`) anywhere near those types. The underlying data is kept in arrays of integers defined as such: `INTEGER, DIMENSION(:), POINTER, CONTIGUOUS :: DATA => Null()`, I can't figure out where this `REAL(4)` type could have sneaked from, so I can't prepare a reproducer like the one initially in this bug report...

**Comment by inaki-amatria** [comment]
Hi @pawosm-arm

You can use [C-Vise](https://github.com/marxin/cvise) to reduce the code to a minimal reproducer. C-Vise systematically removes unnecessary lines while preserving the behavior that triggers the bug. In other words, it simplifies the code iteratively until only the essential lines remain to reproduce the issue.

Suppose you have this Fortran program (`foo.f90`) that triggers a **semantic error** in Flang:

```fortran
program foo
  integer :: a
  a = 40
  print *, a
  call bar()
contains
  subroutine bar()
    integer :: b(a)
    integer :: a
    a = 50
    print *, a
  end
end
```

Flang reports the following error:

```bash
error: Semantic errors in foo.f90
foo.f90:8:18: error: Forward reference to 'a' is not allowed in the same specification part
      integer :: b(a)
                   ^
foo.f90:8:18: Later declaration of 'a'
      integer :: b(a)
                   ^
```

To reduce this test case using C-Vise, you need a script that compiles the code and checks for the error.

Create a file called `reduce.bash` and add the following:  

```bash
#!/bin/bash
flang foo.f90 2>&1 | grep "Forward reference to 'a' is not allowed in the same specification part"
```

Make the script executable:

```bash
chmod +x reduce.bash
```

Run **C-Vise**:  

```bash
$ cvise --not-c reduce.bash foo.f90
00:00:00 INFO ===< 8201 >===
00:00:00 INFO running 14 interestingness tests in parallel
00:00:00 INFO INITIAL PASSES
00:00:00 INFO ===< BlankPass >===
00:00:00 INFO ===< LinesPass::0 >===
00:00:01 INFO (22.1%, 127 bytes, 10 lines)
00:00:02 INFO (30.1%, 114 bytes, 9 lines)
00:00:02 INFO (38.0%, 101 bytes, 8 lines)
00:00:03 INFO (44.8%, 90 bytes, 7 lines)
00:00:03 INFO (54.0%, 75 bytes, 6 lines)
. . .
Runtime: 36 seconds

contains
  subroutine bar0
    integer b(a)
    integer a
  end
end
```

This reduced version still triggers the error, but is much smaller and easier to analyze.

Please note that reducing a Fortran source file that depends on other modules can be tricky. If your code has a `use` statement that imports symbols from another module, you need to reduce both files together. My recommended strategy is:

1. First, reduce the file that triggers the compilation error (e.g., `foo.f90`).
2. If you reach a state where `foo.f90` still contains a `use` statement, copy and paste the relevant module source into the working directory where you are running C-Vise.
3. Run C-Vise on both files simultaneously:
```bash
