### ISSUE TITLE
[flang] Flang is unable to compile a code with a call to `transfer`

### ISSUE THREAD

**Issue by inaki-amatria** [llvm/llvm-project#108832]
- `flang-new` version is: `flang-new version 20.0.0git (https://github.com/llvm/llvm-project.git bafe3a4b0ca0e9294a18a9ec4fea8567cb98dabe)`
- Reduced test case:
```f90
! main.f90
program main
  use iso_fortran_env, only : real32, int32
  real(kind=real32) :: mask_val
  integer(kind=int32), dimension(2) :: i4tmp
  i4tmp = transfer(mask_val, i4tmp)
end program main
```
- `flang-new` invocation is: `flang-new main.f90`
- Expected behavior is: The code compiles successfully without errors. According to https://gcc.gnu.org/onlinedocs/gcc-9.2.0/gfortran/TRANSFER.html: "If the bitwise representation of the result is longer than that of SOURCE, then the leading bits of the result correspond to those of SOURCE and any trailing bits are filled arbitrarily."
- Actual behavior: Compilation fails with the following error:
```
error: Semantic errors in main.f90
main.f90:5:3: error: Dimension 1 of left-hand side has extent 2, but right-hand side has extent 1
    i4tmp = transfer(mask_val, i4tmp)
    ^^^^^
```

**Comment by klausler** [comment]
Working as intended.  See Fortran 2023 subclause 16.9.212: "If MOLD is an array and SIZE is absent, the result is an array and of rank one. Its size is as small as possible such that its physical representation is not shorter than that of SOURCE."  Add `SIZE=SIZE(i4tmp)` to make it larger in a portable and standard-conforming way.

**Comment by inaki-amatria** [comment]
Thank you so much for the clarification
