### ISSUE TITLE
SPEC CPU 2017 511.povray_r fails at runtime when built with clang-cl on Windows

### ISSUE THREAD

**Issue by pulidocr** [llvm/llvm-project#109012]
Hi,

I'm trying to run SPEC CPU 2017 C/C++ benchmarks on Windows with clang-cl, but for some reason it is failing at runtime for 511.povray_r. It fails with `-clang:-O3 -clang:-ffast-math` which suggests it might be a miscompilation. Any help reducing the problem further would be appreciated - for now, I have provided a small config file.

Additional details:

- It used to work with LLVM 17 but fails with LLVM 18.
- Happens on both x64 and ARM64 Windows.

Minimal config file:

```
CC_VERSION_OPTION   =  ""
CXX_VERSION_OPTION  =  ""
CC                 = clang-cl.exe /TC
CLD                = clang-cl.exe
CXX                = clang-cl.exe /TP
CXXLD              = clang-cl.exe
OBJ                = .obj
PORTABILITY = /DSPEC_P64
OPTIMIZE    = -clang:-O3 -clang:-ffast-math
CXXOPTIMIZE = /EHsc
```

Repro steps:

1. Obtain SPEC CPU 2017 and set it up for Windows
2. Download Visual Studio 2022 and install the "Desktop development with C++" workload.
3. Install clang/LLVM through LLVM's installer.
4. Copy and paste the above config file contents to `spec2017\config\test.cfg`
5. Open x64 Native Tools Command Prompt for VS2022
6. If clang-cl.exe is not already on PATH, `set "PATH=path\to\LLVM\bin;%PATH%`
7. `cd path\to\spec2017`
8. `shrc.bat`
9. `runcpu -a validate --rebuild --size test  --iterations 1 -c test 511.povray_r`
10. Observe that the benchmark builds successfully, but fails at runtime with LLVM 18. Works with LLVM 17.

**Comment by topperc** [comment]
povray uses infinity as a place holder for an uninitialized value. This not compatible with `-ffast-math`. You can add `-fno-finite-math-only` after `-ffast-math`.

**Comment by pulidocr** [comment]
Got it, thanks for the information.
