### ISSUE TITLE
Compilation failures around structs in code generated by C backend

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#10917]
|  |  |
| --- | --- |
| Bugzilla Link | [10545](https://llvm.org/bz10545) |
| Version | trunk |
| OS | Linux |
| Attachments | [Patch with suggested fixes](https://user-images.githubusercontent.com/60944935/143743580-f22999ce-4619-4fb6-9e91-b8db9125df7b.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Code generated by C backend as of rev 136600 produces errors when compiled with gcc due to missing struct keyword in three places and incorrectly placed name for structure embedding array.

Attached is patch to fix these problems.

**Comment by arsenm** [comment]
C backend no longer exists
