### ISSUE TITLE
-mvzeroupper

### ISSUE THREAD

**Issue by fbarchard** [llvm/llvm-project#109186]
In XNNPack we have a mix of SSE2 and AVX2 code.  Is _mm256_zeroupper() still required in all avx and avx512 code?

In this PR vzeroupper is automatically added.  Nov 2019... clang 9.01
https://reviews.llvm.org/D69786

I found 7 microkernels in XNNPack that do _mm256_zeroupper() and require it.  I remove the call and run a perf stat on skylake
It shows no sse-avx-assists.
Disassembling one of the avx kernels, clang added the vzeroupper.

But in godbolt, a simple avx function does not generate a vzeroupper?
https://godbolt.org/z/5E4KKc6Kv

I was wanting to test different compilers / versions to see which compilers require explicite _mm256_zeroupper() 
Is this a bug?

**Comment by alexander-shaposhnikov** [comment]
cc @topperc

**Comment by efriedma-quic** [comment]
If a function's arguments or return type are 256-bit or wider vector types, we know the caller is AVX-enabled, so we don't vzeroupper.

**Comment by topperc** [comment]
> If a function's arguments or return type are 256-bit or wider vector types, we know the caller is AVX-enabled, so we don't vzeroupper.

We do vzeroupper if the function doesn't return a 256-bit vector. https://godbolt.org/z/zzMvKa47r
