### ISSUE TITLE
The imported target "clang-cpp" references the file [cmake]  [cmake]      "/usr/lib/llvm-20/lib/libclang-cpp.so.20.0" [cmake]  [cmake]   but this file does not exist.

### ISSUE THREAD

**Issue by Zingam** [llvm/llvm-project#109153]
Configuring libc++ fails when using LLVM20 installed by `llvm.sh` on Ubuntu 24.04 Noble.

> [cmake] CMake Error at /usr/lib/llvm-20/lib/cmake/clang/ClangTargets.cmake:847 (message):
[cmake]   The imported target "clang-cpp" references the file
[cmake] 
[cmake]      "/usr/lib/llvm-20/lib/libclang-cpp.so.20.0"
[cmake] 
[cmake]   but this file does not exist.  Possible reasons include:
[cmake] 
[cmake]   * The file was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and contained
[cmake] 
[cmake]      "/usr/lib/llvm-20/lib/cmake/clang/ClangTargets.cmake"

This is the latest issue in a series of issues related to LLVM19/20: 
https://github.com/llvm/llvm-project/issues/107116
https://github.com/llvm/llvm-project/issues/99819
https://github.com/llvm/llvm-project/issues/108995

**Comment by kimgr** [comment]
We're using the following workaround in IWYU CI: https://github.com/include-what-you-use/include-what-you-use/blob/5ac52caf1529630e6aa7932e0ea9382fca206fb4/.github/workflows/ci.yml#L50

**Comment by kimgr** [comment]
This is fixed for both 19 and 20 as far as I can tell from the consuming side.

**Comment by sylvestre** [comment]
Yes. Thanks
Forgot to close it
