### ISSUE TITLE
Does LLVMGold support Windows PE files?

### ISSUE THREAD

**Issue by CycloneRing** [llvm/llvm-project#109248]
Hi, I'm using Clang/MinGW/MSYS2 to compile Qemu on Windows x64 for Windows x64
When i use --enable-lto otpion clang is asking for LLVMGold.dll which is not presented in Clang and LLVM package in MSYS2.
After hours of searching I found there's a LLVMGold.dll in old NDK packages.
Also on the LLVM docs I've seen it mentioned Gold is a linker for ELF only. Now I'm confused.
Does LLVMGold.dll supports optimizing .dll and .exe files on windows or it's only for unix? 
Why it was offered as dll inside NDK for windows before?
Is there an alternative for Windows PE files?
I am using version 18.1.8

**Comment by CycloneRing** [comment]
@DimitryAndric I installed all the required packages, I need to confirm LLVMGold itself doesn't support windows binaries, And know why my clang is looking for LLVMGold.dll in mingw64\lib folder after passing --enable-lto

Since I'm using meson, lld doesn't function properly as meson forcefully passes some paramters lld doesn't support, I searched for hours and none of the current fixes work, But overall the reason of opening this issue is just to know the things I mentioned above, I want to know and confirm them.

**Comment by MaskRay** [comment]
No. GNU gold only supports ELF. The CMake build system does some check like `LLVM_BINUTILS_INCDIR` to decide whether to build `LLVMgold.so`.

> Since I'm using meson, lld doesn't function properly as meson forcefully passes some paramters lld doesn't support, I searched for hours and none of the current fixes work, But overall the reason of opening this issue is just to know the things I mentioned above, I want to know and confirm them.

Not familiar with Meson, but it seems that some options might need to be adjusted. Certain useful options can be implemented.
