### ISSUE TITLE
[libc][[math] Implement Classification Macros

### ISSUE THREAD

**Issue by Sh0g0-1758** [llvm/llvm-project#109201]
Refer section 7.12.3 of the [ISO spec](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf). We still have some unimplemented math function macros. The following are to be implemented : 

- [x] fpclassify #109519 
- [x] iscanonical #111403 
- [x] isnormal #109547 
- [x] issignaling #109615 #111403
- [x] issubnormal #109572 
- [x] iszero #109336 

cc : @lntue

**Comment by Sh0g0-1758** [comment]
Kindly assign the issue to me, @lntue

**Comment by Sh0g0-1758** [comment]
Closing this as all the math macro functions are successfully implemented now 🎉

cc: @lntue

**Comment by lntue** [comment]
Thanks @Sh0g0-1758 for completing this issue!
