### ISSUE TITLE
[clang] Assertion failed in LoopVectorize

### ISSUE THREAD

**Issue by cardigan1008** [llvm/llvm-project#109561]
When I compiled this code with O2, it crashed:

```c
long a;
int b;
int c;
long d;
void e() {
  for (int f = 0; f < b; f++)
      d = c > 0 ? a / c : 1;
}
```

Crash is:
```
VPIRBasicBlock can only be used as pre-header or a successor of middle-block at the moment!
clang: /root/llvm-project/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:8593: void llvm::LoopVectorizationPlanner::buildVPlansWithVPRecipes(llvm::ElementCount, llvm::ElementCount): Assertion `verifyVPlanIsValid(*Plan) && "VPlan is invalid"' failed.
```

Details can be found here: https://godbolt.org/z/7nhzEWb81

**Comment by shafik** [comment]
This looks like a clang trunk regression: https://godbolt.org/z/1d3nvjK9v

Was this a fuzzer generated bug?

**Comment by cardigan1008** [comment]
> This looks like a clang trunk regression: https://godbolt.org/z/1d3nvjK9v
> 
> Was this a fuzzer generated bug?

Yes, I’m currently working on a new fuzzing technique.

**Comment by fhahn** [comment]
Looks like this is a duplicate of https://github.com/llvm/llvm-project/issues/109510 and should be fixed on latest `main` (https://github.com/llvm/llvm-project/commit/bd8fe9972e3f17776e4e05e69e13ab8271d34132 from yesterday)
