### ISSUE TITLE
[flang] list-directed output of a character literal constant line wraps after 78 characters

### ISSUE THREAD

**Issue by rouson** [llvm/llvm-project#109589]
Hopefully the bug reproducer below suffices to describe and reproduce this issue.  The same problem occurs if `print *,` is replaced with `write(*,*)`.  The problem also occurs if the character literal constant is replaced with a `character` variable.  No wrapping occurs if the `*` format is replaced with `"(a)"`.
```
% cat list-directed-output-wraps.f90 
print *, "List-directed printing of a character literal constant of length > 78 characters wraps around to a new line."
end
% flang-new list-directed-output-wraps.f90 
% ./a.out
 List-directed printing of a character literal constant of length > 78 characte
 rs wraps around to a new line.
% flang-new --version
flang-new version 20.0.0git (git@github.com:llvm/llvm-project 3acb1eac5eb6ef4e60dd64b7845615e076cc6a3e)
Target: arm64-apple-darwin23.6.0
Thread model: posix
InstalledDir: /Users/rouson/Repositories/llvm-project/build/bin
```

**Comment by klausler** [comment]
The maximum line length for list-directed output is set by the runtime environment variable FORT_FMT_RECL, whose default is 78 if memory serves.
