### ISSUE TITLE
[Clang-Cl][Modules][VS2022]

### ISSUE THREAD

**Issue by MohammedAhmed381** [llvm/llvm-project#109586]
using clang-cl 19.1.0 and visual studio 2022 latest version
With this properties
Build Iso c++23 standered library module set to yes
Scan sources fo buildup dependences set to yes
and cpp preview features
```
import std;
int main() 
{
  return 0;
}
```
and compile error was 
```
1>FileName.cpp(1,8): fatal  error : module 'std' not found
```
in the meanwhile msvc compilles successfully
and the same thing happens if I make cppm file
then try to import the new module in cppm

ane even if I used single headers
```
import <iostream>;
```

is it a bug or am I missing something

**Comment by MohammedAhmed381** [comment]
hey, I am trying to post it on llvm forms but it gives me Eror::Access denied..

**Comment by frederick-vs-ja** [comment]
Not sure whether this should go to https://github.com/microsoft/STL/issues.

**Comment by MohammedAhmed381** [comment]
so should repsot it in another place or leave it here in issues??

**Comment by ChuanqiXu9** [comment]
I think this is duplicated with https://github.com/llvm/llvm-project/issues/93722. So I'll close this.

**Comment by MohammedAhmed381** [comment]
@ChuanqiXu9 
but this is not about std only (yes import std is part of the problem)...
clang cl does not import any module.. even the ones I created by cppm files.
it is included in the solution with Visual Studio and msvc can compile it.
but clang cl can not.
and to replicate it :
1) create new vs solution.
2) Modify The above settings to enable modules
2) create a cppm file, and add Test module
```
export module Test;
```
4) Create a cpp file, and import Test module and main func
```
import Test;
int main(){ return 0; };
```
not it compiles with MSVC with out any errors
but when switching to clang cl 19.1.0
it send this error
```
fatal  error : module 'Test' not found
```

**Comment by ChuanqiXu9** [comment]
It looks like you're not using a build system. Maybe it is due to build system has not support clang-cl yet. From @sharadhr , what I heard is, the clang-cl should work basically.
