### ISSUE TITLE
[ARM][AARCH64] clang doesn’t support mfence in aarch64 or arm?

### ISSUE THREAD

**Issue by Zhenhang1213** [llvm/llvm-project#109652]
I find neither AArch64 nor ARM supports this, but x86 is ok;  but in gcc, it‘s ok.  And I don't find  reference about this case
[godbolt](https://godbolt.org/z/5q4K8vrME)
```
__asm__ __volatile__("mfence" : : : "memory")
```

**Comment by antoniofrighetto** [comment]
*fence is x86 specific, so clang's behaviour is correct. You may be looking for a dmb instead (https://developer.arm.com/documentation/100941/0101/Barriers).
