### ISSUE TITLE
Does Signals.cpp require cxxabi.h?

### ISSUE THREAD

**Issue by oroppas** [llvm/llvm-project#10973]
|  |  |
| --- | --- |
| Bugzilla Link | [10601](https://llvm.org/bz10601) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Hi,

When I tried to have llvm/clang self-hosted with clang++/libc++ pair with
-stdlib=libc++, clang++ complained about missing cxxabi.h:

[  1%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/Signals.cpp.o
In file included from /home/ryuta/devel/llvm/src/llvm/lib/Support/Signals.cpp:30:
/home/ryuta/devel/llvm/src/llvm/lib/Support/Unix/Signals.inc:31:10: fatal error: 
      'cxxabi.h' file not found
#include <cxxabi.h>
         ^
1 error generated.
make[2]: *** [lib/Support/CMakeFiles/LLVMSupport.dir/Signals.cpp.o] Error 1

The search paths of clang++ -stdlib=libc++ are:

#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/v1
 /usr/local/include
 /usr/bin/../lib/clang/3.0/include
 /usr/include
End of search list.

This missing header case makes sense since libc++ doesn't come with cxxabi.h.
To see what function declarations from cxxabi.h are needed, I created an empty cxxabi.h in /usr/include/c++/v1 just to circumvent the missing header error.
Surprisingly, the compiler did not make a single warning nor error for the empty cxxabi.h, which indicates at least lib/Support/Signal.cpp doesn't need to include cxxabi.h. So, my question is: Does LLVMSupport have an *explicit* dependency on cxxabi? Or does it require cxxabi itself in general?

**Comment by arsenm** [comment]
Old build question
