### ISSUE TITLE
libc++.1.0.dylib of macos x64 binary(llvm 19.1.0)  cause segmentation fault 

### ISSUE THREAD

**Issue by lnpg** [llvm/llvm-project#109782]
libc++.1.0.dylib of macos x64 binary  cause segmentation fault before enter main, replace it with binary from brew intallation, execution pass.

**Comment by ldionne** [comment]
@lnpg Can you please provide a reproducer? Is there any error message? What's the crash like?

Sorry but there's very little we can do with the amount of information you provided so far. Please provide that information and reopen.

**Comment by lnpg** [comment]
I am using clion, 
the toolchain setting is this:
<img width="933" alt="Screenshot 2024-09-27 at 22 52 37" src="https://github.com/user-attachments/assets/bd4b94d1-b5dc-4f27-8e92-fededd96cbd7">
the cmake profiles is all default like:
<img width="1270" alt="Screenshot 2024-09-27 at 22 53 43" src="https://github.com/user-attachments/assets/e9dd7bc3-6135-4d72-be9f-53295de398ff">



the content of the Environment file is:
LLVM_PATH="/Users/greg/CLionProjects/LLVM/LLVM-19.1.0"
export LDFLAGS="-L$LLVM_PATH/lib  -Wl,-rpath,$LLVM_PATH/lib  -fuse-ld=lld -stdlib=libc++ -lc++abi -lunwind "
export CPPFLAGS="-I$LLVM_PATH/include -std=c++20 -stdlib=libc++"

a simple hello world program  would just finish with "Process finished with exit code 139 (interrupted by signal 11:SIGSEGV)", nothing else.

if I add LDFLAGS with "-L$LLVM_PATH/lib/c++ -Wl,-rpath,$LLVM_PATH/lib/c++",  execution finished normally.

contents in $LLVM_PATH/lib/c++ is copyed from brew installatioin(libc++ libc++abi ...).

I did similar things with vscode, same result.

I was just trying to setup a custom toolchain, I don't known if I missed anything?

**Comment by lnpg** [comment]
or I could just put those files from brew installation into the $LLVM_PATH/lib directory, replacing these "official" ones,
