### ISSUE TITLE
[SLP vectorizer] Assertion fails with slp-revec

### ISSUE THREAD

**Issue by JonPsson1** [llvm/llvm-project#109835]
[tc_slp_revec.tar.gz](https://github.com/user-attachments/files/17118250/tc_slp_revec.tar.gz)

opt -mtriple=systemz-unknown -mcpu=z16 -O3 -o out.ll tc_crash22_aftercreduce.ll -slp-revec

Type.cpp:691: static llvm::FixedVectorType* llvm::FixedVectorType::get(llvm::Type*, unsigned int): Assertion `isValidElementType(
ElementType) && "Element type of a VectorType must " "be an integer, floating point, or " "pointer type."' failed.

#9 0x000002aa076e014e llvm::slpvectorizer::BoUpSLP::ShuffleCostEstimator::finalize

**Comment by HanKuanChen** [comment]
The fix is landing.

**Comment by HanKuanChen** [comment]
The fix is landing.
