### ISSUE TITLE
[Instcombine] -instcombine-verify-known-bits failure.

### ISSUE THREAD

**Issue by JonPsson1** [llvm/llvm-project#109957]
[tc_instcomb_knownbits.tar.gz](https://github.com/user-attachments/files/17129455/tc_instcomb_knownbits.tar.gz)

opt -mtriple=systemz-unknown -mcpu=z15 -O1 tc_instcomb_knownbits.bc -instcombine-verify-known-bits -o /dev/null

Mismatched known bits for   %rem.i = srem i32 %conv.i, -1 in f
computeKnownBits(): 0000000000000000000000000000000?
SimplifyDemandedBits(): ????????????????????????????????

#8 0x000002aa01d6825c llvm::InstCombinerImpl::SimplifyDemandedInstructionBits

@RKSimon @jf-botto @nikic

**Comment by RKSimon** [comment]
CC @artagnon who is looking at something related on #109121

**Comment by nikic** [comment]
I fixed the immediate problem in https://github.com/llvm/llvm-project/commit/5ef02a3fd4758ae1b9151ac581eebd1109b4daad. 

It would make sense to also use `KnownBits::srem()` here, but I noticed that the implementation (https://github.com/llvm/llvm-project/blob/5ef02a3fd4758ae1b9151ac581eebd1109b4daad/llvm/lib/Support/KnownBits.cpp#L1061) only covers positive power of 2, while demanded bits simplification takes the absolute value (https://github.com/llvm/llvm-project/blob/5ef02a3fd4758ae1b9151ac581eebd1109b4daad/llvm/lib/Transforms/InstCombine/InstCombineSimplifyDemanded.cpp#L864).

**Comment by artagnon** [comment]
> It would make sense to also use `KnownBits::srem()` here, but I noticed that the implementation (
> 
> https://github.com/llvm/llvm-project/blob/5ef02a3fd4758ae1b9151ac581eebd1109b4daad/llvm/lib/Support/KnownBits.cpp#L1061
> ) only covers positive power of 2, while demanded bits simplification takes the absolute value (
> 
> https://github.com/llvm/llvm-project/blob/5ef02a3fd4758ae1b9151ac581eebd1109b4daad/llvm/lib/Transforms/InstCombine/InstCombineSimplifyDemanded.cpp#L864
> ).

I _think_ the abs() doesn't make sense, since srem with a negative RHS is flipped into one with a positive RHS, changing LHS as appropriate. I tried exercising the abs() with different tests, with the same result: the change seems to be an NFC.

**Comment by nikic** [comment]
@artagnon Good point. Do you want to submit a PR to switch that code to KnownBits::srem?

**Comment by artagnon** [comment]
> @artagnon Good point. Do you want to submit a PR to switch that code to KnownBits::srem?

On it. I'm currently working through the reasoning.
