### ISSUE TITLE
llvm19.1.10 reports an error when compiling spec2006's 483.Xalan

### ISSUE THREAD

**Issue by fanwudi7463** [llvm/llvm-project#109966]
483.Xalan of spec2006 can be compiled successfully in both llvm17 and 18 versions, but today when upgrading to llvm19.1.10, an error message appeared while compiling this example。

./xercesc/util/NameIdPool.c:416:20: error: cannot assign to non-static data member 'fMemoryManager' with const-qualified type 'MemoryManager *const'
  416 |     fMemoryManager = toAssign.fMemoryManager;
      |     ~~~~~~~~~~~~~~ ^
./xercesc/util/NameIdPool.hpp:307:26: note: non-static data member 'fMemoryManager' declared const here
  307 |     MemoryManager *const fMemoryManager;
      |     ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
1 error generated.

![20240925200341](https://github.com/user-attachments/assets/44b03e88-0d47-47af-b551-eecddf2db65a)

**Comment by topperc** [comment]
Add -delayed-template-parsing to your command line.

This is a bug in the Xalanc source code that both gcc and clang have started diagnosing this year.

**Comment by shafik** [comment]
> Add -delayed-template-parsing to your command line.
> 
> This is a bug in the Xalanc source code that both gcc and clang have started diagnosing this year.

Do you have a link to the commit?

**Comment by topperc** [comment]
> > Add -delayed-template-parsing to your command line.
> > This is a bug in the Xalanc source code that both gcc and clang have started diagnosing this year.
> 
> Do you have a link to the commit?

Probably https://github.com/llvm/llvm-project/pull/90152

**Comment by topperc** [comment]
gcc bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111544

**Comment by pinskia** [comment]
and GCC bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116064 (which is spec 2017's xalancbmk_r but both source bases in spec 2006 and 2017 have a similar issue) Both are worked around similarly:
GCC: -Wno-error=template-body
clang: -fdelayed-template-parsing

**Comment by fanwudi7463** [comment]
Thanks，the problem has been solved under your suggestion
