### ISSUE TITLE
Assertion "only support multiples of 64-bits" failed while compiling wine

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11013]
|  |  |
| --- | --- |
| Bugzilla Link | [10641](https://llvm.org/bz10641) |
| Version | 2.9 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Yes, this really occurred in the wild (while building wine)!  In the original
code the i160 appears as padding at the end of a struct.

$ cat bigint.ll 
target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:32:32-f128:128:128-n8:16:32"
target triple = "i386-unknown-linux-gnu"

@&#8203;g = global i160 zeroinitializer

$ llc bigint.ll 
llc: llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:1633: void EmitGlobalConstantLargeInt(const llvm::ConstantInt*, unsigned int, llvm::AsmPrinter&): Assertion `(BitWidth & 63) == 0 && "only support multiples of 64-bits"' failed.
...
5  libc.so.6 0x00007ff4859f1cbd __assert_fail + 221
llvm::AsmPrinter::EmitGlobalVariable(llvm::GlobalVariable const*) + 553
8  llc       0x0000000000aa45cf llvm::AsmPrinter::doFinalization(llvm::Module&) + 63
9  llc       0x0000000000e278b4 llvm::FPPassManager::doFinalization(llvm::Module&) + 84
10 llc       0x0000000000e2c369 llvm::FPPassManager::runOnModule(llvm::Module&) + 73
11 llc       0x0000000000e2bfcf llvm::MPPassManager::runOnModule(llvm::Module&) + 527
12 llc       0x0000000000e2ccbb llvm::PassManagerImpl::run(llvm::Module&) + 187
13 llc       0x000000000053ceea main + 3210
14 libc.so.6 0x00007ff4859e430d __libc_start_main + 237
15 llc       0x0000000000537d39
Stack dump:
0.	Program arguments: llc bigint.ll 
1.	Running pass 'Function Pass Manager' on module 'bigint.ll'.
Aborted (core dumped)

**Comment by arsenm** [comment]
Works fine on main
