### ISSUE TITLE
[libc] add `mremap` syscall wrapper

### ISSUE THREAD

**Issue by SchrodingerZhu** [llvm/llvm-project#110119]
We need to create a `mremap` wrapper for linux targets, see https://man7.org/linux/man-pages/man2/mremap.2.html.

This requires:

- implement the entrypoint header similar to `libc/src/sys/mman/mmap.h`
   - modify `libc/src/sys/mman/CMakeLists.txt` accordingly
- implement the entrypoint similar to `libc/src/sys/mman/linux/mmap.cpp`
   - modify `libc/src/sys/mman/linux/CMakeLists.txt` accordingly
- add in the header spec
  - modify `functions` section in `libc/newhdrgen/yaml/sys/mman.yaml`
  - modify `SysMMan` section in `libc/spec/linux.td`
- add in test
  - similar to `libc/test/src/sys/mman/linux/mmap_test.cpp`
  - modify `libc/test/src/sys/mman/linux/CMakeLists.txt` accordingly

-----------------------------------------------------
Misc:
- How to build libc for dev: https://libc.llvm.org/full_host_build.html
- Code style and dev guide: https://libc.llvm.org/dev/index.html

If you use vscode, [sample settings](https://code.visualstudio.com/docs/getstarted/settings#_settings-json-file) are as the following (optional settings are useful in speeding up the compilation):
```
{
    "cmake.sourceDirectory": "${workspaceFolder}/runtimes",
    "cmake.configureSettings": {
        "CMAKE_EXPORT_COMPILE_COMMANDS": true,
        "LLVM_ENABLE_RUNTIMES": [
            "libc",
            "compiler-rt"
        ],
        "LLVM_LIBC_FULL_BUILD": true,
        "LLVM_USE_LINKER": "lld", // optional: requires installing lld
        "CMAKE_CXX_COMPILER_LAUNCHER": "sccache", // optional: requires installing sccache first
        "CMAKE_C_COMPILER_LAUNCHER": "sccache", // optional: requires installing sccache first
        "CMAKE_CXX_COMPILER": "/usr/bin/clang++",
        "CMAKE_C_COMPILER": "/usr/bin/clang",
        "LLVM_LIBC_INCLUDE_SCUDO": true,
        "COMPILER_RT_BUILD_SCUDO_STANDALONE_WITH_LLVM_LIBC": true,
        "COMPILER_RT_BUILD_GWP_ASAN": false,
        "COMPILER_RT_SCUDO_STANDALONE_BUILD_SHARED": false,
        "LIBC_USE_NEW_HEADER_GEN": true
    },
    "cmake.generator": "Ninja", // optional: requires installing Ninja
    "editor.formatOnSave": true,
    "files.insertFinalNewline": true,
    "clangd.arguments": [
        "--header-insertion=never"
    ]
}
```

**Comment by SchrodingerZhu** [comment]
@SoftJing1 wanted to have a try

**Comment by SchrodingerZhu** [comment]
hi @AlyElashram, @SoftJing1 is currently looking into this. I will let you know if anything changed. That is being said, I can open another issue for `remap_file_pages` if you want to have a try. It should be following largely the same instructions as above.

**Comment by WilliamFreedman** [comment]
Looks like nobody's currently assigned, I'd love to take a look at it if that's right.

**Comment by nickdesaulniers** [comment]
@WilliamFreedman we can't assign users who aren't members of the llvm github org.  It sounds like @softjing1 is looking into this?

**Comment by SoftJing1** [comment]
@WilliamFreedman @nickdesaulniers  Yes I am currently working on this, and hopefully will get it done this week.

**Comment by zenmov** [comment]
@SoftJing1 are you still working on this?

**Comment by SoftJing1** [comment]
> @SoftJing1 are you still working on this?

Yes

**Comment by whiteio** [comment]
Hi @SoftJing1 are you still working on this? I'd like to do it if not

**Comment by SchrodingerZhu** [comment]
Ah, sorry. It is my fault. 

The PR is already merged but I forget to close the issue. 

@whiteio thanks for your interest in contributing to LLVM-libc. We do have a lot of other syscall wrappers or libc functions unimplemented but I currently do not have the time to create more good first issues. You are welcome to join the discord to ask whether there are other similar contribution opportunities.
