### ISSUE TITLE
File takes 8s to compiled with clang but only 74ms to compile with gcc

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11023]
|  |  |
| --- | --- |
| Bugzilla Link | [10651](https://llvm.org/bz10651) |
| Version | trunk |
| OS | Linux |
| Attachments | [Preprocessed syscache.c C source file from Postgres source](https://user-images.githubusercontent.com/60944935/143743660-fbbc065d-77b3-44e2-bda2-f4c2dc720dcf.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@DougGregor,@efriedma-quic,@jryans,@tkremenek,@vleschuk,@yuanfang-chen |

## Extended Description 
The build times for Postgres are still slower with clang than gcc. On my machine Postgres builds in about 90s with gcc but takes nearly 4 minutes with clang. There is no longer a single offending file but there are a bunch of files that seem to take 5-8s with clang even though they don't take particularly long with gcc. This is true even with -O0.

This is the current worst offender but there are 17 files that take 10 times as long or more to build with clang as gcc.

These times are after running the two commands repeatedly:

$ time gcc -c syscache-preprocessed.c 

real    0m0.074s
user    0m0.050s
sys     0m0.040s

$ time clang -c syscache-preprocessed.c 

real    0m7.742s
user    0m7.700s
sys     0m0.040s

**Comment by arsenm** [comment]
Compiles in milliseconds for me at all -O levels
