### ISSUE TITLE
SHA2 ASAN interceptors on FreeBSD and NetBSD

### ISSUE THREAD

**Issue by botovq** [llvm/llvm-project#110215]
The SHA2 `*_{Init,Update,Final,Transform}()` functions on FreeBSD ([manual][1]) and NetBSD (cf [manual][2]) collide with functions of the same name [in OpenSSL][3]. The signatures are incompatible (return types and contexts).

This leads to undesirable runtime failures when using `-fsanitize=-address` in combination with `-lcrypto`.

Not all of the below are problematic for both FreeBSD and NetBSD, but should probably be audited in detail and potentially be removed.

https://github.com/llvm/llvm-project/blob/880ee48d5c9d88be1c611451e84f16eafcebd1a6/compiler-rt/lib/sanitizer_common/sanitizer_platform_interceptors.h#L564-L570

See https://github.com/libressl/portable/issues/1098, https://github.com/openssl/openssl/issues/25456, and https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281685 for more details.

Cc: @krytarowski @devnexen

[1]: https://man.freebsd.org/cgi/man.cgi?query=SHA256_Init&apropos=0&sektion=0&manpath=FreeBSD+14.1-RELEASE+and+Ports&arch=default&format=html
[2]: https://man.netbsd.org/SHA256_Init.3
[3]: https://docs.openssl.org/3.0/man3/SHA256_Init/

**Comment by devnexen** [comment]
Will make a PR backport to 19.x later in the day.

**Comment by oschonrock** [comment]
There is an additional manifestation of this here:

https://github.com/curl/curl/issues/15477

In short: In short, compiling a trivial curl program on FreeBSD with ASAN and openssl triggers  openssl error.
