### ISSUE TITLE
[libc++] Are some standard overloads of `std::pow` missing?

### ISSUE THREAD

**Issue by frederick-vs-ja** [llvm/llvm-project#110241]
I'm referring to C++20/[WG21 N4868](https://wg21.link/n4868) here, because the changes of additional overloads of `std::pow` introduced in C++23 by [P1467R9](https://wg21.link/p1467r9) look defective and libc++ hasn't implemented P1467R9 yet.

In [N4868 [complex.syn]](https://timsong-cpp.github.io/cppwp/n4868/complex.syn) there were 3 explicitly specified standard overloads of `pow`:
```C++
  template<class T> complex<T> pow  (const complex<T>&, const T&);
  template<class T> complex<T> pow  (const complex<T>&, const complex<T>&);
  template<class T> complex<T> pow  (const T&, const complex<T>&);
```

And then, several additional overloads were specified in [N4868 [cmplx.over]/3](https://timsong-cpp.github.io/cppwp/n4868/cmplx.over#3), but their exact forms were not specified.

Currently, libc++ provides 4 overloads:
https://github.com/llvm/llvm-project/blob/1c26e2b6f90253efdf38a5a70d011722d4eb1216/libcxx/include/complex#L1095-L1116

If I understood correctly, only the first one is an explicitly specified overload, and the rest are additional overloads. So it seems that the remaining 2 overloads are missing.

However, when I attempted to added them during handling #110235, I found that it's very hard, if not impossible, to portably verify that these overloads are added. Because instantiating `std::complex<NonFP>` is unspecified and in some cases `std::complex<std::complex<T>>` would be instantiated when using braced-init-list due to the form of these overloads.
E.g. according to the current standard overload set, `std::pow(std::complex<float>(1.0f), {1l, 1l})` would cause `pow(const T&, const complex<T>&)` (where `T` is `complex<float>`) to be detected, which in turn instantiates (probably nonsense) `std::complex<std::complex<float>>`.

It's not clear to me
1. whether libc++ is effectively conforming now, i.e. lacking of these 2 overloads isn't observable in any conforming program, and
2. whether there's any defect in the specification of explicitly overloads (effectively unchanged since C++20, see [[complex.syn]](https://eel.is/c++draft/complex.syn)) as they possibly cause `std::complex<std::complex<T>>` to be instantiated.

Edit: [LWG3693](https://cplusplus.github.io/LWG/issue3693) is somehow related.

**Comment by ldionne** [comment]
I think our overloads that use `__promote` might have been an undocumented extension we provided by mistake. I'd be curious to try removing them and replace them by the Standard ones.

I don't think it's possible to observe that we don't provide the overloads exactly as specified in the Standard, because those overloads are only enabled for arithmetic types and `std::complex<T>` can only be instantiated for `T = {float, double, long double}`. However, it might still be worth getting back in line with what the spec says.

**Comment by frederick-vs-ja** [comment]
Closing as there at least _shouldn't_ be observable differences. I remembered that I've submitted [LWG3693](https://cplusplus.github.io/LWG/issue3693) which is somehow related.
