### ISSUE TITLE
Assertion failed: (LHS.isSimple() && "Can only subscript lvalue vectors here!") with ext_vector_type

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#11026]
|  |  |
| --- | --- |
| Bugzilla Link | [10654](https://llvm.org/bz10654) |
| Version | unspecified |
| OS | All |
| CC | @tlattner |

## Extended Description 
Testcase:
__attribute((ext_vector_type(4))) typedef int extv4;
extv4 v; 
void f(int i) { v.xzwy[i] = 10; }

Assertion failed: (LHS.isSimple() && "Can only subscript lvalue vectors here!"), function EmitArraySubscriptExpr, file /Users/efriedma/llvm/tools/clang/lib/CodeGen/CGExpr.cpp, line 1566.

There happens to be a similar construct to this in test/CodeGen/volatile.c, although it's on the right-hand side on an assignment there.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.5: https://cexplorer.testlabs.pro/z/8an3n6
