### ISSUE TITLE
libc++errors in CI

### ISSUE THREAD

**Issue by tschuett** [llvm/llvm-project#110368]
I have libc++ errors in my PR: https://github.com/llvm/llvm-project/pull/110287.
Even after several force pushes, they do not go away. I claim that they are unrelated, but CI is red.

**Comment by frederick-vs-ja** [comment]
I encountered the same error (error: no type named 'type' in 'std::common_type<long double, long double, long>') yesterday.

#107638 (reverted by #110384 recently) may be related. I guess you can retry force-pushing now.
