### ISSUE TITLE
Missing type in constructor argument list gives poor error message

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11031]
|  |  |
| --- | --- |
| Bugzilla Link | [10659](https://llvm.org/bz10659) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
clang r136602 gives uninformative error messages for undeclared types used in constructor arguments.  IWBN if instead of the following it actually said something to the effect of "Unknown type: Bar".

$ clang++ -c t.cc
```
t.cc:2:10: error: expected ')'
  Foo(Bar* b) {}
         ^
t.cc:2:6: note: to match this '('
  Foo(Bar* b) {}
     ^
t.cc:2:15: error: function definition does not declare parameters
  Foo(Bar* b) {}
              ^
2 errors generated.
```
This is t.cc:
```c
struct Foo {
  Foo(Bar* b) {}
};
```

**Comment by philnik777** [comment]
This has been fixed in Clang 3.1.
