### ISSUE TITLE
libcxx compliation issue with clang-cl

### ISSUE THREAD

**Issue by ShuangLiu1992** [llvm/llvm-project#110415]
building with the latest msvc 1914 with clang tools,

configure as shown in the docs 
```
cmake -G Ninja -S runtimes -B build -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DLLVM_ENABLE_RUNTIMES=libcxx
```

getting erros like these
```
E:\projects\llvm-project\build\include\c++\v1\string(2272,1): error: explicit instantiation of 'insert' does not refer to a function template, variable template, member function, member class, or static data member
E:\projects\llvm-project\build\include\c++\v1\__string/extern_template_lists.h(46,85): note: expanded from macro '_LIBCPP_STRING_V1_EXTERN_TEMPLATE_LIST'
   46 |   _Func(_LIBCPP_EXPORTED_FROM_ABI basic_string<_CharType>& basic_string<_CharType>::insert(size_type, value_type const*, size_type)) \
      |                                                                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
35 warnings and 20 errors generated.
```

**Comment by ldionne** [comment]
@mstorsjo Any idea? We do the same thing in our CI setup and it works for us?

**Comment by mstorsjo** [comment]
The setup seems correct in general, and this is indeed what we do test in CI.

> building with the latest msvc 1914 with clang tools,

Sorry, which version of MSVC is this, and more importantly, which version of Clang is that? From looking at https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering, "msvc 1914" looks like "Visual Studio 2017 version 15.7", which is quite old. Do you use a Clang version that shipped along with that as well, or what version of Clang are you using?

**Comment by ShuangLiu1992** [comment]
> The setup seems correct in general, and this is indeed what we do test in CI.
> 
> > building with the latest msvc 1914 with clang tools,
> 
> Sorry, which version of MSVC is this, and more importantly, which version of Clang is that? From looking at https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering, "msvc 1914" looks like "Visual Studio 2017 version 15.7", which is quite old. Do you use a Clang version that shipped along with that as well, or what version of Clang are you using?

When I got the error last time I just installed the latest Visual Studio 2022 update to see if it fixes these errors, so 1914 might be a typo but I might have genuinely used an old version too by mistake. Will check and report back.
