### ISSUE TITLE
RISC-V: enable `-mno-strict-align` when `Zicclsm` is enabled

### ISSUE THREAD

**Issue by newpavlov** [llvm/llvm-project#110454]
Otherwise LLVM generates terrible code for misaligned loads/stores, as can be seen here: https://rust.godbolt.org/z/ax1bqeeKx

The [RISC-V Profiles specification](https://github.com/riscv/riscv-profiles/releases/download/v1.0/profiles.pdf) states the following
>Even though mandated, misaligned loads and stores might execute extremely slowly. Standard software distributions should assume their existence only for correctness, not for performance.

This footnote is not present in the RVA23 spec, but it's unclear whether it got deprecated or implicitly inherited from the profiles spec.

In practice, we probably can expect that most hardware which declares `Zicclsm` support will have "fast" misaligned support implemented in hardware.

As another data point, it looks like Linux also considers that enabled `Zicclsm` means "fast" misaligned operations. From [this patch](https://lwn.net/ml/all/20240613191616.2101821-1-jesse@rivosinc.com/):
>If Zicclsm is present, the kernel will set both scalar and vector unaligned access speed to FAST.

**Comment by dtcxzyw** [comment]
See https://github.com/llvm/llvm-project/pull/108551.

**Comment by newpavlov** [comment]
@dtcxzyw 
I explicitly discussed the spec footnote. Arguably, we should ignore it and blame hardware which declares `Zicclsm` support, but relies on emulated misaligned operations. It looks like hardware which targets the RVA profiles overwhelmingly supports native misaligned operations. Otherwise, codegen for misaligned operations will be extremely terrible for everyone.

Either way, it would be nice to get an explicit clarification from the RISC-V folks.

**Comment by topperc** [comment]
I worry that many hardware vendors are going to want to claim to be RVA23 compliant, but rely on trap and emulate of unaligned accesses.

**Comment by topperc** [comment]
> It looks like hardware which targets the RVA profiles overwhelmingly supports native misaligned operations.

Can you provide public documentation that demonstrates that this is "overwhelming"?

**Comment by newpavlov** [comment]
Citing this [message](https://www.reddit.com/r/RISCV/comments/1frrai9/opinionrant_riscv_prioritizes_hardware_developers/lplgkh6/):
>As my own testing shows (see link below), the C906, C910, SpacemiT X60 all support fast misaligned accesses. The only common SoC that doesn't is the JH7110 (U74 core), and near future SiFive cores (P550, P670) are known to have hardware misaligned access handling.

**Comment by cyyself** [comment]
> Wouldn't this hypothetical hardware clash with how Linux interprets `Zicclsm`, thus making them non-compliant in practice?

Actually, the scalar misaligned load/store has been handled by OpenSBI since v0.1 6 years ago.

**Comment by topperc** [comment]
-mno-strict-align includes misaligned vector which is known to crash on the Spacemit X60

**Comment by newpavlov** [comment]
@cyyself 
I am no sure how it's relevant to the current discussion. IIUC Linux assumes that `Zicclsm` means "fast" misaligned operations, breaking this assumption would make such hardware "non-compliant" with how Linux interprets the spec.

**Comment by newpavlov** [comment]
@topperc 
Spacemit X60 does not claim support of an RVA profile, no? Thus `Zicclsm` will not be enabled for it.

**Comment by topperc** [comment]
> @topperc Spacemit X60 does not claim support of an RVA profile, no? Thus `Zicclsm` will not be enabled for it.

RVA23 isn't ratified so I'm not sure anyone would claim support for it yet.

**Comment by newpavlov** [comment]
>RVA23 isn't ratified so I'm not sure anyone would claim support for it yet.

But RVA20 and RVA2 are ratified and list `Zicclsm` as a mandatory extension.

**Comment by topperc** [comment]
Did that patch make it into the Linux kernel? I can't find Zicclsm or RISCV_ISA_EXT_ZICCLSM searching the kernel source.

**Comment by newpavlov** [comment]
>Did that patch make it into the Linux kernel?

Hm, it does not look like it did yet. It was created less than 3 months ago, so maybe not enough time has passed yet? I don't see any objections about `Zicclsm` handling in the [patch discussion](https://lwn.net/ml/all/20240613191616.2101821-1-jesse@rivosinc.com/).

**Comment by topperc** [comment]
> >Did that patch make it into the Linux kernel?
> 
> 
> 
> Hm, it does not look like it did yet. It was created less than 4 months ago, so maybe not enough time has passed? I don't see any objections about `Zicclsm` handling in the [patch discussion](https://lwn.net/ml/all/20240613191616.2101821-1-jesse@rivosinc.com/).

There's a discussion here that resolved to abandoning it. https://lore.kernel.org/lkml/43941f48-9905-4b25-89ef-6ad75bf1a123@rivosinc.com/

**Comment by dtcxzyw** [comment]
> > Did that patch make it into the Linux kernel?
> 
> Hm, it does not look like it did yet. It was created less than 4 months ago, so maybe not enough time has passed? I don't see any objections about `Zicclsm` handling in the [patch discussion](https://lwn.net/ml/all/20240613191616.2101821-1-jesse@rivosinc.com/).


See also https://patchew.org/linux/20240625005001.37901-1-jesse@rivosinc.com/20240625005001.37901-2-jesse@rivosinc.com/

> Note:
> This introduces a new extension name for this feature.
> This requires misaligned support for all regular load and store
> instructions (including scalar and vector) but not AMOs or other
> specialized forms of memory access. Even though mandated, misaligned
> loads and stores might execute extremely slowly. Standard software
> distributions should assume their existence only for correctness,
> not for performance.

**Comment by cyyself** [comment]
@newpavlov 

> IIUC Linux assumes that Zicclsm means "fast" misaligned operations, breaking this assumption would make such hardware "non-compliant" with how Linux interprets the spec.

This is not true. Linux master branch has no code checked zicclsm (at least v6.12-rc1 today). I have also checked mailing list and found [a series](https://lore.kernel.org/linux-riscv/20240717180727.4180475-1-jesse@rivosinc.com/) has no change to misaligned speed probe when zicclsm exist.

And even hardware didn't handle misaligned load/store. From the S-Mode Linux perspective, we can also allow "Zicclsm" to appear in the ISA string of the device tree / ACPI table to tell the kernel it's safe to do misaligned load/store. Such as Zicntr and Zihpm did before.

So, I think assuming misaligned access is fast when Zicclsm exists in the ISA string is not right.

**Comment by newpavlov** [comment]
@topperc
It looks you are right.

Sigh... I totally agree with this [message](https://lore.kernel.org/lkml/ZoR9swwgsGuGbsTG@ghost/):
>This extension does not seem useful as it is written!

I am going to close this issue since apparently we can not do anything with the existing spec and we have to live with the extremely terrible codegen. I guess I will just blame RISC-V authors for this utter mess.

**Comment by newpavlov** [comment]
I still think that it may be reasonable to ignore the footnote. After all, generated code will be "correct" and in practice more often than not misaligned operations will work with aligned pointers. And we can just blame hardware which relies on emulation for any potential slowness, thus discouraging hardware developers from taking this route. But I understand why LLVM would prefer to not use this approach.

**Comment by newpavlov** [comment]
Relevant issue: https://github.com/riscv/riscv-profiles/issues/187
