### ISSUE TITLE
Clang 19.1.0 Windows release binary fails when targeting MIPS

### ISSUE THREAD

**Issue by Mr-Wiseguy** [llvm/llvm-project#110536]
As of the latest release (https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.0), the Windows clang binary is unable to compile when targeting MIPS. The cc1 pass is reporting that some flags are invalid, such as `-mips-ssection-threshold=0` and `-mgpopt`, both of which are being inserted by the driver by translating the provided compilation flags (`-G0` and `-mno-abicalls` respectively). If I remove all compiler flags besides `-target mips -O2 -mips2 -mabi=32` the compiler will fail with `'No available targets are compatible with triple "mips"'`.

The 18.1.8 release binary does not have these issues.

**Comment by zufuliu** [comment]
See https://discourse.llvm.org/t/llvm-19-1-0-rc3-tagged/80803/7, in order to fix NSSS installer 2GB limit, only AArch64, ARM and X86 targets were included, you can use [LLVM-19.1.0-Windows-X64.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.0/LLVM-19.1.0-Windows-X64.tar.xz) that contains everything.

**Comment by Mr-Wiseguy** [comment]
Thanks, switching to that distribution fixed it. I'll close this issue, though I do think it might be a good idea to rename the release asset that contains all architectures so that it's clear what the difference is.

**Comment by bspeice** [comment]
Update - it seems LLVM is not uploading the `.tar.xz` archives at the moment for releases 19.1.4 and onwards. Haven't seen any updates on the forum: https://discourse.llvm.org/t/llvm-19-x-release-third-party-binaries/80374/53

I'm hitting issues related to the validator; shimgen takes too long to run, and the builds ultimately time out. I think the existing `llvm.portable` will be unfortunately stuck in time for a bit.
