### ISSUE TITLE
Emit a diagnostic note at the class declaration when the method definition does not match any declaration.

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#110558]
Considering the follow case:

```
template <class T>
class FooBar {
  double Foo();
};

template <class T>
double FooBar<T>::Bar() { return 0.0; }
```

Currently, Clang only emits the error out-of-line definition of 'Bar' does not match any declaration at the Bar definition. It would be helpful to also emit a note pointing to the FooBar class declaration (GCC already does this).

See https://godbolt.org/z/GG8zvvzaP

**Comment by shafik** [comment]
@hokein since you labelled this a good first issue, it may be helpful to point out the diagnostic id and where the diagnostic is being emitted to help someone new get started.
