### ISSUE TITLE
[clang] discrepancy between different version of constexpr bit_cast

### ISSUE THREAD

**Issue by JeWaVe** [llvm/llvm-project#110530]
Using trunk (or tag 19.1), this code compiles fine and runs as expected : 

```
static constexpr int bit_cast_float_to_int(float value) {
    union {
        float f;
        int i;
    } u;
    u.f = value;
    return u.i;
}

int main() {
    return bit_cast_float_to_int(1.0F);
}
```

yielding : 

```
main:
  movl $1065353216, %eax
  retq
```

while this one

```

static constexpr int bit_cast_float_to_int(float value) {
    union {
        float f;
        int i;
    } u;
    u.f = value;
    return u.i;
}

constexpr int zou = bit_cast_float_to_int(1.0F);

int main() {
    return zou;
}
```

does not because of errors : 

```
<source>:11:15: error: constexpr variable 'zou' must be initialized by a constant expression
   11 | constexpr int zou = bit_cast_float_to_int(1.0F);
      |               ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:8:12: note: read of member 'i' of union with active member 'f' is not allowed in a constant expression
    8 |     return u.i;
      |            ^
<source>:11:21: note: in call to 'bit_cast_float_to_int(1.000000e+00)'
   11 | constexpr int zou = bit_cast_float_to_int(1.0F);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Compiler returned: 1
```

Link to godbolt : https://godbolt.org/z/xPWh7nMPs
options : -std=c++20

**Comment by tbaederr** [comment]
That is expected because what you're doing is UB and has to be diagnosed if the constexpr function is evaluated at compile time, which it only is in the second example. If you make the function `consteval` instead, both instances are diagnosed: https://godbolt.org/z/r4cT3onhh

**Comment by zygoloid** [comment]
You can use `std::bit_cast<int>(value)` instead to perform this cast with defined behavior, and at compile time. (If you are using an old standard library or an old C++ standard version, you can access the compiler builtin directly with `__builtin_bit_cast(int, value)`, but this isn't recommended.)

**Comment by JeWaVe** [comment]
Agreed with all of that, but then why UB is not warned somehow ?
