### ISSUE TITLE
[META] Compiling Wine with dragonegg

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11054]
|  |  |
| --- | --- |
| Bugzilla Link | [10682](https://llvm.org/bz10682) |
| Version | trunk |
| OS | Linux |
| Depends On | llvm/llvm-project#11011 llvm/llvm-project#11012 llvm/llvm-project#11051 llvm/llvm-project#11052 llvm/llvm-project#11053 llvm/llvm-project#10074 llvm/llvm-bugzilla-archive#10707 llvm/llvm-bugzilla-archive#10713 llvm/llvm-bugzilla-archive#11173  |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
This is a meta-bug for issues compiling wine with Dragonegg (for issues Wine/Clang, see bug 10638).

Inspired by bug 4068, bug 6815, and bug 7207.

**Comment by asl** [comment]
Dragonegg is obsolete

**Comment by asl** [comment]
Dragonegg is obsolete
