### ISSUE TITLE
[Flang] [AIX] Incorrect `sqrt` folding on AIX.

### ISSUE THREAD

**Issue by DanielCChen** [llvm/llvm-project#110682]
Consider the following code:
```
complex :: cv = sqrt((-2.0,0.0))
END
```

On AIX, it generates 
```
    %cst = arith.constant -6.18172393E-8 : f32
    %cst_0 = arith.constant 1.41421354 : f32
```

On LoP, it generates
```
    %cst = arith.constant 0.000000e+00 : f32
    %cst_0 = arith.constant 1.41421354 : f32
```

**Comment by klausler** [comment]
That's a complex square root, and those are folded using the local math library to which the compiler has been linked.

**Comment by DanielCChen** [comment]
> That's a complex square root, and those are folded using the local math library to which the compiler has been linked.

I see. Thanks for the pointer.

**Comment by kkwli** [comment]
It is desirable to make the folding result and the runtime result the same. On AIX, the `cacos` and `csqrt` give different output.
```fortran
  complex :: c1, r1, r2
  complex, parameter :: c2 = (-2.0, 0.0)
  r1 = csqrt((-2.0, 0.0))
  c1 = (-2.0, 0.0)
  r2 = csqrt(c1)
  print *, r1
  print *, r2
end
```
Output:
```
 (-6.181724E-08,1.4142135)
 (0.,1.4142135)
```

**Comment by kkwli** [comment]
Fixed in https://github.com/llvm/llvm-project/pull/114106
