### ISSUE TITLE
[DirectX] Confirm that our translation of a resource's undef global variable's type emits valid DXIL

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#110703]
In DXIL, the resource metadata includes a ["Pointer to a global constant symbol with the original shape of resource and element type."](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#metadata-resource-records). In non-library shaders, this is an undef value of a type based on the resource's template parameter, like so:

```llvm
%"class.RWBuffer<float4>" = type { <4 x float> }
!... = !{i32 0, %"class.RWBuffer<float>"* undef, !"", i32 0, i32 0, i32 1, i32 10, i1 false, i1 false, i1 false, !7}
````

Currently in DXILResourceAnalysis, we simply emit an undef value of an opaque pointer type here. We need to make sure that when this is emitted to DXIL the type we emit for the pointer doesn't break consumers and the validator. The type does not necessarily need to be recovered correctly for this, and something like `i8*` might be fine since most consumers don't actually read this.

If a bogus type isn't sufficient, then we'll need to smuggle the type through to the DXIL bitcode writer - see #75981

**Comment by tex3d** [comment]
I confirmed that replacing a StructuredBuffer type with `type { i8* }` validates and runs on at least some implementations with no issue.
