### ISSUE TITLE
[HLSL] Function mangling for output parameters not working

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#110710]
There are a couple bugs related to mangling of output parameters. The Itanium ABI isn't including parameter mangling as expected, and the parameter types are not correctly mutated to references for template functions.

This test demonstrates both bugs: https://godbolt.org/z/oj1hEfjMv

**Comment by damyanp** [comment]
Now we've switched to the Itanium ABI this is moot.
