### ISSUE TITLE
Assertion `CapturedVar->isInitCapture()' failed

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#110721]
Recent clang says:

clang++: /home/dcb40b/llvm/trunk/clang/lib/Sema/SemaConcept.cpp:719: clang::Sema::addInstantiatedCapturesToScope(clang::FunctionDecl*, const clang::FunctionDecl*, clang::LocalInstantiationScope&, const clang::MultiLevelTemplateArgumentList&)::<lambda(const clang::ValueDecl*, unsigned int)>: Assertion `CapturedVar->isInitCapture()' failed.

[connectionencryptiondata_p-e2be0f.sh.gz](https://github.com/user-attachments/files/17214449/connectionencryptiondata_p-e2be0f.sh.gz)
[connectionencryptiondata_p-e2be0f.cpp.gz](https://github.com/user-attachments/files/17214453/connectionencryptiondata_p-e2be0f.cpp.gz)

**Comment by shafik** [comment]
Looks like a regression on trunk: https://godbolt.org/z/h9frKK74Y

**Comment by dcb314** [comment]
Seems to go wrong sometime before or on date 2024-09-03.
Git hash 4d8903bd4e6ec29ab28be0d8949c7fde4a740fbe.
