### ISSUE TITLE
[llvm-libc] support for 96b long double (i386)

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#110894]
building llvm-libc for i386 fails to build in the printf code; it seems that `sizeof(long double)` on i386 is `12`.  example:
```
In file included from /android0/llvm-project/libc/src/stdio/printf_core/converter.cpp:9:
In file included from /android0/llvm-project/libc/src/stdio/printf_core/converter.h:13:
In file included from /android0/llvm-project/libc/src/stdio/printf_core/core_structs.h:16:
/android0/llvm-project/libc/src/__support/FPUtil/FPBits.h:824:52: error: no matching function for call to 'bit_cast'
  824 |   LIBC_INLINE constexpr T get_val() const { return cpp::bit_cast<T>(UP::bits); }
      |                                                    ^~~~~~~~~~~~~~~~
/android0/llvm-project/libc/src/stdio/printf_core/float_dec_converter.h:502:47: note: in instantiation of member function '__llvm_libc_19_0_0_git::fputil::FPBits<long double>::get_val' requested here
  502 |   FloatToString<T> float_converter(float_bits.get_val());
      |                                               ^
/android0/llvm-project/libc/src/stdio/printf_core/float_dec_converter.h:1116:14: note: in instantiation of function template specialization '__llvm_libc_19_0_0_git::printf_core::convert_float_decimal_typed<long double, 0>' requested here
 1116 |       return convert_float_decimal_typed<long double>(writer, to_conv,
      |              ^
/android0/llvm-project/libc/src/__support/CPP/bit.h:38:1: note: candidate template ignored: substitution failure [with To = long double, From = StorageType]: implicit instantiation of undefined template '__llvm_libc_19_0_0_git::cpp::enable_if<false, long double>'
   38 | bit_cast(const From &from) {
      | ^
/android0/llvm-project/libc/src/__support/big_int.h:1099:1: note: candidate template ignored: substitution failure [with To = long double, From = StorageType]: implicit instantiation of undefined template '__llvm_libc_19_0_0_git::cpp::enable_if<false, long double>'
 1099 | bit_cast(const From &from) {
      | ^
/android0/llvm-project/libc/src/__support/big_int.h:1114:1: note: candidate template ignored: substitution failure [with To = long double, Bits = 128]: implicit instantiation of undefined template '__llvm_libc_19_0_0_git::cpp::enable_if<false, long double>'
 1114 | bit_cast(const UInt<Bits> &from) {
      | ^
```

perhaps the `StorageType` for `FPLayout<FPType::X86_Binary80>` should be a 96b `UInt` for i386, but that leads to other errors?

Filing a bug to track this, as it's a blocker for i386 support.

cc @michaelrj-google

**Comment by lntue** [comment]
We will need to explicitly specialize:
```
template <> struct WordTypeSelector<96> : cpp::type_identity<uint32_t> {};
```
https://github.com/llvm/llvm-project/blob/main/libc/src/__support/big_int.h#L983
and i386 should be able to use `LIBC_NAMESPACE::UInt<96>` as storage type for long double.

**Comment by gchatelet** [comment]
@nickdesaulniers I'm still blocked on the syscall issues when trying to compile for i386 (i.e., `CMAKE_C_FLAGS=-m32` and `CMAKE_CXX_FLAGS=-m32`). Can you give me a repro for the above error?

**Comment by nickdesaulniers** [comment]
I've pushed a WIP branch: https://github.com/nickdesaulniers/llvm-project/commits/i386/. The syscall implementation, and most changes aren't yet correct (I need to be able to compile for i386 to verify some of these changes) but eliminate the low hanging fruit blocking compilation.

**Comment by nickdesaulniers** [comment]
> i386 should be able to use LIBC_NAMESPACE::UInt<96> as storage type for long double.

Should that be:

```c++
using StorageType = BigInt<__SIZEOF_LONG_DOUBLE__ * CHAR_BIT, false, uint32_t>;`
```

**Comment by lntue** [comment]
Once `struct WordTypeSelector<96>` is overloaded, we can just use
```
using StorageType = BigInt<__SIZEOF_LONG_DOUBLE__ * CHAR_BIT, false>;`
```
in general then?  Let the default `WordTypeSelector` choose the underlying type (mainly for 128-bit cases).

**Comment by nickdesaulniers** [comment]
https://gist.github.com/nickdesaulniers/3c9892af61273db863fc08626ac69c75

(ah looks like `jmp_buf` needs a definition for i386 as well)

some of the resulting errors from:
- libc/src/__support/FPUtil/FPBits.h
- libc/src/__support/CPP/type_traits/is_unsigned.h
- libc/src/__support/big_int.h
I don't really understand.  We [do have the binary operators defined for BigInt](https://github.com/llvm/llvm-project/blob/main/libc/src/__support/big_int.h#L771-L780).

**Comment by lntue** [comment]
> Once `struct WordTypeSelector<96>` is overloaded, we can just use
> 
> ```
> using StorageType = BigInt<__SIZEOF_LONG_DOUBLE__ * CHAR_BIT, false>;`
> ```
> 
> in general then? Let the default `WordTypeSelector` choose the underlying type (mainly for 128-bit cases).

Probably the correct one is:
```
using StorageType = UInt<__SIZEOF_LONG_DOUBLE__ * CHAR_BIT>;
```

**Comment by gchatelet** [comment]
So ultimately it has to do with how `eisel_lemire` is implemented. Currently it assumes that long double `StorageType` is 64 or 128 bits. @michaelrj-google can you give it a try?

**Comment by michaelrj-google** [comment]
I'm happy to take a look, what cmake command are you using to build for i386?

**Comment by gchatelet** [comment]
I've been using the following cmd lines
```
> git checkout nickdesaulniers/i386
> cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_COMPILER="/usr/bin/clang++" -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_C_COMPILER="/usr/bin/clang" -DCMAKE_C_FLAGS="-m32" -DLLVM_ENABLE_PROJECTS="libc" -S/path/to/home/git/llvm-project/llvm -B/path/to/home/build/libc_x86 -GNinja
> ninja -C /path/to/home/build/libc_x86 libc.src.stdlib.atof
```

**Comment by nickdesaulniers** [comment]
I'm just setting `-DLIBC_TARGET_TRIPLE=i386-linux-gnu`

**Comment by nickdesaulniers** [comment]
Thanks @michaelrj-google for those patches!  The next issue I run into is that the `StorageType` for `FPLayout<FPType::X86_Binary80>` currently is `UInt128`, but I suspect it should be a `UInt96` (or rather `UInt<__SIZEOF_LONG_DOUBLE__* CHAR_BIT>`) (for `long double` on i386).  This seems to blow up in `eisel_lemire` (str_to_float.h) for `!defined(LIBC_TYPES_LONG_DOUBLE_IS_FLOAT64)`.  The intermediary calculations are done on `UInt128`, but the mantissa is the storage type of `UInt<96>`.  That causes comparisons using binary operators to fail.  Should we be able to compare via bin ops two different kinds of BigInts, or should the intermediaries values in `eisel_lemire` be changed?

`ninja libc.src.stdio.scanf_core.converter` is a good target to build that exposes this.
