### ISSUE TITLE
Configuring without "--build" creates a host tblgen that is used during the build

### ISSUE THREAD

**Issue by rubenvb** [llvm/llvm-project#11088]
|  |  |
| --- | --- |
| Bugzilla Link | [10716](https://llvm.org/bz10716) |
| Version | trunk |
| OS | Linux |
| Attachments | [config.log without --build argument](https://user-images.githubusercontent.com/92601424/143743702-bda578a8-f036-474b-97b7-80c287932bda.gz) |

## Extended Description 

OS: Fedora 15
GCC: 4.6

When I configure with:

/home/ruben/mingw-w64/toolchain/src/LLVM/configure --host=x86_64-w64-mingw32 --build=x86_64-redhat-linux --target=x86_64-w64-mingw32 --with-sysroot=/home/ruben/mingw-w64/toolchain/mingw64mingw64/mingw64 --prefix=/home/ruben/mingw-w64/toolchain/mingw64mingw64/mingw64-clang --enable-optimized --disable-assertions --disable-pthreads CFLAGS= LDFLAGS=

Everything is fine, if I configure with:

/home/ruben/mingw-w64/toolchain/src/LLVM/configure --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-sysroot=/home/ruben/mingw-w64/toolchain/mingw64mingw64/mingw64 --prefix=/home/ruben/mingw-w64/toolchain/mingw64mingw64/mingw64-clang --enable-optimized --disable-assertions --disable-pthreads CFLAGS= LDFLAGS=

tblgen is built for the host, and used as if it were native:

llvm[2]: Linking Release executable tblgen (without symbols)
llvm[2]: ======= Finished Linking Release Executable tblgen (without symbols)
make[2]: Leaving directory `/home/ruben/mingw-w64/toolchain/mingw64mingw64/llvm-clang/utils/TableGen'
make[1]: Leaving directory `/home/ruben/mingw-w64/toolchain/mingw64mingw64/llvm-clang/utils'
make[1]: Entering directory `/home/ruben/mingw-w64/toolchain/mingw64mingw64/llvm-clang/lib/VMCore'
llvm[1]: Building Intrinsics.gen.tmp from Intrinsics.td
err:module:import_dll Library libgcc_s_sjlj-1.dll (which is needed by L"Z:\\home\\ruben\\mingw-w64\\toolchain\\mingw64mingw64\\llvm-clang\\Release\\bin\\tblgen.exe") not found
err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\ruben\\mingw-w64\\toolchain\\mingw64mingw64\\llvm-clang\\Release\\bin\\tblgen.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"Z:\\home\\ruben\\mingw-w64\\toolchain\\mingw64mingw64\\llvm-clang\\Release\\bin\\tblgen.exe" failed, status c0000135
make[1]: *** [/home/ruben/mingw-w64/toolchain/mingw64mingw64/llvm-clang/lib/VMCore/Release/Intrinsics.gen.tmp] Error 53
make[1]: Leaving directory `/home/ruben/mingw-w64/toolchain/mingw64mingw64/llvm-clang/lib/VMCore'
make: *** [all] Error 1

This is mostly my Linux binfmt stuff trying to run a Win32 app through WINE, which is not what should happen. tblgen should be either only built for the detected BUILD platform, or built for both BUILD and HOST platforms, so it can be used during the build and after install. Attached is a config.log that produces the wrong platform tblgen.

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
