### ISSUE TITLE
[Compiler-rt] Missing include in ubsan_interface.h

### ISSUE THREAD

**Issue by gbMattN** [llvm/llvm-project#110823]
ubsan_interface.h uses the macro SANITIZER_CDECL. This is defined in sanitizer/common_interface_defs.h, but that file is not included. This means that any user code wanting to use the ubsan interface would need to modify ubsan_interface.h to include the sanitizer/common_interface_defs.h, or to include it in their code.

**Comment by fmayer** [comment]
Fixed by @gbMattN in https://github.com/llvm/llvm-project/commit/75103aae4a9d22e2c46068f2160f2dddd6ad2116. Thanks
