### ISSUE TITLE
clang-format: Incorrectly formats multiplication as if it was pointer dereference

### ISSUE THREAD

**Issue by griffin2000** [llvm/llvm-project#110879]
In the attached example ([test.cpp.txt](https://github.com/user-attachments/files/17232763/test.cpp.txt), renamed to .txt so it can be attached) using the attached .clang-format settings ([clang-format.txt](https://github.com/user-attachments/files/17232766/clang-format.txt), also renamed to .txt and . prefix removed), the second line of the struct is formatted by clang-format (v 14.0.0) as if it was a pointer de-reference, and the space following the `*` is removed.  

So this...
```

constexpr Thingy kConfig = {
    {
        (uint16_t)(kScale * kThing.width_pixels),
        (uint16_t)(kScale * kThing.height_pixels),
    },
};
```

Becomes:
```
constexpr Thingy kConfig = {
    {
        (uint16_t)(kScale * kThing.width_pixels),
        (uint16_t)(kScale *kThing.height_pixels),
    },
};
```

The expected behaviour is the space should be maintained, or added if it it is removed (if either the space before or after the `*` is removed on the previous line, it will be added back by clang-format)

**Comment by EugeneZelenko** [comment]
Could you please try 19 or `main` branch?

**Comment by griffin2000** [comment]
Wow! Quick turnaround.  Thanks @owenca
