### ISSUE TITLE
 [AVX2] `bitcast i64 to <64 x i1>` + `sext <64 x i1> to <64 x i8>` should not use `vpermq 0b01_00_01_00` when `vpbroadcastq` would work too

### ISSUE THREAD

**Issue by Validark** [llvm/llvm-project#110868]
[LLVM Godbolt](https://llvm.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:llvm,selection:(endColumn:1,endLineNumber:7,positionColumn:1,positionLineNumber:7,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:'define+dso_local+range(i8+-1,+1)+%3C64+x+i8%3E+@unmovemask64_auto(i64+%250)+local_unnamed_addr+%7B%0AEntry:%0A++%251+%3D+bitcast+i64+%250+to+%3C64+x+i1%3E%0A++%252+%3D+sext+%3C64+x+i1%3E+%251+to+%3C64+x+i8%3E%0A++ret+%3C64+x+i8%3E+%252%0A%7D%0A'),l:'5',n:'1',o:'LLVM+IR+source+%231',t:'0')),k:49.75646879756469,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:irclangtrunk,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:llvm,libs:!(),options:'-O3+-march%3Dznver3',overrides:!(),selection:(endColumn:12,endLineNumber:87,positionColumn:12,positionLineNumber:87,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+clang+(trunk)+(Editor+%231)',t:'0')),k:50.24353120243532,l:'4',m:100,n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)
[Zig Godbolt](https://zig.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:13,fontUsePx:'0',j:3,lang:zig,selection:(endColumn:1,endLineNumber:10,positionColumn:1,positionLineNumber:10,selectionStartColumn:1,selectionStartLineNumber:10,startColumn:1,startLineNumber:10),source:'const+std+%3D+@import(%22std%22)%3B%0A%0Aexport+fn+unmovemask64_auto(x:+u64)+@Vector(64,+u8)+%7B%0A++++return+@select(u8,%0A++++++++@as(@Vector(64,+bool),+@bitCast(x)),%0A++++++++@as(@Vector(64,+u8),+@splat(0xff)),%0A++++++++@as(@Vector(64,+u8),+@splat(0))%0A++++)%3B%0A%7D%0A%0Aexport+fn+unmovemask64(x:+u64)+@Vector(64,+u8)+%7B%0A++++const+bit_positions+%3D+comptime+std.simd.repeat(64,+@as(@Vector(8,+u8),+@splat(1))+%3C%3C+std.simd.iota(u3,+8))%3B%0A++++return+@select(u8,%0A++++++++bit_positions+%3D%3D+(bit_positions+%26+@shuffle(u8,+@as(@Vector(64,+u8),+@bitCast(@as(@Vector(8,+u64),+@splat(x)))),+undefined,+(std.simd.iota(u8,+64)+%3E%3E+@splat(4)+%3C%3C+@splat(4))+%2B+(std.simd.iota(u8,+64)+%3E%3E+@splat(3)))),%0A++++++++@as(@Vector(64,+u8),+@splat(0xff)),%0A++++++++@as(@Vector(64,+u8),+@splat(0))%0A++++)%3B%0A%7D'),l:'5',n:'1',o:'Zig+source+%233',t:'0')),header:(),k:56.563878859314066,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:ztrunk,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:zig,libs:!(),options:'-O+ReleaseFast+-target+x86_64-linux+-mcpu%3Dznver3',overrides:!(),selection:(endColumn:12,endLineNumber:173,positionColumn:12,positionLineNumber:173,selectionStartColumn:12,selectionStartLineNumber:173,startColumn:12,startLineNumber:173),source:3),l:'5',n:'0',o:'+zig+trunk+(Editor+%233)',t:'0')),header:(),k:43.43612114068593,l:'4',m:100,n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

```llvm
define dso_local range(i8 -1, 1) <64 x i8> @unmovemask64(i64 %0) local_unnamed_addr {
Entry:
  %1 = bitcast i64 %0 to <64 x i1>
  %2 = sext <64 x i1> %1 to <64 x i8>
  ret <64 x i8> %2
}
```

Emit for Zen 3:

```diff
.LCPI0_0:
        .byte   0
        .byte   0
        .byte   0
        .byte   0
        .byte   0
        .byte   0
        .byte   0
        .byte   0
        .byte   1
        .byte   1
        .byte   1
        .byte   1
        .byte   1
        .byte   1
        .byte   1
        .byte   1
        .byte   2
        .byte   2
        .byte   2
        .byte   2
        .byte   2
        .byte   2
        .byte   2
        .byte   2
        .byte   3
        .byte   3
        .byte   3
        .byte   3
        .byte   3
        .byte   3
        .byte   3
        .byte   3
.LCPI0_2:
        .byte   4
        .byte   4
        .byte   4
        .byte   4
        .byte   4
        .byte   4
        .byte   4
        .byte   4
        .byte   5
        .byte   5
        .byte   5
        .byte   5
        .byte   5
        .byte   5
        .byte   5
        .byte   5
        .byte   6
        .byte   6
        .byte   6
        .byte   6
        .byte   6
        .byte   6
        .byte   6
        .byte   6
        .byte   7
        .byte   7
        .byte   7
        .byte   7
        .byte   7
        .byte   7
        .byte   7
        .byte   7
.LCPI0_1:
        .byte   1
        .byte   2
        .byte   4
        .byte   8
        .byte   16
        .byte   32
        .byte   64
        .byte   128
unmovemask64:
        vmovq   xmm0, rdi
        vpbroadcastq    ymm2, qword ptr [rip + .LCPI0_1]
-       vpermq  ymm1, ymm0, 68 ; 0b01_00_01_00
+       vpbroadcastq    ymm1, xmm0
        vpshufb ymm0, ymm1, ymmword ptr [rip + .LCPI0_0]
        vpshufb ymm1, ymm1, ymmword ptr [rip + .LCPI0_2]
        vpand   ymm0, ymm0, ymm2
        vpand   ymm1, ymm1, ymm2
        vpcmpeqb        ymm0, ymm0, ymm2
        vpcmpeqb        ymm1, ymm1, ymm2
        ret
```

**Comment by RKSimon** [comment]
Fixed by 19f657d55d679cc3949e9e4c1a5bf76cc4c031b1
