### ISSUE TITLE
[clang-format] Unnecessary extra spaces around template brackets

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#110968]
When bumping from clang-format 18.1.8 to 19.1.1 we notice this change in formatting:

```
$ cat test.cpp
auto x = std::conditional_t<T::value == U::value, T, U>{};
```

```
$ clang-format-19 test.cpp
auto x = std::conditional_t < T::value == U::value, T, U > {};
```

Notice the extra spaces around the `<` and `>`. This happens with default configuration (no `.clang-format` file). This is also happening in `main`:
https://godbolt.org/z/9nv3js7qe

**Comment by carlosgalvezp** [comment]
Thanks for quick the fix @owenca ! Is there any chance to cherrypick it into the 19.x branch?

**Comment by carlosgalvezp** [comment]
@owenca I see it failed to cherry-pick, was this handled elsewhere?

**Comment by owenca** [comment]
This will succeed after #111245 lands.

**Comment by carlosgalvezp** [comment]
Awesome, thanks!
