### ISSUE TITLE
#80527 introduces behavior change that breaks icecream's icecc-create-env script

### ISSUE THREAD

**Issue by 13steinj** [llvm/llvm-project#110958]
Script and some relevant lines for reference: https://github.com/icecc/icecream/blob/d680e4fcb261d7de271ddce331f4a23adbfd573f/client/icecc-create-env.in#L313-L316

#80527 (more accurately combined with the minor commit 0f76d9fb5fbfea92da7647af70d78165c71c0700 on top) results in a behavior change _at least_ when building clang with `-DCLANG_CONFIG_FILE_SYSTEM_DIR=/path/to/where/clang/will/be/installed/to/cfg`, and supplying the produced `default-clang` (supplying merely `clang` is unaffected).

Prior behavior: the script ends up executing the equivalent of 

```bash
/opt/clang-18.1.8/cfg/default-clang -print-prog-name=default-clang
# output: /opt/clang-18.1.8/cfg/default-clang
```

New behavior: no full path.
```bash
/opt/clang-19.1.1/cfg/default-clang -print-prog-name=default-clang
# output: default-clang
```

It is unclear if this behavior change to `-print-prog-name` is intentional hence why I'm filing this issue here first before filing a PR to icecc/icecream.

Resolution/workaround (at least for this execution of `-print-prog-name` is simple-- I'll just modify the script to call `-no-canonical-prefixes -print-prog-name`.

```bash
/opt/clang-19.1.1/cfg/default-clang -no-canonical-prefixes -print-prog-name=default-clang
# output: /opt/clang-19.1.1/cfg/default-clang
```

There is [another use of `-print-prog-name` in this script](https://github.com/icecc/icecream/blob/d680e4fcb261d7de271ddce331f4a23adbfd573f/client/icecc-create-env.in#L223) that I appears unaffected as it requests the name of actual binaries (potentially outside of the clang installation directory? is the key factor?) rather than a clang config symlink to one.

**Comment by 13steinj** [comment]
I understand the original intent is

> [1] If a user creates a symlink to the regular file clang and uses the
default -canonical-prefixes, they now consistently get search and
library paths relative to the regular file clang, not mix-and-match
paths.

> [2] If a user creates a symlink to the regular file clang and replaces
some directorys from the actual installation, they should change the
symlink to a wrapper that calls the underlying clang with
-no-canonical-prefixes.

I assume this actually occurs; however the unclear part to me is if side effect

[3] `-print-prog-name` of such symlinks was supposed to change with this as well to result in just the name of the symlink itself (considering the documentation is [unchanged](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-print-prog-name)).

More accurately, the behavior changes from "symlinks to the clang binary treat the basename of the symlink as a valid program name such that the output should be the symlink" to "symlinks to the clang binary act as though one passed an invalid program name that clang doesn't know about and thus the output is the input."

Similarly it is unclear how intended effect [2] interacts with icecc / distcc envs; nor how it interacts with clang configs which, are still symlinks (and not wrappers that call the underlying clang; thought I don't know what "replaces some directories from the actual installation" means in this context).

cc @MaskRay in case they can clear some of this up.

**Comment by MaskRay** [comment]
> Resolution/workaround (at least for this execution of -print-prog-name is simple-- I'll just modify the script to call -no-canonical-prefixes -print-prog-name.

```
/opt/clang-19.1.1/cfg/default-clang -no-canonical-prefixes -print-prog-name=default-clang
# output: /opt/clang-19.1.1/cfg/default-clang
```

Specifying `-no-canonical-prefixes` is a resolution instead of a workaround, since the path components `/opt/clang-19.1.1/cfg` contain symlinks.

Without `-no-canonical-prefixes`, basically `dirname(realpath("/opt/clang-19.1.1/cfg/default-clang"))` will be the first element in `ProgramPaths`.
If that directory doesn't contain an executable `default-clang`, `clang --print-prog-name=default-clang` will print unprefixed `default-clang`.

Before #80527 , there was some inconsistency due to having both `InstalledDir` and `Dir`, but that was unintentional.
