### ISSUE TITLE
Small Documentation issues

### ISSUE THREAD

**Issue by Naville** [llvm/llvm-project#111]
https://clang.llvm.org/docs/LibASTMatchersReference.html
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/5205699/73130782-bb6cba80-4039-11ea-98c5-64f5cf9007e1.png">

http://releases.llvm.org 

The link to the release note of 9.0.1 is dead 
<img width="380" alt="image" src="https://user-images.githubusercontent.com/5205699/73130789-d4756b80-4039-11ea-8b6f-8a54f7fcb44d.png">

**Comment by ecnelises** [comment]
I committed https://github.com/llvm/llvm-project/commit/59d690850eebcd0e37f205bde16edbd4f2a54053 to fix the typo.

@tstellar Can you help to look at the release note missing? Thanks. I didn't find these in `www-releases` repo.

**Comment by Naville** [comment]
Ping. the link
