### ISSUE TITLE
clang-format adds unnecessary space before & when :: operator is used

### ISSUE THREAD

**Issue by mkaz101** [llvm/llvm-project#111011]
I experienced a strange bug in clang-format in version 19.1.1. I didn't observe it in version 16 (which I previously used in my project).
I have a setting to keep reference (&) signs glued to the type on the left side (`ReferenceAlignment: Left`). This formatting works for most functions, however if the function is in global scope (prepended with ::) clang-format is adding additional space between the type and &.

Here is the small code snippet that I used for testing.

```
class test {
  friend std::ostream& ::operator<<(std::ostream & lhs,
                                    const ::test_1::test2 &
                                        rhs);

  friend std::ostream& operator<<(std::ostream& lhs,
                                  const ::test_1::test2& rhs);
}
```

**Comment by rymiel** [comment]
Seems to have regressed in 3f3620e5c9ee0f7b64afc39e5a26c6f4cc5e7b37

I don't remember that patch anymore but looking at the diff, a check for coloncolon was removed, so maybe that's what happened?

**Comment by owenca** [comment]
> Seems to have regressed in [3f3620e](https://github.com/llvm/llvm-project/commit/3f3620e5c9ee0f7b64afc39e5a26c6f4cc5e7b37)

That patch uncovered a bug that `::operator` was not annotated as `FunctionDeclarationName`.

> I don't remember that patch anymore but looking at the diff, a check for coloncolon was removed, so maybe that's what happened?

That check was removed because it became redundant.
