### ISSUE TITLE
[WebAssembly] LLVM IR add does not compile to wrapping Wasm 

### ISSUE THREAD

**Issue by yowl** [llvm/llvm-project#111018]
https://godbolt.org/z/6ETzMh11h

This LLVM uses `add` to add -4 to a symbol, but the Wasm, as I read it, has the $base as -4 and $offset as the symbol, this will not wrap whereas the semantic for LLVM `add` should wrap.

Compiling with `O1` creates the correct Wasm:

https://godbolt.org/z/5W8rEMs5q

**Comment by aheejin** [comment]
By the way, can you post the original C code which generated this code?
