### ISSUE TITLE
Missing windows ARM-binaries in 19.1.1

### ISSUE THREAD

**Issue by emipa00** [llvm/llvm-project#111118]
The 18.1.8 release had support for windows ARM, did you miss that in this release or do you no longer support it?

**Comment by efriedma-quic** [comment]
Third-party binaries are not posted on the release page for LLVM 19 and later.  You can find third-party builds of LLVM 19 binaries at  https://discourse.llvm.org/t/llvm-19-x-release-third-party-binaries/80374 .  See https://discourse.llvm.org/t/rfc-improve-binary-security/78121/ for context.

**Comment by emipa00** [comment]
Not sure that answered my question, do you mean that the [LLVM-18.1.8-woa64.exe](https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/LLVM-18.1.8-woa64.exe) in the 18.1.8 release was not an official build? 
If it was from a third party, could you direct me to where you got it from?

**Comment by efriedma-quic** [comment]
https://discourse.llvm.org/t/18-1-8-has-been-tagged/79726/9 has information on who uploaded which builds for 18.1.8.

See also #111355 (which doesn't really say anything different, but there's some additional discussion about future directions.)

**Comment by omjavaid** [comment]
@emipa00  please read https://discourse.llvm.org/t/rfc-official-llvm-binary-releases-for-arm-and-aarch64-platforms/82413

**Comment by emipa606** [comment]
> @emipa00 please read https://discourse.llvm.org/t/rfc-official-llvm-binary-releases-for-arm-and-aarch64-platforms/82413

Thank you!

**Comment by emipa00** [comment]
> @emipa00 please read https://discourse.llvm.org/t/rfc-official-llvm-binary-releases-for-arm-and-aarch64-platforms/82413

Thank you!
