### ISSUE TITLE
[flang] gfortran expects semantic errors in some assumed-rank tests.

### ISSUE THREAD

**Issue by jeanPerier** [llvm/llvm-project#111120]
Need to triage if semantic errors expected by gfortran test suite are legit:

regression:
- c_sizeof_7.f90

regression/c-interop:
  - c535b-3.f90
  - c535c-1.f90
  - c535c-2.f90
  - c535c-3.f90
  - c535c-4.f90

**Comment by klausler** [comment]
For c_sizeof_7.f90: The F'2023 definition of `C_SIZEOF` doesn't require a whole array object.  18.2.3.8: "X shall be a data entity with interoperable type and type parameters, and shall not be an assumed- size array, an assumed-rank array that is associated with an assumed-size array, an unallocated allocatable variable, or a pointer that is not associated." and
"If X is an array, the result value is the value that the companion processor returns as the result of applying the sizeof operator to an object of a type that interoperates with the type and type parameters of X, multiplied by the number of elements in X."

For c535b-3.f90, errors should be emitted for attempts to use an assumed-rank dummy argument as the TARGET argument of ASSOCIATED; will fix.

For c535c-1.f90 through c535c-4.f90, errors should be emitted for actual arguments corresponding to INTENT(OUT) assumed-rank dummy arguments when the actual argument size cannot be known (e.g., assumed-size).  Will fix.

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/111204
