### ISSUE TITLE
Unexpected O1 Optimization Result

### ISSUE THREAD

**Issue by zchrissirhcz** [llvm/llvm-project#111251]
When calculate fibonacci number with `int` type, I throw an exception when result is greater than maximum int value. If specified `-O1` with `x86-64 clang(trunk)`(on GodBolt), it gives wrong result:

```
i = 46, fibo = 1836311903, a = 701408733, b = 1134903170
i = 47, fibo = -1323752223, a = 1134903170, b = 1836311903
i = 48, fibo = 512559680, a = 1836311903, b = -1323752223
i = 49, fibo = -811192543, a = -1323752223, b = 512559680
...
```

If no `-O1` specified, or using `x86-64 gcc(trunk)`, the result is expected:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Overflow at i = 47, c = -1323752223, a = 1134903170, b = 1836311903
Program terminated with signal: SIGSEGV
```

Reproduce code and compiler running result, see https://godbolt.org/z/WzfTqWhzd

**Comment by DimitryAndric** [comment]
Alternatively, use `-fwrapv` to make signed integer wrapping "defined", but you are then diverging from the standard of course. Then again, lots of projects (Linux kernel, Python, etc) use this... :)
