### ISSUE TITLE
Verification of Accurate Debug Information in BOLT After Optimizations

### ISSUE THREAD

**Issue by Thrrreeee** [llvm/llvm-project#111286]
Hello @ayermolo, 
I would like to inquire about the methods or processes employed by BOLT to ensure that the debug information remains accurate after optimizations. Specifically, after an optimization pass is applied, what mechanisms are used to verify that the updated debug information correctly reflects the transformed code?

While BOLT significantly improves the performance of binaries, it is crucial to retain the integrity of debug information, especially for profiling, debugging, and future code maintenance. Mismatches between the optimized code and the debug data can lead to confusion and errors during development.

Questions:

1. Are there specific verification tests or processes that check the accuracy of debug information post-optimization?
2. How does BOLT handle complex transformations that may affect source-to-binary mappings?
3. Are there any known limitations or challenges in maintaining accurate debug info during BOLT 's optimization process?

Thank you for your time and any insights you can provide regarding this matter.

**Comment by asl** [comment]
@Thrrreeee Consider using LLVM Discourse for discussions & questions, as this is not an issue.
