### ISSUE TITLE
[msan] Better handling of signed compare

### ISSUE THREAD

**Issue by eugenis** [llvm/llvm-project#111212]
https://github.com/llvm/llvm-project/pull/110880 triggers a false positive in MSan.

Improve handleSignedRelationalComparison to handle the kind of IR generated with that change; or enable exact handling (-msan-handle-icmp-exact) at the cost of ~3% code size and (unknown) CPU.

**Comment by goldsteinn** [comment]
Do you still want me to revert https://github.com/llvm/llvm-project/commit/a64643688526114b50c25b3eda8a57855bd2be87? Happy to do so.

**Comment by vitalybuka** [comment]
> Do you still want me to revert [a646436](https://github.com/llvm/llvm-project/commit/a64643688526114b50c25b3eda8a57855bd2be87)? Happy to do so.

Yes please! It will take some time to optimize -msan-handle-icmp-exact.

Please mention this issue in revert, so we can reland when msan is fixed.

**Comment by goldsteinn** [comment]
> > Do you still want me to revert [a646436](https://github.com/llvm/llvm-project/commit/a64643688526114b50c25b3eda8a57855bd2be87)? Happy to do so.
> 
> Yes please! It will take some time to optimize -msan-handle-icmp-exact.
> 
> Please mention this issue in revert, so we can reland when msan is fixed.

see you did so, thank you. Can you ping back on the PR when recommit is okay?

**Comment by vitalybuka** [comment]
@goldsteinn  Lat see if this one is not reverted and  try to reland #110880 tomorrow.
