### ISSUE TITLE
clang crashes from gcc torture test limits-pointer.c

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11123]
|  |  |
| --- | --- |
| Bugzilla Link | [10751](https://llvm.org/bz10751) |
| Version | 2.9 |
| OS | Linux |
| Attachments | [gcc torture test limits-pointer.c](https://user-images.githubusercontent.com/60944935/143743727-fb6a4ebd-7a10-48f3-a0eb-1990328ef6d5.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

~/build_llvm/install/bin/clang ~/gcc-4.4.6/gcc/testsuite/gcc.c-torture/compile/limits-pointer.c 
clang: error: unable to execute command: Segmentation fault
clang: error: clang frontend command failed due to signal 2 (use -v to see invocation)
clang: note: diagnostic msg: Please submit a bug report to http://llvm.org and include command line arguments and all diagnostic information.
clang: note: diagnostic msg: Preprocessed source(s) are located at:
clang: note: diagnostic msg: /tmp/cc-q6dAJR.i
rkotler@ubuntu-rkotler:~/icpc$

**Comment by Endilll** [comment]
Fixed in Clang 3.5.2
https://godbolt.org/z/o3MMPnMda
