### ISSUE TITLE
LLVM_TARGETS_TO_BUILD incomplete documentation (missing "host", "Native")

### ISSUE THREAD

**Issue by PerMildner** [llvm/llvm-project#111356]
https://github.com/llvm/llvm-project/blob/a1c0ba1646f5a80dadd34f55e4a36d5409c2675a/llvm/docs/CMake.rst?plain=1#L832

1. The "full list" of `LLVM_TARGETS_TO_BUILD` values is not complete and is missing the useful and commonly used values `host` and `Native`.
2. The `host` and `Native` values for `LLVM_TARGETS_TO_BUILD` do not seem to be documented anywhere.

[CMake.rst](https://github.com/llvm/llvm-project/blob/a1c0ba1646f5a80dadd34f55e4a36d5409c2675a/llvm/docs/CMake.rst?plain=1#L832) currently says:

> LLVM_TARGETS_TO_BUILD:STRING
>     Semicolon-separated list of targets to build, or all for building all targets. Case-sensitive. Defaults to all. Example: -DLLVM_TARGETS_TO_BUILD="X86;PowerPC". The full list, as of March 2023, is: AArch64;AMDGPU;ARM;AVR;BPF;Hexagon;Lanai;LoongArch;Mips;MSP430;NVPTX;PowerPC;RISCV;Sparc;SystemZ;VE;WebAssembly;X86;XCore

However, many places, both in `llvm-project` and outside, seem to use the values `host` and `Native`, which sounds like useful options. Unfortunately both are undocumented (and it is unclear whether they mean the same thing and why sometimes `host` is used and sometimes `Native`).

**Comment by harrisonGPU** [comment]
@dtcxzyw , Hello, what do you think about this PR:https://github.com/llvm/llvm-project/pull/111382
