### ISSUE TITLE
[clang-format] Space between `)` and ref-qualifier in for-loops shouldn't be removed

### ISSUE THREAD

**Issue by kadircet** [llvm/llvm-project#111346]
expected formatting for a.cc:
```cpp
for (foo<void() &&>& cb : X)
````

actual formatting (notice missing space between `void()` and `&&`)
```
$ clang-format -style='{PointerAlignment: Left}' a.cc
for (foo<void()&&>& cb : X)
```

**Comment by kadircet** [comment]
culprit seems to be 4fd14b9a3afb2ab34dfaa3bc4ed86e82122507be cc @owenca @mydeveloperday

**Comment by owenca** [comment]
Is this a regression or even a bug? The `&&` was annotated as `BinaryOperator` before, but it's been annotated as `PointerOrReference` since 4fd14b9a3afb2ab34dfaa3bc4ed86e82122507be.

**Comment by kadircet** [comment]
I am not sure about the annotation, it feels like the annotation was wrong both before and after the patch, but the user visible effect on final formatting is different. I think having the space before `&&` is more conventional for function prototypes, e.g:
```cpp
struct Foo {
  void bar() &&;
};
```

**Comment by owenca** [comment]
> I am not sure about the annotation, it feels like the annotation was wrong both before and after the patch, but the user visible effect on final formatting is different. I think having the space before `&&` is more conventional for function prototypes, e.g:
> 
> ```c++
> struct Foo {
>   void bar() &&;
> };
> ```

The `&&` here was annotated as `PointerOrReference` before and after the patch, which at least made annotating ref-qualifiers consistent everywhere. It also makes sense when there's a cv-qualifier before the ref-qualifier:
```
struct Foo {
  void bar() const&&;
};
```
