### ISSUE TITLE
Clang++ fails to match template template parameters as function arguments

### ISSUE THREAD

**Issue by PiliLatiesa** [llvm/llvm-project#111363]
Clang++ trunk started rejecting the following testcase (adapted from https://eel.is/c++draft/temp#arg.template-example-3). Clang 19 accepts it. It's a recent regression.

```c++
template <template <class, class...> class TT, class T1, class... Rest>
void f(TT<T1, Rest...> const &) {}

template <typename T1> struct A {};

int main()
{ 
  A<int> a;
  f(a);   // bogus "no matching function for call to 'f'"
}
```

**Comment by zyn0217** [comment]
@mizvekov Is it also related to #96023?

**Comment by cor3ntin** [comment]
Yes https://github.com/llvm/llvm-project/pull/96023#issuecomment-2393228464

**Comment by mizvekov** [comment]
This will be fixed by https://github.com/llvm/llvm-project/pull/111457
