### ISSUE TITLE
clang fails to compiler g++.dg/torture/pr37146-1.C

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11139]
|  |  |
| --- | --- |
| Bugzilla Link | [10767](https://llvm.org/bz10767) |
| Version | 2.9 |
| OS | Linux |
| Attachments | [pr37146.C](https://user-images.githubusercontent.com/60944935/143743744-8a1093e9-e9d5-4f53-96dd-0714622bf0a7.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic |

## Extended Description 

/home/rkotler/gcc-4.4.6/gcc/testsuite/g++.dg/torture/pr37146-1.C

Seems to be a known issue but I don't know if there is a bug filed for it.

r@ubuntu-rkotler:~/icpc$ ~/build_llvm/install/bin/clang++ /home/rkotler/gcc-4.4.6/gcc/testsuite/g++.dg/torture/pr37146-1.C
/home/rkotler/gcc-4.4.6/gcc/testsuite/g++.dg/torture/pr37146-1.C:17:4: error: 
      cannot compile this conditional operator yet
  (x ? c.i : c.j) = y;
   ^~~~~~~~~~~~~
1 error generated.

**Comment by shafik** [comment]
duplicate: https://github.com/llvm/llvm-project/issues/14181
