### ISSUE TITLE
I want clang-format to remove these empty lines, how to set the .clang-format?

### ISSUE THREAD

**Issue by traversebitree** [llvm/llvm-project#111340]
I want clang-format to remove these empty lines, how to set the `.clang-format`?

Keep `MaxEmptyLinesToKeep :1` and based on any style.

![image](https://github.com/user-attachments/assets/4813b8de-9e5a-421e-b7ac-346da1e1fa1f)

![image](https://github.com/user-attachments/assets/09c898fa-2b96-48a3-8e8b-0660383afe5e)

**Comment by owenca** [comment]
> I want clang-format to remove these empty lines, how to set the `.clang-format`?
> 
> Keep `MaxEmptyLinesToKeep :1` and based on any style.

Please add the new option `RemoveEmptyLinesInUnwrappedLines` implemented in #112325.

**Comment by traversebitree** [comment]
@owenca Thanks!

**Comment by TryerGit** [comment]
> Please add the new option `RemoveEmptyLinesInUnwrappedLines` implemented in [#112325](https://github.com/llvm/llvm-project/pull/112325).

Hello,
How can one access this version of clang-format? This reply is dated October 18th. Presumably the latest version available for download at https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.8 is dated earlier June 19th.
Can I just download clang-format.exe from somewhere else (for windows) which does include the new option?
Thanks.

**Comment by owenca** [comment]
It'll be available in version 20 as documented [here](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#removeemptylinesinunwrappedlines). If you want it sooner, you can build a latest version from the main branch.
