### ISSUE TITLE
[LLD] symbol not found with PROVIDE script

### ISSUE THREAD

**Issue by DianQK** [llvm/llvm-project#111478]
I tried the following code. I expect lld to link successful while also removing unused symbols, but it reports `symbol not found: bar`.

a.s:
```asm
.global _start
_start:
 nop
.section .text.foo,"ax",@progbits
.global foo
foo:
 nop
.section .text.bar,"ax",@progbits
.global bar
bar:
 nop
```

script.t:
```
PROVIDE(foo = bar);
```

commands:
```bash
llvm-mc -filetype=obj -triple=x86_64 a.s -o a.o
ld.lld -o a_gc a.o --gc-sections -T script.t
```

output:
```
ld.lld: error: script.t:1: symbol not found: bar
ld.lld: error: script.t:1: symbol not found: bar
ld.lld: error: script.t:1: symbol not found: bar
```

cc @MaskRay ebb326a51fec37b5a47e5702e8ea157cd4f835cd

**Comment by DianQK** [comment]
> I cannot reproduce `ld.lld: error: script.t:1: symbol not found: bar`. Are you testing the latest lld?
> 
> `foo` is not in the symbol table. lld considers it unneeded.

Sorry, I mistakenly deleted the definition of `foo`. I may have forgotten to run the `llvm-mc` command to verify after the deletion. I have now fixed this description.

**Comment by MaskRay** [comment]
Does #111945 address your use case?

**Comment by tru** [comment]
Does this need a backport?

**Comment by DianQK** [comment]
> Does #111945 address your use case?

I have verified that #111945 has fixed the build error in https://github.com/rust-lang/rust/issues/131164. 

I’d like to ask for your advice on the backport. I reverted the related changes in https://github.com/rust-lang/llvm-project/pull/178. What do you think is better, revert or cherry-pick the new patch?

**Comment by DianQK** [comment]
> Does this need a backport?

Yes. I think so. :)

**Comment by DianQK** [comment]
Backport PR: https://github.com/llvm/llvm-project/pull/112136
