### ISSUE TITLE
Inline assembly allocated register clash with multi-register constraints

### ISSUE THREAD

**Issue by netch80** [llvm/llvm-project#111494]
Consider the following minimum example (provided by Joseph C. Sible at the bugzilla origin):

```
void f(void) {
  asm volatile(
    "nop     # x is in %0 and y is in %1"
    :: "cd" (123), "cd" (456)
  );
}
```
With clang trunk (tested today on godbolt) there is no different registers assigned to two values as expected, with optimization levels from -O1 to -O3:
```
f():
        movl    $456, %ecx
        nop     # x is in %ecx and y is in %ecx
        retq
```
With -O0, there are two different load instructions compiled in.

My original example was more verbose but closer to the original exploded code:
```
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char *argv[])
{
  unsigned arg1 = strtoul(argv[1], NULL, 0);
  unsigned arg2 = strtoul(argv[2], NULL, 0);
  asm(
    "mov %[arg1], %%ecx\n\t"
    "add %[arg2], %[arg1]\n\t"
    "add %[arg2], %%ecx\n\t"
    "rcl $0, %%ecx"
    : [arg1] "+&abdSD" (arg1), [arg2] "+&abdSD" (arg2)
    :
    : "cc", "ecx");
  printf("%u %u\n", arg1, arg2);
}
```
With all levels from -O0 to -O3 it assigns the same register to arg1 and arg2.

GCC renders these statements correctly, different registers in all cases.

The first Clang version at which I've detected the issue is 6.0.

This is a clone of https://bugs.llvm.org/show_bug.cgi?id=48862, copying from now closed LLVM bugzilla.

**Comment by topperc** [comment]
The old bugzilla was migrated here https://github.com/llvm/llvm-project/issues/48206

**Comment by netch80** [comment]
Hm, sorry, the search was overfilled with irrelevant results.
So I close it.
wontfix/duplicate
