### ISSUE TITLE
__has_builtin(__reference_binds_to_temporary) became false in Clang 19

### ISSUE THREAD

**Issue by timsong-cpp** [llvm/llvm-project#111477]
Likewise for `__has_builtin(__reference_constructs_from_temporary)`. 

Is that intentional? What's the replacement if I want to detect whether the compiler supports them?

**Comment by timsong-cpp** [comment]
@cor3ntin Can a fix for the two intrinsics named in the issue be backported to clang 19? This is a [regression from clang 18](https://gcc.godbolt.org/z/nhYYTMrx8) - and for `__reference_binds_to_temporary`, from clang 10.

**Comment by cor3ntin** [comment]
> @cor3ntin Can a fix for the two intrinsics named in the issue be backported to clang 19? This is a [regression from clang 18](https://gcc.godbolt.org/z/nhYYTMrx8) - and for `__reference_binds_to_temporary`, from clang 10.

This seems reasonable
