### ISSUE TITLE
[RISCV][Backend]Do not know how to promote this operator's operand!

### ISSUE THREAD

**Issue by fioraking** [llvm/llvm-project#111486]
clang version 18.1.8 (https://github.com/llvm/llvm-project.git)

C code:
```
register int i asm("x22");
register int j asm("x23");

int main() {
  i = 12;
  j = 13;

  return i + j;
}

```

command:
```shell
clang -c -march=rv64gc 
```

output:
```
PromoteIntegerOperand Op #2: t8: ch = WRITE_REGISTER t24, MDNode:ch<0x1120f7e8>, Constant:i32<12>

fatal error: error in backend: Do not know how to promote this operator's operand!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
```

**Comment by topperc** [comment]
Use `long` or `uint64_t` instead of `int`. We need the variables to have XLEN bits. clang 20 will have better handling and give an error instead of crashing.

**Comment by topperc** [comment]
This is effectively a duplicate of https://github.com/llvm/llvm-project/issues/109588

**Comment by asb** [comment]
I wonder if we should backport https://github.com/llvm/llvm-project/pull/109596?

**Comment by fioraking** [comment]
> We need the variables to have XLEN bits
Thank you. But I have some problem.

Why it must have XLEN bits? Are there any authoritative sources?
Can it less than XLEN bits?

**Comment by topperc** [comment]
> > We need the variables to have XLEN bits
> 
> 
> 
> Thank you. But I have some problem.
> 
> 
> 
> Why it must have XLEN bits? Are there any authoritative sources?
> 
> Can it less than XLEN bits?
> 
> 

No. That's what caused the crash. `int` has 32 bits and XLEN is 64 for rv64.

This is a gcc feature that clang doesn't seem to implement very well. I can trigger similar crashe s on other targets than RISCV.

**Comment by fioraking** [comment]
> > > We need the variables to have XLEN bits
> > 
> > 
> > Thank you. But I have some problem.
> > Why it must have XLEN bits? Are there any authoritative sources?
> > Can it less than XLEN bits?
> 
> No. That's what caused the crash. `int` has 32 bits and XLEN is 64 for rv64.
> 
> This is a gcc feature that clang doesn't seem to implement very well. I can trigger similar crashe s on other targets than RISCV.

Bingo, so it can less than XLEN bits.

**Comment by fioraking** [comment]
As topperc commented.

**Comment by fioraking** [comment]
As topperc commented.
