### ISSUE TITLE
typeinfo problem  compiling gcc test g++.dg/cpp0x/auto10.C

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11150]
|  |  |
| --- | --- |
| Bugzilla Link | [10778](https://llvm.org/bz10778) |
| Version | 2.9 |
| OS | Linux |
| Attachments | [gcc/testsuite/g++.dg/cpp0x/auto10.C -std=c++0x](https://user-images.githubusercontent.com/60944935/143743749-b1368bca-ea21-4690-88f3-f93e375eb8a5.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 

/build_llvm/install/bin/clang
/home/rkotler/gcc-4.4.6/gcc/testsuite/g++.dg/cpp0x/auto10.C -std=c++0x
In file included from
/home/rkotler/gcc-4.4.6/gcc/testsuite/g++.dg/cpp0x/auto10.C:5:
In file included from /usr/include/c++/4.4/typeinfo:34:
In file included from /usr/include/c++/4.4/exception:148:
/usr/include/c++/4.4/exception_ptr.h:143:13: error: unknown type name
      'type_info'
      const type_info*
            ^
1 error generated.

rkotler@ubuntu-rkotler:~/test$ icpc
/home/rkotler/gcc-4.4.6/gcc/testsuite/g++.dg/cpp0x/auto10.C -std=c++0x
rkotler@ubuntu-rkotler:~/test$ g++
/home/rkotler/gcc-4.4.6/gcc/testsuite/g++.dg/cpp0x/auto10.C -std=c++0x
rkotler@ubuntu-rkotler:~/test$

**Comment by philnik777** [comment]
This has been fixed in Clang 3.0: https://godbolt.org/z/bhdfK63bh
