### ISSUE TITLE
[mlir] Add `MLIRContext::getDialectOperations(Dialect&)` or equiv

### ISSUE THREAD

**Issue by stellaraccident** [llvm/llvm-project#111591]
See: https://discourse.llvm.org/t/callback-to-iterate-over-all-dialect-op-classes/82417/3

We would likely be ok adding a little bit of extra accounting to keep track of the subrange of dialect ops in the sorted list of all operations for each dialect.

This would simplify things iterating over the subset of RegisteredOperationName that belong to a dialect (such as getting canonicalization patterns).

**Comment by harrisonGPU** [comment]
Hello, Stella. Could you please give me an example? If possible, could you please give me this opportunity? I want to try it.

**Comment by stellaraccident** [comment]
I don't have anything else. You can attempt a patch.

**Comment by harrisonGPU** [comment]
> I don't have anything else. You can attempt a patch.

Okay, I will try to attempt a patch! Thanks Stella. :)
