### ISSUE TITLE
assume_aligned incorrectly diagnoses a dependent return type

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#111563]
Consider:
```
template<typename T>
__attribute__((assume_aligned(2)))
T my_alloc(int);
```
(https://godbolt.org/z/EGebP7o8n)

Clang issues a diagnostic about the return type not being a pointer type despite there being no instantiations. It seems we need to add `if T->isDependentType() return true;` to `isValidPointerAttrType()`, possibly.

**Comment by AmrDeveloper** [comment]
Interested, i will do it, i tested it with if T->isDependentType() return true; and its working, i will create PR and update tests
