### ISSUE TITLE
Clang no longer showing basic warnings

### ISSUE THREAD

**Issue by SKPG-Tech** [llvm/llvm-project#111535]
Before (Clang 17) showed warings based on the clang-tidy file in the root of the project. After updating to Clang 18 and 19, it fails to show the same warnings anywhere, it only mentioned unsorted includes. Is this something that I'm doing wrong or is this a problem with Clang (Clangd?)

Clang 17
![image](https://github.com/user-attachments/assets/c5e8ecec-b1fd-4e87-9728-f1fa067a0182)

Clang 18 or 19
![image](https://github.com/user-attachments/assets/f25de297-d453-4a9b-8b1f-66e8a9b0ae22)

**Comment by HighCommander4** [comment]
Can you share a code example (complete, in text form), and [clangd logs](https://clangd.llvm.org/troubleshooting.html#gathering-logs) please?

**Comment by SKPG-Tech** [comment]
Sorry, this seems to be an issue with my .clang-tidy file I think. In any case, the logs threw this error
```
