### ISSUE TITLE
Add Flang frontend support for the missing target specific options.

### ISSUE THREAD

**Issue by manosanaggh** [llvm/llvm-project#111565]
In `clang/lib/Driver/ToolChains/Flang.cpp` resides the following TODO: `// TODO: Add target specific flags, ABI, mtune option etc.` under the function `void Flang::addTargetOptions`.

Here an analysis is needed for all the missing target specific flags that need to be supported by `Flang` (and are already supported by `Clang`).

Someone should also extend the visibility of those options to include `FlangOption, FC1Option` under `clang/include/clang/Driver/Options.td` before intervening in `clang/lib/Driver/ToolChains/Flang.cpp`.

This is going to need proper testcases for the testsuite in order to be upstreamable.

**Comment by manosanaggh** [comment]
Already has an assignee.

**Comment by tarunprabhu** [comment]
Are there specific options that you need supported?
