### ISSUE TITLE
Miscompile in GVN due to MemDepAnalysis caching

### ISSUE THREAD

**Issue by alinas** [llvm/llvm-project#111585]
The following miscompile was uncovered in GVN, to reproduce:
`opt --passes=gvn  gvntest.ll` on [gvntest.ll.txt](https://github.com/user-attachments/files/17299256/gvntest.ll.txt)

The miscompiled output is: 
[testafterbad.ll.txt](https://github.com/user-attachments/files/17299260/testafterbad.ll.txt)

It appears that if the cache entry is cleared at MemoryDependenceAnalysis.cpp:1060 with `NonLocalPointerDeps.erase(CacheKey);` before the insert, the test is correct.
The resulting IR with this change: 
[testaftergood.ll.txt](https://github.com/user-attachments/files/17299268/testaftergood.ll.txt)

**Comment by aeubanks** [comment]
reduced:

```llvm
define float @wombat(i1 %arg, i1 %arg1) {
bb:
  br label %bb3

bb2:                                              ; No predecessors!
  br label %bb3

bb3:                                              ; preds = %bb2, %bb
  %call = tail call noalias ptr @_Znwm(i64 8)
  br label %bb4

bb4:                                              ; preds = %bb4, %bb3
  %phi = phi ptr [ null, %bb4 ], [ %call, %bb3 ]
  store float 0.000000e+00, ptr %phi, align 4
  br i1 %arg, label %bb5, label %bb4

bb5:                                              ; preds = %bb4
  br i1 %arg1, label %bb7, label %bb6

bb6:                                              ; preds = %bb5
  %load = load <4 x float>, ptr %call, align 4
  %extractelement = extractelement <4 x float> %load, i64 0
  br label %bb9

bb7:                                              ; preds = %bb5
  %load8 = load float, ptr %call, align 4
  br label %bb9

bb9:                                              ; preds = %bb7, %bb6
  %phi10 = phi float [ %load8, %bb7 ], [ 1.000000e+00, %bb6 ]
  ret float %phi10
}

declare ptr @_Znwm(i64)
```

`opt -dom-tree-reachability-max-bbs-to-explore=1 -enable-pre=0 -p gvn -S`
