### ISSUE TITLE
dejagnu test fails to compiler with clang /g++.dg/cpp0x/rv-trivial-bug.C

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11158]
|  |  |
| --- | --- |
| Bugzilla Link | [10786](https://llvm.org/bz10786) |
| Version | 2.9 |
| OS | Linux |
| Attachments | [https://user-images.githubusercontent.com/60944935/143743754-e04e9ded-66b2-44e2-909f-6e6a21dad0c4.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

c00x extension

**Comment by philnik777** [comment]
This looks to me like Clang correctly rejects the code. GCC does too: https://godbolt.org/z/7qh5cGcoc
