### ISSUE TITLE
Documentation formatting error

### ISSUE THREAD

**Issue by cmorve-te** [llvm/llvm-project#111691]
https://github.com/llvm/llvm-project/blame/665457815f11118f7e755a471f33606c8562a4be/clang-tools-extra/docs/clang-tidy/checks/bugprone/reserved-identifier.rst#L31 used `_not_`.

As per https://docutils.sourceforge.io/docs/user/rst/quickref.html#inline-markup, it probably should be `*not*`.

**Comment by njriasan** [comment]
I would like to pickup this issue. Could you assign it to me?
