### ISSUE TITLE
[mlir] remove-dead-values zero exit code on failure

### ISSUE THREAD

**Issue by mtopalovicTT** [llvm/llvm-project#111757]
In case remove-dead-values pass emits error like below:

`/localdev/mtopalovic/src/tt-mlir/test/ttmlir/Dialect/TTNN/simple_broadcast.mlir:3:1: error: cannot optimize an IR with non-function symbol ops, non-call symbol user ops or branch ops`

mlir opt pass doesn't return `failure` but `success`.

This was discovered when llvm-lit reported that a test which emitted error above succeeded, but when command llvm-lit run was run manually you could see error above. This is because llvm-lit checks for error code in order to determine if test failed or succeeded. 

Are we missing `signalPassFailure` in `removeDeadValuePass`
https://github.com/llvm/llvm-project/blob/10054ba4acbc5378d2e2aa869a5bccd88aa4b59e/mlir/lib/Transforms/RemoveDeadValues.cpp#L584

**Comment by CoTinker** [comment]
https://github.com/llvm/llvm-project/blob/10054ba4acbc5378d2e2aa869a5bccd88aa4b59e/mlir/lib/Transforms/RemoveDeadValues.cpp#L591-L592
Maybe you can add `signalPassFailure` here.
