### ISSUE TITLE
dexter relies on the `imp` package that was removed from Python 3.12

### ISSUE THREAD

**Issue by asb** [llvm/llvm-project#111815]
Due to this dependency, it doesn't seem possible run the cross-project-tests on a system with Python 3.12+. [imp](https://docs.python.org/3.11/library/imp.html) has been deprecated since Python 3.4 it seems, and Python seems to have become more aggressive about actually removing modules marked as deprecated!

CC @SLTozer

**Comment by SLTozer** [comment]
Looks like a fairly straightforward update from `imp` to `importlib` is required - the only `imp` pattern used in Dexter is:
```python
  module_info = imp.find_module(name, [dir])
  imp.load_module(name, *module_info)
```
I'm not familiar enough to know the 1:1 replacement for `importlib`, but I imagine this should be a fairly common case; should be able to open a patch soon.
