### ISSUE TITLE
since Clang 17 `-ffast-math` prevents tail call optimization for math.h functions

### ISSUE THREAD

**Issue by namniav** [llvm/llvm-project#111950]
https://godbolt.org/z/Ea5ccfebr

```c
#include <math.h>

float foo(float x) {
    return expf(x);
}
```

Clang 17.0.1 `-O3 -ffast-math`:
```asm
foo:
        push    rax
        call    expf@PLT
        pop     rax
        ret
```

Clang 17.0.1 `-O3`:
```asm
foo:
        jmp     expf@PLT
```

Clang 16.0.0 `-O3 -ffast-math`:
```asm
foo:
        jmp     expf@PLT
```

GCC 14.2 `-O3 -ffast-math`:
```asm
foo:
        jmp     expf
```

**Comment by namniav** [comment]
They're not redundant for `call` due to [alignment requirement](https://stackoverflow.com/a/37774474), but a single `jmp` should be sufficient.

**Comment by dtcxzyw** [comment]
With `-ffast-math` we convert `expf` into `llvm.exp.f32`. I don't know why tail call optimization doesn't work here...
