### ISSUE TITLE
Request Commit Access For @Jobhdez

### ISSUE THREAD

**Issue by Jobhdez** [llvm/llvm-project#111947]
Hello, I have been contributing to LLVM libc since this past March and I am doing it relatively consistently. I also plan to keep working on LLVM libc because I want to work on libmvec. I am working closely with @lntue who is the current LLVM libc math maintainer.

**Comment by Jobhdez** [comment]
Sorry, I read this rfc https://discourse.llvm.org/t/rfc-change-the-process-for-requesting-commit-access/80184 and I thought I had to file an issue. I am going to email @lattner

**Comment by marcauberer** [comment]
@Jobhdez yes, currently you still have to email Chris. Will close this issue as resolved.
