### ISSUE TITLE
[lldb] Include guards missing for compression.h

### ISSUE THREAD

**Issue by ggreif** [llvm/llvm-project#112]
See: https://github.com/llvm/llvm-project/blob/f15b60b3a2a20f68ba303c5e771a0552718eca8e/lldb/tools/debugserver/source/RNBRemote.cpp#L43-L45

How it should be: https://github.com/llvm/llvm-project/blob/f15b60b3a2a20f68ba303c5e771a0552718eca8e/lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp#L49-L51

This was detected while [updating the `nixpkgs`](https://github.com/NixOS/nixpkgs/pull/78482) for llvm-10.

Similarly
https://github.com/llvm/llvm-project/blob/f15b60b3a2a20f68ba303c5e771a0552718eca8e/lldb/tools/debugserver/source/RNBRemote.cpp#L715-L761

needs to be adapted.

**Comment by ggreif** [comment]
This is now https://bugs.llvm.org/show_bug.cgi?id=44690.

**Comment by JDevlieghere** [comment]
https://reviews.llvm.org/D123616

**Comment by JDevlieghere** [comment]
@ggreif debugserver is only meant to be built on Darwin, where libcompression is always available. I think the right thing to do here is to stop building debugserver on NixOS.
