### ISSUE TITLE
HIP driver should not be invoking llvm-mc as the assembler

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#112031]
Clang is currently using llvm-mc as the assembler in the HIP driver: https://github.com/llvm/llvm-project/blob/2bb3d3a3f32ffaef3d9b6a27db7f1941f0cb1136/clang/lib/Driver/ToolChains/HIPUtility.cpp#L469

llvm-mc is for assembler tests, but isn't intended for use this way. Clang itself can be invoked as the assembler, which would avoid depending on an avoidable installed binary

**Comment by jhuber6** [comment]
Yeah we can just do the same thing the linker wrapper does, `clang --target=amdgcn-amd-amdhsa`.

**Comment by arsenm** [comment]
> Anything that stops us from invoking the compiler inside of the clang driver? Could also just do that.

That is how codegen always works? Driver invokes cc1? It's the same thing, just running for asm instead of source

**Comment by jhuber6** [comment]
> > Anything that stops us from invoking the compiler inside of the clang driver? Could also just do that.
> 
> That is how codegen always works? Driver invokes cc1? It's the same thing, just running for asm instead of source

The one thing that just makes this a little annoying is that `clang` doesn't have a valid language for assembly as far as I can tell, so you need it to be inferred from the filename. Other than that, should be a pretty straightforward swap of `llvm-mc` to `clang -c`.

**Comment by arsenm** [comment]
> The one thing that just makes this a little annoying is that `clang` doesn't have a valid language for assembly as far as I can tell

clang -x assembler?

**Comment by jhuber6** [comment]
> > The one thing that just makes this a little annoying is that `clang` doesn't have a valid language for assembly as far as I can tell
> 
> clang -x assembler (or -x assembler-with-cpp)?

Stand corrected, didn't see that in the list of approved user specified types in `clang/lib/Types.cpp`. Should be easy then.
