### ISSUE TITLE
missing error when bound member function not called

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#11202]
|  |  |
| --- | --- |
| Bugzilla Link | [10830](https://llvm.org/bz10830) |
| Version | unspecified |
| OS | Linux |
| CC | @dwblaikie,@DougGregor,@zygoloid |

## Extended Description 
Sometimes clang doesn't diagnose when a bound non-static member function is not called:

```cpp
  struct C { void f() {}; };
  decltype(C().f);             // -Wmissing-declarations warning, expected error
```

**Comment by shafik** [comment]
This is a hard error now: https://godbolt.org/z/qf7e4eT8d
