### ISSUE TITLE
[DirectX] Shader Flag Analysis to indicate use of Raw and Structured Buffers

### ISSUE THREAD

**Issue by bharadwajy** [llvm/llvm-project#112273]
Two flags viz., `ComputeShadersPlusRawAndStructuredBuffers` and `EnableRawAndStructuredBuffers` are set based on use of raw and structured buffers.

- [ ] Implement shader flag analysis to set `EnableRawAndStructuredBuffers` if shader uses Raw or Structured buffers.
- [ ] Implement shader flag analysis to set `ComputeShadersPlusRawAndStructuredBuffers` if shader uses Raw or Structured buffers, SM Major is = 4 and is a compute shader

NOTE:`EnableRawAndStructuredBuffers` is required for particle life but `ComputeShadersPlusRawAndStructuredBuffers` depends on one extra condition and can be implemented alongside.

See [DxilModule::CollectShaderFlagsForModule(ShaderFlags &Flags)](https://github.com/microsoft/DirectXShaderCompiler/blob/db90a461c5f35b75cfbd5d9368810be103c5d2b2/lib/DXIL/DxilModule.cpp#L291C6-L291C65) - specifically setting of `bool hasRawAndStructuredBuffer` for the conditions to set the flag `ComputeShadersPlusRawAndStructuredBuffers` and `EnableRawAndStructuredBuffers`.

AC
Add tests that use Raw and Structure buffers to verify that the flags are appropriately set.

**Comment by coopp** [comment]
This issue is blocked at the moment by the need to generate proper IR for tests.  ResourceKinds are not being picked up correctly for StructuredBuffers or other types.

**Comment by coopp** [comment]
Not blocked

**Comment by coopp** [comment]
Closing this issue as these flags being set are no longer needed or used.  The PR created to set the flags has been closed out as well and not merged.

Tex opened https://github.com/microsoft/DirectXShaderCompiler/issues/7003 to track addressing what to do with them long term.

**Comment by bogner** [comment]
I opened #122663 the other day, which seems to be a duplicate. We should discuss whether this is really "not needed"
