### ISSUE TITLE
Clang-format does not remove multiple line breaks within a statement

### ISSUE THREAD

**Issue by Terve16** [llvm/llvm-project#112225]
If I have a statement that has multiple line breaks, clang-format does not remove them. E.g.: 
Original:
```
  int c

    = a + b;
```

Desired Output:
`  int c = a + b;`

But it does not remove them. I can add as many line breaks as I want and they remain. It only works with a single line break.
I know this is really bad formatting, but it should be valid C code. Therefore I would expect clang-format to fix this.

I have searched for options to change this behavior, but I did not find anything.

I use clang format versions 18.1.3 and 14.0.6.

Is this behavior a bug or expected? If it has to be like this - what is the reason and is there a way to change it?

**Comment by owenca** [comment]
This is a duplicate of #111340.
