### ISSUE TITLE
[InstCombine] `samesign` flag should be dropped

### ISSUE THREAD

**Issue by dtcxzyw** [llvm/llvm-project#112350]
Reproducer:
```
define i1 @src(i64 %x, i64 %y, i1 %cond) {
  %cmp1 = icmp ult i64 %x, %y
  %cmp2 = icmp samesign uge i64 %x, %y
  %sel = select i1 %cond, i1 %cmp1, i1 %cmp2
  ret i1 %sel
}

define i1 @tgt(i64 %x, i64 %y, i1 %cond) {
  %cmp2 = icmp samesign uge i64 %x, %y
  %sel = xor i1 %cond, %cmp2
  ret i1 %sel
}
```

**Comment by antoniofrighetto** [comment]
Don't we miss checking the flag in `hasPoisonGeneratingFlags`?

**Comment by dtcxzyw** [comment]
> Don't we miss checking the flag in `hasPoisonGeneratingFlags`?

Yeah. I am preparing a patch.

**Comment by dtcxzyw** [comment]
But adding support in `hasPoisonGeneratingFlags` doesn't address this issue :(

**Comment by antoniofrighetto** [comment]
> But adding support in `hasPoisonGeneratingFlags` doesn't address this issue :(

I assume we may need to `dropPoisonGeneratingFlags` in InstCombineCompares, where needed?
