### ISSUE TITLE
Address-space casts cause LLVM assertion

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11237]
|  |  |
| --- | --- |
| Bugzilla Link | [10865](https://llvm.org/bz10865) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic |

## Extended Description 
This code causes an LLVM assertion ("Pointer must be a pointer to Val type" during generation of a StoreInst):

    #define MY_ADDRESS_SPACE    __attribute__((address_space(512)))
    void MY_ADDRESS_SPACE *x = (void MY_ADDRESS_SPACE *)malloc(123);

But this works fine:

    #define MY_ADDRESS_SPACE    __attribute__((address_space(512)))
    void MY_ADDRESS_SPACE *x = (void MY_ADDRESS_SPACE *)(uintptr_t)malloc(123);

Looks like clang isn't generating a bitcast instruction where one is needed, and the intermediate uintptr_t forces the bitcast generation.

**Comment by Endilll** [comment]
We diagnose this since Clang 8, and fixed that in Clang 10: https://cexplorer.testlabs.pro/z/oxhqfd
