### ISSUE TITLE
Bootstrap build exhausts memory and looks fall into infinite loop on X86

### ISSUE THREAD

**Issue by bzEq** [llvm/llvm-project#112347]
Use the trunk driver to bootstrap, the clang driver looks falling into infinite loop on X86.
To reproduce, use the commit 0a17bdfc361400cb511368f2edfc68c0d11e1974 to build an `llc` and run following command
```
llc < sample.ll
```
[sample.ll.txt](https://github.com/user-attachments/files/17377449/sample.ll.txt)

**Comment by bzEq** [comment]
I believe 4647a4666c4f8edabaa89163e899953bcd584aa7 is a good commit, I'm bisecting to find the first bad commit.

**Comment by bzEq** [comment]
```
6fd229a655f521a9f58d40c671e5cab4ea3ea87b is the first bad commit
commit 6fd229a655f521a9f58d40c671e5cab4ea3ea87b
Author: Miguel Saldivar <miguel.saldivar@hpe.com>
Date:   Sat Oct 12 03:28:39 2024 -0700

    [X86] Invert (and X, ~(and ~Y, Z)) back into (and X, (or Y, ~Z)) (#109215)
    
    When `andn` is available, we should avoid switching `s &= ~(z & ~y);` into `s &= ~z | y;`
    
    This patch turns this assembly from:
    ```
    foo:
            not     rcx
            and     rsi, rdx
            andn    rax, rsi, rdi
            or      rcx, rdx
            and     rax, rcx
            ret
    ```
    into:
    ```
    foo:
            and     rsi, rdx
            andn    rcx, rdx, rcx
            andn    rax, rsi, rdi
            andn    rax, rcx, rax
            ret
    ```
    Fixes #108731
```
@Saldivarcher Could you please take a look?

**Comment by RKSimon** [comment]
Trying to reduce now

**Comment by RKSimon** [comment]
llc -mtriple=x86_64-- -mattr=+bmi
```ll
define void @PR112347(ptr %p0, ptr %p1, ptr %p2) {
  %load0 = load i32, ptr %p0, align 1
  %load1 = load i32, ptr %p1, align 4
  %not = xor i32 %load0, -1
  %top = or i32 %not, -16777204
  %mask = and i32 %load1, %top
  store i32 %mask, ptr %p2, align 4
  ret void
}
```

**Comment by Saldivarcher** [comment]
@RKSimon thanks for fixing this 👍
