### ISSUE TITLE
[BoundsSafety] Move `FieldDecl::IsBoundsSafetyCounter` to an attribute.

### ISSUE THREAD

**Issue by rapidsna** [llvm/llvm-project#112586]
`IsBoundsSafetyCounter` is used to indicate that the field is referred to by another field that has `__counted_by` or friends. `__counted_by` will be extended to be used on a variable. Hence, we would need an attribute to apply to a non-field decl and hold more information about the other variable referring to it.

**Comment by bwendling** [comment]
I removed this flag.
