### ISSUE TITLE
Assertion "Narrow integer argument must have a valid extension type." failed.

### ISSUE THREAD

**Issue by JonPsson1** [llvm/llvm-project#112503]
@sum seems to have extension attributes missing for the returned value as well as for both of the arguments:

```
Testing: 
FAIL: LLVM-Unit :: ExecutionEngine/Orc/./OrcJITTests/7/21 (1 of 79162)
******************** TEST 'LLVM-Unit :: ExecutionEngine/Orc/./OrcJITTests/7/21' FAILED ********************
Script(shard):
--
GTEST_OUTPUT=json:/home/ijonpan/llvm-project/build/unittests/ExecutionEngine/Orc/./OrcJITTests-LLVM-Unit-344154-7-21.json GTEST_SHUFFLE=0 GTEST_TOTAL_SHARDS=21 GTEST_SHARD_INDEX=7 /home/ijonpan/llvm-
project/build/unittests/ExecutionEngine/Orc/./OrcJITTests
--

Note: This is test shard 8 of 21.
[==========] Running 8 tests from 7 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from CoreAPIsStandardTest
[ RUN      ] CoreAPIsStandardTest.RemoveSymbolsTest
[       OK ] CoreAPIsStandardTest.RemoveSymbolsTest (0 ms)
[ RUN      ] CoreAPIsStandardTest.GeneratorTest
[       OK ] CoreAPIsStandardTest.GeneratorTest (0 ms)
[----------] 2 tests from CoreAPIsStandardTest (0 ms total)

[----------] 1 test from ExecutorAddrTest
[ RUN      ] ExecutorAddrTest.PtrConversion
[       OK ] ExecutorAddrTest.PtrConversion (0 ms)
[----------] 1 test from ExecutorAddrTest (0 ms total)

[----------] 1 test from MapperJITLinkMemoryManagerTest
[ RUN      ] MapperJITLinkMemoryManagerTest.Coalescing
[       OK ] MapperJITLinkMemoryManagerTest.Coalescing (0 ms)
[----------] 1 test from MapperJITLinkMemoryManagerTest (0 ms total)

[----------] 1 test from OrcCAPITestBase
[ RUN      ] OrcCAPITestBase.EnableDebugSupport
ERROR: Missing extension attribute of returned value from function:
i32 @sum(i32, i32)

```
@lhames @nikic

**Comment by JonPsson1** [comment]
ping. @lhames @nikic @SahilPatidar @vtjnash @higuoxing @tjk213 

This seems to be a generated test of some kind, and I don't know how to reproduce it. Is @sum() part of some test code, or is it part of the ExecutionEngine runtime library?

**Comment by weliveindetail** [comment]
Yes, there are a few inline. This one is here: https://github.com/llvm/llvm-project/blob/900b6369e2f5fbc229371a142fdcd28b5280dbc0/llvm/unittests/ExecutionEngine/Orc/OrcCAPITest.cpp#L211

**Comment by lhames** [comment]
@JonPsson1 Is there a desire to continue supporting the LLVM JIT on SystemZ? I just noticed that SystemZ is one of the architectures for which we have no JITLink backend.

**Comment by JonPsson1** [comment]
Patch: https://github.com/llvm/llvm-project/issues/112503

**Comment by uweigand** [comment]
> @JonPsson1 Is there a desire to continue supporting the LLVM JIT on SystemZ? I just noticed that SystemZ is one of the architectures for which we have no JITLink backend.

Oh, we absolutely want LLVM JIT on SystemZ!  I admit I haven't followed ongoing JIT developments closely so I must have overlooked that we're missing a piece here.  @JonPsson1, @dominik-steenken - we'll need to look into closing this gap.

**Comment by lhames** [comment]
> > @JonPsson1 Is there a desire to continue supporting the LLVM JIT on SystemZ? I just noticed that SystemZ is one of the architectures for which we have no JITLink backend.
> 
> Oh, we absolutely want LLVM JIT on SystemZ! I admit I haven't followed ongoing JIT developments closely so I must have overlooked that we're missing a piece here. @JonPsson1, @dominik-steenken - we'll need to look into closing this gap.

The existing MCJIT implementation is ok for now, but MCJIT (and the RuntimeDyld JIT linker that it's based on) will be deprecated soon, and eventually removed in favor of ORC and JITLink (our new JIT linker). There should be plenty of time to get this done (at least a couple of release cycles, probably more), and there are some good reference implementations that you can look at in `llvm/lib/ExecutionEngine/JITLink`, e.g. PPC64 (See initial commit https://github.com/llvm/llvm-project/commit/8313507a7c3fd0603cd4cab1dc220235bd668ae1, and follow-ups by @bzEq) and Loongarch (initial commit https://github.com/llvm/llvm-project/blob/main/llvm/lib/ExecutionEngine/JITLink/loongarch.cpp).
