### ISSUE TITLE
[Clang] Clang erroneously allows `if constexpr` in C23 mode

### ISSUE THREAD

**Issue by Sirraide** [llvm/llvm-project#112587]
See https://godbolt.org/z/E8PEzzfP3. According to @AaronBallman, this isn’t intentional, so we should probably disallow this.

**Comment by AaronBallman** [comment]
It would be really nice if we could get a fix for this in to Clang 19.x

**Comment by Fznamznon** [comment]
I don't think this is a regression since clang 18 doesn't support c23 constexpr.

**Comment by shafik** [comment]
> I don't think this is a regression since clang 18 doesn't support c23 constexpr.

I guess I look at it as `if constexpr` is now erroneously enabled in C whereas previously it was a hard error.
