### ISSUE TITLE
[flang][HLFIR] unimplemented symbol lowering

### ISSUE THREAD

**Issue by tblah** [llvm/llvm-project#112549]
Some programs from the Fujitsu test suite hit `not yet implemented: lowering symbol to HLFIR`:
- https://github.com/fujitsu/compiler-test-suite/blob/main/Fortran/0115/0115_0009.F90
- https://github.com/fujitsu/compiler-test-suite/blob/main/Fortran/0115/0115_0010.F90
- https://github.com/fujitsu/compiler-test-suite/blob/main/Fortran/0115/0115_0011.F90

Here is a minimal reproducer:
```
subroutine sub1(dest1, dest2, src1, src2)
  real, dimension(1:2)::dest1, dest2, src1, src2
  integer::i

  do i=1,2
     block
       dest1(i) = src1(i) * src2(i) + src1(i) * src2(i)
     end block
  end do
end subroutine sub1

subroutine sub2(dest1_res, dest2_res, src1_res, src2_res)
  real(kind=8),dimension(1:2)::dest1_res, dest2_res, src1_res, src2_res
end subroutine sub2
```

@jeanPerier is this expected? I was surprised to see a HLFIR TODO

**Comment by jeanPerier** [comment]
Thanks for bringing this to my attention @tblah, yes that is a bug, but it seems to be a really weird front-end bug. The parse tree is broken, the statement inside the block was somehow moved to sub2, hence lowering crashes when lowering sub2:

```
subroutine sub1(dest1, src1)
  real, dimension(1:2)::dest1, src1
  integer::i
  block
    dest1(i) = src1(1)
  end block
end subroutine sub1

subroutine sub2()
end subroutine sub2
```

`flang-new -fc1 -fdebug-unparse` output is bad:

```
SUBROUTINE sub1 (dest1, src1)
 REAL, DIMENSION(1_4:2_4) :: dest1, src1
 INTEGER i
 BLOCK
 END BLOCK
END SUBROUTINE sub1
SUBROUTINE sub2
  dest1(int(i,kind=8))=src1(1_8)
END SUBROUTINE sub2
```

**Comment by klausler** [comment]
I am tempted to say "that's not even possible" and assign it back to you.
