### ISSUE TITLE
[Clang-tidy] Why are there differences in the detection of such duplicate claims?

### ISSUE THREAD

**Issue by Zhenhang1213** [llvm/llvm-project#112691]
Why are there differences in the detection of such duplicate claims？

demo: [godbolt](https://godbolt.org/z/6MGdEYsqq)

**Comment by EugeneZelenko** [comment]
There is no difference in `main`: https://godbolt.org/z/cP7nrPM46

**Comment by Zhenhang1213** [comment]
> There is no difference in `main`: https://godbolt.org/z/cP7nrPM46

U would see that there is no warning for f1, right?

**Comment by Zhenhang1213** [comment]
I find it is related with order.
