### ISSUE TITLE
[META] #pragma weak does not work

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11271]
|  |  |
| --- | --- |
| Bugzilla Link | [10899](https://llvm.org/bz10899) |
| Version | trunk |
| OS | Linux |
| Depends On | llvm/llvm-project#4051 llvm/llvm-project#8755 llvm/llvm-bugzilla-archive#15695 llvm/llvm-project#8846 llvm/llvm-project#10522  |
| Reporter | LLVM Bugzilla Contributor |
| CC | @gribozavr |

**Comment by philnik777** [comment]
Closing, since metabugs don't really work on github.
