### ISSUE TITLE
Add CMake Support to SAFECode

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11287]
|  |  |
| --- | --- |
| Bugzilla Link | [10915](https://llvm.org/bz10915) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @seanm |

## Extended Description 
SAFECode currently builds only with the Autconf configure scripts and make.  Some people have expressed an interest in a CMake build system.

**Comment by arsenm** [comment]
cmake is the only build system now
