### ISSUE TITLE
`wasm-ld -v` exits without generating output

### ISSUE THREAD

**Issue by jmillikin** [llvm/llvm-project#112836]
lld has two version-related options, `-v` and `--version`. The difference is that `ld.lld -v -o hello hello.o` will print out its version and then continue, whereas `ld.lld --version -o hello hello.o` will exit immediately.

https://github.com/llvm/llvm-project/blob/7ba7d8e2f7b6445b60679da826210cdde29eaf8b/lld/ELF/Driver.cpp#L634-L635

https://github.com/llvm/llvm-project/blob/7ba7d8e2f7b6445b60679da826210cdde29eaf8b/lld/ELF/Driver.cpp#L657-L662

When lld is invokved as `wasm-ld` , it treats both flags identically and always exits early:

https://github.com/llvm/llvm-project/blob/7ba7d8e2f7b6445b60679da826210cdde29eaf8b/lld/wasm/Driver.cpp#L1193-L1197

This breaks existing tooling that expects `clang -Wl,-v` to generate output regardless of the chosen target platform.

**Comment by sbc100** [comment]
Seems like we can/should just match the ELF behaviour here.  Would you have time to upload a PR for that?

**Comment by jmillikin** [comment]
I could send a PR but I don't currently have a machine capable of doing an LLVM build, so my PR would be untested (other than by CI). Would that be ok?

**Comment by sbc100** [comment]
No worries, I can take care of it
