### ISSUE TITLE
The branch instruction is compiled into other instructions after linking

### ISSUE THREAD

**Issue by muxiff** [llvm/llvm-project#112818]
Hi,
I have customized two branch instructions using the following class,
```
let DecoderNamespace = "Namspace" in {
  class BranchClassName<bit F, bits<3> funct3, string opcodestr>
    : RVInst<(outs), (ins GPR:$rs1, GPR:$rs2, simm12_lsb0:$imm11), 
              opcodestr, "$rs1, $rs2, $imm11", [], InstFormatB> {
    bits<5> rs1;
    bits<5> rs2;
    bits<11> imm11;

    let Inst{31} = F;
    let Inst{30-25} = imm11{9-4};
    let Inst{24-20} = rs2;
    let Inst{19-15} = rs1;
    let Inst{14-12} = funct3;
    let Inst{11-8} = imm11{3-0};
    let Inst{7} = imm11{10};
    let Inst{6-0} = OPC_CUSTOM_3.Value;

    let isBranch = 1;
    let isTerminator = 1;
  }
}
```
When I use them simultaneously in the same assembly file, the encoding and decoding I see when performing assembly and disassembly operations are one-to-one correspondence.
 However, when I compile this assembly file into a complete elf and then use disassembly tools to view it, I found that one of these two branch instructions has been compiled into the other. 
Can someone tell me why this is happening, or is there any other restriction that needs to be added to the class definition？

**Comment by RamaKishanMalladi** [comment]
Can you confirm you are using unique encoding bits for each of these branch instructions? It would help if you can share more details/ a reproducer. Thanks

**Comment by topperc** [comment]
What if you change `InstFormatB` to `InstFormatOther`. InstFormatB tells RISCVMCCodeEmitter.cpp to generate a relocation that allows the linker to relax the branch instruction. Your encoding is a little different than the standard branch encoding so the linker could be corrupting it.

**Comment by muxiff** [comment]
I am certain that the encoding is unique, but as suggested by @topperc , I have now added a new `InstFormat*` and relocation type, and the issue has been resolved. Thank you for your reply.
