### ISSUE TITLE
[clang][libc][complex][c23] Add support for the `_Imaginary` builtin-type

### ISSUE THREAD

**Issue by Sh0g0-1758** [llvm/llvm-project#112932]
Refer Annex G of the [ISO](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf) spec. Clang should support the `_Imaginary` builtin-type. The specifications for adding this type are : 

1. It is used as a type specifier within declaration specifiers in the same way as `_Complex` is (thus, float _Imaginary is a valid type name).
2. Each imaginary type has the same representation and alignment requirements as the corresponding real type. The value of an object of imaginary type is the value of the real representation times the imaginary unit.

cc: @lntue

**Comment by frederick-vs-ja** [comment]
But `_Imaginary` is recently removed from C2y, see also [WG14 N3274](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3274.pdf).

**Comment by Sh0g0-1758** [comment]
The reason for removing this from C2y seems rather weird (because no compiler supports it). But thanks for pointing this out. I think I will close this issue for now.
