### ISSUE TITLE
files placed in source directory during make or make check

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11290]
|  |  |
| --- | --- |
| Bugzilla Link | [10918](https://llvm.org/bz10918) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic |

## Extended Description 
Sometimes as a result of make, files are placed in the source directory (as opposed to the build directory). This can cause problems and lead to false failures later sometimes.

In one source directory, the following files appeared:	docs/SegmentedStacks.html
#	test/Analysis/BasicAA/memset_pattern.ll
#	test/CodeGen/ARM/2011-08-29-SchedCycle.ll
#	test/CodeGen/ARM/2011-08-29-ldr_pre_imm.ll
#	test/CodeGen/ARM/atomic-64bit.ll
#	test/CodeGen/ARM/elf-lcomm-align.ll
#	test/CodeGen/ARM/subreg-remat.ll
#	test/CodeGen/PowerPC/cr1eq.ll
#	test/CodeGen/X86/2011-08-29-BlockConstant.ll
#	test/CodeGen/X86/MachineSink-DbgValue.ll
#	test/CodeGen/X86/segmented-stacks.ll
#	test/MC/ARM/basic-thumb2-instructions.s
#	test/MC/ARM/thumb-nop.s
#	test/MC/ARM/thumb2-diagnostics.s
#	test/MC/Disassembler/ARM/thumb2.txt
#	test/Transforms/DeadStoreElimination/2011-09-06-EndOfFunction.ll
#	test/Transforms/DeadStoreElimination/2011-09-06-MemCpy.ll
#	test/Transforms/GVN/pr10820.ll
#	test/Transforms/InstSimplify/2011-09-05-InsertExtractValue.ll
#	test/Transforms/LoopUnroll/pr10813.ll
#	test/Transforms/SCCP/atomic-load-store.ll
#	test/Transforms/SimplifyCFG/2011-09-05-TrivialLPad.ll

In another:

#	test/CodeGen/ARM/2011-09-09-OddVectorDivision.s

**Comment by arsenm** [comment]
Never seen this as an issue
