### ISSUE TITLE
[AMDGPU] Numerical error related to load/store vectorization

### ISSUE THREAD

**Issue by qedawkins** [llvm/llvm-project#112941]
The following input example: https://gist.github.com/qedawkins/c620832f96a5c504295f9694cc8956e2

Which is approximately compiled from
```
// int8_t a[144]; // [2 x 8 x 3 x 3]
// int8_t b[144]; // [2 x 8 x 3 x 3]
// int c[2];
__global__ void helloworld(int8_t* a, int8_t* b, int* c)
{
  int id = hipThreadIdx_x
  if (id < 2) {
    for (int c = 0; c < 8; ++c) {
      for (int h = 0; h < 3; ++h) {
        for (int w = 0; w < 3; ++w) {
          int x = a[id * 72 + c * 9 + h * 3 + w];
          int y = b[id * 72 + c * 9 + h * 3 + w];
          c[id] += x * y;
        }
      }
    }
  }
}
```

When compiled with
```
llc -O3 module_test_dispatch_0_rocm_hsaco_fb.optimized.ll -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100
```
Produces incorrect numerics. For inputs
```
a = np.ones((2, 8, 3, 3), dtype=np.int8)
b = np.broadcast_to(np.array([1, 2, 1], dtype=np.int8), (2, 8, 3, 3))
```
In other words only the values of `b` vary along the inner most loop, this gives `c = [88, 88]` when the correct values should be `(1 + 2 + 1) * 3 * 8 = [96, 96]`

Compiling with
```
llc -O3 module_test_dispatch_0_rocm_hsaco_fb.optimized.ll -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 -amdgpu-load-store-vectorizer=false
```
(turning off the load/store vectorizer) or just with `-O1` instead of `-O3` gives the correct values. I am not sure exactly how the generated code is miscompiling and don't know whether load/store vectorization is the root cause or if disabling it is just masking the problem. Further information about the downstream issue here: https://github.com/iree-org/iree/issues/18798

cc @MaheshRavishankar

**Comment by arsenm** [comment]
No idea what's wrong but there are some weird things with this IR. Something is quite suboptimal with whatever produced it.

First it has a sequence of assumes at the start of the function, asserting that the pointers are aligned. The assumes are implemented using ptrtoint (a better way would be in terms of llvm.ptrmask). But the assumes are entirely unnecessary, they are redundant with the align attribute on the pointer parameters. Assumes are in general harmful, so these should only be added when they definitely do something.

Second, this IR has not run through the middle end optimizer passes. The vectorization seen in llc -O3 produces strange 7 and 9 element vectors, which produce sloppy looking codegen. The vectorization produced from the middle end is much more reasonable looking

**Comment by arsenm** [comment]
Does it work if you use -global-isel?

**Comment by MaheshRavishankar** [comment]
Thanks @arsenm ! We can definitely drop the assumes that you think are redundant. The IR should be produced with `opt -O3` though.

**Comment by arsenm** [comment]
> Thanks @arsenm ! We can definitely drop the assumes that you think are redundant. The IR should be produced with `opt -O3` though.

It is not. The IR radically changes if I run opt/clang -O3 on it

**Comment by MaheshRavishankar** [comment]
I checked, we are using `-O2` AFAICS. So maybe `-O2` to `-O3` makes a difference.

**Comment by arsenm** [comment]
Overall I think the vectorization is a red herring. The SLPVectorizer should run at any optimization level, by default.

My suspicion is that this is something wrong with the v_perm_b32 and related bit shuffling optimizations. Globalisel just happens to not implement those, so it's the closest thing we have to an option to disable them

**Comment by MaheshRavishankar** [comment]
> Overall I think the vectorization is a red herring. The SLPVectorizer should run at any optimization level, by default.

We've had issues with SLP vectorizer using up too many registers and spilling/degrading performance (on other backends). We tried turning it on for AMD GPU backend, and it seems ok but it is something we are scared about cause we prefer to vectorize ourselves instead of using SLP vectorizer. 

> 
> My suspicion is that this is something wrong with the v_perm_b32 and related bit shuffling optimizations. Globalisel just happens to not implement those, so it's the closest thing we have to an option to disable them 

That's probably right.

**Comment by krzysz00** [comment]
Would like to record some progress notes:

https://github.com/krzysz00/iree-bug-18798-reproduction-harness is now a standalone reproduction harness for the bug

While trying to reduce the problem further, I discovered that removing all the `llvm.assume` stuff didn't affect the correctness of the generated code (it was still correct), but removing the addition of the Y and Z workitem IDs (which, per `!reqd_work_group_size` are always 0) *does* make the code work

Also, some debugging session a while back yielded that applying
```
diff --git a/llvm/lib/Target/AMDGPU/SIISelLowering.cpp b/llvm/lib/Target/AMDGPU/SIISelLowering.cpp
index bbdc006b9afc..dedaeb2fe34b 100644
--- a/llvm/lib/Target/AMDGPU/SIISelLowering.cpp
+++ b/llvm/lib/Target/AMDGPU/SIISelLowering.cpp
@@ -11932,6 +11932,7 @@ calculateSrcByte(const SDValue Op, uint64_t DestByte, uint64_t SrcIndex = 0,
static const std::optional<ByteProvider<SDValue>>
calculateByteProvider(const SDValue &Op, unsigned Index, unsigned Depth,
                       unsigned StartingIndex = 0) {
+                        return std::nullopt;
   // Finding Src tree of RHS of or typically requires at least 1 additional
   // depth
   if (Depth > 6)
```
would work around the issue

**Comment by krzysz00** [comment]
Another observation is that `load-store-vectorizer` isn't treating the two input arguments consistently for reasons that aren't clear to me

**Comment by krzysz00** [comment]
Further notes from operation "flail around wildly" - disabling (by patch) loop strength reduction causes the `load-store-vectorizer` equivalence classes to be the length-9 ones that're expected, which causes the bug to go away

So, it seems we have
1. Loop strength reduction doing *something* that confuses the vectorizer - but only when there're those additional adds
2. SelectionDAG choking on `<7 x i8>`

Could someone remind me the incantations for dumping out IR right before it gets selection-DAG'd? There might be two tickets here, it feels ilke

**Comment by arsenm** [comment]
-print-before=amdgpu-isel -print-module-scope. or -print-after one of the late passes, maybe amdgpu-late-codegenprepare

**Comment by jrbyrnes** [comment]
Those perms are coming from the v_dot combine -- this combine is probably responsible. At this point, not sure if the correctness issue is a result of bad perm masks or a bad attempt to match the signedness semantics with perm + v_dot

**Comment by qedawkins** [comment]
FWIW based on my own playing around with input values, using only unsigned inputs \in {1, 2} still reproduced the issue, so I would guess an issue with the perm is more likely than signedness semantics.

**Comment by qedawkins** [comment]
A few more notes in case they are useful. I'm finding that commenting out any of the following cases (i.e. return std::nullopt) fixes the error:

- https://github.com/llvm/llvm-project/blob/aa7941289ee5b7d9bdf47e1b0ebf2130a86d9522/llvm/lib/Target/AMDGPU/SIISelLowering.cpp#L11901
- https://github.com/llvm/llvm-project/blob/aa7941289ee5b7d9bdf47e1b0ebf2130a86d9522/llvm/lib/Target/AMDGPU/SIISelLowering.cpp#L12003
- https://github.com/llvm/llvm-project/blob/aa7941289ee5b7d9bdf47e1b0ebf2130a86d9522/llvm/lib/Target/AMDGPU/SIISelLowering.cpp#L12053-L12058
- https://github.com/llvm/llvm-project/blob/aa7941289ee5b7d9bdf47e1b0ebf2130a86d9522/llvm/lib/Target/AMDGPU/SIISelLowering.cpp#L12103

So this seems to confirm it is related to v_perm handling.

**Comment by jrbyrnes** [comment]
Sorry, looks like I made a typo.. @qedawkins can you please try changing `Src1.SrcOffset` -> `Src0.SrcOffset` here https://github.com/llvm/llvm-project/blob/304c41217303ce613de8f4042e570ac6ca8757e8/llvm/lib/Target/AMDGPU/SIISelLowering.cpp#L14014

**Comment by qedawkins** [comment]
> Sorry, looks like I made a typo.. @qedawkins can you please try changing `Src1.SrcOffset` -> `Src0.SrcOffset` here
> 
> https://github.com/llvm/llvm-project/blob/304c41217303ce613de8f4042e570ac6ca8757e8/llvm/lib/Target/AMDGPU/SIISelLowering.cpp#L14014
> 
> If this fixes your issue (which, according to my tests, it does), then issue should be resolved by #115224

Nice, that fixed it! Thanks much for the help 🎉

**Comment by arsenm** [comment]
> Another observation is that `load-store-vectorizer` isn't treating the two input arguments consistently for reasons that aren't clear to me

What do you mean by this? Should a new issue be opened for it?

**Comment by jrbyrnes** [comment]
> Another observation is that load-store-vectorizer isn't treating the two input arguments consistently for reasons that aren't clear to me

I did see that loop-strength-reduce was changing the accesses for one vector and not the other. This affected the behavior of lsv -- perhaps this is what you meant? By using flag --disable-lsr=1 we see more regular / consistent vector accesses.

**Comment by krzysz00** [comment]
Yeah, I do mean that loop-strength-reduce was only touching one of the vectors, and that this only seems to happen when there's those adds of Y and Z to the coordinated lane ID. That's probably a separate ticket, and a lower-priority one
