### ISSUE TITLE
Clang-Format: Sort include directives by letter, not by ASCII code

### ISSUE THREAD

**Issue by mmoderau** [llvm/llvm-project#113]
When sorting includes in a project, that mixes case styles for file names (for example both `PascalCase` and `snake_case`), it would be helpful to be able to sort alphabetically (case aware) instead of by character code.

*Currently*
```c++
#include <AClass.h>
#include <ThisIsADifferentClass.h>
#include <a_header_with_utility_functions.h>
```

*Expected*
```c++
#include <AClass.h>
#include <a_header_with_utility_functions.h>
#include <ThisIsADifferentClass.h>
```

**Comment by mkurdej** [comment]
The option `SortIncludes` gained `CaseInsensitive` some time ago (in v13). You might give it a try.
Cf. https://github.com/llvm/llvm-project/commit/a8105b3766e4195ca2390cd0714e07406bc8a4a5
