### ISSUE TITLE
problem with undefined characters while compiling on Ubuntu

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11304]
|  |  |
| --- | --- |
| Bugzilla Link | [10932](https://llvm.org/bz10932) |
| Version | 2.9 |
| OS | Linux |
| Attachments | [problem with undefined characters](https://user-images.githubusercontent.com/60944935/143743887-e32238fa-c7ba-4fed-8999-8481a7d8f7c6.gz), [problem with using -ftol](https://user-images.githubusercontent.com/60944935/143743888-1bb5b920-b94f-4765-bcf8-192ccbbd2cb9.gz), [my scons files](https://user-images.githubusercontent.com/60944935/143743889-c94b1f44-9640-40af-9d21-3a1fce771e0d.gz), [llvm python](https://user-images.githubusercontent.com/60944935/143743890-ff6e5c86-7656-4649-8dbf-a0cf6e851f71.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Hello.

Sorry if I disturb you, but I am having one problem with compiling on Ubuntu 11.10 beta. 

I am using GCC-4.6.1-9ubuntu2, LLVM 2.8.6 and scons 2.0.1-r5134 version (I downloaded all that from Ubuntu Software Center).
While compiling IDTech3 based game I have met with quiet unusual problem for me

I will uploaded files with problems and my scons files what I am using at moment of error.

**Comment by arsenm** [comment]
Old build issue
