### ISSUE TITLE
The latest version of LLVM clang-format crashes.

### ISSUE THREAD

**Issue by cheblin** [llvm/llvm-project#113011]
D:\AdHocTMP\AdhocProtocol DEPLOY in place>clang-format -i -style="{ColumnLimit: 0,IndentWidth: 4,  TabWidth: 4,  UseTab: Never,  BreakBeforeBraces: Allman,  IndentCaseLabels: true,  SpacesInLineCommentPrefix: {Minimum: 0, Maximum: 0}}" "D:\AdHocTMP\AdhocProtocol DEPLOY in place\AdhocProtocol\InCS\LayoutFile\gen\LayoutFile.cs"
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: clang-format -i "-style={ColumnLimit: 0,IndentWidth: 4,  TabWidth: 4,  UseTab: Never,  BreakBeforeBraces: Allman,  IndentCaseLabels: true,  SpacesInLineCommentPrefix: {Minimum: 0, Maximum: 0}}" "D:\\AdHocTMP\\AdhocProtocol DEPLOY in place\\AdhocProtocol\\InCS\\LayoutFile\\gen\\LayoutFile.cs"
Exception Code: 0xC0000005
 #0 0x00007ff7bb6a175d (C:\Program Files\LLVM\bin\clang-format.exe+0xd175d)
 #1 0x00007ff7bb69b0b4 (C:\Program Files\LLVM\bin\clang-format.exe+0xcb0b4)
 #2 0x00007ff7bb6a2f3c (C:\Program Files\LLVM\bin\clang-format.exe+0xd2f3c)
 #3 0x00007ff7bb69f966 (C:\Program Files\LLVM\bin\clang-format.exe+0xcf966)
 #4 0x00007ff7bb69a35c (C:\Program Files\LLVM\bin\clang-format.exe+0xca35c)
 #5 0x00007ff7bb6a0696 (C:\Program Files\LLVM\bin\clang-format.exe+0xd0696)
 #6 0x00007ff7bb69b407 (C:\Program Files\LLVM\bin\clang-format.exe+0xcb407)
 #7 0x00007ff7bb6a2f3c (C:\Program Files\LLVM\bin\clang-format.exe+0xd2f3c)
 #8 0x00007ff7bb69f966 (C:\Program Files\LLVM\bin\clang-format.exe+0xcf966)
 #9 0x00007ff7bb69a35c (C:\Program Files\LLVM\bin\clang-format.exe+0xca35c)
#10 0x00007ff7bb6a0696 (C:\Program Files\LLVM\bin\clang-format.exe+0xd0696)
#11 0x00007ff7bb69b407 (C:\Program Files\LLVM\bin\clang-format.exe+0xcb407)
#12 0x00007ff7bb6a2f3c (C:\Program Files\LLVM\bin\clang-format.exe+0xd2f3c)
#13 0x00007ff7bb69f966 (C:\Program Files\LLVM\bin\clang-format.exe+0xcf966)
#14 0x00007ff7bb69a35c (C:\Program Files\LLVM\bin\clang-format.exe+0xca35c)
#15 0x00007ff7bb6a0696 (C:\Program Files\LLVM\bin\clang-format.exe+0xd0696)
#16 0x00007ff7bb69b407 (C:\Program Files\LLVM\bin\clang-format.exe+0xcb407)
#17 0x00007ff7bb6a2f3c (C:\Program Files\LLVM\bin\clang-format.exe+0xd2f3c)
#18 0x00007ff7bb69f966 (C:\Program Files\LLVM\bin\clang-format.exe+0xcf966)
#19 0x00007ff7bb69a35c (C:\Program Files\LLVM\bin\clang-format.exe+0xca35c)
#20 0x00007ff7bb6a0696 (C:\Program Files\LLVM\bin\clang-format.exe+0xd0696)
#21 0x00007ff7bb69b407 (C:\Program Files\LLVM\bin\clang-format.exe+0xcb407)
#22 0x00007ff7bb6993a6 (C:\Program Files\LLVM\bin\clang-format.exe+0xc93a6)
#23 0x00007ff7bb6999a2 (C:\Program Files\LLVM\bin\clang-format.exe+0xc99a2)
#24 0x00007ff7bb6a0460 (C:\Program Files\LLVM\bin\clang-format.exe+0xd0460)
#25 0x00007ff7bb6a2f3c (C:\Program Files\LLVM\bin\clang-format.exe+0xd2f3c)
#26 0x00007ff7bb6a31f5 (C:\Program Files\LLVM\bin\clang-format.exe+0xd31f5)
#27 0x00007ff7bb6993a6 (C:\Program Files\LLVM\bin\clang-format.exe+0xc93a6)
#28 0x00007ff7bb6999a2 (C:\Program Files\LLVM\bin\clang-format.exe+0xc99a2)
#29 0x00007ff7bb69bd9a (C:\Program Files\LLVM\bin\clang-format.exe+0xcbd9a)
#30 0x00007ff7bb6993a6 (C:\Program Files\LLVM\bin\clang-format.exe+0xc93a6)
#31 0x00007ff7bb6999a2 (C:\Program Files\LLVM\bin\clang-format.exe+0xc99a2)
#32 0x00007ff7bb6a261e (C:\Program Files\LLVM\bin\clang-format.exe+0xd261e)
#33 0x00007ff7bb69b20a (C:\Program Files\LLVM\bin\clang-format.exe+0xcb20a)
#34 0x00007ff7bb6993a6 (C:\Program Files\LLVM\bin\clang-format.exe+0xc93a6)
#35 0x00007ff7bb6999a2 (C:\Program Files\LLVM\bin\clang-format.exe+0xc99a2)
#36 0x00007ff7bb6a018e (C:\Program Files\LLVM\bin\clang-format.exe+0xd018e)
#37 0x00007ff7bb6993a6 (C:\Program Files\LLVM\bin\clang-format.exe+0xc93a6)
#38 0x00007ff7bb6999a2 (C:\Program Files\LLVM\bin\clang-format.exe+0xc99a2)
#39 0x00007ff7bb6a018e (C:\Program Files\LLVM\bin\clang-format.exe+0xd018e)
#40 0x00007ff7bb6993a6 (C:\Program Files\LLVM\bin\clang-format.exe+0xc93a6)
#41 0x00007ff7bb69851b (C:\Program Files\LLVM\bin\clang-format.exe+0xc851b)
#42 0x00007ff7bb697828 (C:\Program Files\LLVM\bin\clang-format.exe+0xc7828)
#43 0x00007ff7bb654930 (C:\Program Files\LLVM\bin\clang-format.exe+0x84930)
#44 0x00007ff7bb647a34 (C:\Program Files\LLVM\bin\clang-format.exe+0x77a34)
#45 0x00007ff7bb62e8bf (C:\Program Files\LLVM\bin\clang-format.exe+0x5e8bf)
#46 0x00007ff7bb6329eb (C:\Program Files\LLVM\bin\clang-format.exe+0x629eb)
#47 0x00007ff7bb61bec5 (C:\Program Files\LLVM\bin\clang-format.exe+0x4bec5)
#48 0x00007ff7bb619549 (C:\Program Files\LLVM\bin\clang-format.exe+0x49549)
#49 0x00007ff7bb7186f0 (C:\Program Files\LLVM\bin\clang-format.exe+0x1486f0)
#50 0x00007ffdc5fd257d (C:\Windows\System32\KERNEL32.DLL+0x1257d)
#51 0x00007ffdc738af08 (C:\Windows\SYSTEM32\ntdll.dll+0x5af08)
[LayoutFile.zip](https://github.com/user-attachments/files/17441890/LayoutFile.zip)

D

**Comment by EugeneZelenko** [comment]
Could you please provide reproducer?
