### ISSUE TITLE
 [feature-request] [clang-format] Preserve the form feed character (^L, 0xC, \f)

### ISSUE THREAD

**Issue by Gleefre** [llvm/llvm-project#113170]
The form feed character is often used to divide programs into logical blocks. When placed alone on a line, it acts as a logical page break, which can be used by text editors for efficient navigation and various display features. For example, Emacs has commands like `narrow-to-page` and `forward-page` / `backward-page`, and Vim also recognizes the ^L markers for navigation. Additionally, various IDE extensions provide similar functionality.

Although formfeeds are mostly used in lisp code, they also can be found in C/C++ code. Here's a quote from the [GNU coding standards](https://www.gnu.org/prep/standards/standards.html#index-formfeed) (gcc's code style):
> Please use formfeed characters (control-L) to divide the program into pages at logical places (but not within a function). It does not matter just how long the pages are, since they do not have to fit on a printed page. The formfeeds should appear alone on lines by themselves. 

Currently, `clang-format` removes form feed characters that appear alone on a line, and to my knowledge there is no option to disable this behavior. It would be great either if formfeeds were always preserved or if there was an configuration option to control that.

**Comment by owenca** [comment]
Here is what the new option would do:
```
--- a/clang/include/clang/Format/Format.h
+++ b/clang/include/clang/Format/Format.h
@@ -3207,6 +3207,13 @@ struct FormatStyle {
   /// \version 3.7
   // bool KeepEmptyLinesAtTheStartOfBlocks;
 
+  /// Keep the form feed character if it's immediately preceded and followed by
+  /// a newline. Multiple form feeds and newlines within a whitespace range are
+  /// replaced with a single newline and form feed followed by the remaining
+  /// newlines.
+  /// \version 20
+  bool KeepFormFeed;
+
   /// Indentation logic for lambda bodies.
   enum LambdaBodyIndentationKind : int8_t {
     /// Align lambda body relative to the lambda signature. This is the default.

```

**Comment by Gleefre** [comment]
That would be great, thanks!
