### ISSUE TITLE
Wrong canonicalization of a range check idiom

### ISSUE THREAD

**Issue by bongjunj** [llvm/llvm-project#113123]
https://github.com/llvm/llvm-project/blob/11dad2fa5138a50d60a5a34a2c7e074b976820e2/llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp#L1511-L1527

Alive2 report: https://alive2.llvm.org/ce/z/2b7VR2

```llvm
----------------------------------------
define i1 @test_and_olt_fmf_propagation_union.2(float %x) {
#0:
  %cmp1 = fcmp nnan ninf olt float %x, 0.000000
  %cmp2 = fcmp nnan nsz ogt float %x, -0.000000
  %#1 = select i1 %cmp2, i1 %cmp1, i1 %cmp2
  %cond = and i1 %#1, %cmp2
  ret i1 %cond
}
=>
define i1 @test_and_olt_fmf_propagation_union.2(float %x) {
#0:
  %#1 = fabs nnan ninf nsz float %x
  %#2 = fcmp nnan ninf nsz olt float %#1, 0.000000
  ret i1 %#2
}
Transformation doesn't verify!

ERROR: Target is more poisonous than source

Example:
float %x = #xff800000 (-oo)

Source:
i1 %cmp1 = poison
i1 %cmp2 = #x0 (0)
i1 %#1 = #x0 (0)
i1 %cond = #x0 (0)

Target:
float %#1 = poison
i1 %#2 = poison
Source value: #x0 (0)
Target value: poison

Summary:
  0 correct transformations
  1 incorrect transformations
  0 failed-to-prove transformations
  0 Alive2 errors
```

**Comment by XChy** [comment]
Thanks for the report.

We preserve `ninf` flag from `cmp1` when folding logical and `select cmp2, cmp1, false` into `fcmp ninf (fabs(x))`. But if `cmp2` equals to `false`, the select won't be poison whatever `cmp1` is. Thus, such fold makes it more poisonous. See https://alive2.llvm.org/ce/z/hnqeLC

**Comment by XChy** [comment]
And it looks like you are mutating the unit tests to fuzz LLVM. Looks interesting to me. If OK, could you provide some information about it?

**Comment by bongjunj** [comment]
> And it looks like you are mutating the unit tests to fuzz LLVM. Looks interesting to me. If OK, could you provide some information about it?

@XChy Yes we are designing a fuzzer on top of LLVM to test the compiler. We can't disclose the full detail at this time. Thank you.
