### ISSUE TITLE
Why remove support for old llvm.amdgcn.buffer.* intrinsics?

### ISSUE THREAD

**Issue by mrxia1216** [llvm/llvm-project#113250]
Why remove llvm.amdgcn.buffer.* intrinsics？Is using llvm.amdgcn.raw.buffer. and llvm.amdgcn.struct.buffer.* intrinsics more complex?（https://github.com/llvm/llvm-project/pull/93838/files）

**Comment by arsenm** [comment]
The main issue with the old intrinsics was the backend can't correctly make use of the addressing modes. The clamping and bounds check behavior requires the producer to know the context of the resource descriptor for what to use for the SGPR unswizzled and VGPR offset

Additionally, the vector is not a good representation for the fat pointer (as it is not a pointer). The llvm.amdgcn.struct.ptr.buffer* and llvm.amdgcn.raw.ptr.buffer* intrinsics should be preferred now over the versions using the vector.

**Comment by arsenm** [comment]
Does this answer your question? In any case we're not going to bring them back and you should migrate to using the structured intrinsics with pointers
