### ISSUE TITLE
Incorrect DCE with `fvirtual-function-elimination fvisibility=hidden` 

### ISSUE THREAD

**Issue by Umesh-k26** [llvm/llvm-project#113286]
Reproducer: 
```
// RUN: clang++ -O1 -flto -fvirtual-function-elimination -fvisibility=hidden %s
#include <stdio.h>

class MyClass {
public:
    virtual int foo(int e) {
        return 42+e;
    }
};

int main() {
    MyClass c;
    using casted_foo_t = int (MyClass::*)(long);
    auto casted_foo = (casted_foo_t)&MyClass::foo;
    printf("%d\n", (c.*casted_foo)(2));
}
```

Output:
`Segmentation fault (core dumped)`

The type metadata node for `foo`  ( !"_ZTSM7MyClassFiiE.virtual" ) and `casted_foo_t` ( !"_ZTSM7MyClassFilE.virtual" ) is different. 
In GlobalDCE, these callsites are analyzed only with type metadata, and address taken here is not captured. 

`GlobalStatus` might not help here, as the virtual-function's use-list only contains vtables.

**Comment by HerrCai0907** [comment]
It looks like a UB in CPP.
https://timsong-cpp.github.io/cppwp/n4861/expr.call#6
> Calling a function through an expression whose function type is different from the function type of the called function's definition results in undefined behavior[.](https://timsong-cpp.github.io/cppwp/n4861/expr.call#6.sentence-1)
