### ISSUE TITLE
[AArch64][SVE][Question] incorrect fold of SVE's svwhilele?

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#113244]
The following test case is taken from gcc bugzilla.
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=117045.

```cpp
#include <arm_sve.h>
#include <limits.h>
svbool_t f() { return svwhilele_b8_s32(INT_MAX, INT_MAX); }
```
https://godbolt.org/z/vecxznE48

Gcc:
```asm
f():
        ptrue   p0.b, all
        ret
```

Clang:
```asm
f():
        ptrue   p0.b, vl1
        ret
```

If bugzilla's comment is correct, clang's code is incorrect. I'm not sure if clang is wrong, but can someone check this?

**Comment by fhahn** [comment]
cc @paulwalker-arm @sdesmalen-arm

**Comment by sdesmalen-arm** [comment]
It seems like #111183 addresses this.

**Comment by k-arrows** [comment]
Thank you for your information. I will close this issue.
