### ISSUE TITLE
Sanitizers unblock user blocked signals

### ISSUE THREAD

**Issue by vitalybuka** [llvm/llvm-project#113385]
Regression after #98200

**Comment by vitalybuka** [comment]
We need to get the gurrent procmask and check sigismember before each sigdelset.

**Comment by thevar1able** [comment]
@thurstond Could you please point me to a "revert revert" commit, or reopen this issue?

**Comment by thurstond** [comment]
> @vitalybuka @thurstond Could you please point me to a "revert revert" commit, or reopen this issue?

Sorry, reopened. I didn't realize the revert didn't do that automatically.

**Comment by thurstond** [comment]
Landed https://github.com/llvm/llvm-project/pull/115790, hopefully the change will stick this time 🤞

**Comment by thevar1able** [comment]
Thank you! Sorry I'm not familiar with the release process, does it require a backport to be included in 19.1.4?

**Comment by thurstond** [comment]
> @thurstond Thank you! Sorry I'm not familiar with the release process, does it require a backport to be included in 19.1.4?

Yes. I'll kick off the backport in a few days, to give time for the buildbots to surface any issues with the patch in head.
