### ISSUE TITLE
No i386 packages in APT repository for Debian for LLVM 19

### ISSUE THREAD

**Issue by serhii-nakon** [llvm/llvm-project#113438]
In this repositories no LLVM 19 packages for i386 architecture at all

https://apt.llvm.org/bookworm/pool/main/l/llvm-toolchain-19/
https://apt.llvm.org/buster/pool/main/l/llvm-toolchain-19/
https://apt.llvm.org/bullseye/pool/main/l/llvm-toolchain-19/

**Comment by serhii-nakon** [comment]
@sylvestre Thank you, it work now. I will close it. Also I want to ask you does LLVM still should allow to install i386 and amd64 packages at the same time? Because in both packages libLLVM is on this path `/usr/lib/llvm-19/lib/libLLVM.so.1` - so it like override each other

**Comment by sylvestre** [comment]
welcome. it should work, please submit a new bug if it isn't the case :)
