### ISSUE TITLE
trunk llvm (r140196) fails to build for linux/ppc

### ISSUE THREAD

**Issue by 0e6f8740-1d2a-4afc-85fd-df25c3a603fd** [llvm/llvm-project#11341]
|  |  |
| --- | --- |
| Bugzilla Link | [10969](https://llvm.org/bz10969) |
| Version | trunk |
| OS | Linux |
| Attachments | [PPCAsmPrinter.pp.c.bz2](https://user-images.githubusercontent.com/92601458/143743919-8335af9b-31da-4f5a-95dd-176052b6aefc.gz) |
| CC | @efriedma-quic |

## Extended Description 
if  g++ -I/home/jeremy/src/llvm/build.ppc/include -I/home/jeremy/src/llvm/build.ppc/lib/Target/PowerPC -I/home/jeremy/src/llvm/include -I/home/jeremy/src/llvm/lib/Target/PowerPC  -D_DEBUG -D_GNU_SOURCE -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -O3 -fomit-frame-pointer -g -fno-exceptions -fno-rtti -fPIC -Woverloaded-virtual -Wcast-qual    -pedantic -Wno-long-long -Wall -W -Wno-unused-parameter -Wwrite-strings  -c -MMD -MP -MF "/home/jeremy/src/llvm/build.ppc/lib/Target/PowerPC/Release+Debug+Asserts/PPCAsmPrinter.d.tmp" -MT "/home/jeremy/src/llvm/build.ppc/lib/Target/PowerPC/Release+Debug+Asserts/PPCAsmPrinter.o" -MT "/home/jeremy/src/llvm/build.ppc/lib/Target/PowerPC/Release+Debug+Asserts/PPCAsmPrinter.d" /home/jeremy/src/llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp -o /home/jeremy/src/llvm/build.ppc/lib/Target/PowerPC/Release+Debug+Asserts/PPCAsmPrinter.o ; \
	        then /bin/mv -f "/home/jeremy/src/llvm/build.ppc/lib/Target/PowerPC/Release+Debug+Asserts/PPCAsmPrinter.d.tmp" "/home/jeremy/src/llvm/build.ppc/lib/Target/PowerPC/Release+Debug+Asserts/PPCAsmPrinter.d"; else /bin/rm "/home/jeremy/src/llvm/build.ppc/lib/Target/PowerPC/Release+Debug+Asserts/PPCAsmPrinter.d.tmp"; exit 1; fi
In file included from /home/jeremy/src/llvm/lib/Target/PowerPC/MCTargetDesc/PPCMCTargetDesc.h:41:0,
                 from /home/jeremy/src/llvm/lib/Target/PowerPC/MCTargetDesc/PPCBaseInfo.h:20,
                 from /home/jeremy/src/llvm/lib/Target/PowerPC/PPC.h:18,
                 from /home/jeremy/src/llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp:20:
/home/jeremy/src/llvm/build.ppc/lib/Target/PowerPC/PPCGenRegisterInfo.inc:17:11: error: expected identifier before numeric constant
/home/jeremy/src/llvm/build.ppc/lib/Target/PowerPC/PPCGenRegisterInfo.inc:17:11: error: expected unqualified-id before numeric constant
In file included from /usr/include/c++/4.5/new:42:0,
                 from /usr/include/c++/4.5/ext/new_allocator.h:33,
                 from /usr/include/c++/4.5/powerpc-linux-gnu/bits/c++allocator.h:34,
                 from /usr/include/c++/4.5/bits/allocator.h:48,
                 from /usr/include/c++/4.5/string:43,
                 from /home/jeremy/src/llvm/include/llvm/ADT/StringRef.h:16,
                 from /home/jeremy/src/llvm/include/llvm/Support/ErrorHandling.h:19,
                 from /home/jeremy/src/llvm/lib/Target/PowerPC/MCTargetDesc/PPCBaseInfo.h:21,
                 from /home/jeremy/src/llvm/lib/Target/PowerPC/PPC.h:18,
                 from /home/jeremy/src/llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp:20:
/usr/include/c++/4.5/exception:37:37: error: expected ‘}’ before end of line
/usr/include/c++/4.5/exception:37:37: error: expected declaration before end of line
/bin/rm: cannot remove `/home/jeremy/src/llvm/build.ppc/lib/Target/PowerPC/Release+Debug+Asserts/PPCAsmPrinter.d.tmp': No such file or directory

preprocessed source attached.

**Comment by arsenm** [comment]
Old build issue
