### ISSUE TITLE
[LLD] lld does not parse options for orphan-handling in a case insensitive manner.

### ISSUE THREAD

**Issue by quic-rb10** [llvm/llvm-project#113444]
Currently LLD does not parse options for orphan handling in a case insensitive manner.

The command:
`ld.lld 1.o -orphan-handling=Error -T script.t`
returns an error: `ld.lld: error: unknown --orphan-handling mode: Error`

However, GCC supports case insensitive parsing for `-orphan-handling` options and the above command works normally.

We should support case insensitive parsing in lld; this would help improve compatibility with GNU ld.

**Comment by MaskRay** [comment]
Thanks for reporting this difference. It looks like --orphan-handling in binutils is special in that it is case insensitive. Other options taking a string argument are all(?) case sensitive, e.g. `--unresolved-symbols=`. I don't think `=Error` is used widely. Actually, `warn`/`error`/`discard` are almost exclusively used in the wild.

Therefore, I don't think we should change lld code.
