### ISSUE TITLE
We should remove links to the IRC channel from the website

### ISSUE THREAD

**Issue by kbeyls** [llvm/llvm-project#113484]
There are very few people still using the IRC LLVM channel.
It seems that when newcomers/people do ask questions on the IRC channels, we don't have "critical mass" anymore to get a significant part of them answered.
That results in a poor experience.

We should remove links advertising the IRC channel as a place for people to ask questions about LLVM.

@AaronBallman

**Comment by AaronBallman** [comment]
As much as it pains me to drop IRC as an official channel, I think it's time. There's just not enough of the community around to help out. The channel itself can stay open and folks can continue to use it as they see fit, but we shouldn't advertise it any longer on the LLVM site.

**Comment by AaronBallman** [comment]
This has been addressed in 0ab44fd2464354dfdca0e7afacbb21a84bca46d9
