### ISSUE TITLE
[openmp][test] The `gtid.cpp` test case fails when OpenMP has been built with `-DLIBOMP_ENABLE_SHARED=False`

### ISSUE THREAD

**Issue by pawosm-arm** [llvm/llvm-project#113436]
With OpenMP built with the `-DLIBOMP_ENABLE_SHARED=False` CMake flag, the `openmp/runtime/test/tasking/hidden_helper_task/gtid.cpp` test case is failing as the linker complains that the `__kmp_hidden_helper_threads_num` symbol is defined in both `libomp.a` and `gtid.cpp`. In `gtid.cpp` it is defined globally as such:

```
kmp_int32 __kmp_hidden_helper_threads_num;
```

There is one more test case which also defines `kmp_int32 __kmp_hidden_helper_threads_num`, it is the `openmp/runtime/test/worksharing/for/kmp_sch_simd_guided.c` test case and it defines it as such:

```
static int __kmp_hidden_helper_threads_num = 0;
```

Shouldn't it be `static` in the `gtid.cpp` test case too?

**Comment by shiltian** [comment]
@TerryLWilmarth Do we really have to support building `libomp` as a static library?

**Comment by pawosm-arm** [comment]
I have a debugger test suite which builds with and without `-static`, the only way to make it work is to have `libomp.a`.

**Comment by TerryLWilmarth** [comment]
Hi Shilei,
Yeah, it's strongly discouraged, but there are still people who need it, so we continue to support it, but only on Linux these days.  Here are a couple of cases:
https://discourse.llvm.org/t/building-a-static-llvm-openmp-library/39629
https://discourse.llvm.org/t/building-a-static-library-of-openmp/51606

**Comment by pawosm-arm** [comment]
A somewhat more general question, is this test case correct with defining this variable global without `static`?

**Comment by TerryLWilmarth** [comment]
For this bug, the test should just rename that variable to something without the __kmp_* prefix. The __kmp, __kmpc, kmp, pseudo-namespaces are meant for the Intel and LLVM OpenMP runtime.

**Comment by pawosm-arm** [comment]
Thank you @shiltian
