### ISSUE TITLE
fmtlib compilation fails (consteval) on clang main branch

### ISSUE THREAD

**Issue by kamrann** [llvm/llvm-project#113517]
https://godbolt.org/z/bf5MeK3TW

It's not entirely clear since this issue does not show up if using `fmtlib` `master` branch, but only on the latest 11.0.2 release. However, since 11.0.2 builds fine with MSVC, GCC and Clang 19, it suggests a probable regression.

**Comment by tbaederr** [comment]
The error doesn't ring a bell here. Can you provide the preprocessed sources for that file?

The only thing that comes to mind is the string literal change, wasn't there a problem in fmtlib that got fixed in their master branch, @zygoloid?

**Comment by kamrann** [comment]
> Can you provide the preprocessed sources for that file?

For `fmt`? I just added `-E` to the CE invocation and [pasted the output back into the input](https://godbolt.org/z/7WGfPxsv3). If you meant something else, let me know.

**Comment by zygoloid** [comment]
This was [a bug in `fmtlib`](https://github.com/fmtlib/fmt/issues/4177) that's fixed in their trunk, combined with all compilers previously being overly permissive in repeated constant evaluation of string literals.

**Comment by kamrann** [comment]
Understood, sorry for the false report then. I searched on `fmtlib` initially but missed that issue somehow.

**Comment by zygoloid** [comment]
No worries, thanks for reporting!
