### ISSUE TITLE
[Clang] Accessing a reference member of a volatile-qualified class glvalue is misinterpreted as volatile read

### ISSUE THREAD

**Issue by frederick-vs-ja** [llvm/llvm-project#113530]
Tracked in [CWG2957](https://cplusplus.github.io/CWG/issues/2957.html).

----

Currently, Clang (and GCC) rejects the following example ([link](https://godbolt.org/z/v9fKKEaGW)), which doesn't seem conforming.

Possible wrong example:
```C++
struct S { const int& ref; };
constexpr int n = 42;

template<class T>
constexpr int readref(T&& t) {
  return static_cast<T&&>(t).ref;
}

static_assert(::readref(static_cast<volatile S&&>(S{n})) == 42, "");
```

Error messages:
```
<source>:9:15: error: static assertion expression is not an integral constant expression
    9 | static_assert(::readref(static_cast<volatile S&&>(S{n})) == 42, "");
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:6:30: note: read of volatile temporary is not allowed in a constant expression
    6 |   return static_cast<T&&>(t).ref;
      |                              ^
<source>:9:15: note: in call to 'readref<volatile S>(S{n})'
    9 | static_assert(::readref(static_cast<volatile S&&>(S{n})) == 42, "");
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:9:51: note: volatile temporary created here
    9 | static_assert(::readref(static_cast<volatile S&&>(S{n})) == 42, "");
      |                                                   ^
1 error generated.
Compiler returned: 1
```

I think the relevant standard wording is [[expr.const]/5.9](https://eel.is/c++draft/expr.const#5.9):

> an lvalue-to-rvalue conversion unless it is applied to
> - a non-volatile glvalue that refers to an object that is usable in constant expressions, or
> - a non-volatile glvalue of literal type that refers to a non-volatile object whose lifetime began within the evaluation of _E_;

However, there doesn't seem any wording treating evaluating a reference non-static data member of a class object as lvalue-to-rvalue conversion. So perhaps this example should be well-formed.
(A reference member behaves like it were an "auto-dereferencing" pointer in many cases. But IIUC this example is not such a case.)

----
[Another example](https://godbolt.org/z/3qejKMbTW):
```C++
struct S { const int& ref; };
constexpr int n = 42;
constexpr volatile S s{n};

static_assert(s.ref == 42, "");
```

**Comment by efriedma-quic** [comment]
Under your interpretation, the following should also be accepted.

```
struct A { int &x; A(int&); };
int main() {
  int x = 3;
  A xx = {x};
  constexpr bool c = &xx.x == &x;
}
```

That's impossible to evaluate, so the missing wording is pretty clearly an oversight.

**Comment by frederick-vs-ja** [comment]
> Under your interpretation, the following should also be accepted.
> 
> ```
> struct A { int &x; A(int&); };
> int main() {
>   int x = 3;
>   A xx = {x};
>   constexpr bool c = &xx.x == &x;
> }
> ```
> 
> That's impossible to evaluate, so the missing wording is pretty clearly an oversight in the standard.

Thanks. I've realized that in this original example the temporary object (of `volatile S` type due to reference binding) is just not usable in constant expressions. The wording issue seems to be that too many aspects of the "unspecified object" (introduced in [P2280R4](https://wg21.link/p2280r4)) are underspecified.

There's already cplusplus/CWG#340 for this, although it's not yet made into a formal CWG issue.

---
But the following example (accidently) has the [same effects](https://godbolt.org/z/3qejKMbTW):

```C++
struct S { const int& ref; };
constexpr int n = 42;
constexpr volatile S s{n};

static_assert(s.ref == 42, "");
```

In this example there's no unspecified object - `s` and `s.ref` should be usable in constant expressions per [[expr.const]/3](https://eel.is/c++draft/expr.const#3) and [[expr.const]/4](https://eel.is/c++draft/expr.const#4).

**Comment by zygoloid** [comment]
I think we should ask CWG if naming a member reference in a volatile object qualifies as a volatile access (in codegen and in constant evaluation). It seems like it probably should.

**Comment by frederick-vs-ja** [comment]
Closing as there's now [CWG2957](https://cplusplus.github.io/CWG/issues/2957.html).
