### ISSUE TITLE
[clang-tidy] Crash when turn on the modernize-use-designated-initializers check.

### ISSUE THREAD

**Issue by lingege321** [llvm/llvm-project#113652]
I am using clangd and get the crash when turn on the modernize-use-designated-initializers check.
The code segment is like following.
The Crash is a forward declaration.

```
struct Crash;

struct Der{
  Der(Crash& d):d{d}{}
  Crash& d;
};
```

**Comment by chrchr-github** [comment]
https://godbolt.org/z/396azx6Yr

**Comment by lingege321** [comment]
@chrchr-github 
Hi it's a clang-tidy issue.
Not a clang compiler issue.
The crash is happened when using clang-tidy.
