### ISSUE TITLE
[clang] call to non-constexpr function should be supported

### ISSUE THREAD

**Issue by lingege321** [llvm/llvm-project#113656]
I have the following code segment.
[GodBolt](https://godbolt.org/z/qnv7vf31e)
``` cpp
bool foo1(int b) {
    return b==1;
}


constexpr bool foo2(int b) {
    return foo1(b-5);
}

int main() {

}
```

If I use g++ to compile it. G++ will error out the message 'error: call to non-‘constexpr’ function ‘bool foo1(int)’'
Visual Studio also errors out the same error.

Only clang does not support this error and I cannot early detect the error in clangd.

Is it possible to print the same compile error as gcc?

gcc version:
gcc (GCC) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

clang version:
clang version 19.1.2 (https://github.com/llvm/llvm-project.git 7ba7d8e2f7b6445b60679da826210cdde29eaf8b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /remote/vgrnd106/chielin/local/llvm/llvm-project-19.1.2/build/bin

**Comment by frederick-vs-ja** [comment]
FYI, Clang used to diagnose this in 11, but stopped since 12 ([Godbolt link](https://godbolt.org/z/E3GoGh4qP)).

**Comment by lingege321** [comment]
Hi @keinflue 
Thanks for your information, it's very clear.
it's warning in gcc14 and the warning is disabled in -std=c++23 like you say.

@frederick-vs-ja 
Thank for your information! 
It's helpful for me.
