### ISSUE TITLE
[libc++][test] Non-rebindable `test_alloc` in string.capacity/deallocate_size.pass.cpp

### ISSUE THREAD

**Issue by StephanTLavavej** [llvm/llvm-project#113609]
This `test_alloc` has a `rebind` struct, but not a rebinding constructor:

https://github.com/llvm/llvm-project/blob/564fd62aedfde6358baa1776a2de975b45bc7778/libcxx/test/std/strings/basic.string/string.capacity/deallocate_size.pass.cpp#L22-L46

This fails to meet the allocator requirements. MSVC's STL rejects this because we attempt to rebind the allocator (to an internal "container proxy" type).

I observe other requirement deficiencies here (no comparison operators) but the rebinding one is the specific problem for us.

**Comment by frederick-vs-ja** [comment]
When attempting to fix this, I realized that MSVC STL's "container proxy" objects can make `allocated_` have different values when they are present... I wish `assert(allocated_ == 0 || allocated_ >= i)` passes as the "different value" should be larger than normal.
