### ISSUE TITLE
[AVX] Cannot select ch = Prefetch

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11366]
|  |  |
| --- | --- |
| Bugzilla Link | [10994](https://llvm.org/bz10994) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @bcardosolopes |

## Extended Description 
revision: 140371

x86/AVX backend segfaults for following LLVM IR including llvm.prefetch().

$ llc -mavx bugpoint-reduces-simplified.bc
LLVM ERROR: Cannot select: 0x101832410: ch = Prefetch 0x10110bae8, 0x101832010, 0x101832110, 0x101832210, 0x101832310<LD1[undef]> [ID=9]
  0x101832010: i64 = undef [ID=1]
  0x101832110: i32 = Constant<0> [ID=2]
  0x101832210: i32 = Constant<2> [ID=3]
  0x101832310: i32 = Constant<1> [ID=4]

$ cat bugpoint-reduced-simplified.ll 
; ModuleID = 'bugpoint-reduced-simplified.bc'
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64"
target triple = "x86_64-apple-macosx10.6.8"
define void @&#8203;_ZNK6embree13ObjectBinningILi2EE5splitEPNS_4BBoxINS_4ssefEEERS1_S6_() uwtable ssp align 2 {
entry:
  call void @&#8203;llvm.prefetch(i8* undef, i32 0, i32 2, i32 1) nounwind
  br i1 undef, label %cond.true.i, label %_ZN6embree4sseiixEm.exit

cond.true.i:                                      ; preds = %entry
  unreachable

_ZN6embree4sseiixEm.exit:                         ; preds = %entry
  unreachable
}

**Comment by arsenm** [comment]
Works fine now
