### ISSUE TITLE
[clang] __attribute__((__noreturn__)) miscompile

### ISSUE THREAD

**Issue by ZijunZhaoCCK** [llvm/llvm-project#113747]
`__attribute__((__noreturn__))` is miscompiled upstream.
See https://godbolt.org/z/T6nMoa75G from Miguel Young and his comment.

```
When using the standard [[noreturn]] and _Noreturn in their respective languages, codegen is identical, and correct. The C codegen is obviously wrong and clearly confusing the hell out of LLVM, as evidenced by this instruction sequence:

    jne     .LBB1_1
    mov     rax, qword ptr [rip + baz@GOTPCREL]
    call    rax
.LBB1_1: mov rax, qword ptr [rip + foo@GOTPCREL] call rax

(Just do call foo@PLT?)

My recommendation is that upstream use _Noreturn, or noreturn + <stdnoreturn.h>. Clang is clearly able to get this right, but somehow left hand isn't talking to right hand in the unification algorithm.

(This really isn't a C v. C++ difference at all; both languages define their standard noreturn primitives identically.)
```

**Comment by dzaima** [comment]
I think the "clang (trunk)" version looks fine? Have to go back to clang 15 to see an issue. Perhaps an easier-to-understand test: https://godbolt.org/z/qvW3xs3dM - showing the presence of the full post-return instruction sequence for `foo` for all 4 cases.

The weirdness of separated load and call appears to be from the conditional select being converted to a branch too late.

**Comment by efriedma-quic** [comment]
Yes, I don't think there's anything to do here. (Unless you want to file a bug for the missed optimization of turning the indirect call into a direct call.)
