### ISSUE TITLE
Clang + -fms-extensions: __FUNCSIG__ is not a literal

### ISSUE THREAD

**Issue by vrubleg** [llvm/llvm-project#114]
`__FUNCSIG__` is a literal in MSVC, so you can write something like this:
```
char Data[] = __FUNCSIG__;
```
Clang with `-fms-extensions` specified can't compile it:
```
error: array initializer must be an initializer list or string literal
```

**Comment by vrubleg** [comment]
@nico but it seems like it is a different issue.

**Comment by nico** [comment]
You're right, apologies.

**Comment by aeubanks** [comment]
https://reviews.llvm.org/D146764

**Comment by vrubleg** [comment]
Thank you for fixing this.

TBH, it feels like this behavior should be default for all string predefined macros in both Clang and GCC, I don't see any reason why it shouldn't.

Anyway, it is at least available as an option in Clang.

**Comment by aeubanks** [comment]
patch was reverted, reopening
