### ISSUE TITLE
[clang] Class fields with placeholder names cause incorrect instantiation of in-class initializers

### ISSUE THREAD

**Issue by groundswellaudio** [llvm/llvm-project#114069]
MRE : 

https://godbolt.org/z/Mjdnz8G31

```cpp
#include <cassert>

template <class T>
struct A {
    T _ = 5;
    T _ = 4;
};

int main() {
    A<int> a;
    auto [x, y] = a;
    assert( y == 4 );
}
```

`assert( y == 4 )` fails because Clang finds the in-class init pattern like this (in Sema::BuildCXXDefaultInitExpr) : 

```cpp
CXXRecordDecl *ClassPattern = ParentRD->getTemplateInstantiationPattern();
DeclContext::lookup_result Lookup = ClassPattern->lookup(Field->getDeclName());

FieldDecl *Pattern = nullptr;
for (auto *L : Lookup) {
  if ((Pattern = dyn_cast<FieldDecl>(L)))
    break;
}
```

Obviously this cannot works with `_`. I think to remedy this imply keeping track of the pattern of an instantiated field with a placeholder name in some auxiliary structure? The entry would only need to be temporary until its consumed by Sema::BuildCXXDefaultInitExpr. 

Also I think a warning should be emitted that we're using a C++26 feature before its time?

**Comment by cor3ntin** [comment]
The template seems to be the culprit (both for the lack of warning and the codegen issue) https://godbolt.org/z/evThj3jrM

**Comment by groundswellaudio** [comment]
It's not a codegen issue but an AST one. Clang finds the pattern of a FieldDecl by looking up its name in the template, this fails with `_` so the init of the second field becomes 5, not 4 (it stops at the first FieldDecl it has found by name lookup).

**Comment by cor3ntin** [comment]
> It's not a codegen issue but an AST one. Clang finds the pattern of a FieldDecl by looking up its name in the template, this fails with `_` so the init of the second instantiated field becomes 5, not 4 (it stops at the first FieldDecl it has found by name lookup).

Yup. We should find the field by index instead.
