### ISSUE TITLE
[libcxx][libunwind][libcxxabi] How to pass multiple compilation options to -DLIBCXX_ADDITIONAL_COMPILE_FLAGS ?

### ISSUE THREAD

**Issue by trcrsired** [llvm/llvm-project#114134]
i want to pass "-fwasm-exceptions -D_REENTRANT" for example. don't know how to pass it

**Comment by trcrsired** [comment]
https://github.com/WebAssembly/wasi-libc/issues/545

**Comment by ldionne** [comment]
From https://libcxx.llvm.org/VendorDocumentation.html#cmdoption-arg-LIBCXX-LIBCXXABI-LIBUNWIND-_ADDITIONAL_COMPILE_FLAGS-STRING:

> Additional compile flags to use when building the runtimes. This should be a CMake ;-delimited list of individual compiler options to use. For options that must be passed as-is to the compiler without deduplication (e.g. -Xclang -foo option groups), consider using SHELL: as [documented here](https://cmake.org/cmake/help/latest/command/add_compile_options.html#option-de-duplication).

So, for example, you'd pass `-DLIBCXX_ADDITIONAL_COMPILE_FLAGS="-fwasm-exceptions;-D_REENTRANT"`.

**Comment by trcrsired** [comment]
ty ty
