### ISSUE TITLE
[lld] ld64.lld does not respect allowable-client field in .tbds

### ISSUE THREAD

**Issue by bdash** [llvm/llvm-project#114146]
Apple's linker rejects linking to libraries with allowable client lists:

```
$ cc -framework vecLib -o test test.m         
ld: cannot link directly with 'vecLib' because product being built is not an allowed client of it
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

After https://github.com/llvm/llvm-project/pull/97639, not only does ld64.lld not reject linking to vecLib.framework, it links to the library despite the binary not being an allowed client:
```
$ cc -framework vecLib -fuse-ld=lld -Bllvm-build/Release+Asserts/bin -o test test.m
$ nm -m test | grep vecLib                                                                                               
                 (undefined) external _vvdiv (from vecLib)
$ grep ' clients:' $(xcrun --show-sdk-path)/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/vecLib.tbd
    clients:         [ Accelerate ]
    clients:         [ vecLib ]
    clients:         [ vecLib ]
    clients:         [ vecLib ]
    clients:         [ vecLib ]
    clients:         [ Sparse, vecLib ]
```

Generating binaries that don't respect the allowable client list means applications will break if / when Apple moves symbols between libraries.

test.m:
```
#include <stdio.h>
#include <vecLib/vForce.h>

int main(int argc, char**argv) {
    fprintf(stderr, "%p\n", &vvdiv);
    return 0;
}
```

_Originally posted by @bdash in https://github.com/llvm/llvm-project/issues/97639#issuecomment-2445467330_

**Comment by bdash** [comment]
My apologies, I was too hasty in blaming #97639. The problem appears to predate that change.

**Comment by carlocab** [comment]
I have a branch that kind of fixes this for `.dylib`s (ld64.lld also does not respect it when dylibs are linked with `-allowable_client` flags).

It still needs polishing and tests, and I don't think it works for `.tbd`s yet (haven't tested). I can open a PR if desired (unless someone's already done the work on this).

**Comment by carlocab** [comment]
I opened #114638 to respect dylibs linked with `-allowable_client`. It doesn't support the same property for `.tbd`s yet.

It can be added to #114638 with
```diff
diff --git a/lld/MachO/InputFiles.cpp b/lld/MachO/InputFiles.cpp
index c715169927e7..bb922a05cd2b 100644
--- a/lld/MachO/InputFiles.cpp
+++ b/lld/MachO/InputFiles.cpp
@@ -1899,6 +1899,11 @@ DylibFile::DylibFile(const InterfaceFile &interface, DylibFile *umbrella,
   exportingFile = (canBeImplicitlyLinked && isImplicitlyLinked(installName))
                       ? this
                       : umbrella;
+
+  if (!canBeImplicitlyLinked)
+    for (const auto &allowableClient : interface.allowableClients())
+      allowableClients.push_back(*make<std::string>(allowableClient.getInstallName().str()));
+
   auto addSymbol = [&](const llvm::MachO::Symbol &symbol,
                        const Twine &name) -> void {
     StringRef savedName = saver().save(name);
```
but doing this strikes me as a bit inefficient, so I'm wondering if there's a better way.

**Comment by nico** [comment]
Thanks for the fix, @carlocab!

**Comment by carlocab** [comment]
No problem. Thanks for the review and testing!

I hope to have an implementation of `-allowable_client` by next week ready so we can get rid of the `liballowable_client.dylib` binary test fixture.

**Comment by carlocab** [comment]
I've opened #117113 to track support for `-allowable_client` and removal of the `liballowable_client.dylib` test fixture.
