### ISSUE TITLE
Incorrect assembly code generated with -Os

### ISSUE THREAD

**Issue by mushenoy** [llvm/llvm-project#114185]
For the below sample source file -  the assembly code generated is incorrect.

Sample.c:
```
struct sample {
    struct sample *next;
    char a;
};

char function (char);
void test(void);

void* test_function (const struct sample *c)
{
    char type;
    if (c) {
        type = c->a;
        test();
   }
   function(type);
   return (void *)0;
} 
```

Compilation command:

```
clang --target=aarch64-linux-gnu -save-temps -c sample.c -o sample.o -Os

```

In the assembly:
- No conditional branch is generated to check if `c` is non-null.
- test function call is done unconditionally

Assembly code:

```
test_function:
        stp     x29, x30, [sp, #-32]!
        str     x19, [sp, #16]
        mov     x29, sp
        ldrb    w19, [x0, #8]
        bl      test
        mov     w0, w19
        bl      function
        mov     x0, xzr
        ldr     x19, [sp, #16]
        ldp     x29, x30, [sp], #32
        ret
```

x86_64:
```
test_function:
        push    rbx
        movsx   ebx, byte ptr [rdi + 8]
        call    test@PLT
        mov     edi, ebx
        call    function@PLT
        xor     eax, eax
        pop     rbx
        ret
 ```
 
 Observations:
 - The issue is observed when -Os is used
 - Code gets generated correctly when `type` variable is initialized with some value.

**Comment by dtcxzyw** [comment]
The key point is that clang sets `noundef` on the function argument of `function`. Then `SimplifyCFGPass` will eliminate the null check:
https://github.com/llvm/llvm-project/blob/287781c7c9dbd7674cf7cbab8a8fe8a49a4b9317/llvm/lib/Transforms/Utils/SimplifyCFG.cpp#L8045-L8080
https://github.com/llvm/llvm-project/blob/287781c7c9dbd7674cf7cbab8a8fe8a49a4b9317/llvm/lib/Transforms/Utils/SimplifyCFG.cpp#L8009-L8037

With `-Xclang -no-enable-noundef-analysis`, the null pointer check will be kept: https://godbolt.org/z/3Eb4rhens
