### ISSUE TITLE
[CMake]PARTIAL_SOURCES_INTENDED no longer works after 36adb82c251d2d0627856b648a1c357fa7f3864e

### ISSUE THREAD

**Issue by Naville** [llvm/llvm-project#114369]
Title.
In 36adb82c251d2d0627856b648a1c357fa7f3864e ,  ``PARTIAL_SOURCES_INTENDED`` is already consumed by llvm_process_sources, which means ``llvm_check_source_file_list`` is unable to parse ``PARTIAL_SOURCES_INTENDED``

@chapuni I think?

**Comment by Naville** [comment]
I think my interpretation of the issue is correct, due to ``_UNPARSED_ARGUMENTS`` that gets passes into ``llvm_check_source_file_list`` no longer contains ``PARTIAL_SOURCES_INTENDED``, which results in using ``PARTIAL_SOURCES_INTENDED`` still yields an ``Found unknown source file`` warning

**Comment by chapuni** [comment]
@Naville What is your actual matter?

**Comment by Naville** [comment]
> @Naville What is your actual matter?

PARTIAL_SOURCES_INTENDED is broken due to this change and I can no longer use it when adding llvm libraries

**Comment by Naville** [comment]
The fix is probably to don't parse ``PARTIAL_SOURCES_INTENDED`` in ``llvm_process_sources``, since it's not used there anyway, and move the parameter parsing to https://github.com/llvm/llvm-project/blob/36adb82c251d2d0627856b648a1c357fa7f3864e/llvm/cmake/modules/LLVMProcessSources.cmake#L78

**Comment by chapuni** [comment]
Could you show me the actual case that doesn't work as you expected?

**Comment by Naville** [comment]
DMed on Discord

**Comment by chapuni** [comment]
With my quick check, `PARTIAL_SOURCES_INTENDED` is caught by;
https://github.com/llvm/llvm-project/commit/36adb82c251d2d0627856b648a1c357fa7f3864e#diff-65f45433d3f4d2d45acc5b9d60dd3bfdb11be27984dbf8b8b9b1eb10202681b4R93

**Comment by chapuni** [comment]
FYI, before fa3d789df15bd, llvm/utils/TableGen was the actual user of `PARTIAL_SOURCES_INTENDED`.

**Comment by Naville** [comment]
I'm currently 

> With my quick check, `PARTIAL_SOURCES_INTENDED` is caught by; [36adb82#diff-65f45433d3f4d2d45acc5b9d60dd3bfdb11be27984dbf8b8b9b1eb10202681b4R93](https://github.com/llvm/llvm-project/commit/36adb82c251d2d0627856b648a1c357fa7f3864e#diff-65f45433d3f4d2d45acc5b9d60dd3bfdb11be27984dbf8b8b9b1eb10202681b4R93)

That ARGS_ in theory and in practice on (at least mine) ``CMake 3.29.3`` is not set, due the reasons I talked about in Discord.
I'll bypass the problem locally for now by not using it.

Let me try to explain the bug (At least my interpretation of it) step by step:
- In ``llvm_process_sources``, you've used ``cmake_parse_arguments`` to parse the parameter ``PARTIAL_SOURCES_INTENDED``, which results in ARGS_PARTIAL_SOURCES_INTENDED being defined, **in that scope only**, due to ``function`` starts a new variable scope
- Per CMake documentation, ``ARG_UNPARSED_ARGUMENTS`` contains the **unparsed** arguments, which doesn't contain ``PARTIAL_SOURCES_INTENDED``. I've added ``message(STATUS "${ARG_UNPARSED_ARGUMENTS}")`` before the call to ``  llvm_check_source_file_list(${sources})`` to confirm this option doesn't exist
- Now in ``llvm_check_source_file_list``, ``cmake_parse_arguments``  doesn't parse ``PARTIAL_SOURCES_INTENDED`` at all, which results in ``ARG_PARTIAL_SOURCES_INTENDED`` remains always undefined

**Comment by chapuni** [comment]
I've reconfirmed with `3.30.5` (win32 x64). It's working as expected.

**Comment by Naville** [comment]
I'm confused as much as you do w.r.t. this.
I'll see Tom Stellar, the release manager for the next LLVM release to double-check this.

Thanks for the effort

**Comment by tstellar** [comment]
@tru

**Comment by tru** [comment]
Not sure how I can help here. Is this a problem with the release process itself?

**Comment by tru** [comment]
Can you try the latest 19 branch and see if it's still a problem? What version of CMake are you using?
