### ISSUE TITLE
compiling warning: /usr/lib/llvm/19/include/llvm/ADT/APInt.h:172:18: warning: ‘void operator delete [](void*)’ called on a pointer to an unallocated object ‘1’ [-Wfree-nonheap-object]

### ISSUE THREAD

**Issue by EssenSea** [llvm/llvm-project#114393]
AS TITLE SAY. Package triggers severe warnings which indicate that it may exhibit random runtime failures.

**Comment by tbaederr** [comment]
This is a false-positive emitted by gcc, unless you can prove otherwise.
