### ISSUE TITLE
llvm 'GV doesn't have initializer' assert with using LTO

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11449]
|  |  |
| --- | --- |
| Bugzilla Link | [11077](https://llvm.org/bz11077) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic |

## Extended Description 
Getting this within a build that works great for the remainder of the source code, but one small so fails when linking. This is on ubuntu 11.04 with binutils built from cvs head with the gold linker enabled and clang/llvm trunk from today.

$ clang++ -O4 -use-gold-plugin -save-temps -o plugins/input/ogr.input -shared plugins/input/ogr/ogr_converter.os plugins/input/ogr/ogr_datasource.os plugins/input/ogr/ogr_featureset.os plugins/input/ogr/ogr_index_featureset.os -Lagg -Lsrc -L/usr/local/lib -L/usr/lib -L/home/mapnik/projects/mapnik-static-build/sources/lib -L/home/mapnik/projects/mapnik-static-build/sources -lgdal -lmapnik2 -licuuc -lboost_system -lboost_filesystem -lproj -lexpat -ljpeg -ltiff -lpng -lz -lpthread -lm -lrt -ldl
ld: /home/mapnik/src/llvm/include/llvm/GlobalVariable.h:122: llvm::Constant* llvm::GlobalVariable::getInitializer(): Assertion `hasInitializer() && "GV doesn't have initializer!"' failed.
clang: error: unable to execute command: Aborted
clang: error: linker command failed due to signal 2 (use -v to see invocation)
clang: note: diagnostic msg: Please submit a bug report to http://llvm.org/bugs/ and include command line arguments and all diagnostic information.
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
clang: note: diagnostic msg: Error generating preprocessed source(s).

**Comment by arsenm** [comment]
Reproducer seems complicated and not attached, dead links
