### ISSUE TITLE
C++ constructor interpreted as function when rvalue and using parenthesis, preventing template deduction for aliases

### ISSUE THREAD

**Issue by mld2443** [llvm/llvm-project#114586]
https://godbolt.org/z/fPvqG4Txx
```cpp
template <int> class A {};
A() -> A<0>;

template <int ARG>
using B = A<ARG>;

static_assert(sizeof(B()));
```
GCC deduces `B` to be a type alias for `A` and interprets `B()` as instantiation using deduction guides. clang interprets rvalue as an alias to a function instead of a type constructor, and the template argument deductions are incorrectly rejected.

In order to convince clang that `B` is a type and not a function, we can use braced initialization, `B{}`.

clang and MSVC both consider this ill-formed, however I think GCC is correct here.

**Comment by zygoloid** [comment]
I agree. `B` here is a type according to the grammar, so `B()` is interpreted as a function type.

(I wrote up a [resolution to CWG2228](https://htmlpreview.github.io/?https://github.com/zygoloid/wg21papers/blob/master/to-review/cwg2228.html) that would cause this to be allowed, but I haven't had time to follow up on it.)

**Comment by zygoloid** [comment]
The status of the corresponding language issue is tracked in [EWG issue 1376](https://github.com/cplusplus/papers/issues/1376). For now there's no clear suggestion that a language rule change will be made, so I'm closing this as "not planned". We can revisit if and when there's progress on the EWG issue.
