### ISSUE TITLE
SLPVectorizer blows up compile times on certain input

### ISSUE THREAD

**Issue by aeubanks** [llvm/llvm-project#114584]
Running `opt -p slp-vectorizer /tmp/h.ll -disable-output` takes >1 min on my machine, and much longer on weaker build farm machines. -ftime-trace shows that this took more than half the total compile time.

[h.ll.txt](https://github.com/user-attachments/files/17602799/h.ll.txt)

**Comment by alexey-bataev** [comment]
Are you using debug build of the compiler? For me it takes 7 seconds with the release version of the compiler, even though the input file is 17MB

**Comment by aeubanks** [comment]
Double checking today, it's an optimized build with asserts at 6e7375031a1a, which is ~2 weeks ago, and it took ~100s. However, moving to ToT from today (c6cce261f5f7), it has gone down to ~9s for me, so something was improved in the last couple of weeks. However, running `opt -O3 --time-passes` over the provided IR, it still takes a lot more time than all the other passes, which sorta points to it potentially blowing up compile times on even larger input. It'd be nice to understand if there's a specific part of SLPVectorizer that's eating up compile times on this IR and if we can bound that part? Otherwise perhaps there's nothing left to do.

```
===-------------------------------------------------------------------------===
                          Pass execution timing report
===-------------------------------------------------------------------------===
  Total Execution Time: 16.2712 seconds (16.2773 wall clock)

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
   7.7776 ( 48.1%)   0.0159 ( 16.8%)   7.7936 ( 47.9%)   7.7962 ( 47.9%)  SLPVectorizerPass
   3.2544 ( 20.1%)   0.0039 (  4.1%)   3.2582 ( 20.0%)   3.2595 ( 20.0%)  InstCombinePass
   1.4416 (  8.9%)   0.0239 ( 25.1%)   1.4655 (  9.0%)   1.4665 (  9.0%)  GVNPass
...
```

**Comment by alexey-bataev** [comment]
> Double checking today, it's an optimized build with asserts at [6e73750](https://github.com/llvm/llvm-project/commit/6e7375031a1a3172d5e369cf2c108da2bcf65c8a), which is ~2 weeks ago, and it took ~100s. However, moving to ToT from today ([c6cce26](https://github.com/llvm/llvm-project/commit/c6cce261f5f7e1bdb092374d51e44ab7bc04e769)), it has gone down to ~9s for me, so something was improved in the last couple of weeks. However, running `opt -O3 --time-passes` over the provided IR, it still takes a lot more time than all the other passes, which sorta points to it potentially blowing up compile times on even larger input. It'd be nice to understand if there's a specific part of SLPVectorizer that's eating up compile times on this IR and if we can bound that part? Otherwise perhaps there's nothing left to do.
> 
> ```
> ===-------------------------------------------------------------------------===
>                           Pass execution timing report
> ===-------------------------------------------------------------------------===
>   Total Execution Time: 16.2712 seconds (16.2773 wall clock)
> 
>    ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
>    7.7776 ( 48.1%)   0.0159 ( 16.8%)   7.7936 ( 47.9%)   7.7962 ( 47.9%)  SLPVectorizerPass
>    3.2544 ( 20.1%)   0.0039 (  4.1%)   3.2582 ( 20.0%)   3.2595 ( 20.0%)  InstCombinePass
>    1.4416 (  8.9%)   0.0239 ( 25.1%)   1.4655 (  9.0%)   1.4665 (  9.0%)  GVNPass
> ...
> ```

I `perfed` it and did not found any significant time eaters, all SLP-related calls took less than 2% of overall time, so no idea where to improve it for now.

**Comment by aeubanks** [comment]
I realized my timing report was slightly misleading because I had captured the IR right before SLP vectorization, so most previous passes wouldn't do any work.

If there's nothing obvious to fix then I'll close this.

**Comment by aeubanks** [comment]
Turns out it was https://github.com/llvm/llvm-project/pull/112221 that drastically improved compile times here.
