### ISSUE TITLE
Support may_alias in processTypeAttrs()

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#11454]
|  |  |
| --- | --- |
| Bugzilla Link | [11082](https://llvm.org/bz11082) |
| Version | trunk |
| OS | All |
| CC | @chandlerc,@efriedma-quic,@rjmccall |

## Extended Description 
clang now complains about unsupported attributes on types. As a consequence, it complains about may_alias in cast expressions such as here:

void g(int p __attribute__((may_alias))) {}

void f() {
  int a = 0;
  g((int __attribute__((may_alias)))a);
}

hummer:clang thakis$ ../../Release+Asserts/bin/clang -Wall test.c -c
test.c:5:25: error: 'may_alias' attribute ignored when parsing type
  g((int __attribute__((may_alias)))a);
                        ^~~~~~~~~
1 error generated.

This is used in glib, see e.g. here:
http://codesearch.google.com/#cZwlSNS7aEw/external/bluetooth/glib/glib/gatomic.h&q=%5C(g_atomic_pointer_set%5C)%5C%20%5C(%5C(volatile%5C%20gpointer%5C%20G_GNUC_MAY_ALIAS%5C%20%5C*%5C)%5C%20%5C(void%5C%20%5C*%5C)%5C%20%5C(atomic%5C),%5C%20%5C(newval%5C)%5C)%5C)&type=cs&l=76

**Comment by philnik777** [comment]
Closing, since `may_alias` is supported by clang and unknown attributes are a warning now.
