### ISSUE TITLE
SwitchInst default block doesn't get optimized away

### ISSUE THREAD

**Issue by nlewycky** [llvm/llvm-project#1146]
|  |  |
| --- | --- |
| Bugzilla Link | [774](https://llvm.org/bz774) |
| Version | trunk |
| OS | Linux |
| CC | @ggreif |

## Extended Description 
LLVM doesn't seem to do a good job of removing the default block of a switch
statement. Given the C++ code:

  int test1(bool b)
  {
    switch (b) {
      case true:
        return 1;
      case false:
        return 2;
      default:
        return 3;
    }
    return 4;
  }

The return 4 is removed, but return 3 is kept. By contrast, the same logic with
if statements:

  int test1if(bool b)
  {
    if (b == true)
      return 1;
    else if (b == false)
      return 2;
    else
      return 3;
  
    return 4;
  }

becomes:

  int %_Z7test1ifb(bool %b) {
  entry:
          %retval = select bool %b, int 1, int 2          ; <int> [#uses=1]
          ret int %retval
  }

so it's clear that LLVM should know what's going on.

**Comment by gwelymernans** [comment]
The code that's generated is far better. The original example compiles to this:

```
test1:                                  # @test1
	.cfi_startproc
# %bb.0:
	movl	$2, %eax
	subl	%edi, %eax
	retq
```

The `switch (x & 7)` example compiles down to this:

```
@switch.table.test1 = private unnamed_addr constant [8 x i32] [i32 -1, i32 -2, i32 -3, i32 -4, i32 -6, i32 -7878, i32 -11, i32 -23], align 4

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone uwtable willreturn
define dso_local i32 @test1(i32 %0) local_unnamed_addr #0 {
  %2 = and i32 %0, 7
  %3 = zext i32 %2 to i64
  %4 = getelementptr inbounds [8 x i32], [8 x i32]* @switch.table.test1, i64 0, i64 %3
  %5 = load i32, i32* %4, align 4
  ret i32 %5
}
```
