### ISSUE TITLE
[SelectionDAG] "Add preliminary plumbing" fails assert and crashes on ARM

### ISSUE THREAD

**Issue by vitalybuka** [llvm/llvm-project#114648]

**Comment by vitalybuka** [comment]
Reproducible on x86_64 clang build with assertions with:
[BranchProbabilityInfo.TGZ](https://github.com/user-attachments/files/17606257/BranchProbabilityInfo.TGZ)

**Comment by antoniofrighetto** [comment]
Thanks, closing this as the assert should be fixed by 917b3d13b558e61885c3db085e27b4a110ce8032.
