### ISSUE TITLE
Missing built-in operator overloading candidates with address spaces

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11465]
|  |  |
| --- | --- |
| Bugzilla Link | [11093](https://llvm.org/bz11093) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @AaronBallman,@DougGregor,@efriedma-quic |

## Extended Description 
Hi,

Compiling PCL with clang (trunk version) fails with error asking for bug report so here it is.
1.      <eof> parser at end of file
2.      .../eigen3/Eigen/src/SVD/JacobiSVD.h:412:5: instantiating function definition 'JacobiSVD'
3.      .../include/eigen3/Eigen/src/SVD/JacobiSVD.h:431:16: instantiating function definition 'compute'
4.      .../include/eigen3/Eigen/src/SVD/JacobiSVD.h:262:6: instantiating function definition 'real_2x2_ja
cobi_svd'
5.      .../include/eigen3/Eigen/src/Core/MatrixBase.h:455:10: instantiating function definition 'applyOnT
heLeft'
6.      ../include/eigen3/Eigen/src/Jacobi/Jacobi.h:271:6: instantiating function definition 'apply_rotat
ion_in_the_plane'
clang-3: error: unable to execute command: Aborted

To report the error simply download PCL sources and try a fresh build. ALthough not worth mentioning but just in case, code compiles and runs with gcc-4.4.3 ubuntu falvour.

I would appreciate your help.

**Comment by shafik** [comment]
Fixed: https://godbolt.org/z/xE6ersYP7
