### ISSUE TITLE
[mlir] MLIRNVVMTarget link an Absolute Path Library

### ISSUE THREAD

**Issue by MikaOvO** [llvm/llvm-project#114757]
When build mlir with `-DMLIR_ENABLE_NVPTXCOMPILER=ON`, there will be an absolute path library in the `/Path/to/build/install/lib/cmake/mlir/MLIRTargets.cmake`. For example:

```cmake
set_target_properties(MLIRNVVMTarget PROPERTIES
  INTERFACE_LINK_LIBRARIES "MLIRIR;MLIRExecutionEngineUtils;MLIRSupport;MLIRGPUDialect;MLIRTargetLLVM;MLIRNVVMToLLVMIRTranslation;LLVMSupport;/An/absolute/path/libnvptxcompiler_static.a"
)
```

If downstream project needs use this target, it will probably can not find this library, then fail to build.

We should make this absolute path become a library that downstream project can modify its path.

**Comment by BwL1289** [comment]
@MikaOvO this was marked as completed but no commit or pr was associated. Is there a reference to where it was fixed? Thanks!

**Comment by BwL1289** [comment]
@MikaOvO bumping this. Is there a reference to where it was fixed?
