### ISSUE TITLE
Error compiling zlib

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11471]
|  |  |
| --- | --- |
| Bugzilla Link | [11099](https://llvm.org/bz11099) |
| Version | 2.9 |
| OS | Windows XP |
| Attachments | [Files causing troubles](https://user-images.githubusercontent.com/60944935/143744045-0336a323-b211-4b25-baa6-ee5b8fc9cfe1.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@efriedma-quic |

## Extended Description 

When trying to compile zlib 1.2.5 with clang:

E:\projects\benchmark04\tst\tmp>c:\clang\bin\clang.exe -o deflate.c.obj -c deflate.c -v
clang version 2.9 (tags/RELEASE_29/final)
Target: i386-pc-mingw32
Thread model: posix
 "c:/clang/bin/clang.exe" -cc1 -triple i386-pc-mingw32 -S -disable-free -disable
-llvm-verifier -main-file-name deflate.c -mrelocation-model static -mdisable-fp-
elim -mconstructor-aliases -target-cpu pentium4 -target-linker-version 97.14 -mo
mit-leaf-frame-pointer -v -resource-dir c:/clang/bin\..\lib\clang\2.9 -ferror-li
mit 19 -fmessage-length 80 -fno-use-cxa-atexit -fgnu-runtime -fdiagnostics-show-
option -fcolor-diagnostics -o C:/DOCUME~1/ADMINI~1/LOCALS~1/Temp/cc-270455.s -x
c E:\projects\benchmark04\src\zlib\deflate.c
clang -cc1 version 2.9 based upon llvm 2.9 hosted on i386-pc-mingw32
ignoring nonexistent directory "/usr/local/include"
ignoring nonexistent directory "/mingw/include"
ignoring nonexistent directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 c:/clang/bin/../lib/clang/2.9/include
 c:/mingw/include
End of search list.
 "c:/MinGW/bin/gcc.exe" -v -c -m32 -o deflate.c.obj -x assembler C:/DOCUME~1/ADM
INI~1/LOCALS~1/Temp/cc-270455.s
Using built-in specs.
COLLECT_GCC=c:/MinGW/bin/gcc.exe
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/4.5.2/lto-wrapper.exe
Target: mingw32
Configured with: ../gcc-4.5.2/configure --enable-languages=c,c++,ada,fortran,obj
c,obj-c++ --disable-sjlj-exceptions --with-dwarf2 --enable-shared --enable-libgo
mp --disable-win32-registry --enable-libstdcxx-debug --enable-version-specific-r
untime-libs --disable-werror --build=mingw32 --prefix=/mingw
Thread model: win32
gcc version 4.5.2 (GCC)
COLLECT_GCC_OPTIONS='-v' '-c' '-m32' '-o' 'deflate.c.obj' '-mtune=i386' '-march=
i386'
 c:/mingw/bin/../lib/gcc/mingw32/4.5.2/../../../../mingw32/bin/as.exe -o deflate
.c.obj C:/DOCUME~1/ADMINI~1/LOCALS~1/Temp/cc-270455.s
C:/DOCUME~1/ADMINI~1/LOCALS~1/Temp/cc-270455.s: Assembler messages:
C:/DOCUME~1/ADMINI~1/LOCALS~1/Temp/cc-270455.s:5971: Error: unknown pseudo-op: `
.hidden'
C:/DOCUME~1/ADMINI~1/LOCALS~1/Temp/cc-270455.s:5972: Error: unknown pseudo-op: `
.hidden'
C:/DOCUME~1/ADMINI~1/LOCALS~1/Temp/cc-270455.s:5973: Error: unknown pseudo-op: `
.hidden'
C:/DOCUME~1/ADMINI~1/LOCALS~1/Temp/cc-270455.s:5974: Error: unknown pseudo-op: `
.hidden'
C:/DOCUME~1/ADMINI~1/LOCALS~1/Temp/cc-270455.s:5975: Error: unknown pseudo-op: `
.hidden'
C:/DOCUME~1/ADMINI~1/LOCALS~1/Temp/cc-270455.s:5976: Error: unknown pseudo-op: `
.hidden'
clang: error:
      assembler
      (via
      gcc)
      command
      failed
      with
      exit
      code
      1
      (use
      -v
      to
      see
      invocation)

clang version:
clang version 2.9 (tags/RELEASE_29/final)
Target: i386-pc-mingw32
Thread model: posix

**Comment by arsenm** [comment]
Build issue too old to be useful
