### ISSUE TITLE
[RISCV] Cannot select nxv2bf16 = RISCVISD::VFSLIDE1UP_VL

### ISSUE THREAD

**Issue by topperc** [llvm/llvm-project#114893]
This test case give a cannot select error with -mattr=+zfbfmin,+zvfbfmin,+zvl64b

```
define <2 x bfloat> @vslide1up_2xbfloat(<2 x bfloat> %v, bfloat %b) {
  %vb = insertelement <2 x bfloat> poison, bfloat %b, i64 0
  %v1 = shufflevector <2 x bfloat> %v, <2 x bfloat> %vb, <2 x i32> <i32 2, i32 0
  ret <2 x bfloat> %v1
}
```

We need to disable `lowerVECTOR_SHUFFLEAsVSlide1` for bf16. We probably also need to disable it for f16 without Zfh.

CC: @lukel97 @preames

**Comment by lukel97** [comment]
Is there a reason why we couldn't lower this as a fmv.x.w and vslide1up.vx?

**Comment by topperc** [comment]
> Is there a reason why we couldn't lower this as a fmv.x.w and vslide1up.vx?

That would work too.
