### ISSUE TITLE
[CVP] Infer samesign in CorrelatedValuePropagation

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#114820]
CVP performs signed -> unsigned comparison canonicalization, so we should also infer the samesign flag there. Relevant function is: https://github.com/llvm/llvm-project/blob/3268d51a5c81be705a97216bf061fab9bb195ebe/llvm/lib/Transforms/Scalar/CorrelatedValuePropagation.cpp#L286

We need a change similar to https://github.com/llvm/llvm-project/commit/095d49da76be09143582e07a807c86d3b4334dec for InstCombine.

**Comment by rhanqtl** [comment]
I'd like to fix this issue, could you please assign it to me?
