### ISSUE TITLE
Stale comments

### ISSUE THREAD

**Issue by hexagonrecursion** [llvm/llvm-project#115]
There are a number of comments referencing GREngine and GRExprEngine, but as far as I can tell GREngine no longer exists. Should they be changed to reference ExprEngine?

https://github.com/llvm/llvm-project/blob/1132f87fbf1373835d7030354f6210c5dab62c3e/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp#L10

https://github.com/llvm/llvm-project/blob/1132f87fbf1373835d7030354f6210c5dab62c3e/clang/lib/StaticAnalyzer/README.txt#L8

https://github.com/llvm/llvm-project/blob/a974b33a10745b528c34f0accbd230b0a4e1fb87/clang/test/Analysis/PR3991.m#L53

https://github.com/llvm/llvm-project/blob/a974b33a10745b528c34f0accbd230b0a4e1fb87/clang/test/Analysis/misc-ps-eager-assume.m#L52

**Comment by haoNoQ** [comment]
Yes, definitely.
