### ISSUE TITLE
[EarlyCSE] Optimization ignores specified floating point rounding mode

### ISSUE THREAD

**Issue by patrick-rivos** [llvm/llvm-project#115072]
Testcase:
```llvm ir
define float @test() {
  call void @llvm.set.rounding(i32 2)   ;; Round up
  %a = bitcast i32 1 to float           ;; 1e-45
  %b = bitcast i32 u0x3F800000 to float ;; 1.0
  %res = fadd float %a, %b
  ret float %res
}
```

The optimized version is:
```llvm ir
define float @test() {
  call void @llvm.set.rounding(i32 2)
  ret float 1.000000e+00
}
```

IIUC this ignores the specified rounding mode since it rounds down the result of the fadd.

Godbolt: https://godbolt.org/z/471Ph5EWP

**Comment by efriedma-quic** [comment]
Using llvm.set.rounding outside a strictfp function is undefined behavior: see https://llvm.org/docs/LangRef.html#floating-point-environment .  (Maybe the documentation for llvm.set.rounding should link to that.)

**Comment by patrick-rivos** [comment]
Ah whoops - thanks for the pointer!
