### ISSUE TITLE
Add AliasAnalysis Interface to DSA

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11502]
|  |  |
| --- | --- |
| Bugzilla Link | [11130](https://llvm.org/bz11130) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
There used to be passes within DSA that implemented the AliasAnalysis interface.  This is an enhancement request to re-implement or resurrect such a pass so that DSA can more easily be used for alias analysis queries by other LLVM passes.

**Comment by arsenm** [comment]
DSA no longer exists
