### ISSUE TITLE
[lld] CANNOT LINK EXECUTABLE "clang": unknown reloc type 16 @ 0x7b4a4f523ba0 (1273) on x86_64-linux-android30

### ISSUE THREAD

**Issue by trcrsired** [llvm/llvm-project#115103]
![image](https://github.com/user-attachments/assets/fc8731cb-28ac-4ea0-a34b-f233d7e38694)
Why?

**Comment by trcrsired** [comment]
@MaskRay

**Comment by trcrsired** [comment]
I have checked the bionic and glibc code:
bionic does not support R_X86_64_DTPMOD64??

https://github.com/aosp-mirror/platform_bionic/blob/3da2fec061833d3445990b4b891628dd4e757038/linker/linker_relocate.cpp#L477


glibc:

https://github.com/aosp-mirror/platform_bionic/blob/3da2fec061833d3445990b4b891628dd4e757038/linker/linker_relocate.cpp#L477
```
#define R_X86_64_NONE		0	/* No reloc */
#define R_X86_64_64		1	/* Direct 64 bit  */
#define R_X86_64_PC32		2	/* PC relative 32 bit signed */
#define R_X86_64_GOT32		3	/* 32 bit GOT entry */
#define R_X86_64_PLT32		4	/* 32 bit PLT address */
#define R_X86_64_COPY		5	/* Copy symbol at runtime */
#define R_X86_64_GLOB_DAT	6	/* Create GOT entry */
#define R_X86_64_JUMP_SLOT	7	/* Create PLT entry */
#define R_X86_64_RELATIVE	8	/* Adjust by program base */
#define R_X86_64_GOTPCREL	9	/* 32 bit signed PC relative
					   offset to GOT */
#define R_X86_64_32		10	/* Direct 32 bit zero extended */
#define R_X86_64_32S		11	/* Direct 32 bit sign extended */
#define R_X86_64_16		12	/* Direct 16 bit zero extended */
#define R_X86_64_PC16		13	/* 16 bit sign extended pc relative */
#define R_X86_64_8		14	/* Direct 8 bit sign extended  */
#define R_X86_64_PC8		15	/* 8 bit sign extended pc relative */
#define R_X86_64_DTPMOD64	16	/* ID of module containing symbol */
```

**Comment by trcrsired** [comment]
![image](https://github.com/user-attachments/assets/d5374a0d-d14b-43c1-825d-f70ed4da0854)

**Comment by trcrsired** [comment]
binaries are here:
https://github.com/trcrsired/llvm-releases/releases/tag/20241105

x86_64-linux-android30.tar.xz

**Comment by MaskRay** [comment]
The error message is from Android Bionic, unrelated to lld. Please include enough context to save everyone's time. If this is valid usage, you should ask on an Android bug tracker.
