### ISSUE TITLE
What happened to #106456?

### ISSUE THREAD

**Issue by dabrahams** [llvm/llvm-project#115207]
I filed issue #106456 (clang-format: Generalize BAS_AlwaysBreak to all delimiter types) in April and it is now missing.  Can anyone explain why it might be gone?  I don't _think_ I put anything offensive in the issue.

Refiled [here](https://github.com/llvm/llvm-project/issues/115352).

**Comment by hstk30-hw** [comment]
Maybe github's problem? Just issue again :)

**Comment by dabrahams** [comment]
I filed an issue with GH.  It's not regular LLVM practice to delete issues, is it?
