### ISSUE TITLE
[mlir] Inconsistent results for arith.ceildivsi

### ISSUE THREAD

**Issue by wangyongj1a** [llvm/llvm-project#115293]
I have the following MLIR program:
test.mlir:
```
module {
  func.func @func1() -> f32 {
    %c1189465982_i64 = arith.constant 1189465982 : i64
    %c-9223372036854775808_i64 = arith.constant -9223372036854775808 : i64
    %156 = arith.ceildivsi %c-9223372036854775808_i64, %c1189465982_i64 : i64
    vector.print %156 : i64
    %0 = arith.sitofp %156 : i64 to f32
    return %0 : f32
  }
}
```
When I ran ```/data/tmp/v1107/llvm-project/build/bin/mlir-opt --int-range-optimizations --arith-expand --convert-arith-to-llvm --convert-vector-to-llvm --convert-func-to-llvm --reconcile-unrealized-casts test.mlir  | /data/tmp/v1107/llvm-project/build/bin/mlir-cpu-runner -e func1 --shared-libs=/data/tmp/v1107/llvm-project/build/lib/libmlir_runner_utils.so,/data/tmp/v1107/llvm-project/build/lib/libmlir_c_runner_utils.so``` on the program, I got the result of:
```
-7754212542
-7.754212e+09
```
However, when I ran ```/data/tmp/v1107/llvm-project/build/bin/mlir-opt --arith-expand --convert-arith-to-llvm --convert-vector-to-llvm --convert-func-to-llvm --reconcile-unrealized-casts test.mlir  | /data/tmp/v1107/llvm-project/build/bin/mlir-cpu-runner -e func1 --shared-libs=/data/tmp/v1107/llvm-project/build/lib/libmlir_runner_utils.so,/data/tmp/v1107/llvm-project/build/lib/libmlir_c_runner_utils.so``` on the program, I got the result of:
```
7754212542
7.754212e+09
```

The above two results seem to be inconsistent. I'm not sure if there is any bug in my program or if the wrong usage of the above passes caused these results.

My git version is 1469d82e1cb3edc939d6b93089046edfef0cf36c.

**Comment by wangyongj1a** [comment]
I tried to reproduce this issue on history commit versions, and I found these inconsistence results can be reproduced on commit 472291111d9135961305afebe4e283e3e4e7eebc, and cannot be reproduced on the previous commit 3e39328b62f2932c082496dd2471a9064dbff878. Hi @krzysz00, sorry to disturb but I was wondering if you would mind taking a look at this problem?

**Comment by krzysz00** [comment]
@Mogball @River707 Having stared at this (and noticed that `--arith-expand-ops --canonicalize` on the input gives a simpler reproducer), I *think* the expansion of CeilDivSI is incorrect - a negative number divided by a positive number, rounded up, should still be negative.

**Comment by krzysz00** [comment]
On further investigation, the issue is that `--arith-expand` isn't lowering to logic that handles a ceildiv b where a = INT_MIN , which overflows.

From where I'm standing:
1. In arbitrary precision, the negative result is correct
2. The positive result isn't unreasonable for some of the usual `ceil_div` functions you can find out there

I suspect that, since it looks like this is defined behavior, I need to go add some cases to integer range analysis
