### ISSUE TITLE
arm64ec incorrect mangling instantiating C++ template

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#115231]
```
template <typename X> struct Wrapper {
  int GetValue(void) const;
};
struct A {
  int GetValue(void) const;
};
template<typename X> int Wrapper<X>::GetValue(void) const { return 3; }
template class Wrapper<A>;
```

clang produces `?GetValue@$$h?$Wrapper@UA@@@@QEBAHXZ`, MSVC produces `?GetValue@?$Wrapper@UA@@@@$$hQEBAHXZ`.  I guess the algorithm in llvm::getArm64ECMangledFunctionName is wrong.

CC @mstorsjo @cjacek @dpaoliello @steplong

**Comment by dpaoliello** [comment]
I believe that I have the correct algorithm - PR out shortly
