### ISSUE TITLE
BranchFolding pass fails to reliably maintain "kill" bit

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11533]
|  |  |
| --- | --- |
| Bugzilla Link | [11161](https://llvm.org/bz11161) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @stoklund |

## Extended Description 
The BranchFolding pass fails to properly maintain the kill bit in the following hoisting scenario after register allocation:

BB:...
   %CC <- CMP %R10,...
   CJMP  TBB,condcode,%CC
   JMP FBB

TBB:
   %R11 <-  ADD %R10<kill>,1
   ...

FBB:
   %R11 <- ADD %R10<kill>,1
   ...

BranchFolding hoists the ADD as follows, but fails to maintain the <kill> bit on the %R10 operands.

BB: ...
    %R11 <- ADD %R10<kill>,1    <-- Kill bit not cleared!
    %CC  <- CMP %R10,...        <-- Kill bit not set!
    CJMP  TBB,condcode,%CC
    JMP FBB

This problem causes the register scavenger to bomb during post-register-allocation processing.

**Comment by arsenm** [comment]
Kill flags are obsolete
