### ISSUE TITLE
icu segfaults after being compiled with clang, behaves normal with gcc

### ISSUE THREAD

**Issue by alistra** [llvm/llvm-project#11540]
|  |  |
| --- | --- |
| Bugzilla Link | [11168](https://llvm.org/bz11168) |
| Version | 2.9 |
| OS | Linux |
| Attachments | [backtrace](https://user-images.githubusercontent.com/92601900/143744092-adb27bc9-9ed4-47da-96fa-ebf2c9d75181.gz) |
| CC | @DimitryAndric |

## Extended Description 
I use xxxterm(web browser) and it depends on icu.

When I compile icu with gcc it works normally, but when I compile it on clang it segfaults (attached backtrace) when entering on some sites (like google calendar, google reader).

Tried with icu-4.8 and 4.8.1, same effect.

**Comment by Endilll** [comment]
Author has never got back to us.

**Comment by alistra** [comment]
Sorry, stopped using the browser all together
