### ISSUE TITLE
InstCombineCompares 

### ISSUE THREAD

**Issue by SpencerAbson** [llvm/llvm-project#115486]
This has the side-effect of converting a post-inc IV into a pre-inc IV. LSR has the ability to rectify this, but it's use of SCEVExpander can only do so by inserting instructions into the pre-header. A similar issue (https://github.com/llvm/llvm-project/issues/54558) was fixed by https://github.com/llvm/llvm-project/commit/5f8c2b884d4288617138114ebd2fdb235452c8ce - but I'm hesitant to apply a similar fix here unless it is the only option.

**Comment by EugeneZelenko** [comment]
@SpencerAbson: Could you please elaborate?

**Comment by SpencerAbson** [comment]
@EugeneZelenko Apologies for this, it was a mistake whilst writing https://github.com/llvm/llvm-project/issues/115493.
