### ISSUE TITLE
clang-20 crashed with optnone attribute at -O1 and above. error in backend: Cannot select: intrinsic %llvm.expect.with.probability.

### ISSUE THREAD

**Issue by iamanonymouscs** [llvm/llvm-project#115411]
clang-20 crashed with ```optnone``` attribute at ```-O1``` and above.

Compiler explorer: https://godbolt.org/z/4dP5xGxnx

```
$cat mutant.c
int a;
void __attribute__((optnone)) b() {
  int c = __builtin_expect_with_probability(a, 0, 0.8);
}

Also crashed on clang-19.

$clang-19 -O1 mutant.c
fatal error: error in backend: Cannot select: intrinsic %llvm.expect.with.probability
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Ubuntu clang version 19.0.0 (++20240722031324+65825cd5431c-1~exp1~20240722151445.1819)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-19/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/mutant-b18d19.c
clang: note: diagnostic msg: /tmp/mutant-b18d19.sh
clang: note: diagnostic msg: 

********************
```

**Comment by phoebewang** [comment]
I think this is Clang codegen problem. According to https://github.com/llvm/llvm-project/blob/main/clang/lib/CodeGen/CGBuiltin.cpp#L3522, we should not generate llvm.expect.with.probability for `optnone` as well.

**Comment by antangelo** [comment]
That link seems to have drifted, but I presume it means to link to this: https://github.com/llvm/llvm-project/blob/93a4244523b171c8a9cc2ba23e1107ef0ddf7436/clang/lib/CodeGen/CGBuiltin.cpp#L3573-L3577

Curiously, if you replace `__builtin_expect_with_probability` with `__builtin_expect`, there is no assertion failure in the backend (despite the optimization check on the Clang side being exactly the same). See https://godbolt.org/z/abeh8Wba5

It seems like [SelectionDAGBuilder](https://github.com/llvm/llvm-project/blob/315519917368dce841f1cb1e7b296846d13497c3/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp#L7534-L7537), [FastISel](https://github.com/llvm/llvm-project/blob/315519917368dce841f1cb1e7b296846d13497c3/llvm/lib/CodeGen/SelectionDAG/FastISel.cpp#L1459-L1465), and [IntrinsicLowering](https://github.com/llvm/llvm-project/blob/315519917368dce841f1cb1e7b296846d13497c3/llvm/lib/CodeGen/IntrinsicLowering.cpp#L239-L244) each have similar handling that removes the `llvm.expect` if it has not already been transformed out, but no such handling exists for `llvm.expect.with.probability`. I think it should be handled here for consistency, but it probably doesn't hurt to check for `optnone` on the clang side too.
