### ISSUE TITLE
[clang] Miscompile with -O2/3 and -O0/1

### ISSUE THREAD

**Issue by cardigan1008** [llvm/llvm-project#115678]
When I compiled this code with -O2/3, its return code is 224. With -O0/1, its return code is 0 and its output is 0:

```c
int printf(const char *, ...);
int a, e;
struct b {
  int *c;
  int d;
};
void f(int g) {
  int h[] = {6, e, 4};
  int *i = h;
  int j = 0;
  for (; j < g; j++) {
    struct b *k = (struct b *)&i[j];
    if (k->c)
      k->d = 0;
  }
}
int main() {
  f(1);
  printf("%X\n", a);
}
```

The earliest version with this bug is clang 15.0.0. Details can be found here: https://godbolt.org/z/c4saxe9nq

**Comment by hstk30-hw** [comment]
Function `f` inlined, the code is dead in f, so elimited.
But `GVNPass` seem merge the BBs: `if.end.i` and `f.exit`, then the main is marked **unreachable** in `SCCP`.
https://godbolt.org/

CC @resistor @nikic

**Comment by shafik** [comment]
Note w/ `-fno-strict-aliasing` it returns `0` again: https://godbolt.org/z/hqnxhseE8
