### ISSUE TITLE
[3.0] Non-determinism in self-host on x86-32 linux

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11572]
|  |  |
| --- | --- |
| Bugzilla Link | [11200](https://llvm.org/bz11200) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @stoklund |

## Extended Description 
Using the script utils/release/test-release.sh to do a Release clang self-host,
on 64 bit linux I see the following:

# Comparing Phase 2 and Phase 3 files
file CommandLine.o differs between phase 2 and phase 3
file Path.o differs between phase 2 and phase 3

This is normal: these two files have the path and or date embedded in them
(that should be fixed if possible, but that's another story).

However on 32 bit linux I see:

# Comparing Phase 2 and Phase 3 files
file SparseBitVectorTest.o differs between phase 2 and phase 3
file CXType.o differs between phase 2 and phase 3
file LiveVariables.o differs between phase 2 and phase 3
file PrintfFormatString.o differs between phase 2 and phase 3
file FormatString.o differs between phase 2 and phase 3
file CGDebugInfo.o differs between phase 2 and phase 3
file Lexer.o differs between phase 2 and phase 3
file ExprConstant.o differs between phase 2 and phase 3
file ASTContext.o differs between phase 2 and phase 3
file Expr.o differs between phase 2 and phase 3
file SemaChecking.o differs between phase 2 and phase 3
file SemaExprMember.o differs between phase 2 and phase 3
file SemaType.o differs between phase 2 and phase 3
file ParseDecl.o differs between phase 2 and phase 3
file ParseExprCXX.o differs between phase 2 and phase 3
file ParseStmt.o differs between phase 2 and phase 3
file ClangAttrEmitter.o differs between phase 2 and phase 3
file ClangDiagnosticsEmitter.o differs between phase 2 and phase 3
file MSP430InstrInfo.o differs between phase 2 and phase 3
file TargetData.o differs between phase 2 and phase 3
file AlphaISelDAGToDAG.o differs between phase 2 and phase 3
file X86ISelLowering.o differs between phase 2 and phase 3
file X86FloatingPoint.o differs between phase 2 and phase 3
file X86CodeEmitter.o differs between phase 2 and phase 3
file X86InstrInfo.o differs between phase 2 and phase 3
file X86FastISel.o differs between phase 2 and phase 3
file X86DisassemblerDecoder.o differs between phase 2 and phase 3
file X86AsmParser.o differs between phase 2 and phase 3
file X86AsmBackend.o differs between phase 2 and phase 3
file X86MCCodeEmitter.o differs between phase 2 and phase 3
file BlackfinISelLowering.o differs between phase 2 and phase 3
file BlackfinRegisterInfo.o differs between phase 2 and phase 3
file CBackend.o differs between phase 2 and phase 3
file ARMCodeEmitter.o differs between phase 2 and phase 3
file ARMFastISel.o differs between phase 2 and phase 3
file ARMBaseInstrInfo.o differs between phase 2 and phase 3
file ARMExpandPseudoInsts.o differs between phase 2 and phase 3
file ARMDisassembler.o differs between phase 2 and phase 3
file ARMInstPrinter.o differs between phase 2 and phase 3
file ARMAsmParser.o differs between phase 2 and phase 3
file SystemZISelLowering.o differs between phase 2 and phase 3

file SPUISelDAGToDAG.o differs between phase 2 and phase 3
file SPUISelLowering.o differs between phase 2 and phase 3
file MBlazeDisassembler.o differs between phase 2 and phase 3
file MBlazeAsmParser.o differs between phase 2 and phase 3
file Lint.o differs between phase 2 and phase 3
file ConstantFolding.o differs between phase 2 and phase 3
file LiveVariables.o differs between phase 2 and phase 3
file LiveIntervalAnalysis.o differs between phase 2 and phase 3
file ShrinkWrapping.o differs between phase 2 and phase 3
file PHIElimination.o differs between phase 2 and phase 3
file MachineVerifier.o differs between phase 2 and phase 3
file AsmPrinterDwarf.o differs between phase 2 and phase 3
file DwarfException.o differs between phase 2 and phase 3
file DAGCombiner.o differs between phase 2 and phase 3
file SelectionDAGBuilder.o differs between phase 2 and phase 3
file JITDwarfEmitter.o differs between phase 2 and phase 3
file SimplifyCFG.o differs between phase 2 and phase 3
file AsmLexer.o differs between phase 2 and phase 3
file Function.o differs between phase 2 and phase 3
file ConstantFold.o differs between phase 2 and phase 3
file AsmWriter.o differs between phase 2 and phase 3
file Module.o differs between phase 2 and phase 3
file Instructions.o differs between phase 2 and phase 3
file regexec.o differs between phase 2 and phase 3
file APInt.o differs between phase 2 and phase 3
file CommandLine.o differs between phase 2 and phase 3
file Path.o differs between phase 2 and phase 3
file SubtargetEmitter.o differs between phase 2 and phase 3

**Comment by arsenm** [comment]
Old build issue
