### ISSUE TITLE
LLD strips PC-TABLE data lld:ELF 

### ISSUE THREAD

**Issue by noam1610** [llvm/llvm-project#115706]
I am compiling some C code (hello_world.c) as an example with SanitizerCoverage (trace-pc-guard and pc-table).
Changing the linker to lld (with --fuse-ld=lld) strips the pcs addresses from the table:

Here are the 2 examples:

1. Default linker

Compiling:
```
clang-18 hello_world.c -o hello_world -fsanitize-coverage=trace-pc-guard,pc-table 
```

Looking at the pc-table section in the elf sections ( __sancov_pcs)
```
llvm-readelf-20 ./hello_world -x __sancov_pcs
> 0x00046b70 **50ea0200** 00000000 01000000 00000000
```
You can see that the address of the instrumented basic block is written

2. Using lld as a linker

Compiling:
```
clang-18 hello_world.c -o hello_world -fsanitize-coverage=trace-pc-guard,pc-table  --fuse-ld=lld
```

Looking at the pc-table section in the elf sections ( __sancov_pcs)
```
llvm-readelf-20 ./hello_world -x __sancov_pcs
> 0x00047430 **00000000** 00000000 01000000 00000000
```
You can see that the address of the instrumented basic block is 0

Are there some conflicts between SanitizerCoverage and the Linker ?

**Comment by smithp35** [comment]
I can't reproduce this with a hello world program in a recent source build of clang/lld. `clang version 20.0.0git (git@github.com:llvm/llvm-project.git 5cfc6bc22b6284a2e0b78c71c84d272fcc8ac850)`. I've not tried clang/lld version 18 though.

On my machine:
```
Hex dump of section '__sancov_pcs':
0x00049b70 f00c0300 00000000 01000000 00000000 ................
```
Where 0x30cf0 is the address of main.
```
 1711: 0000000000030cf0    49 FUNC    GLOBAL DEFAULT    14 main
```
In the original object file:
```
Hex dump of section '__sancov_pcs':
0x00000000 00000000 00000000 01000000 00000000 ................

Relocation section '.rela__sancov_pcs' at offset 0x458 contains 1 entries:
    Offset             Info             Type               Symbol's Value  Symbol's Name + Addend
0000000000000000  0000000800000001 R_X86_64_64            0000000000000000 main + 0
```
R_X86_64_64 is a very common and basic relocation that I'd not expect LLD to get wrong without anyone noticing.

It is possible that if the target symbol is an undefined weak reference then 0 will be used as the address. The other thing that could be happening is if the target symbol has STB_LOCAL binding and the compiler (clang) hasn't put the section defining the target symbol and the `__sancov_pcs` section in the same COMDAT group.

I think we need more information to know if there is a problem with LLD, or clang.

**Comment by noam1610** [comment]
Hello

Thank you for your fast answer, I did retry using some docker:

Dockerfile
```
FROM ubuntu:22.04

# Udpate relevant packages 
RUN apt-get update -y && apt-get install -y vim wget curl clang-format clang-tidy clang-tools clang clangd libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python3-clang
RUN apt update -y && apt install -y lsb-release wget software-properties-common gnupg

# Install llvm 20 
RUN wget https://apt.llvm.org/llvm.sh
RUN chmod +x llvm.sh
RUN  ./llvm.sh 20

# Add hello world file
RUN echo '#include <stdio.h>\nint main() {\n   // printf() displays the string inside quotation\n   printf("Hello, World!");\n   return 0;\n}' > hello.c

# Compile it
RUN clang-20 hello.c -o hello -fsanitize-coverage=trace-pc-guard,pc-table -fuse-ld=lld-20

# Save result
RUN llvm-readelf ./hello -x __sancov_pcs > result.txt
```

Just build the docker and look at the result.txt file
```
docker build -f Dockerfile . -t llvm-bug
docker run llvm-bug:latest cat result.txt
```

I got the same 
`
Hex dump of section '__sancov_pcs':
0x0004a650 00000000 00000000 01000000 00000000 ................
`

**Comment by smithp35** [comment]
Thank you I can reproduce it now.

**Comment by smithp35** [comment]
OK I can see the difference. LLD has a different value for the `--apply-dynamic-relocs`. By default LLD does not write the value of symbols subject to dynamic relocation to the file. Instead the dynamic linker will write this at load time. You can add -Wl,--apply-dynamic-relocs` to get LLD to write the value of the symbol and the relocation (the relocation will overwrite the original).

On my system without --apply-dynamic-relocs
```
[28] __sancov_pcs      PROGBITS        000000000004a1a0 0471a0 000010 00  WA  0   0  8

000000000004a1a0  0000000000000008 R_X86_64_RELATIVE                 44a70

Hex dump of section '__sancov_pcs':
0x0004a1a0 00000000 00000000 01000000 00000000 ................
```
With --apply-dynamic-relocs
```
Hex dump of section '__sancov_pcs':
0x0004a1a0 704a0400 00000000 01000000 00000000 pJ..............
```

Hope that answers the question.

**Comment by noam1610** [comment]
Great it works !
Thanks
