### ISSUE TITLE
[libc] fstatvfs_test are failing

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#115795]
fstatvfs_test seems flaky. I wonder if we have some kind of TOCTOU bug in that test where if one VM is running multiple build bots, and that test dies for whatever reason, it might be leaving behind a file the test expects to not exist?

**Comment by nickdesaulniers** [comment]
https://lab.llvm.org/buildbot/#/builders/188/builds/6631/steps/4/logs/stdio:
```
[ RUN      ] LlvmLibcSysFStatvfsTest.FStatvfsInvalidPath
/home/libc_worker/libc-riscv64-debian/libc-riscv64-debian-dbg/llvm-project/libc/test/src/sys/statvfs/linux/fstatvfs_test.cpp:40: FAILURE
Failed to match LIBC_NAMESPACE::mkdirat(AT_FDCWD, TEST_DIR, S_IRWXU) against Succeeds(0).
Expected return value to be equal to 0 but got -1.
Expected errno to be equal to "Success" but got "File exists".
```

**Comment by nickdesaulniers** [comment]
cc @SchrodingerZhu

**Comment by michaelrj-google** [comment]
Should be fixed by https://github.com/llvm/llvm-project/pull/115949. Closing for now.
