### ISSUE TITLE
determine unwished/optional side effects

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11575]
|  |  |
| --- | --- |
| Bugzilla Link | [11203](https://llvm.org/bz11203) |
| Version | trunk |
| OS | All |
| Attachments | [Readable unoptimized code (look at global.init$)](https://user-images.githubusercontent.com/60944935/143744124-f9dcb939-0a84-4cc6-a5d0-ae5beb53a03a.gz), [Optimized test case](https://user-images.githubusercontent.com/60944935/143744125-7621fd44-8042-4a62-9114-93e0bdf69536.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I have a language that has a garbage collector. Garbage collected items are inserted into a linked list which confuses the optimizer.
What I want is to make this list insertion optional so that the alloc+insert is only performed when the resulting value is used.

The idea is to introduce a function modifier that indicates that the function is unnecessary when it's result value is not used and so all the side effects of calling this function can be ignored.
This allows me lots of very aggressive optimizations because i can tell the compiler which side effects are unwanted.
The function should of course not be inlined until the compiler knows that the result is really never used (worst case: never).

Other use cases are:
 - Allocating garbage collected ram
 - Counters that should react to optimizations (count how often the mem is readed)
 - in-llvm based branch prediction profiling

**Comment by arsenm** [comment]
> The idea is to introduce a function modifier that indicates that the function is unnecessary when it's result value is not used and so all the side effects of calling this function can be ignored.

There are a lot more optimization attributes now than there were in 2011, some combination of them probably work in this case
