### ISSUE TITLE
Backport #113446 to 19.x

### ISSUE THREAD

**Issue by anutosh491** [llvm/llvm-project#115827]
Hi,

I am interested in a PR #113446 that I would like to have in the release (if possible in 19.1.4) 
The PR works towards allowing clang-repl to run in the browser. It is a small but essential change.

**Comment by anutosh491** [comment]
cc @aheejin

**Comment by aheejin** [comment]
You can request for a backport merge with this process: https://llvm.org/docs/GitHub.html#backporting-fixes-to-the-release-branches

**Comment by anutosh491** [comment]
> You can request for a backport merge with this process

Thanks. I hope should be enough (I thought it is only a maintainer that could probably pick commit for a release)

**Comment by aheejin** [comment]
I am not a release maintainer either 😀

**Comment by aheejin** [comment]
> /cherry-pick [d61f58f](https://github.com/llvm/llvm-project/commit/d61f58f66839652ec4c1101521c2a7297cffacff)

Re-posting this after adding the milestone

**Comment by aheejin** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/d61f58f66839652ec4c1101521c2a7297cffacff

Re-posting this after adding the milestone

**Comment by anutosh491** [comment]
Hi @tru 

Could you maybe tell us if we're doing something wrong here. Just did what the docs suggested.

**Comment by aheejin** [comment]
It says the cherry-pick failed because of conflicts. I think you should do a cherry-pick of the commit on top of `release/19.x` branch, resolve conflicts locally, and create a PR against the `release/19.x` branch as the doc says.

**Comment by tru** [comment]
What @aheejin said. There are conflicts so you need to manually resolve those.

**Comment by anutosh491** [comment]
Well I don't think I have a conflicts issue. I am seeing this (https://github.com/llvm/llvm-project/actions/runs/11793878279) 
```
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git cherry-pick -x d61f58f66839652ec4c1101521c2a7297cffacff
  stderr: 'fatal: bad object d61f58f66839652ec4c1101521c2a7297cffacff'
  
```

**Comment by anutosh491** [comment]
Here's one with the same changes as https://github.com/llvm/llvm-project/commit/d61f58f66839652ec4c1101521c2a7297cffacff
https://github.com/llvm/llvm-project/pull/115846

Not sure I could do a cherry pick as @aheejin suggested.

**Comment by aheejin** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/075581f34035c01659cc883d0d69336c279ef0d5

#113446's commit is https://github.com/llvm/llvm-project/commit/075581f34035c01659cc883d0d69336c279ef0d5. I think we should cherry-pick this one
