### ISSUE TITLE
3.0rc1: clang/Basic/DiagnosticCommonKinds.inc not being installed

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11604]
|  |  |
| --- | --- |
| Bugzilla Link | [11232](https://llvm.org/bz11232) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @tomilov |

## Extended Description 
1. Download 3.0rc1 and clang-3.0rc1 as source
2. Untar them, move clang to be in tools/clang
3. ./configure --prefix=/tmp/llvmx
4. make install ...

% echo "#include <clang/Frontend/CompilerInstance.h>" | clang -x c++ -c - -I/tmp/llvmx/include -o /dev/null
In file included from <stdin>:1:
In file included from /tmp/llvmx/include/clang/Frontend/CompilerInstance.h:13:
In file included from /tmp/llvmx/include/clang/Frontend/CompilerInvocation.h:19:
In file included from /tmp/llvmx/include/clang/Frontend/DiagnosticOptions.h:13:
In file included from /tmp/llvmx/include/clang/Basic/Diagnostic.h:17:
/tmp/llvmx/include/clang/Basic/DiagnosticIDs.h:53:10: fatal error: 'clang/Basic/DiagnosticCommonKinds.inc' file not found
#include "clang/Basic/DiagnosticCommonKinds.inc"
         ^
1 error generated.
%

Copying DiagnosticCommonKinds.inc from the source dir to the appropriate place in the install dir fixes this.  (I'm not sure if other things from clang are being missed during the install step as well, though.)

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
