### ISSUE TITLE
Is it ok to call `DiagEngine->getDiagnosticIDs()->getCustomDiagID()` with a runtime string?

### ISSUE THREAD

**Issue by GKxxUCAS** [llvm/llvm-project#116169]
I need to create diagnostics from runtime strings. I found two ways: one is to use `clang::DiagnosticsEngine::getCustomDiagID`, the other is to use `clang::DiagnosticIDs::getCustomDiagID`. The former accepts the string in the form of `const char (&)[N]`, which cannot accept runtime strings. The latter accepts a `StringRef`, but there is a comment on that saying

```cpp
  // FIXME: Replace this function with a create-only facilty like
  // createCustomDiagIDFromFormatString() to enforce safe usage. At the time of
  // writing, nearly all callers of this function were invalid.
  unsigned getCustomDiagID(Level L, StringRef FormatString);
```

I'm not sure what it means by "nearly all callers of this function were invalid". How can I make a "valid" call to it?

`ClangTidyContext::diag` uses `DiagEngine->getDiagnosticIDs()->getCustomDiagID()` to create diagnostics from possibly runtime determined strings. It this also an "invalid" caller to that function?

Moreover, a related commit [29cb66b](https://github.com/llvm/llvm-project/commit/29cb66ba2f0b251a430941d00eea305b6d6c6966) seems to suggest against non-constant format strings.

**Comment by AaronBallman** [comment]
Letting the user specify the diagnostic string means that the user can define strings the diagnostic engine doesn't expect and will crash on. Using constant strings makes it less likely to pass malformed data that will crash.

> I'm not sure what it means by "nearly all callers of this function were invalid". How can I make a "valid" call to it?

You shouldn't call `DiagnosticIDs::getCustomDiagID()`, that interface should be only called by `DiagnosticsEngine::getCustomDiagID()` (in fact, I think we can make it private and `friend` the diagnostics engine at this point, there seem to be no more extant calls to the IDs-based version).

If you need to let users create the format strings, you'll need to sanitize that data before passing it along to create the custom diagnostic. That's going to involve handling things like `%`, non-null-terminated strings, etc.

Closing the issue but if you have more questions on the same topic, feel free to reopen.
