### ISSUE TITLE
Hello, where can I see how to compile C++ code?

### ISSUE THREAD

**Issue by aedjof** [llvm/llvm-project#116164]
Hello, where can I see how to compile C++ code?

**Comment by EugeneZelenko** [comment]
See https://clang.llvm.org/docs/UsersManual.html.

**Comment by aedjof** [comment]
> См. https://clang.llvm.org/docs/UsersManual.html . https://godbolt.org должен быть полезен.

I looked but I don’t see anything about C++ there. It's only about flags and the like. If there is, what is the item called?
