### ISSUE TITLE
Requesting Github CI/CD access for boomanaiden154

### ISSUE THREAD

**Issue by boomanaiden154** [llvm/llvm-project#116123]
In accordance with https://github.com/llvm/llvm-project/pull/115321, I'm filing this issue to request to be granted the Github CI/CD role.

I'm working on moving the current premerge infrastructure for X86 Linux and Windows to Github Actions from the current Buildkite setup. It would help to have additional permissions on the Github side so I do not have to bother the LLVM Admins everytime we need to change something/grab tokens/etc.

**Comment by tstellar** [comment]
I am in favor of this, @boomanaiden154 has been helping to maintain the GitHub Actions infrastructure for a while has done a good job.

**Comment by tstellar** [comment]
@boomanaiden154 I've added you to the CI/CD admins team now.  Let me know if you have any issues.

**Comment by boomanaiden154** [comment]
Thank you!
