### ISSUE TITLE
OpenMP offloading failure in LLVM 15 or later versions on multiple and different AMD GPUs and a found solution

### ISSUE THREAD

**Issue by tkojima0107** [llvm/llvm-project#116162]
After changing nextgen driver as default in LLVM 15,
OpenMP offloading fails if multiple and different AMD GPUs are installed in the host machine, even though the correct GPU architecture is specified in the compilation time.

I had conducted several experiments to confirm the issue and found a solution to it.

On the host machine with Radeon RX 6950 XT (gfx1030) and Radeon RX 7900 XTX (gfx1100),
I compiled the following code to offload to gfx1100.
```
clang++ -O3 --offload-arch=gfx1100 -fopenmp offload.cpp
```

Then, Debug type build of libomptarget was used to trace the issue.
Here is an interesting part of the debug output.

```
TARGET AMDGPU RTL --> gfx1100                                                                                                                                                   │=
TARGET AMDGPU RTL --> Compatible: Exact match   [Image: gfx1100]        :       [Env: gfx1100]                                                                                  │=
TARGET AMDGPU RTL --> gfx1030                                                                                                                                                   │=
TARGET AMDGPU RTL --> Incompatible: Processor mismatch  [Image: gfx1100]        :       [Env: gfx1030]                                                                          │=
PluginInterface --> Image is notcompatible with current environment: gfx1100                                                                                                    │=
Libomptarget --> Image 0x000055bcc7a01090 is NOT compatible with RTL libomptarget.rtl.amdgpu.so!  
```

Even though the image is regarded as compatible with gfx1100 at the early stage, it finally becomes incompatible with that environment.

This issue does not occur with ROCm LLVM developed by AMD.

Thus, I compered both libomptarget implementations in the original LLVM and the ROCm one to find the difference.

In LLVM 17.0.6 https://github.com/llvm/llvm-project/blob/6009708b4367171ccdbf4b5905cb6a803753fe18/openmp/libomptarget/plugins-nextgen/amdgpu/src/rtl.cpp#L2697,
It seems that the image must be compatible with all GPUs in the host machine due to the last if statement.
```
Expected<bool> isImageCompatible(__tgt_image_info *Info) const override {
    for (hsa_agent_t Agent : KernelAgents) {
      std::string Target;
      auto Err = utils::iterateAgentISAs(Agent, [&](hsa_isa_t ISA) {
        uint32_t Length;
        hsa_status_t Status;
        Status = hsa_isa_get_info_alt(ISA, HSA_ISA_INFO_NAME_LENGTH, &Length);
        if (Status != HSA_STATUS_SUCCESS)
          return Status;

        // TODO: This is not allowed by the standard.
        char ISAName[Length];
        Status = hsa_isa_get_info_alt(ISA, HSA_ISA_INFO_NAME, ISAName);
        if (Status != HSA_STATUS_SUCCESS)
          return Status;

        llvm::StringRef TripleTarget(ISAName);
        if (TripleTarget.consume_front("amdgcn-amd-amdhsa"))
          Target = TripleTarget.ltrim('-').str();
        return HSA_STATUS_SUCCESS;
      });
      if (Err)
        return std::move(Err);

      if (!utils::isImageCompatibleWithEnv(Info, Target))
        return false;
    }
    return true;
  }
```

On the other hands,
in ROCm LLVM 6.2.1
https://github.com/ROCm/llvm-project/blob/669db884972e769450470020c06a6f132a8a065b/openmp/libomptarget/plugins-nextgen/amdgpu/src/rtl.cpp#L3550,
it seems to check there is at least one compatible GPU in the host machine.

```
Expected<bool>
  isImageCompatible(__tgt_image_info *Info,
                    __tgt_device_image *TgtImage) const override {

    for (hsa_agent_t Agent : KernelAgents) {
      std::string Target;
      auto Err = utils::iterateAgentISAs(Agent, [&](hsa_isa_t ISA) {
        uint32_t Length;
        hsa_status_t Status;
        Status = hsa_isa_get_info_alt(ISA, HSA_ISA_INFO_NAME_LENGTH, &Length);
        if (Status != HSA_STATUS_SUCCESS)
          return Status;

        // TODO: This is not allowed by the standard.
        char ISAName[Length];
        Status = hsa_isa_get_info_alt(ISA, HSA_ISA_INFO_NAME, ISAName);
        if (Status != HSA_STATUS_SUCCESS)
          return Status;

        llvm::StringRef TripleTarget(ISAName);
        if (TripleTarget.consume_front("amdgcn-amd-amdhsa"))
          Target = TripleTarget.ltrim('-').str();
        return HSA_STATUS_SUCCESS;
      });
      if (Err)
        return std::move(Err);

      if (utils::isImageCompatibleWithEnv(Info, Target))
        return true;
    }
```

Does the original LLVM implementation assume that the host machine has the same GPUs?

If yes, I guess limiting the visible GPUs only to the target GPU might be a solution with setting `ROCR_VISIBLE_DEVICES` environment variable.

**Comment by jhuber6** [comment]
This was already fixed in https://github.com/llvm/llvm-project/commit/435aa7663d56e7216ad148ede3a422675b5f2be1. You are comparing an old version of LLVM with a new version of the ROCm fork.
