### ISSUE TITLE
known constant not folded: new() + 4 != 0

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#11613]
|  |  |
| --- | --- |
| Bugzilla Link | [11241](https://llvm.org/bz11241) |
| Version | trunk |
| OS | Linux |
| Attachments | [Testcase](https://user-images.githubusercontent.com/92601262/143744180-f6222750-ef61-454c-9940-a7767921c14b.gz) |
| CC | @chandlerc,@nlewycky |

## Extended Description 

This IR:
```
  %alloc2 = tail call noalias i8* @&#8203;_Znwm(i64 8) nounwind
  %add = getelementptr inbounds i8* %alloc2, i64 4
  %always_false = icmp eq i8* %add, null
  ret i1 %always_false
```
... is collapsed to "ret i1 0". However, this IR:
```
  %alloc2 = tail call noalias i8* @&#8203;_Znwm(i64 8) nounwind
  %add = getelementptr inbounds i8* %alloc2, i64 4
  %always_false = icmp eq i8* %add, null
  br i1 %always_false, label %skipinit2, label %init2

init2:                                            ; preds = %entry
  store i8 1, i8* %alloc2, align 1
  ret void

skipinit2:                                        ; preds = %entry
  ret void
```
... is not optimized any further.

**Comment by philnik777** [comment]
Closing, since the reproducer doesn't work anymore.
