### ISSUE TITLE
Assertion failed: "Cannot split critical edge from IndirectBrInst" with constant expression in PHI

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#11618]
|  |  |
| --- | --- |
| Bugzilla Link | [11246](https://llvm.org/bz11246) |
| Version | unspecified |
| OS | All |
| Attachments | [Testcase](https://user-images.githubusercontent.com/56606707/143744182-a673ea38-cb39-454f-8614-18e4d300dd26.gz) |
| CC | @atrick,@fhahn |

## Extended Description 

Testcase attached; llc crashes with:

Assertion failed: (!isa<IndirectBrInst>(TI) && "Cannot split critical edge from IndirectBrInst"), function SplitCriticalEdge, file /Volumes/storage/llvm/lib/Transforms/Utils/BreakCriticalEdges.cpp, line 175.

Not sure anyone is actually likely to hit this in practice, but it seems possible.

**Comment by nikic** [comment]
This is resolved by the removal of trapping constant expressions (and thus also the need to perform critical edge splitting here).
