### ISSUE TITLE
Clang fails to warn -Wunused-private-field

### ISSUE THREAD

**Issue by VitorRamos** [llvm/llvm-project#116270]
clang version: 19.1
os: ubuntu 22.04

```c++
class A
{
public:
   A() : m_x(0)
   {
   }
private:
   const int m_x;
};

#ifdef BUG
class C
{
    friend auto operator==(C, C) -> bool = default;
};
#endif

int main()
{
   [[maybe_unused]] auto c = A();
}
```

clang++ -std=c++20 -Wall main.cpp

```
main.cpp:8:14: warning: private field 'm_x' is not used [-Wunused-private-field]
    8 |    const int m_x;
      |              ^
1 warning generated.
```

clang++ -DBUG -std=c++20 -Wall main.cpp

no warnings

**Comment by VitorRamos** [comment]
Bisected to  https://github.com/llvm/llvm-project/commit/78d404a11dd33c8349fd9b6ef5876d523c457f0e seems like that fix should be limited to the class that has the default comparison operator.

**Comment by whiteio** [comment]
Hey! Could I be assigned to this please?
