### ISSUE TITLE
[Github] Run failed: Labelling new pull requests

### ISSUE THREAD

**Issue by Sirraide** [llvm/llvm-project#116322]
I’m getting some emails about a workflow failing on #115144:
- https://github.com/llvm/llvm-project/actions/runs/11847602248
- https://github.com/llvm/llvm-project/actions/runs/11850756309

CC @tstellar, @boomanaiden154

**Comment by boomanaiden154** [comment]
Seems like a permissions issue with the token. @tstellar or one of the other LLVM admins will probably have to regenerate the token.

**Comment by boomanaiden154** [comment]
This should be fixed now. It was a permissions issue according `#build-systems` on Discord.
