### ISSUE TITLE
Error with unicode.h using clang 19.1.4

### ISSUE THREAD

**Issue by AnonimiAngels** [llvm/llvm-project#116378]
CMakeLists.txt has been modified, regenerating build environment.
-- The C compiler identification is Clang 19.1.4
-- The CXX compiler identification is Clang 19.1.4
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/llvm-19/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/llvm-19/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1")
-- Checking for module 'libssh2'
--   Found libssh2, version 1.11.0
-- Using the multi-header code from /mnt/d/dev/astorbench_v2/build/_deps/json-src/include/
-- Configuring done (12.4s)
-- Generating done (0.1s)
-- Build files have been written to: /mnt/d/dev/astorbench_v2/build
[35/40] Building CXX object CMakeFiles/astorbench_v2.dir/mnt/d/dev/astorbench_v2/src/main.cpp.o
FAILED: CMakeFiles/astorbench_v2.dir/mnt/d/dev/astorbench_v2/src/main.cpp.o
/usr/lib/llvm-19/bin/clang++ -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -I/mnt/d/dev/astorbench_v2/inc -I/mnt/d/dev/astorbench_v2/inc/logics -I/mnt/d/dev/astorbench_v2/inc/objects -I/mnt/d/dev/astorbench_v2/inc/stb -I/mnt/d/dev/astorbench_v2/build/_deps/imgui-src -I/mnt/d/dev/astorbench_v2/build/_deps/imgui-src/backends -I/mnt/d/dev/astorbench_v2/build/_deps/json-src/include  -g -std=gnu++23 -flto=thin -MD -MT CMakeFiles/astorbench_v2.dir/mnt/d/dev/astorbench_v2/src/main.cpp.o -MF CMakeFiles/astorbench_v2.dir/mnt/d/dev/astorbench_v2/src/main.cpp.o.d @CMakeFiles/astorbench_v2.dir/mnt/d/dev/astorbench_v2/src/main.cpp.o.modmap -o CMakeFiles/astorbench_v2.dir/mnt/d/dev/astorbench_v2/src/main.cpp.o -c /mnt/d/dev/astorbench_v2/src/main.cpp
In file included from /mnt/d/dev/astorbench_v2/src/main.cpp:1:
In file included from /mnt/d/dev/astorbench_v2/inc/main.hpp:5:
In file included from /mnt/d/dev/astorbench_v2/inc/render_manager.hpp:5:
In file included from /mnt/d/dev/astorbench_v2/inc/globals.hpp:16:
In file included from /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/chrono:45:
In file included from /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/sstream:40:
In file included from /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/istream:41:
In file included from /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/ostream:43:
In file included from /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/format:58:
/usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/unicode.h:802:4: error: expression is not assignable
  802 |           ++this;
      |           ^ ~~~~
1 error generated.

What can i do to fix this issue?

**Comment by AnonimiAngels** [comment]
Installed with following script

sudo apt update -y && sudo apt dist-upgrade -y
echo "deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-19 main" | sudo tee /etc/apt/sources.list.d/llvm.list
wget https://apt.llvm.org/llvm-snapshot.gpg.key
sudo gpg --dearmor -o -y /usr/share/keyrings/llvm-archive-keyring.gpg llvm-snapshot.gpg.key
sudo rm llvm-snapshot.gpg.key
sudo apt install -y llvm-19 clang-19 clang-format-19 libc++-19-dev cmake ninja-build clang fonts-firacode python3 doxygen gdb kali-win-kex graphviz libspdlog-dev g++-14 clang-tools-17 pngquant libglfw3-dev ffmpeg libglew-dev uuid-dev vpx-tools zenity clang-tools-19
sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-19 100
sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-19 100
sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-19 100
sudo update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-19 100
sudo update-alternatives --install /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-19 100

**Comment by AaronBallman** [comment]
This is an issue with libstdc++ which has already been fixed in 14.2: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115119

**Comment by AnonimiAngels** [comment]
> This is an issue with libstdc++ which has already been fixed in 14.2: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115119

Im already using the 14.2

ii  libstdc++-14-dev:amd64                         14-20240330-1                                                   amd64        GNU Standard C++ Library v3 (development files)
ii  libstdc++6:amd64                               14-20240330-1                                                   amd64        GNU Standard C++ Library v3

**Comment by AaronBallman** [comment]
> > This is an issue with libstdc++ which has already been fixed in 14.2: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115119
> 
> Im already using the 14.2
> 
> ii libstdc++-14-dev:amd64 14-20240330-1 amd64 GNU Standard C++ Library v3 (development files) ii libstdc++6:amd64 14-20240330-1 amd64 GNU Standard C++ Library v3

2024-03-30 looks too old to be 14.2, which was released 2024-08-01 (https://gcc.gnu.org/gcc-14/), but maybe I'm missing something?

**Comment by AnonimiAngels** [comment]
> > > This is an issue with libstdc++ which has already been fixed in 14.2: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115119
> > 
> > 
> > Im already using the 14.2
> > ii libstdc++-14-dev:amd64 14-20240330-1 amd64 GNU Standard C++ Library v3 (development files) ii libstdc++6:amd64 14-20240330-1 amd64 GNU Standard C++ Library v3
> 
> 2024-03-30 looks too old to be 14.2, which was released 2024-08-01 (https://gcc.gnu.org/gcc-14/), but maybe I'm missing something?
My bad, i tought i already updated to 14.2
