### ISSUE TITLE
[clang] Miscompile at O3 with SIGKILL

### ISSUE THREAD

**Issue by cardigan1008** [llvm/llvm-project#116483]
When I compiled this code with -O3, it triggered SIGKILL. With -O0/1/2, it returned 0.

Bisected to https://github.com/llvm/llvm-project/commit/254da5ab8bce846bcbac9862f31c1891d8feea44, which was committed by @RKSimon 

Compiler Explorer: https://godbolt.org/z/oE87zTxGf

Code:
```c
int printf(const char *, ...);
int a, b, c, e, f;
long k, l;
void m(int n) {
  b = 1;
  for (; b <= n; b++)
    for (; c; c++)
      ;
}
long o(long n) {
  long g = 0, i = 1, j = n;
  char h = 0;
  while (j > 0) {
    char d = j & i;
    if (d)
      g += i << h;
    j >>= 1;
    h++;
  }
  g *= h % 2 == 0 ? 2 : 3;
  return g;
}
long p(unsigned short n) {
  for (; e;)
    if (f)
      return 0;
  return n;
}
int main() {
  k = o(207 + 122);
  l = p((char)k);
  m(l);
  printf("%X\n", a);
}
```

**Comment by DimitryAndric** [comment]
It's interesting though, for me it appears to work fine, but I am trying this on FreeBSD. It does not even use a huge amount of memory:

```text
$ time -l ~/ins/llvmorg-20-init-12185-g6fb7cdff3d9/bin/clang -cc1 -triple x86_64-unknown-freebsd13.2 -emit-obj -disable-free -clear-ast-before-backend -main-file-name pr116483.cpp -mrelocation-model static -mframe-pointer=all -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/home/dim/bugs/pr116483 -fcoverage-compilation-dir=/home/dim/bugs/pr116483 -resource-dir /home/dim/ins/llvmorg-20-init-12185-g6fb7cdff3d9/lib/clang/20 -internal-isystem /usr/include/c++/v1 -internal-isystem /home/dim/ins/llvmorg-20-init-12185-g6fb7cdff3d9/lib/clang/20/include -internal-externc-isystem /usr/include -O3 -fdeprecated-macro -ferror-limit 19 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fcxx-exceptions -fexceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o pr116483.o -x c++ pr116483.cpp
        0.06 real         0.05 user         0.00 sys
     79536  maximum resident set size
     74708  average shared memory size
       812  average unshared data size
       128  average unshared stack size
      1460  page reclaims
         0  page faults
         0  swaps
         0  block input operations
         3  block output operations
         0  messages sent
         0  messages received
         0  signals received
         2  voluntary context switches
         1  involuntary context switches
```

Can you get a core dump or backtrace from this crash?

**Comment by RKSimon** [comment]
The commit was just a cost table update so will have just exposed an existing issue.

**Comment by antoniofrighetto** [comment]
This looks somewhat nasty. Started to appear after 0289dad538fa2fdc1a82a26f5d19f94fbd20d949, though I can't see any visible issues with the folding. This folding (we deal with a xor of and instead of a or disjoint of and) allows IndVarsSimplify to simplify two branch conditions to false, whose both folded conditions seem okay (I'm sure with the first one, slightly less with the second one, but https://alive2.llvm.org/ce/z/W83Xrz looks fine, unless wrong src/tgt unroll bound). This latter simplification seems to have introduced an infinite loop. cc/ @dtcxzyw, feel free to take a look at this, if you wish. :)

**Comment by dtcxzyw** [comment]
I cannot reproduce the problem with 

> This looks somewhat nasty. Started to appear after [0289dad](https://github.com/llvm/llvm-project/commit/0289dad538fa2fdc1a82a26f5d19f94fbd20d949), though I can't see any visible issues with the folding. This folding (we deal with a xor of and instead of a or disjoint of and) allows IndVarsSimplify to simplify two branch conditions to false, whose both folded conditions seem okay (I'm sure with the first one, slightly less with the second one, but https://alive2.llvm.org/ce/z/W83Xrz looks fine, unless wrong src/tgt unroll bound). This latter simplification seems to have introduced an infinite loop. cc/ @dtcxzyw, feel free to take a look at this, if you wish. :)

Unroll size should be 65500 :)

**Comment by dtcxzyw** [comment]
Reproducer: https://godbolt.org/z/aM9acE77v
llvm version: 0ff8b79160509b25fd913ffa320b9dab5b87b55e
```
; bin/opt -passes=indvars test.ll -S
define i32 @main() {
entry:
  %xor = xor i32 0, 3
  %mul = mul i32 %xor, 329
  %conv = trunc i32 %mul to i16
  %sext = shl i16 %conv, 8
  %conv1 = ashr i16 %sext, 8
  %conv3 = zext i16 %conv1 to i32
  br label %loop.body

loop.body:
  %indvar = phi i32 [ %indvar.inc, %loop.body ], [ 1, %entry ]
  %indvar.inc = add nuw i32 %indvar, 1
  %exitcond = icmp eq i32 %indvar, %conv3
  br i1 %exitcond, label %exit, label %loop.body

exit:
  ret i32 %conv3
}
```
```
; ModuleID = 'test.ll'
source_filename = "test.ll"

define i32 @main() {
entry:
  %xor = xor i32 0, 3
  %mul = mul i32 %xor, 329
  %conv = trunc i32 %mul to i16
  %sext = shl i16 %conv, 8
  %conv1 = ashr i16 %sext, 8
  br label %loop.body

loop.body:                                        ; preds = %loop.body, %entry
  br i1 false, label %exit, label %loop.body

exit:                                             ; preds = %loop.body
  %conv3 = zext i16 %conv1 to i32
  ret i32 %conv3
}
```

**Comment by dtcxzyw** [comment]
@antoniofrighetto I used https://github.com/dtcxzyw/llvm-ub-aware-interpreter for debugging and test reduction. EMI-based automatic test reduction is coming soon :)

**Comment by antoniofrighetto** [comment]
@dtcxzyw Oh, that's very cool! Thank you for sharing it :)
