### ISSUE TITLE
Undesired AST printout for PackIndexingExpr

### ISSUE THREAD

**Issue by zyn0217** [llvm/llvm-project#116486]
Given

```cpp
template <class... T, unsigned N>
auto foo(T ...params) {
  return params...[N];
}
```

Running `clang -std=c++2c -fsyntax-only -Xclang -ast-print` on it results in

```
template <class ...T, unsigned int N> auto foo(T ...params) {
    return 0xd3cffc0...[0xd3cffe0];
}
```

https://compiler-explorer.com/z/czchqqj1s

The cause is due to the inadvertent use of `operator <<` in `clang/lib/AST/StmtPrinter.cpp`:

https://github.com/llvm/llvm-project/blob/e508bacce45d4fb2ba07d02c55391b858000c3b3/clang/lib/AST/StmtPrinter.cpp#L2519-L2521

Any `PackIndexingExpr` would be printed as their addresses rather than intelligible source codes, contrary to the behavior for any other expressions.

We should use `PrintExpr()` anyway.

**Comment by kmr-srbh** [comment]
Hello! I am new to the LLVM codebase. I would love to work on this issue. Could I be assigned this?

**Comment by zyn0217** [comment]
@kmr-srbh Here it is. Happy hacking!
