### ISSUE TITLE
[MLIR] affineexpr parser emitError when b.getAffineDimExpr(0) * b.getAffineDimExpr(1)

### ISSUE THREAD

**Issue by enjustli** [llvm/llvm-project#116401]
from https://github.com/llvm/llvm-project/pull/78855/files#diff-67742c4ca42f128ad1a690d256faf13b7c8f6c66e66ae47fbfb1869b52f4e0d2R25 , 
<img width="799" alt="image" src="https://github.com/user-attachments/assets/0bad8fac-a07d-4b64-a8e8-ce8170149e6c">

if this is write in mlir file and then parse it, it will be failed in https://github.com/llvm/llvm-project/blob/main/mlir/lib/AsmParser/AffineParser.cpp#L125
<img width="959" alt="image" src="https://github.com/user-attachments/assets/689b7c4f-2bbc-4b79-a403-f3544df41af1">

**Comment by enjustli** [comment]
@ubfx

**Comment by ubfx** [comment]
`d0 * d1` is not a valid affine expression, so the parser error is correct.
We are a little less strict when constructing `AffineExpr` (see here: https://github.com/llvm/llvm-project/pull/103010) which is why the test works.
