### ISSUE TITLE
[flang] compiler is not able to scan the continuation line in presence of preprocessed output 

### ISSUE THREAD

**Issue by shivaramaarao** [llvm/llvm-project#116578]
The following file is generated after preprocessing the source code.
test2.f90:
                  integer, allocatable :: array(:)
                  integer, allocatable :: source(:)
                  allocate (array,&
#76 "test2.F90"
                      & source=source)
                  end program

flang compiler fails to compile above file with following error.
flang test2.f90
error: Could not scan test2.f90
test2.F90:76:38: error: Unmatched ')'
                        & source=source)

if the preprocessed line is moved above allocate statement, the test works fine.

**Comment by klausler** [comment]
Works with current top of llvm-project/main tree.
