### ISSUE TITLE
[flang] missing diagnostic for bind(c) derived type with noninteroperable component

### ISSUE THREAD

**Issue by kkwli** [llvm/llvm-project#116574]
```fortran
type dt0
  real :: x
end type
type, bind(c) :: xdt
  type(dt0) :: y
end type
end
```

R726: "Each component of a derived type with the BIND attribute shall be a nonpointer, nonallocatable data component with interoperable type and type parameters."

**Comment by klausler** [comment]
When a derived type meets all of the requirements for interoperability, it is treated as an interoperable type even without `BIND(C)`.  Compile with `-pedantic` to observe a warning for these cases, e.g. "warning: Derived type of component 'y' of an interoperable derived type should have the BIND attribute".  This behavior is a documented extension.

**Comment by kkwli** [comment]
@klausler Thanks for the quick response. On AIX, we are working on having different alignment for interoperable and noninteroperable derived types. So we will assume that non-`bind(c)` derived type component in a `bind(c)` derived type as interoperable.
