### ISSUE TITLE
read of string to integer variable fails on internal compiler error

### ISSUE THREAD

**Issue by zrick** [llvm/llvm-project#116586]
The following snippet of code fails on a compiler error with the amdflang-new compiler (see attached log file) 

`program TEST

  implicit none 
  
  integer(4) nrun, stat
  character(len=20) :: nrun_string

  call GetArg(1,nrun_string)
  read(nrun_string,iostat=stat) nrun

  
end program TEST
`

[flang-new.txt](https://github.com/user-attachments/files/17797065/flang-new.txt)

**Comment by klausler** [comment]
The program is attempting unformatted internal input, which is not a thing in Fortran.  Semantic checking should have produced a fatal error message; will fix.  Change to `read(nrun_string,*,iostat=stat) nrun` to fix the program.
