### ISSUE TITLE
Assertion when using analysis results from a CallGraphSCCPass in a ModulePass

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11659]
|  |  |
| --- | --- |
| Bugzilla Link | [11287](https://llvm.org/bz11287) |
| Version | trunk |
| OS | Linux |
| Attachments | [Example that produces the assertion](https://user-images.githubusercontent.com/60944935/143744215-f350d3e2-b5dd-47a5-a7bc-deb12b17b441.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

When trying to add a CallGraphSCCPass as a required pass for a ModulePass, the following assertion is raised:

opt: /.../llvm/lib/Analysis/IPA/CallGraphSCCPass.cpp:535: virtual void llvm::CallGraphSCCPass::assignPassManager(llvm::PMStack&, llvm::PassManagerType): Assertion `!PMS.empty() && "Unable to handle Call Graph Pass"' failed.

I've attached an example file.

Since I'm not completely sure if this is a bug, I tried asking on the mailing list (http://lists.cs.uiuc.edu/pipermail/llvmdev/2011-October/043987.html) first but didn't get any responses.

**Comment by gandhi56** [comment]
I fixed the path by replacing the first line with `#include "llvm/Analysis/CallGraphSCCPass.h"`. With that, I don't see the assertion failure.
