### ISSUE TITLE
[NVPTX] Lower `dynamic_stackallloc` in Instruction Selection instead of Operation Legalization

### ISSUE THREAD

**Issue by justinfargnoli** [llvm/llvm-project#116697]
Currently, we [lower `dynamic_stackalloc` during operation legalization](https://github.com/llvm/llvm-project/blob/e0b522dd94e48229d587a54a3103ba1c198b16a7/llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp#L2275-L2304). However, if we are okay with losing the friendlier error message we could decare this operation as legal and handle is during [instruction selection](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/NVPTX/NVPTXInstrInfo.td).

This would require declaring [`ISD::DYNAMIC_STACKALLOC`](https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/CodeGen/ISDOpcodes.h#L1105-L1112) in [`TargetSelectionDAG.td`](https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/Target/TargetSelectionDAG.td) and lowering it in [NVPTXInstrInfo.td](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/NVPTX/NVPTXInstrInfo.td)

**Comment by AlexMaclean** [comment]
I'm not sure this is a good idea, we actually have a fair bit of logic in this function, representing that in table-gen may not be so clean. If anything, we should pull the address-space cast out of the instruction itself and add that in the legalization as well, allowing for more combines to occur.

**Comment by pdoundka** [comment]
Hey, can you assign this to me?

**Comment by justinfargnoli** [comment]
@pdoundka, in light of @AlexMaclean's comment, I will close this issue until I understand if this approach is a good idea. 

However, if you feel that this approach makes sense, please feel free to put up a PR with the change! I'd happily review it and learn about how you tackled this issue.
