### ISSUE TITLE
Weird behavior when returning pointer to static local variable from consteval function

### ISSUE THREAD

**Issue by Eczbek** [llvm/llvm-project#116672]
https://godbolt.org/z/j58z8175s

```cpp
#include <print>

consteval const int* foo() {
	static constexpr int x = 5;
	return &x;
}

int main() {
	std::print("{}", *foo());
}
```

GCC prints `5` as expected, but Clang prints `0`.

**Comment by Fznamznon** [comment]
Perhaps a duplicate of https://github.com/llvm/llvm-project/issues/82994 .

**Comment by Eczbek** [comment]
> Perhaps a duplicate of #82994 .

Looks like it.
