### ISSUE TITLE
__builtin_wcslen is not a constant expression when using -fexperimental-new-constant-interpreter

### ISSUE THREAD

**Issue by OgnianM** [llvm/llvm-project#116638]
https://godbolt.org/z/T64z6r5b5
Practically, this means that just including `<iostream>` breaks compilation.

I can look into it later if nobody has any immediate ideas.

**Comment by tbaederr** [comment]
The plan is to implement the other strlen/memcpy/memcmp builtins using the bitcast facilities, which is what I'm working on at the moment.

**Comment by frederick-vs-ja** [comment]
Looks like that we should add workaround to libc++ in the meanwhile.

**Comment by OgnianM** [comment]
I hadn't said anything because there are other issues like in <functional> 
```
/usr/local/bin/../include/c++/v1/__functional/function.h:521:31: error: constexpr variable '__policy' must be initialized by a constant expression
  521 |     static constexpr __policy __policy = {
      |                               ^          ~
  522 |         nullptr,
      |         ~~~~~~~~
  523 |         nullptr,
      |         ~~~~~~~~
  524 |         true,
      |         ~~~~~
  525 | #  if _LIBCPP_HAS_RTTI
      | ~~~~~~~~~~~~~~~~~~~~~~
  526 |         &typeid(void)
      |         ~~~~~~~~~~~~~
  527 | #  else
      | ~~~~~~~
  528 |         nullptr
      |         ~~~~~~~
  529 | #  endif
      | ~~~~~~~~
  530 |     };
      |     ~
```

In this case &typeid(void) is not constexpr.

**Comment by tbaederr** [comment]
> Looks like that we should add workaround to libc++ in the meanwhile.

Why? this is just for an experimental feature and the problem is just that the feature is incomplete.

**Comment by tbaederr** [comment]
`__builtin_wcslen` should be working now.
