### ISSUE TITLE
[mlir][nvvm] NVPTXSerializer does not support FATBIN target in compileToBinaryNVPTX flow

### ISSUE THREAD

**Issue by MikaOvO** [llvm/llvm-project#116747]
In `lib/Target/LLVM/NVVM/Target.cpp`, `NVPTXSerializer` compile `PTX` to binary with two different flows controlled by `MLIR_ENABLE_NVPTXCOMPILER`.

If building mlir with `-DMLIR_ENABLE_NVPTXCOMPILER=ON`, the flow does not check if the target is `gpu::CompilationTarget::Fatbin`, and compile `PTX` to `cubin` directly, which is not consistent with another flow.

Is this expected?

**Comment by joker-eph** [comment]
I don't think it is, feel free to send a patch!

**Comment by MikaOvO** [comment]
The `compileToBinary` flow converts `PTX` to `Cubin` using `ptxas`, and converts `Cubin` to `Fatbin` using `fatbinary`, all through files.

The `compileToBinaryNVPTX` flow converts `PTX` to `Cubin` using `libnvptxcompiler_static.a`, which is done in memory. So is it a bad idea to generate `Fatbin` through `fatbinary` (writing the `Cubin` result to file first)? Is it acceptable to generate `Fatbin` only through `libnvfatbin_static.a`?

Thanks!

**Comment by joker-eph** [comment]
Seems reasonable to me.

**Comment by MikaOvO** [comment]
PR here: https://github.com/llvm/llvm-project/pull/118044
