### ISSUE TITLE
Request Commit Access For fzou1

### ISSUE THREAD

**Issue by fzou1** [llvm/llvm-project#116746]
### Why Are you requesting commit access ?
I’m compiler engineer from Intel. I’m working on X86 Code generator. May I apply for commit/write access to LLVM github repo?
My github account is fzou1. Thanks.

**Comment by nikic** [comment]
@EugeneZelenko Can you please coordinate with @tstellar on the label here? You are currently editing the label away from the one that automation produces in https://github.com/llvm/llvm-project/blob/843498d4545b86fbd9c5b83d28bd39a22df52ef4/.github/new-issues-labeler.yml#L31-L32. I think the fact that this is a separate label is intentional so new requests don't go into the same place as the checks for old commit access. But possibly it should use the full `infrastructure:` prefix for consistency.

**Comment by EugeneZelenko** [comment]
@nikic: Two not very actively used labels for same purpose looks overkill for me.

**Comment by tstellar** [comment]
We should  remove the https://github.com/llvm/llvm-project/labels/infrastructure%3Acommit-access label, we agreed on the PR for this change that we would use https://github.com/llvm/llvm-project/labels/infra%3Acommit-access

**Comment by tstellar** [comment]
fyi @AaronBallman

**Comment by AaronBallman** [comment]
> We should remove the [ infrastructure:commit-access](https://github.com/llvm/llvm-project/labels/infrastructure%3Acommit-access) label, we agreed on the PR for this change that we would use https://github.com/llvm/llvm-project/labels/infra%3Acommit-access-request

SGTM!

**Comment by AaronBallman** [comment]
Also, I approve of giving commit access to @fzou1, in case that matters :-D

**Comment by tstellar** [comment]
> Also, I approve of giving commit access to @fzou1, in case that matters :-D

It's not required, but it does matter :) .  I'm just trying to raise visibility of these requests, so I'm planning to cc co-workers or other potentially interested people when these requests come in.

**Comment by tstellar** [comment]
@fzou1, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.

**Comment by fzou1** [comment]
@AaronBallman , @tstellar , Thank you. I'll go through the code review policy.

**Comment by tstellar** [comment]
@fzou1, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.
