### ISSUE TITLE
[Clang][C++] Better error message for defining a friend function in a local class defintion

### ISSUE THREAD

**Issue by dawmd** [llvm/llvm-project#116808]
Reproducer:

```cpp
void f() {
    struct A {
        friend void foo() {}
    };
}
```

compiled with `--std=gnu++23`.

---

clang-19.1.0:
```
<source>:3:21: error: no matching function found in local scope
    3 |         friend void foo() {}
      |                     ^~~
1 error generated.
```

gcc-14-2:
```
<source>: In function 'void f()':
<source>:3:21: error: cannot define friend function 'foo' in a local class definition
    3 |         friend void foo() {}
      |                     ^~~
```

**Comment by AaronBallman** [comment]
This should be relatively easy to do, I think. Rewording the diagnostic and fixing up the tests that start failing to instead expect the new wording should be all that's required.

The diagnostic wording is at: https://github.com/llvm/llvm-project/blob/def22f4e718daa74c2d0c03a32e32d4913a46278/clang/include/clang/Basic/DiagnosticSemaKinds.td#L1730

Be sure to update both `err_no_matching_local_friend` and `err_no_matching_local_friend_suggest` at the same time.

**Comment by tlemy** [comment]
I am working on this

**Comment by tlemy** [comment]
From what I understand, I assume the messages should be like gcc. So is this ok?

err_no_matching_local_friend: "cannot define friend function in a local class definition"
err_no_matching_local_friend_suggest: "cannot define friend function %0 in a local class definition; did you mean %3?"

**Comment by AaronBallman** [comment]
> From what I understand, I assume the messages should be like gcc. So is this ok?
> 
> err_no_matching_local_friend: "cannot define friend function in a local class definition"
> err_no_matching_local_friend_suggest: "cannot define friend function %0 in a local class definition; did you mean %3?"

Yes, those messages look like an improvement to me.
