### ISSUE TITLE
Double single-quotes in "illegal vector component name" diagnostic

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#116932]
See this test case:
https://github.com/llvm/llvm-project/blob/565a9ac7df3815ed038938942be4cf1471de4755/clang/test/SemaCXX/vector-bool.cpp#L88-L91

The double single-quotes are incorrect and usually coming from the diagnostic text containing the quotes directly, while passing a `NamedDecl` to the diagnostics engine adds single-quotes again.

**Comment by smallp-o-p** [comment]
I'll try and tackle this. Could I be assigned this issue? Thanks!

**Comment by the-slow-one** [comment]
@AaronBallman Could you please assign this to me?

**Comment by charan-003** [comment]
can i also work on this

**Comment by tbaederr** [comment]
Only one person can work on an issue at a time.
