### ISSUE TITLE
Request Commit Access For peterbell10

### ISSUE THREAD

**Issue by peterbell10** [llvm/llvm-project#117059]
### Why Are you requesting commit access ?
I am a core maintainer of [triton-lang/triton](https://github.com/triton-lang/triton) which uses MLIR and NVPTX codegen. I have had [4 PRs merged](https://github.com/llvm/llvm-project/pulls?q=is%3Apr+author%3Apeterbell10) already and intend to continue contributing as we uncover issues on our end.

**Comment by tstellar** [comment]
@peterbell10, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.

**Comment by tstellar** [comment]
@peterbell10, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.
