### ISSUE TITLE
Request Commit Access For juliannagele

### ISSUE THREAD

**Issue by juliannagele** [llvm/llvm-project#117027]
Hi, since spring '24 I'm a compiler engineer at Apple, currently working on middle- and back-end optimizations, and am now requesting commit access. Thanks

**Comment by fhahn** [comment]
@juliannagele landed number of improvements over the last few months

8538b913857 [LV] Vectorize Epilogues for loops with small VF but high IC (#108190)
7c8e05aa45f0 [SCEV] Collect and merge loop guards through PHI nodes with multiple incoming values (#113915)
7dbba39e583a Reapply "[TBAA] Add verifier for tbaa.struct metadata (#86709)"
f905935ff96d Fix tbaa.struct metadata for bitfields using big endian. (#87753)
dcab42a0f9aa [TBAA] Test for tbaa.struct metadata with bitfields in big endian layout (#87617)
df75183d70e0 [TBAA] Add verifier for tbaa.struct metadata (#86709)
507e59aa757b [TBAA] Tests for invalid tbaa.struct metadata (#86167)


I approve of giving commit access to @juliannagele , in case that matters :)

**Comment by tstellar** [comment]
> I approve of giving commit access to @juliannagele , in case that matters :)

It's not required, but it does matter, thanks for providing this info.

**Comment by tstellar** [comment]
@juliannagele, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.

**Comment by tstellar** [comment]
@juliannagele, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.

**Comment by juliannagele** [comment]
Thanks! -- I've read through the code review policy
