### ISSUE TITLE
Question about the mlir-linalg-ods-gen patch

### ISSUE THREAD

**Issue by joshua-arch1** [llvm/llvm-project#117114]
I noticed there was a patch (https://github.com/llvm/llvm-project/pull/75093/commits/d93f47228a1b4b7f11f96b44540ca3eb36333e8b) committed, but was reverted one day later, due to build breaking. Are there any updates for this patch by solving the breakage? @MikeHolman

**Comment by joker-eph** [comment]
Here is the PR: https://github.com/llvm/llvm-project/pull/76843
Please follow-up with discussion directly in the pull-request.
