### ISSUE TITLE
Request Commit Access For zhaoqi5

### ISSUE THREAD

**Issue by zhaoqi5** [llvm/llvm-project#117101]
### Why Are you requesting commit access ?

Hi, I am a compiler engineer working on LoongArch backend and GISelISel. I have already had more than 10 commits. 

May I request for commit access? Thanks.

**Comment by tstellar** [comment]
fyi @xen0n, @dtcxzyw

**Comment by zhaoqi5** [comment]
Thanks very much for your agreement and invitation. @tstellar

**Comment by tstellar** [comment]
@zhaoqi5, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html).

**Comment by tstellar** [comment]
@zhaoqi5, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.

**Comment by zhaoqi5** [comment]
@tstellar . Thank you. I will read it carefully and abide by it.
