### ISSUE TITLE
[libc] ensure libc-riscv32-* are using newhdrgen

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#117209]
@mikhailramalho 

Please ensure the following buildbots:
1. libc-riscv32-qemu-debian-dbg
2. libc-riscv32-qemu-yocto-fullbuild-dbg

Have the following set in their build/CMakeCache.txt:
`LIBC_USE_NEW_HEADER_GEN:BOOL=ON`

If they do, no further work is necessary and this issue can be closed.

If build/CMakeCache.txt instead has:
`LIBC_USE_NEW_HEADER_GEN:BOOL=OFF`
Then please `rm build/CMakeCache.txt`, then close this issue.

All other buildbots are moved to newhdrgen at this time.  I'd like to move them over before we delete the old hdrgen (#117208).

---

libc-riscv32-qemu-debian-dbg seems offline; can that bot be deleted?

**Comment by mikhailramalho** [comment]
Hi, I just double-checked and the option seems to be already set.

> 
> libc-riscv32-qemu-debian-dbg seems offline; can that bot be deleted?

Sure, it's the same bot actually, we just renamed it to enable fullbuild. I'll check internally how we can remove it
