### ISSUE TITLE
[flang] Incorrect preprocesor output

### ISSUE THREAD

**Issue by shivaramaarao** [llvm/llvm-project#117297]
for the following program:
#define NOCOMMENT
NOCOMMENT    CALL myfunc( 'hello ' // &
NOCOMMENT    'world' // &
NOCOMMENT    'again' )

The correct preprocessor output is
 CALL myfunc( 'hello ' // &
    'world' //
    'again' )

flang is not able to scan this code and gives following error
flang -E -ffree-form x1.F
error: Could not scan x1.F
./x1.F:2:25: error: Unmatched '('
  NOCOMMENT    CALL myfunc( 'hello ' // &
                          ^
./x1.F:4:22: error: Unmatched ')'
  NOCOMMENT    'again' )
                       ^

**Comment by klausler** [comment]
You're missing a line continuation marker at the end of the line containing `world`.

**Comment by shivaramaarao** [comment]
> You're missing a line continuation marker at the end of the line containing `world`.

Thanks. Corrected the testcase.
