### ISSUE TITLE
Documentation typo in DestinationStyleOpInterface

### ISSUE THREAD

**Issue by PerMildner** [llvm/llvm-project#117222]
https://github.com/llvm/llvm-project/blob/505e049aa078c8961f00cacefc3983398a46fb04/mlir/include/mlir/Interfaces/DestinationStyleOpInterface.td#L86

Says
```
    /// Return the number of DPS inits.
    int64_t getNumDpsInputs() {
      return $_op->getNumOperands() - $_op.getNumDpsInits();
    }
```
but it should say `... DPS inputs.`

It looks like a copy-paste bug from [getNumDpsInits()](https://github.com/llvm/llvm-project/blob/505e049aa078c8961f00cacefc3983398a46fb04/mlir/include/mlir/Interfaces/DestinationStyleOpInterface.td#L72)).

**Comment by CoTinker** [comment]
Nice catch, please fell free to open a PR.
