### ISSUE TITLE
SelectionDAGBuilder.cpp assertion fail

### ISSUE THREAD

**Issue by yuanfang-chen** [llvm/llvm-project#11727]
|  |  |
| --- | --- |
| Bugzilla Link | [11355](https://llvm.org/bz11355) |
| Version | trunk |
| OS | Linux |
| Attachments | [file causing fail](https://user-images.githubusercontent.com/455423/143744248-c8259156-0693-4d85-b066-9073f125e9dd.gz) |
| CC | @efriedma-quic,@arsenm |

## Extended Description 

Assertion `TLI.isTypeLegal(Op.getValueType()) && "Intrinsic uses a non-legal type?"' failed

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.1: https://godbolt.org/z/Modz8sP5c
