### ISSUE TITLE
Request Commit Access For @a-tarasyuk

### ISSUE THREAD

**Issue by a-tarasyuk** [llvm/llvm-project#117255]
### Why Are you requesting commit access?

I'm an [open-source enthusiast](https://github.com/a-tarasyuk) with an interest in compilers. Over the past five months as a Clang contributor, I have resolved over [forty issues](https://github.com/llvm/llvm-project/pulls/a-tarasyuk), implementing various fixes and improvements. Gaining commit access would allow me ownership to manage my pull requests more efficiently.

**Comment by cor3ntin** [comment]
I approve

**Comment by tstellar** [comment]
@a-tarasyuk, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.

**Comment by a-tarasyuk** [comment]
@tstellar @cor3ntin @AaronBallman thanks
