### ISSUE TITLE
[WebAssembly] ICE when using  `__builtin_thread_pointer`

### ISSUE THREAD

**Issue by kleisauke** [llvm/llvm-project#117433]
`test.c`:
```c
void *f0(void)
{
#if __has_builtin(__builtin_thread_pointer)
  return __builtin_thread_pointer();
#else
  return 0;
#endif
}
```
```console
$ /emsdk/upstream/bin/clang --target=wasm32 --no-standard-libraries -Wl,--no-entry -Wl,--export-all -o test.wasm test.c
fatal error: error in backend: Cannot select: intrinsic %llvm.thread.pointer
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 20.0.0git (https:/github.com/llvm/llvm-project 3a31427224d4fa49d7ef737b21f6027dc4928ecf)
Target: wasm32
Thread model: posix
InstalledDir: /emsdk/upstream/bin
Build config: +assertions
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/test-9adbd1.c
clang: note: diagnostic msg: /tmp/test-9adbd1.sh
clang: note: diagnostic msg: 

********************

```

Context: https://github.com/emscripten-core/emscripten/pull/21548.

**Comment by sbc100** [comment]
On the gcc side it looks like that is SH-specific builtin: https://gcc.gnu.org/onlinedocs/gcc-8.5.0/gcc/SH-Built-in-Functions.html.

Is this something that you think we should try to support, or are you just suggesting we need a better error here?

**Comment by kleisauke** [comment]
> Is this something that you think we should try to support, or are you just suggesting we need a better error here?

I'm unsure whether we should support this. If it's not possible, it should likely produce an error like `use of unknown builtin '__builtin_thread_pointer'` and the `__has_builtin(__builtin_thread_pointer)` check should return `false`.

I've updated the reproducer accordingly.

**Comment by sbc100** [comment]
> > Is this something that you think we should try to support, or are you just suggesting we need a better error here?
> 
> I'm unsure whether we should support this. If it's not possible, it should likely produce an error like `use of unknown builtin '__builtin_thread_pointer'` and the `__has_builtin(__builtin_thread_pointer)` check should return `false`.
> 
> I've updated the reproducer accordingly.

Actually, I think we can implement fairly easily and I can so some uses for this.  (I think we would just lower to `global.get __tls_base`).
