### ISSUE TITLE
Request Commit Access For AidanGoldfarb

### ISSUE THREAD

**Issue by AidanGoldfarb** [llvm/llvm-project#117508]
### Why Are you requesting commit access ?
I would like to begin contributing to LLVM. I have already created a [pull request](https://github.com/llvm/llvm-project/pull/117507) to address an issue. Some context, I have recently graduated from my masters program in CS and would am very interested in contributing to LLVM over the next several months. Thanks!

**Comment by tstellar** [comment]
### Activity Summary:
* [1 Pull Requests](https://github.com/llvm/llvm-project/pulls/AidanGoldfarb) (0 merged)
* Top 3 Committers: 
* Top 3 Reviewers: @justinfargnoli (1), @Sirraide (1)

**Comment by tstellar** [comment]
@AidanGoldfarb, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.
