### ISSUE TITLE
Over-eager SIMD causing up to 6x regression on basic math functions [x64]

### ISSUE THREAD

**Issue by BlobTheKat** [llvm/llvm-project#117557]
# Part 1

```cpp
#include <math.h>
#include <bit>
using namespace std;

volatile float accumulate = 1.;
int main(){
	for(int i=0;i<1000000000;i++){
		float r = accumulate;
		r = abs(r);
		// or indeed
		//r = bit_cast<float>(bit_cast<unsigned int>(r) & 0x7ffffff);
		accumulate = r;
	}
}
```
The loop is partially unrolled but the load/abs()/store is turned into
```asm
.LCPI0_0:
	.long   0x7fffffff
	.long   0x7fffffff
	.long   0x7fffffff
	.long   0x7fffffff
.main
	...
	movss   xmm1, dword ptr [rip + x]
	andps   xmm1, xmm0
	movss   dword ptr [rip + x], xmm1
	...
```
The compiler attempts to make use of SIMD but it ends up being much slower. On my machine the loop completes in 2.72s on average

In contrast, replacing `0x7ffffff` with `0x7fffffe` results in much nicer assembly:
```asm
; LCPI0_0 is gone
.main
	...
	and     dword ptr [rip + x], 2147483646
	...
```
On my machine the loop completes in 450ms on average

# Part 2

Let's say we perform the volatile load/store outside the loop

```cpp
#include <math.h>
#include <bit>
using namespace std;

volatile float accumulate = 1.;
int main(){
	float r = accumulate;
	for(int i=0;i<1000000000;i++){
		r = bit_cast<float>(bit_cast<unsigned int>(r) & 0x7ffffff);
	}
	accumulate = r;
}
```
The loop is unrolled 8x and compiled into
```asm
.LCPI0_0:
	.long   0x7fffffff
	.long   0x7fffffff
	.long   0x7fffffff
	.long   0x7fffffff
.main
        ; xmm1 = xmm0 = accumulate
	...
	andps   xmm0, xmm1
	...
        ; accumulate = xmm0
```
Completion time: 270ms

Now with the modified version, as earlier
```cpp
#include <math.h>
#include <bit>
using namespace std;

volatile float accumulate = 1.;
int main(){
	float r = accumulate;
	for(int i=0;i<1000000000;i++){
		r = bit_cast<float>(bit_cast<unsigned int>(r) & 0x7fffffe);
	}
	accumulate = r;
}
```
The above is completely optimized away into
```asm
main:
        and     dword ptr [rip + x], 2147483646
        xor     eax, eax
        ret
x:
        .long   0x3f800000
```
In the first case the compiler attempts to use SIMD instructions where not necessary, creating an additional data section in the process
In the second case the compiler does that plus fails to optimize a loop whose body is dependent on a volatile, despite the volatile not being accessed inside the loop.

**In both cases the compiler determines that it SIMD is faster if and only if the second operand to `&` is `0x7ffffff`, which is completely wrong as only one value is being modified, no SIMD is needed**

**Comment by BlobTheKat** [comment]
For comparison, gcc correctly avoids SIMD and the body of the loop looks like `and eax, 2147483647`

**Comment by fhahn** [comment]
Looks like the loop gets unrolled on X86 and then the backend forms SIMD instructions, not the middle-end: https://clang.godbolt.org/z/q3KWehGzr

**Comment by jeremy-rifkin** [comment]
Nothing SIMD is happening here as far as I can tell, middle or back-end. The middle-end reduces it down to a simple loop body of load-abs-store and then unrolls that loop. Nothing significant happens in the back-end. https://godbolt.org/z/vbq1nzTb3

**Comment by topperc** [comment]
The backend is using an SSE instruction because the data has `float` type. We're not determining SIMD is faster. Had there been other floating poing arithmetic than just `abs`, those operations would need to use SSE or x87 instructions. In that case moving to scalar integer and back would be more costly.

I guess gcc realized that the operation is just load/store/abs and moves converts it to an integer operation instead fp operation.

**Comment by RKSimon** [comment]
Other ops like FNEG/FCOPYSIGN are also susceptible - a workaround is pretty easy, but I'm not sure how far we need to take this (select to CMOV etc.).
