### ISSUE TITLE
Request Commit Access For willlovett-arm

### ISSUE THREAD

**Issue by willlovett-arm** [llvm/llvm-project#117580]
### Why Are you requesting commit access ?

I'm the Arm technology manager responsible for compiler development, which includes all our upstream LLVM contributions.  I'm unlikely to commit code directly, but would like membership of the GitHub organisation so that I can interact with project boards such as [this one](https://github.com/orgs/llvm/projects/34), which we're using to state our priorities with Bolt enablement.

**Comment by tstellar** [comment]
@willlovett-arm Would the 'Triage' role be enough for you: https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization

**Comment by willlovett-arm** [comment]
@tstellar - yes that sounds ideal.  Thanks.

**Comment by tstellar** [comment]
@willlovett-arm has been added to the Triagers team.
