### ISSUE TITLE
Request Commit Access For tianleliu

### ISSUE THREAD

**Issue by tianleliu** [llvm/llvm-project#117512]
Why are you requesting commit access ?
I’m compiler engineer from Intel. I’m working on X86 Code generator. May I apply for commit/write access to LLVM github repo?
Though my commits are not very much, I have been working on llvm or llvm based compiler/tools for more than 6 years. And I'd like to be more involved with LLVM maintenance. Gaining commit access would allow me ownership to manage my pull requests more efficiently. Thanks!
As a author:
https://github.com/llvm/llvm-project/commits?author=tianleliu
https://reviews.llvm.org/D60552
https://reviews.llvm.org/D60550
As a reviewer:
https://reviews.llvm.org/D78190
https://reviews.llvm.org/D65933
https://reviews.llvm.org/D54250

**Comment by tstellar** [comment]
### Activity Summary:
* [0 Pull Requests](https://github.com/llvm/llvm-project/pulls/tianleliu) (0 merged)
* Top 3 Committers: 
* Top 3 Reviewers:

**Comment by tstellar** [comment]
cc @AaronBallman

**Comment by AaronBallman** [comment]
I'm okay with granting commit access in this case

**Comment by tstellar** [comment]
@tianleliu, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.
