### ISSUE TITLE
[clang-tidy] bugprone-return-const-ref-from-parameter should ignore [[clang::lifetimebound]] parameters

### ISSUE THREAD

**Issue by RedBeard0531** [llvm/llvm-project#117696]
[godbolt](https://godbolt.org/z/fz7sbPfqe)

```cpp
template <typename T>
const T& max(const T& a [[clang::lifetimebound]], const T& b [[clang::lifetimebound]]) {
    return a > b ? a : b; // trips bugprone-return-const-ref-from-parameter
}

int add_one(const int& x) { return x + 1; }

void test() {
    int fine = max(1, 2);
    int also_fine = add_one(max(1, 2));
    const int& bad = max(1,2); // trips -Wdangling
}
```

`[[clang::lifetimebound]]` indicates that it is intentional to return a reference from an argument, so clang tidy warning about it is just telling the author what they already know. Also, the attribute enables clang to give more precise warnings when the function is _used_ in a bad way, rather than just preemptively warning in the definition even when used correctly.

Ideally, this should even suggest a fixit to add the attribute so that we can get the precise warnings while still taking advantage of the performance benefits of not copying for non-trivial arguments.

**Comment by HerrCai0907** [comment]
That is pretty cool. Is it pending feature of C++ or clang customized extensions?
