### ISSUE TITLE
SCEV fails to take advantage of nsw

### ISSUE THREAD

**Issue by nlewycky** [llvm/llvm-project#11781]
|  |  |
| --- | --- |
| Bugzilla Link | [11409](https://llvm.org/bz11409) |
| Version | trunk |
| OS | Linux |
| CC | @atrick |

## Extended Description 
opt -O2 does a pretty decent job of handling this loop:

  int f(int i) { int j, k = 0; for (j = i; j < i + 10; ++j) ++k; return k; } 

but it's not taking advantage of the no-signed-wrap property. GCC optimizes it straight down to "return 10".

**Comment by JOE1994** [comment]
LLVM trunk now also optimizes the program straight down to `return 10` on x86_64:

* Godbolt link : https://godbolt.org/z/ccsj55q88
