### ISSUE TITLE
[Clang] --dump-config option returns default configuration

### ISSUE THREAD

**Issue by NahuFigueroa97** [llvm/llvm-project#117893]
I'm using the -style=file option to find the .clang-format in the same directory or higher, while I use the --dump-config option to check that it takes the indicated options, but it always returns the default options. It's strange because if I modify my own .clang-format incorrectly, it tells me the error so I assume it's finding the file correctly. This happens in both versions 14 and 18.

```
clang-format-14 -i example/src/fieldAlertHelper.hpp --style=file --dump-config
```

**Comment by EugeneZelenko** [comment]
Could you please try 19 or `main` branch?

**Comment by NahuFigueroa97** [comment]
I get the same results. If I put a wrong configuration, it warns me. But with --dump-config it shows me the default file.

**Comment by owenca** [comment]
> I'm using the -style=file option to find the .clang-format in the same directory or higher, while I use the --dump-config option to check that it takes the indicated options, but it always returns the default options. It's strange because if I modify my own .clang-format incorrectly, it tells me the error so I assume it's finding the file correctly. This happens in both versions 14 and 18.

What's your .clang-format file? What options you changed were not reflected by `-dump-config`?

**Comment by NahuFigueroa97** [comment]
This is my .clang-format

```
...
AccessModifierOffset: '-4'
AlignAfterOpenBracket: Align
AlignConsecutiveAssignments: 'false'
AlignConsecutiveDeclarations: 'false'
AlignConsecutiveMacros: 'true'
AlignEscapedNewlines: Right
AlignOperands: 'true'
AlignTrailingComments: 'true'
AllowAllArgumentsOnNextLine: 'true'
AllowAllConstructorInitializersOnNextLine: 'true'
AllowAllParametersOfDeclarationOnNextLine: 'true'
AllowShortBlocksOnASingleLine: 'false'
AllowShortCaseLabelsOnASingleLine: 'true'
AllowShortFunctionsOnASingleLine: Inline
AllowShortIfStatementsOnASingleLine: Never
AllowShortLambdasOnASingleLine: Inline
AllowShortLoopsOnASingleLine: 'true'
AlwaysBreakBeforeMultilineStrings: 'false'
AlwaysBreakTemplateDeclarations: 'Yes'
BinPackArguments: 'false'
BinPackParameters: 'false'
BreakBeforeBinaryOperators: NonAssignment
BreakBeforeBraces: Allman
BreakConstructorInitializers: BeforeComma
BreakInheritanceList: BeforeComma
ColumnLimit: 120
Cpp11BracedListStyle: 'true'
FixNamespaceComments: 'true'
IncludeBlocks: Preserve
IndentCaseLabels: 'true'
IndentWidth: '4'
PointerAlignment: Left
SortIncludes: 'true'
SpaceAfterCStyleCast: 'false'
SpaceAfterLogicalNot: 'false'
SpaceAfterTemplateKeyword: 'false'
SpaceBeforeAssignmentOperators: 'true'
SpaceBeforeCpp11BracedList: 'true'
SpaceBeforeCtorInitializerColon: 'true'
SpaceBeforeInheritanceColon: 'true'
SpaceBeforeParens: ControlStatements
SpaceInEmptyParentheses: 'false'
SpacesInAngles: 'false'
Standard: Auto
TabWidth: '4'
UseTab: Never
---
Language: Proto
DisableFormat: false
```

**Comment by NahuFigueroa97** [comment]
I see that it modifies the options I have in my file and leaves the others intact. This is a problem because when I run clang-14 and apply the changes, if I then run clang-18 it reapplies changes to what clang-14 had corrected.
In this line for example:

```
template<typename T>
nlohmann::json fillEmptyOrNegative(T&& field)
{
    if constexpr (std::is_same_v<std::remove_cv_t<std::remove_reference_t<T>>, std::string_view>
                         || std::is_same_v<T, std::string>)

```

clang-format-14
```
template<typename T>
nlohmann::json fillEmptyOrNegative(T&& field)
{
    if constexpr (std::is_same_v<std::remove_cv_t<std::remove_reference_t<T>>,
                                 std::string_view> || std::is_same_v<T, std::string>)
```

clang-format-18
```
template<typename T>
nlohmann::json fillEmptyOrNegative(T&& field)
{
    if constexpr (std::is_same_v<std::remove_cv_t<std::remove_reference_t<T>>, std::string_view>
                  || std::is_same_v<T, std::string>)

```

**Comment by owenca** [comment]
> This is my .clang-format
> 
> ```
> ...
> AccessModifierOffset: '-4'
> AlignAfterOpenBracket: Align
> AlignConsecutiveAssignments: 'false'
> AlignConsecutiveDeclarations: 'false'
> AlignConsecutiveMacros: 'true'
> AlignEscapedNewlines: Right
> AlignOperands: 'true'
> AlignTrailingComments: 'true'
> AllowAllArgumentsOnNextLine: 'true'
> AllowAllConstructorInitializersOnNextLine: 'true'
> AllowAllParametersOfDeclarationOnNextLine: 'true'
> AllowShortBlocksOnASingleLine: 'false'
> AllowShortCaseLabelsOnASingleLine: 'true'
> AllowShortFunctionsOnASingleLine: Inline
> AllowShortIfStatementsOnASingleLine: Never
> AllowShortLambdasOnASingleLine: Inline
> AllowShortLoopsOnASingleLine: 'true'
> AlwaysBreakBeforeMultilineStrings: 'false'
> AlwaysBreakTemplateDeclarations: 'Yes'
> BinPackArguments: 'false'
> BinPackParameters: 'false'
> BreakBeforeBinaryOperators: NonAssignment
> BreakBeforeBraces: Allman
> BreakConstructorInitializers: BeforeComma
> BreakInheritanceList: BeforeComma
> ColumnLimit: 120
> Cpp11BracedListStyle: 'true'
> FixNamespaceComments: 'true'
> IncludeBlocks: Preserve
> IndentCaseLabels: 'true'
> IndentWidth: '4'
> PointerAlignment: Left
> SortIncludes: 'true'
> SpaceAfterCStyleCast: 'false'
> SpaceAfterLogicalNot: 'false'
> SpaceAfterTemplateKeyword: 'false'
> SpaceBeforeAssignmentOperators: 'true'
> SpaceBeforeCpp11BracedList: 'true'
> SpaceBeforeCtorInitializerColon: 'true'
> SpaceBeforeInheritanceColon: 'true'
> SpaceBeforeParens: ControlStatements
> SpaceInEmptyParentheses: 'false'
> SpacesInAngles: 'false'
> Standard: Auto
> TabWidth: '4'
> UseTab: Never
> ---
> Language: Proto
> DisableFormat: false
> ```

So which of the above options has a value different (or not equivalent to) the one printed by `-dump-config`? Please try version 19 or the main branch.
