### ISSUE TITLE
[Clang] Implement P2865R6 (Remove Deprecated Array Comparisons from C++26)

### ISSUE THREAD

**Issue by cor3ntin** [llvm/llvm-project#117859]
Paper link: https://isocpp.org/files/papers/P2865R6.pdf

We implement the depreciation warning, we need to turn it into an error https://godbolt.org/z/sqod3G69P.

TODO:

- [ ] Adding an error diagnostics in C++26 mode (while keeping the existing depreciation warning in older language modes)
- [ ] Adding tests
- [ ] Modifying cxx_status.html
- [ ] Adding changelog entry

**Comment by AmrDeveloper** [comment]
I can work on it, i am already working on `-warray-comparion` in this [issue](https://github.com/llvm/llvm-project/issues/114770#issuecomment-2501595214) and i can support C++26 error case after it

**Comment by AaronBallman** [comment]
> Adding an error diagnostics in C++26 mode (while keeping the existing depreciation warning in older language modes)

We should discuss this more. I think this should be a warning which defaults to an error rather than a hard error unless there's a really good reason not to. We know we still have people with code using these comparisons -- for example: https://sourcegraph.com/github.com/mongodb/mongo/-/blob/src/third_party/icu4c-57.1/source/BUILD.bazel?L28-30

We can then strengthen to an error in a release or two once folks have gotten the stronger message. WDYT?

**Comment by frederick-vs-ja** [comment]
Hmm... Given P2865R6 (implicitly) requires changes in SFINAE, would it be burdensome for Clang to accept such comparison in some cases while considering it as substitution failure?

**Comment by AaronBallman** [comment]
> Hmm... Given P2865R6 (implicitly) requires changes in SFINAE, would it be burdensome for Clang to accept such comparison in some cases while considering it as substitution failure?

Possibly, but my intuition isn't very strong here. My biggest concern would be that we'd need ABI tags so folks can opt in to the old behavior or the new behavior in order to not get silent (ABI impacting) behavioral changes.

**Comment by AmrDeveloper** [comment]
I created a PR to report with a new warning for C++26 and it's an error by default.

Also there is this point for overlapping between warns

> This seems to overlap w/ warn_stringcompare we probably want to do some special handling here since string literals are a special case of arrays and they have their own comparison functions.
We can do this as part of the C++26 feature implementation.

@shafik https://github.com/llvm/llvm-project/pull/118031#discussion_r1866335717

Should we stop this warning in C++26 mode and only report the new error?
