### ISSUE TITLE
Division miscompile regression on Arm

### ISSUE THREAD

**Issue by ZequanWu** [llvm/llvm-project#117819]
https://github.com/llvm/llvm-project/commit/5a5b78a84e7214796410265139ecf0266b1fd216 introduced a miscompile and causes highway [division test](https://github.com/google/highway/blob/master/hwy/tests/div_test.cc#L114) to fail. @davemgreen Are you okay to revert that commit while we working on a smaller reproducer for it?

**Comment by ZequanWu** [comment]
Disabling global isel when compile the div_test.cc source file makes the test pass.

**Comment by fhahn** [comment]
cc @aemerson

**Comment by davemgreen** [comment]
It does look obviously wrong. Not sure how I messed that up, it looks like a silly one. Is it fixed by 712ef7d0baf9b7b6c2a3f01f0c02305a0e0160e9? If not we can revert and figure out what is wrong.

**Comment by ZequanWu** [comment]
Yes, it fixed that.
