### ISSUE TITLE
Request Commit Access For fschlimb (Frank Schlimbach)

### ISSUE THREAD

**Issue by fschlimb** [llvm/llvm-project#117983]
Currently I am the most active contributor to mesh and mpi dialects (MLIR).

@rengolin

**Comment by rengolin** [comment]
@AaronBallman @nikic What's the process for getting these approved nowadays?

**Comment by tstellar** [comment]
### Activity Summary:
* [8 Pull Requests](https://github.com/llvm/llvm-project/pulls/fschlimb) (8 merged)
* Top 3 Committers: @rengolin (6), @jplehr (1), @mfrancio (1)
* Top 3 Reviewers: @yaochengji (3), @sogartar (3), @mfrancio (1)
