### ISSUE TITLE
[NSan] How to enable Numerical Sanitizer in Clang++ and generate instrumented code?

### ISSUE THREAD

**Issue by bartlettroscoe** [llvm/llvm-project#117912]
CC: @alexander-shaposhnikov, @firewave, @cjappl

I know this is closely related to:

* #98869

but how to you enable support for the Numerical Sanitizer (NSan) described in the paper:

* “NSan: A Floating-Point Numerical Sanitizer” https://arxiv.org/pdf/2102.12782 (paper from 2021)

?

Is this as simple as setting a compiler option or do you need to build a version of LLVM Clang++ that even has support for NSan?

I can likely dig through source code and other places to figure this out, but I thought I might just ask.

**Comment by firewave** [comment]
`-fsanitize=numerical`

**Comment by bartlettroscoe** [comment]
> -fsanitize=numerical

And the default LLVM `clang++` compiler is built by default to support this option?  (Or it will in LLVM 18.0 relesae?)

**Comment by firewave** [comment]
It is supported by Clang 19+ and should be built-in by default.

**Comment by bartlettroscoe** [comment]
Thanks for answering questions!  I will work on building LLVM Clang++ 19.1.z and testing this out. 

Closing this issue.

**Comment by bartlettroscoe** [comment]
FYI: I was able to build and install 'main' version of LLVM and verify that just setting the compiler option `-fsanitize=numerical` enabled NSan and produced some errors.
