### ISSUE TITLE
clangd .clang-format custom location

### ISSUE THREAD

**Issue by Barricade** [llvm/llvm-project#118]
Hello, how could I set custom location for .clang-format in clangd? I can't move it into project roo directory.

**Comment by MarcusJohnson91** [comment]
The default location is `$HOME/.clang-format`

`clang-format -style=file` finds my .clang-format file just fine.

**Comment by HighCommander4** [comment]
I'm going to dupe this over to https://github.com/clangd/clangd/issues/805 (even though that was more recently filed), as there is more discussion there.
