### ISSUE TITLE
[lldb][tests] Sockets leaks in API tests with a remote target

### ISSUE THREAD

**Issue by slydiman** [llvm/llvm-project#118032]
We got unexpected errors on a random single test on [lldb-remote-linux-ubuntu](https://lab.llvm.org/buildbot/#/builders/195) and [lldb-remote-linux-win](https://lab.llvm.org/staging/#/builders/197) 1-4 times per day.

Error 1: Unresolved some test with the exception `failed to create a socket to the launched debug monitor after 20 tries`.
Usually we got this error on the Linux host (lldb-remote-linux-ubuntu), e.g. [TestGdbRemoteMemoryAllocation.py](https://lab.llvm.org/buildbot/#/builders/195/builds/1660), [TestNonStop.py](https://lab.llvm.org/buildbot/#/builders/195/builds/1625), [TestGdbRemoteSingleStep.py](https://lab.llvm.org/buildbot/#/builders/195/builds/1614). But we saw the same error (very rarely) on Windows host (lldb-remote-linux-win) too: [TestGdbRemoteHostInfo.py](https://lab.llvm.org/staging/#/builders/197/builds/732).

Error 2: 600 seconds timeout.
Usually (99%) we got this error on the Windows host (lldb-remote-linux-win) with the test [TestModuleLoadedNotifys.py](https://lab.llvm.org/staging/#/builders/197/builds/890) and less often with any other test, e.g. [TestLldbGdbServer.py](https://lab.llvm.org/staging/#/builders/197/builds/744). We also saw the same error (very rarely) on Linux host (lldb-remote-linux-ubuntu) too: [TestCancelAttach.py](https://lab.llvm.org/buildbot/#/builders/195/builds/1402).

I believe that the cause of both issues is the same - leaking sockets.

Error 1 is raised in connect_to_debug_monitor() in gdbremote_testcase.py.
It uses a random port `12000 + random.randint(0, 3999)` to launch a new instance of `lldb-server gdbserver *:port` on the target.
Then it tries to connect to the lldb-server up to 10 times with 0.5 sec delay and terminates the lldb-server if connection failed.
Then it tries another port up to 20 times with a random delay 1-5 seconds `to avoid collisions`.

We checked netstat during the tests in the beginning and got 164 connections in the state TIME_WAIT between the host and the target:
24 connections to `target IP`:1234 (platform)
100 connections to `target IP`:43107 (gdbserver)
40 connections to `target IP` with a random port
and 2 connections in the state ESTABLISHED.

We checked netstat during the tests after 15 minutes and got 641 connections in the state TIME_WAIT between the host and the target
310 connections to `target IP`:1234 (platform)
331 connections to `target IP`:43107 (gdbserver)
and 9 connections in the state ESTABLISHED.

Usually the state TIME_WAIT means timeout 4 minutes before releasing resources.

Both buildbots run tests in 8 threads.

Both buildbots use python 3.12. Note the results with python 3.13 are worse probably due to an incremental GC. The average build/test time with python 3.13 is longer.

Probably increasing `MAX_ATTEMPTS = 20` in connect_to_debug_monitor() may be enough to fix the error 1.
But I have no idea how to fix and even debug the error 2. It is very hard to reproduce.

**Comment by slydiman** [comment]
@labath, do you have any thoughts/suggestions?

**Comment by JDevlieghere** [comment]
I have some thought after reading this, but please take them with a grain of salt as I didn't actually look into this problem, and my suggestions might try to solve problems that are somewhat orthogonal... 

- To avoid the variance introduced by using a random port, could we key the port off of something unique, like the pid of the (test) process? I suspect we might need more than one port per process and therefore that doesn't work? Maybe there are other tricks to get somewhat of a unique namespace, like reserving different blocks in the 4000 ports and picking one based on the test name or something. The problem I'm trying to solve by this is not so much avoiding the collisions, but making it easier to reproduce these issues once they start happening.  
- Instead of retrying after a random amount of time, should we use something like exponential backoff? I'd rather have the test take a lot of time occasionally than fail randomly.

**Comment by labath** [comment]
> * To avoid the variance introduced by using a random port, could we key the port off of something unique, like the pid of the (test) process? I suspect we might need more than one port per process and therefore that doesn't work? Maybe there are other tricks to get somewhat of a unique namespace, like reserving different blocks in the 4000 ports and picking one based on the test name or something. The problem I'm trying to solve by this is not so much avoiding the collisions, but making it easier to reproduce these issues once they start happening.

The problem with that is we can't really assume these ports are only going to be used by us. Anything on the system could decide to open one of those ports. If the port number function of the test, then this could cause a specific test to start failing. The failure would be sort of deterministic, but it would depend on the environment outside of the test that you may not be able to do anything about.

I suppose you could handle this by generating a deterministic *sequence* of port numbers for each test (which would be tried in turn). That would get around this problem and give you some amount of reproducibility, but I don't think it would be much because the behavior would still depend on the relative speeds of different tests (as well as the external environment).

I think the only solid solution is to avoid guessing a port altogether. We don't do that for local runs -- we just have lldb-server connect to the test (reverse-connect mode). That might not work in all remote setups (e.g. if there are firewalls/nats involved), but it could certainly work sometimes. There are also ways to have lldb-server pick a port and communicate that back to the test. Someone just needs to design and implement it.

**Comment by slydiman** [comment]
17 hours after #118222 is ok on [lldb-remote-linux-ubuntu](https://lab.llvm.org/buildbot/#/builders/195).

But I see something new on [lldb-remote-linux-win](https://lab.llvm.org/staging/#/builders/197). Something is incrementally leaking under Windows. Note all crashes are unrelated to llvm changes and the next build is green.

[TIMEOUT: lldb-api::TestModuleLoadedNotifys.py](https://lab.llvm.org/staging/#/builders/197/builds/1010) - as usual.

[UNRESOLVED: lldb-api::TestIOHandlerResizeNoEditline.py](https://lab.llvm.org/staging/#/builders/197/builds/1012) - exit code 0xC0000409 means an assert inside the python code.

[UNRESOLVED: lldb-api::TestModuleLoadedNotifys.py](https://lab.llvm.org/staging/#/builders/197/builds/1015) - and a crash (access violation in windows.storage.dll, SHELL32.dll) inside SBDebugger::CreateTarget()
```
Windows fatal exception: access violation
Thread 0x0000119c (most recent call first):
  File "C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\__init__.py", line 4832 in CreateTarget
  File "C:\buildbot\as-builder-10\lldb-x-aarch64\llvm-project\lldb\test\API\functionalities\target-new-solib-notifications\TestModuleLoadedNotifys.py", line 65 in test_launch_notifications
  File "C:\Python312\Lib\unittest\case.py", line 589 in _callTestMethod
  File "C:\Python312\Lib\unittest\case.py", line 634 in run
  File "C:\Python312\Lib\unittest\case.py", line 690 in __call__
  File "C:\Python312\Lib\unittest\suite.py", line 122 in run
  File "C:\Python312\Lib\unittest\suite.py", line 84 in __call__
  File "C:\Python312\Lib\unittest\suite.py", line 122 in run
  File "C:\Python312\Lib\unittest\suite.py", line 84 in __call__
  File "C:\Python312\Lib\unittest\runner.py", line 240 in run
  File "C:\buildbot\as-builder-10\lldb-x-aarch64\llvm-project\lldb\packages\Python\lldbsuite\test\dotest.py", line 1106 in run_suite
  File "C:\buildbot\as-builder-10\lldb-x-aarch64\llvm-project\lldb\test\API\dotest.py", line 8 in <module>
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Exception Code: 0xC0000005
 #0 0x00007ff94c151ba9 (C:\Windows\System32\SHELL32.dll+0x61ba9)
 #1 0x00007ff94c1473cb (C:\Windows\System32\SHELL32.dll+0x573cb)
 #2 0x00007ff9402fcf19 (C:\Windows\SYSTEM32\windows.storage.dll+0x1ccf19)
 #3 0x00007ff9402857e1 (C:\Windows\SYSTEM32\windows.storage.dll+0x1557e1)
 #4 0x00007ff940284198 (C:\Windows\SYSTEM32\windows.storage.dll+0x154198)
 #5 0x00007ff940288bcf (C:\Windows\SYSTEM32\windows.storage.dll+0x158bcf)
 #6 0x00007ff940287204 (C:\Windows\SYSTEM32\windows.storage.dll+0x157204)
 #7 0x00007ff940286cdf (C:\Windows\SYSTEM32\windows.storage.dll+0x156cdf)
 #8 0x00007ff94028b692 (C:\Windows\SYSTEM32\windows.storage.dll+0x15b692)
 #9 0x00007ff9144254de PyInit__lldb (C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\_lldb.cp312-win_amd64.pyd+0x9a54de)
#10 0x00007ff914032d5e PyInit__lldb (C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\_lldb.cp312-win_amd64.pyd+0x5b2d5e)
#11 0x00007ff91403260a PyInit__lldb (C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\_lldb.cp312-win_amd64.pyd+0x5b260a)
#12 0x00007ff9140349f8 PyInit__lldb (C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\_lldb.cp312-win_amd64.pyd+0x5b49f8)
#13 0x00007ff914033d92 PyInit__lldb (C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\_lldb.cp312-win_amd64.pyd+0x5b3d92)
#14 0x00007ff913fcfbca PyInit__lldb (C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\_lldb.cp312-win_amd64.pyd+0x54fbca)
#15 0x00007ff913fd1a3d PyInit__lldb (C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\_lldb.cp312-win_amd64.pyd+0x551a3d)
#16 0x00007ff913fd1f09 PyInit__lldb (C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\_lldb.cp312-win_amd64.pyd+0x551f09)
#17 0x00007ff913fa6a83 PyInit__lldb (C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\_lldb.cp312-win_amd64.pyd+0x526a83)
#18 0x00007ff913f98616 PyInit__lldb (C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\_lldb.cp312-win_amd64.pyd+0x518616)
#19 0x00007ff913fb56d6 PyInit__lldb (C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\_lldb.cp312-win_amd64.pyd+0x5356d6)
#20 0x00007ff913f7def9 PyInit__lldb (C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\_lldb.cp312-win_amd64.pyd+0x4fdef9)
#21 0x00007ff913f7e0e3 PyInit__lldb (C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\_lldb.cp312-win_amd64.pyd+0x4fe0e3)
#22 0x00007ff91446bb5a PyInit__lldb (C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\_lldb.cp312-win_amd64.pyd+0x9ebb5a)
#23 0x00007ff91446ac7f PyInit__lldb (C:\buildbot\as-builder-10\lldb-x-aarch64\build\Lib\site-packages\lldb\_lldb.cp312-win_amd64.pyd+0x9eac7f)
#24 0x00007ff94b2d6b4c (C:\Windows\System32\ucrtbase.dll+0x26b4c)
#25 0x00007ff94d714cb0 (C:\Windows\System32\KERNEL32.DLL+0x14cb0)
#26 0x00007ff94dd7ecdb (C:\Windows\SYSTEM32\ntdll.dll+0x7ecdb)
```

**Comment by slydiman** [comment]
I have updated the call stack above with symbols from windows.storage.dll and shell32.dll.
The original `_lldb.cp312-win_amd64.pyd` file is lost, so it is impossible to reconstruct the full call stack. 
But it seems the hang and timeout on Windows host is not related to sockets.

It seems SHFileOperationWithAdditionalFlags() is an alias for SHFileOperationW(). SHFileOperationW() is called from:
* llvm/utils/lit/lit/TestRunner.py, executeBuiltinRm()
* llvm::sys::fs::remove_directories()

llvm::sys::fs::remove_directories() is called from:
* source/Target/ModuleCache.cpp, DeleteExistingModule()
* source/Host/common/HostInfoBase.cpp, ~HostInfoBaseFields()

Note the crash occured in SHELL32_CallFileCopyHooks(). It is very similar to [this article](https://devblogs.microsoft.com/oldnewthing/20120330-00/?p=7963).
I will try to add the FOFX_NO­COPY­HOOKS flag to llvm::sys::fs::remove_directories().

**Comment by slydiman** [comment]
Note the buildbot [lldb-aarch64-windows](https://lab.llvm.org/staging/#/builders/194) is very unstable. 
I see a lot random failures, including timeouts and access violations. 
For example https://lab.llvm.org/staging/#/builders/194/builds/5291
Unfortunately it does not contain any stacktrace at all. But it seems to be the same issue.

**Comment by slydiman** [comment]
> ```wil::details::FeatureImpl<__WilFeatureTraits_Feature_CloudFileCopyHook>::ReportUsage(bool,wil::ReportingKind,unsigned __int64)```

Probably this issue may be fixed by disabling OneDrive and `Submit a file for malware analysis` option in the builtin antivirus. 
We will check it.

**Comment by slydiman** [comment]
The patch #118222 did not fix the issue on Ubuntu (4 hours between builds):
https://lab.llvm.org/buildbot/#/builders/195/builds/2032
https://lab.llvm.org/buildbot/#/builders/195/builds/2043
```
Exception: failed to create a socket to the launched debug monitor after 10 tries
```

**Comment by slydiman** [comment]
After disabling OneDrive and all Azure Arc and Windows Defender Antivirus related options we have the following statistics on Windows host since [this build](https://lab.llvm.org/staging/#/builders/197/builds/1202) (3 days):
- 7 timeouts on the test `lldb-api::TestModuleLoadedNotifys.py`, [link](https://lab.llvm.org/staging/#/builders/197/builds/1292)
- 2 crashes inside python (exit code 0xC0000409, no stack trace) on the test `lldb-api::TestIOHandlerResizeNoEditline.py` [link1](https://lab.llvm.org/staging/#/builders/197/builds/1224), [link2](https://lab.llvm.org/staging/#/builders/197/builds/1271)
- 2 times `Exception: failed to create a socket to the launched debug monitor after 10 tries`, [link1](https://lab.llvm.org/staging/#/builders/197/builds/1238), [link2](https://lab.llvm.org/staging/#/builders/197/builds/1257)

I hope #118677 or #119146 will improve situation. We did not try to change the socket WAIT_TIME timeout in the registry yet.

**Comment by slydiman** [comment]
It seems #118677 fixed the crash and timeout in the test `lldb-api::TestModuleLoadedNotifys.py`.
But something is still leaks in LLDB at least on Windows host.

UNRESOLVED: lldb-api::TestIOHandlerResizeNoEditline.py - exit code 0xC0000409 means an assert/exception inside the native python code.
https://lab.llvm.org/staging/#/builders/197/builds/1541
https://lab.llvm.org/staging/#/builders/197/builds/1512

**Comment by slydiman** [comment]
I already fixed the test `lldb-api::TestModuleLoadedNotifys.py` for Windows #92286.
But it seems this test crashes sometimes on the last line `dbg.GetInputFile().Close()` with the following exception inside CRT:
```
Exception Code: 0x80000003
 #0 0x00007ffb4842e03d (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0x14e03d)
 #1 0x00007ffb4842e4f5 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0x14e4f5)
 #2 0x00007ffb28a29f09 lldb_private::NativeFile::GetStream(void) D:\llvm-project\lldb\source\Host\common\File.cpp:292:0
 #3 0x00007ffb289af668 lldb_private::IOHandler::GetInputFILE(void) D:\llvm-project\lldb\source\Core\IOHandler.cpp:92:0
 #4 0x00007ffb289b0988 lldb_private::IOHandlerEditline::GetLine(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> &, bool &) D:\llvm-project\lldb\source\Core\IOHandler.cpp:385:0
 #5 0x00007ffb289b034e lldb_private::IOHandlerEditline::Run(void) D:\llvm-project\lldb\source\Core\IOHandler.cpp:596:0
 #6 0x00007ffb28887c68 lldb_private::Debugger::RunIOHandlers(void) D:\llvm-project\lldb\source\Core\Debugger.cpp:1118:0
 #7 0x00007ffb2888a644 lldb_private::Debugger::IOHandlerThread(void) D:\llvm-project\lldb\source\Core\Debugger.cpp:2052:0
 #8 0x00007ffb2888ebb7 `lldb_private::Debugger::StartIOHandlerThread'::`5'::<lambda_1>::operator() D:\llvm-project\lldb\source\Core\Debugger.cpp:2163:0
 #9 0x00007ffb2889b7c4 std::invoke<`lldb_private::Debugger::StartIOHandlerThread'::`5'::<lambda_1> &> C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\type_traits:1696:0
#10 0x00007ffb2888ef8b std::_Func_impl_no_alloc<`lldb_private::Debugger::StartIOHandlerThread'::`5'::<lambda_1>,unsigned int>::_Do_call C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\functional:878:0
#11 0x00007ffb28a82f80 std::_Func_class<unsigned int>::operator()(void) const C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\functional:921:0
#12 0x00007ffb28a82e0c lldb_private::HostNativeThreadBase::ThreadCreateTrampoline(void *) D:\llvm-project\lldb\source\Host\common\HostNativeThreadBase.cpp:62:0
#13 0x00007ffb48393010 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0xb3010)
#14 0x00007ffb774c4cb0 (C:\WINDOWS\System32\KERNEL32.DLL+0x14cb0)
#15 0x00007ffb78a1edcb (C:\WINDOWS\SYSTEM32\ntdll.dll+0x7edcb)
```
Sometimes there is a racing condition closing CRT file handles and python crashes handling a CRT exception (invalid file handle). 
It seems m_descriptor is invalid in the line `m_descriptor = ::_dup(m_descriptor);` inside `NativeFile::GetStream()`.
