### ISSUE TITLE
[builtins] compiler-rt fails to link absvdi2_test (revision 145139)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11805]
|  |  |
| --- | --- |
| Bugzilla Link | [11433](https://llvm.org/bz11433) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Build log](https://user-images.githubusercontent.com/60944935/143744296-fd342046-ee96-474c-9acf-ae11d6b2af59.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @vitalybuka |

## Extended Description 

System: x86_64-pc-linux-gnu
OS: Gentoo Linux

**Comment by arsenm** [comment]
Old build issue
