### ISSUE TITLE
CMake fails to detect MSVC-built Clang's target triple

### ISSUE THREAD

**Issue by rubenvb** [llvm/llvm-project#11804]
|  |  |
| --- | --- |
| Bugzilla Link | [11432](https://llvm.org/bz11432) |
| Version | trunk |
| OS | Windows NT |
| CC | @oscarfv |

## Extended Description 
I get this error when trying to run CMake to use Clang

cmake ../../Source/LLVM -G"NMake Makefiles JOM" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

CMake Error at cmake/modules/GetTargetTriple.cmake:24 (message):
  Failed to execute M:/Development/Source/LLVM/autoconf/config.guess
Call Stack (most recent call first):
  cmake/config-ix.cmake:291 (get_target_triple)
  CMakeLists.txt:205 (include)

**Comment by arsenm** [comment]
Old build issue, I assume this was fixed as part of the complete move to cmake
