### ISSUE TITLE
[middle-end] Crash in llvm::scc_begin

### ISSUE THREAD

**Issue by FFreestanding** [llvm/llvm-project#118169]
## Description
version: llvm-19.1.4, llvm-13
path: llvm-19.1.4/llvm/include/llvm/ADT/SCCIterator.h
call `scc_begin` when the llvm::Function is declaration, will trigger crash
`F` is a decaration: `declare i32 @printf(ptr noundef, ...) #1`
```cpp
 for (scc_iterator<Function *> I = llvm::scc_begin(&F),
                                  IE = llvm::scc_end(&F);
         I != IE; ++I)
```
```cpp
  static scc_iterator begin(const GraphT &G) {
      return scc_iterator(GT::getEntryNode(G));
  }
```
GT::getEntryNode(G) will return a invalid NodeRef
```cpp
template <> struct GraphTraits<Function *> : public GraphTraits<BasicBlock *> {
  static NodeRef getEntryNode(Function *F) {
    return &F->getEntryBlock();
  }
```
DFSVisitOne will use it
```cpp
  scc_iterator(NodeRef entryN) : visitNum(0) {
    DFSVisitOne(entryN);
    GetNextSCC();
  }
```
N is invalid, visit nodeVisitNumbers[N] will crash
```cpp
template <class GraphT, class GT>
void scc_iterator<GraphT, GT>::DFSVisitOne(NodeRef N) {
  ++visitNum;
  nodeVisitNumbers[N] = visitNum;
  SCCNodeStack.push_back(N);
  VisitStack.push_back(StackElement(N, GT::child_begin(N), visitNum));
#if 0 // Enable if needed when debugging.
  dbgs() << "TarjanSCC: Node " << N <<
        " : visitNum = " << visitNum << "\n";
#endif
}
```
## Testcase
test.ll
```
; ModuleID = 'test.c'
source_filename = "test.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@.str = private unnamed_addr constant [8 x i8] c"func a\0A\00", align 1
@.str.1 = private unnamed_addr constant [8 x i8] c"func b\0A\00", align 1
@.str.2 = private unnamed_addr constant [5 x i8] c"end\0A\00", align 1

; Function Attrs: noinline nounwind optnone uwtable
define dso_local void @a() #0 {
  %1 = call i32 (ptr, ...) @printf(ptr noundef @.str)
  ret void
}

declare i32 @printf(ptr noundef, ...) #1

; Function Attrs: noinline nounwind optnone uwtable
define dso_local void @b() #0 {
  %1 = call i32 (ptr, ...) @printf(ptr noundef @.str.1)
  ret void
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @main() #0 {
  %1 = alloca i32, align 4
  %2 = alloca i32, align 4
  store i32 0, ptr %1, align 4
  store i32 1, ptr %2, align 4
  call void @b()
  %3 = load i32, ptr %2, align 4
  %4 = icmp sgt i32 %3, 0
  br i1 %4, label %5, label %11

5:                                                ; preds = %0
  %6 = load i32, ptr %2, align 4
  %7 = icmp sgt i32 %6, -1
  br i1 %7, label %8, label %9

8:                                                ; preds = %5
  call void @b()
  store i32 1, ptr %1, align 4
  br label %18

9:                                                ; preds = %5
  br label %10

10:                                               ; preds = %15, %9
  call void @a()
  br label %16

11:                                               ; preds = %0
  %12 = load i32, ptr %2, align 4
  %13 = icmp slt i32 %12, -1
  br i1 %13, label %14, label %15

14:                                               ; preds = %11
  br label %16

15:                                               ; preds = %11
  br label %10

16:                                               ; preds = %14, %10
  %17 = call i32 (ptr, ...) @printf(ptr noundef @.str.2)
  br label %18

18:                                               ; preds = %16, %8
  %19 = load i32, ptr %1, align 4
  ret i32 %19
}

attributes #0 = { noinline nounwind optnone uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }

!llvm.module.flags = !{!0, !1, !2, !3, !4}
!llvm.ident = !{!5}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{i32 7, !"frame-pointer", i32 2}
!5 = !{!"clang version 19.1.4"}

```
llvm pass code
```cpp
  for (auto &F : M) {
    for (scc_iterator<Function *> I = llvm::scc_begin(&F),
                                  IE = llvm::scc_end(&F);
         I != IE; ++I) {
    }
  }
```
command
```sh
opt -debug-pass-manager -load-pass-plugin=build/xxx/xxx.so -passes=xxx -disable-output test.ll > "test.ll.txt" 2>&1
```

**Comment by nikic** [comment]
Does it assert in an assertion-enabled build? This looks like user error to me.

**Comment by EugeneZelenko** [comment]
Please provide complete stack.

**Comment by FFreestanding** [comment]
> Please provide complete stack.
Thanks.

Stack dump:
0.	Program arguments: opt -debug-pass-manager -load-pass-plugin=build/testpass/testpass.so -passes=testpass -disable-output inputs/test/test.ll
 #0 0x00007df5fb7ea868 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x00007df5fb7e78db SignalHandler(int) Signals.cpp:0:0
 #2 0x00007df5fae45320 (/lib/x86_64-linux-gnu/libc.so.6+0x45320)
 #3 0x00007df5fa3b90e6 llvm::ilist_node_base<false>::getNext() const (build/testpass/testpass.so+0x1b90e6)
 #4 0x00007df5fa3c0e34 llvm::ilist_node_impl<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void> >::getNext() const (build/testpass/testpass.so+0x1c0e34)
 #5 0x00007df5fa3bd8b5 llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>::operator++() (build/testpass/testpass.so+0x1bd8b5)
 #6 0x00007df5fa3c0e60 std::iterator_traits<llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true> >::difference_type std::__distance<llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true> >(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, std::input_iterator_tag) (build/testpass/testpass.so+0x1c0e60)
 #7 0x00007df5fa3ba907 llvm::simple_ilist<llvm::Instruction>::size() const (build/testpass/testpass.so+0x1ba907)
 #8 0x00007df5fa3b91b4 llvm::BasicBlock::size() const (build/testpass/testpass.so+0x1b91b4)
 #9 0x00007df5fa3b9a24 llvm::control_flow_graph::control_flow_graph(llvm::Function&) (build/testpass/testpass.so+0x1b9a24)
#10 0x00007df5fa3b55b5 llvm::testpass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (build/testpass/testpass.so+0x1b55b5)
#11 0x00007df5fa3eef4b llvm::detail::PassModel<llvm::Module, llvm::testpass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (build/testpass/testpass.so+0x1eef4b)
#12 0x00007df5fbc832b1 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/ffreestanding/envs/llvm-13/llvm-project/build/bin/../lib/libLLVMCore.so.13+0x2832b1)
#13 0x00005f0a0807db95 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::StringRef>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool) (/home/ffreestanding/envs/llvm-13/llvm-project/build/bin/opt+0x34b95)
#14 0x00005f0a0806d37b main (/home/ffreestanding/envs/llvm-13/llvm-project/build/bin/opt+0x2437b)
#15 0x00007df5fae2a1ca __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#16 0x00007df5fae2a28b call_init ./csu/../csu/libc-start.c:128:20
#17 0x00007df5fae2a28b __libc_start_main ./csu/../csu/libc-start.c:347:5
#18 0x00005f0a0806f405 _start (/home/ffreestanding/envs/llvm-13/llvm-project/build/bin/opt+0x26405)
Segmentation fault (core dumped)

**Comment by FFreestanding** [comment]
> Does it assert in an assertion-enabled build? This looks like user error to me.

It doesn't assert in an assertion-enabled build.
