### ISSUE TITLE
LLVM can't handle spaces in directory names

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11823]
|  |  |
| --- | --- |
| Bugzilla Link | [11451](https://llvm.org/bz11451) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
When the full path to the LLVM source directory contains a space, make will fail with a cryptic error message (on OSX Lion 10.7).

Example:

LLVM_SRC_ROOT=/Volumes/OSX Data/Projects/llvm

make

result:

$ make 
Makefile:145: /Volumes/OSX/Makefile.rules: No such file or directory
make: *** No rule to make target `/Volumes/OSX/Makefile.rules'.  Stop.

The only way to fix this is to rename the Volume (ie rename to OSX_Data, configure, builds fine).

Incredibly annoying (if the drive is used for anything but llvm) and hard to google an answer for.

**Comment by arsenm** [comment]
Old autotools build
