### ISSUE TITLE
[Clang]Uninitialized variables are set to -1 at optimization levels of - O1 and above

### ISSUE THREAD

**Issue by muxiff** [llvm/llvm-project#118246]
Consider the following case ，
https://godbolt.org/z/8fKaq9Yhh

 When the optimization level is - O1 or above, it is found that uninitialized variables are set to -1 by default, which is different from the behavior of gcc's policy setting to 0 by default. Is this the default policy of LLVM with optimization, is there a way to avoid it, or is it necessary to strictly manually set the initial value of all variables？

**Comment by asl** [comment]
Your code contains an undefined behavior. There is no "policy setting uninitialized variables to -1 by default" (neither in LLVM nor in gcc). Uninitialized variables are uninitialized, their values are arbitrary. 

Compile your code with ubsan / asan to catch such mistakes
