### ISSUE TITLE
narrowing conversion of ‘266’ from ‘unsigned int’ to ‘unsigned char’ [-Wnarrowing] in /mnt/f/linuxlibrary/llvm-project/BuildAllElementDebug/Build/lib/Target/RISCV/RISCVGenDAGISel.inc

### ISSUE THREAD

**Issue by adjfangjiawei** [llvm/llvm-project#118259]
When I build llvm-20 with this option:
```shell
cmake -S llvm -B BuildAllElementDebug/Build -DCMAKE_INSTALL_PREFIX=BuildAllElementDebug/Install -G Ninja -DLLVM_ENABLE_PROJECTS="bolt;clang;clang-tools-extra;compiler-rt;cross-project-tests;libc;libclc;lld;lldb;mlir;openmp;polly;pstl" -DLLVM_ENABLE_RUNTIMES="libunwind;libcxxabi;libcxx;llvm-libgcc;offload" -DLIBC_GPU_BUILD=ON -DLLVM_CCACHE_BUILD=ON -DLLVM_ENABLE_DAGISEL_COV=ON -DLLVM_ENABLE_GISEL_COV=ON -DLLVM_INSTALL_UTILS=ON -DLLVM_INSTALL_MODULEMAPS=ON -DLLVM_USE_FOLDERS=ON -DLLVM_TOOL_LLVM_DRIVER_BUILD=ON -DCMAKE_BUILD_TYPE=Debug -DLLVM_ENABLE_FFI=ON -DLLVM_ENABLE_Z3_SOLVER=ON -DLLVM_ENABLE_CURL=ON -DLLVM_HAS_LOGF128=ON -DLLVM_ENABLE_HTTPLIB=ON -DLLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=ON -DLLVM_USE_INTEL_JITEVENTS=ON -DLLVM_USE_OPROFILE=ON -DLLVM_BUILD_EXAMPLES=ON -DLLVM_BUILD_TESTS=ON -DLLVM_INSTALL_GTEST=ON -DLLVM_BUILD_BENCHMARKS=ON -DLLVM_BUILD_DOCS=ON -DLLVM_ENABLE_DOXYGEN=ON -DLLVM_ENABLE_SPHINX=ON -DBUILD_SHARED_LIBS=ON -DLLVM_OPTIMIZED_TABLEGEN=ON -DDLLVM_BUILD_INSTRUMENTED_COVERAGE=ON -DDLLVM_APPEND_VC_REV=ON -DDLLVM_ENABLE_LIBCXX=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DLIBCLC_CUSTOM_LLVM_TOOLS_BINARY_DIR=/usr/bin -DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_RTTI=ON
```
I get such errors.
![Image](https://github.com/user-attachments/assets/c4640d0a-4993-448d-b004-54f0a4324456)
The `MarcherTable` is a char array, but the element in this table was an integer.
![Image](https://github.com/user-attachments/assets/6dbaf116-2ed8-4aa0-b550-2a1e85bdd6f5)
![Image](https://github.com/user-attachments/assets/833eec60-b553-4fe2-9bd3-1792408c2330)
The solution of the `TARGET_VAL` macro is an unsigned int.
![Image](https://github.com/user-attachments/assets/01e307aa-1082-409a-b81f-2904afa5b886)

**Comment by adjfangjiawei** [comment]
> I think `TARGET_VAL(…)` is actually placing two adjacent (unsigned) chars into the opcode array, one for the low 8 bits of the value, and one for the next 8 bits - and the issue is that it's trying to encode a value that doesn't fit into 16 bits (the error messages seem to point out that
> 
> ~This seems like quite a big problem, I'm not sure how the RISC-V backend has gone over 2^16 ISD node IDs, and how we haven't caught this with a compile-time error.~
> 
> It's not encoding an ISD node, it's encoding a coverage value, from the `-instrument-coverage` tablegen option. This coverage seems to believe that pattern indexes can only be 16-bit, and the code to emit the pattern match table (`MatchTableEmittter::EmitPatternMatchTable`) seems to have an assert - which might be turned off by your configuration?
> 
> Are you using `-instrument-patterns` and asking LLVM to optimize tablegen?

I use the DLLVM_OPTIMIZED_TABLEGEN=ON option.

**Comment by lenary** [comment]
Yeah, if you weren't using `DLLVM_OPTIMIZED_TABLEGEN=On`, then the assert would have fired.

This probably means we need to extend the size of the indexes in `OPC_Coverage` operations. I don't think that's particularly difficult.
