### ISSUE TITLE
Raptor Lake CPU detected as Alder Lake

### ISSUE THREAD

**Issue by edwloef** [llvm/llvm-project#118205]
rustc detects my i7-13700H as Alder Lake, Wikipedia lists it as Raptor Lake. Looking through rustc issues, it seems these kinds of misclassifications have always been LLVM bugs so I decided to report it here.

![Image](https://github.com/user-attachments/assets/3f179884-0005-4d52-9ec4-50502906ad63)
![Image](https://github.com/user-attachments/assets/9eebc6f7-b4e8-4562-9fd1-9666c9f76e5c)

**Comment by boomanaiden154** [comment]
We're mostly following gcc for these things.

https://github.com/gcc-mirror/gcc/blob/e1009b3de2d05782ae1e0c62f9e81da14c4d6156/gcc/common/config/i386/i386-cpuinfo.h#L69

RocketLake/MeteorLake/Gracemont are all aliased to AlderLake in LLVM and GCC. 

@FreddyLeaf Why is this aliased here? I don't think we do this for any core other than AlderLake.

**Comment by phoebewang** [comment]
They have the same subtype, and there are precedents, e.g., "Kaby Lake" and "Comet Lake" are detected as "skylake" too. But there is a difference here, we have defined "raptorlake", "meteorlake" etc. in X86.td, so I think we may assign them different names even they have the same subtype #118237.
