### ISSUE TITLE
Clang: modules and std::initializer_list do not like each other

### ISSUE THREAD

**Issue by jijjijj** [llvm/llvm-project#118218]
Clang version: 19.1.3
C++ version: 23
STL: from msvc

I was trying to compile nlohmann json using modules and I encountered an error (posting the original error for others who might google it):
```
C:\Users\username\.conan2\p\nlohm0567ffc90cfc1\p\include\nlohmann\detail\input\lexer.hpp:748:66: error: no matching constructor for initialization of 'std::initializer_list<char_int_type>' (aka 'initializer_list<int>')
  748 |                     if (JSON_HEDLEY_UNLIKELY(!next_byte_in_range({0x80, 0xBF})))
```

I tried to reduce code to the minimum reproducible example and here's what I got (pay attention to the highlighted lines changing which kind of fixes the issue):

<pre>
// main.cpp

import std; // <b><i>Workaround 1: if I delete this line everything works fine</i></b>
import mod;

int main() {
    lexer{}.func({1,1});
    return 0;
}
</pre>

```
// mod.cppm

module;

#include "inc.hpp"

export module mod;

export using ::lexer;
export using ::adapter;
```

<pre>
// inc.hpp

#pragma once

#include &lt;initializer_list>
#include &lt;string>

struct adapter {
    using char_type = char;
};

template&lt;typename InputAdapterType = adapter>
class lexer
{
    using char_type = typename InputAdapterType::char_type; // <b><i>Workaround 2: if I replace "InputAdapterType" here with "adapter" everything works fine</i></b>
    using char_int_type = typename std::char_traits&lt;char_type>::int_type;

public:
    void func(std::initializer_list&lt;char_int_type> ranges) {}
};
</pre>

<pre>
// std.cppm

module;

#define _BUILD_STD_MODULE // <b><i>Workaround 3: if I delete this line everything works fine</i></b>

#include &lt;intrin.h>

export module std;

#include &lt;initializer_list>
#include &lt;regex> // <b><i>Workaround 4: if I delete this line everything works fine</i></b>
</pre>

<details>
<summary>The full error I get</summary>

```
C:/Users/username/CLionProjects/untitled23_1/std/modules/std.msvc.cppm:9:10: warning: '#include <filename>' attaches the declarations to the named module 'std', which is not usually intended; consider moving that directive before the module declaration [-Winclude-angled-in-module-purview]
    9 | #include <initializer_list>
      |          ^
C:/Users/username/CLionProjects/untitled23_1/std/modules/std.msvc.cppm:7:15: warning: 'std' is a reserved name for a module [-Wreserved-module-identifier]
    7 | export module std;
      |               ^
C:/Users/username/CLionProjects/untitled23_1/std/modules/std.msvc.cppm:10:10: warning: '#include <filename>' attaches the declarations to the named module 'std', which is not usually intended; consider moving that directive before the module declaration [-Winclude-angled-in-module-purview]
   10 | #include <regex>
      |          ^
3 warnings generated.
[4/6] Building CXX object CMakeFiles/untitled23_1.dir/main.cpp.obj
FAILED: CMakeFiles/untitled23_1.dir/main.cpp.obj 
C:\Tools\llvm\bin\clang++.exe  -IC:/Users/username/CLionProjects/untitled23_1/include -IC:/Users/username/CLionProjects/untitled23_1/mod/../include -IC:/Users/username/CLionProjects/untitled23_1/std/include -O0 -std=c++23 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -MD -MT CMakeFiles/untitled23_1.dir/main.cpp.obj -MF CMakeFiles\untitled23_1.dir\main.cpp.obj.d @CMakeFiles\untitled23_1.dir\main.cpp.obj.modmap -o CMakeFiles/untitled23_1.dir/main.cpp.obj -c C:/Users/username/CLionProjects/untitled23_1/main.cpp
C:/Users/username/CLionProjects/untitled23_1/main.cpp:6:18: error: no matching constructor for initialization of 'std::initializer_list<char_int_type>' (aka 'initializer_list<int>')
    6 |     lexer{}.func({1,1});
      |                  ^~~~~
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\initializer_list:33:15: note: candidate constructor not viable: no known conversion from 'int' to 'const int *' for 1st argument
   33 |     constexpr initializer_list(const _Elem* _First_arg, const _Elem* _Last_arg) noexcept
      |               ^                ~~~~~~~~~~~~~~~~~~~~~~~
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\initializer_list:21:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
   21 | class initializer_list {
      |       ^~~~~~~~~~~~~~~~
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\initializer_list:21:7: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
   21 | class initializer_list {
      |       ^~~~~~~~~~~~~~~~
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\initializer_list:31:15: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
   31 |     constexpr initializer_list() noexcept : _First(nullptr), _Last(nullptr) {}
      |               ^
C:\Users\username\CLionProjects\untitled23_1\mod\..\include\inc.hpp:17:52: note: passing argument to parameter 'ranges' here
   17 |     void func(std::initializer_list<char_int_type> ranges) {}
      |                                                    ^
1 error generated.
```

</details>

**Comment by shafik** [comment]
CC @ChuanqiXu9

**Comment by jijjijj** [comment]
Seems to happen because `bool Sema::isStdInitializerList` cannot recognize `std::initializer_list` as initializer_list if it's defined in `<implicit global module>`

**Comment by jijjijj** [comment]
@ChuanqiXu9 Anyway what's the benefit of splitting `<global>` and `<implicit global>`? There's no such thing in the standard, and it looks like it complicates the implementation with corner cases like the one above

**Comment by ChuanqiXu9** [comment]
@jijjijj the reason why we split <global> and <implicit global> is, the contents in `<global>` may be exported but `<implicit global>` may not. It relates to some internal implementation logics.

**Comment by ChuanqiXu9** [comment]
@jijjijj And out of curiosity, since I don't have environment for MSVC, does it mean we can use clang to compile the std module from MSSTL?

**Comment by jijjijj** [comment]
@ChuanqiXu9 it was compilable already, but as we saw with this issue, the problems may arise when you *use* this module

**Comment by ChuanqiXu9** [comment]
> [@ChuanqiXu9](https://github.com/ChuanqiXu9) it was compilable already, but as we saw with this issue, the problems may arise when you _use_ this module

Got it. Fine enough.
