### ISSUE TITLE
landingpad crash when compiling ParserTest.cpp from podofo

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11820]
|  |  |
| --- | --- |
| Bugzilla Link | [11448](https://llvm.org/bz11448) |
| Version | trunk |
| OS | FreeBSD |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
FreeBSD clang version 3.0 (branches/release_30 142614) 20111021
Target: x86_64-unknown-freebsd10.0
Thread model: posix

Building CXX object test/ParserTest/CMakeFiles/ParserTest.dir/ParserTest.cpp.o

The unwind destination does not have a landingpad instruction!
  invoke void @&#8203;_ZN6PoDoFo9PdfParser9ParseFileEPKcb(%"class.PoDoFo::PdfParser"* %parser, i8* %pszInput.0, i1 zeroext %tobool)
          to label %do.end unwind label %lpad138.preheader
Block containing LandingPadInst must be jumped to only by the unwind edge of an invoke.
  %80 = landingpad { i8*, i32 } personality i8* bitcast (i32 (...)* @&#8203;__gxx_personality_v0 to i8*)
          cleanup
          catch i8* bitcast ({ i8*, i8*, i8* }* @&#8203;_ZTIN6PoDoFo8PdfErrorE to i8*)
Instruction does not dominate all uses!
  %80 = landingpad { i8*, i32 } personality i8* bitcast (i32 (...)* @&#8203;__gxx_personality_v0 to i8*)
          cleanup
          catch i8* bitcast ({ i8*, i8*, i8* }* @&#8203;_ZTIN6PoDoFo8PdfErrorE to i8*)
  %81 = extractvalue { i8*, i32 } %80, 0
Instruction does not dominate all uses!
  %80 = landingpad { i8*, i32 } personality i8* bitcast (i32 (...)* @&#8203;__gxx_personality_v0 to i8*)
          cleanup
          catch i8* bitcast ({ i8*, i8*, i8* }* @&#8203;_ZTIN6PoDoFo8PdfErrorE to i8*)
  %82 = extractvalue { i8*, i32 } %80, 1
Instruction does not dominate all uses!
  %82 = extractvalue { i8*, i32 } %80, 1
  %matches = icmp eq i32 %82, %74
Instruction does not dominate all uses!
  %matches = icmp eq i32 %82, %74
  br i1 %matches, label %catch, label %ehcleanup198
Broken module found, compilation aborted!
Stack dump:
0.	Program arguments: /usr/bin/clang++ -cc1 -triple x86_64-unknown-freebsd10.0 -emit-obj -disable-free -main-file-name ParserTest.cpp -mrelocation-model static -mdisable-fp-elim -relaxed-aliasing -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu core2 -momit-leaf-frame-pointer -coverage-file CMakeFiles/ParserTest.dir/ParserTest.cpp.o -resource-dir /usr/bin/../lib/clang/3.0 -I /usr/local/include -I /usr/local/include/lua51 -I /usr/ports/graphics/podofo/work/podofo-0.9.1 -I /usr/ports/graphics/podofo/work/podofo-0.9.1/src -I /usr/local/include/freetype2 -fmodule-cache-path /var/tmp/clang-module-cache -O2 -fdeprecated-macro -ferror-limit 19 -fmessage-length 80 -fgnu-runtime -fobjc-runtime-has-arc -fobjc-runtime-has-weak -fobjc-fragile-abi -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o CMakeFiles/ParserTest.dir/ParserTest.cpp.o -x c++ /usr/ports/graphics/podofo/work/podofo-0.9.1/test/ParserTest/ParserTest.cpp 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/usr/ports/graphics/podofo/work/podofo-0.9.1/test/ParserTest/ParserTest.cpp'.
4.	Running pass 'Module Verifier' on function '@main'
clang++: error: unable to execute command: Abort trap: 6 (core dumped)
clang++: error: clang frontend command failed due to signal 2 (use -v to see invocation)

**Comment by Endilll** [comment]
Link to preprocessed source is dead.
