### ISSUE TITLE
SAFECode causes certain C++ programs to crash on startup

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11837]
|  |  |
| --- | --- |
| Bugzilla Link | [11465](https://llvm.org/bz11465) |
| Version | unspecified |
| OS | Linux |
| Attachments | [test case that reproduces bug](https://user-images.githubusercontent.com/60944935/143744315-ee01eedc-e1e8-4cca-bcda-111fb2db4006.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

On x86_64 Linux, I'm seeing a number of C++ programs crash on startup after being compiled with SAFECode.

The attachment is the bitcode for MultiSource/Prolangs-C++/NP and it exhibits the behavior.

Compiling with

clang -fmemsafety np.ll -L/home/wala1/local/lib

results in the following output when I run the executable:

$ ./a.out 
SAFECode: Fault!
Segmentation fault

and here is a stack trace:

#&#8203;0  0x0000003065269eea in std::_Rb_tree_decrement(std::_Rb_tree_node_base*) () from /usr/lib64/libstdc++.so.6
#&#8203;1  0x000000000040d629 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, unsigned int>, std::_Select1st<std::pair<unsigned int const, unsigned int> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, unsigned int> > >::_M_insert_unique(std::pair<unsigned int const, unsigned int> const&) ()
#&#8203;2  0x000000000040d77a in std::_Rb_tree<unsigned int, std::pair<unsigned int const, unsigned int>, std::_Select1st<std::pair<unsigned int const, unsigned int> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, unsigned int> > >::_M_insert_unique_(std::_Rb_tree_const_iterator<std::pair<unsigned int const, unsigned int> >, std::pair<unsigned int const, unsigned int> const&) ()
#&#8203;3  0x000000000040a7c2 in pool_unregister_stack_debug ()
#&#8203;4  0x00000000004032de in True::True() ()
#&#8203;5  0x0000000000403077 in True::True() ()
#&#8203;6  0x0000000000402601 in __cxx_global_var_init ()
#&#8203;7  0x0000000000402d69 in global constructors keyed to a ()
#&#8203;8  0x0000000000426f6d in __libc_csu_init ()
#&#8203;9  0x000000305f21ec70 in __libc_start_main () from /lib64/libc.so.6
#&#8203;10 0x0000000000402529 in _start ()

As can be observed the error occurs in a call to the SAFECode runtime library, which is presumably being called from some global constructor.

**Comment by Endilll** [comment]
SAFECode is archived.
