### ISSUE TITLE
Request Commit Access For Wheest

### ISSUE THREAD

**Issue by Wheest** [llvm/llvm-project#118451]
### Why Are you requesting commit access ?

I have made several contributions to MLIR recently, and was recommended to request commit access by @makslevental  [here](https://github.com/llvm/llvm-project/pull/117188#issuecomment-2512158316).

Examples of my PRs include:

- #117188
- #115850
- #109990
- #79704
- [#D133977](https://reviews.llvm.org/D133977)

**Comment by tstellar** [comment]
### Activity Summary:
* [5 Pull Requests](https://github.com/llvm/llvm-project/pulls/Wheest) (3 merged)
* Top 3 Committers: @makslevental (2), @joker-eph (1)
* Top 3 Reviewers: @makslevental (2), @joker-eph (2), @ftynse (1)

**Comment by tstellar** [comment]
@Wheest, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.
