### ISSUE TITLE
[AVX-512] Missed `vpmaddwd` and `vpdpwssd` canonicalization

### ISSUE THREAD

**Issue by Validark** [llvm/llvm-project#118433]
[Godbolt link](https://zig.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYgAzKVpMGoAF55gpJfWQE8Ayo3QBhVLQCuLBiABMXUk4AMngMmAByngBGmMQSBgAOqAqE9gyuHl6%2B/onJdgLBoREs0bFcBtaYtqlCBEzEBOme3n5WmDZ5DDV1BAXhUTFxVrX1jZktCsM9IX3FA2UAlFao7sTI7BxoDBMA1BPo2wCkegAi2wACeCyJ9RAHPj57dz7zRwBCBxoAgps7ke50dgYhxO50u1wIt3ufwBISeLz07y%2BPwI2yYCiU9WBpz2ADosH9gDi0RiCG8Pt8BDsAGqBbBhLG7AjoHHJFjMhTuYDATATKmVIjEQKMYAEBAAMRIzni7gg7gAHKRttDaICcchpfMcUcxWSvuSqEDlABZT7HY4AfQAStgACpyS1hc02gCaymwEBtIG2BAAnvFMPNvX7MIcAOyIz7bKPbZHbY2mi00ukMs6%2B/0ASQY/A9moAbvySDj6ECAPTbHy6yPRvBUbYQeNm81J%2BlHY6t7YaQNnNBXOg4YjEEgQXFUFgENWoK52NjKYghCFPBsW612h1O13YbbESqYPD5/ZpkMHcPH46KljuHYIJj51HbfO2EjbYsihDbVC1pgo%2BholEV%2B6Klq4Y2qe8zwhG0bbDWdapsGmbZjaeYFsQRaMIcPgAKzltsYBgO2nbnD28R9tgA5DiOY4TlOlwqHOgiQj4S5Wra9qOi6bpbjue6YAewZhu8oZntsF5XjeIZMPeyHPsKoreteBBgBwCh3heKp4PE9DvrW/4%2BIBx6vCBglgZWkHbgQKxAmcfKPsQ9Ymo2zaKribC1DimYQiyFihOgipnJEhBCHgpiYAA8lQECwRmWaoDmOIPgKaoIHQ6CBgAVOWxkIuSp7ZUilIogAiim1kChAXAAGyKngFXgdsJZlkxK6seuboRSVQ56LpUE1YGrZHJuVnIWVlVQZ1Lx6l8mCqOC2wGve8QsEw6DoAA7ug5qiAwAh4KItBBTx5pTRCTBegViqRF6Zw2sGYUQEwYFxvZy4sWu7HuldN3hfdvUnl8pmYOZxBArmC1Lat62bdtu37egd3neB2WCblnxTTNc0g4ty1rea850ckyCHaox2nedl3Xf6t3fY9CbMaubEbhF5OhV9D36eS/2A8DoNY%2BtuMhPjcNKgjepIxNKPTSQKLo/E6DxCt6IQ8YUNiDD5q5ngTA44IeM7RAyBeo1L3061BWLKiJNKmTn13Q9ht0y171M5TrO/VWUZmRZ82Y%2BDWsEDryCC5EvU%2BO8mExpWOVi6jkuzVzsvywoitbQwO0q8F63q5rkMp9D6d6wbT2081b0QKbiondsZ2W%2BcTss4GdvFwzH0U3X/Hs9GHtA17YPY9nqd7XnTDw%2BhodYcgEei58%2Bpc97vdKznac8XdXrGD6h6kzX1tU4NNkRYe8Exc3zM20hNmoaW5ZOUyOIuUwbn0Z5wDeYqPjbOlfkBftt2RZgB%2BM1vYE4rIUSslMCP0ILRljMgFMaI2pDR/n/I%2BztT4JWLFfZkt974eWSE/HiL837nH8sIL%2B4UEHRX/i3E%2BQCz7ICSrQFKYFy5pSVCZSB%2BVtg%2BRjOwo8IJcSsmZFgecMQjBrAgF1ZAws3acU5hwkedwsKYAnm2MW9VthhFQCiUUIZog7CYO4IgABaBQ0MTBQSuPQNgggvypHOvoqCCklJ3gmN0bY6ZtjAHcDyBQOIfHT27jzX2/tl6ogYGvYMG8kGtwbq9JutcT5tz%2BmwrYKJjiYBoCnDoyl2wTGIO4WwCSpGQSOjEIEc0zhPFoLQXMLAcSqDlOVFkSgfA4m5syNaTw4G7wVN1cqZsd6lW6dVXpXZ2q2WkKNZ4rDIJRmKV3MpFSqk1LqQ0m8qhmmtJxO0%2B4nTSoVSqjVXyozhr7OGecI5gyxpTOmbM0plkFnVNqfUokuZVAYS4Os2eeIcRvJ0jsjqXUhl9KOZ1E5D1%2BlDj2RMyRkEcpZTFpBWMVJirwMWqoCA3TnJfgQGqXctBlCoBWjEMKNoVoxXcJCsh2ZIlUPioWYsgZRAEFodsdwDBtxMFoUwSI9AzaAojokqM0EIrJGCt/OJVN%2BrbGbOA9u0yuHJO2NeWgVAuAMgxj3Xm2t%2Ba6z4ZcZkR1iAcuOoqDQipmwlmeOgzybIcQGqNRASIJqzW0jCBazKEC5WxnoFQIg%2BZiApn3uQ6l31qGoLQgYqVLqLVXIRewpVVBX7tnVQEvmWwdXX34baomhrbCC3NV1b1vqYhm11Tau1ubHWRrpBaxUhbUB%2BvdbK6ZncgTxCWgAdUIAgOQDAsDpJ4goOyNMmoxNasGxhjJ2R6pxNoVAIQIDxv8IqsQCbG0CrDMoqe66W2Tutfq7N9qzg0DaLDVJ6SUiUicitQgzKIBUhleuyC4LbKDJqliSV9yllPPRJgD5YNNnoCeKQJtT6jmQsBe%2BvQm5P2PJWS8v9y0ANAZA9GZ9EAQU9N6icD99xKkPOWc8157yWmfOZD85Dj7oxtCUJBgaRESJkVshRccRFpy0XnAxYAGigz%2BjbkjAC2wgKvCpKBRYTbQIQDbegTtooe19umOgQdVImGKikzJ7tva0kKaU/DM2prziBuzNE42jsAGANpShelSjkZ%2BLU12uTWnvKDs9DxzAipcxiE8SvUJh5AxCrOCK4%2B1KPMeADFhgagXbqIS7HEkLnjAzUZDDaApsaFVSfwCYc0xYA1wXIYhUNdLw0Gdy1S2LnmwsFcs4wK5O6hXpZCMALLaEjjOHwoGOLIZEu7szbO%2BdHXfKwLQ/VzLaDitRQQigwstDQG%2BQUBpL8spNP9oYZIyOnwOCLFoJwDCvBvAcC0KQVAnAABaFhdjLFWEeHweg9C8AIJoDbiwECYCWgMCAiwADWIAMINIAJy/a4KGX7oY9Byh8HKUMGhyqSGkFtjgkheAsAkBoU1e2DtHY4LwBQIBTX3f2xt0gcBYBIHo/QMgFA9aTmImTkApg/aso%2B3wAEMRscOoe6QfyzBiA%2Bk4DwDnIQ6g%2BhCpEbQ/Jee8B7JYggIUGC0B5/j0g%2BJOTODELQbH3BeBYEWiYcQCv8DbiqPmdXB2pqVH0esPnQi4cHb2pEQ13PXBYHZ37S44vSB%2BsiEkTAqTtfAD2iYB7iwqBGGAAoKkeBMArRCv6PbfP%2BCCBEGIdgUgZCCEUCodQCvdC6SMAH8wlhbfY8gIsVA8RMmcAMSFbYlo2gvaUGKX82wDHDG5CiZZ5pocGP9%2B4VQTeWDqncK2UwDA/U7cO36ucWAi/vdaO0VIjhe2jG8P4II0wiglAkKQHIF60huCaJv7fHRejr7mLP/k1RJhL83xUKoAguj1GP/0UoQxuhX/8M4h/a%2Bn8SEWAoC7ax9BNtttdt2cMdth89vRckGAPs6xcBCAnw7gbt5g7tA8nsXssBYgZ8vtJA9AcQUcwcNAfBypAd3lfs9AftDBOAEdSAkcuAUdSA0deAMcsccdSA8ctBGE4cfAQCFdmC2DUD3cWd59JAgA%3D%3D%3D)

My attempts in getting the compiler to emit `vpmaddwd` via an intrinsic and via canonicalization were both successful:

```zig
export fn vpmaddwd_canonicalized_ext(a: Q, b: @TypeOf(a)) PMADD_RETURN_TYPE(@TypeOf(a)) {
    return vpmaddwd_canonicalized(a, b);
}

export fn vpmaddwd_intrinsic_ext(a: Q, b: @TypeOf(a)) PMADD_RETURN_TYPE(@TypeOf(a)) {
    return vpmaddwd_intrinsic(a, b);
}
```

```asm
vpmaddwd_canonicalized_ext:
        vpmaddwd        ymm0, ymm1, ymm0
        ret

vpmaddwd_intrinsic_ext:
        vpmaddwd        ymm0, ymm0, ymm1
        ret
```

However, when I tried adding a vector of the result type of `vpmaddwd`, I got mixed results. Code:

```zig
export fn vpdpwssd_canonicalized_via_intrinsic(c: PMADD_RETURN_TYPE(Q), a: Q, b: @TypeOf(a)) PMADD_RETURN_TYPE(@TypeOf(a)) {
    return vpmaddwd_intrinsic(a, b) +% c;
}

export fn vpdpwssd_canonicalized_via_canonicalized(c: PMADD_RETURN_TYPE(Q), a: Q, b: @TypeOf(a)) PMADD_RETURN_TYPE(@TypeOf(a)) {
    return vpmaddwd_canonicalized(a, b) +% c;
}
```

Emit:

```asm
vpdpwssd_canonicalized_via_intrinsic:
        {vex}   vpdpwssd      ymm0, ymm1, ymm2
        ret

vpdpwssd_canonicalized_via_canonicalized:
        vpmovsxwd       zmm1, ymm1
        vpmovsxwd       zmm2, ymm2
        vpmulld zmm1, zmm2, zmm1
        vpmovqd ymm2, zmm1
        vextracti64x4   ymm3, zmm1, 1
        vshufps ymm1, ymm1, ymm3, 221
        vpermpd ymm1, ymm1, 216
        vpaddd  ymm0, ymm1, ymm0
        vpaddd  ymm0, ymm0, ymm2
        ret
```

Full code:

```zig
const std = @import("std");
const builtin = @import("builtin");
const assert = std.debug.assert;
const VLEN = std.simd.suggestVectorLengthForCpu(u8, builtin.cpu).?;

fn PMADD_RETURN_TYPE(T: type) type {
    const PMADD_VLEN = @typeInfo(T).vector.len / 2;
    if (PMADD_VLEN == 0) @compileError(std.fmt.comptimePrint("PMADD_RETURN_TYPE received type {}, must have a vector length of at least 2", .{T}));
    if (@typeInfo(T).vector.len % 2 != 0) @compileError(std.fmt.comptimePrint("PMADD_RETURN_TYPE received type {}, must have a vector length that's a multiple of 2", .{T}));
    return @Vector(PMADD_VLEN, std.meta.Int(.signed, @bitSizeOf(@typeInfo(T).vector.child) * 2));
}

const Q = @Vector(16, i16); // PMADD_RETURN_TYPE(@Vector(32, i16)) => @Vector(16, i32)

export fn vpmaddwd_canonicalized_ext(a: Q, b: @TypeOf(a)) PMADD_RETURN_TYPE(@TypeOf(a)) {
    return vpmaddwd_canonicalized(a, b);
}

export fn vpmaddwd_intrinsic_ext(a: Q, b: @TypeOf(a)) PMADD_RETURN_TYPE(@TypeOf(a)) {
    return vpmaddwd_intrinsic(a, b);
}

export fn vpdpwssd_canonicalized_via_intrinsic(c: PMADD_RETURN_TYPE(Q), a: Q, b: @TypeOf(a)) PMADD_RETURN_TYPE(@TypeOf(a)) {
    return vpmaddwd_intrinsic(a, b) +% c;
}

export fn vpdpwssd_canonicalized_via_canonicalized(c: PMADD_RETURN_TYPE(Q), a: Q, b: @TypeOf(a)) PMADD_RETURN_TYPE(@TypeOf(a)) {
    return vpmaddwd_canonicalized(a, b) +% c;
}

fn vpmaddwd_canonicalized(a: anytype, b: @TypeOf(a)) @Vector(@typeInfo(@TypeOf(a)).vector.len / 2, std.meta.Int(.signed, 2 * @bitSizeOf(@typeInfo(@TypeOf(a)).vector.child))) {
    const c = @as(@Vector(@typeInfo(@TypeOf(a)).vector.len, std.meta.Int(.signed, 2 * @bitSizeOf(@typeInfo(@TypeOf(a)).vector.child))), a) * b;
    const d, const e = std.simd.deinterlace(2, c);
    return d +% e;
}

// Not the best auto-scaling implementation, but it's a start I guess...
fn vpmaddwd_intrinsic(a: anytype, b: @TypeOf(a)) PMADD_RETURN_TYPE(@TypeOf(a)) {
    const Definitions = struct {
        extern fn @"llvm.x86.sse2.pmadd.wd"(@Vector(8, i16), @Vector(8, i16)) @Vector(4, i32);
        extern fn @"llvm.x86.avx2.pmadd.wd"(@Vector(16, i16), @Vector(16, i16)) @Vector(8, i32);
        extern fn @"llvm.x86.avx512.pmaddw.d.512"(@Vector(32, i16), @Vector(32, i16)) @Vector(16, i32);
    };

    const V = @Vector(@max(8, std.math.ceilPowerOfTwo(u16, @typeInfo(@TypeOf(a)).vector.len) catch unreachable), i16);

    if (@sizeOf(@TypeOf(a)) > VLEN) {
        const half1 = vpmaddwd_intrinsic(std.simd.extract(a, 0, VLEN/2), std.simd.extract(b, 0, VLEN/2));
        const leftover = @typeInfo(@TypeOf(a)).vector.len - VLEN/2;
        const half2 = vpmaddwd_intrinsic(std.simd.extract(a, VLEN/2, leftover), std.simd.extract(b, VLEN/2, leftover));
        return padWithUndefineds(PMADD_RETURN_TYPE(@TypeOf(a)), std.simd.join(half1, half2));
    }

    return std.simd.extract(@field(Definitions, switch (V) {
        @Vector(8, i16) => "llvm.x86.sse2.pmadd.wd",
        @Vector(16, i16) => "llvm.x86.avx2.pmadd.wd",
        @Vector(32, i16) => "llvm.x86.avx512.pmaddw.d.512",
        else => @compileError(std.fmt.comptimePrint("got type {}", .{V})),
    })(padWithUndefineds(V, a), padWithUndefineds(V, b)), 0, @typeInfo(PMADD_RETURN_TYPE(@TypeOf(a))).vector.len);
}


fn padWithUndefineds(T: type, value: anytype) if (@sizeOf(@TypeOf(value)) > @sizeOf(T)) @TypeOf(value) else T {
    const padding_len = @typeInfo(T).vector.len - @typeInfo(@TypeOf(value)).vector.len;
    return if (padding_len <= 0) value else std.simd.join(value, @as(@Vector(padding_len, @typeInfo(T).vector.child), @splat(undefined)));
}
```

Optimized LLVM:

```llvm
define dso_local <8 x i32> @vpmaddwd_canonicalized_ext(<16 x i16> %0, <16 x i16> %1) local_unnamed_addr {
Entry:
  %2 = sext <16 x i16> %0 to <16 x i32>
  %3 = sext <16 x i16> %1 to <16 x i32>
  %4 = mul nsw <16 x i32> %3, %2
  %5 = shufflevector <16 x i32> %4, <16 x i32> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %6 = shufflevector <16 x i32> %4, <16 x i32> poison, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %7 = add <8 x i32> %5, %6
  ret <8 x i32> %7
}

define dso_local <8 x i32> @vpmaddwd_intrinsic_ext(<16 x i16> %0, <16 x i16> %1) local_unnamed_addr {
Entry:
  %2 = tail call <8 x i32> @llvm.x86.avx2.pmadd.wd(<16 x i16> %0, <16 x i16> %1)
  ret <8 x i32> %2
}

declare <8 x i32> @llvm.x86.avx2.pmadd.wd(<16 x i16>, <16 x i16>) #1

define dso_local <8 x i32> @vpdpwssd_canonicalized_via_intrinsic(<8 x i32> %0, <16 x i16> %1, <16 x i16> %2) local_unnamed_addr {
Entry:
  %3 = tail call <8 x i32> @llvm.x86.avx2.pmadd.wd(<16 x i16> %1, <16 x i16> %2)
  %4 = add <8 x i32> %3, %0
  ret <8 x i32> %4
}

define dso_local <8 x i32> @vpdpwssd_canonicalized_via_canonicalized(<8 x i32> %0, <16 x i16> %1, <16 x i16> %2) local_unnamed_addr {
Entry:
  %3 = sext <16 x i16> %1 to <16 x i32>
  %4 = sext <16 x i16> %2 to <16 x i32>
  %5 = mul nsw <16 x i32> %4, %3
  %6 = shufflevector <16 x i32> %5, <16 x i32> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %7 = shufflevector <16 x i32> %5, <16 x i32> poison, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %8 = add <8 x i32> %7, %0
  %9 = add <8 x i32> %8, %6
  ret <8 x i32> %9
}
```

**Comment by topperc** [comment]
Looks like the 2 adds have been reassociated and broke the pattern recognition. Swapping %6 and %0 in the adds fixes it.

```
define dso_local <8 x i32> @vpdpwssd_canonicalized_via_canonicalized(<8 x i32> %0, <16 x i16> %1, <16 x i16> %2) local_unnamed_addr {
Entry:
  %3 = sext <16 x i16> %1 to <16 x i32>
  %4 = sext <16 x i16> %2 to <16 x i32>
  %5 = mul nsw <16 x i32> %4, %3
  %6 = shufflevector <16 x i32> %5, <16 x i32> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %7 = shufflevector <16 x i32> %5, <16 x i32> poison, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %8 = add <8 x i32> %7, %0
  %9 = add <8 x i32> %8, %6
  ret <8 x i32> %9
}
```

**Comment by RKSimon** [comment]
matchPMADDWD / matchPMADDWD_2 only match very specific add(mul, mul) patterns - but it shouldn't be too difficult to improve this to handle the (possibly reassociated) accumulation stage as well.
