### ISSUE TITLE
Invalid LLVM IR code generated on x86-64 with a very simple sample (crash the generated executable code)

### ISSUE THREAD

**Issue by dje64240** [llvm/llvm-project#118467]
Below is a very simple program that's loading 16 bits table value into a 32 bits variable from a 8 bits table.
On **x86-64** with **-O2** or **-O3** flags, this program works fine with LLVM 16.0.0 and below, but since LLVM 17.0.0, the LLVM IR and the generated assembly code are using a wrong calculated offset on the table (doesn't occurs on LLVM armv8 whatever the version).
As you can see below, the offset in the table which is supposed to be **2149675576** (**0x80217238**) has its 32 upper bits inverted for **-2145291720** (**0xFFFFFFFF80217238**).

```c

#include <stdint.h>

// Load 16 bits into 32 bits value from data offset 0x80217238

uint32_t Test(const uint8_t* data)
{        
    uint32_t a, b, c;    
	b = 0xFFFF8022 << 16;
    b += 0xFFFFE808;    
    a = data[b + 0xFFFF8A31];
    c = data[b + 0xFFFF8A30];
    c &= ~0x0000FF00;
    c |= ((a << 8) | (a >> 24)) & 0x0000FF00;
	return c;
}

```

LLVM IR with LLVM 16.0.0 (from Compiler Explorer)
```ll
define dso_local noundef i32 @Test(unsigned char const*)(ptr nocapture noundef readonly %data) local_unnamed_addr {
entry:
  %arrayidx4 = getelementptr inbounds i8, ptr %data, i64 2149675576
  %0 = load i16, ptr %arrayidx4, align 1
  %1 = zext i16 %0 to i32
  ret i32 %1
}

declare void @llvm.dbg.value(metadata, metadata, metadata) #1
```
LLVM IR with LLVM 19.1.0 and trunk (from Compiler Explorer)
```ll
define dso_local noundef range(i32 0, 65536) i32 @Test(unsigned char const*)(ptr nocapture noundef readonly %data) local_unnamed_addr {
entry:
  %0 = getelementptr i8, ptr %data, i64 -2145291720
  %1 = load i16, ptr %0, align 1
  %2 = zext i16 %1 to i32
  ret i32 %2
}
```

**Comment by topperc** [comment]
opt-bisect suggests AggressiveInstCominer. There were two separate loads that got merged. The resulting GEP had an index of `i32 -2145291720` with trunk and `i64 2149675576` with clang 16. Those would be the same number if GEP zero extended indices instead of sign extending.

**Comment by antoniofrighetto** [comment]
Alive2: https://alive2.llvm.org/ce/z/RXRYZe.

**Comment by AreaZR** [comment]
> opt-bisect suggests AggressiveInstCominer. There were two separate loads that got merged. The resulting GEP had an index of `i32 -2145291720` with trunk and `i64 2149675576` with clang 16. Those would be the same number if GEP zero extended indices instead of sign extending.

See my PR for 19.x
