### ISSUE TITLE
Clang binaries for Ubuntu 11.10/x86 contain 64-bit executables (not 32-bit ones)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11853]
|  |  |
| --- | --- |
| Bugzilla Link | [11481](https://llvm.org/bz11481) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic |

## Extended Description 
Simple repro from CLI session:

$ wget http://llvm.org/releases/3.0/clang+llvm-3.0-i386-linux-Ubuntu-11_10.tar.gz
$ tar xzvfp clang+llvm-3.0-i386-linux-debian.tar.gz
$ ./clang+llvm-3.0-x86_64-linux-Ubuntu-11_10/bin/clang -v
-bash: ./clang+llvm-3.0-x86_64-linux-Ubuntu-11_10/bin/clang: cannot execute binary file
$ file clang+llvm-3.0-x86_64-linux-Ubuntu-11_10/bin/clang
clang+llvm-3.0-x86_64-linux-Ubuntu-11_10/bin/clang: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.15, stripped

Note the "ELF 64-bit" part in the last command.

**Comment by arsenm** [comment]
Old packaging issue
