### ISSUE TITLE
libc: fails to build with `add_custom_target cannot create target "libc" because another target with the same name already exists`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#118558]
Not sure what caused it. Maybe #117220  by @nickdesaulniers 
```
-- Looking for logf128 - found
-- Targeting M68k
-- Targeting Xtensa
-- Targeting AArch64
-- Setting LIBC_NAMESPACE namespace to '__llvm_libc_20_0_0_'
g++: error: unrecognized command-line option '--print-resource-dir'; did you mean '--print-search-dirs'?
g++: fatal error: no input files
compilation terminated.
-- Set COMPILER_RESOURCE_DIR to /usr/lib/gcc/aarch64-linux-gnu/10/ using --print-search-dirs
-- Building libc for aarch64 on linux with
        LIBC_COMPILE_OPTIONS_DEFAULT: 
-- LIBC_CONF_ENABLE_STRONG_STACK_PROTECTOR: ON
```

Regression range 356df2dd72e8..1e7171f692d0
Fails log:
https://llvm-jenkins.debian.net/job/llvm-toolchain-bullseye-binaries/architecture=arm64,distribution=bullseye,label=arm64/1608/console

**Comment by nickdesaulniers** [comment]
```
g++: error: unrecognized command-line option '--print-resource-dir'; did you mean '--print-search-dirs'?
g++: fatal error: no input files
```
I think is a red herring; I observe that when building llvm-libc with g++; it's orthogonal to https://github.com/llvm/llvm-project/pull/117220 and I don't think that's why your build is failing. I'm looking closer at the logs now to better understand why your build did fail.

**Comment by nickdesaulniers** [comment]
<details>
<summary>actual cmake error</summary>

```
CMake Error at cmake/modules/LLVMExternalProjectUtils.cmake:453 (add_custom_target):
  add_custom_target cannot create target "libc" because another target with
  the same name already exists.  The existing target is a static library
  created in source directory "/build/source/libc/lib".  See documentation
  for policy CMP0002 for more details.
Call Stack (most recent call first):
  runtimes/CMakeLists.txt:266 (llvm_ExternalProject_Add)
  runtimes/CMakeLists.txt:559 (runtime_default_target)


CMake Error at cmake/modules/LLVMExternalProjectUtils.cmake:453 (add_custom_target):
  add_custom_target cannot create target "install-libc" because another
  target with the same name already exists.  The existing target is a custom
  target created in source directory "/build/source/libc/lib".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  runtimes/CMakeLists.txt:266 (llvm_ExternalProject_Add)
  runtimes/CMakeLists.txt:559 (runtime_default_target)


CMake Error at cmake/modules/LLVMExternalProjectUtils.cmake:453 (add_custom_target):
  add_custom_target cannot create target "install-libc-stripped" because
  another target with the same name already exists.  The existing target is a
  custom target created in source directory "/build/source/libc/lib".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  runtimes/CMakeLists.txt:266 (llvm_ExternalProject_Add)
  runtimes/CMakeLists.txt:559 (runtime_default_target)


CMake Error at cmake/modules/LLVMExternalProjectUtils.cmake:453 (add_custom_target):
  add_custom_target cannot create target "check-libc" because another target
  with the same name already exists.  The existing target is a custom target
  created in source directory "/build/source/libc/test".  See documentation
  for policy CMP0002 for more details.
Call Stack (most recent call first):
  runtimes/CMakeLists.txt:266 (llvm_ExternalProject_Add)
  runtimes/CMakeLists.txt:559 (runtime_default_target)
```
</details>

**Comment by nickdesaulniers** [comment]
Do you have the ability to reset the CMakeCache.txt file on this buildbot?

**Comment by sylvestre** [comment]
as it is built in a new chroot, i don't think we have an existing cache before

**Comment by nickdesaulniers** [comment]
I wonder if `-DLLVM_LIBC_GPU_BUILD=ON` is somehow tickling this. @jhuber6 mentioned in #libc on discord:

> Trying to fix this but I have no clue why it's broken, keeps telling me that the libc target is  already defined

I wonder if it was the same error encountered?

**Comment by jhuber6** [comment]
It's possible, I did get something similar but I thought i fixed it. I'll do a git pull and clean build and  report back.

**Comment by jhuber6** [comment]
Yep, seems busted on the GPU. I got it working earlier but I guess that was a fluke.

**Comment by jhuber6** [comment]
Seems to work if you just delete the entirety of the `LIBC_NEED_GPU_UTILS` check and just make it return if it's a projects build, so likely the logic isn't firing correctly there and returning if we're only trying to build the loader.

**Comment by nickdesaulniers** [comment]
> Seems to work if you just delete the entirety of the LIBC_NEED_GPU_UTILS check and just make it return if it's a projects build

s/LIBC_NEED_GPU_UTILS/LIBC_NEED_LOADER_UTILS/ ?

So:

```diff
diff --git a/libc/CMakeLists.txt b/libc/CMakeLists.txt
index fd82359022cf..b3607a0f1ea8 100644
--- a/libc/CMakeLists.txt
+++ b/libc/CMakeLists.txt
@@ -64,6 +64,9 @@ if(LIBC_BUILD_GPU_LOADER OR NOT LLVM_RUNTIMES_BUILD)
      "${LIBC_TARGET_TRIPLE}" STREQUAL "nvptx64-nvidia-cuda")
     set(LIBC_NEED_LOADER_UTILS TRUE)
   endif()
+  if (not LLVM_RUNTIMES_BUILD)
+    return()
+  endif()
   if(LIBC_NEED_LOADER_UTILS)
     add_subdirectory(utils/gpu)
     return()
```
?

**Comment by jhuber6** [comment]
There's already a check for that, a solution would be to deprecate the projects build and just make it return unconditionally. But we still kind of support that right now.

**Comment by nickdesaulniers** [comment]
Ok, I think I see what's going on.  Prior to e0ae7793fca0c78919bc41ffd407acb62146ad47:

```cmake
if(NOT LLVM_RUNTIMES_BUILD)
  if("libc" IN_LIST LLVM_ENABLE_RUNTIMES)
    set(NEED_LIBC_HDRGEN TRUE) # <----- let's say this gets set
...
if(LIBC_HDRGEN_ONLY OR NEED_LIBC_HDRGEN)
  # When libc is build as part of the runtimes/bootstrap build's CMake run, we
  # only need to build the host tools to build the libc. So, we just do enough
  # to build libc-hdrgen and return.
  return() # <---- then this return is taken
```

so maybe:
```diff
diff --git a/libc/CMakeLists.txt b/libc/CMakeLists.txt
index fd82359022cf..6653705ea119 100644
--- a/libc/CMakeLists.txt
+++ b/libc/CMakeLists.txt
@@ -72,6 +72,10 @@ endif()
 
 add_subdirectory(newhdrgen)
 
+if(NOT LLVM_RUNTIMES_BUILD AND "libc" IN_LIST LLVM_ENABLE_RUNTIMES)
+  return()
+endif()
+
 option(LIBC_CMAKE_VERBOSE_LOGGING
   "Log details warnings and notifications during CMake configuration." OFF)
```
is necessary?

**Comment by jhuber6** [comment]
You'd probably need to use the same logic that `llvm/CMakeLists.txt` uses to *add* it to the projects lists, that's what I thought I did but somehow it's not working here. If I force it to pass once I lose the ability to reproduce it even after clearing the cache.

**Comment by nickdesaulniers** [comment]
Not sure I follow. I'm about to go offline for a few hours. Some ways forward I see are:
1. revert https://github.com/llvm/llvm-project/pull/117220/commits/88a931d30b8a6c05ab590a1919a41775a531f80a hunks
2. stop setting -DLLVM_LIBC_GPU_BUILD=ON for debian for now
3. revert https://github.com/llvm/llvm-project/commit/e0ae7793fca0c78919bc41ffd407acb62146ad47

**Comment by jhuber6** [comment]
It's like hitting this code twice somehow, with the second run undefined a ton of these variables.

**Comment by jhuber6** [comment]
Okay so I think the logic before worked because it would *always* add the libc project and quit. For whatever reason the runtimes variables are just unset in this weird extra run where I don't know where it comes from, Within the projects build it will first run w/ everything set, then again without then set. Maybe this is part of the NATIVE thing? I don't know, maybe @petrhosek can help.

If I print `LLVM_RUNTIME_TARGETS` in `libc/CMakeLists.txt` it will first print the values I have set, then it will print again with an empty string later, but still say that it's not an LLVM runtimes build.

**Comment by michaelrj-google** [comment]
as a quick fix would it be easiest to just add something like `if LLVM_RUNTIME_TARGETS == ""; return` to the start of `libc/CMakeLists.txt`?

**Comment by jhuber6** [comment]
It might come from the "NATIVE" build, but I have no clue what that does.
