### ISSUE TITLE
[libc++] ABI compat breakage using reference type for std::set key_compare

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [llvm/llvm-project#118559]
The following compiled fine with libc++ version 19:
```cpp
#include <set>

struct Cmp {
  __int128 x;
  bool operator()(__int128, __int128) const;
};

struct MySet {
  unsigned char b;
  std::set<__int128, const Cmp &> s;
};

extern char q[sizeof(MySet)];
extern char q[40];
```

It no longer compiles with libc++ trunk (https://godbolt.org/z/cTbEovcer). It seems the size of `MySet` has changed because of a change in `std::set`.
The draft release notes (https://libcxx.llvm.org/ReleaseNotes.html#abi-affecting-changes) mention issues with overaligned empty types, but nothing about reference types.

**Comment by rnk** [comment]
I am personally surprised by how alignof works on references, but it is consistent with `sizeof`. `alignof(__int128&)` is 16, not 8 or pointer-aligned. That seems to be the root cause here.

`__compressed_pair_padding` has some accommodation to avoid adding extra padding around references, but there isn't analogous logic to fix up the alignment attribute.

**Comment by jwakely** [comment]
`std::set<__int128, const Cmp &>` is somewhere in the intersection of underspecified, undefined, and just a very bad idea.

**Comment by hubert-reinterpretcast** [comment]
> `std::set<__int128, const Cmp &>` is somewhere in the intersection of underspecified, undefined, and just a very bad idea.

I tend to agree; however, from that point of view, I think a deliberate compile-time error is better than the ABI break (documented or not).

**Comment by ldionne** [comment]
I do agree that reference comparators are a terrible idea. But this was an unintended ABI break and (unless I missed something) this is easy to address, at least until we officially decide to make such comparators ill-formed: https://github.com/llvm/llvm-project/pull/118685
