### ISSUE TITLE
[clangd] Allow indexing of exposed resource directory headers

### ISSUE THREAD

**Issue by jhuber6** [llvm/llvm-project#118684]
Clang provides several intrinsic headers inside of its resource directory. Most of these are intended to be present in user code, however they prefer to use reserved keywords as they are commonly a part of system headers. These functions are not indexed, which makes working with them very difficult. My specific use-case is from the GPU utility header I've recently added that wraps around common builtins for GPU vendors https://godbolt.org/z/rvTEaeoP3. It's difficult to use this because `clangd` does not autocomplete for any of them. I have https://github.com/llvm/llvm-project/pull/118674 which is the alternate approach to fix this, but the headers are better-off keeping internal names.

**Comment by HighCommander4** [comment]
A couple of possible approaches to this:

 1. Index reserved symbols in some or all headers in the resource directory by default. If we go with this approach, we need to consider what other headers are in the resource directory and whether having their symbols indexed would be appropriate for them as well, or just for specific ones like `*intrin.h`.
 2. Add a flag to opt into indexing symbols in headers in the resource directory. Note that I've tried in the past to add a [config option](https://clangd.llvm.org/config.html) to index all reserved symbols in https://github.com/clangd/clangd/issues/1680, but during the review of that patch it was [noted](https://reviews.llvm.org/D153946#4503585) that a config option, which can be scoped to specific projects/directories, is not a good fit for this. So if we go with this approach, it would need to be a global option like a command line flag.

**Comment by jhuber6** [comment]
> 1. Index reserved symbols in some or all headers in the resource directory by default. If we go with this approach, we need to consider what other headers are in the resource directory and whether having their symbols indexed would be appropriate for them as well, or just for specific ones like `*intrin.h`.

I think this would be the easiest method, and just going off of `*intrin.h` is a good starting point. How difficult would that be?

**Comment by HighCommander4** [comment]
> > 1. Index reserved symbols in some or all headers in the resource directory by default. If we go with this approach, we need to consider what other headers are in the resource directory and whether having their symbols indexed would be appropriate for them as well, or just for specific ones like `*intrin.h`.
> 
> I think this would be the easiest method, and just going off of `*intrin.h` is a good starting point. How difficult would that be?

I think it would be fairly straightforward.

The check that needs to be adjusted is this one:

https://github.com/llvm/llvm-project/blob/22d26ae3040095c7bfe4e2f1678b9738bf81fd4a/clang-tools-extra/clangd/index/SymbolCollector.cpp#L553-L556

We'd want to avoid taking this early return for the affected `*intrin.h` files.

Are you interested in writing a patch? I'm happy to provide a few more details if that helps.
