### ISSUE TITLE
projects/sample/Makefile.llvm.config incorrectly configures x86_64 target as 'x86'

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11862]
|  |  |
| --- | --- |
| Bugzilla Link | [11490](https://llvm.org/bz11490) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
When compiling from trunk on a x86_64 hardware, the projects/sample/Release+Asserts/lib/libsample.a build fails because it gets compiled for i386 rather than x86_64. This misbehavior is caused by a wrong parameter in projects/sample/Makefile.llvm.config line 85:

# Target hardware architecture
ARCH=x86

instead of:

# Target hardware architecture
ARCH=x86_64

And so the build fails without a correcting patch. I think it is very easy to fix.

V.

**Comment by arsenm** [comment]
Makefiles are gone
