### ISSUE TITLE
Crash zero-initializing union with pointer to data member and long double

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#11868]
|  |  |
| --- | --- |
| Bugzilla Link | [11496](https://llvm.org/bz11496) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor |

## Extended Description 
Testcase:

namespace llvm/llvm-project#11859  {
  union U
  {
    int U::* mptr;
    struct S { char a; long double b; } x;
  } x;
}

EmitNullConstant needs to be rewritten from scratch to handle this correctly.

**Comment by xgupta** [comment]
fixed on trunk https://godbolt.org/z/Ej618vYqd.
