### ISSUE TITLE
`-fno-profile-instr-generate` ignored during linking

### ISSUE THREAD

**Issue by cf-coheretech** [llvm/llvm-project#118690]
The `-fno-profile-instr-generate` flag is ignored during linking. This repo has a minimal example: https://github.com/chf2117/noProfileFlag/tree/main

Clang installed from apt

clang --version:
```
Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by EugeneZelenko** [comment]
Could you please try 19 or `main` branch? https://godbolt.org should be helpful.

**Comment by cf-coheretech** [comment]
I don't know the details of instrumentation, but `-fprofile-instr-generate` does something in the command 
```
clang++ -fprofile-instr-generate main.o -o mainWithFlags
```

Please take a look at my example and try for yourself before closing.

**Comment by boomanaiden154** [comment]
> I don't know the details of instrumentation, but -fprofile-instr-generate does something in the command

Do you get an error if you don't include it in the linker invocation through the clang driver?

**Comment by cf-coheretech** [comment]
> > I don't know the details of instrumentation, but -fprofile-instr-generate does something in the command
> 
> Do you get an error if you don't include it in the linker invocation through the clang driver?

I don't get an error either way. 

With either of these linker invocations the profraw file is created
```
clang++ -fprofile-instr-generate main.o -o mainWithFlags
# or
clang++ -fprofile-instr-generate -fno-profile-instr-generate main.o -o mainWithFlags
```

With this linker invocation the profraw file is NOT created
```
clang++  main.o -o mainWithFlags
```
