### ISSUE TITLE
[Clang] v14 Misinterpretation of binary operators

### ISSUE THREAD

**Issue by NahuFigueroa97** [llvm/llvm-project#118618]
There is a problem in clang-format 14 on how to interpret binary operators. It is not differentiating them with the angle brackets used in the templates. On the contrary, clang-format-18 interprets it correctly. Both using the same .clang-format.yml. The BreakBeforeBinaryOperators is in nonassigment and AlignOperands is in true. The length of the line is 120.

clang-format-18
```
    if constexpr (std::is_same_v<std::remove_cv_t<std::remove_reference_t<T>>, std::string_view>
                  || std::is_same_v<T, std::string>)

```

clang-format-14

```
    if constexpr (std::is_same_v<std::remove_cv_t<std::remove_reference_t<T>>,
                                 std::string_view> || std::is_same_v<T, std::string>)

```

Please confirm if this is a bug in version 14

**Comment by EugeneZelenko** [comment]
Could you please try 19 or `main` branch? Only most recent release (currently 19) is maintained.
