### ISSUE TITLE
Request Commit Access For MrSidims

### ISSUE THREAD

**Issue by MrSidims** [llvm/llvm-project#118667]
I’m working in Intel for SYCL compiler project and I'm co-maintainer of https://github.com/KhronosGroup/SPIRV-LLVM-Translator and currently started contributing to SPIR-V backend part of LLVM. I need commit access to merge patches for myself and for other developers in SPIR-V backend.

Current list of [my PRs in SPIR-V backend](https://github.com/llvm/llvm-project/pulls/MrSidims) is short, but I have previous record contributing to LLVM (mostly in clang) during phabricator era, for example https://reviews.llvm.org/D82174, nickname there was sidorovd.

**Comment by tstellar** [comment]
### Activity Summary:
* [2 Pull Requests](https://github.com/llvm/llvm-project/pulls/MrSidims) (2 merged)
* Top 3 Committers: @VyacheslavLevytskyy (2)
* Top 3 Reviewers: @VyacheslavLevytskyy (1)

**Comment by VyacheslavLevytskyy** [comment]
@tstellar I'm not sure what is the new procedure for this. Should I confirm or approve anything here?

**Comment by tstellar** [comment]
@VyacheslavLevytskyy There is nothing for you to do, you were just mentioned for awareness since you have been committing @MrSidims PRs.  One of the admins will handle the request.

**Comment by tstellar** [comment]
@MrSidims, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.

**Comment by MrSidims** [comment]
@tstellar thanks!
