### ISSUE TITLE
Suppress new MSVC warning C5278 "adding a specialization for 'type trait' has undefined behavior"

### ISSUE THREAD

**Issue by CaseyCarter** [llvm/llvm-project#118727]
MSVC is adding a new warning that will be emitted for program-defined partial and explicit specializations of the Standard Library type traits defined in [[type.traits]](https://eel.is/c++draft/type.traits) per [[meta.rqmts]/4](https://eel.is/c++draft/meta.rqmts#4). MSVC implements many of the type traits directly in the compiler, so the manifestation of the undefined behavior is generally that we ignore these specializations. We're hoping the warning will reduce confusion for users who don't know these specializations are forbidden, and emitting a warning seems less hostile than just silently ignoring the specializations.

It's extremely likely that a future release of MSVC with this warning will diagnose specializations in libc++ if the warning isn't suppressed e.g. with `#pragma warning(disable : 5278)`. I'm not certain how much you folks support MSVC, but we thought you'd like a heads up.

**Comment by frederick-vs-ja** [comment]
Recently #101469 added similar ability to Clang. #118167 is currently checking implementation of type traits in libc++. I _guess_ almost no type traits need such suppression.

**Comment by philnik777** [comment]
We don't support MSVC, so this won't affect us (except if we're incorrectly specializing any traits in the tests of course). Thanks for the info though.
