### ISSUE TITLE
Request Commit Access For VladiKrapp-Arm

### ISSUE THREAD

**Issue by VladiKrapp-Arm** [llvm/llvm-project#118998]
### Why Are you requesting commit access 
I am working at Arm, and have multiple patches I need to add, primarily in the middle end and in the Arm backend. 
I have already made the following: 
https://github.com/llvm/llvm-project/pull/112333
https://github.com/llvm/llvm-project/pull/112540
https://github.com/llvm/llvm-project/pull/118692

I'm working on multiple additional patches, and would like to not have to bother others to press the button after a PR has been reviewed and approved. 

Cheers!

Vladi

**Comment by tstellar** [comment]
### Activity Summary:
* [4 Pull Requests](https://github.com/llvm/llvm-project/pulls/VladiKrapp-Arm) (3 merged)
* Top 3 Committers: @jthackray (2), @stuij (1)
* Top 3 Reviewers: @davemgreen (1), @Stylie777 (1)

**Comment by tstellar** [comment]
@VladiKrapp-Arm, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.
