### ISSUE TITLE
[Flang] Crash when a function result is used for `merge` argument

### ISSUE THREAD

**Issue by kawashima-fj** [llvm/llvm-project#118922]
@jeanPerier #118070 has a regression.

A binary produced by Flang crashes.

Source program:

```fortran
program main
  implicit none
  type :: ty
    integer, allocatable :: val(:)
  end type
  type(ty) :: a1(1), a2(1), a3(1)
  allocate(a1(1)%val(1), source=1)
  allocate(a2(1)%val(1), source=2)
  allocate(a3(1)%val(1), source=3)
  a3 = merge(f(a1), a2, .true.)
  print *, a3(1)%val(1)
contains
  function f(d) result(r)
    implicit none
    type(ty), intent(in) :: d(:)
    type(ty) :: r(size(d))
    r = d
  end function
end
```

Run (on AArch64):

```console
$ flang test.f90
$ ./a.out
Segmentation fault (core dumped)
```

This is detected by [Fujitsu Compiler Test Suite run on Linaro CI](https://linaro.atlassian.net/browse/LLVM-1459). The soruce program above is a simplified version of [Fujitsu/Fortran/0173/Fujitsu-Fortran-0173_0248.test](https://github.com/fujitsu/compiler-test-suite/blob/main/Fortran/0173/0173_0248.f90). I confirmed the commit cd7e65398fbbd9642573013800dc3ae1e7307f82 (#118070) and eb49788bd935b2335f73fd2a4124c82e683bd9b0 (the latest latest `main` branch) have this problem but the commit before cd7e65398fbbd9642573013800dc3ae1e7307f82 does not have the problem.

This may be related to #113843, though #113843 is reported before #118070.

**Comment by jeanPerier** [comment]
Thanks for the bug report, I could reproduced and reduced it to an issue in hlfir.elemental lowering, working on a fix.

**Comment by jeanPerier** [comment]
https://github.com/llvm/llvm-project/pull/119219

**Comment by jeanPerier** [comment]
Fix has been merged and the reproducer works for me now.

**Comment by kawashima-fj** [comment]
Thanks for the fix.

According to [the result of Fujitsu Compiler Test Suite run on Linaro CI](https://linaro.atlassian.net/browse/LLVM-1459), another kind of regression by #118070 seems to exist. I'll check the tests and open another issue if it is a real regression.
