### ISSUE TITLE
[flang] Allow constant expressions in DATA statements

### ISSUE THREAD

**Issue by psteinfeld** [llvm/llvm-project#119005]
In most contexts that allow constants, Fortran allows a constant expression.  But in `DATA` statements, based on my reading of the standard, only a constant (either a literal or a named constant) is allowed.

Here's a program that illustrates that:
```
program main
  character*2 :: ary4
  data ary4/"abcdef"(3:4)/
end program main
```
When I compile this with `flang`, I get error messages:
```
error: Could not parse const.f90
./const.f90:3:21: error: expected '/'
    data ary4/"abcdef"(3:4)/
                      ^
./const.f90:3:3: in the context: DATA statement
    data ary4/"abcdef"(3:4)/
    ^
./const.f90:3:3: in the context: declaration construct
    data ary4/"abcdef"(3:4)/
    ^
./const.f90:2:3: in the context: specification part
    character*2 :: ary4
    ^
./const.f90:1:1: in the context: main program
  program main
  ^
```
The only other compilers I could find that don't compile this program are the Intel compilers -- ifort and ifx.  GNU, NAG, nvfortran, and IBM all compile it without error.

**Comment by klausler** [comment]
Obviously we can't support arbitrary constant expressions in `DATA` statements, since division and character concatenation would be syntactic problems.  Maybe we should support a named constant designator, though.

**Comment by klausler** [comment]
The standard allows a `scalar-constant-subobject` as a `data-stmt-constant`, and the parser looks for one, so I'll fix whatever's going wrong with this test case.
