### ISSUE TITLE
Trivial math builtins not inlined

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11916]
|  |  |
| --- | --- |
| Bugzilla Link | [11544](https://llvm.org/bz11544) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@lattner,@seanm |

## Extended Description 
When compiling for -march=armv7-a, Apple Clang 3.0 from Xcode 4.2 fails to inline math builtins, both relatively complex ones like __builtin_fmodf as well as trivial (single instruction) ones like __builtin_lrintf.
-ffast-math -D__NO_MATH_INLINES do not help...

__builtin_lrintf is most important to me as I need fast scalar float to int 
rounding and there is no intrisic for that AFAIK (and the inline ARM assembler is broken in Apple's Clang 3.0).

**Comment by philnik777** [comment]
This has been fixed in Clang 11: https://godbolt.org/z/P8dcWaYn8
