### ISSUE TITLE
[Clang-CL][DXC] Should we expose `-fdiagnostics-color=` to clang-cl / clang-dxc?

### ISSUE THREAD

**Issue by Maetveis** [llvm/llvm-project#119184]
Apologies if the `HLSL` tag is not appropriate I did not find one for the `dxc` driver.

Recently while exposing more options to the Fortran `flang` driver, some options were accidentally exposed to `clang-cl` / `clang-dxc` too. Among them is `-fdiagnostics-color=`. Note that `-fcolor-diagnostics` and `-fno-color-diagnostics` are already allowed for both.
`-fdiagnostics-color=` allows one additional value `auto` which roughly means only use colors if the output is a terminal. This is also the default value of nothing is specified therefore, `-fdiagnostics-color=` is mainly useful to override an earlier `-f(no)?-color-diagnostics` / `-fdiagnostics-color=` option.

In #118640 I am looking to disable to flag again, mostly to keep the PR a clean fix and not introduce new features, but
personally I don't see a reason why this option shouldn't be exposed to `clang-cl` and `clang-dxc`. If we do we should definitely add test however.

**Comment by zmodem** [comment]
Supporting `-fdiagnostics-color=` in clang-cl sounds good to me. You can test the flag with the existing ones in clang/test/Driver/cl-options.c

**Comment by Maetveis** [comment]
So what needs to be done is enabling `CLOption` and `DXCOption` for `Visibility` in [clang/include/clang/Driver/Options.td:1993](https://github.com/llvm/llvm-project/blob/31239540b09bf5315b3a795160cf47d4c4edcd4e/clang/include/clang/Driver/Options.td#L1992-L1993), and adding a test for clang-cl at clang/test/Driver/cl-options.c and finding where to add a test for dxc. 

Probably somewhere there is already testing for `-fdiagnostics-color` and `-fno-diagnostics-color` for `clang-dxc` adding `-fdiagnostics-color=` tests there would make sense.

**Comment by whiteio** [comment]
Hey! I'd like to work on this, could it be assigned to me please?
