### ISSUE TITLE
-slp-max-vf doesn't affect horizontal reductions

### ISSUE THREAD

**Issue by lukel97** [llvm/llvm-project#119189]
E.g. for the example below:

```llvm
define i32 @f(ptr %p) {
  %p0 = getelementptr i32, ptr %p, i32 0
  %p1 = getelementptr i32, ptr %p, i32 1
  %p2 = getelementptr i32, ptr %p, i32 2
  %p3 = getelementptr i32, ptr %p, i32 3
  %x0 = load i32, ptr %p0
  %x1 = load i32, ptr %p1
  %x2 = load i32, ptr %p2
  %x3 = load i32, ptr %p3
  %y0 = add i32 %x0, %x1
  %y1 = add i32 %y0, %x2
  %y2 = add i32 %y1, %x3
  ret i32 %y2
}
```

`opt -passes=slp-vectorizer -slp-max-vf=2` will still vectorize it to a vector of 4 elements:

```llvm
define i32 @f(ptr %p) {
  %p0 = getelementptr i32, ptr %p, i32 0
  %1 = load <4 x i32>, ptr %p0, align 4
  %2 = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> %1)
  ret i32 %2
}
```

I'm not sure if this is by design or not. My intuition is that the VF for a horizontal reduction would be the number of root scalars.

**Comment by alexey-bataev** [comment]
> E.g. for the example below:
> 
> define i32 @f(ptr %p) {
>   %p0 = getelementptr i32, ptr %p, i32 0
>   %p1 = getelementptr i32, ptr %p, i32 1
>   %p2 = getelementptr i32, ptr %p, i32 2
>   %p3 = getelementptr i32, ptr %p, i32 3
>   %x0 = load i32, ptr %p0
>   %x1 = load i32, ptr %p1
>   %x2 = load i32, ptr %p2
>   %x3 = load i32, ptr %p3
>   %y0 = add i32 %x0, %x1
>   %y1 = add i32 %y0, %x2
>   %y2 = add i32 %y1, %x3
>   ret i32 %y2
> }
> `opt -passes=slp-vectorizer -slp-max-vf=2` will still vectorize it to a vector of 4 elements:
> 
> define i32 @f(ptr %p) {
>   %p0 = getelementptr i32, ptr %p, i32 0
>   %1 = load <4 x i32>, ptr %p0, align 4
>   %2 = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> %1)
>   ret i32 %2
> }
> I'm not sure if this is by design or not. My intuition is that the VF for a horizontal reduction would be the number of root scalars.

Most of these options are intended for debugging and were never guaranteed to work in all cases. IIRC, this option was never used for reductions, but you can support it if you think it may help to debug some corner cases

**Comment by lukel97** [comment]
That's fair, I don't have an urgent need for it. However I'm also noticing now that `TargetTransformInfo::getMaximumVF` doesn't seem to affect it either. Do we want to take that into account?

**Comment by alexey-bataev** [comment]
> That's fair, I don't have an urgent need for it. However I'm also noticing now that `TargetTransformInfo::getMaximumVF` doesn't seem to affect it either. Do we want to take that into account?

Generally speaking, no. SLP vectorizer tends to generate large vectors, relying completely on the backend in splitting them properly

**Comment by lukel97** [comment]
> Generally speaking, no. SLP vectorizer tends to generate large vectors, relying completely on the backend in splitting them properly

Ok, that makes sense. Thanks for the clarification
