### ISSUE TITLE
[RISCV] error in generating assembly for compressed instruction

### ISSUE THREAD

**Issue by ahmedshakill** [llvm/llvm-project#119182]
` int a=20, b=10; `
   ` asm volatile ("c.sub %0, %1":
        "=r"(a):
        "r"(b)
    );    `

Clang generates the below assembly sequence for the above code

`li      a0, 20 `
`sw      a0, -20(s0) `
`li      a0, 10`
`sw      a0, -24(s0) `
`lw      a0, -24(s0) `
`sub     a0, a0, a0`
`sw      a0, -20(s0) `

which is subtraction of `b` from `b` ie ` (b-b) ` whereas subtraction of `b` from `a`  ie `(a-b) ` is expected 

see it on [godbolt](https://godbolt.org/z/z8xdPdaKW)

### expected assembly

`li      a0, 20 `
`sw      a0, -20(s0) `
`li      a0, 10`
`sw      a0, -24(s0) `
`lw      a0, -24(s0) `
`lw      a1, -20(s0) `
`sub     a1, a1, a0`
`sw      a0, -20(s0) `

**Comment by topperc** [comment]
You need to use +r instead of =r. =r means output only.

**Comment by ahmedshakill** [comment]
> You need to use +r instead of =r. =r means output only. +r is input and output

Thanks @topperc.

**Comment by lenary** [comment]
> > You need to use +r instead of =r. =r means output only. +r is input and output
> 
> Thanks [@topperc](https://github.com/topperc). Are these documented somewhere ?

Not by Clang, but GCC does, annoyingly split over a few different pages, start here: https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html (the `+` and `=` are "Constraint Modifiers")
