### ISSUE TITLE
Support the option -fextended-identifiers

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#11910]
|  |  |
| --- | --- |
| Bugzilla Link | [11538](https://llvm.org/bz11538) |
| Version | unspecified |
| OS | All |
| CC | @belkadan,@zygoloid |

## Extended Description 
It would be nice if you could support the option -fextended-identifiers like in gcc/g++:

       -fextended-identifiers
           Accept universal character names in identifiers.  This option is
           experimental; in a future version of GCC, it will be enabled by
           default for C99 and C++.

This wish has been reported on:
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=647636

**Comment by cor3ntin** [comment]
Clang supports UAX identifiers in C++ and C2X mode, the flag is supported (and ignored), enabled by default in C99+ by gcc. 
This issue no longer seems relevant.
