### ISSUE TITLE
Request Commit Access For knickish

### ISSUE THREAD

**Issue by knickish** [llvm/llvm-project#119142]
### Why Are you requesting commit access ?

I've been working on the M68k backend to fix the relevant rust target, and have landed a couple PRs ([here](https://github.com/llvm/llvm-project/pull/114714) and [here](https://github.com/llvm/llvm-project/pull/108982)) with [another one approved](https://github.com/llvm/llvm-project/pull/115523), it would be nice to be able to hit the merge button myself

**Comment by tstellar** [comment]
### Activity Summary:
* [6 Pull Requests](https://github.com/llvm/llvm-project/pulls/knickish) (2 merged)
* Top 3 Committers: @mshockwave (1), @0x59616e (1)
* Top 3 Reviewers: @mshockwave (2), @DianQK (1)

**Comment by tstellar** [comment]
@knickish, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.
