### ISSUE TITLE
no diagnostic for ill-formed call to function on a member of the current instantiation

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#11920]
|  |  |
| --- | --- |
| Bugzilla Link | [11548](https://llvm.org/bz11548) |
| Version | unspecified |
| OS | Linux |
| CC | @DougGregor,@hubert-reinterpretcast |

## Extended Description 
This bit me recently: see r146366. g++ diagnoses the following, but clang doesn't notice anything wrong with it:
```c++
struct A {
  void f(int);
};

template<typename T> struct S {
  A a;
  void g() {
    a.f();
  }
};
```

**Comment by philnik777** [comment]
Fixed in Clang 10: https://godbolt.org/z/KoPWv7xPn
