### ISSUE TITLE
Request Commit Access for jerryyin

### ISSUE THREAD

**Issue by jerryyin** [llvm/llvm-project#119237]
Why are you requesting commit access ?

I’m compiler engineer from AMD, (just started) working on MLIR IREE project. I had commit/write permission before, but get downgraded to triage access earlier this year. I'm planning to start to actively contributing to MLIR and LLVM again. With commit access, I'm hopping to be able to merge my own PR when I get enough approval from reviewers. In the past, I had fair amount of PRs in a downstream fork (https://github.com/ROCm/rocMLIR/pulls?q=is%3Apr+author%3Ajerryyin+is%3Aclosed)  but didn't end to be the author in upstreaming them. 

My past PRs:
 - https://reviews.llvm.org/D80233
 - https://reviews.llvm.org/D81663
 - https://reviews.llvm.org/D87773
 - https://reviews.llvm.org/D88038

Commits: https://github.com/llvm/llvm-project/commits?author=jerryyin

Current PR: https://github.com/llvm/llvm-project/pull/117340

Thanks for your time and consideration.

**Comment by tstellar** [comment]
### Activity Summary:
* [1 Pull Requests](https://github.com/llvm/llvm-project/pulls/jerryyin) (1 merged)
* Top 3 Committers: @nirvedhmeshram (1)
* Top 3 Reviewers: @Max191 (1), @banach-space (1)

**Comment by tstellar** [comment]
@jerryyin, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.
