### ISSUE TITLE
clang segfaults when compiling mesa-7.11.2 with debug symbols

### ISSUE THREAD

**Issue by alistra** [llvm/llvm-project#11925]
|  |  |
| --- | --- |
| Bugzilla Link | [11553](https://llvm.org/bz11553) |
| Version | 3.0 |
| OS | Linux |
| Attachments | [preprocessed source file](https://user-images.githubusercontent.com/92601900/143744389-52c17d35-46dd-4810-beaf-9ea72b04679f.gz), [preprocessed source file 2](https://user-images.githubusercontent.com/92601900/143744390-1876fbcf-7203-4290-a669-4e756e9c0489.gz), [emerge build log](https://user-images.githubusercontent.com/92601900/143744391-9389f01f-27db-4dca-b5f4-5ba404ce4867.gz) |
| CC | @efriedma-quic,@zygoloid |

## Extended Description 

tried installing mesa by:

FEATURES=splitdebug CC=clang CXX=clang++ emerge =mesa-7.11.2

the installation crashes with clang segfaulting

attaching 2 preprocessed files that diagnostic messages suggested and the build log

**Comment by Endilll** [comment]
Can't reproduce with either Clang 3.0 and 16
https://godbolt.org/z/Te5cxv79z
