### ISSUE TITLE
Request Commit Access For fahadnayyar

### ISSUE THREAD

**Issue by fahadnayyar** [llvm/llvm-project#119240]
I work in the clang compiler team at Apple. 
I have made some commits in the upstream llvm-project repository in the past via Phabricator. I plan to make some more patches to the clang frontend in next few months. So I wanted to get commit access to the main branch of llvm-project via GitHub so that I can submit PRs, get approvals and merge my changes into the main branch of LLVM.

**Comment by fahadnayyar** [comment]
[tstellar](https://github.com/tstellar) Can you please look into this?

**Comment by fahadnayyar** [comment]
My current open PR:
https://github.com/llvm/llvm-project/pull/118938

Some of my past commits in llvm-project from last year:
https://github.com/llvm/llvm-project/commit/4c37671a7c946ac246b52fa44a6a649b89d6310b
https://github.com/llvm/llvm-project/commit/5e5d901feb3c4522c2b4d748bd52fda18abde821
https://github.com/llvm/llvm-project/commit/226798f3aa2f8467a29d909f0b18dbc4dfb398f7

**Comment by tstellar** [comment]
### Activity Summary:
* [1 Pull Requests](https://github.com/llvm/llvm-project/pulls/fahadnayyar) (1 merged)
* Top 3 Committers: @ahatanak (1)
* Top 3 Reviewers: @Xazax-hun (1), @egorzhdan (1), @compnerd (1)

**Comment by tstellar** [comment]
@fahadnayyar, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.
