### ISSUE TITLE
Request Commit Access For guy-david

### ISSUE THREAD

**Issue by guy-david** [llvm/llvm-project#119375]
I've recently started a new role as a compiler engineer at Apple, humbly requesting commit access.
Previously, I've mostly worked downstream and my sole contribution is this PR:
[[mlir][llvm] Implement ConstantLike for ZeroOp, UndefOp, PoisonOp](https://github.com/llvm/llvm-project/pull/93690)
Thank you.

**Comment by tstellar** [comment]
### Activity Summary:
* [2 Pull Requests](https://github.com/llvm/llvm-project/pulls/guy-david) (1 merged)
* Top 3 Committers: @gysit (1)
* Top 3 Reviewers: @zero9178 (1)

**Comment by tstellar** [comment]
@guy-david, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.
