### ISSUE TITLE
[ninja] Ninja command to build closes the terminal unexpectedly

### ISSUE THREAD

**Issue by sm0gskr3am** [llvm/llvm-project#119464]
The following command below, after performing cmake, is unexpectedly closing the terminal without any type of error or log:

`ninja -C build check-llvm`

Unfortunately I tried looking for log messages in journalctl, but without success either.
Im using the latest commit of LLVM: 

`git clone --depth 1 https://github.com/llvm/llvm-project.git
`
Does anyone have any idea what it could be?

OBS: The binaries are working properly.

**Comment by thesamesam** [comment]
Are you sure it didn't OOM and the terminal got killed?

**Comment by sm0gskr3am** [comment]
Resolved using the "Unix Makefiles" option for compile.
