### ISSUE TITLE
Request Commit Access For lizhengxing

### ISSUE THREAD

**Issue by lizhengxing** [llvm/llvm-project#119466]
### Why Are you requesting commit access ?
I'm working on HLSL in Clang/LLVM. My colleagues helped me merged 3 PRs. It would be great if I have the commit access.

**Comment by tstellar** [comment]
### Activity Summary:
* [5 Pull Requests](https://github.com/llvm/llvm-project/pulls/lizhengxing) (3 merged)
* Top 3 Committers: @spall (1), @tex3d (1), @farzonl (1)
* Top 3 Reviewers: @llvm-beanz (2), @inbelic (1), @tex3d (1)

**Comment by tstellar** [comment]
@lizhengxing, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.

**Comment by lizhengxing** [comment]
@tstellar Awesome, thank you for the help.
