### ISSUE TITLE
Clang :: Format/docs_updated.test failed after building with MSVC

### ISSUE THREAD

**Issue by NEIL-smtg** [llvm/llvm-project#119517]
I work on Microsoft Visual C++ testing, where we regularly build popular open-source projects, including yours, with development builds of our compiler and libraries to detect and prevent shipping regressions that would affect you. This also allows us to provide advance notice of breaking changes, which is the case here.

Recently, while running the tests for LLVM, the `Clang :: Format/docs_updated.test` test failed. Please refer to the attached build log for more details:
[docs_updated.test.log](https://github.com/user-attachments/files/18090961/docs_updated.test.log)

Repro steps:

1. Open x64 native tools command prompt for VS2022
2. git clone https://github.com/llvm/llvm-project.git
3. mkdir llvm\llvm-project\build_amd64 & cd llvm\llvm-project\build_amd64
4. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DLLVM_ENABLE_PROJECTS="clang" ..\llvm 2>&1
5. msbuild /m /p:Platform=x64 /p:Configuration=RelWithDebInfo /p:PreferredToolArchitecture=x64 LLVM.sln /t:Rebuild 2>&1
6. python.exe ../llvm/utils/lit/lit.py -v --no-progress-bar --param build_mode=RelWithDebInfo --param clang_site_config=./tools/clang/test/lit.site.cfg ./tools/clang/test -j 16 --filter Format/docs_updated.test

**Comment by boomanaiden154** [comment]
It's hard to see what exactly the differences between the files are. Are the line endings different?

If so, we might just want to disable this test on windows. Running on Linux would give us plenty of coverage on postcommit/precommit testing, and wouldn't run into any line endings issues.

**Comment by owenca** [comment]
> Recently, while running the tests for LLVM, the `Clang :: Format/docs_updated.test` test failed. Please refer to the attached build log for more details: [docs_updated.test.log](https://github.com/user-attachments/files/18090961/docs_updated.test.log)

AFAICT there's no difference as shown in the log file. Did you have `core.autocrlf` set to `true` in git?

**Comment by NEIL-smtg** [comment]
> AFAICT there's no difference as shown in the log file. Did you have `core.autocrlf` set to `true` in git?

Yes, I did have `core.autocrlf` set to `true`. When I ran `diff` with the `--strip-trailing-cr` option, it normalized the line endings and removed the differences.

**Comment by owenca** [comment]
I suppose we can add `--strip-trailing-cr` to the test.
