### ISSUE TITLE
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)

### ISSUE THREAD

**Issue by rsielken** [llvm/llvm-project#119581]
I updated EMSDK/Emscripten from 3.1.68 to 3.1.73 (which included an underlying LLVM update) and tried to rebuild my whole project.  In the middle of building, I got an LLVM error and was provided instructions from opening a bug report here.

clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
clang version 20.0.0git (https:/github.com/llvm/llvm-project 1d810ece2b2c8fab77720493864257f0ea3336a9)

I have the requested files (there was no .crash file), but they contain pieces of my source code, so I will attach them here, but you'll need to reach out to me separately to get the password to unlock the zip file.[FilesForLLVM.zip](https://github.com/user-attachments/files/18099045/FilesForLLVM.zip)

**Comment by shafik** [comment]
The reproducer needs to be publically accessible please provide something that is available to everyone.

**Comment by Endilll** [comment]
Note that a very plausible workflow is that we extract test cases out of your source, and include them in our public repo. So you shouldn't share with us parts of your code you don't want to be public. It's not unheard of that proprietary code is submitted in bug reports in redacted yet well-formed state.

**Comment by rsielken** [comment]
We have tried to create a test case that recreates the problem without exposing our code and we have been unable to do so.  By the time we strip it down, I can't recreate the LLVM error.

I went back to different LLVM levels (inside of EMSDK) and this error happens when we build the whole project the first time (after a clean).  If you run the build again from that middle point, it works.  So, while it has been going on for a long time (and I finally decided to open this issue with what I had), we just build twice and it works, so we have been and will continue to just live with it.  I just thought you'd like to know it is there and possibly fix it, but I can't give you a public version that recreates the issue.

Therefore, I think this should just be closed.

**Comment by DConmy** [comment]
We did verify that this is not unique to the new EMSDK.
We see this issue in 2 files, and have narrowed it down to:
1) On the Mac, it fails with optimization (-O1, -O2 or -O3) and does not fail with no optimization -O0
2) On Linux, it does not fail, even with optimization.
