### ISSUE TITLE
Backport `.init_array` WebAssembly fixes to release/19.x

### ISSUE THREAD

**Issue by georgestagg** [llvm/llvm-project#119528]
I'd like to backport #111008 & #119127, implementing fixes for when there are multiple `.init_array` sections in WebAssembly.

/cherry-pick ac5dd455caaf286625f61b604291f2eaed9702f0 ed91843d435d0cd2c39ebb1a50f2907c621f07ed

**Comment by nikic** [comment]
/cherry-pick ac5dd455caaf286625f61b604291f2eaed9702f0 ed91843d435d0cd2c39ebb1a50f2907c621f07ed
