### ISSUE TITLE
[X86][Float128][compiler-rt]  float128 test case core dump

### ISSUE THREAD

**Issue by zhangtianhao6** [llvm/llvm-project#119521]
test case
```
#include <fenv.h>
#include <stdlib.h>

int
main (void)
{
  volatile __float128 a = 0x0.fffffffffffffffp-1022q, b = 0x0.fffffffffffff8p-1022q;
  volatile double r;
  r = (double) a;
  if (fetestexcept (FE_UNDERFLOW))
    abort ();
  if (r != 0x1p-1022)
    abort ();
  r = (double) b;
  if (!fetestexcept (FE_UNDERFLOW))
    abort ();
  if (r != 0x1p-1022)
    abort ();
  exit (0);
}

```

use compiler-rt error: -rtlib=compiler-rt
https://godbolt.org/z/scj8M4WKW

use libgcc ok:
https://godbolt.org/z/YMMjsf3az

 **Is compiler-rt bug?**

**Comment by phoebewang** [comment]
The current compiler-rt implementation does not support FP exception raising, nor rouding control from fenv functions. I think it should be taken as a missing feature, but I don't know any plan about it.
