### ISSUE TITLE
[BOLT][MCInst][X86]

### ISSUE THREAD

**Issue by wuwen03** [llvm/llvm-project#119555]
I want to use BOLT to implement a toy auto-vectorization on binary-code level so I have to create some new MCInst. However, current BOLT's X86MCPlusBuidler doesn't have methods to create a simd instruction. When i want to construct a MCInst  by myself, I can't get any information about what the oprands mean in a certain instruction. How can I get the 'grammar' rule about this?

**Comment by maksfb** [comment]
You can take a look at how LLVM backend constructs instructions of the interest.

Another approach is to use `llvm-tblgen` and run it on `llvm/lib/Target/X86/X86.td`. The output will provide detailed info for every X86 MC opcode.

**Comment by wuwen03** [comment]
> You can take a look at how LLVM backend constructs instructions of the interest.
> 
> Another approach is to use `llvm-tblgen` and run it on `llvm/lib/Target/X86/X86.td`. The output will provide detailed info for every X86 MC opcode.

Thank you! I think this is exactly what I need. Since there are some inlcude problem, I use the command `llvm-tblgen /path/to/llvm-project/llvm/lib/Target/X86/X86.td -I /path/to/llvm-project/llvm/include -I /path/to/llvm-project/llvm/lib/Target/X86` to get the result.
I close the issue now
