### ISSUE TITLE
llvm Codegen crashes when debugging and optimization enabled

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#11964]
|  |  |
| --- | --- |
| Bugzilla Link | [11592](https://llvm.org/bz11592) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced test case for sparc](https://user-images.githubusercontent.com/60944935/143744421-1cb0ea29-c401-431e-a076-b0aee66b6d18.gz), [C code when compiled with -O1 -g causes xcore mblaze hexagon sparc to fail](https://user-images.githubusercontent.com/60944935/143744422-f1119a29-c506-4d8f-869c-330d54dff8c4.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

The attached files cause the following problem when compiling for Sparc: 
 
llc: /home/jpbonn/Documents/clang/llvm/include/llvm/CodeGen/MachineFrameInfo.h:378: int64_t llvm::MachineFrameInfo::getObjectOffset(int) const: Assertion `unsigned(ObjectIdx+NumFixedObjects) < Objects.size() && "Invalid Object Idx!"' failed.

The reduced test case is attached.

The attached .i file also seem to causes  problems for sparcv9, xcore, hexagon and mblaze when compiled with clang. I'm not sure if they are all related.

**Comment by arsenm** [comment]
Can't reproduce on main
