### ISSUE TITLE
[LLVM][SLSR] Add a debug counter

### ISSUE THREAD

**Issue by justinfargnoli** [llvm/llvm-project#119770]
Add a debug counter to selectively enable or disable SLSR transformations. The debug counter should wrap `SLSR`'s invocation of [rewriteCandidateWithBasis()](https://github.com/llvm/llvm-project/blob/bd40421ad9ec5ecc164f8208caf3ba5657977e17/llvm/lib/Transforms/Scalar/StraightLineStrengthReduce.cpp#L693C7-L693C32).

---

See [DAGCombiner.cpp](https://github.com/llvm/llvm-project/blob/bd40421ad9ec5ecc164f8208caf3ba5657977e17/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp#L2025-L2026) for an example use case for a debug counter:
```
SDValue DAGCombiner::combine(SDNode *N) {
  if (!DebugCounter::shouldExecute(DAGCombineCounter))
      return SDValue();
  ...
```

See 7a8dc3dafa85a1bbbb9458f2162ac5d61a9dc91a for an example of a patch that adds support for a debug counter. 

---

Don't feel the need to ask permission to work on this. Just give it a try! 

CC @akshayrdeodhar

**Comment by GrumpyPigSkin** [comment]
Hi @justinfargnoli ,
I thought this would be an easy first issue, so I have added the debug counter to the file. My issue is how to write a test to ensure it's doing its job. 
I had a look at Straight Line Strength Reduction in llvm and it is not immediately obvious to me how the output should be affected by using the counter, so any help would be great :) (or did you just want the functionality added with no test?)

**Comment by ParkHanbum** [comment]
@GrumpyPigSkin he left a commit link : https://github.com/llvm/llvm-project/commit/7a8dc3dafa85a1bbbb9458f2162ac5d61a9dc91a
maybe you can refer it.

**Comment by justinfargnoli** [comment]
I'd recommend checking out the current state of the [DCE debug counter test](https://github.com/llvm/llvm-project/blob/main/llvm/test/Other/debugcounter-dce.ll) to understand what kind of test we want to write.

---

Perhaps you could base the test on [`stride_is_2s`](https://github.com/llvm/llvm-project/blob/2135babe28b038c99d77f15c39b3f7e498fc6694/llvm/test/Transforms/StraightLineStrengthReduce/slsr-add.ll#L23-L44). You could check that only the first transformation occurs and the others are skipped.

**Comment by GrumpyPigSkin** [comment]
Aha okay thanks I’ll have a look. If you want to assign it to me that’d be great, I’m sure I can figure it out with the example's :)

**Comment by justinfargnoli** [comment]
Also, be sure to check out [Adding debug counters to aid in debugging your code](https://llvm.org/docs/ProgrammersManual.html#adding-debug-counters-to-aid-in-debugging-your-code).
