### ISSUE TITLE
Request Commit Access For alexrp

### ISSUE THREAD

**Issue by alexrp** [llvm/llvm-project#119737]
### Why Are you requesting commit access ?

I'm a core team member on the [Zig](https://github.com/ziglang/zig) project. I did most of the work for the LLVM 19 upgrade recently, and I'm likely also going to be driving future LLVM upgrades. I've also been doing a lot of general work on our LLVM backend as well. This means I'll be regularly interacting with and contributing to the LLVM project going forward. It would be nice to be able to commit my patches after review & approval without needing to bother other people to do it for me. 🙂

I've followed the LLVM project for many years prior to actually contributing, so I'm already familiar with the general culture here, and I've also familiarized myself with the developer policy.

**Comment by tstellar** [comment]
### Activity Summary:
* [17 Pull Requests](https://github.com/llvm/llvm-project/pulls/alexrp) (11 merged)
* Top 3 Committers: @uweigand (3), @wzssyqa (2), @arsenm (2)
* Top 3 Reviewers: @arsenm (3), @arichardson (2), @topperc (1)

**Comment by tstellar** [comment]
@alexrp, you have been granted commit access.  Please review the project's [code review policy](https://llvm.org/docs/CodeReview.html) before submitting a patch.
