### ISSUE TITLE
[C++][Modules] `-fmodule-output` does nothing

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#119929]
Given some module in file a.cpp

```
export module b;
```

Compiling it with

`clang++ -std=c++20 -x c++-module -fmodule-output=c.pcm --precompile a.cpp`

I would expect to produce a file `c.pcm`. Instead it produces a file `a.pcm`. Am I misunderstanding the purpose of this option? The documentation states

> `-fmodule-output=<arg>`
> Save intermediate module file results when compiling a standard C++ module unit.

**Comment by davidstone** [comment]
It looks like if I remove `--precompile` (and add `-c`), it behaves as I expected. So if I have `--precompile`, I need to use `-o` to determine the name of the generated pcm file, but if I don't, then I use `-o` for the `.o` file and `-fmodule-output=` to determine the .pcm file name. This feels surprising to me -- I would expect `-o` to always apply to the `.o` file name (if it would be generated) and `-fmodule-file=` to always apply to the generated `.pcm`.

**Comment by ChuanqiXu9** [comment]
Yes, `-fmodule-output` tend to be working with `-c` options. According to the document you cide:

> -fmodule-output=<arg>
> Save intermediate module file results when compiling a standard C++ module unit.

If we're `--precompile`, the `.pcm` file is not  intermediate module file. 

So I'd like to close this one as invalid.
