### ISSUE TITLE
Clang compiles an invalid program normally

### ISSUE THREAD

**Issue by ZY546** [llvm/llvm-project#119953]
https://godbolt.org/z/jETK87bq7
```c
int func_2();  //note: previous declaration of 'func_2' with type 'int(void)'
int func_1() { return func_2();}
int func_2(int a) {     //error: conflicting types for 'func_2'; have 'int(int)'
    return 8;
}
int main() {
  return func_1();
}
```

Clang compiles the program normally, and the resulting program can be executed.

Expected behavior (like gcc):
```
Could not execute the program

Build failed

Compiler returned: 1
Compiler stderr

<source>:4:5: error: conflicting types for 'func_2'; have 'int(int)'
    4 | int func_2(int a) {
      |     ^~~~~~
<source>:2:5: note: previous declaration of 'func_2' with type 'int(void)'
    2 | int func_2();
      |     ^~~~~~
```

**Comment by topperc** [comment]
The latest gcc defaults to `-std=c23`. The latest clang defaults to `-std=c17`. If you add `-std=c23` to the clang command line it will produce an error.

**Comment by ZY546** [comment]
> The latest gcc defaults to `-std=c23`. The latest clang defaults to `-std=c17`. If you add `-std=c23` to the clang command line it will produce an error.

Thank you very much.
