### ISSUE TITLE
Compiling llvm in VC++11 fails.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12007]
|  |  |
| --- | --- |
| Bugzilla Link | [11635](https://llvm.org/bz11635) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Visual Studio 2011 Developer Preview reports an error in file lib/CodeGen/AsmPrinter
This is the error:
E:\Documents\Projects\llvm\lib\CodeGen\AsmPrinter\DwarfDebug.cpp(534): error C2668: 'llvm::tie' : ambiguous call to overloaded function
          E:\Documents\Projects\llvm\include\llvm/ADT/STLExtras.h(206): could be 'llvm::tier<T1,T2> llvm::tie<std::_Tree_iterator<_Mytree>,bool>(T1 &,T2 &)'
          with
          [
              T1=std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::pair<std::string,std::string>,unsigned int>>>>,
              T2=bool,
              _Mytree=std::_Tree_val<std::_Tree_simple_types<std::pair<const std::pair<std::string,std::string>,unsigned int>>>
          ]
          C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\tuple(690): or       'std::tuple<<unnamed-symbol>,_V0_t,_V1_t,_V2_t,_V3_t,_V4_t,_V5_t,std::_Nil> std::tie<std::_Tree_iterator<_Mytree>,bool>(std::_Tree_iterator<_Mytree> &,bool &)' [found using argument-dependent lookup]
          with
          [
              <unnamed-symbol>=std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::pair<std::string,std::string>,unsigned int>>>> &,
              _V0_t=bool &,
              _V1_t=std::_Nil,
              _V2_t=std::_Nil,
              _V3_t=std::_Nil,
              _V4_t=std::_Nil,
              _V5_t=std::_Nil,
              _Mytree=std::_Tree_val<std::_Tree_simple_types<std::pair<const std::pair<std::string,std::string>,unsigned int>>>
          ]
          while trying to match the argument list '(std::_Tree_iterator<_Mytree>, bool)'
          with
          [
              _Mytree=std::_Tree_val<std::_Tree_simple_types<std::pair<const std::pair<std::string,std::string>,unsigned int>>>
          ]

**Comment by arsenm** [comment]
Old unsupported compiler
