### ISSUE TITLE
[clang++]Does clang++ support '-minline-stringops-dynamically' ?

### ISSUE THREAD

**Issue by zhaojiangkun-1** [llvm/llvm-project#120049]
I have no problem using `g++ -minline-stringops-dynamically`, but failed to compile with `clang++ --minline-stringops-dynamically`.
Does clang++ support '-minline-stringops-dynamically' ?

**error:**
`clang-15: error: unknown argument: '-minline-stringops-dynamically'`

**Comment by tbaederr** [comment]
The output states pretty clearly that the option isn't supported.
