### ISSUE TITLE
`ios_base::sync_with_stdio` doesn't seem to do anything

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#120178]
Here's the implementation for `ios_base::sync_with_stdio`:

```cpp
bool ios_base::sync_with_stdio(bool sync) {
  static bool previous_state = true;
  bool r                     = previous_state;
  previous_state             = sync;
  return r;
}
```

As far as I can tell, that's only shuffling the state of a local bool, which tells me that it might not be decoupling iostream from stdio (I can't find any usage of the function to probe the state by the library, and since it's a local variable, it's not affecting anything on a broader level).

**Comment by trcrsired** [comment]
i do not think you can change it in any meaningful way. Disabling sync with stdio will cause thread-safety issues
