### ISSUE TITLE
clang-cl crash om windows

### ISSUE THREAD

**Issue by jtveiten** [llvm/llvm-project#120407]
1>PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
1>Stack dump:
1>0.	Program arguments: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\Llvm\\x64\\bin\\clang-cl.exe" -cc1 -triple amd64-pc-windows-msvc19.42.34435 -emit-obj -mincremental-linker-compatible -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name mdeventbus.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=none -relaxed-aliasing -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -fms-volatile -funwind-tables=2 -target-cpu x86-64 -target-feature +sse4.2 -mllvm -x86-asm-syntax=intel -tune-cpu generic -D_MT -D_DLL --dependent-lib=msvcrt --dependent-lib=oldnames -stack-protector 2 -fcxx-exceptions -fexceptions -fasync-exceptions -fdefault-calling-conv=cdecl -fdiagnostics-format msvc -gno-column-info -gcodeview -debug-info-kind=constructor -fdebug-compilation-dir=C:\\Users\\JanTveiten\\source\\repos\\paleoscan\\eventbus -object-file-name=C:\\Users\\JanTveiten\\source\\repos\\paleoscan\\eventbus\\x64\\Clang_Release\\mdeventbus.obj -ffunction-sections -fcoverage-compilation-dir=C:\\Users\\JanTveiten\\source\\repos\\paleoscan\\eventbus -resource-dir "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\Llvm\\x64\\lib\\clang\\18" -I x64\\Clang_Release\\moc -I . -I C:\\Users\\JanTveiten\\source\\repos\\paleoscan\\json\\single_include -I include -I release -I C:\\Users\\JanTveiten\\source\\repos\\paleoscan\\ -I C:\\Users\\JanTveiten\\source\\repos\\paleoscan\\eventbus\\ -I C:\\Users\\JanTveiten\\source\\repos\\paleoscan\\eventbus\\ -I C:\\QT\\qt5.15.13_msvc2019\\qtbase\\include -I C:\\QT\\qt5.15.13_msvc2019\\qtbase\\include\\QtGui -I C:\\QT\\qt5.15.13_msvc2019\\qtbase\\include\\QtCore -I C:\\QT\\qt5.15.13_msvc2019\\qtbase\\mkspecs\\win32-msvc -I x64\\Clang_Release\\moc -D _WINDOWS -D UNICODE -D _UNICODE -D WIN32 -D _ENABLE_EXTENDED_ALIGNED_STORAGE -D WIN64 -D OPENMP_ENABLED -D _EXPORTINGEVENTBUS -D NDEBUG -D QT_NO_DEBUG -D QT_PLUGIN -D _WINDOWS -D WIN32 -D _ENABLE_EXTENDED_ALIGNED_STORAGE -D WIN64 -D NDEBUG -D QT_NO_DEBUG -D QT_GUI_LIB -D QT_CORE_LIB -D _WINDLL -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\Llvm\\x64\\lib\\clang\\18\\include" -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\Llvm\\x64\\lib\\clang\\18\\include" -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.42.34433\\include" -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.42.34433\\atlmfc\\include" -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Auxiliary\\VS\\include" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.19041.0\\ucrt" -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Auxiliary\\VS\\UnitTest\\include" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.19041.0\\um" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.19041.0\\shared" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.19041.0\\winrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.19041.0\\cppwinrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\Include\\um" -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.42.34433\\include" -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.42.34433\\atlmfc\\include" -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Auxiliary\\VS\\include" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.19041.0\\ucrt" -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Auxiliary\\VS\\UnitTest\\include" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.19041.0\\um" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.19041.0\\shared" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.19041.0\\winrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.19041.0\\cppwinrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\Include\\um" -O2 -Wall -Wno-error -Werror=c++11-compat-deprecated-writable-strings -Werror=c++11-compat-deprecated-writable-strings -Wno-address-of-temporary -Wno-microsoft-enum-value -Werror=unused-private-field -Werror=unused-const-variable -Werror=unused-variable -Werror=empty-body -Werror=range-loop-construct -Werror=inconsistent-dllimport -Werror=invalid-source-encoding -Werror=microsoft-template -Werror=comment -Werror=dangling-else -Werror=extra-tokens -Werror=infinite-recursion -Werror=logical-not-parentheses -Werror=microsoft-goto -Werror=microsoft-include -Werror=misleading-indentation -Werror=non-literal-null-conversion -Werror=nonportable-include-path -Werror=pointer-bool-conversion -Werror=pointer-to-int-cast -Werror=pragma-once-outside-header -Werror=return-stack-address -Werror=self-assign-overloaded -Werror=sometimes-uninitialized -Werror=string-plus-int -Werror=switch -Werror=undefined-bool-conversion -Werror=unknown-escape-sequence -Werror=unused-comparison -Werror=unused-lambda-capture -Werror=unused-private-field -Werror=unused-result -Werror=unused-value -Werror=unused-variable -Werror=vexing-parse -Werror=ignored-attributes -Werror=microsoft-enum-forward-reference -Werror=microsoft-extra-qualification -Werror=typename-missing -fdeprecated-macro -ferror-limit 19 -fno-use-cxa-atexit -fms-extensions -fms-compatibility -fms-compatibility-version=19.42.34435 -std=c++17 -fskip-odr-check-in-gmf -fdelayed-template-parsing -fno-caret-diagnostics -vectorize-loops -vectorize-slp -faddrsig -o x64\\Clang_Release\\mdeventbus.obj -x c++ src\\mdeventbus.cpp
1>1.	<eof> parser at end of file
1>2.	Code generation
1>3.	Running pass 'Function Pass Manager' on module 'src\mdeventbus.cpp'.
1>4.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@"??$_Erase_tree@V?$allocator@U?$_Tree_node@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$basic_json@Vmap@std@@Vvector@2@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@_N_J_KNVallocator@2@Uadl_serializer@nlohmann@@V?$vector@EV?$allocator@E@std@@@2@@nlohmann@@@std@@PEAX@std@@@std@@@?$_Tree_val@U?$_Tree_simple_types@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$basic_json@Vmap@std@@Vvector@2@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@_N_J_KNVallocator@2@Uadl_serializer@nlohmann@@V?$vector@EV?$allocator@E@std@@@2@@nlohmann@@@std@@@std@@@std@@QEAAXAEAV?$allocator@U?$_Tree_node@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$basic_json@Vmap@std@@Vvector@2@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@_N_J_KNVallocator@2@Uadl_serializer@nlohmann@@V?$vector@EV?$allocator@E@std@@@2@@nlohmann@@@std@@PEAX@std@@@1@PEAU?$_Tree_node@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$basic_json@Vmap@std@@Vvector@2@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@_N_J_KNVallocator@2@Uadl_serializer@nlohmann@@V?$vector@EV?$allocator@E@std@@@2@@nlohmann@@@std@@PEAX@1@@Z"'
1>Exception Code: 0xC0000005
1> #0 0x00007ff790cac31b (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x277c31b)
1> #1 0x00007ff791318b1a (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x2de8b1a)
1> #2 0x00007ff7906010dd (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x20d10dd)
1> #3 0x00007ff7907440c6 (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x22140c6)
1> #4 0x00007ff78e8eb6b9 (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x3bb6b9)
1> #5 0x00007ff7905d472e (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x20a472e)
1> #6 0x00007ff7905f5533 (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x20c5533)
1> #7 0x00007ff78e876111 (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x346111)
1> #8 0x00007ff78e875bdd (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x345bdd)
1> #9 0x00007ff78e86fa69 (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x33fa69)
1>#10 0x00007ff7905f0365 (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x20c0365)
1>#11 0x00007ff7909af1a8 (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x247f1a8)
1>#12 0x00007ff78eae17e1 (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x5b17e1)
1>#13 0x00007ff78eae1282 (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x5b1282)
1>#14 0x00007ff78eaddfb4 (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x5adfb4)
1>#15 0x00007ff78eadbb30 (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x5abb30)
1>#16 0x00007ff78eada4fe (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x5aa4fe)
1>#17 0x00007ff78e91a47c (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x3ea47c)
1>#18 0x00007ff78e9160c3 (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x3e60c3)
1>#19 0x00007ff790a34b70 (C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe+0x2504b70)
1>#20 0x00007ffb66fde8d7 (C:\Windows\System32\KERNEL32.DLL+0x2e8d7)
1>#21 0x00007ffb68c7fbcc (C:\Windows\SYSTEM32\ntdll.dll+0xdfbcc)
1>clang-cl : error : clang frontend command failed due to signal (use -v to see invocation)
1>clang version 18.1.8
1>Target: amd64-pc-windows-msvc
1>Thread model: posix
1>InstalledDir: C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin
1>clang-cl : message : diagnostic msg:
1>********************
1>PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
1>Preprocessed source(s) and associated run script(s) are located at:
1>clang-cl : message : diagnostic msg: C:\Users\JANTVE~1\AppData\Local\Temp\mdeventbus-e8fc05.cpp
1>clang-cl : message : diagnostic msg: C:\Users\JANTVE~1\AppData\Local\Temp\messagemgr-6b94b0.cpp
1>clang-cl : message : diagnostic msg: C:\Users\JANTVE~1\AppData\Local\Temp\mdeventbus-e8fc05.sh
1>clang-cl : message : diagnostic msg:
1>********************

[messagemgr-6b94b0.cpp.txt](https://github.com/user-attachments/files/18180489/messagemgr-6b94b0.cpp.txt)
[mdeventbus-e8fc05.cpp.txt](https://github.com/user-attachments/files/18180495/mdeventbus-e8fc05.cpp.txt)
[mdeventbus-e8fc05.sh.txt](https://github.com/user-attachments/files/18180499/mdeventbus-e8fc05.sh.txt)

**Comment by DimitryAndric** [comment]
Looking at your command line, `C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin\clang-cl.exe` is most likely a Microsoft-provided clang-cl binary, so posting a bug here is not likely to solve this crash. You should probably report it to Microsoft  too.

That said, I can reproduce with clang 18.1.x:

```text
A single unwind edge may only enter one EH pad
  invoke void @llvm.seh.scope.end()
          to label %104 unwind label %102, !dbg !12629
A single unwind edge may only enter one EH pad
  invoke void @llvm.seh.scope.end()
          to label %160 unwind label %158, !dbg !12737
A single unwind edge may only enter one EH pad
  invoke void @llvm.seh.scope.end()
          to label %199 unwind label %197, !dbg !12821
A single unwind edge may only enter one EH pad
  invoke void @llvm.seh.scope.end()
          to label %327 unwind label %325, !dbg !12921
Assertion failed: (!verifyFunction(*L->getHeader()->getParent(), &dbgs())), function processLoop, file /home/dim/src/llvm/llvm-project/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp, line 10219.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang -cc1 -triple amd64-pc-windows-msvc19.42.34435 -emit-obj -mincremental-linker-compatible -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name mdeventbus.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=none -relaxed-aliasing -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -fms-volatile -funwind-tables=2 -target-cpu x86-64 -target-feature +sse4.2 -mllvm -x86-asm-syntax=intel -tune-cpu generic -D_MT -D_DLL --dependent-lib=msvcrt --dependent-lib=oldnames -stack-protector 2 -fcxx-exceptions -fexceptions -fasync-exceptions -fdefault-calling-conv=cdecl -fdiagnostics-format msvc -gno-column-info -gcodeview -debug-info-kind=constructor -fdebug-compilation-dir=C:\\Users\\JanTveiten\\source\\repos\\paleoscan\\eventbus -object-file-name=C:\\Users\\JanTveiten\\source\\repos\\paleoscan\\eventbus\\x64\\Clang_Release\\mdeventbus.obj -ffunction-sections -fcoverage-compilation-dir=C:\\Users\\JanTveiten\\source\\repos\\paleoscan\\eventbus -D _WINDOWS -D UNICODE -D _UNICODE -D WIN32 -D _ENABLE_EXTENDED_ALIGNED_STORAGE -D WIN64 -D OPENMP_ENABLED -D _EXPORTINGEVENTBUS -D NDEBUG -D QT_NO_DEBUG -D QT_PLUGIN -D _WINDOWS -D WIN32 -D _ENABLE_EXTENDED_ALIGNED_STORAGE -D WIN64 -D NDEBUG -D QT_NO_DEBUG -D QT_GUI_LIB -D QT_CORE_LIB -D _WINDLL -O2 -Wall -Wno-error -Werror=c++11-compat-deprecated-writable-strings -Werror=c++11-compat-deprecated-writable-strings -Wno-address-of-temporary -Wno-microsoft-enum-value -Werror=unused-private-field -Werror=unused-const-variable -Werror=unused-variable -Werror=empty-body -Werror=range-loop-construct -Werror=inconsistent-dllimport -Werror=invalid-source-encoding -Werror=microsoft-template -Werror=comment -Werror=dangling-else -Werror=extra-tokens -Werror=infinite-recursion -Werror=logical-not-parentheses -Werror=microsoft-goto -Werror=microsoft-include -Werror=misleading-indentation -Werror=non-literal-null-conversion -Werror=nonportable-include-path -Werror=pointer-bool-conversion -Werror=pointer-to-int-cast -Werror=pragma-once-outside-header -Werror=return-stack-address -Werror=self-assign-overloaded -Werror=sometimes-uninitialized -Werror=string-plus-int -Werror=switch -Werror=undefined-bool-conversion -Werror=unknown-escape-sequence -Werror=unused-comparison -Werror=unused-lambda-capture -Werror=unused-private-field -Werror=unused-result -Werror=unused-value -Werror=unused-variable -Werror=vexing-parse -Werror=ignored-attributes -Werror=microsoft-enum-forward-reference -Werror=microsoft-extra-qualification -Werror=typename-missing -fdeprecated-macro -ferror-limit 19 -fno-use-cxa-atexit -fms-extensions -fms-compatibility -fms-compatibility-version=19.42.34435 -std=c++17 -fdelayed-template-parsing -fno-caret-diagnostics -vectorize-loops -vectorize-slp -faddrsig -x c++ mdeventbus-e8fc05.cpp
1.      <eof> parser at end of file
2.      Optimizer
 #0 0x000000000405f708 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x405f708)
 #1 0x000000000405d4c9 llvm::sys::RunSignalHandlers() (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x405d4c9)
 #2 0x000000000405fece SignalHandler(int) Signals.cpp:0:0
 #3 0x000000082a24f4af handle_signal /usr/src/lib/libthr/thread/thr_sig.c:0:3
 #4 0x000000082a24ea6b thr_sighandler /usr/src/lib/libthr/thread/thr_sig.c:245:1
 #5 0x000000082885f2d3 ([vdso]+0x2d3)
 #6 0x000000082f400a0a __sys_thr_kill /usr/obj/usr/src/lib/libc/thr_kill.S:4:0
 #7 0x000000082f37a1e4 _raise /usr/src/lib/libc/gen/raise.c:0:10
 #8 0x000000082f42abc9 abort /usr/src/lib/libc/stdlib/abort.c:71:17
 #9 0x000000082f35d551 (/lib/libc.so.7+0x93551)
#10 0x000000000541e495 llvm::LoopVectorizePass::processLoop(llvm::Loop*) (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x541e495)
#11 0x00000000054223db llvm::LoopVectorizePass::runImpl(llvm::Function&, llvm::ScalarEvolution&, llvm::LoopInfo&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::BlockFrequencyInfo*, llvm::TargetLibraryInfo*, llvm::DemandedBits&, llvm::AssumptionCache&, llvm::LoopAccessInfoManager&, llvm::OptimizationRemarkEmitter&, llvm::ProfileSummaryInfo*) (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x54223db)
#12 0x0000000005422d48 llvm::LoopVectorizePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x5422d48)
#13 0x00000000053aed52 llvm::detail::PassModel<llvm::Function, llvm::LoopVectorizePass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) PassBuilder.cpp:0:0
#14 0x0000000003bc4e23 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x3bc4e23)
#15 0x000000000314cb62 llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) X86CodeGenPassBuilder.cpp:0:0
#16 0x0000000003bc96a5 llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x3bc96a5)
#17 0x000000000314c8e2 llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) X86CodeGenPassBuilder.cpp:0:0
#18 0x0000000003bc3a61 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x3bc3a61)
#19 0x00000000047dadbe (anonymous namespace)::EmitAssemblyHelper::RunOptimizationPipeline(clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>&, std::__1::unique_ptr<llvm::ToolOutputFile, std::__1::default_delete<llvm::ToolOutputFile>>&, clang::BackendConsumer*) BackendUtil.cpp:0:0
#20 0x00000000047d2821 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x47d2821)
#21 0x00000000047f330d clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x47f330d)
#22 0x0000000005aeb546 clang::ParseAST(clang::Sema&, bool, bool) (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x5aeb546)
#23 0x0000000004ba8133 clang::FrontendAction::Execute() (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x4ba8133)
#24 0x0000000004b2eecd clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x4b2eecd)
#25 0x0000000004c7e10e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x4c7e10e)
#26 0x0000000002502b10 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x2502b10)
#27 0x00000000024ffcd5 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#28 0x00000000024fed37 clang_main(int, char**, llvm::ToolContext const&) (/home/dim/ins/llvmorg-19-init-00000-g987087df900/bin/clang+0x24fed37)
Abort trap
```

This problem got fixed with `llvmorg-19-init-07329-g`a1f4ac77042 by @phoebewang @robertcox-github, but it was possibly a side-effect. You might want to point to that commit if you report the problem to Microsoft.
