### ISSUE TITLE
"Getting Started" docs out of date

### ISSUE THREAD

**Issue by 3a17e7c4-fca4-4827-b2a7-11a54d73d746** [llvm/llvm-project#12050]
|  |  |
| --- | --- |
| Bugzilla Link | [11678](https://llvm.org/bz11678) |
| Version | trunk |
| OS | Linux |
| CC | @gribozavr,@jryans |

## Extended Description 
http://clang.llvm.org/get_started.html

step 4 should be 'cd ../projects' not 'cd llvm/projects' because after step 3 you're already in llvm/tools

I think step 6 is out of date, instead of hacking the sources I think it's now possible to simply configure with --with-cxx-include-root and --with-cxx-include-arch

**Comment by Endilll** [comment]
`llvm/projects` is not a thing anymore
