### ISSUE TITLE
An alloca that is never used for anything but updating itself is not optimized away

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12064]
|  |  |
| --- | --- |
| Bugzilla Link | [11692](https://llvm.org/bz11692) |
| Version | 3.0 |
| OS | Linux |
| Attachments | [example showing the behaviour](https://user-images.githubusercontent.com/60944935/143744506-65c64597-2c6b-415b-a1ef-619e597e968b.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

An alloca that is never used for anything but updating itself is not optimized away in the attached example. This depends on the size of the array. When I tested it then it was optimized away if the size of the array was <= 21 and not optimized away otherwise.

**Comment by arsenm** [comment]
opt -O3 folds this away today:
```
define i32 @main() local_unnamed_addr #0 {
entry:
  ret i32 0
}

```
