### ISSUE TITLE
Semantics of `std::move` and `std::forward` changed in D123345 and now allow invalid code to compile

### ISSUE THREAD

**Issue by graphitemaster** [llvm/llvm-project#120668]
GCC and clang both treat `std::move` and `std::forward` specially in their frontend now as a result of

https://reviews.llvm.org/D123345

and (for GCC) https://gcc.gnu.org/bugzilla/attachment.cgi?id=51732

This change has now enabled `std::move` and `std::forward` to work on incomplete types when they wouldn't usually and allows invalid code to compile on both gcc and clang.

Consider this trivial example
```cpp
template<class T1, class T2> struct pair { T1 first; T2 second; };
template<class T> struct array {};
struct incomplete; // incomplete type
struct test {
  test(test&& t) : data{std::move(t.data)} {} // This compiles but shouldn't
  array<pair<int, incomplete>> data; // T1 is complete, T2 is incomplete
};
```

If you implement your own `std::move` as can be seen here
```cpp
template<typename T>
constexpr std::remove_reference_t<T>&& move(T&& t) noexcept {
  return static_cast<std::remove_reference_t<T>&&>(t);
}
struct test {
  test(test&& t) : data{move(t.data)} {} 
  array<pair<int, incomplete>> data;
};
```

When compiled this will produce the correct error
```
<source>: In instantiation of 'struct pair<int, incomplete>':
<source>:14:44:   required from here
   14 |     test(test&& other) : data{move(other.data)} {}
      |                                              ^
<source>:3:26: error: 'pair<T1, T2>::second' has incomplete type
    3 | struct pair { T1 first; T2 second; };
      |                         ^~~~~~~~~
<source>:12:8: note: forward declaration of 'struct incomplete'
   12 | struct incomplete;
      |        ^~~~~~~~~~
```

**Comment by pinskia** [comment]
Note you are wrong about the patch which caused GCC to accept it. Since the gimplification would happen after the rejection in the first place.

**Comment by pinskia** [comment]
>If you implement your own std::move as can be seen here

No that is doing ADL lookup and that is what is causing the failure. This has nothing to do with std::move or move. You could have used `::move` and it would work with your definition of move.

That is this works:
```
#include <utility>
template<class T1, class T2> struct pair { T1 first; T2 second; };
template<class T> struct array {};
struct incomplete; // incomplete type
template<typename T>
constexpr std::remove_reference_t<T>&& move(T&& t) noexcept {
  return static_cast<std::remove_reference_t<T>&&>(t);
}
struct test1 {
  test1(test1&& t) : data{::move(t.data)} {} 
  array<pair<int, incomplete>> data;
};
```

Notice the use of `::move` rather than `move`. The qualified name causes ADL not to happen.

**Comment by frederick-vs-ja** [comment]
The example compiled with Clang 3.7, which is far more earlier than the mentioned change. I'm closing this as invalid.
