### ISSUE TITLE
automatically tries to build libc++ using OSX Makefile

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12076]
|  |  |
| --- | --- |
| Bugzilla Link | [11704](https://llvm.org/bz11704) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Hello,

I have a checkout of llvm, and checkouts of clang under tools/ and compiler-rt and libcxx under projects/ as recommended. I configure with the simple: /path/to/configure --prefix=/path/to/inst --enable-optimized, then run make and make install.

Apparently, this now automatically tries to handle libc++ (which is great), except that it uses the Makefile in there which only stands some chance of working on OSX. Besides, the compilation is triggered by make install, not by make. And things are done in the checkout, not in the build directory.

Since the build system is not ready, it might be better not to automatically do anything with libcxx?

**Comment by philnik777** [comment]
This is definitely fixed now.

**Comment by Endilll** [comment]
Autotools is long gone.
