### ISSUE TITLE
[AArch64][GISel] Handle bitreverse intrinsic for some vector types

### ISSUE THREAD

**Issue by madhur13490** [llvm/llvm-project#120869]
Parent issue: https://github.com/llvm/llvm-project/issues/115133
Godbolt link: https://godbolt.org/z/nP8jssKh8

This intrinsic is missing support for v2i64, v4i16 etc. as shown by the above godbolt link.

**Comment by madhur13490** [comment]
@aemerson Are you planning to handle this as you seem to have the recent patch around this? https://github.com/llvm/llvm-project/commit/49ecd665fcc311f7cd61e81d3f7a112cd287e292

**Comment by aemerson** [comment]
> [@aemerson](https://github.com/aemerson) Are you planning to handle this as you seem to have the recent patch around this? [49ecd66](https://github.com/llvm/llvm-project/commit/49ecd665fcc311f7cd61e81d3f7a112cd287e292) If not, I will take a look.

I wasn't looking at this issue in particular, it was one of the more common fallbacks I saw when building CTMark with -O3.

I added some more tests to show the other types are now working, although there's still some room for improvement on some: 3bb0c73ab50121f518c8d66154283cfd50d6d31a

Will close this issue as it seems to be done from a functionality standpoint.

**Comment by madhur13490** [comment]
2 x s32, 2 x i64, 4 x s16, 4 x s32, 8 x s16 are still falling back as I see on [here](https://godbolt.org/z/nP8jssKh8)

**Comment by aemerson** [comment]
> 2 x s32, 2 x i64, 4 x s16, 4 x s32, 8 x s16 are still falling back as I see on [here](https://godbolt.org/z/nP8jssKh8)

I think it takes some time (I don't know how much exactly) for godbolt to pick up the latest build of LLVM.

**Comment by madhur13490** [comment]
Yes, confirmed locally. Filed 
https://github.com/llvm/llvm-project/issues/120878 for optimization.
Thanks!
