### ISSUE TITLE
Crash referring to label from a constexpr function

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#12088]
|  |  |
| --- | --- |
| Bugzilla Link | [11716](https://llvm.org/bz11716) |
| Version | unspecified |
| OS | All |
| CC | @asl,@DougGregor,@zygoloid |

## Extended Description 
Testcase:
constexpr long a() {
  return (0 && ({lbl1:lbl2: 0;})), (long)&&lbl1 - (long)&&lbl2;
}
void b() { static long b = a(); }

Crashes in IRGen with:

Referring to a basic block in another function!
  indirectbr i8* undef, [label %lbl1, label %lbl2]
Broken module found, compilation aborted!

Not sure whether we should try to enforce some restriction on Evaluate or just add the relevant safety check to CGExprConstant.

**Comment by Endilll** [comment]
Can't reproduce on either Clang 3.5 and 16
https://godbolt.org/z/jYrc6EPME
