### ISSUE TITLE
Missing AST matcher: dependentScopeDeclRefExpr

### ISSUE THREAD

**Issue by HighCommander4** [llvm/llvm-project#120937]
The AST matchers library seems to be missing a matcher that matches an expression of type `DependentScopeDeclRefExpr`.

**Comment by AmrDeveloper** [comment]
Interested, I will work on it

**Comment by HighCommander4** [comment]
> Interested, I will work on it

Thanks!

 Let me know if you need any code pointers / other guidance to get you started.

**Comment by AmrDeveloper** [comment]
I opened a [PR](https://github.com/llvm/llvm-project/pull/120996) for it, if you have time i can assign you as reviwer
