### ISSUE TITLE
Failed to compile matrix product like code using llvm 19.x for riscv vector extension.

### ISSUE THREAD

**Issue by fanghuaqi** [llvm/llvm-project#121086]
Hi there,

I tried to compile source code as below, using clang with options: `-march=rv32imafc_zve32f_zvl128b -mabi=ilp32f -Ofast`

~~~c

float *matA, *matB, *matC;
int nthreads = 1;

typedef struct{
   int id;
   int rowsA;
   int colsA;
   int colsB;
} tArgs;

void CalculaProdutoMatriz(void *arg) {
   int i, j, k;
   tArgs *args = (tArgs*) arg;
   int rowsA = args->rowsA;
   int colsA = args->colsA;
   int colsB = args->colsB;

   for(i = args->id; i < rowsA; i += nthreads) {
      for(j = 0; j < colsB; j++) {
         matC[i * colsB + j] = 0;
         for(k = 0; k < colsA; k++) {
               matC[i * colsB + j] += matA[i * colsA + k] * matB[k * colsB + j];
         }
      }
   }
}
~~~

It works in llvm 18.x and llvm truck(20.x), but failed in llvm 19.x error message like this

```
3.      Running pass 'Function Pass Manager' on module 'main.c'.
4.      Running pass 'RISC-V DAG->DAG Pattern Instruction Selection' on function '@main'
```

Thanks

**Comment by topperc** [comment]
The error says the `main` function was being compiled, but your source does not have a `main`. Is this the complete source?

**Comment by fanghuaqi** [comment]
I didn't paste the complete source code, I compiled it in my SDK environment, I create compiler explorer link here https://godbolt.org/z/Ec3o8vex1

It contains a main function. I just want to test the auto vectorization for riscv vector in llvm clang.

**Comment by wangpc-pp** [comment]
Can you be more specific about the baseline of 19.x? I can't reproduce the error with:
```bash
# clang -march=rv32imafc_zve32f_zvl128b -mabi=ilp32f -Ofast reduced.c -S
clang: warning: argument '-Ofast' is deprecated; use '-O3 -ffast-math' for the same behavior, or '-O3' to enable only conforming optimizations [-Wdeprecated-ofast]

# clang -v
clang version 19.1.6 (e21dc4bd5474d04b8e62d7331362edcc5648d7e5)
Target: riscv64-unknown-linux-gnu
Thread model: posix
InstalledDir: /data00/wpc/software/llvm-dev/bin
Build config: +unoptimized, +assertions
```

**Comment by fanghuaqi** [comment]
Thanks @topperc @wangpc-pp , yes the error is `fatal error: error in backend: Do not know how to soften this operator's operand!`

**Comment by fanghuaqi** [comment]
When I changed the `-march=rv32imafc_zve32f_zvl128b -mabi=ilp32f` to `-march=rv32imafdc_zve32f_zvl128b -mabi=ilp32d` then the compile error disappeared.

**Comment by wangpc-pp** [comment]
I think https://github.com/llvm/llvm-project/pull/116159 can fix this error.
We may backport it to 19.x, but it may be too late. @topperc WDYT?

**Comment by fanghuaqi** [comment]
Hi @wangpc-pp ， this #116159 can fix this issue locally in my llvm compiler cherry picked this PR.
