### ISSUE TITLE
Find point in time where test failed

### ISSUE THREAD

**Issue by tlattner** [llvm/llvm-project#1210]
|  |  |
| --- | --- |
| Bugzilla Link | [838](https://llvm.org/bz838) |
| Version | trunk |
| OS | Linux |

## Extended Description 
It would be useful to see at what point in time a test failed (which day) so
that its easier to determine what caused the failure. Ideally I would be able to
click on a test and see either a graph or list of dates when it failed, passed,
etc. This feature could also be used to catch tests that flip-flop between
passing and failing. It would be great to have this feature for all the tests
(including dejagnu regression tests).

**Comment by gwelymernans** [comment]
This is done with the built and test systems we have going.
