### ISSUE TITLE
Can't specify a physical register in inline assembly issue

### ISSUE THREAD

**Issue by LuoYuanke** [llvm/llvm-project#121142]
It seems below inline assembly fails to be compiled with clang, but can be successful compiled with GCC. It can be duplicated in https://godbolt.org/z/xhrq6YEvT

```
void foo() {
  int src = 1;
  int dst, dst2;

  asm("movl %1, %0\n\t"
      "addl $1, %0"
      : "=eax"(dst)
      : "i"(1));
}
```

**Comment by phoebewang** [comment]
`eax` isn't a documented inline asm constraint, see https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Machine-Constraints.html#Machine-Constraints. Change it to `a` can solve the problem.
