### ISSUE TITLE
MCAsmStreamer: Omit initial ".text" causing lot of breakages

### ISSUE THREAD

**Issue by pranavk** [llvm/llvm-project#121119]
@MaskRay 

https://github.com/llvm/llvm-project/commit/7b23f413d1f76532825e470b523e971818d453ca#diff-c1cd0d8700618033d5c6439791e7203361e531ee49f9a53865ca158302a79adc is causing us a lot of problems. I know you have changed all the tests that were dependent on it in the LLVM repo but it's a disruptive change in general. I am trying to fix-forward but failing that, could we revert this and reland it later after the holidays?

**Comment by MaskRay** [comment]
How is this disruptive at all? Do you have a downstream `llvm/lib/Target/XXX` with many tests expect implicit `.text`? The fix is mechanical.

You can also hack `initSections` to use `switchSection` instead of `switchSectionNoPrint` for your targets.

**Comment by pranavk** [comment]
Ok. ended up working around it. Sorry for the noise.
