### ISSUE TITLE
Clang mixes up class name with member variable name when parsing explicit dtors

### ISSUE THREAD

**Issue by wangbo15** [llvm/llvm-project#121155]
A very simple case:

```c++
struct a { 
    int a; 
    ~a()=default;
};
```

Clang rejects it by complaining that `a` is not a type name:

```c++
<source>:3:6: error: identifier 'a' after '~' in destructor name does not name a type
    3 |     ~a()=default;
      |      ^
      |      a
<source>:2:9: note: non-type declaration found by destructor name lookup
    2 |     int a; 
      |         ^
1 error generated.
```

It seems that there shouldn't be any ambiguity here as that `a` in `~a()` definitely refers to `struct a` here. GCC and MSVC both accept the code.

Please see [https://godbolt.org/z/KjhE6rjTh](https://godbolt.org/z/KjhE6rjTh)

**Comment by shafik** [comment]
Duplicate: https://github.com/llvm/llvm-project/issues/88597
