### ISSUE TITLE
clang-cl does not understand /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS

### ISSUE THREAD

**Issue by Kataglyphis** [llvm/llvm-project#121166]
Hi,

I am using Microsoft Visual Studio 2022 with the C++-Clang-Compiler 
for Windows (18.1.8).
When running the following command:
```ps
PS C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin> .\clang-cl.exe /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS
```

I get an output like this:
```ps
clang-cl: error: no input files
```
which indicates clang does not understand this macro yet.
Any chances to include that?
Do I miss something?

Best
Kataglyphis

**Comment by DimitryAndric** [comment]
Yes, you still have to provide an input file to compile (probably a .cpp file). The macro definition is just fine.
