### ISSUE TITLE
does not compile even a simple project, causing exception code 0xC0000005

### ISSUE THREAD

**Issue by Dormammu-616** [llvm/llvm-project#121264]
Using Clang-Tidy via the terminal in Visual Code for the C++ programming language results in an error message even for simple projects.
It produces the following:

PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\Llvm\\bin\\clang-tidy.exe" main.cpp -checks=* --
Exception Code: 0xC0000005
#0 0x014c1110 (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin\clang-tidy.exe+0x8c1110)

**Comment by EugeneZelenko** [comment]
Which version of Clang-tidy do you use?

**Comment by Dormammu-616** [comment]
> Which version of Clang-tidy do you use?

LLVM version 18.1.8
