### ISSUE TITLE
[clang++] Does not error with a zero length array declaration (definition)

### ISSUE THREAD

**Issue by safocl** [llvm/llvm-project#121398]
Clang++ allows declaration (definition) of arrays of zero size (`TYPE NAME[0]`). However, this is prohibited by the c++ standard:
[c++23] ([here](https://timsong-cpp.github.io/cppwp/n4950/dcl.array#1.sentence-3))
```
In a declaration T D where D has the form
D1 [ constant-expression opt ] attribute-specifier-seq opt
[...]
The constant-expression shall be a converted constant expression of type std​::​size_t ([expr.const]).
Its value N specifies the array bound, i.e., the number of elements in the array; N shall be greater than zero.
```

[c++11] ([here](https://timsong-cpp.github.io/cppwp/n3337/dcl.array#1))

[c++17] ([here](https://timsong-cpp.github.io/cppwp/n4659/dcl.array#1))

[Example](https://godbolt.org/z/xT6farz85) :
```
#include <iostream>

struct Data {
   int lhs[0];
   explicit Data(const int rhs) {
    lhs[rhs];
    lhs[0]=rhs;
   }

   void print() {
      std::cout << lhs[0] << "\n";
   }
};


int main() {
   int aaa[0];
   int bbb[0]{};
   Data t(42);
   t.print();
   return sizeof(aaa) + sizeof(bbb);
}
```

**Expected behavior**
COMPILETIME ERROR.

**Current behavior**
Compilation completed without errors.

**Comment by MacDue** [comment]
Note: If you use `-pedantic -Werror` this does become an error:
```
<source>:4:12: error: zero size arrays are an extension [-Werror,-Wzero-length-array]
    4 |    int lhs[0];
      |            ^
```
https://godbolt.org/z/717Y6xn3c

**Comment by safocl** [comment]
> Note: If you use `-pedantic -Werror` this does become an error:
> 
> ```
> <source>:4:12: error: zero size arrays are an extension [-Werror,-Wzero-length-array]
>     4 |    int lhs[0];
>       |            ^
> ```

This error is a limitation of the core language - it should work without additional compiler options (which only help to generate correct code).

**Comment by safocl** [comment]
> > Note: If you use `-pedantic -Werror` this does become an error:
> > ```
> > <source>:4:12: error: zero size arrays are an extension [-Werror,-Wzero-length-array]
> >     4 |    int lhs[0];
> >       |            ^
> > ```
> 
> This error is a limitation of the core language - it should work without additional compiler options (which only help to generate correct code). (this is not semantics, but syntax -- such a code entry is unacceptable in principle)
> 
> https://godbolt.org/z/1TfPEcr1f -- it does error for the `The constant-expression shall be a converted constant expression of type std​::​size_t ([expr.const])` rule, that have same rank with issue
```
<source>:17:12: error: value of type 'const char[1]' is not implicitly convertible to 'unsigned long'
   17 |    int aaa[""];
      |            ^~
```

**Comment by shafik** [comment]
This is a GNU extension: https://github.com/llvm/llvm-project/issues/54705 

There is some question as to why this allowed outside of a flexible array context but I am not sure how much appetite there would be to change this as we would need to coordinate with both gcc/edg.
