### ISSUE TITLE
LLVM disassembly failed

### ISSUE THREAD

**Issue by facihul-intel** [llvm/llvm-project#121327]
I tried to generate "trng" instruction assembly code. after running llvm disassembly to 128 bit Encoded value it fails  showing the error msg below, even though PyASM disassembly works.

 // trng 128N b32 (src0 = GRF(0x0), src1 = GRF(0xffffffff))
    r0          =         mov.b32 0x0
    r8          =         mov.b32 0xffffffff
    fs0         =         sseta.b32 0x1 // lane 0
    // LLVM disassembly failed because of "PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
    Stack dump:
    0.Program arguments: C:\\Users\\mdfacihu\\work\\xe4_eu_clt_gen\\testgen\\llvm\\llvm-mc.exe --arch=         xe --disassemble --raw-bin llvm_in.bin
    Exception Code: 0xC0000005
    0x00007FF76B170B9F, C:\Users\mdfacihu\work\xe4_eu_clt_gen\testgen\llvm\llvm-mc.exe(0x00007FF76AF20000) + 0x250B9F byte(s)
    0x00007FF76B65AF64, C:\Users\mdfacihu\work\xe4_eu_clt_gen\testgen\llvm\llvm-mc.exe(0x00007FF76AF20000) + 0x73AF64 byte(s)
    0x0000000000827C14 <unknown module>
    0x00007FF76AF20000, C:\Users\mdfacihu\work\xe4_eu_clt_gen\testgen\llvm\llvm-mc.exe(0x00007FF76AF20000) + 0x0 byte(s)
    0x000002145A7BCBD0 <unknown module>
    0x00007FF76B1730E2, C:\Users\mdfacihu\work\xe4_eu_clt_gen\testgen\llvm\llvm-mc.exe(0x00007FF76AF20000) + 0x2530E2 byte(s)
    0x00007FF76B172DA6, C:\Users\mdfacihu\work\xe4_eu_clt_gen\testgen\llvm\llvm-mc.exe(0x00007FF76AF20000) + 0x252DA6 byte(s)
    0x00007FF76B227582, C:\Users\mdfacihu\work\xe4_eu_clt_gen\testgen\llvm\llvm-mc.exe(0x00007FF76AF20000) + 0x307582 byte(s)
    0x00007FF76B2773B9, C:\Users\mdfacihu\work\xe4_eu_clt_gen\testgen\llvm\llvm-mc.exe(0x00007FF76AF20000) + 0x3573B9 byte(s)
    0x00007FF76AF2E93B, C:\Users\mdfacihu\work\xe4_eu_clt_gen\testgen\llvm\llvm-mc.exe(0x00007FF76AF20000) + 0xE93B byte(s)
    0x00007FF76AF2D16A, C:\Users\mdfacihu\work\xe4_eu_clt_gen\testgen\llvm\llvm-mc.exe(0x00007FF76AF20000) + 0xD16A byte(s)
    0x00007FF76B366FA0, C:\Users\mdfacihu\work\xe4_eu_clt_gen\testgen\llvm\llvm-mc.exe(0x00007FF76AF20000) + 0x446FA0 byte(s)
    0x00007FFC68F6259D, C:\windows\System32\KERNEL32.DLL(0x00007FFC68F50000) + 0x1259D byte(s), BaseThreadInitThunk() + 0x1D byte(s)
    0x00007FFC6A72AF38, C:\windows\SYSTEM32\ntdll.dll(0x00007FFC6A6D0000) + 0x5AF38 byte(s), RtlUserThreadStart() + 0x28 byte(s)
    "!
    // Using PyASM for a0f30000000000000000000014804005
    // Field values: {'dbg': 0, 'op': 464, 'res0': 0, 'sbid': 30, 'sbd0': 0, 'sbt0': 0, 'sbd1': 0, 'sbt1': 0, 'ttype': 0, 'pack': 0, 'mralg': 0, 'mxdim': 0, 'reddim': 0, 'n': 0, 'rndsrc': 0, 'res1': 0, 'dsat': 0, 'ipred': 0, 'pf': 0, 'trmo': 0, 'w': 0, 'meta0': 0, 'meta1': 0, 'imm10': 0, 'src1': 40, 'src0': 32, 'dst': 42, 'sbctrl0': 0, 'sbctrl1': 0}
    r10         =         (p0) trng.b32 r0, r8 {128N}

**Comment by EugeneZelenko** [comment]
@facihul-intel: Could you please elaborate?

**Comment by facihul-intel** [comment]
Hi,

It was my coding error. Just managed to fix the issue. I just closed the issue report.
Thanks for contacting.
