### ISSUE TITLE
incorrectly narrowing switch cases before checking for duplicates

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#12150]
|  |  |
| --- | --- |
| Bugzilla Link | [11778](https://llvm.org/bz11778) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@hubert-reinterpretcast,@jsonn |

## Extended Description 
<stdin>:1:34: warning: overflow converting case value to switch condition type
      (256 to 0) [-Wswitch]
int f(char c) { switch(c) { case 256: case 0: return 1; } return 0; }
                                 ^
<stdin>:1:44: error: duplicate case value '0'
int f(char c) { switch(c) { case 256: case 0: return 1; } return 0; }
                                           ^
<stdin>:1:34: note: previous case defined here
int f(char c) { switch(c) { case 256: case 0: return 1; } return 0; }
                                 ^

This is incorrect: the promoted type of the switch condition is 'int', and there are no duplicate case values in this switch statement. The warning is also incorrect, but it seems wise to produce some kind of warning for this case: 'condition value can never equal case value' or similar.

**Comment by philnik777** [comment]
Has been fixed in Clang 7: https://godbolt.org/z/MdGMe9vca
