### ISSUE TITLE
-ftime-trace doesn't work as well with -fexperimental-new-pass-manager

### ISSUE THREAD

**Issue by tru** [llvm/llvm-project#122]
I was doing some work with `-ftime-trace` recently and it turns out that if you use it together with `-fexperimental-new-pass-manager` the optimization block in the JSON output from time-trace is going to have a huge block that's not annotated the data without the new pass manager is much more detailed.

**Comment by jdoerfert** [comment]
Might have been fixed by https://reviews.llvm.org/rGc5a06019d23

**Comment by RKSimon** [comment]
@tru Was this issue fixed by c5a06019d23?

**Comment by tru** [comment]
I hadn't thought about this in a long time - but I just created a tracefile from LLVM 14.x that I had installed and I did both with the new and the legacy pass manager and it looks fine to me now. I think this can be closed and if someone digs deeper and find any more problems they can re-open or create a new issue.
