### ISSUE TITLE
clang makefile assumes all powerpc systems have altivec

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12296]
|  |  |
| --- | --- |
| Bugzilla Link | [11924](https://llvm.org/bz11924) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 
Compiling clang 3.0 with g++ 4.4.5 on a PowerPC G3 system (no AltiVec) running Linux results in a clang binary which crashes when the lexer runs. The problem is these lines in lib/Lex/Makefile which cause the compiler to compile a section with AltiVec instructions in Lexer.cpp:

ifeq ($(ARCH),PowerPC)
CXX.Flags += -maltivec
endif

These lines are still in trunk. When I remove them then the compiled binary runs fine. Not all PowerPC systems have AltiVec support, so these lines should be removed or replaced with a more intelligent test.

**Comment by cor3ntin** [comment]
We no longer have makefiles!
