### ISSUE TITLE
Fix git clang-format help message

### ISSUE THREAD

**Issue by albestro** [llvm/llvm-project#123]
The helper message reports

`clangFormat.extension` (singular)

but in the code `clangformat.extensions` (plural) is used.

https://github.com/llvm/llvm-project/blob/fddacd00fc36358d2f7c48af108ccaa27fc3b084/clang/tools/clang-format/git-clang-format#L46-L49

For what concerns the case-sensitiveness, it seems that options names are case-insensitive.

**Comment by tclin914** [comment]
Fixed by https://reviews.llvm.org/rGd40afadec0ac.
