### ISSUE TITLE
__assume() cannot compile

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12317]
|  |  |
| --- | --- |
| Bugzilla Link | [11945](https://llvm.org/bz11945) |
| Version | 3.0 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @arrowd |

## Extended Description 
int main (int argc, const char * argv[])
{
    __assume(1);
    return 0;
}

got error message:
__assume() cannot compile this function yet.

**Comment by arsenm** [comment]
__assume is undefined. __builtin_assume works. Latest comment says this can be closed
