### ISSUE TITLE
Error without source location with qualified function type

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#12337]
|  |  |
| --- | --- |
| Bugzilla Link | [11965](https://llvm.org/bz11965) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor |

## Extended Description 
Testcase:

typedef int a() const;
void* x = (void*)new a;

Currently gives:

error: a qualified function type cannot be used to declare a nonmember function
<stdin>:2:22: error: cannot allocate function type 'int ()' with new
void* x = (void*)new a;
                     ^
2 errors generated.

The first error makes absolutely no sense.

**Comment by wheatman** [comment]
This error was improved between 3.1 and 3,2
https://godbolt.org/z/rbf1c4arz

I think it would be considered good enough, but will let somebody else close it if they agree. 

code
```
typedef int a() const;
void* x = (void*)new a;
```

old error
```
error: a qualified function type cannot be used to declare a nonmember function
<source>:2:22: error: cannot allocate function type 'int ()' with new
void* x = (void*)new a;
                     ^
2 errors generated.
Compiler returned: 1
```

new error
```
clang: warning: argument unused during compilation: '-gdwarf-4'
<source>:2:22: error: non-member function of type 'a' (aka 'int () const') cannot have 'const' qualifier
void* x = (void*)new a;
                     ^
<source>:2:22: error: cannot allocate function type 'int ()' with new
void* x = (void*)new a;
                     ^
2 errors generated.
Compiler returned: 1
```
