### ISSUE TITLE
gnu Assertions not supported

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12448]
|  |  |
| --- | --- |
| Bugzilla Link | [12076](https://llvm.org/bz12076) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Even though they are going to be deprecated, there are a lot of headers out there that are currently using them.

Here is the link that describes them: http://gcc.gnu.org/onlinedocs/gcc-4.0.4/cpp/Assertions.html

**Comment by Endilll** [comment]
At the time this feature request was filed, `#assert` was considered obsolete by a 6-years-old GCC 4.0.
We didn't bother supporting that back then, and don't bother supporting that today.

CC @AaronBallman
