### ISSUE TITLE
crash with opaque member

### ISSUE THREAD

**Issue by nlewycky** [llvm/llvm-project#12451]
|  |  |
| --- | --- |
| Bugzilla Link | [12079](https://llvm.org/bz12079) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Testcase 1:

  %struct.B = type opaque
  %struct.A = type {i32, %struct.B, i8}
  
  define i32* @&#8203;test(%struct.A* %x) {
    %A = bitcast %struct.A* %x to i32*
    ret i32* %A      
  }

and testcase 2:

  %struct.B = type opaque
  %struct.A = type {i32, %struct.B, i8}
  
  @&#8203;gv = global %struct.A zeroinitializer
  
  define i32* @&#8203;test() {
    %A = bitcast %struct.A* @&#8203;gv to i32*
    ret i32* %A      
  }

both crash trying to build a getelementptr, the first in instcombine and the second in early-cse (in inst-simplify, in constant folding).

Are all-zero GEPs supposed to be valid on partially-opaque types? Is that type supposed to be rejected? If you use %struct.B for the test then you'll find that it stays a bitcast (instruction or constant expression) thus avoiding the crash. Should that logic be extended?

**Comment by arsenm** [comment]
Both work fine for me today
