### ISSUE TITLE
clang frontend command failed due to signal 2

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12455]
|  |  |
| --- | --- |
| Bugzilla Link | [12083](https://llvm.org/bz12083) |
| Version | 3.0 |
| OS | FreeBSD |
| Attachments | [Preprocessed source(s)](https://user-images.githubusercontent.com/60944935/143744804-0ac38e18-4f41-4ed3-9b9f-6a194aa5f815.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 

FreeBSD clang version 3.0 (branches/release_30 142614) 20111021
Target: i386-unknown-freebsd9.0
Thread model: posix
 "/usr/obj/nanobsd.ALIX/usr/src/tmp/usr/bin/clang" -cc1 -triple i386-unknown-freebsd9.0 -emit-obj -disable-free -main-file-name unwind-dw2.c -pic-level 2 -mdisable-fp-elim -masm-verbose -mconstructor-aliases -target-cpu pentium-mmx -momit-leaf-frame-pointer -v -coverage-file unwind-dw2.o -resource-dir /usr/obj/nanobsd.ALIX/usr/src/tmp/usr/bin/../lib/clang/3.0 -D IN_GCC -D IN_LIBGCC2 -D __GCC_FLOAT_NOT_NEEDED -D HAVE_GTHR_DEFAULT -D HIDE_EXPORTS -D __GLIBC__=3 -D ElfW=__ElfN -I /usr/src/gnu/lib/libgcc/../../../contrib/gcclibs/include -I /usr/src/gnu/lib/libgcc/../../../contrib/gcc/config -I /usr/src/gnu/lib/libgcc/../../../contrib/gcc -I . -I /usr/src/gnu/lib/libgcc/../../usr.bin/cc/cc_tools -fmodule-cache-path /var/tmp/clang-module-cache -Os -std=gnu99 -ferror-limit 19 -fmessage-length 0 -fvisibility hidden -fgnu-runtime -fobjc-runtime-has-arc -fobjc-runtime-has-weak -fobjc-fragile-abi -fexceptions -fdiagnostics-show-option -o unwind-dw2.o -x c /usr/src/gnu/lib/libgcc/../../../contrib/gcc/unwind-dw2.c
clang -cc1 version 3.0 based upon llvm 3.0 hosted on i386-unknown-freebsd9.0
ignoring nonexistent directory "/usr/obj/nanobsd.ALIX/usr/src/tmp/usr/bin/../lib/clang/3.0/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/src/gnu/lib/libgcc/../../../contrib/gcclibs/include
 /usr/src/gnu/lib/libgcc/../../../contrib/gcc/config
 /usr/src/gnu/lib/libgcc/../../../contrib/gcc
 .
 /usr/src/gnu/lib/libgcc/../../usr.bin/cc/cc_tools
 /usr/obj/nanobsd.ALIX//usr/src/tmp/usr/include/clang/3.0
 /usr/obj/nanobsd.ALIX//usr/src/tmp/usr/include
End of search list.
Assertion failed: ((!IntvIn || !LeaveBefore || LeaveBefore > Start) && "Impossible intf"), function splitLiveThroughBlock, file /usr/src/lib/clang/libllvmcodegen/../../../contrib/llvm/lib/CodeGen/SplitKit.cpp, line 1168.
Stack dump:
0.	Program arguments: /usr/obj/nanobsd.ALIX/usr/src/tmp/usr/bin/clang -cc1 -triple i386-unknown-freebsd9.0 -emit-obj -disable-free -main-file-name unwind-dw2.c -pic-level 2 -mdisable-fp-elim -masm-verbose -mconstructor-aliases -target-cpu pentium-mmx -momit-leaf-frame-pointer -v -coverage-file unwind-dw2.o -resource-dir /usr/obj/nanobsd.ALIX/usr/src/tmp/usr/bin/../lib/clang/3.0 -D IN_GCC -D IN_LIBGCC2 -D __GCC_FLOAT_NOT_NEEDED -D HAVE_GTHR_DEFAULT -D HIDE_EXPORTS -D __GLIBC__=3 -D ElfW=__ElfN -I /usr/src/gnu/lib/libgcc/../../../contrib/gcclibs/include -I /usr/src/gnu/lib/libgcc/../../../contrib/gcc/config -I /usr/src/gnu/lib/libgcc/../../../contrib/gcc -I . -I /usr/src/gnu/lib/libgcc/../../usr.bin/cc/cc_tools -fmodule-cache-path /var/tmp/clang-module-cache -Os -std=gnu99 -ferror-limit 19 -fmessage-length 0 -fvisibility hidden -fgnu-runtime -fobjc-runtime-has-arc -fobjc-runtime-has-weak -fobjc-fragile-abi -fexceptions -fdiagnostics-show-option -o unwind-dw2.o -x c /usr/src/gnu/lib/libgcc/../../../contrib/gcc/unwind-dw2.c 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/usr/src/gnu/lib/libgcc/../../../contrib/gcc/unwind-dw2.c'.
4.	Running pass 'Greedy Register Allocator' on function '@uw_frame_state_for'
clang: error: unable to execute command: Abort trap: 6 (core dumped)
clang: error: clang frontend command failed due to signal 2 (use -v to see invocation)
clang: note: diagnostic msg: Please submit a bug report to http://llvm.org/bugs/ and include command line arguments and all diagnostic information.
clang: note: diagnostic msg: Preprocessed source(s) are located at:
clang: note: diagnostic msg: /tmp/unwind-dw2-0YteID.i
*** Error code 254

**Comment by Endilll** [comment]
I can't reproduce this with exactly same `cc1` arguments using assertion builds of Clang 3.0 and 3.1.
