### ISSUE TITLE
Regression Tracker wanted

### ISSUE THREAD

**Issue by tlattner** [llvm/llvm-project#1246]
|  |  |
| --- | --- |
| Bugzilla Link | [874](https://llvm.org/bz874) |
| Version | trunk |
| OS | Linux |

## Extended Description 
It would be nice if the nightly tester could present a list of tests that passed
on date X but failed on date Y. This feature would be used to track regressions
between releases. I don't care if the test failed at any point during the time
span, just the difference between results on day X and day Y. The only potential
issue is that if the test results used llvm-gcc3 during part of the date span
and llvm-gcc4 for the rest, I would prefer to see new regressions for llvm-gcc3
(so only check between the start and end dates using llvm-gcc3) and new
regressions for llvm-gcc4 (start and end dates using llvm-gcc4) as two lists and
not one. This feature should be restricted to only query results from a single
unique machine (ie. only from zion, or persephone, but not together).

**Comment by gwelymernans** [comment]
I think this is taken care of via the current build/test system.
