### ISSUE TITLE
LLVM MC Dissassembler shared library link fail (cmake)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12494]
|  |  |
| --- | --- |
| Bugzilla Link | [12122](https://llvm.org/bz12122) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
With revision r151623, cmake build with shared libraries:

[fangism:src/LLVM-svn/gcc40-cmake-build] fang% cd lib/MC/MCDisassembler/
[fangism:lib/MC/MCDisassembler] fang% !make
make VERBOSE=1 -j1
cd /Users/fang/local/src/LLVM-svn/gcc40-cmake-build && /Volumes/Mercedes2/sw/bin/cmake -H/Users/fang/local/src/LLVM-svn/llvm -B/Users/fang/local/src/LLVM-svn/gcc40-cmake-build --check-build-system CMakeFiles/Makefile.cmake 0
cd /Users/fang/local/src/LLVM-svn/gcc40-cmake-build && /Volumes/Mercedes2/sw/bin/cmake -E cmake_progress_start /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/CMakeFiles /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/MC/MCDisassembler/CMakeFiles/progress.marks
cd /Users/fang/local/src/LLVM-svn/gcc40-cmake-build && make -f CMakeFiles/Makefile2 lib/MC/MCDisassembler/all
make -f lib/Support/CMakeFiles/LLVMSupport.dir/build.make lib/Support/CMakeFiles/LLVMSupport.dir/depend
cd /Users/fang/local/src/LLVM-svn/gcc40-cmake-build && /Volumes/Mercedes2/sw/bin/cmake -E cmake_depends "Unix Makefiles" /Users/fang/local/src/LLVM-svn/llvm /Users/fang/local/src/LLVM-svn/llvm/lib/Support /Users/fang/local/src/LLVM-svn/gcc40-cmake-build /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/Support /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/Support/CMakeFiles/LLVMSupport.dir/DependInfo.cmake --color=
make -f lib/Support/CMakeFiles/LLVMSupport.dir/build.make lib/Support/CMakeFiles/LLVMSupport.dir/build
make[2]: Nothing to be done for `lib/Support/CMakeFiles/LLVMSupport.dir/build'.
/Volumes/Mercedes2/sw/bin/cmake -E cmake_progress_report /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/CMakeFiles  42 43 44 45 46
[ 31%] Built target LLVMSupport
make -f lib/TableGen/CMakeFiles/LLVMTableGen.dir/build.make lib/TableGen/CMakeFiles/LLVMTableGen.dir/depend
cd /Users/fang/local/src/LLVM-svn/gcc40-cmake-build && /Volumes/Mercedes2/sw/bin/cmake -E cmake_depends "Unix Makefiles" /Users/fang/local/src/LLVM-svn/llvm /Users/fang/local/src/LLVM-svn/llvm/lib/TableGen /Users/fang/local/src/LLVM-svn/gcc40-cmake-build /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/TableGen /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/TableGen/CMakeFiles/LLVMTableGen.dir/DependInfo.cmake --color=
make -f lib/TableGen/CMakeFiles/LLVMTableGen.dir/build.make lib/TableGen/CMakeFiles/LLVMTableGen.dir/build
make[2]: Nothing to be done for `lib/TableGen/CMakeFiles/LLVMTableGen.dir/build'.
/Volumes/Mercedes2/sw/bin/cmake -E cmake_progress_report /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/CMakeFiles  47
[ 37%] Built target LLVMTableGen
make -f utils/TableGen/CMakeFiles/llvm-tblgen.dir/build.make utils/TableGen/CMakeFiles/llvm-tblgen.dir/depend
cd /Users/fang/local/src/LLVM-svn/gcc40-cmake-build && /Volumes/Mercedes2/sw/bin/cmake -E cmake_depends "Unix Makefiles" /Users/fang/local/src/LLVM-svn/llvm /Users/fang/local/src/LLVM-svn/llvm/utils/TableGen /Users/fang/local/src/LLVM-svn/gcc40-cmake-build /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/utils/TableGen /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DependInfo.cmake --color=
make -f utils/TableGen/CMakeFiles/llvm-tblgen.dir/build.make utils/TableGen/CMakeFiles/llvm-tblgen.dir/build
make[2]: Nothing to be done for `utils/TableGen/CMakeFiles/llvm-tblgen.dir/build'.
/Volumes/Mercedes2/sw/bin/cmake -E cmake_progress_report /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/CMakeFiles  97 98
[ 50%] Built target llvm-tblgen
make -f include/llvm/CMakeFiles/intrinsics_gen.dir/build.make include/llvm/CMakeFiles/intrinsics_gen.dir/depend
cd /Users/fang/local/src/LLVM-svn/gcc40-cmake-build && /Volumes/Mercedes2/sw/bin/cmake -E cmake_depends "Unix Makefiles" /Users/fang/local/src/LLVM-svn/llvm /Users/fang/local/src/LLVM-svn/llvm/include/llvm /Users/fang/local/src/LLVM-svn/gcc40-cmake-build /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/include/llvm /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/include/llvm/CMakeFiles/intrinsics_gen.dir/DependInfo.cmake --color=
make -f include/llvm/CMakeFiles/intrinsics_gen.dir/build.make include/llvm/CMakeFiles/intrinsics_gen.dir/build
cd /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/include/llvm && /Volumes/Mercedes2/sw/bin/cmake -E copy_if_different /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/include/llvm/Intrinsics.gen.tmp /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/include/llvm/Intrinsics.gen
/Volumes/Mercedes2/sw/bin/cmake -E cmake_progress_report /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/CMakeFiles 
[ 50%] Built target intrinsics_gen
make -f lib/VMCore/CMakeFiles/LLVMCore.dir/build.make lib/VMCore/CMakeFiles/LLVMCore.dir/depend
cd /Users/fang/local/src/LLVM-svn/gcc40-cmake-build && /Volumes/Mercedes2/sw/bin/cmake -E cmake_depends "Unix Makefiles" /Users/fang/local/src/LLVM-svn/llvm /Users/fang/local/src/LLVM-svn/llvm/lib/VMCore /Users/fang/local/src/LLVM-svn/gcc40-cmake-build /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/VMCore /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/VMCore/CMakeFiles/LLVMCore.dir/DependInfo.cmake --color=
make -f lib/VMCore/CMakeFiles/LLVMCore.dir/build.make lib/VMCore/CMakeFiles/LLVMCore.dir/build
make[2]: Nothing to be done for `lib/VMCore/CMakeFiles/LLVMCore.dir/build'.
/Volumes/Mercedes2/sw/bin/cmake -E cmake_progress_report /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/CMakeFiles  24 25 26
[ 68%] Built target LLVMCore
make -f lib/Object/CMakeFiles/LLVMObject.dir/build.make lib/Object/CMakeFiles/LLVMObject.dir/depend
cd /Users/fang/local/src/LLVM-svn/gcc40-cmake-build && /Volumes/Mercedes2/sw/bin/cmake -E cmake_depends "Unix Makefiles" /Users/fang/local/src/LLVM-svn/llvm /Users/fang/local/src/LLVM-svn/llvm/lib/Object /Users/fang/local/src/LLVM-svn/gcc40-cmake-build /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/Object /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/Object/CMakeFiles/LLVMObject.dir/DependInfo.cmake --color=
make -f lib/Object/CMakeFiles/LLVMObject.dir/build.make lib/Object/CMakeFiles/LLVMObject.dir/build
make[2]: Nothing to be done for `lib/Object/CMakeFiles/LLVMObject.dir/build'.
/Volumes/Mercedes2/sw/bin/cmake -E cmake_progress_report /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/CMakeFiles 
[ 68%] Built target LLVMObject
make -f lib/MC/CMakeFiles/LLVMMC.dir/build.make lib/MC/CMakeFiles/LLVMMC.dir/depend
cd /Users/fang/local/src/LLVM-svn/gcc40-cmake-build && /Volumes/Mercedes2/sw/bin/cmake -E cmake_depends "Unix Makefiles" /Users/fang/local/src/LLVM-svn/llvm /Users/fang/local/src/LLVM-svn/llvm/lib/MC /Users/fang/local/src/LLVM-svn/gcc40-cmake-build /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/MC /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/MC/CMakeFiles/LLVMMC.dir/DependInfo.cmake --color=
make -f lib/MC/CMakeFiles/LLVMMC.dir/build.make lib/MC/CMakeFiles/LLVMMC.dir/build
make[2]: Nothing to be done for `lib/MC/CMakeFiles/LLVMMC.dir/build'.
/Volumes/Mercedes2/sw/bin/cmake -E cmake_progress_report /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/CMakeFiles  30 31 32
[ 87%] Built target LLVMMC
make -f lib/MC/MCParser/CMakeFiles/LLVMMCParser.dir/build.make lib/MC/MCParser/CMakeFiles/LLVMMCParser.dir/depend
cd /Users/fang/local/src/LLVM-svn/gcc40-cmake-build && /Volumes/Mercedes2/sw/bin/cmake -E cmake_depends "Unix Makefiles" /Users/fang/local/src/LLVM-svn/llvm /Users/fang/local/src/LLVM-svn/llvm/lib/MC/MCParser /Users/fang/local/src/LLVM-svn/gcc40-cmake-build /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/MC/MCParser /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/MC/MCParser/CMakeFiles/LLVMMCParser.dir/DependInfo.cmake --color=
make -f lib/MC/MCParser/CMakeFiles/LLVMMCParser.dir/build.make lib/MC/MCParser/CMakeFiles/LLVMMCParser.dir/build
make[2]: Nothing to be done for `lib/MC/MCParser/CMakeFiles/LLVMMCParser.dir/build'.
/Volumes/Mercedes2/sw/bin/cmake -E cmake_progress_report /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/CMakeFiles  34
[ 93%] Built target LLVMMCParser
make -f lib/MC/MCDisassembler/CMakeFiles/LLVMMCDisassembler.dir/build.make lib/MC/MCDisassembler/CMakeFiles/LLVMMCDisassembler.dir/depend
cd /Users/fang/local/src/LLVM-svn/gcc40-cmake-build && /Volumes/Mercedes2/sw/bin/cmake -E cmake_depends "Unix Makefiles" /Users/fang/local/src/LLVM-svn/llvm /Users/fang/local/src/LLVM-svn/llvm/lib/MC/MCDisassembler /Users/fang/local/src/LLVM-svn/gcc40-cmake-build /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/MC/MCDisassembler /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/MC/MCDisassembler/CMakeFiles/LLVMMCDisassembler.dir/DependInfo.cmake --color=
make -f lib/MC/MCDisassembler/CMakeFiles/LLVMMCDisassembler.dir/build.make lib/MC/MCDisassembler/CMakeFiles/LLVMMCDisassembler.dir/build
Linking CXX shared library ../../libLLVMMCDisassembler.dylib
cd /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/MC/MCDisassembler && /Volumes/Mercedes2/sw/bin/cmake -E cmake_link_script CMakeFiles/LLVMMCDisassembler.dir/link.txt --verbose=1
/Users/fang/local/bin/ccg++  -fno-common -fPIC -fvisibility-inlines-hidden -fno-rtti  -O3 -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names   -o ../../libLLVMMCDisassembler.dylib -install_name /Users/fang/local/src/LLVM-svn/gcc40-cmake-build/lib/libLLVMMCDisassembler.dylib CMakeFiles/LLVMMCDisassembler.dir/Disassembler.cpp.o CMakeFiles/LLVMMCDisassembler.dir/EDDisassembler.cpp.o CMakeFiles/LLVMMCDisassembler.dir/EDInst.cpp.o CMakeFiles/LLVMMCDisassembler.dir/EDMain.cpp.o CMakeFiles/LLVMMCDisassembler.dir/EDOperand.cpp.o CMakeFiles/LLVMMCDisassembler.dir/EDToken.cpp.o -lpthread ../../libLLVMMC.dylib ../../libLLVMMCParser.dylib ../../libLLVMSupport.dylib ../../libLLVMMC.dylib ../../libLLVMObject.dylib ../../libLLVMCore.dylib ../../libLLVMSupport.dylib -lpthread 
ld: Undefined symbols:
_LLVMInitializeARMAsmParser
_LLVMInitializeARMDisassembler
_LLVMInitializeARMTargetInfo
_LLVMInitializeARMTargetMC
_LLVMInitializePowerPCTargetInfo
_LLVMInitializePowerPCTargetMC
_LLVMInitializeX86AsmParser
_LLVMInitializeX86Disassembler
_LLVMInitializeX86TargetInfo
_LLVMInitializeX86TargetMC
/usr/libexec/gcc/powerpc-apple-darwin8/4.0.1/libtool: internal link edit command failed
make[2]: *** [lib/libLLVMMCDisassembler.dylib] Error 1
make[1]: *** [lib/MC/MCDisassembler/CMakeFiles/LLVMMCDisassembler.dir/all] Error 2
make: *** [all] Error 2

Looks like some dependencies are missing or not listed?

**Comment by arsenm** [comment]
Old build issue
