### ISSUE TITLE
Support CUDA 10.2

### ISSUE THREAD

**Issue by japm48** [llvm/llvm-project#125]
While compiling with CUDA 10.2 I get the following error:
`error: cannot find libdevice for sm_52. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.`

Apparently the problem is that `CudaStringToVersion` returns  `CudaVersion::UNKNOWN`.

Unless I'm missing anything, the addition of `CudaVersion::CUDA_102` after wherever `CUDA_101` is found should be trivial. Of course, with `PtxFeature = "+ptx64"`, as PTX 6.5 can wait.

**Comment by kkwli** [comment]
https://reviews.llvm.org/D74571

**Comment by japm48** [comment]
Well, for the record I managed to make it work without recompiling clang with a very hackish solution.

In case this is useful to someone:
 - Edit `.../cuda/version.txt` to mock CUDA version `10.1.106`.
 - Comment out `#error "Unsupported CUDA version!"` in `__clang_cuda_runtime_wrapper.h`.

Feel free to close the issue or wait until 10.2 (with ptx65, etc.) is properly supported.
