### ISSUE TITLE
fatal error 'cmath' file not found when building llvm for vmkit

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12552]
|  |  |
| --- | --- |
| Bugzilla Link | [12180](https://llvm.org/bz12180) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@efriedma-quic |

## Extended Description 
I wanted to try out llvm-vmkit and followed the steps at this link:
http://vmkit.llvm.org/get_started.html

After checking out llvm and clang, I did a ./configure and make. I get these errors. /home/ganapathy/projects/llvm is the svn trunk check out. Pasting the errors below.

In file included from Atomic.cpp:14:
In file included from /home/ganapathy/projects/llvm/include/llvm/Support/Atomic.h:17:
/home/ganapathy/projects/llvm/include/llvm/Support/DataTypes.h:37:10: fatal error: 'cmath' file not found
#include <cmath>
         ^
1 error generated.
make[1]: *** [/home/ganapathy/projects/llvm/lib/Support/Release+Asserts/Atomic.o] Error 1
make[1]: Leaving directory `/home/ganapathy/projects/llvm/lib/Support'
make: *** [all] Error 1

PS: Since this is a fatal build error, I am setting it to release blocker severity. Not sure how this project uses severity. Thanks

**Comment by asl** [comment]
vmkit is dead
