### ISSUE TITLE
Clang does not use partial specialization

### ISSUE THREAD

**Issue by be579e8c-b74b-475b-a126-3b8cefdd833c** [llvm/llvm-project#12599]
|  |  |
| --- | --- |
| Bugzilla Link | [12227](https://llvm.org/bz12227) |
| Version | trunk |
| OS | Windows NT |
| CC | @DougGregor |

## Extended Description 
I thought this should select the partial specialization (because "K" can be deduced to "{E}"). But clang always selects the primary template of "B":
```c++
template<typename T> struct valid { typedef int type; }; 
template<typename U, typename ...T> struct A { 
  template<typename K> struct B; 
  template<typename ...K, typename valid<K..., T>::type...> 
  struct B<K...> { }; 
}; 

enum E { }; 
A<int>::B<E> a;
```
Clang says: "implicit instantiation of undefined template 'A<int, >::B<E>'". 

This code does not contain a template whose only valid specializations have empty template parameter packs. Hence the template definition itself is well-formed. 

I thought that when "K" is deduced to "{ E }", then we are supposed to substitute it into the latter pack expansion, which results in an empty list of more template parameters.  Hence we have deduced all template parameters and use the partial specialization.

Is there something wrong with my analysis?

**Comment by philnik777** [comment]
Clang and GCC seem to agree that your partial specialization is incorrect: https://godbolt.org/z/h7rKfKfc6.
