### ISSUE TITLE
Overflow builtins

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12662]
|  |  |
| --- | --- |
| Bugzilla Link | [12290](https://llvm.org/bz12290) |
| Version | unspecified |
| OS | All |
| Attachments | [add __overflow_* builtins](https://user-images.githubusercontent.com/60944935/143744936-936b7e06-e395-4558-8d0e-3fa7e27a7532.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lattner,@gottesmm |

## Extended Description 
It would be great if Clang provides builtins to help C/C++ programmers perform overflow checking.  Here's an possible usage, assuming __umuloz(a, b, p) stores the result of size_t multiplication a * b to p and returns 0 if no overflow happens.

void *malloc_array(size_t n, size_t size)
{
	size_t bytes;
	if (__umuloz(n, size, &bytes))
		return NULL;
	return malloc(bytes);
}

Other overflow builtins could include __[s|u][add|sub|mul][16|32|64].

These builtins are convenient to use and less error-prone, compared to popular ad-hoc checks such as (size && n > SIZE_MAX / size).

LLVM (esp. instcombine) doesn't recognize such ad-hoc checking patterns, either, and generates code using div rather than a simple jno.  These builtins could be easily lowered to the LLVM overflow intrinsics llvm.*.with.overflow.* for better code generation.

**Comment by nikic** [comment]
Builtins like __builtin_add_overflow exist nowadays, so closing this.
