### ISSUE TITLE
Web interface should provide access to test logs

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#1273]
|  |  |
| --- | --- |
| Bugzilla Link | [901](https://llvm.org/bz901) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Right now only the build log is accessible via llvm.org/nightlytest. It would be
nice if all the other test logs are made available as well.

**Comment by EugeneZelenko** [comment]
@nunoplopes Please add comment why issue was closed: is it obsolete (and add label)? or where such functionality could be found.

**Comment by nunoplopes** [comment]
website is dead.
