### ISSUE TITLE
Missed constant propagation in loops

### ISSUE THREAD

**Issue by d0k** [llvm/llvm-project#12757]
|  |  |
| --- | --- |
| Bugzilla Link | [12385](https://llvm.org/bz12385) |
| Version | trunk |
| OS | All |
| CC | @atrick,@lattner,@duck-37,@nlewycky,@kaomoneus |

## Extended Description 
From GCC #29738 : 

---8<---
```c++
int i;

void foo (void);
void bar (void)
{
  int j;
  i = 0;
  for (j = 0; j < 10000; j++)
    if (i)
      foo ();
}
```
--->8---

The loop is a nop and should be optimized away, yet clang -O3 doesn't realize that "i" cannot become non-null.

**Comment by philnik777** [comment]
Fixed in LLVM 12: https://godbolt.org/z/EjcPd46fd
