### ISSUE TITLE
Missed optimization opportunity when using the ?: operator.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12765]
|  |  |
| --- | --- |
| Bugzilla Link | [12393](https://llvm.org/bz12393) |
| Version | 3.0 |
| OS | Windows XP |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lattner |

## Extended Description 
The following seemingly identical functions, get compiled to quite
different machine code (one optimized, and the other not).  The first is correctly optimized (the computation of var y is nicely moved into the else branch of the "if" statement), which the second one is not (the full computation of var y is always done).  The output was produced using the demo page on llvm's web site (optimization level LTO).

A simple fix would be for you to lower ?: into an "if" in the front end and since the "if" statement case is optimized you get the optimization for free.

=================================================
int f1(int x) {
  int y = 5*x*x*x+2*x*x+3*x+1;

  if (x > 0)
    return 0;
  else
     return y;
}

int f2(int x) {
  int y = 5*x*x*x+2*x*x+3*x+1;

  return x > 0 ? 0 : y;
}

=================================================

f1:                                     # @&#8203;f1
.Ltmp0:
	.cfi_startproc
# BB#0:
	movl	4(%esp), %ecx
	testl	%ecx, %ecx
	jle	.LBB0_2
# BB#1:
	xorl	%eax, %eax
	ret
.LBB0_2:
	leal	2(%ecx,%ecx,4), %eax
	imull	%ecx, %eax
	addl	$3, %eax
	imull	%ecx, %eax
	incl	%eax
	ret
.Ltmp1:
	.size	f1, .Ltmp1-f1
.Ltmp2:
	.cfi_endproc
.Leh_func_end0:

	.globl	f2
	.align	16, 0x90
	.type	f2,@function
f2:                                     # @&#8203;f2
.Ltmp3:
	.cfi_startproc
# BB#0:
	movl	4(%esp), %eax
	leal	2(%eax,%eax,4), %ecx
	imull	%eax, %ecx
	addl	$3, %ecx
	imull	%eax, %ecx
	incl	%ecx
	testl	%eax, %eax
	movl	$0, %eax
	cmovlel	%ecx, %eax
	ret

**Comment by wheatman** [comment]
I am not able to reproduce this even on version 3.0
https://godbolt.org/z/rdxhn5cWj

code
```
int f1(int x) {
  int y = 5*x*x*x+2*x*x+3*x+1;

  if (x > 0)
    return 0;
  else
     return y;
}

int f2(int x) {
  int y = 5*x*x*x+2*x*x+3*x+1;

  return x > 0 ? 0 : y;
}
```

assembly 

```
f1(int):                                 # @f1(int)
        xor     eax, eax
        test    edi, edi
        jle     .LBB0_1
        ret
.LBB0_1:                                # %if.else
        lea     eax, [rdi + 4*rdi]
        add     eax, 2
        imul    eax, edi
        add     eax, 3
        imul    eax, edi
        inc     eax
        ret
f2(int):                                 # @f2(int)
        lea     ecx, [rdi + 4*rdi]
        add     ecx, 2
        imul    ecx, edi
        add     ecx, 3
        imul    ecx, edi
        inc     ecx
        xor     eax, eax
        test    edi, edi
        cmovle  eax, ecx
        ret
```

The optimizations seem about the same just with different assumptions about how often the condition will be true, in the first case it gets more likely, in the second case it is not more likely, which is what I would assume based on the use of the ternary operator
