### ISSUE TITLE
Build a push mechanism for notifying the world about new SVN revisions

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12780]
|  |  |
| --- | --- |
| Bugzilla Link | [12408](https://llvm.org/bz12408) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 
Because we (and anybody who has to read the llvm.org web server logs) hate polling, we should have some kind of push notifications when SVN commits happen. Off the top of my head, something built on top of RSS and PubSubHubbub (http://code.google.com/p/pubsubhubbub/) might do the trick.

**Comment by tlattner** [comment]
We moved to GitHub, closing this.
