### ISSUE TITLE
Polyhedron 2005 benchmark failures with -O2 -ftree-vectorize -fplugin-arg-dragonegg-enable-gcc-optzns

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12806]
|  |  |
| --- | --- |
| Bugzilla Link | [12434](https://llvm.org/bz12434) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
A number of Polyhedron 2005 benchmarks are now failing when compiled with -O2 -ftree-vectorize -fplugin-arg-dragonegg-enable-gcc-optzns on x86_64-apple-darwin11 at revision 153840. One example is doduc which when compiled with...

de-gfortran46 -msse4 -O2 -ftree-vectorize -fplugin-arg-dragonegg-enable-gcc-optzns -g doduc.f90 -o doduc

fails as...

% ./doduc
 MAIN : FIN S00002
 MAIN : FIN S00001
Illegal instruction

and backtraces in lldb as...

% lldb ./doduc
Current executable set to './doduc' (x86_64).
(lldb) r
Process 12839 launched: '/Users/howarth/Downloads/pb05/lin/source/doduc' (x86_64)
 MAIN : FIN S00002
 MAIN : FIN S00001
Process 12839 stopped
* thread #&#8203;1: tid = 0x1f03, 0x0000000100011d31 doduc`s00011_ + 2065 at doduc.f90:2949, stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #&#8203;0: 0x0000000100011d31 doduc`s00011_ + 2065 at doduc.f90:2949
   2946	                  I6Ft = i
   2947	                  J6Ft = j
   2948	               ENDIF
-> 2949	               IF ( z8.LE.zmax ) THEN
   2950	                  I8Ft = i
   2951	                  J8Ft = j
   2952	                  GOTO 200
(lldb) bt
* thread #&#8203;1: tid = 0x1f03, 0x0000000100011d31 doduc`s00011_ + 2065 at doduc.f90:2949, stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #&#8203;0: 0x0000000100011d31 doduc`s00011_ + 2065 at doduc.f90:2949
    frame #&#8203;1: 0x0000000100019056 doduc`main [inlined] MAIN__ + 439 at doduc.f90:169
    frame #&#8203;2: 0x0000000100018e9f doduc`main + 79 at doduc.f90:199
    frame #&#8203;3: 0x0000000100000d94 doduc`start + 52
(lldb) 

using lldb from Xcode 4.3.2. The other Polyhedron 2005 benchmarks exhibiting this failure include fatigue and test_fpu

**Comment by arsenm** [comment]
Dragonegg is obsolete
