### ISSUE TITLE
[meta] Support Microsoft C++ ABI

### ISSUE THREAD

**Issue by timurrrr** [llvm/llvm-project#12849]
|  |  |
| --- | --- |
| Bugzilla Link | [12477](https://llvm.org/bz12477) |
| Version | unspecified |
| OS | Windows NT |
| Depends On | llvm/llvm-bugzilla-archive#17152 llvm/llvm-bugzilla-archive#18126 llvm/llvm-bugzilla-archive#19398 llvm/llvm-bugzilla-archive#21022 llvm/llvm-bugzilla-archive#23549 llvm/llvm-project#5430 llvm/llvm-project#5436 llvm/llvm-project#9585 llvm/llvm-project#9649 llvm/llvm-project#11777 llvm/llvm-project#12161 llvm/llvm-project#12219 llvm/llvm-project#12413 llvm/llvm-project#12446 llvm/llvm-project#12488 llvm/llvm-project#12704 llvm/llvm-project#12705 llvm/llvm-project#12708 llvm/llvm-bugzilla-archive#12535 llvm/llvm-bugzilla-archive#12594 llvm/llvm-bugzilla-archive#12603 llvm/llvm-bugzilla-archive#12631 llvm/llvm-bugzilla-archive#12648 llvm/llvm-bugzilla-archive#12701 llvm/llvm-bugzilla-archive#12709 llvm/llvm-bugzilla-archive#12715 llvm/llvm-bugzilla-archive#12749 llvm/llvm-bugzilla-archive#12783 llvm/llvm-bugzilla-archive#12784 llvm/llvm-bugzilla-archive#12785 llvm/llvm-bugzilla-archive#12974 llvm/llvm-bugzilla-archive#13022 llvm/llvm-bugzilla-archive#13047 llvm/llvm-bugzilla-archive#13153 llvm/llvm-bugzilla-archive#13158 llvm/llvm-bugzilla-archive#13176 llvm/llvm-bugzilla-archive#13177 llvm/llvm-bugzilla-archive#13182 llvm/llvm-bugzilla-archive#13207 llvm/llvm-bugzilla-archive#13231 llvm/llvm-bugzilla-archive#13232 llvm/llvm-bugzilla-archive#13344 llvm/llvm-bugzilla-archive#13389 llvm/llvm-bugzilla-archive#13434 llvm/llvm-bugzilla-archive#13443 llvm/llvm-bugzilla-archive#13444 llvm/llvm-bugzilla-archive#13455 llvm/llvm-bugzilla-archive#13457 llvm/llvm-bugzilla-archive#13488 llvm/llvm-bugzilla-archive#13676 llvm/llvm-bugzilla-archive#13761 llvm/llvm-bugzilla-archive#13782 llvm/llvm-bugzilla-archive#13792 llvm/llvm-bugzilla-archive#13984 llvm/llvm-bugzilla-archive#14006 llvm/llvm-bugzilla-archive#14104 llvm/llvm-bugzilla-archive#14410 llvm/llvm-bugzilla-archive#14413 llvm/llvm-bugzilla-archive#15058 llvm/llvm-bugzilla-archive#15512 llvm/llvm-bugzilla-archive#15556 llvm/llvm-bugzilla-archive#15768 llvm/llvm-bugzilla-archive#15875 llvm/llvm-bugzilla-archive#15900 llvm/llvm-bugzilla-archive#16096 llvm/llvm-bugzilla-archive#16233 llvm/llvm-bugzilla-archive#16406 llvm/llvm-bugzilla-archive#16459 llvm/llvm-bugzilla-archive#16655 llvm/llvm-bugzilla-archive#16735 llvm/llvm-bugzilla-archive#16759 llvm/llvm-bugzilla-archive#16788 llvm/llvm-bugzilla-archive#16789 llvm/llvm-bugzilla-archive#16832 llvm/llvm-bugzilla-archive#16835 llvm/llvm-bugzilla-archive#16836 llvm/llvm-bugzilla-archive#16844 llvm/llvm-bugzilla-archive#16848 llvm/llvm-bugzilla-archive#16853 llvm/llvm-bugzilla-archive#16887 llvm/llvm-bugzilla-archive#16888 llvm/llvm-bugzilla-archive#16959 llvm/llvm-bugzilla-archive#16994 llvm/llvm-bugzilla-archive#17034 llvm/llvm-bugzilla-archive#17100 llvm/llvm-bugzilla-archive#17157 llvm/llvm-bugzilla-archive#17161 llvm/llvm-bugzilla-archive#17273 llvm/llvm-bugzilla-archive#17371 llvm/llvm-bugzilla-archive#17382 llvm/llvm-bugzilla-archive#17514 llvm/llvm-bugzilla-archive#17738 llvm/llvm-bugzilla-archive#17748 llvm/llvm-bugzilla-archive#17750 llvm/llvm-bugzilla-archive#17761 llvm/llvm-bugzilla-archive#17767 llvm/llvm-bugzilla-archive#17768 llvm/llvm-bugzilla-archive#17772 llvm/llvm-bugzilla-archive#17816 llvm/llvm-bugzilla-archive#18021 llvm/llvm-bugzilla-archive#18022 llvm/llvm-bugzilla-archive#18024 llvm/llvm-bugzilla-archive#18025 llvm/llvm-bugzilla-archive#18026 llvm/llvm-bugzilla-archive#18027 llvm/llvm-bugzilla-archive#18035 llvm/llvm-bugzilla-archive#18039 llvm/llvm-bugzilla-archive#18118 llvm/llvm-bugzilla-archive#18131 llvm/llvm-bugzilla-archive#18167 llvm/llvm-bugzilla-archive#18168 llvm/llvm-bugzilla-archive#18169 llvm/llvm-bugzilla-archive#18170 llvm/llvm-bugzilla-archive#18172 llvm/llvm-bugzilla-archive#18173 llvm/llvm-bugzilla-archive#18175 llvm/llvm-bugzilla-archive#18186 llvm/llvm-bugzilla-archive#18204 llvm/llvm-bugzilla-archive#18215 llvm/llvm-bugzilla-archive#18216 llvm/llvm-bugzilla-archive#18248 llvm/llvm-bugzilla-archive#18264 llvm/llvm-bugzilla-archive#18278 llvm/llvm-bugzilla-archive#18433 llvm/llvm-bugzilla-archive#18434 llvm/llvm-bugzilla-archive#18435 llvm/llvm-bugzilla-archive#18436 llvm/llvm-bugzilla-archive#18437 llvm/llvm-bugzilla-archive#18444 llvm/llvm-bugzilla-archive#18464 llvm/llvm-bugzilla-archive#18467 llvm/llvm-bugzilla-archive#18474 llvm/llvm-bugzilla-archive#18476 llvm/llvm-bugzilla-archive#18479 llvm/llvm-bugzilla-archive#18617 llvm/llvm-bugzilla-archive#18618 llvm/llvm-bugzilla-archive#18675 llvm/llvm-bugzilla-archive#18692 llvm/llvm-bugzilla-archive#18694 llvm/llvm-bugzilla-archive#18702 llvm/llvm-bugzilla-archive#18826 llvm/llvm-bugzilla-archive#18844 llvm/llvm-bugzilla-archive#18845 llvm/llvm-bugzilla-archive#18880 llvm/llvm-bugzilla-archive#18902 llvm/llvm-bugzilla-archive#18917 llvm/llvm-bugzilla-archive#18951 llvm/llvm-bugzilla-archive#18967 llvm/llvm-bugzilla-archive#19012 llvm/llvm-bugzilla-archive#19025 llvm/llvm-bugzilla-archive#19066 llvm/llvm-bugzilla-archive#19104 llvm/llvm-bugzilla-archive#19172 llvm/llvm-bugzilla-archive#19180 llvm/llvm-bugzilla-archive#19181 llvm/llvm-bugzilla-archive#19240 llvm/llvm-bugzilla-archive#19361 llvm/llvm-bugzilla-archive#19399 llvm/llvm-bugzilla-archive#19407 llvm/llvm-bugzilla-archive#19408 llvm/llvm-bugzilla-archive#19413 llvm/llvm-bugzilla-archive#19414 llvm/llvm-bugzilla-archive#19487 llvm/llvm-bugzilla-archive#19505 llvm/llvm-bugzilla-archive#19506 llvm/llvm-bugzilla-archive#19733 llvm/llvm-bugzilla-archive#20017 llvm/llvm-bugzilla-archive#20047 llvm/llvm-bugzilla-archive#20221 llvm/llvm-bugzilla-archive#20315 llvm/llvm-bugzilla-archive#20337 llvm/llvm-bugzilla-archive#20343 llvm/llvm-bugzilla-archive#20346 llvm/llvm-bugzilla-archive#20351 llvm/llvm-bugzilla-archive#20418 llvm/llvm-bugzilla-archive#20444 llvm/llvm-bugzilla-archive#20464 llvm/llvm-bugzilla-archive#20477 llvm/llvm-bugzilla-archive#20479 llvm/llvm-bugzilla-archive#20653 llvm/llvm-bugzilla-archive#20719 llvm/llvm-bugzilla-archive#20897 llvm/llvm-bugzilla-archive#20947 llvm/llvm-bugzilla-archive#21031 llvm/llvm-bugzilla-archive#21046 llvm/llvm-bugzilla-archive#21060 llvm/llvm-bugzilla-archive#21061 llvm/llvm-bugzilla-archive#21062 llvm/llvm-bugzilla-archive#21064 llvm/llvm-bugzilla-archive#21073 llvm/llvm-bugzilla-archive#21074 llvm/llvm-bugzilla-archive#21164 llvm/llvm-bugzilla-archive#21888 llvm/llvm-bugzilla-archive#22840 llvm/llvm-bugzilla-archive#23325 llvm/llvm-bugzilla-archive#23452 llvm/llvm-bugzilla-archive#27621 llvm/llvm-bugzilla-archive#28223 llvm/llvm-bugzilla-archive#37465  |
| Blocks | llvm/llvm-bugzilla-archive#13707  |
| CC | @XVilka,@asl,@compnerd,@majnemer,@DougGregor,@zmodem,@tritao,@pageexec,@timurrrr |

## Extended Description 
This is a meta bug to cover all known Clang vs Microsoft C++ ABI incompatibility / unsupportness.

**Comment by philnik777** [comment]
This is broken for GitHub, so I'm closing it. I also don't think that this is relevant anymore. AFAIK the Microsoft ABI is mostly working in Clang.
