### ISSUE TITLE
Support a nice (potentially git-based) viewer for code/commits

### ISSUE THREAD

**Issue by chandlerc** [llvm/llvm-project#12856]
|  |  |
| --- | --- |
| Bugzilla Link | [12484](https://llvm.org/bz12484) |
| Version | unspecified |
| OS | All |
| CC | @asl,@lattner,@jryans |

## Extended Description 
My suggestion:

https://github.com/jonashaag/klaus

It's Python, WSGI based, so no crazy new technologies. It's not flashy, or gimmicky. It's dead simple, but also really easy to navigate and pretty. =]

In particular it has much more useful views of commits and of code which are useful when sending links around pointing at code.

**Comment by philnik777** [comment]
Given that the repo is hosted on GitHub now, I think this is completed.
