### ISSUE TITLE
fatal error: error in backend: ran out of registers during register allocation

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12862]
|  |  |
| --- | --- |
| Bugzilla Link | [12490](https://llvm.org/bz12490) |
| Version | 3.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@efriedma-quic,@stoklund |

## Extended Description 
I has tryed to build qt4.8.1 with clang, on Ubuntu 11.10, 32bit
the optimization level "O3" is succeeded, but "Oz" or "Os", clang failed with the follow information:

fatal error: error in backend: ran out of registers during register allocation
fatal error: error in backend: ran out of registers during register allocation
make[1]: *** [.obj/release-shared/qdrawhelper_mmx.o] error 1
make[1]: *** [.obj/release-shared/qdrawhelper_mmx3dnow.o] error 1
fatal error: error in backend: ran out of registers during register allocation
make[1]: *** [.obj/release-shared/qdrawhelper_sse3dnow.o] error 1
fatal error: error in backend: ran out of registers during register allocation
make[1]: *** [.obj/release-shared/qdrawhelper_sse.o] error 1
make: *** [sub-gui-make_default-ordered] error 2

**Comment by nickdesaulniers** [comment]
I had to modify the "[Reduced Bitcode](https://user-images.githubusercontent.com/92601353/143745062-a27992b3-4757-45fa-987d-c1199db1bc04.gz)" to declare `_ZL35rasterop_solid_SourceAndDestinationI14QMMXIntrinsicsEvPjijj`, but could no longer reproduce the issue on llc-15:
```llvm
target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:32:32-n8:16:32-S128"
target triple = "i386-pc-linux-gnu"

declare void @_ZL35rasterop_solid_SourceAndDestinationI14QMMXIntrinsicsEvPjijj(i32* inreg %x, i32 inreg %y, i32 inreg %z, i32 %w)

define internal void @_ZL38rasterop_solid_NotSourceAndDestinationI14QMMXIntrinsicsEvPjijj(i32* inreg %dest, i32 inreg %length, i32 inreg %color, i32 %const_alpha) nounwind optsize {
entry:
  tail call void @_ZL35rasterop_solid_SourceAndDestinationI14QMMXIntrinsicsEvPjijj(i32* inreg %dest, i32 inreg %length, i32 inreg 0, i32 %const_alpha) optsize
  ret void
}
```
```sh
$ llc -relocation-model=pic 143745062-a27992b3-4757-45fa-987d-c1199db1bc04
$
```
The other attachments are double gzipped tarballs (from the bugzilla -> github migration). qdrawhelper_sse3dnow.i had too many compile time errors that we never made it past Sema.

Closing as obsolete. Please file a new bug with newer test cases if still reproducible.
