### ISSUE TITLE
Array type qualifiers only allowed in function parameters

### ISSUE THREAD

**Issue by tobiasgrosser** [llvm/llvm-project#12876]
|  |  |
| --- | --- |
| Bugzilla Link | [12504](https://llvm.org/bz12504) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Following the C standard:

=============================
6.7.5.2 Array declarators 

Constraints

In addition to optional type qualifiers and the keyword static, the [ and ] may delimit an expression or *. If they delimit an expression (which specifies the size of an array), the expression shall have an integer type. If the expression is a constant expression, it shall have a value greater than zero. The element type shall not be an incomplete or function type. The optional type qualifiers and the keyword static shall appear only in a declaration of a function parameter with an array type, and then only in the outermost array type derivation.
=============================

I am allowed to use static/restrict in a function parameter but not within a function:

========================
void f_restrict(float A[restrict 10]) { // valid
        float B[restrict 10];           // invalid
}
void f_static(float A[static 10]) {     // valid
        float B[static 10];             // invalid
}
========================

gcc gets it right (icc too):

gcc /tmp/test.c -c -std=gnu99
/tmp/test.c: In function ‘f_restrict’:
/tmp/test.c:2:8: error: static or type qualifiers in non-parameter array declarator
/tmp/test.c: In function ‘f_static’:
/tmp/test.c:5:8: error: static or type qualifiers in non-parameter array declarator

**Comment by AaronBallman** [comment]
This was fixed in Clang 3.3: https://gcc.godbolt.org/z/E9z1q8f4v
