### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by asl** [llvm/llvm-project#12872]
|  |  |
| --- | --- |
| Bugzilla Link | [12500](https://llvm.org/bz12500) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor,@rjmccall |

## Extended Description 
Consider the following code:

namespace Foo {
  class Bar;
}

namespace Baz {
  class Foo::Bar;
  class Quuz {
    Foo::Bar *b;
  };
}

Right now clang emits an error "definition or redeclaration of 'Bar' not in a namespace enclosing Foo" which for me seems a bit misleading. Maybe it should be "Baz" does not enclose "Foo" ? Also, here fixit class => using makes sense.

**Comment by philnik777** [comment]
I don't think this ever made it into a release.
