### ISSUE TITLE
overload resolution incorrectly checking whether an implicit conversion sequence from initializer list to reference-to-array is viable

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#12884]
|  |  |
| --- | --- |
| Bugzilla Link | [12512](https://llvm.org/bz12512) |
| Version | unspecified |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
g++ accepts this code, but Clang rejects it claiming there is an ambiguity:

int f(const int (&x)[3]) { return x[0] + x[1] + x[2]; }
int f(const int (&x)[2]) = delete;
int k = f({1, 2, 3});

The second 'f' should not be viable: there is no implicit conversion sequence which converts {1, 2, 3} to const int (&)[2].

13.3.3.1.5/2 and 13.3.2/3 don't make it especially clear whether this should be valid, but 13.3.2/3's requirement that "there shall exist for each argument an implicit conversion sequence (13.3.3.1) that converts that argument to the corresponding parameter of F" does not appear to be met: the conversion sequence defined in 13.3.3.1.5/2 can't convert the argument to the right type.

[The related program:

int f(const int (&x)[2]);
int k = f({1, 2, 3});

is rejected, though strangely produces a note twice:

<stdin>:1:38: error: reference to type 'const int [2]' could not bind to an rvalue of type 'int'
int f(const int (&x)[2]); int k = f({1, 2, 3});
                                     ^
<stdin>:1:19: note: passing argument to parameter 'x' here
int f(const int (&x)[2]); int k = f({1, 2, 3});
                  ^
<stdin>:1:19: note: passing argument to parameter 'x' here]

**Comment by shafik** [comment]
Given:

```cpp
```

**Comment by Endilll** [comment]
Thank you!
