### ISSUE TITLE
clang fails to consider inheritance-path access control for implicit calls to special members of virtual bases

### ISSUE THREAD

**Issue by rjmccall** [llvm/llvm-project#12880]
|  |  |
| --- | --- |
| Bugzilla Link | [12508](https://llvm.org/bz12508) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
clang needs to be considering whether the inheritance path to a virtual base constrains access when checking implicit calls to special members in the following cases:
  - when deciding whether or not to define an implicit member as deleted (in C++11)
  - when initializing a base-class subobject in a ctor
  - when checking access to subobject destructors in a ctor/dtor

As examples, I believe each of the following cases is ill-formed:
```cpp
  struct A {
    A(); A(const A&); ~A();
  };
  class B : private virtual A {};

  class C : public B {
    C() : A() {} // explicit base init, implicit base destroy
    C(int) {} // implicit base init, implicit base destroy
    ~C() {} // implicit base destroy
  };

  class D {
    // In C++11, the implicit dtor, default ctor, and copy ctor here should all be defined as deleted
  };
```
It looks like we currently get the explicit base-init case right, but not the others.

**Comment by shafik** [comment]
It looks like clang rejects all of these now, the rest of the implementation will either reject it outright of reject when we attempt to instantiate.
