### ISSUE TITLE
clang Makefile for include/clang and include/clang-c has broken find pipeline

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12890]
|  |  |
| --- | --- |
| Bugzilla Link | [12518](https://llvm.org/bz12518) |
| Version | 3.0 |
| OS | Solaris |
| Attachments | [The attached patch both backports trunk changes for these Makefiles to 3.0 and adds the fixes.](https://user-images.githubusercontent.com/60944935/143745083-b73ab8b2-1427-479a-856b-3fd796c5b54d.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

The Makefiles for the clang and clang-c headers error out when using a separate build tree because a find that won't find anything is piped into a series of greps. grep will return 1 if it's invoked with no input (which will happen in you're looking for include files to install in the object tree, as these only exist in the source tree), even if it's a negative grep (-v). As this is being used to define the list for a for loop, the simple solution is to terminate the pipeline with "|| /usr/bin/true" so that the pipeline doesn't error out and fail the target.

As the attached patch also backports trunk changes to 3.0, I can confirm that this isn't resolved in the trunk.

**Comment by cor3ntin** [comment]
We no longer have Makefiles, closing
