### ISSUE TITLE
Unhelpful "did you mean" for mistyped template

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#12919]
|  |  |
| --- | --- |
| Bugzilla Link | [12547](https://llvm.org/bz12547) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
The following code:
```c++
#include <vector>

int main(void)
{
  std:vector<int> v;
}
```
Produces the error:
```
/Users/caj/temp/temp.cc:5:9: error: no template named 'vector'; did you mean 'std::vector'?
    std:vector<int> v;
        ^~~~~~
        std::vector
```

It took me a good couple of minutes to figure out what the actual problem was (there is only a single : )
Chris

**Comment by philnik777** [comment]
I'm not sure why this is unhelpful. I think the error message is pretty clear.

**Comment by Endilll** [comment]
Duplicate of #13406
