### ISSUE TITLE
Regression(r154816): clang produces chromium binaries that are 0.875 MB (1.4%) larger than clang 154815

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#13017]
|  |  |
| --- | --- |
| Bugzilla Link | [12645](https://llvm.org/bz12645) |
| Version | unspecified |
| OS | All |
| CC | @chandlerc |

## Extended Description 
See http://build.chromium.org/f/chromium/perf/mac-release/sizes/report.html?history=150&rev=133696&graph=ChromiumFramework

**Comment by arsenm** [comment]
Too old to be useful
