### ISSUE TITLE
"conflicting types for function declaration" error is not triggered for builtin functions

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13026]
|  |  |
| --- | --- |
| Bugzilla Link | [12654](https://llvm.org/bz12654) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

**Comment by AaronBallman** [comment]
This issue should now be fixed by https://reviews.llvm.org/rG385e7df33046d7292612ee1e3ac00a59d8bc0441
