### ISSUE TITLE
clang should have a fixit for missing typename in sizeof expressions

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#13023]
|  |  |
| --- | --- |
| Bugzilla Link | [12651](https://llvm.org/bz12651) |
| Version | unspecified |
| OS | Windows NT |
| CC | @DougGregor,@zygoloid |

## Extended Description 
clang suggests missing "typename"s almost everywhere. It doesn't in this case:

C:\src\chrome\src>type test2.cc
```c++
template<class T>
int f(const T& unused) {
  return sizeof(T::a);
}

struct A {
  typedef int a;
};

int g() {
  A a;
  return f(a);
}
```
C:\src\chrome\src>..\..\llvm-build\bin\Release\clang.exe -c test2.cc
```c++
test2.cc:3:20: error: unexpected type name 'a': expected expression
  return sizeof(T::a);
                   ^
test2.cc:12:10: note: in instantiation of function template specialization 'f<A>' requested here
  return f(a);
         ^
1 error generated.
```

**Comment by philnik777** [comment]
Fixed in Clang 3.4: https://godbolt.org/z/srqK9afqd
