### ISSUE TITLE
Failure to diagnose violation of C99 6.7.5.2 constraint

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13035]
|  |  |
| --- | --- |
| Bugzilla Link | [12663](https://llvm.org/bz12663) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [test case](https://user-images.githubusercontent.com/60944935/143745181-b9ae4a85-bf0a-4ab7-a393-1af671a74f8c.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @seanm |

## Extended Description 

clang version 3.1 (branches/release_31 154941)

C99 6.7.5.2 constrains the array declaration syntax.
http://c0x.coding-guidelines.com/6.7.5.2.html

But clang fails to diagnose the violations for the following code:

struct { int i; char a[static 5]; } s;

void foo(int n[][restrict static 3]){
}

gcc  -std=c99 -pedantic -c c99_6752.c 
c99_6752.c:1: error: static or type qualifiers in non-parameter array declarator
c99_6752.c:3: error: static or type qualifiers in non-parameter array declarator

**Comment by AaronBallman** [comment]
This issue was fixed in Clang 3.2: https://gcc.godbolt.org/z/csYWdTr4z
