### ISSUE TITLE
clang fails to detect invalid application of "sizeof" to an incomplete type when there is a complete type in different scope

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13033]
|  |  |
| --- | --- |
| Bugzilla Link | [12661](https://llvm.org/bz12661) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [test case](https://user-images.githubusercontent.com/60944935/143745178-bbb027ec-9642-4ac8-b8b4-5478265a293e.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie,@zygoloid,@zahiraam |

## Extended Description 

Clang accepts the following erroneous code:

void bar(int);
int foo()
{
  extern int arr[];
  { extern int arr[10]; }
  bar(sizeof(arr)); /* should raise error here */
  return 0;
}

GCC will report the error:
size_of_incomp.c: In function 'foo':
size_of_incomp.c:6: error: invalid application of 'sizeof' to incomplete type 'int[]'

**Comment by AaronBallman** [comment]
This was resolved in Clang 3.3: https://gcc.godbolt.org/z/nz3MbrsaW
