### ISSUE TITLE
chrome crashes when google-perftools is compiled with clang

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13051]
|  |  |
| --- | --- |
| Bugzilla Link | [12679](https://llvm.org/bz12679) |
| Version | 3.0 |
| OS | FreeBSD |
| Attachments | [More info](https://user-images.githubusercontent.com/60944935/143745193-935948ac-a7cb-4a04-b553-a0927df3e198.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

When google-perftools is compiled with clang, the chrome web browser crashes on startup.  It does not when compiled with GCC 4.2 (the old one in the FreeBSD base system).  It also apparently does not at -O1, so this maybe be a code generation bug.

Please see the attached file for some more info.  There is also an issue open on the gperftools site:  http://code.google.com/p/gperftools/issues/detail?id=394&redir=1

Marcus Reid

**Comment by Endilll** [comment]
Author hasn't got back to us with more information.
