### ISSUE TITLE
DSA does not recognize the poolcheckstr() run-time check

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13090]
|  |  |
| --- | --- |
| Bugzilla Link | [12718](https://llvm.org/bz12718) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
DSA's StdLib pass should be taught how to recognize the poolcheckstr() family of run-time checks in SAFECode.

**Comment by arsenm** [comment]
DSA is gone
