### ISSUE TITLE
SAFECode should treat getenv() as an allocator

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13111]
|  |  |
| --- | --- |
| Bugzilla Link | [12739](https://llvm.org/bz12739) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
SAFECode should treat the getenv() function as an allocator (although this may be unnecessary on some systems if getenv() merely returns a pointer already registered as an environment argument to main()).

**Comment by Endilll** [comment]
SAFECode is archived.
