### ISSUE TITLE
Error recovery can trigger  Assertion `i < getNumParams() && "Illegal param #"' (Decl.h:1820)

### ISSUE THREAD

**Issue by hfinkel** [llvm/llvm-project#13150]
|  |  |
| --- | --- |
| Bugzilla Link | [12778](https://llvm.org/bz12778) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced test case (provided by C.S.)](https://user-images.githubusercontent.com/910929/143745271-d81de377-74f0-4058-b3e9-3db7e661d7a2.gz) |
| CC | @DougGregor |

## Extended Description 

Running clang trunk on x86_64 on:

 void operator delete() throw(void*);
           pointer allocate(size_type __n, const void* = 0) {
   return static_cast<_Tp*>(::operator new(__n * sizeof(_Tp)));

results in:

In file included from prog.cpp:1:
prog.cpp:1:7: error: 'operator delete' must have at least one parameter.
 void operator delete() throw(void*);
      ^
prog.cpp:2:12: error: unknown type name 'pointer'
           pointer allocate(size_type __n, const void* = 0) {
           ^
prog.cpp:2:29: error: unknown type name 'size_type'
           pointer allocate(size_type __n, const void* = 0) {
                            ^
prog.cpp:3:23: error: unknown type name '_Tp'
   return static_cast<_Tp*>(::operator new(__n * sizeof(_Tp)));
                      ^
clang: /src/llvm-trunk-writable/tools/clang/lib/Sema/../../include/clang/AST/Decl.h:1820: clang::ParmVarDecl* clang::FunctionDecl::getParamDecl(unsigned int): Assertion `i < getNumParams() && "Illegal param #"' failed.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.4: https://godbolt.org/z/zGzKb14xK
