### ISSUE TITLE
Possible infinite loop in compile

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13164]
|  |  |
| --- | --- |
| Bugzilla Link | [12792](https://llvm.org/bz12792) |
| Version | 3.0 |
| OS | Linux |
| Attachments | [bzip2 compressed source code file.](https://user-images.githubusercontent.com/60944935/143745283-e224fd25-b1bc-41c2-af61-9c44ccfa1144.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @nico |

## Extended Description 

I ran into what seems to be an infinite loop trying to compile the attached code. I let it run for at least 30 minutes before killing it.

Here's the command:
clang -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mudd/pkgs/Python-2.7.2.install/include/python2.7 -c drug_table.c -o build/temp.linux-i686-2.7/drug_table.o

It's not necessarily a clang bug. I tried with gcc and got the following output after about 10 minutes of compiling. It (gcc) did produce a .o output file.

gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mudd/pkgs/Python-2.7.2.install/include/python2.7 -c drug_table.c -o build/temp.linux-i686-2.7/drug_table.o
drug_table.c: In function ‘initdrug_table’:
drug_table.c:81869:16: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without

Note: The program is the output of a Python program that has been translated to C via Cython compiler.

$ clang --version
clang version 3.0 (tags/RELEASE_30/final)
Target: i386-pc-linux-gnu
Thread model: posix
$
$ gcc --version
gcc (Ubuntu/Linaro 4.6.1-9ubuntu3) 4.6.1
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$
$ uname -a
Linux mudd-PC 3.0.0-19-generic-pae #&#8203;33-Ubuntu SMP Thu Apr 19 20:59:10 UTC 2012 i686 i686 i386 GNU/Linux
$

**Comment by arsenm** [comment]
Assuming this was fixed based on last comment, testcase isn't self contained and depends on old python headers
