### ISSUE TITLE
odd crash from linker

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#13174]
|  |  |
| --- | --- |
| Bugzilla Link | [12802](https://llvm.org/bz12802) |
| Version | trunk |
| OS | Linux |

## Extended Description 
[regehr@dyson r45]$ clang  -O0 small.c
[regehr@dyson r45]$ clang  -O1 small.c
/tmp/small-GNORdv.o: In function `fn1':
small.c:(.text+0x2f): relocation truncated to fit: R_X86_64_32 against symbol `d' defined in .bss section in /tmp/small-GNORdv.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[regehr@dyson r45]$ cat small.c
short a;
int b;
char c;
int d[][81] = {
};
void
fn1 ()
{
    char *e = &c;
    for (;;)
    {
        if (b)
            continue;
        a = 0;
        for (; a >= 0; a--)
        {
            if (b)
                break;
            *e = d[a][0];
        }
    }
}

int main (void)
{
}
[regehr@dyson r45]$ clang -v
clang version 3.2 (trunk 156655)
Target: x86_64-unknown-linux-gnu
Thread model: posix

**Comment by Endilll** [comment]
The original test case appears to be fixed in Clang 3.9: https://godbolt.org/z/K9PWfKPTa
The second and the third test cases appear to be fixed in Clang 12:
https://godbolt.org/z/6xh8q1vcq
https://godbolt.org/z/xnY1WbPTo
