### ISSUE TITLE
Assertion `NextFieldOffset <= RecordSize && "Size mismatch!"'

### ISSUE THREAD

**Issue by hfinkel** [llvm/llvm-project#13189]
|  |  |
| --- | --- |
| Bugzilla Link | [12817](https://llvm.org/bz12817) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced test case (provided by Craig Schroeder)](https://user-images.githubusercontent.com/910929/143745306-0ae12bfb-902b-45af-8953-0b12c978a025.gz) |
| CC | @DougGregor,@efriedma-quic |

## Extended Description 

Running clang trunk on:

struct s1 {long a[-6 / (8 * sizeof (long))];};struct s2 {int b;struct
s1 c;};struct s3 {struct s2 d[1];};struct s3 * e;

results in:

clang: /src/llvm-trunk-writable/tools/clang/lib/CodeGen/CGRecordLayoutBuilder.cpp:868: void<unnamed>::CGRecordLayoutBuilder::AppendTailPadding(clang::CharUnits): Assertion `NextFieldOffset <= RecordSize && "Size mismatch!"' failed.

FWIW, gcc 4.4.3 accepts this without error or warning.

**Comment by Endilll** [comment]
Appears to be fixed on trunk after Clang 16:
https://cexplorer.testlabs.pro/z/3hPxh1
https://godbolt.org/z/eWPToadjP
