### ISSUE TITLE
hangs in TextDiagnostic::buildFixItInsertionLine on invalid input

### ISSUE THREAD

**Issue by hfinkel** [llvm/llvm-project#13186]
|  |  |
| --- | --- |
| Bugzilla Link | [12814](https://llvm.org/bz12814) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced test case (provided by Craig Schroeder)](https://user-images.githubusercontent.com/910929/143745302-6edbfe6b-885e-4990-a145-a76f8029792b.gz), [reduced test case (provided by Craig Schroeder)](https://user-images.githubusercontent.com/910929/143745303-b825871f-779c-45be-b1c0-84f3928f8b93.gz) |
| CC | @DougGregor |

## Extended Description 

When running clang trunk on the provided input file, clang produces:

t9.c:1:25: error: expected member name or ';' after declaration specifiers
typedef union {union wai<U+00C0> * a;} b __attribute__ ((__transparent_union__));
               ~~~~~    ^
t9.c:1:16: error: field has incomplete type 'union wai'
typedef union {union wai<U+00C0> * a;} b __attribute__ ((__transparent_union__));
               ^
t9.c:1:22: note: forward declaration of 'union wai'
typedef union {union wai<U+00C0> * a;} b __attribute__ ((__transparent_union__));
                     ^
t9.c:1:25: error: expected ';' at end of declaration list

and then hangs.

**Comment by Endilll** [comment]
One test case is not crashing since 3.3: https://godbolt.org/z/oxd7bcEKG
Another test case is not crashing since 3.2: https://godbolt.org/z/zYxco9EG7
