### ISSUE TITLE
Error recovery can trigger Assertion `!EnteredScope && "Already entered the scope!"'

### ISSUE THREAD

**Issue by hfinkel** [llvm/llvm-project#13181]
|  |  |
| --- | --- |
| Bugzilla Link | [12809](https://llvm.org/bz12809) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced test case (provided by Craig Schroeder)](https://user-images.githubusercontent.com/910929/143745298-73fed732-6786-4f57-b897-9a8b54c5c305.gz) |
| CC | @DougGregor |

## Extended Description 

Running clang trunk on:

namespace std {template<bool T> struct copy<T>{};template(std::copy_a<T>(n));}

Results in the following:

t4.cpp:1:40: error: explicit specialization of non-template struct 'copy'
namespace std {template<bool T> struct copy<T>{};template(std::copy_a<T>(n));}
                                       ^   ~~~
t4.cpp:1:64: error: no template named 'copy_a' in namespace 'std'; did you mean 'copy'?
namespace std {template<bool T> struct copy<T>{};template(std::copy_a<T>(n));}
                                                          ~~~~~^~~~~~
                                                               copy
t4.cpp:1:40: note: 'copy' declared here
namespace std {template<bool T> struct copy<T>{};template(std::copy_a<T>(n));}
                                       ^
t4.cpp:1:71: error: use of undeclared identifier 'T'
namespace std {template<bool T> struct copy<T>{};template(std::copy_a<T>(n));}
                                                                      ^
clang: /src/llvm-trunk-writable/tools/clang/lib/Parse/../../include/clang/Parse/Parser.h:1901: void clang::Parser::DeclaratorScopeObj::EnterDeclaratorScope(): Assertion `!EnteredScope && "Already entered the scope!"' failed.

Interestingly, If you rename "copy" or "copy_a" to
something else (eg, "c" and "c_a"), the assertion is avoided.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.8: https://cexplorer.testlabs.pro/z/oePedj
