### ISSUE TITLE
Error recovery can trigger Assertion `D && "Cannot get layout of forward declarations!"'

### ISSUE THREAD

**Issue by hfinkel** [llvm/llvm-project#13187]
|  |  |
| --- | --- |
| Bugzilla Link | [12815](https://llvm.org/bz12815) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced test case (provided by Craig Schroeder)](https://user-images.githubusercontent.com/910929/143745304-55e2db04-2948-4ed4-ad50-83865c2ac5c0.gz) |
| CC | @DougGregor |

## Extended Description 

Running clang trunk on:

```cpp
typedef union{union b u;} A __attribute__ ((__transparent_union__));
```

results in:

t10.c:1:23: error: field has incomplete type 'union b'
typedef union{union b u;} A __attribute__ ((__transparent_union__));
                      ^
t10.c:1:21: note: forward declaration of 'union b'
typedef union{union b u;} A __attribute__ ((__transparent_union__));
                    ^
clang: /src/llvm-trunk-writable/tools/clang/lib/AST/RecordLayoutBuilder.cpp:2385: const clang::ASTRecordLayout& clang::ASTContext::getASTRecordLayout(const clang::RecordDecl*) const: Assertion `D && "Cannot get layout of forward declarations!"' failed.

**Comment by shafik** [comment]
No longer reproduces on clang trunk: https://godbolt.org/z/cPYo91ohf

**Comment by Endilll** [comment]
Fixed in Clang 4: https://godbolt.org/z/sYM1n1WEG
