### ISSUE TITLE
segfault (no assertion) in Sema::CheckFunctionDeclaration on invalid input

### ISSUE THREAD

**Issue by hfinkel** [llvm/llvm-project#13185]
|  |  |
| --- | --- |
| Bugzilla Link | [12813](https://llvm.org/bz12813) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
clang trunk segfaults (no assertion) on this invalid C code (provided by Craig Schroeder):

extern int f(int x) __attribute__ ((__mode__ (__HI__)));extern int f(int x);

start of the backtrace is:
#&#8203;0  0x0000000000cec292 in clang::FunctionType::getResultType (this=0x0)
    at/src/llvm-trunk-writable/tools/clang/lib/Serialization/../../include/clang/AST/Type.h:2678
#&#8203;1  0x0000000000db757e in clang::FunctionDecl::getResultType (this=0x408cd30)
    at /src/llvm-trunk-writable/tools/clang/lib/CodeGen/../../include/clang/AST/Decl.h:1839
#&#8203;2  0x0000000000ffc184 in clang::Sema::CheckFunctionDeclaration (this=0x40a1fe0, S=0x40a67f0, NewFD=0x408cd30, Previous=..., 
    IsExplicitSpecialization=false) at /src/llvm-trunk-writable/tools/clang/lib/Sema/SemaDecl.cpp:5761

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.9: https://cexplorer.testlabs.pro/z/z5M5Ez
