### ISSUE TITLE
Error recovery can trigger Assertion `Chunk.Kind == DeclaratorChunk::Function'

### ISSUE THREAD

**Issue by hfinkel** [llvm/llvm-project#13182]
|  |  |
| --- | --- |
| Bugzilla Link | [12810](https://llvm.org/bz12810) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced test case (provided by Craig Schroeder)](https://user-images.githubusercontent.com/910929/143745299-59314122-b74a-4e19-a86e-e4dfcb48d44e.gz) |
| CC | @DougGregor |

## Extended Description 

Running clang trunk on:

template<typename T> struct s{}; template<typename T> s<T> f(T (x)() const) {}

results in:

t5.cpp:1:70: error: non-member function cannot have 'const' qualifier
template<typename T> struct s{}; template<typename T> s<T> f(T (x)() const) {}
                                                                     ^~~~~
clang: /src/llvm-trunk-writable/tools/clang/lib/Sema/SemaType.cpp:3119: void<unnamed>::DeclaratorLocFiller::VisitFunctionTypeLoc(clang::FunctionTypeLoc): Assertion `Chunk.Kind == DeclaratorChunk::Function' failed.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.2: https://godbolt.org/z/j8G4saxbo
