### ISSUE TITLE
crash on unclosed asm

### ISSUE THREAD

**Issue by hfinkel** [llvm/llvm-project#13191]
|  |  |
| --- | --- |
| Bugzilla Link | [12819](https://llvm.org/bz12819) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced test case (provided by Craig Schroeder)](https://user-images.githubusercontent.com/910929/143745309-4681577d-9bb3-42bc-badb-d4982e2ae383.gz) |
| CC | @DougGregor |

## Extended Description 

clang trunk crashes on this input after issuing the error (when in C mode):

int vscanf () __asm__ (("")

the result is:

t15.c:1:24: error: expected string literal
int vscanf () __asm__ (("")

(and then it crashes in Parser::ParseSimpleAsm).

**Comment by wheatman** [comment]
reproduces on 3.4.1
seems to be fixed by 3.5
https://godbolt.org/z/h1rvvEnsY
