### ISSUE TITLE
COVERED_SWITCH_DEFAULT is misdetected as supported

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13199]
|  |  |
| --- | --- |
| Bugzilla Link | [12827](https://llvm.org/bz12827) |
| Version | trunk |
| OS | Linux |
| Attachments | [hack to disable that flag](https://user-images.githubusercontent.com/60944935/143745317-ed04c121-17c8-4acc-9b75-32916b1a2b2f.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

With a fresh checkout of llvm/clang, I tried to build out of tree:
$ rm -rf build
$ cd build
$ ../configure --enable-optimized

configure detects -Wcovered-switch-default as supported:
#checking optional compiler flags... -Wno-variadic-macros -Wno-missing-field-initializers -Wcovered-switch-default

(as it should, since a recent clang is installed in /usr/local/bin). If I run make, however:
austin@debian-buildbot:~/src/llvm/build$ make
make[1]: Entering directory `/home/austin/src/llvm/build/lib/Support'
llvm[1]: Compiling regcomp.c for Release+Asserts build
cc1: error: unrecognized command line option "-Wcovered-switch-default"
/bin/rm: cannot remove `/home/austin/src/llvm/build/lib/Support/Release+Asserts/regcomp.d.tmp': No such file or directory
make[1]: *** [/home/austin/src/llvm/build/lib/Support/Release+Asserts/regcomp.o] Error 1
make[1]: Leaving directory `/home/austin/src/llvm/build/lib/Support'
make: *** [all] Error 1

my workaround has been to hack out support from the makefiles, then it compiles fine.

I get the same error if I use gcc-4.5.3 to compile, which lacks support for that flag.

OS is debian testing, 32-bit.

**Comment by Endilll** [comment]
Autotools support has been removed long ago.
