### ISSUE TITLE
SAFECode control-flow integrity should consider function signature

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13195]
|  |  |
| --- | --- |
| Bugzilla Link | [12823](https://llvm.org/bz12823) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
SAFECode's control-flow integrity enforcement currently assumes that using the conservative call-graph computed by some compiler analysis is correct.

However, there are a few gotcha's with this approach:

1) A callgraph may provide a function target for a call site that takes more parameters than what the call site provides.  This means that accessing those extra arguments in the callee can violate memory safety.

2) The callgraph may contain a function target for a call site that doesn't match the byval annotation of the call site.  This, too, can cause memory safety errors.

SAFECode should vet the list of valid function targets to ensure that the number of arguments and byval attributes between call site and callee are compatible (from a memory safety perspective) and filter out those function targets that are not.  Additionally, it should do this even for incomplete function call checks.

**Comment by Endilll** [comment]
SAFECode is archived.
