### ISSUE TITLE
Add a new feature about RISCV target

### ISSUE THREAD

**Issue by WilliamWangPeng** [llvm/llvm-project#132]
hi guys (-)
I have done some tests about llvm-mc now，such as---assemble , -disassemble ,-mattr=<a1,+a2,-a3,...>  and I have seen many options in llvm-mc --help, I want to add a new feature about RISCV target, what can I do ? 
thank you
Best Regards

**Comment by tclin914** [comment]
`llvm-mc --help`
...
 --mhvx                                            - Enable Hexagon Vector eXtensions
...

You can refer to clang/lib/Target/Hexagon/MCTargetDesc/HexagonMCTargetDesc.cpp that how the option mhvx add.

**Comment by WilliamWangPeng** [comment]
> 
thank you dear guys, I have already added a feature and implement the RISC-V graphics subtarget extension.

**Comment by asb** [comment]
Great to hear! Marking this issue as resolved then - just reopen if not.
