### ISSUE TITLE
libc++ functions as first class fails (namely std::string)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13206]
|  |  |
| --- | --- |
| Bugzilla Link | [12834](https://llvm.org/bz12834) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@efriedma-quic |

## Extended Description 
This example:

#include <string>

int main()
{
 void (std::string::*f)() = &std::string::clear;
}

Fails to link in ToT Clang and libcxx (as of 5/14/2012).  Other function pointers I tried seem to work fine, including function pointers of class methods, but reaching into std::string to get refer to its methods causes the problem.

**Comment by philnik777** [comment]
Taking the address of non-addressable library functions is UB, so this seems fine to me.
