### ISSUE TITLE
Server side nightly test results incorrect without-enable-llcbeta

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#1321]
|  |  |
| --- | --- |
| Bugzilla Link | [949](https://llvm.org/bz949) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Currently the nightly tester's option -enable-llcbeta doesn't do anything. You
get the llcbeta test whether you use this option or not.  While it is probably a
reasonable default to have llcbeta turned on by default, there should be a way
to turn it off. 

I would prefer that the llcbeta was on by default and a -disable-llcbeta option
was provided, similar to -disable-jit, -disable-cbe, etc.

**Comment by gwelymernans** [comment]
I'm guessing that this is no longer an issue given the current build farms we have.
