### ISSUE TITLE
memoize constexpr function invocations

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13222]
|  |  |
| --- | --- |
| Bugzilla Link | [12850](https://llvm.org/bz12850) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie,@DougGregor,@dushistov,@efriedma-quic,@tkremenek,@pogo59,@zygoloid |

## Extended Description 
The following is some simple test code that causes clang to slow to a crawl:

#include <stdio.h>

constexpr int fn(int i) {
    return i < 0 ? 0 : (i + fn(i-1) + fn(i-2));
}

constexpr int e = fn(NUM);

int main() {
    printf("%i\n", e);
    return 0;
}

With gcc 4.6.3 or 4.7.0, compiling using "gcc -std=c++0x test.cpp -DNUM=???" (where NUM is given in the table below), takes the following compile times:

NUM | compile time | output
================================
  5 |     0.03     |  26
 10 |     0.03     |  364
 15 |     0.03     |  4163
 20 |     0.03     |  46345
 25 |     0.03     |  514201
 30 |     0.03     |  5702854
 35 |     0.03     |  63245948
 40 |     0.03     |  701408690

On clang 3.1 rc-1, the corresponding compile times become:

NUM | compile time | output
================================
  5 |      0.03    |  26
 10 |      0.04    |  364
 15 |      0.04    |  4163
 20 |      0.12    |  46345
 25 |      1.03    |  514201
 30 |     11.16    |  5702854
 35 |    123.93    |  63245948
 40 |   1377.85    |  701408690

In both cases, compile times are in seconds.  I can only assume gcc must be somehow caching previously evaluated function calls...

**Comment by ChuanqiXu9** [comment]
Let's discuss this in https://github.com/llvm/llvm-project/issues/61425.
