### ISSUE TITLE
False Positive Warning for 'conversion never used'.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13231]
|  |  |
| --- | --- |
| Bugzilla Link | [12859](https://llvm.org/bz12859) |
| Version | 3.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
I encountered code issuing an incorrect warning. The small test program below reproduces the issue. The warning it gives is:
test.cpp:26:10: warning: conversion function converting 'MultiDerived' to its base class 'BasePrivate' will never be used
        virtual operator BasePrivate()
                ^
1 warning generated.

However, on executing it prints:
MultiDerived operator BasePrivate was invoked.

Therefore, the warning is untrue.

Apologies if this bug is invalid for some reason or is a duplicate, but it would appear to me that the message should be improved to make clear the unexpected behaviour that will result from code using this poor style, without being misleading. E.g., in this particular case where the operator is virtual, perhaps something like the following would be better (unless this is also incorrect ...):
test.cpp:26:10: warning: conversion of 'MultiDerived' to its base class 'BasePrivate' will only use the provided conversion operator when accessed via a less derived type.
        virtual operator BasePrivate()
                ^

>>>>>>>>>>>>>>>>>>>>>>>>test.cpp contents<<<<<<<<<<<<<<<<<<<<<<<<<
#include <iostream>
#include <string>
using namespace std;

template<typename T>
struct BasePublic
{
	virtual operator T() = 0;
};

struct BasePrivate
{
	BasePrivate()
		:
		m_memberVar("Default value.")
	{
	}
	
	string m_memberVar;
};

struct MultiDerived:
	public BasePublic<BasePrivate>,
	private BasePrivate
{
	virtual operator BasePrivate()
	{
		m_memberVar = "MultiDerived operator BasePrivate was invoked.";
		return (* this);
	}
};

int main(int a_argc, char * a_argv[])
{
	MultiDerived multiDerived;
	BasePublic<BasePrivate> & basePublicRef = multiDerived;
	BasePrivate testBPriv(basePublicRef);
	cout << testBPriv.m_memberVar << endl;
}

**Comment by wheatman** [comment]
reproduces on 3.1
seems to have been fixed by 11.0.0
https://godbolt.org/z/TjM858bhG
