### ISSUE TITLE
Building of lld fails

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13233]
|  |  |
| --- | --- |
| Bugzilla Link | [12861](https://llvm.org/bz12861) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @Bigcheese,@filcab |

## Extended Description 
Building of lld (LLVM linker) fails with following error:

In file included from /Volumes/Dev/LLVM/llvm/tools/lld/tools/lld-core/lld-core.cpp:12:
In file included from /Volumes/Dev/LLVM/llvm/tools/lld/include/lld/Core/NativeReader.h:13:
In file included from /Volumes/Dev/LLVM/llvm/tools/lld/include/lld/Core/File.h:18:
In file included from /Volumes/Dev/LLVM/llvm/include/llvm/ADT/StringRef.h:18:
/usr/include/c++/v1/string:1952:10: error: overload resolution selected implicitly-deleted copy assignment operator
    __r_ = _STD::move(__str.__r_);
         ^
/usr/include/c++/v1/string:1942:9: note: in instantiation of member function 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__move_assign' requested
      here
        __move_assign(__str, true_type());
        ^
/usr/include/c++/v1/string:1961:5: note: in instantiation of member function 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__move_assign' requested
      here
    __move_assign(__str, integral_constant<bool,
    ^
/Volumes/Dev/LLVM/llvm/include/llvm/Support/CommandLine.h:882:11: note: in instantiation of member function 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>
      >::operator=' requested here
    Value = Arg.str();
          ^
/usr/include/c++/v1/memory:1941:5: note: copy assignment operator is implicitly deleted because '__compressed_pair<std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char>>::__rep, std::__1::allocator<char> >' has a user-declared move constructor
    __compressed_pair(__compressed_pair&& __p)
    ^
1 warning and 1 error generated.
make[2]: *** [tools/lld/tools/lld-core/CMakeFiles/lld-core.dir/lld-core.cpp.o] Error 1
make[1]: *** [tools/lld/tools/lld-core/CMakeFiles/lld-core.dir/all] Error 2
make: *** [all] Error 2

OS X 10.7.3
Clang 3.2 from trunk

**Comment by arsenm** [comment]
Old build error
