### ISSUE TITLE
llc documentation of command-line flags isn't up to date

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13274]
|  |  |
| --- | --- |
| Bugzilla Link | [12902](https://llvm.org/bz12902) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The llc documentation - http://llvm.org/docs/CommandGuide/llc.html

Is not updated with respect to command line flags. For example the very important flag -filetype is not documented, and probably many others.

**Comment by arsenm** [comment]
Old documentation issue
