### ISSUE TITLE
Python scripts assume that "/usr/bin/env python" is python2

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13272]
|  |  |
| --- | --- |
| Bugzilla Link | [12900](https://llvm.org/bz12900) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 
The build scripts are written in python2, but "/usr/bin/env python" is python3 on some systems (e.g. Arch Linux). There are at least two solutions

1. Add a --with-python=/path/to/python configure flag so the user can choose a compatible version. Then invoke the scripts using ${PYTHON} path/to/script.py.

2. Make the scripts hybrid python2/python3. This should be easy if you can assume python2.6 or later (to support importing print_function from __future__).

**Comment by arsenm** [comment]
Python2 is dead
