### ISSUE TITLE
The left operand of '==' is a garbage value

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13282]
|  |  |
| --- | --- |
| Bugzilla Link | [12910](https://llvm.org/bz12910) |
| Version | 3.0 |
| OS | Linux |
| Attachments | [report](https://user-images.githubusercontent.com/60944935/143745373-a87c9d6a-9ac3-469b-a550-7a8e4a288776.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Bug reported by the clang static analyzer.

Description: The left operand of '==' is a garbage value
File: /home/kabi/export/lvm2.git/daemons/dmeventd/libdevmapper-event.c
Line: 447

My assumption is that clang doesn't understand, that value of
args[0] will be either dmeventd_path or default_dmeventd_path.
Both pointers allowes its char dereference  args[0][0].

Unless I miss something

**Comment by JOE1994** [comment]
`Clang static analyzer 18.1.0` doesn't emit the warning:

* https://godbolt.org/z/ocxExsqda
