### ISSUE TITLE
Clang 3.1 is unable to compile itself on Gentoo

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13328]
|  |  |
| --- | --- |
| Bugzilla Link | [12956](https://llvm.org/bz12956) |
| Version | unspecified |
| OS | All |
| Attachments | [Patch to fix C++ header search path on Gentoo Linux](https://user-images.githubusercontent.com/60944935/143745411-8a6a4ac6-e898-4086-b594-b2d4463b2d49.gz), [Patch to fix path finding on Gentoo FreeBSD](https://user-images.githubusercontent.com/60944935/143745412-641b9e00-b3d4-450a-a28d-e08b0ab24dd0.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @pageexec |

## Extended Description 

The attached patch has been applied to Clang 3.1 in downstream Gentoo. The downstream bug is the following:

https://bugs.gentoo.org/show_bug.cgi?id=417537

**Comment by arsenm** [comment]
Old build issue

**Comment by EugeneZelenko** [comment]
@arsenm: Please add `obsolete` labels when closing issues of similar nature.
