### ISSUE TITLE
Clang 3.1 will ignore system GCC version on Gentoo

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13327]
|  |  |
| --- | --- |
| Bugzilla Link | [12955](https://llvm.org/bz12955) |
| Version | unspecified |
| OS | All |
| Attachments | [Patch to detect system GCC and adjust paths accordingly](https://user-images.githubusercontent.com/60944935/143745408-09914db3-f913-4b84-b7cf-88d255ca63c5.gz), [Patch for Gentoo FreeBSD](https://user-images.githubusercontent.com/60944935/143745409-c2d39262-d924-417b-abfc-83057e23cb7d.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @pageexec |

## Extended Description 

I have attached a patch that I have applied downstream to address this. Comments are appreciated.

**Comment by arsenm** [comment]
Old build issue
