### ISSUE TITLE
Win7x64 Mingw64 "make install" drops off files in x86 program folder

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13345]
|  |  |
| --- | --- |
| Bugzilla Link | [12973](https://llvm.org/bz12973) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
On Windows x64, you want the 64-bit version of LLVM/Clang to be installed to the "%SYSTEMDRIVE%\Program Files" directory rather than the x86 "%SYSTEMDRIVE%\Program Files (x86)" folder.

Commands used to build:

   (retrieve trunk version of LLVM, Clang, etc.)
   (change to other directory; this is where LLVM will be built)
   (ask CMake to create Makefiles)
   make install

The install location should be as follows:

   Win32:
         Mingw32:
                 %SYSTEMDRIVE%\Program Files\LLVM
         Mingw64:
                 N/A
   Win64:
         Mingw32:
                 %SYSTEMDRIVE%\Program Files (x86)\LLVM
         Mingw64:
                  %SYSTEMDRIVE%\Program Files\LLVM

Oscar Fuentes, from the LLVMdev mailing lists, mentions that it MIGHT be a CMake script error as he says CMake is 100 percent aware that I am doing a 64-bit build.

**Comment by arsenm** [comment]
Old build issue
