### ISSUE TITLE
The poolregister optimization should be re-enabled

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13358]
|  |  |
| --- | --- |
| Bugzilla Link | [12986](https://llvm.org/bz12986) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
SAFECode currently has a GlobalRegisterOpts.cpp file that implements an optimization to remove pool_register_global() calls.  The old code to remove pool_register() and pool_register_stack() calls should be re-enabled.

**Comment by arsenm** [comment]
I can't find any trace of this remaining
