### ISSUE TITLE
multiple gentoo packages fail to compile if dragonegg.so included in CFLAGS

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13350]
|  |  |
| --- | --- |
| Bugzilla Link | [12978](https://llvm.org/bz12978) |
| Version | 3.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
SOmewhere I had read that you were looking for a list of the packages that cannot be built with draganegg.  The following were tracked down to not compile wherever -fplugin=/usr/lib64/llvm/dragonegg.so was included in the CFLAGS:

   kde-base/nepomuk
   dev-lang/ocaml
   dev-lang/ruby-1.8.7_p357
   dev-lang/ruby-enterprise-1.8.7.2010.02-r1
   app-office/libreoffice-3.5.2.2
   media-libs/xine-lib-1.2.1-r1
   x11-libs/pixman-0.24.0
   kde-base/kdelibs-4.8.1-r2
   dev-libs/glib-2.32.3 -- 'asm goto' not supported
   dev-lang/ruby (1.9.3_p125 to 1.9.3_p194_r1)

I suspect a few other packages may have problems, but this is an initial set extracted from an 1800 package build system.

I have yet to notice any patterns besides removing dragonegg.so

I will send any pertinent information I find.

**Comment by asl** [comment]
Dragonegg is obsolete
