### ISSUE TITLE
i386 make check failure: win_ftol2.ll fails on SVN r157887

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13389]
|  |  |
| --- | --- |
| Bugzilla Link | [13017](https://llvm.org/bz13017) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I'm running on recent git commit 31219d2cec17dca632b6d047a15e86dc92b76e18
 
git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@157887 91177308-0d34-0410-b5e6-96231b3b80d8

Compiled with 

export CC='gcc-4.7'
export CXX='g++-4.7'
export CPP='cpp-4.7'
export CFLAGS="-march=pentium-m -O3 -mfpmath=sse -ftree-vectorize"
export CXXFLAGS="$CFLAGS"
export LDFLAGS="-Wl,-O1 -Wl,--as-needed"

/sctank2/Dane/linux/llvm/configure \
	--enable-optimized \
	--disable-assertions \
	--enable-bindings=none \
	--with-built-clang \
	--enable-shared \
	--enable-jit \
	--enable-targets=x86

(make && make check-all) 2>&1 | tee check-all-redir.log

A failure:

FAIL: LLVM :: CodeGen/X86/win_ftol2.ll (3183 of 6078)
******************** TEST 'LLVM :: CodeGen/X86/win_ftol2.ll' FAILED ********************
Script:
--
/sctank2/Dane/linux/llvm-builddir/Release/bin/llc < /sctank2/Dane/linux/llvm/test/CodeGen/X86/win_ftol2.ll -mtriple=i686-pc-win32 | /sctank2/Dane/linux/llvm-builddir/Release/bin/FileCheck /sctank2/Dane/linux/llvm/test/CodeGen/X86/win_ftol2.ll -check-prefix=FTOL
/sctank2/Dane/linux/llvm-builddir/Release/bin/llc < /sctank2/Dane/linux/llvm/test/CodeGen/X86/win_ftol2.ll -mtriple=i686-pc-mingw32 | /sctank2/Dane/linux/llvm-builddir/Release/bin/FileCheck /sctank2/Dane/linux/llvm/test/CodeGen/X86/win_ftol2.ll -check-prefix=COMPILERRT
/sctank2/Dane/linux/llvm-builddir/Release/bin/llc < /sctank2/Dane/linux/llvm/test/CodeGen/X86/win_ftol2.ll -mtriple=i686-pc-linux | /sctank2/Dane/linux/llvm-builddir/Release/bin/FileCheck /sctank2/Dane/linux/llvm/test/CodeGen/X86/win_ftol2.ll -check-prefix=COMPILERRT
/sctank2/Dane/linux/llvm-builddir/Release/bin/llc < /sctank2/Dane/linux/llvm/test/CodeGen/X86/win_ftol2.ll -mtriple=x86_64-pc-win32 | /sctank2/Dane/linux/llvm-builddir/Release/bin/FileCheck /sctank2/Dane/linux/llvm/test/CodeGen/X86/win_ftol2.ll -check-prefix=COMPILERRT
/sctank2/Dane/linux/llvm-builddir/Release/bin/llc < /sctank2/Dane/linux/llvm/test/CodeGen/X86/win_ftol2.ll -mtriple=x86_64-pc-mingw32 | /sctank2/Dane/linux/llvm-builddir/Release/bin/FileCheck /sctank2/Dane/linux/llvm/test/CodeGen/X86/win_ftol2.ll -check-prefix=COMPILERRT
/sctank2/Dane/linux/llvm-builddir/Release/bin/llc < /sctank2/Dane/linux/llvm/test/CodeGen/X86/win_ftol2.ll -mtriple=x86_64-pc-linux | /sctank2/Dane/linux/llvm-builddir/Release/bin/FileCheck /sctank2/Dane/linux/llvm/test/CodeGen/X86/win_ftol2.ll -check-prefix=COMPILERRT
/sctank2/Dane/linux/llvm-builddir/Release/bin/llc < /sctank2/Dane/linux/llvm/test/CodeGen/X86/win_ftol2.ll -mattr=-sse -O0 -mtriple=i686-pc-win32 | /sctank2/Dane/linux/llvm-builddir/Release/bin/FileCheck /sctank2/Dane/linux/llvm/test/CodeGen/X86/win_ftol2.ll -check-prefix=FTOL_2
--
Exit Code: 1
Command Output (stderr):
--
/sctank2/Dane/linux/llvm/test/CodeGen/X86/win_ftol2.ll:140:9: error: expected string not found in input
; FTOL: @&#8203;double_ui64_5
        ^
<stdin>:185:2: note: scanning from here
 movl %ebp, %esp
 ^
<stdin>:186:2: note: possible intended match here
 popl %ebp
 ^
--

********************

Only this single test is failing.

Thanks,
Witek

**Comment by arsenm** [comment]
Old build issue
