### ISSUE TITLE
DSA Local analysis has assertion failure in debug build

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13391]
|  |  |
| --- | --- |
| Bugzilla Link | [13019](https://llvm.org/bz13019) |
| Version | trunk |
| OS | Linux |
| Attachments | [A testcase](https://user-images.githubusercontent.com/60944935/143745452-7d4e58a1-1861-471d-a2a9-d9a77dc08fb4.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Hello,
 1)  I am running DSA on a small threaded program. Optimized build is running OK, but debug build is asserting here:

Local.cpp ( function GraphBuilder::MergeConstantInitIntoNode): 
1258   } else {
1259     assert(0 && "Unknown constant type!");
1260   }

  The variable seems to be a constant string.
@.str = private unnamed_addr constant [42 x i8] c"Usage: matrixmul <size of n x n matrix> \0A\00", align 1

  Is this a known issue? I got the DSA few days ago. And I have combined it with llvm 3.1

2) On a second note, I'm thinking how to enhance DSA so it can look through the (void *) casting needed in thread start functions. Often, we pass different nodes through the (void *) argument which is actually a struct, and cast to void * only for pthread_create. Any hint where I could hack, or whether it can be incorporated as a general enhancement in DSA?

  I appreciate your help!
thanks & regards,
madan

**Comment by arsenm** [comment]
DSA no longer exists
