### ISSUE TITLE
-fplugin-arg-dragonegg-llvm-option=-vectorize produces bad bitcode for some SPEC benchmarks

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13412]
|  |  |
| --- | --- |
| Bugzilla Link | [13040](https://llvm.org/bz13040) |
| Version | trunk |
| OS | Linux |
| Attachments | [Broken ASCII bitcode output of gfortran + DragonEgg + vectorization](https://user-images.githubusercontent.com/60944935/143745466-0934b1f6-0c1b-46f5-bb9c-42c0db76265f.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@rotateright |

## Extended Description 
I think I've seen this on other SPEC benchmarks as well, but I've recently been working with tonto:

    $ gfortran -g -fplugin=/usr/local/lib/dragonegg.so -fplugin-arg-dragonegg-emit-ir -O2 -fno-strict-aliasing -fplugin-arg-dragonegg-llvm-option=-vectorize -S textfile.fppized.f90 -o textfile.fppized.ll
    $ llvm-as textfile.fppized.ll
    llvm-as: assembly parsed, but does not verify as correct!
    Range types must match load type!
      %4 = load <2 x i32>* %3, align 4, !dbg !&#8203;1765, !range !&#8203;1766
    Broken module found, compilation terminated.
    Range types must match load type!
      %20 = load <2 x i32>* %19, align 4, !dbg !&#8203;1779, !range !&#8203;1780
    Broken module found, compilation terminated.
                         ...

Take out the -vectorize and all is well:

    $ gfortran -g -fplugin=/usr/local/lib/dragonegg.so -fplugin-arg-dragonegg-emit-ir -O2 -fno-strict-aliasing -S textfile.fppized.f90 -o textfile.fppized.ll
    $ llvm-as textfile.fppized.ll

This is with gfortran 4.5.2 and LLVM/DragonEgg revision 158077.

-- Scott

**Comment by asl** [comment]
Dragonegg is obsolete as well. We can reopen, if necessary
