### ISSUE TITLE
-O2 -fplugin-arg-dragonegg-llvm-option=-vectorize gives floating point exception

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13427]
|  |  |
| --- | --- |
| Bugzilla Link | [13055](https://llvm.org/bz13055) |
| Version | trunk |
| OS | Linux |
| Attachments | [Reproducer for a DragonEgg floating-point exception](https://user-images.githubusercontent.com/60944935/143745478-b61706a1-4af8-4930-909b-54f2833e1314.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Here's what I'm seeing when I try to compile the attached code with LLVM+DragonEgg revision 158012 and gcc v4.7.0 or v4.5.2:

    $ gcc -O2 -fplugin=/home/pakin/llvm/lib/dragonegg.so -fplugin-arg-dragonegg-llvm-option=-vectorize -c dragonegg-fpe.c
    Stack dump:
    0.      Running pass 'CallGraph Pass Manager' on module 'dragonegg-fpe.c'.
    1.      Running pass 'BasicBlock Pass Manager' on function '@readVariableVLB'
    2.      Running pass 'Basic-Block Vectorization' on basic block '%"3"'
    *** WARNING *** there are active plugins, do not report this as a bug unless you can reproduce it without enabling any plugins.
    Event                            | Plugins
    PLUGIN_FINISH_UNIT               | dragonegg
    PLUGIN_FINISH                    | dragonegg
    PLUGIN_START_UNIT                | dragonegg
    PLUGIN_ALL_IPA_PASSES_END        | dragonegg
    dragonegg-fpe.c:82:1: internal compiler error: Floating point exception
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <http://gcc.gnu.org/bugs.html> for instructions.

The reproducer is kind of large, but I did manage to cut it down from 5000+ lines to 82 lines.  Dropping either the -O2 or the -fplugin-arg-dragonegg-llvm-option=-vectorize makes the problem go away.

-- Scott

**Comment by asl** [comment]
Dragonegg is obsolete
