### ISSUE TITLE
loop in CFGBuilder::Visit ?

### ISSUE THREAD

**Issue by pwo** [llvm/llvm-project#13448]
|  |  |
| --- | --- |
| Bugzilla Link | [13076](https://llvm.org/bz13076) |
| Version | trunk |
| OS | FreeBSD |
| Attachments | [Pre-processed source](https://user-images.githubusercontent.com/92601275/143745483-89c2266f-a26d-4d98-a053-16b8586e3d83.gz) |

## Extended Description 

Somewhere around r158250 or later self-hosted clang on FreeBSD/i386 started to crash when building usr.bin/kdump/ioctl.c (auto generated file).

Around the same time the many-logical-ops.c test started to fail on the self-host compiler again (not sure if that is related).

1>buildbot@llvm-i386 /tmp% gdb /data/buildslave/freebsd-clang-i386/obj/llvm.2/Release+Asserts/bin/clang
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "i386-marcel-freebsd"...(no debugging symbols found)...
(gdb) run -cc1 -triple i386-unknown-freebsd9.0 -emit-obj -disable-free -main-file-name ioctl.c -mrelocation-model static -mdisable-fp-elim -masm-verbose -mconstructor-aliases -target-cpu i486 -target-linker-version 2.22 -momit-leaf-frame-pointer -O2 -Wsystem-headers -Wall -Wno-format-y2k -W -Wno-unused-parameter -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wunused-parameter -Wcast-align -Wchar-subscripts -Winline -Wnested-externs -Wredundant-decls -Wold-style-definition -Wno-pointer-sign -Wno-empty-body -Wno-string-plus-int -std=gnu99 -fconst-strings -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -mstackrealign -fgnu-runtime -fobjc-runtime-has-arc -fobjc-runtime-has-weak -fobjc-dispatch-method=non-legacy -fdiagnostics-show-option -x c ioctl-krZebt.i
Starting program: /data/buildslave/freebsd-clang-i386/obj/llvm.2/Release+Asserts/bin/clang -cc1 -triple i386-unknown-freebsd9.0 -emit-obj -disable-free -main-file-name ioctl.c -mrelocation-model static -mdisable-fp-elim -masm-verbose -mconstructor-aliases -target-cpu i486 -target-linker-version 2.22 -momit-leaf-frame-pointer -O2 -Wsystem-headers -Wall -Wno-format-y2k -W -Wno-unused-parameter -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wunused-parameter -Wcast-align -Wchar-subscripts -Winline -Wnested-externs -Wredundant-decls -Wold-style-definition -Wno-pointer-sign -Wno-empty-body -Wno-string-plus-int -std=gnu99 -fconst-strings -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -mstackrealign -fgnu-runtime -fobjc-runtime-has-arc -fobjc-runtime-has-weak -fobjc-dispatch-method=non-legacy -fdiagnostics-show-option -x c ioctl-krZebt.i
(no debugging symbols found)...[New LWP 100110]
(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...[New Thread 2a004300 (LWP 100110/clang)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 2a004300 (LWP 100110/clang)]
0x089bc36c in (anonymous namespace)::CFGBuilder::Visit ()
(gdb) bt
#&#8203;0  0x089bc36c in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;1  0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;2  0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;3  0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;4  0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;5  0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;6  0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;7  0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;8  0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;9  0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;10 0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;11 0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;12 0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;13 0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;14 0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;15 0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;16 0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;17 0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;18 0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;19 0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;20 0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;21 0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
#&#8203;22 0x089bf6c3 in (anonymous namespace)::CFGBuilder::Visit ()
...

**Comment by Endilll** [comment]
Can't reproduce using assertions builds of Clang 3.0 through 3.2.
