### ISSUE TITLE
Invalid but unused NSDMI is not ignored

### ISSUE THREAD

**Issue by 3a17e7c4-fca4-4827-b2a7-11a54d73d746** [llvm/llvm-project#13452]
|  |  |
| --- | --- |
| Bugzilla Link | [13080](https://llvm.org/bz13080) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid,@tstellar |

## Extended Description 
I couldn't find anything in the standard about when a NSDMI in a template is instantiated, but I'm pretty sure it's never needed here and this should compile:

```cpp
template<typename T>
struct A
{
    A() = default;
    A(T t) : t(t) { }
    T t{ T() };
};

struct NotDefaultConstructible
{
    NotDefaultConstructible(int) { }
};

A<NotDefaultConstructible> a( NotDefaultConstructible(0) );
```

The default constructor (which would use the NSDMI) is never odr-used so should not be defined. Even if the default constructor is removed clang++ still rejects the code.

G++ accepts this code and I was hoping to use something like it in libstdc++ but that would cause problems for people using libstdc++ with clang++.

Naïvely I would expect this to have the same semantics as:

template<typename T>
struct A
{
    A(T t = T()) : t(t) { }
    T t;
};

In this case the default argument is only implicitly instantiated when the constructor is called in a context that requires it.

**Comment by shafik** [comment]
Looks fixed in clang-3.6: https://godbolt.org/z/6hn59Te8T

CC @jwakely @zygoloid
