### ISSUE TITLE
Failure to Compile CLang/LLVM from Source on a PPC Machine under Linux?

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13460]
|  |  |
| --- | --- |
| Bugzilla Link | [13088](https://llvm.org/bz13088) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic |

## Extended Description 
Attempt at building from source crashes/fails. I am trying to compile from source per these instructions:

http://clang.llvm.org/get_started.html

Machine is an old Mac G4 Powerbook (32 bit PowerPC (PPC) architecture)running Linux (Debian Squeeze).

These are the error messages/ output:

haziz@debian:~/src/build$ make
make[1]: Entering directory `/home/haziz/src/build/lib/Support'
llvm[1]: Compiling APFloat.cpp for Release+Asserts build
In file included from /home/haziz/src/llvm/lib/Support/APFloat.cpp:15:
In file included from /home/haziz/src/llvm/include/llvm/ADT/APFloat.h:104:
In file included from /home/haziz/src/llvm/include/llvm/ADT/APInt.h:18:
In file included from /home/haziz/src/llvm/include/llvm/ADT/ArrayRef.h:13:
In file included from /home/haziz/src/llvm/include/llvm/ADT/SmallVector.h:18:
In file included from /home/haziz/src/llvm/include/llvm/Support/type_traits.h:20:
In file included from /home/haziz/src/build/include/llvm/Support/DataTypes.h:37:
/usr/include/c++/4.4/cmath:42:10: fatal error: 'bits/c++config.h' file not found
#include <bits/c++config.h>
         ^
0  clang     0x10e24058
1  clang     0x10e248b4
2            0x00100364 __kernel_sigtramp32 + 0
3            0000000000 __kernel_sigtramp32 + 4293917852
4  clang     0x10505100
5  clang     0x10318068
6  clang     0x10260260
7  clang     0x105aded0
8  clang     0x105965c0
9  clang     0x1058d27c
10 clang     0x1058d998
11 clang     0x105b56c8
12 clang     0x105b61d0
13 clang     0x105b64f8
14 clang     0x10592954
15 clang     0x105874d8
16 clang     0x10587778
17 clang     0x1022424c
18 clang     0x100288d0
19 clang     0x10028a24
20 clang     0x10016f08
21 clang     0x10008d18
22 clang     0x1000bc70 main + 1488
23 libc.so.6 0x0fbb069c
24 libc.so.6 0x0fbb0860
Stack dump:
0.	Program arguments: /usr/bin/clang -cc1 -triple powerpc-unknown-linux-gnu -S -disable-free -disable-llvm-verifier -main-file-name APFloat.cpp -pic-level 2 -mconstructor-aliases -resource-dir /usr/lib/clang/1.1 -dependency-file /home/haziz/src/build/lib/Support/Release+Asserts/APFloat.d.tmp -MP -MT /home/haziz/src/build/lib/Support/Release+Asserts/APFloat.o -MT /home/haziz/src/build/lib/Support/Release+Asserts/APFloat.d -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/haziz/src/build/include -I/home/haziz/src/build/lib/Support -I/home/haziz/src/llvm/include -I/home/haziz/src/llvm/lib/Support -O3 -Woverloaded-virtual -Wcast-qual -Wall -W -Wno-unused-parameter -Wwrite-strings -fmessage-length 125 -fno-signed-char -fgnu-runtime -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/cc-liZ0XT.s -x c++ /home/haziz/src/llvm/lib/Support/APFloat.cpp 
1.	/usr/include/c++/4.4/bits/basic_string.h:2144:17: current parser token '('
clang: error: compiler command failed due to signal 11 (use -v to see invocation)
make[1]: *** [/home/haziz/src/build/lib/Support/Release+Asserts/APFloat.o] Error 1
make[1]: Leaving directory `/home/haziz/src/build/lib/Support'
make: *** [all] Error 1

I have succeeded in compiling it on other machines in the past (Debian, Slackware and Ubuntu Linux, all x86 or AMD64). This is the first time that an attempt at compiling Clang/LLVM from source fails.

Thanks.

Sincerely,

Hany.

**Comment by arsenm** [comment]
Old build issue
