### ISSUE TITLE
Generalize support for FMA contraction

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#13490]
|  |  |
| --- | --- |
| Bugzilla Link | [13118](https://llvm.org/bz13118) |
| Version | trunk |
| OS | All |
| CC | @hfinkel,@lhames,@sunfishcode,@rotateright |

## Extended Description 
The llvm.fmuladd intrinsic is enough to model contraction of multiply and add when FP_CONTRACT is enabled, but isn't enough to handle more general cases like ppc fmsub and other instructions.  

Here's a possible sketch of an approach that could handle the more general cases (including subtract, random negations, etc):

1. Add two bits (like NSW/NUW on integer ops) to the floating point binary operations (fmul, fadd, ...): LHS_Contractable and RHS_Contractable.

2. Semantics are that the code generator is allowed to contract any tree of operations linked through "contractable" operands.  In the FMA case, the multiply can be merged into the add if the add's operand is marked contractable.  In the PPC case, fmsub can be contracted if the multiply operand of the subtract is marked.

3. Clang would generate the operand bits according to the language mode in effect.  I believe that this model is sufficiently general to handle the C99 and C++ cases.

**Comment by Endilll** [comment]
@arsenm Can you elaborate?

**Comment by arsenm** [comment]
> @arsenm Can you elaborate?

contract flag was added in cd847a8f3059d87cc6c5343d2dae7b25aacac322
