### ISSUE TITLE
Simple try-catch with std::cout throws std::ios_base::failure exception

### ISSUE THREAD

**Issue by rubenvb** [llvm/llvm-project#13497]
|  |  |
| --- | --- |
| Bugzilla Link | [13125](https://llvm.org/bz13125) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [-S output for GCC 4.7.0 and Clang 3.2pre](https://user-images.githubusercontent.com/92601424/143745509-7613b506-872a-4770-9f0a-a29d9df22089.gz) |
| CC | @asl,@FlashSheridan |

## Extended Description 

This test code:
-----
#include <iostream>

int main()
{
try
{
throw 5;
}
catch(int i)
{
std::cout << "Caught int: " << i << "\n";
}
}
----
Produces an extra exception when compiled with Clang 3.2pre (r158153) with GCC 4.7.0 libstdc++. GCC itself does not show this problem. I attached the asm generated by the compilers in question (which can be downloaded as the gcc-4.7.0-clang-3.2pre package from here
http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/rubenvb/experimental/
)

Using std::cout without throw-catch works fine. Switching to printf from <cstdio> also works fine. I attached the two asm files produced by running
[clan]g++ -O0 test.cpp -S -o [clang|gcc]asm.S
on the above code.

**Comment by nunoplopes** [comment]
Closing super old bug. @rubenvb please reopen if still an issue.
