### ISSUE TITLE
"Function is not marked const" error message should also be generated for template functions

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13539]
|  |  |
| --- | --- |
| Bugzilla Link | [13167](https://llvm.org/bz13167) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The error message that Clang produces for the code
```c++
  struct Test {
    void test1() const { test2(0); }
	
    template <typename T>
    void test2(T value) { }
  };

  int main() {
    Test().test1();
  }

```
  test.cpp:3:23: error: no matching member function for call to 'test2'
        void test1() const { test2(0); }
                             ^~~~~
  test.cpp:6:7: note: candidate function [with T = int] not viable: no known conversion from 'const Test *' to 'Test' for
        object argument;
          void test2(T value) { }
               ^
  1 error generated.

is less clear than the error it produces for the equivalent non-template code:
```c++
  struct Test {
    void test1() const { test2(0); }
	
    void test2(int value) { }
  };


  int main() {
    Test().test1();
  }
```

  test.cpp:3:23: error: member function 'test2' not viable: 'this' argument has type 'const Test', but function is not
      marked const
          void test1() const { test2(0); }
                               ^~~~~
  test.cpp:5:7: note: 'test2' declared here
          void test2(int value) { }
             ^
  1 error generated.

**Comment by philnik777** [comment]
Clang now produces
```
<source>:2:26: error: no matching member function for call to 'test2'
    void test1() const { test2(0); }
                         ^~~~~
<source>:5:10: note: candidate function template not viable: 'this' argument has type 'const Test', but method is not marked const
    void test2(T value) { }
```
for the first example, so I think this can be considered fixed.
