### ISSUE TITLE
cmake does not correctly check "git svn log" output [PATCH INCLUDED]

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13577]
|  |  |
| --- | --- |
| Bugzilla Link | [13205](https://llvm.org/bz13205) |
| Version | trunk |
| OS | All |
| Attachments | [add a check to the VersionFromVCS cmake module: git_output should not be empty](https://user-images.githubusercontent.com/60944935/143745549-3dc236e2-0dae-4c21-8064-ea75f79abf66.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @yuanfang-chen |

## Extended Description 

Cmake, precisely the "VersionFromVCS" module, calls "git svn log --limit=1 --oneline" and tries to extract the latest svn revision number. Unfortunately, "git svn log" also returns 0 (success) if the git repository has no svn information (is not connected to an SVN). But in this case, the output is empty, and the regular expression matching fails.
To detect the situation that we are in a git, but no svn information is available, we should also check the return value of the "git svn log" call. If it's empty, then don't use it. The patch just adds this check:
-      if( git_result EQUAL 0 )
+      if( git_result EQUAL 0 AND git_output )

Even though not many people will need it, I have exactly that situation, because I downloaded the sources as an archive, and initialized a local git repository with it to test different patches on them.

It shouldn't hurt anyone, so please apply the patch.

**Comment by arsenm** [comment]
git svn log no longer matters as git is the canonical repository
