### ISSUE TITLE
Building a sanitized Clang with --enable-shared dies with SIGSEGV

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13585]
|  |  |
| --- | --- |
| Bugzilla Link | [13213](https://llvm.org/bz13213) |
| Version | unspecified |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @ramosian-glider,@kcc,@zygoloid |

## Extended Description 
Since I've been using more Clang-built tools, I find it useful for debugging to 
use a sanitized Clang.  So I installed compiler-rt, built Clang-3.1 from the 
release branch, and then I built Clang again using that Clang, as follows:

/usr/local/src/llvm/configure --prefix=/usr/local/stow/clang-3.1-asan 
--enable-assertions --enable-expensive-checks --enable-debug-runtime 
--enable-debug-symbols --disable-bootstrap --with-extra-options="-g -O1 
-faddress-sanitizer" --with-extra-ld-options="-g -O1 -faddress-sanitizer" 
CC=/usr/local/stow/clang-3.1/bin/clang 
CXX=/usr/local/stow/clang-3.1/bin/clang++ LD=/usr/local/stow/clang-3.1/bin/clang

This works great.  However, if I add --enable-shared, the build process will 
die with several SIGSEGVs:

llvm[4]: ======= Finished Linking Debug+Asserts+Checks Executable clang-check
make[4]: Nothing to be done for `all'.
/bin/sh: line 1: 97843 Segmentation fault: 11  
/Volumes/Data/Products/llvm-3.1-asan/Debug+Asserts+Checks/bin/clang -arch $arch 
-c -integrated-as 
/Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/make/platform/clang_darwin_test_input.c 
-isysroot /Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/SDKs/darwin 
-o /dev/null > /dev/null 2> /dev/null
warning: clang_darwin.mk: dropping arch 'i386' from lib 'eprintf'
/bin/sh: line 1: 97846 Segmentation fault: 11  
/Volumes/Data/Products/llvm-3.1-asan/Debug+Asserts+Checks/bin/clang -arch $arch 
-c -integrated-as 
/Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/make/platform/clang_darwin_test_input.c 
-isysroot /Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/SDKs/darwin 
-o /dev/null > /dev/null 2> /dev/null
warning: clang_darwin.mk: dropping arch 'i386' from lib '10.4'
/bin/sh: line 1: 97850 Segmentation fault: 11  
/Volumes/Data/Products/llvm-3.1-asan/Debug+Asserts+Checks/bin/clang -arch $arch 
-c -integrated-as 
/Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/make/platform/clang_darwin_test_input.c 
-isysroot /Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/SDKs/darwin 
-o /dev/null > /dev/null 2> /dev/null
warning: clang_darwin.mk: dropping arch 'x86_64' from lib '10.4'
/bin/sh: line 1: 97889 Segmentation fault: 11  
/Volumes/Data/Products/llvm-3.1-asan/Debug+Asserts+Checks/bin/clang -arch $arch 
-c -integrated-as 
/Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/make/platform/clang_darwin_test_input.c 
-isysroot /Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/SDKs/darwin 
-o /dev/null > /dev/null 2> /dev/null
warning: clang_darwin.mk: dropping arch 'i386' from lib 'ios'
/bin/sh: line 1: 97890 Segmentation fault: 11  
/Volumes/Data/Products/llvm-3.1-asan/Debug+Asserts+Checks/bin/clang -arch $arch 
-c -integrated-as 
/Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/make/platform/clang_darwin_test_input.c 
-isysroot /Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/SDKs/darwin 
-o /dev/null > /dev/null 2> /dev/null
warning: clang_darwin.mk: dropping arch 'x86_64' from lib 'ios'
/bin/sh: line 1: 97891 Segmentation fault: 11  
/Volumes/Data/Products/llvm-3.1-asan/Debug+Asserts+Checks/bin/clang -arch $arch 
-c -integrated-as 
/Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/make/platform/clang_darwin_test_input.c 
-isysroot /Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/SDKs/darwin 
-o /dev/null > /dev/null 2> /dev/null
warning: clang_darwin.mk: dropping arch 'armv6' from lib 'ios'
/bin/sh: line 1: 97912 Segmentation fault: 11  
/Volumes/Data/Products/llvm-3.1-asan/Debug+Asserts+Checks/bin/clang -arch $arch 
-c -integrated-as 
/Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/make/platform/clang_darwin_test_input.c 
-isysroot /Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/SDKs/darwin 
-o /dev/null > /dev/null 2> /dev/null
warning: clang_darwin.mk: dropping arch 'armv7' from lib 'ios'
/bin/sh: line 1: 97918 Segmentation fault: 11  
/Volumes/Data/Products/llvm-3.1-asan/Debug+Asserts+Checks/bin/clang -arch $arch 
-c -integrated-as 
/Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/make/platform/clang_darwin_test_input.c 
-isysroot /Volumes/Data/Archives/Sources/llvm/projects/compiler-rt/SDKs/darwin 
-o /dev/null > /dev/null 2> /dev/null

**Comment by Endilll** [comment]
Autotools is long gone.
Feel free to reopen if you experience this with CMake.
