### ISSUE TITLE
Assert hit in codegen of hi member assignment to 3 element vector

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13584]
|  |  |
| --- | --- |
| Bugzilla Link | [13212](https://llvm.org/bz13212) |
| Version | 3.1 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
george@tower ~/llvm/llvm-3.1.src/bin $ bin/clang -x c ~/miscTests/crash.c 
clang-3.1: /home/george/llvm/llvm-3.1.src/include/llvm/ADT/SmallVector.h:126: T& llvm::SmallVectorTemplateCommon<T>::operator[](unsigned int) [with T = llvm::Constant*, llvm::SmallVectorTemplateCommon<T>::reference = llvm::Constant*&]: Assertion `begin() + idx < end()' failed.
Stack dump:
0.	Program arguments: /home/george/llvm/llvm-3.1.src/bin/bin/clang-3.1 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name crash.c -mrelocation-model static -mdisable-fp-elim -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -momit-leaf-frame-pointer -resource-dir /home/george/llvm/llvm-3.1.src/bin/bin/../lib/clang/3.1 -fmodule-cache-path /var/tmp/clang-module-cache -internal-isystem /usr/local/include -internal-isystem /home/george/llvm/llvm-3.1.src/bin/bin/../lib/clang/3.1/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir /home/george/llvm/llvm-3.1.src/bin -ferror-limit 19 -fmessage-length 117 -mstackrealign -fgnu-runtime -fobjc-runtime-has-arc -fobjc-runtime-has-weak -fobjc-fragile-abi -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/crash-cac3Cn.o -x c /home/george/miscTests/crash.c 
1.	<eof> parser at end of file
2.	/home/george/miscTests/crash.c:3:8: LLVM IR generation of declaration 'f3'
3.	/home/george/miscTests/crash.c:3:8: Generating code for declaration 'f3'
4.	/home/george/miscTests/crash.c:3:13: LLVM IR generation of compound statement ('{}')
clang-3: error: unable to execute command: Aborted
clang-3: error: clang frontend command failed due to signal (use -v to see invocation)
clang-3: note: diagnostic msg: Please submit a bug report to http://llvm.org/bugs/ and include command line arguments and all diagnostic information.
clang-3: note: diagnostic msg: Preprocessed source(s) and associated run script(s) are located at:
clang-3: note: diagnostic msg: /tmp/crash-Gywj0x.i
clang-3: note: diagnostic msg: /tmp/crash-Gywj0x.sh
george@tower ~/llvm/llvm-3.1.src/bin $ cat /tmp/crash-Gywj0x.i
# 1 "/home/george/miscTests/crash.c"
# 1 "/home/george/miscTests/crash.c" 1
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 150 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "/home/george/miscTests/crash.c" 2
typedef __attribute__(( ext_vector_type(3) )) short short3;

short3 f3() {
 short3 res;
 res.hi = 0;
 return res;
}
george@tower ~/llvm/llvm-3.1.src/bin $ cat /tmp/crash-Gywj0x.sh
 "/home/george/llvm/llvm-3.1.src/bin/bin/clang-3.1" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name crash.c -mrelocation-model static -mdisable-fp-elim -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -momit-leaf-frame-pointer -resource-dir /home/george/llvm/llvm-3.1.src/bin/bin/../lib/clang/3.1 -fmodule-cache-path /var/tmp/clang-module-cache -internal-isystem /usr/local/include -internal-isystem /home/george/llvm/llvm-3.1.src/bin/bin/../lib/clang/3.1/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir /home/george/llvm/llvm-3.1.src/bin -ferror-limit 19 -fmessage-length 117 -mstackrealign -fgnu-runtime -fobjc-runtime-has-arc -fobjc-runtime-has-weak -fobjc-fragile-abi -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/crash-cac3Cn.o -x c /home/george/miscTests/crash.c
 "/usr/bin/ld" --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.6/crtbegin.o -L/usr/lib/gcc/x86_64-linux-gnu/4.6 -L/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.6/../../.. -L/lib -L/usr/lib /tmp/crash-cac3Cn.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/4.6/crtend.o /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/crtn.o

**Comment by Endilll** [comment]
Can't reproduce anymore: https://godbolt.org/z/Ev9xY4oz5
