### ISSUE TITLE
clang-3.1 (non-Apple version) does not set __STDC_NO_ATOMICS__ nor provide stdatomic.h

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13639]
|  |  |
| --- | --- |
| Bugzilla Link | [13267](https://llvm.org/bz13267) |
| Version | 3.1 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
clang 3.1 when run with -std=c11 reports __STDC_VERSION__ >= 201112L, but __STDC_NO_ATOMICS__ is not set even though it does not provide stdatomic.h. It is my understanding that all C11 implementations are required to either provide stdatomic.h OR set __STDC_NO_ATOMICS__ to 1.

**Comment by arsenm** [comment]
Looks like this was implemented in 6970ac8b0a125136d1151740993af4c36b678def
