### ISSUE TITLE
NightlyTester should not submit report if error in script occured.

### ISSUE THREAD

**Issue by tlattner** [llvm/llvm-project#1363]
|  |  |
| --- | --- |
| Bugzilla Link | [991](https://llvm.org/bz991) |
| Version | trunk |
| OS | All |

## Extended Description 
The new nightly tester should submit report back to the server if the script
itself had an error.

We also should have a webform (password protected) so the core llvm team can
easily delete test results that are not useful or due to errors in the script or
script usage.

**Comment by gwelymernans** [comment]
Probably not relevant anymore. Please re-file if you see it again.
