### ISSUE TITLE
Compiler crash and incorrect code generation

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13668]
|  |  |
| --- | --- |
| Bugzilla Link | [13296](https://llvm.org/bz13296) |
| Version | trunk |
| OS | All |
| Attachments | [Bogus code generation](https://user-images.githubusercontent.com/60944935/143745615-bf9aa6cd-e8de-4161-b823-6632f1dc8d13.gz), [Compiler crash](https://user-images.githubusercontent.com/60944935/143745616-d8b9a6c0-3391-424a-90ab-d9c596e2bd66.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @d0k,@DougGregor,@zygoloid |

## Extended Description 

llvm revision 159914, clang revision 159913

~/Developer/Tests/tst_af_3> clang++ -o tst_af_3 -O2 tst_af_3.cpp && ./tst_af_3
Error: 0
~/Developer/Tests/tst_af_3> clang++ -o tst_af_3 -O1 tst_af_3.cpp && ./tst_af_3
OK
~/Developer/Tests/tst_af_3> clang++ -o further_reduced_tst_af_3 -O2 further_reduced_tst_af_3.cpp && ./further_reduced_tst_af_3
0  clang             0x000000010a1cdd22 llvm::SmallVectorImpl<char>::swap(llvm::SmallVectorImpl<char>&) + 14034
1  clang             0x000000010a1ce199 llvm::SmallVectorImpl<char>::swap(llvm::SmallVectorImpl<char>&) + 15177
2  libsystem_c.dylib 0x00007fff86600cfa _sigtramp + 26
3  libsystem_c.dylib 0x00007fff687d5db0 _sigtramp + 18446744073208156368
4  clang             0x00000001090a996d llvm::SmallVectorImpl<unsigned int>::swap(llvm::SmallVectorImpl<unsigned int>&) + 62301
5  clang             0x00000001090a5596 llvm::SmallVectorImpl<unsigned int>::swap(llvm::SmallVectorImpl<unsigned int>&) + 44934
6  clang             0x0000000108f68792 std::__1::__tree<std::__1::pair<clang::NamespaceDecl*, clang::NamespaceDecl*>, std::__1::__map_value_compare<clang::NamespaceDecl*, clang::NamespaceDecl*, std::__1::less<clang::NamespaceDecl*>, true>, std::__1::allocator<std::__1::pair<clang::NamespaceDecl*, clang::NamespaceDecl*> > >::destroy(std::__1::__tree_node<std::__1::pair<clang::NamespaceDecl*, clang::NamespaceDecl*>, void*>*) + 5938
7  clang             0x0000000108e79032 std::__1::__split_buffer<std::__1::pair<llvm::WeakVH, llvm::Constant*>, std::__1::allocator<std::__1::pair<llvm::WeakVH, llvm::Constant*> >&>::push_front(std::__1::pair<llvm::WeakVH, llvm::Constant*> const&) + 113426
8  clang             0x0000000108e74586 std::__1::__split_buffer<std::__1::pair<llvm::WeakVH, llvm::Constant*>, std::__1::allocator<std::__1::pair<llvm::WeakVH, llvm::Constant*> >&>::push_front(std::__1::pair<llvm::WeakVH, llvm::Constant*> const&) + 94310
9  clang             0x0000000108e8e173 std::__1::__split_buffer<std::__1::pair<llvm::WeakVH, llvm::Constant*>, std::__1::allocator<std::__1::pair<llvm::WeakVH, llvm::Constant*> >&>::push_front(std::__1::pair<llvm::WeakVH, llvm::Constant*> const&) + 199763
10 clang             0x0000000108e8c58d std::__1::__split_buffer<std::__1::pair<llvm::WeakVH, llvm::Constant*>, std::__1::allocator<std::__1::pair<llvm::WeakVH, llvm::Constant*> >&>::push_front(std::__1::pair<llvm::WeakVH, llvm::Constant*> const&) + 192621
11 clang             0x0000000108e8b259 std::__1::__split_buffer<std::__1::pair<llvm::WeakVH, llvm::Constant*>, std::__1::allocator<std::__1::pair<llvm::WeakVH, llvm::Constant*> >&>::push_front(std::__1::pair<llvm::WeakVH, llvm::Constant*> const&) + 187705
12 clang             0x0000000108e75821 std::__1::__split_buffer<std::__1::pair<llvm::WeakVH, llvm::Constant*>, std::__1::allocator<std::__1::pair<llvm::WeakVH, llvm::Constant*> >&>::push_front(std::__1::pair<llvm::WeakVH, llvm::Constant*> const&) + 99073
13 clang             0x0000000108ec56a0 std::__1::__split_buffer<clang::Parser::ParsingClass**, std::__1::allocator<clang::Parser::ParsingClass**>&>::push_front(clang::Parser::ParsingClass** const&) + 205472
14 clang             0x0000000108ec500e std::__1::__split_buffer<clang::Parser::ParsingClass**, std::__1::allocator<clang::Parser::ParsingClass**>&>::push_front(clang::Parser::ParsingClass** const&) + 203790
15 clang             0x0000000108ec4b11 std::__1::__split_buffer<clang::Parser::ParsingClass**, std::__1::allocator<clang::Parser::ParsingClass**>&>::push_front(clang::Parser::ParsingClass** const&) + 202513
16 clang             0x0000000108e73674 std::__1::__split_buffer<std::__1::pair<llvm::WeakVH, llvm::Constant*>, std::__1::allocator<std::__1::pair<llvm::WeakVH, llvm::Constant*> >&>::push_front(std::__1::pair<llvm::WeakVH, llvm::Constant*> const&) + 90452
17 clang             0x0000000108ed099e llvm::SmallVectorTemplateBase<clang::ParsedTemplateArgument, false>::grow(unsigned long) + 27342
18 clang             0x0000000108e857fb std::__1::__split_buffer<std::__1::pair<llvm::WeakVH, llvm::Constant*>, std::__1::allocator<std::__1::pair<llvm::WeakVH, llvm::Constant*> >&>::push_front(std::__1::pair<llvm::WeakVH, llvm::Constant*> const&) + 164571
19 clang             0x0000000108e852a6 std::__1::__split_buffer<std::__1::pair<llvm::WeakVH, llvm::Constant*>, std::__1::allocator<std::__1::pair<llvm::WeakVH, llvm::Constant*> >&>::push_front(std::__1::pair<llvm::WeakVH, llvm::Constant*> const&) + 163206
20 clang             0x0000000108e737ec std::__1::__split_buffer<std::__1::pair<llvm::WeakVH, llvm::Constant*>, std::__1::allocator<std::__1::pair<llvm::WeakVH, llvm::Constant*> >&>::push_front(std::__1::pair<llvm::WeakVH, llvm::Constant*> const&) + 90828
21 clang             0x0000000108ed099e llvm::SmallVectorTemplateBase<clang::ParsedTemplateArgument, false>::grow(unsigned long) + 27342
22 clang             0x0000000108e857fb std::__1::__split_buffer<std::__1::pair<llvm::WeakVH, llvm::Constant*>, std::__1::allocator<std::__1::pair<llvm::WeakVH, llvm::Constant*> >&>::push_front(std::__1::pair<llvm::WeakVH, llvm::Constant*> const&) + 164571
23 clang             0x0000000108e852a6 std::__1::__split_buffer<std::__1::pair<llvm::WeakVH, llvm::Constant*>, std::__1::allocator<std::__1::pair<llvm::WeakVH, llvm::Constant*> >&>::push_front(std::__1::pair<llvm::WeakVH, llvm::Constant*> const&) + 163206
24 clang             0x0000000108e737ec std::__1::__split_buffer<std::__1::pair<llvm::WeakVH, llvm::Constant*>, std::__1::allocator<std::__1::pair<llvm::WeakVH, llvm::Constant*> >&>::push_front(std::__1::pair<llvm::WeakVH, llvm::Constant*> const&) + 90828
25 clang             0x0000000108ed099e llvm::SmallVectorTemplateBase<clang::ParsedTemplateArgument, false>::grow(unsigned long) + 27342
26 clang             0x0000000108ed0347 llvm::SmallVectorTemplateBase<clang::ParsedTemplateArgument, false>::grow(unsigned long) + 25719
27 clang             0x0000000108e6a6e6 std::__1::__split_buffer<std::__1::pair<llvm::WeakVH, llvm::Constant*>, std::__1::allocator<std::__1::pair<llvm::WeakVH, llvm::Constant*> >&>::push_front(std::__1::pair<llvm::WeakVH, llvm::Constant*> const&) + 53702
28 clang             0x0000000108e32787 std::__1::__split_buffer<clang::CXXRecordDecl const*, std::__1::allocator<clang::CXXRecordDecl const*>&>::push_front(clang::CXXRecordDecl const* const&) + 7111
29 clang             0x0000000108c28792 std::__1::__split_buffer<clang::FileEntry const*, std::__1::allocator<clang::FileEntry const*>&>::push_front(clang::FileEntry const* const&) + 12274
30 clang             0x0000000108c06648 std::__1::__split_buffer<clang::CompilerInstance*, std::__1::allocator<clang::CompilerInstance*>&>::push_front(clang::CompilerInstance* const&) + 16120
31 clang             0x0000000108beb224 void std::__1::__tree_balance_after_insert<std::__1::__tree_node_base<void*>*>(std::__1::__tree_node_base<void*>*, std::__1::__tree_node_base<void*>*) + 4292
32 clang             0x0000000108be2563
33 clang             0x0000000108be71e9 std::__1::__split_buffer<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&>::push_front(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 1193
34 clang             0x0000000108be0d34
35 clang             0x000000000000002d
Stack dump:
0.	Program arguments: /usr/local/bin/clang -cc1 -triple x86_64-apple-macosx10.7.0 -emit-obj -disable-free -main-file-name further_reduced_tst_af_3.cpp -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 128.2 -resource-dir /usr/local/bin/../lib/clang/3.2 -fmodule-cache-path /var/folders/kx/qz2frq7d0p9fn8rg0w4gmmjm0000gn/T/clang-module-cache -O2 -fdeprecated-macro -fdebug-compilation-dir /Users/luc/Developer/Tests/tst_af_3 -ferror-limit 19 -fmessage-length 120 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.7.0 -fobjc-dispatch-method=mixed -fobjc-default-synthesize-properties -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/kx/qz2frq7d0p9fn8rg0w4gmmjm0000gn/T/further_reduced_tst_af_3-LtZNi9.o -x c++ further_reduced_tst_af_3.cpp 
1.	further_reduced_tst_af_3.cpp:29:11: current parser token 'const_ref'
2.	further_reduced_tst_af_3.cpp:3:1: parsing namespace 'scitbx'
3.	further_reduced_tst_af_3.cpp:3:20: parsing namespace 'af'
4.	further_reduced_tst_af_3.cpp:6:3: parsing struct/union/class body 'tiny_plain'
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.2 (http://llvm.org/git/clang.git 6994bb61eff86b2db53253ec74b24c4142fc080e) (http://llvm.org/git/llvm.git d9cff9a25a9d4f2d8d9c1cb4960fb52cb049ef49)
Target: x86_64-apple-darwin11.4.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/kx/qz2frq7d0p9fn8rg0w4gmmjm0000gn/T/further_reduced_tst_af_3-7PoeED.cpp
clang: note: diagnostic msg: /var/folders/kx/qz2frq7d0p9fn8rg0w4gmmjm0000gn/T/further_reduced_tst_af_3-7PoeED.sh
clang: note: diagnostic msg: 

********************

**Comment by Endilll** [comment]
Comment above says it's been fixed.
