### ISSUE TITLE
exclude path in scan build

### ISSUE THREAD

**Issue by enptfb55** [llvm/llvm-project#137]
Forgive me if this issue has already been addressed. 

I found an old bug report from 2015 while i was searching for a way to exclude a given path(s) from a scan-build report. 

Here is a link to the existing bug report: https://bugs.llvm.org/show_bug.cgi?id=22594#c4

Please let me know if you need more information

**Comment by sylvestre** [comment]
Yeah, it has been implemented in 2018:
https://reviews.llvm.org/D52153
