### ISSUE TITLE
Poor recovery for badly-formed __has_include

### ISSUE THREAD

**Issue by belkadan** [llvm/llvm-project#13707]
|  |  |
| --- | --- |
| Bugzilla Link | [13335](https://llvm.org/bz13335) |
| Version | unspecified |
| OS | All |

## Extended Description 
A number of "badly formed expressions" in test/Preprocessor/has_include.c have very poor recovery, emitting extra errors or warnings when the user's intent is fairly clear. We should fix these.

(I'm about to commit a change that tags these under this PR number.)

**Comment by philnik777** [comment]
Looks like the file referenced is lost to time.

**Comment by Endilll** [comment]
@philnik777 Our current practice is to close issues in old test as `obsolete`.
