### ISSUE TITLE
Clang doesn't warn about direct base ‘{anonymous}::S1’ inaccessible in ‘{anonymous}::D9’ due to ambiguity

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13714]
|  |  |
| --- | --- |
| Bugzilla Link | [13342](https://llvm.org/bz13342) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
When building LLVM's unittests, gcc warns that:

unittests/Support/AlignOfTest.cpp:65:8: warning: direct base ‘{anonymous}::S1’ inaccessible in ‘{anonymous}::D9’ due to ambiguity

According to Chandler this is correct and clang should warn about it too.

**Comment by AaronBallman** [comment]
Clang warns on this as of Clang 3.7
