### ISSUE TITLE
work around libstdc++4.5 + C++11 bug: nested_exception.h:122:61: error: redefinition of default argument

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13745]
|  |  |
| --- | --- |
| Bugzilla Link | [13373](https://llvm.org/bz13373) |
| Version | 3.1 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 
clang++ -o main.o -c -O3 -DQT_NO_DEBUG -fvisibility=hidden -fvisibility-inlines-hidden -fomit-frame-pointer -fno-exceptions -fno-stack-protector --param max-inline-insns-single=32 --param max-inline-insns-auto=32 -w -funroll-loops --param max-unrolled-insns=32 -march=native -std=c++0x -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtSql main.cpp
In file included from main.cpp:1:
In file included from ./a.h:6:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.5.4/include/g++-v4/typeinfo:35:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.5.4/include/g++-v4/exception:151:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.5.4/include/g++-v4/nested_exception.h:122:61: error: redefinition of default argument
    __throw_with_nested(_Ex&& __ex, const nested_exception* = 0)
                                                            ^ ~
/usr/lib/gcc/x86_64-pc-linux-gnu/4.5.4/include/g++-v4/nested_exception.h:110:56: note: previous definition is here
    __throw_with_nested(_Ex&&, const nested_exception* = 0)
                                                       ^ ~
1 error generated.

**Comment by philnik777** [comment]
Doesn't seems worth it to try to work around that now if it hasn't already been implemented.
