### ISSUE TITLE
-Wsometimes-uninitialized prints two errors for one issue

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#13788]
|  |  |
| --- | --- |
| Bugzilla Link | [13416](https://llvm.org/bz13416) |
| Version | unspecified |
| OS | All |
| CC | @zygoloid |

## Extended Description 
Somewhere in chromium:

../../chrome/browser/ui/startup/startup_browser_creator_impl.cc:896:9: error: variable 'backup_homepage_is_ntp' is used uninitialized whenever '||' condition is true [-Werror,-Wsometimes-uninitialized]
    if (!prefs_watcher->GetBackupForPref(prefs::kHomePage)->
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../chrome/browser/ui/startup/startup_browser_creator_impl.cc:911:9: note: uninitialized use occurs here
        backup_homepage_is_ntp,
        ^~~~~~~~~~~~~~~~~~~~~~
../../chrome/browser/ui/startup/startup_browser_creator_impl.cc:896:9: note: remove the '||' if its condition is always false
    if (!prefs_watcher->GetBackupForPref(prefs::kHomePage)->
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../chrome/browser/ui/startup/startup_browser_creator_impl.cc:894:32: note: initialize the variable 'backup_homepage_is_ntp' to silence this warning
    bool backup_homepage_is_ntp;
                               ^
                                = false
../../chrome/browser/ui/startup/startup_browser_creator_impl.cc:896:9: error: variable 'backup_show_home_button' is used uninitialized whenever '||' condition is true [-Werror,-Wsometimes-uninitialized]
    if (!prefs_watcher->GetBackupForPref(prefs::kHomePage)->
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../chrome/browser/ui/startup/startup_browser_creator_impl.cc:912:9: note: uninitialized use occurs here
        backup_show_home_button));
        ^~~~~~~~~~~~~~~~~~~~~~~
../../chrome/browser/ui/startup/startup_browser_creator_impl.cc:896:9: note: remove the '||' if its condition is always false
    if (!prefs_watcher->GetBackupForPref(prefs::kHomePage)->
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../chrome/browser/ui/startup/startup_browser_creator_impl.cc:896:9: error: variable 'backup_show_home_button' is used uninitialized whenever '||' condition is true [-Werror,-Wsometimes-uninitialized]
    if (!prefs_watcher->GetBackupForPref(prefs::kHomePage)->
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../chrome/browser/ui/startup/startup_browser_creator_impl.cc:912:9: note: uninitialized use occurs here
        backup_show_home_button));
        ^~~~~~~~~~~~~~~~~~~~~~~
../../chrome/browser/ui/startup/startup_browser_creator_impl.cc:896:9: note: remove the '||' if its condition is always false
    if (!prefs_watcher->GetBackupForPref(prefs::kHomePage)->
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../chrome/browser/ui/startup/startup_browser_creator_impl.cc:895:33: note: initialize the variable 'backup_show_home_button' to silence this warning
    bool backup_show_home_button;
                                ^
                                 = false

Note that the second variable has two errors on the same line.

**Comment by philnik777** [comment]
There is no reproducer, so I'm closing this.
