### ISSUE TITLE
option to generate PIE by default

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13782]
|  |  |
| --- | --- |
| Bugzilla Link | [13410](https://llvm.org/bz13410) |
| Version | 3.1 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dushistov,@foutrelis,@LW-archlinux,@nlewycky,@kraj,@zygoloid |

## Extended Description 
GCC in Gentoo Hardened generates PIE by default
clang could have configure option to generate PIE by default

**Comment by MaskRay** [comment]
[[Driver] Add CLANG_DEFAULT_PIE_ON_LINUX to emulate GCC --enable-default-pie](https://reviews.llvm.org/D113372) (target: 14.0.0) added the ability.
