### ISSUE TITLE
llvm-config: error: components given, but unused

### ISSUE THREAD

**Issue by vinsonlee** [llvm/llvm-project#13802]
|  |  |
| --- | --- |
| Bugzilla Link | [13430](https://llvm.org/bz13430) |
| Version | 3.1 |
| OS | other |

## Extended Description 
$ uname
CYGWIN_NT-6.1-WOW64

$ llvm-config.exe --version
3.1

$ llvm-config.exe --libs
-lLLVM-3.1

$ llvm-config.exe --libs all
-lLLVM-3.1
llvm-config: error: components given, but unused

usage: llvm-config <OPTION>... [<COMPONENT>...]

Get various configuration information needed to compile programs which use
LLVM.  Typically called from 'configure' scripts.  Examples:
  llvm-config --cxxflags
  llvm-config --ldflags
  llvm-config --libs engine bcreader scalaropts

Options:
  --version         Print LLVM version.
  --prefix          Print the installation prefix.
  --src-root        Print the source root LLVM was built from.
  --obj-root        Print the object root used to build LLVM.
  --bindir          Directory containing LLVM executables.
  --includedir      Directory containing LLVM headers.
  --libdir          Directory containing LLVM libraries.
  --cppflags        C preprocessor flags for files that include LLVM headers.
  --cflags          C compiler flags for files that include LLVM headers.
  --cxxflags        C++ compiler flags for files that include LLVM headers.
  --ldflags         Print Linker flags.
  --libs            Libraries needed to link against LLVM components.
  --libnames        Bare library names for in-tree builds.
  --libfiles        Fully qualified library filenames for makefile depends.
  --components      List of all possible components.
  --targets-built   List of all targets currently built.
  --host-target     Target triple used to configure LLVM.
  --build-mode      Print build mode of LLVM tree (e.g. Debug or Release).
Typical components:
  all               All LLVM libraries (default).
  engine            Either a native JIT or a bitcode interpreter.

**Comment by arsenm** [comment]
Old build problem
