### ISSUE TITLE
Ignores dependent base classes using qualified lookup in definition context

### ISSUE THREAD

**Issue by be579e8c-b74b-475b-a126-3b8cefdd833c** [llvm/llvm-project#13826]
|  |  |
| --- | --- |
| Bugzilla Link | [13454](https://llvm.org/bz13454) |
| Version | trunk |
| OS | Windows NT |
| CC | @DougGregor |

## Extended Description 
This should work fine, but Clang doesn't accept the absence of "typename" in the definition of "B"

template<typename T> struct A { 
   typedef int type; 
   struct B; 
}; 

template<typename T> struct A<T>::B : A<T> { 
   B::type t; 
};

**Comment by Endilll** [comment]
We still reject this as of Clang 17, while other implementations accept: https://godbolt.org/z/zMhczK3hh

**Comment by shafik** [comment]
Confirmed

**Comment by shafik** [comment]
CC @Fznamznon
