### ISSUE TITLE
printf and fprintf fail to check inputs for re-write pointers

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13821]
|  |  |
| --- | --- |
| Bugzilla Link | [13449](https://llvm.org/bz13449) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Encountered this issue while testing code addressing bug 11524.  Bug can be reproduce with a modified version of safecode/test/core/fastgepcheck-003.c.  Just remove the last three lines (c[0] = *p1; c[1] = *p2; c[2] = *p5;) before the return.

**Comment by philnik777** [comment]
The reproducer seems to be lost to time.
