### ISSUE TITLE
-Wunused-private-field false positive after error

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#13892]
|  |  |
| --- | --- |
| Bugzilla Link | [13520](https://llvm.org/bz13520) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
This code triggers a -Wunused-private-field false positive on C::S::k:

class C {
  struct X {
    int n;
  } x;

public:
  class S {
  private:
    int k;
    C *p;
  public:
    S(int k, C *p) : k(k), p(p) {}
    void f() { p->x.n = k; }
  };

  void f(UnknownTypeName utn);
};

I guess we're setting C to be invalid, and so discarding the use of 'k' within C::S::f.

(To see this in the wild, introduce a bad type name into any Sema member function declaration...)

**Comment by cor3ntin** [comment]
Can't reproduce in any clang version on CE
