### ISSUE TITLE
clang should warn on comparing bools to integer constants

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#13912]
|  |  |
| --- | --- |
| Bugzilla Link | [13540](https://llvm.org/bz13540) |
| Version | unspecified |
| OS | All |
| CC | @zygoloid,@seanm |

## Extended Description 
eg on this:

bool f(bool b) {
  return b == 48;
}

use case: I had

   if (a == 4)

somewhere, then i moved that into a variable cond, and incompletely replaced my condition with that like so:

  if (cond == 4)

**Comment by xgupta** [comment]
The issue is fixed on trunk, it seems, there is -Wtautological-constant-compare - https://godbolt.org/z/be9fd4Eh4.
