### ISSUE TITLE
#pragma clang diagnostic push ignores garbage at end of line without warning

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13920]
|  |  |
| --- | --- |
| Bugzilla Link | [13548](https://llvm.org/bz13548) |
| Version | 3.1 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I blithely wrote the following code:

#pragma clang diagnostic push ignored "-Wdeprecated-declarations"

Which should not be expected to work, nor is it documented to. Owing to a mental scotoma I could not comprehend why deprecated-declaration warning continued to be issued.
As it happens you can put nigh anything at the end of the line and the compiler will silently ignore it.

If the compiler had warned about the garbage, it would have saved me some mental anguish. Perhaps we need to add -Wextra-stuff-at-end-of-pragma. Or perhaps we don't need to make that one optional.

**Comment by Endilll** [comment]
Nothing has changed as of Clang 16: https://godbolt.org/z/3sbWdeK6r
