### ISSUE TITLE
No error about changing const variable via struct/union copy

### ISSUE THREAD

**Issue by 43113a5a-87dd-4095-9c20-18b5be2ae8c3** [llvm/llvm-project#14018]
|  |  |
| --- | --- |
| Bugzilla Link | [13646](https://llvm.org/bz13646) |
| Version | trunk |
| OS | Linux |

## Extended Description 
union foo {
	int a;
	const int b;
};

int main(void)
{
	union foo f1, f2;

	f1.a = 5;
	f2 = f1;
	return 0;
}

gcc fails:

test2.c:11:2: error: assignment of read-only variable ‘f2’

clang gives no error.

**Comment by Endilll** [comment]
Fixed in Clang 6.
https://godbolt.org/z/zbzToTc5Y
