### ISSUE TITLE
Optimizers wrongly think a GEP of global without inbounds can't point into a different global

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14028]
|  |  |
| --- | --- |
| Bugzilla Link | [13656](https://llvm.org/bz13656) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic |

## Extended Description 
This testcase was inspired by the fact that pointsToConstantGlobal in
InstCombineLoadStoreAlloca.cpp forgets to check "inbounds" on the GEP.
However my attempts to get a testcase failed because all kinds of other
parts of instcombine and constant folding also forget to check inbounds,
and would do wrong transforms before pointsToConstantGlobal could get
anywhere near the IR!  So here is a simple testcase showing the issue:
it loads the value of a non-constant global @&#8203;B, but instcombine is fooled
into thinking it is loading from another, constant, global @&#8203;A thanks to a
tricky GEP.

; RUN: opt < %s -instcombine -S | FileCheck %s
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64"

@&#8203;A = constant i8 0
@&#8203;B = global i8 0

define i8 @&#8203;foo() {
; CHECK: @&#8203;foo
; Load @&#8203;B while sneakily giving the appearance of loading part of @&#8203;A.
  %val = load i8* getelementptr (i8* @&#8203;A, i64 sub (i64 ptrtoint (i8* @&#8203;B to i64), i64 ptrtoint (i8* @&#8203;A to i64)))
  ret i8 %val
; CHECK-NOT: ret i8 0
}

**Comment by nikic** [comment]
As indicated in the previous comment, this is UB due to aliasing rules.
