### ISSUE TITLE
false positive: division by zero with unsigned denominator

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14045]
|  |  |
| --- | --- |
| Bugzilla Link | [13673](https://llvm.org/bz13673) |
| Version | 3.1 |
| OS | FreeBSD |
| Attachments | [division by zero false positive example code.](https://user-images.githubusercontent.com/60944935/143745884-af9f5fab-0f50-464a-b6bc-66662b66983e.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @belkadan |

## Extended Description 

The following attachment produces a false positive for division by zero if 'b' is declared to be 'unsigned int' but no warning is generated if 'b' is declared to be 'int'. 

> clang --analyze cc.c
cc.c:18:8: warning: Division by zero
        c = a / b[i];
            ~~^~~~~~
1 warning generated.
> clang --version
clang version 3.1 (branches/release_31)
Target: i386-portbld-freebsd8.3
Thread model: posix
>

**Comment by Endilll** [comment]
Fixed in Clang 10
https://godbolt.org/z/YK71qGss9
