### ISSUE TITLE
null-conversion warning needs to be suppressed in macro expansion

### ISSUE THREAD

**Issue by ehsan** [llvm/llvm-project#14087]
|  |  |
| --- | --- |
| Bugzilla Link | [13715](https://llvm.org/bz13715) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie,@DougGregor |

## Extended Description 
Macros can accept pointer-like arguments which they would check for non-null-ness using operator!.  Currently clang warns in those cases, but I don't think that warning in macro expansion contexts makes a lot of sense.

ehsan@teenux:/tmp$ cat test.cpp 
#include <stdio.h>
#define foo(x) if (!(x)) printf("x");
int main() {
  int* p;
  foo(p);
  foo(NULL);
}
ehsan@teenux:/tmp$ clang -Wnull-conversion test.cpp 
test.cpp:6:3: warning: implicit conversion of NULL constant to 'bool' [-Wnull-conversion]
  foo(NULL);
  ^~~~~~~~~
test.cpp:2:22: note: expanded from macro 'foo'
#define foo(x) if (!(x)) printf("x");
                   ~ ^
1 warning generated.

**Comment by Endilll** [comment]
Fixed in Clang 3.9
https://godbolt.org/z/saq6M56W7
