### ISSUE TITLE
LLVM-COV is not part of the windows prebuilt binary

### ISSUE THREAD

**Issue by cordeiroph** [llvm/llvm-project#141]
I downloaded all the windows pre build release binary versions (from 6 to 10) and none had the llvm-cov, it is possible get it if built from source.

I am not sure if it is a bug or a decision and I could not find any thing about it.

**Comment by zmodem** [comment]
I think it was just an oversight.

I've added it in dcd89b3de6de891bfcc59189cda1ea059fbdcdb5, so it should become part of the next snapshot and also the 10.0.0 release.
