### ISSUE TITLE
Clang segfaults when __attribute__((constructor)) function refers to local static variable

### ISSUE THREAD

**Issue by Quuxplusone** [llvm/llvm-project#14104]
|  |  |
| --- | --- |
| Bugzilla Link | [13732](https://llvm.org/bz13732) |
| Version | trunk |
| OS | MacOS X |
| Attachments | [output of "clang -c test.cc -v"](https://user-images.githubusercontent.com/702021/143745934-5930fa0b-4a02-4683-a80a-e2053e94b0a3.gz) |
| CC | @AaronBallman |

## Extended Description 

cat >test.cc <<EOF
int main() {
    static int foo = 0;
    struct S { __attribute__((constructor)) void bar() { foo = 1; } };
}
EOF
clang -c test.cc

If you trick Clang/LLVM into generating a "constructor" function that refers to a local-scoped variable, the compiler segfaults. Personally, I don't think member functions should be allowed to have __attribute__((constructor)), but maybe there is a plausible use case for allowing this kind of thing.

Resolved bug 7101 and resolved bug 11883 are superficially similar, but I doubt they're directly related.

Stack dump:
0.	Program arguments: /usr/bin/clang -cc1 -triple x86_64-apple-macosx10.8.0 -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name test.cc -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 134.3 -coverage-file test.o -resource-dir /usr/lib/clang/3.2 -fmodule-cache-path /var/folders/1z/jvnkrdws621c6wmrcf7q_9180000gn/T/clang-module-cache -fdeprecated-macro -fdebug-compilation-dir /tmp -ferror-limit 19 -fmessage-length 147 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.8.0 -fobjc-dispatch-method=mixed -fobjc-default-synthesize-properties -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o test.o -x c++ test.cc 
1.	test.cc:3:70: current parser token ';'
2.	test.cc:1:12: parsing function body 'main'
3.	test.cc:1:12: in compound statement ('{}')
4.	test.cc:3:5: parsing struct/union/class body 'S'
5.	test.cc:3:12: LLVM IR generation of declaration 'S'
6.	test.cc:3:50: Generating code for declaration 'main()::S::bar'
7.	test.cc:3:56: LLVM IR generation of compound statement ('{}')
clang: error: unable to execute command: Segmentation fault: 11

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.5: https://godbolt.org/z/erWc35aK1
