### ISSUE TITLE
decltype in declaration does not match up with definition, causing ambiguous overload

### ISSUE THREAD

**Issue by brunodefraine** [llvm/llvm-project#14102]
|  |  |
| --- | --- |
| Bugzilla Link | [13730](https://llvm.org/bz13730) |
| Version | 3.1 |
| OS | All |
| CC | @DougGregor |

## Extended Description 
Consider this:

```cpp
#include <utility> // std::declval

using namespace std;

template<typename T>
struct vec {
};

template<typename S, typename T>
vec<decltype(declval<S>() * declval<T>())> operator*(const vec<S>& v1, const vec<T>& v2);

template<typename S, typename T>
vec<decltype(declval<S>() * declval<T>())> operator*(const vec<S>&, const vec<T>&) {
	return vec<decltype(declval<S>() * declval<T>())>();
}

int main() {
	vec<double> v1, v2;
	v1 * v2;
}
```
This gives:

amb.cpp:19:5: fatal error: use of overloaded operator '*' is ambiguous (with operand types 'vec<double>' and 'vec<double>')
        v1 * v2;
        ~~ ^ ~~
amb.cpp:10:44: note: candidate function [with S = double, T = double]
vec<decltype(declval<S>() * declval<T>())> operator*(const vec<S>& v1, const vec<T>& v2);
                                           ^
amb.cpp:13:44: note: candidate function [with S = double, T = double]
vec<decltype(declval<S>() * declval<T>())> operator*(const vec<S>&, const vec<T>&) {
                                           ^
1 error generated.

I only intend there to be one function "operator*", that is first declared and then defined.

Somehow, the presence of "decltype" and "declval" in the return type prevents the definition from matching up with the declaration, causing an ambiguous overload?

This is:

Apple clang version 4.0 (tags/Apple/clang-421.0.60) (based on LLVM 3.1svn)
Target: x86_64-apple-darwin12.1.0
Thread model: posix

With -stdlib=libc++

**Comment by shafik** [comment]
Looks fixed: https://godbolt.org/z/6dG7sefq5
