### ISSUE TITLE
crash-on-invalid (?) with template argument list naming destructor

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#14148]
|  |  |
| --- | --- |
| Bugzilla Link | [13776](https://llvm.org/bz13776) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
template <class T> struct A {
  template <class U> struct B {
  };
};
template <class T, class U> void f() {
  typename A<T>::template B<U> b;
  b.A<T>::template B<U>::~B<U>();
}
int main ()
{
  f<int, char>();
}

Assertion failed: (!SS.isSet() && "ObjectType and scope specifier cannot coexist"), function LookupTemplateName, file /Volumes/storage/llvm/tools/clang/lib/Sema/SemaTemplate.cpp, line 256.

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.1 and 3.2 with assertions enabled: https://cexplorer.testlabs.pro/z/fM1c8n
