### ISSUE TITLE
incorrectly rejecting redeclaration of function via using-declaration at block scope

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#14158]
|  |  |
| --- | --- |
| Bugzilla Link | [13786](https://llvm.org/bz13786) |
| Version | unspecified |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Clang incorrectly rejects this:

int f(int a, int b, int c);
void g() {
  using ::f;
  int f(int a, int b, int c);
}

This does not violate [namespace.udecl]p14, because both declarations refer to the same function.

**Comment by Endilll** [comment]
Fixed in Clang 3.5
https://godbolt.org/z/drq9bTveh
