### ISSUE TITLE
-Wdangling-field warning should check in-class initializers

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#14180]
|  |  |
| --- | --- |
| Bugzilla Link | [13808](https://llvm.org/bz13808) |
| Version | unspecified |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
struct S { const int &a; S() : a(0) {} } s;                                             
struct T { const int &a = 0; } t;

produces:

<stdin>:1:34: warning: binding reference member 'a' to a temporary value [-Wdangling-field]
struct S { const int &a; S() : a(0) {} } s;
                                 ^
<stdin>:1:23: note: reference member declared here
struct S { const int &a; S() : a(0) {} } s;
                      ^

We should also issue a diagnostic for the in-class initializer case.

**Comment by Endilll** [comment]
Fixed since Clang 3.4
https://godbolt.org/z/3aM5aaW51
