### ISSUE TITLE
reg2mem pass fail compiling llvm 3.1

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14188]
|  |  |
| --- | --- |
| Bugzilla Link | [13816](https://llvm.org/bz13816) |
| Version | 3.1 |
| OS | Linux |
| Attachments | [reg2mem error](https://user-images.githubusercontent.com/60944935/143745999-68296440-f115-4793-84c5-f32de4d9b9e0.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 

reg2mem pass fail compiling some files in llvm 3.1

I was trying to compile llvm with my pass (and -reg2mem) when it failed.
I figured out that it was reg2mem which failed by removing my pass and just execute reg2mem.

See attached file for error.

**Comment by arsenm** [comment]
Unclear to me what the error is, there are assorted failures in linking. No reproducer supplied
