### ISSUE TITLE
Regression testing fails when building MLIR. It did not on feb. 3

### ISSUE THREAD

**Issue by dpotop** [llvm/llvm-project#142]
Hello,

I'm building the development version of llvm-project, including MLIR.
Regression testing fails immediately.
This is a new issue - a version I had kept from February 3 still compiles
and runs its tests flawlessly).
I'd like to know if this is normal.

Compiling is done using this sequence of commands (the same for both
versions, the one that works, and the current one that does not):

> cd llvm-project
> mkdir build
> cd build
> cmake -G Ninja ../llvm -DLLVM_ENABLE_PROJECTS=mlir    -DLLVM_BUILD_EXAMPLES=ON -DLLVM_TARGETS_TO_BUILD="X86;NVPTX;AMDGPU" -DCMAKE_BUILD_TYPE=Release    -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_C_COMPILER=clang-mp-9.0 -DCMAKE_CXX_COMPILER=clang++-mp-9.0
> cmake --build . --target check-mlir

Here is the output for the current version:
[config.txt](https://github.com/llvm/llvm-project/files/4235853/config.txt)

If I try to replicate the first failed test, I get this output:
[error.txt](https://github.com/llvm/llvm-project/files/4235851/error.txt)

Best,
dpotop

**Comment by joker-eph** [comment]
Can you provide your git hash? We can’t really reproduce without.
Also a problem with the cpu runner was fixed yesterday, you may just need to pull.

**Comment by dpotop** [comment]
Here is the hash:

> wifi-eduroam-85-075:llvm-project llvm-test$ git log -1
> commit dbfc682e2ba2581e214fabb04ba1b555ff8b274a (HEAD -> master, origin/master, origin/HEAD)
>
