### ISSUE TITLE
Conflicting method signatures are not an error when using ARC

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14217]
|  |  |
| --- | --- |
| Bugzilla Link | [13845](https://llvm.org/bz13845) |
| Version | 3.1 |
| OS | MacOS X |
| Attachments | [A small ill-formed program that clang doesn't catch when using ARC](https://user-images.githubusercontent.com/60944935/143746018-9db17343-fe17-4395-bdb7-aee8ff21e8e7.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @gottesmm |

## Extended Description 
Currently, the following program compiles:

	@interface Foo : NSObject
	-(id)foo;
	@end
	
	@implementation Foo
	-(void)foo {}
	@end

Notice that `foo` is supposed to return an `id` but its implementation returns `void`. This causes clang to emit this warning:

	warning: conflicting return type in implementation of 'foo': 'id' vs 'void'

However, with ARC, this will often cause a crash when you use something like `id bar = [myFoo foo]`, because it tries to retain an undefined value.

[Section 3.3.1 of the ARC document][1] states that:

> In general, a program which attempts to implicitly or explicitly convert a value of retainable object pointer type to any non-retainable type, or vice-versa, is ill-formed.

`void` to `id` should be a very good example of an illegal conversion.

Currently, ARC conversion rules are enforced with compile-time errors. Clang should therefore emit an error if incompatible signatures would cause an illegal conversion (or ban incompatible signatures altogether when using ARC).

  1: http://clang.llvm.org/docs/AutomaticReferenceCounting.html#objects.restrictions.conversion

**Comment by AaronBallman** [comment]
I cannot reproduce this issue (https://godbolt.org/z/xbbdhr6of), so closing the bug. However, if you are still seeing the issue, please reopen with additional steps to reproduce.
