### ISSUE TITLE
Local variable has incorrect value

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14227]
|  |  |
| --- | --- |
| Bugzilla Link | [13855](https://llvm.org/bz13855) |
| Version | unspecified |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @isanbard |

## Extended Description 
NS_INLINE void codeRepresentation(NSSet *set, NSMutableString *buffer) {
    if (set.count == 1) {
        OpBase<OpCodeEmulator> *op = [set anyObject];
        if (getRegisterObject(op)) {
            [buffer appendString:[getRegisterObject(op) stringRepresentation]];
        } else {
            [op printValueCode:buffer];
        }
    } else if (set.count > 1) {
        OpBase<OpCodeEmulator> *op = [set anyObject];
        [buffer appendString:[getRegisterObject(op) stringRepresentation]]; // <--debugger breakpoint sees "op = nil", while it has a value
    } else {
        @&#8203;throw [NSException exceptionWithName:@"Getting code represenrarion from empty set!"
                                       reason:nil
                                     userInfo:nil];
    }
}

Solution:
NS_INLINE void codeRepresentation(NSSet *set, NSMutableString *buffer) {
    OpBase<OpCodeEmulator> *op = [set anyObject]; //put the variable in parent scope
    if (set.count == 1) {
        if (getRegisterObject(op)) {
            [buffer appendString:[getRegisterObject(op) stringRepresentation]];
        } else {
            [op printValueCode:buffer];
        }
    } else if (set.count > 1) {
        [buffer appendString:[getRegisterObject(op) stringRepresentation]]; // <--debugger breakpoint sees valid value
    } else {
        @&#8203;throw [NSException exceptionWithName:@"Getting code represenrarion from empty set!"
                                       reason:nil
                                     userInfo:nil];
    }
}

Solution #&#8203;2:
NS_INLINE void codeRepresentation(NSSet *set, NSMutableString *buffer) {
    if (set.count == 1) {
        OpBase<OpCodeEmulator> *op_a = [set anyObject]; //Rename op to op_a
        if (getRegisterObject(op_a)) {
            [buffer appendString:[getRegisterObject(op_a) stringRepresentation]];
        } else {
            [op printValueCode:buffer];
        }
    } else if (set.count > 1) {
        OpBase<OpCodeEmulator> *op_b = [set anyObject]; //Rename op to op_b
        [buffer appendString:[getRegisterObject(op_b) stringRepresentation]]; // <--debugger breakpoint sees valid value
    } else {
        @&#8203;throw [NSException exceptionWithName:@"Getting code represenrarion from empty set!"
                                       reason:nil
                                     userInfo:nil];
    }
}

**Comment by DavidSpickett** [comment]
No response here for many years, closing.
