### ISSUE TITLE
clang incorrectly diagnoses template operator* as invalid

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#14241]
|  |  |
| --- | --- |
| Bugzilla Link | [13869](https://llvm.org/bz13869) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Testcase (from g++.old-deja/g++.pt/overload8.C):

struct baz;
void operator*(baz&, double);
template <class T> inline T operator*(double s, const T &p);
void m(baz& a) { a * .5; }

gcc accepts this; clang gives an error "overloaded 'operator*' must have at least one parameter of class or enumeration type".  Doug says clang should accept this.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 4. GCC and MSVC accept both test cases:
https://godbolt.org/z/9eq5rd5Y7
https://godbolt.org/z/dfYchjr7c
