### ISSUE TITLE
MCDisassembler getInstruction API

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14285]
|  |  |
| --- | --- |
| Bugzilla Link | [13913](https://llvm.org/bz13913) |
| Version | 3.1 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Hi,
    I use MC getInstruction API to decode ARM instructions.

one of the instructions has problem,

The instruction is

e51f3000        ldr     r3, [pc, #-0]

Then I extract MCOperand m from MCInst,

For the offset MCOperand, I call m->getImm() ; 

It does not return 0 but a big number 2147483648

Have A Nice Day

Chia Lun

**Comment by arsenm** [comment]
Unclear to me what's being asked here
