### ISSUE TITLE
cmake names clang library as liblibclang.dll on Windows 7 64 bit

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14281]
|  |  |
| --- | --- |
| Bugzilla Link | [13909](https://llvm.org/bz13909) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 
On Windows 7 64 bit, the Mingw compiler names the libclang library "liblibclang.dll", instead of "libclang.dll". This prevents the python libclang bindings from running, as they are written to load "libclang.dll" . I believe that this is caused by a configuration patch, meant to satisfy Visual Studios naming convention for libraries, however I do not have enough expertise with the configuration system to create a patch or fix to explicitly disable this naming configuration on Mingw builds

**Comment by arsenm** [comment]
Has linked fix
