### ISSUE TITLE
Missing setAlignment on Alloca in the C API

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14348]
|  |  |
| --- | --- |
| Bugzilla Link | [13976](https://llvm.org/bz13976) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
In the llvm-c C bindings I only see LLVMSetAlignment for Global values, but I don't see an equivalent for Alloca (or Load or Store).

**Comment by arsenm** [comment]
LLVMSetAlignment looks like it should handle this case
