### ISSUE TITLE
Compilation warning on windows MSVS 2010 with hexagon backend.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14373]
|  |  |
| --- | --- |
| Bugzilla Link | [14001](https://llvm.org/bz14001) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie |

## Extended Description 
113>D:\llvm\include\llvm/Support/MathExtras.h(64): warning C4554: '<<' : check operator precedence for possible error; use parentheses to clarify precedence
113>          D:\llvm\include\llvm/Support/MathExtras.h(84) : see reference to function template instantiation 'bool llvm::isUInt<9>(uint64_t)' being compiled
113>          ..\..\..\..\lib\Target\Hexagon\HexagonInstrInfo.cpp(1325) : see reference to function template instantiation 'bool llvm::isShiftedUInt<6,3>(uint64_t)' being compiled
113>D:\llvm\include\llvm/Support/MathExtras.h(64): warning C4554: '<<' : check operator precedence for possible error; use parentheses to clarify precedence
113>          D:\llvm\include\llvm/Support/MathExtras.h(84) : see reference to function template instantiation 'bool llvm::isUInt<7>(uint64_t)' being compiled
113>          ..\..\..\..\lib\Target\Hexagon\HexagonInstrInfo.cpp(1335) : see reference to function template instantiation 'bool llvm::isShiftedUInt<6,1>(uint64_t)' being compiled

**Comment by arsenm** [comment]
Old build issue
