### ISSUE TITLE
PreprocessingRecord assertion failure, line 257

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14389]
|  |  |
| --- | --- |
| Bugzilla Link | [14017](https://llvm.org/bz14017) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [The source that triggers the error](https://user-images.githubusercontent.com/60944935/143746120-9e4f9720-d632-4e2a-b01e-e5adf14b846e.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Clang fails with a correct source file:

E:\llvm\llvm\bin\Debug>c-index-test -test-load-source all fail.c
Assertion failed: (PreprocessedEntities.empty() || !SourceMgr.isBeforeInTranslat
ionUnit(BeginLoc, PreprocessedEntities.back()->getSourceRange().getBegin())) &&
"a macro directive was encountered out-of-order", file .\PreprocessingRecord.cpp
, line 257
libclang: crash detected during parsing: {
  'source_filename' : '(null)'
  'command_line_args' : ['fail.c'],
  'unsaved_files' : [],
  'options' : 1,
}
Unable to load translation unit!

**Comment by cor3ntin** [comment]
Unable to reproduce on clang 17
