### ISSUE TITLE
clang does not set DAZ flag in -ffast-math mode

### ISSUE THREAD

**Issue by tobiasgrosser** [llvm/llvm-project#14396]
|  |  |
| --- | --- |
| Bugzilla Link | [14024](https://llvm.org/bz14024) |
| Version | trunk |
| OS | Linux |
| Attachments | [Test case](https://user-images.githubusercontent.com/92601279/143746125-e4eea491-78b2-4a0e-bb89-3a8a877954c5.gz) |
| CC | @andykaylor,@d0k,@gnzlbg,@arsenm |

## Extended Description 

$gcc jacobi_1d.DenormalsAreZero.c -O3
$time ./a.out 
real	0m20.164s

$gcc jacobi_1d.DenormalsAreZero.c -O3 -ffast-math
$time ./a.out 
real	0m0.357s

$clang jacobi_1d.DenormalsAreZero.c -O3
$time ./a.out 
real	0m36.660s

$clang jacobi_1d.DenormalsAreZero.c -O3 -ffast-math
$time ./a.out 
real	0m36.431s

As can be seen the gcc produced binary is a lot faster than clang in -ffast-mode (besides being a little bit faster in general). This is not caused by better optimizations, but because gcc links in a small function into the resulting binary, which sets the DAZ register.

From [1]:

"DAZ tells the CPU to force all Denormals to zero. A Denormal is a number that is so small that FPU can't renormalize it due to limited exponent ranges. They're just like normal numbers, but they take considerably longer to process. Note that not all processors support DAZ."

The test case happens to calculate a lot of these close-to-zero values. Hence, setting the register has a big impact.

[1] http://softpixel.com/~cwright/programming/simd/sse.php

**Comment by jyknight** [comment]
This was resolved by r165240 (aka 058666a8d02f5cd348150862a3401c9c4bd0b4d0) back in 2012, not sure why it wasn't closed then.
