### ISSUE TITLE
LLDB page doesn't clarify where to find the build output

### ISSUE THREAD

**Issue by 84cb368b-a7ae-40d6-bde1-4a04fa9aa698** [llvm/llvm-project#14439]
|  |  |
| --- | --- |
| Bugzilla Link | [14067](https://llvm.org/bz14067) |
| Version | unspecified |
| OS | MacOS X |
| CC | @jryans,@labath |

## Extended Description 
Regarding http://lldb.llvm.org/build.html

I have build LLDB on Mac using the Xcode project as detailed on that page. This may be silly, but I can't find where the lldb binary that has been produced is stored. There is no file called 'lldb' under the LLDB source directory. It would be really helpful if that page therefore provided some hints as to where to find it for people that are not used to using Xcode. (I'd also like to install it into $HOME, so if that isn't as straightforward as simply copying the binary there, then maybe instructions could be added for that at the same time?)

**Comment by DavidSpickett** [comment]
`lldb` will be in in `<build-dir>/bin/`. Making Xcode use the built lldb sounds possible but likely a hack that is not adviseable.

Latest build docs are here https://lldb.llvm.org/resources/build.html.
