### ISSUE TITLE
Compile HandBrake ( Media Transcoder Program ) Failed

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14461]
|  |  |
| --- | --- |
| Bugzilla Link | [14089](https://llvm.org/bz14089) |
| Version | trunk |
| OS | Linux |
| Attachments | [rv34-dbccpI.c and rv34-dbccpI.sh](https://user-images.githubusercontent.com/60944935/143746173-8c223b3f-0804-4030-af82-6b5cc3b2e6f9.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @d0k,@stoklund |

## Extended Description 

config.info

probe: host tuple...(pass) x86_64-unknown-linux-gnu
compute: available architectures...(pass) x86_64
find: ar...(pass) /usr/bin/ar
find: cp...(pass) /bin/cp
find: curl...(pass) /usr/bin/curl
find: gcc...(pass) /usr/bin/gcc
find: gmake...(pass) /usr/bin/make
find: m4...(pass) /usr/bin/m4
find: mkdir...(pass) /bin/mkdir
find: gpatch...(pass) /usr/bin/patch
find: rm...(pass) /bin/rm
find: ranlib...(pass) /usr/bin/ranlib
find: strip...(pass) /usr/bin/strip
find: gtar...(pass) /bin/tar
find: wget...(pass) /usr/bin/wget
find: yasm...(pass) /usr/bin/yasm
find: autoconf...(pass) /usr/bin/autoconf
find: automake...(pass) /usr/bin/automake
find: libtool...(pass) /usr/bin/libtool
find: xcodebuild...(fail) not found
find: lipo...(fail) not found
select: fetch...(pass) wget (/usr/bin/wget)
compute: build tuple...(pass) x86_64-unknown-linux-gnu
probe: number of CPU cores...(pass) 4
probe: svn info...(pass) svn://svn.handbrake.fr/HandBrake/trunk
compute: project data...(pass) HandBrake (unofficial)
compute: makevar SRC/    = ..
compute: makevar BUILD/  = .
compute: makevar PREFIX/ = /usr
mkdir: ./build
chdir: ./build
write: GNUmakefile
mkdir: project
write: project/handbrake.m4
mkdir: log
write: log/build.txt
time begin: Tue Oct 16 00:04:18 2012
launch: /usr/bin/make -j1
time end: Tue Oct 16 00:22:15 2012
duration: 17 minutes, 56 seconds (1076.99s)
result: FAILURE (code 2)

build.info

1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'libavcodec/rv34.c'.
4.	Running pass 'Simple Register Coalescing' on function '@rv34_pred_mv_b'
clang: error: unable to execute command: Aborted
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.2 (trunk 165911)
Target: x86_64-unknown-linux-gnu
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/rv34-dbccpI.c
clang: note: diagnostic msg: /tmp/rv34-dbccpI.sh
clang: note: diagnostic msg: 

********************
make[1]: *** [libavcodec/rv34.o] 错误 254
make[1]:正在离开目录 `/home/houge/Tool/handbrake/hb-trunk/build/contrib/ffmpeg/libav-v0.8-2551-gc83f44d'
make: *** [contrib/ffmpeg/.stamp.build] 错误 2
time end: Tue Oct 16 00:22:15 2012
duration: 17 minutes, 56 seconds (1076.99s)
result: FAILURE (code 2)

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.0 through 3.2 with assertions enabled.
