### ISSUE TITLE
Pre-increment operator not working for variable.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14540]
|  |  |
| --- | --- |
| Bugzilla Link | [14168](https://llvm.org/bz14168) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
In the below test case, the value of i not incremented after call to va_arg:

#include <stdarg.h>

extern void exit (int);
extern void abort (void);

int a[10];
int i = 9;

void
f (int n, ...)
{
  va_list ap;
  va_start (ap, n);
  va_arg (ap, typeof(int (*)[++i]));
  if (i != n)
    abort ();
  va_end (ap);
  
  }

int
main (void)
{
  f (10, &a);
  exit (0);
}

Further , on modifying the TC to :

int a[1];
int main()
{
 int i = 0;
 
 a[0] = 1;
 typeof(int (*)[++i]) a1 = &a;
}

i is getting properly incremented.

Is their any how , clang is bypassing the increment of i in the 1st case.

**Comment by wheatman** [comment]
This was fixed between 3.4.1 and 3.5
https://godbolt.org/z/3cfaevv7b

code
```
#include <stdarg.h>

int a[10];
int i = 9;

int
f (int n, ...)
{
  va_list ap;
  va_start (ap, n);
  va_arg (ap, typeof(int (*)[++i]));
  if (i != n)
    return 1;
  va_end (ap);
  return 0;
  
  }

int
main ()
{
  return f (10, &a);
}
```

should return 0
