### ISSUE TITLE
Bitcode Reader/Assembler incorrectly  handles structs of arrays in different address space.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14544]
|  |  |
| --- | --- |
| Bugzilla Link | [14172](https://llvm.org/bz14172) |
| Version | trunk |
| OS | Linux |
| Attachments | [Patch that fixes the issue](https://user-images.githubusercontent.com/60944935/143746234-378d71d7-0273-4f1f-82fb-8fe271be47ae.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @ekatz |

## Extended Description 
; RUN: llvm-as < %s | llvm-dis > %t1.ll
; RUN: diff %s %t1.ll
target datalayout = "e-p:128:128:128-p1:32:32:32-p2:8:8:8-p3:16:16:16-p4:64:64:64-p5:96:96:96-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:32"

define i64 @&#8203;fa_1() nounwind {
  %t = ptrtoint { [7 x double], [7 x double] } addrspace(4)* null to i64
  ret i64 %t
}

define { [7 x double], [7 x double] } addrspace(4)* @&#8203;fa_2() nounwind {
  %t = getelementptr { [7 x double], [7 x double] } addrspace(4)* null, i64 11
  ret { [7 x double], [7 x double] } addrspace(4)* %t
}

define i64 @&#8203;fa_3() nounwind {
  %t = ptrtoint { [7 x double], [7 x double] } addrspace(4)* getelementptr ({ [7 x double], [7 x double] } addrspace(4)* null, i64 11) to i64
  ret i64 %t
}

define i64 @&#8203;fa_4() nounwind {
  %t = mul i64 ptrtoint ({ [7 x double], [7 x double] } addrspace(4)* getelementptr ({ [7 x double], [7 x double] } addrspace(4)* null, i64 11) to i64), 5
  ret i64 %t
}

define i64 @&#8203;fa_5() nounwind {
  %t = bitcast i64 mul (i64 3, i64 mul (i64 ptrtoint ({ [7 x double], [7 x double] } addrspace(4)* getelementptr ({ [7 x double], [7 x double] } addrspace(4)* null, i64 11) to i64), i64 5)) to i64
  ret i64 %t
}

The above test case fails when being run because fa_4 and fa_5 do not produce the same code at assembly, the structs { [7 x double], [7 x double] } addrspace(4) somehow get incorrectly mapped to double*.

**Comment by arsenm** [comment]
Only diff I see is in the comments at the top
