### ISSUE TITLE
Handling ptrtoint and inttoptr

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14551]
|  |  |
| --- | --- |
| Bugzilla Link | [14179](https://llvm.org/bz14179) |
| Version | trunk |
| OS | All |
| Attachments | [the test case described above](https://user-images.githubusercontent.com/60944935/143746239-f0f5ba0e-d2e3-4f11-bcf4-f4303d68aa65.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

DataStructureAA doesn't seem to handle ptrtoint and inttoptr. 

; ModuleID = 'test.bc'
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define i32 @&#8203;main(i32 %argc, i8** nocapture %argv) nounwind uwtable readnone {
entry:
  %int_1 = ptrtoint i8** %argv to i64
  %int_2 = ptrtoint i8** %argv to i64
  %ptr_1 = inttoptr i64 %int_1 to i8*
  %ptr_2 = inttoptr i64 %int_2 to i8*
  call void @&#8203;foo(i8* %ptr_1, i8* %ptr_2)
  ret i32 0
}

declare void @&#8203;foo(i8* %a, i8* %b) nounwind

DataStructureAA reports %ptr_1 and %ptr_2 don't alias, but they are both derived from %argv.

**Comment by arsenm** [comment]
DataStructureAA no longer exists
