### ISSUE TITLE
Report Diagnostic ID for diagnostics

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14581]
|  |  |
| --- | --- |
| Bugzilla Link | [14209](https://llvm.org/bz14209) |
| Version | trunk |
| OS | All |
| Attachments | [Communication with Ted](https://user-images.githubusercontent.com/60944935/143746279-bc21528e-41d2-403d-8c4f-29c051071022.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Hi,
There is no ErrorID or StaticAnalyzerCheckerID associated with diagnostics being reported.
e.g.
Core.1: The right operand of '==' is a garbage value
Security.2: < diagnostic >
DeadCode.4: <diagnostic>
 
Also IDs can be assigned to compiler error being reported.
e.g. ERROR.1001 - expected identifier or '('
FATAL.234 - 'a.h' file not found

It will help categorize the diagnostics in report.

**Comment by AaronBallman** [comment]
Clang has supported [-fdiagnostics-show-category=](https://clang.llvm.org/docs/UsersManual.html#cmdoption-fdiagnostics-show-category) since at least Clang 3.0.0: https://godbolt.org/z/Pbhq4a1q7 so closing this as complete.
