### ISSUE TITLE
Consider synthesizing ptrint + arithmetic + inttoptr to GEP

### ISSUE THREAD

**Issue by dfef8e66-2662-460a-96b9-d5b30d268030** [llvm/llvm-project#14598]
|  |  |
| --- | --- |
| Bugzilla Link | [14226](https://llvm.org/bz14226) |
| Version | trunk |
| OS | All |
| CC | @majnemer,@efriedma-quic,@hfinkel,@Trass3r |

## Extended Description 
This is a feature request to start a discussion on consideration of turning constructs like 
%4 = ptrtoint i8* %3 to i64
%5 = add i64 %4, 5
%6 = inttoptr i64 %5 to i8*

into a single gep
%4 = gep %3, 5

(Whenever possible) as an early optimization; as GEPs. Since GEP is optimized a lot by other optimization psses.

**Comment by arsenm** [comment]
This is an invalid recurring request
