### ISSUE TITLE
[BB Vectorize ]oggenc with -vectorize fails

### ISSUE THREAD

**Issue by hfinkel** [llvm/llvm-project#14603]
|  |  |
| --- | --- |
| Bugzilla Link | [14231](https://llvm.org/bz14231) |
| Version | trunk |
| OS | Linux |
| Attachments | [The output bugpoint files](https://user-images.githubusercontent.com/910929/143746298-046a1336-0a55-44da-9859-bc5586bb5efe.gz) |

## Extended Description 

oggenc with -O3 -vectorize on x86_64 fails. bugpoint seems to feel that this is a backend problem.

clang -D_GNU_SOURCE -D__STDC_LIMIT_MACROS -DNDEBUG -S -emit-llvm -o oggenc.ll oggenc.c
bugpoint -O3 -run-int -vectorize oggenc.ll --args -Q -s 901820 tune --opt-args -mtriple=x86_64-unknown-linux-gnu
...
*** The following function is being miscompiled:  strncpy_filtered_while.cond_if.end26
<llc><gcc>You can reproduce the problem with the command line: 
  llc bugpoint.test.bc -o bugpoint.test.bc.s
  gcc ./bugpoint.safe.bc.llc.s.so bugpoint.test.bc.s -o bugpoint.test.bc.exe -Wl,-R.
  bugpoint.test.bc.exe -Q -s 901820 tune
The shared object was created with:
  llc -march=c bugpoint.safe.bc -o temporary.c
  gcc -xc temporary.c -O2 -o ./bugpoint.safe.bc.llc.s.so -fPIC -shared -fno-strict-aliasing

The "tune" input file is the one from the test suite.

If I run bugpoint with -llc-safe, then it detects the miscompilation, but says that it cannot help.

**Comment by arsenm** [comment]
BBVectorize was removed in 3545a9e1f9145df7f67428cf8eca9d0053f44e67
