### ISSUE TITLE
clang/docs/Makefile is not safe for multithreading

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14629]
|  |  |
| --- | --- |
| Bugzilla Link | [14257](https://llvm.org/bz14257) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie |

## Extended Description 
The relevant failing part of a build with --enable-doxygen and two build jobs is the following:

make[3]: Entering directory `/usr/src/llvm-3.1.src/tools/clang/docs'
llvm[3]: Building doxygen documentation
llvm[3]: Packaging HTML documentation
[some unrelated warnings about obsolete symbols in doxygen.cfg...]
Notice: Output directory `/usr/src/llvm-3.1.src/tools/clang/docs/doxygen' does not exist. I have created it for you.
llvm[3]: Packaging doxygen documentation
/bin/tar: doxygen: file changed as we read it
make[3]: *** [/usr/src/llvm-3.1.src/tools/clang/docs/doxygen.tar.gz] Error 1
make[3]: *** Waiting for unfinished jobs....
warning: source /usr/src/llvm-3.1.src/tools/clang/docs/img is not a readable file or directory... skipping.
Searching for include files...
Searching for files in directory /usr/src/llvm-3.1.src/tools/clang/include
Searching for files in directory /usr/src/llvm-3.1.src/tools/clang/include/clang
Searching for files in directory /usr/src/llvm-3.1.src/tools/clang/include/clang/Analysis
[...]

Observe that (1.) the "Packaging ... documentation" goals doesn't wait for the "Building doxygen documentation" goal and (2.) the doxygen job goes on and produces over 5000 dot graphs before the
build actually fails!
Also you might not want to build all these graphs by default in the first place when building the documentation (at least not for releases), but that's a different story.

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
