### ISSUE TITLE
Allow disabling backtrace support by environment variable

### ISSUE THREAD

**Issue by jsonn** [llvm/llvm-project#14633]
|  |  |
| --- | --- |
| Bugzilla Link | [14261](https://llvm.org/bz14261) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Bugs like 14260 can result in nasty dead locks at least on Linux. Problem is that the malloc lock is hold by the current thread and backtrace in glibc wants to allocate more memory. It would be nice to disable the fancy signal handlers via environment to make it easier to build test cases without having to hack the source.

**Comment by arsenm** [comment]
I assume this is covered by LLVM_DISABLE_CRASH_REPORT and LLVM_DISABLE_SYMBOLIZATION
