### ISSUE TITLE
Partial ordering of variadic function template

### ISSUE THREAD

**Issue by HighCommander4** [llvm/llvm-project#14744]
|  |  |
| --- | --- |
| Bugzilla Link | [14372](https://llvm.org/bz14372) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
According to the last example in temp.func.order (14.5.6.2), the call to f
below should be ambiguous, but clang compiles the code and the calls #&#8203;2:

template <class T, class... U> void f(T, U...);    // #&#8203;1
template <class T            > void f(T);          // #&#8203;2

void h(int i)
{
    f(&i);  // should be ambiguous, but calls #&#8203;2
}

Test with trunk revision 168277.

**Comment by mizvekov** [comment]
This has already been fixed in clang 16. All the other compilers still accept it though.

https://godbolt.org/z/Yr5bT81Kb
