### ISSUE TITLE
__int128 atomic hangs compiler

### ISSUE THREAD

**Issue by a8b4922b-9ceb-405e-9794-fa0271302cc2** [llvm/llvm-project#14814]
|  |  |
| --- | --- |
| Bugzilla Link | [14442](https://llvm.org/bz14442) |
| Version | trunk |
| OS | Linux |
| CC | @efriedma-quic,@ekatz |

## Extended Description 
$ clang++ -v
clang version 3.3 (trunk 168584)
Target: x86_64-unknown-linux-gnu
Thread model: posix

$ cat /tmp/test.cc
```c
int main() {
	__int128 a;
	__sync_fetch_and_add(&a, 1);
}
```
$ clang++ /tmp/test.cc
[burns 100% CPU and hangs forever in]

#&#8203;0  0x0000000000b943df in llvm::DAGTypeLegalizer::ExpandAtomic(llvm::SDNode*) ()
#&#8203;1  0x0000000000bacf42 in llvm::DAGTypeLegalizer::ExpandIntegerResult(llvm::SDNode*, unsigned int) ()
#&#8203;2  0x0000000000b3f40c in llvm::SelectionDAG::LegalizeTypes() ()
#&#8203;3  0x0000000000aee1a9 in llvm::SelectionDAGISel::CodeGenAndEmitDAG() ()
#&#8203;4  0x0000000000af4e4e in llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) ()
#&#8203;5  0x0000000000af5fb8 in llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) ()
#&#8203;6  0x00000000010f024c in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
#&#8203;7  0x00000000010f02f3 in llvm::FPPassManager::runOnModule(llvm::Module&) ()
#&#8203;8  0x00000000010efe66 in llvm::MPPassManager::runOnModule(llvm::Module&) ()
#&#8203;9  0x00000000010effa2 in llvm::PassManagerImpl::run(llvm::Module&) ()
#&#8203;10 0x00000000011e886a in clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::Module*, clang::BackendAction, llvm::raw_ostream*) ()
#&#8203;11 0x00000000011e61a0 in clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) ()
#&#8203;12 0x000000000146c5ee in clang::ParseAST(clang::Sema&, bool, bool) ()
#&#8203;13 0x00000000013b3a81 in clang::FrontendAction::Execute() ()
#&#8203;14 0x0000000001396aa0 in clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) ()
#&#8203;15 0x00000000011c8aca in clang::ExecuteCompilerInvocation(clang::CompilerInstance*) ()
#&#8203;16 0x0000000000640690 in cc1_main(char const**, char const**, char const*, void*) ()
#&#8203;17 0x00000000006274a2 in main ()

**Comment by philnik777** [comment]
Looks like this got fixed before the release: https://godbolt.org/z/KzofEWffx
