### ISSUE TITLE
LTO crash with very big C++ files

### ISSUE THREAD

**Issue by ismail** [llvm/llvm-project#14866]
|  |  |
| --- | --- |
| Bugzilla Link | [14494](https://llvm.org/bz14494) |
| Version | trunk |
| OS | Linux |
| Attachments | [lto-clang.tar.bz2 (sample project to reproduce the issue)](https://user-images.githubusercontent.com/4255/143746459-6fa9fe0e-1fc9-45f6-8021-064ef421bcae.gz), [gdb.out (gdb output)](https://user-images.githubusercontent.com/4255/143746461-16b3cc0f-5bdf-4453-8914-68c6caedeeba.gz), [valgrind log](https://user-images.githubusercontent.com/4255/143746462-41a80a6c-e704-4d3a-8236-ef9554c0334c.gz) |
| CC | @isanbard,@zygoloid |

## Extended Description 

Hi;

Unpack lto-clang.tar.bz2 and run make, you'll end up with:

clang: error: unable to execute command: Segmentation fault
clang: error: linker command failed due to signal (use -v to see invocation)

This is with llvm/clang r169119 from trunk.

Operating system is Linux/x86-64.
Using binutils 2.23.1

gdb output is in gdb.out file.

**Comment by EugeneZelenko** [comment]
@ismail: Could you please elaborate on reason(s) and also add relevant label(s)?
