### ISSUE TITLE
assert on unused deleted copy constructor with default argument

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#14871]
|  |  |
| --- | --- |
| Bugzilla Link | [14499](https://llvm.org/bz14499) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Clang asserts in IRGen when given this:

struct S { S(int); S(const S & = 0) = delete; } s(0);

Apparently IRGen is trying to look at the exception specification for the deleted copy constructor?

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.1 and 3.2 with assertions enabled: https://godbolt.org/z/d9oKv87j4
