### ISSUE TITLE
The initial email in a phab review email thread is often marked as spam for me

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#14882]
|  |  |
| --- | --- |
| Bugzilla Link | [14510](https://llvm.org/bz14510) |
| Version | unspecified |
| OS | All |
| CC | @zmodem |

## Extended Description 
Replies often make it through fine though, which makes phab reviews look strange to me.

It looks like this is related to me subscribing to cfe-commits with my @&#8203;chromium.org address, which just forwards to my @&#8203;google address.

This only happens for phab reviews sent from people form an @&#8203;google address.

**Comment by arsenm** [comment]
Phabricator will be deprecated soon
