### ISSUE TITLE
SAFECode Clang does not export symbols like standard Clang

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14893]
|  |  |
| --- | --- |
| Bugzilla Link | [14521](https://llvm.org/bz14521) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
To fix PR#14509, I disabled the options in Clang's Makefiles that control the exporting of symbols.  While this probably won't be an issue for SAFECode users, it would be nice to have symbols exported properly.

**Comment by Endilll** [comment]
SAFECode is archived.
