### ISSUE TITLE
Reload from load invariant address is not hoisted out of the loop

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14894]
|  |  |
| --- | --- |
| Bugzilla Link | [14522](https://llvm.org/bz14522) |
| Version | trunk |
| OS | All |
| Attachments | [Test case](https://user-images.githubusercontent.com/60944935/143746469-6dd8a385-aacd-48b3-9178-c7aa466ef923.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @chandlerc |

## Extended Description 
In the attached test case we have the following loop:

  wideptr = (uint64_t*)ptr;
  while (len >= sizeof(wideval)) {
    *wideptr++ = wideval;
    len -= sizeof(wideval);
  }

(note that wideval is loop invariant)

When compiled with clang -O2 we get the following code:

LBB0_5:                                 ## %while.body18
                                        ## =>This Inner Loop Header: Depth=1
        movq    -8(%rbp), %rcx  <-- load of wideval we want to get rid of
        movq    %rcx, (%rax)
        addq    $8, %rax
        addq    $-8, %rdx
        cmpq    $7, %rd.
        ja      LBB0_5

wideval is initialized in the following loop:

  /* Get to 8-byte aligned start */
  tmp = (unsigned char*)&wideval;
  for (i = 0; i < sizeof(wideval); i++, tmp++) {
    *tmp = val;
  }

When this loop gets unrolled there's an opportunity for SROA to combine the eight 8-bit stores into a single 64-bit store and the corresponding i64 value for wideval can be used directly in the copy loop without going through memory.

When compiling the test case with clang -O2 and then feeding the generated LLVM IR into opt -O2, SROA kicks in and as expected we get the following code:

LBB0_6:                                 ## %while.body18
                                        ## =>This Inner Loop Header: Depth=1
        movq    %rcx, (%rax)
        addq    $8, %rax
        addq    $-8, %rdx
        cmpq    $7, %rdx
        ja      LBB0_6

With a single invocation of clang -O2 the optimization does not kick in because SROA is run before the loop unrolling happens.

Tested with trunk169456.

**Comment by xgupta** [comment]
This issue is fixed on trunk -https://godbolt.org/z/W9b35rKPq, wideval is hosted outside of loop. hence closing.
```
.LBB0_11:                               # %while.body12
        mov     qword ptr [rcx], rax
        add     rcx, 8
        add     rdx, -8
        cmp     rdx, 7
        ja      .LBB0_11
```
