### ISSUE TITLE
Backtrace command does not display c++ member function names on Linux or FreeBSD

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14912]
|  |  |
| --- | --- |
| Bugzilla Link | [14540](https://llvm.org/bz14540) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @emaste |

## Extended Description 
Doing a backtrace during a c++ program sometimes does not display the names of member functions correctly.

For example, on Linux, lldb reports:

 frame #&#8203;0: 0x0000000000400a72 a.out`C + 50 at main.cpp:93
 frame #&#8203;1: 0x00000000004008f7 a.out`C + 39 at main.cpp:94
 frame #&#8203;2: 0x0000000000400727 a.out`main + 87 at main.cpp:121
 frame #&#8203;3: 0x00007f04ab6b676d libc.so.6`__libc_start_main + 237
 frame #&#8203;4: 0x0000000000400609 a.out`_start + 41

The name of C's constructor "C::C" is not displayed in any frame.

To reproduce the above, build lldb (with clang) and run:

./dotest.py -A x86_64 -C /home/pulse_agent/bin/clang -v -t -f IterateFrameAndDisassembleTestCase.test_with_dwarf_and_python_api

**Comment by DavidSpickett** [comment]
Appears to be working as of today:
```
(lldb) b C::Member
Breakpoint 2: where = test.o`C::Member() + 8 at test.cpp:3:18, address = 0x0000000000000760
(lldb) run
Process 2745577 launched: '/tmp/test.o' (aarch64)
Process 2745577 stopped
* thread #1, name = 'test.o', stop reason = breakpoint 2.1
    frame #0: 0x0000aaaaaaaaa760 test.o`C::Member(this=0x0000fffffffff24b) at test.cpp:3:18
   1    struct C {
   2      C() { Member(); };
-> 3      void Member() {}
   4    };
   5
   6    int main(){
   7      C c;
(lldb) bt
* thread #1, name = 'test.o', stop reason = breakpoint 2.1
  * frame #0: 0x0000aaaaaaaaa760 test.o`C::Member(this=0x0000fffffffff24b) at test.cpp:3:18
    frame #1: 0x0000aaaaaaaaa74c test.o`C::C(this=0x0000fffffffff24b) at test.cpp:2:9
```

Closing.
