### ISSUE TITLE
Bad diagnostic when omitting #include <vector> but having #include <iterator>

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#14914]
|  |  |
| --- | --- |
| Bugzilla Link | [14542](https://llvm.org/bz14542) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor |

## Extended Description 
I got this when building chromium with libc++:
```
../../chrome/browser/intents/cws_intents_registry.h:41:16: error: too few template arguments for class template 'vector'
  typedef std::vector<IntentExtensionInfo> IntentExtensionList;
               ^
/Users/thakis/src/libcxx/include/iterator:1197:53: note: template is declared here
    template <class _Tp, class _Alloc> friend class vector;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~              ^
1 error generated.
```

The fix was just to add a `#include <vector>`

Maybe clang could detect that it's only seen a declaration of a template and not a definition and say "note: try including the header with the definition of class template 'vector'".

**Comment by philnik777** [comment]
This has been addressed in libc++ by always providing the defaulted second argument.
