### ISSUE TITLE
Should split libcodegen into libcodegen and libmachine

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#1493]
|  |  |
| --- | --- |
| Bugzilla Link | [1121](https://llvm.org/bz1121) |
| Version | 1.0 |
| OS | All |
| CC | @asl |

## Extended Description 
lib/Codegen/* contains two separate things: implementations of the Machine* classes (e.g. 
MachineBasicBlock) and a collection of code generator-related passes.

We should split this into two pieces: lib/CodeGen/Machine and lib/Codegen.  The reason for this is that 
individual targets (e.g. the PPC target) should depend (in a library dependence sense) on the machine bits, 
but not on the Codegen bits.  Currently, the various targets do depend on various machine code passes 
(e.g. the asmprinter) which causes large amounts of code to be linked in to apps that don't need it (e.g. lli 
gets asmprinter, machowriter, elfwriter, etc).  Once lib/CodeGen is split up, we can chase these 
dependencies down more easily and eliminate them.

-Chris

**Comment by arsenm** [comment]
I believe this is talking about the layering that became lib/CodeGen vs. lib/Target

**Comment by lattner** [comment]
Thank you for cleaning up these old bugs @arsenm!
