### ISSUE TITLE
eStateCrashed should be removed as a process state

### ISSUE THREAD

**Issue by andykaylor** [llvm/llvm-project#14970]
|  |  |
| --- | --- |
| Bugzilla Link | [14598](https://llvm.org/bz14598) |
| Version | unspecified |
| OS | All |

## Extended Description 
When the inferior process crashes, the process state should be eStateStopped with stop info used to describe the crashed state.  The eStateCrashed state should be removed.

Via e-mail from Greg Clayton:

After speaking with Jim Ingham, we came up with:

- eStateCrashed should be removed all together, anywhere that was using this should be changed to eStateStopped
- The thread stop info is where the info should be contained for crashes
- In the future, we should add a StopClass enumeration that has accessors on the thread stop info class where the enum is something like:

enum StopClass
{
   eStopClassNormal,    // Normal expected stop (used for breakpoints, watchpoints, etc)
   eStopClassCrash,     // Program will likely crash if there are no handlers installed
   eStopClassFatalCrash // This will always crash the program };

**Comment by bulbazord** [comment]
(Going through old bugs...)

I'm not sure we can remove eStateCrashed at this point if we want to maintain our commitment to stability. It will be an ABI compatibility issue (imagine if somebody built with eStateCrashed and we remove it only for the next value in the enum to take its place). It also will break python source compatibility if anyone is using eStateCrashed.

Should we close this?

**Comment by andykaylor** [comment]
I haven't done any work on LLDB since around the time this bug was filed, and I have absolutely no memory of what I was hoping to accomplish by requesting this removal. I think I was working on a Windows client for LLDB at the time, but I can't say that my work would have any connection to anything current. I have no objections to closing this bug, and I suspect a better solution has been found in the past 11 years.
