### ISSUE TITLE
"tentative array definition" points to the wrong decl

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14986]
|  |  |
| --- | --- |
| Bugzilla Link | [14614](https://llvm.org/bz14614) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Given

static int a16[];
extern int a16[];

clang prints

/test2.c:2:12: warning: tentative array definition assumed to have one element
extern int a16[];

It should probably point at the first declaration.

**Comment by AaronBallman** [comment]
This was fixed in Clang 3.3.0: https://godbolt.org/z/dj1Mqe3Gc
