### ISSUE TITLE
out-of-source build modifies src directory

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#14994]
|  |  |
| --- | --- |
| Bugzilla Link | [14622](https://llvm.org/bz14622) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
After a make using:

GNUMAKE=make /Volumes/proof/Users/rdm/root/interpreter/llvm/src/configure --prefix=/Volumes/proof/Users/rdm/a/interpreter/llvm/inst --disable-docs --disable-bindings --disable-visibility-inlines-hidden --enable-optimized --disable-assertions --enable-targets=host CC=clang CXX=clang++ CFLAGS=-m64 CXXFLAGS=-m64

I see, doing svn st --no-ignore in , the following build products:

I       interpreter/llvm/src/utils/llvm-build/llvmbuild/util.pyc
I       interpreter/llvm/src/utils/llvm-build/llvmbuild/componentinfo.pyc
I       interpreter/llvm/src/utils/llvm-build/llvmbuild/__init__.pyc
I       interpreter/llvm/src/utils/llvm-build/llvmbuild/configutil.pyc
I       interpreter/llvm/src/utils/llvm-build/llvmbuild/main.pyc

**Comment by Endilll** [comment]
I've built Clang 2.6 through 16, and was bitten by it.
It was fixed at some point, presumably in 3.x.
