### ISSUE TITLE
Do not know how to expand this operator's operand! UNREACHABLE executed at lib/CodeGen/SelectionDAG/LegalizeIntegerTypes.cpp:2451!

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15040]
|  |  |
| --- | --- |
| Bugzilla Link | [14668](https://llvm.org/bz14668) |
| Version | trunk |
| OS | FreeBSD |
| Attachments | [preprocessed source (boring...)](https://user-images.githubusercontent.com/60944935/143746582-fdd48997-bef5-4cfb-8e44-07205ada4e9a.gz), [run script (boring...)](https://user-images.githubusercontent.com/60944935/143746583-4cf5d1b8-0ee4-4993-b5ee-b810d8e73e9f.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @d0k,@nadavrot |

## Extended Description 
1. source code (file name: f.c):

int xs[16];

void f(int i)
{
	for (int i = 0; i < 16; i++)
		xs[i] = (long long)1 << i;
}

2. command line:

clang -O2 -c f.c

3. output:

ExpandIntegerOperand Op #&#8203;2: 0x2a968338: i32,i32 = shl_parts 0x2a961338, 0x2a961008, 0x2a9681a0 [ID=0]

Do not know how to expand this operator's operand!
UNREACHABLE executed at /usr/home/devhc/llvmhead/llvm/lib/CodeGen/SelectionDAG/LegalizeIntegerTypes.cpp:2451!
Stack dump:
0.	Program arguments: /usr/home/devhc/lllvm/bin/clang -cc1 -triple i386-unknown-freebsd10.0 -emit-obj -disable-free -main-file-name f.c -mrelocation-model static -mdisable-fp-elim -masm-verbose -mconstructor-aliases -target-cpu i486 -target-linker-version 2.17.50 -momit-leaf-frame-pointer -coverage-file /usr/home/devhc/delme/f.o -resource-dir /usr/home/devhc/lllvm/bin/../lib/clang/3.3 -fmodule-cache-path /var/tmp/clang-module-cache -O2 -fdebug-compilation-dir /home/devhc/delme -ferror-limit 19 -fmessage-length 82 -mstackrealign -fobjc-runtime=gnustep -fdiagnostics-show-option -fcolor-diagnostics -backend-option -vectorize-loops -o f.o -x c f.c 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'f.c'.
4.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@f'
clang: error: unable to execute command: Abort trap (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.3 (trunk 170622) (llvm/trunk 170620)
Target: i386-unknown-freebsd10.0
Thread model: posix

**Comment by arsenm** [comment]
Comment says fixed and mentions separate issue
