### ISSUE TITLE
Possible mistake in libTooling documentation.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15048]
|  |  |
| --- | --- |
| Bugzilla Link | [14676](https://llvm.org/bz14676) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @jryans |

## Extended Description 
The libTooling documentation says to run a tool like
```
  ./tool blah.h -- clang -fsyntax-only
```
However this produces a warning: "warning: clang: 'linker' input unused"
```
  ./tool blah.h -- clang -c -fsyntax-only
```
Also produces the same warning.
```
  ./tool blah.h -- -fsyntax-only
```
Works fine!

**Comment by JOE1994** [comment]
`Libtooling` documentation for Clang 18.1.0 no longer contains such directions:
* https://releases.llvm.org/18.1.0/tools/clang/docs/LibTooling.html
