### ISSUE TITLE
libtool: link messes up '-mllvm -vectorize' to '-mllvm -Wl,...'

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15088]
|  |  |
| --- | --- |
| Bugzilla Link | [14716](https://llvm.org/bz14716) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @brooksmoses |

## Extended Description 
Yes, it is actually a libtool issue but in the meantime clang should be able to handle this.

/bin/sh ../../../libtool  --tag=CC   --mode=link clang -fvisibility=hidden -Wall -std=c99 -Werror=implicit-function-declaration -Werror=missing-prototypes -fno-strict-aliasing -fno-builtin-memcmp -g -O0 -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -mllvm -vectorize -version-number 1:0:0 -no-undefined  -o libOpenVG.la -rpath /usr/lib64 entry.lo mapi.lo stub.lo table.lo u_current.lo u_execmem.lo -lpthread 

libtool: link: clang -shared  -fPIC -DPIC  .libs/entry.o .libs/mapi.o .libs/stub.o .libs/table.o .libs/u_current.o .libs/u_execmem.o   -lpthread  -O0 -O2 -mllvm   -Wl,-soname -Wl,libOpenVG.so.1 -o .libs/libOpenVG.so.1.0.0

clang-3: warning: argument unused during compilation: '-mllvm -Wl,-soname'

/usr/bin/ld: cannot find libOpenVG.so.1: No such file or directory

clang-3: error: linker command failed with exit code 1 (use -v to see invocation)

Manually invoking it works (s:-mllvm:-mllvm -vectorize):
clang -shared  -fPIC -DPIC  .libs/entry.o .libs/mapi.o .libs/stub.o .libs/table.o .libs/u_current.o .libs/u_execmem.o   -lpthread  -O0 -O2 -mllvm -vectorize  -Wl,-soname -Wl,libOpenVG.so.1 -o .libs/libOpenVG.so.1.0.0

clang-3: warning: argument unused during compilation: '-mllvm -vectorize'

**Comment by Endilll** [comment]
On top of the comment above, we dropped support of autotools long ago.
