### ISSUE TITLE
Fresh new organization for GettingStarted.rst

### ISSUE THREAD

**Issue by silvasean** [llvm/llvm-project#15083]
|  |  |
| --- | --- |
| Bugzilla Link | [14711](https://llvm.org/bz14711) |
| Version | trunk |
| OS | Linux |
| CC | @gribozavr,@jryans,@silvasean |

## Extended Description 
docs/GettingStarted.rst needs a fresh new organization. Basically, it needs to start off by presenting the user with simple choices:

- Choice of getting the code: svn, git, or a release tarball
- Choice of build system: make, cmake (cmake can have some bullets, e.g. Xcode, Visual Studio, ninja, make, etc.)

Each of these parts should cover just the basic setup without diving into customizing the build---just enough for someone to get a reasonable llvm/clang running so they can play around with it (maybe touch on Release, Release+Asserts, Debug+Asserts at this stage since that's the "highest level" configuration and gives them a taste of how the build system is customized).

A more in-depth treatment of each build system's idiosyncrasies can be relegated to a "details" section farther down GettingStarted.rst (or, if necessary, its own page).

However, common aspects of both build systems, such as "how to add extra compiler flags" or "how to build only certain targets", should be their own sections and treat both build systems within that section; this keeps the discussion focused and eliminates certain redundancy, such as the general background for the task (e.g. "LLVM supports multiple targets, but you can selectively build only some").

**Comment by philnik777** [comment]
I'm pretty sure this is done. We have a relatively simple setup process now as the first step in `GettingStarted.rst`.
