### ISSUE TITLE
Build errors in Mesa's clover code

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15090]
|  |  |
| --- | --- |
| Bugzilla Link | [14718](https://llvm.org/bz14718) |
| Version | trunk |
| OS | Linux |
| Attachments | [failures dir from static analyzer](https://user-images.githubusercontent.com/60944935/143746606-472a506f-38c6-46c3-8516-9e6d6cdee3ee.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @tstellar |

## Extended Description 

See attached file.

**Comment by arsenm** [comment]
Build failure too old to be useful, I'm pretty sure clang can fully build mesa now
