### ISSUE TITLE
Ubuntu does not detect Clang

### ISSUE THREAD

**Issue by Keryen** [llvm/llvm-project#151]
Hello,

I have updated this project as I saw the new version (i had version 10). I pulled the changes make since I installed this project and now my pc does not detect Clang. I have done the following steps:

- `git pull origin master`
- `cmake -DLLVM_ENABLE_PROJECTS="clang" -G Ninja ../llvm`

When i use the command `clang`, it gives me the error that the command is not found. I have the bin of this project in the PATH, in .profile and also in .bashrc:

> echo $PATH
> /home/enrique/Escritorio/spirv-tools/build/tools:/home/enrique/Escritorio/llvm-project/build/bin:/home/enrique/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/enrique/Escritorio/llvm-project/build/bin:/home/enrique/Escritorio/spirv-tools/build/tools

Any suggestions to solve this problem?

**Comment by delcypher** [comment]
> * `git pull origin master`
> * `cmake -DLLVM_ENABLE_PROJECTS="clang" -G Ninja ../llvm`

You're missing the invocation to `ninja` to build the project. Running `cmake` like you do above just "configures" the project. It doesn't compile LLVM itself.

**Comment by RKSimon** [comment]
Resolving old query - the likely issue was identified and there was no further response
