### ISSUE TITLE
"LLC Compile" reports incorrectly

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#1512]
|  |  |
| --- | --- |
| Bugzilla Link | [1140](https://llvm.org/bz1140) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
If the run of the llc generated program (Output/*.llc) fails then the nightly
tester reports the "LLC Compile" time as "*". This is incorrect. If the compile
finished correctly, it should report the compile time, not "*", even if the
resulting compiled program failed.

**Comment by gwelymernans** [comment]
New build farm, etc. If seen again please file a new bug.
