### ISSUE TITLE
cflags not honored on solaris

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15136]
|  |  |
| --- | --- |
| Bugzilla Link | [14764](https://llvm.org/bz14764) |
| Version | 3.2 |
| OS | Solaris |
| Reporter | LLVM Bugzilla Contributor |
| CC | @Theodor |

## Extended Description 
Hello,

compiling llvm on omnios works fine, until I want to build it for 64bit. Then all settings in the configure script get ignored.

steps to reproduce:
* CFLAGS="-m64" CXXFLAGS="-m64" ./configure
* gmake VERBOSE=1

The resulting object files are all 32bit, instead of 64bit.

But with the following, it works
* CFLAGS="-m64" CXXFLAGS="-m64" ./configure
* CFLAGS="-m64" CXXFLAGS="-m64" gmake VERBOSE=1

All generated object files are now 64bit.

What is the cause of that and how can I solve that?

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
