### ISSUE TITLE
ICE when compiling with clang 3.2

### ISSUE THREAD

**Issue by 86f45abe-dd8b-4984-b80f-817c9f3b7044** [llvm/llvm-project#15153]
|  |  |
| --- | --- |
| Bugzilla Link | [14781](https://llvm.org/bz14781) |
| Version | 3.2 |
| OS | MacOS X |
| CC | @jryans |

## Extended Description 
I got the following:

UNREACHABLE executed at /build/eulisse/ext/CMSSW_6_2_X/20121230_2125/a/BUILD/slc5_amd64_gcc472/external/llvm/3.2-cms2/llvm-3.2-171261/tools/clang/lib/AST/TypeLoc.cpp:325!
0  clang           0x0000000001fb824f
1  clang           0x0000000001fb8749
2  libpthread.so.0 0x0000003b8540ebe0
3  libc.so.6       0x0000003b84c30285 gsignal + 53
4  libc.so.6       0x0000003b84c31d30 abort + 272
5  clang           0x0000000001fa3bec
6  clang           0x0000000001216588 clang::TemplateSpecializationTypeLoc::initializeArgLocs(clang::ASTContext&, unsigned int, clang::TemplateArgument const*, clang::TemplateArgumentLocInfo*, clang::SourceLocation) + 184
7  clang           0x0000000001216c1f clang::TypeLoc::initializeImpl(clang::ASTContext&, clang::TypeLoc, clang::SourceLocation) + 767
8  clang           0x00000000010c9fa5 clang::ASTContext::getTrivialTypeSourceInfo(clang::QualType, clang::SourceLocation) const + 53
9  clang           0x00000000012166a0 clang::TemplateSpecializationTypeLoc::initializeArgLocs(clang::ASTContext&, unsigned int, clang::TemplateArgument const*, clang::TemplateArgumentLocInfo*, clang::SourceLocation) + 464
10 clang           0x0000000001216c1f clang::TypeLoc::initializeImpl(clang::ASTContext&, clang::TypeLoc, clang::SourceLocation) + 767
11 clang           0x00000000010c9fa5 clang::ASTContext::getTrivialTypeSourceInfo(clang::QualType, clang::SourceLocation) const + 53
12 clang           0x0000000000c1a94e
13 clang           0x0000000000c1b8df
14 clang           0x0000000000c1e062 clang::Sema::getMoreSpecializedPartialSpecialization(clang::ClassTemplatePartialSpecializationDecl*, clang::ClassTemplatePartialSpecializationDecl*, clang::SourceLocation) + 1378
15 clang           0x0000000000c4fc58 clang::Sema::InstantiateClassTemplateSpecialization(clang::SourceLocation, clang::ClassTemplateSpecializationDecl*, clang::TemplateSpecializationKind, bool) + 1080
16 clang           0x0000000000c96f3b clang::Sema::RequireCompleteType(clang::SourceLocation, clang::QualType, clang::Sema::TypeDiagnoser&) + 779
17 clang           0x00000000009d0190 clang::Sema::RequireCompleteDeclContext(clang::CXXScopeSpec&, clang::DeclContext*) + 272
18 clang           0x0000000000afcbad clang::Sema::BuildQualifiedDeclarationNameExpr(clang::CXXScopeSpec&, clang::DeclarationNameInfo const&, bool) + 77
19 clang           0x0000000000c422b1
20 clang           0x0000000000c592a1
21 clang           0x0000000000c4a94c
22 clang           0x0000000000c5ea3d
23 clang           0x0000000000c4a525
24 clang           0x0000000000c6636c
25 clang           0x0000000000c671cf
26 clang           0x0000000000c65a1c
27 clang           0x0000000000c67fdf clang::Sema::SubstStmt(clang::Stmt*, clang::MultiLevelTemplateArgumentList const&) + 79
28 clang           0x0000000000c7c475 clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool) + 2261
29 clang           0x0000000000c7afb4 clang::Sema::PerformPendingInstantiations(bool) + 372
30 clang           0x0000000000c7c19d clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool) + 1533
31 clang           0x0000000000c7afb4 clang::Sema::PerformPendingInstantiations(bool) + 372
32 clang           0x0000000000c7c19d clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool) + 1533
33 clang           0x0000000000c7afb4 clang::Sema::PerformPendingInstantiations(bool) + 372
34 clang           0x0000000000c7c19d clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool) + 1533
35 clang           0x0000000000c7afb4 clang::Sema::PerformPendingInstantiations(bool) + 372
36 clang           0x0000000000c7c19d clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool) + 1533
37 clang           0x0000000000c7afb4 clang::Sema::PerformPendingInstantiations(bool) + 372
38 clang           0x0000000000c7c19d clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool) + 1533
39 clang           0x0000000000c7afb4 clang::Sema::PerformPendingInstantiations(bool) + 372
40 clang           0x0000000000c7c19d clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool) + 1533
41 clang           0x0000000000c7afb4 clang::Sema::PerformPendingInstantiations(bool) + 372
42 clang           0x00000000009bd9fb clang::Sema::ActOnEndOfTranslationUnit() + 315
43 clang           0x000000000093a5c2 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) + 306
44 clang           0x00000000009358ae clang::ParseAST(clang::Sema&, bool, bool) + 270
45 clang           0x00000000007df3de clang::CodeGenAction::ExecuteAction() + 78
46 clang           0x0000000000673866 clang::FrontendAction::Execute() + 150
47 clang           0x0000000000656595 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 341
48 clang           0x000000000063db2d clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 1421
49 clang           0x0000000000635a38 cc1_main(char const**, char const**, char const*, void*) + 1176
50 clang           0x000000000063cf22 main + 4834
51 libc.so.6       0x0000003b84c1d994 __libc_start_main + 244
52 clang           0x0000000000634949

See attached preprocessed source.

**Comment by Endilll** [comment]
Can't reproduce: there are no attachments, and links are dead.
