### ISSUE TITLE
Need a portable implementation of llvm::sys::locale::columnWidth

### ISSUE THREAD

**Issue by gribozavr** [llvm/llvm-project#15282]
|  |  |
| --- | --- |
| Bugzilla Link | [14910](https://llvm.org/bz14910) |
| Version | trunk |
| OS | Linux |
| CC | @belkadan,@jryans |

## Extended Description 
Currently there is a proper implementation of columnWidth for Mac OS X, but only a stub implementation for other OSes.

The Mac OS X implementation (lib/Support/LocaleXlocale.inc) is currently not portable because it uses *_l functions (e.g., mbstowcs_l) that are like their standard counterparts (mbstowcs_l), but take a locale as an explicit parameter.  This implementation can be made portable by using standard functions and assuming that we have a UTF-8 locale.

Is this viable?

**Comment by cor3ntin** [comment]
`columnWidthUTF8` works portably, this issue no longer seems relevant
