### ISSUE TITLE
Clang build php 5.4.10 failed

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15289]
|  |  |
| --- | --- |
| Bugzilla Link | [14917](https://llvm.org/bz14917) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic |

## Extended Description 
clang: error: unable to execute command: Aborted (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.3 (http://llvm.org/git/clang.git 0214b992655df72b29bcc6ded9d48748224d3496) (http://llvm.org/git/llvm.git a7aec400a7014edba1eeb53c582d3ab47178fe8d)
Target: i386-pc-linux-gnu
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/sqlite3-bPA3na.c
clang: note: diagnostic msg: /tmp/sqlite3-bPA3na.sh
clang: note: diagnostic msg:

********************
make: *** [ext/sqlite3/libsqlite/sqlite3.lo] Error 1

**Comment by arsenm** [comment]
Old build issue and comment says can't reproduce
