### ISSUE TITLE
Segfault while printing diagnosics

### ISSUE THREAD

**Issue by Bigcheese** [llvm/llvm-project#15302]
|  |  |
| --- | --- |
| Bugzilla Link | [14930](https://llvm.org/bz14930) |
| Version | trunk |
| OS | Linux |
| Attachments | [Preprocessed source](https://user-images.githubusercontent.com/301627/143746715-c14acbd9-7854-470b-951c-57aea3f787d9.gz), [Reduced to a single instantiation.](https://user-images.githubusercontent.com/301627/143746716-f9736774-346f-46e1-a318-ece25f5fa60d.gz) |
| CC | @zygoloid |

## Extended Description 
Had the following crash while clang was printing diagnostics.

FAILED: /usr/local/bin/clang++   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DGTEST_HAS_RTTI=0 -fcolor-diagnostics -Wall -Werror -std=c++11 -stdlib=libc++ -Wcovered-switch-default -O3 -DNDEBUG -Iunittests/ADT -I/mnt/host/llvm-project/llvm/unittests/ADT -Iinclude -I/mnt/host/llvm-project/llvm/include -I/mnt/host/llvm-project/llvm/utils/unittest/googletest/include    -Wall -W -Wno-unused-parameter -Wwrite-strings -pedantic -Wno-long-long -fno-exceptions  -fno-rtti -Wno-variadic-macros -MMD -MT unittests/ADT/CMakeFiles/ADTTests.dir/RangeTest.cpp.o -MF "unittests/ADT/CMakeFiles/ADTTests.dir/RangeTest.cpp.o.d" -o unittests/ADT/CMakeFiles/ADTTests.dir/RangeTest.cpp.o -c /mnt/host/llvm-project/llvm/unittests/ADT/RangeTest.cpp
In file included from /mnt/host/llvm-project/llvm/unittests/ADT/RangeTest.cpp:17:
/mnt/host/llvm-project/llvm/include/llvm/ADT/range.h:65:19: error: no template named 'is_same'; did you mean 'std::is_same'?
struct is_range : is_same<typename detail::begin_result<R>::type,
                  ^~~~~~~
                  std::is_same
/usr/include/c++/v1/type_traits:327:56: note: 'std::is_same' declared here
template <class _Tp, class _Up> struct _LIBCPP_VISIBLE is_same           : public false_type {};
                                                       ^
In file included from /mnt/host/llvm-project/llvm/unittests/ADT/RangeTest.cpp:17:
/mnt/host/llvm-project/llvm/include/llvm/ADT/range.h:88:5: error: unknown class name 'true_type'; did you mean 'std::true_type'?
  : true_type {};
    ^~~~~~~~~
    std::true_type
/usr/include/c++/v1/type_traits:175:40: note: 'std::true_type' declared here
typedef integral_constant<bool, true>  true_type;
                                       ^
In file included from /mnt/host/llvm-project/llvm/unittests/ADT/RangeTest.cpp:17:
/mnt/host/llvm-project/llvm/include/llvm/ADT/range.h:251:16: error: no template named 'is_pointer'; did you mean 'detail::is_pointer'?
              !is_pointer<decltype(detail::adl_begin(r))>::value)
               ^~~~~~~~~~
               detail::is_pointer
/usr/include/c++/v1/type_traits:267:45: note: 'detail::is_pointer' declared here
template <class _Tp> struct _LIBCPP_VISIBLE is_pointer
                                            ^
/mnt/host/llvm-project/llvm/unittests/ADT/RangeTest.cpp:39:24: error: no namespace named 'detail' in namespace 'std'; did you mean 'llvm::detail'?
  using namespace std::detail;
                  ~~~~~^~~~~~
                  llvm::detail
/mnt/host/llvm-project/llvm/include/llvm/ADT/range.h:41:11: note: namespace 'llvm::detail' defined here
namespace detail {
          ^
Stack dump:
0.      Program arguments: /usr/local/bin/clang-3.2 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -main-file-name RangeTest.cpp -mrelocation-model static -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -momit-leaf-frame-pointer -coverage-file /home/mspencer/llvm-project/build/llvm+lld/release/unittests/ADT/CMakeFiles/ADTTests.dir/RangeTest.cpp.o -resource-dir /usr/local/bin/../lib/clang/3.3 -dependency-file unittests/ADT/CMakeFiles/ADTTests.dir/RangeTest.cpp.o.d -MT unittests/ADT/CMakeFiles/ADTTests.dir/RangeTest.cpp.o -D _GNU_SOURCE -D __STDC_CONSTANT_MACROS -D __STDC_FORMAT_MACROS -D __STDC_LIMIT_MACROS -D GTEST_HAS_RTTI=0 -D NDEBUG -I unittests/ADT -I /mnt/host/llvm-project/llvm/unittests/ADT -I include -I /mnt/host/llvm-project/llvm/include -I /mnt/host/llvm-project/llvm/utils/unittest/googletest/include -fmodule-cache-path /var/tmp/clang-module-cache -internal-isystem /usr/include/c++/v1 -internal-isystem /usr/
local/include -internal-isystem /usr/local/bin/../lib/clang/3.3/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -Wall -Werror -Wcovered-switch-default -Wall -W -Wno-unused-parameter -Wwrite-strings -Wno-long-long -Wno-variadic-macros -pedantic -std=c++11 -fconst-strings -fdeprecated-macro -fdebug-compilation-dir /home/mspencer/llvm-project/build/llvm+lld/release -ferror-limit 19 -fmessage-length 0 -mstackrealign -fno-rtti -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -o unittests/ADT/CMakeFiles/ADTTests.dir/RangeTest.cpp.o -x c++ /mnt/host/llvm-project/llvm/unittests/ADT/RangeTest.cpp
1.      /mnt/host/llvm-project/llvm/unittests/ADT/RangeTest.cpp:41:3 <Spelling=/mnt/host/llvm-project/llvm/unittests/ADT/RangeTest.cpp:41:78>: current parser token 'type'
2.      /mnt/host/llvm-project/llvm/unittests/ADT/RangeTest.cpp:38:20: parsing function body 'test_traits'
3.      /mnt/host/llvm-project/llvm/unittests/ADT/RangeTest.cpp:38:20: in compound statement ('{}')
clang-3: error: unable to execute command: Segmentation fault (core dumped)
clang-3: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.3
Target: x86_64-unknown-linux-gnu
Thread model: posix
clang-3: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3: note: diagnostic msg: /tmp/RangeTest-NCDWRQ.cpp
clang-3: note: diagnostic msg: /tmp/RangeTest-NCDWRQ.sh
clang-3: note: diagnostic msg:

********************

**Comment by AaronBallman** [comment]
I can no longer reproduce this issue, but if you're still seeing a crash, please reopen with more details on how to reproduce.

**Comment by Endilll** [comment]
I can't reproduce it either on Clang 3.2 and 3.3: https://cexplorer.testlabs.pro/z/avhb7E
