### ISSUE TITLE
BugPoint tests fail with "Program could not be executed"

### ISSUE THREAD

**Issue by andrewjcg** [llvm/llvm-project#15342]
|  |  |
| --- | --- |
| Bugzilla Link | [14970](https://llvm.org/bz14970) |
| Version | 3.2 |
| OS | Linux |
| Attachments | [Patch removing memory rlimits from BugPoint tests](https://user-images.githubusercontent.com/92601611/143746733-a66197c9-944c-4317-80c8-dd948bc3b7ff.gz) |
| CC | @yuanfang-chen |

## Extended Description 

BugPoint tests fail, printing "Program could not be executed".  An strace shows that the failure originates when the dynamic linker tries to load libLLVMARMInfo.so, and it dies with a memory related error: "failed to map segment from shared object: Cannot allocate memory."

This appears to be caused by the deafult rlimits set in "lib/Support/Unix/Program.inc".  Passing '-mlimit=0' into the tests allows them to pass (see attached).

**Comment by arsenm** [comment]
Old build issue
