### ISSUE TITLE
CPP back end generates bad code

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15386]
|  |  |
| --- | --- |
| Bugzilla Link | [15014](https://llvm.org/bz15014) |
| Version | 3.2 |
| OS | MacOS X |
| Attachments | [source file to reproduce bug](https://user-images.githubusercontent.com/60944935/143746753-152cd0eb-28f2-442f-bf12-ed918ec2c8b8.gz), [Example output from source file that fails.](https://user-images.githubusercontent.com/60944935/143746754-9c14b30d-0d82-4f74-928c-ec9bf3566125.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @silvasean |

## Extended Description 

For the enclosed file test5.s, run the following (I've also included the test5.s.cpp it generated on my machine):

llc -march=cpp test5.s && clang++ `llvm-config --cppflags --ldflags --libs core` test5.s.cpp

Note the errors:

test5.s.cpp:49:20: error: redefinition of 'FuncTy_0_args'
 std::vector<Type*>FuncTy_0_args;
                   ^
test5.s.cpp:42:20: note: previous definition is here
 std::vector<Type*>FuncTy_0_args;
                   ^
test5.s.cpp:71:16: error: redefinition of 'FuncTy_0'
 FunctionType* FuncTy_0 = FunctionType::get(
               ^
test5.s.cpp:56:16: note: previous definition is here
 FunctionType* FuncTy_0 = FunctionType::get(

It also tries to use FuncTy_0_args without clearing first.

**Comment by arsenm** [comment]
cpp backend is gone
