### ISSUE TITLE
LLVM LIT test fails on Win8 (ExecutionEngine/MCJIT/2003-05-06-LivenessClobber.ll)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15428]
|  |  |
| --- | --- |
| Bugzilla Link | [15056](https://llvm.org/bz15056) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The following LLVM LIT test fails when running on Win8: 
ExecutionEngine/MCJIT/2003-05-06-LivenessClobber.ll 
This failures happens in the current llvm trunk (rev. 173279). 
This test failure might be related to transition to MCJIT (This test was previously ran with the regular execution enginen and passend on LLVM 3.0 release) or the DynamicLibrary which is responsible for loading modules. 

Test's command line: 
not.exe lli.exe -mtriple=x86_64-pc-win32-elf -use-mcjit c:\llvm\test\ExecutionEngine\MCJIT\2003-05-06-LivenessClobber.ll 

The lli.exe is expected to fail (return val != 0). 
It seems that lli.exe runs the function from the LIT tests, which returns 1, and then runs the "exit(int)" windows system call with the given value. 

on Win7 this system call terminates the process with return code "1", while on Win8 this system call terminates the process with return code "0". 

After investigation I saw that on Win7 the exit() system call was loaded from C:\Windows\System32\msvcr100d.dll, while  on Win8 it was loaded from C:\Windows\System32\KernelBase.dll and they were 2 completley different system calls and implemented differently.

**Comment by arsenm** [comment]
Old build issue
