### ISSUE TITLE
Can no longer compile LLVM with --with-oprofile

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15427]
|  |  |
| --- | --- |
| Bugzilla Link | [15055](https://llvm.org/bz15055) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
$ svn info | grep Revision
Revision: 173314
$ cd build
$ ../configure --prefix=/usr/local/stow/llvm-latest --enable-optimized --enable-debug-runtime --enable-debug-symbols --disable-assertions --enable-libffi --with-oprofile CC=gcc CXX=g++ REQUIRES_RTTI=1
$ make
[blah, blah, blah]
make[3]: Entering directory `/tmp/llvm/build/lib/ExecutionEngine/OProfileJIT'
llvm[3]: Compiling OProfileWrapper.cpp for Release+Debug build
/tmp/llvm/lib/ExecutionEngine/OProfileJIT/OProfileWrapper.cpp: In member function ‘bool llvm::OProfileWrapper::checkForOProfileProcEntry()’:
/tmp/llvm/lib/ExecutionEngine/OProfileJIT/OProfileWrapper.cpp:141:59: error: ‘read’ was not declared in this scope
/tmp/llvm/lib/ExecutionEngine/OProfileJIT/OProfileWrapper.cpp:142:24: error: ‘close’ was not declared in this scope
make[3]: *** [/tmp/llvm/build/lib/ExecutionEngine/OProfileJIT/Release+Debug/OProfileWrapper.o] Error 1
make[3]: Leaving directory `/tmp/llvm/build/lib/ExecutionEngine/OProfileJIT'
make[2]: *** [OProfileJIT/.makeall] Error 2
make[2]: Leaving directory `/tmp/llvm/build/lib/ExecutionEngine'
make[1]: *** [ExecutionEngine/.makeall] Error 2
make[1]: Leaving directory `/tmp/llvm/build/lib'
make: *** [all] Error 1

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
