### ISSUE TITLE
Poolalloc for LLVM 3.0 fails to compile with -Werror and -Wall flags [FIXED]

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15437]
|  |  |
| --- | --- |
| Bugzilla Link | [15065](https://llvm.org/bz15065) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Note: This error only exists in release_30 and has been fixed in release_32.

While following the steps from http://sva.cs.illinois.edu/docs/Install.html to compile poolalloc, I get an error to Printer.cpp.

The error probably occurs because I was using a version of gcc or clang that was more stringent about warnings/errors.

It works fine when the compiler flags -Werror -Wall are removed before configuring poolalloc.

The error trace looks like this:

llvm[2]: Compiling Printer.cpp for Debug build (PIC)
In file included from Printer.cpp:23:0:
/home/Workspace/llvm/include/llvm/Support/GraphWriter.h: In instantiation of ‘void llvm::GraphWriter<GraphType>::writeNode(llvm::GraphWriter<GraphType>::NodeType*) [with GraphType = const llvm::DSGraph*; llvm::GraphWriter<GraphType>::NodeType = const llvm::DSNode]’:
Printer.cpp:295:19:   required from here
/home/Workspace/llvm/include/llvm/Support/GraphWriter.h:175:9: error: cast from type ‘llvm::GraphWriter<const llvm::DSGraph*>::NodeType* {aka const llvm::DSNode*}’ to type ‘void*’ casts away qualifiers [-Werror=cast-qual]
/home/Workspace/llvm/include/llvm/Support/GraphWriter.h:195:9: error: cast from type ‘llvm::GraphWriter<const llvm::DSGraph*>::NodeType* {aka const llvm::DSNode*}’ to type ‘void*’ casts away qualifiers [-Werror=cast-qual]
cc1plus: all warnings being treated as errors
/bin/rm: cannot remove `/home/Workspace/llvm/projects/poolalloc/lib/DSA/Debug/Printer.d.tmp': No such file or directory
make[2]: *** [/home/Workspace/llvm/projects/poolalloc/lib/DSA/Debug/Printer.o] Error 1
make[2]: Leaving directory `/home/Workspace/llvm/projects/poolalloc/lib/DSA'
make[1]: *** [all] Error 1
make[1]: Leaving directory `/home/Workspace/llvm/projects/poolalloc/lib'
make: *** [all] Error 1

**Comment by arsenm** [comment]
Old build issue and title says fixed
