### ISSUE TITLE
Clang incorrectly reports error parsing lambda and then segfaults

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15431]
|  |  |
| --- | --- |
| Bugzilla Link | [15059](https://llvm.org/bz15059) |
| Version | 3.0 |
| OS | Linux |
| Attachments | [Build output and preprocessed source file](https://user-images.githubusercontent.com/60944935/143746776-2eb96487-87fe-46a8-95f8-f6fb52e50038.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Not sure if this might be the same as #&#8203;12840...I've attached my build output and the preprocessed source file. Clang 3.0-6, Linux Mint 64-bit.

**Comment by cor3ntin** [comment]
decade old bug with no reduction and weird attachment, closing as stale

**Comment by Endilll** [comment]
Somehow it has the same attachment as #58667
It appears to be fixed in Clang 3.1: https://godbolt.org/z/6E13TK69j
Reduced by C-Reduce:
```cpp
struct Set {}

Set::Set() {
  0,[
}

)
```
