### ISSUE TITLE
assertion needed

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15468]
|  |  |
| --- | --- |
| Bugzilla Link | [15096](https://llvm.org/bz15096) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
MBB->end()->getParent() will just return garbage instead of asserting

this can happen also when you are at the end.

MI->getParent()

**Comment by JOE1994** [comment]
Seems unactionable,
given no pointers to code where such invalid accesses occur.
