### ISSUE TITLE
FileCheck should properly report errors rather than just using assert()

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15485]
|  |  |
| --- | --- |
| Bugzilla Link | [15113](https://llvm.org/bz15113) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
For example, in attern::FindRegexVarEnd() we have:
        case ']':                                                                
          assert(BracketDepth > 0 && "Invalid regex");                           
          BracketDepth--;                                                        
          break;

That's from expressions like [[[NAME]], r0]. The parser gets confused by the [[[ and goes south. The error should be a real diagnostic, not an assertion failure.

**Comment by EugeneZelenko** [comment]
@arsenm: Could you please elaborate?

**Comment by arsenm** [comment]
The mentioned function has a PrintMessage + exit
