### ISSUE TITLE
Poolallocation of higher-order function has assertion error

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15493]
|  |  |
| --- | --- |
| Bugzilla Link | [15121](https://llvm.org/bz15121) |
| Version | trunk |
| OS | MacOS X |
| Attachments | [example program](https://user-images.githubusercontent.com/60944935/143746815-e84d54bb-2cef-4136-a709-f03a58537e46.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Consider the attached program. It contains part of an implementation of a dynamic array in C. It has a map function, which uses C's function pointer mechanism to simulate a higher-order function. When the map function is removed, the program successfully compiles. When compiling with the map function, the below assertion error is raised.

bash-3.2$ clang -flto -fmemsafety -o dynarray.o dynarray.c
Pool allocating 18 global nodes!
[DynArray_new] 3 nodes pool allocatable
[DynArray_add] 3 nodes pool allocatable
[DynArray_map] 3 nodes pool allocatable
[main] 3 nodes pool allocatable
Assertion failed: (!N->isGlobalNode() && "Should be in global mapping!"), function getLocalPoolNodes, file AllNodesHeuristic.cpp, line 220.
Stack dump:
0.	Running pass 'Pool allocate disjoint data structures' on module 'ld-temp.o'.
clang: error: unable to execute command: Illegal instruction
clang: error: linker command failed due to signal (use -v to see invocation)

**Comment by Endilll** [comment]
Can't reproduce: https://cexplorer.testlabs.pro/z/cfWzEs
