### ISSUE TITLE
clang-x86_64-linux-fnt LNT failures: scimark2 and ms_struct_pack_layout

### ISSUE THREAD

**Issue by atrick** [llvm/llvm-project#15555]
|  |  |
| --- | --- |
| Bugzilla Link | [15183](https://llvm.org/bz15183) |
| Version | trunk |
| OS | All |
| CC | @atrick,@d0k |

## Extended Description 
These linux LNT tests began failing on Jan 22:
http://lab.llvm.org:8011/builders/clang-x86_64-linux-fnt/builds/645

I have not been able to reproduce either failures on darwin. The linux tests link with gcc.

I'll copy a couple folks who checked in at this time.

**Comment by arsenm** [comment]
Old build failure
