### ISSUE TITLE
clang-x86_64-debian LNT failures: scimark2, linpack-pc

### ISSUE THREAD

**Issue by atrick** [llvm/llvm-project#15552]
|  |  |
| --- | --- |
| Bugzilla Link | [15180](https://llvm.org/bz15180) |
| Version | trunk |
| OS | All |
| CC | @atrick |

## Extended Description 
These two tests have been failing on the debian builder for the past week or so. There don't appear to be any logs before that point.

It looks like the admin is Duncan.

**Comment by arsenm** [comment]
Old build issue
