### ISSUE TITLE
make -f Makefile.sphinx latexpdf produces errors in generating hyper references

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15570]
|  |  |
| --- | --- |
| Bugzilla Link | [15198](https://llvm.org/bz15198) |
| Version | trunk |
| OS | All |
| Blocks | llvm/llvm-bugzilla-archive#15202  |
| Reporter | LLVM Bugzilla Contributor |
| CC | @gribozavr,@silvasean |

## Extended Description 
Even when run 3 times, cross reference errors are still produced.  For example:

LaTeX Warning: Hyper reference `tutorial/OCamlLangImpl6:example' on page 427 un
defined on input line 34558.

**Comment by arsenm** [comment]
Don't think these use latex anymore
