### ISSUE TITLE
lldb on Linux/FreeBSD does not display the correct size of static arrays

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15633]
|  |  |
| --- | --- |
| Bugzilla Link | [15261](https://llvm.org/bz15261) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @emaste |

## Extended Description 
The test case TestStaticVariables fails because lldb prints empty square-brackets instead of the size of static arrays. The test verifies both class-static and file-static arrays, and both fail.

To reproduce, run:

python dotest.py lang/cpp/class_static

The relevant failure trace is:

runCmd: target variable A::g_points
output: (PointType []) A::g_points = {}

Expecting sub string: (PointType [2]) A::g_points
Not matched

**Comment by DavidSpickett** [comment]
Test passes today on Linux with clang, gcc is disabled for a known issue. Closing.
