### ISSUE TITLE
LiveInterval::killedAt() is broken for early-clobber kills and should be replaced by LiveRangeQuery

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15689]
|  |  |
| --- | --- |
| Bugzilla Link | [15317](https://llvm.org/bz15317) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @stoklund |

## Extended Description 
LiveInterval::killedAt() has this implementation:

    bool killedAt(SlotIndex index) const {
      const_iterator r = find(index.getRegSlot(true));
      return r != end() && r->end == index;
    }

This will always return false for an early-clobber kill. We should replace its (thankfully few) uses with LiveRangeQuery.

**Comment by arsenm** [comment]
killedAt was removed
