### ISSUE TITLE
indexing an integral type with a pointer type

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15793]
|  |  |
| --- | --- |
| Bugzilla Link | [15421](https://llvm.org/bz15421) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie |

## Extended Description 
C allows "indexing an integral type with a pointer type":

int a;
char *p;
a[p];

This is an obscure feature, and is possibly the result of C trying to mimic some assembly syntax.

The proposal is to give a warning and 2 notes:
- warning: indexing an integral type with a pointer is an obscure feature
- note: use ``p[a]'' to silence this warning
- note: use ``*(p + a)'' to allow p and a to be flippable macro parameters, while silencing this warning.

**Comment by AaronBallman** [comment]
Closing; I don't think this finds a sufficient number of real bugs to warrant adding it as a warning to Clang. It could be a reasonable style warning for clang-tidy, but I'm not certain it's worth the effort (it's more of a curio than anything).
