### ISSUE TITLE
type overloading does not strip function attributes

### ISSUE THREAD

**Issue by compnerd** [llvm/llvm-project#15795]
|  |  |
| --- | --- |
| Bugzilla Link | [15423](https://llvm.org/bz15423) |
| Version | trunk |
| OS | Linux |
| Attachments | [instantiation.cc](https://user-images.githubusercontent.com/63311/143747004-fe671a54-f454-4fa3-945b-65c4de3dbff6.gz) |
| CC | @DougGregor,@gribozavr,@zygoloid,@ftynse |

## Extended Description 

When performing template type instantations, function attributes need to be stripped to allow for proper template instantation.  The following example helps indicate this.

In particular, the make_thunk template specialisation fails as there are two template specialisations available (one for the const and one for the non-const version).  The __attribute__ (( noreturn )) is considered part of the templated type, which does not have a template specialisation, and so the template instantiation fails.

**Comment by shafik** [comment]
Resolution to https://github.com/llvm/llvm-project/issues/15477 seems to say this is intended behavior and we do not intend to change this.

CC @zygoloid in case this position has changed
