### ISSUE TITLE
redundant warning when trying to apply operator== on values of uncomparable types

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15792]
|  |  |
| --- | --- |
| Bugzilla Link | [15420](https://llvm.org/bz15420) |
| Version | trunk |
| OS | FreeBSD |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie,@DougGregor |

## Extended Description 
1. Source code:

struct A { };

int main()
{
    A a;
    return a == a;
}

2. Actual output (slimmed):

warning: self-comparison always evaluates to true
error: invalid operands to binary expression ('A' and 'A')

3. Expected output:

error: invalid operands to binary expression ('A' and 'A')

(ie., no warning)

**Comment by AaronBallman** [comment]
This behavior was changed in Clang 10 and the warning is no longer issued.
