### ISSUE TITLE
Error in backend: Cannot select 0x2696770: i64 = fabs 0x269aa70

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#15800]
|  |  |
| --- | --- |
| Bugzilla Link | [15428](https://llvm.org/bz15428) |
| Version | 3.2 |
| OS | Linux |
| CC | @d0k |

## Extended Description 
Under a Debian with experimental packages, with the code at the end of the bug report, the command:
$ clang++   -O2 -c -o ladmin.o ladmin.cpp
is failing with:

fatal error: error in backend: Cannot select: 0x2696770: i64 = fabs 0x269aa70
      [ORD=16] [ID=32]
  0x269aa70: i64 = zero_extend 0x269a470 [ID=31]
    0x269a470: i8 = X86ISD::SETCC 0x269a870, 0x2696870:1 [ID=29]
      0x269a870: i8 = Constant<9> [ID=13]
      0x2696870: i64,i32 = X86ISD::SUB 0x2693e30, 0x2696670 [ID=27]
        0x2693e30: i64 = add 0x2693130, 0x2695d70 [ORD=12] [ID=25]
          0x2693130: i64,ch = load 0x2693b30, 0x2696470, 0x2693930<LD8[%33](tbaa=!"any pointer")> [ORD=11] [ID=24]
            0x2696470: i64 = FrameIndex<5> [ORD=8] [ID=3]
            0x2693930: i64 = undef [ORD=10] [ID=5]
          0x2695d70: i64 = Constant<-24> [ORD=12] [ID=8]
        0x2696670: i64 = X86ISD::Wrapper 0x2695c70 [ID=18]
          0x2695c70: i64 = TargetGlobalAddress<[0 x i64]* @&#8203;_ZNSs4_Rep20_S_empty_rep_storageE> 0 [ID=16]
In function: _Z9term_funcv

---------
/// BEGIN ladmin.cpp
#include <string>

struct const_string
{
    const_string(const std::string& s);
};

void ladmin_log(const_string);

void term_func(void)
{
    ladmin_log(
        static_cast<const std::string&>(
            (
                std::string()
            )
        )
    );
}
/// END ladmin.cpp
--------

Please note that it might be related that I am using:
libstdc++6 - 4.8-20130102-1
libc6 - 2.16-0experimental1

Originally reported here: 
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=701138

**Comment by arsenm** [comment]
Works for me today
