### ISSUE TITLE
UNREACHABLE executed at ScheduleDAGInstrs.cpp:521!

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15831]
|  |  |
| --- | --- |
| Bugzilla Link | [15459](https://llvm.org/bz15459) |
| Version | trunk |
| OS | Linux |
| Attachments | [test case](https://user-images.githubusercontent.com/60944935/143747024-621cfc77-4702-43f2-a1fc-861a236685ae.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

/usr/local/bin/clang -cc1 -triple x86_64-unknown-freebsd9.1 -emit-obj -disable-free -main-file-name perlmini.c -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -relaxed-aliasing -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu corei7 -target-linker-version 2.17.50 -momit-leaf-frame-pointer -D PERL_CORE -D 'APPLLIB_EXP="/usr/local/lib/perl5/5.16.2/BSDPAN"' -D HAS_FPSETMASK -D HAS_FLOATINGPOINT_H -D PIC -D PERL_IS_MINIPERL -D PERL_EXTERNAL_GLOB -O2 -Wall -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings -std=c89 -fconst-strings -ferror-limit 19 -fmessage-length 115 -stack-protector 1 -mstackrealign -fobjc-runtime=gnustep -fobjc-default-synthesize-properties -fdiagnostics-show-option -fcolor-diagnostics -backend-option -vectorize-loops -mllvm -enable-misched -mllvm -enable-aa-sched-mi -x c perlmini.c

UNREACHABLE executed at ScheduleDAGInstrs.cpp:521!
Stack dump:
0.      Program arguments: /usr/local/bin/clang -cc1 -triple x86_64-unknown-freebsd9.1 -emit-obj -disable-free -main-file-name perlmini.c -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -relaxed-aliasing -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu corei7 -target-linker-version 2.17.50 -momit-leaf-frame-pointer -D PERL_CORE -D APPLLIB_EXP="/usr/local/lib/perl5/5.16.2/BSDPAN" -D HAS_FPSETMASK -D HAS_FLOATINGPOINT_H -D PIC -D PERL_IS_MINIPERL -D PERL_EXTERNAL_GLOB -O2 -Wall -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings -std=c89 -fconst-strings -ferror-limit 19 -fmessage-length 115 -stack-protector 1 -mstackrealign -fobjc-runtime=gnustep -fobjc-default-synthesize-properties -fdiagnostics-show-option -fcolor-diagnostics -backend-option -vectorize-loops -mllvm -enable-misched -mllvm -enable-aa-sched-mi -x c perlmini.c 
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'perlmini.c'.
4.      Running pass 'Machine Instruction Scheduler' on function '@perl_construct'
Abort (core dumped)

**Comment by arsenm** [comment]
Had to massage the source slightly to compile but doesn't reproduce
