### ISSUE TITLE
clang/C: should issue a warning instead of an error when 'main' function have different signatures

### ISSUE THREAD

**Issue by tinti** [llvm/llvm-project#15880]
|  |  |
| --- | --- |
| Bugzilla Link | [15508](https://llvm.org/bz15508) |
| Version | trunk |
| OS | Linux |
| CC | @spavloff |

## Extended Description 
Since the C standard does not explicit says that this is not allowed it would be better if Clang simply issue a warning when building the following code:

#include <stdio.h>
#include <stdlib.h>

int main(int this, int that, int another) {
  return 0;
}

With GCC:

$ gcc -c main.c -o main.o
OK

With Clang:

$ clang -c main.c -o main.o
main.c:4:5: error: second parameter of 'main' (argument array) must be of type 'char **'
int main(int this, int that, int another) {
    ^
main.c:4:5: error: third parameter of 'main' (environment) must be of type 'char **'
2 errors generated.

**Comment by AaronBallman** [comment]
Closing as not a bug. We're correct to diagnose this unless `-ffreestanding` is passed, and `-ffreestanding` does suppress the diagnostic as expected. https://godbolt.org/z/sb933bEcM
