### ISSUE TITLE
Diagnose mismatched exception specifications

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#15906]
|  |  |
| --- | --- |
| Bugzilla Link | [15534](https://llvm.org/bz15534) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Per discussions in core, we should diagnose this:

template<typename T> void f() noexcept(sizeof(T) == 4);
template<typename T> void f() noexcept(sizeof(T) == 8);

More generally, for a redeclaration of a function template, the exception-specifications should match under the terms of the ODR.

**Comment by wheatman** [comment]
This was fixed between 6.0.1 and 7.0.0
https://godbolt.org/z/jo6E8TjWP

code
```
template<typename T> void f() noexcept(sizeof(T) == 4);
template<typename T> void f() noexcept(sizeof(T) == 8);
```

new diagnostic 
```
<source>:2:27: error: exception specification in declaration does not match previous declaration
template<typename T> void f() noexcept(sizeof(T) == 8);
                          ^
<source>:1:27: note: previous declaration is here
template<typename T> void f() noexcept(sizeof(T) == 4);
                          ^
1 error generated.
Compiler returned: 1
```
