### ISSUE TITLE
issues can be opened

### ISSUE THREAD

**Issue by jdoerfert** [llvm/llvm-project#160]
I was surprised but it seems we allow github issues now [0](https://github.com/llvm/llvm-project/issues/160)

One unfortunate consequence is that people do not get emails for the new issues as they get them for new bugs (there is some opt-in required or we need to forward emails to the appropriate lists). Is this on purpose? If so, could we announce that more prominently on the lists? If it is not on purpose we should disable Issues for now.

**Comment by DimitryAndric** [comment]
Read the extremely long thread here first: http://lists.llvm.org/pipermail/llvm-dev/2019-October/136162.html :)

**Comment by jdoerfert** [comment]
> Read the extremely long thread here first: http://lists.llvm.org/pipermail/llvm-dev/2019-October/136162.html :)

You basically just made my point.

**Comment by tstellar** [comment]
@jdoerfert He haven't officially enabled issues, so I'll se if I can find away to close new ones without closing the existing once.

**Comment by JonChesterfield** [comment]
There will be a non-empty set of issues which would be raised on github, but where the developer sees the overhead of emailing someone at bugzilla to open an account and decides they've got better things to do. I think we should keep github issues available on that basis.

**Comment by tstellar** [comment]
@JonChesterfield This is why we have discussed switching to GitHub issues long-term, but I do think it's confusing to have them enabled before we've officially switched.

**Comment by jyknight** [comment]
We should keep this open.

Many of the users reporting issues here I believe are not long-term members of our community, and would not open a bugzilla account. We should be welcoming them.

**Comment by jdoerfert** [comment]
> We should keep this open.
> 
> Many of the users reporting issues here I believe are not long-term members of our community, and would not open a bugzilla account. We should be welcoming them.

That was one of the main arguments of the discussion that was going on. I do not disagree.

However, welcoming should mean we don't only have a bug tracker open here but also people that monitor it. The people that usually monitor bugs and address them might also find it less welcoming if we have a discussion about moving to issues and just do it while no consensus was reached.

To repeat my initial problem: We need to announce this properly either way and we need to set up the infrastructure to make this work seamlessly for people, e.g., emails to the -bugs list.

@tstellar Can you send a new email on *-dev to announce "the plan"?

**Comment by andrewrk** [comment]
https://github.com/llvm/llvm-project/issues/163#issuecomment-593515274

**Comment by jdoerfert** [comment]
> We should keep this open.
> 
> Many of the users reporting issues here I believe are not long-term members of our community, and would not open a bugzilla account. We should be welcoming them.

To repeat myself because I don't think anything changed in the last 12 days:

_welcoming should mean we don't only have a bug tracker open here but also people that monitor it._

To me, it feels like GH issues are still ignored by a huge fraction of the community. It is great that we make it easy for people to report issues and ask questions but I doubt it helps them if they are largely ignored:  #73, #95, #97, #115, #122, #147 ... ([all](https://github.com/llvm/llvm-project/issues?page=1&q=is%3Aissue+is%3Aopen+comments%3A0))

In addition we now have four separate systems that all do similar things with no clear guidance on how to use them...

**Comment by joker-eph** [comment]
> It is great that we make it easy for people to report issues and ask questions but I doubt it helps them if they are largely ignored

That's my feeling as well. 
The issues were opened with the expectation of a migration: but GH issues are not there yet in terms of features as far as I can tell. Having two different bug-trackers is not a good situation to be in. 

We should close the issue until there is a real plan.

**Comment by sam-mccall** [comment]
Well, the migration has now happened. Seems safe to close this.
