### ISSUE TITLE
bugpoint help doesn't

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#1603]
|  |  |
| --- | --- |
| Bugzilla Link | [1231](https://llvm.org/bz1231) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@jryans |

## Extended Description 
The --help option for bugpoint produces
USAGE: bugpoint [options] --args <program arguments>... --tool-args <tool arguments>... <input 
llvm ll/bc files>
followed by a lengthy list of options, most of which, I think, don't apply to bugpoint.  This is completely 
wrong, and produces mysterious errors when you attempt to do things this way, for example:

bugpoint -run-llc --tool-args="-o lencod.llc.s -stats -march=thumb -debug-only=arm-cp-islands -
mcpu=arm1136jf-s -relocation-model=pic -f" lencod.llvm.bc 
bugpoint: Not enough positional command line arguments specified!

Not real helpful, the reverse in fact.  I looked briefly at fixing this but it appears command line 
processing is centralized for the various tools in a way that makes it nontrivial.

Also, the -o and -f options cannot be passed to llc, as bugpoint inserts these itself and llc will not 
tolerate duplication.

**Comment by arsenm** [comment]
Bugpoint's flags truly have always been incomprehensible, and won't get any better as a result of a 16 years old ticket. llvm-reduce has more comprehensible options and uses an option group to filter out unrelated flags in --help (though for some reason some extra stuff shows up in --help-hidden)
