### ISSUE TITLE
Empty macro arguments cause whitespace to go missing

### ISSUE THREAD

**Issue by hvdijk** [llvm/llvm-project#16047]
|  |  |
| --- | --- |
| Bugzilla Link | [15675](https://llvm.org/bz15675) |
| Version | 3.2 |
| OS | Linux |

## Extended Description 
```cpp
#define A()
#define B(x)x
#define C(x) x
#define STR(x) STR_(x)
#define STR_(x) #x
STR([ A()])
STR([ B()])
STR([ C()])
```

is preprocessed to

```cpp
"[ ]"
"[]"
"[]"
```

It should be `"[ ]"` for all three lines, which is what gcc and mcpp do.

**Comment by shafik** [comment]
This looks fixed in clang-3.5: https://godbolt.org/z/zeK1Ef7GG

and it looks like we have good testing now as well.
