### ISSUE TITLE
seg fault in clang frontend triggered by std::is_trivially_default_destructible<std::vector<int>>

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16106]
|  |  |
| --- | --- |
| Bugzilla Link | [15734](https://llvm.org/bz15734) |
| Version | 3.2 |
| OS | MacOS X |
| Attachments | [source (preprocessed source exceeds file-size limit)](https://user-images.githubusercontent.com/60944935/143747222-2b46ce8f-4996-4f14-b67c-db219b5d7a9a.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
clang++ -std=c++11 -stdlib=libc++ crashes upon processing std::is_trivially_default_constructible<std::vector<int>>.

source is trivial, preprocessed source attached (sorry, cannot attach run script as I can only attach one file here).
crash backtrace:

clang version 3.2 (tags/RELEASE_32/final)
Target: x86_64-apple-darwin12.3.0
Thread model: posix
 "/opt/local/share/clang-32/bin/clang" -cc1 -triple x86_64-apple-macosx10.8.0 -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name test1.cc -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 134.9 -v -resource-dir /opt/local/share/clang-32/bin/../lib/clang/3.2 -fmodule-cache-path /var/folders/n5/bcfvl8s53ds0g8slrlcwnk9m0000gq/T/clang-module-cache -I/Users/walter/code/tbb41_20121003oss//include -I/Users/walter/code/tbb41_20121003oss//include -stdlib=libc++ -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /Users/walter1/nemo/usr/dehnen/utils -ferror-limit 19 -fmessage-length 167 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.8.0 -fobjc-dispatch-method=mixed -fobjc-default-synthesize-properties -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/n5/bcfvl8s53ds0g8slrlcwnk9m0000gq/T/test1-mmEPFD.o -x c++ test1.cc
clang -cc1 version 3.2 based upon LLVM 3.2svn default target x86_64-apple-darwin12.3.0
ignoring nonexistent directory "/opt/local/share/clang-32/bin/../lib/c++/v1"
ignoring nonexistent directory "/usr/local/include"
ignoring duplicate directory "/Users/walter/code/tbb41_20121003oss//include"
#include "..." search starts here:
#include <...> search starts here:
 /Users/walter/code/tbb41_20121003oss//include
 /usr/include/c++/v1
 /opt/local/share/clang-32/bin/../lib/clang/3.2/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
0  clang             0x0000000103e69005 llvm::SmallVectorImpl<char>::swap(llvm::SmallVectorImpl<char>&) + 13189
1  clang             0x0000000103e69424 llvm::SmallVectorImpl<char>::swap(llvm::SmallVectorImpl<char>&) + 14244
2  libsystem_c.dylib 0x00007fff8871c94a _sigtramp + 26
3  clang             0x0000000102d7056c std::vector<std::pair<llvm::Constant*, int>, std::allocator<std::pair<llvm::Constant*, int> > >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::pair<llvm::Constant*, int>*, std::vector<std::pair<llvm::Constant*, int>, std::allocator<std::pair<llvm::Constant*, int> > > >, std::pair<llvm::Constant*, int> const&) + 14908
4  clang             0x0000000102f8bd31 llvm::SmallVectorImpl<unsigned int>::swap(llvm::SmallVectorImpl<unsigned int>&) + 22705
5  clang             0x0000000102f8c4d6 llvm::SmallVectorImpl<unsigned int>::swap(llvm::SmallVectorImpl<unsigned int>&) + 24662
6  clang             0x0000000102f6f52e llvm::SmallVectorImpl<clang::sema::FunctionScopeInfo::WeakUseTy>::operator=(llvm::SmallVectorImpl<clang::sema::FunctionScopeInfo::WeakUseTy> const&) + 171294
7  clang             0x0000000102f6e0e8 llvm::SmallVectorImpl<clang::sema::FunctionScopeInfo::WeakUseTy>::operator=(llvm::SmallVectorImpl<clang::sema::FunctionScopeInfo::WeakUseTy> const&) + 166104
8  clang             0x0000000102f5217e llvm::SmallVectorImpl<clang::sema::FunctionScopeInfo::WeakUseTy>::operator=(llvm::SmallVectorImpl<clang::sema::FunctionScopeInfo::WeakUseTy> const&) + 51566
9  clang             0x0000000103042883 llvm::SmallVectorImpl<clang::DeducedTemplateArgument>::operator=(llvm::SmallVectorImpl<clang::DeducedTemplateArgument> const&) + 65187
10 clang             0x00000001030498bc llvm::SmallVectorImpl<clang::DeducedTemplateArgument>::operator=(llvm::SmallVectorImpl<clang::DeducedTemplateArgument> const&) + 93916
11 clang             0x000000010304a2bf llvm::SmallVectorImpl<clang::DeducedTemplateArgument>::operator=(llvm::SmallVectorImpl<clang::DeducedTemplateArgument> const&) + 96479
12 clang             0x00000001030370b1 llvm::SmallVectorImpl<clang::DeducedTemplateArgument>::operator=(llvm::SmallVectorImpl<clang::DeducedTemplateArgument> const&) + 18129
13 clang             0x0000000103035884 llvm::SmallVectorImpl<clang::DeducedTemplateArgument>::operator=(llvm::SmallVectorImpl<clang::DeducedTemplateArgument> const&) + 11940
14 clang             0x000000010303ad9f llvm::SmallVectorImpl<clang::DeducedTemplateArgument>::operator=(llvm::SmallVectorImpl<clang::DeducedTemplateArgument> const&) + 33727
15 clang             0x000000010303b481 llvm::SmallVectorImpl<clang::DeducedTemplateArgument>::operator=(llvm::SmallVectorImpl<clang::DeducedTemplateArgument> const&) + 35489
16 clang             0x000000010303c816 llvm::SmallVectorImpl<clang::DeducedTemplateArgument>::operator=(llvm::SmallVectorImpl<clang::DeducedTemplateArgument> const&) + 40502
17 clang             0x0000000103075e8f llvm::SmallVectorImpl<clang::Decl*>::operator=(llvm::SmallVectorImpl<clang::Decl*> const&) + 108383
18 clang             0x0000000102eb8c79 llvm::SmallVectorImpl<clang::sema::DelayedDiagnostic>::operator=(llvm::SmallVectorImpl<clang::sema::DelayedDiagnostic> const&) + 13497
19 clang             0x000000010303b020 llvm::SmallVectorImpl<clang::DeducedTemplateArgument>::operator=(llvm::SmallVectorImpl<clang::DeducedTemplateArgument> const&) + 34368
20 clang             0x000000010303b481 llvm::SmallVectorImpl<clang::DeducedTemplateArgument>::operator=(llvm::SmallVectorImpl<clang::DeducedTemplateArgument> const&) + 35489
21 clang             0x000000010303c816 llvm::SmallVectorImpl<clang::DeducedTemplateArgument>::operator=(llvm::SmallVectorImpl<clang::DeducedTemplateArgument> const&) + 40502
22 clang             0x0000000103075e8f llvm::SmallVectorImpl<clang::Decl*>::operator=(llvm::SmallVectorImpl<clang::Decl*> const&) + 108383
23 clang             0x0000000102e1cc84 std::vector<std::pair<unsigned int, clang::SourceLocation>, std::allocator<std::pair<unsigned int, clang::SourceLocation> > >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::pair<unsigned int, clang::SourceLocation>*, std::vector<std::pair<unsigned int, clang::SourceLocation>, std::allocator<std::pair<unsigned int, clang::SourceLocation> > > >, std::pair<unsigned int, clang::SourceLocation> const&) + 2052
24 clang             0x0000000102e7915c std::_Rb_tree<clang::NamespaceDecl*, std::pair<clang::NamespaceDecl* const, clang::NamespaceDecl*>, std::_Select1st<std::pair<clang::NamespaceDecl* const, clang::NamespaceDecl*> >, std::less<clang::NamespaceDecl*>, std::allocator<std::pair<clang::NamespaceDecl* const, clang::NamespaceDecl*> > >::_M_erase(std::_Rb_tree_node<std::pair<clang::NamespaceDecl* const, clang::NamespaceDecl*> >*) + 860
25 clang             0x0000000102de5141 llvm::SmallVectorTemplateBase<clang::ParsedTemplateArgument, false>::grow(unsigned long) + 33441
26 clang             0x0000000102de5440 llvm::SmallVectorTemplateBase<clang::ParsedTemplateArgument, false>::grow(unsigned long) + 34208
27 clang             0x0000000102dae854 std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> >::_M_insert_aux(__gnu_cxx::__normal_iterator<clang::IdentifierInfo**, std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> > >, clang::IdentifierInfo* const&) + 20820
28 clang             0x0000000102daa1da std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> >::_M_insert_aux(__gnu_cxx::__normal_iterator<clang::IdentifierInfo**, std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> > >, clang::IdentifierInfo* const&) + 2778
29 clang             0x0000000102da9a81 std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> >::_M_insert_aux(__gnu_cxx::__normal_iterator<clang::IdentifierInfo**, std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> > >, clang::IdentifierInfo* const&) + 897
30 clang             0x0000000102da996e std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> >::_M_insert_aux(__gnu_cxx::__normal_iterator<clang::IdentifierInfo**, std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> > >, clang::IdentifierInfo* const&) + 622
31 clang             0x0000000102dd00f3 std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> >::_M_insert_aux(__gnu_cxx::__normal_iterator<clang::IdentifierInfo**, std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> > >, clang::IdentifierInfo* const&) + 158195
32 clang             0x0000000102dcfc61 std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> >::_M_insert_aux(__gnu_cxx::__normal_iterator<clang::IdentifierInfo**, std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> > >, clang::IdentifierInfo* const&) + 157025
33 clang             0x0000000102dcf30a std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> >::_M_insert_aux(__gnu_cxx::__normal_iterator<clang::IdentifierInfo**, std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> > >, clang::IdentifierInfo* const&) + 154634
34 clang             0x0000000102dd59cf std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> >::_M_insert_aux(__gnu_cxx::__normal_iterator<clang::IdentifierInfo**, std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> > >, clang::IdentifierInfo* const&) + 180943
35 clang             0x0000000102dd75bf std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> >::_M_insert_aux(__gnu_cxx::__normal_iterator<clang::IdentifierInfo**, std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> > >, clang::IdentifierInfo* const&) + 188095
36 clang             0x0000000102de4006 llvm::SmallVectorTemplateBase<clang::ParsedTemplateArgument, false>::grow(unsigned long) + 29030
37 clang             0x0000000102d904cf std::vector<std::pair<llvm::WeakVH, llvm::Constant*>, std::allocator<std::pair<llvm::WeakVH, llvm::Constant*> > >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::pair<llvm::WeakVH, llvm::Constant*>*, std::vector<std::pair<llvm::WeakVH, llvm::Constant*>, std::allocator<std::pair<llvm::WeakVH, llvm::Constant*> > > >, std::pair<llvm::WeakVH, llvm::Constant*> const&) + 109567
38 clang             0x0000000102de3798 llvm::SmallVectorTemplateBase<clang::ParsedTemplateArgument, false>::grow(unsigned long) + 26872
39 clang             0x0000000102de3303 llvm::SmallVectorTemplateBase<clang::ParsedTemplateArgument, false>::grow(unsigned long) + 25699
40 clang             0x0000000102de2920 llvm::SmallVectorTemplateBase<clang::ParsedTemplateArgument, false>::grow(unsigned long) + 23168
41 clang             0x0000000102de2014 llvm::SmallVectorTemplateBase<clang::ParsedTemplateArgument, false>::grow(unsigned long) + 20852
42 clang             0x0000000102d85256 std::vector<std::pair<llvm::WeakVH, llvm::Constant*>, std::allocator<std::pair<llvm::WeakVH, llvm::Constant*> > >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::pair<llvm::WeakVH, llvm::Constant*>*, std::vector<std::pair<llvm::WeakVH, llvm::Constant*>, std::allocator<std::pair<llvm::WeakVH, llvm::Constant*> > > >, std::pair<llvm::WeakVH, llvm::Constant*> const&) + 63878
43 clang             0x0000000102d4ed9a std::vector<clang::CXXRecordDecl const*, std::allocator<clang::CXXRecordDecl const*> >::_M_insert_aux(__gnu_cxx::__normal_iterator<clang::CXXRecordDecl const**, std::vector<clang::CXXRecordDecl const*, std::allocator<clang::CXXRecordDecl const*> > >, clang::CXXRecordDecl const* const&) + 4282
44 clang             0x0000000102b71036 std::_Rb_tree<clang::edit::FileOffset, std::pair<clang::edit::FileOffset const, clang::edit::EditedSource::FileEdit>, std::_Select1st<std::pair<clang::edit::FileOffset const, clang::edit::EditedSource::FileEdit> >, std::less<clang::edit::FileOffset>, std::allocator<std::pair<clang::edit::FileOffset const, clang::edit::EditedSource::FileEdit> > >::_M_erase(std::_Rb_tree_node<std::pair<clang::edit::FileOffset const, clang::edit::EditedSource::FileEdit> >*) + 4422
45 clang             0x0000000102b5435d std::vector<clang::CompilerInstance*, std::allocator<clang::CompilerInstance*> >::_M_insert_aux(__gnu_cxx::__normal_iterator<clang::CompilerInstance**, std::vector<clang::CompilerInstance*, std::allocator<clang::CompilerInstance*> > >, clang::CompilerInstance* const&) + 14477
46 clang             0x0000000102b23c96 std::_Rb_tree<std::string, std::string, std::_Identity<std::string>, std::less<std::string>, std::allocator<std::string> >::_M_insert_unique(std::string const&) + 4278
47 clang             0x0000000102b1bf59
48 clang             0x0000000102b20663 std::vector<std::string, std::allocator<std::string> >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, std::string const&) + 3507
49 clang             0x0000000102b1bc34
Stack dump:
0.	Program arguments: /opt/local/share/clang-32/bin/clang -cc1 -triple x86_64-apple-macosx10.8.0 -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name test1.cc -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 134.9 -v -resource-dir /opt/local/share/clang-32/bin/../lib/clang/3.2 -fmodule-cache-path /var/folders/n5/bcfvl8s53ds0g8slrlcwnk9m0000gq/T/clang-module-cache -I/Users/walter/code/tbb41_20121003oss//include -I/Users/walter/code/tbb41_20121003oss//include -stdlib=libc++ -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /Users/walter1/nemo/usr/dehnen/utils -ferror-limit 19 -fmessage-length 167 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.8.0 -fobjc-dispatch-method=mixed -fobjc-default-synthesize-properties -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/n5/bcfvl8s53ds0g8slrlcwnk9m0000gq/T/test1-mmEPFD.o -x c++ test1.cc 
1.	test1.cc:9:70: current parser token 'value'
2.	test1.cc:6:1: parsing function body 'main'
3.	test1.cc:6:1: in compound statement ('{}')
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.2 (tags/RELEASE_32/final)
Target: x86_64-apple-darwin12.3.0
Thread model: posix

**Comment by Endilll** [comment]
Can't reproduce on either 3.5 or 16: https://godbolt.org/z/vn9PvbWeK
We have libc++ 3.5 readily available now, but going older than that is somewhat challenging.
