### ISSUE TITLE
variable with constant initializer is dependent

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16108]
|  |  |
| --- | --- |
| Bugzilla Link | [15736](https://llvm.org/bz15736) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
Variable with constant initializer is considered dependent currently. That is why clang do not print error on the following code:

template <int N>
struct x
{
    static const int M = 10;

    typedef typename x<M>::asdf mytype2;
};

GCC understand that M is not dependent and print error message:

12.cpp:6:28: error: 'asdf' in 'struct x<10>' does not name a type

**Comment by wheatman** [comment]
This seems to have been fixed between 11.0.1 and 12.0.0 and now gives an error
https://godbolt.org/z/EqYevn3W5

for reference
code
```
template <int N>
struct x
{
    static const int M = 10;

    typedef typename x<M>::asdf mytype2;
};

```

error with 12.0.0
```
<source>:6:22: error: implicit instantiation of template 'x<10>' within its own definition
    typedef typename x<M>::asdf mytype2;
                     ^
1 error generated.
Compiler returned: 1
```
