### ISSUE TITLE
clang -fixit hits an assertions when given two files

### ISSUE THREAD

**Issue by Weverything** [llvm/llvm-project#16134]
|  |  |
| --- | --- |
| Bugzilla Link | [15762](https://llvm.org/bz15762) |
| Version | trunk |
| OS | Linux |

## Extended Description 
clang -cc1 -fixit a b

llvm/tools/clang/include/clang/Basic/Diagnostic.h:371: clang::SourceManager& clang::DiagnosticsEngine::getSourceManager() const: Assertion `SourceMgr && "SourceManager not set!"' failed.

Running Clang fixit with any two files will cause an assertion failure.

Tested at r179627.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.6.
