### ISSUE TITLE
unable to match template friend conversion operator in redeclaration lookup

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#16136]
|  |  |
| --- | --- |
| Bugzilla Link | [15764](https://llvm.org/bz15764) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Clang rejects this:

```cpp
template<typename T, typename U> using X = T(*)(U);
struct S { template<typename T, typename U> operator X<T,U>(); };
struct U { template<typename T, typename U> friend S::operator X<T,U>(); };
```

error: no function named 'operator type-parameter-0-0 (*)(struct U)' with type 'X<T, U> ()' was found in the specified scope

This code is valid; EDG and g++ accept.

**Comment by shafik** [comment]
Looks like it was fixed around clang-11: https://godbolt.org/z/vhrhaMPqj
