### ISSUE TITLE
no diagnostic for template friend which names nonexistent class member

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#16144]
|  |  |
| --- | --- |
| Bugzilla Link | [15772](https://llvm.org/bz15772) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Clang accepts this:

  struct X { const char *f(); };
  struct B { template<typename T> friend void X::f(T); };

It looks like we're injecting the friend template into the scope of X rather than requiring it to redeclare a member in X. We do diagnose if there is no function named 'f' in X, however.

**Comment by wheatman** [comment]
This was fixed between 8 and 9
https://godbolt.org/z/e5v697rW3

code
```
struct X { const char *f(); };
struct B { template<typename T> friend void X::f(T); };
```

new error
```
<source>:2:50: error: friend declaration of 'f' does not match any declaration in 'X'
  struct B { template<typename T> friend void X::f(T); };
                                                 ^
1 error generated.
Compiler returned: 1
```
