### ISSUE TITLE
need eager instantiation of default template arguments

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#16141]
|  |  |
| --- | --- |
| Bugzilla Link | [15769](https://llvm.org/bz15769) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
This is ill-formed (with a required diagnostic):

```cpp
  #include <type_traits>

  template<class T>
  struct X {
    template<class U = typename T::type>
    static void foo(int){}
    static void foo(...){}
  };

  int main(){
    X<std::enable_if<false>>::foo(0);
  }
```

g++ and EDG reject, clang accepts.

**Comment by shafik** [comment]
Looks like it was fixed in clang-3.4.1: https://godbolt.org/z/s3o9Tr7PM
