### ISSUE TITLE
optimize attribute ignored by clang 11

### ISSUE THREAD

**Issue by dpotop** [llvm/llvm-project#162]
Hello,

I'm using clang 11.0.0 (MacOSX Xcode build).
The following code:
`__attribute__((optimize("-O0")))
int bench_fun() {
    return 0 ;
}
`
gives the following warning:
> try.c:26:16: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]

Is this a bug, or a feature? If it's a feature, how can I obtain the same effect?

Best regards,
dpotop

**Comment by tclin914** [comment]
It looks like that clang doesn't support this function attribute.
Do you have tried other versions of clang?
If you expect the function without any optimization, you can use '__attribute__(optnone)'..

**Comment by dpotop** [comment]
Thanks tclin914. optnone seems to work. Too bad, however, that the general attribute "optimize" does not work, for compatibility with gcc.
