### ISSUE TITLE
clang-3.2 does not pass 26 tests

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16201]
|  |  |
| --- | --- |
| Bugzilla Link | [15829](https://llvm.org/bz15829) |
| Version | 3.2 |
| OS | All |
| Attachments | [clang-3.2 gentoo build log](https://user-images.githubusercontent.com/60944935/143747289-b8df6ab5-a09b-49eb-b90b-b7739e38a796.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

clang-3.2 was compiled using gcc-4.7.2 (Gentoo Hardened amd64 4.7.2-r1 p1.5, pie-0.5.5). The complete build log is attached. In the build log, among the errors in the condensed list below, a similar pattern appears several times:

 Exit Code: 1
 Command Output (stderr):
 --
 opt: <stdin>:22:39: error: expected '{' in function body
 define i32 @&#8203;s0_load_x(%struct.s0* %a) #&#8203;0 {
                                     ^
--

XFAIL: Clang :: ARCMT/GC-check-warn-nsalloc.m (1 of 6207)
XFAIL: Clang :: Analysis/outofbound-notwork.c (264 of 6207)
XFAIL: Clang :: Analysis/string-fail.c (311 of 6207)
XFAIL: Clang :: CXX/basic/basic.lookup/basic.lookup.qual/p6-0x.cpp (360 of 6207)
XFAIL: Clang :: CXX/basic/basic.lookup/basic.lookup.unqual/p15.cpp (367 of 6207)
XFAIL: Clang :: CXX/dcl.dcl/dcl.spec/dcl.fct.spec/p4.cpp (480 of 6207)
XFAIL: Clang :: CXX/dcl.dcl/dcl.spec/dcl.stc/p10.cpp (484 of 6207)
XFAIL: Clang :: CXX/temp/temp.param/p14.cpp (816 of 6207)
XFAIL: Clang :: CXX/temp/temp.res/temp.dep.res/temp.point/p1.cpp (827 of 6207)
 FAIL: Clang :: CodeGen/2005-06-15-ExpandGotoInternalProblem.c (1039 of 6207)
XFAIL: Clang :: CodeGen/blocks-2.c (1312 of 6207)
 FAIL: Clang :: CodeGen/extern-weak.c (1422 of 6207)
XFAIL: Clang :: CodeGen/libcalls-d.c (1468 of 6207)
XFAIL: Clang :: CodeGen/libcalls-ld.c (1470 of 6207)
 FAIL: Clang :: CodeGen/packed-structure.c (1536 of 6207)
XFAIL: Clang :: CodeGenCXX/conversion-function.cpp (1809 of 6207)
XFAIL: Clang :: CodeGenCXX/debug-info-limit-type.cpp (1875 of 6207)
 FAIL: Clang :: CodeGenCXX/for-range-temporaries.cpp (1934 of 6207)
 FAIL: Clang :: CodeGenCXX/for-range.cpp (1935 of 6207)
XFAIL: Clang :: FixIt/fixit-pmem.cpp (2725 of 6207)
XFAIL: Clang :: PCH/changed-files.c (3239 of 6207)
XFAIL: Clang :: PCH/pr4489.c (3319 of 6207)
XFAIL: Clang :: PCH/source-manager-stack.c (3335 of 6207)
XFAIL: Clang :: Parser/cxx-ambig-decl-expr-xfail.cpp (3390 of 6207)
XFAIL: Clang :: SemaCXX/switch-implicit-fallthrough-cxx98.cpp (4558 of 6207)
XFAIL: Clang :: SemaTemplate/instantiate-function-1.mm (5266 of 6207)

**Comment by arsenm** [comment]
Old build issue
