### ISSUE TITLE
[C99] clang crashes on compound literal initialization with address-of as element.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16211]
|  |  |
| --- | --- |
| Bugzilla Link | [15839](https://llvm.org/bz15839) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
given test.c:

int x;
struct S { int x : 2; };
struct S b = (struct S){ &x };

clang test.c

This will crash clang. 
I believe this is invalid c99 code since &x is not a constant expression.

**Comment by AaronBallman** [comment]
I cannot reproduce this with Clang trunk either, so closing as WORKSFORME. If you can still reproduce the issue, please reopen it with more details about how to reproduce.
