### ISSUE TITLE
Build of LLVM + Clang with Clang as Compiler fails

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16262]
|  |  |
| --- | --- |
| Bugzilla Link | [15890](https://llvm.org/bz15890) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@isanbard |

## Extended Description 
Build clang version 3.3 (trunk 180835) (llvm/trunk 180832) in Debug with Assertions on a stock Debian 6 with gcc, then tried to build the same clang in Release + Assertions with the Debug Clang.

llvm[3]: Compiling X86InstrInfo.cpp for Release+Asserts build
clang: /second/llvm/lib/CodeGen/RegisterCoalescer.cpp:589: bool<unnamed>::RegisterCoalescer::removeCopyByCommutingDef(const llvm::CoalescerPair&, llvm::MachineInstr*): Assertion `AValNo && "COPY source not live"' failed.
0  clang           0x000000000300f65e _ZN4llvm3sys15PrintStackTraceEP8_IO_FILE + 38
1  clang           0x000000000300f8c2
2  clang           0x000000000300f333
3  libpthread.so.0 0x00002b1dcf4daff0
4  libc.so.6       0x00002b1dd02d41b5 gsignal + 53
5  libc.so.6       0x00002b1dd02d6fc0 abort + 384
6  libc.so.6       0x00002b1dd02cd301 __assert_fail + 241
7  clang           0x00000000029c06cb
8  clang           0x00000000029c2cd3
9  clang           0x00000000029c6214
10 clang           0x00000000029c69fd
11 clang           0x00000000029c6cbf
12 clang           0x0000000002939f55 _ZN4llvm19MachineFunctionPass13runOnFunctionERNS_8FunctionE + 95
13 clang           0x0000000002f93b89 _ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE + 393
14 clang           0x0000000002f93d89 _ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE + 89
15 clang           0x0000000002f94101 _ZN4llvm13MPPassManager11runOnModuleERNS_6ModuleE + 573
16 clang           0x0000000002f94716 _ZN4llvm15PassManagerImpl3runERNS_6ModuleE + 254
17 clang           0x0000000002f94a71 _ZN4llvm11PassManager3runERNS_6ModuleE + 39
18 clang           0x0000000000ec457c
19 clang           0x0000000000ec4646 _ZN5clang17EmitBackendOutputERNS_17DiagnosticsEngineERKNS_14CodeGenOptionsERKNS_13TargetOptionsERKNS_11LangOptionsEPN4llvm6ModuleENS_13BackendActionEPNSB_11raw_ostreamE + 140
20 clang           0x0000000000ec043f
21 clang           0x00000000010b0b08 _ZN5clang8ParseASTERNS_4SemaEbb + 789
22 clang           0x0000000000c73cd6 _ZN5clang17ASTFrontendAction13ExecuteActionEv + 298
23 clang           0x0000000000ebf79c _ZN5clang13CodeGenAction13ExecuteActionEv + 1296
24 clang           0x0000000000c73858 _ZN5clang14FrontendAction7ExecuteEv + 200
25 clang           0x0000000000c468b2 _ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE + 726
26 clang           0x0000000000c14f40 _ZN5clang25ExecuteCompilerInvocationEPNS_16CompilerInstanceE + 1048
27 clang           0x0000000000c04e40 _Z8cc1_mainPPKcS1_S0_Pv + 673
28 clang           0x0000000000c0f489 main + 484
29 libc.so.6       0x00002b1dd02c0c8d __libc_start_main + 253
30 clang           0x0000000000c045a9
Stack dump:
0.      Program arguments: /usr/local/bin/clang -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -main-file-name X86InstrInfo.cpp -mrelocation-model pic -pic-level 2 -fmath-errno -masm-verbos                                 tables -target-cpu x86-64 -target-linker-version 2.20.1 -momit-leaf-frame-pointer -coverage-file /second/llvm-buildr/lib/Target/X86/Release+Asserts/X86InstrInfo.o -resource-dir /usr/local/bin/../lib/clang                                 m-buildr/lib/Target/X86/Release+Asserts/X86InstrInfo.d.tmp -MP -MT /second/llvm-buildr/lib/Target/X86/Release+Asserts/X86InstrInfo.o -MT /second/llvm-buildr/lib/Target/X86/Release+Asserts/X86InstrInfo.d -                                 _CONSTANT_MACROS -D __STDC_FORMAT_MACROS -D __STDC_LIMIT_MACROS -I /second/llvm-buildr/include -I /second/llvm-buildr/lib/Target/X86 -I /second/llvm/include -I /second/llvm/lib/Target/X86 -internal-isyste                                 /4.4/../../../../include/c++/4.4 -internal-isystem /usr/lib64/gcc/x86_64-linux-gnu/4.4/../../../../include/c++/4.4/x86_64-linux-gnu -internal-isystem /usr/lib64/gcc/x86_64-linux-gnu/4.4/../../../../includ                                 tem /usr/lib64/gcc/x86_64-linux-gnu/4.4/../../../../include/x86_64-linux-gnu/c++/4.4 -internal-isystem /usr/local/include -internal-isystem /usr/local/bin/../lib/clang/3.3/include -internal-externc-isyste                                 tem /usr/include -O3 -Woverloaded-virtual -Wcast-qual -Wno-long-long -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcovered-switch-default -Wno-uninitialized -Wno-missing-field-initializers -pedantic -f                                 -fdebug-compilation-dir /second/llvm-buildr/lib/Target/X86 -ferror-limit 19 -fmessage-length 237 -fvisibility-inlines-hidden -mstackrealign -fno-rtti -fobjc-runtime=gcc -fobjc-default-synthesize-propertie                                 or-diagnostics -backend-option -vectorize-loops -o /second/llvm-buildr/lib/Target/X86/Release+Asserts/X86InstrInfo.o -x c++ /second/llvm/lib/Target/X86/X86InstrInfo.cpp
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module '/second/llvm/lib/Target/X86/X86InstrInfo.cpp'.
4.      Running pass 'Simple Register Coalescing' on function '@_ZNK4llvm12X86InstrInfo19unfoldMemoryOperandERNS_15MachineFunctionEPNS_12MachineInstrEjbbRNS_15SmallVectorImplIS4_EE'
clang: error: unable to execute command: Aborted
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.3 (trunk 180835) (llvm/trunk 180832)
Target: x86_64-unknown-linux-gnu
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/X86InstrInfo-JkH5K1.cpp
clang: note: diagnostic msg: /tmp/X86InstrInfo-JkH5K1.sh
clang: note: diagnostic msg:

********************
/bin/rm: cannot remove `/second/llvm-buildr/lib/Target/X86/Release+Asserts/X86InstrInfo.d.tmp': No such file or directory
make[3]: *** [/second/llvm-buildr/lib/Target/X86/Release+Asserts/X86InstrInfo.o] Error 1
make[3]: Leaving directory `/second/llvm-buildr/lib/Target/X86'
make[2]: *** [X86/.makeall] Error 2
make[2]: Leaving directory `/second/llvm-buildr/lib/Target'
make[1]: *** [Target/.makeall] Error 2
make[1]: Leaving directory `/second/llvm-buildr/lib'
make: *** [all] Error 1

**Comment by Endilll** [comment]
Unfortunately, uploaded.net died on December 1, 2022.
Feel free to reopen this issue with a reproducer.
