### ISSUE TITLE
clang-3.2 C++ SEGV

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16269]
|  |  |
| --- | --- |
| Bugzilla Link | [15897](https://llvm.org/bz15897) |
| Version | 3.2 |
| OS | Linux |
| Attachments | [c++ source and stderr output](https://user-images.githubusercontent.com/60944935/143747342-b30e9511-dd6b-4c1a-97de-58460c5d1483.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 

Hi, 

I am new to clang and bug reporting, so if there's sth missing 
pleas point me at it and I'll try to help as best as I can.

I am trying to compile a mid-sized project using some boost code,
and clang SEGV's on it. The code works fine on several versions of gcc,
and has been reported to work with clang-3.1 and earlier.

I attached a ZIP containing the *.cpp and *.sh file 
created by clang++ -v and the trace information on stderr.

I removed all optimisation etc. options down to:
clang++ -v -I. -c boost/regex/src/fileiter.cpp -o boost/regex/src/fileiter.o
and the SEGV remains. 

The development system is ubuntu 12.04, with clang pulled from 
https://launchpad.net/~kxstudio-team/+archive/builds,
versions are shown below.

If I run the shell script in the attachement, it reports 20+ errors. 
Could the SEGV be a subsequent problem ? But why do I get 
a SEGV instead of the error messages when just running clang++ ?

Yours,
Steffen

ii  clang                                  3.2-1~exp5ubuntu1~precise1              C, C++ and Objective-C compiler (LLVM based)
ii  clang-3.2                              3.2-1~exp5ubuntu1~precise1              C, C++ and Objective-C compiler (LLVM based)
ii  compiler-rt                            3.2-1~exp5ubuntu1~precise1              Runtime C library - LLVM based
ii  libllvm3.0                             3.0-4ubuntu1                            Low-Level Virtual Machine (LLVM), runtime library
ii  libllvm3.0:i386                        3.0-4ubuntu1                            Low-Level Virtual Machine (LLVM), runtime library
ii  libllvm3.2                             3.2-2ubuntu3~precise1                   Low-Level Virtual Machine (LLVM), runtime library
ii  llvm-3.2                               3.2-2ubuntu3~precise1                   Low-Level Virtual Machine (LLVM)
ii  llvm-3.2-dev                           3.2-2ubuntu3~precise1                   Low-Level Virtual Machine (LLVM), libraries and headers
ii  llvm-3.2-runtime                       3.2-2ubuntu3~precise1                   Low-Level Virtual Machine (LLVM), bytecode interpreter

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.2 or 3.3 with assertions enabled.
