### ISSUE TITLE
clang-format.py is not installed

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16270]
|  |  |
| --- | --- |
| Bugzilla Link | [15898](https://llvm.org/bz15898) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Make install install clang-format, but not clang-format.py.

**Comment by mkurdej** [comment]
Fixed in November 2013... commit https://github.com/llvm/llvm-project/commit/ae78e23e5f43e5d78fa0550e7dce64c21c758839.
