### ISSUE TITLE
crash-on-invalid with invalid friend definition inside class

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#16280]
|  |  |
| --- | --- |
| Bugzilla Link | [15908](https://llvm.org/bz15908) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
This triggers an assert:

struct X {
  class foo_bar_Test {
    void TestBody();
  };
  friend void foo_bar_Test::TestBody() {
  }
};

clang-3.2: tools/clang/lib/Sema/SemaAccess.cpp:1753: Sema::AccessResult clang::Sema::CheckFriendAccess(clang::NamedDecl *): Assertion `method->getQualifier()' failed.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.6: https://cexplorer.testlabs.pro/z/4cbf3o
