### ISSUE TITLE
Implement an equivalent of GDB's TUI

### ISSUE THREAD

**Issue by 84cb368b-a7ae-40d6-bde1-4a04fa9aa698** [llvm/llvm-project#16343]
|  |  |
| --- | --- |
| Bugzilla Link | [15971](https://llvm.org/bz15971) |
| Version | unspecified |
| OS | All |
| CC | @compnerd,@jryans |

## Extended Description 
It would be really great if LLDB had an equivalent of GDB's TUI.

http://sourceware.org/gdb/current/onlinedocs/gdb/TUI.html

**Comment by DavidSpickett** [comment]
This was added some time ago, use the `gui` command to enter it.
