### ISSUE TITLE
llc 3.3rc1 fails to compile attached ll file

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16383]
|  |  |
| --- | --- |
| Bugzilla Link | [16011](https://llvm.org/bz16011) |
| Version | trunk |
| OS | Linux |
| Attachments | [ll file to reproduce problem](https://user-images.githubusercontent.com/60944935/143747395-56381b21-d09f-4b96-a793-b289a56d5634.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie,@isanbard |

## Extended Description 

When I run llc 3.3rc1 on ARM on attached file it fails when processing debug info as follows:

llc: /home/deldon/Work/llvm/3.3rc1/sources/lib/CodeGen/LexicalScopes.cpp:191: llvm::LexicalScope* llvm::LexicalScopes::getOrCreateAbstractScope(const llvm::MDNode*): Assertion `N && "Invalid Scope encoding!"' failed.
Stack dump:
0.	Program arguments: /home/deldon/Work/llvm/3.3rc1/bin.arm/bin/llc ./core_list_join.llvm -march=arm -mcpu=cortex-a9 -mattr=+neon,-vmlx-forwarding -float-abi=soft -o ./core_list_join.s -debug 
1.	Running pass 'Function Pass Manager' on module './core_list_join.llvm'.
2.	Running pass 'Debug Variable Analysis' on function '@core_bench_list'

**Comment by arsenm** [comment]
Comments say this is an upgrade issue for 10 year old debug info
