### ISSUE TITLE
Clang ignores include path arguments when compiling assembly files

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16394]
|  |  |
| --- | --- |
| Bugzilla Link | [16022](https://llvm.org/bz16022) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I am using the llvm/clang trunk from last week.

To reproduce:

    mkdir /tmp/test
    cd /tmp/test
    mkdir baz
    echo -e "\n" > baz/bar.s
    echo -e ".include \"bar.s\"\n.global main\nmain: hlt\n" > foo.s

GCC has no problem following the .include and successfully creates a "working" binary:

    gcc foo.s -I/tmp/test/baz -o a.out
    ./a.out
  Segmentation fault (core dumped)

Clang on the other hand fails miserably to understand the -I argument:

    clang foo.s -I/tmp/test/baz -o a.out
clang-3.4: warning: argument unused during compilation: '-I /tmp/test/baz'
foo.s:1:10: error: Could not find include file 'bar.s'
.include "bar.s"

Unfortunately this makes clang useless when compiling assembly code with .include statements.

Also see specification here: http://sourceware.org/binutils/docs-2.17/as/I.html

**Comment by widberg** [comment]
Two years after this issue was opened, commit https://github.com/llvm/llvm-project/commit/c78c2bcb2a005266d7c6982ed57accd394028153 made it so `-I` options are passed to cc1as for `.include` search paths. I do not have this issue on Clang 17.
