### ISSUE TITLE
installed LLVM gives not enough permissions for users

### ISSUE THREAD

**Issue by c1f2da5c-3510-4ef9-b7bb-24e698b33024** [llvm/llvm-project#16399]
|  |  |
| --- | --- |
| Bugzilla Link | [16027](https://llvm.org/bz16027) |
| Version | 3.2 |
| OS | Linux |

## Extended Description 
I have downloaded the LLVM-3.2 release from
   http://llvm.org/releases/3.2/llvm-3.2.src.tar.gz

Then I did
$ ./configure --enable-assertions --enable-shared --prefix=/usr/local/llvm-3.2
$ make -j4
$ sudo make install

and end up with:
$ ls -al /usr/local/ | fgrep llvm
drwx------  6 root root 4096 Mai 16 11:23 llvm-3.2

That is, read and execution permission for the llvm-3.2 directory (and all of its sub-directories and files) are missing.

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
