### ISSUE TITLE
incorrect mangling for same name used for multiple types defined inside a function

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#16390]
|  |  |
| --- | --- |
| Bugzilla Link | [16018](https://llvm.org/bz16018) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Consider:

```cpp
inline auto f() {
  struct S {
    auto f() {
      struct S {};
      return S();
    }
  };
  return S().f();
}
typedef decltype(f()) S;
void g(S s) {}
```

clang++ mangles 'g' as _Z1gZZ1fvEN1S1fEvE1S_0
But g++ mangles 'g' as _Z1gZZ1fvEN1S1fEvE1S

The Itanium ABI is not spectacularly clear here, but presumably we're supposed to have separate independent counts for the body of each function, even if one is nested within another.

Here's another case which we get wrong (much more surprisingly; I thought we handled this case):
```cpp
inline auto f() {
  { struct S {}; }
  { struct S {}; return S(); }
}
typedef decltype(f()) S;
void g(S s) {}
```
Here, we mangle as _Z1gZ1fvE1S -- which is wrong.
g++ correctly uses _Z1gZ1fvE1S_0

This can be observed outside of C++1y, too, for instance by using one of these types as a template argument.

**Comment by shafik** [comment]
It looks like these are correct now: https://godbolt.org/z/8rEWh19Pq
