### ISSUE TITLE
SROA fails to eliminate alloca

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16425]
|  |  |
| --- | --- |
| Bugzilla Link | [16053](https://llvm.org/bz16053) |
| Version | trunk |
| OS | Linux |
| Attachments | [testcase .ll](https://user-images.githubusercontent.com/60944935/143747425-5fac9f8d-6afe-4564-a15f-1b0bb30183d1.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @d0k,@chandlerc |

## Extended Description 

SROA fails to eliminate the alloca in this function.  This is the IR produced for a store to a bitfield of float type (allowed in Ada).  SROA should understand that bits 0 .. 32 of %.0.load are just the bits of %f, and the other bits are all undef.

define i64 @&#8203;bf__w__2(i64 %x.0, float %f) {
entry:
  %0 = alloca i40, align 8
  %1 = trunc i64 %x.0 to i40
  %.0.cast3 = bitcast i40* %0 to float*
  store float %f, float* %.0.cast3, align 8
  %.0.load = load i40* %0, align 8
  %2 = shl i40 %.0.load, 2
  %3 = and i40 %2, 17179869180
  %4 = and i40 %1, -17179869181
  %5 = or i40 %3, %4
  %.0.insert.ext = zext i40 %5 to i64
  ret i64 %.0.insert.ext
}

**Comment by arsenm** [comment]
Current SROA output
```
define i64 @bf__w__2(i64 %x.0, float %f) {
entry:
  %0 = trunc i64 %x.0 to i40
  %1 = bitcast float %f to i32
  %.sroa.2.0.insert.ext = zext i8 undef to i40
  %.sroa.2.0.insert.shift = shl i40 %.sroa.2.0.insert.ext, 32
  %.sroa.2.0.insert.mask = and i40 undef, 4294967295
  %.sroa.2.0.insert.insert = or i40 %.sroa.2.0.insert.mask, %.sroa.2.0.insert.shift
  %.sroa.0.0.insert.ext = zext i32 %1 to i40
  %.sroa.0.0.insert.mask = and i40 %.sroa.2.0.insert.insert, -4294967296
  %.sroa.0.0.insert.insert = or i40 %.sroa.0.0.insert.mask, %.sroa.0.0.insert.ext
  %2 = shl i40 %.sroa.0.0.insert.insert, 2
  %3 = and i40 %2, 17179869180
  %4 = and i40 %0, -17179869181
  %5 = or i40 %3, %4
  %.0.insert.ext = zext i40 %5 to i64
  ret i64 %.0.insert.ext
}
```
