### ISSUE TITLE
Segmentation fault on cyclical recursive include

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16423]
|  |  |
| --- | --- |
| Bugzilla Link | [16051](https://llvm.org/bz16051) |
| Version | 3.2 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Create 4 files:
1) 1.c:
#include "1.h"
2) 1.h
#include "2.h"
3) 2.h
#include "not_exist.h"
#include "3.h"
4)3.h
#include "3.h"
#include "1.h"

Run clang:
clang 1.c

Output:
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: clang frontend command failed due to signal 2 (use -v to see invocation)
clang: note: diagnostic msg: Please submit a bug report to http://llvm.org/bugs/ and include command line arguments and all diagnostic information.
clang: error: unable to execute command: Segmentation fault (core dumped)

**Comment by Endilll** [comment]
Appears to be fixed in Clang 7.
