### ISSUE TITLE
LLDB does not support setting breakpoints by column

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16487]
|  |  |
| --- | --- |
| Bugzilla Link | [16112](https://llvm.org/bz16112) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @echristo,@jryans,@RamNalamothu |

## Extended Description 
Currently LLDB allows setting breakpoints by line number via the "-l" option to "breakpoint set" but not by column.

This bug is to add support for setting breakpoints by column number via the command-line interface.

It looks like the LLDB API (SBBreakpoint, SBBreakpointLocation) also needs to be updated. Also, SBTarget.CreateBreakpointByLocation should be updated to take an (optional) column number parameter, or an SBLineEntry which does support columns.

**Comment by RamNalamothu** [comment]
Closing as the requested feature is already supported.
