### ISSUE TITLE
A question from a beginner.

### ISSUE THREAD

**Issue by Photonico** [llvm/llvm-project#165]
Hello,

I'm a user of Solus OS, and I'm also a beginner in programming.
In terms of that it's hard for me to compile this project, I want a binary edition of LLVM+Clang.
I found ur released the binary edition for ubuntu: `clang+llvm-9.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz`. I want to know does it work normally in my system?

Sincerely,
Lu

**Comment by xgupta** [comment]
For building llvm you can follow https://llvm.org/docs/GettingStarted.html#getting-the-source-code-and-building-llvm  and for clang you can check https://clang.llvm.org/get_started.html.
