### ISSUE TITLE
Cannot build most recent version: fatal error: 'valgrind/valgrind.h'

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16503]
|  |  |
| --- | --- |
| Bugzilla Link | [16128](https://llvm.org/bz16128) |
| Version | trunk |
| OS | MacOS X |
| Blocks | llvm/llvm-project#16104  |
| Reporter | LLVM Bugzilla Contributor |
| CC | @chandlerc,@gnzlbg,@jryans,@rnk,@steveire |

## Extended Description 
When I try to build the most recent version, I receive:

lib/Support/Valgrind.cpp:20:10: fatal error: 'valgrind/valgrind.h' file not found
#include <valgrind/valgrind.h>

Any assistance would be appreciated.

**Comment by arsenm** [comment]
Old build issue and probably user config error
