### ISSUE TITLE
Turning on gcc's optimizations halves the run-time of the gas_dyn and induct polyhedron benchmarks

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16567]
|  |  |
| --- | --- |
| Bugzilla Link | [16193](https://llvm.org/bz16193) |
| Version | 3.2 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
gcc-4.8 + LLVM 3.3 dragonegg plugin, -ffast-math -funroll-loops -O3, x86_apple-darwin12, numbers by Jack Howarth.

gas_dyn runtimes:

LLVM optimizations only: 7.94
LLVM+GCC optimizations: 4.20
Just GCC, no LLVM: 3.59

induct runtimes:

LLVM optimizations only: 24.04
LLVM+GCC optimizations: 11.85
Just GCC, no LLVM: 12.21

The GCC mid-level optimizers are doing something good here, halving the run-time.

**Comment by asl** [comment]
Dragonegg is obsolete
