### ISSUE TITLE
Code gen for contracted FP operation wrong

### ISSUE THREAD

**Issue by dbc7d0cf-60de-4ba2-bc9a-c1b7219315df** [llvm/llvm-project#16575]
|  |  |
| --- | --- |
| Bugzilla Link | [16201](https://llvm.org/bz16201) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
Code generation appears to be wrong for the contracted floating-point operation:
  p = x*y;
  m = -p;
  z = -m - (x*y);
where all the variables are of type float or double.  The other three forms:
  z = x*y - p;
  z = x*y + m;
  z = p - (x*y);
appear to be OK.

This is clang 3.3-0.4 on Linux Fedora Core 19 in 32-bit mode on an Intel
Core 2 Duo CPU.

Command line options:  -std=c1x -O0 -pedantic

**Comment by arsenm** [comment]
The default behavior for C99+ is contraction is allowed but not mandated. The backend is free to chose to codegen as it believes is faster which doesn't guarantee consistent results

**Comment by jcranmer-intel** [comment]
Actually, this isn't a bug with contraction, it's an x87 excess precision "bug." Which is also perfectly legal per C99+ (`FLT_EVAL_METHOD`=2).
