### ISSUE TITLE
Clang compiles block in .cpp file instead of generating a compilation error

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16605]
|  |  |
| --- | --- |
| Bugzilla Link | [16231](https://llvm.org/bz16231) |
| Version | unspecified |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie,@efriedma-quic,@zygoloid |

## Extended Description 
I have installed the latest version of XCode 4.6.2. Imagine there is a code sample like below.

In one project I have 3 similar classes that use blocks. One is an Objective-C:

TestClass1.h:
@&#8203;interface TestClass1 : NSObject
- (void)test;
@&#8203;end

TestClass1.m:
@&#8203;implementation TestClass1

- (void)test
{
    void (^d_block)(void) =
    ^{
        int n;
    };
}

@&#8203;end

One is in C++ (in the same project):

TestClass2.h:
class TestClass2
{
public:
    void TestIt();
};

TestClass2.cpp:
void TestClass2::TestIt()
{
    void (^d_block)(void) =
    ^{
        int n;
    };
}

One is in Objective-C++ (in the same project):

TestClass3.h:
class TestClass3
{
public:
    void TestIt();
};

TestClass3.mm:
void TestClass3::TestIt()
{
    void (^d_block)(void) =
    ^{
        int n;
    };
}

Clang compiles all these 3 classes successfully but blocks are the Objective-C feature. It seems to me that the compiler should generate an error message in .cpp file case. Is it a bug? Or maybe I don't understand something...

**Comment by davidchisnall** [comment]
Blocks are enabled or disabled by the `-f{no-}blocks` flag, which overrides the default.  The default is per target and is independent of the language selected.  If you want to disable blocks on macOS then you can use `-fno-blocks` (though there's no guarantee that you'll be able to include Apple-provided headers in the future).
