### ISSUE TITLE
JIT unittests crash when LLVM built with expensive checks enabled

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16639]
|  |  |
| --- | --- |
| Bugzilla Link | [16265](https://llvm.org/bz16265) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
LLVM configured with --enable-optimized --enable-assertions --enable-expensive-checks --enable-debug-symbols

.../unittests/ExecutionEngine/JIT/Release+Debug+Asserts+Checks/JITTests 
*** Error in `./unittests/ExecutionEngine/JIT/Release+Debug+Asserts+Checks/JITTests': free(): invalid pointer: 0x00000000014b5840 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x80a46)[0x7fbb09a9ba46]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSt15basic_stringbufIcSt11char_traitsIcESaIcEE8overflowEi+0x149)[0x7fbb0a3982a9]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSt15basic_streambufIcSt11char_traitsIcEE6xsputnEPKcl+0x36)[0x7fbb0a39c976]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_l+0x194)[0x7fbb0a393984]
./unittests/ExecutionEngine/JIT/Release+Debug+Asserts+Checks/JITTests[0x499dfd]
./unittests/ExecutionEngine/JIT/Release+Debug+Asserts+Checks/JITTests[0x49a3c2]
./unittests/ExecutionEngine/JIT/Release+Debug+Asserts+Checks/JITTests[0x445935]
./unittests/ExecutionEngine/JIT/Release+Debug+Asserts+Checks/JITTests[0xdb33dd]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85)[0x7fbb09a3ce35]
./unittests/ExecutionEngine/JIT/Release+Debug+Asserts+Checks/JITTests[0x44c7cd]

Running under valgrind shows an attempt to free a global variable:

==29624== Invalid free() / delete / delete[] / realloc()
==29624==    at 0x4C2B28C: operator delete(void*) (vg_replace_malloc.c:480)
==29624==    by 0x52EF2A8: std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::overflow(int) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.17)
==29624==    by 0x52F3975: std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.17)
==29624==    by 0x52EA983: std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.17)
==29624==    by 0x499DFC: testing::internal::FlagToEnvVar(char const*) (ostream:533)
==29624==    by 0x49A3C1: testing::internal::BoolFromGTestEnv(char const*, bool) (gtest-port.cc:712)
==29624==    by 0x445934: _GLOBAL__sub_I_gtest.cc (gtest.cc:182)
==29624==    by 0xDB33DC: __libc_csu_init (in /home/duncan/LLVM/llvm-objects/unittests/ExecutionEngine/JIT/Release+Debug+Asserts+Checks/JITTests)
==29624==    by 0x5A94E34: (below main) (libc-start.c:219)
==29624==  Address 0x14b5840 is 0 bytes inside data symbol "_ZNSs4_Rep20_S_empty_rep_storageE"

**Comment by Endilll** [comment]
Probably too old to be useful.
