### ISSUE TITLE
Several clang-check tests crash with double-free when built with expensive checks

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16640]
|  |  |
| --- | --- |
| Bugzilla Link | [16266](https://llvm.org/bz16266) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dushistov |

## Extended Description 
LLVM configured with --enable-optimized --enable-assertions --enable-expensive-checks --enable-debug-symbols

These tests fail:

    Clang :: Tooling/auto-detect-from-source-parent-of-cwd.cpp
    Clang :: Tooling/auto-detect-from-source-parent.cpp
    Clang :: Tooling/clang-check-autodetect-dir.cpp

Example failure:

*** Error in `clang-check': double free or corruption (out): 0x0000000001a57dc0 ***                                                     
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x80a46)[0x7f727c739a46]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSt15basic_stringbufIcSt11char_traitsIcESaIcEE8overflowEi+0x149)[0x7f727d0362a9]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSt15basic_streambufIcSt11char_traitsIcEE6xsputnEPKcl+0x36)[0x7f727d03a976]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_l+0x194)[0x7f727d031984]
clang-check[0x688146]
clang-check[0x6886eb]
clang-check[0x689332]
clang-check[0x687a70]
clang-check[0x4888b2]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f727c6daea5]
clang-check[0x489e4d]

**Comment by Endilll** [comment]
Probably too old to be useful.
