### ISSUE TITLE
Cannot initialize const reference function argument with braced-init-list

### ISSUE THREAD

**Issue by rubenvb** [llvm/llvm-project#16659]
|  |  |
| --- | --- |
| Bugzilla Link | [16285](https://llvm.org/bz16285) |
| Version | 3.2 |
| OS | Windows NT |
| CC | @DougGregor |

## Extended Description 
This code fails when using Clang 3.2 and current ToT, and using GCC 4.6 and 4.8's libstdc++:

#include <unordered_set>

void lol(const std::unordered_set<double>& yodel = {}) {}

int main()
{
  lol();
}

GCC accepts this since 4.7. Also see:

http://stackoverflow.com/questions/6615823/uniform-initializer-used-in-default-argument-to-const-reference
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3139.pdf

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.7: https://godbolt.org/z/E54z5j11q
