### ISSUE TITLE
llvm-config --libs dumps core

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16679]
|  |  |
| --- | --- |
| Bugzilla Link | [16305](https://llvm.org/bz16305) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
SD=/var/scratch/freundt/src/devel/llvm/tools/opt; \
  DD=opt; \
  if [ ! -f $SD/Makefile ]; then \
    SD=opt; \
    DD=opt; \
  fi; \
  if ([ ! -f $DD/Makefile ] || \
            command test $DD/Makefile -ot \
                      $SD/Makefile ); then \
  /var/scratch/freundt/src/devel/llvm/autoconf/mkinstalldirs $DD; \
  /bin/cp $SD/Makefile $DD/Makefile; \
fi; \
make -C $DD all
llvm-config: /var/scratch/freundt/src/devel/llvm/include/llvm/ADT/StringRef.h:78: llvm::StringRef::StringRef(const char*): Assertion `Str && "StringRef cannot be built from a NULL argument"' failed.
/bin/sh: line 1: 14669 Aborted                 (core dumped) /var/scratch/freundt/src/devel/llvm/build/Debug+Asserts/bin/llvm-config --libs bitreader bitwriter asmparser irreader instrumentation scalaropts objcarcopts ipo vectorize all-targets
make[2]: Entering directory `/var/scratch/freundt/src/devel/llvm/build/tools/opt'
/var/scratch/freundt/src/devel/llvm/Makefile.rules:1057: *** llvm-config --libs failed.  Stop.

$ gdb /var/scratch/freundt/src/devel/llvm/build/Debug+Asserts/bin/llvm-config core
$ bt
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7fff36bfe000
Core was generated by `/var/scratch/freundt/src/devel/llvm/build/Debug+Asserts/bin/llvm-config --libs'.
Program terminated with signal 6, Aborted.
#&#8203;0  0x00002b7f275b1ab5 in raise () from /lib64/libc.so.6
(gdb) bt
#&#8203;0  0x00002b7f275b1ab5 in raise () from /lib64/libc.so.6
#&#8203;1  0x00002b7f275b2fb6 in abort () from /lib64/libc.so.6
#&#8203;2  0x00002b7f275aa385 in __assert_fail () from /lib64/libc.so.6
#&#8203;3  0x000000000040643f in llvm::StringRef::StringRef(char const*) () at /var/scratch/freundt/src/devel/llvm/include/llvm/ADT/StringRef.h:78
#&#8203;4  0x0000000000404a35 in ComputeLibsForComponents(std::vector<llvm::StringRef, std::allocator<llvm::StringRef> > const&, std::vector<llvm::StringRef, std::allocator<llvm::StringRef> >&, bool) ()
    at /var/scratch/freundt/src/devel/llvm/tools/llvm-config/llvm-config.cpp:103
#&#8203;5  0x000000000040604a in main () at /var/scratch/freundt/src/devel/llvm/tools/llvm-config/llvm-config.cpp:328

**Comment by arsenm** [comment]
Old build issue
