### ISSUE TITLE
llvm-project build failing on link stage

### ISSUE THREAD

**Issue by qaco** [llvm/llvm-project#167]
Hello, I am building llvm-project on my laptop (Ubuntu 18.04, amd64, kernel 4.15). But it fails at the end of the process (linking) with this output :

[ 98%] Building CXX object tools/llvm-lto/CMakeFiles/llvm-lto.dir/llvm-lto.cpp.o
[ 98%] Building CXX object tools/lto/CMakeFiles/LTO.dir/lto.cpp.o
[100%] Linking CXX executable ../../../../bin/mlir-opt
/usr/bin/ld : can't find -lLLVMNVPTXCodeGen
/usr/bin/ld : can't find -lLLVMNVPTXDesc
/usr/bin/ld : can't find -lLLVMNVPTXInfo
clang: error: linker command failed with exit code 1 (use -v to see invocation)
tools/mlir/tools/mlir-opt/CMakeFiles/mlir-opt.dir/build.make:228: recipe for target 'bin/mlir-opt' failed
make[2]: *** [bin/mlir-opt] Error 1

Do you know this issue ?

Regards,

Hugo

**Comment by stephenneuendorffer** [comment]
Hi Hugo,

This should be fixed yesterday (f80c6d8dec). Or you can work around it by enabling the NVPTX target.

Steve

**Comment by qaco** [comment]
Thank you very much !

**Comment by nunoplopes** [comment]
Closing, bug was fixed already.
