### ISSUE TITLE
__int128_t multiply with -fsanitize=undefined fails to link (undefined reference to __muloti4)

### ISSUE THREAD

**Issue by 460e50c4-8816-4069-87ec-587b183296d4** [llvm/llvm-project#16778]
|  |  |
| --- | --- |
| Bugzilla Link | [16404](https://llvm.org/bz16404) |
| Resolution | FIXED |
| Resolved on | Nov 02, 2021 13:20 |
| Version | 3.3 |
| OS | Windows NT |
| CC | @apolukhin,@dbabokin,@brooksmoses,@topperc,@echristo,@zmodem,@mmatrosov,@nickdesaulniers,@rengolin,@zygoloid,@rogerorr,@Shachar,@stephenhines |

## Extended Description 
clang fails to link code which does a multiply of two int128_t variables on x86_64 if the code is compiled with -fsanitize=undefined : it fails with "undefined reference to '__muloti4'. The same code compiles OK if the -fsanitize argument is omitted:
```
cam-vm-266:precise:qemu$ cat /tmp/zz9.c
__int128_t a;
int main (void) {
  a = a * a;
  return 0;
}
cam-vm-266:precise:qemu$ clang /tmp/zz9.c -o /tmp/zz9
cam-vm-266:precise:qemu$ clang /tmp/zz9.c -fsanitize=undefined -o /tmp/zz9
/tmp/zz9-eAeaq5.o: In function `main':
/tmp/zz9.c:(.text+0x3b): undefined reference to `__muloti4'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
cam-vm-266:precise:qemu$ clang --version
clang version 3.3 (tags/RELEASE_33/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```
(I'm using the prebuilt clang binaries on Ubuntu 12.04:
http://llvm.org/releases/3.3/clang+llvm-3.3-amd64-Ubuntu-12.04.2.tar.gz)

**Comment by rengolin** [comment]
This is far from "fixed": https://reviews.llvm.org/D141836

I created a proposal to address this here: https://discourse.llvm.org/t/proposal-split-built-ins-from-the-rest-of-compiler-rt/67978

**Comment by jcelerier** [comment]
This is still a problem with clang-19

**Comment by jcelerier** [comment]
In my case it's on aarch64 (fedora 41/Asahi Linux) - happens when trying to build Qt with ubsan.

**Comment by nikic** [comment]
Yeah, it looks like the libcalls is still emitted on aarch64. For reference, here's how the change to disable this looks like (for ppc): c1a31ee65b3a2bf2b452febb99703b3fdfa43328
