### ISSUE TITLE
libclang.so in Ubuntu x86 3.3 download package is an x86_64 binary

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16789]
|  |  |
| --- | --- |
| Bugzilla Link | [16415](https://llvm.org/bz16415) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Repro steps:

$ wget http://llvm.org/releases/3.3/clang+llvm-3.3-Ubuntu-13.04-x86-linux-gnu.tar.bz2
$ tar -xjf clang+llvm-3.3-Ubuntu-13.04-x86-linux-gnu.tar.bz2
$ file clang+llvm-3.3-Ubuntu-13.04-x86-linux-gnu/lib/libclang.so
clang+llvm-3.3-Ubuntu-13.04-x86-linux-gnu/lib/libclang.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0x6c03df905dc2dbeccec20acc69616de5901843a4, not stripped

Obviously, this makes it impossible to load the .so on an x86 Linux machine and defeats the purpose of the pre-built binary package.

**Comment by arsenm** [comment]
Old release issue
