### ISSUE TITLE
Bitcode file which crashes opt

### ISSUE THREAD

**Issue by 021de1a4-aab3-4b45-ada0-9b4a8d155441** [llvm/llvm-project#16806]
|  |  |
| --- | --- |
| Bugzilla Link | [16432](https://llvm.org/bz16432) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [Test case exposing problem](https://user-images.githubusercontent.com/92601859/143747659-6d77dd3a-d2ce-485f-92fc-600f4a205452.gz) |

## Extended Description 

I have compiled LLVM 3.3, checked out from:

http://llvm.org/svn/llvm-project/llvm/tags/RELEASE_33/final

and compiled with Visual Studio 10 in Debug mode, under Windows 7.

Running opt on the attached bitcode file causes opt to crash, printing the following:

0x01235862 (0x00000001 0x00D68C38 0x00D68F08 0x00C1FADC)
0x014D885C (0x00000000 0x00D68C38 0x00F18C98 0x0122CF3B)
0x0122CC11 (0x00000001 0x01A1D84C 0x00000001 0x00000000)
0x01128064 (0x00000002 0x00F11B20 0x00F12170 0xE69D83C3)
0x017AFF44 (0x7EFDE000 0x00C1FD34 0x779B9EF2 0x7EFDE000), ??0_Mutex@std@@QAE@W4_
Uninitialized@1@@Z() + 0x2EE bytes(s)
0x774033AA (0x7EFDE000 0x761149A7 0x00000000 0x00000000), BaseThreadInitThunk()
+ 0x12 bytes(s)
0x779B9EF2 (0x017B0065 0x7EFDE000 0x00000000 0x00000000), RtlInitializeException
Chain() + 0x63 bytes(s)
0x779B9EC5 (0x017B0065 0x7EFDE000 0x00000000 0x00000000), RtlInitializeException
Chain() + 0x36 bytes(s)

Any advice on what's wrong here would be appreciated.

**Comment by arsenm** [comment]
Unclear exactly how you're running this to see a crash but the common tool invocations crash on this now
