### ISSUE TITLE
Terrible error message for missing semicolon defining constructor after class

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#16804]
|  |  |
| --- | --- |
| Bugzilla Link | [16430](https://llvm.org/bz16430) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor,@jryans |

## Extended Description 
class C {
  C();
}
C::C() {}
<stdin>:4:4: error: member 'C' has the same name as its class
C::C() {}
   ^
<stdin>:1:7: error: 'C' can not be defined in the result type of a function
class C {
      ^
<stdin>:4:4: error: constructor cannot have a return type
C::C() {}
   ^
3 errors generated.

**Comment by xgupta** [comment]
Fixed on trunk - https://godbolt.org/z/chP7fre1d.
Present warning - 
<source>:3:2: error: expected ';' after class
}
 ^
 ;
