### ISSUE TITLE
DR1358: if an instantiated constexpr function template doesn't satisfy the constexpr requirements, we should not allow it to be called in a constant expression

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#16822]
|  |  |
| --- | --- |
| Bugzilla Link | [16448](https://llvm.org/bz16448) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Example:
```
struct S { virtual int f(); };
template<typename T> struct X : T {
  constexpr X() {}
  double d = 0.0;
  constexpr int f() { return sizeof(T); }
};
constexpr X<X<S> > xxs;
constexpr const X<S> *p = &xxs;
static_assert(p->f() == sizeof(X<S>), "");
```
Clang accepts this but the static_assert fails, because the call is made non-virtually. Per core issue DR1358, evaluation of a call to a constexpr constructor temploid whose specialization does not obey the constexpr rules is supposed to fail.

**Comment by hubert-reinterpretcast** [comment]
I suppose this is actually implemented, but the implementation of [CWG 1872](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1872) has deteriorated (see #54468).
