### ISSUE TITLE
huge alignment in load instruction

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16840]
|  |  |
| --- | --- |
| Bugzilla Link | [16466](https://llvm.org/bz16466) |
| Version | 3.2 |
| OS | Linux |
| Attachments | [test case](https://user-images.githubusercontent.com/60944935/143747685-8853b38b-2bb2-4d4f-b66f-11c38d51f21f.gz), [generated bitcode](https://user-images.githubusercontent.com/60944935/143747686-b1671c4f-519b-4694-9d48-8acd76db89ce.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Dragonegg creates an align of 32 for simple i32 value:

  %0 = load i32* %p_addr, align 32

Clang sets align to 4.

**Comment by asl** [comment]
Dragonegg is obsolete
