### ISSUE TITLE
Rejects-valid with decltype and exception specification

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#16843]
|  |  |
| --- | --- |
| Bugzilla Link | [16469](https://llvm.org/bz16469) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Testcase:
void f() noexcept;
decltype(f)**g;

<stdin>:2:14: error: exception specifications are not allowed beyond a single level of indirection
decltype(f)**g;
             ^
1 error generated.

This testcase is well-formed, as far as I can tell.

**Comment by xgupta** [comment]
This seems to fix on trunk - https://godbolt.org/z/dxn6zW9Ta. clang also accepts the provided test code.
