### ISSUE TITLE
SAFECode generates failure in wget 1.14, grep 2.14, and nginx 1.2.3

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16869]
|  |  |
| --- | --- |
| Bugzilla Link | [16495](https://llvm.org/bz16495) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
SAFECode generates a failure on a memcpy() for wget 1.14, grep 2.14, and nginx 1.2.3.

**Comment by Endilll** [comment]
SAFECode is archived.
