### ISSUE TITLE
clang: error: unable to execute command: Segmentation fault: 11

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16871]
|  |  |
| --- | --- |
| Bugzilla Link | [16497](https://llvm.org/bz16497) |
| Version | 3.2 |
| OS | MacOS X |
| Attachments | [Preprocessed source + run script](https://user-images.githubusercontent.com/60944935/143747702-b53790ee-8aed-4667-8593-e4ea44733244.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic |

## Extended Description 

Version:

Apple LLVM version 4.2 (clang-425.0.28)

Summary:

While compiling an open source megadrive emulator, picodrive (https://github.com/notaz/picodrive), clang crashed with the error: 

clang: error: unable to execute command: Segmentation fault: 11

Notes:

0  clang 0x0000000100c57bb2 main + 12932498
Stack dump:
0.	Program arguments: /usr/bin/clang -cc1 -triple x86_64-apple-macosx10.8.0 -emit-obj -disable-free -disable-llvm-verifier -main-file-name memory.c -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 136 -g -coverage-file /Users/clobber/Documents/clobber/picodrive/pico/memory.o -resource-dir /usr/bin/../lib/clang/4.2 -D NDEBUG -D EMU_F68K -D _USE_CZ80 -I . -I platform/linux/ -fmodule-cache-path /var/folders/kh/f9qqcqz165d0gbtbg9v43zlh0000gn/T/clang-module-cache -O2 -Wall -fdebug-compilation-dir /Users/clobber/Documents/clobber/picodrive -ferror-limit 19 -fmessage-length 87 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.8.0 -fobjc-dispatch-method=mixed -fobjc-default-synthesize-properties -fdiagnostics-show-option -fcolor-diagnostics -o pico/memory.o -x c pico/memory.c 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'pico/memory.c'.
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)
Target: x86_64-apple-darwin12.4.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/kh/f9qqcqz165d0gbtbg9v43zlh0000gn/T/memory-47tPfX.c
clang: note: diagnostic msg: /var/folders/kh/f9qqcqz165d0gbtbg9v43zlh0000gn/T/memory-47tPfX.sh
clang: note: diagnostic msg: 

********************
make: *** [pico/memory.o] Error 254

**Comment by Endilll** [comment]
Appears to be fixed in Clang 15: https://godbolt.org/z/j86Ta6j69
Reduced by C-Reduce:
```cpp
m68k_write16_map[];
int m68k_map_unmap_start_addr_shift = 6;
static m68k_unmapped_read16();

int m68k_map_unmap_start_addr() {
  int addr;
  int i = m68k_map_unmap_start_addr;
  for (i; i;)
    addr = m68k_unmapped_read16;
  for (; i; i++)
    m68k_write16_map[i] = (addr >> 1) | 0;
}
```
