### ISSUE TITLE
SAFECode does not register memory objects for localtime and gmtime

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#16880]
|  |  |
| --- | --- |
| Bugzilla Link | [16506](https://llvm.org/bz16506) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The localtime() and gmtime() functions return a pointer to a statically allocated memory object.  SAFECode should know the location of this object for run-time checks but does not.

This causes problems when using libLTO which considers localtime() and gmtime() to be recognized functions that it marks complete.

**Comment by Endilll** [comment]
SAFECode is archived.
