### ISSUE TITLE
Regarding compiling clang tools

### ISSUE THREAD

**Issue by norhh** [llvm/llvm-project#169]
I wanted to use LibTooling, so I tried out building clang as mentioned in https://clang.llvm.org/docs/LibASTMatchersTutorial.html . For some reason even with 16GB RAM and a lot of swap space, the build crashes either by segfault or it gets killed(on both Mac and Ubuntu). Is there any way to build it with 16GB RAM?
Does anyone have a docker container for running LibTooling and LibASTMatchers?

**Comment by Lekensteyn** [comment]
How much CPUs do you have? Linking can be very expensive, and ninja by default runs these processes in parallel.

When you build with CMake, try setting a lower number of parallel linker jobs. E.g.
```
cmake -DLLVM_PARALLEL_LINK_JOBS=2
```
This option is documented at https://llvm.org/docs/CMake.html

**Comment by norhh** [comment]
Gave it 8 CPUs in both Mac and Ubuntu.

**Comment by norhh** [comment]
It crashed with 2 parallel jobs or 1 parallel job.

**Comment by androm3da** [comment]
> on both Mac and Ubuntu

You might have better luck using `lld` or `gold` as your linker on Ubuntu.

**Comment by Lekensteyn** [comment]
Can you share your build output? As suggested above, you can also try a more memory-efficient linker with `-DLLVM_USE_LINKER=lld` or `-DLLVM_USE_LINKER=gold`.
