### ISSUE TITLE
Behavior of __has_nothrow_constructor differs from GCC

### ISSUE THREAD

**Issue by apolukhin** [llvm/llvm-project#17001]
|  |  |
| --- | --- |
| Bugzilla Link | [16627](https://llvm.org/bz16627) |
| Version | 3.2 |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Following code works well on GCC-4.6 but fails with clang 3.0 and clang 3.2:

```cpp
#include <cassert>

struct nothrow_def {
    nothrow_def(int i = 0) noexcept {}
};

int main() {
    assert(__has_nothrow_constructor(nothrow_def));
}
```
Without `int i = 0` it work OK.

**Comment by shafik** [comment]
Looks fixed: https://godbolt.org/z/6oPxd6sK5
