### ISSUE TITLE
assertion: Invalid scalar expression to emit in CGExprScalar

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17018]
|  |  |
| --- | --- |
| Bugzilla Link | [16644](https://llvm.org/bz16644) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic |

## Extended Description 
It crashed with the Ubuntu release of llvm/clang so I compiled the trunk instead and got this.

The project is a C program. Unfortunately the source code is proprietary so I cannot paste the include file. Building with debug works but it appears the SROA pass crashes clang. Instructions on how to manually disable this pass would be a helpful workaround.

==========================================================================================

0  clang-3.4       0x0000000001becf94 llvm::sys::PrintStackTrace(_IO_FILE*) + 38
1  clang-3.4       0x0000000001bed21b
2  clang-3.4       0x0000000001becc56
3  libpthread.so.0 0x00007f39796e3bd0
4  clang-3.4       0x0000000000ca7046
5  clang-3.4       0x0000000001ad3f7c llvm::PointerType::get(llvm::Type*, unsigned int) + 28
6  clang-3.4       0x0000000000ed57b9
7  clang-3.4       0x0000000000ed5873
8  clang-3.4       0x0000000000ed574d
9  clang-3.4       0x0000000000efd337
10 clang-3.4       0x0000000002ca01b2
11 clang-3.4       0x0000000002c9d0fc
12 clang-3.4       0x0000000002ca128e
13 clang-3.4       0x0000000002ca1566
14 clang-3.4       0x0000000002c9d343
15 clang-3.4       0x0000000002ca644f
16 clang-3.4       0x0000000002ca37a3
17 clang-3.4       0x0000000002ca0ba5
18 clang-3.4       0x0000000002c9cbb7
19 clang-3.4       0x0000000002c9e41e
20 clang-3.4       0x0000000002c9ed7f
21 clang-3.4       0x0000000001ac109a llvm::FPPassManager::runOnFunction(llvm::Function&) + 382
22 clang-3.4       0x0000000001ac0de4 llvm::FunctionPassManagerImpl::run(llvm::Function&) + 84
23 clang-3.4       0x0000000001ac09e2 llvm::FunctionPassManager::run(llvm::Function&) + 180
24 clang-3.4       0x0000000001c24d2a
25 clang-3.4       0x0000000001c24f00 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::Module*, clang::BackendAction, llvm::raw_ostream*) + 136
26 clang-3.4       0x0000000001c20a9c
27 clang-3.4       0x0000000001f95fbf clang::ParseAST(clang::Sema&, bool, bool) + 785
28 clang-3.4       0x0000000001ea406a clang::ASTFrontendAction::ExecuteAction() + 298
29 clang-3.4       0x0000000001c1fa74 clang::CodeGenAction::ExecuteAction() + 1414
30 clang-3.4       0x0000000001ea3bc0 clang::FrontendAction::Execute() + 200
31 clang-3.4       0x0000000001e7dcf8 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 564
32 clang-3.4       0x0000000001bf1ac5 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 1012
33 clang-3.4       0x0000000000c58f37 cc1_main(char const**, char const**, char const*, void*) + 717
34 clang-3.4       0x0000000000c52fd1 main + 523
35 libc.so.6       0x00007f3978b0fea5 __libc_start_main + 245
36 clang-3.4       0x0000000000c51739
Stack dump:
0.      Program arguments: /usr/local/bin/clang-3.4 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -main-file-name src_lwthreads.i -mrelocation-model static -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -momit-leaf-frame-pointer -g -coverage-file /redacted/src_lwthreads.o -resource-dir /usr/local/bin/../lib/clang/3.4 -O1 -Werror -std=c99 -fdebug-compilation-dir /redacted/oc-init -ferror-limit 19 -fmessage-length 0 -mstackrealign -fobjc-runtime=gcc -fobjc-default-synthesize-properties -fdiagnostics-show-option -vectorize-loops -fcolor-diagnostics -o /redacted/src_lwthreads.o -x cpp-output /redacted/src_lwthreads.i
1.      <eof> parser at end of file
2.      Per-function optimization
3.      Running pass 'SROA' on function '@lwt_sigtkill_thread'
clang-3.4: error: unable to execute command: Segmentation fault (core dumped)
clang-3.4: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.4
Target: x86_64-unknown-linux-gnu
Thread model: posix
clang-3.4: note: diagnostic msg: PLEASE submit a bug report to  and include the crash backtrace, preprocessed source, and associated run script.
clang-3.4: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.

**Comment by Endilll** [comment]
Both reductions appear to be fixed in Clang 3.4:
https://cexplorer.testlabs.pro/z/T5zEc8
https://cexplorer.testlabs.pro/z/dvE7jo

**Comment by Endilll** [comment]
CC @AaronBallman
