### ISSUE TITLE
Rejects-valid with variadic alias template in variadic class template

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#17042]
|  |  |
| --- | --- |
| Bugzilla Link | [16668](https://llvm.org/bz16668) |
| Version | unspecified |
| OS | All |
| Attachments | [Patch for discussion](https://user-images.githubusercontent.com/56606707/143747810-15fa06ba-88a3-493a-8a2a-7317023fefd3.gz) |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Testcase:

template<int ...Args1> struct A {
    template<int ...Args2> using B = A<(Args1+Args2)...>;
};
template<int ...Args> using X = A<1,2,3>::B<Args...>;

Currently prints:
<stdin>:2:53: error: pack expansion contains parameter pack 'Args2' that has a different length (3 vs. 1) from outer parameter packs
    template<int ...Args2> using B = A<(Args1+Args2)...>;
                                              ~~~~~ ^
<stdin>:4:43: note: in instantiation of template type alias 'B' requested here
template<int ...Args> using X = A<1,2,3>::B<Args...>;
                                          ^
1 error generated.

I don't see any obvious reason why this wouldn't be allowed by the standard.

**Comment by Endilll** [comment]
Nothing has changed as of Clang 16: https://godbolt.org/z/86YzhKjb6

**Comment by vient** [comment]
Since https://github.com/llvm/llvm-project/issues/61415 seems to be duplicate, this is affecting c++23 builds with libstdc++-13.

**Comment by vient** [comment]
My previous example seems to be fixed in trunk: https://godbolt.org/z/eMfYsEbo1
