### ISSUE TITLE
Warning 'pragma once in main file' doesn't print its command line option

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17041]
|  |  |
| --- | --- |
| Bugzilla Link | [16667](https://llvm.org/bz16667) |
| Version | 3.2 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @jryans,@zygoloid |

## Extended Description 
What it prints now:

test.cpp:1:9: warning: #pragma once in main file
#pragma once
        ^
1 warning generated.

What it should print:

test.cpp:1:9: warning: #pragma once in main file [-Wpragma-once-in-main-file]
#pragma once
        ^
1 warning generated.

**Comment by AaronBallman** [comment]
Closing as this issue no longer reproduces for me.
