### ISSUE TITLE
disable flag for - 'warning: #pragma once in main file'

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17060]
|  |  |
| --- | --- |
| Bugzilla Link | [16686](https://llvm.org/bz16686) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic,@rnk |

## Extended Description 
We're using clang to generate reflection data from only header files. It would be excellent if we could disable this warning.

*path_to_file*:10:9: warning: #pragma once in main file
#pragma once
        ^

**Comment by philnik777** [comment]
`-Wpragma-once-outside-header` was added in Clang 3.8: https://godbolt.org/z/4h4Gjq73b
