### ISSUE TITLE
Difference in treating with __builtin declratations

### ISSUE THREAD

**Issue by kaomoneus** [llvm/llvm-project#17086]
|  |  |
| --- | --- |
| Bugzilla Link | [16712](https://llvm.org/bz16712) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Example:

extern int abs(int __i);
#define	abs(__i) __builtin_abs(__i)

int
abs(int x)
{
  return (x < 0) ? -x : x;
}

Is compiled with gcc, while clang emits error:
abc.c:5:1: error: definition of builtin function '__builtin_abs'
abs(int x)

abc.c:2:18: note: expanded from macro 'abs'
#define abs(__i) __builtin_abs(__i)

**Comment by AaronBallman** [comment]
Clang does not allow you to provide a definition for a builtin function. Closing as invalid, but if there a particular need to be able to do this, please reopen the issue with more details on why.
