### ISSUE TITLE
Error in 'Getting Started: Building and Running Clang'

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17092]
|  |  |
| --- | --- |
| Bugzilla Link | [16718](https://llvm.org/bz16718) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic,@silvasean |

## Extended Description 
http://clang.llvm.org/get_started.html

This section ...

6. Build LLVM and Clang:
- mkdir build (for building without polluting the source dir)
- cd build

... suggests building under a separate directory to avoid polluting the build.
However, it appears as if (at least) clang-tools/clang-format does not build unless the build is started from the root (llvm) directory, because of the relative path specified for Makefile.config in tools/clang/tools/clang-format/Makefile.

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
