### ISSUE TITLE
Build mlir failed in Windows

### ISSUE THREAD

**Issue by jacky82226** [llvm/llvm-project#171]
Here are commands for my mlir build:
```
git clone --config core.autocrlf=false https://github.com/llvm/llvm-project.git
mkdir llvm-project/build && cd llvm-project/build
cmake -G Ninja ../llvm \
   -DLLVM_ENABLE_PROJECTS=mlir \
   -DLLVM_BUILD_EXAMPLES=ON \
   -DLLVM_TARGETS_TO_BUILD="host" \
   -DCMAKE_BUILD_TYPE=Release \
   -DLLVM_ENABLE_ASSERTIONS=ON \
   -DLLVM_ENABLE_RTTI=ON
cmake --build . --target check-mlir
```
However, I bumped into some errors while executing the last command. (cmake --build . --target check-mlir)

> ex1:
> llvm/Support/Mutex.h:29:12: error: 'recursive_mutex' in namespace 'std' does not name a type
> ex2:
> llvm/lib/Support/CrashRecoveryContext.cpp:89:27: error: 'mutex' is not a member of 'std'
> ex3:
> llvm/lib/Support/Chrono.cpp:35:17: error: '::localtime_s' has not been declared; did you mean 'localtime'?

It seems like a version issue, but I do not know the proper version. I am using cmake-3.17.0-rc2-win64-x64, ninja v1.10.0, latest MinGW and latest Windows 10. 

I saw that there are some updates for fixing Windows issue today. I was wondering that is latest repo works well in Windows? How can I fix my errors? 

Thanks!

**Comment by joker-eph** [comment]
Seems like your issues are related to MinGW and the standard library. I don't know enough about MinGW to help you on this.
The windows fix you saw recently were MSVC related, I doubt it would help.

**Comment by jacky82226** [comment]
Good point. I will try visual studio c++ instead. Will report whether it works soon. Thank you for answering!

**Comment by jacky82226** [comment]
> Seems like your issues are related to MinGW and the standard library. I don't know enough about MinGW to help you on this.
> The windows fix you saw recently were MSVC related, I doubt it would help.

Good point. I will try visual studio c++ instead. Will report whether it works soon. Thank you for answering!

**Comment by stellaraccident** [comment]
My team does regularly build and use MLIR on Windows with Visual Studio
2019 (both VC/cl and clang-cl).

If I had to guess (and it is a complete guess), something in your MinGW
setup is not causing an appropriate -std= copt to be passed and it may be
falling back to a pre-c++-11 standard (some of your reported errors are
reminiscent of that sort of mismatch). I've personally found CMake on
windows to be quite fiddly when it comes to configuring it to use different
compilers and there is usually an option or two that needs to be set. I
don't know what that would be in this case.

**Comment by mstorsjo** [comment]
Your issue is most probably that you've got a GCC/MinGW setup that uses win32 threading model, which doesn't support C++11 threads. For native toolchains, there's often separate installs for ones with the pthreads/posix threading model, which do support C++11 threads. For cross toolchains on e.g. debian/ubuntu, both are often available in tandem, where you can call either `x86_64-w64-mingw32-g++-posix` or `x86_64-w64-mingw32-g++-win32` to choose between the two.

**Comment by jacky82226** [comment]
Thank you all for the answering. I kept failing on MinGW so I tried to build it in Visual Studio C++ command line and it seems work. (Pass all test except one Unexpected Failures)
