### ISSUE TITLE
`make install` does not install compiler-rt components

### ISSUE THREAD

**Issue by 70311826-e6d8-4d29-8604-c4ec4bfa7f0d** [llvm/llvm-project#17141]
|  |  |
| --- | --- |
| Bugzilla Link | [16767](https://llvm.org/bz16767) |
| Version | trunk |
| OS | MacOS X |
| CC | @ramosian-glider,@seanm |

## Extended Description 
Below is the recipe I use to build Clang and Compiler-rt gear.

After make install, I found I have been missing the following over time ("over time" because I don't realize they are missing until a later date):

* scan-build
* scan-view
* libclang_rt.asan_osx_dynamic.dylib
* asan_symbolize.py

I suppose the request here is, "please install required components when running `make install`"

~JW

*** Recipe ***
```bash
wget http://llvm.org/releases/3.3/llvm-3.3.src.tar.gz
wget http://llvm.org/releases/3.3/cfe-3.3.src.tar.gz
wget http://llvm.org/releases/3.3/compiler-rt-3.3.src.tar.gz
# wget http://llvm.org/releases/3.3/lldb-3.3.src.tar.gz
tar xvf llvm-3.3.src.tar.gz
cd llvm-3.3.src/tools
tar xvf ../../cfe-3.3.src.tar.gz
mv cfe-3.3.src clang
#vtar xvf ../../lldb-3.3.src.tar.gz
# mv lldb-3.3.src/ lldb
cd ..
cd projects
tar xvf ../../compiler-rt-3.3.src.tar.gz
mv compiler-rt-3.3.src/ compiler-rt
cd ..
./configure --enable-optimized --prefix=/usr/local
make -j4
sudo make install
```

**Comment by Endilll** [comment]
Autotools build has been removed long ago.
