### ISSUE TITLE
[potential accepts-invalid] Dereferencing pointer to incomplete enclosing class in method declaration

### ISSUE THREAD

**Issue by HighCommander4** [llvm/llvm-project#17202]
|  |  |
| --- | --- |
| Bugzilla Link | [16828](https://llvm.org/bz16828) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor |

## Extended Description 
Clang accepts the following code:

```cpp
struct S
{
    int foo();

    struct nested
    {
        S* outer;

        auto bar() -> decltype(outer->foo());
    };
};
```

GCC rejects it, with the following errors:

test.cpp:9:37: error: invalid use of incomplete type ‘struct S’
test.cpp:1:8: error: forward declaration of ‘struct S’

The reason for rejecting it is stated in [1]. If that reasoning is sound, then clang should reject the code as well. If it's not, I'd be curious to hear why.

[1] http://gcc.gnu.org/ml/gcc-patches/2013-08/msg00398.html

**Comment by cor3ntin** [comment]
All compilers seems to accept that. The wording is probably
https://eel.is/c++draft/basic.lookup#class.member.lookup-3
