### ISSUE TITLE
Assertion failed in DwarfCompileUnit.cpp

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17220]
|  |  |
| --- | --- |
| Bugzilla Link | [16846](https://llvm.org/bz16846) |
| Version | trunk |
| OS | Linux |
| Attachments | [command](https://user-images.githubusercontent.com/60944935/143747918-51749c87-e8c2-4296-b465-16a238089612.gz), [source](https://user-images.githubusercontent.com/60944935/143747919-67cf1fb3-2672-4b3c-a524-0b52ecff4c85.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Please find the files that was report when compiling some Objective-C file.
The complete description below:

 Compiling file AMD64/AMD64ABIInfo.mm ...
Assertion failed: (Ty && "Trying to add a type that doesn't exist?"), function addType, file /usr/home/mathieu/llvm/lib/CodeGen/AsmPrinter/DwarfCompileUnit.cpp, line 779.
Stack dump:
0.      Program arguments: /usr/local/bin/clang -cc1 -triple x86_64-unknown-freebsd9.1 -emit-obj -disable-free -main-file-name AMD64ABIInfo.mm -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -relaxed-alia
sing -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -target-linker-version 2.17.50 -g -coverage-file /usr/home/mathieu/Etoile/Languages/LanguageKit/CodeGen/obj/LanguageKitCodeGen.obj/AMD
64/AMD64ABIInfo.mm.o -resource-dir /usr/local/bin/../lib/clang/3.4 -dependency-file obj/LanguageKitCodeGen.obj/AMD64/AMD64ABIInfo.mm.d -MT obj/LanguageKitCodeGen.obj/AMD64/AMD64ABIInfo.mm.o -MP -D GNU_RUNTIME_V
ERSION=1 -D GNU_RUNTIME_VERSION=1 -D LLVM_MAJOR=3 -D LLVM_MINOR=4 -D GNU_RUNTIME_VERSION=1 -D LLVM_MAJOR=3 -D LLVM_MINOR=4 -D GNU_RUNTIME_VERSION=1 -D GNUSTEP -D GNUSTEP_BASE_LIBRARY=1 -D GNU_GUI_LIBRARY=1 -D G
NU_RUNTIME=1 -D GNUSTEP_BASE_LIBRARY=1 -D _NATIVE_OBJC_EXCEPTIONS -D _NONFRAGILE_ABI -D DEBUG -D GSWARN -D GSDIAGNOSE -D _DEBUG -D _GNU_SOURCE -D __STDC_CONSTANT_MACROS -D __STDC_FORMAT_MACROS -D __STDC_LIMIT_M
ACROS -I /usr/local/include -I /usr/home/mathieu/Etoile/Build -I /usr/home/mathieu/Etoile/Languages/LanguageKit -I /usr/home/mathieu/Etoile/Languages/LanguageKit/Headers -I /usr/include/amd64-undermydesk-freebs
d/ -I /usr/home/mathieu/Etoile/Build -I /usr/home/mathieu/Etoile/Languages/LanguageKit/CodeGen -I /usr/home/mathieu/Etoile/Languages/LanguageKit/CodeGen/Headers -I /usr/include/amd64-undermydesk-freebsd/ -I /us
r/home/mathieu/Etoile/Build -I /usr/home/mathieu/Etoile/Languages/LanguageKit/CodeGen -I /usr/home/mathieu/Etoile/Languages/LanguageKit/CodeGen/Headers -I /usr/include/amd64-undermydesk-freebsd/ -I /usr/home/ma
thieu/Etoile/Build -I /usr/home/mathieu/Etoile/Languages/LanguageKit/CodeGen -I /usr/home/mathieu/Etoile/Languages/LanguageKit/CodeGen/Headers -I /usr/include/amd64-undermydesk-freebsd/ -I ./derived_src -I . -I
 /home/mathieu/GNUstep/Library/Headers -I /Local/Library/Headers -I /System/Library/Headers -I /usr/local/include -O2 -Wall -Wno-import -Wno-variadic-macros -Wno-gnu -Wno-pedantic -Woverloaded-virtual -Wcast-qu
al -fdeprecated-macro -fdebug-compilation-dir /usr/home/mathieu/Etoile/Languages/LanguageKit/CodeGen -fconstant-string-class NSConstantString -ferror-limit 19 -fmessage-length 210 -fvisibility-inlines-hidden -p
thread -mstackrealign -fblocks -fno-rtti -fobjc-runtime=gnustep-1.6 -fobjc-dispatch-method=non-legacy -fobjc-default-synthesize-properties -fobjc-arc -fobjc-arc-cxxlib=libstdc++ -fobjc-arc-exceptions -fobjc-exc
eptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o obj/LanguageKitCodeGen.obj/AMD64/AMD64ABIInfo.mm.o -x objective-c++ AMD64/AMD64ABIInfo.mm
1.      <eof> parser at end of file
2.      Code generation
clang: error: unable to execute command: Abort trap: 6 (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.4 (trunk ^/cfe/trunk 187966) (llvm/trunk ^/llvm/trunk 187965)
Target: x86_64-unknown-freebsd9.1
Thread model: posix

**Comment by arsenm** [comment]
Previous comment says works on trunk
