### ISSUE TITLE
chrome build error

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17237]
|  |  |
| --- | --- |
| Bugzilla Link | [16863](https://llvm.org/bz16863) |
| Version | 3.3 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
Error occurred in compiling.

OS:ubuntu 12.04 32bit

ninja: Entering directory `out/Debug'
[8993/13095] ACTION ppapi_ipc_untrusted: build irt x86-64 nlib_4633807c3c7a53656cc4c6dc833cce6d
FAILED: cd ../../ppapi; python ../native_client/build/build_nexe.py -t ../out/Debug/gen/sdk/toolchain/ --arch x86-64 --build newlib_nlib_pnacl --root .. --name ../out/Debug/gen/tc_irt/lib64/libppapi_ipc_untrusted.a --objdir ../out/Debug/obj/ppapi/ppapi_ipc_untrusted.gen/irt-x86-64/ppapi_ipc_untrusted "--include-dirs=../out/Debug/gen/tc_newlib/include .. .. ../third_party/khronos ../gpu" "--compile_flags=--target=x86_64-nacl -O2 -g -Wall -fdiagnostics-show-option -Werror  -gline-tables-only -Wno-unused-function -Wno-char-subscripts -Wno-c++11-extensions -Wno-unnamed-type-template-args -Wno-extra-semi -Wno-unused-private-field -Wno-char-subscripts -Wno-unused-function " "--defines=__linux__ \"__STDC_LIMIT_MACROS=1\" \"__STDC_FORMAT_MACROS=1\" \"_GNU_SOURCE=1\" \"_BSD_SOURCE=1\" \"_POSIX_C_SOURCE=199506\" \"_XOPEN_SOURCE=600\" \"DYNAMIC_ANNOTATIONS_ENABLED=1\" \"DYNAMIC_ANNOTATIONS_PREFIX=NACL_\" \"NACL_BUILD_ARCH=x86\" ANGLE_DX11 \"_FILE_OFFSET_BITS=64\" CHROMIUM_BUILD COMPONENT_BUILD \"USE_DEFAULT_RENDER_THEME=1\" \"USE_LIBJPEG_TURBO=1\" \"USE_NSS=1\" \"USE_X11=1\" ENABLE_ONE_CLICK_SIGNIN \"GTK_DISABLE_SINGLE_INCLUDES=1\" \"ENABLE_REMOTING=1\" \"ENABLE_WEBRTC=1\" ENABLE_PEPPER_CDMS ENABLE_CONFIGURATION_POLICY ENABLE_INPUT_SPEECH ENABLE_NOTIFICATIONS \"ENABLE_GPU=1\" \"ENABLE_EGLIMAGE=1\" \"ENABLE_TASK_MANAGER=1\" \"ENABLE_EXTENSIONS=1\" \"ENABLE_PLUGIN_INSTALLATION=1\" \"ENABLE_PLUGINS=1\" \"ENABLE_SESSION_SERVICE=1\" \"ENABLE_THEMES=1\" \"ENABLE_BACKGROUND=1\" \"ENABLE_AUTOMATION=1\" \"ENABLE_GOOGLE_NOW=1\" \"ENABLE_PRINTING=1\" \"ENABLE_SPELLCHECK=1\" \"ENABLE_CAPTIVE_PORTAL_DETECTION=1\" \"ENABLE_MANAGED_USERS=1\" \"ENABLE_MDNS=1\" __STDC_CONSTANT_MACROS __STDC_FORMAT_MACROS" "--link_flags=--target=x86_64-nacl -B../out/Debug/gen/tc_irt/lib64  " "--source-list=irt-x86-64.ppapi_ipc_untrusted.source_list.gypcmd"
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.3 (http://git.chromium.org/native_client/pnacl-clang.git 3b1ef29c338890ce55a1990389d8e63f6be7da2c) (http://git.chromium.org/native_client/pnacl-llvm.git dad71e1d326ac5fb4e8a3d64262e875ef01cf38d)
Target: x86_64--nacl
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: Error generating preprocessed source(s).
FAILED with 254: ../out/Debug/gen/sdk/toolchain/linux_x86_pnacl/newlib/bin/pnacl-clang++ -c proxy/ppapi_messages.cc -o ../out/Debug/obj/ppapi/ppapi_ipc_untrusted.gen/irt-x86-64/ppapi_ipc_untrusted/ppapi_messages.o -MD -MF ../out/Debug/obj/ppapi/ppapi_ipc_untrusted.gen/irt-x86-64/ppapi_ipc_untrusted/ppapi_messages.o.d --target=x86_64-nacl -O2 -g -Wall -fdiagnostics-show-option -Werror -gline-tables-only -Wno-unused-function -Wno-char-subscripts -Wno-c++11-extensions -Wno-unnamed-type-template-args -Wno-extra-semi -Wno-unused-private-field -Wno-char-subscripts -Wno-unused-function -D__linux__ -D__STDC_LIMIT_MACROS=1 -D__STDC_FORMAT_MACROS=1 -D_GNU_SOURCE=1 -D_BSD_SOURCE=1 -D_POSIX_C_SOURCE=199506 -D_XOPEN_SOURCE=600 -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DDYNAMIC_ANNOTATIONS_PREFIX=NACL_ -DNACL_BUILD_ARCH=x86 -DANGLE_DX11 -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_NSS=1 -DUSE_X11=1 -DENABLE_ONE_CLICK_SIGNIN -DGTK_DISABLE_SINGLE_INCLUDES=1 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_INPUT_SPEECH -DENABLE_NOTIFICATIONS -DENABLE_GPU=1 -DENABLE_EGLIMAGE=1 -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_BACKGROUND=1 -DENABLE_AUTOMATION=1 -DENABLE_GOOGLE_NOW=1 -DENABLE_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNACL_WINDOWS=0 -DNACL_OSX=0 -DNACL_LINUX=0 -I../out/Debug/gen/tc_newlib/include -I.. -I.. -I../third_party/khronos -I../gpu
[8993/13095] ACTION ppapi_ipc_untrusted: build IRT x86-32 nlib_4633807c3c7a53656cc4c6dc833cce6d
ninja: build stopped: subcommand failed.

**Comment by Endilll** [comment]
Author never got back to us with preprocessed source.
