### ISSUE TITLE
OCaml bindings for Alias Analysis in LLVM?

### ISSUE THREAD

**Issue by taquangtrung** [llvm/llvm-project#173]
Hi,

I'd like to ask whether OCaml bindings of LLVM support querying alias information of variables?

I want to use functions similar to `isNoAlias`, `isMayAlias`, `isMustAlias`, provided in [`llvm::AAResults`](https://llvm.org/doxygen/classllvm_1_1AAResults.html)

However, I am unable to find such functions in the OCaml bindings of LLVM.
Does anybody know how to do it?

Thank you very much!

**Comment by jyknight** [comment]
Nope, the C bindings (and by implication the ocaml bindings) don't get into the sorts of inner parts of LLVM such as retrieving analysis pass results. The bindings are intended for more high-level operations like creating IR and writing it or dynamically loading it. That sort of thing.
