### ISSUE TITLE
__attribute__((noreturn)) merged in an if-expression "?:"

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17356]
|  |  |
| --- | --- |
| Bugzilla Link | [16982](https://llvm.org/bz16982) |
| Version | 3.3 |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
In the following code, if the parameter `err' is zero, the functions will return.

good(0) returns fine, but bad(0) doesn't, the thread returns from dontexit() into garbage memory.

```c++
void exit(int) __attribute__((noreturn));
void dontexit(int);

int good(int err)
{
	if(err)
		exit(0);
	else
		dontexit(0);
}

int bad(int err)
{
	(err ? exit : dontexit)(0);
}
```

It looks like the types "void (int)" and "void (int) __attribute__((noreturn))" are being merged into "void (int)" for the ?: expression, and so clang assumes "(err ? exit : dontexit)(0)" doesn't return.

This happens on both -O0, -Os and -O3.

Possibly related to #&#8203;10347.

**Comment by philnik777** [comment]
Fixed in Clang 4: https://godbolt.org/z/dhzoj7rE4
