### ISSUE TITLE
error: conflicting types for '__clear_cache'

### ISSUE THREAD

**Issue by eschnett** [llvm/llvm-project#17381]
|  |  |
| --- | --- |
| Bugzilla Link | [17007](https://llvm.org/bz17007) |
| Version | trunk |
| OS | Linux |

## Extended Description 
LLVM trunk (Revision: 189279) does not build for me on a Raspberry Pi with Raspbian. I configure with

../llvm/configure '--build=armv6-unknown-linux-gnueabihf' '--with-cpu=arm1176jzf-s' '--with-float=hard' '--with-abi=aapcs-vfp' '--enable-targets=arm' '--enable-optimized' '--enable-assertions' '--enable-shared' '--prefix=/home/pi/llvm'

and then build with

make

and then receive the error message

make[1]: Entering directory `/home/pi/eschnetter-titan/water/llvm-build/lib/Support'
llvm[1]: Compiling Memory.cpp for Release+Asserts build
In file included from /home/pi/eschnetter-titan/water/llvm/lib/Support/Memory.cpp:21:
/home/pi/eschnetter-titan/water/llvm/lib/Support/Unix/Memory.inc:38:17: error: 
      conflicting types for '__clear_cache'
extern "C" void __clear_cache(void *, void*);
                ^
/home/pi/eschnetter-titan/water/llvm/lib/Support/Unix/Memory.inc:38:17: note: 
      '__clear_cache' is a builtin with type 'void ()'
1 error generated.
make[1]: *** [/home/pi/eschnetter-titan/water/llvm-build/lib/Support/Release+Asserts/Memory.o] Error 1
make[1]: Leaving directory `/home/pi/eschnetter-titan/water/llvm-build/lib/Support'
make: *** [all] Error 1

I am using gcc 4.6.1 (Debian 4.6.3-14+rpi1) for building.

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
