### ISSUE TITLE
Fail to compile clang

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17384]
|  |  |
| --- | --- |
| Bugzilla Link | [17010](https://llvm.org/bz17010) |
| Version | 3.3 |
| OS | Linux |
| Attachments | [required by bug report](https://user-images.githubusercontent.com/60944935/143747990-aa4e9d8f-b24e-4deb-94fd-0254b82c8d7d.gz), [the .sh file](https://user-images.githubusercontent.com/60944935/143747991-ce81c3da-7132-4622-a232-a7e646d0f13d.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic |

## Extended Description 

0  clang           0x00000000021d3432 llvm::sys::PrintStackTrace(_IO_FILE*) + 34
1  clang           0x00000000021d3089
2  libpthread.so.0 0x0000003dc580eb10
3  clang           0x0000000001e0c565
4  clang           0x0000000001e0896b
5  clang           0x0000000001e092ba
6  clang           0x0000000001e0a597
7  clang           0x0000000002168a17 llvm::MPPassManager::runOnModule(llvm::Module&) + 663
8  clang           0x0000000002168bd7 llvm::PassManagerImpl::run(llvm::Module&) + 231
9  clang           0x00000000009636c2 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::Module*, clang::BackendAction, llvm::raw_ostream*) + 3458
10 clang           0x000000000096133f
11 clang           0x0000000000ad02e2 clang::ParseAST(clang::Sema&, bool, bool) + 514
12 clang           0x00000000009602fe clang::CodeGenAction::ExecuteAction() + 78
13 clang           0x00000000007dcbd9 clang::FrontendAction::Execute() + 265
14 clang           0x00000000007bd4f5 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 341
15 clang           0x00000000007a48c2 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 1794
16 clang           0x000000000079dca8 cc1_main(char const**, char const**, char const*, void*) + 1176
17 clang           0x000000000078abc0 main + 4992
18 libc.so.6       0x0000003dc4c1d994 __libc_start_main + 244
19 clang           0x000000000079cb31
Stack dump:
0.      Program arguments: /sbclocal/DSA/home/libil/local/build/Release+Asserts/bin/clang -cc1 -triple i386-unknown-linux-gnu -emit-obj -disable-free -main-file-name asan_rtl.cc -mrelocation-model pic -pic-level 2 -pie-level 2 -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu pentium4 -target-linker-version 2.17.50.0.6 -momit-leaf-frame-pointer -coverage-file /sbclocal/DSA/home/libil/local/build/tools/clang/runtime/compiler-rt/clang_linux/asan-i386/i386/SubDir.lib__asan/asan_rtl.o -resource-dir /sbclocal/DSA/home/libil/local/build/Release+Asserts/bin/../lib/clang/3.3 -D ASAN_FLEXIBLE_MAPPING_AND_OFFSET=1 -I /sbclocal/DSA/home/libil/local/download/llvm-3.3.src/projects/compiler-rt/lib -I /sbclocal/DSA/home/libil/local/download/llvm-3.3.src/projects/compiler-rt/include -internal-isystem /sbcimp/run/pd/gcc/64-bit/4.7.3/lib/gcc/x86_64-linux-gnu/4.7.3/../../../../include/c++/4.7.3 -internal-isystem /sbcimp/run/pd/gcc/64-bit/4.7.3/lib/gcc/x86_64-linux-gnu/4.7.3/../../../../include/c++/4.7.3/x86_64-linux-gnu/32 -internal-isystem /sbcimp/run/pd/gcc/64-bit/4.7.3/lib/gcc/x86_64-linux-gnu/4.7.3/../../../../include/c++/4.7.3/backward -internal-isystem /sbcimp/run/pd/gcc/64-bit/4.7.3/lib/gcc/x86_64-linux-gnu/4.7.3/../../../../include/x86_64-linux-gnu/c++/4.7.3/32 -internal-isystem /usr/local/include -internal-isystem /sbclocal/DSA/home/libil/local/build/Release+Asserts/bin/../lib/clang/3.3/include -internal-externc-isystem /sbcimp/run/pd/gcc/64-bit/4.7.3/include/c++/4.7.3 -internal-externc-isystem /sbcimp/run/pd/gcc/64-bit/4.7.3/include/c++/4.7.3/x86_64-linux-gnu -internal-externc-isystem /usr/include -O3 -Wall -Werror -fdeprecated-macro -fdebug-compilation-dir /sbclocal/DSA/home/libil/local/download/llvm-3.3.src/projects/compiler-rt -ferror-limit 19 -fmessage-length 160 -mstackrealign -fno-builtin -fno-rtti -fobjc-runtime=gcc -fobjc-default-synthesize-properties -fdiagnostics-show-option -fcolor-diagnostics -backend-option -vectorize-loops -o /sbclocal/DSA/home/libil/local/build/tools/clang/runtime/compiler-rt/clang_linux/asan-i386/i386/SubDir.lib__asan/asan_rtl.o -x c++ /sbclocal/DSA/home/libil/local/download/llvm-3.3.src/projects/compiler-rt/lib/asan/asan_rtl.cc
1.      <eof> parser at end of file
2.      Per-module optimization passes
3.      Running pass 'Interprocedural Sparse Conditional Constant Propagation' on module '/sbclocal/DSA/home/libil/local/download/llvm-3.3.src/projects/compiler-rt/lib/asan/asan_rtl.cc'.
clang: error: unable to execute command: Illegal instruction
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.3 (tags/RELEASE_33/final)
Target: i386-unknown-linux-gnu
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
  COMPILE:   clang_linux/asan-i386/i386: /sbclocal/DSA/home/libil/local/download/llvm-3.3.src/projects/compiler-rt/lib/asan/asan_thread.cc
  COMPILE:   clang_linux/asan-i386/i386: /sbclocal/DSA/home/libil/local/download/llvm-3.3.src/projects/compiler-rt/lib/asan/asan_win.cc
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/asan_rtl-Wcw8CY.cpp
clang: note: diagnostic msg: /tmp/asan_rtl-Wcw8CY.sh
clang: note: diagnostic msg:

********************
  COMPILE:   clang_linux/asan-i386/i386: /sbclocal/DSA/home/libil/local/download/llvm-3.3.src/projects/compiler-rt/lib/int_util.c
make[5]: *** [/sbclocal/DSA/home/libil/local/build/tools/clang/runtime/compiler-rt/clang_linux/asan-i386/i386/SubDir.lib__asan/asan_rtl.o] Error 254
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory `/sbclocal/DSA/home/libil/local/download/llvm-3.3.src/projects/compiler-rt'
make[4]: *** [BuildRuntimeLibraries] Error 2
rm /sbclocal/DSA/home/libil/local/build/Release+Asserts/lib/clang/3.3/lib/linux/.dir
make[4]: Leaving directory `/sbclocal/DSA/home/libil/local/build/tools/clang/runtime/compiler-rt'
make[3]: *** [compiler-rt/.makeall] Error 2
make[3]: Leaving directory `/sbclocal/DSA/home/libil/local/build/tools/clang/runtime'
make[2]: *** [all] Error 1
make[2]: Leaving directory `/sbclocal/DSA/home/libil/local/build/tools/clang'
make[1]: *** [clang/.makeall] Error 2
make[1]: Leaving directory `/sbclocal/DSA/home/libil/local/build/tools'
make: *** [all] Error 1

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.3 and 3.4 with assertions enabled.
