### ISSUE TITLE
NightlyTester should draw confidence bands for longterm results

### ISSUE THREAD

**Issue by asl** [llvm/llvm-project#1739]
|  |  |
| --- | --- |
| Bugzilla Link | [1367](https://llvm.org/bz1367) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Some tests shows highly unstable results from run to run. It will be nice to
have some sane confidence borders.

**Comment by gwelymernans** [comment]
@asl, is this a concern? I'm thinking it's not. Please file a new bug if so.
