### ISSUE TITLE
[ASan] Turn use-after-return checking on by default

### ISSUE THREAD

**Issue by chandlerc** [llvm/llvm-project#17438]
|  |  |
| --- | --- |
| Bugzilla Link | [17064](https://llvm.org/bz17064) |
| Version | unspecified |
| OS | All |
| CC | @kcc,@LebedevRI |

## Extended Description 
Filing this as a tracking bug to track progress on turning ASan's use-after-return checking on by default.

The reason I want this on by default is that there is very little to indicate to a user that a bug in their code is related to use-after-return, and so it seems especially valuable to eagerly diagnose it. Also, it seems likely that by applying LLVM's capture analysis to the instrumentation the overhead associated with this mode could be significantly reduced.

**Comment by vitalybuka** [comment]
Fixed with 4b4437c084e2b8a2643e97e7aef125c438635a4d
