### ISSUE TITLE
InitAlloca for LLVM 3.3 hits memset assertion

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17560]
|  |  |
| --- | --- |
| Bugzilla Link | [17186](https://llvm.org/bz17186) |
| Version | unspecified |
| OS | All |
| Attachments | [Test case provided by Joshua Cranmer](https://user-images.githubusercontent.com/60944935/143748071-36b4abed-00c7-4763-baab-1a8f157726a9.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

The new version of SAFECode for LLVM 3.3 hits an assertion in the InitAllocas pass.  The problem appears to be that the doInitialization() method adds the memset() function into the program which is to be used later by methods called by runOnFunction().  However, LLVM optimizations run before InitAllocas remove the memset() function declaration, causing InitAllocas to hit the assertion.

This bug was found by Joshua Cranmer and can be reproduced using the following command on the attached test case:

clang -O1 -std=c++11 -fmemsafety initalloca.cpp  -c

**Comment by Endilll** [comment]
Can't reproduce using assertion builds of Clang 3.3 and 3.4: https://cexplorer.testlabs.pro/z/75oe8E
