### ISSUE TITLE
llvm: $LDFLAGS is used with both build and host compiler (should only be for host compiler)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17573]
|  |  |
| --- | --- |
| Bugzilla Link | [17199](https://llvm.org/bz17199) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
In the llvm/configure

echo "$as_me: error: no acceptable cc found in \$PATH" >&2;}
   { (exit 1); exit 1; }; }
  ac_build_link='${BUILD_CC-cc} -o conftest $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
  rm -f conftest*
  echo 'int main () { return 0; }' > conftest.$ac_ext
  ac_cv_build_exeext=
  if { (eval echo "$as_me:$LINENO: \"$ac_build_link\"") >&5
  (eval $ac_build_link) 2>&5
  ac_status=$?
  echo "$as_me:$LINENO: \$? = $ac_status" >&5
  (exit $ac_status); }; then
    for file in conftest.*; do
      case $file in
      *.c | *.o | *.obj | *.dSYM) ;;
      *) ac_cv_build_exeext=`echo $file | sed -e s/conftest//` ;;
      esac
    done
  else
    { { echo "$as_me:$LINENO: error: installation or configuration problem: compiler cannot create executables." >&5

The build compiler uses $CFLAGS $CPPFLAGS $LDFLAGS for target compiler. If some flags are target compiler only, then configure error happens.

**Comment by arsenm** [comment]
Old autotools build
