### ISSUE TITLE
Incorrect -Woverloaded-virtual when parent overload is private.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17592]
|  |  |
| --- | --- |
| Bugzilla Link | [17218](https://llvm.org/bz17218) |
| Version | 3.2 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Using the following compiler:
Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)

To compile the following code:

template <typename Type>
class A {
    virtual void func(Type) {}
};

class B : A<int>, A<double> {
    virtual void func(int);
};

Using the following command line:
clang -Wall -c test.cpp

Generates the following warning:
clang_hides_overload.cpp:7:15: warning: 'B::func' hides overloaded virtual function [-Woverloaded-virtual]
        virtual void func(int);
                     ^
clang_hides_overload.cpp:3:15: note: hidden overloaded virtual function 'A<double>::func' declared here
        virtual void func(Type) {}
                     ^
1 warning generated.

I believe this is not true since the base method 'A<double>::func' is private and thus was never available to B anyway.

**Comment by AaronBallman** [comment]
GCC and EDG have the same behavior as Clang, and I think this behavior is defensible because it means we don't have to hunt around in the base class hierarchy for a friend declaration to see if it provides access to the private function. Closing this as working by design.
