### ISSUE TITLE
not everybody has endian.h

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17617]
|  |  |
| --- | --- |
| Bugzilla Link | [17243](https://llvm.org/bz17243) |
| Version | unspecified |
| OS | Windows XP |
| Attachments | [patch to check for endian.h](https://user-images.githubusercontent.com/60944935/143748092-c6fa5e7c-82c4-4c0b-8998-57a20f9fea50.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @Theodor,@thielema,@silvasean |

## Extended Description 

While trying to build LLVM on Solaris, I ran into the following:

+ gmake
llvm[0]: Constructing LLVMBuild project information.
gmake[1]: Entering directory `/builds/jacobs/f/lib/Support'
llvm[1]: Compiling APFloat.cpp for Release build
In file included from /builds/jacobs/f/include/llvm/ADT/Hashing.h:50:0,
                 from APFloat.cpp:18:
/builds/jacobs/f/include/llvm/Support/Host.h:23:28: fatal error: machine/endian.h: No such file or directory
compilation terminated.
rm: /builds/jacobs/f/lib/Support/Release/APFloat.d.tmp: No such file or directory
gmake[1]: *** [/builds/jacobs/f/lib/Support/Release/APFloat.o] Error 1
gmake[1]: Leaving directory `/builds/jacobs/f/lib/Support'
gmake: *** [all] Error 1

This is because Solaris doesn't have an endian.h to include.  The closest it has is sys/isa_defs.h.  To work around this, I updated configure.ac include checks for endian.h, machine/endian.h, and sys/isa_defs.h.  Then I updated Host.h to use the corresponding HAVE_* macros to determine which header to include.  When sys/isa_defs.h is included, the missing macros are added too.

**Comment by philnik777** [comment]
This is now conditionally included in `ADT/bit.h`
