### ISSUE TITLE
[dragonegg] non-local gotos not supported

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#1763]
|  |  |
| --- | --- |
| Bugzilla Link | [1391](https://llvm.org/bz1391) |
| Version | trunk |
| OS | All |

## Extended Description 
This is needed for full nested function support.  Here is a testcase:

main()
{
  __label__ l;

  void*x()
  {
    goto l;
  }

  x();
  abort();
  return;
l:
  exit(0);
}

**Comment by asl** [comment]
Dragonegg is obsolete
