### ISSUE TITLE
The annotate button in viewvc doesn't work

### ISSUE THREAD

**Issue by 991901f3-cc14-4404-b340-165691b62a58** [llvm/llvm-project#17630]
|  |  |
| --- | --- |
| Bugzilla Link | [17256](https://llvm.org/bz17256) |
| Version | unspecified |
| OS | All |
| CC | @dwblaikie |

## Extended Description 
consider the following url:
http://llvm.org/viewvc/llvm-project/llvm/trunk/CREDITS.TXT?annotate=188568

notice the error raised:
Error occurred while calculating annotation data

It would be really swell if this worked :)

**Comment by xgupta** [comment]
viewvc server on llvm.org is shutdown.
