### ISSUE TITLE
Self-host error on FreeBSD/i386 (PHI node has multiple entries for the same basic block with different incoming values!)

### ISSUE THREAD

**Issue by pwo** [llvm/llvm-project#17640]
|  |  |
| --- | --- |
| Bugzilla Link | [17266](https://llvm.org/bz17266) |
| Version | trunk |
| OS | FreeBSD |
| Attachments | [ARMAsmBackend-9b1b59.cpp](https://user-images.githubusercontent.com/92601275/143748119-013cda2b-b2b3-420c-a299-ff3afdb18d84.gz), [ARMAsmBackend-9b1b59.sh](https://user-images.githubusercontent.com/92601275/143748121-e24635b1-f25f-4fe1-96df-26731714904c.gz) |

## Extended Description 
This has been happening for quite some time.

llvm/clang r190855 dies on the stage two build, the fist state is built with clang 3.3. This only happens on FreeBSD/i386, amd64 does not have this issue.

llvm[4]: Compiling ARMAsmBackend.cpp for Release+Asserts build
PHI node has multiple entries for the same basic block with different incoming values!
  %retval.0 = phi i32 [ %conv376, %if.then367 ], [ %conv378, %if.end377 ], [ %conv340, %if.end330 ], [ %conv313, %sw.bb309 ], [ %conv308, %sw.bb304 ], [ %or303, %sw.bb294 ], [ %conv293, %sw.bb289 ], [ %or288, %sw.bb243 ], [ %or242, %sw.bb207 ], [ %conv206, %sw.bb180 ], [ %or178525, %sw.bb124 ], [ %conv123, %sw.bb119 ], [ %or117526, %sw.bb88 ], [ %or87, %_ZN4llvm6ARM_AML11getSOImmValEj.exit ], [ %conv65, %sw.bb61 ], [ %conv58, %if.then51 ], [ %conv60, %if.end59 ], [ %or35, %sw.bb11 ], [ %or, %sw.bb2 ], [ %4, %entry ], [ %5, %entry ], [ %6, %entry ]
label %entry
  %5 = extractelement <2 x i32> %3, i32 0
  %4 = extractelement <2 x i32> %3, i32 0
Broken module found, compilation aborted!
Stack dump:
0.	Program arguments: /data/buildslave/freebsd-clang-i386/obj/llvm.1/Release+Asserts/bin/clang -cc1 -triple i386-unknown-freebsd9.2 -emit-obj -disable-free -main-file-name ARMAsmBackend.cpp -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -masm-verbose -mconstructor-aliases -target-cpu i486 -target-linker-version 2.17.50 -coverage-file /data/buildslave/freebsd-clang-i386/obj/llvm/lib/Target/ARM/MCTargetDesc/Release+Asserts/ARMAsmBackend.o -resource-dir /data/buildslave/freebsd-clang-i386/obj/llvm.1/Release+Asserts/bin/../lib/clang/3.4 -dependency-file /data/buildslave/freebsd-clang-i386/obj/llvm/lib/Target/ARM/MCTargetDesc/Release+Asserts/ARMAsmBackend.d.tmp -MP -MT /data/buildslave/freebsd-clang-i386/obj/llvm/lib/Target/ARM/MCTargetDesc/Release+Asserts/ARMAsmBackend.o -MT /data/buildslave/freebsd-clang-i386/obj/llvm/lib/Target/ARM/MCTargetDesc/Release+Asserts/ARMAsmBackend.d -D _DEBUG -D _GNU_SOURCE -D __STDC_CONSTANT_MACROS -D __STDC_FORMAT_MACROS -D __STDC_LIMIT_MACROS -I /data/buildslave/freebsd-clang-i386/obj/llvm/lib/Target/ARM/MCTargetDesc/.. -I /data/buildslave/freebsd-clang-i386/src-llvm/lib/Target/ARM/MCTargetDesc/.. -I /data/buildslave/freebsd-clang-i386/obj/llvm/include -I /data/buildslave/freebsd-clang-i386/obj/llvm/lib/Target/ARM/MCTargetDesc -I /data/buildslave/freebsd-clang-i386/src-llvm/include -I /data/buildslave/freebsd-clang-i386/src-llvm/lib/Target/ARM/MCTargetDesc -stdlib=libc++ -O2 -Woverloaded-virtual -Wcast-qual -Wno-long-long -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcovered-switch-default -Wno-uninitialized -Wno-missing-field-initializers -pedantic -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /data/buildslave/freebsd-clang-i386/obj/llvm/lib/Target/ARM/MCTargetDesc -ferror-limit 19 -fmessage-length 0 -fvisibility-inlines-hidden -mstackrealign -fno-rtti -fobjc-runtime=gnustep -fobjc-default-synthesize-properties -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o /data/buildslave/freebsd-clang-i386/obj/llvm/lib/Target/ARM/MCTargetDesc/Release+Asserts/ARMAsmBackend.o -x c++ /data/buildslave/freebsd-clang-i386/src-llvm/lib/Target/ARM/MCTargetDesc/ARMAsmBackend.cpp 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/data/buildslave/freebsd-clang-i386/src-llvm/lib/Target/ARM/MCTargetDesc/ARMAsmBackend.cpp'.
4.	Running pass 'Module Verifier' on function '@_ZL16adjustFixupValueRKN4llvm7MCFixupEyPNS_9MCContextE'
clang: error: unable to execute command: Abort trap: 6 (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.4 (trunk 190855)
Target: i386-unknown-freebsd9.2
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/ARMAsmBackend-9b1b59.cpp
clang: note: diagnostic msg: /tmp/ARMAsmBackend-9b1b59.sh
clang: note: diagnostic msg: 

********************

**Comment by Endilll** [comment]
Can't reproduce using assertion builds of Clang 3.3 and 3.4.
