### ISSUE TITLE
*** glibc detected *** clang double free or corruption

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17671]
|  |  |
| --- | --- |
| Bugzilla Link | [17297](https://llvm.org/bz17297) |
| Version | trunk |
| OS | Linux |
| Attachments | [reproduction files](https://user-images.githubusercontent.com/60944935/143748141-313286df-92ff-461e-8d20-8441b59ea2ce.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Revision: 190763 .. head as of a couple days ago. Attached are all files used to reproduce

*** glibc detected *** /path/bin/clang: double free or corruption (out): 0x0000000004318920 ***
======= Backtrace: =========
/lib64/libc.so.6[0x2aaaac82776e]
/lib64/libc.so.6(__libc_free+0x6c)[0x2aaaac828ebc]
/path/bin/clang(_ZN4llvm13LiveVariables20runOnMachineFunctionERNS_15MachineFunctionE+0x1363)[0x29ffc13]
/path/bin/clang(_ZN4llvm19MachineFunctionPass13runOnFunctionERNS_8FunctionE+0x61)[0x2a26f31]
/path/bin/clang(_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE+0x1c0)[0x304d830]
/path/bin/clang(_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE+0x49)[0x304d629]
/path/bin/clang(_ZN4llvm13MPPassManager11runOnModuleERNS_6ModuleE+0x1d6)[0x3051036]
/path/bin/clang(_ZN4llvm15PassManagerImpl3runERNS_6ModuleE+0xc0)[0x3050de0]

This was discovered when attempting to compile pypy with clang.

**Comment by philnik777** [comment]
The reproducer still depends on system headers, so closing as missing reproducer.
