### ISSUE TITLE
LLVM Tests fail on i386-pc-nto-qnx6.5.0 due to non-standard expectations of UNIX commands

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17701]
|  |  |
| --- | --- |
| Bugzilla Link | [17327](https://llvm.org/bz17327) |
| Version | trunk |
| OS | other |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic |

## Extended Description 
QNX Neutrino 6.5.0 is a POSIX-compliant 32-bit operating system. I am porting LLVM to this system and have run into test failures that can be fixed with simple changes to the tests.

The following tests failed because they were using the non-standard ">& /dev/null" instead of "> /dev/null 2>&1": (See http://llvm.org/bugs/show_bug.cgi?id=9698)

test/Analysis/BasicAA/unreachable-block.ll
test/Assembler/2003-11-11-ImplicitRename.ll
test/Assembler/2007-11-26-AttributeOverload.ll
test/CodeGen/X86/GC/badreadproto.ll
test/CodeGen/X86/GC/badrootproto.ll
test/CodeGen/X86/GC/badwriteproto.ll
test/CodeGen/X86/GC/fat.ll
test/CodeGen/X86/GC/outside.ll
test/Other/2002-01-31-CallGraph.ll
test/Transforms/GCOVProfiling/linkagename.ll
test/Transforms/LoopStrengthReduce/pr2570.ll
test/Verifier/2004-05-21-SwitchConstantMismatch.ll
test/Verifier/2007-12-21-InvokeParamAttrs.ll
test/Verifier/2008-01-11-VarargAttrs.ll
test/Verifier/2009-05-29-InvokeResult1.ll
test/Verifier/2009-05-29-InvokeResult2.ll
test/Verifier/2009-05-29-InvokeResult3.ll
test/Verifier/byval-1.ll
test/Verifier/gcread-ptrptr.ll
test/Verifier/gcroot-alloca.ll
test/Verifier/gcroot-meta.ll
test/Verifier/gcroot-ptrptr.ll
test/Verifier/gcwrite-ptrptr.ll
test/TableGen/UnterminatedComment.td

The following test uses grep "", instead of grep ".*"
test/TableGen/lisp.td

The following test attempts to do a grep on a file without newlines.
test/Transforms/GCOVProfiling/linkagename.ll
(Note: for this test, it should echo the contents of the .gcno file to a temporary file (which will add the newline) and then grep the temporary file)

**Comment by arsenm** [comment]
Old build failure, tests are mostly not using grep anymore
