### ISSUE TITLE
Option to format code with braces indented

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17764]
|  |  |
| --- | --- |
| Bugzilla Link | [17390](https://llvm.org/bz17390) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mydeveloperday |

## Extended Description 
The Visual Studio 2012 IDE has a setting for this in Tools > Options > Text Editor > C/C++ > Formatting > Indentation > Indent Braces

To clang-format, add an option to have braces indented when a brace is on its own line (for example when BreakBeforeBraces is Allman). 

Example:
Input of clang-format:
-----------
```
void foo()
{
  if (something) {
    dothat();
}
else if (somethingelse)
{
  dothis();
} else { domore(); }
dorest();
}
```

-----------

Output would be:
-----------

```
void foo()
  {
  if (something)
    {
    dothat();
    }
  else if (somethingelse)
    {
    dothis();
    }
  else
    {
    domore();
    }
  dorest();
  }
```
-----------

**Comment by mydeveloperday** [comment]
We have support for Whitesmiths style, please verify if this resolves your issue, but feel free to reopen this issue if it doesn't
