### ISSUE TITLE
null pointer reference in Parser::ParseMicrosoftAsmStatement

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17774]
|  |  |
| --- | --- |
| Bugzilla Link | [17400](https://llvm.org/bz17400) |
| Version | trunk |
| OS | All |
| Attachments | [fix](https://user-images.githubusercontent.com/60944935/143748198-53a6fb5e-cc13-449c-a115-19f5eb561505.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic |

## Extended Description 

In

lib/Parse/ParseStmt.cpp

StmtResult Parser::ParseMicrosoftAsmStatement(SourceLocation AsmLoc)
...
const llvm::Target *TheTarget = llvm::TargetRegistry::lookupTarget(TT, Error);

TheTarget is never checked against null pointer.

See attached patch file.

**Comment by JOE1994** [comment]
Clang trunk has a null-pointer check on the value returned by `llvm::TargetRegistry::lookupTarget`.

https://github.com/llvm/llvm-project/blob/b46f980454d5ceafc8dab37dbdb1011e333ae6de/clang/lib/Parse/ParseStmtAsm.cpp#L540-L542
