### ISSUE TITLE
 about project site http://llvm.org/docs/

### ISSUE THREAD

**Issue by ghost** [llvm/llvm-project#178]
I went to llvm project site from Google and it led to http://llvm.org

there are sudden redirects on http://llvm.org/docs/ to some other link, found when going to http://llvm.org/docs/GettingStartedTutorials.html. tried again, it redirected to a link, and then it finally went to <removed>
is this site safe to use?

**Comment by m23retyer** [comment]
sorry, if its not the right place to post.

thanks, Raj

**Comment by tstellar** [comment]
Hi, I'm not sure why you are seeing that, but it looked like an unsafe link, so I removed it from your comment.

**Comment by ret23** [comment]
thank you for edit.

similar stuff happened for another http site, got redirected to something else thanks to "https everywhere" extension.

seems https://llvm.org/docs/ does exist and works without redirects. wonder why https version does not open by default? to me, seems firefox doesn't care about security, as another extension is required. I assume the llvm site is setup securely. 

didn't find any more unwanted redirect on https://llvm.org/docs/. 
though now I have to worry about the extension.

sincerely
Raj
