### ISSUE TITLE
GetSVN.cmake is run even when nothing changed

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17803]
|  |  |
| --- | --- |
| Bugzilla Link | [17429](https://llvm.org/bz17429) |
| Version | trunk |
| OS | Linux |
| Attachments | [hack patch](https://user-images.githubusercontent.com/60944935/143748225-5ca7c101-dd53-44e8-bd37-b8be5a1721c2.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

This is really annoying in a development environment since cmake is *much* slower than ninja figuring out it has nothing to do.

On my machine "ninja bin/clang" takes 0m2.377s when there is nothing to do.

With the hack patch attached that just disables the version information the same command takes 0m0.207s.

**Comment by arsenm** [comment]
svn is no more
