### ISSUE TITLE
more missing builtins ... builtin_finitef, isfinite and others

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17828]
|  |  |
| --- | --- |
| Bugzilla Link | [17454](https://llvm.org/bz17454) |
| Version | 3.2 |
| OS | Linux |
| Attachments | [gcc test](https://user-images.githubusercontent.com/60944935/143748243-a9a2e053-10fc-43d3-9e29-af4b21bc43fe.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@echristo |

## Extended Description 

rkotler@mipssw006:~/rt-rk-4doug/tmp$  ~/llvmw/install/bin/clang ../tests-c/pr28796-2.c -std=gnu89 -lm -O2
In file included from ../tests-c/pr28796-2.c:6:
../tests-c/tg-tests.h:35:7: error: use of unknown builtin '__builtin_isnanf'
      [-Wimplicit-function-declaration]
  if (__builtin_isnanf (f) != res_isnan)
      ^
../tests-c/tg-tests.h:35:7: note: did you mean '__builtin_isnan'?
../tests-c/tg-tests.h:29:7: note: '__builtin_isnan' declared here
  if (__builtin_isnan (f) != res_isnan)
      ^
../tests-c/tg-tests.h:37:7: error: use of unknown builtin '__builtin_isnanl'
      [-Wimplicit-function-declaration]
  if (__builtin_isnanl (ld) != res_isnan)
      ^
../tests-c/tg-tests.h:46:7: error: use of unknown builtin '__builtin_isinff'
      [-Wimplicit-function-declaration]
  if (__builtin_isinff (f) != res_isinf)
      ^
../tests-c/tg-tests.h:46:7: note: did you mean '__builtin_isinf'?
../tests-c/tg-tests.h:40:7: note: '__builtin_isinf' declared here
  if (__builtin_isinf (f) != res_isinf)
      ^
../tests-c/tg-tests.h:48:7: error: use of unknown builtin '__builtin_isinfl'
      [-Wimplicit-function-declaration]
  if (__builtin_isinfl (ld) != res_isinf)
      ^
../tests-c/tg-tests.h:72:7: error: use of unknown builtin '__builtin_finitef'
      [-Wimplicit-function-declaration]
  if (__builtin_finitef (f) != res_isfin)
      ^
../tests-c/tg-tests.h:72:7: note: did you mean '__builtin_isfinite'?
../tests-c/tg-tests.h:65:7: note: '__builtin_isfinite' declared here
  if (__builtin_isfinite (f) != res_isfin)
      ^
../tests-c/tg-tests.h:74:7: error: use of unknown builtin '__builtin_finite'
      [-Wimplicit-function-declaration]
  if (__builtin_finite (f) != res_isfin)
      ^
../tests-c/tg-tests.h:74:7: note: did you mean '__builtin_finitef'?
../tests-c/tg-tests.h:72:7: note: '__builtin_finitef' declared here
  if (__builtin_finitef (f) != res_isfin)
      ^
../tests-c/tg-tests.h:78:7: error: use of unknown builtin '__builtin_finitel'
      [-Wimplicit-function-declaration]
  if (__builtin_finitel (d) != res_isfin)
      ^
7 errors generated.
rkotler@mipssw006:~/rt-rk-4doug/tmp$

**Comment by arsenm** [comment]
__builtin_isnan, __builtin_isfinite, __builtin_isinf exist and do not require the type suffixes
