### ISSUE TITLE
python bindings `get_tokens` - returns token for one-past-end token

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17849]
|  |  |
| --- | --- |
| Bugzilla Link | [17475](https://llvm.org/bz17475) |
| Version | trunk |
| OS | Linux |
| Attachments | [python bindings test that shows the bug](https://user-images.githubusercontent.com/60944935/143748252-5e1e02c0-8df2-415f-afe1-539744d6498e.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Maybe related to http://llvm.org/bugs/show_bug.cgi?id=9069 #&#8203;9069

I havent tried with the c libclang yet, so i will report this has python bug only.
I could not find the bug in the python code tough. Its probably a libclang or clang Lexer bug.

desc:
```cpp
 int i;
 extern int x;
```
when parsing tokens for cursor on `int i`, you get `['int','i',';']`
```cpp
 #define PLOP 1
 extern int x;
```
when parsing tokens for cursor on `PLOP`, you get `['PLOP','1','extern']`
which is not correct.

**Comment by DeinAlptraum** [comment]
This has been fixed in c7c6a07548172399844e85f0dfb5476525fd07ff. @Endilll can you close this?
