### ISSUE TITLE
llvm-tblgen crashes if compiled with MTd on Win32 VC 2005

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17860]
|  |  |
| --- | --- |
| Bugzilla Link | [17486](https://llvm.org/bz17486) |
| Version | 3.2 |
| OS | Windows NT |
| Attachments | [Patch that fixes the error](https://user-images.githubusercontent.com/60944935/143748253-19733f82-d367-4d61-bc2d-5422278aaec9.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

llvm-tblgen triggers a debug exception (and thus crash) if compiled with MTd (static link debug runtime) on Win32 with VS2005, as a 32b executable.

It is caused by CodeGenInstruction.cpp line 411 , where Selection.split('|').first is null. Attempting to append this to a std::string triggers a debug check.

The attached change avoids the append if the above value is null.

NOTE: Tested on LLVM 3.3, but there's no 3.3 in the version list.

**Comment by Endilll** [comment]
I wonder if VS 2005 was supported even 10 years ago, putting aside how ancient it is today.
