### ISSUE TITLE
Without late-vectorize, clang can run forever and uses ridiculous amounts of memory

### ISSUE THREAD

**Issue by DimitryAndric** [llvm/llvm-project#17899]
|  |  |
| --- | --- |
| Bugzilla Link | [17525](https://llvm.org/bz17525) |
| Version | trunk |
| OS | All |
| Attachments | [Testcase for ns_core memory exhaustion problem](https://user-images.githubusercontent.com/9060368/143748275-80ae9086-8ae0-4b0f-80a3-f70a4d6c0c3d.gz), [Test case for bug 17525, reduced a little bit more](https://user-images.githubusercontent.com/9060368/143748276-86903c6b-2a19-425c-8f22-8d0602c01891.gz) |
| CC | @hfinkel,@jsonn,@rengolin |

## Extended Description 

I recently received a sample source file from a FreeBSD user, who observed clang running forever, until all memory was exhausted and the process was killed, while compiling a Mozilla WebRTC source file.  This occurred with clang 3.3 release on the i386 arch, and *only* when compiling with -march=pentium3.

With more recent trunk versions I could not reproduce the problem, so I did some bisecting, and the revision that 'fixed' it turned out to be r189858 ("Enable late-vectorization by default").  However, this just changes the default setting for late-vectorize, and when you turn it off, the problem can still be reproduced with trunk r192062.

I reduced the sample to the attached testcase, which should be compiled with the following flags:

clang -O3 -m32 -march=pentium3 -mllvm -late-vectorize=false -c

This makes clang run forever and eats up all RAM, until it crashes.  Other -march= settings do not exhibit this problem, e.g. pentium2, pentium4, core2, etc all compile it quickly as expected, and use very little RAM.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.5: https://godbolt.org/z/64dbMsqKs
