### ISSUE TITLE
Assertion `RegNo < NumRegs && "Attempting to access record for invalid register number!"' failed.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17893]
|  |  |
| --- | --- |
| Bugzilla Link | [17519](https://llvm.org/bz17519) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @maleadt |

## Extended Description 
As of r192159 NVPTX backend crashes on a reduced test case:

$ llc --version
LLVM (http://llvm.org/):
  LLVM version 3.4svn
  DEBUG build with assertions.
  Built Oct  9 2013 (00:05:24).
  Default target: x86_64-unknown-linux-gnu
  Host CPU: core-avx-i

  Registered Targets:
    nvptx   - NVIDIA PTX 32-bit
    nvptx64 - NVIDIA PTX 64-bit
    x86     - 32-bit X86: Pentium-Pro and above
    x86-64  - 64-bit X86: EM64T and AMD64

$ opt bugpoint-reduced-simplified.bc -S -o -
; ModuleID = 'bugpoint-reduced-simplified.bc'
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v32:32:32-v64:64:64-v128:128:128-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

; Function Attrs: nounwind
define ptx_device void @&#8203;kernelgen_memcpy() #&#8203;0 {
entry:
  br i1 undef, label %for.end, label %vector.body

vector.body:                                      ; preds = %vector.body, %entry
  br label %vector.body

for.end:                                          ; preds = %entry
  ret void
}

attributes #&#8203;0 = { nounwind "less-precise-fpmad"="false" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-realign-stack" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }

$ kernelgen-llc bugpoint-reduced-simplified.bc
kernelgen-llc: /home/marcusmae/rpmbuild/BUILD/llvm/build/include/llvm/MC/MCRegisterInfo.h:316: const llvm::MCRegisterDesc& llvm::MCRegisterInfo::operator[](unsigned int) const: Assertion `RegNo < NumRegs && "Attempting to access record for invalid register number!"' failed.
0  libLLVM-3.4svn.so 0x00007f9627ecc199 llvm::sys::PrintStackTrace(_IO_FILE*) + 38
1  libLLVM-3.4svn.so 0x00007f9627ecc416
2  libLLVM-3.4svn.so 0x00007f9627ecbe75
3  libpthread.so.0   0x00007f96267c5cb0
4  libc.so.6         0x00007f9625afe425 gsignal + 53
5  libc.so.6         0x00007f9625b01b8b abort + 379
6  libc.so.6         0x00007f9625af70ee
7  libc.so.6         0x00007f9625af7192
8  libLLVM-3.4svn.so 0x00007f96274d5714
9  libLLVM-3.4svn.so 0x00007f96274d5752
10 libLLVM-3.4svn.so 0x00007f96274d577d
11 libLLVM-3.4svn.so 0x00007f96274ccf0f
12 libLLVM-3.4svn.so 0x00007f96274cdefc llvm::AsmPrinter::EmitFunctionBody() + 1110
13 libLLVM-3.4svn.so 0x00007f96274d4dff
14 libLLVM-3.4svn.so 0x00007f962765fbd9 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) + 95
15 libLLVM-3.4svn.so 0x00007f96278cd3fe llvm::FPPassManager::runOnFunction(llvm::Function&) + 290
16 libLLVM-3.4svn.so 0x00007f96278cd56e llvm::FPPassManager::runOnModule(llvm::Module&) + 84
17 libLLVM-3.4svn.so 0x00007f96278cd8c2 llvm::MPPassManager::runOnModule(llvm::Module&) + 556
18 libLLVM-3.4svn.so 0x00007f96278cdeb8 llvm::PassManagerImpl::run(llvm::Module&) + 244
19 libLLVM-3.4svn.so 0x00007f96278ce0c3 llvm::PassManager::run(llvm::Module&) + 39
20 kernelgen-llc     0x000000000040ee98
21 kernelgen-llc     0x000000000040df77 main + 237
22 libc.so.6         0x00007f9625ae976d __libc_start_main + 237
23 kernelgen-llc     0x000000000040d899
Stack dump:
0.	Program arguments: kernelgen-llc bugpoint-reduced-simplified.bc 
1.	Running pass 'Function Pass Manager' on module 'bugpoint-reduced-simplified.bc'.
2.	Running pass 'NVPTX Assembly Printer' on function '@kernelgen_memcpy'
Aborted (core dumped)

**Comment by xgupta** [comment]
Seems it is fixed, no assertion today :)
