### ISSUE TITLE
Build scripts assume availability of GNU tools (grep, tr, sed, etc)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17901]
|  |  |
| --- | --- |
| Bugzilla Link | [17527](https://llvm.org/bz17527) |
| Version | 3.2 |
| OS | Solaris |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The configure scripts outright use `grep`, `tr`, and a number of other tools under the assumption they accept more modern parameters for the GNU equivalent of those tools.

For example, when checking the linker version it attempts to execute `grep -q` as part of the check, which fails because it isn't a valid option for sun's `grep` command.

To name a few I've noticed that are used outright instead of through a variable (after finding the 'right' one to use):

grep
tr
sed
head
awk

There's probably others, but I wasn't being entirely thorough.

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
