### ISSUE TITLE
Wrong constant folding

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17945]
|  |  |
| --- | --- |
| Bugzilla Link | [17571](https://llvm.org/bz17571) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
LLVM + clang (trunk) for ARM miscompiles the following code with
optimization level -O1.

```console
  $ clang -target arm-linux-gnueabi -I /usr/arm-linux-gnueabi/include
-mthumb -c error.c -o error.o -O1
  $ arm-linux-gnueabi-gcc error.o -o error.out
  $ qemu-arm -L /usr/arm-linux-gnueabi/ ./error.out
  @&#8203;NG@ t = 4294967296

  $ clang -v
  clang version 3.4 (http://llvm.org/git/clang.git
890a1baadf4bd4c0ef0e8cd9ba30ecdea48d75a6)
(http://llvm.org/git/llvm.git
4fc2774b438c6c09f487362e53d5ac1a84edea73)
  Target: x86_64-unknown-linux-gnu
  Thread model: posix
```

```c
#include <stdio.h>

int main (void)
{
  volatile int x = 1;
  long long t = ( x & 2147483648LL ) << 1;
  if (t != 0LL) { printf("@NG@ t = %lld\n", t); }
  return 0;
}
```

**Comment by philnik777** [comment]
I can't see anything wrong with the code and the bug doesn't actually say what the problem is supposed to be, so I'm closing this. Since the version is trunk this might never have gotten into a release.
