### ISSUE TITLE
Perl and python dependencies

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17982]
|  |  |
| --- | --- |
| Bugzilla Link | [17608](https://llvm.org/bz17608) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @isanbard |

## Extended Description 
http://llvm.org/docs/GettingStarted.html
This page states dependencies on python >= 2.4 (only for test suite) and perl.
But configure requires python >= 2.5 as mandatory, and it seems that perl is not used at all.

**Comment by arsenm** [comment]
Ancient build directions
