### ISSUE TITLE
Unhandled builtin type kind, UNREACHABLE executed at ASTContext.cpp:4637

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18025]
|  |  |
| --- | --- |
| Bugzilla Link | [17651](https://llvm.org/bz17651) |
| Version | 3.2 |
| OS | MacOS X |
| Attachments | [Run script](https://user-images.githubusercontent.com/60944935/143748326-684723e8-7cd8-4f47-8d3a-1b7abc9b504d.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @d0k |

## Extended Description 
I encounter the following error message while building Firefox:

21:44.27 Unhandled builtin type kind
21:44.27 UNREACHABLE executed at ASTContext.cpp:4637!
21:44.28 0  libLLVM-3.2svn.dylib 0x0000000108ef85e2 _ZL15PrintStackTracePv + 34
21:44.28 1  libLLVM-3.2svn.dylib 0x0000000108ef8ac9 _ZL13SignalHandleri + 649
21:44.28 2  libsystem_c.dylib    0x00007fff91589cfa _sigtramp + 26
21:44.28 3  clang                0x0000000107c70a06 clang::MemberExpr::getLocStart() const + 70
21:44.28 4  libLLVM-3.2svn.dylib 0x0000000108ef8826 abort + 22
21:44.28 5  libLLVM-3.2svn.dylib 0x0000000108ee50b4 llvm::llvm_unreachable_internal(char const*, char const*, unsigned int) + 468
21:44.28 6  clang                0x0000000107beb2b5 _ZL28ObjCEncodingForPrimitiveKindPKN5clang10ASTContextENS_8QualTypeE + 101
21:44.28 7  clang                0x0000000107be858a clang::ASTContext::getObjCEncodingForTypeImpl(clang::QualType, std::string&, bool, bool, clang::FieldDecl const*, bool, bool, bool, bool, bool) const + 202
21:44.28 8  clang                0x0000000107bea0fc clang::ASTContext::getObjCEncodingForTypeImpl(clang::QualType, std::string&, bool, bool, clang::FieldDecl const*, bool, bool, bool, bool, bool) const + 7228
21:44.28 9  clang                0x0000000107bebb62 clang::ASTContext::getObjCEncodingForStructureImpl(clang::RecordDecl*, std::string&, clang::FieldDecl const*, bool) const + 2002
21:44.28 10 clang                0x0000000107bebbfc clang::ASTContext::getObjCEncodingForStructureImpl(clang::RecordDecl*, std::string&, clang::FieldDecl const*, bool) const + 2156
21:44.28 11 clang                0x0000000107be94d9 clang::ASTContext::getObjCEncodingForTypeImpl(clang::QualType, std::string&, bool, bool, clang::FieldDecl const*, bool, bool, bool, bool, bool) const + 4121
21:44.28 12 clang                0x0000000107bebb62 clang::ASTContext::getObjCEncodingForStructureImpl(clang::RecordDecl*, std::string&, clang::FieldDecl const*, bool) const + 2002
21:44.29 13 clang                0x0000000107bebbfc clang::ASTContext::getObjCEncodingForStructureImpl(clang::RecordDecl*, std::string&, clang::FieldDecl const*, bool) const + 2156
21:44.29 14 clang                0x0000000107be94d9 clang::ASTContext::getObjCEncodingForTypeImpl(clang::QualType, std::string&, bool, bool, clang::FieldDecl const*, bool, bool, bool, bool, bool) const + 4121
21:44.29 15 clang                0x0000000107bea0fc clang::ASTContext::getObjCEncodingForTypeImpl(clang::QualType, std::string&, bool, bool, clang::FieldDecl const*, bool, bool, bool, bool, bool) const + 7228
21:44.29 16 clang                0x0000000107bea757 clang::ASTContext::getObjCEncodingForMethodDecl(clang::ObjCMethodDecl const*, std::string&, bool) const + 567
21:44.29 17 clang                0x00000001074f7541 (anonymous namespace)::CGObjCCommonMac::GetMethodVarType(clang::ObjCMethodDecl const*, bool) + 65
21:44.29 18 clang                0x00000001074f7484 (anonymous namespace)::CGObjCNonFragileABIMac::GetMethodDescriptionConstant(clang::ObjCMethodDecl const*) + 132
21:44.29 19 clang                0x00000001074f631c (anonymous namespace)::CGObjCNonFragileABIMac::GetOrEmitProtocol(clang::ObjCProtocolDecl const*) + 860
21:44.29 20 clang                0x00000001074f7a8d (anonymous namespace)::CGObjCNonFragileABIMac::EmitProtocolList(llvm::Twine, clang::ObjCProtocolDecl* const*, clang::ObjCProtocolDecl* const*) + 445
21:44.29 21 clang                0x00000001074fdf16 (anonymous namespace)::CGObjCNonFragileABIMac::BuildClassRoTInitializer(unsigned int, unsigned int, unsigned int, clang::ObjCImplementationDecl const*) + 2422
21:44.29 22 clang                0x00000001074f2a42 (anonymous namespace)::CGObjCNonFragileABIMac::GenerateClass(clang::ObjCImplementationDecl const*) + 1378
21:44.29 23 clang                0x000000010753605b clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) + 555
21:44.29 24 clang                0x000000010755253f (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) + 127
21:44.29 25 clang                0x0000000107525c6a clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) + 170
21:44.30 26 clang                0x000000010755e083 clang::ParseAST(clang::Sema&, bool, bool) + 323
21:44.30 27 clang                0x000000010752500b clang::CodeGenAction::ExecuteAction() + 1259
21:44.30 28 clang                0x00000001073320fb clang::FrontendAction::Execute() + 107
21:44.30 29 clang                0x00000001073127ff clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 991
21:44.30 30 clang                0x00000001072db99a clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 3322
21:44.30 31 clang                0x00000001072d291d cc1_main(char const**, char const**, char const*, void*) + 5533
21:44.30 32 clang                0x00000001072d7b67 main + 663
21:44.30 33 clang                0x00000001072d1374 start + 52
21:44.30 Stack dump:
21:44.31 0.	Program arguments: /opt/local/libexec/llvm-3.2/bin/clang -cc1 -triple x86_64-apple-macosx10.6.0 -emit-obj -mrelax-all -disable-free -main-file-name nsChildView.mm -pic-level 2 -mdisable-fp-elim -relaxed-aliasing -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 128.2 -g -coverage-file /Users/david/.ccache/2/a/2e8125889f182a639574f94eef6a76-7933361.o.tmp.Niels.local.44304 -resource-dir /opt/local/libexec/llvm-3.2/bin/../lib/clang/3.2 -include ../../mozilla-config.h -D MOZILLA_INTERNAL_API -D IMPL_LIBXUL -D STATIC_EXPORTABLE_JS_API -D NO_NSPR_10_SUPPORT -D NO_X11 -D MOZILLA_CLIENT -D NO_X11 -D DEBUG -D _DEBUG -D TRACING -I /Users/david/Documents/Code/mc-osfile/widget/cocoa/../xpwidgets -I /Users/david/Documents/Code/mc-osfile/widget/cocoa/../shared -I /Users/david/Documents/Code/mc-osfile/layout/forms -I /Users/david/Documents/Code/mc-osfile/layout/generic -I /Users/david/Documents/Code/mc-osfile/layout/xul/base/src -I /Users/david/Documents/Code/mc-osfile/widget/cocoa -I . -I ../../dist/include -I /Users/david/Documents/Code/mc-osfile/obj-x86_64-apple-darwin11.4.2/dist/include/nspr -I /Users/david/Documents/Code/mc-osfile/obj-x86_64-apple-darwin11.4.2/dist/include/nss -fmodule-cache-path /var/folders/8r/0dk4wrtj5s9dzk37d7hgy27m0000gn/T/clang-module-cache -Wall -Wpointer-arith -Woverloaded-virtual -Werror=return-type -Wtype-limits -Wempty-body -Wsign-compare -Wno-invalid-offsetof -Wno-c++0x-extensions -Wno-extended-offsetof -Wno-unknown-warning-option -Wno-return-type-c-linkage -Wno-mismatched-tags -Wno-error=uninitialized -Wno-error=deprecated-declarations -std=gnu++0x -fdeprecated-macro -fdebug-compilation-dir /Users/david/Documents/Code/mc-osfile/obj-x86_64-apple-darwin11.4.2/widget/cocoa -ferror-limit 19 -fmessage-length 0 -fvisibility hidden -pthread -stack-protector 1 -mstackrealign -fblocks -fno-rtti -fobjc-runtime=macosx-10.6.0 -fobjc-dispatch-method=mixed -fobjc-default-synthesize-properties -fobjc-exceptions -fexceptions -fdiagnostics-show-option -o /Users/david/.ccache/2/a/2e8125889f182a639574f94eef6a76-7933361.o.tmp.Niels.local.44304 -x objective-c++ /Users/david/Documents/Code/mc-osfile/widget/cocoa/nsChildView.mm
21:44.31 1.	/Users/david/Documents/Code/mc-osfile/widget/cocoa/nsChildView.mm:6152:1: current parser token 'void'
21:44.31 2.	/Users/david/Documents/Code/mc-osfile/widget/cocoa/nsChildView.mm:2718:15: LLVM IR generation of declaration 'globalDragPboard'
21:44.33 clang: error: unable to execute command: Illegal instruction: 4
21:44.33 clang: error: clang frontend command failed due to signal (use -v to see invocation)
21:44.33 clang version 3.2 (trunk 162304)
21:44.33 Target: x86_64-apple-darwin11.4.2
21:44.33 Thread model: posix
21:44.33 clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
21:44.33 clang: note: diagnostic msg:
21:44.33 ********************
21:44.33
21:44.34 PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
21:44.34 Preprocessed source(s) and associated run script(s) are located at:
21:44.34 clang: note: diagnostic msg: /var/folders/8r/0dk4wrtj5s9dzk37d7hgy27m0000gn/T/nsChildView-sdb8vm.mm
21:44.34 clang: note: diagnostic msg: /var/folders/8r/0dk4wrtj5s9dzk37d7hgy27m0000gn/T/nsChildView-sdb8vm.sh
21:44.34 clang: note: diagnostic msg:
21:44.34
21:44.34 ********************

**Comment by AaronBallman** [comment]
This does not appear to be reproducible any longer, so closing as works for me.
