### ISSUE TITLE
C11 _Generic keyword could be formatted nicer

### ISSUE THREAD

**Issue by 991901f3-cc14-4404-b340-165691b62a58** [llvm/llvm-project#18080]
|  |  |
| --- | --- |
| Bugzilla Link | [17706](https://llvm.org/bz17706) |
| Version | trunk |
| OS | All |
| CC | @anatol,@compnerd,@EdSchouten |

## Extended Description 
consider a typical use of _Generic:

```
_Static_assert(_Generic((__INT64_TYPE__)0, signed long: 1, default: 0),
               "int64_t should be signed long");
```

The formatter will change this to:

```
_Static_assert(_Generic((__INT64_TYPE__)0, signed long : 1, default : 0),
               "int64_t should be signed long");
```

I believe that there should be no space between the type-name and the colon seeing as how _Generic is basically "switch on types".

**Comment by g-berthiaume** [comment]
+1 for `_Generic` formating.
This issue has been mentioned here: https://github.com/travisjeffery/ClangFormat-Xcode/issues/131
