### ISSUE TITLE
Poolalloc does not compile on Linux

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18108]
|  |  |
| --- | --- |
| Bugzilla Link | [17734](https://llvm.org/bz17734) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Poolalloc fails to compile on Linux platform. The function 'GetNodesReachableFromGlobals' is not used, because the only call to it in 'PoolAllocate::FindFunctionPoolArgs' has been placed inside "#if 0". Also the static variables 'check_interval' and 'rss_max_allowable' are only used in context which are inside "#if defined(__APPLE__)". Since llvm is compiled with '-Wunused-functions -Wunused-variable -Werror' it stops here. Here is the patch which allowed me to compile:

Index: tools/WatchDog/WatchDog.cpp
===================================================================
--- tools/WatchDog/WatchDog.cpp	(revision 193678)
+++ tools/WatchDog/WatchDog.cpp	(working copy)
@@ -34,12 +34,14 @@
 // handler.
 static int pid_to_watch = 0;
 
+#if defined(__APPLE__)
 // Number of seconds to wait before checking up on the child process
 static const unsigned check_interval = 10;
 
 // Maximum amount for the resident set size in kilobytes (i.e., how much
 // physical memory is in use).
 static const int rss_max_allowable = 4 * 1024 * 1024;
+#endif
 
 //
 // Function: create_process()
Index: lib/PoolAllocate/PoolAllocate.cpp
===================================================================
--- lib/PoolAllocate/PoolAllocate.cpp	(revision 193678)
+++ lib/PoolAllocate/PoolAllocate.cpp	(working copy)
@@ -599,6 +599,7 @@
 //                     DSNodes reachable from globals.  DSNodes are *added* to
 //                     this container; it is not cleared by this function.
 //                     DSNodes from both the local and globals graph are added.
+#if 0
 static inline void
 GetNodesReachableFromGlobals (DSGraph* G,
                               DenseSet<const DSNode*> &NodesFromGlobals) {
@@ -649,6 +650,7 @@
     }
   }
 }
+#endif
 
 //
 // Method: FindPoolArgs()

**Comment by arsenm** [comment]
Old build issue and referenced file no longer exists
