### ISSUE TITLE
Safecode Trunk crashes

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18111]
|  |  |
| --- | --- |
| Bugzilla Link | [17737](https://llvm.org/bz17737) |
| Version | unspecified |
| OS | Linux |
| Attachments | [The compilation unit](https://user-images.githubusercontent.com/60944935/143748370-f4ac4d53-c2fe-4084-88bb-69602ab035ca.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

When I compile the attached file I get the following crash. I used the trunk of Safecode compiled on top of LLVM 3.3 release.

0  clang           0x0000000001a8c8e5 llvm::sys::PrintStackTrace(_IO_FILE*) + 37
1  clang           0x0000000001a8cd13
2  libpthread.so.0 0x00007f48d3124f60
3  clang           0x0000000001a2b797
4  clang           0x0000000001a1ef49 llvm::CallInst::init(llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&) + 153
5  clang           0x00000000010d3872
6  clang           0x00000000010e3dde
7  clang           0x00000000010e3a5f
8  clang           0x0000000001a3a2e6 llvm::MPPassManager::runOnModule(llvm::Module&) + 406
9  clang           0x0000000001a3ac30 llvm::PassManagerImpl::run(llvm::Module&) + 480
10 clang           0x0000000000806c60 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::Module*, clang::BackendAction, llvm::raw_ostream*) + 9376
11 clang           0x0000000000803d4c
12 clang           0x000000000090fd23 clang::ParseAST(clang::Sema&, bool, bool) + 515
13 clang           0x0000000000803396 clang::CodeGenAction::ExecuteAction() + 390
14 clang           0x00000000006bf3a1 clang::FrontendAction::Execute() + 81
15 clang           0x00000000006a15dd clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 797
16 clang           0x000000000068c9c6 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 2806
17 clang           0x0000000000684cc3 cc1_main(char const**, char const**, char const*, void*) + 659
18 clang           0x000000000068b0ec main + 9052
19 libc.so.6       0x00007f48d201dc4d __libc_start_main + 253
20 clang           0x0000000000684969
Stack dump:
0.	Program arguments: /usr/lib/llvm-3.3/safecode/bin/clang -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name func.c -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -relaxed-aliasing -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu core2 -target-linker-version 2.20.1 -g -coverage-file func.o -resource-dir /usr/lib/llvm-3.3/safecode/bin/../lib/clang/3.3 -dependency-file func.d -MT func.o -MP -D SSH_BUILD_IPSEC -D SSH_BUILD_FIPS -D RETSIGTYPE=void -D SSH_MP_INTEGER_BIT_SIZE_STATIC=0 -D LINUX_HAS_RTM_SETLINK -D QUICKSEC_DIST_SERVER -D _LARGEFILE_SOURCE -D _FILE_OFFSET_BITS=64 -D __SMP__ -D DEBUG_LIGHT -D _GNU_SOURCE -D DEBUG_LIGHT -D ENABLE_CRYPTO_MODULE -D SGE_IPV6_ENABLED -D QUICKSEC_DIST_SERVER -D _REENTRANT -D SSH_BUILD_FIPS -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-3.3/safecode/bin/../lib/clang/3.3/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O0 -Wno-gnu -Wno-ignored-attributes -Wno-static-in-inline -Wno-typedef-redefinition -Wno-constant-conversion -Wno-enum-conversion -Wno-unused-function -Wno-tautological-constant-out-of-range-compare -Wno-empty-body -Werror -Wall -Wno-switch -Wno-enum-compare -Wno-pointer-sign -Wno-address -std=gnu89 -ferror-limit 19 -fmessage-length 0 -mstackrealign -fobjc-runtime=gcc -fdiagnostics-show-option -backend-option -vectorize-loops -o func.o -x c func.c -g -fmemsafety 
1.	<eof> parser at end of file
2.	Per-module optimization passes
3.	Running pass 'SpecializeCMSCalls' on module 'func.c'.
./build.sh: line 4:  2679 Segmentation fault      (core dumped) $CLANG -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name $SOURCE -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -relaxed-aliasing -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu core2 -target-linker-version 2.20.1 -g -coverage-file func.o -resource-dir /usr/lib/llvm-3.3/safecode/bin/../lib/clang/3.3 -dependency-file func.d -MT func.o -MP -D SSH_BUILD_IPSEC -D SSH_BUILD_FIPS -D RETSIGTYPE=void -D SSH_MP_INTEGER_BIT_SIZE_STATIC=0 -D LINUX_HAS_RTM_SETLINK -D QUICKSEC_DIST_SERVER -D _LARGEFILE_SOURCE -D _FILE_OFFSET_BITS=64 -D __SMP__ -D DEBUG_LIGHT -D _GNU_SOURCE -D DEBUG_LIGHT -D ENABLE_CRYPTO_MODULE -D SGE_IPV6_ENABLED -D QUICKSEC_DIST_SERVER -D _REENTRANT -D SSH_BUILD_FIPS -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-3.3/safecode/bin/../lib/clang/3.3/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O0 -Wno-gnu -Wno-ignored-attributes -Wno-static-in-inline -Wno-typedef-redefinition -Wno-constant-conversion -Wno-enum-conversion -Wno-unused-function -Wno-tautological-constant-out-of-range-compare -Wno-empty-body -Werror -Wall -Wno-switch -Wno-enum-compare -Wno-pointer-sign -Wno-address -std=gnu89 -ferror-limit 19 -fmessage-length 0 -mstackrealign -fobjc-runtime=gcc -fdiagnostics-show-option -backend-option -vectorize-loops -o func.o -x c $SOURCE -g -fmemsafety

**Comment by Endilll** [comment]
SAFECode is archived.
