### ISSUE TITLE
Format initializer lists one member per line.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18128]
|  |  |
| --- | --- |
| Bugzilla Link | [17754](https://llvm.org/bz17754) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I have noticed that `clang-format' has the habbit of putting all initializers on one line if they fit. I think this removes some of the readability of my code. A different way to format code would look like this:

```
void Foo::bar( ... )
: blub_(91),
  foo_(95),
  cheers_("hooray")
{
}
```

I haven't found a way to make the formatter do that, but I've created an experimental diff that yields this behaviour:

Index: lib/Format/TokenAnnotator.cpp
===================================================================
--- lib/Format/TokenAnnotator.cpp	(revision 193745)
+++ lib/Format/TokenAnnotator.cpp	(working copy)
@@ -1,4 +1,4 @@
-//===--- TokenAnnotator.cpp - Format C++ code -----------------------------===//
+////===--- TokenAnnotator.cpp - Format C++ code -----------------------------===//
 //
 //                     The LLVM Compiler Infrastructure
 //
@@ -1394,10 +1394,17 @@
              Style.AlwaysBreakTemplateDeclarations) {
     // FIXME: Fix horrible hack of using BindingStrength to find top-level <>.
     return true;
+  } else if (Right.Type == TT_CtorInitializerColon) {
+    return true;
+  } else if (Right.Type == TT_CtorInitializerComma) {
+    return false;
+  } else if (Right.Previous->Type == TT_CtorInitializerComma) {
+    return true;
   } else if (Right.Type == TT_CtorInitializerComma &&
              Style.BreakConstructorInitializersBeforeComma &&
              !Style.ConstructorInitializerAllOnOneLineOrOnePerLine) {
     return true;
+#endif
   } else if (Right.Previous->BlockKind == BK_Block &&
              Right.Previous->isNot(tok::r_brace) && Right.isNot(tok::r_brace)) {
     return true;

Surely this isn't the right way to implement it, but it results in the proposed behaviour.

**Comment by mydeveloperday** [comment]
I'm going to close this issue because https://clang.llvm.org/docs/ClangFormatStyleOptions.html  has extensive new options for handling the initalizers via `PackConstructorInitializers` especially the `Never` option.  

This option will be introduced in v14
