### ISSUE TITLE
clang -pedantic -Werror complains about C11 Generics in math.h

### ISSUE THREAD

**Issue by rakuco** [llvm/llvm-project#18162]
|  |  |
| --- | --- |
| Bugzilla Link | [17788](https://llvm.org/bz17788) |
| Version | 3.3 |
| OS | FreeBSD |
| Attachments | [Preprocessed test case.](https://user-images.githubusercontent.com/92601887/143748401-c0345d33-5e68-4b61-a0c8-1ae4f0fbd25f.gz) |
| CC | @AaronBallman,@davidchisnall,@DimitryAndric |

## Extended Description 
From <http://article.gmane.org/gmane.os.freebsd.current.scm/5259>: David says clang should not emit any warnings about Generics being used because math.h is a system header, and the following snippet should build just fine with `clang -pedantic -Werror isnan.c`:

  #include <math.h>
  int main() { return isnan(42.); }

At the moment, the build fails on FreeBSD 11-CURRENT with:

isnan.c:2:21: warning: generic selections are a C11-specific feature [-Wc11-extensions]
int main() { return isnan(42.); }
                    ^
/usr/include/math.h:118:2: note: expanded from macro 'isnan'
        __fp_type_select(x, __inline_isnanf, __inline_isnan, __inline_isnanl)
        ^
/usr/include/math.h:86:39: note: expanded from macro '__fp_type_select'
#define __fp_type_select(x, f, d, ld) _Generic((x),                     \
                                      ^
1 warning generated.

**Comment by AaronBallman** [comment]
I still cannot reproduce the issue, so closing this as worksforme. However, if you're still seeing the issue, please reopen with more details on how I can reproduce.
