### ISSUE TITLE
slice_array::operator= cannot use braced-init-list for its argument

### ISSUE THREAD

**Issue by e48d0f12-b0d3-485a-93ce-75b823b0ccac** [llvm/llvm-project#18188]
|  |  |
| --- | --- |
| Bugzilla Link | [17814](https://llvm.org/bz17814) |
| Version | unspecified |
| OS | All |
| CC | @mclow |

## Extended Description 
The following code cannot be compiled with clang and libc++ r193963:

#include <valarray>

int main()
{
    std::valarray<char> a(10);
    a[std::slice(0, 2, 3)] = {'x', 'y'};
}

According to C++ standards(ISO/IEC 14882-2011),

1) a[std::slice(0, 2, 3)] returns slice_array<char>
2) slice_array<char> has a member function operator=(const valarray<char>&)
3) valarray<char> has a constructor valarray(initializer_list<char>)

Therefore, this code should be compiled successfully.

**Comment by philnik777** [comment]
This has been fixed in LLVM12: https://godbolt.org/z/E1fbs9ro1.
