### ISSUE TITLE
trunk clang cannot find system libc++ on OS X 10.9

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18195]
|  |  |
| --- | --- |
| Bugzilla Link | [17821](https://llvm.org/bz17821) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lattner,@emaste,@nico,@timurrrr |

## Extended Description 
This is particularly in view of the discussion about moving to c++11.

In a OS X 10.9, "xcode-select --install" puts only libstdc++ in /usr/include. The result is:

$ cat test.cpp
#include <iostream>
$ ./build/bin/clang -stdlib=libstdc++ -S test.cpp
$ ./build/bin/clang  -S test.cpp
test.cpp:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^
1 error generated.

The xcode provided clang can find the include (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/c++/v1/iostream).

**Comment by arsenm** [comment]
Closing old build issue that was closed and reopened
