### ISSUE TITLE
Building clang with CMake outside LLVM tree without specifying CLANG_PATH_TO_LLVM_SOURCE

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18211]
|  |  |
| --- | --- |
| Bugzilla Link | [17837](https://llvm.org/bz17837) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
I'm trying to build Clang using CMake, and I want to keep the Clang and LLVM source trees separate. Looking at the Clang top-level CMakeLists.txt it should be possible, but when I try to build with 

cmake ... -DCLANG_PATH_TO_LLVM_BUILD=/my/llvm ...

the build fails with 

FAILED: cd /home/jesperes/dev/wtd-analyzer/build/clang-prefix/src/clang-build/include/clang/Driver && /home/jesperes/dev/wtd-analyzer/build/llvm-prefix/bin/llvm-tblgen -gen-opt-parser-defs -I /home/jesperes/dev/wtd-analyzer/build/clang-prefix/src/clang/include/clang/Driver -I /lib/Target -I /include /home/jesperes/dev/wtd-analyzer/build/clang-prefix/src/clang/include/clang/Driver/Options.td -o /home/jesperes/dev/wtd-analyzer/build/clang-prefix/src/clang-build/include/clang/Driver/Options.inc.tmp
/home/jesperes/dev/wtd-analyzer/build/clang-prefix/src/clang/include/clang/Driver/Options.td:15:9: error: Could not find include file 'llvm/Option/OptParser.td'
include "llvm/Option/OptParser.td"
        ^

I noted the "-I /lib/Target", which got me suspicious and started poking around in the CMakeLists.txt file, and discovered this line:

set(LLVM_MAIN_INCLUDE_DIR "${LLVM_MAIN_SRC_DIR}/include")

but LLVM_MAIN_SRC_DIR is only set if CLANG_PATH_TO_LLVM_SOURCE is set. However, the documentation of CLANG_PATH_TO_LLVM_SOURCE claims that it is not necessary to set if building against an installed LLVM.

It looks like the proper solution is to set LLVM_MAIN_INCLUDE_DIR properly using output from "llvm-config --includedir` if CLANG_PATH_TO_LLVM_SOURCE is not set.

**Comment by arsenm** [comment]
Obsoleted by monorepo
