### ISSUE TITLE
Clang Fails to LLVM When Aggressive Optimization Flags Are Used

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18263]
|  |  |
| --- | --- |
| Bugzilla Link | [17889](https://llvm.org/bz17889) |
| Version | trunk |
| OS | MacOS X |
| Attachments | [Output from "make VERBOSE=1"](https://user-images.githubusercontent.com/60944935/143748449-76dba8f5-0c4a-4204-a14a-9a3c5e1b28da.gz), [./configure log](https://user-images.githubusercontent.com/60944935/143748450-0f1eb490-8623-4f7f-b044-ba50b5672f94.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

I am using recent version of LLVM from svn to build LLVM itself. This time I decided to try some aggressive optimization settings:

CFLAGS='-O3 -flto -fslp-vectorize-aggressive -mavx'

The build quickly fails with the errors

Intrinsic name not mangled correctly for type arguments!
i64 (i8*, i1)* @&#8203;llvm.objectsize.i64.p0i8
Broken module found, compilation aborted!
Stack dump:
0.	Running pass 'Function Pass Manager' on module 'ld-temp.o'.
1.	Running pass 'Module Verifier' on function '@p_ere'
clang: error: unable to execute command: Illegal instruction: 4
clang: error: linker command failed due to signal (use -v to see invocation)

I am attaching the config.log and output from the compiler. Let me know if you need more information.

**Comment by Endilll** [comment]
Unfortunately, we can't do much without a reproducer.
Feel free to reopen if you have additional information.
