### ISSUE TITLE
Do-nothing static variable not optimized out

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18311]
|  |  |
| --- | --- |
| Bugzilla Link | [17937](https://llvm.org/bz17937) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
Clang does not optimize out a do-nothing static variable at O3.  The first load could be removed as rec_count should always be zero when the function is called.

This program:
    const int rec_limit = 30;
    void foo(int& x) {
        static int rec_count = 0;
        if (rec_count > rec_limit) { return; }
        rec_count += 1;
        x = 37;
        rec_count -= 1;
    }

With this command:
    % clang++ -S foo.cc -o - -O3 -I. -emit-llvm

Produces this output:
    @&#8203;_ZZ3fooRiE9rec_count = internal unnamed_addr global i32 0, align 4

    ; Function Attrs: nounwind uwtable
    define void @&#8203;_Z3fooRi(i32* nocapture %x) #&#8203;0 {
     %1 = load i32* @&#8203;_ZZ3fooRiE9rec_count, align 4, !tbaa !&#8203;0
     %2 = icmp sgt i32 %1, 30
     br i1 %2, label %7, label %3

    ; <label>:3                                       ; preds = %0
     %4 = add nsw i32 %1, 1
     store i32 %4, i32* @&#8203;_ZZ3fooRiE9rec_count, align 4, !tbaa !&#8203;0
     store i32 37, i32* %x, align 4, !tbaa !&#8203;0
     %5 = load i32* @&#8203;_ZZ3fooRiE9rec_count, align 4, !tbaa !&#8203;0
     %6 = add nsw i32 %5, -1
     store i32 %6, i32* @&#8203;_ZZ3fooRiE9rec_count, align 4, !tbaa !&#8203;0
     br label %7

    ; <label>:7                                       ; preds = %0, %3
     ret void
    }

**Comment by xgupta** [comment]
This issue is fixed on trunk - https://godbolt.org/z/j8rh8f7xn and static variable optimize out, hence closing.
