### ISSUE TITLE
-Wall does not enable -Wconditional-uninitialized

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18348]
|  |  |
| --- | --- |
| Bugzilla Link | [17974](https://llvm.org/bz17974) |
| Version | 3.3 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid,@rnk |

## Extended Description 
Bug #&#8203;17940 reported a case where gcc reports an uninitialised variable at -Wall -O2, but clang does not. The bug was marked as "RESOLVED INVALID" because the option -Wconditional-uninitialized exposes the bug. So I'm opening a new bug because -Wall obviously does not enable that option:

ddd@Marypuce ~> clang -Wall -c -O2 /tmp/undetected.cpp 
ddd@Marypuce ~> clang -Wconditional-uninitialized -c -O2 /tmp/undetected.cpp 
/tmp/undetected.cpp:9:12: warning: variable 'result' may be uninitialized when
      used here [-Wconditional-uninitialized]
    return result;
           ^~~~~~
/tmp/undetected.cpp:6:17: note: initialize the variable 'result' to silence this
      warning
    char *result;
                ^
                 = 0
1 warning generated.

**Comment by philnik777** [comment]
`-Wsometimes-unintitialized` is enabled by `-Wall` since Clang 3.2: https://godbolt.org/z/5Evhd6588
