### ISSUE TITLE
equivilent of gdb's follow-fork-mode child

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18346]
|  |  |
| --- | --- |
| Bugzilla Link | [17972](https://llvm.org/bz17972) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @arrowd,@emaste,@jrmuizel,@jryans,@jwatt,@mstange,@Trass3r,@yuanfang-chen |

## Extended Description 
There is no way to attach to a child process across fork() immediately after it is created. gdb has this feature through follow-fork-mode child.

**Comment by labath** [comment]
This is now implemented (via the target.process.follow-fork-mode setting).
