### ISSUE TITLE
lld build fails when compiling HexagonLinkingContext.cpp

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18340]
|  |  |
| --- | --- |
| Bugzilla Link | [17966](https://llvm.org/bz17966) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Build of llvm+clang+lld with clang3.3 fails on Debian Wheezy
svn version 194914.
(also, Hexagon support is disabled in configuration of this build)

[ 98%] Building CXX object tools/lld/lib/ReaderWriter/ELF/Hexagon/CMakeFiles/lldHexagonELFTarget.dir/HexagonLinkingContext.cpp.o
In file included from /home/buildbot/llvm/svn/llvm/tools/lld/lib/ReaderWriter/ELF/Hexagon/HexagonLinkingContext.cpp:11:
In file included from /home/buildbot/llvm/svn/llvm/tools/lld/lib/ReaderWriter/ELF/Hexagon/HexagonLinkingContext.h:13:
In file included from /home/buildbot/llvm/svn/llvm/tools/lld/lib/ReaderWriter/ELF/Hexagon/HexagonTargetHandler.h:13:
In file included from /home/buildbot/llvm/svn/llvm/tools/lld/lib/ReaderWriter/ELF/./DefaultTargetHandler.h:13:
In file included from /home/buildbot/llvm/svn/llvm/tools/lld/lib/ReaderWriter/ELF/./DefaultLayout.h:14:
In file included from /home/buildbot/llvm/svn/llvm/tools/lld/lib/ReaderWriter/ELF/./HeaderChunks.h:13:
In file included from /home/buildbot/llvm/svn/llvm/tools/lld/lib/ReaderWriter/ELF/./SegmentChunks.h:15:
In file included from /home/buildbot/llvm/svn/llvm/tools/lld/lib/ReaderWriter/ELF/./SectionChunks.h:19:
In file included from /home/buildbot/llvm/svn/llvm/tools/lld/include/lld/Core/Parallel.h:28:
In file included from /usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../../include/c++/4.6/condition_variable:38:
/usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../../include/c++/4.6/chrono:535:6: error: no matching
      constructor for initialization of 'duration' (aka 'std::chrono::duration<long long,
      std::ratio<1, 1000000> >')
          : __d(__t.time_since_epoch())
            ^   ~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../../include/c++/4.6/condition_variable:106:42: note: in
      instantiation of function template specialization
      'std::chrono::time_point<std::chrono::system_clock, std::chrono::duration<long long,
      std::ratio<1, 1000000> > >::time_point<std::chrono::duration<long long, std::ratio<1,
      1000000000> > >' requested here
        const __clock_t::time_point __s_atime = __s_entry + __delta;
                                                ^
/usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../../include/c++/4.6/chrono:234:12: note: candidate
      constructor not viable: no known conversion from 'duration<[...], ratio<[...], 1000000000>>'
      to 'const duration<[...], ratio<[...], 1000000>>' for 1st argument
        constexpr duration(const duration&) = default;
                  ^
/usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../../include/c++/4.6/chrono:240:23: note: candidate
      template ignored: couldn't infer template argument ''
          constexpr explicit duration(const _Rep2& __rep)
                             ^
/usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../../include/c++/4.6/chrono:247:14: note: candidate
      template ignored: couldn't infer template argument ''
          constexpr duration(const duration<_Rep2, _Period2>& __d)
                    ^
/usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../../include/c++/4.6/chrono:232:12: note: candidate
      constructor not viable: requires 0 arguments, but 1 was provided
        constexpr duration() : __r() { }
                  ^
1 error generated.

**Comment by arsenm** [comment]
Old build failure
