### ISSUE TITLE
assertion if pack expansion of lambda contains struct with member function with dependent decl

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#18359]
|  |  |
| --- | --- |
| Bugzilla Link | [17985](https://llvm.org/bz17985) |
| Version | trunk |
| OS | Linux |
| CC | @majnemer,@DougGregor |

## Extended Description 
This causes IRgen to assert:

  template<typename ...T> void g(T...);
  template<typename ...T> void f() {
    g(
      []{
        struct S { T f() { static T t; return ++t; } } s;
        return s.f();
      }()...
    );
  }
  template void f<int, int, int>();

The instantiation of S::f inside each lambda looks like this:

  CXXMethodDecl 0x6a9a480 <col:22, col:54> f 'int (void)'
  `-CompoundStmt 0x6aa1628 <col:28, col:54>
    |-DeclStmt 0x6aa15a8 <col:30, col:40>
    | `-VarDecl 0x6aa1550 <col:30, col:39> t 'T' static
    `-ReturnStmt 0x6aa1608 <col:42, col:51>
      `-UnaryOperator 0x6aa15e8 <col:49, col:51> '<dependent type>' prefix '++'
        `-DeclRefExpr 0x6aa15c0 <col:51> 'T' lvalue Var 0x6aa1550 't' 'T'

That's clearly bogus: we should have substituted for T here.

Net result: IRgen asserts:

clang-3.4: lib/AST/Type.cpp:887: bool clang::Type::isConstantSizeType() const: Assertion `!isDependent
Type() && "This doesn't make sense for dependent types"' failed.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.7: https://godbolt.org/z/nzKdTW3na
