### ISSUE TITLE
static_assert does not print the whole condition on failure

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#18389]
|  |  |
| --- | --- |
| Bugzilla Link | [18015](https://llvm.org/bz18015) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Example:

static_assert(std::is_same<int,
              float>::value,
              "error message for static assert");

prints:

error: static_assert failed "error message for static assert"
    static_assert(std::is_same<int,
    ^             ~~~~~~~~~~~~~~~~

It should at least print the whole condition, that is:

error: static_assert failed "error message for static assert"
    static_assert(std::is_same<int,
                  float>::value, 
    ^             ~~~~~~~~~~~~~~~~

I'd rather have the complete condition than the "static_assert(" part which is redundant: 

error: static_assert failed "error message for static assert", condition: 
       std::is_same<int,
                  float>::value
is false.

**Comment by Endilll** [comment]
We are including condition in the message since Clang 6: https://godbolt.org/z/zn5M564Gb
