### ISSUE TITLE
MLIR: how to disable constant propagation during inlining?

### ISSUE THREAD

**Issue by dpotop** [llvm/llvm-project#184]
Hello,

It seems that adding inlining to the pass manager automatically 
enables constant propagation. Is there a way to disable it ?

Best regards,
Dumitru

**Comment by River707** [comment]
What is your use case for disabling? The inliner runs canonicalization/simplification on the callgraph nodes during inlining as it will directly play into the cost model. There is a flag `mlir-disable-inline-simplify`, but that has generally just been for testing.

**Comment by dpotop** [comment]
Thanks River707 - testing is exactly my objective, since it's apparently the only way of starting to use MLIR, and understanding how each pass works.
