### ISSUE TITLE
Regression: NaN handling differs from LLVM 3.1-3.3

### ISSUE THREAD

**Issue by redstar** [llvm/llvm-project#18422]
|  |  |
| --- | --- |
| Bugzilla Link | [18048](https://llvm.org/bz18048) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [IR file demonstrating the problem.](https://user-images.githubusercontent.com/827859/143748539-e627dc94-3519-439d-ae32-b5f380565815.gz) |
| CC | @gottesmm |

## Extended Description 

The attached IR code is reduced from a D program. It can be compiled and run on Linux/x86_64.

Compiled with llc -filetype=obj bug.ll ; gcc -o bug bug.o ; ./bug it produces the output:

0000ffff - 0000ffff

but compiled with opt -O3 <bug.ll | llc -filetype=obj >bug.o ; gcc -o bug bug.o ; ./bug it produces the output:

0000ffff - 00007fff

The root cause seems to be that -real.nan is negativ but 2* -real.nan is positiv (with -O3). That is really surprising.

The original D program is:
import core.stdc.stdio : printf;

ushort sign(real x)
{
    ushort* pxe = cast(ushort *)&x;
    return pxe[4];
}

void main()
{
    real x = -real.nan;
    real y = 2*x;
    printf("%08x - %08x\n", sign(x), sign(y));
}

This happens only with LLVM3.4+, not with LLVM 3.1/3.2/3.3.

**Comment by arsenm** [comment]
Sign bit of a nan is meaningless and you aren't supposed to depend on them
