### ISSUE TITLE
Segmentation fault in clang::CodeGen::CodeGenFunction::EmitScalarExpr (Clang 3.4 trunk)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18433]
|  |  |
| --- | --- |
| Bugzilla Link | [18059](https://llvm.org/bz18059) |
| Version | trunk |
| OS | Linux |
| Attachments | [Archive with Solver-9dbcd0.{sh|cpp}](https://user-images.githubusercontent.com/60944935/143748554-78d780da-606e-4bff-bf0f-a66b7ee9ea7b.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

The bug is present in 3.3, and in 3.4 trunk. Might be a duplicate of Bug 15909, which is for 3.2.

Error message:

0  clang-3.4       0x00000000013c5432 llvm::sys::PrintStackTrace(_IO_FILE*) + 34
1  clang-3.4       0x00000000013c4fe4
2  libpthread.so.0 0x00007fe3d1f7e870
3  clang-3.4       0x00000000014e8c97
4  clang-3.4       0x00000000006722c5
5  clang-3.4       0x00000000014e9d5a
6  clang-3.4       0x00000000014eb12d clang::CodeGen::CodeGenFunction::EmitScalarExpr(clang::Expr const*, bool) + 61
7  clang-3.4       0x00000000014a74b7 clang::CodeGen::CodeGenFunction::EmitScalarInit(clang::Expr const*, clang::ValueDecl const*, clang::CodeGen::LValue, bool) + 967
8  clang-3.4       0x0000000001499934 clang::CodeGen::CodeGenFunction::EmitInitializerForField(clang::FieldDecl*, clang::CodeGen::LValue, clang::Expr*, llvm::ArrayRef<clang::VarDecl*>) + 388
9  clang-3.4       0x000000000149a1b2
10 clang-3.4       0x000000000149ac51 clang::CodeGen::CodeGenFunction::EmitCtorPrologue(clang::CXXConstructorDecl const*, clang::CXXCtorType, clang::CodeGen::FunctionArgList&) + 929
11 clang-3.4       0x000000000149aff7 clang::CodeGen::CodeGenFunction::EmitConstructorBody(clang::CodeGen::FunctionArgList&) + 151
12 clang-3.4       0x000000000142ac8b clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) + 1707
13 clang-3.4       0x000000000149d7aa clang::CodeGen::CodeGenModule::EmitCXXConstructor(clang::CXXConstructorDecl const*, clang::CXXCtorType) + 186
14 clang-3.4       0x000000000143e0d1 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl) + 385
15 clang-3.4       0x000000000143e1bd clang::CodeGen::CodeGenModule::EmitDeferred() + 125
16 clang-3.4       0x000000000143e1f9 clang::CodeGen::CodeGenModule::Release() + 9
17 clang-3.4       0x00000000013e8020
18 clang-3.4       0x00000000016823db clang::ParseAST(clang::Sema&, bool, bool) + 507
19 clang-3.4       0x00000000015c9df1 clang::FrontendAction::Execute() + 177
20 clang-3.4       0x00000000015ab220 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 304
21 clang-3.4       0x00000000013c8f4f clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 1727
22 clang-3.4       0x000000000074b2d8 cc1_main(char const**, char const**, char const*, void*) + 1192
23 clang-3.4       0x000000000072e4eb main + 7611
24 libc.so.6       0x00007fe3d13c8bc5 __libc_start_main + 245
25 clang-3.4       0x00000000007497e5
Stack dump:
0.	Program arguments: /usr/bin/clang-3.4 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name Solver.cpp -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -g -coverage-file /home/thume/Work/nina/src/xHeinz/CMakeFiles/mwcscommon.dir/Solver.cpp.o -resource-dir /usr/bin/../lib/clang/3.4 -D IL_STD -D DEBUG -D VERBOSE -I /opt/ibm/ILOG/CPLEX_Studio1251/cplex/include -I /opt/ibm/ILOG/CPLEX_Studio1251/concert/include -I /home/thume/Work/nina/src/xHeinz/../externlib/lemon-1.3/include -I /home/thume/Work/nina/src/xHeinz/../externlib/tinyxml2 -I /home/thume/Work/nina/src/xHeinz/.. -I /home/thume/Work/nina/src/xHeinz/. -internal-isystem /usr/include/c++/v1 -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/clang/3.4/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -Wall -std=c++1y -fdeprecated-macro -fdebug-compilation-dir /home/thume/Work/nina/src/xHeinz -ferror-limit 19 -fmessage-length 123 -mstackrealign -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-slp -o CMakeFiles/mwcscommon.dir/Solver.cpp.o -x c++ /home/thume/Work/nina/src/xHeinz/Solver.cpp 
1.	<eof> parser at end of file
2.	Per-file LLVM IR generation
3.	/home/thume/Work/nina/src/xHeinz/./Graph.hpp:34:6: Generating code for declaration 'xHeinz::Graph::DataStruct<lemon::SmartGraphBase::Node>::DataStruct'
clang-3.4: error: unable to execute command: Segmentation fault (core dumped)
clang-3.4: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.4 (trunk)
Target: x86_64-unknown-linux-gnu
Thread model: posix
clang-3.4: note: diagnostic msg: PLEASE submit a bug report to  and include the crash backtrace, preprocessed source, and associated run script.
clang-3.4: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3.4: note: diagnostic msg: /tmp/Solver-9dbcd0.cpp
clang-3.4: note: diagnostic msg: /tmp/Solver-9dbcd0.sh
clang-3.4: note: diagnostic msg: 

********************

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.6: https://godbolt.org/z/GWff8K915
Reduced by C-Reduce:
```cpp
struct Graph {
  template < typename > struct DataStruct {
    DataStruct() {}
    int comp = 0;
  };
  struct SpecialIter {
    DataStruct< int > startNode;
  };
};
Graph::SpecialIter __trans_tmp_6;
```
