### ISSUE TITLE
Failures on freebsd-x86_64-9.2: scimark2, nbench, initp1, mandel

### ISSUE THREAD

**Issue by kaomoneus** [llvm/llvm-project#18463]
|  |  |
| --- | --- |
| Bugzilla Link | [18089](https://llvm.org/bz18089) |
| Version | trunk |
| OS | Linux |
| Attachments | [Logs](https://user-images.githubusercontent.com/857042/143748574-cec6f6cb-95c2-4669-8754-0ba7a8ca07c9.gz), [Failures with gcc-4.7 as system compiler](https://user-images.githubusercontent.com/857042/143748575-5af10366-5cef-463f-8129-45f70ba9b3c4.gz) |
| CC | @emaste |

## Extended Description 

Hello,
I got 4 failures on freebsd-x86_64-9.2:
MultiSource/Benchmarks/SciMark2-C LNT failure on freebsd-9.2-x86_64 machines - fp difference
MultiSource/Benchmarks/nbench - timeout
SingleSource/UnitTests, Output/initp1.out-llc - didn't output anything
SingleSource/Benchmarks/Misc/mandel - fp difference.

Mandel test also has been described here (pr18056):
http://llvm.org/bugs/show_bug.cgi?id=18056

Logs ("gmake VERBOSE=1 TEST=nightly report 1>make.log 2>make.err") are attached.

**Comment by arsenm** [comment]
Old failures
