### ISSUE TITLE
asm declaration makes the backend crash

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#18487]
|  |  |
| --- | --- |
| Bugzilla Link | [18113](https://llvm.org/bz18113) |
| Version | trunk |
| OS | Linux |
| Depends On | llvm/llvm-project#37244  |

## Extended Description 
The following declaration: 
__asm__(".symver foo, bar@@v"  );

make clang crash with:

fatal error: error in backend: A @@ version cannot be undefined
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Debian clang version 3.3-12 (branches/release_33) (based on LLVM 3.3)
Target: x86_64-pc-linux-gnu
Thread model: posix
Fails with both 3.3 and 3.4 rc1.

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.3 and 3.4: https://godbolt.org/z/3GbPcodK9
