### ISSUE TITLE
incorrect implementation of isnan and similar functions

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18592]
|  |  |
| --- | --- |
| Bugzilla Link | [18218](https://llvm.org/bz18218) |
| Version | unspecified |
| OS | All |
| Depends On | llvm/llvm-project#18759  |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dlj-NaN,@eugenis,@K-ballo,@mclow,@zygoloid,@seanm |

## Extended Description 
The standard specifies in [c.math] that isnan and other classification functions must have the following overloads:

   bool isnan(float x);
   bool isnan(double x);
   bool isnan(long double x);

Implementing it as a template seems like a good idea, except that the following valid code is rejected:
 
   #include <cmath>

   struct A {
      operator float()   {    return 0.0;  }
   };

   int main() {
      std::isnan(A());
   }

The template should be enabled for every type that is convertible to an arithmetic type, to make the implementation indistinguishable from what is specified in the standard.

**Comment by philnik777** [comment]
This has been fixed in LLVM 10: https://godbolt.org/z/j6Y8h3d8G.
