### ISSUE TITLE
MLIR: how to get the full list of options?

### ISSUE THREAD

**Issue by dpotop** [llvm/llvm-project#186]
I've just discovered that "--help-hidden" and "--help-list-hidden" are not printing all available options. For instance, "--mlir-disable-inline-simplify" is not printed. How can I print all of them, or otherwise obtain a list of them?

**Comment by joker-eph** [comment]
(Assigned to River.)
FYI: we prefer bugzilla to centralize all of our issues

**Comment by River707** [comment]
Many of the testing options in LLVM are marked as `ReallyHidden` as they are only meant for testing, and not really for users. There is no way for these options to appear in the help.
https://llvm.org/docs/CommandLine.html#hiding-an-option-from-help-output

**Comment by dpotop** [comment]
Thanks River707. My problem is the following - I'm trying to use MLIR to write a compiler for a DSL, and I really advanced in doing this. But documentation is scarce. I really don't know where to ask questions, except here...

**Comment by joker-eph** [comment]
@dpotop 
If the documentation is scarce, we'd like to know about it and your pain point: it is very important to us to produce better document and user feedback is critical to achieve it!
The best way to engage is likely Discord (for live chat discussions/question), Discourse (forum-style), and bugzilla. They are all referenced from https://mlir.llvm.org/
Hope this helps!
