### ISSUE TITLE
llvm-objdump: warning: invalid instruction encoding

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18667]
|  |  |
| --- | --- |
| Bugzilla Link | [18293](https://llvm.org/bz18293) |
| Version | 3.3 |
| OS | other |
| Attachments | [llvm-objdump output](https://user-images.githubusercontent.com/60944935/143748682-5ae6ab0d-6263-49e3-9d33-5bd083479729.gz), [gnu objdump output](https://user-images.githubusercontent.com/60944935/143748683-58a12884-2557-4b87-9a07-233601c1168c.gz), [source file](https://user-images.githubusercontent.com/60944935/143748684-7f2be68b-5f1c-4796-affe-f3fb63637886.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @emaste |

## Extended Description 

llvm-objdump warns of an invalid instruction encoding.

This is on i386.  It was compiled with -no-integrated-as and binutils 2.15

I have attached 3 files.

mptramp.S - source file
llvm-objdump.txt - output of llvm-objdump
objdump.txt - output of gnu objdump

mptramp.o:      file format ELF32-i386

Disassembly of section .text:
cpu_spinup_trampoline:
       0:       fa                                              cli
       1:       31 c0                                           xorl    %eax, %eax
       3:       8e d8                                           movl    %eax, %ds
       5:       8e c0                                           movl    %eax, %es
       7:       8e d0                                           movl    %eax, %ss
       9:       67 66 0f 01 15                                  lgdtw   (%di)
       e:       b4 70                                           movb    $112, %ah
      10:       00 00                                           addb    %al, (%eax)
      12:       0f 20 c0                                        movl    %cr0, %eax
      15:       66 83 c8 01                                     orw     $1, %ax
      19:       0f 22 c0                                        movl    %eax, %cr0
      1c:       ea 21 70 08 00 b8 10                            ljmpl   $4280, $552993
      23:       00 00                                           addb    %al, (%eax)
      25:       00 8e d8 8e d0 8e                               addb    %cl, -1898934568(%esi)
      2b:       c0 8e e0 8e e8 bc f0                            rorb    $-16, -1125609760(%esi)
      32:       7f 00                                           jg      0
      34:       00 6a 02                                        addb    %ch, 2(%edx)
      37:       9d                                              popfl
      38:       8b 0d 00 00 00 30                               movl    805306368, %ecx
      3e:       0f 22 d9                                        movl    %ecx, %cr3
      41:       0f 20 c0                                        movl    %cr0, %eax
      44:       0d 2f 00 01 80                                  orl     $2147549231, %eax
      49:       0f 22 c0                                        movl    %eax, %cr0
      4c:       a1 20 00 00 00                                  movl    32, %eax
      51:       c1 e8 18                                        shrl    $24, %eax
      54:       31 db                                           xorl    %ebx, %ebx
      56:       8d 0c 9d 00 00 00 00                            leal    (,%ebx,4), %ecx
      5d:       43                                              incl    %ebx
      5e:       8b 89 00 00 00 00                               movl    (%ecx), %ecx
      64:       8b 91 a4 01 00 00                               movl    420(%ecx), %edx
      6a:       39 c2                                           cmpl    %eax, %edx
      6c:       75 e8                                           jne     -24
      6e:       66 c7 44 24 06 ff ff                            movw    $65535, 6(%esp)
      75:       8b 81 24 03 00 00                               movl    804(%ecx), %eax
      7b:       89 44 24 08                                     movl    %eax, 8(%esp)
      7f:       0f 01 54 24 06                                  lgdt    6(%esp)
      84:       eb 01                                           jmp     1
      86:       90                                              nop
      87:       b8 10 00 00 00                                  movl    $16, %eax
      8c:       8e d8                                           movl    %eax, %ds
      8e:       8e c0                                           movl    %eax, %es
      90:       8e d0                                           movl    %eax, %ss
      92:       6a 08                                           pushl   $8
      94:       68 ba 00 00 00                                  pushl   $186
      99:       cb                                              lretl
      9a:       00 00                                           addb    %al, (%eax)
      9c:       00 00                                           addb    %al, (%eax)
      9e:       00 00                                           addb    %al, (%eax)
      a0:       00 00                                           addb    %al, (%eax)
      a2:       00 00                                           addb    %al, (%eax)
llvm-objdump: warning: invalid instruction encoding
      a6:       00 00                                           addb    %al, (%eax)
      a8:       00 9f cf 00 ff ff                               addb    %bl, -65329(%edi)
      ae:       00 00                                           addb    %al, (%eax)
      b0:       00 93 cf 00 17 00                               addb    %dl, 1507535(%ebx)
      b6:       9c                                              pushfl
      b7:       70 00                                           jo      0

mp_cont:
      ba:       8b b1 bc 01 00 00                               movl    444(%ecx), %esi
      c0:       8b 66 38                                        movl    56(%esi), %esp
      c3:       8b 6e 3c                                        movl    60(%esi), %ebp
      c6:       8b 46 1c                                        movl    28(%esi), %eax
      c9:       0f 22 d8                                        movl    %eax, %cr3
      cc:       b8 20 00 00 00                                  movl    $32, %eax
      d1:       8e e0                                           movl    %eax, %fs
      d3:       31 c0                                           xorl    %eax, %eax
      d5:       8e e8                                           movl    %eax, %gs
      d7:       8b 86 78 02 00 00                               movl    632(%esi), %eax
      dd:       0f 22 c0                                        movl    %eax, %cr0
      e0:       51                                              pushl   %ecx
      e1:       e8 fc ff ff ff                                  calll   -4

**Comment by MaskRay** [comment]
There is no mapping symbol to tell whether a region is `.code16`, so this is infeasible to fix.
