### ISSUE TITLE
32-bit Linux fails to compile with clang due to std::atomic support

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18685]
|  |  |
| --- | --- |
| Bugzilla Link | [18311](https://llvm.org/bz18311) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Trying to compile the latest lldb from trunk on 32-bit Linux currently fails with this error:

In file included from SBBlock.cpp:10:
In file included from /home/andrew/src/llvm-trunk/tools/lldb/source/API/../../include/lldb/API/SBBlock.h:13:
In file included from /home/andrew/src/llvm-trunk/tools/lldb/source/API/../../include/lldb/API/SBDefines.h:18:
In file included from /home/andrew/src/llvm-trunk/tools/lldb/source/API/../../include/lldb/lldb-defines.h:13:
In file included from /home/andrew/src/llvm-trunk/tools/lldb/source/API/../../include/lldb/lldb-types.h:14:
In file included from /home/andrew/src/llvm-trunk/tools/lldb/source/API/../../include/lldb/lldb-forward.h:15:
In file included from /home/andrew/src/llvm-trunk/tools/lldb/source/API/../../include/lldb/Utility/SharingPtr.h:22:
In file included from /usr/lib/gcc/i686-linux-gnu/4.8/../../../../include/c++/4.8/atomic:41:
/usr/lib/gcc/i686-linux-gnu/4.8/../../../../include/c++/4.8/bits/atomic_base.h:420:16: error:
      cannot compile this atomic library call yet
      { return __atomic_add_fetch(&_M_i, __i, memory_order_seq_cst); }
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

The error appears to be because clang doesn't yet support C++11 std::atomic on 64-bit values (bug 15034) and this is used at least in Address::m_offset.

**Comment by DavidSpickett** [comment]
While this might still be an issue somewhere out there, the only 32-bit builder is https://lab.llvm.org/buildbot/#/builders/17 and it's fine at the moment. Note that it is using clang.

Closing.
