### ISSUE TITLE
`InitHeaderSearch.cpp:17:51`: `fatal error: clang/Config/config.h: No such file or directory`

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18686]
|  |  |
| --- | --- |
| Bugzilla Link | [18312](https://llvm.org/bz18312) |
| Version | 3.3 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@DougGregor,@zygoloid |

## Extended Description 
I get the following error when I try to build clang from source on a Debian 6 machine:
```
InitHeaderSearch.cpp:17:51: fatal error: clang/Config/config.h: No such file or directory
compilation terminated.
/bin/rm: cannot remove '/local/stiwari/llvm2/llvm-3.3.src/tools/cfe-3.3.src/lib/Frontend/Release+Asserts/InitHeaderSearch.d.tmp': No such file or directory
```
The reproduction steps are:
1. Download LLVM and Clang source ( version 3.3) into the current directory. Their path being `./llvm-3.3.src.tar.gz` and `./cfe-3.3.src.tar.gz`
2. Extract llvm by `tar -zxvf llvm-3.3.src.tar.gz` such that the `llvm-3.3.src` folder is created.
3. `cd llvm-3.3.src/tools`
4. `tar -zxvf ./../../cfe-3.3.src.tar.gz`
5. `cd ..`
6. `./configure`
7. `make`
8. `cd tools/cfe-3.3.src`
9. `make`

**Comment by Endilll** [comment]
Feel free to reopen if this reproduces when building a supported version of Clang on a supported platform.
