### ISSUE TITLE
crash at some source files with gcc's -O > 0

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18741]
|  |  |
| --- | --- |
| Bugzilla Link | [18367](https://llvm.org/bz18367) |
| Version | unspecified |
| OS | Windows XP |
| Attachments | [compilation log](https://user-images.githubusercontent.com/60944935/143748737-c9b44430-3194-4baf-b24e-f7a3b347d772.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

When trying to recompile gcc 4.6.4 with itself with dragonegg enabled (cygwin, gcc patched to support dll plugins), it crashes at some files - mostly at libgcc.

gcc configure flags: --enable-shared --enable-static --disable-bootstrap --with-arch=pentium3 --with-tune=pentium3 --enable-languages=ada,c,c++,fortran --disable-graphite --enable-lto --enable-threads=posix --disable-win32-registry --enable-plugin --build=pentium3-pc-cygwin

llvm configure flags: --enable-optimized --disable-assertions --enable-shared --enable-libffi --enable-ltdl-install --disable-docs --build=pentium3-pc-cygwin

dragonegg compiled with llvm plugins enabled (doesn't seem to make a difference)

llvm and dragonegg 3.4rc3, CFLAGS in the compilation log.

Adding -O0 prevents crash from happening (despite level 3 optimizations enabled for dragonegg for both ir-optimize and codegen-optimize using CFLAGS), so it is clearly gcc messing something up. Still, the crash happens regardless of ir-optimize/codegen-optimize levels for gcc's -O > 0, so if one wants to use both dragonegg and gcc optimizations, that's something to consider.

**Comment by asl** [comment]
Dragonegg is obsolete
