### ISSUE TITLE
ENABLE_LLVM_PLUGINS=1 : dlopen(/opt/local/libexec/dragonegg/llvm35gcc48.so, 10): Symbol not found: __ZN4llvm20createObjCARCOptPassEv

### ISSUE THREAD

**Issue by 0e6f8740-1d2a-4afc-85fd-df25c3a603fd** [llvm/llvm-project#18781]
|  |  |
| --- | --- |
| Bugzilla Link | [18407](https://llvm.org/bz18407) |
| Version | trunk |
| OS | All |

## Extended Description 
When we turned on ENABLE_LLVM_PLUGINS=1 to support polly in dragonegg-gcc

This issue came up with trunk r198565 but doesn't seem to be an issue with 3.4 r198150.

**Comment by asl** [comment]
Dragonegg is obsolete
