### ISSUE TITLE
Several of the editor integration scripts are missing license headers

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#18816]
|  |  |
| --- | --- |
| Bugzilla Link | [18442](https://llvm.org/bz18442) |
| Version | trunk |
| OS | All |

## Extended Description 
We're thinking about adding clang-format to chromium's tooling. Our license checker script complained that several of the integration scripts are missing license headers.

(This isn't blocking us, but it'd be nice to fix anyhow.)

**Comment by mydeveloperday** [comment]
clang-format-diff.py
clang-format.py
and 
git-clang-format all carry the following license

```
#===- clang-format-diff.py - ClangFormat Diff Reformatter ----*- python -*--===#
#
# Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
#===------------------------------------------------------------------------===#
```
These were added in 2019 post this bug being raised, I'm going to close this issue, if you think there are others that need doing please reopen this issue (but could you be specific about which files need to be changed)
