### ISSUE TITLE
[powerpc-darwin] cpusubtype mismatches between integrated/no-integrated-as

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18837]
|  |  |
| --- | --- |
| Bugzilla Link | [18463](https://llvm.org/bz18463) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @echristo,@iains,@jeremyhu |

## Extended Description 
Object files written by the integrated-as get a different CPU subtype than using no-integrated-as.  

% otool -h gcc40-stage2-build/lib/Support/CMakeFiles/LLVMSupport.dir/IsNAN.cpp.o
gcc40-stage2-build/lib/Support/CMakeFiles/LLVMSupport.dir/IsNAN.cpp.o:
Mach header
      magic cputype cpusubtype   filetype ncmds sizeofcmds      flags
 0xfeedface      18         10          1     3        364 0x00002000

% otool -h gcc40-stage2-intas-build/lib/Support/CMakeFiles/LLVMSupport.dir/IsNAN.cpp.o
gcc40-stage2-intas-build/lib/Support/CMakeFiles/LLVMSupport.dir/IsNAN.cpp.o:
Mach header
      magic cputype cpusubtype   filetype ncmds sizeofcmds      flags
 0xfeedface      18          0          1     3        364 0x00002000

-----------------------------^ here

Is this perhaps related to the .machine directive in AsmParser?

Once we get this to match, I can do a direct object comparison between stage-2 with/without integrated-as.

**Comment by chenzheng1030** [comment]
PowerPC dropped the support for Darwin. Closing this item.
