### ISSUE TITLE
Bogus message regarding use of "this" in friend declaration

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [llvm/llvm-project#18849]
|  |  |
| --- | --- |
| Bugzilla Link | [18475](https://llvm.org/bz18475) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
The use of "this" in trailing-return-types and exception-specifications does not work in friend declarations in Clang.

## SMALL SOURCE:
```cpp
struct Other {
   int p();
   auto q() -> decltype(p()) *;
};

class Friendly {
   // according to 5.1.1 [expr.prim.general] paragraph 3 the expression "this"
   // below is a prvalue of type "pointer to Other".
   friend auto Other::q() -> decltype(this->p()) *;
      // GCC and ICC accepts, Clang rejects
};
```

## COMPILER INVOCATION:
clang++ -std=c++11 friendThis.cc 

## ACTUAL OUTPUT:

```console
friendThis.cc:9:39: error: invalid use of 'this' outside of a non-static member function
   friend auto Other::q() -> decltype(this->p()) *;
                                      ^
1 error generated.
```

## EXPECTED OUTPUT:
Clean compile.

## clang++ -v:
clang version 3.5 
Target: powerpc64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/ppc64-redhat-linux/3.4.6
Found candidate GCC installation: /usr/lib/gcc/ppc64-redhat-linux/4.4.6
Selected GCC installation: /usr/lib/gcc/ppc64-redhat-linux/4.4.6

**Comment by pepsiman** [comment]
GCC rejects this from 9.1 onwards.

**Comment by Endilll** [comment]
Per [[expr.prim.this]](http://eel.is/c++draft/expr.prim.this), `this` is allowed to appear only in declarations of member functions, member function templates, and non-static data members. Friend declarations do not belong to any of those categories.

GCC agrees, EDG and MSVC do not: https://godbolt.org/z/jfaM78jhq
