### ISSUE TITLE
crash if no lib is found

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18857]
|  |  |
| --- | --- |
| Bugzilla Link | [18483](https://llvm.org/bz18483) |
| Version | 3.3 |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I'm trying to run clang on ARM (Final release 3.3) and i can't figure out what libs are needed. That's the reason it crashes for the simplest file with empty main() functions.

01-15 12:45:42.925: INFO/System.out(15326): /data/data/name.antonsmirnov.android.cppdroid/se/clang -c -g -DIDE=CppDroid /data/data/name.antonsmirnov.android.cppdroid/buildSources/project_jan14b.cpp -o /data/data/name.antonsmirnov.android.cppdroid/build/project_jan14b.cpp.o
01-15 12:45:43.085: WARN/System.err(15326): clang: error: unable to execute command: No such file or directory
01-15 12:45:43.085: WARN/System.err(15326): clang: error: assembler (via gcc) command failed due to signal (use -v to see invocation)
01-15 12:45:43.085: WARN/System.err(15326): clang version 3.3 (tags/RELEASE_33/final)
01-15 12:45:43.085: WARN/System.err(15326): Target: arm-unknown--eabi
01-15 12:45:43.085: WARN/System.err(15326): Thread model: posix
01-15 12:45:43.095: WARN/System.err(15326): clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
01-15 12:45:43.125: WARN/System.err(15326): clang: note: diagnostic msg:
01-15 12:45:43.125: WARN/System.err(15326): ********************
01-15 12:45:43.125: WARN/System.err(15326): [ 01-15 12:45:43.125 15326:15532 W/System.err ]
        PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
01-15 12:45:43.125: WARN/System.err(15326): Preprocessed source(s) and associated run script(s) are located at:
01-15 12:45:43.125: WARN/System.err(15326): clang: note: diagnostic msg: /storage/sdcard0/CppDroid/temp/project_jan14b-j15530.cpp
01-15 12:45:43.135: WARN/System.err(15326): assertion "I != std::string::npos && "Expected to find -main-file-name"" failed: file "Driver.cpp", line 476, function "void clang::driver::Driver::generateCompilationDiagnostics(clang::driver::Compilation&, const clang::driver::Command*)"
01-15 12:45:43.135: WARN/System.err(15326): Stack dump:
01-15 12:45:43.135: WARN/System.err(15326): 0.	Program arguments: /data/data/name.antonsmirnov.android.cppdroid/se/clang -c -g -DIDE=CppDroid /data/data/name.antonsmirnov.android.cppdroid/buildSources/project_jan14b.cpp -o /data/data/name.antonsmirnov.android.cppdroid/build/project_jan14b.cpp.o
01-15 12:45:46.659: WARN/System.err(15326): /data/data/name.antonsmirnov.android.cppdroid/se/clang returned 11

I have done `readelf` for clang executable and copied the next libs to the folder with clang executable:
libLTO.so

libc.so

libclang.so

libdl.so

libgnustl_shared.so

libm.so

libprofile_rt.so

libstdc++.so

libz.so

What file is also required?

**Comment by stuij** [comment]
Closing. This compiler fail, back from LLVM 3.3, 8 years ago, failed because clang couldn't find `as` when trying to compile an assembler file:

    01-16 12:33:33.173: WARN/System.err(18215): "as" -mfloat-abi=soft -o   /data/data/name.antonsmirnov.android.arduinodroid/build/project_jan14b.cpp.o /storage/sdcard0/arduinodroid/temp/project_jan14b-a18352.s
    01-16 12:33:33.173: WARN/System.err(18215): clang: error: unable to execute command: No such file or directory
    01-16 12:33:33.173: WARN/System.err(18215): clang: error: assembler command failed due to signal (use -v to see invocation)
