### ISSUE TITLE
clang-format: penalty for breaking double brackets for c++ attributes

### ISSUE THREAD

**Issue by mdavis199** [llvm/llvm-project#189]
There should be a penalty setting that prevents breaking the double-brackets around c++ attributes.

Using the attached `clang-format`, the following code:
```c++
int PluginColumnModel::columnCount([[maybe_unused]] const QModelIndex& parent) const {}
```

is formated as
```c++
int PluginColumnModel::columnCount([
    [maybe_unused]] const QModelIndex& parent) const {}
```

[clang-format.txt](https://github.com/llvm/llvm-project/files/4355559/clang-format.txt)

**Comment by rymiel** [comment]
Fixed by 5a4ddbd69db2b0e09398214510501d0e59a0c30b

There probably doesn't need to be a config option for this because I'd consider the two square brackets ever being broken up as a bug
