### ISSUE TITLE
crash with address_space(256)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18923]
|  |  |
| --- | --- |
| Bugzilla Link | [18549](https://llvm.org/bz18549) |
| Version | trunk |
| OS | Linux |
| Attachments | [Preprocessed source](https://user-images.githubusercontent.com/60944935/143748832-7df5e0b3-3775-44b4-80bb-06192970d544.gz), [A simpler crash](https://user-images.githubusercontent.com/60944935/143748833-12e3948e-cd67-48cd-8a5e-395789950ea9.gz), [Same issue in memset()](https://user-images.githubusercontent.com/60944935/143748834-a6ca4646-5008-44d0-ad71-ac106fe664c6.gz), [A quick fix for the issue that cannot cleanly by avoided from the .c source](https://user-images.githubusercontent.com/60944935/143748835-17555105-4b30-4b12-b1f4-2e0a13a03cb9.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @alex,@manueljacob |

## Extended Description 

Attached an example where clang-trunk crashes with an assertion, when compiling a program that makes heavy use of address_space(256):

SelectionDAGBuilder.cpp:4599: const char* llvm::SelectionDAGBuilder::visitIntrinsicCall(const llvm::CallInst&, unsigned int): Assertion `cast<PointerType>(I.getArgOperand(0)->getType())->getAddressSpace() < 256 && cast<PointerType>(I.getArgOperand(1)->getType())->getAddressSpace() < 256 && "Unknown address space"

A preliminary guess is that it's a memcpy() inserted automatically by some earlier pass.  All explicit memcpy() in the C source are with "char *" or "void *" arguments with no address_space.

It always fails for me on Linux 64 when running "clang frame-22da9c.c", apparently at any "-O" level.

**Comment by Endilll** [comment]
Both examples appear to be fixed in Clang 3.8:
https://cexplorer.testlabs.pro/z/qqoeGe
https://cexplorer.testlabs.pro/z/GoEeG9
