### ISSUE TITLE
clang fails to reject partial specializations that are less specialized than the primary template

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#18983]
|  |  |
| --- | --- |
| Bugzilla Link | [18609](https://llvm.org/bz18609) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Clang accepts this ill-formed code:

  template<typename A, typename B> struct S {};
  template<typename...Ts> struct S<Ts...> {};

This is ill-formed because the partial specialization is less specialized than the primary template. We presumably have the same bug in variable template partial specializations.

GCC and EDG get this right.

**Comment by wheatman** [comment]
This was fixed between 3.9 and 4
https://godbolt.org/z/TvbjGnb4Y

code
```
  template<typename A, typename B> struct S {};
  template<typename...Ts> struct S<Ts...> {};
```

new error message
```
<source>:2:34: error: class template partial specialization is not more specialized than the primary template [-Winvalid-partial-specialization]
  template<typename...Ts> struct S<Ts...> {};
                                 ^
<source>:1:43: note: template is declared here
  template<typename A, typename B> struct S {};
                                          ^
1 error generated.
Compiler returned: 1
```
