### ISSUE TITLE
AggressiveAntiDepBreaker.cpp:574: bool llvm::AggressiveAntiDepBreaker::FindSuitableFreeRegisters(unsigned int, llvm::AggressiveAntiDepBreaker::RenameOrderType&, std::map<unsigned int, unsigned int>&): Assertion `IsSub && "Expecting group subregister"' fai

### ISSUE THREAD

**Issue by hfinkel** [llvm/llvm-project#19037]
|  |  |
| --- | --- |
| Bugzilla Link | [18663](https://llvm.org/bz18663) |
| Version | trunk |
| OS | Linux |
| Attachments | [bugpoint reduced test case](https://user-images.githubusercontent.com/910929/143748902-d53d8f25-7d9f-417c-9b6e-1c70c6b19a0a.gz) |
| CC | @atrick,@jmolloy,@MatzeB,@rotateright,@stoklund,@uweigand |

## Extended Description 

The aggressive anti-dep breaker fails on the attached (bugpoint-reduced) input:

llc -mcpu=a2 aab-ppc-a2-bugpoint-reduced-simplified.ll
AggressiveAntiDepBreaker.cpp:574: bool llvm::AggressiveAntiDepBreaker::FindSuitableFreeRegisters(unsigned int, llvm::AggressiveAntiDepBreaker::RenameOrderType&, std::map<unsigned int, unsigned int>&): Assertion `IsSub && "Expecting group subregister"' failed.
...
2.	Running pass 'Post RA top-down list latency scheduler' on function '@_ZN4Foam3CSVINS_6VectorIdEEE4readEv'

**Comment by arsenm** [comment]
Comments suggest this is fixed and not reproducible
