### ISSUE TITLE
-ftrapping-math flag ignored in optimization

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19047]
|  |  |
| --- | --- |
| Bugzilla Link | [18673](https://llvm.org/bz18673) |
| Version | 3.4 |
| OS | Linux |
| Attachments | [the test case](https://user-images.githubusercontent.com/60944935/143748908-b5411df6-ca2b-4a2d-9ec9-73cbff89e0cb.gz), [modified test case for Mac Darwin](https://user-images.githubusercontent.com/60944935/143748909-65a68743-d218-4373-b5f1-36d1aeb6398c.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @andykaylor,@emaste,@hfinkel,@CarlosAlbertoEnciso,@RKSimon,@urnathan,@rotateright,@wjristow,@yuanfang-chen |

## Extended Description 

I recently installed the clang 3.4 release (from source, downloaded from the llvm download page) on my 64-bit openSUSE 13.1 system. When I compiled the code I develop, I noticed that it crashed almost immediately on an FP exception. The same code ran fine under clang 3.3. I could reduce the problem to the attached program.

If you compile this program with

% clang++ -O2 -ftrapping-math bug.cc
% ./a.out 
0
Floating exception

Compiling at a lower level gives the correct result:

% clang++ -O1 -ftrapping-math bug.cc
% ./a.out
0
1e+300

You need to supply the input value 0 on the command line to prevent the compiler from pre-computing the result at compile time.

By inspecting the assembly, it appears that the compiler implements the division more or less as

1./max(x,1.e-300) -> min(1./x,1e300)

However, such an optimization is not allowed when -ftrapping-math is in effect since it will spuriously crash the program when x is zero.

**Comment by efriedma-quic** [comment]
FENV_ACCESS should work with current clang.
