### ISSUE TITLE
Support formatting json files

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#19073]
|  |  |
| --- | --- |
| Bugzilla Link | [18699](https://llvm.org/bz18699) |
| Version | trunk |
| OS | All |

## Extended Description 
json is a javascript object literal. Supporting these in clang-format should be trivial, just assume that toplevel '{'s in .json files start expressions, not blocks.

**Comment by mydeveloperday** [comment]
https://reviews.llvm.org/D93528 landed in commit 8b7881a084d0bc26499cf93e4ac45b59257a03b3
