### ISSUE TITLE
llc segfaults on custom bc

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19078]
|  |  |
| --- | --- |
| Bugzilla Link | [18704](https://llvm.org/bz18704) |
| Version | 3.3 |
| OS | Linux |
| Attachments | [the file that causes the crash](https://user-images.githubusercontent.com/60944935/143748924-d15195f6-be31-4f83-ae2b-6f200d81dc97.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @rnk,@silvasean |

## Extended Description 

I am tinkering with making my own compiler for my own language. Attached is a bc file my frontend generates. This may be invalid input, but llc does not give any error print besides a backtrace and segfault, so I can't figure out where my error is if there is one.
I tried running the attached bc through llc and it crashed. bugpoint also segfaults on the file.

Printed backtrace:
0  libLLVM-3.3.so.1 0x00002b843f3de382 llvm::sys::PrintStackTrace(_IO_FILE*) + 34
1  libLLVM-3.3.so.1 0x00002b843f3de711
2  libpthread.so.0  0x00002b843fe2fcb0
3  libLLVM-3.3.so.1 0x00002b843eae2a98 llvm::BitcodeReader::ParseFunctionBody(llvm::Function*) + 1672
4  libLLVM-3.3.so.1 0x00002b843eae7465 llvm::BitcodeReader::Materialize(llvm::GlobalValue*, std::string*) + 309
5  libLLVM-3.3.so.1 0x00002b843eae170d llvm::BitcodeReader::MaterializeModule(llvm::Module*, std::string*) + 77
6  libLLVM-3.3.so.1 0x00002b843ed459fb llvm::Module::MaterializeAllPermanently(std::string*) + 27
7  libLLVM-3.3.so.1 0x00002b843eae23e9 llvm::ParseBitcodeFile(llvm::MemoryBuffer*, llvm::LLVMContext&, std::string*) + 41
8  libLLVM-3.3.so.1 0x00002b843ede4b2c llvm::ParseIR(llvm::MemoryBuffer*, llvm::SMDiagnostic&, llvm::LLVMContext&) + 396
9  libLLVM-3.3.so.1 0x00002b843ede51c9 llvm::ParseIRFile(std::string const&, llvm::SMDiagnostic&, llvm::LLVMContext&) + 761
10 llc              0x000000000040a044
11 llc              0x0000000000409a81 main + 385
12 libc.so.6        0x00002b844036976d __libc_start_main + 237
13 llc              0x0000000000409af1
Stack dump:
0.	Program arguments: llc example.bc -o - 
Segmentation fault (core dumped)

**Comment by arsenm** [comment]
Last comment says fixed
