### ISSUE TITLE
Cannot build lld with '-DBUILD_SHARED_LIBS=ON

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19197]
|  |  |
| --- | --- |
| Bugzilla Link | [18823](https://llvm.org/bz18823) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @Bigcheese |

## Extended Description 
CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "lldCore" of type SHARED_LIBRARY
    depends on "lldNative" (weak)
    depends on "lldReaderWriter" (weak)
    depends on "lldPasses" (weak)
    depends on "lldYAML" (weak)
  "lldPasses" of type SHARED_LIBRARY
    depends on "lldReaderWriter" (weak)
    depends on "lldCore" (weak)
    depends on "lldNative" (weak)
    depends on "lldYAML" (weak)
  "lldReaderWriter" of type SHARED_LIBRARY
    depends on "lldCore" (weak)
    depends on "lldNative" (weak)
    depends on "lldYAML" (weak)
    depends on "lldPasses" (weak)
  "lldNative" of type SHARED_LIBRARY
    depends on "lldReaderWriter" (weak)
    depends on "lldCore" (weak)
    depends on "lldYAML" (weak)
    depends on "lldPasses" (weak)
  "lldYAML" of type SHARED_LIBRARY
    depends on "lldReaderWriter" (weak)
    depends on "lldCore" (weak)
    depends on "lldNative" (weak)
    depends on "lldPasses" (weak)

**Comment by arsenm** [comment]
Old build issue
