### ISSUE TITLE
Fabricator wants Flash. It shouldn't.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19216]
|  |  |
| --- | --- |
| Bugzilla Link | [18842](https://llvm.org/bz18842) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @chandlerc |

## Extended Description 
llvm-reviews.chandlerc.com prompts to install flash, but then works fine when I tell it "no". It should not even try. Flash shouldn't be required, or even optional, for that stuff.

**Comment by tlattner** [comment]
No longer an issue.
