### ISSUE TITLE
Infinite loop in AlwaysInliner pass

### ISSUE THREAD

**Issue by e5a3e8f3-eb3a-4805-b780-9eacefb4a0c1** [llvm/llvm-project#19329]
|  |  |
| --- | --- |
| Bugzilla Link | [18955](https://llvm.org/bz18955) |
| Version | trunk |
| OS | Linux |
| Attachments | [The two modules mentioned.](https://user-images.githubusercontent.com/93435900/143749075-dc770a31-d69b-45ca-863f-00fb2c711f6f.gz) |
| CC | @chandlerc,@ekatz,@hfinkel |

## Extended Description 
Attached is a tarball of two LLVM code modules which are nearly identical. When running

opt -O2 -o bad.bc bad.ll

opt rapidly consumes GiB's of memory and seems to run indefinitely (>10min). When running

opt -O2 -o good.bc good.ll

opt exits quickly. The difference between the two modules is 599 removals of the alwaysinline function attribute; therefore I believe the problem is in the AlwaysInliner pass. I also wrote code to only run the AlwaysInliner pass, and that produced the same result.

I have also experimentally observed this bug in the LLVM 3.4 and LLVM 3.0 releases.

**Comment by arsenm** [comment]
Last comment was asking for fresh reproducer
