### ISSUE TITLE
wrong code by LTO at -O0 on x86_64-linux-gnu

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#19358]
|  |  |
| --- | --- |
| Bugzilla Link | [18984](https://llvm.org/bz18984) |
| Version | trunk |
| OS | All |
| CC | @hfinkel |

## Extended Description 
The current clang trunk miscompiles the following code when using LTO at -O0 on x86_64-linux-gnu (in both 32-bit and 64-bit modes). 

$ clang-trunk -v
clang version 3.5 (trunk 202330)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -O0 small.c; a.out
$ clang-trunk -flto -O1 small.c; a.out
$     
$ clang-trunk -flto -O0 small.c; a.out
Aborted (core dumped)
$ 

----------------------

int a, b, d, *e = &d; 
int volatile c = 1;

void
foo (int *p)
{
  int f = 0;
  for (; b < 1; b++)
    {
      e = p;
      if (c)
	{
	  if (f)
	    ;
	  break;
	}
      if (c)
	break;
    }
  if (!e) 
    __builtin_abort(); 
}

int
main ()
{
  foo (&a);
  return 0;
}

**Comment by fhahn** [comment]
I was unable to reproduce this with Clang 4.0 or newer (https://godbolt.org/z/vcdsvdfxx). earlier versions of clang don't seem to work with LTO on godbolt.
