### ISSUE TITLE
Repeated AST node for attributes

### ISSUE THREAD

**Issue by Abramo-Bagnara** [llvm/llvm-project#19374]
|  |  |
| --- | --- |
| Bugzilla Link | [19000](https://llvm.org/bz19000) |
| Version | trunk |
| OS | Linux |
| CC | @AaronBallman |

## Extended Description 
$ cat z.c
void __attribute__((noinline,noreturn))
f(void);
$ _clang -cc1 -ast-dump z.c
TranslationUnitDecl 0x6630730 <<invalid sloc>>
|-TypedefDecl 0x6630c30 <<invalid sloc>> __int128_t '__int128'
|-TypedefDecl 0x6630c90 <<invalid sloc>> __uint128_t 'unsigned __int128'
|-TypedefDecl 0x6630fe0 <<invalid sloc>> __builtin_va_list
'__va_list_tag [1]'
`-FunctionDecl 0x6631120 <z.c:1:1, line:2:7> f 'void (void)
__attribute__((noreturn))'
  |-NoInlineAttr 0x66311c0 <line:1:21>
  `-NoInlineAttr 0x6631200 <col:21>
$ clang -cc1 -ast-print z.c
void f() __attribute__((noinline)) __attribute__((noinline));

The NoInlineAttr node is added twice.

**Comment by davidbolvansky** [comment]
Fixed since Clang 7
