### ISSUE TITLE
"memory read -size" should explicitly reject invalid value

### ISSUE THREAD

**Issue by emaste** [llvm/llvm-project#19387]
|  |  |
| --- | --- |
| Bugzilla Link | [19013](https://llvm.org/bz19013) |
| Version | unspecified |
| OS | FreeBSD |

## Extended Description 
I accidentally ended up with an extra - before a memory read -size option, and the error message is non-obvious:

(lldb) memory read -size -4 -format hex -count 4 0x100150
error: Normally, 'memory read' will not read over 1024 bytes of data.
error: Please use --force to override this restriction just once.
error: or set target.max-memory-read-size if you will often need a larger limit.

**Comment by RamNalamothu** [comment]
The latest lldb generates a meaningful error as follows.

`(lldb) memory read --size -4 -format hex -count 1 0x0000555555558010`
`error: invalid uint64_t string value: '-4'`

Checked with:
`lldb version 15.0.0git (git@github.com:llvm/llvm-project.git revision cc2139524f77248c7e147d4cc3befb31fe3e6daa)`
