### ISSUE TITLE
wrong code (that hangs) by LTO at -O0 on x86_64-linux-gnu

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#19400]
|  |  |
| --- | --- |
| Bugzilla Link | [19026](https://llvm.org/bz19026) |
| Version | trunk |
| OS | All |
| CC | @dexonsmith |

## Extended Description 
The current clang trunk miscompiles the following code when using LTO at -O0 on x86_64-linux-gnu (in both 32-bit and 64-bit modes). The generated code hangs. 

This may be related to http://llvm.org/bugs/show_bug.cgi?id=18984. 

$ clang-trunk -v
clang version 3.5 (trunk 202589)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -O0 small.c; a.out
$ clang-trunk -flto -O1 small.c; a.out
$ 
$ clang-trunk -flto -O0 small.c
$ a.out
^C
$ 

-------------------------

int a;

int
main ()
{
  int b = 0;
  for (; a < 1; a++)
    if (!b && b)
      ;
  return 0;
}

**Comment by fhahn** [comment]
I am unable to reproduce this on current main. I'll close the issue, but please re-open it again with additional info if it still reproduces on your side.
