### ISSUE TITLE
clang 3.4 aborts when compiling dlaed3_ function in Numeric-24.2 on i386 with -fPIC -march=athlon64

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19403]
|  |  |
| --- | --- |
| Bugzilla Link | [19029](https://llvm.org/bz19029) |
| Version | 3.4 |
| OS | FreeBSD |
| Attachments | [run script](https://user-images.githubusercontent.com/60944935/143749114-d984303a-be3b-484d-955b-5b75f01f2b64.gz), [preprocessed source](https://user-images.githubusercontent.com/60944935/143749115-b7089d48-8046-457d-8ffb-f04b9ea45e11.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DimitryAndric,@hfinkel,@jmolloy,@zygoloid |

## Extended Description 
When attempting to compile the dlapack_lite.c file in the python Numeric-24.2 module, clang aborts when it encounters the dlaed3_() function if -march=athlon64 is specified.  Clang does not abort without -march=athlon64.

# cc -c -O2 -fno-strict-aliasing -fPIC -march=athlon64 dlaed3_.c
Instruction does not dominate all uses!
  %arrayidx106 = getelementptr inbounds double* %dlamda, i32 %sub83
  %bound1492 = icmp ule double* %arrayidx106, %scevgep473
Instruction does not dominate all uses!
  %arrayidx106 = getelementptr inbounds double* %dlamda, i32 %sub83
  %bound0491 = icmp ule double* %scevgep471, %arrayidx106
Broken module found, compilation aborted!
Stack dump:
0.	Program arguments: /usr/bin/cc -cc1 -triple i386-unknown-freebsd11.0 -emit-obj -disable-free -main-file-name dlaed3_.c -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -relaxed-aliasing -masm-verbose -mconstructor-aliases -target-cpu athlon64 -coverage-file /usr/ports/math/py-numeric/work/Numeric-24.2/Src/dlaed3_.o -resource-dir /usr/bin/../lib/clang/3.4 -O2 -fdebug-compilation-dir /usr/ports/math/py-numeric/work/Numeric-24.2/Src -ferror-limit 19 -fmessage-length 191 -mstackrealign -fobjc-runtime=gnustep -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o dlaed3_.o -x c dlaed3_.c 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'dlaed3_.c'.
4.	Running pass 'Module Verifier' on function '@dlaed3_'
cc: error: unable to execute command: Abort trap (core dumped)
cc: error: clang frontend command failed due to signal (use -v to see invocation)
FreeBSD clang version 3.4 (tags/RELEASE_34/final 197956) 20140216
Target: i386-unknown-freebsd11.0
Thread model: posix
cc: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
cc: note: diagnostic msg: 
********************

**Comment by artagnon** [comment]
As mentioned, the bug is fixed, and I have verified that it no longer reproduces.
