### ISSUE TITLE
GEP on struct pointer obtained from bitcast canonicalized incorrectly

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19422]
|  |  |
| --- | --- |
| Bugzilla Link | [19048](https://llvm.org/bz19048) |
| Version | trunk |
| OS | Linux |
| Attachments | [Misoptimized testcase](https://user-images.githubusercontent.com/60944935/143749129-e939d83b-b8b2-4575-a2f3-6ac898b15554.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

In the attached code, if a datalayout declaration is present the instructions

  %variant_source = bitcast i16* %dataload_case_ptr to { i16, i64 }*
  %8 = getelementptr inbounds { i16, i64 }* %variant_source, i32 0, i32 1
  %9 = load i64* %8
  store i64 %9, i64* %1, align 8

get transformed by opt -O3 into

  %6 = getelementptr inbounds i16* %5, i64 4
  %7 = bitcast i16* %6 to i64*
  %8 = load i64* %7, align 8
  store i64 %8, i64* %1, align 8

If the datalayout is removed, the bitcast is instead deleted entirely and retains the correct GEP form, at which point returning the datalayout once more and re-optimizing correctly reduces the entire function to 'ret i8 1', which is ideally what would happen regardless. Presumably the noncanonical form interferes with further optimizations.

**Comment by arsenm** [comment]
Pointer bitcasts are no longer relevant, opaquified testcase does fold to ret i8 1
