### ISSUE TITLE
Add support for indenting class members and methods one level under the modifiers

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19430]
|  |  |
| --- | --- |
| Bugzilla Link | [19056](https://llvm.org/bz19056) |
| Version | 3.4 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @3nids,@Budovi,@m-kuhn,@mydeveloperday |

## Extended Description 
I want to have this formatting after running clang-format:

```
class AClass
{
    public:
        AClass()
        {
            int a=5;
        }
    protected:
        int m_Member;
};
```

The config file I'm using looks something like this:
```
BasedOnStyle: LLVM
AccessModifierOffset: 0
ColumnLimit: 100
IndentCaseLabels: true
IndentWidth: 4
TabWidth: 4
SpaceAfterControlStatementKeyword: true
UseTab: Never
BreakBeforeBraces: Allman
```

So in essence what I want is modifiers (private, protected, public) to be indented one level from the class/struct and the members/methods of the class to be indented one level from the modifiers.

**Comment by mydeveloperday** [comment]
Closing this issue as it was landed in 2a42c759ae7bb09dd448d188138f310d014fcab6
