### ISSUE TITLE
wrong code (that segfaults) by LTO at -O1 and above on x86_64-linux-gnu

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#19436]
|  |  |
| --- | --- |
| Bugzilla Link | [19062](https://llvm.org/bz19062) |
| Version | trunk |
| OS | All |
| CC | @hfinkel |

## Extended Description 
The current clang trunk miscompiles the following code when using LTO at -O1 and above on x86_64-linux-gnu (in both 32-bit and 64-bit modes). 

$ clang-trunk -v
clang version 3.5.0 (trunk 202978)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -O1 small.c; a.out
$ clang-trunk -flto -O0 small.c; a.out
$ 
$ clang-trunk -flto -O1 small.c; a.out
Segmentation fault (core dumped)
$ 

------------------------------------

int *a, **volatile b = &a, **c = &a, d, e;

void __assert_fail (void) __attribute__ ((__noreturn__));

int
main ()
{
  for (; d < 1; d++)
    {
      *b = &e;
      if (!a)
        __assert_fail ();
      **c = 0;
    }
  return 0;
}

**Comment by fhahn** [comment]
I was unable to reproduce this with Clang 4.0 or newer (https://godbolt.org/z/va9Tn5Kxr). earlier versions of clang don't seem to work with LTO on godbolt.
