### ISSUE TITLE
wrong code by LTO at -O0 on x86_64-linux-gnu in 64-bit mode

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#19447]
|  |  |
| --- | --- |
| Bugzilla Link | [19073](https://llvm.org/bz19073) |
| Version | trunk |
| OS | All |
| CC | @hfinkel |

## Extended Description 
The current clang trunk miscompiles the following code when using LTO at -O0 on x86_64-linux-gnu in 64-bit mode (but not 32-bit mode). 

$ clang-trunk -v
clang version 3.5.0 (trunk 203119)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -O0 f.c main.c
$ a.out
1
$ clang-trunk -flto -m32 -O0 f.c main.c
$ a.out
1
$ clang-trunk -flto -m64 -O1 f.c main.c
$ a.out
1
$ 
$ clang-trunk -flto -m64 -O0 f.c main.c
$ a.out
0
$ 
$           
$ cat f.c 
extern int a, b, d, e, g;
extern long f;

static int
fn1 (int p)
{
  return b ? 0 : p;
}

int
fn2 ()
{
  int h = 1;
  e = d + 1;
  if (fn1 (e < 0))
    for (h = 0; h;)
      ;
  else
    {
      int i = 0, j = 0;
      g = a ? 0 : i;
      f = g;
      if (f || j || j || f >> j)
	;
      for (d = 1; d; d = (char) d + 1)
	;
    }
  return h;
}
$ cat main.c
extern int printf (const char *, ...);
extern int fn2 ();

int a, b, c, d, e, g, k;
long f;

int
main ()
{
  k = fn2 ();
  if (k)
    c = 1;
  printf ("%d\n", c);
  return 0;
}

**Comment by fhahn** [comment]
I am unable to reproduce this on current main. The bug likely has been fixed. I'll close the issue, but please re-open it again with additional info if it still reproduces on your side.
