### ISSUE TITLE
-Wdocumentation-unknown-command requires -Wdocumentation

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19442]
|  |  |
| --- | --- |
| Bugzilla Link | [19068](https://llvm.org/bz19068) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@seanm |

## Extended Description 
Take the following program where an unknown Doxygen command is used:

/**
 * \unknown unknowns
 */
int main() {}

Compiling with clang r201876 and only -Wdocumentation-unknown-command results in no warning at all. It is necessary to compile with both -Wdocumentation-unknown-command -Wdocumentation to get the expected warning:

% ~/LLVM/build/Release+Asserts/bin/clang++ -Wdocumentation-unknown-command -Wdocumentation clang.cpp
clang.cpp:2:4: warning: unknown command tag name [-Wdocumentation-unknown-command]
 * \unknown     Unknown.
   ^
1 warning generated.

While it can be expected that users who use -Wdocumentation-unknown-command will also use -Wdocumentation, this behavior is still surprising.

**Comment by wheatman** [comment]
This was fixed between 3.6 and 3.7
https://godbolt.org/z/caW3sq5fs

code compiled with `-Wdocumentation-unknown-command`
```
/**
 * \unknown unknowns
 */
int main() {}
```

new warning
```
<source>:2:4: warning: unknown command tag name [-Wdocumentation-unknown-command]
 * \unknown unknowns
   ^
1 warning generated.
```
