### ISSUE TITLE
Alignment Enhancements

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19441]
|  |  |
| --- | --- |
| Bugzilla Link | [19067](https://llvm.org/bz19067) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @Trass3r |

## Extended Description 
Below are some cases where I'd like to see clang-format align (tabulate really) the code differently than it does today (as options of course).  

1) Consecutive #defines:

#define Name       0x1
#define LongerName 0x2
#define OtherName  3

2) consecutive assignment:

name       = 3;
longerName = 400;
other      = 5;

3) Some sort of alignment specification for consecutive declaration:

[<static/extern>] <type> [<const>] <variable name> [= <initialization>];

group declarations with the same storage class and cv-qualifier, seperating declarations that don't match (see example 3).

Examples of what I'm thinking:

ex 1:
  int  name = 4;
  long blah = 5;

ex 2:
  int  const cname = 6;
  long const cblah;

ex 3:
  static short const a = 8;
  static long  const b = 9;

  long const c = 10; // if there was no space above this line, then (optionally) insert one

4) similar to (3), but with function parameter list, and without storage class/const matching requirement:

Function(short const a,
         long        b,
         ...

5) consecutive output/input lines:

std::cout << "Name:"      << Name      << std::endl;
std::cout << "OtherName:" << OtherName << std::endl;

std::cin >> Name;
std::cin >> OtherName;

6) it would also be nice to be able to specify left/right justification for each column in the above cases.

I wouldn't mind taking a crack at these myself, but I wanted to first know if this sort of thing is intended in the clang-format scope, and if so, get some input as to the best way to approach it.

**Comment by mydeveloperday** [comment]
This issue is a laundry list of wishes, we can't process this bug effectively, if you still require elements from this very old issue then I respectfully as that we log them separately. Especially as many of your requests have been done already.

I'm closing this as won't fix (meaning won't likely fix all of it)
