### ISSUE TITLE
LTO linking error on x86_64-linux-gnu (affecting the current trunk, but not 3.4 and earlier versions)

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#19453]
|  |  |
| --- | --- |
| Bugzilla Link | [19079](https://llvm.org/bz19079) |
| Version | trunk |
| OS | All |
| CC | @hfinkel |

## Extended Description 
The following code causes a linker error when it is compiled on x86_64-linux-gnu by the current clang trunk using LTO in 64-bit mode, but not in 32-bit mode. 

$ clang-trunk -v
clang version 3.5.0 (trunk 203239)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -O0 fn1.c fn2.c main.c
$ a.out
$ 
$ clang-trunk -flto -O0 -c fn2.c
$ clang-trunk -flto -O1 -c fn1.c
$ clang-trunk -flto -O1 -c main.c
$ clang-trunk -flto -O1 fn1.o fn2.o main.o
ld: /tmp/llvm/include/llvm/Support/Casting.h:240: typename cast_retty<X, Y *>::ret_type llvm::cast(Y *) [X = llvm::PHINode, Y = llvm::Instruction]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
clang: error: unable to execute command: Aborted (core dumped)
clang: error: linker command failed due to signal (use -v to see invocation)
$ 
$ cat fn1.c 
extern int a, b, c, i, f;

void
fn1 ()
{
  int j = 0, k = 1;
  for (; k; k = 0)
    {
      if (i)
	continue;
      for (; j < 1; j++)
	;
    }
lbl:
  for (; b < 1; b++)
    {
      if (c)
	continue;
      for (;;)
	if (a & 1)
	  {
	    if (j)
	      goto lbl;
	    f--;
	  }
    }
}
$ cat fn2.c
extern int a, c, d, e[1], f;

extern void fn1 ();

void
fn2 (void)
{
  int g[1] = {0};
  int h = 1;
  for (;;)
    {
      for (; h < 1; h++)
	if (g[0])
	  fn1 ();
      for (; a < 1; a++)
	for (; d < 1; d++)
	  ;
      if (e[0])
	break;
      c = 0;
    }
}
$ cat main.c
extern void fn2 ();

int a, b, c = 1, d, e[1] = {1}, f, i;

int
main ()
{
  fn2 ();
  return 0;
}

**Comment by MaskRay** [comment]
`clang -flto -O1 fn1.c fn2.c main.c; ./a.out` works fine.
