### ISSUE TITLE
wrong code by LTO at -O0 and -O1 on x86_64-linux-gnu (both 32-bit and 64-bit modes)

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#19452]
|  |  |
| --- | --- |
| Bugzilla Link | [19078](https://llvm.org/bz19078) |
| Version | trunk |
| OS | All |
| CC | @hfinkel,@zygoloid,@yuanfang-chen |

## Extended Description 
The current clang trunk miscompiles the following code when using LTO at -O0 and -O1 (but not at -Os and above) on x86_64-linux-gnu (in both 32-bit and 64-bit modes). 

$ clang-trunk -v
clang version 3.5.0 (trunk 203239)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -O0 small.c; a.out
-1
$ clang-trunk -flto -Os small.c; a.out
-1
$             
$ clang-trunk -flto -O0 small.c; a.out
0
$ clang-trunk -flto -O1 small.c; a.out
0
$ 

---------------------------------

int printf (const char *, ...);

int a, b, c, d = 1, e, g, h;
short f;

int
fn1 (int p1, int p2)
{
  return -p2 < 0 ? 0 : p2;
}

int
fn2 ()
{
  return b = 0;
}

void
fn3 (int p)
{
  int i, j = d = 0;
  i = 1 ? 1 : 0;
  f = j || j || 0 > j ? 0 : j;
  if (!(1 & i && f))
    {
      if (g)
	;
      for (g = 0; g != 1; g++)
	{
	  g || fn1 (fn2 (), p);
	  if (!d)
	    {
	      e = g || a;
	      break;
	    }
	}
      for (h = -1; c >= 0; c = h)
	if (g)
	  break;
    }
}

int
main ()
{
  fn3 (1);
  printf ("%d\n", c);
  return 0;
}

**Comment by fhahn** [comment]
I was unable to reproduce this with Clang 4.0 or newer (https://godbolt.org/z/r4b3aWM54). earlier versions of clang don't seem to work with LTO on godbolt.
