### ISSUE TITLE
Formatting of the chained ternary operator

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19456]
|  |  |
| --- | --- |
| Bugzilla Link | [19082](https://llvm.org/bz19082) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @EdSchouten,@nico |

## Extended Description 
There is a (not that often used, but still present) pattern-matching-inspired idiom in C and C++ that uses the ternary operator like this:

```
const int j = (someTestValue < 1) ? 0 :
              (someTestValue < 3) ? 2 :
              (someTestValue < 5) ? 3 :
              (someTestValue < 7) ? 4 :
                                    5 ;
```

This is (for some) a preferred way of writing this type of constructs (as opposed to if/else/if/else chains).

clang-format formats this as a chain of ?: instead of looking at it as a single construct. When applied to the above code, it produces:

```
    const int j =
        (someTestValue < 1) ? 0 : (someTestValue < 3)
                                      ? 2
                                      : (someTestValue < 5)
                                            ? 3
                                            : (someTestValue < 7) ? 4 : 5;
```

--

Or turns this:
```
    const int j = (v < 1) ? 0 :
                  (v < 3) ? 2 :
                  (v < 5) ? 3 :
                  (v < 7) ? 4 :
                            5 ;

```
Into this:
`    const int j = (v < 1) ? 0 : (v < 3) ? 2 : (v < 5) ? 3 : (v < 7) ? 4 : 5;`

significantly reducing readability.

**Comment by mydeveloperday** [comment]
clang-format v13 and above formats as the following:

```
const int j = (someTestValue < 1)   ? 0
              : (someTestValue < 3) ? 2
              : (someTestValue < 5) ? 3
              : (someTestValue < 7) ? 4
                                    : 5;
```

I'm closing this issue, feel free to reopen the issue if it doesn't cover your needs
