### ISSUE TITLE
Weird (likely bugged) error diagnostic when reusing builtin name

### ISSUE THREAD

**Issue by Abramo-Bagnara** [llvm/llvm-project#19457]
|  |  |
| --- | --- |
| Bugzilla Link | [19083](https://llvm.org/bz19083) |
| Version | trunk |
| OS | Linux |
| CC | @jryans |

## Extended Description 
$ cat z.c
int printf;
$ clang -c z.c
z.c:1:5: error: redefinition of 'printf' as different kind of symbol
int printf;
    ^
z.c:1:5: note: previous definition is here
1 error generated.

The message about previous definition is definitely misleading.

That apart I'm not sure that to treat this as a fatal error is the right thing to do.

FWIW:
$ gcc -c z.c
z.c:1:5: warning: built-in function ‘printf’ declared as non-function [enabled by default]
 int printf;
     ^

**Comment by AaronBallman** [comment]
Closing as duplicate of #15523
