### ISSUE TITLE
wrong code by LTO at -Os and above on x86_64-linux-gnu (both 32-bit and 64-bit modes)

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#19467]
|  |  |
| --- | --- |
| Bugzilla Link | [19093](https://llvm.org/bz19093) |
| Version | trunk |
| OS | All |
| CC | @hfinkel |

## Extended Description 
The current clang trunk miscompiles the following code when using LTO at -Os and above on x86_64-linux-gnu (in both 32-bit and 64-bit modes). 

$ clang-trunk -v
clang version 3.5.0 (trunk 203396)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -Os small.c; a.out
1
$ clang-trunk -flto -O1 small.c; a.out
1
$ 
$ clang-trunk -flto -Os small.c; a.out
0
$ 

---------------------------------

int printf (const char *, ...);

int a[2], b = 2, c, *d = &c, **e = &d, ***f = &e, *g = &b, *h = &b, i;

static int
fn1 ()
{
  for (c = 2; c; c--)
    for (;;)
      {
	*g &= **e;
	for (; i; i++)
	  ;
	if (*h)
	  break;
	return 0;
      }
  return 0; 
}

int
main ()
{
  a[1] = 1;
  fn1 ();
  printf ("%d\n", a[c]);
  return 0;
}

**Comment by fhahn** [comment]
I was unable to reproduce this with Clang 11.0 or newer (https://godbolt.org/z/EhnazfM5j). earlier versions of clang don't seem to work with LTO on godbolt and the `-Os` option.
