### ISSUE TITLE
wrong code (that segfaults) by LTO at -O2 and -O3 on x86_64-linux-gnu

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#19483]
|  |  |
| --- | --- |
| Bugzilla Link | [19109](https://llvm.org/bz19109) |
| Version | trunk |
| OS | All |
| CC | @hfinkel |

## Extended Description 
The current clang trunk miscompiles the following code when using LTO at -O2 and -O3 on x86_64-linux-gnu (in both 32-bit and 64-bit modes). 

This is likely related to http://llvm.org/bugs/show_bug.cgi?id=19062. 

$ clang-trunk -v
clang version 3.5.0 (trunk 203564)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -O2 small.c; a.out
$ clang-trunk -flto -Os small.c; a.out
$      
$ clang-trunk -flto -O2 small.c  
$ a.out
a.out: small.c:13: void foo(): Assertion `a == 0' failed.
Aborted (core dumped)
$ 

-------------------------------

#include <assert.h>

int *a, **volatile b = &a, c, *d = &c, *e = &c, **f = &a, g; 

void
foo ()
{
  for (;;)
    {
      assert (a == 0);
      *f = &g;
      *b = 0;
      assert (a == 0);
      *f = 0;
      if (*e)
	break;
    }
}

int
main ()
{
  *d = 1;
  assert (a == 0);
  foo ();
  return 0;
}

**Comment by fhahn** [comment]
I am unable to reproduce this on current main. The bug likely has been fixed. I'll close the issue, but please re-open it again with additional info if it still reproduces on your side.
