### ISSUE TITLE
wrong code (that segfaults) by LTO at all optimization levels (affecting 3.2 till trunk)

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#19512]
|  |  |
| --- | --- |
| Bugzilla Link | [19138](https://llvm.org/bz19138) |
| Version | trunk |
| OS | All |
| CC | @hfinkel |

## Extended Description 
The current clang trunk miscompiles the following code when using LTO at all optimization levels (-O0 to -O3) on x86_64-linux-gnu (in both 32-bit and 64-bit modes).  

It also affects clang 3.2, 3.3, and 3.4. 

$ clang-trunk -v
clang version 3.5.0 (trunk 203791)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -O0 small.c; a.out
$ 
$ clang-trunk -flto -O0 small.c
$ a.out
a.out: small.c:11: int main(): Assertion `b == &a' failed.
Aborted (core dumped)
$ 

---------------------------------

#include <assert.h>

int a, *b, **volatile c = &b, *d = &a;

int
main ()
{
  for (a = 0; a < 1; a++)
    {
      *c = d;
      assert(b == &a);
    }
  return 0;
}

**Comment by fhahn** [comment]
I was unable to reproduce this with Clang 4.0 or newer (https://godbolt.org/z/oKohEaWs4). earlier versions of clang don't seem to work with LTO on godbolt.
