### ISSUE TITLE
When configparser-3.2.0 is installed, LLVM-3.4 won't compile

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19528]
|  |  |
| --- | --- |
| Bugzilla Link | [19154](https://llvm.org/bz19154) |
| Version | 3.4 |
| OS | Linux |
| Attachments | [A build-log, showing the build failure.](https://user-images.githubusercontent.com/60944935/143749181-e4d76eb5-f087-433c-a454-84e05bf05053.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

The package configparser is a backport of python3's ConfigParser to python2. When version 3.2.0 is installed, LLVM-3.4 fails to build, because the parsing of LLVMBuild.txt files fails. The user visible error is LLVM not being able to find a target to build (can be seen in attached log).

When version 3.3 of configparser is installed, or configparser is not installed at all, LLVM-3.4 compiles without error. Either the build system should ensure version 3.2 is not installed, or whatever issue is causing this should be fixed. I'm unsure of how, or why configparser-3.2 causes the parsing issue. This was not an issue in llvm-3.3, because ConfigParser (built-in to python) was always used.

Some more details are provided at a gentoo bug report, https://bugs.gentoo.org/show_bug.cgi?id=500856

**Comment by arsenm** [comment]
Old build problem, linked gentoo issue is marked as fixed
