### ISSUE TITLE
wrong code by LTO at -O3 on x86_64-linux-gnu (affecting 3.4 and trunk)

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#19520]
|  |  |
| --- | --- |
| Bugzilla Link | [19146](https://llvm.org/bz19146) |
| Version | trunk |
| OS | All |
| CC | @hfinkel |

## Extended Description 
The current clang trunk and 3.4 miscompile the following code when using LTO at -O3 on x86_64-linux-gnu (in both 32-bit and 64-bit modes). 

This is regression from 3.3. 

$ clang-trunk -v
clang version 3.5.0 (trunk 203921)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -O3 small.c; a.out
-1
$ clang-trunk -flto -O2 small.c; a.out
-1
$ clang-3.3 -flto -O3 small.c; a.out
-1
$ 
$ clang-trunk -flto -O3 small.c; a.out
0
$ clang-3.4 -flto -O3 small.c; a.out
0
$ 

---------------------------------

int printf (const char *, ...);

int j, k, l, m[2], v, a;

int
main ()
{
  int s = m[0] = j = 0;

  for (; j >= 0; --j)
    {
      a = k >= 0 || s ? 0 : k;
      l = a >= 0;
      if (m[1])
	break;
      s = l;
    }

  k = printf ("%d\n", j);

  for (; v < 1; v++)
    m[v] = 0;

  return 0;
}

**Comment by fhahn** [comment]
I was unable to reproduce this with Clang 4.0 or newer (https://godbolt.org/z/Gbs3jsaqj). earlier versions of clang don't seem to work with LTO on godbolt.
