### ISSUE TITLE
llvm-config.cpp:45:10: fatal error: 'LibraryDependencies.inc' file not found

### ISSUE THREAD

**Issue by 70311826-e6d8-4d29-8604-c4ec4bfa7f0d** [llvm/llvm-project#19532]
|  |  |
| --- | --- |
| Bugzilla Link | [19158](https://llvm.org/bz19158) |
| Version | 3.4 |
| OS | Linux |

## Extended Description 
I fetched Clang 3.4 with the recipe below. I'm hitting an error while attempting to compile:

llvm-config.cpp:45:10: fatal error: 'LibraryDependencies.inc' file not found #include "LibraryDependencies.inc"

Full ouptut is:

llvm[1]: Compiling llvm-config.cpp for Release+Asserts build
llvm-config.cpp:45:10: fatal error: 'LibraryDependencies.inc' file not found
#include "LibraryDependencies.inc"
         ^
1 error generated.
/bin/rm: cannot remove `/home/jwalton/scratch-llvm/llvm-3.4/tools/llvm-config/Release+Asserts/llvm-config.d.tmp': No such file or directory
make[1]: *** [/home/jwalton/scratch-llvm/llvm-3.4/tools/llvm-config/Release+Asserts/llvm-config.o] Error 1
make[1]: Leaving directory `/home/jwalton/scratch-llvm/llvm-3.4/tools/llvm-config'
make: *** [all] Error 1

Sure enough, its missing:

$ find . -iname LibraryDependencies.inc
$

I've run through the recipe three or four times in the past, so I know it used to work.

Any ideas how to proceed?

Thanks in advance.

**********

# Fetch
wget http://llvm.org/releases/3.4/llvm-3.4.src.tar.gz
wget http://llvm.org/releases/3.4/clang-3.4.src.tar.gz
wget http://llvm.org/releases/3.4/compiler-rt-3.4.src.tar.gz
# wget http://llvm.org/releases/3.4/lldb-3.4.src.tar.gz

# LLVM
tar xvf llvm-3.4.src.tar.gz
cd llvm-3.4/tools

# Clang Front End
tar xvf ../../clang-3.4.src.tar.gz
mv clang-3.4 clang

# LLDB
# tar xvf ../../lldb-3.4.src.tar.gz
# mv lldb-3.4.src/ lldb

# Compiler RT
cd ..
cd projects
tar xvf ../../compiler-rt-3.4.src.tar.
gz
mv compiler-rt-3.4/ compiler-rt

# Build
cd ..
./configure --enable-optimized --prefix=/usr/local
make -j4
sudo make install

**Comment by arsenm** [comment]
Old build issue and python2 is dead
