### ISSUE TITLE
clang : error : unable to execute command: Killed

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19539]
|  |  |
| --- | --- |
| Bugzilla Link | [19165](https://llvm.org/bz19165) |
| Version | 3.3 |
| OS | Linux |
| Attachments | [clang told me to add this](https://user-images.githubusercontent.com/60944935/143749190-11cafcc2-1013-46d6-8abb-c10d033b755a.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 

Ubuntu clang version 3.3-5ubuntu4~precise1 (branches/release_33) (based on LLVM 3.3)
2>  Target: x86_64-pc-linux-gnu
2>  Thread model: posix
2>  clang: note: diagnostic msg: PLEASE submit a bug report to http://bugs.debian.org/ and include the crash backtrace, preprocessed source, and associated run script.

Cannot post source on a public web page, but I can provide it by email if required.

**Comment by Endilll** [comment]
No preprocessed source. On top of that, author themselves weren't able to reproduce the issue.
