### ISSUE TITLE
LTO crashes with linker error on invalid code at -O1 on x86_64-linux-gnu

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#19558]
|  |  |
| --- | --- |
| Bugzilla Link | [19184](https://llvm.org/bz19184) |
| Version | trunk |
| OS | All |

## Extended Description 
The following (invalid) code causes a linker error when it is compiled on x86_64-linux-gnu by the current clang trunk using LTO at -O1 in both 32-bit and 64-bit modes.  

This is a regression from clang 3.4 

Perhaps related to 19079, but it only triggers in 64-bit mode.  

$ clang-trunk -v
clang version 3.5.0 (trunk 204149)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -O1 small.c
$ clang-3.4 -flto -O1 small.c
$ clang-trunk -flto -O0 small.c
$ 
$ clang-trunk -flto -O1 small.c
ld: /tmp/llvm/include/llvm/Support/Casting.h:237: typename cast_retty<X, Y *>::ret_type llvm::cast(Y *) [X = llvm::PHINode, Y = llvm::Instruction]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
clang: error: unable to execute command: Aborted (core dumped)
clang: error: linker command failed due to signal (use -v to see invocation)
$ 

------------------------------

int a, e;

struct
{
  int f1;
  volatile int f2;
  int f3;
} b, c;

int d[1];

int
fn1 (int p)
{
  return p;
}

int
fn2 (int p)
{
  return p ? p : a % p;
}

void fn3 ();

void
fn4 ()
{
  fn3 (d);
}

void
fn3 (int p)
{
  int j, f;
  if (fn1 (p))
    p = 1;
  for (; c.f1; c.f1++)
    {
      if (p)
	f = e > 0;
      e |= 1;
      if (p > 1)
	for (; j; j++)
	  b.f3 = fn2 (f);
      b.f2;
    }
}

int
main ()
{
  fn4 ();
  return 0;
}

**Comment by fhahn** [comment]
I was unable to reproduce this with Clang 4.0 or newer (https://godbolt.org/z/eEqvPWEfa). earlier versions of clang don't seem to work with LTO on godbolt.
