### ISSUE TITLE
Feature request: option to specify the position of pointer/reference qualifiers

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#19568]
|  |  |
| --- | --- |
| Bugzilla Link | [19194](https://llvm.org/bz19194) |
| Version | unspecified |
| OS | All |
| CC | @mkurdej |

## Extended Description 
Currently one can choose if the reference is to be bound to the type or the variable:

auto& a = ...;  // to the type
auto &a = ...;  // to the variable

There is however no option for choosing the style of reference/pointer qualifiers:

const auto& a = ...;  // qualifiers before the type
auto const& a = ...;  // qualifiers after the type

Similar issues apply for pointer types. Such a feature would be useful to keep this side of coding styles consistent.

**Comment by carlosgalvezp** [comment]
This functionality is already available in `clang-format`, see `QualifierAlignment`.
