### ISSUE TITLE
std::complex::operator*= too restrictive with types it accepts

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19563]
|  |  |
| --- | --- |
| Bugzilla Link | [19189](https://llvm.org/bz19189) |
| Version | unspecified |
| OS | All |
| Depends On | llvm/llvm-project#29937  |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
Changeset r187529 for <complex> has imposed additional restrictions on the accepted types in operator*=. An example of the problematic change is below.

Where previously only the existence of

  complex<_Tp> operator*(complex<_Tp>, complex<_Xp>)

was necessary for the implementation of operator*=, 
now a constructor _Tp(_Xp) is required. 

Is this new constraint deliberately there?

An example situation where the new behaviour is problematic is for physical units types that should never be directly constructed from doubles, but which can be multiplied by doubles. 

```
Index: complex
===================================================================
--- complex     (revision 187528)
+++ complex     (revision 187529)
@@ -309,12 +309,12 @@
         }
     template<class _Xp> _LIBCPP_INLINE_VISIBILITY complex& operator*=(const complex<_Xp>& __c)
         {
-            *this = *this * __c;
+            *this = *this * complex(__c.real(), __c.imag());
             return *this;
         }
     template<class _Xp> _LIBCPP_INLINE_VISIBILITY complex& operator/=(const complex<_Xp>& __c)
         {
-            *this = *this / __c;
+            *this = *this / complex(__c.real(), __c.imag());
             return *this;
         }
 };
```

**Comment by ldionne** [comment]
`std::complex<T>` requires `T` to be `float`, `double` or `long double`, so this is not a bug. Closing.
