### ISSUE TITLE
wrong code (that hangs) by LTO at -O0 on x86_64-linux-gnu in 64-bit mode (affecting 3.4 and trunk)

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#19575]
|  |  |
| --- | --- |
| Bugzilla Link | [19201](https://llvm.org/bz19201) |
| Version | trunk |
| OS | All |
| CC | @hfinkel |

## Extended Description 
The current clang trunk and clang 3.4 miscompile the following code when using LTO at -O0 on x86_64-linux-gnu in 64-bit mode (but not 32-bit). The generated code hangs. 

This is a regression from clang 3.3. 

$ clang-trunk -v
clang version 3.5.0 (trunk 204228)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -O0 small.c; a.out
$ clang-trunk -flto -O1 small.c; a.out
$ clang-trunk -flto -m32 -O0 small.c; a.out
$ clang-3.3 -flto -O0 small.c; a.out
$ 
$ clang-trunk -flto -O0 small.c
$ a.out
^C
$ 

--------------------------------

int a, b = 1, c;

int
fn1 (unsigned char p1, int p2)
{
  return p2 || p1 > 1 ? 0 : p2;
}

int
main ()
{
  int d = 0;
  for (; a < 1; a++)
    {
      c = 1;
      fn1 ((b &= c) | 10L, d);
    }
  return 0;
}

**Comment by fhahn** [comment]
I was unable to reproduce this with Clang 4.0 or newer (https://godbolt.org/z/faev4xhP8). earlier versions of clang don't seem to work with LTO on godbolt.
