### ISSUE TITLE
wrong code (that hangs) by LTO at -O0 on x86_64-linux-gnu in 32-bit mode (affecting 3.4 and trunk)

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#19576]
|  |  |
| --- | --- |
| Bugzilla Link | [19202](https://llvm.org/bz19202) |
| Version | trunk |
| OS | All |
| CC | @hfinkel |

## Extended Description 
The current clang trunk and clang 3.4 miscompile the following code when using LTO at -O0 on x86_64-linux-gnu in 32-bit mode (but not 64-bit). The generated code hangs. 

This is a regression from clang 3.3. 

$ clang-trunk -v
clang version 3.5.0 (trunk 204228)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -m32 -O0 small.c; a.out
$ clang-trunk -flto -m32 -O1 small.c; a.out
$ clang-trunk -flto -m64 -O0 small.c; a.out
$ clang-3.3 -flto -m32 -O0 small.c; a.out
$ 
$ clang-trunk -flto -m32 -O0 small.c 
$ a.out
^C
$ 

----------------------------------

int a, b;

int
main ()
{
  int c = 1;
  if (!(~4294967295UL))
    for (; a < 1; a++)
      b = c >= 2 || 1 >> c ? 0 : c;
  return 0;
}

**Comment by fhahn** [comment]
I was unable to reproduce this with Clang 7.0 or newer (https://godbolt.org/z/753cc7d8z). earlier versions of clang don't seem to work with LTO & `-m32` on godbolt.
