### ISSUE TITLE
Building of compiler-rt fails in trunk

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19588]
|  |  |
| --- | --- |
| Bugzilla Link | [19214](https://llvm.org/bz19214) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I tried to follow these instructions http://clang.llvm.org/get_started.html to build llvm/clang/compiler-rt.  If I configure with 'configure' I get the following error:

make[3]: Entering directory `[..]/bld-trunk/tools/clang/runtime'
/usr/bin/cp: cannot stat â€˜compiler-rt/Makefileâ€™: No such file or directory
make[4]: Entering directory `[...]/bld-trunk/tools/clang/runtime/compiler-rt'
make[4]: *** No rule to make target `all'.  Stop.
make[4]: Leaving directory `[...]/bld-trunk/tools/clang/runtime/compiler-rt'
make[3]: *** [compiler-rt/.makeall] Error 2

If I try to cmake I get the following:

Linking C static library /clang/3.4/lib/linux/libclang_rt.x86_64.a
/usr/bin/ar: /clang/3.4/lib/linux/libclang_rt.x86_64.a: No such file or directory
make[2]: *** [/clang/3.4/lib/linux/libclang_rt.x86_64.a] Error 1
make[1]: *** [projects/compiler-rt/lib/builtins/CMakeFiles/clang_rt.x86_64.dir/all] Error 2

Withe verbose I see:

cd [...]/bld/projects/compiler-rt/lib/builtins && /usr/bin/cmake -E cmake_link_script CMakeFiles/clang_rt.x86_64.dir/link.txt --verbose=yes
/usr/bin/ar cr /clang/3.4/lib/linux/libclang_rt.x86_64.a  CMakeFiles/clang_rt.x86_64.[...]

Somehow it is missing the prefix for the path of the archive.

The same happens on 3.4.

**Comment by arsenm** [comment]
Old build problem
