### ISSUE TITLE
Include svn revision number in nightly tester web page report

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#1959]
|  |  |
| --- | --- |
| Bugzilla Link | [1587](https://llvm.org/bz1587) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Please include svn revision number in www.llvm.org/nighltlytest table. This will make it easier to understand whether particular test run includes selected patch or not.

**Comment by EugeneZelenko** [comment]
@nunoplopes Please add comment why issue was closed: is it obsolete (and add label)? or where such functionality could be found.

**Comment by nunoplopes** [comment]
website is dead
