### ISSUE TITLE
wrong code by LTO at -Os (only) on x86_64-linux-gnu (affecting trunk and 3.4)

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#19599]
|  |  |
| --- | --- |
| Bugzilla Link | [19225](https://llvm.org/bz19225) |
| Version | trunk |
| OS | All |
| CC | @hfinkel,@zygoloid |

## Extended Description 
The current clang trunk and 3.4 miscompile the following code when using LTO at -Os on x86_64-linux-gnu in both 32-bit and 64-bit modes. The generated code hangs. 

This is a regression from clang 3.3.

$ clang-trunk -v
clang version 3.5.0 (trunk 204459)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$
$ clang-trunk -Os small.c; a.out
$ clang-trunk -flto -O1 small.c; a.out
$ clang-trunk -flto -O2 small.c; a.out
$ clang-3.3 -flto -Os small.c; a.out
$
$ clang-trunk -flto -Os small.c
$ a.out
^C
$ clang-3.4 -flto -Os small.c
$ a.out
^C
$

-------------------------------

int *a, b, c, e, **f = &a;
long long d = -1;

static int *
fn1 (long long p)
{ 
  int g;
  if (d < 0)
    for (b = 1; b >=0; b--)
      { 
        int h = p;
        g = h == 0 ? 0 : 2 % h;
        e = g || c;
      }
  return 0;
}

int
main ()
{ 
  fn1 (a == 0);
  return 0;
}

**Comment by fhahn** [comment]
I was unable to reproduce this with Clang 11.0 or newer (https://godbolt.org/z/GYhqcYTr9). earlier versions of clang don't seem to work with LTO & `-Os` on godbolt.
