### ISSUE TITLE
Kill flags missing on function argument copies

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19598]
|  |  |
| --- | --- |
| Bugzilla Link | [19224](https://llvm.org/bz19224) |
| Version | trunk |
| OS | Linux |
| Attachments | [test case; run with "llc -o /dev/null -print-machineinstrs"](https://user-images.githubusercontent.com/60944935/143749217-a7239f3a-e2cc-469d-b1ff-3bceb8076488.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @atrick |

## Extended Description 

It seems like the liveness analyzer removes kill flags from all register uses, expecting them to be added back later, but they don't get re-added to registers that start off as physical registers due to ABI constraints, such as function arguments.

I'm not sure what the scope of this is, but it means that the later analyses will be overly-conservative about the set of live-ins and live-outs, since they may not consider the function arguments dead even when they are.

For example, with this IR:

declare void @&#8203;foo(i64)

define void @&#8203;test(i64 %a) {
  call void @&#8203;foo(i64 1)
  call void @&#8203;foo(i64 %a)
  ret void
}

The following machine instructions are generated:

BB#0: derived from LLVM BB %0
    Live Ins: %RDI %RBX
	PUSH64r %RBX<kill>, %RSP<imp-def>, %RSP<imp-use>; flags: FrameSetup
	PROLOG_LABEL <MCSym=.Ltmp0>
	PROLOG_LABEL <MCSym=.Ltmp1>
	%RBX<def> = MOV64rr %RDI
	%EDI<def,dead> = MOV32ri64 1, %RDI<imp-def>
	CALL64pcrel32 <ga:@foo>, <regmask>, %RSP<imp-use>, %RDI<imp-use>, %RSP<imp-def>
	%RDI<def> = MOV64rr %RBX<kill>
	CALL64pcrel32 <ga:@foo>, <regmask>, %RSP<imp-use>, %RDI<imp-use>, %RSP<imp-def>
	%RBX<def> = POP64r %RSP<imp-def>, %RSP<imp-use>
	RETQ

Notice that there is no kill flag on the "%RBX<def> = MOV64rr %RDI" instruction.

I may be misunderstanding whether or not the kill flag is warranted here, but in that case I think other parts of the code do as well.

**Comment by arsenm** [comment]
We should just get rid of kill flags altogether
