### ISSUE TITLE
Add an option to place constructor initializers one per line

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19649]
|  |  |
| --- | --- |
| Bugzilla Link | [19275](https://llvm.org/bz19275) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
There is ConstructorInitializerAllOnOneLineOrOnePerLine option but it does't allow to *always* put the initializers one per line. E.g. the following code

struct Point {
    Point()
        : x(0)
        , y(0)
    {}

    // ...

private:
    int x, y;
};

will always be formatted in a way similar to

struct Point {
    Point() : x(0), y(0) {}

    // ...

private:
    int x, y;
};

Possibly, it's better to have an enum to control constructor initializers:

ConstructorInitializer: AllOnOneLineOrOnePerLine / BinPack (default?) / OnePerLine

**Comment by mydeveloperday** [comment]
I believe this is addressed by `PackConstructorInitializers`  which was added in v14 of clang-format

I am going to close this issue for now, but feel free to reopen if you have an issue
