### ISSUE TITLE
LoopVectorize.cpp: runOnFunction() does not check if function should be optimized at all

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19693]
|  |  |
| --- | --- |
| Bugzilla Link | [19319](https://llvm.org/bz19319) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Most of passes that inherit FunctionPass start their implementation of runOnFunction() like this (code taken from SLPVectorizer.cpp in the same directory):

  bool runOnFunction(Function &F) override {
    if (skipOptnoneFunction(F))
      return false;
  ...

For some reason LoopVectorizer.cpp does not contain such checking in its runOnFunction() method.
Shouldn't it be added?

**Comment by fhahn** [comment]
Looks like most passes don't check for `optnone` (and SLPVectorizer doesn't do so any longer). I don't think there's anything left to do here, but please feel free to re-open with additional details if you think there is.
