### ISSUE TITLE
Message 'argument unused during compilation' emitting while linking

### ISSUE THREAD

**Issue by steveire** [llvm/llvm-project#19702]
|  |  |
| --- | --- |
| Bugzilla Link | [19328](https://llvm.org/bz19328) |
| Version | trunk |
| OS | Linux |

## Extended Description 
$ clang -c -Xclang -fixit-recompile -fPIC empty.cpp 
$ clang -shared -o somelib.so -Xclang -fixit-recompile empty.o
clang: warning: argument unused during compilation: '-Xclang -fixit-recompile
$ clang --version
Ubuntu clang version 3.5.0-1~exp1 (trunk) (based on LLVM 3.5.0)
Target: x86_64-pc-linux-gnu
Thread model: posix

**Comment by xgupta** [comment]
it is fixed on trunk.
