### ISSUE TITLE
__GCC_ATOMIC_LLONG_LOCK_FREE only set to 1 on X86

### ISSUE THREAD

**Issue by 24bb07d4-a064-4a64-856b-dc3103e7a3ac** [llvm/llvm-project#19729]
|  |  |
| --- | --- |
| Bugzilla Link | [19355](https://llvm.org/bz19355) |
| Version | 3.4 |
| OS | All |
| CC | @Lastique,@sylvestre |

## Extended Description 
Hello,

when compiling the Boost Atomic library I noticed a test case failure which expects that boost::atomic<long long> is always lock-free on X86 [1].

This is caused by the fact that clang sets the __GCC_ATOMIC_LLONG_LOCK_FREE to 1.
In comparison gcc (4.8) sets this preprocessor symbol to 2:

$ gcc --version
gcc (Debian 4.8.2-19) 4.8.2
$ gcc -dM -E - -m32 < /dev/null|grep __GCC_ATOMIC_LLONG_LOCK_FREE
#define __GCC_ATOMIC_LLONG_LOCK_FREE 2

In contrast:

$ clang --version
Debian clang version 3.4-2 (tags/RELEASE_34/final) (based on LLVM 3.4)
Target: x86_64-pc-linux-gnu
Thread model: posix
$ clang -dM -E - -m32 < /dev/null|grep __GCC_ATOMIC_LLONG_LOCK_FREE
#define __GCC_ATOMIC_LLONG_LOCK_FREE 1

Is this difference a bug? Andrey Semashev stated in the Boost Atomic bug report that Core2 CPUs all should support cmpxchg8b and thus be always completely lock free.

Thanks,
Gregor

[1] See https://svn.boost.org/trac/boost/ticket/9842

**Comment by rprichard** [comment]
I believe this issue was fixed in Clang 15 by https://reviews.llvm.org/D28213.
```
$ /x/clang14/bin/clang -target i686-linux-gnu -dM -E - </dev/null | grep ATOMIC_LLONG_LOCK_FREE
#define __CLANG_ATOMIC_LLONG_LOCK_FREE 1
#define __GCC_ATOMIC_LLONG_LOCK_FREE 1

$ /x/clang15/bin/clang -target i686-linux-gnu -dM -E - </dev/null | grep ATOMIC_LLONG_LOCK_FREE
#define __CLANG_ATOMIC_LLONG_LOCK_FREE 2
#define __GCC_ATOMIC_LLONG_LOCK_FREE 2

$ /x/clang15/bin/clang -target i686-linux-gnu -march=i486  -dM -E - </dev/null | grep ATOMIC_LLONG
#define __CLANG_ATOMIC_LLONG_LOCK_FREE 1
#define __GCC_ATOMIC_LLONG_LOCK_FREE 1

$ /x/clang15/bin/clang -target i686-linux-gnu -march=i586  -dM -E - </dev/null | grep ATOMIC_LLONG
#define __CLANG_ATOMIC_LLONG_LOCK_FREE 2
#define __GCC_ATOMIC_LLONG_LOCK_FREE 2
```
