### ISSUE TITLE
Feature request: align trailing comments even across a blank lines

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19756]
|  |  |
| --- | --- |
| Bugzilla Link | [19382](https://llvm.org/bz19382) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
It would be great if there was an option to tweak AlignTrailingComments slightly to continue aligning comments even if there are some blank lines in-between. For me, ignoring a single blank line would be enough, but perhaps this could be configurable, similar to MaxEmptyLinesToKeep.

Here is an example of code that looks like the start of one of our C files:
-- 8< --
```
#include        "moduleA.h"              /* some comment                  */
#include        "relatedToA.h"           /* some comment                  */

#include        "B.h"                    /* some comment                  */
#include        "B21.h"                  /* some comment                  */
#include        "B0.h"                   /* some comment                  */

#include        "otherheader.h"          /* some comment                  */
```
-- 8< --

And here is what clang-format produces:
-- 8< --
```
#include "moduleA.h"    /* some comment                  */
#include "relatedToA.h" /* some comment                  */

#include "B.h"   /* some comment                  */
#include "B21.h" /* some comment                  */
#include "B0.h"  /* some comment                  */

#include "otherheader.h" /* some comment                  */
```
-- 8< --

What I was hoping for was more like this:
-- 8< --
```
#include "moduleA.h"     /* some comment                  */
#include "relatedToA.h"  /* some comment                  */

#include "B.h"           /* some comment                  */
#include "B21.h"         /* some comment                  */
#include "B0.h"          /* some comment                  */

#include "otherheader.h" /* some comment                  */
```
-- 8< --

The result is not much different when using C99 / C++ inline comments, except that then it honors SpacesBeforeTrailingComments, which improves readability at least a bit).

**Comment by yusuke-kadowaki** [comment]
I submitted a patch for this anyway
https://reviews.llvm.org/D132131

**Comment by HazardyKnusperkeks** [comment]
Is this done with the patch, or still open?

**Comment by yusuke-kadowaki** [comment]
Yes, it's done.
It can be done with a setting like below starting from clang 16.
```
AlignTrailingComments:
  Kind: Always
  OverEmptyLines: 2
```
