### ISSUE TITLE
Port big-endian support to ARM64

### ISSUE THREAD

**Issue by TNorthover** [llvm/llvm-project#19774]
|  |  |
| --- | --- |
| Bugzilla Link | [19400](https://llvm.org/bz19400) |
| Version | trunk |
| OS | Linux |
| CC | @jmolloy,@TNorthover |

## Extended Description 
Big-endian support is currently being implemented on AArch64, and this will probably need to be ported to ARM64 before the merge can be called complete.

This may mean the (hopefully temporary) creation of an arm64_be triple to do the redirection (yuck!).

**Comment by arsenm** [comment]
I believe this is done
