### ISSUE TITLE
zlib support in windows with MSVC

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19777]
|  |  |
| --- | --- |
| Bugzilla Link | [19403](https://llvm.org/bz19403) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @amykhuang,@dwblaikie,@zmodem,@MikeHolman,@rnk |

## Extended Description 
Why is zlib support disabled for windows/MSVC in CMake?

I got the zlib headers and libraries from GetGnuWin32. I have a code in llvm that uses zlib algorithm. With the current CMake configuration in LLVM, I couldn't configure to link zlib.

To detect zlib.h header   
-DCMAKE_C_FLAGS="/IC:/GetGnuWin32/gnuwin32/include" - DCMAKE_CXX_FLAGS="/IC:/GetGnuWin32/gnuwin32/include" 

To detect zlib.lib library (dirty hack)
-DHAVE_LIBZ=1 -DCMAKE_EXE_LINKER_FLAGS="C:/GetGnuWin32/gnuwin32/lib/zlib.lib" -DCMAKE_SHARED_LINKER_FLAGS="C:/GetGnuWin32/gnuwin32/lib/zlib.lib"
The checks to detect zlib library and add it to the linker line are written for non-windows/MSVC sytems.

I think, blocking the zlib support in windows is a limitation and a bug.

--Sumanth G

**Comment by arsenm** [comment]
Old build issue with referenced fix commits
