### ISSUE TITLE
[R3.4.1] tools/clang/include/clang-c/Makefile aborts on Open Solaris 11

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19784]
|  |  |
| --- | --- |
| Bugzilla Link | [19410](https://llvm.org/bz19410) |
| Version | 3.4 |
| OS | Solaris |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
There is a multi line backquote in the Makefile here 
(starting with `find clang-c -type f ...):

ifneq ($(PROJ_SRC_ROOT),$(PROJ_OBJ_ROOT))
        $(Verb) if test -d "$(PROJ_OBJ_ROOT)/tools/clang/include/clang-c" ; then \
          cd $(PROJ_OBJ_ROOT)/tools/clang/include && \
          for hdr in `find clang-c -type f '!' '(' -name 'Makefile' ')' -print \
            | grep -v CVS | grep -v .tmp | grep -v .dir` ; do \
            instdir=`dirname "$(IntIncludeDir)/$$hdr"` ; \
            if test \! -d "$$instdir" ; then \
              $(EchoCmd) Making install directory $$instdir ; \
              $(MKDIR) $$instdir ;\
            fi ; \
            $(DataInstall) $$hdr $(IntIncludeDir)/$$hdr ; \
          done ; \
        fi
endif

This fails in Solaris 11 (Virtual Box).
It works, after joining the lines into a single line.

rgds,
Frank

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
