### ISSUE TITLE
check for variables that could be declared 'const'

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#19793]
|  |  |
| --- | --- |
| Bugzilla Link | [19419](https://llvm.org/bz19419) |
| Version | unspecified |
| OS | All |
| CC | @EugeneZelenko |

## Extended Description 
Some C++ experts advise making variables `const` wherever possible. It'd be nice for clang-tidy to have a mode to check for variables which could be marked `const` but aren't, and provide a fixit adding in the missing `const`.

**Comment by EugeneZelenko** [comment]
@JonasToth

**Comment by JonasToth** [comment]
https://reviews.llvm.org/D54943

**Comment by JonasToth** [comment]
landed with https://github.com/llvm/llvm-project/commit/46ae26e7eb7095faeda6d6c15470c256f9294c48 that should be released with llvm-15

There will be more improvements over time, but i think its viable enough to close this ticket.
