### ISSUE TITLE
warning: implicit conversion changes signedness: 'long' to 'int'

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19816]
|  |  |
| --- | --- |
| Bugzilla Link | [19442](https://llvm.org/bz19442) |
| Version | trunk |
| OS | Linux |
| Attachments | [Testcase](https://user-images.githubusercontent.com/60944935/143749330-14988adb-431a-4465-b286-fbc9c5601a41.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

The below small testcase causes -Wsign-conversion to print a (to me) nonsensical warning message: "warning: implicit conversion changes signedness: 'long' to 'int'".

void f(void)
{
	unsigned int mask = 1;
	long value = 1;
	int result = value & mask;
}

The warning is correct in that there is an implicit sign conversion going on, but it's not between (signed) long and (signed) int, like the warning message says.

This message has been the same since at least 3.0.

**Comment by AaronBallman** [comment]
The warning leaves a bit to be desired because it doesn't seem immediately obvious why it can change sign, but what it means is: https://godbolt.org/z/v3zMqh9z1

GCC gives the same warning as Clang: https://godbolt.org/z/W7os3fKaa

Closing as by design.
