### ISSUE TITLE
Linking with LLVM shared library outside of build tree fails

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19917]
|  |  |
| --- | --- |
| Bugzilla Link | [19543](https://llvm.org/bz19543) |
| Version | trunk |
| OS | All |
| Attachments | [Fix for handling shared libraries](https://user-images.githubusercontent.com/60944935/143749386-55f2454f-5b19-421b-8a79-baae85f058c9.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

If an external projects tries to link with the library libLLVM3.*.so it fails as Makefile.rules searches in the project lib directory not in the LLVM directory.

Patch to fix that is attached.

(In case it gets committed, please apply it as well to the 3.4 branch).

Thanks.

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
