### ISSUE TITLE
cannot build clang from trunk

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19950]
|  |  |
| --- | --- |
| Bugzilla Link | [19576](https://llvm.org/bz19576) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [output of the make command](https://user-images.githubusercontent.com/60944935/143749398-66d99502-8e14-4dc6-b259-4addc12b5bf4.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DimitryAndric |

## Extended Description 

I tried to follow the instructions at http://clang.llvm.org/get_started.html to build a debug version of clang ( I need this to troubleshoot persistent problems with clang-3.3 and associated tools on Linux.)

anyway, had to upgrade gcc to 4.8 (I'm on ubuntu 12.04, which had gcc4.6). 

ran configure with:

../llvm/configure CC="/usr/bin/clang" CXX="/usr/bin/clang++"

compling seemed to go without issue, but it failed onthe link step with a useless error message.

make TOOL_VERBOSE=1 log attached.

I'm now trying to configure with CC=gcc etc. to see if that works.

**Comment by arsenm** [comment]
Old build problem
