### ISSUE TITLE
failing to substitute into lambda-expression in initializer of a variable template

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#20003]
|  |  |
| --- | --- |
| Bugzilla Link | [19629](https://llvm.org/bz19629) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
This code:

  template<typename T> int var = [] {
    struct S { int f() { return T(); } };
    return S().f();
  } ();
  int k = var<int>;

crashes in IR gen, because we reused the LambdaExpr from the template definition in the initializer of the template specialization.

Not clear whether we're not transforming it at all, or whether TreeTransform somehow believes it can reuse the LambdaExpr.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 16: https://godbolt.org/z/efbeeTaKW
