### ISSUE TITLE
make fails with error "No rule to make target `clang_macho_embedded'."

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20016]
|  |  |
| --- | --- |
| Bugzilla Link | [19642](https://llvm.org/bz19642) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
After updating llvm and llvm/tools/clang to version 207851, I did

./configure --prefix=/opt --enable-optimized --enable-libcpp

and then

make -j 2

(The reason for using enable-libcpp is that otherwise it complains about my version of libstdc++.)

The make ran for a while, but ended like this:

make[5]: Nothing to be done for `clang_darwin'.
make[5]: *** No rule to make target `clang_macho_embedded'.  Stop.
make[4]: *** [BuildRuntimeLibraries] Error 2
rm /open-source/llvm-build/Release+Asserts/lib/clang/3.5.0/lib/macho_embedded/.dir /open-source/llvm-build/Release+Asserts/lib/clang/3.5.0/lib/darwin/.dir
make[3]: *** [compiler-rt/.makeall] Error 2
make[2]: *** [all] Error 1
make[1]: *** [clang/.makeall] Error 2
make: *** [all] Error 1

I'm on Mac OS X 10.7.5.

**Comment by arsenm** [comment]
Old build issue
