### ISSUE TITLE
Undefinied references in firefox build after SVN 207451

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20032]
|  |  |
| --- | --- |
| Bugzilla Link | [19658](https://llvm.org/bz19658) |
| Version | trunk |
| OS | Linux |
| Attachments | [firefox compile errors](https://user-images.githubusercontent.com/60944935/143749429-3a3fe17d-ef63-422b-a9b6-7e1dfa88f283.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @majnemer |

## Extended Description 

After clang SVN r207451 (git f5563f573675f1b0b30884185cc52e611e97bd6c), firefox-28.0 (gentoo) no longer builds. The revision prior, SVN r207446 (git ec47c9130c83eabfa9460651da30eefeac297f62) will compile firefox.

I'm still working on a test case that's smaller than compiling all of firefox.

It seems to be related to kIID in nsID.h

/**
 * A macro to build the static const IID accessor method. The Dummy
 * template parameter only exists so that the kIID symbol will be linked
 * properly (weak symbol on linux, gnu_linkonce on mac, multiple-definitions
 * merged on windows). Dummy should always be instantiated as "int".
 */

#define NS_DECLARE_STATIC_IID_ACCESSOR(the_iid)                         \
  template <class Dummy>                                                \
  struct COMTypeInfo                                                    \
  {                                                                     \
    static const nsIID kIID NS_HIDDEN;                                  \
  };                                                                    \
  static const nsIID& GetIID() {return COMTypeInfo<int>::kIID;}

**Comment by arsenm** [comment]
Old build issue
