### ISSUE TITLE
LLVM trunk fails to build on OS X 10.9.2

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20081]
|  |  |
| --- | --- |
| Bugzilla Link | [19707](https://llvm.org/bz19707) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @echristo |

## Extended Description 
I followed the instructions here: http://clang.llvm.org/get_started.html

When I get to the make command the build is unsuccessful.

#... successful compiling ...
llvm[1]: Compiling Valgrind.cpp for Debug+Asserts build
      Pattern::AddRegExToRegEx(llvm::StringRef, unsigned int&, llvm::SourceMgr&) in FileCheck.o
      Pattern::Match(llvm::StringRef, unsigned long&, llvm::StringMap<llvm::StringRef, llvm::MallocAllocator>&) const in FileCheck.o
      ValidateCheckPrefix(llvm::StringRef) in FileCheck.o
  "vtable for llvm::cl::Option", referenced from:
      llvm::cl::Option::Option(llvm::cl::NumOccurrencesFlag, llvm::cl::OptionHidden) in FileCheck.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
#... similar errors...

This is on OS X 10.9.2.

What's going on in this build is opaque to me. What other information should I provide and how do I get it?

I can tell you that I have system clang and homebrew gcc installed. Here are the versions they report.

$ clang -v
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.1.0
Thread model: posix

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc48/4.8.2/libexec/gcc/x86_64-apple-darwin13.0.0/4.8.2/lto-wrapper
Target: x86_64-apple-darwin13.0.0
Configured with: ../configure --build=x86_64-apple-darwin13.0.0 --prefix=/usr/local/Cellar/gcc48/4.8.2 --enable-languages=c,c++,fortran,java,objc,obj-c++ --program-suffix=-4.8 --with-gmp=/usr/local/opt/gmp4 --with-mpfr=/usr/local/opt/mpfr2 --with-mpc=/usr/local/opt/libmpc08 --with-cloog=/usr/local/opt/cloog018 --with-isl=/usr/local/opt/isl011 --with-system-zlib --enable-version-specific-runtime-libs --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --enable-plugin --disable-nls --with-ecj-jar=/usr/local/opt/ecj/share/java/ecj.jar --disable-multilib
Thread model: posix
gcc version 4.8.2 (GCC)

**Comment by arsenm** [comment]
Old build problem
