### ISSUE TITLE
llvm creates a really large constantexpr and spends a lot of time on it

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20101]
|  |  |
| --- | --- |
| Bugzilla Link | [19727](https://llvm.org/bz19727) |
| Version | trunk |
| OS | All |
| Attachments | [testcase](https://user-images.githubusercontent.com/60944935/143749458-036084ff-ca07-4608-9b2e-d7baf8968a62.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @d0k |

## Extended Description 

This is some variation of llvm/llvm-project#16086 .

This can be reproduced by running

./bin/opt -basicaa  -inline  -simplifycfg -instcombine -loop-rotate -licm -indvars -gvn test.ll -o test.bc

Looks like the slow part is actually writing the bitcode.

Tested with r208570.

**Comment by nikic** [comment]
IR compatible with modern LLVM: https://gist.github.com/nikic/468e38797f2b009b90f322e09042a922

Can't reproduce any slowness. Quite likely that the test case just doesn't trigger the issue anymore, but I don't think there's a lot we can do at this point without a current reproducer.
