### ISSUE TITLE
SegFault in Type Legalizer

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20126]
|  |  |
| --- | --- |
| Bugzilla Link | [19752](https://llvm.org/bz19752) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#11360  |
| Attachments | [reduced test case](https://user-images.githubusercontent.com/60944935/143749463-b40d2c6c-7590-4e89-b629-fd78d2513453.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @compnerd,@majnemer |

## Extended Description 

Some inline asm returns an i64 and takes an i64 but building with the triple "i386---elf" resulted in this crash.

Cheers,
Edward.

**Comment by RKSimon** [comment]
This was fixed sometime after 10.x  https://gcc.godbolt.org/z/96M8h43j5
