### ISSUE TITLE
accidentally performing ADL on non-dependent operator calls during template instantiation

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#20149]
|  |  |
| --- | --- |
| Bugzilla Link | [19775](https://llvm.org/bz19775) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor |

## Extended Description 
As filed by Doug on GCC's bugzilla...

Clang and GCC both reject this valid code:

```cpp
template<class T> struct wrap {};

template<typename T> bool& operator==(wrap<T>, wrap<T>);

template<typename T>
void g(T, wrap<wrap<int> > x)
{
  bool& b = x == x;
}

template<typename T> int& operator==(wrap<wrap<T> >, wrap<wrap<T> >);

void h()
{
  wrap<wrap<int> > x;
  g(17, x);
}
```

In Clang's case, we resolve the non-dependent == operator inside 'g' during the template definition, but TreeTransform does the wrong thing and rebuilds the operator using code that performs ADL. Oops...

**Comment by hubert-reinterpretcast** [comment]
Fixed in Clang 6.x: https://godbolt.org/z/9jKj64b9P
