### ISSUE TITLE
Clang frontend command failed due to signal while compiling jemalloc.c for Rust

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20162]
|  |  |
| --- | --- |
| Bugzilla Link | [19788](https://llvm.org/bz19788) |
| Version | trunk |
| OS | Linux |
| Attachments | [Preprocessed source](https://user-images.githubusercontent.com/60944935/143749489-717afd1c-1a5e-4d04-850e-0fae1ff793c8.gz), [Associated run script](https://user-images.githubusercontent.com/60944935/143749490-58d1744e-6c4f-4d16-9f78-b23a8eef9900.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @rnk |

## Extended Description 
make[1]: Entering directory `/usr/src/rust/x86_64-unknown-linux-gnu/rt/jemalloc'
clang -Qunused-arguments -std=gnu99 -Wall -pipe -g3 -m64 -g1 -fvisibility=hidden -O3 -funroll-loops -c -I /usr/src/rust/src/rt/ -D_GNU_SOURCE -D_REENTRANT -I/usr/src/rust/src/jemalloc/include -Iinclude -o src/jemalloc.o /usr/src/rust/src/jemalloc/src/jemalloc.c
0  clang           0x0000000001e4c6f2 llvm::sys::PrintStackTrace(_IO_FILE*) + 34
1  clang           0x0000000001e4bf8c
2  libpthread.so.0 0x0000003d2900f710
3  clang           0x0000000001dcc593 llvm::PHINode::removeIncomingValue(unsigned int, bool) + 67
4  clang           0x0000000001afa690 llvm::CloneAndPruneFunctionInto(llvm::Function*, llvm::Function const*, llvm::ValueMap<llvm::Value const*, llvm::WeakVH, llvm::ValueMapConfig<llvm::Value const*> >&, bool, llvm::SmallVectorImpl<llvm::ReturnInst*>&, char const*, llvm::ClonedCodeInfo*, llvm::DataLayout const*, llvm::Instruction*) + 4688
5  clang           0x0000000001b047e7 llvm::InlineFunction(llvm::CallSite, llvm::InlineFunctionInfo&, bool) + 2247
6  clang           0x0000000001483d87 llvm::Inliner::runOnSCC(llvm::CallGraphSCC&) + 2295
7  clang           0x0000000001b5f52e
8  clang           0x0000000001de8fe8 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 1112
9  clang           0x00000000007f3578 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::raw_ostream*) + 3800
10 clang           0x00000000007ee7f1
11 clang           0x0000000000984545 clang::ParseAST(clang::Sema&, bool, bool) + 789
12 clang           0x0000000000670096 clang::FrontendAction::Execute() + 134
13 clang           0x000000000064c860 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 288
14 clang           0x0000000000635b24 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 1716
15 clang           0x000000000062d668 cc1_main(char const**, char const**, char const*, void*) + 936
16 clang           0x0000000000634f34 main + 8212
17 libc.so.6       0x0000003d28c1ed1d __libc_start_main + 253
18 clang           0x000000000062ce35
Stack dump:
0.	Program arguments: /usr/bin/clang -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -main-file-name jemalloc.c -mrelocation-model static -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -target-linker-version 2.20.51.0.2 -momit-leaf-frame-pointer -g -coverage-file /usr/src/rust/x86_64-unknown-linux-gnu/rt/jemalloc/src/jemalloc.o -resource-dir /usr/bin/../lib/clang/3.5.0 -D _GNU_SOURCE -D _REENTRANT -I /usr/src/rust/src/rt/ -I /usr/src/rust/src/jemalloc/include -I include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/clang/3.5.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -Wall -std=gnu99 -fdebug-compilation-dir /usr/src/rust/x86_64-unknown-linux-gnu/rt/jemalloc -ferror-limit 19 -fmessage-length 129 -fvisibility hidden -funroll-loops -mstackrealign -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o src/jemalloc.o -x c /usr/src/rust/src/jemalloc/src/jemalloc.c 
1.	<eof> parser at end of file
2.	Per-module optimization passes
3.	Running pass 'CallGraph Pass Manager' on module '/usr/src/rust/src/jemalloc/src/jemalloc.c'.
clang: error: unable to execute command: Segmentation fault
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.5.0 (trunk 209064)
Target: x86_64-unknown-linux-gnu
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/jemalloc-1a047c.c
clang: note: diagnostic msg: /tmp/jemalloc-1a047c.sh
clang: note: diagnostic msg: 

********************
make[1]: *** [src/jemalloc.o] Error 254
make[1]: Leaving directory `/usr/src/rust/x86_64-unknown-linux-gnu/rt/jemalloc'
make: *** [x86_64-unknown-linux-gnu/rt/libjemalloc.a] Error 2

**Comment by Endilll** [comment]
I can't reproduce it either using assertion builds of Clang 3.4 through 3.6.
