### ISSUE TITLE
Avoid bad substitutions in case SHLIBPATH_VAR is not set for Makefile.unittest

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20190]
|  |  |
| --- | --- |
| Bugzilla Link | [19816](https://llvm.org/bz19816) |
| Version | 3.4 |
| OS | All |
| Attachments | [Patch](https://user-images.githubusercontent.com/60944935/143749507-62b812d8-f561-420b-8d4a-eef3d6022fda.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Attached is a small patch which fixes an issue with unittest.makefile in case shlibpath is not set.
In that case substitution fail.
It is just relevant for LLVM 3.4, trunk got rid of that part.

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
