### ISSUE TITLE
libc++ has no minor or patch version, and no version symbols

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20191]
|  |  |
| --- | --- |
| Bugzilla Link | [19817](https://llvm.org/bz19817) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
The libc++.so.1 library symlink points to libc++.so.1.0 for both llvm 3.3 and 3.4. However, these libraries contain different symbols. For example, I can see std::__1::shared_mutex::lock is present in the llvm 3.4 libc++.so. This may cause a problem for distributing binaries built on llvm 3.4 to a machine with llvm 3.3 installed.

Correct me if I'm wrong, but I believe the libc++.so library should distinguish these ambiguous libraries using patch versions, ie. create libc++.so.1.0.1, and include version symbols similar to GLIBCXX_* symbols in the libstdc++.so library.

**Comment by philnik777** [comment]
The dylib is only supposed to be backwards compatible, not forwards compatible, so there shouldn't be any need for this. AFAICT nobody else in the last 8 years has asked for something like this, so I don't think there is huge demand for this.
