### ISSUE TITLE
LTO crashes with linker error on valid code at -O0 on x86_64-linux-gnu

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#20204]
|  |  |
| --- | --- |
| Bugzilla Link | [19830](https://llvm.org/bz19830) |
| Version | trunk |
| OS | All |
| CC | @hfinkel |

## Extended Description 
The following code causes a linker error when it is compiled on x86_64-linux-gnu by the current clang trunk using LTO at -O0 (but not other optimization levels) in both 32-bit and 64-bit modes.  

This is a regression from clang 3.4. 

$ clang-trunk -v
clang version 3.5.0 (trunk 209432)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -O0 small.c; a.out
$ clang-trunk -flto -O1 small.c; a.out
$ clang-3.4 -flto -O0 small.c; a.out
$ 
$ clang-trunk -flto -O0 small.c
ld: /tmp/llvm/include/llvm/Support/Casting.h:237: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::PHINode; Y = llvm::Instruction; typename llvm::cast_retty<X, Y*>::ret_type = llvm::PHINode*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
clang: error: unable to execute command: Aborted (core dumped)
clang: error: linker command failed due to signal (use -v to see invocation)
$ 

----------------------------

int a, b, *c = &b, d = 1, e[1], **f, ***g, h, *i = &b;

void
fn1 ()
{
  for (; h < 1; h++)
    g = &f;
  if (g == 0)
    for (;;)
      {
	int ****k[1], *****l = &k[0];
	for (d = 0; d;)
	  for (h = 0; h < 1;)
	    {
	      a--;
	      for (;;)
		{
		  i = &e[a];
		  *c = (l != 0);
		}
	    }
      }
}

int
main ()
{
  fn1 ();
  return 0;
}

**Comment by fhahn** [comment]
I was unable to reproduce this with Clang 4.0 or newer (https://godbolt.org/z/zeMczT97s). earlier versions of clang don't seem to work with LTO on godbolt.
