### ISSUE TITLE
Clang static analyzer reports different line numbers in command line vs. html file.

### ISSUE THREAD

**Issue by hiraditya** [llvm/llvm-project#20201]
|  |  |
| --- | --- |
| Bugzilla Link | [19827](https://llvm.org/bz19827) |
| Version | 3.4 |
| OS | Linux |
| CC | @hiraditya |

## Extended Description

```cpp
// cat test.cpp

unsigned int *gp;
int foo(unsigned int argc) {
  int* p = new int[10];
  unsigned int i = 100;
  gp = &i;
  if (argc>*p)
    return i;
  return *p;
}
```

$ clang++ -cc1 -analyze -analyzer-checker=security,unix,core,alpha -analyzer-output html -o report-dir/ -x c++ test.cpp

------------------Command line output----------------------
test.cpp:13:3: warning: Potential leak of memory pointed to by 'p'
  return *p;
  ^~~~~~~~~
test.cpp:14:1: warning: Address of stack memory associated with local variable 'i' is still referred to by the global variable 'gp' upon returning to the caller.  This will be a dangling reference
}

--------------------html output------------------
Bug Summary
File:	test.cpp
Location:	line 12, column 12 <------- vs. 13:1 from the command line
Description:	Potential leak of memory pointed to by 'p'

**Comment by hiraditya** [comment]
can't repro.

**Comment by EugeneZelenko** [comment]
@hiraditya: It'll be great to provide links to GodBolt as proof.

**Comment by hiraditya** [comment]
https://godbolt.org/z/Ev5GTGsh6
