### ISSUE TITLE
crash compiling libkqueue on OSX targeting powerpc-unknown-linux

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20257]
|  |  |
| --- | --- |
| Bugzilla Link | [19883](https://llvm.org/bz19883) |
| Version | trunk |
| OS | MacOS X |
| Attachments | [Preprocessed source(s) and associated run script(s)](https://user-images.githubusercontent.com/60944935/143749525-4bf38b18-b20c-48c1-8e92-cd64dc03a57e.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel |

## Extended Description 

/devel/comx_p2020_linux_3_8_tools/bin/clang --sysroot /devel/linux_sysroot_3.8 -target powerpc-unknown-linux    -DHAVE_CONFIG_H -I. -I./src/common -I./include -Wall -Wextra -Wno-missing-field-initializers -Werror -O0 -std=c99 -D_XOPEN_SOURCE=600  -fvisibility=hidden -o src/common/kevent.o -fPIC -DPIC  -c src/common/kevent.c
Assertion failed: ((TLI.getTypeAction(*DAG.getContext(), Node->getOperand(i).getValueType()) == TargetLowering::TypeLegal || Node->getOperand(i).getOpcode() == ISD::TargetConstant) && "Unexpected illegal type!"), function LegalizeOp, file /Volumes/storage/clangcrosscompiler/llvm/lib/CodeGen/SelectionDAG/LegalizeDAG.cpp, line 1174.
0  clang                    0x0000000105d684b8 void* llvm::object_creator<llvm::sys::ThreadLocal<llvm::PrettyStackTraceEntry const> >() + 15240
1  clang                    0x0000000105d689b4 void* llvm::object_creator<llvm::sys::ThreadLocal<llvm::PrettyStackTraceEntry const> >() + 16516
2  libsystem_platform.dylib 0x00007fff91f8e5aa _sigtramp + 26
3  libsystem_platform.dylib 000000000000000000 _sigtramp + 1845959280
4  clang                    0x0000000105d68766 void* llvm::object_creator<llvm::sys::ThreadLocal<llvm::PrettyStackTraceEntry const> >() + 15926
5  clang                    0x0000000105d68741 void* llvm::object_creator<llvm::sys::ThreadLocal<llvm::PrettyStackTraceEntry const> >() + 15889
6  clang                    0x000000010557c28d void std::__1::vector<std::__1::pair<llvm::Type*, llvm::Type* const*>, std::__1::allocator<std::__1::pair<llvm::Type*, llvm::Type* const*> > >::__push_back_slow_path<std::__1::pair<llvm::Type*, llvm::Type* const*> >(std::__1::pair<llvm::Type*, llvm::Type* const*>&&) + 53901
7  clang                    0x0000000105574b7b void std::__1::vector<std::__1::pair<llvm::Type*, llvm::Type* const*>, std::__1::allocator<std::__1::pair<llvm::Type*, llvm::Type* const*> > >::__push_back_slow_path<std::__1::pair<llvm::Type*, llvm::Type* const*> >(std::__1::pair<llvm::Type*, llvm::Type* const*>&&) + 23419
8  clang                    0x000000010568b3f6 llvm::SmallVectorTemplateBase<llvm::MachineModuleInfo::VariableDbgInfo, false>::grow(unsigned long) + 36422
9  clang                    0x0000000105689e0e llvm::SmallVectorTemplateBase<llvm::MachineModuleInfo::VariableDbgInfo, false>::grow(unsigned long) + 30814
10 clang                    0x00000001056876fa llvm::SmallVectorTemplateBase<llvm::MachineModuleInfo::VariableDbgInfo, false>::grow(unsigned long) + 20810
11 clang                    0x0000000105376468 void std::__1::vector<std::__1::pair<llvm::MCSymbol*, llvm::MCSymbol*>, std::__1::allocator<std::__1::pair<llvm::MCSymbol*, llvm::MCSymbol*> > >::__push_back_slow_path<std::__1::pair<llvm::MCSymbol*, llvm::MCSymbol*> >(std::__1::pair<llvm::MCSymbol*, llvm::MCSymbol*>&&) + 115768
12 clang                    0x00000001057c94cc llvm::raw_ostream& llvm::WriteGraph<llvm::MachineFunction const*>(llvm::raw_ostream&, llvm::MachineFunction const* const&, bool, llvm::Twine const&) + 5916
13 clang                    0x0000000105cf910d void* llvm::object_creator<llvm::LeakDetectorImpl<void> >() + 25485
14 clang                    0x0000000105cf939b void* llvm::object_creator<llvm::LeakDetectorImpl<void> >() + 26139
15 clang                    0x0000000105cf99cc void* llvm::object_creator<llvm::LeakDetectorImpl<void> >() + 27724
16 clang                    0x00000001040fcdee void std::__1::vector<clang::serialization::ModuleFile*, std::__1::allocator<clang::serialization::ModuleFile*> >::__push_back_slow_path<clang::serialization::ModuleFile* const&>(clang::serialization::ModuleFile* const&&&) + 8590
17 clang                    0x0000000104225cab llvm::SmallVectorTemplateBase<llvm::DenseMap<clang::BaseSubobject, unsigned long long, llvm::DenseMapInfo<clang::BaseSubobject> >, false>::grow(unsigned long) + 22379
18 clang                    0x00000001042867e4 void std::__1::vector<clang::CXXRecordDecl const*, std::__1::allocator<clang::CXXRecordDecl const*> >::__push_back_slow_path<clang::CXXRecordDecl const* const&>(clang::CXXRecordDecl const* const&&&) + 139348
19 clang                    0x00000001042246c8 llvm::SmallVectorTemplateBase<llvm::DenseMap<clang::BaseSubobject, unsigned long long, llvm::DenseMapInfo<clang::BaseSubobject> >, false>::grow(unsigned long) + 16776
20 clang                    0x0000000103f81443 std::__1::__tree<std::__1::__value_type<clang::edit::FileOffset, clang::edit::EditedSource::FileEdit>, std::__1::__map_value_compare<clang::edit::FileOffset, std::__1::__value_type<clang::edit::FileOffset, clang::edit::EditedSource::FileEdit>, std::__1::less<clang::edit::FileOffset>, true>, std::__1::allocator<std::__1::__value_type<clang::edit::FileOffset, clang::edit::EditedSource::FileEdit> > >::destroy(std::__1::__tree_node<std::__1::__value_type<clang::edit::FileOffset, clang::edit::EditedSource::FileEdit>, void*>*) + 7571
21 clang                    0x0000000103f5967d void std::__1::vector<clang::FrontendInputFile, std::__1::allocator<clang::FrontendInputFile> >::__push_back_slow_path<clang::FrontendInputFile const&>(clang::FrontendInputFile const&&&) + 17821
22 clang                    0x0000000103f1d09a void std::__1::__tree_balance_after_insert<std::__1::__tree_node_base<void*>*>(std::__1::__tree_node_base<void*>*, std::__1::__tree_node_base<void*>*) + 4426
23 clang                    0x0000000103f14c9f
24 clang                    0x0000000103f1ae2d void std::__1::vector<llvm::SourceMgr::SrcBuffer, std::__1::allocator<llvm::SourceMgr::SrcBuffer> >::__push_back_slow_path<llvm::SourceMgr::SrcBuffer const&>(llvm::SourceMgr::SrcBuffer const&&&) + 9181
25 libdyld.dylib            0x00007fff8ec625fd start + 1
26 libdyld.dylib            0x0000000000000048 start + 1899616844
Stack dump:
0.	Program arguments: /Volumes/dev/devel/comx_p2020_linux_3_8_tools/bin/clang -cc1 -triple powerpc-unknown-linux -S -disable-free -main-file-name kevent.c -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -fmath-errno -no-integrated-as -mconstructor-aliases -target-cpu ppc -target-linker-version 136 -coverage-file /var/folders/yb/mnfx7n_14xvdwy23w9f_wt9c0000gn/T/kevent-a1e533.s -resource-dir /Volumes/dev/devel/comx_p2020_linux_3_8_tools/bin/../lib/clang/3.5.0 -D HAVE_CONFIG_H -D _XOPEN_SOURCE=600 -D PIC -I . -I ./src/common -I ./include -isysroot /devel/linux_sysroot_3.8 -internal-isystem /devel/linux_sysroot_3.8/usr/local/include -internal-isystem /Volumes/dev/devel/comx_p2020_linux_3_8_tools/bin/../lib/clang/3.5.0/include -internal-externc-isystem /devel/linux_sysroot_3.8/include -internal-externc-isystem /devel/linux_sysroot_3.8/usr/include -O0 -Wall -Wextra -Wno-missing-field-initializers -Werror -std=c99 -fno-dwarf-directory-asm -fdebug-compilation-dir /Volumes/Old_HD/media_store/Downloads/gcd/libkqueue-2.0.1 -ferror-limit 19 -fmessage-length 316 -fvisibility hidden -mstackrealign -fno-signed-char -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-slp -o /var/folders/yb/mnfx7n_14xvdwy23w9f_wt9c0000gn/T/kevent-a1e533.s -x c src/common/kevent.c 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'src/common/kevent.c'.
4.	Running pass 'PowerPC DAG->DAG Pattern Instruction Selection' on function '@kevent_dump'
clang: error: unable to execute command: Illegal instruction: 4
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.5.0 (trunk 205694)
Target: powerpc-unknown-linux
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/yb/mnfx7n_14xvdwy23w9f_wt9c0000gn/T/kevent-f149f8.c
clang: note: diagnostic msg: /var/folders/yb/mnfx7n_14xvdwy23w9f_wt9c0000gn/T/kevent-f149f8.sh
clang: note: diagnostic msg: 

********************

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.6.
Reduced by C-Reduce:
```
kevent_dump() {
  static __thread buf;
  snprintfbuf(buf);
}
```
