### ISSUE TITLE
wrong code by LTO at -O1 (only) on x86_64-linux-gnu (affecting 3.4 and trunk)

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#20265]
|  |  |
| --- | --- |
| Bugzilla Link | [19891](https://llvm.org/bz19891) |
| Version | unspecified |
| OS | All |
| CC | @hfinkel |

## Extended Description 
The current clang trunk and clang 3.4 miscompile the following code when using LTO at -O1 (only) on x86_64-linux-gnu in both 32-bit and 64-bit modes.

This is a regression from clang 3.3. 

$ clang-trunk -v
clang version 3.5.0 (trunk 209780)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -O1 small.c; a.out
1
$ clang-trunk -flto -O0 small.c; a.out
1
$ clang-3.3 -flto -O1 small.c; a.out
1
$ 
$ clang-trunk -flto -O1 small.c; a.out
0
$ clang-3.4 -flto -O1 small.c; a.out
0
$ 

--------------------------------

int printf (const char *, ...);

int a = 1, c = 1, d;
volatile int b;

int
fn1 ()
{
  for (; d < 1; d++)
    a = 0;
  if (1 & 1 << b)
    for (;;)
      {
	if (a)
	  break;
	return 0;
      }
  else
    c = 0;
  return 1;
}

int
main ()
{
  fn1 ();
  printf ("%d\n", c);
  return 0;
}

**Comment by fhahn** [comment]
I was unable to reproduce this with Clang 4.0 or newer (https://godbolt.org/z/YEs4rsozT). earlier versions of clang don't seem to work with LTO on godbolt.
