### ISSUE TITLE
wrong code by LTO at -Os and above on x86_64-linux-gnu

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#20281]
|  |  |
| --- | --- |
| Bugzilla Link | [19907](https://llvm.org/bz19907) |
| Version | unspecified |
| OS | All |
| CC | @hfinkel |

## Extended Description 
The current clang trunk miscompiles the following code when using LTO at -Os and above on x86_64-linux-gnu (in both 32-bit and 64-bit modes). 

This is a regression from 3.4. 

$ clang-trunk -v
clang version 3.5.0 (trunk 209947)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
$ 
$ clang-trunk -Os small.c; a.out
$ clang-3.4 -flto -Os small.c; a.out
$ 
$ clang-trunk -flto -Os small.c; a.out
Aborted (core dumped)
$ 

-----------------------------

int a, b, c, d = 1, e, f = 1;

void
fn1 ()
{
  a = 1;
}

int
main ()
{
  fn1 ();

lbl:
  e || (b = 0);
  if (f)
    d = 0;
  if (a)
    {
      c = a;
      f = 0;
      a = 0;
      goto lbl;
    }

  if (c != 1)
    __builtin_abort ();

  return 0;
}

**Comment by fhahn** [comment]
I was unable to reproduce this with Clang 11.0 or newer (https://godbolt.org/z/TGcas11fo). earlier versions of clang don't seem to work with LTO + `-Os` on godbolt.
