### ISSUE TITLE
clang 3.4 crash Running pass 'Value Propagation' on function '@_ZN10ViModeTest23VimStyleCommandBarTestsEv'

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20299]
|  |  |
| --- | --- |
| Bugzilla Link | [19925](https://llvm.org/bz19925) |
| Version | 3.4 |
| OS | FreeBSD |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@hfinkel |

## Extended Description 
Linking CXX executable kateencodingtest
[100%] Built target kateencodingtest
Stack dump:
0.	Program arguments: /usr/bin/c++ -cc1 -triple i386-unknown-freebsd11.0 -emit-obj -disable-free -main-file-name vimode_test.cpp -mrelocation-model static -mdisable-fp-elim -relaxed-aliasing -masm-verbose -mconstructor-aliases -target-cpu corei7 -coverage-file /usr/ports/editors/kate/work/.build/tests/CMakeFiles/vimode_test.dir/vimode_test.o -resource-dir /usr/bin/../lib/clang/3.4.1 -D KDE4_CMAKE_TOPLEVEL_DIR_LENGTH=28 -D KDE_DEPRECATED_WARNINGS -D KTEXTEDITOR_NO_DEPRECATED -D QT_NO_CAST_TO_ASCII -D QT_NO_STL -D QT_USE_FAST_CONCATENATION -D QT_USE_FAST_OPERATOR_PLUS -D _REENTRANT -D NDEBUG -D QT_NO_DEBUG -D _LARGEFILE64_SOURCE -D KDESRCDIR="/usr/ports/editors/kate/work/kate-4.12.5/tests/" -I /usr/ports/editors/kate/work/.build/tests -I /usr/ports/editors/kate/work/kate-4.12.5/tests -I /usr/ports/editors/kate/work/.build -I /usr/ports/editors/kate/work/kate-4.12.5/part -I /usr/ports/editors/kate/work/kate-4.12.5/part/buffer -I /usr/ports/editors/kate/work/kate-4.12.5/part/completion -I /usr/ports/editors/kate/work/kate-4.12.5/part/dialogs -I /usr/ports/editors/kate/work/kate-4.12.5/part/document -I /usr/ports/editors/kate/work/kate-4.12.5/part/script -I /usr/ports/editors/kate/work/kate-4.12.5/part/mode -I /usr/ports/editors/kate/work/kate-4.12.5/part/render -I /usr/ports/editors/kate/work/kate-4.12.5/part/search -I /usr/ports/editors/kate/work/kate-4.12.5/part/syntax -I /usr/ports/editors/kate/work/kate-4.12.5/part/undo -I /usr/ports/editors/kate/work/kate-4.12.5/part/utils -I /usr/ports/editors/kate/work/kate-4.12.5/part/vimode -I /usr/ports/editors/kate/work/kate-4.12.5/part/view -I /usr/ports/editors/kate/work/kate-4.12.5/part/kte5 -I /usr/ports/editors/kate/work/.build/part -I /usr/local/include -I /usr/local/include/KDE -I /usr/local/include/qt4/phonon -I /usr/local/include/qt4/QtXmlPatterns -I /usr/local/include/qt4/QtXml -I /usr/local/include/qt4/QtWebKit -I /usr/local/include/qt4/QtUiTools -I /usr/local/include/qt4/QtTest -I /usr/local/include/qt4/QtSvg -I /usr/local/include/qt4/QtSql -I /usr/local/include/qt4/QtScript -I /usr/local/include/qt4/QtOpenGL -I /usr/local/include/qt4/QtNetwork -I /usr/local/include/qt4/QtHelp -I /usr/local/include/qt4/QtDesigner -I /usr/local/include/qt4/QtDeclarative -I /usr/local/include/qt4/QtDBus -I /usr/local/include/qt4/Qt3Support -I /usr/local/include/qt4/QtGui -I /usr/local/include/qt4/QtCore -I /usr/local/include/qt4/Qt -I /usr/local/share/qt4/mkspecs/default -I /usr/local/include/qt4 -internal-isystem /usr/include/c++/v1 -O2 -Wnon-virtual-dtor -Wno-long-long -Wundef -Wcast-align -Wchar-subscripts -Wall -W -Wpointer-arith -Wformat-security -Woverloaded-virtual -Werror=return-type -Wno-return-type-c-linkage -fdeprecated-macro -fdebug-compilation-dir /usr/ports/editors/kate/work/.build/tests -ferror-limit 19 -fmessage-length 0 -fvisibility hidden -fvisibility-inlines-hidden -mstackrealign -fobjc-runtime=gnustep -fcxx-exceptions -fexceptions -fno-common -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o CMakeFiles/vimode_test.dir/vimode_test.o -x c++ /usr/ports/editors/kate/work/kate-4.12.5/tests/vimode_test.cpp 
1.	<eof> parser at end of file
2.	Per-module optimization passes
3.	Running pass 'CallGraph Pass Manager' on module '/usr/ports/editors/kate/work/kate-4.12.5/tests/vimode_test.cpp'.
4.	Running pass 'Value Propagation' on function '@_ZN10ViModeTest23VimStyleCommandBarTestsEv'
c++: error: unable to execute command: Abort trap (core dumped)
c++: error: clang frontend command failed due to signal (use -v to see invocation)
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: i386-unknown-freebsd11.0
Thread model: posix
c++: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
c++: error: unable to execute command: Abort trap (core dumped)
c++: note: diagnostic msg: Error generating preprocessed source(s).
--- tests/CMakeFiles/vimode_test.dir/vimode_test.o ---
*** [tests/CMakeFiles/vimode_test.dir/vimode_test.o] Error code 254

make[11]: stopped in /usr/ports/editors/kate/work/.build
1 error

make[11]: stopped in /usr/ports/editors/kate/work/.build
--- tests/CMakeFiles/vimode_test.dir/all ---
*** [tests/CMakeFiles/vimode_test.dir/all] Error code 2

make[10]: stopped in /usr/ports/editors/kate/work/.build
1 error

NB Tell me, please, where to find core dumped, so I could attach it?

**Comment by Endilll** [comment]
Core dump link is dead. We can't do much without a preprocessed source even we had a core dump.
Feel free to reopen if you have additional information.
