### ISSUE TITLE
Extra temporaries with should-be-xvalue conditional expressions with operands requiring conversion

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [llvm/llvm-project#20290]
|  |  |
| --- | --- |
| Bugzilla Link | [19916](https://llvm.org/bz19916) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
The conditional operator as implemented by Clang introduces extra temporaries when given a class that can be implicitly converted to an xvalue of the "other type" through a conversion function.

N3290 subclause 5.16 [expr.cond] paragraph 3 applies. Note that the third bullet contains an instance of "rvalue" which was replaced with "prvalue" as an editorial fix.

The source below demonstrates that implicit conversion to `int &&` from the expression `aObj` is possible.
The conditions for the second bullet of [expr.cond]/3 is met.
The conversion in the other direction is not possible.
The end result from the last sentence of [expr.cond]/3 is that both the second and third operand should be considered xvalues of type int for [expr.cond]/4.

### SOURCE:
```console
> cat condExprUDCtoXval_Xval.cc
```
```cpp 
int glob;

struct A {
   operator int &&() { return static_cast<int &&>(glob); }
} aObj;

int &&implicitconvcheck = aObj;
int &&condExprResult = false ? aObj : aObj.operator int &&();

extern "C" int printf(const char *, ...);

int main() {
   printf("address of implicitconvcheck %s consistent with direct binding\n", &implicitconvcheck == &glob ? "is" : "is NOT");
   printf("address of condExprResult %s consistent with direct binding\n", &condExprResult == &glob ? "is" : "is NOT");
   return 0;
}
```
```console
Return:  0x00:0
```

### COMPILER INVOCATION AND OUTPUT:
```console
> clang++ -std=c++11 condExprUDCtoXval_Xval.cc && ./a.out 
address of implicitconvcheck is consistent with direct binding
address of condExprResult is NOT consistent with direct binding
Return:  0x00:0
```

### EXPECTED OUTPUT:
```console
> ./a.out 
address of implicitconvcheck is consistent with direct binding
address of condExprResult is consistent with direct binding
Return:  0x00:0
```

### VERSION INFO:
```console
> clang++ -v
clang version 3.4 (tags/RELEASE_34/final)
Target: powerpc64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/ppc64-redhat-linux/4.4.4
Found candidate GCC installation: /usr/lib/gcc/ppc64-redhat-linux/4.4.6
Selected GCC installation: /usr/lib/gcc/ppc64-redhat-linux/4.4.6
Return:  0x00:0
```

**Comment by zwuis** [comment]
Doesn't reproduce since Clang 3.9.

**Comment by Endilll** [comment]
@zwuis Can you leave Compiler Explorer links that showcase that?

**Comment by zwuis** [comment]
Links are added in my comment above.

**Comment by zwuis** [comment]
I think label "clang:frontend" should be added, not "clang:codegen".
