### ISSUE TITLE
Clang does not define __INTPTR_MAX__

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20335]
|  |  |
| --- | --- |
| Bugzilla Link | [19961](https://llvm.org/bz19961) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
__INTPTR_MAX__ is used by newlib (in stdint.h) if __INTPTR_TYPE__ is defined:

  #ifdef __INTPTR_TYPE__
  #define INTPTR_MIN (-__INTPTR_MAX__ - 1)
  #define INTPTR_MAX __INTPTR_MAX__
  #define UINTPTR_MAX __UINTPTR_MAX__
  #elif defined(__PTRDIFF_TYPE__)
  ...

GCC defines __INTPTR_TYPE__ and __INTPTR_MAX__, but Clang only defines __INTPTR_TYPE__, so using INTPTR_{MIN,MAX} produces an undefined symbol error.

Newlib could be fixed here, but it might be nicer to match GCC's predefined macros.

**Comment by arsenm** [comment]
This was done in ab8d0a0dd514e8313f39e3f09482468577ffe144
