### ISSUE TITLE
clang-format breaks default uniformly initialized function arguments

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#20341]
|  |  |
| --- | --- |
| Bugzilla Link | [19967](https://llvm.org/bz19967) |
| Version | trunk |
| OS | All |

## Extended Description 
The following function: 

```
auto long_enough_function_name(const int i = int{0}) noexcept -> double { 
  return i;
}
```

gets formatted to:

```
auto long_enough_function_name(const int i = int{
                               0}) noexcept -> double { 
  return i;
}
```

which shouldn't be the case.

**Comment by mydeveloperday** [comment]
With the 2 examples you give this is the output with your .clang-format file

As of 2021.12.17 clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 55d392cc30fb36e6361ba71f4b568c093f8b23f3)

As this issue seem resolved I am going to close this issue, but feel free to reopen it if you think there is still an issue

```
auto long_enough_function_name(const int i = int{0}) noexcept -> double {
  return i;
}

struct TypeAbc {
  int a;
};

namespace baaaz {
template <class T> struct struct_in_baaaz { int a; };
}  // namespace baaaz

struct just_a_type {};

template <class T> struct A {
  inline auto foo_aaaa(const TypeAbc nIdx = TypeAbc{0}) const
   -> baaaz::struct_in_baaaz<just_a_type> {
    return {1};
  }
};

int main() { return 0; }
```
