### ISSUE TITLE
raw_string_ostream doesn't set unbuffered

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20353]
|  |  |
| --- | --- |
| Bugzilla Link | [19979](https://llvm.org/bz19979) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
sorry if i got the component wrong. the bug is in Support/raw_ostream.h.

raw_string_ostream subclasses raw_ostream, but doesn't pass any value for the "unbuffered" constructor field. the default is false (or buffered). but no buffer is ever allocated because raw_string_ostream is a wrapper for a std::string.

attempting to work around this bug will always end up in a codepath that tries to delete[] the null buffer, and then sad faces all around.

the fix is simple. around line 441, this:

  explicit raw_string_ostream(std::string &O) : OS(O) {}

should be this:

  explicit raw_string_ostream(std::string &O) : raw_ostream(true), OS(O) {}

**Comment by JOE1994** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/65b13610a5226b84889b923bae884ba395ad084d
