### ISSUE TITLE
ICE during LinkageComputer

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20354]
|  |  |
| --- | --- |
| Bugzilla Link | [19980](https://llvm.org/bz19980) |
| Version | 3.4 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
When compiler below codes using clang 3.4, clang will ICE. I think we should issue an msg or build pass. NOT ICE.

```cpp
void f(int i) {
  extern int i;
}
```

clang: /home/qshanz/work/source/llvm/tools/clang/lib/AST/Decl.cpp:1205: static clang::LinkageInfo clang::LinkageComputer::getLVForDecl(const clang::NamedDecl*, LVComputationKind): Assertion `!Old || Old->getCachedLinkage() == D->getCachedLinkage()' failed.

**Comment by shafik** [comment]
Does not crash on trunk: https://godbolt.org/z/6hq31GKT7

**Comment by Endilll** [comment]
Fixed in Clang 3.5: https://cexplorer.testlabs.pro/z/8PcrdK
