### ISSUE TITLE
not able to install llvm-3.1 with methods given

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20364]
|  |  |
| --- | --- |
| Bugzilla Link | [19990](https://llvm.org/bz19990) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I tried installing llvm 3.1 and failing in each method described on install page.
Steps missing to install.

**Comment by sylvestre** [comment]
Fixed a while back
