### ISSUE TITLE
codegen crash regression r210961

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20412]
|  |  |
| --- | --- |
| Bugzilla Link | [20038](https://llvm.org/bz20038) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie |

## Extended Description 
To reproduce:
$ clang -cc1 -emit-obj -O2 -std=gnu++11 -x c++ testcase.ii

Testcase:
template <typename, typename, typename> struct __sso_string_base;
template <template <typename, typename, typename> class = __sso_string_base> struct __versa_string;
template <typename, typename, typename> struct __sso_string_base {
  template <typename _InputIterator>
  __sso_string_base(_InputIterator, _InputIterator, int);
  ~__sso_string_base();
};

template <template <typename, typename, typename> class _Base>
struct __versa_string : _Base<int, int, int> {
  __versa_string(int, int) : _Base<int, int, int>(0, 0, 0) {}
};
struct basic_string : __versa_string<> {
  basic_string(int = 0) : __versa_string(0, 0) {}
};

static int NamesMatch(basic_string);
struct S {
  char *S_name = GetName();
  S() { S_name && NamesMatch(0); }
  char *GetName();
  basic_string bs;
};

void test() {
  S();
}

**Comment by AaronBallman** [comment]
I am no longer able to reproduce the crash; if you're still able to see the issue, please reopen with additional steps to reproduce.

**Comment by Endilll** [comment]
Doesn't reproduce with assertions builds either: https://cexplorer.testlabs.pro/z/Y1M4f1
