### ISSUE TITLE
"hex sequence out of range" error prevents invalid but probably reasonable code from building

### ISSUE THREAD

**Issue by berolinux** [llvm/llvm-project#20438]
|  |  |
| --- | --- |
| Bugzilla Link | [20064](https://llvm.org/bz20064) |
| Version | trunk |
| OS | All |
| CC | @zygoloid,@rnk |

## Extended Description 
This piece of code fails to build with clang:

memcmp(magic,"\xFD7z",3);

clang (correctly) complains about "\xFD7" being a hex escape sequence out of range -- but there is no "\xFD7" sequence involved here - what the code means (and what gcc takes it to mean) is check for \xFD followed by the string 7z.

Probably the error should be downgraded to a warning because it's entirely possible that someone actually meant "\xFD7" to be a 0xfd7 hex sequence - but it should do what the code means to do anyway.

**Comment by widberg** [comment]
This still causes a warning in GCC and an error in Clang https://godbolt.org/z/jTW44q77r. The previous comment raises good points regarding what can be done about this.

**Comment by cor3ntin** [comment]
@widberg both GCC and clang now accept delimited escapes sequences which make the intent clear https://godbolt.org/z/ee9P8b1zP 

MSVC also rejects `"\xFD7z"`.
I think the potential for bugs here is too great there hasn't been a lot of request for that behavior in the past decade

**Comment by shafik** [comment]
Note both gcc/clang diagnose delimited-escape-sequences w/ `-pedantic`: https://godbolt.org/z/oTTEPsej8

Given that we have a suitable alternative and the potential for bugs with the original feature request I will close this.
