### ISSUE TITLE
clang stack dump

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20444]
|  |  |
| --- | --- |
| Bugzilla Link | [20070](https://llvm.org/bz20070) |
| Version | 3.3 |
| OS | Linux |
| Attachments | [run script](https://user-images.githubusercontent.com/60944935/143749660-8e53e5b8-23dc-4771-984e-af2c5c28fd1c.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Am running a fedora-based appliance in a VM (using VMware Player). When trying to compile C programs, I receive the following error message:

============================================================================

jharvard@appliance (~/Dropbox/pset1): clang hello.c
0  libLLVM-3.3.so 0x4946d3d0 llvm::sys::PrintStackTrace(_IO_FILE*) + 48
1  libLLVM-3.3.so 0x4946d640
2  libLLVM-3.3.so 0x4946d1fc
3                 0xb77a7400 __kernel_sigreturn + 0
4  clang          0x0882bdf0 clang::LookupResult::configure() + 0
5  clang          0x086ec572 clang::Sema::HandleDeclarator(clang::Scope*, clang::Declarator&, llvm::MutableArrayRef<clang::TemplateParameterList*>) + 1314
6  clang          0x086ed0b4 clang::Sema::ActOnDeclarator(clang::Scope*, clang::Declarator&) + 68
7  clang          0x085a79b2 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&) + 98
8  clang          0x085b41a0 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, unsigned int, bool, clang::SourceLocation*, clang::Parser::ForRangeInit*) + 1024
9  clang          0x085b50d6 clang::Parser::ParseSimpleDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, unsigned int, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, bool, clang::Parser::ForRangeInit*) + 886
10 clang          0x085b53f3 clang::Parser::ParseDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, unsigned int, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) + 243
11 clang          0x0859d9c9 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) + 1049
12 clang          0x0859e113 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) + 227
13 clang          0x08595b67 clang::ParseAST(clang::Sema&, bool, bool) + 311
14 clang          0x082773cd clang::ASTFrontendAction::ExecuteAction() + 109
15 clang          0x08402604 clang::CodeGenAction::ExecuteAction() + 52
16 clang          0x08277bd8 clang::FrontendAction::Execute() + 168
17 clang          0x0825095a clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 250
18 clang          0x0823809b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 1611
19 clang          0x08230f16 cc1_main(char const**, char const**, char const*, void*) + 1206
20 clang          0x0822f3ce main + 8926
21 libc.so.6      0x48221963 __libc_start_main + 243
22 clang          0x0822fcd1
Stack dump:
0.	Program arguments: /usr/bin/clang -cc1 -triple i386-redhat-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name hello.c -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu pentium4 -target-linker-version 2.23.52.0.1 -resource-dir /usr/bin/../lib/clang/3.3 -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/clang/3.3/include -internal-externc-isystem /usr/include -internal-externc-isystem /usr/lib/gcc/i686-redhat-linux/4.8.1/include -fdebug-compilation-dir /home/jharvard/Dropbox/pset1 -ferror-limit 19 -fmessage-length 80 -mstackrealign -fobjc-runtime=gcc -fobjc-default-synthesize-properties -fdiagnostics-show-option -fcolor-diagnostics -backend-option -vectorize-loops -o /tmp/hello-wgIcYe.o -x c hello.c 
1.	/usr/bin/../lib/clang/3.3/include/stddef.h:34:35: current parser token ';'
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.3 (tags/RELEASE_33/rc3)
Target: i386-redhat-linux-gnu
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/hello-IFdXxP.c
clang: note: diagnostic msg: /tmp/hello-IFdXxP.sh
clang: note: diagnostic msg: 

********************

============================================================================

I've attempted this with the simplest program I can think of, using no flags, in the hope that this makes tracking the bug easier(?).  HAve also attached the run script (can't attached preprocessed source as only allowed one attachment at a time...?)

**Comment by Endilll** [comment]
Sounds like a terribly broken ancient build.
