### ISSUE TITLE
llvm3.5 debian cmake helper scripts does not work

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20506]
|  |  |
| --- | --- |
| Bugzilla Link | [20132](https://llvm.org/bz20132) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I got my first clang project and tried to compile it with the following cmake script:

 4 cmake_minimum_required(VERSION 2.8)
  5 set(CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH}:/usr/share/llvm-3.5/cmake")
  6 find_package(LLVM)
  7 
  8 include(AddLLVM)
  9 add_definitions(${LLVM_DEFINITIONS})
 10 include_directories(${LLVM_INCLUDE_DIRS})
 11 link_directories(${LLVM_LIBRARY_DIRS})
 12 
 13 #llvm_map_components_to_libraries(REQ_LLVM_LIBRARIES jit native)
 14 
 15 
 16 add_clang_executable(test
 17     main2.cpp
 18     )

Unforutnalty this results in the following error:

CMake Error at /usr/share/llvm-3.5/cmake/LLVMExports.cmake:6 (set_property):
  set_property could not find TARGET LLVMSupport.  Perhaps it has not yet
  been created.
Call Stack (most recent call first):
  /usr/share/llvm-3.5/cmake/LLVMConfig.cmake:43 (include)
  CMakeLists.txt:6 (find_package)

... there will be a lot of simila follow-up errors.

**Comment by arsenm** [comment]
Old build issue
