### ISSUE TITLE
ext_vector_type is not compatible with constexpr

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20531]
|  |  |
| --- | --- |
| Bugzilla Link | [20157](https://llvm.org/bz20157) |
| Version | trunk |
| OS | All |
| Blocks | llvm/llvm-project#30794  |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@RKSimon,@zygoloid |
| Fixed by commit(s) | b30c16670e42 |

## Extended Description 
It seems many uses of a type based on ext_vector_type are not suitable for use in a constexpr, for example:

typedef float __attribute__((ext_vector_type(4))) float4;

constexpr float4 MultiplyByTwo(float4 x)
{
  return x * 2.0f; 
}

main.cpp:3:18: error: constexpr function never produces a constant expression [-Winvalid-constexpr]

constexpr float4 MultiplyByTwo(float4 x)
                 ^
main.cpp:5:12: note: subexpression not valid in a constant expression

  return x * 2.0f; 
           ^
1 error generated.

**Comment by yronglin** [comment]
Vector/ExtVector binary operator was already supported (https://godbolt.org/z/qd1fvMxMb).
