### ISSUE TITLE
vtable layout of __func in <functional> is sensitive to RTTI settings

### ISSUE THREAD

**Issue by rnk** [llvm/llvm-project#20561]
|  |  |
| --- | --- |
| Bugzilla Link | [20187](https://llvm.org/bz20187) |
| Version | unspecified |
| OS | Windows NT |
| CC | @chandlerc,@mclow |

## Extended Description 
This segment of <funcitonal> is worrying:
    virtual void destroy_deallocate() _NOEXCEPT;
    virtual _Rp operator()(_ArgTypes&& ... __arg);
#ifndef _LIBCPP_NO_RTTI
    virtual const void* target(const type_info&) const _NOEXCEPT;
    virtual const std::type_info& target_type() const _NOEXCEPT;
#endif  // _LIBCPP_NO_RTTI
};

What happens if an -frtti and -fno-rtti library both instantiate std::function<void()> and then link together?

Chandler had some ideas about splitting __func in to __func and __func_rtti which extends __func.  If RTTI is enabled, we get an always inline std::function ctor that builds a __func_rtti.  If it is disabled, we get __func.  Only if we call std::function::target* do we static_cast the __func to __func_rtti and call the virtual methods.

**Comment by philnik777** [comment]
I think the ship has sailed here. If we change anything now it will most likely just break someone.
