### ISSUE TITLE
error: no member named `max_align_t` in the global namespace

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20570]
|  |  |
| --- | --- |
| Bugzilla Link | [20196](https://llvm.org/bz20196) |
| Version | 3.4 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
I'm trying to install llvm 3.4.2 (on an 64Bit Ubuntu)

I've checked "https://groups.google.com/forum/#!topic/llvm-dev/mIaY3BCXtf8" and 
"http://reviews.llvm.org/rL201729" which are already in the current version.

I configured via:
```
../configure --enable-optimized --enable-cxx11 --prefix=/somepath/llvm-3.4.2-install
```
Then make gives me:
```
make[1]: Entering directory `local/llvm-3.4.2.src/build/lib/Support'
llvm[1]: Compiling APFloat.cpp for Release+Asserts build
In file included from local/llvm-3.4.2.src/lib/Support/APFloat.cpp:15:
In file included from local/llvm-3.4.2.src/include/llvm/ADT/APFloat.h:20:
In file included from local/llvm-3.4.2.src/include/llvm/ADT/APInt.h:19:
In file included from local/llvm-3.4.2.src/include/llvm/ADT/ArrayRef.h:14:
In file included from local/llvm-3.4.2.src/include/llvm/ADT/SmallVector.h:17:
In file included from local/llvm-3.4.2.src/include/llvm/Support/AlignOf.h:19:
/somelocalpathto/gcc/include/c++/4.9.0/cstddef:51:11: error: no member named 'max_align_t' in the global namespace
  using ::max_align_t;
        ~~^
1 error generated.
make[1]: *** [local/llvm-3.4.2.src/build/lib/Support/Release+Asserts/APFloat.o] Error 1
make[1]: Leaving directory `local/llvm-3.4.2.src/build/lib/Support'
make: *** [all] Error 1
```
(I have some user-installed gcc-4.9.0 where I added the binary path to the `PATH` variable, the libary path to the `LD_LIBRARY_PATH` and the header path to the `C(PLUS)_INCLUDE_PATH`.)

Any hints what to do, or do you need more information on this?

**Comment by Endilll** [comment]
Feel free to reopen if you encounter this issue building a supported version of Clang using a toolchain that satisfies minimum requirements.
