### ISSUE TITLE
LongjmpTestCase tests fail on Linux

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20605]
|  |  |
| --- | --- |
| Bugzilla Link | [20231](https://llvm.org/bz20231) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Failed on Linux x86_64, consistently, Ubuntu 14.04 LTS x86_64 using clang-based build.

May be related to these bugs:
llvm.org/pr16769
llvm.org/pr17214

**Comment by DavidSpickett** [comment]
No info on what test case exactly, no reproducer, we don't have any known issues with longjmp. Closing.
