### ISSUE TITLE
The clang-cl driver driver invokes the driver by spawning a new process

### ISSUE THREAD

**Issue by ehsan** [llvm/llvm-project#20627]
|  |  |
| --- | --- |
| Bugzilla Link | [20253](https://llvm.org/bz20253) |
| Version | trunk |
| OS | All |
| CC | @asl,@majnemer,@zmodem,@jrmuizel,@rnk |

## Extended Description 
Doing work by creating a new process is awfully slow on Windows.  Can we avoid doing this and invoke -cc1 in-process?

**Comment by Endilll** [comment]
We either support this already or not going to support this in foreseeable future.

CC @AaronBallman

**Comment by AaronBallman** [comment]
You can pass `/clang:-fintegrated-cc1` to disable running cc1 as a separate process from clang-cl, so I believe this can be closed as completed.
