### ISSUE TITLE
TestMultipleDebuggers intermittently failing

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20656]
|  |  |
| --- | --- |
| Bugzilla Link | [20282](https://llvm.org/bz20282) |
| Version | unspecified |
| OS | Linux |
| Attachments | [MacOSX 10.9.4 error log for TestMultipleDebuggers.](https://user-images.githubusercontent.com/60944935/143749726-ab86ebc5-6e29-4497-9fb4-662bfb32fdd9.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @emaste,@vedantk |

## Extended Description 

Keeping test, marking as XFAIL.

Attached: error from MacOSX.

**Comment by DavidSpickett** [comment]
Closing this as a duplicate of https://github.com/llvm/llvm-project/issues/101162.
