### ISSUE TITLE
wrong tokenization around invalid UCNs

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#20686]
|  |  |
| --- | --- |
| Bugzilla Link | [20312](https://llvm.org/bz20312) |
| Version | unspecified |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Consider:

  #define X(a) y##a
  #define yx Q(
  #define Q(x)
  X(x\u200e))

This code is ill-formed: it contains the identifier token 'x\u200e' which contains the UCN '\u200e' which is not permitted in an identifier.

Clang treats this as two tokens instead, and as a result accepts the above ill-formed code. This similar case is correctly rejected:

  X(x\u0065))

**Comment by cor3ntin** [comment]
Fixed in Clang 14.0
