### ISSUE TITLE
recent header breakage in clang

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20700]
|  |  |
| --- | --- |
| Bugzilla Link | [20326](https://llvm.org/bz20326) |
| Version | trunk |
| OS | All |
| Attachments | [diff of preprocessed source from clang svn vs that from clang 3.4.2](https://user-images.githubusercontent.com/60944935/143749751-9d1330d1-5708-42d5-a785-e489a338d7c2.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dexonsmith,@zygoloid |

## Extended Description 
Since around Jul 12th, clang trunk has been broken on darwin11 with the simple test case…

#include <stdio.h>

main()
{
	printf("hello, world\n");
}

producing the error…

% /sw/opt/llvm-3.5.0/bin/clang hello.c
In file included from hello.c:2:
/usr/include/stdio.h:85:9: error: unknown type name '__darwin_off_t'
typedef __darwin_off_t          fpos_t;
        ^
/usr/include/stdio.h:414:9: error: unknown type name '__darwin_off_t'
typedef __darwin_off_t          off_t;
        ^
hello.c:4:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
main()
^~~~
1 warning and 2 errors generated.

**Comment by arsenm** [comment]
Old build issue
