### ISSUE TITLE
wrong initialization after template instantiation for aggregate initialization that implicitly default-constructs

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#20724]
|  |  |
| --- | --- |
| Bugzilla Link | [20350](https://llvm.org/bz20350) |
| Version | unspecified |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Clang rejects-valid on this:

namespace NoExtraCopy {
  struct S { S(); S(const S&) = delete; };
  struct T { S s; };
  template<typename> void f() {
    T t = {};
  }
  template void f<int>();
}

... because the template instantiation of the initializer initializes the S subobject from the existing CXXConstructExpr, resulting in an unnecessary move construction.

We should either make TreeTransform::TransformInitializer recurse through InitListExprs (and throw away things that were implied), or (better) not redo initialization sequence formation during template instantiation if we succeeded in building the initialization sequence in the initial parse.

(In the latter case, we'd probably benefit from an AST node representing a dependent initialization sequence, so we can get TreeTransform to rerun the initialization step where needed.)

**Comment by wheatman** [comment]
This was fixed between 3.6 and 3.7
https://godbolt.org/z/d3ccGnxbW

code
```
namespace NoExtraCopy {
  struct S { S(); S(const S&) = delete; };
  struct T { S s; };
  template<typename> void f() {
    T t = {};
  }
  template void f<int>();
}

```

old error
```
<source>:5:12: error: call to deleted constructor of 'NoExtraCopy::S'
    T t = {};
           ^
<source>:7:17: note: in instantiation of function template specialization 'NoExtraCopy::f<int>' requested here
  template void f<int>();
                ^
<source>:2:19: note: 'S' has been explicitly marked deleted here
  struct S { S(); S(const S&) = delete; };
                  ^
1 error generated.
Compiler returned: 1
```
