### ISSUE TITLE
The binary tarballs are missing .tar in the extension.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20738]
|  |  |
| --- | --- |
| Bugzilla Link | [20364](https://llvm.org/bz20364) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The latest binary tarballs (3.4.2) all end with a .xz and should end with .tar.xz.

Here's an example link from the releases page for 3.4.2:

    http://llvm.org/releases/3.4.2/clang+llvm-3.4.2-x86_64-unknown-ubuntu12.04.xz

**Comment by arsenm** [comment]
Old packaging, I see .tar.gz now
