### ISSUE TITLE
Poor first diagnostic on ambiguous namespace reference

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#20747]
|  |  |
| --- | --- |
| Bugzilla Link | [20373](https://llvm.org/bz20373) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@zygoloid,@Weverything |

## Extended Description 
Nicos-MacBook-Pro:src thakis$ cat test.cc
namespace Foo { class Bar {}; }

namespace A = Foo;
namespace { namespace A = Foo; }

void f() {
  A::Bar b;
}
Nicos-MacBook-Pro:src thakis$ ~/src/llvm-build/bin/clang -c test.cc
test.cc:7:3: error: 'A' is not a class, namespace, or scoped enumeration
  A::Bar b;
  ^
test.cc:7:3: error: reference to 'A' is ambiguous
  A::Bar b;
  ^
test.cc:3:11: note: candidate found by name lookup is 'A'
namespace A = Foo;
          ^
test.cc:4:23: note: candidate found by name lookup is '(anonymous namespace)::A'
namespace { namespace A = Foo; }
                      ^
2 errors generated.

The second error is great, but the first shouldn't be there. We had this bug somewhere and were building with -ferror-limit=1 for some reason, and due to that first diagnostic it took me longer to understand what's going on than it should have.

**Comment by xgupta** [comment]
This is fixed on trunk, it seems, no error: 'B' is not a class, namespace, or scoped enumeration -  https://godbolt.org/z/jjPM3Y5Yq.
