### ISSUE TITLE
libc++abi :: test_demangle.cpp relies on implementation-defined behaviour and fails on FreeBSD 9.2

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20810]
|  |  |
| --- | --- |
| Bugzilla Link | [20436](https://llvm.org/bz20436) |
| Version | unspecified |
| OS | FreeBSD |
| Reporter | LLVM Bugzilla Contributor |
| CC | @emaste,@mclow |

## Extended Description 
libc++abi :: test_demangle.cpp fails on:

FreeBSD localhost 9.2-RELEASE FreeBSD 9.2-RELEASE #&#8203;0 r255898: Thu Sep 26 22:50:31 UTC 2013     root@bake.isc.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

when run as:

make check-all

Here's the log:
******************** TEST 'libc++abi :: test_demangle.cpp' FAILED ********************
Compiled With: '/usr/bin/clang++' '-o' '/tmp/tmpPNdBTLexe' '/usr/home/ik/llvm/llvm.current/projects/libcxxabi/test/test_demangle.cpp' '-nostdinc++' '-std=c++11' '-I/usr/home/ik/llvm/llvm.current/projects/libcxxabi/test/../include' '-I/usr/home/ik/llvm/llvm.current/projects/libcxx/include' '-nodefaultlibs' '-L/usr/home/ik/llvm/llvm.current.build/lib' '-lc++' '-lc++abi' '-lgcc_eh' '-lc' '-lm' '-lpthread' '-lgcc_s' '-Wl,-R' '/usr/home/ik/llvm/llvm.current.build/lib'
Command: '/tmp/tmpPNdBTLexe'
Exit Code: -6
Standard Output:
--
_ZN5test01hIfEEvRAcvjplstT_Le4001a000000000000000E_c -> void test0::h<float>(char (&) [(unsigned int)((sizeof (float)) + (0xap-1L))])
Got instead: void test0::h<float>(char (&) [(unsigned int)((sizeof (float)) + (0x1.4p+2L))])
--Standard Error:
--
Assertion failed: (std::strcmp(demang, cases[i][1]) == 0), function test, file /usr/home/ik/llvm/llvm.current/projects/libcxxabi/test/test_demangle.cpp, line 29628.
--

Compiled test failed unexpectedly!
********************

**Comment by ldionne** [comment]
We have been running this test successfully on FreeBSD (in our CI) for a while, closing.
