### ISSUE TITLE
error message trying to open core file without read permission is unclear

### ISSUE THREAD

**Issue by emaste** [llvm/llvm-project#20812]
|  |  |
| --- | --- |
| Bugzilla Link | [20438](https://llvm.org/bz20438) |
| Version | unspecified |
| OS | FreeBSD |

## Extended Description 
I ended up with a core file unreadable by a non-root user.  The message produced by lldb in this case is misleading:

% lldb /usr/local/bin/pkg -c pkg.core
error: Unable to find process plug-in for core file '/tank/ports/ports-mgmt/pkg/pkg.core'
(lldb)

**Comment by DavidSpickett** [comment]
Somewhere in the last decade this got fixed :)

```
$ file linux-aarch64-neon.core
linux-aarch64-neon.core: regular file, no read permission
$ ./bin/lldb --core linux-aarch64-neon.core
(lldb) target create --core "linux-aarch64-neon.core"
error: Cannot open '/home/david.spickett/build-llvm-aarch64/linux-aarch64-neon.core': Permission denied.
```
