### ISSUE TITLE
Internal error: getKind() == Template && "Unexpected kind"

### ISSUE THREAD

**Issue by eschnett** [llvm/llvm-project#20832]
|  |  |
| --- | --- |
| Bugzilla Link | [20458](https://llvm.org/bz20458) |
| Version | trunk |
| OS | All |
| Attachments | [run script](https://user-images.githubusercontent.com/92601316/143749804-345f899f-383f-4664-8127-bf9187228e5a.gz) |

## Extended Description 

I am using clang 3.4.2 with libstdc++ of gcc 4.9.0 on OS X. When executing this command:

/Users/eschnett/SIMFACTORY/llvm-3.4.2/install/bin/clang++ -std=c++11 -c -x c++ tree.i

I encounter this internal error:

{{{
Assertion failed: (getKind() == Template && "Unexpected kind"), function getAsTemplate, file /Users/eschnett/SIMFACTORY/llvm-3.4.2/src/llvm-3.4.2.src/tools/clang/lib/Sema/../../include/clang/AST/TemplateBase.h, line 264.
0  libLLVM-3.4.dylib 0x000000010cb1fb62 llvm::sys::PrintStackTrace(__sFILE*) + 34
Stack dump:
0.	Program arguments: /Users/eschnett/SIMFACTORY/llvm-3.4.2/install/bin/clang -cc1 -triple x86_64-apple-macosx10.9.0 -emit-obj -mrelax-all -disable-free -main-file-name tree.i -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 236.3 -coverage-file /tmp/cc/mpi-rpc/tree.o -resource-dir /Users/eschnett/SIMFACTORY/llvm-3.4.2/install/bin/../lib/clang/3.4.2 -stdlib=libc++ -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /tmp/cc/mpi-rpc -ferror-limit 19 -fmessage-length 80 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.9.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-slp -o tree.o -x c++ tree.i 
1.	<eof> parser at end of file
2.	./cxx_foldable.hh:47:1: instantiating function definition 'foldl'
clang: error: unable to execute command: Illegal instruction: 4
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.4.2 (tags/RELEASE_34/dot2-final)
Target: x86_64-apple-darwin13.3.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/gl/zvl8d6415vsbkd50nnll95k40000gs/T/tree-2dac1a.cpp
clang: note: diagnostic msg: /var/folders/gl/zvl8d6415vsbkd50nnll95k40000gs/T/tree-2dac1a.sh
clang: note: diagnostic msg: 

********************
}}}

I attach the preprocessed source and the run script.

**Comment by shafik** [comment]
The smaller repro does not reproduce on trunk anymore: https://godbolt.org/z/v97EPjvbv

I have not tried the original.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 7:
https://cexplorer.testlabs.pro/z/Pn4Pn6
https://godbolt.org/z/zqrKse7eh
