### ISSUE TITLE
clang 3.4.2 fails on Ubuntu 14.04.1

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20844]
|  |  |
| --- | --- |
| Bugzilla Link | [20470](https://llvm.org/bz20470) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @BenPope,@sylvestre |

## Extended Description 
I downloaded the pre-built binaries clang+llvm-3.4.2-x86_64-linux-gnu-ubuntu-14.04 to my Ubuntu 14.04.1 system (Linux LC2430HD 3.13.0-32-generic #&#8203;57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux).

When I try to run clang, I get the error message "clang: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by clang)".

Note that I am using the standard "gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)" included in this version of Ubuntu.  Its version of libstdc++ (/usr/lib/x86_64-linux-gnu/libstdc++.so.6) seems to provide only GLIBCXX_3.4.19.  I have seen reports of what appears to be a related bug in the "opposite direction", where some version of clang wants GLIBCXX_3.4.19 but the user has installed gcc 4.9, which I think is not due to be included in Ubuntu until version 14.10.

Any ideas about this apparent incompatibility between the pre-built binaries of clang 3.4.2 and my Ubuntu 14.04.1 system?

**Comment by sylvestre** [comment]
We are now good
