### ISSUE TITLE
scan-build scripts should be part of binary package

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20854]
|  |  |
| --- | --- |
| Bugzilla Link | [20480](https://llvm.org/bz20480) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The scan-build scripts (c++-analyzer, ccc-analyzer, scan-build) should be included in the binary package. They are required to use the static analyzer. Eventually (#4250) they will be replaced, but until then they should be included.

**Comment by sylvestre** [comment]
it is now the case
