### ISSUE TITLE
Feature request: Option to keep constructor initializer ':' on same line as constructor

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#20873]
|  |  |
| --- | --- |
| Bugzilla Link | [20499](https://llvm.org/bz20499) |
| Version | trunk |
| OS | All |

## Extended Description 
I'm working in a code base that uses tabs for indentation. With tabs, it's more natural to write

```
CPDF_VariableText::CPDF_VariableText() :
    m_bInitial(FALSE),
    m_pVTProvider(NULL),
    m_pVTIterator(NULL),
    m_bRichText(FALSE),
```

instead of

```
CPDF_VariableText::CPDF_VariableText()
    : m_bInitial(FALSE),
      m_pVTProvider(NULL),
      m_pVTIterator(NULL),
      m_bRichText(FALSE),
```

because then you only have 1 leading tab on each line, not one tab and either ':' space or 2 spaces.

(The project uses allman brace style, so the constructor body and the initializer list having the same indent isn't a problem.)

**Comment by mydeveloperday** [comment]
Isn't this just `BreakConstructorInitializers: AfterColon` see https://clang.llvm.org/docs/ClangFormatStyleOptions.html

`BreakConstructorInitializers: AfterColon`

```
CPDF_VariableText::CPDF_VariableText() :
    m_bInitial(FALSE), m_pVTProvider(NULL), m_pVTIterator(NULL),
    m_bRichText(FALSE) {}
```
As I think this is fixed I am going to close this, but feel free to reopen if you think this isn't quite what you expect
