### ISSUE TITLE
Implement debug mode for remaining containers.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20888]
|  |  |
| --- | --- |
| Bugzilla Link | [20514](https://llvm.org/bz20514) |
| Version | unspecified |
| OS | All |
| Blocks | llvm/llvm-project#17211  |
| Reporter | LLVM Bugzilla Contributor |
| CC | @gnzlbg,@JoeLoser,@mclow |

## Extended Description 
Debug mode is currently in a very sorry state. This bug is meant to track the progress of fixing and documenting debug mode.

As I understand it there are two levels of debug mode.

_LIBCPP_DEBUG = 0:
  - Does not required that the dynlib was built in debug mode. 

_LIBCPP_DEBUG = 1:
  - Requires that the dynlib was compiled with _LIBCPP_DEBUG = 1.
  - There is currently no cmake switch to compile for debug mode.
  

My first priority is going to be to get everything compiling with _LIBCPP_DEBUG = 0. Once that is done the next step will be to document what _LIBCPP_DEBUG = 0 actually does and how to use it.

Once _LIBCPP_DEBUG = 0 is fixed I will try and tackle _LIBCPP_DEBUG = 1. 

In order to test debug mode some changes are going to have to be made to the structure of the testsuite. There is currently no clear place to put debug mode tests. I think we need to decide where these tests should live in the current testsuite.

Along with the test suffixs "pass.cpp" and "fail.cpp" I propose we add a new test suffix "rt-fail.cpp" which specifies that a test is expected to compile, run and exit with a non-zero code. This is needed to test that the debug mode assertions fire when they should.

**Comment by ldionne** [comment]
Closing since we removed the debug mode in favour of the hardening modes. We are not at feature parity yet with the legacy debug mode, but I don't think this bug brings a lot of value staying open.
