### ISSUE TITLE
clang: error: clang frontend command failed due to signal 2 (use -v to see invocation)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20893]
|  |  |
| --- | --- |
| Bugzilla Link | [20519](https://llvm.org/bz20519) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
pi@raspberrypi ~/src/dysnomia $ clang++ --version
Debian clang version 3.0-6.2 (tags/RELEASE_30/final) (based on LLVM 3.0)
Target: arm-unknown-linux-gnueabihf
Thread model: posix

fatal error: too many errors emitted, stopping now [-ferror-limit=]
Stack dump:
0.	Program arguments: /usr/bin/clang -cc1 -triple armv4t-unknown-linux-gnueabihf -S -disable-free -disable-llvm-verifier -main-file-name Chat.cpp -mrelocation-model static -mdisable-fp-elim -mconstructor-aliases -target-abi apcs-gnu -target-cpu arm1136jf-s -mfloat-abi hard -target-linker-version 2.22 -momit-leaf-frame-pointer -g -coverage-file /tmp/Chat-p8dWHc.s -resource-dir /usr/bin/../lib/clang/3.0 -I WebFramework/ -I /usr/local/include -fmodule-cache-path /var/tmp/clang-module-cache -internal-isystem /usr/include/c++/4.6 -internal-isystem /usr/include/c++/4.6/arm-linux-gnueabihf -internal-isystem /usr/include/c++/4.6/backward -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/clang/3.0/include -internal-externc-isystem /usr/include/arm-linux-gnueabihf -internal-externc-isystem /usr/include -Wall -std=c++11 -fdeprecated-macro -ferror-limit 19 -fmessage-length 165 -fno-signed-char -fgnu-runtime -fobjc-runtime-has-arc -fobjc-runtime-has-weak -fobjc-fragile-abi -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/Chat-p8dWHc.s -x c++ Dysnomia/controller/Chat.cpp 
1.	WebFramework/WebFramework/controller/../session/Session.h:53:19: current parser token '.'
2.	WebFramework/WebFramework/controller/../session/Session.h:14:1: parsing namespace 'framework'
3.	WebFramework/WebFramework/controller/../session/Session.h:21:5: parsing namespace 'session'
4.	WebFramework/WebFramework/controller/../session/Session.h:24:9: parsing struct/union/class body 'Session'
5.	WebFramework/WebFramework/controller/../session/Session.h:49:13: parsing function body 'loadModel'
6.	WebFramework/WebFramework/controller/../session/Session.h:49:13: in compound statement ('{}')
clang: error: unable to execute command: Segmentation fault
clang: error: clang frontend command failed due to signal 2 (use -v to see invocation)
clang: note: diagnostic msg: Please submit a bug report to http://llvm.org/bugs/ and include command line arguments and all diagnostic information.
clang: note: diagnostic msg: Preprocessed source(s) are located at:
clang: note: diagnostic msg: /tmp/Chat-XH7Gmp.ii
make: *** [Dysnomia/controller/Chat.o] Error 254

Same code does not fail on Ubuntu and OSX

**Comment by Endilll** [comment]
Unfortunately, we can't do much without preprocessed source.
Feel free to reopen if you have additional information.
