### ISSUE TITLE
Clang incorrect applies conversion when built-in operator is selected by overload resolution

### ISSUE THREAD

**Issue by 7318a870-54d1-4d9b-a5cf-8ce660251251** [llvm/llvm-project#20901]
|  |  |
| --- | --- |
| Bugzilla Link | [20527](https://llvm.org/bz20527) |
| Version | 3.4 |
| OS | All |
| CC | @DougGregor |

## Extended Description 
N3936 13.3.1.2 [over.match.oper]/p7 specifies that 

If a built-in candidate is selected by overload resolution, the operands of class type are converted to the types of the corresponding parameters of the selected operation function, except that the second standard conversion sequence of a user-defined conversion sequence (13.3.3.1.2) is not applied. Then the operator is treated as the corresponding built-in operator and interpreted according to Clause 5.

In particular, only operands of class type are converted before the operator is treated as a built-in and interpreted according to Clause 5, and even then the second standard conversion sequence (after the user-defined conversion) is not applied.

The following example is given in the standard:

struct X {
operator double();
};
struct Y {
operator int*();
};
int *a = Y() + 100.0; // error: pointer arithmetic requires integral operand
int *b = Y() + X(); // error: pointer arithmetic requires integral operand

However, clang 3.4 accepts this code, producing no error on either line.
http://coliru.stacked-crooked.com/a/25bcc0549a19921f

**Comment by wheatman** [comment]
This was fixed between 6 and 7
https://godbolt.org/z/ddbq83x56

code
```
struct X {
operator double();
};
struct Y {
operator int*();
};
int *a = Y() + 100.0; // error: pointer arithmetic requires integral operand
int *b = Y() + X(); // error: pointer arithmetic requires integral operand
```

new errors
```
<source>:7:14: error: invalid operands to binary expression ('Y' and 'double')
int *a = Y() + 100.0; // error: pointer arithmetic requires integral operand
         ~~~ ^ ~~~~~
<source>:5:1: note: first operand was implicitly converted to type 'int *'
operator int*();
^
<source>:8:14: error: invalid operands to binary expression ('Y' and 'X')
int *b = Y() + X(); // error: pointer arithmetic requires integral operand
         ~~~ ^ ~~~
<source>:5:1: note: first operand was implicitly converted to type 'int *'
operator int*();
^
<source>:2:1: note: second operand was implicitly converted to type 'double'
operator double();
^
2 errors generated.
Compiler returned: 1
```
