### ISSUE TITLE
Some MCJIT tests are failing under GNU/Linux i386

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#20960]
|  |  |
| --- | --- |
| Bugzilla Link | [20586](https://llvm.org/bz20586) |
| Version | trunk |
| OS | Linux |

## Extended Description 
These tests are failing:
    LLVM :: ExecutionEngine/MCJIT/cross-module-sm-pic-a.ll
    LLVM :: ExecutionEngine/MCJIT/eh-lg-pic.ll
    LLVM :: ExecutionEngine/MCJIT/eh-sm-pic.ll
    LLVM :: ExecutionEngine/MCJIT/hello-sm-pic.ll
    LLVM :: ExecutionEngine/MCJIT/multi-module-sm-pic-a.ll
    LLVM :: ExecutionEngine/MCJIT/remote/cross-module-sm-pic-a.ll
    LLVM :: ExecutionEngine/MCJIT/remote/multi-module-sm-pic-a.ll
    LLVM :: ExecutionEngine/MCJIT/remote/test-global-init-nonzero-sm-pic.ll
    LLVM :: ExecutionEngine/MCJIT/remote/test-ptr-reloc-sm-pic.ll
    LLVM :: ExecutionEngine/MCJIT/stubs-sm-pic.ll
    LLVM :: ExecutionEngine/MCJIT/test-global-init-nonzero-sm-pic.ll
    LLVM :: ExecutionEngine/MCJIT/test-ptr-reloc-sm-pic.ll

FAIL: LLVM :: ExecutionEngine/MCJIT/eh-sm-pic.ll (6187 of 11364)
******************** TEST 'LLVM :: ExecutionEngine/MCJIT/eh-sm-pic.ll' FAILED ********************
Script:
--
/tmp/buildd/llvm-toolchain-snapshot-3.6~svn215184/build-llvm/Release/bin/lli -use-mcjit -relocation-model=pic -code-model=small /tmp/buildd/llvm-toolchain-snapshot-3.6~svn215184/test/ExecutionEngine/MCJIT/eh-sm-pic.ll
--
Exit Code: 1

Command Output (stderr):
--
LLVM ERROR: Program used external function '_GLOBAL_OFFSET_TABLE_' which could not be resolved!

--

All failures are the same.

**Comment by arsenm** [comment]
Old build issue
