### ISSUE TITLE
Assertion failure writing .ast files when class data member initializers contain Block expressions

### ISSUE THREAD

**Issue by tahonermann** [llvm/llvm-project#20968]
|  |  |
| --- | --- |
| Bugzilla Link | [20594](https://llvm.org/bz20594) |
| Version | trunk |
| OS | Linux |
| CC | @synopsys-sig-compiler-frontends |

## Extended Description 
The following test cases compile to object code successfully, but fail an
assertion when a .ast file is emitted.  The assertion failure has been reproduced with Clang 3.4 and Clang trunk (r214770).

$ cat t.cpp
struct S {
    static void(^bp)();
};
void(^S::bp)() = ^{};

$ cat t-cxx11.cpp
struct S {
    void(^bp)() = ^{};
};

$ clang --version
clang version 3.6.0 (trunk 214770)
Target: x86_64-unknown-linux-gnu
Thread model: posix

$ clang -fblocks -c t.cpp
<no error>

$ clang -fblocks -c t.cpp -emit-ast
clang: .../lib/AST/DeclBase.cpp:701: bool clang::Decl::AccessDeclContextSanity() const: Assertion `Access != AS_none && "Access specifier is AS_none inside a record decl"' failed.
...

$ clang -fblocks -std=c++11 -c t-cxx11.cpp
<no error>

$ clang -fblocks -std=c++11 -c t-cxx11.cpp -emit-ast
clang: .../lib/AST/DeclBase.cpp:701: bool clang::Decl::AccessDeclContextSanity() const: Assertion `Access != AS_none && "Access specifier is AS_none inside a record decl"' failed.
...

**Comment by Endilll** [comment]
Appears to be fixed in Clang 6: https://cexplorer.testlabs.pro/z/ezbP8T
