### ISSUE TITLE
Non conformance caused by `_Stream&& operator<<(_Stream&& __os, const _Tp& __x)`

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20970]
|  |  |
| --- | --- |
| Bugzilla Link | [20596](https://llvm.org/bz20596) |
| Version | unspecified |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
The following snippets compiles successfully with clang++ on MacOS X 10.9.4
```console
$ clang --version
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.3.0
Thread model: posix
```
---
```cpp
#include <string>
#include <iostream>
#include <sstream>

void print(const std::string& s)
{
  std::cout << s << std::endl;
}

int main()
{
  int v = 1;
  print((std::ostringstream() << "value: " << v).str());
  return 0;
}
```
The type of `ostringstream() << "value: "` is rvalue `ostringstream`.
While it should be lvalue `ostream`.

According to the addition of the following operator in C++11,
```cpp
template< class CharT, class Traits, class T >
basic_ostream< CharT, Traits >& operator<<( basic_ostream<CharT,Traits>&& os, 
                                            const T& value );
```
The code sample above should be written the following way:
```cpp
print(static_cast<std::ostringstream&>(std::ostringstream() << "value: " << v).str());
```
But then, clang++ with libc++ returns the following error message:
```console
$ clang++ --std=c++11 -g main.cpp
main.cpp:13:9: error: non-const lvalue reference to type 'basic_ostringstream<[3 * ...]>' cannot bind to a temporary of type 'basic_ostringstream<[3 * ...]>'
  print(static_cast<std::ostringstream&>(std::ostringstream() << "value: " << v).str());
```

---
In the end, the most reliable way to achieve that one-liner is to write:
```cpp
print(static_cast<std::ostringstream&>(std::ostringstream().flush() << "value: " << v).str());
```
Now it compiles successfully and works as expected with G++, clang++ (libstdc++ or libc++) and also MSVC++ 2012. Either in C++2003 or C++11. Note that in the case of MSVC++ 2012, I went for `flush()` instead of `seekp(0)` because `seekp(0)` on a newly constructed `ostringstream` sets the `failbit`...

**Comment by frederick-vs-ja** [comment]
Let's close this as LWG1203 is implemented in 12.0.
