### ISSUE TITLE
get svn requests out of access_log

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#2099]
|  |  |
| --- | --- |
| Bugzilla Link | [1727](https://llvm.org/bz1727) |
| Version | unspecified |
| OS | MacOS X |

## Extended Description 
The access_log is getting bloated, we need to filter PROPFIND requests out in httpd.conf.  Here's an example that could be adapted to do this:

http://www.webmasterworld.com/forum92/1795.htm

It is filtering propfind requests to a separate file.

-Chris

**Comment by tlattner** [comment]
We moved to GitHub, closing this.
