### ISSUE TITLE
Top half of __m256i is not filled when returned from a function

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21035]
|  |  |
| --- | --- |
| Bugzilla Link | [20661](https://llvm.org/bz20661) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Test case](https://user-images.githubusercontent.com/60944935/143749888-abfc4e17-daf1-4a49-b30f-d39a624468a8.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 

When returning an std::array (or boost::array) of __m256i, the top half of the vector is not filled. In the attached test case, assigning t to a works as expected but when t is assigned to c via the eval function, the top half of the vector is lost. 

This also works with g++.

**Comment by wheatman** [comment]
This was fixed between 3.5.2 and 3.6
https://godbolt.org/z/Goeohc3os

code
```
#include <iostream>

#include <array>
#include <immintrin.h>

typedef __m256i n_t;

std::ostream& operator<<(std::ostream& os, __m256i const& a)
{
  __attribute__((aligned(32))) int b[8];
  _mm256_store_si256((__m256i*)b,a);

  for (std::size_t ii=0;ii<8;ii++)
    os<<b[ii]<<" ";
  os<<'\n';
  return os;
}

std::array<n_t,1> eval(n_t const& a)
{
  std::array<n_t,1> b;
  b[0]=a;
  std::cout<<" b "<< b[0]<<'\n';
  return b;
}

int main()
{
  std::array<n_t,1> a;

  n_t t = _mm256_set1_epi32(1);
  a[0]=t;

  std::cout<<" a " << a[0]<<'\n';

  std::array<n_t,1> c = eval(t);

  std::cout<<" c " << c[0]<<'\n';
}

```

old output
```
ASM generation compiler returned: 0
Execution build compiler returned: 0
Program returned: 0
 a 1 1 1 1 1 1 1 1 

 b 1 1 1 1 1 1 1 1 

 c 1 1 1 1 6300020 0 6299728 0 

```

new output
```
ASM generation compiler returned: 0
Execution build compiler returned: 0
Program returned: 0
 a 1 1 1 1 1 1 1 1 

 b 1 1 1 1 1 1 1 1 

 c 1 1 1 1 1 1 1 1 

```
