### ISSUE TITLE
clang-format c comment in preprocessor macro

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21069]
|  |  |
| --- | --- |
| Bugzilla Link | [20695](https://llvm.org/bz20695) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [Code to apply clang-format to](https://user-images.githubusercontent.com/60944935/143749901-9afadae8-370c-48ae-9c2b-d3cdafb77d2b.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @insertinterestingnamehere,@mydeveloperday |

## Extended Description 

I have a multi-line macro that has a C-style comment in the middle of it.  When I attempt to run clang-format over it extra '\' are placed and line breaks are unexpected.

Running clang-format multiple times over the code makes the problem worse.

I am using the Visual Studio plugin installer, based on SVN r215355.

**Comment by mkurdej** [comment]
Closing as no new info is available and the problem has been probably solved.
