### ISSUE TITLE
clang-format comment in preprocessor macro causes assert fail

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21070]
|  |  |
| --- | --- |
| Bugzilla Link | [20696](https://llvm.org/bz20696) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [File to run clang-format on](https://user-images.githubusercontent.com/60944935/143749902-7c8fb6c6-c055-40a8-9388-6d35dfdd114d.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Given the attached file, when I run clang-format from inside Visual Studio it pops up a dialog box that says:

Error while running clang-format:

Can't find usable .clang-format, using LLVM styel
Assertion failed: TokenText.startswith("/*") &&
TokenText.endswith("*/"), file
..\tools\clang\lib\Format\BreakableToken.cpp, line 257

I am using Visual Studio plugin installer, based on SVN r215355.

**Comment by mkurdej** [comment]
Fixed probably in clang 9 or before.
