### ISSUE TITLE
Path to clang-format style file

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#21127]
|  |  |
| --- | --- |
| Bugzilla Link | [20753](https://llvm.org/bz20753) |
| Version | trunk |
| OS | All |
| CC | @jamadagni |

## Extended Description 
I would like to pass a path to the style file to be used by clang-format. 

This would allow clang-format to work on _any_ project directory structure e.g. independently from where the style-file (or multiple style files) are located.

**Comment by mydeveloperday** [comment]
https://reviews.llvm.org/D72326

**Comment by mkurdej** [comment]
Fixed in b9e173fcd46b336b5589f577a74de9472d4deae3.
