### ISSUE TITLE
Assertion on attempt to define class in class template with the same name

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [llvm/llvm-project#21136]
|  |  |
| --- | --- |
| Bugzilla Link | [20762](https://llvm.org/bz20762) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

### SOURCE:
$ cat redefTmplInjClassName.cc 
template <class T> struct Y {
   struct Y { };
};

### COMPILER INVOCATION AND OUTPUT:
$ clang -cc1 -x c++ -std=c++03 redefTmplInjClassName.cc 
clang: /build/clang/src/llvm/include/llvm/Support/Casting.h:223: typename std::enable_if<(! llvm::is_simple_type<Y>::value), typename llvm::cast_retty<X, const Y>::ret_type>::type llvm::cast(const Y&) [with X = clang::TagType; Y = clang::QualType; typename std::enable_if<(! llvm::is_simple_type<Y>::value), typename llvm::cast_retty<X, const Y>::ret_type>::type = const clang::TagType*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
0  clang           0x0000000003c87265 llvm::sys::PrintStackTrace(_IO_FILE*) + 38
1  clang           0x0000000003c874e2
2  clang           0x0000000003c86e88
3  libpthread.so.0 0x00007f3ba26de340
4  libc.so.6       0x00007f3ba191af79 gsignal + 57
5  libc.so.6       0x00007f3ba191e388 abort + 328
6  libc.so.6       0x00007f3ba1913e36
7  libc.so.6       0x00007f3ba1913ee2
8  clang           0x00000000017816d4
9  clang           0x00000000017723b1 clang::Sema::ActOnTag(clang::Scope*, unsigned int, clang::Sema::TagUseKind, clang::SourceLocation, clang::CXXScopeSpec&, clang::IdentifierInfo*, clang::SourceLocation, clang::AttributeList*, clang::AccessSpecifier, clang::SourceLocation, llvm::MutableArrayRef<clang::TemplateParameterList*>, bool&, bool&, clang::SourceLocation, bool, clang::ActionResult<clang::OpaquePtr<clang::QualType>, false>, bool) + 6967
10 clang           0x0000000001624d5f clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::Parser::ParsedAttributesWithRange&) + 7241
11 clang           0x0000000001611745 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) + 9067
12 clang           0x0000000001626a1d clang::Parser::ParseCXXClassMemberDeclaration(clang::AccessSpecifier, clang::AttributeList*, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject*) + 2149
13 clang           0x0000000001628d99 clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::Parser::ParsedAttributesWithRange&, unsigned int, clang::Decl*) + 3271
14 clang           0x0000000001624f24 clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::Parser::ParsedAttributesWithRange&) + 7694
15 clang           0x0000000001611745 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) + 9067
16 clang           0x000000000166f8f0 clang::Parser::ParseSingleDeclarationAfterTemplate(unsigned int, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) + 622
17 clang           0x000000000166f61e clang::Parser::ParseTemplateDeclarationOrSpecialization(unsigned int, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) + 1026
18 clang           0x000000000166f203 clang::Parser::ParseDeclarationStartingWithTemplate(unsigned int, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) + 209
19 clang           0x000000000160b3e0 clang::Parser::ParseDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, unsigned int, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) + 218
20 clang           0x00000000015f9de6 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) + 1828
21 clang           0x00000000015f9678 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) + 538
22 clang           0x00000000015f2e1f clang::ParseAST(clang::Sema&, bool, bool) + 399
23 clang           0x00000000010af8c4 clang::ASTFrontendAction::ExecuteAction() + 322
24 clang           0x00000000010af39f clang::FrontendAction::Execute() + 139
25 clang           0x00000000010799bd clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 721
26 clang           0x000000000103d1eb clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 993
27 clang           0x000000000102ad32 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 770
28 clang           0x0000000001037cbc
29 clang           0x00000000010380f0 main + 661
30 libc.so.6       0x00007f3ba1905ec5 __libc_start_main + 245
31 clang           0x0000000001029369
Stack dump:
0.	Program arguments: clang -cc1 -x c++ -std=c++03 redefTmplInjClassName.cc 
1.	redefTmplInjClassName.cc:2:13: current parser token '{'
2.	redefTmplInjClassName.cc:1:20: parsing struct/union/class body 'Y'
Aborted (core dumped)

### COMPILER VERSION INFO:
$ clang++ -v
clang version 3.6.0 (trunk 215824)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Selected multilib: .;@m64

**Comment by wheatman** [comment]
This seems to have been fixed between 3.5 and 3.6
https://cexplorer.testlabs.pro/z/1bd31n

As a note, the issue only seemed to trigger on assertion builds

for reference

code 
```
template <class T> struct Y {
   struct Y { };
};
```

crash 
```
clang-3.5: /home/tonik/llvm-project/llvm/include/llvm/Support/Casting.h:223: typename std::enable_if<(! llvm::is_simple_type<Y>::value), typename llvm::cast_retty<X, const Y>::ret_type>::type llvm::cast(const Y&) [with X = clang::TagType; Y = clang::QualType; typename std::enable_if<(! llvm::is_simple_type<Y>::value), typename llvm::cast_retty<X, const Y>::ret_type>::type = const clang::TagType*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
0  clang-3.5 0x00000000016fade2 llvm::sys::PrintStackTrace(_IO_FILE*) + 50
1  clang-3.5 0x00000000016fa624
2  libc.so.6 0x00007f049f854df0
3  libc.so.6 0x00007f049f8a154c
4  libc.so.6 0x00007f049f854d46 raise + 22
5  libc.so.6 0x00007f049f8287f3 abort + 211
6  libc.so.6 0x00007f049f82871b
7  libc.so.6 0x00007f049f84dce6
8  clang-3.5 0x000000000212bfb2 clang::Sema::ActOnTag(clang::Scope*, unsigned int, clang::Sema::TagUseKind, clang::SourceLocation, clang::CXXScopeSpec&, clang::IdentifierInfo*, clang::SourceLocation, clang::AttributeList*, clang::AccessSpecifier, clang::SourceLocation, llvm::MutableArrayRef<clang::TemplateParameterList*>, bool&, bool&, clang::SourceLocation, bool, clang::ActionResult<clang::OpaquePtr<clang::QualType>, false>, bool) + 11154
9  clang-3.5 0x0000000001f0e79b clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::Parser::ParsedAttributesWithRange&) + 3371
10 clang-3.5 0x0000000001ef6e3f clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) + 3663
11 clang-3.5 0x0000000001f0a835 clang::Parser::ParseCXXClassMemberDeclaration(clang::AccessSpecifier, clang::AttributeList*, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject*) + 1349
12 clang-3.5 0x0000000001f0d289 clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::Parser::ParsedAttributesWithRange&, unsigned int, clang::Decl*) + 2009
13 clang-3.5 0x0000000001f0ebf9 clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::Parser::ParsedAttributesWithRange&) + 4489
14 clang-3.5 0x0000000001ef6e3f clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) + 3663
15 clang-3.5 0x0000000001f57cfa clang::Parser::ParseSingleDeclarationAfterTemplate(unsigned int, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) + 922
16 clang-3.5 0x0000000001f59560 clang::Parser::ParseTemplateDeclarationOrSpecialization(unsigned int, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) + 1008
17 clang-3.5 0x0000000001f5983a clang::Parser::ParseDeclarationStartingWithTemplate(unsigned int, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) + 138
18 clang-3.5 0x0000000001efb0e4 clang::Parser::ParseDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, unsigned int, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) + 644
19 clang-3.5 0x0000000001ee4141 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) + 369
20 clang-3.5 0x0000000001ee4860 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) + 496
21 clang-3.5 0x0000000001edaef8 clang::ParseAST(clang::Sema&, bool, bool) + 440
22 clang-3.5 0x0000000001af47fe clang::CodeGenAction::ExecuteAction() + 78
23 clang-3.5 0x000000000186fc46 clang::FrontendAction::Execute() + 118
24 clang-3.5 0x000000000184bd20 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 336
25 clang-3.5 0x00000000018f3f73 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 2147
26 clang-3.5 0x000000000097c928 cc1_main(char const**, char const**, char const*, void*) + 1432
27 clang-3.5 0x00000000009550cf main + 1247
28 libc.so.6 0x00007f049f83feb0
29 libc.so.6 0x00007f049f83ff60 __libc_start_main + 128
30 clang-3.5 0x000000000097a689 _start + 41
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-3.5.0-assert/bin/clang-3.5 -cc1 -triple x86_64-unknown-linux-gnu -S -disable-free -main-file-name example.cpp -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -g -dwarf-column-info -coverage-file /tmp/compiler-explorer-compiler202366-960250-e7c93p.zdukf/output.s -resource-dir /opt/compiler-explorer/clang-3.5.0-assert/bin/../lib/clang/3.5.0 -internal-isystem /opt/compiler-explorer/gcc-6.3.0/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0 -internal-isystem /opt/compiler-explorer/gcc-6.3.0/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/x86_64-linux-gnu -internal-isystem /opt/compiler-explorer/gcc-6.3.0/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/backward -internal-isystem /usr/local/include -internal-isystem /opt/compiler-explorer/clang-3.5.0-assert/bin/../lib/clang/3.5.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /tmp/compiler-explorer-compiler202366-960250-e7c93p.zdukf -ferror-limit 19 -fmessage-length 0 -mstackrealign -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -mllvm --x86-asm-syntax=intel -o /tmp/compiler-explorer-compiler202366-960250-e7c93p.zdukf/output.s -x c++ <source> 
1.	<source>:2:13: current parser token '{'
2.	<source>:1:20: parsing struct/union/class body 'Y'
clang-3.5: error: unable to execute command: Aborted (core dumped)
clang-3.5: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.5.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
clang-3.5: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3.5: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3.5: note: diagnostic msg: /tmp/example-d2b41a.cpp
clang-3.5: note: diagnostic msg: /tmp/example-d2b41a.sh
clang-3.5: note: diagnostic msg: 

********************
Compiler returned: 254
```
