### ISSUE TITLE
[META] Fix errors in UBSan bootstrap of LLVM/Clang

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21189]
|  |  |
| --- | --- |
| Bugzilla Link | [20815](https://llvm.org/bz20815) |
| Version | trunk |
| OS | Linux |
| Depends On | llvm/llvm-project#19676 llvm/llvm-project#21353 llvm/llvm-project#21355 llvm/llvm-project#21356  |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
I've recently added bootstrap of LLVM/Clang with UBSan to the sanitizer-x86_64-linux-boostrap buildbot: http://lab.llvm.org:8011/builders/sanitizer-x86_64-linux-bootstrap

You can try it on your machine by passing just-built Clang as a host compiler and -DLLVM_USE_SANITIZER=Undefined option to CMake.

Currently both check-llvm and check-clang test suites have failing tests:
http://lab.llvm.org:8011/builders/sanitizer-x86_64-linux-bootstrap/builds/4368/steps/check-llvm%20ubsan/logs/stdio
http://lab.llvm.org:8011/builders/sanitizer-x86_64-linux-bootstrap/builds/4368/steps/check-clang%20ubsan/logs/stdio

A lot of LLVM failures will be fixed once:
1) http://reviews.llvm.org/D4976 lands (reviewers are welcome!)
2) jit_exit function in lib/ExecutionEngine/JIT/JITMemoryManager.cpp is defined to return int to pacify function type sanitizer (if it's an appropriate fix).

There is a not-so-long tail of remaining issues there. I'd be grateful if you can take a look and/or fix some of them.

**Comment by asl** [comment]
Looks like all blockers were fixed. Please reopen if this still an issue
