### ISSUE TITLE
std::vector ctor for POD type from pointer range results in horrible codegen

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21205]
|  |  |
| --- | --- |
| Bugzilla Link | [20831](https://llvm.org/bz20831) |
| Version | unspecified |
| OS | All |
| Attachments | [Full disassembly of the inefficient code](https://user-images.githubusercontent.com/60944935/143749969-6fc40c47-a6c8-41b6-91f7-527c2dfb1ac0.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @chandlerc,@hfinkel,@mclow |

## Extended Description 
Using clang from Xcode 6 Beta 3:
Apple LLVM version 6.0 (clang-600.0.38) (based on LLVM 3.5svn)

Compiling the following code:

std::vector<char> build(const char* data, size_t size) { return std::vector<char>(data, data + size); }

Results in the assembly with *this* as an inner loop (clang++ -O3):

LBB0_5:                                 ## =>This Inner Loop Header: Depth=1
	testq	%rcx, %rcx
	movl	$0, %eax
	je	LBB0_7
## BB#6:                                ##   in Loop: Header=BB0_5 Depth=1
	movb	(%rbx), %al
	movb	%al, (%rcx)
	movq	8(%r14), %rax
LBB0_7:                                 ## %_ZNSt3__116allocator_traitsINS_9allocatorIcEEE9constructIccEEvRS2_PT_RKT0_.exit.i.i.i
                                        ##   in Loop: Header=BB0_5 Depth=1
	incq	%rax
	movq	%rax, 8(%r14)
	incq	%rbx
	decq	%r15
	movq	%rax, %rcx
	jne	LBB0_5

With -stdlib=libstdc++ I get "callq _memcpy" instead.

Changing libc++ sources to hoist __end_ into a local does not help very much - it removes redundant load/store instructions for __end_ but the loop is still there.

Also I'm not sure why "decq %r15" is here - as far as I can see compiler should have removed it. Can someone confirm that this part looks like a separate optimization issue and warrants filing a separate LLVM bug?

Full disassembly dump attached.

**Comment by philnik777** [comment]
AFAICT this has been fixed in LLVM 8: https://godbolt.org/z/49Ma315s8
