### ISSUE TITLE
Clang Makefile build doesn't generate PROFILE-PIC version of compiler-rt

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21214]
|  |  |
| --- | --- |
| Bugzilla Link | [20840](https://llvm.org/bz20840) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Overview:
  Building LLVM/Clang with GNU autoconf (./configure) doesn't generate libclang_rt.profile-pic-x86_64.a needed for clang to link with "-fprofile-instr-generate -fPIC"

Steps to Reproduce:
  1) Compile LLVM/clang with GNU autoconf, below is the options I've used
     ./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --enable-shared \
        --enable-libffi \
        --enable-targets=all \
        --disable-expensive-checks \
        --disable-debug-runtime \
        --disable-assertions \
        --with-binutils-include=/usr/include \
        --with-python=/usr/bin/python2 \
        --enable-cxx1y --enable-libcpp \
        --enable-optimized
  2) Build an library with {C,CXX}FLAGS="-fprofile-instr-generate"
Expected Results:
  Build successful with no problems
Actual Results:
  Build failed, GNU ld error:
  /usr/bin/ld: error: cannot open /usr/bin/../lib/clang/3.6.0/lib/linux/libclang_rt.profile-pic-x86_64.a: No such file or directory
Additional Information: libclang_rt.profile-pic-x86_64.a presents in cmake build

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
