### ISSUE TITLE
assertion "Leftover temporaries in function" triggered on calls which may throw

### ISSUE THREAD

**Issue by compnerd** [llvm/llvm-project#21212]
|  |  |
| --- | --- |
| Bugzilla Link | [20838](https://llvm.org/bz20838) |
| Version | trunk |
| OS | All |
| Attachments | [reduced.mm](https://user-images.githubusercontent.com/63311/143749974-88627f44-aafd-4a93-8828-ed43e8c37ed5.gz) |
| CC | @hfinkel |

## Extended Description 

This occurs with 3.4 and current trunk.  If you have a complex statement, e.g. a stack block and an implicit conversion which may throw an exception, the temporary value cleanup is not triggered, resulting in an assertion triggering.

The reduced test case demonstrates this.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.6: https://cexplorer.testlabs.pro/z/MnMzzG
