### ISSUE TITLE
clang tries to use 128-bit function __multi3 on 32-bit target

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21245]
|  |  |
| --- | --- |
| Bugzilla Link | [20871](https://llvm.org/bz20871) |
| Version | trunk |
| OS | Linux |
| Attachments | [The C source file that triggers the bug](https://user-images.githubusercontent.com/60944935/143750000-996e05f0-f71e-40e9-866e-39fba8328974.gz), [Preprocessed source](https://user-images.githubusercontent.com/60944935/143750001-d0a9b719-8a8e-4ebc-bbfb-a2a1a6863de0.gz), [Run script](https://user-images.githubusercontent.com/60944935/143750002-13f8220a-f639-4b63-8d68-162a25504fb1.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @topperc,@DMG862,@koutheir,@RKSimon,@riyazvp,@smithp35,@rotateright,@vchuravy |

## Extended Description 

When I try to compile a certain short C-file with clang for a 32-bit i386 target with optimization, I get this linker error:
/tmp/addup-b0948d.o:/home/tor/c/addup.c:function addup: error: undefined reference to '__multi3'

As I understand it, __multi3 is a 128-bit function, and not available on 32-bit i386. The C source does not use and 128-bit types, only 64-bit.

With the versions of clang-3.4 and 3.5 in the Ubuntu repositories, clang segfaults instead. Reported here: https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-snapshot/+bug/1365701

**Comment by DimitryAndric** [comment]
This was fixed via 789708617d2023dbb343c65120556b2e6a97044d.
