### ISSUE TITLE
Redundant instruction injected after the assembly block

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#21255]
|  |  |
| --- | --- |
| Bugzilla Link | [20881](https://llvm.org/bz20881) |
| Version | trunk |
| OS | FreeBSD |
| Attachments | [testcase](https://user-images.githubusercontent.com/95090477/143750008-a1722c9a-9988-4a55-8f0f-1388d69eac35.gz) |
| CC | @DougGregor,@hfinkel |

## Extended Description 
In the attached case redundant instruction "movl    %eax, %eax" is generated that isn't needed.
I think this is maybe because of the preceding assembly.

$ sh run-rdts.sh
        .text
        .file   "rdtsc.c"
        .globl  do_rdtsc
        .align  16, 0x90
        .type   do_rdtsc,@function
do_rdtsc:                               # @&#8203;do_rdtsc
        .cfi_startproc
# BB#0:
        pushq   %rbp
.Ltmp0:
        .cfi_def_cfa_offset 16
.Ltmp1:
        .cfi_offset %rbp, -16
        movq    %rsp, %rbp
.Ltmp2:
        .cfi_def_cfa_register %rbp
        #APP
        rdtsc
        #NO_APP
                                        # kill: EDX<def> EDX<kill> RDX<def>
        shlq    $32, %rdx
        movl    %eax, %eax
        orq     %rdx, %rax
        popq    %rbp
        retq
.Ltmp3:
        .size   do_rdtsc, .Ltmp3-do_rdtsc
        .cfi_endproc

        .ident  "clang version 3.6.0 (trunk 215999)"
        .section        ".note.GNU-stack","",@progbits

**Comment by JOE1994** [comment]
With `clang trunk`, the redundant instruction is no longer generated.

* https://godbolt.org/z/Pso8E8cYo

Please re-open if necessary.
