### ISSUE TITLE
Identifier `strdup` not found with `LLVM_ENABLE_CXX1Y` enabled

### ISSUE THREAD

**Issue by mkurdej** [llvm/llvm-project#21296]
|  |  |
| --- | --- |
| Bugzilla Link | [20922](https://llvm.org/bz20922) |
| Version | trunk |
| OS | Windows NT |

## Extended Description 
When compiling the trunk with `LLVM_ENABLE_CXX1Y` enabled, I get the following error:
```
Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/CommandLine.cpp.obj
c:/.../llvm/lib/Support/CommandLine.cpp:733:19: error: use of undeclared identifier 'strdup'
      char *Dup = strdup(Str);
                  ^
1 error generated.
```
Disabling this option makes the error disappear.

Environment:
* Source: LLVM revision 217666
* OS: Windows 8.1 Pro
* Compiler: clang version 3.5.0 (217039)
  Target: i686-pc-windows-gnu
  Thread model: posix

**Comment by Endilll** [comment]
Clang 3.5 is ancient at this point. Feel free to reopen if you encounter this with a supported version of Clang using the compiler that satisfies the minimum requirements.
