### ISSUE TITLE
crashes when instantiating ambiguous template

### ISSUE THREAD

**Issue by a1eaaf79-3824-4e4a-810d-221cd1b83ce5** [llvm/llvm-project#21315]
|  |  |
| --- | --- |
| Bugzilla Link | [20941](https://llvm.org/bz20941) |
| Version | trunk |
| OS | All |
| Attachments | [source code](https://user-images.githubusercontent.com/92601337/143750033-ee2e7180-fa01-4e73-90ab-a429e84432e5.gz) |
| CC | @Weverything |

## Extended Description 

crashes with ambiguous instantiation. source code attached. here's the generated sh script:

 "/opt/local/libexec/llvm-3.5/bin/clang" -cc1 -triple x86_64-apple-macosx10.9.0 -emit-obj -mrelax-all -disable-free -main-file-name main.cpp -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu corei7-avx -target-linker-version 136 -gdwarf-2 -stdlib=libc++ -std=c++1y -fdeprecated-macro -ferror-limit 19 -fmessage-length 117 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.9.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-slp -x c++ main-82d9b7.cpp

**Comment by Endilll** [comment]
Appears to be fixed in Clang 5: https://godbolt.org/z/xbsMon1jq
