### ISSUE TITLE
objc method calls wrapped incorrectly

### ISSUE THREAD

**Issue by 35a556ef-26b9-4f2b-837d-9b3f7ccf6035** [llvm/llvm-project#21381]
|  |  |
| --- | --- |
| Bugzilla Link | [21007](https://llvm.org/bz21007) |
| Version | unspecified |
| OS | All |

## Extended Description 
Before and after can be viewed at https://codereview.chromium.org/591493002/diff/1/chrome/browser/ui/cocoa/ssl_client_certificate_selector_cocoa_browsertest.mm#newcode51

Original code:
```
  SSLClientCertificateSelectorCocoa* selector =
      [[SSLClientCertificateSelectorCocoa alloc]
          initWithNetworkSession:auth_requestor_->http_network_session_
                 certRequestInfo:auth_requestor_->cert_request_info_
                        callback:base::Bind(&OnCertificateSelected,
                                            &cert,
                                            &count)];
```

Incorrectly formatted code:
```
  SSLClientCertificateSelectorCocoa* selector = [
      [SSLClientCertificateSelectorCocoa alloc]
      initWithNetworkSession:auth_requestor_->http_network_session_
             certRequestInfo:auth_requestor_->cert_request_info_.get()
                    callback:base::Bind(&OnCertificateSelected, &cert, &count)];
```

It should have kept the original formatting rather than splitting apart the [[, e.g.:
```
  SSLClientCertificateSelectorCocoa* selector =
      [[SSLClientCertificateSelectorCocoa alloc]
          initWithNetworkSession:auth_requestor_->http_network_session_
                 certRequestInfo:auth_requestor_->cert_request_info_.get()
                        callback:base::Bind(&OnCertificateSelected,
                                            &cert,
                                            &count)];
```

Interestingly enough, just a few lines further down in the same file, the formatter opted to preserve the original formatting rather than reflow it incorrectly (https://codereview.chromium.org/591493002/diff/1/chrome/browser/ui/cocoa/ssl_client_certificate_selector_cocoa_browsertest.mm#newcode73).

**Comment by mydeveloperday** [comment]
With clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 7890afddec
ff01119f4d5e8825b43dd2c8361648)

This is the output

```
SSLClientCertificateSelectorCocoa *selector =
    [[SSLClientCertificateSelectorCocoa alloc]
        initWithNetworkSession:auth_requestor_->http_network_session_
               certRequestInfo:auth_requestor_->cert_request_info_
                      callback:base::Bind(&OnCertificateSelected, &cert,
                                          &count)];
```

As this appears fixed I'm going to close this issue, please feel free to reopen if it doesn't solve your issue
