### ISSUE TITLE
Deleting whole buffer with Rewriter::RemoveText

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21402]
|  |  |
| --- | --- |
| Bugzilla Link | [21028](https://llvm.org/bz21028) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
There's an assertion in Rewriter::RemoveText that seems to preclude removing the whole text [http://clang.llvm.org/doxygen/Rewriter_8cpp_source.html#l00059]

  assert(RealOffset+Size < Buffer.size() && "Invalid location");

Should this be:

  assert(RealOffset+Size <= Buffer.size() && "Invalid location");

?

**Comment by Endilll** [comment]
Proposed change has landed in https://github.com/llvm/llvm-project/commit/69e6f1f257be7dcc2487aeb23b6246d03c651990
