### ISSUE TITLE
clang fails to cross compile LLVM for AArch64 - assert in AArch64FastISel

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21430]
|  |  |
| --- | --- |
| Bugzilla Link | [21056](https://llvm.org/bz21056) |
| Version | trunk |
| OS | Linux |
| Attachments | [clang command line](https://user-images.githubusercontent.com/60944935/143750094-651de466-c057-4f8b-a6fa-87563eaf42aa.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @rengolin |

## Extended Description 
clang fails on the assertion when using it to cross compile LLVM for AArch64 with the following stack trace:

clang-3.6: /path/to/llvm/lib/Target/AArch64/AArch64FastISel.cpp:3660: unsigned int {anonymous}::AArch64FastISel::emitASR_ri(llvm::MVT, llvm::MVT, unsigned int, bool, uint64_t, bool): Assertion `(SrcVT == MVT::i8 || SrcVT == MVT::i16 || SrcVT == MVT::i32 || SrcVT == MVT::i64) && "Unexpected source value type."' failed.
llvm::sys::PrintStackTrace(_IO_FILE*) + 38

llvm::FastISel::selectInstruction(llvm::Instruction const*) + 709
llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) + 1371
llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) + 1095

llvm::MachineFunctionPass::runOnFunction(llvm::Function&) + 95
llvm::FPPassManager::runOnFunction(llvm::Function&) + 290
llvm::FPPassManager::runOnModule(llvm::Module&) + 84

llvm::legacy::PassManagerImpl::run(llvm::Module&) + 244
llvm::legacy::PassManager::run(llvm::Module&) + 39

clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::raw_ostream*) + 127

clang::ParseAST(clang::Sema&, bool, bool) + 776
clang::ASTFrontendAction::ExecuteAction() + 322
clang::CodeGenAction::ExecuteAction() + 1467
clang::FrontendAction::Execute() + 139
clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 770
clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 993
cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 770

main + 1015
__libc_start_main + 245

1. <eof> parser at end of file
2. Code generation
3. Running pass 'Function Pass Manager' on module '/home/oleg/work/src/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp'.
4. Running pass 'AArch64 Instruction Selection' on function '@_ZNK12_GLOBAL__N_111DAGCombiner7isAliasEPN4llvm12LSBaseSDNodeES3_'

The preprocessed cpp and the clang's command line attached.

**Comment by DanielKristofKiss** [comment]
Works on ToT.
