### ISSUE TITLE
Clang fails to compile GLFW

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21449]
|  |  |
| --- | --- |
| Bugzilla Link | [21075](https://llvm.org/bz21075) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [build script](https://user-images.githubusercontent.com/60944935/143750099-4dfaa05c-453e-48f9-a472-15a5c660a724.gz), [preprocessed source](https://user-images.githubusercontent.com/60944935/143750100-4e79f298-2aeb-44a9-9a30-8cc8d5a20b98.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I built clang with mingw 4.8.2 (from mingw.org). Clang fails to compile the attached source, which is from GLFW 3.0.4.

The error message is:
fatal error: error in backend: alignment is limited to 4-bytes

**Comment by arsenm** [comment]
Had to hack up the reproducer a bit but compiles fine today
