### ISSUE TITLE
Triviality of special member functions of class with volatile members

### ISSUE THREAD

**Issue by K-ballo** [llvm/llvm-project#21444]
|  |  |
| --- | --- |
| Bugzilla Link | [21070](https://llvm.org/bz21070) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor,@mclow,@zygoloid |

## Extended Description 
The following snippet fails to compile, with all 4 static assertions firing:

    #include <type_traits>

    struct foo { volatile int i; };

    int main() {
      static_assert(!std::is_trivially_copy_constructible<foo>::value, "is_trivially_copy_constructible");
      static_assert(!std::is_trivially_move_constructible<foo>::value, "is_trivially_move_constructible");
      static_assert(!std::is_trivially_copy_assignable<foo>::value, "is_trivially_copy_assignable");
      static_assert(!std::is_trivially_move_assignable<foo>::value, "is_trivially_move_assignable");
    }

I think it should compile fine, at least according to my reading of 12.8/12:

> A copy/move constructor for class X is trivial if (...)
>  - class X has no non-static data members of volatile-qualified type

and 12.8/25:

> A copy/move assignment operator for class X is trivial if (...)
>  - class X has no non-static data members of volatile-qualified type

These bullets were introduced by the resolution of CWG496.

**Comment by Endilll** [comment]
Resolution of [CWG 496](https://cplusplus.github.io/CWG/issues/496.html) was an ABI break for IA-64, and it was reverted in [CWG 2094](https://cplusplus.github.io/CWG/issues/2094.html).

**Comment by Endilll** [comment]
All major implementation are conformant to CWG 2094: https://godbolt.org/z/M6a3TKjMK
