### ISSUE TITLE
crashes during template type deduction

### ISSUE THREAD

**Issue by a1eaaf79-3824-4e4a-810d-221cd1b83ce5** [llvm/llvm-project#21470]
|  |  |
| --- | --- |
| Bugzilla Link | [21096](https://llvm.org/bz21096) |
| Version | trunk |
| OS | MacOS X |
| Attachments | [crash generated sh script](https://user-images.githubusercontent.com/92601337/143750110-06d866b9-4fe2-4a8e-a1a2-325fe4ce7ebc.gz), [original file (depends on fatal library https://user-images.githubusercontent.com/92601337/143750111-f02af5d1-adcd-455f-9122-c93d5a4dd114.gz), [crash generated cpp file](https://user-images.githubusercontent.com/92601337/143750112-9b3510e4-c425-47ed-8b24-36f20d466a40.gz) |
| CC | @DougGregor,@rnburn |

## Extended Description 
crashes during template argument deduction. Attached original c++ file (uses Facebook fatal library), as well as generate files. 

The code gives this error when compiling with g++:

main.cpp: In function 'int main()':
main.cpp:106:79: error: no matching function for call to 'slice(fatal::constant_sequence<int, 1, 2, 3, 4, 5>)'
main.cpp:106:79: note: candidate is:
main.cpp:84:3: note: template<int I, int J, class T, T ...Values> constexpr decltype (to_constant_sequence(typename fatal::constant_sequence<T, Values ...>::list:: slice<I, J>)) slice(fatal::constant_sequence<T, Values ...>)
main.cpp:84:3: note:   template argument deduction/substitution failed:
main.cpp: In substitution of 'template<int I, int J, class T, T ...Values> constexpr decltype (to_constant_sequence(typename fatal::constant_sequence<T, Values ...>::list:: slice<I, J>)) slice(fatal::constant_sequence<T, Values ...>) [with int I = 1; int J = 3; T = int; T ...Values = {1, 2, 3, 4, 5}]':
main.cpp:106:79:   required from here
main.cpp:84:3: error: dependent-name 'typename fatal::constant_sequence<T, Values ...>::list:: slice<I, J>' is parsed as a non-type, but instantiation yields a type
main.cpp:84:3: note: say 'typename typename fatal::constant_sequence<T, Values ...>::list:: slice<I, J>' if a type is meant

**Comment by Endilll** [comment]
Appears to be fixed in Clang 9: https://godbolt.org/z/EEfEsasno
Reduced by C-Reduce:
```cpp
struct type_list {
  template <End> using slice = int;
  namespace struct constant_sequence {
    typedef type_list list
  } template <int, int, class T> decltype(T : list::slice<>) slice(T) {
    slice<1, 3>(constant_sequence())
```
