### ISSUE TITLE
LLVM ERROR: Cannot select with llvm.experimental.stackmap

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21478]
|  |  |
| --- | --- |
| Bugzilla Link | [21104](https://llvm.org/bz21104) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
This is with 3.5 actually, can't select that in the version field.

# cat a.ll
declare void @&#8203;llvm.experimental.stackmap(i64, i32, ...)

define fastcc void @.hlt.mini_parse_test_internal() {
  call void (i64, i32, ...)* @&#8203;llvm.experimental.stackmap(i64 1, i32 0,
  i1 undef)
  unreachable
}

# llc a.ll
LLVM ERROR: Cannot select: 0x22d0e88: ch,i32 = X86ISD::ADD 0x22d0f90, 0x22d11a0 [ORD=2] [ID=6]
  0x22d0f90: i64 = TargetConstant<1> [ID=2]
  0x22d11a0: i32 = TargetConstant<0> [ID=3]
In function: .hlt.mini_parse_test_internal

Looks like it doesn't like passing in an i1, works when using i8 instead.

**Comment by vext01** [comment]
This looks like a duplicate of https://github.com/llvm/llvm-project/issues/21657
