### ISSUE TITLE
Crash building clasp (Common Lisp implementation based on Clang)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21488]
|  |  |
| --- | --- |
| Bugzilla Link | [21114](https://llvm.org/bz21114) |
| Version | trunk |
| OS | Linux |
| Attachments | [build log contains traceback from crash](https://user-images.githubusercontent.com/60944935/143750121-522b0fd4-9c05-4d79-9e7f-5a86bb8cfcfb.gz), [sh file to build gc_interface-841319.cpp file](https://user-images.githubusercontent.com/60944935/143750122-fb5e22b8-e091-4217-9a04-3256c315fbc3.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 

I got a crash when building Clang
( https://github.com/drmeister/clasp ) on Debian wheezy.

I'm attaching the build log, and two files that the traceback told me to include. I don't know if this is a real bug, or some artifact of the Linux OOM killer. When I tried running the example script produced by the crash, the process was killed by the OOM killer after some time.

**Comment by Endilll** [comment]
Author hasn't got back to us with preprocessed source.
