### ISSUE TITLE
LLVM 3.5.0 compilation & Snow Leoaprd : a failure

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21520]
|  |  |
| --- | --- |
| Bugzilla Link | [21146](https://llvm.org/bz21146) |
| Version | trunk |
| OS | MacOS X |
| Attachments | [Log files all in a zip file to be unarchived.](https://user-images.githubusercontent.com/60944935/143750150-0a5b9508-705f-4ecc-a8dd-34d44c2c7b6a.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Preliminary : maybe similar to LLVM bug ref. to as # 9610 in particular.

The compilation of LLVM v. 3.5.0  during the MAKE process failed, so not allowing its use.

Consequently, I tried to build LLVM v. 3.4.2 and is currently under process : the compilation seems to be effective, and CLang is currently compiled.

With this message, an attached ZIP file is enclosed, including log files (in particular, the config.log giving you all hardware informations as well as the other usual LLVM-based ones).

The compiler used is GCC v. 4.9.1 (the most recent) I just build and tested successfully. Platform is a Mac Mini (Intel Core 2 Duo - x86_64) and OS is Snow Leopard (last update version).

**Comment by arsenm** [comment]
Old build issue
