### ISSUE TITLE
libclang_rt i386 not building in 3.5

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21527]
|  |  |
| --- | --- |
| Bugzilla Link | [21153](https://llvm.org/bz21153) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
Configured as in http://llvm.org/bugs/show_bug.cgi?id=21152

After getting my project to compile/link properly, I then moved on to checking whether sanitizers would work and discovered it's only building the 64-bit libclang_rt.*-x86_64.a libraries.

**Comment by arsenm** [comment]
Old build issue with old autotools build
