### ISSUE TITLE
After upgrading Xcode to 6.0.1, all clang (mp-clang-3.4 and Apple clang) crash

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21568]
|  |  |
| --- | --- |
| Bugzilla Link | [21194](https://llvm.org/bz21194) |
| Version | 3.4 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@qcolombet,@rnk |

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.9: https://godbolt.org/z/dKxr8bcvP
