### ISSUE TITLE
clang-format single-line enums

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21574]
|  |  |
| --- | --- |
| Bugzilla Link | [21200](https://llvm.org/bz21200) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Using clang-format 3.6 (svn218873), a single line enum

`enum Foo {FooA, FooB, FooC};`

is always converted to multiple lines,

```
enum Foo
{
    FooA,
    FooB,
    FooC
};
```

if ColumnLimit=0. In order to keep the single line format, ColumnLimit has to be set to something large (and BreakBeforeBraces needs to be something other than GNU or Allman).

I would expect the single line to be preserved when ColumnLimit=0 -- perhaps always, but at least when BreakBeforeBraces is something other than GNU or Allman.

If the latter, it would be useful to have an option to enable one-line enums regardless of the value of BreakBeforeBraces (in the same way that AllowShortXXXOnASingleLine allows for one-line functions etc. even with Allman and GNU brace placement).

**Comment by mydeveloperday** [comment]
This is resolved by using `AllowShortEnumsOnASingleLine` which was added in v12 of clang-format

https://clang.llvm.org/docs/ClangFormatStyleOptions.html

I am closing this issue, but please feel free to reopen it if you have problems
