### ISSUE TITLE
Clang generates broken module, "Instruction does not dominate all uses!"

### ISSUE THREAD

**Issue by 991901f3-cc14-4404-b340-165691b62a58** [llvm/llvm-project#21594]
|  |  |
| --- | --- |
| Bugzilla Link | [21220](https://llvm.org/bz21220) |
| Version | unspecified |
| OS | All |
| CC | @Arnaud-de-Grandmaison-ARM,@compnerd |

## Extended Description 
$ cat t.cpp
struct s {
  char c[33];
};
struct t {
  t(const s &);
};
extern int a;
void fn1() {
  switch (a) {
  case 0:
    *new t(s());
  case 1:
    (t(s()));
  }
}

$ ~/llvm/Debug+Asserts/bin/clang -cc1 -x c++ t.cpp -o - -emit-llvm -O1 -fexceptions
t.cpp:11:5: warning: expression result unused
    *new t(s());
    ^~~~~~~~~~~
Instruction does not dominate all uses!
  %call = call noalias i8* @&#8203;_Znwm(i64 1) #&#8203;4
  call void @&#8203;_ZdlPv(i8* %call) #&#8203;5
fatal error: error in backend: Broken function found, compilation aborted!

**Comment by fhahn** [comment]
It looks like this has been fixed in current `main`: https://clang.godbolt.org/z/x98ord4h3, so I'll go ahead and close this.

If it still reproduces, please re-open the issue with additional details.
