### ISSUE TITLE
Error during compilation with cling

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21627]
|  |  |
| --- | --- |
| Bugzilla Link | [21253](https://llvm.org/bz21253) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 
1.	<eof> parser at end of file
2.	Per-module optimization passes
3.	Running pass 'Function Pass Manager' on module '/opt/root-6.02.00.source/math/matrix/src/TDecompSparse.cxx'.
4.	Running pass 'Loop Pass Manager' on function '@_ZN13TDecompSparse11Factor_sub2EiiPdiPiiS1_S1_iRiS1_S1_S1_S0_S1_'
5.	Running pass 'Unroll loops' on basic block '%for.body766'
clang: error: unable to execute command: Aborted (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.6.0 (trunk 219583)
Target: x86_64-unknown-linux-gnu
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/TDecompSparse-b2f04b.cpp
clang: note: diagnostic msg: /tmp/TDecompSparse-b2f04b.sh
clang: note: diagnostic msg: 

********************
make: *** [math/matrix/src/TDecompSparse.o] Error 254
make: *** Waiting for unfinished jobs....
root@cosmic:/opt/root-6.02.00.source# 

TDecompSparse-b2f04b.sh file -------------------------------------------------
 "/usr/local/bin/clang" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -main-file-name TDecompSparse.cxx -mrelocation-model pic -pic-level 2 -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -target-linker-version 2.24 -momit-leaf-frame-pointer -dwarf-column-info -D "NDEBUG" -D "R__HAVE_CONFIG" -O2 -Wshadow -Wall -W -Woverloaded-virtual -Wno-deprecated-declarations -std=c++11 -fdeprecated-macro -ferror-limit 19 -fmessage-length 147 -pthread -mstackrealign -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -x c++ TDecompSparse-b2f04b.cpp

**Comment by Endilll** [comment]
Author hasn't got back to us with preprocessed source in 9 years.
Unfortunately, we can't do much without it.
Feel free to reopen if you have additional information.
