### ISSUE TITLE
clang-format produces extra whitespace in sequences of C comments directly following each other

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21633]
|  |  |
| --- | --- |
| Bugzilla Link | [21259](https://llvm.org/bz21259) |
| Version | 3.6 |
| OS | Windows NT |
| Attachments | [Example source file for reproducing the problem](https://user-images.githubusercontent.com/60944935/143750208-2896b3e9-0abf-4ab3-94c4-8e9080982efe.gz), [With this configuration file the bug is reproducible](https://user-images.githubusercontent.com/60944935/143750209-6a1ee544-98a8-4444-9963-e964da36cb0e.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

If C comments directly follow each other (which is AFAIK totally legal in C language syntax), clang-format adds extra whitespace in some cases:

See attached file for an example. Configuration file will follow as well.

The problem is at least present in Windows snapshot build of SVN revision 217401. "clang-format.exe --version" gives
{{{
clang-format version 3.6.0 (217401)
}}}

**Comment by mydeveloperday** [comment]
ClangFormat 3.9 gives
```
// Code containing the following kind of comments is
// changed by clang-format in a strange way: The space between
// the sequences of "=" is expanded with additional whitespace.

/*

*/ /*


*/ /*============================================ ===========================*/
```

clang-format 8 and above gives

```
// Code containing the following kind of comments is
// changed by clang-format in a strange way: The space between
// the sequences of "=" is expanded with additional whitespace.

/*

*//*


*//*============================================ ===========================*/
```
I am therefore closing this issue, as I think its fixed, but feel free to reopen if you still have an issue
