### ISSUE TITLE
clang-format breaks C syntax when breaking a C comment before a forward slash

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21645]
|  |  |
| --- | --- |
| Bugzilla Link | [21271](https://llvm.org/bz21271) |
| Version | 3.6 |
| OS | Windows NT |
| Attachments | [Example source file for reproducing the problem](https://user-images.githubusercontent.com/60944935/143750222-1c58df40-c8f1-4816-b482-00a6d8a8b67f.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @pepsiman |

## Extended Description 

Again (as in bug 21259 and bug 21261), in sequences of C comments, clang-format gets confused.

In this case, a single "/" inside the second comment leads clang-format to ending the comment inside the original one, which itself produces syntax errors. See attachement for an example.

Again, the configuration used can be found in attachment 13195.

**Comment by mydeveloperday** [comment]
I believe this has been fixed (recently) clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 55d392cc30
fb36e6361ba71f4b568c093f8b23f3)


```
/* Blah blah blah blah blah blah blah blah blah blah process the file
  * /foo/bar/baz/quux
 **/
```

As this seems to be fixed and so I am going to close this issue, but please feel free to open this again if you still have issues.
