### ISSUE TITLE
ambiguous template instantiation crashes clang++

### ISSUE THREAD

**Issue by fcbbcdbd-9c33-417d-9711-1f8e9c944891** [llvm/llvm-project#21667]
|  |  |
| --- | --- |
| Bugzilla Link | [21293](https://llvm.org/bz21293) |
| Version | 3.4 |
| OS | Linux |
| Attachments | [Peprocessed source](https://user-images.githubusercontent.com/93436148/143750230-a426bc29-d910-4cba-b5f0-c20315578af6.gz) |
| CC | @DougGregor,@zygoloid,@rnk |

## Extended Description 

clang++ 3.4 crashes with the following simple program. g++ 4.8 reports 'ambiguous template specialization'.

template < typename T >
class DummyClass {
 public:
  DummyClass(const T &t) {};

  template< typename S >
  DummyClass(const S &s) {};

  void dummyFunction(const T &t) {};

  template< typename S >
  void dummyFunction(const S &s) {};
};

// These template instantiations are okay
template class DummyClass< int >;
template DummyClass< int >::DummyClass(const double &s);
template DummyClass< int >::dummyFunction(const double &s);

// These template instantiations will cause segmentation fault for clang++ 3.4
// In g++ 4.8, it reports 'ambiguous template specialization'.
template DummyClass< int >::DummyClass(const int &s);
template void DummyClass< int >::dummyFunction(const int &s);

int main() {
  return 0;
}

**Comment by Endilll** [comment]
Appears to be fixed in Clang 5: https://godbolt.org/z/Whdzo84rd
