### ISSUE TITLE
Clang 3.6 crash on invalid template specialization code

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21684]
|  |  |
| --- | --- |
| Bugzilla Link | [21310](https://llvm.org/bz21310) |
| Version | unspecified |
| OS | Windows NT |
| Attachments | [Preprocessed source and run script](https://user-images.githubusercontent.com/60944935/143750251-606fb5d5-9fe3-48df-bc7c-998c640f99cb.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @majnemer |

## Extended Description 

The following invalid template code crashed the clang compiler:

template <class T1>
class SomeClass
{
public:
	template <class T2>
	void SomeFunc(T2 someArg)
	{}
};

template <class T1>
void SomeClass<T1>::SomeFunc<int>(int someArg)
{}

The development environment is Windows 8.1 with Visual Studio 2013 Update 3, using the following distribution of Clang for Windows: http://llvm.org/builds/downloads/LLVM-3.6.0-r219740-win32.exe

The output log from the compilation process is as follows:
1>crash.cpp(11,21): error : cannot specialize a member of an unspecialized template
1>  void SomeClass<T1>::SomeFunc<int>(int someArg)
1>                      ^       ~~~~~
1>  Assertion failed: TemplateTypeParm->getDepth() == 0 && "Can't deduce with depth > 0", file ..\tools\clang\lib\Sema\SemaTemplateDeduction.cpp, line 1129
1>clang-cl.exe : error : clang frontend command failed due to signal (use -v to see invocation)
1>  clang version 3.6.0 (219740)
1>  Target: i686-pc-windows-msvc
1>  Thread model: posix
1>  clang-cl.exe: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
1>  clang-cl.exe: note: diagnostic msg: 
1>  ********************
1>  
1>  PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
1>  Preprocessed source(s) and associated run script(s) are located at:
1>  clang-cl.exe: note: diagnostic msg: C:\TEMP\crash-68eb19.cpp
1>  clang-cl.exe: note: diagnostic msg: C:\TEMP\crash-68eb19.sh
1>  clang-cl.exe: note: diagnostic msg: 

The preprocessed source file and run script referenced in this build log are attached to this report.

**Comment by Endilll** [comment]
Both examples appear to be fixed in Clang 4:
https://cexplorer.testlabs.pro/z/aYaWx5
https://cexplorer.testlabs.pro/z/G77hPs
