### ISSUE TITLE
Investigate and fix failing localization tests on linux.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21738]
|  |  |
| --- | --- |
| Bugzilla Link | [21364](https://llvm.org/bz21364) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
This bug tracks the failing localization tests on linux. The following localization tests currently fail for a variety of reasons.

localization/locale.categories/category.collate/locale.collate.byname/compare.pass.cpp
localization/locale.categories/category.ctype/locale.ctype.byname/tolower_1.pass.cpp
localization/locale.categories/category.ctype/locale.ctype.byname/tolower_many.pass.cpp
localization/locale.categories/category.ctype/locale.ctype.byname/toupper_1.pass.cpp
localization/locale.categories/category.ctype/locale.ctype.byname/toupper_many.pass.cpp
localization/locale.categories/category.ctype/locale.ctype.byname/widen_1.pass.cpp
localization/locale.categories/category.ctype/locale.ctype.byname/widen_many.pass.cpp
localization/locale.categories/category.monetary/locale.money.get/locale.money.get.members/get_long_double_ru_RU.pass.cpp
localization/locale.categories/category.monetary/locale.money.get/locale.money.get.members/get_long_double_zh_CN.pass.cpp
localization/locale.categories/category.monetary/locale.money.put/locale.money.put.members/put_long_double_ru_RU.pass.cpp
localization/locale.categories/category.monetary/locale.money.put/locale.money.put.members/put_long_double_zh_CN.pass.cpp
localization/locale.categories/category.monetary/locale.moneypunct.byname/decimal_point.pass.cpp
localization/locale.categories/category.monetary/locale.moneypunct.byname/thousands_sep.pass.cpp
localization/locale.categories/category.numeric/locale.nm.put/facet.num.put.members/put_long_double.pass.cpp
localization/locale.categories/category.time/locale.time.get.byname/get_date.pass.cpp
localization/locale.categories/category.time/locale.time.get.byname/get_date_wide.pass.cpp
localization/locale.categories/category.time/locale.time.get.byname/get_one.pass.cpp
localization/locale.categories/category.time/locale.time.get.byname/get_one_wide.pass.cpp
localization/locale.categories/category.time/locale.time.get.byname/get_weekday.pass.cpp
localization/locale.categories/category.time/locale.time.get.byname/get_weekday_wide.pass.cpp
localization/locale.categories/category.time/locale.time.put.byname/put1.pass.cpp
localization/locale.categories/category.time/locale.time.put/locale.time.put.members/put2.pass.cpp
localization/locale.categories/facet.numpunct/locale.numpunct.byname/grouping.pass.cpp
localization/locale.categories/facet.numpunct/locale.numpunct.byname/thousands_sep.pass.cpp

**Comment by philnik777** [comment]
All the listed tests are passing on linux AFAICT.
