### ISSUE TITLE
Assertion failed: (MBB != &MF->front() && "Can't find reaching def for virtreg")

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21756]
|  |  |
| --- | --- |
| Bugzilla Link | [21382](https://llvm.org/bz21382) |
| Version | trunk |
| OS | All |
| Attachments | [The LLVM assembly file which triggers the bug.](https://user-images.githubusercontent.com/60944935/143750271-25b8803a-8a9c-4d63-80cd-65016c18249c.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @atrick |

## Extended Description 

Attached testcase triggers an assertion in llc version 3.5.0

Assertion failed: (MBB != &MF->front() && "Can't find reaching def for virtreg"), function MarkVirtRegAliveInBlock, file ~/llvm-3.5.0/lib/CodeGen/LiveVariables.cpp, line 114

**Comment by xgupta** [comment]
The input IR ir is invalid - 
```
define i32 @test(i32 %x) {
entry:
  %cmp = icmp slt i32 %x, 0
  br i1 %cmp, label %label1, label %label2

label1:
  br label %label_end

label2:
  br label %label_end

label_end:
  %0 = phi i32 [ 1, %label1 ], [ 2, %label2 ]
  %1 = phi i32 [ 1, %label1 ], [ %0, %label2 ]
  ret i32 %1
}
```

It gives  -

Instruction does not dominate all uses!
  %0 = phi i32 [ 1, %label1 ], [ 2, %label2 ]
  %1 = phi i32 [ 1, %label1 ], [ %0, %label2 ]
llc: error: '<source>': input module cannot be verified
Compiler returned: 1
