### ISSUE TITLE
Missing inline scopes when two calls to the same function come from the same call site (eg: macro expansion, etc)

### ISSUE THREAD

**Issue by stbergmann** [llvm/llvm-project#21782]
|  |  |
| --- | --- |
| Bugzilla Link | [21408](https://llvm.org/bz21408) |
| Version | trunk |
| OS | MacOS X |
| CC | @adrian-prantl,@dwblaikie,@jsonn,@pogo59,@rnk |

## Extended Description 
At least with recent LLVM trunk r220776 on Mac OS X 10.10, compiling TRIAGE.cc

> template<typename T> struct X {
>     static T * t;
>     __attribute__ ((__always_inline__)) T * f() { return t; }
> };
> struct Y { Y(int, int); };
> struct Z: Y {
>     Z(Z&);
>     operator X<Z>();
>     int f();
>     Z(X<Z> x): Y(x.f()->f(), x.f()->f()) {}
> };
> Z f();
> void g() { Z z = f(); }

via

> clang++ -cc1 -triple x86_64-apple-macosx10.10.0 -emit-obj -gdwarf-2 TRIAGE.cc

fails with

> Assertion failed: (CurNum != ArgNum), function addScopeVariable, file src/lib/CodeGen/AsmPrinter/DwarfFile.cpp, line 180.
> 0  clang++                  0x00000001111715ab llvm::sys::PrintStackTrace(__sFILE*) + 43
> 1  clang++                  0x0000000111171d4b SignalHandler(int) + 635
> 2  libsystem_platform.dylib 0x00007fff8be2df1a _sigtramp + 26
> 3  libsystem_platform.dylib 0x0000000000000002 _sigtramp + 1948066050
> 4  clang++                  0x0000000111171ab6 abort + 22
> 5  clang++                  0x0000000111171a91 __assert_rtn + 81
> 6  clang++                  0x0000000110a1575c llvm::DwarfFile::addScopeVariable(llvm::LexicalScope*, llvm::DbgVariable*) + 364
> 7  clang++                  0x0000000110a01f45 llvm::DwarfDebug::collectVariableInfoFromMMITable(llvm::SmallPtrSetImpl<llvm::MDNode const*>&) + 597
> 8  clang++                  0x0000000110a02d61 llvm::DwarfDebug::collectVariableInfo(llvm::DwarfCompileUnit&, llvm::DISubprogram, llvm::SmallPtrSetImpl<llvm::MDNode const*>&) + 49
> 9  clang++                  0x0000000110a04844 llvm::DwarfDebug::endFunction(llvm::MachineFunction const*) + 756
> 10 clang++                  0x00000001109dfd9d llvm::AsmPrinter::EmitFunctionBody() + 4909
> 11 clang++                  0x0000000110704068 llvm::X86AsmPrinter::runOnMachineFunction(llvm::MachineFunction&) + 152
> 12 clang++                  0x0000000110aeb5fc llvm::MachineFunctionPass::runOnFunction(llvm::Function&) + 124
> 13 clang++                  0x00000001110fadfd llvm::FPPassManager::runOnFunction(llvm::Function&) + 333
> 14 clang++                  0x00000001110fb08b llvm::FPPassManager::runOnModule(llvm::Module&) + 43
> 15 clang++                  0x00000001110fb6b1 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 1137
> 16 clang++                  0x000000010f13c91e clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::raw_ostream*) + 6590
> 17 clang++                  0x000000010f288ed2 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) + 514
> 18 clang++                  0x000000010f320684 clang::ParseAST(clang::Sema&, bool, bool) + 468
> 19 clang++                  0x000000010f2878ab clang::CodeGenAction::ExecuteAction() + 123
> 20 clang++                  0x000000010ef85093 clang::FrontendAction::Execute() + 67
> 21 clang++                  0x000000010ef56b9c clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 972
> 22 clang++                  0x000000010ef11c15 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 4149
> 23 clang++                  0x000000010ef08a0d cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 1053
> 24 clang++                  0x000000010ef0fcad main + 11517
> 25 libdyld.dylib            0x00007fff952465c9 start + 1
> 26 libdyld.dylib            0x0000000000000007 start + 1792776767
> Stack dump:
> 0.      Program arguments: clang++ -cc1 -triple x86_64-apple-macosx10.10.0 -emit-obj -gdwarf-2 TRIAGE.cc 
> 1.      <eof> parser at end of file
> 2.      Code generation
> 3.      Running pass 'Function Pass Manager' on module 'TRIAGE.cc'.
> 4.      Running pass 'X86 Assembly / Object Emitter' on function '@_ZN1ZC2E1XIS_E'
> ./TRIAGE.sh: line 1:   447 Illegal instruction: 4  clang++ -cc1 -triple x86_64-apple-macosx10.10.0 -emit-obj -gdwarf-2 TRIAGE.cc

**Comment by Endilll** [comment]
Doesn't reproduce using Clang 3.5 and 3.6 with assertions enabled: https://cexplorer.testlabs.pro/z/cxKT38
Is it possible to check if the proper fix has been implemented?

CC @shafik @AaronBallman

**Comment by shafik** [comment]
I don't fully understand the issue @dwblaikie pointed out but I am sure he can confirm if the issue still exists or not. If you generate the IR you can see the debug info that way.

**Comment by dwblaikie** [comment]
Yep, the full fix was done here: df706288fba670943e164893e1fa0ccda3e24895 (luckily found by good documentation in commit messages, when I went and looked for r220923 I found the revert of it in e7d473461ea2ca1cfd905efa481804fd9b52a072 that mentioned the revision of the full fix that obsoleted the workaround)
