### ISSUE TITLE
ExitDuringStepTestCase hanging on buildbot and local runs on FreeBSD

### ISSUE THREAD

**Issue by emaste** [llvm/llvm-project#21785]
|  |  |
| --- | --- |
| Bugzilla Link | [21411](https://llvm.org/bz21411) |
| Version | unspecified |
| OS | FreeBSD |

## Extended Description 
Unfortunately the buildbot output is not useful: the test runs ninja check-lldb but is killed by timeout after 1200s and none of the output is displayed.

Running the suite locally on FreeBSD 10.1-RC3 I see that the test suite is executing the exit_during_step test and making no progress.

Example output:

http://llvm-amd64.freebsd.your.org/b/builders/lldb-amd64-freebsd/builds/2784/steps/check-lldb.1/logs/stdio

ninja check-lldb
 in dir /data/buildslave/lldb-amd64-freebsd/obj/llvm (timeout 1200 secs)
 watching logfiles {}
 argv: ['ninja', 'check-lldb']
 environment:
  HOME=/home/buildbot
  LOGNAME=buildbot
  MALLOC_CONF=abort:true,junk:true
  PATH=/home/buildbot/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  PWD=/data/buildslave/lldb-amd64-freebsd/obj/llvm
  SHELL=/bin/sh
  USER=buildbot
 using PTY: False
[1/1] Testing LLDB (with a separate subprocess per test)

command timed out: 1200 seconds without output running ['ninja', 'check-lldb'], attempting to kill
process killed by signal 9
program finished with exit code -1
elapsedTime=1200.280414

**Comment by DavidSpickett** [comment]
I don't see any xfail on the test right now and last time I checked on arm64 FreeBSD 14, it was passing.
