### ISSUE TITLE
LLVMConfig.cmake has wrong LLVM_LIBRARY_DIRS on systems that use lib64

### ISSUE THREAD

**Issue by arichardson** [llvm/llvm-project#21781]
|  |  |
| --- | --- |
| Bugzilla Link | [21407](https://llvm.org/bz21407) |
| Version | trunk |
| OS | Linux |

## Extended Description 
On my system (openSuSE) it shows LLVM_LIBRARY_DIRS points to /usr/local/lib
instead of /usr/local/lib64

This line here is wrong (line 97 in 3.5):
set(LLVM_LIBRARY_DIRS "${LLVM_INSTALL_PREFIX}/lib")

**Comment by arsenm** [comment]
There's a separate config variable for this now
