### ISSUE TITLE
checker-276 published on web site doesn't support new parameters from Xcode 6

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21877]
|  |  |
| --- | --- |
| Bugzilla Link | [21503](https://llvm.org/bz21503) |
| Version | 3.5 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @AnnaZaks |

## Extended Description 
checker-276 published on February 19, 2014 is the latest version available on the Clang Static Analyser web site at http://clang-analyzer.llvm.org/.

Unfortunately, this version seems to be too old for Xcode 6: some new parameters are not supported and make our Jenkins jobs to fail. Example:

clang: error: unknown argument: '-fmodule-implementation-of'
clang: error: cannot specify -o when generating multiple output files
Command /usr/checker-276/bin/clang failed with exit code 1

Would it be possible to update the Clang Static Analyser package on that site to make it compatible with latest Xcode release? Thanks!

**Comment by arsenm** [comment]
Old
