### ISSUE TITLE
C-style comments can get reflowed and mistakenly terminate comment

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21919]
|  |  |
| --- | --- |
| Bugzilla Link | [21545](https://llvm.org/bz21545) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @pepsiman |

## Extended Description 
llvm/clang r221770

If you reduce one of the long comments from <http://opensource.apple.com/source/xnu/xnu-2782.1.97/bsd/vfs/vfs_lookup.c>

into its own source file:

$ cat foo.c
```
/*
 * Example: 
 * 
 * If you are now looking up /foo/b and the vnode for this link represents /tmp/a, 
 * vnode_update_identity will fix the parentage so that you can get /foo/b back 
 * through the v_parent chain (preventing you from getting /tmp/b back). It would 
 * not fix whether or not you should or should not get /tmp/a vs. /foo/b.
 */
```
$ ~/Documents/llvm/build/bin/clang-format -style='{ ColumnLimit: 80, TabWidth: 4, IndentWidth: 4, UseTab: Never }' foo.c
```
/*
 * Example:
 *
 * If you are now looking up /foo/b and the vnode for this link represents
 */tmp/a,
 * vnode_update_identity will fix the parentage so that you can get /foo/b back
 * through the v_parent chain (preventing you from getting /tmp/b back). It
 *would
 * not fix whether or not you should or should not get /tmp/a vs. /foo/b.
 */
```
$ 

Something about the combination of overflowing the column limit and the existing hard breaks in the comment causes a "*/tmp/a" line to be emitted, which terminates the C-style comment and cause syntax errors. The "*would" is also ugly, but not invalid C.

**Comment by mydeveloperday** [comment]
As of 2021.12.17   clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 55d392cc30fb36e6361ba71f4b568c093f8b23f3)

This issue is resolved, this is the output, as such I am closing this issue but if you see another issue then feel free to reopen

```
/*
 * Example:
 *
 * If you are now looking up /foo/b and the vnode for this link represents
 * /tmp/a, vnode_update_identity will fix the parentage so that you can get
 * /foo/b back through the v_parent chain (preventing you from getting /tmp/b
 * back). It would not fix whether or not you should or should not get /tmp/a
 * vs. /foo/b.
 */
```
