### ISSUE TITLE
Clang halts with -mllvm -inline-threshold=10000 option

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#21932]
|  |  |
| --- | --- |
| Bugzilla Link | [21558](https://llvm.org/bz21558) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

**Comment by philnik777** [comment]
An inline threshold of 10000 is completely nuts. The highest I've ever seen for non-single-use functions through heuristics is 487, so I don't think it's reasonable to expect clang to behave properly with anything close to 10000. (It's ~15000 if clang knows the function isn't visible outside the TU and there is only a single call, but this is a very special case.)
