### ISSUE TITLE
Reassociate: nsw/nuw dropped when merging add into mul

### ISSUE THREAD

**Issue by 991901f3-cc14-4404-b340-165691b62a58** [llvm/llvm-project#21985]
|  |  |
| --- | --- |
| Bugzilla Link | [21611](https://llvm.org/bz21611) |
| Version | trunk |
| OS | All |

## Extended Description 
consider:
define i32 @&#8203;triple_i(i32 %x) {
  %1 = add nsw i32 %x, %x
  %2 = add nsw i32 %1, %x
  ret i32 %2
}

after running with opt -reassociate:
define i32 @&#8203;triple_i(i32 %x) {
  %factor = mul i32 %x, 3
  ret i32 %factor
}

**Comment by arsenm** [comment]
Flag is preserved today:
```
define i32 @triple_i(i32 %x) {
  %1 = mul nsw i32 %x, 3
  ret i32 %1
}
```
