### ISSUE TITLE
llvm::sys::process::get_self is not thread-safe

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22013]
|  |  |
| --- | --- |
| Bugzilla Link | [21639](https://llvm.org/bz21639) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
llvm::sys::process::get_self() is not thread-safe (at least on Windows) because initialization of function local statics is not thread-safe. I've been bitten by this with random crashes when using Clang in a multi-threaded application.

As long as the minimum required MSVC version does not implement thread-safe static initialization this should be guarded explicitly (maybe with ManagedStatic?).

**Comment by JOE1994** [comment]
Function `llvm::sys::process::get_self()` no longer exists as of `acab142751d3498c6d0aa63253dc1c9f3f83f268` (LLVM 19)

**Comment by JOE1994** [comment]
`llvm::sys::Process::get_self` was removed way back in c0610bf4e0e8844cec9e77dc53deafb211edadca .
