### ISSUE TITLE
clang-format breaks __attribute__ when attached to a scope extern decl

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22031]
|  |  |
| --- | --- |
| Bugzilla Link | [21657](https://llvm.org/bz21657) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
clang-format will apply the following transformation
```
  void foo() {
-   extern void bar(void) __attribute__((weak));
+   extern void bar(void)__attribute__((weak));
  }
```

**Comment by mkurdej** [comment]
Fixed in v3.8.
