### ISSUE TITLE
clang-format should not treat (foo) as a cast in a macro

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22032]
|  |  |
| --- | --- |
| Bugzilla Link | [21658](https://llvm.org/bz21658) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lichray |

## Extended Description 
- #define foo(x) ((x) & bar)
+ #define foo(x) ((x)&bar)

clang-format takes this to be casting the address of bar to type x. Generally speaking, this is the sensible choice, but not in a macro.

It should be assumed that (macro_param) is not actually a cast.

**Comment by rymiel** [comment]
This specific scenario was fixed by 7a4cdbeafb4c2c9fae2ac69d362d22d431404bbe
