### ISSUE TITLE
clang-format needs an option to ignore all block comments

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22033]
|  |  |
| --- | --- |
| Bugzilla Link | [21659](https://llvm.org/bz21659) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
clang-format seems to generally do a pretty bad job with wrapping long lines in block comments. As an example: https://android-review.googlesource.com/#/c/116090/8/linker/linker.cpp@542

It's nicely wrapped the long lines for us, but didn't reflow the following lines into the wrapped one, leaving an odd pattern of long line, short line, long line, short line.

This is probably a Hard Problem (since block comments are often meticulously hand aligned). There should probably just be an option to tell clanf-format to leave my block comments alone.

**Comment by mkurdej** [comment]
Reflowing comments is fixed since version 5.
