### ISSUE TITLE
Crash while capturing template std::function in lambdas

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22038]
|  |  |
| --- | --- |
| Bugzilla Link | [21664](https://llvm.org/bz21664) |
| Version | 3.4 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
When trying to capture a template std::function alias in a lambda by value, I am experiencing a crash in the resulting binary. Here is a code snippet showing this error:

#include <functional>

template<class T>
using Callback = std::function<void (T)>;

std::function<void ()> f(const Callback<int> &callback)
{
    return [=] {
        callback(0); // crash here
    };
}

int main()
{
    auto lambda = f([](int) { });
    lambda();
    return 0;
}

This also happens when explicitly capturing "callback". To work around the crash, the variable needs to be captured using generalized capture:

#include <functional>

template<class T>
using Callback = std::function<void (T)>;

std::function<void ()> f(const Callback<int> &callback)
{
    return [=, callback = callback] {
        callback(0);                   // no crash now
    };
}

int main()
{
    auto lambda = f([](int) { });
    lambda();
    return 0;
}

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.5 and 3.6: https://godbolt.org/z/YPPPTG3oe
