### ISSUE TITLE
Feature request: Generate .ini file for UniversalIndentGUI

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22070]
|  |  |
| --- | --- |
| Bugzilla Link | [21696](https://llvm.org/bz21696) |
| Version | 3.5 |
| OS | Windows NT |
| Attachments | [Sample .ini file for integrating clang-format into UniversalIndentGUI](https://user-images.githubusercontent.com/60944935/143750451-f9c3fff6-5578-41fb-80d9-ffeddcdbad78.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
UniversalIndentGUI[1] provides an easy to use GUI to select, test, and configure a formatter. You can select a formatter from a dropdown list. All formatter specific options are organized in categories, and you can change their values. You can load a file for formatting, and have it updated in real-time as you change configuration options. It's really neat.

For each formatter, UniversalIndentGUI needs an .ini file which tells it how to call the formatter, which options exist, and how they work. I have attached a sample file for clang-format with a couple of its options. You can find others in the source [2].

The formatter uncrustify[3] has a `--universalindent` option, which generates such an .ini file specifically for UniversalIndentGUI. My feature request is to add such an option to clang-format.

[1] http://universalindent.sourceforge.net/
[2] http://sourceforge.net/p/universalindent/code/HEAD/tree/trunk/indenters/
[3] http://uncrustify.sourceforge.net/

**Comment by mydeveloperday** [comment]
I do not think UniversalIndentGUI  has been updated since 2015, I don't really see why we'd want to do this with any priority.
