### ISSUE TITLE
AlwaysBreakAfterDefinitionReturnType Not Always Breaking

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22078]
|  |  |
| --- | --- |
| Bugzilla Link | [21704](https://llvm.org/bz21704) |
| Version | unspecified |
| OS | MacOS X |
| Attachments | [The example file I am running on](https://user-images.githubusercontent.com/60944935/143750457-ace6fcf5-fa85-42af-83bc-dafcae2e8d76.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

I reduced the test to only using AlwaysBreakAfterDefinitionReturnType, although adding a column limit makes the issue worse.

# Version info
clang-format version 3.6.0 (trunk 222672)

**Comment by mkurdej** [comment]
The file doesn't seem to be misformatted anymore. Closing.
Please reopen with a self-contained minimal reproduce (.clang-format config + file) if you still find the behaviour unintended.
