### ISSUE TITLE
ASTReader.cpp 759  Assertion faild  II->ExtensionToken() =ExtensionToken

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22081]
|  |  |
| --- | --- |
| Bugzilla Link | [21707](https://llvm.org/bz21707) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
A .cpp include <iostream>  and -emit-ast it to .ast
when read the ast (-ast-dump) the assert faild

**Comment by Endilll** [comment]
Unfortunately, we can't do much without a reproducer. Feel free to reopen if you have additional information.
