### ISSUE TITLE
Provide class level comments

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22186]
|  |  |
| --- | --- |
| Bugzilla Link | [21812](https://llvm.org/bz21812) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Properly use them to document the terminology and stuff.

**Comment by mydeveloperday** [comment]
I don't really understand what this is? closing old issue without good repo case, please reopen if there is something more specific we should look at
