### ISSUE TITLE
clang::Sema::~Sema(): Assertion `DelayedTypos.empty() && "Uncorrected typos!"' failed.

### ISSUE THREAD

**Issue by 991901f3-cc14-4404-b340-165691b62a58** [llvm/llvm-project#22279]
|  |  |
| --- | --- |
| Bugzilla Link | [21905](https://llvm.org/bz21905) |
| Version | trunk |
| OS | All |
| CC | @kcc,@rnk,@xiangzhai |

## Extended Description 
consider:
```cpp
int (*a) () = (void)Z;
```
tools/clang/lib/Sema/Sema.cpp:249: clang::Sema::~Sema(): Assertion `DelayedTypos.empty() && "Uncorrected typos!"' failed.
#&#8203;0  0x00007ffff6bdcbb9 in __GI_raise (sig=sig@entry=0x6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56  
#&#8203;1  0x00007ffff6bdffc8 in __GI_abort () at abort.c:89  
#&#8203;2  0x00007ffff6bd5a76 in __assert_fail_base (fmt=0x7ffff6d272b0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x538caa8 "DelayedTypos.empty() && \"Uncorrected typos!\"", file=file@entry=0x538ca60 "~/llvm/src/tools/clang/lib/Sema/Sema.cpp", line=line@entry=0xf9, function=function@entry=0x53909f0 <clang::Sema::~Sema()::__PRETTY_FUNCTION__> "clang::Sema::~Sema()") at assert.c:92
#&#8203;3  0x00007ffff6bd5b22 in __GI___assert_fail (assertion=0x538caa8 "DelayedTypos.empty() && \"Uncorrected typos!\"", file=0x538ca60 ~/llvm/src/tools/clang/lib/Sema/Sema.cpp", line=0xf9, function=0x53909f0 <clang::Sema::~Sema()::__PRETTY_FUNCTION__> "clang::Sema::~Sema()") at assert.c:101
#&#8203;4  0x0000000003451095 in clang::Sema::~Sema (this=0x6bd29a0, __in_chrg=<optimized out>) at ~/llvm/src/tools/clang/lib/Sema/Sema.cpp:249  
#&#8203;5  0x00000000024e33d4 in std::default_delete<clang::Sema>::operator() (this=0x6b84f70, __ptr=0x6bd29a0) at /usr/include/c++/4.8/bits/unique_ptr.h:67
#&#8203;6  0x00000000024e0104 in std::unique_ptr<clang::Sema, std::default_delete<clang::Sema> >::reset (this=0x6b84f70, __p=0x6bd29a0) at /usr/include/c++/4.8/bits/unique_ptr.h:262 
#&#8203;7  0x00000000024d516d in clang::CompilerInstance::setSema (this=0x6b84f10, S=0x0) at ~/llvm/src/tools/clang/lib/Frontend/CompilerInstance.cpp:101
#&#8203;8  0x000000000250f73f in clang::FrontendAction::EndSourceFile (this=0x6b85dd0) at ~/llvm/src/tools/clang/lib/Frontend/FrontendAction.cpp:467
#&#8203;9  0x00000000024d8f56 in clang::CompilerInstance::ExecuteAction (this=0x6b84f10, Act=...) at ~/llvm/src/tools/clang/lib/Frontend/CompilerInstance.cpp:812  
#&#8203;10 0x0000000002620855 in clang::ExecuteCompilerInvocation (Clang=0x6b84f10) at ~/llvm/src/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:222
#&#8203;11 0x00000000011b58d6 in cc1_main (Argv=..., Argv0=0x7fffffffe4c2 "~/llvm/Debug+Asserts/bin/clang", MainAddr=0x11abffd <GetExecutablePath(char const*, bool)>) at ~/llvm/src/tools/clang/tools/driver/cc1_main.cpp:110
#&#8203;12 0x00000000011ad69a in ExecuteCC1Tool (argv=..., Tool=...) at ~/llvm/src/tools/clang/tools/driver/driver.cpp:369
#&#8203;13 0x00000000011addd0 in main (argc_=0x5, argv_=0x7fffffffe1c8) at ~/llvm/src/tools/clang/tools/driver/driver.cpp:415

**Comment by Endilll** [comment]
Doesn't reproduce with assertions builds either: https://cexplorer.testlabs.pro/z/qj5649
