### ISSUE TITLE
ModuleLinker "chooses" the wrong DISubprogram when linkonce_odr is replaced by weak_odr

### ISSUE THREAD

**Issue by 3f18db19-85d0-42b5-b58f-dbfbd8cbce51** [llvm/llvm-project#22284]
|  |  |
| --- | --- |
| Bugzilla Link | [21910](https://llvm.org/bz21910) |
| Version | trunk |
| OS | All |
| Attachments | [repro.tar.gz: demonstrate mismatched "first subprogram" vs. "chosen subprogram"](https://user-images.githubusercontent.com/92601280/143750584-493a9af0-3007-495c-af8f-f782576264d4.gz) |
| CC | @adrian-prantl,@dwblaikie,@dexonsmith,@echristo,@fredriss |

## Extended Description 

When a `linkonce_odr` function gets replaced by a `weak_odr` function, the new function body's `!dbg` references point at a potentially new DW_TAG_subprogram in a new DW_TAG_compile_unit.

Some algorithms assume the first `DW_TAG_subprogram` that points at an `llvm::Function*` is the canonical one, where the first is obtained by walking compile units in order, and within those, walking their subprograms.  (Maybe it is?)

Although DW_TAG_subprograms usually de-dup, you can trivially create a discrepancy by having the `weak_odr` come from a compile_unit that was compiled in a different directory than the `linkonce_odr`, and linking in the `weak_odr` version second.

I think (?) the right result would be for the destination module to only contain one copy of the subprogram, and for it to be the one from the compile unit that had `weak_odr` linkage.  It's not clear whether that's practical, though.

Attaching repro.tar.gz, which demonstrates how to create the discrepancy:

$ tar xzf repro.tar.gz
$ cd repro/
$ for f in *.h */*.cpp; do echo "// $f"; cat $f; done
// t.h
template <class T> struct Class {
  int foo() { return 0; }
};
// d1/t1.cpp
#include "t.h"
int foo() { return Class<int>().foo(); }
// d2/t2.cpp
#include "t.h"
template struct Class<int>;
$ make
cd d1 && clang -I.. -c -emit-llvm -gline-tables-only -o t1.bc t1.cpp
cd d2 && clang -I.. -c -emit-llvm -gline-tables-only -o t2.bc t2.cpp
llvm-link -S -o linked.ll d1/t1.bc d2/t2.bc
llvm-link -o linked.bc d1/t1.bc d2/t2.bc
$ grep -e '!dbg !&#8203;20' linked.ll -B4
define weak_odr i32 @&#8203;_ZN5ClassIiE3fooEv(%struct.Class* %this) #&#8203;1 align 2 {
  %1 = alloca %struct.Class*, align 8
  store %struct.Class* %this, %struct.Class** %1, align 8
  %2 = load %struct.Class** %1
  ret i32 0, !dbg !&#8203;20
$ grep -e '^#20 ' linked.ll 
!&#8203;20 = metadata !{i32 2, i32 0, metadata !&#8203;13, null}
$ grep -e '@_ZN5ClassIiE3fooEv, ' linked.ll 
!&#8203;7 = metadata !{i32 786478, metadata !&#8203;8, metadata !&#8203;9, metadata !"foo", metadata !"foo", metadata !"", i32 2, metadata !&#8203;6, i1 false, i1 true, i32 0, i32 0, null, i32 256, i1 false, i32 (%struct.Class*)* @&#8203;_ZN5ClassIiE3fooEv, null, null, metadata !&#8203;2, i32 2}
!&#8203;13 = metadata !{i32 786478, metadata !&#8203;14, metadata !&#8203;15, metadata !"foo", metadata !"foo", metadata !"", i32 2, metadata !&#8203;6, i1 false, i1 true, i32 0, i32 0, null, i32 256, i1 false, i32 (%struct.Class*)* @&#8203;_ZN5ClassIiE3fooEv, null, null, metadata !&#8203;2, i32 2}

**Comment by dwblaikie** [comment]
> I have a two thoughts for longer term:
> 
> 1. `makeSubprogramMap()` is a gross hack.  Why don't we just attach metadata to the function?
>    ```
>    define void @&#8203;foo() !subprogram !&#8203;7 {
>        ret void
>    }
>    ```
>    This is a simple canonical place to find the "true" subprogram for a function.  Of course, it requires new IR, but metadata attachments to functions should be trivial to implement (and won't have nearly the overhead of attachments to instructions).  A few things to figure out:  can they be attached to declarations?  Do we handle arbitrary attachments, or just start with `!subprogram`?  Are they in the same namespace as instruction attachments, or a new one?

In the intervening decade... this ^ has been done (& by @dexonsmith if I recall correctly)

So I'll consider this bug closed due to that alone.

> 2. Once subprograms have a custom class -- as opposed to some generic MDNode -- we can update ModuleLinker/MapValue to have special handling for it.  The ModuleLinker should change the old canonical subprogram to "match" the new one (update directory, variable nodes, etc.), and then when we're pulling in the new metadata, the ValueMapper should redirect all references to the updated old one.

Not sure whethe (2) or something like it is done, or is desirable to do (subprograms do now have a custom class)
