### ISSUE TITLE
Missed optimisation for modulo 2

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22303]
|  |  |
| --- | --- |
| Bugzilla Link | [21929](https://llvm.org/bz21929) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @LebedevRI,@RKSimon,@nlewycky,@zygoloid,@silvasean,@rotateright |

## Extended Description 
See Godbolt snippet here: http://goo.gl/imHtck
```
inline int intMod(int x, int y)
{
	const int r = x % y;
	if(r < 0)
		return y + r;
	else
		return r;
}

int f(int x)
{
  return intMod(x, 2); // Should this optimse to x & 0x1 ?
  //return x & 0x1;
}
```

Compiles to:
```
f(int):
	movl	%edi, %eax
	shrl	$31, %eax
	addl	%edi, %eax
	andl	$-2, %eax
	subl	%eax, %edi
	movl	%edi, %eax
	shrl	$31, %eax
	leal	(%rdi,%rax,2), %eax
	ret
```

It seems to be valid to make the optimisation intMod(x, 2) = x & 0x1,
which LLVM doesn't do.

**Comment by RKSimon** [comment]
Alive: https://alive2.llvm.org/ce/z/zwFkMy

----------------------------------------
define i32 @src(i32 %0) {
%1:
  %2 = srem i32 %0, 2
  %3 = lshr i32 %2, 30
  %4 = and i32 %3, 2
  %5 = add i32 %4, %2
  ret i32 %5
}
=>
define i32 @tgt(i32 %0) {
%1:
  %2 = and i32 %0, 1
  ret i32 %2
}
Transformation seems to be correct!

**Comment by RKSimon** [comment]
Going into InstCombine we have:
```
define i32 @Za(i32 noundef %x) {
  %rem.i = srem i32 %x, 2
  %cmp.i = icmp slt i32 %rem.i, 0
  %add.i = select i1 %cmp.i, i32 2, i32 0
  %retval.0.i = add nsw i32 %add.i, %rem.i
  ret i32 %retval.0.i
}
```
which InstCombine converts to:
```
define i32 @Za(i32 noundef %x) {
  %rem.i = srem i32 %x, 2
  %1 = lshr i32 %rem.i, 30
  %2 = and i32 %1, 2
  %retval.0.i = add nsw i32 %2, %rem.i
  ret i32 %retval.0.i
}
```
Would we be better off folding:
```
  %cmp.i = icmp slt i32 %rem.i, 0
  %add.i = select i1 %cmp.i, i32 2, i32 0
-->
  %cmp.i = ashr i32 %rem.i, 31
  %add.i = and i32 %cmp.i, 2
```
which would then allow us to remove the ashr (as we only demand known sign bits)?

**Comment by RKSimon** [comment]
> ```
> 1. (x a>> y) & C -> x & C, if C only selects sign bits from x
> -  %0 = ashr i32 %rem.i, 31
> -  %1 = and i32 %0, 2
> +  %1 = and i32 %rem.i, 2 ; because %rem.i has >= 31 sign bits
> ```
Candidate Patch: https://reviews.llvm.org/D122340

**Comment by RKSimon** [comment]
Latest codegen: https://gcc.godbolt.org/z/We8fW8rYq
```
define i32 @_Z1fi(i32 %x) {
entry:
  %rem.i = srem i32 %x, 2
  %0 = lshr i32 %rem.i, 30
  %1 = and i32 %0, 2
  %retval.0.i = add nsw i32 %1, %rem.i
  ret i32 %retval.0.i
}
```

**Comment by RKSimon** [comment]
```
(x & 2^C) + x -> x & (2^C - 1), if bit C in x is a sign bit
```
Proof: https://alive2.llvm.org/ce/z/Ygq26C

**Comment by RKSimon** [comment]
> ```
> (x & 2^C) + x -> x & (2^C - 1), if bit C in x is a sign bit
> ```
> 
> Proof: https://alive2.llvm.org/ce/z/Ygq26C

Candidate Patch: https://reviews.llvm.org/D123374
