### ISSUE TITLE
iso646.h: clang-format removes whitespace between name and expression

### ISSUE THREAD

**Issue by EdSchouten** [llvm/llvm-project#22310]
|  |  |
| --- | --- |
| Bugzilla Link | [21936](https://llvm.org/bz21936) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
Assume one has the following header file:

#ifndef _ISO646_H_
#define _ISO646_H_

#ifndef __cplusplus
#define and &&
#define and_eq &=
#define bitand &
#define bitor |
#define compl ˜
#define not !
#define not_eq !=
#define or ||
#define or_eq |=
#define xor ^
#define xor_eq ^=
#endif

#endif

If you run clang-format on this header, you'll get:

$ clang-format35 ~/iso646.h 
Can't find usable .clang-format, using LLVM style
#ifndef _ISO646_H_
#define _ISO646_H_

#ifndef __cplusplus
#define and&&
#define and_eq &=
#define bitand&
#define bitor |
#define compl ˜
#define not!
#define not_eq !=
#define or ||
#define or_eq |=
#define xor ^
#define xor_eq ^=
#endif

Notice the missing spaces after "and", "bitand" and "not".

**Comment by mydeveloperday** [comment]
I can confirm that this issue has been resolved at some point between clang-format 8 and clang-format 12 (its broken in 8)

```
#ifndef _ISO646_H_
#define _ISO646_H_

#ifndef __cplusplus
#define and &&
#define and_eq &=
#define bitand &
#define bitor |
#define compl ˜
#define not !
#define not_eq !=
#define or ||
#define or_eq |=
#define xor ^
#define xor_eq ^=
#define _NoReturn [[noreturn]]
#endif

#endif
```
