### ISSUE TITLE
[fuzz, binary] Assertion `StartColNo <= EndColNo && "Trying to highlight whitespace??"' failed.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22329]
|  |  |
| --- | --- |
| Bugzilla Link | [21955](https://llvm.org/bz21955) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#23431  |
| Attachments | [test case](https://user-images.githubusercontent.com/60944935/143750615-2ae09d21-be8b-44d0-9ba3-61311c6bef07.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Fuzzing discovered that the attached test case, which contains a null byte, when given as input to

  clang -fno-crash-diagnostics -std=c++11 -xc++ -c -emit-llvm

causes this assertion failure:

clang-3.6: tools/clang/lib/Frontend/TextDiagnostic.cpp:969: void highlightRange(const clang::CharSourceRange&, unsigned int, clang::FileID, const {anonymous}::SourceColumnMap&, std::string&, const clang::SourceManager&, const clang::LangOptions&): Assertion `StartColNo <= EndColNo && "Trying to highlight whitespace??"' failed.

**Comment by AaronBallman** [comment]
The source has a null character in it immediately before the `<C>`, which surprised me. However, I cannot reproduce (with or without the null character), so closing as works for me.

**Comment by Endilll** [comment]
It doesn't reproduce even on assertions builds: https://cexplorer.testlabs.pro/z/dPjhT3
