### ISSUE TITLE
[fuzz, binary] Assertion `D.getName().getKind() != UnqualifiedId::IK_TemplateId && "should have a 'template<>' for this decl"' failed.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22332]
|  |  |
| --- | --- |
| Bugzilla Link | [21958](https://llvm.org/bz21958) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#23431  |
| Attachments | [test case](https://user-images.githubusercontent.com/60944935/143750618-c22883f2-8be9-4cca-9fb4-97a07903aee8.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Fuzzing discovered that the attached test case, which contains unprintable characters, when given as input to

  clang -fno-crash-diagnostics -std=c++11 -xc++ -c -emit-llvm

causes this assertion failure:

clang-3.6: tools/clang/lib/Sema/SemaDecl.cpp:5560: clang::NamedDecl* clang::Sema::ActOnVariableDeclarator(clang::Scope*, clang::Declarator&, clang::DeclContext*, clang::TypeSourceInfo*, clang::LookupResult&, clang::MultiTemplateParamsArg, bool&): Assertion `D.getName().getKind() != UnqualifiedId::IK_TemplateId && "should have a 'template<>' for this decl"' failed.

**Comment by AaronBallman** [comment]
I cannot reproduce, so closing as works for me.

**Comment by Endilll** [comment]
Fixed in Clang 3.7: https://cexplorer.testlabs.pro/z/dKb1r1
