### ISSUE TITLE
[fuzz] Assertion `Ctx->isFileContext() && "We should have been looking only at file context here already."' failed.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22344]
|  |  |
| --- | --- |
| Bugzilla Link | [21970](https://llvm.org/bz21970) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#23431  |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Fuzzing discovered that the test case below, when given as input to

  clang -fno-crash-diagnostics -std=c++11 -xc++ -c -emit-llvm

causes this assertion failure:

clang-3.6: tools/clang/lib/Sema/SemaLookup.cpp:1140: bool clang::Sema::CppLookupName(clang::LookupResult&, clang::Scope*): Assertion `Ctx->isFileContext() && "We should have been looking only at file context here already."' failed.

Test case:

--------------------------------------------------
class { template <typename I, I::(((; namespace { o
--------------------------------------------------

**Comment by Endilll** [comment]
Fixed in Clang 3.8: https://cexplorer.testlabs.pro/z/W4fMvx
