### ISSUE TITLE
[fuzz] Assertion `T->isIntegralOrEnumerationType() && "unexpected converted const type"' failed.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22346]
|  |  |
| --- | --- |
| Bugzilla Link | [21972](https://llvm.org/bz21972) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#23431  |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Fuzzing discovered that the test case below, when given as input to

  clang -fno-crash-diagnostics -std=c++11 -xc++ -c -emit-llvm

causes this assertion failure:

clang-3.6: tools/clang/lib/Sema/SemaOverload.cpp:5079: clang::ExprResult clang::Sema::CheckConvertedConstantExpression(clang::Expr*, clang::QualType, llvm::APSInt&, clang::Sema::CCEKind): Assertion `T->isIntegralOrEnumerationType() && "unexpected converted const type"' failed.

Test case:

--------------------------------------------------
template<typename T> struct p<enum E : T { a=1 };
--------------------------------------------------

**Comment by Endilll** [comment]
Fixed in Clang 5: https://cexplorer.testlabs.pro/z/YjWo1d
