### ISSUE TITLE
Add Clang C++ warning to suggest making non-virtual method const

### ISSUE THREAD

**Issue by EugeneZelenko** [llvm/llvm-project#22355]
|  |  |
| --- | --- |
| Bugzilla Link | [21981](https://llvm.org/bz21981) |
| Version | unspecified |
| OS | All |
| CC | @JonasToth,@Trass3r |

## Extended Description 
Hi!

I think will be great to have warning which will suggest to make non-vuirtual method const if doesn't modify object's state and/or call only other const methods.

Eugene.

**Comment by carlosgalvezp** [comment]
Already implemented in `readability-make-member-function-const`
