### ISSUE TITLE
Template instantiation marks decl invalid after it is completely defined

### ISSUE THREAD

**Issue by 991901f3-cc14-4404-b340-165691b62a58** [llvm/llvm-project#22415]
|  |  |
| --- | --- |
| Bugzilla Link | [22041](https://llvm.org/bz22041) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor |

## Extended Description 
consider:

```cpp
struct A;
template <typename T> struct SS { template <typename U> struct X; };
template <typename T> template <A> struct SS<T>::X<A *> { SS<int> X; };
```

Sema::InstantiateClass will call ActOnFields.  ActOnFields will mark the class as defined.  After that point, we will try to InstantiateClassTemplatePartialSpecialization.  However, this will fail causing us to setInvalidDecl() after the class has been defined.

**Comment by shafik** [comment]
Duplicate of: https://github.com/llvm/llvm-project/issues/21523
