### ISSUE TITLE
Regression(r159216): Source files with \127 assert

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#22422]
|  |  |
| --- | --- |
| Bugzilla Link | [22048](https://llvm.org/bz22048) |
| Version | trunk |
| OS | All |
| CC | @Weverything |

## Extended Description 
$ cat test.cc
#error 'avilability'
// Note that this has an ASCII 127 character after the 'v'
$ bin/clang -c test.cc
error: 'avilability'Assertion failed: (TextNormal && "Text highlighted at end of diagnostic message."), function printWordWrapped, file /Users/thakis/src/llvm-rw/tools/clang/lib/Frontend/TextDiagnostic.cpp, line 661.
0  clang-3.5                0x00000001095c59c9 llvm::sys::PrintStackTrace(__sFILE*) + 57
1  clang-3.5                0x00000001095c614b SignalHandler(int) + 635
2  libsystem_platform.dylib 0x00007fff872f7f1a _sigtramp + 26
3  libsystem_platform.dylib 0x00007fff5fe7a764 _sigtramp + 3635947620
4  clang-3.5                0x00000001095c5eb6 abort + 22
5  clang-3.5                0x00000001095c5e91 __assert_rtn + 81
6  clang-3.5                0x000000010982203e clang::TextDiagnostic::printDiagnosticMessage(llvm::raw_ostream&, bool, llvm::StringRef, unsigned int, unsigned int, bool) + 1054
7  clang-3.5                0x00000001098218fd clang::TextDiagnostic::emitDiagnosticMessage(clang::SourceLocation, clang::PresumedLoc, clang::DiagnosticsEngine::Level, llvm::StringRef, llvm::ArrayRef<clang::CharSourceRange>, clang::SourceManager const*, llvm::PointerUnion<clang::Diagnostic const*, clang::StoredDiagnostic const*>) + 285
8  clang-3.5                0x00000001097ea8b4 clang::DiagnosticRenderer::emitDiagnostic(clang::SourceLocation, clang::DiagnosticsEngine::Level, llvm::StringRef, llvm::ArrayRef<clang::CharSourceRange>, llvm::ArrayRef<clang::FixItHint>, clang::SourceManager const*, llvm::PointerUnion<clang::Diagnostic const*, clang::StoredDiagnostic const*>) + 1812
9  clang-3.5                0x0000000109828379 clang::TextDiagnosticPrinter::HandleDiagnostic(clang::DiagnosticsEngine::Level, clang::Diagnostic const&) + 1657
10 clang-3.5                0x00000001096a8b54 clang::DiagnosticIDs::ProcessDiag(clang::DiagnosticsEngine&) const + 484
11 clang-3.5                0x00000001096a3134 clang::DiagnosticsEngine::EmitCurrentDiagnostic(bool) + 100
12 clang-3.5                0x000000010aa2b281 clang::Preprocessor::HandleUserDiagnosticDirective(clang::Token&, bool) + 449
13 clang-3.5                0x000000010aa246b6 clang::Preprocessor::HandleDirective(clang::Token&) + 1382
14 clang-3.5                0x000000010a9ff321 clang::Lexer::LexTokenInternal(clang::Token&, bool) + 10305
15 clang-3.5                0x000000010a9fb8f0 clang::Lexer::Lex(clang::Token&) + 112
16 clang-3.5                0x000000010aa53844 clang::Preprocessor::Lex(clang::Token&) + 68
17 clang-3.5                0x0000000109f362c3 clang::ParseAST(clang::Sema&, bool, bool) + 195
18 clang-3.5                0x0000000109b8b82b clang::CodeGenAction::ExecuteAction() + 123
19 clang-3.5                0x00000001097eea83 clang::FrontendAction::Execute() + 67
20 clang-3.5                0x00000001097c02fc clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 972
21 clang-3.5                0x000000010982eff5 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 4149
22 clang-3.5                0x00000001086bc34c cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 1068
23 clang-3.5                0x00000001086baffe main + 11438
24 libdyld.dylib            0x00007fff8a2cf5c9 start + 1
25 libdyld.dylib            0x0000000000000033 start + 1976765035

This is because r159216 added a ToggleHighlight constant that's 127, but it didn't expect that source files could contain this character.

**Comment by Endilll** [comment]
Test cases here appear to be butchered both here and in Bugzilla archive.
Test case from #22330 appears to be fixed in Clang 3.7. As usual with test cases involving null character, it doesn't reproduce on Compiler Explorer.
