### ISSUE TITLE
clang-format: Allman option does not work reliably

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22478]
|  |  |
| --- | --- |
| Bugzilla Link | [22104](https://llvm.org/bz22104) |
| Version | unspecified |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mydeveloperday |

## Extended Description 
According to the documentation, Allman enforces "Always break before braces"

Unfortunately, it doesn't seem to be doing that for if statements or for loops (see below).

Repros with 3.5.0 and http://llvm.org/git/clang.git d287557ca022716d56a6ff4e7f8ba44a08ef9737

Thanks!

INPUT
```
void function() {
    for (unsigned i = 0; i < 5; i++) {
        if (YES) {
        }
        else {
        }
    }
}
```

OUTPUT
```
void function()
{
    for (unsigned i = 0; i < 5; i++) {
        if (YES) {
        }
        else
        {
        }
    }
}
```

**Comment by mydeveloperday** [comment]
Closing no futher response
