### ISSUE TITLE
Assertion failure when taking the size of template argument that is an ill-formed lambda type

### ISSUE THREAD

**Issue by Weverything** [llvm/llvm-project#22483]
|  |  |
| --- | --- |
| Bugzilla Link | [22109](https://llvm.org/bz22109) |
| Version | trunk |
| OS | Linux |
| CC | @majnemer |

## Extended Description 
```cpp
template <class T>
class A;

class B {
  A<int> a;
};

template <class X>
void F(X x) {
  int y = sizeof(x);
}

void Test(B b) {
  F([b]() {});
}
```

```console
clang -std=c++11 foo.cc

clang-3.5: ../tools/clang/lib/AST/RecordLayoutBuilder.cpp:2807: const clang::ASTRecordLayout &clang::ASTContext::getASTRecordLayout(const clang::RecordDecl *) const: Assertion `!D->isInvalidDecl() && "Cannot get layout of invalid decl!"' failed
```

It looks like the lambda is not marked as invalid, but should be.  Since Clang thinks the lambda is valid, it assumes that all parts of the lambda are valid as well, then asserting when it finds that the captured variable b has invalid type.

**Comment by shafik** [comment]
It looks like neither reproducer crashes on trunk: https://godbolt.org/z/oe76W4sGf or https://godbolt.org/z/6fc4Y8886

**Comment by Endilll** [comment]
Both examples were fixed in Clang 8: https://cexplorer.testlabs.pro/z/oq781z
