### ISSUE TITLE
clang-format: brace formatting in block variable declaration changes with block return type

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22560]
|  |  |
| --- | --- |
| Bugzilla Link | [22186](https://llvm.org/bz22186) |
| Version | unspecified |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mydeveloperday |

## Extended Description 
INPUT1
`void*(^block)()=^void*{if(a) return;};`

OUTPUT1
```
void * (^block)() = ^void *
{
  if (a)
    return;
};
```

INPUT2
`void(^block)()=^void{if(a) return;};`

OUTPUT2
```
void (^block)() = ^void {
  if (a)
    return;
};
```

Repros with
`-style='{"BasedOnStyle": "LLVM", "BreakBeforeBraces": "Allman"}'`
http://llvm.org/git/clang.git d287557ca022716d56a6ff4e7f8ba44a08ef9737

PS: Could someone please comment on whether the pointer orientation is correct in OUTPUT1? It looks strange.

**Comment by mydeveloperday** [comment]
with clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 7890afddec
ff01119f4d5e8825b43dd2c8361648)

I see the following

```
void (^block)() = ^void {
  if (a)
    return;
};

void * (^block)() = ^void * {
  if (a)
    return;
};
```

For this style  `PointerAlignment: Right` is correct


As this appears to be fixed I'm going to close this, feel free to reopen if  this doesn't solve your problem
