### ISSUE TITLE
Clang crashes when bitfield-width contains a functional cast expression for copy-constructing a record

### ISSUE THREAD

**Issue by 991901f3-cc14-4404-b340-165691b62a58** [llvm/llvm-project#22612]
|  |  |
| --- | --- |
| Bugzilla Link | [22238](https://llvm.org/bz22238) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor |

## Extended Description 
consider:
extern "C" {
struct T {
  char c;
} a;
struct B {
  x : T(a);
};
}

we diagnose with:
t.cpp:6:3: error: unknown type name 'x'
  x : T(a);

before crashing with:
lib/AST/ExprConstant.cpp:8565: llvm::APSInt clang::Expr::EvaluateKnownConstInt(const clang::ASTContext&, llvm::SmallVectorImpl<std::pair<clang::SourceLocation, clang::PartialDiagnostic> >*) const: Assertion `Result && "Could not evaluate expression"' failed

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.7: https://cexplorer.testlabs.pro/z/hrcc9x
