### ISSUE TITLE
Crash on implicit member access in initializer in dependent type

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#22629]
|  |  |
| --- | --- |
| Bugzilla Link | [22255](https://llvm.org/bz22255) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
This crashes:

```cpp
template <class> void redundant_typename() {
  struct A {
    int pT = pT;
  };
};

void f() {
  redundant_typename<int>();
}
```

If the initializer is spelled `= this->pT;` instead, it works. That's because the initializer is a CXXDependentScopeMemberExpr in that case, because Sema::ActOnMemberAccessExpr() calls ActOnDependentMemberExpr() for dependent members. Sema::BuildImplicitMemberExpr() doesn't do that -- adding code to do that makes the crash go away, but I'm pretty unsure if that's the right fix.

**Comment by Endilll** [comment]
Fixed in Clang 3.7: https://cexplorer.testlabs.pro/z/9bx77b
