### ISSUE TITLE
clang can't find gcc5 libraries

### ISSUE THREAD

**Issue by ismail** [llvm/llvm-project#22669]
|  |  |
| --- | --- |
| Bugzilla Link | [22295](https://llvm.org/bz22295) |
| Version | trunk |
| OS | Linux |
| CC | @arichardson,@zmodem |

## Extended Description 
With gcc5 on openSUSE we have the following gcc directory

/usr/lib64/gcc/x86_64-suse-linux/5/

clang fails to detect gcc here because Linux::GCCVersion::Parse function assumes gcc version number has a dot in it.

**Comment by EugeneZelenko** [comment]
@ismail" Could you please elaborate on reason(s) and also add relevant label(s)?
