### ISSUE TITLE
printing std::string reports "error: summary string parsing error"

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22687]
|  |  |
| --- | --- |
| Bugzilla Link | [22313](https://llvm.org/bz22313) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie,@rnk |

## Extended Description 
When trying to print out a std::string in lldb 3.5.0, it always reports error:

  (std::string) myVar = error: summary string parsing error

When I attempt to print out the raw data, it shows up as blank:

  (std::string) myVar = {}

**Comment by dwblaikie** [comment]
Install the debug info for your standard library, for instance on Debian you'd want to install a package something like this one: https://packages.debian.org/sid/libstdc++6-dbgsym (if you're using libstdc++6)
