### ISSUE TITLE
Assertion `StringIndexMap.count(s) && "String is not in table!"' failed.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22716]
|  |  |
| --- | --- |
| Bugzilla Link | [22342](https://llvm.org/bz22342) |
| Version | trunk |
| OS | Linux |
| Attachments | [Obtained by clang -O0 -S -save-temps](https://user-images.githubusercontent.com/60944935/143750809-2192cad1-3f23-42fe-8ed9-fad156958132.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @atamazov,@zygoloid |

## Extended Description 

Hi, 

Clang fails to compile the　attached code, which includes a function whose section and name is the same, and specified as an alias. 

<<<<<[section.c]
void sub1(void) __attribute__(( section("sub1"), alias("sub2") ));
void sub2(void) { return; }
>>>>>

% clang ./section.c -O0 -c
clang: /home/kama/llvm/include/llvm/MC/StringTableBuilder.h:53: size_t llvm::StringTableBuilder::getOffset(llvm::StringRef): Assertion `StringIndexMap.count(s) && "String is not in table!"' failed.
...

Clang is able to emit an assembler file, but fails to emit an object while gcc succeeds.
Adding to this, there is a difference in assembler files of gcc and clang.
The section of function b code is in .section a by clang and .text by gcc.

I don'n know which section is correct, but at least the assertion must be fixed.

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.5 and 3.6 with assertions enabled: https://cexplorer.testlabs.pro/z/49557z
