### ISSUE TITLE
Instantiation involving explicit destructor call crashes clang

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22768]
|  |  |
| --- | --- |
| Bugzilla Link | [22394](https://llvm.org/bz22394) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @bcardosolopes,@majnemer,@nico |

**Comment by shafik** [comment]
No longer crashes on trunk: https://godbolt.org/z/1jb6oEM3n

Looks like it was fixed after clang-3.5

**Comment by Endilll** [comment]
Both examples are fixed in Clang 4:
https://godbolt.org/z/MfGz67acP
https://godbolt.org/z/8nnvd47fx
