### ISSUE TITLE
crash in function SubstituteExplicitTemplateArguments

### ISSUE THREAD

**Issue by a1eaaf79-3824-4e4a-810d-221cd1b83ce5** [llvm/llvm-project#22773]
|  |  |
| --- | --- |
| Bugzilla Link | [22399](https://llvm.org/bz22399) |
| Version | trunk |
| OS | All |
| Attachments | [generation script](https://user-images.githubusercontent.com/92601337/143750844-4b898a42-c1ac-4cf8-a95b-c28911b31eb2.gz), [source code](https://user-images.githubusercontent.com/92601337/143750845-25086e9a-2940-4314-b04f-57cae1df3066.gz) |
| CC | @majnemer |

## Extended Description 
attached source and generation script

**Comment by shafik** [comment]
It looks likes this was fixed after clang-16: https://godbolt.org/z/nfTP7596z

CC @erichkeane
