### ISSUE TITLE
loop vectorizer fails to optimize dot product

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#22900]
|  |  |
| --- | --- |
| Bugzilla Link | [22526](https://llvm.org/bz22526) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
clang fails to optimize what looks like a very simple loop to me.
(run on ARM "Juno" box running Fedora 22 and using gcc 4.9.2 to compile llvm)

$ cat test.c
float foo(float *b, float *c) {
  int i;
  float v = 0.0;
  for(i = 0; i < 1000; i++) {
    v += b[i] + c[i];
  }
  return v;
}
$ clang -S -O3 -Rpass-analysis=loop-vectorize test.c
test.c:8:1: remark: loop not vectorized: value that could not be identified as
      reduction is used outside the loop [-Rpass-analysis=loop-vectorize]
}
^
test.c:8:1: note: could not determine the original source location for :0:0

**Comment by fhahn** [comment]
The original case is now vectorized: https://clang.godbolt.org/z/seE9odn7v

As for the strided case, whether this is profitable depends on the target.
