### ISSUE TITLE
crash in SubstFunctionType function

### ISSUE THREAD

**Issue by a1eaaf79-3824-4e4a-810d-221cd1b83ce5** [llvm/llvm-project#22911]
|  |  |
| --- | --- |
| Bugzilla Link | [22537](https://llvm.org/bz22537) |
| Version | trunk |
| OS | All |
| Attachments | [script](https://user-images.githubusercontent.com/92601337/143750911-c931c7bb-7d10-418c-9c1c-19721c5fc04e.gz) |

## Extended Description 
attached source code and script

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.6: https://godbolt.org/z/3WcG1e1ME
Reduced by C-Reduce:
```cpp
template <class Functor>
void apply_if_applicable(Functor functor) {
  functor(0)
}
struct A {
  ____C_A_T_C_H____T_E_S_T____10() {
  auto f = [](auto ) -> {}
  A a(enable_if_applicable(f)
```
