### ISSUE TITLE
Assertion failed: (LIsBuiltins && RIsBuiltins && "Non-built-in locations must be rooted in the main file"), function isBeforeInTranslationUnit

### ISSUE THREAD

**Issue by DimitryAndric** [llvm/llvm-project#22950]
|  |  |
| --- | --- |
| Bugzilla Link | [22576](https://llvm.org/bz22576) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@echristo,@jsonn |

## Extended Description 
This assertion was originally reported in a FreeBSD PR: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=197527

It reproduces with clang trunk r228967, and occurs during compilation of WebKit's LowLevelInterpreter.cpp, which is file containing quite a lot of generated inline assembly for the JavaScript engine.

I reduced the test case to just this two-liner:

    #pragma clang diagnostic ignored "-Wmissing-noreturn"
    __asm__(".Lfoo: movw r2, #:lower16:.Lbar - .Lfoo");

Compile this with:

    clang -cc1 -triple armv6 -emit-obj bug197527-reduced.c

Results in:

    Assertion failed: (LIsBuiltins && RIsBuiltins && "Non-built-in locations must be rooted in the main file"), function isBeforeInTranslationUnit, file /share/dim/src/llvm/trunk/tools/clang/lib/Basic/SourceManager.cpp, line 2091.
    Abort trap

**Comment by Endilll** [comment]
Both test cases appear to be fixed in Clang 3.7:
https://cexplorer.testlabs.pro/z/odjMGP
https://cexplorer.testlabs.pro/z/o3Mjrx
