### ISSUE TITLE
Xcode 4.6.3 fails to build llvm trunk LazyEmittingLayer.h

### ISSUE THREAD

**Issue by 0e6f8740-1d2a-4afc-85fd-df25c3a603fd** [llvm/llvm-project#22993]
|  |  |
| --- | --- |
| Bugzilla Link | [22619](https://llvm.org/bz22619) |
| Version | trunk |
| OS | MacOS X |
| CC | @alexcrichton |

## Extended Description 
clang-425.0.28 (from the last Xcode version supported on Lion) fails to compile llvm trunk r229298:

In file included from OrcMCJITReplacement.cpp:10:
In file included from /opt/local/var/macports/build/_opt_mports_dports_lang_llvm-3.7/llvm-3.7/work/trunk/lib/ExecutionEngine/Orc/OrcMCJITReplacement.h:20:
/opt/local/var/macports/build/_opt_mports_dports_lang_llvm-3.7/llvm-3.7/work/trunk/include/llvm/ExecutionEngine/Orc/LazyEmittingLayer.h:110:67: error: only virtual member functions can be marked 'override'
    bool provides(StringRef Name, bool ExportedSymbolsOnly) const override {
                                                                  ^~~~~~~~

**Comment by arsenm** [comment]
Old build problem
