### ISSUE TITLE
LLVM_THREAD_LOCAL causes build failure on Snow Leopard

### ISSUE THREAD

**Issue by 0e6f8740-1d2a-4afc-85fd-df25c3a603fd** [llvm/llvm-project#23000]
|  |  |
| --- | --- |
| Bugzilla Link | [22626](https://llvm.org/bz22626) |
| Version | trunk |
| OS | All |
| CC | @chandlerc |

## Extended Description 
Recent llvm trunk (r229298) fails to build on Snow Leopard.  r226372 built ok.

PrettyStackTrace.cpp:39:8: error: thread-local storage is unsupported for the current target
static LLVM_THREAD_LOCAL const PrettyStackTraceEntry *PrettyStackTraceHead =
       ^
/opt/local/var/macports/build/_opt_mports_dports_lang_llvm-3.7/llvm-3.7/work/trunk/include/llvm/Support/Compiler.h:403:27: note: expanded from macro 'LLVM_THREAD_LOCAL'
#define LLVM_THREAD_LOCAL __thread
                          ^
1 error generated.

**Comment by arsenm** [comment]
Old build issue
