### ISSUE TITLE
operator new and STL containers silently ignore element alignment

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23008]
|  |  |
| --- | --- |
| Bugzilla Link | [22634](https://llvm.org/bz22634) |
| Version | 3.5 |
| OS | All |
| Attachments | [testcase](https://user-images.githubusercontent.com/60944935/143750979-460e90ab-97ee-4cfd-9c29-39fe0a4a8c83.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @ts826848,@leezu,@mclow,@zygoloid,@vsapsai |

## Extended Description 

Even in C++11 mode, even with the C++11 alignas keyword, element alignment isn't honored by std::vector.

$ c++ vectoralign.cpp -o a --std=c++11 && ./a
ctor 0x7fec03c03950
ctor 0x7fec03c03990

Attaching testcase.

I only tested the 3.5svn version that's installed on Mac OSX 10.9.5 here.

$ c++ --version
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

Note: homologous libstdc++ bug report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65122

**Comment by philnik777** [comment]
Looking at https://godbolt.org/z/TW64o3qTo it seems like the bug has been fixed.

**Comment by mstorsjo** [comment]
> Looking at https://godbolt.org/z/TW64o3qTo it seems like the bug has been fixed.

It's fixed as long as using a C++ version of C++17 or newer, yes. For older versions of C++, the issue is still present. (Not saying that this is something that needs to be fixed, just clarifying the context of the fix.)
