### ISSUE TITLE
Crash when accessing files through a symlink

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23034]
|  |  |
| --- | --- |
| Bugzilla Link | [22660](https://llvm.org/bz22660) |
| Version | unspecified |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I get something like this :

==============
1.	/Users/manu/Documents/Sources/MacLibPc/H/Std/../Sdl/System.h:357:2: current parser token ';'
2.	/Users/manu/Documents/Sources/MacLibPc/H/Std/../Sdl/System.h:267:1: parsing struct/union/class body 'CSystem'
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: i386-apple-darwin13.4.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: error: unable to execute command: Segmentation fault: 11
clang: note: diagnostic msg: Error generating preprocessed source(s).
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 254
==============

when I tried to compile a source file through a symlink, and/or if its header file is accessed through a symlink.
When the header is in accessed through a symlink, the crash report starts at : "clang: error: unable to execute command: Segmentation fault: 11" (ie: no line error reported)

The symlink is created with the following command :
ln -s /Users/manu/Documents/Sources/MacLibPc/ /Users/manu/Documents/Sources/SymLibPc

**Comment by Endilll** [comment]
Unfortunately, we can't do much without a reproducer.
Feel free to reopen if you have additional information.
