### ISSUE TITLE
generator crashes with -mfpmath=387 -mno-sse

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23119]
|  |  |
| --- | --- |
| Bugzilla Link | [22745](https://llvm.org/bz22745) |
| Version | 3.5 |
| OS | Linux |
| Attachments | [preprocessed source and run script](https://user-images.githubusercontent.com/60944935/143751043-77fc3a62-9e20-45bc-9b4a-991aa42b5313.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @rotateright |

## Extended Description 

I'm working on a meshing code and noticed different results on MacBook and Lenovo machines. I think I've traced it to slightly different floating point arithmetic. Per this StackOverflow answer:

http://stackoverflow.com/questions/17663780/is-there-a-document-describing-how-clang-handles-excess-floating-point-precision

I tried compiling with "-O2 -mfpmath=387 -mno-sse", which crashed the clang code generator. Attached is a tarball with the clang output and the temporary files it requested.

I don't actually care so much whether clang can support this obscure combination of flags, what I'm really interested in is what flags do I use to get exactly the same answers on both machines.

I did see that bug 3604 is a possible duplicate, but clang still crashes so I'll submit this bug as a request that it not crash with these flags, instead exit cleanly with a descriptive error.

**Comment by Endilll** [comment]
I can't reproduce the crash using Clang 3.2 through 3.7 with assertions enabled.
Every one of them give me the following error: `fatal error: error in backend: SSE register return with SSE disabled`.
