### ISSUE TITLE
plugin crash

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23126]
|  |  |
| --- | --- |
| Bugzilla Link | [22752](https://llvm.org/bz22752) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 
Hi, I have a plugin crash. The plugin is working withclang version 3.4.1 but is crashing with clang version 3.5.1

0  clang           0x000000000201a1c2 llvm::sys::PrintStackTrace(_IO_FILE*) + 34
1  clang           0x0000000002019de4
2  libpthread.so.0 0x00007f38fdd087c0
3  clang           0x000000000066fd29 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 2697
4  clang           0x0000000000669780 cc1_main(char const**, char const**, char const*, void*) + 1040
5  clang           0x000000000064f7d6 main + 8070
6  libc.so.6       0x00007f38fcbb2c36 __libc_start_main + 230
7  clang           0x00000000006684fd

clang: note: diagnostic msg: Error generating preprocessed source(s).

**Comment by Endilll** [comment]
Author hasn't got back to us with more information to reproduce.
