### ISSUE TITLE
Clang is crashing with basic usage of std::async

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23157]
|  |  |
| --- | --- |
| Bugzilla Link | [22783](https://llvm.org/bz22783) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
This code segfaults in c++14/c++1z mode, not mattering whether libstdc++ or libc++ is being used:

#include <future>
int main() { std::async(std::launch::async, []{}); }

It doesn't crash in c++11 mode.

clang version 3.7.0 (trunk 231040) (llvm/trunk 231045)
Target: x86_64-unknown-linux-gnu
Thread model: posix

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.6 and 3.7: https://godbolt.org/z/xn7P49Ye6
