### ISSUE TITLE
CFL-AA doesn't understand internal global values properly

### ISSUE THREAD

**Issue by jmolloy** [llvm/llvm-project#23175]
|  |  |
| --- | --- |
| Bugzilla Link | [22801](https://llvm.org/bz22801) |
| Version | trunk |
| OS | All |
| CC | @gburgessiv,@hfinkel |

## Extended Description 
In the following code:

static int g_1 = 0;
int f3(int n, int * a) {
    int i;
    for (i = 0; i < n; ++i) {
	g_1 += a[i];
    }
    return g_1;
}

We know g_1 is internal and does not escape, therefore it cannot alias with a[i]. CFL cannot currently work this out.

**Comment by nunoplopes** [comment]
CFL AA was removed from LLVM. So, closing this.
