### ISSUE TITLE
CMAKE defines NDEBUG differently than Autoconf for Assertions.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23172]
|  |  |
| --- | --- |
| Bugzilla Link | [22798](https://llvm.org/bz22798) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @tedwoodward |

## Extended Description 
When going through _DEBUG, NDEBUG definitions found a difference between autoconf and cmake.

    llvm/Makefile.rules (MSVC case not applicable)

        ifeq ($(DISABLE_ASSERTIONS),1)
          CPP.Defines += -DNDEBUG
        else
          BuildMode := $(BuildMode)+Asserts
          CPP.Defines += -D_DEBUG
        endif

    llvm/cmake/modules/HandleLLVMOptions.cmake

        if( LLVM_ENABLE_ASSERTIONS )
          # MSVC doesn't like _DEBUG on release builds. See PR 4379.
          if( NOT MSVC )
            add_definitions( -D_DEBUG )
          endif()
          # On non-Debug builds cmake automatically defines NDEBUG, so we
          # explicitly undefine it:
          if( NOT uppercase_CMAKE_BUILD_TYPE STREQUAL "DEBUG" )
            add_definitions( -UNDEBUG )
            # Also remove /D NDEBUG to avoid MSVC warnings about conflicting defines.
            foreach (flags_var_to_scrub
                CMAKE_CXX_FLAGS_RELEASE
                CMAKE_CXX_FLAGS_RELWITHDEBINFO
                CMAKE_CXX_FLAGS_MINSIZEREL
                CMAKE_C_FLAGS_RELEASE
                CMAKE_C_FLAGS_RELWITHDEBINFO
                CMAKE_C_FLAGS_MINSIZEREL)
              string (REGEX REPLACE "(^| )[/-]D *NDEBUG($| )" " "
                "${flags_var_to_scrub}" "${${flags_var_to_scrub}}")
            endforeach()
          endif()
          --- BUG different than autoconf, if not msvc, -DNDEBUG
          if( NOT MSVC )
            add_definitions( -DNDEBUG )
          endif()
          ---
        endif()

**Comment by arsenm** [comment]
Autotools is dead so differences no longer matter
