### ISSUE TITLE
"error: ‘trunk’ was not declared in this scope" while compiling clang

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23190]
|  |  |
| --- | --- |
| Bugzilla Link | [22816](https://llvm.org/bz22816) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
System: stock debian7 64bit

checkout from SVN: llvm, clang, lldb, extra, compiler-rt

configure like this:

CC=gcc CXX=g++ ../llvm/configure --enable-targets=all

fails to compile:

llvm[4]: Compiling ASTWriter.cpp for Debug+Asserts build
/Users/afink/llvm/llvm/tools/clang/lib/Serialization/ASTWriter.cpp: In member function ‘void clang::ASTWriter::WriteControlBlock(clang::Preprocessor&, clang::ASTContext&, llvm::StringRef, const string&)’:
/Users/afink/llvm/llvm/tools/clang/lib/Serialization/ASTWriter.cpp:1155:20: error: ‘trunk’ was not declared in this scope
/Users/afink/llvm/llvm/tools/clang/lib/Serialization/ASTWriter.cpp:1156:39: error: no matching function for call to ‘llvm::SmallVector<long unsigned int, 64u>::push_back()’
/Users/afink/llvm/llvm/tools/clang/lib/Serialization/ASTWriter.cpp:1156:39: note: candidate is:
In file included from /Users/afink/llvm/llvm/include/llvm/ADT/ArrayRef.h:14:0,
                 from /Users/afink/llvm/llvm/include/llvm/ADT/APInt.h:19,
                 from /Users/afink/llvm/llvm/include/llvm/ADT/APFloat.h:20,
                 from /Users/afink/llvm/llvm/tools/clang/lib/Serialization/../../include/clang/AST/APValue.h:18,
                 from /Users/afink/llvm/llvm/tools/clang/lib/Serialization/../../include/clang/AST/Decl.h:17,
                 from /Users/afink/llvm/llvm/tools/clang/lib/Serialization/../../include/clang/Serialization/ASTWriter.h:18,
                 from /Users/afink/llvm/llvm/tools/clang/lib/Serialization/ASTWriter.cpp:14:
/Users/afink/llvm/llvm/include/llvm/ADT/SmallVector.h:328:8: note: void llvm::SmallVectorTemplateBase<T, true>::push_back(const T&) [with T = long unsigned int]
/Users/afink/llvm/llvm/include/llvm/ADT/SmallVector.h:328:8: note:   candidate expects 1 argument, 0 provided
/bin/rm: cannot remove `/Users/afink/llvm/llvm-build/tools/clang/lib/Serialization/Debug+Asserts/ASTWriter.d.tmp': No such file or directory

trying to compile using CMAKE fails too but with other errors (will open other ticket)

**Comment by arsenm** [comment]
Old build issue with make
