### ISSUE TITLE
fails to build using CMAKE under debian7

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23192]
|  |  |
| --- | --- |
| Bugzilla Link | [22818](https://llvm.org/bz22818) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
cmake ../llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=all

[ 87%] Building CXX object tools/lldb/source/Host/CMakeFiles/lldbHost.dir/common/Editline.cpp.o
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘unsigned char lldb_private::Editline::DeleteNextCharCommand(int)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:714:57: warning: cast from type ‘const LineInfo* {aka const lineinfo*}’ to type ‘LineInfo* {aka lineinfo*}’ casts away qualifiers [-Wcast-qual]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘unsigned char lldb_private::Editline::DeletePreviousCharCommand(int)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:758:57: warning: cast from type ‘const LineInfo* {aka const lineinfo*}’ to type ‘LineInfo* {aka lineinfo*}’ casts away qualifiers [-Wcast-qual]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘unsigned char lldb_private::Editline::FixIndentationCommand(int)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:864:57: warning: cast from type ‘const LineInfo* {aka const lineinfo*}’ to type ‘LineInfo* {aka lineinfo*}’ casts away qualifiers [-Wcast-qual]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘unsigned char lldb_private::Editline::RevertLineCommand(int)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:890:61: warning: cast from type ‘const LineInfo* {aka const lineinfo*}’ to type ‘LineInfo* {aka lineinfo*}’ casts away qualifiers [-Wcast-qual]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In lambda function:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1041:47: error: ‘this’ was not captured for this lambda function
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1042:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘void lldb_private::Editline::ConfigureEditor(bool)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1042:6: error: invalid cast from type ‘lldb_private::Editline::ConfigureEditor(bool)::<lambda(EditLine*)>’ to type ‘lldb_private::line_editor::EditlinePromptCallbackType {aka const char* (*)(editline*)}’
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In lambda function:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1046:55: error: ‘this’ was not captured for this lambda function
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1047:13: error: return-statement with a value, in function returning 'void' [-fpermissive]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘void lldb_private::Editline::ConfigureEditor(bool)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1047:14: error: invalid cast from type ‘lldb_private::Editline::ConfigureEditor(bool)::<lambda(EditLine*, lldb_private::line_editor::EditLineCharType*)>’ to type ‘lldb_private::line_editor::EditlineGetCharCallbackType {aka int (*)(editline*, char*)}’
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In lambda function:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1052:54: error: ‘this’ was not captured for this lambda function
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1053:12: error: return-statement with a value, in function returning 'void' [-fpermissive]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘void lldb_private::Editline::ConfigureEditor(bool)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1053:13: error: invalid cast from type ‘lldb_private::Editline::ConfigureEditor(bool)::<lambda(EditLine*, int)>’ to type ‘lldb_private::line_editor::EditlineCommandCallbackType {aka unsigned char (*)(editline*, int)}’
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In lambda function:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1056:54: error: ‘this’ was not captured for this lambda function
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1057:12: error: return-statement with a value, in function returning 'void' [-fpermissive]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘void lldb_private::Editline::ConfigureEditor(bool)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1057:13: error: invalid cast from type ‘lldb_private::Editline::ConfigureEditor(bool)::<lambda(EditLine*, int)>’ to type ‘lldb_private::line_editor::EditlineCommandCallbackType {aka unsigned char (*)(editline*, int)}’
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In lambda function:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1060:54: error: ‘this’ was not captured for this lambda function
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1061:12: error: return-statement with a value, in function returning 'void' [-fpermissive]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘void lldb_private::Editline::ConfigureEditor(bool)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1061:13: error: invalid cast from type ‘lldb_private::Editline::ConfigureEditor(bool)::<lambda(EditLine*, int)>’ to type ‘lldb_private::line_editor::EditlineCommandCallbackType {aka unsigned char (*)(editline*, int)}’
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In lambda function:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1064:54: error: ‘this’ was not captured for this lambda function
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1065:12: error: return-statement with a value, in function returning 'void' [-fpermissive]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘void lldb_private::Editline::ConfigureEditor(bool)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1065:13: error: invalid cast from type ‘lldb_private::Editline::ConfigureEditor(bool)::<lambda(EditLine*, int)>’ to type ‘lldb_private::line_editor::EditlineCommandCallbackType {aka unsigned char (*)(editline*, int)}’
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In lambda function:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1068:54: error: ‘this’ was not captured for this lambda function
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1069:12: error: return-statement with a value, in function returning 'void' [-fpermissive]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘void lldb_private::Editline::ConfigureEditor(bool)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1069:13: error: invalid cast from type ‘lldb_private::Editline::ConfigureEditor(bool)::<lambda(EditLine*, int)>’ to type ‘lldb_private::line_editor::EditlineCommandCallbackType {aka unsigned char (*)(editline*, int)}’
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In lambda function:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1072:54: error: ‘this’ was not captured for this lambda function
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1073:12: error: return-statement with a value, in function returning 'void' [-fpermissive]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘void lldb_private::Editline::ConfigureEditor(bool)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1073:13: error: invalid cast from type ‘lldb_private::Editline::ConfigureEditor(bool)::<lambda(EditLine*, int)>’ to type ‘lldb_private::line_editor::EditlineCommandCallbackType {aka unsigned char (*)(editline*, int)}’
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In lambda function:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1076:55: error: ‘this’ was not captured for this lambda function
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1077:13: error: return-statement with a value, in function returning 'void' [-fpermissive]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘void lldb_private::Editline::ConfigureEditor(bool)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1077:14: error: invalid cast from type ‘lldb_private::Editline::ConfigureEditor(bool)::<lambda(EditLine*, int)>’ to type ‘lldb_private::line_editor::EditlineCommandCallbackType {aka unsigned char (*)(editline*, int)}’
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In lambda function:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1080:55: error: ‘this’ was not captured for this lambda function
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1081:13: error: return-statement with a value, in function returning 'void' [-fpermissive]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘void lldb_private::Editline::ConfigureEditor(bool)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1081:14: error: invalid cast from type ‘lldb_private::Editline::ConfigureEditor(bool)::<lambda(EditLine*, int)>’ to type ‘lldb_private::line_editor::EditlineCommandCallbackType {aka unsigned char (*)(editline*, int)}’
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In lambda function:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1088:47: error: ‘this’ was not captured for this lambda function
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1089:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘void lldb_private::Editline::ConfigureEditor(bool)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1089:5: error: cannot convert ‘lldb_private::Editline::ConfigureEditor(bool)::<lambda(EditLine*, int)>’ to ‘lldb_private::line_editor::EditlineCommandCallbackType {aka unsigned char (*)(editline*, int)}’ in initialization
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In lambda function:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1106:54: error: ‘this’ was not captured for this lambda function
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1107:12: error: return-statement with a value, in function returning 'void' [-fpermissive]
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘void lldb_private::Editline::ConfigureEditor(bool)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1107:13: error: invalid cast from type ‘lldb_private::Editline::ConfigureEditor(bool)::<lambda(EditLine*, int)>’ to type ‘lldb_private::line_editor::EditlineCommandCallbackType {aka unsigned char (*)(editline*, int)}’
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp: In member function ‘bool lldb_private::Editline::GetLines(int, lldb_private::StringList&, bool&)’:
/Users/afink/development/svn/llvm/tools/lldb/source/Host/common/Editline.cpp:1385:60: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-deprecated-register" [enabled by default]
make[2]: *** [tools/lldb/source/Host/CMakeFiles/lldbHost.dir/common/Editline.cpp.o] Error 1
make[1]: *** [tools/lldb/source/Host/CMakeFiles/lldbHost.dir/all] Error 2
make: *** [all] Error 2
root@debian64:/Users/afink/development/svn/llvm-build6#

**Comment by arsenm** [comment]
Old build issue
