### ISSUE TITLE
[powerpc] powerpc-linux-gnu accesses memory below the stack

### ISSUE THREAD

**Issue by markus-oberhumer** [llvm/llvm-project#23193]
|  |  |
| --- | --- |
| Bugzilla Link | [22819](https://llvm.org/bz22819) |
| Version | 3.6 |
| OS | Linux |
| CC | @chmeeedalf,@hfinkel |

## Extended Description 
powerpc-linux-gnu accesses memory below the stack - please see "-4(1)" below.

This is a nasty one as it only shows up under rare conditions - it was
quite hard to find the real cause of the problem.

$ cat test.c

int foo(int *);

int test(int *a) {
    return foo(a) + 1;
}

// EOF

$ clang-3.6.0 -target powerpc-linux-gnu -O2 -Wall -save-temps -c test.c

$ cat test.s

        .text
        .file   "test.bc"
        .globl  test
        .align  2
        .type   test,@function
test:                                   # @&#8203;test
# BB#0:                                 # %entry
        mflr 0
        stw 31, -4(1)
        stw 0, 4(1)
        stwu 1, -16(1)
        mr 31, 1
        bl foo
        addi 3, 3, 1
        addi 1, 1, 16
        lwz 0, 4(1)
        lwz 31, -4(1)
        mtlr 0
        blr
.Ltmp0:
        .size   test, .Ltmp0-test
        .ident  "clang version 3.6.0 (tags/RELEASE_360/final)"
        .section        ".note.GNU-stack","",@progbits

**Comment by chenzheng1030** [comment]
https://godbolt.org/z/c5fT4o1cW

the trunk should generate expected instructions.
