### ISSUE TITLE
"return { value }" returns uninitialized std::initializer_list

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23235]
|  |  |
| --- | --- |
| Bugzilla Link | [22861](https://llvm.org/bz22861) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@hfinkel,@zygoloid |

## Extended Description 
Testcase:

#include <initializer_list>
#include <cstdio>

std::initializer_list<int> MakeList() {
  return { 7 };
}

void helper(std::initializer_list<int> list) {
  for (auto i : list) {
    printf("%d\n", i);
  }
}

int main() {
  helper(MakeList());
}

This prints "32767" on my system, and has an msan error indicating that the list allocated in MakeList was uninitialized memory, later read in the use of 'i' at the printf callsite.

GCC prints "7" which is what I'd expect. It's an x-value shouldn't go away until the ';' at the end of helper(), right?

**Comment by wheatman** [comment]
closing this since the program was buggy and clang now warns of the bug as of 7.0.0
https://godbolt.org/z/hKK9s1v4b

code
```
#include <initializer_list>
#include <cstdio>

std::initializer_list<int> MakeList() {
  return { 7 };
}

void helper(std::initializer_list<int> list) {
  for (auto i : list) {
    printf("%d\n", i);
  }
}

int main() {
  helper(MakeList());
}
```

warning
```
<source>:5:10: warning: returning address of local temporary object [-Wreturn-stack-address]
  return { 7 };
         ^~~~~
1 warning generated.
Compiler returned: 0
```
