### ISSUE TITLE
Document the test suite on the website

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23261]
|  |  |
| --- | --- |
| Bugzilla Link | [22887](https://llvm.org/bz22887) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
This is just a TODO for myself.  I will eventually pick up this bug.  

Documentation should include:

1) Commonly used command line arguments
2) Structure of a test case
3) test methods vs. private methods (hint: test methods start with "test")
4) attributes like @&#8203;pythonAPITest, @&#8203;skipIf, etc.
5) test logs
6) inline tests vs
7) How to run the test suite:  (ninja check-lldb & running from xcode)

As we think of more stuff that should be documented, respond to this bug

**Comment by DavidSpickett** [comment]
Whoever you were, seems like you did eventually pick it up :)

https://lldb.llvm.org/resources/test.html
