### ISSUE TITLE
clang 3.7 requires a definition of an unused variable if -g option is specified

### ISSUE THREAD

**Issue by e48d0f12-b0d3-485a-93ce-75b823b0ccac** [llvm/llvm-project#23276]
|  |  |
| --- | --- |
| Bugzilla Link | [22902](https://llvm.org/bz22902) |
| Version | trunk |
| OS | Linux |
| Attachments | [clang++ -v](https://user-images.githubusercontent.com/92601792/143751117-c5a5d2f6-e9a1-4edb-90f7-30f5fc44a85e.gz) |
| CC | @adrian-prantl,@dwblaikie,@DougGregor,@echristo |

## Extended Description 

The sample code below is compiled and linked successfully if -g option is not specified but it causes a linkage error if -g option is specified.

================ sample code ================
extern char dummy;

template<char&>
void f() {}

int main()
{
    f<dummy>();
}
================ sample code ================
with -g option: http://melpon.org/wandbox/permlink/Bt83IkZr8Mu1bW9s
w/o  -g option: http://melpon.org/wandbox/permlink/0Rgoup5odwqIrDju

Note that clang 3.3 compiles and links it successfully even though -g option is specified.

cf. http://melpon.org/wandbox/permlink/iXtqIsBEkDBOXhpL

**Comment by JOE1994** [comment]
Fixed as of `clang 18.1.0` : https://godbolt.org/z/rbMPqdj5a
