### ISSUE TITLE
llgo's libgo build failure on Linux 32bit (i686)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23282]
|  |  |
| --- | --- |
| Bugzilla Link | [22908](https://llvm.org/bz22908) |
| Version | trunk |
| OS | Linux |
| Attachments | [files mentioned in the log](https://user-images.githubusercontent.com/60944935/143751123-588093b3-7584-4403-b353-0709f0ef7e00.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Build for llvm and clang were successful, then failed at libgo with the following message:
CMake Error at /extra/llvm/llvm-build/tools/llgo/libgo-prefix/src/libgo-stamp/libgo-build.cmake:16 (message):
  Command failed: 2

   'make' '-j4'

Here's the error log:

clang-3.7: /extra/llvm/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.cpp:646: bool isUnsignedDIType(llvm::DwarfDebug*, llvm::DIType): Assertion `(Encoding == dwarf::DW_ATE_unsigned || Encoding == dwarf::DW_ATE_unsigned_char || Encoding == dwarf::DW_ATE_signed || Encoding == dwarf::DW_ATE_signed_char || Encoding == dwarf::DW_ATE_float || Encoding == dwarf::DW_ATE_UTF || Encoding == dwarf::DW_ATE_boolean || (Ty.getTag() == dwarf::DW_TAG_unspecified_type && Ty.getName() == "decltype(nullptr)")) && "Unsupported encoding"' failed.
#&#8203;0 0xa03e41c llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/extra/llvm/llvm-build/bin/clang-3.7+0xa03e41c)
#&#8203;1 0xa03e70d PrintStackTraceSignalHandler(void*) (/extra/llvm/llvm-build/bin/clang-3.7+0xa03e70d)
#&#8203;2 0xa03d25b SignalHandler(int) (/extra/llvm/llvm-build/bin/clang-3.7+0xa03d25b)
0  clang-3.7 0x0a03e41c llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 50
1  clang-3.7 0x0a03e70d
2  clang-3.7 0x0a03d25b
3            0x40022400 __kernel_sigreturn + 0
4            0x40022424 __kernel_vsyscall + 16
5  libc.so.6 0x4022d607 gsignal + 71
6  libc.so.6 0x40230a33 abort + 323
7  libc.so.6 0x40226757
8  libc.so.6 0x40226807
9  clang-3.7 0x0a36d02d
10 clang-3.7 0x0a36d485 llvm::DwarfUnit::addConstantValue(llvm::DIE&, llvm::MachineOperand const&, llvm::DIType) + 119
11 clang-3.7 0x0a398254 llvm::DwarfCompileUnit::constructVariableDIEImpl(llvm::DbgVariable const&, bool) + 700
12 clang-3.7 0x0a397f6f llvm::DwarfCompileUnit::constructVariableDIE(llvm::DbgVariable&, bool) + 57
13 clang-3.7 0x0a3985c5 llvm::DwarfCompileUnit::constructVariableDIE(llvm::DbgVariable&, llvm::LexicalScope const&, llvm::DIE*&) + 61
14 clang-3.7 0x0a3986af llvm::DwarfCompileUnit::createScopeChildrenDIE(llvm::LexicalScope*, llvm::SmallVectorImpl<std::unique_ptr<llvm::DIE, std::default_delete<llvm::DIE> > >&, unsigned int*) + 189
15 clang-3.7 0x0a39746c llvm::DwarfCompileUnit::constructScopeDIE(llvm::LexicalScope*, llvm::SmallVectorImpl<std::unique_ptr<llvm::DIE, std::default_delete<llvm::DIE> > >&) + 446
16 clang-3.7 0x0a398741 llvm::DwarfCompileUnit::createScopeChildrenDIE(llvm::LexicalScope*, llvm::SmallVectorImpl<std::unique_ptr<llvm::DIE, std::default_delete<llvm::DIE> > >&, unsigned int*) + 335
17 clang-3.7 0x0a39746c llvm::DwarfCompileUnit::constructScopeDIE(llvm::LexicalScope*, llvm::SmallVectorImpl<std::unique_ptr<llvm::DIE, std::default_delete<llvm::DIE> > >&) + 446
18 clang-3.7 0x0a398741 llvm::DwarfCompileUnit::createScopeChildrenDIE(llvm::LexicalScope*, llvm::SmallVectorImpl<std::unique_ptr<llvm::DIE, std::default_delete<llvm::DIE> > >&, unsigned int*) + 335
19 clang-3.7 0x0a39746c llvm::DwarfCompileUnit::constructScopeDIE(llvm::LexicalScope*, llvm::SmallVectorImpl<std::unique_ptr<llvm::DIE, std::default_delete<llvm::DIE> > >&) + 446
20 clang-3.7 0x0a398741 llvm::DwarfCompileUnit::createScopeChildrenDIE(llvm::LexicalScope*, llvm::SmallVectorImpl<std::unique_ptr<llvm::DIE, std::default_delete<llvm::DIE> > >&, unsigned int*) + 335
21 clang-3.7 0x0a398a64 llvm::DwarfCompileUnit::createAndAddScopeChildren(llvm::LexicalScope*, llvm::DIE&) + 92
22 clang-3.7 0x0a398929 llvm::DwarfCompileUnit::constructSubprogramScopeDIE(llvm::LexicalScope*) + 421
23 clang-3.7 0x0a346a7b llvm::DwarfDebug::endFunction(llvm::MachineFunction const*) + 1655
24 clang-3.7 0x0a32c472 llvm::AsmPrinter::EmitFunctionBody() + 3152
25 clang-3.7 0x09566cd5
26 clang-3.7 0x09955465 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) + 87
27 clang-3.7 0x09c7a395 llvm::FPPassManager::runOnFunction(llvm::Function&) + 301
28 clang-3.7 0x09c7a536 llvm::FPPassManager::runOnModule(llvm::Module&) + 92
29 clang-3.7 0x09c7a831
30 clang-3.7 0x09c7ae86 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 224
31 clang-3.7 0x09c7b085 llvm::legacy::PassManager::run(llvm::Module&) + 39
32 clang-3.7 0x0a57c073
33 clang-3.7 0x0a57c115 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::raw_ostream*) + 92
34 clang-3.7 0x0a55f8e7
35 clang-3.7 0x0aed95f9 clang::ParseAST(clang::Sema&, bool, bool) + 681
36 clang-3.7 0x0a221f27 clang::ASTFrontendAction::ExecuteAction() + 307
37 clang-3.7 0x0a561d8a clang::CodeGenAction::ExecuteAction() + 1584
38 clang-3.7 0x0a221a3a clang::FrontendAction::Execute() + 122
39 clang-3.7 0x0a1ec184 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 790
40 clang-3.7 0x0a3215eb clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 982
41 clang-3.7 0x08dd591d cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 754
42 clang-3.7 0x08dce56a
43 clang-3.7 0x08dceb56 main + 1099
44 libc.so.6 0x40218a83 __libc_start_main + 243
45 clang-3.7 0x08dcb711
Stack dump:
0.	Program arguments: /extra/llvm/llvm-build/bin/clang-3.7 -cc1 -triple i686-pc-linux-gnu -emit-obj -disable-free -main-file-name go-type-complex.c -mrelocation-model pic -pic-level 2 -mthread-model posix -split-stacks -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu pentium4 -momit-leaf-frame-pointer -g -dwarf-column-info -coverage-file /extra/llvm/llvm-build/tools/llgo/libgo/.libs/go-type-complex.o -resource-dir /extra/llvm/llvm-build/bin/../lib/clang/3.7.0 -dependency-file .deps/go-type-complex.Tpo -sys-header-deps -MP -MT go-type-complex.lo -D HAVE_CONFIG_H -D _GNU_SOURCE -D _LARGEFILE_SOURCE -D _FILE_OFFSET_BITS=64 -D PIC -I . -I /extra/llvm/llvm/tools/llgo/third_party/gofrontend/libgo -I /extra/llvm/llvm/tools/llgo/third_party/gofrontend/libgo/runtime -I /extra/llvm/llvm/tools/llgo/third_party/gofrontend/libgo/../libffi/include -I ../libffi/include -I /extra/llvm/llvm/tools/llgo/third_party/gofrontend/libgo/../libgcc -I /extra/llvm/llvm/tools/llgo/third_party/gofrontend/libgo/../libbacktrace -I ../../gcc/include -internal-isystem /usr/local/include -internal-isystem /extra/llvm/llvm-build/bin/../lib/clang/3.7.0/include -internal-externc-isystem /usr/include/i386-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O2 -Wall -Wextra -Wwrite-strings -Wcast-qual -Werror -Wno-microsoft -fconst-strings -fdebug-compilation-dir /extra/llvm/llvm-build/tools/llgo/libgo -ferror-limit 19 -fmessage-length 0 -pthread -mstackrealign -fms-extensions -fms-compatibility-version=18.00 -fobjc-runtime=gcc -fexceptions -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o .libs/go-type-complex.o -x c /extra/llvm/llvm/tools/llgo/third_party/gofrontend/libgo/runtime/go-type-complex.c 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/extra/llvm/llvm/tools/llgo/third_party/gofrontend/libgo/runtime/go-type-complex.c'.
4.	Running pass 'X86 Assembly / Object Emitter' on function '@__go_type_hash_complex'
clang-3.7: error: unable to execute command: Aborted (core dumped)
clang-3.7: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.7.0 (trunk 232262)
Target: i686-pc-linux-gnu
Thread model: posix
clang-3.7: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3.7: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3.7: note: diagnostic msg: /tmp/go-type-complex-2e903a.c
clang-3.7: note: diagnostic msg: /tmp/go-type-complex-2e903a.sh
clang-3.7: note: diagnostic msg: 

********************
make[5]: *** [go-type-complex.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [all-recursive] Error 1
make[3]: *** [all] Error 2

**Comment by xgupta** [comment]
llgo is not in the repo anymore.
