### ISSUE TITLE
Segmentation fault in -O2 for g++.dg/opt/inline11.C

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23290]
|  |  |
| --- | --- |
| Bugzilla Link | [22916](https://llvm.org/bz22916) |
| Version | trunk |
| OS | Linux |
| Attachments | [C++ source code](https://user-images.githubusercontent.com/60944935/143751131-7311c1b3-8797-4881-90d3-edccd9430419.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel |

## Extended Description 

I just tried to compile g++.dg/opt/inline11.C
from the gcc test suite. All ok without optimisation,
but Segmentation fault with -O2.

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.6 and 3.7: https://godbolt.org/z/57EdME7d7
