### ISSUE TITLE
DragonEgg 3.6 build failure

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23299]
|  |  |
| --- | --- |
| Bugzilla Link | [22925](https://llvm.org/bz22925) |
| Version | 3.6 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I'm hitting the following compilation error with dragonegg-3.6.0 && llvm-3.6.0 on Linux.

-bash-4.1$ make
Compiling Aliasing.cpp
/home/rcgorton/svn/Compiler/trunk/LLVM3_6/dragonegg-3.6.0.src/src/Aliasing.cpp: In function ‘llvm::MDNode* describeAliasSet(tree)’:
/home/rcgorton/svn/Compiler/trunk/LLVM3_6/dragonegg-3.6.0.src/src/Aliasing.cpp:140:16: error: ‘class llvm::MDNode’ has no member named ‘replaceAllUsesWith’
      LeafTag->replaceAllUsesWith(getTBAARoot());
               ^
make: *** [Aliasing.o] Error 1

--------
In LLVM3.5, MDNode is jointly derived from public Value, public FoldingSetNode; the method replaceAllUsesWith() is part of class Value.

In LLVM3.6, MDNode is derived from public Metadata; the Metadata class does not have such a method.

If I understand the LLVM3.6 release notes correctly, Metadata nodes do not have use-lists, but the Aliasing.cpp code appears to require use lists.  Unfortunately, I do not know enough about Metadata to be able to effect a patch/fix.

**Comment by asl** [comment]
Dragonegg is obsolete
