### ISSUE TITLE
CFL-AA is too conservative with inttoptr/ptrtoint instructions.

### ISSUE THREAD

**Issue by gburgessiv** [llvm/llvm-project#23301]
|  |  |
| --- | --- |
| Bugzilla Link | [22927](https://llvm.org/bz22927) |
| Version | trunk |
| OS | All |
| CC | @hfinkel |

## Extended Description 
CFLAA will answer more conservatively than it needs to given the following code:

%A = ptrtoint %Ptr
%B = inttoptr %A
; A is otherwise unused (or used only in other inttoptr instructions)

At the moment, the sets attached to %Ptr and %B will be marked as with AttrUnknown, but if we can prove that %A is used only in inttoptr instructions, then we can avoid the "unknown" attribute and simply unify the sets for %A, %B, etc.

Thanks to ol.sall@gmail.com for bringing this up.

**Comment by nunoplopes** [comment]
CFL AA was removed from LLVM. So, closing this.
