### ISSUE TITLE
autoconf picks up build machine's "strip" instead of picking up the strip from cross-compile toolchain

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23320]
|  |  |
| --- | --- |
| Bugzilla Link | [22946](https://llvm.org/bz22946) |
| Version | 3.5 |
| OS | Linux |
| Attachments | [Build log when it breaks](https://user-images.githubusercontent.com/60944935/143751145-a3d64911-aa3a-499d-abf2-3fb5c653077d.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

I am trying to cross-build Julia for ARMv6 using arm-buildroot-linux-uclibcgnueabi cross-compiler toolchain on an x86_64-linux-gnu.LLVM gets built during the Julia build process.While all other Julia dependency libraries are picking up "arm-buildroot-linux-uclibcgnueabi-strip" during the build process,LLVM build alone picks up  x86_64-linux-gnu-strip and thus the build breaks.
Is there any way I could force the LLVM build to use "arm-buildroot-linux-uclibcgnueabi-strip" ? 

I have attached the build error log when it breaks.

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
