### ISSUE TITLE
Python "print" statement used for defining ECHOPATH on mingw32

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23350]
|  |  |
| --- | --- |
| Bugzilla Link | [22976](https://llvm.org/bz22976) |
| Version | 3.6 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
In line 829 of Makefile.rules (3.6.0 source), python2 is assumed:

  ifeq (-mingw32,$(findstring -mingw32,$(BUILD_TRIPLE)))
    ECHOPATH := $(Verb)$(PYTHON) -u -c "import sys;print ' '.join(sys.argv[1:])"
  else
    ECHOPATH := $(Verb)$(ECHO)
  endif

It can be made py2/3 compatible by using the function form of print:

    ECHOPATH := $(Verb)$(PYTHON) -u -c "import sys;print(' '.join(sys.argv[1:]))"

**Comment by JOE1994** [comment]
Environment variable `ECHOPATH` is no longer used (as of LLVM 18)
