### ISSUE TITLE
check-lldb target is missing dependencies

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#23362]
|  |  |
| --- | --- |
| Bugzilla Link | [22988](https://llvm.org/bz22988) |
| Version | trunk |
| OS | All |
| CC | @martong,@vedantk |

## Extended Description 
This target doesn't seem to depend on lldb, lldb-mi, and other targets necessary for the tests to actually run properly.

**Comment by DavidSpickett** [comment]
Currently you get:
```
llvm-lit: /home/david.spickett/llvm-project/llvm/utils/lit/lit/llvm/subst.py:126: note: Did not find obj2yaml in /home/david.spickett/build-llvm-aarch64/./bin:/home/david.spickett/build-llvm-aarch64/./bin
llvm-lit: /home/david.spickett/llvm-project/llvm/utils/lit/lit/llvm/subst.py:126: note: Did not find llvm-objdump in /home/david.spickett/build-llvm-aarch64/./bin:/home/david.spickett/build-llvm-aarch64/./bin
```
When running lit, but these programs are not required for the tests themselves.

llvm-pdbutil is now listed as a test dependency.
