### ISSUE TITLE
function template/generic lambda/local class/member function => undefined symbol

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23363]
|  |  |
| --- | --- |
| Bugzilla Link | [22989](https://llvm.org/bz22989) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid,@rnk |

## Extended Description 
Attempts to call a member function in a local class nested in a generic lambda nested in a function template results in an undefined symbol link error.

template <class>
void f() {
    [](auto a) {
        struct C {
            static void g() {}
        };
        C::g();
    }(0);
}

int main() {
    f<void>();
}

$clang -std=c++14 link_error.cpp
  warning: inline function 'f()::(anonymous class)::operator()(int)::C::g' is not
  defined [-Wundefined-inline]
                        static void g() {}
                                    ^
  link_error.cpp:7:6: note: used here
                C::g();
                   ^
  1 warning generated.
  Undefined symbols for architecture x86_64:
    "auto void f<void>()::'lambda'(void)::operator()<int>(void) const::C::g()",
  referenced from:
    auto void f<void>()::'lambda'(void)::operator()<int>(void) const in
    link_error-b8a662.o
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)

$clang --version
  clang version 3.7.0  (http://llvm.org/git/llvm.git
    00edfaecf079bd80ed9d26f6e97fcdfc936c6937)
  Target: x86_64-apple-darwin14.1.0
  Thread model: posix

Also tested with 3.5 and 3.6 with same result.

**Comment by wheatman** [comment]
This was fixed between 3.6 and 3.7
https://godbolt.org/z/71vbad3z1
code 
```cpp
template <class>
void f() {
    [](auto a) {
        struct C {
            static void g() {}
        };
        C::g();
    }(0);
}

int main() {
    f<void>();
}
```

old error
```
<source>:5:25: warning: inline function 'f()::(anonymous class)::operator()(int)::C::g' is not defined [-Wundefined-inline]
            static void g() {}
                        ^
<source>:7:12: note: used here
        C::g();
           ^
1 warning generated.
ASM generation compiler returned: 0
<source>:5:25: warning: inline function 'f()::(anonymous class)::operator()(int)::C::g' is not defined [-Wundefined-inline]
            static void g() {}
                        ^
<source>:7:12: note: used here
        C::g();
           ^
1 warning generated.
/usr/bin/ld: /tmp/example-3f57aa.o: in function `operator()<int>':
<source>:7: undefined reference to `f<void>()::{lambda(auto:1)#1}::operator()<int>(int) const::C::g()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Execution build compiler returned: 1
```
