### ISSUE TITLE
With LTO, dead stripped ObjC protocols can result in linker error

### ISSUE THREAD

**Issue by pcc** [llvm/llvm-project#23381]
|  |  |
| --- | --- |
| Bugzilla Link | [23007](https://llvm.org/bz23007) |
| Version | trunk |
| OS | All |
| CC | @dexonsmith,@hiraditya,@nico |

## Extended Description 
On Darwin:

$ cat foo.mm
#import <Foundation/Foundation.h>

@&#8203;protocol CrAppProtocol
- (bool)isHandlingSendEvent;
@&#8203;end

bool foo(NSObject *obj) {
  return [obj conformsToProtocol:@protocol(CrAppProtocol)];
}
$ cat main.c
int main() {}
$ export DYLD_LIBRARY_PATH=$HOME/src/llvm-build-rel/lib 
$ $HOME/src/llvm-build-rel/bin/clang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -c -flto foo.mm main.c
$ ar cru libfoo.a foo.o
$ $HOME/src/llvm-build-rel/bin/clang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -flto -Wl,-ObjC -Wl,-dead_strip main.o libfoo.a
ld: warning: '__Z3fooP8NSObject' is implemented in bitcode, but it was loaded too late
Undefined symbols for architecture x86_64:
  "_objc_msgSend", referenced from:
      import-atom in libfoo.a(foo.o)
  "l_OBJC_PROTOCOL_REFERENCE_$_CrAppProtocol", referenced from:
      import-atom in libfoo.a(foo.o)
  "l_OBJC_LABEL_PROTOCOL_$_CrAppProtocol", referenced from:
      import-atom in libfoo.a(foo.o)
  "l_OBJC_PROTOCOL_$_CrAppProtocol", referenced from:
      l_OBJC_LABEL_PROTOCOL_$_CrAppProtocol in lto.o
      l_OBJC_PROTOCOL_REFERENCE_$_CrAppProtocol in lto.o
      import-atom in libfoo.a(foo.o)
      l_OBJC_LABEL_PROTOCOL_$_CrAppProtocol in libfoo.a(foo.o)
      l_OBJC_PROTOCOL_REFERENCE_$_CrAppProtocol in libfoo.a(foo.o)
ld: symbol(s) not found for architecture x86_64
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)

Reverting 209227 and 207979 in LLVM appears to fix this problem.

**Comment by hiraditya** [comment]
With xcode 13.3 the crash reported in: https://github.com/llvm/llvm-project/issues/23381#issuecomment-980944000 does not repro 

```
$ clang -v
Apple clang version 13.1.6 (clang-1316.0.21.2)
$ xcodebuild -version
Xcode 13.3
Build version 13E113

```

**Comment by fhahn** [comment]
Thanks @hiraditya , IICU this issue can be closed now. Please feel free to re-open if there's still anything left to fixed.
