### ISSUE TITLE
Segfault during llvm 3.6 build in llvm::SmallVectorImpl<char>::swap(llvm::SmallVectorImpl<char>&)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23387]
|  |  |
| --- | --- |
| Bugzilla Link | [23013](https://llvm.org/bz23013) |
| Version | 3.5 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @RKSimon |

## Extended Description 
Building llvm 3.6 segfaults while trying to build ScalarEvolution.cpp.

Bug occurs with -O0 and -emit-llvm. Bug doesn't occur with -w.

Attachments: https://gist.github.com/joelteon/23beb503b65361b36dd8 (scalar-min.i is the minimal .cpp testcase)

**Comment by arsenm** [comment]
Attached reproducer is a dead link
