### ISSUE TITLE
clant/tools Makefile pod2html incompatibility

### ISSUE THREAD

**Issue by e84d2fdb-199c-48b3-b9b5-4c43e784ffdc** [llvm/llvm-project#23428]
|  |  |
| --- | --- |
| Bugzilla Link | [23054](https://llvm.org/bz23054) |
| Version | 3.6 |
| OS | MacOS X |
| CC | @pkryger |

## Extended Description 
On OsX 10.10. Use clang from Apple, installed via xcode --select.
$ clang++ --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
$ brew --version
0.9.5

brew cannot install llvm (brew install llvm36 --with-libcxx --with-clang --rtti). brew output:

2015-03-28 08:46:18 +0000

make
VERBOSE=1
install
[...]
private/tmp/llvm3620150328-42496-m7aphz/llvm-3.6.0.src/autoconf/mkinstalldirs /private/tmp/llvm3620150328-42496-m7aphz/llvm-3.6.0.src/tools/clang/docs/tools/ > /dev/null
/bin/date > /private/tmp/llvm3620150328-42496-m7aphz/llvm-3.6.0.src/tools/clang/docs/tools//.dir
pod2html --css=manpage.css --htmlroot=. \
	  --podpath=. --infile=clang.pod --outfile=/private/tmp/llvm3620150328-42496-m7aphz/llvm-3.6.0.src/tools/clang/docs/tools/clang.html --title=clang
make[4]: pod2html: Permission denied
pod2man --release "clang 3.6.0" --center="Clang Tools Documentation" clang.pod /private/tmp/llvm3620150328-42496-m7aphz/llvm-3.6.0.src/tools/clang/docs/tools/clang.1
make[4]: *** [/private/tmp/llvm3620150328-42496-m7aphz/llvm-3.6.0.src/tools/clang/docs/tools/clang.html] Error 1
make[4]: *** Waiting for unfinished jobs....
rm /private/tmp/llvm3620150328-42496-m7aphz/llvm-3.6.0.src/tools/clang/docs/tools//.dir
make[3]: *** [install] Error 1
make[2]: *** [install] Error 1
make[1]: *** [clang/.makeinstall] Error 2
make: *** [install] Error 1

(full version here: https://gist.githubusercontent.com/anonymous/3f1a31e22d46aced723f/raw/07.make)

$ ls -l  /usr/bin/pod2html*
-rw-rw-rw-  37 root  wheel   811 10 Sep  2014 /usr/bin/pod2html
-rwxr-xr-x   1 root  wheel  2073 10 Sep  2014 /usr/bin/pod2html5.16
-rwxr-xr-x   1 root  wheel  2073 10 Sep  2014 /usr/bin/pod2html5.18

The file located at /usr/local/bin/pod2html path clearly states:
-- cut --
The contents of this script should normally never run!  The perl wrapper
should pick the correct script in /usr/bin by appending the appropriate version.
You can try appending the appropriate perl version number.  See perlmacosx.pod
for more information about multiple version support in Mac OS X.
-- cut --

I believe this is an issue with assumption in cfe/clang/docs/tools/Makefile, that pod2html is accessible (with exactly this name).

It builds when /usr/bin/pod2html5.18 is symlinked to pod2html (symlink earlier in path).

**Comment by Endilll** [comment]
Makefile support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
