### ISSUE TITLE
Weird initializer list formatting

### ISSUE THREAD

**Issue by eugenis** [llvm/llvm-project#23516]
|  |  |
| --- | --- |
| Bugzilla Link | [23142](https://llvm.org/bz23142) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Input:

```
#include <initializer_list>

class A {
 public:
  static constexpr std::initializer_list<uint64_t> kZZZZZZZZZZZZZZZZZZZZZZZZZZZ = {
      0x1234567890abcde0,  // aaaaaa bbbbbb cccccc dddddd eeeeee ffffff gggggg                                               
  };
};
```

Output:

```
#include <initializer_list>

class A {
public:
  static constexpr std::initializer_list<
      uint64_t> kZZZZZZZZZZZZZZZZZZZZZZZZZZZ = {
      0x1234567890abcde0, // aaaaaa bbbbbb cccccc dddddd eeeeee ffffff gggggg
  };
};
```

**Comment by mydeveloperday** [comment]
You don't really describe what is wierd about this other than the breaking of <uint64_t> which is what I assume you mean

Using the current main branch as of 2021.12.17 (clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 55d392cc30fb36e6361ba71f4b568c093f8b23f3) This what we see

```
#include <initializer_list>

class A {
public:
  static constexpr std::initializer_list<uint64_t>
      kZZZZZZZZZZZZZZZZZZZZZZZZZZZ = {
          0x1234567890abcde0, // aaaaaa bbbbbb cccccc dddddd eeeeee ffffff
                              // gggggg
  };
};
```

As this removes what I believe to be your wierdness I am closing this issue, but if you think you still have a problem feel free to reopen this issue  (but please include a .clang-format file and an example of input and what you expect)
