### ISSUE TITLE
Missing 'null passed to a callee that requires a non-null argument' warning for block expression invocations

### ISSUE THREAD

**Issue by tahonermann** [llvm/llvm-project#23520]
|  |  |
| --- | --- |
| Bugzilla Link | [23146](https://llvm.org/bz23146) |
| Version | trunk |
| OS | Linux |
| CC | @AaronBallman,@seanm |

## Extended Description 
Bug 23117 fixed (in r234297) an assertion failure that occurred when nonnull attributes appertain to block declarations.  Warnings are issued when invoking a block with a null argument for a block with a corresponding nonnull parameter when the attribute is explicitly specified for a block pointer type, but not for block invocations on block expressions that specify the attribute.  In the following example, a warning is emitted for the invocation of bp(0), but not for the block expression invocation.

$ cat t.c
void(^bp)(int *) __attribute__((nonnull(1)));
void f() {
    bp(0); // expected-warning{{null passed to a callee that requires a non-null argument}}
    ^(int *p1) __attribute__((nonnull(1))) {}(0); // expected-warning{{null passed to a callee that requires a non-null argument}}
}

$ clang -fblocks -c t.c
t.c:3:9: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
    bp(0);
       ~^
1 warning generated.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.7: https://cexplorer.testlabs.pro/z/eh767h
