### ISSUE TITLE
sNAN is not handled correct on legacy X87.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23532]
|  |  |
| --- | --- |
| Bugzilla Link | [23158](https://llvm.org/bz23158) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
When handling the float or double signaling NaN (sNAN) value with legacy X87 on x86. If it loads signal NaN to the x87 FP, the sNAN will be changed into into quiet NANs (qNAN). And Sometimes the value will be handled with normal regiter because of optimzation. This will leads to difference result.

**Comment by arsenm** [comment]
Signaling nan behavior isn't guaranteed when FENV_ACCESS isn't enabled. Support for FENV_ACCESS is partial at this point. For x87 specifically, it's unlikely perfect signaling nan behavior can be guaranteed
