### ISSUE TITLE
ICE on -O2 when using clang {3.7|3.5|3.4} from debian

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23584]
|  |  |
| --- | --- |
| Bugzilla Link | [23210](https://llvm.org/bz23210) |
| Version | 3.5 |
| OS | Linux |
| Attachments | [preprocessed file](https://user-images.githubusercontent.com/60944935/143751275-cc95371d-0f31-4dba-b63e-0e5abbbcbad9.gz), [preprocessed file from clang 3.8](https://user-images.githubusercontent.com/60944935/143751276-8dc01b76-71e6-4c0c-88eb-be0d101dca24.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
-O0 compiles fine

clang c.4 and 3.5 also crash when optimizations are on

repro:
$ clang++-3.7 -O2 -std=c++11 /tmp/ephemeral_rope_test-2c2816.cpp

output:
Debian clang version 3.7.0-svn230892-1 (trunk) (based on LLVM 3.7.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/i586-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/i586-linux-gnu/4.9.2
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/i586-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i586-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
 "/usr/lib/llvm-3.7/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -main-file-name ephemeral_rope_test.cpp -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -target-linker-version 2.25 -momit-leaf-frame-pointer -v -g -dwarf-column-info -resource-dir /usr/lib/llvm-3.7/bin/../lib/clang/3.7.0 -D FATAL_USE_CXXABI -I . -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-3.7/bin/../lib/clang/3.7.0/include -internal-externc-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O2 -Wall -Werror -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /home/marcelo/src/fatal -ferror-limit 19 -fmessage-length 0 -pthread -mstackrealign -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o /tmp/ephemeral_rope_test-8a4927.o -x c++ fatal/string/test/ephemeral_rope_test.cpp
clang -cc1 version 3.7.0 based upon LLVM 3.7.0 default target x86_64-pc-linux-gnu
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9"
#include "..." search starts here:
#include <...> search starts here:
 .
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward
 /usr/local/include
 /usr/lib/llvm-3.7/bin/../lib/clang/3.7.0/include
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Debian clang version 3.7.0-svn230892-1 (trunk) (based on LLVM 3.7.0)
Target: x86_64-pc-linux-gnu
Thread model: posix

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.6: https://godbolt.org/z/vf9vaxnKn
Reduced by C-Reduce:
```cpp
template <  typename >
struct Trans_NS_transform_impl_apply

template < template < typename... > , typename... Args >
using apply = Trans_NS_transform_impl_apply<  Args... >;

template < template <> TTemplate, typename... UArgs >
apply< TTemplate, Args..., UArgs>
```
