### ISSUE TITLE
clang doesn't warn when integer is tried against literal that is too big

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23585]
|  |  |
| --- | --- |
| Bugzilla Link | [23211](https://llvm.org/bz23211) |
| Version | 3.4 |
| OS | Linux |
| Attachments | [Testcase](https://user-images.githubusercontent.com/60944935/143751277-533d667d-b64e-4fed-8309-2b8fc6475280.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @davidstone |

## Extended Description 

Using the attached testcase, clang doesn't output any warnings when comparing an unsigned int against a literal that is too big in size. Compile Flags:

dtscode@dtscode-laptop:~/Desktop$ clang unsigned-test.c -o unsigned-test -Wall -Wextra -pedantic -Wtype-limits
dtscode@dtscode-laptop:~/Desktop$

using similar flags in gcc (with the addition of -std=c99 since I'm a few releases behind):

dtscode@dtscode-laptop:~/Desktop$ gcc -std=c99 unsigned-test.c -o unsigned-test -Wall -Wextra -pedantic
unsigned-test.c: In function ‘main’:
unsigned-test.c:5:3: warning: comparison is always true due to limited range of data type [-Wtype-limits]
   for (unsigned int i=0; i<=4294967295; i++) sum++;
   ^
dtscode@dtscode-laptop:~/Desktop$

**Comment by AaronBallman** [comment]
This is diagnosed with -Wtype-limits, so closing the issue.
