### ISSUE TITLE
clang 3.6 segmentation fault

### ISSUE THREAD

**Issue by blastrock** [llvm/llvm-project#23597]
|  |  |
| --- | --- |
| Bugzilla Link | [23223](https://llvm.org/bz23223) |
| Version | 3.6 |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
Clang crashes with the attached preprocessed source. The code is not correct and fixing the errors avoids the crash, but still :)

Compile with:
"clang-3.6" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-emit-obj" "-mrelax-all" "-disable-free" "-disable-llvm-verifier" "-main-file-name" "test2impl.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-mdisable-fp-elim" "-fmath-errno" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-fuse-init-array" "-target-cpu" "x86-64" "-g" "-dwarf-column-info" "-D" "test2_EXPORTS" "-fdeprecated-macro" "-ferror-limit" "19" "-fmessage-length" "0" "-mstackrealign" "-fobjc-runtime=gcc" "-fcxx-exceptions" "-fexceptions" "-fdiagnostics-show-option" "-x" "c++" "test2impl-c04fd2.cpp"

**Comment by ValZapod** [comment]
File is gone, @blastrock.
