### ISSUE TITLE
__attribute__((....)) causes strange indentation of function name

### ISSUE THREAD

**Issue by silvasean** [llvm/llvm-project#23615]
|  |  |
| --- | --- |
| Bugzilla Link | [23241](https://llvm.org/bz23241) |
| Version | unspecified |
| OS | All |

## Extended Description 
Before:

```
static __attribute__((__always_inline__, __nodebug__)) __m256i 
foo(__m256i __a, int imm8) {}
```

After:

```
static __attribute__((__always_inline__, __nodebug__)) __m256i
    foo(__m256i __a, int imm8) {}
```

The strange indentation doesn't happen if the `__attribute__((__always_inline__, __nodebug__)) __m256i` is replaced with an equivalent-length run of `a`'s. Doing this also seems to significantly affect the wrapping:

Before:

```
static aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
foo(__m256i __a, int imm8) {}
```

After:

```
static aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa foo(__m256i __a,
                                                                   int imm8) {}
```

**Comment by mydeveloperday** [comment]
With the current main version 2021.12.17 (clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 55d392cc30
fb36e6361ba71f4b568c093f8b23f3) I see this

With this as the .clang-format file

`BasedOnStyle: LLVM`

```
static __attribute__((__always_inline__, __nodebug__)) __m256i foo(__m256i __a,
                                                                   int imm8) {}
```

**Comment by mydeveloperday** [comment]
As this seems to be behaving as you suggest it should I am going to close this issue, however if you see have problems feel free to reopen this  (BTW I checked v8 and it was also the same as it is now)
