### ISSUE TITLE
clang miscompiles atomics by using optimized libcalls for underaligned storage

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#23637]
|  |  |
| --- | --- |
| Bugzilla Link | [23263](https://llvm.org/bz23263) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Per https://gcc.gnu.org/wiki/Atomic/GCCMM/LIbrary, "All the optimized routines expect that the object will be properly aligned for a data type of the specified size".

However, Clang and GCC get this wrong:

  struct X { int a, b; };
  X f(X *p) { X r; __atomic_load(p, &r, 5); return r; }

... calls __atomic_load_8. And GCC's libatomic implements __atomic_load_8 on x86_64 with a single 8-byte mov, which is only atomic for a correctly-aligned operand.

We should instead emit a call to __atomic_load(8, p, &r, 5) because we have no reason to think that p is 8 byte aligned.

The same happens for __atomic_store and probably all the other atomic libcalls.

**Comment by MaskRay** [comment]
`__atomic_load` is generated and the program ("Testcase: build the following code with libstdc++ ") passes for both -O0 and -O1.
