### ISSUE TITLE
assertion failure emitting lvalue address space cast

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#23635]
|  |  |
| --- | --- |
| Bugzilla Link | [23261](https://llvm.org/bz23261) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
This:
```cpp
  int __attribute__((address_space(1))) a = 0;
  void f() { int &b = reinterpret_cast<int&>(a); }
```
results in:

clang-3.6: IR/Constants.cpp:1571: static llvm::Constant *llvm::ConstantExpr::getCast(unsigned int, llvm::Constant *, llvm::Type *, bool): Assertion `CastInst::castIsValid(opc, C, Ty) && "Invalid constantexpr cast!"' failed.

**Comment by shafik** [comment]
I can't reproduce either of the crashes: https://godbolt.org/z/K656Mn45W

**Comment by Endilll** [comment]
The first example was fixed in Clang 9: https://cexplorer.testlabs.pro/z/f6sEhT
The second example was fixed in Clang 8: https://cexplorer.testlabs.pro/z/zY7fzf
