### ISSUE TITLE
Clang win32  assert  "The next DeclContext should be lexically contained in the current one."

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23701]
|  |  |
| --- | --- |
| Bugzilla Link | [23327](https://llvm.org/bz23327) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [Example code](https://user-images.githubusercontent.com/60944935/143751333-aa88afd9-eb96-4779-8f10-64957cc59348.gz), [clang logs and output (exprtk_test-53da00.cpp, exprtk_test-53da00.sh)](https://user-images.githubusercontent.com/60944935/143751334-f4cc51f6-36b9-4e59-a350-75f58e942a42.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @ismail |

## Extended Description 
Attached code example builds error/warning free with clang (3.2+) built on linux. 

However when attempting to build the same code, using the win32 clang build the following error is observed:

1>------ Rebuild All started: Project: exprtk_test, Configuration: Release Win32 ------
1>clang-cl.exe : warning : argument unused during compilation: '/GL'
1>clang-cl.exe : warning : argument unused during compilation: '/Gm-'
1>clang-cl.exe : warning : argument unused during compilation: '/GS'
1>  Assertion failed: getContainingDC(DC) == CurContext && "The next DeclContext should be lexically contained in the current one.", file D:\src\llvm_snapshot_235383\llvm\tools\clang\lib\Sema\SemaDecl.cpp, line 1073
1>  0x00C1BCE7 (0x00000016 0x0199BC72 0x00138888 0x056EE364)
1>  0x0199CF21 (0x02268D40 0x02268B60 0x00000431 0x0568BE20)
1>  0x01419017 (0x04FC06E0 0x056EE364 0x00138888 0x0636F9E0)
1>  0x012A82DD (0x00000000 0x00000000 0x0010F0D4 0x00138C28)
1>  0x00BA0274 (0x0636F9E0 0x0165B0CF 0x0014EFA8 0x0636F9E0)
1>  0x012A796D (0x0014EFA8 0x0636F9E0 0x07693960 0x004F90BE)
1>  0x0165B0CF (0x00108B10 0x02F2DDFC 0x02F2DDFC 0x00138888)
1>  0x014F347D (0x00000001 0x00139938 0x073EC4A0 0x00000000)
1>  0x013B0875 (0x073EC4C4 0x04939328 0x013B20B3 0x073EC520)
1>  0x0180FC94 (0x073EC520 0x013FDF8C 0x02F2DE8C 0x073EC4A0)
1>  0x013B20B3 (0x02F2DE8C 0x073EC4A0 0x00000000 0x00138888)
1>  0x013FDF8C (0x00000000 0x073EC4A0 0x07694048 0x07695358)
1>  0x013FDFB4 (0x00000600 0x000EA978 0x0759C088 0x00000008)
1>  0x013FA961 (0x004F90BE 0x07693960 0x00000001 0x00F2C500)
1>  0x0165D053 (0x00138888 0x07693960 0x00000000 0x02290480)
1>  0x00F1FF89 (0x00000001 0x073EC4A0 0x004FA804 0x00138888)
1>  0x0165B46A (0x073EC4A0 0x004FA804 0x00138888 0x073EC4A0)
1>clang-cl.exe : error : clang frontend command failed due to signal (use -v to see invocation)
1>  clang version 3.7.0 (trunk)
1>  Target: i686-pc-windows-msvc
1>  Thread model: posix
1>  clang-cl.exe: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
1>  clang-cl.exe: note: diagnostic msg:
1>  ********************
1>
1>  PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
1>  Preprocessed source(s) and associated run script(s) are located at:
1>  clang-cl.exe: note: diagnostic msg: C:\Users\user\AppData\Local\Temp\exprtk_test-53da00.cpp
1>  clang-cl.exe: note: diagnostic msg: C:\Users\user\AppData\Local\Temp\exprtk_test-53da00.sh
1>  clang-cl.exe: note: diagnostic msg:
1>
1>  ********************
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by ArashPartow** [comment]
This issue has been resolved in later versions of clang. As such recommend closing this issue.
