### ISSUE TITLE
LLVM_OPTIMIZED_TABLEGEN broken

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23702]
|  |  |
| --- | --- |
| Bugzilla Link | [23328](https://llvm.org/bz23328) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @llvm-beanz |

## Extended Description 
Tried to build with -DLLVM_OPTIMIZED_TABLEGEN=ON on x86-64 Linux (-DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON):

$ make
[  4%] Built target LLVMSupport
[  6%] Built target LLVMTableGen
[  8%] Built target llvm-tblgen
make[2]: *** No rule to make target 'NATIVE/bin/llvm-tblgen', needed by 'include/llvm/IR/Intrinsics.gen.tmp'.  Stop.
CMakeFiles/Makefile2:480: recipe for target 'include/llvm/IR/CMakeFiles/intrinsics_gen.dir/all' failed
make[1]: *** [include/llvm/IR/CMakeFiles/intrinsics_gen.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2

This is with r235577 and CMake 3.0.2.

Any idea what could be wrong?

If you know of any "known good" revisions I'd be happy to give it try to see if this is a regression.

**Comment by arsenm** [comment]
Old build problem
