### ISSUE TITLE
Initializing reference to array crashes clang: Assertion `CurInit.get()->isRValue() && "not a temporary"' failed.

### ISSUE THREAD

**Issue by 991901f3-cc14-4404-b340-165691b62a58** [llvm/llvm-project#23725]
|  |  |
| --- | --- |
| Bugzilla Link | [23351](https://llvm.org/bz23351) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
either:
const char (&V)[]{"a"};

or:
const char (&V)[1]{"a"};

results in:
lib/Sema/SemaInit.cpp:6031: clang::ExprResult clang::InitializationSequence::Perform(clang::Sema&, const clang::InitializedEntity&, const clang::InitializationKind&, clang::MultiExprArg, clang::QualType*): Assertion `CurInit.get()->isRValue() && "not a temporary"' failed.

**Comment by Endilll** [comment]
The first test case appears to be fixed in Clang 9: https://cexplorer.testlabs.pro/z/Yfxoc7
The second test case appears to be fixed in Clang 12: https://cexplorer.testlabs.pro/z/zWbvWW
