### ISSUE TITLE
Apt repository's have invalid paths in cmake files (Debian 8)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23733]
|  |  |
| --- | --- |
| Bugzilla Link | [23359](https://llvm.org/bz23359) |
| Version | 3.6 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
freshly installed Debian 8

Did execute this:

#
# LLVM 3.6
#
FILE=/etc/apt/sources.list.d/llvm.list
echo "deb http://llvm.org/apt/jessie/ llvm-toolchain-jessie-3.6 main" > $FILE
echo "deb-src http://llvm.org/apt/jessie/ llvm-toolchain-jessie-3.6 main" >> $FILE
wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key > /tmp/llvm-snapshot.gpg.key
apt-key add /tmp/llvm-snapshot.gpg.key
apt-get update
apt-get install clang-3.6 clang-3.6-doc libclang-common-3.6-dev libclang-3.6-dev libclang1-3.6 libclang1-3.6-dbg libllvm-3.6-ocaml-dev libllvm3.6 libllvm3.6-dbg lldb-3.6 llvm-3.6 llvm-3.6-dev llvm-3.6-doc llvm-3.6-examples llvm-3.6-runtime clang-modernize-3.6 clang-format-3.6 python-clang-3.6 lldb-3.6-dev libc++-dev libc++-helpers libc++-test libc++1

then I downloaded gnustep which I need to build for ObjectiveC 2.0 support (ARC).

wget http://download.gna.org/gnustep/libobjc2-1.7.tar.bz2
wget http://ftpmain.gnustep.org/pub/gnustep/core/gnustep-make-2.6.6.tar.gz
wget http://ftpmain.gnustep.org/pub/gnustep/core/gnustep-base-1.24.7.tar.gz
wget http://ftpmain.gnustep.org/pub/gnustep/core/gnustep-gui-0.24.0.tar.gz
wget http://ftpmain.gnustep.org/pub/gnustep/core/gnustep-back-0.24.0.tar.gz

tar -xvjf libobjc2-1.7.tar.bz2
tar -xvzf gnustep-make-2.6.6.tar.gz
tar -xvzf gnustep-back-0.24.0.tar.gz
tar -xvzf gnustep-base-1.24.7.tar.gz
tar -xvzf gnustep-gui-0.24.0.tar.gz

cd gnustep-make-2.6.6
./configure CC=clang-3.6 CXX=clang++-3.6 --disable-importing-config-file --enable-debug-by-default --enable-objc-nonfragile-abi
make install

cd ../libobjc2-1.7
mkdir build
cd build
cmake ..

this fails wit a cmake include file not found

Fix for this part: in file

	/usr/share/llvm-3.6/cmake/LLVMConfig.cmake

the line

	set(LLVM_CMAKE_DIR "/usr/lib/llvm-3.6/share/llvm/cmake")
	
should be
	
	set(LLVM_CMAKE_DIR "/usr/share/llvm-3.6/cmake")

(its being referenced by libobjc and line 53 fails)

When this is fixed, the make process gets further but still fails at a later stage in the AddLLVM.cmake file (couldn't figure out yet how to fix that part yet).

**Comment by arsenm** [comment]
Old build issue
