### ISSUE TITLE
-Wcast-qual doesn't work in C++

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23770]
|  |  |
| --- | --- |
| Bugzilla Link | [23396](https://llvm.org/bz23396) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@vangyzen,@rnk,@wjristow |

## Extended Description 
I don't see any warning:

clang++ bug.cpp -W -Wcast-qual

```c++
void f(const void *p1)
{
	char *p2 = (char *)p1;
}
```

Bug 4802 says it is fixed. Is the fix not included in the Windows version?

**Comment by xgupta** [comment]
This seems to be fixed -  https://godbolt.org/z/v95xa51xh.

**Comment by tbaederr** [comment]
I agree, so closing.
