### ISSUE TITLE
Unexpected arch error

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23789]
|  |  |
| --- | --- |
| Bugzilla Link | [23415](https://llvm.org/bz23415) |
| Version | 3.6 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
I am trying to build LLVM/Clang-3.6.0 on a Raspberry Pi 1 Development board.
I followed the instructions on the LLVM.org site to build LLVM/Clang from source.

Here is my configure command:
./configure --prefix=/home/pi/llvm/build --build=armv6l-unknown-linux-gnueabihf --host=armv6l-unknown-linux-gnueabihf --target=armv6l-unknown-linux-gnueabihf --with-cpu=arm1176jzf-s --with-float=hard --with-abi=aapcs-vfp --with-fpu=vfp --enable-targets=arm --enable-optimized --enable-assertions --enable-shared

The Build was successfull.

But when I tried to compile a simple helloworld.c program I am getting following errors:

pi@raspberrypi ~ $ clang hello.c
Unexpected arch
UNREACHABLE executed at Tools.cpp:7410!
Stack dump:
0.      Program arguments: clang hello.c
1.      Compilation construction
2.      Building compilation jobs
3.      Building compilation jobs
Aborted

pi@raspberrypi ~ $ clang -c hello.c
error: unknown target triple 'armv6l-unknown-linux-gnueabihf', please use -triple or -arch

**Comment by Endilll** [comment]
Seems like a terribly broken build.
