### ISSUE TITLE
Clang getting started - Visual Studio - Cmake fails

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23816]
|  |  |
| --- | --- |
| Bugzilla Link | [23442](https://llvm.org/bz23442) |
| Version | unspecified |
| OS | Windows NT |
| Attachments | [Cmake error log](https://user-images.githubusercontent.com/60944935/143751379-214a6bcd-0c6d-4516-a053-2e6bea6c8677.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

I follow the instructions on the site. However, Cmake fails with many files not found. I call cmake as stated for VS2012 from a separate build directory as advised, so Llvm and build have the same root. Clang sits as follows: \Llvm\tools\clang.

Attached are the log files.

I am REALLY new to this. Normally work in VS2012, win7 64 bit.

Also link to subversion has moved, is now here: https://subversion.apache.org/download/#recommended-release

Thanks for helping out, Jan

**Comment by xgupta** [comment]
too old, this can be close now.
