### ISSUE TITLE
Replying to issues from my MUA?

### ISSUE THREAD

**Issue by dnovillo** [llvm/llvm-project#23822]
|  |  |
| --- | --- |
| Bugzilla Link | [23448](https://llvm.org/bz23448) |
| Version | unspecified |
| OS | All |
| CC | @tlattner |

## Extended Description 
I'm not quite sure whether this is something that can changed with this bugzilla implementation or not.

I would like to be able to reply to bugs using my mailer and my reply automatically added to the bug trail. Currently, I'm forced to go to the web UI and reply from there.

Is this possible?

Thanks. Diego.

**Comment by arsenm** [comment]
Bugzilla is closed
