### ISSUE TITLE
using __attribute__((address_space(256))) crashes compiler in user mode

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23939]
|  |  |
| --- | --- |
| Bugzilla Link | [23565](https://llvm.org/bz23565) |
| Version | unspecified |
| OS | MacOS X |
| Attachments | [the test file](https://user-images.githubusercontent.com/60944935/143751446-f7fccc19-9eb4-4ec8-b85d-24d4dc3afd54.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @majnemer |

## Extended Description 

I was trying to test a code generation sequence for a function in kernel, clang crashes when trying to compile the code for user mode. 

#define SEGMENT_RELATIVE volatile __attribute__((address_space(256)))

void * test_segment()
{
	char SEGMENT_RELATIVE* uber_ptr = (char SEGMENT_RELATIVE *) 0UL;
	return (void*)(uber_ptr + 1);
}

**Comment by AaronBallman** [comment]
This appears to have been fixed in Clang 10.0.0.
