### ISSUE TITLE
Crash in llc with unusual initializer

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#2395]
|  |  |
| --- | --- |
| Bugzilla Link | [2023](https://llvm.org/bz2023) |
| Version | unspecified |
| OS | Linux |
| CC | @asl |

## Extended Description 
Testcase:

@&#8203;b =  global i16 ptrtoint (i16* @&#8203;b to i16)

run through llvm-as | llc, should generate code that initializes the global appropriately.

Current output:
llc: /home/eli/llvm/lib/CodeGen/AsmPrinter.cpp:789: void llvm::AsmPrinter::EmitConstantValueOnly(const llvm::Constant*): Assertion `0 && "FIXME: Don't yet support this kind of constant cast expr"' failed.

Fixing this isn't really a high priority for me, but I would like to know whether the fact that this doesn't work is considered a bug; see http://lists.cs.uiuc.edu/pipermail/cfe-dev/2008-February/001054.html.  I'm in the process of considering how to handle constant expressions in clang, and this affects what clang should accept as a constant expression.

**Comment by gwelymernans** [comment]
We now generate this:

```
	.globl	b
	.p2align	1
b:
	.short	b
	.size	b, 2
```

and GCC compiles it without issue.
