### ISSUE TITLE
Android buildbot - run arm tests twice: armeabi and armeabi-v7a binaries

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23950]
|  |  |
| --- | --- |
| Bugzilla Link | [23576](https://llvm.org/bz23576) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I think you need to add "-march=armv7-a -mfloat-abi=softfp" to CFLAGS
might also need

-Wl,--fix-cortex-a8

**Comment by DavidSpickett** [comment]
I don't believe there is an Android buildbot anymore, not a public one at least.

Linaro has a 32 bit Armv8 bot: https://lab.llvm.org/buildbot/#/builders/17
