### ISSUE TITLE
llvm-dis fails with assertion

### ISSUE THREAD

**Issue by Vsevolod-Livinskij** [llvm/llvm-project#24007]
|  |  |
| --- | --- |
| Bugzilla Link | [23633](https://llvm.org/bz23633) |
| Version | trunk |
| OS | Linux |
| Attachments | [Reproducer.](https://user-images.githubusercontent.com/92601286/143751479-416a57ec-7754-4586-9e63-a80c80dbc05e.gz) |
| CC | @dbabokin,@filcab,@Vsevolod-Livinskij |

## Extended Description 

llvm-dis fails with
llvm-dis: llvm-trunk/lib/Bitcode/Reader/BitcodeReader.cpp:788: llvm::Constant *(anonymous namespace)::BitcodeReaderValueList::getConstantFwdRef(unsigned int, llvm::Type *): Assertion `Ty == V->getType() && "Type mismatch in constant table!"' failed.

llvm-dis -version
LLVM (http://llvm.org/):
  LLVM version 3.7.0svn
  Optimized build with assertions.
  Built May 21 2015 (15:01:04).
  Default target: x86_64-unknown-linux-gnu
  Host CPU: sandybridge

clang version 3.7.0 (trunk 237892)

**Comment by arsenm** [comment]
Works on main
