### ISSUE TITLE
mm3dnow.h misses a number of intrinsics

### ISSUE THREAD

**Issue by DimitryAndric** [llvm/llvm-project#24022]
|  |  |
| --- | --- |
| Bugzilla Link | [23648](https://llvm.org/bz23648) |
| Version | trunk |
| OS | All |
| CC | @RKSimon |

## Extended Description 
This turned up during certain FreeBSD port builds.  Apparently the mmd3dnow.h header shipped with clang misses the following intrinsics:

__m64 _m_from_float(float);
__m64 _m_from_int(int);
void _m_prefetch(void *);
float _m_to_float(__m64);
int _m_to_int(__m64);

Note that the int variants are also not declared by gcc, e.g. these seem to be only relevant to Microsoft C.  Maybe it is not worth declaring them in mm3dnow.h, since they are already in the Microsoft-specific Intrin.h header.

**Comment by RKSimon** [comment]
Resolving - the 3dnow coverage is as good as its ever going to get.
