### ISSUE TITLE
AlwaysBreakAfterDefinitionReturnType gets confused by function prototypes with unnamed parameters

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24057]
|  |  |
| --- | --- |
| Bugzilla Link | [23683](https://llvm.org/bz23683) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Input: (test.c)

```
int
foo(char a)
{
        something();
}

int
bar(xyz)
{
        something();
}
```

clang-format -style="{BasedOnStyle: llvm, AllowShortFunctionsOnASingleLine: None, AlwaysBreakAfterDefinitionReturnType: true}" test.c

```
int
foo(char a) {
  something();
}

int bar(xyz) {
  something();
}
```

Note that in the second case, it didn't break after the return type.  The "xyz" could be a typedef or a macro to make this compile.  Note that it formats correctly when using a built-in type such as "char" instead of "xyz".

**Comment by mydeveloperday** [comment]
with clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 7890afddec
ff01119f4d5e8825b43dd2c8361648 this is the output
```
int
foo(char a) {
  something();
}

int
bar(xyz) {
  something();
}
```

As I believe this was fixed recently I'm closing this issue, if you still have issues with it feel free to reopen
