### ISSUE TITLE
building clang leads to crash

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24080]
|  |  |
| --- | --- |
| Bugzilla Link | [23706](https://llvm.org/bz23706) |
| Version | trunk |
| OS | Linux |
| Attachments | [preprocessed source](https://user-images.githubusercontent.com/60944935/143751505-0ac488c7-dd97-4b24-9002-ee94b51824b9.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

building the clang with g++ leads to a crash. see also attached files

message:

======= Memory map: ========
00400000-0351d000 r-xp 00000000 08:04 1050135                            /home/me/programme/clang/build/Release+Asserts/bin/clang
0371c000-03898000 r--p 0311c000 08:04 1050135                            /home/me/programme/clang/build/Release+Asserts/bin/clang
03898000-038a4000 rw-p 03298000 08:04 1050135                            /home/me/programme/clang/build/Release+Asserts/bin/clang
038a4000-038b4000 rw-p 00000000 00:00 0 
04d61000-04e87000 rw-p 00000000 00:00 0                                  [heap]
7fd783ff2000-7fd784190000 r-xp 00000000 08:03 785037                     /lib64/libc-2.19.so
7fd784190000-7fd78438f000 ---p 0019e000 08:03 785037                     /lib64/libc-2.19.so
7fd78438f000-7fd784393000 r--p 0019d000 08:03 785037                     /lib64/libc-2.19.so
7fd784393000-7fd784395000 rw-p 001a1000 08:03 785037                     /lib64/libc-2.19.so
7fd784395000-7fd784399000 rw-p 00000000 00:00 0 
7fd784399000-7fd7843af000 r-xp 00000000 08:03 1715367                    /usr/local/lib64/libgcc_s.so.1
7fd7843af000-7fd7845ae000 ---p 00016000 08:03 1715367                    /usr/local/lib64/libgcc_s.so.1
7fd7845ae000-7fd7845af000 r--p 00015000 08:03 1715367                    /usr/local/lib64/libgcc_s.so.1
7fd7845af000-7fd7845b0000 rw-p 00016000 08:03 1715367                    /usr/local/lib64/libgcc_s.so.1
7fd7845b0000-7fd7846b0000 r-xp 00000000 08:03 785069                     /lib64/libm-2.19.so
7fd7846b0000-7fd7848af000 ---p 00100000 08:03 785069                     /lib64/libm-2.19.so
7fd7848af000-7fd7848b0000 r--p 000ff000 08:03 785069                     /lib64/libm-2.19.so
7fd7848b0000-7fd7848b1000 rw-p 00100000 08:03 785069                     /lib64/libm-2.19.so
7fd7848b1000-7fd784a23000 r-xp 00000000 08:03 1716131                    /usr/local/lib64/libstdc++.so.6.0.21
7fd784a23000-7fd784c23000 ---p 00172000 08:03 1716131                    /usr/local/lib64/libstdc++.so.6.0.21
7fd784c23000-7fd784c2d000 r--p 00172000 08:03 1716131                    /usr/local/lib64/libstdc++.so.6.0.21
7fd784c2d000-7fd784c2f000 rw-p 0017c000 08:03 1716131                    /usr/local/lib64/libstdc++.so.6.0.21
7fd784c2f000-7fd784c33000 rw-p 00000000 00:00 0 
7fd784c33000-7fd784c36000 r-xp 00000000 08:03 785065                     /lib64/libdl-2.19.so
7fd784c36000-7fd784e35000 ---p 00003000 08:03 785065                     /lib64/libdl-2.19.so
7fd784e35000-7fd784e36000 r--p 00002000 08:03 785065                     /lib64/libdl-2.19.so
7fd784e36000-7fd784e37000 rw-p 00003000 08:03 785065                     /lib64/libdl-2.19.so
7fd784e37000-7fd784e4f000 r-xp 00000000 08:03 785140                     /lib64/libpthread-2.19.so
7fd784e4f000-7fd78504e000 ---p 00018000 08:03 785140                     /lib64/libpthread-2.19.so
7fd78504e000-7fd78504f000 r--p 00017000 08:03 785140                     /lib64/libpthread-2.19.so
7fd78504f000-7fd785050000 rw-p 00018000 08:03 785140                     /lib64/libpthread-2.19.so
7fd785050000-7fd785054000 rw-p 00000000 00:00 0 
7fd785054000-7fd785069000 r-xp 00000000 08:03 784983                     /lib64/libz.so.1.2.8
7fd785069000-7fd785268000 ---p 00015000 08:03 784983                     /lib64/libz.so.1.2.8
7fd785268000-7fd785269000 r--p 00014000 08:03 784983                     /lib64/libz.so.1.2.8
7fd785269000-7fd78526a000 rw-p 00015000 08:03 784983                     /lib64/libz.so.1.2.8
7fd78526a000-7fd78528a000 r-xp 00000000 08:03 785000                     /lib64/ld-2.19.so
7fd785431000-7fd785463000 rw-p 00000000 00:00 0 
7fd785482000-7fd785483000 rw-p 00000000 00:00 0 
7fd785483000-7fd785489000 r--p 00000000 08:04 2490681                    /home/me/programme/clang/build/Release+Asserts/lib/clang/3.7.0/include/stdint.h
7fd785489000-7fd78548a000 rw-p 00000000 00:00 0 
7fd78548a000-7fd78548b000 r--p 00020000 08:03 785000                     /lib64/ld-2.19.so
7fd78548b000-7fd78548c000 rw-p 00021000 08:03 785000                     /lib64/ld-2.19.so
7fd78548c000-7fd78548d000 rw-p 00000000 00:00 0 
7ffc8aec7000-7ffc8aee9000 rw-p 00000000 00:00 0                          [stack]
7ffc8afc3000-7ffc8afc5000 r-xp 00000000 00:00 0                          [vdso]
7ffc8afc5000-7ffc8afc7000 r--p 00000000 00:00 0                          [vvar]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
#&#8203;0 0x235b545 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/me/programme/clang/build/Release+Asserts/bin/clang+0x235b545)
#&#8203;1 0x235a081 SignalHandler(int) (/home/me/programme/clang/build/Release+Asserts/bin/clang+0x235a081)
#&#8203;2 0x7fd784e46890 __restore_rt (/lib64/libpthread.so.0+0xf890)
#&#8203;3 0x7fd784027187 __GI_raise (/lib64/libc.so.6+0x35187)
#&#8203;4 0x7fd784028538 __GI_abort (/lib64/libc.so.6+0x36538)
#&#8203;5 0x7fd784064844 (/lib64/libc.so.6+0x72844)
#&#8203;6 0x7fd78406a0ae malloc_printerr (/lib64/libc.so.6+0x780ae)
#&#8203;7 0x7fd78406adb6 _int_free (/lib64/libc.so.6+0x78db6)
#&#8203;8 0x9debd1 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::raw_pwrite_stream*) (/home/me/programme/clang/build/Release+Asserts/bin/clang+0x9debd1)
#&#8203;9 0x9cb4ec clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/me/programme/clang/build/Release+Asserts/bin/clang+0x9cb4ec)
#&#8203;10 0xbae7ea clang::ParseAST(clang::Sema&, bool, bool) (/home/me/programme/clang/build/Release+Asserts/bin/clang+0xbae7ea)
#&#8203;11 0x9cb5e7 clang::CodeGenAction::ExecuteAction() (/home/me/programme/clang/build/Release+Asserts/bin/clang+0x9cb5e7)
#&#8203;12 0x81fd96 clang::FrontendAction::Execute() (/home/me/programme/clang/build/Release+Asserts/bin/clang+0x81fd96)
#&#8203;13 0x7fa0f1 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/me/programme/clang/build/Release+Asserts/bin/clang+0x7fa0f1)
#&#8203;14 0x7e0222 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/me/programme/clang/build/Release+Asserts/bin/clang+0x7e0222)
#&#8203;15 0x7d8a08 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/me/programme/clang/build/Release+Asserts/bin/clang+0x7d8a08)
#&#8203;16 0x7b7bb3 main (/home/me/programme/clang/build/Release+Asserts/bin/clang+0x7b7bb3)
#&#8203;17 0x7fd784013b05 __libc_start_main (/lib64/libc.so.6+0x21b05)
#&#8203;18 0x7d7fe4 _start /home/abuild/rpmbuild/BUILD/glibc-2.19/csu/../sysdeps/x86_64/start.S:125:0
Stack dump:
0.      Program arguments: /home/me/programme/clang/build/Release+Asserts/bin/clang -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -main-file-name absvdi2.c -mrelocation-model pic -pic-level 2 -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -target-linker-version 13.2 -momit-leaf-frame-pointer -dwarf-column-info -coverage-file /home/me/programme/clang/build/tools/clang/runtime/compiler-rt/clang_linux/builtins-x86_64/x86_64/SubDir.lib__builtins/absvdi2.o -resource-dir /home/me/programme/clang/build/Release+Asserts/bin/../lib/clang/3.7.0 -I /home/me/programme/clang/llvm/projects/compiler-rt/lib -I /home/me/programme/clang/llvm/projects/compiler-rt/include -internal-isystem /usr/local/include -internal-isystem /home/me/programme/clang/build/Release+Asserts/bin/../lib/clang/3.7.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -Wall -Werror -fdebug-compilation-dir /home/me/programme/clang/llvm/projects/compiler-rt -ferror-limit 19 -fmessage-length 77 -mstackrealign -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o /home/me/programme/clang/build/tools/clang/runtime/compiler-rt/clang_linux/builtins-x86_64/x86_64/SubDir.lib__builtins/absvdi2.o -x c /home/me/programme/clang/llvm/projects/compiler-rt/lib/builtins/absvdi2.c 
1.      <eof> parser at end of file
clang: error: unable to execute command: Aborted
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.7.0 (trunk 238653)
Target: x86_64-unknown-linux-gnu
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/absvdi2-7d4223.c
clang: note: diagnostic msg: /tmp/absvdi2-7d4223.sh
clang: note: diagnostic msg: 

*******
second file to attach:

absvdi2-7d4223.sh, content:
# Crash reproducer for clang version 3.7.0 (trunk 238653)
# Original command:  "/home/me/programme/clang/build/Release+Asserts/bin/clang" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-emit-obj" "-disable-free" "-main-file-name" "absvdi2.c" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-fmath-errno" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-fuse-init-array" "-target-cpu" "x86-64" "-target-linker-version" "13.2" "-momit-leaf-frame-pointer" "-dwarf-column-info" "-coverage-file" "/home/me/programme/clang/build/tools/clang/runtime/compiler-rt/clang_linux/builtins-x86_64/x86_64/SubDir.lib__builtins/absvdi2.o" "-resource-dir" "/home/me/programme/clang/build/Release+Asserts/bin/../lib/clang/3.7.0" "-I" "/home/me/programme/clang/llvm/projects/compiler-rt/lib" "-I" "/home/me/programme/clang/llvm/projects/compiler-rt/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/home/me/programme/clang/build/Release+Asserts/bin/../lib/clang/3.7.0/include" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-O3" "-Wall" "-Werror" "-fdebug-compilation-dir" "/home/me/programme/clang/llvm/projects/compiler-rt" "-ferror-limit" "19" "-fmessage-length" "77" "-mstackrealign" "-fobjc-runtime=gcc" "-fdiagnostics-show-option" "-vectorize-loops" "-vectorize-slp" "-o" "/home/me/programme/clang/build/tools/clang/runtime/compiler-rt/clang_linux/builtins-x86_64/x86_64/SubDir.lib__builtins/absvdi2.o" "-x" "c" "/home/me/programme/clang/llvm/projects/compiler-rt/lib/builtins/absvdi2.c"
 "/home/me/programme/clang/build/Release+Asserts/bin/clang" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-emit-obj" "-disable-free" "-main-file-name" "absvdi2.c" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-fmath-errno" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-fuse-init-array" "-target-cpu" "x86-64" "-target-linker-version" "13.2" "-momit-leaf-frame-pointer" "-dwarf-column-info" "-O3" "-Wall" "-Werror" "-ferror-limit" "19" "-fmessage-length" "77" "-mstackrealign" "-fobjc-runtime=gcc" "-fdiagnostics-show-option" "-vectorize-loops" "-vectorize-slp" "-x" "c" "absvdi2-7d4223.c"

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.6 through 3.8 with assertions enabled.
