### ISSUE TITLE
buildbot - test arm32 inferiors on arm64 target

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24113]
|  |  |
| --- | --- |
| Bugzilla Link | [23739](https://llvm.org/bz23739) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Please add a build step to the Linux Android builder to test arm32 inferiors on an arm64 device.  (Still use the arm64 lldb-server binary)

**Comment by DavidSpickett** [comment]
There is no Android buildbot anymore. Existing builders for Linux check only 64 -> 64 and 32 -> 32. There are no plans to change that.
