### ISSUE TITLE
SROA replaces atomic volatile load with volatile load

### ISSUE THREAD

**Issue by 991901f3-cc14-4404-b340-165691b62a58** [llvm/llvm-project#24111]
|  |  |
| --- | --- |
| Bugzilla Link | [23737](https://llvm.org/bz23737) |
| Version | trunk |
| OS | Linux |
| CC | @chandlerc,@jfbastien |

## Extended Description 
consider:
target triple = "x86_64-pc-linux"

define void @&#8203;f(i64** %x) {
entry:
  %ptr = alloca i64, align 8
  store i64 0, i64* %ptr, align 8
  %load = load atomic volatile i64, i64* %ptr seq_cst, align 8
  ret void
}

running -sroa results in:
target triple = "x86_64-pc-linux"

define void @&#8203;f(i64** %x) {
entry:
  %ptr = alloca i64, align 8
  store i64 0, i64* %ptr, align 8
  %ptr.0.load = load volatile i64, i64* %ptr, align 8
  ret void
}

This doesn't seem correct.

**Comment by arsenm** [comment]
volatile is preserved today and last comment says partially fixed. Not sure what problem "non-volatile yet still atomics" had, but those are deleted as I would expect
