### ISSUE TITLE
attempted to build llvm again using formerly built llvm

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24129]
|  |  |
| --- | --- |
| Bugzilla Link | [23755](https://llvm.org/bz23755) |
| Version | 3.6 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
downloaded sources for 3.6.1
extracted the tarballs
clang extra tools was symlinked into the clang source tree as tools/extra
clang was symlinked into llvm source tree as tools/clang
lld was symlinked into llvm source tree as tools/lld
compiler-rt was symlinked into llvm source tree as projects/compiler-rt
libcxx was symlinked into llvm source tree as projects/libcxx
libcxxabi was symlinked into llvm source tree as projects/libcxxabi

I built this once using GCC and libstdc++.

I was hoping to build it again using the now available clang/clang++ and libc++/libc++abi, but when I attempt this, various executable linking stages fail claiming they can't find __cxa_guard_acquire, __cxa_guard_release, and __cxa_pure_virtual

this seems to indicate something isn't being linked against libc++, or that libc++ lacks those symbols/targets for some reason.

it is ENTIRELY possible that I did something incorrectly with my former build or setup or that I am doing something incorrectly this time.

the command for cmake would be something like this correct?:

cmake /path/to/llvm/source/tree \
-DCMAKE_INSTALL_PREFIX=/UCHC/HPC/Gooch/biotoolmodules/llvm_suite/3.6.1 \
-DCMAKE_C_COMPILER=/UCHC/HPC/Gooch/biotoolmodules/llvm_suite/3.6.1/bin/clang \
-DCMAKE_CXX_COMPILER=/UCHC/HPC/Gooch/biotoolmodules/llvm_suite/3.6.1/bin/clang++ \
-DLLVM_ENABLE_LIBCXX=1 \
-DLIBCXX_CXX_ABI=libcxxabi

if not, what am I missing?

**Comment by arsenm** [comment]
Old build issue

> i noticed a few of the .so files and executables showing the following in their ldd output: libstdc++.so.6 => 
> is it realistic to expect to build a functional llvm with no dependencies on gcc or gnu's libstdc++?

That's just the default host C++ default. If you want to build against libc++, you can use LLVM_ENABLE_LIBCXX. It's possible there's a bug with this where something ends up using the wrong one
