### ISSUE TITLE
Linux lldb-server arm64 can't get register information from 32 bit inferiors

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24173]
|  |  |
| --- | --- |
| Bugzilla Link | [23799](https://llvm.org/bz23799) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
REPRO:
Run arm64 "lldb-server --listen *:5432 --server"
./dotest.py --platform-url adb://<sn>:5432 lang/c/strings

Ovyalov:
"Potentially, if lldb-server will be capable to choose in runtime what register context to use (based on inferior architecture) then we should be able to share arm64 lldb-server both for 32-bit and 64-bit apps."

**Comment by DavidSpickett** [comment]
This is a known limitation. With AArch64 being increasingly more important (some CPUs even removing the 32 bit mode) I doubt that we will ever do this.
