### ISSUE TITLE
Mail from phabricator doesn't always thread correctly

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#24209]
|  |  |
| --- | --- |
| Bugzilla Link | [23835](https://llvm.org/bz23835) |
| Version | unspecified |
| OS | All |
| Attachments | [Screenshot showing the issue in the mail archive](https://user-images.githubusercontent.com/199297/143751586-41be873e-bf97-4d7f-a43b-2cbed8dc33e3.gz) |

## Extended Description 

Emails from phabricator don't always show up as a single thread of replies in the archive.

You can see an example in the attached image, for the "[PATCH] Improve formatting of lambda functions." thread from http://lists.cs.uiuc.edu/pipermail/cfe-commits/Week-of-Mon-20150608/thread.html

**Comment by xgupta** [comment]
Maybe llvm-iwg can help https://github.com/llvm/llvm-iwg/issues?

**Comment by fhahn** [comment]
Not sure if this is still an issue, but I doubt it will be fixed. Closing.
