### ISSUE TITLE
Crash while compiling

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24220]
|  |  |
| --- | --- |
| Bugzilla Link | [23846](https://llvm.org/bz23846) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I hit the following crash using r238013 to build my project:

0  clang           0x0000000000f0a645 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 37
1  clang           0x0000000000f09a11
2  libpthread.so.0 0x0000003797c0f500
3  clang           0x0000000000eb0be4 llvm::APInt::countLeadingZerosSlowCase() const + 36
4  clang           0x0000000000eb0cba llvm::APInt::EqualSlowCase(unsigned long) const + 90
5  clang           0x0000000000b34101
6  clang           0x0000000000b4efb9 llvm::ConstantExpr::getGetElementPtr(llvm::Type*, llvm::Constant*, llvm::ArrayRef<llvm::Value*>, bool, llvm::Type*) + 57
7  clang           0x0000000000871c06 llvm::SimplifyGEPInst(llvm::ArrayRef<llvm::Value*>, llvm::DataLayout const&, llvm::TargetLibraryInfo const*, llvm::DominatorTree const*, llvm::AssumptionCache*, llvm::Instruction const*) + 246
8  clang           0x000000000087282b llvm::SimplifyInstruction(llvm::Instruction*, llvm::DataLayout const&, llvm::TargetLibraryInfo const*, llvm::DominatorTree const*, llvm::AssumptionCache*) + 683
9  clang           0x0000000000dd72b1
10 clang           0x0000000000dd8575
11 clang           0x0000000000c08c3f llvm::FPPassManager::runOnFunction(llvm::Function&) + 623
12 clang           0x0000000000c08d1e llvm::legacy::FunctionPassManagerImpl::run(llvm::Function&) + 126
13 clang           0x0000000000c08dd4 llvm::legacy::FunctionPassManager::run(llvm::Function&) + 36
14 clang           0x000000000130601d clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::raw_pwrite_stream*) + 3837
15 clang           0x00000000012f13b0
16 clang           0x0000000001815885 clang::ParseAST(clang::Sema&, bool, bool) + 741
17 clang           0x0000000001087b86 clang::FrontendAction::Execute() + 118
18 clang           0x0000000001066c71 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 289
19 clang           0x000000000110f673 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 1939
20 clang           0x00000000006ccf48 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 968
21 clang           0x00000000006cc68e main + 9902
22 libc.so.6       0x000000379781ecdd __libc_start_main + 253
23 clang           0x00000000006c8b99
Stack dump:
0.      Program arguments: /data1/jenkins-workspace/xxx-gerrit/BUILD_TYPE/TSAN/label/xxx-gerrit-slaves/thirdparty/clang-238013/bin/clang -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -main-file-name module_builder.cc -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -target-feature +sse4.2 -momit-leaf-frame-pointer -g -dwarf-column-info -fno-unique-section-names -coverage-file /data1/jenkins-workspace/xxx-gerrit/BUILD_TYPE/TSAN/label/xxx-gerrit-slaves/src/xxx/codegen/CMakeFiles/codegen.dir/module_builder.cc.o -resource-dir /data1/jenkins-workspace/xxx-gerrit/BUILD_TYPE/TSAN/label/xxx-gerrit-slaves/thirdparty/clang-238013/bin/../lib/clang/3.7.0 -isystem /data1/jenkins-workspace/xxx-gerrit/BUILD_TYPE/TSAN/label/xxx-gerrit-slaves/thirdparty/installed/include -D DYNAMIC_ANNOTATIONS_ENABLED -D XXX_HEADERS_NO_STUBS=1 -D KUDU_HEADERS_USE_RICH_SLICE=1 -D XXX_HEADERS_USE_SHORT_STATUS_MACROS=1 -D XXX_STATIC_DEFINE -D LLVM_SUPPORT_VALGRIND_H -D THREAD_SANITIZER -D _GLIBCXX_EXTERN_TEMPLATE=0 -D __STDC_CONSTANT_MACROS -D __STDC_LIMIT_MACROS -D codegen_EXPORTS -D __STDC_FORMAT_MACROS -I /data1/jenkins-workspace/xxx-gerrit/BUILD_TYPE/TSAN/label/xxx-gerrit-slaves/src -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7 -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/x86_64-redhat-linux -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/backward -internal-isystem /usr/local/include -internal-isystem /data1/jenkins-workspace/xxx-gerrit/BUILD_TYPE/TSAN/label/xxx-gerrit-slaves/thirdparty/clang-238013/bin/../lib/clang/3.7.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O1 -Wall -Wno-sign-compare -Wno-deprecated -Wno-c++11-extensions -fdebug-compilation-dir /data1/jenkins-workspace/xxx-gerrit/BUILD_TYPE/TSAN/label/xxx-gerrit-slaves/src/xxx/codegen -ferror-limit 19 -fmessage-length 0 -fsanitize=thread -fsanitize-blacklist=/data1/jenkins-workspace/xxx-gerrit/BUILD_TYPE/TSAN/label/xxx-gerrit-slaves/build-support/sanitize-blacklist.txt -pthread -mstackrealign -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o CMakeFiles/codegen.dir/module_builder.cc.o -x c++ /data1/jenkins-workspace/xxx-gerrit/BUILD_TYPE/TSAN/label/xxx-gerrit-slaves/src/xxx/codegen/module_builder.cc 
1.      <eof> parser at end of file
2.      Per-function optimization
3.      Running pass 'Early CSE' on function '@_ZN4xxx7codegen13ModuleBuilder4InitEv'
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.7.0 (trunk)
Target: x86_64-unknown-linux-gnu
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.

Unfortunately the project isn't open source as of yet, so I can't share the preprocessed source generally. If the above isn't enough to repro, feel free to reply and I can probably get you a copy of the preprocessed source via email.

**Comment by nikic** [comment]
Closing this because it's a very old issue without a repro, unlikely to be actionable.
