### ISSUE TITLE
Adding a reviewer in Phabricator to a bug does not email the new reviewer

### ISSUE THREAD

**Issue by Weverything** [llvm/llvm-project#24228]
|  |  |
| --- | --- |
| Bugzilla Link | [23854](https://llvm.org/bz23854) |
| Version | unspecified |
| OS | Linux |
| CC | @rnk |

## Extended Description 
On patch http://reviews.llvm.org/D9665, I was added as a reviewer, but Phabricator did not email me.  I did not see any mail about this patch until the author pinged it.

**Comment by JOE1994** [comment]
Closing this as we no longer use `phabricator`.
