### ISSUE TITLE
Phabricator sometimes likes to send duplicate messages

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#24254]
|  |  |
| --- | --- |
| Bugzilla Link | [23880](https://llvm.org/bz23880) |
| Version | unspecified |
| OS | All |

## Extended Description 
Every so often two almost identical mails show up on a phabricator thread. It looked to me like this happens when somebody top-posts in an email reply to a phabricator thread - one mail goes to the list from the email author, another from phab. If this is what's happening, we should teach phab not to send the mail if the destination is already in the recipients list.

When I was looking at an example of this happening though, it looks like it might be more complicated than that. Consider these two mails:

  http://lists.cs.uiuc.edu/pipermail/llvm-commits/Week-of-Mon-20150615/281960.html
  http://lists.cs.uiuc.edu/pipermail/llvm-commits/Week-of-Mon-20150615/281961.html

They're identical, except the former is missing the part with inline replies. You'd think my explanation above was correct: the latter was from Chandler to the list, and the former from phab. This theory gets a bit muddier though, because both of these emails have the following headers:

  X-Phabricator-Sent-This-Message: Yes
  X-Phabricator-Mail-Tags: <differential-comment>

So I guess *both* came from phabricator? That's weird.

In any case, I'd really like to only receive the version with the full content, and not the one that repeats the start of the content.

**Comment by JOE1994** [comment]
Closing this as we no longer use `phabricator`.
