### ISSUE TITLE
Phabricator had a bad time with this patch that renamed some files.

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#24295]
|  |  |
| --- | --- |
| Bugzilla Link | [23921](https://llvm.org/bz23921) |
| Version | unspecified |
| OS | All |

## Extended Description 
The following patch from phabricator isn't even close to something that could apply:

  http://lists.cs.uiuc.edu/pipermail/llvm-commits/Week-of-Mon-20150622/283256.html

It modifies files that didn't exist, and it completely lacks the removal of the file that was moved. You can see what the patch was actually trying to do in the review and in the mailing list followup that included the patch directly:

  http://reviews.llvm.org/D10636
  http://lists.cs.uiuc.edu/pipermail/llvm-commits/attachments/20150622/8ef2382a/attachment.obj

**Comment by JOE1994** [comment]
Closing this as we no longer use `phabricator`.
