### ISSUE TITLE
Phabricator thinks FilCab needs to be more friendly

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#24312]
|  |  |
| --- | --- |
| Bugzilla Link | [23938](https://llvm.org/bz23938) |
| Version | unspecified |
| OS | All |
| CC | @LebedevRI,@rnk |

## Extended Description 
Either Phabricator has decided FilCab needs to be more friendly or it failed to parse his email.

Phab link:
http://reviews.llvm.org/D10710

Email link:
http://lists.cs.uiuc.edu/pipermail/llvm-commits/Week-of-Mon-20150622/283803.html

**Comment by JOE1994** [comment]
Closing this as we no longer use `phabricator`.
