### ISSUE TITLE
Accepts invalid when undeduced context encountered deducing from a trailing parameter pack

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [llvm/llvm-project#24313]
|  |  |
| --- | --- |
| Bugzilla Link | [23939](https://llvm.org/bz23939) |
| Version | trunk |
| OS | Windows NT |
| CC | @DougGregor |

## Extended Description 
In the call to "f" from "h" below, the deduction for T@1 should find both "fptype" and "Func" and fail.

### SOURCE (<stdin>):
```cpp
template <typename ...T> struct A;

void g();
void g(bool);

typedef void (*fptype)();
struct Func { operator fptype(); } func;

template<typename ...T> void f(A<T ...> *ap, T ...b);

void h(A<fptype, fptype> *ap) { f(ap, g, func); }
```

### COMPILER INVOCATION:
`clang++ -std=c++11 -c -x c++ -`

### ACTUAL OUTPUT:
(Clean compile).

### EXPECTED OUTPUT:
(Error message).

### COMPILER VERSION INFO:
clang version 3.7.0 (trunk)
Target: powerpc64le-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/ppc64le-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/ppc64le-redhat-linux/4.8.3
Selected GCC installation: /usr/lib/gcc/ppc64le-redhat-linux/4.8.3
Candidate multilib: .;@m64
Selected multilib: .;@m64

**Comment by wheatman** [comment]
This went from accepted to rejected between 3.9 and 4.0
https://godbolt.org/z/Mdz49Mfd4

However it is still accepted by gcc, so leaving it open for somebody better than me to interpret which is correct 

code
```
template <typename ...T> struct A;

void g();
void g(bool);

typedef void (*fptype)();
struct Func { operator fptype(); } func;

template<typename ...T> void f(A<T ...> *ap, T ...b);

void h(A<fptype, fptype> *ap) { f(ap, g, func); }
```

reject error
```
<source>:11:33: error: no matching function for call to 'f'
void h(A<fptype, fptype> *ap) { f(ap, g, func); }
                                ^
<source>:9:30: note: candidate template ignored: deduced conflicting types for parameter 'T' (<void (*)(), void (*)()> vs. <(no value), Func>)
template<typename ...T> void f(A<T ...> *ap, T ...b);
                             ^
1 error generated.
Compiler returned: 1
```

**Comment by shafik** [comment]
@hubert-reinterpretcast it looks like only gcc accepts this now: https://godbolt.org/z/bYzs8v4oo

Do you consider this a gcc bug?

**Comment by cor3ntin** [comment]
Looks like a gcc bug. Feel free to reopen if you think clang behavior still needs to be adapted
