### ISSUE TITLE
clang crashes due to infinite template recursion

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24317]
|  |  |
| --- | --- |
| Bugzilla Link | [23943](https://llvm.org/bz23943) |
| Version | 3.6 |
| OS | Windows NT |
| Attachments | [the crash backtrace](https://user-images.githubusercontent.com/60944935/143751635-0dcaa3c6-dd88-490a-9b95-3f2a89d6385b.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @rnk |

## Extended Description 

Clang crashes when given a type dependent on infinite-recursive template as a template parameter.

The code is not valid as it is, but the clang crashing was not the expected reaction.

You can reproduce the issue by compiling the following code with Clang 3.6.1 (I'm using the build from MSYS2)

template<typename T>
struct Concat
{
	typedef int type;
};

template<typename T, T Count>
struct Iota
{
	typedef typename Concat<
		typename Iota<T, Count-1>::type
	>::type type;
};

Iota<int, 4>::type err;

int main() {}

The run script is as follows:

 "C:\\__MOJE\\prog\\MSYS2_Toolset64\\mingw64\\bin\\clang++.exe" "-cc1" "-triple" "x86_64-w64-windows-gnu" "-emit-obj" "-mrelax-all" "-disable-free" "-disable-llvm-verifier" "-main-file-name" "ice.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-mdisable-fp-elim" "-fmath-errno" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-target-linker-version" "2.25" "-dwarf-column-info" "-std=c++11" "-fdeprecated-macro" "-ferror-limit" "19" "-fmessage-length" "0" "-mstackrealign" "-fno-use-cxa-atexit" "-fobjc-runtime=gcc" "-fcxx-exceptions" "-fexceptions" "-fdiagnostics-show-option" "-x" "c++" "ice-143b03.cpp"

The trace is in the attachment.

The clang++ -v output is:

clang version 3.6.1 (tags/RELEASE_361/final)
Target: x86_64-w64-windows-gnu
Thread model: posix

**Comment by Endilll** [comment]
Can't reproduce on Clang 3.6 and 3.7: https://godbolt.org/z/anPr7c9b8
