### ISSUE TITLE
-Wnullability-completeness broken for templated types

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24361]
|  |  |
| --- | --- |
| Bugzilla Link | [23987](https://llvm.org/bz23987) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
Consider the following code in a header:

_Pragma("clang assume_nonnull begin")
template <typename T>
inline void f(T x) {}
_Pragma("clang assume_nonnull end")

This gives the following bogus warning:

./nullability.h:3:15: warning: pointer is missing a nullability type
specifier (__nonnull or __nullable) [-Wnullability-completeness]

**Comment by AaronBallman** [comment]
I cannot reproduce this issue, but if you're still seeing it, please reopen with more information on how to reproduce.
