### ISSUE TITLE
Additional flags for brace decisions

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24363]
|  |  |
| --- | --- |
| Bugzilla Link | [23989](https://llvm.org/bz23989) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
A fairly common K&R brace style extension to C++ is

```
class Class {
    void foo() {
        return;
    }

    int bar();
}

int Class::bar()
{
    return 0;
}
```

Note that separate function definitions break before the opening brace (bar), while the inline definition (foo) does not.
This is currently not possible with clang-format. Please add additional granularity to the brace decisions.

Thanks.

**Comment by mydeveloperday** [comment]
This doesn't meet the criteria.. closing
