### ISSUE TITLE
Need to disable most libc library builtin optimizations when SEH is present

### ISSUE THREAD

**Issue by rnk** [llvm/llvm-project#24383]
|  |  |
| --- | --- |
| Bugzilla Link | [24009](https://llvm.org/bz24009) |
| Version | unspecified |
| OS | Windows NT |
| CC | @majnemer |

## Extended Description 
This program crashes instead of exiting zero:

```
#include <string.h>
bool try_memcpy(void *d, void *s, size_t n) {
  __try {
    memcpy(d, s, n);
  } __except (1) {
    return false;
  }
  return true;
}
int main() {
  return try_memcpy(nullptr, nullptr, 42);
}
```

This is because we codegen memcpy to llvm.memcpy instead of emitting the libcall. We don't support invoking most intrinsics, so for now we should probably behave as if -fno-builtin was set in functions that use SEH.

**Comment by Endilll** [comment]
Can you confirm that this issue is still not resolved?

**Comment by rnk** [comment]
Looks fixed: https://gcc.godbolt.org/z/3GjW4enPv
