### ISSUE TITLE
Phabricator sent me an email off-list when I'd already received the same message on-list

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#24421]
|  |  |
| --- | --- |
| Bugzilla Link | [24047](https://llvm.org/bz24047) |
| Version | unspecified |
| OS | All |

## Extended Description 
In D10946, Rafael replied with an LGTM via email:

    http://lists.cs.uiuc.edu/pipermail/llvm-commits/Week-of-Mon-20150706/285787.html

This message doesn't have any phab headers - it's to the list and phab, with a couple of people CC'd.

Then phabricator sent a nearly identical mail (The difference is it doesn't quote deadalnix) to me directly:

    From: Rafael Ávila de Espíndola <rafael.espindola@gmail.com>
    Subject: Re: [PATCH] D10946: Add capability to get and set the personalitty function from the C API
    To: deadalnix+llvmreview@gmail.com, chandlerc@gmail.com, mail@justinbogner.com, andrew.kaylor@intel.com, rnk@google.com
    Date: Mon, 6 Jul 2015 22:54:12 +0000 (54 minutes, 35 seconds ago)
    Reply-to: reviews+D10946+public+fea3378a898619f8@reviews.llvm.org
    X-Herald-Rules: none
    List-Id: reviews@reviews.llvm.org
    X-Phabricator-Sent-This-Message: Yes
    X-Phabricator-Mail-Tags: <differential-comment>
    
    Lgtm
    
    http://reviews.llvm.org/D10946

This one did not go to the list (which is good because the message was already sent), but straight to my inbox (because it doesn't have an llvm-commits list-id, obviously). The email obviously isn't helpful, and shouldn't be sent.

**Comment by JOE1994** [comment]
Closing this as we no longer use `phabricator`.
