### ISSUE TITLE
Crash/assert in reassociate

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24429]
|  |  |
| --- | --- |
| Bugzilla Link | [24055](https://llvm.org/bz24055) |
| Version | trunk |
| OS | All |
| Attachments | [The bugpointed test case](https://user-images.githubusercontent.com/60944935/143751680-a7088357-e519-4651-8b99-370554424cd3.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@joker-eph |

## Extended Description 

Assertion failed: (!Duplicates.count(Factor) && "Shouldn't have two constant factors, missed a canonicalize"), function OptimizeAdd, file ../lib/Transforms/Scalar/Reassociate.cpp, line 1645.

Replicate with bin/opt -S -reassociate < test.ll

The bugpointed test case looks ridiculous, but it's reduced from a real test.

**Comment by arsenm** [comment]
Last testcase works for me now
