### ISSUE TITLE
x86 assembly could be improved for expression x+9*y where x,y are int8_t

### ISSUE THREAD

**Issue by calixteman** [llvm/llvm-project#24426]
|  |  |
| --- | --- |
| Bugzilla Link | [24052](https://llvm.org/bz24052) |
| Version | 3.6 |
| OS | Linux |
| CC | @RKSimon,@rotateright,@sylvestre |

## Extended Description 
The following C code:
int8_t foo(int8_t x, int8_t y)
{
    return x + 9 * y;
}

generates this assembly with clang:
movb	$9, %cl
movb	%sil, %al
mulb	%cl
addb	%al, %dil
movsbl	%dil, %eax

and generates this one with gcc:
leal	(%rsi,%rsi,8), %esi
leal	(%rsi,%rdi), %eax

For information it is ok when args are int32_t.

**Comment by RKSimon** [comment]
This was fixed by D54803 / d31220e0de0d8924e7c1f54d08d4515cfabb1aeb which promotes i8 mul-by-constant to i32
```
  leal (%rsi,%rsi,8), %eax
  addb %dil, %al
```
