### ISSUE TITLE
Object/archive-update.test flakily fails on Windows

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#24480]
|  |  |
| --- | --- |
| Bugzilla Link | [24106](https://llvm.org/bz24106) |
| Version | trunk |
| OS | All |
| CC | @AaronBallman,@Bigcheese |

## Extended Description 
-- Testing: 23438 tests, 40 threads --
FAIL: LLVM :: Object/archive-update.test (18284 of 23438)
******************** TEST 'LLVM :: Object/archive-update.test' FAILED ********************
Script:
--
cd C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output
rm -f C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test.tmp.a
mkdir -p C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test.tmp.older
echo older > C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test.tmp.older/evenlen
touch -m -t 200001010000 C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test.tmp.older/evenlen |
| sleep 1.1
mkdir -p C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test.tmp.newer
echo newer > C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test.tmp.newer/evenlen
touch C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test.tmp.newer/evenlen
C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE r C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\O
bject\Output\archive-update.test.tmp.a C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test.tmp.n
ewer/evenlen
C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE p C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\O
bject\Output\archive-update.test.tmp.a | C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\FileCheck.EXE --check-prefix=NEWER C
:\src\chrome\src\third_party\llvm\test\Object\archive-update.test
C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE r C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\O
bject\Output\archive-update.test.tmp.a C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test.tmp.o
lder/evenlen
C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE p C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\O
bject\Output\archive-update.test.tmp.a | C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\FileCheck.EXE --check-prefix=OLDER C
:\src\chrome\src\third_party\llvm\test\Object\archive-update.test
C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE ru C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\
Object\Output\archive-update.test.tmp.a C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test.tmp.
newer/evenlen
C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE p C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\O
bject\Output\archive-update.test.tmp.a | C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\FileCheck.EXE --check-prefix=NEWER C
:\src\chrome\src\third_party\llvm\test\Object\archive-update.test
C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE ru C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\
Object\Output\archive-update.test.tmp.a C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test.tmp.
older/evenlen
C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE p C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\O
bject\Output\archive-update.test.tmp.a | C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\FileCheck.EXE --check-prefix=NEWER C
:\src\chrome\src\third_party\llvm\test\Object\archive-update.test
--
Exit Code: 1

Command Output (stdout):
--
Command 0: "rm" "-f" "C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test.tmp.a"
Command 0 Result: 0
Command 0 Output:

Command 0 Stderr:

Command 1: "mkdir" "-p" "C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test.tmp.older"
Command 1 Result: 0
Command 1 Output:

Command 1 Stderr:

Command 2: "echo" "older"
Command 2 Result: 0
Command 2 Output:
None

Command 2 Stderr:

Command 3: "touch" "-m" "-t" "200001010000" "C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test
.tmp.older/evenlen"
Command 3 Result: 0
Command 3 Output:

Command 3 Stderr:

Command 4: "mkdir" "-p" "C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test.tmp.newer"
Command 4 Result: 0
Command 4 Output:

Command 4 Stderr:

Command 5: "echo" "newer"
Command 5 Result: 0
Command 5 Output:
None

Command 5 Stderr:

Command 6: "touch" "C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive-update.test.tmp.newer/evenlen"
Command 6 Result: 0
Command 6 Output:

Command 6 Stderr:

Command 7: "C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE" "r" "C:\src\chrome\src\third_party\llvm-build\Releas
e+Asserts\test\Object\Output\archive-update.test.tmp.a" "C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archive
-update.test.tmp.newer/evenlen"
Command 7 Result: 0
Command 7 Output:

Command 7 Stderr:
C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE: creating C:\src\chrome\src\third_party\llvm-build\Release+Assert
s\test\Object\Output\archive-update.test.tmp.a

Command 8: "C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE" "p" "C:\src\chrome\src\third_party\llvm-build\Releas
e+Asserts\test\Object\Output\archive-update.test.tmp.a"
Command 8 Result: 0
Command 8 Output:

Command 8 Stderr:

Command 9: "C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\FileCheck.EXE" "--check-prefix=NEWER" "C:\src\chrome\src\third_pa
rty\llvm\test\Object\archive-update.test"
Command 9 Result: 0
Command 9 Output:

Command 9 Stderr:
Command 10: "C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE" "r" "C:\src\chrome\src\third_party\llvm-build\Relea
se+Asserts\test\Object\Output\archive-update.test.tmp.a" "C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archiv
e-update.test.tmp.older/evenlen"
Command 10 Result: 0
Command 10 Output:

Command 10 Stderr:

Command 11: "C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE" "p" "C:\src\chrome\src\third_party\llvm-build\Relea
se+Asserts\test\Object\Output\archive-update.test.tmp.a"
Command 11 Result: 0
Command 11 Output:

Command 11 Stderr:

Command 12: "C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\FileCheck.EXE" "--check-prefix=OLDER" "C:\src\chrome\src\third_p
arty\llvm\test\Object\archive-update.test"
Command 12 Result: 0
Command 12 Output:

Command 12 Stderr:

Command 13: "C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE" "ru" "C:\src\chrome\src\third_party\llvm-build\Rele
ase+Asserts\test\Object\Output\archive-update.test.tmp.a" "C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archi
ve-update.test.tmp.newer/evenlen"
Command 13 Result: 0
Command 13 Output:

Command 13 Stderr:

Command 14: "C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE" "p" "C:\src\chrome\src\third_party\llvm-build\Relea
se+Asserts\test\Object\Output\archive-update.test.tmp.a"
Command 14 Result: 0
Command 14 Output:

Command 14 Stderr:

Command 15: "C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\FileCheck.EXE" "--check-prefix=NEWER" "C:\src\chrome\src\third_p
arty\llvm\test\Object\archive-update.test"
Command 15 Result: 0
Command 15 Output:

Command 15 Stderr:

Command 16: "C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE" "ru" "C:\src\chrome\src\third_party\llvm-build\Rele
ase+Asserts\test\Object\Output\archive-update.test.tmp.a" "C:\src\chrome\src\third_party\llvm-build\Release+Asserts\test\Object\Output\archi
ve-update.test.tmp.older/evenlen"
Command 16 Result: 0
Command 16 Output:

Command 16 Stderr:

Command 17: "C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\llvm-ar.EXE" "p" "C:\src\chrome\src\third_party\llvm-build\Relea
se+Asserts\test\Object\Output\archive-update.test.tmp.a"
Command 17 Result: 0
Command 17 Output:

Command 17 Stderr:

Command 18: "C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin\FileCheck.EXE" "--check-prefix=NEWER" "C:\src\chrome\src\third_p
arty\llvm\test\Object\archive-update.test"
Command 18 Result: 1
Command 18 Output:

Command 18 Stderr:
C:\src\chrome\src\third_party\llvm\test\Object\archive-update.test:34:8: error: expected string not found in input
NEWER: newer
       ^
<stdin>:1:1: note: scanning from here
older
^

--

********************

Testing Time: 364.62s
********************
Failing Tests (1):
    LLVM :: Object/archive-update.test

  Expected Passes    : 22504
  Expected Failures  : 140
  Unsupported Tests  : 793
  Unexpected Failures: 1
lit.py: lit.cfg:195: note: using clang: 'C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin/clang.EXE'
lit.py: lit.cfg:333: note: Did not find clang-interpreter in C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin;C:/src/chrome/sr
c/third_party/llvm-build/Release+Asserts/./bin
lit.py: lit.cfg:279: note: Did not find llvm-go in C:/src/chrome/src/third_party/llvm-build/Release+Asserts/./bin
FAILED: cmd.exe /C "cd /D C:\src\chrome\src\third_party\llvm-build\Release+Asserts && C:\python_27_amd64\files\python.exe C:/src/chrome/src/
third_party/llvm/utils/lit/lit.py -sv --no-progress-bar --param clang_site_config=C:/src/chrome/src/third_party/llvm-build/Release+Asserts/t
ools/clang/test/lit.site.cfg --param lld_site_config=C:/src/chrome/src/third_party/llvm-build/Release+Asserts/tools/lld/test/lit.site.cfg --
param lld_unit_site_config=C:/src/chrome/src/third_party/llvm-build/Release+Asserts/tools/lld/test/Unit/lit.site.cfg --param llvm_site_confi
g=C:/src/chrome/src/third_party/llvm-build/Release+Asserts/test/lit.site.cfg --param llvm_unit_site_config=C:/src/chrome/src/third_party/llv
m-build/Release+Asserts/test/Unit/lit.site.cfg C:/src/chrome/src/third_party/llvm-build/Release+Asserts/projects/compiler-rt/test/ubsan/Stan
dalone-x86_64 C:/src/chrome/src/third_party/llvm-build/Release+Asserts/projects/compiler-rt/test/cfi C:/src/chrome/src/third_party/llvm-buil
d/Release+Asserts/tools/clang/test C:/src/chrome/src/third_party/llvm-build/Release+Asserts/tools/lld/test C:/src/chrome/src/third_party/llv
m-build/Release+Asserts/test"
ninja: build stopped: subcommand failed.
Failed.
Failed: ['C:\\python_27_amd64\\files\\python.exe', 'tools\\clang\\scripts\\update.py', '--bootstrap', '--force-local-build', '--run-tests',
'--no-stdin-hack']

**Comment by arsenm** [comment]
Old build issue
