### ISSUE TITLE
clang-cl should be compatible to `cl.exe` regarding `extern "C"` handling in namespaces

### ISSUE THREAD

**Issue by 24bb07d4-a064-4a64-856b-dc3103e7a3ac** [llvm/llvm-project#24569]
|  |  |
| --- | --- |
| Bugzilla Link | [24195](https://llvm.org/bz24195) |
| Version | trunk |
| OS | All |
| Blocks | llvm/llvm-project#14079  |
| CC | @XVilka,@DougGregor,@rnk |

## Extended Description 
Hello,

I try to use libclang to parse some source files. But the error is also visible in clang-cl (r242653 nightly build).

The error originates from boost interprocess headers which declare windows.h functions different than windows.h. The error got a work-around in later boost versions but unfortunately we are stuck with 1.50 for a while.

It boils down to Visual Studio Compiler accepting the following, but clang-cl does not:
```cpp
extern "C" void foo(int a);
 
namespace bar {
    extern "C" void foo(long b);
}
```
In the boost case the functions get pointers to different structures.

Could you modify clang to accept this oddity with enabled `ms-extensions` / `ms-compatibility` like `cl.exe` does?

Thanks,
Gregor

**Comment by AaronBallman** [comment]
Duplicate of #95681
