### ISSUE TITLE
compiler-rt cmake configure fails on 32-bit systems

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#24596]
|  |  |
| --- | --- |
| Bugzilla Link | [24222](https://llvm.org/bz24222) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Nikola reports failing to configure compiler-rt on 32-bit OpenSUSE and Fedora with CMake.

On Fedora, gcc targets i686 so the first stage (building compiler-rt and clang) of a bootstrap build succeeds.

But the second stage (building with the newly built clang) fails, because Clang does not define __i686__.

clang --version says it targets i686-pc-linux-gnu, but it doesn't define __i686__.

On my regular x86_64 workstation, it doesn't work either:

$ bin/clang -target i686-pc-linux-gnu -v
Prints "Target: i686-pc-linux-gnu" as expected, but:
$ bin/clang -target i686-pc-linux-gnu -dM -E -c /tmp/a.c | grep i.*86
Only prints __i386__, __i386 and i386.

Isn't Clang supposed to define __i686__ when targeting i686? Am I holding it wrong? Is compiler-rt checking the wrong thing?

On OpenSUSE, even Phase1 fails, because the system gcc is targeting i586 instead of i686:
gcc -v prints i586-suse-linux. It defines __i386__ and __i586__.
I suppose that's a different kind of bug, but it also seems related.

I have VMs for 32-bit OpenSUSE and Fedora set up. Let me know if I can help debugging.

**Comment by arsenm** [comment]
Old build issue
