### ISSUE TITLE
Mixing init-declarator for variables and functions in declaration with auto type-specifier

### ISSUE THREAD

**Issue by ebdd6ebc-1612-4e9b-aee1-f7d2b6361d5f** [llvm/llvm-project#24639]
|  |  |
| --- | --- |
| Bugzilla Link | [24265](https://llvm.org/bz24265) |
| Version | trunk |
| OS | All |

## Extended Description 
Consider the following program (`prog.cc`):
```cpp
  auto i = 0, f();
  int main() {}
```
Compile it with the following command line:
```
  clang++ prog.cc -std=c++14 -pedantic-errors
```
No error messages are given. I expect to get at least one error message since the program is ill-formed.

The program is ill-formed by [decl.spec.auto]/8:

  http://eel.is/c++draft/dcl.dcl#dcl.spec.auto-8

  > If the init-declarator-list contains more than one init-declarator, they shall all form declarations of variables.

I have tried this with clang HEAD 3.8.0 (trunk 243216) here:

  http://melpon.org/wandbox/permlink/9wMaOZMUED4X0xL8

**Comment by Endilll** [comment]
Fixed wandbox link: https://wandbox.org/permlink/9wMaOZMUED4X0xL8

**Comment by shafik** [comment]
clang rejects both: https://godbolt.org/z/eMG61crh6

```cpp
auto i = 0, f();
int main() {}
```

and: https://godbolt.org/z/sj37aWhfT

```cpp
auto f() -> int, i = 0;
```
