### ISSUE TITLE
NVPTX: Bad machine code: Reading virtual register without a def

### ISSUE THREAD

**Issue by tobiasgrosser** [llvm/llvm-project#24674]
|  |  |
| --- | --- |
| Bugzilla Link | [24300](https://llvm.org/bz24300) |
| Version | trunk |
| OS | Linux |
| Attachments | [Test case to reproduce the bug](https://user-images.githubusercontent.com/92601279/143751787-3fdb312d-6f00-4130-a45e-99a97b6fb87e.gz) |
| CC | @stoklund |

## Extended Description 

The attached test case fails when running it through llc (243247).

The following error is printed:

----------------------------------------------------------------------
# Machine code for function hoge: Post SSA

BB#0: derived from LLVM BB %bb
	%vreg2<def> = IMOV64i 0; Int64Regs:%vreg2
	CBranch %vreg3<undef>, <BB#6>; Int1Regs:%vreg3
	GOTO <BB#1>
    Successors according to CFG: BB#1(16) BB#6(16)

BB#6: 
    Predecessors according to CFG: BB#0
	%vreg9<def> = COPY %vreg2; Int64Regs:%vreg9,%vreg2
	GOTO <BB#5>
    Successors according to CFG: BB#5

BB#1: derived from LLVM BB %bb1
    Predecessors according to CFG: BB#0
	CBranch %vreg4<undef>, <BB#3>; Int1Regs:%vreg4
	GOTO <BB#2>
    Successors according to CFG: BB#3(16) BB#2(16)

BB#2: derived from LLVM BB %bb2
    Predecessors according to CFG: BB#1 BB#3
	CBranch %vreg7, <BB#4>; Int1Regs:%vreg7
    Successors according to CFG: BB#4(16) BB#7(16)

BB#7: 
    Predecessors according to CFG: BB#2
	%vreg9<def> = COPY %vreg2; Int64Regs:%vreg9,%vreg2
	GOTO <BB#5>
    Successors according to CFG: BB#5

BB#3: derived from LLVM BB %bb3
    Predecessors according to CFG: BB#1
	GOTO <BB#2>
    Successors according to CFG: BB#2(16)

BB#4: derived from LLVM BB %bb5
    Predecessors according to CFG: BB#2
	%vreg9<def> = COPY %vreg2; Int64Regs:%vreg9,%vreg2
    Successors according to CFG: BB#5

BB#5: derived from LLVM BB %bb7
    Predecessors according to CFG: BB#4 BB#5 BB#6 BB#7
	%vreg0<def> = COPY %vreg9<kill>; Int64Regs:%vreg0,%vreg9
	%vreg1<def> = ADDi64ri %vreg0, 1; Int64Regs:%vreg1,%vreg0
	%vreg9<def> = COPY %vreg1; Int64Regs:%vreg9,%vreg1
	GOTO <BB#5>
    Successors according to CFG: BB#5

# End machine code for function hoge.

*** Bad machine code: Reading virtual register without a def ***
- function:    hoge
- basic block: BB#2 bb2 (0x621000005648)
- instruction: CBranch- operand 0:   %vreg7
LLVM ERROR: Found 1 machine code errors.
----------------------------------------------------------------------

The test case has been found by bugpoint while reducing another issue. It would be great if we could _not_ crash, as this would allow allow me to reduce the original bug.

**Comment by arsenm** [comment]
Can't reproduce
