### ISSUE TITLE
LSR miscompiles code after r243348

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24721]
|  |  |
| --- | --- |
| Bugzilla Link | [24347](https://llvm.org/bz24347) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@pcc |

## Extended Description 
To reproduce:

$ cat example.c 
#include <stdint.h>
#include <stdio.h>

struct S {
  int a;
  int b;
};

void foo(struct S* s, int last_index, uint8_t *arr)
{
    int x, i, j, prev;
    if (s->a && !s->b) {
      i = 1;
    } else {
      i = 0;
    }

    prev = i - 1;
    for (; i <= last_index; i++) {
        j = arr[i];
        fprintf(stderr, "### j = %d\n", j);
        x = i - prev - 1;
        prev = i;
        fprintf(stderr, "### %d %d\n", x, prev);
    }
}

int main() {
  struct S s = { 0, 0 };
  uint8_t arr[] = {0, 1, 2, 3};
  foo(&s, 3, arr);
  return 0;
}

$ ./bin/clang -O0 example.c && ./a.out
### 0 3

$ ./bin/clang -O1 example.c && ./a.out
Segmentation fault (core dumped)

Looks like the problem is that loop counter (which can be negative after the transformation) is stored in 32-bit register, and is incorrectly zero-extended instead of being sign-extended:

$ objdump -d a.out
0000000000400580 <foo>:
<...>
  400589:       83 3f 00                cmpl   $0x0,(%rdi)
  40058c:       74 0b                   je     400599 <foo+0x19>
  40058e:       bb 01 00 00 00          mov    $0x1,%ebx
  400593:       83 7f 04 00             cmpl   $0x0,0x4(%rdi)
  400597:       74 02                   je     40059b <foo+0x1b>
  400599:       31 db                   xor    %ebx,%ebx        <--- %ebx is a counter, can become zero here.
<...>
  4005a4:       ff cb                   dec    %ebx                    <--- %ebx can be 0xffffffff
  4005a6:       66 2e 0f 1f 84 00 00    nopw   %cs:0x0(%rax,%rax,1)
  4005ad:       00 00 00 
  4005b0:       89 d8                   mov    %ebx,%eax
  4005b2:       41 0f b6 54 06 01       movzbl 0x1(%r14,%rax,1),%edx  <---- here we add 0x100000000 instead of 0x0

**Comment by arsenm** [comment]
Regression point was reverted
