### ISSUE TITLE
clang release notes aren't linked from the download page

### ISSUE THREAD

**Issue by LegalizeAdulthood** [llvm/llvm-project#24819]
|  |  |
| --- | --- |
| Bugzilla Link | [24445](https://llvm.org/bz24445) |
| Version | unspecified |
| OS | Windows NT |
| CC | @zmodem,@tstellar |

## Extended Description 
The last release that had release notes linked from the download page was 3.4, but there are release notes for 3.5, 3.6, 3.7, etc.

**Comment by LegalizeAdulthood** [comment]
Given that this is now a historical release (7 years ago), I'm going to close this issue.

**Comment by xgupta** [comment]
> Given that this is now a historical release (7 years ago), I'm going to close this issue.

Yay!
