### ISSUE TITLE
sphinx docs fail to build with: "undefined label: langext-address_sanitizer"

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#24812]
|  |  |
| --- | --- |
| Bugzilla Link | [24438](https://llvm.org/bz24438) |
| Version | unspecified |
| OS | Linux |
| CC | @AaronBallman,@delcypher,@zygoloid,@silvasean |

## Extended Description 
The problem seems to be that docs/AddressSanitizer.rst (and some other sanitizer docs) refer to labels that are expected to be found in docs/AttributeReference.rst.

But that file is empty, and says it's supposed to be regenerated manually with "clang-tblgen -gen-attr-docs".

It would be much nicer if that would all happen automatically as part of building the sphinx target.

As it is, the sphinx target fails to build, which throws me off when building the docs for a release.

**Comment by arsenm** [comment]
Old build issue
