### ISSUE TITLE
Valid Code with "char * restrict _Atomic" Is Rejected

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#24825]
|  |  |
| --- | --- |
| Bugzilla Link | [24451](https://llvm.org/bz24451) |
| Version | trunk |
| OS | Linux |
| CC | @chengniansun,@zygoloid |

## Extended Description 
I think the following code is valid, but clang rejects it. Please kindly advise if I am wrong. Thanks. 

$: cat t.c
#include <stdint.h>
#include <stdatomic.h>
char (*restrict _Atomic a) = "hello";

$: clang-trunk -c t.c
t.c:3:7: error: restrict requires a pointer or reference
('_Atomic(char (*))' is invalid)
char (*restrict _Atomic a) = "hello";
      ^
1 error generated.
$: gcc-trunk -c t.c
$:

**Comment by AaronBallman** [comment]
Clang rejects, GCC and ICC accept (even in pedantic mode). The wording in C2x makes the Clang behavior correct (I can find no DRs filed with the C committee that speak to this):

6.7.3p2: Types other than pointer types whose referenced type is an object type and (possibly multidimensional) array types with such pointer types as element type shall not be restrict-qualified.

6.2.5 still leaves atomic types distinct from their underlying type, so an atomic type is not a pointer type.

6.7.2.4p3: The type name in an atomic type specifier shall not refer to an array type, a function type, an atomic type, or a qualified type.

Closing the issue as not a bug, however, if there is a situation where this functionality is needed as an extension, please file a new issue with details on what the use case is.
