### ISSUE TITLE
[LegacyPassManager] PM does not verifies passes preserved by setPreservesAll()

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24830]
|  |  |
| --- | --- |
| Bugzilla Link | [24456](https://llvm.org/bz24456) |
| Version | trunk |
| OS | Linux |
| Attachments | [A unit test that uses setPreservesAll() and checks whether the analysis verified.](https://user-images.githubusercontent.com/60944935/143751849-6a2bc5e9-5644-41ec-b5c9-991c7b0d889d.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

The LegacyPassManager, PMDataManager::verifyPreservedAnalysis() iterates over PreservedSet and calls verifyAnalysis() for each analysis.

In other hand, some passes use setPreservesAll() which setups a flag, but adds nothing to the PreservedSet.

As a result only passes, added by addPreserved<T>(), will be verified.

A unit test reproducer is in attachment.

**Comment by arsenm** [comment]
Old pass manager
