### ISSUE TITLE
3.6.2: 35 AAarch64 tests are failing

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#24846]
|  |  |
| --- | --- |
| Bugzilla Link | [24472](https://llvm.org/bz24472) |
| Version | 3.6 |
| OS | Linux |
| CC | @DougGregor,@rengolin |

## Extended Description 
Probably caused by the recent changes of libstdc++ in Debian, a bunch of AAarch64 are failing under Debian x86_64.

They all looks the same

                     -- Testing: 12318 tests, 5 threads --                     
FAIL: LLVM :: CodeGen/AArch64/aarch64_f16_be.ll (630 of 12318)
******************** TEST 'LLVM :: CodeGen/AArch64/aarch64_f16_be.ll' FAILED ********************
Script:
--
/root/llvm-toolchain-3.6-3.6.2/build-llvm/Release/bin/llc -mtriple=aarch64-linux-gnuabi -O0 < /root/llvm-toolchain-3.6-3.6.2/test/CodeGen/AArch64/aarch64_f16_be.ll | /root/llvm-toolchain-3.6-3.6.2/build-llvm/Release/bin/FileCheck /root/llvm-toolchain-3.6-3.6.2/test/CodeGen/AArch64/aarch64_f16_be.ll
/root/llvm-toolchain-3.6-3.6.2/build-llvm/Release/bin/llc -mtriple=aarch64_be-linux-gnuabi -O0 < /root/llvm-toolchain-3.6-3.6.2/test/CodeGen/AArch64/aarch64_f16_be.ll | /root/llvm-toolchain-3.6-3.6.2/build-llvm/Release/bin/FileCheck /root/llvm-toolchain-3.6-3.6.2/test/CodeGen/AArch64/aarch64_f16_be.ll --check-prefix=CHECK-BE
--
Exit Code: 2

Command Output (stderr):
--
FileCheck error: '-' is empty.

--

[...]

********************
Failing Tests (35):
    LLVM :: CodeGen/AArch64/aarch64_f16_be.ll
    LLVM :: CodeGen/AArch64/and-mask-removal.ll
    LLVM :: CodeGen/AArch64/arm64-2012-06-06-FPToUI.ll
    LLVM :: CodeGen/AArch64/arm64-abi.ll
    LLVM :: CodeGen/AArch64/arm64-abi_align.ll
    LLVM :: CodeGen/AArch64/arm64-anyregcc-crash.ll
    LLVM :: CodeGen/AArch64/arm64-anyregcc.ll
    LLVM :: CodeGen/AArch64/arm64-big-endian-bitconverts.ll
    LLVM :: CodeGen/AArch64/arm64-big-endian-vector-caller.ll
    LLVM :: CodeGen/AArch64/arm64-elf-globals.ll
    LLVM :: CodeGen/AArch64/arm64-fast-isel-call.ll
    LLVM :: CodeGen/AArch64/arm64-fast-isel-fcmp.ll
    LLVM :: CodeGen/AArch64/arm64-fast-isel-indirectbr.ll
    LLVM :: CodeGen/AArch64/arm64-fast-isel-noconvert.ll
    LLVM :: CodeGen/AArch64/arm64-fastisel-gep-promote-before-add.ll
    LLVM :: CodeGen/AArch64/arm64-fp128.ll
    LLVM :: CodeGen/AArch64/arm64-illegal-float-ops.ll
    LLVM :: CodeGen/AArch64/arm64-neon-mul-div.ll
    LLVM :: CodeGen/AArch64/arm64-neon-vector-list-spill.ll
    LLVM :: CodeGen/AArch64/arm64-platform-reg.ll
    LLVM :: CodeGen/AArch64/arm64-spill.ll
    LLVM :: CodeGen/AArch64/arm64-stackmap.ll
    LLVM :: CodeGen/AArch64/arm64-stacksave.ll
    LLVM :: CodeGen/AArch64/arm64-vcvt_f.ll
    LLVM :: CodeGen/AArch64/arm64-vfloatintrinsics.ll
    LLVM :: CodeGen/AArch64/fast-isel-folding.ll
    LLVM :: CodeGen/AArch64/illegal-float-ops.ll
    LLVM :: CodeGen/AArch64/ldst-opt.ll
    LLVM :: CodeGen/AArch64/machine-copy-prop.ll
    LLVM :: CodeGen/AArch64/neon-fpround_f128.ll
    LLVM :: CodeGen/AArch64/ragreedy-csr.ll
    LLVM :: CodeGen/AArch64/regress-tail-livereg.ll
    LLVM :: CodeGen/AArch64/sincos-expansion.ll
    LLVM :: CodeGen/AArch64/sincospow-vector-expansion.ll
    LLVM :: DebugInfo/AArch64/cfi-eof-prologue.ll

Executing a command by hands return:
# /root/llvm-toolchain-3.6-3.6.2/build-llvm/Release/bin/llc -mtriple=aarch64-linux-gnu -mcpu=cortex-a57 -verify-machineinstrs < /root/llvm-toolchain-3.6-3.6.2/test/CodeGen/AArch64/machine-copy-prop.ll | /root/llvm-toolchain-3.6-3.6.2/build-llvm/Release/bin/FileCheck /root/llvm-toolchain-3.6-3.6.2/test/CodeGen/AArch64/machine-copy-prop.ll
0  libLLVM-3.6.so.1 0x00007f5aa7c7bb02 llvm::sys::PrintStackTrace(_IO_FILE*) + 34
1  libLLVM-3.6.so.1 0x00007f5aa7c7a309
2  libpthread.so.0  0x00007f5aa695f8d0
3  libLLVM-3.6.so.1 0x00007f5aa7a09a17 llvm::MachineInstr::addMemOperand(llvm::MachineFunction&, llvm::MachineMemOperand*) + 23
4  libLLVM-3.6.so.1 0x00007f5aa818f08a llvm::AArch64InstrInfo::storeRegToStackSlot(llvm::MachineBasicBlock&, llvm::MachineBasicBlock::bundle_iterator<llvm::MachineInstr, llvm::ilist_iterator<llvm::MachineInstr> >, unsigned int, bool, int, llvm::TargetRegisterClass const*, llvm::TargetRegisterInfo const*) const + 762
5  libLLVM-3.6.so.1 0x00007f5aa798ea98
6  libLLVM-3.6.so.1 0x00007f5aa79929a0
7  libLLVM-3.6.so.1 0x00007f5aa7a820a3
8  libLLVM-3.6.so.1 0x00007f5aa7a85c78
9  libLLVM-3.6.so.1 0x00007f5aa7a74856 llvm::RegAllocBase::allocatePhysRegs() + 182
10 libLLVM-3.6.so.1 0x00007f5aa7a867a9
11 libLLVM-3.6.so.1 0x00007f5aa73a8b87 llvm::FPPassManager::runOnFunction(llvm::Function&) + 471
12 libLLVM-3.6.so.1 0x00007f5aa73a8ddb llvm::FPPassManager::runOnModule(llvm::Module&) + 43
13 libLLVM-3.6.so.1 0x00007f5aa73a8814 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 756
14 llc              0x00000000004134d5
15 llc              0x000000000040d610 main + 368
16 libc.so.6        0x00007f5aa54c4b45 __libc_start_main + 245
17 llc              0x000000000040d669
Stack dump:
0.	Program arguments: /root/llvm-toolchain-3.6-3.6.2/build-llvm/Release/bin/llc -mtriple=aarch64-linux-gnu -mcpu=cortex-a57 -verify-machineinstrs 
1.	Running pass 'Function Pass Manager' on module '<stdin>'.
2.	Running pass 'Greedy Register Allocator' on function '@foo'
FileCheck error: '-' is empty.

**Comment by arsenm** [comment]
Old build issue
