### ISSUE TITLE
clang-tidy's misc-use-override checker should not touch template classes which inherit from their template argument

### ISSUE THREAD

**Issue by ehsan** [llvm/llvm-project#24870]
|  |  |
| --- | --- |
| Bugzilla Link | [24496](https://llvm.org/bz24496) |
| Version | unspecified |
| OS | All |

## Extended Description 
See the following program, for example:

struct B {
  virtual void f() = 0;
};
struct OB {
  virtual void f() = 0;
  virtual ~OB();
};

template<class B>
struct D:B {
  void f();
  ~D();
};

D<B> d;
D<OB> od;

Right now clang-tidy rewrites both functions in D as override, which makes the program invalid, since ~B is not virtual.

I think in this case, it's best to leave the D template alone, since rewriting any of its methods can cause similar bugs.  I'm trying to write a patch for it, but I'm stuck on figuring out how to detect that a base class is a template argument.  Here is what I have so far:

diff --git a/clang-tidy/misc/UseOverrideCheck.cpp b/clang-tidy/misc/UseOverrideCheck.cpp
index ec71d1b..c1927a2 100644
--- a/clang-tidy/misc/UseOverrideCheck.cpp
+++ b/clang-tidy/misc/UseOverrideCheck.cpp
@@ -61,12 +61,27 @@ void UseOverrideCheck::check(const MatchFinder::MatchResult &Result) {
   if (!Result.Context->getLangOpts().CPlusPlus11)
     return;
 
-  const FunctionDecl *Method = Result.Nodes.getStmtAs<FunctionDecl>("method");
+  const CXXMethodDecl *Method = Result.Nodes.getStmtAs<CXXMethodDecl>("method");
   const SourceManager &Sources = *Result.SourceManager;
-
   assert(Method != nullptr);
+
+  // If this is a template inheriting from a template argument, be conservative
+  // and do not change the method.
+  const CXXRecordDecl *Record = Method->getParent();
+  const ClassTemplateSpecializationDecl *Spec = dyn_cast<ClassTemplateSpecializationDecl>(Record);
+  if (Spec) {
+    const CXXRecordDecl *Template = Spec->getSpecializedTemplate()->getTemplatedDecl();
+    for (auto Base : Template->bases()) {
+      // This incorrectly filters things such as:
+      //   template<class T> struct D : B<T> {};
+      if (Base.getType()->isInstantiationDependentType()) {
+        return;
+      }
+    }
+  }
+
   if (Method->getInstantiatedFromMemberFunction() != nullptr)
-    Method = Method->getInstantiatedFromMemberFunction();
+    Method = dyn_cast<CXXMethodDecl>(Method->getInstantiatedFromMemberFunction());
 
   if (Method->isImplicit() || Method->getLocation().isMacroID() ||
       Method->isOutOfLine())

Any pointers appreciated!

**Comment by carlosgalvezp** [comment]
Warning in the OP no longer reproducible on trunk. Discussion seems also settled on not proceeding with any changes.
