### ISSUE TITLE
Test Makefiles don't know how to build static libraries on Windows

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24901]
|  |  |
| --- | --- |
| Bugzilla Link | [24527](https://llvm.org/bz24527) |
| Version | unspecified |
| OS | Windows NT |
| Blocks | llvm/llvm-project#22140  |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Makefile.rules needs to be able to build static libraries on Windows for certain test scenarios.  It knows how to do this on non-Windows platforms by using the 'ar' command, but it needs to be taught on Windows how to make a .lib file.

This will allow re-enabling TestBSDArchives.py

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
