### ISSUE TITLE
basic_filebuf non-standard constructor/open functions for taking an open FILE stream

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24941]
|  |  |
| --- | --- |
| Bugzilla Link | [24567](https://llvm.org/bz24567) |
| Version | unspecified |
| OS | Linux |
| Attachments | [patch that adds FILE* constructor/open function to basic_filebuf](https://user-images.githubusercontent.com/60944935/143751900-26259ef0-9236-41c0-b991-f85dbbb10366.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 

Currently it is not possible to construct a C++ stream for an already open file.

Some other C++ libraries offer non-standard extensions like 

__gnu_cxx::stdio_filebuf from ext/stdio_filebuf.h

in the libstdc++.

Given that the current implementation of basic_filebuf uses a FILE stream internally it is easily possibly to add an alternative constructor and open function that takes an already open FILE stream.

Attached is a patch containing a straight forward approach to add this functionality.

**Comment by philnik777** [comment]
Closing this, since we generally try to not add any extensions, and it doesn't seem that there is a lot of interest in this extension.
