### ISSUE TITLE
Assertion failed: (isa<Argument>(Val) && "Unknown live-in to the entry block"), function solveBlockValueNonLocal

### ISSUE THREAD

**Issue by DimitryAndric** [llvm/llvm-project#24957]
|  |  |
| --- | --- |
| Bugzilla Link | [24583](https://llvm.org/bz24583) |
| Version | trunk |
| OS | All |
| Attachments | [Test case for solveBlockValueNonLocal assertion](https://user-images.githubusercontent.com/9060368/143751904-f4c7abeb-843e-4ebf-91f0-74db12cb31f2.gz) |
| CC | @emaste |

## Extended Description 
This assertion came up during a FreeBSD ports exp-run with a recent clang trunk snapshot, here:

http://package18.nyi.freebsd.org/data/headi386#201377 -default/2015-08-20_15h42m20s/logs/errors/stepmania-devel-5.0.a3_4,1.log

I will attach a reduced testcase.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 4: https://godbolt.org/z/b3GM3E4zj
