### ISSUE TITLE
The clang-format "SpaceAfterCStyleCast" option is used incorrectly

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24968]
|  |  |
| --- | --- |
| Bugzilla Link | [24594](https://llvm.org/bz24594) |
| Version | 3.7 |
| OS | MacOS X |
| Attachments | [Example file that can be used to reproduce the bug](https://user-images.githubusercontent.com/60944935/143751908-f4d05f07-d3f1-4fda-ba5b-19182fe19739.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

I have the SpaceAfterCStyleCast option set to false in my .clang-format file, but when I run clang-format, it inserts spaces in my file.  I have attached a sample file below.  I ran clang with: `clang-format -style=file -i file.cpp`.

My .clang-format looks like this:

---
BasedOnStyle: Google
DerivePointerAlignment: false
IndentWidth: 4
TabWidth: 4
UseTab: Never
AccessModifierOffset: -4
SpaceAfterCStyleCast: false
...

**Comment by mydeveloperday** [comment]
```
typedef struct {
    int a;
    int* b;
} MyStruct;

MyStruct arr[] = {{1, (int*)&x}};
```

**Comment by mydeveloperday** [comment]
As of clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 7890afddecff01119f4d5e8825b43dd2c8361648) this seems to be fixed so I'm closing this issue
