### ISSUE TITLE
Rejects valid code: va_start in lambda function

### ISSUE THREAD

**Issue by bisqwit** [llvm/llvm-project#24985]
|  |  |
| --- | --- |
| Bugzilla Link | [24611](https://llvm.org/bz24611) |
| Version | 3.6 |
| OS | All |
| CC | @DougGregor |

## Extended Description 
For this sample code:

    #include <cstdarg>
    #include <cstdio>

    int main()
    {
        auto test = [&](const char* fmt, ...)
        {
            va_list ap;
            va_start(ap,fmt);
            char Buf[1024];
            std::vsprintf(Buf, fmt, ap);
            va_end(ap);
            std::puts(Buf);
        };
    
        test("Test %d", 1);
    }

Clang++-3.6 incorrectly gives the following error message:

    tmp.cc:9:9: error: 'va_start' used in function with fixed args
            va_start(ap,fmt);

**Comment by wheatman** [comment]
reproduces in 3.6
seems to be fixed in 5.0.0
https://godbolt.org/z/5afr8Gon9
