### ISSUE TITLE
Error on redefinition of builtin functions.

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#24997]
|  |  |
| --- | --- |
| Bugzilla Link | [24623](https://llvm.org/bz24623) |
| Version | trunk |
| OS | Windows NT |
| CC | @chengniansun |

## Extended Description 
I declare a variable with the name "rint", which accidentally is a builtin function. Then clang rejects the code, although I do not include the header file <math.h>. 

Even though this behavior was deliberate, the message is still confusing, "tmp.c:1:5: note: previous definition is here", as the first line is not the the location of the previous definition. 

$ clang-trunk -O0 -c tmp.c

tmp.c:1:5: error: redefinition of 'rint' as different kind of symbol

int rint; 

    ^

tmp.c:1:5: note: previous definition is here

1 error generated.

$ 

$ gcc-trunk -O0 -c tmp.c

tmp.c:1:5: warning: built-in function ‘rint’ declared as non-function

 int rint; 

     ^

$ 

$ cat tmp.c

int rint; 

$

**Comment by AaronBallman** [comment]
Closing as duplicate of #15523
