### ISSUE TITLE
llvm-as: Assertion `isExtended() && "Type is not extended!"' failed.

### ISSUE THREAD

**Issue by kcc** [llvm/llvm-project#25031]
|  |  |
| --- | --- |
| Bugzilla Link | [24657](https://llvm.org/bz24657) |
| Version | unspecified |
| OS | Linux |
| Blocks | llvm/llvm-project#25013  |

## Extended Description 
Found with libFuzzer.

echo "declare <2 x i32> @&#8203;llvm.ctlz.v2i32(<2 x i3*>)" | llvm-as - 

llvm-as: lib/IR/ValueTypes.cpp:184: llvm::Type *llvm::EVT::getTypeForEVT(llvm::LLVMContext &) const: Assertion `isExtended() && "Type is not extended!"' failed.

**Comment by arsenm** [comment]
With the raw reproducer instructions, works fine. If I try to refine this to a codegen context where the EVT should matter, I still can't break this. The verifier correctly rejects the incorrect intrinsic signature
