### ISSUE TITLE
[3.7] MCJITTest.add_function unit test fails in mingw-w64

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25095]
|  |  |
| --- | --- |
| Bugzilla Link | [24721](https://llvm.org/bz24721) |
| Version | 3.7 |
| OS | Windows XP |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Running the MCJITTests unit test fails with:
[ RUN      ] MCJITTest.add_function
0x0123D7A4 (0x0028F901 0x2152D440 0x00000001 0x00000B68), Ordinal77095() + 0xC bytes(s)
0x011C7592 (0x00340000 0x0028FA04 0x0135A1D8 0x21554068), _ZNK4llvm22BlockFrequencyInfoImplINS_10BasicBlockEE8rpot_endEv() + 0x16 bytes(s)
0x008840B2 (0x00340000 0x21554D28 0x0028FA38 0x011D709C), _ZNSt6vectorIN4llvm4yaml18MachineStackObjectESaIS2_EEixEj() + 0x45 bytes(s)
0x00884126 (0x00340000 0x00340000 0x00000000 0x00000030), _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_yESt10_Select1stIS8_ESt4lessIS5_ESaIS8_EE8_S_valueEPKSt18_Rb_tree_node_base() + 0x20 bytes(s)
0x0088A9B5 (0x2152D440 0x2152D450 0x2152D401 0x2152D3C4), _ZN4llvm14RuntimeDyldELF16registerEHFramesEv() + 0xD7 bytes(s)
0x008881CC (0x2152D398 0x0028FBBC 0x00000001 0x2152D398), _ZN4llvm11RuntimeDyld16registerEHFramesEv() + 0x2C bytes(s)
0x00875D46 (0x0028FBBC 0x00000001 0x0028FB1F 0x2151E1B0), _ZSt7forwardISt7_Mem_fnIMN4llvm15ScalarEvolutionEFbPKNS1_4SCEVEEEEOT_RNSt16remove_referenceIS9_E4typeE() + 0x4C bytes(s)
0x00876658 (0x0028FBBC 0x014BDE2B 0x00000003 0x0028FBB8), _ZSt7forwardISt5tupleIJRKPN4llvm8ArgumentEEEEOT_RNSt16remove_referenceIS7_E4typeE() + 0x56 bytes(s)
0x0040DEEC (0x0000013C 0x21518918 0x0028FCB8 0x0112388E), _ZN35MCJITCAPITest_addGlobalMapping_Test8TestBodyEv() + 0xA652 bytes(s)
0x01123A89 (0x2151E080 0x00000011 0x00000000 0x014BEF93), _ZN7testing8internal38HandleSehExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc() + 0x39 bytes(s)
0x0112388E (0x2151E080 0x00000011 0x00000000 0x014BEF93), _ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc() + 0x36 bytes(s)
0x00414D67 (0x0039C850 0x00000009 0x00000000 0x014BF0F8), _ZN7testing4Test3RunEv() + 0xB9 bytes(s)
0x004152C0 (0x00000001 0x0111F0A0 0x00000000 0x014BF135), _ZN7testing8TestInfo3RunEv() + 0xEA bytes(s)
0x00415755 (0x00000000 0x00418BA4 0x00000000 0x21518968), _ZN7testing8TestCase3RunEv() + 0xED bytes(s)
0x00418E5B (0x00000001 0x21518918 0x0028FE58 0x011237AE), _ZN7testing8internal12UnitTestImpl11RunAllTestsEv() + 0x287 bytes(s)
0x01123A11 (0x21518918 0x00418BD4 0x00000000 0x014BF6B8), _ZN7testing8internal38HandleSehExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc() + 0x39 bytes(s)
0x011237AE (0x21518918 0x00418BD4 0x00000000 0x014BF6B8), _ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc() + 0x36 bytes(s)
0x00418325 (0x00000003 0x00391818 0x00000000 0x00DF99E8), _ZN7testing8UnitTest3RunEv() + 0x59 bytes(s)
0x0041FAB0 (0x00392630 0x0000000F 0x00000001 0x004013E2), Ordinal111115() + 0x74 bytes(s)
0x004013E2 (0x7EFDE000 0x0028FFD4 0x775C92E2 0x7EFDE000)
0x7566337A (0x7EFDE000 0x7FC63F85 0x00000000 0x00000000), BaseThreadInitThunk() + 0x12 bytes(s)
0x775C92E2 (0x004014E0 0x7EFDE000 0x00000000 0x00000000), RtlInitializeExceptionChain() + 0x63 bytes(s)
0x775C92B5 (0x004014E0 0x7EFDE000 0x00000000 0x78746341), RtlInitializeExceptionChain() + 0x36 bytes(s)

Clang/LLVM was compiled with:
../llvm-3.7.0.src/configure --prefix=/mingw64-64 --host=x86_64-w64-mingw32 --disable-shared --disable-optimized --enable-assertions --enable-debug-runtime --enable-debug-symbols --enable-keep-symbols --enable-targets="x86 x86_64 cpp" --disable-docs "--with-gcc-toolchain=`which x86_64-w64-mingw32-gcc | xargs dirname`" CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ AR=x86_64-w64-mingw32-gcc-ar LD=x86_64-w64-mingw32-ld "CPPFLAGS=-std=c++14" "CFLAGS=-m32" "CXXFLAGS=-m32"

**Comment by arsenm** [comment]
Old build issue using old old autotools build
