### ISSUE TITLE
[3.7] runToolOnCode.FindsNoTopLevelDeclOnEmptyCode function unit test fails in mingw-w64

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25101]
|  |  |
| --- | --- |
| Bugzilla Link | [24727](https://llvm.org/bz24727) |
| Version | 3.7 |
| OS | Windows XP |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Running the ToolingTests unit test fails with:
Program received signal SIGSEGV, Segmentation fault.
0x0000000000f59fc1 in llvm::sys::path::append (path=..., a=..., b=..., c=..., d=...)
    at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/lib/Support/Path.cpp:446
446	                                         const Twine &d) {
#&#8203;0  0x0000000000f59fc1 in llvm::sys::path::append (path=..., a=..., b=..., c=..., d=...)
    at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/lib/Support/Path.cpp:446
#&#8203;1  0x000000000064d995 in clang::driver::Driver::Driver (this=0x2fd6e0, ClangExecutable=..., DefaultTargetTriple=..., Diags=...)
    at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/tools/clang/lib/Driver/Driver.cpp:71
#&#8203;2  0x00000000004d722c in newDriver (BinaryName=0x2fd2a0 "clang-tool", Diagnostics=0x22ef40)
    at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/tools/clang/lib/Tooling/Tooling.cpp:58
#&#8203;3  clang::tooling::ToolInvocation::run (this=this@entry=0x22f580)
    at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/tools/clang/lib/Tooling/Tooling.cpp:215
#&#8203;4  0x00000000004d7cf7 in clang::tooling::runToolOnCodeWithArgs (ToolAction=<optimized out>, Code=..., Args=..., FileName=..., PCHContainerOps=..., 
    VirtualMappedFiles=...) at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/tools/clang/lib/Tooling/Tooling.cpp:147
#&#8203;5  0x00000000004d7e69 in clang::tooling::runToolOnCode (ToolAction=ToolAction@entry=0x2fc750, Code=..., FileName=..., PCHContainerOps=...)
    at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/tools/clang/lib/Tooling/Tooling.cpp:111
#&#8203;6  0x00000000004c7df5 in clang::tooling::runToolOnCode_FindsNoTopLevelDeclOnEmptyCode_Test::TestBody (this=<optimized out>)
    at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/tools/clang/unittests/Tooling/ToolingTest.cpp:64
#&#8203;7  0x0000000000ecc63d in testing::Test::Run (this=this@entry=0x2fc000)
    at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/utils/unittest/googletest/src/gtest.cc:2162
#&#8203;8  0x0000000000ed3605 in Run (this=<optimized out>)
    at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/utils/unittest/googletest/src/gtest.cc:2153
#&#8203;9  testing::TestInfo::Run (this=0x31285be0) at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/utils/unittest/googletest/src/gtest.cc:2309
#&#8203;10 0x0000000000ed37d5 in Run (this=<optimized out>)
    at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/utils/unittest/googletest/src/gtest.cc:2284
#&#8203;11 testing::TestCase::Run (this=0x2f24b0) at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/utils/unittest/googletest/src/gtest.cc:2416
#&#8203;12 0x0000000000ed7c1e in Run (this=<optimized out>)
    at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/utils/unittest/googletest/src/gtest.cc:4245
#&#8203;13 testing::internal::UnitTestImpl::RunAllTests (this=0x31285cc0)
    at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/utils/unittest/googletest/src/gtest.cc:4207
#&#8203;14 0x0000000000ed7ea3 in HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=<synthetic pointer>, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0xed78f0 <testing::internal::UnitTestImpl::RunAllTests()>, object=0x31285cc0) at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/utils/unittest/googletest/src/gtest.cc:2145
#&#8203;15 testing::UnitTest::Run (this=<optimized out>) at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/utils/unittest/googletest/src/gtest.cc:3841
#&#8203;16 0x0000000001266ba9 in main (argc=1, argv=0x31282480)
    at e:/Downloads/Applications/llvm/3.7/llvm-3.7.0.src/utils/unittest/UnitTestMain/TestMain.cpp:47

Clang/LLVM was compiled as 64-bit build with:
../llvm-3.7.0.src/configure --prefix=/mingw64-64 --host=x86_64-w64-mingw32 --disable-shared --enable-assertions --enable-debug-symbols --enable-keep-symbols --enable-targets="x86 x86_64 cpp" --disable-docs "--with-gcc-toolchain=`which x86_64-w64-mingw32-gcc | xargs dirname`" CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ AR=x86_64-w64-mingw32-gcc-ar LD=x86_64-w64-mingw32-ld "CPPFLAGS=-std=c++14"

**Comment by Endilll** [comment]
Old test failure is unlikely to be relevant today.
