### ISSUE TITLE
Clang segfaults when linking xhyve

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25106]
|  |  |
| --- | --- |
| Bugzilla Link | [24732](https://llvm.org/bz24732) |
| Version | 3.6 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I am running OS X 10.10 Yosemite.
I have a version of llvm I installed with homebrew with a few extra options:
$ brew install llvm --with-clang --with-asan

Here is some information about my clang version:
$ clang --version
clang version 3.6.2 (tags/RELEASE_362/final)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

When I attempt to compile a fresh version of xhyve[1], the bsd hypervisor port built on Hypervisor.framework, clang segfaults during the linking phase.

Here is what make outputs, but it's basically a lie.
$ make clean
$ make
cc src/vmm/x86.c
cc src/vmm/vmm.c
cc src/vmm/vmm_host.c
cc src/vmm/vmm_mem.c
cc src/vmm/vmm_lapic.c
cc src/vmm/vmm_instruction_emul.c
cc src/vmm/vmm_ioport.c
cc src/vmm/vmm_callout.c
cc src/vmm/vmm_stat.c
cc src/vmm/vmm_util.c
cc src/vmm/vmm_api.c
cc src/vmm/intel/vmx.c
cc src/vmm/intel/vmx_msr.c
cc src/vmm/intel/vmcs.c
cc src/vmm/io/vatpic.c
cc src/vmm/io/vatpit.c
cc src/vmm/io/vhpet.c
cc src/vmm/io/vioapic.c
cc src/vmm/io/vlapic.c
cc src/vmm/io/vpmtmr.c
cc src/vmm/io/vrtc.c
cc src/acpitbl.c
cc src/atkbdc.c
cc src/block_if.c
cc src/consport.c
cc src/dbgport.c
cc src/inout.c
cc src/ioapic.c
cc src/md5c.c
cc src/mem.c
cc src/mevent.c
cc src/mptbl.c
cc src/pci_ahci.c
cc src/pci_emul.c
cc src/pci_hostbridge.c
cc src/pci_irq.c
cc src/pci_lpc.c
cc src/pci_uart.c
cc src/pci_virtio_block.c
cc src/pci_virtio_net_tap.c
cc src/pci_virtio_net_vmnet.c
cc src/pci_virtio_rnd.c
cc src/pm.c
cc src/post.c
cc src/rtc.c
cc src/smbiostbl.c
cc src/task_switch.c
cc src/uart_emul.c
cc src/xhyve.c
cc src/virtio.c
cc src/xmsr.c
cc src/firmware/kexec.c
cc src/firmware/fbsd.c
ld xhyve.sym
clang-3.6: error: unable to execute command: Segmentation fault: 11
clang-3.6: error: linker command failed due to signal (use -v to see invocation)
make: *** [build/xhyve.sym] Error 254

More interesting is the actual command being run by make:
ANG=en_US.US-ASCII clang -arch x86_64 -framework Hypervisor -framework vmnet -Xlinker -object_path_lto -Xlinker build/xhyve.lto.o -o build/xhyve.sym build/vmm/x86.o build/vmm/vmm.o build/vmm/vmm_host.o build/vmm/vmm_mem.o build/vmm/vmm_lapic.o build/vmm/vmm_instruction_emul.o build/vmm/vmm_ioport.o build/vmm/vmm_callout.o build/vmm/vmm_stat.o build/vmm/vmm_util.o build/vmm/vmm_api.o build/vmm/intel/vmx.o build/vmm/intel/vmx_msr.o build/vmm/intel/vmcs.o build/vmm/io/vatpic.o build/vmm/io/vatpit.o build/vmm/io/vhpet.o build/vmm/io/vioapic.o build/vmm/io/vlapic.o build/vmm/io/vpmtmr.o build/vmm/io/vrtc.o build/acpitbl.o build/atkbdc.o build/block_if.o build/consport.o build/dbgport.o build/inout.o build/ioapic.o build/md5c.o build/mem.o build/mevent.o build/mptbl.o build/pci_ahci.o build/pci_emul.o build/pci_hostbridge.o build/pci_irq.o build/pci_lpc.o build/pci_uart.o build/pci_virtio_block.o build/pci_virtio_net_tap.o build/pci_virtio_net_vmnet.o build/pci_virtio_rnd.o build/pm.o build/post.o build/rtc.o build/smbiostbl.o build/task_switch.o build/uart_emul.o build/xhyve.o build/virtio.o build/xmsr.o build/firmware/kexec.o build/firmware/fbsd.o

This does not occur when running the version of clang which ships with XCode:
$ clang --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

If you need more details, please let me know.

[1]: https://github.com/mist64/xhyve

**Comment by Endilll** [comment]
Unfortunately, we can't do much without preprocessed source.
Feel free to reopen if you have additional information.
