### ISSUE TITLE
Use-list order not preserved for personality functions, prefix data, or prologue data

### ISSUE THREAD

**Issue by sanjoy** [llvm/llvm-project#25129]
|  |  |
| --- | --- |
| Bugzilla Link | [24755](https://llvm.org/bz24755) |
| Version | trunk |
| OS | All |
| Attachments | [op.ll](https://user-images.githubusercontent.com/136291/143751993-01fb07ce-bb91-40c8-a857-5205f93c9fd0.gz), [op2.ll](https://user-images.githubusercontent.com/136291/143751994-7fdf270b-7ee1-490d-a1e6-73f5b03906e5.gz) |
| CC | @majnemer,@dexonsmith,@nikic,@rnk,@vedantk |

## Extended Description 

Attached op.ll and op2.ll

On op.ll:

 $ ./bin/verify-uselistorder ~/tmp/op.ll
*** verify-uselistorder ***
verify bitcode
LLVM ERROR: use-list order changed

On op2.ll:

 $ ./bin/verify-uselistorder ~/tmp/op2.ll
*** verify-uselistorder ***
verify bitcode
verify assembly
reverse
verify bitcode
verify assembly
verify-uselistorder: /var/folders/92/h8j88b090hb0fr_64xs4p43w0000gp/T/uselistorder-a5063d.ll:4:1: error: value has no uses
uselistorder i8 3, { 1, 0 }
^
LLVM ERROR: parsing failed

**Comment by nikic** [comment]
This has been fixed by https://github.com/llvm/llvm-project/commit/f5832eaaadc5382a4385e63d25f5ce08bc7a516c.
