### ISSUE TITLE
[analyzer] False positive: Called C++ object pointer is uninitialize

### ISSUE THREAD

**Issue by hiraditya** [llvm/llvm-project#25169]
|  |  |
| --- | --- |
| Bugzilla Link | [24795](https://llvm.org/bz24795) |
| Version | trunk |
| OS | Windows NT |
| CC | @ASDenysPetrov |

## Extended Description 
struct T{
  void hello() {}

};

int main()
{
  auto&& x = T();
  x.hello(); // issue at this point
  return 0;
}

Diagnostic:
test.cpp:9:3: warning: Called C++ object pointer is uninitialized
  x.hello(); // issue at this point
  ^~~~~~~~~
1 warning generated.

Reference:
http://stackoverflow.com/q/32539825/811335

**Comment by hiraditya** [comment]
can't repro.

**Comment by Endilll** [comment]
@hiraditya Can you provide a Compiler Explorer link?

**Comment by hiraditya** [comment]
https://godbolt.org/z/7Wa89xxnT
