### ISSUE TITLE
inefficient floating point register ld/st instructions are generated when -mcpu=power8 is specified

### ISSUE THREAD

**Issue by weiguozhi** [llvm/llvm-project#25191]
|  |  |
| --- | --- |
| Bugzilla Link | [24817](https://llvm.org/bz24817) |
| Version | trunk |
| OS | Linux |
| CC | @hfinkel,@nemanjai |

## Extended Description 
The simple test case is:

int foo(float *p)
{
  float f1 = p[1];
  float f2 = p[2];
  return f1 > f2;
}

Compiler command line and output

clang -S t8.c --target=powerpc -m64 -mcpu=power8 -O2
	li 4, 4             // A
	li 5, 8             // B
	lxsspx 0, 3, 4      // C
	lxsspx 1, 3, 5      // D
	li 3, 0
	li 4, 1
	fcmpu 0, 0, 1
	isel 3, 4, 3, 1
	blr

If I change -mcpu=power8 to -mcpu=power7, I got

	lfs 0, 4(3)        // E
	lfs 1, 8(3)        // F
	li 3, 0
	li 4, 1
	fcmpu 0, 0, 1
	isel 3, 4, 3, 1
	blr

Instructions AC are replaced by E
Instructions BD are replaced by F

**Comment by chenzheng1030** [comment]
https://godbolt.org/z/jY3oscPef

Trunk is good even for Pwr8
