### ISSUE TITLE
readability-identifier-naming only provides global TypedefCase

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#25210]
|  |  |
| --- | --- |
| Bugzilla Link | [24836](https://llvm.org/bz24836) |
| Version | unspecified |
| OS | All |

## Extended Description 
Right now there is only one global TypedefCase that applies to all type-defs.

I would like to specify different TypedefCases for:
- classes: public, protected, private,
- local scopes (e.g. inside a function), and
- global scopes (e.g. inside a namespace).

**Comment by EugeneZelenko** [comment]
According to current documentation all these options are supported.
