### ISSUE TITLE
clang crashes at -O0 on valid code with inlined assembly on x86_64-linux-gnu

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#25258]
|  |  |
| --- | --- |
| Bugzilla Link | [24884](https://llvm.org/bz24884) |
| Version | trunk |
| OS | All |
| CC | @compnerd,@hfinkel,@zygoloid |

## Extended Description 
The current clang trunk crashes when compiling the following code at -O0 (but not at -O1 and above) in both 32-bit and 64-bit modes on x86_64-linux-gnu.  

It is a regression from 3.1. 

$ clang-trunk -v
clang version 3.8.0 (trunk 248020)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/tools/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.1.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.1.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clang-trunk -O1 small.c
$ clang-3.1 -O0 small.c
$ 
$ clang-trunk -O0 small.c
Instruction uses an allocated register
UNREACHABLE executed at /tmp/llvm/lib/CodeGen/RegAllocFast.cpp:361!
#&#8203;0 0x2de285d llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/clang-trunk/bin/clang+0x2de285d)
#&#8203;1 0x2de1ee6 llvm::sys::RunSignalHandlers() (/usr/local/clang-trunk/bin/clang+0x2de1ee6)
#&#8203;2 0x2de405e (/usr/local/clang-trunk/bin/clang+0x2de405e)
#&#8203;3 0x7f1808a30340 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10340)
#&#8203;4 0x7f18079cbcc9 gsignal /build/buildd/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;5 0x7f18079cf0d8 abort /build/buildd/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;6 0x2dca32d llvm::llvm_unreachable_internal(char const*, char const*, unsigned int) (/usr/local/clang-trunk/bin/clang+0x2dca32d)
#&#8203;7 0x25b5862 (/usr/local/clang-trunk/bin/clang+0x25b5862)
#&#8203;8 0x25b280f (/usr/local/clang-trunk/bin/clang+0x25b280f)
#&#8203;9 0x254496c llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/usr/local/clang-trunk/bin/clang+0x254496c)
#&#8203;10 0x2d32404 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/local/clang-trunk/bin/clang+0x2d32404)
#&#8203;11 0x2d3264b llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/local/clang-trunk/bin/clang+0x2d3264b)
#&#8203;12 0x2d32b25 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/local/clang-trunk/bin/clang+0x2d32b25)
#&#8203;13 0x9db71d clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::raw_pwrite_stream*) (/usr/local/clang-trunk/bin/clang+0x9db71d)
#&#8203;14 0x9bdf03 (/usr/local/clang-trunk/bin/clang+0x9bdf03)
#&#8203;15 0xc44da6 clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/clang-trunk/bin/clang+0xc44da6)
#&#8203;16 0x7764e5 clang::FrontendAction::Execute() (/usr/local/clang-trunk/bin/clang+0x7764e5)
#&#8203;17 0x74384c clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/clang-trunk/bin/clang+0x74384c)
#&#8203;18 0x723477 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/clang-trunk/bin/clang+0x723477)
#&#8203;19 0x719355 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/clang-trunk/bin/clang+0x719355)
#&#8203;20 0x721b0f main (/usr/local/clang-trunk/bin/clang+0x721b0f)
#&#8203;21 0x7f18079b6ec5 __libc_start_main /build/buildd/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;22 0x718de9 _start (/usr/local/clang-trunk/bin/clang+0x718de9)
Stack dump:
0.	Program arguments: /usr/local/clang-trunk/bin/clang -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name small.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -target-linker-version 2.24 -dwarf-column-info -resource-dir /usr/local/clang-trunk/bin/../lib/clang/3.8.0 -internal-isystem /usr/local/include -internal-isystem /usr/local/clang-trunk/bin/../lib/clang/3.8.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O0 -fdebug-compilation-dir /data2/c-hunter-results/C/tokenmutate-bugs/20150918-clang-build-test92-1 -ferror-limit 19 -fmessage-length 109 -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/small-79a9dc.o -x c small.c 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'small.c'.
4.	Running pass 'Fast Register Allocator' on function '@main'
clang: error: unable to execute command: Aborted
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.8.0 (trunk 248020)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/tools/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/small-102ab9.c
clang: note: diagnostic msg: /tmp/small-102ab9.sh
clang: note: diagnostic msg: 

********************
$ 

---------------------------------------------

int
main ()
{
  register int x asm ("r8");
  __asm ("mov %0, %1;" : "=r" (x) , "=r" (x));
  return 0; 
}

**Comment by fhahn** [comment]
Clang now produces the following error message instead of crashing: https://clang.godbolt.org/z/4e5cYYacs

```
source>:5:1: error: multiple outputs to hard register: r8
__asm ("mov %0, %1;" : "=r" (x) , "=r" (x));
^
1 error generated.
Compiler returned: 1
```

GCC also rejects the inline assembly as invalid, so I am closing this for now.
