### ISSUE TITLE
feature request: readability check for reference syntax

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#25271]
|  |  |
| --- | --- |
| Bugzilla Link | [24897](https://llvm.org/bz24897) |
| Version | unspecified |
| OS | All |
| CC | @EugeneZelenko |

## Extended Description 
It would be nice to have a check to enforce a consistent reference syntax. Examples:

void foo(const param&);  vs  void foo(param const&);
void foo(const param&&); vs  void foo(param const&&);

const b& = c;  vs int const& a = c;
const b&& = c;  vs int const&& a = c;

As far as I know there are only these two conventions (const type& and type const&), and the difference only matters for const lvalue references and const rvalue references (whether const rvalue references should be used or not is a different story).  

Since this check is out of scope for clang-format, I guess the right place to add this is in clang-tidy as a readability check.

**Comment by carlosgalvezp** [comment]
This functionality is already implemented in clang-format via the `QualifierAlignment` option.
