### ISSUE TITLE
feature request: automatically nest namespaces

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#25275]
|  |  |
| --- | --- |
| Bugzilla Link | [24901](https://llvm.org/bz24901) |
| Version | unspecified |
| OS | All |
| CC | @EugeneZelenko |

## Extended Description 
In C++ >= 17 one can nest different namespace definitions, so it would be nice to have a tool that automatically transforms

namespace A { 
namespace B { 

// watch out with comments
namespace C {

...

}
}
}

to 

namespace A::B {

// watch out with comments
namespace C {

 ... 

}
}

**Comment by EugeneZelenko** [comment]
Implemented as `modernize-concat-nested-namespaces`.
