### ISSUE TITLE
Undefined referenced building libc++abi with MinGW-w64

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25285]
|  |  |
| --- | --- |
| Bugzilla Link | [24911](https://llvm.org/bz24911) |
| Version | 3.7 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
I have MinGW-w64 (gcc 5.2.0, 64bit, posix threads, sjlj) installed

I'm building LLVM, Clang, lld, libc++, and libc++abi 3.7 that I downloaded from http://llvm.org/releases/download.html

I configured the project with cmake (cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release ..\llvm) I'm building by running mingw32-make

The build fails when it gets to linking libc++abi

C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0xb): undefined reference to `malloc'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x16): undefined reference to `_encode_pointer'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0xc0): undefined reference to `_amsg_exit'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x1ac): undefined reference to `_decode_pointer'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x1c4): undefined reference to `_decode_pointer'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x1eb): undefined reference to `free'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x255): undefined reference to `_initterm'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../..[ 18%] /x86_64Built target ClangCommentHTMLTags-w64-mingw32/
lib[ 18%] /Built target ClangDiagnosticParse../lib/dllcrt2.o:crtdll.c:(.text+0x264
): undefined reference to `_amsg_exit'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x27c): undefined reference to `_initterm'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x2ba): undefined reference to `_pei386_runtime_relocator'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x2c7): undefined reference to `DllMain'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x2f1): undefined reference to `_pei386_runtime_relocator'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x31d): undefined reference to `DllEntryPoint'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x349): undefined reference to `DllEntryPoint'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x376): undefined reference to `__main'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x386): undefined reference to `DllMain'
C:/PROGRA~1/MINGW-~[ 18%] 1Built target ClangDiagnosticAST
/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x39d): undefined reference to `DllMain'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x3aa): undefined reference to `DllEntryPoint'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x3cc): undefined reference to `DllMain'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x40f): undefined reference to `__security_init_cookie'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../[ 18%] x86_64Built target ClangCommentHTMLTagsProperties-
w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x414): undefined reference to `__mingw_init_ehandler'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.rdata$.refptr.mingw_app_type[.refptr.mingw_app_type]+0x0): undefined reference to `mingw_app_type'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/[ 18%] .Built target ClangAttrClasses./
lib/dllcrt2.o:crtdll.c:(.rdata$.refptr.__native_dllmain_reason[.refptr.__native_dllmain_reason]+0x0): undefined reference to `__native_dllmain_reason'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.rdata$.refptr.__dyn_tls_init_callback[.refptr.__dyn_tls_init_callback]+0x0): undefined reference to `__dyn_tls_init_callback'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.rdata$.refptr.__xc_a[.refptr.__xc_a]+0x0): undefined reference to `__xc_a'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.rdata$.refptr.__xc_z[.refptr.__xc_z]+0x0): undefined reference to `__xc_z'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.rdata$.refptr.__xi_a[.refptr.__xi_a]+0x0): undefined reference to `__xi_a'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.rdata$.refptr.__xi_z[.refptr.__xi_z]+0x0): undefined reference to `__xi_z'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.rdata$.refptr.__native_startup_state[.refptr.__native_startup_state]+0x0): undefined reference to `__native_startup_state'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib[ 18%] /Built target ClangDeclNodesdllcrt2.o
:crtdll.c:(.rdata$.refptr.__native_startup_lock[.refptr.__native_startup_lock]+0x0): undefined reference to `__native_startup_lock'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.rdata$.refptr.__onexitend[.refptr.__onexitend]+0x0): undefined reference to `__onexitend'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64[ 18%] Built target ClangCommentNodes
-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.rdata$.refptr.__onexitbegin[.refptr.__onexitbegin]+0x0): undefined reference to [ 18%] Built target ClangCommentCommandInfo
`__onexitbegin'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/crtbegin.o:cygming-crtbegin.c:(.text+0x5f): undefined reference to `atexit'
CMakeFiles\cxxabi_shared.dir/objects.a(abort_message.cpp.obj):abort_message.cpp:(.text+0xa): undefined reference to `__imp___iob_func'
CMakeFiles\cxxabi_shared.dir/objects.a(abort_message.cpp.obj):abort_message.cpp:(.text+0x37): undefined reference to `vfprintf'
CMakeFiles\cxxabi_shared.dir/objects.a(abort_message.cpp.obj):abort_message.cpp:(.text+0x47): undefined reference to `fputc'
CMakeFiles\cxxabi_shared.dir/objects.a(abort_message.cpp.obj):abort_message.cpp:(.text+0x4c): undefined reference to `abort'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0xe8): undefined reference to `malloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x176): undefined reference to `malloc'[ 18%]
Built target ClangStmtNodesCMakeFiles
\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x1e5): undefined reference to `_assert'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x1f9): undefined reference to `malloc[ 18%] 'Built target ClangDiagnosticFrontend

CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x215): undefined reference to `memcpy'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x265): undefined reference to `memcpy'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x29a): undefined reference to `_assert'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text[ 18%] Built target ClangDiagnosticDriver
+0x2b3): undefined reference to `malloc'
CMakeFiles\cxxabi_shared.dir/objects.a([ 18%] Built target ClangDiagnosticCommon
cxa_demangle.cpp.obj)[ 18%] :Built target ClangAttrImplcxa_demangle.cpp
:(.text+0x3a3): undefined reference to `malloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x3d2): undefined reference to `free'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x40f): undefined reference to `malloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x425): undefined reference to `memcpy'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp[ 18%] :Built target ClangAttrVisitor(
.text+0x440): undefined reference to `memcpy'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x46e): undefined reference to `memcpy'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x4a9): undefined reference to `_assert'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x512): undefined reference to `memcpy'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x610): undefined reference to `strlen'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x676): undefined reference to `_assert'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x6da): undefined reference to `memmove'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj)[ 18%] :Built target ClangAttrDumpcxa_demangle.cpp
:(.text+0x6eb): undefined reference to `memmove'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x7a5): undefined reference to `strlen'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x80a): undefined reference to `memmove[ 20%] 'Built target ClangDiagnosticComment

CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x954): undefined reference to `__ms_vsnprintf'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0xbda): undefined reference to `strlen'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0xc64): undefined reference to `strlen'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0xd56): undefined reference to `strlen[ 20%] Built target ClangDiagnosticSerialization
'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0xefd): undefined reference to `memmove'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0xfd5): undefined reference to `strlen'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x102c): undefined reference to `_assert'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x10dc): undefined reference to `memcmp'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x11c5): undefined reference to `_assert'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x11d9): undefined reference to `malloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x150c): undefined reference to[ 20%]  Built target ClangAttrHasAttributeImpl`
memcpy'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x151d): undefined reference to `free'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text[ 20%] +Built target ClangDiagnosticSema0x156a
): undefined reference to `malloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x15d1): undefined reference to `malloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x1755): undefined reference to `malloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x1773): undefined reference to `free'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.[ 20%] Built target ClangDiagnosticGroups
text+0x179f): undefined reference to `malloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x17b5): undefined reference to `memcpy'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x17d4): undefined reference to `memcpy'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x1809): undefined reference to `_assert'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x1aa6): undefined reference to `_assert'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x1af1): undefined reference to `malloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x1f3f): undefined reference to `_assert'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x24f5): undefined reference to `malloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x251d): undefined reference to `_assert'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x2aed): undefined reference to `_assert[ 20%] 'Built target ClangDiagnosticIndexName

CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+[ 20%] 0x2b02Built target ClangAttrList)
: undefined reference to `malloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x2d8d): undefined reference to `_assert'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x2da2): undefined reference to `malloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x2fe1): undefined reference to `_assert[ 20%] Built target ClangAttrParserStringSwitches
'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x3250): undefined reference to `_assert'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x45a2): undefined reference to `__imp_isupper'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x4742): undefined reference to `__imp_isupper'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x9846): undefined reference to `memmove'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x9cff): undefined reference to `memmove'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0xae2a): undefined reference to `memmove'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0xb56b)[ 20%] : undefined referenceBuilt target ClangARMNeon
to `memmove'
CMakeFiles[ 20%] \Built target ClangAttrTemplateInstantiatecxxabi_shared.dir
/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0xfb29): undefined reference to `memmove'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x11573): undefined reference to `__imp_isxdigit'
CMakeFiles[ 21%] \Built target ClangAttrParsedAttrListcxxabi_shared.dir
/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x117f6): undefined reference to `__imp_isxdigit'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x11a46): undefined reference to `__imp_isxdigit'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x1336d): undefined reference to `_assert'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x21637): undefined reference to `___chkstk_ms'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x218ad): undefined reference[ 21%] Built target ClangAttrSpellingListIndex
to[ 21%] Built target ClangAttrPCHRead
`strlen'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x21bd1): undefined reference to `memcpy'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):[ 21%] Built target ClangAttrParsedAttrKinds
cxa_demangle.cpp:(.text+0x21c49): undefined reference to `realloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0x304): undefined reference to `free'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_demangle.cpp.obj):cxa_demangle.cpp:(.text+0xad5): undefined reference to `free'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_exception.cpp.obj):cxa_exception.cpp:(.text+0x2a4): undefined reference to `free'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_exception.cpp.obj):cxa_exception.cpp:(.text+0x3b3): undefined reference to `malloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_exception.cpp.obj):cxa_exception.cpp:(.text+0x3ce): undefined reference to `memset'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_exception.cpp.obj):cxa_exception.cpp:(.text+0x51b): undefined reference to `malloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_exception_storage.cpp.obj):cxa_exception_storage.cpp:(.text+0x35): undefined reference to `free'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_exception_storage.cpp.obj):cxa_exception_storage.cpp:(.text+0xcb): undefined reference to `calloc'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_new_delete.cpp.obj):cxa_new_delete.cpp:(.text+0xfd): undefined reference to `malloc'[ 21%] Built target ClangDriverOptions

CMakeFiles\cxxabi_shared.dir/objects.a(cxa_new_delete.cpp.obj):cxa_new_delete.cpp:(.text+0x4d2): undefined reference to `operator new[](unsigned long long)'
[ 21%] CMakeFilesBuilt target ClangAttrPCHWrite\
cxxabi_shared.dir/objects.a(cxa_new_delete.cpp.obj):cxa_new_delete.cpp:(.text+0x5c6): undefined reference to `free'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_new_delete.cpp.obj):cxa_new_delete.cpp:(.text+0x600): undefined reference to `operator delete(void*)'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_new_delete.cpp.obj):cxa_new_delete.cpp:(.text+0x630): undefined reference to `[ 21%] operatorBuilt target DriverOptionsTableGen
delete(void*)'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_new_delete.cpp.obj):cxa_new_delete.cpp:(.text+0x660): undefined reference to `operator delete[ 21%] Built target COFFOptionsTableGen(
void*)'
[ 21%] Built target intrinsics_gen
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_new_delete.cpp.obj)[ 21%] Built target LibOptionsTableGen
:cxa_new_delete.cpp:(.text+0x671): undefined reference to `operator delete(void*)'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_new_delete.cpp.obj):cxa_new_delete.cpp:(.text+0x681): undefined reference to `operator delete(void*)'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_new_delete.cpp.obj):cxa_new_delete.cpp:(.text+0x691): undefined reference to `operator delete[](void*)'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_personality.cpp.obj):cxa_personality.cpp:(.text+0xd3): undefined reference to `abort'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_vector.cpp.obj):cxa_vector.cpp:(.rdata$.refptr._Znay[.refptr._Znay]+0x0): undefined reference to `operator new[](unsigned long long)'
CMakeFiles\cxxabi_shared.dir/objects.a(cxa_vector.cpp.obj):cxa_vector.cpp:(.rdata$.refptr._ZdaPv[.refptr._ZdaPv]+0x0): undefined reference to `operator delete[](void*)'
CMakeFiles\cxxabi_shared.dir/objects.a(exception.cpp.obj):exception.cpp:(.text+0x41): undefined reference to `operator delete(void*)'
CMakeFiles\cxxabi_shared.dir/objects.a(exception.cpp.obj):exception.cpp:(.text+0x51): undefined reference to `operator delete(void*)'
CMakeFiles\cxxabi_shared.dir/objects.a(private_typeinfo.cpp.obj):private_typeinfo.cpp:(.text+0x2b2): undefined reference to `strcmp'
CMakeFiles\cxxabi_shared.dir/objects.a(private_typeinfo.cpp.obj):private_typeinfo.cpp:(.text+0x2e2): undefined reference to `strcmp'
CMakeFiles\cxxabi_shared.dir/objects.a(private_typeinfo.cpp.obj):private_typeinfo.cpp:(.text+0x335): undefined reference to `strcmp'
CMakeFiles\cxxabi_shared.dir/objects.a(private_typeinfo.cpp.obj):private_typeinfo.cpp:(.text+0x364): undefined reference to `strcmp'
CMakeFiles\cxxabi_shared.dir/objects.a(private_typeinfo.cpp.obj):private_typeinfo.cpp:(.text+0x4b2): undefined reference to `strcmp'
CMakeFiles\cxxabi_shared.dir/objects.a(private_typeinfo.cpp.obj):private_typeinfo.cpp:(.text+0x52b): more undefined references to `strcmp' follow
CMakeFiles\cxxabi_shared.dir/objects.a(private_typeinfo.cpp.obj):private_typeinfo.cpp:(.text+0xe0): undefined reference to `operator delete(void*)'
CMakeFiles\cxxabi_shared.dir/objects.a(private_typeinfo.cpp.obj):private_typeinfo.cpp:(.text+0x110): undefined reference to `operator delete(void*)'
CMakeFiles\cxxabi_shared.dir/objects.a(private_typeinfo.cpp.obj):private_typeinfo.cpp:(.text+0x140): undefined reference to `operator delete(void*)'
CMakeFiles\cxxabi_shared.dir/objects.a(private_typeinfo.cpp.obj):private_typeinfo.cpp:(.text+0x170): undefined reference to `operator delete(void*)'
CMakeFiles\cxxabi_shared.dir/objects.a(private_typeinfo.cpp.obj):private_typeinfo.cpp:(.text+0x1a0): undefined reference to `operator delete(void*)'
CMakeFiles\cxxabi_shared.dir/objects.a(private_typeinfo.cpp.obj):private_typeinfo.cpp:(.text+0x1d0): more undefined references to `operator delete(void*)' follow
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/libgcc_eh.a(unwind-sjlj.o): In function `_Unwind_RaiseException_Phase2':
C:/mingw520/src/gcc-5.2.0/libgcc/unwind.inc:71: undefined reference to `abort'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/libgcc_eh.a(unwind-sjlj.o): In function `_Unwind_SjLj_Resume':
C:/mingw520/src/gcc-5.2.0/libgcc/unwind.inc:234: undefined reference to `abort'
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/libgcc_eh.a(unwind-sjlj.o): In function `_Unwind_SjLj_Resume_or_Rethrow':
C:/mingw520/src/gcc-5.2.0/libgcc/unwind.inc:259: undefined reference to `abort'
collect2.exe: error: ld returned 1 exit status
projects\libcxxabi\src\CMakeFiles\cxxabi_shared.dir\build.make:103: recipe for target 'bin/libc++abi.dll' failed
mingw32-make[2]: *** [bin/libc++abi.dll] Error 1
CMakeFiles\Makefile2:11706: recipe for target 'projects/libcxxabi/src/CMakeFiles/cxxabi_shared.dir/all' failed
mingw32-make[1]: *** [projects/libcxxabi/src/CMakeFiles/cxxabi_shared.dir/all] Error 2
mingw32-make[1]: *** Waiting for unfinished jobs....
[ 22%] Built target clangBasic
[ 23%] Built target clangLex
[ 23%] Built target clangParse
makefile:148: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by philnik777** [comment]
Closing this, since I don't think there is a way to find out what exactly the problem was and the version built is very old.
