### ISSUE TITLE
[autoconf -> cmake] libclang.a is not packaged in the Ubuntu x86_64 pre-built

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25293]
|  |  |
| --- | --- |
| Bugzilla Link | [24919](https://llvm.org/bz24919) |
| Version | 3.7 |
| OS | Linux |
| Blocks | llvm/llvm-project#16104  |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz[1] release doesn't contain a libclang.a, due to the autoconf -> cmake change. The static libclang has been provided in all recent prior versions and the lack of this library in 3.7.0 makes it unusable for some.

The OS X and FreeBSD pre-builts don't suffer from this, since they're still using autoconf, I believe.

[1] http://llvm.org/releases/3.7.0/clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz

**Comment by arsenm** [comment]
Old build/packaging issue
