### ISSUE TITLE
SCEV Expander fails to reuse existing values

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25294]
|  |  |
| --- | --- |
| Bugzilla Link | [24920](https://llvm.org/bz24920) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @sanjoy |

## Extended Description 
Currently SCEV expander only reuses existing values if they're exactly like the one it tries to expand. However, it should be able to use similar values (not exactly the same) to generate more optimal code.

Below is the example:
------------------
target datalayout = "e-m:o-i64:64-f80:128-n8:16:32:64-S128"

; Function Attrs: noinline nounwind ssp uwtable
define i8* @&#8203;foo(i32 %y, i8* noalias %src, i8* noalias %dst) {
entry:
  %cmp = icmp slt i32 %y, 4096
  %sub = add nsw i32 %y, -1
  %tripcount = select i1 %cmp, i32 %sub, i32 4095
  %loop.entry.cond = icmp sgt i32 %tripcount, 0
  br i1 %loop.entry.cond, label %loop.ph, label %loop.exit

loop.ph:                                   ; preds = %entry
  br label %loop.body

loop.body:                                         ; preds = %loop.body, %loop.ph
  %iv = phi i32 [ 0, %loop.ph ], [ %iv.next, %loop.body ]
  %src.iv = phi i8* [ %src, %loop.ph ], [ %src.iv.next, %loop.body ]
  %dst.iv = phi i8* [ %dst, %loop.ph ], [ %dst.iv.next, %loop.body ]

  %tmp = load i8, i8* %src.iv, align 1
  store i8 %tmp, i8* %dst.iv, align 1

  %src.iv.next = getelementptr inbounds i8, i8* %src.iv, i64 1
  %dst.iv.next = getelementptr inbounds i8, i8* %dst.iv, i64 1
  %iv.next = add nsw i32 %iv, 1

  %loop.cond = icmp slt i32 %iv.next, %tripcount
  br i1 %loop.cond, label %loop.body, label %loop.exit

loop.exit:                                 ; preds = %loop.exit, %entry
  %src.iv.lcssa = phi i8* [ %src.iv.next, %loop.body ], [ %src, %entry ]
  ret i8* undef
}

!llvm.module.flags = !{#0, !&#8203;1}
!llvm.ident = !{#2}

!&#8203;0 = !{i32 2, !"Debug Info Version", i32 3}
!&#8203;1 = !{i32 1, !"PIC Level", i32 2}
!&#8203;2 = !{!"clang version 3.8.0 (trunk 247767) (llvm/trunk 247769)"}
------------------
In this test it fails to rewrite exit value for %src, as its SCEV value contains smax, which is considered expensive. However, it doesn't need to generate code for smax, because such code already exists and the result is in %tripcount value.

This bug was revealed in this review: http://reviews.llvm.org/D12765

**Comment by fhahn** [comment]
AFAICT current LLVM generates the expected IR: https://llvm.godbolt.org/z/4ov69bexT
