### ISSUE TITLE
Proposal for new check: alternate function syntax

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25343]
|  |  |
| --- | --- |
| Bugzilla Link | [24969](https://llvm.org/bz24969) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @EugeneZelenko |

## Extended Description 
http://en.wikipedia.org/wiki/C%2B%2B11#Alternative_function_syntax

== Check Considerations
Impact: all function declarations and definitions, member function declarations and definitions.
Possible Impact Levels:
Everything
Only non-POD return types

Return types of member functions defined out-of-line where the type is a member type e.g.
{{
MyClass::MyType MyClass::myFunction() {..}

to
auto MyClass::myFunction() -> MyType {...}
}}

The alternate function syntax solves other issues, especially for function templates when the return type depends on template arguments. Since we're transforming existing compiling C++ code this problem will have been solved in other ways already so it's not something to worry about. However, if we come across a common idiom used to fix the issue we could account for that in the transform.

**Comment by EugeneZelenko** [comment]
Already implemented in `modernize-use-trailing-return-type`.
