### ISSUE TITLE
assertion failure: (Ty && "Invalid GetElementPtrInst indices for type!")

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25349]
|  |  |
| --- | --- |
| Bugzilla Link | [24975](https://llvm.org/bz24975) |
| Version | 3.7 |
| OS | All |
| Attachments | [backtrace](https://user-images.githubusercontent.com/60944935/143752087-a339decb-fda1-4fe7-aa67-d01ce6718952.gz), [run script](https://user-images.githubusercontent.com/60944935/143752088-c94ecc33-158d-454a-89a0-f9f192ecbb86.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel |

## Extended Description 

I am trying to compile the latest revision of graph-tool (https://graph-tool.skewed.de) with -fopenmp. Both clang 3.7 and r246024 crash with the attached backtrace.

**Comment by Endilll** [comment]
Link to preprocessed source is dead. Unfortunately, we can't do much without a reproducer.
Feel free to reopen if you have additional information.
