### ISSUE TITLE
Memory leak when compiling a file with a lot of enums

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25388]
|  |  |
| --- | --- |
| Bugzilla Link | [25014](https://llvm.org/bz25014) |
| Version | 3.7 |
| OS | All |
| Attachments | [Run script](https://user-images.githubusercontent.com/60944935/143752115-6ea5e31d-d6e7-41a6-b424-74288887f390.gz), [Preprocessed source (gzipped)](https://user-images.githubusercontent.com/60944935/143752116-2a1fc635-d070-47f7-a0fc-ef4aa58c0e57.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
PS: I am trying to build glbinding https://github.com/cginternals/glbinding and build fails at file `types.cpp`

Host: MSYS2 x86_64 on Windows 10 x86_64 clang version 3.7.0
When building this file for x86_64 the build takes a very long time, clang uses more than 3Gb of RAM, but it succeeds(the clang executable is 64bit). When building a 32-bit build clang crashes because it can't allocate enough memory.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 4.
