### ISSUE TITLE
Incorrect whitespace with SpaceAfterCStyleCast

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25417]
|  |  |
| --- | --- |
| Bugzilla Link | [25043](https://llvm.org/bz25043) |
| Version | trunk |
| OS | All |
| Attachments | [Code that formats incorrectly](https://user-images.githubusercontent.com/60944935/143752141-5e5102f5-952e-4b0a-9eec-12ee23345fdd.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Formatting the attached C++ source file with

    clang-format -style="{SpaceAfterCStyleCast: true}" -i clang-format-bug.cpp

adds an unnecessary space before the last closing parenthesis in foo(). This can be fixed by setting the SpaceAfterCStyleCast style to false, even though there is no C-style cast in the code.

**Comment by mydeveloperday** [comment]
clang-format-bug.cpp is

```
template <typename T> T bar(T t) { return t; }

void foo() { bar(bar(bar<int>) ); }
```

**Comment by mydeveloperday** [comment]
Using clang-format v13 produces the following, I will close this issue please reopen if you consider it not fixed

```
template <typename T> T bar(T t) { return t; }

void foo() { bar(bar(bar<int>)); }
```
