### ISSUE TITLE
Add two features to clang-format needed by LLDB

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25415]
|  |  |
| --- | --- |
| Bugzilla Link | [25041](https://llvm.org/bz25041) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
1) Constructor initializer list comma at the end of the line.

Clang-format currently supports this:

foo::foo()
    : m1(1)
    , m2(2)
{ }

LLDB needs it to support the following syntax:

foo::foo() :
    m1(1),
    m2(2)
{ }

2) Return type on separate line for declarations and definitions.

Clang-format currently supports putting a function's return type on a separate line for function definitions.

LLDB needs this syntax for declarations *and* definitions.  For example, if I have this:

class Foo
{
    void
    Bar();
};

clang-format will change this to:

class Foo
{
    void Bar();
};

We need an option that will format function declarations as shown in the first example.

**Comment by mkurdej** [comment]
Closing as this was fixed by 1. `BreakConstructorInitializers: AfterColon` and 2. `AlwaysBreakAfterReturnType: All`.
