### ISSUE TITLE
Running pass 'Module Verifier' on function '@main':Segmentation fault(core dumped)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25486]
|  |  |
| --- | --- |
| Bugzilla Link | [25112](https://llvm.org/bz25112) |
| Version | unspecified |
| OS | Linux |
| Attachments | [I have attached code as well as the error](https://user-images.githubusercontent.com/60944935/143752177-214c409a-ad65-4ca1-b558-fdc4bbb4d71a.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Hey can you tell me what is the issue with my pass due to which it is showing "Segmetation fault".I am creating it for llvm-3.4 is this because of older version or there is bug in the pass.

**Comment by arsenm** [comment]
Missing context but this is modifying a block instruction list during iteration of the block
