### ISSUE TITLE
clang++ segfaults upon trying to compile with -fconstexpr-depth

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25509]
|  |  |
| --- | --- |
| Bugzilla Link | [25135](https://llvm.org/bz25135) |
| Version | 3.5 |
| OS | Windows NT |
| Attachments | [preprocessed source and invocation script tarballed together, gzipped](https://user-images.githubusercontent.com/60944935/143752186-38809766-93c0-4e52-9c46-0c1d2ee47543.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
Attached are preprocessed source and invocation script in a tarball. The error message asked for the crash backtrace, but I have no idea where that is, as it didn't specify.

I'm sorry that my horrible abuse of template metaprogramming broke stuff.

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.5 through 3.8 with assertions enabled: https://godbolt.org/z/h4Y95cWa1
