### ISSUE TITLE
Compiling v8 engine in vagrant (Jessie)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25514]
|  |  |
| --- | --- |
| Bugzilla Link | [25140](https://llvm.org/bz25140) |
| Version | trunk |
| OS | Linux |
| Attachments | [associate run script](https://user-images.githubusercontent.com/60944935/143752191-b1e40f09-c53e-4098-8812-f9fd3a5b3af6.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @jmolloy |

## Extended Description 
Don't really know much about clang but following instructions here:

https://github.com/phpv8/v8js/blob/master/README.Linux.md

On Mac OSX with Vagrant (Virtualbox) on Debian jessie.  

Didn't even know I had to do sudo apt-get install clang for the instructions to work.  

Anyway, got to this part of the instructions

make native library=shared -j8

which took forever (more than 15 minutes) then got the note to file a bug report

===

test/cctest/cctest.target.native.mk:315: recipe for target '/home/vagrant/tmp/v8/out/native/obj.target/cctest/test/cctest/gay-fixed.o' failed
make[1]: *** [/home/vagrant/tmp/v8/out/native/obj.target/cctest/test/cctest/gay-fixed.o] Error 254
make[1]: *** Waiting for unfinished jobs....
clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.8.0 (trunk 247874)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/vagrant/tmp/v8/third_party/llvm-build/Release+Asserts/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:

test/cctest/cctest.target.native.mk:315: recipe for target '/home/vagrant/tmp/v8/out/native/obj.target/cctest/test/cctest/gay-shortest.o' failed
make[1]: *** [/home/vagrant/tmp/v8/out/native/obj.target/cctest/test/cctest/gay-shortest.o] Error 254
make[1]: Leaving directory '/home/vagrant/tmp/v8/out'
Makefile:317: recipe for target 'native' failed
make: *** [native] Error 2

**Comment by Endilll** [comment]
Author has never got back to us with a reproducer.
Unfortunately, we can't do much without preprocessed source.
Feel free to reopen if you have additional information.
