### ISSUE TITLE
modernize check to use alternative operator representations

### ISSUE THREAD

**Issue by EugeneZelenko** [llvm/llvm-project#25569]
|  |  |
| --- | --- |
| Bugzilla Link | [25195](https://llvm.org/bz25195) |
| Version | unspecified |
| OS | All |
| CC | @gnzlbg,@mgehre |

## Extended Description 
Will be good idea to have modernize check which could replace traditional operators representations with alternative ones: && with and, || with or, etc. See http://en.cppreference.com/w/cpp/language/operator_alternative.

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D144522

**Comment by PiotrZSL** [comment]
Finished by a084854266ca60748982228a4c98d036bca5f762
