### ISSUE TITLE
r226467 causes crashes when parsing bitcode generated by LLVM 3.5

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#25622]
|  |  |
| --- | --- |
| Bugzilla Link | [25248](https://llvm.org/bz25248) |
| Version | trunk |
| OS | Linux |
| Attachments | [bitcode to reproduce crash](https://user-images.githubusercontent.com/143300/143752252-d78f08fd-40cc-48ca-812a-3ef5926a3678.gz), [LLVM IR used to generate bitcode with llvm 3.5](https://user-images.githubusercontent.com/143300/143752253-f83477d9-cce7-4f90-8431-33c611a80ecd.gz) |
| CC | @majnemer,@echristo |

## Extended Description 

Commit r226467 causes llvm-dis to crash when parsing bitcode generated by LLVM 3.5.  Here is the backtrace:

#&#8203;0 0x7f540de75b92 llvm::sys::PrintStackTrace(_IO_FILE*) (libLLVM-3.7svn.so+0x44db92)
#&#8203;1 0x7f540de73d21 SignalHandler(int) (libLLVM-3.7svn.so+0x44bd21)
#&#8203;2 0x7f540d6001c0 (/lib64/libpthread.so.0+0x101c0)
#&#8203;3 0x7f540e31c200 llvm::Comdat::getName() const (libLLVM-3.7svn.so+0x8f4200)
#&#8203;4 0x7f540e303b21 llvm::Comdat::print(llvm::raw_ostream&) const (libLLVM-3.7svn.so+0x8dbb21)
#&#8203;5 0x7f540e30e60d llvm::AssemblyWriter::printModule(llvm::Module const*) (libLLVM-3.7svn.so+0x8e660d)
#&#8203;6 0x7f540e30f571 llvm::Module::print(llvm::raw_ostream&, llvm::AssemblyAnnotationWriter*) const (libLLVM-3.7svn.so+0x8e7571)
#&#8203;7 0x402899 main (llvm-dis+0x402899)
#&#8203;8 0x7f540c5e9a65 __libc_start_main (/lib64/libc.so.6+0x21a65)
#&#8203;9 0x402a39 _start (llvm-dis+0x402a39)

Attached are 2 files:

comdat-crash-3.5.bc - The bitcode which triggers the bug
comdat-crash-3.5.ll - The LLVM IR used to generate the bitcode with llvm 3.5

**Comment by arsenm** [comment]
Attached bitcode and IR roundtrip without asserting today. The section isn't implicitly dropped or anything
