### ISSUE TITLE
CodeGen build broken on cygwin

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25664]
|  |  |
| --- | --- |
| Bugzilla Link | [25290](https://llvm.org/bz25290) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@pcc,@rnk |

## Extended Description 
In file included from /home/eric/llvm/lib/CodeGen/ParallelCG.cpp:22:0:
/home/eric/llvm/include/llvm/Support/thread.h:41:14: error: ‘thread’ in namespace ‘std’ does not name a type
 typedef std::thread thread;
              ^

**Comment by arsenm** [comment]
Old build issue
