### ISSUE TITLE
modernize-pass-by-value doesn't handle both pass by rvalue-ref as const-lvalue-ref

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#25693]
|  |  |
| --- | --- |
| Bugzilla Link | [25319](https://llvm.org/bz25319) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Reproduction scenario](https://user-images.githubusercontent.com/95090374/143752306-d45b9543-89a8-478e-89f2-3c618a62cff4.gz) |
| CC | @JVApen |

## Extended Description 

#include <string>

struct A final
{
    explicit A(const std::string &s) : _s(s) {}
    explicit A(std::string &&s) : _s(std::move(s)) {}
    ~A() = default;

    std::string _s;
};

results into:
t.h:5:13: warning: pass by value and use std::move [modernize-pass-by-value]
        explicit A(const std::string &s) : _s(s) {}

though in this case; when you have short string optimization and you already have a std::string available which can be copied, the const-ref can be preferred.

I would expect the warning not to be given when the by-value/by-rvalue-ref overload is available.

Full reproduction in attachment.

**Comment by carlosgalvezp** [comment]
No longer reproducible on trunk.
