### ISSUE TITLE
Access to a public template alias declaration that refers to friend's private nested type is not allowed.

### ISSUE THREAD

**Issue by de9ccd5f-6521-4b39-ab30-f4e04ed39258** [llvm/llvm-project#25708]
|  |  |
| --- | --- |
| Bugzilla Link | [25334](https://llvm.org/bz25334) |
| Version | 3.7 |
| OS | Linux |
| Attachments | [test code (also in the text)](https://user-images.githubusercontent.com/92601579/143752318-71f7ca20-13c3-4f8b-aef1-a802cddd9b53.gz) |
| CC | @DougGregor,@ecatmur |

## Extended Description 

The test case that fails is:

```cpp
struct FooAccessor
{
    template <typename T>
    using Foo = typename T::Foo;
};

class Type
{
    friend struct FooAccessor;
    
    using Foo = int;
};

int main()
{
    FooAccessor::Foo<Type> t;
}
```

The result is:

```console
$ clang++ test.cpp -std=c++11
test.cpp:4:5: error: 'Foo' is a private member of 'Type'
    using Foo = typename T::Foo;
    ^
test.cpp:11:11: note: implicitly declared private here
    using Foo = int;
          ^
1 error generated.
```

**Comment by shafik** [comment]
I think this should be allowed, wdyt @Endilll

**Comment by Endilll** [comment]
Seems like a bug to me. Can't find anything in [temp] to justify current Clang behavior.
