### ISSUE TITLE
false positive: unitilization after switch

### ISSUE THREAD

**Issue by Dushistov** [llvm/llvm-project#25711]
|  |  |
| --- | --- |
| Bugzilla Link | [25337](https://llvm.org/bz25337) |
| Version | 3.7 |
| OS | Linux |

## Extended Description 
For such code:
int f(unsigned val)
{
        int res;
        switch ((val & 1)) {
        case 0: res = 1; break;
        case 1: res = 2; break;
        }
        return res;
}

clang static analyser (3.7) return "Undefined or garbage value returned to caller", but this is not true because of (val & 1) can produce only 0 or 1, so all possible branches handled in switch, and res will contain not garbage.

**Comment by JOE1994** [comment]
Issue fixed as of `clang 18.1.0`:

* https://godbolt.org/z/7Ex8TbT4x
