### ISSUE TITLE
AlignConsecutiveAssignments misbehaves for special member functions

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#25729]
|  |  |
| --- | --- |
| Bugzilla Link | [25355](https://llvm.org/bz25355) |
| Version | trunk |
| OS | All |

## Extended Description 
The following code is aligned as:

struct A {
  constexpr A& operator=(A const&) = default;
  constexpr A(A&&)     = default;
};

which makes no sense. If anything it should probably be aligned at the "= default;":

struct A {
  A& operator=(A const&) = default;
  A(A&&)                 = default;
};

but I think that AlignConsecutiveAssignments should bail out in this case since nothing is being assigned here.

**Comment by dfrib** [comment]
@mkurdej Closed as per https://github.com/llvm/llvm-project/commit/480a1fab72f4e367a5986d572914d252c318431d?
