### ISSUE TITLE
Cannot build LLVM trunk OS X 10.10.5 | Xcode Version 7.1 (7B91b) | CMake 3.4.0-rc1

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25726]
|  |  |
| --- | --- |
| Bugzilla Link | [25352](https://llvm.org/bz25352) |
| Version | trunk |
| OS | All |
| Attachments | [CMakeError.log](https://user-images.githubusercontent.com/60944935/143752329-251f6a01-6776-454c-ad7f-92591efc9c16.gz), [CMakeOutput.log](https://user-images.githubusercontent.com/60944935/143752330-93ea682f-4600-4822-81ae-415c4041f758.gz), [CMakeError_SecondTry.log](https://user-images.githubusercontent.com/60944935/143752331-5cd44198-7bce-4f2c-8cbe-49084ed0526c.gz), [CMakeOutput_SecondTry.log](https://user-images.githubusercontent.com/60944935/143752332-1ee694c6-1988-4d1b-9531-d8931494552b.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @llvm-beanz,@jmolloy,@joker-eph |

## Extended Description 

Failed to build LLVM trunk following steps at http://llvm.org/docs/GettingStarted.html.
OS X 10.10.5
Xcode Version 7.1 (7B91b)
CMake 3.4.0-rc1

CMakeError.log, CMakeOutput.log attached

**Comment by arsenm** [comment]
Old build problem
