### ISSUE TITLE
Failed to build LLVM trunk | OS X 10.10.5 | Xcode Version 7.1

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25725]
|  |  |
| --- | --- |
| Bugzilla Link | [25351](https://llvm.org/bz25351) |
| Version | trunk |
| OS | MacOS X |
| Attachments | [CMakeOutput.log](https://user-images.githubusercontent.com/60944935/143752327-dfa6abd2-bd1d-4072-a84e-8be255ea3d88.gz), [CMakeError.log](https://user-images.githubusercontent.com/60944935/143752328-7bf478ba-ac5e-4578-8c86-f64ab024f857.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Failed to build LLVM trunk following steps at http://llvm.org/docs/GettingStarted.html.
OS X 10.10.5
Xcode Version 7.1 (7B91b)
CMake 3.4.0-rc1

CMakeError.log, CMakeOutput.log attached

**Comment by arsenm** [comment]
Old build problem
