### ISSUE TITLE
fail to build clang 3.7.0 (linking c-index-test)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25749]
|  |  |
| --- | --- |
| Bugzilla Link | [25375](https://llvm.org/bz25375) |
| Version | 3.7 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
....

[ 98%] Linking CXX shared library ../../lib/libclang.so
[ 98%] Built target libclang
[ 98%] Building C object tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o
[ 98%] Linking CXX executable ../../bin/c-index-test
../../lib/libclang.so.3.7: undefined reference to `std::error_category::error_category()@GLIBCXX_3.4.15'
../../lib/libclang.so.3.7: undefined reference to `std::error_category::default_error_condition(int) const@GLIBCXX_3.4.11'
../../lib/libclang.so.3.7: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string&&)@GLIBCXX_3.4.14'
../../lib/libclang.so.3.7: undefined reference to `std::__detail::_List_node_base::_M_unhook()@GLIBCXX_3.4.15'
../../lib/libclang.so.3.7: undefined reference to `std::__throw_bad_function_call()@GLIBCXX_3.4.14'
../../lib/libclang.so.3.7: undefined reference to `std::error_category::equivalent(int, std::error_condition const&) const@GLIBCXX_3.4.11'
../../lib/libclang.so.3.7: undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)@GLIBCXX_3.4.15'
../../lib/libclang.so.3.7: undefined reference to `std::generic_category()@GLIBCXX_3.4.11'
../../lib/libclang.so.3.7: undefined reference to `std::error_category::~error_category()@GLIBCXX_3.4.15'
../../lib/libclang.so.3.7: undefined reference to `std::string::operator=(std::string&&)@GLIBCXX_3.4.14'
../../lib/libclang.so.3.7: undefined reference to `std::ctype<char>::_M_widen_init() const@GLIBCXX_3.4.11'
../../lib/libclang.so.3.7: undefined reference to `std::__detail::_List_node_base::swap(std::__detail::_List_node_base&, std::__detail::_List_node_base&)@GLIBCXX_3.4.15'
../../lib/libclang.so.3.7: undefined reference to `std::system_category()@GLIBCXX_3.4.11'
../../lib/libclang.so.3.7: undefined reference to `std::error_category::equivalent(std::error_code const&, int) const@GLIBCXX_3.4.11'
../../lib/libclang.so.3.7: undefined reference to `std::__detail::_List_node_base::_M_transfer(std::__detail::_List_node_base*, std::__detail::_List_node_base*)@GLIBCXX_3.4.15'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/c-index-test] Error 1
make[1]: *** [tools/c-index-test/CMakeFiles/c-index-test.dir/all] Error 2
make: *** [all] Error 2

shestero@shestero-laptop:/media/database_/llvm/cfe-3.7.0.src/build$ g++ --version
g++ (GCC) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

--------
PS What is c-index-test tool for?
May be it's possible just to skip it?

**Comment by arsenm** [comment]
Old build issue
