### ISSUE TITLE
LLVM 3.7+ doesn't build on Illumos-based OSes (SmartOS, OpenIndiana, etc.)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25783]
|  |  |
| --- | --- |
| Bugzilla Link | [25409](https://llvm.org/bz25409) |
| Version | trunk |
| OS | Solaris |
| Reporter | LLVM Bugzilla Contributor |
| CC | @jclulow |

## Extended Description 
Hello,

Makefile.rules adds linker flags to strip dead symbols. For Solaris-like operating systems it has the following code:

    ifeq ($(HOST_OS),SunOS)
      LD.Flags += -Wl,-z -Wl,discard-unused=sections
      ...
    endif

According to an OpenIndiana developers mailing list [1] Illumos (the OpenSolaris fork) doesn't support the linker flag "discard-unused=sections" yet. It's available only on Oracle's Solaris 11.1 [2].

That makes it impossible to compile LLVM on Illumos derivatives, such as Joyent SmartOS, OmniOS, and others.

Both Illumos and Oracle Solaris support `-z ignore` flag, though, that is similar (but not equivalent) to `discard-unused=sections`. So this bug can be easily fixed by replacing the "discard-unused=sections" with "ignore".

If maintainers are OK with such a fix, I can submit a patch.

Thanks!

[1] http://openindiana.org/pipermail/oi-dev/2015-June/003696.html
[2] https://docs.oracle.com/cd/E26502_01/html/E26507/glmth.html

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
