### ISSUE TITLE
llvm configure error in allocator.h

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25816]
|  |  |
| --- | --- |
| Bugzilla Link | [25442](https://llvm.org/bz25442) |
| Version | 3.7 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
../llvm/configure --disable-optimized --enable-clang --disable-compiler-version-checks --disable-bindings CC=/usr/bin/clang CXX=/usr/bin/clang++

checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/clang accepts -g... yes
checking for /usr/bin/clang option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether /usr/bin/clang++ accepts -g... yes
checking how to run the C preprocessor... /usr/bin/clang -E
checking whether GCC or Clang is our host compiler... clang
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking target system type... i686-pc-linux-gnu
checking type of operating system we're going to host on... Linux
checking type of operating system we're going to target... Linux
checking target architecture... x86
checking optimization flags... -O3
checking for GNU make... make
checking whether ln -s works... yes
checking for nm... /usr/bin/nm
checking for cmp... /usr/bin/cmp
checking for cp... /bin/cp
checking for date... /bin/date
checking for find... /usr/bin/find
checking for grep... /bin/grep
checking for mkdir... /bin/mkdir
checking for mv... /bin/mv
checking for ranlib... ranlib
checking for ar... ar
checking for rm... /bin/rm
checking for sed... /bin/sed
checking for tar... /bin/tar
checking for pwd... /bin/pwd
checking for dot... /usr/bin/dot
checking for a BSD-compatible install... /usr/bin/install -c
checking for bzip2... /bin/bzip2
checking for cat... /bin/cat
checking for doxygen... /usr/bin/doxygen
checking for groff... /usr/bin/groff
checking for gzip... /bin/gzip
checking for pdfroff... /usr/bin/pdfroff
checking for zip... /usr/bin/zip
checking for go... no
checking for ocamlfind... /usr/bin/ocamlfind
checking for gas... no
checking for as... /usr/bin/as
checking for linker version... 2.22
checking for compiler -Wl,-R<path> option... yes
checking for compiler -rdynamic option... yes
checking for compiler -Wl,--version-script option... yes
checking for grep that handles long lines and -e... (cached) /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking tool compatibility... ok
checking optional compiler flags... -Wno-variadic-macros -Wno-missing-field-initializers  -Wno-uninitialized  -Wno-comment
checking for python... /usr/bin/python
checking for python >= 2.7... /usr/bin/python (2.7.3)
checking for sin in -lm... yes
checking for library containing dlopen... -ldl
checking for library containing clock_gettime... -lrt
checking for library containing setupterm... -ltinfo
checking for library containing el_init... no
checking for library containing mallinfo... none required
checking for pthread_mutex_init in -lpthread... yes
checking for library containing pthread_mutex_lock... none required
checking for library containing pthread_rwlock_init... none required
checking for library containing pthread_getspecific... none required
checking for compress2 in -lz... yes
checking for xml2-config... xml2-config
checking for libxml2 includes... -I/usr/include/libxml2
checking for xmlReadFile in -lxml2... yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for MAP_ANONYMOUS vs. MAP_ANON... yes
checking whether stat file-mode macros are broken... no
checking for sys/wait.h that is POSIX.1 compatible... yes
checking whether time.h and sys/time.h may both be included... yes
checking for cxxabi.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking link.h usability... yes
checking link.h presence... yes
checking for link.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking setjmp.h usability... yes
checking setjmp.h presence... yes
checking for setjmp.h... yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking for stdint.h... (cached) yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking for unistd.h... (cached) yes
checking utime.h usability... yes
checking utime.h presence... yes
checking for utime.h... yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/uio.h usability... yes
checking sys/uio.h presence... yes
checking for sys/uio.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking malloc/malloc.h usability... no
checking malloc/malloc.h presence... no
checking for malloc/malloc.h... no
checking mach/mach.h usability... no
checking mach/mach.h presence... no
checking for mach/mach.h... no
checking valgrind/valgrind.h usability... yes
checking valgrind/valgrind.h presence... yes
checking for valgrind/valgrind.h... yes
checking fenv.h usability... yes
checking fenv.h presence... yes
checking for fenv.h... yes
checking whether FE_ALL_EXCEPT is declared... yes
checking whether FE_INEXACT is declared... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking CrashReporterClient.h usability... no
checking CrashReporterClient.h presence... no
checking for CrashReporterClient.h... no
checking __crashreporter_info__... no
checking for HUGE_VAL sanity... yes
checking for pid_t... yes
checking for size_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for int64_t... yes
checking for uint64_t... yes
checking for backtrace... yes
checking for getcwd... yes
checking for getpagesize... yes
checking for getrusage... yes
checking for getrlimit... yes
checking for setrlimit... yes
checking for gettimeofday... yes
checking for isatty... yes
checking for mkdtemp... yes
checking for mkstemp... yes
checking for mktemp... yes
checking for posix_spawn... yes
checking for pread... yes
checking for realpath... yes
checking for sbrk... yes
checking for setrlimit... (cached) yes
checking for strerror... yes
checking for strerror_r... yes
checking for setenv... yes
checking for strtoll... yes
checking for strtoq... yes
checking for sysconf... yes
checking for malloc_zone_statistics... no
checking for setjmp... yes
checking for longjmp... yes
checking for sigsetjmp... no
checking for siglongjmp... yes
checking for writev... yes
checking for futimes... yes
checking for futimens... yes
checking if printf has the %a format character... yes
checking for srand48/lrand48/drand48 in <stdlib.h>... yes
checking whether arc4random is declared... no
checking whether strerror_s is declared... no
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for getpagesize... (cached) yes
checking for working mmap... yes
checking for mmap of files... yes
checking if /dev/zero is needed for mmap... no
checking for GCC atomic builtins... yes
checking for __dso_handle... yes
checking for compiler -fvisibility-inlines-hidden option... yes
configure: creating ./config.status
config.status: creating include/llvm/Config/Targets.def
config.status: creating include/llvm/Config/AsmPrinters.def
config.status: creating include/llvm/Config/AsmParsers.def
config.status: creating include/llvm/Config/Disassemblers.def
config.status: creating Makefile.config
config.status: creating llvm.spec
config.status: creating docs/doxygen.cfg
config.status: creating tools/clang/docs/doxygen.cfg
config.status: creating bindings/ocaml/llvm/META.llvm
config.status: creating include/llvm/Config/config.h
config.status: creating include/llvm/Config/llvm-config.h
config.status: creating include/llvm/Support/DataTypes.h
config.status: include/llvm/Support/DataTypes.h is unchanged
config.status: creating tools/clang/include/clang/Config/config.h
config.status: tools/clang/include/clang/Config/config.h is unchanged
config.status: executing setup commands
config.status: executing Makefile commands
config.status: executing Makefile.common commands
config.status: executing examples/Makefile commands
config.status: executing lib/Makefile commands
config.status: executing test/Makefile commands
config.status: executing test/Makefile.tests commands
config.status: executing unittests/Makefile commands
config.status: executing tools/Makefile commands
config.status: executing utils/Makefile commands
config.status: executing projects/Makefile commands
config.status: executing bindings/Makefile commands
config.status: executing bindings/ocaml/Makefile.ocaml commands
administrator@compit-ubuntu-01:~/somanew/build$ make
llvm[0]: Constructing LLVMBuild project information.
make[1]: Entering directory `/home/administrator/somanew/build/lib/Support'
llvm[1]: Compiling APFloat.cpp for Debug+Asserts build
In file included from /home/administrator/somanew/llvm/lib/Support/APFloat.cpp:17:
In file included from /home/administrator/somanew/llvm/include/llvm/ADT/FoldingSet.h:22:
/home/administrator/somanew/llvm/include/llvm/Support/Allocator.h:368:14: error: 
      use of undeclared identifier 'Begin'
      assert(Begin == (char*)alignAddr(Begin, alignOf<T>()));
             ^
/usr/include/assert.h:92:5: note: expanded from:
  ((expr)                                                               \
    ^
In file included from /home/administrator/somanew/llvm/lib/Support/APFloat.cpp:17:
In file included from /home/administrator/somanew/llvm/include/llvm/ADT/FoldingSet.h:22:
/home/administrator/somanew/llvm/include/llvm/Support/Allocator.h:368:40: error: 
      use of undeclared identifier 'Begin'
      assert(Begin == (char*)alignAddr(Begin, alignOf<T>()));
                                       ^
/usr/include/assert.h:92:5: note: expanded from:
  ((expr)                                                               \
    ^
In file included from /home/administrator/somanew/llvm/lib/Support/APFloat.cpp:17:
In file included from /home/administrator/somanew/llvm/include/llvm/ADT/FoldingSet.h:22:
/home/administrator/somanew/llvm/include/llvm/Support/Allocator.h:369:24: error: 
      use of undeclared identifier 'Begin'
      for (char *Ptr = Begin; Ptr + sizeof(T) <= End; Ptr += sizeof(T))
                       ^
/home/administrator/somanew/llvm/include/llvm/Support/Allocator.h:369:50: error: 
      use of undeclared identifier 'End'
      for (char *Ptr = Begin; Ptr + sizeof(T) <= End; Ptr += sizeof(T))
                                                 ^
0  libLLVM-3.0.so.1 0x40d5acc8
1  libLLVM-3.0.so.1 0x40d5b37c
2                   0x40022400 __kernel_sigreturn + 0
3  clang            0x0869f2e9 clang::Sema::DeduceAutoType(clang::TypeSourceInfo*, clang::Expr*, clang::TypeSourceInfo*&) + 73
4  clang            0x084ffc9d clang::Sema::AddInitializerToDecl(clang::Decl*, clang::Expr*, bool, bool) + 2477
5  clang            0x084489d7 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&) + 1623
6  clang            0x0844c634 clang::Parser::ParseDeclGroup(clang::Parser::ParsingDeclSpec&, unsigned int, bool, clang::SourceLocation*, clang::Parser::ForRangeInit*) + 1300
7  clang            0x08451c73 clang::Parser::ParseSimpleDeclaration(clang::ASTOwningVector<clang::Stmt*, 32u>&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, bool, clang::Parser::ForRangeInit*) + 803
8  clang            0x08451e92 clang::Parser::ParseDeclaration(clang::ASTOwningVector<clang::Stmt*, 32u>&, unsigned int, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) + 178
9  clang            0x084231dd clang::Parser::ParseStatementOrDeclaration(clang::ASTOwningVector<clang::Stmt*, 32u>&, bool) + 413
10 clang            0x08420484 clang::Parser::ParseCompoundStatementBody(bool) + 1652
11 clang            0x08420de4 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) + 164
12 clang            0x08440411 clang::Parser::ParseLexedMethodDef(clang::Parser::LexedMethod&) + 625
13 clang            0x08440e12 clang::Parser::LexedMethod::ParseLexedMethodDefs() + 34
14 clang            0x08440116 clang::Parser::ParseLexedMethodDefs(clang::Parser::ParsingClass&) + 134
15 clang            0x08461a00 clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, unsigned int, clang::Decl*) + 1472
16 clang            0x0846302d clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool) + 3341
17 clang            0x0844ffdd clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext) + 2237
18 clang            0x08428f07 clang::Parser::ParseSingleDeclarationAfterTemplate(unsigned int, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) + 775
19 clang            0x0842c8cf clang::Parser::ParseTemplateDeclarationOrSpecialization(unsigned int, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) + 639
20 clang            0x0842d3de clang::Parser::ParseDeclarationStartingWithTemplate(unsigned int, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) + 110
21 clang            0x08452084 clang::Parser::ParseDeclaration(clang::ASTOwningVector<clang::Stmt*, 32u>&, unsigned int, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) + 676
22 clang            0x0843a8ab clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::Parser::ParsingDeclSpec*) + 1163
23 clang            0x0845cb96 clang::Parser::ParseInnerNamespace(std::vector<clang::SourceLocation, std::allocator<clang::SourceLocation> >&, std::vector<clang::IdentifierInfo*, std::allocator<clang::IdentifierInfo*> >&, std::vector<clang::SourceLocation, std::allocator<clang::SourceLocation> >&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::Parser::BalancedDelimiterTracker&) + 454
24 clang            0x0845da29 clang::Parser::ParseNamespace(unsigned int, clang::SourceLocation&, clang::SourceLocation) + 2009
25 clang            0x084520c8 clang::Parser::ParseDeclaration(clang::ASTOwningVector<clang::Stmt*, 32u>&, unsigned int, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) + 744
26 clang            0x0843a8ab clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::Parser::ParsingDeclSpec*) + 1163
27 clang            0x0843b9c4 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) + 180
28 clang            0x0840e628 clang::ParseAST(clang::Sema&, bool) + 296
29 clang            0x081ec687 clang::ASTFrontendAction::ExecuteAction() + 103
30 clang            0x082e0f22 clang::CodeGenAction::ExecuteAction() + 66
31 clang            0x081ecfd3 clang::FrontendAction::Execute() + 275
32 clang            0x081d3895 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 325
33 clang            0x081bb526 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 1126
34 clang            0x081b3e30 cc1_main(char const**, char const**, char const*, void*) + 912
35 clang            0x081b13bd main + 653
36 libc.so.6        0x415034d3 __libc_start_main + 243
37 clang            0x081b394d
Stack dump:
0.	Program arguments: /usr/bin/clang -cc1 -triple i386-pc-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name APFloat.cpp -pic-level 2 -mdisable-fp-elim -masm-verbose -mconstructor-aliases -target-cpu pentium4 -target-linker-version 2.22 -momit-leaf-frame-pointer -g -ffunction-sections -fdata-sections -coverage-file /home/administrator/somanew/build/lib/Support/Debug+Asserts/APFloat.o -resource-dir /usr/bin/../lib/clang/3.0 -dependency-file /home/administrator/somanew/build/lib/Support/Debug+Asserts/APFloat.d.tmp -MP -MT /home/administrator/somanew/build/lib/Support/Debug+Asserts/APFloat.o -MT /home/administrator/somanew/build/lib/Support/Debug+Asserts/APFloat.d -D _DEBUG -D _GNU_SOURCE -D __STDC_CONSTANT_MACROS -D __STDC_FORMAT_MACROS -D __STDC_LIMIT_MACROS -I /home/administrator/somanew/build/include -I /home/administrator/somanew/build/lib/Support -I /home/administrator/somanew/llvm/include -I /home/administrator/somanew/llvm/lib/Support -fmodule-cache-path /var/tmp/clang-module-cache -internal-isystem /usr/include/c++/4.6 -internal-isystem /usr/include/c++/4.6/i686-linux-gnu -internal-isystem /usr/include/c++/4.6/backward -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/clang/3.0/include -internal-externc-isystem /usr/include/i686-linux-gnu -internal-externc-isystem /usr/include -Wcast-qual -Wall -W -Wno-unused-parameter -Wwrite-strings -Wno-uninitialized -Wno-missing-field-initializers -Wno-comment -std=c++11 -fconst-strings -fdeprecated-macro -ferror-limit 19 -fmessage-length 80 -fvisibility-inlines-hidden -fno-rtti -fgnu-runtime -fobjc-runtime-has-arc -fobjc-runtime-has-weak -fobjc-fragile-abi -fdiagnostics-show-option -fcolor-diagnostics -o /home/administrator/somanew/build/lib/Support/Debug+Asserts/APFloat.o -x c++ /home/administrator/somanew/llvm/lib/Support/APFloat.cpp 
1.	/home/administrator/somanew/llvm/include/llvm/Support/Allocator.h:371:6: current parser token ';'
2.	/home/administrator/somanew/llvm/include/llvm/Support/Allocator.h:34:1: parsing namespace 'llvm'
3.	/home/administrator/somanew/llvm/include/llvm/Support/Allocator.h:349:23: parsing struct/union/class body 'SpecificBumpPtrAllocator'
4.	/home/administrator/somanew/llvm/include/llvm/Support/Allocator.h:366:21: parsing function body 'DestroyAll'
5.	/home/administrator/somanew/llvm/include/llvm/Support/Allocator.h:366:21: in compound statement ('{}')
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: clang frontend command failed due to signal 2 (use -v to see invocation)
clang: note: diagnostic msg: Please submit a bug report to http://llvm.org/bugs/ and include command line arguments and all diagnostic information.
clang: note: diagnostic msg: Preprocessed source(s) are located at:
clang: note: diagnostic msg: /tmp/APFloat-q7KYul.ii
make[1]: *** [/home/administrator/somanew/build/lib/Support/Debug+Asserts/APFloat.o] Error 1
make[1]: Leaving directory `/home/administrator/somanew/build/lib/Support'
make: *** [all] Error 1

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
