### ISSUE TITLE
PPCJITInfo.cpp fails to compile on Power5 / AIX 5.3

### ISSUE THREAD

**Issue by 2bc7c7fd-1c4d-47d1-ae9c-4135a0a8cc8f** [llvm/llvm-project#2582]
|  |  |
| --- | --- |
| Bugzilla Link | [2210](https://llvm.org/bz2210) |
| Version | 2.2 |
| OS | AIX |
| Attachments | [PATCH to fix assembler errors](https://user-images.githubusercontent.com/92601866/143737828-66e7b525-0892-4ea1-bc8b-939e2a28c4b0.gz) |

## Extended Description 

llvm[3]: Compiling PPCJITInfo.cpp for Release build
Assembler:
/tmp/ccLdO0ra.s: line 4: 1252-016 The specified opcode or pseudo-op is not valid.
        Use supported instructions or pseudo-ops only.
make[3]: *** [/llvm-2.2/lib/Target/PowerPC/Release/PPCJITInfo.o] Error 1

I investigated and it is complaining about the .text lines. Also, once those are fixed, it can't resolve the registers by name. Adding .set lines mapping the registers to register numbers eliminates that problem as well. Generated assembler  from gcc outputs .csect text[PR], so I switched the .text lines to those.

I don't have any way of verifying this doesn't break anyone else, but the file builds clean for me now with this patch.

**Comment by arsenm** [comment]
Old build issue
