### ISSUE TITLE
Casts in array initializers sometimes have trailing spaces, but sometimes don't

### ISSUE THREAD

**Issue by EdSchouten** [llvm/llvm-project#25829]
|  |  |
| --- | --- |
| Bugzilla Link | [25455](https://llvm.org/bz25455) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Consider the following definition of the tzname array (part of <time.h>):

char *tzname[2] = {(char *)"UTC", (char *)"UTC"};

If I pull this statement through clang-format SVN revision 252153, I get:

char *tzname[2] = {(char *)"UTC", (char *) "UTC"};

Notice that there is no space between the cast and the string literal the first element in the initializer, whereas the second element does contain one.

**Comment by PatriotRossii** [comment]
Seems to be fixed. Given repro is formatting right with `clang-format version 15.0.0 (git@github.com:llvm/llvm-project.git 963192228b05e3bce86cf520e2bda5f069be9894)`

Input:

```
char *tzname[2] = {(char *)"UTC", (char *)"UTC"};
```

Output:

```
char *tzname[2] = {(char *)"UTC", (char *)"UTC"};
```

**Comment by rymiel** [comment]
Given that this was a bug somewhere around LLVM 3.8 in 2015 and can no longer be reproduced, I think it's safe to close
