### ISSUE TITLE
Abort with recursive C++14 polymorphic lambda

### ISSUE THREAD

**Issue by 066609a1-1e53-4cd0-b6cb-efe5048c5913** [llvm/llvm-project#25849]
|  |  |
| --- | --- |
| Bugzilla Link | [25475](https://llvm.org/bz25475) |
| Version | trunk |
| OS | Linux |
| Attachments | [Compiling the attached code crash the front-end.](https://user-images.githubusercontent.com/92601693/143752410-23869f90-6af2-4710-b36d-51bc93043452.gz) |

## Extended Description 

The following code produces an abort following an assertion failure in SemaTemplateInstantiate.cpp. I'm using 64-bit Ubuntu 15.04 (vivid), and clang version 3.8.0 (trunk 252425). GCC 4.9.2 compiles and runs.

clang++ -std=c++14 rec_lam_clang.cpp

int main(int argc, char *argv[])
{
  const auto a = [](const auto b, const auto x)
  {
    if (x)
      return;
    b(b,"dd");
  };
  a(a,1);

  return 0;
}

**Comment by Endilll** [comment]
Appears to be fixed in Clang 13: https://cexplorer.testlabs.pro/z/aqeGaa
