### ISSUE TITLE
AlignConsecutiveAssignments misbehaves for functions returning references

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#25863]
|  |  |
| --- | --- |
| Bugzilla Link | [25489](https://llvm.org/bz25489) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Given functions returning references:
```c++
static int a_v = 3;
static int a2_v = 4;

int& a() { return a_v; }
int& a2() { return b_v; }
```
one can assign through a function call as follows: 
```c++
a() = 4;
a2() = 5;
```

clang-format doesn't recognizes that the assignment operator=(..) is being used here, and thus doesn't align these assignments.

They should probably be aligned to: 
```c++
a()  = 4;
a2() = 5;
```

**Comment by rymiel** [comment]
Cannot reproduce with any version down to version 9, and I am unable to build any older versions; it is very likely this has been fixed sometime within the last 8 years.
