### ISSUE TITLE
[META] Make llvm-ar a drop-in replacement for BSD ar

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#25899]
|  |  |
| --- | --- |
| Bugzilla Link | [25525](https://llvm.org/bz25525) |
| Version | trunk |
| OS | Windows NT |
| Depends On | llvm/llvm-project#22086  |
| Reporter | LLVM Bugzilla Contributor |
| CC | @emaste |

## Extended Description 
Let me write this down here so I don't forget.
There are two major blockers:
1) Missing options, -c , -r, -D (description attached)

 -c      Suppress the informational message printed when a new archive is
         created using the -r and -q options.
(I think this one can be probably ignored).

  -r      Replace (add) the files specified by arguments file ... in the
             archive specified by argument archive, creating the archive if
             necessary.  Replacing existing members will not change the order
             of members within the archive.  If a file named in arguments
             file ... does not exist, existing members in the archive that
             match that name are not changed.  New files are added to the end
             of the archive unless one of the positioning options -a, -b or -i
             is specified.  The archive symbol table, if it exists, is updated
             to reflect the new state of the archive.

     -D      When used in combination with the -r or -q option, insert 0's
             instead of the real mtime, uid and gid values and 0644 instead of
             file mode from the members named by arguments file ....  This
             ensures that checksums on the resulting archives are reproducible
             when member contents are identical.  This option is enabled by
             default.  If multiple -D and -U options are specified on the com-
             mand line, the final one takes precedence.

2) Size. llvm-ar is currently 15MB (without debug) while BSD ar is currently 1MB. The size might be a concern if FreeBSD wants to ship with ar on embedded (e.g. ARM), so we should see if we can improve on this side.

**Comment by asl** [comment]
@emaste Can we close this?

**Comment by emaste** [comment]
I compared the options supported by BSD ar and llvm-ar - options that are supported by only one of the two, or have a different meaning:

BSD ar:
```
     -C      Prevent extracted files from replacing like-named files in the
             file system.
     -f      Synonymous with option -T.
     -j      This option is accepted but ignored.
     -M      Read and execute MRI librarian commands from standard input.  The
             commands understood by the ar utility are described in the
             section MRI Librarian Commands.
     -T      Use only the first fifteen characters of the archive member name
             or command line file name argument when naming archive members.
     -z      This option is accepted but ignored.
```

llvm-ar:
```
  [h] - display this help and exit
  [L] - add archive's contents
  [N] - use instance [count] of name
  [P] - use full names when matching (implied for thin archives)
  [T] - create a thin archive
```

So there are two that have some concern (and could not be implemented trivially): `-M` MRI librarian support, and the different use of `-T`. I would like to determine real-world impact of these still.

**Comment by emaste** [comment]
I requested an exp-run (experimental ports build) for FreeBSD with `-T` disabled in /usr/bin/ar: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=260523

If no ports are affected (or once those that are get fixed) I intend to disable `-T` in the built-in ar. I will also take a look at the remaining options (CfjMz) and if they're common to GNU ar as well propose at least reserving them in llvm-ar so they do not get used for a different purpose.

**Comment by emaste** [comment]
GNU ar, for reference:
```
  [f]          - truncate inserted file names
  [N]          - use instance [count] of name
  [O]          - display offsets of files in the archive
  [P]          - use full path names when matching
  [T]          - make a thin archive
```

As the only real conflict is with `-T` and as llvm-ar and GNU ar agree on the meaning of `-T` it seems the outstanding issue here is one to be resolved in FreeBSD. Closing.

**Comment by MaskRay** [comment]
I agree that the T conflict is unfortunate.

The Linux kernel has used the thin archive `-T` semantics since 2016:
 [kbuild: allow architectures to use thin archives instead of ld -r](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a5967db9af51a84f5e181600954714a9e4c69f1f). Some groups use llvm-ar along with other binutils replacements, we cannot immediately drop the current T semantics.

I have filed https://sourceware.org/bugzilla/show_bug.cgi?id=28759 and sent [[PATCH] ar: Add --thin for creating thin archives](https://sourceware.org/pipermail/binutils/2022-January/119250.html)

**Comment by emaste** [comment]
Agreed that using `--thin` will be best for portability.

We have made `-T` a silent nop in FreeBSD main (will be 14+) since the X/Open functionality is not particularly useful (regardless of what option is used to specify it).
