### ISSUE TITLE
[memcpyopt] fails to eliminate memcpy fed by sret

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#2590]
|  |  |
| --- | --- |
| Bugzilla Link | [2218](https://llvm.org/bz2218) |
| Version | unspecified |
| OS | Linux |
| Attachments | [testcase .ll](https://user-images.githubusercontent.com/60944935/143737834-a2a3af6f-f1b4-4219-8b5d-6784c93c9db6.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic |

## Extended Description 

Here's the testcase (also attached).  %pointless could be
eliminated since no use is ever made of it except as a
memcpy target.  %temporary could also be eliminated in
favour of passing %result directly to the @&#8203;initialize call.

define void @&#8203;f(i8* noalias sret  %result) {
entry:
        %temporary = alloca i8          ; <i8*> [#uses=3]
        %pointless = alloca i8          ; <i8*> [#uses=1]
        call void @&#8203;initialize( i8* noalias sret  %temporary )
        call void @&#8203;llvm.memcpy.i32( i8* %pointless, i8* %temporary, i32 1, i32 4 )
        call void @&#8203;llvm.memcpy.i32( i8* %result, i8* %temporary, i32 1, i32 4 )
        ret void
}

declare void @&#8203;initialize(i8* noalias sret )
declare void @&#8203;llvm.memcpy.i32(i8*, i8*, i32, i32) nounwind

**Comment by arsenm** [comment]
opt -O2 through modernized testcase removes all the memcpies:
```
define void @f(ptr noalias sret(i8) %result) {
entry:
  %temporary = alloca i8, align 1
  %pointless = alloca i8, align 1
  call void @initialize(ptr noalias sret(i8) %temporary)
  call void @llvm.memcpy.p0.p0.i32(ptr align 4 %pointless, ptr align 4 %temporary, i32 1, i1 false)
  call void @llvm.memcpy.p0.p0.i32(ptr align 4 %result, ptr align 4 %temporary, i32 1, i1 false)
  ret void
}

declare void @initialize(ptr noalias sret(i8))

; Function Attrs: nocallback nofree nounwind willreturn memory(argmem: readwrite)
declare void @llvm.memcpy.p0.p0.i32(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i32, i1 immarg) #0

attributes #0 = { nocallback nofree nounwind willreturn memory(argmem: readwrite) }


```
