### ISSUE TITLE
clang crashes on valid code with inlined assembly on x86_64-linux-gnu

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#25967]
|  |  |
| --- | --- |
| Bugzilla Link | [25593](https://llvm.org/bz25593) |
| Version | trunk |
| OS | All |
| CC | @RKSimon |

## Extended Description 
The current clang trunk crashes when compiling the following code on x86_64-linux-gnu.  

It also affects 3.2 and later, and thus a regression from 3.1. 

$ clang-trunk -v
clang version 3.8.0 (trunk 253495)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/tools/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.1.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.1.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clang-3.1 -c small.c
$    
$ clang-trunk -c small.c
clang: /tmp/llvm/lib/CodeGen/TwoAddressInstructionPass.cpp:1504: void (anonymous namespace)::TwoAddressInstructionPass::processTiedPairs(llvm::MachineInstr *, TiedPairList &, unsigned int &): Assertion `i == DstIdx || !MI->getOperand(i).isReg() || MI->getOperand(i).getReg() != RegA' failed.
#&#8203;0 0x0000000002f5aea8 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/clang-trunk/bin/clang+0x2f5aea8)
#&#8203;1 0x0000000002f5b617 (/usr/local/clang-trunk/bin/clang+0x2f5b617)
#&#8203;2 0x00007ff4dd3af340 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10340)
#&#8203;3 0x00007ff4dc34acc9 gsignal /build/buildd/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;4 0x00007ff4dc34e0d8 abort /build/buildd/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;5 0x00007ff4dc343b86 __assert_fail_base /build/buildd/eglibc-2.19/assert/assert.c:92:0
#&#8203;6 0x00007ff4dc343c32 (/lib/x86_64-linux-gnu/libc.so.6+0x2fc32)
#&#8203;7 0x000000000278457c (/usr/local/clang-trunk/bin/clang+0x278457c)
#&#8203;8 0x000000000267a9c9 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/usr/local/clang-trunk/bin/clang+0x267a9c9)
#&#8203;9 0x0000000002ea6ea4 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/local/clang-trunk/bin/clang+0x2ea6ea4)
#&#8203;10 0x0000000002ea70eb llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/local/clang-trunk/bin/clang+0x2ea70eb)
#&#8203;11 0x0000000002ea75b5 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/local/clang-trunk/bin/clang+0x2ea75b5)
#&#8203;12 0x00000000009f05bd clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::raw_pwrite_stream*) (/usr/local/clang-trunk/bin/clang+0x9f05bd)
#&#8203;13 0x00000000009d1838 (/usr/local/clang-trunk/bin/clang+0x9d1838)
#&#8203;14 0x0000000000c6a596 clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/clang-trunk/bin/clang+0xc6a596)
#&#8203;15 0x0000000000774f45 clang::FrontendAction::Execute() (/usr/local/clang-trunk/bin/clang+0x774f45)
#&#8203;16 0x0000000000740441 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/clang-trunk/bin/clang+0x740441)
#&#8203;17 0x000000000071f84e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/clang-trunk/bin/clang+0x71f84e)
#&#8203;18 0x00000000007158b8 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/clang-trunk/bin/clang+0x7158b8)
#&#8203;19 0x000000000071de43 main (/usr/local/clang-trunk/bin/clang+0x71de43)
#&#8203;20 0x00007ff4dc335ec5 __libc_start_main /build/buildd/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;21 0x0000000000715347 _start (/usr/local/clang-trunk/bin/clang+0x715347)
Stack dump:
0.	Program arguments: /usr/local/clang-trunk/bin/clang -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name small.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -target-linker-version 2.24 -dwarf-column-info -coverage-file /data2/small.c -resource-dir /usr/local/clang-trunk/bin/../lib/clang/3.8.0 -internal-isystem /usr/local/include -internal-isystem /usr/local/clang-trunk/bin/../lib/clang/3.8.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir /data2 -ferror-limit 19 -fmessage-length 111 -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -o small.o -x c small.c 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'small.c'.
4.	Running pass 'Two-Address instruction pass' on function '@foo'
clang: error: unable to execute command: Aborted (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.8.0 (trunk 253495)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/tools/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/small-02cc72.c
clang: note: diagnostic msg: /tmp/small-02cc72.sh
clang: note: diagnostic msg: 

********************
$ 

-----------------------------------

void foo ()
{
  register int a asm ("rsi"); 
  asm ("" : "=r" (a), "+r" (a));
}

**Comment by fhahn** [comment]
Clang produces the following error message now and does not crash: https://clang.godbolt.org/z/rM11oGK9M

```
source>:4:1: error: multiple outputs to hard register: rsi
asm ("" : "=r" (a), "+r" (a));
^
1 error generated.
Compiler returned: 1
```
