### ISSUE TITLE
crash during parsing of entangled alias template and variable template

### ISSUE THREAD

**Issue by tomilov** [llvm/llvm-project#25995]
|  |  |
| --- | --- |
| Bugzilla Link | [25621](https://llvm.org/bz25621) |
| Version | trunk |
| OS | Linux |
| Attachments | [soruce generated at crash](https://user-images.githubusercontent.com/92601325/143752502-7adf63ce-ad74-4bb4-a0c0-e77334dcec10.gz) |

## Extended Description 
Crash caused by missing typename keyword before and {} or () or ::value after mentioning of a alias template in a definition of a variable template.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 9: https://godbolt.org/z/Y6n8od8b3
Reduced by C-Reduce:
```cpp
struct Trans_NS_versatile_variant {
  template < typename >
  using index =  int>
}
struct variant {
  using variant_type = Trans_NS_versatile_variant ;
  using size_type = variant_type:template < typename variant_type, typename >
  constexpr size_type index = variant_type::variant_type::index<>;
namespace ast {
  struct empty  
  struct statement : variant 
  int empty{index< statement, ast:empty >
```
