### ISSUE TITLE
missing `__is_destructible()` type trait

### ISSUE THREAD

**Issue by tomilov** [llvm/llvm-project#26011]
|  |  |
| --- | --- |
| Bugzilla Link | [25637](https://llvm.org/bz25637) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Missed `__is_destructible()` type trait, but `__is_constructible()` present.

**Comment by Endilll** [comment]
`__is_destructible()` is supported without MS extensions since Clang 16: https://godbolt.org/z/a9YeM6TE1
