### ISSUE TITLE
r253905 polly ScopInfo.cpp fails to build on Mountain Lion with Xcode 5.1

### ISSUE THREAD

**Issue by 0e6f8740-1d2a-4afc-85fd-df25c3a603fd** [llvm/llvm-project#26047]
|  |  |
| --- | --- |
| Bugzilla Link | [25673](https://llvm.org/bz25673) |
| Version | unspecified |
| OS | All |
| Attachments | [build log (compressed)](https://user-images.githubusercontent.com/92601458/143752528-647a3bbe-3e15-4ce9-8e22-613cd03ecc1d.gz) |
| CC | @Meinersbur |

## Extended Description 

Recent polly fails to build on Mountain Lion with Xcode 5.1 (clang-503.0.35, based on LLVM 3.4svn):

In file included from .../trunk/tools/polly/lib/Analysis/ScopInfo.cpp:21:
In file included from .../trunk/tools/polly/include/polly/Options.h:17:
In file included from .../trunk/include/llvm/Support/CommandLine.h:23:
In file included from .../trunk/include/llvm/ADT/ArrayRef.h:13:
In file included from .../trunk/include/llvm/ADT/Hashing.h:49:
In file included from .../trunk/include/llvm/Support/Host.h:17:
In file included from .../trunk/include/llvm/ADT/StringMap.h:17:
In file included from .../trunk/include/llvm/ADT/StringRef.h:14:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/algorithm:626:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/utility:284:11: error: call to implicitly-deleted copy constructor of 'std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> >'
          second(__p.second)
          ^      ~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/memory:1641:31: note: in instantiation of member function 'std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > >::pair' requested here
            ::new((void*)__p) _Up(_VSTD::forward<_Args>(__args)...);
                              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/memory:1568:18: note: in instantiation of function template specialization 'std::__1::allocator<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > > >::construct<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > >, const std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > > &>' requested here
            {__a.construct(__p, _VSTD::forward<_Args>(__args)...);}
                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/memory:1449:14: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > > > >::__construct<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > >, const std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > > &>' requested here
            {__construct(__has_construct<allocator_type, pointer, _Args...>(),
             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/memory:1531:17: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > > > >::construct<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > >, const std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > > &>' requested here
                construct(__a, _VSTD::__to_raw_pointer(__end2-1), _VSTD::move_if_noexcept(*--__end1));
                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/vector:839:21: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > > > >::__construct_backward<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > > *>' requested here
    __alloc_traits::__construct_backward(this->__alloc(), this->__begin_, this->__end_, __v.__begin_);
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/vector:1528:5: note: in instantiation of member function 'std::__1::vector<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > >, std::__1::allocator<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > > > >::__swap_out_circular_buffer' requested here
    __swap_out_circular_buffer(__v);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/vector:1561:9: note: in instantiation of function template specialization 'std::__1::vector<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > >, std::__1::allocator<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > > > >::__push_back_slow_path<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > > >' requested here
        __push_back_slow_path(_VSTD::move(__x));
        ^
.../trunk/include/llvm/ADT/MapVector.h:80:14: note: in instantiation of member function 'std::__1::vector<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > >, std::__1::allocator<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > > > >::push_back' requested here
      Vector.push_back(std::make_pair(Key, ValueT()));
             ^
.../trunk/tools/polly/lib/Analysis/ScopInfo.cpp:2963:31: note: in instantiation of member function 'llvm::MapVector<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> >, llvm::DenseMap<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, unsigned int, llvm::DenseMapInfo<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int> >, llvm::detail::DenseMapPair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, unsigned int> >, std::__1::vector<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > >, std::__1::allocator<std::__1::pair<std::__1::pair<llvm::AssertingVH<const llvm::Value>, int>, std::__1::unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> > > > > >::operator[]' requested here
  auto &SAI = ScopArrayInfoMap[std::make_pair(BasePtr, Kind)];
                              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/memory:2510:31: note: copy constructor is implicitly deleted because 'unique_ptr<polly::ScopArrayInfo, std::__1::default_delete<polly::ScopArrayInfo> >' has a user-declared move constructor
    _LIBCPP_INLINE_VISIBILITY unique_ptr(unique_ptr&& __u) _NOEXCEPT
                              ^

**Comment by arsenm** [comment]
Old build issue
