### ISSUE TITLE
Assertion failed: (Loc.isValid() && "point of instantiation must be valid!"),

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26042]
|  |  |
| --- | --- |
| Bugzilla Link | [25668](https://llvm.org/bz25668) |
| Version | 3.7 |
| OS | FreeBSD |
| Attachments | [Compressed source](https://user-images.githubusercontent.com/60944935/143752523-4d405f3e-29c0-48b5-bc82-6e81dd8cdbaa.gz), [Run script](https://user-images.githubusercontent.com/60944935/143752524-7b55a8f1-ef59-4b5d-84a9-88135a40ea44.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hokein,@zahiraam |

## Extended Description 

Clang 3.7.0 from FreeBSD-current base system crashes on my code:

---
FreeBSD clang version 3.7.0 (tags/RELEASE_370/final 246257) 20150906
Target: x86_64-unknown-freebsd11.0
Thread model: posix
---
Assertion failed: (Loc.isValid() && "point of instantiation must be valid!"), function setPointOfInstantiation, file /usr/src/lib/clang/libclangsema/../../../contrib/llvm/tools/clang/include/clang/AST/DeclTemplate.h, line 1606.
CC: error: unable to execute command: Abort trap
CC: error: clang frontend command failed due to signal (use -v to see invocation)
FreeBSD clang version 3.7.0 (tags/RELEASE_370/final 246257) 20150906
Target: x86_64-unknown-freebsd11.0
Thread model: posix
CC: note: diagnostic msg: PLEASE submit a bug report to https://bugs.freebsd.org/submit/ and include the crash backtrace, preprocessed source, and associated run script.
CC: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
CC: note: diagnostic msg: /tmp/coins-a35b73.cpp
CC: note: diagnostic msg: /tmp/coins-a35b73.sh
CC: note: diagnostic msg: 

********************
*** Error code 254

Stop.
make[2]: stopped in /home/amdmi3/projects/software/hoverboard-sdl/build
*** Error code 1

Stop.
make[1]: stopped in /home/amdmi3/projects/software/hoverboard-sdl/build
*** Error code 1

Stop.
make: stopped in /home/amdmi3/projects/software/hoverboard-sdl/build
---

Complete source and run script attached.

**Comment by shafik** [comment]
Looks like this was fixed in clang-12: https://cexplorer.testlabs.pro/z/Mrvdx4
