### ISSUE TITLE
presence of non-const copy- constructor or assignment operator makes class non-trivial

### ISSUE THREAD

**Issue by tomilov** [llvm/llvm-project#26064]
|  |  |
| --- | --- |
| Bugzilla Link | [25690](https://llvm.org/bz25690) |
| Version | trunk |
| OS | Linux |
| CC | @comex,@DougGregor,@tomilov |

## Extended Description 
I use clang version 3.8.0 (trunk 253951). If I uncomment either commented line:

struct S
{
    constexpr S() = default;
    constexpr S(S const &) = default;
    //constexpr S(S &) = default;
    constexpr S(S &&) = default;
    S & operator = (S const &) = default;
    //S & operator = (S &) = default;
    S & operator = (S &&) = default;
    ~S() = default;
};

static_assert(std::is_trivially_default_constructible< S >{}, "!");
static_assert(std::is_trivially_copy_constructible< S >{}, "!");
static_assert(std::is_trivially_move_constructible< S >{}, "!");
static_assert(std::is_trivially_copy_assignable< S >{}, "!");
static_assert(std::is_trivially_move_assignable< S >{}, "!");
static_assert(std::is_trivially_destructible< S >{}, "!");

static_assert(std::is_trivial< S >{}, "!");

Then last static_assert is fired (but no one upper). I think the problem is in `__is_trivial*`/`__is_trivially*` built-in type traits. I use libc++ from trunk.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 15: https://godbolt.org/z/he7vKEnfc
