### ISSUE TITLE
Linux build breaks when both python 2 and python 3 are installed

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26118]
|  |  |
| --- | --- |
| Bugzilla Link | [25744](https://llvm.org/bz25744) |
| Version | unspecified |
| OS | Linux |
| Depends On | llvm/llvm-project#26175 llvm/llvm-project#26240  |
| Reporter | LLVM Bugzilla Contributor |
| CC | @tberghammer |

## Extended Description 
I'm not sure if this is new, but when both Python 2 and 3 are installed on Linux, the readline overload module has code that is not Python-3 compatible.  (I'm pretty sure I've run python 2/3 systems in the past and not hit this, so it might have crept in more recently).

I think we want to limit Linux to Python 2.x in the short term.  Later, we can iron out the Python 3 bits.  An alternative would be to fix up the basic wrapper code to work on both Python 2 and 3, but that's a bit more involved.  I prefer to handle that as a lower priority follow up step.

See initial report here:
https://bugs.swift.org/browse/SR-14

I'm still working on getting the exact repro environment, but calling it out now.

**Comment by DavidSpickett** [comment]
This appears to have been fixed. If the referenced issues didn't do that then us dropping Python2 support likely did.
