### ISSUE TITLE
Segmentation fault, possibly OpenMP related

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26113]
|  |  |
| --- | --- |
| Bugzilla Link | [25739](https://llvm.org/bz25739) |
| Version | 3.7 |
| OS | MacOS X |
| Attachments | [Crash backtrace](https://user-images.githubusercontent.com/60944935/143752552-166cf051-aac1-4df2-b1ec-dae183952f1f.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @alexey-bataev,@hfinkel |

## Extended Description 
When building PCL 1.7.2 on OSX, clang crashes (segmentation fault) when compiling poisson.cpp in the surface module.

OS: OSX El Capitan 10.11.1 
Compiler version: Clang 3.7.0 (binaries downloaded from website, but same results when using clang built from current trunk)

Trying to build: PCL 1.7.2

Dependencies used:
- Eigen 3.2.7 (latest version)
- Boost 1.59 (built with clang)
- Flann 1.8.4 (built with clang)

Attachment:
Zip file containing the following:
- Crash backtrace
- Preprocessed source
- Run script

Note: when trying to run it again copying the long program arguments (clang++ --cc1 ... ), if I remove the -fopenmp flag, it doesn't crash. But I do need OpenMP support.

**Comment by arsenm** [comment]
Old issue, reproducer is dead link
