### ISSUE TITLE
clang-format adds a break after parameter name when it's of a template type

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26139]
|  |  |
| --- | --- |
| Bugzilla Link | [25765](https://llvm.org/bz25765) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [.clang-format](https://user-images.githubusercontent.com/60944935/143752570-386fe22d-27b1-4d02-9e36-77bda4a64d04.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

I use Visual Studio plugin r254298.

Seems like clang-format doesn't like it when a function parameter that is passed by-value and is't type is a template.

Minimal example:

Source:
int functionNameLongEnoughForWrappingTheParameters(bool someFlag,
                                                   std::vector<uint8_t> buf);

Results with:
int functionNameLongEnoughForWrappingTheParameters(bool someFlag,
                                                   std::vector<uint8_t>
                                                      buf);

But:
int functionNameLongEnoughForWrappingTheParameters(bool someFlag,
                                                   std::vector<uint8_t>& buf);
stays as is (as expected).

More info:
Turning off AlwaysBreakTemplateDeclarations option doesn't help.
Happens with my custom configuration file (attached).
Doesn't happen with LLVM style.
Happens with Chromium style.

**Comment by rymiel** [comment]
I cannot reproduce with any version of clang-format down to clang-format 9, and I am unable to build any version older than that; probably safe to close?
