### ISSUE TITLE
No email with 'LGTM' sent when a revision is just marked as marked as "accepted"

### ISSUE THREAD

**Issue by chandlerc** [llvm/llvm-project#26145]
|  |  |
| --- | --- |
| Bugzilla Link | [25771](https://llvm.org/bz25771) |
| Version | unspecified |
| OS | All |

## Extended Description 
This causes folks to sometimes mark a revision accepted without adding an explicit comment, and as a consequence no email gets sent to the mailing list. This is important because folks watching the mailing list may not realize that there was an explicit LGTM given in the review.

**Comment by xgupta** [comment]
Still an issue, maybe llvm-iwg <https://github.com/llvm/llvm-iwg> can help.

**Comment by xgupta** [comment]
This is fixed.
