### ISSUE TITLE
Should clang-cl require compiler-rt?

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26142]
|  |  |
| --- | --- |
| Bugzilla Link | [25768](https://llvm.org/bz25768) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @rnk |

## Extended Description 
clang-cl uses MSVC includes and libraries. Yet it sometimes requires additional functions from compiler-rt, for example 

  __int128 i;
  i = i % 3;

requires _umodti3().

Is it OK for clang-cl to use functions from compiler-rt or should such usage be disabled?

**Comment by rnk** [comment]
This continues to come up, and I think we want the answer to be **yes**, we just need to make it happen.

**Comment by rnk** [comment]
Let's say this is a Duplicate of #25679.
