### ISSUE TITLE
clang-format shits the bed if it sees paretheses

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26166]
|  |  |
| --- | --- |
| Bugzilla Link | [25792](https://llvm.org/bz25792) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mydeveloperday |

## Extended Description 
Apologies; there is no clang-format component under tools in bugzilla. I looked under tools because that's where it is in the git repo.

clang-format attempts the following change, which is wrong because it removes the space before fromDate.
```
-    [calendar components:(NSYearCalendarUnit | NSMonthCalendarUnit | NSDayCalendarUnit) fromDate:earliestDate];
+    [calendar components:(NSYearCalendarUnit | NSMonthCalendarUnit | NSDayCalendarUnit)fromDate:earliestDate];
```

**Comment by mkurdej** [comment]
Cannot reproduce. Checked with clang-format starting with version 3.7 and style:
LLVM
`--style="{BasedOnStyle: LLVM, ColumnLimit: 0}"`
`--style="{BasedOnStyle: LLVM, ColumnLimit: 300}"`
