### ISSUE TITLE
Arch Linux fails to build python support

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26175]
|  |  |
| --- | --- |
| Bugzilla Link | [25801](https://llvm.org/bz25801) |
| Version | unspecified |
| OS | Linux |
| Blocks | llvm/llvm-project#26118  |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
There are possibly two issues here:

* python 2.x and 3.x, where we want to prefer python 2.x
* symbol definitions around Py_InitModule4, where ArchLinux x86_64 is needing it to be defined Py_InitModule4_64 whereas Ubuntu x86_64 doesn't require that.

Breaking this one out separately from a Gentoo one since the solutions for both are not necessarily one and the same.

**Comment by arsenm** [comment]
Old build issue
