### ISSUE TITLE
Using an autofdo derived sample profile causes a crash

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26174]
|  |  |
| --- | --- |
| Bugzilla Link | [25800](https://llvm.org/bz25800) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @yuanfang-chen |

## Extended Description 
The attached sample file as built with autofdo from  binary with LTO enabled so might have a problem Run the .sh to create

**Comment by AaronBallman** [comment]
No reproducer was attached, so there's not much we can do to try to reproduce the issue. Closing the bug, but if there's still a problem, please reopen with more details on how to reproduce.
