### ISSUE TITLE
ppc64 crashes when running ThreadPool unittests

### ISSUE THREAD

**Issue by joker-eph** [llvm/llvm-project#26203]
|  |  |
| --- | --- |
| Bugzilla Link | [25829](https://llvm.org/bz25829) |
| Version | trunk |
| OS | All |
| CC | @hfinkel |

## Extended Description 
See: http://lab.llvm.org:8011/builders/ppc64le-clang/builds/3301/steps/check-all_1/logs/stdio

Sample crash log looks like:

******************** TEST 'LLVM-Unit :: Support/Release+Asserts/SupportTests/ThreadPoolTest.Async' FAILED ********************
Note: Google Test filter = ThreadPoolTest.Async
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ThreadPoolTest
[ RUN      ] ThreadPoolTest.Async
0  SupportTests      0x00000000102bec34 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 116
1  SupportTests      0x00000000102bf1a0
2  SupportTests      0x00000000102bf614
3  linux-vdso64.so.1 0x00003fff8f370478 __kernel_sigtramp_rt64 + 0
4  SupportTests      0x00000000102d5288 void std::__once_call_impl<std::_Bind_simple<std::_Mem_fn<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)> (std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)> >() + 24
5  SupportTests      0x00000000102d5284 void std::__once_call_impl<std::_Bind_simple<std::_Mem_fn<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)> (std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)> >() + 20
6  libpthread.so.0   0x00003fff8f330fd0
7  SupportTests      0x00000000102d4b5c
8  SupportTests      0x00000000102d3e3c
9  libstdc++.so.6    0x00003fff8f0e5584
10 libpthread.so.0   0x00003fff8f327e70
11 libc.so.6         0x00003fff8eefa560 clone + 152

**Comment by Endilll** [comment]
Old unit test crash is most likely not relevant today.
