### ISSUE TITLE
Missing uchar.h header causes check-libcxx to fail on Redhat 6.5

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26209]
|  |  |
| --- | --- |
| Bugzilla Link | [25835](https://llvm.org/bz25835) |
| Version | 3.7 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
Afternoon,

On Redhat 6.5 uchar.h is in /usr/include/unicode

When running "make check-libcxx", there is a failure in the check:

The lit test: llvm/projects/libcxx/test/std/depr/depr.c.headers/uchar_h.pass.cpp
    fails because it can't find the header uchar.h as an include file.  

My dirty fix is to append unicode to uchar.h so line becomes:
#include <unicode/uchar.h>

  This passes the test, but I regret that I've not enough knowledge of the entire cmake/lit structure to know where is the best place to add an additional item to the INCLUDE_PATH list such that only the lit test is affected.  On the other hand, I guess the PATH may also need to be part of the libcxx header search path for the library.

I hope this is enough information for you to pursue addressing this issue.

Thanks.

**Comment by philnik777** [comment]
RedHat 6 is in it's ELS cycle and RedHat 7 provides the required functions. Given this I don't think it's worth fixing, so I'm closing this.
