### ISSUE TITLE
clang-cl: error when using #pragma pack with template structs

### ISSUE THREAD

**Issue by JaschaWetzel** [llvm/llvm-project#26206]
|  |  |
| --- | --- |
| Bugzilla Link | [25832](https://llvm.org/bz25832) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [reproducer for clang-cl error](https://user-images.githubusercontent.com/92601328/143752616-1c7c0d69-4494-4de3-877e-8e5bd0016066.gz), [reproducer](https://user-images.githubusercontent.com/92601328/143752618-d2db723d-67ec-44c1-94e3-75e1141f3cd9.gz) |
| CC | @rnk |

## Extended Description 

Using clang-cl from r255486.

cudafe++ which is part of nvcc, generates these #pragma pack instances in between template<> and struct statements.

With this out of the way, using nvcc with clang-cl as a host compiler successfully compiles. I didn't test the results yet since i have too many modules to manually fix the intermediate output files for all of them.

**Comment by AaronBallman** [comment]
This issue was fixed in Clang 3.9.0: https://godbolt.org/z/qqW7ehrrf
