### ISSUE TITLE
request: enable gnatlink to use -emit-llvm when compiling the binder generated main

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#2623]
|  |  |
| --- | --- |
| Bugzilla Link | [2251](https://llvm.org/bz2251) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 
Hi,

   When gnatmake is invoked with -emil-llvm, '-emit-llvm' is not recorded in the ali file.The reason for this is that gnatmake passes an invisible -gnatez argument to the compiler to indicate the end of the arguments that should be placed in the ali file.  So gcc gets invoked something like this:

  gcc -emit-llvm -gnatez -c file.adb

However gcc rewrites -emit-llvm into -emit-llvm-bc if used with -c.
Actually what it apparently does is turn the -c into -emit-llvm-bc.

This gives

  gcc -gnatez -emit-llvm-bc file.adb

Since -emit-llvm-bc is now after the -gnatez, it is no longer placed
in the ali file.

This means (for example) that gnatlink will not use -emit-llvm when
compiling the binder generated main; and that gnatmake -s will always
think there is a switch mismatch and recompile every time.

cheers,
Rod.

**Comment by arsenm** [comment]
I assume this was a drageonegg feature which is dead
