### ISSUE TITLE
Seg fault when compiling llvm and friends libcxx/algorithm

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26258]
|  |  |
| --- | --- |
| Bugzilla Link | [25884](https://llvm.org/bz25884) |
| Version | 3.7 |
| OS | Linux |
| Attachments | [Backtrace](https://user-images.githubusercontent.com/60944935/143752656-ec667c9d-a27d-4b43-8c8b-0c8b0006a786.gz), [run script](https://user-images.githubusercontent.com/60944935/143752657-1fc12bfa-bf74-4b9c-b84f-582103ec38de.gz), [Preprocessed Source 0](https://user-images.githubusercontent.com/60944935/143752658-fc34bcf4-46de-4f3a-b913-b8200b6bb8ff.gz), [Preprocessed Source 1](https://user-images.githubusercontent.com/60944935/143752659-efeb0892-6bcb-4e2e-93bb-e4c633dadec6.gz), [Preprocessed Source 2](https://user-images.githubusercontent.com/60944935/143752660-d837e8d4-9185-4285-a821-e5550c5bdc60.gz), [Preprocessed Source 3](https://user-images.githubusercontent.com/60944935/143752661-18fec101-d987-4252-a761-a8b32340382a.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 

When compiling llvm and friends from git sources clang seg faulted. See the attached backtrace, preprocessed source, and run script.

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.6 through 3.8 with assertions enabled.
