### ISSUE TITLE
bad machine code building fontforge

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26277]
|  |  |
| --- | --- |
| Bugzilla Link | [25903](https://llvm.org/bz25903) |
| Version | trunk |
| OS | FreeBSD |
| Attachments | [tar of crash reproducer and reduced bitcode](https://user-images.githubusercontent.com/60944935/143752670-e660ae86-2bae-4518-ac11-ea35552678b7.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@zygoloid |

## Extended Description 

Building fontforge 20150824_2 on FreeBSD 11-CURRENT i386 produces 3 bad machine code errors. See this log:

http://beefy3.nyi.freebsd.org/data/head-i386-default/p403994_s292455/logs/errors/fontforge-20150824_2.log

I've produced the error using trunk llvm+clang on FreeBSD 11-CURRENT amd64. The reduced case is in bugpoint-reduced-simplified.bc in the attached tar. Please let me know if you need more information.

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.6 through 3.8 with assertions enabled.
I checked both preprocessed source and its reduction.
