### ISSUE TITLE
Clang-format's WebKit style doesn't format `} else` properly

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26279]
|  |  |
| --- | --- |
| Bugzilla Link | [25905](https://llvm.org/bz25905) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
WebKit's style guide explicitly states that it wants the if statement connected to the else statement:

"An else statement should go on the same line as a preceding close brace if one is present, else it should line up with the if statement."

Right:

    if (condition) {
        ...
    } else {
        ...
    }

    if (condition)
        doSomething();
    else
        doSomethingElse();

    if (condition)
        doSomething();
    else {
        ...
    }

Wrong:

    if (condition) {
        ...
    }
    else {
        ...
    }

    if (condition) doSomething(); else doSomethingElse();

    if (condition) doSomething(); else {
        ...
    }

I plugged in the "Right:" part into clang-format, with the flag `-style=WebKit`, and the else statement was broken from the if:

    if (condition) {
        ...
    }
    else {
        ...
    }

BTW, the desired behavior is achieved with the style as Google or LLVM, so it is probably a configuration bug.

**Comment by mydeveloperday** [comment]
I believe this to be fixed (even before v8)

clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git fb7bea0a5a
b96b8ba3f73653fefea881bfeae350)

so I'm closing it, but please reopen if you think this is still an issue

```
$ clang-format -style=webkit test1.cpp
if (condition) {
    ...
} else {
    ...
}

if (condition)
    doSomething();
else
    doSomethingElse();

if (condition)
    doSomething();
else {
    ...
}
```
