### ISSUE TITLE
Cannot configure llvm with clang with cmake for visual studio

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26304]
|  |  |
| --- | --- |
| Bugzilla Link | [25930](https://llvm.org/bz25930) |
| Version | 3.7 |
| OS | Windows NT |
| Attachments | [error file produced by cmake](https://user-images.githubusercontent.com/60944935/143752677-77ddd2b0-2518-4dbc-a230-e67186c80dd1.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @bradking |

## Extended Description 

I followed the instructions from the Get Started page under development on clang.llvm.org in order to produce the Visual Studio solution file, but I cannot get llvm with clang to configure. I installed Visual Studio 2015 Community along with the Subversion plug-in, CMake 3.4, Python 2.7, and the GnuWin32 Tools. I used Subversion to check out llvm and clang using the folder heirarchy as instructed. I then created the build folder as told and CD'd to it and put in: cmake -G "Visual Studio 14 2015" ..\llvm

It tells me "configuring incomplete, errors occurred!"

How can I get this configured?

Attached is CMakeError.log.

**Comment by AaronBallman** [comment]
I don't think this issue is relevant any longer; we've adjusted our CMake considerably and Visual Studio now supports CMake directly, so it's not really possible to try to reproduce this.
