### ISSUE TITLE
PowerPC64 missing 16 byte atomic ops

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26307]
|  |  |
| --- | --- |
| Bugzilla Link | [25933](https://llvm.org/bz25933) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @echristo,@hfinkel,@vchuravy |

## Extended Description 
The following test case:

int main(void)
{
        __uint128_t x;
        __sync_val_compare_and_swap_16(&x, 1, 0);
}

works on gcc:

$ gcc -mcpu=power8 -O2 test.c

but fails on clang:

$ clang -mcpu=power8 -O2 test.c
/tmp/test-bae14f.o: In function `main':
test.c:(.text+0x34): undefined reference to `__sync_val_compare_and_swap_16'

**Comment by bzEq** [comment]
This should be fixed, https://godbolt.org/z/a7eYoeGcE.
