### ISSUE TITLE
Segfault when compiling simple C++14 test code

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26321]
|  |  |
| --- | --- |
| Bugzilla Link | [25947](https://llvm.org/bz25947) |
| Version | 3.7 |
| OS | Linux |
| Attachments | [Offending test file.](https://user-images.githubusercontent.com/60944935/143752692-0f1f2ff8-da2b-4630-862f-f8f3ded3f0de.gz), [Minimial version of the test script that reproduces the segfault](https://user-images.githubusercontent.com/60944935/143752693-97ab8824-dbb5-4ad5-8a5d-cbaa5bc37b8c.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 

The clang++ compiler version 3.7.0 (on GNU/Linux) segfaults when compiling the test code attached.

The segmentation fault can be reproduced with the following compilation script:

# Crash reproducer for clang version 3.7.0 (tags/RELEASE_370/final)
# Driver args: "--driver-mode=g++" "--std=c++14" "test.cc"
# Original command:  "/usr/bin/clang-3.7" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-emit-obj" "-mrelax-all" "-disable-free" "-disable-llvm-verifier" "-main-file-name" "test.cc" "-mrelocation-model" "static" "-mthread-model" "posix" "-mdisable-fp-elim" "-fmath-errno" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-fuse-init-array" "-target-cpu" "x86-64" "-dwarf-column-info" "-resource-dir" "/usr/bin/../lib/clang/3.7.0" "-internal-isystem" "/sbin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0" "-internal-isystem" "/sbin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/x86_64-unknown-linux-gnu" "-internal-isystem" "/sbin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/backward" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/bin/../lib/clang/3.7.0/include" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "--std=c++14" "-fdeprecated-macro" "-fdebug-compilation-dir" "/home/count0/stuff/workspace/graph-tool/build_clang_py3" "-ferror-limit" "19" "-fmessage-length" "264" "-mstackrealign" "-fobjc-runtime=gcc" "-fcxx-exceptions" "-fexceptions" "-fdiagnostics-show-option" "-fcolor-diagnostics" "-o" "/tmp/test-b0932d.o" "-x" "c++" "test.cc"
 "/usr/bin/clang-3.7" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-emit-obj" "-mrelax-all" "-disable-free" "-disable-llvm-verifier" "-main-file-name" "test.cc" "-mrelocation-model" "static" "-mthread-model" "posix" "-mdisable-fp-elim" "-fmath-errno" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-fuse-init-array" "-target-cpu" "x86-64" "-dwarf-column-info" "--std=c++14" "-fdeprecated-macro" "-ferror-limit" "19" "-fmessage-length" "264" "-mstackrealign" "-fobjc-runtime=gcc" "-fcxx-exceptions" "-fexceptions" "-fdiagnostics-show-option" "-fcolor-diagnostics" "-x" "c++" "test-ff3a26.cpp"

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.6 through 3.8 with assertions enabled: https://godbolt.org/z/3K56bsb7E
I also tried exact `cc1` arguments locally.
