### ISSUE TITLE
-Wliteral-conversion diagnostic with negative values could be improved

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#26338]
|  |  |
| --- | --- |
| Bugzilla Link | [25964](https://llvm.org/bz25964) |
| Version | trunk |
| OS | Windows NT |

## Extended Description 
Consider the following code:

void f() {
  bool b1 = -0.99f;
}

This produces the diagnostic: implicit conversion from 'float' to 'bool' changes value from 0.99 to true

While it's valid to drop the negative sign in the diagnostic (because that's not part of the literal value, but is instead an expression), it can still be a bit confusing to users. It might fit programmer's mental models more closely for the diagnostic to print -0.99 instead.

**Comment by xgupta** [comment]
This issue is now fix on trunk- https://godbolt.org/z/hYTPq8K6h. Closing.
