### ISSUE TITLE
Improve diagnostic messages in std::mutex and similar types.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26356]
|  |  |
| --- | --- |
| Bugzilla Link | [25982](https://llvm.org/bz25982) |
| Version | 3.4 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
Hi

Got this sporadic failed assertion on OSX with clang 3.4

Assertion failed: (ec == 0), function unlock, file /SourceCache/libcxx/libcxx-120/src/mutex.cpp, line 45.

How can logging be activated to get detailed context?

**Comment by philnik777** [comment]
ThreadSanitizer can be used to find problems with threading related functionality.
