### ISSUE TITLE
clang-format:  Assertion `getClient() && "DiagnosticClient not set!"' failed.

### ISSUE THREAD

**Issue by kcc** [llvm/llvm-project#26406]
|  |  |
| --- | --- |
| Bugzilla Link | [26032](https://llvm.org/bz26032) |
| Version | trunk |
| OS | Linux |

## Extended Description 
found by libFuzzer bot, see also bug 23052. 

%  echo /v9o0ypsDjs= | base64 --decode  | clang-format - 

tools/clang/lib/Basic/Diagnostic.cpp:363: bool clang::DiagnosticsEngine::EmitCurrentDiagnostic(bool): Assertion `getClient() && "DiagnosticClient not set!"' failed.

**Comment by mydeveloperday** [comment]
This issue I believe is closed by a92cf5a5a0cd01145f8db2ae09334a8b43a1271b (so closing this issue)
