### ISSUE TITLE
Crash on friend declarations dependant on class template parameters

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26478]
|  |  |
| --- | --- |
| Bugzilla Link | [26104](https://llvm.org/bz26104) |
| Version | 3.7 |
| OS | Linux |
| Attachments | [clang's output, the files the crash requested and a relevant code snippet](https://user-images.githubusercontent.com/60944935/143752769-a50383ef-fcc9-400f-935d-5a005704b879.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

While declaring some friend functions (operators specifically) I acidentally referenced the classes template parameters instead of the functions template parameters. This caused a crash the output of which you can find in the attached files, along with the relevant code snippet.

(Seems (based on 'Possible Duplicates') others have had similar problems but mostly resulting in errors not crashes...)

**Comment by Endilll** [comment]
Appears to be fixed in Clang 5: https://godbolt.org/z/4T1Eedc17
Reduced by C-Reduce:
```cpp
struct enable_if

template < typename KeyT, typename...  >
struct TypedUnion {
  template < typename KeyT2, typename OtherT, typename... KVMap2 >
  friend enable_if_t

  operator==(const TypedUnion< KeyT2, KVMap2... > &, const OtherT&)
    noexcept( KeyT::helper_tgeneric_equality}template < typename KeyT, typename OtherT, typename... KVMap >

enable_if_t operator==(const TypedUnion< KeyT, KVMap... > &, const OtherT &) struct  : TypedUnion< int > 
```
