### ISSUE TITLE
Assertion failed! -  Expression: !Init->isValueDependent()

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26500]
|  |  |
| --- | --- |
| Bugzilla Link | [26126](https://llvm.org/bz26126) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [Console log - ellcc invocation](https://user-images.githubusercontent.com/60944935/143752787-2b3d064f-56e5-4dc8-afaa-5577b48ede70.gz), [Preprocessed source](https://user-images.githubusercontent.com/60944935/143752788-876d2bd8-e251-4fe5-a836-e64bf76814af.gz), [Preprocessed header](https://user-images.githubusercontent.com/60944935/143752789-1c81039b-618d-4c49-9090-61aa740a00f0.gz), [Preprocessed header](https://user-images.githubusercontent.com/60944935/143752789-1c81039b-618d-4c49-9090-61aa740a00f0.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
Using CLANG 3.8.0 via ELLC.
Trying to compile a snippet using the Eigen3 library. 
Target: aarch64

I created this bug because I'm not sure if this duplicates https://llvm.org/bugs/show_bug.cgi?id=12779

**Comment by Endilll** [comment]
I can't reproduce it using Clang 3.7 or 3.8 with assertions enabled.
