### ISSUE TITLE
Crash due to wrong address space in load pre-splitting in SROA

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26528]
|  |  |
| --- | --- |
| Bugzilla Link | [26154](https://llvm.org/bz26154) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @chandlerc,@zmodem,@jrprice |

## Extended Description 
This is a copy-paste of an internal bug report; I might be able to conjure up a test case if necessary (it's GPU code with multiple address spaces), but the bug looks pretty straightforward. The reporter supplied a patch. The context is a load from addrspace(1) which is then stored to the stack, which SROA mishandles.

Report:

The problem appears to be that when pre-splitting the load, SROA seems to be using the address space of the store instead of the address space of the load. The function is SROA::presplitLoadsAndStores and the code is:

      auto *PartTy = Type::getIntNTy(Ty->getContext(), PartSize * 8);
      auto *PartPtrTy = PartTy->getPointerTo(SI->getPointerAddressSpace());
      …
        PLoad = IRB.CreateAlignedLoad(
            getAdjustedPtr(IRB, DL, LoadBasePtr,
                           APInt(DL.getPointerSizeInBits(), PartOffset),
                           PartPtrTy, LoadBasePtr->getName() + “.”),

diff --git a/lib/Transforms/Scalar/SROA.cpp b/lib/Transforms/Scalar/SROA.cpp
index 9c69b6c..48c907f 100644
--- a/lib/Transforms/Scalar/SROA.cpp
+++ b/lib/Transforms/Scalar/SROA.cpp
@@ -3919,7 +3919,8 @@ bool SROA::presplitLoadsAndStores(AllocaInst &AI, AllocaSlices &AS) {
         PLoad = IRB.CreateAlignedLoad(
             getAdjustedPtr(IRB, DL, LoadBasePtr,
                            APInt(DL.getPointerSizeInBits(), PartOffset),
-                           PartPtrTy, LoadBasePtr->getName() + "."),
+                           PartTy->getPointerTo(LI->getPointerAddressSpace()),
+                           LoadBasePtr->getName() + "."),
             getAdjustedAlignment(LI, PartOffset, DL), /*IsVolatile*/ false,
             LI->getName());
       }

**Comment by arsenm** [comment]
Attached testcase works. The code seems to have changed a lot and I don't see any defaulted getPointer* calls
