### ISSUE TITLE
modernize-use-nullptr replaces found issues several times

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26555]
|  |  |
| --- | --- |
| Bugzilla Link | [26181](https://llvm.org/bz26181) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Naive patch, tested and works](https://user-images.githubusercontent.com/60944935/143752818-0df97e36-5245-4fc4-a64c-6093635cdcfe.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hokein,@LegalizeAdulthood,@pepsiman |

## Extended Description 

When trying to run clang-tidy -checks=modernize-use-nullptr -fix-errors on the kodi.tv codebase I noticed that it replaced found NULL macros several times leading to code like int* p = nullptrptrptrptr;

I tracked this down to missing tracking of the replaced locations, attached is a naive patch(new to the code base)

Version: all sources checked out from github.com/llvm-mirror this week.

**Comment by carlosgalvezp** [comment]
No longer reproducible on trunk.
