### ISSUE TITLE
Assertion `QualifierLoc && "should be created for dependent qualifiers"' failed.

### ISSUE THREAD

**Issue by 991901f3-cc14-4404-b340-165691b62a58** [llvm/llvm-project#26577]
|  |  |
| --- | --- |
| Bugzilla Link | [26203](https://llvm.org/bz26203) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor |

## Extended Description 
consider:
template <typename T>
inline void f(T) {
    struct S {
        inline operator T() {}
        static void X() {
            &operator T;
        }
    };
}

int main() {
  f(3);
}

run with:
clang -cc1 -S -std=c++11 -x c++ -emit-llvm

**Comment by Endilll** [comment]
Appears to be fixed in Clang 10: https://cexplorer.testlabs.pro/z/GarYbs
