### ISSUE TITLE
clang-tidy looks for compilation database with `-- --emit-llvm -S`

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26583]
|  |  |
| --- | --- |
| Bugzilla Link | [26209](https://llvm.org/bz26209) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
$ cat foo.c
int main() {}
$ ./bin/clang-tidy foo.c -- foo.c
$ ./bin/clang-tidy foo.c -- --emit-llvm -S foo.c
LLVM ERROR: Could not auto-detect compilation database for file "foo.c"
No compilation database found in /Users/jroelofs/workdir/build or any parent directory
json-compilation-database: Error while opening JSON database: No such file or directory

It would be better if it didn't do so in this case.

**Comment by carlosgalvezp** [comment]
No longer reproducible in trunk.
