### ISSUE TITLE
Undiagnosed syntax error (not checking dead #elif conditions)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#2663]
|  |  |
| --- | --- |
| Bugzilla Link | [2291](https://llvm.org/bz2291) |
| Version | unspecified |
| OS | NetBSD |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lattner,@efriedma-quic |

## Extended Description 
#elif is not in a skipped group so the following must be diagnosed:

#if 1
#elif
#endif

**Comment by gwelymernans** [comment]
Neither recent GCCs or Clangs generate a diagnostic here. Is this still an issue that needs addressing?
