### ISSUE TITLE
google-readability-namespace-comments should remove trailing semicolon after namespace's closing '}'

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#26664]
|  |  |
| --- | --- |
| Bugzilla Link | [26290](https://llvm.org/bz26290) |
| Version | unspecified |
| OS | All |
| CC | @EugeneZelenko |

## Extended Description 
google-readability-namespace-comments turns this

namespace blink {
};

into this:

namespace blink
} // namespace blink;

It should strip that trailing ;

**Comment by EugeneZelenko** [comment]
Clang has `-Wextra-semi` and `-Wextra-semi-stmt` and they may be added to Clang-tidy command-line.
