### ISSUE TITLE
llvm.org bugzilla mails do not pass SPF verification @ gentoo.org

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26698]
|  |  |
| --- | --- |
| Bugzilla Link | [26324](https://llvm.org/bz26324) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @qcolombet,@tlattner |

## Extended Description 
Upon receiving e-mails from LLVM bugzilla, smtp.log states:

Jan 26 15:07:14 woodpecker postfix/smtpd[2439]: connect from llvmnew.cs.illinois.edu[192.17.58.186]
Jan 26 15:07:18 woodpecker postfix/smtpd[2439]: NOQUEUE: reject: RCPT from llvmnew.cs.illinois.edu[192.17.58.186]: 550 5.1.7 <www-data@llvm.org>: Sender address rejected: undeliverable address: host aspmx.l.google.com[74.125.28.26] said: 550-5.1.1 The email account that you tried to reach does not exist. Please try 550-5.1.1 double-checking the recipient's email address for typos or 550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1  https://support.google.com/mail/answer/6596 ud10si2548882pab.54 - gsmtp (in reply to RCPT TO command); from=<www-data@llvm.org> to=<mgorny@gentoo.org> proto=ESMTP helo=<llvm.org>
Jan 26 15:07:18 woodpecker postfix/smtpd[2439]: disconnect from llvmnew.cs.illinois.edu[192.17.58.186]

I'm not an expert on mail but I guess this means you're sending mail from address that is not known to your SMTP.

**Comment by jyknight** [comment]
Obsolete, bugzilla no longer used.
