### ISSUE TITLE
Instrument std::string with ASAN contiguous container annotations.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26754]
|  |  |
| --- | --- |
| Bugzilla Link | [26380](https://llvm.org/bz26380) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
__sanitizer_annotate_contiguous_container clearly mark used/unused portions of container storage and help catch out of bounds errors.

**Comment by AdvenamTacet** [comment]
There is a new, independent implementation, currently split into three revisions:
- Core implementation (long string and default allocator only) - https://reviews.llvm.org/D132769
- Turning on annotations for short strings - https://reviews.llvm.org/D147680
- Turn on annotations for all allocators (as in `std::vector` and `std::deque`) - https://reviews.llvm.org/D146214

That implementation is already somehow tested, but after that change it is required to build a separate libc++ dylibs with ASan, so we are waiting with landing for #33347 (we want to ship those dylibs with LLVM and we want driver to choose correct ones automatically, that should help with avoiding compatibility issues after that change).
While it is change "breaking ABI", ASan ABI is not stable.
