### ISSUE TITLE
clang++.exe: error: clang frontend command failed due to signal

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26760]
|  |  |
| --- | --- |
| Bugzilla Link | [26386](https://llvm.org/bz26386) |
| Version | 3.7 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@rnk |

## Extended Description 
0x08045D4B (0x08045D49 0x00000001 0x02CAE040 0x06E0E1A8) <unknown module>
0x02CAE409 (0x00000001 0x02CAE040 0x06E0E1A8 0x0000000A) <unknown module>
0x08045D49 (0x01000000 0x00000000 0xFC000000 0x00FFFFFF) <unknown module>
clang++.exe: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.7.0 (tags/RELEASE_370/final)
Target: i686-w64-windows-gnu
Thread model: posix
clang++.exe: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang++.exe: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++.exe: note: diagnostic msg: C:\msys64\tmp\win-c4b5c5.cpp
clang++.exe: note: diagnostic msg: C:\msys64\tmp\win-c4b5c5.sh
clang++.exe: note: diagnostic msg: 

********************
Makefile.mingw32:74: ...
make: *** [win.o] ...

**Comment by Endilll** [comment]
Links to preprocessed sources and shell script are dead.
Feel free to reopen if you can provide those.
