### ISSUE TITLE
Update cmake build on recent Haiku

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26779]
|  |  |
| --- | --- |
| Bugzilla Link | [26405](https://llvm.org/bz26405) |
| Version | trunk |
| OS | other |
| Attachments | [updates cmake build scripts to build on Haiku](https://user-images.githubusercontent.com/60944935/143752949-190bc823-5630-4c22-af88-b292261e5615.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

cmake build support on Haiku is lagging a bit.

This patch updates cmake build scripts to build on Haiku. It updates config.guess to a newer version which recognizes Haiku x86_64.
It should apply directly to trunk, please consider applying.

**Comment by kasperk81** [comment]
https://github.com/llvm/llvm-project/commit/9590c532b892743040b7a3ea8a8308098e1aff1e fixed this.
