### ISSUE TITLE
fatal error: error in backend: Broken function found, compilation aborted!

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26790]
|  |  |
| --- | --- |
| Bugzilla Link | [26416](https://llvm.org/bz26416) |
| Version | 3.6 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Error when trying to clone binary operations using the following pass:

if (auto *op = dyn_cast(&*I)) { auto temp = op->clone();}

favorite
	

Error when trying to clone binary operations using the following pass:

if (auto *op = dyn_cast(&*I)) { auto temp = op->clone();}

this gives the following error: fatal error: error in backend: Broken function found, compilation aborted! clang-3.6: error: clang frontend command failed with exit code 70 (use -v to see invocation) clang version 3.6.2 (tags/RELEASE_362/final) Target: x86_64-unknown-linux-gnu Thread model: posix clang-3.6: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script. clang-3.6: note: diagnostic msg:

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT: Preprocessed source(s) and associated run script(s) are located at: clang-3.6: note: diagnostic msg: /tmp/add1-260d76.c clang-3.6: note: diagnostic msg: /tmp/add1-260d76.sh clang-3.6: note: diagnostic msg:

**Comment by Endilll** [comment]
I don't think this is relevant anymore.
Feel free to reopen if you can reproduce it on trunk.
