### ISSUE TITLE
Problems running test-suite as part of an llvm build

### ISSUE THREAD

**Issue by hfinkel** [llvm/llvm-project#26796]
|  |  |
| --- | --- |
| Bugzilla Link | [26422](https://llvm.org/bz26422) |
| Version | trunk |
| OS | All |
| Attachments | [Verbose make output](https://user-images.githubusercontent.com/910929/143752954-e09d36f2-05ae-4d1d-833e-0459c903723a.gz), [Start of output showing](https://user-images.githubusercontent.com/910929/143752956-21677429-8e53-40ae-aa58-6101681cddfd.gz) |
| CC | @zmodem,@MatzeB,@rengolin |

## Extended Description 
When using cmake to generate makefiles, running:

  make -j<something large> test-suite

often fails with:

/bin/sh: /home/xxxxxxx/public/build/x86_64/llvm-stage1/test-suite bins/MultiSource/Applications/lua/generate_inputs.sh: No such file or directory
make[6]: *** [MultiSource/Applications/lua/generate_inputs.sh] Error 127
make[5]: *** [MultiSource/Applications/lua/CMakeFiles/lua_input.dir/all] Error 2
make[5]: *** Waiting for unfinished jobs....

I've observed no problems with a serial run.

**Comment by arsenm** [comment]
Old build issue
