### ISSUE TITLE
Add modernize-use-brace-initialization check

### ISSUE THREAD

**Issue by LegalizeAdulthood** [llvm/llvm-project#26832]
|  |  |
| --- | --- |
| Bugzilla Link | [26458](https://llvm.org/bz26458) |
| Version | unspecified |
| OS | Windows NT |

## Extended Description 
Add a check that transforms assignment initialization and constructor argument initialization to uniform brace initialization.

When should the check transform an initialization by assignment or constructor arguments into a brace initialization?

Herb Sutter proposes a style guide for preferring brace initialization here: http://herbsutter.com/elements-of-modern-c-style/

Opinions are likely to vary widely on where/when to prefer brace initialization among different teams.

Therefore the check may need a bunch of configuration parameters to specify which initializations should be preferred in brace style.

**Comment by carlosgalvezp** [comment]
Duplicate of #25337
