### ISSUE TITLE
-Wuninitialized warning on empty struct

### ISSUE THREAD

**Issue by hjl-tools** [llvm/llvm-project#26842]
|  |  |
| --- | --- |
| Bugzilla Link | [26468](https://llvm.org/bz26468) |
| Version | trunk |
| OS | Linux |

## Extended Description 
[hjl@gnu-6 empty-2]$ cat x.c
struct empty {};

struct empty
foo (void)
{
  struct empty s;
  return s;
}
[hjl@gnu-6 empty-2]$ make
/export/build/gnu/llvm-clang-bootstrap/stage1/build-x86_64-linux/bin/clang -m32 -S -O -Wall x.c
x.c:7:10: warning: variable 's' is uninitialized when used here
      [-Wuninitialized]
  return s;
         ^
x.c:6:3: note: variable 's' is declared here
  struct empty s;
  ^
1 warning generated.
[hjl@gnu-6 empty-2]$ 

Shouldn't empty struct be a special case here?

**Comment by AaronBallman** [comment]
We're also diagnosing the case where all the fields are unnamed bit-fields or zero-length bit-fields when we shouldn't be. GCC warns on none of:
```
struct One {};
struct Two { int : 0; };
struct Three { int : 12 };
```
https://godbolt.org/z/4E771zM5Y
