### ISSUE TITLE
[phabricator] Too easy to miss adding llvm-commits/cfe-commits to a review

### ISSUE THREAD

**Issue by silvasean** [llvm/llvm-project#26854]
|  |  |
| --- | --- |
| Bugzilla Link | [26480](https://llvm.org/bz26480) |
| Version | unspecified |
| OS | All |

## Extended Description 
Phabricator should reject patches (hopefully with a useful diagnostic) that don't subscribe either llvm-commits or cfe-commits.

**Comment by arsenm** [comment]
These now get auto added usually, plus phabricator's days are numbered
