### ISSUE TITLE
reference to std::cout causes crash

### ISSUE THREAD

**Issue by tomilov** [llvm/llvm-project#26861]
|  |  |
| --- | --- |
| Bugzilla Link | [26487](https://llvm.org/bz26487) |
| Version | 3.8 |
| OS | Linux |

## Extended Description 
Simple program (a.cpp):

#include <iostream>
int main()
{
  std::ostream & out_ = std::cout;
  return 0;
}

when compiled with flags:

clang++ -stdlib=libc++ a.cpp && ./a.out

crashed on execution with message:

Segmentation fault (core dumped)

Version of libc++ is svn r253593.
Version of clang is 3.8.0 trunk 253951.

**Comment by Endilll** [comment]
Seems like a broken Clang build.
Feel free to reopen if you can reproduce it with trunk.
