### ISSUE TITLE
clang-format option for space after operator

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26870]
|  |  |
| --- | --- |
| Bugzilla Link | [26496](https://llvm.org/bz26496) |
| Version | 3.8 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 
We have a weird coding standard where there are no spaces before and after operators. 
Eg.,

int variable=0;
if(variable==0) {
// Observe no space before and after ==
}

etc.

I couldn't find a similar bug/enhancement on this.

It would be nice to have this option or a workaround.

**Comment by mkurdej** [comment]
Duplicate of #19412.
