### ISSUE TITLE
google-readability-casting suggests casting when no casting is needed

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26901]
|  |  |
| --- | --- |
| Bugzilla Link | [26527](https://llvm.org/bz26527) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Testing the following three lines with clang-tidy will trigger a google-readability-casting warning:

	int i = 0;
	int *ip = &i;
	void *vp = (void *)ip;

The warning is:

	warning: C-style casts are discouraged. Use static_cast/const_cast/reinterpret_cast

However, no cast is needed here.

**Comment by carlosgalvezp** [comment]
On trunk, the check only warns about the third line, rightfully. The check's responsibility is to flag C-style casts and suggest an equivalent C++ style cast. It's not the responsibility of this check to remove unneeded casts. Please open a new ticket requesting a new check to implement that functionality if wanted.
