### ISSUE TITLE
performance-for-range-copy adding reference to POD

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26920]
|  |  |
| --- | --- |
| Bugzilla Link | [26546](https://llvm.org/bz26546) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Hi,
I am not sure if this check is being developed right now, but I found out that it doesn't work as it should for case like 

typedef int32_t NodeIDType;

const std::vector<NodeIDType>& fun();

for (NodeIDType ancestorID : fun() {
}

After running clang-tidy it adds const ref to ancestorID.
I can't attach preprocessed file right now - if this code won't be enough I find some time to prepare one.

**Comment by PiotrZSL** [comment]
This issue is already fixed, types trivial to copy are excluded.

**Comment by PiotrZSL** [comment]
Fixed already by f4fdc8aba00d8a8508af7ed86cab2dbc7f17ed08
