### ISSUE TITLE
check_clang_tidy.py doesn't report SEGV faults in the build log

### ISSUE THREAD

**Issue by LegalizeAdulthood** [llvm/llvm-project#26937]
|  |  |
| --- | --- |
| Bugzilla Link | [26563](https://llvm.org/bz26563) |
| Version | unspecified |
| OS | Windows NT |

## Extended Description 
When the buildbots fail because clang-tidy crashed in a release build, the check_clang_tidy.py script obfuscates this because the SEGV messages don't appear in the log.

Fix the script so this kind of failure is more self-evident.

**Comment by carlosgalvezp** [comment]
This does not seem to longer occur on trunk:

* The full crash stacktrace is printed.
* The message `subprocess.CalledProcessError: Command ['clang-tidy', ...]  died with <Signals.SIGSEGV: 11>.`, which is enough information to understand the program crashed with a segfault.
