### ISSUE TITLE
[GlobalISel] Generic MachineInstrs need a type but this increases the memory footprint of the related objects

### ISSUE THREAD

**Issue by qcolombet** [llvm/llvm-project#26950]
|  |  |
| --- | --- |
| Bugzilla Link | [26576](https://llvm.org/bz26576) |
| Version | trunk |
| OS | All |
| CC | @chandlerc,@lattner,@dwblaikie,@echristo,@qcolombet,@TNorthover |

## Extended Description 
As r260558, we added a Type * field to the MachineInstr class. This field is actually used only for generic MachineInstr and moreover, only during the instruction selection process.
In other words, we negatively impact the memory footprint of the whole backend pipeline for generic instructions that are used only at the beginning of such pipeline.

The question is then, is it possible to have that information in a union or
something?
My initial thought was that we could have a derived class GenericMachineInstr
with additional information, but in practice it makes little to no sense since
generic MachineInstrs are likely turned into non-generic ones by just switching
the opcode. In other words, we don't want to go through the process of creating
a new, non-generic MachineInstr, object each time we do this switch. The memory
benefit probably is not worth the extra compile time.

Another option would be to keep the type of the MachineInstr in a side table.
This would induce an extra indirection though.

That being said, when we have the basic pipeline lay down, we will be able to make measurements for the different option.

However, if you have ideas, please share!

**Comment by aemerson** [comment]
Closing this as an old issue not to be addressed.

**Comment by mehdi2021mp** [comment]
AC8E 115B F73E 2D8D 47FA 9908 E98E 9B2D 19C6 C8BD

**Comment by mehdi2021mp** [comment]
AC8E 115B F73E 2D8D 47FA 9908 E98E 9B2D 19C6 C8BD
