### ISSUE TITLE
crash on invalid with switch containing static local inside invalid function

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#26958]
|  |  |
| --- | --- |
| Bugzilla Link | [26584](https://llvm.org/bz26584) |
| Version | trunk |
| OS | Linux |

## Extended Description 
This causes Clang to crash / assert:

#define A B B B B B B B B B B 
#define B C C C C C C C C C C
#define C D D D D D D D D D D
#define D E E E E E E E E E E
#define E F F F F F F F F F F
#define F { int n = 0; (void)n; }
void f() { A }

class Foo {};

class Bar {
  void Baz();
};

namespace {
void Bar::Baz() {
  switch (0) static Foo foo;
  switch (0) static Foo foo;
  switch (0) static Foo foo;
}

The assertion is:

include/llvm/ADT/SmallVector.h:164: reference llvm::SmallVectorTemplateCommon<clang::SwitchStmt *, void>::back() [T = clang::SwitchStmt *]: Assertion `!empty()' failed.

within clang::Sema::ActOnFinishSwitchStmt(clang::SourceLocation, clang::Stmt*, clang::Stmt*).

**Comment by Endilll** [comment]
Appears to be fixed in Clang 7: https://cexplorer.testlabs.pro/z/WsEhc3
