### ISSUE TITLE
[LLDB][MIPS] TestInferiorAssert tests fail if section .gnu_debuglink is not available in libc.so.6

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#26966]
|  |  |
| --- | --- |
| Bugzilla Link | [26592](https://llvm.org/bz26592) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The loaded library (like libc.so) may not have its debug version available on the system (section .gnu_debuglink is not available). The debug version contains additional symbol information (such as __assert_perror_fail). Backtrace/function bound fails when symbol information is missing.

**Comment by DavidSpickett** [comment]
We no longer support Linux MIPS debug.

https://lldb.llvm.org/#platform-support

**Comment by Endilll** [comment]
@DavidSpickett Can you add `obsolete` label to issues you're closing for this reason?

**Comment by DavidSpickett** [comment]
> Can you add obsolete label to issues you're closing for this reason?

...sure let me remember find the list of the others I just closed.

**Comment by DavidSpickett** [comment]
Ah I see you did them, thanks!

I'll use the labels as well in future.

**Comment by Endilll** [comment]
Don't forget to close issues as not planned when it's appropriate as well!
