### ISSUE TITLE
Live range for register DBG_VALUEs extends across register mask clobbers

### ISSUE THREAD

**Issue by rnk** [llvm/llvm-project#26963]
|  |  |
| --- | --- |
| Bugzilla Link | [26589](https://llvm.org/bz26589) |
| Version | trunk |
| OS | Windows NT |
| CC | @adrian-prantl,@pogo59 |

## Extended Description 
Consider:

void __attribute__((noinline)) clobber() { asm volatile("xor %edi, %edi"); }
int main(int argc, char **argv) { clobber(); }

Clang emits dwarf that shows that argc is in EDI and it is live across the entire body of main. This is not true, it is clobbered by the call to clobber. Our current code only stops live ranges on direct register definitions, not call register masks.

Iterating over register mask clobbers should be enough to fix this.

**Comment by arsenm** [comment]
Linked patch is committed
