### ISSUE TITLE
clang-format treats multiplication as pointer dereference

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27024]
|  |  |
| --- | --- |
| Bugzilla Link | [26650](https://llvm.org/bz26650) |
| Version | 3.6 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Consider the following code:

    a=b*c;

clang-format correctly renders it as follows:

    a = b * c;

However, this breaks if a is a pointer which we must dereference:

    *a=b*c;

clang-format now renders this as:

    *a = b *c;

Note that it thinks we are dereferencing c, instead of multiplying by it!

**Comment by PatriotRossii** [comment]
All producers format well with `clang-format version 15.0.0 (git@github.com:llvm/llvm-project.git 325539bcbc9a26bd6dcbf25afa6d384604aa0a9b)` ([config.txt](https://github.com/llvm/llvm-project/files/9125328/config.txt))
