### ISSUE TITLE
Formatter eats space in front of attributes for `operator delete`

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#27037]
|  |  |
| --- | --- |
| Bugzilla Link | [26663](https://llvm.org/bz26663) |
| Version | trunk |
| OS | All |

## Extended Description 
This works:

$ echo 'void operator new(void* foo) ATTRIB;' | bin/clang-format -
`void operator new(void *foo) ATTRIB;`

This doesn't:

$ echo 'void operator delete(void* foo) ATTRIB;' | bin/clang-format -
`void operator delete(void *foo)ATTRIB;`

Note the missing space in front of ATTRIB.

**Comment by mydeveloperday** [comment]
Confirmed this is still an issue with clang-format v13

**Comment by mydeveloperday** [comment]
https://reviews.llvm.org/D116920
