### ISSUE TITLE
Implement the Concepts TS

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#27087]
|  |  |
| --- | --- |
| Bugzilla Link | [26713](https://llvm.org/bz26713) |
| Version | trunk |
| OS | All |
| CC | @ts826848 |

## Extended Description 
Implement the concepts TS:

P0121R0: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0121r0.pdf

**Comment by Quuxplusone** [comment]
I suspect it's no longer useful to keep this issue open.
