### ISSUE TITLE
braced initialization breaks lambda capture expressions formatting

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27146]
|  |  |
| --- | --- |
| Bugzilla Link | [26772](https://llvm.org/bz26772) |
| Version | 3.7 |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
SSCCE:

```
int break_me() {
  int x = 42;
  return int{[x = x]() {
    return x;
  }()};
}
```

Gets formatted as: 
```
int break_me() {
  int x = 42;
  return int{[x = x](){return x;
}
()
}
;
}
```

However, if you use the default initialization (i.e.: `int(...)`), it's formatted properly:

```
int break_me() {
  int x = 42;
  return int([x = x]() { return x; }());
}
```

**Comment by mkurdej** [comment]
Review: https://reviews.llvm.org/D116553.
