### ISSUE TITLE
Proposed check: modernize-use-emplace

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27140]
|  |  |
| --- | --- |
| Bugzilla Link | [26766](https://llvm.org/bz26766) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @EugeneZelenko |

## Extended Description 
doc version:
https://docs.google.com/document/d/1cl3yuKuDODQvRZMyXNsB3f31-Y13Dw72JelxLGxGoiw/edit

This check would look for cases, when inserting new element into STL container, but the element is constructed temporarily, or is constructed just to be moved:

std::vector<MyClass> v;
v.push_back(MyClass(21, 37));
// Could be replaced with
v.emplace_back(21, 37);

or situation like:
std::vector<std::pair<int,int> > v;
v.push_back(std::make_pair(21, 37));
// Could be replaced with
v.emplace_back(21, 37);

The second situation would work only for some known functions like std::make_pair.

**Comment by EugeneZelenko** [comment]
Implemented as `modernize-use-emplace`.
