### ISSUE TITLE
-pre-RA-sched=list-td doesn't preserve physical register dependencies

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#2716]
|  |  |
| --- | --- |
| Bugzilla Link | [2344](https://llvm.org/bz2344) |
| Version | unspecified |
| OS | All |
| Attachments | [Testcase showing the faulty behaviour](https://user-images.githubusercontent.com/60944935/143737913-c592b695-ad16-4cb8-9da1-dcfd07039e09.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@sunfishcode,@stoklund |

## Extended Description 

The attached file seems to cause list-td to generate bad code. Compiled with llc without list-td, it produces a fine result, but with list-td, the result seems wrong.

Excpected behaviour:
Since toBool is false in '@mystery' upon the call from main, all useless_... values should be irrelevant to the eventual outcome. Since notToBool is true, the code at the end should properly write '13' to %tmp, read the same value from %tmp again and return it after sign-extending it.

Actual behaviour:
Returns '13' when compiled with llc. Returns '-65' (presumably it's just a random value on the stack) when -pre-RA-sched=list-td is enabled.

**Comment by arsenm** [comment]
list-td was deleted in e2ff95e3279a043f9304951dce9b2955a4694ad9
