### ISSUE TITLE
[phabricator] Bogus "changed before commit".

### ISSUE THREAD

**Issue by silvasean** [llvm/llvm-project#27194]
|  |  |
| --- | --- |
| Bugzilla Link | [26820](https://llvm.org/bz26820) |
| Version | unspecified |
| OS | All |

## Extended Description 
Consider:

http://reviews.llvm.org/D17676?vs=49402&id=49666#toc

It seems like whatever is detecting what is "changed before commit" is diffing the patch on the one hand with something having compiler-rt/trunk/ prepended to all file paths. Obviously, this makes this "changed before commit" completely useless.

**Comment by JOE1994** [comment]
LLVM no longer uses Phabricator for code reviews
