### ISSUE TITLE
Assertion failure with -Wdocumentation

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27222]
|  |  |
| --- | --- |
| Bugzilla Link | [26848](https://llvm.org/bz26848) |
| Version | 3.7 |
| OS | Windows NT |
| Attachments | [source and output](https://user-images.githubusercontent.com/60944935/143753148-e7a221b4-2cc3-41d6-81e3-2858b8027fde.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zmodem,@mordante,@zygoloid,@Weverything |

## Extended Description 
Attached are all files that were requested in the output. Reproduce with -Weverything

**Comment by Endilll** [comment]
Appears to be fixed in Clang 8: https://cexplorer.testlabs.pro/z/Yjs9qK
