### ISSUE TITLE
clang doesn't warn about duplicated conditions

### ISSUE THREAD

**Issue by ahatanak** [llvm/llvm-project#27263]
|  |  |
| --- | --- |
| Bugzilla Link | [26889](https://llvm.org/bz26889) |
| Version | trunk |
| OS | All |

## Extended Description 
clang should warn that condition “a == 2” is duplicated in the following if-else-if chain:

int g1;

void foo1(int a) {
  if (a == 2)
    g1 = 32;
  else if (a == 3)
    g1 += 23;
  else if (a == 2)
    g1 -= 123;
}

gcc6 added a command line option -Wduplicated-cond to catch this.

**Comment by Quuxplusone** [comment]
Duplicate of #9565, which has already been resolved as a duplicate of #10324.
