### ISSUE TITLE
Clang/mingw-w64 crashes if configured with any optimization level other than -O0

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27274]
|  |  |
| --- | --- |
| Bugzilla Link | [26900](https://llvm.org/bz26900) |
| Version | 3.8 |
| OS | Windows XP |
| Attachments | [Files to reproduce the crash](https://user-images.githubusercontent.com/60944935/143753177-bb42813b-3cc9-4c27-8313-e49a959b15ee.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @rnk |

## Extended Description 

When compiling our project, clang crashes on release builds, but runs fine for debug. Attached the files to reproduce.

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.7 through 3.9 with assertions enabled.
This is not the first time we see an issue with MinGW builds that doesn't reproduce upstream.
