### ISSUE TITLE
std::allocator should use sized-delete

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27319]
|  |  |
| --- | --- |
| Bugzilla Link | [26945](https://llvm.org/bz26945) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @jyknight,@mclow |

## Extended Description 
This is the implementation of std::allocator<T>::deallocate from http://llvm.org/svn/llvm-project/libcxx/trunk/include/memory : 

    _LIBCPP_INLINE_VISIBILITY void deallocate(pointer __p, size_type) _NOEXCEPT
        {_VSTD::__deallocate((void*)__p);}

This is suboptimal for toolchains that implement an optimized sized-delete (that is, ::operator delete(void *ptr, size_t s).)

I think this should invoke 

_VSTD::__deallocate((void *)__p, size * sizeof(T))

or something similar (with the obvious implementation of sized __deallocate.)

**Comment by philnik777** [comment]
`std::allocator::deallocate` uses sized deallocation in ToT.
