### ISSUE TITLE
Crash at clang::Sema::ActOnCallExpr

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27318]
|  |  |
| --- | --- |
| Bugzilla Link | [26944](https://llvm.org/bz26944) |
| Version | 3.8 |
| OS | Linux |
| Attachments | [Shell script from crash reporter](https://user-images.githubusercontent.com/60944935/143753196-e9085cab-96c5-4f67-ac23-418701f1ed50.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
#include <map>
using namespace std;
int main() {
    __builtin_alloca(size) bbb;
}

clang++ -std=c++11 -c clang-crash.cpp -o clang-crash.o
(doesn't crash without "-std=c++11" flag)

clang-crash.cpp:8:27: error: expected ';' after expression
    __builtin_alloca(size) bbb;
                          ^
                          ;
#&#8203;0 0x000000000192f495 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/XXX/clang/3.8.0/bin/clang-3.8+0x192f495)
#&#8203;1 0x000000000192d6d6 llvm::sys::RunSignalHandlers() (/XXX/clang/3.8.0/bin/clang-3.8+0x192d6d6)
#&#8203;2 0x000000000192d8c5 SignalHandler(int) (/XXX/clang/3.8.0/bin/clang-3.8+0x192d8c5)
#&#8203;3 0x00002aaaab331810 __restore_rt (/lib64/libpthread.so.0+0xf810)
#&#8203;4 0x00000000025b48b2 clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool) (/XXX/clang/3.8.0/bin/clang-3.8+0x25b48b2)
#&#8203;5 0x000000000260d171 clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformCallExpr(clang::CallExpr*) (/XXX/clang/3.8.0/bin/clang-3.8+0x260d171)
#&#8203;6 0x00000000025fb81e clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformExpr(clang::Expr*) (/XXX/clang/3.8.0/bin/clang-3.8+0x25fb81e)
#&#8203;7 0x00000000025f9098 clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) (/XXX/clang/3.8.0/bin/clang-3.8+0x25f9098)
#&#8203;8 0x00000000025fa78e clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool, bool) (/XXX/clang/3.8.0/bin/clang-3.8+0x25fa78e)
#&#8203;9 0x00000000027052e0 clang::Sema::ActOnExprStmt(clang::ActionResult<clang::Expr*, true>) (/XXX/clang/3.8.0/bin/clang-3.8+0x27052e0)
#&#8203;10 0x00000000022c986d clang::Parser::ParseExprStatement() (/XXX/clang/3.8.0/bin/clang-3.8+0x22c986d)
#&#8203;11 0x00000000022c88e7 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedContsructsKind, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/XXX/clang/3.8.0/bin/clang-3.8+0x22c88e7)
#&#8203;12 0x00000000022c8c94 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedContsructsKind, clang::SourceLocation*) (/XXX/clang/3.8.0/bin/clang-3.8+0x22c8c94)
#&#8203;13 0x00000000022c58f9 clang::Parser::ParseCompoundStatementBody(bool) (/XXX/clang/3.8.0/bin/clang-3.8+0x22c58f9)
#&#8203;14 0x00000000022cd463 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/XXX/clang/3.8.0/bin/clang-3.8+0x22cd463)
#&#8203;15 0x000000000224b7dd clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/XXX/clang/3.8.0/bin/clang-3.8+0x224b7dd)
#&#8203;16 0x000000000226a200 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, unsigned int, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/XXX/clang/3.8.0/bin/clang-3.8+0x226a200)
#&#8203;17 0x00000000022475c1 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/XXX/clang/3.8.0/bin/clang-3.8+0x22475c1)
#&#8203;18 0x0000000002247c21 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) [clone .part.177] (/XXX/clang/3.8.0/bin/clang-3.8+0x2247c21)
#&#8203;19 0x0000000002247c4f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/XXX/clang/3.8.0/bin/clang-3.8+0x2247c4f)
#&#8203;20 0x000000000224df4f clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/XXX/clang/3.8.0/bin/clang-3.8+0x224df4f)
#&#8203;21 0x000000000224e840 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/XXX/clang/3.8.0/bin/clang-3.8+0x224e840)
#&#8203;22 0x00000000022433cb clang::ParseAST(clang::Sema&, bool, bool) (/XXX/clang/3.8.0/bin/clang-3.8+0x22433cb)
#&#8203;23 0x0000000001d08146 clang::FrontendAction::Execute() (/XXX/clang/3.8.0/bin/clang-3.8+0x1d08146)
#&#8203;24 0x0000000001ce35b6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/XXX/clang/3.8.0/bin/clang-3.8+0x1ce35b6)
#&#8203;25 0x0000000001d8a633 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/XXX/clang/3.8.0/bin/clang-3.8+0x1d8a633)
#&#8203;26 0x00000000008afd50 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/XXX/clang/3.8.0/bin/clang-3.8+0x8afd50)
#&#8203;27 0x000000000086551c main (/XXX/clang/3.8.0/bin/clang-3.8+0x86551c)
#&#8203;28 0x00002aaaabf0fc16 __libc_start_main (/lib64/libc.so.6+0x1ec16)
#&#8203;29 0x00000000008ad985 _start /usr/src/packages/BUILD/glibc-2.11.3/csu/../sysdeps/x86_64/elf/start.S:116:0
Stack dump:
0.	Program arguments: /XXX/clang/3.8.0/bin/clang-3.8 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name clang-crash.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -coverage-file /XXX/clang-crash.o -resource-dir /XXX/clang/3.8.0/bin/../lib/clang/3.8.0 -internal-isystem /usr/XXX/gcc/4.9.3/lib64/gcc/x86_64-suse-linux/4.9.3/../../../../include/c++/4.9.3 -internal-isystem /usr/XXX/gcc/4.9.3/lib64/gcc/x86_64-suse-linux/4.9.3/../../../../include/c++/4.9.3/x86_64-suse-linux -internal-isystem /usr/XXX/gcc/4.9.3/lib64/gcc/x86_64-suse-linux/4.9.3/../../../../include/c++/4.9.3/backward -internal-isystem /usr/local/include -internal-isystem /XXX/clang/3.8.0/bin/../lib/clang/3.8.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /XXX -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o clang-crash.o -x c++ clang-crash.cpp 
1.	clang-crash.cpp:8:28: current parser token 'bbb'
2.	clang-crash.cpp:7:12: parsing function body 'main'
3.	clang-crash.cpp:7:12: in compound statement ('{}')
clang-3.8: error: unable to execute command: Segmentation fault
clang-3.8: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.8.0 (http://llvm.org/git/clang.git 961db8de3198ee3aae87194fc02400531ce81a61) (http://llvm.org/git/llvm.git 6e961aa243f223ddb704ce708056238d7c1d7e24)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /XXX/clang/3.8.0/bin
clang-3.8: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3.8: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3.8: note: diagnostic msg: /tmp/clang-crash-627bf1.cpp
clang-3.8: note: diagnostic msg: /tmp/clang-crash-627bf1.sh
clang-3.8: note: diagnostic msg: 

********************

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.7 through 3.9: https://godbolt.org/z/99hecadas
