### ISSUE TITLE
InstCombine: frem X, (C ? 0 : Y) -> frem X, Y changes result

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27317]
|  |  |
| --- | --- |
| Bugzilla Link | [26943](https://llvm.org/bz26943) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @sanjoy |

## Extended Description 
The following program:

$ cat ../example.ll
define i1 @&#8203;main() {
  %w = call float @&#8203;foo(i1 1, float 17.0)
  %w2 = frem float 17.0, 42.0
  %rr = fcmp oeq float %w, %w2
  ret i1 %rr
}

define float @&#8203;foo(i1 %c, float %x) {
  %r = select i1 %c, float 0.0, float 42.0
  %rr = frem float %x, %r
  ret float %rr
}

gets optimized to:

$ bin/opt < ../example.ll -instcombine -S > ../example2.ll && cat ../example2.ll
; ModuleID = '<stdin>'

define i1 @&#8203;main() {
  %w = call float @&#8203;foo(i1 true, float 1.700000e+01)
  %rr = fcmp oeq float %w, 1.700000e+01
  ret i1 %rr
}

define float @&#8203;foo(i1 %c, float %x) {
  %rr = frem float %x, 4.200000e+01
  ret float %rr
}

The output of the original program and the optimized program is not the same:

$ bin/lli ../example.ll; echo $?
0
$ bin/lli ../example2.ll; echo $?
1

It seems like the optimization assumes that a frem %x, 0.0 results in undefined behavior but according to [0], the result should just be NaN and an error flag should be set. My understanding is that frem corresponds to C's fmod (see e.g. [1]), so it seems like the optimization is invalid.

[0] http://pubs.opengroup.org/onlinepubs/9699919799/functions/fmod.html
[1] http://llvm.org/docs/doxygen/html/classllvm_1_1APFloat.html#ab715d4ba706dd8dd1c7d51e43d067d4c

**Comment by msebor** [comment]
On Linux the latest trunk (16.0.0) produces the output below which matches expectations: the `select` instruction is preserved by all passes and `main`'s return  statement is folded to zero.  I don't see anything MacOS X specific in the test case so I'll go and close this on that basis even though I can't tell what change caused it.
```
$ opt -S -instcombine /build/tmp/llvm-pr27317.ll
opt -O2 -S llvm-pr27317.ll
; ModuleID = 'llvm-pr27317.ll'
source_filename = "llvm-pr27317.ll"

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define i1 @main() local_unnamed_addr #0 {
  ret i1 false
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define float @foo(i1 %c, float %x) local_unnamed_addr #0 {
  %r = select i1 %c, float 0.000000e+00, float 4.200000e+01
  %rr = frem float %x, %r
  ret float %rr
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind readnone willreturn }
```
