### ISSUE TITLE
FAIL: Clang :: CodeGenObjC/illegal-UTF8.m

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27324]
|  |  |
| --- | --- |
| Bugzilla Link | [26950](https://llvm.org/bz26950) |
| Version | 3.8 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Hi everyone,
make check-all fail on one test.
I call cmake and make with
$ gcc --version
gcc-4.8.real (Ubuntu/Linaro 4.8.4-2ubuntu1~14.04.1) 4.8.4
(same version for g++)
cmake is invoked with -DLLVM_TARGETS_TO_BUILD="ARM;X86" -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_CXX1Y=ON -DLLVM_ENABLE_RTTI=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release

[100%] Running all regression tests
lit.py: discovery.py:224: warning: input '/home/willy/local/build/llvm/release_38/build_odroid-willy-0_Release_RTTIOFF_SHAREDOFF/projects/compiler-rt/test/sanitizer_common/Unit' contained no tests
lit.py: lit.cfg:195: note: using clang: '/home/willy/local/build/llvm/release_38/build_odroid-willy-0_Release_RTTIOFF_SHAREDOFF/./bin/clang'
FAIL: Clang :: CodeGenObjC/illegal-UTF8.m (3584 of 26826)
******************** TEST 'Clang :: CodeGenObjC/illegal-UTF8.m' FAILED ********************
Script:
--
/home/willy/local/build/llvm/release_38/build_odroid-willy-0_Release_RTTIOFF_SHAREDOFF/./bin/clang  /home/willy/local/build/llvm/release_38/llvm/tools/clang/test/CodeGenObjC/illegal-UTF8.m -S -m64 -o -
--
Exit Code: 1

Command Output (stderr):
--
/home/willy/local/build/llvm/release_38/llvm/tools/clang/test/CodeGenObjC/illegal-UTF8.m:6:16: warning: input conversion stopped due to an input byte that does not belong to the input codeset UTF-8 [-WCFString-literal]
NSString *S = @"\xff\xff___WAIT___"; // expected-warning {{input conversion stopped due to an input byte that does not belong to the input codeset UTF-8}}
               ^~~~~~~~~~~~~~~~~~~~
error: unable to create target: 'No available targets are compatible with this triple, see -version for the available targets.'
1 warning and 1 error generated.

--

********************
Testing Time: 773.62s
********************
Failing Tests (1):
    Clang :: CodeGenObjC/illegal-UTF8.m

  Expected Passes    : 21828
  Expected Failures  : 113
  Unsupported Tests  : 4884
  Unexpected Failures: 1

1 warning(s) in tests.
make[3]: *** [CMakeFiles/check-all] Error 1

**Comment by cor3ntin** [comment]
This issue no longer seems relevant (all tests pass!)
