### ISSUE TITLE
[idea] Some sort of "layering analysis" / "layering check" feature.

### ISSUE THREAD

**Issue by silvasean** [llvm/llvm-project#27333]
|  |  |
| --- | --- |
| Bugzilla Link | [26959](https://llvm.org/bz26959) |
| Version | unspecified |
| OS | All |

## Extended Description 
The linker is in a unique position to analyze the layering of the input program.

I'm not sure what form this would take. Maybe some form of visualization. Maybe a diagnostic about recursive dependencies between object files. Maybe a diagnostic about recursive dependencies between archives.
Note that STT_FILE gives us a way to give useful information at the source file level (and if we want to go crazy then debug info can give more precision).

One interesting thing is this sort of "matrix" visualization of the dependencies: http://www.c2lang.org/docs/lld_architecture_20150126.png
(from thread "[LLVMdev] [lld] LLD's software architecture (jan 2015)")
This is a layering diagram for (atom) LLD itself, but the idea would be to provide users with this information about *their* program (but LLD can dogfood this, of course).

This is just an idea. I'm not sure if this is feasible to implement, but I think it would be a nice feature.
Once we can visualize this in a useful way, we can start looking at real projects to figure out what would is a realistic useful "check" that users may want and would not be too noisy.

**Comment by MaskRay** [comment]
For the actionable part of this issue:

`--warn-backrefs` is such a tool (https://maskray.me/blog/2021-06-13-dependency-related-linker-options#warn-backrefs)

`--cref` can dump a cross reference table and user programs can analyze the data.
