### ISSUE TITLE
no member named 'min' in namespace 'std'

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27351]
|  |  |
| --- | --- |
| Bugzilla Link | [26977](https://llvm.org/bz26977) |
| Version | 3.7 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
#include <stdexcept>
using std::min;
int main()
{
    return 0;
}

with -std=c++11 compile option, which passes on gcc 4.8, but fails on clang3.7:

main.cpp:2:12: error: no member named 'min' in namespace 'std'

using std::min;

      ~~~~~^

1 error generated.

**Comment by wheatman** [comment]
std::min is in header `<algorithm>` if you want to use it then include that header.  Depending on which version of the standard library you are using it may or may not be transitively included in `<stdexcept>`
