### ISSUE TITLE
Create modernize-enum-from-macros check

### ISSUE THREAD

**Issue by LegalizeAdulthood** [llvm/llvm-project#27408]
|  |  |
| --- | --- |
| Bugzilla Link | [27034](https://llvm.org/bz27034) |
| Version | unspecified |
| OS | All |
| CC | @EugeneZelenko,@Trass3r |

## Extended Description 
Consider the following code:

```
#define RED 0
#define GREEN 1
#define BLUE 2

struct RGBColor { /* ... */ };

extern float getChannel(const RGBColor &color, int channel);

RGBColor blue;
float red = getChannel(blue, RED);
```

The macros are being used as an enumeration.  This is best done by explicitly using an enumeration instead of int and a bunch of macros.

Create a check that identifies such macros disguised as enumerations and replaces them with an actual enum.

**Comment by LegalizeAdulthood** [comment]
@Trass3r What I settled on is literal tokens only, possibly with unary prefix `+`, `-` or `~`.

**Comment by Trass3r** [comment]
I see. Would be good to also cover these in the future:
* casts and parentheses
* bitwise operations for flags enums
* aliases

https://github.com/tpn/winsdk-10/blob/9b69fd26ac0c7d0b83d378dba01080e93349c2ed/Include/10.0.10240.0/um/WinBase.h#L403

> Macros must not be defined within a conditional compilation block

What's the rationale for this restriction? It's quite common:
https://github.com/tpn/winsdk-10/blob/9b69fd26ac0c7d0b83d378dba01080e93349c2ed/Include/10.0.10240.0/um/WinBase.h#L160
