### ISSUE TITLE
.h files are always parsed as C/ObjC

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27413]
|  |  |
| --- | --- |
| Bugzilla Link | [27039](https://llvm.org/bz27039) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
We implement google C++ code style and the style-guide states that header-files must always use .h as extension. But clang-tidy has no (documented) option to change this behavior of handling .h-files. These are always parsed as C-header files.

See: http://google.github.io/styleguide/cppguide.html#Header_Files

**Comment by EugeneZelenko** [comment]
I think Clang-tidy use model is reasonable explained here.
