### ISSUE TITLE
clang-format sorts includes even in files where it should be disabled completely

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27416]
|  |  |
| --- | --- |
| Bugzilla Link | [27042](https://llvm.org/bz27042) |
| Version | 11.0 |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mydeveloperday,@ptomato |

## Extended Description 
I have the following settings for third-party code:

---
DisableFormat: true
...

clang-format 3.8.0 ignores this option and still sorts includes, although it's expected to be disabled completely and that it won't change files with the above settings.

Now I have to explicitly disable sorting to workaround this issue.

---
DisableFormat: true
SortIncludes: false
...

**Comment by mydeveloperday** [comment]
This issue was resolved by 61dc0f2b593da149a4c0cea67819cd7bdbdd50b8 

which closed https://github.com/llvm/llvm-project/issues/34447 making this issue a duplicate

**Comment by DaanDeMeyer** [comment]
@mydeveloperday This is rather unfortunate as it prevents using clang-format only for include sorting and nothing else. Any suggestions on how to make clang-format work for only include sorting again without doing any other formatting?

**Comment by mydeveloperday** [comment]
> Any suggestions on how to make clang-format work for only include sorting again without doing any other formatting

I'm struggling to understand why this is a requirement we want to support. I mean you code should be formatted right? so running clang-format on your code should be a no op.

Unless of course you are saying... "Oh I don't use clang-format to format my code"... in which case I'm struggling to understand why you are here? why not just write an include sorter? do we need that extra complexity in clang-format?
