### ISSUE TITLE
SIGSEGV compiling LLVM IR with declared intrinsic

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27464]
|  |  |
| --- | --- |
| Bugzilla Link | [27090](https://llvm.org/bz27090) |
| Version | 3.7 |
| OS | Linux |
| Attachments | [clang's crash backtrace](https://user-images.githubusercontent.com/60944935/143753259-d8d1cb79-039f-4d8a-982f-8cb54cc4439e.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

The following LLVM IR, compiled with `clang crash.ll`, results in a segmentation fault.

Steps to reproduce:
1) Place this code in 'crash.ll':
    declare i64 @&#8203;llvm.read_register(metadata)
    define i32 @&#8203;main() {
      call i64 @&#8203;llvm.read_register(metadata !"rsp")
      ret i32 0
    }

2) Compile the code with `clang crash.ll`.
3) Clang segfaults, with the attached backtrace.

Clang should either fail compilation with an error or compilation should succeed.

Clang and llvm-libs were built on Fri 15 Jan 2016 and were downloaded precompiled from Arch Linux's repositories.

**Comment by arsenm** [comment]
Works fine now
