### ISSUE TITLE
error: clang frontend command failed due to signal (-O w/ c++11 atomic?)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27499]
|  |  |
| --- | --- |
| Bugzilla Link | [27125](https://llvm.org/bz27125) |
| Version | 3.8 |
| OS | Windows NT |
| Attachments | [Preprocessed source](https://user-images.githubusercontent.com/60944935/143753286-6032ee7a-8c31-4e47-bb18-1ebb7568d912.gz), [Associated run script](https://user-images.githubusercontent.com/60944935/143753287-6c38172d-223e-47b4-bd9d-018f6799d357.gz), [Original source file, so simple](https://user-images.githubusercontent.com/60944935/143753288-9eaf380a-8275-4a2c-9336-a2aa178c0610.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 

This time a minimal example with which Clang 3.8.0 crashes.

D:\msys64\mingw32\bin>clang++.exe -std=c++14 -O -c I:\test\bug\clang\atomic_bool.cpp
clang++.exe: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.8.0 (/repo/sources/clang 6abf213e6298d95a89b2f309473c1618f5b59d06) (/repo/sources/llvm 7afe4607ee8efbcd3bcf1e377
91d319326a908af)
Target: i686-w64-windows-gnu
Thread model: posix
InstalledDir: D:\msys64\mingw32\bin
clang++.exe: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preproce
ssed source, and associated run script.
clang++.exe: note: diagnostic msg:

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.7 through 3.9 with assertions enabled.
At this point it feels like `msys` build of Clang 3.8 was seriously screwed up.
