### ISSUE TITLE
IR for isfinite() could be improved

### ISSUE THREAD

**Issue by rotateright** [llvm/llvm-project#27519]
|  |  |
| --- | --- |
| Bugzilla Link | [27145](https://llvm.org/bz27145) |
| Version | trunk |
| OS | All |
| CC | @hfinkel |

## Extended Description 
#include <math.h>
#include <stdbool.h>

bool foo(float x) { return isfinite(x); }

$ ./clang -O1 isnan.c -S -o -  -emit-llvm
...
define zeroext i1 @&#8203;foo(float %x) #&#8203;0 {
entry:
  %cmp.i = fcmp ord float %x, 0.000000e+00
  %0 = tail call float @&#8203;llvm.fabs.f32(float %x) #&#8203;2
  %cmp1.i = fcmp une float %0, 0x7FF0000000000000
  %1 = and i1 %cmp.i, %cmp1.i
  ret i1 %1
}

Can't we use 'fcmp one' here to eliminate the first compare?
"one: ordered and not equal"

**Comment by arsenm** [comment]
I think this is fully solved, this is the codegen I get out of the original example:

```
foo:                                    # @foo
# %bb.0:                                # %entry
	andps	.LCPI0_0(%rip), %xmm0
	ucomiss	.LCPI0_1(%rip), %xmm0
	setne	%al
	retq

```
