### ISSUE TITLE
clang-3.8+ does not contain openmp headers and libs

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27528]
|  |  |
| --- | --- |
| Bugzilla Link | [27154](https://llvm.org/bz27154) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @sylvestre |

## Extended Description 
Unlike the pre-built binaries, the debian packages lack the openmp components, namely omp.h and libomp.so (and related symlinks).

**Comment by arsenm** [comment]
These are in the libomp-dev packages
