### ISSUE TITLE
Lowering long vector returns fails.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27535]
|  |  |
| --- | --- |
| Bugzilla Link | [27161](https://llvm.org/bz27161) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
To recreae: Compile the following with 
  llc -march=sparc <filename>.ll

```
define <8 x i8> @&#8203;fun8_2(<8 x i8> %a, <8 x i8> %b) {
entry:
  %and = and <8 x i8> %b, %a
  ret <8 x i8> %and
}
```

Expected result: Compiles well, returning some results on the stack as there are too many results (8 in the vector) to return in output registers.

Actual result: Fails. Tries to return all results in output registers and runs out of registers.

Important part of stack trace:

```
8  libLLVMCodeGen.so      0x00007f4ce1f5f47d llvm::CCState::AnalyzeReturn(llvm::SmallVectorImpl<llvm::ISD::OutputArg> const&, bool (*)(unsigned int, llvm::MVT, llvm::MVT, llvm::CCValAssign::LocInfo, llvm::ISD::ArgFlagsTy, llvm::CCState&)) + 683
9  libLLVMSparcCodeGen.so 0x00007f4ce40bcda4 llvm::SparcTargetLowering::LowerReturn_32(llvm::SDValue, unsigned int, bool, llvm::SmallVectorImpl<llvm::ISD::OutputArg> const&, llvm::SmallVectorImpl<llvm::SDValue> const&, llvm::SDLoc, llvm::SelectionDAG&) const + 222
```

**Comment by brad0** [comment]
@koachan Is just me or has this been resolved with ToT?

**Comment by brad0** [comment]
> I think it's this patch? https://reviews.llvm.org/D132465 I wasn't aware that it also affects this case too back then, I'm sorry.

Absolutely nothing to be sorry about. It's just good to try and clear out the bug reports. Take note of what issues have been resolved and what issues still affect the backend. Thank you for your effort.
