### ISSUE TITLE
VirtRegMap.cpp should not just remove an identity copy which also has a impl-def of a super-reg

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#27530]
|  |  |
| --- | --- |
| Bugzilla Link | [27156](https://llvm.org/bz27156) |
| Version | trunk |
| OS | Linux |
| Attachments | [clang input](https://user-images.githubusercontent.com/55128014/143753296-1b6f9e2e-9593-4338-b8aa-1a69d427a795.gz), [Patch to make COPY -> IMPLICIT_DEF when needed](https://user-images.githubusercontent.com/55128014/143753297-1d22a253-d743-4efc-96a6-aaff5e6114ae.gz) |
| CC | @hfinkel,@MatzeB |

## Extended Description 

VirtRegMap removes identity copies, but that leads to machine-verifier complaints if there is a def of a super reg as well.

I am not sure what the best fix is, but the patch attached seems to fix this by transforming the COPY to an IMPLICIT_DEF when there is a def of a super-reg. The patch assumes (arbitrarily) that there could only be one extra operand - not sure if this is always true...

./bin/clang -cc1 -triple s390x-ibm-linux -S -disable-free -main-file-name expr.c -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu z13 -momit-leaf-frame-pointer -v -dwarf-column-info -debugger-tuning=gdb  -O3 -ferror-limit 19 -fmessage-length 238 -funroll-loops -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o expr.s -x ir ./expr.bc -mllvm -verify-machineinstrs

**Comment by arsenm** [comment]
VirtRegRewriter::handleIdentityCopy replaces identity copies with implicit operands with KILL now
