### ISSUE TITLE
Infinite recursion during template instantiation

### ISSUE THREAD

**Issue by Weverything** [llvm/llvm-project#27547]
|  |  |
| --- | --- |
| Bugzilla Link | [27173](https://llvm.org/bz27173) |
| Version | trunk |
| OS | Linux |

## Extended Description 
$ cat bind.cc
template <typename _Tp> _Tp declval();

template <typename _Signature>
struct _Bind;

template <typename _Functor, typename T>
struct _Bind<_Functor(T)> {
  template <typename Arg, typename _Result = decltype(
                              declval<_Functor>()(declval<volatile T>()))>
  void operator()(Arg&& arg) {}
};

template <typename _Func, typename _Arg>
inline _Bind<_Func(_Arg)>
bind(_Func&& __f, _Arg&& __args) {}

struct A {
  template <typename T> A(T t);
};

template <typename T>
struct B {
  B(T&& arg);
};

template <typename T>
B<T> get_B();

void g(A a) {}

void test() {
  bind(g, get_B<A>());
}
$ clang -cc1 -std=c++11 bind.cc
Segmentation fault (core dumped)

From the backtrace, these 4 functions are repeated:
clang::Sema::PerformCopyInitialization
clang::Sema::GatherArgumentsForCall
clang::Sema::CompleteConstructorCall
clang::InitializationSequence::Perform

**Comment by Endilll** [comment]
Appears to be fixed in Clang 5: https://godbolt.org/z/8b4qWjhdW
