### ISSUE TITLE
mregparm=3 causes 'ran out of registers during register allocation'

### ISSUE THREAD

**Issue by blitz** [llvm/llvm-project#27550]
|  |  |
| --- | --- |
| Bugzilla Link | [27176](https://llvm.org/bz27176) |
| Version | 3.8 |
| OS | Linux |
| Attachments | [Preprocessed source that triggers the error](https://user-images.githubusercontent.com/95090691/143753306-05ff0e17-a754-4bc5-89df-fe083ebeaff9.gz), [clang command that triggers the error](https://user-images.githubusercontent.com/95090691/143753307-242712f0-5070-40ef-9c91-04811246f32d.gz) |
| CC | @DougGregor |

## Extended Description 

With the attached source the command below triggers a fatal error in clang (ran out of registers during register allocation). This was reproduced using clang 3.7 from Fedora 23 and clang 3.8 (Fedora 23 x86_64) from http://llvm.org/releases/download.html

% clang++ -mregparm=3 -m32 -std=c++11 -O1 -c crash.cpp

fatal error: error in backend: ran out of registers during register allocation
clang-3.8: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 3.8.0 (tags/RELEASE_380/final)
Target: i386-unknown-linux-gnu
Thread model: posix
InstalledDir: /tmp/clang+llvm-3.8.0-x86_64-fedora23/bin
clang-3.8: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3.8: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3.8: note: diagnostic msg: /tmp/crash-10f03c.cpp
clang-3.8: note: diagnostic msg: /tmp/crash-10f03c.sh
clang-3.8: note: diagnostic msg:

**Comment by nickdesaulniers** [comment]
thanks for the report. I was not able to reproduce with clang-15.
```
$ wget https://user-images.githubusercontent.com/95090691/143753306-05ff0e17-a754-4bc5-89df-fe083ebeaff9.gz
$ gunzip 143753306-05ff0e17-a754-4bc5-89df-fe083ebeaff9.gz
$ mv 143753306-05ff0e17-a754-4bc5-89df-fe083ebeaff9 crash.cpp
$ clang++ -mregparm=3 -m32 -std=c++11 -O2 -c crash.cpp
$ clang++ -mregparm=3 -m32 -std=c++11 -O1 -c crash.cpp
```
