### ISSUE TITLE
?: operator does not remove nullable

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27566]
|  |  |
| --- | --- |
| Bugzilla Link | [27192](https://llvm.org/bz27192) |
| Version | unspecified |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @madsravn |

## Extended Description 
The code:

#pragma clang diagnostic push
#pragma clang diagnostic warning "-Wnullable-to-nonnull-conversion"

void Test()
{
	NSDictionary* d = @{};
	CGPoint location = NSPointFromString( d[@"Nothing"] ?: @"{0,0}" );
	NSLog( @"location is %@", NSStringFromPoint(location) );
}

#pragma clang diagnostic pop

Reports the warning:

>warning: implicit conversion from nullable pointer 'id _Nullable' to non-nullable pointer type 'NSString * _Nonnull' [-Wnullable-to-nonnull-conversion]
>        CGPoint location = NSPointFromString( d[@"Nothing"] ?: @"{0,0}" );

The ?: operator should be smart enough to know that if the right hand is non-nullable then the entire expression is non-nullable.

**Comment by CodingMarkus** [comment]
This is a duplicate of #27058
