### ISSUE TITLE
indvars makes i1 indvar, LSR doesn't fix

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#2760]
|  |  |
| --- | --- |
| Bugzilla Link | [2388](https://llvm.org/bz2388) |
| Version | 1.0 |
| OS | All |
| CC | @atrick,@efriedma-quic,@sunfishcode |

## Extended Description 
Consider:
void foo(int x) {
  int i;
  _Bool b = x < 0;
  for (i = 0; i < 100000; ++i) {
    bar(i, b);

    b = !b;
  }
}

This compiles into this entertaining code:

bb:		; preds = %bb, %entry
	%i.0.reg2mem.0 = phi i32 [ 0, %entry ], [ %indvar.next, %bb ]		; <i32> [#uses=3]
	%indvar23 = trunc i32 %i.0.reg2mem.0 to i1		; <i1> [#uses=1]
	%b.0.in.reg2mem.0 = add i1 %indvar23, %tmp1		; <i1> [#uses=1]
	%tmp34 = zext i1 %b.0.in.reg2mem.0 to i32		; <i32> [#uses=1]

This is really bad.

**Comment by bwendling** [comment]
We now get this:

```llvm
define dso_local void @foo(i32 noundef %0) local_unnamed_addr #0 {
  %2 = icmp slt i32 %0, 0
  br label %3

3:                                                ; preds = %1, %3
  %4 = phi i1 [ %2, %1 ], [ %6, %3 ]
  %5 = phi i32 [ 0, %1 ], [ %7, %3 ]
  tail call void @bar(i32 noundef %5, i1 noundef zeroext %4) #2
  %6 = xor i1 %4, true
  %7 = add nuw nsw i32 %5, 1
  %8 = icmp eq i32 %7, 100000
  br i1 %8, label %9, label %3, !llvm.loop !5

9:                                                ; preds = %3
  ret void
}
```

which looks better, I think. Okay to close?
