### ISSUE TITLE
Missing Verifier check for debug info intrinsics that precede their SSA operands

### ISSUE THREAD

**Issue by 3f18db19-85d0-42b5-b58f-dbfbd8cbce51** [llvm/llvm-project#27647]
|  |  |
| --- | --- |
| Bugzilla Link | [27273](https://llvm.org/bz27273) |
| Version | trunk |
| OS | All |
| CC | @adrian-prantl |

## Extended Description 
r265631, reverted in r265637, uncovered a bug in -reassociate that breaks the order of @&#8203;llvm.dbg.value instructions compared to the SSA values they reference.

The current Verifier check doesn't look through the MetadataAsValue/LocalAsMetadata operands that debug info intrinsics use, such as `metadata i32 %x` in:
--
call void @&#8203;llvm.dbg.value(metadata i32 %x, ...)
%x = add i32 0, %arg
--

As a result, we need a hack in llvm::MapMetadata to return `!{}` instead of `null` when RF_IgnoreMissingLocals is turned off to prevent a crash in llvm::RemapInstruction.

We should add a verifier check; fix the bugs; write an upgrade to drop invalid instructions and commit the verifier check; and then fix llvm::MapMetadata to ignore RF_IgnoreMissingLocals (as r265631 tried to do).

There's a more complete write-up of the issue on llvm-commits (in the reply to r265631):

  http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20160404/345617.html

For now I'm going to push forward with a modified version of r265631 that documents what's going on.  I'll add a comment with the revision.

**Comment by arsenm** [comment]
Comments refer to pushed fixes
