### ISSUE TITLE
PowerPC: missing MC instruction analyzer

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27648]
|  |  |
| --- | --- |
| Bugzilla Link | [27274](https://llvm.org/bz27274) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@nemanjai |

## Extended Description 
I tried to get code coverage data for my LLVM fuzzing work and found that we are not implementing an MC instruction analyzer:

Error: no instruction analysis info for target powerpc64le-unknown-unknown

**Comment by chenzheng1030** [comment]
`no instruction analysis info for target powerpc64le-unknown-unknown` should be reported in https://github.com/llvm/llvm-project/blob/main/llvm/tools/sancov/sancov.cpp#L738-L740

There is an implementation of `PPCMCInstrAnalysis` in https://github.com/llvm/llvm-project/commit/b66328701a525d026a91b10df011712e5811319e, so the above error should not be reported any more.

For the functionality of sancov, welcome to report new issue if this is still an issue. I am closing this 7 years issue.
