### ISSUE TITLE
Wrong warning -Wunevaluated-expression for sizeof of VLA

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27687]
|  |  |
| --- | --- |
| Bugzilla Link | [27313](https://llvm.org/bz27313) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Compiling the program:

int main()
{
  int a[1][(0, 1)];
  int i = 0;
  sizeof a[i++];
}

gives such warnings:

$ clang -Wall example.c 
example.c:5:10: warning: expression with side effects has no effect in an unevaluated context [-Wunevaluated-expression]
  sizeof a[i++];
         ^
example.c:5:3: warning: expression result unused [-Wunused-value]
  sizeof a[i++];
  ^~~~~~~~~~~~~
2 warnings generated.

The first warning is wrong: `a` is VLA and a[i++] in sizeof is evaluated. The program is compiled just fine, only the warning is wrong.

**Comment by AaronBallman** [comment]
I cannot reproduce this behavior with Clang trunk: https://godbolt.org/z/575WTqGMn so closing as worksforme. If you can still reproduce the issue with the latest Clang, please reopen the issue with more details on how to reproduce.
