### ISSUE TITLE
Volatile stores of undef values are deleted

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27683]
|  |  |
| --- | --- |
| Bugzilla Link | [27309](https://llvm.org/bz27309) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @sanjoy |

## Extended Description 
All stores of undef values are deleted at the moment - including volatile stores:

define void @&#8203;f(i32 *%p) {
  store volatile i32 undef, i32 *%p;
  ret void;
}

Compiles to:

f: retq

In theory, the pointer could point to a hardware device where the store has some side-effects like increasing a queue pointer.  A driver that wants to write dummy data could reasonably store an undef and need it to be actually performed.

Bug found when browsing idly through the code, I don't actually have a real-world case for it.

**Comment by enferex** [comment]
Closed as fixed by https://github.com/llvm/llvm-project/commit/404071b059818ba51b6a832e5e09a93a4a8b579e
