### ISSUE TITLE
LiveRange not updated correctly in RegisterCoalescer

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#27705]
|  |  |
| --- | --- |
| Bugzilla Link | [27331](https://llvm.org/bz27331) |
| Version | trunk |
| OS | Linux |
| Attachments | [Failing test case](https://user-images.githubusercontent.com/143300/143753365-ba34412f-6606-4577-9f31-ad3e53309fe1.gz) |
| CC | @MatzeB,@qcolombet |

## Extended Description 

Compiling the attached test case results in a verifier error.  Command ot reproduce:

llc -mtriple=amdgcn--amdhsa -mcpu=fiji coalescer-bug.ll -verify-machineinstrs -o - 

qcolombet helped be debug this on IRC, and it appears the problem is that the live range information is not updated correctly during this transformation:

**BEFORE**
%vreg23 = 0
%vreg24:sub0 = %vreg23
%vreg24:sub1 = 2146435072
USE %vreg24
%vreg80:sub0 = %vreg23
%vreg80:sub1 = 1076494336
USE %vreg80

**AFTER**

%vreg80:sub0 = 0
%vreg80:sub1 = 2146435072
USE %vreg80
%vreg80:sub1 = 1076494336
USE %vreg80

**Comment by arsenm** [comment]
After a little modernization test works now
