### ISSUE TITLE
PointerAlignment: Right interaction with AlignConsecutiveDeclarations

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27727]
|  |  |
| --- | --- |
| Bugzilla Link | [27353](https://llvm.org/bz27353) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mkurdej |

## Extended Description 
Repro:
```
$ cat sample.c
int* a;
unsigned long long x;
double* b;
```
```
$ clang-format -style="{PointerAlignment: Right, AlignConsecutiveDeclarations: true}" sample.c
int *              a;
unsigned long long x;
double *           b;
```

Expected/desired output is:

```
int                *a;
unsigned long long  x;
double             *b;
```

**Comment by mydeveloperday** [comment]
Close by 3e333cc82e42e1e2ecc974d896489eebe1a5edc2
