### ISSUE TITLE
Formatter does not handle c++11 string literal prefix with stringize #

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27740]
|  |  |
| --- | --- |
| Bugzilla Link | [27366](https://llvm.org/bz27366) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
For L this was fixed in bug 17144, but u etc. are not fixed.

Example : 
`#define _u(str) u#str`
will become
`#define _u(str) u #str`
this breaks compiling.

the code 
```
 if (Right.is(tok::hash) && Left.is(tok::identifier) && Left.TokenText == "L")
     return false;
```
in TokenAnnotator.cpp takes only care of L not the other possible prefixes.
see https://msdn.microsoft.com/en-US/library/69ze775t.aspx

**Comment by mkurdej** [comment]
Review: https://reviews.llvm.org/D115938
