### ISSUE TITLE
combining modernize-pass-by-value and modernize-use-default generates bad cpp code

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27762]
|  |  |
| --- | --- |
| Bugzilla Link | [27388](https://llvm.org/bz27388) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
version > 3.8 (latest sync : git-svn-id: https://llvm.org/svn/llvm-project/clang-tools-extra/trunk@266265 91177308-0d34-0410-b5e6-96231b3b80d8)

On This code :

// tidy-bug.cpp
class Base {};

class Derived : public Base {
public:
  Derived(const Derived &src);
};
Derived::Derived(const Derived &src) : Base(src) {}

Executing :

clang-tidy -checks=modernize-* tidy-bug.cpp -fix

Reports :

2 warnings generated.
/mypath/tidy-bug.cpp:7:1: warning: use '= default' to define a trivial copy constructor [modernize-use-default]
Derived::Derived(const Derived &src) : Base(src) {}
^
                                     = default;
/mypath/tidy-bug.cpp:7:38: note: FIX-IT applied suggested code changes
Derived::Derived(const Derived &src) : Base(src) {}
                                     ^
/mypath/tidy-bug.cpp:7:18: warning: pass by value and use std::move [modernize-pass-by-value]
Derived::Derived(const Derived &src) : Base(src) {}
                 ^
/mypath/tidy-bug.cpp:1:1: note: FIX-IT applied suggested code changes
class Base {};
^
/mypath/tidy-bug.cpp:5:11: note: FIX-IT applied suggested code changes
  Derived(const Derived &src);
          ^
/mypath/tidy-bug.cpp:7:18: note: FIX-IT applied suggested code changes
Derived::Derived(const Derived &src) : Base(src) {}
                 ^
/mypath/tidy-bug.cpp:7:45: note: FIX-IT applied suggested code changes
Derived::Derived(const Derived &src) : Base(src) {}
                                            ^
/mypath/tidy-bug.cpp:7:48: note: FIX-IT applied suggested code changes
Derived::Derived(const Derived &src) : Base(src) {}
                                               ^
clang-tidy applied 6 of 6 suggested fixes.

And generates bad cpp code :

#include <utility>

class Base {};

class Derived : public Base {
public:
  Derived(Derived src);
};
Derived::Derived(Derived src) = dstd::move(efa)ult;

**Comment by carlosgalvezp** [comment]
No longer reproducible on trunk.
