### ISSUE TITLE
compile error: reference to ‘Module’ is ambiguous

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27791]
|  |  |
| --- | --- |
| Bugzilla Link | [27417](https://llvm.org/bz27417) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I am on Ubuntu 14.04, g++/gcc 4.9.3. It was able to compile before, it doesn't compile anymore after pulling the new changes with svn update.

How to duplicate the error: basically follow http://llvm.org/docs/GettingStarted.html, negate all optional, -DCMAKE_BUILD_TYPE=Release, after "make" the below error shows up

[ 91%] Building CXX object tools/clang/tools/extra/modularize/CMakeFiles/modularize.dir/ModularizeUtilities.cpp.o
/home/jason/llvm/tools/clang/tools/extra/modularize/ModularizeUtilities.cpp:337:54: error: reference to ‘Module’ is ambiguous
 bool ModularizeUtilities::collectModuleHeaders(const Module &Mod) {
                                                      ^
In file included from /home/jason/llvm/tools/clang/include/clang/Frontend/CodeGenOptions.h:20:0,
                 from /home/jason/llvm/tools/clang/include/clang/Frontend/CompilerInvocation.h:17,
                 from /home/jason/llvm/tools/clang/include/clang/Frontend/CompilerInstance.h:17,
                 from /home/jason/llvm/tools/clang/tools/extra/modularize/ModularizeUtilities.cpp:18:
/home/jason/llvm/include/llvm/Target/TargetOptions.h:24:9: note: candidates are: class llvm::Module
   class Module;
         ^
In file included from /home/jason/llvm/tools/clang/include/clang/Lex/ModuleLoader.h:17:0,
                 from /home/jason/llvm/tools/clang/include/clang/Frontend/CompilerInstance.h:19,
                 from /home/jason/llvm/tools/clang/tools/extra/modularize/ModularizeUtilities.cpp:18:
/home/jason/llvm/tools/clang/include/clang/Basic/Module.h:47:7: note:                 class clang::Module
 class Module {
       ^
/home/jason/llvm/tools/clang/tools/extra/modularize/ModularizeUtilities.cpp:337:54: error: ‘Module’ does not name a type
 bool ModularizeUtilities::collectModuleHeaders(const Module &Mod) {
                                                      ^
/home/jason/llvm/tools/clang/tools/extra/modularize/ModularizeUtilities.cpp:337:6: error: prototype for ‘bool Modularize::ModularizeUtilities::collectModuleHeaders(const int&)’ does not match any in class ‘Modularize::ModularizeUtilities’
 bool ModularizeUtilities::collectModuleHeaders(const Module &Mod) {
      ^
In file included from /home/jason/llvm/tools/clang/tools/extra/modularize/ModularizeUtilities.cpp:26:0:
/home/jason/llvm/tools/clang/tools/extra/modularize/ModularizeUtilities.h:162:8: error: candidate is: bool Modularize::ModularizeUtilities::collectModuleHeaders(const clang::Module&)
   bool collectModuleHeaders(const clang::Module &Mod);
        ^
make[2]: *** [tools/clang/tools/extra/modularize/CMakeFiles/modularize.dir/ModularizeUtilities.cpp.o] Error 1
make[1]: *** [tools/clang/tools/extra/modularize/CMakeFiles/modularize.dir/all] Error 2
make: *** [all] Error 2

**Comment by JOE1994** [comment]
The description doesn't specify up to which commit the OP pulled in.
Given this was created way back in 2016, trying to reproduce & isolate the build failure seems impractical & unnecessary.
