### ISSUE TITLE
misc-suspicious-string-compare false positives on LLVM code:

### ISSUE THREAD

**Issue by EugeneZelenko** [llvm/llvm-project#27839]
|  |  |
| --- | --- |
| Bugzilla Link | [27465](https://llvm.org/bz27465) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
I run misc-suspicious-string-compare on LLVM/Clang code and found next false positives:

In first case returned value is analyzed in caller.

include/llvm/ADT/StringRef.h:60:14: warning: function 'memcmp' is called without explicitly comparing result [misc-suspicious-string-compare]
      return ::memcmp(Lhs,Rhs,Length);
             ^
                                      != 0
Obviously false positive:

include/llvm/ADT/StringSwitch.h:60:10: warning: function 'memcmp' is called without explicitly comparing result [misc-suspicious-string-compare]
        (std::memcmp(S, Str.data(), N-1) == 0)) {
         ^
                                         != 0

**Comment by carlosgalvezp** [comment]
No longer reproducible on trunk.
