### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#27848]
|  |  |
| --- | --- |
| Bugzilla Link | [27473](https://llvm.org/bz27473) |
| Version | trunk |
| OS | All |
| Attachments | [minimal working example](https://user-images.githubusercontent.com/92601263/143753404-4c9e68d7-4756-4852-b77a-9546f01e4e51.gz) |

## Extended Description 

Trying to reduce another ICE with delta resulted in a different segmentation fault (see attachment).

**Comment by Endilll** [comment]
Can't reproduce: https://godbolt.org/z/b4YGrjvE9
