### ISSUE TITLE
clang: error: clang frontend command failed due to signal

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27873]
|  |  |
| --- | --- |
| Bugzilla Link | [27499](https://llvm.org/bz27499) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Hello,

I am building Android content_shell_apk on my Ubuntu 16.04 LTS machine.
(Build instructions: https://www.chromium.org/developers/how-tos/android-build-instructions)

GN config:
+++++++++
target_os = "android"
target_cpu = "arm"  # (default)
is_debug = false  # (default)

# Other args you may want to set:
is_component_build = true
enable_nacl = false
is_clang = true
symbol_level = 0
+++++++++++++++++

Build failed 2 times with clang crash and then succeeded.

1.	../../mojo/public/cpp/bindings/lib/interface_endpoint_client.h:127:53: current parser token ';'
2.	../../mojo/public/cpp/bindings/lib/interface_endpoint_client.h:22:1: parsing namespace 'mojo'
3.	../../mojo/public/cpp/bindings/lib/interface_endpoint_client.h:26:1: parsing namespace 'internal'
4.	../../mojo/public/cpp/bindings/lib/interface_endpoint_client.h:34:1: parsing struct/union/class body 'InterfaceEndpointClient'
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.9.0 (trunk 266460)
Target: arm--linux-android
Thread model: posix
InstalledDir: /home/sarath/WORK/CHROMIUM/chromium_android/src/out/Default/../../third_party/llvm-build/Release+Asserts/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/service_worker_storage-fdc0b3.cpp
clang: note: diagnostic msg: /tmp/service_worker_storage-fdc0b3.sh
clang: note: diagnostic msg: 

********************
[11030/15230] CXX obj/content/browser/browser/service_worker_version.o
ninja: build stopped: subcommand failed.

Please see the attachments. Thank you.

**Comment by Endilll** [comment]
Unfortunately, there are no attachments.
