### ISSUE TITLE
[asan] Read/write page fault detection on ARM mac

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27917]
|  |  |
| --- | --- |
| Bugzilla Link | [27543](https://llvm.org/bz27543) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @vitalybuka |

## Extended Description 
http://reviews.llvm.org/D19561 adds a support for read/write page fault detection to mac on intel. ARM support is missing.

Umbrella sanitizers bug: https://github.com/google/sanitizers/issues/653

**Comment by thetruestblue** [comment]
Fixed. 
https://reviews.llvm.org/D125416
