### ISSUE TITLE
LLVM 3.3/3.7.1 build failed in i586 with glibc 2.23

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27922]
|  |  |
| --- | --- |
| Bugzilla Link | [27548](https://llvm.org/bz27548) |
| Version | 3.7 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@DimitryAndric |

## Extended Description 
Hi,

I am the maintainer of julia package in openSUSE. Julia 0.4.5 needs llvm 3.3 that is built together with the package. Today, I noticed that llvm 3.3 is failing to build against i586 in openSUSE Factory.

The full build log can be found here: http://pastebin.com/yzefpSqt

The messages about the error are:

[  132s] llvm[4]: ======= Finished Linking Release Executable llvm-tblgen (without symbols)
[  132s] make[4]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/utils/TableGen'
[  132s] make[3]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/utils'
[  132s] make[3]: Entering directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR'
[  132s] /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/autoconf/mkinstalldirs /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR/Release > /dev/null
[  132s] /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/autoconf/mkinstalldirs /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/include/llvm/IR > /dev/null
[  132s] echo 'Created.' > /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR/Release/.dir
[  132s] echo 'Created.' > /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/include/llvm/IR/.dir
[  132s] llvm[3]: Building Intrinsics.gen.tmp from Intrinsics.td
[  132s] /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/Release/bin/llvm-tblgen -I  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/lib/IR -I  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/include -I  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/include -I  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/lib/Target  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/include/llvm/IR/Intrinsics.td -o  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR/Release/Intrinsics.gen.tmp -gen-intrinsic
[  132s] Makefile:23: recipe for target '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR/Release/Intrinsics.gen.tmp' failed
[  132s] make[3]: *** [/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR/Release/Intrinsics.gen.tmp] Segmentation fault
[  132s] make[3]: *** Deleting file '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR/Release/Intrinsics.gen.tmp'
[  132s] make[3]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR'
[  132s] /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/Makefile.rules:866: recipe for target 'all' failed
[  132s] make[2]: *** [all] Error 1
[  132s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release'
[  132s] Makefile:670: recipe for target 'llvm-3.3/build_Release/Release/lib/libLLVMCodeGen.a' failed
[  132s] make[1]: *** [llvm-3.3/build_Release/Release/lib/libLLVMCodeGen.a] Error 2
[  132s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps'
[  132s] Makefile:51: recipe for target 'julia-deps' failed
[  132s] make: *** [julia-deps] Error 2

One thing that should be noticed is that it builds fine against openSUSE Tumbleweed i586. Thus, I really think that this can be a problem related to some package that was updated. I took the diff between the two environments:

--- factory 2016-04-27 23:44:26.625113876 -0300
+++ tumbleweed  2016-04-27 23:44:09.301014052 -0300
@@ -8,12 +8,12 @@
 brp-check-suse-13.2+git20150521.971ea2f
 brp-extract-appdata-2012.02.13
 build-compare-20160406T155640.b74db7f
-build-mkbaselibs-20160331
+build-mkbaselibs-20160304
 bzip2-1.0.6
 coreutils-8.25
 cpio-2.12
 cpp-5
-cpp5-5.3.1+r234891
+cpp5-5.3.1+r233831
 cracklib-2.9.5
 dSFMT-devel-2.2.3
 desktop-file-utils-0.22
@@ -31,14 +31,14 @@
 gcc-5
 gcc-c++-5
 gcc-fortran-5
-gcc5-5.3.1+r234891
-gcc5-c++-5.3.1+r234891
-gcc5-fortran-5.3.1+r234891
+gcc5-5.3.1+r233831
+gcc5-c++-5.3.1+r233831
+gcc5-fortran-5.3.1+r233831
 gettext-runtime-mini-0.19.6
 gettext-tools-mini-0.19.6
-glibc-2.23
-glibc-devel-2.23
-glibc-locale-2.23
+glibc-2.22
+glibc-devel-2.22
+glibc-locale-2.22
 gmp-devel-6.1.0
 grep-2.22
 gzip-1.7
@@ -53,8 +53,8 @@
 libacl1-2.2.52
 libamd-2_4_1-2.4.1
 libarpack2-3.2.0
-libasan2-5.3.1+r234891
-libatomic1-5.3.1+r234891
+libasan2-5.3.1+r233831
+libatomic1-5.3.1+r233831
 libattr1-2.4.47
 libaudit1-2.5
 libblas3-3.5.0
@@ -66,7 +66,7 @@
 libcap2-2.22
 libccolamd-2_9_1-2.9.1
 libcholmod-3_0_6-3.0.6
-libcilkrts5-5.3.1+r234891
+libcilkrts5-5.3.1+r233831
 libcolamd-2_9_1-2.9.1
 libcom_err2-1.42.13
 libcrack2-2.9.5
@@ -80,21 +80,21 @@
 libfdisk1-2.28
 libfftw3-3-3.3.4
 libfftw3_threads3-3.3.4
-libgcc_s1-5.3.1+r234891
+libgcc_s1-5.3.1+r233831
 libgdbm4-1.11
-libgfortran3-5.3.1+r234891
+libgfortran3-5.3.1+r233831
 libgit2-24-0.24.0
 libgit2-devel-0.24.0
 libglib-2_0-0-2.48.0
 libgmp10-6.1.0
 libgmpxx4-6.1.0
-libgomp1-5.3.1+r234891
+libgomp1-5.3.1+r233831
 libhttp-parser-suse0-2.6.2
 libicu57_1-57.1
 libicu57_1-ledata-57.1
 libidn11-1.32
 libisl15-0.16.1
-libitm1-5.3.1+r234891
+libitm1-5.3.1+r233831
 libkeyutils1-1.5.9
 libklu-1_3_3-1.3.3
 liblapack3-3.5.0
@@ -106,8 +106,8 @@
 libmount1-2.28
 libmpc3-1.0.3
 libmpfr4-3.1.4
-libmpx0-5.3.1+r234891
-libmpxwrappers0-5.3.1+r234891
+libmpx0-5.3.1+r233831
+libmpxwrappers0-5.3.1+r233831
 libncurses5-6.0
 libncurses6-6.0
 libnghttp2-14-1.9.1
@@ -123,7 +123,7 @@
 libpopt0-1.16
 libpsl5-0.13.0
 libpython2_7-1_0-2.7.10
-libquadmath0-5.3.1+r234891
+libquadmath0-5.3.1+r233831
 librbio-2_2_1-2.2.1
 libreadline6-6.3
 libsasl2-3-2.1.26
@@ -134,10 +134,10 @@
 libsqlite3-0-3.12.1
 libssh2-1-1.7.0
 libstdc++-devel-5
-libstdc++6-5.3.1+r234891
-libstdc++6-devel-gcc5-5.3.1+r234891
+libstdc++6-5.3.1+r233831
+libstdc++6-devel-gcc5-5.3.1+r233831
 libsuitesparseconfig-4_4_6-4.4.6
-libubsan0-5.3.1+r234891
+libubsan0-5.3.1+r233831
 libumfpack-5_7_1-5.7.1
 libunwind-1.1
 libunwind-devel-1.1

Is it possible that theses differences can cause the behavior?

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
