### ISSUE TITLE
clang-format should sort headers case-insensitively

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27928]
|  |  |
| --- | --- |
| Bugzilla Link | [27554](https://llvm.org/bz27554) |
| Version | 3.8 |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
It would be nice if clang-format had the option to sort headers case-insensitively.  While I realize that case insensitivity is a bit hard to define over the entire UTF-8 space, it is at least well defined for the Roman alphabet.

I often have to incorporate headers from multiple modules, some of which have capitalized headers.  Instead of:

```
#include "Foo.h"
#include "bar.h"
```

... I would like clang-format to ideally produce:

```
#include "bar.h"
#include "Foo.h"
```

**Comment by mydeveloperday** [comment]
This is a duplicate of https://github.com/llvm/llvm-project/issues/34026 which is already fixed
