### ISSUE TITLE
Clang crashes when processing a class that allocates a multidimensional array of templated structs

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27969]
|  |  |
| --- | --- |
| Bugzilla Link | [27595](https://llvm.org/bz27595) |
| Version | 3.8 |
| OS | All |
| Attachments | [Preprocessed C++ source code](https://user-images.githubusercontent.com/60944935/143753442-f6c0a834-8b22-45d1-a4d9-0cd03b83658b.gz), [C++ source code](https://user-images.githubusercontent.com/60944935/143753443-eb4b67b8-ce4e-4443-86f8-db245a242bf8.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Clang++ versions >3.0 crash when compiling the following source file, which is compiled successfully by GCC. Error as follows:

clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal

**Comment by Endilll** [comment]
I can confirm Aaron's conclusion with assertion builds: https://godbolt.org/z/zfK9d9b4Y
