### ISSUE TITLE
clang-3.8 fails to link against boost libraries while older versions and gcc work

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28030]
|  |  |
| --- | --- |
| Bugzilla Link | [27656](https://llvm.org/bz27656) |
| Version | 3.8 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Johannes Obermayr 2016-04-27 18:31:51 UTC
https://pmbs.links2linux.de/package/show/Extra/FreeCAD

$ make
[  1%] Built target SMDS
[  1%] Built target Driver
[  2%] Built target DriverDAT
[  2%] Built target SMESHDS
[  2%] Built target DriverUNV
[  2%] Built target DriverSTL
[  3%] Built target SMESH
[  3%] Built target MEFISTO2
[  4%] Built target StdMeshers
[  7%] Built target FreeCADBase
[  7%] Linking CXX shared library ../../lib/libFreeCADApp.so
clang version 3.8.0 (tags/RELEASE_380/final 262553)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-suse-linux/5
Found candidate GCC installation: /usr/lib64/gcc/x86_64-suse-linux/5
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-suse-linux/5
Candidate multilib: .;@m64
Selected multilib: .;@m64
clang-3.8: warning: argument unused during compilation: '-grecord-gcc-switches'
 "/usr/bin/ld" -z relro --hash-style=gnu --hash-style=both --build-id --enable-new-dtags --eh-frame-hdr -m elf_x86_64 -shared -o ../../lib/libFreeCADApp.so /usr/bin/../lib64/gcc/x86_64-suse-linux/5/../../../../lib64/crti.o /usr/bin/../lib64/gcc/x86_64-suse-linux/5/crtbeginS.o -L/usr/bin/../lib64/gcc/x86_64-suse-linux/5 -L/usr/bin/../lib64/gcc/x86_64-suse-linux/5/../../../../lib64 -L/usr/bin/../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/bin/../lib64/gcc/x86_64-suse-linux/5/../../../../x86_64-suse-linux/lib -L/usr/bin/../lib64/gcc/x86_64-suse-linux/5/../../.. -L/usr/bin/../lib -L/lib -L/usr/lib -soname libFreeCADApp.so CMakeFiles/FreeCADApp.dir/Annotation.cpp.o CMakeFiles/FreeCADApp.dir/Document.cpp.o CMakeFiles/FreeCADApp.dir/DocumentObject.cpp.o CMakeFiles/FreeCADApp.dir/DocumentObjectFileIncluded.cpp.o CMakeFiles/FreeCADApp.dir/DocumentObjectGroup.cpp.o CMakeFiles/FreeCADApp.dir/DocumentObjectGroupPyImp.cpp.o CMakeFiles/FreeCADApp.dir/GeoFeaturePyImp.cpp.o CMakeFiles/FreeCADApp.dir/DocumentObjectPyImp.cpp.o CMakeFiles/FreeCADApp.dir/DocumentObserver.cpp.o CMakeFiles/FreeCADApp.dir/DocumentObserverPython.cpp.o CMakeFiles/FreeCADApp.dir/DocumentPyImp.cpp.o CMakeFiles/FreeCADApp.dir/Expression.cpp.o CMakeFiles/FreeCADApp.dir/FeaturePython.cpp.o CMakeFiles/FreeCADApp.dir/FeatureTest.cpp.o CMakeFiles/FreeCADApp.dir/GeoFeature.cpp.o CMakeFiles/FreeCADApp.dir/GeoFeatureGroupPyImp.cpp.o CMakeFiles/FreeCADApp.dir/GeoFeatureGroup.cpp.o CMakeFiles/FreeCADApp.dir/OriginGroupPyImp.cpp.o CMakeFiles/FreeCADApp.dir/OriginGroup.cpp.o CMakeFiles/FreeCADApp.dir/PartPyImp.cpp.o CMakeFiles/FreeCADApp.dir/Part.cpp.o CMakeFiles/FreeCADApp.dir/Origin.cpp.o CMakeFiles/FreeCADApp.dir/Path.cpp.o CMakeFiles/FreeCADApp.dir/InventorObject.cpp.o CMakeFiles/FreeCADApp.dir/MeasureDistance.cpp.o CMakeFiles/FreeCADApp.dir/Placement.cpp.o CMakeFiles/FreeCADApp.dir/OriginFeature.cpp.o CMakeFiles/FreeCADApp.dir/Range.cpp.o CMakeFiles/FreeCADApp.dir/Transactions.cpp.o CMakeFiles/FreeCADApp.dir/VRMLObject.cpp.o CMakeFiles/FreeCADApp.dir/MaterialObject.cpp.o CMakeFiles/FreeCADApp.dir/MergeDocuments.cpp.o CMakeFiles/FreeCADApp.dir/DynamicProperty.cpp.o CMakeFiles/FreeCADApp.dir/ObjectIdentifier.cpp.o CMakeFiles/FreeCADApp.dir/Property.cpp.o CMakeFiles/FreeCADApp.dir/PropertyContainer.cpp.o CMakeFiles/FreeCADApp.dir/PropertyContainerPyImp.cpp.o CMakeFiles/FreeCADApp.dir/PropertyFile.cpp.o CMakeFiles/FreeCADApp.dir/PropertyGeo.cpp.o CMakeFiles/FreeCADApp.dir/PropertyLinks.cpp.o CMakeFiles/FreeCADApp.dir/PropertyPythonObject.cpp.o CMakeFiles/FreeCADApp.dir/PropertyStandard.cpp.o CMakeFiles/FreeCADApp.dir/PropertyUnits.cpp.o CMakeFiles/FreeCADApp.dir/PropertyExpressionEngine.cpp.o CMakeFiles/FreeCADApp.dir/Application.cpp.o CMakeFiles/FreeCADApp.dir/ApplicationPy.cpp.o CMakeFiles/FreeCADApp.dir/Branding.cpp.o CMakeFiles/FreeCADApp.dir/ColorModel.cpp.o CMakeFiles/FreeCADApp.dir/ComplexGeoData.cpp.o CMakeFiles/FreeCADApp.dir/ComplexGeoDataPyImp.cpp.o CMakeFiles/FreeCADApp.dir/Enumeration.cpp.o CMakeFiles/FreeCADApp.dir/Material.cpp.o CMakeFiles/FreeCADApp.dir/MaterialPyImp.cpp.o CMakeFiles/FreeCADApp.dir/PreCompiled.cpp.o ../../lib/libFreeCADBase.so -lboost_filesystem-mt -lboost_program_options-mt -lboost_regex-mt -lboost_signals-mt -lboost_system-mt -lboost_thread-mt -lboost_chrono-mt -lboost_date_time-mt -lboost_atomic-mt -lQtCore -lQtXml -lpython2.7 -lxerces-c -lboost_filesystem-mt -lboost_program_options-mt -lboost_regex-mt -lboost_signals-mt -lboost_system-mt -lboost_thread-mt -lboost_chrono-mt -lboost_date_time-mt -lboost_atomic-mt -lQtCore -lz -lutil -ldl -lzipios -rpath /home/abuild/rpmbuild/BUILD/freecad/build/lib: -lstdc++ -lm -lgcc_s -lc -lgcc_s /usr/bin/../lib64/gcc/x86_64-suse-linux/5/crtendS.o /usr/bin/../lib64/gcc/x86_64-suse-linux/5/../../../../lib64/crtn.o
[ 10%] Built target FreeCADApp
[ 10%] Linking CXX shared library ../../lib/libFreeCADGui.so
clang-3.8: warning: argument unused during compilation: '-grecord-gcc-switches'
[ 29%] Built target FreeCADGui
[ 29%] Linking CXX executable ../../bin/FreeCAD
clang-3.8: warning: argument unused during compilation: '-grecord-gcc-switches'
../../lib/libFreeCADApp.so: undefined reference to `boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'
../../lib/libFreeCADApp.so: undefined reference to `boost::program_options::arg'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
src/Main/CMakeFiles/FreeCADMain.dir/build.make:123: recipe for target 'bin/FreeCAD' failed
make[2]: *** [bin/FreeCAD] Error 1
CMakeFiles/Makefile2:725: recipe for target 'src/Main/CMakeFiles/FreeCADMain.dir/all' failed
make[1]: *** [src/Main/CMakeFiles/FreeCADMain.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by arsenm** [comment]
Old build issue
