### ISSUE TITLE
AST matcher triggers assert

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28083]
|  |  |
| --- | --- |
| Bugzilla Link | [27709](https://llvm.org/bz27709) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Using the AST Matchers library, I got an assertion failure at ASTMatchFinder.cpp: 653 using the following pattern:
declRefExpr(to(varDecl(hasParent(cxxRecordDecl()))))
Can someone confirm that the matcher is OK and not somehow badly formed? If so I will gather the details (source / preprocessed input / stack trace).

**Comment by Endilll** [comment]
> Can someone confirm that the matcher is OK and not somehow badly formed? If so I will gather the details (source / preprocessed input / stack trace).

I believe however the matcher is, we shouldn't crash.

Unfortunately, we can't do much without a reproducer. Feel free to reopen if you have more information.
