### ISSUE TITLE
clang trunk r261461+ fails to compile on some platforms (including Snow Leopard, FreeBSD 7.4) due to strnlen usage

### ISSUE THREAD

**Issue by 0e6f8740-1d2a-4afc-85fd-df25c3a603fd** [llvm/llvm-project#28088]
|  |  |
| --- | --- |
| Bugzilla Link | [27714](https://llvm.org/bz27714) |
| Version | 4.0 |
| OS | MacOS X |
| CC | @dexonsmith,@emaste,@zmodem,@ryandesign |

## Extended Description 
strnlen() is used unconditionally, but it is not available on all supported platforms.

trunk/tools/clang/lib/Lex/HeaderMap.cpp:158:18: error: use of undeclared identifier 'strnlen'
  unsigned Len = strnlen(Data, MaxLen);
                 ^
1 error generated.

---

Regression introduced by:

commit 839cd13b65d802f06276ff88d234419c38a44199
Author: Duncan P. N. Exon Smith <dexonsmith@apple.com>
Date:   Sun Feb 21 00:14:36 2016 +0000

    Lex: Never overflow the file in HeaderMap::lookupFilename()
    
    If a header map file is corrupt, the strings in the string table may not
    be null-terminated.  The logic here previously relied on `MemoryBuffer`
    always being null-terminated, but this isn't actually guaranteed by the
    class AFAICT.  Moreover, we're seeing a lot of crash traces at calls to
    `strlen()` inside of `lookupFilename()`, so something is going wrong
    there.
    
    Instead, use `strnlen()` to get the length, and check for corruption.
    
    Also remove code paths that could call `StringRef(nullptr)`.  r261459
    made these rather obvious (although they'd been there all along).
    
    git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@261461 91177308-0d34-0410-b5e6-96231b3b80d8

**Comment by Endilll** [comment]
`strnlen` is still there, not guarded in any way: https://github.com/llvm/llvm-project/blob/f36e909da03767c317eaa5ded9abbf3214299ff5/clang/lib/Lex/HeaderMap.cpp#L159

[Apple documenation](https://developer.apple.com/documentation/kernel/1579340-strnlen) says that `strnlen` has been available since 10.5.

It should be noted that it's barely used throughout Clang, and can be quite easily replaced: https://stackoverflow.com/a/32468556/4182606

CC @AaronBallman do we care about platforms without `strnlen`?

**Comment by Endilll** [comment]
I wonder if Apple documentation ignores PowerPC, because one of the comments above says the issue persists on his PPC 10.5.8.

**Comment by AaronBallman** [comment]
> CC @AaronBallman do we care about platforms without `strnlen`?

`strnlen` was added to POSIX in 2006 and we require POSIX support on non-Windows systems, so I don't think we're too concerned about such platforms. That said, if someone submitted a patch to replace use of `strnlen` to improve portability, I don't think anyone would be opposed.

Closing the issue as not planned, feel free to reopen if this is still an issue.
