### ISSUE TITLE
tsan uses OS X private API that was added in 10.9 (fails to link on 10.8 and earlier)

### ISSUE THREAD

**Issue by 0e6f8740-1d2a-4afc-85fd-df25c3a603fd** [llvm/llvm-project#28089]
|  |  |
| --- | --- |
| Bugzilla Link | [27715](https://llvm.org/bz27715) |
| Version | unspecified |
| OS | MacOS X |
| CC | @vitalybuka |

## Extended Description 
The build system attempts to build tsan on older versions of OSX, but this of course fails.  We should automatically detect that tsan should not be built based on the deployment target.

:info:build Undefined symbols for architecture x86_64:
:info:build   "_os_lock_lock", referenced from:
:info:build       _wrap_os_lock_lock in tsan_interceptors_mac.cc.o
:info:build       __ZN6__tsanL25substitution_os_lock_lockE in tsan_interceptors_mac.cc.o
:info:build      (maybe you meant: _wrap_os_lock_lock)
:info:build   "_os_lock_trylock", referenced from:
:info:build       _wrap_os_lock_trylock in tsan_interceptors_mac.cc.o
:info:build       __ZN6__tsanL28substitution_os_lock_trylockE in tsan_interceptors_mac.cc.o
:info:build      (maybe you meant: _wrap_os_lock_trylock)
:info:build   "_os_lock_unlock", referenced from:
:info:build       _wrap_os_lock_unlock in tsan_interceptors_mac.cc.o
:info:build       __ZN6__tsanL27substitution_os_lock_unlockE in tsan_interceptors_mac.cc.o
:info:build      (maybe you meant: _wrap_os_lock_unlock)
:info:build   "_pthread_introspection_hook_install", referenced from:
:info:build       __tsan::InitializePlatform() in tsan_platform_mac.cc.o
:info:build ld: symbol(s) not found for architecture x86_64
:info:build clang: error: linker command failed with exit code 1 (use -v to see invocation)
:info:build make[2]: *** [lib/clang/3.8.0/lib/darwin/libclang_rt.tsan_osx_dynamic.dylib] Error 1

**Comment by arsenm** [comment]
Old build issue
