### ISSUE TITLE
misc-definitions-in-headers false positive on recommended way of defining callables in C++11 and beyond

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#28106]
|  |  |
| --- | --- |
| Bugzilla Link | [27732](https://llvm.org/bz27732) |
| Version | unspecified |
| OS | All |

## Extended Description 
misc-definitions-in-headers has a false positive on the standard way of defining customization points [0, 1], algorithms [2] and callables in C++ 11 and beyond. If anything clang-tidy should actually be recommending users to write code this way. 

Minimal example, the following _is not_ an ODR violation in a header file (even when linking multiple TUs): 

template <class T> struct static_const { static constexpr T value{}; };
template <class T> constexpr T static_const<T>::value;

struct foo_fn {};

namespace {
constexpr auto const& foo = static_const<foo_fn>::value;
} // namespace

In C++17 inline variables are introduced into the language to avoid using the static_const workaround. clang-tidy should recommend users in C++>17 to use inline variables instead.

[0] N4381 Suggested design for Customization Points, http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4381.html

[1] CMCSTL2: for example, begin and end, see here: 
https://github.com/CaseyCarter/cmcstl2/blob/024d495d2f7675a5806269312017293bad1a8523/include/stl2/detail/range/access.hpp

[2] range-v3: for example, find_if, see here:
https://github.com/ericniebler/range-v3/blob/master/include/range/v3/algorithm/find_if.hpp#L73

**Comment by PiotrZSL** [comment]
Fixed by 2990ac1ebd49a8546b0876c73b8473ce8353bfd8
