### ISSUE TITLE
Crash during code completion

### ISSUE THREAD

**Issue by cameron314** [llvm/llvm-project#28110]
|  |  |
| --- | --- |
| Bugzilla Link | [27736](https://llvm.org/bz27736) |
| Version | trunk |
| OS | Windows NT |

## Extended Description 
The following simple code causes clang to crash (access violation from null pointer) during code completion after the '->' arrow operator:

crashtest.c:
    struct S {
        unsigned x;
    };

    int main()
    {
        struct S s;
        return (int)(&s)->
    }

$ c-index-test -code-completion-at=crashtest.c:8:23 crashtest.c
libclang: crash detected in code completion
Unable to perform code completion!

**Comment by JOE1994** [comment]
With `clang 19 trunk (@ edf4e02906bd0c57087a44e5c4890ffc453667b2)`, code-completion no longer crashes.

```bash
$ c-index-test -code-completion-at=crashtest.c:8:23 crashtest.c

FieldDecl:{ResultType unsigned int}{TypedText x} (35)
Completion contexts:
Arrow member access
Container Kind: StructDecl
Container is complete
Container USR: c:@S@S
```
