### ISSUE TITLE
clang-format never adds line feed at end of file

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28122]
|  |  |
| --- | --- |
| Bugzilla Link | [27748](https://llvm.org/bz27748) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
clang-format always results in a file without a line feed at the end of file. This cause many headaches for those working in a Unix system. For example, I cannot easily build an amalgamation of sources with simple `cat`. `git` always have this warning about no LF at the end of file. Sometimes `gcc` will warn about that too if warning level is high enough. Ensuring new line at the end of file will never hurt anyone, but save many from these headaches.

**Comment by owenca** [comment]
Fixed in 2c6ecc9db624.
