### ISSUE TITLE
Regression: D19133 makes two piglit test fail

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28129]
|  |  |
| --- | --- |
| Bugzilla Link | [27755](https://llvm.org/bz27755) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@nemanjai |

## Extended Description 
http://reviews.llvm.org/D19133 causes a regression in mesa's llvmpipe driver on ppc64le.

The regression is detected by running piglit test suite with mesa master and llvm master.

The following two tests fail with D19133 (and pass without it):

fbo-blending-formats GL_EXT_texture_snorm -auto -fbo
max-samplers border -auto -fbo

**Comment by chenzheng1030** [comment]
I am going to close this item. It was reported 7 years ago. And no further repose from piglit.
