### ISSUE TITLE
missing optimization of multiply overflow check

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#28168]
|  |  |
| --- | --- |
| Bugzilla Link | [27794](https://llvm.org/bz27794) |
| Version | trunk |
| OS | All |
| CC | @atrick,@hfinkel,@RKSimon,@nikic,@sanjoy,@rotateright |

## Extended Description 
This is a portable, UB-free idiom for seeing if a multiply is going to overflow:

  int f(unsigned a, unsigned b) { return a > (UINT_MAX / b); }

we should turn this into a multiply with condition code and then also CSE it with the multiply itself which will surely be nearby.

Request for this optimization comes from Rich Felker, author of Musl libc:

  http://wiki.musl-libc.org/wiki/Projects_using_musl

This should be done in CodeGenPrepare, Sanjoy Das says.

**Comment by RKSimon** [comment]
This was fixed by https://reviews.llvm.org/D65143 / fb38b7aab3f23604611ae424f3dc702124962524
