### ISSUE TITLE
Assertion triggered in SemaChecking.cpp

### ISSUE THREAD

**Issue by rui314** [llvm/llvm-project#28209]
|  |  |
| --- | --- |
| Bugzilla Link | [27835](https://llvm.org/bz27835) |
| Version | trunk |
| OS | Linux |
| CC | @hfinkel,@zygoloid |

## Extended Description 
It is observed that clang triggered assertion on lld buildbot.

http://lab.llvm.org:8011/builders/llvm-clang-lld-x86_64-debian-fast/builds/38263/steps/build/logs/stdio

clang-3.9: /home/llvmbb/llvm-buildit/llvm/tools/clang/lib/Sema/SemaChecking.cpp:5937: clang::Expr *EvalAddr(clang::Expr *, SmallVectorImpl<clang::DeclRefExpr *> &, clang::Decl *): Assertion `(E->getType()->isAnyPointerType() || E->getType()->isBlockPointerType() || E->getType()->isObjCQualifiedIdType()) && "EvalAddr only works on pointers"' failed.
#&#8203;0 0x00000000018b9d68 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x18b9d68)
#&#8203;1 0x00000000018ba4c7 SignalHandler(int) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x18ba4c7)
#&#8203;2 0x00007fa78ad23d30 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10d30)
#&#8203;3 0x00007fa78a10e458 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x33458)
#&#8203;4 0x00007fa78a10f8da abort (/lib/x86_64-linux-gnu/libc.so.6+0x348da)
#&#8203;5 0x00007fa78a107387 (/lib/x86_64-linux-gnu/libc.so.6+0x2c387)
#&#8203;6 0x00007fa78a107432 (/lib/x86_64-linux-gnu/libc.so.6+0x2c432)
#&#8203;7 0x00000000026c0905 EvalAddr(clang::Expr*, llvm::SmallVectorImpl<clang::DeclRefExpr*>&, clang::Decl*) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x26c0905)
#&#8203;8 0x00000000026a65d3 clang::Sema::CheckReturnValExpr(clang::Expr*, clang::QualType, clang::SourceLocation, bool, llvm::SmallVector<clang::Attr*, 2u> const*, clang::FunctionDecl const*) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x26a65d3)
#&#8203;9 0x0000000002a2f104 clang::Sema::BuildReturnStmt(clang::SourceLocation, clang::Expr*) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x2a2f104)
#&#8203;10 0x0000000002a2e919 clang::Sema::ActOnReturnStmt(clang::SourceLocation, clang::Expr*, clang::Scope*) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x2a2e919)
#&#8203;11 0x00000000024e5f37 clang::Parser::ParseReturnStatement() (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x24e5f37)
#&#8203;12 0x00000000024e1043 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedContsructsKind, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x24e1043)
#&#8203;13 0x00000000024e0925 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedContsructsKind, clang::SourceLocation*) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x24e0925)
#&#8203;14 0x00000000024e7a2a clang::Parser::ParseCompoundStatementBody(bool) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x24e7a2a)
#&#8203;15 0x00000000024e838c clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x24e838c)
#&#8203;16 0x000000000246002c clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x246002c)
#&#8203;17 0x00000000024efd7e clang::Parser::ParseSingleDeclarationAfterTemplate(unsigned int, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x24efd7e)
#&#8203;18 0x00000000024ee935 clang::Parser::ParseTemplateDeclarationOrSpecialization(unsigned int, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x24ee935)
#&#8203;19 0x00000000024ee265 clang::Parser::ParseDeclarationStartingWithTemplate(unsigned int, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x24ee265)
#&#8203;20 0x0000000002473594 clang::Parser::ParseDeclaration(unsigned int, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x2473594)
#&#8203;21 0x000000000245ded4 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x245ded4)
#&#8203;22 0x000000000245d432 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x245d432)
#&#8203;23 0x00000000024593a6 clang::ParseAST(clang::Sema&, bool, bool) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x24593a6)
#&#8203;24 0x0000000001dbb045 clang::FrontendAction::Execute() (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x1dbb045)
#&#8203;25 0x0000000001d86801 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x1d86801)
#&#8203;26 0x0000000001e51a22 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x1e51a22)
#&#8203;27 0x0000000000758252 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x758252)
#&#8203;28 0x0000000000756eb2 main (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x756eb2)
#&#8203;29 0x00007fa78a0fb5f0 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x205f0)
#&#8203;30 0x0000000000753f89 _start (/home/llvmbb/bin/clang-latest/bin/clang-3.9+0x753f89)

**Comment by AaronBallman** [comment]
Closing as there is no way to reproduce this.
