### ISSUE TITLE
clang_getSpellingLocation() doesn't actually return the spelling location

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28205]
|  |  |
| --- | --- |
| Bugzilla Link | [27831](https://llvm.org/bz27831) |
| Version | 3.8 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
From the Github mirror in the source code of clang_getSpellingLocation():

const SourceManager &SM =
  *static_cast<const SourceManager*>(location.ptr_data[0]);
// FIXME: This should call SourceManager::getSpellingLoc().
SourceLocation SpellLoc = SM.getFileLoc(Loc);

Found here: https://github.com/llvm-mirror/clang/blob/4ab9d6e02b29c24ca44638cc61b52cde2df4a888/tools/libclang/CXSourceLocation.cpp#L328-L331

I'm guessing that should call SourceManager::getSpellingLoc()? :D
Right now this is an exact copy of clang_getFileLocation().

The FIXME has been there since Branch release_33.

**Comment by DeinAlptraum** [comment]
Thanks for the heads-up, closing
