### ISSUE TITLE
Compilation triggers a compiler bug - it asked to report to llvm.org

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28214]
|  |  |
| --- | --- |
| Bugzilla Link | [27840](https://llvm.org/bz27840) |
| Version | 3.7 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zmodem,@jmolloy,@noloader,@sanjoy |

## Extended Description 
Mac OS X 10.11.5, Xcode-7.3.1, Macports-2.3.4.

The problem is with Macports-installed clang-3.7 (which was built using Xcode-7.3.1).

Here's the screen log:

clang++-mp-3.7 -maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4.1 -msse4.2 -std=c++11 -ffunction-sections -fdata-sections -O3 -fPIC -march=native -pipe -c integer.cpp
Assertion failed: (BB->getTerminator()->getNumSuccessors() == 1 && "Should have a single succ!"), function SplitEdge, file /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_lang_llvm-3.7/llvm-3.7/work/llvm-3.7.1.src/lib/Transforms/Utils/BasicBlockUtils.cpp, line 262.
0  libLLVM-3.7.dylib        0x000000010ee3a6bf llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 57
1  libLLVM-3.7.dylib        0x000000010ee3ad0e SignalHandler(int) + 231
2  libsystem_platform.dylib 0x00007fff92c6952a _sigtramp + 26
3  libsystem_platform.dylib 0x00007fa9738024e8 _sigtramp + 3770257368
4  libsystem_c.dylib        0x00007fff8c8af6e7 abort + 129
5  libsystem_c.dylib        0x00007fff8c876df8 basename + 0
6  libLLVM-3.7.dylib        0x000000010eeb2d23 llvm::SplitBlock(llvm::BasicBlock*, llvm::Instruction*, llvm::DominatorTree*, llvm::LoopInfo*) + 0
7  libLLVM-3.7.dylib        0x000000010ebb253d (anonymous namespace)::JumpThreading::DuplicateCondBranchOnPHIIntoPred(llvm::BasicBlock*, llvm::SmallVectorImpl<llvm::BasicBlock*> const&) + 981
8  libLLVM-3.7.dylib        0x000000010ebad752 (anonymous namespace)::JumpThreading::runOnFunction(llvm::Function&) + 4938
9  libLLVM-3.7.dylib        0x000000010e7258e5 llvm::FPPassManager::runOnFunction(llvm::Function&) + 297
10 libLLVM-3.7.dylib        0x000000010f09f74e (anonymous namespace)::CGPassManager::runOnModule(llvm::Module&) + 1230
11 libLLVM-3.7.dylib        0x000000010e725dc0 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 628
12 clang                    0x000000010c911a6d clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::raw_pwrite_stream*) + 6301
13 clang                    0x000000010ca28d0c clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) + 510
14 clang                    0x000000010ca9ee7a clang::ParseAST(clang::Sema&, bool, bool) + 393
15 clang                    0x000000010c7c63cf clang::FrontendAction::Execute() + 71
16 clang                    0x000000010c79eebb clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 553
17 clang                    0x000000010c7726f6 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 3822
18 clang                    0x000000010c76adcd cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 1389
19 clang                    0x000000010c770e67 main + 8505
20 libdyld.dylib            0x00007fff90a385ad start + 1
21 libdyld.dylib            0x0000000000000086 start + 1868331738
Stack dump:
0.	Program arguments: /opt/local/libexec/llvm-3.7/bin/clang -cc1 -triple x86_64-apple-macosx10.11.0 -emit-obj -disable-free -main-file-name integer.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu ivybridge -target-feature -sse4a -target-feature -avx512bw -target-feature +cx16 -target-feature -tbm -target-feature -adx -target-feature -fma4 -target-feature -avx512vl -target-feature -prfchw -target-feature -bmi2 -target-feature -avx512pf -target-feature +fsgsbase -target-feature +avx -target-feature -avx512cd -target-feature -rtm -target-feature +popcnt -target-feature -fma -target-feature -bmi -target-feature -avx2 -target-feature -avx512er -target-feature +sse -target-feature -lzcnt -target-feature -avx512f -target-feature +f16c -target-feature +mmx -target-feature +cmov -target-feature -xop -target-feature -rdseed -target-feature -movbe -target-feature -hle -target-feature -sha -target-feature +sse3 -target-feature -avx512dq -target-feature +aes -target-feature +pclmul -target-feature +rdrnd -target-feature +sse2 -target-feature +ssse3 -target-feature +sse4.1 -target-feature +sse4.2 -target-linker-version 253.3 -dwarf-column-info -ffunction-sections -fdata-sections -coverage-file /Users/ur20980/src/cryptopp/integer.cpp -resource-dir /opt/local/libexec/llvm-3.7/bin/../lib/clang/3.7.1 -stdlib=libc++ -O3 -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /Users/ur20980/src/cryptopp -ferror-limit 19 -fmessage-length 113 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.11.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o integer.o -x c++ integer.cpp 
1.	<eof> parser at end of file
2.	Per-module optimization passes
3.	Running pass 'CallGraph Pass Manager' on module 'integer.cpp'.
4.	Running pass 'Jump Threading' on function '@_ZN8CryptoPPrsERNSt3__113basic_istreamIcNS0_11char_traitsIcEEEERNS_7IntegerE'
clang: error: unable to execute command: Abort trap: 6
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.7.1 (tags/RELEASE_371/final)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/c6/lnc_0m093ys8w16md_fm1mnxhtfnj8/T/integer-953212.cpp
clang: note: diagnostic msg: /var/folders/c6/lnc_0m093ys8w16md_fm1mnxhtfnj8/T/integer-953212.sh
clang: note: diagnostic msg: 

********************
make: *** [integer.o] Error 254

I'm attaching the files it requested.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 4.0: https://cexplorer.testlabs.pro/z/zEWrfz
