### ISSUE TITLE
modernize-use-equals-default does not work correctly for unions that have members with non-trivial default constructors

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28300]
|  |  |
| --- | --- |
| Bugzilla Link | [27926](https://llvm.org/bz27926) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @gnzlbg,@pepsiman,@zygoloid |

## Extended Description 
#include <string>

class Foo {
public:
	union Bar {
		Bar() {};
		~Bar() {};
		int i;
		std::string s;
	} bar;
};

int main(void)
{
	Foo foo;
	return 0;
}

modernize-use-default suggests adding "= default" for Bar() and ~Bar(). Doing so however results in the following compilation error:

delme.cpp:15:6: error: call to implicitly-deleted default constructor of 'Foo' [clang-diagnostic-error]
        Foo foo;
            ^
delme.cpp:10:4: note: default constructor of 'Foo' is implicitly deleted because field 'bar' has a deleted default constructor
        } bar;
          ^
delme.cpp:6:3: note: explicitly defaulted function was implicitly deleted here
                Bar() = default;
                ^
delme.cpp:9:15: note: default constructor of 'Bar' is implicitly deleted because variant field 's' has a non-trivial default constructor
                std::string s;
                            ^

**Comment by zmodem** [comment]
@llvm/issue-subscribers-clang-tidy people keep hitting this.

Stand-alone repro:

```
$ cat /tmp/a.cc
#include <string>

union U {
  int i;
  std::string s;
  U();
};

U::U() {}

$ bin/clang-tidy -checks=modernize-use-equals-default /tmp/a.cc
...
/tmp/a.cc:9:4: warning: use '= default' to define a trivial default constructor [modernize-use-equals-default]
U::U() {}
   ^   ~~
       = default;
```

**Comment by alexander-shaposhnikov** [comment]
yeah, it's a bug, clang-tidy shouldn't suggest '=default' in this case.
https://godbolt.org/z/xaPd31eh3

**Comment by PiotrZSL** [comment]
This issue exist because check instead of using ofClass to get real class, is using hasParent, therfor out of line destructors and constructors of unions are still pointed out.

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D146882
