### ISSUE TITLE
modernize-use-default breaks destructor when union with member with non-trivial destructor

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#28301]
|  |  |
| --- | --- |
| Bugzilla Link | [27927](https://llvm.org/bz27927) |
| Version | unspecified |
| OS | All |

## Extended Description 
struct A {
~A() { new int(); }  // non-trivial destructor
};

union U {
A a;
// ~U() {}; // works but modernizes changes this to = default;
~U() = default; // fails 
};

int main() {
  U u;
  return 0;
}

So I guess clang-tidy's modernize-use-default doesn't know about unions and it doesn't check that the program will compile after applying the fix.

**Comment by PiotrZSL** [comment]
This issue were fixed long ago by 44503482e0af189d3a7fc57b80238ea4151992b9
