### ISSUE TITLE
clang takes a lot of time to compile RxCpp code

### ISSUE THREAD

**Issue by ismail** [llvm/llvm-project#28302]
|  |  |
| --- | --- |
| Bugzilla Link | [27928](https://llvm.org/bz27928) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [Preprocessed source](https://user-images.githubusercontent.com/4255/143753603-c23ab2f9-bd59-499d-bd2d-90306b76433a.gz) |
| CC | @asl,@nico,@rnk,@sanjoy |

## Extended Description 

Attached preprocessor source is taken from RxCpp example, VS2015 Update 2 compiles it under 10 seconds while clang takes around 8 minutes. Also reproducible on Linux. Compile with:

clang++- -O2 -target x86_64-windows-msvc -fms-compatibility-version=19 -c rx.ii

**Comment by EugeneZelenko** [comment]
@ismail" Could you please elaborate on reason(s) and also add relevant label(s)?

**Comment by ismail** [comment]
> @ismail" Could you please elaborate on reason(s) and also add relevant label(s)?

After 6 years I don't know the status or this nor can check it. I don't see any value in leaving it open.

**Comment by EugeneZelenko** [comment]
@ismail; So `obsolete` is reasonable label.
