### ISSUE TITLE
LIBCXXABI_GCC_TOOLCHAIN is not used during configuration

### ISSUE THREAD

**Issue by EugeneZelenko** [llvm/llvm-project#28324]
|  |  |
| --- | --- |
| Bugzilla Link | [27950](https://llvm.org/bz27950) |
| Version | unspecified |
| OS | Linux |
| CC | @mclow |

## Extended Description 
LIBCXXABI_GCC_TOOLCHAIN is not used during configuration, so it's lead to failure on RHEL 6 where GCC 4.4 is found by default. But configuration is OK when I specify newer GCC path as --gcc-toolchain in CMAKE_CXX_FLAGS.

Same happens with LIBUNWIND_GCC_TOOLCHAIN for libunwind.

**Comment by ldionne** [comment]
Closing since `LIBCXXABI_GCC_TOOLCHAIN` doesn't exist anymore. If you're still witnessing a problem related to this, please reopen a new issue with a current explanation and we'll take a look!
