### ISSUE TITLE
Cannot parse array subscript with comma/assignment

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [llvm/llvm-project#28336]
|  |  |
| --- | --- |
| Bugzilla Link | [27962](https://llvm.org/bz27962) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@hfinkel |

## Extended Description 
Clang fails to attempt parsing a /statement/ as an /expression-statement/ when it encounters a comma (or an assignment operator) in the potential array bound in its attempt to parse the /statement/ as a /declaration-statement/.

### SOURCE:
void foo(int *x, unsigned idx) {
   int(x[0, idx]);
}

### INVOCATION:
clang++ -cc1 -fsyntax-only subscriptvex.cc

### ACTUAL OUTPUT:
subscriptvex.cc:2:11: error: expected ']'
   int(x[0, idx]);
          ^
subscriptvex.cc:2:9: note: to match this '['
   int(x[0, idx]);
        ^
subscriptvex.cc:2:8: error: redefinition of 'x' with a different type: 'int ([0]' vs 'int *'
   int(x[0, idx]);
       ^
subscriptvex.cc:1:15: note: previous definition is here
void foo(int *x, unsigned idx) {
              ^
2 errors generated.

### EXPECTED OUTPUT:
Clean compile.

**Comment by wheatman** [comment]
This seems to have been fixed between 9.0.1 and 10.0.0
https://godbolt.org/z/bjMb198s6

For reference
code 
```
void foo(int *x, unsigned idx) {
   int(x[0, idx]);
}
```

Original error

```
<source>:2:11: error: expected ']'
   int(x[0, idx]);
          ^
<source>:2:9: note: to match this '['
   int(x[0, idx]);
        ^
<source>:2:8: error: redefinition of 'x' with a different type: 'int ([0]' vs 'int *'
   int(x[0, idx]);
       ^
<source>:1:15: note: previous definition is here
void foo(int *x, unsigned idx) {
              ^
2 errors generated.
Compiler returned: 1
```

warning with 10.0.0

```
<source>:2:10: warning: expression result unused [-Wunused-value]
   int(x[0, idx]);
         ^
<source>:2:4: warning: expression result unused [-Wunused-value]
   int(x[0, idx]);
   ^   ~~~~~~~~~
2 warnings generated.
Compiler returned: 0
```

current warning with 16.0.0

```
<source>:2:10: warning: left operand of comma operator has no effect [-Wunused-value]
   int(x[0, idx]);
         ^
<source>:2:4: warning: expression result unused [-Wunused-value]
   int(x[0, idx]);
   ^   ~~~~~~~~~
2 warnings generated.
Compiler returned: 0
```
