### ISSUE TITLE
[clang-format] SpacesBeforeTrailingComments is ignored for trailing C-style block-comments (/* ... */)

### ISSUE THREAD

**Issue by Bagira80** [llvm/llvm-project#28353]
|  |  |
| --- | --- |
| Bugzilla Link | [27979](https://llvm.org/bz27979) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
The clang-format option "SpacesBeforeTrailingComments" works for trailing "//" comments as expected, but not for trailing "/*...*/" block-comments. In the latter case only a single space will be put in front of the comment.

Example:

The following code

```
int example1()
{
    return 1;// Correct number of spaces after formatting.
}
int example2()
{
    return 2;/* Incorrect number of spaces after formatting. */
}
```

will be formatted to the following when "SpacesBeforeTrailingComments" is set to 4:

```
int example1()
{
    return 1    ;// Correct number of spaces after formatting.
}
int example2()
{
    return 2; /* Incorrect number of spaces after formatting */
}
```

The number of spaces before the comment in "example1()" is correct, while the number of spaces before the comment in "example2()" is incorrect.

**Comment by mydeveloperday** [comment]
You are not clear of the .clang-format settings you are using, this formats for me as, which means this isn't a trailing comment

```
int example1() {
  return 1;    // Correct number of spaces after formatting.
}
int example2() { return 2; /* Incorrect number of spaces after formatting. */ }
```

**Comment by mkurdej** [comment]
The documentation is clear that this option doesn't apply to block-comments:
> The number of spaces before trailing line comments (// - comments).
>
> This does not affect trailing block comments (/* - comments) as those commonly have different usage patterns and a number of special cases.

Cf. https://clang.llvm.org/docs/ClangFormatStyleOptions.html.
