### ISSUE TITLE
InstCombine hangs in BitCast optimization

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28370]
|  |  |
| --- | --- |
| Bugzilla Link | [27996](https://llvm.org/bz27996) |
| Version | trunk |
| OS | Linux |
| Attachments | [test case](https://user-images.githubusercontent.com/60944935/143753636-49a6eb72-6f45-4bb4-9f6f-3cd5d370c4f2.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @weiguozhi,@hfinkel,@vitalybuka |

## Extended Description 

clang -O2 -S 2.c hangs on my x86
2.c (attached)

This is a regression introduced at r270135.

Potential fix:
http://reviews.llvm.org/D20847

**Comment by msebor** [comment]
I'm not able to reproduce the problem with the attached test case (copied below) and the latest trunk or any other version I have access to so I assume it's been fixed.  Please reopen if it persists and provide more details to help reproduce it.
```
float *resf;
int *resi;
int cmp;
const int i = 1;
const float f = 1.1;
int foo() {
  int *res = 0;
  int *ii = (int *)&i;
  while (cmp >>= 1) {
    if (cmp & 1)
      res = ii;
    else
      res = (int *)&f;
  }
  resf = (float*)res;
  resi = res;
  return 0;
}
```
