### ISSUE TITLE
clang crashes on invalid C++ code: Assertion `!D->isInvalidDecl() && "Cannot get layout of invalid decl!"' failed

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#28407]
|  |  |
| --- | --- |
| Bugzilla Link | [28033](https://llvm.org/bz28033) |
| Version | trunk |
| OS | All |
| CC | @majnemer,@DougGregor,@hfinkel |

## Extended Description 
The current clang trunk crashes when compiling the following C++ test case with on x86_64-linux-gnu in both 32-bit and 64-bit modes. 

3.8.x (incorrectly) accepts and compiles the code, while, like the trunk, 3.4.x to 3.7.x all crash on the same code. 

 
$ clang++ -v
clang version 3.9.0 (trunk 271877)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$
$ clang++-3.8 -c small.cpp
$ g++-6.1 -c small.cpp
small.cpp: In instantiation of ‘class C<int>’:
small.cpp:12:13:   required from here
small.cpp:6:15: error: ‘void C()’ redeclared as different kind of symbol
   friend void C < T > (); // should be: friend void f < T > ();
               ^~~~~~~
small.cpp:4:7: note: previous declaration ‘template<class T> class C’
 class C
       ^
$
$ clang++ -c small.cpp
clang-3.9: /tmp/llvm-builder/llvm-source-trunk/tools/clang/lib/AST/RecordLayoutBuilder.cpp:2934: const clang::ASTRecordLayout& clang::ASTContext::getASTRecordLayout(const clang::RecordDecl*) const: Assertion `!D->isInvalidDecl() && "Cannot get layout of invalid decl!"' failed.
#&#8203;0 0x0000000001e1a4f5 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/clang-trunk/bin/clang-3.9+0x1e1a4f5)
#&#8203;1 0x0000000001e18486 llvm::sys::RunSignalHandlers() (/usr/local/clang-trunk/bin/clang-3.9+0x1e18486)
#&#8203;2 0x0000000001e186a4 SignalHandler(int) (/usr/local/clang-trunk/bin/clang-3.9+0x1e186a4)
#&#8203;3 0x00007f771ad1e340 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10340)
#&#8203;4 0x00007f7719f3ccc9 gsignal /build/eglibc-3GlaMS/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;5 0x00007f7719f400d8 abort /build/eglibc-3GlaMS/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;6 0x00007f7719f35b86 __assert_fail_base /build/eglibc-3GlaMS/eglibc-2.19/assert/assert.c:92:0
#&#8203;7 0x00007f7719f35c32 (/lib/x86_64-linux-gnu/libc.so.6+0x2fc32)
#&#8203;8 0x00000000034a0402 clang::ASTContext::getASTRecordLayout(clang::RecordDecl const*) const (/usr/local/clang-trunk/bin/clang-3.9+0x34a0402)
#&#8203;9 0x0000000001f9060d (anonymous namespace)::CGRecordLowering::CGRecordLowering(clang::CodeGen::CodeGenTypes&, clang::RecordDecl const*, bool) (/usr/local/clang-trunk/bin/clang-3.9+0x1f9060d)
#&#8203;10 0x0000000001f99a9c clang::CodeGen::CodeGenTypes::ComputeRecordLayout(clang::RecordDecl const*, llvm::StructType*) (/usr/local/clang-trunk/bin/clang-3.9+0x1f99a9c)
#&#8203;11 0x000000000202b356 clang::CodeGen::CodeGenTypes::ConvertRecordDeclType(clang::RecordDecl const*) (/usr/local/clang-trunk/bin/clang-3.9+0x202b356)
#&#8203;12 0x000000000202d19d clang::CodeGen::CodeGenTypes::ConvertType(clang::QualType) (/usr/local/clang-trunk/bin/clang-3.9+0x202d19d)
#&#8203;13 0x000000000202e5df clang::CodeGen::CodeGenTypes::ConvertTypeForMem(clang::QualType) (/usr/local/clang-trunk/bin/clang-3.9+0x202e5df)
#&#8203;14 0x00000000020d89e6 clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(clang::VarDecl const&) (/usr/local/clang-trunk/bin/clang-3.9+0x20d89e6)
#&#8203;15 0x00000000020d9017 clang::CodeGen::CodeGenFunction::EmitAutoVarDecl(clang::VarDecl const&) (/usr/local/clang-trunk/bin/clang-3.9+0x20d9017)
#&#8203;16 0x0000000001f9c26f clang::CodeGen::CodeGenFunction::EmitDeclStmt(clang::DeclStmt const&) (/usr/local/clang-trunk/bin/clang-3.9+0x1f9c26f)
#&#8203;17 0x0000000001fa8412 clang::CodeGen::CodeGenFunction::EmitSimpleStmt(clang::Stmt const*) (/usr/local/clang-trunk/bin/clang-3.9+0x1fa8412)
#&#8203;18 0x0000000001fa47d8 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*) (/usr/local/clang-trunk/bin/clang-3.9+0x1fa47d8)
#&#8203;19 0x0000000001fa551f clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/usr/local/clang-trunk/bin/clang-3.9+0x1fa551f)
#&#8203;20 0x0000000001fcb3e2 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::CodeGen::FunctionArgList&, clang::Stmt const*) (/usr/local/clang-trunk/bin/clang-3.9+0x1fcb3e2)
#&#8203;21 0x0000000001fd5b6e clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/usr/local/clang-trunk/bin/clang-3.9+0x1fd5b6e)
#&#8203;22 0x0000000001ff6d81 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/usr/local/clang-trunk/bin/clang-3.9+0x1ff6d81)
#&#8203;23 0x0000000002008161 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/usr/local/clang-trunk/bin/clang-3.9+0x2008161)
#&#8203;24 0x0000000002009079 clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl) (/usr/local/clang-trunk/bin/clang-3.9+0x2009079)
#&#8203;25 0x000000000200974d clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) [clone .part.6208] (/usr/local/clang-trunk/bin/clang-3.9+0x200974d)
#&#8203;26 0x00000000025c703b (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) (/usr/local/clang-trunk/bin/clang-3.9+0x25c703b)
#&#8203;27 0x00000000025c194c clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) (/usr/local/clang-trunk/bin/clang-3.9+0x25c194c)
#&#8203;28 0x0000000002923676 clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/clang-trunk/bin/clang-3.9+0x2923676)
#&#8203;29 0x00000000025c23fe clang::CodeGenAction::ExecuteAction() (/usr/local/clang-trunk/bin/clang-3.9+0x25c23fe)
#&#8203;30 0x000000000228f1fe clang::FrontendAction::Execute() (/usr/local/clang-trunk/bin/clang-3.9+0x228f1fe)
#&#8203;31 0x0000000002264c66 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/clang-trunk/bin/clang-3.9+0x2264c66)
#&#8203;32 0x000000000231c362 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/clang-trunk/bin/clang-3.9+0x231c362)
#&#8203;33 0x0000000000aecce8 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/clang-trunk/bin/clang-3.9+0xaecce8)
#&#8203;34 0x0000000000aa14de main (/usr/local/clang-trunk/bin/clang-3.9+0xaa14de)
#&#8203;35 0x00007f7719f27ec5 __libc_start_main /build/eglibc-3GlaMS/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;36 0x0000000000ae8d54 _start (/usr/local/clang-trunk/bin/clang-3.9+0xae8d54)
Stack dump:
0.      Program arguments: /usr/local/clang-trunk/bin/clang-3.9 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name small.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -coverage-file /data2/small.cpp -resource-dir /usr/local/clang-trunk/bin/../lib/clang/3.9.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward -internal-isystem /usr/local/include -internal-isystem /usr/local/clang-trunk/bin/../lib/clang/3.9.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /data2 -ferror-limit 19 -fmessage-length 252 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o small.o -x c++ small.cpp
1.      <eof> parser at end of file
2.      small.cpp:10:1: LLVM IR generation of declaration 'main'
3.      small.cpp:10:1: Generating code for declaration 'main'
clang-3.9: error: unable to execute command: Aborted (core dumped)
clang-3.9: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.9.0 (trunk 271877)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
clang-3.9: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3.9: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3.9: note: diagnostic msg: /tmp/small-e29f91.cpp
clang-3.9: note: diagnostic msg: /tmp/small-e29f91.sh
clang-3.9: note: diagnostic msg:

********************
$

-----------------------------------------------------------------

template < class T > void f () {}

template < class T >
class C
{ 
  friend void C < T > (); // should be: friend void f < T > ();
};

int
main ()
{ 
  C < int > c;
  return 0;
}

**Comment by fhahn** [comment]
Clang now produces the following error message and doesn't crash: https://clang.godbolt.org/z/nGTocxeYW


```
source>:6:13: error: no candidate function template was found for dependent friend function template specialization
friend void C < T > (); // should be: friend void f < T > ();
            ^
<source>:4:7: note: candidate ignored: not a function template
class C
      ^
1 error generated.
Compiler returned: 1
```
