### ISSUE TITLE
Crash when using template parameter dependent template alias without appropriate keywords

### ISSUE THREAD

**Issue by jplatte** [llvm/llvm-project#28417]
|  |  |
| --- | --- |
| Bugzilla Link | [28043](https://llvm.org/bz28043) |
| Version | 3.8 |
| OS | Linux |
| Attachments | [Output on stdout (without the bug reporting instructions at the end)](https://user-images.githubusercontent.com/95090772/143753660-39b1ab20-4176-41f6-a41b-d4d9679db3e2.gz), [Preprocessed test case](https://user-images.githubusercontent.com/95090772/143753661-a5a41171-180d-4241-84cc-0e37deff89be.gz), [Crash reproducer script](https://user-images.githubusercontent.com/95090772/143753662-631c3d4c-71f4-4ed1-8e23-2a9192de018c.gz) |
| CC | @DougGregor |

## Extended Description 

The crash seems to happen in 'clang::ASTContext::getTypeInfoImpl(clang::Type const*) const'. I have a 25 line preprocessed test case that I'll attach.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 5: https://godbolt.org/z/fezrTq81d
