### ISSUE TITLE
Build docs shouldn't use relative paths

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28466]
|  |  |
| --- | --- |
| Bugzilla Link | [28092](https://llvm.org/bz28092) |
| Version | unspecified |
| OS | All |
| Attachments | [Patch](https://user-images.githubusercontent.com/60944935/143753692-213f8cf3-66a6-4630-8a75-ae00d8de3c7b.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
http://lldb.llvm.org/build.html#BuildingLldbOnLinux has a couple of places where it says "cmake .." instead of giving a path relative to $llvm or $lldb. It actually recommends keeping the build dir in $llvm/../llvm-build in the previous section, so `cmake ..` won't even work in the recommended version.

Patch attached.

**Comment by DavidSpickett** [comment]
Quick scan doesn't show any relative paths in the current docs. Pull requests welcome to fix any anyone does find.
