### ISSUE TITLE
clang crashes on C++ code with invalid access to a non-existent member: Assertion `DerivationOkay && "Can only be used with a derived-to-base conversion"' failed

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#28545]
|  |  |
| --- | --- |
| Bugzilla Link | [28171](https://llvm.org/bz28171) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
The current clang trunk crashes when compiling the following C++ test case on x86_64-linux-gnu in both 32-bit and 64-bit modes. 

It seems to affect all clang versions since as early as 3.4. 

$ clang++ -v
clang version 3.9.0 (trunk 272993)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$   
$ 
$ clang++ -c small.cpp
clang-3.9: /tmp/llvm-builder/llvm-source-trunk/tools/clang/lib/Sema/SemaDeclCXX.cpp:1765: bool clang::Sema::CheckDerivedToBaseConversion(clang::QualType, clang::QualType, unsigned int, unsigned int, clang::SourceLocation, clang::SourceRange, clang::DeclarationName, clang::CXXCastPath*, bool): Assertion `DerivationOkay && "Can only be used with a derived-to-base conversion"' failed.
#&#8203;0 0x0000000001d1b425 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/clang-trunk/bin/clang-3.9+0x1d1b425)
#&#8203;1 0x0000000001d192b6 llvm::sys::RunSignalHandlers() (/usr/local/clang-trunk/bin/clang-3.9+0x1d192b6)
#&#8203;2 0x0000000001d194d4 SignalHandler(int) (/usr/local/clang-trunk/bin/clang-3.9+0x1d194d4)
#&#8203;3 0x00007fe5042f0340 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10340)
#&#8203;4 0x00007fe50350ecc9 gsignal /build/eglibc-3GlaMS/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;5 0x00007fe5035120d8 abort /build/eglibc-3GlaMS/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;6 0x00007fe503507b86 __assert_fail_base /build/eglibc-3GlaMS/eglibc-2.19/assert/assert.c:92:0
#&#8203;7 0x00007fe503507c32 (/lib/x86_64-linux-gnu/libc.so.6+0x2fc32)
#&#8203;8 0x0000000002b1f9a1 clang::Sema::CheckDerivedToBaseConversion(clang::QualType, clang::QualType, unsigned int, unsigned int, clang::SourceLocation, clang::SourceRange, clang::DeclarationName, llvm::SmallVector<clang::CXXBaseSpecifier*, 4u>*, bool) (/usr/local/clang-trunk/bin/clang-3.9+0x2b1f9a1)
#&#8203;9 0x0000000002b1f9e3 clang::Sema::CheckDerivedToBaseConversion(clang::QualType, clang::QualType, clang::SourceLocation, clang::SourceRange, llvm::SmallVector<clang::CXXBaseSpecifier*, 4u>*, bool) (/usr/local/clang-trunk/bin/clang-3.9+0x2b1f9e3)
#&#8203;10 0x0000000002b86aa1 clang::Sema::PerformObjectMemberConversion(clang::Expr*, clang::NestedNameSpecifier*, clang::NamedDecl*, clang::NamedDecl*) (/usr/local/clang-trunk/bin/clang-3.9+0x2b86aa1)
#&#8203;11 0x0000000002c3c5aa BuildFieldReferenceExpr(clang::Sema&, clang::Expr*, bool, clang::SourceLocation, clang::CXXScopeSpec const&, clang::FieldDecl*, clang::DeclAccessPair, clang::DeclarationNameInfo const&) (/usr/local/clang-trunk/bin/clang-3.9+0x2c3c5aa)
#&#8203;12 0x0000000002c42848 clang::Sema::BuildMemberReferenceExpr(clang::Expr*, clang::QualType, clang::SourceLocation, bool, clang::CXXScopeSpec const&, clang::SourceLocation, clang::NamedDecl*, clang::LookupResult&, clang::TemplateArgumentListInfo const*, clang::Scope const*, bool, clang::Sema::ActOnMemberAccessExtraArgs*) (/usr/local/clang-trunk/bin/clang-3.9+0x2c42848)
#&#8203;13 0x0000000002c43b3c std::_Function_handler<clang::ActionResult<clang::Expr*, true> (clang::Sema&, clang::TypoExpr*, clang::TypoCorrection), LookupMemberExprInRecord(clang::Sema&, clang::LookupResult&, clang::Expr*, clang::RecordType const*, clang::SourceLocation, bool, clang::CXXScopeSpec&, bool, clang::TypoExpr*&)::{lambda(clang::Sema&, clang::TypoExpr*, clang::TypoCorrection)#2}>::_M_invoke(std::_Any_data const&, clang::Sema&, clang::TypoExpr*, clang::TypoCorrection) (/usr/local/clang-trunk/bin/clang-3.9+0x2c43b3c)
#&#8203;14 0x0000000002bfb3fd std::function<clang::ActionResult<clang::Expr*, true> (clang::Sema&, clang::TypoExpr*, clang::TypoCorrection)>::operator()(clang::Sema&, clang::TypoExpr*, clang::TypoCorrection) const (/usr/local/clang-trunk/bin/clang-3.9+0x2bfb3fd)
#&#8203;15 0x0000000002c1b079 clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformExpr(clang::Expr*) (/usr/local/clang-trunk/bin/clang-3.9+0x2c1b079)
#&#8203;16 0x0000000002c28558 clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformBinaryOperator(clang::BinaryOperator*) (/usr/local/clang-trunk/bin/clang-3.9+0x2c28558)
#&#8203;17 0x0000000002c1ae28 clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformExpr(clang::Expr*) (/usr/local/clang-trunk/bin/clang-3.9+0x2c1ae28)
#&#8203;18 0x0000000002c1beb9 (anonymous namespace)::TransformTypos::TryTransform(clang::Expr*) (/usr/local/clang-trunk/bin/clang-3.9+0x2c1beb9)
#&#8203;19 0x0000000002c1867d clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) (/usr/local/clang-trunk/bin/clang-3.9+0x2c1867d)
#&#8203;20 0x0000000002c19903 clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool, bool) (/usr/local/clang-trunk/bin/clang-3.9+0x2c19903)
#&#8203;21 0x0000000002d430f0 clang::Sema::ActOnExprStmt(clang::ActionResult<clang::Expr*, true>) (/usr/local/clang-trunk/bin/clang-3.9+0x2d430f0)
#&#8203;22 0x0000000002874bbd clang::Parser::ParseExprStatement() (/usr/local/clang-trunk/bin/clang-3.9+0x2874bbd)
#&#8203;23 0x000000000287206f clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedContsructsKind, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/usr/local/clang-trunk/bin/clang-3.9+0x287206f)
#&#8203;24 0x00000000028721ce clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedContsructsKind, clang::SourceLocation*) (/usr/local/clang-trunk/bin/clang-3.9+0x28721ce)
#&#8203;25 0x00000000028767b9 clang::Parser::ParseCompoundStatementBody(bool) (/usr/local/clang-trunk/bin/clang-3.9+0x28767b9)
#&#8203;26 0x0000000002879009 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/usr/local/clang-trunk/bin/clang-3.9+0x2879009)
#&#8203;27 0x00000000027f76eb clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/usr/local/clang-trunk/bin/clang-3.9+0x27f76eb)
#&#8203;28 0x00000000028175dd clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, unsigned int, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/usr/local/clang-trunk/bin/clang-3.9+0x28175dd)
#&#8203;29 0x00000000027f330d clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/usr/local/clang-trunk/bin/clang-3.9+0x27f330d)
#&#8203;30 0x00000000027f39b1 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) [clone .part.222] (/usr/local/clang-trunk/bin/clang-3.9+0x27f39b1)
#&#8203;31 0x00000000027f39ef clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/usr/local/clang-trunk/bin/clang-3.9+0x27f39ef)
#&#8203;32 0x00000000027f8860 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/usr/local/clang-trunk/bin/clang-3.9+0x27f8860)
#&#8203;33 0x00000000027f9030 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/usr/local/clang-trunk/bin/clang-3.9+0x27f9030)
#&#8203;34 0x00000000027f065b clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/clang-trunk/bin/clang-3.9+0x27f065b)
#&#8203;35 0x0000000002486d3e clang::CodeGenAction::ExecuteAction() (/usr/local/clang-trunk/bin/clang-3.9+0x2486d3e)
#&#8203;36 0x00000000021977fe clang::FrontendAction::Execute() (/usr/local/clang-trunk/bin/clang-3.9+0x21977fe)
#&#8203;37 0x000000000216d266 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/clang-trunk/bin/clang-3.9+0x216d266)
#&#8203;38 0x00000000022245c2 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/clang-trunk/bin/clang-3.9+0x22245c2)
#&#8203;39 0x0000000000af0548 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/clang-trunk/bin/clang-3.9+0xaf0548)
#&#8203;40 0x0000000000aa46dc main (/usr/local/clang-trunk/bin/clang-3.9+0xaa46dc)
#&#8203;41 0x00007fe5034f9ec5 __libc_start_main /build/eglibc-3GlaMS/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;42 0x0000000000aec5b4 _start (/usr/local/clang-trunk/bin/clang-3.9+0xaec5b4)
Stack dump:
0.	Program arguments: /usr/local/clang-trunk/bin/clang-3.9 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name small.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -coverage-file /data2/small.cpp -resource-dir /usr/local/clang-trunk/bin/../lib/clang/3.9.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward -internal-isystem /usr/local/include -internal-isystem /usr/local/clang-trunk/bin/../lib/clang/3.9.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /data2 -ferror-limit 19 -fmessage-length 128 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o small.o -x c++ small.cpp 
1.	small.cpp:11:3: current parser token 'return'
2.	small.cpp:8:1: parsing function body 'main'
3.	small.cpp:8:1: in compound statement ('{}')
clang-3.9: error: unable to execute command: Aborted (core dumped)
clang-3.9: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.9.0 (trunk 272993)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
clang-3.9: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3.9: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3.9: note: diagnostic msg: /tmp/small-7e5974.cpp
clang-3.9: note: diagnostic msg: /tmp/small-7e5974.sh
clang-3.9: note: diagnostic msg: 

********************
$ 

------------------------------

struct A { int i; };

struct B {};

struct C: A, B {};

int main ()
{
  C c;
  c.B::i = 0;
  return 0; 
}

**Comment by fhahn** [comment]
Clang now generates the following error message and does not crash: https://godbolt.org/z/PqfaYbeeY

```
<source>:10:6: error: no member named 'i' in 'B'
c.B::i = 0;
~    ^
```
