### ISSUE TITLE
clang crashes on C++11 code with invalid use of decltype: Assertion `CachedTokens[CachedLexPos-1].getLastLoc() == Tok.getAnnotationEndLoc() && "The annotation should be until the most recent cached token"' failed

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#28548]
|  |  |
| --- | --- |
| Bugzilla Link | [28174](https://llvm.org/bz28174) |
| Version | trunk |
| OS | All |
| CC | @compnerd,@DougGregor,@hfinkel |

## Extended Description 
The current clang trunk crashes when compiling the following C++11 test case on x86_64-linux-gnu in both 32-bit and 64-bit modes. 

It is a regression from 3.8.x.

$ clang++ -v
clang version 3.9.0 (trunk 272993)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$
$ clang++ -c -std=c++11 small.cpp
small.cpp:4:19: error: expected '(' after 'decltype'
void foo (decltype x);
                  ^
                  (
clang-3.9: /tmp/llvm-builder/llvm-source-trunk/tools/clang/lib/Lex/PPCaching.cpp:101: void clang::Preprocessor::AnnotatePreviousCachedTokens(const clang::Token&): Assertion `CachedTokens[CachedLexPos-1].getLastLoc() == Tok.getAnnotationEndLoc() && "The annotation should be until the most recent cached token"' failed.
#&#8203;0 0x0000000001d1b425 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/clang-trunk/bin/clang-3.9+0x1d1b425)
#&#8203;1 0x0000000001d192b6 llvm::sys::RunSignalHandlers() (/usr/local/clang-trunk/bin/clang-3.9+0x1d192b6)
#&#8203;2 0x0000000001d194d4 SignalHandler(int) (/usr/local/clang-trunk/bin/clang-3.9+0x1d194d4)
#&#8203;3 0x00007f7df46c0340 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10340)
#&#8203;4 0x00007f7df38decc9 gsignal /build/eglibc-3GlaMS/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;5 0x00007f7df38e20d8 abort /build/eglibc-3GlaMS/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;6 0x00007f7df38d7b86 __assert_fail_base /build/eglibc-3GlaMS/eglibc-2.19/assert/assert.c:92:0
#&#8203;7 0x00007f7df38d7c32 (/lib/x86_64-linux-gnu/libc.so.6+0x2fc32)
#&#8203;8 0x0000000003443736 clang::Preprocessor::AnnotatePreviousCachedTokens(clang::Token const&) (/usr/local/clang-trunk/bin/clang-3.9+0x3443736)
#&#8203;9 0x000000000284510c clang::Parser::ParseOptionalCXXScopeSpecifier(clang::CXXScopeSpec&, clang::OpaquePtr<clang::QualType>, bool, bool*, bool, clang::IdentifierInfo**) (/usr/local/clang-trunk/bin/clang-3.9+0x284510c)
#&#8203;10 0x00000000027f97a5 clang::Parser::TryAnnotateTypeOrScopeToken(bool, bool) (/usr/local/clang-trunk/bin/clang-3.9+0x27f97a5)
#&#8203;11 0x0000000002889bbc clang::Parser::isCXXDeclarationSpecifier(clang::Parser::TPResult, bool*) (/usr/local/clang-trunk/bin/clang-3.9+0x2889bbc)
#&#8203;12 0x000000000288bd08 clang::Parser::TryParseParameterDeclarationClause(bool*, bool) (/usr/local/clang-trunk/bin/clang-3.9+0x288bd08)
#&#8203;13 0x000000000288bfe9 clang::Parser::isCXXFunctionDeclarator(bool*) (/usr/local/clang-trunk/bin/clang-3.9+0x288bfe9)
#&#8203;14 0x000000000281c7c6 clang::Parser::ParseDirectDeclarator(clang::Declarator&) (/usr/local/clang-trunk/bin/clang-3.9+0x281c7c6)
#&#8203;15 0x00000000028138e3 clang::Parser::ParseDeclaratorInternal(clang::Declarator&, void (clang::Parser::*)(clang::Declarator&)) (/usr/local/clang-trunk/bin/clang-3.9+0x28138e3)
#&#8203;16 0x0000000002814b52 clang::Parser::ParseDeclarator(clang::Declarator&) (/usr/local/clang-trunk/bin/clang-3.9+0x2814b52)
#&#8203;17 0x0000000002816c26 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, unsigned int, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/usr/local/clang-trunk/bin/clang-3.9+0x2816c26)
#&#8203;18 0x00000000027f330d clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/usr/local/clang-trunk/bin/clang-3.9+0x27f330d)
#&#8203;19 0x00000000027f39b1 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) [clone .part.222] (/usr/local/clang-trunk/bin/clang-3.9+0x27f39b1)
#&#8203;20 0x00000000027f39ef clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/usr/local/clang-trunk/bin/clang-3.9+0x27f39ef)
#&#8203;21 0x00000000027f8860 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/usr/local/clang-trunk/bin/clang-3.9+0x27f8860)
#&#8203;22 0x00000000027f9030 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/usr/local/clang-trunk/bin/clang-3.9+0x27f9030)
#&#8203;23 0x00000000027f065b clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/clang-trunk/bin/clang-3.9+0x27f065b)
#&#8203;24 0x0000000002486d3e clang::CodeGenAction::ExecuteAction() (/usr/local/clang-trunk/bin/clang-3.9+0x2486d3e)
#&#8203;25 0x00000000021977fe clang::FrontendAction::Execute() (/usr/local/clang-trunk/bin/clang-3.9+0x21977fe)
#&#8203;26 0x000000000216d266 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/clang-trunk/bin/clang-3.9+0x216d266)
#&#8203;27 0x00000000022245c2 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/clang-trunk/bin/clang-3.9+0x22245c2)
#&#8203;28 0x0000000000af0548 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/clang-trunk/bin/clang-3.9+0xaf0548)
#&#8203;29 0x0000000000aa46dc main (/usr/local/clang-trunk/bin/clang-3.9+0xaa46dc)
#&#8203;30 0x00007f7df38c9ec5 __libc_start_main /build/eglibc-3GlaMS/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;31 0x0000000000aec5b4 _start (/usr/local/clang-trunk/bin/clang-3.9+0xaec5b4)
Stack dump:
0.      Program arguments: /usr/local/clang-trunk/bin/clang-3.9 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name small.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -coverage-file /data2/c-hunter/test/fun/try5b/llvm-source/RES8/20160616-clang++-trunk-O0-m32-build-053959/small.cpp -resource-dir /usr/local/clang-trunk/bin/../lib/clang/3.9.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward -internal-isystem /usr/local/include -internal-isystem /usr/local/clang-trunk/bin/../lib/clang/3.9.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /data2/c-hunter/test/fun/try5b/llvm-source/RES8/20160616-clang++-trunk-O0-m32-build-053959 -ferror-limit 19 -fmessage-length 226 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o small.o -x c++ small.cpp
1.      small.cpp:4:11: at annotation token
clang-3.9: error: unable to execute command: Aborted (core dumped)
clang-3.9: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.9.0 (trunk 272993)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
clang-3.9: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3.9: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3.9: note: diagnostic msg: /tmp/small-5f4458.cpp
clang-3.9: note: diagnostic msg: /tmp/small-5f4458.sh
clang-3.9: note: diagnostic msg:

********************
$

---------------------------------------

int x;

// should be: void foo (decltype (x));
void foo (decltype x);

**Comment by fhahn** [comment]
Clang now produces the following error message and does not crash: https://godbolt.org/z/Krz44xnxa


```
<source>:6:14: error: expected '(' after 'decltype'
Foo (decltype::initializer_list < int >);
             ^
             (
<source>:6:41: error: expected ')'
Foo (decltype::initializer_list < int >);
                                        ^
<source>:6:5: note: to match this '('
Foo (decltype::initializer_list < int >);
    ^
<source>:12:19: error: expected '(' after 'decltype'
void foo (decltype x);
                  ^
                  (
<source>:12:22: error: expected ')'
void foo (decltype x);
                     ^
<source>:12:10: note: to match this '('
void foo (decltype x);
         ^
4 errors generated.
Compiler returned: 1
```
