### ISSUE TITLE
Add locale conversion support in std::experimental::filesystem

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28551]
|  |  |
| --- | --- |
| Bugzilla Link | [28177](https://llvm.org/bz28177) |
| Version | unspecified |
| OS | All |
| Blocks | llvm/llvm-project#37767  |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@mclow |

## Extended Description 
This is the only feature missing from the current filesystem implementation.
Adding a bug to track the progress of this feature.

**Comment by philnik777** [comment]
`experimental::filesystem` has been removed a while ago.
