### ISSUE TITLE
Android make - out of memory?!

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28565]
|  |  |
| --- | --- |
| Bugzilla Link | [28191](https://llvm.org/bz28191) |
| Version | 3.8 |
| OS | Linux |
| Attachments | [Requested files](https://user-images.githubusercontent.com/60944935/143753757-e0885d23-f131-4360-aadd-838d4495ef62.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 

[ 20% 5058/25035] host C++: libartd <=...points/quick/quick_lock_entrypoints.cc
FAILED: /bin/bash -c "(PWD=/proc/self/cwd prebuilts/misc/linux-x86/ccache/ccache prebuilts/clang/host/linux-x86/clang-2812033/bin/clang++ 	-I external/gtest/include -I external/icu/icu4c/source/common -I external/lz4/lib -I external/valgrind/include -I external/valgrind -I external/vixl/src -I external/zlib -I bionic/libc/private -I art/cmdline -I art/sigchainlib -I art -I art/runtime -I /home/dans/out/source/host/linux-x86/obj/SHARED_LIBRARIES/libartd_intermediates -I /home/dans/out/source/host/linux-x86/gen/SHARED_LIBRARIES/libartd_intermediates -I libnativehelper/include/nativehelper \$(cat /home/dans/out/source/host/linux-x86/obj/SHARED_LIBRARIES/libartd_intermediates/import_includes) -isystem system/core/include -isystem system/media/audio/include -isystem hardware/libhardware/include -isystem hardware/libhardware_legacy/include -isystem hardware/ril/include -isystem libnativehelper/include -isystem frameworks/native/include -isystem frameworks/native/opengl/include -isystem frameworks/av/include -isystem frameworks/base/include -isystem /home/dans/out/source/host/linux-x86/obj/include -c  -fno-exceptions -Wno-multichar -Wa,--noexecstack -fPIC -no-canonical-prefixes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -O2 -g -fno-strict-aliasing --gcc-toolchain=prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8 --sysroot prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/sysroot -fstack-protector-strong -m64 -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -DNDEBUG -UDEBUG -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics   -target x86_64-linux-gnu -Bprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/x86_64-linux/bin  -Wsign-promo -Wno-inconsistent-missing-override -isystem prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/x86_64-linux/include/c++/4.8 -isystem prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/x86_64-linux/include/c++/4.8/backward -isystem prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/x86_64-linux/include/c++/4.8/x86_64-linux  -DBUILDING_LIBART=1 -Wthread-safety -Wthread-safety-negative -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wmissing-noreturn -fno-omit-frame-pointer -fno-rtti -std=gnu++11 -ggdb3 -Wall -Werror -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -DART_DEFAULT_GC_TYPE_IS_CMS -DIMT_SIZE=43 -DART_BASE_ADDRESS=0x60000000 -DART_DEFAULT_INSTRUCTION_SET_FEATURES=default -DART_ENABLE_CODEGEN_arm -DART_ENABLE_CODEGEN_arm64 -DART_ENABLE_CODEGEN_mips -DART_ENABLE_CODEGEN_mips64 -DART_ENABLE_CODEGEN_x86 -DART_ENABLE_CODEGEN_x86_64 -DART_BASE_ADDRESS_MIN_DELTA=-0x1000000 -DART_BASE_ADDRESS_MAX_DELTA=0x1000000 -DART_DEFAULT_INSTRUCTION_SET_FEATURES=\"default\" -O2 -DDYNAMIC_ANNOTATIONS_ENABLED=1 -UNDEBUG -fPIC -D_USING_LIBCXX -DANDROID_STRICT -std=gnu++14 -nostdinc++  -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast  -Werror=address-of-temporary -Werror=null-dereference -Werror=return-type    -MD -MF /home/dans/out/source/host/linux-x86/obj/SHARED_LIBRARIES/libartd_intermediates/entrypoints/quick/quick_lock_entrypoints.d -o /home/dans/out/source/host/linux-x86/obj/SHARED_LIBRARIES/libartd_intermediates/entrypoints/quick/quick_lock_entrypoints.o art/runtime/entrypoints/quick/quick_lock_entrypoints.cc ) && (cp /home/dans/out/source/host/linux-x86/obj/SHARED_LIBRARIES/libartd_intermediates/entrypoints/quick/quick_lock_entrypoints.d /home/dans/out/source/host/linux-x86/obj/SHARED_LIBRARIES/libartd_intermediates/entrypoints/quick/quick_lock_entrypoints.P; sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\\\\$//' -e '/^\$/ d' -e 's/\$/ :/' < /home/dans/out/source/host/linux-x86/obj/SHARED_LIBRARIES/libartd_intermediates/entrypoints/quick/quick_lock_entrypoints.d >> /home/dans/out/source/host/linux-x86/obj/SHARED_LIBRARIES/libartd_intermediates/entrypoints/quick/quick_lock_entrypoints.P; rm -f /home/dans/out/source/host/linux-x86/obj/SHARED_LIBRARIES/libartd_intermediates/entrypoints/quick/quick_lock_entrypoints.d )"
clang++: error: unable to execute command: Segmentation fault
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Android clang version 3.8.256229  (based on LLVM 3.8.256229)
Target: x86_64--linux-gnu
Thread model: posix
InstalledDir: prebuilts/clang/host/linux-x86/clang-2812033/bin
clang++: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/quick_lock_entrypoints-c80c3c.cpp
clang++: note: diagnostic msg: /tmp/quick_lock_entrypoints-c80c3c.sh
clang++: note: diagnostic msg: 

********************
[ 20% 5060/25035] Building with Jack: ...work_intermediates/dex-dir/classes.dex
FAILED: /bin/bash /home/dans/out/source/target/common/obj/JAVA_LIBRARIES/framework_intermediates/dex-dir/classes.dex.rsp
Out of memory error (version 1.2-rc4 'Carnac' (298900 f95d7bdecfceb327f9d201a1348397ed8a843843 by android-jack-team@google.com)).
GC overhead limit exceeded.
Try increasing heap size with java option '-Xmx<size>'.
Warning: This may have produced partial or corrupted output.
ninja: build stopped: subcommand failed.
make: *** [ninja_wrapper] Error 1

#### make failed to build some targets (01:06:27 (hh:mm:ss)) ####

**Comment by Endilll** [comment]
Can't reproduce Clang 3.7 through 3.9 with assertions enabled.
