### ISSUE TITLE
[mc] flat_load -- with tfe, fetch-dest size shall be inreased by 1.

### ISSUE THREAD

**Issue by e7b993e6-0c19-4c7b-abbd-20f032a343c0** [llvm/llvm-project#28604]
|  |  |
| --- | --- |
| Bugzilla Link | [28230](https://llvm.org/bz28230) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [00008.tests_tg_gfx7_asm_lit1_bug.06.08.min.flat_load-tfe.zip](https://user-images.githubusercontent.com/92601306/143753791-1ec3a480-5da7-4274-b0c1-836ea4a39f96.gz) |
| CC | @atamazov,@dpreobra,@arsenm |

## Extended Description 

GCN ISA spec says:
TFE -- Texel Fail Enable for PRT (partially resident textures). When set to 1, fetch can return a NACK that causes a VGPR write into DST+1 (first GPR after all fetch-dest GPRs).

Examples:
> flat_load_dword v2, v[0:1] // correct
> flat_load_dword v[2:3], v[0:1] tfe // fails

Tested with r273139 (git # 4a94acfea8bfd6eb6b5809dd40f03e1fa42e673a)

Some GFX7 lit tests attached.

Similar problem with flat_atomic insns.

**Comment by arsenm** [comment]
Since it was dropped in current hardware it's probably not worth adding legacy assembler support for TFE support for flat
