### ISSUE TITLE
lli / JIT bug in KMeans

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#2865]
|  |  |
| --- | --- |
| Bugzilla Link | [2493](https://llvm.org/bz2493) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Defines.common.mk](https://user-images.githubusercontent.com/60944935/143738038-17deed16-cc73-4ee3-b706-c34f6b602fc0.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@sunfishcode |

## Extended Description 
I see sth that looks like an lli/JIT bug. The program is the KMeans benchmark from the STAMP benchmark suite (http://stamp.stanford.edu). 
Overwrite ./common/Defines.common.mk with the attached files to make CC/LD 
customizable.

in ./kmeans, for
./kmeans -m40 -n40 -t0.00001 -i inputs/random-n65536-d32-c16.txt -p 1 :

make -f Makefile.seq clean

CC='llvm-gcc' LD='llvm-gcc -lm' make -f Makefile.seq
-->works, but is slower than gcc (35s vs 16s on my Intel 32b system)

CC='llvm-gcc -emit-llvm' LD='llvm-ld -lm' make -f Makefile.seq
--> does not work (lot's of NaN's in the output, and much faster (11s)) and uses lli

CC='llvm-gcc -emit-llvm' LD='llvm-ld -lm -disable-opt' make -f Makefile.seq
--> does not work either, and uses lli

CC='llvm-gcc -emit-llvm' LD='llvm-ld -lm -disable-opt -native' make -f --> 
looks as if it would work (and is faster, 16s)

CC='llvm-gcc -emit-llvm' LD='llvm-ld -lm -native' make -f Makefile.seq
--> looks as if it would work (and is faster, 16s)

CC='llvm-gcc -emit-llvm' LD='llvm-ld -link-as-library' make -f Makefile.seq
llc -f -o kmeans.s kmeans
gcc -o kmeans kmeans.s -lm -lpthread
--> looks as if it would work (and is faster, 16s)

**Comment by nunoplopes** [comment]
Closing old bug; llvm-gcc doesn't exist anymore.
