### ISSUE TITLE
Clang crashes when creating a this expression during template instantiation

### ISSUE THREAD

**Issue by Weverything** [llvm/llvm-project#28658]
|  |  |
| --- | --- |
| Bugzilla Link | [28284](https://llvm.org/bz28284) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
template <typename T>
struct Foo {
  void (*function)() = [this]() -> void { auto x = s1.s2.ptr; };

  struct S1 {
    struct S2 {
      int* ptr;
    };
    S2 s2;
  };

  S1 s1;
};

void run() { new Foo<int>(); }

From lib/Sema/TreeTransform.h:
template<typename Derived>
ExprResult
TreeTransform<Derived>::TransformCXXThisExpr(CXXThisExpr *E) {
  QualType T = getSema().getCurrentThisType();

  if (!getDerived().AlwaysRebuild() && T == E->getType()) {
    // Make sure that we capture 'this'.
    getSema().CheckCXXThisCapture(E->getLocStart());
    return E;
  }

  return getDerived().RebuildCXXThisExpr(E->getLocStart(), T, E->isImplicit());
}

In TransformCXXThisExpr, getSema().getCurrentType() returns a empty QualType.  This is passed to function RebuildCXXThisExpr, which expects the QualType to be a valid Type.

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.8 and 3.9: https://godbolt.org/z/a8odd1YEW
