### ISSUE TITLE
LLDB can't find split debug info if the debuggee has been moved from build directory

### ISSUE THREAD

**Issue by vadimcn** [llvm/llvm-project#28667]
|  |  |
| --- | --- |
| Bugzilla Link | [28293](https://llvm.org/bz28293) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
(This situation often arises when build servers are employed)

I think this happens because LLDB simply takes DW_AT_comp_dir at the face value here: https://github.com/llvm-mirror/lldb/blob/876d71dc6c37f23c8ae9d219705d06c6def3f354/source/Plugins/SymbolFile/DWARF/SymbolFileDWARF.cpp#L1778-1794

There should be a way to remap debug info paths similarly to what is done for source with 'target.source-map'.  I would even argue that it should be the same setting for both.

Another good candidate seems to be the 'target.debug-file-search-paths' setting.  LLDB could probe each of these directories (also probably the directory where the debuggee is located) combined with the value of DW_AT_GNU_dwo_name.

**Comment by lenary** [comment]
I think I'm running into the same problem, but I've also made a reproducer (sorry, it's a long self-contained bash script). My reproducer doesn't rely on moving any images, it does rely on trying to execute the debugee from different directory though. It likely also relies on the `-fdebug-prefix-map` making the directory _look_ relative, even if it isn't.

In short, `gdb` will always show the example's local variables and source, even when compiling with `-gsplit-dwarf`. `lldb` will only show the locals when you do not compile with `-gsplit-dwarf`.

I've been using `CC=clang-14` on Ubuntu Focal (20.04), and have reproduced the behaviour with:
- `lldb-14` from apt.llvm.org
- `lldb` built from source https://reviews.llvm.org/rG81767f52f49339be2c78fc9bf831856b9f57e2f0

```
#!/bin/bash

set -e

# Set GDB, LLDB, and CC correctly. CC should be a C compiler.
# and with 
: "${GDB:=gdb}"
: "${LLDB:=lldb}"
: "${CC:=cc}"

comp_dir="${PWD}/tmp"
mkdir -p "${comp_dir}"

lldb_flags=(-g "-fdebug-prefix-map=${comp_dir}=." -gsplit-dwarf)
gdb_flags=(-g -gdwarf-4 "-fdebug-prefix-map=${comp_dir}=." -gsplit-dwarf)

echo "[] Deleting old files"
find "${comp_dir}" -print0 | xargs -0 rm -rf

echo "[] Creating C file"
(
  mkdir -p "${comp_dir}/a/b/c/d"
  cat > "${comp_dir}/a/b/c/d/main.c" <<END_C
#include <stdio.h>

int main(void) {
    int num_times = 5;
    char *string = "foo bar baz";
    for (int i = 0; i < num_times; i++) {
        puts(string);
    }
    return 0;
}
END_C
)

echo "[] Compiling in ${comp_dir}/a/b"
(
  cd "${comp_dir}/a/b"

  "${CC}" -O0 -c "${lldb_flags[@]}" \
    c/d/main.c \
    -o c/d/main_lldb.o

  "${CC}" -O0 -c "${gdb_flags[@]}" \
    c/d/main.c \
    -o c/d/main_gdb.o
)

echo "[] Linking in ${comp_dir}/a"
(
  cd "${comp_dir}/a"

  "${CC}" "${lldb_flags[@]}" \
    "${comp_dir}/a/b/c/d/main_lldb.o" \
    -o "${comp_dir}/a/main_lldb"

  "${CC}" "${lldb_flags[@]}" \
    "${comp_dir}/a/b/c/d/main_gdb.o" \
    -o "${comp_dir}/a/main_gdb"
)

(
  echo "set substitute-path . ${comp_dir}"
  echo "set debug-file-directory ${comp_dir}"

  echo "file ${comp_dir}/a/main_gdb"

  echo "break main"
  echo "break main.c:7"
  echo "run"

  echo "list"
  echo "info locals"
  echo "continue"

  echo "list"
  echo "info locals"
) > "${comp_dir}/gdb-commands"

(
  echo "settings append target.source-map . ${comp_dir}"
  echo "settings append target.debug-file-search-paths ${comp_dir}"

  echo "target create ${comp_dir}/a/main_lldb"

  echo "breakpoint set -b main"
  echo "breakpoint set -y main.c:7"
  echo "process launch --"

  echo "source list"
  echo "frame variable"
  echo "continue"

  echo "source list"
  echo "frame variable"
) > "${comp_dir}/lldb-commands"

echo "[] Debugging with gdb in ${comp_dir}/e"
(
  mkdir -p "${comp_dir}/e"
  cd "${comp_dir}/e"

  "${GDB}" --nx \
    "--command=${comp_dir}/gdb-commands" \
    --batch \
    | tee "${comp_dir}/gdb.out"
)

echo "[] Debugging with lldb in ${comp_dir}/e)"
(
  mkdir -p "${comp_dir}/e"
  cd "${comp_dir}/e"

  "${LLDB}" --no-lldbinit \
    --source "${comp_dir}/lldb-commands" \
    --batch \
    | tee "${comp_dir}/lldb.out"
)
```

There have been improvements since I started preparing this reproducer with lldb-14:
- Listings are now produced
- You print some warnings about dwo's/dwp's:

after target create, I now get:
```
warning: (x86_64) <PWD>/tmp/a/main_lldb unable to locate separate debug file (dwo, dwp). Debugging will be degraded.
```

and after frame variable, I now get:
```
error: unable to locate .dwo debug file "<PWD>/tmp/a/a/b/c/d/main_lldb.dwo" for skeleton DIE 0x0000000000000014
```

**Comment by DavidSpickett** [comment]
https://reviews.llvm.org/D157609 fixes the reproducer you have by searching debug file dirs for relative dwo files. It's work in progress, when I get a chance I'll add some proper testing. It at least doesn't break any existing tests.

**Comment by DavidSpickett** [comment]
https://reviews.llvm.org/D157609 updated and now in review.

**Comment by DavidSpickett** [comment]
This is now fixed, mostly.

You can now use the `target.debug-file-search-paths` setting to help lldb find DWO files. If you find a situation that doesn't work and you want to be extra nice when you report it, you can modify one of the tests at `lldb/test/Shell/SymbolFile/DWARF/dwo-*` to match your use case.
