### ISSUE TITLE
Assertion failed 'cannot emit delegate call arguments for inalloca arguments' in certain cases involving lambdas

### ISSUE THREAD

**Issue by pcc** [llvm/llvm-project#28673]
|  |  |
| --- | --- |
| Bugzilla Link | [28299](https://llvm.org/bz28299) |
| Version | trunk |
| OS | Windows XP |
| CC | @majnemer,@zmodem,@k15tfu,@nico,@zygoloid,@rnk,@ZequanWu |

## Extended Description 
e.g.
https://build.chromium.org/p/chromium.fyi/builders/ClangToTWin/builds/8593/steps/compile/logs/stdio
https://build.chromium.org/p/chromium.fyi/builders/CrWinClang/builds/10185/steps/compile/logs/stdio

Working on reproducer.

**Comment by rnk** [comment]
+@amykhuang

**Comment by amykhuang** [comment]
Looks like the compiler doesn't crash if we just remove the error that @rnk added back in.. 2018? I wonder what happened.

**Comment by efriedma-quic** [comment]
See https://reviews.llvm.org/D137872

**Comment by nico** [comment]
015049338d7e8e0e81f2ad2f94e5a43e2e3f5220

**Comment by pkasting** [comment]
This should be reopened as the patch was reverted.

**Comment by rnk** [comment]
It actually relanded just yesterday as 27dab4d305acb6e0935e014c061c5317016ae2b3, and I think no issues have been found so far.
