### ISSUE TITLE
[PM] Use new PM in production for Clang, LLD, libLTO, etc. middle-end

### ISSUE THREAD

**Issue by silvasean** [llvm/llvm-project#28697]
|  |  |
| --- | --- |
| Bugzilla Link | [28323](https://llvm.org/bz28323) |
| Version | unspecified |
| OS | Linux |
| Blocks | llvm/llvm-project#28696  |
| CC | @hfinkel,@sanjoy |

## Extended Description 
This bug tracks progress towards moving the main middle-end compilation codepath of Clang, LLD, libLTO, etc. to the new PM.

Clang will be the most work for this. Essentially the entirety of PassManagerBuilder in lib/Transforms/IPO/PassManagerBuilder.cpp needs to be ported, including the "extension" point stuff.

The part of PassBuilder (lib/Passes/PassBuilder.cpp) which seems intended to replace PassManagerBuilder is mostly FIXME's at the time of this writing.

Porting the LTO use case seems like a good first step.

**Comment by Endilll** [comment]
This was done several releases ago.
