### ISSUE TITLE
BDNZ not generated for simple loops

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28737]
|  |  |
| --- | --- |
| Bugzilla Link | [28363](https://llvm.org/bz28363) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@nemanjai,@sanjoy |

## Extended Description 
For many loops, sometimes very simple ones like:

     for (i = 0; i < m; i++)
        sum += b[i]*a[i];

Where sum, a and b are single precision float (arrays), we do not generate bdnz, and instead use, three instructions in the loop. (add, compare, branch-conditional).

I looked at one of the loops like this and Scalar Evolution was not able to compute loop iteration count. When the loop is not unrolled (compile with -fno-unroll-loops) this is not an issue. Also for the residue loops of an unrolled loop we generate bdnz.

**Comment by chenzheng1030** [comment]
https://godbolt.org/z/a7a9TdcMh 

The sources in this issue now generates bdnz as expected.

I'll close this issue first. Some BDNZ loops are not generated is some kind of expected. See lit cases like ctrloop-*.ll. There are FIXMEs there too.
