### ISSUE TITLE
Thread local variables are not working on Linux

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28766]
|  |  |
| --- | --- |
| Bugzilla Link | [28392](https://llvm.org/bz28392) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The "packages/Python/lldbsuite/test/lang/c/tls_globals" test is broken on Linux. It seemed to be ok only because before TLS support was added to Darwin, it was being expected failed by the following decorator:

     @&#8203;unittest2.expectedFailure("rdar://7796742")

once I fixed Darwin, the buildbots started to fail on linux. Not sure which other OS variants will be failing as well, so I added back a:

     @&#8203;unittest2.expectedFailure("now works on Darwin, but not linux")

**Comment by jeffreytan81** [comment]
https://github.com/llvm/llvm-project/pull/67470
