### ISSUE TITLE
c++'1z component of clang does not cc llvmbugs by default

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#28770]
|  |  |
| --- | --- |
| Bugzilla Link | [28396](https://llvm.org/bz28396) |
| Version | unspecified |
| OS | All |
| CC | @tlattner |

## Extended Description 
Clang's "C++'1z" component should CC llvmbugs by default, but does not.

The name of this component should also be C++1z, not C++'1z.

**Comment by Endilll** [comment]
We've migrated from bugzilla years ago.
