### ISSUE TITLE
Assertion failed: ESI.Type != EST_Uninstantiated && ESI.Type != EST_Unevaluated

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28839]
|  |  |
| --- | --- |
| Bugzilla Link | [28465](https://llvm.org/bz28465) |
| Version | 3.8 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
$ ~/runnable/bin/clang++ -std=c++11 r.cpp

Assertion failed: ESI.Type != EST_Uninstantiated && ESI.Type != EST_Unevaluated, file: /home/jtony/clang_syn/clang/llvm-dev.src/tools/clang/lib/Sema/TreeTransform.h, line: 4956
CEE5207E The signal SIGABRT was received.
clang-3.8: error: unable to execute command: Signal 3
clang-3.8: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.8.0 (tags/RELEASE_380/final)
Target: s390-ibm-zos
Thread model: posix
InstalledDir: /home/jtony/runnable/bin
clang-3.8: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3.8: error: unable to execute command: Signal 9
clang-3.8: note: diagnostic msg: Error generating preprocessed source(s).
CEE3561S External function get_new_handler__3stdFv was not found in DLL CELHDCPP.
         From compile unit /home/jtony/clang_syn/clang/llvm-dev.src/tools/clang/lib/Basic/Diagnostic.cpp at entry point
         clang::DiagnosticsEngine::~DiagnosticsEngine() at statement 757 at compile unit offset +000000BC at entry
         
 $ cat r.cpp
struct FOO {
  int foo()
  {
        struct FOO : ::FOO {
                using ::FOO::FOO;
                operator int() {return i;}
        };
        FOO a(1);
        return a;
  }
  ~FOO();
  template <typename T> FOO(T = 0);
  operator int() {return i;}
  int i;
} a(2);

int main()
{
  return a.foo();
}
         
         offset +000000BC at address 2D018364.

This problem can also be reproduced on linux, here is the printf log I got in clang 3.8 on linux ( I added the printf info in my local clang 3.8 build):

clang  t.cpp -std=c++11 -c
(ESI.Type != EST_Unevaluated)=0 
(ESI.Type != EST_Uninstantiated)=1

**Comment by Endilll** [comment]
Appears to be fixed in Clang 3.9: https://cexplorer.testlabs.pro/z/nPo9r3
