### ISSUE TITLE
clang accepts illegal C++ code that uses expression as function

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#28842]
|  |  |
| --- | --- |
| Bugzilla Link | [28468](https://llvm.org/bz28468) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@hfinkel,@zygoloid |

## Extended Description 
The current clang trunk (and all versions at least as early as 3.2) accepts the following C++ code, which is illegal and rejected by the current GCC trunk. 

Interestingly, the code is also accepted by GCC 6.1 and before, and MSVC. 

$ clang++ -v
clang version 3.9.0 (trunk 274742)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.1.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clang++ -c small.cpp
$ 
$ g++-trunk -c small.cpp
small.cpp: In member function ‘void A< <template-parameter-1-1> >::foo()’:
small.cpp:7:9: error: expression cannot be used as a function
     i (0);
         ^
$ 
$ g++-6.1 -c small.cpp
$ 

-----------------------------------

template < class > struct A
{
  int i;

  void foo () 
  { 
    i (0);
  }
};

A < int > a;

**Comment by fhahn** [comment]
Clang now produces the following error message: https://godbolt.org/z/oaYcPPn43

```
<source>:7:3: error: called object type 'int' is not a function or function pointer
```
