### ISSUE TITLE
Assertion failed: QualifierLoc && "should be created for dependent qualifiers"

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28876]
|  |  |
| --- | --- |
| Bugzilla Link | [28502](https://llvm.org/bz28502) |
| Version | 3.8 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Steps to reproduce on linux:
-bash-4.2$ cat r.cpp
        typename U::template U<U>
bar ( typename U :: template U < U > u = typename U :: template U < operator U > ( U ( ) ) )
        {
                return u;
        }
};

-bash-4.2$ myclang++ r.cpp  -std=c++11
clang: /home/jtony/build/3_8/llvm-dev.src/tools/clang/lib/AST/ExprCXX.cpp:453: static clang::DependentScopeDeclRefExpr* clang::DependentScop
eDeclRefExpr::Create(const clang::ASTContext&, clang::NestedNameSpecifierLoc, clang::SourceLocation, const clang::DeclarationNameInfo&, cons
t clang::TemplateArgumentListInfo*): Assertion `QualifierLoc && "should be created for dependent qualifiers"' failed.
0  clang     0x000000001568c4e4 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 68
1  clang     0x000000001568c8d4

...
clang version 3.8.0 (tags/RELEASE_380/final)
Target: powerpc64le-unknown-linux-gnu
Thread model: posix

-bash-4.2$ type myclang
myclang is aliased to `/home/jtony/build/runnable/bin/clang'

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.7, 3.8, and 3.9 with assertions enabled: https://cexplorer.testlabs.pro/z/WbcvoY
