### ISSUE TITLE
Passing 0 to __atomic_fetch_add generates mfence instead of lock xadd

### ISSUE THREAD

**Issue by goussepi** [llvm/llvm-project#28872]
|  |  |
| --- | --- |
| Bugzilla Link | [28498](https://llvm.org/bz28498) |
| Version | trunk |
| OS | All |
| CC | @efriedma-quic,@pogo59 |

## Extended Description 
Using clang 3.9 on trunk at r273567
Target: x86_64-unknown-linux-gnu

When passing a '0' constant to '__atomic_fetch_add', an mfence instruction is generated instead of the usual 'lock xadd' which seems less efficient.

---
#include <stdint.h>

int64_t * g_ptr;

int foo() {
  return __atomic_fetch_add(g_ptr, 0, __ATOMIC_RELAXED);
}
---

clang -O3 -S test.c

Generates:

movq    %rdi, -8(%rsp)
movq    g_ptr(%rip), %rax
mfence
movq    (%rax), %rax
retq

Using gcc:

movq    g_ptr(%rip), %rdx
movq    %rdi, -8(%rsp)
xorl    %eax, %eax
lock xaddq      %rax, (%rdx)
ret

**Comment by efriedma-quic** [comment]
The original testcase gets optimized to a simple load now.
