### ISSUE TITLE
Inconsistent lambda capture list formatting with trailing return type deduction

### ISSUE THREAD

**Issue by vittorioromeo** [llvm/llvm-project#28964]
|  |  |
| --- | --- |
| Bugzilla Link | [28590](https://llvm.org/bz28590) |
| Version | 3.8 |
| OS | Linux |
| Attachments | [Code example](https://user-images.githubusercontent.com/92601346/143753943-1221c793-cf63-4f57-9830-0696232ad9e6.gz) |

## Extended Description 

Consider the following code, formatted by `clang-format`:

```
int main()
{
    int x, y;

    auto l0 = [x, y](auto z)
    { /* ... */ };

    auto l1 = [x, y](auto z) -> int
    { /* ... */ };

    auto l2 = [ x, y ](auto z) -> auto {/* ... */};
}

```

* Lambdas with no trailing return type are formatted as expected.

* Lambdas with a non-`auto` trailing return type are formatted as expected.

* (!) Lambdas with an `auto` trailing return type are inconsistently formatted. A space is added in the capture list and line breaks are not respected. 

Removing the `-> auto` or changing `auto` to `int` allows the lambda to be formatted as expected.

Might be related to bug #&#8203;20450:
https://llvm.org/bugs/show_bug.cgi?id=20450

**Comment by rymiel** [comment]
This was fixed by 17fb879764dcaf1f5f6bc505c5c747067ba7c3cd
