### ISSUE TITLE
Inconsistent formatting of functions with anonymous parameters

### ISSUE THREAD

**Issue by labath** [llvm/llvm-project#28988]
|  |  |
| --- | --- |
| Bugzilla Link | [28614](https://llvm.org/bz28614) |
| Version | unspecified |
| OS | All |

## Extended Description 
I think the example says it all.

```
$ clang-format -style='{BreakBeforeBraces: Allman, AlwaysBreakAfterReturnType: All}' <<EOF
 class C
 {
     void f() {}
     void f(int) {}
     void f(a::b) {}
     void f(a::b c) {}
 };
 EOF
```
```
class C
{
  void
  f()
  {
  }
  void
  f(int)
  {
  }
  void f(a::b) {}
  void
  f(a::b c)
  {
  }
};

```

Note that the function void f(a::b) is not formatted like the others. Also note that this does not happen when the function is not in a class.

**Comment by mydeveloperday** [comment]
This is the output from clang-format v8

```
$ clang-format-8.0.exe -style='{BreakBeforeBraces: Allman, AlwaysBreakAfterReturnType: All}' <<EOF
 class C
 {
     void f() {}
     void f(int) {}
     void f(a::b) {}
     void f(a::b c) {}
 };
```

This is the output from clang-format 12 and 13

```
class C
{
  void
  f()
  {
  }
  void
  f(int)
  {
  }
  void
  f(a::b)
  {
  }
  void
  f(a::b c)
  {
  }
};
```

I'm going to mark this issue as fixed, please reopen if its still a problem for you
