### ISSUE TITLE
git-clang-format doesn't detect changes when space in file path (patch included)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29028]
|  |  |
| --- | --- |
| Bugzilla Link | [28654](https://llvm.org/bz28654) |
| Version | trunk |
| OS | All |
| Attachments | [Patch fix from my fork at https://user-images.githubusercontent.com/60944935/143753973-05f2d682-ec23-4600-8c28-8a0e1b05e1f0.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

git-clang-format was failing to format some of my modified files.

Inspecting the git-clang-format script, I was able to trace it to "modified_files" including a trailing tab in the file name. e.g. "My Directory/Foo.m\t", which was ignored on account of ".m\t" being an unknown extension.

This *may* be because my directory structure includes a space. I *did* test that the files were properly formatted when renaming "My Directory" to "MyDirectory" but not when renaming it to "My Other Directory"

**Comment by mkurdej** [comment]
Revision URI: https://reviews.llvm.org/D126365

**Comment by owenca** [comment]
Fixed in c31bc7bdf810.
