### ISSUE TITLE
Fix and consolidate the test allocators.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29061]
|  |  |
| --- | --- |
| Bugzilla Link | [28687](https://llvm.org/bz28687) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
There are a bunch of problems in our test suite relating to our test allocator classes. First they have separate duplicate definitions in a bunch of different test files. We should pull them all out into a single support header.

This will help solve the second problem, which is many of these allocator don't conform to the standard requirements and therefore it makes the tests non portable.

Doing this will be a lot of work. This bug tracks the status of that work.

**Comment by philnik777** [comment]
We've got `test_allocators.h` now. I think this has mostly been done, so I'm closing this.
