### ISSUE TITLE
Bootstrapped Clang on Windows fails with "Argument index out of range!" assert

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#29079]
|  |  |
| --- | --- |
| Bugzilla Link | [28705](https://llvm.org/bz28705) |
| Version | trunk |
| OS | Linux |
| CC | @DimitryAndric,@emaste,@rnk |

## Extended Description 
For example:
http://lab.llvm.org:8011/builders/clang-x86-win2008-selfhost/builds/9244/steps/ninja%20check%202/logs/FAIL%3A%20Clang%3A%3Aswitch.c

Currently bisecting.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 4: https://godbolt.org/z/hKoEc77vd
