### ISSUE TITLE
clang crashes on valid C++ code (with self initialization of pointer reference): in clang::DeclContext::getRedeclContext

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#29074]
|  |  |
| --- | --- |
| Bugzilla Link | [28700](https://llvm.org/bz28700) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@hfinkel |

## Extended Description 
The current clang trunk crashes when compiling the following C++ test case on x86_64-linux-gnu in both 32-bit and 64-bit modes. 

The test hangs all versions till 3.8.x since at least as early as 2.9, except 3.2, which crashes on the test. 

$ clang++ -v
clang version 4.0.0 (trunk 276574)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.1.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$
$ g++-6.1 -c small.cpp
$
$ clang++ -c small.cpp
#&#8203;0 0x0000000001d6c945 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/clang-trunk/bin/clang-4.0+0x1d6c945)
#&#8203;1 0x0000000001d6a9fe llvm::sys::RunSignalHandlers() (/usr/local/clang-trunk/bin/clang-4.0+0x1d6a9fe)
#&#8203;2 0x0000000001d6ab60 SignalHandler(int) (/usr/local/clang-trunk/bin/clang-4.0+0x1d6ab60)
#&#8203;3 0x00007f3c059c9340 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10340)
#&#8203;4 0x0000000001f0f386 clang::VarDecl::hasLocalStorage() const (/usr/local/clang-trunk/bin/clang-4.0+0x1f0f386)
#&#8203;5 0x0000000002aa0062 EvalAddr(clang::Expr const*, llvm::SmallVectorImpl<clang::DeclRefExpr const*>&, clang::Decl const*) (/usr/local/clang-trunk/bin/clang-4.0+0x2aa0062)

... 

#&#8203;255 0x0000000002a9ff85 EvalAddr(clang::Expr const*, llvm::SmallVectorImpl<clang::DeclRefExpr const*>&, clang::Decl const*) (/usr/local/clang-trunk/bin/clang-4.0+0x2a9ff85)
Stack dump:
0.      Program arguments: /usr/local/clang-trunk/bin/clang-4.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name small.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -coverage-file /data2/small.cpp -resource-dir /usr/local/clang-trunk/bin/../lib/clang/4.0.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward -internal-isystem /usr/local/include -internal-isystem /usr/local/clang-trunk/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /data2 -ferror-limit 19 -fmessage-length 192 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o small.o -x c++ small.cpp
1.      small.cpp:4:11: current parser token ';'
2.      small.cpp:2:1: parsing function body 'foo'
3.      small.cpp:2:1: in compound statement ('{}')
clang-4.0: error: unable to execute command: Segmentation fault (core dumped)
clang-4.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0 (trunk 276574)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
clang-4.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-4.0: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-4.0: note: diagnostic msg: /tmp/small-a4d3b1.cpp
clang-4.0: note: diagnostic msg: /tmp/small-a4d3b1.sh
clang-4.0: note: diagnostic msg:

********************
$

-----------------------

int * foo ()
{ 
  int *&a = a;
  return a;
}

**Comment by fhahn** [comment]
Clang does not crash any longer and produces the following warning  + assembly with -O3: https://llvm.godbolt.org/z/3ozrfzcq7


```
source>:3:11: warning: reference 'a' is not yet bound to a value when used within its own initialization [-Wuninitialized]
int *&a = a;
      ~   ^
1 warning generated.
Compiler returned: 0


foo():                                # @foo()
        ret
```
