### ISSUE TITLE
clang crashes on invalid C++11 code with recursive template instantiation: in clang::FieldDecl::setInClassInitializer

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#29084]
|  |  |
| --- | --- |
| Bugzilla Link | [28710](https://llvm.org/bz28710) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@hfinkel,@zygoloid |

## Extended Description 
The current clang trunk crashes when compiling the following C++11 test case on x86_64-linux-gnu in both 32-bit and 64-bit modes. 

It is a regression from 3.8.x, which properly rejects the code.

$ clang++ -v
clang version 4.0.0 (trunk 276673)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.1.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clang++ -c -std=c++11 small.cpp
small.cpp:1:32: fatal error: recursive template instantiation exceeded maximum depth of 256
template < typename T > struct A
                               ^
small.cpp:1:32: note: in instantiation of default member initializer 'A<int>::t' requested here
small.cpp:1:32: note: in instantiation of default member initializer 'A<int>::t' requested here
small.cpp:1:32: note: in instantiation of default member initializer 'A<int>::t' requested here
small.cpp:1:32: note: in instantiation of default member initializer 'A<int>::t' requested here
small.cpp:1:32: note: in instantiation of default member initializer 'A<int>::t' requested here
small.cpp:1:32: note: (skipping 247 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
small.cpp:1:32: note: in instantiation of default member initializer 'A<int>::t' requested here
small.cpp:1:32: note: in instantiation of default member initializer 'A<int>::t' requested here
small.cpp:1:32: note: in instantiation of default member initializer 'A<int>::t' requested here
small.cpp:1:32: note: in instantiation of default member initializer 'A<int>::t' requested here
small.cpp:1:32: note: in instantiation of default member initializer 'A<int>::t' requested here
small.cpp:1:32: note: use -ftemplate-depth=N to increase recursive template instantiation depth
small.cpp:3:47: note: implicit default constructor for 'A<int>' first required here
  int t = ([] (A < T > *) { return 0; }) (new A < T >);
                                              ^
small.cpp:3:47: note: implicit default constructor for 'A<int>' first required here
clang-4.0: /tmp/llvm-builder/llvm-source-trunk/tools/clang/include/clang/AST/Decl.h:2427: void clang::FieldDecl::setInClassInitializer(clang::Expr*): Assertion `hasInClassInitializer() && InitStorage.getPointer() == nullptr && "bit width, initializer or captured type already set"' failed.

... 

257.    small.cpp:3:7: instantiating default member init 'A<int>::t'
clang-4.0: error: unable to execute command: Aborted (core dumped)
clang-4.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0 (trunk 276673)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/tools/bin
clang-4.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-4.0: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-4.0: note: diagnostic msg: /tmp/small-42a53c.cpp
clang-4.0: note: diagnostic msg: /tmp/small-42a53c.sh
clang-4.0: note: diagnostic msg:

********************
$ 

--------------------------------------------------------

template < typename T > struct A
{
  int t = ([] (A < T > *) { return 0; }) (new A < T >);
};

A < int > a;

**Comment by fhahn** [comment]
Clang now produces the following error message and does not crash: https://clang.godbolt.org/z/T8GjqP3q6

```
<source>:1:32: error: default member initializer for 't' uses itself
template < typename T > struct A
                               ^
<source>:1:32: note: in instantiation of default member initializer 'A<int>::t' requested here
<source>:3:45: note: in evaluation of exception specification for 'A<int>::A' needed here
int t = ([] (A < T > *) { return 0; }) (new A < T >);
                                            ^
<source>:1:32: note: in instantiation of default member initializer 'A<int>::t' requested here
template < typename T > struct A
                               ^
<source>:6:11: note: in evaluation of exception specification for 'A<int>::A' needed here
A < int > a;
          ^
1 error generated.
```
