### ISSUE TITLE
inconsistent behavior in compiling vector extension code with vector assignment

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#29081]
|  |  |
| --- | --- |
| Bugzilla Link | [28707](https://llvm.org/bz28707) |
| Version | trunk |
| OS | All |

## Extended Description 
The following two test cases illustrate an inconsistency how clang processes vector extension code.  All versions since at least as early as 2.9 are impacted. 

$ clang -v
clang version 4.0.0 (trunk 276574)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.1.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clang test1.c 
test1.c:5:8: error: assigning to '__attribute__((__vector_size__(2 * sizeof(double)))) double' (vector of 2 'double' values) from incompatible type
      '__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values)
  avec = bvec; 
       ^ ~~~~
1 error generated.
$ 
$ clang test2.c
$ 
$ cat test1.c
```c
int main ()
{
  __attribute__ ((vector_size ((2) * sizeof (double)))) double avec; 
  __attribute__ ((vector_size ((2) * sizeof (int)))) int bvec = { 1, 2 }; 
  avec = bvec; 
  return 0;
}
```
$ 
$ cat test2.c
```c
int main ()
{
  __attribute__ ((vector_size ((2) * sizeof (float)))) float avec; 
  __attribute__ ((vector_size ((2) * sizeof (int)))) int bvec = { 1, 2 }; 
  avec = bvec; 
  return 0;
}
```
$

**Comment by fhahn** [comment]
I believe this works as expected. ` __attribute__ ((vector_size ((2) * sizeof (float))))` is compatible to `__attribute__ ((vector_size ((2) * sizeof (int))))` because if `sizeof(int) == sizeof(float)`. That doesn't hold if `float` is replaced with `double`

please re-open with additional info if I missed anything.
