### ISSUE TITLE
SystemZ backend: failing assert in ScheduleDAGRRList

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29125]
|  |  |
| --- | --- |
| Bugzilla Link | [28753](https://llvm.org/bz28753) |
| Version | trunk |
| OS | Linux |
| Attachments | [C source](https://user-images.githubusercontent.com/60944935/143754032-3a54dfe5-7bc7-49be-8dd7-6568d5c20c56.gz), [.ll output for bug.c](https://user-images.githubusercontent.com/60944935/143754033-b4fc4bcc-d564-422b-babc-cd7eefb62a71.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

To reproduce, compile bug.c with
clang -O1 -target s390x-linux-gnu -c bug.c

Compilation aborts during "DAG->DAG Pattern Instruction Selection" with this failed assert:

llvm/lib/CodeGen/SelectionDAG/ScheduleDAGRRList.cpp:1197: llvm::MVT getPhysicalRegisterVT(llvm::SDNode*, unsigned int, const llvm::TargetInstrInfo*): Assertion `MCID.ImplicitDefs && "Physical reg def must be in implicit def list!"' failed.

Compiling at -O0 does not reproduce the failure. Changing "shift" in bug.c to a value lower than 64 also causes compilation to pass.

LLVM/Clang is from SVN trunk 276984.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 6: https://godbolt.org/z/sM6fWdYdd
