### ISSUE TITLE
Assertion `(!ModifiedMF || EmitDone) && "Dbg values are not emitted in LDV"' with fast-isel and greedy regalloc

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#29143]
|  |  |
| --- | --- |
| Bugzilla Link | [28773](https://llvm.org/bz28773) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [Testcase](https://user-images.githubusercontent.com/56606707/143754042-2b007bd8-b021-458f-94f5-f17c0795ccfd.gz) |

## Extended Description 

"llc -O0 -regalloc=greedy a.ll" crashes with the attached .ll file.  On x86-64 Linux if it matters.

I hand-edited the attached IR to insert an extra call to llvm.dbg.value, so it's possible the debug info is invalid somehow, but I think it's okay.

**Comment by xgupta** [comment]
Attached IR testcase becomes invalid now - https://godbolt.org/z/b7zofG5sW.
