### ISSUE TITLE
Missing -Wpragma diagnostic

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29154]
|  |  |
| --- | --- |
| Bugzilla Link | [28784](https://llvm.org/bz28784) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
While building with GCC 6.1:

[156/201] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/AlignOfTest.cpp.o
../unittests/Support/AlignOfTest.cpp:38:32: warning: ‘-w’ is not an option that controls warnings [-Wpragmas]
 #pragma GCC diagnostic warning "-w"
                                ^~~~

clang doesn't seem to warn on the same case.

**Comment by AaronBallman** [comment]
Clang does diagnose the issue and supports `-Wpragmas`, so closing as complete.
