### ISSUE TITLE
crash on invalid C++ code on x86_64-linux-gnu (Assertion `!isNull() && "Cannot retrieve a NULL type pointer"' failed.)

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#29234]
|  |  |
| --- | --- |
| Bugzilla Link | [28864](https://llvm.org/bz28864) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
$ clang++-trunk -v
clang version 4.0.0 (trunk 277732)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.1.1
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$
$ clang++-trunk small.C
small.C:6:8: error: cannot initialize a variable of type 'S *' with an lvalue of type 'void () __attribute__((noreturn)) throw()'
    S *s = abort S[n];
       ^   ~~~~~
small.C:6:17: error: expected ';' at end of declaration
    S *s = abort S[n];
                ^
                ;
small.C:6:19: warning: decomposition declarations are a C++1z extension [-Wc++1z-extensions]
    S *s = abort S[n];
                  ^~~
small.C:6:19: error: decomposition declaration cannot be declared with type 'S'; declared type must be 'auto' or reference to 'auto'
clang-4.0: /tmp/llvm-builder/llvm-source-trunk/tools/clang/include/clang/AST/Type.h:612: const clang::ExtQualsTypeCommonBase* clang::QualType::getCommonPtr() const: Assertion `!isNull() && "Cannot retrieve a NULL type pointer"' failed.
#&#8203;0 0x0000000001b7d425 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/clang-trunk/bin/clang-4.0+0x1b7d425)
#&#8203;1 0x0000000001b7b14e llvm::sys::RunSignalHandlers() (/usr/local/clang-trunk/bin/clang-4.0+0x1b7b14e)
#&#8203;2 0x0000000001b7b2b2 SignalHandler(int) (/usr/local/clang-trunk/bin/clang-4.0+0x1b7b2b2)
#&#8203;3 0x00007f81b414ded0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10ed0)
#&#8203;4 0x00007f81b2ce21c8 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x331c8)
#&#8203;5 0x00007f81b2ce364a abort (/lib/x86_64-linux-gnu/libc.so.6+0x3464a)
#&#8203;6 0x00007f81b2cdb107 (/lib/x86_64-linux-gnu/libc.so.6+0x2c107)
#&#8203;7 0x00007f81b2cdb1b2 (/lib/x86_64-linux-gnu/libc.so.6+0x2c1b2)
#&#8203;8 0x0000000001d26c25 (/usr/local/clang-trunk/bin/clang-4.0+0x1d26c25)
#&#8203;9 0x000000000296fdec clang::Sema::BuildDeclarationNameExpr(clang::CXXScopeSpec const&, clang::DeclarationNameInfo const&, clang::NamedDecl*, clang::NamedDecl*, clang::TemplateArgumentListInfo const*, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x296fdec)
#&#8203;10 0x000000000297031e clang::Sema::BuildDeclarationNameExpr(clang::CXXScopeSpec const&, clang::LookupResult&, bool, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x297031e)
#&#8203;11 0x00000000028a5d63 clang::Sema::ClassifyName(clang::Scope*, clang::CXXScopeSpec&, clang::IdentifierInfo*&, clang::SourceLocation, clang::Token const&, bool, std::unique_ptr<clang::CorrectionCandidateCallback, std::default_delete<clang::CorrectionCandidateCallback> >) (/usr/local/clang-trunk/bin/clang-4.0+0x28a5d63)
#&#8203;12 0x00000000025f3abe clang::Parser::TryAnnotateName(bool, std::unique_ptr<clang::CorrectionCandidateCallback, std::default_delete<clang::CorrectionCandidateCallback> >) (/usr/local/clang-trunk/bin/clang-4.0+0x25f3abe)
#&#8203;13 0x000000000266e3cb clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedContsructsKind, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/usr/local/clang-trunk/bin/clang-4.0+0x266e3cb)
#&#8203;14 0x000000000266e65e clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedContsructsKind, clang::SourceLocation*) (/usr/local/clang-trunk/bin/clang-4.0+0x266e65e)
#&#8203;15 0x0000000002671ac7 clang::Parser::ParseCompoundStatementBody(bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2671ac7)
#&#8203;16 0x0000000002671e95 clang::Parser::ParseCompoundStatement(bool, unsigned int) (/usr/local/clang-trunk/bin/clang-4.0+0x2671e95)
#&#8203;17 0x0000000002671ee2 clang::Parser::ParseCompoundStatement(bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2671ee2)
#&#8203;18 0x000000000266e24a clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedContsructsKind, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/usr/local/clang-trunk/bin/clang-4.0+0x266e24a)
#&#8203;19 0x000000000266e65e clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedContsructsKind, clang::SourceLocation*) (/usr/local/clang-trunk/bin/clang-4.0+0x266e65e)
#&#8203;20 0x0000000002671ac7 clang::Parser::ParseCompoundStatementBody(bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2671ac7)
#&#8203;21 0x0000000002673e09 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/usr/local/clang-trunk/bin/clang-4.0+0x2673e09)
#&#8203;22 0x00000000025f90a8 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/usr/local/clang-trunk/bin/clang-4.0+0x25f90a8)
#&#8203;23 0x0000000002616926 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, unsigned int, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/usr/local/clang-trunk/bin/clang-4.0+0x2616926)
#&#8203;24 0x00000000025f5162 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/usr/local/clang-trunk/bin/clang-4.0+0x25f5162)
#&#8203;25 0x00000000025f5821 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) [clone .part.158] [clone .constprop.181] (/usr/local/clang-trunk/bin/clang-4.0+0x25f5821)
#&#8203;26 0x00000000025f586f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/usr/local/clang-trunk/bin/clang-4.0+0x25f586f)
#&#8203;27 0x00000000025fac0f clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/usr/local/clang-trunk/bin/clang-4.0+0x25fac0f)
#&#8203;28 0x00000000025fb549 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/usr/local/clang-trunk/bin/clang-4.0+0x25fb549)
#&#8203;29 0x00000000025f0d0b clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x25f0d0b)
#&#8203;30 0x00000000022d9667 clang::CodeGenAction::ExecuteAction() (/usr/local/clang-trunk/bin/clang-4.0+0x22d9667)
#&#8203;31 0x0000000001fff7a6 clang::FrontendAction::Execute() (/usr/local/clang-trunk/bin/clang-4.0+0x1fff7a6)
#&#8203;32 0x0000000001fd3836 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/clang-trunk/bin/clang-4.0+0x1fd3836)
#&#8203;33 0x0000000002083f47 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/clang-trunk/bin/clang-4.0+0x2083f47)
#&#8203;34 0x0000000000941778 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/clang-trunk/bin/clang-4.0+0x941778)
#&#8203;35 0x00000000008deb60 main (/usr/local/clang-trunk/bin/clang-4.0+0x8deb60)
#&#8203;36 0x00007f81b2ccf730 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20730)
#&#8203;37 0x000000000093dff9 _start (/usr/local/clang-trunk/bin/clang-4.0+0x93dff9)
Stack dump:
0.	Program arguments: /usr/local/clang-trunk/bin/clang-4.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name small.C -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -resource-dir /usr/local/clang-trunk/bin/../lib/clang/4.0.0 -c-isystem . -c-isystem /usr/local/include/csmith -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/x86_64-linux-gnu/c++/6.1.1 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/x86_64-linux-gnu/c++/6.1.1 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/backward -internal-isystem /usr/local/include -internal-isystem /usr/local/clang-trunk/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/cnsun/workspace/meta-compiler/error-fuzzer/exp-runs/crash/20160729-clang++-trunk--O3-c-Weverything-std=c++14-build-141725 -ferror-limit 19 -fmessage-length 135 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/small-a0e0e1.o -x c++ small.C
1.	small.C:7:5: current parser token 'n'
2.	small.C:3:26: parsing function body '__attribute__doit'
3.	small.C:3:26: in compound statement ('{}')
4.	small.C:5:3: in compound statement ('{}')
clang-4.0: error: unable to execute command: Aborted
clang-4.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0 (trunk 277732)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-4.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-4.0: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-4.0: note: diagnostic msg: /tmp/small-980b40.cpp
clang-4.0: note: diagnostic msg: /tmp/small-980b40.sh
clang-4.0: note: diagnostic msg:

********************
$
$ cat small.c
cat: small.c: No such file or directory
$ cat small.C
void abort() throw() __attribute__((__noreturn__));
struct S {};
void __attribute__doit() {
  int n;
  {
    S *s = abort S[n];
    n;
  }
}
$

**Comment by oToToT** [comment]
Closing as it seems already been fixed.
