### ISSUE TITLE
crash on invalid C++ code on x86_64-linux-gnu (Assertion `NewArgs.empty() && "no parens or braces but have direct init with arguments?"' failed.)

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#29239]
|  |  |
| --- | --- |
| Bugzilla Link | [28869](https://llvm.org/bz28869) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
$ clang++-trunk -v
clang version 4.0.0 (trunk 277732)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.1.1
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ clang++-trunk small.C
small.C:8:16: error: expected ')'
        A a ( 1;
               ^
small.C:8:13: note: to match this '('
        A a ( 1;
            ^
clang-4.0: /tmp/llvm-builder/llvm-source-trunk/tools/clang/lib/Sema/TreeTransform.h:3279: clang::ExprResult clang::TreeTransform<Derived>::TransformInitializer(clang::Expr*, bool) [with Derived = {anonymous}::TemplateInstantiator; clang::ExprResult = clang::ActionResult<clang::Expr*>]: Assertion `NewArgs.empty() && "no parens or braces but have direct init with arguments?"' failed.
#&#8203;0 0x0000000001b7d425 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/clang-trunk/bin/clang-4.0+0x1b7d425)
#&#8203;1 0x0000000001b7b14e llvm::sys::RunSignalHandlers() (/usr/local/clang-trunk/bin/clang-4.0+0x1b7b14e)
#&#8203;2 0x0000000001b7b2b2 SignalHandler(int) (/usr/local/clang-trunk/bin/clang-4.0+0x1b7b2b2)
#&#8203;3 0x00007fd4a48a7ed0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10ed0)
#&#8203;4 0x00007fd4a343c1c8 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x331c8)
#&#8203;5 0x00007fd4a343d64a abort (/lib/x86_64-linux-gnu/libc.so.6+0x3464a)
#&#8203;6 0x00007fd4a3435107 (/lib/x86_64-linux-gnu/libc.so.6+0x2c107)
#&#8203;7 0x00007fd4a34351b2 (/lib/x86_64-linux-gnu/libc.so.6+0x2c1b2)
#&#8203;8 0x0000000002b9748d clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformInitializer(clang::Expr*, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2b9748d)
#&#8203;9 0x0000000002b97654 clang::Sema::SubstInitializer(clang::Expr*, clang::MultiLevelTemplateArgumentList const&, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2b97654)
#&#8203;10 0x0000000002bbebbd clang::Sema::InstantiateVariableInitializer(clang::VarDecl*, clang::VarDecl*, clang::MultiLevelTemplateArgumentList const&) (/usr/local/clang-trunk/bin/clang-4.0+0x2bbebbd)
#&#8203;11 0x0000000002bc9a43 clang::Sema::BuildVariableInstantiation(clang::VarDecl*, clang::VarDecl*, clang::MultiLevelTemplateArgumentList const&, llvm::SmallVector<clang::Sema::LateInstantiatedAttribute, 16u>*, clang::DeclContext*, clang::LocalInstantiationScope*, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2bc9a43)
#&#8203;12 0x0000000002bc9e97 clang::TemplateDeclInstantiator::VisitVarDecl(clang::VarDecl*, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2bc9e97)
#&#8203;13 0x0000000002bcca42 clang::Sema::SubstDecl(clang::Decl*, clang::DeclContext*, clang::MultiLevelTemplateArgumentList const&) (/usr/local/clang-trunk/bin/clang-4.0+0x2bcca42)
#&#8203;14 0x0000000002b925a8 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDeclStmt(clang::DeclStmt*) (/usr/local/clang-trunk/bin/clang-4.0+0x2b925a8)
#&#8203;15 0x0000000002bb6a13 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformStmt(clang::Stmt*) (/usr/local/clang-trunk/bin/clang-4.0+0x2bb6a13)
#&#8203;16 0x0000000002bb843c clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2bb843c)
#&#8203;17 0x0000000002bb857b clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*) (/usr/local/clang-trunk/bin/clang-4.0+0x2bb857b)
#&#8203;18 0x0000000002bb69f3 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformStmt(clang::Stmt*) (/usr/local/clang-trunk/bin/clang-4.0+0x2bb69f3)
#&#8203;19 0x0000000002bbaf18 clang::Sema::SubstStmt(clang::Stmt*, clang::MultiLevelTemplateArgumentList const&) (/usr/local/clang-trunk/bin/clang-4.0+0x2bbaf18)
#&#8203;20 0x0000000002bcedd7 clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2bcedd7)
#&#8203;21 0x0000000002bcdadb clang::Sema::PerformPendingInstantiations(bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2bcdadb)
#&#8203;22 0x00000000027dca62 clang::Sema::ActOnEndOfTranslationUnit() (/usr/local/clang-trunk/bin/clang-4.0+0x27dca62)
#&#8203;23 0x00000000025fb605 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/usr/local/clang-trunk/bin/clang-4.0+0x25fb605)
#&#8203;24 0x00000000025f0d0b clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x25f0d0b)
#&#8203;25 0x00000000022d9667 clang::CodeGenAction::ExecuteAction() (/usr/local/clang-trunk/bin/clang-4.0+0x22d9667)
#&#8203;26 0x0000000001fff7a6 clang::FrontendAction::Execute() (/usr/local/clang-trunk/bin/clang-4.0+0x1fff7a6)
#&#8203;27 0x0000000001fd3836 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/clang-trunk/bin/clang-4.0+0x1fd3836)
#&#8203;28 0x0000000002083f47 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/clang-trunk/bin/clang-4.0+0x2083f47)
#&#8203;29 0x0000000000941778 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/clang-trunk/bin/clang-4.0+0x941778)
#&#8203;30 0x00000000008deb60 main (/usr/local/clang-trunk/bin/clang-4.0+0x8deb60)
#&#8203;31 0x00007fd4a3429730 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20730)
#&#8203;32 0x000000000093dff9 _start (/usr/local/clang-trunk/bin/clang-4.0+0x93dff9)
Stack dump:
0.	Program arguments: /usr/local/clang-trunk/bin/clang-4.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name small.C -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -resource-dir /usr/local/clang-trunk/bin/../lib/clang/4.0.0 -c-isystem . -c-isystem /usr/local/include/csmith -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/x86_64-linux-gnu/c++/6.1.1 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/x86_64-linux-gnu/c++/6.1.1 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/backward -internal-isystem /usr/local/include -internal-isystem /usr/local/clang-trunk/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/cnsun/workspace/meta-compiler/error-fuzzer/exp-runs/crash/RandomTokenManipulationFuzzingEngine/20160805-clang++-trunk--O3-c-Weverything-std=c++14-build-051023 -ferror-limit 19 -fmessage-length 135 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/small-a4a1cd.o -x c++ small.C
1.	<eof> parser at end of file
2.	small.C:7:3: instantiating function definition 'B<607>::B'
clang-4.0: error: unable to execute command: Aborted
clang-4.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0 (trunk 277732)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-4.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-4.0: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-4.0: note: diagnostic msg: /tmp/small-d34e5a.cpp
clang-4.0: note: diagnostic msg: /tmp/small-d34e5a.sh
clang-4.0: note: diagnostic msg:

********************
$ cat small.C
class A {
public:
    A ( int);
};
template <int> class B {
public:
  B() {
        A a ( 1;
  }
};
class C {
public:
    C ( B < 607 >, int);
};
class D {
  D() : c(b, int(1)) {}
  B<607> b;
  C c;
};
$

**Comment by inclyc** [comment]
Fixed in trunk. https://godbolt.org/z/PdjfKs9GM
