### ISSUE TITLE
crash on invalid code n x86_64-linux-gnu (UNREACHABLE executed at /path/to/Expr.cpp:2832!)

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#29236]
|  |  |
| --- | --- |
| Bugzilla Link | [28866](https://llvm.org/bz28866) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
$ clang-trunk -v
clang version 4.0.0 (trunk 277732)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.1.1
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ clang-trunk small.C
small.C:4:28: error: use of undeclared identifier 'value'; did you mean 'false'?
  A(G) : _g(static_cast<G>(value)) {}
                           ^~~~~
                           false
small.C:4:28: error: address of overloaded function 'value' does not match required type 'LC<int, 1, 0, 2, 1>'
  A(G) : _g(static_cast<G>(value)) {}
                           ^~~~~
small.C:8:39: note: in instantiation of member function 'A<LC<int, 1, 0, 2, 1> &>::A' requested here
void fn1() { A<LC<int, 1, 0, 2, 1> &> a(b); }
                                      ^
shouldn't see dependent / unresolved nodes here
UNREACHABLE executed at /tmp/llvm-builder/llvm-source-trunk/tools/clang/lib/AST/Expr.cpp:2832!
#&#8203;0 0x0000000001b7d425 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/clang-trunk/bin/clang-4.0+0x1b7d425)
#&#8203;1 0x0000000001b7b14e llvm::sys::RunSignalHandlers() (/usr/local/clang-trunk/bin/clang-4.0+0x1b7b14e)
#&#8203;2 0x0000000001b7b2b2 SignalHandler(int) (/usr/local/clang-trunk/bin/clang-4.0+0x1b7b2b2)
#&#8203;3 0x00007fe48b12aed0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10ed0)
#&#8203;4 0x00007fe489cbf1c8 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x331c8)
#&#8203;5 0x00007fe489cc064a abort (/lib/x86_64-linux-gnu/libc.so.6+0x3464a)
#&#8203;6 0x0000000001b2c850 LLVMInstallFatalErrorHandler (/usr/local/clang-trunk/bin/clang-4.0+0x1b2c850)
#&#8203;7 0x0000000003026400 clang::Expr::HasSideEffects(clang::ASTContext const&, bool) const (/usr/local/clang-trunk/bin/clang-4.0+0x3026400)
#&#8203;8 0x00000000030261b2 clang::Expr::HasSideEffects(clang::ASTContext const&, bool) const (/usr/local/clang-trunk/bin/clang-4.0+0x30261b2)
#&#8203;9 0x00000000028cccc8 (anonymous namespace)::BaseAndFieldInfo::addFieldInitializer(clang::CXXCtorInitializer*) [clone .constprop.4112] (/usr/local/clang-trunk/bin/clang-4.0+0x28cccc8)
#&#8203;10 0x00000000028e7f0e CollectFieldInitializer(clang::Sema&, (anonymous namespace)::BaseAndFieldInfo&, clang::FieldDecl*, clang::IndirectFieldDecl*) [clone .constprop.4107] (/usr/local/clang-trunk/bin/clang-4.0+0x28e7f0e)
#&#8203;11 0x00000000028f7d9c clang::Sema::SetCtorInitializers(clang::CXXConstructorDecl*, bool, llvm::ArrayRef<clang::CXXCtorInitializer*>) (/usr/local/clang-trunk/bin/clang-4.0+0x28f7d9c)
#&#8203;12 0x00000000028f8de4 clang::Sema::ActOnMemInitializers(clang::Decl*, clang::SourceLocation, llvm::ArrayRef<clang::CXXCtorInitializer*>, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x28f8de4)
#&#8203;13 0x0000000002bca97f clang::Sema::InstantiateMemInitializers(clang::CXXConstructorDecl*, clang::CXXConstructorDecl const*, clang::MultiLevelTemplateArgumentList const&) (/usr/local/clang-trunk/bin/clang-4.0+0x2bca97f)
#&#8203;14 0x0000000002bcedc5 clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2bcedc5)
#&#8203;15 0x0000000002bcdadb clang::Sema::PerformPendingInstantiations(bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2bcdadb)
#&#8203;16 0x00000000027dca62 clang::Sema::ActOnEndOfTranslationUnit() (/usr/local/clang-trunk/bin/clang-4.0+0x27dca62)
#&#8203;17 0x00000000025fb605 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/usr/local/clang-trunk/bin/clang-4.0+0x25fb605)
#&#8203;18 0x00000000025f0d0b clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x25f0d0b)
#&#8203;19 0x00000000022d9667 clang::CodeGenAction::ExecuteAction() (/usr/local/clang-trunk/bin/clang-4.0+0x22d9667)
#&#8203;20 0x0000000001fff7a6 clang::FrontendAction::Execute() (/usr/local/clang-trunk/bin/clang-4.0+0x1fff7a6)
#&#8203;21 0x0000000001fd3836 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/clang-trunk/bin/clang-4.0+0x1fd3836)
#&#8203;22 0x0000000002083f47 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/clang-trunk/bin/clang-4.0+0x2083f47)
#&#8203;23 0x0000000000941778 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/clang-trunk/bin/clang-4.0+0x941778)
#&#8203;24 0x00000000008deb60 main (/usr/local/clang-trunk/bin/clang-4.0+0x8deb60)
#&#8203;25 0x00007fe489cac730 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20730)
#&#8203;26 0x000000000093dff9 _start (/usr/local/clang-trunk/bin/clang-4.0+0x93dff9)
Stack dump:
0.	Program arguments: /usr/local/clang-trunk/bin/clang-4.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name small.C -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -resource-dir /usr/local/clang-trunk/bin/../lib/clang/4.0.0 -c-isystem . -c-isystem /usr/local/include/csmith -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/x86_64-linux-gnu/c++/6.1.1 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/x86_64-linux-gnu/c++/6.1.1 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/backward -internal-isystem /usr/local/include -internal-isystem /usr/local/clang-trunk/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/cnsun/workspace/meta-compiler/error-fuzzer/exp-runs/crash/20160729-clang++-trunk--O3-c-Weverything-std=c++14-build-210015 -ferror-limit 19 -fmessage-length 135 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/small-ec0a17.o -x c++ small.C
1.	<eof> parser at end of file
2.	small.C:4:3: instantiating function definition 'A<LC<int, 1, 0, 2, 1> &>::A'
clang-4.0: error: unable to execute command: Aborted
clang-4.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0 (trunk 277732)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-4.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-4.0: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-4.0: note: diagnostic msg: /tmp/small-10b7ef.cpp
clang-4.0: note: diagnostic msg: /tmp/small-10b7ef.sh
clang-4.0: note: diagnostic msg:

********************
$ cat small.C
template <class, int, int, int, int> class LC {};
template <class G> class A {
public:
  A(G) : _g(static_cast<G>(value)) {}
  G _g;
};
LC<int, 1, 0, 2, 1> b;
void fn1() { A<LC<int, 1, 0, 2, 1> &> a(b); }
$

**Comment by wheatman** [comment]
This seems to have been fixed between 3.9.0 and 4.0.0
https://cexplorer.testlabs.pro/z/7qE35M

As a note this only occurs with assertions

for reference

code 
```
template <class, int, int, int, int> class LC {};
template <class G> class A {
public:
  A(G) : _g(static_cast<G>(value)) {}
  G _g;
};
LC<int, 1, 0, 2, 1> b;
void fn1() { A<LC<int, 1, 0, 2, 1> &> a(b); }
```

dump

```
<source>:4:28: error: use of undeclared identifier 'value'; did you mean 'false'?
  A(G) : _g(static_cast<G>(value)) {}
                           ^~~~~
                           false
<source>:4:28: error: address of overloaded function 'value' does not match required type 'LC<int, 1, 0, 2, 1>'
  A(G) : _g(static_cast<G>(value)) {}
                           ^~~~~
<source>:8:39: note: in instantiation of member function 'A<LC<int, 1, 0, 2, 1> &>::A' requested here
void fn1() { A<LC<int, 1, 0, 2, 1> &> a(b); }
                                      ^
shouldn't see dependent / unresolved nodes here
UNREACHABLE executed at /home/tonik/llvm-project/llvm/tools/clang/lib/AST/Expr.cpp:2831!
#0 0x0000000001c01e88 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x1c01e88)
#1 0x0000000001bff9ee llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x1bff9ee)
#2 0x0000000001bffb54 SignalHandler(int) (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x1bffb54)
#3 0x00007f7a25e54df0 __restore_rt (/lib64/libc.so.6+0x54df0)
#4 0x00007f7a25ea154c __pthread_kill_implementation (/lib64/libc.so.6+0xa154c)
#5 0x00007f7a25e54d46 __GI_raise (/lib64/libc.so.6+0x54d46)
#6 0x00007f7a25e287f3 __GI_abort (/lib64/libc.so.6+0x287f3)
#7 0x0000000001bac740 LLVMInstallFatalErrorHandler (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x1bac740)
#8 0x00000000031e5908 clang::Expr::HasSideEffects(clang::ASTContext const&, bool) const (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x31e5908)
#9 0x00000000031e556a clang::Expr::HasSideEffects(clang::ASTContext const&, bool) const (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x31e556a)
#10 0x0000000002a26be5 CollectFieldInitializer(clang::Sema&, (anonymous namespace)::BaseAndFieldInfo&, clang::FieldDecl*, clang::IndirectFieldDecl*) (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x2a26be5)
#11 0x0000000002a3c1ac clang::Sema::SetCtorInitializers(clang::CXXConstructorDecl*, bool, llvm::ArrayRef<clang::CXXCtorInitializer*>) (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x2a3c1ac)
#12 0x0000000002a3cdef clang::Sema::ActOnMemInitializers(clang::Decl*, clang::SourceLocation, llvm::ArrayRef<clang::CXXCtorInitializer*>, bool) (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x2a3cdef)
#13 0x0000000002d4ef4c clang::Sema::InstantiateMemInitializers(clang::CXXConstructorDecl*, clang::CXXConstructorDecl const*, clang::MultiLevelTemplateArgumentList const&) (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x2d4ef4c)
#14 0x0000000002d53f85 clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x2d53f85)
#15 0x0000000002d528ab clang::Sema::PerformPendingInstantiations(bool) (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x2d528ab)
#16 0x00000000028f80cf clang::Sema::ActOnEndOfTranslationUnit() (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x28f80cf)
#17 0x00000000026fa605 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x26fa605)
#18 0x00000000026ef8c3 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x26ef8c3)
#19 0x00000000023b5359 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x23b5359)
#20 0x00000000020bc666 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x20bc666)
#21 0x000000000208d276 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x208d276)
#22 0x0000000002146caa clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x2146caa)
#23 0x0000000000957ff8 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x957ff8)
#24 0x00000000008f3c31 main (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x8f3c31)
#25 0x00007f7a25e3feb0 __libc_start_call_main (/lib64/libc.so.6+0x3feb0)
#26 0x00007f7a25e3ff60 __libc_start_main_alias_2 (/lib64/libc.so.6+0x3ff60)
#27 0x0000000000954739 _start (/opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9+0x954739)
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-3.9.0-assert/bin/clang-3.9 -cc1 -triple x86_64-unknown-linux-gnu -S -disable-free -main-file-name example.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -coverage-file /tmp/compiler-explorer-compiler202366-960250-1oh1z8k.k3lm/output.s -resource-dir /opt/compiler-explorer/clang-3.9.0-assert/bin/../lib/clang/3.9.0 -internal-isystem /opt/compiler-explorer/gcc-7.2.0/lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0 -internal-isystem /opt/compiler-explorer/gcc-7.2.0/lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/x86_64-linux-gnu -internal-isystem /opt/compiler-explorer/gcc-7.2.0/lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/backward -internal-isystem /usr/local/include -internal-isystem /opt/compiler-explorer/clang-3.9.0-assert/bin/../lib/clang/3.9.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include --std=c++14 -fdeprecated-macro -fdebug-compilation-dir /tmp/compiler-explorer-compiler202366-960250-1oh1z8k.k3lm -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -mllvm --x86-asm-syntax=intel -o /tmp/compiler-explorer-compiler202366-960250-1oh1z8k.k3lm/output.s -x c++ <source> 
1.	<eof> parser at end of file
2.	<source>:4:3: instantiating function definition 'A<LC<int, 1, 0, 2, 1> &>::A'
clang-3.9: error: unable to execute command: Aborted (core dumped)
clang-3.9: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.9.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/compiler-explorer/clang-3.9.0-assert/bin
clang-3.9: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3.9: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3.9: note: diagnostic msg: /tmp/example-db50d8.cpp
clang-3.9: note: diagnostic msg: /tmp/example-db50d8.sh
clang-3.9: note: diagnostic msg: 

********************
Compiler returned: 254
```
