### ISSUE TITLE
Assertion `CastInst::castIsValid(opc, C, Ty) && "Invalid constantexpr cast!" after r260711

### ISSUE THREAD

**Issue by wolfy1961** [llvm/llvm-project#29249]
|  |  |
| --- | --- |
| Bugzilla Link | [28879](https://llvm.org/bz28879) |
| Version | trunk |
| OS | Linux |
| CC | @zmodem,@preames,@pogo59 |

## Extended Description 
; Running opt -gvn on the following module causes an assertion after 
; r260711. Probably something to do with vector sizes < 1 byte.

; ModuleID = 'bugpoint-reduced-simplified.bc'

; Function Attrs: norecurse noreturn nounwind
define void @&#8203;autogen_SD106151532() #&#8203;0 {
BB:
  %A4 = alloca <7 x i1>, align 2
  store <7 x i1> undef, <7 x i1>* %A4, align 2
  br label %CF829.preheader.split62

CF829.preheader.split62:                          ; preds = %BB
  %0 = getelementptr inbounds <7 x i1>, <7 x i1>* %A4, i64 0, i64 0
  %A4.0.A4.0.L865961 = load i1, i1* %0, align 2
  br i1 %A4.0.A4.0.L865961, label %CF871.us.preheader, label %CF829.preheader

CF829.preheader:                                  ; preds = %CF829.preheader.split62
  unreachable

CF871.us.preheader:                               ; preds = %CF829.preheader.split62
  unreachable
}

attributes #&#8203;0 = { noreturn nounwind }

opt: /home/user/src/llvm/trunk/llvm/lib/IR/Constants.cpp:1533: static llvm::Constant* llvm::ConstantExpr::getCast(unsigned int, llvm::Constant*, llvm::Type*, bool): Assertion `CastInst::castIsValid(opc, C, Ty) && "Invalid constantexpr cast!"' failed.

**Comment by arsenm** [comment]
Works fine now?
