### ISSUE TITLE
llvm lib crashes luxmark when using mesa opencl

### ISSUE THREAD

**Issue by DarkShadow44** [llvm/llvm-project#29261]
|  |  |
| --- | --- |
| Bugzilla Link | [28891](https://llvm.org/bz28891) |
| Version | trunk |
| OS | Linux |
| Attachments | [Console log and backtrace](https://user-images.githubusercontent.com/93436132/143754114-cae32faf-6fa5-4e77-91c4-4f7c11a10276.gz) |
| CC | @DarkShadow44,@arsenm,@tstellar |

## Extended Description 

A lot of programs crash with a segmentation fault in llvm when using opencl, using luxmark as example. Backtrace attached.

Hope this is the right place for this issue, I'll provide more information if needed.

On
 Arch linux 64bit
 with Radeon R9 285 

Using
 Mesa 12.1.0-devel (git-3fb4a9b)
 llvm-libs-svn=277953
 llvm-svn=277953
 opencl-mesa-git 83708.3fb4a9b-1

**Comment by arsenm** [comment]
Pretty sure Luxmark has worked fine for years
