### ISSUE TITLE
Compiler crash when compiling atomic.c in compiler-rt.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29317]
|  |  |
| --- | --- |
| Bugzilla Link | [28947](https://llvm.org/bz28947) |
| Version | 3.8 |
| OS | Windows NT |
| Attachments | [preprocessed atomic.c and run script](https://user-images.githubusercontent.com/60944935/143754141-2bb6fd80-89c5-408a-8451-dad99ee748f3.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

When clang(target: ARM, host: msys2 32bit) compiling atomi.c in compiler-rt, clang abort doe to signal.
Follows are error message.

===========================================================
Compiling ../../lib/compiler-rt/lib/builtins/atomic.c
0x6821C409 (0x0381B9E0 0x7730EA06 0x037AB000 0x00000023), _ZN4llvm12MachineInstr10addOperandERNS_15MachineFunctionERKNS_14MachineOperandE() + 0x9 bytes(s)
arm-eabihf-clang.exe: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.8.0 (tags/RELEASE_381/final)
Target: arm---eabihf
Thread model: posix
InstalledDir: C:\msys32\mingw32\bin
arm-eabihf-clang.exe: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
arm-eabihf-clang.exe: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
arm-eabihf-clang.exe: note: diagnostic msg: C:\msys32\tmp\atomic-adf706.c
arm-eabihf-clang.exe: note: diagnostic msg: C:\msys32\tmp\atomic-adf706.sh
arm-eabihf-clang.exe: note: diagnostic msg:

===========================================================

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.7 through 3.9 with assertions enabled.
