### ISSUE TITLE
Assignment from _Atomic modify gets incorrect error message

### ISSUE THREAD

**Issue by mibintc** [llvm/llvm-project#29321]
|  |  |
| --- | --- |
| Bugzilla Link | [28951](https://llvm.org/bz28951) |
| Version | 3.9 |
| OS | Linux |

## Extended Description 
clang -c -std=c11 tm.c
tm.c:9:9: error: assigning to 'int' from incompatible type '_Atomic(int)'
 result = a -= b;
        ^ ~~~~~~
1 error generated.
-bash-4.2$ cat tm.c

void
test_minus (void)
{
//_Atomic
 int result;
 _Atomic int a = 5;
 int b = 7;
 result = a; // this is ok, type of rhs is int
 result = a -= b; // this gets the error
}

**Comment by AaronBallman** [comment]
This issue appears to have been fixed in Clang 15; closing as completed.
