### ISSUE TITLE
[fast-math] support for math flags 'nsz', 'arcp', 'fast' in opt and TargetOptions

### ISSUE THREAD

**Issue by c1f2da5c-3510-4ef9-b7bb-24e698b33024** [llvm/llvm-project#29349]
|  |  |
| --- | --- |
| Bugzilla Link | [28979](https://llvm.org/bz28979) |
| Version | 3.8 |
| OS | Linux |
| CC | @ecnelises,@hfinkel |

## Extended Description 
It seems that
  opt -enable-no-infs-fp-math  adds  ninf  globally
  opt -enable-no-nans-fp-math  adds  nnan  globally

but I do not see counterparts for the flags 'nsz', 'arcp' and 'fast'.
I also do not see corresponding flags in TargetOptions.
Am I missing something?
Is there another way to apply fast-math flags to whole functions or modules?
Or is it discouraged for some reason, anyway?

**Comment by arsenm** [comment]
It's preferable to move away from the attributes / cl::opts to individual fast flags
