### ISSUE TITLE
Clang crashes with a std::bad_alloc exception

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29376]
|  |  |
| --- | --- |
| Bugzilla Link | [29006](https://llvm.org/bz29006) |
| Version | 3.8 |
| OS | Windows NT |
| Attachments | [Command line and cpp file causing Clang 3.8.243773 to crash](https://user-images.githubusercontent.com/60944935/143754176-e448e664-b001-4146-9bc5-02316e0aad3c.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@yuanfang-chen |

## Extended Description 

When compiling generated C++ binding code for our SkookumScript plugin for Unreal Engine 4 using Android Codeworks 1R4u2 (which ships with Clang 3.8.243773), Clang crashes throwing a std::bad_alloc exception. I am enclosing the generated test case code hoping you can reproduce the crash.

The same source code compiles fine with Clang 3.6, and also with Visual Studio 2015, so I am suspecting this is due to changes introduced between Clang 3.6 and 3.8.243773.

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.7 through 3.9 with assertions enabled.
