### ISSUE TITLE
Wrong `.file` directive generated by `-S`

### ISSUE THREAD

**Issue by hjl-tools** [llvm/llvm-project#29373]
|  |  |
| --- | --- |
| Bugzilla Link | [29003](https://llvm.org/bz29003) |
| Version | trunk |
| OS | Linux |
| CC | @echristo,@nlewycky |

## Extended Description 
On Linux, I got
```console
[hjl@gnu-6 tmp]$ cat x.c
```
```cpp
void
foo ()
{
}
```
```console
[hjl@gnu-6 tmp]$ cat y.c
```
```cpp
#include "x.c"
```
```console
[hjl@gnu-6 tmp]$ clang -S -O2 y.c -g
[hjl@gnu-6 tmp]$ gcc -c y.s
y.s: Assembler messages:
y.s:8: Error: junk at end of line, first unrecognized character is `"'
[hjl@gnu-6 tmp]$ 
```
The bad line is
```asm
	.file	1 "." "x.c"
```
From GNU assembler manual:

When emitting DWARF2 line number information, `.file` assigns filenames
to the `.debug_line` file name table.  The syntax is:
```asm
     .file FILENO FILENAME
```
   The `FILENO` operand should be a unique positive integer to use as the
index of the entry in the table.  The `FILENAME` operand is a C string
literal.

**Comment by dwblaikie** [comment]
Working as intended.
