### ISSUE TITLE
In GetVectorElementPointer - EltSize assertions fail if getSizeInBits is less than 8

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29388]
|  |  |
| --- | --- |
| Bugzilla Link | [29018](https://llvm.org/bz29018) |
| Version | 3.8 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @RKSimon |

## Extended Description 
The code at lib/CodeGen/SelectionDAG/LegalizeTypes.cpp:1031 seems to have issues if the element size is less than a full byte (e.g., processing a "i1"), as EltSize will truncate to 0 and then the assertion will fail.  Allowing the assertion to be ignored if EltSize == 0 seems to fix this issue, but it looks like something that needs more review:

  // Calculate the element offset and add it to the pointer.
  unsigned EltSize = EltVT.getSizeInBits() / 8; // FIXME: should be ABI size.
  if (EltSize)
  {
    assert(EltSize * 8 == EltVT.getSizeInBits() &&
         "Converting bits to bytes lost precision");
  }

**Comment by Endilll** [comment]
I don't see 8-bit bytes being hardcoded in that file as of post-16 trunk.

CC @efriedma-quic @rjmccall

**Comment by efriedma-quic** [comment]
I'm pretty sure the code in question was fixed.

**Comment by vfdff** [comment]
hi @efriedma-quic ,I find there is some crash related above assert, eg: [42304](https://github.com/llvm/llvm-project/issues/42304), [54423](https://github.com/llvm/llvm-project/issues/54423)

**Comment by efriedma-quic** [comment]
This isn't really a useful ticket as-is; please track each issue in a separate ticket, e.g. "SplitVecRes_INSERT_SUBVECTOR is broken for non-byte-size types", or  "SplitVecOp_EXTRACT_VECTOR_ELT is broken for non-byte-size types larger than 8 bits".
