### ISSUE TITLE
Bugpoint enhancement: Remove unnecessary attributes

### ISSUE THREAD

**Issue by MatzeB** [llvm/llvm-project#29397]
|  |  |
| --- | --- |
| Bugzilla Link | [29027](https://llvm.org/bz29027) |
| Version | trunk |
| OS | All |
| CC | @preames,@modocache,@silvasean |

## Extended Description 
It is often possible to remove function attributes to further simplify a testcase.

**Comment by arsenm** [comment]
This is done and llvm-reduce does it too
