### ISSUE TITLE
Bugpoint enhancement: Simplify pointer types

### ISSUE THREAD

**Issue by MatzeB** [llvm/llvm-project#29398]
|  |  |
| --- | --- |
| Bugzilla Link | [29028](https://llvm.org/bz29028) |
| Version | trunk |
| OS | All |
| CC | @donhinton,@preames,@arsenm,@vedantk |

## Extended Description 
It is often possible to simplify pointer types to further simplify the output. Example:

I had a case where instead of this:

%"class.llvm::ilist_node.271.331.53909.117119.330.3340.3942.4544.6350.9962.12644" = type { %"struct.llvm::ilist_node_base.106.53685.116895.106.3116.3718.4320.6126.9738.12643" }
%"struct.llvm::ilist_node_base.106.53685.116895.106.3116.3718.4320.6126.9738.12643" = type { %"class.llvm::PointerIntPair.0.105.53684.116894.105.3115.3717.4319.6125.9737.12642", %"struct.llvm::ilist_node_base.106.53685.116895.106.3116.3718.4320.6126.9738.12643"* }
%"class.llvm::PointerIntPair.0.105.53684.116894.105.3115.3717.4319.6125.9737.12642" = type { i64 }
...
%cmp.i202 = icmp eq %"class.llvm::ilist_node.271.331.53909.117119.330.3340.3942.4544.6350.9962.12644"* undef, undef

This would do and save a bunch of type declarations:

%cmp.i202 = icmp eq i8* undef, undef

**Comment by arsenm** [comment]
Solved by removing pointee types from the IR
