### ISSUE TITLE
GNU statement expression in static initializer is miscompiled to all bytes zero

### ISSUE THREAD

**Issue by mahkoh** [llvm/llvm-project#29394]
|  |  |
| --- | --- |
| Bugzilla Link | [29024](https://llvm.org/bz29024) |
| Version | 3.8 |
| OS | Linux |
| CC | @hfinkel |

## Extended Description 
Consider the following example:

------------
struct x {
	unsigned char i;
};

const struct x *f(void);
const struct x *f(void)
{
	static const struct x *x = __extension__ ({
		static const struct x z = { .i = 255 };
		&z;
	});
	return x;
}

const struct x *g(void);
const struct x *g(void)
{
	static const struct x z = { .i = 255 };
	static const struct x *x = &z;
	return x;
}
-----------

which miscompiles to

-----------
f:
	movl	$f.z, %eax
	retq
g:
	movl	$g.z, %eax
	retq
f.z:
	.zero	1
g.z:
	.byte	255
-----------

GCC rejects statement expressions in constant positions.

**Comment by AaronBallman** [comment]
This issue was fixed in Clang 15.0.0: https://godbolt.org/z/sfqE7WKTY
