### ISSUE TITLE
clang-format AlignConsecutiveDeclarations doesn't align methods with parameters.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29417]
|  |  |
| --- | --- |
| Bugzilla Link | [29047](https://llvm.org/bz29047) |
| Version | 3.9 |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
clang-format will align foo and bar correctly when `AlignConsecutiveDeclarations` is set to true.
```
struct A {
  void foo();
  int  bar();
};
```

Adding a parameter to foo will break alignment.
```
struct A {
  void foo(int x);
  int bar(); // no longer aligned
};
```

**Comment by mkurdej** [comment]
Fixed in clang-format 5.
