### ISSUE TITLE
llvm-4.0 package tries to overwrite llvm-3.9 manpage

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29478]
|  |  |
| --- | --- |
| Bugzilla Link | [29108](https://llvm.org/bz29108) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @sylvestre |

## Extended Description 
On Ubuntu 16.04:

Unpacking llvm-4.0 (1:4.0~svn279502-1~exp1) ...
dpkg: error processing archive /var/cache/apt/archives/llvm-4.0_1%3a4.0~svn279502-1~exp1_amd64.deb (--unpack):
 trying to overwrite '/usr/share/man/man1/llvm-readobj.1.gz', which is also in package llvm-3.9 1:3.9~svn279174-1~exp1

**Comment by sylvestre** [comment]
now fixed
