### ISSUE TITLE
Support ES6 Symbol's 'for' method differently than JavaScript 'for' loops

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29535]
|  |  |
| --- | --- |
| Bugzilla Link | [29165](https://llvm.org/bz29165) |
| Version | 3.9 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Consider the following output of clang-format 3.9 on JavaScript code using ES6/ES2015 Symbol:

const S = Symbol.for ('sym');

Notice the extraneous space between 'for' and '('sym')'. Is clang-format treating this method named 'for' [1] as a for loop?

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for

**Comment by mydeveloperday** [comment]
For clang-format v8 and above I get

```
const S = Symbol.for('sym');
```

Please reopen if this is still an issue
