### ISSUE TITLE
[feature request] identical code in branches

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#29581]
|  |  |
| --- | --- |
| Bugzilla Link | [30233](https://llvm.org/bz30233) |
| Version | unspecified |
| OS | All |
| CC | @EugeneZelenko,@zmodem,@kirillbobyrev |

## Extended Description 
It would be nice if clang-tidy could detect identical code in branches and warn about it:

void bar(); 

void foo() {
  bool condition = true;
  if (condition) 
    bar();
  else
    bar();
}

void baz() {
  int condition = 3;
  switch(condition) {
    case 0: {
      foo();
      bar();
      break;
    }
    case 2: {
      foo();
      break;
    }
    case 3: {
      foo();
      bar();
      break;
    }
    default: {
      foo();
      break;
    }
}

It is not clear how these issues should be fixed (probably best left to a human), but clang-tidy should definitely warn about these in all control flow statements (if, switch, goto, ...).

**Comment by EugeneZelenko** [comment]
Implemented in `bugprone-branch-clone`.
