### ISSUE TITLE
[SLP][AArch64] Implement cost model for intrinsics.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29606]
|  |  |
| --- | --- |
| Bugzilla Link | [30258](https://llvm.org/bz30258) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
In r270537, Simon added the framework for an intrinsic cost model in the X86 backend.  We should consider doing the same for AArch64 as this may expose opportunities in the SLP vectorizer.

Currently, X86 supports bitreverse, bswap, ctlz, ctpop, and cttz.  I want to say AArch64 has support for most of these in vector form.  However, I don't know how well the AArch64 backend handles the lowering of these intrinsics.

**Comment by RKSimon** [comment]
Closing this old ticket - AArch64TTIImpl::getIntrinsicInstrCost was introduced back at 0fcc6f7a7607b3bf80e67b9f9a07b608724ee031 / https://reviews.llvm.org/D89953
