### ISSUE TITLE
reviews.llvm.org/F* links aren't accessible without logging in to phabricator

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#29600]
|  |  |
| --- | --- |
| Bugzilla Link | [30252](https://llvm.org/bz30252) |
| Version | unspecified |
| OS | All |
| CC | @silvasean |

## Extended Description 
Phab seems to allow pastes or screenshots or whatever, but if you try to look at them it demands you log in. This is problematic for things like https://reviews.llvm.org/D24144, where the review (which is, correctly, public) œrefers to things inside the walled garden.

**Comment by fhahn** [comment]
I don't think we plan on making any Phabricator changes at this point. Closing.
