### ISSUE TITLE
Typo in CMakeLists.txt "LLVM_INCLDE_TESTS"

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29642]
|  |  |
| --- | --- |
| Bugzilla Link | [30294](https://llvm.org/bz30294) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
There is a typo in CMakeLists.txt LLVM_INCLDE_TESTS

  if ( LLVM_INCLUDE_TESTS )
    message(FATAL_ERROR "Including tests when not building utils will not work.
    Either set LLVM_INCLUDE_UTILS to On, or set LLVM_INCLDE_TESTS to Off.")

Should be LLVM_INCLUDE_TESTS

**Comment by arsenm** [comment]
git grep doesn't find this typo
