### ISSUE TITLE
numpunt_byname and moneypunct_byname cannot represent multibyte decimal_point or thousands_sep.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29650]
|  |  |
| --- | --- |
| Bugzilla Link | [30302](https://llvm.org/bz30302) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
The virtual functions they use to return the separators only return a single character. If the requested locale uses multibyte separators then these facets have no way to represent those. For example ru_RU.UTF-8 uses \u00A0 as the thousands_sep on glibc. Unfortunatly libc++ can only return the first byte of that when the underlying char_type is 'char'. The first byte is 0xC2 which ends up creating an invalid utf-8 string.

This probably requires a LWG issue and a fix in the standard.

See also: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=16006

**Comment by mordante** [comment]
I agree it would be good to accept multibyte separators when they are used in a locale.

I'm quite sure LWG will reject it and require a LEWG/SG16 paper to make this change. Since this change requires changing the interface libc++ will not do this unless the Standard changes.
