### ISSUE TITLE
clang crashes on invalid C++ code with "-std=c++11": UNREACHABLE executed at /tmp/llvm-builder/llvm-source-trunk/tools/clang/lib/Sema/SemaTemplate.cpp:3167

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#29661]
|  |  |
| --- | --- |
| Bugzilla Link | [30313](https://llvm.org/bz30313) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
It affects at least all versions 3.2 and later. 

$ clang++ -v
clang version 4.0.0 (trunk 280730)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.1.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$
$ clang++ -c -std=c++11 small.cpp
small.cpp:1:1: error: use of undeclared identifier 'T'
T::template operator "" f < 0 >;
^
literal operator id cannot have a dependent scope
UNREACHABLE executed at /tmp/llvm-builder/llvm-source-trunk/tools/clang/lib/Sema/SemaTemplate.cpp:3167!
#&#8203;0 0x0000000001e484f5 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/clang-trunk/bin/clang-4.0+0x1e484f5)
#&#8203;1 0x0000000001e465de llvm::sys::RunSignalHandlers() (/usr/local/clang-trunk/bin/clang-4.0+0x1e465de)
#&#8203;2 0x0000000001e46740 SignalHandler(int) (/usr/local/clang-trunk/bin/clang-4.0+0x1e46740)
#&#8203;3 0x00007fb925d37340 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10340)
#&#8203;4 0x00007fb924b28cc9 gsignal /build/eglibc-3GlaMS/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;5 0x00007fb924b2c0d8 abort /build/eglibc-3GlaMS/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;6 0x0000000001dfa47a (/usr/local/clang-trunk/bin/clang-4.0+0x1dfa47a)
#&#8203;7 0x0000000002f2a900 clang::Sema::ActOnDependentTemplateName(clang::Scope*, clang::CXXScopeSpec&, clang::SourceLocation, clang::UnqualifiedId&, clang::OpaquePtr<clang::QualType>, bool, clang::OpaquePtr<clang::TemplateName>&) (/usr/local/clang-trunk/bin/clang-4.0+0x2f2a900)
#&#8203;8 0x00000000029d0e80 clang::Parser::ParseOptionalCXXScopeSpecifier(clang::CXXScopeSpec&, clang::OpaquePtr<clang::QualType>, bool, bool*, bool, clang::IdentifierInfo**) (/usr/local/clang-trunk/bin/clang-4.0+0x29d0e80)
#&#8203;9 0x000000000297b94a clang::Parser::TryAnnotateCXXScopeToken(bool) (/usr/local/clang-trunk/bin/clang-4.0+0x297b94a)
#&#8203;10 0x000000000299940c clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) (/usr/local/clang-trunk/bin/clang-4.0+0x299940c)
#&#8203;11 0x000000000297c046 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/usr/local/clang-trunk/bin/clang-4.0+0x297c046)
#&#8203;12 0x000000000297c7b1 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) [clone .part.223] (/usr/local/clang-trunk/bin/clang-4.0+0x297c7b1)
#&#8203;13 0x000000000297c7ef clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/usr/local/clang-trunk/bin/clang-4.0+0x297c7ef)
#&#8203;14 0x00000000029813e0 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/usr/local/clang-trunk/bin/clang-4.0+0x29813e0)
#&#8203;15 0x0000000002981f12 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/usr/local/clang-trunk/bin/clang-4.0+0x2981f12)
#&#8203;16 0x000000000298214c clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/usr/local/clang-trunk/bin/clang-4.0+0x298214c)
#&#8203;17 0x000000000297937b clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x297937b)
#&#8203;18 0x00000000025ea82e clang::CodeGenAction::ExecuteAction() (/usr/local/clang-trunk/bin/clang-4.0+0x25ea82e)
#&#8203;19 0x00000000022e8cce clang::FrontendAction::Execute() (/usr/local/clang-trunk/bin/clang-4.0+0x22e8cce)
#&#8203;20 0x00000000022be326 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/clang-trunk/bin/clang-4.0+0x22be326)
#&#8203;21 0x00000000023783d2 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/clang-trunk/bin/clang-4.0+0x23783d2)
#&#8203;22 0x0000000000b567a0 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/clang-trunk/bin/clang-4.0+0xb567a0)
#&#8203;23 0x0000000000b0123f main (/usr/local/clang-trunk/bin/clang-4.0+0xb0123f)
#&#8203;24 0x00007fb924b13ec5 __libc_start_main /build/eglibc-3GlaMS/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;25 0x0000000000b528fe _start (/usr/local/clang-trunk/bin/clang-4.0+0xb528fe)
Stack dump:
0.      Program arguments: /usr/local/clang-trunk/bin/clang-4.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name small.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /data2/small.gcno -resource-dir /usr/local/clang-trunk/bin/../lib/clang/4.0.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward -internal-isystem /usr/local/include -internal-isystem /usr/local/clang-trunk/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /data2 -ferror-limit 19 -fmessage-length 201 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o small.o -x c++ small.cpp
1.      small.cpp:1:27: current parser token '<'
clang-4.0: error: unable to execute command: Aborted (core dumped)
clang-4.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0 (trunk 280730)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
clang-4.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-4.0: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-4.0: note: diagnostic msg: /tmp/small-473954.cpp
clang-4.0: note: diagnostic msg: /tmp/small-473954.sh
clang-4.0: note: diagnostic msg:

********************
$

--------------------------------------

T::template operator "" f < 0 >;

**Comment by wheatman** [comment]
This was fixed between 9.0 and 11.0
https://godbolt.org/z/77fP1EYcM

code
```
// compile with -std=c++11
T::template operator "" f < 0 >;
```

old dump
```
<source>:2:1: error: use of undeclared identifier 'T'
T::template operator "" f < 0 >;
^
literal operator id cannot have a dependent scope
UNREACHABLE executed at /root/llvm-project/clang/lib/Sema/SemaTemplate.cpp:4469!
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9 -cc1 -triple x86_64-unknown-linux-gnu -S -disable-free -main-file-name example.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -coverage-notes-file /app/output.gcno -resource-dir /opt/compiler-explorer/clang-assertions-9.0.0/lib/clang/9.0.0 -internal-isystem /opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/../../../../include/c++/9.2.0 -internal-isystem /opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/../../../../include/c++/9.2.0/x86_64-linux-gnu -internal-isystem /opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/../../../../include/c++/9.2.0/backward -internal-isystem /usr/local/include -internal-isystem /opt/compiler-explorer/clang-assertions-9.0.0/lib/clang/9.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /app -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -mllvm --x86-asm-syntax=intel -faddrsig -o /app/output.s -x c++ <source> 
1.	<source>:2:27: current parser token '<'
 #0 0x000055dcedf249aa llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x2d249aa)
 #1 0x000055dcedf22654 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x2d22654)
 #2 0x000055dcedf22792 SignalHandler(int) (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x2d22792)
 #3 0x00007f3283dfb420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007f32838c800b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007f32838a7859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x000055dcedebf3ba (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x2cbf3ba)
 #7 0x000055dcef863c87 (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x4663c87)
 #8 0x000055dcef368e1d clang::Parser::ParseOptionalCXXScopeSpecifier(clang::CXXScopeSpec&, clang::OpaquePtr<clang::QualType>, bool, bool*, bool, clang::IdentifierInfo**, bool) (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x4168e1d)
 #9 0x000055dcef31509b clang::Parser::TryAnnotateCXXScopeToken(bool) (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x411509b)
#10 0x000055dcef339a8a clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x4139a8a)
#11 0x000055dcef31679f clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x411679f)
#12 0x000055dcef3170b1 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.215) (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x41170b1)
#13 0x000055dcef31af70 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x411af70)
#14 0x000055dcef31c2b9 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x411c2b9)
#15 0x000055dcef31c657 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x411c657)
#16 0x000055dcef3120a6 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x41120a6)
#17 0x000055dceecd5be8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x3ad5be8)
#18 0x000055dcee605ec9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x3405ec9)
#19 0x000055dcee5c9fc1 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x33c9fc1)
#20 0x000055dcee6b086f clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x34b086f)
#21 0x000055dcec24a36f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x104a36f)
#22 0x000055dcec1b35a9 main (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0xfb35a9)
#23 0x00007f32838a9083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#24 0x000055dcec24595a _start (/opt/compiler-explorer/clang-assertions-9.0.0/bin/clang-9+0x104595a)
clang-9: error: unable to execute command: Aborted (core dumped)
clang-9: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 254
```

new error
```
<source>:2:1: error: use of undeclared identifier 'T'
T::template operator "" f < 0 >;
^
1 error generated.
Compiler returned: 1
```
