### ISSUE TITLE
clang crashes on invalid C++ code (use of undeclared variable): Assertion `TyposInContext < ~0U && "Recursive call of CorrectDelayedTyposInExpr"' failed

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#29662]
|  |  |
| --- | --- |
| Bugzilla Link | [30314](https://llvm.org/bz30314) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
Clang crashes on the given code without issuing any proper diagnostics. This affects 3.6.x and later; 3.5.x properly rejects the code. 

It is interesting that the crash appears to be sensitive to the choices of identifier names for "end" and "bend". 

$ clang++ -v
clang version 4.0.0 (trunk 280730)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.1.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$
$ clang++ -c small.cpp
clang-4.0: /tmp/llvm-builder/llvm-source-trunk/tools/clang/lib/Sema/SemaExprCXX.cpp:6958: clang::ExprResult clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, llvm::function_ref<clang::ActionResult<clang::Expr*>(clang::Expr*)>): Assertion `TyposInContext < ~0U && "Recursive call of CorrectDelayedTyposInExpr"' failed.
#&#8203;0 0x0000000001e484f5 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/clang-trunk/bin/clang-4.0+0x1e484f5)
#&#8203;1 0x0000000001e465de llvm::sys::RunSignalHandlers() (/usr/local/clang-trunk/bin/clang-4.0+0x1e465de)
#&#8203;2 0x0000000001e46740 SignalHandler(int) (/usr/local/clang-trunk/bin/clang-4.0+0x1e46740)
#&#8203;3 0x00007f42abd63340 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10340)
#&#8203;4 0x00007f42aab54cc9 gsignal /build/eglibc-3GlaMS/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;5 0x00007f42aab580d8 abort /build/eglibc-3GlaMS/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;6 0x00007f42aab4db86 __assert_fail_base /build/eglibc-3GlaMS/eglibc-2.19/assert/assert.c:92:0
#&#8203;7 0x00007f42aab4dc32 (/lib/x86_64-linux-gnu/libc.so.6+0x2fc32)
#&#8203;8 0x0000000002db3822 clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) (/usr/local/clang-trunk/bin/clang-4.0+0x2db3822)
#&#8203;9 0x0000000002d65058 clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2d65058)
#&#8203;10 0x0000000002dcc02d clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformCallExpr(clang::CallExpr*) (/usr/local/clang-trunk/bin/clang-4.0+0x2dcc02d)
#&#8203;11 0x0000000002db4fcf clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformExpr(clang::Expr*) (/usr/local/clang-trunk/bin/clang-4.0+0x2db4fcf)
#&#8203;12 0x0000000002db5bf9 (anonymous namespace)::TransformTypos::TryTransform(clang::Expr*) (/usr/local/clang-trunk/bin/clang-4.0+0x2db5bf9)
#&#8203;13 0x0000000002db263d clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) (/usr/local/clang-trunk/bin/clang-4.0+0x2db263d)
#&#8203;14 0x0000000002db3963 clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2db3963)
#&#8203;15 0x0000000002ee1900 clang::Sema::ActOnExprStmt(clang::ActionResult<clang::Expr*, true>) (/usr/local/clang-trunk/bin/clang-4.0+0x2ee1900)
#&#8203;16 0x00000000029ffa3d clang::Parser::ParseExprStatement() (/usr/local/clang-trunk/bin/clang-4.0+0x29ffa3d)
#&#8203;17 0x00000000029fce5f clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedContsructsKind, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/usr/local/clang-trunk/bin/clang-4.0+0x29fce5f)
#&#8203;18 0x00000000029fd03e clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedContsructsKind, clang::SourceLocation*) (/usr/local/clang-trunk/bin/clang-4.0+0x29fd03e)
#&#8203;19 0x0000000002a019b9 clang::Parser::ParseCompoundStatementBody(bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2a019b9)
#&#8203;20 0x0000000002a041f9 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/usr/local/clang-trunk/bin/clang-4.0+0x2a041f9)
#&#8203;21 0x0000000002980a97 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/usr/local/clang-trunk/bin/clang-4.0+0x2980a97)
#&#8203;22 0x0000000002a119a8 clang::Parser::ParseSingleDeclarationAfterTemplate(unsigned int, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) (/usr/local/clang-trunk/bin/clang-4.0+0x2a119a8)
#&#8203;23 0x0000000002a12627 clang::Parser::ParseTemplateDeclarationOrSpecialization(unsigned int, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) (/usr/local/clang-trunk/bin/clang-4.0+0x2a12627)
#&#8203;24 0x0000000002a1299a clang::Parser::ParseDeclarationStartingWithTemplate(unsigned int, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) (/usr/local/clang-trunk/bin/clang-4.0+0x2a1299a)
#&#8203;25 0x00000000029a3694 clang::Parser::ParseDeclaration(unsigned int, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) (/usr/local/clang-trunk/bin/clang-4.0+0x29a3694)
#&#8203;26 0x0000000002981402 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/usr/local/clang-trunk/bin/clang-4.0+0x2981402)
#&#8203;27 0x0000000002981f12 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/usr/local/clang-trunk/bin/clang-4.0+0x2981f12)
#&#8203;28 0x0000000002979393 clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2979393)
#&#8203;29 0x00000000025ea82e clang::CodeGenAction::ExecuteAction() (/usr/local/clang-trunk/bin/clang-4.0+0x25ea82e)
#&#8203;30 0x00000000022e8cce clang::FrontendAction::Execute() (/usr/local/clang-trunk/bin/clang-4.0+0x22e8cce)
#&#8203;31 0x00000000022be326 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/clang-trunk/bin/clang-4.0+0x22be326)
#&#8203;32 0x00000000023783d2 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/clang-trunk/bin/clang-4.0+0x23783d2)
#&#8203;33 0x0000000000b567a0 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/clang-trunk/bin/clang-4.0+0xb567a0)
#&#8203;34 0x0000000000b0123f main (/usr/local/clang-trunk/bin/clang-4.0+0xb0123f)
#&#8203;35 0x00007f42aab3fec5 __libc_start_main /build/eglibc-3GlaMS/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;36 0x0000000000b528fe _start (/usr/local/clang-trunk/bin/clang-4.0+0xb528fe)
Stack dump:
0.      Program arguments: /usr/local/clang-trunk/bin/clang-4.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name small.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /data2/c-hunter/test/fun/try5b/RES8/LATERCLANG/20160730-clang++-trunk-O3-m32-build-232354/small.gcno -resource-dir /usr/local/clang-trunk/bin/../lib/clang/4.0.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward -internal-isystem /usr/local/include -internal-isystem /usr/local/clang-trunk/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /data2/c-hunter/test/fun/try5b/RES8/LATERCLANG/20160730-clang++-trunk-O3-m32-build-232354 -ferror-limit 19 -fmessage-length 166 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o small.o -x c++ small.cpp
1.      small.cpp:12:1: current parser token '}'
2.      small.cpp:9:1: parsing function body 'A::operator='
3.      small.cpp:9:1: in compound statement ('{}')
clang-4.0: error: unable to execute command: Aborted (core dumped)
clang-4.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0 (trunk 280730)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
clang-4.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-4.0: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-4.0: note: diagnostic msg: /tmp/small-ec0f54.cpp
clang-4.0: note: diagnostic msg: /tmp/small-ec0f54.sh
clang-4.0: note: diagnostic msg:

********************
$

--------------------------------------------------------------------

template < typename T > struct A
{ 
  A &operator= (const A &);
  void end ();
  void foo (int, T);
};

template < typename T > A < T > & A < T >::operator= (const A &)
{ 
  T t;
  foo (bend, t);
}

**Comment by wheatman** [comment]
This seems to have been fixed between 6.0.0 and 7.0.0
https://cexplorer.testlabs.pro/z/E3EjbW

As a note the issue only showed up with assertions

for reference

code 
```
template < typename T > struct A
{ 
  A &operator= (const A &);
  void end ();
  void foo (int, T);
};

template < typename T > A < T > & A < T >::operator= (const A &)
{ 
  T t;
  foo (bend, t);
}
```

dump
```
clang-6.0: /home/tonik/llvm-project/llvm/tools/clang/lib/Sema/SemaExprCXX.cpp:7508: clang::ExprResult clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, llvm::function_ref<clang::ActionResult<clang::Expr*>(clang::Expr*)>): Assertion `TyposInContext < ~0U && "Recursive call of CorrectDelayedTyposInExpr"' failed.
#0 0x0000000002305e1a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x2305e1a)
#1 0x0000000002303a46 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x2303a46)
#2 0x0000000002303de5 SignalHandler(int) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x2303de5)
#3 0x00007fbcfd654df0 __restore_rt (/lib64/libc.so.6+0x54df0)
#4 0x00007fbcfd6a154c __pthread_kill_implementation (/lib64/libc.so.6+0xa154c)
#5 0x00007fbcfd654d46 __GI_raise (/lib64/libc.so.6+0x54d46)
#6 0x00007fbcfd6287f3 __GI_abort (/lib64/libc.so.6+0x287f3)
#7 0x00007fbcfd62871b _nl_load_domain.cold (/lib64/libc.so.6+0x2871b)
#8 0x00007fbcfd64dce6 (/lib64/libc.so.6+0x4dce6)
#9 0x0000000003520640 clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x3520640)
#10 0x00000000034c8f86 clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x34c8f86)
#11 0x0000000003513015 (anonymous namespace)::TransformTypos::RebuildCallExpr(clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x3513015)
#12 0x0000000003532d99 clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformCallExpr(clang::CallExpr*) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x3532d99)
#13 0x000000000351ec66 clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x351ec66)
#14 0x00000000035208c4 clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool, bool) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x35208c4)
#15 0x000000000366f920 clang::Sema::ActOnExprStmt(clang::ActionResult<clang::Expr*, true>) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x366f920)
#16 0x0000000003125a19 clang::Parser::ParseExprStatement() (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x3125a19)
#17 0x0000000003122ca6 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedConstructsKind, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x3122ca6)
#18 0x0000000003122f9c clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedConstructsKind, clang::SourceLocation*) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x3122f9c)
#19 0x0000000003127430 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x3127430)
#20 0x00000000031299b0 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x31299b0)
#21 0x00000000030a1577 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x30a1577)
#22 0x0000000003136f8b clang::Parser::ParseSingleDeclarationAfterTemplate(clang::DeclaratorContext, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x3136f8b)
#23 0x0000000003137e75 clang::Parser::ParseTemplateDeclarationOrSpecialization(clang::DeclaratorContext, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x3137e75)
#24 0x00000000031380b9 clang::Parser::ParseDeclarationStartingWithTemplate(clang::DeclaratorContext, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x31380b9)
#25 0x00000000030c57d6 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x30c57d6)
#26 0x00000000030a3ecd clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x30a3ecd)
#27 0x00000000030a4b9b clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x30a4b9b)
#28 0x0000000003099512 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x3099512)
#29 0x0000000002c578f8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x2c578f8)
#30 0x00000000028d5d66 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x28d5d66)
#31 0x000000000289d89e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x289d89e)
#32 0x000000000297300a clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0x297300a)
#33 0x0000000000af9330 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0xaf9330)
#34 0x0000000000a7e95e main (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0xa7e95e)
#35 0x00007fbcfd63feb0 __libc_start_call_main (/lib64/libc.so.6+0x3feb0)
#36 0x00007fbcfd63ff60 __libc_start_main_alias_2 (/lib64/libc.so.6+0x3ff60)
#37 0x0000000000af52f9 _start (/opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0+0xaf52f9)
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-6.0.0-assert/bin/clang-6.0 -cc1 -triple x86_64-unknown-linux-gnu -S -disable-free -main-file-name example.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -coverage-notes-file /tmp/compiler-explorer-compiler202366-960250-1ebwmd2.pcta/output.gcno -resource-dir /opt/compiler-explorer/clang-6.0.0-assert/lib/clang/6.0.0 -internal-isystem /opt/compiler-explorer/gcc-7.3.0/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0 -internal-isystem /opt/compiler-explorer/gcc-7.3.0/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/x86_64-linux-gnu -internal-isystem /opt/compiler-explorer/gcc-7.3.0/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/backward -internal-isystem /usr/local/include -internal-isystem /opt/compiler-explorer/clang-6.0.0-assert/lib/clang/6.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /tmp/compiler-explorer-compiler202366-960250-1ebwmd2.pcta -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -mllvm --x86-asm-syntax=intel -o /tmp/compiler-explorer-compiler202366-960250-1ebwmd2.pcta/output.s -x c++ <source> 
1.	<source>:12:1: current parser token '}'
2.	<source>:9:1: parsing function body 'A::operator='
3.	<source>:9:1: in compound statement ('{}')
clang-6.0: error: unable to execute command: Aborted (core dumped)
clang-6.0: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 254
```
