### ISSUE TITLE
[feature request] add check, which would suggest making a variable const

### ISSUE THREAD

**Issue by kirillbobyrev** [llvm/llvm-project#29683]
|  |  |
| --- | --- |
| Bugzilla Link | [30335](https://llvm.org/bz30335) |
| Version | unspecified |
| OS | All |
| CC | @JonasToth,@EugeneZelenko |

## Extended Description 
Often one can see a code piece like this:

```
std::string s;
std::string l = "Hello, " + s + "!\n";
doSomethingWithString(s);
giveMeString(s);
```

while above used functions have following signatures:

```
whatever_type doSomethingWithString(const std::string &s);
whatever_type giveMeString(std::string s);
```

Thus, `s` can be a `const std::string`, but it's time-consuming to look up every method that uses s and figure out whether they are fine with `s` being const or not.

Automating that would be nice IMO.

**Comment by JonasToth** [comment]
https://reviews.llvm.org/D54943
