### ISSUE TITLE
clang-format breaks user-defined literal for string_view (from experimental)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29696]
|  |  |
| --- | --- |
| Bugzilla Link | [30348](https://llvm.org/bz30348) |
| Version | 3.9 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @BillyONeal,@pepsiman |

## Extended Description 
With std::experimental::string_view comes a new UDL, operator""sv - clang-format however inserts an extra space when trying to use it, breaking compile. Operator""s for std::string is processed correctly.

Before formatting:
```
cat test.cc
#include <string>
#include <experimental/string_view>

using namespace std::experimental;
using namespace std::string_literals;

const auto x = "broken"sv;
const auto y = "works"s;
```

After:
```
clang-format -style=Google test.cc 
#include <experimental/string_view>
#include <string>

using namespace std::experimental;
using namespace std::string_literals;

const auto x = "broken" sv;
const auto y = "works"s;
```

**Comment by mkurdej** [comment]
Fixed in https://reviews.llvm.org/D26829, in release v4.
