### ISSUE TITLE
Assert in LegacyPassManager when adding PostDominatorTree to analysis pass

### ISSUE THREAD

**Issue by cddouma-arm** [llvm/llvm-project#29718]
|  |  |
| --- | --- |
| Bugzilla Link | [30370](https://llvm.org/bz30370) |
| Version | trunk |
| OS | All |
| Attachments | [reproducer - created against svn revision 281213.](https://user-images.githubusercontent.com/92601870/143754362-15d93310-80d6-43ba-9ee4-2efdf1e55c51.gz) |

## Extended Description 

When I add PostDominatorTree analysis pass to scalar-evolution (as a transitive requirement) the LegacyPassManager run into an assert:
opt: ../lib/IR/LegacyPassManager.cpp:520: void llvm::PMTopLevelManager::setLastUser(llvm::ArrayRef<llvm::Pass*>, llvm::Pass*): Assertion `AnalysisPass && "Expected analysis pass to exist."' failed.

This looks like a bad interaction between the new PassManager and the LegacyPassManager.

To reproduce, use the attached patch on ScalarEvolution.cpp that only adds PostDominatorTree as a required pass and run using:

true | opt -loop-idiom -loop-unroll

This currently blocks my attempt to solve bug 28429.

**Comment by arsenm** [comment]
Legacy PM is dead enough to ignore this
