### ISSUE TITLE
broken formatting of post-fix increment when combined with noexcept

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#29725]
|  |  |
| --- | --- |
| Bugzilla Link | [30377](https://llvm.org/bz30377) |
| Version | trunk |
| OS | All |

## Extended Description 
The following code doesn't get formatted properly"

```
struct A {
  int idx_;
  
  // prefix increment: fine
  constexpr A& operator++() noexcept {  
    ++idx_;
    return (*this);
  }

  // postfix increment: no space between (int) and noexcept:
  constexpr A operator++(int)noexcept {
    A tmp(*this);
    ++(*this);
    return tmp;
  }
};
```

As you can see there is no space between the arguments of postfix increment and the noexcept qualifier.

I haven't tried but the same might be true for other function qualifiers (const, override, final), for function reference qualifiers (&, const&, &&), and other operators like --, *, ->, /, ...

**Comment by mydeveloperday** [comment]
This formats as 

```
struct A {
  int idx_;

  // prefix increment: fine
  constexpr A &operator++() noexcept {
    ++idx_;
    return (*this);
  }

  // postfix increment: no space between (int) and noexcept:
  constexpr A operator++(int) noexcept {
    A tmp(*this);
    ++(*this);
    return tmp;
  }
};
```

As it appears fixed I am closing this issue
