### ISSUE TITLE
Merge Phabricator product and Website/Phabricator component

### ISSUE THREAD

**Issue by MatzeB** [llvm/llvm-project#29736]
|  |  |
| --- | --- |
| Bugzilla Link | [30388](https://llvm.org/bz30388) |
| Version | unspecified |
| OS | All |

## Extended Description 
We currently have a product Phabricator in Bugzilla and a phabricator component under the Website Product. One of them should probably be merged into the other.

**Comment by xgupta** [comment]
We have moved to github issues.
