### ISSUE TITLE
GCC produces ABI-incompatible libc++ dylibs

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29739]
|  |  |
| --- | --- |
| Bugzilla Link | [30391](https://llvm.org/bz30391) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
GCC handles _LIBCPP_INLINE_VISIBILITY differently than Clang. In particular when the attributes are applied to symbols which are externally instantiated.

For example in the reproducer below Clang will emit both 'foo' and 'bar' with default visibility while GCC only emits a non-hidden 'foo'.  

// RUN: g++ -std=c++11 -shared -O3 test.cpp && sym_extract.py a.out
// RUN: clang++ -std=c++11 -shared -O3 test.cpp && sym_extract.py a.out
template <class T>
struct Foo {
  void foo();
  void bar();
};

template <class T>
void Foo<T>::foo() {}

template <class T>
inline __attribute__((visibility("hidden"), always_inline))
void Foo<T>::bar() {}

template struct Foo<int>;

One way to fix this would be to add _LIBCPP_EXTERN_TEMPLATE_INLINE_VISIBILITY which is defined as __attribute__((visibility("default"), always_inline)).

**Comment by philnik777** [comment]
This has been addressed by https://llvm.org/D24602.
