### ISSUE TITLE
Regression(280979): 3 Transforms/LoopVectorize/X86/ tests fail when using gcc 4.8.2 as host compiler

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#29798]
|  |  |
| --- | --- |
| Bugzilla Link | [30450](https://llvm.org/bz30450) |
| Version | trunk |
| OS | Linux |

## Extended Description 
If I use gcc 4.8.2 (from here http://commondatastorage.googleapis.com/chromium-browser-clang/index.html?path=tools/ - gcc482precise.tgz) to build clang and then run tests, three tests fail for me. This started at r280979:

lit.py: /usr/local/google/home/thakis/src/chrome/src/third_party/llvm/tools/clang/test/lit.cfg:195: note: using clang: '/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/clang'
-- Testing: 27715 tests, 48 threads --
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90
FAIL: LLVM :: Transforms/LoopVectorize/X86/scatter_crash.ll (26269 of 27715)
******************** TEST 'LLVM :: Transforms/LoopVectorize/X86/scatter_crash.ll' FAILED ********************
Script:
--
/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt < /usr/local/google/home/thakis/src/chrome/src/third_party/llvm/test/Transforms/LoopVectorize/X86/scatter_crash.ll -loop-vectorize -S | /usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/FileCheck /usr/local/google/home/thakis/src/chrome/src/third_party/llvm/test/Transforms/LoopVectorize/X86/scatter_crash.ll
--
Exit Code: 2

Command Output (stderr):
--
opt: /usr/local/google/home/thakis/src/chrome/src/third_party/llvm/lib/IR/Instructions.cpp:1636: void llvm::GetElementPtrInst::init(llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&): Assertion `getNumOperands() == 1 + IdxList.size() && "NumOperands not initialized?"' failed.
#&#8203;0 0x00000000010f4ca5 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x10f4ca5)
#&#8203;1 0x00000000010f2c7e llvm::sys::RunSignalHandlers() (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x10f2c7e)
#&#8203;2 0x00000000010f2de2 SignalHandler(int) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x10f2de2)
#&#8203;3 0x00007fb9dd06e330 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10330)
#&#8203;4 0x00007fb9dbc62c37 gsignal /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;5 0x00007fb9dbc66028 abort /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;6 0x00007fb9dbc5bbf6 __assert_fail_base /build/eglibc-oGUzwX/eglibc-2.19/assert/assert.c:92:0
#&#8203;7 0x00007fb9dbc5bca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
#&#8203;8 0x0000000000cd920c (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0xcd920c)
#&#8203;9 0x00000000011ea877 llvm::GetElementPtrInst::Create(llvm::Type*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&, llvm::Instruction*) [clone .constprop.1495] (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x11ea877)
#&#8203;10 0x00000000011fa7f6 (anonymous namespace)::InnerLoopVectorizer::vectorizeMemoryInstruction(llvm::Instruction*) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x11fa7f6)
#&#8203;11 0x00000000011f2de1 (anonymous namespace)::InnerLoopVectorizer::vectorizeBlockInLoop(llvm::BasicBlock*, llvm::SmallVector<llvm::PHINode*, 4u>*) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x11f2de1)
#&#8203;12 0x00000000011f52b3 (anonymous namespace)::InnerLoopVectorizer::vectorizeLoop() (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x11f52b3)
#&#8203;13 0x00000000012044e2 llvm::LoopVectorizePass::processLoop(llvm::Loop*) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x12044e2)
#&#8203;14 0x00000000012059d5 llvm::LoopVectorizePass::runImpl(llvm::Function&, llvm::ScalarEvolution&, llvm::LoopInfo&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::BlockFrequencyInfo&, llvm::TargetLibraryInfo*, llvm::DemandedBits&, llvm::AAResults&, llvm::AssumptionCache&, std::function<llvm::LoopAccessInfo const& (llvm::Loop&)>&, llvm::OptimizationRemarkEmitter&) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x12059d5)
#&#8203;15 0x0000000001206064 (anonymous namespace)::LoopVectorize::runOnFunction(llvm::Function&) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x1206064)
#&#8203;16 0x0000000000cfc563 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0xcfc563)
#&#8203;17 0x0000000000cfc60c llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0xcfc60c)
#&#8203;18 0x0000000000cfcc2f llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0xcfcc2f)
#&#8203;19 0x0000000000623db2 main (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x623db2)
#&#8203;20 0x00007fb9dbc4df45 __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;21 0x0000000000650938 _start (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x650938)
Stack dump:
0.	Program arguments: /usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt -loop-vectorize -S 
1.	Running pass 'Function Pass Manager' on module '<stdin>'.
2.	Running pass 'Loop Vectorization' on function '@_Z3fn1v'
FileCheck error: '-' is empty.
FileCheck command line:  /usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/FileCheck /usr/local/google/home/thakis/src/chrome/src/third_party/llvm/test/Transforms/LoopVectorize/X86/scatter_crash.ll

--

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90
FAIL: LLVM :: Transforms/LoopVectorize/X86/gather_scatter.ll (26288 of 27715)
******************** TEST 'LLVM :: Transforms/LoopVectorize/X86/gather_scatter.ll' FAILED ********************
Script:
--
/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt < /usr/local/google/home/thakis/src/chrome/src/third_party/llvm/test/Transforms/LoopVectorize/X86/gather_scatter.ll  -O3 -mcpu=knl -S | /usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/FileCheck /usr/local/google/home/thakis/src/chrome/src/third_party/llvm/test/Transforms/LoopVectorize/X86/gather_scatter.ll -check-prefix=AVX512
--
Exit Code: 2

Command Output (stderr):
--
opt: /usr/local/google/home/thakis/src/chrome/src/third_party/llvm/lib/IR/Instructions.cpp:1636: void llvm::GetElementPtrInst::init(llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&): Assertion `getNumOperands() == 1 + IdxList.size() && "NumOperands not initialized?"' failed.
#&#8203;0 0x00000000010f4ca5 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x10f4ca5)
#&#8203;1 0x00000000010f2c7e llvm::sys::RunSignalHandlers() (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x10f2c7e)
#&#8203;2 0x00000000010f2de2 SignalHandler(int) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x10f2de2)
#&#8203;3 0x00007fc78328d330 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10330)
#&#8203;4 0x00007fc781e81c37 gsignal /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;5 0x00007fc781e85028 abort /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;6 0x00007fc781e7abf6 __assert_fail_base /build/eglibc-oGUzwX/eglibc-2.19/assert/assert.c:92:0
#&#8203;7 0x00007fc781e7aca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
#&#8203;8 0x0000000000cd920c (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0xcd920c)
#&#8203;9 0x00000000011ea877 llvm::GetElementPtrInst::Create(llvm::Type*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&, llvm::Instruction*) [clone .constprop.1495] (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x11ea877)
#&#8203;10 0x00000000011fa7f6 (anonymous namespace)::InnerLoopVectorizer::vectorizeMemoryInstruction(llvm::Instruction*) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x11fa7f6)
#&#8203;11 0x00000000011f2de1 (anonymous namespace)::InnerLoopVectorizer::vectorizeBlockInLoop(llvm::BasicBlock*, llvm::SmallVector<llvm::PHINode*, 4u>*) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x11f2de1)
#&#8203;12 0x00000000011f52b3 (anonymous namespace)::InnerLoopVectorizer::vectorizeLoop() (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x11f52b3)
#&#8203;13 0x00000000012044e2 llvm::LoopVectorizePass::processLoop(llvm::Loop*) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x12044e2)
#&#8203;14 0x00000000012059d5 llvm::LoopVectorizePass::runImpl(llvm::Function&, llvm::ScalarEvolution&, llvm::LoopInfo&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::BlockFrequencyInfo&, llvm::TargetLibraryInfo*, llvm::DemandedBits&, llvm::AAResults&, llvm::AssumptionCache&, std::function<llvm::LoopAccessInfo const& (llvm::Loop&)>&, llvm::OptimizationRemarkEmitter&) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x12059d5)
#&#8203;15 0x0000000001206064 (anonymous namespace)::LoopVectorize::runOnFunction(llvm::Function&) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x1206064)
#&#8203;16 0x0000000000cfc563 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0xcfc563)
#&#8203;17 0x0000000000cfc60c llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0xcfc60c)
#&#8203;18 0x0000000000cfcc2f llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0xcfcc2f)
#&#8203;19 0x0000000000623db2 main (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x623db2)
#&#8203;20 0x00007fc781e6cf45 __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;21 0x0000000000650938 _start (/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt+0x650938)
Stack dump:
0.	Program arguments: /usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt -O3 -mcpu=knl -S 
1.	Running pass 'Function Pass Manager' on module '<stdin>'.
2.	Running pass 'Loop Vectorization' on function '@foo2'
FileCheck error: '-' is empty.
FileCheck command line:  /usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/FileCheck /usr/local/google/home/thakis/src/chrome/src/third_party/llvm/test/Transforms/LoopVectorize/X86/gather_scatter.ll -check-prefix=AVX512

--

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90
FAIL: LLVM :: Transforms/LoopVectorize/X86/reg-usage.ll (26347 of 27715)
******************** TEST 'LLVM :: Transforms/LoopVectorize/X86/reg-usage.ll' FAILED ********************
Script:
--
/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt < /usr/local/google/home/thakis/src/chrome/src/third_party/llvm/test/Transforms/LoopVectorize/X86/reg-usage.ll -debug-only=loop-vectorize -loop-vectorize -vectorizer-maximize-bandwidth -O2 -mtriple=x86_64-unknown-linux -S 2>&1 | /usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/FileCheck /usr/local/google/home/thakis/src/chrome/src/third_party/llvm/test/Transforms/LoopVectorize/X86/reg-usage.ll
/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt < /usr/local/google/home/thakis/src/chrome/src/third_party/llvm/test/Transforms/LoopVectorize/X86/reg-usage.ll -debug-only=loop-vectorize -loop-vectorize -vectorizer-maximize-bandwidth -O2 -mtriple=x86_64-unknown-linux -mattr=+avx512f -S 2>&1 | /usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/FileCheck /usr/local/google/home/thakis/src/chrome/src/third_party/llvm/test/Transforms/LoopVectorize/X86/reg-usage.ll --check-prefix=AVX512F
--
Exit Code: 134

Command Output (stderr):
--
/usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/test/Transforms/LoopVectorize/X86/Output/reg-usage.ll.script: line 2: 14693 Aborted                 (core dumped) /usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/opt -debug-only=loop-vectorize -loop-vectorize -vectorizer-maximize-bandwidth -O2 -mtriple=x86_64-unknown-linux -mattr=+avx512f -S < /usr/local/google/home/thakis/src/chrome/src/third_party/llvm/test/Transforms/LoopVectorize/X86/reg-usage.ll 2>&1
     14694 Done                    | /usr/local/google/home/thakis/src/chrome/src/third_party/llvm-bootstrap/./bin/FileCheck /usr/local/google/home/thakis/src/chrome/src/third_party/llvm/test/Transforms/LoopVectorize/X86/reg-usage.ll --check-prefix=AVX512F

--

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
Testing Time: 40.51s
********************
Failing Tests (3):
    LLVM :: Transforms/LoopVectorize/X86/gather_scatter.ll
    LLVM :: Transforms/LoopVectorize/X86/reg-usage.ll
    LLVM :: Transforms/LoopVectorize/X86/scatter_crash.ll

**Comment by Endilll** [comment]
Currently the minimum required GCC is 7.4
