### ISSUE TITLE
Fuzzing lld/ELF

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29888]
|  |  |
| --- | --- |
| Bugzilla Link | [30540](https://llvm.org/bz30540) |
| Version | unspecified |
| OS | Linux |
| Depends On | llvm/llvm-project#30263  |
| Attachments | [crashes](https://user-images.githubusercontent.com/60944935/143754463-8163e3c2-9535-43ce-a059-c9429df94ce6.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie,@emaste,@filcab,@pcc |

## Extended Description 
Trying to track crashes here. I did a first run with AFL and will upload the first attachment soon.

**Comment by MaskRay** [comment]
There is no actionable work for the repo itself so closing.
