### ISSUE TITLE
Can't delete inline comment after last upgrade

### ISSUE THREAD

**Issue by joker-eph** [llvm/llvm-project#29920]
|  |  |
| --- | --- |
| Bugzilla Link | [30572](https://llvm.org/bz30572) |
| Version | unspecified |
| OS | All |
| CC | @AaronBallman,@jlebar,@MatzeB |

## Extended Description 
I can now only edit, but not delete comment. When I click on the trash it grays and stays like that forever.

**Comment by JOE1994** [comment]
Closing this as we're no longer using https://reviews.llvm.org for patch reviews.

**Comment by Endilll** [comment]
@JOE1994 Can you use `obsolete` label for such issues?

**Comment by JOE1994** [comment]
> @JOE1994 Can you use `obsolete` label for such issues?

I'll update such tickets that I've closed so far with the `obsolete` label.
