### ISSUE TITLE
clang crashes on valid C++ code: Assertion `!R.empty() && "empty lookup results when building templateid"' failed

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#29931]
|  |  |
| --- | --- |
| Bugzilla Link | [30583](https://llvm.org/bz30583) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
This affects 3.2.x and later, and is a regression from 3.1. 

GCC, ICC, and MSVC all accept the code. 

$ clang++ -v
clang version 4.0.0 (trunk 282702)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.1.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$
$ clang++-3.1 -c small.cpp
$ g++-6.2 -c small.cpp
$
$ clang++ -c small.cpp
clang-4.0: /tmp/llvm-builder/llvm-source-trunk/tools/clang/lib/Sema/SemaTemplate.cpp:3028: clang::ExprResult clang::Sema::BuildTemplateIdExpr(const clang::CXXScopeSpec&, clang::SourceLocation, clang::LookupResult&, bool, const clang::TemplateArgumentListInfo*): Assertion `!R.empty() && "empty lookup results when building templateid"' failed.
#&#8203;0 0x0000000001e8a445 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/clang-trunk/bin/clang-4.0+0x1e8a445)
#&#8203;1 0x0000000001e8852e llvm::sys::RunSignalHandlers() (/usr/local/clang-trunk/bin/clang-4.0+0x1e8852e)
#&#8203;2 0x0000000001e88690 SignalHandler(int) (/usr/local/clang-trunk/bin/clang-4.0+0x1e88690)
#&#8203;3 0x00007f830642a340 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10340)
#&#8203;4 0x00007f830521bcc9 gsignal /build/eglibc-3GlaMS/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;5 0x00007f830521f0d8 abort /build/eglibc-3GlaMS/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;6 0x00007f8305214b86 __assert_fail_base /build/eglibc-3GlaMS/eglibc-2.19/assert/assert.c:92:0
#&#8203;7 0x00007f8305214c32 (/lib/x86_64-linux-gnu/libc.so.6+0x2fc32)
#&#8203;8 0x0000000002fcab47 clang::Sema::BuildTemplateIdExpr(clang::CXXScopeSpec const&, clang::SourceLocation, clang::LookupResult&, bool, clang::TemplateArgumentListInfo const*) (/usr/local/clang-trunk/bin/clang-4.0+0x2fcab47)
#&#8203;9 0x0000000002dfdcfb clang::Sema::ActOnIdExpression(clang::Scope*, clang::CXXScopeSpec&, clang::SourceLocation, clang::UnqualifiedId&, bool, bool, std::unique_ptr<clang::CorrectionCandidateCallback, std::default_delete<clang::CorrectionCandidateCallback> >, bool, clang::Token*) (/usr/local/clang-trunk/bin/clang-4.0+0x2dfdcfb)
#&#8203;10 0x0000000002a72977 clang::Parser::tryParseCXXIdExpression(clang::CXXScopeSpec&, bool, clang::Token&) (/usr/local/clang-trunk/bin/clang-4.0+0x2a72977)
#&#8203;11 0x0000000002a72aa7 clang::Parser::ParseCXXIdExpression(bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2a72aa7)
#&#8203;12 0x0000000002a5eabc clang::Parser::ParseCastExpression(bool, bool, bool&, clang::Parser::TypeCastState) (/usr/local/clang-trunk/bin/clang-4.0+0x2a5eabc)
#&#8203;13 0x0000000002a6155d clang::Parser::ParseCastExpression(bool, bool, clang::Parser::TypeCastState) (/usr/local/clang-trunk/bin/clang-4.0+0x2a6155d)
#&#8203;14 0x0000000002a615e9 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/usr/local/clang-trunk/bin/clang-4.0+0x2a615e9)
#&#8203;15 0x0000000002a61669 clang::Parser::ParseExpression(clang::Parser::TypeCastState) (/usr/local/clang-trunk/bin/clang-4.0+0x2a61669)
#&#8203;16 0x0000000002aa2db6 clang::Parser::ParseExprStatement() (/usr/local/clang-trunk/bin/clang-4.0+0x2aa2db6)
#&#8203;17 0x0000000002a9ffe7 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedContsructsKind, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/usr/local/clang-trunk/bin/clang-4.0+0x2a9ffe7)
#&#8203;18 0x0000000002aa03ae clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedContsructsKind, clang::SourceLocation*) (/usr/local/clang-trunk/bin/clang-4.0+0x2aa03ae)
#&#8203;19 0x0000000002aa4c89 clang::Parser::ParseCompoundStatementBody(bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2aa4c89)
#&#8203;20 0x0000000002aa74d9 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/usr/local/clang-trunk/bin/clang-4.0+0x2aa74d9)
#&#8203;21 0x0000000002a23547 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/usr/local/clang-trunk/bin/clang-4.0+0x2a23547)
#&#8203;22 0x0000000002ab4c68 clang::Parser::ParseSingleDeclarationAfterTemplate(unsigned int, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) (/usr/local/clang-trunk/bin/clang-4.0+0x2ab4c68)
#&#8203;23 0x0000000002ab58e7 clang::Parser::ParseTemplateDeclarationOrSpecialization(unsigned int, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) (/usr/local/clang-trunk/bin/clang-4.0+0x2ab58e7)
#&#8203;24 0x0000000002ab5c5a clang::Parser::ParseDeclarationStartingWithTemplate(unsigned int, clang::SourceLocation&, clang::AccessSpecifier, clang::AttributeList*) (/usr/local/clang-trunk/bin/clang-4.0+0x2ab5c5a)
#&#8203;25 0x0000000002a46124 clang::Parser::ParseDeclaration(unsigned int, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) (/usr/local/clang-trunk/bin/clang-4.0+0x2a46124)
#&#8203;26 0x0000000002a23eaa clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/usr/local/clang-trunk/bin/clang-4.0+0x2a23eaa)
#&#8203;27 0x0000000002a249d2 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/usr/local/clang-trunk/bin/clang-4.0+0x2a249d2)
#&#8203;28 0x0000000002a24c0c clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/usr/local/clang-trunk/bin/clang-4.0+0x2a24c0c)
#&#8203;29 0x0000000002a1bd8b clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/clang-trunk/bin/clang-4.0+0x2a1bd8b)
#&#8203;30 0x000000000263473e clang::CodeGenAction::ExecuteAction() (/usr/local/clang-trunk/bin/clang-4.0+0x263473e)
#&#8203;31 0x000000000232cdae clang::FrontendAction::Execute() (/usr/local/clang-trunk/bin/clang-4.0+0x232cdae)
#&#8203;32 0x00000000023027fe clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/clang-trunk/bin/clang-4.0+0x23027fe)
#&#8203;33 0x00000000023bc4c2 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/clang-trunk/bin/clang-4.0+0x23bc4c2)
#&#8203;34 0x0000000000b91f10 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/clang-trunk/bin/clang-4.0+0xb91f10)
#&#8203;35 0x0000000000b3a8f5 main (/usr/local/clang-trunk/bin/clang-4.0+0xb3a8f5)
#&#8203;36 0x00007f8305206ec5 __libc_start_main /build/eglibc-3GlaMS/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;37 0x0000000000b8e0be _start (/usr/local/clang-trunk/bin/clang-4.0+0xb8e0be)
Stack dump:
0.      Program arguments: /usr/local/clang-trunk/bin/clang-4.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name small.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /data2/small.gcno -resource-dir /usr/local/clang-trunk/bin/../lib/clang/4.0.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward -internal-isystem /usr/local/include -internal-isystem /usr/local/clang-trunk/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /data2 -ferror-limit 19 -fmessage-length 178 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o small.o -x c++ small.cpp
1.      small.cpp:3:18: current parser token '('
2.      small.cpp:2:1: parsing function body 'f'
3.      small.cpp:2:1: in compound statement ('{}')
clang-4.0: error: unable to execute command: Aborted (core dumped)
clang-4.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0 (trunk 282702)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
clang-4.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-4.0: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-4.0: note: diagnostic msg: /tmp/small-d71383.cpp
clang-4.0: note: diagnostic msg: /tmp/small-d71383.sh
clang-4.0: note: diagnostic msg:

********************
$

------------------------------------

template < typename > void f ()
{ 
  f < struct f > ();
}

**Comment by fhahn** [comment]
Clang now generates the following error message and does not crash: https://clang.godbolt.org/z/e8vhjrd4n

```
<source>:3:1: warning: use of function template name with no prior declaration in function call with explicit template arguments is a C++20 extension [-Wc++20-extensions]
f < struct f > ();
^
1 warning generated.
Compiler returned: 0
```
