### ISSUE TITLE
libc++experimental built w/ UBSAN has undefined references to __muloti4 builtin

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#29991]
|  |  |
| --- | --- |
| Bugzilla Link | [30643](https://llvm.org/bz30643) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @apolukhin,@mclow |

## Extended Description 
For some reason the typical GNU libraries don't provide this builtin, but libclang_rt.builtins-x86_64.a does. This means that the user must manually link the libclang builtins to get UBSAN to work.

The missing builtin is required when doing 128-bit integer multiplication in filesystem.

I'm filing this bug as a reminder to fix this.

**Comment by philnik777** [comment]
Closing, since the underlying issue is that we don't have compiler-rt. That's not something we can change within libc++.
