### ISSUE TITLE
clang 3.9 release and 4.0 trunk ICE with -fsanitize-coverage=trace-pc on Windows

### ISSUE THREAD

**Issue by 1feda113-18e2-42e3-8624-9c17d4d32ec3** [llvm/llvm-project#30003]
|  |  |
| --- | --- |
| Bugzilla Link | [30655](https://llvm.org/bz30655) |
| Version | 3.9 |
| OS | Windows NT |
| Attachments | [crash dump](https://user-images.githubusercontent.com/92601429/143754517-99ad9d12-fdb9-4159-9968-e4918be5dec0.gz), [source repro](https://user-images.githubusercontent.com/92601429/143754518-cf696a4d-a0ae-4cda-b841-eac2dbb7597c.gz) |
| CC | @vitalybuka |

## Extended Description 

For smaller programs -fsanitize-coverage=trace-pc works very well with clang targeting the MSVC ABI on Windows. Unfortunately more complex programs ICEs the compiler:

C:\Users\ned\Documents\boostish\kerneltest\test>clang++ -shared -fexceptions -o test_output.dll coverage_main.cpp -I.. -DUNICODE -fsanitize-coverage=trace-pc
Wrote crash dump file "C:\Users\ned\AppData\Local\Temp\clang++.exe-4df732.dmp"
0x00007FF6AEA72CF6 (0x0000017E203C0C80 0x0000000000000000 0x0000000000000000 0x00002F61F001923C)
0x00007FF6AEA72C76 (0x0000017E2021CCB8 0x0000017E2038FA10 0x0000017E2021CCB8 0x0000000000000000)
0x00007FF6B0123F5F (0x00000000202D4301 0x0000000000000855 0x0000017E20460950 0x0000017E18709E90)
0x00007FF6B0122ED8 (0x00000000000000A1 0x0000017E20270DC0 0x0000017E204348D8 0x00000000000000A1)
0x00007FF6AEA489D1 (0x0000017E1F1D8901 0x00007FF6B01DD4D0 0x000000000000001F 0x00000000000008A6)
0x00007FF6AEECCF13 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000017E1A7FD708)
0x00007FF6B01B7665 (0x00007FF6B0CE8920 0x00007FF6AF18B72A 0x0000000800000000 0x00007FF6ADF01001)
0x00007FF6AF6A8E82 (0x0000000000000000 0x0000000000000000 0x0000000000000008 0x0000017E18678AA0)
0x00007FF6AF1C0AD7 (0x0000000000000004 0x0000017E00000013 0x00007FF6B08BBBB7 0x0000000000000004)
0x00007FF6AF18E077 (0x0000017E18684DC0 0x00007FF6B01DD547 0x00002535323EB0BD 0x00007FF6B0CE9188)
0x00007FF6AF1FE8E2 (0x000000000001FF01 0x0000000000000000 0x0000000000000940 0x0000000000000001)
0x00007FF6ADF05B14 (0x0000000000000001 0x0000017E1868B310 0x0000001AA9D8E680 0x00007FF9DB18BDFF)
0x00007FF6ADF03BEC (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF6B01DE1F4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF9D9598364 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FF9DB1C5E91 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
clang++.exe: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.9.0 (branches/release_39)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
clang++.exe: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang++.exe: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++.exe: note: diagnostic msg: C:\Users\ned\AppData\Local\Temp\coverage_main-ae94ef.cpp
clang++.exe: note: diagnostic msg: C:\Users\ned\AppData\Local\Temp\coverage_main-ae94ef.sh
clang++.exe: note: diagnostic msg:

********************

**Comment by Endilll** [comment]
Appears to be fixed in Clang 5: https://godbolt.org/z/4P97W4d8E
Reduced by C-Reduce:
```
template <class _Facet> _Facet use_facet();
struct ios_base {};
struct ostreambuf_iterator {
  ostreambuf_iterator(int);
};
struct num_put {
  void put(ostreambuf_iterator, ios_base, int, int);
};
struct basic_ostream : ios_base {
  struct _Sentry_base {
    _Sentry_base(basic_ostream);
    ~_Sentry_base();
  };
  struct sentry : _Sentry_base {
    sentry(basic_ostream _Ostr) : _Sentry_base(_Ostr) {}
  };
  void operator<<(int) {
    sentry _Ok(*this);
    num_put _Nput_fac = use_facet<num_put>();
    try {
      _Nput_fac.put(0, *this, 0, 0);
    } catch (...) {
    }
  }
};
struct value_type {};
void operator<<(basic_ostream s, value_type) { s << .1; }
```
