### ISSUE TITLE
[GCOV] Crashes when trying to compile a simple cpp file

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#30026]
|  |  |
| --- | --- |
| Bugzilla Link | [30678](https://llvm.org/bz30678) |
| Version | trunk |
| OS | Linux |
| Attachments | [Debug script generated from clang.](https://user-images.githubusercontent.com/60944935/143754521-ee57adff-6d07-4eb4-9b25-a1a74520861a.gz), [Preprocessed cpp file generated by clang for debug.](https://user-images.githubusercontent.com/60944935/143754522-2d3b9efc-fbab-42ad-a323-a3f7cc7c885d.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @vns-mn,@dnovillo,@sebpop,@vedantk |

## Extended Description 

As of trunk on Oct. 11, the x86_64 LLVM compiler is still crashing when trying to compile with the GCOV option. The following is the clang backtrace output.

Attached is the slightly modified debug shell and preprocessed cpp from clang.

---------------

clang -cc1 version 4.0.0 based upon LLVM 4.0.0svn default target x86_64-unknown-linux-gnu
#include "..." search starts here:
End of search list.
clang-4.0: /tmp/tmp.6qQhiGb7vv/llvm/lib/Support/raw_ostream.cpp:525: virtual size_t llvm::raw_fd_ostream::preferred_buffer_size() const: Assertion `FD >= 0 && "File not yet open!"' failed.
#&#8203;0 0x00007f3594c2e235 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/libLLVMSupport.so.40+0xde235)
#&#8203;1 0x00007f3594c2bf8e llvm::sys::RunSignalHandlers() (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/libLLVMSupport.so.40+0xdbf8e)
#&#8203;2 0x00007f3594c2c0f2 SignalHandler(int) (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/libLLVMSupport.so.40+0xdc0f2)
#&#8203;3 0x00007f3598113330 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10330)
#&#8203;4 0x00007f3592adfc37 gsignal /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;5 0x00007f3592ae3028 abort /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;6 0x00007f3592ad8bf6 __assert_fail_base /build/eglibc-oGUzwX/eglibc-2.19/assert/assert.c:92:0
#&#8203;7 0x00007f3592ad8ca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
#&#8203;8 0x00007f3594c0e21e (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/libLLVMSupport.so.40+0xbe21e)
#&#8203;9 0x00007f3594c0e53f llvm::raw_ostream::SetBuffered() (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/libLLVMSupport.so.40+0xbe53f)
#&#8203;10 0x00007f3594c0ecd3 llvm::raw_ostream::write(char const*, unsigned long) (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/libLLVMSupport.so.40+0xbecd3)
#&#8203;11 0x00007f35987b0bd6 (anonymous namespace)::GCOVProfiler::emitProfileNotes() [clone .constprop.327] (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/libLLVMInstrumentation.so.40+0x47bd6)
#&#8203;12 0x00007f35987b2118 (anonymous namespace)::GCOVProfilerLegacyPass::runOnModule(llvm::Module&) (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/libLLVMInstrumentation.so.40+0x49118)
#&#8203;13 0x00007f3595feda8d llvm::legacy::PassManagerImpl::run(llvm::Module&) (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/libLLVMCore.so.40+0x163a8d)
#&#8203;14 0x00007f359761fe07 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/libclangCodeGen.so.40+0x77e07)
#&#8203;15 0x00007f35977dc30e clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/libclangCodeGen.so.40+0x23430e)
#&#8203;16 0x00007f358ff99238 clang::ParseAST(clang::Sema&, bool, bool) (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/../lib/libclangParse.so.40+0x2c238)
#&#8203;17 0x00007f35977d7ac7 clang::CodeGenAction::ExecuteAction() (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/libclangCodeGen.so.40+0x22fac7)
#&#8203;18 0x00007f3596fc8fa6 clang::FrontendAction::Execute() (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/libclangFrontend.so.40+0xb2fa6)
#&#8203;19 0x00007f3596f920f6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/libclangFrontend.so.40+0x7c0f6)
#&#8203;20 0x00007f3596d148bb clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/../lib/libclangFrontendTool.so.40+0x38bb)
#&#8203;21 0x000000000040ff28 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/clang-4.0+0x40ff28)
#&#8203;22 0x000000000040e704 main (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/clang-4.0+0x40e704)
#&#8203;23 0x00007f3592acaf45 __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;24 0x000000000040ac29 _start (/sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/clang-4.0+0x40ac29)
Stack dump:
0.      Program arguments: /sarc-c/compiler_tmp/tools/cross/llvm-4.0/2016-10-11-23-30-38-80cf341-master/bin/clang-4.0 -cc1 -triple x86_64--linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name src.cxx -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -femit-coverage-notes -femit-coverage-data -coverage-notes-file /work/x.hu/build/libcxx_sharedptr_patch/benchmarks/benchmark-libcxx/src/google-benchmark-libcxx-build/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_944e3.dir/src.cxx.gcno -coverage-data-file /work/x.hu/build/libcxx_sharedptr_patch/benchmarks/benchmark-libcxx/src/google-benchmark-libcxx-build/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_944e3.dir/src.cxx.gcda -nostdinc++ -D HAVE_CXX_FLAG_COVERAGE -Wno-unused-command-line-argument -Wall -Wextra -Wshadow -Wshorten-64-to-32 -Wfloat-equal -Wstrict-aliasing -Wthread-safety -pedantic -pedantic-errors -std=c++11 -fdeprecated-macro -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -x c++ src-f47e53.cpp -v 
1.      <eof> parser at end of file
2.      Per-module optimization passes
3.      Running pass 'GCOV Profiler' on module 'src-f47e53.cpp'.
src-f47e53.sh: line 8: 26262 Aborted                 (core dumped) $CC "-cc1" "-triple" "x86_64--linux-gnu" "-emit-obj" "-mrelax-all" "-disable-free" "-main-file-name" "src.cxx" "-mrelocation-model" "static" "-mthread-model" "posix" "-mdisable-fp-elim" "-fmath-errno" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-fuse-init-array" "-target-cpu" "x86-64" "-dwarf-column-info" "-debugger-tuning=gdb" "-femit-coverage-notes" "-femit-coverage-data" "-coverage-notes-file" "/work/x.hu/build/libcxx_sharedptr_patch/benchmarks/benchmark-libcxx/src/google-benchmark-libcxx-build/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_944e3.dir/src.cxx.gcno" "-coverage-data-file" "/work/x.hu/build/libcxx_sharedptr_patch/benchmarks/benchmark-libcxx/src/google-benchmark-libcxx-build/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_944e3.dir/src.cxx.gcda" "-nostdinc++" "-D" "HAVE_CXX_FLAG_COVERAGE" "-Wno-unused-command-line-argument" "-Wall" "-Wextra" "-Wshadow" "-Wshorten-64-to-32" "-Wfloat-equal" "-Wstrict-aliasing" "-Wthread-safety" "-pedantic" "-pedantic-errors" "-std=c++11" "-fdeprecated-macro" "-ferror-limit" "19" "-fmessage-length" "0" "-fobjc-runtime=gcc" "-fcxx-exceptions" "-fexceptions" "-fdiagnostics-show-option" "-x" "c++" "src-f47e53.cpp" -v

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.9 and 4 with assertions enabled: https://cexplorer.testlabs.pro/z/Y8591f
