### ISSUE TITLE
Some tests fail when clang is build with only one, non host target

### ISSUE THREAD

**Issue by hyp** [llvm/llvm-project#30024]
|  |  |
| --- | --- |
| Bugzilla Link | [30676](https://llvm.org/bz30676) |
| Version | trunk |
| OS | All |
| CC | @hyp,@nigelp-xmos,@pogo59 |

## Extended Description 
When I build llvm and clang with only the XCore target and run clang's tests, I get 51 test failures (clang r284007):

Failing Tests (51):
    Clang :: ASTMerge/anonymous-fields.cpp
    Clang :: ASTMerge/codegen-body.c
    Clang :: CodeGen/2005-09-24-AsmUserPrefix.c
    Clang :: CodeGen/2009-04-23-dbg.c
    Clang :: CodeGen/2009-07-31-DbgDeclare.c
    Clang :: CodeGen/attribute-section-data-common.c
    Clang :: CodeGen/extern-weak.c
    Clang :: CodeGen/libcalls-fno-builtin.c
    Clang :: CodeGen/pointer-arithmetic.c
    Clang :: CodeGenCXX/2010-03-09-AnonAggregate.cpp
    Clang :: CodeGenCXX/crash.cpp
    Clang :: CodeGenCXX/debug-info-byval.cpp
    Clang :: CodeGenCXX/debug-info-ctor2.cpp
    Clang :: CodeGenCXX/debug-info-member.cpp
    Clang :: CodeGenCXX/debug-info-method-spec.cpp
    Clang :: CodeGenObjC/2007-05-02-Strong.m
    Clang :: CodeGenObjC/2009-01-21-invalid-debug-info.m
    Clang :: CodeGenObjC/blocks-ivar-debug.m
    Clang :: CodeGenObjC/debug-info-class-extension.m
    Clang :: CodeGenObjC/debug-info-class-extension2.m
    Clang :: CodeGenObjC/debug-info-class-extension3.m
    Clang :: CodeGenObjC/debug-info-linkagename.m
    Clang :: CodeGenObjC/debug-info-property.m
    Clang :: CodeGenObjC/debug-info-property2.m
    Clang :: CodeGenObjC/debug-info-property4.m
    Clang :: CodeGenObjC/debug-info-property5.m
    Clang :: CodeGenObjC/illegal-UTF8.m
    Clang :: CodeGenObjC/property-dbg.m
    Clang :: CodeGenOpenCL/denorms-are-zero.cl
    Clang :: Driver/cc-print-options.c
    Clang :: Driver/clang_f_opts.c
    Clang :: Driver/linker-opts.c
    Clang :: Driver/modules-ts.cpp
    Clang :: Driver/no-canonical-prefixes.c
    Clang :: Driver/output-file-cleanup.c
    Clang :: Driver/unknown-arg.c
    Clang :: Frontend/ir-support.c
    Clang :: Modules/DebugInfoSubmoduleImport.c
    Clang :: Modules/DebugInfoSubmodules.c
    Clang :: Modules/DebugInfoTransitiveImport.m
    Clang :: Modules/ExtDebugInfo.cpp
    Clang :: Modules/ExtDebugInfo.m
    Clang :: Modules/ModuleDebugInfo.cpp
    Clang :: Modules/ModuleDebugInfo.m
    Clang :: Modules/ModuleModuleDebugInfo.cpp
    Clang :: Modules/debug-info-moduleimport.m
    Clang :: Modules/module_file_info.m
    Clang :: PCH/debug-info-pch-path.c
    Clang :: SemaCUDA/exceptions-host-device.cu
    Clang :: SemaCUDA/vla-host-device.cu
    Clang :: SemaCXX/warn-unused-local-typedef-serialize.cpp

Run the following commands to reproduce this issue (on X86 host):

cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DLLVM_TARGETS_TO_BUILD="XCore" <PATH_TO_LLVM>
ninja check-clang

**Comment by Endilll** [comment]
Old failure building Clang. Unlikely to be relevant anymore.
