### ISSUE TITLE
Merge r281669 into 3.9.1 branch (allow vectors to be shifted by a scalar)

### ISSUE THREAD

**Issue by TNorthover** [llvm/llvm-project#30036]
|  |  |
| --- | --- |
| Bugzilla Link | [30688](https://llvm.org/bz30688) |
| Version | 3.9 |
| OS | All |
| Blocks | llvm/llvm-project#29609  |
| CC | @tstellar |

## Extended Description 
This particular patch looks like a pretty straightforward, though I did notice other changes to vector diagnostics that someone may want to consider too.

**Comment by asl** [comment]
It was either merged or certainly obsolete as of now
