### ISSUE TITLE
assertion failure on ambiguous qualifier in dependent member access, "Cannot handle ambiguities here yet"

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#30087]
|  |  |
| --- | --- |
| Bugzilla Link | [30739](https://llvm.org/bz30739) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Testcase:

```cpp
inline namespace N { struct X { int n; }; }
inline namespace M { struct X {}; }
struct Y : N::X {};
template<typename T> int f(T y) { return y.X::n; }
```

Result:

clang-3.5: lib/Sema/SemaCXXScopeSpec.cpp:370: clang::NamedDecl *clang::Sema::FindFirstQualifierInScope(clang::Scope *, clang::NestedNameSpecifier *): Assertion `!Found.isAmbiguous() && "Cannot handle ambiguities here yet"' failed.

**Comment by shafik** [comment]
Duplicate: https://github.com/llvm/llvm-project/issues/28556
