### ISSUE TITLE
llvm-cov timeout in buildbots may be caused by Unix signal implementation

### ISSUE THREAD

**Issue by rengolin** [llvm/llvm-project#30083]
|  |  |
| --- | --- |
| Bugzilla Link | [30735](https://llvm.org/bz30735) |
| Version | unspecified |
| OS | Linux |
| CC | @rovka,@vedantk |

## Extended Description 
Timeouts on check-all are getting slightly more common than they should. Example:

http://lab.llvm.org:8011/builders/clang-cmake-armv7-a15/builds/15968

and many other PPC and AArch64 builds out there.

While building it locally on AArch64, I noticed my tests were locked in the same way as we saw the buildbot once, with multiple instances of `llvm-cov` and zero CPU utilisation.

Here's a few error messages I've seen on my local build (that weren't on the buildbots, possibly because the timeout killed it first):

terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
#&#8203;0 0x0000ffff83f2e8ec llvm::sys::PrintStackTrace(llvm::raw_ostream&) llvm/lib/Support/Unix/Signals.inc:402:0

I'm not sure this is related, but it sure it weird, given that those errors weren't on `llvm-cov` itself, but on unrelated unit tests, like `VerifierTest.StripInvalidDebugInfoLegacy`.

**Comment by arsenm** [comment]
Old build issue that seems to have had fixes applied
