### ISSUE TITLE
clang-tidy -fix "fixes" code in template, inserts name of instantiated type

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#30110]
|  |  |
| --- | --- |
| Bugzilla Link | [30762](https://llvm.org/bz30762) |
| Version | unspecified |
| OS | All |
| Attachments | [Testcase for the bug](https://user-images.githubusercontent.com/60944935/143754583-b7040e9c-70fc-420c-94f3-120da140bc0f.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

The automatic fix for the "destructor is called, class has virtual members but no virtual destructor" warning can break templated code. Testcase is below & in attachment, when using -Wall -Wextra with the below code and running clang-tidy -fix it will add a qualification for to the "my_t->~T();" line, which is obviously wrong - it should not touch that template, other classes might be using it.

/* CMakeLists.txt for compile_commands.json 

cmake_minimum_required (VERSION 2.8.11)
project (HELLO)
set(CMAKE_EXPORT_COMPILE_COMMANDS on)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra")
add_executable(hello hello.cpp)
*/

/* hello.cpp */
#include <new>

template <typename T>
struct StupidContainer
{
    char* data;
    T* my_t;
    StupidContainer()
    {
        data = new char[sizeof(T)];
        my_t = reinterpret_cast<T*>(data);
        new (my_t) T();
    }
    ~StupidContainer()
    {
        my_t->~T();
        delete[] data;
    }

};

struct BuggyClass {
    virtual void f() {}
    ~BuggyClass() {}
};

int main()
{
    StupidContainer<BuggyClass> foobar;
}

**Comment by PiotrZSL** [comment]
This issue is about compiler warning:
```
 warning: destructor called on non-final 'BuggyClass' that has virtual functions but non-virtual destructor [clang-diagnostic-delete-non-abstract-non-virtual-dtor]
```

And looks like clang-tidy no longer fixes this issues (non for any clang-tidy check or compiler warning).
Closing, as issue no longer exist.
