### ISSUE TITLE
Rename DarwinDirective

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#30144]
|  |  |
| --- | --- |
| Bugzilla Link | [30796](https://llvm.org/bz30796) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @ecnelises,@hfinkel,@nemanjai |

## Extended Description 
DarwinDirective is used to specify which PPC CPU maps to the subtarget object. It has nothing to do with Darwin and should be renamed.

**Comment by arsenm** [comment]
Comment says this was done and darwin support was dropped from ppc anyway
