### ISSUE TITLE
In c++1z/gnu++1z mode clang crashed for code uses lambda defined inside lambda

### ISSUE THREAD

**Issue by tomilov** [llvm/llvm-project#30143]
|  |  |
| --- | --- |
| Bugzilla Link | [30795](https://llvm.org/bz30795) |
| Version | trunk |
| OS | Linux |
| Attachments | [preprocessed source](https://user-images.githubusercontent.com/92601325/143754601-6aff2f6c-c4dd-451c-a75d-11a7b79ba333.gz), [associated run script](https://user-images.githubusercontent.com/92601325/143754602-74f6f169-6214-4aa7-a5c2-33bf12ca1b97.gz) |
| CC | @tomilov |

## Extended Description 

Trying to compile the following code (in -std=gnu++1z and c++1z modes, but not in either c++14 or gnu++14):

# clang++ /tmp/a.cpp -std=gnu++1z -o /dev/null

int main()
{
    struct S { int i; };
    [] (auto i) -> S
    {
        auto l = [&] { return i; };
        return {l()};
    }(0);
}

If two statements fused into "return {[&] { return i; }()};" then code compiles without error.
Trying this on latest clang from trunk available (rev 285073) also get the same error.

#&#8203;0 0x0000000000f84635 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/bin/clang-4.0+0xf84635)
#&#8203;1 0x0000000000f84bc6 SignalHandler(int) (/usr/local/bin/clang-4.0+0xf84bc6)
#&#8203;2 0x00007f96405433d0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x113d0)
#&#8203;3 0x00007f963f199e1e /build/glibc-GKVZIf/glibc-2.23/string/../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:38:0
#&#8203;4 0x000000000246f649 (anonymous namespace)::IntExprEvaluator::Success(llvm::APSInt const&, clang::Expr const*, clang::APValue&) (/usr/local/bin/clang-4.0+0x246f649)
#&#8203;5 0x000000000247a468 (anonymous namespace)::IntExprEvaluator::VisitCastExpr(clang::CastExpr const*) (/usr/local/bin/clang-4.0+0x247a468)
#&#8203;6 0x00000000024685da clang::StmtVisitorBase<clang::make_const_ptr, (anonymous namespace)::IntExprEvaluator, bool>::Visit(clang::Stmt const*) (/usr/local/bin/clang-4.0+0x24685da)
#&#8203;7 0x0000000002450de9 Evaluate(clang::APValue&, (anonymous namespace)::EvalInfo&, clang::Expr const*) (/usr/local/bin/clang-4.0+0x2450de9)
#&#8203;8 0x000000000246416f EvaluateStmt((anonymous namespace)::StmtResult&, (anonymous namespace)::EvalInfo&, clang::Stmt const*, clang::SwitchCase const*) (/usr/local/bin/clang-4.0+0x246416f)
#&#8203;9 0x0000000002463a3f EvaluateStmt((anonymous namespace)::StmtResult&, (anonymous namespace)::EvalInfo&, clang::Stmt const*, clang::SwitchCase const*) (/usr/local/bin/clang-4.0+0x2463a3f)
#&#8203;10 0x00000000024522de HandleFunctionCall(clang::SourceLocation, clang::FunctionDecl const*, (anonymous namespace)::LValue const*, llvm::ArrayRef<clang::Expr const*>, clang::Stmt const*, (anonymous namespace)::EvalInfo&, clang::APValue&, (anonymous namespace)::LValue const*) (/usr/local/bin/clang-4.0+0x24522de)
#&#8203;11 0x0000000002479ae4 (anonymous namespace)::ExprEvaluatorBase<(anonymous namespace)::IntExprEvaluator>::handleCallExpr(clang::CallExpr const*, clang::APValue&, (anonymous namespace)::LValue const*) (/usr/local/bin/clang-4.0+0x2479ae4)
#&#8203;12 0x000000000246d35a (anonymous namespace)::IntExprEvaluator::VisitCallExpr(clang::CallExpr const*) (/usr/local/bin/clang-4.0+0x246d35a)
#&#8203;13 0x00000000024678b3 clang::StmtVisitorBase<clang::make_const_ptr, (anonymous namespace)::IntExprEvaluator, bool>::Visit(clang::Stmt const*) (/usr/local/bin/clang-4.0+0x24678b3)
#&#8203;14 0x0000000002450de9 Evaluate(clang::APValue&, (anonymous namespace)::EvalInfo&, clang::Expr const*) (/usr/local/bin/clang-4.0+0x2450de9)
#&#8203;15 0x000000000244eff5 EvaluateInPlace(clang::APValue&, (anonymous namespace)::EvalInfo&, (anonymous namespace)::LValue const&, clang::Expr const*, bool) (/usr/local/bin/clang-4.0+0x244eff5)
#&#8203;16 0x000000000247fce0 clang::StmtVisitorBase<clang::make_const_ptr, (anonymous namespace)::RecordExprEvaluator, bool>::Visit(clang::Stmt const*) (/usr/local/bin/clang-4.0+0x247fce0)
#&#8203;17 0x000000000245147e Evaluate(clang::APValue&, (anonymous namespace)::EvalInfo&, clang::Expr const*) (/usr/local/bin/clang-4.0+0x245147e)
#&#8203;18 0x000000000244dc5a EvaluateAsRValue((anonymous namespace)::EvalInfo&, clang::Expr const*, clang::APValue&) (/usr/local/bin/clang-4.0+0x244dc5a)
#&#8203;19 0x000000000244da2f clang::Expr::EvaluateAsRValue(clang::Expr::EvalResult&, clang::ASTContext const&) const (/usr/local/bin/clang-4.0+0x244da2f)
#&#8203;20 0x000000000244f401 clang::Expr::isEvaluatable(clang::ASTContext const&, clang::Expr::SideEffectsKind) const (/usr/local/bin/clang-4.0+0x244f401)
#&#8203;21 0x00000000010e90a4 clang::CodeGen::CodeGenFunction::EmitReturnStmt(clang::ReturnStmt const&) (/usr/local/bin/clang-4.0+0x10e90a4)
#&#8203;22 0x00000000010e6dc6 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*) (/usr/local/bin/clang-4.0+0x10e6dc6)
#&#8203;23 0x00000000010ee2fc clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/usr/local/bin/clang-4.0+0x10ee2fc)
#&#8203;24 0x00000000011159a7 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::CodeGen::FunctionArgList&, clang::Stmt const*) (/usr/local/bin/clang-4.0+0x11159a7)
#&#8203;25 0x00000000011162d7 clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/usr/local/bin/clang-4.0+0x11162d7)
#&#8203;26 0x0000000001126f6f clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/usr/local/bin/clang-4.0+0x1126f6f)
#&#8203;27 0x0000000001122e98 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/usr/local/bin/clang-4.0+0x1122e98)
#&#8203;28 0x000000000111e1b3 clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/bin/clang-4.0+0x111e1b3)
#&#8203;29 0x000000000111d849 clang::CodeGen::CodeGenModule::Release() (/usr/local/bin/clang-4.0+0x111d849)
#&#8203;30 0x00000000016cb055 (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) (/usr/local/bin/clang-4.0+0x16cb055)
#&#8203;31 0x00000000016ca204 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/usr/local/bin/clang-4.0+0x16ca204)
#&#8203;32 0x0000000001aab7e5 clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/bin/clang-4.0+0x1aab7e5)
#&#8203;33 0x00000000013ad6fd clang::FrontendAction::Execute() (/usr/local/bin/clang-4.0+0x13ad6fd)
#&#8203;34 0x000000000137aa08 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/bin/clang-4.0+0x137aa08)
#&#8203;35 0x0000000001423811 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/bin/clang-4.0+0x1423811)
#&#8203;36 0x0000000000753f85 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/bin/clang-4.0+0x753f85)
#&#8203;37 0x0000000000752a78 main (/usr/local/bin/clang-4.0+0x752a78)
#&#8203;38 0x00007f963f11b830 __libc_start_main /build/glibc-GKVZIf/glibc-2.23/csu/../csu/libc-start.c:325:0
#&#8203;39 0x000000000074ff29 _start (/usr/local/bin/clang-4.0+0x74ff29)
Stack dump:
0.	Program arguments: /usr/local/bin/clang-4.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name a.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -resource-dir /usr/local/bin/../lib/clang/4.0.0 -cxx-isystem /home/user/variant/include -cxx-isystem /home/user/eggs-variant/include -cxx-isystem /home/user/insituc/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.1/../../../../include/c++/5.4.1 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.1/../../../../include/x86_64-linux-gnu/c++/5.4.1 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.1/../../../../include/x86_64-linux-gnu/c++/5.4.1 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.1/../../../../include/c++/5.4.1/backward -internal-isystem /usr/local/include -internal-isystem /usr/local/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=gnu++1z -fdeprecated-macro -fdebug-compilation-dir /home/user/sweepline -ferror-limit 19 -fmessage-length 204 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/a-38e8f1.o -x c++ /tmp/a.cpp 
1.	<eof> parser at end of file
2.	Per-file LLVM IR generation
3.	/tmp/a.cpp:4:5: Generating code for declaration 'main()::(anonymous class)::operator()'
clang-4.0: error: unable to execute command: Segmentation fault (core dumped)
clang-4.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0 (trunk 282683)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
clang-4.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-4.0: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-4.0: note: diagnostic msg: /tmp/a-d88c26.cpp
clang-4.0: note: diagnostic msg: /tmp/a-d88c26.sh
clang-4.0: note: diagnostic msg: 

********************

**Comment by Endilll** [comment]
Can't reproduce both test cases using Clang 3.9 and 4:
https://godbolt.org/z/Eosc7rYcb
https://godbolt.org/z/9z4911WYr
