### ISSUE TITLE
Linker error: undefined reference to `std::vector<...>::~vector()

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#30168]
|  |  |
| --- | --- |
| Bugzilla Link | [30820](https://llvm.org/bz30820) |
| Version | 3.9 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
Hi

I have recently encountered the problem of compiling some code which uses std::vector class. Here is the minimal example which reproduces the problem:

#include <vector>

template <typename I>
void f(I i, const std::vector<int> & v = { 1, 2, 3}) {
}

int main(int , char**) {
  f(1);
}

Here is the compiler output:

:> clang++ -std=c++14 t.cc
/tmp/kolos/ttt-460d3b.o: In function `main':
ttt.cc:(.text+0x61): undefined reference to `std::vector<int,
std::allocator<int> >::~vector()'
ttt.cc:(.text+0x92): undefined reference to `std::vector<int,
std::allocator<int> >::~vector()'
clang-3.9: error: linker command failed with exit code 1 (use -v to see
invocation)

Here are the system and compiler details

:> clang++ -v
clang version 3.9.0 (tags/RELEASE_390/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /external/llvm/3.9/x86_64-slc6/bin
Found candidate GCC installation:
/contrib/gcc/4.9/x86_64-slc6/lib/gcc/x86_64-unknown-linux-gnu/4.9.3
Selected GCC installation:
/contrib/gcc/4.9/x86_64-slc6/lib/gcc/x86_64-unknown-linux-gnu/4.9.3
Candidate multilib: .;@m64
Selected multilib: .;@m64

:> uname -a
Linux 2.6.32-642.6.1.el6.x86_64 #&#8203;1 SMP Wed Oct 5 16:49:07 CEST 2016 x86_64
x86_64 x86_64 GNU/Linux

**Comment by wheatman** [comment]
seems to have been fixed for 4.0.0
https://godbolt.org/z/8bEq8zK8f

for reference

code 
```
#include <vector>

template <typename I>
void f(I i, const std::vector<int> & v = { 1, 2, 3}) {
}

int main(int , char**) {
  f(1);
}
```

linker error
```
ASM generation compiler returned: 0
/tmp/example-1ad201.o: In function `main':
<source>:8: undefined reference to `std::vector<int, std::allocator<int> >::~vector()'
<source>:8: undefined reference to `std::vector<int, std::allocator<int> >::~vector()'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
Execution build compiler returned: 1
```
