### ISSUE TITLE
clang-format doesn't recognize access modifiers expanded by preprocessor?

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#30197]
|  |  |
| --- | --- |
| Bugzilla Link | [30849](https://llvm.org/bz30849) |
| Version | 3.8 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Input:

#define _PRIVATE private
class x {
public:
  int y;

_PRIVATE:
  int z;
};

Bad output:

#define _PRIVATE private
class x {
public:
  int y;

  _PRIVATE : int z;
};

Desired output to treat a 'private' expanded from a macro the same as a bare 'private', i.e.

#define _PRIVATE private
class x {
public:
  int y;

_PRIVATE:
  int z;
};

The use case is "developers who need to be able to build a codebase with private changed to public sometimes, and use a preprocessor definition to do the dirty deed".

The codebase in question is 322KLOC, and this is the only showstopper for
using clang-format as the automated formatter for every commit.

Tested with 
clang-format version 3.8.0-2ubuntu4 (the default clang-format on ubuntu 16.04)

**Comment by mydeveloperday** [comment]
We have to be realistic here we are never going to fix this issue.

1) We cannot necessarily see the macro definition to expand it (we don't preprocess)
2) Even if we could we'd have to put it in place, format it, work out the correct indentation then remove it

This would be better handled by having `AccessModifiersMacros` setting and then you use

_PRIVATE_NOT_PRIVATE

but I still wouldn't put the whole class thing in the macro as that is really pretty horrible.. so I'm marking this as won't fix
