### ISSUE TITLE
Parallel cmake/gmake build fails with random errors

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#30226]
|  |  |
| --- | --- |
| Bugzilla Link | [30878](https://llvm.org/bz30878) |
| Version | trunk |
| OS | FreeBSD |

## Extended Description 
Build that runs long on single CPU quickly fails on multiple CPUs with random errors which don't occur in single CPU build.

> cd ../cmake -G "Unix Makefiles" ../llvm -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/opt/llvm/current
> cmake -G "Unix Makefiles" ../llvm -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/opt/llvm/current
> gmake -j 10

on FreeBSD 11.

**Comment by arsenm** [comment]
Old build issue
