### ISSUE TITLE
memcpyopt doesn't zap an alloca + memmove

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#3027]
|  |  |
| --- | --- |
| Bugzilla Link | [2655](https://llvm.org/bz2655) |
| Version | 1.0 |
| OS | All |
| CC | @efriedma-quic |

## Extended Description 
In this case, memcpyopt should "out->replaceAllUsesWith(agg.result)" and then nuke the memmove as an identity memmove:

target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:128:128"
target triple = "i686-pc-linux-gnu"
	%struct.out = type <{ i32, i32 }>

define void @&#8203;foo(%struct.out* sret %agg.result) {
entry:
	%out = alloca %struct.out, align 4		; <%struct.out*> [#uses=3]
	%tmp = getelementptr %struct.out* %out, i32 0, i32 0		; <i32*> [#uses=1]
	%call = call i32 @&#8203;bar( )		; <i32> [#uses=1]
	store i32 %call, i32* %tmp
	%tmp1 = getelementptr %struct.out* %out, i32 0, i32 1		; <i32*> [#uses=1]
	%call2 = call i32 @&#8203;bar( )		; <i32> [#uses=1]
	store i32 %call2, i32* %tmp1
	%tmp3 = bitcast %struct.out* %agg.result to i8*		; <i8*> [#uses=1]
	%tmp4 = bitcast %struct.out* %out to i8*		; <i8*> [#uses=1]
	call void @&#8203;llvm.memmove.i32( i8* %tmp3, i8* %tmp4, i32 8, i32 4 )
	ret void
}

declare void @&#8203;llvm.memmove.i32(i8*, i8*, i32, i32) nounwind

declare i32 @&#8203;bar()

This produces:

define void @&#8203;foo(%struct.out* sret %agg.result) {
entry:
	%call = call i32 @&#8203;bar( )		; <i32> [#uses=1]
	%call2 = call i32 @&#8203;bar( )		; <i32> [#uses=1]
	%tmp3 = bitcast %struct.out* %agg.result to i8*		; <i8*> [#uses=0]
	%agg.result.0 = getelementptr %struct.out* %agg.result, i32 0, i32 0		; <i32*> [#uses=1]
	store i32 %call, i32* %agg.result.0
	%agg.result.1 = getelementptr %struct.out* %agg.result, i32 0, i32 1		; <i32*> [#uses=1]
	store i32 %call2, i32* %agg.result.1
	ret void
}

**Comment by arsenm** [comment]
Modernized testcase:

```
target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:128:128"
target triple = "i686-pc-linux-gnu"

%struct.out = type <{ i32, i32 }>

define void @foo(ptr sret(%struct.out) %agg.result) {
entry:
  %out = alloca %struct.out, align 4
  %tmp = getelementptr %struct.out, ptr %out, i32 0, i32 0
  %call = call i32 @bar()
  store i32 %call, ptr %tmp, align 4
  %tmp1 = getelementptr %struct.out, ptr %out, i32 0, i32 1
  %call2 = call i32 @bar()
  store i32 %call2, ptr %tmp1, align 4
  %tmp3 = bitcast ptr %agg.result to ptr
  %tmp4 = bitcast ptr %out to ptr
  call void @llvm.memcpy.p0.p0.i32(ptr align 4 %tmp3, ptr align 4 %tmp4, i32 8, i1 false)
  ret void
}

declare i32 @bar()

; Function Attrs: nocallback nofree nounwind willreturn memory(argmem: readwrite)
declare void @llvm.memmove.p0.p0.i32(ptr nocapture writeonly, ptr nocapture readonly, i32, i1 immarg) #0

; Function Attrs: nocallback nofree nounwind willreturn memory(argmem: readwrite)
declare void @llvm.memcpy.p0.p0.i32(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i32, i1 immarg) #0

attributes #0 = { nocallback nofree nounwind willreturn memory(argmem: readwrite) }

```

**Comment by nikic** [comment]
This will already be optimized by SROA -- I'm not sure there is anything to do here? At least this needs a better test case to clarify what the request is.

**Comment by lattner** [comment]
I don't think there is any great need to hold onto this bug.
