### ISSUE TITLE
const is stuck to postfix increment/decrement

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#30305]
|  |  |
| --- | --- |
| Bugzilla Link | [30957](https://llvm.org/bz30957) |
| Version | 3.9 |
| OS | All |
| Attachments | [formatting options](https://user-images.githubusercontent.com/60944935/143754675-8d1d5e59-6a82-4ea5-95d0-c1133a633aed.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

The following code:

class A
{
  A& operator++();
  A operator++(int) const;
  A& operator--();
  A operator--(int) const;
};

is formatted as

class A
{
    A& operator++();
    A operator++(int)const;
    A& operator--();
    A operator--(int)const;
};

**Comment by mydeveloperday** [comment]
This issue seems to be resolved some time prior to v8

```
class A {
  A &operator++();
  A operator++(int) const;
  A &operator--();
  A operator--(int) const;
};
```
