### ISSUE TITLE
CodeGen should support arbitrary return types

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#3032]
|  |  |
| --- | --- |
| Bugzilla Link | [2660](https://llvm.org/bz2660) |
| Version | unspecified |
| OS | All |
| Attachments | [IR file that will crash lli](https://user-images.githubusercontent.com/60944935/143738188-7010072b-ec8b-463d-9a62-64e3434b006e.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lattner,@isanbard,@sunfishcode,@nlewycky |

## Extended Description 

I've been using the new first-class aggregate support quite a bit, and I ran into a crash bug. I've isolated a small test case which I will attach. This is on the latest trunk from August 10.

**Comment by arsenm** [comment]
This already works by implicitly converting types that don't fit in registers to sret
