### ISSUE TITLE
check-lldb always fails on an Ubuntu 14.04 machine

### ISSUE THREAD

**Issue by pcc** [llvm/llvm-project#30330]
|  |  |
| --- | --- |
| Bugzilla Link | [30982](https://llvm.org/bz30982) |
| Version | unspecified |
| OS | Linux |
| CC | @labath |

## Extended Description 
Testing: 557 test suites, 40 threads
 83 out of 557 test suites processed - TestDataFormatterScript.py                 

Session logs for test failures/errors/unexpected successes will go into directory '[...]/ra/lldb-test-traces'
Command invoked: [...]/llvm/tools/lldb/test/dotest.py -q --arch=x86_64 --executable [...]/ra/bin/lldb-4.0.0 -s [...]/ra/lldb-test-traces -S nm -u CXXFLAGS -u CFLAGS -C /usr/bin/clang --results-port 48706 -S nm --inferior -p TestLibCxxAtomic.py [...]/lldb/packages/Python/lldbsuite/test --event-add-entries worker_index=12:int
FAIL: LLDB (/usr/lib/llvm-3.6/bin/clang-x86_64) :: test_dwarf (TestLibCxxAtomic.LibCxxAtomicTestCase)
FAIL: LLDB (/usr/lib/llvm-3.6/bin/clang-x86_64) :: test_dwo (TestLibCxxAtomic.LibCxxAtomicTestCase)
======================================================================
ERROR: test_dwarf (TestLibCxxAtomic.LibCxxAtomicTestCase)
   Test that std::atomic as defined by libc++ is correctly printed by LLDB
----------------------------------------------------------------------
Error when building test subject.

Build Command:
make MAKE_DSYM=NO ARCH=x86_64 CC="/usr/bin/clang" 

Build Command Output:
main.o: In function `std::atomic<S>::store(S, std::memory_order)':
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/atomic:199: undefined reference to `__atomic_store_8'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [a.out] Error 1

Test Directory:
[...]/lldb/packages/Python/lldbsuite/test/functionalities/data-formatter/data-formatter-stl/libcxx/atomic
======================================================================
ERROR: test_dwo (TestLibCxxAtomic.LibCxxAtomicTestCase)
   Test that std::atomic as defined by libc++ is correctly printed by LLDB
----------------------------------------------------------------------
Error when building test subject.

Build Command:
make MAKE_DSYM=NO MAKE_DWO=YES ARCH=x86_64 CC="/usr/bin/clang" 

Build Command Output:
clang: warning: argument unused during compilation: '-gsplit-dwarf'
main.o: In function `std::atomic<S>::store(S, std::memory_order)':
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/atomic:199: undefined reference to `__atomic_store_8'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [a.out] Error 1

Test Directory:
[...]/lldb/packages/Python/lldbsuite/test/functionalities/data-formatter/data-formatter-stl/libcxx/atomic
----------------------------------------------------------------------
Ran 2 tests in 0.959s

RESULT: FAILED (0 passes, 0 failures, 2 errors, 0 skipped, 0 expected failures, 0 unexpected successes)

[TestLibCxxAtomic.py FAILED]
Command invoked: /usr/bin/python2.7 [...]/llvm/tools/lldb/test/dotest.py -q --arch=x86_64 --executable [...]/ra/bin/lldb-4.0.0 -s [...]/ra/lldb-test-traces -S nm -u CXXFLAGS -u CFLAGS -C /usr/bin/clang --results-port 48706 -S nm --inferior -p TestLibCxxAtomic.py [...]/lldb/packages/Python/lldbsuite/test --event-add-entries worker_index=12:int
557 out of 557 test suites processed - TestTsanThreadNumbers.py                                  
=============
Issue Details
=============
ERROR: test_dwarf (functionalities/data-formatter/data-formatter-stl/libcxx/atomic/TestLibCxxAtomic.py)
ERROR: test_dwo (functionalities/data-formatter/data-formatter-stl/libcxx/atomic/TestLibCxxAtomic.py)
UNEXPECTED SUCCESS: test_continue_in_watchpoint_command_dwarf (functionalities/watchpoint/watchpoint_commands/command/TestWatchpointCommandPython.py)
UNEXPECTED SUCCESS: test_continue_in_watchpoint_command_dwo (functionalities/watchpoint/watchpoint_commands/command/TestWatchpointCommandPython.py)
UNEXPECTED SUCCESS: test_dwarf (functionalities/asan/TestMemoryHistory.py)
UNEXPECTED SUCCESS: test_dwarf (functionalities/thread/exit_during_break/TestExitDuringBreak.py)
UNEXPECTED SUCCESS: test_dwarf (functionalities/asan/TestReportData.py)
UNEXPECTED SUCCESS: test_dwo (functionalities/thread/exit_during_break/TestExitDuringBreak.py)
UNEXPECTED SUCCESS: test_dwo (functionalities/asan/TestMemoryHistory.py)
UNEXPECTED SUCCESS: test_dwo (functionalities/asan/TestReportData.py)
UNEXPECTED SUCCESS: test_process_interrupt_dwarf (functionalities/thread/state/TestThreadStates.py)
UNEXPECTED SUCCESS: test_sb_api_listener_resume_dwarf (api/multithreaded/TestMultithreaded.py)
UNEXPECTED SUCCESS: test_sb_api_listener_resume_dwo (api/multithreaded/TestMultithreaded.py)
UNEXPECTED SUCCESS: test_with_dwarf (lang/cpp/printf/TestPrintf.py)
UNEXPECTED SUCCESS: test_with_dwo (lang/cpp/printf/TestPrintf.py)

===================
Test Result Summary
===================
Test Methods:       1870
Reruns:                0
Success:            1146
Expected Failure:     91
Failure:               0
Error:                 2
Exceptional Exit:      0
Unexpected Success:   13
Skip:                618
Timeout:               0
Expected Timeout:      0

**Comment by arsenm** [comment]
Old build issue
