### ISSUE TITLE
OCaml binding memory crash

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#30356]
|  |  |
| --- | --- |
| Bugzilla Link | [31008](https://llvm.org/bz31008) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
According to the manual (https://caml.inria.fr/pub/docs/manual-ocaml/intfc.html)'s Rule 5, block must be filled by direct assignment after "caml_alloc_small".

```
Rule 5   After a structured block (a block with tag less than No_scan_tag) is allocated with the low-level functions, all fields of this block must be filled with well-formed values before the next allocation operation. If the block has been allocated with caml_alloc_small, filling is performed by direct assignment to the fields of the block:

        Field(v, n) = vn;
```

However, in the code below, there does not exist such assignment.
https://github.com/llvm-mirror/llvm/blob/master/bindings/ocaml
/llvm/llvm_ocaml.c#L483
https://github.com/llvm-mirror/llvm/blob/master/bindings/ocaml/llvm/llvm_ocaml.c#L630

This actually led to memory crash, and following patch solved it.
```
     result = caml_alloc_small(1, 0);
+    Field(result,0) = Val_int(0);
     Store_field(result, 0, caml_copy_string(C));
```

**Comment by jberdine** [comment]
fixed by 6f77926f464b6834339895e295f295953686af22
