### ISSUE TITLE
Assertion `Index.getValueType() == MVT::i32 && "Expect to be extending 32-bit registers for use in LEA"' failed

### ISSUE THREAD

**Issue by Vsevolod-Livinskij** [llvm/llvm-project#30392]
|  |  |
| --- | --- |
| Bugzilla Link | [31044](https://llvm.org/bz31044) |
| Version | trunk |
| OS | Linux |
| Attachments | [Reduced reproducer.](https://user-images.githubusercontent.com/92601286/143754711-870bd31a-f612-4cc3-a807-2b73b0eeb455.gz), [Original reproducer](https://user-images.githubusercontent.com/92601286/143754712-c43295b8-f467-4d52-80e6-836442c25c16.gz) |
| CC | @dbabokin,@zmodem,@igor-breger,@RKSimon,@Vsevolod-Livinskij,@ZviRackover |

## Extended Description 

Clang crashes with assertion.
Reproducer:
int a, d, e, f, g, h, p;
long i;
char j;
struct q {
  int k : 3;
};
struct r {
  q l;
};
struct s {
  unsigned m : 23;
};
r n;
s o;
void t() {
  int b(o.m + (o.m - 3516209982) - (n.l.k + e));
  g = o.m >= b;
  if (60151248080599800 - j)
    f = 0;
  else
    int c = d || ~a;
  if (o.m + (o.m - 3516209982U - (n.l.k + e)) - (6 - h) + i)
    p = o.m + (o.m - 3516209982 - (n.l.k + e));
}

LLVM version:
clang version 4.0.0 (trunk 286273)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/vlivinsk/workspace/llvm/bin-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

Error:
>$ clang++ -std=c++11 -O3 -c repr.cpp
clang-4.0: /home/vlivinsk/workspace/llvm/llvm-trunk/lib/Target/X86/X86ISelDAGToDAG.cpp:1605: bool {anonymous}::X86DAGToDAGISel::selectLEA64_32Addr(llvm::SDValue, llvm::SDValue&, llvm::SDValue&, llvm::SDValue&, llvm::SDValue&, llvm::SDValue&): Assertion `Index.getValueType() == MVT::i32 && "Expect to be extending 32-bit registers for use in LEA"' failed.
#&#8203;0 0x0000000001441b08 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x1441b08)
#&#8203;1 0x000000000143f75e llvm::sys::RunSignalHandlers() (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x143f75e)
#&#8203;2 0x000000000143f8d2 SignalHandler(int) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x143f8d2)
#&#8203;3 0x00007f99878003e0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x113e0)
#&#8203;4 0x00007f998679c428 gsignal /build/glibc-Qz8a69/glibc-2.23/signal/../sysdeps/unix/sysv/linux/raise.c:54:0
#&#8203;5 0x00007f998679e02a abort /build/glibc-Qz8a69/glibc-2.23/stdlib/abort.c:91:0
#&#8203;6 0x00007f9986794bd7 __assert_fail_base /build/glibc-Qz8a69/glibc-2.23/assert/assert.c:92:0
#&#8203;7 0x00007f9986794c82 (/lib/x86_64-linux-gnu/libc.so.6+0x2dc82)
#&#8203;8 0x00000000009eea22 (anonymous namespace)::X86DAGToDAGISel::CheckComplexPattern(llvm::SDNode*, llvm::SDNode*, llvm::SDValue, unsigned int, llvm::SmallVectorImpl<std::pair<llvm::SDValue, llvm::SDNode*> >&) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x9eea22)
#&#8203;9 0x0000000001b3b56e llvm::SelectionDAGISel::SelectCodeCommon(llvm::SDNode*, unsigned char const*, unsigned int) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x1b3b56e)
#&#8203;10 0x00000000009ea10f (anonymous namespace)::X86DAGToDAGISel::Select(llvm::SDNode*) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x9ea10f)
#&#8203;11 0x0000000001b33f75 llvm::SelectionDAGISel::DoInstructionSelection() (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x1b33f75)
#&#8203;12 0x0000000001b37daf llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x1b37daf)
#&#8203;13 0x0000000001b4230c llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x1b4230c)
#&#8203;14 0x0000000001b44529 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) [clone .part.722] [clone .constprop.746] (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x1b44529)
#&#8203;15 0x00000000009eecf4 (anonymous namespace)::X86DAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x9eecf4)
#&#8203;16 0x0000000000d3e475 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0xd3e475)
#&#8203;17 0x000000000104b4d3 llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x104b4d3)
#&#8203;18 0x000000000104b59c llvm::FPPassManager::runOnModule(llvm::Module&) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x104b59c)
#&#8203;19 0x000000000104b03d llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x104b03d)
#&#8203;20 0x00000000015cfb58 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x15cfb58)
#&#8203;21 0x0000000001c06bf3 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x1c06bf3)
#&#8203;22 0x0000000001fe9f28 clang::ParseAST(clang::Sema&, bool, bool) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x1fe9f28)
#&#8203;23 0x0000000001c02039 clang::CodeGenAction::ExecuteAction() (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x1c02039)
#&#8203;24 0x00000000019181e6 clang::FrontendAction::Execute() (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x19181e6)
#&#8203;25 0x00000000018ea416 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x18ea416)
#&#8203;26 0x000000000199dbc2 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x199dbc2)
#&#8203;27 0x0000000000922cb8 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x922cb8)
#&#8203;28 0x00000000008e5104 main (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x8e5104)
#&#8203;29 0x00007f9986787830 __libc_start_main /build/glibc-Qz8a69/glibc-2.23/csu/../csu/libc-start.c:325:0
#&#8203;30 0x000000000091f689 _start (/home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0+0x91f689)
Stack dump:
0.      Program arguments: /home/vlivinsk/workspace/llvm/bin-trunk/bin/clang-4.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -main-file-name repr.cpp -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -momit-leaf-frame-pointer -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /home/vlivinsk/workspace/yarpgen/found/scalar/clang/S_682650922/repr.gcno -resource-dir /home/vlivinsk/workspace/llvm/bin-trunk/bin/../lib/clang/4.0.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward -internal-isystem /usr/local/include -internal-isystem /home/vlivinsk/workspace/llvm/bin-trunk/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /home/vlivinsk/workspace/yarpgen/found/scalar/clang/S_682650922 -ferror-limit 19 -fmessage-length 135 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o repr.o -x c++ repr.cpp
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'repr.cpp'.
4.      Running pass 'X86 DAG->DAG Instruction Selection' on function '@_Z1tv'
clang-4.0: error: unable to execute command: Aborted (core dumped)
clang-4.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0 (trunk 286273)
Target: x86_64-unknown-linux-gnu
Thread model: posix

**Comment by Endilll** [comment]
The first test case appears to be fixed in Clang 5: https://godbolt.org/z/Wc5TYbf75
The second test case doesn't reproduce using Clang 7 and 8: https://godbolt.org/z/zPn88src8
