### ISSUE TITLE
Braced-init-list misformatted with AlignAfterOpenBracket=AlwaysBreak

### ISSUE THREAD

**Issue by griwes** [llvm/llvm-project#30463]
|  |  |
| --- | --- |
| Bugzilla Link | [31115](https://llvm.org/bz31115) |
| Version | trunk |
| OS | Linux |
| Attachments | [an example](https://user-images.githubusercontent.com/92601853/143754743-b313df9e-91fc-4aed-bec3-28d44f7e9cbf.gz) |

## Extended Description 

It seems that AlwaysBreak is disregarded for braced-init-lists, and instead Align is used when either Align or AlwaysBreak are specified for AlignAfterOpenBracket.

An example is attached. The config I'm using to run clang-format (reduced to the necessary options) is:

    -style='{BasedOnStyle: WebKit, AlignAfterOpenBracket: AlwaysBreak, ColumnLimit: 80, BinPackArguments: false, Cpp11BracedListStyle: true}'

(Cpp11BracedListStyle doesn't matter; the only thing it changes is that with it, the BinPackArguments option is respected. It'd be nice if it was possible to respect it *without* removing the spaces from within the braces, but that's not important here.)

The second line in main() in the example yields the expected result:

    std::vector<int> foo(
        verylongname,
        verylongname,
        verylongname,
        verylongname,
        verylongname,
        verylongname,
        verylongname,
        verylongname,
        verylongname,
        verylongname,
        verylongname,
        verylongname,
        verylongname);

(This is obviously invalid code, but it illustrates the point.) The first line, however, completely disregards AlignAfterOpenBracket=AlwaysBreak:

    std::vector<int> foo{verylongname,
                         verylongname,
                         verylongname,
                         verylongname,
                         verylongname,
                         verylongname,
                         verylongname,
                         verylongname,
                         verylongname,
                         verylongname,
                         verylongname,
                         verylongname,
                         verylongname};

while the expected result is the same as for the second line, only with braces instead of parentheses.

It wouldn't be *very* bad if not for some of my test files that construct literals corresponding to an AST parsed by the tested code, which causes it to be completely unreadable with Align. I *could* (and I guess I'll have to, for now) run two configs, one for the tests that disables this and one for normal code where this bug doesn't hurt readability that much (but does hurt it nevertheless), but it's not very nice.

**Comment by rymiel** [comment]
This was fixed in clang-format 10
