### ISSUE TITLE
unsigned integer overflow in murmur2_or_cityhash<_Size, 64>::__hash_len_17_to_32

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#30479]
|  |  |
| --- | --- |
| Bugzilla Link | [31131](https://llvm.org/bz31131) |
| Version | unspecified |
| OS | All |
| CC | @eugenis,@mclow |

## Extended Description 
I am hitting a 

include/c++/v1/memory:3139:46: runtime error: unsigned integer overflow: 8751185004910830951 * 13011662864482103923 cannot be represented in type 'unsigned long'
SUMMARY: AddressSanitizer: undefined-behavior include/c++/v1/memory:3139:46 in 

The function seems to be: 

__murmur2_or_cityhash<_Size, 64>::__hash_len_17_to_32(const char *__s, _Size __len).

Since it is a hash function, I would guess that the unsigned integer overflow is intentional, and the signature is missing the:

_LIBCPP_DISABLE_UBSAN_UNSIGNED_INTEGER_CHECK

annotation.

**Comment by philnik777** [comment]
The attribute has been added to the hashing functions.
