### ISSUE TITLE
[inline asm] Memory operand arithmetics support

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#30478]
|  |  |
| --- | --- |
| Bugzilla Link | [31130](https://llvm.org/bz31130) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @RKSimon |

## Extended Description 
Memory operand arithmetics are not supported and crashes llvm

int main(){
        __asm   lea     rcx, [rdi * (1<<2) ]
        __asm   lea     rcx, [rdi * (2*2) ]
        return 0;
}

the part of (1<<2) or (2*2) isn't supported, gcc and icc however are supporting this kinds of calculations.
it does however works for IMM operands.

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.9 and 4: https://godbolt.org/z/z9aoj99ff
