### ISSUE TITLE
opt crashes with "opt -globals-aa -lcssa -functionattrs -rpo-functionattrs": Assertion `ResultPass && "getAnalysis*() called on an analysis that was not " "'required' by pass!"' failed

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#30532]
|  |  |
| --- | --- |
| Bugzilla Link | [31184](https://llvm.org/bz31184) |
| Version | trunk |
| OS | All |
| Attachments | [bitcode triggering the crash](https://user-images.githubusercontent.com/95090394/143754783-b86299b4-e6d8-408b-a841-16933a7dd3ab.gz) |
| CC | @zmodem,@hfinkel |

## Extended Description 
$ clang -v
clang version 4.0.0 (trunk 287975)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.2.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clang -c -emit-llvm -o small.bc small.c
$ opt -globals-aa -lcssa -functionattrs -rpo-functionattrs -o small-opt.bc small.bc
opt: /tmp/llvm-builder/llvm-source-trunk/include/llvm/PassAnalysisSupport.h:236: AnalysisType& llvm::Pass::getAnalysisID(llvm::AnalysisID) const [with AnalysisType = llvm::CallGraphWrapperPass; llvm::AnalysisID = const void*]: Assertion `ResultPass && "getAnalysis*() called on an analysis that was not " "'required' by pass!"' failed.
#&#8203;0 0x0000000001c45a45 (opt+0x1c45a45)
#&#8203;1 0x0000000001c43b2e (opt+0x1c43b2e)
#&#8203;2 0x0000000001c43c90 (opt+0x1c43c90)
#&#8203;3 0x00007fc0b4efc330 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10330)
#&#8203;4 0x00007fc0b3ce8c37 gsignal /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;5 0x00007fc0b3cec028 abort /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;6 0x00007fc0b3ce1bf6 __assert_fail_base /build/eglibc-oGUzwX/eglibc-2.19/assert/assert.c:92:0
#&#8203;7 0x00007fc0b3ce1ca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
#&#8203;8 0x000000000186c42d (opt+0x186c42d)
#&#8203;9 0x00000000017e0bda (opt+0x17e0bda)
#&#8203;10 0x000000000078c9a1 (opt+0x78c9a1)
#&#8203;11 0x00007fc0b3cd3f45 __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;12 0x00000000007e6f4b (opt+0x7e6f4b)
Stack dump:
0.      Program arguments: opt -globals-aa -lcssa -functionattrs -rpo-functionattrs -o small-opt.bc small.bc 
1.      Running pass 'Deduce function attributes in RPO' on module 'small.bc'.
Aborted (core dumped)
$ 

-------------------------

int main ()
{
  return 0; 
}

**Comment by arsenm** [comment]
Old pass manager
