### ISSUE TITLE
wrong code at -Os and above on x86_64-linux-gnu in the 32-bit mode (but not in the 64-bit mode)

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#30607]
|  |  |
| --- | --- |
| Bugzilla Link | [31259](https://llvm.org/bz31259) |
| Version | trunk |
| OS | All |
| CC | @hfinkel,@zygoloid |

## Extended Description 
It affects 3.8.x and later, and is a regression from 3.7.x. 

$ clang -v
clang version 4.0.0 (trunk 288581)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.2.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$
$ clang -m32 -O1 small.c; ./a.out
1
$ clang-3.7 -m32 -Os small.c; ./a.out
1
$
$ clang-3.8 -m32 -Os small.c; ./a.out
0
$ clang -m32 -Os small.c; ./a.out
0
$

-----------------------------------------------------

int printf (const char *, ...);

char a, b, c[2][2][2] = { { { 1, 1 }, { 1, 0 } } };
int d, e;

int main ()
{ 
  int i[2];
  i[e] = b = 1;
  for (d = 1; d >= 0; d--)
    { 
      a++;
      c[1][b][d] = (char) (i[0]);
    }

  printf ("%d\n", c[1][1][0]);
  return 0;
}

**Comment by fhahn** [comment]
I am unable to reproduce this on the earliest version of Clang in godbolt that works with `-m32`, so this likely has been fixed: https://clang.godbolt.org/z/rnYxKrzo1
