### ISSUE TITLE
clang talks about C++1z in diagnostic for C file

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#30660]
|  |  |
| --- | --- |
| Bugzilla Link | [31312](https://llvm.org/bz31312) |
| Version | unspecified |
| OS | All |
| CC | @hfinkel,@zygoloid |

## Extended Description 
Nicos-MBP:llvm-build thakis$ cat asdf.c
_Static_assert(1);
Nicos-MBP:llvm-build thakis$ bin/clang -c asdf.c
asdf.c:1:17: warning: static_assert with no message is a C++1z extension [-Wc++1z-extensions]
_Static_assert(1);
                ^
                , ""
1 warning generated.

a) This should say _Static_assert, not static_assert
b) It shouldn't talk about C++1z in C mode.

**Comment by AaronBallman** [comment]
This should be fixed as of b7e77ff25fb2412f6ab6d6cc756666b0e2f97bd3
