### ISSUE TITLE
Merge r281586 into 3.9.1

### ISSUE THREAD

**Issue by DimitryAndric** [llvm/llvm-project#30668]
|  |  |
| --- | --- |
| Bugzilla Link | [31320](https://llvm.org/bz31320) |
| Version | 3.9 |
| OS | All |
| Blocks | llvm/llvm-project#29609  |

## Extended Description 
Please merge r281586 into 3.9.1:
------------------------------------------------------------------------
r281586 | wmi | 2016-09-15 08:28:34 +0200 (Thu, 15 Sep 2016) | 11 lines

Add some shortcuts in LazyValueInfo to reduce compile time of Correlated Value Propagation.

The patch is to partially fix llvm/llvm-project#10956 . Correlated Value Propagation queries LVI
to check non-null for pointer params of each callsite. If we know the def of
param is an alloca instruction, we know it is non-null and can return early from
LVI. Similarly, CVP queries LVI to check whether pointer for each mem access is
constant. If the def of the pointer is an alloca instruction, we know it is not
a constant pointer. These shortcuts can reduce the cost of CVP significantly.

Differential Revision: https://reviews.llvm.org/D18066
------------------------------------------------------------------------

This greatly increases the performance of the Value Propagation pass in some cases, and it is (as far as I can see) a low-impact, non-API changing fix.

**Comment by asl** [comment]
It was either merged or certainly obsolete as of now
