### ISSUE TITLE
[ppc] unnecessary zero extension / clear left instruction

### ISSUE THREAD

**Issue by weiguozhi** [llvm/llvm-project#30725]
|  |  |
| --- | --- |
| Bugzilla Link | [31377](https://llvm.org/bz31377) |
| Version | trunk |
| OS | Linux |
| CC | @hfinkel |

## Extended Description 
Compile the following code with options -m64 -O2 -mvsx -mcpu=power8

typedef unsigned long long uint64;

void foo(unsigned char* p, uint64* pval) {
      uint64 code = *p; 
      if (code < 128) {
        *pval = code;
      }   
}

LLVM generates:

foo:                                    # @&#8203;foo
.Lfunc_begin0:
# BB#0:                                 # %entry
        lbz 3, 0(3)                // A
        extsb. 3, 3                // B
        bltlr 0
# BB#1:                                 # %if.then
        clrldi   3, 3, 56          // C
        std 3, 0(4)
        blr

Instruction A load a byte from *p and zero extends it, instruction B sign extends it and set cr accordingly, instruction C clears high bits, the result should be exactly the result of instruction A.
So if instruction B write the result to a different register, or use cmpli directly, instruction C can be removed.

**Comment by chenzheng1030** [comment]
https://godbolt.org/z/nh6vjx9bY 

Should generate the expected now.
