### ISSUE TITLE
[feature request] const preventing move

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#30778]
|  |  |
| --- | --- |
| Bugzilla Link | [31430](https://llvm.org/bz31430) |
| Version | unspecified |
| OS | All |
| CC | @JonasToth,@pepsiman |

## Extended Description 
Consider the following two functions:

std::string foo(const std::string a) {
  // side-effect
  return a;
}

std::string bar() {
  const std::string a = ...;
  return a;
}

In these two cases, const prevents the string a from being moved. Not even using std::move(a) will help, since that will produce a const rvalue reference (&&const std::string), which cannot be moved from and must be copied.

It would be very useful to have a lint that warns when a const qualifier prevents a move operation for those types in which move constructors/assignment do something else than just performing a copy construction/assignment (e.g. for int such a lint makes no sense, since move and copy are "equivalent").

One should probably also warn on `std::move`/`std::forward` usage on variables that are const qualified, since that makes no sense either.

**Comment by PiotrZSL** [comment]
Detected by performance-no-automatic-move (both cases).
```
warning: constness of 'a' prevents automatic move [performance-no-automatic-move]
```
