### ISSUE TITLE
sanitizer_procmaps_mac.cc fails to compile on Mountain Lion and earlier due to usage of newer CPU types/subtypes

### ISSUE THREAD

**Issue by 0e6f8740-1d2a-4afc-85fd-df25c3a603fd** [llvm/llvm-project#30782]
|  |  |
| --- | --- |
| Bugzilla Link | [31434](https://llvm.org/bz31434) |
| Version | 3.9 |
| OS | MacOS X |
| CC | @vitalybuka |

## Extended Description 
Noticed this build failure on MacPorts ountain Lion buildbot:

/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_llvm-devel/clang-devel/work/trunk/projects/compiler-rt/lib/sanitizer_common/sanitizer_procmaps_mac.cc:121:25: error: use of undeclared identifier 'CPU_SUBTYPE_X86_64_H'
      if (cpusubtype == CPU_SUBTYPE_X86_64_H) return kModuleArchX86_64H;
                        ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_llvm-devel/clang-devel/work/trunk/projects/compiler-rt/lib/sanitizer_common/sanitizer_procmaps_mac.cc:131:10: error: use of undeclared identifier 'CPU_TYPE_ARM64'
    case CPU_TYPE_ARM64:
         ^
2 errors generated.
make[2]: *** [projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.osx.dir/sanitizer_procmaps_mac.cc.o] Error 1

We should probably just define CPU_SUBTYPE_X86_64_H and CPU_TYPE_ARM64 if their definitions are missing from the SDK's libmacho.

**Comment by arsenm** [comment]
Old build issue
