### ISSUE TITLE
stddef.h does not define ::nullptr_t in C++

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#30821]
|  |  |
| --- | --- |
| Bugzilla Link | [31473](https://llvm.org/bz31473) |
| Version | 3.9 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@zygoloid |

## Extended Description 
When <stddef.h> is included in a C++ program, ::nullptr_t should be defined. But only std::nullptr_t is.

Test case:

#include <stddef.h>
using Foo = nullptr_t;

$ clang++ -std=c++14 -c a.cpp
a.cpp:3:13: error: unknown type name 'nullptr_t'

See the same bug in GCC (which was fixed) with explanations: 
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54249

**Comment by Endilll** [comment]
CC @AaronBallman
