### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#30907]
|  |  |
| --- | --- |
| Bugzilla Link | [31559](https://llvm.org/bz31559) |
| Version | 3.7 |
| OS | other |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
FuzzerCrossOver.cpp:13:

math.h:635:18: error: use of undeclared identifier '_hypot'; did you mean 'hypot'?

Win 7 libfuzz clang win32 3.7.1

**Comment by arsenm** [comment]
Unclear what's being reported here
