### ISSUE TITLE
Spurious "conditional expression is ambiguous; 'S' and 'const char [1]' can be converted to several common types"

### ISSUE THREAD

**Issue by CyberShadow** [llvm/llvm-project#30925]
|  |  |
| --- | --- |
| Bugzilla Link | [31577](https://llvm.org/bz31577) |
| Version | 3.9 |
| OS | Linux |
| CC | @DougGregor,@hfinkel,@zygoloid |

## Extended Description 
//////////// test.cpp ////////////
struct S
{
    operator char*() const;
};

void fun()
{
    S s;
    const char* p = true ? s : "";
}
//////////////////////////////////

$ clang test.cpp
test.cpp:9:23: error: conditional expression is ambiguous; 'S' and 'const char [1]' can be converted to several common types
        const char* p = true ? s : "";
                             ^ ~   ~~
1 error generated.

Doesn't occur with gcc or msvc.

Additionally, would be nice if it listed what the several common types are.

**Comment by wheatman** [comment]
This was fixed between 5.0.2 and 6.0.0
https://godbolt.org/z/nKT3ea1z1
code
```
struct S
{
    operator char*() const;
};

void fun()
{
    S s;
    const char* p = true ? s : "";
}
```

old error
```
<source>:9:26: error: conditional expression is ambiguous; 'S' and 'const char [1]' can be converted to several common types
    const char* p = true ? s : "";
                         ^ ~   ~~
1 error generated.
Compiler returned: 1

```
