### ISSUE TITLE
no warning for comma within sizeof

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#30926]
|  |  |
| --- | --- |
| Bugzilla Link | [31578](https://llvm.org/bz31578) |
| Version | 3.8 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
Hi,
For the following test-case:

#include <stddef.h>
size_t f(int n)
{
  return sizeof(n, n + 1);
}

gcc -Wall emits diagnostic:
foo.c: In function ‘f’:
foo.c:4:18: warning: left-hand operand of comma expression has no effect [-Wunused-value]
   return sizeof(n, n + 1);
                  ^
clang -Wall -Wextra doesn't seem to emit any diagnostic.

clang --version:
clang version 3.8.1-12ubuntu1 (tags/RELEASE_381/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Thanks,
Prathamesh

**Comment by AaronBallman** [comment]
`-Wcomma` was implemented in Clang 3.9.0 and seems to cover the thrust of this request: https://godbolt.org/z/v4vbqrrno so closing as completed.
