### ISSUE TITLE
[AVR] Optimize 16-bit comparisions with zero

### ISSUE THREAD

**Issue by dylanmckay** [llvm/llvm-project#30923]
|  |  |
| --- | --- |
| Bugzilla Link | [31575](https://llvm.org/bz31575) |
| Version | trunk |
| OS | All |

## Extended Description 
Currently when we try and perform a 16-bit comparision with zero, we generate the following code:

ldi r24, 0
ldi r25, 0
cp  r26, r24
cpc r27, r25
breq LBB0_4

We can simplify this to

ldi r24, 0
cp  r26, r24
cpc r27, r24

And save a register

**Comment by benshi001** [comment]
An alternative way is 
```
cp  rlo, zero_reg
cpc rhi, zero_reg
```
The zero_reg is R17 on avrtiny or R1 on others.

**Comment by benshi001** [comment]
fixed by https://reviews.llvm.org/D142281

**Comment by benshi001** [comment]
fixed by https://github.com/llvm/llvm-project/commit/f37d7c9381ffc720a00ab61945f96e083eb58f55
