### ISSUE TITLE
llvm-lit substitutions should be discoverable.

### ISSUE THREAD

**Issue by atrick** [llvm/llvm-project#30957]
|  |  |
| --- | --- |
| Bugzilla Link | [31609](https://llvm.org/bz31609) |
| Version | trunk |
| OS | All |
| CC | @jdenny-ornl |

## Extended Description 
I’d like to be able to discover all available substitutions and their values for a given configuration.

e.g.
$ lit —show-substitutions
%key1% = “some string”
%key2% = “other string”

**Comment by matlo607** [comment]
This feature is already implemented by the `--show-suites` options.

Example of output with lit 17.0.6:
```txt
-- Test Suites --
  The name of the test suite - 12 tests
    Source Root: <project_path>/tests
    Exec Root  : <project_path>/build-dir/tests
    Available Features: gcc-compiler
    Available Substitutions: %c_flags => --specs=nosys.specs
                             %cross-compiler-c => <toolchain_path>/bin/arm-none-eabi-gcc
                             %cross-compiler-cxx =><toolchain_path>/bin/arm-none-eabi-g++
                             %cxx_flags => --specs=nosys.specs -fno-exceptions
```

@atrick : you can close this issue.
