### ISSUE TITLE
NewGVN asserts, "instruction processed too many times"

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#30961]
|  |  |
| --- | --- |
| Bugzilla Link | [31613](https://llvm.org/bz31613) |
| Version | trunk |
| OS | Windows NT |
| Blocks | llvm/llvm-project#30343  |
| Reporter | LLVM Bugzilla Contributor |
| CC | @aeubanks,@alinas,@fhahn,@nikic,@ruiling |

## Extended Description 
Reduced from one of our games (game7, for the archives).

define void @&#8203;patatino() {
entry:
  br label %while.body

while.body:                                       ; preds = %while.end129.loopexit, %entry
  %foo.0237 = phi i32 [ 0, %entry ], [ -1, %while.end129.loopexit ]
  br label %while.cond22.outer

while.cond22.outer:                               ; preds = %while.cond38, %while.body
  %foo.1.ph211 = phi i32 [ %foo.0237, %while.body ], [ %foo.2, %while.cond38 ]
  br label %while.cond22.outer212

while.cond22.outer212:                            ; preds = %if.else, %while.cond22.outer
  %foo.1.ph214 = phi i32 [ %foo.1.ph211, %while.cond22.outer ], [ %foo.2.lcssa253, %if.else ]
  br i1 undef, label %while.end129.loopexit, label %if.end31.us

if.end31.us:                                      ; preds = %while.cond22.outer212
  br label %while.body37

while.body37:                                     ; preds = %cleanup, %if.end31.us
  %foo.2 = phi i32 [ %foo.4, %cleanup ], [ %foo.1.ph214, %if.end31.us ]
  br label %while.cond38

while.cond38:                                     ; preds = %land.rhs47, %while.body37
  switch i8 undef, label %land.rhs47 [
    i8 0, label %while.cond22.outer
    i8 10, label %lor.lhs.false
  ]

land.rhs47:                                       ; preds = %while.cond38
  br label %while.cond38

lor.lhs.false:                                    ; preds = %while.cond38
  br i1 undef, label %if.then70, label %if.else

if.then70:                                        ; preds = %lor.lhs.false
  br i1 undef, label %if.then77, label %cleanup

if.then77:                                        ; preds = %if.then70
  br label %cleanup

if.else:                                          ; preds = %lor.lhs.false
  %foo.2.lcssa253 = phi i32 [ %foo.2, %lor.lhs.false ]
  br label %while.cond22.outer212

cleanup:                                          ; preds = %if.then77, %if.then70
  %foo.4 = phi i32 [ undef, %if.then77 ], [ %foo.2, %if.then70 ]
  br label %while.body37

while.end129.loopexit:                            ; preds = %while.cond22.outer212
  br label %while.body
}

**Comment by alinas** [comment]
46fb81095507 committed to resolve this.
