### ISSUE TITLE
inline namespace template ambiguities not well diagnosed

### ISSUE THREAD

**Issue by hfinkel** [llvm/llvm-project#31008]
|  |  |
| --- | --- |
| Bugzilla Link | [31660](https://llvm.org/bz31660) |
| Version | 4.0 |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
Given this code:

$ cat /tmp/t6.cpp 
namespace ns {
inline namespace in {
template <class T>
class foo { };
}
}

namespace ns {
template <class T>
class foo { };
}

using namespace ns;
foo<int> x;

We produce only this error:

$ clang -stdlib=libc++ -fsyntax-only /tmp/t6.cpp -std=c++14
/tmp/t6.cpp:14:1: error: unknown type name 'foo'
foo<int> x;
^
/tmp/t6.cpp:14:4: error: expected unqualified-id
foo<int> x;
   ^
2 errors generated.

This is really confusing. The problem, I can only suppose, is that the lookup is ambiguous, but we don't say that (and, thus, we fail to point out the relevant candidates).

If foo were not a template, like this:

$ cat /tmp/t7.cpp 
namespace ns {
inline namespace in {
class foo { };
}
}

namespace ns {
class foo { };
}

using namespace ns;
foo x;

then we produce a very sensible error:

$ clang -stdlib=libc++ -fsyntax-only /tmp/t7.cpp -std=c++14
/tmp/t7.cpp:12:1: error: reference to 'foo' is ambiguous
foo x;
^
/tmp/t7.cpp:3:7: note: candidate found by name lookup is 'ns::in::foo'
class foo { };
      ^
/tmp/t7.cpp:8:7: note: candidate found by name lookup is 'ns::foo'
class foo { };
      ^
1 error generated.

Can we do better in the template case?

**Comment by wheatman** [comment]
This was fixed for 9.0.0
https://godbolt.org/z/vhd7dPGM8

code
```cpp
namespace ns {
inline namespace in {
template <class T>
class foo { };
}
}

namespace ns {
template <class T>
class foo { };
}

using namespace ns;
foo<int> x;
```

original error (4.0)
```
<source>:14:1: error: unknown type name 'foo'
foo<int> x;
^
<source>:14:4: error: expected unqualified-id
foo<int> x;
   ^
2 errors generated.
Compiler returned: 1
```

in 5.0 the error changed to 
```
<source>:14:1: error: no template named 'foo'
foo<int> x;
^
1 error generated.
Compiler returned: 1
```

in 9.0 the error became
```
<source>:14:1: error: reference to 'foo' is ambiguous
foo<int> x;
^
<source>:4:7: note: candidate found by name lookup is 'ns::in::foo'
class foo { };
      ^
<source>:10:7: note: candidate found by name lookup is 'ns::foo'
class foo { };
      ^
1 error generated.
Compiler returned: 1
``
