### ISSUE TITLE
Loop unswitch and GVN interact badly and miscompile

### ISSUE THREAD

**Issue by nunoplopes** [llvm/llvm-project#31000]
|  |  |
| --- | --- |
| Bugzilla Link | [31652](https://llvm.org/bz31652) |
| Version | trunk |
| OS | All |
| Blocks | llvm/llvm-project#27880  |
| Attachments | [Reduced IR test case](https://user-images.githubusercontent.com/2998477/143754969-c962b58d-049c-4e71-a13d-9cc3e5d1f114.gz) |
| CC | @chandlerc,@majnemer,@aqjune,@regehr,@sanjoy |

## Extended Description 

Loop unswitch and GVN when taken together can miscompile code due to disagreeing semantics of branch on undef.
In our opinion it's loop unswitch that is incorrect.

Test case in C:
static volatile int always_false = 0;

void maybe_init(int *p) {}

int f(int limit0) {
  int maybe_undef_loc;
  maybe_init(&maybe_undef_loc);

  int limit = limit0;
  int total = 0;
  for (int i = 0; i < limit; i++) {
    total++;
    if (always_false) {
      if (maybe_undef_loc != (limit0 + 10)) {
        total++;
      }
    }
    limit = limit0 + 10;
  }
  return total;
}

int printf(const char *, ...);

int main(int argc, char **argv) {
  printf("f(10) = %d\n", f(10));
  return 0;
}

I believe this test case has no UB even at C level. It should print "f(10) = 20".

I've attached a reduced IR test case.

Running LICM, the comparison of maybe_undef_loc gets hoisted:

$ opt -S bug.ll -loop-rotate -licm
...
loop.body.lr.ph:
  %undef_loc = load i32, i32* %maybe_undef_loc, align 4
  %add = add nsw i32 %limit0, 10
  %cmp3 = icmp ne i32 %undef_loc, %add
  %limit2 = add nsw i32 %limit0, 10
  br label %loop.body
...

This is still ok. But then adding loop unswitch:

$ opt -S bug.ll -loop-rotate -licm -loop-unswitch
...
loop.body.lr.ph:
  %undef_loc = load i32, i32* %maybe_undef_loc, align 4
  %add = add nsw i32 %limit0, 10
  %cmp3 = icmp ne i32 %undef_loc, %add
  %limit2 = add nsw i32 %limit0, 10
  br i1 %cmp3, label %loop.body.lr.ph.split.us, label %loop.body.lr.ph.loop.body.lr.ph.split_crit_edge
...

Loop unswitch introduce a branch on %cmp3, which will be undef once we inline maybe_init(). Hence loop unswitch assumes branch on undef is a non-deterministic jump (so not UB).
By running GVN after loop unswitch, we clearly see that GVN has a different perspective on the semantics of branch on undef. It produces this diff:
-  %limit2 = add nsw i32 %limit0, 10
...
-  %cmp = icmp slt i32 %i2, %limit2
+  %cmp = icmp slt i32 %i2, %undef_loc

I'm not including the context here, but to be able to justify this transformation, branch on undef has to be UB, not a non-deterministic jump as assumed by loop unswitch above.

Putting all things together:
$ opt -S bug.ll -loop-rotate -licm -loop-unswitch -gvn | opt -S -O2 | llc -o x.S && clang x.S -o x && ./x
f(10) = 1

This is wrong. Should be 20, not 1.

This example shows how Loop unswitch and GVN can produce a miscompilation end-to-end. The bug can be fixed by using the proposed freeze instruction in loop unswitch.

(Example by Sanjoy)

**Comment by aqjune** [comment]
If this issue is addressed, we'll need to remove this snippet of code as well: https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp#L2508

**Comment by aqjune** [comment]
The old loop unswitch pass will be removed in https://reviews.llvm.org/D124376 .

**Comment by fhahn** [comment]
> The old loop unswitch pass will be removed in https://reviews.llvm.org/D124376 .

I think we can consider this issue closed, once D124376 lands.

**Comment by aqjune** [comment]
> If this issue is addressed, we'll need to remove this snippet of code as well: https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp#L2508

This is removed via https://github.com/llvm/llvm-project/commit/40a2e35599b5e5fa0dd93ac4edf4bf02ee636f6e
