### ISSUE TITLE
Align Compound assignment

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31029]
|  |  |
| --- | --- |
| Bugzilla Link | [31681](https://llvm.org/bz31681) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Given:
```cpp
xxxxx = 2;
x     = 5;
xxx  += 4;
```
With: `AlignConsecutiveAssignments: true`
Currently clang-format produces:
```cpp
xxxxx = 2;
x     = 5;
xxx += 4;
```
Thus it removes the alignment of the compound assignment. It would be nice if AlignConsecutiveAssignments also applied to compound assignments.

**Comment by rymiel** [comment]
I believe this was implemented as c24b3db45c7d0f08b423308723cd2e678a0cb7f1, even if it currently flawed (#58029)
