### ISSUE TITLE
Missed deadcode elimination with function pointers

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31031]
|  |  |
| --- | --- |
| Bugzilla Link | [31683](https://llvm.org/bz31683) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
See here: https://godbolt.org/g/xQD64y

If I uncomment the first call, clang determines that it's all deadcode, and generates the same "xor eax, eax" as gcc. With the first call commented out, clang still assigns to the array.

**Comment by arsenm** [comment]
See the same result as gcc in the godbolt link
