### ISSUE TITLE
Misc incorrect folds with fabs

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#31050]
|  |  |
| --- | --- |
| Bugzilla Link | [31702](https://llvm.org/bz31702) |
| Version | trunk |
| OS | Windows NT |
| CC | @jlebar,@jyknight,@RKSimon,@arsenm,@rotateright |

## Extended Description 
Testcase (opt -instcombine):

define double @&#8203;f1(double %x) local_unnamed_addr #&#8203;0 {
entry:
  %call = tail call double @&#8203;llvm.fabs.f64(double %x)
  %add = fadd double %call, 0x7FF8000000000000
  %abs = tail call double @&#8203;llvm.fabs.f64(double %add)
  ret double %abs
}

define double @&#8203;f2(double %x) local_unnamed_addr #&#8203;1 {
entry:
  %call1 = tail call double @&#8203;llvm.maxnum.f64(double 0x7FF8000000000000, double %x)
  %call2 = tail call double @&#8203;llvm.fabs.f64(double %call1)
  ret double %call1
}

define double @&#8203;f3(double %x, i32 %n) local_unnamed_addr #&#8203;1 {
entry:
  %call1 = tail call double @&#8203;llvm.powi.f64(double -0.0, i32 %n)
  %call2 = tail call double @&#8203;llvm.fabs.f64(double %call1)
  ret double %call1
}

declare double @&#8203;llvm.maxnum.f64(double, double)
declare double @&#8203;llvm.fabs.f64(double)
declare double @&#8203;llvm.powi.f64(double, i32)

instcombine eliminates fabs calls from all of these, so the sign bit could be wrong.  I think a few others are wrong too.

See https://reviews.llvm.org/D28927.

**Comment by nunoplopes** [comment]
Alive2 doesn't complain about any of the transformations anymore: https://alive2.llvm.org/ce/z/ikQvWP
