### ISSUE TITLE
3.9 compilation failure on valid code: array type mismatch

### ISSUE THREAD

**Issue by 0e6f8740-1d2a-4afc-85fd-df25c3a603fd** [llvm/llvm-project#31073]
|  |  |
| --- | --- |
| Bugzilla Link | [31725](https://llvm.org/bz31725) |
| Version | 3.9 |
| OS | All |
| CC | @tstellar |

## Extended Description 
Clang 3.9 incorrectly errors out with some legacy static assert macros (eg: libunwind).  This issue was addressed in 4.0 with r280330.

Please consider cherry-picking this commit into release_39 in case there is ever a 3.9.2.

commit 0c1c1751472348ead92a1c5ffd6a7db08dd446e7
Author: Akira Hatanaka <ahatanaka@apple.com>
Date:   Thu Sep 1 01:03:21 2016 +0000

    [Sema] Don't diagnose an array type mismatch when the new or previous
    declaration has a dependent type.
    
    This fixes a bug where clang errors out on a valid code.
    
    rdar://problem/28051467
    
    Differential Revision: https://reviews.llvm.org/D24110
    
    
    git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@280330 91177308-0d34-0410-b5e6-96231b3b80d8

**Comment by AaronBallman** [comment]
Closing as this is no longer relevant.
