### ISSUE TITLE
clang-format changes semantics of code on '#define keyword(x)'

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31086]
|  |  |
| --- | --- |
| Bugzilla Link | [31738](https://llvm.org/bz31738) |
| Version | 3.8 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
For certain keywords, '#define keyword(x)' will erroneously insert an extra space, causing the function-like macro to instead become an object-like macro. This can change the semantics of the compiled code, which should never happen.

    $ echo '#define if(x)' | clang-format
    #define if (x)

The full list of affected C++ keywords seems to be:

and, and_eq, bitor, case, catch, delete, for, if, new, not_eq, or, or_eq, return, switch, try, while, xor, xor_eq. Additionally, the MSVC-specific __except is affected, and __try is not (but I haven't exhaustively tested all of MSVC's keywords.)

Note that this is not the same as the list of keywords which should be followed by a space when used normally according to the current style, or the list of keywords which are recognised by the preprocessor, or the list of keywords which it's grammatically valid for them to be followed by an open-parenthesis. In particular, note that bitor is affected, but bitand is not.

    $ clang-format -version
    clang-format version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)

**Comment by mydeveloperday** [comment]
For the simple case of `#define XXX(` where XXX is a keyword I think this could be handled,

**Comment by mkurdej** [comment]
Revision URI: https://reviews.llvm.org/D118844.
