### ISSUE TITLE
clang-format does not handle lambda init capture by reference

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31098]
|  |  |
| --- | --- |
| Bugzilla Link | [31750](https://llvm.org/bz31750) |
| Version | 3.9 |
| OS | Linux |
| Attachments | [Example of `clang-format -style=google` failing for lambda init capture by-reference](https://user-images.githubusercontent.com/60944935/143755010-83a2d7df-cfbb-44f7-b20f-554ef1aa9537.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

When a lambda capture list includes an init capture by reference, clang-format will not change any of the lambda code.

I attached an example C++ file which includes a lambda with a capture list that exceeds the line limit in the body and the capture list.  When running `clang-format -style=google example.cpp`, neither line is wrapped to the 80 character limit.  If capture list only uses by-value init capture (i.e. remove the '&'s), the file will be formatted correctly.

**Comment by rymiel** [comment]
Cannot reproduce with any version above 8, and I cannot build any older version.
