### ISSUE TITLE
clang-format BreakBeforeBinaryOperators mishandles the standard assert idiom.

### ISSUE THREAD

**Issue by atrick** [llvm/llvm-project#31120]
|  |  |
| --- | --- |
| Bugzilla Link | [31772](https://llvm.org/bz31772) |
| Version | unspecified |
| OS | All |

## Extended Description 
clang-format is confused by the standard assert idiom used in LLVM. 

It should always do this, even with BreakBeforeBinaryOperators:

assert((precondition1 || predcondition2) &&
       “informative message”)

In this idiom, the boolean operator fills in for a comma. That’s how it’s meant to be parsed by the reader. It’s presence in the code is purely distracting. From the tool’s point of view, it’s tautological so shouldn’t be given significance as a boolean operator.

This is very important to me because I want to use clang-format in the Swift code base, but I need to add the BreakBeforeBinaryOperators setting. clang-format ended up with the wrong default out of inertia. This was never discussed AFAIK when the LLVM ratified style. If this were a matter of style, then inertia would win. But hiding the important operators creates a real code quality issue.

       if (some_expression->with_calls() ||
           another_expression->with(nested_calls()) &&
           an_even_longer_expression->making_your_eyes->glaze_over())

This is an objective code quality degradation. It's a demonstrably bug-prone thing to do. It's hurt me too many times in the past, and I'm not happy using a formatting tool that injects future bugs and harms code comprehension.

**Comment by mkurdej** [comment]
It's more of a rant than a bug report. No clear examples of the desired behaviour.
At the very last, it could be a bug report on the style guide.
Also, "objective" is pretty much subjective here.
I'm going to close it.
If anyone judges it worth reopening, please do so providing some new evidence and clear explanation.
