### ISSUE TITLE
llgo fails to build

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31134]
|  |  |
| --- | --- |
| Bugzilla Link | [31786](https://llvm.org/bz31786) |
| Version | trunk |
| OS | Linux |
| Attachments | [Don't ignore the return value of write() calls](https://user-images.githubusercontent.com/60944935/143755025-2dc9cdcc-fdeb-45da-9f6b-71d2fb54bb2a.gz), [Accept and ignore -pipe and --param=* flags](https://user-images.githubusercontent.com/60944935/143755026-a85e82b0-664f-404d-a46c-c3e47e65c8f0.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

llgo from branches/release_40 doesn't compile.

At first, building libgo barfs with complaints about return values of runtime_write being ignored (runtime_write is #defined to write, which in glibc is marked __attribute__((__warn_unused_result__)) -- and libgo is built with -Werror, causing the warning to be fatal).

After fixing that (1st attached patch), the build barfs again because compiler flags passed to clang are also used for llgo, but llgo only understands a subset of the flags clang understands -- causing "gllgo: error: unrecognized command line option '-pipe'" and "gllgo: error: unknown command line option: '--param=ssp-buffer-size=4'".

The second patch I'm attaching fixes the latter (for the moment, by making llgo accept (and quietly ignore) those flags - but maybe using a separate set of flags when calling gllgo is a better fix).

**Comment by xgupta** [comment]
llgo is not in the repo anymore.
