### ISSUE TITLE
clang 3.9.1 fails to reject or even warn about some forms of assignments to const struct fields

### ISSUE THREAD

**Issue by markmi** [llvm/llvm-project#31144]
|  |  |
| --- | --- |
| Bugzilla Link | [31796](https://llvm.org/bz31796) |
| Version | 3.9 |
| OS | All |
| CC | @DimitryAndric |

## Extended Description 
[The context for this was FreeBSD head -r312942
and so its clang 3.9.1 variant.]

clang 3.9.1 in FreeBSD allows the
following to compile without
complaint, even with -Wpedantic :
(Note the const between the * and the desc.)

struct mlx5_core_diagnostics_entry {
    const char           *const desc;
          unsigned short        counter_id;
} empty;

int main ()
{
    struct mlx5_core_diagnostics_entry test;
    test = empty;
}

gcc6, by contrast, rejects the assignment
as an error.

**Comment by Quuxplusone** [comment]
This seems to have been fixed since Clang 6.
