### ISSUE TITLE
Clang-CL diagnoses ternary ambiguity which cl.exe allows

### ISSUE THREAD

**Issue by steveire** [llvm/llvm-project#31164]
|  |  |
| --- | --- |
| Bugzilla Link | [31816](https://llvm.org/bz31816) |
| Version | trunk |
| OS | Windows NT |
| CC | @DougGregor,@zmodem,@rnk |

## Extended Description 
Given 

    struct MyBool
    {
        MyBool(bool b = false) {}
        operator bool() const { return false; }
    };

    int main()
    {
        MyBool mb;
        bool result = true ? false : mb;
        return 0;
    }

C:\dev\tmp>cl /c main.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24325.6 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

main.cpp

C:\dev\tmp>"c:\dev\src\llvm\build\Release\msbuild-bin\cl.exe" /c main.cpp
main.cpp(11,21):  error: conditional expression is ambiguous; 'bool' can be converted to 'MyBool' and vice versa
        bool result = true ? false : mb;
                           ^ ~~~~~   ~~
1 error generated.

It could be considered to match the behavior of cl.exe

**Comment by xgupta** [comment]
GCC also diagnoses this - https://godbolt.org/z/qaxrPWM1o.
