### ISSUE TITLE
cppcoreguidelines-slicing confuses initialization of virtual base classes with slicing

### ISSUE THREAD

**Issue by VReichelt** [llvm/llvm-project#31187]
|  |  |
| --- | --- |
| Bugzilla Link | [31839](https://llvm.org/bz31839) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
Running the command 

clang-tidy -checks='-*,cppcoreguidelines-slicing' bug.cc -- -c

on the code snippet

=====================================
struct A
{
  virtual ~A() {}
  virtual void foo() {}

  int i;
};

struct B : virtual A
{
  virtual void foo() {}
};

struct C : B
{
  C(const B& b) : A(b), B(b) {}
};
=====================================

produces the following output:

bug.cc:16:19: warning: slicing object from type 'B' to 'A' discards 8 bytes of state [cppcoreguidelines-slicing]
  C(const B& b) : A(b), B(b) {}
                  ^
bug.cc:16:19: warning: slicing object from type 'B' to 'A' discards override 'foo' [cppcoreguidelines-slicing]
  C(const B& b) : A(b), B(b) {}
                  ^

I.e. the check confuses the initialization of a virtual base class with slicing.
This happens with the llvm-4.0.0rc1 version.

**Comment by PiotrZSL** [comment]
Reproduced on LLVM 17 (main).
