### ISSUE TITLE
-Wnull-conversion warnings are no longer reported for `char c = NULL`

### ISSUE THREAD

**Issue by cpeterso** [llvm/llvm-project#31190]
|  |  |
| --- | --- |
| Bugzilla Link | [31842](https://llvm.org/bz31842) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor |

## Extended Description 
The following program used to report a -Wnull-conversion warning with whatever clang version Apple was shipping in 2012:

  warning: implicit conversion of NULL constant to 'char' [-Wnull-conversion]

I noted this in a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=778984

With the latest clang version Apple is shipping (Apple LLVM version 8.0.0 (clang-800.0.42.1, Target: x86_64-apple-darwin16.4.0), the following program produces no warnings, even with clang -Weverything:

#include <stdlib.h>

int main()
{
  bool b = NULL; (void) b;
  char c = NULL; (void) c;
  int i = NULL; (void) i;
  return 0;
}

**Comment by wheatman** [comment]
All of these have caused warnings since 3.2
https://godbolt.org/z/7Taqcz5Tr

code 
```cpp
#include <stdlib.h>

int main()
{
  bool b = NULL; (void) b;
  char c = NULL; (void) c;
  int i = NULL; (void) i;
  return 0;
}
```

warnings
```
<source>:5:12: warning: implicit conversion of NULL constant to 'bool' [-Wnull-conversion]
    5 |   bool b = NULL; (void) b;
      |        ~   ^~~~
      |            false
<source>:6:12: warning: implicit conversion of NULL constant to 'char' [-Wnull-conversion]
    6 |   char c = NULL; (void) c;
      |        ~   ^~~~
      |            '\0'
<source>:7:11: warning: implicit conversion of NULL constant to 'int' [-Wnull-conversion]
    7 |   int i = NULL; (void) i;
      |       ~   ^~~~
      |           0
3 warnings generated.
Compiler returned: 0
```
