### ISSUE TITLE
cppcoreguidelines-special-member-functions too strict for default destructors

### ISSUE THREAD

**Issue by VReichelt** [llvm/llvm-project#31206]
|  |  |
| --- | --- |
| Bugzilla Link | [31858](https://llvm.org/bz31858) |
| Version | unspecified |
| OS | Linux |
| CC | @AaronBallman,@jhasse |

## Extended Description 
Running the command

clang-tidy -checks='-*,cppcoreguidelines-special-member-functions' bug.cc -- -c

on the code snippet

================================
struct A
{
  virtual ~A() = default;
};
================================

produces the following output:

bug.cc:1:8: warning: class 'A' defines a destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator [cppcoreguidelines-special-member-functions]

which is IMHO not helpful at all. Technically, rule
C.21: "If you define or =delete any default operation, define or =delete them all"
applies in this context. But the destructor was only defined to make it virtual so that the class becomes usable in a polymorphic class hierarchy.
It doesn't deal with resources that need to be handled (the reason for rule C.21). Hence, there does not require a special copy constructor or assignment operator.

The only way to fix the warning would be to write the class as follows:

================================
struct A
{
  A() = default;
  virtual ~A() = default;
  A(const A&) = default;
  A(A&&) = default;
  A& operator= (const A&) = default;
  A& operator= (A&&) = default;
};
================================

which is *much* harder to read and would be in direct violation of rule
C.20: "If you can avoid defining default operations, do"

To make things short:
IMHO it would make more sense to relax the warning a little and don't warn if only a default destructor (virtual or non-virtual) has been defined in the class.

**Comment by aminya** [comment]
Yeah. It seems that `-Wnon-virtual-dtor` conflicts with `cppcoreguidelines-special-member-functions`

**Comment by carlosgalvezp** [comment]
AllowSoleDefaultDtor enables the use case described in the OP. Please open a separate bug for when the destructor is defaulted in the .cpp file.
