### ISSUE TITLE
r293518 broke module self-host

### ISSUE THREAD

**Issue by adrian-prantl** [llvm/llvm-project#31208]
|  |  |
| --- | --- |
| Bugzilla Link | [31860](https://llvm.org/bz31860) |
| Version | unspecified |
| OS | All |
| CC | @adrian-prantl,@hyp,@bcardosolopes,@DougGregor,@zygoloid |

## Extended Description 
See
> commit 2ba07641a3730952d139f831f38778ebe8538edc
> Author: Alex Lorenz <arphaman@gmail.com>
> Date:   Wed Feb 1 10:52:02 2017 +0000
> 
>     Revert r293518 as it caused module linking error in clang-reorder-fields
>     
>     This commit reverts "r293518 - [ASTMatchers] Sprinkle some constexpr on the
>     global matcher constructors" because after it a buildbot that builds clang
>     stage 2 with modules failed to link clang-reorder-fields.
>     
>     
>     git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@293759 

Link to the failing linux-selfhost-modules bot:
http://lab.llvm.org:8011/builders/clang-x86_64-linux-selfhost-modules/builds/2728

In ReorderFieldsAction.cpp
The linkage of
> @&#8203;_ZN5clang12ast_matchersL10recordDeclE = internal constant %"class.clang::ast_matchers::internal::VariadicDynCastAllOfMatcher.916" undef, align 1
changed to 

> @&#8203;_ZN5clang12ast_matchersL10recordDeclE = external global %"class.clang::ast_matchers::internal::VariadicDynCastAllOfMatcher.847", align 1

We should figure out what went wrong there.

**Comment by arsenm** [comment]
Old build issue
