### ISSUE TITLE
misc-unused-parameters fixit breaks code around unused fixed-length array parameter

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31204]
|  |  |
| --- | --- |
| Bugzilla Link | [31856](https://llvm.org/bz31856) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
clang-tidy's misc-unused-parameters fixit breaks code when given a fixed-length array parameter. (Note that as well as removing the array annotation it also leaves parentheses unbalanced.)

$ cat test.cpp
void f(int (&array)[10]) {}
$ clang-tidy -checks='-*,misc-unused-parameters' test.cpp -fix
1 warning generated.
test.cpp:1:14: warning: parameter 'array' is unused [misc-unused-parameters]
void f(int (&array)[10]) {}
             ^
              /*array*/
test.cpp:1:14: note: FIX-IT applied suggested code changes
void f(int (&array)[10]) {}
             ^
clang-tidy applied 1 of 1 suggested fixes.
$ cat test.cpp 
void f(int (& /*array*/) {}
$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 3.9.1
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: skylake

**Comment by PiotrZSL** [comment]
This is already fixed, currently output is `void f(int (& /*array*/)[10]) { }`
