### ISSUE TITLE
clang-format formats unnamed rvalue reference arguments incorrectly

### ISSUE THREAD

**Issue by 35a556ef-26b9-4f2b-837d-9b3f7ccf6035** [llvm/llvm-project#31210]
|  |  |
| --- | --- |
| Bugzilla Link | [31862](https://llvm.org/bz31862) |
| Version | unspecified |
| OS | All |

## Extended Description 
Another bug in the past in this area: https://llvm.org/bugs/show_bug.cgi?id=15051

Formatting with -style=Chromium, the input is:
```
template <class Key, class Compare>
auto flat_set<Key, Compare>::operator=(flat_set&&) -> flat_set& = default;
```

The output is:
```
template <class Key, class Compare>
auto flat_set<Key, Compare>::operator=(flat_set &&) -> flat_set& = default;
```

But there should be no space flat_set and &&.

Interestingly enough, if the parameter is named, like this:
```
template <class Key, class Compare>
auto flat_set<Key, Compare>::operator=(flat_set &&set) -> flat_set& = default;
```

Then it formats correctly:
```
template <class Key, class Compare>
auto flat_set<Key, Compare>::operator=(flat_set&& set) -> flat_set& = default;
```

**Comment by mydeveloperday** [comment]
as of clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 7890afddecff01119f4d5e8825b43dd2c8361648)
 this  formats as

```
template <class Key, class Compare>
auto flat_set<Key, Compare>::operator=(flat_set&&) -> flat_set& = default;
```

This is likely fixed by some sort that was done for nameless parameters, as it appears to be fixed I am closing this
