### ISSUE TITLE
clang-format removes space between "async" and arrow function

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31224]
|  |  |
| --- | --- |
| Bugzilla Link | [31876](https://llvm.org/bz31876) |
| Version | 4.0 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
clang-format (with default config) formats this JS code:
`    const f1 = async () => {};`
as:
`    const f1 = async() => {};`

I would rather expect for the space after async keyword not be removed as it looks confusing (like a function call).

Other context where async can be used is for example class members:

```
class Foo {
  async foo() {}
}
```

Not really proving anything with this example...

**Comment by mydeveloperday** [comment]
As of 2021.12.17 clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 55d392cc30fb36e6361ba71f4b568c093f8b23f3) this issue persists

This would make a good extension to `SpaceBeforeParensOptions`  by adding `AfterAsync: true`

**Comment by andmis** [comment]
I just tried this and I got the opposite behavior of what the ticket describes:

```
~/tmp $ clang-format --version
clang-format version 14.0.0 (git@github.com:llvm/llvm-project 73205feb00f57e8a976c385b1e7523683ec26d00)
~/tmp $ cat arrow.js 
const f = async() => {};
~/tmp $ clang-format arrow.js 
const f = async () => {};
~/tmp $ 
```

**Comment by mydeveloperday** [comment]
I confirm as of clang-format version 15.0.0 (https://github.com/llvm/llvm-project.git 7890afddecff01119f4d5e8825b43dd2c8361648)

This doesn't seem to "not" put a space after async for

.clang-format
`Language: JavaScript`

```
const f3 = async arg => {};
const f1 = async () => {};

class Foo {
  async foo() {}
}
```

Closing as functioning as desired, if you see something different feel free to reopen
