### ISSUE TITLE
Complex division is not optimised with -ffast-math

### ISSUE THREAD

**Issue by dc81c6b5-3a5b-438e-b826-9e7edb3cf487** [llvm/llvm-project#31220]
|  |  |
| --- | --- |
| Bugzilla Link | [31872](https://llvm.org/bz31872) |
| Version | trunk |
| OS | Linux |
| CC | @hyp,@compnerd,@lesshaste,@hfinkel,@joker-eph,@RKSimon,@rotateright,@TNorthover |

## Extended Description 
Consider:

#include <complex.h>
complex float f(complex float x, complex float y) {
  return x/y;
}

clang trunk with -O3 -march=core-avx2 but with or without -ffast-math gives:

f:                                      # @&#8203;f
        vmovaps xmm2, xmm1
        vmovshdup       xmm1, xmm0      # xmm1 = xmm0[1,1,3,3]
        vmovshdup       xmm3, xmm2      # xmm3 = xmm2[1,1,3,3]
        jmp     __divsc3                # TAILCALL

However both gcc and ICC attempt to optimise this code when -ffast-math (or equivalent) is enabled.

ICC appears to give the fastest code which is:

f:
        vcvtps2pd xmm2, xmm1                                    #&#8203;3.12
        vcvtps2pd xmm4, xmm0                                    #&#8203;3.12
        vmulpd    xmm8, xmm2, xmm2                              #&#8203;3.12
        vunpckhpd xmm3, xmm2, xmm2                              #&#8203;3.12
        vmulpd    xmm6, xmm3, xmm4                              #&#8203;3.12
        vmovddup  xmm7, xmm2                                    #&#8203;3.12
        vshufpd   xmm5, xmm4, xmm4, 1                           #&#8203;3.12
        vshufpd   xmm9, xmm8, xmm8, 1                           #&#8203;3.12
        vfmaddsub213pd xmm7, xmm5, xmm6                         #&#8203;3.12
        vaddpd    xmm11, xmm8, xmm9                             #&#8203;3.12
        vshufpd   xmm10, xmm7, xmm7, 1                          #&#8203;3.12
        vdivpd    xmm12, xmm10, xmm11                           #&#8203;3.12
        vcvtpd2ps xmm0, xmm12                                   #&#8203;3.12
        ret

**Comment by jcranmer-intel** [comment]
As of https://github.com/llvm/llvm-project/pull/70244, -ffast-math implies limited range division, and https://github.com/llvm/llvm-project/pull/81514 adds some more fine-grained control over which division algorithm is selected. I think this bug can be closed now as fixed.
