### ISSUE TITLE
[feature request] provide a __ctfe builtin for detecting compile-time execution

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#31265]
|  |  |
| --- | --- |
| Bugzilla Link | [31917](https://llvm.org/bz31917) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@RKSimon,@zygoloid |

## Extended Description 
From the D language docs:

"The __ctfe boolean pseudo-variable, which evaluates to true at compile time, but false at run time, can be used to provide an alternative execution path to avoid operations which are forbidden at compile time. Every usage of __ctfe is evaluated before code generation and therefore has no run-time cost, even if no optimizer is used."

It would be nice to have such an intrinsic in clang to be able to switch algorithms optimized for compile-time or run-time usage in constexpr functions. 

For example, a constexpr function that wants to use SIMD intrinsics at run-time, currently cannot, because the intrinsics are not constexpr, and clang's constant evaluator cannot handle them (and the one in LLVM cannot be leveraged for this). 

Providing such an intrinsic would be a way easier task than, say, teaching clang's constant expression evaluator how to handle _all_ intrinsics so that one can make them constexpr.

**Comment by Endilll** [comment]
In C++20 we got `std::is_constant_evaluated()`, then in C++23 we got `if consteval`.
Feel free to reopen if there are concerns not addressed by aforementioned features.
