### ISSUE TITLE
SEGV when starting thread with empty body

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31271]
|  |  |
| --- | --- |
| Bugzilla Link | [31923](https://llvm.org/bz31923) |
| Version | 3.9 |
| OS | Linux |
| Attachments | [example reproducing issue](https://user-images.githubusercontent.com/60944935/143755088-bdc1dfd4-5965-4758-be80-ca5cbf7c90cd.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 

starting thread, with empty function/lambda body causes SEGV, when compiled with optimizations and profiling. adding any delay when starting thread (like sleep for a nanosecond) fixes the issue.

example code is attached. compile it with:
clang++-3.9 -std=c++11 -O1 -pg -lpthread thread.cpp

i'm observing this behavior on clang++ starting with 3.5 up to 3.9, inclusively.

**Comment by wheatman** [comment]
This seems to have been fixed between 3.9.0 and 4.0.0
https://godbolt.org/z/PfvKb117e

For reference 
code
```
// clang++-3.9 -std=c++11 -O1 -pg -lpthread thread.cpp
// ./a.out # SEGV...
#include <chrono>
#include <thread>

int main()
{

  std::thread th{ []{} };
  th.join();
}

```
