### ISSUE TITLE
clang-format incorrectly removes space between macro and ::-qualified return type

### ISSUE THREAD

**Issue by 35a556ef-26b9-4f2b-837d-9b3f7ccf6035** [llvm/llvm-project#31299]
|  |  |
| --- | --- |
| Bugzilla Link | [31951](https://llvm.org/bz31951) |
| Version | unspecified |
| OS | Windows NT |

## Extended Description 
$ cat test.cc
`#define MY_MACRO`

```
MY_MACRO ::std::string GetString() {
  return "abc";
}
```
$ clang-format -i --style=Chromium test.cc
$ cat test.cc
```
#define MY_MACRO

MY_MACRO::std::string GetString() {
  return "abc";
}
```

This is a bit tricky since IIRC, clang-format doesn't know anything about macros... and without that knowledge, this could read ambiguously.

**Comment by mydeveloperday** [comment]
As of 2021.12.17 clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 55d392cc30fb36e6361ba71f4b568c093f8b23f3)

This formats as the following, clang-format doesn't understand what MY_MACRO is, it could be a namespace or it could be [[nodiscard]] in both cases it would need to do something different in terms of spacing.

```
#define MY_MACRO

MY_MACRO::std::string GetString() { return "abc"; }
```

**Comment by mkurdej** [comment]
Since version 5, clang-format does not remove a preexisting space after `MY_MACRO` (it did in version 4).
Closing.

Given input:
```
MY_MACRO::std::string GetString() {
  return "abc";
}

MY_MACRO ::std::string GetString() {
  return "abc";
}
```

I get:

V5:
```
"d:\Program Files\LLVM-5.0.2\bin\clang-format.exe" -style=file test.cpp
MY_MACRO::std::string GetString() {
  return "abc";
}

MY_MACRO ::std::string GetString() {
  return "abc";
}
```

And V4:
```
d:\src\bugs\llvm\gh>"d:\Program Files\LLVM-4.0.1\bin\clang-format.exe" -style=file test.cpp
MY_MACRO::std::string GetString() {
  return "abc";
}

MY_MACRO::std::string GetString() {
  return "abc";
}
```
