### ISSUE TITLE
libc++ does not support explicit instantiation of valarray transcendentals

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31314]
|  |  |
| --- | --- |
| Bugzilla Link | [31966](https://llvm.org/bz31966) |
| Version | 4.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow,@petrpavlu |

## Extended Description 
The following causes a compile error:
```
------------>8------------
#include <valarray>

int main() {
  std::valarray<double> v00;
  std::sinh<double>(v00);
  return 0;
}
------------8<------------
```
Whereas the following use is supported:
```
------------>8------------
#include <valarray>

int main() {
  std::valarray<double> v00;
  std::sinh(v00);
  return 0;
}
------------8<------------
```
The former is valid as per the standard (Section 26.6.3.3). libstdc++ (4.8) supports both forms.

There is a patch to fix this at: https://reviews.llvm.org/D13289 (although it may have bit-rotted a bit).

**Comment by Quuxplusone** [comment]
I agree, this doesn't look like a bug to me. Calling STL functions with explicit arguments is never a good idea — whether it's `std::min<int>` or `std::make_pair<int, int>` (which actually _broke_ in C++11) or whatever. If you want to take the sinh of `v00`, just write `std::sinh(v00)`, which works everywhere.
