### ISSUE TITLE
llvm-tblgen.exe crashes while compiling LLVM/Clang current release_40 with MinGW 4.9.2

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31366]
|  |  |
| --- | --- |
| Bugzilla Link | [32018](https://llvm.org/bz32018) |
| Version | 4.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zmodem,@rnk,@TNorthover |

## Extended Description 
NOTE: The product for this report is most probably wrong, please correct.

MinGW 4.9.2
Current release_40 branch, top commit is:

commit 86fb9eec6cc7843df17ad8fc3feb75f09c067459
Author: Hans Wennborg <hans@hanshq.net>
Date:   Thu Feb 16 21:13:06 2017 +0000

    Merging r295224:
    ------------------------------------------------------------------------
    r295224 | rsmith | 2017-02-15 11:57:10 -0800 (Wed, 15 Feb 2017) | 2 lines

    llvm/llvm-project#24814 : Do not silently discard a fold-expression appearing as the operand of a cast-expression.

    ------------------------------------------------------------------------

    git-svn-id: https://llvm.org/svn/llvm-project/cfe/branches/release_40@295375 91177308-0d34-0410-b5e6-96231b3b80

Commands used:
$ cmake -G "MinGW Makefiles" -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_BUILD_TYPE=Release
$ mingw32-make.exe -j4 install-libclang install-libclang-headers install-clang-headers install-llvm-config

Output:
mingw32-make.exe[3]: Entering directory 'D:/dev/llvm/4.0/builds/mingw492'
[ 26%] Building X86GenSubtargetInfo.inc...
cd /d D:\dev\llvm\4.0\builds\mingw492\lib\Target\X86 && ..\..\..\bin\llvm-tblgen.exe -gen-subtarget -I D:/dev/llvm/
4.0/source/lib/Target/X86 -I D:/dev/llvm/4.0/source/include -I D:/dev/llvm/4.0/source/lib/Target D:/dev/llvm/4.0/so
urce/lib/Target/X86/X86.td -o D:/dev/llvm/4.0/builds/mingw492/lib/Target/X86/X86GenSubtargetInfo.inc.tmp
Wrote crash dump file "C:\Users\nik\AppData\Local\Temp\llvm-tblgen.exe-447764.dmp"
0x005382D2 (0x0840D550 0x086F8D10 0x086FB358 0x086FCA50)
0x0840D4FC (0x0162FD60 0x034B263C 0x0000000D 0x00000000) <unknown module>
0x004CF3D5 (0x017B8F30 0x0000000B 0x00152AD0 0x00000000)
0x77666D3C (0x00000001 0x00000000 0x00000001 0x0162FE14), LdrLoadDll() + 0x91 bytes(s)
0x7634D076 (0x00152AD0 0x004D2620 0x005B8E9A 0x00000000), GetProcAddressForCaller() + 0x47 bytes(s)
0x0059D6C1 (0x0000000B 0x00152A98 0x00151730 0x00000000)
0x004013DE (0x7FFDE000 0x0162FFD4 0x7766BD99 0x7FFDE000)
0x767F86E3 (0x7FFDE000 0xC3825040 0x00000000 0x00000000), BaseThreadInitThunk() + 0xE bytes(s)
0x7766BD99 (0x004014E0 0x7FFDE000 0xFFFFFFFF 0x776E220F), RtlInitializeExceptionChain() + 0x85 bytes(s)
0x7766BD6C (0x004014E0 0x7FFDE000 0x00000000 0x3D3D2F2F), RtlInitializeExceptionChain() + 0x58 bytes(s)
lib\Target\X86\CMakeFiles\X86CommonTableGen.dir\build.make:704: recipe for target 'lib/Target/X86/X86GenSubtargetIn
fo.inc.tmp' failed
mingw32-make.exe[3]: *** [lib/Target/X86/X86GenSubtargetInfo.inc.tmp] Error -1073741819
mingw32-make.exe[3]: *** Deleting file 'lib/Target/X86/X86GenSubtargetInfo.inc.tmp'
mingw32-make.exe[3]: Leaving directory 'D:/dev/llvm/4.0/builds/mingw492'
CMakeFiles\Makefile2:4430: recipe for target 'lib/Target/X86/CMakeFiles/X86CommonTableGen.dir/all' failed
mingw32-make.exe[2]: *** [lib/Target/X86/CMakeFiles/X86CommonTableGen.dir/all] Error 2
mingw32-make.exe[2]: Leaving directory 'D:/dev/llvm/4.0/builds/mingw492'
CMakeFiles\Makefile2:12530: recipe for target 'tools/clang/tools/libclang/CMakeFiles/install-libclang.dir/rule' fai
led
mingw32-make.exe[1]: *** [tools/clang/tools/libclang/CMakeFiles/install-libclang.dir/rule] Error 2
mingw32-make.exe[1]: Leaving directory 'D:/dev/llvm/4.0/builds/mingw492'
makefile:3121: recipe for target 'install-libclang' failed
mingw32-make.exe: *** [install-libclang] Error 2

D:\dev\llvm\4.0\builds\mingw492>

**Comment by arsenm** [comment]
Old build issue
