### ISSUE TITLE
llvm-3.91 and LTO

### ISSUE THREAD

**Issue by 318fd643-f71d-4317-9e72-7567dcb33bee** [llvm/llvm-project#31377]
|  |  |
| --- | --- |
| Bugzilla Link | [32029](https://llvm.org/bz32029) |
| Version | 3.9 |
| OS | Linux |

## Extended Description 
Compiling llvm-3.9.1 with and without LTO, there is a huge difference in the size of the static libs, but LTO should not be used on the static libs.

LLVM_ENABLE_LTO:STRING=OFF 29,552,856 libLLVM-3.9.so  29,258,242 libclangSema.a
LLVM_ENABLE_LTO:STRING=ON  26,684,952 libLLVM-3.9.so 137,760,300 libclangSema.a

**Comment by arsenm** [comment]
Old build issue
