### ISSUE TITLE
[clang] "Stored value type does not match pointer operand type" with some objc code

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31381]
|  |  |
| --- | --- |
| Bugzilla Link | [32033](https://llvm.org/bz32033) |
| Version | 3.9 |
| OS | Linux |
| Attachments | [ObjC code that crashes clang](https://user-images.githubusercontent.com/60944935/143755144-8c1f98c3-3475-4e4c-a8e3-d3793567d89d.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Hi! The following program makes clang crash (with an assertion failure, if assertions are enabled):

---8<-----------------------------------------------------------
/* Compile with clang-3.9 -cc1 -emit-obj foo.m */
@&#8203;protocol Object @&#8203;end
@&#8203;interface Object {} @&#8203;end

@&#8203;interface Container <ObjectType>: Object
- (ObjectType const *)objects;
@&#8203;end

@&#8203;class Stuff;
@&#8203;interface A : Object
{
  Container <Stuff *> * _stuff;
}
@&#8203;end

@&#8203;implementation A
- (void)method
{
  Stuff *const *objects = [_stuff objects];
}
@&#8203;end
---8<-----------------------------------------------------------

Equivalent one-liner and result:
$ base64 -d<<<H4sIAMJcrFgCA02OQQ6CMBBF9z3FXwqJFxAlEA/gQnfGGCxDrIEOoaOJIdxdpQXZvvn/zc/ajoU11zjcHqQFGdlSZcYKdVWhacL94C/L056tFMZSh61Pnd4tpZtQUWus/hiarRPEEY/IJSrodF04h6M8qypZynPMol5h+WvMIk4R4+p8b5hspmlrauibFcMW+W/Ei00ZNSR3LkdV6IdBYQ92OHsbArnM2g8WmkgyJAEAAA==|gzip -d|clang-3.9 -cc1 -emit-obj -x objective-c -
Stored value type does not match pointer operand type!
  store i8** %call, %1*** %objects, align 4
 %"type 0x55a0d48564b0"**fatal error: error in backend: Broken function found, compilation aborted!

I have tested clang 3.8, 3.9, and 4.0-rc2 as shipped in Debian: They fail with the same error.

**Comment by Endilll** [comment]
Can't reproduce on Clang 3.8, 3.9, 4.0, and 16
https://godbolt.org/z/9v4nPejaK
