### ISSUE TITLE
Formatter doesn't wrap things that use alignment directives well

### ISSUE THREAD

**Issue by 35a556ef-26b9-4f2b-837d-9b3f7ccf6035** [llvm/llvm-project#31397]
|  |  |
| --- | --- |
| Bugzilla Link | [32049](https://llvm.org/bz32049) |
| Version | unspecified |
| OS | Windows NT |

## Extended Description 
Before:
```c++
alignas(DATA_ALIGNMENT)
    uint8_t data[kSegments * (sizeof(media::AudioInputBufferParameters) +
                              frames * channels * sizeof(float))];
```
Arguably a bit unreadable already, but the formatted result is this:
```c++
alignas(
    DATA_ALIGNMENT) uint8_t data[kSegments *
                                 (sizeof(media::AudioInputBufferParameters) +
                                  frames * channels * sizeof(float))];
```

Which I'm not sure is more readable. It'd be nice not to break in the middle of alignas, at the very least.

**Comment by rymiel** [comment]
The oldest version I can get my hands on clang-format 9, and this bug seems to already be fixed there, so it seems it was fixed somewhere within the 2 year gap between this issue and clang-format 9
