### ISSUE TITLE
CMake INSTALL error: libclang_rt.asan-i386.so not found

### ISSUE THREAD

**Issue by Keno** [llvm/llvm-project#31429]
|  |  |
| --- | --- |
| Bugzilla Link | [32081](https://llvm.org/bz32081) |
| Version | 4.0 |
| OS | All |
| CC | @vitalybuka |

## Extended Description 
CMake Install Step fails with the following message:
```
CMake Error at projects/compiler-rt/lib/asan/cmake_install.cmake:72 (file):
  file INSTALL cannot find
  "/home/keno/julia/deps/scratch/llvm-svn/build_Release+Asserts/projects/compiler-rt/lib/asan/CMakeFiles/CMakeRelink.dir/libclang_rt.asan-i386.so".
Call Stack (most recent call first):
  projects/compiler-rt/lib/cmake_install.cmake:43 (include)
  projects/compiler-rt/cmake_install.cmake:38 (include)
  projects/cmake_install.cmake:37 (include)
  cmake_install.cmake:61 (include)
```

Clang/LLVM/CompilerRT are on the release_40 branch. Configuration cache is copied here: https://gist.github.com/Keno/7d0fc916ee5f7181796c07bf16312fa2

I suppose the option most likely to be the culprit is `-DLLVM_BUILD_LLVM_DYLIB:BOOL=ON`.

**Comment by arsenm** [comment]
Old build issue
