### ISSUE TITLE
Multiple moves compiled inefficiently

### ISSUE THREAD

**Issue by dc81c6b5-3a5b-438e-b826-9e7edb3cf487** [llvm/llvm-project#31434]
|  |  |
| --- | --- |
| Bugzilla Link | [32086](https://llvm.org/bz32086) |
| Version | trunk |
| OS | Linux |
| CC | @alexey-bataev,@lesshaste,@dtemirbulatov,@hfinkel,@jyknight,@RKSimon,@rotateright |

## Extended Description 
Consider:

double a[4], b[4], c[4];

void foo ()
{
  a[0] = c[0];
  a[1] = c[1];
  a[2] = c[0];
  a[3] = c[1];
  b[0] = c[2];
  b[1] = c[3];
  b[2] = c[2];
  b[3] = c[3];
}

clang compiles this with -O3 to:

foo:                                    # @&#8203;foo
        mov     rax, qword ptr [rip + c]
        mov     qword ptr [rip + a], rax
        mov     rcx, qword ptr [rip + c+8]
        mov     qword ptr [rip + a+8], rcx
        mov     qword ptr [rip + a+16], rax
        mov     qword ptr [rip + a+24], rcx
        mov     rax, qword ptr [rip + c+16]
        mov     qword ptr [rip + b], rax
        mov     rcx, qword ptr [rip + c+24]
        mov     qword ptr [rip + b+8], rcx
        mov     qword ptr [rip + b+16], rax
        mov     qword ptr [rip + b+24], rcx
        ret

gcc on the other hand gives the more efficient:

foo:
        movapd  xmm1, XMMWORD PTR c[rip]
        movapd  xmm0, XMMWORD PTR c[rip+16]
        movaps  XMMWORD PTR a[rip], xmm1
        movaps  XMMWORD PTR a[rip+16], xmm1
        movaps  XMMWORD PTR b[rip], xmm0
        movaps  XMMWORD PTR b[rip+16], xmm0
        ret

**Comment by RKSimon** [comment]
Fixed in trunk: https://godbolt.org/z/vj5oMMKa1
