### ISSUE TITLE
Can't see option in clang-format to omit spaces around binary operators

### ISSUE THREAD

**Issue by 8574d5df-4f6c-46cc-848c-86d7e751e0ab** [llvm/llvm-project#31431]
|  |  |
| --- | --- |
| Bugzilla Link | [32083](https://llvm.org/bz32083) |
| Version | 4.0 |
| OS | Windows NT |
| CC | @LegalizeAdulthood |

## Extended Description 
Maybe I'm missing something and just can't find the right option. But I think it's actually valid code style to do this and as I checked out both Resharper and Visual Studio formatting options provide this option.

**Comment by mkurdej** [comment]
Duplicate of #19412.
