### ISSUE TITLE
Support C++17

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#31440]
|  |  |
| --- | --- |
| Bugzilla Link | [32092](https://llvm.org/bz32092) |
| Version | trunk |
| OS | All |
| Depends On | llvm/llvm-project#31441 llvm/llvm-project#29237  |

## Extended Description 
Clang-format does not support C++17, which leads to some very horrible formatting. This is a meta-issue to link all other C++17 related issues.

**Comment by asl** [comment]
@mydeveloperday Can we close this?

**Comment by mydeveloperday** [comment]
Both dependant issues are closed, so closing this
