### ISSUE TITLE
Implement formatting of structured bindings.

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#31441]
|  |  |
| --- | --- |
| Bugzilla Link | [32093](https://llvm.org/bz32093) |
| Version | trunk |
| OS | All |
| Blocks | llvm/llvm-project#31440  |

## Extended Description 
Structured bindings should be properly supported in clang-format.

`auto [x, y, z] = std::make_tuple(0, 1, 2);`

gets reformatted as

`auto[x, y, z] = std::make_tuple(0, 1, 2);`

Probably want to offer a way to customize this as well.

**Comment by mydeveloperday** [comment]
In clang-format v5 we see this

`auto[x, y, z] = std::make_tuple(0, 1, 2);`

in clang-format v8 and above we see

`auto [x, y, z] = std::make_tuple(0, 1, 2);`

I'm going to close this issue please reopen if its still a problem for you
