### ISSUE TITLE
FixNamespaceComments on an empty namespace will add the comment

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#31465]
|  |  |
| --- | --- |
| Bugzilla Link | [32117](https://llvm.org/bz32117) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
```
BasedOnStyle: LLVM
FixNamespaceComments: true
```

foo.c
```
namespace a {

}
```

$ clang-format-5.0 foo.c
namespace a {} // namespace a

**Comment by mydeveloperday** [comment]
I think this has been fixed for some time, but you should look at `ShortNamespaceLines` in https://clang.llvm.org/docs/ClangFormatStyleOptions.html

![image](https://user-images.githubusercontent.com/16046346/145967006-71b4eae0-ec20-4776-bdce-f4c015a58772.png)

I'm marking this item as closed, please reopen if still an issue
