### ISSUE TITLE
missing div-by-zero warning

### ISSUE THREAD

**Issue by 9816046d-d175-4de2-95d1-ce389e5190e8** [llvm/llvm-project#31474]
|  |  |
| --- | --- |
| Bugzilla Link | [32126](https://llvm.org/bz32126) |
| Version | 3.9 |
| OS | Linux |
| CC | @dwblaikie |

## Extended Description 
I ran across a case where gcc turns a simple function

  static inline int return0(void) { return 0; }
  int provoke_div0_warning(void) { return 1 / return0(); }

into an unconditionally trapping instruction, but does not
warn about doing this, I opened #79828  in gcc bugzilla
for this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79828

Cross-checking with clang revealed that the same input
instead of trapping leads to undefined behavior (returning
uninitialized register value) and also produces no warning,
even with -Weverything.

It would be nice to have a warning about this, and it could
also be useful to use a trapping instruction rather than
silent undefined behavior.

**Comment by Quuxplusone** [comment]
UBSan (`-fsanitize=undefined`) _does_ catch this — i.e. it unconditionally inserts instrumentation into `provoke_div0_warning` — so I don't think there's anything more to do here.
