### ISSUE TITLE
UTF-16 (LE) byte order mark encoding not supported

### ISSUE THREAD

**Issue by zahiraam** [llvm/llvm-project#31475]
|  |  |
| --- | --- |
| Bugzilla Link | [32127](https://llvm.org/bz32127) |
| Version | trunk |
| OS | Windows NT |
| CC | @DougGregor |

## Extended Description 
UTF-16 encoding in a file or in an included file produces an error.

Simple test case:
ksh-3.2$ cat -v toto.cpp
#include "foo.h"^M
^M
ksh-3.2$

Content of file included in toto.cpp:
ksh-3.2$ cat -v foo.h
M-^?M-~/^@/^@^M^@
^@#^@d^@e^@f^@i^@n^@e^@ ^@r^@ ^@1^@0^@^M^@
^@^M^@
^@ksh-3.2$

When compiling toto.cpp with:

ksh-3.2$ clang-cl -v -c toto.cpp
clang version 5.0.0 (cfe/trunk 296821)
....
clang -cc1 version 5.0.0 based upon LLVM 5.0.0svn default target x86_64-pc-windows-msvc
...

toto.cpp(1,10):  fatal error: UTF-16 (LE) byte order mark detected in './foo.h', but encoding is not supported
#include "foo.h"
         ^
1 error generated.

I have also tried put the content of foo.h directly in the .cpp file and I get the same behavior.

**Comment by cor3ntin** [comment]
Duplicate of #39211
