### ISSUE TITLE
Cannot select: intrinsic %llvm.arm.get.fpscr after r296865

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#31482]
|  |  |
| --- | --- |
| Bugzilla Link | [32134](https://llvm.org/bz32134) |
| Version | trunk |
| OS | Linux |
| Attachments | [preprocessed source](https://user-images.githubusercontent.com/1148786/143755180-8ee7fb86-2008-4d9b-b483-7b58571251b6.gz), [invocation](https://user-images.githubusercontent.com/1148786/143755181-b0de359d-7c82-485f-8f65-ea26b7bd8bd3.gz) |

## Extended Description 

This broke the Chromium build for Android.

Attaching preprocessed source.

**Comment by xgupta** [comment]
Seems this is fixed, can't reproduce with clang version 15.0.0 (https://github.com/llvm/llvm-project.git c204cee642ee794901d2e8a9819b52ac12f92bc9)
.
