### ISSUE TITLE
[feature request] requires clause in class templates (Concepts TS)

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#31513]
|  |  |
| --- | --- |
| Bugzilla Link | [32165](https://llvm.org/bz32165) |
| Version | trunk |
| OS | All |
| CC | @CaseyCarter,@HazardyKnusperkeks,@Sebanisu |

## Extended Description 
The following code:

template <class T, class U, class... Rest>
  requires CommonReference<T, U>() 
struct common_reference<T, U, Rest...>
    : common_reference<common_reference_t<T, U>, Rest...> {};

is reformatted to 

template <class T, class U, class... Rest>
requires CommonReference<T, U>() struct common_reference<T, U, Rest...>
    : common_reference<common_reference_t<T, U>, Rest...> {};

because clang-format does not understand the requires keyword in class templates.

It should either be formatted to 

// A: requires clause in its own line: 
template <class T, class U, class... Rest>
  requires CommonReference<T, U>() 
struct common_reference<T, U, Rest...>
    : common_reference<common_reference_t<T, U>, Rest...> {};

// B: small require clause in line with template arguments 
template <class T, class U, class... Rest> requires CommonReference<T, U>() 
struct common_reference<T, U, Rest...>
    : common_reference<common_reference_t<T, U>, Rest...> {};

Also, long requires clauses are not handled properly

template <class T, class U, class... Rest>
    requires CommonReference<T, U>() && 
             CommonReference<T, U>() &&
             CommonReference<T, U>() 
struct common_reference<T, U, Rest...>
    : common_reference<common_reference_t<T, U>, Rest...> {};

is reformatted to:

template <class T, class U, class... Rest>
    requires CommonReference<T, U>() && CommonReference<T, U>() &&
    CommonReference<T, U>() struct common_reference<T, U, Rest...>
    : common_reference<common_reference_t<T, U>, Rest...> {};

Following customization parameters _might_ make sense, but I haven't given this much thought:

- indentation of the require clause with respect to the template arguments/struct (e.g. 1 space, 4 spaces...). Maybe we could reuse ContinuationIndentWidth/AccessModifierOffset for this, but I'd rather have it as a standalone option.
- AllowShortRequireClausesOnASingleLine: whether short requires clauses should be wrapped into the same line as the template arguments

And well probably stuff like BreakBeforeBinaryOperators should work here properly.

**Comment by HazardyKnusperkeks** [comment]
Review link: https://reviews.llvm.org/D113319

**Comment by HazardyKnusperkeks** [comment]
Pushed
