### ISSUE TITLE
[feature request] requires clause in functions (concepts TS)

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#31514]
|  |  |
| --- | --- |
| Bugzilla Link | [32166](https://llvm.org/bz32166) |
| Version | trunk |
| OS | All |
| CC | @CaseyCarter,@HazardyKnusperkeks,@mydeveloperday |

## Extended Description 
This code
```c++
template <bool IsConst>
struct A {
  void prev() 
  requires BidirectionalIterator<iterator_t<IsConst>>() &&
           BidirectionalIterator<iterator_t<IsConst>>() &&
           BidirectionalIterator<iterator_t<IsConst>>() 
  { --it_; }
};
```
gets formatted into: 
```c++
template <bool IsConst>
struct A {
  void prev() requires BidirectionalIterator<iterator_t<IsConst>>() &&
      BidirectionalIterator<iterator_t<IsConst>>() &&
      BidirectionalIterator<iterator_t<IsConst>>() {
    --it_;
  }
};
```
I don't see a reason why the options specified in #&#8203;32165 shouldn't apply here as well. 

Also: https://github.com/CaseyCarter/cmcstl2/blob/43b63f6846d80bcd1867f512519bc18841bd961e/include/stl2/detail/iterator/operations.hpp#L25

this code: 
```c++
template <class I>
requires
        Iterator<I>()
        // Pre: 0 <= n && [i,i+n)
constexpr void impl(I& i, difference_type_t<I> n)
noexcept(noexcept(++std::declval<I&>()))
{
    STL2_EXPECT(0 <= n);
    while (n != 0) {
        --n;
        ++i;
    }
}
```
gets formatted into 
```c++
template <class I>
requires Iterator<I>()
    // Pre: 0 <= n && [i,i+n)
    constexpr void impl(I& i, difference_type_t<I> n) noexcept(
        noexcept(++std::declval<I&>())) {
  STL2_EXPECT(0 <= n);
  while (n != 0) {
    --n;
    ++i;
  }
}
```
(Note how the constexpr keywords is not aligned with the template keyword).

**Comment by HazardyKnusperkeks** [comment]
The review link would be: https://reviews.llvm.org/D113319
But I have decided that the style
``` c++
template <typename T>
requires
             C<T>
class ...
```
will not be supported. If you are really interested in it you can look at some older revision where I had a basic handling of that and try to get it working.

**Comment by CaseyCarter** [comment]
Let's go ahead and call this closed. Anyone who wants changes can file a new issue.
