### ISSUE TITLE
[llvm-namespace-comment] does not support nested namespace A::B::C

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#31543]
|  |  |
| --- | --- |
| Bugzilla Link | [32195](https://llvm.org/bz32195) |
| Version | unspecified |
| OS | All |
| CC | @def- |

## Extended Description 
[llvm-namespace-comment] does not support nested namespace A::B::C

namespace A::B::C {

struct foo {};

} // namespace A::B::C

^ Error wrong closing comment for namespace C 

Critical: clang-format _automatically_ generates these comments for nested namespaces!

When clang-tidy uses clang-format to reformat the code, reformatting will break clang-tidy!

**Comment by PiotrZSL** [comment]
Currently llvm-namespace-comment properly handles such namespaces.
Looks to be fixed by 9549c1180fc8e547d29888cea1ba07066214dbea.
