### ISSUE TITLE
[cppcoreguidelines-special-member-functions] broken for constexpr destructors

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#31554]
|  |  |
| --- | --- |
| Bugzilla Link | [32206](https://llvm.org/bz32206) |
| Version | unspecified |
| OS | All |
| Depends On | llvm/llvm-project#31563  |

## Extended Description 
[cppcoreguidelines-special-member-functions] warns when a destructor is omitted and suggests to =default it.

When this destructor would be implicitly generated to be constexpr, =defaulting it prevents it from being constexpr. 

As a consequence, this breaks programs that rely on constexpr destructors.

**Comment by carlosgalvezp** [comment]
Closing since the referred issue has been closed. There is also lack of example code to reproduce this issue.
