### ISSUE TITLE
user-declared implicitly-provided destructor prevents constexpr copy/move assignment

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#31563]
|  |  |
| --- | --- |
| Bugzilla Link | [32215](https://llvm.org/bz32215) |
| Version | trunk |
| OS | All |
| Blocks | llvm/llvm-project#31554  |
| CC | @JonasToth |

## Extended Description 
Uncommenting the defaulted destructor in the template specialization prevents the copy assignment and move assignment operators from being constexpr:

// Type your code here, or load an example.
template <int NoRows, int NoCols>
struct bounds {
  constexpr bounds()              = default;
  constexpr bounds(bounds const&) = default;
  constexpr bounds(bounds&&)      = default;
  constexpr bounds& operator=(bounds const&) = default;
  constexpr bounds& operator=(bounds&&) = default;
  ~bounds()                             = default;

  constexpr bounds(int , int ) {}
};

template <>
struct bounds<-1, -1> {
  int a{}, b{};
  constexpr bounds()              = default;
  constexpr bounds(bounds const&) = default;
  constexpr bounds(bounds&&)      = default;
  constexpr bounds& operator=(bounds const&) = default;
  constexpr bounds& operator=(bounds&&) = default;
  //~bounds()                             = default;

  constexpr bounds(int a_, int b_) :a(a_), b(b_) {}
};

**Comment by carlosgalvezp** [comment]
Both examples compile with Clang trunk now, closing.
