### ISSUE TITLE
clang-format formats valid c code into invalid one (incorrectly separating the token "<:" into "<" and ":")

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#31592]
|  |  |
| --- | --- |
| Bugzilla Link | [32244](https://llvm.org/bz32244) |
| Version | trunk |
| OS | Windows NT |

## Extended Description 

```
$ clang-format -version
clang-format version 5.0.0 (trunk 296436)
```

```
$ clang-format good.c | tee bad.c
main(int argc, char *argv< : :>)<% %>
$ clang-trunk -w good.c 
$ clang-trunk -w bad.c
bad.c:1:26: error: expected ')'
main(int argc, char *argv< : :>)<% %>
                         ^
bad.c:1:5: note: to match this '('
main(int argc, char *argv< : :>)<% %>
    ^
bad.c:1:1: error: second parameter of 'main' (argument array) must be of type 'char **'
main(int argc, char *argv< : :>)<% %>
^
2 errors generated.
```

`$ cat good.c`:
```
main(int argc, char *argv<: :>)<% %>
```

**Comment by mydeveloperday** [comment]
2021.12.17 clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 55d392cc30fb36e6361ba71f4b568c093f8b23f3) 

This is still an issue, the correct should be: (I think)

`main(int argc, char *argv<: :>)<% %>`

not

`main(int argc, char *argv< : :>)<% %>`

I reproduced with .clang-format of

`BasedOnStyle: LLVM`
