### ISSUE TITLE
inconsistent sjlj choice between CodeGen and MC assertion

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31605]
|  |  |
| --- | --- |
| Bugzilla Link | [32257](https://llvm.org/bz32257) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @compnerd,@TNorthover |

## Extended Description 
$ cat main.c
#include <stdio.h>
int main(void) { return (0); }

$ ./clang -target armv8-unknown-freebsd main.c -ccc-gcc-name aarch64-linux-gnu-gcc -fuse-ld=lld -o main
clang-4.0: ../lib/Target/ARM/ARMSubtarget.cpp:144: void llvm::ARMSubtarget::initializeEnvironment(): Assertion `(!TM.getMCAsmInfo() || (TM.getMCAsmInfo()->getExceptionHandlingType() == ExceptionHandling::SjLj) == UseSjLjEH) && "inconsistent sjlj choice between CodeGen and MC"' failed.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 6: https://cexplorer.testlabs.pro/z/a9KMse
