### ISSUE TITLE
There's no way to build with LLVM_ENABLE_DUMP

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31631]
|  |  |
| --- | --- |
| Bugzilla Link | [32283](https://llvm.org/bz32283) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Currently, there is no way to actually define LLVM_ENABLE_DUMP. This macro is used to add all the dump() methods in a Release build. So this is currently impossible.

I suggest exposing it as a cmake option.

**Comment by arsenm** [comment]
This is a cmake option
