### ISSUE TITLE
Wrong resolving boost::variant template arguments by formatters API

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31647]
|  |  |
| --- | --- |
| Bugzilla Link | [32300](https://llvm.org/bz32300) |
| Version | 3.9 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
1. Use C++ code:

#include <boost/variant>
#include <vector>
#include <string>

template<typename ParentType>
struct Example
{
    using Variant = boost::variant<int, std::string, std::vector<ParentType>>;
};

int main()
{
    Example<float>::Variant ex(std::string("string"));
    Example<float>::Variant ex2(10);
    return ex.which() == ex2.which();
}

2. Use formatter for boost::variant:

import lldb
import lldb.formatters.Logger

def get_template_arg(valobj, i):
    valobj_type = valobj.GetType().GetUnqualifiedType()
    if valobj_type.IsReferenceType():
        valobj_type = valobj_type.GetDereferencedType()
    if valobj_type.GetNumberOfTemplateArguments() > i:
        data_type = valobj_type.GetTemplateArgumentType(i)
    else:
        data_type = None
    return data_type

class BoostVariantSynthProvider:
    def __init__(self, valobj, dict):
        self.val_obj = valobj
        self.value = None
        self.update()

    def num_children(self):
        return 1

    def has_children(self):
        return True

    def get_child_index(self, name):
        if name == "value":
            return 0

        return -1

    def get_child_at_index(self, index):
        if index == 0:
            return self.value

        return None

    def update(self):
        type_index = self.val_obj.GetChildMemberWithName("which_").GetValueAsUnsigned()
        element_type = get_template_arg(self.val_obj, type_index)
        self.value = self.val_obj.GetChildMemberWithName("storage_").GetChildMemberWithName("data_"). \
            GetChildMemberWithName("buf").CreateChildAtOffset("value", 0, element_type)

Actual:
GetNumberOfTemplateArguments() returns 1 for Example<float>::Variant type and get_template_arg returns 'None'
Expected:
GetNumberOfTemplateArguments() should return 3 for Example<float>::Variant type and get_template_arg should returns std::string type

**Comment by dprogm** [comment]
Are there any updates on this? I am experiencing the same issue when I am trying to retrieve the argument type via `GetTemplateArgumentType()`. The function `GetTemplateArgumentKind()` returns `eTemplateArgumentKindType` for the first type at index 0 and `eTemplateArgumentKindPack` for the second type at index 1. Furthermore the type I am trying to debug has 3 template arguments but `GetNumberOfTemplateArguments()` only return 2. It seems that `GetTemplateArgumentType()` isn't implemented for the enum value `eTemplateArgumentKindPack`. I have found a [gist for the type boost variant](https://gist.github.com/v0lat1le/f1b6b350b81a6e56d3eee0215642aec9) but here the problem with the statement `lldb.target.FindFirstType(valueTypeName)` in line 67 is that the target is None. Maybe someone has an explanation for this too.

I would be very happy if someone can give me an advice. A solution for the general case of variadic templates would be very helpful.

**Comment by Michael137** [comment]
SBAPI parameter pack support was added in: https://reviews.llvm.org/D51387
