### ISSUE TITLE
clang-format incorrectly puts space before and after * in local function pointer decl

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#31659]
|  |  |
| --- | --- |
| Bugzilla Link | [32312](https://llvm.org/bz32312) |
| Version | unspecified |
| OS | Windows NT |

## Extended Description 
Not sure if this is a regression, but
```cpp
void f() {
  void (*SetRow)(uint8* dst, uint8 value, int width) = SetRow_C;
}
```
gets turned into

C:\src\chrome\src>buildtools\win\clang-format.exe temp.cc
```cpp
void f() {
  void (*SetRow)(uint8 * dst, uint8 value, int width) = SetRow_C;
}
```

**Comment by rymiel** [comment]
Differential: https://reviews.llvm.org/D135707
