### ISSUE TITLE
llvm-tblgen crashes when compiling llvm 4.0 with gcc 6.2.1

### ISSUE THREAD

**Issue by blastrock** [llvm/llvm-project#31650]
|  |  |
| --- | --- |
| Bugzilla Link | [32303](https://llvm.org/bz32303) |
| Version | 4.0 |
| OS | Linux |
| Attachments | [Backtrace of the crash](https://user-images.githubusercontent.com/92601857/143755242-0df3986e-1cbe-46f0-af72-dc31910e0676.gz) |

## Extended Description 

Hi,

I'm trying to compile the latest version of llvm. I have checked out the release_40 branch in my worktree, but llvm-tblgen keeps crashing.

I am using debian testing with GCC 6.2.1

To reproduce the crash:

cmake -DLLVM_TARGETS_TO_BUILD=X86 -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja ..
ninja lib/Target/X86/X86GenRegisterInfo.inc # to go straight to the crash
...
0.	Program arguments: /home/philippe/packages/llvm/build/bin/llvm-tblgen -gen-register-info -I /home/philippe/packages/llvm/lib/Target/X86 -I /home/philippe/packages/llvm/include -I /home/philippe/packages/llvm/lib/Target /home/philippe/packages/llvm/lib/Target/X86/X86.td -o /home/philippe/packages/llvm/build/lib/Target/X86/X86GenRegisterInfo.inc.tmp 
Segmentation fault (core dumped)

I am attaching the full backtrace

The crash does not occur when building in debug.

**Comment by arsenm** [comment]
Old build issue
