### ISSUE TITLE
DominatorTree is not up to date!

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31770]
|  |  |
| --- | --- |
| Bugzilla Link | [32423](https://llvm.org/bz32423) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Running

clang -cc1 -emit-llvm -fprofile-instrument=clang -O2

on

struct foo {
  foo *bah;
};
struct bar {
  bool operator!=(const bar &xxx)  {
    return xyz != xxx.xyz;
  }
  bar(foo **abc, foo *cur) : abc(abc), xyz(cur) {}
  foo **abc;
  foo *xyz;
  bar operator++(int) {
    bar tmp = *this;
    if (xyz != 0)
      xyz = xyz->bah;
    while (xyz == 0)
      xyz = *abc;
    return tmp;
  }
};
foo **abcs;
int eee;
bar Begin() {
  foo **buk = abcs;
  return bar(buk, *buk);
}
bar End() {
  foo **term = abcs + eee;
  return bar(term, *term);
}
void zed() {
  for (bar it = Begin(); it != End(); it++)
    ;
}

crashes with

DominatorTree is not up to date!

Tested with r297719

**Comment by arsenm** [comment]
Doesn't reproduce and comment says "maybe fixed"
