### ISSUE TITLE
[ppc] redundant zero extension when returning bool value

### ISSUE THREAD

**Issue by weiguozhi** [llvm/llvm-project#31789]
|  |  |
| --- | --- |
| Bugzilla Link | [32442](https://llvm.org/bz32442) |
| Version | trunk |
| OS | Linux |
| CC | @hfinkel |

## Extended Description 
Compile the following code with options -m64 -O2 -mvsx -mcpu=power8

bool foo(int i, int* p) {
  if (i==0)
    return false;

  *p = i;
  return true;
}

LLVM generates:

_Z3fooiPi:                              # @&#8203;_Z3fooiPi
.Lfunc_begin0:
# BB#0:                                 # %entry
        cmplwi   3, 0
        beq      0, .LBB0_2
# BB#1:                                 # %if.end
        stw 3, 0(4)
        li 3, 1
        clrldi   3, 3, 32           // redundant
        blr
.LBB0_2:
        li 3, 0
        clrldi   3, 3, 32           // redundant
        blr

The problem is when PPCBoolRetToInt.cpp converts the old the old cmp/isel behavior into today's integer operation, it uses  i32 type, on ppc64, it needs to be zero extended to 64bit before return. We should use i64 on ppc64 and i32 on ppc32.

**Comment by chenzheng1030** [comment]
https://godbolt.org/z/9s66334jj 

No unnecessary zero extension for li result.
