### ISSUE TITLE
APFloat unit tests fail on some AArch64 platforms

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#31795]
|  |  |
| --- | --- |
| Bugzilla Link | [32448](https://llvm.org/bz32448) |
| Version | 3.9 |
| OS | Linux |
| Attachments | [Test output](https://user-images.githubusercontent.com/143300/143755335-390c18a4-6633-4c53-b6f3-a6f27c3986a4.gz) |
| CC | @dwblaikie,@ekatz,@sunfishcode |

## Extended Description 

I'm seeing these failures on just one AArch64 system that I've tested.  Other AArch64 systems seem to work fine.  I'm still trying to get detailed CPU information for the failing system.

**Comment by arsenm** [comment]
Old build issue
