### ISSUE TITLE
Real warning produced by definition of _cvtss_sh in C++

### ISSUE THREAD

**Issue by 69d80b74-475e-435b-96f3-4fe863603a63** [llvm/llvm-project#31838]
|  |  |
| --- | --- |
| Bugzilla Link | [32491](https://llvm.org/bz32491) |
| Resolution | FIXED |
| Resolved on | Apr 03, 2017 22:14 |
| Version | trunk |
| OS | Linux |
| CC | @topperc,@DougGregor,@RKSimon |

## Extended Description 
With the following code in C++:

    b16 = _cvtss_sh(f, 0);

The compiler produces:

/qfloat16.h:119:11: error: compound literals are a C99-specific feature [-Werror,-Wc99-extensions]
    b16 = _cvtss_sh(f, 0);
          ^
/opt/clang/lib64/clang/5.0.0/include/f16cintrin.h:76:55: note: expanded from macro '_cvtss_sh'
  ((unsigned short)(((__v8hi)__builtin_ia32_vcvtps2ph((__v4sf){a, 0, 0, 0}, \
                                                      ^

This warning is caused by the macro definition in f16cintrin.h as supplied by Clang.

Please either suppress the warning when it's produced by a macro created in a Clang-supplied file or fix the file not to produce a warning in C++ mode.

Reproduced with Clang 3.9.1 and 5.0 (trunk)

**Comment by yupinov** [comment]
The bug was reintroduced 4 years ago in c63386.

**Comment by topperc** [comment]
Re-fixed in ff80dc85449307d90e5276cd8f41825ace9b8594
