### ISSUE TITLE
AMDGPU tests just started to fail on Debian unstable

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#31830]
|  |  |
| --- | --- |
| Bugzilla Link | [32483](https://llvm.org/bz32483) |
| Version | trunk |
| OS | Linux |
| Depends On | llvm/llvm-project#30958  |
| CC | @zmodem,@arsenm,@tstellar |

## Extended Description 
+++ This bug was initially created as a clone of Bug #&#8203;31610 +++

Starting after svn299239, a bunch of AMDGPU started to fail

Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.
FAIL: LLVM :: MC/AMDGPU/code-object-metadata-kernel-args.s (13484 of 20170)
******************** TEST 'LLVM :: MC/AMDGPU/code-object-metadata-kernel-args.s' FAILED ********************
Script:
--
/build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/llvm-mc -triple=amdgcn-amd-amdhsa -mcpu=gfx700 -show-encoding /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-args.s | /build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/FileCheck --check-prefix=CHECK --check-prefix=GFX700 /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-args.s
/build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/llvm-mc -triple=amdgcn-amd-amdhsa -mcpu=gfx800 -show-encoding /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-args.s | /build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/FileCheck --check-prefix=CHECK --check-prefix=GFX800 /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-args.s
/build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/llvm-mc -triple=amdgcn-amd-amdhsa -mcpu=gfx900 -show-encoding /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-args.s | /build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/FileCheck --check-prefix=CHECK --check-prefix=GFX900 /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-args.s
--
Exit Code: 1

Command Output (stderr):
--
/build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-args.s:6:11: error: expected string not found in input
// CHECK: Version: [ 1, 0 ]
          ^
<stdin>:4:1: note: scanning from here
---
^
<stdin>:5:1: note: possible intended match here
Version: 
^

--

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.
FAIL: LLVM :: MC/AMDGPU/code-object-metadata-kernel-debug-props.s (13486 of 20170)
******************** TEST 'LLVM :: MC/AMDGPU/code-object-metadata-kernel-debug-props.s' FAILED ********************
Script:
--
/build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/llvm-mc -triple=amdgcn-amd-amdhsa -mcpu=gfx700 -show-encoding /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-debug-props.s | /build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/FileCheck --check-prefix=CHECK --check-prefix=GFX700 /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-debug-props.s
/build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/llvm-mc -triple=amdgcn-amd-amdhsa -mcpu=gfx800 -show-encoding /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-debug-props.s | /build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/FileCheck --check-prefix=CHECK --check-prefix=GFX800 /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-debug-props.s
/build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/llvm-mc -triple=amdgcn-amd-amdhsa -mcpu=gfx900 -show-encoding /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-debug-props.s | /build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/FileCheck --check-prefix=CHECK --check-prefix=GFX900 /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-debug-props.s
--
Exit Code: 1

Command Output (stderr):
--
/build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-debug-props.s:6:11: error: expected string not found in input
// CHECK: Version: [ 1, 0 ]
          ^
<stdin>:4:1: note: scanning from here
---
^
<stdin>:5:1: note: possible intended match here
Version: 
^

--

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.
FAIL: LLVM :: MC/AMDGPU/code-object-metadata-kernel-code-props.s (13487 of 20170)
******************** TEST 'LLVM :: MC/AMDGPU/code-object-metadata-kernel-code-props.s' FAILED ********************
Script:
--
/build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/llvm-mc -triple=amdgcn-amd-amdhsa -mcpu=gfx700 -show-encoding /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-code-props.s | /build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/FileCheck --check-prefix=CHECK --check-prefix=GFX700 /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-code-props.s
/build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/llvm-mc -triple=amdgcn-amd-amdhsa -mcpu=gfx800 -show-encoding /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-code-props.s | /build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/FileCheck --check-prefix=CHECK --check-prefix=GFX800 /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-code-props.s
/build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/llvm-mc -triple=amdgcn-amd-amdhsa -mcpu=gfx900 -show-encoding /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-code-props.s | /build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/FileCheck --check-prefix=CHECK --check-prefix=GFX900 /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-code-props.s
--
Exit Code: 1

Command Output (stderr):
--
/build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-code-props.s:6:11: error: expected string not found in input
// CHECK: Version: [ 1, 0 ]
          ^
<stdin>:4:1: note: scanning from here
---
^
<stdin>:5:1: note: possible intended match here
Version: 
^

--

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.
FAIL: LLVM :: MC/AMDGPU/code-object-metadata-kernel-attrs.s (13488 of 20170)
******************** TEST 'LLVM :: MC/AMDGPU/code-object-metadata-kernel-attrs.s' FAILED ********************
Script:
--
/build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/llvm-mc -triple=amdgcn-amd-amdhsa -mcpu=gfx700 -show-encoding /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-attrs.s | /build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/FileCheck --check-prefix=CHECK --check-prefix=GFX700 /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-attrs.s
/build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/llvm-mc -triple=amdgcn-amd-amdhsa -mcpu=gfx800 -show-encoding /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-attrs.s | /build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/FileCheck --check-prefix=CHECK --check-prefix=GFX800 /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-attrs.s
/build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/llvm-mc -triple=amdgcn-amd-amdhsa -mcpu=gfx900 -show-encoding /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-attrs.s | /build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/FileCheck --check-prefix=CHECK --check-prefix=GFX900 /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-attrs.s
--
Exit Code: 1

Command Output (stderr):
--
/build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/code-object-metadata-kernel-attrs.s:6:11: error: expected string not found in input
// CHECK: Version: [ 1, 0 ]
          ^
<stdin>:4:1: note: scanning from here
---
^
<stdin>:5:1: note: possible intended match here
Version: 
^

--

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.
FAIL: LLVM :: MC/AMDGPU/hsa.s (13498 of 20170)
******************** TEST 'LLVM :: MC/AMDGPU/hsa.s' FAILED ********************
Script:
--
/build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/llvm-mc -triple amdgcn--amdhsa -mcpu=kaveri -show-encoding /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/hsa.s | /build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/FileCheck /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/hsa.s --check-prefix=ASM
/build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/llvm-mc -filetype=obj -triple amdgcn--amdhsa -mcpu=kaveri -show-encoding /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/hsa.s | /build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/llvm-readobj -symbols -s -sd | /build/llvm-toolchain-snapshot-5.0~svn299142/build-llvm/./bin/FileCheck /build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/hsa.s --check-prefix=ELF
--
Exit Code: 1

Command Output (stderr):
--
/build/llvm-toolchain-snapshot-5.0~svn299142/test/MC/AMDGPU/hsa.s:48:9: error: expected string not found in input
// ASM: Version: [ 3, 0 ]
        ^
<stdin>:14:1: note: scanning from here
---
^
<stdin>:15:1: note: possible intended match here
Version: 
^
[...]

********************
Failing Tests (11):
    LLVM :: CodeGen/AMDGPU/code-object-metadata-from-llvm-ir-full.ll
    LLVM :: CodeGen/AMDGPU/code-object-metadata-invalid-ocl-version-1.ll
    LLVM :: CodeGen/AMDGPU/code-object-metadata-invalid-ocl-version-2.ll
    LLVM :: CodeGen/AMDGPU/code-object-metadata-invalid-ocl-version-3.ll
    LLVM :: CodeGen/AMDGPU/code-object-metadata-kernel-code-props.ll
    LLVM :: CodeGen/AMDGPU/code-object-metadata-kernel-debug-props.ll
    LLVM :: MC/AMDGPU/code-object-metadata-kernel-args.s
    LLVM :: MC/AMDGPU/code-object-metadata-kernel-attrs.s
    LLVM :: MC/AMDGPU/code-object-metadata-kernel-code-props.s
    LLVM :: MC/AMDGPU/code-object-metadata-kernel-debug-props.s
    LLVM :: MC/AMDGPU/hsa.s

**Comment by arsenm** [comment]
Old ticket
