### ISSUE TITLE
[java] missing BraceWrapping: AfterInterface option

### ISSUE THREAD

**Issue by ed628777-e86e-4544-8e44-c6f20c9fc656** [llvm/llvm-project#31850]
|  |  |
| --- | --- |
| Bugzilla Link | [32503](https://llvm.org/bz32503) |
| Version | trunk |
| OS | Windows NT |

## Extended Description 
As far as I can tell, there's no way to achieve this formatting:

```
public interface Foo
{
  void bar();
}
```

This always gets reformatted to:

```
public interface Foo {
  void bar();
}
```

For both classes and enums, this can be controlled with `AfterClass` and `AfterEnum` respectively. An `AfterInterface` setting seems to be missing however. None of the non-custom `BraceBreakingStyle` options seem to help either.

clang-format version: 5.0.0 (1cd6beccb6bb876db3bbfa763e8979)

**Comment by mydeveloperday** [comment]
After the introduction of C# support, this came under the AfterClass option

The following will give you the format you desire

```
Language: Java
BasedOnStyle: LLVM
BreakBeforeBraces: Custom
BraceWrapping:
    AfterClass: true
```

I am closing this issue as fixed, please reopen if still an issue
