### ISSUE TITLE
Inline ASM: Assertion failed: isLegalInHWReg(N->getValueType(ResNo)) && "Unsupported SoftenFloatRes opcode!"

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31859]
|  |  |
| --- | --- |
| Bugzilla Link | [32512](https://llvm.org/bz32512) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @jmolloy |

## Extended Description 
target triple = "aarch64-none-linux-gnu"
define void @&#8203;tinkywinky(i64 %dipsy) #&#8203;0 { 
	call void asm "", "r,~{d1}"(i64 %dipsy)  
	ret void
}

attributes #&#8203;0 = { "target-features"="-fp-armv8" }

> .\llc.exe D:\littlehelpers\pcg\mismatch.ll

Assertion failed: isLegalInHWReg(N->getValueType(ResNo)) && "Unsupported SoftenFloatRes opcode!", file C:\Users\fluttershy\work\llvm\lib\CodeGen\SelectionDAG\LegalizeFloatTypes.cpp, line 66
Wrote crash dump file "C:\Users\FLUTTE~1\AppData\Local\Temp\llc.exe-fa9982.dmp"

**Comment by john-brawn-arm** [comment]
No longer crashes with latest trunk. Looks like the current behaviour is that unrecognised registers (including float registers when they're not present but also completely fictitious registers) are just ignored. Closing.
