### ISSUE TITLE
modernize-use-using problems: template types, missing fix-it, type modification

### ISSUE THREAD

**Issue by EugeneZelenko** [llvm/llvm-project#31864]
|  |  |
| --- | --- |
| Bugzilla Link | [32517](https://llvm.org/bz32517) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
Krystyna, dziękuję bardzo for fixes, but there are still some problem with check on LLVM code base.

I think fixes in LLVM code will simplify further check debugging, but not everyone is happy about them :-(

Template parameters substituted:

include/llvm/ADT/SmallVector.h:102:3: warning: use 'using' instead of 'typedef' [modernize-use-using]
  typedef T *iterator;
  ^
  using iterator = void **
include/llvm/ADT/SmallVector.h:103:3: warning: use 'using' instead of 'typedef' [modernize-use-using]
  typedef const T *const_iterator;
  ^
  using const_iterator = void *const *

Original type was modified:

/grid/cic/nsd-farm2/data/zelenko/LLVM.svn/llvm-svn.src/include/llvm/IR/ValueMap.h:104:3: warning: use 'using' instead of 'typedef' [modernize-use-using]
  typedef unsigned size_type;
  ^
  using size_type = unsigned int

No fix-it provided:

include/llvm/Support/Casting.h:170:3: warning: use 'using' instead of 'typedef' [modernize-use-using]
  typedef typename cast_retty<To, SimpleFrom>::ret_type ret_type;
  ^

include/llvm/Support/Endian.h:266:1: warning: use 'using' instead of 'typedef' [modernize-use-using]
typedef detail::packed_endian_specific_integral
^

include/llvm/CodeGen/AsmPrinter.h:112:3: warning: use 'using' instead of 'typedef' [modernize-use-using]
  typedef std::pair<const GlobalVariable *, unsigned> GOTEquivUsePair;
  ^

Is it correct? http://en.cppreference.com/w/cpp/language/type_alias doesn't mention arrays, so may be such typedefs should be skipped?

include/llvm/ADT/STLExtras.h:225:3: warning: use 'using' instead of 'typedef' [modernize-use-using]
  typedef char yes[1];
  ^
include/llvm/ADT/STLExtras.h:226:3: warning: use 'using' instead of 'typedef' [modernize-use-using]
  typedef char no[2];
  ^

**Comment by PiotrZSL** [comment]
This were fixed by b34b6ffa9d4aae16272cbdbf508134f98b4647d4.
