### ISSUE TITLE
Duplicate "no member named 'x' in namespace 'y'" error message

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#31868]
|  |  |
| --- | --- |
| Bugzilla Link | [32521](https://llvm.org/bz32521) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
A duplicate error message is emitted involving missing namespace members in template parameters. Reproduces with the following:

  template <typename X> class Qux {};
  namespace foo {}
  void bar(Qux<foo::baz> x) {}

Which emits two identical errors like so:

  % clang++ -x c++ -fsyntax-only foo.cpp
  foo.cpp:3:19: error: no member named 'baz' in namespace 'foo'
  void bar(Qux<foo::baz> x) {}
               ~~~~~^
  foo.cpp:3:19: error: no member named 'baz' in namespace 'foo'
  void bar(Qux<foo::baz> x) {}
               ~~~~~^
  2 errors generated.

**Comment by wheatman** [comment]
This seems to have been fixed between 10.0.1 and 11.0.0
https://godbolt.org/z/xYqszzYKa

for reference
code 
```
 template <typename X> class Qux {};
  namespace foo {}
  void bar(Qux<foo::baz> x) {}
```
