### ISSUE TITLE
request for adding function note to force emission of stack frame pointer

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#3186]
|  |  |
| --- | --- |
| Bugzilla Link | [2814](https://llvm.org/bz2814) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I'd like to request that a new function note be added, which forces the output of a stack frame in the "noted" function.

Currently there are only hacks to accomplish this, like calling llvm.unwind.init somewhere. I need to guarantee that the stack frame is emitted (ie. EBP on x86), for functions using inline asm, and currently the unwind.init hack is working well, however, It'd be much nicer if we could just put a note.

I asked about this in the IRC channel a while ago but was told to basically wait a bit as there was going to be a proposal for this stuff (function notes) soon, since it's implemented now, now feels like a good time to suggest its addition. Would be nice to get it into the 2.4 release.

**Comment by arsenm** [comment]
The "frame-pointer" attribute now exists
