### ISSUE TITLE
When using C-bindings, on x86_64 ELF, fails to generate the correct instruction for external call

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#31975]
|  |  |
| --- | --- |
| Bugzilla Link | [32628](https://llvm.org/bz32628) |
| Version | 4.0 |
| OS | Linux |
| Attachments | [Code to reproduce the problem](https://user-images.githubusercontent.com/60944935/143755420-f4c63da0-d9f4-4243-a425-ba0b9fa8ee24.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Debian 8, using llvm 4.0, as well as the trunk, when running the attached code I get a segfault.

It looks like the generated call is of the near, ip-relative type, and when the symbol is resolved, the offset is incorrect, as it can't fit into 32-bit allowed for that type of instruction.

$ clang -g min.c `llvm-config --cflags --ldflags --system-libs --libs core orcjit native` -rdynamic  -lstdc++ -o min
$ gdb min
$ (gdb) run
$ Program received signal SIGSEGV, Segmentation fault.
$ 0x00007ffff7ff0001 in ?? ()
$ (gdb) x/i 0x00007ffff7ff0001
$ => 0x7ffff7ff0001:	callq  0x800000edbd50

**Comment by lhames** [comment]
Closing as stale. RuntimeDyld still requires specific code and relocation models, and the original issue was likely due to that. The solution is to move to JITLink, which we're in the process of doing.
