### ISSUE TITLE
Assert "Default argument is not yet instantiated!" after clang::CXXRecordDecl::getODRHash()

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#31987]
|  |  |
| --- | --- |
| Bugzilla Link | [32640](https://llvm.org/bz32640) |
| Version | unspecified |
| OS | Linux |
| Attachments | [preprocessed source](https://user-images.githubusercontent.com/1148786/143755426-2a220697-2ed2-4103-a8a7-e37fbb7edb35.gz), [invocation](https://user-images.githubusercontent.com/1148786/143755427-fb7ac3d0-8a75-4b2b-822d-3f430fa4da86.gz) |
| CC | @pogo59,@Weverything |

## Extended Description 
When building Chromium on Mac with r300006:

FAILED: obj/base/base/precompile.h-mm.gch 
export DEVELOPER_DIR=/b/c/b/ClangToTMac/src/build/mac_files/Xcode.app;  ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/base/base/precompile.h-mm.gch.d -DSYSTEM_NATIVE_UTF8 -DV8_DEPRECATION_WARNINGS -DNO_TCMALLOC -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=\"300006\" -DCR_XCODE_VERSION=0511 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DCOMPONENT_BUILD -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBASE_IMPLEMENTATION -I../.. -Igen -fno-strict-aliasing -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -fcolor-diagnostics -arch x86_64 -Wall -Werror -Wextra -Wpartial-availability -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -fno-omit-frame-pointer -g1 -isysroot /b/c/b/ClangToTMac/src/build/mac_files/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.9 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wno-char-subscripts -Wexit-time-destructors -Wexit-time-destructors -O2 -fvisibility-inlines-hidden -std=c++11 -stdlib=libc++ -fobjc-call-cxx-cdtors -Wobjc-missing-property-synthesis -fno-rtti -fno-exceptions -x objective-c++-header -c ../../build/precompile.h -o obj/base/base/precompile.h-mm.gch
Assertion failed: (!hasUninstantiatedDefaultArg() && "Default argument is not yet instantiated!"), function getDefaultArg, file /b/c/b/ClangToTMac/src/third_party/llvm/tools/clang/lib/AST/Decl.cpp, line 2424.
0  clang-5.0                0x0000000103af73f8 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  clang-5.0                0x0000000103af7af6 llvm::sys::PrintStackTraceOnErrorSignal(llvm::StringRef, bool) + 838
2  libsystem_platform.dylib 0x00007fff9d78fbba _sigtramp + 26
3  libsystem_platform.dylib 0x0000000000000001 _sigtramp + 1653015649
4  libsystem_c.dylib        0x00007fff9d616420 abort + 129
5  libsystem_c.dylib        0x00007fff9d5dd893 basename_r + 0
6  clang-5.0                0x00000001055ab93d clang::ParmVarDecl::getDefaultArg() + 109
7  clang-5.0                0x00000001056a9299 clang::ODRHash::AddType(clang::Type const*) + 409
8  clang-5.0                0x00000001056a97a2 clang::ODRHash::AddType(clang::Type const*) + 1698
9  clang-5.0                0x00000001056a902f clang::ODRHash::AddCXXRecordDecl(clang::CXXRecordDecl const*) + 463
10 clang-5.0                0x00000001055d0276 clang::CXXRecordDecl::getODRHash() const + 294
11 clang-5.0                0x0000000104b0aeb9 clang::ASTRecordWriter::AddCXXDefinitionData(clang::CXXRecordDecl const*) + 1753
12 clang-5.0                0x0000000104b25d5a clang::ASTDeclWriter::VisitCXXRecordDecl(clang::CXXRecordDecl*) + 314
13 clang-5.0                0x0000000104b271e0 clang::ASTDeclWriter::VisitClassTemplateSpecializationDecl(clang::ClassTemplateSpecializationDecl*) + 128
14 clang-5.0                0x0000000104b1c806 clang::ASTDeclWriter::Visit(clang::Decl*) + 22
15 clang-5.0                0x0000000104b301ab clang::ASTWriter::WriteDecl(clang::ASTContext&, clang::Decl*) + 459
16 clang-5.0                0x0000000104b0799a clang::ASTWriter::WriteASTCore(clang::Sema&, llvm::StringRef, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, clang::Module*) + 12154
17 clang-5.0                0x0000000104b0489c clang::ASTWriter::WriteAST(clang::Sema&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, clang::Module*, llvm::StringRef, bool) + 652
18 clang-5.0                0x0000000104b46d0b clang::PCHGenerator::HandleTranslationUnit(clang::ASTContext&) + 251
19 clang-5.0                0x000000010421833c clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) + 44
20 clang-5.0                0x0000000104959da5 clang::ParseAST(clang::Sema&, bool, bool) + 469
21 clang-5.0                0x00000001041d65ac clang::FrontendAction::Execute() + 76
22 clang-5.0                0x0000000104192931 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 1217
23 clang-5.0                0x0000000104237ba2 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 4914
24 clang-5.0                0x000000010235acac cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 1388
25 clang-5.0                0x0000000102359373 main + 11875
26 libdyld.dylib            0x00007fff9d582255 start + 1
27 libdyld.dylib            0x000000000000008f start + 1655168571

**Comment by Endilll** [comment]
Can't reproduce with Clang 4.0, 4.0.1, 5.0, and 16. I assume this was fixed by r300074.
https://godbolt.org/z/7cPd6aave
