### ISSUE TITLE
Clang hangs compiling ARM inline assembly, with instruction on unsupported target

### ISSUE THREAD

**Issue by 130b3519-e3e6-4fca-9572-f7b920a99446** [llvm/llvm-project#32001]
|  |  |
| --- | --- |
| Bugzilla Link | [32654](https://llvm.org/bz32654) |
| Version | unspecified |
| OS | Linux |
| CC | @rovka,@jmolloy |

## Extended Description 
$ cat test.cc
float sqrtf(float x) {
  __asm__("vsqrt.f32 %0, %1"
          : "=t"(x)
          : "t"(x));
  return x;
}

$ ~/llvm/build/bin/clang --target=armv5-linux-gnueabi test.c -S -o -
        .text
        .syntax unified
        .eabi_attribute 67, "2.09"      @ Tag_conformance
        .cpu    arm10tdmi
        .eabi_attribute 6, 3    @ Tag_CPU_arch
        .eabi_attribute 8, 1    @ Tag_ARM_ISA_use
        .eabi_attribute 17, 1   @ Tag_ABI_PCS_GOT_use
        .eabi_attribute 20, 1   @ Tag_ABI_FP_denormal
        .eabi_attribute 21, 1   @ Tag_ABI_FP_exceptions
        .eabi_attribute 23, 3   @ Tag_ABI_FP_number_model
        .eabi_attribute 34, 0   @ Tag_CPU_unaligned_access
        .eabi_attribute 24, 1   @ Tag_ABI_align_needed
        .eabi_attribute 25, 1   @ Tag_ABI_align_preserved
        .eabi_attribute 38, 1   @ Tag_ABI_FP_16bit_format
        .eabi_attribute 18, 4   @ Tag_ABI_PCS_wchar_t
        .eabi_attribute 26, 2   @ Tag_ABI_enum_size
        .eabi_attribute 14, 0   @ Tag_ABI_PCS_R9_use
        .file   "test3.c"
clang-5.0: /usr/local/google/home/yikong/llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:392: void getCopyToParts(llvm::SelectionDAG &, const llvm::SDLoc &, llvm::SDValue, llvm::SDValue *, unsigned int, llvm::MVT, const llvm::Value *, ISD::NodeType): Assertion `DAG.getTargetLoweringInfo().isTypeLegal(PartVT) && "Copying to an illegal type!"' failed.
(hangs)

vsqrt instruction does not exist for armv5, this should throw an error instead of compiler internal assertion failure and hanging.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 14: https://godbolt.org/z/nfchcc4j8
