### ISSUE TITLE
clang::tidy::utils::parseHeaderFileExtensions() bug: fails to parse HeaderFileExtensions="h++"

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#32022]
|  |  |
| --- | --- |
| Bugzilla Link | [32675](https://llvm.org/bz32675) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
.clang-tidy contains:

  - key:             google-build-namespaces.HeaderFileExtensions
    value:           'h++'
  - key:             google-global-names-in-headers.HeaderFileExtensions
    value:           'h++'
  - key:             misc-definitions-in-headers.HeaderFileExtensions
    value:           'h++'

when i run clang-tidy on some source, i see:
Invalid header file extension: h++
Invalid header file extension: h++
Invalid header file extension: h++

I don't personally have any such headers, but at least SonarQube has sonar.cpp.file.suffixes setting which does contain h++ in it, so it may exist in the wild.

**Comment by PiotrZSL** [comment]
Looks to be fixed... most probably during last HeaderFileExtensions changes.
closing.
