### ISSUE TITLE
Fix Windows test failures marked with XFAIL: LIBCXX-WINDOWS-FIXME

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#32077]
|  |  |
| --- | --- |
| Bugzilla Link | [32730](https://llvm.org/bz32730) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
This bug is a reminder to fix all tests marked with `XFAIL: LIBCXX-WINDOWS-FIXME`.

Tests with `// XFAIL: LIBCXX-WINDOWS-FIXME` were marked as XFAIL as part of the initial Windows test failure triage and each one needs to be fixed, or the XFAIL needs to be changed to another condition.

Once every usage of LIBCXX-WINDOWS-FIXME has been removed this bug should be closed.

**Comment by mstorsjo** [comment]
Almost 5 years later, all remaining instances of `XFAIL: LIBCXX-WINDOWS-FIXME` are now gone, and the test configs no longer defines this feature, so this issue is finally closed by https://github.com/llvm/llvm-project/commit/7594e236795f695c7cf9336ee24ef76c275d8703.
