### ISSUE TITLE
Assertion failed: (all_of(FrameIndexExprs, [](FrameIndexExpr &FIE) { return FIE.Expr && FIE.Expr->isFragment(); }) && "conflicting locations for variable"), function addMMIEntry, file ../../lib/CodeGen/AsmPrinter/DwarfDebug.h, line 142

### ISSUE THREAD

**Issue by compnerd** [llvm/llvm-project#32075]
|  |  |
| --- | --- |
| Bugzilla Link | [32728](https://llvm.org/bz32728) |
| Version | trunk |
| OS | All |
| Attachments | [reduced.c](https://user-images.githubusercontent.com/63311/143755490-ff0b5c46-44ee-4eba-8744-e7e4d8c2f9ba.gz) |

## Extended Description 

Debug Info will cause an assertion to be triggered here at -O2.  See attached reduced test case.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 5: https://cexplorer.testlabs.pro/z/fofYsK
