### ISSUE TITLE
Allow clang-tidy to load more checkers from an external library/plugin

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#32086]
|  |  |
| --- | --- |
| Bugzilla Link | [32739](https://llvm.org/bz32739) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @bbannier,@chgans,@justincady,@JonasToth,@froydnj,@jbytheway,@stephenhines,@steveire |

## Extended Description 
The goal is to be able to write checkers out of tree, which are specific to to some project or customer, then just load them with: clang-tidy -plugin mychecks.so ...

Or similar

**Comment by glandium** [comment]
Wasn't this fixed by 84f137a590e7de25c4105303e5938c40566c2dfb?

**Comment by PiotrZSL** [comment]
Looks like it was.
