### ISSUE TITLE
Support -fdelete-null-pointer-checks

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#32112]
|  |  |
| --- | --- |
| Bugzilla Link | [32765](https://llvm.org/bz32765) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel |

## Extended Description 
Because gcc ans icc does.

**Comment by arsenm** [comment]
This was added in da08f6ac16b6a53ab25ecb56e1be800c5f0095d9
