### ISSUE TITLE
Polly 4.0.0 fails compiling

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#32128]
|  |  |
| --- | --- |
| Bugzilla Link | [32781](https://llvm.org/bz32781) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
make

[ 66%] Built target PollyISL
[ 66%] Built target Polly
[ 66%] Built target LLVMPolly
[ 66%] Built target polly-isl-test
[ 66%] Linking C shared library ../../../../lib/libPollyPPCG.so
/src/llvm/llvm-4.0.0.src/tools/polly/lib/External/pet/include/pet.h:20:1: error: function ‘pet_options_args’ redeclared as variable
 ISL_ARG_DECL(pet_options, struct pet_options, pet_options_args)
 ^
/src/llvm/llvm-4.0.0.src/tools/polly/lib/External/ppcg/external.c:121:6: note: previously declared here
 void pet_options_args() {
      ^
lto1: fatal error: errors during merging of translation units
compilation terminated.
lto-wrapper: fatal error: /usr/local/bin/cc returned 1 exit status
compilation terminated.
/usr/local/lib/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [tools/polly/lib/External/CMakeFiles/PollyPPCG.dir/build.make:356: lib/libPollyPPCG.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:22407: tools/polly/lib/External/CMakeFiles/PollyPPCG.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by arsenm** [comment]
Old build issue
