### ISSUE TITLE
UNREACHABLE "Couldn't join subrange" in RegisterCoalescer (out-of-tree backend)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#32120]
|  |  |
| --- | --- |
| Bugzilla Link | [32773](https://llvm.org/bz32773) |
| Version | 4.0 |
| OS | Linux |
| Attachments | [llc bugpoint-reduced-simplified.bc  -verify-machineinstrs -debug-only=regalloc 2>log](https://user-images.githubusercontent.com/60944935/143755510-6a66376b-c7d6-4b7e-9aaa-acbe0fbce6fa.gz), [bugpoint-reduced-simplified.bc](https://user-images.githubusercontent.com/60944935/143755511-a12aaa41-b341-49cd-8aa6-9cacff3f77bc.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dstutt,@arsenm |

## Extended Description 

While lowering a small testcase for my out-of-tree target, llc experiences an UNREACHABLE during RegisterCoalescer.  I have not been able to reproduce this with a stock target.  This testcase passes -verify-machineinstrs.

Here's a backtrace of the failure.  I've also attached a log with -debug-only=regalloc

*** Couldn't join subrange!

UNREACHABLE executed at /d/en/johnsoni-0/gctools/llvm/lib/CodeGen/RegisterCoalescer.cpp:2693!
#&#8203;0 0x00000000027395af llvm::sys::PrintStackTrace(llvm::raw_ostream&) /d/en/johnsoni-0/gctools/llvm/lib/Support/Unix/Signals.inc:402:0
#&#8203;1 0x0000000002739971 PrintStackTraceSignalHandler(void*) /d/en/johnsoni-0/gctools/llvm/lib/Support/Unix/Signals.inc:466:0
#&#8203;2 0x0000000002737bce llvm::sys::RunSignalHandlers() /d/en/johnsoni-0/gctools/llvm/lib/Support/Signals.cpp:44:0
#&#8203;3 0x0000000002738f41 SignalHandler(int) /d/en/johnsoni-0/gctools/llvm/lib/Support/Unix/Signals.inc:256:0
#&#8203;4 0x000000396140f7e0 __restore_rt (/lib64/libpthread.so.0+0x396140f7e0)
#&#8203;5 0x0000003960c325e5 __GI_raise (/lib64/libc.so.6+0x3960c325e5)
#&#8203;6 0x0000003960c33dc5 __GI_abort (/lib64/libc.so.6+0x3960c33dc5)
#&#8203;7 0x00000000026d4c42 bindingsErrorHandler(void*, std::string const&, bool) /d/en/johnsoni-0/gctools/llvm/lib/Support/ErrorHandling.cpp:127:0
#&#8203;8 0x0000000001fdbc85 (anonymous namespace)::RegisterCoalescer::joinSubRegRanges(llvm::LiveRange&, llvm::LiveRange&, llvm::LaneBitmask, llvm::CoalescerPair const&) /d/en/johnsoni-0/gctools/llvm/lib/CodeGen/RegisterCoalescer.cpp:2695:0
#&#8203;9 0x0000000001fdc3df (anonymous namespace)::RegisterCoalescer::mergeSubRangeInto(llvm::LiveInterval&, llvm::LiveRange const&, llvm::LaneBitmask, llvm::CoalescerPair&) /d/en/johnsoni-0/gctools/llvm/lib/CodeGen/RegisterCoalescer.cpp:2769:0
#&#8203;10 0x0000000001fdcbd5 (anonymous namespace)::RegisterCoalescer::joinVirtRegs(llvm::CoalescerPair&) /d/en/johnsoni-0/gctools/llvm/lib/CodeGen/RegisterCoalescer.cpp:2832:0
#&#8203;11 0x0000000001fdd174 (anonymous namespace)::RegisterCoalescer::joinIntervals(llvm::CoalescerPair&) /d/en/johnsoni-0/gctools/llvm/lib/CodeGen/RegisterCoalescer.cpp:2892:0
#&#8203;12 0x0000000001fd5fc3 (anonymous namespace)::RegisterCoalescer::joinCopy(llvm::MachineInstr*, bool&) /d/en/johnsoni-0/gctools/llvm/lib/CodeGen/RegisterCoalescer.cpp:1468:0
#&#8203;13 0x0000000001fdd4b6 (anonymous namespace)::RegisterCoalescer::copyCoalesceWorkList(llvm::MutableArrayRef<llvm::MachineInstr*>) /d/en/johnsoni-0/gctools/llvm/lib/CodeGen/RegisterCoalescer.cpp:2962:0
#&#8203;14 0x0000000001fddf32 (anonymous namespace)::RegisterCoalescer::coalesceLocals() /d/en/johnsoni-0/gctools/llvm/lib/CodeGen/RegisterCoalescer.cpp:3087:0
#&#8203;15 0x0000000001fde3a1 (anonymous namespace)::RegisterCoalescer::joinAllIntervals() /d/en/johnsoni-0/gctools/llvm/lib/CodeGen/RegisterCoalescer.cpp:3121:0
#&#8203;16 0x0000000001fde6e2 (anonymous namespace)::RegisterCoalescer::runOnMachineFunction(llvm::MachineFunction&) /d/en/johnsoni-0/gctools/llvm/lib/CodeGen/RegisterCoalescer.cpp:3167:0
#&#8203;17 0x0000000001d28d87 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) /d/en/johnsoni-0/gctools/llvm/lib/CodeGen/MachineFunctionPass.cpp:62:0
...

**Comment by arsenm** [comment]
It's quite impossible to work on this type of issue without a concrete reproducer. Similar failures have been fixed since then
