### ISSUE TITLE
GVN crash at -O3 and -O2 in 32-bit mode (Instruction does not dominate all uses! error in backend: Broken function found, compilation aborted!)

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#32142]
|  |  |
| --- | --- |
| Bugzilla Link | [32795](https://llvm.org/bz32795) |
| Version | unspecified |
| OS | Linux |
| CC | @fhahn,@zygoloid |

## Extended Description 
$ clang-trunk -v
clang version 5.0.0 (trunk 298510)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ clang-trunk -O3 -m32 small.c
Instruction does not dominate all uses!
  %.pre = sext i16 %p1 to i32
  store i32 %.pre, i32* @&#8203;e, align 4, !tbaa !&#8203;6
fatal error: error in backend: Broken function found, compilation aborted!
clang-5.0: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 5.0.0 (trunk 298510)
Target: i386-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
clang-5.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-5.0: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-5.0: note: diagnostic msg: /tmp/small-62a555.c
clang-5.0: note: diagnostic msg: /tmp/small-62a555.sh
clang-5.0: note: diagnostic msg: 

********************
$ cat small.c
short a, i;
int b[6];
int c, e, f, g, h, j;
short d[6];
void
fn1 (short p1)
{
  if (a)
    ;
  else
    f = 2;
  if (f)
    i = h >= p1;
  else
  lbl_1586:
    e = p1;
  for (; g < p1;)
    {
      c = b
	[b
	 [b
	  [b
	   [b
	    [b
	     [b
	      [b
	       [b
		[b
		 [b
		  [b
		   [b
		    [b
		     [b
		      [b
		       [b
			[b
			 [b
			  [b
			   [b
			    [b
			     [b
			      [b
			       [b
				[b
				 [b
				  [b
				   [b
				    [b
				     [b
				      [b
				       [b
					[b
					 [b
					  [b
					   [b
					    [b
					     [b
					      [b
					       [b
						[b
						 [b
						  [b
						   [b
						    [b
						     [b
						      [b
						       [b
							[b
							 [b
							  [b
							   [b
							    [b
							     [b
							      [b
							       [b
								[b
								 [b
								  [b
								   [b
								    [b
								     [b
								      [b
								       [b
									[b
									 [b
									  [b
									   [b
									    [b
									     [b
									      [b
									       [b
										[b
										 [b
										  [b
										   [b
										    [b
										     [b
										      [b
										       [b
											[b
											 [b
											  [b
											   [b
											    [b
											     [b
											      [b
											       [b
												[b
												 [b
												  [b
												   [b
												    [b
												     [b
												      [b
												       [b
													[b
													 [b
													  [b
													   [b
													    [b
													     [b
													      [b
													       [b
														[b
														 [b
														  [b
														   [b
														    [b
														     [b
														      [b
														       [b
															[b
															 [b
															  [b
															   [b
															    [b
															     [b
															      [b
															       [b
																[b
																 [b
																  [b
																   [b
																    [b
																     [b
																      [d
																       [j]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
	 ^ d[j]];
      j = p1;
    }
  goto lbl_1586;
}
$

**Comment by fhahn** [comment]
Looks like this has finally been fixed, it doesn't reproduce on current `main`: https://llvm.godbolt.org/z/c63YadzEf https://clang.godbolt.org/z/78Yeszxc6
