### ISSUE TITLE
Emit warning for initializing a reference with literal/temporary

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#32147]
|  |  |
| --- | --- |
| Bugzilla Link | [32800](https://llvm.org/bz32800) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hyp,@LebedevRI,@seanm |

## Extended Description 
Hi,

would it be possible to emit a warning for the code below? I could imagine this case could be detected easily in the frontend / middleend.

ASan finds this with detect_stack_use_after_return enabled, but this option is sometimes not feasible due to high memory usage.

struct RefStorer
{
  RefStorer(const bool& ref): m_ref(ref) {}

  const bool& m_ref;
};

RefStorer getRefStorer()
{
  return RefStorer(false); // false passed as reference
}

int main()
{
  RefStorer r = getRefStorer(); // m_ref now dangling
  return 0;
}

Additionally such cases should also be handled:

RefStorer getRefStorer()
{
  bool b = false;
  return RefStorer(b);
}

Best regards,
Martin

**Comment by usx95** [comment]
Old bug. This is resolved using lifetimebound
https://godbolt.org/z/dvqMecvfj
