### ISSUE TITLE
Missed optimization: (int)x + 1 == (int)y - 1

### ISSUE THREAD

**Issue by Tilka** [llvm/llvm-project#32161]
|  |  |
| --- | --- |
| Bugzilla Link | [32814](https://llvm.org/bz32814) |
| Version | trunk |
| OS | All |
| CC | @LebedevRI,@RKSimon,@rotateright |

## Extended Description 
int(x) + 1 == int(y) - 1

is not being optimized to

int(x) + 2 == int(y)

Proof: http://rise4fun.com/Alive/vaC

**Comment by RKSimon** [comment]
> And of course it fails to work with vectors.

Vector support: https://reviews.llvm.org/D121358

**Comment by RKSimon** [comment]
Not sure what the next step should be: https://alive2.llvm.org/ce/z/cdodNQ

We can just drop the NSW/NUW requirements for eq/ne cases - which AFAICT is enough for this ticket.

Not sure what else we could be doing for other icmp predicates though? @rotateright @LebedevRI any thoughts?

**Comment by RKSimon** [comment]
General constant support for ne/eq comparisons: https://reviews.llvm.org/D121551

**Comment by rotateright** [comment]
> Not sure what the next step should be: https://alive2.llvm.org/ce/z/cdodNQ
> 
> We can just drop the NSW/NUW requirements for eq/ne cases - which AFAICT is enough for this ticket.
> 
> Not sure what else we could be doing for other icmp predicates though? @rotateright @LebedevRI any thoughts?

I agree - just drop the no-wrap requirement when eq/ne. I don't think there's anything more to do with other predicates.

**Comment by RKSimon** [comment]
Fixed by 7e4cf582cffdc287a0d6ee354e90a4fbdc5a696d
