### ISSUE TITLE
Possible incorrect code generation on use of initializer_list in range-based for loop

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#32171]
|  |  |
| --- | --- |
| Bugzilla Link | [32824](https://llvm.org/bz32824) |
| Version | 3.9 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
This issue was originally posted at http://stackoverflow.com/questions/43624400/is-this-unsafe-usage-of-a-braced-initializer-list-in-a-range-based-for-loop - I didn't get much of an answer there, and I'm inclined to think it might be a clang bug.

My example program is as follows:

    #include <initializer_list>
    #include <memory>

    struct Test
    {
        int x;
    };

    int main()
    {
        std::unique_ptr<Test> a(new Test);
        std::unique_ptr<Test> b(new Test);
        std::unique_ptr<Test> c(new Test);
        int id = 0;
        for(auto t : std::initializer_list<Test*>({a.get(), b.get(), c.get()}))
            t->x = id++;
        return 0;
    }

I compile this with the following command line:

    clang++ -std=c++11 -O3 crash.cc -o crash

The example is online at https://godbolt.org/g/r9uOEd as well.

When I compile the code using clang versions less than or equal to 3.8.1, I get what I would expect; the generated assembly looks like:

    main:                                   # @&#8203;main
            xor     eax, eax
            ret

No problem there. For clang 3.9.0, 3.9.1, and 4.0.0 (I haven't tested anything newer), I get the following:

    main:                                   # @&#8203;main
            mov     rax, qword ptr [rsp - 24]
            mov     dword ptr [rax], 0
            mov     rax, qword ptr [rsp - 16]
            mov     dword ptr [rax], 1
            mov     rax, qword ptr [rsp - 8]
            mov     dword ptr [rax], 2
            xor     eax, eax
            ret

It looks like the compiler optimized away the construction of the `Test` objects; it never invokes `operator new` to allocate memory for them, but it still runs the body of the for loop, dereferencing pointers that were never initialized. This obviously results in a segfault.

If I subtly tweak the example, taking out the parentheses used in the construction of the initializer_list in the range-based for loop, like this:

    #include <initializer_list>
    #include <memory>

    struct Test
    {
        int x;
    };

    int main()
    {
        std::unique_ptr<Test> a(new Test);
        std::unique_ptr<Test> b(new Test);
        std::unique_ptr<Test> c(new Test);
        int id = 0;
        for(auto t : std::initializer_list<Test*>{a.get(), b.get(), c.get()})
            t->x = id++;
        return 0;
    }

Then I get good code generation on all clang versions that I've tried. What I've been trying to understand is whether this is a compiler bug or undefined behavior. In the first example, is the inner braced initializer treated as a temporary whose lifetime ends after the range-based for loop is initialized, and therefore gets optimized out?

**Comment by Endilll** [comment]
Appears to be fixed in Clang 12: https://godbolt.org/z/bzjK7GWhr
12 emits the same instructions as 3.8.
