### ISSUE TITLE
clang-tidy doesn't define __clang_analyzer__ when doing static analyses

### ISSUE THREAD

**Issue by gburgessiv** [llvm/llvm-project#32261]
|  |  |
| --- | --- |
| Bugzilla Link | [32914](https://llvm.org/bz32914) |
| Version | unspecified |
| OS | All |
| CC | @stephenhines |

## Extended Description 
clang's static analyzer #defines __clang_analyzer__ when it's running. this is useful for making implicit guarantees explicit for the static analyzer, like:

// LOG(FATAL) delegates to a function that's `noreturn` if it's passed FATAL
#if __clang_analyzer__
struct Die {
  ~Die() __attribute__((noreturn)) { abort(); }
  operator bool() const { return false; }
};
#define LOG(sev) ((sev) >= FATAL && Die()) || log(sev)
#else
// log(FATAL) terminates the program on destruction; log(WARN), etc. don't, so
// log can't simply be marked noreturn.
#define LOG(sev) log(sev)
#endif

...and a fair amount of existing code is using it for this purpose.

clang-tidy doesn't seem to define this macro (or anything special, really) when running its static analyzer based checks. it would be nice if it did.

**Comment by EugeneZelenko** [comment]
Should be fixed in c5d14b5c6fa9e003ef2037dcd3601c8339b1e42f.
