### ISSUE TITLE
ConvertUTF.cpp is shipped with a non "University of Illinois Open Source  License" compatible license

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#32309]
|  |  |
| --- | --- |
| Bugzilla Link | [32962](https://llvm.org/bz32962) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie,@DimitryAndric,@jlebar,@MatzeB |

## Extended Description 
Detected by lintian, the Debian static analyzer:

lib/Support/ConvertUTF.cpp include material under a non-free
license from Unicode Inc. Therefore, it is not possible to ship this in
main or contrib.
    
This license does not grant any permission to modify the files (thus
failing DFSG#3). Moreover, the license grant to attempt to restrict use
to "products supporting the Unicode Standard" (thus failing DFSG#6).
    
In this case a solution is to use libicu and to remove this code by
repacking.

Refer to https://bugs.debian.org/823100 for details.

And https://en.wikipedia.org/wiki/Debian_Free_Software_Guidelines for Debian information.

**Comment by sylvestre** [comment]
well done :)

**Comment by bkmgit** [comment]
@jyknight  Discussion at https://github.com/AmokHuginnsson/replxx/issues/12 indicates these can be replaced by https://github.com/nemtrif/utfcpp

**Comment by jyknight** [comment]
The code does not need to be replaced for license reasons. The files were
relicensed to a proper license by Unicode.org some 15 years ago, so we
fixed this issue for llvm by applying the "new" license terms to our copy.

I would suggest anyone else who is in a similar situation should do the
same. (Of course, if you want to use a different library for functional
reasons, that's another matter.)
