### ISSUE TITLE
generic thunk code fails

### ISSUE THREAD

**Issue by nlewycky** [llvm/llvm-project#3233]
|  |  |
| --- | --- |
| Bugzilla Link | [2861](https://llvm.org/bz2861) |
| Version | trunk |
| OS | Linux |
| Attachments | [testcase](https://user-images.githubusercontent.com/392652/143738348-f798d329-9d3d-45f1-b48c-bbbd7faabe29.gz) |
| CC | @lattner,@efriedma-quic |

## Extended Description 

This delta-reduced testcase triggers a problem with llvm-g++ that doesn't happen with FSF g++ 4.2:

$ g++ thunk_error.cpp -c
thunk_error.cpp:21: error: generic thunk code fails for method ‘virtual void RPCCore::Ev(const char*, int, int, const char*, ...) const’ which uses ‘...’
$ g++-4.2 thunk_error.cpp -c
$ g++-4.2 -v
[...]
gcc version 4.2.4 (Debian 4.2.4-3)

**Comment by gwelymernans** [comment]
Dragonegg isn't around anymore.
