### ISSUE TITLE
man clang-format has ERROR ld.so in the description comments

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#32353]
|  |  |
| --- | --- |
| Bugzilla Link | [33006](https://llvm.org/bz33006) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
running `man clang-format` on clang-format 3.8 on Ubuntu 16.04 and clang-format 4.0 on Ubuntu 17.04 produces the following text in the output:

ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored. OVERVIEW: A tool to format C/C++/Obj-C code.

You can actually see this output on web hosted man pages for clang-format: http://manpages.org/clang-format

**Comment by mkurdej** [comment]
This bug concerns an old version of clang. It seems that it doesn't occur anymore on newer releases.
Cf. https://manpages.debian.org/experimental/clang-format-10/clang-format-10.1.en.html, https://manpages.debian.org/testing/clang-format-9/clang-format-9.1.en.html.
Nota bene: the link http://manpages.org/clang-format still points to the buggy documentation of version 3.7.
