### ISSUE TITLE
[OPENMP] positive loop step not recognized as such

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [llvm/llvm-project#32409]
|  |  |
| --- | --- |
| Bugzilla Link | [33062](https://llvm.org/bz33062) |
| Version | trunk |
| OS | All |
| CC | @alexey-bataev,@hfinkel |

## Extended Description 
The increment expression in the code below increases the loop counter by 1.
Clang generates diagnostics which claim otherwise.

### SOURCE (<stdin>):
int main(void) {
#pragma omp for
  for (unsigned i = 0; i < 10; i -= 0u - 1u) { }
}

### COMPILER INVOCATION:
clang -fsyntax-only -x c -std=c99 -fopenmp -

### OUTPUT:
<stdin>:3:40: error: increment expression must cause 'i' to increase on each iteration of OpenMP for loop
  for (unsigned i = 0; i < 10; i -= 0u - 1u) { }
                                    ~~~^~~~
<stdin>:3:26: note: loop step is expected to be positive due to this condition
  for (unsigned i = 0; i < 10; i -= 0u - 1u) { }
                       ~~^~~~
1 error generated.


### EXPECTED OUTPUT:
(Compiles successfully).


### COMPILER VERSION INFO (clang -v):
clang version 5.0.0 (https://github.com/llvm-mirror/clang.git 600a9e6e11f067dbb921c742b6fb676e0ac045bd) (https://github.com/llvm-mirror/llvm.git f0a3e25eca945f00368b68c9aa006b95b92fafaf)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/wandbox/clang-head/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

**Comment by jdoerfert** [comment]
I don't think this is valid. @alexey-bataev was right. 

If I read
> For an unsigned int x where x != UINT_MAX, x - UINT_MAX is x - UINT_MAX + UINT_MAX + 1 (i.e., x + 1).

It seems to say: x = x+1, if x != UINT_MAX, which is not clear to me.
