### ISSUE TITLE
-Wunneeded-internal-declaration disregards sizeof(x)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#32415]
|  |  |
| --- | --- |
| Bugzilla Link | [33068](https://llvm.org/bz33068) |
| Version | 3.6 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
$ clang --version
Ubuntu clang version 3.6.0-2ubuntu1~trusty1 (tags/RELEASE_360/final) (based on LLVM 3.6.0)
Target: x86_64-pc-linux-gnu
Thread model: posix

$ cat test.c 
static int x = 10;
int
main(void)
{
    return sizeof(x) == 4;
}

 
$ clang -Wall -Wextra -Werror -o test test.c
test.c:1:12: error: variable 'x' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]
static int x = 10;
           ^
1 error generated.

**Comment by shafik** [comment]
duplicate: https://github.com/llvm/llvm-project/issues/42943
