### ISSUE TITLE
SimplifyCFG sinks instructions too aggressively

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#32431]
|  |  |
| --- | --- |
| Bugzilla Link | [33084](https://llvm.org/bz33084) |
| Version | trunk |
| OS | Windows NT |
| CC | @jmolloy |

## Extended Description 
Testcase:

int f(int a, int b, int g(void)) {
  int c;
  if (g) {
    g(); c = (a + 31) & -32;
  } else {
    c = (b + 62) & -64;
  }
  return c;
}

Pass this to clang -O2, and you get IR something like this:

define i32 @&#8203;f(i32 %a, i32 %b, i32 ()* %g) local_unnamed_addr #&#8203;0 {
entry:
  %tobool = icmp eq i32 ()* %g, null
  br i1 %tobool, label %if.else, label %if.then

if.then:                                          ; preds = %entry
  %call = tail call i32 %g() #&#8203;1
  %add = add nsw i32 %a, 31
  br label %if.end

if.else:                                          ; preds = %entry
  %add1 = add nsw i32 %b, 62
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  %.sink = phi i32 [ -64, %if.else ], [ -32, %if.then ]
  %add1.sink = phi i32 [ %add1, %if.else ], [ %add, %if.then ]
  %and2 = and i32 %add1.sink, %.sink
  ret i32 %and2
}

Sinking the "and" here might not make sense: we're generating two phi nodes to remove one "and" instruction.

We started sinking the "and" in r280351.

I'm planning to continue looking into this, but suggestions welcome.

**Comment by xgupta** [comment]
This seems to fix on trunk - https://godbolt.org/z/bb4Pqaza6, no phi.

**Comment by efriedma-quic** [comment]
That godbolt link has the wrong optimization level, but yes, appears to be fixed.
