### ISSUE TITLE
bugpoint needs to try removing fastcc when using CBE

### ISSUE THREAD

**Issue by nlewycky** [llvm/llvm-project#3244]
|  |  |
| --- | --- |
| Bugzilla Link | [2872](https://llvm.org/bz2872) |
| Version | trunk |
| OS | Linux |
| CC | @jayfoad,@sunfishcode |

## Extended Description 
The CBE doesn't (can't, never will) support the fastcc calling convention. Currently, when it splits the module it will emit the LLVM 'to-optimize' side with fastcc intact, but the CBE-side will silently drop fastcc. This causes an obvious ABI mismatch and a not very useful reduction.

Before bugpoint starts splitting across the CBE, it should try removing all fastcc's. It also needs to make sure that step doesn't, on its own, 'fix' the problem.

**Comment by arsenm** [comment]
C backend and bugpoint are obsolete
