### ISSUE TITLE
Assertion failed: Result.isUninit() && "temporary created multiple times", file ExprConstant.cpp, line 1107

### ISSUE THREAD

**Issue by rgal** [llvm/llvm-project#32487]
|  |  |
| --- | --- |
| Bugzilla Link | [33140](https://llvm.org/bz33140) |
| Version | trunk |
| OS | Linux |
| CC | @arichardson,@DougGregor,@efriedma-quic,@gregbedwell,@nlewycky,@pogo59,@zygoloid,@VReichelt |

## Extended Description 
These are two cases found in internal testing. They hit the same assertion but were introduced at different times, presumably by related commits.

$ cat testa.cpp
```cpp
struct S {
  constexpr S(const int &a = 0) {}
};
void foo(void) {
  S s[2] = {};
}
```
$ clang -c testa.cpp -std=c++11
Assertion failed: Result.isUninit() && "temporary created multiple times", file
<...>\ExprConstant.cpp, line 1107
 
Bisects to:
commit f83586caa9df7ebae5226227614513df4af4b402
Author: Nick Lewycky <nicholas@mxc.ca>
Date:   Sat Apr 29 09:33:46 2017 +0000
 
    Remove Sema::CheckForIntOverflow, and instead check all full-expressions.
 
    CheckForIntOverflow used to implement a whitelist of top-level expressions to
    send to the constant expression evaluator, which handled many more expressions
    than the CheckForIntOverflow whitelist did.
 
 
    git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@301742 91177308-0d34-0410-b5e6-96231b3b80d8
 

$ cat testb.cpp
```cpp
bool bar(float const &f = 0);
bool foo() { return bar() && bar(); }
```
$ clang -c testb.cpp
Assertion failed: Result.isUninit() && "temporary created multiple times", file <...>\ExprConstant.cpp, line 1107
 
Bisects to:
commit 750306071663247152ab611f63e1d97ec175786d
Author: Nick Lewycky <nicholas@mxc.ca>
Date:   Wed May 17 23:56:54 2017 +0000
 
    The constant expression evaluator should examine function arguments for non-constexpr function calls unless the EvalInfo says to stop.
 
    git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@303317 91177308-0d34-0410-b5e6-96231b3b80d8

**Comment by shafik** [comment]
No longer reproduces on trunk: https://godbolt.org/z/YW3PMPE7r and https://godbolt.org/z/qKdGfzErY and https://godbolt.org/z/x67zP9rjG
