### ISSUE TITLE
-march=cpp: Calling makeLLVMModuleContents twice gives memory errors

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#3250]
|  |  |
| --- | --- |
| Bugzilla Link | [2878](https://llvm.org/bz2878) |
| Version | trunk |
| OS | All |
| Attachments | [.ll test case](https://user-images.githubusercontent.com/60944935/143738357-d073d149-ef5a-43e0-b6a2-089301a88c93.gz), [.cpp test case.](https://user-images.githubusercontent.com/60944935/143738358-889d2707-3bb3-4213-bbea-c88a4c3ac5b9.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@isanbard |

## Extended Description 
When calling two times the makeLLVMModuleContents function generated by the cpp backend with -cppgen=contents, I get a memory corruption.

You can find the .ll file to compile using:
llvm-as -f essai.ll -o - | llc -march=cpp -cppgen=contents -f -o generated.cpp

And then compile essai.cpp with the appropriate llvm libraries.

The error is probably due to the use of opaque types in the makeLLVMModuleContents function.

The error message is:
*** glibc detected *** ./a.out: malloc(): memory corruption (fast): 0x087dabe8 ***
======= Backtrace: =========
/lib/tls/i686/cmov/libc.so.6[0xb7d54962]
/lib/tls/i686/cmov/libc.so.6(__libc_malloc+0x8d)[0xb7d55cad]
/usr/lib/libstdc++.so.6(_Znwj+0x27)[0xb7f20447]
./a.out(_ZNSt6vectorIPKN4llvm4TypeESaIS3_EEC1ERKS5_+0x4e)[0x85ff81e]

The trace with the core dump.

#&#8203;0  0xb7f8b410 in __kernel_vsyscall ()
#&#8203;1  0xb7d13085 in raise () from /lib/tls/i686/cmov/libc.so.6
#&#8203;2  0xb7d14a01 in abort () from /lib/tls/i686/cmov/libc.so.6
#&#8203;3  0xb7d4bb7c in ?? () from /lib/tls/i686/cmov/libc.so.6
#&#8203;4  0xb7d54962 in ?? () from /lib/tls/i686/cmov/libc.so.6
#&#8203;5  0xb7d55cad in malloc () from /lib/tls/i686/cmov/libc.so.6
#&#8203;6  0xb7f20447 in operator new () from /usr/lib/libstdc++.so.6
#&#8203;7  0x085ff81e in std::vector<llvm::Type const*, std::allocator<llvm::Type const*> >::vector ()
#&#8203;8  0x085fc3fc in llvm::FunctionType::get ()
#&#8203;9  0x0865b455 in makeLLVMModuleContents (mod=0x87da320) at generated.cpp:26
#&#8203;10 0x0865b737 in main () at essai.cpp:19

**Comment by arsenm** [comment]
cpp backend no longer exists
