### ISSUE TITLE
Suggest using SQLite in test suite

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#3252]
|  |  |
| --- | --- |
| Bugzilla Link | [2880](https://llvm.org/bz2880) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I suggest adding SQLite to your test or acceptance suites as it is suitably large and meaty.  For me it has already highlighted issues #&#8203;2879 and #&#8203;2828.  There is a SQLite ticket which gives some idea of how useful the analyser turned out to be:

http://www.sqlite.org/cvstrac/tktview?tn=3391

**Comment by JOE1994** [comment]
`llvm-test-suite` has `sqlite3` as one of the tests:

* https://github.com/llvm/llvm-test-suite/tree/92b58b3bf4c6001bff4c7c7f8f98305e3ead56ff/MultiSource/Applications/sqlite3
