### ISSUE TITLE
Infinite loop compiling erroneous C++ code

### ISSUE THREAD

**Issue by asl** [llvm/llvm-project#32533]
|  |  |
| --- | --- |
| Bugzilla Link | [33186](https://llvm.org/bz33186) |
| Version | trunk |
| OS | All |
| Attachments | [Testcase](https://user-images.githubusercontent.com/67392/143755677-e448d601-b20d-4487-8c26-e345348121ea.gz) |
| CC | @DougGregor |

## Extended Description 

See the testcase attached. clang is looping somewhere inside TreeTransform. Both ToT, 4.0 and clang from the latest XCode are affected.

**Comment by wheatman** [comment]
This seems to have been fixed between 10.0.1 and 11.0.0
https://godbolt.org/z/PoPrnn7Ta

for reference
code
```
namespace
{
	struct V
	{
		float x;
	};

	class H
	{
	public:
		const V& getV() const { return mV; }
		int      getN() const { return mN; }
	private:
		V   mV;
		int mN;
	};
	
	class T
	{
	public:
		const H& getH0() const { return mH0; }
		const H& getH1() const { return mH1; }
		
		const V& getV0() const { return mH0.getV(); }
		const V& getV1() const { return mH1.getV(); }
		
	private:
		H mH0;
		H mH1;
	};
	
	T sT;
	H sH;
}

void func()
{
	( sT.getH2().getM() > sH.getM() ?
	  sT.getH3() :
	  0 );
}

```
