### ISSUE TITLE
null pointer call lib/Bitcode/Writer/BitcodeWriter.cpp in LLVM::BugPoint/named-md.ll (runtime error)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#32545]
|  |  |
| --- | --- |
| Bugzilla Link | [33198](https://llvm.org/bz33198) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
llvm @ f1e232d9b0afea4224c5cf2e8c0259594237f28f /
git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@304080 91177308-0d34-0410-b5e6-96231b3b80d8

This was the result of doing a stage2 asan+ubsan instrumented check-all run.

build setup was like this:

cmake ../llvm -G "Ninja" \
	-DCMAKE_BUILD_TYPE=Release \
	-DLLVM_BINUTILS_INCDIR=/usr/include \
	-DCMAKE_C_FLAGS="-march=native -Og  -g" \
	-DCMAKE_CXX_FLAGS="-march=native -Og  -g" \
	-DLLVM_PARALLEL_LINK_JOBS=1 \
	-DLLVM_OPTIMIZED_TABLEGEN=1 \
	-DLLVM_TARGETS_TO_BUILD="X86" \
	-DCMAKE_AR="${rootDir}/stage_1/build/bin/llvm-ar" \
	-DCMAKE_RANLIB="${rootDir}/stage_1/build/bin/llvm-ranlib" \
	-DLLVM_USE_LINKER="${rootDir}/stage_1/build/bin/ld.lld"  \
	-DLLVM_USE_SANITIZER="Address;Undefined" \
	-DLLVM_PARALLEL_LINK_JOBS=1 \
	-DLLVM_ENABLE_EXPENSIVE_CHECKS=1 

LLVM::BugPoint/named-md.ll failed due to 

llvm/lib/Bitcode/Writer/BitcodeWriter.cpp:3830:16: runtime error: member call on null pointer of type 'llvm::Module'

Test output:

********************
FAIL: LLVM :: BugPoint/named-md.ll (15254 of 34661)
******************** TEST 'LLVM :: BugPoint/named-md.ll' FAILED ********************
Script:
--
/home/matthias/LLVM/LLVM_san/stage_2/objects/./bin/bugpoint -load /home/matthias/LLVM/LLVM_san/stage_2/objects/./lib/BugpointPasses.so /home/matthias/LLVM/LLVM_san/stage_2/llvm/test/BugPoint/named-md.ll -output-prefix /home/matthias/LLVM/LLVM_san/stage_2/objects/test/BugPoint/Output/named-md.ll.tmp -bugpoint-crash-too-many-cus -silence-passes -disable-strip-debuginfo > /dev/null
/home/matthias/LLVM/LLVM_san/stage_2/objects/./bin/llvm-dis /home/matthias/LLVM/LLVM_san/stage_2/objects/test/BugPoint/Output/named-md.ll.tmp-reduced-simplified.bc -o - | /home/matthias/LLVM/LLVM_san/stage_2/objects/./bin/FileCheck /home/matthias/LLVM/LLVM_san/stage_2/llvm/test/BugPoint/named-md.ll
--
Exit Code: 1

Command Output (stderr):
--
Final cleanups failed.  Sorry. :(  Please report a bug!
/home/matthias/LLVM/LLVM_san/stage_2/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp:3830:16: runtime error: member call on null pointer of type 'llvm::Module'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/matthias/LLVM/LLVM_san/stage_2/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp:3830:16 in 

--

**Comment by Endilll** [comment]
Old build issue is unlikely to be relevant today.
