### ISSUE TITLE
readability-non-const-parameter should fix all function declarations when inserting `const`

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#32566]
|  |  |
| --- | --- |
| Bugzilla Link | [33219](https://llvm.org/bz33219) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I have this pointer.c file

#include "pointer.h"
int switcher(int * i) {
 int a = *i;
    switch (a) {
        case 1: 
            return 0;
        default: 
            return 1;
    }
}  

and the associated header contains only one line

int switcher(int * i);

This compiles using clang.

If I now use clang-tidy (clang-tidy -fix pointer.c -checks=* -header-filter=.* ) I get the following result

#include "pointer.h"
int switcher(const int * i) {
    int a = *i;
    switch (a) {
        case 1: 
            return 0;
        default: 
            return 1;
    }
}

and the header

#ifndef _HOME_GWE_PROJEKTE_CLANG_TIDY_POINTER_H
#define _HOME_GWE_PROJEKTE_CLANG_TIDY_POINTER_H

int switcher(int * i);

#endif

The signature of the function has been changed form (int i) to (const int i) which is nice. The header file has also been altered (guards), but the signature stays the very same. Thus. the code does not compile any more.

My compile_commands.json looks like this

[
{
  "directory": "/home/gwe/projekte/clang/tidy",
  "command": "clang -c pointer.c -I.",
  "file": "pointer.c"
}
]

Best regards, Georg

**Comment by PiotrZSL** [comment]
this is already fixed, closing
