### ISSUE TITLE
wrong code at -Os and above in CFLAA on x86_64-linux-gnu (with either "-mllvm -use-cfl-aa=anders" or "-mllvm -use-cfl-aa=steens")

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#32686]
|  |  |
| --- | --- |
| Bugzilla Link | [33339](https://llvm.org/bz33339) |
| Version | trunk |
| OS | All |
| CC | @filcab,@gburgessiv,@hfinkel,@rnk |

## Extended Description 
The current trunk and 3.9.x miscompile this test, but 4.0.x do not (neither do 3.8.x as it appears). 

$ clang -v
clang version 5.0.0 (trunk 304811) (llvm/trunk 304810)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clang -Os -w small.c; ./a.out
$ clang-4.0.0 -Os -mllvm -use-cfl-aa=anders -w small.c; ./a.out
$ 
$ clang -Os -mllvm -use-cfl-aa=steens -w small.c; ./a.out
Aborted (core dumped)
$ clang -Os -mllvm -use-cfl-aa=anders -w small.c; ./a.out
Aborted (core dumped)
$ 

------------------------------

int a, b, *c, d, e, *f;

int fn1 (int p)
{
  return p;
}

int main ()
{
  int *g;
  if (d)
    goto L;
  int **h = &g;
  f = &a;
  int *i; 
  while (b)
    {
      fn1 (!i);
      &e != &i;
    L:
      c = g;
    }
  *h = f;
  if (g != &a)
    __builtin_abort ();
  return 0; 
}

**Comment by nunoplopes** [comment]
CFL AA was removed from LLVM. So, closing this.
