### ISSUE TITLE
Merge r303851 into the 4.0 branch : [CodeGen] Pessimize aliasing for member unions (and may-alias) objects

### ISSUE THREAD

**Issue by sesse** [llvm/llvm-project#32690]
|  |  |
| --- | --- |
| Bugzilla Link | [33343](https://llvm.org/bz33343) |
| Version | 4.0 |
| OS | All |
| Blocks | llvm/llvm-project#31409  |
| CC | @tstellar |

## Extended Description 
Is this patch OK to merge to the 4.0 branch?

**Comment by arsenm** [comment]
Old release
