### ISSUE TITLE
-verify-scev is causing hang or just taking forever

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#32734]
|  |  |
| --- | --- |
| Bugzilla Link | [33387](https://llvm.org/bz33387) |
| Version | trunk |
| OS | Linux |
| Attachments | [test case](https://user-images.githubusercontent.com/55128014/143755770-888a469e-6171-44ab-8099-45844889c9e1.gz) |
| CC | @JonPsson |

## Extended Description 

(Csmith)

This test case takes a second to compile with clang, but with -mllvm -verify-scev, it does not seem to terminate after even an hour...

It seems that GlobalsModRef.cpp is recursing very heavily in Constant::isConstantUsed(). 

When I try this->dump() on the Constant, the dumping never ends, so this seems to be either crazy or something that the algorithm should guard against.

bin/clang -cc1 -triple s390x-ibm-linux -S  -target-cpu z13 -O3 -vectorize-loops -vectorize-slp  -o /dev/null -x ir ~/build-dev/test4.bc -mllvm -verify-scev

**Comment by fhahn** [comment]
It looks like current `opt` doesn't hang any longer, so this likely has been fixed: https://clang.godbolt.org/z/h6nK4bWM8

Please re-open the issue with additional info, if it still reproduces on your end.
