### ISSUE TITLE
readability-redundant-declaration throws a warning for static field with non-integral type initialization

### ISSUE THREAD

**Issue by kirillbobyrev** [llvm/llvm-project#32732]
|  |  |
| --- | --- |
| Bugzilla Link | [33385](https://llvm.org/bz33385) |
| Version | unspecified |
| OS | Linux |
| CC | @JDevlieghere |

## Extended Description 
Basically, if a struct or a class has a const static field with non-integral type (such as other class/struct), this field has to be initialized in some source file. However, readability-redundant-declaration check produces a warning for that, which (I believe) is not correct.

Minimal example:

```
#include <string>

struct Data {
  static const std::string field; 
};

const std::string Data::field = "Hello, world!";

int main() {
  Data D;
  return 0;
}
```

Clang-Tidy output:

```
[omtcyfz@omtcyfz-arch playground]$ clang-tidy -checks=readability-redundant-declaration main.cpp -- -std=c++14
/home/omtcyfz/dev/playground/main.cpp:7:25: warning: redundant 'field' declaration [readability-redundant-declaration]
const std::string Data::field = "Hello, world!";
                        ^
/home/omtcyfz/dev/playground/main.cpp:4:28: note: previously declared here
  static const std::string field;
```

**Comment by PiotrZSL** [comment]
This were fixed by 80c3b17410e10bab68ca3f48e86cdbc5357a9954.
