### ISSUE TITLE
FMA Header Included but not wanted

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#32780]
|  |  |
| --- | --- |
| Bugzilla Link | [33433](https://llvm.org/bz33433) |
| Version | 4.0 |
| OS | Linux |
| Attachments | [Test file for compilation](https://user-images.githubusercontent.com/60944935/143755795-c3927e17-d974-423b-91ba-3a62ff652aca.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @topperc |

## Extended Description 

My machine supports AVX, not FMA.
Compile test.c with:
clang -mavx

It says: clang -mavx test.c
test.c:6:25: error: redefinition of '_mm256_fmadd_pd'
  static inline __m256d _mm256_fmadd_pd(__m256d a, __m256d b, __m256d c) {
                        ^
/usr/bin/../lib64/clang/4.0.0/include/fmaintrin.h:161:1: note: previous
definition is here
_mm256_fmadd_pd(__m256d __A, __m256d __B, __m256d __C)

Headers for FMA are included. So clearly a redefinition happens. But this behaviour is not normal.

If I compile with
gcc -mavx, it compiles and run the normal way.

**Comment by arsenm** [comment]
Last comment says this works as intended
