### ISSUE TITLE
SelectionDAGISel::CodeGenAndEmitDAG takes 3 minutes to compile 11 lines of C++,

### ISSUE THREAD

**Issue by kcc** [llvm/llvm-project#32841]
|  |  |
| --- | --- |
| Bugzilla Link | [33494](https://llvm.org/bz33494) |
| Version | unspecified |
| OS | Linux |
| CC | @filcab,@bogner |

## Extended Description 
r305575, x86_64 linux

void foo(int *a) {
while (a[56]){
a[0]=(a[0]+(a[0]+(a[0]+(a[0]>=1))));
while (a[0]){
a[0]=(a[0]+(1048576));
a[8]=(((((((((((((a[0]+a[0])*(((((a[0]+a[0])*a[0])*a[0])*a[0])*a[0]))*a[0])*(((((a[0]+a[0])*a[0])*a[0])*a[0])*a[0]))*a[0])*a[0])*a[0])*a[0])*a[0])*a[0])*a[0])+((a[0]+1)+(0)))+a[8]);
a[0]=(a[0]+(30));
}
}
}

clang -cc1 -triple x86_64-unknown-linux-gnu t.cc -O2  -emit-obj

# finishes in 3 minutes

#&#8203;0  0x00000000023c2163 in (anonymous namespace)::ScheduleDAGRRList::PickNodeToScheduleBottomUp() ()
#&#8203;1  0x00000000023bfd77 in (anonymous namespace)::ScheduleDAGRRList::Schedule() ()
#&#8203;2  0x000000000235075a in llvm::SelectionDAGISel::CodeGenAndEmitDAG() ()
#&#8203;3  0x000000000234dd4e in llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) ()
#&#8203;4  0x000000000234a512 in llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) ()
#&#8203;5  0x00000000010c5d91 in (anonymous namespace)::X86DAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) ()
#&#8203;6  0x000000000149eaf4 in llvm::MachineFunctionPass::runOnFunction(llvm::Function&) ()
#&#8203;7  0x00000000017692ff in llvm::FPPassManager::runOnFunction(llvm::Function&) ()

the code is generated by an experimental clang-proto-fuzzer

**Comment by arsenm** [comment]
All compile fine for me today
