### ISSUE TITLE
__has_cpp_attribute is 1 but warning is printed

### ISSUE THREAD

**Issue by 69d80b74-475e-435b-96f3-4fe863603a63** [llvm/llvm-project#32865]
|  |  |
| --- | --- |
| Bugzilla Link | [33518](https://llvm.org/bz33518) |
| Version | trunk |
| OS | Linux |
| CC | @AaronBallman,@DougGregor,@jyknight,@zygoloid,@viccpp |

## Extended Description 
In the following source code:

#if __has_cpp_attribute(nodiscard)
[[nodiscard]] 
#endif
int f()
{
    return 1;
}

If compiled with:
 clang -std=c++11 -Wc++1z-extensions 
 (or -std=c++14)

Will produce the warning:
 warning: use of the 'nodiscard' attribute is a C++1z extension [-Wc++1z-extensions]

The compiler should not advertise the availability of a feature it will print a warning for, if used.

Compatibility: GCC does have __has_cpp_attribute(nodiscard) > 0 even in C++11 mode, but it (currently) no equivalent warning switch.

**Comment by AaronBallman** [comment]
I went with the diagnostic group approach in a18632adc884397e0cd7f27bdb8ea3a822b63000 and I believe this issue can be closed as I don't envision semantic changes to `__has_cpp_attribute`.
