### ISSUE TITLE
[MS] Clang crashes emitting IR for "throw" when _CxxThrowException is defined in the TU

### ISSUE THREAD

**Issue by rnk** [llvm/llvm-project#32876]
|  |  |
| --- | --- |
| Bugzilla Link | [33529](https://llvm.org/bz33529) |
| Version | unspecified |
| OS | Windows NT |
| CC | @compnerd,@rnk |

## Extended Description 
Consider:

struct _ThrowInfo { int a, b, c, d; };
extern "C" void _CxxThrowException(void *p, _ThrowInfo *e) {}
void f() { throw 53; }

Compiling in the usual way on Windows results in:

Assertion failed: isa<X>(Val) && "cast<Ty>() argument of incompatible type!", file C:\src\llvm-project\llvm\include\llvm/Support/Casting.h, line 255

**Comment by Endilll** [comment]
Appears to be fixed in Clang 9: https://cexplorer.testlabs.pro/z/GWETMh
