### ISSUE TITLE
PowerPC - miscompile yields infinite looping when using -code-model=large

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#32894]
|  |  |
| --- | --- |
| Bugzilla Link | [33547](https://llvm.org/bz33547) |
| Version | 4.0 |
| OS | Windows NT |
| Attachments | [reproducer reduced from larger program](https://user-images.githubusercontent.com/60944935/143755861-dec1d5e9-bd07-4ae6-9c9c-7945fe23f569.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@jsonn,@nemanjai |

## Extended Description 

This bug appears in the release_40 branch on PowerPC.

To reproduce:

% opt -O2 bug.bc -o bug.opt.bc
% llc bug.opt.bc -mcpu=native -code-model=large -o bug.s

In the prologue for z0042(), there should be the following sequence

# BB#0:                                 # %L.entry
        addis 3, 2, .LC0@toc@ha
        bl .L0$pb
.L0$pb:
        ld 4, .LC0@toc@l(3)
        mflr 3
        lwz 4, 0(4)
        cmpwi    4, 1
        bltlr 0

which is a call from the prologue to the next instruction. This call sends the program into an infinite loop.

The reproducer has reduced from a much larger code to isolate this specific code gen pattern.

The SVN commit that results in this failure was 287059. Reverting that changeset eliminates the infinite loop and corrects the test application.

**Comment by nemanjai** [comment]
This has long since been fixed. I'm not sure why I never closed the issue/bug.
