### ISSUE TITLE
ICE'd clang with Tot

### ISSUE THREAD

**Issue by tschuett** [llvm/llvm-project#32928]
|  |  |
| --- | --- |
| Bugzilla Link | [33581](https://llvm.org/bz33581) |
| Version | trunk |
| OS | Linux |
| Attachments | [Reproducer,stacktrace](https://user-images.githubusercontent.com/7668424/143755880-2d0f9c1e-72bd-4746-9e7e-cb5d844074b6.gz) |
| CC | @zmodem,@tschuett |

## Extended Description 

clang ICE'd:

1.	passes/analysis.cpp:71:68: current parser token ')'
2.	passes/analysis.cpp:7:1: parsing namespace '(anonymous)'
3.	passes/analysis.cpp:11:3: parsing struct/union/class body '(anonymous namespace)::Analysis'
4.	passes/analysis.cpp:57:85: parsing function body '(anonymous namespace)::Analysis::analyzeTerminator'
5.	passes/analysis.cpp:57:85: in compound statement ('{}')
6.	passes/analysis.cpp:58:81: in compound statement ('{}')
7.	passes/analysis.cpp:60:16: in compound statement ('{}')
8.	passes/analysis.cpp:63:69: in compound statement ('{}')
9.	passes/analysis.cpp:69:75: in compound statement ('{}')
clang-5.0: error: unable to execute command: Segmentation fault

**Comment by Endilll** [comment]
Appears to be fixed in Clang 7: https://godbolt.org/z/8Mbc3WhxG
Reduced by C-Reduce:
```cpp
auto [FunctionId, BasicBlockId, LoadId] = getLoadId();
```
