### ISSUE TITLE
clang-format incorrectly treats throw *this as binary operator

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33012]
|  |  |
| --- | --- |
| Bugzilla Link | [33665](https://llvm.org/bz33665) |
| Version | unspecified |
| OS | All |
| Attachments | [Proposed patch](https://user-images.githubusercontent.com/60944935/143755916-23ccc69a-c3fa-4092-86cf-1b03fde2beae.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
With the following code:

`void Throw() { throw *this; }`

c-f currently formats it as:

`void Throw() { throw * this; }`

I looked into this and the star token is being given the type TT_BinaryOperator instead of TT_PointerOrReference, so it gets formatted with a space before and after. I'm currently working on a fix.

**Comment by mydeveloperday** [comment]
As of clang-format v8 and above the output is this, I am marking this as closed please reopen if still an issue

```
void Throw() { throw *this; }
```
