### ISSUE TITLE
clang tidy check request: implicit inline

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#33013]
|  |  |
| --- | --- |
| Bugzilla Link | [33666](https://llvm.org/bz33666) |
| Version | unspecified |
| OS | All |
| CC | @EugeneZelenko |

## Extended Description 
Some functions are implicitly inline (e.g. constexpr implies inline, a function definition within a class declaration, etc.), some variables are implicitly inline (some constexpr variables in C++17 inline variables). In these cases using the inline keyword is unnecessary.

clang-tidy should have a check that detects unnecessary inline annotations, and warns about them and/or fixes them by removing them.

**Comment by PiotrZSL** [comment]
Covered already by readability-redundant-inline-specifier.
