### ISSUE TITLE
register promotion miscompilation: hoisting division by zero

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33020]
|  |  |
| --- | --- |
| Bugzilla Link | [33673](https://llvm.org/bz33673) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @chandlerc,@majnemer,@efriedma-quic,@aqjune,@nunoplopes,@rnk,@sanjoy,@rotateright |

## Extended Description 
```
$ opt --version
LLVM (http://llvm.org/):
  LLVM version 5.0.0svn
  DEBUG build with assertions.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: ivybridge


$ cat yy.ll

@G = external global i32, align 4

define void @bar() {
  %p = alloca i32, align 4
  %a = load i32, i32* %p, align 4
  call void @foo(i32 %a)
  store i32 sdiv (i32 1, i32 sub (i32 ptrtoint (i32* @G to i32), i32 ptrtoint (i32* @G to i32))), i32* %p, align 4
  ret void
}

declare void @foo(i32)


$ opt yy.ll -mem2reg -S                        

; ModuleID = 'yy.ll'
source_filename = "yy.ll"

@G = external global i32, align 4

define void @bar() {
  call void @foo(i32 sdiv (i32 1, i32 sub (i32 ptrtoint (i32* @G to i32), i32 ptrtoint (i32* @G to i32))))
  ret void
}

declare void @foo(i32)
```

This is a miscompilation, because the sdiv constant expression, which is a division by zero, is hoisted across a function call to foo().  It may introduce undefined behavior when foo() does not terminate.

This bug is due to rewriteSingleStoreAlloca(...) in PromoteMemoryToRegister.cpp.  It should check that the stored value is not division by zero, when it is a constant expression.

**Comment by nikic** [comment]
Fixed by the removal of trapping constant expressions.
