### ISSUE TITLE
std::right and std::boolalpha not working right

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33027]
|  |  |
| --- | --- |
| Bugzilla Link | [33680](https://llvm.org/bz33680) |
| Version | 4.0 |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @edfvogel,@mclow |

## Extended Description 
std::cout << std::setw(54) << std::setfill(' ') << std::left << "blah test";
std::cout << std::setw(16) << std::setfill('.') << std::right << std::boolalpha << false;
std::cout << '\n';

results in:
blah test                                             false...............

If I remove std::boolalpha, or print the string "false" it works as expected.

**Comment by philnik777** [comment]
I think https://godbolt.org/z/no3bWroYv shows the expected behaviour, so I'm closing this.
