### ISSUE TITLE
differences with Microsoft __has_nothrow_assign and __has_trivial_assign when the assign operator is deleted

### ISSUE THREAD

**Issue by mibintc** [llvm/llvm-project#33063]
|  |  |
| --- | --- |
| Bugzilla Link | [33716](https://llvm.org/bz33716) |
| Version | trunk |
| OS | Windows NT |
| CC | @compnerd,@DougGregor,@zygoloid,@rnk |

## Extended Description 
The Microsoft compiler will compile these without error, but clang gives static assertions.

Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64

test.cpp
test.cpp:5:1: error: static_assert failed "__has_nothrow_assign is incorrect"
static_assert(!__has_nothrow_assign(non_assignable),
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test.cpp:7:1: error: static_assert failed "Fail"
static_assert(!__has_trivial_assign(non_assignable), "Fail");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
compilation aborted for test.cpp (code 1)
ksh-3.2$ cat test.cpp
struct non_assignable {
   non_assignable();
   non_assignable& operator=(const non_assignable&) = delete;
};
static_assert(!__has_nothrow_assign(non_assignable),
         "__has_nothrow_assign is incorrect");
static_assert(!__has_trivial_assign(non_assignable), "Fail");

**Comment by Endilll** [comment]
As Richard pointed out, libstdc++ is still using `__has_trivial_destructor` and `__has_virtual_destructor`. On top of that, I can find `__has_trivial_constructor`: https://github.com/search?q=repo%3Agcc-mirror%2Fgcc+path%3A%2F%5Elibstdc%5C%2B%5C%2B-v3%5C%2F%2F++%2F__has_%28trivial%7Cvirtual%29%2F&type=code

**Comment by shafik** [comment]
CC @cjdb @AaronBallman not sure who the right person to address this is tody

**Comment by AaronBallman** [comment]
> CC @cjdb @AaronBallman not sure who the right person to address this is tody

I don't think we have anyone teed up to work on this specifically, but anyone interested in MS compatbility or type traits would be good to work on it. It seems GCC and MSVC behavior diverged, so we should follow the GCC behavior by default and the MSVC behavior under `-fms-compatibility`. Given that these are deprecated and discouraged, I don't think it needs to worry about adding ABI tags, and the fix not a high priority unless we find some breakage in a system header or other important 3rd party library.

**Comment by AaronBallman** [comment]
> Can't we implement them as aliases to respective standard traits, with no care for subtle differences unless anything major emerges?

The trouble there is that type traits like this often end up in template metaprogramming and thus become part of the ABI, so subtle differences can be very expensive for users to fix. So it's not impossible; we could implement them as aliases, but it's risky and hard to measure what the impacts will be.

**Comment by cor3ntin** [comment]
@royjacobson has been the person doing most of the work in this area lately.

**Comment by cjdb** [comment]
Provided that we warn on them being _different_ to the standard library traits (or deprecate them), I have no real strong opinions here.

**Comment by royjacobson** [comment]
We added deprecation warnings about a year ago.
https://github.com/llvm/llvm-project/commit/0b89d1d59f82cf5b45c250cd5c3351e43ce35ef9

So I think this should be closed as won't fix.
