### ISSUE TITLE
Expose fp-contract flags in MIR

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33060]
|  |  |
| --- | --- |
| Bugzilla Link | [33713](https://llvm.org/bz33713) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@rotateright,@wjristow |

## Extended Description 
This is a follow-on to llvm/llvm-project#26095 .

**Comment by arsenm** [comment]
This is exposed
