### ISSUE TITLE
[opt; GVN] input program causes "Instruction does not dominate uses" error

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33078]
|  |  |
| --- | --- |
| Bugzilla Link | [33731](https://llvm.org/bz33731) |
| Version | 4.0 |
| OS | Linux |
| Attachments | [reproduce the instruction does not dominate uses bug](https://user-images.githubusercontent.com/60944935/143755946-03e3518c-8996-4b56-895d-52a55d6ba3a3.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @john-brawn-arm |

## Extended Description 

See the attached reproducer. To recreate the problem:

% opt -verify reduced.bc -o /dev/null
% opt -gvn reduced.bc -o /dev/null
Instruction does not dominate all uses!
  %.pre = sext i32 %1 to i64
  %6 = mul i64 %.pre, 4
LLVM ERROR: Broken function found, compilation aborted!

% opt -version
LLVM (http://llvm.org/):
  LLVM version 4.0.1
  DEBUG build with assertions.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: haswell

**Comment by fhahn** [comment]
Doesn't reproduce on current `main`, closing.
