### ISSUE TITLE
default member initialization and noexcept problems

### ISSUE THREAD

**Issue by jtsylve** [llvm/llvm-project#33083]
|  |  |
| --- | --- |
| Bugzilla Link | [33736](https://llvm.org/bz33736) |
| Version | 4.0 |
| OS | All |
| CC | @arrowd,@DougGregor,@Ivan171,@zygoloid |

## Extended Description 
I'm seeing an error that is similar to the question raised at https://stackoverflow.com/questions/43819314.  That question seems to not have any consensus as to what the problem may be.  

The following code produces a compile-time error in clang++ 4.0.0 and later, but works fine in gcc as well as previous versions of clang.

#include <memory>

struct A {
    A() noexcept = default;
    A(const A&) noexcept = default;

    std::shared_ptr<int> _a {};
};

int main() {
    return 0;
}

It's worth noting that if I remove the copy constructor, this compiles fine.  If I remove the noexcept qualification from the default constructor it also compiles fine.

The error I'm getting is as follows:

<source>:4:5: error: default member initializer for '_a' needed within definition of enclosing class 'A' outside of member functions
    A() noexcept = default;
    ^
/opt/compiler-explorer/clang-4.0.0/bin/../include/c++/v1/type_traits:1306:29: note: in instantiation of template class 'std::__1::is_class<int *>' requested here
template <class _Tp, bool = is_class<_Tp>::value>
                            ^
/opt/compiler-explorer/clang-4.0.0/bin/../include/c++/v1/type_traits:1311:71: note: in instantiation of default argument for '__libcpp_abstract<int *>' required here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS is_abstract : public __libcpp_abstract<_Tp> {};
                                                                      ^~~~~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/clang-4.0.0/bin/../include/c++/v1/type_traits:1384:39: note: in instantiation of template class 'std::__1::is_abstract<int *>' requested here
                                     !is_abstract<_T2>::value> {};
                                      ^
/opt/compiler-explorer/clang-4.0.0/bin/../include/c++/v1/memory:3918:39: note: in instantiation of template class 'std::__1::is_convertible<int *, int *>' requested here
                   typename enable_if<is_convertible<_Yp*, element_type*>::value, __nat>::type = __nat())
                                      ^
/opt/compiler-explorer/clang-4.0.0/bin/../include/c++/v1/memory:3883:28: note: while substituting deduced template arguments into function template 'shared_ptr' [with _Yp = int]
class _LIBCPP_TEMPLATE_VIS shared_ptr
                           ^
<source>:7:26: note: default member initializer declared here
    std::shared_ptr<int> _a {};

**Comment by wheatman** [comment]
As the above post indicates this seems to have been fixed between 5.0.2 and 6.0.0
https://godbolt.org/z/oj9PdY7Pq

for reference

code 
```
template<typename T> struct B { using type = bool; };

template<typename T> struct S {
  S() noexcept;

  template<typename U, typename B<U>::type = true>
  S(const S<U>&) noexcept;
};

struct A {
    A() noexcept = default;
    A(const A&) noexcept = default;
    S<int> _a {};
};

```

old error message
```
<source>:11:5: error: default member initializer for '_a' needed within definition of enclosing class 'A' outside of member functions
    A() noexcept = default;
    ^
<source>:6:44: note: in instantiation of template class 'B<int>' requested here
  template<typename U, typename B<U>::type = true>
                                           ^
<source>:7:3: note: while substituting prior template arguments into non-type template parameter [with U = int]
  S(const S<U>&) noexcept;
  ^~~~~~~~~~~~~~~~~~~~~~~
<source>:3:29: note: while substituting deduced template arguments into function template 'S' [with U = int, $1 = (no value)]
template<typename T> struct S {
                            ^
<source>:13:12: note: default member initializer declared here
    S<int> _a {};
           ^
1 error generated.
Compiler returned: 1
```
