### ISSUE TITLE
CompareSCEVComplexity(): Assertion `DT.dominates(RHead, LHead) && "No dominance between recurrences used by one SCEV?"' failed.

### ISSUE THREAD

**Issue by nunoplopes** [llvm/llvm-project#33108]
|  |  |
| --- | --- |
| Bugzilla Link | [33761](https://llvm.org/bz33761) |
| Version | trunk |
| OS | All |
| Attachments | [IR](https://user-images.githubusercontent.com/2998477/143755961-7c03ccfa-f772-4321-8de1-ad6ddd4ede3f.gz) |
| CC | @efriedma-quic,@sanjoy |

## Extended Description 

The bug should be in SCEV not in the alias analysis.

$ opt -S -scev-aa -print-alias-sets a.ll

opt: lib/Analysis/ScalarEvolution.cpp:648: int CompareSCEVComplexity(llvm::SmallSet<std::pair<const llvm::SCEV*, const llvm::SCEV*>, 8u>&, const llvm::LoopInfo*, const llvm::SCEV*, const llvm::SCEV*, llvm::DominatorTree&, unsigned int): Assertion `DT.dominates(RHead, LHead) && "No dominance between recurrences used by one SCEV?"' failed.

#&#8203;8 0x000056535aa00c00 CompareSCEVComplexity(llvm::SmallSet<std::pair<llvm::SCEV const*, llvm::SCEV const*>, 8u, std::less<std::pair<llvm::SCEV const*, llvm::SCEV const*> > >&, llvm::LoopInfo const*, llvm::SCEV const*, llvm::SCEV const*, llvm::DominatorTree&, unsigned int)
#&#8203;9 0x000056535aa06e74 GroupByComplexity(llvm::SmallVectorImpl<llvm::SCEV const*>&, llvm::LoopInfo*, llvm::DominatorTree&)
#&#8203;10 0x000056535aa18daf llvm::ScalarEvolution::getAddExpr(llvm::SmallVectorImpl<llvm::SCEV const*>&, llvm::SCEV::NoWrapFlags, unsigned int)
#&#8203;11 0x000056535aa1b03b llvm::ScalarEvolution::getAddExpr(llvm::SCEV const*, llvm::SCEV const*, llvm::SCEV::NoWrapFlags, unsigned int)
#&#8203;12 0x000056535aa1ffd4 llvm::ScalarEvolution::getMinusSCEV(llvm::SCEV const*, llvm::SCEV const*, llvm::SCEV::NoWrapFlags, unsigned int)
#&#8203;13 0x000056535aa3436a llvm::SCEVAAResult::alias(llvm::MemoryLocation const&, llvm::MemoryLocation const&)
#&#8203;14 0x000056535a8a5cb8 llvm::AAResults::alias(llvm::MemoryLocation const&, llvm::MemoryLocation const&)
#&#8203;15 0x000056535a8c2834 llvm::BasicAAResult::aliasCheck(llvm::Value const*, unsigned long, llvm::AAMDNodes, llvm::Value const*, unsigned long, llvm::AAMDNodes, llvm::Value const*, llvm::Value const*)
#&#8203;16 0x000056535a8c3d62 llvm::BasicAAResult::alias(llvm::MemoryLocation const&, llvm::MemoryLocation const&)
#&#8203;17 0x000056535a8a5cb8 llvm::AAResults::alias(llvm::MemoryLocation const&, llvm::MemoryLocation const&)
#&#8203;18 0x000056535a8b3262 llvm::AliasSet::aliasesPointer(llvm::Value const*, unsigned long, llvm::AAMDNodes const&, llvm::AAResults&) const
#&#8203;19 0x000056535a8b6500 llvm::AliasSetTracker::mergeAliasSetsForPointer(llvm::Value const*, unsigned long, llvm::AAMDNodes const&)
#&#8203;20 0x000056535a8b74b3 llvm::AliasSetTracker::getAliasSetForPointer(llvm::Value*, unsigned long, llvm::AAMDNodes const&)
#&#8203;21 0x000056535a8b8cf1 llvm::AliasSetTracker::addPointer(llvm::Value*, unsigned long, llvm::AAMDNodes const&, llvm::AliasSet::AccessLattice)
#&#8203;22 0x000056535a8b8fa1 llvm::AliasSetTracker::add(llvm::StoreInst*)
#&#8203;23 0x000056535a8ba417 (anonymous namespace)::AliasSetPrinter::runOnFunction(llvm::Function&)

**Comment by fhahn** [comment]
I am unable to reproduce this on current `main` so this likely has been fixed: https://godbolt.org/z/hGEEP9KEe

Please re-open the issue with additional info if you are still able to reproduce it.
