### ISSUE TITLE
debuginfo-tests failing

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33146]
|  |  |
| --- | --- |
| Bugzilla Link | [33799](https://llvm.org/bz33799) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The repo can be found here:
http://llvm.org/git/debuginfo-tests.git
Check it out into tools/clang/test/debuginfo-tests  and run  make check-clang

I ran the tests as part of stage one tests (clang-dev being compiled by clang 4.0.0)

These tests were failing:

    Clang :: debuginfo-tests/asan.c
    Clang :: debuginfo-tests/dbg-arg.c
    Clang :: debuginfo-tests/safestack.c
    Clang :: debuginfo-tests/stack-var.c

CMake setup:

cmake ../llvm -G "Ninja" \
	-DCMAKE_BUILD_TYPE=Release \
	-DLLVM_BINUTILS_INCDIR=/usr/include \
	-DCMAKE_C_FLAGS="-march=native -O3 -g0 -DNDEBUG" \
	-DCMAKE_CXX_FLAGS="-march=native -O3 -g0 -DNDEBUG" \
	-DLLVM_PARALLEL_LINK_JOBS=1 \
	-DLLVM_TARGETS_TO_BUILD="X86" \
	-DLLVM_OPTIMIZED_TABLEGEN=1 \
	-DLLVM_BUILD_TOOLS=0 

clang @ 07af1d2a4e1c80ccd8fbafe785c163a8ca43cec3 / 
git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@308084 91177308-0d34-0410-b5e6-96231b3b80d8

lit.py: /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/lit.cfg:200: note: using clang: '/home/matthias/LLVM/LLVM_dev/stage_1/build/./bin/clang'
FAIL: Clang :: debuginfo-tests/asan.c (9138 of 11042)
******************** TEST 'Clang :: debuginfo-tests/asan.c' FAILED ********************
Script:
--
/home/matthias/LLVM/LLVM_dev/stage_1/build/./bin/clang  --target=x86_64-unknown-linux-gnu -arch x86_64 /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/asan.c -o /home/matthias/LLVM/LLVM_dev/stage_1/build/tools/clang/test/debuginfo-tests/Output/asan.c.tmp.out -g -fsanitize=address
/home/matthias/LLVM/LLVM_dev/stage_1/llvm/utils/test_debuginfo.pl  /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/asan.c /home/matthias/LLVM/LLVM_dev/stage_1/build/tools/clang/test/debuginfo-tests/Output/asan.c.tmp.out
--
Exit Code: 1

Command Output (stderr):
--
clang-5.0: warning: argument unused during compilation: '-arch x86_64' [-Wunused-command-line-argument]
/home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/asan.c:38:3: error: use of undeclared identifier '__block'
  __block int x = 42;
  ^
1 error generated.

--

********************
FAIL: Clang :: debuginfo-tests/safestack.c (9142 of 11042)
******************** TEST 'Clang :: debuginfo-tests/safestack.c' FAILED ********************
Script:
--
/home/matthias/LLVM/LLVM_dev/stage_1/build/./bin/clang  --target=x86_64-unknown-linux-gnu -arch x86_64 /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/safestack.c -o /home/matthias/LLVM/LLVM_dev/stage_1/build/tools/clang/test/debuginfo-tests/Output/safestack.c.tmp.out -g -fsanitize=safe-stack
/home/matthias/LLVM/LLVM_dev/stage_1/llvm/utils/test_debuginfo.pl  /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/safestack.c /home/matthias/LLVM/LLVM_dev/stage_1/build/tools/clang/test/debuginfo-tests/Output/safestack.c.tmp.out
--
Exit Code: 1

Command Output (stderr):
--
clang-5.0: warning: argument unused during compilation: '-arch x86_64' [-Wunused-command-line-argument]
/usr/bin/ld: error: cannot open /home/matthias/LLVM/LLVM_dev/stage_1/build/lib/clang/5.0.0/lib/linux/libclang_rt.safestack-x86_64.a: No such file or directory
/home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/safestack.c:14: error: undefined reference to '__safestack_unsafe_stack_ptr'
/home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/safestack.c:22: error: undefined reference to '__safestack_unsafe_stack_ptr'
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)

--

********************
FAIL: Clang :: debuginfo-tests/dbg-arg.c (9143 of 11042)
******************** TEST 'Clang :: debuginfo-tests/dbg-arg.c' FAILED ********************
Script:
--
/home/matthias/LLVM/LLVM_dev/stage_1/build/./bin/clang  --target=x86_64-unknown-linux-gnu -arch x86_64 -mllvm -fast-isel=false  /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/dbg-arg.c -c -o /home/matthias/LLVM/LLVM_dev/stage_1/build/tools/clang/test/debuginfo-tests/Output/dbg-arg.c.tmp.o -g
/home/matthias/LLVM/LLVM_dev/stage_1/build/./bin/clang  --target=x86_64-unknown-linux-gnu -arch x86_64 /home/matthias/LLVM/LLVM_dev/stage_1/build/tools/clang/test/debuginfo-tests/Output/dbg-arg.c.tmp.o -o /home/matthias/LLVM/LLVM_dev/stage_1/build/tools/clang/test/debuginfo-tests/Output/dbg-arg.c.tmp.out
/home/matthias/LLVM/LLVM_dev/stage_1/llvm/utils/test_debuginfo.pl  /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/dbg-arg.c /home/matthias/LLVM/LLVM_dev/stage_1/build/tools/clang/test/debuginfo-tests/Output/dbg-arg.c.tmp.out
--
Exit Code: 1

Command Output (stdout):
--
Debugger output was:
Breakpoint 1 at 0x400503: file /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/dbg-arg.c, line 26.
warning: the debug information found in "/usr/lib/debug//lib64/ld-2.24.so.debug" does not match "/lib64/ld-linux-x86-64.so.2" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/ld-2.24.so.debug" does not match "/lib64/ld-linux-x86-64.so.2" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libc-2.24.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.24.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

Breakpoint 1, foobar (mutex=0x7fffffffe920) at /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/dbg-arg.c:26
26	  int l = 0;
$1 = (struct _mtx *) 0x7fffffffe920
A debugging session is active.

	Inferior 1 [process 29512] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]

--
Command Output (stderr):
--
clang-5.0: warning: argument unused during compilation: '-arch x86_64' [-Wunused-command-line-argument]
/home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/dbg-arg.c:32:9: warning: implicit declaration of function 'bar' is invalid in C99 [-Wimplicit-function-declaration]
    j = bar(r, l);
        ^
1 warning generated.
clang-5.0: warning: argument unused during compilation: '-arch x86_64' [-Wunused-command-line-argument]
/home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/dbg-arg.c:9:11: error: expected string not found in input
// CHECK: ={{.*}} 0x0
          ^
/home/matthias/LLVM/LLVM_dev/stage_1/build/tools/clang/test/debuginfo-tests/Output/dbg-arg.c.gdb.output:1:1: note: scanning from here
Breakpoint 1 at 0x400503: file /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/dbg-arg.c, line 26.
^
/home/matthias/LLVM/LLVM_dev/stage_1/build/tools/clang/test/debuginfo-tests/Output/dbg-arg.c.gdb.output:13:16: note: possible intended match here
$1 = (struct _mtx *) 0x7fffffffe920
               ^

--

********************
FAIL: Clang :: debuginfo-tests/stack-var.c (9146 of 11042)
******************** TEST 'Clang :: debuginfo-tests/stack-var.c' FAILED ********************
Script:
--
/home/matthias/LLVM/LLVM_dev/stage_1/build/./bin/clang  --target=x86_64-unknown-linux-gnu /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/stack-var.c -O -o /home/matthias/LLVM/LLVM_dev/stage_1/build/tools/clang/test/debuginfo-tests/Output/stack-var.c.tmp.out -g
/home/matthias/LLVM/LLVM_dev/stage_1/llvm/utils/test_debuginfo.pl  /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/stack-var.c /home/matthias/LLVM/LLVM_dev/stage_1/build/tools/clang/test/debuginfo-tests/Output/stack-var.c.tmp.out
--
Exit Code: 1

Command Output (stdout):
--
Debugger output was:
Breakpoint 1 at 0x400500: file /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/stack-var.c, line 12.
warning: the debug information found in "/usr/lib/debug//lib64/ld-2.24.so.debug" does not match "/lib64/ld-linux-x86-64.so.2" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/ld-2.24.so.debug" does not match "/lib64/ld-linux-x86-64.so.2" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libc-2.24.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.24.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

Breakpoint 1, main () at /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/stack-var.c:17
17	  return test;
$1 = 23
Breakpoint 2 at 0x400500: file /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/stack-var.c, line 17.
[Inferior 1 (process 29580) exited with code 027]
/home/matthias/LLVM/LLVM_dev/stage_1/build/tools/clang/test/debuginfo-tests/Output/stack-var.c.debugger.script:6: Error in sourced command file:
No symbol "test" in current context.

--
Command Output (stderr):
--
/home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/stack-var.c:16:12: error: expected string not found in input
 // CHECK: 23
           ^
/home/matthias/LLVM/LLVM_dev/stage_1/build/tools/clang/test/debuginfo-tests/Output/stack-var.c.gdb.output:14:1: note: scanning from here
Breakpoint 2 at 0x400500: file /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/stack-var.c, line 17.
^
/home/matthias/LLVM/LLVM_dev/stage_1/build/tools/clang/test/debuginfo-tests/Output/stack-var.c.gdb.output:14:12: note: possible intended match here
Breakpoint 2 at 0x400500: file /home/matthias/LLVM/LLVM_dev/stage_1/llvm/tools/clang/test/debuginfo-tests/stack-var.c, line 17.
           ^

--

**Comment by arsenm** [comment]
Old build issue
