### ISSUE TITLE
PowerPC64: Code built with -mcpu=power9 hits select issue

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33155]
|  |  |
| --- | --- |
| Bugzilla Link | [33808](https://llvm.org/bz33808) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @echristo,@hfinkel,@nemanjai |

## Extended Description 
I'm hitting an error with the following test case:

typedef struct {
        short b, c, d, e;
} f;
char g;
f *h;
int i;
void j(void)
{
        short k;
        for (; i; i++) {
                h->b = h->c = h->d = k = 257 * g;
                h->e = k;
                h++;
        }
}

# clang -O2 -mcpu=power9 test.i

fatal error: error in backend: Cannot select: 0x127a99d10: v8i16 = BUILD_VECTOR Constant:i32<257>, Constant:i32<257>, Constant:i32<257>, Constant:i32<257>, Constant:i32<257>, Constant:i32<257>, Constant:i32<257>,
      Constant:i32<257>
  0x127a99c40: i32 = Constant<257>
  0x127a99c40: i32 = Constant<257>
  0x127a99c40: i32 = Constant<257>
  0x127a99c40: i32 = Constant<257>
  0x127a99c40: i32 = Constant<257>
  0x127a99c40: i32 = Constant<257>
  0x127a99c40: i32 = Constant<257>
  0x127a99c40: i32 = Constant<257>
In function: j
clang-3.9: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 5.0.0 (git://github.com/llvm-mirror/clang.git 3c1756a95139610e837bfd6c992d45950f18db75) (https://github.com/llvm-mirror/llvm.git 40d67727c7971b006a0ccd28a2f8992e22b9ea26)
Target: powerpc64le-unknown-linux-gnu

**Comment by nemanjai** [comment]
This has long since been fixed. Not sure why I never closed it.
