### ISSUE TITLE
-warn-objc-unused-ivars reports 'isa' as unused variable in root classes

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#3321]
|  |  |
| --- | --- |
| Bugzilla Link | [2949](https://llvm.org/bz2949) |
| Version | unspecified |
| OS | All |
| Attachments | [Test case for -warn-objc-unused-ivars](https://user-images.githubusercontent.com/60944935/143738417-29bbfd80-0e85-4fb2-8d3f-d3bb533cfdde.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

I think there's a false positive in unused ivar checker, although the case I describe here is pretty rare in average ObjC projects.

Each ObjC instance must have an instance variable of type 'Class' with name 'isa'. NSObject defines it, and since NSObject is used almost always as a parent class for every other class, the 'isa' doesn't have to be defined in subclasses. 

However, Objective-C allows for the declaration of new root classes which do not inherit any existing functionality. However, 'isa' variable still must be defined [1], since it enables the ObjC runtime to determine the class of each instance.

The isa variable is almost never accessed directly by code, so objc-unused-ivars check shouldn't warn about those cases.

Test case included.

[1] http://lists.apple.com/archives/objc-language/2005/Sep/msg00019.html

P.S. A potential new check which stems from this requirement could make sure that each new root class defines the 'isa' variable with type 'Class'. However, this is a separate issue and should be probably put into its own PR. It would be also nice to get some input for this check from Obj-C runtime people at Apple - if ObjC runtime really requires the 'isa' variable, then maybe it should be a compiler warning instead of analyzer warning?

**Comment by JOE1994** [comment]
`clang -cc1 -Wunused-property-ivar test.m -verify` no longer reports '`isa`' as unused variable in root classes
(Checked with locally built Clang 19 @ `012d217174e28dc000ba1f437827cd23ec5ef606`).

(compiler explorer doesn't yet support using clang for objective-c files)
