### ISSUE TITLE
-falign-functions not supported

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33254]
|  |  |
| --- | --- |
| Bugzilla Link | [33907](https://llvm.org/bz33907) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
% gcc -falign-functions=32 -O3 test.c -S -o -  | grep align
        .p2align 5,,31
% clang -falign-functions=32 -O3 test.c -S -o -  | grep align
clang-6.0: warning: optimization flag '-falign-functions=32' is not supported [-Wignored-optimization-argument]
        .p2align        4, 0x90

**Comment by arsenm** [comment]
Works now
