### ISSUE TITLE
-Wcast-qual should not warn about dropping 'const' when casting to ObjC types

### ISSUE THREAD

**Issue by belkadan** [llvm/llvm-project#33276]
|  |  |
| --- | --- |
| Bugzilla Link | [33929](https://llvm.org/bz33929) |
| Version | trunk |
| OS | MacOS X |

## Extended Description 
// clang -fsyntax-only -x objective-c -Weverything -
id reinterpretAsObject(const void *ptr) {
  return (id)ptr;
}

<stdin>:2:14: warning: cast from 'const void *' to 'id' drops const qualifier
      [-Wcast-qual]
  return (id)ptr;
             ^

...however, there's no way to avoid this warning; you can't const-qualify Objective-C object types inside the pointer. It might have been better if this weren't a common idiom on Apple platforms, but it is---both 'const void *' and opaque pointers to const struct types are sometimes valid Objective-C objects, and casts to 'id', 'Class', or concrete object pointer types like 'NSString *' are considered common and acceptable.

(If we /were/ to start warning on these all the time, they should be silenced by adding '__bridge', and the warning should have a fix-it. But even that's probably too much churn for Apple platforms.)

**Comment by Endilll** [comment]
Fixed in Clang 5
https://godbolt.org/z/GnWT8vqz7
