### ISSUE TITLE
Clang-tidy fails to find LLVM STL headers with --

### ISSUE THREAD

**Issue by EugeneZelenko** [llvm/llvm-project#33299]
|  |  |
| --- | --- |
| Bugzilla Link | [33952](https://llvm.org/bz33952) |
| Version | unspecified |
| OS | Linux |
| CC | @jwillikers |

## Extended Description 
4.0.1 and trunk (as of r309016) fails to locate LLVM STL headers when Clang command line parameters (including path to Clang) are specified after --. At same time it works with compile database.

For example, I got

include/llvm/MC/MachineLocation.h:18:10: error: 'cstdint' file not found [clang-diagnostic-error]

for llvm-svn.src/lib/Target/Hexagon/HexagonConstPropagation.cpp. Clang command line parameters for -- were copied from compile database.

**Comment by carlosgalvezp** [comment]
No longer reproducible on trunk, please open a new ticket with a minimal example if the problem persists.
