### ISSUE TITLE
clang-format unexpected token with "}" a comment block

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33309]
|  |  |
| --- | --- |
| Bugzilla Link | [33962](https://llvm.org/bz33962) |
| Version | 5.0 |
| OS | Windows XP |
| Attachments | [Used .clang-format configuration file](https://user-images.githubusercontent.com/60944935/143756039-5c91e71d-d608-4fa5-a71b-92a23dae656a.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

The following code causes an error in clang-format:
```
void f()
{
    if (true)
    {
        /*Hello*/}
}
```
The error message is: `'5' is unexpected token. The expected token is '"' or ''. Line2, position 66.`

By moving the closing `}` to the next line, the error is gone:
```
void f()
{
    if (true)
    {
        /*Hello*/
    }
}
```

**Comment by mkurdej** [comment]
Not reproducible. Tested with all versions since 5.0.2.
