### ISSUE TITLE
OpenMP documentation is non-existent

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#33365]
|  |  |
| --- | --- |
| Bugzilla Link | [34018](https://llvm.org/bz34018) |
| Version | unspecified |
| OS | All |
| Depends On | llvm/llvm-project#33364  |

## Extended Description 
This is a cross-reference from clang-bug 34017 so that the correct people get pinged. Basically implementing OpenMP in clang has taken years and been a titanic amount of work, but without user documentation, it is hard for anybody to use it.

**Comment by arsenm** [comment]
Duplicate #33364
