### ISSUE TITLE
wrong code with -loop-reroll

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33376]
|  |  |
| --- | --- |
| Bugzilla Link | [34029](https://llvm.org/bz34029) |
| Version | trunk |
| OS | All |
| Attachments | [bitcode](https://user-images.githubusercontent.com/60944935/143756066-ff70a226-8fe1-4856-985e-74ba851c534f.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @coffezhou,@efriedma-quic,@filcab,@zmodem,@hfinkel |

## Extended Description 
$ ./opt ~/pat.bc | ./lli
checksum = 74640FC
$ ./opt -loop-reroll ~/pat.bc | ./lli
checksum = A3DD5B7F

I'll try to reduce this once I get a chance, but putting it here so it doesn't get lost.
Also, cc:in Hal and Eli who both did some work in this area recent('ish)ly.

**Comment by nikic** [comment]
The LoopReroll pass has been removed by https://github.com/llvm/llvm-project/pull/80972.
