### ISSUE TITLE
readability-container-size-empty should manage better ternary operator

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#33408]
|  |  |
| --- | --- |
| Bugzilla Link | [34061](https://llvm.org/bz34061) |
| Version | unspecified |
| OS | Linux |
| CC | @EugeneZelenko,@Xazax-hun |

## Extended Description 
With this checker http://clang.llvm.org/extra/clang-tidy/checks/readability-container-size-empty.html

When we have 

return mIdeal.size() ? mIdeal : defaultValue;

currently, it is converted to:
return !mIdeal.empty() ? mIdeal : defaultValue;

Returning
return mIdeal.empty() ? defaultValue : mIdeal;

Would probably make more sense!

**Comment by EugeneZelenko** [comment]
Works in main. Looks like this was fixed in a5311d731e1b95e93b35b1e9183a4a531df386e7. At least relevant test was added in this patch.
