### ISSUE TITLE
division 1/a may be optimized better

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33410]
|  |  |
| --- | --- |
| Bugzilla Link | [34063](https://llvm.org/bz34063) |
| Version | 3.9 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @RKSimon,@rotateright |

## Extended Description 
Really it is platform-independent optimization bug. Lets look it on x86:
```
int a = 1;

int
main ()
{
  int f = 1 / a;
  return (f == 1) ? 0 : 1;
}
```
compile with:

clang -v
clang version 3.9.0 (tags/RELEASE_390/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix

command line:

clang -S -O2 div-bug.c

You shall see:
```
main:
        .cfi_startproc
# BB#0:                                 # %entry
        movl    a(%rip), %eax
        leal    1(%rax), %ecx
        cmpl    $3, %ecx
        sbbb    %cl, %cl
        cmpl    $1, %eax
        sete    %al
        andb    %cl, %al
        movzbl  %al, %eax
        xorl    $1, %eax
        retq
```
Comparison with 3 in assembler definitely unncessary.

Real problem is in platform independent instruction combiner. It transforms:
```
  %0 = load i32, i32* @a, align 4, !tbaa !1
  %div = sdiv i32 1, %0
  %cmp = icmp eq i32 %div, 1
```
to
```
  %0 = load i32, i32* @&#8203;a, align 4, !1
  %1 = add i32 %0, 1
  %2 = icmp ult i32 %1, 3
  %cmp2 = icmp eq i32 %0, 1
  %cmp = and i1 %2, %cmp2
```
Of course check if %1 less then 3 is excessive for this case.

**Comment by RKSimon** [comment]
Fixed in trunk - test coverage added at 4f97aa7e1d70f1b259e5fddd85de05235b01b192
