### ISSUE TITLE
Improve optimized debug info for escaped variables that live in memory

### ISSUE THREAD

**Issue by rnk** [llvm/llvm-project#33483]
|  |  |
| --- | --- |
| Bugzilla Link | [34136](https://llvm.org/bz34136) |
| Version | trunk |
| OS | Windows NT |
| CC | @adrian-prantl,@chandlerc,@chrisjbris,@dwblaikie,@dpxf,@echristo,@zmodem,@hfinkel,@jmorse,@jimingham,@jrmuizel,@jdm,@lhames,@jasonmolenda,@nico,@OCHyams,@pogo59 |

## Extended Description 
Consider:

```
int getint(void);
void alias(char *);
void crash(void);
void f() {
  int x = getint();
  int y = getint();
  int z = getint();
  alias((char*)&x);
  alias((char*)&y);
  alias((char*)&z);
  crash();
}
```

InstCombine runs LowerDbgDeclares on this code, and we end up with very poor debug info. We basically say that x, y, and z live in EAX after each call to getint, and they are immediately clobbered, never to be available again.

Those casts to char* also prevent the transform from adding more dbg.values that would extend the range.

This was reduced from http://crbug.com/753934

**Comment by OCHyams** [comment]
I think it might be time to close this ticket. Using [assignment tracking](https://discourse.llvm.org/t/rfc-assignment-tracking-a-better-way-of-specifying-variable-locations-in-ir/62367), which is enabled by default for Non-O0, non-LTO builds which are not tuned for LLDB  ([conditions in code](https://github.com/llvm/llvm-project/blob/a1c736ec08f25e83552b20c94a5b2afdcd021a40/clang/lib/CodeGen/BackendUtil.cpp#L860)), we use emit a single location - the stack location - for all the variables in the original reproducer ([godbolt](https://godbolt.org/z/GPTYKzjKM)).

With assignment tracking disabled we still get better coverage now for the variables than is reported in the original summary ([goldbolt](https://godbolt.org/z/jGMdahccT)). Each variable has a location list of: eax until eax is clobbered, then the stack location at the escaping call for that variable.

**Comment by rnk** [comment]
What is the story for `llvm::LowerDbgDeclare`? I think Chrome still uses the flag I added as a workaround to turn that off:
https://source.chromium.org/chromium/chromium/src/+/main:build/config/compiler/BUILD.gn;l=582?q=instcombine-lower-dbg-declare&ss=chromium&start=11

For tracking purposes, is there some other issue Chromium should follow which tracks what we need to do to remove that flag and still get good debug info?

**Comment by rnk** [comment]
I think most debugging happens on Windows, so we're using PDBs and Codeview. From reading the clang sources, it suggests that we are still using the default debugger tuning of gdb. We really ought to add an entry in the tuning enum to cover Windows debuggers.

In any case, it sounds like we aren't using the new mode yet, and the next step is to try it and evaluate it.
