### ISSUE TITLE
Clang-Format: Option AlignConsecutiveAssignments not working with Statement-Expressions

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33499]
|  |  |
| --- | --- |
| Bugzilla Link | [34151](https://llvm.org/bz34151) |
| Version | 5.0 |
| OS | MacOS X |
| Attachments | [clang-format configuration file](https://user-images.githubusercontent.com/60944935/143756132-b7cc0bf2-e35d-406e-82fe-dbfa908a0ca1.gz), [text example](https://user-images.githubusercontent.com/60944935/143756133-367bcfb3-8561-479e-a6da-de0503524e36.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mkurdej |

## Extended Description 

Hello,

it seems like the open `AlignConsecutiveAssignments` in combination with statement expressions is not working correctly (anymore).

All equal signs are placed on the first lines equal sign, if possible.

This leads to some weird formatting if the name is too short or very long.

```
#include <stdio.h>

int test() {
  // If the name (a) is short the formatting is off
  int a = ({
    int b= 1;
    int c= b + 1;
    int d= c + 1;
    d
  });

  /**
   * Is it possible to have it that way?
   */
  //  int a = ({
  //    int b = 1;
  //    int c = b + 1;
  //    int d = c + 1;
  //    d
  //  });

  // ------------------------------

  // It seems not so bad here, but if the longerName gets event longer it
  // becomes worse
  int longerName = ({
    int bb       = 1;
    int cccc     = b + 1;
    int dd       = c + 1;
    d;
  });

  int somethingRidiculousLongProbablyWithBadNamingAndATpyo = ({
    int bb                                                 = 1;
    int cccc                                               = b + 1;
    int dd                                                 = c + 1;
    d;
  });

  /**
   * I think this would be the right formatting.
   */
  //  int somethingRidiculousLongProbablyWithBadNamingAndATpyo = ({
  //    int bb   = 1;
  //    int cccc = b + 1;
  //    int dd   = c + 1;
  //    d;
  //  });

  return a;
}
```

The .clang-format file is as following
```
---
Language:         Cpp
BasedOnStyle:  Google
AlignConsecutiveAssignments: true
...
```

Thank you very much!

**Comment by rymiel** [comment]
Closing as fixed as mentioned above
