### ISSUE TITLE
wrong code generated for extern_weak relocation with -pic-level 2 -pic-is-pie -mpie-copy-relocations

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#33496]
|  |  |
| --- | --- |
| Bugzilla Link | [34148](https://llvm.org/bz34148) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Testcase:

extern "C" int printf(const char*, ...);
extern __attribute__((weak)) int n;
int main() { printf("%p\n", &n); }

Built with -pic-level 2 -pic-is-pie -mpie-copy-relocations, we generate this bogus code:

        leaq    .L.str(%rip), %rdi
        leaq    n(%rip), %rsi
        xorl    %eax, %eax
        callq   printf@PLT

Note the %rip-relative lea for n: this is wrong, that relocation type cannot represent the possibility that &n is 0, which happens when the symbol is not defined.

**Comment by rnk** [comment]
This was fixed in b8956a70d3486556b93ea5d5074d340866f16f88
