### ISSUE TITLE
ReplaceAutoPtrCheck.cpp triggers a bug in gcc 4.8

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#33498]
|  |  |
| --- | --- |
| Bugzilla Link | [34150](https://llvm.org/bz34150) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
On Ubuntu trusty
We could try to workaround the crash

/usr/bin/g++-4.8   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I"/build/llvm-toolchain-snapshot-6.0~svn310694/build-llvm/tools/clang/tools/extra/clang-tidy/utils" -I"/build/llvm-toolchain-snapshot-6.0~svn310694/tools/clang/tools/extra/clang-tidy/utils" -I"/build/llvm-toolchain-snapshot-6.0~svn310694/tools/clang/include" -I"/build/llvm-toolchain-snapshot-6.0~svn310694/build-llvm/tools/clang/include" -I"/build/llvm-toolchain-snapshot-6.0~svn310694/build-llvm/include" -I"/build/llvm-toolchain-snapshot-6.0~svn310694/include"  -std=c++0x -gsplit-dwarf -Wl,-fuse-ld=gold -fPIC -fvisibility-inlines-hidden -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -O2 -g -DNDEBUG    -fno-exceptions -o CMakeFiles/clangTidyUtils.dir/IncludeSorter.cpp.o -c "/build/llvm-toolchain-snapshot-6.0~svn310694/tools/clang/tools/extra/clang-tidy/utils/IncludeSorter.cpp"
/build/llvm-toolchain-snapshot-6.0~svn310694/tools/clang/tools/extra/clang-tidy/modernize/ReplaceAutoPtrCheck.cpp:199:1: internal compiler error: in output_index_string, at dwarf2out.c:21847
 } // namespace clang
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.

**Comment by JOE1994** [comment]
Closing as the ticket seems outdated.
Please re-open if necessary.
