### ISSUE TITLE
5.0: multiple test failures

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33501]
|  |  |
| --- | --- |
| Bugzilla Link | [34153](https://llvm.org/bz34153) |
| Version | 5.0 |
| OS | Linux |
| Attachments | [build script I use which gets the repos and runs cmake and builds](https://user-images.githubusercontent.com/60944935/143756134-ff71d85d-be08-4ff2-8baa-b565bce15163.gz), [lit log of the failing testsy](https://user-images.githubusercontent.com/60944935/143756135-11afe3d6-f579-435e-94c4-83f59ce7e2e1.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Hi, I get multiple test failures on my machine from the 5.0 branch.

These tests fail:

    AddressSanitizer-x86_64-linux :: TestCases/sanity_check_pure_c.c
    Clang :: debuginfo-tests/asan.c
    Clang :: debuginfo-tests/dbg-arg.c
    Clang :: debuginfo-tests/safestack.c
    Clang :: debuginfo-tests/stack-var.c
    DataFlowSanitizer-x86_64 :: basic.c
    DataFlowSanitizer-x86_64 :: custom.cc
    DataFlowSanitizer-x86_64 :: dump_labels.c
    DataFlowSanitizer-x86_64 :: flags.c
    DataFlowSanitizer-x86_64 :: fncall.c
    DataFlowSanitizer-x86_64 :: label_count.c
    DataFlowSanitizer-x86_64 :: propagate.c
    DataFlowSanitizer-x86_64 :: vararg.c
    XRay-x86_64-linux :: TestCases/Linux/always-never-instrument.cc
    XRay-x86_64-linux :: TestCases/Linux/fdr-mode.cc
    XRay-x86_64-linux :: TestCases/Linux/fdr-thread-order.cc
    lldb :: Expr/TestCallStdStringFunction.test
    lldb :: Expr/TestCallStopAndContinue.test
    lldb :: Expr/TestCallUserAnonTypedef.test
    lldb :: Expr/TestCallUserDefinedFunction.test
    lldb-Unit :: tools/lldb-server/tests/./LLDBServerTests/ThreadsInJstopinfoTest.TestStopReplyContainsThreadPcsLlgs

The results are from 10th of August.

I attached my script which runs the tests as well as the log of the failing tests.

Thanks.

**Comment by arsenm** [comment]
Old build failures
