### ISSUE TITLE
std::map operator< stack frame size consumption

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#33536]
|  |  |
| --- | --- |
| Bugzilla Link | [34188](https://llvm.org/bz34188) |
| Version | unspecified |
| OS | Linux |
| CC | @ahatanak,@dwblaikie,@joker-eph,@ldionne,@mclow |

## Extended Description 
This could be either expected, or be a libcxx implementation defect, or clang missing optimization, or any combination of those.

Reduced testcase:
```c++
#include <map>
#include <memory>
#include <string>
struct a;
struct b
{
  std::string c;
  std::string f;
  std::string d;
  int operator<(b e) const
  {
    return tie(c, f, d) < tie(c, f, e.d);
  }
};
struct j
{
  std::map<b, std::unique_ptr<a> > cameras;
  const a *g(const std::string &, const std::string &, const std::string &) const;
};
using std::string;
inline b h(string, string, string)
{
  b i;
  return i;
}
const a *j::g(const string &c, const string &f, const string &d) const
{
  auto camera = cameras.find(h(0, 0, 0));
  return camera->second.get();
}
```

Compilation flags: -std=c++14 -c -Wframe-larger-than=0 cxx.cpp
Here is a comparison of stack frame size usage in function 'b::operator<':
```
/ --------------------------\
|======| libcxx | libstdc++ |
| -O3  |  n/a   |    n/a    |
| -O2  |  n/a   |    n/a    |
| -O1  |  72b   |    88b    |
| -O0  |  4840b |    88b    |
| noop |  4840b |    88b    |
\---------------------------/
```
The measurements were made with clang tip, libcxx tip (compiled in release build mode, no sanitizations)

**Comment by philnik777** [comment]
This has been fixed in LLVM 8: https://godbolt.org/z/EWhzrr5aP
