### ISSUE TITLE
[clang-format] ColumnLimit: 0 together with AlignTrailingComments: true breaks formatting

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33578]
|  |  |
| --- | --- |
| Bugzilla Link | [34230](https://llvm.org/bz34230) |
| Version | unspecified |
| OS | Windows NT |
| Attachments | [Clang Format Config](https://user-images.githubusercontent.com/60944935/143756163-b10a52df-7aa7-47d3-afc9-c19e1944de50.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

If I adjust the `ColumnLimit` to 0 in the attached config, then the `AlignTrailingComments = true`
does not work anymore... 

based on VisualStudioTools from SVN r310867.
```
A = aasdasd; //!< asdasdasd
A = asd; //!< asdasd
```
--->
```
A = aasdasd;  //!< asdasdasd
A = asd;      //!< asdasd
```

**Comment by mkurdej** [comment]
Fixed since at least version 7.
