### ISSUE TITLE
prefetch instruction is not accepted in inline asm, sparc

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33574]
|  |  |
| --- | --- |
| Bugzilla Link | [34226](https://llvm.org/bz34226) |
| Version | trunk |
| OS | Solaris |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Consider the code sample:

] cat prefetch.cpp 
void _Prefetch_read (void *loc, int interval) {
    __asm__ volatile
      ("prefetch [%0+%1], 0" : : "r" (loc), "r" (interval) : "memory" );
  }

int main() {
	int * i = new int[10];
	_Prefetch_read(i, 5);
	return 0;
}

] clang++ prefetch.cpp             
prefetch.cpp:3:8: error: invalid instruction mnemonic
      ("prefetch [%0+%1], 0" : : "r" (loc), "r" (interval) : "memory" );
       ^
<inline asm>:1:2: note: instantiated into assembly here
        prefetch [%i0+%i1], 0
        ^
1 error generated.

] g++ prefetch.cpp 
] a.out 

] CC prefetch.cpp
] a.out

**Comment by brad0** [comment]
This was resolved with ec428f7b780615769b7ca712ff67d05c2c957946.
