### ISSUE TITLE
Wrong size taken for vectorization

### ISSUE THREAD

**Issue by itaraban** [llvm/llvm-project#33631]
|  |  |
| --- | --- |
| Bugzilla Link | [34283](https://llvm.org/bz34283) |
| Version | trunk |
| OS | All |
| CC | @ayalz,@itaraban |

## Extended Description 
==============nice.c=================
#include "stdio.h"
#define M 32
#define N 2 * M
unsigned int a [N];
int main ()
{
    unsigned char i = 0;
    for (i = 0; i < N; i += 1)
    {
        a[i] = 0;
    }
    unsigned int j = 0;
    for (j = 0; j < M - 6; ++j)
    {
        a[N - 2 * j] = 69;
        a[N - 12 - 2 * j] = 7;
    }
    for (int i1 = 0; i1 != M; ++i1) printf("%d\n", a[i1]);
    return 0;
}

======================================

>>>clang -v
clang version 6.0.0 (trunk 311429)
...

>>>clang nice.c -O0 -march=skx -o nice_0
>>>clang nice.c -O2 -march=skx -o nice_2
>>>sde -skx -- nice_0 > output_0
>>>sde -skx -- nice_2 > output_2
>>>vimdiff output_0 output_2
+ +-- 12 lines: 0------------|+ +-- 12 lines: 0------
  7                          |  7
  0                          |  0
  69                         |  69
  0                          |  0
  69                         |  69
  0                          |  0
  69                         |  7              #Vector operations intersection
  0                          |  0
  69                         |  7              # here
  0                          |  0
  69                         |  69
  0                          |  0
  69                         |  69
  0                          |  0
  69                         |  69
+ +--  5 lines: 0------------|+ +--  5 lines: 0-------
======================================

We see in debug output, that wrong register size has been chosen for loop vectorization.

>>>clang -mllvm -debug -mllvm -print-after-all nice.c -O2 -march=skx
...
LAA: Positive distance 48 with max VF = 6
Total Dependences: 1
LAA: No unsafe dependent memory operations in loop.  We don't need runtime memory checks.
LV: We can vectorize this loop!
LV: Analyzing interleaved accesses...
LV: Creating an interleave group with:  store i32 7, i32* %arrayidx11, align 8, !tbaa !&#8203;2
LV: Creating an interleave group with:  store i32 69, i32* %arrayidx7, align 8, !tbaa !&#8203;2
LV: The Smallest and Widest types: 32 / 32 bits.
LV: The Widest register is: 384 bits.           
>> Wrong value (maxVF * sizeof(int) * 8 = 192 bits) <<
...

------------------------
Intel Software Engineer
Ilia Taraban

**Comment by MatzeB** [comment]
Last comment indicates this was fixed, closing.
