### ISSUE TITLE
improve support for fuzz targets in LLVM

### ISSUE THREAD

**Issue by kcc** [llvm/llvm-project#33662]
|  |  |
| --- | --- |
| Bugzilla Link | [34314](https://llvm.org/bz34314) |
| Version | unspecified |
| OS | Linux |
| CC | @bogner |

## Extended Description 
Currently, we have only one way to build fuzz targets (e.g. clang-fuzzer) in LLVM: specify  -DLLVM_USE_SANITIZE_COVERAGE=On and -DLLVM_USE_SANITIZER=Address

I would like to have this be more flexible. 

1. Fuzz targets should be built in the default configuration (no asan, no coverage). They won't be suitable for fuzzing this way, but this will ensure that the code still builds (fuzz targets need to be build during check-all)

2. [stretch] each fuzz target foo-fuzz needs to have a build rule check-foo-fuzz that will execute the fuzz target on a fixed set of inputs (from the same repo) as a way of regression testing. This will ensure that the fuzz target not only builds, but runs. This is also a great regression test. 

3. Fuzz targets should work with any of the sanitizers, or with none at all (-DLLVM_USE_SANITIZER=Address should not be mandatory) 

4. There should be a way to specify the compile-time coverage instrumentation flags and link-time fuzzing engine flag. In particular, I'd like to support the env. vars. defined by OSS-Fuzz: CC, CXX, CFLAGS, CXXFLAGS, LIB_FUZZING_ENGINE (by passing these flags to cmake variables). This way we'll be able to build the fuzz targets with e.g. AFL, hoggfuzz, and with Clang Coverage (for coverage visualization)

**Comment by morehouse** [comment]
Most work is done, and bug untouched for nearly 5 years.

Can open new bugs for any additional work we want to do.
