### ISSUE TITLE
non-template friend does not find function template

### ISSUE THREAD

**Issue by 3415b6ac-fb6a-4126-bec9-30864225cf9f** [llvm/llvm-project#33677]
|  |  |
| --- | --- |
| Bugzilla Link | [34329](https://llvm.org/bz34329) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
clang rejects this well-formed code:

template <typename T>
int f(T& obj) { return obj.m; }

class X {
private:
    int m;
    friend int ::f(X&);
};

int main() {
    X x;
    f(x);
}

The error message is:
7 : <source>:7:18: error: out-of-line declaration of 'f' does not match any declaration in the global namespace
    friend int ::f(X&);
                 ^

This situation is described in Standard section [temp.friend].  (The wording was clarified some in C++11, but has the same meaning as in C++03, and has not changed since.)

Quote:

For a friend function declaration that is not a template declaration:

- if the name of the friend is a qualified or unqualified template-id, the friend declaration refers to a specialization of a function template, otherwise,

- if the name of the friend is a qualified-id and a matching non-template function is found in the specified class or namespace, the friend declaration refers to that function, otherwise,

- if the name of the friend is a qualified-id and a matching function template is found in the specified class or namespace, the friend declaration refers to the deduced specialization of that function template ([]), otherwise,

- the name shall be an unqualified-id that declares (or redeclares) a non-template function.

End Quote.

In this code, the first bullet does not apply because ::f is not a template-id (there are no <> tokens).  ::f is a qualfied-id, so the second bullet should be checked, but there is no matching non-template function named ::f.  The third bullet is what makes the code well-formed: the compiler should deduce a specialization of the function template ::f.  Since deduction should succeed, the friend names a specialization of ::f.

(gcc 7.2, icc 17, and MSVC 19.00.23506 all accept the above code.)

**Comment by Quuxplusone** [comment]
Looks like this got fixed in Clang 8 and later.
https://godbolt.org/z/czv3f4Edq
