### ISSUE TITLE
std::copy does not optimise for reverse_iterator.

### ISSUE THREAD

**Issue by e0e1e613-dccb-47a5-85db-3dc989429265** [llvm/llvm-project#33687]
|  |  |
| --- | --- |
| Bugzilla Link | [34339](https://llvm.org/bz34339) |
| Version | unspecified |
| OS | All |
| CC | @mclow |

## Extended Description 
std::copy could unroll 3 reverse_iterators into copy_backward and than do a memmove.
Example: https://godbolt.org/g/G6NWRG

**Comment by philnik777** [comment]
D124328 fixes this.
