### ISSUE TITLE
Wrong code bug: load removed by GVN

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#33692]
|  |  |
| --- | --- |
| Bugzilla Link | [34344](https://llvm.org/bz34344) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Reproducer](https://user-images.githubusercontent.com/55733087/143756217-3047e6d5-52f1-420e-bac9-b9ed5c778478.gz) |
| CC | @bjope,@topperc,@efriedma-quic,@hfinkel,@nunoplopes,@sanjoy |

## Extended Description 

Reproduce with:
opt -S -gvn -o - gvn_input.ll

And you get:

target datalayout = "p:8:8"

define void @&#8203;foo() {
entry:
  %array = alloca [130 x i8], align 1
  br label %for.body

for.body:                                         ; preds = %for.body, %entry
  %i = phi i8 [ 0, %entry ], [ %inc, %for.body ]
  %idx = zext i8 %i to i16
  %addr = getelementptr inbounds [130 x i8], [130 x i8]* %array, i16 0, i16 %idx
  store i8 %i, i8* %addr, align 1
  %inc = add nuw i8 %i, 1
  %exitcond = icmp ne i8 %inc, -126
  br i1 %exitcond, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.body
  %addr2 = getelementptr inbounds [130 x i8], [130 x i8]* %array, i16 0, i16 129
  tail call void @&#8203;bar(i8 undef)
  ret void
}

declare void @&#8203;bar(i8)

Note that now we pass undef to bar instead of the value loaded from index 129
in the local array. The array is initialized in the loop, from index 0 to (but
not including) index 130.

For some reason GVN fails to realize that the loop indeed writes at index 129,
the only dependency it sees when examining the load, is the alloca, and thus
it thinks we read from uninitialized memory, and the load is removed and replaced
with undef.

As far as I can tell, this bug is not new. It was at least present in November 2016.

(Originally found on my out-of-tree target where we have 16b pointers. Loading from
index 32768 then gives the same problems as index 129 in the example above.)

**Comment by bjope** [comment]
As pre previous comment this was solved by https://reviews.llvm.org/D59648 (the original reproducer from https://bugs.llvm.org/show_bug.cgi?id=34344 was added as a lit test). So I'll just close this as it seem to have been working for a couple of years now.
