### ISSUE TITLE
CodeGen/AArch64/machine-outliner-remarks.ll is failing on ubuntu trusty i386

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#33741]
|  |  |
| --- | --- |
| Bugzilla Link | [34393](https://llvm.org/bz34393) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Script:
--
/build/llvm-toolchain-snapshot-6.0~svn312209/build-llvm/./bin/llc /build/llvm-toolchain-snapshot-6.0~svn312209/test/CodeGen/AArch64/machine-outliner-remarks.ll -enable-machine-outliner -mtriple=aarch64-unknown-unknown -pass-remarks-missed=machine-outliner -o /dev/null 2>&1 | /build/llvm-toolchain-snapshot-6.0~svn312209/build-llvm/./bin/FileCheck /build/llvm-toolchain-snapshot-6.0~svn312209/test/CodeGen/AArch64/machine-outliner-remarks.ll
/build/llvm-toolchain-snapshot-6.0~svn312209/build-llvm/./bin/llc /build/llvm-toolchain-snapshot-6.0~svn312209/test/CodeGen/AArch64/machine-outliner-remarks.ll -enable-machine-outliner -mtriple=aarch64-unknown-unknown -o /dev/null -pass-remarks-missed=machine-outliner -pass-remarks-output=/build/llvm-toolchain-snapshot-6.0~svn312209/build-llvm/test/CodeGen/AArch64/Output/machine-outliner-remarks.ll.tmp.yaml
cat /build/llvm-toolchain-snapshot-6.0~svn312209/build-llvm/test/CodeGen/AArch64/Output/machine-outliner-remarks.ll.tmp.yaml | /build/llvm-toolchain-snapshot-6.0~svn312209/build-llvm/./bin/FileCheck /build/llvm-toolchain-snapshot-6.0~svn312209/test/CodeGen/AArch64/machine-outliner-remarks.ll -check-prefix=YAML
--
Exit Code: 1

Command Output (stderr):
--
remark: machine-outliner-remarks.ll:5:9: Did not outline 2 instructions from 2 locations. Instructions from outlining all occurrences (9) >= Unoutlined instruction count (4) (Also found at: machine-outliner-remarks.ll:13:9)
/build/llvm-toolchain-snapshot-6.0~svn312209/test/CodeGen/AArch64/machine-outliner-remarks.ll:28:14: error: expected string not found in input
; YAML-NEXT: - OtherStartLoc1: 'machine-outliner-remarks.ll:13:9'
             ^
<stdin>:38:2: note: scanning from here
 - 4: 'machine-outliner-remarks.ll:13:9'
 ^

--

**Comment by arsenm** [comment]
Old build failure
