### ISSUE TITLE
wrong code in Polly on x86_64-linux-gnu with "opt -sroa -functionattrs -loop-rotate -licm -loop-unswitch -loop-unroll -jump-threading -polly-opt-isl -polly-codegen"

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#33834]
|  |  |
| --- | --- |
| Bugzilla Link | [34486](https://llvm.org/bz34486) |
| Version | unspecified |
| OS | All |
| CC | @tobiasgrosser |

## Extended Description 
$ clangpolly -v
clang version 6.0.0 (http://llvm.org/git/clang.git 5a2b037a53684751a712b11898a0cc69815f2ba7) (http://llvm.org/git/llvm.git 76db91a4f033defd405dfb4d14ba6c0c7e205ce0)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.2.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clangpolly -w -O3 -mllvm -disable-llvm-optzns -c -emit-llvm -o small.bc small.c               
$ optpolly -sroa -functionattrs -loop-rotate -licm -loop-unswitch -loop-unroll -jump-threading -polly-opt-isl -polly-codegen -o small-opt.bc small.bc
$ clangpolly small-opt.bc
$ ./a.out
0
$ 
$ clangpolly -O0 -w small.c; ./a.out
1
$ 

------------------------------------------------------

int printf (const char *, ...);

char fn1 (int e, int f) { return 0; }
int fn2 (int h) { return 0; }

int l, m, n, p, q, r[3][1], s, t, x, y, z, aa, ab;
unsigned o;

void fn3 ()
{
  unsigned ad;
L:;
  int af;
  for (ad = 0; ad < 1; ad++)
    {
      int ag;
      r[ad + 2][ad] || (fn1 (0, 5) && n);
      m = r[1][0] = 15 > p;
      if (!m)
	{
	  if (q)
	    goto L;
	  y = fn1 (t, 0);
	  z = fn2 (y);
	  aa = fn1 (z, s);
	  ab = fn2 (t);
	  (af = fn1 (l, 2)) || (s = fn1 (ab, x) > 10);
	}
    }
  for (; o < 4; o++)
    af;
}

int main ()
{
  fn3 ();
  printf ("%d\n", m);
  return 0;
}

**Comment by fhahn** [comment]
Closing as per the previous comment. Please re-open with additional info if this still reproduces on your end.
