### ISSUE TITLE
Assertion failure (DelayedTypos.empty() && "Uncorrected typos!") in case of multiple typos in expression

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33855]
|  |  |
| --- | --- |
| Bugzilla Link | [34507](https://llvm.org/bz34507) |
| Version | unspecified |
| OS | All |
| Attachments | [Reproducer](https://user-images.githubusercontent.com/60944935/143756283-89442b15-9fbc-48da-bbdf-d6f95c703a41.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

If a chain of member function calls has multiple typos in it clang -cc1 fails with the assertion failure if built with assertion enabled.

To reproduce compile the attached test case:
clang -cc1 typo.cpp

In the expression "z_obj.getY2().getM();" both getY2() and getM() calls are mistyped. The initial AST for this expression:
  CallExpr 0xcda1b01428 '<dependent type>'
  `-CXXDependentScopeMemberExpr 0xcda1b013d0 '<dependent type>' lvalue .getM
    `-CallExpr 0xcda1b013a8 '<dependent type>'
      `-TypoExpr 0xcda1b01398 '<dependent type>' lvalue

The TypoExpr here stands for the getY2() call.

During typo resolution TransformCXXDependentScopeMemberExpr() detects that getM() is also a typo and transforms the whole CXXDependentScopeMemberExpr into a single TypoExpr. The resulting expression after the transformation looks like this:
  CallExpr 0xcda1b01768 '<dependent type>'
  `-TypoExpr 0xcda1b01758 '<dependent type>' lvalue

This newly created TypoExpr does not get into the TypoExprs container and it is not processed by the transform, thereby causing the assertion failure with clang built with assertions enabled or missing typo diagnostics for getM() if assertions are disabled.

**Comment by shafik** [comment]
No longer reproduces on trunk: https://godbolt.org/z/b7zP6nrq9

**Comment by Endilll** [comment]
Doesn't reproduce with assertions builds: https://cexplorer.testlabs.pro/z/4Ef9M7
