### ISSUE TITLE
Clang-cl Bootstrap: APPLICATION_FAULT_INVALID_POINTER_WRITE_clang_cl+1268045

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33889]
|  |  |
| --- | --- |
| Bugzilla Link | [34541](https://llvm.org/bz34541) |
| Version | 5.0 |
| OS | Windows NT |
| Attachments | [clang-cl dump file](https://user-images.githubusercontent.com/60944935/143756289-6fb0f850-4b9d-4102-8f91-5e3197574052.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

When I use Clang 5.0 (Visual C + + 2017) Bootstrap trunk clang, clang frontend command failed due to signal

MSVC: 14.11.25503
Windows 10 Pro

cmdline:

# Crash reproducer for clang version 5.0.0 (clangbuilder.io)
# Driver args: "--driver-mode=cl" "/nologo" "-D" "GTEST_HAS_RTTI=0" "-D" "UNICODE" "-D" "_CRT_NONSTDC_NO_DEPRECATE" "-D" "_CRT_NONSTDC_NO_WARNINGS" "-D" "_CRT_SECURE_NO_DEPRECATE" "-D" "_CRT_SECURE_NO_WARNINGS" "-D" "_DEBUG_POINTER_IMPL=" "-D" "_GNU_SOURCE" "-D" "_HAS_EXCEPTIONS=0" "-D" "_SCL_SECURE_NO_DEPRECATE" "-D" "_SCL_SECURE_NO_WARNINGS" "-D" "_UNICODE" "-D" "__STDC_CONSTANT_MACROS" "-D" "__STDC_FORMAT_MACROS" "-D" "__STDC_LIMIT_MACROS" "-I" "tools\\clang\\lib\\AST" "-I" "F:\\Clangbuilder\\out\\mainline\\tools\\clang\\lib\\AST" "-I" "F:\\Clangbuilder\\out\\mainline\\tools\\clang\\include" "-I" "tools\\clang\\include" "-I" "include" "-I" "F:\\Clangbuilder\\out\\mainline\\include" "-fms-compatibility-version=19.11" "-m64" "/Zc:inline" "-Werror=c++11-compat-deprecated-writable-strings" "-fbuiltin" "/Zc:rvalueCast" "-mno-incremental-linker-compatible" "-WCL4" "-W" "-Wno-unused-parameter" "-Wwrite-strings" "-Wcast-qual" "-Wmissing-field-initializers" "-Wcovered-switch-default" "-Wdelete-non-virtual-dtor" "-Wstring-conversion" "/MT" "/O2" "/Ob2" "-D" "NDEBUG" "/EHs-c-" "/GR-" "--show-includes" "/Fotools\\clang\\lib\\AST\\CMakeFiles\\clangAST.dir\\DeclCXX.cpp.obj" "/Fdtools\\clang\\lib\\AST\\CMakeFiles\\clangAST.dir\\clangAST.pdb" "-c" "F:\\Clangbuilder\\out\\mainline\\tools\\clang\\lib\\AST\\DeclCXX.cpp"
# Original command:  "D:\\LLVM\\bin\\clang-cl.exe" "-cc1" "-triple" "x86_64-pc-windows-msvc19.11.0" "-emit-obj" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "DeclCXX.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-relaxed-aliasing" "-fmath-errno" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-D_MT" "-flto-visibility-public-std" "--dependent-lib=libcmt" "--dependent-lib=oldnames" "--show-includes" "-fno-rtti-data" "-stack-protector" "2" "-fms-volatile" "-fdiagnostics-format" "msvc" "-momit-leaf-frame-pointer" "-dwarf-column-info" "-debugger-tuning=gdb" "-ffunction-sections" "-coverage-notes-file" "F:\\Clangbuilder\\out\\prebuilt\\DeclCXX.gcno" "-resource-dir" "D:\\LLVM\\lib\\clang\\5.0.0" "-D" "GTEST_HAS_RTTI=0" "-D" "UNICODE" "-D" "_CRT_NONSTDC_NO_DEPRECATE" "-D" "_CRT_NONSTDC_NO_WARNINGS" "-D" "_CRT_SECURE_NO_DEPRECATE" "-D" "_CRT_SECURE_NO_WARNINGS" "-D" "_DEBUG_POINTER_IMPL=" "-D" "_GNU_SOURCE" "-D" "_HAS_EXCEPTIONS=0" "-D" "_SCL_SECURE_NO_DEPRECATE" "-D" "_SCL_SECURE_NO_WARNINGS" "-D" "_UNICODE" "-D" "__STDC_CONSTANT_MACROS" "-D" "__STDC_FORMAT_MACROS" "-D" "__STDC_LIMIT_MACROS" "-I" "tools\\clang\\lib\\AST" "-I" "F:\\Clangbuilder\\out\\mainline\\tools\\clang\\lib\\AST" "-I" "F:\\Clangbuilder\\out\\mainline\\tools\\clang\\include" "-I" "tools\\clang\\include" "-I" "include" "-I" "F:\\Clangbuilder\\out\\mainline\\include" "-D" "NDEBUG" "-internal-isystem" "D:\\LLVM\\lib\\clang\\5.0.0\\include" "-internal-isystem" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.11.25503\\ATLMFC\\include" "-internal-isystem" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.11.25503\\include" "-internal-isystem" "C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\include\\um" "-internal-isystem" "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16278.0\\ucrt" "-internal-isystem" "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16278.0\\shared" "-internal-isystem" "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16278.0\\um" "-internal-isystem" "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16278.0\\winrt" "-O2" "-Werror=c++11-compat-deprecated-writable-strings" "-WCL4" "-W" "-Wno-unused-parameter" "-Wwrite-strings" "-Wcast-qual" "-Wmissing-field-initializers" "-Wcovered-switch-default" "-Wdelete-non-virtual-dtor" "-Wstring-conversion" "-fdeprecated-macro" "-fdebug-compilation-dir" "F:\\Clangbuilder\\out\\prebuilt" "-ferror-limit" "19" "-fmessage-length" "0" "-fms-extensions" "-fms-compatibility" "-fms-compatibility-version=19.11" "-std=c++14" "-fdelayed-template-parsing" "-finline-functions" "-fobjc-runtime=gcc" "-fdiagnostics-show-option" "-vectorize-loops" "-vectorize-slp" "-o" "tools\\clang\\lib\\AST\\CMakeFiles\\clangAST.dir\\DeclCXX.cpp.obj" "-x" "c++" "F:\\Clangbuilder\\out\\mainline\\tools\\clang\\lib\\AST\\DeclCXX.cpp"
 "D:\\LLVM\\bin\\clang-cl.exe" "-cc1" "-triple" "x86_64-pc-windows-msvc19.11.0" "-emit-obj" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "DeclCXX.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-relaxed-aliasing" "-fmath-errno" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-D_MT" "-flto-visibility-public-std" "--dependent-lib=libcmt" "--dependent-lib=oldnames" "--show-includes" "-fno-rtti-data" "-stack-protector" "2" "-fms-volatile" "-fdiagnostics-format" "msvc" "-momit-leaf-frame-pointer" "-dwarf-column-info" "-debugger-tuning=gdb" "-ffunction-sections" "-coverage-notes-file" "F:\\Clangbuilder\\out\\prebuilt\\DeclCXX.gcno" "-D" "GTEST_HAS_RTTI=0" "-D" "UNICODE" "-D" "_CRT_NONSTDC_NO_DEPRECATE" "-D" "_CRT_NONSTDC_NO_WARNINGS" "-D" "_CRT_SECURE_NO_DEPRECATE" "-D" "_CRT_SECURE_NO_WARNINGS" "-D" "_DEBUG_POINTER_IMPL=" "-D" "_GNU_SOURCE" "-D" "_HAS_EXCEPTIONS=0" "-D" "_SCL_SECURE_NO_DEPRECATE" "-D" "_SCL_SECURE_NO_WARNINGS" "-D" "_UNICODE" "-D" "__STDC_CONSTANT_MACROS" "-D" "__STDC_FORMAT_MACROS" "-D" "__STDC_LIMIT_MACROS" "-D" "NDEBUG" "-O2" "-Werror=c++11-compat-deprecated-writable-strings" "-WCL4" "-W" "-Wno-unused-parameter" "-Wwrite-strings" "-Wcast-qual" "-Wmissing-field-initializers" "-Wcovered-switch-default" "-Wdelete-non-virtual-dtor" "-Wstring-conversion" "-fdeprecated-macro" "-ferror-limit" "19" "-fmessage-length" "0" "-fms-extensions" "-fms-compatibility" "-fms-compatibility-version=19.11" "-std=c++14" "-fdelayed-template-parsing" "-finline-functions" "-fobjc-runtime=gcc" "-fdiagnostics-show-option" "-vectorize-loops" "-vectorize-slp" "-x" "c++" "DeclCXX-b75c02.cpp"

**Comment by Endilll** [comment]
Old build issue is unlikely to be relevant today.
