### ISSUE TITLE
libc++ build not install c++.dll

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33888]
|  |  |
| --- | --- |
| Bugzilla Link | [34540](https://llvm.org/bz34540) |
| Version | 5.0 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
When I use Clangbuilder Bootstrap libc++, after run cpack or ninja install, c++.dll is not installed.

**Comment by arsenm** [comment]
Old build issue
