### ISSUE TITLE
clang-format breaks operator < with explicit template parameter

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33899]
|  |  |
| --- | --- |
| Bugzilla Link | [34551](https://llvm.org/bz34551) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
clang--format --version:
clang-format version 5.0.0-+rc2-1 (tags/RELEASE_500/rc2)

Example code:

#include <tuple>

struct S {
	int i;
	double d;
	char *cp;
	static constexpr auto get_members() {
		return std::make_tuple(&S::i, &S::d, &S::cp);
	}
};

template <std::size_t index = 0>
bool operator<(const S &lhs, const S &rhs) {
	if constexpr (index < std::tuple_size<decltype(S::get_members())>()) {
		constexpr auto members = S::get_members();
		if (lhs.*std::get<index>(members) < rhs.*std::get<index>(members)) {
			return true;
		} else if (rhs.*std::get<index>(members) < lhs.*std::get<index>(members)) {
			return false;
		} else {
			return operator< <index + 1>(lhs, rhs); //clang-format 5.0 removes space in < < which causes the code to not compile
		}
	}
	return false;
}

Workaround: Replace the space that clang-format removes with a comment

**Comment by mkurdej** [comment]
Duplicate of #30118.
