### ISSUE TITLE
Clang runs indefinitely at -O3

### ISSUE THREAD

**Issue by 4f99a97d-37e2-4b4f-939b-3f5760df598b** [llvm/llvm-project#33917]
|  |  |
| --- | --- |
| Bugzilla Link | [34569](https://llvm.org/bz34569) |
| Version | 5.0 |
| OS | Linux |
| Attachments | [C++ source that brings clang-5 into an infinite loop wiht -O3](https://user-images.githubusercontent.com/92601790/143756303-dfcb007c-a629-4a13-8b7a-e5d3f0b779c1.gz) |
| CC | @DougGregor |

## Extended Description 

The attached reduced C++ code compiles with

clang++-4.0 -emit-llvm -S -O3 -std=c++14 c.ii

as well as with

clang++-5.0 -emit-llvm -S -O2 -std=c++14 c.ii

However, it appears to run indefinitely with

clang++-5.0 -emit-llvm -S -O3 -std=c++14 c.ii

**Comment by shafik** [comment]
Looks like does not reproduce on clang trunk: -emit-llvm -S -O3 -std=c++14
