### ISSUE TITLE
New test case test/MC/BPF/insn-unit.s in r313055 fails on powerpc64 (big endian)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33941]
|  |  |
| --- | --- |
| Bugzilla Link | [34593](https://llvm.org/bz34593) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
It works on powerpc64le so it's probably an endian issue in the test case.

FAIL: LLVM :: MC/BPF/insn-unit.s (28551 of 36022)
******************** TEST 'LLVM :: MC/BPF/insn-unit.s' FAILED ********************
Script:
--
/home/seurer/llvm/build/llvm-test2/./bin/llvm-mc -triple bpf -filetype=obj -o 
/home/seurer/llvm/build/llvm-test2/test/MC/BPF/Output/insn-unit.s.tmp /home/seurer/llvm/llvm-test2/test/MC/BPF/insn-unit.s
/home/seurer/llvm/build/llvm-test2/./bin/llvm-objdump -d -r /home/seurer/llvm/build/llvm-test2/test/MC/BPF/Output/insn-unit.s.tmp | /home/seurer/llvm/build/llvm-test2/./bin/FileCheck /home/seurer/llvm/llvm-test2/test/MC/BPF/insn-unit.s
--
Exit Code: 1

Command Output (stderr):
--
/home/seurer/llvm/llvm-test2/test/MC/BPF/insn-unit.s:11:11: error: expected string not found in input
// CHECK: 28 00 00 00 02 00 00 00 r0 = *(u16 *)skb[2]
          ^
<stdin>:7:2: note: scanning from here
 1: 28 00 00 00 00 00 00 02 r0 = *(u16 *)skb[2]
 ^
<stdin>:7:5: note: possible intended match here
 1: 28 00 00 00 00 00 00 02 r0 = *(u16 *)skb[2]
    ^

--

********************

**Comment by arsenm** [comment]
Old build issue
