### ISSUE TITLE
Please support #pragma clang target

### ISSUE THREAD

**Issue by ba445bc0-1011-4361-8560-c5d362a94dfe** [llvm/llvm-project#34009]
|  |  |
| --- | --- |
| Bugzilla Link | [34661](https://llvm.org/bz34661) |
| Version | trunk |
| OS | Windows NT |
| CC | @DougGregor,@echristo,@hfinkel,@zygoloid |

## Extended Description 
If you want to write an application that automatically uses extended intrinsics if the processor supports them, you have to compile multiple source files with differing target command-line options.  This works at a basic level.

There's one major problem, though: if you have inline or template functions in header files, the compiler will be free to generate code using the extended features for these functions.  If you're unlucky at link time, the linker will choose the copy of these functions that use the extended processor features, causing a crash when they don't exist.

GCC solves this by having pragmas (using the "basic" x86-64 as an example):

#pragma GCC push_options
#pragma GCC target "arch=k8"
#include "MyHeader.h"
#pragma GCC pop_options

Could a #pragma clang target be added for similar purposes?

**Comment by Endilll** [comment]
I can find the attribute mentioned above in documentation (https://clang.llvm.org/docs/AttributeReference.html#target), but I still can't find the pragma author asks for. Are we even willing to support it?

CC @AaronBallman

**Comment by AaronBallman** [comment]
Clang has a different, more general approach for applying attributes to declarations, so I don't think we will implement support for this feature unless it starts showing up in system headers.

In the meantime, I'd recommend using `#pragma clang attribute`, which would look something like (untested):
```
#pragma clang attribute push (__attribute__((target("arch=k8"))), apply_to = function)
#include "MyHeader.h"
#pragma clang attribute pop
```

**Comment by AaronBallman** [comment]
Closing this issue because there's a comparable workaround, but without prejudice in case `#pragma GCC target` starts being used in system headers or another critical context.
