### ISSUE TITLE
clang-format crashes with blank assume-filename

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34015]
|  |  |
| --- | --- |
| Bugzilla Link | [34667](https://llvm.org/bz34667) |
| Version | 4.0 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Overview
--------------------
clang-format crashes when the assume-filename is given a blank string

Steps to Reproduce
--------------------
clang-format -output-replacements-xml -assume-filename '' -offset 0 -length 10 -cursor 5 <<< 'aaaa = 1234;'

Actual Results
--------------------
clang-format -output-replacements-xml -assume-filename '' -offset 0 -length 10 -cursor 5 <<< 'aaaa = 1234;'
0  clang-format             0x0000000106ba765b llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  clang-format             0x0000000106ba6f93 llvm::sys::RunSignalHandlers() + 83
2  clang-format             0x0000000106ba7aaa SignalHandler(int) + 195
3  libsystem_platform.dylib 0x00007fff8d04452a _sigtramp + 26
4  libsystem_platform.dylib 0x00007fff59089ea0 _sigtramp + 3422837136
5  clang-format             0x0000000106bde825 clang::format::Environment::CreateVirtualEnvironment(llvm::StringRef, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>) + 661
6  clang-format             0x0000000106bcc115 clang::format::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, llvm::StringRef, bool*) + 221
7  clang-format             0x0000000106b75892 clang::format::format(llvm::StringRef) + 3655
8  clang-format             0x0000000106b74880 main + 671
9  libdyld.dylib            0x00007fff93d4a5ad start + 1
zsh: segmentation fault  clang-format -output-replacements-xml -assume-filename '' -offset 0 -length 1

Expected Results
--------------------
Should exit with error:
No such file or directory

Clang Format Version
--------------------
clang-format version 4.0.1 (tags/RELEASE_401/final)

**Comment by mydeveloperday** [comment]
For clang-format v13 the errors shows as

```
$ clang-format -output-replacements-xml -assume-filename '' -offset 0 -length 10 -cursor 5 <<< 'aaaa = 1234;'
error: empty filenames are not allowed
```
