### ISSUE TITLE
#include sorting should have a case-insensitive option

### ISSUE THREAD

**Issue by 8e047713-bd9b-482b-8c91-a67787768e7a** [llvm/llvm-project#34026]
|  |  |
| --- | --- |
| Bugzilla Link | [34678](https://llvm.org/bz34678) |
| Version | trunk |
| OS | All |
| CC | @mkurdej |

## Extended Description 
The Swift project has headers in folders called "SIL" and "Sema". clang-format currently sorts these includes as

```
#include "swift/SIL/SILModule.h"
#include "swift/Sema/IDETypeChecking.h"
```

But we'd prefer a case-insensitive sort.

**Comment by mydeveloperday** [comment]
This can be handled by using the CaseInsensivite settting

https://clang.llvm.org/docs/ClangFormatStyleOptions.html

![image](https://user-images.githubusercontent.com/16046346/145820136-e4089a8c-d1ea-40b2-8278-be22e0539066.png)
