### ISSUE TITLE
Regression: Referencing labels across asm blocks results in bad asm since 4.0.0

### ISSUE THREAD

**Issue by CyberShadow** [llvm/llvm-project#34056]
|  |  |
| --- | --- |
| Bugzilla Link | [34708](https://llvm.org/bz34708) |
| Version | 4.0 |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
///////////// test.cpp ////////////
```cpp
bool test()
{
  __asm mov byte ptr [magic], 0x90;
  __asm {
    magic:
      nop
  };
}
```

$ clang -c -m32 -target i386-pc-windows-msvc18.0.0 test.cpp 
test.cpp:3:3: error: assembler label 'L__MSASMLABEL_.0__magic' can not be undefined
  __asm mov byte ptr [magic], 0x90;
  ^
<inline asm>:2:2: note: instantiated into assembly here
        mov byte ptr L__MSASMLABEL_.0__magic, 0x90
        ^
1 error generated.

Looking at the emitted assembly, it looks like Clang/LLVM uses the "L__MSASMLABEL_.0__magic" label when referring to the address of the "magic" label, but actually defines the label with the name "L__MSASMLABEL_.1__magic". In 3.9.1 "L__MSASMLABEL_.0__magic" is used throughout.

This pattern is necessary for MSVC compatibility with programs using self-modifying code.

**Comment by wheatman** [comment]
I can't reproduce this on the specified version or anything nearby
https://godbolt.org/z/4Ev3994vc

If this is still an issue feel free to reopen with a reproducer
