### ISSUE TITLE
wrong code with opt "-sroa -loop-rotate -licm -simplifycfg -loop-unroll -slp-vectorizer -latesimplifycfg -instcombine -loop-reroll"

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#34093]
|  |  |
| --- | --- |
| Bugzilla Link | [34745](https://llvm.org/bz34745) |
| Version | trunk |
| OS | All |

## Extended Description 
$ clangpolly -v
clang version 6.0.0 (http://llvm.org/git/clang.git f475b581cc5a98d8b44e476884245ecfe7d33051)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.2.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clangpolly -O3 -mllvm -disable-llvm-optzns -c -emit-llvm -o small.bc small.c
$ optpolly -sroa -loop-rotate -licm -simplifycfg -loop-unroll -slp-vectorizer -latesimplifycfg -instcombine -loop-reroll -o small-opt.bc small.bc
$ clangpolly small-opt.bc; ./a.out
Segmentation fault (core dumped)
$ 
$ clangpolly -O0 small.c; ./a.out
$ 

--------------------------------------

int a, b[64];

int main ()
{
  while (1)
    {
      int c;
      for (; a < 8; a++)
	for (c = 0; c < 8; c++)
	  b[a * 8 + c] = 0;
      break;
    }
  return 0; 
}

**Comment by fhahn** [comment]
It looks like the issue was an incorrect SCEV expansion, fixed between 6.0 (BAD: https://clang.godbolt.org/z/je1ra7bMG) and 7.0 (GOOD: https://clang.godbolt.org/z/jjYTbWTzW)
