### ISSUE TITLE
clang-format disrespects AllowShortFunctionsOnASingleLine setting with lambda functions

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34115]
|  |  |
| --- | --- |
| Bugzilla Link | [34767](https://llvm.org/bz34767) |
| Version | 4.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
AllowShortFunctionsOnASingleLine setting is disrespected with regards to C++ lambda functions.

In the clang-format config I set the following:
AllowShortFunctionsOnASingleLine: 'false'

Expected output:
com->callbackOutgoingMessageSent = [] {
    com->goToRxMode();
};

Actual output:
com->callbackOutgoingMessageSent = [] { com->goToRxMode(); };

**Comment by rymiel** [comment]
I think `AllowShortLambdasOnASingleLine` (which was added after this bug was created) should suffice for closing this issue
