### ISSUE TITLE
Testsuite should support overriding settings

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34119]
|  |  |
| --- | --- |
| Bugzilla Link | [34771](https://llvm.org/bz34771) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The LLDB testsuite should have a flag that allows the user to provide a custom file, similar to .lldbinit, which has settings that are set for each test.

This would make it very easy to run the testsuite with experimental settings enabled.

**Comment by DavidSpickett** [comment]
I don't know if we had this back in the day, but we certainly do now, it was just incorrectly documented.

I fixed that and added https://lldb.llvm.org/resources/test.html#changing-test-suite-options.
