### ISSUE TITLE
BraceWrapping: SplitEmptyRecord ignored when AfterFunction is true

### ISSUE THREAD

**Issue by 8f86e7e5-cf11-44aa-9452-d007e98888f9** [llvm/llvm-project#34126]
|  |  |
| --- | --- |
| Bugzilla Link | [34778](https://llvm.org/bz34778) |
| Version | 5.0 |
| OS | Windows NT |

## Extended Description 
The following works as expected:

$ echo "template<typename T> struct X{};" | clang-format -style="{BasedOnStyle: llvm, BreakBeforeBraces: Custom, BraceWrapping: { AfterFunction: false, AfterStruct: true, SplitEmptyRecord: false}}"
template <typename T> struct X
{};

Change AfterFunction to true:

$ echo "template<typename T> struct X{};" | clang-format -style="{BasedOnStyle: llvm, BreakBeforeBraces: Custom, BraceWrapping: { AfterFunction: true, AfterStruct: true, SplitEmptyRecord: false}}"
template <typename T> struct X
{
};

I would not expect AfterFunction to interfere with the formatting of a struct (combined with SplitEmptyRecord).

Might be related to llvm/llvm-project#25506  and llvm/llvm-project#33355

**Comment by mydeveloperday** [comment]
This is what I see with clang-format 13, I am going to close this issue, please reopen if you still see a problem

```
$ echo "template struct X{};" | clang-format -style="{BasedOnStyle: llvm, BreakBeforeBraces: Custom, BraceWrapping: { AfterFunction: false, AfterStruct: true, SplitEmptyRecord: false}}"
template struct X
{};

$ echo "template struct X{};" | clang-format -style="{BasedOnStyle: llvm, BreakBeforeBraces: Custom, BraceWrapping: { AfterFunction: true, AfterStruct: true, SplitEmptyRecord: false}}"
template struct X
{};
```
