### ISSUE TITLE
Object/macho-invalid.test is failing on Debian stretch i386

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#34150]
|  |  |
| --- | --- |
| Bugzilla Link | [34802](https://llvm.org/bz34802) |
| Version | trunk |
| OS | Linux |

## Extended Description 
not /build/llvm-toolchain-snapshot-6.0~svn314656/build-llvm/./bin/llvm-objdump -macho -private-headers /build/llvm-toolchain-snapshot-6.0~svn314656/test/Object/Inputs/macho-invalid-note 2>&1 | /build/llvm-toolchain-snapshot-6.0~svn314656/build-llvm/./bin/FileCheck -check-prefix INVALID-NOTE-COMMAND /build/llvm-toolchain-snapshot-6.0~svn314656/test/Object/macho-invalid.test
--
Exit Code: 1

Command Output (stderr):
--
/build/llvm-toolchain-snapshot-6.0~svn314656/test/Object/macho-invalid.test:288:24: error: expected string not found in input
INVALID-DYLIB-CMDSIZE: macho-invalid-dylib-cmdsize-past-eof': truncated or malformed object (load command 0 extends past end of file)
                       ^
<stdin>:1:1: note: scanning from here
LLVMSymbolizer: error reading file: No such file or directory
^

**Comment by arsenm** [comment]
Old test failure
