### ISSUE TITLE
Allow to select the segment and offset of the stack canary

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34179]
|  |  |
| --- | --- |
| Bugzilla Link | [34831](https://llvm.org/bz34831) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @petrhosek,@frobtech |

## Extended Description 
Mirror the behaviour from gcc: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81708

The Linux and Zircon/Magenta kernel is moving to PIE code generation on x86. It means using -fPIE and removing -mcmodel=kernel. The problem is that -mcmodel=kernel is used to switch the TLS segment from fs to gs (for stack cookie or stack-guard on clang).

Gcc went for this format and using the same would be useful:
-mstack-protector-guard-reg=%fs -mstack-protector-guard-offset=0x200

**Comment by nickdesaulniers** [comment]
I think this has been implemented recently; maybe clang-15 or clang-16. Please reopen if we're missing something.
