### ISSUE TITLE
cppcoreguidelines-pro-type-member-init incorrect suggestion for union member

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34232]
|  |  |
| --- | --- |
| Bugzilla Link | [34884](https://llvm.org/bz34884) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @JonasToth,@EugeneZelenko |

## Extended Description 
Incorrect suggestion is given when a class contains union. Code snippet:

>cat union.cpp
#include <iostream>
class A
{
public:
   A() : i(){}
   union
   {
      int i;
      int j;
   };
};

int main()
{
   A a;
   std::cout<<sizeof(a)/sizeof(a.i)<<std::endl;
   return 0;
}

Error received:

>clang-tidy union.cpp -checks=hicpp-member-init
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "union.cpp"
No compilation database found in /login/xxx or any parent directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
3 warnings generated.
/login/xxx/union.cpp:5:4: warning: constructor does not initialize these fields: j [hicpp-member-init]
   A() : i(){}
   ^        ~
            , j()

After suggested fix the code does not compile:

>clang-tidy union.cpp -checks=hicpp-member-init -fix
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "union.cpp"
No compilation database found in /login/xxx or any parent directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
3 warnings generated.
/login/xxx/union.cpp:5:4: warning: constructor does not initialize these fields: j [hicpp-member-init]
   A() : i(){}
   ^        ~
            , j()
/login/xxx/union.cpp:5:13: note: FIX-IT applied suggested code changes
   A() : i(){}
            ^
clang-tidy applied 1 of 1 suggested fixes.
Suppressed 2 warnings (2 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.

>clang++ union.cpp
union.cpp:5:15: error: initializing multiple members of union
   A() : i(), j(){}
              ^~~
union.cpp:5:10: note: previous initialization is here
   A() : i(), j(){}
         ^~~
1 error generated.

**Comment by carlosgalvezp** [comment]
Example from OP is fixed on latest trunk
