### ISSUE TITLE
AliastSet Tracker object being modified during iteration.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34277]
|  |  |
| --- | --- |
| Bugzilla Link | [34929](https://llvm.org/bz34929) |
| Version | 3.8 |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
In the LICM.cpp, we see that the AST (AliasSet Tracker) object is being iterated over all the alias sets it contains and modified at the same time (in LLVM 3.8). We like to know if it is safe to do so. 

We have a similar usage of AST in a transformation we developed and that causes crashes. Additionally, we also see LICM crash sometimes but never able to reproduce deterministic. So we think this style of using AST tracker object might be a potential bug. We very well are aware of the fact that without reproduction steps it's impossible to debug. However, if we can be assured that it is safe to mutate AST object while iterating over the alias sets of the object, at least we can eliminate this possibility for the crash.

**Comment by Endilll** [comment]
I can't answer your question, but be mindful of our [Code of Conduct](https://llvm.org/docs/CodeOfConduct.html).

**Comment by nikic** [comment]
AST use has mostly been replaced with MSSA at this point. LICM still uses AST in one place, but without doing concurrent IR modification. Using AST and modifying IR is no longer supported.
