### ISSUE TITLE
Cyclic PHI nodes prevent NewGVN from converging.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34283]
|  |  |
| --- | --- |
| Bugzilla Link | [34935](https://llvm.org/bz34935) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
define void @&#8203;patatino() {
bb:
  br label %bb1

bb1:
  %tmp = phi i1 [ undef, %bb ], [ %tmp3, %bb1 ]
  %tmp3 = and i1 %tmp, true
  br label %bb1
}

This is the bug that we think we defeated, many times, and instead, keeps coming back.
NewGVN keeps moving instructions between classes and never reaches convergence. Eventually we hit an assertion because we processed an instruction too many times.

I'll take a stab at debugging it, but this is a FYI.

**Comment by ManuelJBrito** [comment]
It seems to have been fixed in the meantime. [https://godbolt.org/z/heYfzdKh3](https://godbolt.org/z/heYfzdKh3)
@alinas  @nunoplopes
