### ISSUE TITLE
Syntax error for "new struct" inside conditional-expression

### ISSUE THREAD

**Issue by HighCommander4** [llvm/llvm-project#34341]
|  |  |
| --- | --- |
| Bugzilla Link | [34993](https://llvm.org/bz34993) |
| Version | trunk |
| OS | All |

## Extended Description 
This code does not compile with clang:

struct A {};
struct A* b = (1 == 1) ? new struct A : new struct A;

The error message suggests that it's trying to parse "struct A :" as a class-specifier, with the ":" starting the base-clause.

I believe that this is valid, at least since DR 2141 [1], which introduced the "defining-type-specifier" grammar production. A "new-type-id" can only contain a "type-specifier", not a "defining-type-specifier", and a "class-specifier" is only valid as a "defining-type-specifier", so I don't believe clang should be trying to parse a "class-specifier" at all. (Instead, the "struct A" should be parsed as an "elaborate-type-specifier", which is a valid "type-specifier".)

(I'm not convinced that the code was invalid even before DR 2141 - I would have thought that, having tried and failed to parse a "class-specifier", the compiler would backtrack and try to parse an "elaborate-type-specifier" instead - but I'm less confident about that.)

[1] http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#2141

**Comment by AaronBallman** [comment]
Clang and GCC reject, MSVC and ICC accept. According to our DR status page, CWG2141 is unknown, but it's pretty safe to say it's "no" now. This issue still reproduces as of Clang 16.0.0: https://godbolt.org/z/cbjxnnafb

**Comment by Fznamznon** [comment]
https://reviews.llvm.org/D153857
