### ISSUE TITLE
Clang-format comment alignment issue

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34355]
|  |  |
| --- | --- |
| Bugzilla Link | [35007](https://llvm.org/bz35007) |
| Version | 5.0 |
| OS | Windows NT |
| Attachments | [source file](https://user-images.githubusercontent.com/60944935/143756472-e16078bb-dc99-4f03-bb62-de189682d9f1.gz), [format file](https://user-images.githubusercontent.com/60944935/143756473-8ddba699-cf62-4f95-ab81-56a5911301f1.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Running clang-format with -style=file -i over attached C source file, with attached .clang-format results in what I believe to be a wrong alignment for line 7

**Comment by mydeveloperday** [comment]
```
#ifdef __cplusplus
extern "C" {
#endif
void foo()
{
}
/*====================================================================================================================*/

#ifdef __cplusplus
}
#endif
```

**Comment by mydeveloperday** [comment]
Produces 

```
#ifdef __cplusplus
extern "C" {
#endif
void foo()
{
}
/*====================================================================================================================*/

#ifdef __cplusplus
}
#endif
```

I don't understand what is the incorrect aligment but it looks good to me, closing this issue but feel free to reopen it if you think its still wrong
