### ISSUE TITLE
wrong code at -O3 with -fexperimental-new-pass-manager

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#34373]
|  |  |
| --- | --- |
| Bugzilla Link | [35025](https://llvm.org/bz35025) |
| Version | unspecified |
| OS | All |
| CC | @chandlerc,@hfinkel |

## Extended Description 
Tested with trunk rev. 316262. 

$ clangpolly -v
clang version 6.0.0 (http://llvm.org/git/clang.git a6d3ef724655a64ac137945615d3ff002c4f7993) (http://llvm.org/git/llvm.git 3aad6fd98b60114347bcfdeaeded7987ec5b629e)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clangpolly -fexperimental-new-pass-manager -O2 -w small.c; ./a.out
2
2
$ 
$ clangpolly -fexperimental-new-pass-manager -O3 -w small.c; ./a.out
2
0
$ 

-------------------------------------------------------------

int printf (const char *, ...);

int a, b, c, d, e, *f, **g = &f, ***k = &g, h, j, l, o, p;
short i[2], m, n;

int r (int s)
{
  return a < 0 || s ? s : s << a;
}

static void t (int *s)
{
  for (e = 0; e < 5; e++)
    {
      int *u = &b;
      for (j = 0; j < 2; j++)
	i[j] = 0;
      for (l = 0; l < 2; l++)
	{
	  int *v = &c;
	  **k = s;
	  for (d = 0; d < 5; d++)
	    for (m = 0; m < 2; m++)
	      {
		short *w = &n;
		(i[m] |= j) <= (*w |= *u = r ((short) (*v |= 6) >> h));
		o = *s;
		if (o)
		  break;
	      }
	}
    }
}

void x ()
{
  int *q = &b;
  t (q);
}
 
int main ()
{
  x ();
  for (; p < 2; p++)
    printf ("%d\n", i[0]);
  return 0;
}

**Comment by fhahn** [comment]
I cannot reproduce this on current `main`, so this is likely fixed. I am closing the issue, but please re-open with more details if it still reproduces on your end!
