### ISSUE TITLE
[coroutines] segmentation fault running pass Module Verifier

### ISSUE THREAD

**Issue by fed5e9a7-7d28-4f31-a028-3851a135503d** [llvm/llvm-project#34396]
|  |  |
| --- | --- |
| Bugzilla Link | [35048](https://llvm.org/bz35048) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@modocache |

## Extended Description 
See godbolt code: https://godbolt.org/g/6JYFvu

Instruction does not dominate all uses!
  <badref> = getelementptr inbounds, !dbg <0x7be4770>
  %9 = atomicrmw sub %"struct.task::promise_type"* (%"struct.task::promise_type"*)* #&#8203;0 0x0000000001e94b6a (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x1e94b6a)
#&#8203;1 0x0000000001e92c5e (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x1e92c5e)
#&#8203;2 0x0000000001e92dac (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x1e92dac)
#&#8203;3 0x00007fa477e49390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
#&#8203;4 0x0000000001922ba2 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x1922ba2)
#&#8203;5 0x0000000001922fb7 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x1922fb7)
#&#8203;6 0x000000000192370e (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x192370e)
#&#8203;7 0x000000000192966e (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x192966e)
#&#8203;8 0x000000000192bd04 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x192bd04)
#&#8203;9 0x0000000001a0bec9 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x1a0bec9)
#&#8203;10 0x0000000001a19447 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x1a19447)
#&#8203;11 0x0000000001a229da (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x1a229da)
#&#8203;12 0x0000000001a22c1c (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x1a22c1c)
#&#8203;13 0x0000000001a2332d (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x1a2332d)
#&#8203;14 0x00000000019cefba (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x19cefba)
#&#8203;15 0x00000000019cf0fe (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x19cf0fe)
#&#8203;16 0x00000000019cf45c (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x19cf45c)
#&#8203;17 0x0000000002824f01 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x2824f01)
#&#8203;18 0x0000000002826675 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x2826675)
#&#8203;19 0x00000000014e46a3 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x14e46a3)
#&#8203;20 0x00000000019ceb74 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x19ceb74)
#&#8203;21 0x000000000204c164 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x204c164)
#&#8203;22 0x0000000002816b24 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x2816b24)
#&#8203;23 0x00000000029affc8 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x29affc8)
#&#8203;24 0x0000000002816107 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x2816107)
#&#8203;25 0x00000000023dc4ae (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x23dc4ae)
#&#8203;26 0x00000000023a98e6 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x23a98e6)
#&#8203;27 0x000000000246e482 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x246e482)
#&#8203;28 0x00000000009e8818 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x9e8818)
#&#8203;29 0x000000000095523a (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x95523a)
#&#8203;30 0x00007fa476dce830 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20830)
#&#8203;31 0x00000000009e6269 (/opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0+0x9e6269)
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk-20171023/bin/clang-6.0 -cc1 -triple x86_64-unknown-linux-gnu -S -disable-free -disable-llvm-verifier -discard-value-names -main-file-name example.cpp -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -coverage-notes-file /tmp/compiler-explorer-compiler117924-58-4capm4.omaapjh5mi/output.gcno -resource-dir /opt/compiler-explorer/clang-trunk-20171023/lib/clang/6.0.0 -c-isystem /usr/include/x86_64-linux-gnu -cxx-isystem /usr/include/x86_64-linux-gnu -internal-isystem /opt/compiler-explorer/clang-trunk-20171023/bin/../include/c++/v1 -internal-isystem /usr/local/include -internal-isystem /opt/compiler-explorer/clang-trunk-20171023/lib/clang/6.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -std=c++1z -fdeprecated-macro -fdebug-compilation-dir /compiler-explorer -ferror-limit 19 -fmessage-length 0 -fcoroutines-ts -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -vectorize-loops -vectorize-slp -mllvm --x86-asm-syntax=intel -o /tmp/compiler-explorer-compiler117924-58-4capm4.omaapjh5mi/output.s -x c++ <source> 
1.	<eof> parser at end of file
2.	Per-module optimization passes
3.	Running pass 'CallGraph Pass Manager' on module '<source>'.
4.	Running pass 'Module Verifier' on function '@_Z1fv.resume'
clang-6.0: error: unable to execute command: Segmentation fault (core dumped)
clang-6.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0 (trunk 316311)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/compiler-explorer/clang-trunk/bin
clang-6.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-6.0: note: diagnostic msg: 
********************
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-6.0: note: diagnostic msg: /tmp/example-788647.cpp
clang-6.0: note: diagnostic msg: /tmp/example-788647.sh
clang-6.0: note: diagnostic msg: 
********************
Compiler exited with result code 254

**Comment by fhahn** [comment]
this now fails with a clang error:

```
<source>:83:6: error: the expression 'co_await __promise.final_suspend()' is required to be non-throwing
task g()
     ^
```

As this doesn't reproduce any longer, I'll close the issue for now. Please comment/re-open with additional info if it still reproduces.
