### ISSUE TITLE
clang disagrees with {gcc,icc,msvc} about ambiguous name

### ISSUE THREAD

**Issue by silvasean** [llvm/llvm-project#34390]
|  |  |
| --- | --- |
| Bugzilla Link | [35042](https://llvm.org/bz35042) |
| Version | unspecified |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
GCC and clang seem to disagree about whether the reference to `isa` in this snippet is valid:

namespace myarch {
  namespace isa {
  }
}

using namespace myarch;

namespace llvm {
  template <typename T>
  void isa() {}
}

using namespace llvm;

void f() {
  isa<int>();
}

Clang accepts this code. GCC says `error: reference to 'isa' is ambiguous`.

https://godbolt.org/g/ix2jsS

Also, ICC and MSVC seem to believe that it is ambiguous as well.

**Comment by wheatman** [comment]
This was fixed between 8.0.1 and 9.0.0
https://gcc.godbolt.org/z/oa369W1YK

code
```
namespace myarch {
  namespace isa {
  }
}

using namespace myarch;

namespace llvm {
  template <typename T>
  void isa() {}
}

using namespace llvm;

void f() {
  isa<int>();
}
```

new error
```
<source>:16:3: error: reference to 'isa' is ambiguous
  isa<int>();
  ^
<source>:2:13: note: candidate found by name lookup is 'myarch::isa'
  namespace isa {
            ^
<source>:10:8: note: candidate found by name lookup is 'llvm::isa'
  void isa() {}
       ^
1 error generated.
Compiler returned: 1
```
