### ISSUE TITLE
[META] Many test failures on Fedora 27

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34410]
|  |  |
| --- | --- |
| Bugzilla Link | [35062](https://llvm.org/bz35062) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @jankratochvil,@tstellar |

## Extended Description 
=============
Issue Details
=============
FAIL: test_expr_commands_dwarf (expression_command/radar_9673664/TestExprHelpExamples.py)
FAIL: test_expr_commands_dwo (expression_command/radar_9673664/TestExprHelpExamples.py)
FAIL: test_expr_commands_gmodules (expression_command/radar_9673664/TestExprHelpExamples.py)
FAIL: test_more_expr_commands_dwarf (expression_command/test/TestExprs2.py)
FAIL: test_more_expr_commands_dwo (expression_command/test/TestExprs2.py)
FAIL: test_more_expr_commands_gmodules (expression_command/test/TestExprs2.py)
FAIL: test_top_level_expressions_dwarf (expression_command/top-level/TestTopLevelExprs.py)
FAIL: test_top_level_expressions_dwo (expression_command/top-level/TestTopLevelExprs.py)
FAIL: test_with_dwarf (lang/cpp/lambdas/TestLambdas.py)
FAIL: test_with_dwo (lang/cpp/lambdas/TestLambdas.py)
FAIL: test_with_gmodules (lang/cpp/lambdas/TestLambdas.py)
UNEXPECTED SUCCESS: test (functionalities/thread/concurrent_events/n_watch_n_break/TestConcurrentNWatchNBreak.py)
UNEXPECTED SUCCESS: test_dwarf (functionalities/thread/exit_during_break/TestExitDuringBreak.py)
UNEXPECTED SUCCESS: test_dwo (functionalities/thread/exit_during_break/TestExitDuringBreak.py)
UNEXPECTED SUCCESS: test_gmodules (functionalities/thread/exit_during_break/TestExitDuringBreak.py)
UNEXPECTED SUCCESS: test_lldbmi_gdb_set_target_async_off (tools/lldb-mi/TestMiGdbSetShow.py)
UNEXPECTED SUCCESS: test_lldbmi_process_output (tools/lldb-mi/syntax/TestMiSyntax.py)
UNEXPECTED SUCCESS: test_lldbmi_settings_set_target_run_args_after (tools/lldb-mi/interpreter/TestMiInterpreterExec.py)
UNEXPECTED SUCCESS: test_restart_bug (functionalities/signal/raise/TestRaise.py)
UNEXPECTED SUCCESS: test_with_dwarf (lang/cpp/printf/TestPrintf.py)
UNEXPECTED SUCCESS: test_with_dwo (lang/cpp/printf/TestPrintf.py)
UNEXPECTED SUCCESS: test_with_gmodules (lang/cpp/printf/TestPrintf.py)
TIMEOUT: test_sb_api_listener_event_description_dwo (api/multithreaded/TestMultithreaded.py)

===================
Test Result Summary
===================
Test Methods:       2662
Reruns:                0
Success:            1695
Expected Failure:    147
Failure:              11
Error:                 0
Exceptional Exit:      0
Unexpected Success:   11
Skip:                797
Timeout:               1
Expected Timeout:      0
FAILED: cd /home/davide/work/build-lldb/tools/lldb/test && /usr/bin/python2.7 /home/davide/work/llvm-lldb/tools/lldb/test/dotest.py -q --arch=x86_64 --executable /home/davide/work/build-lldb/bin/lldb -s /home/davide/work/build-lldb/lldb-test-traces -S nm -u CXXFLAGS -u CFLAGS -C /home/davide/work/build-lldb/bin/clang-5.0 --env ARCHIVER=/usr/bin/ar --env OBJCOPY=/usr/bin/objcopy
ninja: build stopped: subcommand failed.

I'll keep this open and then maybe create other bugzilla PRs for specific issues.

**Comment by asl** [comment]
Please reopen if this still an issue
