### ISSUE TITLE
AArch64 backend does not handle contract math.

### ISSUE THREAD

**Issue by yuyichao** [llvm/llvm-project#34439]
|  |  |
| --- | --- |
| Bugzilla Link | [35091](https://llvm.org/bz35091) |
| Version | 5.0 |
| OS | Linux |
| CC | @rotateright |

## Extended Description 
Test case:

```
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

define double @&#8203;f1(double, double, double) {
  %4 = call double @&#8203;llvm.fmuladd.f64(double %0, double %1, double %2)
  ret double %4
}

define double @&#8203;f2(double, double, double) {
  %4 = fmul contract double %0, %1
  %5 = fadd contract double %4, %2
  ret double %5
}

declare double @&#8203;llvm.fmuladd.f64(double %a, double %b, double %c)
```

According to LangRef, the two function should be the same and should both use fma or mul and add depending on what the backend think is faster. However, running with `llc -O3` only the first one generates an fma instruction and the second one uses a mul and an add.

ARM backend might have the same issue.

**Comment by vfdff** [comment]
Now both emit fmadd , which is fine, https://gcc.godbolt.org/z/rahGsGjs6
