### ISSUE TITLE
ClangFormat extension does not work in Visual Studio 2013

### ISSUE THREAD

**Issue by a4d7907a-3415-4f9c-a2cc-9ddede69acfc** [llvm/llvm-project#34448]
|  |  |
| --- | --- |
| Bugzilla Link | [35100](https://llvm.org/bz35100) |
| Version | trunk |
| OS | Windows NT |

## Extended Description 
Sometimes, ClangFormat extension does not work in Visual Studio 2013. I install it, but menu items do not appear under Tools menu and there is no LLVM/Clang node in Options dialog.

Sometimes reinstalling the extensions and restarting Visual Studio several times helps, sometimes it does not. I tried to manually remove extension folder from  "%LocalAppData%\Microsoft\VisualStudio\12.0\Extensions\", but this did not help either.

On some installations it did work and worked smoothly. On some we see such bug.

**Comment by mydeveloperday** [comment]
Out of scope, I don't think we are going to go back to 2013.
