### ISSUE TITLE
clang-format support { on its own line, but only on multi-line conditionals

### ISSUE THREAD

**Issue by 461fbe0d-6a87-49d5-9fcc-6394452b7c47** [llvm/llvm-project#34446]
|  |  |
| --- | --- |
| Bugzilla Link | [35098](https://llvm.org/bz35098) |
| Version | unspecified |
| OS | All |

## Extended Description 
I'd like to propose an additional brace option for conditionals -- attached braces if the conditional expression fits on a single line, otherwise a break before the brace.   That is:

    if (something < 10) {          // one-line condition, attached brace
        DoConditionalThing();
    }

    if (something < 10 && SomeOtherCondition() &&
        SomeOtherCheckCall())
    {                              // multi-line condition, brace on its own line
        DoConditionalThing();
    }

Right now, the only options are either putting the { on its own line always (making the simple statement above 4 lines instead of 3), or attaching it to the end always, making the complex statement above have a hidden, hanging {, like so:

    if (something < 10 && SomeOtherCondition() &&
        SomeOtherCheckCall()) {
        DoConditionalThing();
    }

I'm willing to take a stab at this myself if there's interest in having this as an option in BraceWrapping (probably as a "MultilineOnly" option to BraceWrapping - AfterControlStatement, in addition to true/false)

**Comment by owenca** [comment]
We can do both now with `AfterControlStatement: MultiLine` and `AllowShortIfStatementsOnASingleLine: WithoutElse`.
