### ISSUE TITLE
incorrect __sanitizer_cov_trace_pc prototype produces fatal error: error in backend:Sanitizer interface function redefined

### ISSUE THREAD

**Issue by emaste** [llvm/llvm-project#34457]
|  |  |
| --- | --- |
| Bugzilla Link | [35109](https://llvm.org/bz35109) |
| Version | trunk |
| OS | All |
| Attachments | [__sanitizer_cov_trace_pc function with wrong prototype](https://user-images.githubusercontent.com/1034582/143756508-c6b1c534-669f-4ef1-be31-fac39cfe65cb.gz) |
| CC | @DimitryAndric,@vitalybuka |

## Extended Description 
An error is expected for this case, but it should not be one suggesting submission of an LLVM bug report.

% clang -fsanitize-coverage=trace-pc hellosan.c 
void ()* bitcast (void (i8*)* @&#8203;__sanitizer_cov_trace_pc to void ()*)
fatal error: error in backend: Sanitizer interface function redefined: void ()*
      bitcast (void (i8*)* @&#8203;__sanitizer_cov_trace_pc to void ()*)
clang-6.0: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 6.0.0 (https://github.com/llvm-mirror/clang.git d2d3a85d2777c75fdda6b69b7b62c0361015288a) (https://github.com/llvm-mirror/llvm.git f1bc4aa5fa5b44ded9991dfa0df5d1a9d13ff5b7)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /home/emaste/src/sanitize/../llvm/build/bin
clang-6.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-6.0: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-6.0: note: diagnostic msg: /tmp/hellosan-20aa32.c
clang-6.0: note: diagnostic msg: /tmp/hellosan-20aa32.sh
clang-6.0: note: diagnostic msg: 

********************

**Comment by Endilll** [comment]
Appears to be fixed in Clang 9: https://godbolt.org/z/3bfWx436h
