### ISSUE TITLE
Poor error message from control flow at global scope

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#34462]
|  |  |
| --- | --- |
| Bugzilla Link | [35114](https://llvm.org/bz35114) |
| Version | trunk |
| OS | Windows NT |
| CC | @hfinkel |

## Extended Description 
If you compile the following code:
```
while(true) {}
```
You get the not especially helpful error message:
```
<source>:1:1: error: expected unqualified-id
while(true) {}
^
1 error generated.
```

This came up for me in the context of calling a macro that wrapped a few statements in a `do { ... } while(false);` construct, and I spend a fair amount of time looking for a missing semicolon somewhere before I finally found the problem. I would have preferred to get a message along the lines of "while loops not allowed outside of functions" or something else that directly says the problem from the user's perspective.

**Comment by inclyc** [comment]
work on this

**Comment by inclyc** [comment]
https://reviews.llvm.org/D129573
