### ISSUE TITLE
clang crashes on x86_64-linux-gnu with Assertion `Us < (1u << NumUserOperandsBits) && "Too many operands"' failed.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34466]
|  |  |
| --- | --- |
| Bugzilla Link | [35118](https://llvm.org/bz35118) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @kamleshbhalui,@zygoloid |

## Extended Description 
$ clang-trunk -v
clang version 6.0.0 (trunk 316829)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin

$ clang-trunk -c abc.c
clang-6.0: /home/absozero/trunk/llvm/lib/IR/User.cpp:116: static void* llvm::User::allocateFixedOperandUser(size_t, unsigned int, unsigned int): Assertion `Us < (1u << NumUserOperandsBits) && "Too many operands"' failed.
#&#8203;0 0x00000000020c308a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x20c308a)
#&#8203;1 0x00000000020c0f2e llvm::sys::RunSignalHandlers() (/home/absozero/trunk/root-clang/bin/clang-6.0+0x20c0f2e)
#&#8203;2 0x00000000020c1082 SignalHandler(int) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x20c1082)
#&#8203;3 0x00007fd5c5b7c330 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10330)
#&#8203;4 0x00007fd5c46f9c37 gsignal /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;5 0x00007fd5c46fd028 abort /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;6 0x00007fd5c46f2bf6 __assert_fail_base /build/eglibc-oGUzwX/eglibc-2.19/assert/assert.c:92:0
#&#8203;7 0x00007fd5c46f2ca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
#&#8203;8 0x0000000001c2f806 (/home/absozero/trunk/root-clang/bin/clang-6.0+0x1c2f806)
#&#8203;9 0x0000000001b6048a llvm::ConstantUniqueMap<llvm::ConstantArray>::getOrCreate(llvm::ArrayType*, llvm::ConstantAggrKeyType<llvm::ConstantArray>) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x1b6048a)
#&#8203;10 0x0000000001b6068b llvm::ConstantArray::get(llvm::ArrayType*, llvm::ArrayRef<llvm::Constant*>) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x1b6068b)
#&#8203;11 0x0000000002299cbb clang::StmtVisitorBase<clang::make_ptr, (anonymous namespace)::ConstExprEmitter, llvm::Constant*, clang::QualType>::Visit(clang::Stmt*, clang::QualType) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x2299cbb)
#&#8203;12 0x0000000002297b93 clang::CodeGen::ConstantEmitter::tryEmitPrivate(clang::Expr const*, clang::QualType) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x2297b93)
#&#8203;13 0x0000000002297d76 clang::CodeGen::ConstantEmitter::tryEmitPrivateForMemory(clang::Expr const*, clang::QualType) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x2297d76)
#&#8203;14 0x00000000022998e1 clang::StmtVisitorBase<clang::make_ptr, (anonymous namespace)::ConstExprEmitter, llvm::Constant*, clang::QualType>::Visit(clang::Stmt*, clang::QualType) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x22998e1)
#&#8203;15 0x0000000002299f09 clang::CodeGen::ConstantEmitter::tryEmitPrivateForVarInit(clang::VarDecl const&) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x2299f09)
#&#8203;16 0x000000000229a012 clang::CodeGen::ConstantEmitter::tryEmitAbstractForInitializer(clang::VarDecl const&) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x229a012)
#&#8203;17 0x00000000023fec78 clang::CodeGen::CodeGenFunction::EmitAutoVarInit(clang::CodeGen::CodeGenFunction::AutoVarEmission const&) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x23fec78)
#&#8203;18 0x0000000002402932 clang::CodeGen::CodeGenFunction::EmitAutoVarDecl(clang::VarDecl const&) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x2402932)
#&#8203;19 0x0000000002402a16 clang::CodeGen::CodeGenFunction::EmitVarDecl(clang::VarDecl const&) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x2402a16)
#&#8203;20 0x0000000002402d94 clang::CodeGen::CodeGenFunction::EmitDecl(clang::Decl const&) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x2402d94)
#&#8203;21 0x00000000022a716f clang::CodeGen::CodeGenFunction::EmitDeclStmt(clang::DeclStmt const&) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x22a716f)
#&#8203;22 0x00000000022b4362 clang::CodeGen::CodeGenFunction::EmitSimpleStmt(clang::Stmt const*) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x22b4362)
#&#8203;23 0x00000000022b0130 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x22b0130)
#&#8203;24 0x00000000022b12db clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x22b12db)
#&#8203;25 0x00000000022b15b4 clang::CodeGen::CodeGenFunction::EmitCompoundStmt(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x22b15b4)
#&#8203;26 0x00000000022b43c3 clang::CodeGen::CodeGenFunction::EmitSimpleStmt(clang::Stmt const*) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x22b43c3)
#&#8203;27 0x00000000022b0130 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x22b0130)
#&#8203;28 0x00000000022b12db clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x22b12db)
#&#8203;29 0x00000000022b15b4 clang::CodeGen::CodeGenFunction::EmitCompoundStmt(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x22b15b4)
#&#8203;30 0x00000000022b43c3 clang::CodeGen::CodeGenFunction::EmitSimpleStmt(clang::Stmt const*) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x22b43c3)
#&#8203;31 0x00000000022b0130 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x22b0130)
#&#8203;32 0x00000000022b12db clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x22b12db)
#&#8203;33 0x00000000022e53f0 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::CodeGen::FunctionArgList&, clang::Stmt const*) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x22e53f0)
#&#8203;34 0x00000000022f222e clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x22f222e)
#&#8203;35 0x0000000002311358 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x2311358)
#&#8203;36 0x0000000002321ec7 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x2321ec7)
#&#8203;37 0x0000000002322d1a clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x2322d1a)
#&#8203;38 0x000000000232350a clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) [clone .part.6149] [clone .constprop.6154] (/home/absozero/trunk/root-clang/bin/clang-6.0+0x232350a)
#&#8203;39 0x0000000002a96afb (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x2a96afb)
#&#8203;40 0x0000000002a8d87b clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x2a8d87b)
#&#8203;41 0x0000000002c75356 clang::ParseAST(clang::Sema&, bool, bool) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x2c75356)
#&#8203;42 0x0000000002a943ec clang::CodeGenAction::ExecuteAction() (/home/absozero/trunk/root-clang/bin/clang-6.0+0x2a943ec)
#&#8203;43 0x000000000262981e clang::FrontendAction::Execute() (/home/absozero/trunk/root-clang/bin/clang-6.0+0x262981e)
#&#8203;44 0x00000000025f8c86 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x25f8c86)
#&#8203;45 0x00000000026bc363 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/absozero/trunk/root-clang/bin/clang-6.0+0x26bc363)
#&#8203;46 0x0000000000a528a8 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/absozero/trunk/root-clang/bin/clang-6.0+0xa528a8)
#&#8203;47 0x00000000009cf245 main (/home/absozero/trunk/root-clang/bin/clang-6.0+0x9cf245)
#&#8203;48 0x00007fd5c46e4f45 __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;49 0x0000000000a4edb9 _start (/home/absozero/trunk/root-clang/bin/clang-6.0+0xa4edb9)
Stack dump:
0.	Program arguments: /home/absozero/trunk/root-clang/bin/clang-6.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name abc.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /home/absozero/projects/reduction/crash/abc.gcno -resource-dir /home/absozero/trunk/root-clang/lib/clang/6.0.0 -internal-isystem /usr/local/include -internal-isystem /home/absozero/trunk/root-clang/lib/clang/6.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir /home/absozero/projects/reduction/crash -ferror-limit 19 -fmessage-length 172 -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -o abc.o -x c abc.c
1.	<eof> parser at end of file
2.	abc.c:1:6: LLVM IR generation of declaration 'fn1'
3.	abc.c:1:6: Generating code for declaration 'fn1'
4.	abc.c:2:3: LLVM IR generation of compound statement ('{}')
5.	abc.c:3:5: LLVM IR generation of compound statement ('{}')
clang-6.0: error: unable to execute command: Aborted (core dumped)
clang-6.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0 (trunk 316829)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
clang-6.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-6.0: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-6.0: note: diagnostic msg: /tmp/abc-db7b2c.c
clang-6.0: note: diagnostic msg: /tmp/abc-db7b2c.sh
clang-6.0: note: diagnostic msg:

********************

$ cat abc.c
void fn1() {
  {
    { int a[][757177340][1] = {{{6}}}; }
  }
}

**Comment by Endilll** [comment]
Appears to be fixed in Clang 7: https://cexplorer.testlabs.pro/z/b65Thr
