### ISSUE TITLE
LoopVectorize segfaults

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34470]
|  |  |
| --- | --- |
| Bugzilla Link | [35122](https://llvm.org/bz35122) |
| Version | 5.0 |
| OS | MacOS X |
| Attachments | [zipped preprocessed source](https://user-images.githubusercontent.com/60944935/143756510-b70825f4-4625-4ad5-9e1b-05b56f3fbb45.gz), [associated run script](https://user-images.githubusercontent.com/60944935/143756511-0b92f4e6-cb9a-4808-aa31-5703d7a3282e.gz), [crash backtrace](https://user-images.githubusercontent.com/60944935/143756512-68c38631-1c77-4a61-9e00-e53b711ed1b2.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @ayalz,@hfinkel,@zygoloid |

## Extended Description 
Compiling libeddsa/dh.c with -O2 causes a segfault.

**Comment by fhahn** [comment]
I am unable to reproduce this with current `main`. The issue has likely been fixed. Please re-open the issue with additional details if it still reproduces on your end.
