### ISSUE TITLE
clang crashes on valid code at -O1, -O2 and -O3 with -fexperimental-new-pass-manager: Assertion `(FoundIB || !DFS.hasPostorder(*I)) && "should have seen IB"' failed

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#34472]
|  |  |
| --- | --- |
| Bugzilla Link | [35124](https://llvm.org/bz35124) |
| Version | unspecified |
| OS | All |
| CC | @chandlerc,@hfinkel |

## Extended Description 
Tested with trunk rev. 316871. 

$ clangpolly -v
clang version 6.0.0 (http://llvm.org/git/clang.git 68e041468bfb4a364acdfa32abb0c7e38cfb938e) (http://llvm.org/git/llvm.git 986395e8cd168305bcf7a9463fb0fc9696218f0b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clangpolly -fexperimental-new-pass-manager -O0 small.c
$ clangpolly -O1 small.c
$ 
$ clangpolly -fexperimental-new-pass-manager -O1 small.c
clang-6.0: /home/su/software/tmp/polly/llvm/lib/Analysis/LoopInfo.cpp:610: llvm::Loop* {anonymous}::UnloopUpdater::getNearestLoop(llvm::BasicBlock*, llvm::Loop*): Assertion `(FoundIB || !DFS.hasPostorder(*I)) && "should have seen IB"' failed.
#&#8203;0 0x0000000002099e4a llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/su/software/tmp/polly/llvm/lib/Support/Unix/Signals.inc:402:0
#&#8203;1 0x0000000002097cee llvm::sys::RunSignalHandlers() /home/su/software/tmp/polly/llvm/lib/Support/Signals.cpp:50:0
#&#8203;2 0x0000000002097e62 SignalHandler(int) /home/su/software/tmp/polly/llvm/lib/Support/Unix/Signals.inc:242:0
#&#8203;3 0x00007ffb15f1c390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
#&#8203;4 0x00007ffb14c8e428 gsignal /build/glibc-bfm8X4/glibc-2.23/signal/../sysdeps/unix/sysv/linux/raise.c:54:0
#&#8203;5 0x00007ffb14c9002a abort /build/glibc-bfm8X4/glibc-2.23/stdlib/abort.c:91:0
#&#8203;6 0x00007ffb14c86bd7 __assert_fail_base /build/glibc-bfm8X4/glibc-2.23/assert/assert.c:92:0
#&#8203;7 0x00007ffb14c86c82 (/lib/x86_64-linux-gnu/libc.so.6+0x2dc82)
#&#8203;8 0x00000000017257c7 bool llvm::DenseMapBase<llvm::DenseMap<llvm::BasicBlock*, unsigned int, llvm::DenseMapInfo<llvm::BasicBlock*>, llvm::detail::DenseMapPair<llvm::BasicBlock*, unsigned int> >, llvm::BasicBlock*, unsigned int, llvm::DenseMapInfo<llvm::BasicBlock*>, llvm::detail::DenseMapPair<llvm::BasicBlock*, unsigned int> >::LookupBucketFor<llvm::BasicBlock const*>(llvm::BasicBlock const* const&, llvm::detail::DenseMapPair<llvm::BasicBlock*, unsigned int> const*&) const /home/su/software/tmp/polly/llvm/include/llvm/ADT/DenseMap.h:603:0
#&#8203;9 0x00000000017257c7 llvm::DenseMapBase<llvm::DenseMap<llvm::BasicBlock*, unsigned int, llvm::DenseMapInfo<llvm::BasicBlock*>, llvm::detail::DenseMapPair<llvm::BasicBlock*, unsigned int> >, llvm::BasicBlock*, unsigned int, llvm::DenseMapInfo<llvm::BasicBlock*>, llvm::detail::DenseMapPair<llvm::BasicBlock*, unsigned int> >::find(llvm::BasicBlock const*) const /home/su/software/tmp/polly/llvm/include/llvm/ADT/DenseMap.h:154:0
#&#8203;10 0x00000000017257c7 llvm::LoopBlocksDFS::hasPostorder(llvm::BasicBlock*) const /home/su/software/tmp/polly/llvm/include/llvm/Analysis/LoopIterator.h:148:0
#&#8203;11 0x00000000017257c7 (anonymous namespace)::UnloopUpdater::getNearestLoop(llvm::BasicBlock*, llvm::Loop*) /home/su/software/tmp/polly/llvm/lib/Analysis/LoopInfo.cpp:610:0
#&#8203;12 0x0000000001727321 updateBlockParents /home/su/software/tmp/polly/llvm/lib/Analysis/LoopInfo.cpp:501:0
#&#8203;13 0x0000000001727321 llvm::LoopInfo::erase(llvm::Loop*) /home/su/software/tmp/polly/llvm/lib/Analysis/LoopInfo.cpp:694:0
#&#8203;14 0x0000000002111d2b llvm::UnrollLoop(llvm::Loop*, unsigned int, unsigned int, bool, bool, bool, bool, bool, unsigned int, unsigned int, bool, llvm::LoopInfo*, llvm::ScalarEvolution*, llvm::DominatorTree*, llvm::AssumptionCache*, llvm::OptimizationRemarkEmitter*, bool) /home/su/software/tmp/polly/llvm/lib/Transforms/Utils/LoopUnroll.cpp:821:0
#&#8203;15 0x0000000001f5cd42 tryToUnrollLoop(llvm::Loop*, llvm::DominatorTree&, llvm::LoopInfo*, llvm::ScalarEvolution&, llvm::TargetTransformInfo const&, llvm::AssumptionCache&, llvm::OptimizationRemarkEmitter&, bool, int, llvm::Optional<unsigned int>, llvm::Optional<unsigned int>, llvm::Optional<bool>, llvm::Optional<bool>, llvm::Optional<bool>, llvm::Optional<bool>) [clone .constprop.316] /home/su/software/tmp/polly/llvm/lib/Transforms/Scalar/LoopUnrollPass.cpp:1057:0
#&#8203;16 0x0000000001f5e17a llvm::Optional<unsigned int>::reset() /home/su/software/tmp/polly/llvm/include/llvm/ADT/Optional.h:121:0
#&#8203;17 0x0000000001f5e17a llvm::Optional<unsigned int>::~Optional() /home/su/software/tmp/polly/llvm/include/llvm/ADT/Optional.h:62:0
#&#8203;18 0x0000000001f5e17a llvm::LoopFullUnrollPass::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop<llvm::LoopStandardAnalysisResults&> >&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&) /home/su/software/tmp/polly/llvm/lib/Transforms/Scalar/LoopUnrollPass.cpp:1192:0
#&#8203;19 0x00000000039c7e41 llvm::detail::PassModel<llvm::Loop, llvm::LoopFullUnrollPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&) /home/su/software/tmp/polly/llvm/include/llvm/IR/PassManagerInternal.h:81:0
#&#8203;20 0x0000000003ab5ddc llvm::PassManager<llvm::Loop, llvm::AnalysisManager<llvm::Loop<llvm::LoopStandardAnalysisResults&> >, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>::run(llvm::Loop&, llvm::Loop<llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater) /home/su/software/tmp/polly/llvm/lib/Transforms/Scalar/LoopPassManager.cpp:40:0
#&#8203;21 0x00000000039f20ec llvm::FunctionToLoopPassAdaptor<llvm::PassManager<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) /home/su/software/tmp/polly/llvm/include/llvm/Transforms/Scalar/LoopPassManager.h:328:0
#&#8203;22 0x00000000039f23c1 llvm::detail::PassModel<llvm::Function, llvm::FunctionToLoopPassAdaptor<llvm::PassManager<llvm::Loop, llvm::AnalysisManager<llvm::Loop<llvm::LoopStandardAnalysisResults&> >, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&> >, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function<> >>::run(llvm::Function&, llvm::PreservedAnalyses&) /home/su/software/tmp/polly/llvm/include/llvm/IR/PassManagerInternal.h:81:0
#&#8203;23 0x0000000001c15617 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function<> >>::run(llvm::Function&, llvm::Function<>&) /home/su/software/tmp/polly/llvm/include/llvm/IR/PassManager.h:460:0
#&#8203;24 0x00000000039efdf5 llvm::CGSCCToFunctionPassAdaptor<llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function<> >> >::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph<llvm::CGSCCToFunctionPassAdaptor<llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function<> >> >&> >&, llvm::LazyCallGraph::SCC&, llvm::CGSCCUpdateResult&) /home/su/software/tmp/polly/llvm/include/llvm/Analysis/CGSCCPassManager.h:619:0
#&#8203;25 0x00000000039f0171 llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::CGSCCToFunctionPassAdaptor<llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function<> >> >, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC<llvm::LazyCallGraph&> >, llvm::PreservedAnalyses, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::LazyCallGraph&, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC<llvm::LazyCallGraph&> >) /home/su/software/tmp/polly/llvm/include/llvm/IR/PassManagerInternal.h:81:0
#&#8203;26 0x0000000003acd288 llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) /home/su/software/tmp/polly/llvm/lib/Analysis/CGSCCPassManager.cpp:73:0
#&#8203;27 0x00000000039f53ee llvm::DevirtSCCRepeatedPass<llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC<llvm::LazyCallGraph&> >, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&> >::run(llvm::LazyCallGraph::SCC&, llvm::LazyCallGraph::SCC<llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult) /home/su/software/tmp/polly/llvm/include/llvm/Analysis/CGSCCPassManager.h:736:0
#&#8203;28 0x00000000039f9126 llvm::ModuleToPostOrderCGSCCPassAdaptor<llvm::DevirtSCCRepeatedPass<llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC<llvm::LazyCallGraph&> >, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&> > >::run(llvm::Module&, llvm::AnalysisManager<llvm::ModuleToPostOrderCGSCCPassAdaptor<llvm::DevirtSCCRepeatedPass<llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC<llvm::LazyCallGraph&> >, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&> > ><> >&) /home/su/software/tmp/polly/llvm/include/llvm/Analysis/CGSCCPassManager.h:433:0
#&#8203;29 0x00000000039f9991 llvm::detail::PassModel<llvm::Module, llvm::ModuleToPostOrderCGSCCPassAdaptor<llvm::DevirtSCCRepeatedPass<llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&> > >, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) /home/su/software/tmp/polly/llvm/include/llvm/IR/PassManagerInternal.h:81:0
#&#8203;30 0x0000000001c14c1b llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) /home/su/software/tmp/polly/llvm/include/llvm/IR/PassManager.h:460:0
#&#8203;31 0x00000000039afba1 llvm::detail::PassModel<llvm::Module, llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module<> >>, llvm::PreservedAnalyses, llvm::Module<><> >::run(llvm::Module&, llvm::Module<>&) /home/su/software/tmp/polly/llvm/include/llvm/IR/PassManagerInternal.h:81:0
#&#8203;32 0x0000000001c14c1b llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) /home/su/software/tmp/polly/llvm/include/llvm/IR/PassManager.h:460:0
#&#8203;33 0x000000000223d39b (anonymous namespace)::EmitAssemblyHelper::EmitAssemblyWithNewPassManager(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) /home/su/software/tmp/polly/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp:977:0
#&#8203;34 0x000000000223f14a std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >::~unique_ptr() /usr/include/c++/5/bits/unique_ptr.h:235:0
#&#8203;35 0x000000000223f14a clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) /home/su/software/tmp/polly/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp:1143:0
#&#8203;36 0x0000000002a4d5a7 std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >::~unique_ptr() /usr/include/c++/5/bits/unique_ptr.h:235:0
#&#8203;37 0x0000000002a4d5a7 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) /home/su/software/tmp/polly/llvm/tools/clang/lib/CodeGen/CodeGenAction.cpp:292:0
#&#8203;38 0x0000000002c21238 void std::swap<bool>(bool&, bool&) /usr/include/c++/5/bits/move.h:187:0
#&#8203;39 0x0000000002c21238 clang::ParseAST(clang::Sema&, bool, bool) /home/su/software/tmp/polly/llvm/tools/clang/lib/Parse/ParseAST.cpp:161:0
#&#8203;40 0x0000000002a4ca3f clang::CodeGenAction::ExecuteAction() /home/su/software/tmp/polly/llvm/tools/clang/lib/CodeGen/CodeGenAction.cpp:1032:0
#&#8203;41 0x00000000025ec376 clang::FrontendAction::Execute() /home/su/software/tmp/polly/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:897:0
#&#8203;42 0x00000000025bc9a6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/su/software/tmp/polly/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:992:0
#&#8203;43 0x000000000267a892 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/su/software/tmp/polly/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:252:0
#&#8203;44 0x0000000000a90fb8 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /home/su/software/tmp/polly/llvm/tools/clang/tools/driver/cc1_main.cpp:221:0
#&#8203;45 0x0000000000a0b702 ExecuteCC1Tool /home/su/software/tmp/polly/llvm/tools/clang/tools/driver/driver.cpp:309:0
#&#8203;46 0x0000000000a0b702 main /home/su/software/tmp/polly/llvm/tools/clang/tools/driver/driver.cpp:388:0
#&#8203;47 0x00007ffb14c79830 __libc_start_main /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:325:0
#&#8203;48 0x0000000000a8d8d9 _start (/home/su/software/tmp/polly/llvm_build/bin/clang-6.0+0xa8d8d9)
Stack dump:
0.	Program arguments: /home/su/software/tmp/polly/llvm_build/bin/clang-6.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -main-file-name small.c -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -momit-leaf-frame-pointer -resource-dir /home/su/software/tmp/polly/llvm_build/lib/clang/6.0.0 -internal-isystem /usr/local/include -internal-isystem /home/su/software/tmp/polly/llvm_build/lib/clang/6.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O1 -fdebug-compilation-dir /home/su -ferror-limit 19 -fmessage-length 116 -fexperimental-new-pass-manager -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/small-c07e06.o -x c small.c 
1.	<eof> parser at end of file
2.	Optimizer
clang-6.0: error: unable to execute command: Aborted (core dumped)
clang-6.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0 (http://llvm.org/git/clang.git 68e041468bfb4a364acdfa32abb0c7e38cfb938e) (http://llvm.org/git/llvm.git 986395e8cd168305bcf7a9463fb0fc9696218f0b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
clang-6.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-6.0: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-6.0: note: diagnostic msg: /tmp/small-4c90cd.c
clang-6.0: note: diagnostic msg: /tmp/small-4c90cd.sh
clang-6.0: note: diagnostic msg: 

********************
$ 

------------------------------------------

int a, b, c, d;

void fn1 (int e)
{
  while (d) 
    {
      int f, g = 6;
      while (g--)
        {
          while (c)
            f++;
          for (b = 0; b < 50; b += 2)
            e && (a = 0);
        }
    }
}

int main ()
{
  fn1 (0);
  return 0; 
}

**Comment by fhahn** [comment]
I cannot reproduce this on current main, so this is likely fixed. I am closing the issue, but please re-open with more details if it still reproduces on your end!
