### ISSUE TITLE
Failure to delete dead store

### ISSUE THREAD

**Issue by silvasean** [llvm/llvm-project#34491]
|  |  |
| --- | --- |
| Bugzilla Link | [35143](https://llvm.org/bz35143) |
| Version | trunk |
| OS | Linux |
| CC | @GabrielRavier,@ramosian-glider,@hfinkel,@pogo59 |

## Extended Description 
struct S {
  int x[5];
};

S get_S();

void foo() {
  S s = get_S();
  s.x[5] = 8;
}

https://godbolt.org/g/QcpRBY

Clang does not delete the store to `s.x[5] = 8`.

Looking at the IR, the pointer out argument passed to get_S seems to be marked as `sret`. I don't know if that is strong enough to allow inferring `noescape` on the pointer, but even manually adding `noescape` I don't see that store being deleted by the O2 pipeline.

**Comment by Endilll** [comment]
Seems indeed fixed in Clang 12: https://godbolt.org/z/ETfT96vq8
