### ISSUE TITLE
Codegen for x86 produces an unnecessary cmp instruction.

### ISSUE THREAD

**Issue by e0e1e613-dccb-47a5-85db-3dc989429265** [llvm/llvm-project#34550]
|  |  |
| --- | --- |
| Bugzilla Link | [35202](https://llvm.org/bz35202) |
| Version | trunk |
| OS | All |
| CC | @topperc,@hfinkel,@RKSimon,@rotateright |

## Extended Description 
Clang figures out that it can omit cmp instruction, when you use equality, but doesn't if you use a reverse comparison (which is a very common thing to do, in STL for example).

godbolt: https://godbolt.org/g/Wy9eWR

**Comment by RKSimon** [comment]
Closing - we now have test coverage, and both test cases only use a single cmp
