### ISSUE TITLE
Formatter breaks code while sorting includes

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34626]
|  |  |
| --- | --- |
| Bugzilla Link | [35278](https://llvm.org/bz35278) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mydeveloperday |

## Extended Description 
Formatter breaks code while sorting includes.

Very simple repro:

=== foo.c:
```
#include <stdio.h>
#include <stdint.h> /* long
                       comment */
```

`clang-format foo.c` (so, the default config) reformats it to:

```
#include <stdint.h> /* long
#include <stdio.h>
                       comment */
```

`clang-format --version`:
clang-format version 6.0.0 (trunk 317949)

**Comment by mkurdej** [comment]
Revision URI: https://reviews.llvm.org/D118627
