### ISSUE TITLE
dbg.addr location lists are wrong

### ISSUE THREAD

**Issue by adrian-prantl** [llvm/llvm-project#34666]
|  |  |
| --- | --- |
| Bugzilla Link | [35318](https://llvm.org/bz35318) |
| Version | trunk |
| OS | All |
| CC | @adrian-prantl,@dstenb,@dwblaikie,@jmorse,@rnk |

## Extended Description 
$ cat /tmp/test.c
int main(int argc, char **argv) {
  printf(argv[0]);
  int i = argc;
  ++i;
  ++i;
  return i;
}
$ clang --version
clang version 6.0.0 (trunk 318314) (llvm/trunk 318312)
$ clang -mllvm -use-dbg-addr -o /tmp/test /tmp/test.c -g
$ dwarfdump /tmp/test.dSYM

0x0000002a:     TAG_subprogram [2] *
                 AT_low_pc( 0x0000000100000f40 )
                 AT_high_pc( 0x0000004a )
                 AT_frame_base( rbp )
                 AT_name( "main" )
...

0x0000005f:         TAG_variable [4]  
                     AT_location( 0x00000000
                        0x0000000100000f84 - 0x0000000100000f8a: rbp-20 )
                     AT_name( "i" )
                     AT_decl_file( "/private/tmp/test.c" )
                     AT_decl_line( 3 )
                     AT_type( {0x0000006f} ( int ) )

**Comment by jryans** [comment]
`dbg.addr` has been [removed](https://discourse.llvm.org/t/dbg-addr-intrinsic-slated-for-removal/68781), so I believe it makes sense to close this issue. Feel free to reopen if I have misunderstood.
