### ISSUE TITLE
clang-cl crashes when compiling incorrect code

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34673]
|  |  |
| --- | --- |
| Bugzilla Link | [35325](https://llvm.org/bz35325) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [Auto-generated crash dump](https://user-images.githubusercontent.com/60944935/143756578-5286f8c9-7539-4623-8d2f-67f728adf182.gz), [Run Script](https://user-images.githubusercontent.com/60944935/143756579-92903ba4-432a-44cd-89c3-b73221038524.gz), [Preprocessed source (gzip'd)](https://user-images.githubusercontent.com/60944935/143756580-117f71d7-d85f-49a9-8ba1-295fb06eaf8c.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Occasionally when compiling code in the PowerShell terminal in Visual Studio Code clang-cl will crash instead of displaying the proper error message. I have only been able to reproduce this crash in Visual Studio Code's PowerShell terminal. This does not occur in an independent PowerShell session (could be a Visual Studio Code problem?).

The code being compiled was a simple hello world program, intentionally malformed using single quotes for the string rather than the proper double quotes -> 'Hello, World!\n'

Attached is the crash backtrace, preprocessed source, and run script.

Platform: Windows 10 Pro x64 Version 1709 (Fall Creator's Update)
Visual Studio Code Insiders 1.19.0 x64 with
Latest Windows 64-bit LLVM SVN Build from https://llvm.org/builds/
clang-cl options: /std:c++17 /TP /Wall /WX

Steps to reproduce (though only sometimes occurs):

1) Open broken Hello World (using 'Hello, World!\n' rather than "Hello, World!\n" in std::cout line) source in Visual Studio Code

2) Open integrated PowerShell terminal in Visual Studio Code
3) Compile hello_world with 'clang-cl.exe /std:c++17 /TP /Wall /WX hello_world.cpp'

Expected results:
clang-cl prints out proper error message and cleanly exits as such:
.\hello_world.cpp(5,15):  error: multi-character character constant [-Werror,-Wmultichar]
        std::cout << 'Hello, World!\n';
                     ^
.\hello_world.cpp(5,15):  error: character constant too long for its type [-Werror]
2 errors generated.

Actual results:
clang-cl crashes printing gibberish to the console and displays bug report notice.

**Comment by Endilll** [comment]
Can't reproduce using Clang 4 through 7 with assertions enabled.
