### ISSUE TITLE
[ASan/Win] lld-link doesn't link ASAN binaries

### ISSUE THREAD

**Issue by sesse** [llvm/llvm-project#34691]
|  |  |
| --- | --- |
| Bugzilla Link | [35343](https://llvm.org/bz35343) |
| Resolution | DUPLICATE |
| Resolved on | Jun 12, 2018 11:36 |
| Version | 5.0 |
| OS | Windows NT |
| CC | @rnk,@vitalybuka |

## Extended Description 
Hi,

I'm trying to run MySQL with ASAN on Windows (we're already clean on Linux). However, seemingly linking with LLD isn't automatic:

R:\ade\sesse\mysql\obj\mysql-test>"c:\Program Files\LLVM\msbuild-bin\cl.exe" /nologo /c hello.cpp -fsanitize=address
R:\ade\sesse\mysql\obj\mysql-test>"c:\Program Files\LLVM\bin\lld-link.exe" /out:hello.exe hello.obj
c:\Program Files\LLVM\bin\lld-link.exe: warning: hello.obj: undefined symbol: __asan_shadow_memory_dynamic_address
c:\Program Files\LLVM\bin\lld-link.exe: warning: hello.obj: undefined symbol: __asan_option_detect_stack_use_after_return
c:\Program Files\LLVM\bin\lld-link.exe: warning: hello.obj: undefined symbol: __asan_stack_malloc_0
c:\Program Files\LLVM\bin\lld-link.exe: warning: hello.obj: undefined symbol: __asan_report_load8
c:\Program Files\LLVM\bin\lld-link.exe: warning: hello.obj: undefined symbol: __asan_init
c:\Program Files\LLVM\bin\lld-link.exe: warning: hello.obj: undefined symbol: __asan_version_mismatch_check_v8
error: link failed

I can link in clang_rt.asan-x86_64.lib manually by giving the path, and then simple tests work, but anything that tries to do LoadLibrary dies, so I suppose this is the wrong approach:

==18756==AddressSanitizer CHECK failed: C:\src\llvm_package_500\llvm\projects\compiler-rt\lib\asan\asan_win.cc:179 "((::
__interception::OverrideFunction("RtlRaiseException", (uptr)__asan_wrap_RtlRaiseException, (uptr *)&__interception::real
_RtlRaiseException))) != (0)" (0x0, 0x0)
    #&#8203;0 0x7ffe458b8fcf in _asan_init+0x16f (R:\ade\sesse\mysql\obj\plugin_output_directory\keyring_udf.dll+0x180cb8fcf)
    #&#8203;1 0x7ffe458c326b in __sanitizer::CheckFailed+0x5b (R:\ade\sesse\mysql\obj\plugin_output_directory\keyring_udf.dll+0
x180cc326b)
    #&#8203;2 0x7ffe458cdbe8 in _asan_wrap_CreateThread+0x248 (R:\ade\sesse\mysql\obj\plugin_output_directory\keyring_udf.dll+0
x180ccdbe8)
    #&#8203;3 0x7ffe458c00e7 in _asan_wrap_atol+0x9c7 (R:\ade\sesse\mysql\obj\plugin_output_directory\keyring_udf.dll+0x180cc00
e7)
    #&#8203;4 0x7ffe458b8451 in _asan_storeN_noabort+0x181 (R:\ade\sesse\mysql\obj\plugin_output_directory\keyring_udf.dll+0x18
0cb8451)
    #&#8203;5 0x7ffe65f8a37e in RtlDeactivateActivationContextUnsafeFast+0x1be (C:\Windows\SYSTEM32\ntdll.dll+0x18002a37e)
    #&#8203;6 0x7ffe65f678c4 in RtlGetThreadErrorMode+0x434 (C:\Windows\SYSTEM32\ntdll.dll+0x1800078c4)
    #&#8203;7 0x7ffe65f676e7 in RtlGetThreadErrorMode+0x257 (C:\Windows\SYSTEM32\ntdll.dll+0x1800076e7)
    #&#8203;8 0x7ffe65f67566 in RtlGetThreadErrorMode+0xd6 (C:\Windows\SYSTEM32\ntdll.dll+0x180007566)
    #&#8203;9 0x7ffe65f6d33c in RtlDeleteBoundaryDescriptor+0x1cc (C:\Windows\SYSTEM32\ntdll.dll+0x18000d33c)
    #&#8203;10 0x7ffe65f870b8 in RtlFormatCurrentUserKeyPath+0x7b8 (C:\Windows\SYSTEM32\ntdll.dll+0x1800270b8)
    #&#8203;11 0x7ffe65f86afc in RtlFormatCurrentUserKeyPath+0x1fc (C:\Windows\SYSTEM32\ntdll.dll+0x180026afc)
    #&#8203;12 0x7ffe65f69efb in LdrLoadDll+0x8b (C:\Windows\SYSTEM32\ntdll.dll+0x180009efb)
    #&#8203;13 0x7ffe6329484e in LoadLibraryExW+0x16e (C:\Windows\System32\KERNELBASE.dll+0x18002484e)
    #&#8203;14 0x7ffe632d1c80 in LoadLibraryExA+0x30 (C:\Windows\System32\KERNELBASE.dll+0x180061c80)
    #&#8203;15 0x7ff7d37dd638  (R:\ade\sesse\mysql\obj\runtime_output_directory\mysqld.exe+0x14321d638)
    #&#8203;16 0x7ff7d34d7698  (R:\ade\sesse\mysql\obj\runtime_output_directory\mysqld.exe+0x142f17698)
    #&#8203;17 0x7ff7d34d0b6c  (R:\ade\sesse\mysql\obj\runtime_output_directory\mysqld.exe+0x142f10b6c)
    #&#8203;18 0x7ff7d34c9056  (R:\ade\sesse\mysql\obj\runtime_output_directory\mysqld.exe+0x142f09056)
    #&#8203;19 0x7ff7d34ce0cf  (R:\ade\sesse\mysql\obj\runtime_output_directory\mysqld.exe+0x142f0e0cf)
    #&#8203;20 0x7ff7d32d2093  (R:\ade\sesse\mysql\obj\runtime_output_directory\mysqld.exe+0x142d12093)
    #&#8203;21 0x7ff7d30a3c6c  (R:\ade\sesse\mysql\obj\runtime_output_directory\mysqld.exe+0x142ae3c6c)
    #&#8203;22 0x7ff7d35ff7ab  (R:\ade\sesse\mysql\obj\runtime_output_directory\mysqld.exe+0x14303f7ab)
    #&#8203;23 0x7ff7d7804e03  (R:\ade\sesse\mysql\obj\runtime_output_directory\mysqld.exe+0x147244e03)
    #&#8203;24 0x7ff7d307ee56  (R:\ade\sesse\mysql\obj\runtime_output_directory\mysqld.exe+0x142abee56)
    #&#8203;25 0x7ffe636f8363 in BaseThreadInitThunk+0x13 (C:\Windows\System32\KERNEL32.DLL+0x180008363)
    #&#8203;26 0x7ffe65fc7090 in RtlUserThreadStart+0x20 (C:\Windows\SYSTEM32\ntdll.dll+0x180067090)

Shouldn't this go automatically? I can't find a way to link with cl.exe; on Linux, I guess the clang driver with -fsanitize=address does magic behind the scenes, but giving -fsanitize=address to lld-link seemingly isn't allowed.

**Comment by hmelder** [comment]
This would require me to check for `/MD` as well because the libraries differ:

## `clang-cl lib.cpp main.cpp /fsanitize=address /Oy- /MT -v`:

```
 "C:\\Program Files\\LLVM\\bin\\lld-link" -out:lib.exe "-libpath:C:\\Program Files\\LLVM\\lib\\clang\\18\\lib\\windows" -nologo -debug -incremental:no "C:\\Program Files\\LLVM\\lib\\clang\\18\\lib\\windows\\clang_rt.asan-aarch64.lib" "-wholearchive:C:\\Program Files\\LLVM\\lib\\clang\\18\\lib\\windows\\clang_rt.asan-aarch64.lib" "C:\\Program Files\\LLVM\\lib\\clang\\18\\lib\\windows\\clang_rt.asan_cxx-aarch64.lib" "-wholearchive:C:\\Program Files\\LLVM\\lib\\clang\\18\\lib\\windows\\clang_rt.asan_cxx-aarch64.lib" "C:\\Users\\hugo\\AppData\\Local\\Temp\\lib-48dc9d.obj" "C:\\Users\\hugo\\AppData\\Local\\Temp\\main-e215e9.obj"```
 
 ## `clang-cl lib.cpp main.cpp /fsanitize=address /Oy- /MD -v`:
 
 ```
 "C:\\Program Files\\LLVM\\bin\\lld-link" -out:lib.exe "-libpath:C:\\Program Files\\LLVM\\lib\\clang\\18\\lib\\windows" -nologo -debug -incremental:no "C:\\Program Files\\LLVM\\lib\\clang\\18\\lib\\windows\\clang_rt.asan_dynamic-aarch64.lib" "C:\\Program Files\\LLVM\\lib\\clang\\18\\lib\\windows\\clang_rt.asan_dynamic_runtime_thunk-aarch64.lib" -include:__asan_seh_interceptor "-wholearchive:C:\\Program Files\\LLVM\\lib\\clang\\18\\lib\\windows\\clang_rt.asan_dynamic_runtime_thunk-aarch64.lib" "C:\\Users\\hugo\\AppData\\Local\\Temp\\lib-c86153.obj" "C:\\Users\\hugo\\AppData\\Local\\Temp\\main-a06a55.obj"
 ```
