### ISSUE TITLE
[GlobalISel][AArch64] Calling convention for vectors incorrect on big-endian targets

### ISSUE THREAD

**Issue by ostannard** [llvm/llvm-project#34708]
|  |  |
| --- | --- |
| Bugzilla Link | [35360](https://llvm.org/bz35360) |
| Version | trunk |
| OS | Linux |
| Depends On | llvm/llvm-project#26535  |
| CC | @qcolombet |

## Extended Description 
Global-isel generates incorrect code when targeting big-endian AArch64 for this code:
  #include <arm_neon.h>
  int32x2_t load_vector(int32x2_t *p) {
    return *p;
  }

Global-isel generates this:
  // armclang --target=aarch64-arm-none-eabi -march=armv8-a -c callees.cpp -O0 -Wall -std=c++11 -mllvm -global-isel=true -mllvm -global-isel-abort=0 -mbig-endian -o - -S
  _Z11load_vectorP11__Int32x2_t:          // @&#8203;_Z11load_vectorP11__Int32x2_t
  // BB#0:                                // %entry
          sub     sp, sp, #&#8203;16             // =16
          str     x0, [sp, #&#8203;8]
          ldr     x0, [sp, #&#8203;8]
          ld1     { v0.2s }, [x0]
          add     sp, sp, #&#8203;16             // =16
          ret

With global-isel off, there is a rev64 instruction between the ld1 and the add, which fixes up the endianness of the vector.

**Comment by aemerson** [comment]
Closing as we're not going to implement BE support for AArch64 GISel any time soon. This has been worked around via a fallback instead.
