### ISSUE TITLE
[GlobalISel][AArch64] Calling convention for small arguments passed on stack incorrect on big-endian targets

### ISSUE THREAD

**Issue by ostannard** [llvm/llvm-project#34709]
|  |  |
| --- | --- |
| Bugzilla Link | [35361](https://llvm.org/bz35361) |
| Version | trunk |
| OS | Linux |
| Depends On | llvm/llvm-project#26535  |
| CC | @qcolombet |

## Extended Description 
Global-isel generates incorrect code when targeting big-endian AArch64 for this code:
  int foo(int x0, int x1, int x2, int x3, int x4, int x5, int x6, int x7,
          int stack1) {
    return stack1;
  }

  int main() {
    int ret = foo(0,1,2,3,4,5,6,7,8);
    printf("%d\n", ret);
  }

Global isel thinks that the incoming value of stack1 is stored in bytes [0,4) above SP, but for big-endian targets this should be in bytes [4,8):

// /work/llvm/build/bin/clang --target=aarch64-arm-none-eabi -march=armv8-a -c callees.cpp -O0 -Wall -std=c++11 -mllvm -global-isel=true -mllvm -global-isel-abort=0 -mbig-endian -o - -S
_Z3fooiiiiiiiii:                        // @&#8203;_Z3fooiiiiiiiii
// BB#0:                                // %entry
        sub     sp, sp, #&#8203;48             // =48
        ldr     w8, [sp, #&#8203;48]   // <= Should be [sp, #&#8203;52]
        str     w0, [sp, #&#8203;44]
        str     w1, [sp, #&#8203;40]
        str     w2, [sp, #&#8203;36]
        str     w3, [sp, #&#8203;32]
        str     w4, [sp, #&#8203;28]
        str     w5, [sp, #&#8203;24]
        str     w6, [sp, #&#8203;20]
        str     w7, [sp, #&#8203;16]
        str     w8, [sp, #&#8203;12]
        ldr     w0, [sp, #&#8203;12]
        add     sp, sp, #&#8203;48             // =48
        ret

**Comment by aemerson** [comment]
Closing as we're not going to implement BE support for AArch64 GISel any time soon. This has been worked around via a fallback instead.
