### ISSUE TITLE
SubRange join failure with odd SubRange segments

### ISSUE THREAD

**Issue by dstutt** [llvm/llvm-project#34722]
|  |  |
| --- | --- |
| Bugzilla Link | [35374](https://llvm.org/bz35374) |
| Version | trunk |
| OS | All |
| Attachments | [llvm-ir based reproducer for the bug](https://user-images.githubusercontent.com/28561216/143756602-e33e9c26-a198-458b-b9af-56fef80124ed.gz) |

## Extended Description 

Another SubRange join failure. Distinct from others already reported (as far as I can tell).

See bug 35373, bug 33524, bug 33152 and bug 32773 for details of the others.

Attached is a reproducer - transforming this to .mir doesn't work as it no longer provokes the problem so it's a .ll instead

Initial investigation seems to suggest this is probably due to SubRanges having Segments of the form [1234r, 1234d:0) as in other cases (just in a different place).

**Comment by arsenm** [comment]
Can't reproduce, missing invocation instructions but nothing I've tried breaks it. A bunch of these types of failures are fixed so it probably was fixed (although it's also quite possibly just hidden, IR tests are too fragile for these long term)
