### ISSUE TITLE
SubRange join failure

### ISSUE THREAD

**Issue by dstutt** [llvm/llvm-project#34721]
|  |  |
| --- | --- |
| Bugzilla Link | [35373](https://llvm.org/bz35373) |
| Version | trunk |
| OS | All |
| Attachments | [Reproducer for subrange join failure](https://user-images.githubusercontent.com/28561216/143756601-3b919ae3-e21f-4d53-8927-df8eba6c867d.gz) |

## Extended Description 

There are some other SubRange join failures reported, but since the ones I've investigated have resulted in different fixes I'm filing a fresh one for this reproducer.

See bug 32773, bug 33152 and bug 33524 for details of the others

The attached reproducer will provoke the problem.

Easiest way to do this is:
llc -march=amdgcn -run-pass simple-register-coalescer -o - regcoal-subrange-join-seg.mir

**Comment by arsenm** [comment]
[regcoal-subrange-join-seg.mir.txt](https://github.com/llvm/llvm-project/files/12296279/regcoal-subrange-join-seg.mir.txt)

Modernized testcase works now
