### ISSUE TITLE
no diagnostic issued for invalid friend declaration involving dependent member of the current instantiation

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#34725]
|  |  |
| --- | --- |
| Bugzilla Link | [35377](https://llvm.org/bz35377) |
| Version | unspecified |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Testcase (inspired by testcase for gcc.gnu.org/#65157 ):

template<typename T> struct A {
  struct B;
  template<typename U> struct C;
};

template <typename T>
struct A<T>::B {
  template<typename U> void f();
};

template<typename T> template <typename U>
struct A<T>::C {
 friend void B::f<U>();
};

template<> struct A<int>::B {};
A<int>::C<int> c;

This crashes during IR generation. The root cause is that the friend declaration was marked invalid without any diagnostic being issued. It *is* invalid (we aren't supposed to be looking up things within B, because it's a dependent type, so it can't be given template arguments with <...>), but we should actually produce an error saying so.

**Comment by apinski-cavium** [comment]
The way the import worked messed up a comment here: "gcc.gnu.org/#65157" Should have stayed "gcc.gnu.org/PR65157"

**Comment by Endilll** [comment]
Appears to be fixed in Clang 7: https://godbolt.org/z/51vrdYdMb
