### ISSUE TITLE
Crash in ARM backend for fmaxnum/fminnum

### ISSUE THREAD

**Issue by stephenhines** [llvm/llvm-project#34720]
|  |  |
| --- | --- |
| Bugzilla Link | [35372](https://llvm.org/bz35372) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced ll file](https://user-images.githubusercontent.com/17790020/143756600-4b3d9d22-c359-4e72-9720-96da244fc56b.gz) |
| CC | @rovka,@kbeyls,@pirama-arumuga-nainar,@stephenhines,@yroux |

## Extended Description 

The attached test case breaks for fmaxnum. We also tested a few variations in this source file. Changing the call to fminnum also will crash similarly. If we remove the fp-armv8 flag, then the bug goes away (but the new instructions aren't used either). There are also slightly different crashes if you change a constant value from -3.276800e+04 to -3.376800e+04, but it isn't obvious if this is just a different manifestation of the same bug.

$ llc bugpoint-reduced-simplified.ll 
LLVM ERROR: Cannot select: t12: v4f32 = fmaxnum t22, undef:v4f32
  t22: v4f32 = bitcast t21
    t21: v4i32 = ARMISD::VMOVIMM TargetConstant:i32<1735>
      t20: i32 = TargetConstant<1735>
  t11: v4f32 = undef
In function: _ZN7android11volumeMultiILi4ELi8EsffisEEvPT1_jPKT2_PT4_PKT3_T5_

**Comment by arsenm** [comment]
Duplicate #26618

**Comment by xgupta** [comment]
On current trunk this message got print when compiling the reduce test case. 

'-d16' is not a recognized feature for this target (ignoring feature)
'-fp-only-sp' is not a recognized feature for this target (ignoring feature)
'-d16' is not a recognized feature for this target (ignoring feature)
'-fp-only-sp' is not a recognized feature for this target (ignoring feature)
