### ISSUE TITLE
clang-format breaks formatting when an attribute (C++17) precedes a variable initialized with braces

### ISSUE THREAD

**Issue by mkurdej** [llvm/llvm-project#34734]
|  |  |
| --- | --- |
| Bugzilla Link | [35386](https://llvm.org/bz35386) |
| Version | trunk |
| OS | Windows NT |

## Extended Description 
The simple code:

```
    int i{};
    [[maybe_unused]] int i{};
    int i{1};
    [[maybe_unused]] int i{1};
```

gets formatted to:

```
    int i {};
    [[maybe_unused]] int i {};
    int i { 1 };
    [[maybe_unused]] int i { 1 };
```

Style: LLVM (or anything else actually).

clang-format built from trunk on 2017-11-22.

**Comment by mydeveloperday** [comment]
This seems to be resolved some time before v8, please reopen if you think this is still an issue

```
int i{};
[[maybe_unused]] int i{};
int i{1};
[[maybe_unused]] int i{1};
```
