### ISSUE TITLE
[Modules TS] assertion in lib/AST/Decl.cpp:1397: D->getCachedLinkage() == LV.getLinkage()

### ISSUE THREAD

**Issue by boris-kolpackov** [llvm/llvm-project#34746]
|  |  |
| --- | --- |
| Bugzilla Link | [35398](https://llvm.org/bz35398) |
| Version | trunk |
| OS | Linux |
| Attachments | [Reproducing script.](https://user-images.githubusercontent.com/92601698/143756608-25a0ae2f-5c74-4123-b0f6-977d5085b112.gz) |
| CC | @dwblaikie,@DougGregor,@zygoloid |

## Extended Description 

The attached reproducer triggers an assertion:

lib/AST/Decl.cpp:1397: clang::LinkageInfo clang::LinkageComputer::getLVForDecl(const clang::NamedDecl*, clang::LVComputationKind): Assertion `D->getCachedLinkage() == LV.getLinkage()' failed.

D is function ansec(). Interestingly, making ansec() static gets rid of the assertion.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 15: https://cexplorer.testlabs.pro/z/dM9Wvd
