### ISSUE TITLE
clang crashes (SEGV) with -Wall when passing a variable array into a lambda

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34758]
|  |  |
| --- | --- |
| Bugzilla Link | [35410](https://llvm.org/bz35410) |
| Version | trunk |
| OS | Linux |
| Attachments | [Sample source](https://user-images.githubusercontent.com/60944935/143756617-e038ad0b-b969-4145-87be-a2d3870ce317.gz), [Preprocessed source and runscript](https://user-images.githubusercontent.com/60944935/143756618-655856e8-58a7-450b-9770-354fec799bb6.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 

HostOS: Ubuntu 17.04
Clang:  6.0-trunk as per 20171120

The clang++ front-end crashes on the attached source code when -Wall is specified. Without -Wall, it reports:

clangex.cpp:32:14: error: variable-sized object may not be initialized
                thread t( [timers]() {
                           ^~~~~~

Command-line:
clang++ -c -std=c++14 -Wall -o clangex.o clangex.cpp

Crash output:
#&#8203;0 0x00007f3b70b304fa llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/lib/llvm-6.0/bin/../lib/libLLVM-6.0.so.1+0x8264fa)
#&#8203;1 0x00007f3b70b2e68e llvm::sys::RunSignalHandlers() (/usr/lib/llvm-6.0/bin/../lib/libLLVM-6.0.so.1+0x82468e)
#&#8203;2 0x00007f3b70b2e7ca (/usr/lib/llvm-6.0/bin/../lib/libLLVM-6.0.so.1+0x8247ca)
#&#8203;3 0x00007f3b73c3c670 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11670)
#&#8203;4 0x0000556763b29def clang::FormatASTNodeDiagnosticArgument(clang::DiagnosticsEngine::ArgumentKind, long, llvm::StringRef, llvm::StringRef, llvm::ArrayRef<std::pair<clang::DiagnosticsEngine::ArgumentKind, long> >, llvm::SmallVectorImpl<char>&, void*, llvm::ArrayRef<long>) (/usr/lib/llvm-6.0/bin/clang+0x178cdef)
#&#8203;5 0x00005567629a3669 clang::Diagnostic::FormatDiagnostic(char const*, char const*, llvm::SmallVectorImpl<char>&) const (/usr/lib/llvm-6.0/bin/clang+0x606669)
#&#8203;6 0x0000556762db728e clang::TextDiagnosticPrinter::HandleDiagnostic(clang::DiagnosticsEngine::Level, clang::Diagnostic const&) (/usr/lib/llvm-6.0/bin/clang+0xa1a28e)
#&#8203;7 0x00005567629a7c40 clang::DiagnosticIDs::EmitDiag(clang::DiagnosticsEngine&, clang::DiagnosticIDs::Level) const (/usr/lib/llvm-6.0/bin/clang+0x60ac40)
#&#8203;8 0x00005567629a7dbf clang::DiagnosticIDs::ProcessDiag(clang::DiagnosticsEngine&) const (/usr/lib/llvm-6.0/bin/clang+0x60adbf)
#&#8203;9 0x00005567629a19b4 clang::DiagnosticsEngine::EmitCurrentDiagnostic(bool) (/usr/lib/llvm-6.0/bin/clang+0x6049b4)
#&#8203;10 0x000055676321a46a clang::Sema::EmitCurrentDiagnostic(unsigned int) (/usr/lib/llvm-6.0/bin/clang+0xe7d46a)
#&#8203;11 0x00005567634d5655 clang::Sema::BuildLambdaExpr(clang::SourceLocation, clang::SourceLocation, clang::sema::LambdaScopeInfo*) (/usr/lib/llvm-6.0/bin/clang+0x1138655)
#&#8203;12 0x00005567634d7aba clang::Sema::ActOnLambdaExpr(clang::SourceLocation, clang::Stmt*, clang::Scope*) (/usr/lib/llvm-6.0/bin/clang+0x113aaba)
#&#8203;13 0x00005567630a44e5 clang::Parser::ParseLambdaExpressionAfterIntroducer(clang::LambdaIntroducer&) (/usr/lib/llvm-6.0/bin/clang+0xd074e5)
#&#8203;14 0x00005567630a5d6b clang::Parser::ParseLambdaExpression() (/usr/lib/llvm-6.0/bin/clang+0xd08d6b)
#&#8203;15 0x0000556763091d07 clang::Parser::ParseCastExpression(bool, bool, bool&, clang::Parser::TypeCastState, bool) (/usr/lib/llvm-6.0/bin/clang+0xcf4d07)
#&#8203;16 0x0000556763092c34 clang::Parser::ParseCastExpression(bool, bool, clang::Parser::TypeCastState, bool) (/usr/lib/llvm-6.0/bin/clang+0xcf5c34)
#&#8203;17 0x0000556763092ccc clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/usr/lib/llvm-6.0/bin/clang+0xcf5ccc)
#&#8203;18 0x0000556763094d89 clang::Parser::ParseExpressionList(llvm::SmallVectorImpl<clang::Expr*>&, llvm::SmallVectorImpl<clang::SourceLocation>&, llvm::function_ref<void ()>) (/usr/lib/llvm-6.0/bin/clang+0xcf7d89)
#&#8203;19 0x000055676306291a clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/usr/lib/llvm-6.0/bin/clang+0xcc591a)
#&#8203;20 0x00005567630706cd clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, unsigned int, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/usr/lib/llvm-6.0/bin/clang+0xcd36cd)
#&#8203;21 0x0000556763073994 clang::Parser::ParseSimpleDeclaration(unsigned int, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, bool, clang::Parser::ForRangeInit*) (/usr/lib/llvm-6.0/bin/clang+0xcd6994)
#&#8203;22 0x0000556763073c9e clang::Parser::ParseDeclaration(unsigned int, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) (/usr/lib/llvm-6.0/bin/clang+0xcd6c9e)
#&#8203;23 0x00005567630da5bd clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedConstructsKind, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/usr/lib/llvm-6.0/bin/clang+0xd3d5bd)
#&#8203;24 0x00005567630da76f clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedConstructsKind, clang::SourceLocation*) (/usr/lib/llvm-6.0/bin/clang+0xd3d76f)
#&#8203;25 0x00005567630df371 clang::Parser::ParseCompoundStatementBody(bool) (/usr/lib/llvm-6.0/bin/clang+0xd42371)
#&#8203;26 0x00005567630dfa5e clang::Parser::ParseCompoundStatement(bool, unsigned int) (/usr/lib/llvm-6.0/bin/clang+0xd42a5e)
#&#8203;27 0x00005567630dfa92 clang::Parser::ParseCompoundStatement(bool) (/usr/lib/llvm-6.0/bin/clang+0xd42a92)
#&#8203;28 0x00005567630da2ca clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedConstructsKind, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/usr/lib/llvm-6.0/bin/clang+0xd3d2ca)
#&#8203;29 0x00005567630da76f clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedConstructsKind, clang::SourceLocation*) (/usr/lib/llvm-6.0/bin/clang+0xd3d76f)
#&#8203;30 0x00005567630da8e4 clang::Parser::ParseStatement(clang::SourceLocation*, bool) (/usr/lib/llvm-6.0/bin/clang+0xd3d8e4)
#&#8203;31 0x00005567630dde44 clang::Parser::ParseIfStatement(clang::SourceLocation*) (/usr/lib/llvm-6.0/bin/clang+0xd40e44)
#&#8203;32 0x00005567630da14b clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedConstructsKind, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/usr/lib/llvm-6.0/bin/clang+0xd3d14b)
#&#8203;33 0x00005567630da76f clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedConstructsKind, clang::SourceLocation*) (/usr/lib/llvm-6.0/bin/clang+0xd3d76f)
#&#8203;34 0x00005567630df371 clang::Parser::ParseCompoundStatementBody(bool) (/usr/lib/llvm-6.0/bin/clang+0xd42371)
#&#8203;35 0x00005567630e1c10 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/usr/lib/llvm-6.0/bin/clang+0xd44c10)
#&#8203;36 0x000055676304f2cd clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/usr/lib/llvm-6.0/bin/clang+0xcb22cd)
#&#8203;37 0x0000556763070d82 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, unsigned int, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/usr/lib/llvm-6.0/bin/clang+0xcd3d82)
#&#8203;38 0x000055676304a28a clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/usr/lib/llvm-6.0/bin/clang+0xcad28a)
#&#8203;39 0x000055676304a9a1 (/usr/lib/llvm-6.0/bin/clang+0xcad9a1)
#&#8203;40 0x000055676304a9df clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/usr/lib/llvm-6.0/bin/clang+0xcad9df)
#&#8203;41 0x0000556763051868 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/usr/lib/llvm-6.0/bin/clang+0xcb4868)
#&#8203;42 0x0000556763052446 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/usr/lib/llvm-6.0/bin/clang+0xcb5446)
#&#8203;43 0x000055676304677b clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/llvm-6.0/bin/clang+0xca977b)
#&#8203;44 0x0000556762f11117 clang::CodeGenAction::ExecuteAction() (/usr/lib/llvm-6.0/bin/clang+0xb74117)
#&#8203;45 0x0000556762d6f11e clang::FrontendAction::Execute() (/usr/lib/llvm-6.0/bin/clang+0x9d211e)
#&#8203;46 0x0000556762d3c946 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/llvm-6.0/bin/clang+0x99f946)
#&#8203;47 0x0000556762dfb793 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/llvm-6.0/bin/clang+0xa5e793)
#&#8203;48 0x000055676299aaf0 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/llvm-6.0/bin/clang+0x5fdaf0)
#&#8203;49 0x00005567629874c4 main (/usr/lib/llvm-6.0/bin/clang+0x5ea4c4)
#&#8203;50 0x00007f3b6f4893f1 __libc_start_main /build/glibc-mXZSwJ/glibc-2.24/csu/../csu/libc-start.c:325:0
#&#8203;51 0x000055676299880a _start (/usr/lib/llvm-6.0/bin/clang+0x5fb80a)
Stack dump:
0.	Program arguments: /usr/lib/llvm-6.0/bin/clang -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name clangex.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /home/mober/work/clangex.gcno -resource-dir /usr/lib/llvm-6.0/lib/clang/6.0.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/backward -internal-isystem /usr/include/clang/6.0.0/include/ -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-6.0/lib/clang/6.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -Wall -std=c++14 -fdeprecated-macro -fdebug-compilation-dir /home/mober/work -ferror-limit 19 -fmessage-length 204 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o clangex.o -x c++ clangex.cpp 
1.	clangex.cpp:34:5: current parser token ')'
2.	clangex.cpp:19:1: parsing function body 'SessionManager::destroySession'
3.	clangex.cpp:19:1: in compound statement ('{}')
4.	clangex.cpp:22:16: in compound statement ('{}')
5.	clangex.cpp:32:13: lambda expression parsing
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0-svn318632-1~exp1 (trunk)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-6.0/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/clangex-264826.cpp
clang: note: diagnostic msg: /tmp/clangex-264826.sh
clang: note: diagnostic msg:

**Comment by wheatman** [comment]
This seems to have by the final 6.0.0 version
https://godbolt.org/z/vYoGfedeb

for reference
code
```
int main(int argc, char**)
{
    float adj[argc];
    [&adj]() {};
    
    return 0;
}
```

old dump
```
#0 0x000055f6bc492bea llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x1e92bea)
#1 0x000055f6bc490a86 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x1e90a86)
#2 0x000055f6bc490bcc SignalHandler(int) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x1e90bcc)
#3 0x00007f87f19d1420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
#4 0x000055f6bdc9176f clang::FormatASTNodeDiagnosticArgument(clang::DiagnosticsEngine::ArgumentKind, long, llvm::StringRef, llvm::StringRef, llvm::ArrayRef<std::pair<clang::DiagnosticsEngine::ArgumentKind, long> >, llvm::SmallVectorImpl<char>&, void*, llvm::ArrayRef<long>) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x369176f)
#5 0x000055f6bc60e881 clang::Diagnostic::FormatDiagnostic(char const*, char const*, llvm::SmallVectorImpl<char>&) const (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x200e881)
#6 0x000055f6bca73a1f clang::TextDiagnosticPrinter::HandleDiagnostic(clang::DiagnosticsEngine::Level, clang::Diagnostic const&) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2473a1f)
#7 0x000055f6bc616140 clang::DiagnosticIDs::EmitDiag(clang::DiagnosticsEngine&, clang::DiagnosticIDs::Level) const (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2016140)
#8 0x000055f6bc61848a clang::DiagnosticIDs::ProcessDiag(clang::DiagnosticsEngine&) const (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x201848a)
#9 0x000055f6bc60dc73 clang::DiagnosticsEngine::EmitCurrentDiagnostic(bool) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x200dc73)
#10 0x000055f6bd2e1909 clang::Sema::EmitCurrentDiagnostic(unsigned int) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2ce1909)
#11 0x000055f6bd2b7fbb clang::Sema::SemaDiagnosticBuilder::~SemaDiagnosticBuilder() (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2cb7fbb)
#12 0x000055f6bd5d47ce clang::Sema::DiagnoseUnusedLambdaCapture(clang::sema::CapturingScopeInfo::Capture const&) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2fd47ce)
#13 0x000055f6bd5d97a7 clang::Sema::BuildLambdaExpr(clang::SourceLocation, clang::SourceLocation, clang::sema::LambdaScopeInfo*) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2fd97a7)
#14 0x000055f6bd5dbe0c clang::Sema::ActOnLambdaExpr(clang::SourceLocation, clang::Stmt*, clang::Scope*) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2fdbe0c)
#15 0x000055f6bd161c7b clang::Parser::ParseLambdaExpressionAfterIntroducer(clang::LambdaIntroducer&) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b61c7b)
#16 0x000055f6bd162d93 clang::Parser::ParseLambdaExpression() (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b62d93)
#17 0x000055f6bd150d7e clang::Parser::ParseCastExpression(bool, bool, bool&, clang::Parser::TypeCastState, bool) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b50d7e)
#18 0x000055f6bd152024 clang::Parser::ParseCastExpression(bool, bool, clang::Parser::TypeCastState, bool) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b52024)
#19 0x000055f6bd15378c clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b5378c)
#20 0x000055f6bd154359 clang::Parser::ParseExpression(clang::Parser::TypeCastState) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b54359)
#21 0x000055f6bd196dda clang::Parser::ParseExprStatement() (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b96dda)
#22 0x000055f6bd197896 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedConstructsKind, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b97896)
#23 0x000055f6bd198160 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedConstructsKind, clang::SourceLocation*) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b98160)
#24 0x000055f6bd19bddc clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b9bddc)
#25 0x000055f6bd19e65b clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b9e65b)
#26 0x000055f6bd111195 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b11195)
#27 0x000055f6bd130b53 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, unsigned int, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b30b53)
#28 0x000055f6bd10b361 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b0b361)
#29 0x000055f6bd10b9a1 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) [clone .part.150] (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b0b9a1)
#30 0x000055f6bd112285 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b12285)
#31 0x000055f6bd113346 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b13346)
#32 0x000055f6bd1134a0 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b134a0)
#33 0x000055f6bd107adb clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x2b07adb)
#34 0x000055f6bce5db77 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x285db77)
#35 0x000055f6bca2b676 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x242b676)
#36 0x000055f6bc9f5f1c clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x23f5f1c)
#37 0x000055f6bcad46e3 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x24d46e3)
#38 0x000055f6baf31e48 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x931e48)
#39 0x000055f6baeacfa8 main (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x8acfa8)
#40 0x00007f87f147f083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#41 0x000055f6baf2f65a _start (/opt/compiler-explorer/clang-5.0.2/bin/clang-5.0+0x92f65a)
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-5.0.2/bin/clang-5.0 -cc1 -triple x86_64-unknown-linux-gnu -S -disable-free -disable-llvm-verifier -discard-value-names -main-file-name example.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -coverage-notes-file /app/output.gcno -resource-dir /opt/compiler-explorer/clang-5.0.2/lib/clang/5.0.2 -internal-isystem /opt/compiler-explorer/gcc-7.3.0/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0 -internal-isystem /opt/compiler-explorer/gcc-7.3.0/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/x86_64-linux-gnu -internal-isystem /opt/compiler-explorer/gcc-7.3.0/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/backward -internal-isystem /usr/local/include -internal-isystem /opt/compiler-explorer/clang-5.0.2/lib/clang/5.0.2/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -Wall -std=c++14 -fdeprecated-macro -fdebug-compilation-dir /app -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -mllvm --x86-asm-syntax=intel -o /app/output.s -x c++ <source> 
1.	<source>:4:16: current parser token ';'
2.	<source>:2:1: parsing function body 'main'
3.	<source>:2:1: in compound statement ('{}')
4.	<source>:4:5: lambda expression parsing
clang-5.0: error: unable to execute command: Segmentation fault (core dumped)
clang-5.0: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 254
```
