### ISSUE TITLE
ICE on Android NDK

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34840]
|  |  |
| --- | --- |
| Bugzilla Link | [35492](https://llvm.org/bz35492) |
| Version | unspecified |
| OS | other |
| Attachments | [dump+diagnostic_msg+scrip](https://user-images.githubusercontent.com/60944935/143756656-b8964ac5-b12d-4977-8882-adc24dec11ed.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

ICE on native Android project. Don't know what exactly cause it.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process C:\Users\Andy\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\AndroidProjects\cpptest1\app\.externalNativeBuild\cmake\debug\x86_64 --target native-lib}
  [1/2] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o
  FAILED: C:\NDK\android-ndk-r15c\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=x86_64-none-linux-android --gcc-toolchain=C:/NDK/android-ndk-r15c/toolchains/x86_64-4.9/prebuilt/windows-x86_64 --sysroot=C:/NDK/android-ndk-r15c/sysroot  -Dnative_lib_EXPORTS -isystem C:/NDK/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem C:/NDK/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86_64/include -isystem C:/NDK/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -isystem C:/NDK/android-ndk-r15c/sysroot/usr/include/x86_64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++1z -frtti -fexceptions -Werror=return-type -Werror=uninitialized -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -MF CMakeFiles\native-lib.dir\src\main\cpp\native-lib.cpp.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -c C:\AndroidProjects\cpptest1\app\src\main\cpp\native-lib.cpp
  Wrote crash dump file "C:\Users\Andy\AppData\Local\Temp\clang++.exe-a59a8e.dmp"
  0x00000000012135E6 (0x0000000003B8A940 0x0000000007A69860 0x0000000007AB6470 0x0000000000294BDE)
  0x00000000007827DD (0x000000000AEBD650 0x0000000001263748 0x0000000000000002 0x00000000025204D1)
  0x0000000000782C6D (0x000000000AE3B828 0x000000000AEBDB88 0x00000000096DD278 0x000000000AE3A770)
  0x000000000089D878 (0x0000000007AB6470 0x000000000AEBDB88 0x000000000AEBDB88 0x00000000011E09C9)
  0x00000000008ABE77 (0x0000000000000000 0x0000000000000000 0x0000000003B8C0F8 0x0000000000000000)
  0x00000000008ACCE7 (0x000000000B65A480 0x00000000010D69AE 0x0000000003B8C3C0 0x0000000003B8C350)
  0x00000000008AD54C (0x0000000007A65320 0x000000000AED69C8 0x0000000007AF67F0 0x00000000009DDB06)
  0x0000000000E1B148 (0x0000000000000000 0x000000000AE3C590 0x0000000000000001 0x0000000000E05848)
  0x0000000000E1AF52 (0x0000000000000000 0x000000000AED69C8 0x000000000B6C34E8 0x00000000011E0B6D)
  0x0000000000E1A148 (0x0000000000001022 0x000000000AE66148 0x0000000007AF7380 0x0000000007B35BD0)
  0x0000000000E1AD15 (0x0000000000000000 0x0000000007AEF020 0x0000000000000000 0x0000000003B8E240)
  0x0000000000A0EF38 (0x0000000003B8E4F0 0x0000000007AEF020 0x0000000003704AF0 0x00000000009C874C)
  0x00000000009C86B6 (0x0000000003B8E6D0 0x000000000AF5B178 0x0000000007A56138 0x0000000002CCF4C0)
  0x00000000009327AB (0x0000000000000000 0x0000000007A69C20 0x0000000007A69F20 0x00007FFFD1826A79)
  0x000000000087E221 (0x0000000002CCF4D8 0x000000000000000D 0x0000000002CCF4D8 0x00000000036BF7FF)
  0x000000000045C916 (0x000000000000000A 0x0000000002A91256 0x0000000000000008 0x0000000007A66700)
  0x0000000000438905 (0x0000000007A5B980 0x000000000265C550 0x000000000265BDB0 0x0000000002A91256)
  0x00000000004093C4 (0x0000000007A63890 0x0000000000028510 0x0000000000020000 0x00007FFFD182BADC)
  0x0000000000402948 (0x0000000000000001 0x0000000003B8EFA0 0x0000000000000000 0x0000000003B8EFD8)
  0x0000000002A93610 (0x000000000000005E 0x000000000000003C 0x0000000000000000 0x0000000000000000)
  0x00000000004013B5 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
  0x00000000004014E8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
  0x00007FFFCEF21FE4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
  0x00007FFFD186EF91 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
  clang++.exe: error: clang frontend command failed due to signal (use -v to see invocation)
  Android clang version 5.0.300080  (based on LLVM 5.0.300080)
  Target: x86_64-none-linux-android
  Thread model: posix
  InstalledDir: C:\NDK\android-ndk-r15c\toolchains\llvm\prebuilt\windows-x86_64\bin
  clang++.exe: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
  clang++.exe: note: diagnostic msg: 
  ********************
  
  PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
  Preprocessed source(s) and associated run script(s) are located at:
  clang++.exe: note: diagnostic msg: C:\Users\Andy\AppData\Local\Temp\native-lib-db106c.cpp
  clang++.exe: note: diagnostic msg: C:\Users\Andy\AppData\Local\Temp\native-lib-db106c.sh
  clang++.exe: note: diagnostic msg: 
  
  ********************
  ninja: build stopped: subcommand failed.

**Comment by Endilll** [comment]
Can't reproduce using Clang 4 through 7 with assertions enabled.
