### ISSUE TITLE
clang-format incorrectly handles multiple Java annotations with period

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34893]
|  |  |
| --- | --- |
| Bugzilla Link | [35545](https://llvm.org/bz35545) |
| Version | unspecified |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
If there are multiple Java annotations on a field/method/type, and the annotations contain a period in the name, then clang-format will break after the first period and add an indent level

Input:

@&#8203;Kroll.getProperty
@&#8203;Kroll.method
public IntentProxy getLaunchIntent()
{

Result:
@&#8203;Kroll
	.getProperty
	@Kroll.method
	public IntentProxy getLaunchIntent()
{

Workaround:

// clang-format off
@&#8203;Kroll.getProperty
@&#8203;Kroll.method
public IntentProxy getLaunchIntent()
// clang-format on
{

**Comment by rymiel** [comment]
This seems to have been fixed with clang-format 10
