### ISSUE TITLE
Assertion `Ty && "Trying to add a type that doesn't exist?"' failed on Windows self host

### ISSUE THREAD

**Issue by rgal** [llvm/llvm-project#34891]
|  |  |
| --- | --- |
| Bugzilla Link | [35543](https://llvm.org/bz35543) |
| Version | trunk |
| OS | Windows NT |
| CC | @amccarth-google,@gregbedwell,@rnk |

## Extended Description 
At r319883. Found building a Windows self host compiler with debug. Seen on DeltaAlgorithm.cpp and other files.

Example reduced from DeltaAlgorithm.cpp

$ cat test.cpp
class A {
  typedef void _Nodeptr;
};
class B {
  A FailedTestsCache;
  bool m_fn1();
};
bool B::m_fn1() {}

$ clang++ -cc1 -emit-obj -gcodeview -debug-info-kind=limited -dwarf-version=4 -x c++ test.cpp
test.cpp:8:18: warning: control reaches end of non-void function
bool B::m_fn1() {}
                 ^
clang++: /home/gbgallor/git/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.cpp:764: void llvm::DwarfUnit::addType(llvm::DIE&, const llvm::DIType*, llvm::dwarf::Attribute): Assertion `Ty && "Trying to add a type that doesn't exist?"' failed.

**Comment by Endilll** [comment]
Can't reproduce using both set of arguments with Clang 5 and 6 with assertions enabled: 
https://cexplorer.testlabs.pro/z/EMaWcK
https://cexplorer.testlabs.pro/z/h1sjba
