### ISSUE TITLE
Java: clang-format doesn't honor BreakBeforeBraces with @interface declarations

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34902]
|  |  |
| --- | --- |
| Bugzilla Link | [35554](https://llvm.org/bz35554) |
| Version | unspecified |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Related to #&#8203;21456.

If defining annotations in Java, we use the @&#8203;interface keyword designation. Ideally it would treated similarly to class/interface declarations and would honor the BreakBeforeBraces setting. However it always uses an Attach style brace

```
@Documented
@Retention(RetentionPolicy.SOURCE)
@Target(ElementType.FIELD)
public static @interface property
{
}
```

with BreakBeforeBraces: Allman still produces

```
Documented
Retention(RetentionPolicy.SOURCE)
Target(ElementType.FIELD)
public static @interface property {
}
```

**Comment by mydeveloperday** [comment]
with clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 7890afddecff01119f4d5e8825b
43dd2c8361648)

And

```
Language: Java
BasedOnStyle: LLVM
BreakBeforeBraces: Allman
```

This is what we see, as such I am going to assume this is fixed and close this issue, please feel free to reopen if you still see issues

```
@Documented
@Retention(RetentionPolicy.SOURCE)
@Target(ElementType.FIELD)
public static @interface property
{
}
```
