### ISSUE TITLE
Adler32 Hash; clang 7.0 is 1.3x slower than gcc 7.3

### ISSUE THREAD

**Issue by cf10018d-1d2e-41f9-ab09-cc4591d6d858** [llvm/llvm-project#34915]
|  |  |
| --- | --- |
| Bugzilla Link | [35567](https://llvm.org/bz35567) |
| Version | 7.0 |
| OS | Linux |
| Attachments | [Adler32 C implementation](https://user-images.githubusercontent.com/92601821/143756681-b187ca26-c3c4-480e-8bb4-76e72e42eff4.gz) |
| CC | @adibiagio,@topperc,@RKSimon,@rotateright |

## Extended Description 

adler32-standalone.c (attached, also at https://github.com/google/wuffs/blob/master/script/adler32-standalone.c) is some straight C code to calculate the standard Adler32 hash, used by the zlib format.

Measuring throughput on a recent Debian Testing system (clang 5.0 and gcc 7.2), Intel x86_64 Broadwell, suggests that clang's generated code is 1.3x slower.

$ clang-5.0 -O3 adler32-standalone.c; ./a.out
    2311 MiB/s, clang 5.0.0 (tags/RELEASE_500/rc2)
$ gcc       -O3 adler32-standalone.c; ./a.out
    3052 MiB/s, gcc 7.2.1 20171025

The core loop (manually unrolled 8 times) is:

while (p < end0) {
  s1 += ((uint32_t)(*p));
  s2 += s1; 
  p++;
  s1 += ((uint32_t)(*p));
  s2 += s1; 
  p++;
  s1 += ((uint32_t)(*p));
  s2 += s1; 
  p++;
  s1 += ((uint32_t)(*p));
  s2 += s1; 
  p++;
  s1 += ((uint32_t)(*p));
  s2 += s1; 
  p++;
  s1 += ((uint32_t)(*p));
  s2 += s1; 
  p++;
  s1 += ((uint32_t)(*p));
  s2 += s1; 
  p++;
  s1 += ((uint32_t)(*p));
  s2 += s1; 
  p++;
}

**Comment by tcShadowWalker** [comment]
It seems to me this issue is resolved in recent clang versions. (At least in clang-12, maybe earlier)

```
$ gcc-12 -o bin -O3 adler32.c && ./bin
    3005 MiB/s, gcc 12.3.0
$ clang-12 -o bin -O3 adler32.c && ./bin 
    3020 MiB/s, clang 12.0.1
```

I tried with clang-12, clang-13, clang-14 and clang-18, all giving similar results, at 3000 MiB/s.
On the gcc side, I tried gcc-11, gcc-12 and gcc-13, also all giving similar results.
