### ISSUE TITLE
[X86] Scheduler information missing for CRC32 instructions on haswell, broadwell, skylake

### ISSUE THREAD

**Issue by topperc** [llvm/llvm-project#34935]
|  |  |
| --- | --- |
| Bugzilla Link | [35587](https://llvm.org/bz35587) |
| Version | trunk |
| OS | All |
| Blocks | llvm/llvm-project#31672  |
| CC | @gchatelet,@RKSimon |

## Extended Description 
We have scheduling info for CRC32 on Sandybrige but not the other CPUs

**Comment by RKSimon** [comment]
This was fixed a long time ago shortly after we added the WriteCRC32 class
