### ISSUE TITLE
Missed optimization in math expression: aggressive optimization with std::pow

### ISSUE THREAD

**Issue by zamazan4ik** [llvm/llvm-project#34943]
|  |  |
| --- | --- |
| Bugzilla Link | [35595](https://llvm.org/bz35595) |
| Version | trunk |
| OS | All |
| Blocks | llvm/llvm-project#34959  |
| CC | @davidbolvansky,@efriedma-quic,@hfinkel,@rotateright |

## Extended Description 
clang(trunk) with '--std=c++17 -O3 -march=native -ffast-math' flags for this code:

#include <cmath>

double test(double a, double x)
{
    return pow(a, x) * a * a * a * a;
}

generates this assembly:

test(double, double): # @&#8203;test(double, double)
  push rax
  vmovsd qword ptr [rsp], xmm0 # 8-byte Spill
  call pow
  vmovsd xmm1, qword ptr [rsp] # 8-byte Reload
  vmulsd xmm1, xmm1, xmm1
  vmulsd xmm1, xmm1, xmm1
  vmulsd xmm0, xmm1, xmm0
  pop rax
  ret

As you can see, me can simplify it by adding 4 to 'x' variable and after call std::pow.

**Comment by rotateright** [comment]
All of the examples here should be optimized now. If there's still something missing, please open a new issue.
