### ISSUE TITLE
Optimizing std::search function

### ISSUE THREAD

**Issue by zamazan4ik** [llvm/llvm-project#34961]
|  |  |
| --- | --- |
| Bugzilla Link | [35613](https://llvm.org/bz35613) |
| Version | unspecified |
| OS | All |
| CC | @hfinkel,@mclow |

## Extended Description 
std::search can be optmized for Random Access Iterators by implementing inside search algorithm like Boyer-Moore or Boyer-Moore-Horspool or Musser-Nishanov algorithm (or smth faster). For Bidirectional iterators AFAIK Crochemore-Perrin algorithm is very good.

AFAIK, now std::search use only naive search algortihm. Can be it improved?

P.S. I know about changes in C++17 new search algorithms, but i suggest use the most efficient version for every type of iterators.

P.S.S Efficient algorithms you can find in Seqan library and in Boost.Algorithm.

**Comment by philnik777** [comment]
`std::search` isn't allowed to allocate memory, which the boyer-moore searchers have to do.
