### ISSUE TITLE
std::rotate can be order of magnitude faster, if it can allocate a buffer.

### ISSUE THREAD

**Issue by e0e1e613-dccb-47a5-85db-3dc989429265** [llvm/llvm-project#34962]
|  |  |
| --- | --- |
| Bugzilla Link | [35614](https://llvm.org/bz35614) |
| Version | unspecified |
| OS | All |
| CC | @hfinkel,@mclow |

## Extended Description 
Hi!

For one sided rotation you do optimize for one element on the stack:
https://github.com/llvm-mirror/libcxx/blob/master/include/algorithm#L2435

Actually this is a valid optimization for arbitrary number of elements and it can give you an order of magnitude speed up.

Here is a very naive implementation with measurements:
http://quick-bench.com/KjyAe88UUBAjSmDAbUsbkt1mLxQ

Is it ok for std::rotate to do this?
I'm happy to create a patch but some guidance on the benchmark and restrictions would be nice.

Best,
Dennis

**Comment by philnik777** [comment]
AFAICT this isn't a bug because `std::rotate` isn't allowed to allocate, so I'm closing it.
