### ISSUE TITLE
clang segfaults compiling gzip (and probably others) when using -march=native on Core2 Duo (penryn)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35026]
|  |  |
| --- | --- |
| Bugzilla Link | [35678](https://llvm.org/bz35678) |
| Version | 5.0 |
| OS | Linux |
| Attachments | [build log](https://user-images.githubusercontent.com/60944935/143756724-2f1129fc-4477-4464-89ee-f02dd8097781.gz), [backtrace](https://user-images.githubusercontent.com/60944935/143756725-92d67ca7-618f-409d-bfdd-c3c70d86a40c.gz), [https://user-images.githubusercontent.com/60944935/143756726-c1b9343b-9003-4293-b17e-ed680b0b252c.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@RKSimon |

## Extended Description 
Distro: Gentoo

Reproducilibility: Always

Affected Clang versions: 5.0.0 and 5.0.1_rc2

Expected result: No segfaults

Actual result:

==========

clang-5.0: error: unable to execute command: Segmentation fault
clang-5.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 5.0.1 (tags/RELEASE_501/rc2)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-5.0: note: diagnostic msg: PLEASE submit a bug report to  and include the crash backtrace, preprocessed source, and associated run script.
clang-5.0: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.

==========

I will attach the full build log below.

Workaround: Specifying -mno-sse4.1 eliminates the segfault, even though this CPU supports SSE 4.1

Is clang maybe trying to use some other SSE instructions that aren't available on this old-ish CPU?

**Comment by Endilll** [comment]
Can't reproduce using Clang 4 through 7.
