### ISSUE TITLE
Fails to compile documentation example on MacOSX

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#35040]
|  |  |
| --- | --- |
| Bugzilla Link | [35692](https://llvm.org/bz35692) |
| Version | trunk |
| OS | All |

## Extended Description 
I've installed MacOSX high sierra, updated xcode, installed latest cuda (CUDA 9.1), and when trying to compile the documentation example in: https://llvm.org/docs/CompileCudaWithLLVM.html#invoking-clang

like this:

clang++ axpy.cu -o axpy --cuda-gpu-arch=sm_35 -L/usr/local/cuda/lib -lcudart -ldl -lrt -pthread

it fails to compile with the following error: 

clang-6.0: error: cannot find libdevice for sm_35. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.

I've tried passing clang --cuda-path=/usr/local/cuda/ and also --cuda-path=/Developer/NVIDIA/CUDA-9.1/ without any luck.

The paths in /usr/local/cuda all link to /Developer/NVIDIA/CUDA-9.1/.

**Comment by arsenm** [comment]
Old build issue
