### ISSUE TITLE
modernize-use-equals-default check is probably inverted for destructors

### ISSUE THREAD

**Issue by tkrasnukha** [llvm/llvm-project#35063]
|  |  |
| --- | --- |
| Bugzilla Link | [35715](https://llvm.org/bz35715) |
| Version | unspecified |
| OS | Linux |
| CC | @EugeneZelenko,@tkrasnukha |

## Extended Description 
I get error: use '= default' to define a trivial destructor
for 
Process::~Process() {
  Finalize();
}
and 2 other dtors with non-empty body,
whereas CommLayerImplementor::~CommLayerImplementor() {} and one the same are treated as ok.

**Comment by PiotrZSL** [comment]
Not reproduced on trunk, I would assume that it were fixed during last changes to that check.
