### ISSUE TITLE
"readability-braces-around-statements" semicolon location error

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35102]
|  |  |
| --- | --- |
| Bugzilla Link | [35754](https://llvm.org/bz35754) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @tonyelewis |

## Extended Description 
clang-tools-extra git sha:bf75b14aaf1c50decb69deaa9cd0b46c2b3dddc6

How to reproduce:
$ clang-tidy -fix -config="{Checks: 'readability-braces-around-statements'}" llvm/lib/Transforms/Scalar/NewGVN.cpp -- $Headers

After applying tidy(wrong version): NewGVN.cpp in line 2101:

template <class T, class Range>
T *NewGVN::getMinDFSOfRange(const Range &R) const {
  std::pair<T *, unsigned> MinDFS = {nullptr, ~0U};
  for (const auto X : R) {
    auto DFSNum = InstrToDFSNum(X);
    if (DFSNum < MinDFS.second) {
      MinDFS = { X, DFSNum }
    };
  }
  return MinDFS.first;
}

The correct version should be:

template <class T, class Range>
T *NewGVN::getMinDFSOfRange(const Range &R) const {
  std::pair<T *, unsigned> MinDFS = {nullptr, ~0U};
  for (const auto X : R) {
    auto DFSNum = InstrToDFSNum(X);
    if (DFSNum < MinDFS.second) {
      MinDFS = { X, DFSNum };
    }
  }
  return MinDFS.first;
}

**Comment by PiotrZSL** [comment]
Fixed by 0becc4d721d0036e2e38d581bc487e27f78eb8a9
