### ISSUE TITLE
Crash in CodeGenModule::EmitCtorList

### ISSUE THREAD

**Issue by JaschaWetzel** [llvm/llvm-project#35124]
|  |  |
| --- | --- |
| Bugzilla Link | [35776](https://llvm.org/bz35776) |
| Version | trunk |
| OS | Windows NT |

## Extended Description 
// clang-cl /c -Xclang -std=c++14 -Xclang -fopenmp clang_static_ctor_ice.cc
#include <memory>

namespace some_ns {

template<class T>
struct S {
    static std::unique_ptr<S> m;
};

template<class T>
std::unique_ptr<S<T>> S<T>::m;

template class S<int>;

}

// Looks like I.AssociatedData in CodeGenModule.cpp:837 has an invalid type.

**Comment by Endilll** [comment]
Can't reproduce using Clang 5 and 6: https://godbolt.org/z/vK5hnTGMf
Feels Windows-specific.
