### ISSUE TITLE
libllvm5.0:amd64 changelog file conflicts with libllvm5.0:i386

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35123]
|  |  |
| --- | --- |
| Bugzilla Link | [35775](https://llvm.org/bz35775) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
On a Debian Stretch multiarch system with both i386 and amd64 llvm-toolchain-stretch-5.0 packages installed, upgrading now gives the following error:

$ sudo apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  libllvm5.0 libllvm5.0:i386
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/28.5 MB of archives.
After this operation, 2,048 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Retrieving bug reports... Done
Parsing Found/Fixed information... Done
Reading changelogs... Done
(Reading database ... 739971 files and directories currently installed.)
Preparing to unpack .../libllvm5.0_1%3a5.0.1~svn319952-1~exp1_amd64.deb ...
Unpacking libllvm5.0:amd64 (1:5.0.1~svn319952-1~exp1) over (1:5.0.1~svn319952-1~exp1) ...
dpkg: error processing archive /var/cache/apt/archives/libllvm5.0_1%3a5.0.1~svn319952-1~exp1_amd64.deb (--unpack):
 trying to overwrite shared '/usr/share/doc/libllvm5.0/changelog.Debian.gz', which is different from other instances of package libllvm5.0:amd64
Preparing to unpack .../libllvm5.0_1%3a5.0.1~svn319952-1~exp1_i386.deb ...
Unpacking libllvm5.0:i386 (1:5.0.1~svn319952-1~exp1) over (1:5.0.1~svn319952-1~exp1) ...
dpkg: error processing archive /var/cache/apt/archives/libllvm5.0_1%3a5.0.1~svn319952-1~exp1_i386.deb (--unpack):
 trying to overwrite shared '/usr/share/doc/libllvm5.0/changelog.Debian.gz', which is different from other instances of package libllvm5.0:i386
Errors were encountered while processing:
 /var/cache/apt/archives/libllvm5.0_1%3a5.0.1~svn319952-1~exp1_amd64.deb
 /var/cache/apt/archives/libllvm5.0_1%3a5.0.1~svn319952-1~exp1_i386.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
$

**Comment by MarcoFalke** [comment]
Is this still an issue?
