### ISSUE TITLE
ICE when naming conversion function of generic lambda

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [llvm/llvm-project#35129]
|  |  |
| --- | --- |
| Bugzilla Link | [35781](https://llvm.org/bz35781) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
When naming (a specialization of) the conversion function template of a generic lambda, Clang ICEs.

### SOURCE:
auto g = [](auto) -> int { return 0; };
using fptype = int (*)(int);
fptype fp = g.operator fptype();

### COMPILER INVOCATION:
clang -cc1 -xc++ -

### EXPECTED OUTPUT:
(Clean compile)

### ACTUAL OUTPUT:
#&#8203;0 0x0000000001b57c44 PrintStackTraceSignalHandler(void*) (/opt/wandbox/clang-head/bin/clang+0x1b57c44)
#&#8203;1 0x0000000001b57f16 SignalHandler(int) (/opt/wandbox/clang-head/bin/clang+0x1b57f16)
#&#8203;2 0x00007f43c6998390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
#&#8203;3 0x0000000002cf2b28 clang::Sema::MarkFunctionReferenced(clang::SourceLocation, clang::FunctionDecl*, bool) (/opt/wandbox/clang-head/bin/clang+0x2cf2b28)
#&#8203;4 0x0000000002c53177 clang::Sema::DefineImplicitLambdaToFunctionPointerConversion(clang::SourceLocation, clang::CXXConversionDecl*) (/opt/wandbox/clang-head/bin/clang+0x2c53177)
#&#8203;5 0x0000000002cf2ff5 clang::Sema::MarkFunctionReferenced(clang::SourceLocation, clang::FunctionDecl*, bool) (/opt/wandbox/clang-head/bin/clang+0x2cf2ff5)
#&#8203;6 0x0000000002cf6a97 MarkExprReferenced(clang::Sema&, clang::SourceLocation, clang::Decl*, clang::Expr*, bool) (/opt/wandbox/clang-head/bin/clang+0x2cf6a97)
#&#8203;7 0x0000000002d8294d clang::Sema::BuildMemberReferenceExpr(clang::Expr*, clang::QualType, clang::SourceLocation, bool, clang::CXXScopeSpec const&, clang::SourceLocation, clang::NamedDecl*, clang::LookupResult&, clang::TemplateArgumentListInfo const*, clang::Scope const*, bool, clang::Sema::ActOnMemberAccessExtraArgs*) (/opt/wandbox/clang-head/bin/clang+0x2d8294d)
#&#8203;8 0x0000000002d7d312 clang::Sema::BuildMemberReferenceExpr(clang::Expr*, clang::QualType, clang::SourceLocation, bool, clang::CXXScopeSpec&, clang::SourceLocation, clang::NamedDecl*, clang::DeclarationNameInfo const&, clang::TemplateArgumentListInfo const*, clang::Scope const*, clang::Sema::ActOnMemberAccessExtraArgs*) (/opt/wandbox/clang-head/bin/clang+0x2d7d312)
#&#8203;9 0x0000000002d8368c clang::Sema::ActOnMemberAccessExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, clang::tok::TokenKind, clang::CXXScopeSpec&, clang::SourceLocation, clang::UnqualifiedId&, clang::Decl*) (/opt/wandbox/clang-head/bin/clang+0x2d8368c)
#&#8203;10 0x000000000287f14b clang::Parser::ParsePostfixExpressionSuffix(clang::ActionResult<clang::Expr*, true>) (/opt/wandbox/clang-head/bin/clang+0x287f14b)
#&#8203;11 0x00000000028848ab clang::Parser::ParseCastExpression(bool, bool, bool&, clang::Parser::TypeCastState, bool) (/opt/wandbox/clang-head/bin/clang+0x28848ab)
#&#8203;12 0x000000000287d04f clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/opt/wandbox/clang-head/bin/clang+0x287d04f)
#&#8203;13 0x00000000028589ab clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/wandbox/clang-head/bin/clang+0x28589ab)
#&#8203;14 0x0000000002856a1c clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/wandbox/clang-head/bin/clang+0x2856a1c)
#&#8203;15 0x000000000283edeb clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/wandbox/clang-head/bin/clang+0x283edeb)
#&#8203;16 0x000000000283e718 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/wandbox/clang-head/bin/clang+0x283e718)
#&#8203;17 0x000000000283dae7 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/opt/wandbox/clang-head/bin/clang+0x283dae7)
#&#8203;18 0x000000000283c878 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/opt/wandbox/clang-head/bin/clang+0x283c878)
#&#8203;19 0x0000000002838be7 clang::ParseAST(clang::Sema&, bool, bool) (/opt/wandbox/clang-head/bin/clang+0x2838be7)
#&#8203;20 0x000000000208065f clang::FrontendAction::Execute() (/opt/wandbox/clang-head/bin/clang+0x208065f)
#&#8203;21 0x000000000203f508 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/wandbox/clang-head/bin/clang+0x203f508)
#&#8203;22 0x000000000210dc9e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/wandbox/clang-head/bin/clang+0x210dc9e)
#&#8203;23 0x000000000088a317 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/wandbox/clang-head/bin/clang+0x88a317)
#&#8203;24 0x00000000008891b8 main (/opt/wandbox/clang-head/bin/clang+0x8891b8)
#&#8203;25 0x00007f43c5707830 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20830)
#&#8203;26 0x0000000000886189 _start (/opt/wandbox/clang-head/bin/clang+0x886189)
Stack dump:
0.      Program arguments: /opt/wandbox/clang-head/bin/clang -cc1 -xc++ -
1.      <stdin>:3:30: current parser token '('

### COMPILER VERSION INFO (clang -v):
clang version 6.0.0 (https://github.com/llvm-mirror/clang.git ca674819d0450d7eb350c2205393a69dc206f3a9) (https://github.com/llvm-mirror/llvm.git 7a691a48b11ef2aafbc2ec2b0c75783d4b4088d6)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/wandbox/clang-head/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

**Comment by wheatman** [comment]
This seems to have been fixed between 5.0.0 and 6.0.0
https://cexplorer.testlabs.pro/z/5oqMsv

As a note this only occurred with assertions

for reference

code 
```
auto g = [](auto) -> int { return 0; };
using fptype = int (*)(int);
fptype fp = g.operator fptype();
```

dump
```
clang-5.0: /home/tonik/llvm-project/llvm/tools/clang/lib/Sema/SemaDeclCXX.cpp:12184: void clang::Sema::DefineImplicitLambdaToFunctionPointerConversion(clang::SourceLocation, clang::CXXConversionDecl*): Assertion `CallOpSpec && "Conversion operator must have a corresponding call operator"' failed.
#0 0x00000000021ad3da llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x21ad3da)
#1 0x00000000021aaf76 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x21aaf76)
#2 0x00000000021ab315 SignalHandler(int) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x21ab315)
#3 0x00007fc244c54df0 __restore_rt (/lib64/libc.so.6+0x54df0)
#4 0x00007fc244ca154c __pthread_kill_implementation (/lib64/libc.so.6+0xa154c)
#5 0x00007fc244c54d46 __GI_raise (/lib64/libc.so.6+0x54d46)
#6 0x00007fc244c287f3 __GI_abort (/lib64/libc.so.6+0x287f3)
#7 0x00007fc244c2871b _nl_load_domain.cold (/lib64/libc.so.6+0x2871b)
#8 0x00007fc244c4dce6 (/lib64/libc.so.6+0x4dce6)
#9 0x0000000003252636 (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x3252636)
#10 0x0000000003309ac6 clang::Sema::MarkFunctionReferenced(clang::SourceLocation, clang::FunctionDecl*, bool) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x3309ac6)
#11 0x000000000330e385 MarkExprReferenced(clang::Sema&, clang::SourceLocation, clang::Decl*, clang::Expr*, bool) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x330e385)
#12 0x0000000003393a75 BuildMemberExpr(clang::Sema&, clang::ASTContext&, clang::Expr*, bool, clang::SourceLocation, clang::CXXScopeSpec const&, clang::SourceLocation, clang::ValueDecl*, clang::DeclAccessPair, clang::DeclarationNameInfo const&, clang::QualType, clang::ExprValueKind, clang::ExprObjectKind, clang::TemplateArgumentListInfo const*) [clone .constprop.509] (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x3393a75)
#13 0x000000000339c192 clang::Sema::BuildMemberReferenceExpr(clang::Expr*, clang::QualType, clang::SourceLocation, bool, clang::CXXScopeSpec const&, clang::SourceLocation, clang::NamedDecl*, clang::LookupResult&, clang::TemplateArgumentListInfo const*, clang::Scope const*, bool, clang::Sema::ActOnMemberAccessExtraArgs*) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x339c192)
#14 0x000000000339c947 clang::Sema::BuildMemberReferenceExpr(clang::Expr*, clang::QualType, clang::SourceLocation, bool, clang::CXXScopeSpec&, clang::SourceLocation, clang::NamedDecl*, clang::DeclarationNameInfo const&, clang::TemplateArgumentListInfo const*, clang::Scope const*, clang::Sema::ActOnMemberAccessExtraArgs*) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x339c947)
#15 0x000000000339cc93 clang::Sema::ActOnMemberAccessExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, clang::tok::TokenKind, clang::CXXScopeSpec&, clang::SourceLocation, clang::UnqualifiedId&, clang::Decl*) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x339cc93)
#16 0x0000000002f3314a clang::Parser::ParsePostfixExpressionSuffix(clang::ActionResult<clang::Expr*, true>) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x2f3314a)
#17 0x0000000002f2e008 clang::Parser::ParseCastExpression(bool, bool, bool&, clang::Parser::TypeCastState, bool) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x2f2e008)
#18 0x0000000002f30204 clang::Parser::ParseCastExpression(bool, bool, clang::Parser::TypeCastState, bool) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x2f30204)
#19 0x0000000002f317ec clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x2f317ec)
#20 0x0000000002f01099 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x2f01099)
#21 0x0000000002f10a56 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, unsigned int, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x2f10a56)
#22 0x0000000002eebcc1 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x2eebcc1)
#23 0x0000000002eec2f1 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) [clone .part.166] (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x2eec2f1)
#24 0x0000000002ef200a clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x2ef200a)
#25 0x0000000002ef2ed8 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x2ef2ed8)
#26 0x0000000002ee7612 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x2ee7612)
#27 0x0000000002abfed8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x2abfed8)
#28 0x00000000027501e6 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x27501e6)
#29 0x0000000002719bde clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x2719bde)
#30 0x00000000027ec85a clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x27ec85a)
#31 0x0000000000a59238 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0xa59238)
#32 0x00000000009eafca main (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0x9eafca)
#33 0x00007fc244c3feb0 __libc_start_call_main (/lib64/libc.so.6+0x3feb0)
#34 0x00007fc244c3ff60 __libc_start_main_alias_2 (/lib64/libc.so.6+0x3ff60)
#35 0x0000000000a554f9 _start (/opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0+0xa554f9)
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-5.0.0-assert/bin/clang-5.0 -cc1 -triple x86_64-unknown-linux-gnu -S -disable-free -main-file-name example.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -coverage-notes-file /tmp/compiler-explorer-compiler202366-960250-1o1aznz.v4xqi/output.gcno -resource-dir /opt/compiler-explorer/clang-5.0.0-assert/lib/clang/5.0.0 -internal-isystem /opt/compiler-explorer/gcc-7.3.0/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0 -internal-isystem /opt/compiler-explorer/gcc-7.3.0/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/x86_64-linux-gnu -internal-isystem /opt/compiler-explorer/gcc-7.3.0/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/backward -internal-isystem /usr/local/include -internal-isystem /opt/compiler-explorer/clang-5.0.0-assert/lib/clang/5.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++14 -fdeprecated-macro -fdebug-compilation-dir /tmp/compiler-explorer-compiler202366-960250-1o1aznz.v4xqi -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -mllvm --x86-asm-syntax=intel -o /tmp/compiler-explorer-compiler202366-960250-1o1aznz.v4xqi/output.s -x c++ <source> 
1.	<source>:3:30: current parser token '('
clang-5.0: error: unable to execute command: Aborted (core dumped)
clang-5.0: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 254
```
