### ISSUE TITLE
Clang crashes with computed goto

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35175]
|  |  |
| --- | --- |
| Bugzilla Link | [35827](https://llvm.org/bz35827) |
| Version | 5.0 |
| OS | Windows NT |
| Attachments | [Preprocessed sources and run script](https://user-images.githubusercontent.com/60944935/143756801-386c76f1-2e7e-40ef-af09-67ae0cc4945c.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

I'm using Win7-x64 and Android NDK 16b. I have generated the standalone chain for Android Arm64 that uses Clang 5.0.300080 to generate 64 bit code.

When compiling a C file that contains a shellsort using computed goto jump tables, Clang crashes. The error message suggest to file a bug report.

When I replaced the computed goto shellsort with a version that does not use computed goto, Clang did not crash and produced a binary, as intended. So it has something to do with the computed goto.

I tried to isolate this computed goto shellsort into a single file and just sorting integers, but that did not crash Clang. So the issue is more complex than just computed goto.

I'm also using the Android NDK 16b standalone toolchain configured for Armv7-a with 32 bit target with the same application and the computed goto shellsort, and this works without problems.

**Comment by Endilll** [comment]
Can't reproduce using Clang 4 through 6 with assertions enabled.
