### ISSUE TITLE
modernize-use-using: don't change code in extern "C" {}

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35272]
|  |  |
| --- | --- |
| Bugzilla Link | [35924](https://llvm.org/bz35924) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dkalowsk,@JonasToth,@EugeneZelenko,@gburgessiv,@hokein,@johnmcfarlane,@LegalizeAdulthood,@Ralender,@tinti |

## Extended Description 
clang-tidy generates warnings specific to C++ for code that lies within the scope of an extern "C" {}

E.g. consider the following code

/* example.cpp */

/* This block simulates a C header */
#ifdef __cplusplus
extern "C" {
#endif

typedef int my_int_t;

#ifdef __cplusplus
} // extern "C"
#endif

// This block simulates a C++ implementation/use of the C header's API
#include <iostream>

int main()
{
  my_int_t value{42};
  std::cout << value << std::endl;
  return 0;
}

Compile with:

$ clang++ --std=c++14 -Wall example.cpp -o example

Run clang-tidy as:

$ clang-tidy example.cpp -checks='*' -- -std=c++14 -Wall

gives:

5307 warnings generated.
/home/duncan/temp/example.cpp:5:1: warning: use 'using' instead of 'typedef' [modernize-use-using]
typedef int my_int_t;
^~~~~~~~~~~~~~~~~~~~~
using my_int_t = int
Suppressed 5306 warnings (5306 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.

I don't think C++ checks should be applied to code within the scope of an extern "C" block.

**Comment by Da-Viper** [comment]
@Endilll Could this be assigned to me

**Comment by Endilll** [comment]
@Da-Viper sure!
