### ISSUE TITLE
Check for usage of std::endl

### ISSUE THREAD

**Issue by LegalizeAdulthood** [llvm/llvm-project#35321]
|  |  |
| --- | --- |
| Bugzilla Link | [35973](https://llvm.org/bz35973) |
| Version | unspecified |
| OS | All |
| CC | @madsravn |

## Extended Description 
Unfortunately it has become a common idiom to always use std::endl for newlines in C++ I/O streams, leading to lots of unnecessary buffer flushing in code.

Write a check that looks for (suspicious?) usages of std::endl and suggests a suitable replacement with '\n' (and/or std::flush).

If you wanted to keep this as a pure refactoring that preserved behavior while making the flush nature of endl blatant, then replace all calls to std::endl with '\n' << std::flush and leave it up to the developer to decide which instances of flush to eliminate.

This check is either a misc-, readability-, or performance- category check depending on your point of view.

Still, this sort of thing is so prevalent in C++ code, I think a check is warranted.  An option could control whether or not to insert the std::flush, but most of the time what you want is to get rid of the flush behavior, not preserve it.

**Comment by pradkrish** [comment]
Is this issue still open? I am beginner to llvm-project. I am happy to give this a go with some guidance :)

**Comment by EugeneZelenko** [comment]
@pradkrish: See https://clang.llvm.org/extra/clang-tidy/Contributing.html.
