### ISSUE TITLE
"Std::move of the variable '..' of the trivially-copyable type '..' has no effect" suggested incorrectly

### ISSUE THREAD

**Issue by k15tfu** [llvm/llvm-project#35360]
|  |  |
| --- | --- |
| Bugzilla Link | [36012](https://llvm.org/bz36012) |
| Version | unspecified |
| OS | All |
| CC | @k15tfu |

## Extended Description 
```
struct A;
extern int foo2(A&& a);
int foo1(A&& a) { return foo2(std::move(a)); }  //  <----  remove here

struct A { int _[100] = { 0 }; };
int foo() { return foo1(A()); }
int foo2(A&& a) {
    return a._[23];
}
```

The initial version is optimized the better way than the version without std::move().

Initial: https://godbolt.org/g/DesA7u
W/o std::move: https://godbolt.org/g/CREhJH

**Comment by PiotrZSL** [comment]
No it's not, example provided is incorrect.
Simply you compare passing by value vs passing by rvalue reference.
compare const reference vs rvalue reference to get same result.
