### ISSUE TITLE
Extend IndentPPDirectives with a BeforeHash option

### ISSUE THREAD

**Issue by aardappel** [llvm/llvm-project#35367]
|  |  |
| --- | --- |
| Bugzilla Link | [36019](https://llvm.org/bz36019) |
| Version | trunk |
| OS | All |
| CC | @hartwork |
| Fixed by commit(s) | rL356613 |

## Extended Description 
Currently `IndentPPDirectives` can have values `None`:

```
#ifdef FOO
#define BAR
#endif
```

or `AfterHash`:
```
#ifdef FOO
#    define BAR
#endif
```

I am suggesting to also add BeforeHash:

```
#ifdef FOO
    #define BAR
#endif
```

**Comment by mkurdej** [comment]
Closing as the option is already present since clang-format 9 (whereas clang-format 6 had only `None` and `AfterHash`). Please create another issue if you consider that the behaviour is faulty.
