### ISSUE TITLE
undefined behavior in SelectionDAGAddressAnalysis.cpp

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35422]
|  |  |
| --- | --- |
| Bugzilla Link | [36074](https://llvm.org/bz36074) |
| Version | trunk |
| OS | MacOS X |
| Attachments | [reduced code](https://user-images.githubusercontent.com/60944935/143756905-c1fa6dda-3785-494a-9dac-8bf18a8dee3e.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @MaskRay,@jdoerfert |

## Extended Description 

With the attached reduced file:

> llc -O1 SelectionDAG_UB.ll
[...]lib/CodeGen/SelectionDAG/SelectionDAGAddressAnalysis.cpp:23:22:
runtime error: signed integer overflow: 7124803381091165632 - -7949118599238474896 cannot be represented in type 'long long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior [...]lib/CodeGen/SelectionDAG/SelectionDAGAddressAnalysis.cpp:23:22 in 
Stack dump:
0.	Program arguments: llc -O1 SelectionDAG_UB.ll
1.	Running pass 'Function Pass Manager' on module 'SelectionDAG_UB.ll'.
2.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@Test'

**Comment by arsenm** [comment]
Last comment said can't reproduce
