### ISSUE TITLE
Stores to union incorrectly reordered

### ISSUE THREAD

**Issue by momchil-velikov** [llvm/llvm-project#35424]
|  |  |
| --- | --- |
| Bugzilla Link | [36076](https://llvm.org/bz36076) |
| Version | trunk |
| OS | Linux |
| Attachments | [minimal testcase](https://user-images.githubusercontent.com/5541560/143756906-079e4255-534c-404b-b78e-a0febc29eaa6.gz) |
| CC | @dwblaikie,@hfinkel |

## Extended Description 

The attached test program is mis-compiled at all optimisation levels, except -O0, for X86_64, Arm and likely for all targets.
 
./bin/clang -target x86_64-linux -O2 union-store.c
$ ./a.out 
value = 3, should be 2

This happens in Dead Store Elimination:

*** IR Dump After Value Propagation ***
; Function Attrs: norecurse nounwind
define void @&#8203;f() local_unnamed_addr #&#8203;0 {
entry:
  store i32 5, i32* getelementptr inbounds (%union.U, %union.U* @&#8203;a, i32 0, i32 0), align 4, !tbaa !&#8203;3
  %0 = load i16*, i16** bitcast (%union.U** @&#8203;b to i16**), align 4, !tbaa !&#8203;6
  store i16 3, i16* %0, align 4, !tbaa !&#8203;3
  store i16 2, i16* bitcast (%union.U* @&#8203;a to i16*), align 4, !tbaa !&#8203;3
  ret void
}
*** IR Dump After Dead Store Elimination ***
; Function Attrs: norecurse nounwind
define void @&#8203;f() local_unnamed_addr #&#8203;0 {
entry:
  store i32 2, i32* getelementptr inbounds (%union.U, %union.U* @&#8203;a, i32 0, i32 0), align 4, !tbaa !&#8203;3
  %0 = load i16*, i16** bitcast (%union.U** @&#8203;b to i16**), align 4, !tbaa !&#8203;6
  store i16 3, i16* %0, align 4, !tbaa !&#8203;3
  ret void
}

**Comment by jyknight** [comment]
Not reproducible now.
