### ISSUE TITLE
[clang-tidy] segmentation fault tools/clang/tools/extra/clang-tidy/fuchsia/MultipleInheritanceCheck.cpp, line 101

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35498]
|  |  |
| --- | --- |
| Bugzilla Link | [36150](https://llvm.org/bz36150) |
| Version | unspecified |
| OS | other |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
even on a simple hello world project, clang-tidy fails with :

Assertion failed: (Ty && "RecordType of base class is unknown"), function check, file ../tools/clang/tools/extra/clang-tidy/fuchsia/MultipleInheritanceCheck.cpp, line 101.

**Comment by carlosgalvezp** [comment]
No longer reproducible on latest trunk.
https://godbolt.org/z/v7rjx3v7a
