### ISSUE TITLE
clang-format removes space between macro name and definition in parens (thereby breaking the code)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35518]
|  |  |
| --- | --- |
| Bugzilla Link | [36170](https://llvm.org/bz36170) |
| Version | 5.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Given the following macro:
```
#define true ((int)1)
```
clang-format produces the following, incorrect, output that doesn't compile:
```
#define true((int)1)
```
I tried to find a configuration option related to this, but I couldn't find one. The problem is reproducible with the default configuration (without .clang-format).

**Comment by mkurdej** [comment]
Related issue: #31086.

**Comment by mkurdej** [comment]
This was fixed in clang-format 9.
