### ISSUE TITLE
llvm 6.0 (external lld 6.0) cmake undef refs while linking ../../lib/libLTO.so

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35523]
|  |  |
| --- | --- |
| Bugzilla Link | [36175](https://llvm.org/bz36175) |
| Version | 6.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Using gcc 7.2.1 on 4.14.15-1-ARCH, build with tag `release_60` from https://github.com/llvm-mirror/llvm with external lld  tag `release_60` from https://github.com/llvm-mirror/lld using cmake args:

-DLLVM_EXTERNAL_LLD_SOURCE_DIR=/path/to/lldrepo/root
-DLLVM_TOOL_BUILD_LLD=1

[ 85%] Linking CXX shared library ../../lib/libLTO.so
../../lib/libLLVMNVPTXCodeGen.a(NVPTXAsmPrinter.cpp.o): In function `llvm::NVPTXInstrInfo::~NVPTXInstrInfo()':
/mnt/data/src/llvm/llvm/lib/Target/NVPTX/NVPTXInstrInfo.h:26: undefined reference to `vtable for llvm::NVPTXInstrInfo'
../../lib/libLLVMNVPTXCodeGen.a(NVPTXAsmPrinter.cpp.o): In function `llvm::NVPTXTargetLowering::~NVPTXTargetLowering()':
/mnt/data/src/llvm/llvm/lib/Target/NVPTX/NVPTXISelLowering.h:440: undefined reference to `vtable for llvm::NVPTXTargetLowering'
../../lib/libLLVMNVPTXCodeGen.a(NVPTXSubtarget.cpp.o): In function `llvm::NVPTXSubtarget::NVPTXSubtarget(llvm::Triple const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, llvm::NVPTXTargetMachine const&)':
/mnt/data/src/llvm/llvm/lib/Target/NVPTX/NVPTXSubtarget.cpp:54: undefined reference to `llvm::NVPTXInstrInfo::NVPTXInstrInfo()'
/mnt/data/src/llvm/llvm/lib/Target/NVPTX/NVPTXSubtarget.cpp:54: undefined reference to `llvm::NVPTXTargetLowering::NVPTXTargetLowering(llvm::NVPTXTargetMachine const&, llvm::NVPTXSubtarget const&)'
../../lib/libLLVMNVPTXCodeGen.a(NVPTXTargetMachine.cpp.o): In function `LLVMInitializeNVPTXTarget':
/mnt/data/src/llvm/llvm/lib/Target/NVPTX/NVPTXTargetMachine.cpp:70: undefined reference to `llvm::initializeGenericToNVVMPass(llvm::PassRegistry&)'
/mnt/data/src/llvm/llvm/lib/Target/NVPTX/NVPTXTargetMachine.cpp:73: undefined reference to `llvm::initializeNVPTXLowerArgsPass(llvm::PassRegistry&)'
/mnt/data/src/llvm/llvm/lib/Target/NVPTX/NVPTXTargetMachine.cpp:74: undefined reference to `llvm::initializeNVPTXLowerAllocaPass(llvm::PassRegistry&)'
/mnt/data/src/llvm/llvm/lib/Target/NVPTX/NVPTXTargetMachine.cpp:75: undefined reference to `llvm::initializeNVPTXLowerAggrCopiesPass(llvm::PassRegistry&)'
../../lib/libLLVMNVPTXCodeGen.a(NVPTXTargetMachine.cpp.o): In function `(anonymous namespace)::NVPTXPassConfig::addAddressSpaceInferencePasses()':
/mnt/data/src/llvm/llvm/lib/Target/NVPTX/NVPTXTargetMachine.cpp:199: undefined reference to `llvm::createNVPTXLowerAllocaPass()'
../../lib/libLLVMNVPTXCodeGen.a(NVPTXTargetMachine.cpp.o): In function `(anonymous namespace)::NVPTXPassConfig::addIRPasses()':
/mnt/data/src/llvm/llvm/lib/Target/NVPTX/NVPTXTargetMachine.cpp:242: undefined reference to `llvm::createNVPTXImageOptimizerPass()'
/mnt/data/src/llvm/llvm/lib/Target/NVPTX/NVPTXTargetMachine.cpp:244: undefined reference to `llvm::createGenericToNVVMPass()'
/mnt/data/src/llvm/llvm/lib/Target/NVPTX/NVPTXTargetMachine.cpp:248: undefined reference to `llvm::createNVPTXLowerArgsPass(llvm::NVPTXTargetMachine const*)'
../../lib/libLLVMNVPTXCodeGen.a(NVPTXTargetMachine.cpp.o): In function `(anonymous namespace)::NVPTXPassConfig::addInstSelector()':
/mnt/data/src/llvm/llvm/lib/Target/NVPTX/NVPTXTargetMachine.cpp:277: undefined reference to `llvm::createLowerAggrCopies()'
/mnt/data/src/llvm/llvm/lib/Target/NVPTX/NVPTXTargetMachine.cpp:279: undefined reference to `llvm::createNVPTXISelDag(llvm::NVPTXTargetMachine&, llvm::CodeGenOpt::Level)'
../../lib/libLLVMNVPTXCodeGen.a(NVPTXTargetMachine.cpp.o): In function `llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile()':
/mnt/data/src/llvm/llvm/lib/Target/NVPTX/NVPTXTargetObjectFile.h:22: undefined reference to `vtable for llvm::NVPTXTargetObjectFile'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/lto/CMakeFiles/LTO.dir/build.make:269: lib/libLTO.so.6.0.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:18784: tools/lto/CMakeFiles/LTO.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by arsenm** [comment]
Old build issue
