### ISSUE TITLE
Crash during ParseAST

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35537]
|  |  |
| --- | --- |
| Bugzilla Link | [36189](https://llvm.org/bz36189) |
| Version | 4.0 |
| OS | Linux |
| Attachments | [The backtrace, source code and script to reproduce](https://user-images.githubusercontent.com/60944935/143756959-43fb2785-22bd-4ec8-b630-2f449f40b373.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@DimitryAndric,@walkerkd |

## Extended Description 

Attached is the pre-processed source code that on clang++ 4.0.1 crashes (when using -g and otherwise works) and on clang++ 5.0.1 seems to go into an infinite loop (regardless of -g flag).

**Comment by Endilll** [comment]
Appears to be fixed in Clang 6.
I see memory leak in Clang 4, and infinite loop in Clang 5. Both are too annoying and slow to bother reducing 17 MB of sources.
