### ISSUE TITLE
wrong code at -Os and -O2 on x86_64-linux-gnu in 64-bit mode

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#35577]
|  |  |
| --- | --- |
| Bugzilla Link | [36229](https://llvm.org/bz36229) |
| Version | unspecified |
| OS | All |
| CC | @hfinkel,@rotateright |

## Extended Description 
Tested with trunk revision 324184. 

$ clangpolly -v
clang version 7.0.0 (http://llvm.org/git/clang.git 6804b86ee9cc16b8a0dbc7024a497d179e88b4d4) (http://llvm.org/git/llvm.git 5a24493720154c8145652dd8d2dcee565bd50b99)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clangpolly -O1 small.c; ./a.out
6
$ gcc-7.2.0 -Os small.c; ./a.out
6
$ 
$ clangpolly -Os small.c; ./a.out
0
$ 

-------------------------------------

int printf (const char *, ...);

int a, b, c, g, *h = &a;
char d, e = -1;
static int f;

char fn1 (char j, int k)
{
  return j < 0 ? j : j >> k;
}

int fn2 (int j)
{
  return j;
}

int main ()
{
  long m = 249;
  while (c--)
    {
      if ((d < 1) & fn2 (2))
	f++;
      if (g)
	break;
      if (f)
	b = --m;
    }
  *h = fn1 (m, 6) ^ e;
  printf ("%d\n", a);
  return 0; 
}

**Comment by fhahn** [comment]
It looks like the miscompile was fixed before the Clang 7.0.0 release. It cannot be reproduced in any Clang version of Godbolt I tried: https://clang.godbolt.org/z/Kn7sYPh83

Please reopen with additional info if it still reproduces on your end.
