### ISSUE TITLE
Include comprehensive list of all LLDB settings

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35606]
|  |  |
| --- | --- |
| Bugzilla Link | [36258](https://llvm.org/bz36258) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @jimingham |

## Extended Description 
It would be great to see a full list of the settings for LLDB. Or, if it already exists, to make it easier to find.

**Comment by DavidSpickett** [comment]
Asked and answered, closing.

We could generate a web page for it but that's one more thing to forget about.
