### ISSUE TITLE
Merge r324486 into the 6.0 branch : AMDGPU: Remove the s_buffer workaround for GFX9 chips

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35626]
|  |  |
| --- | --- |
| Bugzilla Link | [36278](https://llvm.org/bz36278) |
| Version | 6.0 |
| OS | All |
| Blocks | llvm/llvm-project#35997  |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zmodem,@arsenm,@tstellar |
| Fixed by commit(s) | r324486 |

## Extended Description 
Is it OK to merge the following revision(s) to the 6.0 branch?

**Comment by arsenm** [comment]
Old release
