### ISSUE TITLE
error in backend: cannot move instruction since its users are not dominated by CoroBegin

### ISSUE THREAD

**Issue by 07db8777-e875-47a6-8e13-f3ee3e0342de** [llvm/llvm-project#35644]
|  |  |
| --- | --- |
| Bugzilla Link | [36296](https://llvm.org/bz36296) |
| Version | 5.0 |
| OS | Linux |
| Attachments | [Preprocessed source and associated run script](https://user-images.githubusercontent.com/92601457/143757015-8a293b70-a557-47a4-aa12-c93908c3b793.gz) |
| CC | @apolukhin,@lewissbaker,@modocache |

## Extended Description

**Comment by ChuanqiXu9** [comment]
Fixed in trunk: https://godbolt.org/z/xjrd16sdr.
