### ISSUE TITLE
variable template specialization accepted as class member name

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#35654]
|  |  |
| --- | --- |
| Bugzilla Link | [36306](https://llvm.org/bz36306) |
| Version | trunk |
| OS | All |

## Extended Description 
Example of incorrectly-accepted code:

template<int> int n;
struct X { int n<0>; };

This results in an anonymous FieldDecl.

Thanks to Jonathan Caves for reporting this!

**Comment by wheatman** [comment]
This was fixed between 14 and 15
https://godbolt.org/z/4nejoeqMe

code
```
template<int> int n;
struct X { int n<0>; };
```

new error
```
<source>:2:16: error: member 'n' cannot have template arguments
struct X { int n<0>; };
               ^~~~
1 error generated.
Compiler returned: 1
```
