### ISSUE TITLE
Merge r324593 into the 6.0 branch : [builtins] Workaround for infinite recursion in c?zdi2

### ISSUE THREAD

**Issue by JDevlieghere** [llvm/llvm-project#35666]
|  |  |
| --- | --- |
| Bugzilla Link | [36318](https://llvm.org/bz36318) |
| Version | 6.0 |
| OS | All |
| Blocks | llvm/llvm-project#35997  |
| CC | @zmodem,@jrtc27,@tstellar |
| Fixed by commit(s) | r324593 |

## Extended Description 
Is it OK to merge the following revision(s) to the 6.0 branch?

**Comment by arsenm** [comment]
Old release
