### ISSUE TITLE
constexpr variable must be initialized by a constant expression

### ISSUE THREAD

**Issue by 4f99a97d-37e2-4b4f-939b-3f5760df598b** [llvm/llvm-project#35697]
|  |  |
| --- | --- |
| Bugzilla Link | [36349](https://llvm.org/bz36349) |
| Version | 5.0 |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
This is a replication of https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78022

The following code used to compile with clang-4, but now with clang-5 shows the same behavior as it does with GCC:

template<typename T>
struct A
{
	template<typename... Args>
		constexpr A(Args&&...){}
};

struct B : public A<int>
{
	using A<int>::A;
};

// Uncommenting the following line makes this file compile.
//constexpr B p{0};
// Commenting the following line makes this file compile.
template<typename>
struct X
{
	X()
	{
		// The following line is fine.
		const B b0{0};
		// The following line produces an error.
		constexpr B b1{0};
	}
};

Maybe this is a dup of 36333.

**Comment by yuanfang-chen** [comment]
Compiles fine as of llvm14. https://godbolt.org/z/6x67js6fT
