### ISSUE TITLE
`.rtf` files from test suite cause svn failures on buildbot

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35706]
|  |  |
| --- | --- |
| Bugzilla Link | [36358](https://llvm.org/bz36358) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@lei137 |

## Extended Description 
I updated one of the powerpc64 lnt buildbot machines to a new OS release and the buildbot started failing every run when it tries to check out the test suite.

The checkout will run for a while then always fails like this:
```
/usr/bin/svn checkout --non-interactive --no-auth-cache --revision 323463 http://llvm.org/svn/llvm-project/test-suite/trunk@323463 test/test-suite
 in dir /home/buildbots/ppc64be-clang-lnt-test/clang-ppc64be-lnt (timeout 1200 secs)
...lots of files checked out...
svn: E000104: Error running context: Connection reset by peer
```

I tried checking out the test suite by hand on the same machine with the same results.  If I restart the checkout (or do an svn update) it will run a bit longer then fail.  Eventually I figured out that 3 files were causing the problem:
```
MultiSource/Applications/ClamAV/inputs/rtf-test/Doc1.rtf
MultiSource/Applications/ClamAV/inputs/rtf-test/docCLAMexe.rtf
MultiSource/Applications/ClamAV/inputs/rtf-test/rtf1.rtf
```

I tried on other powerpc64 machines (various distros and BE/LE) and it works on all of them UNLESS they are using the latest version of svn, version 1.9.7 (r1800392).  The latest svn version that works on a powerpc64 machine was 1.9.5.
It also will fail on a mac running svn 1.9.4.

svn 1.9.7 on a powerpc64 BE machine (or on the mac with svn 1.9.4) always eventually gives the "Connection reset by peer".  With svn 1.9.7 on a powerpc64 LE machine it eventually will hang.

Note that at least one of these files is flagged as suspicious by AV:

https://www.hybrid-analysis.com/sample/bba4eab51c27a6ffbd86bf870048da1902cc7235a4de49cf30208906dac50f85?environmentId=100

If I use https instead of http to check them out they succeed so we could update  the buildbot python to use https.  However, given the AV thing above that makes me nervous.

**Comment by Endilll** [comment]
I think SVN repo is not a thing anymore.
