### ISSUE TITLE
Weird MI '-break-disable' error message

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35713]
|  |  |
| --- | --- |
| Bugzilla Link | [36365](https://llvm.org/bz36365) |
| Version | 6.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
MI command '-break-disable' reports a weird error message for a non-existing breakpoint number. Example:

(gdb)
-break-disable 111
^error,msg="Command '0'. Breakpoint 'Command '%s'. Breakpoint '%s' invalid' invalid"

Probably it should look similar to '-break-delete' instead:

(gdb)
-break-delete 111
^error,msg="Command 'break-delete'. Breakpoint '111' invalid"

**Comment by DavidSpickett** [comment]
Assuming MI is machine interface, that is now out of tree (https://github.com/lldb-tools/lldb-mi).
