### ISSUE TITLE
Clang-format deletes whitespace between return-value attribute and return-value type

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35711]
|  |  |
| --- | --- |
| Bugzilla Link | [36363](https://llvm.org/bz36363) |
| Version | 5.0 |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
When I run clang-format on the file

```
  #include <string>

  __attribute__((warn_unused_result)) ::std::string foo() { return ""; }

  __attribute__((warn_unused_result)) std::string bar() { return ""; }
```

The output is

```
  #include <string>

  __attribute__((warn_unused_result))::std::string foo() { return ""; }

  __attribute__((warn_unused_result)) std::string bar() { return ""; }
```

In the foo function, clang-format deletes the space between the closing paren and the colon. Is this a bug in the formatter?

**Comment by mydeveloperday** [comment]
I think this could be resolved with a spaceBetweenRule 

i.e. `if (Left.is(TT_AttributeParen) && Right.is(tok::colon))` if necessary

**Comment by mkurdej** [comment]
Review: https://reviews.llvm.org/D117894.
