### ISSUE TITLE
[coroutines] lack of diagnostics about missing `promise_type::return_void` for lambda expression

### ISSUE THREAD

**Issue by 07db8777-e875-47a6-8e13-f3ee3e0342de** [llvm/llvm-project#35755]
|  |  |
| --- | --- |
| Bugzilla Link | [36407](https://llvm.org/bz36407) |
| Version | 6.0 |
| OS | Linux |

## Extended Description 
#include <experimental/coroutine>
#include <future>

namespace stdx = std::experimental;

template <typename R, typename... Args>
struct stdx::coroutine_traits<std::future<R>, Args...> {
  struct promise_type : std::promise<R> {
    auto get_return_object() { return this->get_future(); }
    stdx::suspend_never initial_suspend() { return {}; }
    stdx::suspend_never final_suspend()   { return {}; }
    void unhandled_exception() { this->set_exception(std::current_exception()); }
    template <typename U> void return_value(U &&u) {
      this->set_value(std::forward<U>(u));
    }
  };
};

std::future<void> func() {
    // valid warning here: 
    // "control reaches end of coroutine; which is undefined behavior because the promise type ...coroutine_traits<std::future<void>>::promise_type' does not declare 'return_void()' [-Wreturn-type]"

    co_await stdx::suspend_never {};
}

auto lambda = [] () -> std::future<void> {
    // invalid warning here:
    // "control reaches end of non-void lambda [-Wreturn-type]"
    co_await stdx::suspend_never {};
};

https://godbolt.org/g/nhy4xN

**Comment by ChuanqiXu9** [comment]
Fixed in trunk.
