### ISSUE TITLE
Several tests failed in `check-lit` project on Windows 10

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35791]
|  |  |
| --- | --- |
| Bugzilla Link | [36443](https://llvm.org/bz36443) |
| Version | trunk |
| OS | other |
| Attachments | [check-lit build output from Visual Studio](https://user-images.githubusercontent.com/60944935/143757087-0b6ccd3a-c1a5-4fdb-82a2-1100ad79401e.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

OS : Windows 10 64 bit

1. Download LLVM source and build Microsoft Visual Studio solution as per instructions in
   https://clang.llvm.org/get_started.html.
2. Open LLVM.sln with Microsoft  Visual Studio.
3. Build `check-lit` project.
4. Below mentioned tests failed.
```
Failing Tests (8):
    lit :: googletest-format.py
    lit :: max-failures.py
    lit :: selecting.py
    lit :: shtest-encoding.py
    lit :: shtest-format.py
    lit :: shtest-output-printing.py
    lit :: shtest-shell.py
    lit :: unittest-adaptor.py
```

**Comment by Endilll** [comment]
Python 2.7 is no longer supported. Feel free to reopen if it reproduces with a supported version of LLVM and a version of Python that satisfies our minimum requirements.
