### ISSUE TITLE
Wrong Output for AllowShortFunctionsOnASingleLine when ColumnLimit changes

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35805]
|  |  |
| --- | --- |
| Bugzilla Link | [36457](https://llvm.org/bz36457) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Formatting the file with the config below:
```cpp
class A{
#ifndef ASD
	A<bool>& GetMask() { return a; }
	const A<bool>& GetMask() const { return a; }
#endif
};
```
results in weird behavior when:
ColumnLimit: 0
is changed to
ColumnLimit: 500
which should not make any difference.

ColumnLimit: 0
```cpp
class A
{
#ifndef ASD
	A<bool>& GetMask()
	{
		return a;
	}
	const A<bool>& GetMask() const { return a; }
#endif
};
```

ColumnLimit: 500
```cpp
class A
{
#ifndef ASD
	A<bool>& GetMask() { return a; }
	const A<bool>& GetMask() const { return a; }
#endif
};
```

**Comment by rymiel** [comment]
The issue mentions a config, but one wasn't provided. It's likely to have been fixed by 06763ea5d8f96625545bb2c2445363aca9922bf1 anyway
