### ISSUE TITLE
Building of blender_r  using release_60 aborts if -fno-slp-vectorize is not specified

### ISSUE THREAD

**Issue by BalaRishi-AMD** [llvm/llvm-project#35800]
|  |  |
| --- | --- |
| Bugzilla Link | [36452](https://llvm.org/bz36452) |
| Version | 6.0 |
| OS | Linux |
| Attachments | [The config file for building blender_r benchmark with release_60 compiler.](https://user-images.githubusercontent.com/92601646/143757090-e36fab5e-20dd-4128-81b6-b70cd5e61eee.gz) |
| CC | @BalaRishi-AMD |

## Extended Description 

When used the latest release_60 branch to build 526.blender_r benchmark of CPU2017, it allocated >50 GB and then aborted with message "clang-6.0: error: unable to execute command: Killed".

This issue occurs for flagset: -m64 -O3 -flto
But, NOT occurs for flagset  : -m64 -O3 -flto  -fno-slp-vectorize

However, this issue is not seen with the latest trunk.

--
Attaching the config file for building the benchmark.

Command used to build:
runcpu --rebuild --noreportable -I --NoRatios --config cpu2017_llvm60-release.cfg --action=build --tune base 526.blender_r
---

**Comment by alexey-bataev** [comment]
Outdated, must be fixed already long time ago
