### ISSUE TITLE
llvm-mc on SPARC cannot parse TLS sequences

### ISSUE THREAD

**Issue by jrtc27** [llvm/llvm-project#35809]
|  |  |
| --- | --- |
| Bugzilla Link | [36461](https://llvm.org/bz36461) |
| Version | trunk |
| OS | All |
| Attachments | [Example](https://user-images.githubusercontent.com/816232/143757095-35b29f6c-0b6a-46fd-ab1e-4add417bcf74.gz), [Example](https://user-images.githubusercontent.com/816232/143757097-4e23dd68-43ce-47ab-9a7e-477195321d5b.gz) |

## Extended Description 

Whilst LLVM supports TLS on SPARC when using the integrated as or the system as, llvm-mc itself cannot parse the related code sequences, as it does not allow call, ld[x] and add instructions to have an extra parameter with relocation information as required; a test case is attached.

**Comment by rorth** [comment]
Works since LLVM 8.
