### ISSUE TITLE
misc-redundant-expression reports results in decltype expression

### ISSUE THREAD

**Issue by LegalizeAdulthood** [llvm/llvm-project#35857]
|  |  |
| --- | --- |
| Bugzilla Link | [36509](https://llvm.org/bz36509) |
| Version | unspecified |
| OS | All |
| CC | @BatmanAoD,@EugeneZelenko,@Xazax-hun |

## Extended Description 
The misc-redundant-expression check reports a warning for the following use of decltype:
```
int x;
int y;
decltype(x + y - (x + y)) z = 10;
```
It's unclear whether or not misc-redundant-expression should return results for expressions inside a decltype specifier.

**Comment by LegalizeAdulthood** [comment]
Still an issue in clang-tidy 14

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D157374
