### ISSUE TITLE
clang crashes on passing a coro param to operator new

### ISSUE THREAD

**Issue by andrewrk** [llvm/llvm-project#35869]
|  |  |
| --- | --- |
| Bugzilla Link | [36521](https://llvm.org/bz36521) |
| Version | 6.0 |
| OS | All |
| Blocks | llvm/llvm-project#35152 llvm/llvm-project#35997  |
| Attachments | [test.sh](https://user-images.githubusercontent.com/92601305/143757138-998cc71b-805c-4ea3-af8f-45a81869c1bd.gz) |
| CC | @zmodem,@modocache,@tstellar |
| Fixed by commit(s) | r325285 |

## Extended Description 

#include <experimental/coroutine>

struct Allocator {
    void *(*alloc)(unsigned long x);
    void (*free)(void *ptr);
};

struct ResumableThing {
    struct promise_type  {
        void *operator new(unsigned long size, Allocator *allocator) {
            return allocator->alloc(size);
        }
        auto initial_suspend() { return std::experimental::suspend_never{}; }
        auto final_suspend() { return std::experimental::suspend_never{}; }
        void return_void() {}
        ResumableThing get_return_object() {
            return ResumableThing(std::experimental::coroutine_handle<promise_type>::from_promise(*this));
        }
        auto unhandled_exception() { abort(); }
    };
    std::experimental::coroutine_handle<promise_type> m_coroutine = nullptr;
    ResumableThing() = default;
    ResumableThing(ResumableThing const &) = default;
    explicit ResumableThing(std::experimental::coroutine_handle<promise_type> coroutine) :
        m_coroutine(coroutine) {}
};

static char some_bytes[2000];
static void *global_alloc(unsigned long x) {
    return &some_bytes[0];
}
static void global_free(void *ptr) { }

static Allocator allocator = { global_alloc, global_free };

static ResumableThing foo(Allocator *a) {
    co_return;
}

void entry() {
    auto p = foo(&allocator);
}

$ ~/llvm6-release/bin/clang -c  -fcoroutines-ts test.cpp -stdlib=libc++ -std=c++1z
test.cpp:36:23: error: no matching function for call to 'operator new'
static ResumableThing foo(Allocator *a) {
                      ^
test.cpp:10:15: note: candidate function not viable: requires 2 arguments, but 1 was provided
        void *operator new(unsigned long size, Allocator *allocator) {
              ^
#&#8203;0 0x0000000001f7841a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/andy/llvm6-release/bin/clang-6.0+0x1f7841a)
#&#8203;1 0x0000000001f7656e llvm::sys::RunSignalHandlers() (/home/andy/llvm6-release/bin/clang-6.0+0x1f7656e)
#&#8203;2 0x0000000001f76692 SignalHandler(int) (/home/andy/llvm6-release/bin/clang-6.0+0x1f76692)
#&#8203;3 0x00007fb2fe531dd0 __restore_rt (/nix/store/z0b60y0khix9jb74ka56gw7b7n9s8awx-glibc-2.26-131/lib/libpthread.so.0+0x11dd0)
#&#8203;4 0x0000000002e7f527 clang::CoroutineStmtBuilder::makeNewAndDeleteExpr() (/home/andy/llvm6-release/bin/clang-6.0+0x2e7f527)
#&#8203;5 0x0000000002e803cc clang::CoroutineStmtBuilder::buildDependentStatements() (/home/andy/llvm6-release/bin/clang-6.0+0x2e803cc)
#&#8203;6 0x0000000002e80416 clang::CoroutineStmtBuilder::buildStatements() (/home/andy/llvm6-release/bin/clang-6.0+0x2e80416)
#&#8203;7 0x0000000002e80780 clang::Sema::CheckCompletedCoroutineBody(clang::FunctionDecl*, clang::Stmt*&) (/home/andy/llvm6-release/bin/clang-6.0+0x2e80780)
#&#8203;8 0x0000000002ea34ae clang::Sema::ActOnFinishFunctionBody(clang::Decl*, clang::Stmt*, bool) (/home/andy/llvm6-release/bin/clang-6.0+0x2ea34ae)
#&#8203;9 0x0000000002c5e0a4 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/home/andy/llvm6-release/bin/clang-6.0+0x2c5e0a4)
#&#8203;10 0x0000000002bced0b clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/home/andy/llvm6-release/bin/clang-6.0+0x2bced0b)
#&#8203;11 0x0000000002bf0053 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/home/andy/llvm6-release/bin/clang-6.0+0x2bf0053)
#&#8203;12 0x0000000002bc9270 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/home/andy/llvm6-release/bin/clang-6.0+0x2bc9270)
#&#8203;13 0x0000000002bc99d1 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) [clone .part.160] (/home/andy/llvm6-release/bin/clang-6.0+0x2bc99d1)
#&#8203;14 0x0000000002bc99ff clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/home/andy/llvm6-release/bin/clang-6.0+0x2bc99ff)
#&#8203;15 0x0000000002bd0e34 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/home/andy/llvm6-release/bin/clang-6.0+0x2bd0e34)
#&#8203;16 0x0000000002bd18be clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/home/andy/llvm6-release/bin/clang-6.0+0x2bd18be)
#&#8203;17 0x0000000002bc5d0b clang::ParseAST(clang::Sema&, bool, bool) (/home/andy/llvm6-release/bin/clang-6.0+0x2bc5d0b)
#&#8203;18 0x000000000280f961 clang::CodeGenAction::ExecuteAction() (/home/andy/llvm6-release/bin/clang-6.0+0x280f961)
#&#8203;19 0x00000000024e8fb6 clang::FrontendAction::Execute() (/home/andy/llvm6-release/bin/clang-6.0+0x24e8fb6)
#&#8203;20 0x00000000024b2a56 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/andy/llvm6-release/bin/clang-6.0+0x24b2a56)
#&#8203;21 0x000000000257a20b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/andy/llvm6-release/bin/clang-6.0+0x257a20b)
#&#8203;22 0x0000000000a53358 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/andy/llvm6-release/bin/clang-6.0+0xa53358)
#&#8203;23 0x00000000009ca7f0 main (/home/andy/llvm6-release/bin/clang-6.0+0x9ca7f0)
#&#8203;24 0x00007fb2fd28c020 __libc_start_main (/nix/store/z0b60y0khix9jb74ka56gw7b7n9s8awx-glibc-2.26-131/lib/libc.so.6+0x21020)
#&#8203;25 0x0000000000a50a8a _start /build/glibc-2.26/csu/../sysdeps/x86_64/start.S:122:0
Stack dump:
0.	Program arguments: /home/andy/llvm6-release/bin/clang-6.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /home/andy/tmp/test.gcno -resource-dir /home/andy/llvm6-release/lib/clang/6.0.0 -I /nix/store/aficfjm81yiklfygq03y87vp5k8h28mr-glibc-2.26-131-dev/include -internal-isystem /home/andy/llvm6-release/bin/../include/c++/v1 -internal-isystem /usr/local/include -internal-isystem /home/andy/llvm6-release/lib/clang/6.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++1z -fdeprecated-macro -fdebug-compilation-dir /home/andy/tmp -ferror-limit 19 -fmessage-length 107 -fcoroutines-ts -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o test.o -x c++ test.cpp 
1.	test.cpp:40:1: current parser token 'void'
2.	test.cpp:36:41: parsing function body 'foo'
clang-6.0: error: unable to execute command: Segmentation fault (core dumped)
clang-6.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0 (branches/release_60 324533) (llvm/branches/release_60 324525)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/andy/llvm6-release/bin
clang-6.0: note: diagnostic msg: PLEASE submit a bug report to  and include the crash backtrace, preprocessed source, and associated run script.
clang-6.0: note: diagnostic msg:

**Comment by Endilll** [comment]
Appears to be fixed in Clang 7: https://godbolt.org/z/8ezEhjdnM
