### ISSUE TITLE
clang-format -dump-config produces file with trailing whitespace

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35897]
|  |  |
| --- | --- |
| Bugzilla Link | [36549](https://llvm.org/bz36549) |
| Version | trunk |
| OS | Linux |
| Attachments | [.clang-format input](https://user-images.githubusercontent.com/60944935/143757146-88477c33-b542-457c-8bcb-842d71c67dce.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

clang-format -style=file -dump-config > clang-format-3

with attached file it produces trailing whitespace on BraceWrapping parameter.

**Comment by mydeveloperday** [comment]
In clang-format v8

![image](https://user-images.githubusercontent.com/16046346/145854811-d9449408-aed0-4f74-b263-4f6d4177bf4e.png)

in clang-format v12 this seems to be resolved

![image](https://user-images.githubusercontent.com/16046346/145854860-1da027e5-a941-4909-b5e7-5fa6b3a42a1c.png)

I am closing this issue, please reopen if you think it is still an issue
