### ISSUE TITLE
[linux vs macos] fails to inline sqrt

### ISSUE THREAD

**Issue by nlewycky** [llvm/llvm-project#3591]
|  |  |
| --- | --- |
| Bugzilla Link | [3219](https://llvm.org/bz3219) |
| Version | trunk |
| OS | Linux |
| CC | @asl,@lattner,@emaste,@jryans |

## Extended Description 
On this program:

  #include <math.h>
  double foo(double X) { return sqrt(X); }

GCC will inline the fast path (non-negative X) and produce this:

foo:
        pushl   %ebp
        movl    %esp, %ebp
        subl    $8, %esp
        fldl    8(%ebp)
        fld     %st(0)
        fsqrt
        fucomi  %st(0), %st
        jp      .L7
        je      .L8
        fstp    %st(0)
        jmp     .L5
.L7:
        fstp    %st(0)
        .p2align 4,,7
        .p2align 3
.L5:
        fstpl   (%esp)
        .p2align 4,,5
        .p2align 3
        call    sqrt
        .p2align 4,,2
        .p2align 3
        jmp     .L2
        .p2align 4,,7
        .p2align 3
.L8:
        fstp    %st(1)
.L2:
        leave
        .p2align 4,,1
        .p2align 3
        ret

**Comment by gwelymernans** [comment]
This looks to be resolved?

```
$ clang pr.c -o - -S -O3 -fmath-errno -fomit-frame-pointer -fno-optimize-sibling-calls
	.text
	.file	"pr.c"
	.globl	foo                             # -- Begin function foo
	.p2align	4, 0x90
	.type	foo,@function
foo:                                    # @foo
	.cfi_startproc
# %bb.0:
	xorpd	%xmm1, %xmm1
	ucomisd	%xmm1, %xmm0
	jb	.LBB0_2
# %bb.1:
	sqrtsd	%xmm0, %xmm0
	retq
.LBB0_2:
	pushq	%rax
	.cfi_def_cfa_offset 16
	callq	sqrt
	addq	$8, %rsp
	.cfi_def_cfa_offset 8
	retq
.Lfunc_end0:
	.size	foo, .Lfunc_end0-foo
	.cfi_endproc
                                        # -- End function
	.ident	"Debian clang version 13.0.1-+rc1-1~exp4"
	.section	".note.GNU-stack","",@progbits
	.addrsig

$ gcc pr.c -o - -S -O3 -fmath-errno -fomit-frame-pointer -fno-optimize-sibling-calls
	.file	"pr.c"
	.text
	.p2align 4
	.globl	foo
	.type	foo, @function
foo:
.LFB0:
	.cfi_startproc
	pxor	%xmm1, %xmm1
	ucomisd	%xmm0, %xmm1
	ja	.L6
	sqrtsd	%xmm0, %xmm0
	ret
.L6:
	pushq	%rax
	.cfi_def_cfa_offset 16
	call	sqrt@PLT
	popq	%rdx
	.cfi_def_cfa_offset 8
	ret
	.cfi_endproc
.LFE0:
	.size	foo, .-foo
	.ident	"GCC: (Debian 11.2.0-14) 11.2.0"
	.section	.note.GNU-stack,"",@progbits
```

**Comment by rotateright** [comment]
I can't tell exactly what the problem was from the description, but yes, this seems fixed 13+ years later. :)
Note that there are still missing optimizations for sqrt even with today's optimizer/codegen such as #52620.
