### ISSUE TITLE
[Coroutines] mem2reg causes "cannot move instruction since its users are not dominated by CoroBegin"

### ISSUE THREAD

**Issue by andrewrk** [llvm/llvm-project#35926]
|  |  |
| --- | --- |
| Bugzilla Link | [36578](https://llvm.org/bz36578) |
| Version | trunk |
| OS | All |
| Attachments | [repro.ll](https://user-images.githubusercontent.com/92601305/143757158-4e2f1721-654a-4cf1-ad95-220a2851c35a.gz) |
| CC | @avikivity,@modocache,@yuanfang-chen |

## Extended Description 

In my frontend, I'm careful to store args that are referenced in the Cleanup block into the coro frame, to avoid tripping "cannot move instruction since its users are not dominated by CoroBegin":

define internal fastcc i8* @&#8203;amain(%Allocator*, i16*) unnamed_addr #&#8203;0 !dbg !&#8203;234 {
  store %Allocator* %0, %Allocator** %_anon3, align 8, !dbg !&#8203;248

then later in the cleanup block:

  %28 = load %Allocator*, %Allocator** %_anon3, align 8, !dbg !&#8203;248
  %29 = getelementptr inbounds %Allocator, %Allocator* %28, i32 0, i32 2, !dbg !&#8203;248
  %30 = load void (%Allocator*, %"[]u8"*)*, void (%Allocator*, %"[]u8"*)** %29, align 8, !dbg !&#8203;248
  %31 = call i8* @&#8203;llvm.coro.free(token %6, i8* %12), !dbg !&#8203;248

This works at -O0. But when mem2reg runs it replaces the load from _anon3 to %0 directly:

  call fastcc void %31(%Allocator* nonnull %0, %"[]u8"* byval nonnull %2) #&#8203;6, !dbg !&#8203;191

This trips the corosplit assertion.

**Comment by adrianimboden** [comment]
at least this (https://github.com/llvm/llvm-project/issues/35926#issuecomment-980994157) seems to be fixed: https://godbolt.org/z/P65fxa7sM

**Comment by ChuanqiXu9** [comment]
No exist in trunk.
