### ISSUE TITLE
core dump while compiling CobaltFusion using clang-power-tools (syntax only)

### ISSUE THREAD

**Issue by df41ed61-9954-4cdf-bafd-b1d4df4e5ab4** [llvm/llvm-project#35949]
|  |  |
| --- | --- |
| Bugzilla Link | [36601](https://llvm.org/bz36601) |
| Version | 5.0 |
| OS | other |

## Extended Description 
core dump while compiling 
https://github.com/CobaltFusion/DebugViewPP/tree/master/CobaltFusion using clang-power-tools (syntax only)

Start Clang Compile

PROJECT: D:\project\DebugViewPP\CobaltFusion\CobaltFusion.vcxproj
clang++.exe: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
Wrote crash dump file "C:\CrashDumps\\clang++.exe.ce8030.dmp"
0x00007FF79C92AD15 (0x000000377E860AA0 0x00007FF700000000 0x000000377E860AB0 0x0000000000000003)
0x00007FF79C94337A (0x000000377BB6DC90 0x000000377BC7F460 0x0000000000000000 0x00007FF79C81636B)
0x00007FF79C940541 (0x000000377BC7F450 0x0000000000000000 0x000000377BC7A7D0 0x0000000000000001)
0x00007FF79C90C719 (0x000000377BB6DD30 0x0000000000000000 0x000000377BC7F450 0x0000000000000000)
0x00007FF79C297CCC (0x000000377BD30E60 0x000000377BBB0358 0x000000377BD30CC0 0x00007FFE00000005)
0x00007FF79C8129C2 (0x0000000000000000 0x0000000000000000 0x000000377BB6E018 0x000000377BBC7B80)
0x00007FF79C27FDDA (0x00007FFDCFFE7088 0x00007FF79BD50100 0x0000003700000002 0x00007FF700000002)
0x00007FF79C24B460 (0x000000377BB6E018 0x00007FF79C24601B 0x000000377BBF4960 0x0000000000000033)
0x00007FF79C2C027C (0x000000007BBB0101 0x0000000000000071 0x0000000000000078 0x000000817BBB02FC)
0x00007FF79ABA5E6B (0x0000000000000067 0x000000377BBB0300 0x0000000000000089 0x0000000100000080)
0x00007FF79ABA4293 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF79D522D81 (0x00007FF79D522DDC 0x00007FF79AA65000 0x0000000000000000 0x0000000000000000)
0x00007FFE0CE113D2 (0x00007FFE0CE113B0 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x22 bytes(s)
0x00007FFE0F3E54F4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x34 bytes(s)
clang++.exe: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 5.0.1 (tags/RELEASE_501/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
clang++.exe: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang++.exe: note: diagnostic msg: Error generating preprocessed source(s).
Errors encountered during PCH creation

Done Clang Compile

**Comment by Endilll** [comment]
@janwilmans Can you provide what was mentioned in crash log? `include the crash backtrace, preprocessed source, and associated run script.`

**Comment by Endilll** [comment]
Author hasn't got back to us with a reproducer.
