### ISSUE TITLE
clang emits extraneous -Wunused-variable for RAII const reference variable

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35975]
|  |  |
| --- | --- |
| Bugzilla Link | [36627](https://llvm.org/bz36627) |
| Version | 5.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie |

## Extended Description 
Consider

    struct S {
        S();
        ~S();  // Assume this actually does some RAII cleanup.
    };

    extern int f();

    int main() {
        auto const t = S();  // No warning.
        auto const& u = S();  // "warning: unused variable 'u' [-Wunused-variable]".
        f();  // Just so that clang has no way to know whether some work will be done here.
    }

and compile (e.g.) with `--std=c++17 -Wall -Wextra -Wpedantic`

clang (5.0.1 Arch Linux package) correctly recognizes that `t` could be involved in RAII, but emits an unused-variable warning about `u` even though it can also participate in RAII in the same way (as the lifetime of the const reference is prolonged until the end of the scope).  [Note that it would be a different issue if clang neither recognized the possibility of RAII happening for either `t` or `u`.]

**Comment by AaronBallman** [comment]
This issue was resolved in Clang 15.0.0: https://godbolt.org/z/hMd6K7jex
