### ISSUE TITLE
ICE when target-feature flag passed to clang

### ISSUE THREAD

**Issue by hiraditya** [llvm/llvm-project#35985]
|  |  |
| --- | --- |
| Bugzilla Link | [36637](https://llvm.org/bz36637) |
| Version | unspecified |
| OS | All |
| CC | @hiraditya |

## Extended Description 
If you pass a flag which is unknown to the compiler. it crashes.

clang -O3 a.c -S -o a.s  -arch arm64 -Xclang -target-feature -Xclang -asdfasdf

**Comment by Endilll** [comment]
Can't reproduce using Clang 4 through 7 with assertion enabled.

**Comment by hiraditya** [comment]
verified that it works for me.
```
$ clang -O3 a.c -S -o a.s -arch arm64 -Xclang -target-feature -Xclang -asdfasdf
clang: warning: argument unused during compilation: '-arch arm64' [-Wunused-command-line-argument]
'-asdfasdf' is not a recognized feature for this target (ignoring feature)
```
