### ISSUE TITLE
Crash compiling template code with using-aliasing

### ISSUE THREAD

**Issue by JacobALundgren** [llvm/llvm-project#35995]
|  |  |
| --- | --- |
| Bugzilla Link | [36647](https://llvm.org/bz36647) |
| Version | 5.0 |
| OS | Linux |
| Attachments | [Backtrace, reproducing preprocessed source and compilation script](https://user-images.githubusercontent.com/92601812/143757204-4a67b703-11ee-41e8-b4e8-df389249cdbb.gz) |
| CC | @JacobALundgren |

## Extended Description 

Crash attempting to compile a piece of valid C++ code containing a template struct with a nested template struct. A using-statement is used for the outer template when explicitly specializing the inner template for a specific specialization of the outer template. Of note is that replacing the using-statement with an equivalent typedef means that compilation succeeds.

Steps to reproduce:
1. Compile the attached preprocessed source using the attached command

Actual results:
clang++ crashes

Expected results:
Compilation proceeds and succeeds

Hardware:
Arch Linux 4.15.7-1-ARCH

**Comment by AaronBallman** [comment]
This issue was resolved in Clang 7.0.0: https://godbolt.org/z/vh6bPG9vb
