### ISSUE TITLE
Ubuntu repository broken

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36007]
|  |  |
| --- | --- |
| Bugzilla Link | [36659](https://llvm.org/bz36659) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@tycho |

## Extended Description 
I just added deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main to my sources list and added also the  wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - but after apt update I get the following error message:

E: Failed to fetch http://apt.llvm.org/xenial/dists/llvm-toolchain-xenial/main/binary-amd64/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

Once I got the apt-get updated (for some reason it works sometimes) I got the warning:

W: The repository 'http://apt.llvm.org/xenial llvm-toolchain-xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Trying to install clang-format-7 after this gives warning:

WARNING: The following packages cannot be authenticated!
  libllvm7 clang-format-7
Install these packages without verification? [y/N] 

Answering yes outputs the following:

Err:1 http://apt.llvm.org/xenial llvm-toolchain-xenial/main amd64 libllvm7 amd64 1:7~svn325738-1~exp1
  404  Not Found
Err:2 http://apt.llvm.org/xenial llvm-toolchain-xenial/main amd64 clang-format-7 amd64 1:7~svn325738-1~exp1
  404  Not Found
E: Failed to fetch http://apt.llvm.org/xenial/pool/main/l/llvm-toolchain-snapshot/libllvm7_7~svn325738-1~exp1_amd64.deb  404  Not Found

E: Failed to fetch http://apt.llvm.org/xenial/pool/main/l/llvm-toolchain-snapshot/clang-format-7_7~svn325738-1~exp1_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Does not work with update or fix-missing.

**Comment by MarcoFalke** [comment]
> Late last evening the repository started to work again.

Closing for now, as per previous comment. Feel free to reopen if this still exists.
