### ISSUE TITLE
[AMDGPU] *** Couldn't join subrange! whne compiling kernel that use 3 element vectors

### ISSUE THREAD

**Issue by jvesely** [llvm/llvm-project#36027]
|  |  |
| --- | --- |
| Bugzilla Link | [36679](https://llvm.org/bz36679) |
| Version | 6.0 |
| OS | Linux |
| Attachments | [lgamma_r.link-1.ll](https://user-images.githubusercontent.com/5942874/143757210-97647254-a939-42a9-87e8-72127c756a80.gz), [lgamma_r.cl](https://user-images.githubusercontent.com/5942874/143757211-8369e485-1816-49b3-bf69-5c162bf23369.gz), [lgamma_r_5.ll](https://user-images.githubusercontent.com/5942874/143757212-a709f86f-0c04-41f8-beaf-8d8eac8726bb.gz), [lgamma_r_7.ll](https://user-images.githubusercontent.com/5942874/143757213-40c57d2d-7c8b-4a64-a4ac-ffe712708934.gz) |
| CC | @arsenm |

## Extended Description 

(CARRIZO / DRM 3.23.0 / 4.15.6-300.fc27.x86_64, LLVM 6.0.0)

Running OpenCL CTS:
./conformance_bruteforce lgamma_r -3
results in:
*** Couldn't join subrange!

UNREACHABLE executed at /home/jvesely/llvm/lib/CodeGen/RegisterCoalescer.cpp:2916!

Note that other vector widths do not crash.
Linked .ll file is attached. The crash can be reproduced running:

llc -march=amdgcn -mcpu=carrizo < lgamma_r.link-1.ll

**Comment by arsenm** [comment]
Compiles successfully now
