### ISSUE TITLE
Clang crashes when compiling fuzzing tests for chromium.

### ISSUE THREAD

**Issue by e0e1e613-dccb-47a5-85db-3dc989429265** [llvm/llvm-project#36057]
|  |  |
| --- | --- |
| Bugzilla Link | [36709](https://llvm.org/bz36709) |
| Version | 5.0 |
| OS | All |

## Extended Description 
1.	<eof> parser at end of file
2.	../../base/files/file_path_watcher_fsevents.cc:19:11: LLVM IR generation of declaration 'base'
3.	../../base/files/file_path_watcher_fsevents.cc:83:31: Generating code for declaration 'base::FilePathWatcherFSEvents::Watch'
clang++: error: unable to execute command: Abort trap: 6

clang++: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 7.0.0 (trunk 324578)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: ../../third_party/llvm-build/Release+Asserts/bin
clang++: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /var/folders/jc/p2xykjrx59dcts65x1wm00q85krbqt/T/file_path_watcher_fsevents-959136.cpp
clang++: note: diagnostic msg: /var/folders/jc/p2xykjrx59dcts65x1wm00q85krbqt/T/file_path_watcher_fsevents-959136.sh
clang++: note: diagnostic msg: Crash backtrace is located in
clang++: note: diagnostic msg: /Users/dyaroshev/Library/Logs/DiagnosticReports/clang++_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang++: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang++: note: diagnostic msg: 

********************
[22/254] OBJCXX obj/base/base/authorization_util.o

**Comment by AaronBallman** [comment]
Without a reproducer, there's not much that can be done, so closing this issue.
