### ISSUE TITLE
clang-format-6.0 ignores AlignConsecutiveDeclarations and AlignConsecutiveAssignments for section of code

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36070]
|  |  |
| --- | --- |
| Bugzilla Link | [36722](https://llvm.org/bz36722) |
| Version | 6.0 |
| OS | Linux |
| Attachments | [Original file](https://user-images.githubusercontent.com/60944935/143757236-47466a2d-90f6-4433-9a08-876121855fd8.gz), [Formatted file](https://user-images.githubusercontent.com/60944935/143757237-3a2c0766-e69a-4887-bec6-ffe09db40ff5.gz), [.clang-format file](https://user-images.githubusercontent.com/60944935/143757238-a4d9921f-af93-4ed1-817c-84270d1ea869.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

The attached file "bson.c", when processed with the attached clang-format file ".clang-format", produces the following diff (also attached):

```
--- bson.c	2018-03-14 11:24:38.895642438 +0000
+++ bson.c.formatted	2018-03-14 11:24:49.051771534 +0000
@@ -29,13 +29,13 @@
 #else
 	{
 		HashPosition pos;
-		zval**       property;
+		zval** property;
 
 		for (i = 0; i < 10; i++) {
-			char*                         string_key     = NULL;
-			uint                          string_key_len = 0;
-			ulong                         num_key        = 0;
-			zend_class_entry*             map_ce         = NULL;
+			char* string_key = NULL;
+			uint string_key_len = 0;
+			ulong num_key = 0;
+			zend_class_entry* map_ce = NULL;
 			php_phongo_bson_typemap_types map_type;
 		}
 	}
```

This only seems to happen due to some interaction with the code in the php_phongo_bson_visit_binary function, and only for the #else block. If I remove the surrounding { .. }, it works as expected. This is of course a trimmed down version of the function.

**Comment by HazardyKnusperkeks** [comment]
https://reviews.llvm.org/D134042
