### ISSUE TITLE
Debug info for variadic templates

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#36093]
|  |  |
| --- | --- |
| Bugzilla Link | [36745](https://llvm.org/bz36745) |
| Version | trunk |
| OS | All |
| CC | @adrian-prantl,@dwblaikie,@DougGregor,@pogo59 |

## Extended Description 
```
template<typename T>
T accumulator(T v) {
  return v;
}

template<typename T, typename... Args>
T accumulator(T first, Args... args) {
  return first + accumulator(args...);
}

int main()
{
long sum = accumulator(1, 3, 5, 7);
return sum;
}
```

The testcase is given above. This testcase is an example for variadic templates. The debug info generated for this testcase by clang seems to be incorrect. The accumulator is passed the values (1,3,5,7). All the non-first elements are shown with value 7 at the breakpoint. Ideally they should be first=1, args=3, args=5, args=7

Breakpoint 2, accumulator<int, int, int, int> (first=1, args=7, args=7, args=7) at simple_var.cpp:8
8         return first + accumulator(args...);

**Comment by dwblaikie** [comment]
Duplicate of #24643
