### ISSUE TITLE
incorrect diagnostic  illegal initializer type with _Atomic static initialization

### ISSUE THREAD

**Issue by mibintc** [llvm/llvm-project#36105]
|  |  |
| --- | --- |
| Bugzilla Link | [36757](https://llvm.org/bz36757) |
| Version | 6.0 |
| OS | MacOS X |
| CC | @DougGregor |

## Extended Description 
This is similar to llvm/llvm-project#28814 ,  but slightly different. It is cut down from OpenAL. We are compiling this application using gcc7 headers.

Here is the reduced test case,

typedef _Atomic struct { _Bool __val; } atomic_flag;

static atomic_flag LoadedHrtfLock = { 0 };

 /usr/bin/clang -c test.c
test.c:3:37: error: illegal initializer type 'atomic_flag' (aka '_Atomic(struct
      (anonymous struct at test.c:1:17))')
static atomic_flag LoadedHrtfLock = { 0 } ;
                                    ^
1 error generated.

$ /usr/bin/clang -v
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix 

--Melanie Blower, I work for Intel on the Intel c++ compiler

**Comment by AaronBallman** [comment]
This is a duplicate of #28814
