### ISSUE TITLE
clang doesn't to warn about return of reference to temporary when pointers to members are used

### ISSUE THREAD

**Issue by 63d01291-11af-4615-bc70-9d7c3aff8116** [llvm/llvm-project#36117]
|  |  |
| --- | --- |
| Bugzilla Link | [36769](https://llvm.org/bz36769) |
| Version | unspecified |
| OS | Linux |
| Attachments | [test case: no warning on returning reference to temp via pointer-to-member](https://user-images.githubusercontent.com/92601756/143757255-f6534c2f-9843-4947-b5d9-5b894e459e8a.gz) |

## Extended Description 

Expected: Warning about return of reference to temporary

Observed: No warning

Test case (also attached):

////////////////////////////////////////
struct Derp { int b = 66; };

int & memba(Derp obj,int Derp::*mem) {
    return obj.*mem; // <-- would normally warn here if we weren't using reference to member
}

int main() {
    Derp d;
    return memba(d, &Derp::b);
}
///////////////////////////////////////

There might be a technical reason this cannot be detected, but using pointers to data member seem to prevent clang from warning about returning a reference to a temporary.

On the face of it since the value of a pointer to member is not known until runtime it would seem impossible to warn about what it refers to, but AFAIK, since pointers to members cannot refer to references, we can deduce that returning a reference to *any* member of temporary would in turn be returning a reference to a temporary.

Tested in:

3.7, 3.8, 3.9, 4.0, 5.0, 6.0, 7.x (trunk 2018-03-15)

    clang++ -Wall -Wpedantic --std=c++11 warningtestcase.cpp

**Comment by AaronBallman** [comment]
This issue was resolved in Clang 7.0.0: https://godbolt.org/z/E8dG8rr7a
