### ISSUE TITLE
Require full context in diffs.

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#36136]
|  |  |
| --- | --- |
| Bugzilla Link | [36788](https://llvm.org/bz36788) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
Would it be possible to somehow configure phabricator (reviews.llvm.org) to reject the diffs that are not with the full context (`-U99999`)?
It's not really useful to always start by telling to upload such diffs...

**Comment by RKSimon** [comment]
We no longer use phabricator
