### ISSUE TITLE
crash in generated executable relating to shared_ptr rvalues and objc properties

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36207]
|  |  |
| --- | --- |
| Bugzilla Link | [36859](https://llvm.org/bz36859) |
| Version | 6.0 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dexonsmith,@vsapsai |

## Extended Description 
this project is a demo of a bug I see in our projects. the code crashes in  applicationDidFinishLaunching: on line 26.

The code runs correctly if -std=gnu++14 is specified but crashes if -std=gnu++1z or -std=gnu++17 is specified. '

I see the same behavior when building with clang+llvm-6.0.0-x86_64-apple-darwin downloaded from the clang website.

xcode version:  Version 9.3 beta 4 (9Q127n)

$ clang --version
Apple LLVM version 9.1.0 (clang-902.0.37.1)
Target: x86_64-apple-darwin17.4.0

from what I can see, if I store the result of [[cTest alloc] initSPtr] in a stack variable, the code does not crash. it is specifically the act of passing the result directly to setInstance that is causing the problem.

**Comment by Endilll** [comment]
Reproducer is no longer available.
