### ISSUE TITLE
Executable area not filled with traps

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36201]
|  |  |
| --- | --- |
| Bugzilla Link | [36853](https://llvm.org/bz36853) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @nga888,@emaste |

## Extended Description 
Given

        nop

        .section .foo,"ax"
        .align 16
        nop

We produce

90 cc cc cc cc cc cc cc  cc cc cc cc cc cc cc cc

When 90 is the nop in .text and cc are the traps.

But if we add ".zero 0x1000" to the end of the file, lld will produce

90 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00

**Comment by MaskRay** [comment]
Fixed.

That said, I actually want to get rid of this security theatre. It doesn't really help anything https://isopenbsdsecu.re/mitigations/trapsled/
