### ISSUE TITLE
[possible regression] Simple complex numbers expression fails

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#36263]
|  |  |
| --- | --- |
| Bugzilla Link | [36915](https://llvm.org/bz36915) |
| Version | unspecified |
| OS | FreeBSD |
| Blocks | llvm/llvm-project#35997  |
| Attachments | [testcase.cpp](https://user-images.githubusercontent.com/95090477/143757312-40a4458e-eccb-45d7-a6db-57a4db9e284d.gz) |
| CC | @DougGregor,@zmodem,@kamleshbhalui,@mclow,@zygoloid |

## Extended Description 

The attached testcase worked in clang4 and clang5 fine, but it breaks in clang6:

c.cpp:9:32: error: implicit conversion from '_Complex int' to 'double' is not permitted in C++
  complex_t p = cos (omega) +  _I * sin (omega);
                               ^~
c.cpp:6:25: note: expanded from macro '_I'
#define _I ((complex_t)(1i))
            ~           ^~

Found this on FreeBSD 12 in one port.

**Comment by philnik777** [comment]
This doesn't seem to be requested a lot, and I don't think we want to support this as an extension since it would encourage using them, which we normally avoid.
