### ISSUE TITLE
wrong code with opt "-memcpyopt -gvn"

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#36288]
|  |  |
| --- | --- |
| Bugzilla Link | [36940](https://llvm.org/bz36940) |
| Version | trunk |
| OS | All |
| CC | @efriedma-quic |

## Extended Description 
$ clangpolly -v
clang version 7.0.0 (http://llvm.org/git/clang.git 9a41408814f37f4f864fb3e57aa01919b4d871d8) (llvm/trunk 328613)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.2.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clangpolly -O0 small.c; ./a.out
$ 
$ clangpolly -O3 -mllvm -disable-llvm-optzns -c -emit-llvm -o small.bc small.c
$ optpolly -memcpyopt -gvn -o small-opt.bc small.bc
$ clangpolly small-opt.bc
$ ./a.out
Floating point exception (core dumped)
$ 

---------------------------------

int a, b, c, d, e, f = 1, g;

int main ()
{
  b = 1;
  while (1)
    {
      if (e > d)
	break;
      while (1)
	{
	  int h = f % b;
	  h = b;
	  b = a;
	  if (f)
	    ;
	  b = h;
	L:
	  g = b;
	  b = ~b;
	  e = f ^ g ^ ~d;
	  if (!b)
	    break;
	  b = ~c;
	}
    }
  return 0; 
}

**Comment by fhahn** [comment]
I am unable to reproduce this in current `main` and it has likely been fixed. MemCpyOpt doesn't use MemoryDependenceAnalysis any longer.

Please re-open the issue with additional info if it still reproduces on your end.
