### ISSUE TITLE
wrong code with opt "-early-cse-memssa -instcombine -loop-rotate -loop-unroll -memcpyopt -gvn"

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#36291]
|  |  |
| --- | --- |
| Bugzilla Link | [36943](https://llvm.org/bz36943) |
| Version | trunk |
| OS | All |

## Extended Description 
$ clangpolly -v
clang version 7.0.0 (http://llvm.org/git/clang.git 9a41408814f37f4f864fb3e57aa01919b4d871d8) (llvm/trunk 328613)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.2.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clangpolly -O0 small.c; ./a.out
1
$ 
$ clangpolly -O3 -mllvm -disable-llvm-optzns -c -emit-llvm -o small.bc small.c
$ optpolly -early-cse-memssa -instcombine -loop-rotate -loop-unroll -memcpyopt -gvn -o small-opt.bc small.bc
$ clangpolly small-opt.bc
$ ./a.out
0
$ 

----------------------------------

int printf (const char *, ...);

int a, b, c, d;

int main ()
{
  for (; b < 6; b++)
    {
      for (c = 8; c; c--)
	d = 1;
      a = d;
    }
  printf ("%d\n", a);
  return 0;
}

**Comment by fhahn** [comment]
The last bad version is LLVM 12.0.1: https://clang.godbolt.org/z/1q9q8W7Tj

This looks fixed in 13.0: https://clang.godbolt.org/z/rWv9o9Y6x

The likely fix was switching MemCpyOpt to use MemorySSA, which happened in 13.0.
