### ISSUE TITLE
wrong code with opt "-inline -instcombine -simplifycfg -loop-rotate -licm -lcssa -loop-unroll -mem2reg -sccp"

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#36290]
|  |  |
| --- | --- |
| Bugzilla Link | [36942](https://llvm.org/bz36942) |
| Version | trunk |
| OS | All |
| CC | @efriedma-quic |

## Extended Description 
$ clangpolly -v
clang version 7.0.0 (http://llvm.org/git/clang.git 9a41408814f37f4f864fb3e57aa01919b4d871d8) (llvm/trunk 328613)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.2.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clangpolly -O0 small.c; ./a.out
0
$ 
$ clangpolly -O3 -mllvm -disable-llvm-optzns -c -emit-llvm -o small.bc small.c
$ optpolly -inline -instcombine -simplifycfg -loop-rotate -licm -lcssa -loop-unroll -mem2reg -sccp -o small-opt.bc small.bc
$ clangpolly small-opt.bc
$ ./a.out
-1
$ 

-------------------------------------

int printf (const char *, ...);

int a, b, c, d, e, f;

char g (int h, int i)
{
  return i > 1 ? h : h >> i;
}

void j ()
{
  for (; b < 1; b++)
    {
      int k = 54;
      for (e = 0; e < 7; e++)
	for (; a < 2; a++)
	  ;
      for (d = 0; d < 1; d++)
	if (g (3, k))
	  return;
    }
  f--;
}

int main ()
{
  j ();
  printf ("%d\n", f);
  return 0; 
}

**Comment by fhahn** [comment]
As Eli indicated, this looks similar to #29796 and the reproducer produces the same result when using the `opt` sequence and `-O0`.
