### ISSUE TITLE
[GVNSink]  Seg Fault after deep recursion in lookupOrAdd()

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#36302]
|  |  |
| --- | --- |
| Bugzilla Link | [36954](https://llvm.org/bz36954) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced testcase](https://user-images.githubusercontent.com/55128014/143757325-dbe810ec-5ac7-4b4c-b907-a108d3d3f68a.gz), [unreduced test](https://user-images.githubusercontent.com/55128014/143757326-6f36b530-1915-49ed-8ec1-3a7b4d656db9.gz), [testcase](https://user-images.githubusercontent.com/55128014/143757327-f2060be5-c849-473d-9257-d0fe0b2c1209.gz), [test case](https://user-images.githubusercontent.com/55128014/143757328-c3b997dc-0e03-499a-a9d5-47a789fcc6f5.gz), [reduced testcase](https://user-images.githubusercontent.com/55128014/143757329-06bb88f2-5ca7-45a0-ad5e-052f80acbae2.gz), [reduced testcase](https://user-images.githubusercontent.com/55128014/143757330-39540999-d5cf-4a1f-ac7d-5972dbc1ca5c.gz) |
| CC | @jmolloy,@dobbelaj-snps,@JonPsson,@uweigand |

## Extended Description 

```
bin/opt -mtriple=s390x-linux-gnu -mcpu=z13 ./tc_gvnsink.ll -S -o /dev/null -O3 -enable-gvn-sink

#255 0x000002aa1f364dea (anonymous namespace)::ValueTable::lookupOrAdd(llvm::Value*) (bin/opt+0xe64dea)
Stack dump:
0.      Program arguments: bin/opt -mtriple=s390x-linux-gnu -mcpu=z13 ./tc_gvnsink.ll -S -o /dev/null -O3 -enable-gvn-sink 
1.      Running pass 'CallGraph Pass Manager' on module './tc_gvnsink.ll'.
2.      Running pass 'Early GVN sinking of Expressions' on function '@2'
Segmentation fault
```

**Comment by JonPsson** [comment]
[testcase.tar.gz](https://github.com/llvm/llvm-project/files/7961844/testcase.tar.gz)

Seems like the same error at least is still showing up...

clang -cc1 -triple s390x-ibm-linux -S  -target-cpu arch13 -O3 -w -mllvm -enable-gvn-sink -mllvm -unswitch-threshold=30  -o /dev/null  -x ir  tc_crash0_aftercreduce.ll
...
#254 0x000002aa11e6af90 (anonymous namespace)::ValueTable::lookupOrAdd(llvm::Value*) GVNSink.cpp:0:0
#255 0x000002aa11e6af90 (anonymous namespace)::ValueTable::lookupOrAdd(llvm::Value*) GVNSink.cpp:0:0
Segmentation fault (core dumped)

**Comment by xgupta** [comment]
> [testcase.tar.gz](https://github.com/llvm/llvm-project/files/7961844/testcase.tar.gz)
> 
> Seems like the same error at least is still showing up...

tested today, the issue is not produced on the trunk.
