### ISSUE TITLE
Missing line breaks with loop on a single line

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36308]
|  |  |
| --- | --- |
| Bugzilla Link | [36960](https://llvm.org/bz36960) |
| Version | 6.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
With the .clang-format file

Language:        Cpp
AllowShortBlocksOnASingleLine: true
AllowShortLoopsOnASingleLine: true
BreakBeforeBraces: Custom
BraceWrapping:   
  AfterControlStatement: true

I get this formatting

int main() {
  for (int i = 0; i < 10; ++i)
  { i + i + i + i + i + i + i + i + i + i + i + i; } return 10;
}

Note that "return 10;" is on the same line as the braced block.  I see similar behavior with "if" statements and AllowShortIfStatementsOnASingleLine.

This is using the Debian package of clang-format-6.0 in buster.

  $ clang-format-6.0 --version
  clang-format version 6.0.0-1 (tags/RELEASE_600/final)

**Comment by mydeveloperday** [comment]
From clang-format v8 I see the following output, I am closing this issue please reopen if the problem persists

```
int main() {
  for (int i = 0; i < 10; ++i)
  { i + i + i + i + i + i + i + i + i + i + i + i; }
  return 10;
}
```
