### ISSUE TITLE
wrong code with opt "-inline -loop-rotate -loop-unroll -memcpyopt -tbaa -gvn"

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#36313]
|  |  |
| --- | --- |
| Bugzilla Link | [36965](https://llvm.org/bz36965) |
| Version | trunk |
| OS | All |
| CC | @efriedma-quic |

## Extended Description 
$ clangpolly -v
clang version 7.0.0 (http://llvm.org/git/clang.git e327c701dd9ac0a478f777a41a198010ee8ddeba) (llvm/trunk 328759)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.2.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clangpolly -O0 small.c; ./a.out
5
$ 
$ clangpolly -O3 -mllvm -disable-llvm-optzns -c -emit-llvm -o small.bc small.c
$ optpolly -inline -loop-rotate -loop-unroll -memcpyopt -tbaa -gvn -o small-opt.bc small.bc
$ clangpolly small-opt.bc 
$ ./a.out
11
$ 

-----------------------------------------------------

int printf (const char *, ...);

int a, *b = &a, c, d, f, g, h = 1, *j = &c, o = 11;

int *e (int *m, int *n)
{
  int i = 0;
  for (; i < 7; i++)
    ;
  *m = *b;
  a = 5;
  return &d;
}

void k (int *l)
{
  int *t; 
  *b = *l;
  if (h)
    {
      t = e (&f, &g);
      e (j, t);
    }
}

int main ()
{
  k (&o);
  printf ("%d\n", c);
  return 0;
}

**Comment by fhahn** [comment]
This reproduces up to LLVM 12.0.1: https://clang.godbolt.org/z/v9K31f1nM (BAD)

And looks fixed in LLVM 13.0 (https://clang.godbolt.org/z/so9Tf51oh (GOOD)) , which IIRC is the first version that uses MemorySSA for MemCpyOpt, so this matches the earlier comment about the cause of the issue
