### ISSUE TITLE
wrong code with opt "-jump-threading -loop-rotate -gvn -loop-unroll -memcpyopt -gvn"

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#36312]
|  |  |
| --- | --- |
| Bugzilla Link | [36964](https://llvm.org/bz36964) |
| Version | trunk |
| OS | All |

## Extended Description 
$ clangpolly -v
clang version 7.0.0 (http://llvm.org/git/clang.git e327c701dd9ac0a478f777a41a198010ee8ddeba) (llvm/trunk 328759)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.2.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clangpolly -O0 -w small.c; ./a.out
$ 
$ clangpolly -O3 -mllvm -disable-llvm-optzns -w -c -emit-llvm -o small.bc small.c
$ optpolly -jump-threading -loop-rotate -gvn -loop-unroll -memcpyopt -gvn -o small-opt.bc small.bc
$ clangpolly small-opt.bc
$ ./a.out
Aborted (core dumped)
$ 

------------------------------

int a, *b = &a;

int main ()
{    
  int c[1], d[30], i, j;
  for (j = 0; j < 1; j++)
    c;
  for (i = 0; i < 3; i++)
    for (j = 0; j < 10; j++)
      d[i * 3 + j] = 0;
  *b = d[2];
  if (a != 0) 
    __builtin_abort ();
  return 0;  
}

**Comment by fhahn** [comment]
I am unable to reproduce this on current main, so this likely has been fixed. `MemCpyOpt` has had a major update to use MemorySSA instead of MemDepAnalysis.

Please re-open the issue with additional info if it still reproduces on your side.
