### ISSUE TITLE
Using macro for file and line for lttng tracepoint gives error: expected expression

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36364]
|  |  |
| --- | --- |
| Bugzilla Link | [37016](https://llvm.org/bz37016) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Using a macro for file and line as below generates an error:

myfile1.cc:461:9: error: expected expression [clang-diagnostic-error]
        MY_DEBUG(com_XXX, "YYY");
        ^
lttng_helper.h:31:65: note: expanded from macro 'MY_DEBUG'
      do_tracepoint(provider, S_debug, msg_lttng_helper_unique, TP_FILE_AND_LINE);            \
                                                                ^
lttng_helper.h:21:27: note: expanded from macro 'TP_FILE_AND_LINE'
#define TP_FILE_AND_LINE (__FILENAME__ ":" TP_TOSTRING(__LINE__)) 

Changing the line TP_FILE_AND_LINE to some dummy value like

#define TP_FILE_AND_LINE "Hi"

removes the error. 

Adding // NOLINT after the line doesn't help as I would have expected.
Neither does surrounding it with #ifndef __clang-analyzer__ ... #else ... #endif

>clang-tidy -version
LLVM (http://llvm.org/):
  LLVM version 4.0.0
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: sandybridge

**Comment by carlosgalvezp** [comment]
Missing reproducible, self-contained example, please open a new bug if the problem persists.
