### ISSUE TITLE
Assertion `!SpecializedTemplate.is<SpecializedPartialSpecialization*>() && "Already set to a class template partial specialization!"' failed.

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#36376]
|  |  |
| --- | --- |
| Bugzilla Link | [37028](https://llvm.org/bz37028) |
| Version | trunk |
| OS | Linux |

**Comment by Endilll** [comment]
Appears to be fixed in Clang 7: https://cexplorer.testlabs.pro/z/hYd9aY
