### ISSUE TITLE
Unicode string literals

### ISSUE THREAD

**Issue by MarcusJohnson91** [llvm/llvm-project#36392]
|  |  |
| --- | --- |
| Bugzilla Link | [37044](https://llvm.org/bz37044) |
| Version | unspecified |
| OS | MacOS X |
| CC | @topperc,@zygoloid |

## Extended Description 
`\x` Does not work with Unicode characters outside of the BMP for example U+1F984, and `\u` and `\U` (for UTF-16 and UTF-32) will not work with Unicode characters in the ASCII range (for example, 0x20, the space).

I'm not entirely sure what to do here, I ran into this problem because I'm writing a script to parse the Unicode Character Database to create some tables in C for my library, StringIO.

Example code:

    uint_least32_t Space32_1[]         = U"\x20";
    uint_least32_t Space32_2[]         = U"\U20";
    uint_least32_t Unicorn32_1[]       = U"\x1F984";
    uint_least32_t Unicorn32_2[]       = U"\U1F984";

**Comment by cor3ntin** [comment]
Any universal character name is now valid in characters and string literals in both C++ and C23, so I think we can mark this issue as closed.
