### ISSUE TITLE
Make it possible to import another .clang-tidy in .clang-tidy

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36390]
|  |  |
| --- | --- |
| Bugzilla Link | [37042](https://llvm.org/bz37042) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The problem I have is that I want to have some check enabled for almost all files in a project, but certain external dependencies violate the check. As it is now I have to disable them completely or duplicate my .clang-tidy and tweak it slightly in sub-dirs.

An example of this is Google Test. I want to have e.g. cppcoreguidelines-special-member-functions and modernize-use-equals-delete enabled in my project's .clang-tidy but Google Test violates these checks so I have to disable them for all of my project. Would be nice if I could do:

project_root/
    .clang-tidy
    src/
        unit_tests/
            .clang-tidy

And have the .clang-tidy in unit_tests in some way say "use configuration from ../../.clang-tidy but disable cppcoreguidelines-special-member-functions and modernize-use-equals-delete".

**Comment by EugeneZelenko** [comment]
`InheritParentConfig` was introduced in cb1ee34e9d32fce84613827693a8ed3aff1d36cf.
