### ISSUE TITLE
Attributes order, it is meaningful and clang loses it.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#3640]
|  |  |
| --- | --- |
| Bugzilla Link | [3268](https://llvm.org/bz3268) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@efriedma-quic |

## Extended Description 
It is critical in presence of __asm__ attribute, the __asm__ attribute must be first.
Instead in this code:
---->
typedef unsigned long size_t;
extern int strerror_r(int __errnum, char *__buf, size_t __buflen)
  __asm__ ("" "__xpg_strerror_r")
  __attribute__ ((__nothrow__))
  __attribute__ ((__nonnull__ (2)));
----<
The asm attribute comes out last.

**Comment by gwelymernans** [comment]
FWIW, the `-ast-dump` of the original code outputs this:

```
`-FunctionDecl 0x11b9c720 <line:2:1, line:5:29> line:2:12 strerror_r 'int (int, char *, size_t)' extern
  |-ParmVarDecl 0x11b9c440 <col:23, col:27> col:27 __errnum 'int'
  |-ParmVarDecl 0x11b9c4c0 <col:37, col:43> col:43 __buf 'char *'
  |-ParmVarDecl 0x11b9c560 <col:50, col:57> col:57 __buflen 'size_t':'unsigned long'
  |-AsmLabelAttr 0x11b9c7c0 <line:3:6> "__xpg_strerror_r" IsLiteralLabel
  |-NoThrowAttr 0x11b9c850 <line:4:17>
  `-NonNullAttr 0x11b9c878 <line:5:17, col:27> 2
```

**Comment by erichkeane** [comment]
Since this has been filed, the 'ordering' of attributes has been made consistent.  This happened a few years ago.

THOUGH note that 'nothrow' is actually a 'type attribute' in C++ mode, so it ends up being put into the FunctionDecl's type itself.

I think this is a 'fixed' bug.
