### ISSUE TITLE
clang crashes at -O1: Assertion `MBB != &MF->front() && "Can't find reaching def for virtreg"' failed.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36428]
|  |  |
| --- | --- |
| Bugzilla Link | [37080](https://llvm.org/bz37080) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
It happens at 32-bit mode only.  64-bit mode works fine.

It appears to be a backend issue.

$ clang-trunk -v
clang version 7.0.0 (trunk 329676)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin

$ clang-trunk -m32 -O1 abc.c
abc.c:7:8: warning: incompatible pointer types initializing 'int *' with an expression of type 'void ()' [-Wincompatible-pointer-types]
  int *g = fn1;
       ^   ~~~
abc.c:9:7: warning: incompatible pointer types assigning to 'int *' from 'long *' [-Wincompatible-pointer-types]
    g = &e;
      ^ ~~
clang-7: /home/absozero/trunk/llvm/lib/CodeGen/LiveVariables.cpp:113: void llvm::LiveVariables::MarkVirtRegAliveInBlock(llvm::LiveVariables::VarInfo&, llvm::MachineBasicBlock*, llvm::MachineBasicBlock*, std::vector<llvm::MachineBasicBlock*>&): Assertion `MBB != &MF->front() && "Can't find reaching def for virtreg"' failed.
#&#8203;0 0x000000000223db4a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/absozero/trunk/root-clang/bin/clang-7+0x223db4a)
#&#8203;1 0x000000000223b9ee llvm::sys::RunSignalHandlers() (/home/absozero/trunk/root-clang/bin/clang-7+0x223b9ee)
#&#8203;2 0x000000000223bb42 SignalHandler(int) (/home/absozero/trunk/root-clang/bin/clang-7+0x223bb42)
#&#8203;3 0x00007f3a78146330 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10330)
#&#8203;4 0x00007f3a76cc3c37 gsignal /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;5 0x00007f3a76cc7028 abort /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;6 0x00007f3a76cbcbf6 __assert_fail_base /build/eglibc-oGUzwX/eglibc-2.19/assert/assert.c:92:0
#&#8203;7 0x00007f3a76cbcca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
#&#8203;8 0x0000000001993216 (/home/absozero/trunk/root-clang/bin/clang-7+0x1993216)
#&#8203;9 0x0000000001993255 llvm::LiveVariables::MarkVirtRegAliveInBlock(llvm::LiveVariables::VarInfo&, llvm::MachineBasicBlock*, llvm::MachineBasicBlock*) (/home/absozero/trunk/root-clang/bin/clang-7+0x1993255)
#&#8203;10 0x0000000001993969 llvm::LiveVariables::HandleVirtRegUse(unsigned int, llvm::MachineBasicBlock*, llvm::MachineInstr&) (/home/absozero/trunk/root-clang/bin/clang-7+0x1993969)
#&#8203;11 0x0000000001998cd4 llvm::LiveVariables::runOnInstr(llvm::MachineInstr&, llvm::SmallVectorImpl<unsigned int>&) (/home/absozero/trunk/root-clang/bin/clang-7+0x1998cd4)
#&#8203;12 0x0000000001999320 llvm::LiveVariables::runOnBlock(llvm::MachineBasicBlock*, unsigned int) (/home/absozero/trunk/root-clang/bin/clang-7+0x1999320)
#&#8203;13 0x000000000199a29c llvm::LiveVariables::runOnMachineFunction(llvm::MachineFunction&) (/home/absozero/trunk/root-clang/bin/clang-7+0x199a29c)
#&#8203;14 0x00000000019e654d llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/home/absozero/trunk/root-clang/bin/clang-7+0x19e654d)
#&#8203;15 0x0000000001d465e3 llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/absozero/trunk/root-clang/bin/clang-7+0x1d465e3)
#&#8203;16 0x0000000001d466ac llvm::FPPassManager::runOnModule(llvm::Module&) (/home/absozero/trunk/root-clang/bin/clang-7+0x1d466ac)
#&#8203;17 0x0000000001d4617d llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/absozero/trunk/root-clang/bin/clang-7+0x1d4617d)
#&#8203;18 0x00000000024082ec (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/home/absozero/trunk/root-clang/bin/clang-7+0x24082ec)
#&#8203;19 0x0000000002409aa1 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/home/absozero/trunk/root-clang/bin/clang-7+0x2409aa1)
#&#8203;20 0x0000000002c68e47 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/absozero/trunk/root-clang/bin/clang-7+0x2c68e47)
#&#8203;21 0x0000000003195900 clang::ParseAST(clang::Sema&, bool, bool) (/home/absozero/trunk/root-clang/bin/clang-7+0x3195900)
#&#8203;22 0x0000000002c681fc clang::CodeGenAction::ExecuteAction() (/home/absozero/trunk/root-clang/bin/clang-7+0x2c681fc)
#&#8203;23 0x000000000280367e clang::FrontendAction::Execute() (/home/absozero/trunk/root-clang/bin/clang-7+0x280367e)
#&#8203;24 0x00000000027cf8a6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/absozero/trunk/root-clang/bin/clang-7+0x27cf8a6)
#&#8203;25 0x0000000002897d20 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/absozero/trunk/root-clang/bin/clang-7+0x2897d20)
#&#8203;26 0x0000000000a9de18 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/absozero/trunk/root-clang/bin/clang-7+0xa9de18)
#&#8203;27 0x0000000000a1121c main (/home/absozero/trunk/root-clang/bin/clang-7+0xa1121c)
#&#8203;28 0x00007f3a76caef45 __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;29 0x0000000000a99de9 _start (/home/absozero/trunk/root-clang/bin/clang-7+0xa99de9)
Stack dump:
0.	Program arguments: /home/absozero/trunk/root-clang/bin/clang-7 -cc1 -triple i386-unknown-linux-gnu -emit-obj -disable-free -main-file-name abc.c -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu pentium4 -dwarf-column-info -debugger-tuning=gdb -momit-leaf-frame-pointer -resource-dir /home/absozero/trunk/root-clang/lib/clang/7.0.0 -internal-isystem /usr/local/include -internal-isystem /home/absozero/trunk/root-clang/lib/clang/7.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O1 -fdebug-compilation-dir /home/absozero/projects/reduction/crash -ferror-limit 19 -fmessage-length 142 -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/abc-1bd7ab.o -x c abc.c 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'abc.c'.
4.	Running pass 'Live Variable Analysis' on function '@fn1'
clang-7: error: unable to execute command: Aborted (core dumped)
clang-7: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 7.0.0 (trunk 329676)
Target: i386-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
clang-7: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-7: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-7: note: diagnostic msg: /tmp/abc-434316.c
clang-7: note: diagnostic msg: /tmp/abc-434316.sh
clang-7: note: diagnostic msg: 

********************

$ cat abc.c
unsigned a;
short b;
char c, d;
long e;
char *f;
void fn1() {
  int *g = fn1;
  for (; *g;)
    g = &e;
  for (;;)
    b = (d = 0 == (e &= a)) % (*g |= 1) && 0 ?: (c = d) ^ *f;
}

**Comment by Endilll** [comment]
Can't reproduce using Clang 6 and 7 with assertions enabled: https://cexplorer.testlabs.pro/z/8r8rao
