### ISSUE TITLE
Long Long Enum Constant

### ISSUE THREAD

**Issue by MarcusJohnson91** [llvm/llvm-project#36424]
|  |  |
| --- | --- |
| Bugzilla Link | [37076](https://llvm.org/bz37076) |
| Version | unspecified |
| OS | MacOS X |
| CC | @efriedma-quic |

## Extended Description 
For some reason, enums are limited to 32 bits (and have to be signed for some reason)

Can you bump it up to a long long?

As it is, I can't put the magic number of a PNG file as a constant in an enum, I have to use a macro, which is just icky.

I know the standard says it's type is an unqualified int, but getting the standard changed requires an implementation.

**Comment by AaronBallman** [comment]
Clang has supported this for a *long* time, but it is an extension in C: https://godbolt.org/z/5E6aY8aTa. Closing the issue as not reproducible.
