### ISSUE TITLE
Clang-cl 5 and 6 crash when compiling correct code (works with clang 5/6 and gcc)

### ISSUE THREAD

**Issue by 1fa7965d-48d1-4c7f-b7a0-1ff893d88a68** [llvm/llvm-project#36456]
|  |  |
| --- | --- |
| Bugzilla Link | [37108](https://llvm.org/bz37108) |
| Version | 6.0 |
| OS | Windows NT |
| Attachments | [original source, preprocessed source, associated run script and crash dump](https://user-images.githubusercontent.com/95090543/143757374-b2be756b-7c1c-4448-bf94-e80ee3b25b32.gz) |

## Extended Description 

Clang-cl 5 and 6 crash when compiling correct code (with lots of templates). 

System
------

I'm using clang-cl 5.0.1 / 6.0.0 on MSVC 2017 with cmake on windows 10 on x64. 

Compiler used:
--------------
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: D:\windows\LLVM6\bin
Found CUDA installation: /Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0, version 8.0

Description
-----------

When compiling the attached main.cpp, the compiler crashes with C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\clang-cl.exe : error : clang frontend command failed due to signal (use -v to see invocation)

However, it runs on clang 5/6 and gcc 7, tested on wandbox: https://wandbox.org/permlink/CeupMn2iDZZElZZ7.

The crash does not occur when changing line L 1162 in the attached main.cpp file as described there. Unfortunately, I have absolutely no idea what could be the reason.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 8: https://godbolt.org/z/GrW4TM7xT
Reduced by me and C-Reduce:
```cpp
template < typename Nodes_>
struct NodeBase {
  Nodes_ nodes;
  NodeBase(...);
};

template < typename Nodes_>
struct Node : NodeBase< Nodes_ > {
  using NodeBase< Nodes_ >::NodeBase;
};

template < typename >
struct NonTriviallyDestructible {
  ~NonTriviallyDestructible();
};

int foo(Node<NonTriviallyDestructible<Node<int>>>);

auto g = foo(Node<int>{});
```
