### ISSUE TITLE
Seg fault when running clang-format

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36462]
|  |  |
| --- | --- |
| Bugzilla Link | [37114](https://llvm.org/bz37114) |
| Version | 6.0 |
| OS | Linux |
| Attachments | [this file fails clang-format-6.0 for me on Amazon Linux](https://user-images.githubusercontent.com/60944935/143757377-b2aed373-000c-4494-80ff-3bfb9c2a7016.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@cpplearner |

## Extended Description 
i get the following dump:
#&#8203;0 0x0000000000424e64 PrintStackTraceSignalHandler(void*) (/opt/clang/bin/clang-format+0x424e64)
#&#8203;1 0x0000000000425146 SignalHandler(int) (/opt/clang/bin/clang-format+0x425146)
#&#8203;2 0x00007faa6e276390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
#&#8203;3 0x00000000004342e4 clang::DiagnosticIDs::ProcessDiag(clang::DiagnosticsEngine&) const (/opt/clang/bin/clang-format+0x4342e4)
#&#8203;4 0x0000000000432e82 clang::DiagnosticsEngine::EmitCurrentDiagnostic(bool) (/opt/clang/bin/clang-format+0x432e82)
#&#8203;5 0x000000000048a91b clang::Rewriter::overwriteChangedFiles() (/opt/clang/bin/clang-format+0x48a91b)
#&#8203;6 0x0000000000408beb clang::format::format(llvm::StringRef) (/opt/clang/bin/clang-format+0x408beb)
#&#8203;7 0x0000000000406e85 main (/opt/clang/bin/clang-format+0x406e85)
#&#8203;8 0x00007faa6d20e830 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20830)
#&#8203;9 0x0000000000406949 _start (/opt/clang/bin/clang-format+0x406949)
xargs: /opt/clang/bin/clang-format: terminated by signal 11

this is while running on AWS EC2 instance
it's running on Amazon Linux AMI (ie centos)

this is on Java code

**Comment by mydeveloperday** [comment]
The most likely cause of this is that you didn't have permission to save the file that was being overwritten, clang-format used to crash like this, but this was recently fixed.

I believe this to be fixed by a92cf5a5a0cd01145f8db2ae09334a8b43a1271b 

I am closing this issue please reopen if its still an issue
