### ISSUE TITLE
Clang miscompiles with -O0.

### ISSUE THREAD

**Issue by Vsevolod-Livinskij** [llvm/llvm-project#36463]
|  |  |
| --- | --- |
| Bugzilla Link | [37115](https://llvm.org/bz37115) |
| Version | trunk |
| OS | Linux |
| CC | @dbabokin,@Vsevolod-Livinskij |

## Extended Description 
Clang miscompiles testcase with -O0.

Reproducer:
>$ cat repr.cpp
#include <stdio.h>

struct struct_1 {
  int a : 17;
  bool b;
  static int stat_memb;
};
int struct_1::stat_memb;

struct_1 struct_obj_1 = {42, false};
struct_1 struct_obj_2 = {42, false};

int var;

void tf_3_foo() {
  struct_obj_2.stat_memb = unsigned(~0) > 0;
  var = -((-9223372036854775807L - 1) * struct_obj_1.stat_memb / (-9223372036854775807L - 1)) * struct_obj_1.a;
}

int main() {
  tf_3_foo();
  printf("%d\n", var);
}

Error:
>$ clang++ -O0 repr.cpp ; ./a.out
42
>$ clang++ -O1 repr.cpp ; ./a.out
-42

GCC also gives -42 as an answer.

LLVM version:
>$ clang++ -v
clang version 7.0.0 (trunk 329789)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /llvm/bin-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64

**Comment by fhahn** [comment]
Looks like this has been fixed on current main: https://llvm.godbolt.org/z/9sxsf5G9K

I was not able to reproduce this with an clang version I tried on godbolt, so it seems like this never made it into a release. Please re-open the issue with additional info if it still reproduces on your end
