### ISSUE TITLE
clang-rename on a non existing file segfaults

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#36471]
|  |  |
| --- | --- |
| Bugzilla Link | [37123](https://llvm.org/bz37123) |
| Version | unspecified |
| OS | All |

## Extended Description 
$ clang-rename-7 -offset=0  -new-name=plop asdasd
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "asdasd"
No compilation database found in /tmp or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
warning: /tmp/asdasd: 'linker' input unused [-Wunused-command-line-argument]
error: unable to handle compilation, expected exactly one compiler job in ''
Error while processing /tmp/asdasd.
warning: /tmp/asdasd: 'linker' input unused [-Wunused-command-line-argument]
error: unable to handle compilation, expected exactly one compiler job in ''
Error while processing /tmp/asdasd.
Segmentation fault

Same issue with clang-rename-6.0 & clang-rename-5.0

**Comment by xgupta** [comment]
It is now failing with assertion which should be fine? 

Error while trying to load a compilation database:
Could not auto-detect compilation database for file "asdasd"
No compilation database found in /home/digital/Music/llvm-project-main/clang or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
error: no such file or directory: '/home/digital/Music/llvm-project-main/clang/asdasd'
error: no input files
error: unable to handle compilation, expected exactly one compiler job in ''
Error while processing /home/digital/Music/llvm-project-main/clang/asdasd.
error: no such file or directory: '/home/digital/Music/llvm-project-main/clang/asdasd'
error: no input files
error: unable to handle compilation, expected exactly one compiler job in ''
Error while processing /home/digital/Music/llvm-project-main/clang/asdasd.
clang-rename: /home/digital/Downloads/llvm-project/llvm/include/llvm/Support/ErrorOr.h:237: llvm::ErrorOr::storage_type *llvm::ErrorOr<const clang::FileEntry *>::getStorage() [T = const clang::FileEntry *]: Assertion `!HasError && "Cannot get value when an error exists!"' failed.
[1]    12486 abort (core dumped)  clang-rename -offset=0 -new-name=plop asdasd

**Comment by xgupta** [comment]
Patch on review - https://reviews.llvm.org/D148439.

**Comment by xgupta** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/726199146a0bb53315ade042e759c65e6d96d556.

**Comment by kirillbobyrev** [comment]
My bad, I accepted the [patch](https://reviews.llvm.org/D148439) without looking closely enough at it, it shouldn't be the right one to fix this problem.
