### ISSUE TITLE
Preprocessor directives parsing broken when struct, class or namespace declared.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36513]
|  |  |
| --- | --- |
| Bugzilla Link | [37165](https://llvm.org/bz37165) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I've used clang-tidy integrated into latest QtCreator 4.6.0 on Linux.
The bug I've found is wrong clang-tidy diagnostic due to a bug in
preprocessor directives parsing.

Reduced code sample is:

1) OK, without errors (struct declaration commented out):
---
#ifdef ENABLE_DIAGNOSIS
    #define DIAGNOSE_ENABLED true
    #define DIAGNOSIS_LOG_FILE(file) diagnosis::log(file)
//    struct diagnosis {
//        static void log(const char*) {}
//    };
#else
    #define DIAGNOSE_ENABLED false
    #define DIAGNOSIS_LOG_FILE(file)
#endif
---

2) Parsed with errors ("error: unterminated conditional directive") for #ifdef, #else and #endif of the main conditional block

---
#ifdef ENABLE_DIAGNOSIS
    #define DIAGNOSE_ENABLED true
    #define DIAGNOSIS_LOG_FILE(file) diagnosis::log(file)
    struct diagnosis {
        static void log(const char*) {}
    };
#else
    #define DIAGNOSE_ENABLED false
    #define DIAGNOSIS_LOG_FILE(file)
#endif
---

It seems like #if-#else-#endif preprocessor directives parsing breaks when I add any class, structure or namespace definitions.

**Comment by carlosgalvezp** [comment]
Not reproducible.
