### ISSUE TITLE
[llvm-exegesis] Improve unit tests running on the build bots

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#36524]
|  |  |
| --- | --- |
| Bugzilla Link | [37176](https://llvm.org/bz37176) |
| Version | trunk |
| OS | Windows NT |
| Depends On | llvm/llvm-project#51029  |
| CC | @adibiagio,@legrosbuffle,@filcab,@gchatelet,@gregbedwell |

## Extended Description 
We need at least some llvm-exegesis testing on the buildbots, for that we need buildbots running a suitable version of perfmon2/libpfm4 and a suitable supported cpu. I believe there may be issues with buildbots running in a vm not correctly reporting pmc values as well.

The unit tests will then need a cpuid mechanism to correctly attempt at least to match a few basic instructions against expected latency/uop counts.

**Comment by LebedevRI** [comment]
I believe this is now resolved now that at least ~all the X86 exegesis tests use dry-run mode.
