### ISSUE TITLE
modernize-use-using sometimes replaces template parameter in typedef with instantiation

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36561]
|  |  |
| --- | --- |
| Bugzilla Link | [37213](https://llvm.org/bz37213) |
| Version | unspecified |
| OS | All |
| Attachments | [File demonstrating the problem](https://user-images.githubusercontent.com/60944935/143757405-f4ff25c5-7369-4e47-9e8e-5341b18f1b4c.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @EugeneZelenko |

## Extended Description 

When processing the attached file with:

    clang-tidy -checks=-*,modernize-use-using test.cpp -- -std=c++11

the template parameter in the `const_iterator` typedef is replaced in the "using" statement by the instantiation being processed:

/work/test.cpp:67:5: warning: use 'using' instead of 'typedef' [modernize-use-using]
    typedef typename Container::const_iterator const_iterator;
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    using const_iterator = typename map<int, double, less<int>, allocator<pair<const int, double> > >::const_iterator

Sorry I couldn't simplify the problem further.  Removing the definitions of some of the other iterators results in the expected replacement:

/work/ql/timeseries.hpp:67:5: warning: use 'using' instead of 'typedef' [modernize-use-using]
    typedef typename Container::const_iterator const_iterator;
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    using const_iterator = typename Container::const_iterator

I'm working in an Ubuntu Bionic docker image (which I can make available to you, if you need it).  The Boost version is 1.66.0.

# clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 5.0.1
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: haswell

**Comment by PiotrZSL** [comment]
This duplicate of #31864 that were fixed by b34b6ffa9d4aae16272cbdbf508134f98b4647d4.
