### ISSUE TITLE
ClangFormat - Brace initializer syntax is formatted inconsistently and confusingly when dealing with #ifdef

### ISSUE THREAD

**Issue by abpostelnicu** [llvm/llvm-project#36578]
|  |  |
| --- | --- |
| Bugzilla Link | [37230](https://llvm.org/bz37230) |
| Version | trunk |
| OS | All |
| CC | @sylvestre |

## Extended Description 
Given the following input:
```cpp
template<class T>
class NonNull
{
public:
  NonNull()
    : ptr{ nullptr }
  #ifdef DEBUG
, inited(false)
 #endif
  {
  }
};
```
Using the Mozilla style the output is:
```cpp
template<class T>
class NonNull
{
public:
  NonNull()
    : ptr
  {
    nullptr
  }
#ifdef DEBUG
  , inited(false)
#endif
  {}
};
```
We can see two issues here:
1. The initialisation of ptr is strange, it's being split on several lines. Most likely this is because Mozilla cs also uses 'BreakConstructorInitializers' with FormatStyle::BCIS_BeforeComma
2. inited is not indented properly

Using the Google style the output is:
```cpp
template <class T>
class NonNull {
 public:
  NonNull() : ptr { nullptr }
#ifdef DEBUG
  , inited(false)
#endif
  {
  }
};
```
This time the format looks almost accurate except variable inited is not properly aligned. 

Using the LLVM style the output is identical with the Google style.

**Comment by rymiel** [comment]
The original issue with Mozilla style is fixed by 3d209c76ddb56db73def474450532813e39d95fa, part of clang-format 14
