### ISSUE TITLE
Merge r328687 into the 6.0 branch : [ORC] Fix ORC on platforms without indirection support.

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#36584]
|  |  |
| --- | --- |
| Bugzilla Link | [37236](https://llvm.org/bz37236) |
| Version | 6.0 |
| OS | All |
| Blocks | llvm/llvm-project#35152 llvm/llvm-project#35997  |
| Fixed by commit(s) | r328687 |

## Extended Description 
Is it OK to merge the following revision(s) to the 6.0 branch?

**Comment by arsenm** [comment]
Old release
