### ISSUE TITLE
clang crashes at -O1 and above in 32-bit mode with debugging enabled: fatal error: error in backend: Found 1 in/out CFI information errors

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#36604]
|  |  |
| --- | --- |
| Bugzilla Link | [37256](https://llvm.org/bz37256) |
| Version | unspecified |
| OS | All |
| CC | @vedantk |

## Extended Description 
Tested with trunk revision 330807. 

$ clangpolly -v
clang version 7.0.0 (http://llvm.org/git/clang.git 859cc527ff1e5b34c3828766dc830a6e46801945) (llvm/trunk 330807)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.2.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$
$ clangpolly -m32 -O1 -c -w small.c
$ clangpolly -m32 -O0 -g -c -w small.c
$
$ clangpolly -m32 -O1 -g -c -w small.c
*** Inconsistent CFA register and/or offset between pred and succ ***
Pred: if.then outgoing CFA Reg:4
Pred: if.then outgoing CFA Offset:4
Succ: lor.rhs incoming CFA Reg:4
Succ: lor.rhs incoming CFA Offset:8
fatal error: error in backend: Found 1 in/out CFI information errors.
clang-6.0: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 7.0.0 (http://llvm.org/git/clang.git 859cc527ff1e5b34c3828766dc830a6e46801945) (llvm/trunk 330807)
Target: i386-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
clang-6.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-6.0: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-6.0: note: diagnostic msg: /tmp/small-f728ca.c
clang-6.0: note: diagnostic msg: /tmp/small-f728ca.sh
clang-6.0: note: diagnostic msg:

********************
$

--------------------------------

int a, b, c, d, f;
volatile int e;

void g ()
{ 
  int *h;
  if (a)
    { 
      int *i;
      (d || (*i = b)) | e;
    }
  int volatile j = f;
  *h = c;
}

**Comment by fhahn** [comment]
It looks like this was fixed before it made it into a LLVM release. I was unable to reproduce this with any version on godbolt and it doesn't crash on current `main`: https://godbolt.org/z/887caxf4d
