### ISSUE TITLE
layer2/RepCylBond.cpp exposes compiler ICE for -O1 or higher without -fno-strict-aliasing

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36628]
|  |  |
| --- | --- |
| Bugzilla Link | [37280](https://llvm.org/bz37280) |
| Version | 6.0 |
| OS | MacOS X |
| Attachments | [bzip2 compressed compiler ICE reproducer](https://user-images.githubusercontent.com/60944935/143757435-cf4cec64-6a9f-4985-ba07-41dbe28547cb.gz), [compiler ICE reproducer script](https://user-images.githubusercontent.com/60944935/143757436-a8596bfc-4fa5-4adb-8541-d1dc0d92bc7c.gz), [bzip compressed preprocessed source for RepCylBond.cpp](https://user-images.githubusercontent.com/60944935/143757437-1cb473bf-77e5-47c6-a750-ee413d2e37d5.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @rotateright |

## Extended Description 
The recent code for layer2/RepCylBond.cpp has exposed a clang compiler ICE on Darwin.

7 warnings generated.
fatal error: error in backend: Unsupported expression in static initializer: fsub (float 1.000000e+00, float undef)
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /opt/local/libexec/llvm-6.0/bin

This issue occurs reportedly is present with Xoode's clang circa OS X 10.9 and is confirmed in llvm.org's clang since at least clang 4.0 up to clang 6.0. The issue doesn't occur for the -O0 or no optimization flags but does occur for -O1 or higher. The compiler ICE is suppressed however if -fno-strict-aliasing is passed to the compiler.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 7: https://godbolt.org/z/sGGs7WWa9
Reduced by C-Reduce:
```
int RepCylBondNew_n_var_alpha;
float *RepCylBondNew_I_1;
void RepCylBondNew() {
  float bd_transp, bd_alpha(1 - bd_transp);
  while (RepCylBondNew_n_var_alpha)
    RepCylBondNew_I_1[RepCylBondNew_n_var_alpha++] = bd_alpha;
}
```
