### ISSUE TITLE
One-line enum problem

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36650]
|  |  |
| --- | --- |
| Bugzilla Link | [37302](https://llvm.org/bz37302) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Configuration of clang-format:
```
AllowShortBlocksOnASingleLine: true
AllowShortIfStatementsOnASingleLine: true
BreakBeforeBraces: Custom
BraceWrapping: { AfterControlStatement: true, AfterEnum: true }
```

Code:

```
// BEFORE:
enum Enum { No, Yes };
if (statement) { doSomething(); }
```

```
// AFTER:
enum Enum
{
  No,
  Yes
};
if (statement) { doSomething(); }
```

This is similar to bug 34001 (which is already fixed), but for 'enum' instead of 'if'. The problem is that 'BraceWrapping: { AfterEnum: true }' makes it impossible to have one-line enums.

Since AllowShortBlocksOnASingleLine + AllowShortIfStatementsOnASingleLine allow this for 'if', probably an AllowShortEnumsOnASingleLine should be added. That way, one can independently control whether one-line enums are allowed and whether multi-line enums should break before '{'.

**Comment by mydeveloperday** [comment]
Since AllowShortEnumsOnASingleLine  has been added I'm, going to close this issue
