### ISSUE TITLE
clang-tidy reports "unknown argument" if passed "-Xclang -fcolor-diagnostics -pipe"

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36663]
|  |  |
| --- | --- |
| Bugzilla Link | [37315](https://llvm.org/bz37315) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @steveire |

## Extended Description 
I think this started to occur in 6.0.

$ clang-tidy foo.cpp -- -Xclang -fcolor-diagnostics -pipe -o foo.o -c foo.cpp
1 error generated.
Error while processing /tmp/delme/foo.cpp.
error: unknown argument: '-pipe' [clang-diagnostic-error]
$

Passing it -fdiagnostics-color=always (generated by build system when building with GCC) does not generate an error:

$ clang-tidy foo.cpp -- -fdiagnostics-color=always -pipe -o foo.o -c foo.cpp
$

**Comment by eli-schwartz** [comment]
Hi, is there any update or interest in this bug?

There are Meson reports that various perfectly legitimate flags used during actual compilation which are written out by `ninja -t compdb`, break clang-tidy. It would be great if clang-tidy was able to correctly handle well-written `compile_commands.json`.

**Comment by carlosgalvezp** [comment]
No longer reproducible on trunk.
