### ISSUE TITLE
FAIL: LLVM :: Bindings/Go/go.test - fatal error: 'math.h' file not found

### ISSUE THREAD

**Issue by jkorous-apple** [llvm/llvm-project#36673]
|  |  |
| --- | --- |
| Bugzilla Link | [37325](https://llvm.org/bz37325) |
| Version | trunk |
| OS | MacOS X |

## Extended Description 
FAIL: LLVM :: Bindings/Go/go.test (17105 of 44235)
******************** TEST 'LLVM :: Bindings/Go/go.test' FAILED ********************
Script:
--
/Users/jkorous/src/llvm/build/bin/llvm-go go=/usr/local/bin/go test llvm.org/llvm/bindings/go/llvm
--
Exit Code: 1

Command Output (stdout):
--
FAIL    llvm.org/llvm/bindings/go/llvm [build failed]

--
Command Output (stderr):
--
# llvm.org/llvm/bindings/go/llvm
In file included from /var/folders/_n/pwscsy_52cbdx6xt6f5g___00000gr/T/lit_tmp_eN_BLp/gopath309735686/src/llvm.org/llvm/bindings/go/llvm/analysis.go:17:
In file included from /Users/jkorous/src/llvm/src/include/llvm-c/Analysis.h:22:
In file included from /Users/jkorous/src/llvm/src/include/llvm-c/Types.h:17:
/Users/jkorous/src/llvm/src/include/llvm-c/DataTypes.h:30:10: fatal error: 'math.h' file not found
#include <math.h>
         ^~~~~~~~
1 error generated.

--

********************

**Comment by arsenm** [comment]
Old build issue
