### ISSUE TITLE
clang-format doesn't indent {} block when format is set to llvm.

### ISSUE THREAD

**Issue by MiraiHattori** [llvm/llvm-project#36791]
|  |  |
| --- | --- |
| Bugzilla Link | [37443](https://llvm.org/bz37443) |
| Version | 5.0 |
| OS | Linux |
| CC | @MiraiHattori |

## Extended Description 
This occurs clang-format version 3.8 and upper.
When .clang-format is
BasedOnStyle: LLVM
Standard: Cpp11

ColumnLimit: 0
IndentWidth: 4
UseTab: Never
MaxEmptyLinesToKeep: 2

BreakBeforeBinaryOperators: All
BreakBeforeBraces: Linux
AlignAfterOpenBracket: false
SpaceBeforeParens: ControlStatements
AlwaysBreakTemplateDeclarations: true
AlignEscapedNewlinesLeft: true
PointerAlignment: Left
AccessModifierOffset: -4
AllowShortFunctionsOnASingleLine: All
SortIncludes: false
SortUsingDeclarations: false

SpacesBeforeTrailingComments: 2
CommentPragmas: '[!\*]'

and the source file is 

```cpp
void sayHello()
{
    {// Hoge and Fuga
        {// Hoge
            Hoge::sayHoge();
        }
        {  // Fuga
            Fuga::sayFuga();
        }
    }
    {  // Foo and Bar
        {  // Foo
            Foo::sayFoo();
        }
        {  // Bar
            Bar::sayBar();
        }
    }
}

int main()
{
    sayHello();
}
```
then clang-format-3.8 or upper version cannot indent the source properly.

Which is, 
```cpp
void sayHello()
{
    {    // Hoge and Fuga
        {// Hoge
            Hoge::sayHoge();
}
{  // Fuga
    Fuga::sayFuga();
}
}
{      // Foo and Bar
    {  // Foo
        Foo::sayFoo();
    }
    {  // Bar
        Bar::sayBar();
    }
}
}

int main()
{
    sayHello();
}
```

**Comment by rymiel** [comment]
Duplicate of https://github.com/llvm/llvm-project/issues/33891
