### ISSUE TITLE
crash at conditional operator with builtins returning void

### ISSUE THREAD

**Issue by TabbyBelka** [llvm/llvm-project#36899]
|  |  |
| --- | --- |
| Bugzilla Link | [37551](https://llvm.org/bz37551) |
| Version | trunk |
| OS | Linux |
| Attachments | [run test](https://user-images.githubusercontent.com/92601436/143757537-0055ec90-40b8-4e5d-81f0-0d58e6668371.gz) |

## Extended Description 

Originally clang crashed at inputmethod package from tizen(inputmethod.cpp)
But I reduced it to:

void get(void* g) {
    g ? __builtin_prefetch(g, 0, 1) : __builtin_prefetch(g, 0, 1);
}

and found a reason.

In ScalarExprEmitter::VisitAbstractConditionalOperator from CGExprScalar.cpp phi instruction with void type is created. In case not-builtin function call LHS or RHS are null and the instruction isn't created. But in case of builtin functions the LHS is a void type llvm::Value created in CodeGenFunction::EmitBuiltinExpr from CGBuiltin.cpp.

I think it's necessary to check builtins with void return type and replace return expressions with null in CodeGenFunction::EmitBuiltinExpr.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 16: https://godbolt.org/z/989PfcWs3
