### ISSUE TITLE
Clang hangs when compiling the attached code sample

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36910]
|  |  |
| --- | --- |
| Bugzilla Link | [37562](https://llvm.org/bz37562) |
| Version | 6.0 |
| OS | Windows NT |
| Attachments | [clang hangs when compiling this file](https://user-images.githubusercontent.com/60944935/143757540-09f30829-002c-4b01-ae35-a891a6e35157.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Clang hangs when compiling the attached code sample. If the trailing return type is removed from the lambda it works fine.

**Comment by cor3ntin** [comment]
Seems to have been fixed https://compiler-explorer.com/z/Pb1hhzG1b
