### ISSUE TITLE
Memory Region command causes segfault

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36925]
|  |  |
| --- | --- |
| Bugzilla Link | [37577](https://llvm.org/bz37577) |
| Version | unspecified |
| OS | MacOS X |
| Attachments | [Screenshot of it](https://user-images.githubusercontent.com/60944935/143757548-104dbd70-52f7-4939-a088-06dae5847070.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @Teemperor |

## Extended Description 

(* This is lldb lldb-902.0.79.2\n Swift-4.1 *)

When using `memory region` command twice, there is a segmentation fault. Steps as follows:

$lldb ./test_program
(lldb) process launch --stop-at-entry
(lldb) ni
(lldb) ni
(lldb) register read rsp
     rsp = 0x00007ffeefbff5c8
(lldb) memory region 0x00007ffeefbff5c8
(lldb) memory region

Note the last memory region line I do not pass an address to. Should show the help screen again. 

Thank you
Max

**Comment by DavidSpickett** [comment]
Might have been an issue then but it works now with a simple check and I know there are tests that do this in the test suite. Closing.

**Comment by DavidSpickett** [comment]
I keep forgetting to use "close as not planned" instead, apologies.

**Comment by Endilll** [comment]
No worries, it takes a bit of time to get used to our workflow.
If you stumble upon old issue that is still relevant, don't forget to label it `confirmed`.
In any case, I'm keeping an eye on old bug activity through #github channel on Discord.
