### ISSUE TITLE
Dynamic linking: undefined references when linking libLTO.so

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36939]
|  |  |
| --- | --- |
| Bugzilla Link | [37591](https://llvm.org/bz37591) |
| Version | 6.0 |
| OS | Solaris |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I'm building on Solaris 10 / sparcv9, though I suspect this isn't solaris or sparc specific.

I built with the following:

    cmake ../src/llvm \
    -DCMAKE_C_COMPILER=gcc-7.2.0 \
    -DCMAKE_CXX_COMPILER=g++-7.2.0 \
    -DGCC_INSTALL_PREFIX=$(dirname $(dirname $(which gcc-7.2.0))) \
    -DBUILD_SHARED_LIBS=ON \
    -DLINK_LLVM_DYLIB=ON \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo
    
    make -j32

I'll explain why I built using those options in a separate comment.

When linking libLTO.so it fails with undefined references to the following:

    LLVMDisasmDispose
    LLVMCreateDisasmCPU
    LLVMCreateDisasm
    LLVMDisasmInstruction
    LLVMSetDisasmOptions

If I remove those entries from tools/lto/lto.exports then it links fine.

**Comment by arsenm** [comment]
Old build issue
