### ISSUE TITLE
Non-type `auto` function template parameter does not mangle on Windows

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#36937]
|  |  |
| --- | --- |
| Bugzilla Link | [37589](https://llvm.org/bz37589) |
| Version | trunk |
| OS | Windows NT |

## Extended Description 
The following program fails to compile:

template<auto value>
void f() {}

int main() {
    f<0>();
    f<0L>();
}

With this command:

clang++ -std=c++17 file.cpp -o /dev/null

Giving this output:

file.cpp:2:6: error: definition with same mangled name as another definition
void f() {}
     ^
file.cpp:2:6: note: previous definition is here
1 error generated.

You see the same problem for this code:

template<auto value>
struct s {
    static void f() {}
};

int main() {
    s<0>::f();
    s<0L>::f();
}

**Comment by xgupta** [comment]
Fixed in the latest trunk - https://godbolt.org/z/qzTfvPfqq.
