### ISSUE TITLE
xlocale.h not found

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36944]
|  |  |
| --- | --- |
| Bugzilla Link | [37596](https://llvm.org/bz37596) |
| Version | 6.0 |
| OS | Solaris |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow,@zygoloid |

## Extended Description 
Building on Solaris 10 / sparcv9 hardware:

    cmake ../src/llvm \
    -DCMAKE_C_COMPILER=gcc-7.2.0 \
    -DCMAKE_CXX_COMPILER=g++-7.2.0 \
    -DGCC_INSTALL_PREFIX=$(dirname $(dirname $(which gcc-7.2.0))) \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo
    
    make -j32

... with libcxx/libcxxabi un-tarred & appropriately renamed in ../src/llvm/projects.

I get the following compile error:

    In file included from (...)/projects/libcxx/include/ios:216:0,
                     from (...)/projects/libcxx/include/ostream:138,
                     from (...)/projects/libcxx/include/istream:163,
                     from (...)/projects/libcxx/include/rnadom:1646,
                     from (...)/projects/libcxx/src/algorithm.cpp:11:
    (...)/projects/libcxx/include/__locale:33:11: fatal error: xlocale.h: No such file or directory

**Comment by philnik777** [comment]
We've removed solaris support, so this isn't relevant anymore.
