### ISSUE TITLE
math.h conflicting noexcept declaration

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36945]
|  |  |
| --- | --- |
| Bugzilla Link | [37597](https://llvm.org/bz37597) |
| Version | 6.0 |
| OS | Solaris |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@mclow |

## Extended Description 
Building on Solaris 10 / sparcv9 hardware:

    cmake ../src/llvm \
    -DCMAKE_C_COMPILER=gcc-7.2.0 \
    -DCMAKE_CXX_COMPILER=g++-7.2.0 \
    -DGCC_INSTALL_PREFIX=$(dirname $(dirname $(which gcc-7.2.0))) \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo
    
    make -j32

I get the following compile error:

    In file included from (...)/projects/libcxx/src/debug.cpp:10:0:
    (...)/projects/libcxx/include/math.h: In function 'float acosh(float)':
    (...)/projects/libcxx/include/__config:776:21: error: 'float acosh(float)' conflicts with a previous declaration
     #  define _NOEXCEPT noexcept
                         ^
    (...)/projects/libcxx/include/math.h:1038:68: note: in expansion of macro '_NOEXCEPT'
     inline _LIBCPP_INLINE_VISIBILITY float       acosh(float __lcpp_x) _NOEXCEPT       {return ::acoshf(__lcpp_x);}
                                                                        ^~~~~~~~~

... for 34 functions declared in math.h:

acosh, asinh, atanh, cbrt, copysign, erf, erfc, exp2, expm1, fdim, fma, fmax, fmin, hypot, ilogb, lgamma, llrint, llround, log1p, log2, logb, lrint, lround, nearbyint, nextafter, nexttoward, remainder, remquo, rint, round, scalbln, scalbn, tgamma, trunc

**Comment by philnik777** [comment]
AFAICT this isn't relevant anymore.
