### ISSUE TITLE
error: cannot inherit constructors from const T

### ISSUE THREAD

**Issue by 74e05505-0864-4670-ace4-5363b70c21c0** [llvm/llvm-project#36948]
|  |  |
| --- | --- |
| Bugzilla Link | [37600](https://llvm.org/bz37600) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@hfinkel,@zygoloid |

## Extended Description 
Consider the following example:

struct A {};
using T = const A;
struct B : T {
    using T::T; // error: 'const A' is not a direct base of 'B'
};
int main() {
    B b;
}

The code compiles in GCC and VC14.1 but not in Clang (any version).

Obviously T must name a class for 'using T::T' to work ([class.qual]/2.2), so according to [class.name]/5 'const' should be ignored.

In addition, the error makes no sense - how can 'const A' be a class at all?

**Comment by JOE1994** [comment]
OP's code compiles without errors with `clang 18.1.0`
* https://godbolt.org/z/YT4b8Yq8c
