### ISSUE TITLE
clang.exe: error: clang frontend command failed due to signal (use -v to see invocation)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36967]
|  |  |
| --- | --- |
| Bugzilla Link | [37619](https://llvm.org/bz37619) |
| Version | 6.0 |
| OS | Windows NT |
| Attachments | [Preprocessed source file](https://user-images.githubusercontent.com/60944935/143757563-c8f09e85-bcdc-4f3a-a835-cc78333ecd93.gz), [.sh file](https://user-images.githubusercontent.com/60944935/143757564-6a8dc5d7-a67c-4491-a215-4c53bb860d21.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 

C++11.
The attached code uses function templates with auto return type to populate an integer_sequence. Causes clang to crash.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 10: https://godbolt.org/z/41nvT1r3d
