### ISSUE TITLE
shared_ptr cannot be constructed with a move-only deleter

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36985]
|  |  |
| --- | --- |
| Bugzilla Link | [37637](https://llvm.org/bz37637) |
| Version | 5.0 |
| OS | Linux |
| Attachments | [Sample file that demonstrates the bug](https://user-images.githubusercontent.com/60944935/143757574-34bf376f-2fbc-4a13-a16e-5ebaf4570b20.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 

Compiling the attached file with the below command fails with the error message below. This should work, as per [util.smartptr.shared.const]p9/13

Compilation succeeds as expected with -stdlib=libstdc++

clang++-5.0 -std=c++17 -stdlib=libc++ move-only-deleter.cpp 

In file included from move-only-deleter.cpp:1:
/usr/include/c++/v1/memory:3981:39: error: call to deleted constructor of 'Deleter'
        __cntrl_ = new _CntrlBlk(__p, __d, _AllocT());
                                      ^~~
move-only-deleter.cpp:17:5: note: in instantiation of function template specialization 'std::__1::shared_ptr<int>::shared_ptr<int, Deleter>' requested here
    std::shared_ptr<int>(new int,Deleter());
    ^
move-only-deleter.cpp:6:5: note: 'Deleter' has been explicitly marked deleted here
    Deleter(Deleter const&)=delete;
    ^
/usr/include/c++/v1/memory:3507:39: note: passing argument to parameter '__d' here
    __shared_ptr_pointer(_Tp __p, _Dp __d, _Alloc __a)
                                      ^
1 error generated.

**Comment by philnik777** [comment]
This has been implemented in libc++13.
