### ISSUE TITLE
"Instruction does not dominate all uses" with opt -disable-basicaa -loop-versioning

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#36998]
|  |  |
| --- | --- |
| Bugzilla Link | [37650](https://llvm.org/bz37650) |
| Version | unspecified |
| OS | Linux |
| Attachments | [reproducer](https://user-images.githubusercontent.com/55733087/143757583-daba1cab-fdab-4d25-9ab1-724068c68938.gz) |

## Extended Description 

opt -S -o - bbi-14805.ll -disable-basicaa -loop-versioning

gives

Instruction does not dominate all uses!
  %inc = add nsw i16 undef, 1
  store i16 %inc, i16* @&#8203;c, align 1
LLVM ERROR: Broken function found, compilation aborted!

Found when running random passes/flags on random input. We don't normally use -disable-basicaa -loop-versioning.

This happens also with some old opt binary built in Nov 2016.

**Comment by fhahn** [comment]
Still reproduces with ` -passes=loop-versioning -aa-pipeline=''`: https://clang.godbolt.org/z/xMKo5P989

**Comment by VedantParanjape** [comment]
> Still reproduces with ` -passes=loop-versioning -aa-pipeline=''`: https://clang.godbolt.org/z/xMKo5P989

The IR ins't in LCSSA form, in the critical edge, store uses inc which is a value defined inside the loop.

**Comment by VedantParanjape** [comment]
I have pushed a fix for this, thanks (cc: @fhahn and @aeubanks) (https://github.com/llvm/llvm-project/pull/116443)

Thanks,
Vedant
