### ISSUE TITLE
Broken links in Kaleidoscope tutorial

### ISSUE THREAD

**Issue by obiwanjacobi** [llvm/llvm-project#37]
Doing the tutorial and I noticed a lot of links are not working.

For instance on this page: https://llvm.org/docs/tutorial/MyFirstLanguageFrontend/LangImpl03.html
all links to the language reference are pointing within the tutorial folder: `https://llvm.org/docs/tutorial/LangRef.html#linkage`, which should be `https://llvm.org/docs/LangRef.html#linkage`

**Comment by modocache** [comment]
I see, yes. The Kaleidoscope tutorial was moved into its own directory in d80f118e523a, but the tutorial pages use relative links to point to the language reference, such as `../LangRef.html#instruction-reference` here: https://github.com/llvm-mirror/llvm/blame/2c4ca6832fa6b306ee6a7010bfb80a3f2596f824/docs/tutorial/MyFirstLanguageFrontend/LangImpl03.rst#L201

I think the fix would be to find-and-replace all `../` link paths in `llvm/docs/tutorial/MyFirstLanguageFrontend` with `../../`, to account for the additional nesting. I'll try doing so.

**Comment by modocache** [comment]
Oops, I just pulled, and it looks like this has been fixed already in 2916489c54a3. The website just needs to be updated. I don't know how to do that, though 😅

**Comment by obiwanjacobi** [comment]
There are also  a couple of links that link to other pages that do not use the leading zero.
For instance on page: https://llvm.org/docs/tutorial/MyFirstLanguageFrontend/LangImpl02.html

There is a link ' later in the tutorial. ' that links to `https://llvm.org/docs/tutorial/MyFirstLanguageFrontend/LangImpl6.html#user-defined-unary-operators` that should be LangImpl**0**6.html.

Perhaps also search for LangImpl?.html

**Comment by arsenm** [comment]
All these links look like they work to me
