### ISSUE TITLE
[mips] GCC 4.9.2 and later miscompiles LLVM

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37049]
|  |  |
| --- | --- |
| Bugzilla Link | [37701](https://llvm.org/bz37701) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @atanasyan |

## Extended Description 
LLVM since r330024 has been miscompiled by GCC 4.9.2 or later for MIPS. The issue occurs when LLVM is compiled with PIC and optimizations (01+).

The problem is that GCC's implementation of shrink wrapping can move the prologue past a branch instruction which is later expanded into a long jump. To fetch the address of the target, the long branch sequence fetches the GOT pointer from it's spill slot on the stack to load the address of the indirect branch target. However the prologue is responsible for spilling the GOT pointer to the stack.

This results in a indirect jump with to an uninitialized value, detectable with valgrind. Some setups may somehow get the correct behaviour, others will get incoherent stack traces upon crashing. At this point in time, it appears to affect only the AArch64 backend for LLVM with a MIPS host.

There are number of workarounds such as compiling at -O0, disabling PIC or disabling shrink-wrapping (-fno-shrink-wrap).

This issue affects multiple versions of GCC from 4.9.2 onwards. GCC bug filed as https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86069

**Comment by fhahn** [comment]
This sounds like a bug in GCC and nothing to fix in LLVM. Closing, but please re-open with additional info if that's incorrect.
