### ISSUE TITLE
Remove trailing semicolon after function body

### ISSUE THREAD

**Issue by 609891af-0bfb-45ba-b351-d60ffb163ae5** [llvm/llvm-project#37066]
|  |  |
| --- | --- |
| Bugzilla Link | [37718](https://llvm.org/bz37718) |
| Version | unspecified |
| OS | Linux |
| CC | @EugeneZelenko |

## Extended Description 
I have a C file with function like this

```
void foo(void) {
};
```

Semicolon after the function body is unneeded. I want to remove this informational noise. But I do not see such option in clang-format tool.

Please add an option to remove semicolons after the C function body.

**Comment by mydeveloperday** [comment]
I'm going to close this as I don't think we'll fix this just in case we identify the wrong ';' often there isn't much reference to it being for the function so I don't think we could do this reliably, being realistic there are better ways via warnings.

**Comment by mydeveloperday** [comment]
Feel free to open should you decide you want to submit a patch for us to consider
