### ISSUE TITLE
Clang compiler failed with error for the test with sum of variables declared with "constexpr __attribute__((vector_size()))"

### ISSUE THREAD

**Issue by smanna12** [llvm/llvm-project#37087]
|  |  |
| --- | --- |
| Bugzilla Link | [37739](https://llvm.org/bz37739) |
| Version | 6.0 |
| OS | Windows NT |
| CC | @DougGregor,@erichkeane |

## Extended Description 
-bash-4.2$ clang  -c -std=c++11 test.cpp
test.cpp:3:21: error: constexpr variable 's' must be initialized by a constant expression
constexpr vec s = v + v;
                  ~~^~~
1 error generated.

-bash-4.2$ cat test.cpp
typedef long vec __attribute__((vector_size (2 * sizeof (long))));
constexpr vec v = { 3, 4 };
constexpr vec s = v + v;

Clang doesn't consider sum of two variables of type "constexpr long __attribute__((vector_size (2 * sizeof (long))))" as constant expression. 

If I change "constexpr vec s" to just "vec s" this test will pass. 

GCC compiles the test without any error.

**Comment by wheatman** [comment]
This seems to have been fixed between 10.0.1 and 11.0.0
https://godbolt.org/z/1qMr36jjW

For reference

code 
```
int main() {typedef long vec __attribute__((vector_size (2 * sizeof (long))));
constexpr vec v = { 3, 4 };
constexpr vec s = v + v;
}
```
