### ISSUE TITLE
[SelectionDAG] Generalise SelectionDAG::computeOverflowKind to support other opcodes

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#37109]
|  |  |
| --- | --- |
| Bugzilla Link | [37761](https://llvm.org/bz37761) |
| Version | trunk |
| OS | Windows NT |
| CC | @deadalnix,@LebedevRI,@rotateright |

## Extended Description 
SelectionDAG::computeOverflowKind is currently only to be used for additions; it'd be useful for it to also handle signed/unsigned ISD::SUB and ISD::MUL (to cover all the SADDO/UADD, SSUBO/USUBO and SMULO/UMULO nodes).

**Comment by RKSimon** [comment]
This has now been split into:
```c
computeOverflowForSignedAdd
computeOverflowForUnsignedAdd
computeOverflowForSignedSub
computeOverflowForUnsignedSub
```
These more closely match the InstCombine methods, so we're just missing:
```c
computeOverflowForSignedMul
computeOverflowForUnsignedMul
```
It might be useful to add similar helpers to detect exact shifts.

**Comment by elhewaty** [comment]
I will work on this

**Comment by elhewaty** [comment]
Candidate Patch: https://reviews.llvm.org/D159406

**Comment by RKSimon** [comment]
We also need to extend the computeOverflowForSignedSub/computeOverflowForUnsignedSub implementations with ConstantRange - I think this will mainly involve adding test coverage.

**Comment by elhewaty** [comment]
OK, I am working on it now

**Comment by RKSimon** [comment]
computeOverflowForSignedMul
computeOverflowForUnsignedMul
Additional Tests:  e086e0aeef6be3b1b3b403e54fbe2669c649973d
Fixed: 741c1278175b9354442cd2143e1452714dc020a2

**Comment by elhewaty** [comment]
@RKSimon Candidate pull: https://github.com/llvm/llvm-project/pull/67724

**Comment by elhewaty** [comment]
@RKSimon Here is the new pull : https://github.com/llvm/llvm-project/pull/67890

**Comment by RKSimon** [comment]
Closing this - the computeOverflow implementations are in place, we can create smaller issues for any specifics we're still missing.
