### ISSUE TITLE
`mayReadOrWriteMemory` method behaviour in `Instruction` class

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37104]
|  |  |
| --- | --- |
| Bugzilla Link | [37756](https://llvm.org/bz37756) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @arsenm |

## Extended Description 
Hello,

In the comment to `mayReadOrWriteMemory` method [1] said that it resurns "true if this instruction may read or write memory".

Unfortunatelly, if we check both `mayWriteToMemory` and `mayReadFromMemory` methods [2, 3], they do not check opcode Alloca.
But in language reference said that "the `alloca` instruction allocates sizeof(<type>)*NumElements bytes of memory on the runtime stack" [4]. Thus, it is possible to say in other words, that `alloca` instruction modifies memory, as said in the comment to `mayWriteToMemory` method, and I think this should be checked in that method.

Or do I understand incorrectly the logic behind `mayReadOrWriteMemory` method?

Thank you,
Petr.

[1] https://github.com/llvm-mirror/llvm/blob/master/include/llvm/IR/Instruction.h#L496L498
[2] https://github.com/llvm-mirror/llvm/blob/master/lib/IR/Instruction.cpp#L523L541
[3] https://github.com/llvm-mirror/llvm/blob/master/lib/IR/Instruction.cpp#L503L521
[4] https://llvm.org/docs/LangRef.html#alloca-instruction

**Comment by arsenm** [comment]
alloca does not modify memory, it only allocates it
