### ISSUE TITLE
Assertion `StartColNo <= EndColNo && "Invalid range!"' failed

### ISSUE THREAD

**Issue by compnerd** [llvm/llvm-project#37113]
|  |  |
| --- | --- |
| Bugzilla Link | [37765](https://llvm.org/bz37765) |
| Version | trunk |
| OS | All |

## Extended Description 
bin/clang -cc1 -triple armv7-apple-ios6.0 -fobjc-runtime=ios-6.0 -fsyntax-only -x objective-c - -o -
@&#8203;class I;
@&#8203;class J<__covariant T>;
void f(J<__kindof I> *) {}

**Comment by Endilll** [comment]
Fixed in Clang 5
https://godbolt.org/z/h71GEePe6
