### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37147]
|  |  |
| --- | --- |
| Bugzilla Link | [37799](https://llvm.org/bz37799) |
| Version | trunk |
| OS | Linux |
| Attachments | [repro .sh](https://user-images.githubusercontent.com/60944935/143757638-da0b4431-b386-4c38-8172-65c1977e6e3e.gz), [repro .cpp](https://user-images.githubusercontent.com/60944935/143757639-e960281f-0f26-40fc-ae82-41fe71a5973c.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@DougGregor |

## Extended Description 

1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module '../../third_party/blink/renderer/platform/wtf/text/string_concatenate.cc'.
4.      Running pass 'PBQP Register Allocator' on function '@_ZNK3WTF17StringTypeAdapterIPcE7WriteToEPh'
#&#8203;0 0x0000000001fe7634 (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x1fe7634)
#&#8203;1 0x0000000001fe560e llvm::sys::RunSignalHandlers() (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x1fe560e)
#&#8203;2 0x0000000001fe77f2 (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x1fe77f2)
#&#8203;3 0x00007fa25e7c20c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x110c0)
#&#8203;4 0x00007fa25d57dfcf gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x32fcf)
#&#8203;5 0x00007fa25d57f3fa abort (/lib/x86_64-linux-gnu/libc.so.6+0x343fa)
#&#8203;6 0x00007fa25d576e37 (/lib/x86_64-linux-gnu/libc.so.6+0x2be37)
#&#8203;7 0x00007fa25d576ee2 (/lib/x86_64-linux-gnu/libc.so.6+0x2bee2)
#&#8203;8 0x00000000009ada66 (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x9ada66)
#&#8203;9 0x00000000019082fc llvm::VirtRegAuxInfo::weightCalcHelper(llvm::LiveInterval&, llvm::SlotIndex*, llvm::SlotIndex*) (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x19082fc)
#&#8203;10 0x000000000190762c llvm::calculateSpillWeightsAndHints(llvm::LiveIntervals&, llvm::MachineFunction&, llvm::VirtRegMap*, llvm::MachineLoopInfo const&, llvm::MachineBlockFrequencyInfo const&, float (*)(float, unsigned int, unsigned int)) (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x190762c)
#&#8203;11 0x00000000018442ec (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x18442ec)
#&#8203;12 0x0000000001772238 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x1772238)
#&#8203;13 0x0000000001ac6286 llvm::FPPassManager::runOnFunction(llvm::Function&) (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x1ac6286)
#&#8203;14 0x0000000001ac6568 llvm::FPPassManager::runOnModule(llvm::Module&) (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x1ac6568)
#&#8203;15 0x0000000001ac6aef llvm::legacy::PassManagerImpl::run(llvm::Module&) (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x1ac6aef)
#&#8203;16 0x00000000021ac6af clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x21ac6af)
#&#8203;17 0x00000000029ad703 (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x29ad703)
#&#8203;18 0x000000000266503c clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x266503c)
#&#8203;19 0x0000000003182814 clang::ParseAST(clang::Sema&, bool, bool) (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x3182814)
#&#8203;20 0x0000000002638830 clang::FrontendAction::Execute() (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x2638830)
#&#8203;21 0x00000000025e2331 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x25e2331)
#&#8203;22 0x00000000026d2cd9 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x26d2cd9)
#&#8203;23 0x00000000008af323 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x8af323)
#&#8203;24 0x00000000008acc4f main (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x8acc4f)
#&#8203;25 0x00007fa25d56b2b1 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b1)
#&#8203;26 0x00000000008a9d1d _start (../../third_party/llvm-build/Release+Asserts/bin/clang+++0x8a9d1d)
clang++: error: unable to execute command: Aborted
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 7.0.0 (trunk 332838)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: ../../third_party/llvm-build/Release+Asserts/bin
clang++: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg:

**Comment by arsenm** [comment]
I'm unable to reproduce. The attached testcase isn't fully self contained and uses plugins. I tried preserving as many of the flags as I could and haven't found the crash.

**Comment by arsenm** [comment]
[driver.sh.txt](https://github.com/llvm/llvm-project/files/12297050/driver.sh.txt)
