### ISSUE TITLE
Misuse of _Noreturn in a struct member not diagnosed

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37157]
|  |  |
| --- | --- |
| Bugzilla Link | [37809](https://llvm.org/bz37809) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
clang fails to diagnose the following misuse of _Noreturn:
--------------------
struct S {
    _Noreturn int v;
};

**Comment by tbaederr** [comment]
I'm gonna mark this fixed since clang diagnoses this today: https://godbolt.org/z/rhhGh91Tv
