### ISSUE TITLE
[coroutines] Miscompile at -O0 if allocation routine depends on function arguments

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37153]
|  |  |
| --- | --- |
| Bugzilla Link | [37805](https://llvm.org/bz37805) |
| Version | trunk |
| OS | Linux |
| Attachments | [a reduced repro](https://user-images.githubusercontent.com/60944935/143757640-cd93592f-7a3a-479c-8a25-b6d586a92081.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Repro: compile and attached program with:

./clang++ -fcoroutines-ts -stdlib=libc++ efat.cpp -std=c++2a -O2 && ./a.out

Observe that expected output printed:

0x7ffc94e61590:512
allocated from mem pointer (noimpl) 24 0x7ffc94e61590:512
1
2
delete does nothing

./clang++ -fcoroutines-ts -stdlib=libc++ efat.cpp -std=c++2a && ./a.out

0x7ffe518011e8:512
allocated from mem pointer (noimpl) 312 0x401f6d:140730265768424
Segmentation fault (core dumped)

What happens is that MemPtr struct that carries the Buf,Len pair is not observed correctly by the operator new.

It happens because the code in CoroSplit pass that moves stores of arguments into allocas to beyond coro.begin is getting confused with MemPtr struct that is coerced to be passed in registers.

We need to rethink how we deal with relocation of store in CoroSplit to make this code more robust.

**Comment by adrianimboden** [comment]
https://godbolt.org/z/ccb53a9jz

this is no longer reproducible.

**Comment by ChuanqiXu9** [comment]
Fixed in trunk.
