### ISSUE TITLE
OpenMP missing in Clang 6.0

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37151]
|  |  |
| --- | --- |
| Bugzilla Link | [37803](https://llvm.org/bz37803) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hahnjo,@zmodem,@jprotze |

## Extended Description 
It seems OpenMP header (omp.h) as well as libomp.lib/dll are missing in the newest Clang version. They are available in Clang 5.0.2

I am sorry if this is expected but I couldn't find a mention about OpenMP removal from Windows distribution and it's important component of the C compiler.

**Comment by sylvestre** [comment]
fixed now
