### ISSUE TITLE
readability-avoid-const-params-in-decls false positive for friend function in class templates

### ISSUE THREAD

**Issue by pepsiman** [llvm/llvm-project#37160]
|  |  |
| --- | --- |
| Bugzilla Link | [37812](https://llvm.org/bz37812) |
| Version | unspecified |
| OS | Linux |
| CC | @EugeneZelenko |

## Extended Description 
+++ This bug was initially created as a clone of Bug #&#8203;30398 +++

$ cat t.cpp 
template <typename Int> class A {
  Int i;

public:
  friend bool operator==(const A &a, const Int i) { return a.i == i; }
};

A<int> a;

$ clang-tidy-7 --checks=-*,readability-avoid-const-params* t.cpp --
1 warning generated.
t.cpp:5:38: warning: parameter 'i' is const-qualified in the function declaration; const-qualification of parameters only has an effect in function definitions [readability-avoid-const-params-in-decls]
  friend bool operator==(const A &a, const Int i) { return a.i == i; }
                                     ^~~~~~~~~~

$ apt-cache policy clang-tidy-7 
clang-tidy-7:
  Installed: 1:7~svn334732-1~exp1+0~20180614164228.316~1.gbp76c9a0

**Comment by PiotrZSL** [comment]
Not reproduced on LLVM-17 (main). It that to be some fix in Clang itself, because check didn't change much, and always used "unless(isDefinition())".

**Comment by pepsiman** [comment]
Might have been ca4485d9fc3449f7bb9522ee16ccf63f2219732c.
