### ISSUE TITLE
opt crashes with "opt -gvn -jump-threading -indvars" while running pass 'Induction Variable Simplification'

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#37175]
|  |  |
| --- | --- |
| Bugzilla Link | [37827](https://llvm.org/bz37827) |
| Version | trunk |
| OS | All |
| Attachments | [crash triggering LLVM IR](https://user-images.githubusercontent.com/95090394/143757650-983f70a2-c0a4-4057-a274-d82aad282fc1.gz) |

## Extended Description 

Tested with trunk revision 334906. 

$ clangpolly -v
clang version 7.0.0 (http://llvm.org/git/clang.git c36069cffc57a30a20782bf327a87bed4e48a6c2) (http://llvm.org/git/llvm.git 59cb663e72874dda740aa2b18bf47ba65b32fe9b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clangpolly -O0 -w small.c; ./a.out
$ 
$ clangpolly -O3 -mllvm -disable-llvm-optzns -w -c -emit-llvm -o small.bc small.c
$ optpolly -gvn -jump-threading -indvars -o small-opt.bc small.bc
Stack dump:
0.	Program arguments: optpolly -gvn -jump-threading -indvars -o small-opt.bc small.bc 
1.	Running pass 'Function Pass Manager' on module 'small.bc'.
2.	Running pass 'Loop Pass Manager' on function '@f'
3.	Running pass 'Induction Variable Simplification' on basic block '%for.cond'
LLVMSymbolizer: error reading file: No such file or directory
#&#8203;0 0x00000000020eebca (optpolly+0x20eebca)
#&#8203;1 0x00000000020ed1cc (optpolly+0x20ed1cc)
#&#8203;2 0x00000000020ed337 (optpolly+0x20ed337)
#&#8203;3 0x00007f40d95cc390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
#&#8203;4 0x0000000001ac26b4 (optpolly+0x1ac26b4)
#&#8203;5 0x0000000001ef7824 (optpolly+0x1ef7824)
#&#8203;6 0x0000000001ef7aa3 (optpolly+0x1ef7aa3)
#&#8203;7 0x0000000001ef88dd (optpolly+0x1ef88dd)
#&#8203;8 0x0000000001efbc43 (optpolly+0x1efbc43)
#&#8203;9 0x0000000001efd615 (optpolly+0x1efd615)
#&#8203;10 0x0000000001eff9b1 (optpolly+0x1eff9b1)
#&#8203;11 0x0000000001635c4f (optpolly+0x1635c4f)
#&#8203;12 0x0000000001b93493 (optpolly+0x1b93493)
#&#8203;13 0x0000000001b9356c (optpolly+0x1b9356c)
#&#8203;14 0x0000000001b9303d (optpolly+0x1b9303d)
#&#8203;15 0x00000000007bfca8 (optpolly+0x7bfca8)
#&#8203;16 0x00007f40d8329830 __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:325:0
#&#8203;17 0x000000000084fd89 (optpolly+0x84fd89)
Segmentation fault (core dumped)
$ 

--------------------------------

int a, b[3], c, d;

void f ()
{
  for (; d < 1; d++)
    {
      b[d + 2];
      for (c = 0; c == 1; c++)
	while (a)
	  (d || 0, d + 2);
    }
}

int main ()
{
  f ();
  return 0;
}

**Comment by fhahn** [comment]
I am unable to reproduce this crash, so it likely has been fixed. Please re-open the issue with additional info if it still reproduces on your end.
