### ISSUE TITLE
wrong code with "opt -loop-rotate -licm -indvars -loop-vectorize -gvn"

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#37173]
|  |  |
| --- | --- |
| Bugzilla Link | [37825](https://llvm.org/bz37825) |
| Version | trunk |
| OS | All |
| Attachments | [LLVM IR triggering the wrong code](https://user-images.githubusercontent.com/95090394/143757649-7fad5cd3-f872-40d9-9628-cc25716d0d86.gz) |
| CC | @fhahn,@hfinkel |

## Extended Description 

Tested with trunk revision 334906. 

$ clangpolly -v
clang version 7.0.0 (http://llvm.org/git/clang.git c36069cffc57a30a20782bf327a87bed4e48a6c2) (http://llvm.org/git/llvm.git 59cb663e72874dda740aa2b18bf47ba65b32fe9b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clangpolly -O0 small.c; ./a.out
$ 
$ clangpolly -O3 -mllvm -disable-llvm-optzns -c -emit-llvm -o small.bc small.c
$ optpolly -loop-rotate -licm -indvars -loop-vectorize -gvn -o small-opt.bc small.bc
$ clangpolly small-opt.bc
$ ./a.out
Segmentation fault (core dumped)
$ 

-------------------------------------

int a[9][2], *b[10], **c = &b[5], d;

int main ()
{
  for (; d < 4; d++)
    b[d + 5] = &a[d + 2][1];
  **c = 0;
  return 0;
}

**Comment by fhahn** [comment]
I cannot reproduce the segault on current `main`, so this probably has been fixed. I am closing the issue, but please re-open the issue if it still reproduces on your end.
