### ISSUE TITLE
Segmentation failure with strange errors

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37180]
|  |  |
| --- | --- |
| Bugzilla Link | [37832](https://llvm.org/bz37832) |
| Version | trunk |
| OS | Linux |
| Attachments | [generated by compiler](https://user-images.githubusercontent.com/60944935/143757651-a0587986-e92c-4dc1-a04f-0382e4de9646.gz), [first part of a cpp file](https://user-images.githubusercontent.com/60944935/143757652-a6725c2f-1707-4d23-9cbd-fcbb2bc4d862.gz), [second part of a cpp file](https://user-images.githubusercontent.com/60944935/143757653-567bddd3-cb14-40e4-8e41-5af6cc7e4ed5.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DimitryAndric |

## Extended Description 

Add info in attachments.

**Comment by AaronBallman** [comment]
Closing as not reproducible.
