### ISSUE TITLE
llvm-config 2.4 in MinGW - libpsapi, libimagehlp in wrong order

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#3719]
|  |  |
| --- | --- |
| Bugzilla Link | [3347](https://llvm.org/bz3347) |
| Version | 2.4 |
| OS | Windows XP |
| Attachments | [Corrects order for --libs, may be wrong for --libnames, --libfiles](https://user-images.githubusercontent.com/60944935/143738704-b69d5bd5-ae09-4619-b619-75fd8ea603ec.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 

llvm-config --cxxflags --ldflags --libs core gives:

-I/include  -D_DEBUG  -D_GNU_SOURCE -D__STDC_LIMIT_MACROS -O2
-fomit-frame-pointer  -Woverloaded-virtual
-L/lib  -lpsapi -limagehlp -lm
-lLLVMCore -lLLVMSupport -lLLVMSystem

The -lpsapi -limagehlp need to be at the end for ld to resolve all the symbols correctly. (Probably the -lm too but I didn't experience problems with this).

A patch for llvm-config.in.in is attached which gets things working on MinGW but it's not tested elsewhere.

**Comment by arsenm** [comment]
Old build issue
