### ISSUE TITLE
_Atomic with restrict not accepted

### ISSUE THREAD

**Issue by dbc7d0cf-60de-4ba2-bc9a-c1b7219315df** [llvm/llvm-project#37206]
|  |  |
| --- | --- |
| Bugzilla Link | [37858](https://llvm.org/bz37858) |
| Version | unspecified |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
This one line of code:
static int * _Atomic restrict f13(void){return NULL;}

Gets this error:
 error: restrict requires a pointer or reference ('_Atomic(int *)' is invalid)

Bug 24451 seems related.

**Comment by AaronBallman** [comment]
Duplicate of #24825
