### ISSUE TITLE
Inline asm fails to notify on bad inline asm eventually crashing

### ISSUE THREAD

**Issue by echristo** [llvm/llvm-project#37208]
|  |  |
| --- | --- |
| Bugzilla Link | [37860](https://llvm.org/bz37860) |
| Version | unspecified |
| OS | All |
| CC | @zygoloid |

## Extended Description 
Found via a crash on invalid, there was an inline asm that looked like:

__attribute__((target("avx,avx2,fma"))) void Accumulate(__m256 a, __m256 b,
                                                        __m256 *acc) {

  asm("vfmadd132ps %0 %1 (%2)" : : "r"(a), "r"(b), "r"(acc) :);
}

The somewhat more correct version would look like:

__attribute__((target("avx,avx2,fma"))) void Accumulate(__m256 a, __m256 b,
                                                        __m256 *acc) {

  asm("vfmadd132ps %0,%1,%2" : "+x"(a) : "x"(b), "x"(*acc) :);
}

Filing this bug to get better diagnostics and so I don't forget it.

The register constraints are wrong and we should have identified them, unfortunately the code that looks at that isn't looking at the attributes on the target to make those determinations and so wouldn't identify either them or what's going on in a number of places.

The inline asm checker would have failed even on the correct code because it's using the -msse4.2 command line to do the verification thus thinking that the 'x' constraint corresponds to 128 bits rather than 256 bits.

This means that we need subtarget/verification checking here for target attribute code in addition to the code that verifies for intrinsics so we don't incorrectly warn/error on valid code.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 13: https://godbolt.org/z/3ccxKM1he
