### ISSUE TITLE
crash while building application for ppc64 with O3

### ISSUE THREAD

**Issue by d5bfafaa-05ff-4c34-845c-3d10c8ba0197** [llvm/llvm-project#37204]
|  |  |
| --- | --- |
| Bugzilla Link | [37856](https://llvm.org/bz37856) |
| Version | trunk |
| OS | Linux |
| Attachments | [source](https://user-images.githubusercontent.com/92601298/143757657-27ee2c3e-99b5-4ef3-a6d5-29c452059959.gz), [command line](https://user-images.githubusercontent.com/92601298/143757658-80c06997-1d5e-4915-93f2-6ec459b6f667.gz) |

## Extended Description 

building a firmware application with clang trunk (Ubuntu package 1:7~svn335024-1~exp1+0~20180619072109.325~1.gbp76c9a0)

Stack dump:
0.	Program arguments: /usr/lib/llvm-7/bin/clang -cc1 -triple powerpc64--linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name chip.c -mrelocation-model static -mthread-model posix -mllvm -warn-stack-size=2048 -relaxed-aliasing -fmath-errno -masm-verbose -mconstructor-aliases -ffreestanding -fuse-init-array -target-cpu pwr8 -target-feature -vsx -target-feature -direct-move -target-feature -altivec -target-feature -hard-float -msoft-float -mfloat-abi soft -target-abi elfv1 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -coverage-notes-file /home/joel/dev/skiboot/core/chip.gcno -nostdsysteminc -nobuiltininc -resource-dir /usr/lib/llvm-7/lib/clang/7.0.0 -dependency-file core/chip.d -MT core/chip.o -include /home/joel/dev/skiboot/include/config.h -isystem /usr/lib/llvm-7/lib/clang/7.0.0/include -I /home/joel/dev/skiboot/include -I include -I /home/joel/dev/skiboot/libfdt -I /home/joel/dev/skiboot/libflash -I /home/joel/dev/skiboot/libxz -I /home/joel/dev/skiboot/libc/include -I /home/joel/dev/skiboot -I /home/joel/dev/skiboot/libpore -D __SKIBOOT__ -D BITS_PER_LONG=64 -D HAVE_BIG_ENDIAN -D USE_VALGRIND=1 -O3 -Wjump-misses-init -Wsuggest-attribute=const -Wsuggest-attribute=noreturn -Wstack-usage=1024 -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -Werror-implicit-function-declaration -Wdeclaration-after-statement -Wno-pointer-sign -Wextra -Wno-sign-compare -Wmissing-prototypes -Wmissing-declarations -Wwrite-strings -Wcast-align -Winit-self -Wno-stringop-truncation -Werror -Wno-cast-align -Wno-unused-command-line-argument -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wno-address-of-packed-member -std=gnu11 -fconst-strings -fdebug-compilation-dir /home/joel/dev/skiboot -ferror-limit 19 -fmessage-length 106 -fno-signed-char -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o core/chip.o -x c core/chip.c 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'core/chip.c'.
4.	Running pass 'Linux PPC Assembly Printer' on function '@pir_to_core_id'
#&#8203;0 0x00007efeac0e1d9a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0x8f1d9a)
#&#8203;1 0x00007efeac0e04a4 llvm::sys::RunSignalHandlers() (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0x8f04a4)
#&#8203;2 0x00007efeac0e05e2 (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0x8f05e2)
#&#8203;3 0x00007efeaf6e4890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)
#&#8203;4 0x00007efeadcaa076 (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0x24ba076)
#&#8203;5 0x00007efeadcae61e (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0x24be61e)
#&#8203;6 0x00007efead12d395 llvm::MCELFStreamer::EmitInstToData(llvm::MCInst const&, llvm::MCSubtargetInfo const&) (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0x193d395)
#&#8203;7 0x00007efead13d172 llvm::MCObjectStreamer::EmitInstructionImpl(llvm::MCInst const&, llvm::MCSubtargetInfo const&) (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0x194d172)
#&#8203;8 0x00007efead13d1ab llvm::MCObjectStreamer::EmitInstruction(llvm::MCInst const&, llvm::MCSubtargetInfo const&, bool) (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0x194d1ab)
#&#8203;9 0x00007efeadbd1908 (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0x23e1908)
#&#8203;10 0x00007efeadbd3a33 (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0x23e3a33)
#&#8203;11 0x00007efeac76e930 llvm::AsmPrinter::EmitFunctionBody() (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0xf7e930)
#&#8203;12 0x00007efeadbcd26c (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0x23dd26c)
#&#8203;13 0x00007efeac3a51d0 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0xbb51d0)
#&#8203;14 0x00007efeac1ccc58 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0x9dcc58)
#&#8203;15 0x00007efeac1ccca3 llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0x9dcca3)
#&#8203;16 0x00007efeac1cc457 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/llvm-7/bin/../lib/libLLVM-7.so.1+0x9dc457)
#&#8203;17 0x00005576d46e86da clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/usr/lib/llvm-7/bin/clang+0x4e56da)
#&#8203;18 0x00005576d4ce37e4 (/usr/lib/llvm-7/bin/clang+0xae07e4)
#&#8203;19 0x00005576d537c4d9 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/llvm-7/bin/clang+0x11794d9)
#&#8203;20 0x00005576d4ce2967 clang::CodeGenAction::ExecuteAction() (/usr/lib/llvm-7/bin/clang+0xadf967)
#&#8203;21 0x00005576d4b14486 clang::FrontendAction::Execute() (/usr/lib/llvm-7/bin/clang+0x911486)
#&#8203;22 0x00005576d4adbf2c clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/llvm-7/bin/clang+0x8d8f2c)
#&#8203;23 0x00005576d4bc714b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/llvm-7/bin/clang+0x9c414b)
#&#8203;24 0x00005576d4689e68 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/llvm-7/bin/clang+0x486e68)
#&#8203;25 0x00005576d467799e main (/usr/lib/llvm-7/bin/clang+0x47499e)
#&#8203;26 0x00007efeaa8afb97 __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344:0
#&#8203;27 0x00005576d468771a _start (/usr/lib/llvm-7/bin/clang+0x48471a)
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 7.0.0- (trunk)
Target: powerpc64--linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by Endilll** [comment]
Appears to be fixed in Clang 10.
Reduced by C-Reduce:
```cpp
enum { proc_gen_p8, proc_gen_p9 } proc_gen;
unsigned pir_to_core_id(pir) {
  if (proc_gen == proc_gen_p9)
    return pir >> 2 & 5;
  if (proc_gen)
    return pir >> 3 & 5;
  return pir >> 2 & 7;
}
```
