### ISSUE TITLE
Analyzer crashes (Unexpected CFG element at front of block) with widen-loops=true

### ISSUE THREAD

**Issue by wjristow** [llvm/llvm-project#37209]
|  |  |
| --- | --- |
| Bugzilla Link | [37861](https://llvm.org/bz37861) |
| Version | trunk |
| OS | All |

## Extended Description 
The following test-case crashes in the Static Analyzer with an UNREACHABLE:
  Unexpected CFG element at front of block

when widen-loops=true.

$ cat t.cpp
//////////////// "t.cpp" ///////////////
class A {
public:
  void m_fn1();
};
bool g;
void fn1() {
  A a;
  A *b = &a;
  for (;;) {
    g = !b;
    b->m_fn1();
  }
}
////////////////////////////////////////
$ clang --analyze -Xanalyzer -analyzer-config -Xanalyzer widen-loops=true t.cpp
Unexpected CFG element at front of block
UNREACHABLE executed at clang/lib/StaticAnalyzer/Core/PathDiagnostic.cpp:740!
Stack dump:
  ...
clang: error: clang frontend command failed due to signal ...
clang version 7.0.0 (trunk 335000)
Target: x86_64-unknown-linux-gnu
  ...
$

As an aside, prior to r319333 it crashed with a different UNREACHABLE, but in
the same area of "StaticAnalyzer/Core/PathDiagnostic.cpp":
  Unexpected ProgramPoint

That "Unexpected ProgramPoint" crash was reported with a different test-case,
as bug 25609.  Just cross-referencing here, since they may be related.

**Comment by JOE1994** [comment]
No longer reproducible as of `clang 18.1.0` : https://godbolt.org/z/Kx6aq7cY5
