### ISSUE TITLE
clang-format repeatedly adds new comment line

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37223]
|  |  |
| --- | --- |
| Bugzilla Link | [37875](https://llvm.org/bz37875) |
| Version | 6.0 |
| OS | All |
| Attachments | [format file to reproduce the issue](https://user-images.githubusercontent.com/60944935/143757661-4b9283a3-391a-439f-8fb1-f1b284d97086.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

When instructing clang-format to comment the closing bracket of a namespace with the namespace name, in some situations with very long namespace names, that comment is added repeatedly when re-formatting code.

Example:
*******

namespace protobuf_tensorflow_2fcore_2fframework_2fresource_5fhandle_2eproto
{
struct StaticDescriptorInitializer {
}
}

After formatting 5 times:
************************
namespace protobuf_tensorflow_2fcore_2fframework_2fresource_5fhandle_2eproto
{
struct StaticDescriptorInitializer {
}
} // namespace
  // protobuf_tensorflow_2fcore_2fframework_2fresource_5fhandle_2eproto
  // protobuf_tensorflow_2fcore_2fframework_2fresource_5fhandle_2eproto
  // protobuf_tensorflow_2fcore_2fframework_2fresource_5fhandle_2eproto
  // protobuf_tensorflow_2fcore_2fframework_2fresource_5fhandle_2eproto
  // protobuf_tensorflow_2fcore_2fframework_2fresource_5fhandle_2eproto

.clang-format is attached.

Setting FixNamespaceComments: false fixes the issue.

**Comment by mydeveloperday** [comment]
This was broken in v8 but its fixed in at least v12

```
namespace protobuf_tensorflow_2fcore_2fframework_2fresource_5fhandle_2eproto
{
struct StaticDescriptorInitializer {
}
} // namespace
  // protobuf_tensorflow_2fcore_2fframework_2fresource_5fhandle_2eproto
```
