### ISSUE TITLE
[inline asm] invalid asm is sometimes reported via fatal error mechanism

### ISSUE THREAD

**Issue by gregbedwell** [llvm/llvm-project#37244]
|  |  |
| --- | --- |
| Bugzilla Link | [37896](https://llvm.org/bz37896) |
| Version | trunk |
| OS | Windows NT |
| Blocks | llvm/llvm-project#18487 llvm/llvm-project#30519  |

## Extended Description 
Clang correctly spots that the following inline asm is invalid.  Unfortunately it reports this via a fatal error which makes it appear as a compiler crash rather than a user error.

$ clang.exe --version
clang version 7.0.0 (trunk 335220) (llvm/trunk 335219)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: e:\work\upstream-llvm\build-vs2015-native-ninja\bin

$ cat 1.c
void f() { asm("subb %dh, %r9b"); }

$ gcc -c 1.c
1.c: Assembler messages:
1.c:1: Error: can't encode register '%dh' in an instruction requiring REX prefix.

$ clang.exe -c 1.c
fatal error: error in backend: Cannot encode high byte register in REX-prefixed instruction
clang.exe: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 7.0.0 (trunk 335220) (llvm/trunk 335219)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: e:\work\upstream-llvm\build-vs2015-native-ninja\bin
clang.exe: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang.exe: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang.exe: note: diagnostic msg: C:\Users\GREG\AppData\Local\Temp\1-c31ac3.c
clang.exe: note: diagnostic msg: C:\Users\GREG\AppData\Local\Temp\1-c31ac3.sh
clang.exe: note: diagnostic msg:

********************

**Comment by Endilll** [comment]
Can't reproduce using Clang 6 or 7: https://godbolt.org/z/rjTnx3fMx
