### ISSUE TITLE
valid sizeof operation introduced compiler crash

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37254]
|  |  |
| --- | --- |
| Bugzilla Link | [37906](https://llvm.org/bz37906) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The following C test case causes clang to crash.

Assertion failed: (ND->isUsed(false) || !isa<VarDecl>(ND) || !E->getLocation().isValid()) && "Should not use decl without marking it used!", file C:\src\llvm_package_333363\llvm\tools\clang\lib\CodeGen\CGExpr.cpp, line 2453

% clang --version
clang version 7.0.0 (trunk)
Target: i686-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files (x86)\LLVM\bin

Test case: 
---------------- test.c --------------------------------------
#include <stdarg.h>

extern void exit (int);
extern void abort (void);

char a[1];

void
f1 (void)
{
  int i = 0;
  int j = sizeof (typeof (*(++i, (char (*)[i])a)));
  if (i != 1 || j != 1)
    abort ();
}

int
main (void)
{
  f1 ();
  exit (0);
}

**Comment by k-mana** [comment]
This no longer reproduces on trunk: https://godbolt.org/z/61K5Yd1hr
This has been fixed: 968be05
