### ISSUE TITLE
Wrong alignment for multiple declarations of const pointers

### ISSUE THREAD

**Issue by sboukortt** [llvm/llvm-project#37268]
|  |  |
| --- | --- |
| Bugzilla Link | [37920](https://llvm.org/bz37920) |
| Version | 6.0 |
| OS | All |

## Extended Description 
With this code as “input.cc”:

    int main() {
      int n;

      int *a = &n,
          *b = &n;

      int *const c = &n,
          *const d = &n;
    }

Running `clang-format -style='{BasedOnStyle: llvm, ColumnLimit: 0}' input.cc` should produce the same code, but instead it outputs:

    int main() {
      int n;

      int *a = &n,
          *b = &n;

      int *const c = &n,
                 *const d = &n;
    }

The alignment is correct for the non-const pointers, but const seems to confuse clang-format.

The output becomes correct for the const pointers as well if `c` ceases to be initialized.

**Comment by mydeveloperday** [comment]
since at least v8 this has produced

```
int main() {
  int n;

  int *a = &n, *b = &n;

  int *const c = &n, *const d = &n;
}
```

**Comment by sboukortt** [comment]
Thank you but I think the point was more about the alignment of the `*` when there is a line break, and that the purpose of the `ColumnLimit: 0` in the repro command was just to avoid confounding from the automatic wrapping. If the limit is changed from 0 to 25 then the problem still reproduces.
