### ISSUE TITLE
'Assertion `BitWidth == RHS.BitWidth && "Bit widths must be the same"' failed.' with --aa-eval

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#37272]
|  |  |
| --- | --- |
| Bugzilla Link | [37924](https://llvm.org/bz37924) |
| Version | unspecified |
| OS | Linux |
| Attachments | [reproducer](https://user-images.githubusercontent.com/55733087/143757680-3868e58f-4302-4d28-aaec-0329bfe23ae3.gz) |
| CC | @alinas,@RKSimon,@nunoplopes |

## Extended Description 

Running
 opt -S -o - bbi-15492.ll -aa-eval

gives

opt: ../lib/Support/APInt.cpp:193: llvm::APInt &llvm::APInt::operator+=(const llvm::APInt &): Assertion `BitWidth == RHS.BitWidth && "Bit widths must be the same"' failed.
Stack dump:
0.      Program arguments: build-all/bin/opt -S -o - bbi-15492.ll -aa-eval 
1.      Running pass 'Function Pass Manager' on module 'bbi-15492.ll'.
2.      Running pass 'Exhaustive Alias Analysis Precision Evaluator' on function '@f1'
#&#8203;0 0x0000000001fef724 PrintStackTraceSignalHandler(void*) (build-all/bin/opt+0x1fef724)
#&#8203;1 0x0000000001fed990 llvm::sys::RunSignalHandlers() (build-all/bin/opt+0x1fed990)
#&#8203;2 0x0000000001fefa88 SignalHandler(int) (build-all/bin/opt+0x1fefa88)
#&#8203;3 0x00007f9e8ac12330 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10330)
#&#8203;4 0x00007f9e89801c37 gsignal /build/eglibc-ripdx6/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;5 0x00007f9e89805028 abort /build/eglibc-ripdx6/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;6 0x00007f9e897fabf6 __assert_fail_base /build/eglibc-ripdx6/eglibc-2.19/assert/assert.c:92:0
#&#8203;7 0x00007f9e897faca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
#&#8203;8 0x0000000001f7d733 (build-all/bin/opt+0x1f7d733)
#&#8203;9 0x0000000001447f3c llvm::BasicAAResult::GetLinearExpression(llvm::Value const*, llvm::APInt&, llvm::APInt&, unsigned int&, unsigned int&, llvm::DataLayout const&, unsigned int, llvm::AssumptionCache*, llvm::DominatorTree*, bool&, bool&) (build-all/bin/opt+0x1447f3c)
#&#8203;10 0x0000000001447f29 llvm::BasicAAResult::GetLinearExpression(llvm::Value const*, llvm::APInt&, llvm::APInt&, unsigned int&, unsigned int&, llvm::DataLayout const&, unsigned int, llvm::AssumptionCache*, llvm::DominatorTree*, bool&, bool&) (build-all/bin/opt+0x1447f29)
#&#8203;11 0x0000000001447f29 llvm::BasicAAResult::GetLinearExpression(llvm::Value const*, llvm::APInt&, llvm::APInt&, unsigned int&, unsigned int&, llvm::DataLayout const&, unsigned int, llvm::AssumptionCache*, llvm::DominatorTree*, bool&, bool&) (build-all/bin/opt+0x1447f29)
#&#8203;12 0x0000000001447f29 llvm::BasicAAResult::GetLinearExpression(llvm::Value const*, llvm::APInt&, llvm::APInt&, unsigned int&, unsigned int&, llvm::DataLayout const&, unsigned int, llvm::AssumptionCache*, llvm::DominatorTree*, bool&, bool&) (build-all/bin/opt+0x1447f29)
#&#8203;13 0x0000000001447f29 llvm::BasicAAResult::GetLinearExpression(llvm::Value const*, llvm::APInt&, llvm::APInt&, unsigned int&, unsigned int&, llvm::DataLayout const&, unsigned int, llvm::AssumptionCache*, llvm::DominatorTree*, bool&, bool&) (build-all/bin/opt+0x1447f29)
#&#8203;14 0x0000000001447f29 llvm::BasicAAResult::GetLinearExpression(llvm::Value const*, llvm::APInt&, llvm::APInt&, unsigned int&, unsigned int&, llvm::DataLayout const&, unsigned int, llvm::AssumptionCache*, llvm::DominatorTree*, bool&, bool&) (build-all/bin/opt+0x1447f29)
#&#8203;15 0x000000000144d29b llvm::BasicAAResult::constantOffsetHeuristic(llvm::SmallVectorImpl<llvm::BasicAAResult::VariableGEPIndex> const&, unsigned long, unsigned long, long, llvm::AssumptionCache*, llvm::DominatorTree*) (build-all/bin/opt+0x144d29b)
#&#8203;16 0x000000000144cb38 llvm::BasicAAResult::aliasGEP(llvm::GEPOperator const*, unsigned long, llvm::AAMDNodes const&, llvm::Value const*, unsigned long, llvm::AAMDNodes const&, llvm::Value const*, llvm::Value const*) (build-all/bin/opt+0x144cb38)
#&#8203;17 0x000000000144a863 llvm::BasicAAResult::aliasCheck(llvm::Value const*, unsigned long, llvm::AAMDNodes, llvm::Value const*, unsigned long, llvm::AAMDNodes, llvm::Value const*, llvm::Value const*) (build-all/bin/opt+0x144a863)
#&#8203;18 0x000000000144a060 llvm::BasicAAResult::alias(llvm::MemoryLocation const&, llvm::MemoryLocation const&) (build-all/bin/opt+0x144a060)
#&#8203;19 0x0000000001432f0f llvm::AAResults::alias(llvm::MemoryLocation const&, llvm::MemoryLocation const&) (build-all/bin/opt+0x1432f0f)
#&#8203;20 0x0000000001439175 llvm::AAEvaluator::runInternal(llvm::Function&, llvm::AAResults&) (build-all/bin/opt+0x1439175)
#&#8203;21 0x000000000143c885 llvm::AAEvalLegacyPass::runOnFunction(llvm::Function&) (build-all/bin/opt+0x143c885)
#&#8203;22 0x0000000001a7a40a llvm::FPPassManager::runOnFunction(llvm::Function&) (build-all/bin/opt+0x1a7a40a)
#&#8203;23 0x0000000001a7a668 llvm::FPPassManager::runOnModule(llvm::Module&) (build-all/bin/opt+0x1a7a668)
#&#8203;24 0x0000000001a7ab9d llvm::legacy::PassManagerImpl::run(llvm::Module&) (build-all/bin/opt+0x1a7ab9d)
#&#8203;25 0x0000000000745aac main (build-all/bin/opt+0x745aac)
#&#8203;26 0x00007f9e897ecf45 __libc_start_main /build/eglibc-ripdx6/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;27 0x000000000072ee0d _start (build-all/bin/opt+0x72ee0d)
Abort

This is old. Found when running random passes on random input.

**Comment by bjope** [comment]
The reproducer no longer hits the assertion failure. When bisecting old downstream builds it seems like the problem was resolved in April 2021 (or late March 2021). I'll just close this.
