### ISSUE TITLE
Missing space when using macro after function signature

### ISSUE THREAD

**Issue by tanderson-google** [llvm/llvm-project#37276]
|  |  |
| --- | --- |
| Bugzilla Link | [37928](https://llvm.org/bz37928) |
| Version | trunk |
| OS | Linux |
| CC | @nico,@tanderson-google |

## Extended Description 
Formatting this code (from Chromium's base/allocator/allocator_shim_override_cpp_symbols.h) removes the space before __THROW on operator delete.

--------------------------------------------------------------------------------
SHIM_ALWAYS_EXPORT void operator delete(void* p, size_t) __THROW {
  ShimCppDelete(p);
}

SHIM_ALWAYS_EXPORT void operator delete[](void* p, size_t) __THROW {
  ShimCppDelete(p);
}
--------------------------------------------------------------------------------

So now it looks like:

--------------------------------------------------------------------------------
SHIM_ALWAYS_EXPORT void operator delete(void* p, size_t)__THROW {
  ShimCppDelete(p);
}

SHIM_ALWAYS_EXPORT void operator delete[](void* p, size_t) __THROW {
  ShimCppDelete(p);
}
--------------------------------------------------------------------------------

operator delete[] is fine, however.

**Comment by mkurdej** [comment]
Duplicate of #27037.
