### ISSUE TITLE
[Windows] Assigning a base class pointer to a derived class causes an assertion in clang

### ISSUE THREAD

**Issue by c865380c-e43e-4621-95cb-b0e85c2384bb** [llvm/llvm-project#37295]
|  |  |
| --- | --- |
| Bugzilla Link | [37947](https://llvm.org/bz37947) |
| Version | trunk |
| OS | Windows NT |
| CC | @zmodem |

## Extended Description 
This reproduces when trying to run one of the LLDB tests on Windows (specifically, TestCallOverriddenMethod.py).

To reproduce:

1) Build Clang on Windows with LLVM_ENABLE_ASSERTIONS=ON
2) Build the source for TestCallOverriddenMethod.py

Result:

Assertion failed: Prior->Kind == MemberInfo::Field && !Prior->FD && "Only storage fields have tail padding!", file e:\_work\1\s\llvm\tools\clang\lib\codegen\cgrecordlayoutbuilder.cpp, line 596

The source for the test is:

```
class Base {
public:
  virtual ~Base() {}
  virtual void foo() {}
};

class Derived : public Base {
public:
  virtual void foo() {}
};

int main() {
  Derived d;
  Base *b = &d;
  return 0; // Set breakpoint here
}
```

**Comment by ZequanWu** [comment]
It no longer crashes in latest lldb and gives the correct result if let foo() to return different values in base class and derived class. I guess it's already fixed.
