### ISSUE TITLE
[analyzer] Checker for uninitialized C++ objects fails in some trivial situations

### ISSUE THREAD

**Issue by abpostelnicu** [llvm/llvm-project#37313]
|  |  |
| --- | --- |
| Bugzilla Link | [37965](https://llvm.org/bz37965) |
| Version | unspecified |
| OS | All |
| CC | @Szelethus,@sylvestre |

## Extended Description 
Hello,

We've ran scan-build wit cxx-uninitialized-object enabled, and among other issues we also got this kinda trivial issue:

http://sylvestre.ledru.info/reports/fx-scan-build/report-nsCOMPtr.h-nsGetServiceByContractIDWithError-1-24.html#EndPath

It's obvious that |mErrorPtr| it's initialised in the initialisers list in the ctor: nsGetServiceByContractIDWithError(const char* aContractID, nsresult* aErrorPtr), please see https://dxr.mozilla.org/mozilla-central/source/xpcom/base/nsCOMPtr.h?q=nsGetServiceByContractIDWithError%28const+char%2A+aContractID%2C+nsresult%2A+aErrorPtr%29&redirect_type=single#265

Maybe it only support primitive type initialisation, but even so, this is a pointer and shouldn't matter this much.

**Comment by haoNoQ** [comment]
This one looks like it can be closed, these changes have been implemented since(?)

**Comment by Szelethus** [comment]
Yep!
