### ISSUE TITLE
readability-avoid-const-params-in-decls removes const from template parameter

### ISSUE THREAD

**Issue by c264d90a-90ef-44b1-b442-b0cb2e8962f9** [llvm/llvm-project#37383]
|  |  |
| --- | --- |
| Bugzilla Link | [38035](https://llvm.org/bz38035) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Minimum working example](https://user-images.githubusercontent.com/93352316/143757734-22bb6990-b81a-4c5f-8ac6-10606fd019d4.gz) |
| CC | @adesitter,@EugeneZelenko,@tonyelewis |

## Extended Description 

The suggested fix for the attached minimum working example does not compile, as it removes the wrong 'const' from the function declaration.

$ clang-tidy -checks='-*,readability-avoid-const-params*' mwe.cpp -fix
4 warnings generated.
main.cpp:3:10: warning: parameter 1 is const-qualified in the function declaration; const-qualification of parameters only has an effect in function definitions [readability-avoid-const-params-in-decls]
void foo(const std::list<const int *>);
         ^               ~~~~~~~~~
main.cpp:3:26: note: FIX-IT applied suggested code changes
void foo(const std::list<const int *>);
                         ^
clang-tidy applied 1 of 1 suggested fixes.

**Comment by ymand** [comment]
Fixed by commit a34532c330f61c35612bb0c4b753979307020608.
