### ISSUE TITLE
clang-tidy crashes in c++17 mode on sample

### ISSUE THREAD

**Issue by c4d84ccc-fe38-47f3-8565-763f049c3644** [llvm/llvm-project#37390]
|  |  |
| --- | --- |
| Bugzilla Link | [38042](https://llvm.org/bz38042) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Callstack without line breaks](https://user-images.githubusercontent.com/92601311/143757738-5f3bf381-c887-4317-b84e-f2777115a819.gz), [Test Sample](https://user-images.githubusercontent.com/92601311/143757739-db4d5e5f-3f97-4221-942e-0bc7cb51fa93.gz) |
| CC | @adrianimboden |

## Extended Description 
In a quite big file I found a reproducible crash when calling clang-tidy.

After a long search I managed to reduce it to a very small test sample which interestingly does not crash all the time, but on my computer it usually crashes in under 10 tries.

I call it like this to trigger the bug:
# while clang-tidy-6.0 test.cpp -- -std=c++17; do date; done

This is the reduced test samle (test.cpp):
struct base {
    unsigned char counter; // does not happen when != unsigned char
};
struct struct1 {
    char foo[3]; // needs to be >= 3
};
struct struct2 : public base {
    struct1 foo;
};

union VariantImpl {
    struct2 foo;
};

struct Frame {
    explicit Frame(struct2 foo)
        : impl{foo}
        , which{0} {
    }
    VariantImpl impl;
    int         which;
};

template <typename T>
inline Frame parse(T) {
    return Frame{struct2{}};
}

inline void bson_to_message() {
    parse(struct1{});
}

I tested it with clang 6.0 on a clean Ubuntu docker image using the sources from https://apt.llvm.org/.

I use a self-built llvm toolchain, so I built a debug build. There the following assert triggers:
~/workdir/build/clangtidy$ /usr/debug/bin/clang-tidy test.cpp -- -std=c++17
clang-tidy: /source/llvm/llvm/tools/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SVals.h:93: T clang::ento::SVal::castAs() const [T = clang::ento::nonloc::CompoundVal]: Assertion `T::isKind(*this)' failed.
Aborted (core dumped)

The callstack looks like this:
~/workdir/build/clangtidy$ lldb -- /usr/debug/bin/clang-tidy test.cpp -- -std=c++17
(lldb) target create "/usr/debug/bin/clang-tidy"
Current executable set to '/usr/debug/bin/clang-tidy' (x86_64).
(lldb) settings set -- target.run-args  "test.cpp" "--" "-std=c++17"
(lldb) run
Process 6647 launched: '/usr/debug/bin/clang-tidy' (x86_64)
clang-tidy: /source/llvm/llvm/tools/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SVals.h:93: T clang::ento::SVal::castAs() const [T = clang::ento::nonloc::CompoundVal]: Assertion `T::isKind(*this)' failed.
Process 6647 stopped
* thread #&#8203;1, name = 'clang-tidy', stop reason = signal SIGABRT
    frame #&#8203;0: 0x00007ffff6889e97 libc.so.6`__GI_raise(sig=2) at raise.c:51
(lldb) bt
* thread #&#8203;1, name = 'clang-tidy', stop reason = signal SIGABRT
  * frame #&#8203;0: 0x00007ffff6889e97 libc.so.6`__GI_raise(sig=2) at raise.c:51
    frame #&#8203;1: 0x00007ffff688b801 libc.so.6`__GI_abort at abort.c:79
    frame #&#8203;2: 0x00007ffff687b39a libc.so.6`__assert_fail_base(fmt="%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion="T::isKind(*this)", file="/source/llvm/llvm/tools/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SVals.h", line=93, function=<unavailable>) at assert.c:92
    frame #&#8203;3: 0x00007ffff687b412 libc.so.6`__GI___assert_fail(assertion=<unavailable>, file=<unavailable>, line=<unavailable>, function=<unavailable>) at assert.c:101
    frame #&#8203;4: 0x0000000003db2b3a clang-tidy`clang::ento::nonloc::CompoundVal clang::ento::SVal::castAs<clang::ento::nonloc::CompoundVal>(this=0x00007fffffff7c40) const at SVals.h:93
    frame #&#8203;5: 0x000000000420962c clang-tidy`(anonymous namespace)::RegionStoreManager::bindArray(this=0x0000000004b96b40, B=0x00007fffffff7e18, R=0x0000000004ba3fa0, Init=(Data = 0x0000000004b9c720, Kind = 7))::RegionBindingsRef const&, clang::ento::TypedValueRegion const*, clang::ento::SVal) at RegionStore.cpp:2113
    frame #&#8203;6: 0x000000000420a0fb clang-tidy`(anonymous namespace)::RegionStoreManager::bindStruct(this=0x0000000004b96b40, B=0x00007fffffff8138, R=0x0000000004ba3f78, V=(Data = 0x0000000004b9c750, Kind = 3))::RegionBindingsRef const&, clang::ento::TypedValueRegion const*, clang::ento::SVal) at RegionStore.cpp:2275
    frame #&#8203;7: 0x000000000420a1a5 clang-tidy`(anonymous namespace)::RegionStoreManager::bindStruct(this=0x0000000004b96b40, B=0x00007fffffff8430, R=0x0000000004ba3f28, V=(Data = 0x0000000004ba3980, Kind = 3))::RegionBindingsRef const&, clang::ento::TypedValueRegion const*, clang::ento::SVal) at RegionStore.cpp:2277
    frame #&#8203;8: 0x0000000004209041 clang-tidy`(anonymous namespace)::RegionStoreManager::bind(this=0x0000000004b96b40, B=0x00007fffffff8430, L=Loc @ 0x00007fffffff83c0, V=(Data = 0x0000000004ba3980, Kind = 3))::RegionBindingsRef const&, clang::ento::Loc, clang::ento::SVal) at RegionStore.cpp:2036
    frame #&#8203;9: 0x00000000041ffa62 clang-tidy`(anonymous namespace)::RegionStoreManager::Bind(this=0x0000000004b96b40, store=0x0000000000000000, LV=Loc @ 0x00007fffffff8470, V=(Data = 0x0000000004ba3980, Kind = 3)) at RegionStore.cpp:407
    frame #&#8203;10: 0x000000000422b55b clang-tidy`clang::ento::StoreManager::enterStackFrame(this=0x0000000004b96b40, OldStore=0x0000000000000000, Call=0x0000000004b9c2c8, LCtx=0x0000000004ba6260) at Store.cpp:39
    frame #&#8203;11: 0x00000000041dae40 clang-tidy`clang::ento::ProgramState::enterStackFrame(this=0x0000000004ba3e40, Call=0x0000000004b9c2c8, CalleeCtx=0x0000000004ba6260) const at ProgramState.cpp:236
    frame #&#8203;12: 0x000000000419e8ef clang-tidy`clang::ento::ExprEngine::inlineCall(this=0x00007fffffffa8e0, Call=0x0000000004b9c2c8, D=0x0000000004b599c0, Bldr=0x00007fffffff8c68, Pred=0x0000000004ba3e70, State=clang::ento::ProgramStateRef @ 0x00007fffffff89e0) at ExprEngineCallAndReturn.cpp:436
    frame #&#8203;13: 0x00000000041a0138 clang-tidy`clang::ento::ExprEngine::defaultEvalCall(this=0x00007fffffffa8e0, Bldr=0x00007fffffff8c68, Pred=0x0000000004ba3e70, CallTemplate=0x0000000004b9c2c8) at ExprEngineCallAndReturn.cpp:931
    frame #&#8203;14: 0x000000000419a3ef clang-tidy`clang::ento::ExprEngine::VisitCXXConstructExpr(this=0x00007fffffffa8e0, CE=0x0000000004b8da28, Pred=0x0000000004ba3e70, destNodes=0x00007fffffff9fd8) at ExprEngineCXX.cpp:364
    frame #&#8203;15: 0x000000000416ebe6 clang-tidy`clang::ento::ExprEngine::Visit(this=0x00007fffffffa8e0, S=0x0000000004b8da28, Pred=0x0000000004ba3e70, DstTop=0x00007fffffffa0f0) at ExprEngine.cpp:1261
    frame #&#8203;16: 0x000000000416b6d1 clang-tidy`clang::ento::ExprEngine::ProcessStmt(this=0x00007fffffffa8e0, S=const clang::CFGStmt @ 0x00007fffffffa290, Pred=0x0000000004ba3c48) at ExprEngine.cpp:507
    frame #&#8203;17: 0x000000000416b38a clang-tidy`clang::ento::ExprEngine::processCFGElement(this=0x00007fffffffa8e0, E=const clang::CFGElement @ 0x00007fffffffa380, Pred=0x0000000004ba3c48, StmtIdx=6, Ctx=0x00007fffffffa3d8) at ExprEngine.cpp:351
    frame #&#8203;18: 0x0000000004155bcd clang-tidy`clang::ento::CoreEngine::HandlePostStmt(this=0x00007fffffffa8f8, B=0x0000000004ba8458, StmtIdx=6, Pred=0x0000000004ba3c48) at CoreEngine.cpp:531
    frame #&#8203;19: 0x000000000415548c clang-tidy`clang::ento::CoreEngine::dispatchWorkItem(this=0x00007fffffffa8f8, Pred=0x0000000004ba3c48, Loc=ProgramPoint @ 0x00007fffffffa610, WU=0x00007fffffffa710) at CoreEngine.cpp:279
    frame #&#8203;20: 0x0000000004154f9c clang-tidy`clang::ento::CoreEngine::ExecuteWorkList(this=0x00007fffffffa8f8, L=0x0000000004b98730, Steps=224984, InitState=clang::ento::ProgramStateRef @ 0x00007fffffffa860) at CoreEngine.cpp:235
    frame #&#8203;21: 0x0000000002796435 clang-tidy`clang::ento::ExprEngine::ExecuteWorkList(this=0x00007fffffffa8e0, L=0x0000000004b98730, Steps=225000) at ExprEngine.h:109
    frame #&#8203;22: 0x000000000273e282 clang-tidy`(anonymous namespace)::AnalysisConsumer::ActionExprEngine(this=0x0000000004b169b0, D=0x0000000004b8d288, ObjCGCEnabled=false, IMode=Inline_Regular, VisitedCallees=0x00007fffffffaf88) at AnalysisConsumer.cpp:717
    frame #&#8203;23: 0x000000000273e041 clang-tidy`(anonymous namespace)::AnalysisConsumer::RunPathSensitiveChecks(this=0x0000000004b169b0, D=0x0000000004b8d288, IMode=Inline_Regular, Visited=0x00007fffffffaf88) at AnalysisConsumer.cpp:738
    frame #&#8203;24: 0x000000000273dcd5 clang-tidy`(anonymous namespace)::AnalysisConsumer::HandleCode(this=0x0000000004b169b0, D=0x0000000004b8d288, Mode=2, IMode=Inline_Regular, VisitedCallees=0x00007fffffffaf88) at AnalysisConsumer.cpp:685
    frame #&#8203;25: 0x00000000027312cc clang-tidy`(anonymous namespace)::AnalysisConsumer::HandleDeclsCallGraph(this=0x0000000004b169b0, LocalTUDeclsSize=8) at AnalysisConsumer.cpp:498
    frame #&#8203;26: 0x000000000272f547 clang-tidy`(anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(this=0x0000000004b169b0, C=0x0000000004b02370) at AnalysisConsumer.cpp:550
    frame #&#8203;27: 0x0000000002a152de clang-tidy`clang::MultiplexConsumer::HandleTranslationUnit(this=0x0000000004b17bf0, Ctx=0x0000000004b02370) at MultiplexConsumer.cpp:311
    frame #&#8203;28: 0x0000000002bbe8d6 clang-tidy`clang::ParseAST(S=0x0000000004b4f900, PrintStats=false, SkipFunctionBodies=false) at ParseAST.cpp:159
    frame #&#8203;29: 0x000000000291212c clang-tidy`clang::ASTFrontendAction::ExecuteAction(this=0x0000000004b17d70) at FrontendAction.cpp:998
    frame #&#8203;30: 0x0000000002911ba0 clang-tidy`clang::FrontendAction::Execute(this=0x0000000004b17d70) at FrontendAction.cpp:897
    frame #&#8203;31: 0x00000000028961b8 clang-tidy`clang::CompilerInstance::ExecuteAction(this=0x00007fffffffb660, Act=0x0000000004b17d70) at CompilerInstance.cpp:991
    frame #&#8203;32: 0x000000000262f652 clang-tidy`clang::tooling::FrontendActionFactory::runInvocation(this=0x00007fffffffc928, Invocation=nullptr, Files=0x0000000004aaaea0, PCHContainerOps=<unavailable>, DiagConsumer=0x00007fffffffc940) at Tooling.cpp:323
    frame #&#8203;33: 0x000000000262f4f3 clang-tidy`clang::tooling::ToolInvocation::runInvocation(this=0x00007fffffffc410, BinaryName="clang-tool", Compilation=0x0000000004a99440, Invocation=nullptr, PCHContainerOps=nullptr) at Tooling.cpp:298
    frame #&#8203;34: 0x000000000262dd86 clang-tidy`clang::tooling::ToolInvocation::run(this=0x00007fffffffc410) at Tooling.cpp:283
    frame #&#8203;35: 0x00000000026307eb clang-tidy`clang::tooling::ClangTool::run(this=0x00007fffffffd340, Action=0x00007fffffffc928) at Tooling.cpp:456
    frame #&#8203;36: 0x0000000001e82d74 clang-tidy`clang::tidy::runClangTidy(Context=0x00007fffffffd690, Compilations=0x0000000004a99060, InputFiles=(Data = " Length = 1), Profile=0x0000000000000000) at ClangTidy.cpp:545
    frame #&#8203;37: 0x00000000016d3b78 clang-tidy`clang::tidy::clangTidyMain(argc=2, argv=0x00007fffffffe2b8) at ClangTidyMain.cpp:412
    frame #&#8203;38: 0x00000000016d3112 clang-tidy`main(argc=4, argv=0x00007fffffffe2b8) at ClangTidyMain.cpp:539
    frame #&#8203;39: 0x00007ffff686cb97 libc.so.6`__libc_start_main(main=(clang-tidy`main at ClangTidyMain.cpp:538), argc=4, argv=0x00007fffffffe2b8, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffe2a8) at libc-start.c:310
    frame #&#8203;40: 0x00000000016d302a clang-tidy`_start + 42
(lldb)

**Comment by adrianimboden** [comment]
I am the original author of that issue. I just tried to reproduce. It seems to be fixed in the meanwhile.

@devincoughlin you can close this issue
