### ISSUE TITLE
pip install lit does not create lit.exe

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37401]
|  |  |
| --- | --- |
| Bugzilla Link | [38053](https://llvm.org/bz38053) |
| Version | 6.0 |
| OS | other |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
*Overview*

On a clean Windows 7 (and possibly other Windowses) with Python 2.7

$> pip install lit

does not create C:\Python27\Scripts\lit.exe. As a consequence, there is no lit in the PATH, and lit cannot be found by any build tools.

It is possible to install lit v.5.0 (which creates lit.exe) and then upgrade to v.6.0. In this case, lit.exe is kept, and points to lit v.6.0.

*Steps to reproduce*

[On a clean Windows 7]
$> pip install lit
[reboot]
$> where lit
INFO: Could not find files for the given pattern(s).

*Workaround*

$> pip install lit==v0.5.0
$> pip install lit==v0.6.0

**Comment by arsenm** [comment]
Old build issue
