### ISSUE TITLE
clang-format creates extra space in objective-c array literal if it contains "class"

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37417]
|  |  |
| --- | --- |
| Bugzilla Link | [38069](https://llvm.org/bz38069) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @seanm |

## Extended Description 
when formatting

`NSArray* simpleClassArray = @[[NSNumber class]];`

clang-format adds an extra space

`NSArray* simpleClassArray = @ [[NSNumber class]];`

the following code is formatted as expected:
`NSArray *simpleOneElementNSNumberArray = @[[NSNumber numberWithInteger:1`]];

config:
```
Language:        ObjC
BasedOnStyle:  LLVM
```

potentially related to Bug 37454 

occurs with trunk version:
 build locally or installed via home-brew (clang-format version 7.0.0 (tags/google/stable/2018-04-24))

does not occur with version 6.0

**Comment by mkurdej** [comment]
This issue was fixed in clang-format 9. Closing.

```
"d:\Program Files\LLVM-8.0.1\bin\clang-format.exe" -style=file test.m
NSArray *simpleClassArray = @ [[NSNumber class]];

"d:\Program Files\LLVM-9.0.0\bin\clang-format.exe" -style=file test.m
NSArray *simpleClassArray = @[[NSNumber class]];
```
