### ISSUE TITLE
bugprone-forwarding-reference-overload incorrectly warns about an enable_if-ed forwarding constructor

### ISSUE THREAD

**Issue by 0acd4e0f-fb71-46f2-a106-6376379b1b59** [llvm/llvm-project#37429]
|  |  |
| --- | --- |
| Bugzilla Link | [38081](https://llvm.org/bz38081) |
| Version | unspecified |
| OS | Windows NT |
| CC | @akrzemi1 |

## Extended Description 
Checker bugprone-forwarding-reference-overload fires on the following declaration:

  #include <type_traits>

  struct X
  {
    template <typename U, 
              std::enable_if_t<!std::is_base_of<X, std::decay_t<U>>::value>* = nullptr>
    explicit X(U&& u);
  };

Even though in the declaration I have taken the necessary precautions that the forwarding reference constructor is never used while copying/moving.

I think the checker should additionally check if enable_if is used inside templae parameter list, and if so no warning should be emitted.

**Comment by PiotrZSL** [comment]
Already fixed by 68546c9d6fc54a7ca7ad487cd4b6a5dafea9b4f3.
No reproduction on main (LLVM 17).
