### ISSUE TITLE
Regression(336426): Assertion `BitWidth == RHS.BitWidth && "Bit widths must be the same"' failed when building chrome

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#37432]
|  |  |
| --- | --- |
| Bugzilla Link | [38084](https://llvm.org/bz38084) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [repro](https://user-images.githubusercontent.com/3487/143757748-3b3160d2-1af9-4d31-8af4-2f56b6bc1011.gz) |
| CC | @rotateright |

## Extended Description 

https://logs.chromium.org/v/?s=chromium%2Fbb%2Fchromium.clang%2FToTLinux%2F3002%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

   Code generation
3.      Running pass 'Function Pass Manager' on module '../../third_party/skia/src/effects/imagefilters/SkMergeImageFilter.cpp'.
4.      Running pass 'X86 DAG->DAG Instruction Selection' on function '@"?onFilterImage@SkMergeImageFilter@@MEBA?AV?$sk_sp@VSkSpecialImage@@@@PEAVSkSpecialImage@@AEBVContext@SkImageFilter@@PEAUSkIPoint@@@Z"'
#&#8203;0 0x000000000110946d PrintStackTraceSignalHandler(void*) (../../../../llvm-mono/out/gn/bin/clang-cl+0x110946d)

...so very likely due to r336426 . I'll try a revert.

Repro attached.

**Comment by Endilll** [comment]
Can't reproduce using Clang 6 and 7 with assertions enabled.
