### ISSUE TITLE
bugprone-throw-keyword-missing gives false positives on assignment

### ISSUE THREAD

**Issue by 0acd4e0f-fb71-46f2-a106-6376379b1b59** [llvm/llvm-project#37448]
|  |  |
| --- | --- |
| Bugzilla Link | [38100](https://llvm.org/bz38100) |
| Version | unspecified |
| OS | Windows NT |
| CC | @akrzemi1 |

## Extended Description 
Consider the following .cpp file:

  ```
  struct MyException {};

  struct Y
  {
    void operator=(MyException) {}
  };

  void fun1()
  {
    Y x;
    x = MyException{};
  }

  template <typename T>
  void fun2()
  {
    T x;
    x = MyException{};
  }
  ```

bugprone-throw-keyword-missing gives (correctly) no warning for assignment in function fun1(), because this is obviously my intention to assign the exception to object `x`. This happens often when implementing task frameworks that cannot just throw exceptions, but need to pass them around.

But bugprone-throw-keyword-missing gives a warning in function template fun2(). I do not think it is a correct behavior. We cannot see the definition of `T`, but there are two possibilities:
1. Either type `T` has no assignment from the exception type: in this case the program will not compile anyway, so this warning is redundant.
2. Type `T` does provide an assignment from the exception type: in this case it is my intention to  be able to assign an exception object to `T`s, and the warning is a false-positive.

In consequence, it seems that bugprone-throw-keyword-missing should *never* warn when the exception object is in the right-hand side of the assignment.

**Comment by PiotrZSL** [comment]
Already fixed by https://reviews.llvm.org/D9613 (false-positive was due to matching cxxFunctionalCastExpr).
