### ISSUE TITLE
"DISubprogram attached to more than one function" with -argpromotion -instcombine after r336419

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#37462]
|  |  |
| --- | --- |
| Bugzilla Link | [38114](https://llvm.org/bz38114) |
| Version | unspecified |
| OS | Linux |
| Attachments | [reproducer](https://user-images.githubusercontent.com/55733087/143757755-5c5a4e38-cfb0-4fbf-b00f-b7b45f919cb8.gz) |
| CC | @coffezhou,@dstenb,@dwblaikie,@JDevlieghere,@TNorthover |

## Extended Description 

With

  opt -S -o - foo.ll -argpromotion -instcombine

I get

DISubprogram attached to more than one function
!&#8203;1 = distinct !DISubprogram(name: "func_27", scope: !&#8203;2, file: !&#8203;2, line: 
251, type: !&#8203;3, isLocal: true, isDefinition: true, scopeLine: 252, 
isOptimized: false, unit: !&#8203;5)
i64 ()* @&#8203;func_27
LLVM ERROR: Broken module found, compilation aborted!

If I add -print-before-all -print-after-all -print-module-scope I get 
this as the last printouts:

*** IR Dump Before Module Verifier *** (function: func_27)
; ModuleID = 'foo.ll'
source_filename = "foo.ll"

@&#8203;g_280 = external global i32

define i32 @&#8203;func_1() {
bb1:
   %l_55.115 = alloca i32*, align 8
   %_tmp555 = load i32*, i32** %l_55.115, align 8
   %0 = call i64 @&#8203;func_27()
   ret i32 undef
}

define internal i64 @&#8203;func_27() !dbg !&#8203;1 {
   store i32* @&#8203;g_280, i32** undef, align 8
   ret i64 undef
}

define i16 @&#8203;func_28() {
   %_tmp5791 = call i32 @&#8203;func_1()
   ret i16 undef
}

!llvm.dbg.cu = !{}
!llvm.module.flags = !{#0}

!&#8203;0 = !{i32 2, !"Debug Info Version", i32 3}
!&#8203;1 = distinct !DISubprogram(name: "func_27", scope: !&#8203;2, file: !&#8203;2, line: 
251, type: !&#8203;3, isLocal: true, isDefinition: true, scopeLine: 252, 
isOptimized: false, unit: !&#8203;5)
!&#8203;2 = !DIFile(filename: "foo.c", directory: "/bar")
!&#8203;3 = !DISubroutineType(types: !&#8203;4)
!&#8203;4 = !{}
!&#8203;5 = distinct !DICompileUnit(language: DW_LANG_C, file: !&#8203;2, producer: 
"My compiler", isOptimized: false, runtimeVersion: 0, emissionKind: 
LineTablesOnly)
DISubprogram attached to more than one function
!&#8203;1 = distinct !DISubprogram(name: "func_27", scope: !&#8203;2, file: !&#8203;2, line: 
251, type: !&#8203;3, isLocal: true, isDefinition: true, scopeLine: 252, 
isOptimized: false, unit: !&#8203;5)
i64 ()* @&#8203;func_27
*** IR Dump After Module Verifier *** (function: func_27)
; ModuleID = 'foo.ll'
source_filename = "foo.ll"

@&#8203;g_280 = external global i32

define i32 @&#8203;func_1() {
bb1:
   %l_55.115 = alloca i32*, align 8
   %_tmp555 = load i32*, i32** %l_55.115, align 8
   %0 = call i64 @&#8203;func_27()
   ret i32 undef
}

define internal i64 @&#8203;func_27() !dbg !&#8203;1 {
   store i32* @&#8203;g_280, i32** undef, align 8
   ret i64 undef
}

define i16 @&#8203;func_28() {
   %_tmp5791 = call i32 @&#8203;func_1()
   ret i16 undef
}

!llvm.dbg.cu = !{}
!llvm.module.flags = !{#0}

!&#8203;0 = !{i32 2, !"Debug Info Version", i32 3}
!&#8203;1 = distinct !DISubprogram(name: "func_27", scope: !&#8203;2, file: !&#8203;2, line: 
251, type: !&#8203;3, isLocal: true, isDefinition: true, scopeLine: 252, 
isOptimized: false, unit: !&#8203;5)
!&#8203;2 = !DIFile(filename: "foo.c", directory: "/bar")
!&#8203;3 = !DISubroutineType(types: !&#8203;4)
!&#8203;4 = !{}
!&#8203;5 = distinct !DICompileUnit(language: DW_LANG_C, file: !&#8203;2, producer: 
"My compiler", isOptimized: false, runtimeVersion: 0, emissionKind: 
LineTablesOnly)
LLVM ERROR: Broken module found, compilation aborted!

As far as I can see in the printouts !&#8203;1 is only used on func_27 and 
still it complains.

func27 was changed during argpromotion:

ARG PROMOTION:  Promoting to:
declare !dbg !&#8203;0 internal i64 @&#8203;func_27(i32*)

From:
define internal i64 @&#8203;func_27(i32* %p1, i32* %p2) {
   store i32* %p1, i32** undef
   store i32* @&#8203;g_280, i32** undef
   ret i64 undef
}

so I'm not sure if the old func_27 is still hanging around in some way?

This started happening after r336419:

    CallGraphSCCPass: iterate over all functions.
    
    Previously we only iterated over functions reachable from the set of
    external functions in the module. But since some of the passes under
    this (notably the always-inliner and coroutine lowerer) are required for
    correctness, they need to run over everything.
    
    This just adds an extra layer of iteration over the CallGraph to keep
    track of which functions we've already visited and get the next batch of
    SCCs.
    
    Should fix llvm/llvm-project#37377 .

I've no idea if r336419 is really to blame here though or if it's just exposing an already existing problem.

**Comment by jmorse** [comment]
Tested this with the very recent c24f0f9bd6f and I can't replicate the crash. Jonas' comment on Jul 13, 2018 pins the problem down to CGPassManager, and of course in the meantime we've moved on to the "new" pass manager. Thus, I believe it's safe to say that this bug was in code that's since been deprecated and deleted, so it won't be fixed.
