### ISSUE TITLE
LTO build gives assertion

### ISSUE THREAD

**Issue by FlameTop** [llvm/llvm-project#37468]
|  |  |
| --- | --- |
| Bugzilla Link | [38120](https://llvm.org/bz38120) |
| Version | trunk |
| OS | All |
| CC | @eleviant |

## Extended Description 
Change 'r336059 - [Evaluator] Improve evaluation of call instruction' appears to have introduced a compiler assertion when compiling this example code.

NB. This code sample is technically invalid C++ as it breaks the one definition rules, but it used to compile benignly before the change.

$ cat a.cpp
class dYj typedef *(*vfY)(class lYY *);
struct Mxl {
  Mxl(vfY, int, const char *, int, const char *, const char *, const char *,
      bool);
  vfY AvQ;
};
Mxl::Mxl(vfY, int, const char *, int, const char *, const char *, const char *,
         bool) {}
$ cat b.cpp
class dYj;
struct Mxl {
  Mxl(dYj *(class lYY *), int, const char *, int, const char *, const char *,
      const char *, bool = true);
} a(0, 0, 0, 0, 0, 0, 0);

$ clang++ -c a.cpp -o a.cpp.o -flto
$ clang++ -c b.cpp -o b.cpp.o -flto
$ llvm-lto a.cpp.o b.cpp.o

gives the assertion:

llvm-lto: Casting.h:255: typename llvm::cast_retty<X,Y*>::ret_type
llvm::cast(Y*) [with X = llvm::Function; Y = llvm::Constant; typename llvm::cast_retty<X, Y*>::ret_type = llvm::Function*]:
Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.

It would seem better if the compiler could give an error in this case rather than aborting with an assertion.

**Comment by xgupta** [comment]
It is fixed on trunk, tested on local clang-19.

llvm-lto --version                                      
LLVM (http://llvm.org/):
  LLVM version 19.0.0git
  DEBUG build with assertions.
