### ISSUE TITLE
[InstCombine][DagCombine] Improve Signed Truncation Check pattern

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#37497]
|  |  |
| --- | --- |
| Bugzilla Link | [38149](https://llvm.org/bz38149) |
| Version | trunk |
| OS | Linux |
| CC | @topperc,@RKSimon,@rotateright |

## Extended Description 
As disscussed in https://reviews.llvm.org/D49179#1158957 and later:
https://rise4fun.com/Alive/Bd4 <- the ir can be improved
https://godbolt.org/g/xbCLBB   <- the backend will likely want to revert that always.

**Comment by RKSimon** [comment]
@LebedevRI Is there anything left to do for this?  https://alive2.llvm.org/ce/z/TPr2Pv

Both of these get optimized to 'ult':
```
define i1 @src(i16 %x) {
  %old0 = shl i16 %x, 8
  %old1 = ashr exact i16 %old0, 8
  %ret = icmp eq i16 %old1, %x
  ret i1 %ret
}

define i1 @tgt(i16 %x) {
  %new0 = icmp slt i16 %x, 128
  %new1 = icmp sgt i16 %x, -129
  %ret = and i1 %new1, %new0
  ret i1 %ret
}

define i1 @ult(i16 %x) {
  %1 = add i16 %x, 128
  %2 = icmp ult i16 %1, 256
  ret i1 %2
}
```
which x86 efficiently lowers:
```
ult: # @ult
  movsbl %dil, %eax
  cmpw %di, %ax
  sete %al
  retq
```

**Comment by LebedevRI** [comment]
I don't know. Let's just assume that there is nothing left to do here.
