### ISSUE TITLE
Crash on valid: Local instantiation of template using module-exported type

### ISSUE THREAD

**Issue by dwblaikie** [llvm/llvm-project#37512]
|  |  |
| --- | --- |
| Bugzilla Link | [38164](https://llvm.org/bz38164) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Reproduction steps:

m1.cppm:
  export module m1;
  export class t1 { };

m1.cpp:
  module m1;
  template <typename T> void f2() {}
  void f1() { f2<t1>(); }

$ clang++-tot -fmodules-ts -c -std=c++17 --precompile m1.cppm
$ clang++-tot -fmodules-ts -c -std=c++17 m1.cpp -fmodule-file=m1.pcm

Crashes:

./build.sh
clang-5.0: /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/AST/Decl.cpp:1422: clang::LinkageInfo clang::LinkageComputer::getLVForDecl(const clang::NamedDecl *, clang::LVComputationKind): Assertion `D->getCachedLinkage() == LV.getLinkage()' failed.
Stack dump:
0.      Program arguments: /usr/local/google/home/blaikie/dev/llvm/build/default/bin/clang-5.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name m1.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /usr/local/google/home/blaikie/dev/scratch/modules_crash/m1.gcno -resource-dir /usr/local/google/home/blaikie/dev/llvm/build/default/lib/clang/7.0.0 -internal-isystem /usr/local/google/home/blaikie/install/bin/../lib/gcc/x86_64-pc-linux-gnu/8.1.0/../../../../include/c++/8.1.0 -internal-isystem /usr/local/google/home/blaikie/install/bin/../lib/gcc/x86_64-pc-linux-gnu/8.1.0/../../../../include/c++/8.1.0/x86_64-pc-linux-gnu -internal-isystem /usr/local/google/home/blaikie/install/bin/../lib/gcc/x86_64-pc-linux-gnu/8.1.0/../../../../include/c++/8.1.0/backward -internal-isystem /usr/local/include -internal-isystem /usr/local/google/home/blaikie/dev/llvm/build/default/lib/clang/7.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++17 -fdeprecated-macro -fdebug-compilation-dir /usr/local/google/home/blaikie/dev/scratch/modules_crash -ferror-limit 19 -fmessage-length 278 -fmodules-ts -fno-implicit-modules -fmodule-file=m1.pcm -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o m1.o -x c++ m1.cpp 
1.      <eof> parser at end of file
2.      Per-file LLVM IR generation
3.      m1.cpp:3:28: Generating code for declaration 'f2'
#&#8203;0 0x0000000006c5f2b9 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /usr/local/google/home/blaikie/dev/llvm/src/lib/Support/Unix/Signals.inc:490:11
#&#8203;1 0x0000000006c5f469 PrintStackTraceSignalHandler(void*) /usr/local/google/home/blaikie/dev/llvm/src/lib/Support/Unix/Signals.inc:554:1
#&#8203;2 0x0000000006c5d756 llvm::sys::RunSignalHandlers() /usr/local/google/home/blaikie/dev/llvm/src/lib/Support/Signals.cpp:66:5
#&#8203;3 0x0000000006c5fa97 SignalHandler(int) /usr/local/google/home/blaikie/dev/llvm/src/lib/Support/Unix/Signals.inc:353:1
#&#8203;4 0x00007f97e777f0c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x110c0)
#&#8203;5 0x00007f97e6315fcf gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x32fcf)
#&#8203;6 0x00007f97e63173fa abort (/lib/x86_64-linux-gnu/libc.so.6+0x343fa)
#&#8203;7 0x00007f97e630ee37 (/lib/x86_64-linux-gnu/libc.so.6+0x2be37)
#&#8203;8 0x00007f97e630eee2 (/lib/x86_64-linux-gnu/libc.so.6+0x2bee2)
#&#8203;9 0x000000000aaafea9 clang::LinkageComputer::getLVForDecl(clang::NamedDecl const*, clang::LVComputationKind) /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/AST/Decl.cpp:1422:5
#&#8203;10 0x000000000aab1443 clang::LinkageComputer::getDeclLinkageAndVisibility(clang::NamedDecl const*) /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/AST/Decl.cpp:1455:10
#&#8203;11 0x000000000aab2e0b clang::NamedDecl::getLinkageAndVisibility() const /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/AST/Decl.cpp:1071:28
#&#8203;12 0x000000000715c91e clang::CodeGen::CodeGenModule::setGlobalVisibility(llvm::GlobalValue*, clang::NamedDecl const*) const /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/CodeGen/CodeGenModule.cpp:715:23
#&#8203;13 0x000000000715ce37 clang::CodeGen::CodeGenModule::setGlobalVisibilityAndLocal(llvm::GlobalValue*, clang::NamedDecl const*) const /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/CodeGen/CodeGenModule.cpp:824:15
#&#8203;14 0x000000000715cdf8 clang::CodeGen::CodeGenModule::setGVProperties(llvm::GlobalValue*, clang::GlobalDecl) const /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/CodeGen/CodeGenModule.cpp:813:1
#&#8203;15 0x0000000007168cbf clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/CodeGen/CodeGenModule.cpp:3710:30
#&#8203;16 0x0000000007162bad clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/CodeGen/CodeGenModule.cpp:2340:12
#&#8203;17 0x0000000007159c2e clang::CodeGen::CodeGenModule::EmitDeferred() /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/CodeGen/CodeGenModule.cpp:1756:10
#&#8203;18 0x00000000071582f5 clang::CodeGen::CodeGenModule::Release() /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/CodeGen/CodeGenModule.cpp:393:3
#&#8203;19 0x0000000007b43192 (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/CodeGen/ModuleBuilder.cpp:269:11
#&#8203;20 0x0000000007b3deee clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/CodeGen/CodeGenAction.cpp:236:14
#&#8203;21 0x00000000095df013 clang::ParseAST(clang::Sema&, bool, bool) /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/Parse/ParseAST.cpp:177:12
#&#8203;22 0x0000000007992562 clang::ASTFrontendAction::ExecuteAction() /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/Frontend/FrontendAction.cpp:1013:1
#&#8203;23 0x0000000007b3ba22 clang::CodeGenAction::ExecuteAction() /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/CodeGen/CodeGenAction.cpp:1044:1
#&#8203;24 0x0000000007991fa0 clang::FrontendAction::Execute() /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/Frontend/FrontendAction.cpp:914:7
#&#8203;25 0x00000000078670e9 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/Frontend/CompilerInstance.cpp:962:7
#&#8203;26 0x0000000007b25fef clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:257:8
#&#8203;27 0x00000000041d818e cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/tools/driver/cc1_main.cpp:216:11
#&#8203;28 0x00000000041cb462 ExecuteCC1Tool(llvm::ArrayRef<char const*>, llvm::StringRef) /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/tools/driver/driver.cpp:310:5
#&#8203;29 0x00000000041ca094 main /usr/local/google/home/blaikie/dev/llvm/src/tools/clang/tools/driver/driver.cpp:382:5
#&#8203;30 0x00007f97e63032b1 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b1)
#&#8203;31 0x00000000041c902a _start (/usr/local/google/home/blaikie/dev/llvm/build/default/bin/clang-5.0+0x41c902a)

**Comment by Endilll** [comment]
Appears to be fixed in Clang 15.
Clang 14 crash:
```
clang++: /home/tonik/llvm-project/clang/lib/AST/Decl.cpp:1500:
clang::LinkageInfo clang::LinkageComputer::getLVForDecl(const clang::NamedDecl *, clang::LVComputationKind):
Assertion `D->getCachedLinkage() == LV.getLinkage()' failed.

PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /opt/compiler-explorer/clang-14.0.0-assert/bin/clang++ -fmodules-ts -c -std=c++17 m1.cpp -fmodule-file=m1.pcm
1.      <eof> parser at end of file
2.      Per-file LLVM IR generation
3.      m1.cpp:2:30: Generating code for declaration 'f2'
 #0 0x000056420c815cd3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x34a6cd3)
 #1 0x000056420c813abe llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x34a4abe)
 #2 0x000056420c81503d llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x34a603d)
 #3 0x000056420c782c83 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) CrashRecoveryContext.cpp:0:0
 #4 0x000056420c782e2e CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #5 0x00007f72c6642520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #6 0x00007f72c6696a7c pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x96a7c)
 #7 0x00007f72c6642476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #8 0x00007f72c66287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #9 0x00007f72c662871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
#10 0x00007f72c6639e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#11 0x000056420efbd605 clang::LinkageComputer::getLVForDecl(clang::NamedDecl const*, clang::LVComputationKind) (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x5c4e605)
#12 0x000056420efc02e9 clang::NamedDecl::getLinkageAndVisibility() const (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x5c512e9)
#13 0x000056420cbe47f1 clang::CodeGen::CodeGenModule::setGlobalVisibility(llvm::GlobalValue*, clang::NamedDecl const*) const (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x38757f1)
#14 0x000056420cbe4de0 clang::CodeGen::CodeGenModule::setGVProperties(llvm::GlobalValue*, clang::GlobalDecl) const (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x3875de0)
#15 0x000056420cbf50f0 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x38860f0)
#16 0x000056420cbeda92 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x387ea92)
#17 0x000056420cbe051f clang::CodeGen::CodeGenModule::EmitDeferred() (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x387151f)
#18 0x000056420cbde979 clang::CodeGen::CodeGenModule::Release() (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x386f979)
#19 0x000056420d7b96d4 (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) ModuleBuilder.cpp:0:0
#20 0x000056420d7b60fe clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) crtstuff.c:0:0
#21 0x000056420e34cac4 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x4fddac4)
#22 0x000056420d198e20 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x3e29e20)
#23 0x000056420d1137bf clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x3da47bf)
#24 0x000056420d262383 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x3ef3383)
#25 0x000056420a569e84 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x11fae84)
#26 0x000056420a567d40 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#27 0x000056420cfa4bc2 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::$_1>(long) Job.cpp:0:0
#28 0x000056420c782b97 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x3413b97)
#29 0x000056420cfa4600 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x3c35600)
#30 0x000056420cf70068 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x3c01068)
#31 0x000056420cf70337 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x3c01337)
#32 0x000056420cf891a8 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x3c1a1a8)
#33 0x000056420a567378 main (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x11f8378)
#34 0x00007f72c6629d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#35 0x00007f72c6629e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#36 0x000056420a564bce _start (/opt/compiler-explorer/clang-14.0.0-assert/bin/clang+++0x11f5bce)
clang-14: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 14.0.0 (https://github.com/llvm/llvm-project 329fda39c507e8740978d10458451dcdb21563be)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/compiler-explorer/clang-14.0.0-assert/bin
```
