### ISSUE TITLE
Enormous amounts of LLVM tests fail on debian sid when gcc-8 is present.

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#37520]
|  |  |
| --- | --- |
| Bugzilla Link | [38172](https://llvm.org/bz38172) |
| Version | trunk |
| OS | Linux |
| CC | @AaronBallman,@zmodem,@RKSimon,@stoklund,@sylvestre |

## Extended Description 
Expensive checks enable -D_GLIBCXX_DEBUG
And tablegen fails, with messages like:

/build/llvm-build-Clang6-release$ ninja -j1
[1/3099] Building IntrinsicImpl.inc...
FAILED: include/llvm/IR/IntrinsicImpl.inc.tmp 
cd /build/llvm-build-Clang6-release && /build/llvm-build-Clang6-release/bin/llvm-tblgen -gen-intrinsic-impl -I /build/llvm/include/llvm/IR -I /build/llvm/include /build/llvm/include/llvm/IR/Intrinsics.td -o include/llvm/IR/IntrinsicImpl.inc.tmp -d include/llvm/IR/IntrinsicImpl.inc.d
/usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/debug/safe_container.h:83:
Error: attempt to self move assign.

Objects involved in the operation:
    sequence "this" @ 0x0x7fe883407a78 {
    }
#&#8203;0 0x0000000000458401 __interceptor_backtrace.part.117 (/build/llvm-build-Clang6-release/bin/llvm-tblgen+0x458401)
#&#8203;1 0x00007fe88751aaf2 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /build/llvm/lib/Support/Unix/Signals.inc:490:13
#&#8203;2 0x00007fe887514874 llvm::sys::RunSignalHandlers() /build/llvm/lib/Support/Signals.cpp:68:18
#&#8203;3 0x00007fe88751b1bf SignalHandler(int) /build/llvm/lib/Support/Unix/Signals.inc:343:3
#&#8203;4 0x00007fe886f328e0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x128e0)
#&#8203;5 0x00007fe886a3df3b gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x35f3b)
#&#8203;6 0x00007fe886a3f2f1 abort (/lib/x86_64-linux-gnu/libc.so.6+0x372f1)
#&#8203;7 0x00007fe886e2677d __strtof_l (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x8e77d)
#&#8203;8 0x0000000000863179 swap<llvm::MVT::SimpleValueType *> /usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/move.h:193:19
#&#8203;9 0x0000000000863179 _M_swap_data /usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h:112:0
#&#8203;10 0x0000000000863179 _M_move_assign /usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h:1680:0
#&#8203;11 0x0000000000863179 operator= /usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h:601:0
#&#8203;12 0x0000000000863179 std::__debug::vector<llvm::MVT::SimpleValueType, std::allocator<llvm::MVT::SimpleValueType> >::operator=(std::__debug::vector<llvm::MVT::SimpleValueType, std::allocator<llvm::MVT::SimpleValueType> >&&) /usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/debug/vector:231:0
#&#8203;13 0x0000000000862a1d operator= /build/llvm/utils/TableGen/CodeGenIntrinsics.h:40:10
#&#8203;14 0x0000000000862a1d llvm::CodeGenIntrinsic::operator=(llvm::CodeGenIntrinsic&&) /build/llvm/utils/TableGen/CodeGenIntrinsics.h:27:0
#&#8203;15 0x0000000000861c88 swap<llvm::CodeGenIntrinsic> /usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/move.h:195:11
#&#8203;16 0x0000000000861c88 void std::iter_swap<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<llvm::CodeGenIntrinsic*, std::__cxx1998::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > >, std::__debug::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > >, __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<llvm::CodeGenIntrinsic*, std::__cxx1998::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > >, std::__debug::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > > >(__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<llvm::CodeGenIntrinsic*, std::__cxx1998::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > >, std::__debug::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > >, __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<llvm::CodeGenIntrinsic*, std::__cxx1998::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > >, std::__debug::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > >) /usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_algobase.h:148:0
#&#8203;17 0x0000000000861189 ~_Safe_iterator_base /usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/debug/safe_base.h:100:36
#&#8203;18 0x0000000000861189 ~_Safe_iterator /usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/debug/safe_iterator.h:86:0
#&#8203;19 0x0000000000861189 void std::shuffle<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<llvm::CodeGenIntrinsic*, std::__cxx1998::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > >, std::__debug::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > >, std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>&>(__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<llvm::CodeGenIntrinsic*, std::__cxx1998::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > >, std::__debug::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > >, __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<llvm::CodeGenIntrinsic*, std::__cxx1998::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > >, std::__debug::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > >, std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>&&&) /usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_algo.h:3844:0
#&#8203;20 0x000000000083c57c ~_Safe_iterator /usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/debug/safe_iterator.h:86:11
#&#8203;21 0x000000000083c57c sort<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<llvm::CodeGenIntrinsic *, std::__cxx1998::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > >, std::__debug::vector<llvm::CodeGenIntrinsic, std::allocator<llvm::CodeGenIntrinsic> > >, (lambda at /build/llvm/utils/TableGen/CodeGenTarget.cpp:517:14)> /build/llvm/include/llvm/ADT/STLExtras.h:871:0
#&#8203;22 0x000000000083c57c llvm::CodeGenIntrinsicTable::CodeGenIntrinsicTable(llvm::RecordKeeper const&, bool) /build/llvm/utils/TableGen/CodeGenTarget.cpp:516:0
#&#8203;23 0x0000000000a91e32 (anonymous namespace)::IntrinsicEmitter::run(llvm::raw_ostream&, bool) /build/llvm/utils/TableGen/IntrinsicEmitter.cpp:62:25
#&#8203;24 0x0000000000a9a645 _M_data /usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.h:176:28
#&#8203;25 0x0000000000a9a645 _M_is_local /usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.h:211:0
#&#8203;26 0x0000000000a9a645 _M_dispose /usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.h:220:0
#&#8203;27 0x0000000000a9a645 ~basic_string /usr/bin/../lib64/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.h:657:0
#&#8203;28 0x0000000000a9a645 ~IntrinsicEmitter /build/llvm/utils/TableGen/IntrinsicEmitter.cpp:28:0
#&#8203;29 0x0000000000a9a645 llvm::EmitIntrinsicImpl(llvm::RecordKeeper&, llvm::raw_ostream&, bool) /build/llvm/utils/TableGen/IntrinsicEmitter.cpp:853:0
#&#8203;30 0x0000000000c382dc (anonymous namespace)::LLVMTableGenMain(llvm::raw_ostream&, llvm::RecordKeeper&) /build/llvm/utils/TableGen/TableGen.cpp:0:5
#&#8203;31 0x00007fe886ff7b9e llvm::TableGenMain(char*, bool (*)(llvm::raw_ostream&, llvm::RecordKeeper&)) /build/llvm/lib/TableGen/Main.cpp:109:7
#&#8203;32 0x0000000000c3742e main /build/llvm/utils/TableGen/TableGen.cpp:247:10
#&#8203;33 0x00007fe886a2ab17 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x22b17)
#&#8203;34 0x00000000003d702a _start (/build/llvm-build-Clang6-release/bin/llvm-tblgen+0x3d702a)
Stack dump:
0.      Program arguments: /build/llvm-build-Clang6-release/bin/llvm-tblgen -gen-intrinsic-impl -I /build/llvm/include/llvm/IR -I /build/llvm/include /build/llvm/include/llvm/IR/Intrinsics.td -o include/llvm/IR/IntrinsicImpl.inc.tmp -d include/llvm/IR/IntrinsicImpl.inc.d 
Aborted
ninja: build stopped: subcommand failed.

**Comment by arsenm** [comment]
Old build issue
