### ISSUE TITLE
misc-unconventional-assign-operator incorrectly warns about type

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37530]
|  |  |
| --- | --- |
| Bugzilla Link | [38182](https://llvm.org/bz38182) |
| Version | unspecified |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
When running clang-tidy against the following code it claims that the return type is not a reference, but it is (the code compiles and prints out "is reference: 1"):

clang-tidy '-checks=-*,misc-unconventional-assign-operator' main.cc -- -std=c++11 -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/

:7:3: warning: operator=() should return 'Bug&' [misc-unconventional-assign-operator]
  std::enable_if<true, Bug&>::type
  ^
Suppressed 34 warnings (34 in non-user code).

#include <memory>
#include <string>
#include <iostream>

class Bug {
 public:
  std::enable_if<true, Bug&>::type
  operator = (const Bug& rhs) {
    if (val_ != rhs.val_) {
      val_ = rhs.val_;
    }
    return *this;
  }

 private:
  int val_ = 0;
};

int main(int /*argc*/, const char* /*argv*/[]) {
  Bug p1;
  Bug p2;
  p1 = p2;

  std::cout << "is reference: " << std::is_reference<std::enable_if<true, Bug&>::type>::value << std::endl;

  typedef Bug& BugRef;
  std::cout << "BugRef is reference: " << std::is_reference<BugRef>::value << std::endl;

  return 0;
}

**Comment by PiotrZSL** [comment]
Should be already fixed by https://reviews.llvm.org/D114197.
Original code were missing hasCanonicalType.
