### ISSUE TITLE
false positive null pointer analysis due to not inlined list operator == and !=

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37547]
|  |  |
| --- | --- |
| Bugzilla Link | [38199](https://llvm.org/bz38199) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
To reproduce:

$ cat /tmp/null.cpp
#include <list>
typedef std::list<int*> MyList;
extern MyList &mylist;
struct A {
  A();
  void f0();
};
extern void f1(), f2();
void foo()
{
  A *p = nullptr;
  MyList::iterator begin = mylist.begin();
  MyList::iterator end = mylist.end();
  if (begin != end) {
    f1();
    p = new A();
  }
  if (!(begin != end)) {
    f2();
    if (p != nullptr) delete p;
    p = new A();
  }
  p->f0();
  delete p;
}

$ clang-tidy -checks=-*,clang-analy* /tmp/null.cpp -- -std=c++11 -O2
/tmp/null.cpp:23:3: warning: Called C++ object pointer is null [clang-analyzer-core.CallAndMessage]
  p->f0();
  ^
/tmp/null.cpp:11:3: note: 'p' initialized to a null pointer value
  A *p = nullptr;
  ^
/tmp/null.cpp:14:7: note: Assuming the condition is false
  if (begin != end) {
      ^
/tmp/null.cpp:14:3: note: Taking false branch
  if (begin != end) {
  ^
/tmp/null.cpp:18:7: note: Assuming the condition is false
  if (!(begin != end)) {
      ^
/tmp/null.cpp:18:3: note: Taking false branch
  if (!(begin != end)) {
  ^
/tmp/null.cpp:23:3: note: Called C++ object pointer is null
  p->f0();
  ^

If compiled with clang -O2, we can see that all calls to the list and iterator functions can be inlined and it is impossible to have both !(begin != end) and !!(begin != end)

The clang static analyzer does not seem be inlining the != and == operators of the list::iterator.

**Comment by JOE1994** [comment]
Seems to be fixed with `clang 18.1.0` : https://godbolt.org/z/54xa8vrPr
