### ISSUE TITLE
Passing by value to inlined function inhibits optimisation when it should not

### ISSUE THREAD

**Issue by 1feda113-18e2-42e3-8624-9c17d4d32ec3** [llvm/llvm-project#37561]
|  |  |
| --- | --- |
| Bugzilla Link | [38213](https://llvm.org/bz38213) |
| Version | trunk |
| OS | Linux |
| CC | @SuperV1234 |

## Extended Description 
#include <string>

inline size_t calc(std::string a, std::string b)
{
    return a.size() + b.size();
}

int main()
{
    std::string a = "Hello world", b = "Goodbye world";
    return calc(a, b);
}

This should generate:

main:                                   # @&#8203;main
        mov     eax, 24
        ret

But it instead generates this spew with clang trunk:

https://godbolt.org/g/2nU993

**Comment by LebedevRI** [comment]
This appears to have been fully resolved in LLVM13: https://gcc.godbolt.org/z/dT5o6n9fa
