### ISSUE TITLE
Remove register allocator bug workaround

### ISSUE THREAD

**Issue by dylanmckay** [llvm/llvm-project#37572]
|  |  |
| --- | --- |
| Bugzilla Link | [38224](https://llvm.org/bz38224) |
| Version | trunk |
| OS | All |

## Extended Description 
The register allocator does not handle certain functions that use the 'LDDWRdPtrQ' instructions which have high register pressure.

The error message is:

LLVM ERROR: ran out of registers during register allocation

In order to work around this, we restricted the allowable registers of LDDWRdPtrQ to disallow Z.

First noticed in https://github.com/avr-rust/rust/issues/37

**Comment by benshi001** [comment]
Now `LDDWRdPtrQ` can use `Z` as base address without any error.

```
int aff(int *arr) {
        return arr[4];
}
```

is compiled to 
```
aff:                                    ; @aff
; %bb.0:                                ; %entry
        movw    r30, r24
        ldd     r24, Z+8
        ldd     r25, Z+9
        ret
```
