### ISSUE TITLE
preserve_all calling convention is broken on AArch64

### ISSUE THREAD

**Issue by m-gupta** [llvm/llvm-project#37577]
|  |  |
| --- | --- |
| Bugzilla Link | [38229](https://llvm.org/bz38229) |
| Version | trunk |
| OS | Linux |
| CC | @efriedma-quic,@francisvm,@jyknight,@m-gupta,@nickdesaulniers,@stephenhines |

## Extended Description 
$ cat test.c 
void __attribute__((preserve_all)) foo(void *ptr) { }

$ clang -c test.c -> compiles for x86_64
$ clang -c -target aarch64-unknown-linux-gnu

fatal error: error in backend: Unsupported calling convention.

**Comment by ostannard** [comment]
This was implemented by d75e70d7ae1f84cea71f0be5fbee836bdc22138a
