### ISSUE TITLE
Clang-tidy fix is removing business logic.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37588]
|  |  |
| --- | --- |
| Bugzilla Link | [38240](https://llvm.org/bz38240) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @LegalizeAdulthood |

## Extended Description 
OS windows 10 (64)
C:\Program Files\LLVM\bin>clang-tidy -version
LLVM (http://llvm.org/):
  LLVM version 5.0.0
  Optimized build.
  Default target: x86_64-pc-windows-msvc
  Host CPU: skylake

Ran clang-tidy fix on some files in my project, it seems like the [readability-simplify-boolean-expr] is a bit to aggressive in removing code.

Here is the LOG:
10: C:\Repository\###\BaseInstance.cpp
2860 warnings and 1 error generated.
Error while processing C:\Repository\###\BaseInstance.cpp.
C:\Repository\###\..\..\source\code\include\###/lib/stdafx.h(26): error [clang-diagnostic-error]: '###/logging/facade/logger.h' file not found 
#include <###core/logging/facade/logger.h>
         ^
C:\Repository\###\BaseInstance.cpp(27): warning [modernize-use-equals-default]: use '= default' to define a trivial default constructor 
BaseInstance::BaseInstance()
              ^
C:\Repository\###\BaseInstance.cpp(39): warning [google-readability-todo]: missing username/bug in TODO 
        //TODO do stuff here.
        ^~~~~~~~~~~~~~~~~~~~~
        // TODO(###): do stuff here.
C:\Repository\###\BaseInstance.cpp(39): message: FIX-IT applied suggested code changes
C:\Repository\###\BaseInstance.cpp(40): warning [readability-simplify-boolean-expr]: redundant boolean literal in conditional return statement 
        return true;
               ^
C:\Repository\###\BaseInstance.cpp(84): warning [readability-simplify-boolean-expr]: redundant boolean literal in conditional return statement 
        return true;
~~~~~~~~~~~~~~~^~~~~
C:\Repository\###\BaseInstance.cpp(79): message: FIX-IT applied suggested code changes
    if (it != m_Storage.end())
    ^
clang-tidy applied 2 of 2 suggested fixes.


And here is the DIFF of this file:
--- a/source/code/src/KcsAggregator-Lib/BaseInstance.cpp
+++ b/source/code/src/KcsAggregator-Lib/BaseInstance.cpp
@@ -36,7 +36,7 @@ bool BaseInstance::RegisterDataValueBinding(
     const auto it = m_Storage.find(elementId);
     if (it != m_Storage.end())
     {
-        //TODO do stuff here.
+        // TODO(###): do stuff here.
         return true;
     }
     return false;
@@ -76,14 +76,7 @@ bool BaseInstance::GetDataValue(
 {
     const ElementId subId (0, TupleNumeric(0, elementId.GetSubId()));
     const auto it = m_Storage.find(subId);
-    if (it != m_Storage.end())
-    {
-        value = DataValue(it->second,
-                            AttributeType::Value,
-                            SystemTime::GetSystemTime());
-        return true;
-    }
-    return false;
+    return ;
 }

The same thing happened i many files, and seems to be removing whole if clauses.
@@ -683,13 +684,7 @@ bool ConfigurationReader::BuildGraph()
     }
     while (false == m_BrowseGraphHelper.GetResult(requestId, response));

-    if (IsGood(response.GetStatusCode()))
-    {
-        response.GetGraph(m_Graph);
-        return true;
-    }
-
-    return false;
+    return ;
 }

**Comment by LegalizeAdulthood** [comment]
Is there a way we can contact the original requester of an issue when they haven't been mapped to a github user?

**Comment by joker-eph** [comment]
You have their email in Bugzilla when logged-in I believe

**Comment by LegalizeAdulthood** [comment]
Since I asked the original poster for a repro 3 years ago and never received an answer, I'm going to suggest this bug be closed.

**Comment by LegalizeAdulthood** [comment]
@EugeneZelenko Can you close this issue, please?  Thanks.

**Comment by EugeneZelenko** [comment]
Looks like I could not close issues opened by other users.

**Comment by LegalizeAdulthood** [comment]
@llvmbot Does anyone know how issues opened by `llvmbot` can be closed?
