### ISSUE TITLE
clang-format crash for a specific config

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37593]
|  |  |
| --- | --- |
| Bugzilla Link | [38245](https://llvm.org/bz38245) |
| Version | 6.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
$ clang-format -style=file test.cpp 
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x2a)[0x7f90230a8e5a]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZN4llvm3sys17RunSignalHandlersEv+0x3e)[0x7f90230a701e]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(+0x89a16c)[0x7f90230a716c]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f9021de34b0]
clang-format[0x452316]
clang-format[0x456601]
clang-format[0x45299b]
clang-format[0x42f2b6]
clang-format[0x44262f]
clang-format[0x42a377]
clang-format[0x42a3dd]
clang-format[0x42f85c]
clang-format[0x42fe96]
clang-format[0x4112d8]
clang-format[0x40dac0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f9021dce830]
clang-format[0x40dbc9]
Segmentation fault (core dumped)

$ clang-format --version
clang-format version 6.0.1-svn334776-1~exp1~20180627160618.85 (branches/release_60)

$ cat .clang-format
BasedOnStyle:  Google
BreakBeforeBraces: Allman
AllowShortBlocksOnASingleLine: true

$ cat test.cpp
auto cloneColumnDefs = [very_long_lambda_name](very_long_type_name something[], very_very_long_type_name attributes[]) {
    for (int i = 0; i < 3; i++) {
        very_long_lambda_name(something[i], attributes[i]);
    }
};

system:
Ubuntu 16.04.2 LTS
$ uname -or
4.13.0-45-generic GNU/Linux

**Comment by mydeveloperday** [comment]
From at least v8 this doesn't crash any more

```
$ clang-format test1.cpp
auto cloneColumnDefs =
    [very_long_lambda_name](very_long_type_name something[],
                            very_very_long_type_name attributes[])
{
  for (int i = 0; i < 3; i++)
  {
    very_long_lambda_name(something[i], attributes[i]);
  }
};
```
