### ISSUE TITLE
readability-container-size-empty should handle std::string length()

### ISSUE THREAD

**Issue by EugeneZelenko** [llvm/llvm-project#37603]
|  |  |
| --- | --- |
| Bugzilla Link | [38255](https://llvm.org/bz38255) |
| Version | unspecified |
| OS | All |
| CC | @Xazax-hun |

## Extended Description 
length() is synonym for size in std::string and should be handled in same way as size().

**Comment by PiotrZSL** [comment]
Actually code is waiting for review.

**Comment by EugeneZelenko** [comment]
This was done because of unification of labels (`beginner` -> `good first issue`).
