### ISSUE TITLE
6.0.1 Release Notes

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37627]
|  |  |
| --- | --- |
| Bugzilla Link | [38279](https://llvm.org/bz38279) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @ryandesign,@tstellar |

## Extended Description 
The 6.0.1 Release notes
( https://releases.llvm.org/6.0.1/docs/ReleaseNotes.html )
are in fact the 6.0.0 release notes.

I went back and noticed that the sub-minor version release notes are just copies of the minor version notes (this wasn't a comprehensive search).  I came across this when I received the 6.0.1 release email which pointed to the release notes; first line:

"LLVM 6.0.1 is now available! Download it now, or read the release notes."

Much to my chagrin, these release notes don't in any way indicate what was changed between 6.0.0 and 6.0.1.

**Comment by tlattner** [comment]
@tstellar Do you want to update this or should we just close it since its been awhile since 6.0.1.

**Comment by tstellar** [comment]
@tlattner This not actually a bug.  There are no separate 6.0.1 release notes.
