### ISSUE TITLE
Mis-counting of braces with redundant nested scopes

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37662]
|  |  |
| --- | --- |
| Bugzilla Link | [38314](https://llvm.org/bz38314) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @cpplearner |

## Extended Description 
This code formats poorly:
```cpp
namespace n {
void foo() {
    {
        {
            {
                statement();
                if (false) {
                }
            }
        }
        {

        }
    }
}
}
```
Formatter output (default settings, HEAD, reproduced here: https://zed0.co.uk/clang-format-configurator/):
```cpp
namespace n {
void foo() {
  {
    {{statement();
    if (false) {
    }
  }
}
{}
}
}
}
```

**Comment by rymiel** [comment]
Duplicate of https://github.com/llvm/llvm-project/issues/33891
