### ISSUE TITLE
Mismatch between SVN users and Phabricator users can cause revisions on Phabricator to be attributed to the wrong person

### ISSUE THREAD

**Issue by marco-c** [llvm/llvm-project#37677]
|  |  |
| --- | --- |
| Bugzilla Link | [38329](https://llvm.org/bz38329) |
| Version | unspecified |
| OS | Linux |
| CC | @sylvestre |

## Extended Description 
My SVN username is marco, my username on Phabricator is marco-c. Marco Romano's username on Phabricator is marco.
My commits on Phabricator are attributed to Marco Romano, e.g. https://reviews.llvm.org/rL338013.

**Comment by arsenm** [comment]
The move to pull requests will avoid this type of issue
