### ISSUE TITLE
LLDB installation issue

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37708]
|  |  |
| --- | --- |
| Bugzilla Link | [38360](https://llvm.org/bz38360) |
| Version | 6.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
1. the test env is:
bash-4.2$ uname -a
Linux alex 4.17.2-1.el7.elrepo.x86_64 #&#8203;1 SMP Sat Jun 16 11:18:11 EDT
2018 x86_64 x86_64 x86_64 GNU/Linux
bash-4.2$ python --version
Python 2.7.5
bash-4.2$

2. purpose:
   install the lldb 6.0.1 from the source code

3. the problem found 
  a. during the installation, it reported:
CMake Error at scripts/cmake_install.cmake:41 (file):
  file INSTALL cannot find "/home/alex/Downloads/lldb/lib/python2.7".

  b. after the installation completed:
   (lldb) script
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named lldb.embedded_interpreter

4.both can be fixed by moving the python files, but it seem that there is some wrong.

5. the deatil of installation & my workaround was recorded in my blog:

https://zhuanlan.zhihu.com/p/40793869

**Comment by DavidSpickett** [comment]
This was probably a genuine issue back then but is likely completely different now.
