### ISSUE TITLE
Buggy note

### ISSUE THREAD

**Issue by Abramo-Bagnara** [llvm/llvm-project#37730]
|  |  |
| --- | --- |
| Bugzilla Link | [38382](https://llvm.org/bz38382) |
| Version | trunk |
| OS | Linux |

## Extended Description 
$ cat a.c
extern double printf;
$ clang-7 -c a.c
a.c:1:15: error: redefinition of 'printf' as different kind of symbol
extern double printf;
              ^
a.c:1:15: note: unguarded header; consider using #ifdef guards or #pragma once
a.c:1:15: note: previous definition is here
1 error generated.

The first note is completely wrong (also the second is weird, but it seems a less severe problem).

**Comment by AaronBallman** [comment]
Closing as a duplicate of #15523
