### ISSUE TITLE
Weird indentation for ref-qualified, noexcept, template methods

### ISSUE THREAD

**Issue by 0775a785-4f8d-448e-9da0-14f81adf2169** [llvm/llvm-project#37743]
|  |  |
| --- | --- |
| Bugzilla Link | [38395](https://llvm.org/bz38395) |
| Version | 6.0 |
| OS | Linux |

## Extended Description 
This is a subset of llvm/llvm-project#36205  that I've found a precise, small trigger for. It only happens when a single method is all of ref-qualified, noexcept, and a template. This specific repo uses "AlwaysBreakTemplateDeclarations: true", but with a long enough template line that it would break there anyway, it repros even with default settings.

Repro:

> clang-format -style='{AlwaysBreakTemplateDeclarations: true}' example.cpp 
```cpp
struct Struct {
  // Weird indenetation for when all three are true for a single method:
  template <typename T>
      void ref_qualified_noexcept_template() && noexcept {}

  // Any two is fine though:

  void not_a_template() && noexcept {}

  template <typename T>
  void not_noexcept() && {}

  template <typename T>
  void not_ref_qualified() noexcept {}
};
```

**Comment by rymiel** [comment]
This was fixed by c5343e721ba7500513ee2887bfba5395285669c1.
