### ISSUE TITLE
The standard library header <cstdalign> is missing

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#37759]
|  |  |
| --- | --- |
| Bugzilla Link | [38411](https://llvm.org/bz38411) |
| Version | unspecified |
| OS | FreeBSD |
| CC | @mclow |

## Extended Description 
I found this problem on FreeBSD, which uses clang and llvm C++ library: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230230

cppreference says that there should be such standard header: https://en.cppreference.com/w/cpp/header/cstdalign

**Comment by frederick-vs-ja** [comment]
I think this issue is essentially fixed by a linked PR.
