### ISSUE TITLE
Duplicate label causes assembler crash

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37796]
|  |  |
| --- | --- |
| Bugzilla Link | [38448](https://llvm.org/bz38448) |
| Version | 6.0 |
| OS | Windows NT |
| Attachments | [Package with all bug artifacts](https://user-images.githubusercontent.com/60944935/143757858-e7443caa-2a2b-4e6c-b1b8-74ab906b7525.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

With clang 6.0.1:

C:\Users\fabio\clang-bug>"C:\Program Files\LLVM\bin\clang.exe" crash.s
crash.s:2:1: error: invalid symbol redefinition
.a:
^
Wrote crash dump file "C:\Users\fabio\AppData\Local\Temp\clang.exe-5b38c7.dmp"
0x00007FF68DA0F549 (0x000000003B001E25 0x00007FF68FC1FD58 0x0000000002000002 0x0000000000000001)
0x00007FF68DA0C34B (0x00000213D7C4FD60 0x00007FF68D40AD18 0x00000032F5D8CDD0 0x00007FF9BC72E60B)
0x00007FF68DA0250F (0x00007FF600000000 0x00007FF68D3D5105 0x00000032F5D8CDD0 0x0000003200000000)
0x00007FF68D9F845E (0x0000000000000010 0x00007FF60000000E 0x00000213D7C44C90 0x00007FF600000080)
0x00007FF68DA2C065 (0x0000000000000000 0x00007FF600000000 0x0000000000000002 0x00000032F5D8D3D0)
0x00007FF68C95C33A (0x0000000000000015 0x00007FF9BF3F70A0 0x00000000000006B0 0x00000000000000B8)
0x00007FF68C954766 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF68F589778 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF9BEE43034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FF9BF421431 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
clang.exe: error: clang integrated assembler command failed due to signal (use -v to see invocation)
clang version 6.0.1 (tags/RELEASE_601/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
clang.exe: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang.exe: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.

This bug does *not* happen on clang for Linux 6.0.0; this seems to be a Windows specific issue.

I minimized the crash.s file as much as possible; removing any of the 127 nops there gets rid of the bug (and the bug is still visible if you add more nops, or more unrelated instructions, between the labels and the jmp).

**Comment by Endilll** [comment]
Appears to be fixed in Clang 15.
Clang 14 crash:
```
clang-14: warning: unable to find a Visual Studio installation; try running Clang from a developer command prompt [-Wmsvc-not-found]
crash.s:2:1: error: symbol '.a' is already defined
.a:
^
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /media/hdd2tb/compiler-explorer/clang-assertions-14.0.0/bin/clang-14 -cc1as -triple x86_64-pc-windows-msvc19.20.0 -filetype obj -main-file-name crash.s -target-cpu x86-64 -fdebug-compilation-dir=/home/user/endill/llvm-reproducers/gh37796 -dwarf-debug-producer "clang version 14.0.0 (https://github.com/llvm/llvm-project.git 329fda39c507e8740978d10458451dcdb21563be)" -dwarf-version=4 -mrelocation-model pic -mincremental-linker-compatible --mrelax-relocations -o /tmp/crash-a0277d.o crash.s
 #0 0x00000000033956a0 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x0000000003392f5e SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f5d6545a510 (/lib/x86_64-linux-gnu/libc.so.6+0x3c510)
 #3 0x0000000002f3f765 (anonymous namespace)::WinCOFFObjectWriter::writeObject(llvm::MCAssembler&, llvm::MCAsmLayout const&) WinCOFFObjectWriter.cpp:0:0
 #4 0x0000000002eb67b6 llvm::MCAssembler::Finish() (/media/hdd2tb/compiler-explorer/clang-assertions-14.0.0/bin/clang-14+0x2eb67b6)
 #5 0x0000000002f09c67 llvm::MCStreamer::Finish(llvm::SMLoc) (/media/hdd2tb/compiler-explorer/clang-assertions-14.0.0/bin/clang-14+0x2f09c67)
 #6 0x0000000002f6eeb7 (anonymous namespace)::AsmParser::Run(bool, bool) AsmParser.cpp:0:0
 #7 0x0000000000ace263 ExecuteAssemblerImpl((anonymous namespace)::AssemblerInvocation&, clang::DiagnosticsEngine&) cc1as_main.cpp:0:0
 #8 0x0000000000acfb00 cc1as_main(llvm::ArrayRef<char const*>, char const*, void*) (/media/hdd2tb/compiler-explorer/clang-assertions-14.0.0/bin/clang-14+0xacfb00)
 #9 0x0000000000ac2efc ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#10 0x00000000009e79d1 main (/media/hdd2tb/compiler-explorer/clang-assertions-14.0.0/bin/clang-14+0x9e79d1)
#11 0x00007f5d654456ca __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#12 0x00007f5d65445785 call_init ./csu/../csu/libc-start.c:128:20
#13 0x00007f5d65445785 __libc_start_main ./csu/../csu/libc-start.c:347:5
#14 0x0000000000ac2ac5 _start (/media/hdd2tb/compiler-explorer/clang-assertions-14.0.0/bin/clang-14+0xac2ac5)
clang-14: error: unable to execute command: Segmentation fault
clang-14: error: clang integrated assembler command failed due to signal (use -v to see invocation)
clang version 14.0.0 (https://github.com/llvm/llvm-project.git 329fda39c507e8740978d10458451dcdb21563be)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: /opt/compiler-explorer/clang-assertions-14.0.0/bin
clang-14: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
```
