### ISSUE TITLE
Incorrect InstCombine urem removal with undef values

### ISSUE THREAD

**Issue by nunoplopes** [llvm/llvm-project#37809]
|  |  |
| --- | --- |
| Bugzilla Link | [38461](https://llvm.org/bz38461) |
| Version | trunk |
| OS | All |
| CC | @majnemer,@RKSimon,@regehr,@sanjoy,@rotateright |

## Extended Description 
The following functions gets miscompiled:

```
define i2 @foo(i2, i1, i4, i2, i1, i4, i2, i1, i4, i2, i1, i4) {
  %13 = urem i2 %0, -1
  ret i2 %13
}
```

$ opt -S -instcombine urem.ll

```
define i2 @foo(i2, i1, i4, i2, i1, i4, i2, i1, i4, i2, i1, i4) {
  %13 = icmp eq i2 %0, -1
  %14 = zext i1 %13 to i2
  %15 = add i2 %14, %0
  ret i2 %15
}
```

Alive2 complains about this:

```
----------------------------------------
  %13 = urem i2 %0, -1
  ret i2 %13
=>
  %13 = icmp eq i2 %0, -1
  %14 = zext i1 %13 to i2
  %15 = add i2 %14, %0
  ret i2 %15

ERROR: Value mismatch

Example:
i2 %0 = undef
src:
i2 %13 = 0x0 (0)
tgt:
i1 %13 = 0x0 (0)
i2 %14 = 0x0 (0)
i2 %15 = 0x3 (3, -1)
Source value: 0x0 (0)
Target value: 0x3 (3, -1)
```

The transformation is incorrect because it increases the number of uses of %0. Since when undef is read it may return a different value, it's not safe to increase the number of reads like this, as is exemplified in the counterexample above.

[P.S.: The online version of Alive unfortunately incorrectly says that this transformation is correct. It doesn't model multiple undef uses soundly. Alive2 does, and will be available soonish]

**Comment by fhahn** [comment]
Still reproduces: https://llvm.godbolt.org/z/Yesqe6o7c https://alive2.llvm.org/ce/z/uemCr2 

```define i2 @foo(i2, i1, i4, i2, i1, i4, i2, i1, i4, i2, i1, i4) {
  %13 = urem i2 %0, -1
  ret i2 %13
}

=> 

define i2 @foo(i2 %0, i1 %1, i4 %2, i2 %3, i1 %4, i4 %5, i2 %6, i1 %7, i4 %8, i2 %9, i1 %10, i4 %11) {
  %.not = icmp eq i2 %0, -1
  %13 = select i1 %.not, i2 0, i2 %0
  ret i2 %13
}
```

**Comment by rotateright** [comment]
I added freeze to the 3 transforms in these examples, so they should be safe now. 

There's a (small) chance that any of those patches will cause a perf regression and have to be reverted, but I think we can close this report.

If there are other transforms like these still visible in regression tests, please post new bugs and/or tag me.
