### ISSUE TITLE
clang-analyzer-* checks generate warnings from non-user code

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37832]
|  |  |
| --- | --- |
| Bugzilla Link | [38484](https://llvm.org/bz38484) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @JonasToth,@firewave |

## Extended Description 
How to reproduce:

$ cat library.hpp 
struct foo {
  foo() { f(); }
  virtual void f() {}
};

$ cat main.cpp 
#include "library.hpp"

int main() { foo f; }

$ clang-tidy-6.0 main.cpp
...
.../library.hpp:2:11: warning: Call to virtual function during construction [clang-analyzer-optin.cplusplus.VirtualCall]
  foo() { f(); }
...

**Comment by carlosgalvezp** [comment]
This issue is no longer present on latest trunk.
