### ISSUE TITLE
std::filesystem::path::iterator::iterator_category is non-comformingly "bidirectional_iterator_tag"

### ISSUE THREAD

**Issue by CaseyCarter** [llvm/llvm-project#37852]
|  |  |
| --- | --- |
| Bugzilla Link | [38504](https://llvm.org/bz38504) |
| Version | 7.0 |
| OS | Windows NT |
| CC | @mclow |

## Extended Description 
std::filesystem::path::iterator's member iterator_category is an alias for bidirectional_iterator_tag, despite that it does not satisfy the requirement in [forward.iterators]/6:

  If a and b are both dereferenceable, then a == b if and only if *a and *b
  are bound to the same object.

An iterator cannot be bidirectional if it is not forward, so the iterator_category should in fact be input_iterator_tag, or - as a conforming extension - some other type which is convertible to input_iterator_tag but not convertible to forward_iterator_tag.

Note that if path::iterator::operator* were to return a prvalue it would conform to the BidirectionalIterator concept in the Ranges proposal, and could conformingly define its member iterator_concept as an alias for std::bidirectional_iterator_tag.

**Comment by Quuxplusone** [comment]
Given that both libc++ and libstdc++ agree
```
using It = std::filesystem::path::iterator;
static_assert(std::bidirectional_iterator<It>);
static_assert(std::is_same_v<std::iterator_traits<It>::iterator_category, std::bidirectional_iterator_tag>);
```
and given that `path::iterator` _was_ designed to support `operator--` (so it sure _quacks_ like a bidirectional iterator), I think this is more of an L(E?)WG issue than a libc++ bug per se.

If LWG wants `path::iterator::iterator_category` to be set to `input_iterator_tag` and `path::iterator::iterator_concept` to be set to `bidirectional_iterator_tag`, then they should say so in the standard circa [here](https://eel.is/c++draft/fs.path.itr#2). As it is, they just say "A `path​::​iterator` is a constant iterator meeting all the requirements of a bidirectional iterator _except_ [that thing you just said]," which certainly _suggests_ to the untrained eye that it should do as the bidirectional iterators do even when it comes to setting its `iterator_category`.

I encourage _either_ opening an LWG issue, _or_ just changing MSVC's implementation to follow the unwashed herd. :)

**Comment by cpplearner** [comment]
- libstdc++'s `path::iterator` satisfies all bidirectional iterator requirements, including "`it1 == it2` if and only if `*it1` and `*it2` are bound to the same object", and provides an `iterator_category` that aliases `bidirectional_iterator_tag`.
- MSVC's `path::iterator` does not satisfy all bidirectional iterator requirements, and provides an `iterator_category` that aliases `input_iterator_tag`.
- libc++'s `path::iterator` does not satisfy all bidirectional iterator requirements, but provides an `iterator_category` that aliases `bidirectional_iterator_tag`.

There's no herd to follow :)

**Comment by Quuxplusone** [comment]
Hm, I see (I think). libstdc++'s `path` holds a data member more-or-less equivalent to `vector<path> _M_cmpts`, and their `path::iterator` is a regular bidirectional iterator over that vector. libc++'s `path` doesn't hold any additional structure, and our `path::iterator` is like `istream_iterator` where it caches a `path` object inside the iterator itself.

Relatedly, e02ed1c255d71 made libc++'s `reverse_iterator<T>` explode when instantiated with `T=path::iterator`; but that's pretty bad UX, and still doesn't fix the problem for user-defined `reverse_iterator`-alikes, and definitely violates the "`path::iterator` should quack like a bidirectional iterator" rule (because part of being a bidirectional iterator is being safe-to-use-with-`reverse_iterator`).

This is now https://reviews.llvm.org/D116489 although I think the decision to actually adopt that patch is not going to be a slam dunk. :)

**Comment by DimitryAndric** [comment]
Hmm, I ended up at this commit 459b4b725f52f0befd90312a326225eda6450233 when checking the breakage reported for the FreeBSD `cad/horizon-eda` port (see also https://github.com/horizon-eda/horizon), which gives:

```
In file included from src/util/fs_util.cpp:1:
In file included from src/util/fs_util.hpp:2:
In file included from /usr/include/c++/v1/string:525:
In file included from /usr/include/c++/v1/algorithm:667:
In file included from /usr/include/c++/v1/functional:493:
/usr/include/c++/v1/__algorithm/search.h:100:10: error: no matching function for call to '__search'
  return _VSTD::__search<_BinaryPredicate&>(
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/__config:826:15: note: expanded from macro '_VSTD'
#define _VSTD std
              ^
/usr/include/c++/v1/__algorithm/search.h:111:17: note: in instantiation of function template specialization 'std::search<std::filesystem::path::iterator, std::filesystem::path::iterator, std::__equal_to<std::filesystem::path>>' requested here
  return _VSTD::search(__first1, __last1, __first2, __last2, __equal_to<__v1, __v2>());
                ^
src/util/fs_util.cpp:11:25: note: in instantiation of function template specialization 'std::search<std::filesystem::path::iterator, std::filesystem::path::iterator>' requested here
    const auto x = std::search(p.begin(), p.end(), b.begin(), b.end());
                        ^
/usr/include/c++/v1/__algorithm/search.h:26:35: note: candidate function template not viable: no known conversion from 'typename iterator_traits<iterator>::iterator_category' (aka 'std::input_iterator_tag') to 'std::forward_iterator_tag' for 6th argument
    _LIBCPP_CONSTEXPR_AFTER_CXX11 __search(_ForwardIterator1 __first1, _ForwardIterator1 __last1,
                                  ^
/usr/include/c++/v1/__algorithm/search.h:59:1: note: candidate function template not viable: no known conversion from 'typename iterator_traits<iterator>::iterator_category' (aka 'std::input_iterator_tag') to 'std::random_access_iterator_tag' for 6th argument
__search(_RandomAccessIterator1 __first1, _RandomAccessIterator1 __last1, _RandomAccessIterator2 __first2,
^
```

The offending code does this:

```c++
namespace fs = std::filesystem;
std::optional<std::string> get_relative_filename(const std::string &path, const std::string &base)
{
    const auto p = fs::u8path(path);
    const auto b = fs::u8path(base);
    const auto x = std::search(p.begin(), p.end(), b.begin(), b.end());
    if (x == p.begin()) // path is in base path
        return fs::relative(p, b).u8string();
    else
        return {};
}
```

and apparently you now can't use `std::search` on `std::filesystem::path` iterators anymore? At least, not when you compile with `-std=c++17`, like this project?

**Comment by DimitryAndric** [comment]
FWIW the actual source is at https://github.com/horizon-eda/horizon/blob/master/src/util/fs_util.cpp#L11

**Comment by carrotIndustries** [comment]
> Hmm, I ended up at this commit https://github.com/llvm/llvm-project/commit/459b4b725f52f0befd90312a326225eda6450233 when checking the breakage reported for the FreeBSD cad/horizon-eda port (see also https://github.com/horizon-eda/horizon), which gives:

Others also found out https://github.com/horizon-eda/horizon/issues/666 about a month later.
