### ISSUE TITLE
-Wconstant-logical-operand and yoda conditions

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#37919]
|  |  |
| --- | --- |
| Bugzilla Link | [38571](https://llvm.org/bz38571) |
| Version | trunk |
| OS | Linux |
| CC | @gburgessiv,@lalozano,@m-gupta,@stephenhines |

## Extended Description 
```c
void foo(int x) {
    if (x && 5) {}
    if (5 && x) {}
}
```

The above produces -Wconstant-logical-operand for the first statement, but not the second.

This was observed while compiling the Linux kernel, as a single translation unit has a mix of which side the constant logical operand is on, but only some of the conditionals producing warnings.  In these cases, the constant logical operand is nested a few macros deep.

**Comment by xgupta** [comment]
Patch to review - https://reviews.llvm.org/D142609.

**Comment by xgupta** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/dfdfd306cfaf54fbc43e2d5eb36489dac3eb9976. Thanks.
