### ISSUE TITLE
[Formatter/Cpp] Comments before conditions in if else statment are misalligned

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#37981]
|  |  |
| --- | --- |
| Bugzilla Link | [38633](https://llvm.org/bz38633) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I'm not sure whether current behavior is intended, but I think it could be improved considering how common this pattern is:

Could be:

```
// description of the condition
if (true) {
  x = 42;
// description of another condition
} else if (true) {
  x = 42;
// description of else
} else {
  x = 42;
}
```

Current formatting:

```
// description of the condition
if (true) {
  x = 42;
  // description of another condition
} else if (true) {
  x = 42;
  // description of else
} else {
  x = 42;
}
```

One drawback, I can think of, of this change would be an incorrect indentation in the following situation:

Base version:

```
if (...) {
  x = 42;
  // Assign 43 to x
  x = 43;
} else if (...) {
}
```

Developer changed to:

```
if (...) {
  x = 42;
  // Assign 43 to x
  // x = 43; - temporarily comment this line 
} else if (...) {
}
```

After running clang-format on above code:

```
if (...) {
  x = 42;
// Assign 43 to x
// x = 43; - temporarily comment this line 
} else if (...) {
}
```

This would go back to the correct formatting after uncommenting the line, so I don't think this should be an issue.

**Comment by mydeveloperday** [comment]
running clang-format on the above code renders

```
if (...) {
  x = 42;
  // Assign 43 to x
  // x = 43; - temporarily comment this
  // line
} else if (...) {
}
```

This issue appears to be fixed in clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 7890afddec
ff01119f4d5e8825b43dd2c8361648) so I am closing this issue, but if you think there is still an issue feel free to reopen it
