### ISSUE TITLE
LLVM go bindings test fails when using LLD

### ISSUE THREAD

**Issue by rnk** [llvm/llvm-project#38000]
|  |  |
| --- | --- |
| Bugzilla Link | [38652](https://llvm.org/bz38652) |
| Version | unspecified |
| OS | Windows NT |
| CC | @pcc |

## Extended Description 
The go bindings tests fail on my machine. I don't think LLD recognizes zlib-gnu, and I'm not sure it can be made to.

$ ninja check
Already up to date.
Current branch master is up to date.
[83/84] Running the LLVM regression tests
FAIL: LLVM :: Bindings/Go/go.test (14691 of 27228)
******************** TEST 'LLVM :: Bindings/Go/go.test' FAILED ********************
Script:
--
: 'RUN: at line 1';   /usr/local/google/home/rnk/llvm-project/build/bin/llvm-go go=/usr/lib/google-golang/bin/go test llvm.org/llvm/bindings/go/llvm
--
Exit Code: 1

Command Output (stdout):
--
FAIL    llvm.org/llvm/bindings/go/llvm [build failed]

--
Command Output (stderr):
--
# llvm.org/llvm/bindings/go/llvm.test
/usr/lib/google-golang/pkg/tool/linux_amd64/link: running /usr/local/google/home/rnk/chromium/src/third_party/llvm-build/Release+Asserts/bin/clang++ failed: exit status 1
ld.lld: error: unknown --compress-debug-sections value: zlib-gnu
clang: error: linker command failed with exit code 1 (use -v to see invocation)

--

********************
Testing Time: 47.78s
********************
Failing Tests (1):
    LLVM :: Bindings/Go/go.test

  Expected Passes    : 26533
  Expected Failures  : 148
  Unsupported Tests  : 546
  Unexpected Failures: 1
FAILED: test/CMakeFiles/check-llvm
cd /usr/local/google/home/rnk/llvm-project/build/test && /usr/bin/python2.7 /usr/local/google/home/rnk/llvm-project/build/./bin/llvm-lit -sv /usr/local/google/home/rnk/llvm-project/build/test
ninja: build stopped: subcommand failed.

**Comment by arsenm** [comment]
Old build issue
