### ISSUE TITLE
llvm-objdump: wrong output for big endian ARM binaries

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38069]
|  |  |
| --- | --- |
| Bugzilla Link | [38721](https://llvm.org/bz38721) |
| Version | trunk |
| OS | Linux |
| Attachments | [File used to compare llvm-objdump to GNU objdump](https://user-images.githubusercontent.com/60944935/143757994-cff114a0-dbea-4786-8acf-e44db62fc8bc.gz), [File that shows that the problem is also present in the thumbeb backend](https://user-images.githubusercontent.com/60944935/143757995-32a0e73c-51cb-4d4b-98f3-8de807745745.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

LLVM - https://github.com/llvm-mirror/llvm/commit/24535f7c19077d02b193bc6225a667f963901eb4

```
$ llvm-objdump -d foo.o
foo.o:  file format ELF32-arm-big

subsection length greater than section length
subsection length greater than section length
Disassembly of section .text.foo:
foo:
       0:       e0 81 00 00     andeq   r8, r0, r0, ror #&#8203;3
       4:       e1 2f ff 1e     cdpne   p15, #&#8203;15, c2, c15, c1, #&#8203;7
```

GNU objdump (GNU Binutils) 2.31.1

```
$ arm-none-eabi-objdump -d foo.o
foo.o:     file format elf32-bigarm

Disassembly of section .text.foo:

00000000 <foo>:
   0:   e0810000        add     r0, r1, r0
   4:   e12fff1e        bx      lr
```

The foo.o file has been attached

**Comment by DavidSpickett** [comment]
This was fixed by https://reviews.llvm.org/D130902.

```
$ ./bin/llvm-objdump -d 143757994-cff114a0-dbea-4786-8acf-e44db62fc8bc

143757994-cff114a0-dbea-4786-8acf-e44db62fc8bc: file format elf32-bigarm

Disassembly of section .text.foo:

00000000 <foo>:
       0: e0810000      add     r0, r1, r0
       4: e12fff1e      bx      lr
```
```
$ ./bin/llvm-objdump -d 143757995-32a0e73c-51cb-4d4b-98f3-8de807745745

143757995-32a0e73c-51cb-4d4b-98f3-8de807745745: file format elf32-bigarm

Disassembly of section .text:

00000000 <foo>:
       0: 1840          adds    r0, r0, r1
       2: 4770          bx      lr

```
The first release to include this will be 16.0.0 (which is currently in the release candidate stage).
