### ISSUE TITLE
performance-noexcept-move-constructor with libstdc++ >=7

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38081]
|  |  |
| --- | --- |
| Bugzilla Link | [38733](https://llvm.org/bz38733) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Given:
#include <map>
struct S {
    S() = default;
    S(S&&) noexcept/*(true)*/ = default;
    std::map<int, int> m;
};
void f(S s) { S s2 = std::move(s); }

Gives:
clang-tidy   -checks=performance-noexcept-move-constructor test2.cc -- clang++  --gcc-toolchain=/usr/local/gcc-7.3.0
17 warnings generated.
test2.cc:4:5: warning: move constructors should be marked noexcept [performance-noexcept-move-constructor]
    S(S&&) noexcept/*(true)*/ = default;
    ^

The warning is reported with libstd++ 7 and 8 but not with 5 or 6 or libc++.
The same warning is reported with 6.0.1 and 7.0rc2.

The warning has a few issues:
- It is confusing to suggest noexcept for explicitly defaulted constructors given that for those the exception specifier has no effect.
- Adding the noexcept, which the warning suggests, doesn't fix the warning.
- It makes a different whether the exception specifier is noexcept or noexcept(true) (with the later the warning isn't shown) when those have the exact same meaning (and thus should produce the same warning).
- Independent of whether it is defaulted or not, it doesn't make much sense to warn that it should be noexcept if some of the members (or bases) aren't noexcept (and thus it can't be noexcept)

Please let me know if you consider the different issues distinct and prefer independent bugs.

**Comment by carlosgalvezp** [comment]
Warning no longer showing up in trunk for the example provided in OP.
