### ISSUE TITLE
Spurious Unreachable Code Warning Shown For Constexpr Functions

### ISSUE THREAD

**Issue by c6238aa9-e28b-4a2e-9256-1883efbde648** [llvm/llvm-project#38100]
|  |  |
| --- | --- |
| Bugzilla Link | [38752](https://llvm.org/bz38752) |
| Version | trunk |
| OS | Linux |
| Attachments | [Minimal Example that produces the warning spuriously. Also available at https://user-images.githubusercontent.com/93435940/143758014-d3712526-450a-47aa-a882-80a7ecee6dd7.gz) |
| CC | @DougGregor |

## Extended Description 

Attached example gives a spurious unreachable code warning.

**Comment by wheatman** [comment]
This was fixed between 15 and 16
https://godbolt.org/z/hzbxebP41

code
```
#include <string>
#include <iostream>
struct BuildInfo {
#ifdef DEBUG
  bool debug{true};
#else
  bool debug{false};
#endif
};

void debug_log(std::string const& output_string);


void debug_log(std::string const& output_string)
{
  constexpr auto buildinfo = BuildInfo();
  if constexpr (buildinfo.debug) {
    std::cout << output_string << std::endl;
  }
}
```

old warning
```
<source>:18:32: warning: code will never be executed [-Wunreachable-code]
    std::cout << output_string << std::endl;
                               ^~
1 warning generated.
Compiler returned: 0
```
