### ISSUE TITLE
Clang crash building Chrome for Android on 8/29/18

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38114]
|  |  |
| --- | --- |
| Bugzilla Link | [38766](https://llvm.org/bz38766) |
| Version | unspecified |
| OS | Linux |
| Attachments | [sh file](https://user-images.githubusercontent.com/60944935/143758018-cd57b5c2-ea2e-4968-9123-7298621ef4f6.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 

donnd@narsil2:/usr/local/google/code/clankium4/src$ buildrununittests *CanSendPageUrl*
ninja: Entering directory `out/Debug'
[1/37] CXX obj/chrome/test/_unit_tests__library/contextual_search_delegate_unittest.o
FAILED: obj/chrome/test/_unit_tests__library/contextual_search_delegate_unittest.o 
/usr/local/google/home/donnd/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/test/_unit_tests__library/contextual_search_delegate_unittest.o.d -DV8_DEPRECATION_WARNINGS -DNO_TCMALLOC -DSAFE_BROWSING_DB_REMOTE -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_GNU_SOURCE -DANDROID -DHAVE_SYS_UIO_H -DANDROID_NDK_VERSION_ROLL=r16_1 -DCR_CLANG_REVISION=\"338452-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DCOMPONENT_BUILD -D__GNU_SOURCE=1 -DCHROMIUM_CXX_TWEAK_INLINES -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -DGTEST_API_= -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=1 -DGTEST_HAS_TR1_TUPLE=0 -DWEBP_EXTERN=extern -DUSE_EGL -DEXPAT_RELATIVE_PATH -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -DV8_USE_EXTERNAL_STARTUP_DATA -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DPROTOBUF_USE_DLLS -DBORINGSSL_SHARED_LIBRARY -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DWEBRTC_ANDROID -DABSL_ALLOCATOR_NOTHROW=1 -DNO_MAIN_THREAD_WRAPPING -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY -DSK_HAS_JPEG_LIBRARY -DSKIA_DLL -DGR_GL_IGNORE_ES3_MSAA=0 -DSKCMS_API=__attribute__\(\(visibility\(\"default\"\)\)\) -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DSK_BUILD_FOR_ANDROID -DUSE_CHROMIUM_SKIA -DLEVELDB_PLATFORM_CHROMIUM=1 -DUSING_V8_SHARED -DV8_ENABLE_CHECKS -DV8_DEPRECATION_WARNINGS -DI18N_ADDRESS_VALIDATION_DATA_URL=\"https://chromium-i18n.appspot.com/ssl-aggregate-address/\" -DUNIT_TEST -DUSE_REMOTE_TEST_SERVER -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -DWTF_USE_LOW_QUALITY_IMAGE_INTERPOLATION=1 -DWTF_USE_WEBAUDIO_OPENMAX_DL_FFT=1 -DUSE_LIBJPEG_TURBO=1 -DUSING_V8_SHARED -DV8_ENABLE_CHECKS -DV8_DEPRECATION_WARNINGS -DI18N_PHONENUMBERS_USE_ICU_REGEXP=1 -DI18N_PHONENUMBERS_USE_ALTERNATE_FORMATS=1 -DXML_STATIC -DHUNSPELL_STATIC -DHUNSPELL_CHROME_CLIENT -DUSE_HUNSPELL -I../.. -Igen -I../../third_party/googletest/custom -I../../third_party/googletest/src/googletest/include -I../../third_party/libwebp/src -I../../third_party/khronos -I../../gpu -I../../third_party/libyuv/include -I../../third_party/webrtc_overrides -I../../testing/gtest/include -I../../third_party/libyuv/include -I../../third_party/usrsctp/usrsctplib -I../../third_party/webrtc -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../third_party/boringssl/src/include -I../../third_party/webrtc_overrides -I../../third_party/webrtc -I../../third_party/abseil-cpp -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/encode -I../../third_party/skia/include/gpu -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/src/gpu -I../../third_party/skia/src/sksl -I../../third_party/skia/modules/skottie/include -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../third_party/libwebm/source -Igen/media/base/android/media_jni_headers -Igen/media/base/android/media_jni_headers/media -I../../v8/include -Igen/v8/include -I../../third_party/perfetto/include -Igen/third_party/perfetto/protos -Igen/third_party/perfetto/protos -Igen/third_party/perfetto/protos -Igen/third_party/metrics_proto -I../../third_party/re2/src -I../../third_party/mesa_headers -I../../third_party/libaddressinput/src/cpp/include -I../../third_party/googletest/custom -I../../third_party/googletest/src/googlemock/include -I../../third_party/cacheinvalidation/overrides -I../../third_party/cacheinvalidation/src -I../../third_party/flatbuffers/src/include -I../../third_party/libjpeg_turbo -I../../third_party/iccjpeg -I../../third_party/libpng -I../../third_party/zlib -I../../third_party/ots/include -I../../v8/include -Igen/v8/include -I../../third_party/libphonenumber/dist/cpp/src -Igen/third_party/libphonenumber -I../../third_party/libxml/src/include -I../../third_party/libxml/linux/include -I../../third_party/webrtc_overrides -I../../testing/gtest/include -I../../third_party/webrtc -I../../third_party/expat/files/lib -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -fcolor-diagnostics -fmerge-all-constants -no-canonical-prefixes -ffunction-sections -fno-short-enums --target=arm-linux-androideabi -isystem../../third_party/android_ndk/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=16 -DHAVE_PTHREAD_COND_TIMEDWAIT_MONOTONIC=1 -march=armv7-a -mfloat-abi=softfp -mtune=generic-armv7-a -mfpu=neon -mthumb -Wall -Werror -Wextra -Wimplicit-fallthrough -Wthread-safety -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-user-defined-warnings -Wno-unused-lambda-capture -Wno-null-pointer-arithmetic -Wno-enum-compare-switch -Wno-ignored-pragma-optimize -Oz -fno-ident -fdata-sections -ffunction-sections -fomit-frame-pointer -gdwarf-3 -g2 -ggnu-pubnames -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang enforce-in-thirdparty-webkit -Xclang -plugin-arg-find-bad-constructs -Xclang check-enum-max-value -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wno-inconsistent-missing-override -Wno-exit-time-destructors -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libBlinkGCPlugin.so -Xclang -add-plugin -Xclang blink-gc-plugin -DLIBXML_STATIC= -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=c++14 -fno-exceptions -fno-rtti --sysroot=../../third_party/android_ndk/sysroot -isystem../../third_party/android_ndk/sources/cxx-stl/llvm-libc++/include -isystem../../third_party/android_ndk/sources/cxx-stl/llvm-libc++abi/include -isystem../../third_party/android_ndk/sources/android/support/include -fvisibility-inlines-hidden -c ../../chrome/browser/android/contextualsearch/contextual_search_delegate_unittest.cc -o obj/chrome/test/_unit_tests__library/contextual_search_delegate_unittest.o
Stack dump:
0.	Program arguments: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -cc1 -triple thumbv7--linux-android -emit-obj -disable-free -main-file-name contextual_search_delegate_unittest.cc -mrelocation-model pic -pic-level 2 -mthread-model posix -fmerge-all-constants -relaxed-aliasing -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu generic -target-feature +soft-float-abi -target-feature -fp-only-sp -target-feature -d16 -target-feature +vfp3 -target-feature -fp16 -target-feature -vfp4 -target-feature -fp-armv8 -target-feature +neon -target-feature -crypto -target-abi aapcs-linux -mfloat-abi soft -fallow-half-arguments-and-returns -dwarf-column-info -debug-info-kind=limited -dwarf-version=3 -debugger-tuning=gdb -ggnu-pubnames -ffunction-sections -fdata-sections -coverage-notes-file /usr/local/google/code/clankium4/src/out/Debug/obj/chrome/test/_unit_tests__library/contextual_search_delegate_unittest.gcno -resource-dir ../../third_party/llvm-build/Release+Asserts/lib/clang/7.0.0 -dependency-file obj/chrome/test/_unit_tests__library/contextual_search_delegate_unittest.o.d -MT obj/chrome/test/_unit_tests__library/contextual_search_delegate_unittest.o -isystem ../../third_party/android_ndk/sysroot/usr/include/arm-linux-androideabi -isystem ../../third_party/android_ndk/sources/cxx-stl/llvm-libc++/include -isystem ../../third_party/android_ndk/sources/cxx-stl/llvm-libc++abi/include -isystem ../../third_party/android_ndk/sources/android/support/include -D V8_DEPRECATION_WARNINGS -D NO_TCMALLOC -D SAFE_BROWSING_DB_REMOTE -D CHROMIUM_BUILD -D FIELDTRIAL_TESTING_ENABLED -D _GNU_SOURCE -D ANDROID -D HAVE_SYS_UIO_H -D ANDROID_NDK_VERSION_ROLL=r16_1 -D CR_CLANG_REVISION="338452-1" -D __STDC_CONSTANT_MACROS -D __STDC_FORMAT_MACROS -D COMPONENT_BUILD -D __GNU_SOURCE=1 -D CHROMIUM_CXX_TWEAK_INLINES -D _DEBUG -D DYNAMIC_ANNOTATIONS_ENABLED=1 -D WTF_USE_DYNAMIC_ANNOTATIONS=1 -D GTEST_API_= -D GTEST_HAS_POSIX_RE=0 -D GTEST_LANG_CXX11=1 -D GTEST_HAS_TR1_TUPLE=0 -D WEBP_EXTERN=extern -D USE_EGL -D EXPAT_RELATIVE_PATH -D U_USING_ICU_NAMESPACE=0 -D U_ENABLE_DYLOAD=0 -D ICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -D UCHAR_TYPE=uint16_t -D V8_USE_EXTERNAL_STARTUP_DATA -D GOOGLE_PROTOBUF_NO_RTTI -D GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -D HAVE_PTHREAD -D PROTOBUF_USE_DLLS -D BORINGSSL_SHARED_LIBRARY -D WEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -D WEBRTC_CHROMIUM_BUILD -D WEBRTC_POSIX -D WEBRTC_LINUX -D WEBRTC_ANDROID -D ABSL_ALLOCATOR_NOTHROW=1 -D NO_MAIN_THREAD_WRAPPING -D SK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -D SK_HAS_PNG_LIBRARY -D SK_HAS_WEBP_LIBRARY -D SK_HAS_JPEG_LIBRARY -D SKIA_DLL -D GR_GL_IGNORE_ES3_MSAA=0 -D SKCMS_API=__attribute__((visibility("default"))) -D SK_SUPPORT_GPU=1 -D SK_GPU_WORKAROUNDS_HEADER="gpu/config/gpu_driver_bug_workaround_autogen.h" -D SK_BUILD_FOR_ANDROID -D USE_CHROMIUM_SKIA -D LEVELDB_PLATFORM_CHROMIUM=1 -D USING_V8_SHARED -D V8_ENABLE_CHECKS -D V8_DEPRECATION_WARNINGS -D I18N_ADDRESS_VALIDATION_DATA_URL="https://chromium-i18n.appspot.com/ssl-aggregate-address/" -D UNIT_TEST -D USE_REMOTE_TEST_SERVER -D WTF_USE_DYNAMIC_ANNOTATIONS=1 -D WTF_USE_LOW_QUALITY_IMAGE_INTERPOLATION=1 -D WTF_USE_WEBAUDIO_OPENMAX_DL_FFT=1 -D USE_LIBJPEG_TURBO=1 -D USING_V8_SHARED -D V8_ENABLE_CHECKS -D V8_DEPRECATION_WARNINGS -D I18N_PHONENUMBERS_USE_ICU_REGEXP=1 -D I18N_PHONENUMBERS_USE_ALTERNATE_FORMATS=1 -D XML_STATIC -D HUNSPELL_STATIC -D HUNSPELL_CHROME_CLIENT -D USE_HUNSPELL -I ../.. -I gen -I ../../third_party/googletest/custom -I ../../third_party/googletest/src/googletest/include -I ../../third_party/libwebp/src -I ../../third_party/khronos -I ../../gpu -I ../../third_party/libyuv/include -I ../../third_party/webrtc_overrides -I ../../testing/gtest/include -I ../../third_party/libyuv/include -I ../../third_party/usrsctp/usrsctplib -I ../../third_party/webrtc -I ../../third_party/ced/src -I ../../third_party/icu/source/common -I ../../third_party/icu/source/i18n -I ../../third_party/protobuf/src -I gen/protoc_out -I ../../third_party/protobuf/src -I ../../third_party/boringssl/src/include -I ../../third_party/webrtc_overrides -I ../../third_party/webrtc -I ../../third_party/abseil-cpp -I ../../skia/config -I ../../skia/ext -I ../../third_party/skia/include/c -I ../../third_party/skia/include/config -I ../../third_party/skia/include/core -I ../../third_party/skia/include/effects -I ../../third_party/skia/include/encode -I ../../third_party/skia/include/gpu -I ../../third_party/skia/include/images -I ../../third_party/skia/include/lazy -I ../../third_party/skia/include/pathops -I ../../third_party/skia/include/pdf -I ../../third_party/skia/include/pipe -I ../../third_party/skia/include/ports -I ../../third_party/skia/include/utils -I ../../third_party/skia/src/gpu -I ../../third_party/skia/src/sksl -I ../../third_party/skia/modules/skottie/include -I ../../third_party/leveldatabase -I ../../third_party/leveldatabase/src -I ../../third_party/leveldatabase/src/include -I ../../third_party/libwebm/source -I gen/media/base/android/media_jni_headers -I gen/media/base/android/media_jni_headers/media -I ../../v8/include -I gen/v8/include -I ../../third_party/perfetto/include -I gen/third_party/perfetto/protos -I gen/third_party/perfetto/protos -I gen/third_party/perfetto/protos -I gen/third_party/metrics_proto -I ../../third_party/re2/src -I ../../third_party/mesa_headers -I ../../third_party/libaddressinput/src/cpp/include -I ../../third_party/googletest/custom -I ../../third_party/googletest/src/googlemock/include -I ../../third_party/cacheinvalidation/overrides -I ../../third_party/cacheinvalidation/src -I ../../third_party/flatbuffers/src/include -I ../../third_party/libjpeg_turbo -I ../../third_party/iccjpeg -I ../../third_party/libpng -I ../../third_party/zlib -I ../../third_party/ots/include -I ../../v8/include -I gen/v8/include -I ../../third_party/libphonenumber/dist/cpp/src -I gen/third_party/libphonenumber -I ../../third_party/libxml/src/include -I ../../third_party/libxml/linux/include -I ../../third_party/webrtc_overrides -I ../../testing/gtest/include -I ../../third_party/webrtc -I ../../third_party/expat/files/lib -D __DATE__= -D __TIME__= -D __TIMESTAMP__= -D __ANDROID_API__=16 -D HAVE_PTHREAD_COND_TIMEDWAIT_MONOTONIC=1 -D LIBXML_STATIC= -isysroot ../../third_party/android_ndk/sysroot -internal-isystem ../../third_party/android_ndk/sysroot/usr/local/include -internal-isystem ../../third_party/llvm-build/Release+Asserts/lib/clang/7.0.0/include -internal-externc-isystem ../../third_party/android_ndk/sysroot/usr/include/arm-linux-androideabi -internal-externc-isystem ../../third_party/android_ndk/sysroot/include -internal-externc-isystem ../../third_party/android_ndk/sysroot/usr/include -Oz -Wno-builtin-macro-redefined -Wall -Werror -Wextra -Wimplicit-fallthrough -Wthread-safety -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-user-defined-warnings -Wno-unused-lambda-capture -Wno-null-pointer-arithmetic -Wno-enum-compare-switch -Wno-ignored-pragma-optimize -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wno-inconsistent-missing-override -Wno-exit-time-destructors -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=c++14 -fdeprecated-macro -fdebug-compilation-dir /usr/local/google/code/clankium4/src/out/Debug -ferror-limit 19 -fmessage-length 0 -fvisibility hidden -fvisibility-inlines-hidden -stack-protector 1 -stack-protector-buffer-size 4 -fno-rtti -fno-signed-char -fobjc-runtime=gcc -Qn -fdiagnostics-show-option -fcolor-diagnostics -vectorize-slp -load ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -add-plugin find-bad-constructs -plugin-arg-find-bad-constructs enforce-in-thirdparty-webkit -plugin-arg-find-bad-constructs check-enum-max-value -plugin-arg-find-bad-constructs check-ipc -load ../../third_party/llvm-build/Release+Asserts/lib/libBlinkGCPlugin.so -add-plugin blink-gc-plugin -o obj/chrome/test/_unit_tests__library/contextual_search_delegate_unittest.o -x c++ ../../chrome/browser/android/contextualsearch/contextual_search_delegate_unittest.cc -faddrsig 
1.	clang++: error: unable to execute command: Segmentation fault
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 7.0.0 (trunk 338452)
Target: arm--linux-android
Thread model: posix
InstalledDir: ../../third_party/llvm-build/Release+Asserts/bin
clang++: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/contextual_search_delegate_unittest-d7f280.cpp
clang++: note: diagnostic msg: /tmp/contextual_search_delegate_unittest-d7f280.sh
clang++: note: diagnostic msg: 

********************
ninja: build stopped: subcommand failed.

**Comment by Endilll** [comment]
I haven't seen people responding to my requests to access a protected Drive link even once.
