### ISSUE TITLE
Combine and-mask+icmp eq -> icmp ule when mask was all-ones in high bits

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#38139]
|  |  |
| --- | --- |
| Bugzilla Link | [38791](https://llvm.org/bz38791) |
| Version | trunk |
| OS | Linux |
| CC | @davidbolvansky |

## Extended Description 
Copied from llvm/llvm-project#37471 

Name: range using high bits
%masked = or i8 %arg, 192
%r = icmp ne i8 %masked, %arg
  =>
%r = icmp ult i8 %arg, 192

https://rise4fun.com/Alive/lv5

**Comment by RKSimon** [comment]
Missing fold was fixed by 3cf54c533
