### ISSUE TITLE
clang crashes on valid code at -O1 and above with debugging enabled: Assertion `!getType()->isVoidTy() && "Cannot assign a name to void values!"' failed

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#38141]
|  |  |
| --- | --- |
| Bugzilla Link | [38793](https://llvm.org/bz38793) |
| Version | unspecified |
| OS | All |

## Extended Description 
$ clangpolly -v
clang version 8.0.0 (http://llvm.org/git/clang.git b9ef8cb5d0a5501643befcdcf6bef0a3dfa9e205) (llvm/trunk 341010)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.2.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ clangpolly -O0 small.c 
$ clangpolly -O1 small.c
$ 
$ clangpolly -O1 -g small.c
clang-6.0: /home/su/software/tmp/polly/llvm/lib/IR/Value.cpp:256: void llvm::Value::setNameImpl(const llvm::Twine&): Assertion `!getType()->isVoidTy() && "Cannot assign a name to void values!"' failed.
Stack dump:
0.	Program arguments: /home/su/software/tmp/polly/llvm_build/bin/clang-6.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -main-file-name small.c -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -resource-dir /home/su/software/tmp/polly/llvm_build/lib/clang/8.0.0 -internal-isystem /usr/local/include -internal-isystem /home/su/software/tmp/polly/llvm_build/lib/clang/8.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O1 -fdebug-compilation-dir /home/su/20180829-gcctk-m64-O3-wrong-232920/delta/clang -ferror-limit 19 -fmessage-length 108 -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/small-47b8d9.o -x c small.c -faddrsig 
1.	<eof> parser at end of file
2.	Per-module optimization passes
3.	Running pass 'CallGraph Pass Manager' on module 'small.c'.
4.	Running pass 'Simplify the CFG' on function '@main'
#&#8203;0 0x000000000267e8ea llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/su/software/tmp/polly/llvm/lib/Support/Unix/Signals.inc:494:0
#&#8203;1 0x000000000267ceea llvm::sys::RunSignalHandlers() /home/su/software/tmp/polly/llvm/lib/Support/Signals.cpp:67:0
#&#8203;2 0x000000000267d019 SignalHandler(int) /home/su/software/tmp/polly/llvm/lib/Support/Unix/Signals.inc:353:0
#&#8203;3 0x00007f8a3b323330 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10330)
#&#8203;4 0x00007f8a3a10bc37 gsignal /build/eglibc-SvCtMH/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#&#8203;5 0x00007f8a3a10f028 abort /build/eglibc-SvCtMH/eglibc-2.19/stdlib/abort.c:91:0
#&#8203;6 0x00007f8a3a104bf6 __assert_fail_base /build/eglibc-SvCtMH/eglibc-2.19/assert/assert.c:92:0
#&#8203;7 0x00007f8a3a104ca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
#&#8203;8 0x00000000021dec90 llvm::Value::setName(llvm::Twine const&) /home/su/software/tmp/polly/llvm/lib/IR/Value.cpp:295:0
#&#8203;9 0x00000000021dec99 llvm::isa_impl_cl<llvm::Function, llvm::Value const*>::doit(llvm::Value const*) /home/su/software/tmp/polly/llvm/include/llvm/Support/Casting.h:106:0
#&#8203;10 0x00000000021dec99 llvm::isa_impl_wrap<llvm::Function, llvm::Value const*, llvm::Value const*>::doit(llvm::Value const* const&) /home/su/software/tmp/polly/llvm/include/llvm/Support/Casting.h:133:0
#&#8203;11 0x00000000021dec99 llvm::isa_impl_wrap<llvm::Function, llvm::Value* const, llvm::Value const*>::doit(llvm::Value* const&) /home/su/software/tmp/polly/llvm/include/llvm/Support/Casting.h:125:0
#&#8203;12 0x00000000021dec99 isa<llvm::Function, llvm::Value*> /home/su/software/tmp/polly/llvm/include/llvm/Support/Casting.h:144:0
#&#8203;13 0x00000000021dec99 dyn_cast<llvm::Function, llvm::Value> /home/su/software/tmp/polly/llvm/include/llvm/Support/Casting.h:334:0
#&#8203;14 0x00000000021dec99 llvm::Value::setName(llvm::Twine const&) /home/su/software/tmp/polly/llvm/lib/IR/Value.cpp:297:0
#&#8203;15 0x000000000275d0a4 llvm::FoldBranchToCommonDest(llvm::BranchInst*, unsigned int) /home/su/software/tmp/polly/llvm/lib/Transforms/Utils/SimplifyCFG.cpp:2711:0
#&#8203;16 0x000000000275f848 SimplifyCondBranch /home/su/software/tmp/polly/llvm/lib/Transforms/Utils/SimplifyCFG.cpp:5861:0
#&#8203;17 0x000000000275f848 run /home/su/software/tmp/polly/llvm/lib/Transforms/Utils/SimplifyCFG.cpp:6042:0
#&#8203;18 0x000000000275f848 llvm::simplifyCFG(llvm::BasicBlock*, llvm::TargetTransformInfo const&, llvm::SimplifyCFGOptions const&, llvm::SmallPtrSetImpl<llvm::BasicBlock*>*) /home/su/software/tmp/polly/llvm/lib/Transforms/Utils/SimplifyCFG.cpp:6073:0
#&#8203;19 0x00000000025e4f17 iterativelySimplifyCFG(llvm::Function&, llvm::TargetTransformInfo const&, llvm::SimplifyCFGOptions const&) /home/su/software/tmp/polly/llvm/lib/Transforms/Scalar/SimplifyCFGPass.cpp:164:0
#&#8203;20 0x00000000025e517e simplifyFunctionCFG(llvm::Function&, llvm::TargetTransformInfo const&, llvm::SimplifyCFGOptions const&) /home/su/software/tmp/polly/llvm/lib/Transforms/Scalar/SimplifyCFGPass.cpp:178:0
#&#8203;21 0x00000000021a7077 llvm::FPPassManager::runOnFunction(llvm::Function&) /home/su/software/tmp/polly/llvm/lib/IR/LegacyPassManager.cpp:1529:0
#&#8203;22 0x0000000001c1253e RunPassOnSCC /home/su/software/tmp/polly/llvm/lib/Analysis/CallGraphSCCPass.cpp:167:0
#&#8203;23 0x0000000001c1253e RunAllPassesOnSCC /home/su/software/tmp/polly/llvm/lib/Analysis/CallGraphSCCPass.cpp:432:0
#&#8203;24 0x0000000001c1253e (anonymous namespace)::CGPassManager::runOnModule(llvm::Module&) /home/su/software/tmp/polly/llvm/lib/Analysis/CallGraphSCCPass.cpp:487:0
#&#8203;25 0x00000000021a7848 runOnModule /home/su/software/tmp/polly/llvm/lib/IR/LegacyPassManager.cpp:1612:0
#&#8203;26 0x00000000021a7848 llvm::legacy::PassManagerImpl::run(llvm::Module&) /home/su/software/tmp/polly/llvm/lib/IR/LegacyPassManager.cpp:1716:0
#&#8203;27 0x000000000284a995 ~PrettyStackTraceString /home/su/software/tmp/polly/llvm/include/llvm/Support/PrettyStackTrace.h:52:0
#&#8203;28 0x000000000284a995 (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) /home/su/software/tmp/polly/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp:845:0
#&#8203;29 0x000000000284beef ~unique_ptr /usr/include/c++/4.9/bits/unique_ptr.h:235:0
#&#8203;30 0x000000000284beef clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) /home/su/software/tmp/polly/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp:1273:0
#&#8203;31 0x00000000030e40fc ~unique_ptr /usr/include/c++/4.9/bits/unique_ptr.h:235:0
#&#8203;32 0x00000000030e40fc clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) /home/su/software/tmp/polly/llvm/tools/clang/lib/CodeGen/CodeGenAction.cpp:295:0
#&#8203;33 0x000000000364700e clang::ParseAST(clang::Sema&, bool, bool) /home/su/software/tmp/polly/llvm/tools/clang/lib/Parse/ParseAST.cpp:170:0
#&#8203;34 0x00000000030e3580 clang::CodeGenAction::ExecuteAction() /home/su/software/tmp/polly/llvm/tools/clang/lib/CodeGen/CodeGenAction.cpp:1045:0
#&#8203;35 0x0000000002c7b316 clang::FrontendAction::Execute() /home/su/software/tmp/polly/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:910:0
#&#8203;36 0x0000000002c4d37e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/su/software/tmp/polly/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:962:0
#&#8203;37 0x0000000002d1c631 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/su/software/tmp/polly/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:257:0
#&#8203;38 0x0000000000e5bd40 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /home/su/software/tmp/polly/llvm/tools/clang/tools/driver/cc1_main.cpp:218:0
#&#8203;39 0x0000000000dd5575 ExecuteCC1Tool /home/su/software/tmp/polly/llvm/tools/clang/tools/driver/driver.cpp:310:0
#&#8203;40 0x0000000000dd5575 main /home/su/software/tmp/polly/llvm/tools/clang/tools/driver/driver.cpp:382:0
#&#8203;41 0x00007f8a3a0f6f45 __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;42 0x0000000000e577e9 _start (/home/su/software/tmp/polly/llvm_build/bin/clang-6.0+0xe577e9)
clang-6: error: unable to execute command: Aborted (core dumped)
clang-6: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 8.0.0 (http://llvm.org/git/clang.git b9ef8cb5d0a5501643befcdcf6bef0a3dfa9e205) (llvm/trunk 341010)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
clang-6: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-6: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-6: note: diagnostic msg: /tmp/small-9c7ec0.c
clang-6: note: diagnostic msg: /tmp/small-9c7ec0.sh
clang-6: note: diagnostic msg: 

********************
$ 

---------------------------

int a, b;

int main ()
{
  for (; b; b = 1)
    {
      int d = 0;
      if (a)
	break;
    }
  return 0;
}

**Comment by fhahn** [comment]
I am unable to reproduce this on current main, so this likely has been fixed. Please re-open the issue with additional info if it still reproduces on your side.
