### ISSUE TITLE
Clang crash after when compiling bitcodefile.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38164]
|  |  |
| --- | --- |
| Bugzilla Link | [38816](https://llvm.org/bz38816) |
| Version | 6.0 |
| OS | All |
| Attachments | [bitcode file, LLVM IR human readable code and the clang log](https://user-images.githubusercontent.com/60944935/143758049-0f9e62ba-4993-49ca-bf5f-31732d27b322.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

I tried to compile a .bc file and clang crashed.

OS: Windows 10 1803

Output of clang --version:

clang version 6.0.1 (tags/RELEASE_601/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin

**Comment by JOE1994** [comment]
No longer reproducible with `llc 18.1.0` : https://godbolt.org/z/d7s1crnhx
