### ISSUE TITLE
Decl.cpp:2332: bool clang::VarDecl::checkInitIsICE() const: Assertion `!Init->isValueDependent()' failed

### ISSUE THREAD

**Issue by BalaRishi-AMD** [llvm/llvm-project#38168]
|  |  |
| --- | --- |
| Bugzilla Link | [38820](https://llvm.org/bz38820) |
| Version | trunk |
| OS | Linux |
| Attachments | [Reduced testcase file to reproduce the issue](https://user-images.githubusercontent.com/92601646/143758050-50acb768-d9e8-42c4-b6a2-34daa882e5f9.gz), [Console output for assertion error](https://user-images.githubusercontent.com/92601646/143758051-b330ce07-a1d8-4ed4-984f-a9fc27c41fb2.gz) |
| CC | @JVApen |

## Extended Description 

Faced the below assertion failure:

/home/amd/JENKINS/workspace/Staging_Build_Tracker/llvm/tools/clang/lib/AST/Decl.cpp:2332: bool clang::VarDecl::checkInitIsICE() const: Assertion `!Init->isValueDependent()' failed.

Steps to reproduce the issue with the reduced testcase:
- Download the attached file
- Compile the cpp file using the below command
   clang++  CE_assertion_err.cpp

**Comment by shafik** [comment]
I can not get this to reproduce anymore: https://godbolt.org/z/zojea635b

Please reopen if you can get this to reproduce on clang trunk.
