### ISSUE TITLE
[DebugInfo@O2][Dexter] Loop strength reduction preserves little debug info

### ISSUE THREAD

**Issue by jmorse** [llvm/llvm-project#38163]
|  |  |
| --- | --- |
| Bugzilla Link | [38815](https://llvm.org/bz38815) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#38116  |
| CC | @chrisjbris,@gregbedwell,@CarlosAlbertoEnciso,@elavkje,@pogo59 |

## Extended Description 
It seems the loop-strength-reduction pass doesn't preserve debug information, for any transformation it makes. Compiling the example below with llvm/clang @ r340912 and options "-O2 -g -fno-inline" for x86_64, using both gdb and lldb, both the value of "i" and "blah" are reported as being optimised out, after being rewritten by LSR:

-------->8--------
int
foo(int blah)
{
  int i;
  for (i = blah; i < blah + 10; i++) {
    if (i < 3)
      return 0;
  }
  return 1;
}

int
main()
{
  return foo(3);
}
--------8<--------

Which would be fairly frustrating if one landed in the loop and were unable to determine either the loop bound or which iteration it was on. (The example is contrived, but LSR still knackers more complicated loops).

This isn't a bug per se, and the DebugInfo doesn't mislead anyone, it's just a poor debug experience that will annoy developers. Particularly galling is that the values of "i" and "blah" remain in registers for the whole loop, but are still not available to the debugger.

**Comment by chrisjbris** [comment]
Suggest this issue is closed as the above patch has been present since 13.0.0 and there is also [D120168](https://reviews.llvm.org/D120168) to add further salvaging.

**Comment by jryans** [comment]
As @chrisjbris suggested above, I'll go ahead and close this issue since LSR debug info salvaging has landed. We can track further refinements with new issues as needed.
