### ISSUE TITLE
Enhance "returning address of local var" checker

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#38226]
|  |  |
| --- | --- |
| Bugzilla Link | [38878](https://llvm.org/bz38878) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
struct S&& po() {
    struct S tmp;
    return std::move(tmp);
}

No warning from Clang.

GCC warns:
<source>: In function 'S&& po()':
<source>:14:23: warning: function returns address of local variable [-Wreturn-local-addr]
14 |     return std::move(tmp);
   |                       ^
<source>:13:14: note: declared here
13 |     struct S tmp;

**Comment by wheatman** [comment]
This was fixed between 15 and 16
https://godbolt.org/z/3x86j1ofr

code
```
#include <utility>

struct S{};

struct S&& po() {
    struct S tmp;
    return std::move(tmp);
}



struct S&& po2() {
    struct S tmp;
    return std::forward<struct S>(tmp);
}

```

new warnings
```
<source>:7:22: warning: reference to stack memory associated with local variable 'tmp' returned [-Wreturn-stack-address]
    return std::move(tmp);
                     ^~~
<source>:14:35: warning: reference to stack memory associated with local variable 'tmp' returned [-Wreturn-stack-address]
    return std::forward<struct S>(tmp);
                                  ^~~
2 warnings generated.
Compiler returned: 0
```
