### ISSUE TITLE
modernize-use-override should be more careful with templates

### ISSUE THREAD

**Issue by steveire** [llvm/llvm-project#38276]
|  |  |
| --- | --- |
| Bugzilla Link | [38928](https://llvm.org/bz38928) |
| Version | unspecified |
| OS | Windows NT |

## Extended Description 
Given this code:

    template<typename T>
    struct Interface
    {
        virtual void foo(T) = 0;
    };

    template<>
    struct Interface<float>
    {
    };

    template<typename T, typename U>
    struct User : Interface<U>
    {
        // Not an override for all U.
        // clang-tidy should exclude methods on classes 
        // with template-dependent base.
        void foo(T);
    };

    template <typename T>
    struct Templ : public T
    {
        // Pure virtual. Shouldn't have keyword removed
        virtual int someMethod() const = 0;
    };

    struct Empty
    {
    };

    struct Intermediate : public Templ<Empty>
    {
        int someMethod() const override;
    };

    struct Klass : Templ<Intermediate>
    {
        int someMethod() const override
        {
            return {};
        }
    };

    int main(int argc, char**)
    {
        User<int, int> hasOverride;
        User<int, float> notHasOverride;

        return 0;
    }

clang-tidy issues two diagnostics which it should not:

    simplemain.cpp:19:10: warning: annotate this function with 'override' or (rarely) 'final' [modernize-use-override]
        void foo(T);
             ^
                    override
    simplemain.cpp:27:17: warning: prefer using 'override' or (rarely) 'final' instead of 'virtual' [modernize-use-override]
        virtual int someMethod() const = 0;
        ~~~~~~~~    ^
                                       override

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D147924
