### ISSUE TITLE
static_assert yields the wrong result when dereferencing a void*

### ISSUE THREAD

**Issue by c0d9e34c-d4b9-40a8-bbfe-81379a23f33c** [llvm/llvm-project#38275]
|  |  |
| --- | --- |
| Bugzilla Link | [38927](https://llvm.org/bz38927) |
| Version | 5.0 |
| OS | Linux |
| Attachments | [Failed static_assert with operator*(void*)](https://user-images.githubusercontent.com/95090737/143758093-6f9d3023-9fdb-4830-a845-984467750e61.gz) |
| CC | @dwblaikie,@DougGregor,@zygoloid |

## Extended Description 

Hello,

I've been playing with the detected idiom lately, and I came accross a bug related to void pointers.

For the record, I found two bugs in GCC with operator-(void*, void*) and operator-=(void*, void*).

Clang fails with operator*(void*), please see the attachment for a small example.

Expected result: the static_assert passes.

**Comment by wheatman** [comment]
Seems to have been fixed between 15.0.0 and 16.0.0
https://godbolt.org/z/q5M5T3P7j

For reference
code
```
template <typename T>
T&& declval();

template <typename ...>
using void_t = void;

template <typename T>
using dereference = decltype(*declval<T>());

template <typename T, typename = void>
struct can_dereference
{
  static constexpr auto const value = false;
};

template <typename T>
struct can_dereference<T, void_t<dereference<T>>>
{
  static constexpr auto const value = true;
};

int main(int argc, char const *argv[])
{
  static_assert(can_dereference<int*>::value, "");
  static_assert(!can_dereference<void*>::value, "");
  static_assert(!can_dereference<void>::value, "");
}

```
