### ISSUE TITLE
[X86] Poor codegen for comieq/comine intrinsics feeding a branch

### ISSUE THREAD

**Issue by topperc** [llvm/llvm-project#38308]
|  |  |
| --- | --- |
| Bugzilla Link | [38960](https://llvm.org/bz38960) |
| Version | trunk |
| OS | All |
| CC | @RKSimon,@rotateright |

## Extended Description
```
#include <x86intrin.h>

void foo();

void test_mm_comieq_ss(__m128 A, __m128 B) {
  if (_mm_comieq_ss(A, B))
    foo();
}
```
Produces
```
test_mm_comieq_ss(float __vector(4), float __vector(4)):
        vcomiss %xmm1, %xmm0
        setnp   %al
        sete    %cl
        andb    %al, %cl
        movzbl  %cl, %eax
        testl   %eax, %eax
        je      .LBB0_1
        jmp     foo()                 # TAILCALL
.LBB0_1:
        retq
```
Ideally we should only produce a vcomiss and two conditional jumps.

**Comment by RKSimon** [comment]
Current Codegen: https://godbolt.org/z/aWqovh7vf

**Comment by RKSimon** [comment]
clang vs gcc vs icc vs msvc: https://godbolt.org/z/q1WvPfEW8

**Comment by RKSimon** [comment]
CC'ing @topperc @phoebewang @pcordes

Looking at this again - the clang codegen hasn't improved at all (let's ignore gcc which completely ignores the NAN case in the parity flag).

MSVC avoids the and+zext entirely and just tests the 8-bit flag results:

```
test_mm_comieq_ss(float __vector(4), float __vector(4)):
  comiss %xmm1, %xmm0
  setnp   %al
  sete    %cl
  test    %al, %cl
  je      .LBB0_1
  jmp     foo()                 # TAILCALL
.LBB0_1:
  retq
```

while ICC prefers the multiple conditional jumps:
```
test_mm_comieq_ss:
  comiss %xmm1, %xmm0
  jne     ..B1.3
  jp      ..B1.3
  jmp     foo
..B1.3:
  ret #12.1
```

**Comment by RKSimon** [comment]
Dense conditional jumps often cause stalls on AMD targets (see https://reviews.llvm.org/D46662 which had a similar issue), so we might be better off with just avoiding the and+zext like MSVC.

**Comment by RKSimon** [comment]
Candidate Patch: https://reviews.llvm.org/D121472
