### ISSUE TITLE
clang-format breaks code by inserting spaces inside macro calls

### ISSUE THREAD

**Issue by 2cebcbff-deb3-4f85-8491-d6b0a69d170c** [llvm/llvm-project#38301]
|  |  |
| --- | --- |
| Bugzilla Link | [38953](https://llvm.org/bz38953) |
| Version | 7.0 |
| OS | Linux |
| CC | @dwblaikie |

## Extended Description 
$ cat test.c
```
#include <stdio.h>

#define AS_STRING(x) #x

int main() {
    puts(AS_STRING(string-with-minus));

}
```
$ gcc test.c && ./a.out
string-with-minus
$ clang-format-7 -i test.c && gcc test.c && ./a.out
string - with - minus
$ cat test.c
```
#include <stdio.h>

#define AS_STRING(x) #x

int main() { puts(AS_STRING(string - with - minus)); }
```
$ lsb_release -d
Description:	Ubuntu 18.04.1 LTS
$ dpkg-query --showformat='${Version}\n' --show clang-format-7
1:7~svn323616-1

The code changed its behavior after formatting because some whitespace was added inside a macro call.

**Comment by mydeveloperday** [comment]
I don't see how to avoid this as it sees this a `a-b-c` i.e  a minus b minus c? its not different to wanting

`int d = a - b -c;`

This is just one of those cases where you likely need to change the code, I don't see a solution

**Comment by mkurdej** [comment]
You can/should add your macro to `WhitespaceSensitiveMacros` option.
Closing but feel free to reopen if it doesn't fix your issue.
