### ISSUE TITLE
False positive from "misc-unused-using-decls" check when template deduction of constructor is used for a type

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38329]
|  |  |
| --- | --- |
| Bugzilla Link | [38981](https://llvm.org/bz38981) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @tonyelewis,@varqox |

## Extended Description 
The following code produces misc-unused-using-decls warning about unused using decl for std::pair:

--- begin: test1.cc ---
#include <utility>

using std::pair;

const pair v(1, 2);
--- end: test1.cc ---

--- begin: shell ---
$ clang-tidy-8 --checks='misc-unused-using-decls' ./test1.cc -- --std=c++17
1 warning generated.
/tmp/test1.cc:3:12: warning: using decl 'pair' is unused [misc-unused-using-decls]
using std::pair;
~~~~~~~~~~~^~~~~
--- end: shell ---

The warning disappears when template arguments are provided explicitly:

--- begin: test2.cc ---
#include <utility>

using std::pair;

const pair<int, int> v(1, 2);
--- end: test2.cc ---

The code (obviously) won't compile if "using std::pair;" is removed.

**Comment by carlosgalvezp** [comment]
Warning in the OP no longer reproducible on trunk.
