### ISSUE TITLE
[RFE] convert options from gnuindent to clang-format

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38354]
|  |  |
| --- | --- |
| Bugzilla Link | [39006](https://llvm.org/bz39006) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I've got a long list of various projects that run gindent with a huge string of options.

Can the Format documentation be extended to provide some mapping from gindent to clang-format?

ie:
SpaceAfterCStyleCast:
Is similar to `gindent --space-after-cast`

**Comment by mydeveloperday** [comment]
I don't really feel this is necessary for clang-format to do this.
