### ISSUE TITLE
“is_assignable” error when using LLVM / VS2017 / Boost 1.68

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38352]
|  |  |
| --- | --- |
| Bugzilla Link | [39004](https://llvm.org/bz39004) |
| Version | 7.0 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@pavelkryukov |

## Extended Description 
I receive the following build error when switching to LLVM toolset in VS2017 to build code using Boost 1.68. The code builds fine with MSVC compiler. 

1>C:\boost_1_68_0\boost/type_traits/has_trivial_move_assign.hpp(49): error : no template named 'is_assignable'; did you mean 'std::is_assignable'? 1>C:\boost_1_68_0\boost/type_traits/intrinsics.hpp(233): note: expanded from macro 'BOOST_HAS_TRIVIAL_MOVE_ASSIGN'

**Comment by arsenm** [comment]
Old build issue fixed elsewhere
