### ISSUE TITLE
Incorrect "use 'template' keyword to treat 'xxx' as a dependent template name" inside of virtual member functions of template classes

### ISSUE THREAD

**Issue by a06faff7-37e6-4b3d-a713-c8337ad9ce7f** [llvm/llvm-project#38395]
|  |  |
| --- | --- |
| Bugzilla Link | [39047](https://llvm.org/bz39047) |
| Version | 7.0 |
| OS | Windows NT |
| CC | @steveire |

## Extended Description 
E.g. the following code fails to compile:

    template <typename T>
    struct special_ptr
    {
        T* ptr;

        template <typename U>
        special_ptr<U> as()
        {
            special_ptr<U> result;
            result.ptr = reinterpret_cast<U*>(this->ptr);
            return result;
        }
    };

    template <typename T>
    struct thing
    {
        special_ptr<int> intPtr;

        virtual void do_something()
        {
            auto charPtr = this->intPtr.as<char>();
        }
    };

    struct empty {};

    int main()
    {
        thing<empty> t;
    }

You can also view it at https://godbolt.org/z/ywb5CS. Note that GCC does not have a problem with it. If you change 'thing' to no longer be a class template _or_ if you make 'do_something' no longer virtual, it compiles fine.

**Comment by d-patyk** [comment]
Issue can't be reproduced with newest clang (check godbolt), should be closed
