### ISSUE TITLE
32-bit and 64-bit pre-built binaries for Windows are invalid

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38411]
|  |  |
| --- | --- |
| Bugzilla Link | [39063](https://llvm.org/bz39063) |
| Version | 7.0 |
| OS | Windows NT |
| Attachments | [Dialog box received when attempting to install LLVM 7.0.0](https://user-images.githubusercontent.com/60944935/143758138-5d78265d-2a07-4da4-b135-5b950706e85c.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@efriedma-quic,@zmodem,@tlattner |

## Extended Description 

I have tried multiple downloads. All of them for a given platform (32-bit/64-bit) were the same size and all gave an error message during installation that they were invalid due to a failed integrity check. The 64-bit installation is about 25 MB smaller than the one for 6.0.1 (95 MB vs 120 MB).

**Comment by AaronBallman** [comment]
The correct redirect happens and I believe this issue can now be closed as completed.
