### ISSUE TITLE
clang does not support compilation with CUDA 10.0

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38413]
|  |  |
| --- | --- |
| Bugzilla Link | [39065](https://llvm.org/bz39065) |
| Version | trunk |
| OS | All |
| Attachments | [Patch to add preliminary support for CUDA 10.0](https://user-images.githubusercontent.com/60944935/143758141-331b17c7-088f-4475-a4c0-62d0f68f030c.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Clang 7.0 and trunk do not support compiling CUDA code with the CUDA 10.0 SDK that has just been released.

The attached path adds preliminary support for building with CUDA 10.0.

**Comment by arsenm** [comment]
This was handled long ago
