### ISSUE TITLE
valueless_by_exception() should unconditionally return false if all the constructors are noexcept

### ISSUE THREAD

**Issue by apolukhin** [llvm/llvm-project#38420]
|  |  |
| --- | --- |
| Bugzilla Link | [39072](https://llvm.org/bz39072) |
| Version | 7.0 |
| OS | Linux |
| CC | @apolukhin,@mclow |

## Extended Description 
Right now the variant::valueless_by_exception() is defined like that:

  constexpr bool valueless_by_exception() const noexcept {
    return index() == variant_npos;
  }

Above code is quite complex for the optimizer. It may be profitable to detect variant types that never have valueless_by_exception() state and re-implement the function:

  constexpr bool valueless_by_exception() const noexcept {
    return !__always_valid::value /*compile-time constant*/ && index() == variant_npos;
  }

Such change would improve assembly for multiple functions including comparisons, swap, get and constructors.

**Comment by philnik777** [comment]
I'm not sure it's ever possible to guarantee, since it's always possible that things like `emplace` throw somehow. I haven't checked whether libc++'s `variant` can become valueless that way, but it seems way too error-prone to actually implement.

**Comment by mordante** [comment]
Based on @philnik777 's evaluation this seems not worth to pursue.
