### ISSUE TITLE
Crash in RAGreedy::growRegion((anonymous namespace)::RAGreedy::GlobalSplitCandidate&)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38441]
|  |  |
| --- | --- |
| Bugzilla Link | [39093](https://llvm.org/bz39093) |
| Version | trunk |
| OS | Linux |
| Attachments | [crash dump asked to attach this file](https://user-images.githubusercontent.com/60944935/143758153-2a4c71a8-c236-4770-a802-da501d88f9bb.gz), [crash dump asked to attach this file](https://user-images.githubusercontent.com/60944935/143758154-dbe0982b-9c72-4421-aca7-0d2cc77bcba3.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

ccache clang -MMD -MF obj/third_party/externals/expat/lib/expat.xmltok.o.d -DHAVE_MEMMOVE -D_GLIBCXX_DEBUG -DXML_STATIC  -w -fstrict-aliasing -fPIC -g -Wno-unused-parameter -Wno-error -O3 -fdata-sections -ffunction-sections -isystem /home/bsalomon/src/skia/third_party/externals/expat/lib  -c ../../third_party/externals/expat/lib/xmltok.c -o obj/third_party/externals/expat/lib/expat.xmltok.o
Stack dump:
0.	Program arguments: /home/bsalomon/src/llvm/out/bin/clang-8 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name xmltok.c -mrelocation-model pic -pic-level 2 -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -ffunction-sections -fdata-sections -coverage-notes-file /home/bsalomon/src/skia/out/Debug/obj/third_party/externals/expat/lib/expat.xmltok.gcno -resource-dir /home/bsalomon/src/llvm/out/lib/clang/8.0.0 -isystem /home/bsalomon/src/skia/third_party/externals/expat/lib -D HAVE_MEMMOVE -D _GLIBCXX_DEBUG -D XML_STATIC -internal-isystem /usr/local/include -internal-isystem /home/bsalomon/src/llvm/out/lib/clang/8.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -Wno-unused-parameter -Wno-error -w -fdebug-compilation-dir /home/bsalomon/src/skia/out/Debug -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o obj/third_party/externals/expat/lib/expat.xmltok.o -x c ../../third_party/externals/expat/lib/xmltok.c -faddrsig 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '../../third_party/externals/expat/lib/xmltok.c'.
4.	Running pass 'Greedy Register Allocator' on function '@normal_contentTok'
#&#8203;0 0x0000000001ce5ab4 PrintStackTraceSignalHandler(void*) (/home/bsalomon/src/llvm/out/bin/clang-8+0x1ce5ab4)
#&#8203;1 0x0000000001ce3abe llvm::sys::RunSignalHandlers() (/home/bsalomon/src/llvm/out/bin/clang-8+0x1ce3abe)
#&#8203;2 0x0000000001ce5c72 SignalHandler(int) (/home/bsalomon/src/llvm/out/bin/clang-8+0x1ce5c72)
#&#8203;3 0x00007f641ae08890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)
#&#8203;4 0x000000000175f14a (anonymous namespace)::RAGreedy::growRegion((anonymous namespace)::RAGreedy::GlobalSplitCandidate&) (/home/bsalomon/src/llvm/out/bin/clang-8+0x175f14a)
#&#8203;5 0x000000000175c760 (anonymous namespace)::RAGreedy::calculateRegionSplitCost(llvm::LiveInterval&, llvm::AllocationOrder&, llvm::BlockFrequency&, unsigned int&, bool, bool*) (/home/bsalomon/src/llvm/out/bin/clang-8+0x175c760)
#&#8203;6 0x0000000001757852 (anonymous namespace)::RAGreedy::selectOrSplitImpl(llvm::LiveInterval&, llvm::SmallVectorImpl<unsigned int>&, llvm::SmallSet<unsigned int, 16u, std::less<unsigned int> >&, unsigned int) (/home/bsalomon/src/llvm/out/bin/clang-8+0x1757852)
#&#8203;7 0x0000000001752385 (anonymous namespace)::RAGreedy::selectOrSplit(llvm::LiveInterval&, llvm::SmallVectorImpl<unsigned int>&) (/home/bsalomon/src/llvm/out/bin/clang-8+0x1752385)
#&#8203;8 0x0000000001789d55 llvm::RegAllocBase::allocatePhysRegs() (/home/bsalomon/src/llvm/out/bin/clang-8+0x1789d55)
#&#8203;9 0x0000000001751a95 (anonymous namespace)::RAGreedy::runOnMachineFunction(llvm::MachineFunction&) (/home/bsalomon/src/llvm/out/bin/clang-8+0x1751a95)
#&#8203;10 0x00000000015a8d93 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/home/bsalomon/src/llvm/out/bin/clang-8+0x15a8d93)
#&#8203;11 0x000000000185cf65 llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/bsalomon/src/llvm/out/bin/clang-8+0x185cf65)
#&#8203;12 0x000000000185d1c3 llvm::FPPassManager::runOnModule(llvm::Module&) (/home/bsalomon/src/llvm/out/bin/clang-8+0x185d1c3)
#&#8203;13 0x000000000185d73f llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/bsalomon/src/llvm/out/bin/clang-8+0x185d73f)
#&#8203;14 0x0000000001e68d97 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/home/bsalomon/src/llvm/out/bin/clang-8+0x1e68d97)
#&#8203;15 0x00000000025a1c61 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/bsalomon/src/llvm/out/bin/clang-8+0x25a1c61)
#&#8203;16 0x0000000002cc2893 clang::ParseAST(clang::Sema&, bool, bool) (/home/bsalomon/src/llvm/out/bin/clang-8+0x2cc2893)
#&#8203;17 0x00000000022a5d87 clang::FrontendAction::Execute() (/home/bsalomon/src/llvm/out/bin/clang-8+0x22a5d87)
#&#8203;18 0x0000000002252118 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/bsalomon/src/llvm/out/bin/clang-8+0x2252118)
#&#8203;19 0x000000000233bc91 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/bsalomon/src/llvm/out/bin/clang-8+0x233bc91)
#&#8203;20 0x00000000008e1c50 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/bsalomon/src/llvm/out/bin/clang-8+0x8e1c50)
#&#8203;21 0x00000000008e0083 main (/home/bsalomon/src/llvm/out/bin/clang-8+0x8e0083)
#&#8203;22 0x00007f641988fb97 __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344:0
#&#8203;23 0x00000000008dd4ea _start (/home/bsalomon/src/llvm/out/bin/clang-8+0x8dd4ea)
clang-8: error: unable to execute command: Segmentation fault (core dumped)
clang-8: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 8.0.0 (trunk 343150)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/bsalomon/src/llvm/out/bin
clang-8: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-8: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-8: note: diagnostic msg: /tmp/xmltok-f9b367.c
clang-8: note: diagnostic msg: /tmp/xmltok-f9b367.sh
clang-8: note: diagnostic msg:

**Comment by Endilll** [comment]
Can't reproduce using Clang 6 through 9 with assertions enabled.
