### ISSUE TITLE
incorrect optimization with signaling NaN and implicit conversion in fabs: missing exception

### ISSUE THREAD

**Issue by vinc17fr** [llvm/llvm-project#38460]
|  |  |
| --- | --- |
| Bugzilla Link | [39112](https://llvm.org/bz39112) |
| Version | trunk |
| OS | Linux |
| CC | @efriedma-quic,@hfinkel,@rotateright |

## Extended Description 
With a code that does something like

  float f = fabs (double_snan)

one does not get the FE_INVALID exception with -O.

Details:

#include <stdio.h>
#include <inttypes.h>
#include <math.h>
#include <fenv.h>

typedef union { float f; uint32_t i; } ieee_float_t;

int main (void)
{
  volatile ieee_float_t x, y;
  volatile double d;

  x.i = 0x7f800001;
  printf ("0. %x (%g)\n", x.i, x.f);

  feclearexcept (FE_INVALID);
  y.f = fabs (x.f);
  if (fetestexcept (FE_INVALID))
    printf ("2. FE_INVALID\n");
  printf ("2. %x (%g)\n", y.i, y.f);

  return 0;
}

yields:

cventin% clang-8 snan.c -o snan -lm
cventin% ./snan
0. 7f800001 (nan)
2. FE_INVALID
2. 7fc00001 (nan)

which is correct (due to the float-to-double conversion of sNaN), but

cventin% clang-8 snan.c -o snan -lm -O
cventin% ./snan                       
0. 7f800001 (nan)
2. 7f800001 (nan)

The FE_INVALID exception is missing, and the result is a signaling NaN instead of a quiet NaN.

Tested with the clang-8 1:8~svn342638-1 Debian package (x86_64 architecture).

**Comment by vinc17fr** [comment]
> With a code that does something like
> ```
>   float f = fabs (double_snan)
> ```
> one does not get the FE_INVALID exception with `-O`.

Oops, I meant:
```
  float f = fabs (float_snan)
```
like in the details (I have not tried with double).

**Comment by vinc17fr** [comment]
No need to access the floating-point environment to reproduce the bug:

```c
#include <stdio.h>
#include <inttypes.h>
#include <math.h>

typedef union { float f; uint32_t i; } ieee_float_t;

int main (void)
{
  volatile ieee_float_t x, y;

  x.i = 0x7f800001;
  printf ("0. %x (%g)\n", x.i, x.f);

  y.f = fabs (x.f);
  printf ("2. %x (%g)\n", y.i, y.f);

  return 0;
}
```

```
cventin% clang-8 snan.c -o snan -lm
cventin% ./snan
0. 7f800001 (nan)
2. 7fc00001 (nan)
cventin% clang-8 snan.c -o snan -lm -O
cventin% ./snan
0. 7f800001 (nan)
2. 7f800001 (nan)
```

With `-O`, one gets a signaling NaN instead of a quiet NaN.

The bug disappears if one explicitly uses a volatile double as an intermediate variable (since `fabs` returns a double, this should not change anything):

```c
#include <stdio.h>
#include <inttypes.h>
#include <math.h>

typedef union { float f; uint32_t i; } ieee_float_t;

int main (void)
{
  volatile ieee_float_t x, y;
  volatile double d;

  x.i = 0x7f800001;
  printf ("0. %x (%g)\n", x.i, x.f);

  d = fabs (x.f);
  y.f = d;
  printf ("2. %x (%g)\n", y.i, y.f);

  return 0;
}
```

```
cventin% clang-8 snan.c -o snan -lm
cventin% ./snan
0. 7f800001 (nan)
2. 7fc00001 (nan)
cventin% clang-8 snan.c -o snan -lm -O
cventin% ./snan
0. 7f800001 (nan)
2. 7fc00001 (nan)
```

**Comment by arsenm** [comment]
Signaling nans aren't really supported without fenv access enabled, but it wouldn't matter in the case of fabs. fneg/fabs/copysign are bit only operations that do not raise exceptions

**Comment by vinc17fr** [comment]
> Signaling nans aren't really supported without fenv access enabled, but it wouldn't matter in the case of fabs. fneg/fabs/copysign are bit only operations that do not raise exceptions. The implicit float->double cast would raise the exception, but that requires the fenv access

You misread the bug report. This is **not only** about exceptions, but **also** about producing a signaling NaN. This is actually like #43070 (reported later). Even though strict support of signaling NaN is not required by ISO C, Clang claims compatibility with GCC, which aims to provide strict support for signaling NaNs when `-fsignaling-nans` is given (which Clang ignores), though GCC still has some bugs with this.

And actually, there is the same issue with just a cast:

```c
#include <stdio.h>
#include <inttypes.h>
#include <float.h>
#include <fenv.h>

typedef union { float f; uint32_t i; } ieee_float_t;

int main (void)
{
  volatile ieee_float_t x, y;

#ifdef FE_SNANS_ALWAYS_SIGNAL
  printf ("FE_SNANS_ALWAYS_SIGNAL is defined.\n");
#endif

  x.f = FLT_SNAN;
  printf ("%x (%g)\n", x.i, x.f);

  y.f = (double) x.f;
  printf ("%x (%g)\n", y.i, y.f);

  return 0;
}
```

This gives with clang 22.1.6 when using `-O`:
```
7fa00000 (nan)
7fa00000 (nan)
```
i.e., in the second line, one also gets a sNaN instead of a qNaN. However, `FE_SNANS_ALWAYS_SIGNAL` is not defined. But see the issue with GCC compatibility.

**Comment by vinc17fr** [comment]
Actually, the behavior should not depend on `FE_SNANS_ALWAYS_SIGNAL` (for ISO C23). F.2.2p3 says "Where specification of signaling NaNs is not provided, the behavior of signaling NaNs is implementation-defined (either treated as an ISO/IEC 60559 quiet NaN or treated as an ISO/IEC 60559 signaling NaN)." So, this means that a signaling NaN in input is treated either as a quiet NaN or a signaling NaN. Clang fails to handle this correctly, as shown above.

**Comment by arsenm** [comment]
If "the behavior of signaling NaNs is implementation-defined", then either quieting or not quieting is permitted? With clang, it does produce the quieted nan, but gcc does not: https://godbolt.org/z/fzGYrWbdj

**Comment by vinc17fr** [comment]
> If "the behavior of signaling NaNs is implementation-defined", then either quieting or not quieting is permitted?

IMHO, a signaling NaN in input may be treated as a quiet NaN, but a conversion should never produce a signaling NaN (thus optimizing float-double-float conversions would be incorrect if the input may be a signaling NaN).

> With clang, it does produce the quieted nan, but gcc does not: https://godbolt.org/z/fzGYrWbdj

This is without `-O` optimizations. But GCC does some optimizations even without `-O`, and I suppose that this is the case here. Note that such an optimization may be regarded as correct before C23 since older standards did not support signaling NaNs at all.
