### ISSUE TITLE
new check: do not return 0; at the end of main() in C++

### ISSUE THREAD

**Issue by kirillbobyrev** [llvm/llvm-project#38469]
|  |  |
| --- | --- |
| Bugzilla Link | [39121](https://llvm.org/bz39121) |
| Version | unspecified |
| OS | All |

## Extended Description 
As pointed out by Ilya Biryukov in one of the code reviews, C++ will automatically return 0; when control flow reaches the end of main;

https://en.cppreference.com/w/cpp/language/main_function:

> 4) The body of the main function does not need to contain the return statement: if control reaches the end of main without encountering a return statement, the effect is that of executing return 0;.

Saving one line of code is not a big deal, but it seems very easy to enforce and I think it's a nice idea for readability check.

Note that for C, it is only true since C99 ([docs](https://en.cppreference.com/w/c/language/main_function)).

**Comment by dwblaikie** [comment]
I /think/ there's a general idea that clang-tidy checks should be for conventions that have some standing in significant code bases? (perhaps I've got this wrong - maybe the bar is lower) if that's the case, are there some major codebase style guides that do have this rule in place?

**Comment by kirillbobyrev** [comment]
> I /think/ there's a general idea that clang-tidy checks should be for conventions that have some standing in significant code bases? (perhaps I've got this wrong - maybe the bar is lower) if that's the case, are there some major codebase style guides that do have this rule in place?

Hm, that's a good point!

Yeah, I'm not aware of such codebases, maybe it isn't worth it in the end.

**Comment by carlosgalvezp** [comment]
Posting my comment from the PR here as well for visibility:

I agree with the opinions from Aaron And Piotr above - this check does the opposite of readability: it forces people to waste time digging into the Standard to find the quote that says the return is not needed.

Could some argumentation be provided as to why this would be a good check to have? What coding guidelines/best practice articles promote this? I cannot think of any category where it would fit (besides misc).

I believe this is a nano-optimization, and premature optimization is the root of all evil :)
