### ISSUE TITLE
std::lower_bound speed can be improved.

### ISSUE THREAD

**Issue by e0e1e613-dccb-47a5-85db-3dc989429265** [llvm/llvm-project#38477]
|  |  |
| --- | --- |
| Bugzilla Link | [39129](https://llvm.org/bz39129) |
| Version | unspecified |
| OS | All |
| CC | @hfinkel,@mclow |

## Extended Description 
Recently Sean Parent discovered that his quickly hacked implementation of lower_bound is faster than the one that comes with the libcxx:

https://twitter.com/SeanParent/status/1042925651898974210

I did a quick experiment - the problem seems to be that he is using size_t while std::lower_bound uses std::iterator_traits<I>::difference_type. size_t is quicker to divide by two.

http://quick-bench.com/WhkonNgX40J3hk0A2Q8kQown96I

I ran some more measurements - the patterns seems to stay the same - here is binary search in 1000 integers, measured for looking up each number: https://plot.ly/~dyaroshev/110/#/

**Comment by philnik777** [comment]
This seems it has been years ago by the patches linked above, so I'm closing this.
