### ISSUE TITLE
Missing nonnull attribute for string_view(const _CharT* __s)

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#38481]
|  |  |
| --- | --- |
| Bugzilla Link | [39133](https://llvm.org/bz39133) |
| Version | unspecified |
| OS | Linux |
| CC | @dwblaikie,@mclow |

## Extended Description 
Passing nullptr to string_view(const _CharT* __s) is undefined behavior.

=> mark string_view(const _CharT* __s) with __attribute__((__nonnull__)) to enable more compiler optimizations?

**Comment by philnik777** [comment]
Closing, since I don't think we want to add `nonnull` attributes here. The compiler should be able to deduce `nonnull` here.
