### ISSUE TITLE
Extend llvm.dbg.value to take more than one LLVM SSA value.

### ISSUE THREAD

**Issue by CarlosAlbertoEnciso** [llvm/llvm-project#38489]
|  |  |
| --- | --- |
| Bugzilla Link | [39141](https://llvm.org/bz39141) |
| Version | trunk |
| OS | Linux |
| CC | @adrian-prantl,@dstenb,@dwblaikie,@flametop,@gregbedwell,@jmorse,@jryans,@pogo59,@vedantk,@wolfy1961 |

## Extended Description 
During the review of

https://reviews.llvm.org/D51976

where debug information being incorrect (-O2), there were some discussions about extending `llvm.dbg.value' to take more than one LLVM SSA value, as reflected by:

bug 38763 comment 7 and comment 8

**Comment by jryans** [comment]
If I understand correctly, the `DIArgList` work means this is now supported. @Melamoto, you've done most of the work on `DIArgList`, is it okay to close this issue and track any future details separately?

**Comment by SLTozer** [comment]
The feature has landed, this issue can be closed!
