### ISSUE TITLE
clang crashed with SIGSEGV in llvm:ManagedStaticBase::destroy()

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38559]
|  |  |
| --- | --- |
| Bugzilla Link | [39211](https://llvm.org/bz39211) |
| Version | 6.0 |
| OS | Linux |
| Attachments | [compile file,dmesg.txt,file created by ltrace and strace.](https://user-images.githubusercontent.com/60944935/143758202-54869b52-ef5d-46ff-bded-a45cb7a16406.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

System details:
  ubuntu 18.04 linux 4.15.0-34.37-generic 4.15.18
  clang 6.0
 
Bug details:
  when compile one c file with "-Xclang -load -Xclang" option to load a custom llvm-pass.so, clang crash with eip point to an unexpected address.

StackTrace
  ??()
  ??() from /usr/lib/llvm-6.0/bin/../lib/libLLVM-6.0.so.1
  llvm::ManagedStaticBase:destroy() const() from /usr/lib/llvm-6.0/bin/../lib/libLLVM-6.0.so.1
  llvm::llvm_shutdown() () from /usr/lib/llvm-6.0/bin/../lib/libLLVM-6.0.s0.1
  main()

Compile cmd:
  clang -Xclang -load -Xclang llvm-pass.so test-instr.c -o test-instr

Check the attachment with trace log and compiled file.

**Comment by Endilll** [comment]
> when compile one c file with "-Xclang -load -Xclang" option to load a custom llvm-pass.so

Author hasn't provided sources for this custom pass.
