### ISSUE TITLE
[Modules TS] #pragma once leaks out of module files in a way that macros do not

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38554]
|  |  |
| --- | --- |
| Bugzilla Link | [39206](https://llvm.org/bz39206) |
| Version | 7.0 |
| OS | Windows NT |
| Attachments | [Repro with build script](https://user-images.githubusercontent.com/60944935/143758200-55c28325-1488-40d2-bccb-022738a5398d.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @compnerd,@davidstone,@dwblaikie,@DougGregor,@jyknight,@zygoloid,@yuanfang-chen |

## Extended Description 

When I define a macro in a header that is included in both the implementation and interface modules the defined checks fail in the implementation module. 

### HEADER.H
#define MACRO

### MODULE.CPPM
#include "HEADER.H"
export module MyModule;
#ifndef MACRO
#error MISSING MACRO
#end

### IMPL.CPP
#include "HEADER.H"
module MyModule;
#ifndef MACRO
#error MISSING MACRO
#end

**Comment by davidstone** [comment]
Copying my minimal reproducer from #59708

```hpp
// a.hpp
#pragma once
using a = int;
```

```hpp
// b.hpp
#pragma once
#include "a.hpp"
a b;
```

```cpp
// c.cpp
module;
#include "b.hpp"
export module c;
```

Causes Clang to error with

```console
In file included from c.cpp:3:
b.hpp:4:1: error: unknown type name 'a'
a b;
^
```
