### ISSUE TITLE
[AMDGPU] shader generated by radeonsi crashes LLVM codegen

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38562]
|  |  |
| --- | --- |
| Bugzilla Link | [39214](https://llvm.org/bz39214) |
| Version | 6.0 |
| OS | Linux |
| Attachments | [bitcode](https://user-images.githubusercontent.com/60944935/143758203-366ce596-c3a0-4695-8cbd-f5d3dc51dbaf.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @arsenm |

## Extended Description 

The attached LLVM bitcode is prodcued by radeonsi.

LLVM 7.0.0:

--- snip ---
LLVM ERROR: Cannot select: 0x55bf333f40c0: v4i32,ch = load<(dereferenceable invariant load 16 from %ir.25, addrspace 2)> 0x55bf33367b28, 0x55bf333f9438, undef:i32
  0x55bf333f9438: i32 = add 0x55bf333f94a0, Constant:i32<272>
    0x55bf333f94a0: i32,ch = CopyFromReg 0x55bf33367b28, Register:i32 %42
      0x55bf333f98b0: i32 = Register %42
    0x55bf333f9710: i32 = Constant<272>
  0x55bf333f4128: i32 = undef
In function: main
--- snip ---

LLVM 6.0.1:

--- snip ---
#&#8203;0 0x00007fd358284daa llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/lib64/llvm/6/bin/../lib64/libLLVMSupport.so.6+0x108daa)
#&#8203;1 0x00007fd358282c96 llvm::sys::RunSignalHandlers() (/usr/lib64/llvm/6/bin/../lib64/libLLVMSupport.so.6+0x106c96)
#&#8203;2 0x00007fd358282f1b (/usr/lib64/llvm/6/bin/../lib64/libLLVMSupport.so.6+0x106f1b)
#&#8203;3 0x00007fd35717cfe0 (/lib64/libc.so.6+0x35fe0)
#&#8203;4 0x00007fd359ca34e1 (/usr/lib64/llvm/6/bin/../lib64/libLLVMCodeGen.so.6+0x2fb4e1)
Stack dump:
0.	Program arguments: /usr/lib/llvm/6/bin/llc llvm-code.bc 
1.	Running pass 'CallGraph Pass Manager' on module 'llvm-code.bc'.
2.	Running pass 'Simple Register Coalescing' on function '@main'
Segmentation fault
--- snip ---

**Comment by arsenm** [comment]
Out of date IR

**Comment by Endilll** [comment]
@arsenm Auto-upgraded IR to 16. Mind taking another look? 
[llvm-code-16.zip](https://github.com/llvm/llvm-project/files/12330043/llvm-code-16.zip)

**Comment by arsenm** [comment]
We never bothered trying to handle autoupgrading the address space numbers when those shuffled around. Mesa never relied on bitcode serialization
