### ISSUE TITLE
[clang-format] C99 designated initializers confused for Objective-C code

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38564]
|  |  |
| --- | --- |
| Bugzilla Link | [39216](https://llvm.org/bz39216) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @elvenfighter,@BigBigos |

## Extended Description 
The following C99 header file is confused for Objective-C code:
```
struct foo{
    int a;
};

struct foo bar[2] = {
    [0] = {.a = 1},
    [1] = {.a = 1}
};
```
# clang-format -style=file test.h
Configuration file(s) do(es) not support Objective-C: /tmp/.clang-format

A workaround is to rename the file to "something.c" before formatting, or reading it from stdin with "-assume-filename something.c".

**Comment by rymiel** [comment]
This seems to be fixed. Not sure when, but running on trunk with debug output gives `Language: C++`
