### ISSUE TITLE
googletest should not be compiled by default

### ISSUE THREAD

**Issue by tlattner** [llvm/llvm-project#3859]
|  |  |
| --- | --- |
| Bugzilla Link | [3487](https://llvm.org/bz3487) |
| Version | unspecified |
| OS | All |

## Extended Description 
googletest requires a gcc 4.X which limits the versions of gcc that can be used to compile llvm. We should still allow users to use 3.X because many version of 4.X don't work.

We should disable building googletest by default or have configure check for what version of gcc you have.

For 2.5, I have to hack this out.

**Comment by Quuxplusone** [comment]
13 years later, I'm going to suggest this can be closed as obsolete. Feel free to reopen if you disagree.
