### ISSUE TITLE
Assertion failed: (D->getCachedLinkage() == LV.getLinkage()), function getLVForDecl, file tools/clang/lib/AST/Decl.cpp, line 1422.

### ISSUE THREAD

**Issue by DimitryAndric** [llvm/llvm-project#38594]
|  |  |
| --- | --- |
| Bugzilla Link | [39246](https://llvm.org/bz39246) |
| Version | 7.0 |
| OS | All |

## Extended Description 
This assertion shows up when building the FreeBSD emulators/rpcs3 port (a PS/3 emulator) with either clang 6.0.1 or 7.0.0, see also https://bugs.freebsd.org/231952

Reduced test case:

// clang -cc1 -triple x86_64-- -S -std=gnu++17 cellAudio-minimized.cpp
struct a {};
template <typename> inline const a b;
struct {
  void c() { b<int>; }
} d;
void e() { d.c(); }

$ clang -cc1 -triple x86_64-- -S -std=gnu++17 cellAudio-minimized.cpp
cellAudio-minimized.cpp:5:14: warning: expression result unused
  void c() { b<int>; }
             ^~~~~~
Assertion failed: (D->getCachedLinkage() == LV.getLinkage()), function getLVForDecl, file /usr/src/contrib/llvm/tools/clang/lib/AST/Decl.cpp, line 1422.
Abort trap

**Comment by Endilll** [comment]
Appears to be fixed in Clang 9: https://godbolt.org/z/3Pb3n4Gvc
