### ISSUE TITLE
[mc][gfx7] image_atomic_f* -- insns not supported.

### ISSUE THREAD

**Issue by e7b993e6-0c19-4c7b-abbd-20f032a343c0** [llvm/llvm-project#38616]
|  |  |
| --- | --- |
| Bugzilla Link | [39268](https://llvm.org/bz39268) |
| Version | trunk |
| OS | Windows NT |
| CC | @atamazov,@dpreobra |

## Extended Description 
Leftover of bug 28240.

Unsupported instructions:
> image_atomic_fcmpswap
> image_atomic_fmax
> image_atomic_fmin

These do not exist on gfх8+.

**Comment by dpreobra** [comment]
Fixed by e5b0b434f60aa
