### ISSUE TITLE
Documentation for DILabel missing in LangRef

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38634]
|  |  |
| --- | --- |
| Bugzilla Link | [39286](https://llvm.org/bz39286) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @pogo59,@xgupta |

## Extended Description 
The DILabel specialized metadata note was added in LLVM 7.0. However, no documentation for DILabel has yet been added to the LLVM LangRef.

Compared to other specialized metadata nodes, e.g. DISubrange (https://llvm.org/docs/LangRef.html#disubrange), the documentation is expected to be present at https://llvm.org/docs/LangRef.html#dilabel

**Comment by xgupta** [comment]
Documentation for DILabel was added in https://reviews.llvm.org/D89082.
