### ISSUE TITLE
[AMDGPU][MC] Many MIMG opcodes do not accept tfe with dmask:0xf

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#38648]
|  |  |
| --- | --- |
| Bugzilla Link | [39300](https://llvm.org/bz39300) |
| Version | trunk |
| OS | All |
| CC | @atamazov,@jayfoad,@arsenm |

## Extended Description 
The reason for this issue is that current implementation does not support 5-register tuples.

**Comment by jwanggit86** [comment]
I think this problem is now fixed with PR [112622](https://github.com/llvm/llvm-project/pull/112622).

**Comment by arsenm** [comment]
Seems to work now
