### ISSUE TITLE
[AMDGPU][MC][GFX9] New SMEM format features are not supported

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#38652]
|  |  |
| --- | --- |
| Bugzilla Link | [39304](https://llvm.org/bz39304) |
| Version | trunk |
| OS | Windows NT |
| CC | @atamazov,@arsenm |

## Extended Description 
Current implementation does not support new GFX9 SMEM format features including:
- new NV bit
- new SOE bit
- new SOFFSET field.

**Comment by kosarev** [comment]
https://reviews.llvm.org/D126388 adds the support for GFX9 SMEM base+soffset+offset stores and thus completes resolving the soffset-related part of the ticket.

**Comment by dpreobra** [comment]
The SOFFSET/SOE issue with loads and stores has been resolved. But the following tests are still failing:

    s_atc_probe 0x0, s[4:5], s7 offset:0x12345
    s_atomic_add s5, s[2:3], s7 offset:0x12345
    s_buffer_atomic_add s5, s[4:7], s7 offset:0x12345
    s_dcache_discard s[2:3], s7 offset:0x12345

**Comment by kosarev** [comment]
Right, I didn't realise there are more SMEMs with immediate offsets. Will take care of these. Thanks.

**Comment by kosarev** [comment]
The `soffset` and `soffset_en` fields are now supported, if I don't miss anything.

**Comment by dpreobra** [comment]
I confirm that all tests for GFX9+ SMEM addressing modes have passed.

**Comment by dpreobra** [comment]
Fixed. See a list of patches above that addressed the issue.
