### ISSUE TITLE
Clang parser crashes on invalid input with typo suggestions on assertion "queried property of class with no definition"

### ISSUE THREAD

**Issue by orivej** [llvm/llvm-project#38659]
|  |  |
| --- | --- |
| Bugzilla Link | [39311](https://llvm.org/bz39311) |
| Version | trunk |
| OS | Linux |

## Extended Description 
This invalid input crashes "clang++ -c input.cpp":

     template <T> f() { class ClassA class : ClassB, ClassA

It is necessary for "ClassA" and "ClassB" names to be similar enough to trigger the typo suggestion and the crash. This affects all versions of Clang, from  3.7 to trunk (r344434).

This bug is different from llvm/llvm-project#13149  which is no longer reproducible.

**Comment by shafik** [comment]
This no longer reproduces on trunk: https://godbolt.org/z/13jeaEYGn

Looks like it was fixed around clang-14

**Comment by Endilll** [comment]
Fixed in Clang 14: https://godbolt.org/z/aMh15sTfz
