### ISSUE TITLE
Templated static inline variable ignores constructors

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38656]
|  |  |
| --- | --- |
| Bugzilla Link | [39308](https://llvm.org/bz39308) |
| Version | 6.0 |
| OS | Linux |
| Attachments | [testcase](https://user-images.githubusercontent.com/60944935/143758221-00ebd27e-022f-4f2f-bbf4-8a0832b8c75e.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Whenever a static inline variable has template parameters, the constructor is not called.

For example:

#include <iostream>

template <int T>
struct ValueHolder {
        ValueHolder(): val(T) {
                std::cout << "ValueHolder<" << T << "> constructed\n";
        }

        int val;
};

template <int T>
struct Test {
        template <int A = T>
        static inline ValueHolder<A> value;
};

template <int T>
struct Test2 {
        static inline ValueHolder<T> value;
};

template <int T>
struct Test3 {
        typedef ValueHolder<T> HolderType;

        static inline HolderType value;
};

typedef ValueHolder<10> HolderType2;
struct Test4 {
        static inline HolderType2 value;
};

int main() {
        Test3<10>::HolderType v;
        std::cout << "Expected: " << v.val << "\n";
        std::cout << "Got: " << Test<10>::value<10>.val << "\n";
        std::cout << "Got 2: " << Test2<10>::value.val << "\n";
        std::cout << "Got 3: " << Test3<10>::value.val << "\n";
        std::cout << "Got 4: " << Test4::value.val << "\n";
}

-----

This program should output 5 times, before "Expected: 10", the line "ValueHolder<10> constructed", but it is outputted only twice.

using:

$ clang -v
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Candidate multilib: .;@m64
Selected multilib: .;@m64

$ clang++ test.cpp -stdlib=libc++ -std=c++17

$ ./a.out 
ValueHolder<10> constructed
ValueHolder<10> constructed
Expected: 10
Got: 0
Got 2: 0
Got 3: 0
Got 4: 10

**Comment by wheatman** [comment]
This was fixed between 6 and 7
https://godbolt.org/z/o74voxqc1

code
```
// compile with -std=c++17 -stdlib=libc++
#include <iostream>

template <int T>
struct ValueHolder {
        ValueHolder(): val(T) {
                std::cout << "ValueHolder<" << T << "> constructed\n";
        }

        int val;
};

template <int T>
struct Test {
        template <int A = T>
        static inline ValueHolder<A> value;
};

template <int T>
struct Test2 {
        static inline ValueHolder<T> value;
};

template <int T>
struct Test3 {
        typedef ValueHolder<T> HolderType;

        static inline HolderType value;
};

typedef ValueHolder<10> HolderType2;
struct Test4 {
        static inline HolderType2 value;
};

int main() {
        Test3<10>::HolderType v;
        std::cout << "Expected: " << v.val << "\n";
        std::cout << "Got: " << Test<10>::value<10>.val << "\n";
        std::cout << "Got 2: " << Test2<10>::value.val << "\n";
        std::cout << "Got 3: " << Test3<10>::value.val << "\n";
        std::cout << "Got 4: " << Test4::value.val << "\n";
        return 0;
}
```

old output
```
Program returned: 0
ValueHolder<10> constructed
ValueHolder<10> constructed
Expected: 10
Got: 0
Got 2: 0
Got 3: 0
Got 4: 10
```

new output
```
Program returned: 0
ValueHolder<10> constructed
ValueHolder<10> constructed
ValueHolder<10> constructed
ValueHolder<10> constructed
ValueHolder<10> constructed
Expected: 10
Got: 10
Got 2: 10
Got 3: 10
Got 4: 10
```
