### ISSUE TITLE
modernize-use-using only works for trivial typedefs

### ISSUE THREAD

**Issue by steveire** [llvm/llvm-project#38677]
|  |  |
| --- | --- |
| Bugzilla Link | [39329](https://llvm.org/bz39329) |
| Version | unspecified |
| OS | Windows NT |
| CC | @EugeneZelenko,@mloskot |

## Extended Description 
Here are some constructs it choked on for me:

template<bool COND, typename IF_TRUE, typename IF_FALSE, typename OTHER>
struct If
{
    typedef OTHER Type;
};

template<typename IF_TRUE, typename IF_FALSE, typename OTHER>
struct If<true, IF_TRUE, IF_FALSE, OTHER>
{
    typedef IF_TRUE Type;
};

template<typename IF_TRUE, typename IF_FALSE, typename OTHER>
struct If<false, IF_TRUE, IF_FALSE, OTHER>
{
    typedef IF_FALSE Type;
};

If<true, int, double, float> ifstruct_true;

#define DEF_FOO __cdecl

struct A
{
    template<typename T>
    struct B
    {
        typedef void ( DEF_FOO T::*type)();
    };
};

namespace NS
{
    typedef bool (DEF_FOO *Func)();
}

template <typename T, typename U>
class Templ
{
public:
    typedef Templ<T, int> Temp;
};

Templ<double, int> tdi;

class NonTemplate
{
    typedef Templ<int, int> Heap;
};

template<typename T>
struct Outer
{
    template<typename U>
    struct Inner
    {
        using Type = U; 
    };
};

template<typename U>
struct TemplateKeyword
{
    typedef typename U::template Inner<int>::Type Type;
};

typedef bool TopFunc();

template<typename Func>
struct VarTempl;

template<typename T>
struct Container
{

};

template<typename... Args>
struct VarTempl<bool(Container<Args>...)>
{
    typedef bool Func(Container<Args>...);
};

**Comment by 5chmidti** [comment]
All of the above false-negatives are now detected: https://godbolt.org/z/5MGTjs5ve

I'm closing this as completed.

---

While the example

```c++
#define DEF_FOO __cdecl

struct A {
    template <typename T>
    struct B {
        typedef void (DEF_FOO T::*type)();
    };
};
```

works, it does expand the macro. That problem is tracked in https://github.com/llvm/llvm-project/issues/33760 and https://github.com/llvm/llvm-project/issues/37846, and fixed in #113837.
