### ISSUE TITLE
[AMDGPU][MC][DISASSEMBLER] Incorrect MIMG VAddr size for many opcodes

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#38671]
|  |  |
| --- | --- |
| Bugzilla Link | [39323](https://llvm.org/bz39323) |
| Version | trunk |
| OS | All |
| CC | @atamazov,@arsenm,@nhaehnle,@yuanfang-chen |

## Extended Description 
Many MIMG instructions have incorrect VAddr size when disassembled.

For example, according with AMD doc, image_gather4 does not support 1D so at least 2 address components are required (2D). However the following GFX8 code

    0x00,0x01,0x00,0xf1,0x01,0x05,0x62,0x00

is disassembled to 

    image_gather4 v[5:8], v1, s[8:15], s[12:15] dmask:0x1

The expected result is:

    image_gather4 v[5:8], v[1:2], s[8:15], s[12:15] dmask:0x1

Well, I assume this is because GFX8 reuses hardcoded tables from GFX9 which supports a16.

However when looking at GFX9 code, the results are the same. Moreover, a16 modifier does not affect VAddr size. For example, the following GFX9 code

    0x00,0x01,0x04,0xf1,0x01,0x05,0x62,0x00
    0x00,0x81,0x04,0xf1,0x01,0x05,0x62,0x00

is disassembled to:

    image_gather4_cl v[5:8], v1, s[8:15], s[12:15] dmask:0x1
    image_gather4_cl v[5:8], v1, s[8:15], s[12:15] dmask:0x1 a16

Note that:
- a16 does not affect VAddr size.
- according with AMD doc, VAddr cannot have less than 3 components for image_gather4_cl (so at least 2 with a16=1).

Expected results are:

    image_gather4_cl v[5:8], v[1:3], s[8:15], s[12:15] dmask:0x1
    image_gather4_cl v[5:8], v[1:2], s[8:15], s[12:15] dmask:0x1 a16

This issue results in disassembler test failures for all GATHER and most SAMPLE instructions for both GFX8 and GFX9. Assembler tests mostly pass (there are no issues with VAddr size).

**Comment by jwanggit86** [comment]
I've tested this with GFX8 and got the following results:

```
$ llvm-mc -triple=amdgcn -mcpu=tonga -show-encoding test.s
        .text
        image_gather4 v[5:8], v1, s[8:15], s[12:15] dmask:0x1 ; encoding: [0x00,0x01,0x00,0xf1,0x01,0x05,0x62,0x00]
        image_gather4 v[5:8], v[1:2], s[8:15], s[12:15] dmask:0x1 ; encoding: [0x00,0x01,0x00,0xf1,0x01,0x05,0x62,0x00]
        image_gather4 v[5:8], v[1:3], s[8:15], s[12:15] dmask:0x1 ; encoding: [0x00,0x01,0x00,0xf1,0x01,0x05,0x62,0x00]
        image_gather4 v[5:8], v[1:4], s[8:15], s[12:15] dmask:0x1 ; encoding: [0x00,0x01,0x00,0xf1,0x01,0x05,0x62,0x00]
```
For VAddr, it accepts 1 to 4 vgprs and they all produce the same binary. Disassembling the binary produces the first version of the assembly code. Note that sp3 only allows the first version. So is this still a problem that needs fix?

**Comment by arsenm** [comment]
> Disassembling the binary produces the first version of the assembly code. Note that sp3 only allows the first version. So is this still a problem that needs fix?

I don't understand the details of image instructions, but I think the claim here is that the first variant here should not be produced. However if SP3 accepts it, it's probably correct. 

Skimming the documents, I haven't found this note that image_gather4 only supports 1D, or anything about how dmask is interpreted for it. Is 0x1 supposed to be an invalid value to use?

**Comment by jwanggit86** [comment]
To be precise, sp3 accepts this: `image_gather4 v5, v1, s[8:15], s[12:15] dmask:0x1`, i.e., both the 1st and 2nd operands must be 32b. I think they each are interpreted as the first of a number of consecutive registers.

**Comment by jwanggit86** [comment]
Closing this issue as the behavior seems to be correct.
