### ISSUE TITLE
No definition emitted for template class static variable

### ISSUE THREAD

**Issue by andrewjcg** [llvm/llvm-project#38719]
|  |  |
| --- | --- |
| Bugzilla Link | [39371](https://llvm.org/bz39371) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
In some cases (seemingly involving namespaces, and use of the static variable in a function within the module), a definition for a template class's static variable isn't emitted.  Simplified repro at https://reviews.llvm.org/differential/diff/170323/.

**Comment by LittleHuba** [comment]
One further scenario where this occurs is this code snippet:

```C++
int val{3};
int set{val};

struct Container
{
    int set;
};

template <typename T>
class TemplatedContainer
{
  public:
    static const Container container;
};

template <typename T>
const Container TemplatedContainer<T>::container{
    set
};

int main()
{
    return TemplatedContainer<void>::container.set;
}
```

**Comment by shafik** [comment]
Adding `constexpr` to `val` and `set` fixes the issue: https://godbolt.org/z/YcfMa4WxT

I feel like this may be related to: https://github.com/llvm/llvm-project/issues/61028

I feel like technically this behavior may be allowed, I feel @tahonermann may have looked at a similar problem not too long ago

**Comment by LittleHuba** [comment]
> Adding `constexpr` to `val` and `set` fixes the issue: https://godbolt.org/z/YcfMa4WxT
> 
> I feel like this may be related to: https://github.com/llvm/llvm-project/issues/61028
> 
> I feel like technically this behavior may be allowed, I feel @tahonermann may have looked at a similar problem not too long ago

That works as long as you have types that have constexpr constructors. But that is not necessarily the case.

**Comment by tahonermann** [comment]
> Actually I think this is: https://github.com/llvm/llvm-project/issues/61028

I agree. That issue also links the relevant wording; [[basic.start.dynamic]p1](https://eel.is/c++draft/basic.start.dynamic#1). The initialization of `TemplatedContainer<void>::container` is unordered relative to `val` and `set`.
