### ISSUE TITLE
Compilation failure LLVM >= 7, gcc > 5 when system CUDA present

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38736]
|  |  |
| --- | --- |
| Bugzilla Link | [39388](https://llvm.org/bz39388) |
| Version | 7.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @tstellar |

## Extended Description 
LLVM's build system will automatically search system paths for a CUDA installation. CUDA strictly limits itself to old versions of GCC. When building LLVM with a recent version of GCC on a system with an installation of CUDA, the build will fail with the following error.

/usr/local/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
#error -- unsupported GNU version! gcc versions later than 5 are not supported!

In my case, the error occurred when building LLVM 7.0.0 with GCC 6.3, 7.2, and 8.2 on Centos 7, however I could successfully build with the same combination in a debian container without a CUDA installation.

Ideally LLVM's build system would check CUDA for compiler compatibility before including it, but at a minimum, is there a way to explicitly disable CUDA support for LLVM?

**Comment by arsenm** [comment]
Old build issue
