### ISSUE TITLE
Update GitHubMove.rst to reflect finalized monorepo layout

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#38743]
|  |  |
| --- | --- |
| Bugzilla Link | [39395](https://llvm.org/bz39395) |
| Version | unspecified |
| OS | Linux |
| Blocks | llvm/llvm-project#38741  |

## Extended Description 
Also remove proposed layouts to prevent confusion.

**Comment by asl** [comment]
@tstellar Done?

**Comment by tstellar** [comment]
I'm not sure where that file is.  I think we can close this.
