### ISSUE TITLE
Add "login with github" support to bugzilla

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#38778]
|  |  |
| --- | --- |
| Bugzilla Link | [39430](https://llvm.org/bz39430) |
| Version | unspecified |
| OS | Linux |
| Blocks | llvm/llvm-project#38741  |
| CC | @asl,@jyknight,@kbeyls,@kbeyls,@rnk,@miloserdow |

**Comment by asl** [comment]
We moved to github, so this is obsolete
