### ISSUE TITLE
bugprone-dangling-handle gets confused with typedefs

### ISSUE THREAD

**Issue by no-more-secrets** [llvm/llvm-project#38779]
|  |  |
| --- | --- |
| Bugzilla Link | [39431](https://llvm.org/bz39431) |
| Version | unspecified |
| OS | Linux |
| CC | @EugeneZelenko |

## Extended Description 
bugprone-dangling-handle does not work with libstdc++
because its std::basic_string class contains code that
boils down to the following (with EXPOSE_BUG=1):

// =============================================
#define EXPOSE_BUG 0 // set to 1 to expose bug

namespace std {

struct basic_string_view {};
using string_view = basic_string_view;

class basic_string {
 public:
  basic_string();
  ~basic_string();

#if EXPOSE_BUG
  typedef basic_string_view __sv_type;
  operator __sv_type() const noexcept;
#else
  operator basic_string_view() const noexcept;
#endif

};

using string = basic_string;

}

void f() {
  // This line does not trigger bugprone-dangling-handle
  // when EXPOSE_BUG=1
  std::string_view sv = std::string();
}
// =============================================

i.e., it uses a type alias for the return type of the
operator member function that converts a string to
a string_view.  This causes bugprone-dangling-handle
to fail to detect the conversion to string_view and
therefore does not raise an exception for the line
in f().  At least that is what seems to be happening
to me.

Note that the above code will fail linking as-is, but
still should be sufficient to demonstrate the clang-tidy
issue.

I tested this with llvm/clang-tidy trunk as of a few
days prior to raising this issue.

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D148418
