### ISSUE TITLE
Bad machine code: Instruction ending live segment doesn't read the register

### ISSUE THREAD

**Issue by francisvm** [llvm/llvm-project#38788]
|  |  |
| --- | --- |
| Bugzilla Link | [39440](https://llvm.org/bz39440) |
| Version | trunk |
| OS | All |
| Blocks | llvm/llvm-project#27855  |
| CC | @andreyv,@francisvm,@MatzeB,@qcolombet |

## Extended Description 
*** Bad machine code: Instruction ending live segment doesn't read the register ***
- function:    fn
- basic block: %bb.5 if.then13 (0x7fcd6d80ada0) [720B;1056B)
- instruction: 992B	%3:gr8 = COPY %9:gr8
- liverange:   [96r,128B:1)[128B,992r:0)[992r,1056B:3)[1056B,1136B:0)[1136B,1264B:6)[1328B,1776B:6)[1776B,1904r:8)[1920r,1968B:2)[1968B,2192r:5)[2400r,2448B:4)[3024r,3088B:7)  0@128B-phi 1@96r 2@1920r 3@992r 4@2400r 5@1968B-phi 6@1136B-phi 7@3024r 8@1776B-phi
- v. register: %3
- segment:     [128B,992r:0)
LLVM ERROR: Found 1 machine code errors.

Seems to come after Simple Register Coalescing.

build/bin/llc -verify-machineinstrs test/CodeGen/X86/pr38795.ll -O2 -mtriple=i386-unknown-linux-gnu -o -

**Comment by arsenm** [comment]
Still broken

**Comment by arsenm** [comment]
Reduced:

```
# RUN: llc -mtriple=i386-unknown-linux-gnu -verify-coalescing -run-pass=register-coalescer -o - %s
---
name:            fn
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $eax
    %0:gr32 = COPY $eax

  bb.1:
    %1:gr32 = IMPLICIT_DEF
    JCC_1 %bb.3, 4, implicit undef $eflags

  bb.2:
    %0:gr32 = MOV32r0 implicit-def dead $eflags

  bb.3:
    %0:gr32 = COPY %0
    JCC_1 %bb.5, 4, implicit undef $eflags

  bb.4:
    %1:gr32 = COPY %0

  bb.5:
    %0:gr32 = COPY killed %1
    JMP_1 %bb.1

...

```

**Comment by arsenm** [comment]
It works if I remove the identity copy in %bb.2, claiming interference between %0 and %1 and they are not coalesced

**Comment by arsenm** [comment]
Disabling identity copy coalescing for live out values fixes the MIR testcase and fixes the original test verifier error without any lit regressions. However, I still hit the same verifier error in the reduced IR of the original failure

**Comment by arsenm** [comment]
https://reviews.llvm.org/D158850 helps with the reduced tests, seems to need another fix though

**Comment by arsenm** [comment]
https://reviews.llvm.org/D158882 fixes it
