### ISSUE TITLE
comments on bugs do not send mail to llvm-bugs@

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#38793]
|  |  |
| --- | --- |
| Bugzilla Link | [39445](https://llvm.org/bz39445) |
| Version | unspecified |
| OS | Linux |
| CC | @hfinkel,@kbeyls,@kbeyls,@RKSimon,@pogo59,@rnk,@TNorthover |

## Extended Description 
Adding a comment on an existing bug does not send mail to llvm-bugs@, only to explicitly-CC'd people. This means that subscribing to llvm-bugs@ cannot be used as a way to watch bug activity via email, and also that commenting on bugs with no explicitly CC'd people sends mail to no-one.

**Comment by RKSimon** [comment]
Resolving - we now use GitHub Issues with its own notification controls (as well as CC'ing new bugs to llvm-bugs@)
