### ISSUE TITLE
X86 JIT doesn't support TLS

### ISSUE THREAD

**Issue by edwintorok** [llvm/llvm-project#3879]
|  |  |
| --- | --- |
| Bugzilla Link | [3507](https://llvm.org/bz3507) |
| Version | unspecified |
| OS | Linux |
| Attachments | [bugpoint-reduced-simplified.bc](https://user-images.githubusercontent.com/92601246/143738837-6f11a00a-d25b-4b6f-ac23-b7d591feabfa.gz) |
| CC | @AlexDenisov,@dwblaikie,@lhames |

## Extended Description 
With 2.5 prerelease on x86-64 linux:

lli: X86CodeEmitter.cpp:516: void<unnamed>::Emitter::emitInstruction(const llvm::MachineInstr&, const llvm::TargetInstrDesc*): Assertion `0 && "psuedo instructions should be removed before code emission"' failed.
0   lli       0x00000000009ebe8f
1   libc.so.6 0x00002b868c576f60
2   libc.so.6 0x00002b868c576ed5 gsignal + 53
3   libc.so.6 0x00002b868c5783f3 abort + 387
4   libc.so.6 0x00002b868c56fdc9 __assert_fail + 233
5   lli       0x00000000004d0e2f
6   lli       0x00000000004d205f
7   lli       0x000000000099469b llvm::FPPassManager::runOnFunction(llvm::Function&) + 347
8   lli       0x0000000000994a96 llvm::FunctionPassManagerImpl::run(llvm::Function&) + 134
9   lli       0x0000000000994c1e llvm::FunctionPassManager::run(llvm::Function&) + 62
10  lli       0x00000000006533f8 llvm::JIT::runJITOnFunction(llvm::Function*) + 56
11  lli       0x0000000000653669 llvm::JIT::getPointerToFunction(llvm::Function*) + 281
12  lli       0x000000000065bf75
13  lli       0x0000000000616edf X86CompilationCallback2 + 79
14  lli       0x0000000000616dfa
exit 134
RunSafely.sh detected a failure with these command-line arguments:  500 0 /dev/null Output/tls.out-jit /home/edwin/llvm2.5/llvm/Release/bin/lli -force-interpreter=false --disable-core-files Output/tls.llvm.bc

Attached reduced testcase

**Comment by arsenm** [comment]
Closing as obsolete based on comment from @lhames

**Comment by lhames** [comment]
Sounds good to me.

Native TLS support continues to improve, but it's in an intermediate state at the moment: Well supported on Darwin, somewhat supported on Linux, not supported on Windows as far as I know. Improvements are ongoing and I new architectures, and possibly new TLS models, to become supported over the next two years.
