### ISSUE TITLE
Nested Scope formatting failure

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38852]
|  |  |
| --- | --- |
| Bugzilla Link | [39504](https://llvm.org/bz39504) |
| Version | 7.0 |
| OS | Windows NT |
| Attachments | [Clangformat file](https://user-images.githubusercontent.com/60944935/143758275-b968e6be-92b4-4c9b-95fd-702fc23c790e.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

The following code is a simplified version of a thousand line piece of old C++ code:
```cpp
int main()
{
  { // Do group of things 1

    { // Do group of things 1 - A
      Thing1A1();
      Thing1A2();
    }

    NotUsed();

    { // Do group of things 1 - B
      Thing1B1();
      Thing1B2();
    }
  }

  { // Do group of things 2

    { // Do group of things 2 - A
      Thing2A1();
      Thing2A2();
    }

    { // Do group of things 2 - B
      Thing2B1();
      Thing2B2();
    }
  }
}
```
It formats to how it's displayed, which is correct for my projects clang-format file. However, comment out or remove the "NotUsed()" method, and it then formats like so:
```cpp
int main()
{
  {// Do group of things 1

   {// Do group of things 1 - A
    Thing1A1();
  Thing1A2();
}

// NotUsed();

{ // Do group of things 1 - B
  Thing1B1();
  Thing1B2();
}
}

{ // Do group of things 2

  { // Do group of things 2 - A
    Thing2A1();
    Thing2A2();
  }

  { // Do group of things 2 - B
    Thing2B1();
    Thing2B2();
  }
}
}
```
Which is considerably wrong. The scoping has been used to group like regions together in existing code (not how I would've done it, but still valid I guess). Putting a "(void)nullptr;" where the NotUsed() statement was fixes the formatting for a short-term workaround.

**Comment by rymiel** [comment]
Duplicate of https://github.com/llvm/llvm-project/issues/33891
