### ISSUE TITLE
Remove implicit nodes from AST when using AST Matchers

### ISSUE THREAD

**Issue by steveire** [llvm/llvm-project#38870]
|  |  |
| --- | --- |
| Bugzilla Link | [39522](https://llvm.org/bz39522) |
| Version | unspecified |
| OS | Linux |
| CC | @JonasToth,@LebedevRI,@ymand |

## Extended Description 
The Clang AST has many implicit nodes which are not so useful when writing AST Matchers. They cause confusion for newcomers. ASTMatchFinder deliberately includes them when traversing the AST with RAV. It should instead use the default behavior of RAV, which is to exclude those nodes. This also requires some changes to the ASTMatchFinder itself. 

$ cat struct.cpp 

class A
{
 int foo();
};

#ifdef DEFINE_B_STRUCT 
class B
{
  virtual int foo();
};
#endif

$ cat cmds.txt                      

m functionDecl()

set output dump

m functionDecl()

clang-query-6.0 -f cmds.txt struct.cpp -- -DDEFINE_B_STRUCT

Match #&#8203;1:

struct.cpp:4:2: note: "root" binds here
 int foo();
 ^~~~~~~~~

Match #&#8203;2:

struct.cpp:10:3: note: "root" binds here
  virtual int foo();
  ^~~~~~~~~~~~~~~~~

Match #&#8203;3:

Match #&#8203;4:

Match #&#8203;5:

struct.cpp:8:7: note: "root" binds here
class B
      ^
5 matches.

Match #&#8203;1:

Binding for "root":
CXXMethodDecl 0x55df7fd37458 <struct.cpp:4:2, col:10> col:6 foo 'int ()'

Match #&#8203;2:

Binding for "root":
CXXMethodDecl 0x55df7fd37720 <struct.cpp:10:3, col:19> col:15 foo 'int ()' virtual

Match #&#8203;3:

Binding for "root":
CXXMethodDecl 0x55df7fd37818 <struct.cpp:8:7, <invalid sloc>> col:7 implicit constexpr operator= 'B &(const B &)' inline default noexcept-unevaluated 0x55df7fd37818
`-ParmVarDecl 0x55df7fd37940 <col:7> col:7 'const B &'

Match #&#8203;4:

Binding for "root":
CXXMethodDecl 0x55df7fd379d8 <struct.cpp:8:7, <invalid sloc>> col:7 implicit constexpr operator= 'B &(B &&)' inline default noexcept-unevaluated 0x55df7fd379d8
`-ParmVarDecl 0x55df7fd37b00 <col:7> col:7 'B &&'

Match #&#8203;5:

Binding for "root":
CXXDestructorDecl 0x55df7fd37b88 <struct.cpp:8:7> col:7 implicit ~B 'void ()' inline default trivial noexcept-unevaluated 0x55df7fd37b88

5 matches.

**Comment by PiotrZSL** [comment]
This is already fixed, now you can provide TK_IgnoreUnlessSpelledInSource on both matcher level in code and in clang-query with `set traversal`.
Done by 246b428fb3b5d58685064966bcea6592f8839b7e
