### ISSUE TITLE
[llvm-exegesis] segfault in llvm-exegesis

### ISSUE THREAD

**Issue by tschuett** [llvm/llvm-project#38924]
|  |  |
| --- | --- |
| Bugzilla Link | [39576](https://llvm.org/bz39576) |
| Version | trunk |
| OS | Linux |
| CC | @legrosbuffle,@gchatelet,@RKSimon |

## Extended Description 
Hi,

when running:
./llvm-exegesis -mode=latency -opcode-name=ADD64rr
I get a segfault. This seems to be independent of the arguments and I have been running into this problem for a while now.

#&#8203;0  0x00007ffff6c76d60 in std::string::data() const () from /lib64/libstdc++.so.6
#&#8203;1  0x000000000095f568 in StringRef (Str=<error reading variable: Cannot access memory at address 0x1e0>, this=<optimized out>)
    at /local/FOO/llvm/include/llvm/ADT/StringRef.h:96
#&#8203;2  llvm::TargetMachine::getTargetCPU (this=0x0) at /local/FOO/llvm/include/llvm/Target/TargetMachine.h:106
#&#8203;3  0x000000000097ce2a in llvm::exegesis::ExecutableFunction::ExecutableFunction(std::unique_ptr<llvm::LLVMTargetMachine, std::default_delete<llvm::LLVMTargetMachine> >, llvm::object::OwningBinary<llvm::object::ObjectFile>&&) (this=0x7fffffffdaf0, TM=
    std::unique_ptr<llvm::LLVMTargetMachine> containing 0x7fffffffdc40,
    ObjectFileHolder=<unknown type in /local/FOO/clang/bin/llvm-exegesis, CU 0x466f33f, DIE 0x4778b6c>)
    at /local/FOO/llvm/tools/llvm-exegesis/lib/Assembler.cpp:282
#&#8203;4  0x000000000095ec01 in llvm::exegesis::BenchmarkRunner::runConfiguration (this=0x36d4a80, BC=..., NumRepetitions=10000)
    at /local/FOO/llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp:126
#&#8203;5  0x0000000000410c95 in llvm::exegesis::benchmarkMain () at /local/FOO/llvm/tools/llvm-exegesis/llvm-exegesis.cpp:374
#&#8203;6  0x0000000000411247 in main (Argc=3, Argv=0x7fffffffe148) at /local/FOO/llvm/tools/llvm-exegesis/llvm-exegesis.cpp:455

This is a skylake server with CentOS 7.5. LLVM is a trunk build with debug.

Please let me now, if I you want me to provide more information.

Thanks,
  Thorsten

**Comment by LebedevRI** [comment]
I can not reproduce. If it still happens, please help with reproduction steps.
