### ISSUE TITLE
clang++ (v. 7.0.0) segfault at -O2 but not -O1

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38927]
|  |  |
| --- | --- |
| Bugzilla Link | [39579](https://llvm.org/bz39579) |
| Version | 7.0 |
| OS | MacOS X |
| Attachments | [clang++ output to stdout](https://user-images.githubusercontent.com/60944935/143758315-b63f1386-335e-4237-8d35-ec631e9026dd.gz), [.crash file](https://user-images.githubusercontent.com/60944935/143758316-a1e5635d-8e72-4694-b93e-7e272f387dc6.gz), [.sh file](https://user-images.githubusercontent.com/60944935/143758317-a74673a1-5dc7-4763-af4c-49bc8f43d3a8.gz), [preprocessed .cpp file, part 1](https://user-images.githubusercontent.com/60944935/143758318-96eaf82a-35c6-426d-8f1a-e5e6c7e99e3b.gz), [preprocessed .cpp file, part 2](https://user-images.githubusercontent.com/60944935/143758319-4b2a2306-804b-4776-8a47-71b02caa20dc.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@zygoloid |

## Extended Description 

Hi, my clang++ installation crashes when compiling a file c++ source file. 

```
$ clang++ --version
clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```

It segfaults with the -O2 flag, but not with -O1.

I'll attach the stdout output from clang++ as well as the three files asked in the diagnostics message.
Attached file will be from running with -O2.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 8: https://godbolt.org/z/88szaYaf1
Reduced by me and C-Reduce:
```cpp
void Assert(bool);

struct Matrix {
  int mNrows;
  int mNcols;
  int *operator[](int) const;
};

void ConstructFullMatrix(const Matrix &aA, const Matrix &aB, Matrix &aMat) {
  Assert(aA.mNcols == aB.mNcols && aA.mNrows == aB.mNrows);
  for (; aA.mNrows;)
    for (int j; aA.mNcols; ++j)
      aMat[0][0] = aA[0][0] * aB[0][j];
}

void RspEqSolve() {
  Matrix full;
  ConstructFullMatrix({}, {}, full);
}
```
