### ISSUE TITLE
crash at goto label inside sizeof

### ISSUE THREAD

**Issue by TabbyBelka** [llvm/llvm-project#38949]
|  |  |
| --- | --- |
| Bugzilla Link | [39601](https://llvm.org/bz39601) |
| Version | trunk |
| OS | All |
| CC | @zygoloid |

## Extended Description 
source.cpp:
int main() {
    sizeof(({M:0;}));
    goto M;
}
output:
clang-8: error: unable to execute command: Segmentation fault (core dumped)
clang-8: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 8.0.0 (trunk 346454)
Target: x86_64-unknown-linux-gnu
Thread model: posix

Code is a little strange... gcc gets sigsegv too :)

**Comment by Endilll** [comment]
Appears to be fixed in post-17 trunk: https://godbolt.org/z/Y85s1PGo9
