### ISSUE TITLE
make check-all bug:   clang-8: error: unable to execute command: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38975]
|  |  |
| --- | --- |
| Bugzilla Link | [39627](https://llvm.org/bz39627) |
| Version | trunk |
| OS | Linux |
| Attachments | [reproducer scripts](https://user-images.githubusercontent.com/60944935/143758324-38798a2f-aff2-45ff-b7de-5a5b0de2400b.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Tasks:
run "make check-all" in the build directory.

[ 96%] Built target cxx_static
[ 98%] Built target cxx_filesystem
[100%] Built target cxx_experimental
[ 87%] Built target libcxx_fuzzer_x86_64-build
[ 87%] Built target RTfuzzer_main.x86_64
[ 88%] Built target RTfuzzer.x86_64
[ 88%] Built target clang_rt.fuzzer-x86_64
[ 88%] Built target clang_rt.fuzzer_no_main-x86_64
Scanning dependencies of target fuzzer
[ 88%] Built target fuzzer
[ 88%] Built target RTFuzzerTest.x86_64
Scanning dependencies of target TFuzzer-x86_64-Test
[ 88%] Generating FuzzerTestObjects.FuzzerUnittest.cpp.x86_64.o
[ 88%] Generating FuzzerTestObjects.gtest-all.cc.x86_64.o
Stack dump:
0.	Program arguments: /root/build/bin/clang-8 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -main-file-name gtest-all.cc -mrelocation-model pic -pic-level 2 -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -momit-leaf-frame-pointer -coverage-notes-file /root/build/projects/compiler-rt/lib/fuzzer/tests/FuzzerTestObjects.gtest-all.cc.x86_64.gcno -nostdinc++ -resource-dir /root/build/lib/clang/8.0.0 -isystem /root/build/projects/compiler-rt/lib/fuzzer/libcxx_fuzzer_x86_64/include/c++/v1 -D GTEST_NO_LLVM_RAW_OSTREAM=1 -D GTEST_HAS_RTTI=0 -I /root/llvm/utils/unittest/googletest/include -I /root/llvm/utils/unittest/googletest -I /root/llvm/projects/compiler-rt/lib/fuzzer -internal-isystem /usr/local/include -internal-isystem /root/build/lib/clang/8.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O2 -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -Wall -Wno-unused-parameter -Wno-unknown-warning-option -pedantic -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /root/build/projects/compiler-rt/lib/fuzzer/tests -ferror-limit 19 -fmessage-length 80 -fvisibility-inlines-hidden -fno-rtti -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o FuzzerTestObjects.gtest-all.cc.x86_64.o -x c++ /root/llvm/utils/unittest/googletest/src/gtest-all.cc -faddrsig 
1.	<eof> parser at end of file
2.	Per-module optimization passes
3.	Running pass 'Function Pass Manager' on module '/root/llvm/utils/unittest/googletest/src/gtest-all.cc'.
4.	Running pass 'Combine redundant instructions' on function '@_ZNK7testing8UnitTest19disabled_test_countEv'
#&#8203;0 0x0000000004b8cd2b llvm::sys::PrintStackTrace(llvm::raw_ostream&) /root/llvm/lib/Support/Unix/Signals.inc:495:0
#&#8203;1 0x0000000004b8cdbe PrintStackTraceSignalHandler(void*) /root/llvm/lib/Support/Unix/Signals.inc:559:0
#&#8203;2 0x0000000004b8aab8 llvm::sys::RunSignalHandlers() /root/llvm/lib/Support/Signals.cpp:67:0
#&#8203;3 0x0000000004b8c726 SignalHandler(int) /root/llvm/lib/Support/Unix/Signals.inc:358:0
#&#8203;4 0x00007f5850db6390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
#&#8203;5 0x000000000454500e foldAndToXor(llvm::BinaryOperator&, llvm::IRBuilder<llvm::TargetFolder, llvm::IRBuilderCallbackInserter>&) /root/llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp:1418:0
#&#8203;6 0x0000000004546110 llvm::InstCombiner::visitAnd(llvm::BinaryOperator&) /root/llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp:1547:0
#&#8203;7 0x0000000004525675 llvm::InstVisitor<llvm::InstCombiner, llvm::Instruction*>::visit(llvm::Instruction&) /root/llvm/include/llvm/IR/Instruction.def:145:0
#&#8203;8 0x000000000451ea25 llvm::InstCombiner::run() /root/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:3185:0
#&#8203;9 0x000000000451fc83 combineInstructionsOverFunction(llvm::Function&, llvm::InstCombineWorklist&, llvm::AAResults*, llvm::AssumptionCache&, llvm::TargetLibraryInfo&, llvm::DominatorTree&, llvm::OptimizationRemarkEmitter&, bool, llvm::LoopInfo*) /root/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:3417:0
#&#8203;10 0x000000000452006b llvm::InstructionCombiningPass::runOnFunction(llvm::Function&) /root/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:3477:0
#&#8203;11 0x00000000042ef683 llvm::FPPassManager::runOnFunction(llvm::Function&) /root/llvm/lib/IR/LegacyPassManager.cpp:1644:0
#&#8203;12 0x00000000042ef8f5 llvm::FPPassManager::runOnModule(llvm::Module&) /root/llvm/lib/IR/LegacyPassManager.cpp:1679:0
#&#8203;13 0x00000000042efcfc (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /root/llvm/lib/IR/LegacyPassManager.cpp:1744:0
#&#8203;14 0x00000000042f0509 llvm::legacy::PassManagerImpl::run(llvm::Module&) /root/llvm/lib/IR/LegacyPassManager.cpp:1857:0
#&#8203;15 0x00000000042f074d llvm::legacy::PassManager::run(llvm::Module&) /root/llvm/lib/IR/LegacyPassManager.cpp:1889:0
#&#8203;16 0x0000000004e780fc (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) /root/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp:862:0
#&#8203;17 0x0000000004e7b4c2 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) /root/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp:1296:0
#&#8203;18 0x0000000005b6e6d3 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) /root/llvm/tools/clang/lib/CodeGen/CodeGenAction.cpp:295:0
#&#8203;19 0x000000000706b567 clang::ParseAST(clang::Sema&, bool, bool) /root/llvm/tools/clang/lib/Parse/ParseAST.cpp:177:0
#&#8203;20 0x0000000005616019 clang::ASTFrontendAction::ExecuteAction() /root/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:1018:0
#&#8203;21 0x0000000005b6c502 clang::CodeGenAction::ExecuteAction() /root/llvm/tools/clang/lib/CodeGen/CodeGenAction.cpp:1045:0
#&#8203;22 0x0000000005615a1a clang::FrontendAction::Execute() /root/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:920:0
#&#8203;23 0x00000000055a17f6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /root/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:968:0
#&#8203;24 0x000000000577b98f clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /root/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:266:0
#&#8203;25 0x000000000252f39e cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /root/llvm/tools/clang/tools/driver/cc1_main.cpp:218:0
#&#8203;26 0x000000000252455c ExecuteCC1Tool(llvm::ArrayRef<char const*>, llvm::StringRef) /root/llvm/tools/clang/tools/driver/driver.cpp:310:0
#&#8203;27 0x00000000025252a1 main /root/llvm/tools/clang/tools/driver/driver.cpp:382:0
#&#8203;28 0x00007f584fb13830 __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:325:0
#&#8203;29 0x0000000002521e79 _start (/root/build/bin/clang-8+0x2521e79)
clang-8: error: unable to execute command: Segmentation fault (core dumped)
clang-8: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 8.0.0 (trunk 346579) (llvm/trunk 346569)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /root/build/projects/compiler-rt/lib/fuzzer/tests/../../../../../bin
clang-8: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-8: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-8: note: diagnostic msg: /tmp/gtest-all-e83a6e.cpp
clang-8: note: diagnostic msg: /tmp/gtest-all-e83a6e.sh
clang-8: note: diagnostic msg: 

********************

**Comment by Endilll** [comment]
Can't reproduce using Clang 6 through 9 with assertions enabled.
