### ISSUE TITLE
MachineOperand TargetFlags truncation

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38988]
|  |  |
| --- | --- |
| Bugzilla Link | [39640](https://llvm.org/bz39640) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @francisvm |

## Extended Description 
/// Subregister number for MO_Register.  A value of 0 indicates the
  /// MO_Register has no subReg.
  ///
  /// For all other kinds of operands, this field holds target-specific flags.
  unsigned SubReg_TargetFlags : 12;

We have 12 bits for the field but are using "unsigned char" for setter values:

  /// Replace this operand with a target index.
  void ChangeToTargetIndex(unsigned Idx, int64_t Offset,
                           unsigned char TargetFlags = 0);

  static MachineOperand CreateMBB(MachineBasicBlock *MBB,
                                  unsigned char TargetFlags = 0) {

  static MachineOperand CreateCPI(unsigned Idx, int Offset,
                                  unsigned char TargetFlags = 0) {

  static MachineOperand CreateTargetIndex(unsigned Idx, int64_t Offset,
                                          unsigned char TargetFlags = 0) {

And so forth

**Comment by arsenm** [comment]
These look like they all use unsigned today
