### ISSUE TITLE
Assertion `!isNull() && "Cannot retrieve a NULL type pointer"' failed at clang/AST/Type.h

### ISSUE THREAD

**Issue by BalaRishi-AMD** [llvm/llvm-project#38984]
|  |  |
| --- | --- |
| Bugzilla Link | [39636](https://llvm.org/bz39636) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
Description:
Assertion `!isNull() && "Cannot retrieve a NULL type pointer"' failed at clang/AST/Type.h.

To reproduce with the reduce testcase, download 'test-forall-reduced.cpp' and execute:
clang-8 -cc1 -fopenmp   test-forall-reduced.cpp

**Comment by Endilll** [comment]
Can't reproduce using assertion builds of Clang 7 and 8: https://godbolt.org/z/TP9obvGYh
I also tested locally unreduced test case with exactly the same compiler arguments as author suggested.
