### ISSUE TITLE
backport r346699 (#39628 ) to 7.0

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#38986]
|  |  |
| --- | --- |
| Bugzilla Link | [39638](https://llvm.org/bz39638) |
| Version | trunk |
| OS | Linux |
| Depends On | llvm/llvm-project#38976  |
| CC | @zygoloid |

## Extended Description 
r346699 is a safe and localized fix for a wrong-code bug; we should take it for any future 7.0 patch release.

**Comment by arsenm** [comment]
Old release
