### ISSUE TITLE
clang-format sorts headers even when /* clang-format off */ is used

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#38994]
|  |  |
| --- | --- |
| Bugzilla Link | [39646](https://llvm.org/bz39646) |
| Version | 7.0 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
When files include "/* clang-format off */" right at the top, this is ignored and headers are sorted anyway.

Changing this instead to "// clang-format off" makes it work as expected and not sort the headers.

Looking through Format.cpp, in sortCppIncludes, there is an explicit check for "// clang-format off" but not the former version, when both should work. 

Formatting is disabled as expected:

// clang-format off
#include "b.h"
#include "a.h"

Formatting re-orders headers when it shouldn't:

/* clang-format off */
#include "b.h"
#include "a.h"   <- these will be sorted

**Comment by mydeveloperday** [comment]
This was fix by https://reviews.llvm.org/D58819  and landed in 9b468c0b1e3f6b2df84e0891263488bd61456eec
