### ISSUE TITLE
Incorrect use-list order is generated due to stale user created when attempting to constant fold

### ISSUE THREAD

**Issue by 009b8ea0-6754-41bc-becf-d830f82bdd65** [llvm/llvm-project#39008]
|  |  |
| --- | --- |
| Bugzilla Link | [39660](https://llvm.org/bz39660) |
| Version | trunk |
| OS | Linux |
| Attachments | [IR reproducer.](https://user-images.githubusercontent.com/92601278/143758334-af7618f6-672e-41a0-a437-e0deb1bff43d.gz) |
| CC | @dstenb,@mikaelholmen |

## Extended Description 

Seen on trunk (r346809).

A run of verify-uselistorder on the attached IR reproducer fails, due to the use-list order for i64 ptrtoint (i64 ()* @&#8203;foo to i64) being incorrect.

$ verify-uselistorder reduced.ll -debug 2>&1 | grep -A11 fail:
 - fail: user mismatch: ID = 5
 - LHS value = i64 ptrtoint (i64 ()* @&#8203;foo to i64)
   => use: op = 0, user-id = 7, user = i64 add (i64 ptrtoint (i64 ()* @&#8203;foo to i64), i64 ptrtoint (i64 ()* @&#8203;foo to i64))
   => use: op = 1, user-id = 7, user = i64 add (i64 ptrtoint (i64 ()* @&#8203;foo to i64), i64 ptrtoint (i64 ()* @&#8203;foo to i64))
   => use: op = 0, user-id = 9, user = i64 add (i64 ptrtoint (i64 ()* @&#8203;foo to i64), i64 1)
   => use: op = 0, user-id = 0, user = i64 add (i64 ptrtoint (i64 ()* @&#8203;foo to i64), i64 zext (i1 icmp eq (i64 add (i64 ptrtoint (i64 ()* @&#8203;foo to i64), i64 1), i64 0) to i64))
 - RHS value = i64 ptrtoint (i64 ()* @&#8203;foo to i64)
   => use: op = 0, user-id = 0, user = i64 add (i64 ptrtoint (i64 ()* @&#8203;foo to i64), i64 zext (i1 icmp eq (i64 add (i64 ptrtoint (i64 ()* @&#8203;foo to i64), i64 1), i64 0) to i64))
   => use: op = 0, user-id = 9, user = i64 add (i64 ptrtoint (i64 ()* @&#8203;foo to i64), i64 1)
   => use: op = 1, user-id = 7, user = i64 add (i64 ptrtoint (i64 ()* @&#8203;foo to i64), i64 ptrtoint (i64 ()* @&#8203;foo to i64))
   => use: op = 0, user-id = 7, user = i64 add (i64 ptrtoint (i64 ()* @&#8203;foo to i64), i64 ptrtoint (i64 ()* @&#8203;foo to i64))

If you look in the file, you can see that the following user does not exist:

  user = i64 add (i64 ptrtoint (i64 ()* @&#8203;foo to i64), i64 zext (i1 icmp eq (i64 add (i64 ptrtoint (i64 ()* @&#8203;foo to i64), i64 1), i64 0) to i64))

That constant expression is created when parsing:

  i64 add (i64 add (i64 ptrtoint (i64 () * @&#8203;foo to i64), i64 ptrtoint (i64 () * @&#8203;foo to i64)), i64 zext (i1 icmp eq (i64 add (i64 ptrtoint (i64 () * @&#8203;foo to i64), i64 1), i64 0) to i64))

That constant expression is attempted to be constant folded by ConstantFoldBinaryInstruction(), and the new constant expression is created when attempting to rewrite the outermost add:

  // Given ((a + b) + c), if (b + c) folds to something interesting, return
  // (a + (b + c)).
  if (Instruction::isAssociative(Opcode) && CE1->getOpcode() == Opcode) {
    Constant *T = ConstantExpr::get(Opcode, CE1->getOperand(1), C2);
    if (!isa<ConstantExpr>(T) || cast<ConstantExpr>(T)->getOpcode() != Opcode)
      return ConstantExpr::get(Opcode, CE1->getOperand(0), T);

**Comment by mikaelholmen** [comment]
The reduced.ll reproducer doesn't "work" anymore since zext/sext constant expressions were disallowed in e4a4122eb6768b
```[IR] Remove zext and sext constant expressions (#71040)```
so now we just get
```
build-all/bin/verify-uselistorder: reduced.ll:8:106: error: zext constexprs are no longer supported
  store i64 add (i64 add (i64 ptrtoint (i64 () * @foo to i64), i64 ptrtoint (i64 () * @foo to i64)), i64 zext (i1 icmp eq (i64 add (i64 ptrtoint (i64 () * @foo to i64), i64 1), i64 0) to i64)), i64* null
```
when running the reproducer.
I think I'll close this ticket, and if the problem shows up again with a new reproducer without constant expression zext we can open a new ticket then.
