### ISSUE TITLE
clang-tidy: support for Intel compiler flags

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39035]
|  |  |
| --- | --- |
| Bugzilla Link | [39687](https://llvm.org/bz39687) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @JonasToth |

## Extended Description 
clang-tidy doesn't understand compiler flags that are specific to the Intel compiler and so bails if you try to use it alongside the intel toolchain in for example CMake's clang-tidy integration. 

example error:
error: language not recognized: 'SSE4.2' [clang-diagnostic-error]
error: unknown argument '-qopenmp', did you mean '-fopenmp='? [clang-diagnostic-error]
error: unknown argument: '-qno-offload' [clang-diagnostic-error]
error: unknown argument: '-qopt-report-phase=loop,vec,offload' [clang-diagnostic-error]
error: unknown argument: '-qopt-report5' [clang-diagnostic-error]

I guess if used alongside a compilation database then the compilation database could be filtered to remove / translate the intel specific flags to ones that clang understands but it is more convenient to be able to run it directly as part of CMake's invocation.

An option to list a set of compiler arguments to ignore could be one way of handling this?

**Comment by EugeneZelenko** [comment]
I think Jonas suggestion is reasonable. It's hard to keep up with every possible command-line option of every C/C++ compiler.
