### ISSUE TITLE
Aarch64 and "llvm-build: error: invalid target to enable: 'Aarch64' (not in project)"

### ISSUE THREAD

**Issue by 70311826-e6d8-4d29-8604-c4ec4bfa7f0d** [llvm/llvm-project#39046]
|  |  |
| --- | --- |
| Bugzilla Link | [39698](https://llvm.org/bz39698) |
| Version | 7.0 |
| OS | Linux |
| CC | @kbeyls,@noloader |

## Extended Description 
I'm working on GCC117 from the compile farm, which is Aarch64. I'm building LLVM and components from the 7.0 release tarballs.

CMake configure is dying at:

-- Performing Test C_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG
-- Performing Test C_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG - Failed
-- Performing Test CXX_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG
-- Performing Test CXX_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG - Success
-- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP
-- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP - Failed
-- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG
-- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG - Failed
-- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG
-- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG - Failed
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.13")
-- Constructing LLVMBuild project information
CMake Error at CMakeLists.txt:683 (message):

  Unexpected failure executing llvm-build: Usage: llvm-build [options]

  llvm-build: error: invalid target to enable: 'Aarch64' (not in project)

-- Configuring incomplete, errors occurred!

**Comment by arsenm** [comment]
Typo in target name
