### ISSUE TITLE
clang crashes on valid code at -Os and above on x86_64-linux-gnu: fatal error: error in backend: Broken function found, compilation aborted!

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#39066]
|  |  |
| --- | --- |
| Bugzilla Link | [39718](https://llvm.org/bz39718) |
| Version | unspecified |
| OS | All |
| CC | @hfinkel,@zygoloid,@rotateright |

## Extended Description 
Tested with trunk revision 347212. 

$ clangpolly -v
clang version 8.0.0 (http://llvm.org/git/clang.git 8ab54153b8c32d61c5c2251ae490940cbe47a6cc) (http://llvm.org/git/llvm.git 23ff23942df1b56bc58b0282ec762f2aa62c7406)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$
$ clangpolly -O1 small.c; ./a.out
$
$ clangpolly -Os small.c
Instruction does not dominate all uses!
  %spec.select = zext i1 %not.tobool2 to i8
  %and = and i8 %0, %spec.select
in function main
fatal error: error in backend: Broken function found, compilation aborted!
clang-6: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 8.0.0 (http://llvm.org/git/clang.git 8ab54153b8c32d61c5c2251ae490940cbe47a6cc) (http://llvm.org/git/llvm.git 23ff23942df1b56bc58b0282ec762f2aa62c7406)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
clang-6: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-6: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-6: note: diagnostic msg: /tmp/small-8cd6d5.c
clang-6: note: diagnostic msg: /tmp/small-8cd6d5.sh
clang-6: note: diagnostic msg:

********************
$

------------------------------------

char a, e, f;
int b, c, d;

char g (char h)
{ 
  return h == 0 ? a : a % h;
}

int main ()
{ 
  for (; d; d++)
    b = g (e & (f && (c = 1)));
  return 0;
}

**Comment by fhahn** [comment]
This doesn't reproduce on either 8.0, 9.0 nor `main`: https://clang.godbolt.org/z/49ra4rsGx

I *think* the offending commit should have been reverted and recommit with a fix according to @rotateright 's comment. I think it's time to close the issue, but please re-open with additional info if it still reproduces on your end.
