### ISSUE TITLE
crashed while matching template template argument with default value

### ISSUE THREAD

**Issue by sw6ueyz** [llvm/llvm-project#39135]
|  |  |
| --- | --- |
| Bugzilla Link | [39788](https://llvm.org/bz39788) |
| Version | 7.0 |
| OS | Windows NT |
| Attachments | [clang said "PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT" and these are the files](https://user-images.githubusercontent.com/92601778/143758378-348855c5-b2de-48d7-893b-b148a5b2f4f4.gz) |
| CC | @DougGregor,@zygoloid,@rnk |

## Extended Description 

crashed with following log :
=========================================

clang-cl.exe : error : clang frontend command failed due to signal (use -v to see invocation)

clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-pc-windows-msvc
Thread model: posix

clang-cl.exe: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.

**Comment by Endilll** [comment]
Both test cases appear to be fixed in Clang 10:
https://godbolt.org/z/a6rr9Wz5c
https://godbolt.org/z/PPvvnxfcM

Original test case reduced by C-Reduce:
```
template <int _NN, template <int _N, int = _N> class _Templ> struct Test {
  _Templ<_NN> x;
};
template <int, int> struct Templ;
Test<0, Templ> t;
```
CC @shafik if you had interest in this particular bug
