### ISSUE TITLE
[AMDGPU] Couldn't join subrange in one of mcxcl sources

### ISSUE THREAD

**Issue by rampitec** [llvm/llvm-project#39148]
|  |  |
| --- | --- |
| Bugzilla Link | [39801](https://llvm.org/bz39801) |
| Version | trunk |
| OS | All |
| Attachments | [Testcase](https://user-images.githubusercontent.com/8199369/143758383-5fb95250-5960-4454-b243-6eb6b80e3214.gz) |
| CC | @arsenm,@qcolombet |

## Extended Description 

Yet another "*** Couldn't join subrange" error. Reduced testcase attached.

**Comment by arsenm** [comment]
Guessing at the invocation, but everything I've tried so far works now
