### ISSUE TITLE
-Wfloat-conversion error message formatting error

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39167]
|  |  |
| --- | --- |
| Bugzilla Link | [39820](https://llvm.org/bz39820) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
Given code

[havia@villikani colld]$ cat k.c
int main(void)
{
        double a = 3.0;
        long b = 2;

        b /= a;

        return 0;
}

[havia@villikani colld]$ clang-8 -Weverything  k.c
k.c:6:4: warning: implicit conversion turns floating-point number into integer: 'long' to 'double' [-Wfloat-conversion]
        b /= a;
        ~~^~~~
1 warning generated.

  Shouldn't the end of the message be
  "'double' to 'long'" instead of "'long' to 'double'"?

clang-8 is localy compiled

[havia@villikani colld]$ clang-8 -v
clang version 8.0.0 (trunk 345705)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/llvm/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64

  The environment is

[havia@villikani colld]$ lsb_release 
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch

[havia@villikani colld]$ cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
[havia@villikani colld]$

**Comment by ilya-biryukov** [comment]
This no longer happens, was probably fixed before the Clang 8.0 release, see https://gcc.godbolt.org/z/Ez71ccdxq
