### ISSUE TITLE
clang crash with co_await in an auto-lambda in a function template

### ISSUE THREAD

**Issue by blastrock** [llvm/llvm-project#39166]
|  |  |
| --- | --- |
| Bugzilla Link | [39819](https://llvm.org/bz39819) |
| Version | trunk |
| OS | Linux |
| CC | @bartdesmet,@DougGregor,@zygoloid |

## Extended Description 
The following program makes clang crash:

template <typename b> void c(b) {
  [](auto client) { co_await client; };
}
int main() { c(0); }

Compiled with: clang++ -std=c++17 -fcoroutines-ts

Godbolt link: https://godbolt.org/z/bNEkkq

**Comment by Endilll** [comment]
Appears to be fixed in Clang 9: https://godbolt.org/z/95nc64Mhh
Doesn't reproduce on post-17 trunk in C++20 mode either: https://godbolt.org/z/GoErqqvhx
