### ISSUE TITLE
wrong binaries/headers for llvm-toolchain-xenial-7

### ISSUE THREAD

**Issue by andrewrk** [llvm/llvm-project#39170]
|  |  |
| --- | --- |
| Bugzilla Link | [39823](https://llvm.org/bz39823) |
| Version | unspecified |
| OS | All |

## Extended Description 
This build worked on Nov 24 and stopped working Nov 25.

2018-11-25T16:48:47.6020966Z + sudo sh -c echo "deb
http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main" >>
/etc/apt/sources.list
...
2018-11-25T16:53:30.7836235Z
/home/vsts/work/1/s/src/zig_llvm.cpp:686:1: error: static assertion
failed
2018-11-25T16:53:30.7837134Z
static_assert((Triple::OSType)ZigLLVM_LastOSType ==
Triple::LastOSType, "");
2018-11-25T16:53:30.7837409Z ^~~~~~~~~~~~~
full logs https://dev.azure.com/ziglang/zig/_build/results?buildId=229&view=logs

The version on apt.llvm.org has
    HermitCore, // HermitCore Unikernel/Multikernel
    LastOSType = HermitCore

But llvm 7.0.0 and 7.0.1 have
    AMDPAL,     // AMD PAL Runtime
    LastOSType = AMDPAL

Downstream issue https://github.com/ziglang/zig/issues/1788

**Comment by Endilll** [comment]
LLVM 7 is ancient by this point. Feel free to reopen if it still an issue for the latest release.
