### ISSUE TITLE
std::function isn't ABI compatible between C++03 and C++11

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39185]
|  |  |
| --- | --- |
| Bugzilla Link | [39838](https://llvm.org/bz39838) |
| Version | unspecified |
| OS | Linux |
| Attachments | [reproducer.sh.cpp](https://user-images.githubusercontent.com/60944935/143758400-21e6bd83-8102-4b4f-aab0-4f1ad1fdf043.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie,@mclow |

## Extended Description 

Our fallback implementation of std::function for C++03 isn't ABI compatible with the C++11 implementation; specifically the __base<Args>::operator()(Args...). In C++11 the virtual call operator accepts it's parameters by rvalue reference (to avoid additional copies), but the C++03 version accepts its arguments by value.

**Comment by philnik777** [comment]
It's expected that C++03 and C++11 are not ABI compatible AFAIK, so this isn't an issue.
