### ISSUE TITLE
[loop vectorize] failure to vectorize with llvm.invariant.start after instcombine

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39199]
|  |  |
| --- | --- |
| Bugzilla Link | [39852](https://llvm.org/bz39852) |
| Version | trunk |
| OS | All |
| Attachments | [invariant-start-vector-issue.ll](https://user-images.githubusercontent.com/60944935/143758406-dfa50589-e5d1-40ee-a765-fe0df725b9f8.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@hidekisaito |

## Extended Description 

I'm seeing an issue where adding !llvm.invariant.start metadata seems to prevents loop vectorization from occurring.

I'd like the attached example to vectorize, but it doesn't. To reproduce:

  opt -S -O3 invariant-start-vector-issue.ll -force-vector-width=4 -force-vector-interleave=1

and notice that the fmul is not vectorized. (invariant-start-vector-issue.ll is attached). If the llvm.invariant.start metadata is removed (or they are updated to all make %14 invariant, for example), then the loop is vectorized.

This is very surprising. I think most of us expect that adding additional information to the LLVM IR, like llvm.invariant.start, will help and not hinder optimization.

I know a little bit more about what is happening here. instcombine is creating a bitcast that seems to trip up the loop vectorizer.

 opt -instcombine -S invariant-start-vector-issue.ll

generates this snippet:

  %44 = bitcast double* %4 to i64*
  %45 = load i64, i64* %44, align 8, !tbaa !&#8203;2
  %46 = bitcast double* %31 to i64*
  store i64 %45, i64* %46, align 8, !tbaa !&#8203;2

I believe this snippet is tripping up the LoopVectorizer.

**Comment by fhahn** [comment]
This should get vectorized now: https://llvm.godbolt.org/z/7rxasncWb
