### ISSUE TITLE
Misformatting first of two identical blocks

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39197]
|  |  |
| --- | --- |
| Bugzilla Link | [39850](https://llvm.org/bz39850) |
| Version | 3.8 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
This problem first appears in clang-format 3.8.0 (based on my testing with https://zed0.co.uk/clang-format-configurator/) and persists through HEAD.  This is plain clang-format running in llvm style.

The following code:

```
{
  {
    { int a; }
  }
}

{
  {
    { int a; }
  }
}
```

now formats as

```
{{{int a;
}
}
}

{
  {
    { int a; }
  }
}
```

**Comment by rymiel** [comment]
Duplicate of https://github.com/llvm/llvm-project/issues/33891
