### ISSUE TITLE
JavaScript imports not grouped unless out of order

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39219]
|  |  |
| --- | --- |
| Bugzilla Link | [39872](https://llvm.org/bz39872) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
When JS imports are out of order and have no grouping, they are put in the correct order and empty lines are added in between external, different folder, and same folder groups. However, when they are in the right order but have no empty lines for grouping, no empty lines are added.

For example:

```
import {c} from './c';
import {a} from 'a';
import {b} from '../b';
```

becomes

```
import {a} from 'a';

import {b} from '../b';

import {c} from './c';
```

but

```
import {a} from 'a';
import {b} from '../b';
import {c} from './c';
```

doesn't change.

It seems like clang-format should format imports the same way regardless of how the programmer decided to do it. This also is causing problems for certain people using clang-format in combination with TypeScript's Organize Imports.

I wonder if this line (https://github.com/llvm-mirror/clang/blob/f3b7928366f63b51ffc97e74f8afcff497c57e8d/lib/Format/SortJavaScriptImports.cpp#L169) could just be removed.

**Comment by mydeveloperday** [comment]
Still produces with clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 7890afddec
ff01119f4d5e8825b43dd2c8361648)

```
import {a} from 'a';

import {b} from '../b'

import {c} from './c';
```

**Comment by PatriotRossii** [comment]
Not an issue 

> Still produces with clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git [7890afd](https://github.com/llvm/llvm-project/commit/7890afddecff01119f4d5e8825b43dd2c8361648) ff01119f4d5e8825b43dd2c8361648)
> 
> ```
> import {a} from 'a';
> 
> import {b} from '../b'
> 
> import {c} from './c';
> ```

```
import {a} from 'a';
import {b} from '../b';
import {c} from './c';
```

formats right with `clang-format version 15.0.0 (git@github.com:llvm/llvm-project.git 963192228b05e3bce86cf520e2bda5f069be9894)`

**Comment by JOE1994** [comment]
Not reproducible with llvm trunk (at commit `056d62be38c5db3d8332ac300c4ff29214126697`).

The code line which the original poster suggested removing from `clang/lib/Format/SortJavaScriptImports.cpp`
no longer exists in llvm trunk.
