### ISSUE TITLE
Enable 32 bit libraries in llvm 6.0.0 - issue

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39223]
|  |  |
| --- | --- |
| Bugzilla Link | [39876](https://llvm.org/bz39876) |
| Version | 6.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @TNorthover |

## Extended Description 
Hi,

We are using RedHat6 and RedHat7 machine.

As per our user request we are trying to build llvm - 6.0.0 by enabling 32 and 64 bit libraries.

Option that we are using in our build step is below:

********************************************************************************

*export CFLAGS="-O4 -m32 -m64"
*export LDFLAGS="-m32 -m64"

export CLANG_GCC=/opt/gcc/x86_64/6.1.0a/bin/gcc
cmake -DCMAKE_INSTALL_PREFIX=%{_prefix} -DCMAKE_BUILD_WITH_INSTALL_RPATH=1 \
            -DCMAKE_C_COMPILER=/opt/gcc/x86_64/6.1.0a/bin/gcc \
            -DCMAKE_CXX_COMPILER=/opt/gcc/x86_64/6.1.0a/bin/g++ \
            -DGCC_INSTALL_PREFIX=/opt/gcc/x86_64/6.1.0a/ \
            -DCMAKE_CXX_LINK_FLAGS="-L/opt/gcc/x86_64/6.1.0a/lib64" \
            -DCMAKE_INSTALL_RPATH=$ORIGIN/../lib:%{gccpath}/lib64\
            -DCMAKE_CROSSCOMPILING=True -DCMAKE_BUILD_TYPE=Release  \
            -Wno-dev  --enable-zlib -DCMAKE_BUILD_TYPE=Release \
            --enable-gold --enable-plugins \
            *-DLLVM_BUILD_32_BITS:BOOL=ON \
            --enable-targets \
            *-DLLVM_TARGETS_TO_BUILD="X86" \
            -DLLVM_ENABLE_ZLIB:BOOL=ON ..

make

make install 

NOTE: The line which highlighted with star (*) is the one added to enabled 32 and 64 bit.
*******************************************************************************

Below mentioned URL where we referred: 

https://stackoverflow.com/questions/1474243/build-32-bit-with-64-bit-llvm-gcc?rq=1
https://llvm.org/docs/CMake.html

We are not sure how to enable 32 and 64 bit libraries in llvm - 6.0.0.

Can anyone please help us here to get llvm 32 and 64 bit libraries.

Regards,
Abinaya

**Comment by arsenm** [comment]
Old build issue

Second build log said "error: CPU you selected does not support x86-64 instruction set" for reference
