### ISSUE TITLE
Create a clang-tidy check which looks for Objective-C type encodings that exceed a size limit

### ISSUE THREAD

**Issue by stephanemoore** [llvm/llvm-project#39235]
|  |  |
| --- | --- |
| Bugzilla Link | [39888](https://llvm.org/bz39888) |
| Version | unspecified |
| OS | All |
| CC | @nico,@seanm |

## Extended Description 
Objective-C type encodings can get undesirably large without careful attention, particularly in Objective-C++¹. It would be nice if a check was available to detect when Objective-C type encodings exceed some configurable threshold so that projects can easily identify when Objective-C type encodings become larger than they would like.

[1] https://medium.com/@dmaclach/objective-c-encoding-and-you-866624cc02de

**Comment by PiotrZSL** [comment]
Closing as not planed, if this issue is stil valid and such check is needed, please re-open.
