### ISSUE TITLE
raw string literals in C

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39238]
|  |  |
| --- | --- |
| Bugzilla Link | [39891](https://llvm.org/bz39891) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@zygoloid |

## Extended Description 
GCC supports, as an extension, raw string literals in C

For example, R"(^((.*[^[:space:]].*)|())$)"  is valid in C code (with GCC).

Would it be possible for Clang to also provide this as an extension.

Thank you

**Comment by sharkov63** [comment]
I believe this is a duplicate of #85703 and this has been completed in #88265. Maybe we can close this issue now? @AaronBallman

**Comment by AaronBallman** [comment]
Good catch, yes, this is now implemented.
