### ISSUE TITLE
Compilation errors for libclang svn 348328

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39241]
|  |  |
| --- | --- |
| Bugzilla Link | [39894](https://llvm.org/bz39894) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
svn info:  348328

[ 82%] Built target libclang_exports
[ 82%] Building CXX object tools/clang/tools/libclang/CMakeFiles/libclang.dir/CXType.cpp.o
/root/llvm/tools/clang/tools/libclang/CXType.cpp: In function 'CXCallingConv clang_getFunctionTypeCallingConv(CXType)':
/root/llvm/tools/clang/tools/libclang/CXType.cpp:645:30: error: 'CC_AArch64VectorCall' was not declared in this scope
 #define TCALLINGCONV(X) case CC_##X: return CXCallingConv_##X
                              ^
/root/llvm/tools/clang/tools/libclang/CXType.cpp:654:7: note: in expansion of macro 'TCALLINGCONV'
       TCALLINGCONV(AArch64VectorCall);
       ^
/root/llvm/tools/clang/tools/libclang/CXType.cpp:645:45: error: 'CXCallingConv_AArch64VectorCall' was not declared in this scope
 #define TCALLINGCONV(X) case CC_##X: return CXCallingConv_##X
                                             ^
/root/llvm/tools/clang/tools/libclang/CXType.cpp:654:7: note: in expansion of macro 'TCALLINGCONV'
       TCALLINGCONV(AArch64VectorCall);
       ^
tools/clang/tools/libclang/CMakeFiles/libclang.dir/build.make:494: recipe for target 'tools/clang/tools/libclang/CMakeFiles/libclang.dir/CXType.cpp.o' failed
make[2]: *** [tools/clang/tools/libclang/CMakeFiles/libclang.dir/CXType.cpp.o] Error 1
CMakeFiles/Makefile2:42294: recipe for target 'tools/clang/tools/libclang/CMakeFiles/libclang.dir/all' failed
make[1]: *** [tools/clang/tools/libclang/CMakeFiles/libclang.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
root@877aa7b58ab3:~/build#

**Comment by arsenm** [comment]
Old build failure
