### ISSUE TITLE
Change llvm call once check for PowerPC(ppc64le)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39259]
|  |  |
| --- | --- |
| Bugzilla Link | [39912](https://llvm.org/bz39912) |
| Version | trunk |
| OS | other |
| Attachments | [Patch to fix call_once errors on PowerPC64le](https://user-images.githubusercontent.com/60944935/143758417-c5fc0b8f-9fa3-48d8-ab15-794dc1e620d9.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@nemanjai |

## Extended Description 

This change is required to resolve the call_once related errors seen while building the Swift toolchain on PowerPC64LE.

**Comment by arsenm** [comment]
Linked patch was committed
