### ISSUE TITLE
make fails with libz3 4.8.4 (fix inside)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39312]
|  |  |
| --- | --- |
| Bugzilla Link | [39965](https://llvm.org/bz39965) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
[ 81%] Built target clangFormat
make[3]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libz3.so', needed by 'bin/clang-8'.  Stop.
CMakeFiles/Makefile2:25818: recipe for target 'tools/clang/tools/driver/CMakeFiles/clang.dir/all' failed
make[2]: *** [tools/clang/tools/driver/CMakeFiles/clang.dir/all] Error 2
CMakeFiles/Makefile2:25830: recipe for target 'tools/clang/tools/driver/CMakeFiles/clang.dir/rule' failed
make[1]: *** [tools/clang/tools/driver/CMakeFiles/clang.dir/rule] Error 2
Makefile:7726: recipe for target 'clang' failed
make: *** [clang] Error 2

I have libz3 installed from git (4.8.4). This error can be fixed with a simple symbolic link:

ln -s /usr/lib/x86_64-linux-gnu/libz3.so.4 /usr/lib/x86_64-linux-gnu/libz3.so

Maybe a possible enhancement?

**Comment by arsenm** [comment]
Old build issue
