### ISSUE TITLE
ubuntu 18.04 clang 7 has inconsistent dependencies (libncurses6 and libtinfo6)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39362]
|  |  |
| --- | --- |
| Bugzilla Link | [40015](https://llvm.org/bz40015) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @sylvestre |

## Extended Description 
Trying to install via apt (https://apt.llvm.org/) yields:
# sudo apt-get install clang-7 lldb-7 lld-7
...
The following packages have unmet dependencies:
 clang-7 : Depends: libllvm7 (>= 1:7~svn298832-1~) but it is not going to be installed
           Depends: libclang-common-7-dev (= 1:7.0.1~svn348686-1~exp1~20181211133748.6) but it is not going to be installed
           Depends: libclang1-7 (= 1:7.0.1~svn348686-1~exp1~20181211133748.6) but it is not going to be installed
           Recommends: llvm-7-dev but it is not going to be installed
 lld-7 : Depends: libllvm7 (= 1:7.0.1~svn348686-1~exp1~20181211133748.6) but it is not going to be installed
 lldb-7 : Depends: liblldb-7 (>= 1:7~svn298832-1~) but it is not going to be installed
          Depends: libllvm7 (= 1:7.0.1~svn348686-1~exp1~20181211133748.6) but it is not going to be installed
          Depends: libncurses6 (>= 6) but it is not installable
          Depends: libtinfo6 (>= 6) but it is not installable
          Depends: llvm-7-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Checking for libncurses6 reveals that there are no packages for 18.04 LTS, but there exist packages for 18.10.
Checking for libtinfo6 reveals that there exist libtinfo-dev, but I am unsure which one to include.

So do I need to upgrade to 18.10 or is there an easy fix?
Does it even make sense to include the apt, if the package is not easy installable?

For future use, different test scripts could be invoked via
apt-get --simulate install packageThatDoesntExist
(however that would require installed instances of every OS).
https://stackoverflow.com/questions/18008508/bash-how-to-check-if-packages-can-be-installed-if-apt-get-dpkg-is-running

Is there no tool for remote resolving package dependencies?
Or does Debian not check, if the dependencies are fullfilled?

**Comment by arsenm** [comment]
Old releases
