### ISSUE TITLE
[LoopVectorizer]  crash with -force-vector-width=2

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#39427]
|  |  |
| --- | --- |
| Bugzilla Link | [40080](https://llvm.org/bz40080) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced testcase](https://user-images.githubusercontent.com/55128014/143758468-aa46ccf0-f316-4d6b-8cdb-42356d465053.gz) |
| CC | @hfinkel,@hidekisaito,@RKSimon,@JonPsson,@uweigand |

## Extended Description 

This test case contains a loop with a load that gets a disabling (300000) cost, so normally this would not get vectorized.

Still, if vectorization is forced bad code is generated, which should probably be investigated:

opt -mtriple=s390x-unknown-linux -mcpu=z13 -o out.opt.ll tc_LV_width2.ll  -O3 -S -force-vector-width=2 -unroll-count=1

Instruction does not dominate all uses!
  %17 = phi <2 x double> [ %10, %pred.load.continue ], [ %16, %pred.load.if3 ]
  %2 = shufflevector <2 x double> %vector.recur, <2 x double> %17, <2 x i32> <i32 1, i32 2>

**Comment by fhahn** [comment]
I am unable to reproduce this on current `main` and I think this has been fixed. Please re-open with additional info if this still reproduces on your end.
