### ISSUE TITLE
Ignore new line in AlignConsecutiveDeclarations and AlignConsecutiveAssignments

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39462]
|  |  |
| --- | --- |
| Bugzilla Link | [40115](https://llvm.org/bz40115) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
It would be nice to have separate option to alter how AlignConsecutiveDeclarations and AlignConsecutiveAssignments treat empty lines.

Now clang-format with both options enabled formats following code like this:

```
virtual std::string Test1(const double** pBuf) = 0;
virtual bool        Test2()                    = 0;
// empty line or comment
virtual void                    Test3(T t) = 0;
virtual std::vector<td::string> Test4(T t) = 0;
```

Sometimes you want to separate groups of methods with empty line (or comment) but keep proper alignment across all declrations.

```
virtual std::string             Test1(const double** pBuf) = 0;
virtual bool                    Test2()                    = 0;
// empty line or coment
virtual void                    Test3(T t)                 = 0;
virtual std::vector<td::string> Test4(T t)                 = 0;
```

So in general format skiping empty lines (AlignConsecutiveLinesNumAllowed: n)

It would be very convenient to have it at least in class/struct declarations.

Can I modify clang-format to support this feature?

Thanks

**Comment by mydeveloperday** [comment]
Have you used the `AcrossEmptyLinesAndComments/AcrossEmptyLines` settings? That have been added

I'm going to close this issues as fixed, feel free to reopen it if you think it doesn't do what you expected
