### ISSUE TITLE
[x86] keep math/logic on vector unit to avoid insert/extract

### ISSUE THREAD

**Issue by rotateright** [llvm/llvm-project#39482]
|  |  |
| --- | --- |
| Bugzilla Link | [40135](https://llvm.org/bz40135) |
| Version | trunk |
| OS | All |
| CC | @topperc,@RKSimon,@rotateright |

## Extended Description 
We have a potential regression with shift lowering via rotates while trying to do scalarization in:
https://reviews.llvm.org/D55722

I don't think we're allowed to do anything with this in IR even if the pattern was appearing there:
```
define <4 x i32> @shiftamount_math(<4 x i32> %x, <4 x i32> %y) {
  %e = extractelement <4 x i32> %x, i32 0
  %s = sub i32 32, %e
  %i = insertelement <4 x i32> undef, i32 %s, i32 0
  %splat = shufflevector <4 x i32> %i, <4 x i32> undef, <4 x i32> zeroinitializer
  %shift = shl <4 x i32> %y, %splat
  ret <4 x i32> %shift
}

$ llc -o - vecshift.ll
...
	movd	%xmm0, %eax
	movl	$32, %ecx
	subl	%eax, %ecx
	movd	%ecx, %xmm0
	pslld	%xmm0, %xmm1
	movdqa	%xmm1, %xmm0
	retq
```

We would probably be better off loading the '32' as a splat constant and doing the 'sub' as a vector op:
```
	movdqa	LCPI1_0(%rip), %xmm2    ## xmm2 = [32,32,32,32]
	psubd	%xmm0, %xmm2
	pxor	%xmm0, %xmm0
	movss	%xmm2, %xmm0            ## xmm0 = xmm2[0],xmm0[1,2,3]
	pslld	%xmm0, %xmm1
	movdqa	%xmm1, %xmm0
```
It's ugly because of the x86 vector-shift-by-variable-but-not-really-a-vector-shift instruction that takes a 64-bit shift amount, but that beats transferring to scalar and back?

**Comment by RKSimon** [comment]
@rotateright Do we still have cases of this?

The rotation lowering issue from D55722 was fixed a while ago, but we can still create something similar from C quite easily:
```
#include <x86intrin.h>
__m128i PR39482(__m128i x, __m128i y) {
    return _mm_slli_epi32(x, 32 - _mm_cvtsi128_si32(y));
}

define <2 x i64> @PR39482(<2 x i64> %x, <2 x i64> %y){
entry:
  %0 = bitcast <2 x i64> %y to <4 x i32>
  %vecext.i = extractelement <4 x i32> %0, i64 0
  %sub = sub nsw i32 32, %vecext.i
  %1 = bitcast <2 x i64> %x to <4 x i32>
  %2 = tail call <4 x i32> @llvm.x86.sse2.pslli.d(<4 x i32> %1, i32 %sub)
  %3 = bitcast <4 x i32> %2 to <2 x i64>
  ret <2 x i64> %3
}
declare <4 x i32> @llvm.x86.sse2.pslli.d(<4 x i32>, i32)
```
Which would probably still need to be handled in DAG as InstCombine will only convert SSE shift intrinsics to shift ops if valuetracking can confirm its in range. Thoughts?

**Comment by rotateright** [comment]
Note: The fold itself could be generalized for any binop, but I don't know whether the scalar_to_vector pattern would show up for things other than the x86 shift node. It seems likely that we would already catch simpler cases of the general pattern where we're going from vector->scalar->vector.

**Comment by rotateright** [comment]
I made a draft of a DAGCombine fold, and it shows some other improvements, so I'll clean that up and post for review.

**Comment by rotateright** [comment]
Proposal:
https://reviews.llvm.org/D136713

**Comment by rotateright** [comment]
This should handle the case shown here:
54eeadcf442df91aed0fb724
There are some potential enhancements noted in the review and code comments, but I think we can close this report.
