### ISSUE TITLE
clang-format - The InlineOnly option for AllowShortFunctionsOnASingleLine doesn't work with NamespaceIndentation enabled

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39498]
|  |  |
| --- | --- |
| Bugzilla Link | [40151](https://llvm.org/bz40151) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The InlineOnly option for AllowShortFunctionsOnASingleLine does not work when the short functions are indented such as with NamespaceIndentation enabled.

**Original pre-formatted:**
```cpp
namespace test
{

struct Test
{
    void shortFunctionA()
    {
    }

    void shortFunctionB();
};

void Test::shortFunctionB()
{
}

void shortFunctionC()
{
}

} // namespace test
```
Formatted with NamespaceIndentation All:
```cpp
namespace test
{

    struct Test
    {
        void shortFunctionA() {}

        void shortFunctionB();
    };

    void Test::shortFunctionB() {}   // BAD

    void shortFunctionC() {}         // BAD

} // namespace test
```
Formatted with NamespaceIndentation None:
```cpp
namespace test
{

struct Test
{
    void shortFunctionA() {}

    void shortFunctionB();
};

void Test::shortFunctionB()         // GOOD
{
}

void shortFunctionC()               // GOOD
{
}

} // namespace test
```

**Comment by rymiel** [comment]
Duplicate of #24784. This issue was fixed by 7af11989be21df00ad6a510a831ea2425e48fa90 as part of clang-format 14
