### ISSUE TITLE
Many tools are not shipped in the Windows installer

### ISSUE THREAD

**Issue by glandium** [llvm/llvm-project#39499]
|  |  |
| --- | --- |
| Bugzilla Link | [40152](https://llvm.org/bz40152) |
| Version | unspecified |
| OS | Linux |
| CC | @zmodem,@rgal |

## Extended Description 
llvm-config is not there (bug 35791), but also tools such as llvm-readobj, llvm-symbolizer, llvm-pdbutil, llvm-profdata, llvm-dlltool, etc.

**Comment by zmodem** [comment]
The most recent discussion about including more tools in installer is in Issue #51192.
