### ISSUE TITLE
c11: Flexible array member in anonymous struct member of another struct.

### ISSUE THREAD

**Issue by ebdd6ebc-1612-4e9b-aee1-f7d2b6361d5f** [llvm/llvm-project#39515]
|  |  |
| --- | --- |
| Bugzilla Link | [40168](https://llvm.org/bz40168) |
| Version | trunk |
| OS | All |
| CC | @zygoloid |

## Extended Description 
Test case (prog.c):

  struct S
  {
    struct {
      int x;
      int a[];
    };
    int y;
  };

  int main()
  {
  }

Compilation command line:

  clang prog.c -Wall -Wextra -std=c11 -pedantic-errors

Observed behaviour:

  No errors outputed.

Expected behaviour:

  An error message.

  Structures with a flexible array member (in this case an anonymous structure
  are not allowed as a member of another struct (in this case the struct S).

  Another reason why an error message should be outputed is because the flexible
  array member of the anonymous struct member is also considered to be a
  member of the struct S, but it is not the last member of that struct.

Reference to the c17 standard (the bugfix version of c11 standard):

  6.7.2.1/3:

    "A structure or union shall not contain a member with incomplete or function
    type (hence, a structure shall not contain an instance of itself, but may
    contain a pointer to an instance of itself), except that
    the last member of a structure with more than one named member may have
    incomplete array type; such a structure (and any union containing, possibly
    recursively, a member that is such a structure) shall not be a member of a
    structure or an element of an array."

Note:

    GCC outputs the expected error message.

**Comment by AaronBallman** [comment]
This issue was fixed in Clang 11.0.0: https://godbolt.org/z/YbrYW8eKP
