### ISSUE TITLE
misc-new-delete-overloads has false positive for class-specific overloads

### ISSUE THREAD

**Issue by JonasToth** [llvm/llvm-project#39521]
|  |  |
| --- | --- |
| Bugzilla Link | [40174](https://llvm.org/bz40174) |
| Version | unspecified |
| OS | All |
| CC | @AaronBallman,@EugeneZelenko,@pr0g |

## Extended Description 
This Bug-Report is a follow up from cfe-users, original text:

---
Hi there,

Apologies if this is the wrong place to ask about this - if it is I'd be very grateful if you'd point me in the right direction :)

I'm seeing the clang-tidy warning 'misc-new-delete-overloads' when using the two parameter version of class member delete, however when using the single parameter version the warning goes away. 

class Type
{
    void* operator new(size_t) { ... }
    void operator delete(void*) { ... } // no warning
    void operator delete (void*, size_t) { ... } // warning
};

When using the second version I don't think this warning should be reported. Is this correct or am I missing something?

I've been double checking things here:

https://en.cppreference.com/w/cpp/memory/new/operator_new (Items 15, 16)
https://en.cppreference.com/w/cpp/memory/new/operator_delete (Items 17, 18 and 21, 22)

I'm using clang on Windows and using Clang Power Tools in Visual Studio to invoke clang-tidy.

Any info would be greatly appreciated!

Thank you for your time,

Tom
---

To me this confusion looks valid, but I did not create a minimal reproducer (yet).

**Comment by carlosgalvezp** [comment]
Example from OP no longer gives warnings on trunk.
