### ISSUE TITLE
readability-simplify-boolean-expr doesn't handle member variable conditions

### ISSUE THREAD

**Issue by LegalizeAdulthood** [llvm/llvm-project#39526]
|  |  |
| --- | --- |
| Bugzilla Link | [40179](https://llvm.org/bz40179) |
| Version | unspecified |
| OS | Linux |
| Depends On | llvm/llvm-project#27078  |
| CC | @EugeneZelenko,@LegalizeAdulthood |

## Extended Description 
+++ This bug was initially created as a clone of Bug #&#8203;26704 +++

Next situation was not detected by readability-simplify-boolean-expr check in LLDB source/Commands/CommandObjectWatchpointCommand.cpp:

if (m_script_language == eScriptLanguagePython || m_script_language == eScriptLanguageDefault)
{
    m_use_script_language = true;
}
else
{
    m_use_script_language = false;
}          

I think will be good idea to support code in braces for other situations handled by check, since braces may be enforced by readability-braces-around-statements. Braces should contain only single statement.

I use trunk version of Clang-tidy.

**Comment by LegalizeAdulthood** [comment]
@EugeneZelenko Is this still an issue?  Phabricator review [D56323](https://reviews.llvm.org/D56323) fixes the issue and was accepted and pushed and I see those changes in clang-tidy.

**Comment by EugeneZelenko** [comment]
Somehow, I could not close it. But I could confirm that this issue fixed: I run `main` build over LLVM code and Clang-tidy detected such issue in `llvm-project/lldb/source/Commands/CommandObjectThread.cpp`:

<pre>
if (run_mode == eAllThreads)
  m_stop_others = false;
else
  m_stop_others = true;
</pre>

**Comment by LegalizeAdulthood** [comment]
OK, I can close this, just wanted to make sure you don't see the issue anymore.
