### ISSUE TITLE
c11: Rejects well-formed program using . operator on _Atomic struct in unevalueded context.

### ISSUE THREAD

**Issue by ebdd6ebc-1612-4e9b-aee1-f7d2b6361d5f** [llvm/llvm-project#39520]
|  |  |
| --- | --- |
| Bugzilla Link | [40173](https://llvm.org/bz40173) |
| Version | trunk |
| OS | All |
| CC | @hfinkel,@zygoloid |

## Extended Description 
Test case (prog.c):

  int main(void)
  {
    _Atomic struct S { int x; } s;
    sizeof (s.x);
  }

Compilation command line:

  clang prog.c -Wall -Wextra -std=c11 -pedantic-errors

Observed behaviour:

  The following error message was outputed:

    prog.c:4:12: error: member reference base type '_Atomic(struct S)' is not a
      structure or union

    sizeof (s.x);        
            ~^~
    1 error generated.

Expected behaviour:

  No error message outputed.

Note:

  GCC accepts the program with no error message ourputed.

**Comment by AaronBallman** [comment]
This is a duplicate of https://github.com/llvm/llvm-project/issues/54563
