### ISSUE TITLE
readability-non-const-parameter check causes segfault

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39529]
|  |  |
| --- | --- |
| Bugzilla Link | [40182](https://llvm.org/bz40182) |
| Version | unspecified |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @EugeneZelenko |

## Extended Description 
I've encountered a segfault in clang-tidy when using the readability-non-const-parameter check in two cases.
In both cases, I've created the compile_commands.json using compiledb (https://github.com/nickdiego/compiledb). I'm using clang-tidy as part of this LLVM:
$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 7.0.1
  Optimized build.
  Default target: x86_64-apple-darwin18.2.0
  Host CPU: skylake

For reproduction, the segfault happens with the following two programs (sources are available on the specified websites:

-MAFFT 7.407 ( https://mafft.cbrc.jp/alignment/software/ )
  $ clang-tidy -checks=-*,readability-non-const-parameter partSalignmm.c
  Segmentation fault: 11

  partA__align() method causes the segfault here

-SweepFinder ( http://people.binf.ku.dk/rasmus/webpage/sf.html )
  $ clang-tidy -checks=-*,readability-non-const-parameter bfgs.c 
  Segmentation fault: 11

**Comment by carlosgalvezp** [comment]
Example code can no longer be downloaded, please re-open the bug with a self-contained example if the problem persists.
