### ISSUE TITLE
c11: Warning instead of error for missing type specifier.

### ISSUE THREAD

**Issue by ebdd6ebc-1612-4e9b-aee1-f7d2b6361d5f** [llvm/llvm-project#39532]
|  |  |
| --- | --- |
| Bugzilla Link | [40185](https://llvm.org/bz40185) |
| Version | trunk |
| OS | All |
| CC | @hfinkel,@zygoloid |

## Extended Description 
Test case (prog.c):

  int main()
  {
    typedef t;
  }

Compilation command line:

  clang prog.c -Wall -Wextra -std=c11 -pedantic-errors

Observed behaviour:

  The following warnings were outputed:

    prog.c:3:13: warning: type specifier missing, defaults to 'int'
    [-Wimplicit-int]
        typedef t;
        ~~~~~~~ ^
    prog.c:3:13: warning: unused typedef 't' [-Wunused-local-typedef]
    2 warnings generated.

Expected behaviour:

  The first warning should be an error instead since  -pedantic-errors  was
  used.

Note:

  GCC gives the expected error.

**Comment by AaronBallman** [comment]
This was fixed in Clang 15.0.0: https://gcc.godbolt.org/z/1bWdf4EaT
