### ISSUE TITLE
clang should warn about unsigned comparison with zero with -Wall -Wextra

### ISSUE THREAD

**Issue by tbodt** [llvm/llvm-project#39581]
|  |  |
| --- | --- |
| Bugzilla Link | [40234](https://llvm.org/bz40234) |
| Version | unspecified |
| OS | All |
| CC | @zygoloid |

## Extended Description 
Given this function:

int f(unsigned x) {
    return x < 0;
}

GCC gives the following warning with -Wextra:

<source>: In function 'int f(unsigned int)':
<source>:2:14: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
     return x < 0;
            ~~^~~

Clang doesn't warn at all, even with -Wall -Wextra. You need to specify -Wtautological-constant-in-range-compare, which is really hard to figure out.

**Comment by AaronBallman** [comment]
Duplicate of #58375
