### ISSUE TITLE
[ppc64] libomp-9.0.0 fails 125 tests

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39584]
|  |  |
| --- | --- |
| Bugzilla Link | [40237](https://llvm.org/bz40237) |
| Version | unspecified |
| OS | Linux |
| Attachments | [build.log](https://user-images.githubusercontent.com/60944935/143758529-2b986748-25d2-4e6a-8b2a-06e0b175f5f2.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

libomp-7.0.1 fails 92 tests on ppc64, of which 40 leave a coredump. Machine is a Talos II running Gentoo. (see downstream bugreport: https://bugs.gentoo.org/671904).

********************
Failing Tests (92):
    libomp :: api/kmp_aligned_malloc.c
    libomp :: api/kmp_set_defaults_lock_bug.c
    libomp :: api/omp_get_num_threads.c
    libomp :: api/omp_in_parallel.c
    libomp :: atomic/omp_atomic.c
    libomp :: barrier/omp_barrier.c
    libomp :: critical/omp_critical.c
    libomp :: env/kmp_set_dispatch_buf.c
    libomp :: env/omp_thread_limit.c
    libomp :: flush/omp_flush.c
    libomp :: lock/omp_init_lock.c
    libomp :: lock/omp_lock.c
    libomp :: lock/omp_nest_lock.c
    libomp :: lock/omp_test_lock.c
    libomp :: lock/omp_test_nest_lock.c
    libomp :: master/omp_master.c
    libomp :: master/omp_master_3.c
    libomp :: misc_bugs/cancellation_for_sections.c
    libomp :: misc_bugs/many-microtask-args.c
    libomp :: misc_bugs/omp_foreign_thread_team_reuse.c
    libomp :: misc_bugs/teams-no-par.c
    libomp :: misc_bugs/teams-reduction.c
    libomp :: ompt/misc/control_tool_no_ompt_support.c
    libomp :: parallel/omp_nested.c
    libomp :: parallel/omp_parallel_copyin.c
    libomp :: parallel/omp_parallel_default.c
    libomp :: parallel/omp_parallel_firstprivate.c
    libomp :: parallel/omp_parallel_if.c
    libomp :: parallel/omp_parallel_num_threads.c
    libomp :: parallel/omp_parallel_private.c
    libomp :: parallel/omp_parallel_reduction.c
    libomp :: parallel/omp_parallel_shared.c
    libomp :: tasking/bug_36720.c
    libomp :: tasking/bug_nested_proxy_task.c
    libomp :: tasking/bug_proxy_task_dep_waiting.c
    libomp :: tasking/kmp_task_reduction_nest.cpp
    libomp :: tasking/kmp_taskloop.c
    libomp :: tasking/nested_parallel_tasking.c
    libomp :: tasking/nested_task_creation.c
    libomp :: tasking/omp_task.c
    libomp :: tasking/omp_task_final.c
    libomp :: tasking/omp_task_firstprivate.c
    libomp :: tasking/omp_task_if.c
    libomp :: tasking/omp_task_imp_firstprivate.c
    libomp :: tasking/omp_task_private.c
    libomp :: tasking/omp_task_shared.c
    libomp :: tasking/omp_taskloop_grainsize.c
    libomp :: tasking/omp_taskloop_num_tasks.c
    libomp :: tasking/omp_taskwait.c
    libomp :: tasking/omp_taskyield.c
    libomp :: threadprivate/omp_threadprivate.c
    libomp :: threadprivate/omp_threadprivate_for.c
    libomp :: worksharing/for/bug_set_schedule_0.c
    libomp :: worksharing/for/kmp_doacross_check.c
    libomp :: worksharing/for/kmp_sch_simd_guided.c
    libomp :: worksharing/for/kmp_sch_simd_runtime_api.c
    libomp :: worksharing/for/kmp_sch_simd_runtime_guided.c
    libomp :: worksharing/for/kmp_sch_simd_runtime_static.c
    libomp :: worksharing/for/kmp_set_dispatch_buf.c
    libomp :: worksharing/for/omp_doacross.c
    libomp :: worksharing/for/omp_for_collapse.c
    libomp :: worksharing/for/omp_for_firstprivate.c
    libomp :: worksharing/for/omp_for_lastprivate.c
    libomp :: worksharing/for/omp_for_nowait.c
    libomp :: worksharing/for/omp_for_ordered.c
    libomp :: worksharing/for/omp_for_private.c
    libomp :: worksharing/for/omp_for_reduction.c
    libomp :: worksharing/for/omp_for_schedule_auto.c
    libomp :: worksharing/for/omp_for_schedule_dynamic.c
    libomp :: worksharing/for/omp_for_schedule_guided.c
    libomp :: worksharing/for/omp_for_schedule_runtime.c
    libomp :: worksharing/for/omp_for_schedule_static.c
    libomp :: worksharing/for/omp_for_schedule_static_3.c
    libomp :: worksharing/for/omp_parallel_for_firstprivate.c
    libomp :: worksharing/for/omp_parallel_for_if.c
    libomp :: worksharing/for/omp_parallel_for_lastprivate.c
    libomp :: worksharing/for/omp_parallel_for_ordered.c
    libomp :: worksharing/for/omp_parallel_for_private.c
    libomp :: worksharing/for/omp_parallel_for_reduction.c
    libomp :: worksharing/sections/omp_parallel_sections_firstprivate.c
    libomp :: worksharing/sections/omp_parallel_sections_lastprivate.c
    libomp :: worksharing/sections/omp_parallel_sections_private.c
    libomp :: worksharing/sections/omp_parallel_sections_reduction.c
    libomp :: worksharing/sections/omp_section_firstprivate.c
    libomp :: worksharing/sections/omp_section_lastprivate.c
    libomp :: worksharing/sections/omp_section_private.c
    libomp :: worksharing/sections/omp_sections_nowait.c
    libomp :: worksharing/sections/omp_sections_reduction.c
    libomp :: worksharing/single/omp_single.c
    libomp :: worksharing/single/omp_single_copyprivate.c
    libomp :: worksharing/single/omp_single_nowait.c
    libomp :: worksharing/single/omp_single_private.c

  Expected Passes    : 6
  Expected Failures  : 1
  Unsupported Tests  : 72
  Unexpected Failures: 92
FAILED: runtime/test/CMakeFiles/check-libomp 
cd /var/tmp/portage/sys-libs/libomp-7.0.1/work/openmp-7.0.1.src-abi_ppc_64.ppc64/runtime/test && /var/tmp/portage/sys-libs/libomp-7.0.1/temp/python2.7/bin/python /usr/bin/lit -vv -j 34 /var/tmp/portage/sys-libs/libomp-7.0.1/work/openmp-7.0.1.src-abi_ppc_64.ppc64/runtime/test
ninja: build stopped: subcommand failed.
[...]

Coredumps of:
api/Output/kmp_set_defaults_lock_bug.c.tmp
env/Output/kmp_set_dispatch_buf.c.tmp
misc_bugs/Output/cancellation_for_sections.c.tmp
misc_bugs/Output/teams-reduction.c.tmp
api/Output/kmp_aligned_malloc.c.tmp
ompt/misc/Output/control_tool_no_ompt_support.c.tmp
lock/Output/omp_test_lock.c.tmp
misc_bugs/Output/many-microtask-args.c.tmp
barrier/Output/omp_barrier.c.tmp
critical/Output/omp_critical.c.tmp
api/Output/omp_get_num_threads.c.tmp
api/Output/omp_in_parallel.c.tmp
lock/Output/omp_init_lock.c.tmp
lock/Output/omp_nest_lock.c.tmp
env/Output/omp_thread_limit.c.tmp
misc_bugs/Output/teams-no-par.c.tmp
tasking/Output/omp_task_imp_firstprivate.c.tmp
tasking/Output/omp_task_private.c.tmp
tasking/Output/omp_task_shared.c.tmp
tasking/Output/omp_taskloop_grainsize.c.tmp
tasking/Output/kmp_task_reduction_nest.cpp.tmp
threadprivate/Output/omp_threadprivate_for.c.tmp
tasking/Output/omp_taskyield.c.tmp
worksharing/for/Output/kmp_doacross_check.c.tmp
worksharing/for/Output/omp_for_schedule_dynamic.c.tmp
tasking/Output/omp_taskloop_num_tasks.c.tmp
threadprivate/Output/omp_threadprivate.c.tmp
worksharing/for/Output/kmp_sch_simd_runtime_api.c.tmp
worksharing/for/Output/bug_set_schedule_0.c.tmp
tasking/Output/omp_taskwait.c.tmp
worksharing/for/Output/omp_doacross.c.tmp
worksharing/for/Output/kmp_sch_simd_guided.c.tmp
worksharing/for/Output/omp_for_reduction.c.tmp
worksharing/single/Output/omp_single_nowait.c.tmp
worksharing/sections/Output/omp_section_private.c.tmp
worksharing/sections/Output/omp_sections_nowait.c.tmp
worksharing/for/Output/omp_parallel_for_reduction.c.tmp
worksharing/sections/Output/omp_parallel_sections_reducti>
worksharing/single/Output/omp_single_private.c.tmp
worksharing/sections/Output/omp_sections_reduction.c.tmp
ntime/test/worksharing/sections/Output/omp_sections_reduction.c.tmp

**Comment by arsenm** [comment]
Old build issue and linked gentoo issue is closed

**Comment by EugeneZelenko** [comment]
@arsenm: Please don't forget to add `obsolete` labels to such issues when closing them.
