### ISSUE TITLE
Fix flaky tests on NetBSD

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39582]
|  |  |
| --- | --- |
| Bugzilla Link | [40235](https://llvm.org/bz40235) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
According to the discussion in D56064, the NetBSD bots often fail due to flaky tests in libc++.

This bug is used to report any test which makes the NetBSD bots flake (or for other flaky tests in general). I will fix flaky tests as they come in. I plan to close this bug once NetBSD bot failures are no longer occurring regularly.

When reporting a flaky test, please provide a link to the output of the test failure.

**Comment by ldionne** [comment]
We've unflaked these tests since then. We also don't have CI running on NetBSD (anymore?).
