### ISSUE TITLE
c11: Rejects valid program having cast operator with _Atomic int type

### ISSUE THREAD

**Issue by ebdd6ebc-1612-4e9b-aee1-f7d2b6361d5f** [llvm/llvm-project#39596]
|  |  |
| --- | --- |
| Bugzilla Link | [40249](https://llvm.org/bz40249) |
| Version | trunk |
| OS | All |
| CC | @hfinkel,@zygoloid |

## Extended Description 
Test case (prog.c):

  int main()
  {
    (_Atomic int)0;
  }

Compilation command line:

  clang prog.c -Wall -Wextra -std=c11 -pedantic-errors 

Observed beaviour:

  The following error message was outputed:

     error: used type '_Atomic(int)' where arithmetic or pointer type is
            required

Expected behaviour:

  No error message outputed.

  The program is well-formed.

  _Atomic  qualification of the scalar type  int  is allowed here.

  See 6.5.4/2:

  "Unless  the  type  name  specifies  a  void  type,  the  type  name  shall
   specify  atomic,  qualified,  or unqualified scalar type, and the operand
   shall have scalar type."

Note:

  GCC accepts the program without outputing any error message.

**Comment by AaronBallman** [comment]
I can confirm that this issue still happens with trunk.
