### ISSUE TITLE
clang will crash with -fexceptions -fsjlj-exceptions and -fno-rtti

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39616]
|  |  |
| --- | --- |
| Bugzilla Link | [40269](https://llvm.org/bz40269) |
| Version | 6.0 |
| OS | Windows NT |
| Attachments | [CLang binary dump](https://user-images.githubusercontent.com/60944935/143758540-6d8c644b-e9bc-44fb-8614-4a3719816f54.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 

CLang 6.0.0 crashes when using -fexceptions, -fsjlj-exceptions and -fno-rtti. 

Please find attached the clang's binary dump. Other text files will follow attached to this msg. 

------------------------------------------------------------------
The listing spit by clang in the terminal
------------------------------------------------------------------
Wrote crash dump file "C:\Users\hilton\AppData\Local\Temp\clang++.exe-26f585.dmp"
0x00007FF624992FA3 (0x000000261178A780 0x000000261178A780 0x0000000000000000 0x0000132D5C7CBABE)
0x00007FF624A9C82C (0x00000135D37831B0 0x0000000000000008 0x0000000000800000 0x000000261178AA60)
0x00007FF624A9C1DA (0x00000135D3783020 0x0000000000000008 0x000000261178AA58 0x000000261178AC08)
0x00007FF624AE3B4F (0x0000132D5C7CB88E 0x00000135D189FB80 0x00000135D3784840 0x00000135D37864B0)
0x00007FF624AEC013 (0x00000135D3786470 0x00007FF624AA28B8 0x000000000000026B 0x00007FF625DEC80C)
0x00007FF624A689FE (0x00000135D3786470 0x0000000000000016 0x000000261178ADF0 0x00007FF625D722B3)
0x00007FF624A6932E (0x00007FF60000066A 0x00000135D1887980 0x00000135D18858E8 0x0000000000000000)
0x00007FF6249305B1 (0x0000000000000000 0x0000000000000000 0x0000132D5C7CDDAE 0x00000135D189FB80)
0x00007FF62492B53D (0x00000135D1917FF0 0x00007FF6248E98E6 0x000000261178C318 0x00007FF6253DEF2F)
0x00007FF6249325AB (0x0000132D5C7CCAAE 0x00000135D191D8E0 0x000000261178D880 0x000000261178D880)
0x00007FF62610AF6F (0x00000135D191D8D0 0x0000000000000000 0x00000135D1917FF0 0x00000135D3786470)
0x00007FF6261091A9 (0x0000000800000000 0x00007FF626EE9169 0x000000000000001D 0x000000000000000B)
0x00007FF625365E73 (0x0000000000000000 0x0000000000000000 0x00007FF62672F11C 0x00000135D18382A0)
0x00007FF624D0BEBD (0x000000000000000E 0x0000013500000015 0x00007FF626EE91CC 0x000000000000000F)
0x00007FF624CD0657 (0x0000013500000001 0x00000135D187FF30 0x00000135D1880358 0x00000135D1880358)
0x00007FF624D56FF6 (0x0000000000000001 0x0000000000000382 0x0000000000000141 0x00000135D183B2D0)
0x00007FF623517277 (0x00007FFFB587C570 0x00000135D1859840 0x000000000000000E 0x00000000000003C8)
0x00007FF62351461B (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF62612DCC8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFFB6FC7E94 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFFB86FA251 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
clang++.exe: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
clang++.exe: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang++.exe: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++.exe: note: diagnostic msg: C:\Users\hilton\AppData\Local\Temp\hiwrld-19d0c0.cpp
clang++.exe: note: diagnostic msg: C:\Users\hilton\AppData\Local\Temp\hiwrld-19d0c0.sh
clang++.exe: note: diagnostic msg:

********************

Erro 1 na compilacao de: c:\Users\Hilton\svn\TotvsTecX-new\tools\advpl2cpp\obj\hiwrld.prw.cpp

------------------------------------------------------------------
------------------------------------------------------------------
hiwrld-19d0c0.sh
------------------------------------------------------------------
# Crash reproducer for clang version 6.0.0 (tags/RELEASE_600/final)
# Driver args: "--driver-mode=g++" "-emit-llvm" "-x" "c++" "-fdollars-in-identifiers" "-fno-rtti" "-Wunreachable-code" "-Wunused-macros" "-Wunused-parameter" "-fms-volatile" "-fms-compatibility-version=19.0.24210" "-fexceptions" "-fsjlj-exceptions" "-D" "_ADVPL_JITTER_INTERNAL" "-D" "WIN32" "-D" "WIN64" "-D" "ADVTEC9_BRANCH17" "-D" "_ADVPL_64" "-D" "_WIN64" "-D" "_ADVPL_WIN64" "-D" "_ADVPL_NOWEBENGINE" "-D" "_LIBAPPRE_" "-D" "_ADVPL_BD_CTREE" "-D" "_ADVPL_BD_ADS" "-D" "USING_AWS_SQS_" "-D" "USING_TMI_USERS" "-D" "GENERATE_ADVPL2CPP" "-D" "_ADVPL_JITTER" "-D" "BUILD_MAKEDLL" "-D" "ADVPL2CPP_EXPORTS" "-D" "QT_NODLL" "-D" "_DEBUG" "-D" "_CRT_SECURE_NO_DEPRECATE" "-I" "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include" "-I" "c:/Users/Hilton/svn/llvm/include" "-I" "c:/Users/Hilton/svn/llvm/include/llvm/IR" "-I" "c:/Users/Hilton/svn/llvm/tools/clang/include" "-I" "c:/Users/Hilton/svn/llvm/_BUILD_DIR/VS15_64b/include" "-I" "c:/Users/Hilton/svn/llvm/_BUILD_DIR/VS15_64b/tools/clang/include" "-I" "c:/Users/Hilton/svn/TotvsTecX-new/tools/advpl2cpp/../advpl2cpp/include" "-I" "c:/Users/Hilton/svn/TotvsTecX-new/tools/advpl2cpp/../advpl2cpp/obj" "-I" "c:/Users/Hilton/svn/TotvsTecX-new/tools/advpl2cpp/../../advpl" "-I" "c:/Users/Hilton/svn/TotvsTecX-new/tools/advpl2cpp/../../lib_base" "-I" "c:/Users/Hilton/svn/TotvsTecX-new/tools/advpl2cpp/../../lib_comm" "-I" "c:/Users/Hilton/svn/TotvsTecX-new/tools/advpl2cpp/../../apwinnt" "-c" "c:\\Users\\Hilton\\svn\\TotvsTecX-new\\tools\\advpl2cpp\\obj\\hiwrld.prw.cpp" "-o" "obj\\hiwrld.prw.cpp.bc" "-lstdc++"
# Original command:  "C:\\Program Files\\LLVM\\bin\\clang++.exe" "-cc1" "-triple" "x86_64-pc-windows-msvc19.0.24210" "-emit-llvm-bc" "-emit-llvm-uselists" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "hiwrld.prw.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-fmath-errno" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-dwarf-column-info" "-debugger-tuning=gdb" "-momit-leaf-frame-pointer" "-coverage-notes-file" "C:\\Users\\hilton\\svn\\TotvsTecX-new\\tools\\advpl_jitter\\scripts\\obj\\hiwrld.prw.cpp.gcno" "-resource-dir" "C:\\Program Files\\LLVM\\lib\\clang\\6.0.0" "-D" "_ADVPL_JITTER_INTERNAL" "-D" "WIN32" "-D" "WIN64" "-D" "ADVTEC9_BRANCH17" "-D" "_ADVPL_64" "-D" "_WIN64" "-D" "_ADVPL_WIN64" "-D" "_ADVPL_NOWEBENGINE" "-D" "_LIBAPPRE_" "-D" "_ADVPL_BD_CTREE" "-D" "_ADVPL_BD_ADS" "-D" "USING_AWS_SQS_" "-D" "USING_TMI_USERS" "-D" "GENERATE_ADVPL2CPP" "-D" "_ADVPL_JITTER" "-D" "BUILD_MAKEDLL" "-D" "ADVPL2CPP_EXPORTS" "-D" "QT_NODLL" "-D" "_DEBUG" "-D" "_CRT_SECURE_NO_DEPRECATE" "-I" "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include" "-I" "c:/Users/Hilton/svn/llvm/include" "-I" "c:/Users/Hilton/svn/llvm/include/llvm/IR" "-I" "c:/Users/Hilton/svn/llvm/tools/clang/include" "-I" "c:/Users/Hilton/svn/llvm/_BUILD_DIR/VS15_64b/include" "-I" "c:/Users/Hilton/svn/llvm/_BUILD_DIR/VS15_64b/tools/clang/include" "-I" "c:/Users/Hilton/svn/TotvsTecX-new/tools/advpl2cpp/../advpl2cpp/include" "-I" "c:/Users/Hilton/svn/TotvsTecX-new/tools/advpl2cpp/../advpl2cpp/obj" "-I" "c:/Users/Hilton/svn/TotvsTecX-new/tools/advpl2cpp/../../advpl" "-I" "c:/Users/Hilton/svn/TotvsTecX-new/tools/advpl2cpp/../../lib_base" "-I" "c:/Users/Hilton/svn/TotvsTecX-new/tools/advpl2cpp/../../lib_comm" "-I" "c:/Users/Hilton/svn/TotvsTecX-new/tools/advpl2cpp/../../apwinnt" "-internal-isystem" "C:\\Program Files\\LLVM\\lib\\clang\\6.0.0\\include" "-internal-isystem" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\include" "-internal-isystem" "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.17763.0\\ucrt" "-internal-isystem" "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\shared" "-internal-isystem" "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\um" "-internal-isystem" "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\winrt" "-Wunreachable-code" "-Wunused-macros" "-Wunused-parameter" "-fdeprecated-macro" "-fdebug-compilation-dir" "C:\\Users\\hilton\\svn\\TotvsTecX-new\\tools\\advpl_jitter\\scripts" "-ferror-limit" "19" "-fmessage-length" "170" "-fno-rtti" "-fno-use-cxa-atexit" "-fms-extensions" "-fms-compatibility" "-fms-compatibility-version=19.0.24210" "-std=c++14" "-fdelayed-template-parsing" "-fobjc-runtime=gcc" "-fcxx-exceptions" "-fexceptions" "-fsjlj-exceptions" "-fdiagnostics-show-option" "-fcolor-diagnostics" "-fdollars-in-identifiers" "-o" "obj\\hiwrld.prw.cpp.bc" "-x" "c++" "c:\\Users\\Hilton\\svn\\TotvsTecX-new\\tools\\advpl2cpp\\obj\\hiwrld.prw.cpp"
 "C:\\Program Files\\LLVM\\bin\\clang++.exe" "-cc1" "-triple" "x86_64-pc-windows-msvc19.0.24210" "-emit-llvm-bc" "-emit-llvm-uselists" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "hiwrld.prw.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-fmath-errno" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-dwarf-column-info" "-debugger-tuning=gdb" "-momit-leaf-frame-pointer" "-coverage-notes-file" "C:\\Users\\hilton\\svn\\TotvsTecX-new\\tools\\advpl_jitter\\scripts\\obj\\hiwrld.prw.cpp.gcno" "-D" "_ADVPL_JITTER_INTERNAL" "-D" "WIN32" "-D" "WIN64" "-D" "ADVTEC9_BRANCH17" "-D" "_ADVPL_64" "-D" "_WIN64" "-D" "_ADVPL_WIN64" "-D" "_ADVPL_NOWEBENGINE" "-D" "_LIBAPPRE_" "-D" "_ADVPL_BD_CTREE" "-D" "_ADVPL_BD_ADS" "-D" "USING_AWS_SQS_" "-D" "USING_TMI_USERS" "-D" "GENERATE_ADVPL2CPP" "-D" "_ADVPL_JITTER" "-D" "BUILD_MAKEDLL" "-D" "ADVPL2CPP_EXPORTS" "-D" "QT_NODLL" "-D" "_DEBUG" "-D" "_CRT_SECURE_NO_DEPRECATE" "-Wunreachable-code" "-Wunused-macros" "-Wunused-parameter" "-fdeprecated-macro" "-ferror-limit" "19" "-fmessage-length" "170" "-fno-rtti" "-fno-use-cxa-atexit" "-fms-extensions" "-fms-compatibility" "-fms-compatibility-version=19.0.24210" "-std=c++14" "-fdelayed-template-parsing" "-fobjc-runtime=gcc" "-fcxx-exceptions" "-fexceptions" "-fsjlj-exceptions" "-fdiagnostics-show-option" "-fcolor-diagnostics" "-fdollars-in-identifiers" "-x" "c++" "hiwrld-19d0c0.cpp"

**Comment by Endilll** [comment]
Unfortunately, we can't do much without preprocessed source.
Feel free to reopen if you have additional information.
