### ISSUE TITLE
git-llvm: --force-interactive option requires svn 1.8 or newer

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#39655]
|  |  |
| --- | --- |
| Bugzilla Link | [40308](https://llvm.org/bz40308) |
| Version | trunk |
| OS | Linux |
| CC | @gregbedwell,@MaskRay |

## Extended Description 
git-llvm fails to run with svn 1.7.14 with this error message:

svn: invalid option: --force-interactive

This option was introduced in svn 1.8: See https://sourceforge.net/p/svnbook/tickets/270/

Based on this commit message: http://svn.apache.org/viewvc?view=revision&revision=1424037, it appears that --force-interactive was the default behavior prior to svn 1.8.  However, I tried removing the option from my script locally and the script appeared to run fine, but nothing was actually committed.

**Comment by arsenm** [comment]
svn is no more
