### ISSUE TITLE
Clang 7.0.1 crashes on AArch64

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39708]
|  |  |
| --- | --- |
| Bugzilla Link | [40361](https://llvm.org/bz40361) |
| Version | 7.0 |
| OS | FreeBSD |
| Reporter | LLVM Bugzilla Contributor |
| CC | @emaste,@kbeyls,@zygoloid |

## Extended Description 
After upgrading to Clang 7.0.1, it crashed when compiling various
programs on AArch64. They were all terminated at the same place:

# lldb /usr/bin/clang -c /usr/obj/usr/src/arm64.aarch64/lib/libc/cc.core
Core file '/usr/obj/usr/src/arm64.aarch64/lib/libc/cc.core' (aarch64) was loaded.
(lldb) bt
* thread #&#8203;1, name = 'cc', stop reason = signal SIGSEGV
  * frame #&#8203;0: 0x0000000002db02b8 clang`::LookupBucketFor() at StringMap.cpp:79
    frame #&#8203;1: 0x0000000003aeaa30 clang`::try_emplace<llvm::cl::Option *>() at StringMap.h:396
    frame #&#8203;2: 0x0000000003aeabac clang`::addOption() [inlined] insert at StringMap.h:387
    frame #&#8203;3: 0x0000000003aeaba8 clang`::addOption() at CommandLine.cpp:151
    frame #&#8203;4: 0x0000000003ae1c00 clang`::addArgument() [inlined] addOption at CommandLine.cpp:194
    frame #&#8203;5: 0x0000000003ae1b44 clang`::addArgument() at CommandLine.cpp:357
    frame #&#8203;6: 0x000000000305207c clang at CommandLine.h:1342
    frame #&#8203;7: 0x0000000003052078 clang at CommandLine.h:1365
    frame #&#8203;8: 0x0000000003051fcc clang at CorrelatedValuePropagation.cpp:67
    frame #&#8203;9: 0x0000000003051fcc clang at CorrelatedValuePropagation.cpp:0
    frame #&#8203;10: 0x00000000011d01a0 clang`handle_static_init(argc=138, argv=0x0000ffffffffcfd8, env=0x0000ffffffffd430) at ignore_init.c:124
    frame #&#8203;11: 0x00000000011d00a8 clang`__start(argc=138, argv=0x0000ffffffffcfd8, env=0x0000ffffffffd430, cleanup=<unavailable>) at crt1.c:83

**Comment by Endilll** [comment]
Can't reproduce crashes from both linked FreeBSD issues using Clang 6 through 8 with assertions enabled.
