### ISSUE TITLE
ICE/Segfault when parsing incorrect template arguments of nested classes, OS X only?

### ISSUE THREAD

**Issue by mrks** [llvm/llvm-project#39720]
|  |  |
| --- | --- |
| Bugzilla Link | [40374](https://llvm.org/bz40374) |
| Version | 7.0 |
| OS | MacOS X |
| Attachments | [Crash info](https://user-images.githubusercontent.com/92601669/143758584-330de4e8-c59b-485d-844c-7445563f36bd.gz) |
| CC | @zygoloid |

## Extended Description 

The following code leads to an ICE:

#include <type_traits>
class JoinHash {};
template <typename LeftType, typename = std::enable_if_t<bool>
class JoinHash::JoinHashImpl {};

Error:

1.	clangice.cpp:6:30: current parser token '{'
0  clang-7                  0x000000010a9e2356 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 37
1  clang-7                  0x000000010a9e274e SignalHandler(int) + 192
2  libsystem_platform.dylib 0x00007fff6e56ab3d _sigtramp + 29
3  libsystem_platform.dylib 0x00007ffee61e1597 _sigtramp + 2009557623
4  clang-7                  0x000000010bc0dbf6 clang::TypeLoc::getBeginLoc() const + 118
5  clang-7                  0x000000010bbd3437 clang::NestedNameSpecifierLoc::getLocalSourceRange() const + 143
6  clang-7                  0x000000010b62698d clang::CXXScopeSpec::getLastQualifierNameLoc() const + 37
[...]

Interestingly, this happens *after* the correct error message is printed. Also, I am unable to reproduce it on Godbolt or my Linux machines.

clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
(Installed via brew)

**Comment by Endilll** [comment]
Can't reproduce using Clang 6 through 9 with assertions enabled.
