### ISSUE TITLE
Fix the pointer register class used by LDWRdPtr from PTRREGS to PTRDISPREGS

### ISSUE THREAD

**Issue by dylanmckay** [llvm/llvm-project#39734]
|  |  |
| --- | --- |
| Bugzilla Link | [40388](https://llvm.org/bz40388) |
| Version | trunk |
| OS | Linux |
| Attachments | [a patch to update the register class](https://user-images.githubusercontent.com/7722159/143758587-fa783a28-c8a3-4fb1-a281-0841b05ffdc4.gz) |
| CC | @tclin914 |

## Extended Description 
LDWRdPtr expands to LDDRdPtrQ, which requires a PTRDISPREGS class. This means that if the X register is ever allocated, the LDDRdPtrQ will be an illegal instruction and will hit an assertion error at machine code generation time.

**Comment by benshi001** [comment]
avr backend

**Comment by benshi001** [comment]
fixed in https://reviews.llvm.org/rG20b14dacbbbf9fedc90c732b6dde9361b7b2283c

**Comment by benshi001** [comment]
fixed in https://reviews.llvm.org/rG20b14dacbbbf9fedc90c732b6dde9361b7b2283c
