### ISSUE TITLE
Parser Crash

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39746]
|  |  |
| --- | --- |
| Bugzilla Link | [40400](https://llvm.org/bz40400) |
| Version | 7.0 |
| OS | other |
| Attachments | [parser stack dump](https://user-images.githubusercontent.com/60944935/143758590-2b47c3ae-2566-493b-9d92-c31165756113.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @fhahn,@zygoloid |

## Extended Description 
I got a parser crash while compiling fairly large c++ program (~7000 lines).

I'm attaching stack dump, and generated docs. This occurred on CentOS release 6.10.

Best regards,

John Parke

**Comment by Endilll** [comment]
Author has never got back to us with source code.
