### ISSUE TITLE
Impossible to say the number of empty line spacing, always 1

### ISSUE THREAD

**Issue by d75947c2-9580-4fe3-87b3-3a6ed64cecb3** [llvm/llvm-project#39750]
|  |  |
| --- | --- |
| Bugzilla Link | [40404](https://llvm.org/bz40404) |
| Version | unspecified |
| OS | All |

## Extended Description 
An option should be there to set the number of empty line for spacing, it's always 1.

**Comment by mydeveloperday** [comment]
I'm unclear what this is? can you explain a little more if still interested otherwise we'll need to close this.

**Comment by PlasmaMichael** [comment]
We can close it because the empty line spacing of 1 is in all cases the best.
It would give an option to have a different style but better to force for the best and more compact.
