### ISSUE TITLE
clang (Windows) crash with inherited constructors and non-trivial destructors

### ISSUE THREAD

**Issue by CaseyCarter** [llvm/llvm-project#39815]
|  |  |
| --- | --- |
| Bugzilla Link | [40469](https://llvm.org/bz40469) |
| Version | 7.0 |
| OS | Windows NT |
| Attachments | [Repro](https://user-images.githubusercontent.com/456873/143758615-e071fa44-2f00-44a7-8d58-8c99383e7e6a.gz), [Preprocessed sources](https://user-images.githubusercontent.com/456873/143758616-df175861-d0f0-4fa0-a925-64c70016c2ca.gz), [run script](https://user-images.githubusercontent.com/456873/143758617-9a2c40fc-3cd3-4cee-ad72-35d909c77b90.gz), [crash dump](https://user-images.githubusercontent.com/456873/143758618-0fe67be6-1634-4f4a-a4e5-b092bb54c7e6.gz) |
| CC | @DougGregor,@zygoloid |

## Extended Description 

"clang repro.cpp" crashes compiling this correct TU (attached as repro.cpp):

  struct Iterator_base12 {
    ~Iterator_base12() noexcept {}
  };

  struct mixin {
    mixin(Iterator_base12) {}
    ~mixin() noexcept {}
  };

  struct basic_iterator : mixin {
    using mixin::mixin;
  };

  void f(basic_iterator) {}

  int main() {
    f(basic_iterator{Iterator_base12{}});
  }

Which impacts range-v3 support for clang on Windows (this is https://github.com/ericniebler/range-v3/issues/890).

**Comment by Endilll** [comment]
Appears to be fixed in Clang 8: https://godbolt.org/z/453r66z3v
