### ISSUE TITLE
clang crashes on valid code at -O3 with debugging enabled: fatal error: error in backend: Broken function found, compilation aborted!

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#39825]
|  |  |
| --- | --- |
| Bugzilla Link | [40479](https://llvm.org/bz40479) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Tested with trunk revision 352264, and looks like a recent regression. 

$ cltrunk -v
clang version 9.0.0 (http://llvm.org/git/clang.git 8a558a52a96fc5411834e6e015219513a9986bdc) (http://llvm.org/git/llvm.git 6033f8c97abfccb3d9367694f62570ea980ccd81)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ 
$ cltrunk -O3 -g small.c
llvm.dbg.label intrinsic requires a !dbg attachment
  call void @&#8203;llvm.dbg.label(metadata !&#8203;26) #&#8203;3
label %L1.outer.us.preheader.i.split.us
i32 ()* @&#8203;main
llvm.dbg.label intrinsic requires a !dbg attachment
  call void @&#8203;llvm.dbg.label(metadata !&#8203;27) #&#8203;3
label %L1.outer.us.preheader.i.split.us
i32 ()* @&#8203;main
llvm.dbg.label intrinsic requires a !dbg attachment
  call void @&#8203;llvm.dbg.label(metadata !&#8203;26) #&#8203;3
label %L1.outer.us.preheader.i.split.us
i32 ()* @&#8203;main
llvm.dbg.label intrinsic requires a !dbg attachment
  call void @&#8203;llvm.dbg.label(metadata !&#8203;27) #&#8203;3
label %L1.outer.us.preheader.i.split.us
i32 ()* @&#8203;main
in function main
fatal error: error in backend: Broken function found, compilation aborted!
clang-8: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 9.0.0 (http://llvm.org/git/clang.git 8a558a52a96fc5411834e6e015219513a9986bdc) (http://llvm.org/git/llvm.git 6033f8c97abfccb3d9367694f62570ea980ccd81)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/su/bin
clang-8: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-8: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-8: note: diagnostic msg: /tmp/small-bc8f7f.c
clang-8: note: diagnostic msg: /tmp/small-bc8f7f.sh
clang-8: note: diagnostic msg: 

********************
$ 

------------------------------------

int printf (const char *, ...);

struct
{
  int a:10;
} b;

int c, d;

void e ()
{
  int f, g;
  short h;
  g = c;
  h = f = ~g;
L1:
  b.a = (~g || d) - 1;
  if (f)
    goto L1;
L2:
  if (h)
    {
      g = h;
      goto L1;
    }
  if (c)
    {
      printf ("%d\n", c);
      goto L2;
    }
}

int main ()
{
  if (c)
    e ();
  return 0;
}

**Comment by fhahn** [comment]
I am unable to reproduce this on current `main`, so this likely has been fixed. Please re-open with more info if this still reproduces on your end.
