### ISSUE TITLE
Fold "(12 * unsigned) % 8 == 0" ->"(unsigned & 1) == 0" missing

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#39839]
|  |  |
| --- | --- |
| Bugzilla Link | [40493](https://llvm.org/bz40493) |
| Version | trunk |
| OS | Linux |
| CC | @efriedma-quic,@RKSimon,@rotateright |

## Extended Description 
Not sure how general this can be though.

https://godbolt.org/z/9bNnlb

https://rise4fun.com/Alive/O8a

  %mul = mul i32 %area, 12
  %rem = and i32 %mul, 4
  %cmp = icmp eq i32 %rem, 0
=>
  %and = and i32 %area, 1
  %cmp = icmp eq i32 %and, 0

**Comment by rotateright** [comment]
We improved demanded bits analysis, so we handle the example here in IR via one or more of these:
0236c571810d
5372160a188e
79b3fe80707b
897d92faeff6

The code in SDAG was updated to match that for consistency:
fc6bee1c11d4
d1ecfaa097b1

**Comment by rotateright** [comment]
There's at least one more demanded bits improvement that we can make: we can propagate undemanded high bits of the mul value to its operands. That is done in SDAG, but it's missing in IR for mul (it is also already done in IR for add/sub).
That would help with patterns like the related #50893, so I'll follow up there. 
Note that we also have a proposal for a pattern match solution starting from icmp: https://reviews.llvm.org/D114272 @FabianWolff 

So I think we can close this one, but please reopen if anyone sees more to do that is not covered in a related issue.

**Comment by LebedevRI** [comment]
Thanks!
