### ISSUE TITLE
Regression(r352660): Assertion `isValidGCCRegisterName(Name) && "Invalid register passed in"' when building chromium/win

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#39897]
|  |  |
| --- | --- |
| Bugzilla Link | [40551](https://llvm.org/bz40551) |
| Version | trunk |
| OS | Linux |
| Attachments | [repro](https://user-images.githubusercontent.com/3487/143758643-8819991f-8c77-4427-8e92-1c5aa089304f.gz) |
| CC | @topperc,@RKSimon,@rotateright |

## Extended Description 

repro attached

**Comment by Endilll** [comment]
Can't reproduce this using assertion builds of Clang 7 and 8.
