### ISSUE TITLE
diagnostics: "no return statement in constexpr function" when return exists but has bad type

### ISSUE THREAD

**Issue by comex** [llvm/llvm-project#39944]
|  |  |
| --- | --- |
| Bugzilla Link | [40598](https://llvm.org/bz40598) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@mizvekov,@zygoloid |

## Extended Description 
Given

constexpr int foo() {
    return "asdf";
}

Clang produces:

<source>:2:12: error: cannot initialize return object of type 'int' with an lvalue of type 'const char [5]'
    return "asdf";
           ^~~~~~
<source>:1:15: error: no return statement in constexpr function
constexpr int foo() {

The second error is clearly unhelpful in this case.

**Comment by sam-mccall** [comment]
One way to fix this is to preserve ReturnStmt in the AST even if the return value has the wrong type, e.g. using RecoveryExpr. I'm looking at this.
