### ISSUE TITLE
cppcoreguidelines-macro-usage warns about comma wrapper macro

### ISSUE THREAD

**Issue by pavelkryukov** [llvm/llvm-project#39945]
|  |  |
| --- | --- |
| Bugzilla Link | [40599](https://llvm.org/bz40599) |
| Version | unspecified |
| OS | All |
| CC | @JonasToth,@EugeneZelenko,@joto,@LegalizeAdulthood,@Trass3r |

## Extended Description 
Hi

cppcoreguidelines-macro-usage warning checks warns about
a commonly used wrapper around comma. It is used for other
preprocessing stuff (e.g. to call with a single # afterwards),
and there is no chance to convert it to any function.

> file.h:1:9: warning: macro 'COMMA' used to declare a constant; consider using a 'constexpr' constant [cppcoreguidelines-macro-usage]
> #define COMMA ,

**Comment by LegalizeAdulthood** [comment]
[clang-tidy] Narrow cppguidelines-macro-usage to actual constants
https://reviews.llvm.org/D116386

**Comment by pavelkryukov** [comment]
Thanks!
