### ISSUE TITLE
cppcoreguidelines-macro-usage should not warn about macros with #

### ISSUE THREAD

**Issue by pavelkryukov** [llvm/llvm-project#39946]
|  |  |
| --- | --- |
| Bugzilla Link | [40600](https://llvm.org/bz40600) |
| Version | unspecified |
| OS | All |
| CC | @JonasToth,@EugeneZelenko |

## Extended Description 
cppcoreguidelines-macro-usage produces following report

> file.cpp:10:9: warning: function-like macro 'REGISTER' used; consider a
> 'constexpr' template function [cppcoreguidelines-macro-usage]
> #define STRING(X) # X

However, such conversion cannot be expressed in terms
of constexpr or any other CPP function.

**Comment by pavelkryukov** [comment]
@LegalizeAdulthood I guess you’ve fixed this one, right?

**Comment by LegalizeAdulthood** [comment]
Yes, I believe this is fixed with my recent change.  I didn't notice this one or I would have included the # in my commit msg `:)`
