### ISSUE TITLE
Test case clang-tidy/run-clang-tidy.cpp  fails when path contains special characters

### ISSUE THREAD

**Issue by amy-kwan** [llvm/llvm-project#39940]
|  |  |
| --- | --- |
| Bugzilla Link | [40594](https://llvm.org/bz40594) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
The following test case exhibits failures on PowerPC: 

        Clang Tools :: clang-tidy/run-clang-tidy.cpp 

This test was introduced in https://reviews.llvm.org/rCTE327854. 
Whenever a path checked in the test contains special characters such as '+' (for example, if my path contains a directory named 'build+dir'), the test case will fail with "modernize-use-auto" in the output. 

When the path does not contain special characters, the test case will succeed. 

This test case may be similar to the behaviour seen in: llvm/llvm-project#39939

**Comment by PiotrZSL** [comment]
Fixed by:

commit 9f13a032b6d7f720caf6511d0c9b1b6b7d2bbc67
Author: George Burgess IV <george.burgess.iv@gmail.com>
Date:   Fri Nov 22 18:13:18 2019 -0800

    clang-tidy: don't use an absolute path in a test

    `run_clang_tidy` takes a regular expression to match against
    compile_commands.json entries. If we pass "%t/test.cpp" and "%t" expands
    to anything that includes chars that a regex treats specially, like '+',
    this test starts failing.
