### ISSUE TITLE
Solaris ld -z discard-unused=section and --gc-section only supported on newer releases

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39958]
|  |  |
| --- | --- |
| Bugzilla Link | [40612](https://llvm.org/bz40612) |
| Version | 8.0 |
| OS | Solaris |
| Attachments | [Proposed fix](https://user-images.githubusercontent.com/60944935/143758668-f3275780-6c45-47a9-b5fe-154715a5292e.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @jclulow |

## Extended Description 
The LLVM CMake modules emit the ld(1) option '-z discard-unused=section' (and --gc-sections) for linking.  These flags are new (in Solaris terms at least) and are also not yet supported on illumos variants.

I suspect we should put those flags behind a feature test when the platform is SunOS.

Assuming the feature test approach is acceptable, I'm working on a patch to submit that'd do that.

**Comment by brad0** [comment]
This was fixed quite awhile ago.. https://github.com/llvm/llvm-project/commit/2feb72bcd58cabb9f71538cb17fab459b6afc8ef
