### ISSUE TITLE
Missed optimization opportunity: transform comparisons with constants to a mask test

### ISSUE THREAD

**Issue by Kojoley** [llvm/llvm-project#39957]
|  |  |
| --- | --- |
| Bugzilla Link | [40611](https://llvm.org/bz40611) |
| Version | trunk |
| OS | All |
| CC | @DMG862,@zygoloid,@rotateright |

## Extended Description 
LLVM does not recognize that:

bool zot(unsigned i) {
    return i == 0 || i == 2;
}

Can be rewritten as:

bool zot_handopt(unsigned i) {
    return !(~2u & i);
}

https://rise4fun.com/Alive/PXsF

With more values the optimization even more useful:

bool ztfos(unsigned i) {
    return i == 0 || i == 2 || i == 4 || i == 6;
}
bool ztfos_handopt(unsigned i) {
    return !(~6u & i);
}

More complex example that greatly benefits from such optimization:

bool is_sign(char c) {
    return c == '-' || c == '+';
}
bool is_sign_handopt(char c) {
    unsigned char i = c;
    i -= '+';
    return !(~2u & i);
}

https://rise4fun.com/Alive/nKIp

GCC and MSVC recognize and optimize all the examples above https://godbolt.org/z/_Pmy0S
The problem is not target specific (checked x86, x86-64, ppc32, ppc64, arm, and arm64).

**Comment by bcl5980** [comment]
@rotateright 
I'm trying to fix the case 2 in SimplifyCFG, can you help to review it?
https://reviews.llvm.org/D122485

**Comment by rotateright** [comment]
@bcl5980 - I am away from work this week, but I will take a look as soon as possible when I am back.
