### ISSUE TITLE
clang warning: unknown warning option '-Wno-old-style-declaration'

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39962]
|  |  |
| --- | --- |
| Bugzilla Link | [40616](https://llvm.org/bz40616) |
| Version | 7.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
OVERVIEW:

There seems to be problem with clang and warning option '-Wno-old-style-declaration'.

    testaccount@testmachine:~$ uname -a
    Linux testmachine 4.15.0-45-generic #&#8203;48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

    testaccount@testmachine:~$ clang-7 -v
    clang version 7.0.0-3~ubuntu0.18.04.1 (tags/RELEASE_700/final)
    Target: x86_64-pc-linux-gnu
    Thread model: posix
    InstalledDir: /usr/bin
    Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/8
    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0
    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
    Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0
    Candidate multilib: .;@m64
    Selected multilib: .;@m64

STEP TO REPRODUCE:

    testaccount@testmachine:~$ echo "__clang__ __GNUC__ __GNUC_MINOR__ __GNUC_PATCHLEVEL__ __clang_major__ __clang_minor__ __clang_patchlevel__" | /usr/bin/clang-7 -E -P -Wno-old-style-declaration -
    warning: unknown warning option '-Wno-old-style-declaration'; did you mean '-Wno-out-of-line-declaration'? [-Wunknown-warning-option]
    1 4 2 1 7 0 0
    1 warning generated.

ADDITIONAL INFOS:

This issue also appears on clang-5 and clang-6.  
GCC (>=4.3) does not have this problem however.

**Comment by AaronBallman** [comment]
Clang does not support that warning flag, so the diagnostic is correct.
