### ISSUE TITLE
"Assertion `Ty == cast<PointerType>(Ptr->getType())->getElementType()' failed." with -instcombine on "strlen(i16*)"

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#39972]
|  |  |
| --- | --- |
| Bugzilla Link | [40626](https://llvm.org/bz40626) |
| Version | trunk |
| OS | Linux |
| Attachments | [reproducer](https://user-images.githubusercontent.com/55733087/143758670-037309f6-2353-484e-9641-04b38ddc8c14.gz) |

## Extended Description 

Running

 opt -instcombine -S -o - call-strlen.ll

yields

opt: ../lib/IR/Instructions.cpp:1185: llvm::LoadInst::LoadInst(llvm::Type *, llvm::Value *, const llvm::Twine &, bool, unsigned int, llvm::AtomicOrdering, SyncScope::ID, llvm::Instruction *): Assertion `Ty == cast<PointerType>(Ptr->getType())->getElementType()' failed.
Stack dump:
0.      Program arguments: build-all/bin/opt -instcombine -S -o - call-strlen.ll 
1.      Running pass 'Function Pass Manager' on module 'call-strlen.ll'.
2.      Running pass 'Combine redundant instructions' on function '@test_it'
 #&#8203;0 0x00000000022ab7e4 PrintStackTraceSignalHandler(void*) (build-all/bin/opt+0x22ab7e4)
 #&#8203;1 0x00000000022a97f0 llvm::sys::RunSignalHandlers() (build-all/bin/opt+0x22a97f0)
 #&#8203;2 0x00000000022abb48 SignalHandler(int) (build-all/bin/opt+0x22abb48)
 #&#8203;3 0x00007efebd1cf330 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10330)
 #&#8203;4 0x00007efebbdbec37 gsignal /build/eglibc-ripdx6/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
 #&#8203;5 0x00007efebbdc2028 abort /build/eglibc-ripdx6/eglibc-2.19/stdlib/abort.c:91:0
 #&#8203;6 0x00007efebbdb7bf6 __assert_fail_base /build/eglibc-ripdx6/eglibc-2.19/assert/assert.c:92:0
 #&#8203;7 0x00007efebbdb7ca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
 #&#8203;8 0x0000000001c8f5eb llvm::LoadInst::LoadInst(llvm::Type*, llvm::Value*, llvm::Twine const&, bool, unsigned int, llvm::AtomicOrdering, unsigned char, llvm::Instruction*) (build-all/bin/opt+0x1c8f5eb)
 #&#8203;9 0x0000000001c8f3a3 llvm::LoadInst::LoadInst(llvm::Type*, llvm::Value*, llvm::Twine const&, llvm::Instruction*) (build-all/bin/opt+0x1c8f3a3)
#&#8203;10 0x000000000239c053 llvm::LibCallSimplifier::optimizeStringLength(llvm::CallInst*, llvm::IRBuilder<llvm::ConstantFolder, llvm::IRBuilderDefaultInserter>&, unsigned int) (build-all/bin/opt+0x239c053)
#&#8203;11 0x00000000023a823c llvm::LibCallSimplifier::optimizeStringMemoryLibCall(llvm::CallInst*, llvm::IRBuilder<llvm::ConstantFolder, llvm::IRBuilderDefaultInserter>&) (build-all/bin/opt+0x23a823c)
#&#8203;12 0x00000000023a91f8 llvm::LibCallSimplifier::optimizeCall(llvm::CallInst*) (build-all/bin/opt+0x23a91f8)
#&#8203;13 0x0000000001e606c6 llvm::InstCombiner::tryOptimizeCall(llvm::CallInst*) (build-all/bin/opt+0x1e606c6)
#&#8203;14 0x0000000001e5c164 llvm::InstCombiner::visitCallBase(llvm::CallBase&) (build-all/bin/opt+0x1e5c164)
#&#8203;15 0x0000000001e5a1f2 llvm::InstCombiner::visitCallInst(llvm::CallInst&) (build-all/bin/opt+0x1e5a1f2)
#&#8203;16 0x0000000001e1ad79 llvm::InstCombiner::run() (build-all/bin/opt+0x1e1ad79)
#&#8203;17 0x0000000001e1ce11 combineInstructionsOverFunction(llvm::Function&, llvm::InstCombineWorklist&, llvm::AAResults*, llvm::AssumptionCache&, llvm::TargetLibraryInfo&, llvm::DominatorTree&, llvm::OptimizationRemarkEmitter&, bool, llvm::LoopInfo*) (build-all/bin/opt+0x1e1ce11)
#&#8203;18 0x0000000001e1d4eb llvm::InstructionCombiningPass::runOnFunction(llvm::Function&) (build-all/bin/opt+0x1e1d4eb)
#&#8203;19 0x0000000001caf3cd llvm::FPPassManager::runOnFunction(llvm::Function&) (build-all/bin/opt+0x1caf3cd)
#&#8203;20 0x0000000001caf688 llvm::FPPassManager::runOnModule(llvm::Module&) (build-all/bin/opt+0x1caf688)
#&#8203;21 0x0000000001cafaea llvm::legacy::PassManagerImpl::run(llvm::Module&) (build-all/bin/opt+0x1cafaea)
#&#8203;22 0x00000000007a322b main (build-all/bin/opt+0x7a322b)
#&#8203;23 0x00007efebbda9f45 __libc_start_main /build/eglibc-ripdx6/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;24 0x0000000000788c7d _start (build-all/bin/opt+0x788c7d)
Abort

This started happening after commit r352911 but possibly it was broken before too, even if the reproducer above didn't trigger the assertion then.

Also see
 http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20190204/624646.html
and the reply
 http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20190204/624810.html

**Comment by arsenm** [comment]
Don't see the assert now, plus typed pointers are obsolete
