### ISSUE TITLE
llvm-objdump unable to disassemble LSE atomic instructions

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#39995]
|  |  |
| --- | --- |
| Bugzilla Link | [40649](https://llvm.org/bz40649) |
| Version | trunk |
| OS | Linux |
| Attachments | [lse.s](https://user-images.githubusercontent.com/1823839/143758675-3ea860fc-b63d-47a6-810d-dbcd6bca269d.gz) |
| CC | @kbeyls,@rengolin,@rupprecht,@stephenhines,@TNorthover,@kongy |

## Extended Description 

$ cat lse.s
.arch_extension lse
.global _entry
.section _entry
  stadd w0, [x1]

$ clang -target aarch64-linux-gnu -c lse.s
$ aarch64-linux-gnu-objdump -D lse.o

lse.o:     file format elf64-littleaarch64

Disassembly of section _entry:

0000000000000000 <_entry>:
   0:	b820003f 	stadd	w0, [x1]

$ llvm-objdump -D lse.o 

lse.o:	file format ELF64-aarch64-little

Disassembly of section .strtab:
0000000000000000 .strtab:
       0:	00 5f 65 6e 	uqrshl	v0.8h, v24.8h, v5.8h
       4:	74 72 79 00  <unknown>
       8:	2e 74 65 78  <unknown>
       c:	74 00 2e 73  <unknown>
      10:	74 72 74 61  <unknown>
      14:	62 00 2e 73  <unknown>
      18:	79 6d 74 61  <unknown>
      1c:	62 00 24 78  <unknown>
      20:	2e  <unknown>
      21:	30  <unknown>
      22:	00  <unknown>
Disassembly of section _entry:
0000000000000000 $x.0:
       0:	3f 00 20 b8  <unknown>
Disassembly of section .symtab:
0000000000000000 .symtab:
		...
      18:	1e 00 00 00 	udf	llvm/llvm-project#402
      1c:	00 00 03 00  <unknown>
		...

**Comment by MaskRay** [comment]
Fixed by 275862c75d9f203903b8bda2c41bd2d1e1efe885 . llvm-objdump now disassembles all known AArch64 instructions by default (when neither --mcpu= nor --mattr= is specified).
