### ISSUE TITLE
[coroutines] heap allocation regression between clang 6 and clang 7

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#40002]
|  |  |
| --- | --- |
| Bugzilla Link | [40656](https://llvm.org/bz40656) |
| Version | 7.0 |
| OS | Windows NT |
| Attachments | [Halo is not triggered on clang 7 and trunk. Works as expected on clang 6](https://user-images.githubusercontent.com/60944935/143758678-291036c6-e635-4a4c-94a3-cbf4c8f2e7ba.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @arshajii,@lewissbaker |

## Extended Description 

Halo is not triggered on the attached example on clang 7 and trunk. Works as expected on clang 6.

https://godbolt.org/z/y4xoFC

**Comment by ChuanqiXu9** [comment]
This one should be outdated.
