### ISSUE TITLE
VS C++ errors for `compiler.h`

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#40019]
|  |  |
| --- | --- |
| Bugzilla Link | [40673](https://llvm.org/bz40673) |
| Version | 6.0 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
When including the header file `\llvm\Support\Compiler.h`,
Visual Studio's C++ compiler (used from Visual Studio Community 2017) complains that there are 3 errors in this header file, on lines 127, 230, and 236.

The error message is:
```
E2512	the argument to a feature-test macro must be a simple identifier
```
The cause of these error messages is the use of `::` in the argument to `__has_cpp_attribute`.

My proposal is to wrap each erroneous line and the line following it in a test to check whether `_MSC_VER` is defined or not. 

E.g. lines 127 and 128 which are 
```cpp
#elif __has_cpp_attribute(clang::warn_unused_result)
#define LLVM_NODISCARD [[clang::warn_unused_result]]
```
should be changed to 	
```cpp
#elif !defined(_MSC_VER) 
#if __has_cpp_attribute(clang::warn_unused_result)
#define LLVM_NODISCARD [[clang::warn_unused_result]]
#endif
```
This change fixes the error for me.

**Comment by cor3ntin** [comment]
MSVC now supports that code
