### ISSUE TITLE
clang: error: unable to execute command: Segmentation fault when compiling Apache Qpid Dispatch

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#40026]
|  |  |
| --- | --- |
| Bugzilla Link | [40680](https://llvm.org/bz40680) |
| Version | trunk |
| OS | Linux |
| Attachments | [https://user-images.githubusercontent.com/60944935/143758692-57863fdd-0ca3-4d30-8518-ef178126492e.gz), [https://user-images.githubusercontent.com/60944935/143758693-59558ede-45a1-42eb-bc30-cbbb4a1a8ed7.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 

-- Build files have been written to: /home/buildadm/qpid-dispatch/build
+ CC='clang-9 -fsanitize=thread'
+ CXX='clang++-9 -fsanitize=thread'
+ LDFLAGS=-fsanitize=thread
+ ninja -v install
[1/90] cd /home/buildadm/qpid-dispatch/build/src && /usr/bin/python /home/buildadm/qpid-dispatch/build/tests/run.py -s /home/buildadm/qpid-dispatch/src/schema_c.py
[2/90] /usr/bin/clang-9  -fsanitize=thread -Dqpid_dispatch_EXPORTS -I../include -Iinclude -I/home/buildadm/qpid-proton/build/install/include -I/usr/include/python2.7 -I../src -I../src/router_core -Isrc -fsanitize=thread -O2 -g -DNDEBUG -fPIC   -g -fno-omit-frame-pointer -Werror -Wall -Wpedantic -std=gnu99 -pthread -Wno-gnu-statement-expression -MD -MT src/CMakeFiles/qpid-dispatch.dir/bitmask.c.o -MF src/CMakeFiles/qpid-dispatch.dir/bitmask.c.o.d -o src/CMakeFiles/qpid-dispatch.dir/bitmask.c.o   -c /home/buildadm/qpid-dispatch/src/bitmask.c
FAILED: src/CMakeFiles/qpid-dispatch.dir/bitmask.c.o 
/usr/bin/clang-9  -fsanitize=thread -Dqpid_dispatch_EXPORTS -I../include -Iinclude -I/home/buildadm/qpid-proton/build/install/include -I/usr/include/python2.7 -I../src -I../src/router_core -Isrc -fsanitize=thread -O2 -g -DNDEBUG -fPIC   -g -fno-omit-frame-pointer -Werror -Wall -Wpedantic -std=gnu99 -pthread -Wno-gnu-statement-expression -MD -MT src/CMakeFiles/qpid-dispatch.dir/bitmask.c.o -MF src/CMakeFiles/qpid-dispatch.dir/bitmask.c.o.d -o src/CMakeFiles/qpid-dispatch.dir/bitmask.c.o   -c /home/buildadm/qpid-dispatch/src/bitmask.c
Stack dump:
0.	Program arguments: /usr/lib/llvm-9/bin/clang -cc1 -triple x86_64-pc-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name bitmask.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -coverage-notes-file /home/buildadm/qpid-dispatch/build/src/CMakeFiles/qpid-dispatch.dir/bitmask.c.gcno -resource-dir /usr/lib/llvm-9/lib/clang/9.0.0 -dependency-file src/CMakeFiles/qpid-dispatch.dir/bitmask.c.o.d -sys-header-deps -MT src/CMakeFiles/qpid-dispatch.dir/bitmask.c.o -D qpid_dispatch_EXPORTS -I ../include -I include -I /home/buildadm/qpid-proton/build/install/include -I /usr/include/python2.7 -I ../src -I ../src/router_core -I src -D NDEBUG -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-9/lib/clang/9.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O2 -Werror -Wall -Wpedantic -Wno-gnu-statement-expression -std=gnu99 -fdebug-compilation-dir /home/buildadm/qpid-dispatch/build -ferror-limit 19 -fmessage-length 0 -fsanitize=thread -pthread -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o src/CMakeFiles/qpid-dispatch.dir/bitmask.c.o -x c /home/buildadm/qpid-dispatch/src/bitmask.c -faddrsig 
1.	clang: error: unable to execute command: Segmentation fault
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 9.0.0-svn353471-1~exp1+0~20190207214556.1054~1.gbp77e1bc (trunk)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/bitmask-079a44.c
clang: note: diagnostic msg: /tmp/bitmask-079a44.sh
clang: note: diagnostic msg: 

********************
2019/02/10 16:21:20 Clang crash detected
[3/90] /usr/bin/clang-9  -fsanitize=thread -Dqpid_dispatch_EXPORTS -I../include -Iinclude -I/home/buildadm/qpid-proton/build/install/include -I/usr/include/python2.7 -I../src -I../src/router_core -Isrc -fsanitize=thread -O2 -g -DNDEBUG -fPIC   -g -fno-omit-frame-pointer -Werror -Wall -Wpedantic -std=gnu99 -pthread -Wno-gnu-statement-expression -MD -MT src/CMakeFiles/qpid-dispatch.dir/discriminator.c.o -MF src/CMakeFiles/qpid-dispatch.dir/discriminator.c.o.d -o src/CMakeFiles/qpid-dispatch.dir/discriminator.c.o   -c /home/buildadm/qpid-dispatch/src/discriminator.c

**Comment by Endilll** [comment]
Can't reproduce using Clang 7 through 9 with assertions enabled even after trying several dozens of times to account for flakiness.
