### ISSUE TITLE
ICE(internal compiler error), crash dump (nested friend template)

### ISSUE THREAD

**Issue by sw6ueyz** [llvm/llvm-project#40033]
|  |  |
| --- | --- |
| Bugzilla Link | [40687](https://llvm.org/bz40687) |
| Version | 7.0 |
| OS | All |
| Attachments | [dmp, cpp, sh files](https://user-images.githubusercontent.com/92601778/143758697-f3827f97-3ae9-4e2a-ab4f-6b3813ef91be.gz) |
| CC | @DougGregor,@zygoloid |

## Extended Description 

clang7.0.0 crashed with following log.
see attached files.

1>  Wrote crash dump file "C:\Users\sw6ueyz\AppData\Local\Temp\clang-cl.exe-a0071f.dmp"
1>  0x00007FF74A2F5E89 (0x0000000000000008 0x0000000000000000 0x0000000000000000 0x00007FF749A5166E)
1>  0x00007FF74A2EF113 (0x0000000000000000 0x00007FF749A92690 0x00000000000000A3 0x0000000000000000)
1>  0x00007FF74A2E6DF1 (0x00000080E838A500 0x0000000000000000 0x0000000000000000 0x0000000000000001)
1>  0x00007FF74A1D8BEE (0x00008FACE6710D39 0x0000020C79602EA0 0x00000080E838A4E0 0x00000080E838A4C0)
1>  0x00007FF74A29D804 (0x0000020C7B1C74A8 0x0000000000000009 0x0000020C79674700 0x0000020C79677928)
1>  0x00007FF74A29A8B1 (0x0000020C796162E0 0x00000080E838AA78 0x00000080E838AA78 0x0000020C79682CB0)
1>  0x00007FF74A2A3345 (0x0000020C79677928 0x00007FF74A20F0F8 0x0000020C79677928 0x00007FF74B655C5C)
1>  0x00007FF74A1D218E (0x00000080E838A9F0 0x00000080E838A9E0 0x000000000000000F 0x0000020C7B1C7550)
1>  0x00007FF74A1D2A5F (0x0000000000000040 0x00007FF700000000 0x0000000000000028 0x0000020C00000000)
1>  0x00007FF74A07045B (0x0000020C79682158 0x00000080E838C010 0x00000080E838C020 0x0000020C79682080)
1>  0x00007FF74A06AA37 (0x0000020000000000 0x00000080E838C008 0x0000000400000000 0x00007FF74A0701B4)
1>  0x00007FF74A062A73 (0x0000020C7966EE18 0x00007FF74A06AA7E 0x0000020C79602EA0 0x00000080E838C128)
1>  0x00007FF74A061D91 (0x0000000000000000 0x00007FF74B81CA84 0x0000000000000000 0x0000020C79686F40)
1>  0x00007FF74B9AFA05 (0x0000000000000000 0x00007FF74B9AFD15 0x00008FACE6716849 0x00000080E838D758)
1>  0x00007FF74B9ADC44 (0x0000020C00000012 0x00007FF74C731603 0x0000000000000009 0x0000020C00000013)
1>  0x00007FF74AD61324 (0x0000000000000000 0x0000000000000000 0x0000020C795B3CC0 0x0000020C7959AD50)
1>  0x00007FF74A4B227D (0x0000020C7959AD50 0x0000020C795EEF90 0x0000020C795C38A0 0x00007FF74A50A2F9)
1>  0x00007FF74A476847 (0x00000080E838DB01 0x0000000000000000 0x0000000000000000 0x0000020C795D9140)
1>  0x00007FF74A50AF5C (0x0000000000000000 0x00000080E838DB30 0x0000000000000003 0x0000000000000030)
1>  0x00007FF748B16E48 (0x00000080E838F301 0x0000000000000000 0x00000080E8380000 0x00007FFDD660F101)
1>  0x00007FF748B14317 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
1>  0x00007FF74B9B5780 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
1>  0x00007FFDD6E681F4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
1>  0x00007FFDD9A5A251 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
1>  clang-cl.exe : error : clang frontend command failed due to signal (use -v to see invocation)
1>  clang version 7.0.0 (tags/RELEASE_700/final)
1>  Target: x86_64-pc-windows-msvc
1>  Thread model: posix
1>  InstalledDir: C:\Program Files\LLVM\bin
1>  clang-cl.exe: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
1>  clang-cl.exe: note: diagnostic msg:
1>  ********************
1>
1>  PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
1>  Preprocessed source(s) and associated run script(s) are located at:
1>  clang-cl.exe: note: diagnostic msg: C:\Users\sw6ueyz\AppData\Local\Temp\test-cd725a.cpp
1>  clang-cl.exe: note: diagnostic msg: C:\Users\sw6ueyz\AppData\Local\Temp\test-cd725a.sh
1>  clang-cl.exe: note: diagnostic msg:
1>
1>  ********************

**Comment by wheatman** [comment]
reproduced on 7.0.0
seems to be fixed on 9.0.0

https://godbolt.org/z/bMPbqPM77
