### ISSUE TITLE
Function has token parameter but isn't an intrinsic

### ISSUE THREAD

**Issue by compnerd** [llvm/llvm-project#40056]
|  |  |
| --- | --- |
| Bugzilla Link | [40710](https://llvm.org/bz40710) |
| Version | unspecified |
| OS | Windows NT |
| CC | @DougGregor,@hiraditya,@pcc,@zygoloid,@rnk,@smeenai,@vedantk |

## Extended Description 
Reduced from ICU 61:

```cpp
// RUN: %clang_cc1 -triple x86_64-pc-windows-msvc19.0.0 -emit-obj -o /dev/null -O1 -fcxx-exceptions -fexceptions %s
struct T {
  virtual ~T();
};

void f();

struct S {
  virtual ~S();
  T t_[1];
};

S::~S() { f(); }
```

**Comment by hiraditya** [comment]
Attaching the patch by @vedantk(https://github.com/llvm/llvm-project/issues/40056#issuecomment-981009129)  above.
[0001-HotColdSplit-Disable-splitting-within-functions-with.txt](https://github.com/llvm/llvm-project/files/11056687/0001-HotColdSplit-Disable-splitting-within-functions-with.txt)

**Comment by compnerd** [comment]
@Endilll - what exactly needs to be done in terms of triaging? This is an issue with the hot cold splitting implementation, which is done in LLVM.

**Comment by hiraditya** [comment]
I think the fix is to disable outlining of basic blocks with token-type instructions
