### ISSUE TITLE
error in backend: Segmented stacks do not support vararg functions.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#40064]
|  |  |
| --- | --- |
| Bugzilla Link | [40718](https://llvm.org/bz40718) |
| Version | 8.0 |
| OS | Linux |
| Attachments | [packed cgo-gcc-input-266913532-73e194.c and cgo-gcc-input-266913532-73e194.sh](https://user-images.githubusercontent.com/60944935/143758709-b48c3348-a24e-4dba-97cd-76f26a449669.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @topperc,@RKSimon,@zygoloid,@rnk,@sanjoy,@rotateright |

## Extended Description 

Hi!

I'm not really sure what the problem with the code is, but I've attached the files mentioned by clang. 

Some background: I'm working with gollvm to compile C code that is being used in Go. 

Hopefully this can shed some light on a workaround, as I would like to be able to compile. Could it be, that the "-fsplit-stack" invokation leads to this?

CGO_LDFLAGS='"-g" "-O2" "-lrt"' /root/llvm-install/tools/cgo -objdir $WORK/b002/ -importpath karalabe-hid/karalabe/hid -gccgo -gccgopkgpath=karalabe-hid/karalabe/hid -exportheader=$WORK/b002/_cgo_install.h -- -fsanitize=fuzzer,memory -I $WORK/b002/ -g -O2 -I/root/go/src/karalabe-hid/karalabe/hid/hidapi/hidapi -I/root/go/src/karalabe-hid/karalabe/hid/libusb/libusb -DDEFAULT_VISIBILITY= -DOS_LINUX -D_GNU_SOURCE -DPOLL_NFDS_TYPE=int -fsplit-stack ./hid_enabled.go ./wchar.go
# karalabe-hid/karalabe/hid
fatal error: error in backend: Segmented stacks do not support vararg functions.
clang-8: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 8.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-8: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-8: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-8: note: diagnostic msg: /tmp/cgo-gcc-input-266913532-73e194.c
clang-8: note: diagnostic msg: /tmp/cgo-gcc-input-266913532-73e194.sh
clang-8: note: diagnostic msg:

********************

**Comment by asl** [comment]
Dup of #19571
