### ISSUE TITLE
Error mangling declaration in Android NDK header

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#40093]
|  |  |
| --- | --- |
| Bugzilla Link | [40747](https://llvm.org/bz40747) |
| Version | 7.0 |
| OS | All |
| Depends On | llvm/llvm-project#38642  |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie,@froydnj,@zygoloid,@rnk,@HighCommander4 |

## Extended Description 
+++ This bug was initially created as a clone of Bug #&#8203;39294 +++

Same setup as bug 39294:
We have a clang plugin that at some point tries to get mangled names for various C++ elements from the clang AST. It uses the ItaniumMangle context.

Except this time I'm cross compiling for Android ARM from a Linux host. The mangler emits this error:

/builds/worker/workspace/build/src/android-ndk/sources/cxx-stl/llvm-libc++/include/tuple:1015:25: Mangling declaration 'std::__ndk1::__find_detail::__find_exactly_one_checked::__matches'

**Comment by Endilll** [comment]
Link is dead, and no other source code was attached.
