### ISSUE TITLE
Complete implementation of fewerElementsVector legalization method in GlobalISel

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#40112]
|  |  |
| --- | --- |
| Bugzilla Link | [40766](https://llvm.org/bz40766) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @aemerson,@dsandersllvm,@ecnelises,@ornata,@arsenm,@qcolombet |

## Extended Description 
It looks like the current version of the fewerElementsVector legalization method in GlobalISel can handle its inputs iff originalNumberOfElements % requestedNumberOfElements is either 0 or 1 (the vector could be split into equally sized parts or the reminder is exactly a single scalar). It's hard to call such a behavior orthogonal and well expected, and it looks like it may cause subtle and hard to notice bugs and / or force people to do non-obvious work-arounds, maybe we need to improve this. See https://reviews.llvm.org/D58123#inline-516061 and around for more details.

**Comment by aemerson** [comment]
Closing

**Comment by EugeneZelenko** [comment]
@aemerson: Could you please elaborate?
