### ISSUE TITLE
InnerLoopVectorizer::emitSCEVChecks(llvm::Loop *, llvm::BasicBlock *): Assertion `!Cost->foldTailByMasking() && "Cannot SCEV check stride or overflow when folding tail"' failed.

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#40162]
|  |  |
| --- | --- |
| Bugzilla Link | [40816](https://llvm.org/bz40816) |
| Version | trunk |
| OS | Linux |
| Attachments | [reproducer](https://user-images.githubusercontent.com/55733087/143758751-c630ea75-c935-4a40-a32b-bbcea2d4fe42.gz) |
| CC | @ayalz,@JonPsson |

## Extended Description 

Reproduce with:
  opt -S -o - -loop-vectorize bbi-23939_x86.ll -mtriple=x86_64-unknown-unknown -mcpu=skylake-avx512 -enable-interleaved-mem-accesses=0

This seems to be similar to
  llvm/llvm-project#38765 
but the fix for that in r345959 doesn't seem to help here.

**Comment by artagnon** [comment]
No longer reproduces on `main`.
