### ISSUE TITLE
Crash during compilation

### ISSUE THREAD

**Issue by MarkIngramUK** [llvm/llvm-project#40165]
|  |  |
| --- | --- |
| Bugzilla Link | [40819](https://llvm.org/bz40819) |
| Version | 7.0 |
| OS | Windows NT |
| Attachments | [Crash dump](https://user-images.githubusercontent.com/92601248/143758753-5039dba1-d931-41f7-846d-10adfff319b3.gz), [Run script](https://user-images.githubusercontent.com/92601248/143758754-7554d783-a427-4aaf-be12-ad7a43d38954.gz) |
| CC | @riccibruno,@zygoloid |

## Extended Description 

Crash when compiling C++ code. 

  0x00007FF7C98ABF27 (0x00000238EB076930 0x00000238EB06D910 0x00000238EB0772E8 0x00000238F3E7F630)
  0x00007FF7C98ABE0E (0x0000023800000012 0x00007FF7CA7C1603 0x0000000000000009 0x0000023800000013)
  0x00007FF7C8DF1254 (0x0000000000000000 0x0000000000000000 0x00000238EB021AB0 0x00000238EB090380)
  0x00007FF7C854227D (0x00000238EB090380 0x00000238EB06B2F0 0x00000238EB00A890 0x00007FF7C859A2F9)
  0x00007FF7C8506847 (0x000000F77678DD01 0x0000000000000000 0x0000000000000000 0x00000238EB060930)
  0x00007FF7C859AF5C (0x00000238EB05D740 0x00000F81E1798573 0x00000238EB00E96C 0x00000000000003E3)
  0x00007FF7C6BA6E48 (0x0000000000000000 0x0000000000000000 0x000000F77678E680 0x000000F77678E430)
  0x00007FF7C6BA4317 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
  0x00007FF7C9A45780 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
  0x00007FFB31E23DC4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
  0x00007FFB33533691 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\clang-cl.exe : error : clang frontend command failed due to signal (use -v to see invocation)
  clang version 7.0.0 (tags/RELEASE_700/final)
  Target: x86_64-pc-windows-msvc
  Thread model: posix
  InstalledDir: C:\PROGRA~1\LLVM\bin

**Comment by Endilll** [comment]
Author hasn't got back to us with a minimal example.
