### ISSUE TITLE
Implement CWG 2096

### ISSUE THREAD

**Issue by CaseyCarter** [llvm/llvm-project#40183]
|  |  |
| --- | --- |
| Bugzilla Link | [40837](https://llvm.org/bz40837) |
| Version | trunk |
| OS | Windows NT |
| CC | @zygoloid |

## Extended Description 
Compiling this well-formed TU:
```cpp
    struct nonliteral {
        nonliteral() {}
    };

    union U {
        int head_;
        nonliteral tail_;

        constexpr U() : head_{} {}
    };

    constexpr U u{};
```
with `clang++ -std=c++17` diagnoses (https://godbolt.org/z/lQKtv8):
```
    source>:12:17: error: constexpr variable cannot have non-literal type 'const U'
        constexpr U u{};
                    ^
    <source>:7:20: note: 'U' is not literal because it has data member 'tail_' of non-literal type 'nonliteral'
            nonliteral tail_;
                       ^
    1 error generated.
```
This impacts usage of `std::variant` with a mix of literal and non-literal types in a constant expression.

**Comment by cor3ntin** [comment]
Fixed in Clang 18
