### ISSUE TITLE
Missed optimization with redundant overflow checks

### ISSUE THREAD

**Issue by 24ae4267-5921-45a9-a006-c88f1b8f1b03** [llvm/llvm-project#40191]
|  |  |
| --- | --- |
| Bugzilla Link | [40845](https://llvm.org/bz40845) |
| Version | trunk |
| OS | All |
| CC | @alex,@nelhage |

## Extended Description 
Godbolt link: https://godbolt.org/z/h2lkGE

The subtraction can be known not to overflow because it's derived from an overflow checked addition. This was reduced/converted to C from this rust bug: https://github.com/rust-lang/rust/issues/58692

One commenter suggested they thought the issue was in how GVN handled overflow checked operations.

Code:
```
#include <stdlib.h>

extern void panic1();
extern void panic2();
extern void panic3();

size_t f(size_t a, size_t b) {
    size_t x;
    if (!__builtin_add_overflow(a, b, &x)) {
        panic1();
        __builtin_unreachable();
    }

    size_t r;
    if (!__builtin_sub_overflow(x, a, &r)) {
        panic2();
        __builtin_unreachable();
    }
    
    if (r < 0) {
        panic3();
        __builtin_unreachable();
    }

    return x;
}
```
Assembly:
```
f(unsigned long, unsigned long):                                 # @f(unsigned long, unsigned long)
        push    rax
        mov     rax, rsi
        add     rax, rdi
        jae     .LBB0_3
        cmp     rax, rdi
        jae     .LBB0_4
        pop     rcx
        ret
.LBB0_3:
        call    panic1()
.LBB0_4:
        call    panic2()
```

**Comment by alex** [comment]
It looks like this is fixed on llvm/clang trunk, per godbolt: https://godbolt.org/z/8shWdvbeq

**Comment by alex** [comment]
Can someone please close this, it's been fixed since llvm/clang 16.

**Comment by alex** [comment]
Thanks
