### ISSUE TITLE
cxx_status.html seems out of date on c++ default dialect

### ISSUE THREAD

**Issue by rgal** [llvm/llvm-project#40209]
|  |  |
| --- | --- |
| Bugzilla Link | [40863](https://llvm.org/bz40863) |
| Version | trunk |
| OS | All |
| CC | @zygoloid |

## Extended Description 
https://clang.llvm.org/cxx_status.html says:

"By default, Clang builds C++ code according to the C++98 standard, with many C++11 features accepted as extensions. You can use Clang in C++11 mode with the -std=c++11 option."

As of r320250 this was changed to C++14.

**Comment by arsenm** [comment]
"By default, Clang 16 or later builds C++ code according to the C++17 standard"
