### ISSUE TITLE
[coverage] linker failure with dead code stripping

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#40229]
|  |  |
| --- | --- |
| Bugzilla Link | [40884](https://llvm.org/bz40884) |
| Version | trunk |
| OS | Windows XP |
| Reporter | LLVM Bugzilla Contributor |
| CC | @rnk |

## Extended Description 
This is related to Bug 37561. The bug is fixed now, but I get linker errors (lld-link) when building teh project with optimizer (for release).

lld-link reports about an error with relocation against "symbol" in discarded section. This was triggered by a global function calling sprintf(), which was not referenced. After I removed the function or replaced sprintf() with snprintf(), linker did not complain, but the unit test was failing.

When building for Debug, the linker also did not complain, the unit test was passing and I was able to create the coverage report.

Looks to me like dead code stripping is leading to dangling references and also the Optimizer may cause code corruptions.

I hope Marius can reproduce the issue with his project, as I can hardly share mine and it comes with a lot of references in our repository.

SSB

**Comment by fhahn** [comment]
Closing as per latest comment by the reporter.
