### ISSUE TITLE
LLDB compiled by gcc doesn't evaluate expressions on 32 bit

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#40292]
|  |  |
| --- | --- |
| Bugzilla Link | [40947](https://llvm.org/bz40947) |
| Version | 5.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @kwk |

## Extended Description 
I'm using LLDB cross-compiled by gcc on ARM. When I'm trying to evaluate a simple expression (e.g. x+1), debugger gives an error message: "Expression can't be run, because there is no JIT compiled function".

I think I've found the reason. In function lldb_private::IRExecutionUnit::GetRunnableInfo there is a cast operator from void* (32 bit in my case) to lldb::addr_t (64 bit). Pointer-to-integer conversion is implementation defined as per the C99 standard and gcc performs signed extension here. Further it compares with unsigned number (uintptr_t) in IRExecutionUnit::GetRemoteAddressForLocal and address can't be found.

**Comment by DavidSpickett** [comment]
We run the test suite on the 32 bit Arm buildbot which likely does a ton of stuff just like this without issue. Looking at the code I don't see the cast anymore so it may have been fixed.

If this still were an issue, we'd need a reproducer to add to the test suite.
