### ISSUE TITLE
llvm/test/Transforms/SLPVectorizer/X86/phi.ll test is failing with release_80 branch

### ISSUE THREAD

**Issue by BalaRishi-AMD** [llvm/llvm-project#40296]
|  |  |
| --- | --- |
| Bugzilla Link | [40951](https://llvm.org/bz40951) |
| Version | 8.0 |
| OS | Linux |

## Extended Description 
With release_80 branch, facing the below failure for llvm/test/Transforms/SLPVectorizer/X86/phi.ll:

FAIL: LLVM :: Transforms/SLPVectorizer/X86/phi.ll (27008 of 29439)
******************** TEST 'LLVM :: Transforms/SLPVectorizer/X86/phi.ll' FAILED ********************
Script:
--
: 'RUN: at line 2';   /home/amd/JENKINS/workspace/CPUPC_AMD_LLVM-8-0-0-ORG_Branch/BUILD_DIR/bin/opt < /home/amd/JENKINS/workspace/CPUPC_AMD_LLVM-8-0-0-ORG_Branch/llvm/test/Transforms/SLPVectorizer/X86/phi.ll -basicaa -slp-vectorizer -slp-threshold=-100 -dce -S -mtriple=i386-apple-macosx10.8.0 -mcpu=corei7-avx | /home/amd/JENKINS/workspace/CPUPC_AMD_LLVM-8-0-0-ORG_Branch/BUILD_DIR/bin/FileCheck /home/amd/JENKINS/workspace/CPUPC_AMD_LLVM-8-0-0-ORG_Branch/llvm/test/Transforms/SLPVectorizer/X86/phi.ll
--
Exit Code: 1

Command Output (stderr):
--
/home/amd/JENKINS/workspace/CPUPC_AMD_LLVM-8-0-0-ORG_Branch/llvm/test/Transforms/SLPVectorizer/X86/phi.ll:147:15: error: CHECK-NEXT: expected string not found in input
; CHECK-NEXT: [[REORDER_SHUFFLE:%.*]] = shufflevector <4 x float> [[TMP2]], <4 x float> undef, <4 x i32> <i32 3, i32 2, i32 1, i32 0>
              ^
<stdin>:52:2: note: scanning from here
 %3 = extractelement <4 x float> %2, i32 0
 ^
<stdin>:52:2: note: with variable "TMP2" equal to "%2"
 %3 = extractelement <4 x float> %2, i32 0
 ^

--

====================

Please let me know if additional details are required.
====================

**Comment by arsenm** [comment]
Old release
