### ISSUE TITLE
Nightly debian repository empty?

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#40343]
|  |  |
| --- | --- |
| Bugzilla Link | [40998](https://llvm.org/bz40998) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I tried installing llvm-8 on debian stretch.
When I do apt-get update it seems to work, but then apt can't find any packages to install.

If I look at the InRelease file it looks like there's no packages listed for x86_64. main/binary-i386/Packages has a size of 38999 bytes, but main/binary-amd64/Packages is 0 bytes:

$ cat /var/lib/apt/lists/apt.llvm.org_stretch_dists_llvm-toolchain-stretch-8_InRelease 
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Codename: llvm-toolchain-stretch-8
Date: Thu, 28 Feb 2019 06:18:14 UTC
Architectures: amd64 i386
Components: main
MD5Sum:
 d41d8cd98f00b204e9800998ecf8427e 0 main/binary-amd64/Packages
 7029066c27ac6f5ef18d660d5741979a 20 main/binary-amd64/Packages.gz
 063287201b2354699acfe229a752201d 36 main/binary-amd64/Release
 d41d8cd98f00b204e9800998ecf8427e 0 main/debian-installer/binary-amd64/Packages
 7029066c27ac6f5ef18d660d5741979a 20 main/debian-installer/binary-amd64/Packages.gz
 ff8e7a2d8242dd7977ad34784d2482b7 38999 main/binary-i386/Packages
 d519bbbff0b5bff352a60d78207431e4 8424 main/binary-i386/Packages.gz
 5e77d15a7c8b516e15488780beb4ad24 35 main/binary-i386/Release
 d41d8cd98f00b204e9800998ecf8427e 0 main/debian-installer/binary-i386/Packages
 7029066c27ac6f5ef18d660d5741979a 20 main/debian-installer/binary-i386/Packages.gz
 d41d8cd98f00b204e9800998ecf8427e 0 main/source/Sources
 7029066c27ac6f5ef18d660d5741979a 20 main/source/Sources.gz
 92f9b0ec8b2656847b612632542f1735 37 main/source/Release
...

**Comment by sylvestre** [comment]
fixed now
