### ISSUE TITLE
ICE in infinite instantiation of recursive template member function

### ISSUE THREAD

**Issue by 07db8777-e875-47a6-8e13-f3ee3e0342de** [llvm/llvm-project#40385]
|  |  |
| --- | --- |
| Bugzilla Link | [41040](https://llvm.org/bz41040) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description
```cpp
struct CallMe  {
    template <typename Arg>
    auto operator()(Arg arg)
        -> decltype((*this)(arg));
        // The issue is that Clang considers class `CallMe`
        // as callable in this point, if replace `(*this)(arg)`
        // to explicit function call `this->operator()(arg)`
        // the issue will be resolved.
};

void test(CallMe f) {
    f(239);
}
```
https://godbolt.org/z/QghBya

**Comment by Endilll** [comment]
The first reproducer appears to be fixed in Clang 10, and does not reproduce on trunk (19.0): https://godbolt.org/z/vGjGPWr9s
The first reproducer appears to be fixed in Clang 14, and does not reproduce on trunk (19.0): https://godbolt.org/z/5hEeEz9E4
