### ISSUE TITLE
X86 backend converts calls to constant addresses to indirect calls.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#4038]
|  |  |
| --- | --- |
| Bugzilla Link | [3666](https://llvm.org/bz3666) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@sunfishcode,@darkbuck,@nlewycky |

## Extended Description 
The following llvm code:

target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:32:32"
target triple = "i386-pc-linux-gnu"

define i32 @&#8203;main() nounwind {
entry:
	%0 = call i32 inttoptr (i32 12345678 to i32 (i32)*)(i32 0) nounwind		; <i32> [#uses=1]
	ret i32 %0
}

Produces the following assembler (with directives removed)
	
main:
	subl	$4, %esp
	movl	$0, (%esp)
	movl	$12345678, %eax
	call	*%eax
	addl	$4, %esp
	ret

Whereas it should produce this code:

main:
	subl	$4, %esp
	movl	$0, (%esp)
	call	*12345678
	addl	$4, %esp
	ret

This is important since all calls in JIT compiled code, will be in the above form.

**Comment by arsenm** [comment]
Comments say fixed
