### ISSUE TITLE
Crash compiling CMark using Swift's branch of Clang

### ISSUE THREAD

**Issue by belkadan** [llvm/llvm-project#40405]
|  |  |
| --- | --- |
| Bugzilla Link | [41060](https://llvm.org/bz41060) |
| Version | unspecified |
| OS | All |
| CC | @dexonsmith,@zygoloid |

## Extended Description 
(filing on behalf of Marcin Krzyzanowski)

A recent Swift snapshot of Clang crashes when building CMark; repro script and preprocessed files attached to https://bugs.swift.org/browse/SR-10090.

(Admittedly Swift's copy of Clang is going to have branched a while ago, but it's still possible this hasn't been fixed. If it has, we'll track down the fix and cherry-pick it.)

**Comment by Endilll** [comment]
Comments in downstream issue suggest that this was fixed.
