### ISSUE TITLE
operator<=> fails on Windows with Visual Sutdio 2019 Preview

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#40406]
|  |  |
| --- | --- |
| Bugzilla Link | [41061](https://llvm.org/bz41061) |
| Version | 7.0 |
| OS | Windows NT |
| CC | @zygoloid |

## Extended Description 
When compiling code that uses std::strong_ordering using clang and Visual Studio 2019 Preview 4.2, I get the following error message:

error : standard library implementation of 'std::strong_ordering' is not supported; the type does not have the expected form

Sample test file:

#include <compare>

auto x = 0 <=> 0;

**Comment by xgupta** [comment]
It seems to be fixed https://godbolt.org/z/fPvsjhdGM.
