### ISSUE TITLE
[clang-format] Block after case/default label is unindented one level

### ISSUE THREAD

**Issue by Lastique** [llvm/llvm-project#40431]
|  |  |
| --- | --- |
| Bugzilla Link | [41086](https://llvm.org/bz41086) |
| Version | 8.0 |
| OS | Linux |
| CC | @Lastique,@mydeveloperday |

## Extended Description 
For some reason clang-format unindents code blocks after `case` or `default` labels one level, and there seems to be no way to configure that. My desired formatting style is like this:

```
switch (i)
{
case 1:
    x = 10;
    break;

case 2:
    {
        x = 20;
    }
    break;
}
```

In other words, I need `case`/`default` labels to be unindented one level and the code after the labels to be indented one level, whether or not that code includes a code block.

In practice the second `case` gets always unindented like this:

```
switch (i)
{
case 1:
    x = 10;
    break;

case 2:
{
    x = 20;
}
break;
}
```

Please, add an option to fix this.

**Comment by eywdck2l** [comment]
This problem was fixed in 14c044756e771eb9160d5809b4381bdeb0fc210c.
Use these options:

```
BreakBeforeBraces: Allman
IndentCaseBlocks: true
IndentWidth: 4
```
