### ISSUE TITLE
Clang looses constexpr.

### ISSUE THREAD

**Issue by e0e1e613-dccb-47a5-85db-3dc989429265** [llvm/llvm-project#40438]
|  |  |
| --- | --- |
| Bugzilla Link | [41093](https://llvm.org/bz41093) |
| Resolution | INVALID |
| Resolved on | Jun 29, 2020 09:29 |
| Version | unspecified |
| OS | All |
| CC | @DaemonSnake,@jonathanpoelen,@zygoloid,@rogerorr,@fiesh |

## Extended Description 
The following code doesn't compile with clang and compiles with gcc.
https://gcc.godbolt.org/z/L6dcAu

**Comment by pinskia** [comment]
Note https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2280r4.html changes this to be valid from invalid ...

**Comment by shafik** [comment]
This is really a dup of: https://github.com/llvm/llvm-project/issues/63139
