### ISSUE TITLE
clang 8 RC 5 fails to compile <filesystem> on Visual Studio 2017 and Visual Studio 2019 with c++latest

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#40477]
|  |  |
| --- | --- |
| Bugzilla Link | [41132](https://llvm.org/bz41132) |
| Version | 8.0 |
| OS | Windows NT |
| CC | @nico,@zygoloid,@rnk,@StephanTLavavej |

## Extended Description 
The following program fails to compile with `/std:c++latest`:

#include <filesystem>

When using Visual Studio 2017's standard library:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\experimental/filesystem(45): error : declaration of anonymous struct must be a definition

And when using Visual Studio 2019s:

4>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.20.27404\include\experimental/filesystem(45): error : declaration of anonymous struct must be a definition

The relevant line is:

            struct char8_t; // flag for UTF8

**Comment by davidstone** [comment]
No longer relevant

**Comment by cpeterso** [comment]
Good news! The filesystem header in the current MSVC SDK (version 14.39.33519) has renamed the incompatible `struct char8_t` declaration to a C++20 compatible name: `struct _Char8_t`.
