### ISSUE TITLE
#pragma weak doesn't work

### ISSUE THREAD

**Issue by pwo** [llvm/llvm-project#4051]
|  |  |
| --- | --- |
| Bugzilla Link | [3679](https://llvm.org/bz3679) |
| Version | unspecified |
| OS | FreeBSD |
| Blocks | llvm/llvm-bugzilla-archive#10899 llvm/llvm-bugzilla-archive#4696  |
| Attachments | [Test case](https://user-images.githubusercontent.com/92601275/143738946-00a89815-2f80-4f8c-baec-beeb5de5a3c3.gz) |
| CC | @asl,@DougGregor,@EdSchouten,@efriedma-quic,@Theodor,@hfinkel |

## Extended Description 

0>root@one /tmp# gcc -o t t.c
0>root@one /tmp# ./t
spasiba
0>root@one /tmp# ccc -o t t.c
/tmp/tmpTGEXC1.o(.text+0x2b): In function `main':
: undefined reference to `t'

**Comment by arrowd** [comment]
This seem to be fixed. Clang emits a error for the testcase now:

```
t2.c:20:14: error: weak declaration cannot have internal linkage
#pragma weak Av1a = lv1
             ^
```

Removing `static` from the variable definition makes the error go away and the condition evaluates correctly. I believe this can be closed.
