### ISSUE TITLE
auto-returning function declarations not matched to friend definitions in template classes

### ISSUE THREAD

**Issue by 0775a785-4f8d-448e-9da0-14f81adf2169** [llvm/llvm-project#40512]
|  |  |
| --- | --- |
| Bugzilla Link | [41167](https://llvm.org/bz41167) |
| Version | trunk |
| OS | Windows NT |
| CC | @DougGregor,@zygoloid |

## Extended Description 
clang seems to be the only compiler to reject this code: https://godbolt.org/z/jeXWIy

// fine
constexpr int f();
struct X { 
    friend constexpr int f() { return 42; }
};
auto x = f();

// also fine
constexpr auto g();
struct Y { 
    friend constexpr auto g() { return 42; }
};
auto y = g();

// still fine
constexpr int ff();
template <typename T>
struct XX { 
    friend constexpr int ff() { return 42; }
};
template struct XX<int>;
auto xx = ff();

// boom
constexpr auto gg();
template <typename T>
struct YY { 
    friend constexpr auto gg() { return 42; }
};
template struct YY<int>;
auto yy = gg();

**Comment by wheatman** [comment]
This was fixed between 11.0.1 and 12.0.0
https://godbolt.org/z/j988PGczb

code
```cpp
// fine
constexpr int f();
struct X { 
    friend constexpr int f() { return 42; }
};
auto x = f();

// also fine
constexpr auto g();
struct Y { 
    friend constexpr auto g() { return 42; }
};
auto y = g();

// still fine
constexpr int ff();
template <typename T>
struct XX { 
    friend constexpr int ff() { return 42; }
};
template struct XX<int>;
auto xx = ff();

// boom
constexpr auto gg();
template <typename T>
struct YY { 
    friend constexpr auto gg() { return 42; }
};
template struct YY<int>;
auto yy = gg();
```

old error
```
<source>:31:11: error: function 'gg' with deduced return type cannot be used before it is defined
auto yy = gg();
          ^
<source>:25:16: note: 'gg' declared here
constexpr auto gg();
               ^
1 error generated.
Compiler returned: 1
```
