### ISSUE TITLE
LegalizationArtifactCombiner.h contains: "using namespace llvm::MIPatternMatch;" in the root namespace

### ISSUE THREAD

**Issue by abique** [llvm/llvm-project#40534]
|  |  |
| --- | --- |
| Bugzilla Link | [41189](https://llvm.org/bz41189) |
| Version | 8.0 |
| OS | MacOS X |

## Extended Description 
Hi,

I wonder if having "using namespace" in the root namespace is safe. Probably not.

I think it is responsible for a conflict between OSX's TimeRecord and the one in LLVM:

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/MacTypes.h:604:16: error: reference to 'TimeRecord' is ambiguous
typedef struct TimeRecord               TimeRecord;
               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/MacTypes.h:599:8: note: candidate found by name lookup is 'TimeRecord'
struct TimeRecord {
       ^
In file included from /Users/buildbot/jenkins/workspace/bw-studio-osx-release/float/app/nitro/src/main/cpp/Jit.cpp:11:
In file included from ../../app/nitro/src/main/include/nitro/LLVM.h:34:
In file included from ../../../target/dependencies/include/llvm/Passes/StandardInstrumentations.h:21:
In file included from ../../../target/dependencies/include/llvm/IR/PassTimingInfo.h:23:
../../../target/dependencies/include/llvm/Support/Timer.h:27:7: note: candidate found by name lookup is 'llvm::TimeRecord'
class TimeRecord {
      ^

**Comment by arsenm** [comment]
I don't see this now
