### ISSUE TITLE
opt -irce crashing with "Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed"

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#40539]
|  |  |
| --- | --- |
| Bugzilla Link | [41194](https://llvm.org/bz41194) |
| Version | trunk |
| OS | Linux |
| Attachments | [reproducer](https://user-images.githubusercontent.com/55733087/143758915-63fef8b7-3dab-41df-9ba7-4d8b9e9661f2.gz) |

## Extended Description 

Reproduce with:
 opt -irce bbi-26117.ll -S -o -

which yields:

opt: ../include/llvm/Support/Casting.h:254: typename cast_retty<X, Y *>::ret_type llvm::cast(Y *) [X = llvm::IntegerType, Y = llvm::Type]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
Stack dump:
0.      Program arguments: build-all/bin/opt -irce bbi-26117.ll -S -o - 
1.      Running pass 'Function Pass Manager' on module 'bbi-26117.ll'.
2.      Running pass 'Loop Pass Manager' on function '@test_read_imm_2'
3.      Running pass 'Inductive range check elimination' on basic block '%cont48'
 #&#8203;0 0x000000000229a344 PrintStackTraceSignalHandler(void*) (build-all/bin/opt+0x229a344)
 #&#8203;1 0x0000000002298350 llvm::sys::RunSignalHandlers() (build-all/bin/opt+0x2298350)
 #&#8203;2 0x000000000229a6a8 SignalHandler(int) (build-all/bin/opt+0x229a6a8)
 #&#8203;3 0x00007f6fcc262330 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10330)
 #&#8203;4 0x00007f6fcae51c37 gsignal /build/eglibc-ripdx6/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
 #&#8203;5 0x00007f6fcae55028 abort /build/eglibc-ripdx6/eglibc-2.19/stdlib/abort.c:91:0
 #&#8203;6 0x00007f6fcae4abf6 __assert_fail_base /build/eglibc-ripdx6/eglibc-2.19/assert/assert.c:92:0
 #&#8203;7 0x00007f6fcae4aca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
 #&#8203;8 0x0000000002063ca5 (anonymous namespace)::InductiveRangeCheckElimination::run(llvm::Loop*, llvm::function_ref<void (llvm::Loop*, bool)>) (build-all/bin/opt+0x2063ca5)
 #&#8203;9 0x0000000002066341 (anonymous namespace)::IRCELegacyPass::runOnLoop(llvm::Loop*, llvm::LPPassManager&) (build-all/bin/opt+0x2066341)
#&#8203;10 0x00000000016fa4dc llvm::LPPassManager::runOnFunction(llvm::Function&) (build-all/bin/opt+0x16fa4dc)
#&#8203;11 0x0000000001ca0d4d llvm::FPPassManager::runOnFunction(llvm::Function&) (build-all/bin/opt+0x1ca0d4d)
#&#8203;12 0x0000000001ca1008 llvm::FPPassManager::runOnModule(llvm::Module&) (build-all/bin/opt+0x1ca1008)
#&#8203;13 0x0000000001ca146a llvm::legacy::PassManagerImpl::run(llvm::Module&) (build-all/bin/opt+0x1ca146a)
#&#8203;14 0x00000000007a073b main (build-all/bin/opt+0x7a073b)
#&#8203;15 0x00007f6fcae3cf45 __libc_start_main /build/eglibc-ripdx6/eglibc-2.19/csu/libc-start.c:321:0
#&#8203;16 0x000000000078618d _start (build-all/bin/opt+0x78618d)
Abort

Starts crashing with r351926:

    [IRCE] Support narrow latch condition for wide range checks
    
    This patch relaxes restrictions on types of latch condition and range check.
    In current implementation, they should match. This patch allows to handle
    wide range checks against narrow condition. The motivating example is the
    following:
    
      int N = ...
      for (long i = 0; (int) i < N; i++) {
        if (i >= length) deopt;
      }
    
    In this patch, the option that enables this support is turned off by
    default. We'll wait until it is switched to true.
    
    Differential Revision: https://reviews.llvm.org/D56837
    Reviewed By: reames
    
    
    git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@351926 91177308-0d34-0410-b5e6-96231b3b80d8

**Comment by nunoplopes** [comment]
still repros @max-quazan

**Comment by max-quazan** [comment]
Sorry I should have missed that before, will take a look now.

**Comment by max-quazan** [comment]
```
commit 0e465c0c2f898f4fa730207c342459918d44e5e3 (HEAD -> main, origin/main, origin/HEAD)
Author: Max Kazantsev <mkazantsev@azul.com>
Date:   Mon Sep 12 15:50:28 2022 +0700

    [IRCE] Bail in case of pointer types. PR40539

    We should not unconditionally expect that SCEVable types are all integers
    because SCEV can also be computed for pointers. Bail in this case.
```

**Comment by mikaelholmen** [comment]
Thanks!
