### ISSUE TITLE
building static library fails with glibc 2.29 (does not export ustat in libc.a)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#40545]
|  |  |
| --- | --- |
| Bugzilla Link | [41200](https://llvm.org/bz41200) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Building the current git llgo in static library mode fails with an undefined symbol to ustat. glibc 2.29 does not export ustat in libc.a, only in libc.so (and even there it is marked as legacy and deprecated and it will probably go away soon).

I recommend not providing a ustat API in Go. The man page for ustat recommends using statfs instead.

**Comment by xgupta** [comment]
llgo is not in the repo anymore.
