### ISSUE TITLE
modernize-use-equals-default is triggered on functions that contain conditionally compiled code

### ISSUE THREAD

**Issue by igor-akhmetov** [llvm/llvm-project#40554]
|  |  |
| --- | --- |
| Bugzilla Link | [41209](https://llvm.org/bz41209) |
| Version | unspecified |
| OS | Windows NT |

## Extended Description 
clang-tidy suggests to replace the body of X::~X with '= default':

struct X
{
    ~X()
    {
#if FOO
        DoSomething();
#endif
    }
};

**Comment by PiotrZSL** [comment]
Reproduced on trunk.

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D146882
