### ISSUE TITLE
Assertion in clang::CodeGen::CGRecordLayout::getLLVMFieldNo for Swift code importing C library

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#40578]
|  |  |
| --- | --- |
| Bugzilla Link | [41233](https://llvm.org/bz41233) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
As per report at https://bugs.swift.org/browse/SR-9589:

Assertion is:

unsigned int clang::CodeGen::CGRecordLayout::getLLVMFieldNo(const clang::FieldDecl *) const: Assertion `FieldInfo.count(FD) && "Invalid field for record!"' failed.

Brief test case reproducing issue at https://github.com/tokyovigilante/WaylandTest (requires running under a Wayland compositor, I'm using Fedora 30 with Sway but Gnome Shell should also work).

**Comment by Endilll** [comment]
No preprocessed source is provided.
