### ISSUE TITLE
bugprone-exception-escape generated for destructor marked with noexcept(false)

### ISSUE THREAD

**Issue by Flamefire** [llvm/llvm-project#40583]
|  |  |
| --- | --- |
| Bugzilla Link | [41238](https://llvm.org/bz41238) |
| Version | unspecified |
| OS | Linux |
| CC | @EugeneZelenko |

## Extended Description 
There are use cases where a destructor is intended to throw under certain conditions. For an example see e.g. http://blog.sduto.it/2014/05/a-c-error-handling-style-that-plays.html

TLDR: A RAII style classed used to encapsulate a possible error conditions that throws an exception if the error occurred  and is hence marked `noexcept(false)`

But clang-tidy still generates a bugprone-exception-escape in this situation which is a false positive.

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D145865
