### ISSUE TITLE
Compiling Core/IOHandler.cpp is missing -I/usr/include/ncurses.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#40640]
|  |  |
| --- | --- |
| Bugzilla Link | [41295](https://llvm.org/bz41295) |
| Version | 8.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
To compile LLDB 8.0.0 I had to change in source/Core/IOHandler.cpp:

#ifndef LLDB_DISABLE_CURSES
#include <ncurses/curses.h>
#include <ncurses/panel.h>
#endif

In the original ncurses was missing and my system does not have /usr/include/curses.h or /usr/local/include/curses.h.  This means that the cmake system has to check more intensively where curses.h is installed and pass the right CFLAGS.

This could be also /usr/local/include/ncursesw.

**Comment by arsenm** [comment]
Old build issue
