### ISSUE TITLE
Link gtest with -pthread

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#40642]
|  |  |
| --- | --- |
| Bugzilla Link | [41297](https://llvm.org/bz41297) |
| Version | 8.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
To compile LLVM I had to add to build800/utils/unittest/CMakeFiles/gtest.dir/link.txt -pthread.

**Comment by arsenm** [comment]
Old build issue
