### ISSUE TITLE
__clang_call_terminate doesn't have unwind table with -funwind-tables

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#40696]
|  |  |
| --- | --- |
| Bugzilla Link | [41351](https://llvm.org/bz41351) |
| Version | unspecified |
| OS | Windows NT |
| CC | @compnerd,@francisvm,@froydnj,@zygoloid |

## Extended Description 
C++ testcase:

void target(void f()) noexcept { f(); }

If you compile this with "--target=aarch64-eabi -funwind-tables", the unwind tables are missing for __clang_call_terminate.  I think it's somehow forgetting to attach the uwtable attribute to the definition of __clang_call_terminate.

**Comment by xgupta** [comment]
Hi @efriedma-quic,

I have tried this command - 
./clang --target=aarch64-eabi -funwind-tables test.cpp -c -o clang-arm.o
llvm-objdump -D clang-arm.o  > clang-arm

with clang-arm is uploaded here - https://gist.github.com/xgupta/ad644b69ab8e8ec9a30a8a5281d74d3d

It does have eh_frame section. what should be the expectation here?

**Comment by efriedma-quic** [comment]
The function target() has an unwind table; the issue is that the synthesized function __clang_call_terminate doesn't.
