### ISSUE TITLE
[NVPTX] Incorrect lowering for llvm.fshl intrinsic

### ISSUE THREAD

**Issue by eae433e4-f8ea-4bbf-b40e-edf03c2e099b** [llvm/llvm-project#40692]
|  |  |
| --- | --- |
| Bugzilla Link | [41347](https://llvm.org/bz41347) |
| Version | trunk |
| OS | All |
| CC | @hfinkel |

## Extended Description 
The llvm.fshl intrinsic is supposed to behave like a rotate left operation when the first two operands are the same. The PTX backend seems to generate code that doesn't account for the shift amount being larger than the element size (explicitly called out by the LLVM reference manual).

Example LLVM snippet:

```
target datalayout = "e-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64"

; Function Attrs: noinline nounwind
define i64 @&#8203;test_rotate(i64 %y) {
entry:
  %x = tail call i64 @&#8203;llvm.fshl.i64(i64 72340172838076673, i64 72340172838076673, i64 %y)
  ret i64 %x
}

; Function Attrs: nounwind readnone speculatable
declare i64 @&#8203;llvm.fshl.i64(i64, i64, i64)
```

This produces the following PTX:

```
//
// Generated by LLVM NVPTX Back-End
//

.version 3.2
.target sm_20
.address_size 64

        // .globl       test_rotate     // -- Begin function test_rotate
                                        // @&#8203;test_rotate
.visible .func  (.param .b64 func_retval0) test_rotate(
        .param .b64 test_rotate_param_0
)
{
        .reg .b32       %r<2>;
        .reg .b64       %rd<3>;

// %bb.0:                               // %entry
        ld.param.u32    %r1, [test_rotate_param_0];
        mov.u64         %rd1, 72340172838076673;
        {
        .reg .b64 %lhs;
        .reg .b64 %rhs;
        .reg .u32 %amt2;
        shl.b64         %lhs, %rd1, %r1;
        sub.u32         %amt2, 64, %r1;
        shr.b64         %rhs, %rd1, %amt2;
        add.u64         %rd2, %lhs, %rhs;
        }
        st.param.b64    [func_retval0+0], %rd2;
        ret;
                                        // -- End function
}
```

Running this with an argument >64 just produces a result of zero.

**Comment by JOE1994** [comment]
[LangRef section for `llvm.fshl.*` intrinsic](https://llvm.org/docs/LangRef.html#llvm-fshl-intrinsic) says the following:

> The shift argument is treated as an unsigned amount modulo the element size of the arguments.

Given this assumption, the PTX code generated from OP's example is correct
as the compiler needn't worry about cases where the "shift" argument is larger than 64.
It is the user's responsibility to feed the appropriate "shift" argument value.
