### ISSUE TITLE
[dr2026] clang++ accepts self-referring static member initialization

### ISSUE THREAD

**Issue by eyalroz** [llvm/llvm-project#40713]
|  |  |
| --- | --- |
| Bugzilla Link | [41368](https://llvm.org/bz41368) |
| Version | 8.0 |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
GodBolt example: https://godbolt.org/z/1orC3P
StackOverflow question (which started out differently): https://stackoverflow.com/q/55505257/1593077

Consider the following code:
```cpp
  struct bar { static const bool value = !bar::value; };
```
This should not compile; and indeed, it doesn't - with GCC and with MSVC. Yet clang++ is somehow willing to take a default-initialization value for bar::value before it has actually been initialized. I am not a C++ language lawyer, but I'm sure that's wrong.

**Comment by frederick-vs-ja** [comment]
Fixed in Clang 11 by commit 96c899449b61b866b583560a49c4627f561336fc.
