### ISSUE TITLE
Bogus readability-non-const-parameter inspection

### ISSUE THREAD

**Issue by maxim-banaev** [llvm/llvm-project#40738]
|  |  |
| --- | --- |
| Bugzilla Link | [41393](https://llvm.org/bz41393) |
| Version | unspecified |
| OS | All |
| CC | @michaellass,@EugeneZelenko,@wolframroesler |

## Extended Description 
readability-non-const-parameter incorrectly triggers here:

#include <stdlib.h>

typedef struct S {
	int* x;
} S;
S* new_s(int* x) {
	S* s = malloc(sizeof(S));
	*s = (S) { x };
	return s;
}

$clang-tidy -checks='readability-non-const-parameter' test.cpp

warnings
test.cpp:10:12: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
   *s = (S){x};
            ^

**Comment by carlosgalvezp** [comment]
Cannot reproduce on trunk (as a matter of fact I get a compiler error)
