### ISSUE TITLE
Analysis not updated after running a CallGraphSCCPass.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#4075]
|  |  |
| --- | --- |
| Bugzilla Link | [3703](https://llvm.org/bz3703) |
| Version | unspecified |
| OS | All |
| Attachments | [Testcase to reproduce the problem.](https://user-images.githubusercontent.com/60944935/143738973-fa8dfa48-9bc5-4412-8578-ca24e038014b.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lattner,@tlattner |

## Extended Description 

The attached Hello.cpp file illustrates my problem. Replace the original Hello.cpp on the LLVM tree with that one, build and then run (assuming you are on Darwin):

$ ./Debug/bin/opt --debug-pass=Structure --load LLVMHello.dylib -mysccpass -hello -f -o t2.bc t.bc
Pass Arguments:  -myanalysis -basiccg -mysccpass -hello -preverify -domtree -verify
Target Data Layout
  ModulePass Manager
    My Analysis
    Basic CallGraph Construction
    Call Graph SCC Pass Manager
      My SCCPass
    Hello World Pass
    FunctionPass Manager
      Preliminary module verification
      Dominator Tree Construction
      Module Verifier
    Bitcode Writer
 -- Done running MyAnalysis
 -- Done running MySCCPass
 -- Done running Hello

As you can see above, MyAnalysis is not re-run after MySCCPass, even though MySCCPass is not marking the analysis as beeing preserved. I was expecting it would be re-run so Hello can start with a valid analysis.

Thanks,
Julien

**Comment by arsenm** [comment]
Old pass manager
