### ISSUE TITLE
ICE on deducing type of template static class field

### ISSUE THREAD

**Issue by 07db8777-e875-47a6-8e13-f3ee3e0342de** [llvm/llvm-project#40760]
|  |  |
| --- | --- |
| Bugzilla Link | [41415](https://llvm.org/bz41415) |
| Version | trunk |
| OS | All |
| CC | @zygoloid,@willwray |

## Extended Description 
```cpp
template<typename, typename>
bool is_same_v = false;

template<typename T>
struct X {
    template <typename U>
    static const auto a = is_same_v<T, U>;
    
    static const auto b = a<void>;
};

void test() {
    X<void>::b;
}
```
Will compile if specify a type of `a` or `b` explicitly. Reproduced in versions 7.0, 8.0 and trunk: https://gcc.godbolt.org/z/Gzt6IC

**Comment by Endilll** [comment]
Appears to be fixed in Clang 9, does not reproduce on trunk (19.0): https://gcc.godbolt.org/z/c5r5s4GKs
