### ISSUE TITLE
Clang fails with segfault for unknown reason

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#40785]
|  |  |
| --- | --- |
| Bugzilla Link | [41440](https://llvm.org/bz41440) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @TNorthover |

## Extended Description 
Pretty sure something's wrong with my CMake compilation options, but I have to make sure it's not something else, possibly.

My distro is Arch Linux, and I'm building from a slightly modified version of https://aur.archlinux.org/packages/llvm-git/

Segfault:

https://invent.kde.org/snippets/133

PKGBUILD with CMake command and relevant options is here:

https://invent.kde.org/snippets/141#L110

**Comment by Endilll** [comment]
Core dump alone makes it quite hard to debug.
