### ISSUE TITLE
Invalid error "member reference base type "T" is not a structure or union"

### ISSUE THREAD

**Issue by elvenfighter** [llvm/llvm-project#40795]
|  |  |
| --- | --- |
| Bugzilla Link | [41450](https://llvm.org/bz41450) |
| Version | trunk |
| OS | Windows NT |
| CC | @elvenfighter,@zygoloid |

## Extended Description 
Consider the following code:

  template <typename T>
  struct Check {
    explicit Check(T) {}
    auto copy() const { return *this; } 
  };

  int main() {
    static_cast<void>([](const auto& range) {
      Check{range}.copy();
    });
  }

Clang issues an error:

  prog.cc:9:17: error: member reference base type 'Check' is not a structure or union
      Check{range}.copy();
      ~~~~~~~~~~~~^~~~~

The error is clearly invalid. The code should be compilable.
Sandbox is available on Wandbox: https://wandbox.org/permlink/9ImPrkZ90K9ZM2QL

In order for the fragment above to work, the problem line should be rewritten as follows:

      Check c{range};
      std::move(c).copy();

**Comment by wheatman** [comment]
This was fixed between 11.0.1 and 12.0.0
https://gcc.godbolt.org/z/MPY4xMr56
code, compile with `-std=c++17`
```cpp
  template <typename T>
  struct Check {
    explicit Check(T) {}
    auto copy() const { return *this; } 
  };

  int main() {
    static_cast<void>([](const auto& range) {
      Check{range}.copy();
    });
  }

```

old error
```
<source>:9:19: error: member reference base type 'Check' is not a structure or union
      Check{range}.copy();
      ~~~~~~~~~~~~^~~~~
1 error generated.
Compiler returned: 1
```
