### ISSUE TITLE
Missing optimization, elimination of empty data dependant loops

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#40842]
|  |  |
| --- | --- |
| Bugzilla Link | [41497](https://llvm.org/bz41497) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hfinkel,@riccibruno,@zygoloid |

## Extended Description 
```
void * x;
void test(){ for(void * p = x; p; p=*(void**)p); }
```

With -O3 gives:

test():                               # @&#8203;test()
        mov     rax, qword ptr [rip + x]
        test    rax, rax
        je      .LBB0_3
.LBB0_1:                                # =>This Inner Loop Header: Depth=1
        mov     rax, qword ptr [rax]
        test    rax, rax
        jne     .LBB0_1
.LBB0_3:
        ret

As you can see it currently traverses pointers even though it could be optimized away. 

6.8.2.2 Forward progress
The implementation may assume that any thread will eventually do one of the following:

    (1.1) terminate,
    (1.2) make a call to a library I/O function,
    (1.3) perform an access through a volatile glvalue, or
    (1.4) perform a synchronization operation or an atomic operation.

[ Note: This is intended to allow compiler transformations such as removal of empty loops, even when termination cannot be proven. — end note ]

**Comment by Ignition** [comment]
As of clang 12 this was fixed
