### ISSUE TITLE
Assertion failed: (OuterL->isLCSSAForm(*DT) && "Loops should be in LCSSA form after loop-unroll.")

### ISSUE THREAD

**Issue by antonrang** [llvm/llvm-project#40950]
|  |  |
| --- | --- |
| Bugzilla Link | [41605](https://llvm.org/bz41605) |
| Version | 3.9 |
| OS | FreeBSD |
| Attachments | [preprocessed file causing the crash](https://user-images.githubusercontent.com/95090585/143759076-30929cfb-706a-4c57-bc80-71d2bf9a61b8.gz) |
| CC | @fhahn |

## Extended Description 

While building erlang on our FreeBSD variant, with a lightly modified FreeBSD clang 3.9.1 (which adds some format checking for a private printf-like mechanism but is otherwise unchanged), we hit an assertion failure.

gmake[4]: Entering directory `/mnt/erlang/erts/emulator'
if utils/gen_git_version x86_64-unknown-freebsd12.0/gen_git_version.mk; then touch beam/erl_bif_info.c; fi
cc  -Werror=undef -Werror=implicit -Werror=return-type  -g  -O3 -fomit-frame-pointer -I/mnt/erlang/erts/x86_64-unknown-freebsd12.0    -DHAVE_CONFIG_H -Wall -Wstrict-prototypes -Wmissing-prototypes -Wdeclaration-after-statement -DUSE_THREADS -D_THREAD_SAFE -D_REENTRANT -DPOSIX_THREADS   -Ix86_64-unknown-freebsd12.0/opt/smp -Ibeam -Isys/unix -Isys/common -Ix86_64-unknown-freebsd12.0 -Ipcre -Ihipe -I../include -I../include/x86_64-unknown-freebsd12.0 -I../include/internal -I../include/internal/x86_64-unknown-freebsd12.0 -c beam/beam_emu.c -o obj/x86_64-unknown-freebsd12.0/opt/smp/beam_emu.o
Assertion failed: (OuterL->isLCSSAForm(*DT) && "Loops should be in LCSSA form after loop-unroll."), function UnrollLoop, file /b/mnt/src/contrib/llvm/lib/Transforms/Utils/LoopUnroll.cpp, line 680.
cc: error: unable to execute command: Abort trap (core dumped)
cc: error: clang frontend command failed due to signal (use -v to see invocation)
FreeBSD clang version 3.9.1 (tags/RELEASE_391/final 289601) (based on LLVM 3.9.1)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin
cc: note: diagnostic msg: PLEASE submit a bug report to https://bugs.freebsd.org/submit/ and include the crash backtrace, preprocessed source, and associated run script.
cc: note: diagnostic msg:

Unfortunately we didn't have symbols for clang available, so don't have a full backtrace.

This could conceivably be the same cause as bug 27838, but we haven't had the opportunity to try the patch from there.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 4: https://godbolt.org/z/KrfoM38n1
Reduced by C-Reduce:
```cpp
process_main_x_reg_array_I, process_main_x_reg_array_arity;
erts_proc_raw_trylock__() {
  while (1) {
    int lflgs = ethr_atomic32_cmpxchg_acqb();
    if (lflgs)
      return 0;
  }
}
process_main_x_reg_array() {
  int *reg;
  void *opcodes[] = {&&lb_i_put_tuple_yI, &&lb_i_select_val_bins_yfI};
do_schedule:;
  int i;
  for (; i >= 0; i--)
    reg[i] = 1;
lb_i_put_tuple_yI:
  do {
    int term = process_main_x_reg_array_I++;
    switch (term)
    case 0:
      ++reg;
  } while (--process_main_x_reg_array_arity);
  goto * 0;
lb_i_select_val_bins_yfI:
  erts_proc_raw_trylock__();
  goto do_schedule;
}

```
