### ISSUE TITLE
typo in clang static analyzer GenericTaintChecker.cpp

### ISSUE THREAD

**Issue by KnoooW** [llvm/llvm-project#41]
ArgNum = 0;
    else if (C.isCLibraryFunction(FDecl, "memccpy"))
      ArgNum = 3;
    else if (C.isCLibraryFunction(FDecl, "realloc"))
      ArgNum = 1;
 

here line 812 in GenericTaintChecker.cpp, 'memccpy' should be 'memcpy'

**Comment by jyknight** [comment]
That's actually intentional, memccpy is a different function.
http://man7.org/linux/man-pages/man3/memccpy.3.html

**Comment by KnoooW** [comment]
omg... thanks
