### ISSUE TITLE
Some tests fail when specifying `-debug_level=X` via lit

### ISSUE THREAD

**Issue by mclow** [llvm/llvm-project#41030]
|  |  |
| --- | --- |
| Bugzilla Link | [41685](https://llvm.org/bz41685) |
| Version | unspecified |
| OS | All |
| CC | @mclow |

## Extended Description 
Running lit with --param="debug_level=1" causes the following tests to fail:

    libc++ :: std/algorithms/alg.sorting/alg.merge/inplace_merge_comp.pass.cpp
    libc++ :: std/containers/sequences/vector/iterators.pass.cpp
    libc++ :: std/input.output/filesystems/class.path/path.nonmember/path.factory.pass.cpp
    libc++ :: std/input.output/filesystems/fs.op.funcs/fs.op.proximate/proximate.pass.cpp
    libc++ :: std/strings/basic.string/string.modifiers/string_assign/iterator.pass.cpp

Some of these (like the first one) should be easy to fix.

The "iterators" ones appear to be because the debug infrastructure has not been updated to deal with N3644, which added the fact that default-constructed iterators are equivalent to all container's end iterator.

I don't know what's up with the filesystem tests.

**Comment by ldionne** [comment]
This has been fixed now, and we test it in the CI (although the way we enable this now has changed).
