### ISSUE TITLE
coroutines: escaping alloca is not included in coroutine frame

### ISSUE THREAD

**Issue by aykevl** [llvm/llvm-project#41087]
|  |  |
| --- | --- |
| Bugzilla Link | [41742](https://llvm.org/bz41742) |
| Version | trunk |
| OS | Linux |
| CC | @hfinkel |

## Extended Description 
The alloca (n.alloca) in the following function is not included in the coroutine frame, while I think it should.

define i8* @&#8203;f(i32 %n) {
entry:
  %id = call token @&#8203;llvm.coro.id(i32 0, i8* null, i8* null, i8* null)
  %size = call i32 @&#8203;llvm.coro.size.i32()
  %alloc = call i8* @&#8203;malloc(i32 %size)
  %hdl = call noalias i8* @&#8203;llvm.coro.begin(token %id, i8* %alloc)
  %n.alloca = alloca i32
  store i32 %n, i32* %n.alloca
  store i32* %n.alloca, i32** @&#8203;G
  br label %loop
loop:
  %n.val = call i32 @&#8203;next()
  call void @&#8203;print(i32 %n.val)
  %0 = call i8 @&#8203;llvm.coro.suspend(token none, i1 false)
  switch i8 %0, label %suspend [i8 0, label %loop
                                i8 1, label %cleanup]
cleanup:
  %mem = call i8* @&#8203;llvm.coro.free(token %id, i8* %hdl)
  call void @&#8203;free(i8* %mem)
  br label %suspend
suspend:
  %unused = call i1 @&#8203;llvm.coro.end(i8* %hdl, i1 false)
  ret i8* %hdl
}

This is the IR that shows the alloca that is not included in the frame:

define i8* @&#8203;f(i32 %n) {
entry:
  %id = call token @&#8203;llvm.coro.id(i32 0, i8* null, i8* bitcast (i8* (i32)* @&#8203;f to i8*), i8* bitcast ([3 x void (%f.Frame*)*]* @&#8203;f.resumers to i8*))
  %alloc = call i8* @&#8203;malloc(i32 24)
  %hdl = call noalias nonnull i8* @&#8203;llvm.coro.begin(token %id, i8* %alloc)
  %FramePtr = bitcast i8* %hdl to %f.Frame*
  %resume.addr = getelementptr inbounds %f.Frame, %f.Frame* %FramePtr, i32 0, i32 0
  store void (%f.Frame*)* @&#8203;f.resume, void (%f.Frame*)** %resume.addr
  %destroy.addr = getelementptr inbounds %f.Frame, %f.Frame* %FramePtr, i32 0, i32 1
  store void (%f.Frame*)* @&#8203;f.destroy, void (%f.Frame*)** %destroy.addr
  %n.alloca = alloca i32
  store i32 %n, i32* %n.alloca
  store i32* %n.alloca, i32** @&#8203;G
  call void @&#8203;coro.devirt.trigger(i8* null)
  %n.val = call i32 @&#8203;next()
  call void @&#8203;print(i32 %n.val)
  %index.addr1 = getelementptr inbounds %f.Frame, %f.Frame* %FramePtr, i32 0, i32 3
  store i1 false, i1* %index.addr1
  ret i8* %hdl
}

My understanding is that all local variables that may be live across a suspend point, should be included in the coroutine frame. In this case, %n.alloca escapes from the function so it should be considered live in all basic blocks that dominate the alloca.

Full source code:
https://gist.github.com/aykevl/7b72e0f5632736149445927a09cd0c2b
I created coro.opt.bc with:
  opt-9 -o coro.opt.bc -coro-early -coro-split -coro-elide coro.ll

**Comment by ChuanqiXu9** [comment]
This may be fixed in trunk.
