### ISSUE TITLE
bad line number DiagnosticInfoInlineAsm::DiagnosticInfoInlineAsm

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#41080]
|  |  |
| --- | --- |
| Bugzilla Link | [41735](https://llvm.org/bz41735) |
| Version | trunk |
| OS | Linux |
| Attachments | [br_forward.ll](https://user-images.githubusercontent.com/1823839/143759141-e20f1395-7952-4121-8cb1-28364998a9ea.gz) |
| CC | @stephenhines |

## Extended Description 

$ llc -mtriple aarch64-linux-gnu br_forward.ll
error: invalid operand for inline asm constraint 'i' at line 2148965563
$ wc -l br_forward.ll
943 br_forward.ll

**Comment by xgupta** [comment]
different error on trunk - https://godbolt.org/z/5qqsTxM79.
llc: error: '<source>': input module cannot be verified.

**Comment by xgupta** [comment]
Till llc -14.0.0 attached reproducer passing https://godbolt.org/z/dshz5KGaM and after that error: module cannot be verified.
