### ISSUE TITLE
In function: __mulxc3 Cannot select: 0x55d58830cbf0: f80 = ConstantFP<APFloat(604462909807314587353088)>

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#41094]
|  |  |
| --- | --- |
| Bugzilla Link | [41749](https://llvm.org/bz41749) |
| Version | 8.0 |
| OS | Linux |
| Attachments | [bugpoint-reduced-simplified.bc](https://user-images.githubusercontent.com/60944935/143759148-0fd9dfeb-20fe-4f93-9c69-45b15f09fa52.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @topperc,@RKSimon,@rotateright |

## Extended Description 

Clang 7 as well as Clang 8 ran into errors while compiling the respective compiler-rt.

Tracing the bug led me to a crashing llc:

    > llc -asm-show-inst -asm-verbose bugpoint-reduced-simplified.bc
    LLVM ERROR: Cannot select: 0x55d58830cbf0: f80 = ConstantFP<APFloat(604462909807314587353088)>
    In function: __mulxc3

The .bc file is attached.

**Comment by RKSimon** [comment]
Tentatively closing - we never got a repro

I added test coverage at 289b8e0d2fc6747543ee3dce829f148900f437bc
