### ISSUE TITLE
lld documentation build fails with TemplateNotFound on Python 3.7/Sphinx 2.0.1

### ISSUE THREAD

**Issue by tycho** [llvm/llvm-project#41134]
|  |  |
| --- | --- |
| Bugzilla Link | [41789](https://llvm.org/bz41789) |
| Version | unspecified |
| OS | Linux |
| Attachments | [output of sphinx-build with -v -v arguments](https://user-images.githubusercontent.com/92601265/143759162-c89324d3-4c65-4baf-8b97-3ab39d45c768.gz) |
| CC | @smithp35 |

## Extended Description 

I'm trying to build the current release_80 branch of lld, but the build failed around generating the Sphinx documentation:

-----
lld $ mkdir build; cd build
lld/build $ cmake -G Ninja .. -DLLVM_BUILD_DOCS=ON -DLLVM_ENABLE_SPHINX=ON
lld/build $ ninja docs/all
[1/1] Generating html Sphinx documentation for lld into "/home/steven/lld-t/build/docs/html"
FAILED: docs/CMakeFiles/docs-lld-html 
cd /home/steven/lld-t/build/docs && /usr/bin/sphinx-build -b html -d /home/steven/lld-t/build/docs/_doctrees-lld-html -q -W /home/steven/lld-t/docs /home/steven/lld-t/build/docs/html

Theme error:
An error happened in rendering the page index.
Reason: TemplateNotFound()
ninja: build stopped: subcommand failed.
-----

I tried running sphinx-build without -q and with -v -v (output attached). It's complaining about a missing template called "i", which strace shows it's trying to access as well:

32385 stat("/usr/lib/python3.7/site-packages/sphinx/themes/basic/page.html", {st_mode=S_IFREG|0644, st_size=273, ...}) = 0
32385 stat("/home/steven/lld-t/docs/_templates/layout.html", {st_mode=S_IFREG|0644, st_size=305, ...}) = 0
32385 stat("/home/steven/lld-t/docs/llvm-theme/layout.html", {st_mode=S_IFREG|0644, st_size=569, ...}) = 0
32385 stat("/usr/lib/python3.7/site-packages/sphinx/themes/basic/../basic/layout.html", {st_mode=S_IFREG|0644, st_size=7811, ...}) = 0
32385 openat(AT_FDCWD, "/home/steven/lld-t/docs/_templates/i", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
32385 openat(AT_FDCWD, "/home/steven/lld-t/docs/llvm-theme/i", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
32385 openat(AT_FDCWD, "/usr/lib/python3.7/site-packages/sphinx/themes/basic/i", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
32385 openat(AT_FDCWD, "/home/steven/lld-t/docs/llvm-theme/../i", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
32385 openat(AT_FDCWD, "/usr/lib/python3.7/site-packages/sphinx/themes/basic/../i", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

If I run the Python 2.7 version of Sphinx, it builds without any errors. I note that I have two different versions of Sphinx installed (1.8.5 for Python 2.7 and 2.0.1 for Pyton 3.7). Maybe a problem with Sphinx v2.0.x?

**Comment by arsenm** [comment]
Old build issue
