### ISSUE TITLE
Rejects valid on deprecated attributes with a non-narrow string literal

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#41213]
|  |  |
| --- | --- |
| Bugzilla Link | [41868](https://llvm.org/bz41868) |
| Version | unspecified |
| OS | Windows NT |
| CC | @DougGregor,@zygoloid |

## Extended Description 
The following code is valid in C2x and C++11, but is currently rejected by Clang:
```cpp
[[deprecated(L"We can't have nice things")]] int a;
```
The problem is that `Sema::checkStringLiteralArgumentAttr()` requires the string to be ASCII so that it can call `StringLiteral::getString()` to get a `StringRef` to the contents. We could use `StringLiteral::outputString()` to stream it to a string buffer, but there are other parts of the APIs that expect a `StringRef` and not a std::string, so `ClangAttrEmitter` would need to be taught about this for `VariadicStringArgument` arguments.

I think we might want to encode this as part of the attribute argument declaration itself. Some attributes may require any form of string literal (like deprecated does), while others may require ASCII (like section attributes).

**Comment by frederick-vs-ja** [comment]
I believe this is eventually fixed in Clang 18 by commit 49e0495febec5b88dcbc3c0a8814441e207bd608 (https://reviews.llvm.org/D156596) ([Godbolt link](https://godbolt.org/z/KGadWc68h)).
