### ISSUE TITLE
many check-fuzzer tests on linux when using the monorepo

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#41232]
|  |  |
| --- | --- |
| Bugzilla Link | [41887](https://llvm.org/bz41887) |
| Version | trunk |
| OS | Linux |
| Attachments | [ninja check-fuzzer log](https://user-images.githubusercontent.com/1148786/143759207-1282163b-cbbc-4382-9cca-8346ee50bbb7.gz) |

## Extended Description 
I don't know if my machine is cursed in some way, but running "check-fuzzer" in a monorepo build on my google linux workstations leads to many test failures. Is it just me? It looks like they're hitting an internal ld.bfd error :-/

$ git clone --depth 1 https://github.com/llvm/llvm-project/ && mkdir llvm-project/build && cd llvm-project/build && cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_PROJECTS="clang;compiler-rt;lld" ../llvm && ninja check-fuzzer

[...]

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
FAIL: libFuzzer :: large.test (114 of 114)
******************** TEST 'libFuzzer :: large.test' FAILED ********************
Script:
--
: 'RUN: at line 2';     /tmp/nanana/llvm-project/build/./bin/clang  --driver-mode=g++ -std=c++11 -O2 -gline-tables-only -fsanitize=address,fuzzer -I/tmp/nanana/llvm-project/compiler-rt/lib/fuzzer -m32 /tmp/nanana/llvm-project/compiler-rt/test/fuzzer/LargeTest.cpp -o /tmp/nanana/llvm-project/build/projects/compiler-rt/test/fuzzer/I386DefaultLinuxConfig/Output/large.test.tmp-LargeTest
: 'RUN: at line 3';    /tmp/nanana/llvm-project/build/projects/compiler-rt/test/fuzzer/I386DefaultLinuxConfig/Output/large.test.tmp-LargeTest -runs=10000
: 'RUN: at line 4';   env ASAN_OPTIONS=handle_segv=0  /tmp/nanana/llvm-project/build/projects/compiler-rt/test/fuzzer/I386DefaultLinuxConfig/Output/large.test.tmp-LargeTest -runs=10000 -lazy_counters=1 2>&1 | FileCheck /tmp/nanana/llvm-project/compiler-rt/test/fuzzer/large.test
: 'RUN: at line 5';                                 /tmp/nanana/llvm-project/build/projects/compiler-rt/test/fuzzer/I386DefaultLinuxConfig/Output/large.test.tmp-LargeTest -runs=10000 -lazy_counters=1 2>&1 | FileCheck /tmp/nanana/llvm-project/compiler-rt/test/fuzzer/large.test
--
Exit Code: 1

Command Output (stderr):
--
/usr/bin/ld: internal error ../../ld/ldlang.c 6635
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)

--

********************
Testing Time: 18.57s
********************
Failing Tests (97):
    libFuzzer :: acquire-crash-state.test
    libFuzzer :: bad-strcmp.test
    libFuzzer :: bogus-initialize.test
    libFuzzer :: buffer-overflow-on-input.test
    libFuzzer :: caller-callee.test
    libFuzzer :: cleanse.test
    libFuzzer :: counters.test
    libFuzzer :: coverage.test
    libFuzzer :: cross_over.test
    libFuzzer :: cxxstring.test
    libFuzzer :: deep-recursion.test
    libFuzzer :: deprecated-instrumentation.test
    libFuzzer :: disable-leaks.test
    libFuzzer :: dso.test
    libFuzzer :: exit-report.test
    libFuzzer :: exit_on_src_pos.test
    libFuzzer :: extra-counters.test
    libFuzzer :: features_dir.test
    libFuzzer :: fork-sigusr.test
    libFuzzer :: fork-ubsan.test
    libFuzzer :: fork.test
    libFuzzer :: full-coverage-set.test
    libFuzzer :: fuzzer-alignment-assumption.test
    libFuzzer :: fuzzer-customcrossover.test
    libFuzzer :: fuzzer-customcrossoverandmutate.test
    libFuzzer :: fuzzer-custommutator.test
    libFuzzer :: fuzzer-dict.test
    libFuzzer :: fuzzer-dirs.test
    libFuzzer :: fuzzer-fdmask.test
    libFuzzer :: fuzzer-finalstats.test
    libFuzzer :: fuzzer-flags.test
    libFuzzer :: fuzzer-implicit-integer-sign-change.test
    libFuzzer :: fuzzer-implicit-signed-integer-truncation-or-sign-change.test
    libFuzzer :: fuzzer-implicit-signed-integer-truncation.test
    libFuzzer :: fuzzer-implicit-unsigned-integer-truncation.test
    libFuzzer :: fuzzer-leak.test
    libFuzzer :: fuzzer-oom-with-profile.test
    libFuzzer :: fuzzer-oom.test
    libFuzzer :: fuzzer-printcovpcs.test
    libFuzzer :: fuzzer-runs.test
    libFuzzer :: fuzzer-seed.test
    libFuzzer :: fuzzer-segv.test
    libFuzzer :: fuzzer-singleinputs.test
    libFuzzer :: fuzzer-threaded.test
    libFuzzer :: fuzzer-timeout.test
    libFuzzer :: fuzzer-ubsan.test
    libFuzzer :: initialize.test
    libFuzzer :: large.test
    libFuzzer :: len_control.test
    libFuzzer :: libcxx.test
    libFuzzer :: max-number-of-runs.test
    libFuzzer :: memcmp.test
    libFuzzer :: memcmp64.test
    libFuzzer :: merge-control-file.test
    libFuzzer :: merge-posix.test
    libFuzzer :: merge-sigusr.test
    libFuzzer :: merge.test
    libFuzzer :: minimize_crash.test
    libFuzzer :: minimize_two_crashes.test
    libFuzzer :: not-instrumented.test
    libFuzzer :: null-deref-on-empty.test
    libFuzzer :: null-deref.test
    libFuzzer :: overwrite-input.test
    libFuzzer :: print-func.test
    libFuzzer :: read-binary.test
    libFuzzer :: recommended-dictionary.test
    libFuzzer :: reduce_inputs.test
    libFuzzer :: reload.test
    libFuzzer :: repeated-bytes.test
    libFuzzer :: seed_inputs.test
    libFuzzer :: shrink.test
    libFuzzer :: sigusr.test
    libFuzzer :: simple.test
    libFuzzer :: strcmp.test
    libFuzzer :: strncmp-oob.test
    libFuzzer :: strncmp.test
    libFuzzer :: strstr.test
    libFuzzer :: swap-cmp.test
    libFuzzer :: symbolize-deadlock.test
    libFuzzer :: target-function.test
    libFuzzer :: three-bytes.test
    libFuzzer :: trace-malloc-2.test
    libFuzzer :: trace-malloc-threaded.test
    libFuzzer :: trace-malloc-unbalanced.test
    libFuzzer :: trace-malloc.test
    libFuzzer :: ulimit.test
    libFuzzer :: value-profile-cmp.test
    libFuzzer :: value-profile-cmp2.test
    libFuzzer :: value-profile-cmp3.test
    libFuzzer :: value-profile-cmp4.test
    libFuzzer :: value-profile-div.test
    libFuzzer :: value-profile-load.test
    libFuzzer :: value-profile-mem.test
    libFuzzer :: value-profile-set.test
    libFuzzer :: value-profile-strcmp.test
    libFuzzer :: value-profile-strncmp.test
    libFuzzer :: value-profile-switch.test

  Expected Passes    : 4
  Unsupported Tests  : 13
  Unexpected Failures: 97
FAILED: projects/compiler-rt/test/fuzzer/CMakeFiles/check-fuzzer-default-i386

**Comment by Endilll** [comment]
@zmodem Are you still experiencing this on trunk?

**Comment by zmodem** [comment]
> @zmodem Are you still experiencing this on trunk?

No, let's close this. Thanks for checking!
