### ISSUE TITLE
Fix llvm-objdump -r behaviour for non relocatable objects

### ISSUE THREAD

**Issue by jh7370** [llvm/llvm-project#41246]
|  |  |
| --- | --- |
| Bugzilla Link | [41901](https://llvm.org/bz41901) |
| Version | trunk |
| OS | Windows NT |

## Extended Description 
GNU objdump behaviour in every version I have access to easily (v2.22, v2.24, and v2.29), for -r on an executable/shared object is to print non-dynamic relocation sections it finds (possibly also dynamic relocations, but I haven't checked). llvm-objdump does not - see the following bit of code in printRelocations:

  // Regular objdump doesn't print relocations in non-relocatable object
  // files.
  if (!Obj->isRelocatableObject())
    return;

I don't see why this behaviour exists. See also r263971, r263987 and r215844 for relevant revisions to do with this line. We should fix it.

**Comment by MaskRay** [comment]
Patch: https://reviews.llvm.org/D128959
