### ISSUE TITLE
clang-format crashes on windows when emplace formatting read-only file

### ISSUE THREAD

**Issue by 91b604ff-5b4e-4821-a182-129f49d1a44c** [llvm/llvm-project#41359]
|  |  |
| --- | --- |
| Bugzilla Link | [42014](https://llvm.org/bz42014) |
| Version | 8.0 |
| OS | Windows NT |
| CC | @mydeveloperday |

## Extended Description 
clang-format crashes on windows when emplace formatting read-only file

repro:
```
echo "int main(){}" > a.cpp
attrib +R a.cpp
clang-format -i a.cpp
```

**Comment by mydeveloperday** [comment]
This was resolved by  https://reviews.llvm.org/D111815 and landed in  a92cf5a5a0cd01145f8db2ae09334a8b43a1271b 

A suitable warning is now given, it should no longer crash
```
$ clang-format -i a.cpp
clang-format error:unable to rename temporary 'a.cpp-b23fdb7d' to output file 'a
.cpp': 'permission denied'
```
