### ISSUE TITLE
Argument Promotion can cause accesses to memory not accessed before

### ISSUE THREAD

**Issue by jdoerfert** [llvm/llvm-project#41384]
|  |  |
| --- | --- |
| Bugzilla Link | [42039](https://llvm.org/bz42039) |
| Version | trunk |
| OS | All |
| Attachments | [reproducer](https://user-images.githubusercontent.com/6248191/143759277-3d1f67bc-77c5-4452-9d13-e7e980f5999c.gz) |
| CC | @fhahn,@hfinkel |

## Extended Description 

The attached test case shows how ArgumentPromotion can introduce accesses to memory not accessed before. The call to the function in the entry block of @&#8203;local should prevent us from deriving "dereferenceable" for the argument pointer.

**Comment by nikic** [comment]
This has been fixed by https://github.com/llvm/llvm-project/commit/0ebbf3435ff4c3c141549aaf0f791485c28f06f0.
