### ISSUE TITLE
[rejects valid] error when lambda capturing the result of a structured binding

### ISSUE THREAD

**Issue by 91b604ff-5b4e-4821-a182-129f49d1a44c** [llvm/llvm-project#41398]
|  |  |
| --- | --- |
| Bugzilla Link | [42053](https://llvm.org/bz42053) |
| Version | trunk |
| OS | Windows NT |
| CC | @AaronBallman,@PatrickAMoran,@zygoloid |

## Extended Description 
https://godbolt.org/z/do-bM3

struct S {
  int a;
};

void f() {
  []() {
    auto [k] = S{0};
    [k]() {};
  };
}

<source>:8:6: error: 'k' in capture list does not name a variable

    [k]() {};

     ^

**Comment by cor3ntin** [comment]
Fixed by 127bf44385424891eb04cff8e52d3f157fc2cb7c
