### ISSUE TITLE
LTO: GEP is not of right type for indices!

### ISSUE THREAD

**Issue by petrhosek** [llvm/llvm-project#41408]
|  |  |
| --- | --- |
| Bugzilla Link | [42063](https://llvm.org/bz42063) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie |

## Extended Description 
We're getting the following error when trying to build BoringSSL with LTO using lld:

GEP is not of right type for indices!
  %1410 = getelementptr inbounds %"class.bssl::internal::StackAllocated.1896", %"class.bssl::internal::StackAllocated.1896"* %116, i64 0, i32 0, i32 0, !dbg !&#8203;342099
 %"type 0x86cc630"*in function _ZN25EVPExtraTest_Ed25519_Test8TestBodyEv
LLVM ERROR: Broken function found, compilation aborted!

Reproducer is at https://storage.googleapis.com/fuchsia-build/reproducer/lld-lto-failure.tar.bz2

**Comment by yuanfang-chen** [comment]
Fixed on ToT. (likely by d9881e6e27bc7fa8827)
