### ISSUE TITLE
performance-noexcept-move-constructor: complains about the exception specification of explicitly defaulted move constructors

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#41414]
|  |  |
| --- | --- |
| Bugzilla Link | [42069](https://llvm.org/bz42069) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
"performance-noexcept-move-constructor" complains about

class A {
  A(A&&) = default;
}

(even when it's actually noexcept(true)!).

This is specially problematic when it's a templated class which will or will not be noexcept move constructible depending on whether a templated member is noexcept move constructible. In such a case the compiler already takes care of using the correct exception specifier implicitly, and explicitly specifying it is very verbose.

I triggered the issue with clang-tidy 8.0.0, even if it's very similar to llvm/llvm-project#25086  (but that shows a different check name).

**Comment by carlosgalvezp** [comment]
Example from OP not reproducible on trunk.
