### ISSUE TITLE
Inplace new-ing an array overwrites the square of the memory

### ISSUE THREAD

**Issue by e84ee981-20b7-441e-8de0-adb2190144d6** [llvm/llvm-project#41441]
|  |  |
| --- | --- |
| Bugzilla Link | [42096](https://llvm.org/bz42096) |
| Version | 8.0 |
| OS | Linux |
| CC | @dwblaikie,@DougGregor,@jfbastien,@riccibruno,@zygoloid |

## Extended Description 
When in-place new-ing a local variable of an array of trivial type, the generated code calls `memset` with the square of the size of the array, corrupting the stack.

Quick example:
```cpp
#include <new>

template <typename TYPE>
void f()
{
    typedef TYPE TArray[7];

    TArray x;
    new(&x) TArray();
}

int main()
{
    f<char>();
    f<int>();
}
```

Sample code generation can be seen for Clang 7 and 8 via godbolt:
https://godbolt.org/z/WjhFrc

**Comment by awson** [comment]
The "fix" has been reverted, the problem is still with us.

> CreateCXXNew is where it gets weird & the dependent type case gets the bound extracted but the type is not adjusted

@dwblaikie, I can't find `CreateCXXNew` anywhere in the code (even after preprocessing), do you mean `BuildCXXNew`?

**Comment by dwblaikie** [comment]
> The "fix" has been reverted, the problem is still with us.
> 
> > CreateCXXNew is where it gets weird & the dependent type case gets the bound extracted but the type is not adjusted
> 
> @dwblaikie, I can't find `CreateCXXNew` anywhere in the code (even after preprocessing), do you mean `BuildCXXNew`?

Yeah, been a while - but at a cursory glance that correction sounds right.

**Comment by dwblaikie** [comment]
(patch was reverted in https://github.com/llvm/llvm-project/commit/e1321fafbc024007023ce5d9b88d987a920c3bca)

**Comment by awson** [comment]
@djtodoro, how is this "completed"?

I see neither my [PR](https://github.com/llvm/llvm-project/pull/96464) is merged, nor any newer one is referenced in this issue.

**Comment by djtodoro** [comment]
> @djtodoro, how is this "completed"?
> 
> I see neither my PR (#96464) is merged, nor any newer one is referenced in this issue.

I have no idea what happened here. Never touched or visited this issue.
