### ISSUE TITLE
Invalid fix-it for modernize-use-transparent-functors

### ISSUE THREAD

**Issue by igor-akhmetov** [llvm/llvm-project#41454]
|  |  |
| --- | --- |
| Bugzilla Link | [42109](https://llvm.org/bz42109) |
| Version | unspecified |
| OS | Windows NT |
| CC | @EugeneZelenko,@Xazax-hun |

## Extended Description 
Consider this code:

#include <queue>
std::priority_queue<std::pair<long, int>, std::vector<std::pair<long, int>>, std::greater<std::pair<long, int>>> numbers;

After the fix-it it is transformed into

std::priority_queue<std::pair<long, int>, std::vector<std::pair<long, int>>, std::greater<numbers;

The fix-it suggests to remove too much code:

DiagnosticName: modernize-use-transparent-functors
    Message: prefer transparent functors 'greater<>'
    FileOffset: 129
    TextOffset: 126
    Replacements:
        File: C:\tmp\ConsoleApplication12\ConsoleApplication12.cpp
        FileOffset: 142
        Length: 22
        Range: (139 - 161)
        ReplacementText: ''

**Comment by carlosgalvezp** [comment]
This seems fixed on latest trunk, uses `std::greater<>`.
