### ISSUE TITLE
[AMDGPU] using vec3 on SI doesn't seem to work correctly

### ISSUE THREAD

**Issue by ec5042c9-e27e-4c4c-b4bd-a6a3d269d294** [llvm/llvm-project#41461]
|  |  |
| --- | --- |
| Bugzilla Link | [42116](https://llvm.org/bz42116) |
| Version | trunk |
| OS | Linux |
| Attachments | [good_output](https://user-images.githubusercontent.com/95090621/143759317-e487a41c-0045-4084-a033-5ddbd899749f.gz), [bad_output](https://user-images.githubusercontent.com/95090621/143759318-747a3147-6a86-426c-817f-2ee7cdd8f7e8.gz) |

## Extended Description 

Hi,

I recently pushed a patch that removes the vec3 restriction to the LLVM backend in Mesa [1]. This seems to work as expected on GFX8 and GFX9 (I don't have GFX7), but it seems broken on GFX6.

See the two attachments (good and bad) of dEQP-VK.glsl.builtin.precision.fract.mediump_compute.vec3.

[1] https://cgit.freedesktop.org/mesa/mesa/commit/?id=6970a9a6ca9ea26a9e6cf968d3fec3565bef2e9b

**Comment by arsenm** [comment]
Assuming this was fixed, many things have been fixed for odd vectors. Plus gfx6 is old and difficult to test now
