### ISSUE TITLE
Cannot use alias template in friend declaration

### ISSUE THREAD

**Issue by 05cec8df-0431-4da2-94bb-ff57372dc3f8** [llvm/llvm-project#41470]
|  |  |
| --- | --- |
| Bugzilla Link | [42125](https://llvm.org/bz42125) |
| Version | 8.0 |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Hi,

trying to use an alias template in a friend declaration fails with "error: redefinition of 'XYZ' as different kind of symbol".

This piece of code fails to compile on clang-8:
~~~
template<typename T>
class ActualStuff {};

template <typename B>
class Other {
public:
    template<typename T>
    using Stuff = ActualStuff<T>;

#if 1
    // this fails with:
    // error: redefinition of 'Stuff' as different kind of symbol
    template<typename>
    friend class Stuff;
#else
    // this works
    template<typename>
    friend class ActualStuff;
#endif
};
~~~

And the only way I found to make it work (as shown in the example) is to bypass the alias.

As a side note, gcc accepts the code in the example.

Cheers
Marco

**Comment by shafik** [comment]
Interesting, MSVC agrees with clang on this one: https://godbolt.org/z/j7hhG3oYz

I think [dcl.type.elab p5](https://eel.is/c++draft/dcl.type.elab#5) means clang is correct:

>If the identifier or simple-template-id resolves to a typedef-name ([dcl.typedef], [temp.names]), the elaborated-type-specifier is ill-formed.
>[Note 3: This implies that, within a class template with a template type-parameter T, the declaration
>```friend class T;```
> is ill-formed. However, the similar declaration friend T; is allowed ([class.friend]). — end note]

CC @zygoloid @hubert-reinterpretcast

**Comment by zygoloid** [comment]
Yes, this code is invalid. You can only use the *elaborated-type-specifier* syntax `class T` when `T` is an actual class name, not a typedef or alias template or similar.
