### ISSUE TITLE
Missing switch case checking in Clang diagnostics

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#41487]
|  |  |
| --- | --- |
| Bugzilla Link | [42142](https://llvm.org/bz42142) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@efriedma-quic,@zygoloid |

## Extended Description 
void g();

void warn(char c)
{
  switch (c) {
  case 256: g();
  }
}

Clang: No warning. 

GCC warns:
warning: case label value exceeds maximum value for type

**Comment by AaronBallman** [comment]
This appears to be implemented on trunk, so closing as implemented. If you're still seeing issues, please reopen the bug with more details on how to reproduce.
