### ISSUE TITLE
Linter fails to provide implicit conversion warning for char c = 130u

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#41482]
|  |  |
| --- | --- |
| Bugzilla Link | [42137](https://llvm.org/bz42137) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @EugeneZelenko |

## Extended Description 
This code flags an important warning

char c = 130;

This code does not give the important warning (but the result is the same ominous one)

char c = 130u;

I discovered this while answering this question on SO
https://stackoverflow.com/a/56424762/276193

**Comment by carlosgalvezp** [comment]
Warning available in Clang (`-Wconstant-conversion` and `-Wsign-conversion`). Not the scope of clang-tidy.
