### ISSUE TITLE
Aarch64 - FreeBSD 12 : Expression evaluation causes segfault

### ISSUE THREAD

**Issue by itzurabhi** [llvm/llvm-project#41498]
|  |  |
| --- | --- |
| Bugzilla Link | [42153](https://llvm.org/bz42153) |
| Version | unspecified |
| OS | FreeBSD |
| Attachments | [Backtrace & Thread List](https://user-images.githubusercontent.com/93436065/143759323-25f07d1d-4279-4eb3-9132-f3336519d3ef.gz) |
| CC | @itzurabhi,@JDevlieghere |

## Extended Description 

built the master branch(llvm,lldb,clang) from the git on 4th July 2019 on a AARCH64 FreeBSD12.0 VM (qemu)

while running sample program with following commands : 
// sample
int main(int argc,const char ** argv){
        int z = argc + 10;
        return z;
}

/////

(LLDB)b main
(LLDB)r
(LLDB)n
(LLDB)p argc

(SEGFAULT)

=============

I faced the same issue on 7.1 release branch also, same segfault/back trace was generated.So tested latest git in order to see if it was fixed after that.

From my analysis , this line causes:

(data_sp && ReadGPR() && ReadFPR())

https://github.com/llvm-mirror/lldb/blob/master/source/Plugins/Process/FreeBSD/RegisterContextPOSIXProcessMonitor_arm64.cpp#L167

m_register_info_up - point to a zero address.only the constructor of the class calls .reset on this smart pointer.

I have done some debugging and suspect 

(RegisterContextPOSIXProcessMonitor_arm64::ReadGPR())
https://github.com/llvm-mirror/lldb/blob/master/source/Plugins/Process/FreeBSD/RegisterContextPOSIXProcessMonitor_arm64.cpp#L35

or

(RegisterContextPOSIXProcessMonitor_arm64::ReadFPR())
https://github.com/llvm-mirror/lldb/blob/master/source/Plugins/Process/FreeBSD/RegisterContextPOSIXProcessMonitor_arm64.cpp#L40

might be causing the overwrite. please advise on where to look further, I am ready to work on a fix.

**Comment by DavidSpickett** [comment]
This was probably fixed when the code in question got refactored. It does not fault now on FreeBSD 14 on AArch64:
```
ec2-user@freebsd:~/build-llvm $ ./bin/lldb --version
lldb version 19.0.0git (https://github.com/llvm/llvm-project.git revision 235332150d52d11b340a10be1bb88432d2cf4179)
  clang revision 235332150d52d11b340a10be1bb88432d2cf4179
  llvm revision 235332150d52d11b340a10be1bb88432d2cf4179
ec2-user@freebsd:~/build-llvm $ ./bin/lldb /tmp/test.o
(lldb) target create "/tmp/test.o"
Current executable set to '/tmp/test.o' (aarch64).
(lldb) b main
Breakpoint 1: where = test.o`main + 16 at test.c:2:10, address = 0x00000000002105b4
(lldb) r
Process 25309 launched: '/tmp/test.o' (aarch64)
Process 25309 stopped
* thread #1, name = 'test.o', stop reason = breakpoint 1.1
    frame #0: 0x00000000002105b4 test.o`main(argc=1, argv=0x0000000080ffdb10) at test.c:2:10
   1   	int main(int argc,const char ** argv){
-> 2   		int z = argc + 10;
   3   		return z;
   4   	}
(lldb) n
Process 25309 stopped
* thread #1, name = 'test.o', stop reason = step over
    frame #0: 0x00000000002105c0 test.o`main(argc=1, argv=0x0000000080ffdb10) at test.c:3:9
   1   	int main(int argc,const char ** argv){
   2   		int z = argc + 10;
-> 3   		return z;
   4   	}
(lldb) p argc
(int) 1
```
Works with the system's lldb 16.0.6 so it has been fixed since at least that version.
