### ISSUE TITLE
Clang-format Adds Space in Placement New Expression with Setting SpaceBeforeParens: ControlStatements

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#41501]
|  |  |
| --- | --- |
| Bugzilla Link | [42156](https://llvm.org/bz42156) |
| Version | 8.0 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
.clang-format file:
```
Language: Cpp
SpaceBeforeParens: ControlStatements
ColumnLimit: 0
```

After running clang-format the code is formatted as follows:
```
void Foo() {
  new (place) Bar;
}
```

The new expression is not a control statement (the docs name for/if/while as examples). Instead, it works and feels much more like a function call. The parentheses are enclosing a parameter list, not a control expression. So this parameter list should be formatted like the one of a function call, like so:
```
void Foo() {
  new(place) Bar;
}
```

Note the missing space before the parameter list.

**Comment by mydeveloperday** [comment]
`SpaceBeforeParens` is effectively deprecated for making any changes to its behaviour

but we've added the following

`SpaceBeforeParensOptions`

This would be a perfect example of adding `AfterPlacementNew`: true to allow us to control it with a lot more fine control

I wouldn't consider changing the default but an enhancement to add a new option would be a good first task

**Comment by omarahmed1111** [comment]
Hi @mydeveloperday, I have submitted a small patch to add this feature here: https://reviews.llvm.org/D127270
