### ISSUE TITLE
Clang-format Ignores PointerAlignment Setting when Asterisk is Not Directly Attached to Type

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#41506]
|  |  |
| --- | --- |
| Bugzilla Link | [42161](https://llvm.org/bz42161) |
| Version | 8.0 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
.clang-format file:
```
Language: Cpp
PointerAlignment: Left
```

After running clang-format the code is formatted as follows:
```
int* a;
int *c, *d;
int MyClass::*e;
void Foo(int (*Bar)[3]);
```

As you can see, PointerAlignment is used to format the first declaration but not for the other 3 declarations. I find it especially awkward that the addition of the second variable directly affects the placement of the asterisk for the first declared variable in line 2.

I would expect the formatting to be applied to all occurrences of pointer declarations even though they might not have a type name directly written left to the asterisks:
```
int* a;
int* c, * d;
int MyClass::* e;
void Foo(int (* Bar)[3]);
```

Note the added white spaces before all asterisks. Also note that the issue applies to references as well.

**Comment by mydeveloperday** [comment]
This comes up from time to time, specifically for this case

`int* c, *d;`

I feel your response is subjective, and what ever we changed it to someone else would complain the other way.

A long time ago there was a comment from @djasper that we should never do

`int*c,* d;`

I tend to agree, It doesn't feel correct (but then I don't use left alignment. )

I think the bar would have to be very high for us to change this default the impact of changing this now would be huge.

I'm going to close this as I don't think we'd address this or accept a patch without alot of good reason why, but feel free to reopen if you feel this is the wrong decision.
