### ISSUE TITLE
sign extension behavior is different from gcc

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#4151]
|  |  |
| --- | --- |
| Bugzilla Link | [3779](https://llvm.org/bz3779) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lattner |

## Extended Description 
Compiling
----------------------
short x;

void g(int);
short h(void);

short f(void) {
  g(h());
  return x;
}
--------------------

with gcc produces

-----------------------------
      call    h
      movswl  %ax,%edi
      call    g
      movw    x(%rip), %ax
----------------------------

Note that only the caller does sign extension

with llvm we have
-------------------------------
        call    h
        movswl  %ax, %edi
        call    g
        movswl  x, %eax
------------------------------

Note that both caller and callee do sign extension.

**Comment by arsenm** [comment]
Current clang:
```
	.cfi_startproc
# %bb.0:
	pushq	%rax
	.cfi_def_cfa_offset 16
	callq	h@PLT
	movswl	%ax, %edi
	callq	g@PLT
	movzwl	x(%rip), %eax
	popq	%rcx
	.cfi_def_cfa_offset 8
	retq
```

Current gcc:
```

	.cfi_startproc
	endbr64
	subq	$8, %rsp
	.cfi_def_cfa_offset 16
	call	h@PLT
	movswl	%ax, %edi
	call	g@PLT
	movzwl	x(%rip), %eax
	addq	$8, %rsp
	.cfi_def_cfa_offset 8
	ret
	.cfi_endproc

```

Looks the same to me
