### ISSUE TITLE
Clang-format Add Option to Align References Independently Of Pointers

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#41510]
|  |  |
| --- | --- |
| Bugzilla Link | [42165](https://llvm.org/bz42165) |
| Version | 8.0 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Though I understand that references and pointers to other types are both technically just types, the usage of references as parameters of functions feels much different than using pointers because a reference is automatically created when a variable is passed to a function and a reference is also dereferenced implicitly and can be used like a local variable inside the function. In contrast a pointer must be obtained explicitly to pass it into a function and it also needs to be dereferenced explicitly each time the referenced object is accessed inside the function.

This is why the general perception of references is that they are not part of the parameter type but rather a parameter passing convention. Hence I would like to be able to align references independently of pointers. I propose to add 2 new settings:
- DeriveReferenceAlignment, which should have the same options as DerivePointerAlignment, the default should be the option specified by DerivePointerAlignment or, if DerivePointerAlignment is not configured, its default.
- ReferenceAlignment, which should have the same options as PointerAlignment, the default should be the option specified by PointerAlignment or, if PointerAlignment is not configured, its default.

**Comment by mydeveloperday** [comment]
I feel this is covered by https://reviews.llvm.org/D104096 which landed in a08fa8a508199c6463f5ee5d617e2f360f718067 which looks to be in clang-format-v13

I'm closing this as I feel this is now handled
