### ISSUE TITLE
Unsound performance-unnecessary-copy-initialization

### ISSUE THREAD

**Issue by stbergmann** [llvm/llvm-project#41574]
|  |  |
| --- | --- |
| Bugzilla Link | [42229](https://llvm.org/bz42229) |
| Version | unspecified |
| OS | Linux |
| CC | @EugeneZelenko,@fberger |

## Extended Description 
<https://clang.llvm.org/extra/clang-tidy/checks/performance-unnecessary-copy-initialization.html> states: "The check is only applied if it is safe to replace the copy by a const reference."  Yet, in

> $ cat test.cc
> struct S1 { S1(S1 const &); };
> struct S2 { S1 a, b; };
> void f(S2 & s) {
>  S1 & a = s.a;
>  S1 & b = s.b;
>  S1 c = a;
>  s.a = b;
>  s.b = c;
> }

> $ clang-tidy -checks='-*,performance-unnecessary-copy-initialization' test.cc --
> 1 warning generated.
> /home/sbergman/test.cc:6:5: warning: local copy 'c' of the variable 'a' is never modified; consider avoiding the copy [performance-unnecessary-copy-initialization]
>  S1 c = a;
>     ^
>  const  &

doing the replacement is unsound.

**Comment by PiotrZSL** [comment]
Issue no longer reproduce.
