### ISSUE TITLE
No warning for incomplete type

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#41572]
|  |  |
| --- | --- |
| Bugzilla Link | [42227](https://llvm.org/bz42227) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie,@DougGregor,@zygoloid |

## Extended Description 
My clang is 9.0.0, and the code is:

enum E { a, b = true ? 1 : ((E)a, 0) };

gcc rejects it:

<source>:1:32: error: conversion to incomplete type

    1 | enum E { a, b = true ? 1 : ((E)a, 0) };

      |                                ^

Compiler returned: 1

clang accepts it, although the type is incomplete.

**Comment by wheatman** [comment]
This was fixed between 9.0.1 and 10.0.0
https://godbolt.org/z/oddr99K7q
code
```cpp
enum E { a, b = true ? 1 : ((E)a, 0) };
```

new error
```
<source>:1:29: error: 'E' is an incomplete type
enum E { a, b = true ? 1 : ((E)a, 0) };
                            ^
<source>:1:6: note: definition of 'E' is not complete until the closing '}'
enum E { a, b = true ? 1 : ((E)a, 0) };
     ^
1 error generated.
Compiler returned: 1
```
