### ISSUE TITLE
Improve llvm-readobj help text

### ISSUE THREAD

**Issue by jh7370** [llvm/llvm-project#41601]
|  |  |
| --- | --- |
| Bugzilla Link | [42256](https://llvm.org/bz42256) |
| Version | trunk |
| OS | Windows NT |
| CC | @jh7370 |

## Extended Description 
llvm-readobj's help text has a couple of issues that I think we can improve:

* The help text uses single-dash long options for option names, but references in the help text to other options exlcusively use double-dashes.

* Several aliases are missing from the help text. See http://lists.llvm.org/pipermail/llvm-dev/2019-June/132917.html for a discussion on this topic.

**Comment by MaskRay** [comment]
This can be closed. `llvm-readelf --help` and https://llvm.org/docs/CommandGuide/llvm-readelf.html are quite comprehensive (since probably 2020 or 2021).
