### ISSUE TITLE
segmentation fault of target program caused by loop-unroll with "opt -sroa -indvars -loop-rotate -simplifycfg -inline -loop-reroll -loop-unroll"

### ISSUE THREAD

**Issue by 952e6d5a-d994-4724-a6d1-07613b2d95a8** [llvm/llvm-project#41620]
|  |  |
| --- | --- |
| Bugzilla Link | [42275](https://llvm.org/bz42275) |
| Version | trunk |
| OS | Linux |
| Attachments | [.bc file of the source code](https://user-images.githubusercontent.com/92601252/143759349-9aa7a9f5-d02f-4ba8-8653-30f7c5a361ab.gz) |
| CC | @rotateright |

## Extended Description 

$clang -v
clang version 9.0.0 (trunk 362492)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$clang -O3 -c -emit-llvm  -mllvm -disable-llvm-optzns small.c

$opt -sroa -indvars -loop-rotate -simplifycfg -inline -loop-reroll -loop-unroll small.bc -o small-opt.bc

$clang small-opt.bc -o small.out && ./small.out
Segmentation fault (core dumped)

without loop-unroll pass, the target program is fine.
$opt -sroa -indvars -loop-rotate -simplifycfg -inline -loop-reroll small.bc -o small-opt1.bc

$clang small-opt1.bc -o small1.out && ./small1.out

--------------------------------
void a() {
  short b[6][2][7];
  int c, d, e;
  for (c = 0; c < 6; c++) {
    for (d = 0; d < 2; d++) {
      for (e = 0; e < 7; e++)
        b[c][d][e] = 1;
    }
  }
}
void main() { a(); }

**Comment by nikic** [comment]
The LoopReroll pass has been removed by https://github.com/llvm/llvm-project/pull/80972.
