### ISSUE TITLE
Clang-format ternary operator wrong alignment of ':' in second line

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#41647]
|  |  |
| --- | --- |
| Bugzilla Link | [42302](https://llvm.org/bz42302) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
AlignConsecutiveAssignments: true
AlignConsecutiveDeclarations: true

When a ternary operator is in a line following a very long type, the (':') on the next line is aligned with ('?') as if long type name was missing.

```
    {
        VeryLongLongLongLongTypeName name;
        short                        s;
        std::string                  str = ext_bool ? "Hello World!\n" //
                                   : "Goodbye World;)"
    }
```

it is aligned as if, there were no longer declarations:

```
        std::string str = ext_bool ? "Hello World!\n" //
                                   : "Goodbye World;)"
```

**Comment by mydeveloperday** [comment]
This formats as 

```
{
  VeryLongLongLongLongTypeName name;
  short                        s;
  std::string                  str = ext_bool ? "Hello World!\n" //
                                              : "Goodbye World;)"
}
```

As this looks to be fixed I am closing this issue, feel free to reopen if you still see issues
