### ISSUE TITLE
TargetParserTest.ARMExtensionFeatures test fails on 32-bit windows

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#41661]
|  |  |
| --- | --- |
| Bugzilla Link | [42316](https://llvm.org/bz42316) |
| Version | trunk |
| OS | Linux |
| CC | @sjoerdmeijer |

## Extended Description 
cmd.exe /C "cd /D C:\src\llvm_package_363760\build32_stage0\test && C:\python_27_amd64\files\python.exe C:/src/llvm_package_363760/build32_stage0/./bin/llvm-lit.py -sv C:/src/llvm_package_363760/build32_stage0/test"
ninja: build stopped: subcommand failed.
[0/1] Running the LLVM regression tests
-- Testing: 31947 tests, 32 threads --
Testing: 0 .. 10
FAIL: LLVM-Unit :: Support/./SupportTests.exe/TargetParserTest.ARMExtensionFeatures (4352 of 31947)
******************** TEST 'LLVM-Unit :: Support/./SupportTests.exe/TargetParserTest.ARMExtensionFeatures' FAILED ********************
Note: Google Test filter = TargetParserTest.ARMExtensionFeatures
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from TargetParserTest
[ RUN      ] TargetParserTest.ARMExtensionFeatures
LLVM ERROR: out of memory
 #&#8203;0 0x002a312b (C:\src\llvm_package_363760\build32_stage0\unittests\Support\SupportTests.exe+0x1f312b)
 #&#8203;1 0x75a92a12 (C:\WINDOWS\System32\ucrtbase.dll+0x92a12)
 #&#8203;2 0x00247d6d (C:\src\llvm_package_363760\build32_stage0\unittests\Support\SupportTests.exe+0x197d6d)
 #&#8203;3 0x75a8d8bf (C:\WINDOWS\System32\ucrtbase.dll+0x8d8bf)
 #&#8203;4 0x002b9a9b (C:\src\llvm_package_363760\build32_stage0\unittests\Support\SupportTests.exe+0x209a9b)
 #&#8203;5 0x000d62fb (C:\src\llvm_package_363760\build32_stage0\unittests\Support\SupportTests.exe+0x262fb)
 #&#8203;6 0x001c544c (C:\src\llvm_package_363760\build32_stage0\unittests\Support\SupportTests.exe+0x11544c)
 #&#8203;7 0x0028c53b (C:\src\llvm_package_363760\build32_stage0\unittests\Support\SupportTests.exe+0x1dc53b)
 #&#8203;8 0x002aaf2e (C:\src\llvm_package_363760\build32_stage0\unittests\Support\SupportTests.exe+0x1faf2e)
 #&#8203;9 0x002a92e7 (C:\src\llvm_package_363760\build32_stage0\unittests\Support\SupportTests.exe+0x1f92e7)
#&#8203;10 0x002b456e (C:\src\llvm_package_363760\build32_stage0\unittests\Support\SupportTests.exe+0x20456e)
#&#8203;11 0x002b46f8 (C:\src\llvm_package_363760\build32_stage0\unittests\Support\SupportTests.exe+0x2046f8)
#&#8203;12 0x002b461d (C:\src\llvm_package_363760\build32_stage0\unittests\Support\SupportTests.exe+0x20461d)
#&#8203;13 0x002b49a1 (C:\src\llvm_package_363760\build32_stage0\unittests\Support\SupportTests.exe+0x2049a1)

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90..
Testing Time: 116.79s
********************
Failing Tests (1):
    LLVM-Unit :: Support/./SupportTests.exe/TargetParserTest.ARMExtensionFeatures

  Expected Passes    : 30991
  Expected Failures  : 191
  Unsupported Tests  : 764
  Unexpected Failures: 1
FAILED: test/CMakeFiles/check-llvm

**Comment by DavidSpickett** [comment]
Fixed long ago by Sjoerd's patch.
