### ISSUE TITLE
[X86] Implement MMX intrinsics with SSE equivalents

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#41665]
|  |  |
| --- | --- |
| Bugzilla Link | [42320](https://llvm.org/bz42320) |
| Version | trunk |
| OS | Windows NT |
| CC | @topperc,@efriedma-quic,@jyknight,@RKSimon,@rotateright |

## Extended Description 
Similar to what's been proposed recently for gcc, we should investigate promoting MMX intrinsics to SSE equivalents:

https://gcc.gnu.org/ml/gcc-patches/2019-02/msg00061.html

This probably would be best handled in CGBuiltin.cpp - replacing the MMX builtins with SSE equivalents, although some can probably done in headers as well behind a suitable define.

NOTE: This will cause a high number of subvector insertions/extractions, we might need some mechanism to reduce this even without optimizations.

**Comment by jyknight** [comment]
Fixed via the above PRS; MMX intrinsics now use SSE2.
