### ISSUE TITLE
Assertion failure/wrong linkage for explicit specialisation of function templates, declared in an unnamed namespace

### ISSUE THREAD

**Issue by momchil-velikov** [llvm/llvm-project#41666]
|  |  |
| --- | --- |
| Bugzilla Link | [42321](https://llvm.org/bz42321) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Testcase (https://gcc.godbolt.org/z/E85jsh):

inline namespace {
  template <typename T> int f() { return 0; }
  template <typename T> int g() { return 0; }
}

template<> int f<int>() { return 0; }
template int g<int>();

int (*pf)() = f<int>;
int (*pg)() = g<int>;

triggers assertion failure in debug builds:

$ ./bin/clang -S bb.cc -o - 
clang-9: /data/src/llvm-project/clang/lib/AST/Decl.cpp:1491: clang::LinkageInfo clang::LinkageComputer::getLVForDecl(const clang::NamedDecl *, clang::LVComputationKind): Assertion `!Old || Old->getCachedLinkage() == D->getCachedLinkage()' failed.

In release builds, the function `f<int>` has external linkage and filescope, whereas `g<int>` has internal linkage and is in the unnamed namespace.

IIUC [temp.explicit] #&#8203;6 and [temp.expl.spec] #&#8203;8 both should be members of the unnamed namespace and, following, [basic.link] #&#8203;4, have internal linkage.

**Comment by shafik** [comment]
No longer reproduces: https://gcc.godbolt.org/z/7bG8j97sG

**Comment by Endilll** [comment]
Fixed in Clang 14: https://cexplorer.testlabs.pro/z/nT7G6e
