### ISSUE TITLE
 lld 8.0 places .init.rodata.cst8 before .rodata with output section phdr

### ISSUE THREAD

**Issue by 334b2b79-2d6b-4edb-98f9-d5bdd4e3391f** [llvm/llvm-project#41672]
|  |  |
| --- | --- |
| Bugzilla Link | [42327](https://llvm.org/bz42327) |
| Version | unspecified |
| OS | All |
| CC | @DimitryAndric,@MaskRay,@rui314,@smeenai,@smithp35 |

## Extended Description 
lld 8.0 seems to misplace orphaned sections, according to GNU ld manual, orphaned sections should be placed at the end of the output:

https://sourceware.org/binutils/docs/ld/Orphan-Sections.html

lld 8.0 however seems to place some of them at the start, for example giving the following (start) of a linker file:

SECTIONS
{
  [...]
  .text : AT(...) {

lld 8.0 produces the following section headers:

  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .reloc            PROGBITS        ffff82d080000000 001000 000008 00   A  0   0  4
  [ 2] .init.rodata.cst8 PROGBITS        ffff82d080000008 001008 000008 08  AM  0   0  8
  [ 3] .text             PROGBITS        ffff82d080200000 201000 1631ba 00  AX  0   0 4096
[...]

Placing the orphaned .reloc and .init.rodata.cst8 before the linker script defined sections. Note that previos lld versions did not exhibit this behaviour. The output of LLD_REPRODUCE can be found at:

http://xenbits.xen.org/people/royger/xen-lld-repro.tar.gz

**Comment by MaskRay** [comment]
https://reviews.llvm.org/D111717 added a special case `if (script->hasPhdrsCommands())`, which places `.init.rodata.cst8` after `.rodata` like lld 7, even in the presence of https://reviews.llvm.org/D48406 (prioritize the placement of SHT_PROGBITS sections (.rodata, .eh_frame_hdr, and .eh_frame) closer to code sections, to mitigate the risk of relocation overflow)

I have simplified the orphan section placement code in 0f3d646cefbe00b4a1037dc68e9d76e5470e805f

The `script->hasPhdrsCommands()` condition feels too magical. I will create a patch to switch to `cast<OutputDesc>(*i)->osec.phdrs.size()`, which would keep .init.rodata.cst8 unchanged while reducing the differences whether `PHDRS` commands are present.

---

I have been thinking about guidelines to improve portability.
https://maskray.me/blog/2024-06-02-understanding-orphan-sections#portability currently specifies

To maximize portability of linker scripts across different linkers, it's essential to establish clear boundaries for PT_LOAD segments. This can be achieved by:

* Explicit alignment: Utilizing MAXPAGESIZE alignment to distinctly separate sections within the linker script.
* Anchoring sections: Ensuring that the first section in each PT_LOAD segment includes at least one input section, preventing ambiguous placement decisions by the linker. When the PHDRS command is present, ensure that the first sections have :phdr.
