### ISSUE TITLE
clang crashes on FreeBSD on the 'folly' project

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#41683]
|  |  |
| --- | --- |
| Bugzilla Link | [42338](https://llvm.org/bz42338) |
| Version | 8.0 |
| OS | FreeBSD |
| Attachments | [crash-cases.tar.xz](https://user-images.githubusercontent.com/95090477/143759372-ba26842c-08c3-4341-b91d-7c8512a921c7.gz) |
| CC | @DougGregor,@DimitryAndric,@zygoloid |

## Extended Description 
https://github.com/facebook/folly

**Comment by shafik** [comment]
This is pretty old, I don't think there is anything actionable here anymore. Please reopen if that is not the case.
