### ISSUE TITLE
modernize-use-using ignores __attribute__

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#41685]
|  |  |
| --- | --- |
| Bugzilla Link | [42340](https://llvm.org/bz42340) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @EugeneZelenko |

## Extended Description 
Giving this example input and command, the __attribute__ is ignored by this clang-tidy check and lost by the --fix flag.

$ cat /tmp/x.cpp
typedef __attribute__((__aligned__(1))) unsigned int UUINT;

$ bin/clang-tidy --checks=modernize-use-using /tmp/x.cpp --
1 warning generated.
/tmp/x.cpp:1:1: warning: use 'using' instead of 'typedef' [modernize-use-using]
typedef __attribute__((__aligned__(1))) unsigned int UUINT;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
using UUINT = unsigned int

$ bin/clang-tidy --checks=modernize-use-using -fix /tmp/x.cpp --
1 warning generated.
/tmp/x.cpp:1:1: warning: use 'using' instead of 'typedef' [modernize-use-using]
typedef __attribute__((__aligned__(1))) unsigned int UUINT;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
using UUINT = unsigned int
/tmp/x.cpp:1:1: note: FIX-IT applied suggested code changes
clang-tidy applied 1 of 1 suggested fixes.

$ cat /tmp/x.cpp
using UUINT = unsigned int;

**Comment by PiotrZSL** [comment]
Issue still exist on LLVM 17 (main).

**Comment by firewave** [comment]
Also happens with macros as attributes.

```cpp
#define WINAPI

typedef bool (WINAPI *f)(void*, int, int*, void*);
```

```
<source>:3:1: warning: use 'using' instead of 'typedef' [modernize-use-using]
    3 | typedef bool (WINAPI *f)(void*, int, int*, void*);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | using f = bool (*)(void *, int, int *, void *)
```
https://godbolt.org/z/dx1P7frPr
