### ISSUE TITLE
llvm-twine-local fixit includes the `=` inside the added parentheses when fixing default parameters

### ISSUE THREAD

**Issue by donhinton** [llvm/llvm-project#41687]
|  |  |
| --- | --- |
| Bugzilla Link | [42342](https://llvm.org/bz42342) |
| Version | unspecified |
| OS | All |
| CC | @d0k,@EugeneZelenko |

## Extended Description 
While testing llvm checkers, ran into this replacement on a random diff.

Plan to look into it, but adding it here so I don't loose track of it.

diff --git a/llvm/tools/llvm-nm/llvm-nm.cpp b/llvm/tools/llvm-nm/llvm-nm.cpp
index ae9bf60baeb..0e3ee1ed0b6 100644
--- a/llvm/tools/llvm-nm/llvm-nm.cpp
+++ b/llvm/tools/llvm-nm/llvm-nm.cpp
@@ -221,12 +221,12 @@ bool HadError = false;
 std::string ToolName;
 } // anonymous namespace

-static void error(Twine Message, Twine Path = Twine()) {
+static void error(Twine Message, std::string Path (= Twine()).str()) {
   HadError = true;
   WithColor::error(errs(), ToolName) << Path << ": " << Message << ".\n";
 }

-static bool error(std::error_code EC, Twine Path = Twine()) {
+static bool error(std::error_code EC, std::string Path (= Twine()).str()) {

**Comment by carlosgalvezp** [comment]
Cannot reproduce due to not being able to include `Opts.inc`, please provide self-contained minimal example, alternatively step-by-step instructions on how to reproduce.
