### ISSUE TITLE
Segfault when parsing use of static data member template with deduced type dependent on class template template parameter

### ISSUE THREAD

**Issue by eracpp** [llvm/llvm-project#41717]
|  |  |
| --- | --- |
| Bugzilla Link | [42372](https://llvm.org/bz42372) |
| Version | trunk |
| OS | All |
| CC | @zygoloid |

## Extended Description 
The following example (https://gcc.godbolt.org/z/lrNU6I):

template <typename> int C = 0;

template <template <typename> typename T>
struct S
{
    template <typename U>
    static auto const X = C<T<U>>;

    int x = X<void>;
};

Produces a stack dump (omitted program arguments flags due to verbosity; see the Compiler Explorer link above for full message):

Stack dump:
0.	Program arguments: ...
1.	<eof> parser at end of file
2.	<source>:4:1: parsing struct/union/class body 'S'
#&#8203;0 0x000055eb13de3c4a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/compiler-explorer/clang-trunk-20190624/bin/clang-9+0x2754c4a)
#&#8203;1 0x000055eb13de1a14 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-trunk-20190624/bin/clang-9+0x2752a14)
#&#8203;2 0x000055eb13de1b52 SignalHandler(int) (/opt/compiler-explorer/clang-trunk-20190624/bin/clang-9+0x2752b52)
#&#8203;3 0x00007ff38b971890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)
clang-9: error: unable to execute command: Segmentation fault (core dumped)
clang-9: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 254

The type of the static data member must be deduced (e.g. replacing `auto` with `int` avoids the segfault; `decltype(auto)` also works in place of `auto`). The static data member must be used (`X<void>`) to induce the segfault (e.g. removing `int x = X<void>;` avoids the segfault).

**Comment by Endilll** [comment]
Fixed in Clang 12: https://godbolt.org/z/4G94ddxbz
