### ISSUE TITLE
Go to declaration broken for overloaded functions in a template

### ISSUE THREAD

**Issue by 000d6c90-88ad-42ae-9bef-53127a15e612** [llvm/llvm-project#41748]
|  |  |
| --- | --- |
| Bugzilla Link | [42403](https://llvm.org/bz42403) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
Given the following snippet of code:

	int f(void);
	int f(int);
	int f(char);

	template<typename P>
	int funccall(P Param) {
		return f(Param);
	}

when asking clangd for the declaration of symbol f in function funccall the answer is "No declaration found for f". The same happens with go to definition.
 
This somehow makes sense, because it cannot decide which one of the three overloads is the right one.

However I think it might be a better solution in such cases to return a list of all the possible overloads, so that the user can at least see where they are located and choose the appropriate one on his own.

**Comment by HighCommander4** [comment]
This has been fixed since clangd 11.
