### ISSUE TITLE
[ARM] SCE optimization pass hoisting DIV operation outside of is-else BB as a speculative execution

### ISSUE THREAD

**Issue by aymanmusa** [llvm/llvm-project#41750]
|  |  |
| --- | --- |
| Bugzilla Link | [42405](https://llvm.org/bz42405) |
| Version | trunk |
| OS | Linux |
| Attachments | [reproducer mir file](https://user-images.githubusercontent.com/60654394/143759396-62327302-011e-4907-9dfd-a069d1c8411e.gz) |
| CC | @alinas,@anton-afanasyev,@aymanmusa,@igor-breger,@ornata,@qcolombet,@sdesmalen-arm,@TNorthover |

## Extended Description 

Attached is an MIR test (reproducer.mir) that shows a case where the original sequence performs the DIV operation only if the divisor is not 0. But after running MachineCSE pass we can see that the DIV was hoisted outside of the if-else BBs, what would result in an integer division by zero.

The command line for running the pass is:
llc -mtriple=aarch64-none-linux-gnu -run-pass=machine-cse -asm-verbose=1 -verify-machineinstrs reproducer.mir -o after-pass

Most likely that this bug was introduced in: https://reviews.llvm.org/rL362901.
Owner of the change is already investigating the issue.

**Comment by xgupta** [comment]
Hi,

Is this fixed? I think it is -  https://www.diffchecker.com/SvD3hVXM/.
