### ISSUE TITLE
Enable GitHub Commit Access

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#41773]
|  |  |
| --- | --- |
| Bugzilla Link | [42428](https://llvm.org/bz42428) |
| Version | unspecified |
| OS | Linux |
| Blocks | llvm/llvm-project#38741  |
| CC | @davezarzycki,@emaste,@hahnjo,@jryans,@LebedevRI,@RKSimon,@stephanemoore |

## Extended Description 
We need to grant GitHub commit access to all current SVN committers.

**Comment by asl** [comment]
@tstellar Closing?
