### ISSUE TITLE
__int128 stack calling conventions are incorrect on x86-64

### ISSUE THREAD

**Issue by stephenhines** [llvm/llvm-project#41784]
|  |  |
| --- | --- |
| Bugzilla Link | [42439](https://llvm.org/bz42439) |
| Version | trunk |
| OS | Linux |
| CC | @topperc,@gregbedwell,@RKSimon,@nickdesaulniers,@pogo59,@rotateright,@tstellar,@wjristow |

## Extended Description 
This is a bug report that was posted internally at Google, since the user can't register here on bugs.llvm.org:

Clang violates x86-64 calling convention in the obscure case when __int128 is passed on stack.

Conside the following two functions:

```
__int128 foo(__int128 x, __int128 y, __int128 z, uint64_t a, __int128 c) {
   return x + y + z + a + c;
}

__int128 foo(__int128 x, __int128 y, __int128 z, uint64_t a, uint64_t b, __int128 c) {
   return x + y + z + a + c;
}
```

Gcc generates identical code for these because __int128 have to be stored aligned on stack (psABI says:

  Arguments of type __int128 offer the same operations as INTEGERs, yet they do not fit into one general purpose register but require two registers.

For classification purposes __int128 is treated as if it were implemented as:
  typedef struct {
    long low, high;
  } __int128;
with the exception that arguments of type __int128 that are stored in memory must be aligned on a 16-byte boundary.

Clang generates different code for these two functions:
  https://godbolt.org/z/ZKjb4Z

Note that both GCC and Clang show the alignment of __int128 properly as 16 bytes, but this is only getting ignored when the variable is passed on the stack.

**Comment by nikic** [comment]
I was wondering why Clang's ABI handling doesn't end up passing this explicitly on the stack, and it seems like this is the reason: https://github.com/llvm/llvm-project/blob/91af0d0a669880918eda2d2bd2d6185b2903a402/clang/lib/CodeGen/Targets/X86.cpp#L2155-L2171

As the comment indicates the assumption is, indeed, optimistic...

**Comment by nikic** [comment]
Candidate patch: https://reviews.llvm.org/D158169
