### ISSUE TITLE
C++ compiler crashes on the code that uses stdatomic.h

### ISSUE THREAD

**Issue by 7ac8b810-20e7-405b-a8ed-c957e49b76cc** [llvm/llvm-project#41782]
|  |  |
| --- | --- |
| Bugzilla Link | [42437](https://llvm.org/bz42437) |
| Version | unspecified |
| OS | MacOS X |
| Attachments | [Piece if code to reporoduce the crash](https://user-images.githubusercontent.com/95090705/143759408-91198386-a551-461f-9e52-97045c52a252.gz) |
| CC | @Weverything |

## Extended Description 

clang compiler crashes on attempt to compile the attached piece of code, namely the attempt to get result of increment/decrement operation "a += step;" where "a" is atomic. First encountered with Apple LLVM clang version 9, reproduced with version 10 and older versions of the compiler on FreeBSD 11.

**Comment by AaronBallman** [comment]
I can no longer reproduce this issue with Clang trunk, so closing this as WORKSFORME.

**Comment by Endilll** [comment]
Fixed in Clang 10: https://godbolt.org/z/1rvxW9131
