### ISSUE TITLE
"NOCROSSREFS_TO" doesn't supported by LLVM's ld.lld

### ISSUE THREAD

**Issue by 44128753-b9b6-4faf-984b-690a6ca556cf** [llvm/llvm-project#41825]
|  |  |
| --- | --- |
| Bugzilla Link | [42480](https://llvm.org/bz42480) |
| Version | unspecified |
| OS | Linux |
| CC | @P1119r1m,@smithp35 |

## Extended Description 
Build fails on the use of "NOCROSSREFS_TO" command in linker script.

Example:
- funnyos.lds.S:
```
...
NOCROSSREFS_TO (.init .text .data)
...
ENTRY(_start)
...
```

Reported build/link error:
```
ld.lld: error: core/funnyos.lds:11: unknown directive: NOCROSSREFS_TO
>>> NOCROSSREFS_TO (.init .text .data)
>>> ^
```

P.S. Problem also reported on https://stackoverflow.com/questions/56235666/is-it-possible-to-use-nocrossrefs-to-in-linker-script-for-clangs-ld-lld

**Comment by nickdesaulniers** [comment]
It looks like `NOCROSSREFS` is also not supported yet by LLD.

This is breaking builds of 32b ARM with recent Spectre-BHB mitigations from linking with LLD.
https://github.com/ClangBuiltLinux/linux/issues/1609

**Comment by P1119r1m** [comment]
@nickdesaulniers IMHO this feature can be very useful in some cases. It's surprising that this hasn't been implemented in LLD yet.

**Comment by nickdesaulniers** [comment]
cc @stuij

**Comment by pskrgag** [comment]
Seems like this issue is kinda stale for a while, so I decided to try implementing it myself. 
I am new to llvm world, so let see how it will go

See #95714

**Comment by berkus** [comment]
Oooh nice! Thats a good one for OSdev, cheers!
