### ISSUE TITLE
building cross-tools on OpenBSD results in crash

### ISSUE THREAD

**Issue by elewarr** [llvm/llvm-project#41823]
|  |  |
| --- | --- |
| Bugzilla Link | [42478](https://llvm.org/bz42478) |
| Version | 8.0 |
| OS | OpenBSD |
| Attachments | [crash log excerpt](https://user-images.githubusercontent.com/95090703/143759423-f6b19b02-a50f-477a-b1ac-c6e451c8e6de.gz), [script](https://user-images.githubusercontent.com/95090703/143759424-14be12b6-410e-4a83-9389-386eb8e306ff.gz), [stack](https://user-images.githubusercontent.com/95090703/143759425-1a53a7b6-e362-486c-a301-9f7aa71e55c5.gz), [source code](https://user-images.githubusercontent.com/95090703/143759426-caf60b39-dc69-414b-b7d1-034b84539318.gz) |
| CC | @DimitryAndric,@elewarr,@zygoloid,@mordak |

## Extended Description 

I thought it would be a good idea to rebuild cross-tools because of LLVM version bump
but - with recent src - I'm unable to do so:
$ doas make -f Makefile.cross TARGET=${target} CROSSDIR="${destdir}" cross-tools
fails with:
aarch64-unknown-openbsd6: error: unable to execute command: Segmentation fault
(core dumped)

With updated /etc/mk.conf:
DEBUG=-gline-tables-only
(I think it’s unused for clang but disables stripping during installation?)

and src/gnu/usr.bin/clang/Makefile.inc:
CPPFLAGS+=      -DNDEBUG -gline-tables-only
(I think it’s similar to what cmake RelWithDebugInfo does.)

I was eventually able to get debug symbols. More details in attached files.
I reproduced this crash on other machine.

If anyone would like to give it a quick try, then please just follow „Setup” section from:
https://github.com/elewarr/openbsd-arm64-src-dev

**Comment by brad0** [comment]
> I do not observe the issue any longer, with this, Todd Mortimer's commit: [openbsd/src@ac01d30#diff-8ee0f7b66d1ab05714573fc556fbd7ff](https://github.com/openbsd/src/commit/ac01d30ce880eeb475479bed69a1fa12c43f3cfd#diff-8ee0f7b66d1ab05714573fc556fbd7ff)

Thanks.
