### ISSUE TITLE
Inconsistent output when running clang-format twice (keywords: idempotent, fixpoint)

### ISSUE THREAD

**Issue by 5eb4242a-8752-4f36-9f0c-ee925bd2ebee** [llvm/llvm-project#41854]
|  |  |
| --- | --- |
| Bugzilla Link | [42509](https://llvm.org/bz42509) |
| Version | trunk |
| OS | Linux |
| CC | @Kokan,@hartwork |

## Extended Description 
Single runs and double runs of the `clang-format' are not consistent between themselves. See the example below.

file: example.cc:
--------------------------
void foo() {
    /* Empty */
}

Single run
----------------------------
$ style=LLVM; cat example.cc | clang-format --style=${style}

Result:
void foo() { /* Empty */ }

Double run
----------------------------
$ style=LLVM; cat example.cc | clang-format --style=${style} | clang-format --style=${style}

Result:
void foo() { /* Empty */
}

The same is for style=Google.

Mozilla, Chromium and WebKit styles (obviously) work fine. (These probably do not merge an empty function into one line.)

Version:
----------------
$ clang-format --version
clang-format version 9.0.0 (https://github.com/llvm-mirror/clang.git b5cfeee0a6e73044cc755e2ab08145056b2d3fd4) (https://github.com/llvm-mirror/llvm.git 57b4161e8fc497386cebf223cb8a26896303cb05)

**Comment by Da-Viper** [comment]
@Endilll  This bug does not occur anymore 

see https://godbolt.org/z/e4Wqjz871

**Comment by owenca** [comment]
This bug has not been fixed yet. Using either 17.0.6 or main:
```
$ cat test.cpp
void foo() { /* Empty */ }
$ clang-format test.cpp
void foo() { /* Empty */
}
```
