### ISSUE TITLE
fatal error: error in backend: Cannot select: intrinsic %llvm.coro.resume

### ISSUE THREAD

**Issue by Quuxplusone** [llvm/llvm-project#41875]
|  |  |
| --- | --- |
| Bugzilla Link | [42530](https://llvm.org/bz42530) |
| Version | trunk |
| OS | All |
| Attachments | [test-1ed13d.sh (run script produced by Clang)](https://user-images.githubusercontent.com/702021/143759450-fa104b20-9dfb-422a-a404-95840e5775fb.gz), [The un-reduced test case. Fails with "Cannot select: intrinsic %llvm.coro.destroy"](https://user-images.githubusercontent.com/702021/143759451-8b5f2e30-6958-413f-811a-93c3dc5cb9f5.gz) |

## Extended Description 

Since the ICE message talks about the "backend", I wonder if this is an indication that -fcoroutines-ts just isn't implemented for Mac OSX yet. (I'm on OSX 10.11.6, but using an LLVM/Clang that was built from master.)

The following test case is extremely reduced.

====

cat > test.c <<EOF
void *f();
int main() {
    void *coro = f();
    __builtin_coro_resume(coro);
}
EOF
clang -fcoroutines-ts -c test.c

====

fatal error: error in backend: Cannot select: intrinsic %llvm.coro.resume
clang-9: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 9.0.0 (git@github.com:Quuxplusone/clang.git 0b0fedcf8ea844fb1ad956f418825b3b17154e16) (https://git.llvm.org/git/llvm.git f528f0e60898197fde2faf503c36abad5e033dd8)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Users/ajo/Desktop/push.root/llvm/build/bin
clang-9: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-9: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-9: note: diagnostic msg: /var/folders/1z/jvnkrdws621c6wmrcf7q_9180000gn/T/test-1ed13d.c
clang-9: note: diagnostic msg: /var/folders/1z/jvnkrdws621c6wmrcf7q_9180000gn/T/test-1ed13d.sh
clang-9: note: diagnostic msg: Crash backtrace is located in
clang-9: note: diagnostic msg: /Users/ajo/Library/Logs/DiagnosticReports/clang-9_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang-9: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang-9: note: diagnostic msg: 

********************

**Comment by Endilll** [comment]
Appears to be fixed in Clang 12: https://godbolt.org/z/P7qPdxcxT
Doesn't reproduce in C++20 mode on post-17 trunk: https://godbolt.org/z/5PP1TahP5
