### ISSUE TITLE
Invalid readability-simplify-boolean-expr suggestion on non-compilable code

### ISSUE THREAD

**Issue by igor-akhmetov** [llvm/llvm-project#41874]
|  |  |
| --- | --- |
| Bugzilla Link | [42529](https://llvm.org/bz42529) |
| Version | unspecified |
| OS | Windows NT |
| CC | @EugeneZelenko,@LegalizeAdulthood |

## Extended Description 
On the code snippet below readability-simplify-boolean-expr complains about the entire body of operator== and suggests to replace it with "return !", even though the code does not compile (see https://gcc.godbolt.org/z/xzKfDB):

#include <vector>

struct Card
{
    bool operator!=(const Card& other) const noexcept
    {
        return false;
    }
};

struct CardEncyclopedia
{
    std::vector<const Card&> cards;
    
    bool operator==(const CardEncyclopedia& other) noexcept
    {
        if (cards.size() != other.cards.size())
            return false;

        for (size_t i = 0; i < other.cards.size(); ++i)
            if (cards.at(i) != other.cards.at(i))
                return false;

        return true;
    }
};

**Comment by LegalizeAdulthood** [comment]
@igor-akhmetov Is this still a problem?  Latest clang-tidy on godbolt.org doesn't seem to reproduce the problem:

https://gcc.godbolt.org/z/r4osxrjha

**Comment by LegalizeAdulthood** [comment]
Hrm, it seems I fixed the compilation errors in my godbolt link, which is the whole point of this bug `:)`

I don't think clang-tidy makes any guarantees about the proposed fixes when the code itself doesn't compile.

**Comment by igor-akhmetov** [comment]
I understand that clang-tidy's original purpose was to work only with compilable code. These days however more and more IDEs (like Visual Studio, CLion, etc.) run clang-tidy continuously as a code analysis tool, often on incomplete code. The ability to gracefully handle incorrect code is desirable in this scenario.

**Comment by LegalizeAdulthood** [comment]
While I agree that is desirable, the scope is much larger than just this one check.  Everything in clang-tidy would probably need to be revisited for it to be robust in the face of compile errors.  I don't even know how I would detect this scenario in my check.

**Comment by carlosgalvezp** [comment]
Problem described in OP no longer visible on trunk (only the compiler errors)
