### ISSUE TITLE
llgo doesn't compile in current llvm master

### ISSUE THREAD

**Issue by berolinux** [llvm/llvm-project#41893]
|  |  |
| --- | --- |
| Bugzilla Link | [42548](https://llvm.org/bz42548) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
Trying to enable llgo on a current (2019/07/09) llvm-project git checkout results in:

llgo: /home/bero/temp/abf/llvm/BUILD/llvm-9.0.0-20190708/llvm/lib/IR/Attributes.cpp:233: llvm::Type *llvm::Attribute::getValueAsType() const: Assertion `isTypeAttribute() && "Invalid attribute type to get the value as a type!"' failed.
SIGABRT: abort
PC=0x7f8debf2e4c7 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f8debf2e4c7
[...]
goroutine 1 [syscall]:
runtime.cgocall(0x8d0440, 0xc0001632c8, 0xc0001632d0)
        /usr/lib/golang/src/runtime/cgocall.go:128 +0x5b fp=0xc000163298 sp=0xc000163260 pc=0x5d926b
llvm.org/llvm/bindings/go/llvm._Cfunc_LLVMAddAttributeAtIndex(0x15cc908, 0x3, 0x15eb340)
        _cgo_gotypes.go:687 +0x45 fp=0xc0001632c8 sp=0xc000163298 pc=0x808e35
llvm.org/llvm/bindings/go/llvm.Value.AddAttributeAtIndex.func1(0x15cc908, 0x3, 0x15eb340)
        /tmp/gopath529316603/src/llvm.org/llvm/bindings/go/llvm/ir.go:1154 +0x98 fp=0xc000163300 sp=0xc0001632c8 pc=0x838698
llvm.org/llvm/bindings/go/llvm.Value.AddAttributeAtIndex(0x15cc908, 0x3, 0x15eb340)
        /tmp/gopath529316603/src/llvm.org/llvm/bindings/go/llvm/ir.go:1154 +0x3f fp=0xc000163328 sp=0xc000163300 pc=0x82458f
llvm.org/llgo/irgen.(*functionTypeInfo).declare(0xc0000b9860, 0x15ecb20, 0x2cfd9f, 0xb, 0xc0001639e8)
        /tmp/gopath529316603/src/llvm.org/llgo/irgen/cabi.go:526 +0xf0 fp=0xc000163388 sp=0xc000163328 pc=0x888b60
llvm.org/llgo/irgen.(*runtimeFnInfo).init(0xc0000dd6a8, 0xc000130f80, 0x15ecb20, 0x2cfd9f, 0xb, 0xc000163ed8, 0x4, 0x4, 0xc0001639e8, 0x1, ...)
        /tmp/gopath529316603/src/llvm.org/llgo/irgen/runtime.go:31 +0x161 fp=0xc000163480 sp=0xc000163388 pc=0x894671
llvm.org/llgo/irgen.newRuntimeInterface(0x15ecb20, 0xc000130f80, 0x25, 0x1, 0x1)
        /tmp/gopath529316603/src/llvm.org/llgo/irgen/runtime.go:507 +0x34bb fp=0xc0001657d8 sp=0xc000163480 pc=0x897e2b
llvm.org/llgo/irgen.(*compiler).compile(0xc0001080f0, 0xc0000bab40, 0xc00009e4e0, 0x2, 0x2, 0x7ffc1650c35e, 0xb, 0x0, 0x0, 0x0)
        /tmp/gopath529316603/src/llvm.org/llgo/irgen/compiler.go:233 +0x4de fp=0xc0001658d8 sp=0xc0001657d8 pc=0x88d49e
llvm.org/llgo/irgen.(*Compiler).Compile(0xc00010a2c0, 0xc0000bab40, 0xc00009e4e0, 0x2, 0x2, 0x7ffc1650c35e, 0xb, 0x0, 0x0, 0x0)
        /tmp/gopath529316603/src/llvm.org/llgo/irgen/compiler.go:131 +0x14c fp=0xc000165950 sp=0xc0001658d8 pc=0x88cb2c
main.performAction(0xc000165e38, 0x1, 0xc0000ae280, 0x2, 0x2, 0xc0000b2128, 0x5, 0x0, 0x0)
        /tmp/gopath529316603/src/llvm.org/llgo/cmd/gllgo/gllgo.go:604 +0x160c fp=0xc000165bd0 sp=0xc000165950 pc=0x8cd6fc
main.performActions(0xc000165e38, 0x0, 0x0)
        /tmp/gopath529316603/src/llvm.org/llgo/cmd/gllgo/gllgo.go:811 +0x357 fp=0xc000165cc0 sp=0xc000165bd0 pc=0x8ce487
main.main()
        /tmp/gopath529316603/src/llvm.org/llgo/cmd/gllgo/gllgo.go:835 +0xe0 fp=0xc000165f98 sp=0xc000165cc0 pc=0x8ce910
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:200 +0x20c fp=0xc000165fe0 sp=0xc000165f98 pc=0x6033bc
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000165fe8 sp=0xc000165fe0 pc=0x62d691

rax    0x0
rbx    0x7f8dec2ea000
rcx    0x7f8debf2e4c7
rdx    0x0
rdi    0x2
rsi    0x7ffc1650abd0
rbp    0x7f8dec096290
rsp    0x7ffc1650abd0
r8     0x0
r9     0x7ffc1650abd0
r10    0x8
r11    0x246
r12    0x7f8dec925679
r13    0xe9
r14    0x7f8deca0e8b6
r15    0x200
rip    0x7f8debf2e4c7
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

**Comment by xgupta** [comment]
llgo is not in the repo anymore.
