### ISSUE TITLE
Template static constexpr bool class variable inside static_assert always pass

### ISSUE THREAD

**Issue by ofats** [llvm/llvm-project#41900]
|  |  |
| --- | --- |
| Bugzilla Link | [42555](https://llvm.org/bz42555) |
| Version | 9.0 |
| OS | Linux |
| CC | @ofats,@zygoloid |

## Extended Description 
There is a minimal example of code, that compiles on clang, but should not:
--------------------
template <class...>
struct foo {
    template <class...>
    static constexpr bool boo = false;

    void goo() {
        static_assert(boo<>, "");
    }
};
int main() {
    foo<> f;
    f.goo();
}
----------
Msvc and gcc deny to compile such a code with 'static assertion failed' error, as it should be.
Also godbolt example: https://godbolt.org/z/IaYnX5

**Comment by Endilll** [comment]
Appears to be fixed in Clang 10: https://godbolt.org/z/YP5WaWavY
