### ISSUE TITLE
Merge r359066 into the 8.0 branch

### ISSUE THREAD

**Issue by jdoerfert** [llvm/llvm-project#41903]
|  |  |
| --- | --- |
| Bugzilla Link | [42558](https://llvm.org/bz42558) |
| Version | 8.0 |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
As noted here, llvm/llvm-project#40876 #c2, this was a revert/fix for a bug introduced by r350917.

**Comment by arsenm** [comment]
Old release
