### ISSUE TITLE
"ran out of registers" while building i386 linux kernel

### ISSUE THREAD

**Issue by 9816046d-d175-4de2-95d1-ce389e5190e8** [llvm/llvm-project#41914]
|  |  |
| --- | --- |
| Bugzilla Link | [42569](https://llvm.org/bz42569) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#4440  |
| CC | @Aaron1011,@topperc,@efriedma-quic,@fhahn,@RKSimon,@MatzeB,@nickdesaulniers,@qcolombet,@zygoloid,@rotateright |

## Extended Description 
One file in the linux kernel produces an internal error from the register allocator. I reduced the test case to this:

```c
typedef int (*tune_freq_func_t)(int , void * tuneargs);
static struct {
  int power_up;
  int power_down;
  tune_freq_func_t fm_tune_freq;
  tune_freq_func_t am_tune_freq;
  int fm_rsq_status;
  int agc_status;
  int intb_pin_cfg;
} a[1];
int b, c;
int fn1(void) { return a[c].fm_tune_freq(b, fn1); }
```
```sh
$ clang-9 -m32 -mregparm=3 -O2 -fno-strict-overflow -c si476x-cmd.c
error: ran out of registers during register allocation
1 error generated.
```

See https://godbolt.org/z/aQ96HC

**Comment by nickdesaulniers** [comment]
Perhaps relevant to `-fno-omit-frame-pointer`. It looks like gcc-8 stopped obeying that for `-m32`. That's probably what's causing register pressure for LLVM.

https://godbolt.org/z/a7K8dddPG

**Comment by nickdesaulniers** [comment]
Perhaps a clang-12 regression?
https://godbolt.org/z/fos3r6x7d

**Comment by nickdesaulniers** [comment]
> Perhaps a clang-12 regression? https://godbolt.org/z/fos3r6x7d

Bisection converged on https://reviews.llvm.org/D83996. (cc @topperc ); doesn't look like a regression per se. But it definitely looks like having a scheduling model or not affects this, since we were also seeing issues for `-march=atom`.

**Comment by topperc** [comment]
There are two copies from EAX and EDX into virtual regsiters at the start of the function immediately after isel. Those got re-scheduled after the inline assembly which oversubscribed the register allocator for the inline assembly.

**Comment by topperc** [comment]
Adding 

```
def  : InstRW<[WriteMove], (instrs COPY)>;
```

to the SandyBridge scheduler model makes it go away.

**Comment by nickdesaulniers** [comment]
Uploaded a test case to pre-commit/demonstrate a diff once we agree on a fix: https://reviews.llvm.org/D122348.

From discord:
>> (Nick): so @ctopper IIUC, because the copies of EAX+EDX are made AFTER the inline asm, the live range of EAX+EDX are extended across the inline asm where previously they were not, which removes EAX+EDX from the available physreg pool that regalloc has to work with for the INLINEASM?

> (Craig): that was the conclusion I came to

**Comment by nickdesaulniers** [comment]
> Adding
> 
> ```
> def  : InstRW<[WriteMove], (instrs COPY)>;
> ```
> 
> to the SandyBridge scheduler model makes it go away.

https://reviews.llvm.org/D122350 is a tentative patch, but is touching the schedule model really the right fix? Shouldn't we modify instruction scheduling to account for (or straight up avoid) extending live ranges of physregs across INLINEASM statements?

**Comment by nickdesaulniers** [comment]
> Shouldn't we modify instruction scheduling to account for (or straight up avoid) extending live ranges of physregs across INLINEASM statements?

[`isSchedBoundary`](https://github.com/llvm/llvm-project/blob/fcca10c69aaab539962d10fcc59a5f074b73b0de/llvm/lib/CodeGen/MachineScheduler.cpp#L462) looks interesting.

**Comment by phoebewang** [comment]
I think this may have big impact to current use of inline asm, given out of registers cases are rare.
How about sum the reg with the same class and check the pressure:
```
TargetRegisterInfo *TRI = MF->getSubtarget().getRegisterInfo();
...
for (int I = 0; I < N; ++I)
  if (TRI->getRegPressureLimit(RC[I], *MF) < RCCount[I])
    return true;
```

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D124308 PTAL

**Comment by nickdesaulniers** [comment]
I just landed a patch that will ship in clang-15. It makes it less likely that we schedule `mov`s in a way that extends the LiveRange of phyregs across inline asm in a way that RegAlloc will fail.

That said, the MachineScheduler is still not hardened from this re-occuring. Ideally, the scheduler could check if reordering a mov across an inlineasm would produce unsatisfiable constraints on the register allocator.  IIRC, MachineScheduler just uses a priority queue insertion to order instructions that don't have data dependencies between them.  So this might not be the last time we see this issue, but my patch should help a bit.  Closing for now, but let's open a new bug report with more test cases if we can still reproduce this with clang-15.

(My patch allows both test cases by @arndb to compile without issue)

**Comment by nickdesaulniers** [comment]
As is tradition, I spoke to soon. This fixes one of our instances for no `-march=`, but for `-march=atom` we see yet another instance.
https://github.com/ClangBuiltLinux/linux/issues/1589

**Comment by RKSimon** [comment]
@nickdesaulniers  Is this on 32-bit atom builds? We always use ILP on Atom CPU targets which is going to waste registers that 32-bit can't really afford.
```
  // For 64-bit, since we have so many registers, use the ILP scheduler.
  // For 32-bit, use the register pressure specific scheduling.
  // For Atom, always use ILP scheduling.
  if (Subtarget.isAtom())
    setSchedulingPreference(Sched::ILP);
  else if (Subtarget.is64Bit())
    setSchedulingPreference(Sched::ILP);
  else
    setSchedulingPreference(Sched::RegPressure);
```

**Comment by nickdesaulniers** [comment]
> Is this on 32-bit atom builds?

No. 64b ATOM.

926afd74010f437850540d58fbcf620d80c28d67 looks like it moved 32b atom from hybrid to ilp.

If I change atom to hybrid, I can _still_ reproduce the register exhaustion compilation failure. Same for `RegPressure`.

Maybe I should be looking at the `operator()` overloads for the derived classes of `queue_sort`.

I've posted a smaller reproducer [here](https://github.com/ClangBuiltLinux/linux/issues/1589#issuecomment-1120020594).
