### ISSUE TITLE
[7 Regression] Lambda call in template parameter causes compile time error

### ISSUE THREAD

**Issue by apolukhin** [llvm/llvm-project#41945]
|  |  |
| --- | --- |
| Bugzilla Link | [42600](https://llvm.org/bz42600) |
| Version | 7.0 |
| OS | Linux |
| CC | @apolukhin,@dwblaikie,@GabrielRavier,@riccibruno,@zygoloid |

## Extended Description 
Following example compiles in Clang-6 and GCC with flags "-O2 -std=c++17", but fail to compile in Clang-7, Clang-8 and trunk:

template <int I> struct stuff {};
stuff< [](){ return 42; }() > a; // Calling a constexpr lambda

Error message: lambda expression cannot appear in this context

**Comment by cor3ntin** [comment]
This works in std=c++20 mode
