### ISSUE TITLE
clang-format badly format .clang-format config file

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#41969]
|  |  |
| --- | --- |
| Bugzilla Link | [42624](https://llvm.org/bz42624) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @hartwork |

## Extended Description 
To reproduce, create a .clang-format config file:

    BasedOnStyle: Chromium
    ---
    Language: Java
    BasedOnStyle: Google
    ---

Then the following command wrongly put everything on the same line. 
    % clang-format -i .clang-format

This leads to the following error subsequently (when using clang-format on other files):

    YAML:1:39: error: Unexpected token. Expected Key or Block End
    BasedOnStyle : Chromium-- - Language : Java BasedOnStyle : Google-- -
                                      ^
    Error reading /dummy/.clang-format: Invalid argument

This is likely to happen (and surprising) when formatting a whole code base:
    % git ls-files | xargs clang-format -i

**Comment by mydeveloperday** [comment]
As mentioned its git-clang-format, or the 3rd party plugins responsibility as to what extensions it supports, when running on the command line then its upto the command line (this gives clang-format the most power)

Unless we add the ability for clang-format to clang-format yaml (which I'd like to do) then I think this isn't really a bug here.
