### ISSUE TITLE
Transform (1 << (x NUW+ 1)) to (2 << x)

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#41976]
|  |  |
| --- | --- |
| Bugzilla Link | [42631](https://llvm.org/bz42631) |
| Version | trunk |
| OS | Linux |
| CC | @topperc,@LebedevRI,@RKSimon,@zygoloid,@rotateright |

## Extended Description 
```
%a = add nuw i32 %x, 1
%r = shl i32 1, %a
  =>
%r = shl i32 2, %x

Done: 1
Optimization is correct!
```
```
int v1(unsigned x) {
    return (2 << x);
}

int v2(unsigned x) {
    return (1 << (x+1));
}
```
```
v1:                                     # @v1
        mov     ecx, edi
        mov     eax, 2
        shl     eax, cl
        ret
v2:                                     # @v2
        lea     ecx, [rdi + 1]
        mov     eax, 1
        shl     eax, cl
        ret
```
Worth to do? Opinions?

**Comment by rotateright** [comment]
With 'nuw' on the add, this generalizes to any shift opcode and could even apply when the increment and shift value are not constants (although I'm not sure if we want to go that far):
https://alive2.llvm.org/ce/z/a9WPD2
