### ISSUE TITLE
Floating point asm constraint for arm target without floating point should give error

### ISSUE THREAD

**Issue by john-brawn-arm** [llvm/llvm-project#41986]
|  |  |
| --- | --- |
| Bugzilla Link | [42641](https://llvm.org/bz42641) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
If you have some inline asm that has a constraint that specifies a floating-point register, e.g.

  float func(float t)
  {
    __asm__ ( "" : "=w" (t) );
    return t;
  }

then compiling for an arm cpu without floating point (e.g. --target=arm -mcpu=cortex-m3) using a build of clang with asserts enabled you get

  llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp:65: bool llvm::DAGTypeLegalizer::SoftenFloatResult(llvm::SDNode*, unsigned int): Assertion `isLegalInHWReg(N->getValueType(ResNo)) && "Unsupported SoftenFloatRes opcode!"' failed.

or with a build without asserts you end up in an endless loop in SelectionDAG.

We should be rejecting this code early and giving an error. It looks like ARMTargetInfo::validateAsmConstraint is probably the place to do this.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 14: https://godbolt.org/z/aoGbvsf5q
