### ISSUE TITLE
Allow linking of fPIC objects into regular executables.

### ISSUE THREAD

**Issue by sbc100** [llvm/llvm-project#42001]
|  |  |
| --- | --- |
| Bugzilla Link | [42656](https://llvm.org/bz42656) |
| Version | unspecified |
| OS | Linux |
| CC | @MaskRay,@sbc100,@smithp35 |

## Extended Description 
Currently this is not supported under wasm but is supported on other platforms.

We have a couple of options for how to implement this:

1. Linker relaxation

This would rewrite the "get_global + load/store" and "get_global + call_indirect" into simple load/start or call_indirect instructions. 

2. Create module-internal globals for address and table offsets.  

I think I'll start with (2) since is simple and doesn't involve any new relocation types.

**Comment by TerrorJack** [comment]
To my best knowledge, it already works as of today? cc @sbc100

**Comment by sbc100** [comment]
yes, this has be fixed for a while now IIUC.
