### ISSUE TITLE
ArgumentPromotion unpacks recursive types endlessly

### ISSUE THREAD

**Issue by jdoerfert** [llvm/llvm-project#42028]
|  |  |
| --- | --- |
| Bugzilla Link | [42683](https://llvm.org/bz42683) |
| Version | trunk |
| OS | Linux |
| Attachments | [reproducer](https://user-images.githubusercontent.com/6248191/143759501-3a2b44c5-9619-46b8-aed1-c83634da0236.gz) |

## Extended Description 

ArgumentPromotion checks for "self recursive" functions but not for recursion that involves more than one function. This code was a "fix" for llvm/llvm-project#9304 .

Reproducer is attached.

**Comment by nikic** [comment]
This issue still exists.

**Comment by nikic** [comment]
Candidate patch: https://reviews.llvm.org/D119418
