### ISSUE TITLE
clang-format does not format local scopes properly.

### ISSUE THREAD

**Issue by e0e1e613-dccb-47a5-85db-3dc989429265** [llvm/llvm-project#42038]
|  |  |
| --- | --- |
| Bugzilla Link | [42693](https://llvm.org/bz42693) |
| Version | unspecified |
| OS | All |

## Extended Description 
Hi

For some reason clang format could not format my file correctly:
https://github.com/DenisYaroshevskiy/type_erasure_example/blob/c3e0d666421e4192b1e81675190dd2d286017868/slide_code.cc#L327

clang-format-mp-7.0 --version
clang-format version 7.0.1 (tags/RELEASE_701/final)

**Comment by rymiel** [comment]
Duplicate of https://github.com/llvm/llvm-project/issues/33891, with an extra caveat of having a trailing semicolon
