### ISSUE TITLE
Error occured during tensorflow demo apk build using bazel

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#42032]
|  |  |
| --- | --- |
| Bugzilla Link | [42687](https://llvm.org/bz42687) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Error in bazel with tensorflow demo](https://user-images.githubusercontent.com/60944935/143759502-f9ca24cc-afc7-46e1-a5f0-01d8f6d59319.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 

I was following the instructions in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android
I installed bazel 0.26.1, NDK r18b, SDK 29 on Ubuntu 16.04 by VirtualBox. Bazel gave me this error:

#####
ERROR: /home/algensrain/tf/tensorflow/tensorflow/core/kernels/BUILD:6521:1: C++ compilation of rule '//tensorflow/core/kernels:android_tensorflow_kernels' failed (Exit 254)
clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)

Android (4751641 based on r328903) clang version 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242ddd5815e4a043907ea9004281) (https://android.googlesource.com/toolchain/llvm 1d739ffb0366421d383e04ff80ec2ee591315116) (based on LLVM 7.0.2svn)
Target: armv7-none-linux-android
Thread model: posix
InstalledDir: external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/cwise_op_div-fa0869.cpp
clang: note: diagnostic msg: /tmp/cwise_op_div-fa0869.sh
clang: note: diagnostic msg:

********************
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1806.650s, Critical Path: 612.95s
INFO: 776 processes: 776 local.
FAILED: Build did NOT complete successfully
#####

I'm really bad at those things and I couldn't find any answers for this. Please help.

**Comment by Endilll** [comment]
Attached archive contains an empty directory.
Unfortunately, we can't do much without preprocessed source.
Feel free to reopen if you have additional information.
