### ISSUE TITLE
wasm-ld: error: /tmp/wasm-shared-issue-60c549.o: relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol .L.str; recompile with -fPIC

### ISSUE THREAD

**Issue by 77f8885d-0e02-4d3a-84c7-fc7229c8e3dd** [llvm/llvm-project#42059]
|  |  |
| --- | --- |
| Bugzilla Link | [42714](https://llvm.org/bz42714) |
| Version | trunk |
| OS | Linux |
| Attachments | [C code that produces this issue](https://user-images.githubusercontent.com/93436051/143759512-c37ae677-70b4-4c2d-9c78-ffac1c0fe42e.gz) |
| CC | @sbc100 |

## Extended Description 

The attached C code fails to build with "clang --target=wasm32-unknown-unknown -fPIC -nostdlib -Wl,--shared -Wl,--export-all wasm-shared-issue.c".

**Comment by sbc100** [comment]
I believe this was fixed in https://reviews.llvm.org/D153293
