### ISSUE TITLE
Fix for readability-redundant-declaration breaks code if linkage specification is used

### ISSUE THREAD

**Issue by igor-akhmetov** [llvm/llvm-project#42068]
|  |  |
| --- | --- |
| Bugzilla Link | [42723](https://llvm.org/bz42723) |
| Version | unspecified |
| OS | Windows NT |
| CC | @EugeneZelenko |

## Extended Description 
Fix for readability-redundant-declaration changes this snippet:

extern "C" int x;
extern "C" int x;

into this:

extern "C" int x;
extern "C"

**Comment by PiotrZSL** [comment]
Reproduced on main (LLVM 17).

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D146904
