### ISSUE TITLE
compiler infinite loop aliasing bcmp to memcmp

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#42073]
|  |  |
| --- | --- |
| Bugzilla Link | [42728](https://llvm.org/bz42728) |
| Version | trunk |
| OS | Linux |
| Attachments | [string.i](https://user-images.githubusercontent.com/1823839/143759517-dd19c0e4-bc92-48a6-9a18-7a7b378ae966.gz) |
| CC | @legrosbuffle,@zmodem,@jyknight,@stephenhines |

## Extended Description 

Possibly related to llvm/llvm-project#40380 .

declaring bcmp as an alias to memcmp, then using memcmp in a way that it would be lowered to a bcmp is resulting in the compiler not exiting.

Attached is a test case. Observable at -O1 and above, but not -O0.

Instead, I can work around this with an explicit tail call, but it's curious as to why the addition of the alias causing the compiler to hang.

**Comment by xgupta** [comment]
seems to fixed on trunk -  https://godbolt.org/z/Pn1ohj56a.
