### ISSUE TITLE
44: bool clang::APValue::isNullPointer() const: Assertion `isLValue() && "Invali d usage"' failed.

### ISSUE THREAD

**Issue by 1bbe8459-b61d-4fb9-b776-cb06be62cdb7** [llvm/llvm-project#42098]
|  |  |
| --- | --- |
| Bugzilla Link | [42753](https://llvm.org/bz42753) |
| Version | trunk |
| OS | Linux |
| Attachments | [Run script](https://user-images.githubusercontent.com/92601271/143759530-80478009-0f61-4628-9c56-4deb4e7a3249.gz), [Preprocessed source](https://user-images.githubusercontent.com/92601271/143759531-71a598ab-8a73-4461-9941-7ac54eb2df1e.gz) |
| CC | @zygoloid,@vgvassilev |

## Extended Description 
[1775/2160] Building CXX object router...ng_view.dir/test_stdx_string_view.cc.o
FAILED: router/src/harness/tests/CMakeFiles/routertest_harness_stdx_string_view.dir/test_stdx_string_view.cc.o
/export/home/tmp/usr/bin/clang++  -DHAVE_CONFIG_H -DHAVE_LIBEVENT2 -DHAVE_OPENSSL -DHAVE_TLSv13 -DLZ4_DISABLE_DEPRECATE_WARNINGS -DRAPIDJSON_NO_SIZETYPEDEFINE -DRAPIDJSON_SCHEMA_USE_INTERNALREGEX=0 -DRAPIDJSON_SCHEMA_USE_STDREGEX=1 -DUNISTR_FROM_CHAR_EXPLICIT=explicit -DUNISTR_FROM_STRING_EXPLICIT=explicit -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_USE_MATH_DEFINES -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I. -Iinclude -I/export/home/tmp/clones/_bug_30041367 -I/export/home/tmp/clones/_bug_30041367/include -Irouter -Irouter/include -I/export/home/tmp/clones/_bug_30041367/router/src/harness/include -I/export/home/tmp/clones/_bug_30041367/router/src/harness/src/../include -Irouter/src/harness/src/src_SHARED -I/export/home/tmp/clones/_bug_30041367/router/src/router/src/../include -I/export/home/tmp/clones/_bug_30041367/router/src/rest_api/src/../include -I/export/home/tmp/clones/_bug_30041367/router/src/http/src -I/export/home/tmp/clones/_bug_30041367/router/src/http/src/../include -Irouter/src/http/src/../include -I/export/home/tmp/clones/_bug_30041367/router/src/mock_server/include -I/export/home/tmp/clones/_bug_30041367/router/src/http/include -isystem /export/home/tmp/clones/_bug_30041367/extra/rapidjson/include -isystem /export/home/tmp/clones/_bug_30041367/extra/lz4 -isystem /export/home/tmp/clones/_bug_30041367/extra/libedit/editline -isystem /export/home/tmp/clones/_bug_30041367/extra/zstd/lib -isystem extra/zlib -isystem /export/home/tmp/clones/_bug_30041367/extra/zlib -isystem /usr/global/share/googletest-release-1.8.0/googlemock -isystem /usr/global/share/googletest-release-1.8.0/googlemock/include -isystem /usr/global/share/googletest-release-1.8.0/googletest -isystem /usr/global/share/googletest-release-1.8.0/googletest/include -std=c++14 -fno-omit-frame-pointer  -fsanitize=thread -O1 -fno-inline -Wall -Wextra -Wformat-security -Wvla -Wundef -Wmissing-format-attribute -Woverloaded-virtual -Wcast-qual -Wno-null-conversion -Wno-unused-private-field -Wconditional-uninitialized -Wdeprecated -Wextra-semi -Wheader-hygiene -Wnon-virtual-dtor -Wundefined-reinterpret-cast -Winconsistent-missing-destructor-override -Wshadow-field -DSAFE_MUTEX -DENABLED_DEBUG_SYNC -g -fPIE -MD -MT router/src/harness/tests/CMakeFiles/routertest_harness_stdx_string_view.dir/test_stdx_string_view.cc.o -MF router/src/harness/tests/CMakeFiles/routertest_harness_stdx_string_view.dir/test_stdx_string_view.cc.o.d -o router/src/harness/tests/CMakeFiles/routertest_harness_stdx_string_view.dir/test_stdx_string_view.cc.o -c /export/home/tmp/clones/_bug_30041367/router/src/harness/tests/test_stdx_string_view.cc
clang-10: /export/home/tmp/tools/llvm.git/llvm/tools/clang/lib/AST/APValue.cpp:744: bool clang::APValue::isNullPointer() const: Assertion `isLValue() && "Invalid usage"' failed.
Stack dump:
0.      Program arguments: /export/home/tmp/usr/bin/clang-10 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -main-file-name test_stdx_string_view.cc -mrelocation-model pic -pic-level 2 -pic-is-pie -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -coverage-notes-file /export/home/tmp/build/_bug_30041367__clangT/router/src/harness/tests/CMakeFiles/routertest_harness_stdx_string_view.dir/test_stdx_string_view.cc.gcno -resource-dir /export/home/tmp/usr/lib/clang/10.0.0 -dependency-file router/src/harness/tests/CMakeFiles/routertest_harness_stdx_string_view.dir/test_stdx_string_view.cc.o.d -sys-header-deps -MT router/src/harness/tests/CMakeFiles/routertest_harness_stdx_string_view.dir/test_stdx_string_view.cc.o -isystem /export/home/tmp/clones/_bug_30041367/extra/rapidjson/include -isystem /export/home/tmp/clones/_bug_30041367/extra/lz4 -isystem /export/home/tmp/clones/_bug_30041367/extra/libedit/editline -isystem /export/home/tmp/clones/_bug_30041367/extra/zstd/lib -isystem extra/zlib -isystem /export/home/tmp/clones/_bug_30041367/extra/zlib -isystem /usr/global/share/googletest-release-1.8.0/googlemock -isystem /usr/global/share/googletest-release-1.8.0/googlemock/include -isystem /usr/global/share/googletest-release-1.8.0/googletest -isystem /usr/global/share/googletest-release-1.8.0/googletest/include -D HAVE_CONFIG_H -D HAVE_LIBEVENT2 -D HAVE_OPENSSL -D HAVE_TLSv13 -D LZ4_DISABLE_DEPRECATE_WARNINGS -D RAPIDJSON_NO_SIZETYPEDEFINE -D RAPIDJSON_SCHEMA_USE_INTERNALREGEX=0 -D RAPIDJSON_SCHEMA_USE_STDREGEX=1 -D UNISTR_FROM_CHAR_EXPLICIT=explicit -D UNISTR_FROM_STRING_EXPLICIT=explicit -D _FILE_OFFSET_BITS=64 -D _GNU_SOURCE -D _USE_MATH_DEFINES -D __STDC_FORMAT_MACROS -D __STDC_LIMIT_MACROS -I . -I include -I /export/home/tmp/clones/_bug_30041367 -I /export/home/tmp/clones/_bug_30041367/include -I router -I router/include -I /export/home/tmp/clones/_bug_30041367/router/src/harness/include -I /export/home/tmp/clones/_bug_30041367/router/src/harness/src/../include -I router/src/harness/src/src_SHARED -I /export/home/tmp/clones/_bug_30041367/router/src/router/src/../include -I /export/home/tmp/clones/_bug_30041367/router/src/rest_api/src/../include -I /export/home/tmp/clones/_bug_30041367/router/src/http/src -I /export/home/tmp/clones/_bug_30041367/router/src/http/src/../include -I router/src/http/src/../include -I /export/home/tmp/clones/_bug_30041367/router/src/mock_server/include -I /export/home/tmp/clones/_bug_30041367/router/src/http/include -D SAFE_MUTEX -D ENABLED_DEBUG_SYNC -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9 -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/x86_64-redhat-linux -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/backward -internal-isystem /usr/local/include -internal-isystem /export/home/tmp/usr/lib/clang/10.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O1 -Wall -Wextra -Wformat-security -Wvla -Wundef -Wmissing-format-attribute -Woverloaded-virtual -Wcast-qual -Wno-null-conversion -Wno-unused-private-field -Wconditional-uninitialized -Wdeprecated -Wextra-semi -Wheader-hygiene -Wnon-virtual-dtor -Wundefined-reinterpret-cast -Winconsistent-missing-destructor-override -Wshadow-field -std=c++14 -fdeprecated-macro -fdebug-compilation-dir /export/home/tmp/build/_bug_30041367__clangT -ferror-limit 19 -fmessage-length 0 -fsanitize=thread -fno-inline -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -faddrsig -o router/src/harness/tests/CMakeFiles/routertest_harness_stdx_string_view.dir/test_stdx_string_view.cc.o -x c++ /export/home/tmp/clones/_bug_30041367/router/src/harness/tests/test_stdx_string_view.cc
1.      /export/home/tmp/clones/_bug_30041367/router/src/harness/tests/test_stdx_string_view.cc:60:1: current parser token 'template'
2.      /export/home/tmp/clones/_bug_30041367/router/src/harness/tests/test_stdx_string_view.cc:55:20: LLVM IR generation of declaration 'get_string_abc'
3.      /export/home/tmp/clones/_bug_30041367/router/src/harness/tests/test_stdx_string_view.cc:55:20: Generating code for declaration 'get_string_abc'
 #&#8203;0 0x00000000022d0f5f llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/export/home/tmp/usr/bin/clang-10+0x22d0f5f)
 #&#8203;1 0x00000000022cf200 llvm::sys::RunSignalHandlers() (/export/home/tmp/usr/bin/clang-10+0x22cf200)
 #&#8203;2 0x00000000022d14c1 SignalHandler(int) (/export/home/tmp/usr/bin/clang-10+0x22d14c1)
 #&#8203;3 0x00007f37b15aae80 __restore_rt (/lib64/libpthread.so.0+0x12e80)
 #&#8203;4 0x00007f37b1055e75 raise (/lib64/libc.so.6+0x37e75)
 #&#8203;5 0x00007f37b1040895 abort (/lib64/libc.so.6+0x22895)
 #&#8203;6 0x00007f37b1040769 _nl_load_domain.cold (/lib64/libc.so.6+0x22769)
 #&#8203;7 0x00007f37b104e566 (/lib64/libc.so.6+0x30566)
 #&#8203;8 0x0000000003ef909c (/export/home/tmp/usr/bin/clang-10+0x3ef909c)
 #&#8203;9 0x00000000040b88ec EvaluateArgs(llvm::ArrayRef<clang::Expr const*>, llvm::SmallVector<clang::APValue, 8u>&, (anonymous namespace)::EvalInfo&, clang::FunctionDecl const*) (/export/home/tmp/usr/bin/clang-10+0x40b88ec)
#&#8203;10 0x00000000040b7857 HandleConstructorCall(clang::Expr const*, (anonymous namespace)::LValue const&, llvm::ArrayRef<clang::Expr const*>, clang::CXXConstructorDecl const*, (anonymous namespace)::EvalInfo&, clang::APValue&) (/export/home/tmp/usr/bin/clang-10+0x40b7857)
#&#8203;11 0x000000000410cfc1 (anonymous namespace)::RecordExprEvaluator::VisitCXXConstructExpr(clang::CXXConstructExpr const*, clang::QualType) (/export/home/tmp/usr/bin/clang-10+0x410cfc1)
#&#8203;12 0x000000000410cf28 (anonymous namespace)::RecordExprEvaluator::VisitCXXConstructExpr(clang::CXXConstructExpr const*, clang::QualType) (/export/home/tmp/usr/bin/clang-10+0x410cf28)
#&#8203;13 0x00000000040b3f2d EvaluateInPlace(clang::APValue&, (anonymous namespace)::EvalInfo&, (anonymous namespace)::LValue const&, clang::Expr const*, bool) (/export/home/tmp/usr/bin/clang-10+0x40b3f2d)
#&#8203;14 0x00000000040d8000 EvaluateStmt((anonymous namespace)::StmtResult&, (anonymous namespace)::EvalInfo&, clang::Stmt const*, clang::SwitchCase const*) (/export/home/tmp/usr/bin/clang-10+0x40d8000)
#&#8203;15 0x00000000040d84c1 EvaluateStmt((anonymous namespace)::StmtResult&, (anonymous namespace)::EvalInfo&, clang::Stmt const*, clang::SwitchCase const*) (/export/home/tmp/usr/bin/clang-10+0x40d84c1)
#&#8203;16 0x00000000040b7bbc HandleFunctionCall(clang::SourceLocation, clang::FunctionDecl const*, (anonymous namespace)::LValue const*, llvm::ArrayRef<clang::Expr const*>, clang::Stmt const*, (anonymous namespace)::EvalInfo&, clang::APValue&, (anonymous namespace)::LValue const*) (/export/home/tmp/usr/bin/clang-10+0x40b7bbc)
#&#8203;17 0x0000000004115dba (anonymous namespace)::ExprEvaluatorBase<(anonymous namespace)::RecordExprEvaluator>::handleCallExpr(clang::CallExpr const*, clang::APValue&, (anonymous namespace)::LValue const*) (/export/home/tmp/usr/bin/clang-10+0x4115dba)
#&#8203;18 0x000000000410cf28 (anonymous namespace)::RecordExprEvaluator::VisitCXXConstructExpr(clang::CXXConstructExpr const*, clang::QualType) (/export/home/tmp/usr/bin/clang-10+0x410cf28)
#&#8203;19 0x00000000040b2448 Evaluate(clang::APValue&, (anonymous namespace)::EvalInfo&, clang::Expr const*) (/export/home/tmp/usr/bin/clang-10+0x40b2448)
#&#8203;20 0x00000000040b46d6 EvaluateAsRValue((anonymous namespace)::EvalInfo&, clang::Expr const*, clang::APValue&) (/export/home/tmp/usr/bin/clang-10+0x40b46d6)
#&#8203;21 0x00000000040b019f clang::Expr::EvaluateAsRValue(clang::Expr::EvalResult&, clang::ASTContext const&, bool) const (/export/home/tmp/usr/bin/clang-10+0x40b019f)
#&#8203;22 0x00000000040b40c5 clang::Expr::isEvaluatable(clang::ASTContext const&, clang::Expr::SideEffectsKind) const (/export/home/tmp/usr/bin/clang-10+0x40b40c5)
#&#8203;23 0x00000000024d526b clang::CodeGen::CodeGenFunction::EmitReturnStmt(clang::ReturnStmt const&) (/export/home/tmp/usr/bin/clang-10+0x24d526b)
#&#8203;24 0x00000000024d2205 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/export/home/tmp/usr/bin/clang-10+0x24d2205)
#&#8203;25 0x00000000024dc0fc clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/export/home/tmp/usr/bin/clang-10+0x24dc0fc)
#&#8203;26 0x000000000251d868 clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/export/home/tmp/usr/bin/clang-10+0x251d868)
#&#8203;27 0x00000000025386e3 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/export/home/tmp/usr/bin/clang-10+0x25386e3)
#&#8203;28 0x0000000002532502 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/export/home/tmp/usr/bin/clang-10+0x2532502)
#&#8203;29 0x000000000253b447 clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) (/export/home/tmp/usr/bin/clang-10+0x253b447)
#&#8203;30 0x0000000002e7c77f (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) (/export/home/tmp/usr/bin/clang-10+0x2e7c77f)
#&#8203;31 0x0000000002e793db clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) (/export/home/tmp/usr/bin/clang-10+0x2e793db)
#&#8203;32 0x000000000368e5a4 clang::ParseAST(clang::Sema&, bool, bool) (/export/home/tmp/usr/bin/clang-10+0x368e5a4)
#&#8203;33 0x000000000290dff1 clang::FrontendAction::Execute() (/export/home/tmp/usr/bin/clang-10+0x290dff1)
#&#8203;34 0x00000000028c9762 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/export/home/tmp/usr/bin/clang-10+0x28c9762)
#&#8203;35 0x00000000029a4ebf clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/export/home/tmp/usr/bin/clang-10+0x29a4ebf)
#&#8203;36 0x00000000009a4551 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/export/home/tmp/usr/bin/clang-10+0x9a4551)
#&#8203;37 0x00000000009a24af main (/export/home/tmp/usr/bin/clang-10+0x9a24af)
#&#8203;38 0x00007f37b1041f33 __libc_start_main (/lib64/libc.so.6+0x23f33)
#&#8203;39 0x000000000099f6ee _start (/export/home/tmp/usr/bin/clang-10+0x99f6ee)
clang-10: error: unable to execute command: Aborted (core dumped)
clang-10: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 10.0.0 (https://git.llvm.org/git/clang.git 89f0031320593ecd5a1ccd2b2bacf83de981b4d8) (https://git.llvm.org/git/llvm.git 54fa70a4a937660f2a8676362444c450f088c2c1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /export/home/tmp/usr/bin
clang-10: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-10: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-10: note: diagnostic msg: /tmp/test_stdx_string_view-04400f.cpp
clang-10: note: diagnostic msg: /tmp/test_stdx_string_view-04400f.sh
clang-10: note: diagnostic msg:

********************

Error occurs when building MySQL. File will be available in https://github.com/mysql/mysql-server/tree/8.0/router/tests once the 8.0.18 release is made available.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 10: https://godbolt.org/z/bjdM3Ya7q
Reduced by C-Reduce:
```cpp
typedef int size_t;
template <class> struct basic_string_view {
  [[gnu::nonnull]] constexpr basic_string_view(int, size_type) {}
}

constexpr basic_string_view<int> operator_svreturn {
  0, 0
}

```
