### ISSUE TITLE
compound assignment invalid operands

### ISSUE THREAD

**Issue by jaopaulolc** [llvm/llvm-project#42127]
|  |  |
| --- | --- |
| Bugzilla Link | [42782](https://llvm.org/bz42782) |
| Version | trunk |
| OS | Linux |
| Attachments | [stack dump](https://user-images.githubusercontent.com/93436022/143759538-1951b179-44ff-4689-9c6d-3eebc40293bc.gz), [input program](https://user-images.githubusercontent.com/93436022/143759539-aac274fb-f9e2-4af1-97bb-65adbd5080e2.gz), [full command line](https://user-images.githubusercontent.com/93436022/143759540-8cedb9d0-01ad-4da8-a482-b1a6fb5fa0b5.gz) |
| CC | @zygoloid |

## Extended Description 

The code I am attaching has 2 compound assignments where variable x is the LHS, respectively, line 6 and 8.

The assignment on line 6 works fine. However line 8's assignment triggers the following error:

atomic.c:8:5: error: invalid operands to binary expression ('_Atomic(int)' and '_Atomic(int)')

The problem seems to be the fact that only the LHS' _Atomic type-specifier is ignored here:

https://github.com/llvm/llvm-project/blob/736e8aa8ed48fd8c29a909bf616965d0f8677bca/clang/lib/Sema/SemaExpr.cpp#L1358

Which makes LHSType and RHSType different and triggers the error message here:

https://github.com/llvm/llvm-project/blob/736e8aa8ed48fd8c29a909bf616965d0f8677bca/clang/lib/Sema/SemaExpr.cpp#L9462

I tried to "fix" this by adding the following right after SemaExpr.cpp#L1358:

if (const AtomicType *AtomicRHS = RHSType->getAs<AtomicType>())
  RHSType = AtomicRHS->getValueType();

However this breaks the CodeGen at ScalarExprEmitter::EmitCompoundAssignLValue. (please find all resources attached).

**Comment by AaronBallman** [comment]
I can no longer reproduce this issue as of Clang 15, so closing as completed.
