### ISSUE TITLE
struct method pointer definition fails if using decltype to determine the struct type

### ISSUE THREAD

**Issue by niklasnolte** [llvm/llvm-project#42185]
|  |  |
| --- | --- |
| Bugzilla Link | [42840](https://llvm.org/bz42840) |
| Version | unspecified |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
The code:

template<typename s>
using id = s;

template<typename OUT>
struct Functor {
    auto invoke () {
        return true;
    }
};

int main () {
    Functor<bool> f{};

    bool(Functor<bool>::*working)() = &decltype(f)::invoke;
    bool(decltype(f)::*not_working)() = &decltype(f)::invoke; // doesn't work, parsing seems to fail
    bool(id<decltype(f)>::*working_decay_t)() = &decltype(f)::invoke; // can make it work by wrapping into id
    auto working_cast = static_cast<bool(decltype(f)::*)()>(&decltype(f)::invoke);

}

The error:

<source>:14:23: error: expected unqualified-id
    bool(decltype(f)::*not_working)() = &decltype(f)::invoke;
                      ^

See godbolt: https://godbolt.org/z/IVrbZY

I hope the code speaks for itself, everything i could say here would only be speculation.

Thanks for taking care!
Cheers

**Comment by wheatman** [comment]
This was fixed between 9.0.1 and 10.0.0
https://godbolt.org/z/G1hv9dP4T

code
```cpp
template<typename s>
using id = s;

template<typename OUT>
struct Functor {
    auto invoke () {
        return true;
    }
};

int main () {
    Functor<bool> f{};
    bool(Functor<bool>::*working)() = &decltype(f)::invoke;
    bool(decltype(f)::*not_working)() = &decltype(f)::invoke;
    bool(id<decltype(f)>::*working_decay_t)() = &decltype(f)::invoke;
    auto working_cast = static_cast<bool(decltype(f)::*)()>(&decltype(f)::invoke);
}
```

old error
```
<source>:14:23: error: expected unqualified-id
    bool(decltype(f)::*not_working)() = &decltype(f)::invoke;
                      ^
<source>:14:24: error: use of undeclared identifier 'not_working'
    bool(decltype(f)::*not_working)() = &decltype(f)::invoke;
                       ^
2 errors generated.
Compiler returned: 1
```
