### ISSUE TITLE
Out-of-tree build of static library fails when compiled against static libunwind

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#42203]
|  |  |
| --- | --- |
| Bugzilla Link | [42858](https://llvm.org/bz42858) |
| Version | 9.0 |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
The problem is that the final merge step for libc++abi expects to find the location of the libunwind archive from the CMake target, which only exists for in-tree builds. To me, that seems like a bug in the CMake scripts for libc++abi - I would assume that the intention is to support static builds for out-of-tree builds.

**Comment by philnik777** [comment]
We don't support out-of-tree builds anymore.
