### ISSUE TITLE
Candidate template ignored: invalid explicitly-specified argument for template parameter

### ISSUE THREAD

**Issue by msimonsson** [llvm/llvm-project#42224]
|  |  |
| --- | --- |
| Bugzilla Link | [42879](https://llvm.org/bz42879) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
The following code fails to compile with Clang but compiles with GCC (since 7.1). Clang wants a value for the defaulted template parameter Capacity.

```cpp
#include <cstddef>

template <typename T, size_t Capacity = 10>
class smallvector {
  public:
    smallvector(const T*, size_t);
};

template <typename T>
class span {
  public:
    span(const T*, size_t);
};

class str {
  public:
    str(const char* data, size_t size) : data_{data}, size_{size} {}

    template <template <typename> typename Container>
    Container<const char> to_container() {
        return {data_, size_};
    }

  private:
    const char* data_;
    size_t size_;
};

void to_span(str& s) {
    s.to_container<span>(); // This works.
}

void to_smallvector(str& s) {
    s.to_container<smallvector>(); // This doesn't work.
}
```

```console
<source>:34:7: error: no matching member function for call to 'to_container'

    s.to_container<smallvector>();

    ~~^~~~~~~~~~~~~~~~~~~~~~~~~

<source>:20:27: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'Container'

    Container<const char> to_container() {

                          ^

1 error generated.
```

Tested with clang version 10.0.0 (trunk 367740) and -std=c++17.

**Comment by mengyays** [comment]
the selution: need to redefine the template for original template class:
template<typename T>
using smallvector_T = smallvector<T>;

**Comment by jdoubleu** [comment]
I found this one interesting: https://godbolt.org/z/P3fno44o1
I'm not sure who's right and who's wrong. Maybe gcc just accepts it, because of the class template's (i.e. `std::map`) default parameters.

The solution is to either match the template's parameter count or use a template pack:
```
template<template<typename...> typename C>
```

**Comment by cor3ntin** [comment]
@jdoubleu I think this is just clang not implementing C++17 template template argument matching rules by default. The GCC/conforming behavior can be subscribed to by passing `-frelaxed-template-template-args`. @mizvekov

**Comment by mizvekov** [comment]
Duplicate of https://github.com/llvm/llvm-project/issues/36505
