### ISSUE TITLE
[CWG2091] template parameter lookup differs from g++ wrt. constness

### ISSUE THREAD

**Issue by a5fec13e-39c8-49b2-b3dd-e7d891b4dfc7** [llvm/llvm-project#42233]
|  |  |
| --- | --- |
| Bugzilla Link | [42888](https://llvm.org/bz42888) |
| Version | 8.0 |
| OS | Linux |
| Attachments | [Source code illustrating the problem](https://user-images.githubusercontent.com/92601461/143759583-6646354e-dd8b-49bf-9da8-8fbfe04b177d.gz) |
| CC | @DougGregor,@zygoloid |

## Extended Description 

For the attached source file, clang++ errors out with
```
main.C:18:4: error: invalid operands to binary expression ('AA' and 'S<E, EV>')
        a << x;
        ~ ^  ~
main.C:10:14: note: candidate template ignored: substitution failure [with E = E]: deduced non-type template argument does not have the same type as the corresponding template parameter ('E *' vs 'const E *')
                friend AA& operator<<( AA& os, const S<E,V>& e );
```
g++ handles the template fine.

Removing the constness of the second operator parameter or adding constness to the variable makes the problem disappear.

In my application a different operatow was chosen leading to a misbehavior.

**Comment by cor3ntin** [comment]
Fixed in clang 10
https://godbolt.org/z/G35dv4boz 

@Endilll Can you add a test for CWG2091? Thanks
