### ISSUE TITLE
ICE on lambdas returning lambdas 3 deep, when using move or fwd ref

### ISSUE THREAD

**Issue by 1731a261-5786-4527-aa67-c540a5c5e8af** [llvm/llvm-project#42260]
|  |  |
| --- | --- |
| Bugzilla Link | [42915](https://llvm.org/bz42915) |
| Version | 8.0 |
| OS | Linux |
| Attachments | [Example code causing ICE](https://user-images.githubusercontent.com/93435861/143759594-d5f96159-2537-4cdb-b0c4-6c139a6a9fc8.gz), [backtrace](https://user-images.githubusercontent.com/93435861/143759595-411dc821-c3ee-4ae2-891d-615384e508e2.gz), [preprocessed source](https://user-images.githubusercontent.com/93435861/143759596-9435badf-311c-441e-973c-ffe5770d0d10.gz), [compiler call](https://user-images.githubusercontent.com/93435861/143759597-dc233772-2f06-4dc3-aaec-48628290e870.gz) |
| CC | @AaronBallman,@zygoloid |

## Extended Description 

The attached file crashes clang++-8.0.0, and trunk (367966).

The crashes are on the lines with a comment '// E'. If those lines are commented out, it compiles.

There are two ways to make it compile. Remove '= std::move(function)' under the comment '// 1' or remove the forwarding reference '&&' under the comment '// 2'

godbolt link: https://gcc.godbolt.org/z/DXqN06

**Comment by Endilll** [comment]
Appears to be fixed in Clang 18, and doesn't reproduce on trunk (19.0): https://gcc.godbolt.org/z/Mj7r4coTs
