### ISSUE TITLE
hicpp-multiway-paths-covered complains about missing default when all cases are handled

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#42274]
|  |  |
| --- | --- |
| Bugzilla Link | [42929](https://llvm.org/bz42929) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @Quuxplusone,@JonasToth,@EugeneZelenko,@LebedevRI,@madsravn |

## Extended Description 
With clang-tidy 8.0.0

This code

$ cat la.c 
enum test_enum {
	test_enum_1,
	test_enum_2,
	test_enum_3,
	test_enum_4
};

int test_switch(enum test_enum value)
{
    switch (value) {
        case test_enum_1:
            return 1;
        case test_enum_2:
            return 2;
        case test_enum_3:
            return 3;
        case test_enum_4:
            return 4;
    }
}

Generates this warning

$ clang-tidy -checks=hicpp-multiway-paths-covered la.c 
...
la.c:10:5: warning: potential uncovered code path; add a default label [hicpp-multiway-paths-covered]
    switch (value) {
    ^

If I add the default I will fail foul of

$ clang -Wcovered-switch-default -c -o la.o la.c

I have not looked in detauls, but AFAIU the code supposedly should not be generating a warning there since CaseCount == MaxPathsPossible (https://github.com/llvm-mirror/clang-tools-extra/blob/b1ace237b8a4c7246d6a3cd7b1d34118074d9af3/clang-tidy/hicpp/MultiwayPathsCoveredCheck.cpp#L172)

**Comment by carlosgalvezp** [comment]
This is no longer showing up on trunk
