### ISSUE TITLE
Template template parameters and default arguments in C++17 (CWG150 + P0522R0)

### ISSUE THREAD

**Issue by 066609a1-1e53-4cd0-b6cb-efe5048c5913** [llvm/llvm-project#42305]
|  |  |
| --- | --- |
| Bugzilla Link | [42960](https://llvm.org/bz42960) |
| Version | trunk |
| OS | Linux |
| Attachments | [The MWE code described in the report.](https://user-images.githubusercontent.com/92601693/143759618-0a508082-59dd-4dad-b5e7-25ee2c80590a.gz) |
| CC | @zygoloid |

## Extended Description 

The code below will not compile with Clang, though it does with GCC (with the -std=c++17 flag and upwards).

template <typename T, typename = void>
struct jam;

template <template <typename> typename>
struct mata;

using type = mata<jam>;

This relates to CWG 150, which I believe was resolved by P0522R0. That is, since C++17, code such as that above should now be legal.

**Comment by mizvekov** [comment]
Duplicate of https://github.com/llvm/llvm-project/issues/42224
