### ISSUE TITLE
Missing file name for darwin output format with non-Mach-O

### ISSUE THREAD

**Issue by jh7370** [llvm/llvm-project#42316]
|  |  |
| --- | --- |
| Bugzilla Link | [42971](https://llvm.org/bz42971) |
| Version | trunk |
| OS | Windows NT |
| CC | @Bigcheese |

## Extended Description 
llvm-size falls back to printing in Berkeley format, if --format=darwin is specified and a non-Mach-O object has been provided. However, it does not print the input filename when it should:

Goid:
C:\Work> C:\llvm\build\Debug\bin\llvm-size test.tmp
   text    data     bss     dec     hex filename
      1       2       4       7       7 test.tmp

Bad:
C:\Work> C:\llvm\build\Debug\bin\llvm-size test.tmp --format=darwin
   text    data     bss     dec     hex filename
      1       2       4       7       7

**Comment by xgupta** [comment]
Just thinking why someone provide non-Macho-O file when they have passed --format=darwin ?
