### ISSUE TITLE
[coroutines] CoroSplit fails to add musttaill under -O2

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#42415]
|  |  |
| --- | --- |
| Bugzilla Link | [43070](https://llvm.org/bz43070) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [repro of a failure to add musttail to symmetric coroutine transfer](https://user-images.githubusercontent.com/60944935/143759655-7c6261da-ad5d-4179-8577-11e08b7c81c4.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

CoroSplit.cpp:simplifyTerminatorLeadingToRet function is deficient and does not add musttail under -O2 for this simple example (also see attached musttail.ll reproducer).

https://godbolt.org/z/7T_YnR

// -O2 -stdlib=libc++ -std=c++2a -fstack-protector-all
// Bug#1, fails to insert musttail under -O2 (this-bug)
// Bug#2, fstack-protector-all interactions prevent tail call ([coroutines] musttail and -fstack-protector-all interactions don't mix well)
#include <experimental/coroutine>
using namespace std::experimental;

struct coro {
  struct promise_type {
    suspend_always initial_suspend() { return {}; }
    suspend_always final_suspend() { return {}; }
    void return_void() {}
    void unhandled_exception(){}
    coro get_return_object() { return{};}
  };
};
coroutine_handle<> h;
struct sym {
  bool await_ready() { return false; }
  void await_resume() {}
  auto await_suspend(coroutine_handle<>) { return h; }
};
coro f() { co_await sym{}; }

**Comment by ChuanqiXu9** [comment]
Fixed in trunk.
