### ISSUE TITLE
Default -x cuda C++ -std is C++98

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#42412]
|  |  |
| --- | --- |
| Bugzilla Link | [43067](https://llvm.org/bz43067) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
When compiling with `-x cuda`, the default `__cplusplus` version of clang still points to C++98 (199711L) instead of the otherwise default of the (host) compiler.

This is a bit confusing and probably not intentional? Should it be identical to the current default in the other frontends (e.g. C++14)?

**Comment by arsenm** [comment]
It is 2014 now
