### ISSUE TITLE
Clang crashes when it cannot evaluate recursive template

### ISSUE THREAD

**Issue by zoecarver** [llvm/llvm-project#42423]
|  |  |
| --- | --- |
| Bugzilla Link | [43078](https://llvm.org/bz43078) |
| Version | 9.0 |
| OS | All |
| CC | @zygoloid |

## Extended Description 
Found this bug while working on libc++ so the example isn't great. It appears Clang crashes when it cannot evaluate recursive template parameters. Setting -ftemplate-depth=100 turns it into an error. Here is the (rather large) example I have:

template<class _T1, class _T2>
struct __all_const_impl;

template<class..._T1Args, class... _T2Args>
struct __all_const_impl<__tuple_types<_T1Args...>, __tuple_types<_T2Args...>>
    : true_type {};

template<template<class...> class _T1, class... _T1Args, class... _T2Args>
auto __all_const_fn(_T1<_T1Args...>, _T2Args...)
    -> __all_const_impl<__tuple_types<_T1Args...>, __tuple_types<_T2Args...>>;

template<class _T1, class... _T2Args>
using __all_const = decltype(__all_const_fn(declval<_T1>(), declval<_T2Args>()...));

template<class _Tuple,
         class _Idxs = typename __make_tuple_indices<tuple_size<_Tuple>::value>::type>
struct foo_impl;

template<class... _Bound, size_t... _Idxs>
struct foo_impl<__tuple_types<_Bound...>, __tuple_indices<_Idxs...>>
{
    std::tuple<_Bound...> __bound;
    
    template<class... _BoundArgs,
             class = enable_if_t<__all_const<std::tuple<_Bound...>,
                                 _BoundArgs...>::value>>
    foo_impl(_BoundArgs&&... __bound) { }
};

template<class... _Args>
using Foo = foo_impl<__tuple_types<decay_t<_Args>...>>;

static_assert(is_move_constructible<decltype(Foo<int>(1))>::value);

Here is a link to wandbox: https://wandbox.org/permlink/dQwvJViWFJakPfPd

**Comment by Endilll** [comment]
Appears to be fixed in Clang 11: https://godbolt.org/z/6bEMffr3W
