### ISSUE TITLE
constexpr variable initialisation error after forwarding reference

### ISSUE THREAD

**Issue by 066609a1-1e53-4cd0-b6cb-efe5048c5913** [llvm/llvm-project#42431]
|  |  |
| --- | --- |
| Bugzilla Link | [43086](https://llvm.org/bz43086) |
| Version | trunk |
| OS | Linux |
| Attachments | [Code as described.](https://user-images.githubusercontent.com/92601693/143759664-30b7ecc4-4a7f-4956-ba28-a394d26b36f2.gz) |
| CC | @DougGregor,@pkeir,@zygoloid |

## Extended Description 

The C++11 code below (also attached) will fail to compile:

struct Bar {};
struct Foo { Bar t; };

template <typename T>
constexpr T jam(T &&a) { return a; }

void test()
{
  Foo y;
  constexpr Foo x = jam(y);
}

Changing the types of x and y from Foo to Bar will remove the error. GCC snapshot 17th August 2019 produces no error. The error message follows:

constexpr_rvalue.cpp:10:17: error: constexpr variable 'x' must be initialized by a constant expression
  constexpr Foo x = jam(y);
                ^   ~~~~~~
constexpr_rvalue.cpp:10:21: note: read of non-constexpr variable 'y' is not allowed in a constant expression
  constexpr Foo x = jam(y);
                    ^
constexpr_rvalue.cpp:10:21: note: in call to 'Foo(y)'
constexpr_rvalue.cpp:9:7: note: declared here
  Foo y;
      ^
1 error generated.

**Comment by yuanfang-chen** [comment]
It compiles fine as of llvm14.  https://clang.godbolt.org/z/dzx18xPhh
