### ISSUE TITLE
Add default include path and link libraries.

### ISSUE THREAD

**Issue by c9c7c5f7-d5e8-468f-9cef-0ee136478b11** [llvm/llvm-project#42453]
|  |  |
| --- | --- |
| Bugzilla Link | [43108](https://llvm.org/bz43108) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Build instructions for the LLVM toolchain.](https://user-images.githubusercontent.com/92601716/143759674-f7f41dfd-ae57-4e81-a818-364dc91e2942.gz) |
| CC | @qis |

## Extended Description 

When using a complete LLVM toolkit with ParallelSTL and TBB backend, you have to add the include directory (always) and tbb library (when `std::execution::par` is used) manually.

Since it is part of the standard library now, the include path should not be added manually.

The '-ltbb' part is debatable and I totally understand why it can be a bad idea to do it automatically.

Here is a minimal complete viable example:

```
  // main.cpp
  #include <algorithm>
  #include <execution>
  #include <iostream>
  #include <mutex>
  #include <vector>
  int main() {
    std::mutex mutex;
    std::vector<int> v = { 0, 1, 2, 3, 4 };
    std::for_each(std::execution::par, v.begin(), v.end(), [&](auto i) {
      std::lock_guard lock(mutex);
      std::cout << i << std::endl;
    });
  }
```

When compiled with `clang++ main.cpp`, the error is:

```
  In file included from main.cpp:2:
  In file included from /opt/llvm/bin/../include/c++/v1/algorithm:643:
  /opt/llvm/bin/../include/c++/v1/memory:5594:13: fatal error: '__pstl_memory' file not found
  #   include <__pstl_memory>
              ^~~~~~~~~~~~~~~
  1 error generated.
```

When compiled with `clang++ -I/opt/llvm/include main.cpp`, the error is:

```
  ld.lld: error: undefined symbol: tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)
  ...
```

It only works when compiled with `clang++ -I/opt/llvm/include main.cpp -ltbb`.

Build instructions for the LLVM toolchain (git commit 918246788) used to test it in WSL (Ubuntu 18.04.3 LTS) are attached to this bug report.

**Comment by ldionne** [comment]
This should not be an issue anymore since libc++ is installing its implementation of the PSTL under `include/c++/v1` along with all its other headers.
