### ISSUE TITLE
Clang seg fault triggered by defaulted template template parameter calculated from other template parameter

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#42460]
|  |  |
| --- | --- |
| Bugzilla Link | [43115](https://llvm.org/bz43115) |
| Version | 8.0 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 
template <size_t index, typename ARG, E enumVal = static_cast<E>(index), template <typename> typename CONSTRAINT = PT<enumVal>::template constraint>

line 609827 of attached file coreaudiodevice.mm

and line 609860

it was able to compile once i removed the defaulted type for the template template parameter CONSTRAINT and moved the "calculation" of this to the calling function

**Comment by wheatman** [comment]
I am closing this as unreproducible without the referenced file.

My attempt at trying to get the given line to compile with the minimum extra code did not lead to any crash
https://godbolt.org/z/74afob195
