### ISSUE TITLE
Complex nested lambda crashes Clang frontend

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#42465]
|  |  |
| --- | --- |
| Bugzilla Link | [43120](https://llvm.org/bz43120) |
| Version | 8.0 |
| OS | Linux |
| Attachments | [The Clang stack trace](https://user-images.githubusercontent.com/60944935/143759682-fbfc14f4-e00f-4f13-98f4-07caae077641.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @AaronBallman,@DougGregor,@mizvekov,@zygoloid |

## Extended Description 

The following C++17 code causes the compiler to crash, when compiling with -std=c++17 -O0 -emit-llvm:

```cpp
#include <functional>
#include <type_traits>

template <typename F>
constexpr auto curry(F&& f) {
  if constexpr (std::is_invocable_v<F>) {
    return f();
  } else {
    return [f = static_cast<F&&>(f)](auto&& arg) mutable {
      return curry([
        f = static_cast<F&&>(f),
        arg_t = std::forward_as_tuple(static_cast<decltype(arg)&&>(arg))
      ](auto&&... args) mutable->decltype(f(static_cast<decltype(arg)&&>(arg),
                                            static_cast<decltype(args)&&>(
                                                args)...)) {
        return std::apply(
            f, std::tuple_cat(std::move(arg_t),
                              std::forward_as_tuple(
                                  static_cast<decltype(args)&&>(args)...)));
      });
    };
  }
}

int main(){
    int n;
    auto f = [](int n, int m, int x) { return n + m + x; };

    auto c1 = curry(f)(n);
    return 0;
}
```

https://godbolt.org/z/_iWHWd is a link demonstrating it. It crashes on x86-64 Clang 8.0 and trunk, but seems not to crash on the Experimental Concepts Clang build.

**Comment by shafik** [comment]
This is fixed in trunk: https://godbolt.org/z/WcoPoxhKP

Not sure by which patch.

CC @cor3ntin @erichkeane
