### ISSUE TITLE
Support .data directive in wasm assembly

### ISSUE THREAD

**Issue by dschuff** [llvm/llvm-project#42472]
|  |  |
| --- | --- |
| Bugzilla Link | [43127](https://llvm.org/bz43127) |
| Version | trunk |
| OS | Linux |
| CC | @aardappel |

## Extended Description 
We currently support `.text` as a shorthand for switching to the text section, we should probably support `.data` too.

**Comment by aardappel** [comment]
Note: in `WasmAsmParser.cpp`, we have: `// FIXME: .text currently no-op.`, presumably because every Wasm function needs its own section, and `WebAssemblyAsmParser.cpp` forces this by creating these sections as it encounters them.

**Comment by aardappel** [comment]
Added `.data`: https://reviews.llvm.org/D119794

**Comment by aardappel** [comment]
Fixed in https://reviews.llvm.org/D119794
