### ISSUE TITLE
Regression(r369850): Several tests fail when building with gcc5.1, usually with Assertion `FeatureBitset({mode}) == (STI.getFeatureBits() & AllModes)' failed.

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#42494]
|  |  |
| --- | --- |
| Bugzilla Link | [43149](https://llvm.org/bz43149) |
| Version | trunk |
| OS | All |
| CC | @d0k,@jfbastien |

## Extended Description 
When building with gcc5.1, these tests fail:

********************
Failing Tests (8):
    LLVM :: MC/AsmParser/dot-symbol-assignment.s
    LLVM :: MC/ELF/relocation-386.s
    LLVM :: MC/X86/AlignedBundling/bundle-subtarget-change-error.s
    LLVM :: MC/X86/address-size.s
    LLVM :: MC/X86/code16gcc.s
    LLVM :: MC/X86/fixup-cpu-mode.s
    LLVM :: MC/X86/intel-syntax-error.s
    LLVM :: MC/X86/x86-branch-relaxation.s

An example failure looks like this:

-- Testing: 46847 tests, 32 threads --
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70
FAIL: LLVM :: MC/AsmParser/dot-symbol-assignment.s (34461 of 46847)
******************** TEST 'LLVM :: MC/AsmParser/dot-symbol-assignment.s' FAILED ********************
Script:
--
: 'RUN: at line 1';   /b/swarming/w/ir/cache/builder/src/third_party/llvm-bootstrap/bin/llvm-mc -triple i386-unknown-unknown /b/swarming/w/ir/cache/builder/src/third_party/llvm/llvm/test/MC/AsmParser/dot-symbol-assignment.s | /b/swarming/w/ir/cache/builder/src/third_party/llvm-bootstrap/bin/FileCheck /b/swarming/w/ir/cache/builder/src/third_party/llvm/llvm/test/MC/AsmParser/dot-symbol-assignment.s
--
Exit Code: 2

Command Output (stderr):
--
llvm-mc: /b/swarming/w/ir/cache/builder/src/third_party/llvm/llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:933: void {anonymous}::X86AsmParser::SwitchMode(unsigned int): Assertion `FeatureBitset({mode}) == (STI.getFeatureBits() & AllModes)' failed.
Stack dump:
0.	Program arguments: /b/swarming/w/ir/cache/builder/src/third_party/llvm-bootstrap/bin/llvm-mc -triple i386-unknown-unknown /b/swarming/w/ir/cache/builder/src/third_party/llvm/llvm/test/MC/AsmParser/dot-symbol-assignment.s 
#&#8203;0 0x00000000005577ed PrintStackTraceSignalHandler(void*) (/b/swarming/w/ir/cache/builder/src/third_party/llvm-bootstrap/bin/llvm-mc+0x5577ed)
FileCheck error: '-' is empty.
FileCheck command line:  /b/swarming/w/ir/cache/builder/src/third_party/llvm-bootstrap/bin/FileCheck /b/swarming/w/ir/cache/builder/src/third_party/llvm/llvm/test/MC/AsmParser/dot-symbol-assignment.s

A full build log is at https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8903903395454047440/+/steps/package_clang/0/stdout

With other host compilers, things are fine, but for 5.1 it looks like r369852 traded the gcc ICE for a gcc miscompile.

(We're going to switch the Chromium bots to 5.3 to get out of the "find all the 5.1 bugs" business, but here's a last bug report.)

See https://bugs.chromium.org/p/chromium/issues/detail?id=998569 for more details.

**Comment by Endilll** [comment]
We require GCC 7 now.
