### ISSUE TITLE
Build fails using gn

### ISSUE THREAD

**Issue by nandor** [llvm/llvm-project#42530]
|  |  |
| --- | --- |
| Bugzilla Link | [43185](https://llvm.org/bz43185) |
| Version | trunk |
| OS | All |

## Extended Description 
I am trying to add a new library under lib/clang/AST, along with a new tablegen backend. It seems like a bot is failing when trying to build with gn:

http://lab.llvm.org:8011/builders/sanitizer-x86_64-linux-gn/builds/4816/steps/annotate/logs/stdio

**Comment by arsenm** [comment]
Old build issue, gn isn't official anyway
