### ISSUE TITLE
std::atomic<FloatingPoint> missing operator+= and operator-=

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#42546]
|  |  |
| --- | --- |
| Bugzilla Link | [43201](https://llvm.org/bz43201) |
| Version | unspecified |
| OS | Linux |
| CC | @mclow |

## Extended Description 
The following code fails to compile, complaining about no matching overload:

```cpp
#include <atomic>

void f() {
    std::atomic<double> a;
    a += 1.0;
}
```

**Comment by xgupta** [comment]
still an issue, live godbolt link - https://godbolt.org/z/Wd4oPcvE1.

**Comment by philnik777** [comment]
Closing this, since we track Papers at https://libcxx.llvm.org/Status/Cxx20.html and tracking the status in multiple places doesn't make sense.
