### ISSUE TITLE
Indentation of nested scopes is incorrect

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#42582]
|  |  |
| --- | --- |
| Bugzilla Link | [43237](https://llvm.org/bz43237) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @woernsn |

## Extended Description 
Indentation of multiple nested scopes is incorrect. It doesn't matter what are settings of clang-format. Bad output is produced also with default settings for all clang-format styles(webkit,llvm,etc...).

Steps to Reproduce:

Create source file with content as:
```
void fc()
{
// scope1
{ 
// scope2
{
int a;
}
}

// scope3
{
int b;
}
}
```

When clang-format is applied actual result is:
```
void fc()
{
    // scope1
    { // scope2
        { int a;
}
}

// scope3
{
    int b;
}
}
```

Expected result (if parameter `IndentLength` is 4) is:
```
void fc()
{
    // scope1
    { 
        // scope2
        {
             int a;
        }
    }

    // scope3
    {
        int b;
    }
}
```

But if scope3 is removed, indentation of scope1/scope2 is correct.

It seems that it behaves same for all versions of clang-format.
(tested on https://zed0.co.uk/clang-format-configurator/)

**Comment by rymiel** [comment]
Duplicate of https://github.com/llvm/llvm-project/issues/33891
