### ISSUE TITLE
Segfault: infinite recursion in ScalarEvolution

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#42594]
|  |  |
| --- | --- |
| Bugzilla Link | [43249](https://llvm.org/bz43249) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced testcase](https://user-images.githubusercontent.com/55128014/143759724-6e9e69d2-6319-4aa6-8108-b376772db768.gz), [unreduced test case](https://user-images.githubusercontent.com/55128014/143759725-e3c0ece7-9a4f-453d-ac9f-966b922af524.gz) |
| CC | @fhahn,@JonPsson,@uweigand |

## Extended Description 

clang -cc1 -triple s390x-ibm-linux -S -O3 -o crash0.s -x ir tc_scev_segfault.ll

...
#&#8203;245 0x000002aa2585ed2e llvm::ScalarEvolution::getSCEV(llvm::Value*) (/home/ijonpan/llvm/build/llvm-dev/bin/clang-10+0xbded2e)
#&#8203;246 0x000002aa2585da08 llvm::ScalarEvolution::createSCEV(llvm::Value*) (.part.1519.constprop.1613) (/home/ijonpan/llvm/build/llvm-dev/bin/clang-10+0xbdda08)
#&#8203;247 0x000002aa2585ed2e llvm::ScalarEvolution::getSCEV(llvm::Value*) (/home/ijonpan/llvm/build/llvm-dev/bin/clang-10+0xbded2e)
#&#8203;248 0x000002aa2587fc3e llvm::ScalarEvolution::createNodeFromSelectLikePHI(llvm::PHINode*) (/home/ijonpan/llvm/build/llvm-dev/bin/clang-10+0xbffc3e)
#&#8203;249 0x000002aa25881598 llvm::ScalarEvolution::createNodeForPHI(llvm::PHINode*) (/home/ijonpan/llvm/build/llvm-dev/bin/clang-10+0xc01598)
#&#8203;250 0x000002aa2585df80 llvm::ScalarEvolution::createSCEV(llvm::Value*) (.part.1519.constprop.1613) (/home/ijonpan/llvm/build/llvm-dev/bin/clang-10+0xbddf80)
#&#8203;251 0x000002aa2585ed2e llvm::ScalarEvolution::getSCEV(llvm::Value*) (/home/ijonpan/llvm/build/llvm-dev/bin/clang-10+0xbded2e)
#&#8203;252 0x000002aa2585da08 llvm::ScalarEvolution::createSCEV(llvm::Value*) (.part.1519.constprop.1613) (/home/ijonpan/llvm/build/llvm-dev/bin/clang-10+0xbdda08)
#&#8203;253 0x000002aa2585ed2e llvm::ScalarEvolution::getSCEV(llvm::Value*) (/home/ijonpan/llvm/build/llvm-dev/bin/clang-10+0xbded2e)
#&#8203;254 0x000002aa2587fc3e llvm::ScalarEvolution::createNodeFromSelectLikePHI(llvm::PHINode*) (/home/ijonpan/llvm/build/llvm-dev/bin/clang-10+0xbffc3e)
#&#8203;255 0x000002aa25881598 llvm::ScalarEvolution::createNodeForPHI(llvm::PHINode*) (/home/ijonpan/llvm/build/llvm-dev/bin/clang-10+0xc01598)
Segmentation fault
s

**Comment by fhahn** [comment]
This looks like the same issue as #44546. SCEV overflows the stack due to recursively constructing expressions.

**Comment by fhahn** [comment]
A fix just landed. It would be great if you could verify it fixes the issue on your side.
