### ISSUE TITLE
backend error because clang doesn't type check address space qualifiers during casting

### ISSUE THREAD

**Issue by davezarzycki** [llvm/llvm-project#42600]
|  |  |
| --- | --- |
| Bugzilla Link | [43255](https://llvm.org/bz43255) |
| Version | trunk |
| OS | All |
| CC | @davezarzycki,@zygoloid |

## Extended Description 
The following code will crash in the backend because clang isn't type checking address space qualifiers during casting. To fix the code, uncomment the line below.

struct Cache {
	long buffer[100];
};

class Thread {
public:
	Thread *self;
	char buffer[100*8];
	Thread() : self(this) {}
};

__attribute__((address_space(257)))
Thread *const _foo = nullptr;

long getIndex(unsigned long index) {
	return ((
//__attribute__((address_space(257)))
				Cache*)_foo->buffer)->buffer[index];
}

Sema should catch this mismatch and diagnose.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 10: https://godbolt.org/z/7eqT1Yzzr
