### ISSUE TITLE
[InstCombine] Failure to simplify 2 icmp and select after rL369840

### ISSUE THREAD

**Issue by dendibakh** [llvm/llvm-project#42606]
|  |  |
| --- | --- |
| Bugzilla Link | [43261](https://llvm.org/bz43261) |
| Version | trunk |
| OS | Linux |
| CC | @LebedevRI,@RKSimon,@nunoplopes,@rotateright |

## Extended Description 
Before rL369840 we simplified the following case:

  %tmp = add i32 %i, -3
  %tmp1 = icmp ult i32 %tmp, 2
  %cmp2 = icmp eq i32 %i, 5
  %phitmp = zext i1 %cmp2 to i32
  %tmp2 = select i1 %tmp1, i32 1, i32 %phitmp

to

  %tmp = add i32 %i, -3
  %0 = icmp ult i32 %tmp, 3
  %tmp2 = zext i1 %0 to i32

Proof: https://rise4fun.com/Alive/dhoe

There were 4 steps of simplification:
step1&2: https://rise4fun.com/Alive/82o
step3&4: https://rise4fun.com/Alive/Izp

After rL369840 we invert the first comparison (icmp ult -> ugt, as a result of tryToReuseConstantFromSelectInComparison() ) and instcombine takes another route.

I'm not sure if it is a duplicate of recently created bug for InstCombine.

**Comment by RKSimon** [comment]
Resolving - we have test coverage for this at 993d9462e131c79cbc45e306dfb8e406864ebb4c and the case hasn't regressed since it was reported.
