### ISSUE TITLE
Inter-Procedural Analysis (Umbrella bug)

### ISSUE THREAD

**Issue by tkremenek** [llvm/llvm-project#4263]
|  |  |
| --- | --- |
| Bugzilla Link | [3891](https://llvm.org/bz3891) |
| Version | unspecified |
| OS | All |
| Blocks | llvm/llvm-project#4243  |

## Extended Description 
This is an umbrella bug to track the progress of developing inter-procedural analysis (IPA) in the static analyzer.

**Comment by steakhal** [comment]
I don't think this is relevant anymore.
API, aka. inlining functions work for a decade now.
