### ISSUE TITLE
Impossible to configure the wrapping of braces for lambda

### ISSUE THREAD

**Issue by d75947c2-9580-4fe3-87b3-3a6ed64cecb3** [llvm/llvm-project#42630]
|  |  |
| --- | --- |
| Bugzilla Link | [43285](https://llvm.org/bz43285) |
| Version | trunk |
| OS | All |

## Extended Description 
It is actually impossible to configure the wrapping of braces before the lambda body like this two examples:

```
[]() -> T {
  Func();
}
```

```
[]() -> T
{
  Func();
}
```

**Comment by mydeveloperday** [comment]
This issue is resolved by commit a0118e6e588fe303b08e7e06ba28ac1f8d50c68

I will close this issue, but feel free to reopen if you see any issues

```
void foo() {
  []() -> T
  {
    Func();
  }
}
```

and

```
void foo() {
  []() -> T {
    Func();
  }
}
```

with

```
BasedOnStyle: LLVM
BreakBeforeBraces: Custom
BraceWrapping:
    BeforeLambdaBody: false/true
AllowShortLambdasOnASingleLine: None
```
