### ISSUE TITLE
incorrect overload resolution for function with variadic templates and parameter with default value

### ISSUE THREAD

**Issue by 07db8777-e875-47a6-8e13-f3ee3e0342de** [llvm/llvm-project#42642]
|  |  |
| --- | --- |
| Bugzilla Link | [43297](https://llvm.org/bz43297) |
| Version | trunk |
| OS | Windows NT |
| CC | @zygoloid |

## Extended Description 
```cpp
template<typename... T>
void f(T...);          // #1

template<typename... T>
void f(T..., int = 1); // #2

void test() {
    f();
}
```
Clang selects `#2` (https://gcc.godbolt.org/z/tJNCzq), but it must be an ambiguous function call.

**Comment by cor3ntin** [comment]
Fixed in clang 16
