### ISSUE TITLE
modernize-use-emplace does not support alias templates

### ISSUE THREAD

**Issue by bjehlert** [llvm/llvm-project#42659]
|  |  |
| --- | --- |
| Bugzilla Link | [43314](https://llvm.org/bz43314) |
| Version | unspecified |
| OS | Windows NT |
| CC | @EugeneZelenko |

## Extended Description 
The modernize-use-emplace check does not work with alias templates of types in the ContainersWithPushBack list.

Example:

  #include <vector>

  template <typename T>
  using MyVector = std::vector<T>;

  void f()
  {
    std::vector<std::pair<int, int>> stdv;
    stdv.push_back(std::pair<int, int>(0, 0)); // warning on this line

    MyVector<std::pair<int, int>> myv;
    myv.push_back(std::pair<int, int>(0, 0)); // no warning
  }

Ideally, having std::vector in the ContainersWithPushBack list would flag both cases. The performance-faster-string-find check has the option StringLikeClasses which does handle alias templates correctly. With std::basic_string in the list it also works for std::string as well as custom classes with a similar design.

This limits the usefulness of this check for custom containers that heavily use alias templates (similar to the std::string vs std::basic_string design).

Tested with Clang 8.0.0.

**Comment by firewave** [comment]
This is detected by the latest version: https://godbolt.org/z/e987GTqjP.

I suspect this was fixed with #55856.

**Comment by firewave** [comment]
This is fixed with clang-tidy 16.
