### ISSUE TITLE
loop-interchange crashes: Assertion `OuterInnerReductions.find(PHI) != OuterInnerReductions.end() && "Expected a reduction PHI node"' failed.

### ISSUE THREAD

**Issue by 952e6d5a-d994-4724-a6d1-07613b2d95a8** [llvm/llvm-project#42671]
|  |  |
| --- | --- |
| Bugzilla Link | [43326](https://llvm.org/bz43326) |
| Version | trunk |
| OS | Linux |
| Attachments | [.bc file of the source code](https://user-images.githubusercontent.com/92601252/143759758-a2b186d1-c275-403a-aafa-d00236bb6385.gz), [bugpoint-reduced-simplified.bc](https://user-images.githubusercontent.com/92601252/143759760-b0898623-e35d-4e29-9360-28a13cfe256a.gz) |
| CC | @BalaRishi-AMD,@CongzheUalberta,@N-SysR,@fhahn |

## Extended Description 

$clang -v
clang version 10.0.0 (trunk 371952)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$clang -O3 -c -emit-llvm -femit-all-decls -mllvm -disable-llvm-optzns small.c

$opt -instcombine -loop-rotate -sroa -licm -loop-interchange small.bc -o small-opt.bc
opt: /home/jack-zhou/Documents/llvm/llvm_truck/llvm2/lib/Transforms/Scalar/LoopInterchange.cpp:1544: bool {anonymous}::LoopInterchangeTransform::adjustLoopBranches(): Assertion `OuterInnerReductions.find(PHI) != OuterInnerReductions.end() && "Expected a reduction PHI node"' failed.
Stack dump:
0.	Program arguments: /home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt -instcombine -loop-rotate -sroa -licm -loop-interchange small.bc -o small-opt.bc 
1.	Running pass 'Function Pass Manager' on module 'small.bc'.
2.	Running pass 'Loop Pass Manager' on function '@f'
3.	Running pass 'Interchanges loops for cache reuse' on basic block '%for.body'
 #&#8203;0 0x000055c7ba9d327a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x277727a)
 #&#8203;1 0x000055c7ba9d0f54 llvm::sys::RunSignalHandlers() (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x2774f54)
 #&#8203;2 0x000055c7ba9d1092 SignalHandler(int) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x2775092)
 #&#8203;3 0x00007f093d139890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)
 #&#8203;4 0x00007f093bdebe97 raise /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #&#8203;5 0x00007f093bded801 abort /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:81:0
 #&#8203;6 0x00007f093bddd39a __assert_fail_base /build/glibc-OTsEL5/glibc-2.27/assert/assert.c:89:0
 #&#8203;7 0x00007f093bddd412 (/lib/x86_64-linux-gnu/libc.so.6+0x30412)
 #&#8203;8 0x000055c7ba7c755a (anonymous namespace)::LoopInterchangeTransform::transform() (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x256b55a)
 #&#8203;9 0x000055c7ba7c9935 (anonymous namespace)::LoopInterchange::processLoopList(llvm::SmallVector<llvm::Loop*, 8u>) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x256d935)
#&#8203;10 0x000055c7ba7ca57d (anonymous namespace)::LoopInterchange::runOnLoop(llvm::Loop*, llvm::LPPassManager&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x256e57d)
#&#8203;11 0x000055c7b9ca642b llvm::LPPassManager::runOnFunction(llvm::Function&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x1a4a42b)
#&#8203;12 0x000055c7ba312de9 llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x20b6de9)
#&#8203;13 0x000055c7ba312ee1 llvm::FPPassManager::runOnModule(llvm::Module&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x20b6ee1)
#&#8203;14 0x000055c7ba312041 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x20b6041)
#&#8203;15 0x000055c7b8aeb74f main (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x88f74f)
#&#8203;16 0x00007f093bdceb97 __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344:0
#&#8203;17 0x000055c7b8b6354a _start (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x90754a)
Aborted (core dumped)

By using bugpoint, the optimization sequences can be reduced to "-loop-interchange".

$opt bugpoint-reduced-simplified.bc -loop-interchange
opt: /home/jack-zhou/Documents/llvm/llvm_truck/llvm2/lib/Transforms/Scalar/LoopInterchange.cpp:1544: bool {anonymous}::LoopInterchangeTransform::adjustLoopBranches(): Assertion `OuterInnerReductions.find(PHI) != OuterInnerReductions.end() && "Expected a reduction PHI node"' failed.
Stack dump:
0.	Program arguments: /home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt bugpoint-reduced-simplified.bc -loop-interchange 
1.	Running pass 'Function Pass Manager' on module 'bugpoint-reduced-simplified.bc'.
2.	Running pass 'Loop Pass Manager' on function '@f'
3.	Running pass 'Interchanges loops for cache reuse' on basic block '%for.body3'
 #&#8203;0 0x0000556e9772c27a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x277727a)
 #&#8203;1 0x0000556e97729f54 llvm::sys::RunSignalHandlers() (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x2774f54)
 #&#8203;2 0x0000556e9772a092 SignalHandler(int) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x2775092)
 #&#8203;3 0x00007f6427256890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)
 #&#8203;4 0x00007f6425f08e97 raise /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #&#8203;5 0x00007f6425f0a801 abort /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:81:0
 #&#8203;6 0x00007f6425efa39a __assert_fail_base /build/glibc-OTsEL5/glibc-2.27/assert/assert.c:89:0
 #&#8203;7 0x00007f6425efa412 (/lib/x86_64-linux-gnu/libc.so.6+0x30412)
 #&#8203;8 0x0000556e9752055a (anonymous namespace)::LoopInterchangeTransform::transform() (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x256b55a)
 #&#8203;9 0x0000556e97522935 (anonymous namespace)::LoopInterchange::processLoopList(llvm::SmallVector<llvm::Loop*, 8u>) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x256d935)
#&#8203;10 0x0000556e9752357d (anonymous namespace)::LoopInterchange::runOnLoop(llvm::Loop*, llvm::LPPassManager&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x256e57d)
#&#8203;11 0x0000556e969ff42b llvm::LPPassManager::runOnFunction(llvm::Function&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x1a4a42b)
#&#8203;12 0x0000556e9706bde9 llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x20b6de9)
#&#8203;13 0x0000556e9706bee1 llvm::FPPassManager::runOnModule(llvm::Module&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x20b6ee1)
#&#8203;14 0x0000556e9706b041 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x20b6041)
#&#8203;15 0x0000556e9584474f main (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x88f74f)
#&#8203;16 0x00007f6425eebb97 __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344:0
#&#8203;17 0x0000556e958bc54a _start (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build9/bin/opt+0x90754a)
Aborted (core dumped)

---------------------------------------
int a, c, d;
char b;
int e[][1];
void f() {
  for (; a; a++) {
    b = 0;
    for (; b >= 0; b--) {
      c = 0;
      for (; c <= 0; c++) {
        int *g = &d;
        *g ^= e[c][b];
      }
    }
  }
}

**Comment by kawashima-fj** [comment]
Fixed by https://reviews.llvm.org/D102743 .
I confirmed at latest `main` branch doesn't have the problem.
