### ISSUE TITLE
SegFault optimizing C++17 aggregate initialization with inheritance.

### ISSUE THREAD

**Issue by 1b9fe3d2-9500-495a-8113-ebc124ca65d4** [llvm/llvm-project#42701]
|  |  |
| --- | --- |
| Bugzilla Link | [43356](https://llvm.org/bz43356) |
| Version | 8.0 |
| OS | Linux |
| Attachments | [Source code causing segfault](https://user-images.githubusercontent.com/93436018/143759775-cd411381-34ea-4898-964c-dcbde89e5b3b.gz), [preprocessed source](https://user-images.githubusercontent.com/93436018/143759776-be5ed05c-b3e3-421d-89b6-6e145f67f0f6.gz), [reproducer](https://user-images.githubusercontent.com/93436018/143759777-b9339579-047a-4a39-98d4-d148044e4e01.gz) |
| CC | @zygoloid |

## Extended Description 

Clang++ reliably crashes when compiling the attached source.
Expected outcome: successful compilation.

user@machine:~$  /usr/bin/clang++-8  -std=c++17 -O1 clang-crash.cpp
Stack dump:
0.	Program arguments: /usr/lib/llvm-8/bin/clang -cc1 -triple x86_64-pc-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name clang-crash.cpp -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -momit-leaf-frame-pointer -resource-dir /usr/lib/llvm-8/lib/clang/8.0.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/x86_64-linux-gnu/c++/7.4.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/x86_64-linux-gnu/c++/7.4.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/backward -internal-isystem /usr/include/clang/8.0.0/include/ -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-8/lib/clang/8.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O1 -std=c++17 -fdeprecated-macro -fdebug-compilation-dir /home/hendrik -ferror-limit 19 -fmessage-length 211 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/clang-crash-da01be.o -x c++ clang-crash.cpp -faddrsig 
1.	<eof> parser at end of file
2.	Per-function optimization
3.	Running pass 'SROA' on function '@_Z1fv'
 #&#8203;0 0x00007f99a776c4bf llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/lib/x86_64-linux-gnu/libLLVM-8.so.1+0x9724bf)
 #&#8203;1 0x00007f99a776a910 llvm::sys::RunSignalHandlers() (/usr/lib/x86_64-linux-gnu/libLLVM-8.so.1+0x970910)
 #&#8203;2 0x00007f99a776c8c8 (/usr/lib/x86_64-linux-gnu/libLLVM-8.so.1+0x9728c8)
 #&#8203;3 0x00007f99aaa59890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)
 #&#8203;4 0x00007f99a77b51b0 llvm::BasicBlock::getModule() const (/usr/lib/x86_64-linux-gnu/libLLVM-8.so.1+0x9bb1b0)
 #&#8203;5 0x00007f99a81a0166 (/usr/lib/x86_64-linux-gnu/libLLVM-8.so.1+0x13a6166)
 #&#8203;6 0x00007f99a818a8a3 (/usr/lib/x86_64-linux-gnu/libLLVM-8.so.1+0x13908a3)
 #&#8203;7 0x00007f99a818a4d0 (/usr/lib/x86_64-linux-gnu/libLLVM-8.so.1+0x13904d0)
 #&#8203;8 0x00007f99a8193559 llvm::SROA::runOnAlloca(llvm::AllocaInst&) (/usr/lib/x86_64-linux-gnu/libLLVM-8.so.1+0x1399559)
 #&#8203;9 0x00007f99a8194755 llvm::SROA::runImpl(llvm::Function&, llvm::DominatorTree&, llvm::AssumptionCache&) (/usr/lib/x86_64-linux-gnu/libLLVM-8.so.1+0x139a755)
#&#8203;10 0x00007f99a819f9b3 (/usr/lib/x86_64-linux-gnu/libLLVM-8.so.1+0x13a59b3)
#&#8203;11 0x00007f99a785f7f0 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib/x86_64-linux-gnu/libLLVM-8.so.1+0xa657f0)
#&#8203;12 0x00007f99a785ef2e llvm::legacy::FunctionPassManagerImpl::run(llvm::Function&) (/usr/lib/x86_64-linux-gnu/libLLVM-8.so.1+0xa64f2e)
#&#8203;13 0x00007f99a785eec0 llvm::legacy::FunctionPassManager::run(llvm::Function&) (/usr/lib/x86_64-linux-gnu/libLLVM-8.so.1+0xa64ec0)
#&#8203;14 0x00000000006dc072 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/usr/lib/llvm-8/bin/clang+0x6dc072)
#&#8203;15 0x0000000000d58b0f (/usr/lib/llvm-8/bin/clang+0xd58b0f)
#&#8203;16 0x00000000011df3c3 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/llvm-8/bin/clang+0x11df3c3)
#&#8203;17 0x0000000000addfcf clang::FrontendAction::Execute() (/usr/lib/llvm-8/bin/clang+0xaddfcf)
#&#8203;18 0x0000000000a9bb18 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/llvm-8/bin/clang+0xa9bb18)
#&#8203;19 0x0000000000b644c6 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/llvm-8/bin/clang+0xb644c6)
#&#8203;20 0x00000000006a32e7 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/llvm-8/bin/clang+0x6a32e7)
#&#8203;21 0x00000000006a17d6 main (/usr/lib/llvm-8/bin/clang+0x6a17d6)
#&#8203;22 0x00007f99a60ebb97 __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344:0
#&#8203;23 0x000000000069eeca _start (/usr/lib/llvm-8/bin/clang+0x69eeca)
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 8.0.0-3~ubuntu18.04.1 (tags/RELEASE_800/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/clang-crash-d106dc.cpp
clang: note: diagnostic msg: /tmp/clang-crash-d106dc.sh
clang: note: diagnostic msg: 

********************

**Comment by wheatman** [comment]
This seems to have been fixed between 8.0.0 and 9.0.0
https://godbolt.org/z/Pbr88n3Ts

For reference

code 
```
#include <chrono>
#include <vector>

using Duration = std::chrono::duration<double, std::ratio<1, 1>>;
struct foo {
    std::vector<double> f;
};
    
struct bar : public foo {
    std::chrono::duration<double, std::ratio<1, 1>> time;
};


void f() {
    bar s{std::vector<double>{0.0}, Duration{0.0}};
}

int main() {
    return 1;
}
```

Crash backtrace

```
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-8.0.0/bin/clang-8 -cc1 -triple x86_64-unknown-linux-gnu -S -disable-free -disable-llvm-verifier -discard-value-names -main-file-name example.cpp -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -coverage-notes-file /app/output.gcno -resource-dir /opt/compiler-explorer/clang-8.0.0/lib/clang/8.0.0 -internal-isystem /opt/compiler-explorer/gcc-8.3.0/lib/gcc/x86_64-linux-gnu/8.3.0/../../../../include/c++/8.3.0 -internal-isystem /opt/compiler-explorer/gcc-8.3.0/lib/gcc/x86_64-linux-gnu/8.3.0/../../../../include/c++/8.3.0/x86_64-linux-gnu -internal-isystem /opt/compiler-explorer/gcc-8.3.0/lib/gcc/x86_64-linux-gnu/8.3.0/../../../../include/c++/8.3.0/backward -internal-isystem /usr/local/include -internal-isystem /opt/compiler-explorer/clang-8.0.0/lib/clang/8.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O1 -std=c++17 -fdeprecated-macro -fdebug-compilation-dir /app -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -mllvm --x86-asm-syntax=intel -o /app/output.s -x c++ <source> -faddrsig 
1.	<eof> parser at end of file
2.	Per-function optimization
3.	Running pass 'SROA' on function '@_Z1fv'
 #0 0x0000555702c454fa llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x24454fa)
 #1 0x0000555702c43494 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x2443494)
 #2 0x0000555702c435d2 SignalHandler(int) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x24435d2)
 #3 0x00007f4a9200b420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00005557025cc380 llvm::BasicBlock::getModule() const (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x1dcc380)
 #5 0x0000555702b52ece llvm::sroa::AllocaSlices::SliceBuilder::visitStoreInst(llvm::StoreInst&) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x2352ece)
 #6 0x0000555702b58af3 llvm::sroa::AllocaSlices::AllocaSlices(llvm::DataLayout const&, llvm::AllocaInst&) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x2358af3)
 #7 0x0000555702b6394b llvm::SROA::runOnAlloca(llvm::AllocaInst&) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x236394b)
 #8 0x0000555702b65811 llvm::SROA::runImpl(llvm::Function&, llvm::DominatorTree&, llvm::AssumptionCache&) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x2365811)
 #9 0x0000555702b6739c llvm::sroa::SROALegacyPass::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x236739c)
#10 0x0000555702678179 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x1e78179)
#11 0x000055570267828c llvm::legacy::FunctionPassManagerImpl::run(llvm::Function&) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x1e7828c)
#12 0x0000555702678572 llvm::legacy::FunctionPassManager::run(llvm::Function&) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x1e78572)
#13 0x0000555702e50113 (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x2650113)
#14 0x0000555702e5298b clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x265298b)
#15 0x00005557038a1adf clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x30a1adf)
#16 0x000055570402dd69 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x382dd69)
#17 0x00005557038a09d7 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x30a09d7)
#18 0x00005557032e0a86 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x2ae0a86)
#19 0x00005557032a2e8c clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x2aa2e8c)
#20 0x0000555703399f2b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0x2b99f2b)
#21 0x0000555701305b38 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0xb05b38)
#22 0x000055570124a929 main (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0xa4a929)
#23 0x00007f4a91ab9083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#24 0x0000555701302dca _start (/opt/compiler-explorer/clang-8.0.0/bin/clang-8+0xb02dca)
clang-8: error: unable to execute command: Segmentation fault (core dumped)
clang-8: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 254
```
