### ISSUE TITLE
wasm-ld: error: test.o: relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol version_getter; recompile with -fPIC

### ISSUE THREAD

**Issue by 3840186b-43ba-4c0d-9620-502c0a52db92** [llvm/llvm-project#42738]
|  |  |
| --- | --- |
| Bugzilla Link | [43393](https://llvm.org/bz43393) |
| Version | 12.0 |
| OS | Linux |

## Extended Description 
This used to work at revision 358327, but seems to have stopped working with the 9 release. Consider the file (test.c:

int get_version() { return 0; }
int (*version_getter)() = &get_version;
__attribute__ ((visibility("default"))) int version() { return (*version_getter)(); }

Compiling this with

clang-9 --compile -fpic -fvisibility=hidden --target=wasm32-unknown-unknown-wasm -fno-builtin -ffreestanding test.c -o test.o
wasm-ld -o test.wasm --import-memory --shared --no-entry --gc-sections --export=__wasm_call_ctors test.o

yields

wasm-ld: error: test.o: relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol version_getter; recompile with -fPIC

But note that I am compiling it with -fPIC (and it used to work).

**Comment by km19809** [comment]
Is there any update? I'm suffering a similar issue.

**Comment by sbc100** [comment]
Simplified example:

```
$ cat test.c
int (*func_ptr)();

int version() {
  return func_ptr();
}
$ clang -c -fPIC -fvisibility=default --target=wasm32-unknown-emscripten test.c 
$ wasm-ld -o test.wasm --shared test.o 
wasm-ld: warning: creating shared libraries, with -shared, is not yet stable
wasm-ld: error: test.o: relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol `func_ptr`; recompile with -fPIC
```

The problem only occurs when compiling with `wasm32-unknown-unknown`.   With `wasm32-unknown-emscripten` it works as expected:

```
$ clang -c -fPIC -fvisibility=default --target=wasm32-unknown-emscripten test.c -o test.o
$ wasm-ld -o test.wasm --shared test.o
wasm-ld: warning: creating shared libraries, with -shared, is not yet stable
```

As the warnings say the PIC ABI is somewhat experimental and that only place it is know to actually work and get tested is within emscripten.

**Comment by sbc100** [comment]
I think this can be closes as WAI, but can you first confirm that using the emscripten triple with ToT works for you?

**Comment by km19809** [comment]
@sbc100 I tested your emscripten triplet example, then It compiled successfully. 
That means my problem does not come from this issue.
As I think, it can be closed now.
Thank you.
