### ISSUE TITLE
Linker error when building the LLVM 9.0 in Centos 7 docker image

### ISSUE THREAD

**Issue by DoDoENT** [llvm/llvm-project#42756]
|  |  |
| --- | --- |
| Bugzilla Link | [43411](https://llvm.org/bz43411) |
| Version | 9.0 |
| OS | Linux |

## Extended Description 
When trying to build LLVM 9.0 using two-stage build described with this Dockerfile: https://github.com/microblink/centos-clang/blob/2884171f13ea3c4996fb992946733f38d4cd56f8/Dockerfile build fails with the following error:

[3558/5130] Linking CXX shared library lib/libclang-cpp.so.9
FAILED: lib/libclang-cpp.so.9 
: <invocation ommited due to bugzilla limit of 65535 characters > :
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: lib/libLLVMRuntimeDyld.a(RTDyldMemoryManager.cpp.o): in function `llvm::RTDyldMemoryManager::registerEHFramesInProcess(unsigned char*, unsigned long)':
RTDyldMemoryManager.cpp:(.text._ZN4llvm19RTDyldMemoryManager25registerEHFramesInProcessEPhm+0x1): undefined reference to `__register_frame'
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: lib/libLLVMRuntimeDyld.a(RTDyldMemoryManager.cpp.o): in function `llvm::RTDyldMemoryManager::deregisterEHFramesInProcess(unsigned char*, unsigned long)':
RTDyldMemoryManager.cpp:(.text._ZN4llvm19RTDyldMemoryManager27deregisterEHFramesInProcessEPhm+0x1): undefined reference to `__deregister_frame'
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: lib/libLLVMRuntimeDyld.a(RTDyldMemoryManager.cpp.o): in function `llvm::RTDyldMemoryManager::registerEHFrames(unsigned char*, unsigned long, unsigned long)':
RTDyldMemoryManager.cpp:(.text._ZN4llvm19RTDyldMemoryManager16registerEHFramesEPhmm+0x1b): undefined reference to `__register_frame'
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: lib/libLLVMRuntimeDyld.a(RTDyldMemoryManager.cpp.o): in function `llvm::RTDyldMemoryManager::deregisterEHFrames()':
RTDyldMemoryManager.cpp:(.text._ZN4llvm19RTDyldMemoryManager18deregisterEHFramesEv+0x24): undefined reference to `__deregister_frame'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)

You can easily reproduce that by trying to build the docker image using Dockerfile from link above.

**Comment by arsenm** [comment]
Old build issue on old release
