### ISSUE TITLE
Segfault when using const value of union type in a block with optimizations

### ISSUE THREAD

**Issue by nicopauss** [llvm/llvm-project#42751]
|  |  |
| --- | --- |
| Bugzilla Link | [43406](https://llvm.org/bz43406) |
| Version | 8.0 |
| OS | Linux |
| Attachments | [Segfault block union const source code](https://user-images.githubusercontent.com/93436011/143759803-2a237905-6823-47b0-b640-001a792eb1f0.gz), [Segfault block union const backtrace](https://user-images.githubusercontent.com/93436011/143759804-fcdb943f-c032-4082-9628-8d28ad6c8fef.gz) |
| CC | @shining,@DougGregor,@efriedma-quic,@zygoloid |

## Extended Description 

When using a const value of a union type defined outside a block inside a block with optimizations, clang is crashing with Segmentation fault at llvm::PointerType::get(llvm::Type*, unsigned int).

The whole code and clang backtrace can be seen here:
https://godbolt.org/z/wtsleX

The bug is present on clang 3.3 up to clang 8.0.0.
It appears to have been solved on clang 9.0.0.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 15: https://godbolt.org/z/f1jjhsxva
