### ISSUE TITLE
clang-tidy cert-dcl21-cpp is confusing (wrong?)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#42788]
|  |  |
| --- | --- |
| Bugzilla Link | [43443](https://llvm.org/bz43443) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @EugeneZelenko,@Xazax-hun |

## Extended Description 
Until 8.0.0 the documentation of cert-dcl21-cpp (https://releases.llvm.org/8.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/cert-dcl21-cpp.html) pointed to a, now, broken link.

The current documentation (https://clang.llvm.org/extra/clang-tidy/checks/cert-dcl21-cpp.html) says "all of the CERT recommendations have been removed from public view", but I can see some in https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=88046322 (but not DCL21-CPP).

When you look for more information you end up in https://stackoverflow.com/questions/52871026/overloaded-operator-returns-a-non-const-and-clang-tidy-complains/52871143#52871143, which argues such a recommendation must come from a pre-rvalue references world. AFAIU it's correct (at least about it breaking optimizations).

Should the check be removed? Maybe more information should be included in the description?

**Comment by carlosgalvezp** [comment]
The check has been removed from the CERT standard and moved into [the Void section](https://wiki.sei.cmu.edu/confluence/display/cplusplus/VOID+DCL21-CPP.+Overloaded+postfix+increment+and+decrement+operators+should+return+a+const+object).

Patch to deprecate: https://reviews.llvm.org/D147563
Will fully remove 2 releases after that.
