### ISSUE TITLE
loop-versioning crashes: Assertion `DT.dominates(RHead, LHead) && "No dominance between recurrences used by one SCEV?"' failed.

### ISSUE THREAD

**Issue by 952e6d5a-d994-4724-a6d1-07613b2d95a8** [llvm/llvm-project#42782]
|  |  |
| --- | --- |
| Bugzilla Link | [43437](https://llvm.org/bz43437) |
| Version | trunk |
| OS | Linux |
| Attachments | [find_best_colors.bc](https://user-images.githubusercontent.com/92601252/143759827-cb9507c2-fd90-4ada-b293-d630bfdeee3b.gz) |
| CC | @fhahn |

## Extended Description 

This bug is triggered by a function extracted from the jpeg_c program in cbench benchmark.

$clang -v
clang version 10.0.0 (trunk 372743)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$opt -gvn -sroa -loop-rotate -loop-unroll -simplifycfg -correlated-propagation -hotcoldsplit -loop-versioning  find_best_colors.bc 
WARNING: You're attempting to print out a bitcode file.
This is inadvisable as it may cause display problems. If
you REALLY want to taste LLVM bitcode first-hand, you
can force output with the `-f' option.

opt: /home/jack-zhou/Documents/llvm/llvm_truck/llvm2/lib/Analysis/ScalarEvolution.cpp:707: int CompareSCEVComplexity(llvm::EquivalenceClasses<const llvm::SCEV*>&, llvm::EquivalenceClasses<const llvm::Value*>&, const llvm::LoopInfo*, const llvm::SCEV*, const llvm::SCEV*, llvm::DominatorTree&, unsigned int): Assertion `DT.dominates(RHead, LHead) && "No dominance between recurrences used by one SCEV?"' failed.
Stack dump:
0.	Program arguments: /home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt -gvn -sroa -loop-rotate -loop-unroll -simplifycfg -correlated-propagation -hotcoldsplit -loop-versioning find_best_colors.bc 
1.	Running pass 'Function Pass Manager' on module 'find_best_colors.bc'.
2.	Running pass 'Loop Versioning' on function '@find_best_colors'
 #&#8203;0 0x000055f39c08c32a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x278232a)
 #&#8203;1 0x000055f39c08a004 llvm::sys::RunSignalHandlers() (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x2780004)
 #&#8203;2 0x000055f39c08a142 SignalHandler(int) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x2780142)
 #&#8203;3 0x00007fdc53f46890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)
 #&#8203;4 0x00007fdc52bf8e97 raise /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #&#8203;5 0x00007fdc52bfa801 abort /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:81:0
 #&#8203;6 0x00007fdc52bea39a __assert_fail_base /build/glibc-OTsEL5/glibc-2.27/assert/assert.c:89:0
 #&#8203;7 0x00007fdc52bea412 (/lib/x86_64-linux-gnu/libc.so.6+0x30412)
 #&#8203;8 0x000055f39b3f97fb CompareSCEVComplexity(llvm::EquivalenceClasses<llvm::SCEV const*>&, llvm::EquivalenceClasses<llvm::Value const*>&, llvm::LoopInfo const*, llvm::SCEV const*, llvm::SCEV const*, llvm::DominatorTree&, unsigned int) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x1aef7fb)
 #&#8203;9 0x000055f39b404d7c GroupByComplexity(llvm::SmallVectorImpl<llvm::SCEV const*>&, llvm::LoopInfo*, llvm::DominatorTree&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x1afad7c)
#&#8203;10 0x000055f39b4170d2 llvm::ScalarEvolution::getAddExpr(llvm::SmallVectorImpl<llvm::SCEV const*>&, llvm::SCEV::NoWrapFlags, unsigned int) (.part.1507) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x1b0d0d2)
#&#8203;11 0x000055f39b438283 ExposePointerBase(llvm::SCEV const*&, llvm::SCEV const*&, llvm::ScalarEvolution&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x1b2e283)
#&#8203;12 0x000055f39b44545a llvm::SCEVExpander::visitAddRecExpr(llvm::SCEVAddRecExpr const*) (.part.530) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x1b3b45a)
#&#8203;13 0x000055f39b43edc0 llvm::SCEVExpander::expand(llvm::SCEV const*) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x1b34dc0)
#&#8203;14 0x000055f39b43f30c llvm::SCEVExpander::expandCodeFor(llvm::SCEV const*, llvm::Type*) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x1b3530c)
#&#8203;15 0x000055f39b33886b expandBounds(llvm::RuntimePointerChecking::CheckingPtrGroup const*, llvm::Loop*, llvm::Instruction*, llvm::SCEVExpander&, llvm::ScalarEvolution*, llvm::RuntimePointerChecking const&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x1a2e86b)
#&#8203;16 0x000055f39b338d76 llvm::LoopAccessInfo::addRuntimeChecks(llvm::Instruction*, llvm::SmallVectorImpl<std::pair<llvm::RuntimePointerChecking::CheckingPtrGroup const*, llvm::RuntimePointerChecking::CheckingPtrGroup const*> > const&) const (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x1a2ed76)
#&#8203;17 0x000055f39c14ed92 llvm::LoopVersioning::versionLoop(llvm::SmallVectorImpl<llvm::Instruction*> const&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x2844d92)
#&#8203;18 0x000055f39c150700 (anonymous namespace)::LoopVersioningPass::runOnFunction(llvm::Function&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x2846700)
#&#8203;19 0x000055f39b9cad09 llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x20c0d09)
#&#8203;20 0x000055f39b9cae01 llvm::FPPassManager::runOnModule(llvm::Module&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x20c0e01)
#&#8203;21 0x000055f39b9c9f61 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x20bff61)
#&#8203;22 0x000055f39a19b6ff main (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x8916ff)
#&#8203;23 0x00007fdc52bdbb97 __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344:0
#&#8203;24 0x000055f39a21351a _start (/home/jack-zhou/Documents/llvm/llvm_truck/llvm2/build10/bin/opt+0x90951a)
Aborted (core dumped)

Bugpoint failed to reproduce this bug.

**Comment by hiraditya** [comment]
Doesn't repro anymore.

```sh
./bin/opt -gvn -sroa -loop-rotate -loop-unroll -simplifycfg -correlated-propagation -hotcoldsplit -loop-versioning 143759827-cb9507c2-fd90-4ada-b293-d630bfdeee3b  -S -o a.s --stats
===-------------------------------------------------------------------------===
                          ... Statistics Collected ...
===-------------------------------------------------------------------------===

  92 aa                           - Number of MayAlias results
 127 aa                           - Number of MustAlias results
1709 aa                           - Number of NoAlias results
 132 assume-queries               - Number of Queries into an assume assume bundles
 124 basicaa                      - Number of times a GEP is decomposed
 251 bitcode-reader               - Number of Metadata records loaded
  10 bitcode-reader               - Number of MDStrings loaded
  76 capture-tracking             - Number of pointers not captured
   2 correlated-value-propagation - Number of function pointer arguments marked non-null
   2 correlated-value-propagation - Number of phis propagated
   1 correlated-value-propagation - Number of sext converted to zext
   8 gvn                          - Number of blocks speculated as available in IsValueFullyAvailableInBlock(), max
   5 gvn                          - Number of blocks merged
  84 gvn                          - Number of instructions deleted
  55 gvn                          - Number of loads deleted
   4 gvn                          - Number of instructions simplified
   3 gvn                          - Number of loads PRE'd
 212 ipt                          - Number of insts scanned while updating ibt
  29 ir                           - Number of renumberings across all blocks
   8 lcssa                        - Number of live out of a loop variables
   6 local                        - Number of PHI's that got CSE'd
  10 loop-rotate                  - Number of instructions cloned into loop preheader
   5 loop-rotate                  - Number of loops rotated
   1 loop-unroll                  - Number of loops completely unrolled
   2 loop-unroll                  - Number of loops unrolled (completely or otherwise)
   3 mem2reg                      - Number of alloca's promoted within one block
   8 mem2reg                      - Number of PHI nodes inserted
   8 mem2reg                      - Number of alloca's promoted with a single store
   8 memdep                       - Number of block queries that were completely cached
  50 memdep                       - Number of fully cached non-local ptr responses
 327 memdep                       - Number of uncached non-local ptr responses
   8 scalar-evolution             - Number of loops with predictable loop counts
   7 simplifycfg                  - Number of blocks simplified
   1 sroa                         - Maximum number of partitions per alloca
   7 sroa                         - Maximum number of uses of a partition
  80 sroa                         - Number of alloca partition uses rewritten
  23 sroa                         - Number of alloca partitions formed
  25 sroa                         - Number of allocas analyzed for replacement
  96 sroa                         - Number of instructions deleted
  23 sroa                         - Number of allocas promoted to SSA values

```

**Comment by fhahn** [comment]
Thanks for confirming!
