### ISSUE TITLE
attribute target syntax doesn't match -march options

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#42793]
|  |  |
| --- | --- |
| Bugzilla Link | [43448](https://llvm.org/bz43448) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#4440  |
| CC | @DougGregor,@echristo,@erichkeane,@fhahn,@kbeyls,@zygoloid,@stephenhines |

## Extended Description 
When looking into an ISA-extension-assembler-directive related issue in assembling the Linux kernel w/ Clang (https://github.com/ClangBuiltLinux/linux/issues/671, https://github.com/ClangBuiltLinux/linux/issues/573), I ran into some issue with the ARMv8.1 lse extensions.

It seems that we can either:
1. use an assembler `.arch armv8-a+lse` directive
2. use a command line arg `-march=armv8-a+lse`
3. use a function level attribute

Unfortunately, 3 gets a little complicated in terms of our "compatibility w/ GCC" which is a constraint for compiling the Linux kernel w/ Clang.
```cpp
__attribute__((target("arch=armv8-a+lse")))
void foo (void){}
```
produces a warning in Clang, but is accepted by GCC.
```cpp
__attribute__((target("lse")))
void foo (void){}
```
produces an error in GCC, but is accepted by Clang.

I find the current behavior in Clang for 3 inconsistent with 1+2.

**Comment by davemgreen** [comment]
We implemented mostly the same target attribute support as GCC a while ago.
https://godbolt.org/z/nf66T61o7
There are still some changes happening to support all the combinations, but it should work as described in this ticket now.
