### ISSUE TITLE
Can't install lldb-9 apt package on Debian 10 Buster

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#42796]
|  |  |
| --- | --- |
| Bugzilla Link | [43451](https://llvm.org/bz43451) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @adrianimboden,@pedro-w |

## Extended Description 
I'd like to install LLVM 9 (including lldb) on Debian 10 Buster.

Following the instructions at https://apt.llvm.org:
$ wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
$ sudo apt-add-repository 'deb http://apt.llvm.org/buster/ llvm-toolchain-buster-9 main'
$ sudo apt-get update

All that seems to work. But then:

$ sudo apt install clang-9 lldb-9 lld-9 clangd-9
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 lldb-9 : Depends: llvm-9-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

However, when I run:
$ sudo apt install llvm-9-dev
The llvm-9-dev package and its many dependencies appear to install normally, without raising an error.
But, even with llvm-9-dev installed, I still get the 'unmet dependencies' error when I again try to install lldb-9.

The package which I can't install:
lldb-9/unknown 1:9~svn372167-1~exp1~20190917193038.54 amd64

**Comment by sylvestre** [comment]
too old and fixed now
