### ISSUE TITLE
warning: unused variable - for __attribute__(cleanup(...))

### ISSUE THREAD

**Issue by jankratochvil** [llvm/llvm-project#42827]
|  |  |
| --- | --- |
| Bugzilla Link | [43482](https://llvm.org/bz43482) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
static void cleanup(int *p) {}
int main(void) {
  __attribute__((cleanup(cleanup))) int var;
}

cleanup.c:3:41: warning: unused variable 'var' [-Wunused-variable]

gcc-9.2.1-1.fc30.x86_64 does not produce the warning.

Bugreport by: David Gilbert

FAIL: b259e7b6488208d11aee8a4b116d90a8914e115b = 2019-09-27
FAIL: clang-8.0.0-1.fc30.x86_64

**Comment by AaronBallman** [comment]
This was fixed in 877210faa447f4cc7db87812f8ed80e398fedd61 for Clang 17.0.0.
