### ISSUE TITLE
[LSR] Assert in InsertFormula

### ISSUE THREAD

**Issue by sjoerdmeijer** [llvm/llvm-project#42825]
|  |  |
| --- | --- |
| Bugzilla Link | [43480](https://llvm.org/bz43480) |
| Version | trunk |
| OS | Linux |
| Attachments | [reproducer](https://user-images.githubusercontent.com/54853335/143759851-c9b12e8a-e7cd-4a82-98cc-dfc1ec730afd.gz) |

## Extended Description 

LSR is running in this assert:

llvm/lib/Transforms/Scalar/LoopStrengthReduce.cpp:3372: bool {anonymous}::LSRInstance::InsertFormula({anonymous}::LSRUse&, unsigned int, const {anonymous}::Formula&): Assertion `isLegalUse(TTI, LU.MinOffset, LU.MaxOffset, LU.Kind, LU.AccessTy, F) && "Formula is illegal"' failed.
Stack dump:
0.	Program arguments: /data/monorepo/llvm-project/build/bin/llc sjoerd.ll 
1.	Running pass 'Function Pass Manager' on module 'sjoerd.ll'.
2.	Running pass 'Loop Pass Manager' on function '@fn1'
3.	Running pass 'Loop Strength Reduction' on basic block '%for.cond'

Running llc on the attached .ll file is enough to reproduce this.

Just for completeness, this .ll file corresponds to this creduced input file:

__fp16 *a;
void fn1() {
  for (int i; ; i++)
    foo(a[i]);
}

**Comment by fhahn** [comment]
Looks like this has been fixed on current `main`, the attached reproducer doesn't crash any longer: https://godbolt.org/z/nqE7vqaPT
