### ISSUE TITLE
llvmc plugins should be able to access target information

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#4292]
|  |  |
| --- | --- |
| Bugzilla Link | [3920](https://llvm.org/bz3920) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 
Plugins should be able to access information about the target OS
and architecture - most probably via the 'case' expression. One
use case is enabling '-relocation-model=pic' by default only on
64 bit platforms.

**Comment by asl** [comment]
llvmc is dead
