### ISSUE TITLE
no warnings with -Waddress

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#42992]
|  |  |
| --- | --- |
| Bugzilla Link | [43647](https://llvm.org/bz43647) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
clang-10 falls to emit the warning for the following:

$ cat s.c
  int main()
  {
    int *a = (void *) 0;
    int b = (&a) == ((void *) 0);
    return b;
  }

$ clang-10 -Weverything -pedantic s.c

clang version 10.0.0 (https://github.com/llvm/llvm-project.git 49c4e58b75ecec8dce75dd13c61aaeb30e14b531)
Target: x86_64-unknown-linux-gnu
Thread model: posix

[-Waddress] is enabled by default in Clang, but do not issue the warning. When compiled with GCC, warnings such as:

$ gcc -Wall s.c
s.c: In function ‘main’:
s.c:4:16: warning：the comparison will always evaluate as ‘false’ for the address of ‘a’ will never be NULL [-Waddress]
    4 |   int b = (&a) == ((void *) 0);
       |                      ^~

**Comment by Krishna-13-cyber** [comment]
Hi!,
I am trying to solve this issue by targeting **def warn_null_pointer_compare** which does not have variable at present, I suppose due to which it does not catch the address of the pointer to variable.
Please do let me know if its a right approach and on the correct track.
CC: @tbaederr @AaronBallman @cjdb @Quuxplusone

**Comment by AaronBallman** [comment]
> Please do let me know if its a right approach and on the correct track.

I think it's actually a bit easier than that, even. It looks like `Sema::DiagnoseAlwaysNonNullPointer()` is not skipping the paren expression node. When you remove the parens from `(&a)`, we diagnose correctly: https://godbolt.org/z/EWTYWqP9Y

I'd recommend looking through that function to see where we're skipping over nodes we don't care about and ensure we skip over paren AST nodes as well.

**Comment by Krishna-13-cyber** [comment]
Thanks a lot @AaronBallman !
I will work on the suggested approach.

**Comment by Krishna-13-cyber** [comment]
![image](https://user-images.githubusercontent.com/84722531/233797561-2bf862e4-ac7d-433c-886f-1a0afa603e96.png)
I have updated with a patch https://reviews.llvm.org/D149000
Thanks!
