### ISSUE TITLE
Does clang 9.0.0 version support VS2010?

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43028]
|  |  |
| --- | --- |
| Bugzilla Link | [43683](https://llvm.org/bz43683) |
| Version | 9.0 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 
there are two environment.

1. OS:WIN 7 64bit, only VS2010 installed.
2. OS:WIN 10 64bit, only VS2017 installed.

clang is installed by Pre-Built Binaries(Windows 32bit)

environment 2 is working well, but 1 is failed with same code, same bat(only VS version and OS different)

error is clang: error: linker command failed due to signal (use -v to see invocation).

It is suspected that VS2010 is the cause because only VS2010 is different in the same environment. (or OS?)

Then it seems to use VS2017, but the problem is that in a real environment, VS2010 should be used.

So, does clang 9.0.0 version support VS2010?

Do I need to use special options?

Thank you.

**Comment by arsenm** [comment]
Old build question, build requirements for old release should be in the docs for the old release.

https://llvm.org/docs/GettingStarted.html#host-c-toolchain-both-compiler-and-standard-library
