### ISSUE TITLE
Can't install clang-tools 10 on Ubuntu Disco

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43021]
|  |  |
| --- | --- |
| Bugzilla Link | [43676](https://llvm.org/bz43676) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @sylvestre |

## Extended Description 
On Ubuntu Disco 19.04, I set up apt.llvm.org like so: 

    apt-add-repository -yu "deb http://apt.llvm.org/disco/ llvm-toolchain-disco main"

But when I want to install clang-tools 10, like so:

    apt-get -t llvm-toolchain-disco install -yq clang-tools

it seems to ignore the specified repository, and installs Ubuntu's default version instead:

> Get:33 http://archive.ubuntu.com/ubuntu disco/universe amd64 clang-tools amd64 1:8.0-48~exp1ubuntu1 [3,208 B]

Then, when I try to forcefully use the repo, like so:

    apt-get install -yq clang-tools/llvm-toolchain-disco

it fails with:

> E: Release 'llvm-toolchain-disco' for 'clang-tools' was not found

Am I doing something wrong, or is there an underlying problem with apt.llvm.org?

**Comment by sylvestre** [comment]
I think it is now fixed
