### ISSUE TITLE
std::steady_clock::now() frequently overflows on Windows

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43048]
|  |  |
| --- | --- |
| Bugzilla Link | [43703](https://llvm.org/bz43703) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
std::steady_clock::now() multiplies the result from QueryPerformanceCounter() by nano::den (10^9), which frequently overflows, producing a negative int64_t value.  libc++ should perform this calculation more carefully to avoid overflow.

Current implementation:

  return time_point(duration(counter.QuadPart * nano::den / freq.QuadPart));

Proposed fixed implementation:

  const auto first_part = 
    (counter.QuadPart / freq.QuadPart) * nano::den;

  const auto second_part = 
    (counter.QuadPart % freq.QuadPart) * nano::den / freq.QuadPart;

  return time_point(duration(first_part + second_part));

**Comment by rprichard** [comment]
This issue is fixed by https://reviews.llvm.org/D93456.
