### ISSUE TITLE
[JumpThreading] Hangs when called with complex switch/state machines as generated by coroutines

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43065]
|  |  |
| --- | --- |
| Bugzilla Link | [43720](https://llvm.org/bz43720) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [A dirty workaround for the bug reported](https://user-images.githubusercontent.com/60944935/143759941-7f91319e-f0fa-48d8-882d-75930a5e44ba.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic |

## Extended Description 

In ProcessThreadableEdges, it is possible for PredsToFactor to be empty for its call to "ThreadEdge".

This seemingly spins the whole thing in an infinite loop, where:

  if (PredBBs.size() == 1)
    PredBB = PredBBs[0];
  else {
    LLVM_DEBUG(dbgs() << "  Factoring out " << PredBBs.size()
                      << " common predecessors.\n");
    PredBB = SplitBlockPreds(BB, PredBBs, ".thr_comm");
  }

Writes "Factors out 0 common predecessors", which seems to be a nop, leading to the same 0-edge being threaded again, and again, and again.

Perhaps someone who knows the code better than I can see if it is _always_ an error to pass an empty PredBBs to ThreadEdge, in which case it should be asserted in ThreadEdge, and/or how it's possible to end up with an empty PredBBs in the first place.

Workaround attached.

**Comment by fhahn** [comment]
There's not enough info here to reproduce this. Please re-open with a reproducer if it still is an issue on your end
