### ISSUE TITLE
Compares involving NaN are done wrong

### ISSUE THREAD

**Issue by dbc7d0cf-60de-4ba2-bc9a-c1b7219315df** [llvm/llvm-project#43072]
|  |  |
| --- | --- |
| Bugzilla Link | [43727](https://llvm.org/bz43727) |
| Version | 8.0 |
| OS | Linux |
| CC | @topperc,@DougGregor,@zygoloid,@rotateright |

## Extended Description 
Compares (<, <=, >=, >) that involve a floating-point NaN are done wrong with
respect to raising invalid and/or being false.  This is on Intel hardware.

**Comment by arsenm** [comment]
Technically need to enable FENV_ACCESS, which is only semi-supported. Duplicate #8472
