### ISSUE TITLE
static constexpr member is not a constant expression when read from a reference

### ISSUE THREAD

**Issue by 0eb9519d-6b48-43f6-baa3-0a8fdc50e528** [llvm/llvm-project#43077]
|  |  |
| --- | --- |
| Bugzilla Link | [43732](https://llvm.org/bz43732) |
| Resolution | DUPLICATE |
| Resolved on | Jun 29, 2020 09:18 |
| Version | 9.0 |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
#include <type_traits>

struct A
{
  static constexpr std::true_type value {};
};

int main()
{
  A a;
  A& ref = a;
  auto v = ref.value;
  constexpr bool r1 = a.value; //ok
  constexpr bool r2 = ref.value; // error
  constexpr bool r3 = v; // ok
}

This works with GCC and MSVC
https://godbolt.org/z/NiIz02

**Comment by pinskia** [comment]
Note https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2280r4.html changes this.
