### ISSUE TITLE
Clang-format: BraceWrapping/AfterCaseLabel default value does not match old behavior

### ISSUE THREAD

**Issue by 61241ac1-6d17-4107-abc9-1fb3321c87fa** [llvm/llvm-project#43079]
|  |  |
| --- | --- |
| Bugzilla Link | [43734](https://llvm.org/bz43734) |
| Version | 9.0 |
| OS | Linux |
| CC | @jordan-woyak,@mydeveloperday |

## Extended Description 
With the addition of the BraceWrapping/AfterCaseLabel option the default behavior has changed and it seems impossible to produce a .clang-format file which produces consistent output across versions.

The following .clang-format file produces different output depending on the clang-format version.

---
BreakBeforeBraces: Custom
BraceWrapping:
  AfterControlStatement: true
  AfterFunction:   true

$ clang-format --version
clang-format version 7.0.0 (tags/RELEASE_700/final)

$ clang-format <<< 'switch (42) { default:{ break; } }'
```
switch (42)
{
default:
{
  break;
}
}
```

$ clang-format --version
clang-format version 9.0.0 (tags/RELEASE_900/final)

$ clang-format <<< 'switch (42) { default:{ break; } }'
```
switch (42) {
default: {
  break;
}
}
```

Note that adding `  AfterCaseLabel: true` restores the old behavior however having this line stops older versions of clang-format from running.
`YAML:4:19: error: unknown key 'AfterCaseLabel'`

**Comment by mydeveloperday** [comment]
I believe for most format AfterCaseLabel default does tend to follow AfterControlStatement

I'm closing this as I think there is nothing we can do for old versions and AfterCaseLabel was added some versions ago
