### ISSUE TITLE
clang-tidy doesn't handle unicode arguments on Windows

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43096]
|  |  |
| --- | --- |
| Bugzilla Link | [43751](https://llvm.org/bz43751) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic,@rui314 |

## Extended Description 
clang-tidy doesn't seem to handle arguments with unicode characters properly on Windows. It does work on Ubuntu 18.04 (using utf8).

For example, running "clang-tidy.exe mainπΣ.cpp --p=build/compile_commands.json" (in powershell) results in "Skipping C:\Users\safreed\source\repos\unicode\mainpS.cpp. Compile command not found." (notice pi and sigma are replaced with p and S).

Some more information:

Windows 10 build 18362, system locale is English (United States)

clang-tidy.exe --version:
    LLVM (http://llvm.org/):
      LLVM version 7.0.0
      Optimized build.
      Default target: x86_64-pc-win32
      Host CPU: skylake

If I change system locale to the experimental utf8 support, clang-tidy works as expected

If I take the command line arguments and mess with the encoding a bit in C# it works (although this isn't a good solution since it's unsafe): Encoding.Default.GetString(Encoding.UTF8.GetBytes("mainπΣ.cpp --p=build/compile_commands.json"))

Passing arguments with unicode characters does work with clang.exe

**Comment by felix642** [comment]
This issue was fixed by commit https://github.com/llvm/llvm-project/commit/a7acba29c19ac67c77ed282ec9432602ae21268d. If anyone could close this issue, that would be great.
