### ISSUE TITLE
ClangLLVM failed due to error `C3861: 'F': identifier not found` with `/permissive-` on MSVC

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43146]
|  |  |
| --- | --- |
| Bugzilla Link | [43801](https://llvm.org/bz43801) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@jdoerfert,@zygoloid,@rnk |

## Extended Description 
ClangLLVM failed due to `error C3861: 'F': identifier not found` with `/permissive-` on MSVC. It can be reproduced on 2c4ca68 reversion on LLVM master branch. Could you please have a look at this issue? Thanks a lot!

Repro steps:
1 `git clone -c core.autocrlf=false https://github.com/llvm-mirror/llvm D:\llvm\src\`     
2 `git clone -c core.autocrlf=false https://github.com/llvm-mirror/clang D:\llvm\src\tools\clang`
3 open a VS 2017 x86 command prompt and browse to `D:\llvm`
4 `mkdir build_x86 && pushd build_x86`
5 `set _CL_=/permissive-`
6 `cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\src\`
7 `msbuild /maxcpucount:4 /p:Platform=Win32 /p:Configuration=RelWithDebInfo build_x86\ALL_BUILD.vcxproj /t:Rebuild`

Failures:
```
D:\llvm\src\lib\Transforms\IPO\Attributor.cpp(592): error C3861: 'F': identifier not found
D:\llvm\src\lib\Transforms\IPO\Attributor.cpp(602): note: see reference to class template instantiation '`anonymous-namespace'::AAComposeTwoGenericDeduction<AAType,Base,StateType,F,G>' being compiled
```

**Comment by Endilll** [comment]
We don't support building with VS 2017, and per Reid it doesn't reproduce with VS 2019.
