### ISSUE TITLE
Question: Using std::filesystem on macOS prior 10.15 with statically linked libc++

### ISSUE THREAD

**Issue by k15tfu** [llvm/llvm-project#43169]
|  |  |
| --- | --- |
| Bugzilla Link | [43824](https://llvm.org/bz43824) |
| Version | 9.0 |
| OS | MacOS X |
| CC | @k15tfu,@mclow |

## Extended Description 
My program linked statically with libc++.a (among with libc++abi.a), and it's intended to run on macOS Sierra or higher. When we used Clang 6, mmacosx-version-min was set to 10.12 and we were able to use std::experimental::filesystem. Now we decided to upgrade to Clang 9, and faced that now mmacosx-version-min should be set to 10.15.

Questions:
1. Can std::filesystem be used on macOS(-es) prior 10.15 if linking against libc++ statically?
2. How does mmacosx-version-min affect statically linked programs? I thought it only need for those who rely on system's libc++.dylib and its capabilities.

**Comment by arsenm** [comment]
Question that looks answered
