### ISSUE TITLE
gvn crashes: Assertion `castIsValid(op, S, Ty) && "Invalid cast!"' failed.

### ISSUE THREAD

**Issue by 952e6d5a-d994-4724-a6d1-07613b2d95a8** [llvm/llvm-project#43177]
|  |  |
| --- | --- |
| Bugzilla Link | [43832](https://llvm.org/bz43832) |
| Version | trunk |
| OS | Linux |
| Attachments | [fallbackSort.bc](https://user-images.githubusercontent.com/92601252/143759990-2e5a15b7-4e0c-4f91-83d4-d2220a565311.gz) |

## Extended Description 

$clang -v
clang version 10.0.0 (https://github.com/llvm/llvm-project.git 7cd301677461b16a1a5a437a6f6be0b5f0125eaf)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$opt -mem2reg -loop-unroll -loop-simplifycfg -early-cse -load-store-vectorizer -indvars -loop-rotate -loop-unroll -break-crit-edges -loop-reduce -gvn fallbackSort.bc 
WARNING: You're attempting to print out a bitcode file.
This is inadvisable as it may cause display problems. If
you REALLY want to taste LLVM bitcode first-hand, you
can force output with the `-f' option.

opt: /home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/llvm/lib/IR/Instructions.cpp:2749: static llvm::CastInst* llvm::CastInst::Create(llvm::Instruction::CastOps, llvm::Value*, llvm::Type*, const llvm::Twine&, llvm::Instruction*): Assertion `castIsValid(op, S, Ty) && "Invalid cast!"' failed.
Stack dump:
0.	Program arguments: /home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt -mem2reg -loop-unroll -loop-simplifycfg -early-cse -load-store-vectorizer -indvars -loop-rotate -loop-unroll -break-crit-edges -loop-reduce -gvn fallbackSort.bc 
1.	Running pass 'Function Pass Manager' on module 'fallbackSort.bc'.
2.	Running pass 'Global Value Numbering' on function '@fallbackSort'
 #&#8203;0 0x0000562f500bceaa llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x286aeaa)
 #&#8203;1 0x0000562f500bab84 llvm::sys::RunSignalHandlers() (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x2868b84)
 #&#8203;2 0x0000562f500bacc2 SignalHandler(int) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x2868cc2)
 #&#8203;3 0x00007fea89466890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)
 #&#8203;4 0x00007fea88118e97 raise /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #&#8203;5 0x00007fea8811a801 abort /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:81:0
 #&#8203;6 0x00007fea8810a39a __assert_fail_base /build/glibc-OTsEL5/glibc-2.27/assert/assert.c:89:0
 #&#8203;7 0x00007fea8810a412 (/lib/x86_64-linux-gnu/libc.so.6+0x30412)
 #&#8203;8 0x0000562f4f9af3b0 llvm::CastInst::Create(llvm::Instruction::CastOps, llvm::Value*, llvm::Type*, llvm::Twine const&, llvm::Instruction*) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x215d3b0)
 #&#8203;9 0x0000562f501f8b45 llvm::VNCoercion::getStoreValueForLoad(llvm::Value*, unsigned int, llvm::Type*, llvm::Instruction*, llvm::DataLayout const&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x29a6b45)
#&#8203;10 0x0000562f4fe18570 llvm::gvn::AvailableValue::MaterializeAdjustedValue(llvm::LoadInst*, llvm::Instruction*, llvm::GVN&) const (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x25c6570)
#&#8203;11 0x0000562f4fe226a5 llvm::GVN::processLoad(llvm::LoadInst*) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x25d06a5)
#&#8203;12 0x0000562f4fe24862 llvm::GVN::processInstruction(llvm::Instruction*) (.part.818) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x25d2862)
#&#8203;13 0x0000562f4fe251b2 llvm::GVN::processBlock(llvm::BasicBlock*) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x25d31b2)
#&#8203;14 0x0000562f4fe25637 llvm::GVN::iterateOnFunction(llvm::Function&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x25d3637)
#&#8203;15 0x0000562f4fe258ef llvm::GVN::runImpl(llvm::Function&, llvm::AssumptionCache&, llvm::DominatorTree&, llvm::TargetLibraryInfo const&, llvm::AAResults&, llvm::MemoryDependenceResults*, llvm::LoopInfo*, llvm::OptimizationRemarkEmitter*) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x25d38ef)
#&#8203;16 0x0000562f4fe2613e llvm::gvn::GVNLegacyPass::runOnFunction(llvm::Function&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x25d413e)
#&#8203;17 0x0000562f4f9d01e9 llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x217e1e9)
#&#8203;18 0x0000562f4f9d0b99 llvm::FPPassManager::runOnModule(llvm::Module&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x217eb99)
#&#8203;19 0x0000562f4f9cf441 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x217d441)
#&#8203;20 0x0000562f4e15975f main (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x90775f)
#&#8203;21 0x00007fea880fbb97 __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344:0
#&#8203;22 0x0000562f4e1f0aea _start (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x99eaea)
Aborted (core dumped)

**Comment by nikic** [comment]
Doesn't reproduce anymore (both for the original and simplified reproducers).
