### ISSUE TITLE
clang interprets Annex K functions as C99

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43193]
|  |  |
| --- | --- |
| Bugzilla Link | [43848](https://llvm.org/bz43848) |
| Version | 8.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie,@DougGregor,@zygoloid |

## Extended Description 
I was expecting to see something along the lines of "Annex K functions not supported" or "__STDC_LIB_EXT1__ not defined" if memcmp_s was not declared, but clang seems to be ignoring the -std=c11 flag and interpreting this as C99 code instead.

// memcmp.c
#define __STDC_WANT_LIB_EXT1__ 1                                                                                                                                                                            
#include <string.h>

int main()
{
        char dst[10], src[10];
        memcmp_s(dst, 10, src, 10);
}

$ clang -std=c11 memcmp.c -o memcmp.exe
memcmp.c:7:2: warning: implicit declaration of function 'memcmp_s' is invalid in C99 [-Wimplicit-function-declaration]
        memcmp_s(dst, 10, src, 10);
        ^
1 warning generated.
/usr/bin/ld: /tmp/memcmp-b97369.o: in function `main':
memcmp.c:(.text+0x1c): undefined reference to `memcmp_s'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This is clang 8.0.0-3 on x86_64-pc-linux-gnu

**Comment by AaronBallman** [comment]
C2x K.2p2: "An implementation that defines `__STDC_LIB_EXT1__` shall conform to the specifications in this annex."

Clang does not predefine that macro and there's a pretty good chance that neither does your C Library implementation. Given that the Annex K functionality comes from the library and not the compiler, I do not think this is a bug with Clang.
