### ISSUE TITLE
Segfault in llvm::ProfileSummaryInfo::computeSummary

### ISSUE THREAD

**Issue by 2f0b9237-61bb-4b1e-bcb4-b0bb0e3ddf06** [llvm/llvm-project#43198]
|  |  |
| --- | --- |
| Bugzilla Link | [43853](https://llvm.org/bz43853) |
| Version | trunk |
| OS | Linux |

## Extended Description 
When running Mesa 19.3.0 (git commit 780c937a5ded1a4586ba4160020200eebe57b311) SWR software rasterizer with LLVM 1:10~svn375339-1~exp1 on Linux amd64 (znver1, AMD Threadripper 2950X):

user@debian:~/mesa-git/builddir/build-amd64-dbg$ GALLIUM_PRINT_OPTIONS=1 GALLIUM_DUMP_CPU=true LIBGL_ALWAYS_SOFTWARE=1 GALLIUM_DRIVER=swr LP_NATIVE_VECTOR_WIDTH=256 gdb --args glxgears 
GNU gdb (Debian 8.3.1-1) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from glxgears...
(No debugging symbols found in glxgears)
(gdb) r
Starting program: /usr/bin/glxgears 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
debug_get_bool_option: SWRAST_NO_PRESENT = FALSE
debug_get_option: GALLIUM_DRIVER = swr
debug_get_flags_option: GALLIVM_DEBUG = 0x0
debug_get_flags_option: GALLIVM_PERF = 0x0
debug_get_bool_option: GALLIUM_DUMP_CPU = TRUE
util_cpu_caps.nr_cpus = 32
util_cpu_caps.x86_cpu_type = 23
util_cpu_caps.cacheline = 64
util_cpu_caps.has_tsc = 1
util_cpu_caps.has_mmx = 1
util_cpu_caps.has_mmx2 = 1
util_cpu_caps.has_sse = 1
util_cpu_caps.has_sse2 = 1
util_cpu_caps.has_sse3 = 1
util_cpu_caps.has_ssse3 = 1
util_cpu_caps.has_sse4_1 = 1
util_cpu_caps.has_sse4_2 = 1
util_cpu_caps.has_avx = 1
util_cpu_caps.has_avx2 = 1
util_cpu_caps.has_f16c = 1
util_cpu_caps.has_popcnt = 1
util_cpu_caps.has_3dnow = 0
util_cpu_caps.has_3dnow_ext = 0
util_cpu_caps.has_xop = 0
util_cpu_caps.has_altivec = 0
util_cpu_caps.has_vsx = 0
util_cpu_caps.has_neon = 0
util_cpu_caps.has_daz = 1
util_cpu_caps.has_avx512f = 0
util_cpu_caps.has_avx512dq = 0
util_cpu_caps.has_avx512ifma = 0
util_cpu_caps.has_avx512pf = 0
util_cpu_caps.has_avx512er = 0
util_cpu_caps.has_avx512cd = 0
util_cpu_caps.has_avx512bw = 0
util_cpu_caps.has_avx512vl = 0
util_cpu_caps.has_avx512vbmi = 0
Breaking into debugger.

Program received signal SIGTRAP, Trace/breakpoint trap.
__GI_raise (sig=sig@entry=5) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) c
Continuing.
Continuing
debug_get_bool_option: LP_FORCE_SSE2 = FALSE
debug_get_num_option: LP_NATIVE_VECTOR_WIDTH = 256
debug_get_num_option: SWR_CLIENT_COPY_LIMIT = 8192
debug_get_num_option: SWR_MSAA_MAX_COUNT = 1
debug_get_bool_option: SWR_MSAA_FORCE_ENABLE = FALSE
&util_cpu_caps = 0x0x7ffff6840a20 ; util_cpu_caps.has_avx2 = 1
SWR detected AVX2 instruction support (using: libswrAVX2.so).
[New Thread 0x7fffed857700 (LWP 99967)]
[New Thread 0x7fffed056700 (LWP 99968)]
[New Thread 0x7fffec855700 (LWP 99969)]
[New Thread 0x7fffec054700 (LWP 99970)]
[New Thread 0x7fffeb853700 (LWP 99971)]
[New Thread 0x7fffeb052700 (LWP 99972)]
[New Thread 0x7fffea851700 (LWP 99973)]
debug_get_flags_option: ST_DEBUG = 0x0
debug_get_bool_option: MESA_MVP_DP4 = FALSE
debug_get_bool_option: PP_DEBUG = FALSE
debug_get_option: GALLIUM_HUD_SHARE = (null)
debug_get_option: GALLIUM_HUD = fps
debug_get_num_option: GALLIUM_HUD_TOGGLE_SIGNAL = 0
debug_get_bool_option: GALLIUM_HUD_VISIBLE = TRUE
debug_get_option: GALLIUM_REFCNT_LOG = (null)
debug_get_bool_option: TGSI_PRINT_SANITY = FALSE
vert shader  0x7ffff6f6e000
frag shader  0x7ffff6f6c000

Thread 1 "glxgears" received signal SIGSEGV, Segmentation fault.
computeSummary () at /build/llvm-toolchain-snapshot-HGLYs5/llvm-toolchain-snapshot-10~svn375339/lib/Analysis/ProfileSummaryInfo.cpp:86
86	/build/llvm-toolchain-snapshot-HGLYs5/llvm-toolchain-snapshot-10~svn375339/lib/Analysis/ProfileSummaryInfo.cpp: No such file or directory.
(gdb) bt
#&#8203;0  computeSummary () at /build/llvm-toolchain-snapshot-HGLYs5/llvm-toolchain-snapshot-10~svn375339/lib/Analysis/ProfileSummaryInfo.cpp:86
#&#8203;1  0x00007ffff23da594 in hasProfileSummary () at /build/llvm-toolchain-snapshot-HGLYs5/llvm-toolchain-snapshot-10~svn375339/include/llvm/Analysis/ProfileSummaryInfo.h:71
#&#8203;2  runOnFunction () at /build/llvm-toolchain-snapshot-HGLYs5/llvm-toolchain-snapshot-10~svn375339/lib/Transforms/InstCombine/InstructionCombining.cpp:3614
#&#8203;3  0x00007ffff1bf2346 in runOnFunction () at /build/llvm-toolchain-snapshot-HGLYs5/llvm-toolchain-snapshot-10~svn375339/lib/IR/LegacyPassManager.cpp:1648
#&#8203;4  0x00007ffff1bf1a4e in run () at /build/llvm-toolchain-snapshot-HGLYs5/llvm-toolchain-snapshot-10~svn375339/lib/IR/LegacyPassManager.cpp:1585
#&#8203;5  0x00007ffff1bf19e6 in run () at /build/llvm-toolchain-snapshot-HGLYs5/llvm-toolchain-snapshot-10~svn375339/lib/IR/LegacyPassManager.cpp:1510
#&#8203;6  0x00007ffff5aa8ca6 in FetchJit::Create (this=this@entry=0x7fffffffbc00, fetchState=...) at ../../src/gallium/drivers/swr/rasterizer/jitter/fetch_jit.cpp:304
#&#8203;7  0x00007ffff5aa8eee in JitCompileFetch (hJitMgr=0x5555555f3700, state=...) at ../../src/gallium/drivers/swr/rasterizer/jitter/fetch_jit.cpp:2323
#&#8203;8  0x00007ffff5a6de64 in swr_draw_vbo (pipe=0x555555634ca0, info=0x7fffffffcbf0) at ../../src/gallium/drivers/swr/swr_draw.cpp:129
#&#8203;9  0x00007ffff584e348 in u_vbuf_draw_vbo (mgr=0x555555724d00, info=0x7fffffffcbf0) at ../../src/gallium/auxiliary/util/u_vbuf.c:1184
#&#8203;10 0x00007ffff581d53b in cso_draw_vbo (cso=<optimized out>, info=info@entry=0x7fffffffcbf0) at ../../src/gallium/auxiliary/cso_cache/cso_context.c:1705
#&#8203;11 0x00007ffff5ca405f in st_draw_vbo (ctx=<optimized out>, prims=<optimized out>, nr_prims=<optimized out>, ib=0x0, index_bounds_valid=<optimized out>, min_index=<optimized out>, 
    max_index=<optimized out>, tfb_vertcount=0x0, stream=0, indirect=0x0) at ../../src/mesa/state_tracker/st_draw.c:268
#&#8203;12 0x00007ffff5bc1b69 in vbo_save_playback_vertex_list (ctx=0x5555556e66f0, data=0x5555555fdce0) at ../../src/mesa/vbo/vbo_save_draw.c:215
#&#8203;13 0x00007ffff5aed733 in ext_opcode_execute (node=0x5555555fdcdc, ctx=0x5555556e66f0) at ../../src/mesa/main/dlist.c:1126
#&#8203;14 execute_list (ctx=ctx@entry=0x5555556e66f0, list=list@entry=1) at ../../src/mesa/main/dlist.c:11830
#&#8203;15 0x00007ffff5b0d6a1 in _mesa_CallList (list=1) at ../../src/mesa/main/dlist.c:14267
#&#8203;16 0x00005555555571bc in ?? ()
#&#8203;17 0x0000555555556c88 in ?? ()
#&#8203;18 0x00007ffff77b8bbb in __libc_start_main (main=0x555555556410, argc=1, argv=0x7fffffffd8e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffd8d8) at ../csu/libc-start.c:308
#&#8203;19 0x0000555555556f0a in ?? ()

aka

0x00007ffff28ee727 in llvm::ProfileSummaryInfo::computeSummary() () from /lib/x86_64-linux-gnu/libLLVM-10.so.1
(gdb) bt
#&#8203;0  0x00007ffff28ee727 in llvm::ProfileSummaryInfo::computeSummary() () from /lib/x86_64-linux-gnu/libLLVM-10.so.1
#&#8203;1  0x00007ffff23da594 in llvm::InstructionCombiningPass::runOnFunction(llvm::Function&) () from /lib/x86_64-linux-gnu/libLLVM-10.so.1
#&#8203;2  0x00007ffff1bf2346 in llvm::FPPassManager::runOnFunction(llvm::Function&) () from /lib/x86_64-linux-gnu/libLLVM-10.so.1
#&#8203;3  0x00007ffff1bf1a4e in llvm::legacy::FunctionPassManagerImpl::run(llvm::Function&) () from /lib/x86_64-linux-gnu/libLLVM-10.so.1
#&#8203;4  0x00007ffff1bf19e6 in llvm::legacy::FunctionPassManager::run(llvm::Function&) () from /lib/x86_64-linux-gnu/libLLVM-10.so.1
#&#8203;5  0x00007ffff5aa8ca6 in FetchJit::Create (this=this@entry=0x7fffffffbc00, fetchState=...) at ../../src/gallium/drivers/swr/rasterizer/jitter/fetch_jit.cpp:304
#&#8203;6  0x00007ffff5aa8eee in JitCompileFetch (hJitMgr=0x5555555f3700, state=...) at ../../src/gallium/drivers/swr/rasterizer/jitter/fetch_jit.cpp:2323
#&#8203;7  0x00007ffff5a6de64 in swr_draw_vbo (pipe=0x555555634ca0, info=0x7fffffffcbf0) at ../../src/gallium/drivers/swr/swr_draw.cpp:129
#&#8203;8  0x00007ffff584e348 in u_vbuf_draw_vbo (mgr=0x555555724d00, info=0x7fffffffcbf0) at ../../src/gallium/auxiliary/util/u_vbuf.c:1184
#&#8203;9  0x00007ffff581d53b in cso_draw_vbo (cso=<optimized out>, info=info@entry=0x7fffffffcbf0) at ../../src/gallium/auxiliary/cso_cache/cso_context.c:1705
#&#8203;10 0x00007ffff5ca405f in st_draw_vbo (ctx=<optimized out>, prims=<optimized out>, nr_prims=<optimized out>, ib=0x0, index_bounds_valid=<optimized out>, min_index=<optimized out>, 
    max_index=<optimized out>, tfb_vertcount=0x0, stream=0, indirect=0x0) at ../../src/mesa/state_tracker/st_draw.c:268
#&#8203;11 0x00007ffff5bc1b69 in vbo_save_playback_vertex_list (ctx=0x5555556e66f0, data=0x5555555fdce0) at ../../src/mesa/vbo/vbo_save_draw.c:215
#&#8203;12 0x00007ffff5aed733 in ext_opcode_execute (node=0x5555555fdcdc, ctx=0x5555556e66f0) at ../../src/mesa/main/dlist.c:1126
#&#8203;13 execute_list (ctx=ctx@entry=0x5555556e66f0, list=list@entry=1) at ../../src/mesa/main/dlist.c:11830
#&#8203;14 0x00007ffff5b0d6a1 in _mesa_CallList (list=1) at ../../src/mesa/main/dlist.c:14267
#&#8203;15 0x00005555555571bc in ?? ()
#&#8203;16 0x0000555555556c88 in ?? ()
#&#8203;17 0x00007ffff77b8bbb in __libc_start_main (main=0x555555556410, argc=1, argv=0x7fffffffd8e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffd8d8) at ../csu/libc-start.c:308
#&#8203;18 0x0000555555556f0a in ?? ()

**Comment by Endilll** [comment]
Unfortunately, we can't do much without a reproducer.
Feel free to reopen if you have additional information.
