### ISSUE TITLE
leading c-style comments mangle preprocessor macro formatting (output does not compile)

### ISSUE THREAD

**Issue by 53cdf39f-a9d5-4dee-b7b7-e545fed0664c** [llvm/llvm-project#43206]
|  |  |
| --- | --- |
| Bugzilla Link | [43861](https://llvm.org/bz43861) |
| Version | 9.0 |
| OS | Windows NT |
| Attachments | [unformatted source](https://user-images.githubusercontent.com/92601697/143760005-3b687817-ec3d-4fa7-b645-381ce4130b3c.gz) |

## Extended Description 

The reformatted output fails to compile if a C-style comment exists prior to the '#' on a line that defines a preprocessor macro.

https://godbolt.org/z/Bg2D_P demonstrates this if you right-click the source window and choose "Format text".

```

/* A leading comment */ #define FOO (3)

int main()
{
    return FOO;    
}
```

becomes

```

/* A leading comment */ #define FOO(3)

    int main() {
  return FOO;
}
```

**Comment by mkurdej** [comment]
Revision URI: https://reviews.llvm.org/D118924
