### ISSUE TITLE
Automatic installation script fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43213]
|  |  |
| --- | --- |
| Bugzilla Link | [43868](https://llvm.org/bz43868) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Hello,
When I run the Automatic installation script as root on a WSL Ubuntu 18.04 I get the following error:
+ apt-get install -y clang-9 lldb-9 lld-9 clangd-9
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 lldb-9 : Depends: llvm-9-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

How could I fix that?

Thanks

**Comment by sylvestre** [comment]
it is fixed now
