### ISSUE TITLE
core on gsl Assertion `Loc.isValid()' failed

### ISSUE THREAD

**Issue by 9992af82-3d62-44cb-b29b-58bba76f794a** [llvm/llvm-project#43223]
|  |  |
| --- | --- |
| Bugzilla Link | [43878](https://llvm.org/bz43878) |
| Version | unspecified |
| OS | Linux |
| CC | @EugeneZelenko,@donhinton |

## Extended Description 
Internal failure on clang-tidy when using gsl 

GSL comes from  https://github.com/microsoft/GSL 
Commit   66809c6852a0250243db893ab5460bfdace063c4 

Running on centos 7.2 with custom build in docker environment

  XXX/all_3rdparty_NB/llvm/rhel72_64/bin/clang-tidy  --version
LLVM (http://llvm.org/):
  LLVM version 10.0.0svn
  DEBUG build with assertions.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: ivybridge
rhel72_64$

rhel72_64$ cat foo.cpp

#include <gsl/gsl>
//#include <type_traits>

rhel72_64$
XXX/all_3rdparty_NB/llvm/rhel72_64/bin/clang-tidy  foo.cpp  --   XXX/all_3rdparty_NB/llvm/rhel72_64/bin/clang++   -I../../../../../all_3rdparty_NB/gsl/GSL-66809c6852a0250243db893ab5460bfdace063c4/include    -std=c++17
clang-tidy: XXX/all_3rdparty_NB/llvm/llvm/tools/clang/tools/extra/clang-tidy/ClangTidyDiagnosticConsumer.cpp:162: clang::DiagnosticBuilder clang::tidy::ClangTidyContext::diag(llvm::StringRef, clang::SourceLocation, llvm::StringRef, clang::DiagnosticIDs::Level): Assertion `Loc.isValid()' failed.
 #&#8203;0 0x0000000000a4a468 llvm::sys::PrintStackTrace(llvm::raw_ostream&) XXX/all_3rdparty_NB/llvm/llvm/lib/Support/Unix/Signals.inc:544:22
 #&#8203;1 0x0000000000a4a4fb PrintStackTraceSignalHandler(void*) XXX/all_3rdparty_NB/llvm/llvm/lib/Support/Unix/Signals.inc:605:1
 #&#8203;2 0x0000000000a48635 llvm::sys::RunSignalHandlers() XXX/all_3rdparty_NB/llvm/llvm/lib/Support/Signals.cpp:68:20
 #&#8203;3 0x0000000000a49eb9 SignalHandler(int) XXX/all_3rdparty_NB/llvm/llvm/lib/Support/Unix/Signals.inc:391:1
 #&#8203;4 0x00007fb19d4be5f0 __restore_rt (/lib64/libpthread.so.0+0xf5f0)
 #&#8203;5 0x00007fb19c0ac337 raise (/lib64/libc.so.6+0x36337)
 #&#8203;6 0x00007fb19c0ada28 abort (/lib64/libc.so.6+0x37a28)
 #&#8203;7 0x00007fb19c0a5156 __assert_fail_base (/lib64/libc.so.6+0x2f156)
 #&#8203;8 0x00007fb19c0a5202 (/lib64/libc.so.6+0x2f202)
 #&#8203;9 0x000000000108dad6 clang::tidy::ClangTidyContext::diag(llvm::StringRef, clang::SourceLocation, llvm::StringRef, clang::DiagnosticIDs::Level) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/tools/extra/clang-tidy/ClangTidyDiagnosticConsumer.cpp:163:17
#&#8203;10 0x0000000001873dea clang::tidy::ClangTidyCheck::diag(clang::SourceLocation, llvm::StringRef, clang::DiagnosticIDs::Level) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/tools/extra/clang-tidy/ClangTidyCheck.cpp:23:54
#&#8203;11 0x00000000013d9da6 clang::tidy::modernize::UseNoexceptCheck::check(clang::ast_matchers::MatchFinder::MatchResult const&) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/tools/extra/clang-tidy/modernize/UseNoexceptCheck.cpp:107:38
#&#8203;12 0x0000000001873e26 clang::tidy::ClangTidyCheck::run(clang::ast_matchers::MatchFinder::MatchResult const&) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/tools/extra/clang-tidy/ClangTidyCheck.cpp:31:1
#&#8203;13 0x00000000031a942e clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::MatchVisitor::visitMatch(clang::ast_matchers::BoundNodes const&) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/ASTMatchers/ASTMatchFinder.cpp:750:34
#&#8203;14 0x0000000000f9516a clang::ast_matchers::internal::BoundNodesTreeBuilder::visitMatches(clang::ast_matchers::internal::BoundNodesTreeBuilder::Visitor*) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/ASTMatchers/ASTMatchersInternal.cpp:75:31
#&#8203;15 0x00000000031a8933 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::matchWithFilter(clang::ast_type_traits::DynTypedNode const&) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/ASTMatchers/ASTMatchFinder.cpp:580:57
#&#8203;16 0x00000000031a8a8c clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::matchDispatch(clang::Decl const*) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/ASTMatchers/ASTMatchFinder.cpp:602:72
#&#8203;17 0x00000000031add77 void clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::match<clang::Decl>(clang::Decl const&) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/ASTMatchers/ASTMatchFinder.cpp:507:3
#&#8203;18 0x00000000031a9c0d clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/ASTMatchers/ASTMatchFinder.cpp:919:60
#&#8203;19 0x0000000003205bb3 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDeclContextHelper(clang::DeclContext*) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/include/clang/AST/RecursiveASTVisitor.h:1390:7
#&#8203;20 0x00000000031c80ab clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseLinkageSpecDecl(clang::LinkageSpecDecl*) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/include/clang/AST/RecursiveASTVisitor.h:1475:1
#&#8203;21 0x00000000031ae9c0 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDecl(clang::Decl*) XXX/all_3rdparty_NB/llvm/rhel72_64_compile/tools/clang/include/clang/AST/DeclNodes.inc:89:1
#&#8203;22 0x00000000031a9c20 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/ASTMatchers/ASTMatchFinder.cpp:919:69
#&#8203;23 0x0000000003205bb3 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDeclContextHelper(clang::DeclContext*) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/include/clang/AST/RecursiveASTVisitor.h:1390:7
#&#8203;24 0x00000000031d04b7 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseTranslationUnitDecl(clang::TranslationUnitDecl*) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/include/clang/AST/RecursiveASTVisitor.h:1487:1
#&#8203;25 0x00000000031af6b3 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDecl(clang::Decl*) XXX/all_3rdparty_NB/llvm/rhel72_64_compile/tools/clang/include/clang/AST/DeclNodes.inc:577:1
#&#8203;26 0x00000000031a9c20 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/ASTMatchers/ASTMatchFinder.cpp:919:69
#&#8203;27 0x00000000031b12f8 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseAST(clang::ASTContext&) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/include/clang/AST/RecursiveASTVisitor.h:183:11
#&#8203;28 0x00000000031aa679 clang::ast_matchers::MatchFinder::matchAST(clang::ASTContext&) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/ASTMatchers/ASTMatchFinder.cpp:1096:33
#&#8203;29 0x00000000031a9ec7 clang::ast_matchers::internal::(anonymous namespace)::MatchASTConsumer::HandleTranslationUnit(clang::ASTContext&) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/ASTMatchers/ASTMatchFinder.cpp:989:3
#&#8203;30 0x00000000020992fd clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/Frontend/MultiplexConsumer.cpp:291:25
#&#8203;31 0x00000000022ac9d8 clang::ParseAST(clang::Sema&, bool, bool) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/Parse/ParseAST.cpp:178:14
#&#8203;32 0x0000000002066fe3 clang::ASTFrontendAction::ExecuteAction() XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:1042:11
#&#8203;33 0x000000000206695f clang::FrontendAction::Execute() XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:939:38
#&#8203;34 0x000000000200a72c clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:956:42
#&#8203;35 0x00000000010580d2 clang::tooling::FrontendActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/Tooling/Tooling.cpp:397:46
#&#8203;36 0x000000000107777a clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::string>, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, llvm::StringRef)::ActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/tools/extra/clang-tidy/ClangTidy.cpp:545:50
#&#8203;37 0x0000000001057f36 clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::shared_ptr<clang::CompilerInvocation>, std::shared_ptr<clang::PCHContainerOperations>) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/Tooling/Tooling.cpp:372:31
#&#8203;38 0x0000000001057d74 clang::tooling::ToolInvocation::run() XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/Tooling/Tooling.cpp:357:23
#&#8203;39 0x00000000010593d3 clang::tooling::ClangTool::run(clang::tooling::ToolAction*) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/lib/Tooling/Tooling.cpp:550:11
#&#8203;40 0x0000000001077af2 clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::string>, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, llvm::StringRef) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/tools/extra/clang-tidy/ClangTidy.cpp:567:28
#&#8203;41 0x0000000000419c09 clang::tidy::clangTidyMain(int, char const**) XXX/all_3rdparty_NB/llvm/llvm/tools/clang/tools/extra/clang-tidy/tool/ClangTidyMain.cpp:432:53
#&#8203;42 0x000000000041a0d3 main XXX/all_3rdparty_NB/llvm/llvm/tools/clang/tools/extra/clang-tidy/tool/ClangTidyMain.cpp:492:47
#&#8203;43 0x00007fb19c098505 __libc_start_main (/lib64/libc.so.6+0x22505)
#&#8203;44 0x0000000000418505 _start (/home/mpawlowsky/r18_1_0_dcr/nb20191023.9999/all_3rdparty_NB/llvm/rhel72_64/bin/clang-tidy+0x418505)
Aborted (core dumped)
rhel72_64$

**Comment by PiotrZSL** [comment]
No reproduction on LLVM 17 (main).
Most probably fixed already by 4c5818dd8cd9336136a80a02b262b501b23f6492.
