### ISSUE TITLE
slp-vectorizer produces invalid IR: PHI nodes not grouped at top of basic block!

### ISSUE THREAD

**Issue by 952e6d5a-d994-4724-a6d1-07613b2d95a8** [llvm/llvm-project#43221]
|  |  |
| --- | --- |
| Bugzilla Link | [43876](https://llvm.org/bz43876) |
| Version | trunk |
| OS | Linux |
| Attachments | [sp.S.x.bc](https://user-images.githubusercontent.com/92601252/143760010-118bcb83-a589-471a-8a59-7c7dcaf94f4f.gz) |
| CC | @RKSimon |

## Extended Description 

$clang -v
clang version 10.0.0 (https://github.com/llvm/llvm-project.git ec630194fe64e9e304487040e808d0696a4f1895)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$opt -mem2reg -loop-reduce -instcombine -loop-rotate -slp-vectorizer   sp.S.x.bc 
WARNING: You're attempting to print out a bitcode file.
This is inadvisable as it may cause display problems. If
you REALLY want to taste LLVM bitcode first-hand, you
can force output with the `-f' option.

PHI nodes not grouped at top of basic block!
  %610 = phi <2 x i32> [ %606, %for.body1712.lr.ph ], [ %640, %for.inc1851 ]
label %for.body1712
in function x_solve
LLVM ERROR: Broken function found, compilation aborted!

**Comment by fhahn** [comment]
This appears to be fixed on current `main`.
