### ISSUE TITLE
InstCombine incorrectly optimizes `select`s with conditionally undef values

### ISSUE THREAD

**Issue by gburgessiv** [llvm/llvm-project#43224]
|  |  |
| --- | --- |
| Bugzilla Link | [43879](https://llvm.org/bz43879) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie,@efriedma-quic,@gburgessiv,@nunoplopes,@rnk,@rotateright,@stephanemoore |

## Extended Description 
Found while trying to bootstrap clang-tidy.

The intent of the repro is to call @&#8203;bar() once and return false if `%B` is true. Otherwise, it should loop calling @&#8203;bar() forever. (The non-reduced code isn't an infloop, but the infloop doesn't appear to make a difference here)

```
[ub] ~/l/t/gbiv_repro [ 20ms ] ((6082a062…)) ~> git rev-parse HEAD
6082a062a76d0bc9c9c641f5600569bafdf4c338

[ub] ~/l/t/gbiv_repro [ 5ms ] ((6082a062…)) ~> cat repro.ll
declare void @bar()

define dso_local i1 @_Z3foob(i1 zeroext %B) local_unnamed_addr #0 {
entry:
  br label %loop

loop:
  %x = phi i1 [ undef, %entry ], [ %foo, %loop.end ]
  call void @bar()
  br label %loop.end

loop.end:
  %foo = select i1 %B, i1 false, i1 %x
  br i1 %B, label %return, label %loop

return:
  ret i1 %foo
}

[ub] ~/l/t/gbiv_repro [ 2ms ] ((6082a062…)) ~> ../build/release/bin/opt -instcombine < repro.ll -S
; ModuleID = '<stdin>'
source_filename = "<stdin>"

declare void @&#8203;bar()

define dso_local i1 @&#8203;_Z3foob(i1 zeroext %B) local_unnamed_addr {
entry:
  br label %loop

loop:                                             ; preds = %loop.end, %entry
  call void @&#8203;bar()
  br label %loop.end

loop.end:                                         ; preds = %loop
  br i1 %B, label %return, label %loop

return:                                           ; preds = %loop.end
  ret i1 undef
}
```

AIUI, select should block undef from entering the program if %B is true, so the `ret i1 undef` shouldn't be possible.

**Comment by nikic** [comment]
expandBinOp() has been changed to use `Q.getWithoutUndef()` mode, so this should be fixed now. https://llvm.godbolt.org/z/8xP1dqo4W https://llvm.godbolt.org/z/rhzGjqad9
