### ISSUE TITLE
clang-format AlwaysBreakConstructorInitializers

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43246]
|  |  |
| --- | --- |
| Bugzilla Link | [43901](https://llvm.org/bz43901) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mydeveloperday |

## Extended Description 
I was wondering if it would be possible to add an option to always break constructor initializers. For example:

AlwaysBreakConstructorInitializers (booL)

if true, always break the constructor initializer list, regardless if they can all fit on a single line (the style is dictated by BreakConstructorInitializers:

true:
Constructor() :
    initializer1(),
    initializer2()

false:
Constructor() : initializer1(), initializer2()

IMO... clang-format works too hard to get everything to fit on a single line, but this specific instance really makes the code hard to read. It also makes it had to add // NOLINT tags as clang-format will move the comment around. For example:

Constructor() :        // NOLINT
    initializer1(),
    initializer2()

becomes

Constructor() :        
    // NOLINT
    initializer1(),
    initializer2()

**Comment by owenca** [comment]
https://reviews.llvm.org/D129057

**Comment by owenca** [comment]
> I was wondering if it would be possible to add an option to always break constructor initializers.

An equivalent option `PackConstructorInitializers: Never` was added in 8a780a2.
