### ISSUE TITLE
Mishandled attributes on typedef decl-specifier

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#43284]
|  |  |
| --- | --- |
| Bugzilla Link | [43939](https://llvm.org/bz43939) |
| Version | unspecified |
| OS | Windows NT |
| CC | @DougGregor,@zygoloid |

## Extended Description 
The following code fails to compile, though it should compile as per [dcl.spec]p1:
```cpp
typedef [[frobble]] int i_t;
```
The following code *does* compile, but produces *two* unknown attribute warnings instead of one:
```cpp
struct S {};
typedef [[frobble]] S s_t;
```

**Comment by Endilll** [comment]
CC @AaronBallman one of your old issues

**Comment by AaronBallman** [comment]
Issue no longer reproduces, and so closing as works for me.
