### ISSUE TITLE
Clang crashes when incrementing a vector by a float scalar

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43314]
|  |  |
| --- | --- |
| Bugzilla Link | [43969](https://llvm.org/bz43969) |
| Version | trunk |
| OS | All |
| Attachments | [Same f.c source as exists in the description](https://user-images.githubusercontent.com/60944935/143760043-6a129171-85fb-4c72-85c9-d02d3b122704.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@RKSimon,@zygoloid,@rotateright |

## Extended Description 

#include "float.h"

typedef short v2i16 __attribute__((vector_size(4)));
typedef int v2i32 __attribute__((vector_size(8)));
typedef long long v2i64 __attribute__((vector_size(16)));
typedef short v4i16 __attribute__((vector_size(8)));
typedef int v4i32 __attribute__((vector_size(16)));
typedef char v8i8 __attribute__((vector_size(8)));
typedef short v8i16 __attribute__((vector_size(16)));
typedef char v16i8 __attribute__((vector_size(16)));

void func(TYPE a) {
//crash
a+=1.0f;
a-=1.0f;

//OK
a+=1;
a-=1;
}

//Executing clang -DTYPE=v2i32 f.c
// clang-8: /slowfs/us01dwt2p448/hartman/hartman_1/work/llvm-project/llvm/lib/IR/Instructions.cpp:2168: static llvm::BinaryOperator* llvm::BinaryOperator::Create(llvm::Instruction::BinaryOps, llvm::Value*, llvm::Value*, const llvm::Twine&, llvm::Instruction*): Assertion `S1->getType() == S2->getType() && "Cannot create binary operator with two operands of differing type!"' failed.

**Comment by AaronBallman** [comment]
I can reproduce the crash in Clang 8 and 9, but it appears to have been fixed in Clang 10 onwards. Closing as WORKSFORME, but if the issue still persists, please reopen the bug with additional information on how to reproduce.
