### ISSUE TITLE
modernize-use-trailing-return-type: add option to ignore functions reached via macros (from system headers only?)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43325]
|  |  |
| --- | --- |
| Bugzilla Link | [43980](https://llvm.org/bz43980) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @bernhardmgruber |

## Extended Description 
I have the situation where a third-party mock library doesn't use trailing return types in internal functions used to implement a macro (https://github.com/rollbear/trompeloeil/issues/140#issuecomment-552924204).

I don't know how much context clang-tidy gives to check authors. But modernize-use-trailing-return-type is a purely stylistic check, it makes no sense for my code to get a warning because it's using a function without trailing return type when such a function is from a system header and completely hidden behind a macro. It's never seen, I have no style to worry about.

**Comment by PiotrZSL** [comment]
Fixed by 670de10f9deaa83f4d1db6e793c74cbfd18c65c1
