### ISSUE TITLE
Segfault during parsing of invalid template code

### ISSUE THREAD

**Issue by lenerd** [llvm/llvm-project#43340]
|  |  |
| --- | --- |
| Bugzilla Link | [43995](https://llvm.org/bz43995) |
| Version | trunk |
| OS | Linux |
| Attachments | [stack trace, preprocessed source, and run script](https://user-images.githubusercontent.com/95090675/143760055-ed54f3c5-249e-49b4-a72f-9ed9c5f1585b.gz) |
| CC | @lenerd,@zygoloid |

## Extended Description 

Hi there,

while I was trying to minimize a reproducer for a different bug, I ended up with a piece of code that lets clang's parser segfault.

Version: clang version 10.0.0 (trunk) (llvm/trunk 375507)

See attachment for stack trace, preprocessed source, and run script.

Best

Lennart

**Comment by Endilll** [comment]
Fixed in Clang 10: https://godbolt.org/z/9edqxTqEj
