### ISSUE TITLE
Ashr does not alter sign bit - could look past ashr, backend fails to undo transform

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#43370]
|  |  |
| --- | --- |
| Bugzilla Link | [44025](https://llvm.org/bz44025) |
| Version | trunk |
| OS | Linux |
| CC | @topperc,@RKSimon,@rotateright |

## Extended Description 
I'm not sure how relevant this is, but i noticed this while looking at some code.
We could have something like:
```
#include <algorithm>
struct S {
    int a, b;
};
unsigned long zz(S s) {
    return std::abs(static_cast<signed long>(s.a)); // or s.b
}
```
Currently it ends as 
```
define dso_local i64 @_Z2zz1S(i64 %0) local_unnamed_addr #0 {
  %2 = shl i64 %0, 32
  %3 = ashr exact i64 %2, 32
  %4 = sub nsw i64 0, %3
  %5 = icmp slt i64 %3, 0
  %6 = select i1 %5, i64 %4, i64 %3
  ret i64 %6
}
```
```
        movsxd  rcx, edi
        mov     rax, rcx
        neg     rax
        cmovl   rax, rcx
```
But we are checking sign bit of %3, which is ashr, and it preserves sign bit.
We could look past it: https://rise4fun.com/Alive/iANsl

But that exposes a weakness in backend part - it doesn't know that it could
undo such transform, and not perform the test:
```
        movsxd  rcx, edi
        shl     rdi, 32
        mov     rax, rcx
        neg     rax
        test    rdi, rdi
        cmovns  rax, rcx
```
https://godbolt.org/z/Hr4ceT

**Comment by RKSimon** [comment]
Current IR:
```
define i64 @zz(i64 %s.coerce) {
entry:
  %sext = shl i64 %s.coerce, 32
  %conv = ashr exact i64 %sext, 32
  %0 = tail call i64 @llvm.abs.i64(i64 %conv, i1 true)
  ret i64 %0
}
declare i64 @llvm.abs.i64(i64, i1 immarg)
```
Current Codegen:
```
zz(S):                                # @zz(S)
        movslq  %edi, %rcx
        movq    %rcx, %rax
        negq    %rax
        cmovsq  %rcx, %rax
        retq
```

**Comment by rotateright** [comment]
We could narrow the abs in IR, but it might not be a win for codegen, so some backend work is likely needed first:
https://alive2.llvm.org/ce/z/4-ni3W

**Comment by RKSimon** [comment]
OK, we can probably do this as a generic DAG combine with isTruncateFree/isTypeDesirableForOp/isZExtFree checks.

**Comment by RKSimon** [comment]
Candidate Patch: https://reviews.llvm.org/D136559
