### ISSUE TITLE
Pre-built binaries for ubuntu 19.04 link against a too-recent libz3

### ISSUE THREAD

**Issue by anisse** [llvm/llvm-project#43397]
|  |  |
| --- | --- |
| Bugzilla Link | [44052](https://llvm.org/bz44052) |
| Version | unspecified |
| OS | Linux |
| CC | @sylvestre |

## Extended Description 
Pre-built LLVM 9.0.0 binaries for "Ubuntu 19.04" link against a too recent libz3 for Ubuntu 19.04:

http://releases.llvm.org/download.html

clang+llvm-9.0.0-x86_64-pc-linux-gnu $ ./clang
./clang: error while loading shared libraries: libz3.so.4.8: cannot open shared object file: No such file or directory
clang+llvm-9.0.0-x86_64-pc-linux-gnu $ ./clangd
./clangd: error while loading shared libraries: libz3.so.4.8: cannot open shared object file: No such file or directory

libz3 4.8 needs Ubuntu 19.10:
https://packages.ubuntu.com/search?keywords=libz3-4

The good news is that the pre-built package for Ubuntu 18.04 does work on Ubuntu 19.04.

I initially considered opening a bug against the website to just rename Ubuntu 19.04 to Ubuntu 19.10 on the download page, but I'll leave that to your judgement.

**Comment by arsenm** [comment]
Old packaging issue
