### ISSUE TITLE
Incorrect stepping through inlined function on AArch64 Ubuntu, FreeBSD

### ISSUE THREAD

**Issue by rovka** [llvm/llvm-project#43402]
|  |  |
| --- | --- |
| Bugzilla Link | [44057](https://llvm.org/bz44057) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Log of stepping from caller_trivial_1 into caller_trivial_2](https://user-images.githubusercontent.com/9715473/143760086-5c7639d7-fa85-46bb-8127-948084b41934.gz), [Some dumps from lldb](https://user-images.githubusercontent.com/9715473/143760087-a1a258ca-e3a2-428c-9b5a-96ba6ae4c27d.gz) |
| CC | @JDevlieghere,@jmorse |

## Extended Description 

TestInlineStepping.py fails on AArch64:
AssertionError: Step into stopped at wrong place: expected: /home/buildslave/buildslave/lldb-cmake-aarch64/llvm-project/lldb/packages/Python/lldbsuite/test/functionalities/inline-stepping/calling.cpp:78 got: /home/buildslave/buildslave/lldb-cmake-aarch64/llvm-project/lldb/packages/Python/lldbsuite/test/functionalities/inline-stepping/calling.cpp:98:18.

**Comment by jasonmolenda** [comment]
I believe I fixed this via 
```
commit df552edb08c4a1f7600b97444f6315a63c998c59
Author: Jason Molenda <jason@molenda.com>
Date:   Wed May 4 14:43:42 2022 -0700

    Update the CFA to use $sp when $fp is restored on arm64
```
https://reviews.llvm.org/D124492

**Comment by DavidSpickett** [comment]
The mentioned tests are running on the AArch64 Linux bot right now, so I think Jason was right he did fix this.
