### ISSUE TITLE
Autolink PR in Commit Messages to Bugzilla URL

### ISSUE THREAD

**Issue by f1376df8-34bc-4756-9be6-f8bc6a69b887** [llvm/llvm-project#43408]
|  |  |
| --- | --- |
| Bugzilla Link | [44063](https://llvm.org/bz44063) |
| Version | unspecified |
| OS | All |
| Blocks | llvm/llvm-project#38741  |
| CC | @dwblaikie,@rnk |

## Extended Description 
We need to configure github to link to our external bug tracker. See 

https://help.github.com/en/github/administering-a-repository/configuring-autolinks-to-reference-external-resources

For instructions. After this commits like: 
https://github.com/llvm/llvm-project/commit/8723b95cefa4
Should link to:
llvm/llvm-project#42930 

We should use both "PR" and "PR#" as the reference prefix.

**Comment by asl** [comment]
We moved to github, so "#1234" will be recognized
