### ISSUE TITLE
llvm build fail on mac os 10.11.6

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43420]
|  |  |
| --- | --- |
| Bugzilla Link | [44075](https://llvm.org/bz44075) |
| Version | 9.0 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @JDevlieghere |

## Extended Description 
i cannot install llvm 9.0.0 on mac os 10.11.6:

/tmp/llvm-20191120-51054-19joaqd/llvm-9.0.0.src/tools/lldb/source/Plugins/ExpressionParser/Clang/ClangHost.cpp:112:17: error: no matching function for call to 'next'
  auto parent = std::next(rev_it);
                ^~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:521:25: note: candidate template ignored: disabled by 'enable_if' [with _ForwardIter = llvm::sys::path::reverse_iterator]
     typename enable_if<__is_forward_iterator<_ForwardIter>::value>::type* = 0)
                        ^
1 error generated.

**Comment by arsenm** [comment]
Old build issue
