### ISSUE TITLE
Applying modernize-use-trailing-return-type leads to compile error

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43551]
|  |  |
| --- | --- |
| Bugzilla Link | [44206](https://llvm.org/bz44206) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Code before transformation](https://user-images.githubusercontent.com/60944935/143760126-32bfb3f3-d0a8-44ef-88ee-3d78d3a94d41.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @bernhardmgruber |

## Extended Description 

Short version:
Applying the transformation "modernize-use-trailing-return-type" changes
ostream& operator<<(ostream& ostream, int i);
to
auto operator<<(ostream& ostream, int i) -> ostream&;

The latter does not compile because ostream refers to the parameter instead of std::ostream.

Details:
Example code is attached and can be found at https://godbolt.org/z/yTzKth as well.

clang++ modernizeTrailingReturnType.cpp
(compiles fine)

clang-tidy --fix --checks="modernize-use-trailing-return-type" modernizeTrailingReturnType.cpp

clang++ modernizeTrailingReturnType.cpp
modernizeTrailingReturnType.cpp:5:45: error: unknown type name 'ostream'
auto operator<<(ostream& ostream, int i) -> ostream&;
                                            ^
1 error generated.

clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 9.0.0
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: znver1

clang version 9.0.0-2 (tags/RELEASE_900/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by carlosgalvezp** [comment]
Fix merged, closing the issue.
