### ISSUE TITLE
Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43569]
|  |  |
| --- | --- |
| Bugzilla Link | [44224](https://llvm.org/bz44224) |
| Version | trunk |
| OS | Linux |
| Attachments | [Run script](https://user-images.githubusercontent.com/60944935/143760134-3bc7383a-e3af-4a05-92bf-c9502a110f20.gz), [Compressed C code](https://user-images.githubusercontent.com/60944935/143760135-6bd72b5e-9a0d-458c-bf75-291d1067433a.gz), [Run script output](https://user-images.githubusercontent.com/60944935/143760136-e5167a4c-a23b-4bf2-9408-7a195ca550d6.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Internal error compiling GlusterFS:

clang-10: /home/antipov/llvm/10.0.0/source/llvm/include/llvm/Support/Casting.h:264: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::DbgVariableIntrinsic; Y = llvm::DbgInfoIntrinsic; typename llvm::cast_retty<X, Y*>::ret_type = llvm::DbgVariableIntrinsic*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.

**Comment by Endilll** [comment]
Can't reproduce using Clang 8 through 10 with assertions enabled.
