### ISSUE TITLE
clang-format does not transfer brace to the new line for union, if flag Allman is set

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43565]
|  |  |
| --- | --- |
| Bugzilla Link | [44220](https://llvm.org/bz44220) |
| Version | 9.0 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Hi. If I set flag BreakBeforeBraces: Allman, clang-format does not transfer brace to the new line for union. Also if I use BasedOnStyle: Mozilla without anything else, it works correctly for union.
clang-format version 9.0.0 (tags/RELEASE_900/final)

$ echo "union U { int a; int b; }" | clang-format -style="{BreakBeforeBraces: Allman}"
```
union U {
  int a;
  int b;
}
```
$ echo "union U { int a; int b; }" | clang-format -style="{BasedOnStyle: Mozilla}"
```
union U
{
  int a;
  int b;
}
```

seems the same as:
llvm/llvm-project#41500

**Comment by mydeveloperday** [comment]
Some time between v8 and v12 this got fixed,

$ echo "union U { int a; int b; }" | clang-format-12.exe -style="{BreakBeforeBraces: Allman}"
```
union U
{
  int a;
  int b;
}
```

I'm closing this issue, if you still see problems feel free to reopen it.
