### ISSUE TITLE
cleanupAroundReplacements should insert #include directives after #pragma once

### ISSUE THREAD

**Issue by 4ea744ab-442a-4d16-bc53-71fab314a049** [llvm/llvm-project#43582]
|  |  |
| --- | --- |
| Bugzilla Link | [44237](https://llvm.org/bz44237) |
| Version | 8.0 |
| OS | Linux |

## Extended Description 
Our tool uses clang::format::cleanupAroundReplacements() to insert #include directives to generated replacements. I can see the following inconsistent logic: if we try insert #include directives to a header file with a header guard (#ifndef #define), the directive will be correctly inserted after the guard. However this logic doesn't apply to #pragma once. The #include directives will be inserted before the #pragma. This looks wrong for us.

#pragma once should be treated as a header guard in this usecase.

**Comment by mydeveloperday** [comment]
I am closing this issue due to the lack of a reproducible test case

Feel free to reopen this issue if you add one.
