### ISSUE TITLE
[PowerPC] Compile error when including x86 vector intrinsics compatibility headers in C++

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43586]
|  |  |
| --- | --- |
| Bugzilla Link | [44241](https://llvm.org/bz44241) |
| Version | trunk |
| OS | Linux |
| Attachments | [Patch to fix typedefs](https://user-images.githubusercontent.com/60944935/143760157-a888db9a-35f2-437d-83b1-b223ea970c0d.gz), [Patch to add an overload set](https://user-images.githubusercontent.com/60944935/143760158-e4a4642c-94bc-47bf-9b8d-d7959d033691.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @topperc,@ecnelises,@nemanjai,@zygoloid |

## Extended Description 

On ppc64le, this can be reproduced with:

    $ echo -e "#include <xmmintrin.h>\nint main() {}" > test1.cpp
    $ clang++ test.cpp -DNO_WARN_X86_INTRINSICS

And results in the following error:

    /home/colin/devel/llvm-builds/master-clang-assert/lib/clang/10.0.0/include/ppc_wrappers/xmmintrin.h:978:42: error: controlling expression type '__v4sf' (vector of 4 'float' values) not compatible with any generic association type
      result = (__vector unsigned long long) vec_cts (rounded, 0);
                                             ^~~~~~~~~~~~~~~~~~~~
    /home/colin/devel/llvm-builds/master-clang-assert/lib/clang/10.0.0/include/altivec.h:2914:12: note: expanded from macro 'vec_cts'
      _Generic((__a), vector float                                                 \
               ^~~~~
    [...]

This also affects Clang 9.

The issue occurs because the `*mmintrin.h` PPC compatibility headers define typedefs to map the Intel vector types to the AltiVec types. The typedefs use the `__vector_size__` type attribute instead of the `__vector` keyword.

`altivec.h` uses C11 generics for  `vec_ctf`, `vec_cts`, `vec_ctu`, `vec_shasigma_be`, and `vec_test_data_class`. Per the docs:

    In C, type compatibility is decided according to the rules given in
    the appropriate standard, but in C++, which lacks the type
    compatibility rules used in C, types are considered compatible only
    if they are equivalent.

Use of these functions in C++ programs with the `*mmintrin.h` typedef results in the same compiler error. Note that the `vec_ct*` will not work with `__vector float` until bug #&#8203;44239 is resolved.

See attached for a patch that changes the typedefs to use the `__vector` keyword.  Not sure if this is the best approach, since this fixes the issue for the compatibility headers but not for user specified typedefs using `__vector_size__`.

Another option I worked up would be to create overload sets for C++, as in the second attachment.

But let me know if you would like me to work this up further or if there is a better way.

**Comment by ecnelises** [comment]
I believe this was fixed after c0b3071833a80121a5a7ca9ea54fd59a59806acc.
