### ISSUE TITLE
C99 inline + extern decl merging problems

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#4361]
|  |  |
| --- | --- |
| Bugzilla Link | [3989](https://llvm.org/bz3989) |
| Version | unspecified |
| OS | All |
| CC | @davidchisnall,@DougGregor,@EdSchouten,@ismail |

## Extended Description 
Codegen should emit a strong definition for this function in c99 mode because extern gets merged onto it:

inline int toto(void)
{
}

extern int toto(void);

**Comment by arsenm** [comment]
> This is still not fixed as far as I can tell: $ clang -emit-llvm -S -x c - -o - extern void chrt();
> 
> inline void pes() { chrt(); }
> 
> void vlk() { pes(); } ^D ; ModuleID = '-' target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64-S128" target triple = "x86_64-unknown-linux-gnu"
> 
> define void @​vlk() nounwind uwtable { entry: call void (...)* @​pes() ret void }
> 
> declare void @​pes(...) ============== 8< ============== 8< ==============
> 
> WTF, a call of pes which is only declared?

Yes, this is correct. It's expected there's an extern definition somewhere else. With -O0 the inline definition is not emitted. With optimizations enabled an available_externally definition is emitted
