### ISSUE TITLE
Parser crash

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43637]
|  |  |
| --- | --- |
| Bugzilla Link | [44292](https://llvm.org/bz44292) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@kamleshbhalui,@zygoloid |

## Extended Description 
This fragment of a program

    // RUN: %clang_cc1 -triple powerpc64le-unknown-linux-gnu -disable-free -main-file-name OutputSections.cpp -fmath-errno -masm-verbose -U NDEBUG -pedantic -fdeprecated-macro -ferror-limit 19 -fmessage-length 0 -fvisibility-inlines-hidden -fno-signed-char -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -o - -emit-llvm -O0 -Wimplicit-int  %s
    template <typename> class a;
    b() {          a< char >::append(

is, of course, invalid, but triggers after diagnostic reporting:

    clang: /cheri/source/llvm-project/clang/lib/Parse/ParseExprCXX.cpp:585: clang::ExprResult clang::Parser::tryParseCXXIdExpression(clang::CXXScopeSpec &, bool, clang::Token &): Assertion `SS.isEmpty() && "undeclared non-type annotation should be unqualified"' failed.

**Comment by Quuxplusone** [comment]
Doesn't reproduce for any of the Clang releases on Godbolt, either, AFAICT. Feel free to reopen if there's more information.
