### ISSUE TITLE
[JumpThreading]  wrong-code

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#43646]
|  |  |
| --- | --- |
| Bugzilla Link | [44301](https://llvm.org/bz44301) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced testcase](https://user-images.githubusercontent.com/55128014/143760178-ca4a9e02-fe61-4af6-9575-571b2edde672.gz) |
| CC | @JonPsson,@yuanfang-chen |

## Extended Description 

gcc -O0 -march=arch13 tc_wrong_jumpthread.i -o a.out -w; ./a.out
checksum = FFFFFFFF

clang -O3 -march=arch13 tc_wrong_jumpthread.i -o a.out -w; ./a.out
checksum = FFFFFFFF

clang -O3 -march=arch13 tc_wrong_jumpthread.i -o a.out -w -mllvm -jump-threading-across-loop-headers; ./a.out
checksum = 0

**Comment by fhahn** [comment]
I am unable to reproduce this on current `main`, so the issue has likely been fixed: https://godbolt.org/z/GssrYqex8

@JonPsson if it still reproduces on your end, please re-open the issue with additional information.
