### ISSUE TITLE
Unsupported value of LLVM_USE_SANITIZER: Address;Undefined

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#43644]
|  |  |
| --- | --- |
| Bugzilla Link | [44299](https://llvm.org/bz44299) |
| Version | unspecified |
| OS | Linux |
| CC | @mclow |

## Extended Description 
https://llvm.org/docs/CMake.html state "Possible values are Address, Memory, MemoryWithOrigins, Undefined, Thread, and Address;Undefined."

libcxx refuses to allow "Address;Undefined" as an option.

CMake Warning at /home/david/llvm-concepts/libcxx/CMakeLists.txt:696 (message):
  Unsupported value of LLVM_USE_SANITIZER: Address;Undefined
Call Stack (most recent call first):
  /home/david/llvm-concepts/libcxx/CMakeLists.txt:710 (get_sanitizer_flags)

This combination should be allowed.

**Comment by xgupta** [comment]
Seems this is supported by commit - https://github.com/llvm/llvm-project/commit/54176d1766f25bc03ddb1a8932a380f6543d5150.

I haven't checked by myself. Please reopen if it is not fixed.
