### ISSUE TITLE
Ubuntu repository for 16.04: Hash Sum mismatch for i386

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43657]
|  |  |
| --- | --- |
| Bugzilla Link | [44312](https://llvm.org/bz44312) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @sylvestre |

## Extended Description 
Hi,

it seems to me like the Ubuntu repo for i386 is broken.

I followed the instructions for getting the latest clang found at https://apt.llvm.org/ . However, when I do "apt update" I get an
error:

E: Failed to fetch http://apt.llvm.org/xenial/dists/llvm-toolchain-xenial/main/binary-i386/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

This only happens on multiarch systems (i e where "dpkg --print-foreign-architectures" prints "i386"); systems that are amd64 only works fine.

This is very similar to llvm/llvm-project#36007  and
should perhaps be part of that?

Regards

Mårten

**Comment by MarcoFalke** [comment]
Is this still an issue? i386 on Ubuntu with apt.llvm.org isn't supported anyway anymore
