### ISSUE TITLE
clang-format incorrectly formats C code with identifiers that match C++ class access keywords

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43678]
|  |  |
| --- | --- |
| Bugzilla Link | [44333](https://llvm.org/bz44333) |
| Version | unspecified |
| OS | All |
| Attachments | [Source C file for a bug demonstration](https://user-images.githubusercontent.com/60944935/143760185-f4a067f8-22d3-4c4d-82fb-0ca52bbde4d5.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Checked with the last llvm-project master branch, commit f31fa4f8981231ad2d32dc51979c96ec85657fe2

In C code "public", "private" and "protected" are valid identifiers but they are formatted incorrectly, like c++ class access levels keywords:

$ clang-format -verbose -i -style=llvm main.c
Formatting main.c
$ cat main.c 
```
#include <stdio.h>
#include <string.h>

struct type {
  const char *str;
  size_t size;
};

void function(struct type *public) {
public
  ->str = "string";
public
  ->size = strlen(public->str);
}
```

```
int main() {
  struct type private;

private
  .str = "text";
private
  .size = strlen(private.str);

  function(&private);

  return 0;
}
```

The problems are:
- Incorrect indentation
- Redundant new line after such words

**Comment by sean-mcmanus** [comment]
This issue also seems like it's a duplicate of https://github.com/llvm/llvm-project/issues/25697 .

**Comment by sean-mcmanus** [comment]
I'm seeing this fixed with clang-format 14. I'll file a new bug on the other case I mentioned.

**Comment by kleisauke** [comment]
For reference, this was fixed with commit https://github.com/llvm/llvm-project/commit/d1aed486efc6d35a81ca4acbabb4203c4b91cda9.
