### ISSUE TITLE
clang: error: unable to execute command: Floating point exception (core dumped)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43695]
|  |  |
| --- | --- |
| Bugzilla Link | [44350](https://llvm.org/bz44350) |
| Version | 6.0 |
| OS | Linux |
| Attachments | [Input source file](https://user-images.githubusercontent.com/60944935/143760200-2b0c5f55-f309-4d6b-8825-8cd2ae06c513.gz), [Run script](https://user-images.githubusercontent.com/60944935/143760201-dfe8daa9-6b7b-4bea-aa45-f5c882cf275e.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 
FAILED: /usr/bin/clang  -DDISPATCH_USE_DTRACE=0 -DHAVE_CONFIG_H -D_GNU_SOURCE -D_GNU_SOURCE=1 -D__EXTENSIONS__ -isystem lib/dispatch/src/BlocksRuntime -Ilib/dispatch/build -Ilib/dispatch -Ilib/dispatch/src -Ilib/dispatch/build/src -Ilib/dispatch/private -Werror=unused-command-line-argument -fcolor-diagnostics -Wno-unused-function -Wno-missing-braces -Wno-unused-variable -Wno-return-type -Wno-deprecated -Wno-deprecated-declarations -g -funsigned-char -fvisibility=hidden  -fsanitize=undefined,alignment,array-bounds,bool,bounds,builtin,enum,float-divide-by-zero,function,integer-divide-by-zero,leak,null,nonnull-attribute,object-size,pointer-overflow,return,returns-nonnull-attribute,shift,shift-base,shift-exponent,signed-integer-overflow,unsigned-integer-overflow,vla-bound,vptr -fno-omit-frame-pointer -fno-optimize-sibling-calls -fPIC -O1 -fPIC -fvisibility=hidden   -Werror -Wall -Wextra -Warray-bounds-pointer-arithmetic -Wassign-enum -Watomic-properties -Wcomma -Wconditional-uninitialized -Wconversion -Wcovered-switch-default -Wdate-time -Wdeprecated -Wdocumentation -Wdouble-promotion -Wduplicate-enum -Wexpansion-to-defined -Wfloat-equal -Widiomatic-parentheses -Winfinite-recursion -Wmissing-prototypes -Wnewline-eof -Wnullable-to-nonnull-conversion -Wobjc-interface-ivars -Wover-aligned -Wpacked -Wpointer-arith -Wselector -Wshadow -Wshorten-64-to-32 -Wsign-conversion -Wstatic-in-inline -Wsuper-class-method-mismatch -Wswitch -Wunguarded-availability -Wunreachable-code -Wunused -Wno-unknown-warning-option -Wno-trigraphs -Wno-four-char-constants -Wno-disabled-macro-expansion -Wno-pedantic -Wno-bad-function-cast -Wno-c++-compat -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-cast-align -Wno-cast-qual -Wno-documentation-unknown-command -Wno-format-nonliteral -Wno-missing-variable-declarations -Wno-old-style-cast -Wno-padded -Wno-reserved-id-macro -Wno-shift-sign-overflow -Wno-undef -Wno-unreachable-code-aggressive -Wno-unused-macros -Wno-used-but-marked-unused -Wno-vla -Wno-error=assign-enum -fno-exceptions -fblocks -momit-leaf-frame-pointer -pthread -std=gnu11 -MMD -MT lib/dispatch/build/src/CMakeFiles/dispatch.dir/init.c.o -MF lib/dispatch/build/src/CMakeFiles/dispatch.dir/init.c.o.d -o lib/dispatch/build/src/CMakeFiles/dispatch.dir/init.c.o   -c lib/dispatch/src/init.c
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x2a)[0x7f58a80a62ea]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZN4llvm3sys17RunSignalHandlersEv+0x3e)[0x7f58a80a44ae]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(+0x8635fc)[0x7f58a80a45fc]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f58ab294390]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZNK4llvm12SelectionDAG16computeKnownBitsENS_7SDValueERNS_9KnownBitsERKNS_5APIntEj+0x3e57)[0x7f58a863deb7]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZNK4llvm12SelectionDAG16computeKnownBitsENS_7SDValueERNS_9KnownBitsERKNS_5APIntEj+0xc8f)[0x7f58a863acef]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZNK4llvm12SelectionDAG16computeKnownBitsENS_7SDValueERNS_9KnownBitsERKNS_5APIntEj+0x17d3)[0x7f58a863b833]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZNK4llvm12SelectionDAG16computeKnownBitsENS_7SDValueERNS_9KnownBitsEj+0x81)[0x7f58a863ebf1]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZNK4llvm12SelectionDAG17MaskedValueIsZeroENS_7SDValueERKNS_5APIntEj+0x42)[0x7f58a863ed02]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(+0xcdf193)[0x7f58a8520193]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(+0xcee322)[0x7f58a852f322]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(+0xcefbaf)[0x7f58a8530baf]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZN4llvm12SelectionDAG7CombineENS_12CombineLevelEPNS_9AAResultsENS_10CodeGenOpt5LevelE+0x9e8)[0x7f58a8532828]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZN4llvm16SelectionDAGISel17CodeGenAndEmitDAGEv+0xcf)[0x7f58a866ab8f]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZN4llvm16SelectionDAGISel20SelectAllBasicBlocksERKNS_8FunctionE+0x16dc)[0x7f58a8674a3c]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZN4llvm16SelectionDAGISel20runOnMachineFunctionERNS_15MachineFunctionE+0x507)[0x7f58a8676827]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(+0x23296c4)[0x7f58a9b6a6c4]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZN4llvm19MachineFunctionPass13runOnFunctionERNS_8FunctionE+0x91)[0x7f58a83293f1]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE+0x1f2)[0x7f58a8173a22]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE+0x33)[0x7f58a8173ad3]
/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x30f)[0x7f58a817366f]
/usr/lib/llvm-6.0/bin/clang(_ZN5clang17EmitBackendOutputERNS_17DiagnosticsEngineERKNS_19HeaderSearchOptionsERKNS_14CodeGenOptionsERKNS_13TargetOptionsERKNS_11LangOptionsERKN4llvm10DataLayoutEPNSE_6ModuleENS_13BackendActionESt10unique_ptrINSE_17raw_pwrite_streamESt14default_deleteISM_EE+0xa18)[0x777cf8]
/usr/lib/llvm-6.0/bin/clang[0xc9beb4]
/usr/lib/llvm-6.0/bin/clang(_ZN5clang8ParseASTERNS_4SemaEbb+0x318)[0xdc7fa8]
/usr/lib/llvm-6.0/bin/clang(_ZN5clang13CodeGenAction13ExecuteActionEv+0x37)[0xc9b5e7]
/usr/lib/llvm-6.0/bin/clang(_ZN5clang14FrontendAction7ExecuteEv+0x11e)[0xafface]
/usr/lib/llvm-6.0/bin/clang(_ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE+0x146)[0xacae06]
/usr/lib/llvm-6.0/bin/clang(_ZN5clang25ExecuteCompilerInvocationEPNS_16CompilerInstanceE+0x9f2)[0xb88502]
/usr/lib/llvm-6.0/bin/clang(_Z8cc1_mainN4llvm8ArrayRefIPKcEES2_Pv+0x9f8)[0x732ec8]
/usr/lib/llvm-6.0/bin/clang(main+0x1afc)[0x71f60c]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f58a69c5830]
/usr/lib/llvm-6.0/bin/clang(_start+0x29)[0x730ae9]
Stack dump:
0.      Program arguments: /usr/lib/llvm-6.0/bin/clang -cc1 -triple x86_64-pc-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name init.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -mdisable-tail-calls -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -coverage-notes-file /home/qa/Work/solid-linux/lib/dispatch/build/src/CMakeFiles/dispatch.dir/init.c.gcno -resource-dir /usr/lib/llvm-6.0/lib/clang/6.0.0 -dependency-file lib/dispatch/build/src/CMakeFiles/dispatch.dir/init.c.o.d -MT lib/dispatch/build/src/CMakeFiles/dispatch.dir/init.c.o -isystem lib/dispatch/src/BlocksRuntime -D DISPATCH_USE_DTRACE=0 -D HAVE_CONFIG_H -D _GNU_SOURCE -D _GNU_SOURCE=1 -D __EXTENSIONS__ -I lib/dispatch/build -I lib/dispatch -I lib/dispatch/src -I lib/dispatch/build/src -I lib/dispatch/private -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-6.0/lib/clang/6.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O1 -Werror=unused-command-line-argument -Wno-unused-function -Wno-missing-braces -Wno-unused-variable -Wno-return-type -Wno-deprecated -Wno-deprecated-declarations -Werror -Wall -Wextra -Warray-bounds-pointer-arithmetic -Wassign-enum -Watomic-properties -Wcomma -Wconditional-uninitialized -Wconversion -Wcovered-switch-default -Wdate-time -Wdeprecated -Wdocumentation -Wdouble-promotion -Wduplicate-enum -Wexpansion-to-defined -Wfloat-equal -Widiomatic-parentheses -Winfinite-recursion -Wmissing-prototypes -Wnewline-eof -Wnullable-to-nonnull-conversion -Wobjc-interface-ivars -Wover-aligned -Wpacked -Wpointer-arith -Wselector -Wshadow -Wshorten-64-to-32 -Wsign-conversion -Wstatic-in-inline -Wsuper-class-method-mismatch -Wswitch -Wunguarded-availability -Wunreachable-code -Wunused -Wno-unknown-warning-option -Wno-trigraphs -Wno-four-char-constants -Wno-disabled-macro-expansion -Wno-pedantic -Wno-bad-function-cast -Wno-c++-compat -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-cast-align -Wno-cast-qual -Wno-documentation-unknown-command -Wno-format-nonliteral -Wno-missing-variable-declarations -Wno-old-style-cast -Wno-padded -Wno-reserved-id-macro -Wno-shift-sign-overflow -Wno-undef -Wno-unreachable-code-aggressive -Wno-unused-macros -Wno-used-but-marked-unused -Wno-vla -Wno-error=assign-enum -std=gnu11 -fdebug-compilation-dir /home/qa/Work/solid-linux -ferror-limit 19 -fmessage-length 0 -fvisibility hidden -fsanitize=leak,alignment,array-bounds,bool,builtin,enum,float-cast-overflow,float-divide-by-zero,function,integer-divide-by-zero,nonnull-attribute,null,object-size,pointer-overflow,return,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,vla-bound,vptr,unsigned-integer-overflow,local-bounds -fsanitize-recover=alignment,array-bounds,bool,builtin,enum,float-cast-overflow,float-divide-by-zero,function,integer-divide-by-zero,nonnull-attribute,null,object-size,pointer-overflow,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,vla-bound,vptr,unsigned-integer-overflow -pthread -fblocks -fno-signed-char -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -o lib/dispatch/build/src/CMakeFiles/dispatch.dir/init.c.o -x c lib/dispatch/src/init.c 
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'lib/dispatch/src/init.c'.
4.      Running pass 'X86 DAG->DAG Instruction Selection' on function '@_dispatch_bug_kevent_vanished'
clang: error: unable to execute command: Floating point exception (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0-1ubuntu2~16.04.1 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/init-31fd43.c
clang: note: diagnostic msg: /tmp/init-31fd43.sh
clang: note: diagnostic msg: 

********************

**Comment by Endilll** [comment]
Can't reproduce using Clang 5 through 7 with assertions enabled.
