### ISSUE TITLE
Miscompilation: clang generates a weak symbol for a generic lambda that depends on a lambda in a static function

### ISSUE THREAD

**Issue by blastrock** [llvm/llvm-project#43713]
|  |  |
| --- | --- |
| Bugzilla Link | [44368](https://llvm.org/bz44368) |
| Version | trunk |
| OS | Linux |
| Attachments | [complete project that shows the bug](https://user-images.githubusercontent.com/92601857/143760205-2c7ecd8e-2dfc-4b77-818d-b361e558578f.gz) |
| CC | @dwblaikie,@zygoloid |

## Extended Description 

Here is a code snippet that shows the bug:

    template <typename T> auto async() {
      return [](auto func) {
        [func] { func(); }();
      };
    }
    static void f() {
      async<int>()([] { });
    }
    void f1() { f(); }

Compile with:

    clang++ -c ll.cpp

Run objdump -t ll.o -C, and you'll see the following symbol:

    0000000000000000  w    F .text._ZZZ5asyncIiEDavENKUlT_E_clIZL1fvE3$_0EEDaS0_ENKUlvE_clEv	000000000000001b async<int>()::{lambda(auto:1)#1}::operator()<f()::$_0>(f()::$_0) const::{lambda()#1}::operator()() const

This is the call operator of the inner lambda on line 3 and this symbol is *weak*, even though it depends on the func argument, which is a lambda from a static function. I think this symbol should be *local* as a *weak* symbol might be overridden by another translation unit.

The consequence is that if there are two static functions that have the same name in two different translation units and that they both define a lambda, calling async with that lambda will generate only one symbol in the final binary and that usually leads to a crash in a more complex example.

I am attaching a more complete project which shows the miscompilation issue. The program should print 1 and 2, but it prints 1 and 1 for the reason described above. Renaming the static function in one of the translation units fixes the issue.

GCC 9 compiles the program correctly, produces *local* symbols for that call operator and the program prints 1 and 2.

**Comment by Endilll** [comment]
Linked patch was landed, and I can't reproduce the issue.
