### ISSUE TITLE
Wmissing-variable-declarations fires for static variable in module

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#43738]
|  |  |
| --- | --- |
| Bugzilla Link | [44393](https://llvm.org/bz44393) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie,@zygoloid |

## Extended Description 
The following translation unit:

```
export module foo;

namespace {

static constexpr int x = 5;

} // namespace
```

warns when compiled with `clang++ -std=c++2a -Wmissing-variable-declarations`

See it live: https://godbolt.org/z/YBPr-b

**Comment by xgupta** [comment]
Fixed in trunk, no warning - https://godbolt.org/z/sasqMnn63.
