### ISSUE TITLE
Remove SCALAR_TO_VECTOR

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#4375]
|  |  |
| --- | --- |
| Bugzilla Link | [4003](https://llvm.org/bz4003) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lattner |

## Extended Description 
The SCALAR_TO_VECTOR codegen node is redundant: it is
equivalent to BUILD_VECTOR(Value, undef, undef, ...).
It should probably be removed.

**Comment by arsenm** [comment]
This was never removed, but GlobalISel hasn't copied it. File this under "delete SelectionDAG"
