### ISSUE TITLE
Significant compile time regressions since Clang 9

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#43753]
|  |  |
| --- | --- |
| Bugzilla Link | [44408](https://llvm.org/bz44408) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#44654 llvm/llvm-project#43900  |
| CC | @abrahm,@alinas,@topperc,@dwblaikie,@DougGregor,@fhahn,@zmodem,@RKSimon,@nikic,@zygoloid,@rotateright,@sylvestre,@tstellar,@yuanfang-chen |

## Extended Description 
Recent Phoronix article mentions huge compile time / perf regressions.

For example:
https://www.phoronix.com/scan.php?page=article&item=gcc-clang-3960x&num=4

ImageMagisk - 50 % worse compile time.
PHP - 20 % worse compile time.

**Comment by fhahn** [comment]
We've long moved past 10.0.1 and from the discussion here it *seems* to me like the original issue should be fixed. Can we close this issue?

**Comment by davidbolvansky** [comment]
Yes

**Comment by fhahn** [comment]
Thanks!
