### ISSUE TITLE
[clang-format] support interpolated and verbatim strings for CSharp formatting

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43799]
|  |  |
| --- | --- |
| Bugzilla Link | [44454](https://llvm.org/bz44454) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Interpolated (e.g. $"{expression} literal" ) and verbatim (e.g. @" ""foo"" " ) strings should not be modified in a program/compile breaking fashion.  Below are a few examples of symptoms.

clang-format.exe version 10.0.0 downloaded from here:

https://www.google.com/url?q=https://prereleases.llvm.org/win-snapshots/clang-format-e20a1e486e1.exe&sa=D&ust=1578080154426000&usg=AFQjCNFOoOqZ8Iurk2gAxe8hICMLOJapgg

----------.clang-format----------
Language: CSharp
BasedOnStyle: Microsoft

ColumnLimit: 100
AlignAfterOpenBracket: DontAlign
AllowShortFunctionsOnASingleLine: true
AllowShortBlocksOnASingleLine: true
AllowShortCaseLabelsOnASingleLine: true
IndentCaseLabels: true

BreakStringLiterals: false
---------------------------------

----------Code 1 Before----------
```
class Foo
{
    string str = @"""";
}
```
---------------------------------

----------Code 1 After-----------
```
class Foo
{
    string str = @"" "";
                   ^^^ Extra space added
}
```
---------------------------------

----------Code 2 Before----------
```
class Foo
{
    string str1 = $"{null ?? "null"}";
    string str2 = $"{string.Join(";", lines)}";
}
```
---------------------------------

----------Code 2 After----------
```
class Foo
{
    string str1 = $"{null ?? " null "}";
                             ^^^  ^^^ Extra spaces added
    string str2 = $"{string.Join(";
                                  ^^^ Newline added, this doesn't even compile.
    ", lines)}";
}
```
---------------------------------

**Comment by mydeveloperday** [comment]
with current main branch clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 7890afddecff01119f4d5e8825b43dd2c8361648)


I see this

```
class Foo {
  string str = @"""";
}

class Foo {
  string str1 = $"{null ?? "null"}";
  string str2 = $"{string.Join(";", lines)}";
}
```

where as with 10.0 I see this

```
class Foo {
  string str = @"" "";
}

class Foo {
  string str1 = $"{null ?? " null "}";
  string str2 = $"{string.Join(";
  ", lines)}";
}
```

I'm marking this issue as closed, feel free to reopen it if you still see issues
