### ISSUE TITLE
modernize-redundant-void-arg will remove function return type

### ISSUE THREAD

**Issue by 91b604ff-5b4e-4821-a182-129f49d1a44c** [llvm/llvm-project#43791]
|  |  |
| --- | --- |
| Bugzilla Link | [44446](https://llvm.org/bz44446) |
| Version | unspecified |
| OS | Windows NT |
| CC | @EugeneZelenko,@LegalizeAdulthood |

## Extended Description 
https://godbolt.org/z/CbUaa5

#define return_t(T) T
return_t(void) f(void);

<source>:4:10: warning: redundant void argument list in function declaration [modernize-redundant-void-arg]

return_t(void) f(void);

         ^~~~

<source>:4:18: warning: redundant void argument list in function declaration [modernize-redundant-void-arg]

return_t(void) f(void);

                 ^~~~

**Comment by LegalizeAdulthood** [comment]
[clang-tidy] Improve modernize-redundant-void-arg to recognize macro uses
https://reviews.llvm.org/D116425
