### ISSUE TITLE
Assertion `Changes[i - 1].OriginalWhitespaceRange.getBegin() != C.OriginalWhitespaceRange.getBegin() && "Generating two replacements for the same location"' failed.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43809]
|  |  |
| --- | --- |
| Bugzilla Link | [44464](https://llvm.org/bz44464) |
| Version | trunk |
| OS | Linux |
| Attachments | [Stack trace](https://user-images.githubusercontent.com/60944935/143760235-d9a03080-adba-4a3e-a17e-718fac0b214f.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

While blindly applying clang-format on all .cpp files inside the llvm-project tree, I stumbled upon this assertion fail.

The fail appears while running clang-format on the following comments in clang/test/CodeGenCXX/constructor-destructor-return-this.cpp:
//RUN: %clang_cc1 %s -emit-llvm -o - -triple=i686-unknown-linux| FileCheck --check-prefix=CHECKGEN %s
//RUN: %clang_cc1 %s -emit-llvm -o - -triple=thumbv7-apple-ios6.0 -target-abi apcs-gnu | FileCheck --check-prefix=CHECKARM %s
//RUN: %clang_cc1 %s -emit-llvm -o - -triple=thumbv7-apple-ios5.0 -target-abi apcs-gnu | FileCheck --check-prefix=CHECKIOS5 %s
//RUN: %clang_cc1 %s -emit-llvm -o - -triple=wasm32-unknown-unknown \
//RUN:   | FileCheck --check-prefix=CHECKARM %s
//RUN: %clang_cc1 %s -emit-llvm -o - -triple=x86_64-unknown-fuchsia | FileCheck --check-prefix=CHECKFUCHSIA %s
//RUN: %clang_cc1 %s -emit-llvm -o - -triple=aarch64-unknown-fuchsia | FileCheck --check-prefix=CHECKFUCHSIA %s
//RUN: %clang_cc1 %s -emit-llvm -o - -triple=i386-pc-win32 -fno-rtti | FileCheck --check-prefix=CHECKMS %s

I can avoid the assertion fail either by setting the column limit to 0 (but setting it to 500 doesn't work) or by inserting an empty line after each comment line. This issue didn't exist on clang-format 9.

**Comment by mydeveloperday** [comment]
This issue has no reproducible test, I'm going to close it. feel free to open it if you want to add a usecase
