### ISSUE TITLE
docs/AttributeReference.html is blank

### ISSUE THREAD

**Issue by nlewycky** [llvm/llvm-project#43808]
|  |  |
| --- | --- |
| Bugzilla Link | [44463](https://llvm.org/bz44463) |
| Version | unspecified |
| OS | Linux |
| Attachments | [empty AttributeReference.html](https://user-images.githubusercontent.com/392652/143760234-271c7300-d1fd-4e37-8017-f4b22ef5cb4e.gz) |
| CC | @zygoloid |

## Extended Description 

https://clang.llvm.org/docs/AttributeReference.html has no content, just the header + navbar, title "Attributes in Clang", then the navbar + footer.

See also llvm/llvm-project#24415 .

AttributeReference.html as I saw it, attached.

**Comment by arsenm** [comment]
Seems to work?
