### ISSUE TITLE
`readability-misleading-indentation` broken for `if constexpr`

### ISSUE THREAD

**Issue by abpostelnicu** [llvm/llvm-project#43835]
|  |  |
| --- | --- |
| Bugzilla Link | [44490](https://llvm.org/bz44490) |
| Version | unspecified |
| OS | All |

## Extended Description 
I've created this patch in order to fix this issue https://reviews.llvm.org/D72333. Please note this issue is related with Bug 32203.

**Comment by EugeneZelenko** [comment]
Patch was committed in ba129c7d0f5c7c32398ad708c88e14cb06a339ad.
