### ISSUE TITLE
Includes are sorted by ASCII code, not alphabetically

### ISSUE THREAD

**Issue by mmatrosov** [llvm/llvm-project#43847]
|  |  |
| --- | --- |
| Bugzilla Link | [44502](https://llvm.org/bz44502) |
| Version | trunk |
| OS | All |
| CC | @dwblaikie,@seanm |

## Extended Description 
Consider this snippet:

#include <boost/algorithm/string.hpp>
#include <GL/GLU.h>
#include <boost/algorithm/string/split.hpp>

If I sort includes with clang-format, I have this order:

#include <GL/GLU.h>
#include <boost/algorithm/string.hpp>
#include <boost/algorithm/string/split.hpp>

Which satisfies order on ASCII codes of the includes. However, I'd expect the alphabetical order:

#include <boost/algorithm/string.hpp>
#include <boost/algorithm/string/split.hpp>
#include <GL/GLU.h>

**Comment by mydeveloperday** [comment]
This is fixed by using

`SortIncludes: CaseInsensitive`

I'm closing this issue
