### ISSUE TITLE
llvm-profdata failed to merge profraw with Unsupported instrumentation profile format version

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43858]
|  |  |
| --- | --- |
| Bugzilla Link | [44513](https://llvm.org/bz44513) |
| Resolution | WONTFIX |
| Resolved on | Jan 13, 2020 10:29 |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @m-gupta |

## Extended Description 
I built instrumented llvm with -fprofile-generate and use llvm to build libunwind and got profraw data.

When using llvm-profdata to merge the profraw file, cmd:
bin/llvm-profdata merge --output perf.data ~/llvm/libunwind.profraw

It shows error:

warning: ~/llvm/libunwind.profraw: Unsupported instrumentation profile format version
error: No profiles could be merged.

Attached is the profraw data I generated with intrumented llvm.

**Comment by haydenzhourepo** [comment]
I encountered this problem when I used Visual Studio 2022 and clang-cl.exe to build a project. and I have check the clang-cl.exe and llvm-profdata.exe  are the same version.
