### ISSUE TITLE
Pruning of dead -Wshift-count-overflow suppressed in dead branches of _Generic

### ISSUE THREAD

**Issue by c8cd4046-bf2f-4470-bb42-add0a3666ec0** [llvm/llvm-project#43869]
|  |  |
| --- | --- |
| Bugzilla Link | [44524](https://llvm.org/bz44524) |
| Version | 9.0 |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
A simple example in which I'm getting undesirable -Wshift-count-overflow warnings
is

	(void)_Generic(0, int: 0, char: /*untaken*/ 0 ?  1 << 200 : 0); //-Wshift-count-overflow warning

The warning does not come up in a simple

	(void)_Generic(0, char: 0, int: /*taken*/ 0 ?  1 << 200 : 0); //no warning as expected

or in a flat

	(void)(  0 ? 1 << 200 : 0 ); //no warning as expected

Examples on Compiler Explorer: https://gcc.godbolt.org/z/dW8h2K

**Comment by AaronBallman** [comment]
Duplicate of #25764
