### ISSUE TITLE
clang90 on FreeBSD is missing the `map::extract` C++17 feature

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#43864]
|  |  |
| --- | --- |
| Bugzilla Link | [44519](https://llvm.org/bz44519) |
| Version | unspecified |
| OS | FreeBSD |
| CC | @DimitryAndric,@zygoloid |

## Extended Description 
This project fails to build on FreeBSD with clang90: https://github.com/sgsaenger/vipster

The FreeBSD bug report: http://beefy5.nyi.freebsd.org/data/120i386-default/522623/logs/vipster-1.18.b.75_1.log

map::extract (https://en.cppreference.com/w/cpp/container/map/extract) seems to be missing.

**Comment by frederick-vs-ja** [comment]
Should have been "fixed" (added) in LLVM 8.0.
