### ISSUE TITLE
Attempting to split dwarf info into separate file causes segfault during wasm usecase

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43870]
|  |  |
| --- | --- |
| Bugzilla Link | [44525](https://llvm.org/bz44525) |
| Version | 9.0 |
| OS | Linux |
| Attachments | [repro files](https://user-images.githubusercontent.com/60944935/143760258-807c92b3-af5b-4bd8-b357-68b7d78c4949.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie,@zygoloid |

## Extended Description 

pc@debian:~/test/wasm-c-test$ clang-9 -gsplit-dwarf --target=wasm32 --no-standard-libraries -Wl,--export-all -Wl,--no-entry -o add.wasm add.c
Stack dump:
0.	Program arguments: /usr/lib/llvm-9/bin/clang -cc1 -triple wasm32 -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name add.c -mrelocation-model static -mthread-model posix -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -fvisibility hidden -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -ggnu-pubnames -momit-leaf-frame-pointer -resource-dir /usr/lib/llvm-9/lib/clang/9.0.1 -internal-isystem /usr/lib/llvm-9/lib/clang/9.0.1/include -internal-isystem /include -fdebug-compilation-dir /home/pc/test/wasm-c-test -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gnustep -fno-common -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/add-8792ee.o -x c add.c 
1.	<eof> parser at end of file
2.	Code generation
 #&#8203;0 0x00007f9ade13fdbf llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/lib/x86_64-linux-gnu/libLLVM-9.so.1+0xb63dbf)
 #&#8203;1 0x00007f9ade13e1e0 llvm::sys::RunSignalHandlers() (/usr/lib/x86_64-linux-gnu/libLLVM-9.so.1+0xb621e0)
 #&#8203;2 0x00007f9ade1401c1 (/usr/lib/x86_64-linux-gnu/libLLVM-9.so.1+0xb641c1)
 #&#8203;3 0x00007f9ae3e580e0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x110e0)
 #&#8203;4 0x00007f9adefc6d38 llvm::MCWasmStreamer::ChangeSection(llvm::MCSection*, llvm::MCExpr const*) (/usr/lib/x86_64-linux-gnu/libLLVM-9.so.1+0x19ead38)
 #&#8203;5 0x00007f9adefc3ded llvm::MCStreamer::SwitchSection(llvm::MCSection*, llvm::MCExpr const*) (/usr/lib/x86_64-linux-gnu/libLLVM-9.so.1+0x19e7ded)
 #&#8203;6 0x00007f9ade768d34 llvm::DwarfDebug::emitDebugPubSections() (/usr/lib/x86_64-linux-gnu/libLLVM-9.so.1+0x118cd34)
 #&#8203;7 0x00007f9ade743751 llvm::AsmPrinter::doFinalization(llvm::Module&) (/usr/lib/x86_64-linux-gnu/libLLVM-9.so.1+0x1167751)
 #&#8203;8 0x00007f9ade23e451 llvm::FPPassManager::doFinalization(llvm::Module&) (/usr/lib/x86_64-linux-gnu/libLLVM-9.so.1+0xc62451)
 #&#8203;9 0x00007f9ade23e912 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/x86_64-linux-gnu/libLLVM-9.so.1+0xc62912)
#&#8203;10 0x00007f9ae2bcca06 EmitAssembly /build/llvm-toolchain-9-9~+20191205074958+432bf48c08d/clang/lib/CodeGen/BackendUtil.cpp:899:3
#&#8203;11 0x00007f9ae2bcca06 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) /build/llvm-toolchain-9-9~+20191205074958+432bf48c08d/clang/lib/CodeGen/BackendUtil.cpp:1498:15
#&#8203;12 0x00007f9ae2e01eed ~unique_ptr /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/unique_ptr.h:238:6
#&#8203;13 0x00007f9ae2e01eed clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) /build/llvm-toolchain-9-9~+20191205074958+432bf48c08d/clang/lib/CodeGen/CodeGenAction.cpp:303:7
#&#8203;14 0x00007f9ae2142893 __normal_iterator /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/stl_iterator.h:777:20
#&#8203;15 0x00007f9ae2142893 begin /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/stl_vector.h:549:16
#&#8203;16 0x00007f9ae2142893 finalize<std::vector<std::unique_ptr<clang::TemplateInstantiationCallback, std::default_delete<clang::TemplateInstantiationCallback> >, std::allocator<std::unique_ptr<clang::TemplateInstantiationCallback, std::default_delete<clang::TemplateInstantiationCallback> > > > > /build/llvm-toolchain-9-9~+20191205074958+432bf48c08d/clang/include/clang/Sema/TemplateInstCallback.h:54:16
#&#8203;17 0x00007f9ae2142893 clang::ParseAST(clang::Sema&, bool, bool) /build/llvm-toolchain-9-9~+20191205074958+432bf48c08d/clang/lib/Parse/ParseAST.cpp:178:3
#&#8203;18 0x00007f9ae33d4a48 clang::FrontendAction::Execute() /build/llvm-toolchain-9-9~+20191205074958+432bf48c08d/clang/lib/Frontend/FrontendAction.cpp:938:10
#&#8203;19 0x00007f9ae33952c0 getPtr /build/llvm-toolchain-9-9~+20191205074958+432bf48c08d/llvm/include/llvm/Support/Error.h:273:42
#&#8203;20 0x00007f9ae33952c0 operator bool /build/llvm-toolchain-9-9~+20191205074958+432bf48c08d/llvm/include/llvm/Support/Error.h:236:16
#&#8203;21 0x00007f9ae33952c0 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /build/llvm-toolchain-9-9~+20191205074958+432bf48c08d/clang/lib/Frontend/CompilerInstance.cpp:944:23
#&#8203;22 0x00007f9ae3437060 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /build/llvm-toolchain-9-9~+20191205074958+432bf48c08d/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:291:25
#&#8203;23 0x00000000004a2f06 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /build/llvm-toolchain-9-9~+20191205074958+432bf48c08d/clang/tools/driver/cc1_main.cpp:249:15
#&#8203;24 0x00000000004a1271 ExecuteCC1Tool /build/llvm-toolchain-9-9~+20191205074958+432bf48c08d/clang/tools/driver/driver.cpp:309:12
#&#8203;25 0x00000000004a1271 main /build/llvm-toolchain-9-9~+20191205074958+432bf48c08d/clang/tools/driver/driver.cpp:381:12
#&#8203;26 0x00007f9adc9c02e1 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e1)
#&#8203;27 0x000000000049e70a _start (/usr/lib/llvm-9/bin/clang+0x49e70a)
clang: error: unable to execute command: Segmentation fault
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 9.0.1-+20191205074958+432bf48c08d-1~exp1~20191205185557.104 
Target: wasm32
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/add-891092.c
clang: note: diagnostic msg: /tmp/add-891092.sh
clang: note: diagnostic msg:

**Comment by Endilll** [comment]
Fixed in Clang 12: https://godbolt.org/z/5bodhfoEh
