### ISSUE TITLE
Missed optimization: clang does not infer from assumptions

### ISSUE THREAD

**Issue by bernardosulzbach** [llvm/llvm-project#43922]
|  |  |
| --- | --- |
| Bugzilla Link | [44577](https://llvm.org/bz44577) |
| Version | 9.0 |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
As of Clang 9.0.0, no inference is done based on __builtin_assume. I have tested using "-std=c++17 -O2", but -O3 seems to do the same.

Example 1

  bool lessThan(int a, int b) {
      __builtin_assume(a < b);
      return a < b;
  }

compiles into

  lessThan(int, int):
      mov     al, 1
      ret

as one would expect. If the assumption is negated (!(a < b)), the compiler will optimize it to return 0. However, if the assumption is any of (a == b), (a >= b), (a > b), or (a == b || a > b) a comparison is emitted.

Example 2

  bool lessThan(int a, int b, int c) {
      __builtin_assume(a < b);
      __builtin_assume(b < c);
      return a < c;
  }

also requires a comparison, even though a < c can be inferred from the assumptions.

**Comment by wheatman** [comment]
This has been fixed, the first few case were fixed for 11.0.0, and last just in post 16 trunk(f05b58a9468cc2990678e06bc51df56b30344807)
https://godbolt.org/z/6aon8zq38

code
```
// compile with -O3

bool lessThan1(int a, int b) {
__builtin_assume(a == b);
return a < b;
}

bool lessThan2(int a, int b) {
__builtin_assume(a >= b);
return a < b;
}

bool lessThan3(int a, int b) {
__builtin_assume(a > b);
return a < b;
}

bool lessThan4(int a, int b, int c) {
__builtin_assume(a < b);
__builtin_assume(b < c);
return a < c;
}
```

original 
```
lessThan1(int, int):                         # @lessThan1(int, int)
        cmp     edi, esi
        setl    al
        ret
lessThan2(int, int):                         # @lessThan2(int, int)
        cmp     edi, esi
        setl    al
        ret
lessThan3(int, int):                         # @lessThan3(int, int)
        cmp     edi, esi
        setl    al
        ret
lessThan4(int, int, int):                        # @lessThan4(int, int, int)
        cmp     edi, edx
        setl    al
        ret
```
with clang 11 only the last one has a comparison
```
lessThan1(int, int):                         # @lessThan1(int, int)
        xor     eax, eax
        ret
lessThan2(int, int):                         # @lessThan2(int, int)
        xor     eax, eax
        ret
lessThan3(int, int):                         # @lessThan3(int, int)
        xor     eax, eax
        ret
lessThan4(int, int, int):                        # @lessThan4(int, int, int)
        cmp     edi, edx
        setl    al
        ret
```
with current trunk(f05b58a9468cc2990678e06bc51df56b30344807) their are no comparisons
```
lessThan1(int, int):                         # @lessThan1(int, int)
        xor     eax, eax
        ret
lessThan2(int, int):                         # @lessThan2(int, int)
        xor     eax, eax
        ret
lessThan3(int, int):                         # @lessThan3(int, int)
        xor     eax, eax
        ret
lessThan4(int, int, int):                        # @lessThan4(int, int, int)
        mov     al, 1
        ret
```
