### ISSUE TITLE
[AMDGPU][MC][GFX908] 'glc' is not supported for buffer_atomic_add_f32 and buffer_atomic_pk_add_f16

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#43929]
|  |  |
| --- | --- |
| Bugzilla Link | [44584](https://llvm.org/bz44584) |
| Version | trunk |
| OS | Windows NT |
| CC | @atamazov,@arsenm,@rampitec |

## Extended Description 
'glc' is not currently supported for these opcodes:

    buffer_atomic_add       v5, off, s[8:11], s3 offset:4095 glc    // ok
    buffer_atomic_add_f32   v5, off, s[8:11], s3 offset:4095 glc    // fail
    buffer_atomic_add_f32   v5, off, s[8:11], s3 offset:4095        // ok

sp3 assembler seems to support 'glc' modifier:

    buffer_atomic_add_f32   v5, v0, s[8:11], s3 offset:4095 glc     // sp3:ok

**Comment by jwanggit86** [comment]
This comes down to whether the `buffer_atomic_add_f32` instruction returns value. According to Sect. 12.14 of the MI100 ISA Doc, it seems it dose not return value. In that case, it does not support GLC, given the definition of the GLC bit in Sect. 13.6.2:
```
0 = normal, 1 = globally coherent (bypass L0 cache) or for atomics, return preop
value to VGPR.
```
Therefore, this does not seem to be a bug. Same for `buffer_atomic_pk_add_f16`.

**Comment by arsenm** [comment]
In mi100 it could not return a value. It can in later targets

**Comment by jwanggit86** [comment]
> In mi100 it could not return a value. It can in later targets

So the current implementation is correct: glc is not allowed in `buffer_atomic_add_f32` for MI100, but is allowed for later targets.

**Comment by arsenm** [comment]
> So the current implementation is correct: glc is not allowed in `buffer_atomic_add_f32` for MI100, but is allowed for later targets.

Yes, seems to be

**Comment by jwanggit86** [comment]
Closing this issue based on the discussion above.
