### ISSUE TITLE
performance-unnecessary-value-param false positive for template function

### ISSUE THREAD

**Issue by pepsiman** [llvm/llvm-project#43943]
|  |  |
| --- | --- |
| Bugzilla Link | [44598](https://llvm.org/bz44598) |
| Version | unspecified |
| OS | Linux |
| CC | @adegroote,@frankmiller,@EugeneZelenko,@fberger |

## Extended Description 
$ cat move.cpp 
#include <string>

template <typename B> struct A {
  std::string a;
};

template <typename B> A<B> fn(std::string a) {
  return {std::move(a)};
}

$ clang-tidy -checks='-*,performance-unnecessary-value-param' forward.cpp -- -std=c++17
1 warning generated.
move.cpp:7:43: warning: the parameter 'a' is copied for each invocation but only used as a const reference; consider making it a const reference [performance-unnecessary-value-param]
template <typename B> A<B> fn(std::string a) {
                                          ^
                              const      &

**Comment by carlosgalvezp** [comment]
None of the issues mentioned are reproducible on latest trunk.
