### ISSUE TITLE
Compiler crash on dependent type missing typename

### ISSUE THREAD

**Issue by Dwarfobserver** [llvm/llvm-project#43961]
|  |  |
| --- | --- |
| Bugzilla Link | [44616](https://llvm.org/bz44616) |
| Version | trunk |
| OS | All |
| CC | @AaronBallman,@mkurdej,@DougGregor,@zygoloid |

## Extended Description 
Possible duplicate of bug '16926'.

Clang crashes when instanciating a dependent type without writing 'typename'.
Crashes on Clang 3.0.0 as well as Clang trunk.

The invalid code:

```cpp
template <class T>
struct bla {
    template <class U>
    using blo = U;
};

template <class T>
constexpr bool pred() {
    return /*typename*/ bla<T>::template blo<T>{};
}

int main() {
    return pred<int>();
}
```

**Comment by shafik** [comment]
This no longer crashes on trunk: https://godbolt.org/z/WMhTME9dv

but it does crash on clang-16, so this was recently fixed. CC @AaronBallman
