### ISSUE TITLE
[clang-tidy] misc-redundant-expression assumes operator sides are equivalent in if-constexpr

### ISSUE THREAD

**Issue by def-** [llvm/llvm-project#43962]
|  |  |
| --- | --- |
| Bugzilla Link | [44617](https://llvm.org/bz44617) |
| Version | unspecified |
| OS | Linux |
| CC | @EugeneZelenko |

## Extended Description 
Hi,

Starting with clang-tidy 10 I'm seeing misc-redundant-expression detecting equivalent operator sides inside of if-constexpr even though they are not actually equivalent:

```
$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 10.0.175git
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: broadwell
$ cat .clang-tidy
Checks: misc-redundant-expression
$ cat x.cpp
struct S
{
    int a;
    int b;
};

int main(int /*argc*/, char** /*argv*/)
{
    if constexpr((sizeof(S) % sizeof(int) != 0) || (alignof(S) % alignof(int) != 0)) {
    }

    return 0;
}

$ clang-tidy --extra-arg=-std=c++1z x.cpp
/home/d067158/x.cpp:12:49: warning: both sides of operator are equivalent [clang-tidy-misc-redundant-expression]
    if constexpr((sizeof(S) % sizeof(int) != 0) || (alignof(S) % alignof(int) != 0)) {
                                                ^
```

Best regards
Dennis

**Comment by philnik777** [comment]
Is there any update on this? It looks like the bug still exists: https://godbolt.org/z/48an8Kzj4.

**Comment by 5chmidti** [comment]
The check no longer emits diagnostics in both of these examples
