### ISSUE TITLE
Alias template name rejected in explicit destructor call

### ISSUE THREAD

**Issue by 13174bef-8458-48a1-b40c-bc269b577a71** [llvm/llvm-project#43974]
|  |  |
| --- | --- |
| Bugzilla Link | [44629](https://llvm.org/bz44629) |
| Version | unspecified |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Clang (all versions which I could try) reports a compile error on the explicit destructor call line:
```
error: no member named 'B' in 'A<int, int>'
```
(gcc and msvc accept this code).
```cpp
template <typename T, typename U>
class A {};

template <typename T>
using B = A<T, int>;

template <typename T>
void foo(B<T>* x) {

	// Fails with error: no member named 'B' in 'A<int, int>'
	x->~B<T>();

	// workaround:
	//using BT = B<T>;
	//x->~BT();
}

// instantiate foo()
template void foo<int>(B<int>* x);
int main(){}
```

**Comment by cor3ntin** [comment]
Fixed in clang 11 https://godbolt.org/z/rrorhKzYd
