### ISSUE TITLE
clang-format BWACS_MultiLine option not working with ForEachMacros

### ISSUE THREAD

**Issue by 0f224314-e0fe-48a1-ac11-a469005a20f5** [llvm/llvm-project#43977]
|  |  |
| --- | --- |
| Bugzilla Link | [44632](https://llvm.org/bz44632) |
| Version | 11.0 |
| OS | Linux |

## Extended Description 
If the BraceWrapping AfterControlStatement rule is set to MultiLine, this rule is not correctly handled with ForEachMacros, and acts as if it was configured as "Always" on these macros:

Here is a short example to reproduce:

Configuration:
```
---
BreakBeforeBraces: Custom
BraceWrapping:
  AfterControlStatement: MultiLine
ColumnLimit: 30
ForEachMacros: ['for_macro']
```

Input file:
```
void bar(void) {
  for (aaa; bbb && ccc && ddd; eee) {
    foo();
  }
  for (a; b; c) {
    foo();
  }
  for_macro (a, b, c) {
    foo();
  }
  for_macro (aaa, bbb && ccc, ddd) {
    foo();
  }
}
```

Result:
```
void bar(void) {
  for (aaa; bbb && ccc && ddd;
       eee)
  {
    foo();
  }
  for (a; b; c) {
    foo();
  }
  for_macro (a, b, c)
  {
    foo();
  }
  for_macro (aaa, bbb && ccc,
             ddd)
  {
    foo();
  }
}
```

Expected result is to get:
```
  for_macro (a, b, c) {
    foo();
  }
```
for the first occurrence.

This is tested with clang-format version 10.0.0-++20200115115127+cbe681bd833-1~exp1~20200115105727.528

**Comment by mydeveloperday** [comment]
For clang-format v12 and above I see

```
void bar(void) {
  for (aaa; bbb && ccc && ddd;
       eee)
  {
    foo();
  }
  for (a; b; c) {
    foo();
  }
  for_macro (a, b, c) {
    foo();
  }
  for_macro (aaa, bbb && ccc,
             ddd)
  {
    foo();
  }
}
```

I am closing this issue, please feel free to reopen it if you think it is not fixed
