### ISSUE TITLE
GPF when passing a non-aligned struct to a __declspec(align) typedef

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43986]
|  |  |
| --- | --- |
| Bugzilla Link | [44641](https://llvm.org/bz44641) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid,@rnk,@sylvain-audi |

## Extended Description 
Clang does not complain when a non-aligned instance is assigned to aligned typedef'd type (repro below).
I think at least a warning would be nice (if not, an error).

MSVC and GCC handle this by doing a unaligned load.

https://godbolt.org/z/62HzmJ

--------------------------------
// a.h
struct Vector4 { float v[4]; };
typedef __declspec(align(16)) Vector4  AlignVector4;

struct A {
  AlignVector4 vec;
  void SetVec(const AlignVector4& v) { vec = v; }
};
struct B {
  bool b;
  Vector4 vec;
};
--------------------------------
// a.cpp
#include "a.h"
int f(A& a, const B& b) {
  a.SetVec(b.vec);
  return (int)a.vec.v[0];
}
--------------------------------
// main.cpp
#include "a.h"
int f(A& a, const B& b);
int main() {
  A a; B b;
  return f(a, b);
}

--------------------------------
// Build:
// clang-cl a.cpp /O2 /c /MT
// clang-cl main.cpp /c /MT
// lld-link a.obj main.obj /entry:main /subsystem:console

**Comment by sylvain-audi** [comment]
@aganea Is this issue ready to close: clang still generates the aligned instructions, but it will issue a "-Walign-mismatch" diagnostic, since clang 13.0.0

**Comment by aganea** [comment]
@sylvain-audi Yes, a warning is better than nothing.
