### ISSUE TITLE
clangd-vscode: Incorrect Comment Syntax Highlighting Misapplied on Edit

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#44084]
|  |  |
| --- | --- |
| Bugzilla Link | [44739](https://llvm.org/bz44739) |
| Version | trunk |
| OS | MacOS X |
| Attachments | [Image showing syntax highlighting bug](https://user-images.githubusercontent.com/60944935/143760325-ca7e9059-fc26-4e6a-aab2-27e6bb2fac0e.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

This is a bug for the clangd-vscode plugin (http://llvm.org/svn/llvm-project/clang-tools-extra/trunk/clangd/clients/clangd-vscode/).

All the syntax highlighting is fine on first reload, but gets misapplied to comments when they are inserted and the file is reprocessed. The comments seem to take on the highlighting of the code line that was previously in their place. (See attached screenshot.)

On my machine, this reproduces every time in every file. (Latest VSCode, plugin, macOS, and clangd release.)

Otherwise, thank you all for an exceptional plugin!

-Chris

**Comment by sam-mccall** [comment]
Sorry for not finding this until way too late :-(

I believe this is obsolete.
We had a custom protocol for syntax highlighting and a custom client-side implementation in VSCode, and it was buggy. We've now migrated to the standard protocol with the first-party VSCode support, and these bugs are (I believe) all gone.
