### ISSUE TITLE
The clangd is crashed under the macos 15

### ISSUE THREAD

**Issue by 99530f72-9ed6-4ad2-a002-a6bae08d6657** [llvm/llvm-project#44111]
|  |  |
| --- | --- |
| Bugzilla Link | [44766](https://llvm.org/bz44766) |
| Version | unspecified |
| OS | MacOS X |

## Extended Description 
The parameter to start clangd is :  clangd -j=8 --pch-storage=memory -background-index -log=error --compile-commands-dir=build --clang-tidy --completion-style=detailed
The clangd version is 9.0.0(tags/RELEASE_900/final)

**Comment by arsenm** [comment]
Duplicate #44110
