### ISSUE TITLE
Library vectorization broken with new pass manager

### ISSUE THREAD

**Issue by d0k** [llvm/llvm-project#44115]
|  |  |
| --- | --- |
| Bugzilla Link | [44770](https://llvm.org/bz44770) |
| Version | trunk |
| OS | Linux |
| CC | @fpetrogalli,@jdoerfert,@RKSimon |

## Extended Description 
$ cat veclib.c 
void foo(float *a) {
  for (int i = 0; i != 1024; ++i)
    a[i] = __builtin_expf(a[i]);
}

$ clang -O3 -S -o - veclib.c -fveclib=Accelerate -fexperimental-new-pass-manager|grep vexpf
$ clang -O3 -S -o - veclib.c -fveclib=Accelerate |grep vexpf                               
        callq   vexpf
        callq   vexpf

The reason seems to be that InjectTLIMappings never runs.

**Comment by fhahn** [comment]
This should be fixed by https://reviews.llvm.org/rG9ed0612ccaf0590640a5ea0cc57ced546062577a. Please re-open if there is still an issue.
