### ISSUE TITLE
The clangd is crashed under the macos 15

### ISSUE THREAD

**Issue by 99530f72-9ed6-4ad2-a002-a6bae08d6657** [llvm/llvm-project#44110]
|  |  |
| --- | --- |
| Bugzilla Link | [44765](https://llvm.org/bz44765) |
| Version | unspecified |
| OS | MacOS X |
| Attachments | [the crash report while using the clangd](https://user-images.githubusercontent.com/93435950/143760330-9d026271-ffc8-445e-8730-82ceaacd2f12.gz) |

## Extended Description 

The parameter to start clangd is :  clangd -j=8 --pch-storage=memory -background-index -log=error --compile-commands-dir=build --clang-tidy --completion-style=detailed
The clangd version is 9.0.0(tags/RELEASE_900/final)

**Comment by HighCommander4** [comment]
@kopinions are you still seeing this with a recent clangd?

**Comment by kopinions** [comment]
@HighCommander4 I have not using clangd for a while, I just close this issue.

**Comment by kopinions** [comment]
I can't close the issue, please close the issue, thanks.
