### ISSUE TITLE
clang-cl crash running pass 'Frontend instrumentation-based coverage lowering' on module llvm\lib\Support\Parallel.cpp

### ISSUE THREAD

**Issue by 0259615b-abec-4dfe-b850-7b4af5f8b6b0** [llvm/llvm-project#44151]
|  |  |
| --- | --- |
| Bugzilla Link | [44806](https://llvm.org/bz44806) |
| Version | 10.0 |
| OS | Windows NT |
| Attachments | [.sh .cpp .dmp files](https://user-images.githubusercontent.com/93435949/143760341-be1c59cf-3775-4431-8f52-7f5ec188c2f9.gz) |
| CC | @Ivan171,@zygoloid,@rnk |

## Extended Description 

Assertion failed: !NodePtr->isKnownSentinel(), file llvm\include\llvm/ADT/ilist_iterator.h, line 139

when LLVM_BUILD_INSTRUMENTED:STRING=IR

**Comment by Endilll** [comment]
Appears to be fixed in Clang 11: https://godbolt.org/z/bfW75Tevs
Reduced by me and C-Reduce:
```cpp
void construct();

void emplace_back() try {
  construct();
} catch (...) {
  throw;
}

void foo() {
  for (;;)
    emplace_back();
}
```
