### ISSUE TITLE
Add support for GFX1010

### ISSUE THREAD

**Issue by FFY00** [llvm/llvm-project#44186]
|  |  |
| --- | --- |
| Bugzilla Link | [44841](https://llvm.org/bz44841) |
| Version | unspecified |
| OS | Linux |
| CC | @tstellar,@zboszor |

## Extended Description 
Hello, would it be possible to add support for GFX1010 (NAVI10)? Is there anything blocking it? What are the first steps?

**Comment by terminatorul** [comment]
I tried the linking gfx909 to tahiti for my Radeon Graphics (Vega 8) iGPU for Ryzen 7 5700G, and Mesa-libOpenCL (Clover) only appeared to work, but not really.

Luxball scene in LuxMark v3.1 never showed up, and my desktop session crashed and I had to login again. Trying again LuxMark crashed with a strange error "CS (-1) was rejected, but it is not stable".
OpenSUSE Tumbleweed 20230313, Mesa 23.0.0

**Comment by cezarlamann** [comment]
Hello everyone! I'm a noob using llvm for anything, and I'd like to use CLBlast with my AMD Renoir APU (R7-4700U GFX 909 GCN 5.1), which requires LLVM to support gfx909. What can we do to get this working?

**Comment by jayfoad** [comment]
This is a libclc issue. (That was obvious from the original bugzilla but got lost in the transition to github.)

**Comment by peci1** [comment]
Detailed debugging info added in https://github.com/llvm/llvm-project/issues/52665#issuecomment-1732658768 (for gfx909).

**Comment by tstellar** [comment]
> [Add alias symlinks for missing AMD gfx9 and gfx10 generations](https://user-images.githubusercontent.com/95090655/143760354-12cc9972-819d-435a-93d2-334a42924d9e.gz) Probably something like the attached patch should work. It did work on my Renoir based laptop by adding the gfx909 symlinks manually in Fedora 33 with LLVM 11. The patch was made against the LLVM 12 release branch but it's applicable to the main branch, too.

Could someone submit this patch as a pull request?

**Comment by lorn10** [comment]
A short addition. Even if we have 2024 and this topic is quite old it would probably still make sense to add some RDNA and GCN5 support in libclc.

I mean this especially in regard to the (as of early 2024) quite fluctuating stability of rusticl and also the "not so good" rust support of older distros like (K)Ubuntu 22.04 LTS. Ergo it may take quite some time until rusticl (and the rust infrastructure) will be improved.

An updated libclc would enable also on more modern Radeon class hardware some sort of OpenCL support with clover.

I could try to make a merge or "pull" request with the [above mentioned patch](https://github.com/llvm/llvm-project/issues/44186#issuecomment-981024161) but I have unfortunately not really a clue what I would do. So for the first here follows a gently ping to @zboszor. :wink:

**Comment by zboszor** [comment]
> A short addition. Even if we have 2024 and this topic is quite old it would probably still make sense to add some RDNA and GCN5 support in libclc.
> 
> I mean this especially in regard to the (as of early 2024) quite fluctuating stability of rusticl and also the "not so good" rust support of older distros like (K)Ubuntu 22.04 LTS. Ergo it may take quite some time until rusticl (and the rust infrastructure) will be improved.
> 
> An updated libclc would enable also on more modern Radeon class hardware some sort of OpenCL support with clover.
> 
> I could try to make a merge or "pull" request with the [above mentioned patch](https://github.com/llvm/llvm-project/issues/44186#issuecomment-981024161) but I have unfortunately not really a clue what I would do. So for the first here follows a gently ping to @zboszor. 😉

Thanks for reminding me, I wasn't following this bug.

The patch is now submitted as https://github.com/llvm/llvm-project/pull/78884 , with a slightly modified commit title because it can be extended with newer AMD chip generations supported by LLVM today.
