### ISSUE TITLE
Illegal Instruction on startup from gn if built with clang on armv7hnl-linux

### ISSUE THREAD

**Issue by berolinux** [llvm/llvm-project#44201]
|  |  |
| --- | --- |
| Bugzilla Link | [44856](https://llvm.org/bz44856) |
| Version | 10.0 |
| OS | Linux |

## Extended Description 
Building gn (http://gn.googlesource.com/) with clang results in a crash on startup (Illegal Instruction) on armv7hnl.
It works on any other architecture and on armv7hnl with gcc instead of clang.

To reproduce (no reduced test case yet):

git clone https://gn.googlesource.com/gn
cd gn
export CC=clang
export CXX=clang++
python build/gen.py --no-static-libstdc++
ninja -C out
out/gn_unittests

[Illegal Instruction on armv7hnl, success everywhere else]

git clone https://gn.googlesource.com/gn
cd gn
export CC=gcc
export CXX=g++
python build/gen.py --no-static-libstdc++
ninja -C out
out/gn_unittests

[works]

**Comment by Endilll** [comment]
@berolinux Do you still experience this issue with recent versions of Clang?

**Comment by Endilll** [comment]
Author hasn't got back to us.
