### ISSUE TITLE
C++ compiler pretends to support C++11 but does not have <cuchar>

### ISSUE THREAD

**Issue by bhaible** [llvm/llvm-project#44216]
|  |  |
| --- | --- |
| Bugzilla Link | [44871](https://llvm.org/bz44871) |
| Version | 6.0 |
| OS | FreeBSD |
| Attachments | [test case](https://user-images.githubusercontent.com/95090629/143760364-35847038-5f72-4022-821a-f2265bf36b48.gz) |
| CC | @ldionne,@mclow |

## Extended Description 

Originally reported at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=244035.
The FreeBSD people told me to report it here.

C++11 added the header file <cuchar> (a wrapper around the C header file <uchar.h>). See https://en.cppreference.com/w/cpp/header

$ cat foo.cc
#if __cplusplus >= 201103
#include <cuchar>
#endif

$ c++ -c foo.cc
foo.cc:2:10: fatal error: 'cuchar' file not found
#include <cuchar>
         ^~~~~~~~
1 error generated.

$ c++ --version
FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin

**Comment by ldionne** [comment]
Fixed by 311ff3917827131c20d4b8dac4ce0394a2351b94
