### ISSUE TITLE
[LinAlg][Standard] Consider moving copy and slice into standard dialect

### ISSUE THREAD

**Issue by sherhut** [llvm/llvm-project#44224]
|  |  |
| --- | --- |
| Bugzilla Link | [44879](https://llvm.org/bz44879) |
| Version | unspecified |
| OS | Linux |
| Blocks | llvm/llvm-project#44166  |
| CC | @joker-eph |

## Extended Description 
Copy and slice seem to be generally useful operations on tensors. 

We already use slice for lowering HLO reduce to GPU directly. It's semantics are also independent of linalg.

Copy would be a useful construct for example in memory promotion and it would avoid writing explicit loops to copy a memref into a new buffer. Copy's semantics are independent of linalg, so there is no good reason for it to live there. Also, standard already has dma versions.

**Comment by nicolasvasilache** [comment]
Sliced and diced in various ways over time, we now have a `memref` dialect.
