### ISSUE TITLE
modernize-use-default-member-init assertion failure for array with UseAssignment=1

### ISSUE THREAD

**Issue by pepsiman** [llvm/llvm-project#44230]
|  |  |
| --- | --- |
| Bugzilla Link | [44885](https://llvm.org/bz44885) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
$ cat array.cpp 

struct Foo {
  int a[10];

  Foo() : a() {}
};

$ bin/clang-tidy --checks=-*,modernize-use-default-member-init array.cpp --config="CheckOptions: [{ key: 'modernize-use-default-member-init.UseAssignment', value: 1}]"  -- -std=c++11
clang-tidy: llvm-project/clang/lib/AST/Type.cpp:2052: clang::Type::ScalarTypeKind clang::Type::getScalarTypeKind() const: Assertion `isScalarType()' failed.
Stack dump:
0.	Program arguments: bin/clang-tidy --checks=-*,modernize-use-default-member-init array.cpp --config=CheckOptions: [{ key: 'modernize-use-default-member-init.UseAssignment', value: 1}] -- -std=c++11 
1.	<eof> parser at end of file
 #&#8203;0 0x00007fda52e1643a llvm::sys::PrintStackTrace(llvm::raw_ostream&) llvm-project/llvm/lib/Support/Unix/Signals.inc:568:0
 #&#8203;1 0x00007fda52e13f24 llvm::sys::RunSignalHandlers() llvm-project/llvm/lib/Support/Signals.cpp:68:0
 #&#8203;2 0x00007fda52e149f5 SignalHandler(int) llvm-project/llvm/lib/Support/Unix/Signals.inc:396:0
 #&#8203;3 0x00007fda58af2f20 (/lib/x86_64-linux-gnu/libc.so.6+0x3ef20)
 #&#8203;4 0x00007fda58af2e97 raise /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #&#8203;5 0x00007fda58af4801 abort /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:81:0
 #&#8203;6 0x00007fda58ae439a __assert_fail_base /build/glibc-OTsEL5/glibc-2.27/assert/assert.c:89:0
 #&#8203;7 0x00007fda58ae4412 (/lib/x86_64-linux-gnu/libc.so.6+0x30412)
 #&#8203;8 0x00007fda58632ff6 llvm::isa_impl_wrap<clang::BuiltinType, clang::Type const*, clang::Type const*>::doit(clang::Type const* const&) llvm-project/clang/lib/AST/Type.cpp:2052:0
 #&#8203;9 0x00007fda58632ff6 llvm::isa_impl_wrap<clang::BuiltinType, clang::Type const* const, clang::Type const*>::doit(clang::Type const* const&) llvm-project/llvm/include/llvm/Support/Casting.h:123:0
#&#8203;10 0x00007fda58632ff6 bool llvm::isa<clang::BuiltinType, clang::Type const*>(clang::Type const* const&) llvm-project/llvm/include/llvm/Support/Casting.h:142:0
#&#8203;11 0x00007fda58632ff6 llvm::cast_retty<clang::BuiltinType, clang::Type const*>::ret_type llvm::dyn_cast<clang::BuiltinType, clang::Type const>(clang::Type const*) llvm-project/llvm/include/llvm/Support/Casting.h:339:0
#&#8203;12 0x00007fda58632ff6 clang::Type::getScalarTypeKind() const llvm-project/clang/lib/AST/Type.cpp:2055:0
#&#8203;13 0x00007fda550e7e66 clang::tidy::modernize::getValueOfValueInit(clang::QualType) llvm-project/clang-tools-extra/clang-tidy/modernize/UseDefaultMemberInitCheck.cpp:21:0
#&#8203;14 0x00007fda550e8912 llvm::StringRef::str[abi:cxx11]() const llvm-project/llvm/include/llvm/ADT/StringRef.h:249:0
#&#8203;15 0x00007fda550e8912 _ZNK4llvm9StringRefcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv llvm-project/llvm/include/llvm/ADT/StringRef.h:275:0
#&#8203;16 0x00007fda550e8912 clang::FixItHint::CreateInsertion(clang::SourceLocation, llvm::StringRef, bool) llvm-project/clang/include/clang/Basic/Diagnostic.h:98:0
#&#8203;17 0x00007fda550e8912 clang::tidy::modernize::UseDefaultMemberInitCheck::checkDefaultInit(clang::ast_matchers::MatchFinder::MatchResult const&, clang::CXXCtorInitializer const*) llvm-project/clang-tools-extra/clang-tidy/modernize/UseDefaultMemberInitCheck.cpp:268:0

**Comment by carlosgalvezp** [comment]
Assertion no longer happening on latest trunk. Please open a new ticket about wrong suggestion.
