### ISSUE TITLE
[AMDGPU][MC][GFX908] dot opcodes operating 4-bit and 8-bit packed data should not support op_sel

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#44257]
|  |  |
| --- | --- |
| Bugzilla Link | [44912](https://llvm.org/bz44912) |
| Version | trunk |
| OS | Windows NT |
| CC | @atamazov,@arsenm,@rampitec |

## Extended Description 
dot opcodes that have packed data smaller than 16 bits should not allow op_sel/op_sel_hi modifiers. This is confirmed by Justin Smith.

Examples of failed tests:

    v_dot4_u32_u8 v0, v1, v2, v3 op_sel:[1,1]
    v_dot8_i32_i4 v0, v1, v2, v3 op_sel_hi:[1,1]

**Comment by jwanggit86** [comment]
According to ISA document, this is what v_dot4_u32_u8 does:
```
tmp = S2.i32;
tmp += i8_to_i32(S0[7 : 0].i8) * i8_to_i32(S1[7 : 0].i8);
tmp += i8_to_i32(S0[15 : 8].i8) * i8_to_i32(S1[15 : 8].i8);
tmp += i8_to_i32(S0[23 : 16].i8) * i8_to_i32(S1[23 : 16].i8);
tmp += i8_to_i32(S0[31 : 24].i8) * i8_to_i32(S1[31 : 24].i8);
D0.i32 = tmp
```
All the 4 bytes of both src0 and src1 are used. So it seems `op_sel` is indeed superfluous for this instruction. Same for v_dot8.

**Comment by arsenm** [comment]
> According to ISA document, this is what v_dot4_u32_u8 does:
> 
> ```
> tmp = S2.i32;
> tmp += i8_to_i32(S0[7 : 0].i8) * i8_to_i32(S1[7 : 0].i8);
> tmp += i8_to_i32(S0[15 : 8].i8) * i8_to_i32(S1[15 : 8].i8);
> tmp += i8_to_i32(S0[23 : 16].i8) * i8_to_i32(S1[23 : 16].i8);
> tmp += i8_to_i32(S0[31 : 24].i8) * i8_to_i32(S1[31 : 24].i8);
> D0.i32 = tmp
> ```
> 
> All the 4 bytes of both src0 and src1 are used. So it seems `op_sel` is indeed superfluous for this instruction. Same for v_dot8.

Should cross check that, the pseudocode documentation for these kinds of cases often misses mentioning the modifiers

**Comment by jwanggit86** [comment]
Closed by PR 100485.
