### ISSUE TITLE
Spaces between type and variable name in IIFE lambda in brace init removed by formatter

### ISSUE THREAD

**Issue by b7ee91ce-b3af-4553-b4dc-742288cf1e5a** [llvm/llvm-project#44292]
|  |  |
| --- | --- |
| Bugzilla Link | [44947](https://llvm.org/bz44947) |
| Version | 9.0 |
| OS | Linux |
| CC | @w-m,@mydeveloperday |

## Extended Description 
The following code

```
int foo {[]() {
  int bar{ 0 };
  return 0;
}()};
```

is formatted into

```
int foo{ []() {
  intbar{ 0 };
  return 0;
}() };
```

by clang-format-9 when using -style="{AlignConsecutiveDeclarations: true, Cpp11BracedListStyle: false}".

The resulting code no longer compiles - note the missing space between `int` and the variable name.

Changing either formatting option will fix the problem, it's the combination that leads to the erroneous output.

The code is also correctly formatted if the outer braces (initialization of foo) are replaced by a `=` assignment.

I don't have a later clang-format version than 9 installed locally, but trying this code snippet in https://zed0.co.uk/clang-format-configurator with 10.0.0+b452de0 and these two formatting options, the output suddenly gets blank (-> crash?).

**Comment by mkurdej** [comment]
Broken between v4 and v5:
```
"d:\Program Files\LLVM-4.0.1\bin\clang-format.exe" -style=file test.cpp
const auto result{ []() {
  const auto something = 1;
  return 2;
} };

int foo{ []() {
  int bar{ 0 };
  return 0;
}() };

"d:\Program Files\LLVM-5.0.2\bin\clang-format.exe" -style=file test.cpp
const auto result{ []() {
  const autosomething = 1;
  return 2;
} };

int foo{ []() {
  intbar{ 0 };
  return 0;
}() };
```

**Comment by mkurdej** [comment]
Revision URI: https://reviews.llvm.org/D119419
