### ISSUE TITLE
Ubuntu installer script (llvm.sh) does not work for clang-10 on eoan

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#44311]
|  |  |
| --- | --- |
| Bugzilla Link | [44966](https://llvm.org/bz44966) |
| Version | 10.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @gregbedwell,@MaskRay |

## Extended Description 
Current llvm.sh script assumes version 10 is the default version. Version 11 is the default version.

> wget https://apt.llvm.org/llvm.sh
> chmod +x llvm.sh
> sudo ./llvm.sh 10

On eoan, the above installs the default repository:

> REPO_NAME="deb http://apt.llvm.org/eoan/ llvm-toolchain-eoan main"

And then subsequently tries to install clang-10, et al, and fail with:

> E: Unable to locate package clang-10

I fix this with the following stanza:

> sed -i'' 's/LLVM_VERSION_PATTERNS\[10\]=""/LLVM_VERSION_PATTERNS\[10\]="-10"\nLLVM_VERSION_PATTERNS\[11\]=""/' llvm.sh

**Comment by sylvestre** [comment]
it is now fixed
