### ISSUE TITLE
Not able to disable CUDA offloading

### ISSUE THREAD

**Issue by Flamefire** [llvm/llvm-project#44316]
|  |  |
| --- | --- |
| Bugzilla Link | [44971](https://llvm.org/bz44971) |
| Version | trunk |
| OS | All |
| CC | @bryanpkc |

## Extended Description 
The CMake build system only allows to enable or disable the OpenMP target offloading completely via OPENMP_ENABLE_LIBOMPTARGET. But it is not possible to disable a specific backend, e.g. CUDA. If CMake finds CUDA it will be enabled even if the CUDA found is not what is wanted. This may lead to e.g. llvm/llvm-project#38736 

--> There should be an option to disable specific backends, at least once that require some external dependency (e.g CUDA)

**Comment by shiltian** [comment]
This is no longer an issue.
