### ISSUE TITLE
Please backport D70662 : Fix sanitizer-common build with glibc 2.31

### ISSUE THREAD

**Issue by c6238aa9-e28b-4a2e-9256-1883efbde648** [llvm/llvm-project#44330]
|  |  |
| --- | --- |
| Bugzilla Link | [44985](https://llvm.org/bz44985) |
| Version | 8.0 |
| OS | Linux |

## Extended Description 
Please backport the fix to llvm-8 series.

**Comment by arsenm** [comment]
Old release
