### ISSUE TITLE
A newline is added after a string token if the next 2 tokens are lessless and string

### ISSUE THREAD

**Issue by JvdGlind** [llvm/llvm-project#44363]
|  |  |
| --- | --- |
| Bugzilla Link | [45018](https://llvm.org/bz45018) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [File to verify two streamed strings aren't split](https://user-images.githubusercontent.com/92601663/143760409-3d77f355-57f2-49dd-be1d-0dee0cdad6e7.gz) |

## Extended Description 

Given the code:

 QStringList() << "something" << "something" << variable;

If I then run clang-format with the default config file, the output is the following code:

 QStringList() << "something"
               << "something" << variable

What I expected, was that it stays on a single line, unless it exceeds the column limit and possible penalties. In this case, untouched.

It stays untouched when I add a variable in between:

 QStringList() << "something" << a << "something" << variable;

Looking at the code, I noticed that somebody intentionally introduced this to split endline characters in commit df28f7b8dd6a032515109de4ff5b4067be95da8e (currently at lib/Format/TokenAnnotator.cpp, line 3073).

In the attachment I added a file with a slightly different example that I used when debugging clang-format.

**Comment by dan-42** [comment]
Using LLVM 15.0.0 on Windows we have a similar issue.
We use the `operator<<` for collecting `sigslot_connection` when calling `connect(sigslot_slot)` in our `sigslot` library
code looks like this:

```cpp
connection_store_ 
  << some_module.signals().scanning_started.connect(
     [this]()
     { 
        /*business logic*/
     })
  << some_module.signals().scanning_finished.connect(
    [this](...)
    {
      /*business logic*/
    }
    });
```

Clang-format does this:

```cpp
connection_store_ << some_module.signals().on_started.connect(
                         [this]()
                         { 
                            /*business logic*/
                         })

                    << some_module.signals().on_finished.connect(
                         [this](...)
                         {
                            /*business logic*/
                         }
                          });
```

I suggest having an option allowing specific behaviour, something like

`BreakAfterStreamOperator: {Leave, Never, Always, FitLine, ...}`

Anyone else having issues in general with the stream operators? 
Is there any better suggestion?

**Comment by mohad12211** [comment]
same issue here, I agree with the above suggestion.

**Comment by owenca** [comment]
@dan-42, it seems that clang-format 17 formats your example alright although the indent of the comments are wrong, which you can open another issue for.
