### ISSUE TITLE
Make clang-format return with a certain status code if file needs replacements

### ISSUE THREAD

**Issue by efa41be3-5b15-484e-b29c-bb63fbb25564** [llvm/llvm-project#44373]
|  |  |
| --- | --- |
| Bugzilla Link | [45028](https://llvm.org/bz45028) |
| Version | unspecified |
| OS | Windows NT |

## Extended Description 
In a CI environment it would be helpful to make clang-format return a certain status code if a file needs replacements to adhere to the specified config.

**Comment by mydeveloperday** [comment]
This was resolved when we added the -n -Werror

```
$ clang-format -n -Werror test.cpp
test.cpp:1:8: error: code should be clang-formatted [-Wclang-format-violations]
int a =0;
       ^
```
```
$ echo $?
1

```
now do

`clang-format -i test.cpp`

and then again

`clang-format -n -Werror test.cpp`

now

```
$ echo $?
0

```
