### ISSUE TITLE
fast math flags on fcmp scalarizes on aarch64

### ISSUE THREAD

**Issue by 396654f8-e5cc-49eb-a353-c33e3c616b71** [llvm/llvm-project#44381]
|  |  |
| --- | --- |
| Bugzilla Link | [45036](https://llvm.org/bz45036) |
| Version | trunk |
| OS | Linux |
| Attachments | [ll that demonstrates the problem](https://user-images.githubusercontent.com/92601439/143760422-3a82a244-7872-4076-bb60-582fb25e2468.gz) |
| CC | @Arnaud-de-Grandmaison-ARM,@smithp35,@rotateright,@steven-johnson |

## Extended Description 

Any fast math flags on an fcmp seem to cause the aarch64 backend to emit a sequence of scalar fcmp instructions instead of a single vector fcmgt instruction.

The following ll shows the same comparison, with and without a fast math flag. I turned them all on, but it seems that any fast math flag will do.
```
define <4 x i1> @good(<4 x float> %a, <4 x float> %b) {
  %c = fcmp olt <4 x float> %a, %b
  ret <4 x i1> %c
}

define <4 x i1> @bad(<4 x float> %a, <4 x float> %b) {
  %c = fcmp fast olt <4 x float> %a, %b
  ret <4 x i1> %c
}
```
Output from llc -march=aarch64 -filetype=asm fcmgt.ll  -o -

```
good:  
	fcmgt	v0.4s, v1.4s, v0.4s
	xtn	v0.4h, v0.4s
	ret

...

bad:
	mov	s2, v1.s[1]
	mov	s3, v0.s[1]
	fcmp	s3, s2
	csetm	w8, lt
	fcmp	s0, s1
	mov	s4, v1.s[2]
	mov	s2, v0.s[2]
	csetm	w9, lt
	mov	s3, v1.s[3]
	mov	s0, v0.s[3]
	fcmp	s2, s4
	fmov	s1, w9
	csetm	w9, lt
	fcmp	s0, s3
	mov	v1.s[1], w8
	mov	v1.s[2], w9
	csetm	w8, lt
	mov	v1.s[3], w8
	xtn	v0.4h, v1.4s
	ret
```

**Comment by davemgreen** [comment]
The AArch64 backend is relying on the "no-nans-fp-math" target option, where it should be using the instruction fast-math-flags:
https://godbolt.org/z/b9WaP8hEn

The flags might also not be being propagated correctly through all setcc combines.

**Comment by corona10** [comment]
@davemgreen  From the latest commit, I can not reproduce this issue.
Can we close this issue?

`````

corona10@CPython-Ubuntu:~/llvm_build$ bin/llc -march=aarch64 -filetype=asm gh-44381.ll -o -
	.text
	.file	"gh-44381.ll"
	.globl	good                            // -- Begin function good
	.p2align	2
	.type	good,@function
good:                                   // @good
	.cfi_startproc
// %bb.0:
	fcmgt	v0.4s, v1.4s, v0.4s
	xtn	v0.4h, v0.4s
	ret
.Lfunc_end0:
	.size	good, .Lfunc_end0-good
	.cfi_endproc
                                        // -- End function
	.globl	bad                             // -- Begin function bad
	.p2align	2
	.type	bad,@function
bad:                                    // @bad
	.cfi_startproc
// %bb.0:
	fcmgt	v0.4s, v1.4s, v0.4s
	xtn	v0.4h, v0.4s
	ret
.Lfunc_end1:
	.size	bad, .Lfunc_end1-bad
	.cfi_endproc
                                        // -- End function
	.section	".note.GNU-stack","",@progbits
`````

**Comment by corona10** [comment]
Or if we need to add test to close this issue, I would like to submit the patch.

**Comment by davemgreen** [comment]
Hello - yeah I agree. It looks like this was fixed in https://reviews.llvm.org/D130093.

I think we can close it, it looks like it's already done.
