### ISSUE TITLE
Please support configurable position for Java static imports

### ISSUE THREAD

**Issue by ed099df3-f406-4a5c-bafa-3cee39096f87** [llvm/llvm-project#44401]
|  |  |
| --- | --- |
| Bugzilla Link | [45056](https://llvm.org/bz45056) |
| Version | 9.0 |
| OS | All |

## Extended Description 
In the documentation ( https://clang.llvm.org/docs/ClangFormatStyleOptions.html ), the "JavaImportGroups" rule specifies that the static imports are always above regular imports. So clang-format does this:

```
// first the static
import static something.Something.hello;

// then the regular
import something.SomethingElse;
```

It would be great if this behavior is configurable with a new option like JavaStaticImportsPosition: top|bottom, by default top for backwards compatibility and if set to bottom it should swap the order to:

```
// first the regular
import something.SomethingElse;

// then the static
import static something.Something.hello;
```

**Comment by bc-lee** [comment]
I noticed this issue today, but I fixed it at https://reviews.llvm.org/D87201.
As of clang-format 12, this feature (SortJavaStaticImport) is supported.
