### ISSUE TITLE
spurious insuppressible conversion warning

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#44411]
|  |  |
| --- | --- |
| Bugzilla Link | [45066](https://llvm.org/bz45066) |
| Version | 9.0 |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 

```cpp
#include <iostream>

struct D;
struct B {
    virtual operator D() = 0;
};
struct D : B
{
    operator D() override { std::cout << "conv" << std::endl; return D(); }
};
.
int main()
{
    D obj;
    B& br = obj;
    (D)br; // calls D::operator D() through virtual dispatch
    return 0;
}
```

```console
$ clang++ -Wall -o vconv vconv.cpp
vconv.cpp:9:5: warning: conversion function converting 'D' to itself will never be used
    operator D() override { std::cout << "conv" << std::endl; return D(); }
    ^
1 warning generated.

$ ./vconv 
conv
```

The example above shows that the warning
is spurious. Converting to the same type
will indeed never use the conversion
operator. But the above case converts
from B to D, so the warning does not apply.
It may be quite difficult to check properly,
but in this particular example the "override"
keyword is a clear hint that it is going
to be used via the virtual dispatch.

Note that with gcc it is at least possible
to suppress that warning with -Wno-class-conversion.
But in clang it is persistent.

**Comment by shafik** [comment]
This looks fixed: https://godbolt.org/z/bbjGrsse7

via https://reviews.llvm.org/D78444
