### ISSUE TITLE
error recovery improvement for stmtexprs

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#4442]
|  |  |
| --- | --- |
| Bugzilla Link | [4070](https://llvm.org/bz4070) |
| Version | unspecified |
| OS | All |

## Extended Description 
In this example:
```c++
struct fooo {} ;
struct fooo x;

void test(void) {

  *({
    0;
    x/x;
    });
}
```
We emit two diagnostics: one about x/x (good) and one about "indirection requires a pointer operand".  The problem is that we correctly kill the expression tree for x/x, but that means that we build and return a  compound statement with just { 0; } and the stmt expr gets built with type int.  We should somehow propagate invalidity of the last statement in a stmt expr up into the stmt expr itself.

This came from llvm/llvm-project#4437 .

**Comment by philnik777** [comment]
This has been fixed in Clang 11: https://godbolt.org/z/o8axnbrd6
