### ISSUE TITLE
Segmentation fault in simple function call using O1 ~ Os

### ISSUE THREAD

**Issue by haoxintu** [llvm/llvm-project#44466]
|  |  |
| --- | --- |
| Bugzilla Link | [45121](https://llvm.org/bz45121) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@hfinkel,@zygoloid |

## Extended Description 
Hi, the test.c

#include <stdio.h>

void foo( ) {
while(1){} 
//do {}while(1); //crash
//for(;;); //crash
while(-1){}  // non-executed loop, but still crash
}
int main () {
    int size = 100;
    printf("size = %d\n", size);
    foo();
    return 0;
}

is a simple function call code. When I compiler is using `clang-6.0 -O1 test.c` (or O2, O3, and Os) and then `./a.out`, the output is 

size=100
size=100
Segmentation fault(code dumped).

The strange thing is that `printf` function executed twice and whatever loop I use in the function foo(), even a non-executed loop, it gets faults.

**Comment by fhahn** [comment]
Over the last few releases, multiple places in LLVM have been fixed to properly handle infinite loops. This should work as expected now, on current `main` the resulting binary runs an infinite loop: https://clang.godbolt.org/z/TonEasWfq
