### ISSUE TITLE
std::filebuf should allow use to FILE* to construct just like MSVC and GCC does

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#44473]
|  |  |
| --- | --- |
| Bugzilla Link | [45128](https://llvm.org/bz45128) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
Thank you!!!

**Comment by mordante** [comment]
This is not required by the Standard and nowadays we tend to avoid extensions.
