### ISSUE TITLE
`opt -view-cfg` can't handle function names with a slash

### ISSUE THREAD

**Issue by 47c5a6a5-52e6-42d6-b2cb-179836302a4b** [llvm/llvm-project#4447]
|  |  |
| --- | --- |
| Bugzilla Link | [4075](https://llvm.org/bz4075) |
| Version | 2.4 |
| OS | OpenBSD |

## Extended Description 
When invoking `opt -view-cfg` error messages will be printed for function names containing slashes. For example:

Writing '/tmp/llvm_JMwD7i/cfgInteger::oper/Integer[1].dot'... error opening file for writing!

I am assuming this is because a forward slash is the directory delimiter on UNIX file-systems.

Thanks

**Comment by JOE1994** [comment]
With LLVM 19 (at commit `0c90e8837a9e5f27985ccaf85120083db9e1b43e`),
Command `opt -p=view-cfg foo.ll` successfully generates a dot file from the following LLVM IR snippet:

```llvm
; foo.ll
define i32 @"sq/uare"(i32 %0) local_unnamed_addr {
  %2 = mul nsw i32 %0, %0
  ret i32 %2
}
```

`.dot` file was generated at `/tmp/cfg.sq_uare-c41f512.dot`
(slash character in the function name is taken care of when setting the `.dot` file's filename).

No further action seems necessary.
