### ISSUE TITLE
improve llvm-rc preprocessing

### ISSUE THREAD

**Issue by ff34a35c-d8dc-4285-9bc4-b2d01e34f06e** [llvm/llvm-project#44525]
|  |  |
| --- | --- |
| Bugzilla Link | [45180](https://llvm.org/bz45180) |
| Version | unspecified |
| OS | Windows NT |

## Extended Description 
1. support #include. seems only #include "winver.h" works.
2. support user defined macros
3. support #if #ifdef

**Comment by mstorsjo** [comment]
This should have been fixed since 64bc44f5ddfb6da4b6a8b51ea9a03f8772b3ae95 (LLVM 13.0.0).
