### ISSUE TITLE
concepts: constrained member functions illegally instantiated during explicit class template instantiation

### ISSUE THREAD

**Issue by 0acd4e0f-fb71-46f2-a106-6376379b1b59** [llvm/llvm-project#44549]
|  |  |
| --- | --- |
| Bugzilla Link | [45204](https://llvm.org/bz45204) |
| Version | 10.0 |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
The following correct C++20 program fails to compile in clang.

```
template <typename T>
concept has_a = requires(T v) { v.a(); };

template<typename T>
struct X
{
  void fun(T) {}
  void gun(T v) requires has_a<T> { v.a(); }
};

template struct X<int>; 
```
member function `gun()` is instantiated which is a bug according to http://eel.is/c++draft/temp.explicit#11

This works in the old experimental implementation of concepts in Clang by Saar Raz: https://godbolt.org/z/K4SaCm

**Comment by royjacobson** [comment]
Fixed in https://reviews.llvm.org/D120255
