### ISSUE TITLE
[regression] clang crashes in Sema/SemaType.cpp:5689

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#44595]
|  |  |
| --- | --- |
| Bugzilla Link | [45250](https://llvm.org/bz45250) |
| Version | 10.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
This is a test for fix for llvm/llvm-project#42660 . However crashes clang recently.
$ cat 1.cpp
#define a __attribute__((__cdecl__, __regparm__(0)))
int(a b)();

$ clang++ -c -std=c++2a 1.cpp

clang-9: /home/oscar/compiler/llvm-project/clang/lib/Sema/SemaType.cpp:5689: void {anonymous}::DeclaratorLocFiller::VisitFunctionTypeLoc(clang::FunctionTypeLoc): Assertion `Chunk.Kind == DeclaratorChunk::Function' failed.
Stack dump:
0.	Program arguments: /usr/local/bin/clang-9 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name 1.cpp -mrelocation-model static -mthread-model posix -mframe-pointer=all -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -resource-dir /usr/local/lib/clang/10.0.0 -internal-isystem /usr/local/bin/../lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0 -internal-isystem /usr/local/bin/../lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/x86_64-pc-linux-gnu -internal-isystem /usr/local/bin/../lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/backward -internal-isystem /usr/local/include -internal-isystem /usr/local/lib/clang/10.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /media/oscar/xuaner1/autogeneration/testsuitC++/compileinformation/clang-9.0..1-crash-testsuit/clang -ferror-limit 19 -fmessage-length 0 -fgnuc-version=4.2.1 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -faddrsig -o 1.o -x c++ 1.cpp 
1.	1.cpp:2:11: current parser token ';'
 #&#8203;0 0x000055fe5939105f llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/oscar/compiler/llvm-project/llvm/lib/Support/Unix/Signals.inc:544:0
 #&#8203;1 0x000055fe593910f2 PrintStackTraceSignalHandler(void*) /home/oscar/compiler/llvm-project/llvm/lib/Support/Unix/Signals.inc:605:0
 #&#8203;2 0x000055fe5938ef55 llvm::sys::RunSignalHandlers() /home/oscar/compiler/llvm-project/llvm/lib/Support/Signals.cpp:68:0
 #&#8203;3 0x000055fe593909ea SignalHandler(int) /home/oscar/compiler/llvm-project/llvm/lib/Support/Unix/Signals.inc:391:0
 #&#8203;4 0x00007f7e431cc890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)
 #&#8203;5 0x00007f7e422c4e97 raise (/lib/x86_64-linux-gnu/libc.so.6+0x3ee97)
 #&#8203;6 0x00007f7e422c6801 abort (/lib/x86_64-linux-gnu/libc.so.6+0x40801)
 #&#8203;7 0x00007f7e422b639a (/lib/x86_64-linux-gnu/libc.so.6+0x3039a)
 #&#8203;8 0x00007f7e422b6412 (/lib/x86_64-linux-gnu/libc.so.6+0x30412)
 #&#8203;9 0x000055fe5c98cfad (anonymous namespace)::DeclaratorLocFiller::VisitFunctionTypeLoc(clang::FunctionTypeLoc) /home/oscar/compiler/llvm-project/clang/lib/Sema/SemaType.cpp:5690:0
#&#8203;10 0x000055fe5c99a7c3 clang::TypeLocVisitor<(anonymous namespace)::DeclaratorLocFiller, void>::VisitFunctionProtoTypeLoc(clang::FunctionProtoTypeLoc) /home/oscar/compiler/llvm-project/build/tools/clang/include/clang/AST/TypeNodes.inc:44:0
#&#8203;11 0x000055fe5c998cd9 clang::TypeLocVisitor<(anonymous namespace)::DeclaratorLocFiller, void>::Visit(clang::UnqualTypeLoc) /home/oscar/compiler/llvm-project/build/tools/clang/include/clang/AST/TypeNodes.inc:44:0
#&#8203;12 0x000055fe5c98d7c7 GetTypeSourceInfoForDeclarator((anonymous namespace)::TypeProcessingState&, clang::QualType, clang::TypeSourceInfo*) /home/oscar/compiler/llvm-project/clang/lib/Sema/SemaType.cpp:5814:0
#&#8203;13 0x000055fe5c98b098 GetFullTypeForDeclarator((anonymous namespace)::TypeProcessingState&, clang::QualType, clang::TypeSourceInfo*) /home/oscar/compiler/llvm-project/clang/lib/Sema/SemaType.cpp:5278:0
#&#8203;14 0x000055fe5c98b1a9 clang::Sema::GetTypeForDeclarator(clang::Declarator&, clang::Scope*) /home/oscar/compiler/llvm-project/clang/lib/Sema/SemaType.cpp:5296:0
#&#8203;15 0x000055fe5bfc5be1 clang::Sema::HandleDeclarator(clang::Scope*, clang::Declarator&, llvm::MutableArrayRef<clang::TemplateParameterList*>) /home/oscar/compiler/llvm-project/clang/lib/Sema/SemaDecl.cpp:5615:0
#&#8203;16 0x000055fe5bfc4bb7 clang::Sema::ActOnDeclarator(clang::Scope*, clang::Declarator&) /home/oscar/compiler/llvm-project/clang/lib/Sema/SemaDecl.cpp:5403:0
#&#8203;17 0x000055fe5bd6927e clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) /home/oscar/compiler/llvm-project/clang/lib/Parse/ParseDecl.cpp:2281:0
#&#8203;18 0x000055fe5bd6890b clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) /home/oscar/compiler/llvm-project/clang/lib/Parse/ParseDecl.cpp:2126:0
#&#8203;19 0x000055fe5bd4a4c5 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) /home/oscar/compiler/llvm-project/clang/lib/Parse/Parser.cpp:1096:0
#&#8203;20 0x000055fe5bd4a59f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) /home/oscar/compiler/llvm-project/clang/lib/Parse/Parser.cpp:1111:0
#&#8203;21 0x000055fe5bd49aff clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) /home/oscar/compiler/llvm-project/clang/lib/Parse/Parser.cpp:931:0
#&#8203;22 0x000055fe5bd48d5c clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) /home/oscar/compiler/llvm-project/clang/lib/Parse/Parser.cpp:682:0
#&#8203;23 0x000055fe5bd487f7 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) /home/oscar/compiler/llvm-project/clang/lib/Parse/Parser.cpp:560:0
#&#8203;24 0x000055fe5bd44ade clang::ParseAST(clang::Sema&, bool, bool) /home/oscar/compiler/llvm-project/clang/lib/Parse/ParseAST.cpp:157:0
#&#8203;25 0x000055fe59e1433b clang::ASTFrontendAction::ExecuteAction() /home/oscar/compiler/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1042:0
#&#8203;26 0x000055fe5a6bdbe2 clang::CodeGenAction::ExecuteAction() /home/oscar/compiler/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:1089:0
#&#8203;27 0x000055fe59e13c9c clang::FrontendAction::Execute() /home/oscar/compiler/llvm-project/clang/lib/Frontend/FrontendAction.cpp:939:0
#&#8203;28 0x000055fe59dabf17 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/oscar/compiler/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:956:0
#&#8203;29 0x000055fe59f7ba9b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/oscar/compiler/llvm-project/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:290:0
#&#8203;30 0x000055fe56a680bf cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /home/oscar/compiler/llvm-project/clang/tools/driver/cc1_main.cpp:250:0
#&#8203;31 0x000055fe56a5d613 ExecuteCC1Tool(llvm::ArrayRef<char const*>, llvm::StringRef) /home/oscar/compiler/llvm-project/clang/tools/driver/driver.cpp:309:0
#&#8203;32 0x000055fe56a5dd09 main /home/oscar/compiler/llvm-project/clang/tools/driver/driver.cpp:382:0
#&#8203;33 0x00007f7e422a7b97 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b97)
#&#8203;34 0x000055fe56a5bdea _start (/usr/local/bin/clang-9+0x2b39dea)
clang-9: error: unable to execute command: Aborted (core dumped)
clang-9: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 10.0.0 (https://github.com/llvm/llvm-project.git 722b61892454b3217d73ec486e52156c5a92b5b3)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
clang-9: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-9: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-9: note: diagnostic msg: /tmp/1-7bfe14.cpp
clang-9: note: diagnostic msg: /tmp/1-7bfe14.sh
clang-9: note: diagnostic msg: 

********************

**Comment by shafik** [comment]
Looks like it was fixed in clang-10: https://godbolt.org/z/zMWGojYob
