### ISSUE TITLE
Formatting damages friend declaration for specialization of operator function template

### ISSUE THREAD

**Issue by CaseyCarter** [llvm/llvm-project#44601]
|  |  |
| --- | --- |
| Bugzilla Link | [45256](https://llvm.org/bz45256) |
| Version | 10.0 |
| OS | Windows NT |
| Attachments | [Minimal repro](https://user-images.githubusercontent.com/456873/143760510-92646452-0a2b-4233-a9aa-2655fb87ed85.gz) |

## Extended Description 

Formatting this C++ program with clang-format (i.e., using the default style):

```
  template <class> class S;

  template <class T> bool operator<(S<T> const &x, S<T> const &y) {
    return x.i < y.i;
  }

  template <class T> class S {
    int i = 42;
    friend bool operator< <>(S const &, S const &);
  };

  int main() { return S{} < S{}; }
```

Transforms the well-formed friend declaration into the ill-formed:

    friend bool operator<<>(S const &, S const &);

**Comment by mydeveloperday** [comment]
Notes for anyone looking at this...

`tryMergeLessLess()` seems to merge <<> into a sequence `{ tok::lessless, tok::greater }`

The logic here would need to be corrected first I assume.

Then look towards spaceRequiredBefore(), this is a large function with lots of 

```
if (Style.isCpp())
else if (Style.isJava())
else if (Style.isJavaScript())
else {}
```

type code, don't make the same mistake I keep making and put it in the wrong language section!

**Comment by pjessesco** [comment]
I submitted a patch in https://reviews.llvm.org/D117398

**Comment by mkurdej** [comment]
Review: https://reviews.llvm.org/D117398.

**Comment by mkurdej** [comment]
Duplicate of #30118. But I'll close the other one as we have an almost ready patch.
