### ISSUE TITLE
symbol in explicit section with the same name crashes clang

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#44611]
|  |  |
| --- | --- |
| Bugzilla Link | [45266](https://llvm.org/bz45266) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@zygoloid,@stephenhines |

## Extended Description 
__attribute__((section("foo")))
void foo(void) {}

crashes clang: error in backend: 'foo' label emitted multiple times to assembly file

Not high priority; I don't have real code that uses this, but messing around in godbolt, I noticed this crashed clang but not GCC.

**Comment by Endilll** [comment]
Appears to be properly diagnosed since Clang 13: https://godbolt.org/z/drKMYrhc1
