### ISSUE TITLE
[arm64] Missed optimizations in __int128_t comparisons

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#44629]
|  |  |
| --- | --- |
| Bugzilla Link | [45284](https://llvm.org/bz45284) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @Arnaud-de-Grandmaison-ARM,@efriedma-quic,@fhahn,@smithp35 |

## Extended Description 
void doit(void);
void test(unsigned long addr, unsigned long size, unsigned long limit)
{
    if ((__uint128_t)addr + size <= (__uint128_t)limit + 1) doit();
}

with HEAD (85c30f3374d9), compiles to

        adds    x8, x1, x0
        adcs    x9, xzr, xzr
        adds    x10, x2, #&#8203;1
        adcs    x11, xzr, xzr
        cmp     x8, x10                 // comparison start
        cset    w8, hi
        cmp     x9, x11
        cset    w9, hi
        csel    w8, w8, w9, eq          // comparison end
        tbz     w8, #&#8203;0, .LBB1_2

The comparison can be done with

        cmp     x8, x10
        sbcs    xzr, x9, x11
        b.cs    .LBB1_2

a reduction of 3 insns.

**Comment by fzhinkin** [comment]
I'd like to take care of this issue if no one minds.

**Comment by fzhinkin** [comment]
https://reviews.llvm.org/D135302

**Comment by fzhinkin** [comment]
Fixed: https://github.com/llvm/llvm-project/commit/ef774bec63b72a0e900b3ddf22da81efbecd99a9
