### ISSUE TITLE
Infinite loop in SplitCriticalSideEffectEdges

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#44635]
|  |  |
| --- | --- |
| Bugzilla Link | [45290](https://llvm.org/bz45290) |
| Version | trunk |
| OS | Linux |
| Attachments | [bbi-40381_x86.ll reproducer](https://user-images.githubusercontent.com/55733087/143760524-2beb91f4-9f47-463a-aae6-13c0566c6db5.gz) |
| CC | @topperc |

## Extended Description 

Reproduce with:
 llc -O0 -mtriple=x86_64-unknown-linux-gnu -o - bbi-40381_x86.ll

With -debug -debug-Pass=Executions the last thing we see is

[2020-03-24 13:58:41.006703848] 0x60aee00     Executing Pass 'X86 DAG->DAG Instruction Selection' on Function 'f26'...

=== f26

Running in the debugger we see that we're stuck in the loop in SplitCriticalSideEffectEdges in SelectionDAGISel.cpp:

static void SplitCriticalSideEffectEdges(Function &Fn, DominatorTree *DT,
                                         LoopInfo *LI) {
  // Loop for blocks with phi nodes.
  for (BasicBlock &BB : Fn) {
    PHINode *PN = dyn_cast<PHINode>(BB.begin());
    if (!PN) continue;

  ReprocessBlock:
    // For each block with a PHI node, check to see if any of the input values
    // are potentially trapping constant expressions.  Constant expressions are
    // the only potentially trapping value that can occur as the argument to a
    // PHI.
    for (BasicBlock::iterator I = BB.begin(); (PN = dyn_cast<PHINode>(I)); ++I)
      for (unsigned i = 0, e = PN->getNumIncomingValues(); i != e; ++i) {
        ConstantExpr *CE = dyn_cast<ConstantExpr>(PN->getIncomingValue(i));
        if (!CE || !CE->canTrap()) continue;

        // The only case we have to worry about is when the edge is critical.
        // Since this block has a PHI Node, we assume it has multiple input
        // edges: check to see if the pred has multiple successors.
        BasicBlock *Pred = PN->getIncomingBlock(i);
        if (Pred->getTerminator()->getNumSuccessors() == 1)
          continue;

        // Okay, we have to split this edge.
        SplitCriticalEdge(
            Pred->getTerminator(), GetSuccessorNumber(Pred, &BB),
            CriticalEdgeSplittingOptions(DT, LI).setMergeIdenticalEdges());
        goto ReprocessBlock;
      }
  }
}

The problem in this case is because BB has only one predecessor, so SplitCriticalEdge bails out early and does nothing and we're stuck.

**Comment by fhahn** [comment]
Still hangs: https://llvm.godbolt.org/z/f5Mh1MYex

**Comment by nikic** [comment]
This is resolved with the removal of trapping constant expressions (and thus the need to split critical edges).
