### ISSUE TITLE
AllowShortIfStatementsOnASingleLine: WithoutElse broken

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#44683]
|  |  |
| --- | --- |
| Bugzilla Link | [45338](https://llvm.org/bz45338) |
| Version | trunk |
| OS | Linux |
| Attachments | [FormatTest.FormatIfWithoutCompoundStatementButElseWith failure](https://user-images.githubusercontent.com/60944935/143760532-44e0a7ce-3768-4eda-b9a3-b5f3121992d5.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mydeveloperday |

## Extended Description 
```
$ cat test.cpp
int main() {

if (true) { function(); }

if (true) function();

if (true) { function(); } else function();

if (true) { function(); } else { function(); }

if (true) function(); else function();

if (true) function(); else { function(); }

}
```
```
$ clang-format test.cpp -style="{BasedOnStyle: google, BreakBeforeBraces: Allman, AllowShortBlocksOnASingleLine: Always, AllowShortIfStatementsOnASingleLine: WithoutElse}"
int main()
{
  if (true) { function(); }

  if (true) function();

  if (true) { function(); }
  else
    function();

  if (true) { function(); }
  else
  {
    function();
  }

  if (true)
    function();
  else
    function();

  if (true)
    function();
  else
  {
    function();
  }
}
```

According to the clang-format 11 documentation, `AllowShortIfStatementsOnASingleLine: WithoutElse` means the following: "Without else put short ifs on the same line only if the else is not a compound statement.". So the expected result should be:
```
$ clang-format test.cpp -style="{BasedOnStyle: google, BreakBeforeBraces: Allman, AllowShortBlocksOnASingleLine: Always, AllowShortIfStatementsOnASingleLine: WithoutElse}"
int main()
{
  if (true) { function(); }

  if (true) function();

  if (true) { function(); }
  else
    function();

  if (true)
  {
    function();
  }
  else
  {
    function();
  }

  if (true) function();
  else
    function();

  if (true)
    function();
  else
  {
    function();
  }
}
```

I don't use `BreakBeforeBraces: Attach` but it seems broken too:
```
$ ../bin/clang-format test.cpp -style="{BasedOnStyle: google, BreakBeforeBraces: Attach, AllowShortBlocksOnASingleLine: Always, AllowShortIfStatementsOnASingleLine: WithoutElse}"
int main() {
  if (true) { function(); }

  if (true) function();

  if (true) {
    function();
  } else
    function();

  if (true) {
    function();
  } else {
    function();
  }

  if (true)
    function();
  else
    function();

  if (true)
    function();
  else {
    function();
  }
}
```

Might be related to bug 25010 (#25010 ) but I'm not sure.

**Comment by mkurdej** [comment]
Closing as the documentation has been fixed ("SIS_WithoutElse (in configuration: WithoutElse) Put short ifs on the same line only if there is no else statement.") and new options has been added to `AllowShortIfStatementsOnASingleLine`. To obtain what you expected, you should use `AllowShortIfStatementsOnASingleLine: AllIfsAndElse`.

Cf. commit 8d93d7ffedebc5f18dee22ba954d38a1d2d0affa (https://reviews.llvm.org/D100727).
