### ISSUE TITLE
bare identifier parse error when colliding with int/float types

### ISSUE THREAD

**Issue by bondhugula** [llvm/llvm-project#44731]
|  |  |
| --- | --- |
| Bugzilla Link | [45386](https://llvm.org/bz45386) |
| Version | unspecified |
| OS | Linux |
| CC | @jpienaar,@River707 |

## Extended Description 
The parser can't parse bare identifiers like 'i<number>' in affine maps and sets, and similarly ids like f16/f32. But these bare ids are part of the grammar - although they are also primitive types.

$ echo "#map = affine_map<(i0) -> (i0)>" | mlir-opt 
<stdin>:1:20: error: expected bare identifier
#map = affine_map<(i0) -> (i0)>
                   ^

**Comment by Groverkss** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/aab7e2fa05c0ad9bc8ffb40f058512d41d980135
