### ISSUE TITLE
Assertion `getNumOperands() == 2 && "Must be binary operator?"' failed

### ISSUE THREAD

**Issue by BalaRishi-AMD** [llvm/llvm-project#44771]
|  |  |
| --- | --- |
| Bugzilla Link | [45426](https://llvm.org/bz45426) |
| Version | unspecified |
| OS | Linux |
| CC | @DougGregor,@fhahn,@tambry,@zygoloid |

## Extended Description 
The below issue was not seen before October, 2019.

$ cat test.c
int a[], b;
float *c;
int  main() {
        return  -(*c = &b != a);
}

$ clang -c test.c
test.c:1:5: warning: tentative array definition assumed to have one element
int a[], b;
    ^
clang: /home/compiler/llvm-project/llvm/lib/IR/Constants.cpp:1365: llvm::Constant* llvm::ConstantExpr::getWithOperands(llvm::ArrayRef<llvm::Constant*>, llvm::Type*, bool, llvm::Type*) const: Assertion `getNumOperands() == 2 && "Must be binary operator?"' failed.

**Comment by AaronBallman** [comment]
Fixed by bc72a3ab949e14b990c080985fc1e74475f1e7d2
