### ISSUE TITLE
clang-format - placement of maybe_unused token

### ISSUE THREAD

**Issue by e557ce63-ca52-4d25-bd1f-a093d0a56ffd** [llvm/llvm-project#44772]
|  |  |
| --- | --- |
| Bugzilla Link | [45427](https://llvm.org/bz45427) |
| Version | unspecified |
| OS | All |
| Attachments | [The clang-format file that ca](https://user-images.githubusercontent.com/93435922/143760558-fb576145-b84c-492c-9e6b-ee862ad6bd3c.gz) |

## Extended Description 

When running clang-format with a column limit of 80 and AllowAllParametersOfDeclarationOnNextLine set to true, the first opening token of the [[maybe_unused]] attribute will be left on the first line

Example:

class ExampleOfError {
  void DoSomethingUseful([[maybe_unused]] float thisIsAParameterThatGetsSplit);
};

Before:

    void ExampleOfError::DoSomethingUseful([[maybe_unused]] float thisIsAParameterThatGetsSplit) {}

After:

    void ExampleOfError::DoSomethingUseful([
        [maybe_unused]] float thisIsAParameterThatGetsSplit) {}

**Comment by rymiel** [comment]
This appears to be fixed by 5a4ddbd69db2b0e09398214510501d0e59a0c30b
