### ISSUE TITLE
Remove -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang

### ISSUE THREAD

**Issue by kees** [llvm/llvm-project#44842]
|  |  |
| --- | --- |
| Bugzilla Link | [45497](https://llvm.org/bz45497) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie,@DougGregor,@ramosian-glider,@kcc,@jfbastien,@MattPD,@zygoloid,@seanm,@stephenhines,@TNorthover |

## Extended Description 
Using -ftrivial-auto-var-init=zero is preferred by the Linux kernel for both semantics and performance.

It's worth noting that Linus Torvalds would very much like to see zero-init be a by-default change to how the Linux kernel's C "dialect" behaves:
https://lore.kernel.org/lkml/CAHk-=wgTM+cN7zyUZacGQDv3DuuoA4LORNPWgb1Y_Z1p4iedNQ@mail.gmail.com/
"So I'd like the zeroing of local variables to be a native compiler option..."
"This, btw, is why I also think that the "initialize with poison" is
pointless and wrong."

The performance issue is also very real (as noted in the thread above too). Zero init is faster, and for making such a large change to the kernel, we want to more efficient option. Can we please remove -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang ?

**Comment by AaronBallman** [comment]
Two years have passed and `-enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang` still hasn't been removed. I tried to see if there was a conclusion in the mailing list thread, but I didn't see a consensus position (please correct me if I'm wrong).

What needs to happen to remove the feature flag that we've told people we're absolutely going to be removing at some point?

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D125142

**Comment by jfbastien** [comment]
IIRC from the original commit, the expectation was that we’d have numbers showing that the performance difference just can’t be fixed between zero and pattern. My initial numbers had a pretty substantial effort to narrow that gap, and I don’t think there remains much performance gap to be closed. 

@zygoloid had separately proposed a new IR node which would either zero or trap (when UB can be proven), but the patch was never advanced.

**Comment by thesamesam** [comment]
@kees https://github.com/llvm/llvm-project/commit/aef03c9b3bed5cef5a1940774b80128aefcb4095 says it'll be removed in LLVM 17 - is there a commit for that?

**Comment by AaronBallman** [comment]
> @kees [aef03c9](https://github.com/llvm/llvm-project/commit/aef03c9b3bed5cef5a1940774b80128aefcb4095) says it'll be removed in LLVM 17 - is there a commit for that?

It was augmented [here](https://github.com/llvm/llvm-project/commit/aef03c9b3bed5cef5a1940774b80128aefcb4095) to say Clang 18, which is what the final 16.x release notes said: https://github.com/llvm/llvm-project/blob/7cbf1a2591520c2491aa35339f227775f4d3adf6/clang/docs/ReleaseNotes.rst?plain=1#L507

Now that we've branched 17.x, we're clear to start removing the option for 18.

**Comment by kees** [comment]
Thanks for the reminder! I've proposed it here: https://reviews.llvm.org/D159373

**Comment by kees** [comment]
Finished in commit 00e54d04ae2802d498741097d4b83e898bc99c5b.
