### ISSUE TITLE
Incorrect warning "Variable 'i' is not initialized [cppcoreguidelines-init-variables]"

### ISSUE THREAD

**Issue by 07db8777-e875-47a6-8e13-f3ee3e0342de** [llvm/llvm-project#44848]
|  |  |
| --- | --- |
| Bugzilla Link | [45503](https://llvm.org/bz45503) |
| Version | unspecified |
| OS | Windows NT |

## Extended Description 
Clang-Tidy 10.0.0

size_t size(std::vector<int> const & xs)
{
    std::size_t i /* <-- here */ = xs.size();
    return i;
}

**Comment by carlosgalvezp** [comment]
Problem no longer reproducible on trunk. 

> that some unresolved include, can lead to such warning.
For the most part, clang-tidy assumes it's analyzing code that compiles to begin with - checks aren't designed to protect against code that doesn't compile.
