### ISSUE TITLE
flang/runtime: 3 * missing calls to va_end ?

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#44876]
|  |  |
| --- | --- |
| Bugzilla Link | [45531](https://llvm.org/bz45531) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @sscalpone,@tskeith |

## Extended Description 
flang/runtime/io-error.cpp:46:9: error: va_list 'ap' was opened but not closed by va_end(). [va_end_missing]
flang/runtime/io-error.cpp:52:5: error: va_list 'ap' was opened but not closed by va_end(). [va_end_missing]
flang/runtime/terminator.cpp:19:1: error: va_list 'ap' was opened but not closed by va_end(). [va_end_missing]

**Comment by ekieri** [comment]
This issue appears to have been fixed by @klausler in https://reviews.llvm.org/D101928, so I'll close it. Please don't hesitate to reopen if the issue persists.
