### ISSUE TITLE
[AArch64] Incorrect result for vector conversion with -O2

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#44886]
|  |  |
| --- | --- |
| Bugzilla Link | [45541](https://llvm.org/bz45541) |
| Version | 10.0 |
| OS | Linux |
| Attachments | [Test case](https://user-images.githubusercontent.com/60944935/143760608-c3a787ac-595a-4fdd-8184-e51abbc31c5b.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @Arnaud-de-Grandmaison-ARM,@smithp35 |

## Extended Description 

The attached test case works on without optimization and on GCC, but fails with -O2 (`clang-10 -v -target aarch64-linux-gnu -O2 -o mm_cvtepu8_epi16 mm_cvtepu8_epi16.c` to be precise).

I've added a FOO preprocessor macro (see line 27) to switch between making simde__m128i a typedef to int64x2_t and int32x4_t.  Depending on which is used different functions fail.  It shouldn't actually matter since the code uses __builtin_memcpy to convert to/from simde__m128i_private and simde__m128i.

**Comment by mr-c** [comment]
I was able to reproduce the provided test case with clang 13 and 14; it looks like this was fixed in clang-15. Therefore I think this issue can be closed

**Comment by sjoerdmeijer** [comment]
I agree, I can't reproduce this with a trunk build, closing this.
