### ISSUE TITLE
README out of date w.r.t. the llvm monorepo

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#44912]
|  |  |
| --- | --- |
| Bugzilla Link | [45567](https://llvm.org/bz45567) |
| Version | unspecified |
| OS | All |

## Extended Description 
The Clang tools extra readme says:

This repository is only intended to be checked out inside of a full LLVM+Clang
tree, and in the 'tools/extra' subdirectory of the Clang checkout.

This should be updated now that the llvm monorepo happened.

**Comment by xgupta** [comment]
Updated in https://github.com/llvm/llvm-project/commit/8311604669c708f65be7335baba9fd774eef944c.
