### ISSUE TITLE
Deprecated CreateShuffleVector used

### ISSUE THREAD

**Issue by jpienaar** [llvm/llvm-project#44965]
|  |  |
| --- | --- |
| Bugzilla Link | [45620](https://llvm.org/bz45620) |
| Version | unspecified |
| OS | All |
| CC | @joker-eph,@River707,@ftynse |

## Extended Description 
LLVM_ShuffleVectorOp's build method needs to be updated:

tools/mlir/include/mlir/Dialect/LLVMIR/LLVMConversions.inc:438:34: warning: 'CreateShuffleVector' is deprecated: Pass indices as 'int' instead [-Wdeprecated-declarations]
valueMapping[op.res()] = builder.CreateShuffleVector(valueMapping.lookup(op.v1()), valueMapping.lookup(op.v2()), extractPosition(op.mask()));
                                 ^
/usr/local/google/home/jpienaar/Compiles/llvm-project/llvm/include/llvm/IR/IRBuilder.h:2380:3: note: 'CreateShuffleVector' has been explicitly marked deprecated here
  LLVM_ATTRIBUTE_DEPRECATED(Value *CreateShuffleVector(Value *V1, Value *V2,
  ^
/usr/local/google/home/jpienaar/Compiles/llvm-project/llvm/include/llvm/Support/Compiler.h:311:23: note: expanded from macro 'LLVM_ATTRIBUTE_DEPRECATED'
  decl __attribute__((deprecated(message)))
                      ^
1 warning generated.

**Comment by JOE1994** [comment]
[`llvm/include/llvm/IR/IRBuilder.h`](https://github.com/llvm/llvm-project/blob/b746babb22bdcd945b7665d63472c9d8695893d0/llvm/include/llvm/IR/IRBuilder.h) no longer maintains the deprecated version of `CreateShuffleVector` mentioned in the original bugzilla ticket.

The one and only call to `CreateShuffleVector` in [`mlir/include/mlirDialect/LLVMIR/LLVMOpts.td`](https://github.com/llvm/llvm-project/blob/b746babb22bdcd945b7665d63472c9d8695893d0/mlir/include/mlir/Dialect/LLVMIR/LLVMOps.td) doesn't seem to be using a deprecated version of `CreateShuffleVector`.
