### ISSUE TITLE
No-op Boost/CGAL code results in compiler crash with clang-cl with: "error: Stream Error: The stream is too short to perform the requested operation."

### ISSUE THREAD

**Issue by rubenvb** [llvm/llvm-project#44962]
|  |  |
| --- | --- |
| Bugzilla Link | [45617](https://llvm.org/bz45617) |
| Version | 10.0 |
| OS | Windows XP |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Attached repro case fails to compile.
Original code uses CGAL 4.14 and Boost 1.70.
This also failed with Clang version 9.0.1 as well as current trunk.

Basically this code fails to compile:

#include <CGAL/Mesh_triangulation_3.h>
#include <CGAL/Mesh_complex_3_in_triangulation_3.h>
#include <CGAL/Mesh_criteria_3.h>
#include <CGAL/Polyhedral_mesh_domain_3.h>
#include <CGAL/make_mesh_3.h>
#include <CGAL/IO/Polyhedron_iostream.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef CGAL::Polyhedron_3 <Kernel>                         KernelPolyhedron;
typedef KernelPolyhedron::HalfedgeDS                              HalfedgeDS;
typedef CGAL::Polyhedral_mesh_domain_3<KernelPolyhedron, Kernel>  MeshDomain;

#ifdef CGAL_CONCURRENT_MESH_3
typedef CGAL::Mesh_triangulation_3 <
MeshDomain,
CGAL::Kernel_traits<MeshDomain>::Kernel, // Same as sequential
CGAL::Parallel_tag                        // Tag to activate parallelism
>::type Tr;
#else
typedef CGAL::Mesh_triangulation_3<MeshDomain>::type   Tr;
#endif

typedef CGAL::Mesh_complex_3_in_triangulation_3<Tr>     C3T3;
typedef CGAL::Mesh_criteria_3<Tr>                       MeshCriteria;
typedef C3T3::Vertices_in_complex_iterator              VerticesIterator;
typedef C3T3::Cells_in_complex_iterator                 CellsIterator;
typedef C3T3::Facets_in_complex_iterator                FacetsIterator;
typedef Tr::Finite_vertices_iterator                    FiniteVerticesIterator;
typedef Tr::Vertex_handle                               VertexHandle;

using namespace CGAL::parameters;

bool buildMesh(/*cgal::SurfaceMeshPolisherInputData & inputData, cgal::SurfaceMeshPolisherOutputData & outputData, */bool * cancel)
{
    KernelPolyhedron polyhedron;
    bool ok = true;
    C3T3 c3t3;
    return ok;
}

**Comment by Endilll** [comment]
Author hasn't got back to us with a reproducer.
