### ISSUE TITLE
C++20 template Constraints doesn't evaluate the current calling context

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45008]
|  |  |
| --- | --- |
| Bugzilla Link | [45663](https://llvm.org/bz45663) |
| Version | 10.0 |
| OS | All |
| Attachments | [Self-describing source code copy, from godbolt.org link.Feel free to test the code](https://user-images.githubusercontent.com/60944935/143760650-4768fcb3-3f46-4c52-9e63-5c75277c3696.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid,@saarraz |

## Extended Description 

When a template instantiation attempt occur, the compiler seems to cache the resulting instantiation attempt details.

The contraints evaluation along with the template are not further evaluated correctly when further template instantiations are called, even if constraint argument's context has changed.

This lead to valid constraint evaluation failure.
And so, it fails to instantiate specialized template, or function template overload.

The details of such context change evaluation failure can be seen on this link : https://godbolt.org/z/QMU6YC
(This is MAtt Godbolt's website 'Compiler Explorer')

or a copy code from that link below as an attachment.

It explains step by step my testing context, and what I expected.

This testing context focus on :
- a concept testing inheritance (with pointer conversion requires),
- a template class 'Zeta' with template constructor overload using this concept as a constraint,

- two classes 'Alpha' and 'Beta' with inheritance relationship, but the 'Beta' derived class is forward declared,

- some 'Ss' class definitions with a 'Zeta<Alpha>' data member,
declaring two constructors using 'Zeta<Alpha>' and 'Zeta<Beta>' as arguments, causing 'Zeta' constrained template constructor to be evaluated as a conversion constructor, while 'Beta' is still not defined,
Note : 'Zeta' matching type argument copy-constructor is intended.

- 'Beta' defined as derived from 'Alpha' and using 'Ss' class definition (so it need to be defined late),

- valid 'Ss' constructors definition : using 'Zeta<Beta>' to 'Zeta<Alpha>' constrained template conversion-constructor instantiation, as 'Beta' is now defined as inheriting 'Alpha'.

Problem summary :
- 'Beta' inheriting 'Alpha' Constraint evaluate to false, when 'Beta' is already defined as inheriting 'Alpha'.

Expected :
- 'Zeta<Beta>' to 'Zeta<Alpha>' constrained conversion overload is selected, as constraints are satisfied.

**Comment by Quuxplusone** [comment]
Yep, GCC even warns on the godbolted code:
```
error: satisfaction value of atomic constraint 'requires(TypeTo* BasePointer, TypeFrom*
SourcePointer) {BasePointer = SourcePointer;} [with TypeFrom = Cat; TypeTo = Animal]'
changed from 'false' to 'true'
```
So I think this can safely be closed as INVALID.
