### ISSUE TITLE
Bad comment indentation before ifdef after braceless if

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#45002]
|  |  |
| --- | --- |
| Bugzilla Link | [45657](https://llvm.org/bz45657) |
| Version | trunk |
| OS | Linux |
| CC | @krasimir-google |

## Extended Description 
Example input:

$ cat /tmp/a.cc
```
void f() {
  if (foo)
    bar();
  // Comment
#if BAZ
  baz();
#endif
}
```

Example output:

$ bin/clang-format < /tmp/a.cc
```
void f() {
  if (foo)
    bar();
    // Comment
#if BAZ
  baz();
#endif
}
```

Note that the comment is now overly indented. Inserting a new line after "baz()" doesn't change it.

(I was using clang-format built from d254b50b2b5b22368780c6003c419ffa1e23fa93)

This was originally filed in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1074113

**Comment by mydeveloperday** [comment]
I can confirm this is still present in v13 of clang-format

**Comment by rajdroid** [comment]
@mydeveloperday if anyone is not working on this issue then may I try to fix it?

**Comment by mydeveloperday** [comment]
Feel free to go ahead
