### ISSUE TITLE
Failure to remove useless reload

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#45082]
|  |  |
| --- | --- |
| Bugzilla Link | [45737](https://llvm.org/bz45737) |
| Version | trunk |
| OS | Linux |

## Extended Description 
struct testStruct
{
    struct testStruct* p1;
    struct testStruct* p2;
};

void f(struct testStruct *element)
{
    element->p1->p2 = element->p2;
    element->p2->p1 = element->p1;
}

In this code, `element->p2` only needs to be loaded once. However, LLVM loads `element->p2` again after `element->p1->p2 = element->p2`. Whether or not `element->p1 == &element` doesn't matter here, since then `element->p2` would be assigned `element->p2`, so the value would still be known here.

Code from GCC: 

f(testStruct*):
  mov rdx, QWORD PTR [rdi]
  mov rax, QWORD PTR [rdi+8]
  mov QWORD PTR [rdx+8], rax
  mov QWORD PTR [rax], rdx
  ret

Code from LLVM:

f(testStruct*): # @&#8203;f(testStruct*)
  mov rax, qword ptr [rdi]
  mov rcx, qword ptr [rdi + 8]
  mov qword ptr [rax + 8], rcx
  mov rcx, qword ptr [rdi + 8]
  mov qword ptr [rcx], rax
  ret

**Comment by GabrielRavier** [comment]
Looks like this is fixed on trunk now ?

**Comment by dtcxzyw** [comment]
> Looks like this is fixed on trunk now ?

Confirmed. See https://godbolt.org/z/G616q5fdz.
