### ISSUE TITLE
Valid Template Instantiation triggers assertion failure when Clang/LLVM built with ASSERTs enabled, but does not fail without assertion

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45085]
|  |  |
| --- | --- |
| Bugzilla Link | [45740](https://llvm.org/bz45740) |
| Version | 10.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @AaronBallman,@zygoloid |

## Extended Description 
When Clang and LLVM (version 10.0.0 for both) are compiled from source with 'Release' build and assertions are enabled, the following code:

```cpp
template <const int& x>
void g() {
    x;
}
template <int>
void f() {
    static constexpr int x = 0;
    g<x>();
}
int main() {
    f<0>();
    return 0;
}
```

will error out with:

clang++ -std=c++17 template.cpp 

OR

clang++ -std=c++2a template.cpp 

producing:

clang-10: /xxxxx/llvm-project-llvmorg-10.0.0/clang/lib/Sema/SemaTemplateInstantiate.cpp:3527: llvm::PointerUnion<clang::Decl*, llvm::SmallVector<clang::VarDecl*, 4>*>* clang::LocalInstantiationScope::findInstantiationOf(const clang::Decl*): Assertion `isa<LabelDecl>(D) && "declaration not instantiated in this scope"' failed.

However, if Clang and LLVM are compiled for RELEASE and assertions are turned off, the code snippet passes through.

This also affects Clang and LLVM (trunk).

**Comment by shafik** [comment]
duplicate of: https://github.com/llvm/llvm-project/issues/45085
