### ISSUE TITLE
out of memory with code allocating huge array of std::array

### ISSUE THREAD

**Issue by skhrshin** [llvm/llvm-project#45080]
|  |  |
| --- | --- |
| Bugzilla Link | [45735](https://llvm.org/bz45735) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [test code](https://user-images.githubusercontent.com/92601636/143760674-8b361f6b-c446-4648-870e-91c16153458a.gz), [test code 2 (without std::array)](https://user-images.githubusercontent.com/92601636/143760675-14b5be76-e6a5-4bdf-94e9-00630644f887.gz) |
| CC | @DougGregor,@zygoloid |

## Extended Description 

out of memory error is caused when I compile the test code with clang 11.0.0(2663a25f) for Windows x64. MSVC2019 is installed on my machine, and its standard library is used. My machine has 16GB memory.

**Comment by Destroyerrrocket** [comment]
I tried to reproduce this issue, and it seems like trunk no longer fails:
https://godbolt.org/z/caEf4aqv7

**Comment by shafik** [comment]
Looks fixed in trunk: https://godbolt.org/z/bashW6f7d
