### ISSUE TITLE
Frontend crash on += operator with ISO/IEC 18037 types

### ISSUE THREAD

**Issue by shuber2** [llvm/llvm-project#45116]
|  |  |
| --- | --- |
| Bugzilla Link | [45771](https://llvm.org/bz45771) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Backtrace](https://user-images.githubusercontent.com/93435912/143760680-cc8568a9-d7db-47ce-8b8c-67851512ab91.gz), [The C source that provokes the segfault](https://user-images.githubusercontent.com/93435912/143760681-8af07144-1e14-4f63-b727-5f4ec730aa2d.gz), [Crash reproducer](https://user-images.githubusercontent.com/93435912/143760682-a35fba0a-760b-4df7-9f1a-ca8f531493e7.gz) |
| CC | @DougGregor,@zygoloid |

## Extended Description 

The frontend of clang-9.0.1 on Gentoo Linux crashes when compiling a C file that contains an invocation of the += operator on ISO/IEC 18037 types, like _Fract, _Accum or variants of these.

I could not reproduce this issue with clang-7.0.1-8 on Debian Buster or with clang-10.0.0 on Windows via msys2. However, Michał Górny could reproduce it on 10.0.0 on Gentoo Linux as well, see https://bugs.gentoo.org/720270

**Comment by AaronBallman** [comment]
I was able to reproduce this in Clang 10, but unable to reproduce in Clang 11 or later, so closing this as WORKSFORME. If the issue still persists, please reopen the bug with additional information on how to reproduce.
