### ISSUE TITLE
`ld.lld --help ` doesn't mention zlib-gnu or zlib-gabi support

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#45112]
|  |  |
| --- | --- |
| Bugzilla Link | [45767](https://llvm.org/bz45767) |
| Version | unspecified |
| OS | Linux |
| CC | @dwblaikie,@echristo,@MaskRay,@rupprecht,@smithp35,@stephenhines |

## Extended Description 
I'm looking into enabling compressed debug info support within the Linux kernel.

I noticed from `man 1 ld` that the documentation on `--compress-debug-sections=` says:

           The default compression behaviour varies depending upon the
           target involved and the configure options used to build the
           toolchain.  The default can be determined by examining the output
           from the linker's --help option.

If I run:

$ ld.lld --help | grep zlib
  --compress-debug-sections=[none,zlib]
$ ld.bfd --help | grep zlib
  --compress-debug-sections=[none|zlib|zlib-gnu|zlib-gabi]
                              Compress DWARF debug sections using zlib

Does lld not support `zlib-gnu` or `zlib-gabi`?  I'm not really sure which option is even preferred, so I'll run some builds and compare zdebug_* section sizes.

**Comment by MaskRay** [comment]
This is somewhat obsoleted. For clang 14.0.0, we even dropped `-gz=zlib-gnu` and `-Wa,--compress-debug-sections=zlib-gnu`.

ld.lld --help message `--compress-debug-sections=[none,zlib]` is quite clear other values are unsupported.
