### ISSUE TITLE
Failure to properly handle abs with -ftrapv

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#45129]
|  |  |
| --- | --- |
| Bugzilla Link | [45784](https://llvm.org/bz45784) |
| Version | trunk |
| OS | Linux |
| CC | @topperc,@zygoloid,@yuanfang-chen |

## Extended Description 
unsigned f(int x)
{
    return __builtin_abs(x);
}

With -O3 -ftrapv, LLVM outputs this :

f(int): # @&#8203;f(int)
  mov eax, edi
  neg eax
  cmovl eax, edi
  ret

The neg should be checked to avoid overflow on INT_MIN, since `-ftrapv` is on.e

**Comment by artem** [comment]
The issue is still relevant for LLVM trunk
