### ISSUE TITLE
clang-tidy assumes that __addressof reallocates std::string

### ISSUE THREAD

**Issue by aba9944f-3671-4d3d-ae6a-013af1045d9a** [llvm/llvm-project#45131]
|  |  |
| --- | --- |
| Bugzilla Link | [45786](https://llvm.org/bz45786) |
| Version | 9.0 |
| OS | Linux |
| Attachments | [Testcase](https://user-images.githubusercontent.com/93435908/143760686-e92c7249-fa66-4890-822e-ca2841d0d704.gz) |
| CC | @alishuja,@devincoughlin,@EugeneZelenko,@forcasualplayers,@haoNoQ |

## Extended Description 

Analyzing the attached testcase with "clang-tidy test.cpp -- --std=c++17" yields the following error:

1 warning generated.
/home/ivanq/Documents/test.cpp:7:14: warning: Inner pointer of container used after re/deallocation [clang-analyzer-cplusplus.InnerPointer]
        std::string str(opt->data(), opt->size());
                    ^
/home/ivanq/Documents/test.cpp:7:18: note: Pointer to inner buffer of 'class std::__cxx11::basic_string<char>' obtained here
        std::string str(opt->data(), opt->size());
                        ^
/home/ivanq/Documents/test.cpp:7:31: note: Calling 'optional::operator->'
        std::string str(opt->data(), opt->size());
                                     ^
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/optional:894:16: note: Inner buffer of 'class std::__cxx11::basic_string<char>' reallocated by call to '__addressof'
      { return std::__addressof(this->_M_get()); }
               ^
/home/ivanq/Documents/test.cpp:7:31: note: Returning; inner buffer was reallocated
        std::string str(opt->data(), opt->size());
                                     ^
/home/ivanq/Documents/test.cpp:7:14: note: Inner pointer of container used after re/deallocation
        std::string str(opt->data(), opt->size());
                    ^

I am using GCC standard headers. It looks like clang thinks that std::__addressof can reallocate std::string and thus std::optional::operator-> can invalidate the contents which obviously can't be true.

I can get rid of the warning by dereferencing once (e.g. "auto opt_deref = *opt; std::string str(opt_deref.data(), opt_deref.size())"), replacing default constructor + assignment with a single constructor call, i.e. "std::optional<std::string> opt = 'abc';" or using "opt.value()." instead of "opt->". Wrapping the std::string construction with "if(opt)" or similar statements doesn't help.

Versions:

$ clang --version
clang version 9.0.0-2 (tags/RELEASE_900/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 9.0.0
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: westmere

Trying the same testcase on godbolt (https://godbolt.org/z/iFdoDa) gives the same results on newer clang versions too.

**Comment by haoNoQ** [comment]
The fix has landed!
