### ISSUE TITLE
clangd on i386 fails to link with error: undefined reference to '__atomic_load'

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#45130]
|  |  |
| --- | --- |
| Bugzilla Link | [45785](https://llvm.org/bz45785) |
| Version | unspecified |
| OS | Linux |
| CC | @aleden,@slacka,@serge-sans-paille |

## Extended Description 
full log: 
https://llvm-jenkins.debian.net/view/Debian%2011%20-%20unstable/job/llvm-toolchain-binaries/architecture=i386,distribution=unstable/2061/consoleFull

with a stage2 build, clangd cannot link because of undef reference on i386

cd "/build/llvm-toolchain-snapshot-11~++20200503111111+e64f99c51a8/build-llvm/tools/clang/stage2-bins/tools/clang/tools/extra/clangd/tool" && /usr/bin/cmake -E cmake_link_script CMakeFiles/clangd.dir/link.txt --verbose=1
"/build/llvm-toolchain-snapshot-11~++20200503111111+e64f99c51a8/build-llvm/./bin/clang++"   -fuse-ld=gold -fPIC -Wno-unused-command-line-argument -Wno-unknown-warning-option -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -Wno-nested-anon-types -O2 -DNDEBUG -g1  -fuse-ld=gold -fPIC -Wno-unused-command-line-argument -Wno-unknown-warning-option -Wl,--build-id -Wl,-allow-shlib-undefined  -Wl,-O3 -Wl,--gc-sections CMakeFiles/clangd.dir/ClangdMain.cpp.o ../refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/AddUsing.cpp.o ../refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/AnnotateHighlightings.cpp.o ../refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/DumpAST.cpp.o ../refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/DefineInline.cpp.o ../refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/DefineOutline.cpp.o ../refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/ExpandAutoType.cpp.o ../refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/ExpandMacro.cpp.o ../refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/ExtractFunction.cpp.o ../refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/ExtractVariable.cpp.o ../refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/ObjCLocalizeStringLiteral.cpp.o ../refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/RawStringLiteral.cpp.o ../refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/RemoveUsingNamespace.cpp.o ../refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/SwapIfBranches.cpp.o  -o ../../../../../../bin/clangd  -Wl,-rpath,"\$ORIGIN/../lib" -lpthread ../../../../../../lib/libclang-cpp.so.11 ../../../../../../lib/libclangTidy.a ../../../../../../lib/libclangDaemon.a ../../../../../../lib/libclangdSupport.a -lpthread ../../../../../../lib/libclangToolingSyntax.a ../../../../../../lib/libclangTidyAndroidModule.a ../../../../../../lib/libclangTidyAbseilModule.a ../../../../../../lib/libclangTidyBoostModule.a ../../../../../../lib/libclangTidyCERTModule.a ../../../../../../lib/libclangTidyDarwinModule.a ../../../../../../lib/libclangTidyFuchsiaModule.a ../../../../../../lib/libclangTidyHICPPModule.a ../../../../../../lib/libclangTidyBugproneModule.a ../../../../../../lib/libclangTidyCppCoreGuidelinesModule.a ../../../../../../lib/libclangTidyGoogleModule.a ../../../../../../lib/libclangTidyLinuxKernelModule.a ../../../../../../lib/libclangTidyLLVMModule.a ../../../../../../lib/libclangTidyLLVMLibcModule.a ../../../../../../lib/libclangTidyMiscModule.a ../../../../../../lib/libclangTidyModernizeModule.a ../../../../../../lib/libclangTidyObjCModule.a ../../../../../../lib/libclangTidyOpenMPModule.a ../../../../../../lib/libclangTidyPerformanceModule.a ../../../../../../lib/libclangTidyPortabilityModule.a ../../../../../../lib/libclangTidyReadabilityModule.a ../../../../../../lib/libclangTidyZirconModule.a ../../../../../../lib/libclangTidyMPIModule.a ../../../../../../lib/libclangTidyUtils.a ../../../../../../lib/libclangTidy.a ../../../../../../lib/libclangTooling.a ../../../../../../lib/libclangStaticAnalyzerFrontend.a ../../../../../../lib/libclangStaticAnalyzerCheckers.a ../../../../../../lib/libclangStaticAnalyzerCore.a ../../../../../../lib/libclangCrossTU.a ../../../../../../lib/libclangTransformer.a ../../../../../../lib/libclangToolingRefactoring.a ../../../../../../lib/libclangIndex.a ../../../../../../lib/libclangFormat.a ../../../../../../lib/libclangToolingInclusions.a ../../../../../../lib/libclangFrontend.a ../../../../../../lib/libclangDriver.a ../../../../../../lib/libclangParse.a ../../../../../../lib/libclangSerialization.a ../../../../../../lib/libclangSema.a ../../../../../../lib/libclangAnalysis.a ../../../../../../lib/libclangASTMatchers.a ../../../../../../lib/libclangEdit.a ../../../../../../lib/libclangToolingCore.a ../../../../../../lib/libclangAST.a ../../../../../../lib/libclangRewrite.a ../../../../../../lib/libclangLex.a ../../../../../../lib/libclangBasic.a ../../../../../../lib/libLLVM-11.so.1 
/usr/lib/gcc/i686-linux-gnu/9/../../../../include/c++/9/atomic:254: error: undefined reference to '__atomic_load'
/usr/lib/gcc/i686-linux-gnu/9/../../../../include/c++/9/atomic:243: error: undefined reference to '__atomic_store'
/usr/lib/gcc/i686-linux-gnu/9/../../../../include/c++/9/atomic:254: error: undefined reference to '__atomic_load'

it was working with bb7bde5bba5

**Comment by tstellar** [comment]
I think this is #54963.

**Comment by HighCommander4** [comment]
Tentatively closing based on the previous comment. If you're still seeing this with a recent clangd, please feel free to reopen.

**Comment by satmandu** [comment]
Debian continues to work around this i386 build issue that still exists in LLVM 23.1 by adding `-atomic` to 32-bit x86 builds with https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/raw/23/debian/patches/clangd-atomic-cmake.patch?ref_type=heads&inline=false .
