### ISSUE TITLE
Suboptimal code for _mm256_zextsi128_si256(_mm_set1_epi8(-1))

### ISSUE THREAD

**Issue by NemoPublius** [llvm/llvm-project#45153]
|  |  |
| --- | --- |
| Bugzilla Link | [45808](https://llvm.org/bz45808) |
| Version | trunk |
| OS | Linux |
| CC | @topperc,@fhahn,@LebedevRI,@RKSimon,@rotateright |
| Fixed by commit(s) | fe6f5ba0bffd,b8a725274c22,3521ecf1f8a3 |

## Extended Description 
Related: Bug #&#8203;45806 and https://stackoverflow.com/q/61601902/

I am trying to produce an AVX2 mask with all-ones in the lower lane and all-zeroes in the upper lane of a YMM register. The code I am using is:

    __m256i mask = _mm256_zextsi128_si256(_mm_set1_epi8(-1));

This should produce a single instruction like `vpcmpeqd %xmm0,%xmm0,%xmm0`, but Clang insists on putting the value into memory and loading it.

However, Clang insists on putting this into memory and loading it.

The behavior in context is even more odd:

    __m256i minmax(__m256i v1, __m256i v2)
    {
        __m256i comp = _mm256_cmpgt_epi64(v1, v2);
        __m256i mask = _mm256_zextsi128_si256(_mm_set1_epi8(-1));
        return _mm256_blendv_epi8(v2, v1, _mm256_xor_si256(comp, mask));
    }

This goes through a bunch of contortions with extracting, shifting, and expanding 128-bit registers when I feel like the result I want is pretty straightforward.

Godbolt example: https://gcc.godbolt.org/z/GPhJ6s

**Comment by RKSimon** [comment]
I think we can close this: https://gcc.godbolt.org/z/E6bfj1vx6

If we have one use of the mask we create a constant to fold into the xor.

If the mask has multiple uses then we perform the materialization trick - although neither clang or gcc recognise the implicit zero upper bits of the vpcmpeq xmm, both perform a (almost free) vmovdqa to do this.

**Comment by NemoPublius** [comment]
@RKSimon Loading from memory is not "almost free" compared to a single all-register instruction. That is sort of the entire point of this bug report.

I guess I will stick with inline asm for this.
