### ISSUE TITLE
Using __builtin_assume_aligned with alignment sanitizer leads to a crash in clang

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45158]
|  |  |
| --- | --- |
| Bugzilla Link | [45813](https://llvm.org/bz45813) |
| Version | trunk |
| OS | Linux |
| Attachments | [main.c](https://user-images.githubusercontent.com/60944935/143760694-f78b23f4-37f6-4d04-a142-55d3f84230f8.gz), [complete command](https://user-images.githubusercontent.com/60944935/143760695-2d4ce5e3-9c65-4bd1-9f09-304b0fe13fd9.gz), [backtrace](https://user-images.githubusercontent.com/60944935/143760696-b77a1d53-6362-4b4f-9152-d6e6e5d2329e.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@LebedevRI,@orivej,@zygoloid |

## Extended Description 

Trying to compile the following code in Ubuntu 18.04 with command clang-9 -fsanitize=alignment main.c leads to a crash:

int main(void)
{
	__attribute__((aligned(16))) int data[4];

	__builtin_assume_aligned(data, 16);
}

**Comment by MaskRay** [comment]
The issue no long reproduces. Closing per comment on https://reviews.llvm.org/D92001
