### ISSUE TITLE
Crash: templated lambda capturing another lambda object

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45173]
|  |  |
| --- | --- |
| Bugzilla Link | [45828](https://llvm.org/bz45828) |
| Version | 9.0 |
| OS | Linux |
| Attachments | [simple crash test case](https://user-images.githubusercontent.com/60944935/143760702-44061810-fd66-43a3-8cc9-744d22552830.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @bcardosolopes,@rambl30n,@modocache,@zygoloid |

## Extended Description 

Attaching a small self-conteined example that crashes Clang++ 9 through current 10/11 snapshot. Gcc 8+ appears to work fine.

Command:
clang++-9 -O0 -c -emit-llvm -std=c++2a crash.cpp

Versions:
clang++-9: 9.0.0-2~ubuntu18.04.2
clang++-10: 10.0.1-++20200506082601+98f9f73f6d2-1~exp1~20200506183223.15
clang++-11: 11.0.0-++20200506063826+6d6d48add8a-1~exp1~20200506164428.1667

Inline Code:
struct Enum {
  template<typename F>
  static void eachWithIndex(F&& f) {
    f.template operator()<0, short>();
    f.template operator()<1, long>();
  }
};

struct Config {
  template<typename F>
  static void enumerate(F&& f) {
    Enum::eachWithIndex([&]<int i, typename Pi>(){
      f.template operator()<i>();
    });
  }
};

int main() {
  Config::enumerate([&]<int i>(){
  });
}

**Comment by royjacobson** [comment]
Fixed in clang 13.
