### ISSUE TITLE
member variable renaming only performed in header

### ISSUE THREAD

**Issue by a19fd002-0706-4b3d-adad-d72331a75df0** [llvm/llvm-project#45172]
|  |  |
| --- | --- |
| Bugzilla Link | [45827](https://llvm.org/bz45827) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
I am trying apply clang-tidy to my project, but run into the problem that it only renames member variables in the header, but not the occurrences in the cpp files:

E.g. I have a class member named "my_member" in the header file. This gets renamed by clang-tidy to "my_member_". But all occurrences in the cpp file are not touched. (it changes other stuff in the cpp. So it is not the case that it doesnt know about the cpp file).

Example: Original header file:

#ifndef TESTCLASS_H
#define TESTCLASS_H

class TestClass
{
 public:
  TestClass();

 private:
  float my_member;
};

#endif // TESTCLASS_H

The cpp file:

#include "testclass.h"

TestClass::TestClass()
{
  my_member = 0;
}

my_member gets renamed to my_member_, but the occurrence in the cpp stays the same.

I use clang-tidy-9.

**Comment by carlosgalvezp** [comment]
Closed as resolved.
