### ISSUE TITLE
"friends can only be classes or functions" should also be diagnosed when trying to befriend a concept

### ISSUE THREAD

**Issue by Quuxplusone** [llvm/llvm-project#45182]
|  |  |
| --- | --- |
| Bugzilla Link | [45837](https://llvm.org/bz45837) |
| Version | trunk |
| OS | All |
| CC | @mizvekov,@zygoloid |

## Extended Description 
https://godbolt.org/z/jntYnj

Given this code:

struct S {
    template<class>
    friend concept fooable;
};

Clang produces this harsh syntax error:

error: expected member name or ';' after declaration specifiers
    friend concept fooable;
           ^

If you try to befriend any other kind of entity -- for example, a variable or variable template -- Clang gives a much friendlier error message, indicating that it understands what you were *trying* to do:

error: friends can only be classes or functions
    friend bool fooable_v;
                ^

People are already trying to befriend concepts in the field, so it would be nice if Clang gave that same friendly error message (diag::err_unexpected_friend) for the `concept` case, as well.

**Comment by xgupta** [comment]
I found a patch/commit that had implemented this error - https://reviews.llvm.org/D12435#change-1kMp1WNFvcfx. But it is not the tree anymore?

**Comment by xgupta** [comment]
I think we have to fix parser first to not emit this error wrong message - error: expected member name or ';' after declaration specifiers 
here -
https://github.com/llvm/llvm-project/blob/fb40c34b8f8c57f5eb55b085660e111832f27aca/clang/lib/Parse/ParseDecl.cpp#L6252-L6590
and let then sema to handle the error - error: friends can only be classes or function 
here -
https://github.com/llvm/llvm-project/blob/fb40c34b8f8c57f5eb55b085660e111832f27aca/clang/lib/Sema/SemaDeclCXX.cpp#L17155-L17469

**Comment by cor3ntin** [comment]
@Sirraide any chance you want to look at this one?

**Comment by Sirraide** [comment]
Having looked at the code that parses `friend` declarations recently, I should probably be able to figure out where to diagnose that.
