### ISSUE TITLE
std::~unique_ptr is inefficient

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45193]
|  |  |
| --- | --- |
| Bugzilla Link | [45848](https://llvm.org/bz45848) |
| Version | unspecified |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @atmnpatel,@dwblaikie,@mclow,@tambry |

## Extended Description 
The dtor of unique_ptr is implemented in terms of reset (which defaults to a set of a nullptr).
  ~unique_ptr() { reset(); }

This is inefficient as the effect is that the dtor modifies the address held by its ptr
    __ptr_.first() = __p;
This causes address invalidation (and a related cacheline invalidation).

Since this is in the dtor, noone should read that value again.

~unique_ptr should be implemented in terms of the contained destructor only:
~unique_ptr() {
    const pointer ptr = __ptr_.first();
    if (ptr)
        __ptr_.second()(ptr);
}

**Comment by philnik777** [comment]
Given that there seems to be no actual performance difference and there is no consensus to make this change, I'm closing this for now. If there is new information to suggest there is a performance benefit to rewriting the destructor, this can be reopened.
