### ISSUE TITLE
Check for newlib broken: catopen

### ISSUE THREAD

**Issue by LittleFox94** [llvm/llvm-project#45207]
|  |  |
| --- | --- |
| Bugzilla Link | [45862](https://llvm.org/bz45862) |
| Version | unspecified |
| OS | All |
| CC | @mclow |

## Extended Description 
In line 298 of include/__config in libcxx is a check for _NEWLIB_VERSION. Since this header never includes a thing, this macro is not yet defined and the check never finds newlib. Since this function is not available with newlib, compilation fails.

This commit removes the last include in the file which was enough:
https://github.com/llvm/llvm-project/commit/6dec6d896f367334f85f1f522f4d37154d785bd4

Since that commit is very old, this check is either broken for a very long time or other includes were added and removed since then (searched from the past to until it is broken, not from current backwards).

**Comment by philnik777** [comment]
We don't check for `_NEWLIB_VERSION` in `__config` anymore
