### ISSUE TITLE
Assertion `idx < size()' failed in HandleUnionActiveMemberChange

### ISSUE THREAD

**Issue by pcc** [llvm/llvm-project#45224]
|  |  |
| --- | --- |
| Bugzilla Link | [45879](https://llvm.org/bz45879) |
| Version | unspecified |
| OS | All |
| CC | @Quuxplusone,@tambry,@zygoloid,@spavloff,@stephenhines |

## Extended Description 
$ cat test-formatted.ii
struct a {
  char b = 0;
};

struct s {
  a f;
};

constexpr void m() {
  a l;
  l = s{}.f;
}

void p() { return m(); }
$ clang++ -c -o test.o test-formatted.ii -std=gnu++2a
clang++: ../llvm/include/llvm/ADT/SmallVector.h:180: llvm::SmallVectorTemplateCommon::const_reference llvm::SmallVectorTemplateCommon<clang::APValue::LValuePathEntry, void>::operator[](llvm::SmallVectorTemplateCommon::size_type) const [T = clang::APValue::LValuePathEntry]: Assertion `idx < size()' failed.

**Comment by DimitryAndric** [comment]
@rsmith, was this now completely fixed by 30baa5d2a450d5e302d8cba3fc7a26a59d4b7ae1 ?

**Comment by shafik** [comment]
I can't reproduce this, so it looks fixed.
