### ISSUE TITLE
NVPTXTargetLowering::getParamSymbol uses incorrect name for unnamed funcs

### ISSUE THREAD

**Issue by JaschaWetzel** [llvm/llvm-project#45229]
|  |  |
| --- | --- |
| Bugzilla Link | [45884](https://llvm.org/bz45884) |
| Version | trunk |
| OS | All |
| Attachments | [.ll reproducer](https://user-images.githubusercontent.com/92601328/143760714-7d2a5ae4-06e2-4c5c-8e2f-f9d1e5ef688d.gz), [Patch for NVPTXTargetLowering::getParamSymbol](https://user-images.githubusercontent.com/92601328/143760715-6c8b61ea-8987-44ba-8f48-46afb62bcebd.gz) |

## Extended Description 

Compiling the attached .ll using
llc -O3 nvptx_param_name_missing_prefix.ll
produces the invalid PTX below.

.func __unnamed_1(
  .param .align 8 .b8 __unnamed_1_param_0[16], // ...
) {
  // ...
  ld.param.u64 	%rd3, [_param_0+8];
  // ...
}

**Comment by JOE1994** [comment]
This issue is resolved as of `llc 18.1.0` : https://godbolt.org/z/rvbTW593d
