### ISSUE TITLE
Crash on invalid program

### ISSUE THREAD

**Issue by russellmcc** [llvm/llvm-project#45233]
|  |  |
| --- | --- |
| Bugzilla Link | [45888](https://llvm.org/bz45888) |
| Version | 10.0 |
| OS | All |
| Attachments | [crashing cpp file](https://user-images.githubusercontent.com/93435896/143760718-17dc1101-6824-4e34-b164-4c33bbab15bc.gz), [run script](https://user-images.githubusercontent.com/93435896/143760719-9fa77c92-7dc5-4718-80f9-57ceed458286.gz), [Crash Dump](https://user-images.githubusercontent.com/93435896/143760720-fa45edc0-9256-4bba-aa1c-11186f46f3d3.gz) |
| CC | @zygoloid |

## Extended Description

**Comment by AaronBallman** [comment]
This issue was fixed in Clang 11.0.0: https://gcc.godbolt.org/z/nPn35xzeq
