### ISSUE TITLE
[lldb][unittest] Assertion failed : (m_replayers.find(RunID) == m_replayers.end())

### ISSUE THREAD

**Issue by sylvain-audi** [llvm/llvm-project#45250]
|  |  |
| --- | --- |
| Bugzilla Link | [45905](https://llvm.org/bz45905) |
| Version | unspecified |
| OS | Windows NT |
| CC | @amccarth-google,@JDevlieghere,@labath,@ZequanWu |

## Extended Description 
This happens in the LLDB unit tests, when building under windows.

In lldb\unittests\Utility\ReproducerInstrumentationTest.cpp:
  LLDB_REGISTER_METHOD(void, InstrumentedFoo, Validate, ());
  (...)
  LLDB_REGISTER_METHOD(void, InstrumentedBar, Validate, ());

The clashing IDs are evaluated as follows:
   &invoke<void(InstrumentedFoo::*) 
   ()>::method<(&InstrumentedFoo::Validate)>::record
  and
   &invoke<void(InstrumentedBar::*) 
   ()>::method<(&InstrumentedBar::Validate)>::record

Both "record" implementations are only calling Validate() through the vtable, so the implementations are identical for both.

The linker does COMDAT folding (option /OPT:ICF), which merges the 2 functions, so their address, which is used as an ID, end up being identical.

**Comment by labath** [comment]
The code in question does not exist anymore.
