### ISSUE TITLE
clang crashes after parsing bad C++17 deduction guide declaration

### ISSUE THREAD

**Issue by c5408508-9424-45a7-b4f1-3db922c3b89a** [llvm/llvm-project#45260]
|  |  |
| --- | --- |
| Bugzilla Link | [45915](https://llvm.org/bz45915) |
| Version | trunk |
| OS | Linux |
| CC | @davidgreenaway,@zygoloid,@VReichelt |

## Extended Description 
The following code:

```
template <a> class b;
b() b c;
```

compiled with `clang++ -std=c++17` causes clang to crash with the following error:

---

<source>:1:11: error: unknown type name 'a'

template <a> class b;

          ^

<source>:2:1: error: deduction guide declaration without trailing return type

b() b c;                                                                                                                                                                                  

^

<source>:2:4: error: expected ';' after top level declarator

b() b c;                                                                                                                                                                                  

   ^

   ;

PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.

Stack dump:

0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/clang++ -g -o ./output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-9.2.0 -fcolor-diagnostics -fno-crash-diagnostics -O2 -std=c++17 <source> 

1.	<source>:2:8: current parser token ';'

 #&#8203;0 0x000055a39034714a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x2bce14a)

 #&#8203;1 0x000055a390344f14 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x2bcbf14)

 #&#8203;2 0x000055a390345185 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x2bcc185)

 #&#8203;3 0x000055a3902bd720 CrashRecoverySignalHandler(int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x2b44720)

 #&#8203;4 0x00007ff85980f890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)

 #&#8203;5 0x000055a3922736b6 clang::InitializationSequence::Perform(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, clang::QualType*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4afa6b6)

 #&#8203;6 0x000055a3920045a3 clang::Sema::ActOnUninitializedDecl(clang::Decl*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x488b5a3)

 #&#8203;7 0x000055a391dfc2ba clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x46832ba)

 #&#8203;8 0x000055a391e0f175 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4696175)

 #&#8203;9 0x000055a391de60f9 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x466d0f9)

#&#8203;10 0x000055a391de6df1 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.227) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x466ddf1)

#&#8203;11 0x000055a391deccd9 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4673cd9)

#&#8203;12 0x000055a391dee3e9 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x46753e9)

#&#8203;13 0x000055a391de2059 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4669059)

#&#8203;14 0x000055a390b1a839 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x33a1839)

#&#8203;15 0x000055a390ad5b03 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x335cb03)

#&#8203;16 0x000055a390bded4b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3465d4b)

#&#8203;17 0x000055a38e5a5e8c cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xe2ce8c)

#&#8203;18 0x000055a38e5a2abd ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xe29abd)

#&#8203;19 0x000055a3909b0455 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::'lambda'()>(long) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3237455)

#&#8203;20 0x000055a3902bd803 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x2b44803)

#&#8203;21 0x000055a3909b10c0 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (.part.152) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x32380c0)

#&#8203;22 0x000055a39098b8c5 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x32128c5)

#&#8203;23 0x000055a39098c30f clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x321330f)

#&#8203;24 0x000055a390994e15 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x321be15)

#&#8203;25 0x000055a38e4e7020 main (/opt/compiler-explorer/clang-trunk/bin/clang+++0xd6e020)

#&#8203;26 0x00007ff8586cdb97 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b97)

#&#8203;27 0x000055a38e5a263a _start (/opt/compiler-explorer/clang-trunk/bin/clang+++0xe2963a)

clang-11: error: clang frontend command failed due to signal (use -v to see invocation)

Compiler returned: 254

**Comment by usx95** [comment]
Confirmed. Still a issue in C++20. https://godbolt.org/z/oGPsnPYq7

**Comment by shafik** [comment]
It looks like this does not reproduce anymore: https://godbolt.org/z/no5qfvso6

**Comment by Endilll** [comment]
It was fixed on trunk after Clang 16: https://godbolt.org/z/vbvrW93E7
