### ISSUE TITLE
[AssumeBundles]  Missing AU.addRequired() call

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#45278]
|  |  |
| --- | --- |
| Bugzilla Link | [45933](https://llvm.org/bz45933) |
| Version | trunk |
| OS | Linux |
| CC | @OCHyams,@JonPsson,@Ralender |

## Extended Description 
It seems that the AssumeSimplify pass calls getAnalysis<AssumptionCacheTracker>() without requiring it, and I get:

clang ~/tmp/test.c -save-temps -c -S -O3 -mllvm -enable-knowledge-retention

PassAnalysisSupport.h:236:
Assertion `ResultPass && "getAnalysis*() called on an analysis that was not " "'required' by pass!"' failed

Is the following one-line patch good?

diff --git a/llvm/lib/Transforms/Utils/AssumeBundleBuilder.cpp b/llvm/lib/Transforms/Utils/AssumeBundleBuilder.cpp
index ee5e142..631661a 100644
--- a/llvm/lib/Transforms/Utils/AssumeBundleBuilder.cpp
+++ b/llvm/lib/Transforms/Utils/AssumeBundleBuilder.cpp
@@ -467,6 +467,7 @@ public:
 
   void getAnalysisUsage(AnalysisUsage &AU) const override {
     AU.setPreservesAll();
+    AU.addRequired<AssumptionCacheTracker>();
   }
 };

**Comment by Endilll** [comment]
This call was added, but before `AU.setPreservesAll()`.
https://github.com/llvm/llvm-project/blob/649cac3b627fa3d466b8807536c8be970cc8c32f/llvm/lib/Transforms/Utils/AssumeBundleBuilder.cpp#L609-L613
