### ISSUE TITLE
[LoopVectorizer] Assertion "Both operands to ICmp instruction are not of the same type!" failed.

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#45288]
|  |  |
| --- | --- |
| Bugzilla Link | [45943](https://llvm.org/bz45943) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced testcase](https://user-images.githubusercontent.com/55128014/143760739-bff067fd-dcb2-4442-af31-18d986ba4b6b.gz) |
| CC | @d0k,@fhahn,@JonPsson,@sjoerdmeijer |

## Extended Description 

opt -mtriple=systemz-unknown -mcpu=z13 -O3 -force-vector-interleave=2 -unroll-full-max-count=1 -o out.opt.ll tc_loopvec_icmpops.ll

llvm-project/llvm/include/llvm/IR/Instructions.h:1136: void llvm::ICmpInst::AssertOK(): Assertion `getOperand(0)->getType() == getOperand(1)->getType() && "Both operands to ICmp instruction are not of the same type!"' failed.
...
#&#8203;12 0x000002aa3f0e6364 llvm::LoopVectorizationPlanner::executePlan

**Comment by fhahn** [comment]
This should be fixed by 13bf6039c9ae  and doesn't crash any longer: https://llvm.godbolt.org/z/dYsbv65hG
