### ISSUE TITLE
[LoopUnrollPeel]  wrong-code with reduced test case

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#45284]
|  |  |
| --- | --- |
| Bugzilla Link | [45939](https://llvm.org/bz45939) |
| Version | trunk |
| OS | Linux |
| CC | @fhahn,@JonPsson |

## Extended Description 
int a[256];
int b, c, d;
main() {
  c = 0;
  for (; c < 256; c++)
    a[c] = c;
  for (; d; d++)
    ;
  printf("checksum = %X\n", b);
}

clang -O3 -march=z13 tc_peel2.i -o a.out -Wall; ./a.out
checksum = 0

clang -O3 -march=z13 tc_peel2.i -o a.out -Wall -mllvm -unroll-peel-count=2
checksum = 101

**Comment by fhahn** [comment]
This should be fixed by db45746821ab01a54f8df033991c3280c4284e3b and does not reproduce on current `main`. last bad version is 12.0.1: https://godbolt.org/z/zr44Y96e6
