### ISSUE TITLE
Inaccurate system requirements

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45318]
|  |  |
| --- | --- |
| Bugzilla Link | [45973](https://llvm.org/bz45973) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @Jnyfah |

## Extended Description 
The following pages list the minimal requirements for building LLVM: https://llvm.org/docs/GettingStarted.html#software

According to the page, it should be possible to build LLVM with GCC 5.1.0 or later.

I tried building LLVM on Linux with GCC 6.5.0 but it failed:

In file included from /home/atanas/llvm-project-10.0.0/libcxx/src/variant.cpp:9:0:
/home/noan/llvm-project-10.0.0/libcxx/include/variant: At global scope:
/home/noan/llvm-project-10.0.0/libcxx/include/variant:1140:26: error: parameter packs not expanded with ‘...’:
   using _Bases::operator()...;
                          ^
/home/noan/llvm-project-10.0.0/libcxx/include/variant:1140:26: note:         ‘_Bases’
/home/noan/llvm-project-10.0.0/libcxx/include/variant:1140:27: error: expected ‘;’ before ‘...’ token
   using _Bases::operator()...;
                           ^~~
/home/noan/llvm-project-10.0.0/libcxx/include/variant:1140:27: error: expected unqualified-id before ‘...’ token

This is how I configured the build:

cmake -G "Unix Makefiles" -DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra;compiler-rt;libcxx;libcxxabi;libunwind;lld;llvm;mlir;openmp;parallel-libs;pstl' -DCMAKE_INSTALL_PREFIX=/usr/local/llvm-10.0.0 -DCMAKE_BUILD_TYPE=Release LLVM_TARGETS_TO_BUILD=X86 ../llvm

I don't have GCC 7 installed at the moment, however I have GCC 8.4.0 which compiled LLVM problem-free.

I think that the minimum system requirement for GCC should be changed or the above problem fixed.

**Comment by arsenm** [comment]
The minimum gcc version was recently updated to 7.4
