### ISSUE TITLE
32 bit Sanitizer libs are not working with LLVM 9.0

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45336]
|  |  |
| --- | --- |
| Bugzilla Link | [45991](https://llvm.org/bz45991) |
| Version | 9.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Hi Team,

We have built llvm 9.0.0 with GCC 9 by enabling both 32 and 64-bit libraries.

Here the issue is both 32 and 64-bit Sanitizer libs are getting created, but the 32-bit libraries are not working as expected.

The Sanitizer 32 and 64-bit libraries are working fine with LLVM 9 with GCC 8.

The package build steps are the same for both, only the GCC version differs.

Please help us here and let me know if any more details needed from your end.

**Comment by arsenm** [comment]
Old release. "are not working as expected." doesn't explain what the problem is or how to reproduce.
