### ISSUE TITLE
Compilation error while compiling mfem

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45335]
|  |  |
| --- | --- |
| Bugzilla Link | [45990](https://llvm.org/bz45990) |
| Version | 9.0 |
| OS | Linux |
| Attachments | [cpp file (had to zip it)](https://user-images.githubusercontent.com/60944935/143760755-36d4904f-7f72-418b-a03a-009f8df6abb2.gz), [sh file](https://user-images.githubusercontent.com/60944935/143760756-c0f4a5aa-f1d9-4bea-8bc8-2ec34d7d1f31.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @topperc,@DougGregor,@zygoloid |

## Extended Description 
Hello,
Trying to compile mfem with AOCC.2.1.0 has produced the following error:
Error 
1.      <eof> parser at end of file
2.      Per-module optimization passes
3.      Running pass 'CallGraph Pass Manager' on module 'fem/quadinterpolator.cpp'.
4.      Running pass 'Loop Block Pass' on function '@_ZN4mfemL11D2QValues2DILi2ELi3ELi6ELi4EEEviRKNS_5ArrayIdEERKNS_6VectorERS5_iii'
 #&#8203;0 0x00007f5fa57dab8a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libLLVM-9.so+0x854b8a)
 #&#8203;1 0x00007f5fa57d8a8a llvm::sys::RunSignalHandlers() (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libLLVM-9.so+0x852a8a)
 #&#8203;2 0x00007f5fa57d8bb9 SignalHandler(int) (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libLLVM-9.so+0x852bb9)
 #&#8203;3 0x00007f5fa4d79890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)
 #&#8203;4 0x00007f5fa0ea6e97 raise (/lib/x86_64-linux-gnu/libc.so.6+0x3ee97)
 #&#8203;5 0x00007f5fa0ea8801 abort (/lib/x86_64-linux-gnu/libc.so.6+0x40801)
 #&#8203;6 0x00007f5fa0e9839a (/lib/x86_64-linux-gnu/libc.so.6+0x3039a)
 #&#8203;7 0x00007f5fa0e98412 (/lib/x86_64-linux-gnu/libc.so.6+0x30412)
 #&#8203;8 0x00007f5fa69dea73 (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libLLVM-9.so+0x1a58a73)
 #&#8203;9 0x00007f5fa6157872 llvm::SplitEdge(llvm::BasicBlock*, llvm::BasicBlock*, llvm::DominatorTree*, llvm::LoopInfo*, llvm::MemorySSAUpdater*) (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libLLVM-9.so+0x11d1872)
#&#8203;10 0x00007f5fa620923c llvm::CanonicalizeLoops::AddDedicatedLoopBlocks(llvm::Loop*) (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libLLVM-9.so+0x128323c)
#&#8203;11 0x00007f5fa620ac71 llvm::CanonicalizeLoops::CanonicalizeRotatedLoop(llvm::Loop*) (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libLLVM-9.so+0x1284c71)
#&#8203;12 0x00007f5fa64e1279 llvm::LoopBlock::runOnFunction(llvm::Function&) (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libLLVM-9.so+0x155b279)
#&#8203;13 0x00007f5fa58fedeb llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libLLVM-9.so+0x978deb)
#&#8203;14 0x00007f5fa6a09e4e (anonymous namespace)::CGPassManager::runOnModule(llvm::Module&) (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libLLVM-9.so+0x1a83e4e)
#&#8203;15 0x00007f5fa58ff991 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libLLVM-9.so+0x979991)
#&#8203;16 0x00007f5fa2deb686 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libclang-cpp.so.9+0x1253686)
#&#8203;17 0x00007f5fa305763c clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libclang-cpp.so.9+0x14bf63c)
#&#8203;18 0x00007f5fa235f1e9 clang::ParseAST(clang::Sema&, bool, bool) (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libclang-cpp.so.9+0x7c71e9)
#&#8203;19 0x00007f5fa30552df clang::CodeGenAction::ExecuteAction() (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libclang-cpp.so.9+0x14bd2df)
#&#8203;20 0x00007f5fa366beb9 clang::FrontendAction::Execute() (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libclang-cpp.so.9+0x1ad3eb9)
#&#8203;21 0x00007f5fa362cdd2 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libclang-cpp.so.9+0x1a94dd2)
#&#8203;22 0x00007f5fa36da313 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/odyhpc/aocc-compiler-2.1.0/bin/../lib/libclang-cpp.so.9+0x1b42313)
#&#8203;23 0x0000000000413450 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/odyhpc/aocc-compiler-2.1.0/bin/clang-9+0x413450)
#&#8203;24 0x000000000040d5ed main (/home/odyhpc/aocc-compiler-2.1.0/bin/clang-9+0x40d5ed)
#&#8203;25 0x00007f5fa0e89b97 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b97)
#&#8203;26 0x000000000040ea6e _start (/home/odyhpc/aocc-compiler-2.1.0/bin/clang-9+0x40ea6e)
clang-9: error: unable to execute command: Aborted (core dumped)
clang-9: error: clang frontend command failed due to signal (use -v to see invocation)
AOCC.LLVM.2.1.0.B1030.2019_11_12 clang version 9.0.0 (CLANG: Build#1030) (based on LLVM AOCC.LLVM.2.1.0.B1030.2019_11_12)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/odyhpc/aocc-compiler-2.1.0/bin
clang-9: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-9: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-9: note: diagnostic msg: /tmp/quadinterpolator-63389b.cpp
clang-9: note: diagnostic msg: /tmp/quadinterpolator-63389b.sh
clang-9: note: diagnostic msg:

********************
makefile:422: recipe for target 'fem/quadinterpolator.o' failed
make[1]: *** [fem/quadinterpolator.o] Error 254
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/odyhpc/LAGHOS/mfem'
makefile:463: recipe for target 'parallel' failed
make: *** [parallel] Error 2

The script is:
cd $HOME/LAGHOS
git clone https://github.com/mfem/mfem.git ./mfem
cd mfem/
git checkout master
make parallel -j 2
(NOTE: I previously installed HYPRE & METIS as required in the Github repository)
Thanks

**Comment by Endilll** [comment]
Can't reproduce using Clang 8 through 10 with assertions enabled.
It should be noted that cc1 invocation contains `-itodcalls` and `-itodcallsbyclone`, so it could very well be a downstream issue.
