### ISSUE TITLE
need to pass codegen options through to lto

### ISSUE THREAD

**Issue by nlewycky** [llvm/llvm-project#4533]
|  |  |
| --- | --- |
| Bugzilla Link | [4161](https://llvm.org/bz4161) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Some LTO options such as PIC and FP elimination should be passed from the frontend through to the backend. For debugging, it'd be nice to pass -fast through too.

Some of the options (like target triple) are stored in the .bc, but we need to sort out what options go where and how we make them flow through from llvm-gcc to the gold plugin, into libLTO and make it all the way to codegen. Every option that llvm-gcc supports should probably have a matching option unless it's in the bitcode.

**Comment by arsenm** [comment]
This is done, frame pointer is encoded in a function attribute
