### ISSUE TITLE
Webassemly asm text parser/generator doesn't handle custom data section.

### ISSUE THREAD

**Issue by sbc100** [llvm/llvm-project#45368]
|  |  |
| --- | --- |
| Bugzilla Link | [46023](https://llvm.org/bz46023) |
| Version | trunk |
| OS | Linux |
| CC | @aardappel,@dschuff |

## Extended Description 
Currently I can write the following llvm code and it will generate a working working object file:

```
@&#8203;foo = global i32 42, section "mysection", align 4
```

However if I output to assembly I get:

```
$ llc --mtriple=wasm32 --asm-verbose=false test.ll -o -

.type foo,@object
  .section  mysection,"aw",@
  .globl  foo
  .p2align 2
foo:
  .int32  42
  .size foo, 4

```

Which the assembly reader rejects:

```
$ llvm-mc -triple=wasm32-unknown-unknown test.s
test.s:2:23: error: unknown section kind: mysection
  .section  mysection,"",@
```

**Comment by aardappel** [comment]
There's no more `unknown section kind` error anymore, the current code defaults to a data section already if it can't recognize a name prefix in the `.section` parsing.

Currently, the above code produces:
```
        .text
test.s:2:23: error: unknown flag
  .section  mysection,"aw",@
                      ^
        .globl  foo
        .p2align        2
foo:
test.s:6:3: error: Wasm doesn't support data symbols in text sections
  .int32  42
  ^
test.s:6:11: error: data directive must occur in a data segment: 42
  .int32  42
          ^
        .size   foo, 4
```

`a` is "allocatable" and `w` is "writable" in ELF, do we have an equivalent in Wasm @sbc100 ?

**Comment by aardappel** [comment]
If I add:

```
      case 'a':
      case 'w':
        // Ignore for ELF compat.
        break;
```

Then the test file passes. Is this desirable?

**Comment by sbc100** [comment]
Presumably it would be better not to generate those flags at all if we don't support them?   (Out of interest what do they mean?  Should we try to support them?)

**Comment by sbc100** [comment]
Sorry I should have read my own comment above... I don't think we want to support either those since they don't make sense in the wasm runtime today.

**Comment by aardappel** [comment]
With current code, `@foo = global i32 42, section "mysection", align 4` for me outputs no `aw` flags (as @sbc100 pointed out in `MCSectionWasm::PrintSwitchToSection`):

```
        .text
        .file   "test.ll"
        .type   foo,@object
        .section        mysection,"",@
        .globl  foo
        .p2align        2
foo:
        .int32  42
        .size   foo, 4
```

So looks like this is not a problem anymore.
