### ISSUE TITLE
std::to_chars generates exception code

### ISSUE THREAD

**Issue by hanickadot** [llvm/llvm-project#45361]
|  |  |
| --- | --- |
| Bugzilla Link | [46016](https://llvm.org/bz46016) |
| Version | 10.0 |
| OS | All |
| CC | @ldionne,@mclow |

## Extended Description 
`std::to_chars` is generating exception handling code, because internals functions are not marked `noexcept` and clang can't proof they won't throw:

```
namespace __itoa {
_LIBCPP_FUNC_VIS char* __u64toa(uint64_t __value, char* __buffer);
_LIBCPP_FUNC_VIS char* __u32toa(uint32_t __value, char* __buffer);
}
```

if you add `noexcept` there it will generate more efficient code:

https://compiler-explorer.com/z/H29awf

**Comment by philnik777** [comment]
This bug has been addressed by https://llvm.org/D80379.
