### ISSUE TITLE
[LICM with cfl-aa=both]  wrong code

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#45382]
|  |  |
| --- | --- |
| Bugzilla Link | [46037](https://llvm.org/bz46037) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced testcase](https://user-images.githubusercontent.com/55128014/143760768-0a79b053-fd59-498f-9d85-378f0998ffc6.gz) |
| CC | @gburgessiv,@aqjune,@nunoplopes,@JonPsson |

## Extended Description 

clang -O3 -march=z13 tc_cfl-aa.i -o ./a.out -w ; ./a.out
checksum = 4
$LLVM_BUILD/bin/clang -O3 -march=z13 tc_cfl-aa.i -o ./a.out -w -mllvm -use-cfl-aa=both; ./a.out                                                                                              
checksum = 0

The reduced test program should print '4'.

It seems that LICM is hoisting the load of @&#8203;d_ptr which seems wrong since @&#8203;PtoP is a pointer to pointer which alters @&#8203;d_ptr before @&#8203;d_ptr is derefenced.

**Comment by nunoplopes** [comment]
CFL AA was removed from LLVM. So, closing this.
