### ISSUE TITLE
libc++ licensing incosistency

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45407]
|  |  |
| --- | --- |
| Bugzilla Link | [46062](https://llvm.org/bz46062) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic,@mclow |

## Extended Description 
Hi

There seems to be a licensing inconsistency about libc++. The website states
that libc++ is dual-licensed and the top level LICENSE.txt also states:

-------------
The libc++ library is dual licensed under both the University of Illinois
"BSD-Like" license and the MIT license.  As a user of this code you may choose
to use it under either license.  As a contributor, you agree to allow your code
to be used under both.
-------------

However each source file is licensed under Apache 2 with LLVM Exceptions
and they point to https://llvm.org/LICENSE.txt which does not mention anything
about a dual license.

It would be nice to clarify this.

Thank you

**Comment by philnik777** [comment]
I can't find any mention of the license on libcxx.llvm.org and @efriedma-quic said it's been fixed, so I'm closing this.
