### ISSUE TITLE
Failure to use vfmadd132sd when appropriate

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#45424]
|  |  |
| --- | --- |
| Bugzilla Link | [46079](https://llvm.org/bz46079) |
| Version | trunk |
| OS | Linux |
| Depends On | llvm/llvm-project#49566  |
| CC | @andykaylor,@topperc,@davidbolvansky,@RKSimon,@mibintc,@zygoloid,@rotateright,@wjristow |

## Extended Description 
double f(double a, double b, double c)
{
    return a * b + c;
}

When compiled with `-O3 -mavx512f`, GCC produces this :

f(double, double, double):
  vfmadd132sd xmm0, xmm2, xmm1
  ret

Clang produces this :

f(double, double, double): # @&#8203;f(double, double, double)
  vmulsd xmm0, xmm0, xmm1
  vaddsd xmm0, xmm0, xmm2
  ret

**Comment by RKSimon** [comment]
https://godbolt.org/z/xqzjqz9vz

Duplicate of Issue #49566

Fixed in f04e387055e495e3e14570087d68e93593cf2918
