### ISSUE TITLE
AllowShortBlocksOnASingleLine fails on ForEachMacros

### ISSUE THREAD

**Issue by 2919fa4a-95ef-43c0-86e6-9d0adabeb3b0** [llvm/llvm-project#45432]
|  |  |
| --- | --- |
| Bugzilla Link | [46087](https://llvm.org/bz46087) |
| Version | 10.0 |
| OS | Windows NT |
| CC | @mkurdej,@mydeveloperday,@GoBigorGoHome |

## Extended Description 
.clang-format:

```
ForEachMacros: ['rng']
AllowShortBlocksOnASingleLine: Never
```

Before:

```
rng (i, 0, 10) { 
  std::cout << i; 
}
```

After:

`rng (i, 0, 10) { std::cout << i; }`

Expect:

```
rng (i, 0, 10) { 
  std::cout << i; 
}
```

**Comment by mydeveloperday** [comment]
as there is no further action on this fix since Jan 2021, I'll take over this review.
