### ISSUE TITLE
-ast-dump assert on GCC9.x std::string

### ISSUE THREAD

**Issue by erichkeane** [llvm/llvm-project#45456]
|  |  |
| --- | --- |
| Bugzilla Link | [46111](https://llvm.org/bz46111) |
| Version | trunk |
| OS | Windows NT |
| CC | @zygoloid |

## Extended Description 
Minimized from a compilation of std::string in GCC9.x, it seems the deduction guide ends up having an elaborated type specifier, but the assert claims otherwise.    The following test is a massive creduced version of the test, so the names are messed up.

First, the assert:

  | |-FunctionTemplateDecl 0x1196d290 <line:4:1, line:7:6> col:3 implicit <deduction guide for d>
  | | |-TemplateTypeParmDecl 0x1193e8d8 <line:4:11> col:19 typename depth 0 index 0
  | | |-TemplateTypeParmDecl 0x1193e960 <col:21> col:29 typename depth 0 index 1
  | | |-TemplateTypeParmDecl 0x1193ea10 <col:31, col:40> col:40 referenced typename depth 0 index 2 c
  | | `-CXXDeductionGuideDecl 0x1196d1e0 <line:7:3, col:6> col:3 implicit <deduction guide for d> '
llvm-project/clang/lib/AST/NestedNameSpecifier.cpp:304: void clang::NestedNameSpecifier::print(llvm::raw_ostream&, const clang::PrintingPolicy&, bool) const: Assertion `!isa<ElaboratedType>(T) && "Elaborated type in nested-name-specifier"' failed.

Stack Trace:
Stack dump:
0.      Program arguments: ./bin/clang @&#8203;crash.args
1.      <eof> parser at end of file
 #&#8203;0 0x00000000049a607c llvm::sys::PrintStackTrace(llvm::raw_ostream&) /iusers/ekeane1/workspaces/llvm-project/llvm/lib/Support/Unix/Signals.inc:564:22
 #&#8203;1 0x00000000049a610f PrintStackTraceSignalHandler(void*) /iusers/ekeane1/workspaces/llvm-project/llvm/lib/Support/Unix/Signals.inc:625:1
 #&#8203;2 0x00000000049a419f llvm::sys::RunSignalHandlers() /iusers/ekeane1/workspaces/llvm-project/llvm/lib/Support/Signals.cpp:68:20
 #&#8203;3 0x00000000049a5abf SignalHandler(int) /iusers/ekeane1/workspaces/llvm-project/llvm/lib/Support/Unix/Signals.inc:406:1
 #&#8203;4 0x00007fc76a2755e0 __restore_rt (/lib64/libpthread.so.0+0xf5e0)
 #&#8203;5 0x00007fc768dee1f7 raise (/lib64/libc.so.6+0x351f7)
 #&#8203;6 0x00007fc768def8e8 abort (/lib64/libc.so.6+0x368e8)
 #&#8203;7 0x00007fc768de7266 __assert_fail_base (/lib64/libc.so.6+0x2e266)
 #&#8203;8 0x00007fc768de7312 (/lib64/libc.so.6+0x2e312)
 #&#8203;9 0x000000000867e80e clang::NestedNameSpecifier::print(llvm::raw_ostream&, clang::PrintingPolicy const&, bool) const (.localalias.0) /iusers/ekeane1/workspaces/llvm-project/clang/lib/AST/NestedNameSpecifier.cpp:303:5
#&#8203;10 0x0000000008772706 (anonymous namespace)::TypePrinter::printDependentNameBefore(clang::DependentNameType const*, llvm::raw_ostream&) /iusers/ekeane1/workspaces/llvm-project/clang/lib/AST/TypePrinter.cpp:1437:37
#&#8203;11 0x000000000876d41d (anonymous namespace)::TypePrinter::printBefore(clang::Type const*, clang::Qualifiers, llvm::raw_ostream&) /iusers/ekeane1/workspaces/llvm-project/build/tools/clang/include/clang/AST/TypeNodes.inc:39:1
#&#8203;12 0x000000000876cdbc (anonymous namespace)::TypePrinter::print(clang::Type const*, clang::Qualifiers, llvm::raw_ostream&, llvm::StringRef) /iusers/ekeane1/workspaces/llvm-project/clang/lib/AST/TypePrinter.cpp:186:9
#&#8203;13 0x000000000876cd3c (anonymous namespace)::TypePrinter::print(clang::QualType, llvm::raw_ostream&, llvm::StringRef) /iusers/ekeane1/workspaces/llvm-project/clang/lib/AST/TypePrinter.cpp:174:1
#&#8203;14 0x00000000087702f6 (anonymous namespace)::TypePrinter::printFunctionProtoAfter(clang::FunctionProtoType const*, llvm::raw_ostream&) /iusers/ekeane1/workspaces/llvm-project/clang/lib/AST/TypePrinter.cpp:827:5
#&#8203;15 0x000000000876de31 (anonymous namespace)::TypePrinter::printAfter(clang::Type const*, clang::Qualifiers, llvm::raw_ostream&) /iusers/ekeane1/workspaces/llvm-project/build/tools/clang/include/clang/AST/TypeNodes.inc:47:1
#&#8203;16 0x000000000876cdea (anonymous namespace)::TypePrinter::print(clang::Type const*, clang::Qualifiers, llvm::raw_ostream&, llvm::StringRef) /iusers/ekeane1/workspaces/llvm-project/clang/lib/AST/TypePrinter.cpp:183:70
#&#8203;17 0x0000000008774326 clang::QualType::getAsStringInternal(clang::Type const*, clang::Qualifiers, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, clang::PrintingPolicy const&) /iusers/ekeane1/workspaces/llvm-project/clang/lib/AST/TypePrinter.cpp:1990:43
#&#8203;18 0x00000000087740f6 clang::QualType::getAsString[abi:cxx11](clang::Type const*, clang::Qualifiers, clang::PrintingPolicy const&) /iusers/ekeane1/workspaces/llvm-project/clang/lib/AST/TypePrinter.cpp:1960:10
#&#8203;19 0x0000000008658e40 clang::QualType::getAsString[abi:cxx11](clang::SplitQualType, clang::PrintingPolicy const&) /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/Type.h:994:3
#&#8203;20 0x000000000871ab09 clang::TextNodeDumper::dumpBareType(clang::QualType, bool) /iusers/ekeane1/workspaces/llvm-project/clang/lib/AST/TextNodeDumper.cpp:394:58
#&#8203;21 0x000000000871ac60 clang::TextNodeDumper::dumpType(clang::QualType) /iusers/ekeane1/workspaces/llvm-project/clang/lib/AST/TextNodeDumper.cpp:407:1
#&#8203;22 0x000000000871f10d clang::TextNodeDumper::VisitFunctionDecl(clang::FunctionDecl const*) /iusers/ekeane1/workspaces/llvm-project/clang/lib/AST/TextNodeDumper.cpp:1320:39
#&#8203;23 0x000000000873bae9 clang::declvisitor::Base<llvm::make_const_ptr, clang::TextNodeDumper, void>::VisitCXXDeductionGuideDecl(clang::CXXDeductionGuideDecl const*) /iusers/ekeane1/workspaces/llvm-project/build/tools/clang/include/clang/AST/DeclNodes.inc:405:1
#&#8203;24 0x0000000008736338 clang::declvisitor::Base<llvm::make_const_ptr, clang::TextNodeDumper, void>::Visit(clang::Decl const*) /iusers/ekeane1/workspaces/llvm-project/build/tools/clang/include/clang/AST/DeclNodes.inc:405:1
#&#8203;25 0x000000000871a1b8 clang::TextNodeDumper::Visit(clang::Decl const*) /iusers/ekeane1/workspaces/llvm-project/clang/lib/AST/TextNodeDumper.cpp:281:1
#&#8203;26 0x00000000082a370b clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()::operator()() const /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/ASTNodeTraverser.h:83:5
#&#8203;27 0x00000000082acbab void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper)::'lambda'(bool)::operator()(bool) const /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/TextNodeDumper.h:103:20
#&#8203;28 0x00000000082c783e std::_Function_handler<void (bool), void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper)::'lambda'(bool)>::_M_invoke(std::_Any_data const&, bool&&) /nfs/pdx/proj/icl/rdrive/ref/gcc/8.3.0/rhel70/efi2/include/c++/8.3.0/bits/std_function.h:299:7
#&#8203;29 0x00000000082acfba std::function<void (bool)>::operator()(bool) const /nfs/pdx/proj/icl/rdrive/ref/gcc/8.3.0/rhel70/efi2/include/c++/8.3.0/bits/std_function.h:687:71
#&#8203;30 0x00000000082acbeb void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper)::'lambda'(bool)::operator()(bool) const /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/TextNodeDumper.h:72:10
#&#8203;31 0x00000000082c783e std::_Function_handler<void (bool), void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper)::'lambda'(bool)>::_M_invoke(std::_Any_data const&, bool&&) /nfs/pdx/proj/icl/rdrive/ref/gcc/8.3.0/rhel70/efi2/include/c++/8.3.0/bits/std_function.h:299:7
#&#8203;32 0x00000000082acfba std::function<void (bool)>::operator()(bool) const /nfs/pdx/proj/icl/rdrive/ref/gcc/8.3.0/rhel70/efi2/include/c++/8.3.0/bits/std_function.h:687:71
#&#8203;33 0x00000000082aceba void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper) /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/TextNodeDumper.h:116:33
#&#8203;34 0x00000000082a587f void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(clang::ASTDumper) /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/TextNodeDumper.h:49:3
#&#8203;35 0x00000000082a38ae clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*) /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/ASTNodeTraverser.h:103:3
#&#8203;36 0x00000000082a581f clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::dumpDeclContext(clang::DeclContext const*) /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/ASTNodeTraverser.h:252:5
#&#8203;37 0x00000000082a3862 clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()::operator()() const /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/ASTNodeTraverser.h:100:11
#&#8203;38 0x00000000082acbab void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper)::'lambda'(bool)::operator()(bool) const /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/TextNodeDumper.h:103:20
#&#8203;39 0x00000000082c783e std::_Function_handler<void (bool), void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper)::'lambda'(bool)>::_M_invoke(std::_Any_data const&, bool&&) /nfs/pdx/proj/icl/rdrive/ref/gcc/8.3.0/rhel70/efi2/include/c++/8.3.0/bits/std_function.h:299:7
#&#8203;40 0x00000000082acfba std::function<void (bool)>::operator()(bool) const /nfs/pdx/proj/icl/rdrive/ref/gcc/8.3.0/rhel70/efi2/include/c++/8.3.0/bits/std_function.h:687:71
#&#8203;41 0x00000000082aceba void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper) /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/TextNodeDumper.h:116:33
#&#8203;42 0x00000000082a587f void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(clang::ASTDumper) /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/TextNodeDumper.h:49:3
#&#8203;43 0x00000000082a38ae clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*) /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/ASTNodeTraverser.h:103:3
#&#8203;44 0x00000000082a581f clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::dumpDeclContext(clang::DeclContext const*) /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/ASTNodeTraverser.h:252:5
#&#8203;45 0x00000000082a3862 clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()::operator()() const /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/ASTNodeTraverser.h:100:11
#&#8203;46 0x00000000082acbab void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper)::'lambda'(bool)::operator()(bool) const /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/TextNodeDumper.h:103:20
#&#8203;47 0x00000000082c783e std::_Function_handler<void (bool), void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper)::'lambda'(bool)>::_M_invoke(std::_Any_data const&, bool&&) /nfs/pdx/proj/icl/rdrive/ref/gcc/8.3.0/rhel70/efi2/include/c++/8.3.0/bits/std_function.h:299:7
#&#8203;48 0x00000000082acfba std::function<void (bool)>::operator()(bool) const /nfs/pdx/proj/icl/rdrive/ref/gcc/8.3.0/rhel70/efi2/include/c++/8.3.0/bits/std_function.h:687:71
#&#8203;49 0x00000000082acd6a void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper) /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/TextNodeDumper.h:61:25
#&#8203;50 0x00000000082a587f void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(clang::ASTDumper) /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/TextNodeDumper.h:49:3
#&#8203;51 0x00000000082a38ae clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*) /iusers/ekeane1/workspaces/llvm-project/clang/include/clang/AST/ASTNodeTraverser.h:103:3
#&#8203;52 0x000000000829fa3d clang::Decl::dump(llvm::raw_ostream&, bool, clang::ASTDumpOutputFormat) const /iusers/ekeane1/workspaces/llvm-project/clang/lib/AST/ASTDumper.cpp:193:77
#&#8203;53 0x000000000551a14d (anonymous namespace)::ASTPrinter::print(clang::Decl*) /iusers/ekeane1/workspaces/llvm-project/clang/lib/Frontend/ASTConsumers.cpp:96:5
#&#8203;54 0x0000000005519d59 (anonymous namespace)::ASTPrinter::HandleTranslationUnit(clang::ASTContext&) /iusers/ekeane1/workspaces/llvm-project/clang/lib/Frontend/ASTConsumers.cpp:48:23
#&#8203;55 0x0000000007210892 clang::ParseAST(clang::Sema&, bool, bool) /iusers/ekeane1/workspaces/llvm-project/clang/lib/Parse/ParseAST.cpp:178:14
#&#8203;56 0x00000000054ad9f5 clang::ASTFrontendAction::ExecuteAction() /iusers/ekeane1/workspaces/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1060:11
#&#8203;57 0x00000000054ad35d clang::FrontendAction::Execute() /iusers/ekeane1/workspaces/llvm-project/clang/lib/Frontend/FrontendAction.cpp:957:38
#&#8203;58 0x0000000005448ac7 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /iusers/ekeane1/workspaces/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:973:42
#&#8203;59 0x000000000560e530 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /iusers/ekeane1/workspaces/llvm-project/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:282:38
#&#8203;60 0x000000000208e24c cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /iusers/ekeane1/workspaces/llvm-project/clang/tools/driver/cc1_main.cpp:240:40
#&#8203;61 0x0000000002084257 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) /iusers/ekeane1/workspaces/llvm-project/clang/tools/driver/driver.cpp:330:20
#&#8203;62 0x0000000002084958 main /iusers/ekeane1/workspaces/llvm-project/clang/tools/driver/driver.cpp:407:26
#&#8203;63 0x00007fc768ddac05 __libc_start_main (/lib64/libc.so.6+0x21c05)
#&#8203;64 0x0000000002082af9 _start (./bin/clang+0x2082af9)

My response file (AKA, command line args):
"-cc1"
-std=c++17"
"-ast-dump"
"-x"
"c++"
"preproc.pp"

The source:

   namespace a {
   template <typename> struct b;
   namespace {
   template <typename, typename, typename c> struct d {
     typedef a::b<c> e;
     typedef typename e::f f;
     d(f);
   };
   template <typename g, typename h = g, typename i> d(g, i)->d<h, h, i>;
   } // namespace
  } // namespace a

The value of 'T' when it crashes is:

ElaboratedType 0x10361cb0 'a::b<c>' sugar dependent                                                                                                                                                                                            
`-TemplateSpecializationType 0x10361c60 'b<c>' dependent b                                                                                                                                                                                     
  `-TemplateArgument type 'c' 

Anyone have an idea on where to start? Should we be de-sugaring in this case to handle the elaborated type cases?  Should we not be creating the deduction guides with the elaborated type in the first place?  Or should the assert simply be removed?

**Comment by cor3ntin** [comment]
No longer crashes on trunk!
