### ISSUE TITLE
Crash on implicit conversion involving const ref to const pointer binding to a non-const pointer

### ISSUE THREAD

**Issue by a5fec13e-39c8-49b2-b3dd-e7d891b4dfc7** [llvm/llvm-project#45474]
|  |  |
| --- | --- |
| Bugzilla Link | [46129](https://llvm.org/bz46129) |
| Version | 10.0 |
| OS | Linux |
| Attachments | [Source code](https://user-images.githubusercontent.com/92601461/143760802-44afcc82-0217-42e4-9419-2ae0013b93d1.gz), [geerated run scropt](https://user-images.githubusercontent.com/92601461/143760803-70e147de-d3e7-4a77-b28d-6d2cd10c8831.gz) |
| CC | @dwblaikie,@DougGregor,@zygoloid |

## Extended Description 

For the attached source, clang++ in debug mode errors out with:
can't implicitly cast lvalue to rvalue with this cast kind
UNREACHABLE executed at /local/strasser/llvm-10.0.0.src/tools/clang/lib/Sema/Sema.cpp:537!

I think the source is reduced almost to the max.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 11: https://godbolt.org/z/bEjTxs5qP
