### ISSUE TITLE
Failure to optimize compare and bitwise and with same operands properly (stuck at intermediate transformation)

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#45478]
|  |  |
| --- | --- |
| Bugzilla Link | [46133](https://llvm.org/bz46133) |
| Version | trunk |
| OS | Linux |
| CC | @LebedevRI,@RKSimon,@nikic,@rotateright |

## Extended Description 
```
bool f(int x, int y)
{
    if ((unsigned)x >= y)
        return false;

    return (x & 1) == 0;
}
```
This can be optimized to `return ~x & ((unsigned)x < y);`, but is only optimized to `return ((unsigned)x < y) & !(x & 1);`. Furthermore, `return ((unsigned)x < y) & !(x & 1);` by itself gets optimized to `return ~x & ((unsigned)x < y);`, so the code above should also get optimized to that.

**Comment by GabrielRavier** [comment]
Looks like this is fixed on trunk ?

**Comment by RKSimon** [comment]
This was fixed by clang 14.x:
```ll
define  zeroext i1 @PR46133_f0(i32 noundef %x) {
entry:
  %0 = and i32 %x, -15
  %or.cond18 = icmp eq i32 %0, 0
  ret i1 %or.cond18
}

define zeroext i1 @PR46133_f1(i32 noundef %x, i32 noundef %y) {
entry:
  %cmp.not = icmp ult i32 %x, %y
  %and = and i32 %x, 1
  %cmp1 = icmp eq i32 %and, 0
  %retval.0 = and i1 %cmp.not, %cmp1
  ret i1 %retval.0
}
```
```asm
_Z10PR46133_f0i: # @_Z10PR46133_f0i
  testl $-15, %edi
  sete %al
  retq

_Z10PR46133_f1ii: # @_Z10PR46133_f1ii
  cmpl %esi, %edi
  setb %cl
  testb $1, %dil
  sete %al
  andb %cl, %al
  retq
```
