### ISSUE TITLE
dragonegg regparm uses incorrect calling convention with structures

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#4548]
|  |  |
| --- | --- |
| Bugzilla Link | [4176](https://llvm.org/bz4176) |
| Version | unspecified |
| OS | Linux |
| CC | @lattner |

## Extended Description 
struct a {unsigned char a,b,c;};
__attribute((regparm(1))) int a(struct a x) { return x.a+x.b+x.c; }
struct c {unsigned x,y;};
__attribute((regparm(2))) int d(struct c x) { return x.x+x.y; }
struct h {int a:5,b:5,c:5;};
__attribute((regparm(3))) int h(struct h x) { return x.a+x.b+x.c; }

llvm-gcc passes all of the above in memory instead of registers, which is not compatible with gcc.  See bug 3782 comment 2 for more related testcases.

These are manufactured testcases, so I'm not sure they matter much, but I figured I should file it for completeness.

**Comment by asl** [comment]
Dragonegg is obsolete
