### ISSUE TITLE
[AVR] Implement a subclass of clang::ABIInfo that is binary-compatible with AVR-GCC

### ISSUE THREAD

**Issue by dylanmckay** [llvm/llvm-project#45485]
|  |  |
| --- | --- |
| Bugzilla Link | [46140](https://llvm.org/bz46140) |
| Version | unspecified |
| OS | All |
| CC | @aykevl,@benshi001,@zygoloid |

## Extended Description 
Currently, AVR under Clang uses the default ABI implementation - clang::DefaultABIInfo.

There will be cases where the default ABI implementation is binary-incompatible with AVR-GCC. A new AVR-specific calling convention ABIInfo subclass should be written.

**Comment by benshi001** [comment]
The ABI of AVR/AVRTiny  is fully implemented in https://reviews.llvm.org/D120475,

according to document https://gcc.gnu.org/wiki/avr-gcc#Calling_Convention

**Comment by tstellar** [comment]
This issue was not resolved in time for 14.0.0 and will need to be fixed in the next release (14.0.1).  If you disagree with this or you feel there was a mistake, please change the milestone back to 'LLVM 14.0.0 Release' so we can discuss.

**Comment by benshi001** [comment]
Can anybody help me review my patch? The code owner of AVR and other AVR contributors do not give me any feedback. Actually this is a simple change. I am quite sure my solution is correct.

**Comment by tstellar** [comment]
@benshi001 It's usually acceptable to ping the patch once a week if you are having trouble getting reviews.  The reviewer is more likely to see a comment on the patch than on these issues. @dylanmckay

**Comment by benshi001** [comment]
fixed and committed as https://github.com/llvm/llvm-project/commit/51585aa240de6ef07979345de5406483d7393b7b

**Comment by tstellar** [comment]
@aykevl @dylanmckay  What do you think  about backporting this? https://github.com/llvm/llvm-project/commit/51585aa240de6ef07979345de5406483d7393b7b

**Comment by tstellar** [comment]
I can't get in touch with the AVR maintainers, but I think this is OK to merge.  It's very self-contained and seems like a useful fix.

**Comment by tstellar** [comment]
Merged: 10d442522b1afa263f4424478ef62d80c2a8b484

**Comment by tstellar** [comment]
Merged: 10d442522b1a

**Comment by daltenty** [comment]
@tstellar looks like this fix actually had two commits to it, the second which updates the `AVRMcus` initialization is missing from the `14.x` release branch: https://github.com/llvm/llvm-project/commit/86c1d075bb32101fe1c403e873ce33945bfa9626
Without it we are seeing some warnings (errors with -Werror) in the build:
```
clang/lib/Basic/Targets/AVR.cpp:33:41: error: missing field 'IsTiny' initializer [-Werror,-Wmissing-field-initializers]
```
(FYI @jakeegan)

**Comment by amy-kwan** [comment]
> @tstellar looks like this fix actually had two commits to it, the second which updates the `AVRMcus` initialization is missing from the `14.x` release branch: [86c1d07](https://github.com/llvm/llvm-project/commit/86c1d075bb32101fe1c403e873ce33945bfa9626) Without it we are seeing some warnings (errors with -Werror) in the build:
> 
> ```
> clang/lib/Basic/Targets/AVR.cpp:33:41: error: missing field 'IsTiny' initializer [-Werror,-Wmissing-field-initializers]
> ```
> 
> (FYI @jakeegan)

@tstellar Yes, I agree with @daltenty. This appears to affect both AIX and Linux, PowerPC.

Also, I noticed I believe the following patches would be needed to resolve this issue:
https://reviews.llvm.org/rG6edfe45a63125a8938a5bea13534a118b0e31023
https://reviews.llvm.org/rG86c1d075bb32101fe1c403e873ce33945bfa9626

The latter one actually resolves the `error: missing field 'IsTiny' initializer` but the initial patch not only allows the second patch to be applied cleanly, but also resolves a LIT failure in `target-invalid-cpu-note.c` that occurs if the second patch is applied without the first one.

**Comment by tstellar** [comment]
/cherry-pick 6edfe45a63125a8938a5bea13534a118b0e31023 86c1d075bb32101fe1c403e873ce33945bfa9626

**Comment by tstellar** [comment]
Do we have a -Werror buildbot that we could enable for the release branch?
