### ISSUE TITLE
aarch64 "bfm" matching fails with known-zero bits

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#45497]
|  |  |
| --- | --- |
| Bugzilla Link | [46152](https://llvm.org/bz46152) |
| Version | trunk |
| OS | Windows NT |
| CC | @Arnaud-de-Grandmaison-ARM,@smithp35 |

## Extended Description 
Testcase (https://godbolt.org/z/WSTfEg):

long test(long n, long m) {
  return (n & ~15) | ((m&15));
}
long test2(long n, long m) {
  return (n & ~15) | (((m<<2)&15));
}
long test3(long n, long m) {
  return (n << 4) | ((m&15));
}
long test4(long n, long m) {
  return (n << 4) | (((m<<2)&15));
}

test(long, long): // @&#8203;test(long, long)
  bfxil x0, x1, #&#8203;0, #&#8203;4
  ret
test2(long, long): // @&#8203;test2(long, long)
  lsl w9, w1, #&#8203;2
  and x8, x0, #&#8203;0xfffffffffffffff0
  and x9, x9, #&#8203;0xc
  orr x0, x9, x8
  ret
test3(long, long): // @&#8203;test3(long, long)
  bfi x1, x0, #&#8203;4, #&#8203;60
  mov x0, x1
  ret
test4(long, long): // @&#8203;test4(long, long)
  lsl w8, w1, #&#8203;2
  and x8, x8, #&#8203;0xc
  bfi x8, x0, #&#8203;4, #&#8203;60
  mov x0, x8
  ret

Somehow, the matching is getting confused; in test4, we generate an extra "and"; in test2 we completely fail to generate the bfxil.

Tripped over this looking into a different issue; not sure how important this is in practice.

**Comment by xgupta** [comment]
By looking in provided godbolt link, I think it is fixed on the trunk, in test4, there is no extra and in the test2 there is now bfi instruction also.

**Comment by xgupta** [comment]
Fixed on trunk https://godbolt.org/z/WSTfEg.
