### ISSUE TITLE
[LoopVectorizer]  Assertion `Part < UF && "Queried Vector Part is too large."' failed.

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#45500]
|  |  |
| --- | --- |
| Bugzilla Link | [46155](https://llvm.org/bz46155) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced testcase](https://user-images.githubusercontent.com/55128014/143760811-dce094af-fede-4629-a4f2-59aef9be0ef1.gz) |
| CC | @fhahn,@JonPsson |

## Extended Description 

opt -mtriple=s390x-linux-gnu -O3 tc_loopvec.ll -tiny-trip-count-interleave-threshold=4 -vectorizer-min-trip-count=8 -unroll-full-max-count=1

Vectorize/VPlan.h:137: bool llvm::VectorizerValueMap::hasVectorValue(llvm::Value*, unsigned int) const: Assertion `Part < UF && "Queried Vector Part is too large."' failed.
...
#&#8203;11 0x000002aa090fb0d2 llvm::InnerLoopVectorizer::fixCrossIterationPHIs()#11 0x000002aa090fb0d2 llvm::InnerLoopVectorizer::fixCrossIterationPHIs()
...

**Comment by fhahn** [comment]
I am unable to reproduce this on current `main`. There have been a lot of changes since the report, so this has likely been fixed.

Please re-open he issue with additional info if it still reproduces on your end.
