### ISSUE TITLE
Compiler error when using lambda inside if initializer

### ISSUE THREAD

**Issue by 71486b34-980c-41c3-a1d8-14aaed160fc6** [llvm/llvm-project#45587]
|  |  |
| --- | --- |
| Bugzilla Link | [46242](https://llvm.org/bz46242) |
| Version | 10.0 |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
Hi, I have discovered a slight bug (?). The following code does not compile when the lambda is used inside an if initializer

//Compiler error, error: redefinition of 'foo'
if(int foo = [&](){
            int foo = 0;
            return foo;
        }();
        foo)
{
    ...
}

While if the same code is used outside of an initilizer statement it works as expected. 

int foo = [&](){
            int foo = 0;
            return foo;
        }();
if(foo)
{
    return 1;
}

GCC compiles both cases fine, so I suspect this is a bug in the clang frontend.

Example on compiler explorer here:
https://godbolt.org/z/hcUZrx

**Comment by wheatman** [comment]
This was fixed between 14 and 15
https://godbolt.org/z/dhMah1WT8
code
```cpp
int main(){
    //Compiler error, redefinition of 'foo' with a different type: 'int' vs 'const int'
    if( int foo = [&](){
             int foo = 0;
             return foo;
         }();
         foo)
   {
      return 1;
   }

    //Works as expected
    const int bar = [&](){
             int bar = 1;
             return bar;
         }();

   return bar;
}
```

old error
```
<source>:4:18: error: redefinition of 'foo'
             int foo = 0;
                 ^
<source>:3:13: note: previous definition is here
    if( int foo = [&](){
            ^
<source>:3:13: error: cannot initialize a variable of type 'int' with an rvalue of type 'void'
    if( int foo = [&](){
            ^     ~~~~~~
2 errors generated.
Compiler returned: 1
```
