### ISSUE TITLE
Only first destructor is considered when constraints are used

### ISSUE THREAD

**Issue by qookei** [llvm/llvm-project#45614]
|  |  |
| --- | --- |
| Bugzilla Link | [46269](https://llvm.org/bz46269) |
| Version | trunk |
| OS | Linux |
| CC | @efriedma-quic,@qookei,@zygoloid,@saarraz |

## Extended Description 
When there are multiple destructors constrained with a requires clause, only the first one is considered, like in the following code:
```c++
template <bool B>
struct A {
    ~A() requires (B) { }
    ~A() requires (!B) { }
};

A<false> x;
```

The compiler reports the following error:
```
<source>:7:10: error: invalid reference to function '~A': constraints not satisfied
A<false> x;
         ^
<source>:3:20: note: because 'false' evaluated to false
    ~A() requires (B) { }
                   ^
```
The compiler prematurely reports an error about an invalid reference to the destructor because the constraint on the first variant was not satisfied, without checking the second variant.

The same code compiles with GCC without any problems.

**Comment by jwakely** [comment]
N.B. [P2493R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2493r0.html) proposes an update to `__cpp_concepts` to indicate support for this feature.

**Comment by miscco** [comment]
Is there anyone working on this. It also affects other features such as `expected` which creates conformance issues
