### ISSUE TITLE
Clangd stability fixes for 10.0.1

### ISSUE THREAD

**Issue by sam-mccall** [llvm/llvm-project#45615]
|  |  |
| --- | --- |
| Bugzilla Link | [46270](https://llvm.org/bz46270) |
| Version | unspecified |
| OS | Linux |
| Blocks | llvm/llvm-project#44654  |
| CC | @hokein,@kadircet,@tstellar |

## Extended Description 
As mentioned by email, these have already (erroneously) been merged.
Happy to revert any that we don't want.

Links are to the *branch* commits, they each reference the mainline commit from the description.

Trivial crash fixes in clangd:
https://github.com/llvm/llvm-project/commit/2378a6e4f136d574c294da72f2dde0225ba05e89
https://github.com/llvm/llvm-project/commit/30d05b898c6e84160507a66aabba6aceb129a9c7
https://github.com/llvm/llvm-project/commit/52f2d6d4b20dbc4c72f87c27e6e7375496fe0e38
https://github.com/llvm/llvm-project/commit/cb89646a4a888b8721adbc746e167f31fd484c11
https://github.com/llvm/llvm-project/commit/c90082432021360fae9f838502479b9113854de4
https://github.com/llvm/llvm-project/commit/d623a06a8247b1a04e74ad5f02a30ef351697e00

Other bugfixes in clangd:
https://github.com/llvm/llvm-project/commit/7918dbda298871cd4f7f622c4d880e9251986ffd
https://github.com/llvm/llvm-project/commit/357e79c2895736c9d202c79380e3e1f507080df3
https://github.com/llvm/llvm-project/commit/230b872c290d8c80a60accb06f3267e0703d0c49
https://github.com/llvm/llvm-project/commit/b6efa2365812f31667485c8948d49621ebf952f2

Trivial crash fixes in clang:
https://github.com/llvm/llvm-project/commit/3f4a753f597357db77fe395561234a50daa451b3
https://github.com/llvm/llvm-project/commit/d942a81c71a3f970857e92e98cc6503b61b589b0

The others that need a bit more explanation:

https://github.com/llvm/llvm-project/commit/41c5efc3f2f22475bf3290309c90e84713511711
https://github.com/llvm/llvm-project/commit/0530e2a811b08f13e8137c29f047ad6bd11967fa
These commits together fix a clangd crasher, and aren't trivial. The change is in clang/lib/Syntax but this class currently has no users other than clangd.

https://github.com/llvm/llvm-project/commit/cbc9b92df4582617314b08d1ecef41d355733874
This fixes a clang AST serialization bug in a fairly mechanical way (an obscure field wasn't serialized, now it is). It was found through clangd but in principle affects other clang users.

https://github.com/llvm/llvm-project/commit/38f995e4cb4c77c4a64cd1fedc1aeae91d8281cc
This is a fairly involved clangd-only fix for a high-profile crashing bug.

https://github.com/llvm/llvm-project/commit/cd477e7fdbf75642caa58b55b498a62f82a88bf7
This is a small refactoring of a clang-tidy check that was crashing in certain scenarios when embedded in clangd - we weren't able to trigger it outside this environment. The fix simply reduces the lifetime of an object to avoid reentrancy.

**Comment by arsenm** [comment]
Old release
