### ISSUE TITLE
cxxConstructExpr stopped matching templates

### ISSUE THREAD

**Issue by 15815413-e301-41d4-a9d1-90ddd684d31c** [llvm/llvm-project#45632]
|  |  |
| --- | --- |
| Bugzilla Link | [46287](https://llvm.org/bz46287) |
| Version | trunk |
| OS | All |
| CC | @zygoloid,@steveire,@ymand |

## Extended Description 
CLANG VERSION:

    $ third_party/llvm-build/Release+Asserts/bin/clang++ --version
    clang version 11.0.0 (https://github.com/llvm/llvm-project/ f7f1abdb8893af4a606ca1a8f5347a426e9c7f9e)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    InstalledDir: /usr/local/google/home/lukasza/src/chromium4/src/third_party/llvm-build/Release+Asserts/bin

REPRO INPUT FILE:

    template <typename T>
    struct MyTemplate {
      MyTemplate(int i) {}
    };
    
    void foo() {
      MyTemplate<char> mt(123);  // <- corresponds to the CXXConstructExpr node below
    }

REPRO INPUT FILE RENDERED AS AST:

    $ third_party/llvm-build/Release+Asserts/bin/clang++ -Xclang -ast-dump -std=c++14 tools/clang/rewrite_raw_ptr_fields/tests/affected-expr-original.cc
    ...
    `-FunctionDecl 0x5b38300 <line:6:1, line:8:1> line:6:6 foo 'void ()'
      `-CompoundStmt 0x5b65318 <col:12, line:8:1>
        `-DeclStmt 0x5b65300 <line:7:3, col:27>
          `-VarDecl 0x5b385b8 <col:3, col:26> col:20 mt 'MyTemplate<char>':'MyTemplate<char>' callinit
            `-CXXConstructExpr 0x5b652d0 <col:20, col:26> 'MyTemplate<char>':'MyTemplate<char>' 'void (int)'
              `-IntegerLiteral 0x5b38620 <col:23> 'int' 123

REPRO MATCHER:

    cxxConstructExpr().bind("ctor")

EXPECTED BEHAVIOR: The cxxConstructExpr matcher matches all CXXConstructExpr nodes from the AST

ACTUAL BEHAVIOR: The CXXConstructExpr above is not matched.

**Comment by 5chmidti** [comment]
This is fixed on trunk: https://godbolt.org/z/EhnYab91b and matches in `AsIs` and `IgnoreUnlessSpelledInSource` mode.
It is not possible to select the clang-query version to check in what version it was fixed.

**Comment by shafik** [comment]
@5chmidti so it sounds like this can be closed?

**Comment by AaronBallman** [comment]
I also think this has been fixed, so closing the issue; if you're still seeing an issue, please reopen with more details on how to reproduce.
