### ISSUE TITLE
Clang format lacks -D parameters to give defines

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45641]
|  |  |
| --- | --- |
| Bugzilla Link | [46296](https://llvm.org/bz46296) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mydeveloperday |

## Extended Description 
I have a code which always needs some defines gives with -D parameter to compile.

clang-format fails to analyze this code because that _D parameter cannto be given to clang-format.

-D parameter should be added to clang-format. to give it preprocessor defines.

**Comment by mydeveloperday** [comment]
no response, closing
