### ISSUE TITLE
Null dereference when generating module summary index with alias-to-ifunc

### ISSUE THREAD

**Issue by nextsilicon-itay-bookstein** [llvm/llvm-project#45685]
|  |  |
| --- | --- |
| Bugzilla Link | [46340](https://llvm.org/bz46340) |
| Version | trunk |
| OS | Windows NT |

## Extended Description 
Compiling the following piece of code works fine, but crashes with a null-dereference segfault when passing -flto:

static void foo_impl(void) {}
static void *foo_ifunc(void) { return &foo_impl; }
extern void foo(void) __attribute__((ifunc("foo_ifunc")));
extern __typeof(foo) foo2 __attribute__((alias("foo")));

The null-dereference is due to GlobalAlias::getBaseObject returning nullptr when the aliasee is a GlobalIFunc, and it happens specifically in ModuleSummaryAnalysis.cpp function computeAliasSummary.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 15: https://godbolt.org/z/ddzWjvavf
