### ISSUE TITLE
Wrong code generated for simple memory move loop

### ISSUE THREAD

**Issue by weiguozhi** [llvm/llvm-project#45680]
|  |  |
| --- | --- |
| Bugzilla Link | [46335](https://llvm.org/bz46335) |
| Version | trunk |
| OS | Linux |
| CC | @alinas,@topperc,@efriedma-quic,@fhahn,@RKSimon,@rotateright |

## Extended Description 
Compile following code with -O2

typedef struct SS
{
  int d[3];
  int a[6][4];
} S;

void foo(int d, S *p) 
{
    int i;
    for (i = 0; i < 3; i++)
    {   
      p->a[d][i] = p->a[d][i+1];
    }   
}

I got:

# %bb.0:                                # %entry
        movslq  %edi, %rax
        shlq    $4, %rax
        movl    24(%rax,%rsi), %ecx
        movl    %ecx, 20(%rsi,%rax)          // over written before read out
        movq    16(%rax,%rsi), %rcx
        movq    %rcx, 12(%rsi,%rax)
        retq

The 4 bytes word at 20(%rsi,%rax) is over written before read out, causes wrong result at 16(%rsi,%rax).

**Comment by fhahn** [comment]
I believe this can be closed as the offending commit has been reverted. @weiguozhi please re-open the issue if there's anything left to do.
