### ISSUE TITLE
tanf() returns a different value at -O0 and -Os

### ISSUE THREAD

**Issue by hedgehoggalore** [llvm/llvm-project#45721]
|  |  |
| --- | --- |
| Bugzilla Link | [46376](https://llvm.org/bz46376) |
| Version | trunk |
| OS | MacOS X |
| CC | @dwblaikie,@efriedma-quic,@hfinkel,@ldionne,@RKSimon,@mclow,@zygoloid,@rotateright |

## Extended Description 
For specific inputs std::tan() returns different values in Debug and Release. Here's the code that demonstrates the issue (tested in Xcode 10.3 (10G8) under macOS Mojave 10.14.6 (18G95)):

#include <cmath>

int main(int argc, const char * argv[]) {
    return std::tan (0.356189668f) == 0.372058868408203f ? 1 : 0;  // returns 1 in Debug
    //return std::tan (0.356189668f) == 0.372058898210526f ? 1 : 0;  // returns 1 in Release
}

**Comment by fhahn** [comment]
From reading back the discussion, Clang's behavior seems correct and there's nothing left to fix on the Clang/LLVM side. I'm closing the issue, but please re-open with additional details if that's incorrect.
