### ISSUE TITLE
Feature request: AUTOSAR checks set

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45724]
|  |  |
| --- | --- |
| Bugzilla Link | [46379](https://llvm.org/bz46379) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @EugeneZelenko |

## Extended Description 
clang-tidy provide many sets of checks for some coding standards like SEI CERT, and High Integrity C++; but it does not have a set and probably not all the automatable checks for AUTOSAR C++14.

It would be nice if the verification set for AUTOSAR C ++ 14 is included. This is becoming an important standard in security related systems.

There are some static analysis tools that already support it, but all of them are proprietary. 

There is nothing in the conditions of the standard that forbid any tool to include the set of check or make a reference to the standard.

**Comment by carlosgalvezp** [comment]
AUTOSAR module won't be added for the time being due to legal issues. See discussion:
https://reviews.llvm.org/D112730
