### ISSUE TITLE
LLVM ERROR: malformed uleb128

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45732]
|  |  |
| --- | --- |
| Bugzilla Link | [46387](https://llvm.org/bz46387) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @topperc,@jh7370,@pogo59,@rotateright |

## Extended Description 
>> building:DEBUG: llvm-nm failed on file G:\code\rd-html5\rdcore\src\librdphtml\librdphtml_desktopsharing.bc: return code 3221225501, error: LLVM ERROR: malformed uleb128, extends past end
>> PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
>> Stack dump:
>> 0.	Program arguments: G:/emsdk/upstream/bin\llvm-nm.exe G:\code\rd-html5\rdcore\src\librdphtml\librdphtml_desktopsharing.bc 
>>  #&#8203;0 0x00007ff730806df6 (G:\emsdk\upstream\bin\llvm-nm.exe+0x246df6)
>>  #&#8203;1 0x00007ff8c717cb7d (C:\WINDOWS\System32\ucrtbase.dll+0x6cb7d)
>>  #&#8203;2 0x00007ff8c717db81 (C:\WINDOWS\System32\ucrtbase.dll+0x6db81)
>>  #&#8203;3 0x00007ff7307c9fee (G:\emsdk\upstream\bin\llvm-nm.exe+0x209fee)
>>  #&#8203;4 0x00007ff7307c9e07 (G:\emsdk\upstream\bin\llvm-nm.exe+0x209e07)
>>  #&#8203;5 0x00007ff7307a12bc (G:\emsdk\upstream\bin\llvm-nm.exe+0x1e12bc)
>>  #&#8203;6 0x00007ff73079d4a3 (G:\emsdk\upstream\bin\llvm-nm.exe+0x1dd4a3)
>>  #&#8203;7 0x00007ff73079d20a (G:\emsdk\upstream\bin\llvm-nm.exe+0x1dd20a)
>>  #&#8203;8 0x00007ff73079d08f (G:\emsdk\upstream\bin\llvm-nm.exe+0x1dd08f)
>>  #&#8203;9 0x00007ff73079c8a5 (G:\emsdk\upstream\bin\llvm-nm.exe+0x1dc8a5)
>> #&#8203;10 0x00007ff73079240a (G:\emsdk\upstream\bin\llvm-nm.exe+0x1d240a)
>> #&#8203;11 0x00007ff730792627 (G:\emsdk\upstream\bin\llvm-nm.exe+0x1d2627)
>> #&#8203;12 0x00007ff73074cf36 (G:\emsdk\upstream\bin\llvm-nm.exe+0x18cf36)
>> #&#8203;13 0x00007ff7305c3a4a (G:\emsdk\upstream\bin\llvm-nm.exe+0x3a4a)
>> #&#8203;14 0x00007ff7305c33c8 (G:\emsdk\upstream\bin\llvm-nm.exe+0x33c8)
>> #&#8203;15 0x00007ff73093c310 (G:\emsdk\upstream\bin\llvm-nm.exe+0x37c310)
>> #&#8203;16 0x00007ff8c8da7bd4 (C:\WINDOWS\System32\KERNEL32.DLL+0x17bd4)
>> #&#8203;17 0x00007ff8c92ece51 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x6ce51)
>> system_libs:DEBUG: forcing stdlibs: {'libembind'}

**Comment by keith** [comment]
Going to close this since there doesn't seem to be enough info
