### ISSUE TITLE
Failure to optimize __builtin_add_overflow return value to constant when possible

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#45752]
|  |  |
| --- | --- |
| Bugzilla Link | [46407](https://llvm.org/bz46407) |
| Version | trunk |
| OS | Linux |
| CC | @LebedevRI,@RKSimon,@nikic,@rotateright |

## Extended Description 
```
int f(int a, int b)
{
    return __builtin_add_overflow(12312321321321l, a, &b);
}
```
This can be optimized to `return 1`. This transformation is done by GCC, but not by LLVM.

**Comment by GabrielRavier** [comment]
Looks like this is fixed on trunk.

**Comment by RKSimon** [comment]
Looks like this was fixed between 11.x and 12.x https://c.godbolt.org/z/MbTsGooch
