### ISSUE TITLE
clang-format produces non compilable code

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45755]
|  |  |
| --- | --- |
| Bugzilla Link | [46410](https://llvm.org/bz46410) |
| Version | 10.0 |
| OS | Linux |
| Attachments | [the file that has the problem](https://user-images.githubusercontent.com/60944935/143760886-74734e6d-229f-4a33-8634-33181eb07c04.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie,@mydeveloperday,@sam-mccall |

## Extended Description 

If you run clang format over the attached file it will make the code non compilable

Specially it transforms

for (unsigned int i = 0; i < (nRefSegs + 9) >> 3; ++i) {

into 

for (unsigned int i = 0; i<(nRefSegs + 9)> > 3; ++i) {

breaking the shift operator.

JBIG2Stream.cc:1283:50: error: expected primary-expression before ‘>’ token
 1283 |       for (unsigned int i = 0; i<(nRefSegs + 9)> > 3; ++i) {

**Comment by mydeveloperday** [comment]
This is the same as https://github.com/llvm/llvm-project/issues/46124 and is already fixed, closing this issue
