### ISSUE TITLE
Duplicated warning message in -Wcomma

### ISSUE THREAD

**Issue by haoxintu** [llvm/llvm-project#45783]
|  |  |
| --- | --- |
| Bugzilla Link | [46438](https://llvm.org/bz46438) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
This code, bug.cc, clang-9 to clang-trunk emit two duplicated warning message "warning: possible misuse of comma operator here [-Wcomma]", while clang-6 to clang-8 just give one warning message about this.

$cat bug.cc
const long var = 10;
static_assert (1 ? ( 0 , var ) : 0 , "" );

$clang++-trunk -Wcomma -c bug.cc 
bug.cc:2:24: warning: possible misuse of comma operator here [-Wcomma]
static_assert (1 ? ( 0 , var ) : 0 , "" );
                       ^
bug.cc:2:22: note: cast expression to void to silence warning
static_assert (1 ? ( 0 , var ) : 0 , "" );
                     ^
                     static_cast<void>( )
bug.cc:2:24: warning: possible misuse of comma operator here [-Wcomma]
static_assert (1 ? ( 0 , var ) : 0 , "" );
                       ^
bug.cc:2:22: note: cast expression to void to silence warning
static_assert (1 ? ( 0 , var ) : 0 , "" );
                     ^
                     static_cast<void>( )
2 warnings generated.

$clang++-8 -Wcomma -c bug.cc 
bug.cc:2:24: warning: possible misuse of comma operator here [-Wcomma]
static_assert (1 ? ( 0 , var ) : 0 , "" );
                       ^
bug.cc:2:22: note: cast expression to void to silence warning
static_assert (1 ? ( 0 , var ) : 0 , "" );
                     ^
                     static_cast<void>( )
1 warning generated.

**Comment by JOE1994** [comment]
Reproducible with `clang 18.1.0`:
* https://godbolt.org/z/GT4ebzvMr

**Comment by shafik** [comment]
Interesting if we just use a constant as opposed to `var` we don't double diagnose: https://godbolt.org/z/P76eYa88E
