### ISSUE TITLE
Clang 10.0 segfault with temporary as template parameter

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45780]
|  |  |
| --- | --- |
| Bugzilla Link | [46435](https://llvm.org/bz46435) |
| Version | 10.0 |
| OS | MacOS X |
| Attachments | [Crash dump](https://user-images.githubusercontent.com/60944935/143760890-9cc86c7a-8ecc-4a72-938f-d5dfc93322e4.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 

Clang 10.0 crashes with a segfault when compiling the code below. Crash dump attached.

Code to reproduce:

// clang++ -std=c++20 example.cpp -o example

#include <iostream>

template<size_t N>
struct const_literal {
  constexpr const_literal(const char (&v)[N]) {
    std::copy_n(v, N, value);
  }

  char value[N];
};

template<const auto& Name>
struct notation {
  template<typename OutputStream>
  static void print(OutputStream& output) {
    output << Name.value << "\n";
  }
};

using example = notation<const_literal("Example")>;

int main() {
  example::print(std::cout);

  return 0;
}

**Comment by xgupta** [comment]
It is not crashing anymore on latest trunk.
