### ISSUE TITLE
disable_coredump=1 does not disable coredump on systemd

### ISSUE THREAD

**Issue by ecatmur** [llvm/llvm-project#45797]
|  |  |
| --- | --- |
| Bugzilla Link | [46452](https://llvm.org/bz46452) |
| Version | 10.0 |
| OS | Linux |

## Extended Description 
(related: #&#8203;44214)

If /proc/sys/kernel/core_pattern is a pipe (e.g. '|/usr/bin/coredump <args...>') then setting RLIMIT_CORE to 0 does not actually disable coredumps; they are still generated and passed to the coredump helper, which will then send it to /dev/null (if written to respect RLIMIT_CORE).

Per https://github.com/systemd/systemd/issues/2643#issuecomment-234021824 the solution is to set RLIMIT_CORE=1 (!) which will fully disable core dumping (no core is generated, the coredump helper is not invoked, and si_code is CLD_KILLED not CLD_DUMPED).

**Comment by EugeneZelenko** [comment]
Not merged yet.
