### ISSUE TITLE
Optimize some bit magic into a faster pattern when nand is not available

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#45817]
|  |  |
| --- | --- |
| Bugzilla Link | [46472](https://llvm.org/bz46472) |
| Version | trunk |
| OS | Linux |
| CC | @topperc,@LebedevRI,@RKSimon,@rotateright |

## Extended Description 
```
int f(int a, int b, int c)
{
    return (a & ~c) | (b & c);
}
```
Unless the target architecture has a nand intruction available (such as x86 with BMI) this can be optimized to `return ((b ^ a) & c) ^ a;`. This transformation is done by GCC (though sadly it also does it when nand is available), but not by LLVM

**Comment by GabrielRavier** [comment]
Looks like the suggested optimization is implemented on trunk.

**Comment by RKSimon** [comment]
@GabrielRavier Do you know if we have test coverage for this?

**Comment by GabrielRavier** [comment]
Nope, no idea, I just randomly looked at this bug report 3 years after first making it and noticed the original testcase was fixed, I haven't looked further into LLVM source code to check if there's any specific test coverage.
