### ISSUE TITLE
All Qt apps are silently built inoperable when compiled with clang using LTO ("signal not found")

### ISSUE THREAD

**Issue by v-fox** [llvm/llvm-project#45814]
|  |  |
| --- | --- |
| Bugzilla Link | [46469](https://llvm.org/bz46469) |
| Version | 11.0 |
| OS | Linux |
| CC | @dwblaikie,@DougGregor,@dommldomml,@MaskRay,@LebedevRI,@zygoloid |

## Extended Description 
I've noticed that all packages that use Qt and that I tried to build with clang using LTO were unable to draw their GUI at all or got stuck after creating a window. Apparently, it's a known old… "feature" for which I failed to find a report here.

https://www.reddit.com/r/cpp_questions/comments/82jpz5/qt5_signal_broken_by_lto/
https://bugreports.qt.io/browse/QTBUG-43556
https://bugreports.qt.io/browse/QTBUG-61710
https://github.com/InBetweenNames/gentooLTO/issues/444

So, Qt guys refuse to change anything and say that their code is correct and allege that clang guys say the same. However, building broken binaries without erroring-out is definitively not OK. If Qt code is truly correct it would be nice for clang to avoid misoptimising it or, if clang code is correct, detect such usage and skip optimising it. Or, again, at least erroring-out. What if entire distribution would be built with clang with LTO by default ?

**Comment by inclyc** [comment]
Confirmed that this issue was fixed.
