### ISSUE TITLE
libcxx/src/CMakeLists.txt includes thread_win32.cpp regardless of LIBCXX_HAS_WIN32_THREAD_API

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45810]
|  |  |
| --- | --- |
| Bugzilla Link | [46465](https://llvm.org/bz46465) |
| Version | 10.0 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
libcxx/src/CMakeLists.txt has the following fragment:

if(WIN32)
  list(APPEND LIBCXX_SOURCES
    support/win32/locale_win32.cpp
    support/win32/support.cpp
    support/win32/thread_win32.cpp
    )

If LIBCXX_HAS_PTHREAD_API is ON and LIBCXX_HAS_WIN32_THREAD_API is OFF (MINGW), this causes linker errors.

It should be:

if(WIN32)
  list(APPEND LIBCXX_SOURCES
    support/win32/locale_win32.cpp
    support/win32/support.cpp
    )
  if (LIBCXX_HAS_WIN32_THREAD_API)
    list(APPEND LIBCXX_SOURCES
      support/win32/thread_win32.cpp
      )
  endif()

**Comment by waywardmonkeys** [comment]
This was fixed in 0f5020af7f347f029b5687f7a6d3b72174995d59 and can be closed.
