### ISSUE TITLE
Clang crash in build/tools/clang/include/clang/AST/TypeNodes.inc:58: clang::TypeInfo clang::ASTContext::getTypeInfoImpl(const clang::Type *) const: Assertion `!T->isDependentType() && "should not see dependent types here"' failed.

### ISSUE THREAD

**Issue by haoxintu** [llvm/llvm-project#45822]
|  |  |
| --- | --- |
| Bugzilla Link | [46477](https://llvm.org/bz46477) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
This code, bug.cc ,reduce by C-Reduce, makes clang-trunk crashed.

$cat bug.cc
long a enum : decltype(0 = a)::b {

$clang++ bug.cc
bug.cc:1:7: error: expected ';' after top level declarator
long a enum : decltype(0 = a)::b {
      ^
      ;
bug.cc:1:26: error: expression is not assignable
long a enum : decltype(0 = a)::b {
                       ~ ^
bug.cc:1:15: error: missing 'typename' prior to dependent type name 'decltype(<recovery-expr>(0, a))::b'
long a enum : decltype(0 = a)::b {
              ^~~~~~~~~~~~~~~~~~
              typename 
bug.cc:1:35: error: expected identifier
long a enum : decltype(0 = a)::b {
                                  ^
bug.cc:1:35: error: expected '}'
bug.cc:1:34: note: to match this '{'
long a enum : decltype(0 = a)::b {
                                 ^
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name bug.cc -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -dwarf-column-info -fno-split-dwarf-inlining -debugger-tuning=gdb -resource-dir /home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/lib/clang/11.0.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward -internal-isystem /usr/local/include -internal-isystem /home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/lib/clang/11.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/haoxin/compilers/new-scg/new-scg-build/map_test/clang-test/creduce -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -o /tmp/bug-2d86d7.o -x c++ bug.cc 
1.	<eof> parser at end of file
 #&#8203;0 0x000000000221f084 PrintStackTraceSignalHandler(void*) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x221f084)
 #&#8203;1 0x000000000221ce4e llvm::sys::RunSignalHandlers() (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x221ce4e)
 #&#8203;2 0x000000000221f385 SignalHandler(int) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x221f385)
 #&#8203;3 0x00007fc760741390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
 #&#8203;4 0x0000000003f3cea2 clang::ASTContext::getTypeInfoImpl(clang::Type const*) const (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x3f3cea2)
 #&#8203;5 0x0000000003f3e183 clang::ASTContext::getTypeInfo(clang::Type const*) const (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x3f3e183)
 #&#8203;6 0x0000000003f4f08d clang::ASTContext::getIntWidth(clang::QualType) const (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x3f4f08d)
 #&#8203;7 0x00000000038a61c6 clang::Sema::ActOnEnumBody(clang::SourceLocation, clang::SourceRange, clang::Decl*, llvm::ArrayRef<clang::Decl*>, clang::Scope*, clang::ParsedAttributesView const&) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x38a61c6)
 #&#8203;8 0x0000000003690c39 clang::Parser::ParseEnumBody(clang::SourceLocation, clang::Decl*) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x3690c39)
 #&#8203;9 0x000000000368d722 clang::Parser::ParseEnumSpecifier(clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x368d722)
#&#8203;10 0x00000000036849b0 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x36849b0)
#&#8203;11 0x000000000366ecfa clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x366ecfa)
#&#8203;12 0x000000000366eab5 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x366eab5)
#&#8203;13 0x000000000366daf6 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x366daf6)
#&#8203;14 0x000000000366bdff clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x366bdff)
#&#8203;15 0x0000000003667bfd clang::ParseAST(clang::Sema&, bool, bool) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x3667bfd)
#&#8203;16 0x0000000002931887 clang::FrontendAction::Execute() (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x2931887)
#&#8203;17 0x00000000028ca6b1 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x28ca6b1)
#&#8203;18 0x00000000029cab0c clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x29cab0c)
#&#8203;19 0x000000000093747b cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x93747b)
#&#8203;20 0x0000000000935c91 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x935c91)
#&#8203;21 0x0000000000935a49 main (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x935a49)
#&#8203;22 0x00007fc75f296830 __libc_start_main /build/glibc-LK5gWL/glibc-2.23/csu/../csu/libc-start.c:325:0
#&#8203;23 0x0000000000932c89 _start (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-11+0x932c89)
clang-11: error: unable to execute command: Segmentation fault (core dumped)
clang-11: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 11.0.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin
clang-11: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-11: note: diagnostic msg: /tmp/bug-2157c0.cpp
clang-11: note: diagnostic msg: /tmp/bug-2157c0.sh
clang-11: note: diagnostic msg: 

********************

$clang++ --version
clang version 11.0.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin

**Comment by Endilll** [comment]
Can't reproduce using Clang 10 and 11 with assertions enabled: https://godbolt.org/z/fjKz4ndaP
I also tried passing exact cc1 arguments locally.
