### ISSUE TITLE
Failure to optimize xor pattern to xor

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#45820]
|  |  |
| --- | --- |
| Bugzilla Link | [46475](https://llvm.org/bz46475) |
| Version | trunk |
| OS | Linux |
| CC | @LebedevRI,@RKSimon,@nikic,@rotateright |

## Extended Description
```c 
bool f(bool a, bool b)
{
    return ((a & b) ^ b) | ((a & b) ^ a);
}
```
This can be optimized to `return a ^ b;`. This transformation is done by GCC, but not by LLVM.

**Comment by marcauberer** [comment]
Alive2: https://alive2.llvm.org/ce/z/i44xmq
I'd like to work on this

**Comment by marcauberer** [comment]
Differential revision: https://reviews.llvm.org/D159380

**Comment by marcauberer** [comment]
The patch has landed, so I guess we can close this now.

**Comment by dc03** [comment]
> The patch has landed, so I guess we can close this now.

For future reference, you should put something like `Fixes https://github.com/llvm/llvm-project/issues/<issue num>` in your commit message so that github does this for you :slightly_smiling_face:
