### ISSUE TITLE
[LV] ASSERT: getTypeSizeInBits(SrcTy) <= getTypeSizeInBits(Ty) && "getNoopOrSignExtend cannot truncate!"

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#45849]
|  |  |
| --- | --- |
| Bugzilla Link | [46504](https://llvm.org/bz46504) |
| Version | trunk |
| OS | Windows NT |
| CC | @fhahn,@LebedevRI |

## Extended Description 
Reduced from https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21554

opt -loop-vectorize

Crash Type: ASSERT
Crash Address: 
Crash State:
  getTypeSizeInBits(SrcTy) <= getTypeSizeInBits(Ty) && "getNoopOrSignExtend cannot
  llvm::ScalarEvolution::getNoopOrSignExtend
  llvm::LoopAccessInfo::collectStridedAccess

define void @&#8203;ossfuzz21554() {
entry_block:
  br label %for_each_frames

for_each_frames:
  br label %for_each_channel

for_each_channel:
  %channelIndex = phi i32 [ 0, %for_each_frames ], [ %nextChannelIndex, %for_each_channel ]
  %nextChannelIndex = add nuw nsw i32 %channelIndex, 1
  %B6 = and i32 %nextChannelIndex, 2147483647
  %tmp6 = mul i32 undef, %nextChannelIndex
  %tmp7 = getelementptr float, float* undef, i32 %tmp6
  store float undef, float* %tmp7, align 4
  %B5 = add i32 %nextChannelIndex, %B6
  %tmp13 = icmp eq i32 %B5, %nextChannelIndex
  br i1 %tmp13, label %for_each_frames, label %for_each_channel
}

In LoopAccessInfo::collectStridedAccess we test for:

  uint64_t StrideTypeSize = DL.getTypeAllocSize(StrideExpr->getType());
  uint64_t BETypeSize = DL.getTypeAllocSize(BETakenCount->getType());
  if (BETypeSize >= StrideTypeSize)
    CastedStride = SE->getNoopOrSignExtend(StrideExpr, BETakenCount->getType());

but then in ScalarEvolution::getNoopOrSignExtend we fail here:

  assert(getTypeSizeInBits(SrcTy) <= getTypeSizeInBits(Ty) &&
         "getNoopOrSignExtend cannot truncate!");

so we can have cases where the legalized alloc sizes are the same but the original src type is larger than the dst type.

**Comment by artagnon** [comment]
Unable to reproduce on the latest `master`. I think the bug has been fixed. @RKSimon: please re-open if you can reproduce.
