### ISSUE TITLE
Segfault with performance-unnecessary-value-param check

### ISSUE THREAD

**Issue by varqox** [llvm/llvm-project#45855]
|  |  |
| --- | --- |
| Bugzilla Link | [46510](https://llvm.org/bz46510) |
| Version | unspecified |
| OS | Linux |
| CC | @EugeneZelenko,@fberger,@irishrover |

## Extended Description 
Running
  clang-tidy -checks='performance-unnecessary-value-param' bug.cc
on the following code results in a segfault:
==============================
struct Foo {
	Foo(const Foo&) {}
};

template <class T>
bool recur(unsigned x, T&& val) {
	if (x == 0) {
		return false;
	}
	return recur(x / 2, val);
}

void bar(Foo entry) {
	recur(0, entry);
}
==============================

Both clang 10.0.0 and current trunk (clang 11) segfault (see https://godbolt.org/z/gzVMqr).

**Comment by 5chmidti** [comment]
This no longer reproduces, and has probably been fixed by #87954, which is part of LLVM19
