### ISSUE TITLE
Failure to vectorize a std::find across a dereferencable array

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#45863]
|  |  |
| --- | --- |
| Bugzilla Link | [46518](https://llvm.org/bz46518) |
| Version | trunk |
| OS | Windows NT |
| CC | @davidbolvansky,@efriedma-quic,@fhahn,@LebedevRI,@rotateright |

## Extended Description 
```
#include <array>
#include <algorithm>
bool findme(const std::array<int, 8> &db, int key) {
    return std::find(db.begin(), db.end(), key) != db.end();
}
```
https://godbolt.org/z/rdWStD

We end up with a full cmp+branch tree when we could very efficiently use a vector comparison followed by an anyof reduction.

**Comment by alexey-bataev** [comment]
Looks like it is fixed:
define dso_local noundef zeroext i1 @findme(std::array<int, 8ul> const&, int)(ptr nocapture noundef nonnull readonly align 4 dereferenceable(32) %db, i32 noundef %key) local_unnamed_addr {
entry:
  %0 = load <8 x i32>, ptr %db, align 4
  %1 = insertelement <8 x i32> poison, i32 %key, i64 0
  %2 = shufflevector <8 x i32> %1, <8 x i32> poison, <8 x i32> zeroinitializer
  %3 = icmp eq <8 x i32> %0, %2
  %4 = freeze <8 x i1> %3
  %5 = bitcast <8 x i1> %4 to i8
  %6 = icmp ne i8 %5, 0
  ret i1 %6
}

**Comment by RKSimon** [comment]
Fixed between 14.x and 15.x : https://godbolt.org/z/4c51GMP8q
