### ISSUE TITLE
"const auto varName" rewritten to "const autovarName" within a braced-initialized lambda for AlignConsecutiveDeclarations and Cpp11BracedListStyle

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#45874]
|  |  |
| --- | --- |
| Bugzilla Link | [46529](https://llvm.org/bz46529) |
| Version | 10.0 |
| OS | Linux |
| Attachments | [cpp file and .clang-format style file which reproduce the bug](https://user-images.githubusercontent.com/60944935/143760917-de8b9dd2-9c91-4aa6-8b24-13d8dbcbcf2b.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mkurdej |

## Extended Description 

Try to format the attached bug.cpp with the attached .clang-format style file:

clang-format -style=file bug.cpp

The tokens "auto" and "something" become erroneously contracted in the result (tried with clang version 8 and 10).

**Comment by mydeveloperday** [comment]
This issue is still present in clang-format v13

**Comment by mydeveloperday** [comment]
I went back and checked and this seems to be broke in v12, so I changed my mind that this isn't a regression, (and I feel the title of #53409 is a little miss leading.

**Comment by mkurdej** [comment]
It seems to be broken between v4 and v5:
```
"d:\Program Files\LLVM-5.0.2\bin\clang-format.exe" -style=file test.cpp
const auto result{ []() {
  const autosomething = 1;
  return 2;
} };

"d:\Program Files\LLVM-4.0.1\bin\clang-format.exe" -style=file test.cpp
const auto result{ []() {
  const auto something = 1;
  return 2;
} };
```

**Comment by mkurdej** [comment]
Duplicate of #44292.
