### ISSUE TITLE
clang-format: Add option to enforce separation line between method definitions

### ISSUE THREAD

**Issue by akien-mga** [llvm/llvm-project#45895]
|  |  |
| --- | --- |
| Bugzilla Link | [46550](https://llvm.org/bz46550) |
| Version | trunk |
| OS | Linux |

## Extended Description 
This is a feature request for clang-format.

In C/C++ codebases, some developers (possible some IDEs?) tend to group the definition of setters and getters together, without having an empty line separating each definition, e.g.:

```
void some_method() {
    // some code
}

void set_some_property(int p_value) {
    some_property = p_value;
    // do setter stuff
}
int get_some_property() {
    return some_property;
}

void some_other_method() {
     // some code
}
```

Since this "style" is down to personal preference, it tends not to be upheld consistently in big codebases, so in my project (https://github.com/godotengine/godot) we want to enforce having a separation line between *all* method definitions, whether or not they might be semantically related, i.e.:

```
void some_method() {
    // some code
}

void set_some_property(int p_value) {
    some_property = p_value;
    // do setter stuff
}

int get_some_property() {
    return some_property;
}

void some_other_method() {
     // some code
}
```

I would appreciate having a way to enforce this via clang-format instead of manual review.

I'm not sure what the best name would be for the option, maybe EnforceSeparationLineBetweenMethodDefinitions?

I don't know if there would be a use case for a flag that would enforce *not* having a separation line between all method definitions (I don't have any myself), but if so it could be SeparationLineBetweenMethodDefinitions: [Always, Never, LeaveAsIs].

**Comment by CoelacanthusHex** [comment]
I think this feature is useful, there are many newbies in the world, they often forget to add empty line between function definitions unlike skilled programmer always do. For example, in our project [OI-wiki](https://github.com/OI-wiki/OI-wiki), many contributors are beginner, we need this feature to format their code to fit our style.
BTW, other code formatter has added this feature, such as AStyle, but clang-format does better jobs in other aspects,
so we hope clang-format can add this feature and became better!

Thank you!

**Comment by ksyx** [comment]
I have suggested an implementation in <https://reviews.llvm.org/D116314>, and please see if there is anything that could be improved. Thanks

**Comment by ksyx** [comment]
The commit implementing this has just been merged. Please check if it meets your need. Thanks.

**Comment by akien-mga** [comment]
Thanks a lot! It looks great.

I tested the current implementation using the `clang-format-14_14~++20220104111248+cb9ccd38c55f-1~exp1~20220104111347.223_amd64` Debian snapshot (extracted on a non Debian-based distro but with a extra dependencies and some `LD_LIBRARY_PATH` magic it seems to work fine).

Here's the output of the new option on the current https://github.com/godotengine/godot codebase (which is otherwise up-to-date with clang-format 13.0.0 and the snapshot's output without the new `SeparateDefinitionBlocks` option):

https://github.com/akien-mga/godot/commit/241a18e896fb7823b28f20af8c62a0645c383116

Overall it seems pretty satisfactory. There are a few changes which might not 100% match our de facto style, but I'm not sure that they can be catered to without going too deep the rabbit hole - unless other projects also have similar nitpicks. There are also a couple of bugs which break compilation on big preprocessor macros.

Here's what I spotted:

![image](https://user-images.githubusercontent.com/4701338/148123110-6c6d35e8-604f-4b63-85e0-e449dcc96870.png)
This creates a bug. It also affects only two macros out of 51 which use this pattern in https://github.com/godotengine/godot/blob/master/core/error/error_macros.h
(This weird code is a hack to force the requirement to use a semicolon when calling the macro, as if it was a function, e.g. `ERR_PRINT("Fail");`.)

![image](https://user-images.githubusercontent.com/4701338/148123599-72cf6a10-6a1a-4640-83b8-5ca59b3b8a51.png)
In this file this also creates a bug, the macro definition is cut in the middle.
There's a few other occurrences of big macros being broken like this, which breaks compilation.

I can open a separate bug report for the above issue and try to create a minimum reproducer tomorrow.

![image](https://user-images.githubusercontent.com/4701338/148121719-3230e422-e3b1-451d-bb8c-f651f10c03ba.png)
With `AllowShortFunctionsOnASingleLine: Inline`, we sometimes group such inline functions in class definitions together when they are semantically related. Now they get separated by the new option, which makes sense, but in this niche case it's maybe not what we'd prefer (but we can live with it). If other projects have similar style needs, there could be an option like `SeparateDefinitionBlocks: AlwaysButSingleLineDefinitions` but that might be a bit niche.

![image](https://user-images.githubusercontent.com/4701338/148122526-ceadceb8-502a-4425-8eb8-b1141234a6ca.png)
Preprocessor directives are not handled specially, so definition blocks also get separated from them. There again it might be a matter of taste and difficult to please everyone.
This can makes things a bit weird when doing stuff like this:
![image](https://user-images.githubusercontent.com/4701338/148123811-3e2505c0-ad7c-4b15-8b80-29708d582f33.png)

![image](https://user-images.githubusercontent.com/4701338/148122670-cf53a736-b487-48e6-a349-a2f61eeac48d.png)
Similarly, comments before method definitions also get separated from the method they describe. That's likely good and wanted for some styles, while others might want to keep the comment directly touching the method it qualifies (for example to distinguish a comment that describes a whole code section from a comment that describes the immediate function that follows).

![image](https://user-images.githubusercontent.com/4701338/148122830-2dbc8831-0105-4a34-8148-89fa74555906.png)
![image](https://user-images.githubusercontent.com/4701338/148122875-7b515c43-5dad-40a5-a87e-148b3c62c496.png)
Namespace separation line actually gets removed with `SeparateDefinitionBlocks: Always`. That seems unexpected.

**Comment by ksyx** [comment]
@akien-mga 
Thanks for the detailed feedback! I have made changes to fix problems breaking build in <https://reviews.llvm.org/D116663> and may continue optimizing behaviours like namespace empty lines and grouping one-liner functions together in future patches as I had not come out with a nice implementation yet.

**Comment by mkurdej** [comment]
Closing this issue as the new option is already merged.
Please add new comments in https://github.com/llvm/llvm-project/issues/52976 or create new issue(s) so that the tracking the problems is easier.
Anyway, thanks for reporting!

**Comment by ksyx** [comment]
@akien-mga The commit https://github.com/llvm/llvm-project/commit/ee25a327aac0eeae28f468a741b58ec7689de5f2 resolving your feedback has been merged into mainstream and please check if there are any further problems. The `inline` style seems nice to have for me but I have limited time recently, but thanks for all your valuable feedbacks again.

**Comment by mkurdej** [comment]
@akien-mga, also, please create new tickets for any new issues instead of putting comments here (but you can always reference this issue if needed). Are all your issues fixed? How about this strange `else ((void)0)` formatting?

**Comment by akien-mga** [comment]
Thanks! I'll test tomorrow when the latest fix makes it way to the nightly builds, and open new tickets if there are any remaining bugs or suggestions.

**Comment by akien-mga** [comment]
Tested and the bugs I described above have indeed been fixed: https://github.com/akien-mga/godot/commit/c814da35e9eec8b8cb017b4b85fcb3ce318c0172

I'll open new issues for some remaining quirks.
