### ISSUE TITLE
Clang-format does not de-duplicate indented #includes

### ISSUE THREAD

**Issue by elvenfighter** [llvm/llvm-project#45900]
|  |  |
| --- | --- |
| Bugzilla Link | [46555](https://llvm.org/bz46555) |
| Version | trunk |
| OS | Windows NT |
| CC | @mkurdej,@mydeveloperday,@BigBigos |

## Extended Description 
Usually, clang-format will de-duplicate #include directives.

However, on special inputs, it will not. This behavior is inconsistent.

STEPS TO REPRODUCE

1. Create a source:
```
cat >main.cpp <<__EOF__
#include <vector>
  #include <vector>
```

2. Run clang-format:
clang-format main.cpp

EXPECTED RESULTS

$ clang-format main.cpp
`#include <vector>`

ACTUAL RESULTS

$ clang-format main.cpp
```
#include <vector>
#include <vector>
```

ADDITIONAL INFORMATION

I am expecting headers to be de-duplicated, because the second pass actutally eliminates duplicated includes:

$ clang-format main.cpp | clang-format --
`#include <vector>`

**Comment by mydeveloperday** [comment]
This issue is resolved in clang-format v12 by commit fe21c86ee75f93bb0372660c004ac2325ac12cdc

I'm closing this please feel free to reopen if you have further issues
