### ISSUE TITLE
Backend -ftime-trace entries should be demangled

### ISSUE THREAD

**Issue by Trass3r** [llvm/llvm-project#45901]
|  |  |
| --- | --- |
| Bugzilla Link | [46556](https://llvm.org/bz46556) |
| Version | trunk |
| OS | All |

## Extended Description 
While Frontend entries are properly demangled the Backend entries are not:

"name":"OptFunction","args":{"detail":"_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2EPKcRKS3_"}

**Comment by Trass3r** [comment]
Which was because of this
https://github.com/llvm/llvm-project/blob/961439cd7e1f1e6bfbe3733ede0443d0e02c5c72/llvm/lib/IR/LegacyPassManager.cpp#L1411
not using something like this
https://github.com/llvm/llvm-project/blob/781b491bba9d798e53f7784dced3c2be77c81dd4/clang/lib/CodeGen/CodeGenModule.cpp#L3570-L3576

Can't find anything equivalent in the new pass manager:
https://github.com/llvm/llvm-project/blob/961439cd7e1f1e6bfbe3733ede0443d0e02c5c72/llvm/lib/IR/PassManager.cpp#L124

**Comment by alecazam** [comment]
Could this get fixed?  The change is above.   I'm trying to do reports based on -ftime-trace, and the OptModule symbols are the only ones not demangled.  Seems like a very few line change above.

**Comment by Trass3r** [comment]
Well you can thank one particular person for that who rejected my PR cause it affected "dead" code. Of course this "dead" code is (predictably) still in place today.
https://reviews.llvm.org/D135658#3966930

**Comment by alecazam** [comment]
Looks like I'm going to have to disable using the macOS demangle on Windows clang-cli files.  For some reason, the demangle call is crashing in my Swift code.  I'll track it down when I get a chance, but this should all just work without much human/dev intervention.

I would prefer that each platform demangle it's own names with it's own unique demangle that may be specific to C++14/17/20, or the version of clang.  So this really needs to be done before writing these out, so that tools don't have to "fix up" the names from "OptFunction"

**Comment by Trass3r** [comment]
Finally landed in #87626.

**Comment by alecazam** [comment]
Ugh.  Reverted?  Okay, now it's up to every caller to demangle and match to whatever their platform is.  Have an old trace file?   Well you better have the matching demangler from that ancient clang.   Most of the keywords are already demangled in the timings.  It was just a few of the remaining strings that Trass3r's change fixed.  Add a flag, but please don't revert the change.  Or revert the revert.  If I already have timings turned on, then I want the human readable names in the json timings that are written out.

**Comment by Trass3r** [comment]
No need for yet another flag. When passing `-ftime-trace` you already accept the overhead of tracing. You want a usable trace and not fast iterative compile times. Maybe you run it a few times manually to optimize, or you run it in a nightly job to track compile times over time.
The right thing to do would be to optimize the tracing so there's less duplication in the output.
But yeah no point in commenting here, you should target the other issue that led to the revert or the PR.
