### ISSUE TITLE
Option to ignore/disable format for specific styles

### ISSUE THREAD

**Issue by 6e4195b6-1b98-400b-b3ef-354fcfba4b21** [llvm/llvm-project#45912]
|  |  |
| --- | --- |
| Bugzilla Link | [46567](https://llvm.org/bz46567) |
| Version | 10.0 |
| OS | Windows NT |
| CC | @dwblaikie |

## Extended Description 
Hi.

Thank you for clang-format.

I'm trying to introduce .clang-format in an existing repository, but I can't tell clang-format to not change the current style of specific things.

For example, "AlignConsecutiveDeclarations" can only be set to "true" and "false", or not set at all, but in all cases, clang-format will change the alignment of existing code if its not styled as expected.

I would like the ability to set "AlignConsecutiveDeclarations: disable", for example, to disable formatting for just that one setting.

The code clang-format is run against doesn't conform to any guidelines, so I wanted to introduce clang-format a few rules at a time, instead of having to "litter" the code with "clang-format off".

Thank you.

**Comment by mydeveloperday** [comment]
I think we should reject this issue, its not going to happen, my advice is to jump in and start working out your current style, it only takes about 20 minutes of use to get the number of differences down to a minimum.

What is being suggested here is technically extremely complex, I highly advise against it.
