### ISSUE TITLE
load-store-vectorizer cannot assume that an offset calculated from add nuw is fine in general

### ISSUE THREAD

**Issue by aqjune** [llvm/llvm-project#45936]
|  |  |
| --- | --- |
| Bugzilla Link | [46591](https://llvm.org/bz46591) |
| Version | trunk |
| OS | All |
| Attachments | [Input & output](https://user-images.githubusercontent.com/6484889/143760930-38cbe879-a99e-4979-9b41-d362220e9fea.gz) |
| CC | @efriedma-quic,@fhahn,@arsenm,@nunoplopes |

## Extended Description 

test/Transforms/LoadStoreVectorizer/X86/vectorize-i8-nested-add.ll 's ld_v4i8_add_nuw vectorizes a sequence of loads, which is illegal.

https://godbolt.org/z/NzK5oY
(the attached file contains this input/output)

Counter example: if v0 and v1 is 0, nuw is never triggered, but the offsets aren't still consecutive.
https://alive2.llvm.org/ce/z/4nZKBs

This can happen when a program has an allocation larger than 4G.

**Comment by nunoplopes** [comment]
I think this is fixed (by https://github.com/llvm/llvm-project/commit/2be0abb7fe72ed4537b3eabcd3102d48ea845717)
The transformation is no longer performed.

cc @jlebar
