### ISSUE TITLE
Clang assertion failure when using weakref with exclude_from_explicit_instantiation symbols: Assertion `InnerHandle.pointsToAliveValue() && "TrackingVH must be non-null and valid on dereference!"' failed.

### ISSUE THREAD

**Issue by 9d44dc21-33e7-4c02-a68c-e735484060d3** [llvm/llvm-project#45947]
|  |  |
| --- | --- |
| Bugzilla Link | [46602](https://llvm.org/bz46602) |
| Version | unspecified |
| OS | Linux |
| Attachments | [crash backtrace, preprocessed source, and associated run script](https://user-images.githubusercontent.com/93435858/143760939-38e8f0a5-9548-41a3-80d5-415b9a42e1f3.gz) |
| CC | @zygoloid |

## Extended Description 

Please see attachments.

I reduced the reproduction steps as much as I could.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 15: https://godbolt.org/z/7jz3Gn56Y
