### ISSUE TITLE
Store per-thread copy of the global locale

### ISSUE THREAD

**Issue by nickitat** [llvm/llvm-project#45945]
|  |  |
| --- | --- |
| Bugzilla Link | [46600](https://llvm.org/bz46600) |
| Version | unspecified |
| OS | Linux |
| CC | @mclow,@nickitat |

## Extended Description 
That's not news that users of std::stringstream may suffer from the atomic add_shared, release_shared (within ctor and dtor of std::locale) accompanying each stringstream creation and deletion.

Though it is expected to be noticeable only on very heavy multicore servers I personally saw an impact on performance of our service running on a machine with 2 x INTEL Xeon E5-2660 v4.

So, this idea was discussed e.g here: https://groups.google.com/a/isocpp.org/g/std-discussion/c/uLTjDh41sNM/m/QF-yWrB0BgAJ .
And as far as I understood the only con is it will bring additional complexity to the implementation.

So, may we get back to discussion of this enhancement?

**Comment by mordante** [comment]
We recently https://github.com/llvm/llvm-project/pull/73533 made optimizations in this area. Instead of copying the global locale that locale is no longer reference counted and shared. Could you test whether that has solved your issue?

**Comment by ldionne** [comment]
Tentatively closing, please reopen if https://github.com/llvm/llvm-project/pull/73533 wasn't enough -- but I suspect this shouldn't be a problem anymore.
