### ISSUE TITLE
Clang assertion failure: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.

### ISSUE THREAD

**Issue by 9d44dc21-33e7-4c02-a68c-e735484060d3** [llvm/llvm-project#45941]
|  |  |
| --- | --- |
| Bugzilla Link | [46596](https://llvm.org/bz46596) |
| Version | unspecified |
| OS | Linux |
| Attachments | [crash backtrace, preprocessed source, and associated run script](https://user-images.githubusercontent.com/93435858/143760936-f238c20e-778b-4570-bca6-747bcd2aecf9.gz) |
| CC | @zygoloid |

## Extended Description 

Please see attachments.

I hit this bug while trying to compile TBB's test_blocked_rangeNd.cpp

I reduced the reproduction steps as much as I could.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 12: https://godbolt.org/z/xPdxWMe6e
