### ISSUE TITLE
Missing -Wshadow warning in a try-catch block

### ISSUE THREAD

**Issue by haoxintu** [llvm/llvm-project#45951]
|  |  |
| --- | --- |
| Bugzilla Link | [46606](https://llvm.org/bz46606) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie,@zygoloid |

## Extended Description 
Hi, all.

This code, test.cc, Clang might miss the -Wshadow warning message.

$cat test.cc
```cpp
int var = 10;
int main(){
  try  { } catch ( int var )  { }
}
```

$clang++ -Wshadow test.cc
//emits nothing

$clang++ -v
clang version 11.0.0 (https://github.com/llvm/llvm-project b9306fd042ce1c11d84f05d2124dfdc65b8331fe)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/haoxin/compilers/llvm-project/build/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Selected multilib: .;@m64

While in gcc
$g++ -Wshadow test.cc
test.cc: In function ‘int main()’:
test.cc:3:24: warning: declaration of ‘var’ shadows a global declaration [-Wshadow]
    3 |   try  { } catch ( int var )  { }
      |                        ^~~
test.cc:1:5: note: shadowed declaration is here
    1 | int var = 10;
      |     ^~~

Every version from clang 3.0 onwards behaves the same.

Thanks,
Haoxin

**Comment by shafik** [comment]
Confirmed: https://godbolt.org/z/1hscMn49f

**Comment by shafik** [comment]
duplicate: https://github.com/llvm/llvm-project/issues/15807
