### ISSUE TITLE
llvm IR documentation doesn't describe string constants

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#4596]
|  |  |
| --- | --- |
| Bugzilla Link | [4224](https://llvm.org/bz4224) |
| Version | trunk |
| OS | Windows XP |
| Blocks | llvm/llvm-bugzilla-archive#10637  |
| Reporter | LLVM Bugzilla Contributor |
| CC | @jryans,@nlewycky |
| Fixed by commit(s) | 217583 |

## Extended Description 
(Pointed out on IRC). The LLVM IR docs don't ever describe the c"..." syntax.

**Comment by JOE1994** [comment]
The `Array constants` section of the [Complex Constants](https://llvm.org/docs/LangRef.html#complex-constants) section of langref describes the `c"..."` syntax as follows:

> As a special case, character array constants may also be represented as a double-quoted string using the c prefix. For example: “c"Hello World\0A\00"”.

The [String Constants](https://llvm.org/docs/LangRef.html#string-constants) section of langref has a comment on how the bytes are interpreted:

> The interpretation of string constants (e.g. their character encoding) depends on context.

No further action needed to address this ticket.
