### ISSUE TITLE
Format options for attributes, ability to specify custom attributes.

### ISSUE THREAD

**Issue by b9b83f7b-7201-4b2e-b5a4-684938848f82** [llvm/llvm-project#45968]
|  |  |
| --- | --- |
| Bugzilla Link | [46623](https://llvm.org/bz46623) |
| Version | unspecified |
| OS | All |
| CC | @JonasGilg,@mydeveloperday |

## Extended Description 
Clang-format currently does not have options to control attribute formatting.

Some projects prefer to put prefix attributes on a separate line, eg:
```

[[nodiscard]]
int foo();
```

instead of:

`[[nodiscard]] int foo();`

Additionally, it would be useful to be able to provide a list of regexes that identify custom attributes. Maintaining an exhaustive list of attributes in clang-format proper would be daunting, as many projects hide them behind macros for backward compatibility, or rely on platform-specific attributes. Allowing projects to extend the list of recognized attributes would be quite useful.

My personal interest in this stems from using clang-format on CUDA projects, where `__host__ __device__` annotations are frequently used and commonly placed on the line above a function definition. Being able to achieve this common formatting style would ease adoption of clang-format by CUDA projects.

**Comment by owenca** [comment]
https://reviews.llvm.org/D140956
