### ISSUE TITLE
segv in string move-constructor with _LIBCPP_DEBUG=1

### ISSUE THREAD

**Issue by a7313266-558a-4216-9eb3-a25e217f5be6** [llvm/llvm-project#45970]
|  |  |
| --- | --- |
| Bugzilla Link | [46625](https://llvm.org/bz46625) |
| Version | 9.0 |
| OS | Linux |
| CC | @mclow |

## Extended Description 
I believe this program winds up move-constructing over a non-small string in LHS
of the + operator and something about this disagrees with the strings (or more
specifically the iterator-debugging machinery within the strings) produced by
std::to_string. I haven't been able to narrow it down further or determine cause:

Example program:

#include <string>

void use(std::string const& out) {}

int main() {
    use("0123456789012345678901" + std::to_string(1));
}

Example compile command:

$ clang++-9 -stdlib=libc++ -D_LIBCPP_DEBUG=1 t.cpp

Example run:

$ ./a.out 
Segmentation fault (core dumped)

With sanitizer:

$ clang++-9 -stdlib=libc++ -D_LIBCPP_DEBUG=1 -fsanitize=address t.cpp
$ ./a.out

AddressSanitizer:DEADLYSIGNAL
=================================================================
==42275==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x7f2c525e7647 bp 0x7fff815df6f0 sp 0x7fff815df680 T0)
==42275==The signal is caused by a READ memory access.
==42275==Hint: address points to the zero page.
    #&#8203;0 0x7f2c525e7646 in std::__1::__libcpp_db::swap(void*, void*) libcxx/build/src/./libcxx/src/debug.cpp:463:18
    #&#8203;1 0x4c6603 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) (/home/src/stellar-core/a.out+0x4c6603)
    #&#8203;2 0x4c5f55 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) (/home/src/stellar-core/a.out+0x4c5f55)
    #&#8203;3 0x4c5d50 in main (/home/src/stellar-core/a.out+0x4c5d50)
    #&#8203;4 0x7f2c513c0b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #&#8203;5 0x41bcf9 in _start (/home/src/stellar-core/a.out+0x41bcf9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV libcxx/build/src/./libcxx/src/debug.cpp:463:18 in std::__1::__libcpp_db::swap(void*, void*)
==42275==ABORTING

**Comment by philnik777** [comment]
We now require the library to be built with the debug-mode enabled to use it.
