### ISSUE TITLE
Support "filesystem" on Windows

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46004]
|  |  |
| --- | --- |
| Bugzilla Link | [46659](https://llvm.org/bz46659) |
| Version | 10.0 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
Using this file:

    #include <filesystem>
    #include <iostream>
    namespace fs = std::filesystem;
    int main() {
       std::cout << fs::current_path() << std::endl;
    }

and this compiler:

https://packages.msys2.org/package/mingw-w64-x86_64-gcc

and this command:

    g++.exe -std=c++17 -static a.cpp

everything works as expected. However if I use this compiler:

https://github.com/mstorsjo/llvm-mingw

then I get this result:

    lld-link: error: undefined symbol:
       std::__1::__fs::filesystem::__current_path(std::__1::error_code*)
    >>> referenced by
       C:\Windows\TEMP\a-27a261.o:(std::__1::__fs::filesystem::current_path())
    clang-10: error: linker command failed with exit code 1 (use -v to see
       invocation)

its mentioned here, that the reason is because LibCxx doesnt currently support
"filesystem" on Windows:

https://github.com/mstorsjo/llvm-mingw/issues/62#issuecomment-554718348

I think if GCC support "filesystem", then LLVM should too.

**Comment by ldionne** [comment]
This should work now thanks to the work of various people, notably @mstorsjo.

Closing, please reopen if you see issues with this. @89z (sorry if this is the wrong `@`, I tried correlating names with Google).

**Comment by 89z** [comment]
@ldionne please dont do "internet sleuthing" or whatever you did to link the two accounts. If you notice carefully, I have removed the name from my GitHub account. I did that for a reason. Please respect my privacy.

**Comment by ldionne** [comment]
Geez, sorry, there was absolutely no ill-intent -- I know the Bugzilla transition dropped a lot of information on the floor so I thought this was going to be appreciated.

I'll edit my comment above and you can remove yours.

**Comment by 89z** [comment]
I dont mean to be rude, but certain malicious people have been tracking me online, so my privacy is important. Thank you for respecting that.

**Comment by ldionne** [comment]
I do respect that. Like I said, there was no ill intent. We've been going through a migration from Bugzilla and a large number of bugs are now missing information or their reporters aren't aware of the new location of the bug. I thought it would be rude to close without the reporter being aware.
