### ISSUE TITLE
Clang and GCC disagree on the definition of "POD for the purpose of layout" for classes with a defaulted/deleted constructor/destructor/copy or move assignment operator

### ISSUE THREAD

**Issue by riccibruno** [llvm/llvm-project#46056]
|  |  |
| --- | --- |
| Bugzilla Link | [46711](https://llvm.org/bz46711) |
| Version | unspecified |
| OS | Linux |
| CC | @dwblaikie,@DougGregor,@zygoloid |

## Extended Description 
For targets using the C++03 definition of POD for ABI purposes, GCC allows a class type to be "POD for the purpose of layout" if the class has a defaulted or deleted constructor/destructor/copy or move assignment operator. Clang does not. Example:

struct S {
    int i;
    char b;
    ~S() = default;
};

struct T : S {
    char c;
};

int i = sizeof(T); // 12 with GCC, 8 with Clang (on x86-64)

(https://godbolt.org/z/sbsM54)

This is not a new issue; GCC has this behaviour since at least GCC 4.5.3, and clang has this behaviour since at least clang 3.0.

**Comment by hubert-reinterpretcast** [comment]
Addressed by https://reviews.llvm.org/D119051
