### ISSUE TITLE
Multi thread allocation performance issues

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46084]
|  |  |
| --- | --- |
| Bugzilla Link | [46739](https://llvm.org/bz46739) |
| Version | 11.0 |
| OS | other |
| Reporter | LLVM Bugzilla Contributor |
| CC | @cryptoad |

## Extended Description 
We try to apply scudo to android R os on Galaxy S20.
But scudo has allocation performance issue when we test Geekbench 5.1.1 multi-core cases.
Some cases got lower point than Jemalloc that we used previous android version.
```
                Scudo     Jemalloc
HTML5            1450       2886
Face Detection   3274       3749
```
(Higher is better)

These tests seems allocate a lot of large size of memory with 8 threads.
There are lock contention happened between threads when threads try to allocate on secondary cache.

`lockSlow`, especially, is bottle-neck on these cases.
If we change `HybridMutex::lock` to use only "yield and trylock" as below, HTML5 score improve to 2161.
```cpp
class HybridMutex {
public:
.............
  NOINLINE void lock() {
    if (LIKELY(tryLock()))
      return;
#ifdef __clang__
#pragma nounroll
#endif
    while (true) {
      yieldProcessor(NumberOfYields);
      if (tryLock())
        return;
    }
  }
```

We consider test result show `lockSlow` wake threads up is too slow.
This is not whole reason of multi-core test result, `HybridMutex::lock` has performance problem to using android R os.

Could you invest these multi-thread allocation performance issue?

Thank you.

**Comment by cferris1000** [comment]
There have been a lot of fixes for multi-threaded workloads in Scudo that should have fixed a lot of this.

Also, Geekbench has moved on to 6.2.2 which is what we are focused on testing against. If you could rerun and still have problems, please let us know.

**Comment by cferris1000** [comment]
This is really old and the code is very different now. I'm going to just close this.
