### ISSUE TITLE
flang changes on LLVM Phabricator that should cause build failures not flagged as such

### ISSUE THREAD

**Issue by jurahul** [llvm/llvm-project#46096]
|  |  |
| --- | --- |
| Bugzilla Link | [46751](https://llvm.org/bz46751) |
| Version | unspecified |
| OS | All |

## Extended Description 
A change that I had posted for review (https://reviews.llvm.org/D83522) had a compile error, but LLVM's Phabricator build declared that build passed. Flang seems to be building in the builds, but the build was never flagged as failing.

**Comment by arsenm** [comment]
Phabricator has a limited amount of time left
