### ISSUE TITLE
Clang can't compile libstdc++ ranges

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46091]
|  |  |
| --- | --- |
| Bugzilla Link | [46746](https://llvm.org/bz46746) |
| Version | trunk |
| OS | Linux |
| Attachments | [Preprocessed example that reproduces the error.](https://user-images.githubusercontent.com/60944935/143760982-39479df3-d271-42b0-a020-b93fa8c2980c.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @avikivity,@JohelEGP,@mmatrosov,@zygoloid,@HighCommander4 |

## Extended Description 

GCC 10.1.0 came with libstdc++ that has `<ranges>` implemented. Also clang 10 supports concepts. I wanted to use clang to compile a simple snippet that relies on ranges, but clang encountered some errors that just don't happen with gcc.

```
#include <ranges>

int main(void)
{
 char c[3] = {'a', 'b', 'v'};
 std::ranges::subrange sub(c);
}
```

The preprocessed file can be found here: https://godbolt.org/z/7hfbq5
I've also made an attachment with the same preprocessed file compressed.

**Comment by royjacobson** [comment]
Confirmed to work after https://reviews.llvm.org/D126907, so this was also a duplicate of #44178. Closing.
