### ISSUE TITLE
bogus -Wmissing-braces for CTAD deduced aggregate with inherited base

### ISSUE THREAD

**Issue by 4837c776-317b-4adc-a8ef-e2a26bbb71ff** [llvm/llvm-project#46120]
|  |  |
| --- | --- |
| Bugzilla Link | [46776](https://llvm.org/bz46776) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
Combination of aggregate CTAD and inheritance makes -Wmissing-braces wrong.

For example, take a tuple class with the usual CTAD:
https://wandbox.org/permlink/USZGcupYvTtP8D6D

  template <typename...> struct tuple;
  template <typename... T> tuple(T...) -> tuple<T...>;

Implement it as an aggregate, by explicit specializations:

  template <> struct tuple<> {};
  template <typename A> struct tuple<A> {A a;};
  template <typename A, typename B> struct tuple<A,B> {A a; B b;};
  ... & etc.

Now, 'tie' is usually implemented as a helper 'make' function tie(...) 
Instead, implement tie as a class inheriting from tuple, with CTAD

  template <typename... T> struct tie : tuple<T...> {};
  template <typename... T> tie(T&...) -> tie<T&...>;

along with an extra tuple CTAD converting from tie to tuple

  template <typename... T> tuple(tie<T...>) -> tuple<T...>;

Now, usage of tie looks like this:

  bool up = true;
  tuple t = tie{up};

warning: suggest braces around initialization of subobject [-Wmissing-braces]
tuple t = tie{up};
              ^~
              { }
1 warning generated.

However, this warning is incorrect here -
adding the suggested braces breaks the CTAD deduction.

**Comment by cor3ntin** [comment]
Fixed in 13.0 https://godbolt.org/z/9qersvbME
