### ISSUE TITLE
clang-format C/C++ adds space between two greater than characters of binary shift operator

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46124]
|  |  |
| --- | --- |
| Bugzilla Link | [46780](https://llvm.org/bz46780) |
| Version | unspecified |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mydeveloperday |

## Extended Description 
Clang-format adds a space between shift operator see before and after. Also attached .clang_format using command,
clang-format -style=file  problem_before.cpp > problem_after.cpp

problem_before.cpp 

```
#include <stdlib.h>
int main() {
    unsigned with = 0xfff;
    for (int32_t i = 0; i<(width + 7)>> 3; i++) {
        printf("%d\n", i);
    }
    return 0;
}
```

problem_after.cpp

```
#include <stdlib.h>
int main() {
    unsigned with = 0xfff;
    for (int32_t i = 0; i<(width + 7)> > 3; i++) {
        printf("%d\n", i);
    }
    return 0;
}
```

**Comment by mydeveloperday** [comment]
As of clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 7890afddec
ff01119f4d5e8825b43dd2c8361648)
This issue is fixed so I'm closing this issue, but feel free to reopen if you still have issues
