### ISSUE TITLE
Merge 66aff3239849507861d050c013cbe17c4a5781a7 into the 11.0 branch

### ISSUE THREAD

**Issue by erichkeane** [llvm/llvm-project#46122]
|  |  |
| --- | --- |
| Bugzilla Link | [46778](https://llvm.org/bz46778) |
| Version | trunk |
| OS | Windows NT |
| CC | @DougGregor,@zygoloid |

## Extended Description 
This fixes an crash/assertion on invalid code, see the bug report here: llvm/llvm-project#46118 

In the event that this is encountered without assertions, there is a seg-fault.  This patch is very narrowly focused, in that it emits an error ONLY in cases that would have been an assert/seg fault before, so I believe it is very low risk.

**Comment by Endilll** [comment]
Looks like that patch didn't make it into 11 branch, but it's too old by this point.
