### ISSUE TITLE
[git-clang-format] Add diffstat parameter

### ISSUE THREAD

**Issue by roligugus** [llvm/llvm-project#46159]
|  |  |
| --- | --- |
| Bugzilla Link | [46815](https://llvm.org/bz46815) |
| Version | unspecified |
| OS | Linux |
| CC | @mydeveloperday |

## Extended Description 
I propose adding a "diffstat" functionality to git-clang-format that essentially uses git diff --stat, i.e. lists the files needing formatting with amount of changes.

This is mostly useful for CI integration or manual usage where one wants to list the files not properly formatted.

I use it for the Suricata project's github action (CI) integration that verifies proper formatting of a pull request's changes according to project guidelines. As part of that yay/nay check, it's very helpful to say which files are not properly formatted as I find the list of files much more useful than e.g. showing the diff of the required formatting changes using git-clang-format --diff.

**Comment by mkurdej** [comment]
Done in https://github.com/llvm/llvm-project/commit/191a395343b984d26d058c449cefe1a9ac0ff927.
Will be available in release 14.
