### ISSUE TITLE
CTAD fails on nested templated class

### ISSUE THREAD

**Issue by narutse** [llvm/llvm-project#46200]
|  |  |
| --- | --- |
| Bugzilla Link | [46856](https://llvm.org/bz46856) |
| Version | 10.0 |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
The following snippet doesn't compile on clang (10), due to CTAD failing. It occurs when the parent class is templated:

```cpp
template <class U>
struct X {	
	template <class T> struct Y {
		T y;
		Y(T t) : y(t) {}		
	};
	auto test() const {
		return Y(10);
	}
};

auto test() {
    return X<int>().test();
}
```

The snippet compiles on msvc and gcc:
https://godbolt.org/z/Wq6Paf

**Comment by AaronBallman** [comment]
This appears to be https://wg21.link/cwg2471
