### ISSUE TITLE
Buildbot - error during "clean stage" on Windows

### ISSUE THREAD

**Issue by ChristianKuehnel** [llvm/llvm-project#46245]
|  |  |
| --- | --- |
| Bugzilla Link | [46901](https://llvm.org/bz46901) |
| Version | unspecified |
| OS | All |

## Extended Description 
Dear Commmunity,

I repeatedly see errors during the "clean step" on my new buildbot worker on Windows:
http://lab.llvm.org:8014/builders/clang-x86-ninja-win10/builds/680

Does anyone have an idea what is causing this? I guess this is Windows related.

The error message says:
---
rm: reading directory `stage1/test/tools/dsymutil/X86/Output/reproducer.test.tmp.repro/volumes/buildbot/windows10-vs2019/clang-x86-ninja-win10/stage1/test/tools/dsymutil/X86/Output/reproducer.test.tmp/Inputs': No such file or directory
rm: cannot remove directory `stage1/test/tools/dsymutil/X86/Output/reproducer.test.tmp.repro/volumes/buildbot/windows10-vs2019/clang-x86-ninja-win10/stage1/test/tools/dsymutil/X86/Output/reproducer.test.tmp': Directory not empty
rm: reading directory `stage1/tools/clang/test/Modules/Output/dependency-dump-dependent-module.m.tmp/vfs/volumes/buildbot/windows10-vs2019/clang-x86-ninja-win10/llvm/clang/test/Modules/Inputs/AlsoDependsOnModule.framework': No such file or directory
rm: cannot chdir from `stage1/tools/clang/test/Modules/Output/dependency-dump-dependent-module.m.tmp/vfs/volumes/buildbot/windows10-vs2019/clang-x86-ninja-win10/llvm/clang/test/Modules/Inputs' to ..: No such file or directory
---

**Comment by JOE1994** [comment]
Buildbot worker `clang-x86-ninja-win10` no longer exists under `https://lab.llvm.org/buildbot/#/builders` .
