### ISSUE TITLE
cmake config failure with Ninja

### ISSUE THREAD

**Issue by bondhugula** [llvm/llvm-project#46250]
|  |  |
| --- | --- |
| Bugzilla Link | [46906](https://llvm.org/bz46906) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie,@jsji,@jvesely,@RKSimon,@orivej |

## Extended Description 
With the configuration below, I get:

.......
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Configuring done
-- Generating done
CMake Error:
  Running

   '/usr/local/bin/ninja' '-C' '/home/uday/llvm-project/build' '-t' 'cleandead'

  failed with:

   ninja: error: remove(include/llvm/Support): Directory not empty
==================

cmake -G Ninja ../llvm      -DLLVM_ENABLE_PROJECTS="mlir"    -DLLVM_TARGETS_TO_BUILD="X86"    -DCMAKE_BUILD_TYPE=Release  -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_ENABLE_LLD=ON -DLLVM_CCACHE_BUILD=ON -DBUILD_SHARED_LIBS=ON

cmake version 3.17.3

ninja --version
1.10.0

Trunk: a4a0844248d4a68a866b9c4e18ae89fa49a83ec0 (from a few hours ago)

**Comment by xgupta** [comment]
I think this issue might be not valid now.
