### ISSUE TITLE
analysis for min/max/abs intrinsics

### ISSUE THREAD

**Issue by rotateright** [llvm/llvm-project#46259]
|  |  |
| --- | --- |
| Bugzilla Link | [46915](https://llvm.org/bz46915) |
| Version | trunk |
| OS | All |
| Depends On | llvm/llvm-project#48244  |
| Blocks | llvm/llvm-project#45317  |
| CC | @topperc,@davezarzycki,@davidbolvansky,@DMG862,@LebedevRI,@RKSimon,@nikic |

## Extended Description 
We recently added IR intrinsics for min/max/abs, and there are several areas that need to be updated to support and optimize these. Please comment here if you are or are planning to work on any part of this, so we do not duplicate effort.

Partial list:
 * ConstantFolding
 * ValueTracking
 * InstSimplify
 * InstCombine
 * PatternMatch
 * DemandedBits
 * Vectorization 
 * Cost Modeling
 * LVI, CVP, SCCP
 * SCEV
 * IndVars

**Comment by nikic** [comment]
Closing this as completed. Remaining issues should be reported separately.
