### ISSUE TITLE
Code breaking reformat for simdjson.h

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46277]
|  |  |
| --- | --- |
| Bugzilla Link | [46933](https://llvm.org/bz46933) |
| Version | 10.0 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Code breaking reformat. The warning disabling macros are broken when processed with this style (spaces inserted in places where they shouldn't).

Example after reformat:
SIMDJSON_DISABLE_GCC_WARNING(-Wmicrosoft - include)

Processing this file:
https://github.com/simdjson/simdjson/blob/master/singleheader/simdjson.h

With this style:
BasedOnStyle: Google
---
Language: Cpp
AlignOperands: true
AlignAfterOpenBracket: AlwaysBreak
AllowAllParametersOfDeclarationOnNextLine: true
BinPackParameters: false
BinPackArguments: false
DerivePointerAlignment: false
PointerAlignment: Left
ColumnLimit: 100

**Comment by rymiel** [comment]
Closing since WhitespaceSensitiveMacros is the intended solution
