### ISSUE TITLE
merge rGbaca8f977edce6edb0f9074b77a38c753f8f0c79 into 11.0.0

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46281]
|  |  |
| --- | --- |
| Bugzilla Link | [46937](https://llvm.org/bz46937) |
| Version | 11.0 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
Please merge baca8f977edce6edb0f9074b77a38c753f8f0c79 into the 11.0.0 release branch

**Comment by arsenm** [comment]
Old release
