### ISSUE TITLE
[SLP] Suboptimal codegen for v2sf operations

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#46310]
|  |  |
| --- | --- |
| Bugzilla Link | [46966](https://llvm.org/bz46966) |
| Version | trunk |
| OS | Linux |
| CC | @topperc,@RKSimon,@rotateright |

## Extended Description 
float r[2], a[2], b[2], c[2];

void test_plus(void) {
  for (int i = 0; i < 2; i++) r[i] = a[i] + b[i];
}

Clang:
test_plus:                              # @&#8203;test_plus
        movss   xmm0, dword ptr [rip + a]       # xmm0 = mem[0],zero,zero,zero
        addss   xmm0, dword ptr [rip + b]
        movss   dword ptr [rip + r], xmm0
        movss   xmm0, dword ptr [rip + a+4]     # xmm0 = mem[0],zero,zero,zero
        addss   xmm0, dword ptr [rip + b+4]
        movss   dword ptr [rip + r+4], xmm0
        ret

GCC:
test_plus:
        movq    xmm0, QWORD PTR a[rip]
        movq    xmm1, QWORD PTR b[rip]
        addps   xmm0, xmm1
        movlps  QWORD PTR r[rip], xmm0
        ret

Godbolt: https://godbolt.org/z/fnxGj1

**Comment by alexey-bataev** [comment]
> #include <stdlib.h>
> 
> #define SIZE 2
> 
> typedef struct vec { float data[SIZE]; } vec;
> 
> vec add(vec a, vec b) { vec result; for (size_t i = 0; i < SIZE; ++i) { result.data[i] = a.data[i] + b.data[i]; } return result; }
> 
> Clang -Ofast -march=skylake: add(vec, vec): # @​add(vec, vec) vaddps xmm0, xmm1, xmm0 vmovss dword ptr [rsp - 8], xmm0 vextractps dword ptr [rsp - 4], xmm0, 1 vmovsd xmm0, qword ptr [rsp - 8] # xmm0 = mem[0],zero ret
> 
> GCC trunk -Ofast -march=skylake: add(vec, vec): vaddps xmm0, xmm0, xmm1 ret

Fixed , https://godbolt.org/z/3P9bfhz11
