### ISSUE TITLE
Clang crashed in clang/lib/AST/ComputeDependence.cpp:32: clang::ExprDependence clang::computeDependence(clang::OpaqueValueExpr *): Assertion '!(D & ExprDependence::UnexpandedPack)' failed

### ISSUE THREAD

**Issue by haoxintu** [llvm/llvm-project#46333]
|  |  |
| --- | --- |
| Bugzilla Link | [46989](https://llvm.org/bz46989) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
Hi, all.

This code makes Clang-trunk crashed, while other released versions compile it normally.

Input:
//small.cc
template <class... T, (virtual T = )> class A {};

Command:
clang++ small.cc

Output:
small.cc:1:24: error: 'virtual' can only appear on non-static member functions
template <class... T, (virtual T = )> class A {};
                       ^
small.cc:1:36: error: expected expression
template <class... T, (virtual T = )> class A {};
                                   ^
clang-12: /home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/clang/lib/AST/ComputeDependence.cpp:32: clang::ExprDependence clang::computeDependence(clang::OpaqueValueExpr *): Assertion `!(D & ExprDependence::UnexpandedPack)' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name small.cc -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -fno-split-dwarf-inlining -debugger-tuning=gdb -resource-dir /home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/lib/clang/12.0.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward -internal-isystem /usr/local/include -internal-isystem /home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/lib/clang/12.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/haoxin/test/clang-bug -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -o /tmp/small-53e090.o -x c++ small.cc 
1.	small.cc:1:36: current parser token ')'
 #&#8203;0 0x0000000002758f44 PrintStackTraceSignalHandler(void*) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x2758f44)
 #&#8203;1 0x0000000002756b4e llvm::sys::RunSignalHandlers() (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x2756b4e)
 #&#8203;2 0x0000000002759265 SignalHandler(int) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x2759265)
 #&#8203;3 0x00007f88b720f390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
 #&#8203;4 0x00007f88b5d79438 raise /build/glibc-e6zv40/glibc-2.23/signal/../sysdeps/unix/sysv/linux/raise.c:54:0
 #&#8203;5 0x00007f88b5d7b03a abort /build/glibc-e6zv40/glibc-2.23/stdlib/abort.c:91:0
 #&#8203;6 0x00007f88b5d71be7 __assert_fail_base /build/glibc-e6zv40/glibc-2.23/assert/assert.c:92:0
 #&#8203;7 0x00007f88b5d71c92 (/lib/x86_64-linux-gnu/libc.so.6+0x2dc92)
 #&#8203;8 0x0000000004b58dea (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x4b58dea)
 #&#8203;9 0x000000000429564e clang::Sema::ActOnParamDefaultArgumentError(clang::Decl*, clang::SourceLocation) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x429564e)
#&#8203;10 0x0000000003ff166d clang::Parser::ParseParameterDeclarationClause(clang::DeclaratorContext, clang::ParsedAttributes&, llvm::SmallVectorImpl<clang::DeclaratorChunk::ParamInfo>&, clang::SourceLocation&) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x3ff166d)
#&#8203;11 0x0000000003feee87 clang::Parser::ParseFunctionDeclarator(clang::Declarator&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&, bool, bool) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x3feee87)
#&#8203;12 0x0000000003fee0f7 clang::Parser::ParseParenDeclarator(clang::Declarator&) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x3fee0f7)
#&#8203;13 0x0000000003febda9 clang::Parser::ParseDirectDeclarator(clang::Declarator&) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x3febda9)
#&#8203;14 0x0000000003feae66 clang::Parser::ParseDeclaratorInternal(clang::Declarator&, void (clang::Parser::*)(clang::Declarator&)) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x3feae66)
#&#8203;15 0x0000000004077a65 clang::Parser::ParseNonTypeTemplateParameter(unsigned int, unsigned int) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x4077a65)
#&#8203;16 0x0000000004075b0d clang::Parser::ParseTemplateParameterList(unsigned int, llvm::SmallVectorImpl<clang::NamedDecl*>&) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x4075b0d)
#&#8203;17 0x00000000040740ff clang::Parser::ParseTemplateParameters(clang::Parser::MultiParseScope&, unsigned int, llvm::SmallVectorImpl<clang::NamedDecl*>&, clang::SourceLocation&, clang::SourceLocation&) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x40740ff)
#&#8203;18 0x0000000004073bac clang::Parser::ParseTemplateDeclarationOrSpecialization(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x4073bac)
#&#8203;19 0x000000000407382e clang::Parser::ParseDeclarationStartingWithTemplate(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x407382e)
#&#8203;20 0x0000000003fdba00 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, clang::SourceLocation*) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x3fdba00)
#&#8203;21 0x0000000003fc35ba clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x3fc35ba)
#&#8203;22 0x0000000003fc1f7d clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x3fc1f7d)
#&#8203;23 0x0000000003fc17c7 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x3fc17c7)
#&#8203;24 0x0000000003fbd27e clang::ParseAST(clang::Sema&, bool, bool) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x3fbd27e)
#&#8203;25 0x0000000002f2a393 clang::FrontendAction::Execute() (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x2f2a393)
#&#8203;26 0x0000000002ec4ea3 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x2ec4ea3)
#&#8203;27 0x0000000002fd43b2 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x2fd43b2)
#&#8203;28 0x0000000000983453 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x983453)
#&#8203;29 0x00000000009818ec ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x9818ec)
#&#8203;30 0x0000000000981594 main (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x981594)
#&#8203;31 0x00007f88b5d64840 __libc_start_main /build/glibc-e6zv40/glibc-2.23/csu/../csu/libc-start.c:325:0
#&#8203;32 0x000000000097e5a9 _start (/home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin/clang-12+0x97e5a9)
clang-12: error: unable to execute command: Aborted (core dumped)
clang-12: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 12.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/haoxin/corpus-compilers/llvm-trunk/llvm-project-master/build/bin
clang-12: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-12: note: diagnostic msg: /tmp/small-a57f17.cpp
clang-12: note: diagnostic msg: /tmp/small-a57f17.sh
clang-12: note: diagnostic msg: 

********************

Thanks,
Haoxin

**Comment by k-mana** [comment]
This no longer reproduces on trunk: https://godbolt.org/z/P9boK8KTq
This has been fixed: [f1b0a4f](https://github.com/llvm/llvm-project/commit/f1b0a4fc540f986372f09768c325d505b75b414d)
