### ISSUE TITLE
_LIBCPP_DEBUG=1 causes link error

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46396]
|  |  |
| --- | --- |
| Bugzilla Link | [47052](https://llvm.org/bz47052) |
| Version | 11.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 
This program: (err1.cpp)

#include <vector>

int
main()
{
  std::vector<int> v;
  
  return 0;
}

Compiled with:

clang++  -stdlib=libc++ -D_LIBCPP_DEBUG=1  -o err1 err1.cpp

Results in:

/tmp/err1-babb29.o: In function `void std::__1::__libcpp_db::__insert_c<std::__1::vector<int, std::__1::allocator<int> > >(std::__1::vector<int, std::__1::allocator<int> >*)':
err1.cpp:(.text._ZNSt3__111__libcpp_db10__insert_cINS_6vectorIiNS_9allocatorIiEEEEEEvPT_[_ZNSt3__111__libcpp_db10__insert_cINS_6vectorIiNS_9allocatorIiEEEEEEvPT_]+0x26): undefined reference to `std::__1::__libcpp_db::__insert_c(void*, std::__1::__c_node* (*)(void*, void*, std::__1::__c_node*))'
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:5: recipe for target 'err1' failed
make: *** [err1] Error 1
make: Target 'all' not remade because of errors.

**Comment by philnik777** [comment]
It looks like the libc++ instance was configured without debug symbols. Closing, since a library configured with the debug-mode enabled is now required.
