### ISSUE TITLE
Failure to optimize some related bool comparisons to xor+and

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#46405]
|  |  |
| --- | --- |
| Bugzilla Link | [47061](https://llvm.org/bz47061) |
| Version | trunk |
| OS | Linux |
| CC | @RKSimon |

## Extended Description 
int f(int a, int b, int c)
{
    return (a && !b && c) || (!a && b && c);
}

This can be optimized to `((bool)a ^ (bool)b) & (bool)c`. This transformation is done by GCC, but not by LLVM.

**Comment by GabrielRavier** [comment]
Seems to be fixed on trunk ?

**Comment by dtcxzyw** [comment]
Should be fixed by https://github.com/llvm/llvm-project/pull/94915.
https://godbolt.org/z/MWcbvc5nz
