### ISSUE TITLE
Avoid doing equality comparisons between floating expressions.(llvm-project/clang-tools-extra/clang-tidy/bugprone/IncorrectRoundingsCheck.cpp:line 26 and 28)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46424]
|  |  |
| --- | --- |
| Bugzilla Link | [47080](https://llvm.org/bz47080) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Avoid doing equality comparisons between floating expressions.

commit e3546c78cabfbf670391a57766872f0a8e28a423

llvm-project/clang-tools-extra/clang-tidy/bugprone/IncorrectRoundingsCheck.cpp:line 26 and 28

    22	namespace {
    23	AST_MATCHER(FloatingLiteral, floatHalf) {
    24	  const auto &literal = Node.getValue();
    25	  if ((&Node.getSemantics()) == &llvm::APFloat::IEEEsingle())
    26	    return literal.convertToFloat() == 0.5f;
    27	  if ((&Node.getSemantics()) == &llvm::APFloat::IEEEdouble())
    28	    return literal.convertToDouble() == 0.5;
    29	  return false;
    30	}
    31	} // namespace

Reported by: Ustchcs Toolsets Bugfinder
(bugfinder-5.15: Avoid doing equality comparisons between floating expressions.)

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D147906
