### ISSUE TITLE
Failure to optimize code involving strnlen

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#46455]
|  |  |
| --- | --- |
| Bugzilla Link | [47111](https://llvm.org/bz47111) |
| Version | trunk |
| OS | Linux |
| CC | @rotateright |

## Extended Description 
size_t f()
{
    return strnlen("", 0);
}

This code can be transformed to `return 0;`. This transformation is done by GCC, but not by LLVM. This is most likely caused by a lack of a builtin for strnlen.

**Comment by msebor** [comment]
I have posted for review a patch that implements `strnlen` folding: https://reviews.llvm.org/D122686
I suppose I should assign this bug to myself but I don't see a way to do that.

**Comment by msebor** [comment]
Resolved by [D123815](https://reviews.llvm.org/D123815) and related.
