### ISSUE TITLE
MLIR tests are crashing on 32-bit arm linux

### ISSUE THREAD

**Issue by rovka** [llvm/llvm-project#46459]
|  |  |
| --- | --- |
| Bugzilla Link | [47115](https://llvm.org/bz47115) |
| Version | unspecified |
| OS | Linux |
| CC | @zmodem,@jpienaar,@River707,@ftynse |

## Extended Description 
I'm seeing about 250 MLIR test failures for 11.0.0 rc1. I haven't confirmed but it's possible that it just runs out of memory (the board has 1 GB per core allocated). All failures look something like this:

******************** TEST 'MLIR :: Analysis/test-dominance.mlir' FAILED ********************
Script:
--
: 'RUN: at line 1';   /home/tcwg-buildslave/workspace/tcwg-llvm-release/tcwg-tk1_32-build/rc1/Phase3/Release/llvmCore-11.0.0-rc1.obj/bin/mlir-opt /home/tcwg-buildslave/workspace/tcwg-llvm-release/tcwg-tk1_32-build/rc1/llvm-project/mlir/test/Analysis/test-dominance.mlir -test-print-dominance -split-input-file 2>&1 | /home/tcwg-buildslave/workspace/tcwg-llvm-release/tcwg-tk1_32-build/rc1/Phase3/Release/llvmCore-11.0.0-rc1.obj/bin/FileCheck /home/tcwg-buildslave/workspace/tcwg-llvm-release/tcwg-tk1_32-build/rc1/llvm-project/mlir/test/Analysis/test-dominance.mlir
--
Exit Code: 1

Command Output (stderr):
--
/home/tcwg-buildslave/workspace/tcwg-llvm-release/tcwg-tk1_32-build/rc1/llvm-project/mlir/test/Analysis/test-dominance.mlir:3:17: error: CHECK-LABEL: expected string not found in input
// CHECK-LABEL: Testing : func_condBranch
                ^
<stdin>:1:1: note: scanning from here
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
^
<stdin>:1:50: note: possible intended match here
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
                                                 ^

Input file: <stdin>
Check file: /home/tcwg-buildslave/workspace/tcwg-llvm-release/tcwg-tk1_32-build/rc1/llvm-project/mlir/test/Analysis/test-dominance.mlir

-dump-input=help explains the following input dump.

Input was:
<<<<<<
           1: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
label:3'0     X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
label:3'1                                                      ?                                    possible intended match
           2: Stack dump:
label:3'0     ~~~~~~~~~~~
           3: 0. Program arguments: /home/tcwg-buildslave/workspace/tcwg-llvm-release/tcwg-tk1_32-build/rc1/Phase3/Release/llvmCore-11.0.0-rc1.obj/bin/mlir-opt /home/tcwg-buildslave/workspace/tcwg-llvm-release/tcwg-tk1_32-build/rc1/llvm-project/mlir/test/Analysis/test-dominance.mlir -test-print-dominance -split-input-file
label:3'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>>>>>>

**Comment by arsenm** [comment]
Old build issue
