### ISSUE TITLE
ICE: is_invocable_v (access via :: of non static member)

### ISSUE THREAD

**Issue by bernd5** [llvm/llvm-project#46463]
|  |  |
| --- | --- |
| Bugzilla Link | [47119](https://llvm.org/bz47119) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [compiler output](https://user-images.githubusercontent.com/95090604/143761087-35d06837-3de0-4fe0-84a8-c2b382c98177.gz) |
| CC | @DougGregor,@bernd5,@ojeda,@zygoloid |

## Extended Description 

Clang++ front-end crashes with the following code:

Compilation command: clang++ -std=c++17 sample.cpp

See here on godbolt: https://godbolt.org/z/o1xjK8

Code:
=================
```
#include <type_traits>

struct S {
    void Func() {
    }
};

#include <iostream>
int main()
{
    auto lambda = [](const auto& cls) -> decltype(
        std::remove_const_t<std::remove_reference_t<decltype(cls)>>::Func()
    ) {};

    auto isInv = std::is_invocable_v<decltype(lambda), S>;
    if (!isInv){
        std::cout << "detected correctly";
    }
    return 0;
}
```

**Comment by MagentaTreehouse** [comment]
The original repro is no longer crashing on trunk.
