### ISSUE TITLE
Front end crashes when trying to export a type out of a module

### ISSUE THREAD

**Issue by vstiago** [llvm/llvm-project#46460]
|  |  |
| --- | --- |
| Bugzilla Link | [47116](https://llvm.org/bz47116) |
| Version | 10.0 |
| OS | Linux |
| CC | @dwblaikie,@zygoloid |

## Extended Description 
https://godbolt.org/z/6fEE3s

I was trying to convert a header file to a module.

The compiler complained that it could export a std:pair of a iterator class inside a template class (I was trying to emulate the behavior of a stl container.)

My code is probably wrong because I don't know how modules work but it probably shouldn't crash.

I found it with clang 10 on ubuntu, but it also happens on trunk (according to godbolt).

**Comment by ChuanqiXu9** [comment]
Addressed in https://github.com/llvm/llvm-project/commit/3a3af2bbc97e7db045eccb8683e93b9aa7ef562b
