### ISSUE TITLE
length_error exception not being thrown

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46484]
|  |  |
| --- | --- |
| Bugzilla Link | [47140](https://llvm.org/bz47140) |
| Version | 10.0 |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@mclow,@zygoloid |

## Extended Description 
This program should cause a length_error immediately but it doesn't. This behavior is followed by GCC 10 and MetroWerks C++ compilers. 

```c++
#include <iostream>
#include <string>

using namespace std;

int main(int argc, const char * argv[])
{
    string buffer("hi");
    try {
        std::string mystring(buffer.max_size()+1, 'X');
    }
    
    catch(length_error &l) {
        cout<<"Caught length_error exception: "<<l.what()<<endl;
    }
    
    catch(exception &e) {
        cout<<"Caught exception: "<<e.what()<<endl;
    }
    return 0;
}
```

What actually happens is the program crashes with EXC_BAD_ACCESS on Mac OS 10.8. Clang 5.1 and Clang 10.0.0.1 have this issue.

**Comment by ldionne** [comment]
This appears to be working now: https://godbolt.org/z/PsMnEoeWG.

Please reopen if I'm mistaken.
