### ISSUE TITLE
Failure to optimize out strlen that isn't used for any other purpose than more strlen calls (which don't have any external effect)

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#46497]
|  |  |
| --- | --- |
| Bugzilla Link | [47153](https://llvm.org/bz47153) |
| Version | trunk |
| OS | Linux |

## Extended Description 
```
void f(const char *a)
{
    while (*a)
        a += strlen(a);
}
```
This can be optimized to doing nothing. This transformation is done by GCC, but not by LLVM. The same transformation can be done if `strlen(a)` is replaced by `strspn(a, some_other_string)`, and can probably also be done for more examples alike to this with alike functions.

**Comment by GabrielRavier** [comment]
Appears to still be fixed on trunk.

**Comment by nikic** [comment]
This only happens with `-ffinite-loops` (the default), because the loop is just dead. Is that what was intended?

**Comment by GabrielRavier** [comment]
Well, I really don't remember the original testcase for this but to me the interesting part right now is simply that the somewhat entangled usage of `strlen` appeared to be confusing LLVM into thinking the loop was alive, so I guess so ?

**Comment by nikic** [comment]
Okay, let's consider this fixed...
