### ISSUE TITLE
clang-format does not handle semicolons in template argument lists

### ISSUE THREAD

**Issue by 976866b7-fc02-4d23-a1c0-197b08fd7c0e** [llvm/llvm-project#46505]
|  |  |
| --- | --- |
| Bugzilla Link | [47161](https://llvm.org/bz47161) |
| Version | trunk |
| OS | Linux |
| CC | @JohelEGP,@mydeveloperday |

## Extended Description 
This is how semicolons in template argument lists are formatted with the default configuration:
```C++
template <auto> struct X {};

struct Y : X < [] {
  return 0;
} > {};

struct Z : X < decltype([]
{
  return 0;
}){} > {};

struct W : X < requires {
  ill - formed;
} > {};
```
These uses will become more common in C++20 thanks to the used features.

**Comment by mydeveloperday** [comment]
https://reviews.llvm.org/D116806

**Comment by JohelEGP** [comment]
Awesome, thank you.

**Comment by JohelEGP** [comment]
It seems that this still suffers:
```diff
-struct W : X<requires { ill - formed; }> {}
+struct W : X < requires {
+  ill - formed;
+} > {};
```
