### ISSUE TITLE
clang++: error: unable to execute command: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46527]
|  |  |
| --- | --- |
| Bugzilla Link | [47183](https://llvm.org/bz47183) |
| Version | 3.8 |
| OS | Linux |
| Attachments | [diagnostic msg](https://user-images.githubusercontent.com/60944935/143761103-d4949702-69d7-4110-b185-89a708b9ac19.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description

**Comment by Endilll** [comment]
Can't reproduce using Clang 3.7 through 3.9 with assertions enabled.
Reproducer mentions Android Clang, so it might be a downstream issue.
