### ISSUE TITLE
Assert in SemaExprMember.cpp after 61700724

### ISSUE THREAD

**Issue by pogo59** [llvm/llvm-project#46555]
|  |  |
| --- | --- |
| Bugzilla Link | [47211](https://llvm.org/bz47211) |
| Version | unspecified |
| OS | Linux |
| Attachments | [crash log](https://user-images.githubusercontent.com/32180645/143761105-dcb005df-465d-4ddf-ad5e-b058f1f2217e.gz) |
| CC | @dyung,@miyuki,@zygoloid |

## Extended Description 

The following source used to get an error diagnostic, now it asserts.

class C {
    public:
        template <class T> static constexpr T G = T(6.675e-11);
};
template <class T> T F() {
    C object;
    return object.G<T>;
}

int foo() {
  return F<int>();
}

Bisected to 61700724:

commit 617007240cbfb97c8ccf6d61b0c4ca0bb62d43c9 (HEAD)
Author: Richard Smith <richard@metafoo.co.uk>
Date:   Wed Jul 15 19:37:15 2020 -0700

    Improve modeling of variable template specializations with dependent
    arguments.
    
    Don't build a variable template specialization declaration until its
    scope and template arguments are non-dependent.
    
    No functionality change intended, but the AST representation is now more
    consistent with how we model other templates.

**Comment by yuanfang-chen** [comment]
Fixed by e902ffe6d756
