### ISSUE TITLE
clang doesn't provide __builtin_sprintf

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#46568]
|  |  |
| --- | --- |
| Bugzilla Link | [47224](https://llvm.org/bz47224) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
__builtin_snprintf is provided, but not __builtin_sprintf.

**Comment by wheatman** [comment]
seems to have been fixed between 12.0.1 `<source>:2:5: error: use of undeclared identifier '__builtin_sprintf'`
and 13.0.0

https://godbolt.org/z/z9Wz3h7qK
