### ISSUE TITLE
Instcombine drops range information when combining inttoptr with load

### ISSUE THREAD

**Issue by qcolombet** [llvm/llvm-project#46587]
|  |  |
| --- | --- |
| Bugzilla Link | [47243](https://llvm.org/bz47243) |
| Version | trunk |
| OS | All |
| Attachments | [Reproducer](https://user-images.githubusercontent.com/15787733/143761116-d897823c-3f1e-4b6b-a82b-269909ba7d9c.gz) |
| CC | @fhahn,@jdoerfert |

## Extended Description 

When instcombine replaces inttoptr(load intTy) to (load ptrTy) it drops the range information attached to the load.
More precisely, it replaces the range information with an inferior metadata.

The problem may lay into what the range information can represent, but we should fix that one way or another as this may result in suboptimal code.

* Example *

Consider the following snippet:
```
define float* @&#8203;test5_range(i64* %ptr) {
entry:
  %val = load i64, i64* %ptr, !range !{i64 64, i64 65536}
  %valptr = inttoptr i64 %val to float*
  ret float* %valptr
}
```

The returned pointer is known to be between address 64 and address 65536.

After instcombine however, this information is lost and instead we have a less rich information that the pointer is non-null:
```
define float* @&#8203;test5_range(i64* %ptr) {
entry:
  %0 = bitcast i64* %ptr to float**
  %val1 = load float*, float** %0, align 4, !nonnull !&#8203;0
  ret float* %val1
}
```

* To Reproduce *

opt -S  -instcombine ~/Downloads/instcombine_range.ll  -o -

**Comment by msebor** [comment]
The expected range seems to be preserved on trunk (16.0) so it this must have been fixed.  It might be worth adding the test to the test suite if one doesn't cover this case yet.
```
$ (set -x && cat llvm-pr46587.ll && opt -S -instcombine llvm-pr46587.ll)
+ cat llvm-pr46587.ll
define float* @f(i64* %ptr) {
entry:
  %val = load i64, i64* %ptr, !range !{i64 64, i64 65536}
  %valptr = inttoptr i64 %val to float*
  ret float* %valptr
}
+ opt -S -instcombine llvm-pr46587.ll
; ModuleID = 'llvm-pr46587.ll'
source_filename = "llvm-pr46587.ll"

define float* @f(i64* %ptr) {
entry:
  %val = load i64, i64* %ptr, align 4, !range !0
  %valptr = inttoptr i64 %val to float*
  ret float* %valptr
}

!0 = !{i64 64, i64 65536}
```

**Comment by qcolombet** [comment]
Hi @msebor,
From what you shared it looks like the reason the range is correct is because no combine has been applied.
Maybe that was an intentional fix to preserve the range information or the reproducer is not enough to expose the issue anymore.

**Comment by msebor** [comment]
Those seem plausible.  I don't have a way to track down the change that preserves the range.  In traiging these old reports I've made the assumption that it's helpful to close those that are not reproducible.  Please let me know if that's not so or feel free to reopen this report if you think it might still serve a purpose.
