### ISSUE TITLE
Some builtin intrinsics that are not constexpr but could be

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#46593]
|  |  |
| --- | --- |
| Bugzilla Link | [47249](https://llvm.org/bz47249) |
| Version | unspecified |
| OS | Windows NT |
| CC | @erichkeane,@zygoloid |
| Fixed by commit(s) | e7d9182a666a , 2ceac91ec0fc , 00158ae236ddfdc |

This isn't exhaustive, but all are low hanging fruit:

### bit twiddling:

- [x] `__builtin_bitreverse` [D86339](https://reviews.llvm.org/D86339) https://github.com/llvm/llvm-project/commit/e7d9182a666a2a8f903bd330c82d7c623b783371
- [x] `__builtin_rotateleft` [D86342](https://reviews.llvm.org/D86342) https://github.com/llvm/llvm-project/commit/2ceac91ec0fc186ff503402e7b88e4576a69008d
- [x] `__builtin_rotateright` [D86342](https://reviews.llvm.org/D86342) https://github.com/llvm/llvm-project/commit/2ceac91ec0fc186ff503402e7b88e4576a69008d

### vectors:

- [x] `__builtin_convertvector`
- [x] `__builtin_shufflevector`

### -fms-extensions variants:

- [x] `__lzcnt16`, `__lzcnt`, `__lzcnt64` [D157420](https://reviews.llvm.org/D157420) 00158ae236ddfdc 
- [x] `__popcnt16`, `__popcnt`, `__popcnt64` [D157420](https://reviews.llvm.org/D157420) 00158ae236ddfdc 
- [x] `_rotl8`, `_rotl16`, `_rotl`, `_rotl64`, `_lrotl`
- [x] `_rotr8`, `_rotr16`, `_rotr`, `_rotr64`, `_lrotr`

**Comment by Endilll** [comment]
Feels like a good first issue.

CC @shafik @AaronBallman

**Comment by RKSimon** [comment]
> Feels like a good first issue.

Agreed although they need splitting into separate tasks - the ms-extension variants are pretty trivial, but convertvector might be harder and I expect shufflevector to be tricky.

**Comment by shafik** [comment]
@RKSimon Looking at the PRs above they look relatively straight forward.

**Comment by alexguirre** [comment]
Hi, seems like the ROTL/ROTR ms-extension intrinsics were already made constexpr in a1dc3d241ba00042b6160287f887d1019e36bae0.

I would like to work on the remaining intrinsics.

**Comment by alexguirre** [comment]
Submitted a patch for lzcnt/popcnt https://reviews.llvm.org/D157420

**Comment by BertalanD** [comment]
> Also `__builtin_addc` and `__builtin_subc`?

I'm on it: [D156156](https://reviews.llvm.org/D156156). I'll try to find time to finish it this week.

**Comment by RKSimon** [comment]
Also #51787 (elementwise and reduction builtins)

**Comment by Destroyerrrocket** [comment]
Could I take the last two missing expressions?

**Comment by shafik** [comment]
> Could I take the last two missing expressions?

It does not look like anyone is currently working on them, so I can assign this to you if you want.

**Comment by Destroyerrrocket** [comment]
Thank you, I'll take it then!

**Comment by Destroyerrrocket** [comment]
Thank you! I'd like to take it, yes

**Comment by RKSimon** [comment]
@Destroyerrrocket Go for it! I'd recommend you start with `__builtin_convertvector`

**Comment by Destroyerrrocket** [comment]
Hi! I've made the changes for both intrinsics here: https://github.com/llvm/llvm-project/pull/76615
(I think that now you're meant to use github PRs? The bot seems to suggest to use Phabricator, but it seems down)

**Comment by Endilll** [comment]
> (I think that now you're meant to use github PRs? The bot seems to suggest to use Phabricator, but it seems down)

Yes, we moved over to GitHub PRs since that comment was posted.

**Comment by RKSimon** [comment]
Closing - __builtin_shufflevector and __builtin_convertvector were handled in #76615
