### ISSUE TITLE
<version> header is missing __cpp_lib_type_identity and other macros

### ISSUE THREAD

**Issue by marehr** [llvm/llvm-project#46605]
|  |  |
| --- | --- |
| Bugzilla Link | [47261](https://llvm.org/bz47261) |
| Version | 11.0 |
| OS | Linux |
| CC | @mclow |

## Extended Description 
Hi clang-team,

the following code doesn't compile, even thought it can compile `std::type_identity` and `std::unwrap_reference` just fine since clang 9.0.0.

```c++
#include <type_traits>

using a = std::type_identity<int>; // works fine
using b = std::unwrap_reference_t<int>; // works fine

#ifndef __cpp_lib_type_identity
#error "Not defined?"
#endif

#ifndef __cpp_lib_unwrap_ref
#error "Not defined?"
#endif
```

https://godbolt.org/z/6vaa6x

I thought https://eel.is/c++draft/version.syn suggests that __cpp_lib_type_identity should be defined if it was implemented.

Thank you!

**Comment by Quuxplusone** [comment]
This is now https://reviews.llvm.org/D116433
