### ISSUE TITLE
mingw-w64: std::wcout after _setmode(_fileno(stdout), _O_WTEXT) doesn't work

### ISSUE THREAD

**Issue by 90e2333d-394f-40bb-b6bb-805f8d2a5bfd** [llvm/llvm-project#46646]
|  |  |
| --- | --- |
| Bugzilla Link | [47302](https://llvm.org/bz47302) |
| Version | 10.0 |
| OS | Windows NT |
| CC | @mclow |

## Extended Description 
Take this code snippet:
```
#include <iostream>
#include <io.h>
#include <fcntl.h>

int wmain(int argc, const wchar_t* argv[])
{
    _setmode(_fileno(stdout), _O_WTEXT);
    std::wcout << L"Thử nghiệm\n";
    return 0;
}
```

On MS STL, this correctly outputs the string, but on libc++ it outputs nothing.

Additional notes:
Add `-municode` when compiling with clang, and add `/utf-8` when compiling with MSVC

**Comment by mstorsjo** [comment]
I've posted an initial patch that tries to fix this issue at https://reviews.llvm.org/D146398.
