### ISSUE TITLE
Assertion `(!needsOverloadResolutionForDestructor() || (data().DeclaredSpecialMembers & SMF_Destructor)) && "this property has not yet been computed by Sema"' failed.

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#46662]
|  |  |
| --- | --- |
| Bugzilla Link | [47318](https://llvm.org/bz47318) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
reproduce code:

class Base {
public:
  ~Base();
};

class Derived : public Base {
public:
  ~Derived(int);
};

stacktrace:

clang: /llvm-project/clang/include/clang/AST/DeclCXX.h:697: bool clang::CXXRecordDecl::defaultedDestructorIsDeleted() const: Assertion `(!needsOverloadResolutionForDestructor() || (data().DeclaredSpecialMembers & SMF_Destructor)) && "this property has not yet been computed by Sema"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: ./bin/clang -cc1 -ast-dump /tmp/t5.cpp 
1.      /tmp/t5.cpp:12:2: current parser token ';'
2.      /tmp/t5.cpp:9:1: parsing struct/union/class body 'Derived'
 #&#8203;0 0x0000000004475c4a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /llvm-project/llvm/lib/Support/Unix/Signals.inc:563:11
 #&#8203;1 0x0000000004475dfb PrintStackTraceSignalHandler(void*) /llvm-project/llvm/lib/Support/Unix/Signals.inc:627:1
 #&#8203;2 0x00000000044745db llvm::sys::RunSignalHandlers() /llvm-project/llvm/lib/Support/Signals.cpp:69:5
 #&#8203;3 0x000000000447654d SignalHandler(int) /llvm-project/llvm/lib/Support/Unix/Signals.inc:405:1
 #&#8203;4 0x00007f0e5eb7b110 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14110)
 #&#8203;5 0x00007f0e5d0f6761 raise /build/glibc-M65Gwz/glibc-2.30/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #&#8203;6 0x00007f0e5d0e055b abort /build/glibc-M65Gwz/glibc-2.30/stdlib/abort.c:81:7
 #&#8203;7 0x00007f0e5d0e042f get_sysdep_segment_value /build/glibc-M65Gwz/glibc-2.30/intl/loadmsgcat.c:509:8
 #&#8203;8 0x00007f0e5d0e042f _nl_load_domain /build/glibc-M65Gwz/glibc-2.30/intl/loadmsgcat.c:970:34
 #&#8203;9 0x00007f0e5d0ef092 (/lib/x86_64-linux-gnu/libc.so.6+0x34092)
#&#8203;10 0x0000000007f0b3c1 clang::CXXRecordDecl::defaultedDestructorIsDeleted() const /llvm-project/clang/include/clang/AST/DeclCXX.h:0:5
#&#8203;11 0x0000000007e3c7cf canPassInRegisters(clang::Sema&, clang::CXXRecordDecl*, clang::TargetInfo::CallingConvKind) /llvm-project/clang/lib/Sema/SemaDeclCXX.cpp:6466:74
#&#8203;12 0x0000000007e3b2c6 clang::Sema::CheckCompletedCXXClass(clang::Scope*, clang::CXXRecordDecl*) /llvm-project/clang/lib/Sema/SemaDeclCXX.cpp:6807:8
#&#8203;13 0x0000000007e446f7 clang::Sema::ActOnFinishCXXMemberSpecification(clang::Scope*, clang::SourceLocation, clang::Decl*, clang::SourceLocation, clang::SourceLocation, clang::ParsedAttributesView const&) /llvm-project/clang/lib/Sema/SemaDeclCXX.cpp:9815:1
#&#8203;14 0x0000000007a1c5a6 clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::Parser::ParsedAttributesWithRange&, unsigned int, clang::Decl*) /llvm-project/clang/lib/Parse/ParseDeclCXX.cpp:3369:7
#&#8203;15 0x0000000007a1ac0d clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::Parser::ParsedAttributesWithRange&) /llvm-project/clang/lib/Parse/ParseDeclCXX.cpp:1962:7
#&#8203;16 0x00000000079f4402 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) /llvm-project/clang/lib/Parse/ParseDecl.cpp:3839:12
#&#8203;17 0x00000000079ced4d clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) /llvm-project/clang/lib/Parse/Parser.cpp:1011:7
#&#8203;18 0x00000000079ce920 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) /llvm-project/clang/lib/Parse/Parser.cpp:1116:12
#&#8203;19 0x00000000079ce1b3 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) /llvm-project/clang/lib/Parse/Parser.cpp:936:12
#&#8203;20 0x00000000079cc475 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) /llvm-project/clang/lib/Parse/Parser.cpp:684:12

**Comment by wheatman** [comment]
This was fixed between 10.0.0 and 11.0.0
https://cexplorer.testlabs.pro/z/616986

As a note this only shows up with assertions on

for reference
code 
```
class Base {
public:
  ~Base();
};

class Derived : public Base {
public:
  ~Derived(int);
};
```

dump
```
<source>:8:3: error: destructor cannot have any parameters
  ~Derived(int);
  ^
clang++: /home/tonik/llvm-project/llvm/tools/clang/include/clang/AST/DeclCXX.h:694: bool clang::CXXRecordDecl::defaultedDestructorIsDeleted() const: Assertion `(!needsOverloadResolutionForDestructor() || (data().DeclaredSpecialMembers & SMF_Destructor)) && "this property has not yet been computed by Sema"' failed.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-10.0.0-assert/bin/clang++ -gdwarf-4 -g -o /tmp/compiler-explorer-compiler2023615-989231-g0juiw.41ase/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-9.3.0 -fcolor-diagnostics -fno-crash-diagnostics <source> 
1.	<source>:9:2: current parser token ';'
2.	<source>:6:1: parsing struct/union/class body 'Derived'
 #0 0x00000000028c468a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x28c468a)
 #1 0x00000000028c2314 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x28c2314)
 #2 0x00000000028c2589 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x28c2589)
 #3 0x0000000002839eb8 CrashRecoverySignalHandler(int) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x2839eb8)
 #4 0x00007f366b654df0 __restore_rt (/lib64/libc.so.6+0x54df0)
 #5 0x00007f366b6a154c __pthread_kill_implementation (/lib64/libc.so.6+0xa154c)
 #6 0x00007f366b654d46 raise (/lib64/libc.so.6+0x54d46)
 #7 0x00007f366b6287f3 abort (/lib64/libc.so.6+0x287f3)
 #8 0x00007f366b62871b _nl_load_domain.cold (/lib64/libc.so.6+0x2871b)
 #9 0x00007f366b64dce6 (/lib64/libc.so.6+0x4dce6)
#10 0x00000000046c8dbf clang::Sema::CheckCompletedCXXClass(clang::Scope*, clang::CXXRecordDecl*) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x46c8dbf)
#11 0x00000000046c966c clang::Sema::ActOnFinishCXXMemberSpecification(clang::Scope*, clang::SourceLocation, clang::Decl*, clang::SourceLocation, clang::SourceLocation, clang::ParsedAttributesView const&) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x46c966c)
#12 0x000000000438daca clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::Parser::ParsedAttributesWithRange&, unsigned int, clang::Decl*) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x438daca)
#13 0x000000000438ffc0 clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::Parser::ParsedAttributesWithRange&) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x438ffc0)
#14 0x0000000004370745 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x4370745)
#15 0x000000000434b34f clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x434b34f)
#16 0x000000000434bc51 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x434bc51)
#17 0x0000000004351486 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (.localalias) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x4351486)
#18 0x00000000043521f8 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x43521f8)
#19 0x0000000004345b29 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x4345b29)
#20 0x0000000003782448 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x3782448)
#21 0x0000000003100b69 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x3100b69)
#22 0x00000000030bb09e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x30bb09e)
#23 0x00000000031d3ef4 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x31d3ef4)
#24 0x0000000000900817 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x900817)
#25 0x00000000008fc807 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x8fc807)
#26 0x0000000002f88625 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::'lambda'()>(long) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x2f88625)
#27 0x000000000283a034 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x283a034)
#28 0x0000000002f890d6 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (.part.0) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x2f890d6)
#29 0x0000000002f616b8 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x2f616b8)
#30 0x0000000002f61ff9 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x2f61ff9)
#31 0x0000000002f6b9c1 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x2f6b9c1)
#32 0x0000000000870def main (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x870def)
#33 0x00007f366b63feb0 __libc_start_call_main (/lib64/libc.so.6+0x3feb0)
#34 0x00007f366b63ff60 __libc_start_main_impl (/lib64/libc.so.6+0x3ff60)
#35 0x00000000008fc3b9 _start (/opt/compiler-explorer/clang-10.0.0-assert/bin/clang+++0x8fc3b9)
clang-10: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 254
```
