### ISSUE TITLE
opt -instcombine -disable-basic-aa -available-load-scan-limit=0 failing with "LLVM ERROR: Instruction Combining seems stuck in an infinite loop after 100 iterations."

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#46705]
|  |  |
| --- | --- |
| Bugzilla Link | [47361](https://llvm.org/bz47361) |
| Version | trunk |
| OS | Linux |
| Attachments | [bbi-46639.ll reproducer](https://user-images.githubusercontent.com/55733087/143761147-1be26357-44fc-41b6-ba55-559f12e029ab.gz) |
| CC | @RKSimon,@nikic,@rotateright |

## Extended Description 

Reproduce with:
 opt -instcombine -disable-basic-aa -available-load-scan-limit=0 -S -o - bbi-46639.ll

Result:
 LLVM ERROR: Instruction Combining seems stuck in an infinite loop after 100 iterations.

It passes if we just raise the number of allowed iterations to 101 with -instcombine-infinite-loop-threshold=101

Perhaps the many iterations is just a result of making life hard for instcombine with -disable-basic-aa -available-load-scan-limit=0, I don't know.

**Comment by fhahn** [comment]
Looks like this has been fixed in upstream, the reproducer now also works with an iteration threshold of 10: https://llvm.godbolt.org/z/jhxWqe6rd

Please re-open the issue with additional info if it still reproduces on your end.
