### ISSUE TITLE
rejects-valid on non-trailing requires clause in generic lambda

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#46720]
|  |  |
| --- | --- |
| Bugzilla Link | [47376](https://llvm.org/bz47376) |
| Version | unspecified |
| OS | All |
| CC | @CaseyCarter,@zygoloid,@saarraz |

## Extended Description 
Per https://wg21.link/p0857r0 (which we claim to implement), a requires-clause can appear after the explicit template parameter list in a generic lambda, but Clang rejects:

<source>:1:25: error: lambda requires '()' before 'requires' clause
auto x = []<typename T> requires true () {};
                        ^
                        ()

**Comment by xgupta** [comment]
Clang is accepting it now on the trunk, - https://godbolt.org/z/z8nzq6zxd.
