### ISSUE TITLE
clang++ hangs when optimizing the infinite loop

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46802]
|  |  |
| --- | --- |
| Bugzilla Link | [47458](https://llvm.org/bz47458) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Hi, the following code causes clang++ hangs with -O2/O3/Os.

$ cat s.cpp

struct A {
        float a;
        A ( float b ){
                for ( int c ; c < b ;)
                        ++ a ;
        }
};
struct B {
        B ( A );
};
int main (){
        A (1.0);
        B d (0.0), e (1.0);
}

$ clang++ -O2 s.cpp
<hang>

$ clang -v
clang version 11.0.0 (https://github.com/llvm/llvm-project.git ab4627364aefcaac751e757b721b7d07b48a545a)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/oscar/compiler/llvm-project/build/bin

**Comment by JOE1994** [comment]
No longer hangs with `clang 18.1.0` : https://godbolt.org/z/r1rbqbKTK
