### ISSUE TITLE
[Early Machine LICM] Bad machine code: Virtual register killed in block, but needed live out.

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#46827]
|  |  |
| --- | --- |
| Bugzilla Link | [47483](https://llvm.org/bz47483) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced testcase](https://user-images.githubusercontent.com/55128014/143761188-5f2c395b-6bab-4d00-8ad7-2fc18e05291c.gz) |
| CC | @topperc,@JonPsson,@vedantk |

## Extended Description 

llc -mcpu=z13 -O3 tc_mver_vregkilled_neededliveout.ll -sink-insts-to-avoid-spills -verify-machineinstrs

*** Bad machine code: Virtual register killed in block, but needed live out. ***
- function:    main
- basic block: %bb.3 bb5 (0x677c338)
Virtual register %5 is used after the block.
LLVM ERROR: Found 1 machine code errors.

An LLGCR instruction with a killed vreg %5 is moved *into* the loop without the kill flag being cleared...

**Comment by JonPsson** [comment]
[testcase.tar.gz](https://github.com/llvm/llvm-project/files/8799499/testcase.tar.gz)

llc -mcpu=arch13 -O3 -consthoist-gep -sink-insts-to-avoid-spills -verify-machineinstrs tc_crash0_aftercreduce.ll

This is still here...

A little unhappy with the confusion about kill flags and their "trustworthiness". When working on transformations it would be helpful to have something more documented, rather than "maybe not trust" kill flags "late". 

Ideally, either the verifier should not complain if it is actually acceptable (i.e. "kill flags are not guaranteed to be correct"), or the transformation should be fixed to not leave false kill flags.

Having liveness modelled correctly always (all actually killing uses marked as "kill") would be ideal but not practical if it is not really needed and difficult to compute. A first good step then I think would be to at least clear kill flags to conservatively omit them rather than ignoring them and leaving a false kill flag in the IR (which could theoretically be dangerous if that kill flag is "trusted").

**Comment by perlfu** [comment]
I am not sure why this was assigned to me, was this a bug I created?

Probable solution: https://reviews.llvm.org/D126754

**Comment by JonPsson** [comment]
Thanks for the patch! Your name was the best one I could find and there was no "subscribe" button, so I had to assign it to you. I was assuming you would either try to fix it or assign somebody else...
