### ISSUE TITLE
Cannot compile OpenCV 4.5.0 on Alpine

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46848]
|  |  |
| --- | --- |
| Bugzilla Link | [47504](https://llvm.org/bz47504) |
| Version | 10.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic,@zygoloid |

## Extended Description 
Hello,

I am trying to compile opencv 4.5.0 on Alpine 3.12, which ships with clang 10.0.0 within a docker container, and I get the following errors:

***************************************************************************
Stack dump:
0.      Program arguments: /usr/bin/clang++ -DCVAPI_EXPORTS -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_M                                                                                                ACROS -D__STDC_LIMIT_MACROS -DCV_CPU_COMPILE_AVX2=1 -DCV_CPU_COMPILE_AVX512_COMMON=1 -DCV_CPU_COMPILE_AVX512_SKX=1 -DCV_CPU_COMPILE_AVX=1 -DC                                                                                                V_CPU_COMPILE_AVX_512F=1 -DCV_CPU_COMPILE_FMA3=1 -DCV_CPU_COMPILE_FP16=1 -DCV_CPU_COMPILE_POPCNT=1 -DCV_CPU_COMPILE_SSE4_1=1 -DCV_CPU_COMPILE                                                                                                _SSE4_2=1 -DCV_CPU_COMPILE_SSSE3=1 -DCV_CPU_DISPATCH_MODE=AVX512_SKX -I/tmp/opencv-4.4.0/build -I/tmp/opencv-4.4.0/modules/imgproc/include -I                                                                                                /tmp/opencv-4.4.0/build/modules/imgproc -I/tmp/opencv-4.4.0/modules/core/include -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtu                                                                                                al-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototyp                                                                                                es -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virt                                                                                                ual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-deprecated-enum-enum-conversion -Wno-deprecated-anon-enum-enum-conversion -fdiagno                                                                                                stics-show-option -Wno-long-long -pthread -Qunused-arguments -ffunction-sections -fdata-sections -msse -msse2 -msse3 -fvisibility=hidden -fvi                                                                                                sibility-inlines-hidden -O3 -DNDEBUG -DNDEBUG -fPIC -std=c++11 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mf16c -mfma -mavx -mavx2 -mavx512f -mavx51                                                                                                2f -mavx512cd -mavx512f -mavx512cd -mavx512vl -mavx512bw -mavx512dq -o CMakeFiles/opencv_imgproc.dir/sumpixels.avx512_skx.cpp.o -c /tmp/openc                                                                                                v-4.4.0/build/modules/imgproc/sumpixels.avx512_skx.cpp
1.      <eof> parser at end of file
2.      Per-module optimization passes
3.      Running pass 'CallGraph Pass Manager' on module '/tmp/opencv-4.4.0/build/modules/imgproc/sumpixels.avx512_skx.cpp'.
4.      Running pass 'Combine redundant instructions' on function '@_ZN2cv3hal14opt_AVX512_SKX12_GLOBAL__N_118IntegralCalculatorILm2EE16align                                                                                                ed_integralERPKhRPdS9_S9_S9_RDv8_xSB_i'
clang-10: error: clang frontend command failed due to signal (use -v to see invocation)
Alpine clang version 10.0.0 (https://gitlab.alpinelinux.org/alpine/aports.git 7445adce501f8473efdb93b17b5eaf2f1445ed4c)
Target: x86_64-alpine-linux-musl
Thread model: posix
InstalledDir: /usr/bin
clang-10: note: diagnostic msg: PLEASE submit a bug report to  and include the crash backtrace, preprocessed source, and associated run scrip                                                                                                t.
clang-10: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-10: note: diagnostic msg: /tmp/sumpixels-b9f906.cpp
clang-10: note: diagnostic msg: /tmp/sumpixels-b9f906.sh
clang-10: note: diagnostic msg:

********************
make[2]: *** [modules/imgproc/CMakeFiles/opencv_imgproc.dir/build.make:1251: modules/imgproc/CMakeFiles/opencv_imgproc.dir/sumpixels.avx512_s                                                                                                kx.cpp.o] Error 254
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1539: modules/imgproc/CMakeFiles/opencv_imgproc.dir/all] Error 2
make: *** [Makefile:183: all] Error 2
************************************************************************

Though it requests me to attach some file,but I can't get them since this is within a docker container, and it didn't complete its building.

Kind regards

**Comment by Endilll** [comment]
Author has never got back to us with preprocessed source.
Unfortunately, we can't do much without it.
Feel free to reopen if you have additional information.
