### ISSUE TITLE
Patch to solve a false positive issue for performance-unnecessary-value-param

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46844]
|  |  |
| --- | --- |
| Bugzilla Link | [47500](https://llvm.org/bz47500) |
| Version | unspecified |
| OS | All |
| Attachments | [Patch to solve the bug](https://user-images.githubusercontent.com/60944935/143761191-87ed3593-4528-4c1b-aad8-ab9bac88b58f.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Hello,

A few months ago a bug (#44598 ) was filed for a false positive in performance-unnecessary-value-param. This was in the case of template functions, where the argument was an expensive to copy type argument and the check would convert the argument to a const T&, even if it was being moved in the function body.

For example, this sort of code - 

#include <string>
template<class T>
static T* Create(std::string s) {
  return new T(std::move(s));
}

Leads to the check converting the argument to a const std::string&, even when it is being moved in the body. We saw the same behavior in my company codebase, where there were many false positives being reported.

I wrote some code to fix this issue. We ran the modified check on tens of thousands of files to see those false positives not being reported any more. The modifications to the checker are - 

1. For an expensive to copy type, before checking it is const qualified, check to see if it is being moved in the function body.

2. The argument and the AST context are passed on to a helper function. The function uses a matcher to check whether the argument is part of a std::move() call in the function body.

3. If true then ignore.

I am submitting the patch, along with new regression tests to verify that the check is ok if it sees an expensive to copy argument being moved, and does not recommend to change it to const T&. I have most recently applied the patch to LLVM master yesterday (09/10/2020), with no issues in build and all tests passing (using make -j10 check-clang-tools).

I'd like to submit this patch for review, and the possibility that it is merged in to clang-tidy to solve this issue.

Thank You,
Sukraat Ahluwalia.

**Comment by carlosgalvezp** [comment]
Issue no longer reproducible on trunk.
