### ISSUE TITLE
vector (iterator,iterator) constructor doesn't deduce second arg

### ISSUE THREAD

**Issue by kepler-5** [llvm/llvm-project#46841]
|  |  |
| --- | --- |
| Bugzilla Link | [47497](https://llvm.org/bz47497) |
| Version | unspecified |
| OS | All |
| CC | @kamleshbhalui,@mclow |

## Extended Description 
The following code is rejected by libc++ because the second iterator argument to `vector(iterator, iterator)` is not deduced (https://godbolt.org/z/q8f9Y7):

```
#include <iterator>
#include <iostream>
#include <vector>

int main() {
    std::vector<int> v({}, std::istream_iterator<int>{});
}
```

The following code, however, is accepted (https://godbolt.org/z/nM4Yh4):

```
#include <iterator>
#include <iostream>
#include <vector>

int main() {
    std::vector<int> v;
    v.assign({}, std::istream_iterator<int>{});
}
```

I believe this to be a conformance bug.

I stumbled on this in my own code when I noticed that a typo in the following code was being accepted:

    std::vector<int> v(other.cbegin(), other.end()); // note .end(), not .cend()

Since the second argument is not deduced, and the first argument is a const iterator, the second argument is implicitly converted to a const iterator. This is a symptom of the same issue, though I think this particular case could arguably be considered a conforming extension.

**Comment by ldionne** [comment]
There was a review open here to fix this: https://reviews.llvm.org/D88727

However, this seems to have been fixed somewhere between Clang 15 and Clang 16: https://godbolt.org/z/5EWWconno. I'll make sure we have tests for this and I'll close.
