### ISSUE TITLE
evaluation of constraints for std::ranges::views::drop() fails unnecessarily

### ISSUE THREAD

**Issue by 47089556-bf4e-479e-814d-280f07395991** [llvm/llvm-project#46853]
|  |  |
| --- | --- |
| Bugzilla Link | [47509](https://llvm.org/bz47509) |
| Version | trunk |
| OS | Linux |
| CC | @JohelEGP,@mmatrosov,@Craffael,@zygoloid,@viccie30,@jwakely |

## Extended Description 
The test program

==== begin test program ====

```c++
#include <vector>
#include <ranges>

void f(std::vector<int> vec) {
    for (auto& e : vec | std::ranges::views::drop(1)) {
    }
}
```
==== end test program ====

Does not compile on clang, either with libc++ or libstdc++, failing on some enormously complicated constraints. gcc accepts it.

**Comment by ldionne** [comment]
This doesn't happen anymore, see https://godbolt.org/z/5fhnM3YTo.

Also, on libc++, we haven't implemented `views::drop` yet (I have a patch locally and I need to finish it up) so this fails as expected. But the Clang bug seems to be gone.

**Comment by avikivity** [comment]
It does not compile with clang trunk: https://godbolt.org/z/Prn9Kze64

**Comment by ldionne** [comment]
Oh yes, you are right, sorry about that.

https://godbolt.org/z/hsvoWM3je shows:

Clang trunk / libstdc++: fails
GCC trunk / libstdc++: works
Clang trunk / libc++: fails because libc++ doesn't implement it yet

**Comment by jwakely** [comment]
> And this one and that are both dups of Bug 44833

Which is now #44178

**Comment by Quuxplusone** [comment]
Duplicate of #44178.
