### ISSUE TITLE
clang-format incorrectly breaks the line for constexpr lambda call initializing a variable

### ISSUE THREAD

**Issue by gumb0** [llvm/llvm-project#46889]
|  |  |
| --- | --- |
| Bugzilla Link | [47545](https://llvm.org/bz47545) |
| Version | 10.0 |
| OS | Linux |

## Extended Description 
$ clang-format --version
Ubuntu clang-format version 10.0.1-++20200708123514+ef32c611aa2-1~exp1~20200707224111.189 

The code that initializes a variable using curly braces and a call to inline _constexpr_ lambda is formatted incorrectly:

$ echo "int i{[]() constexpr noexcept { std::cout << "hello"; return 1; }()};" | clang-format
int i{[]() constexpr noexcept {std::cout << hello;
return 1;
}
()
}
;

Removing constexpr specifier results in a valid-looking format: 
$ echo "int i{[]() noexcept { std::cout << "hello"; return 1; }()};" | clang-format
int i{[]() noexcept {
  std::cout << hello;
  return 1;
}()};

Workaround: adding more parentheses around lambda definition also helps:

$ echo "int i{([]() constexpr noexcept { std::cout << "hello"; return 1; })()};" | clang-format
int i{([]() constexpr noexcept {
  std::cout << hello;
  return 1;
})()};

**Comment by rymiel** [comment]
Fixed by d2eda49202386b222cec763aad9aaecd463ce044
