### ISSUE TITLE
[AArch64] Crash bitcasting from bfloat to half

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#46895]
|  |  |
| --- | --- |
| Bugzilla Link | [47551](https://llvm.org/bz47551) |
| Version | trunk |
| OS | Windows NT |
| CC | @Arnaud-de-Grandmaison-ARM,@DMG862,@fpetrogalli,@smithp35 |

## Extended Description 
Testcase (crashes with "llc"):

target triple = "aarch64"
define half @&#8203;a(bfloat %x) {
entry:
  %0 = bitcast bfloat %x to half
  ret half %0
}

**Comment by xgupta** [comment]
It seems to fixed on main - https://godbolt.org/z/hGnPjYP13.
