### ISSUE TITLE
Actual argument 'transfer(msg,dat)' associated with dummy argument 'array=' is not a variable or typed expression

### ISSUE THREAD

**Issue by rikigigi** [llvm/llvm-project#46892]
|  |  |
| --- | --- |
| Bugzilla Link | [47548](https://llvm.org/bz47548) |
| Version | trunk |
| OS | Linux |
| CC | @jeanPerier,@kiranktp,@rikigigi,@sscalpone,@tskeith |

## Extended Description 
this compiles under gfortran and ifort, but not flang

[rbertoss@mugon bug_report]$ cat bug.f90
MODULE test
    IMPLICIT NONE
    INTERFACE
       FUNCTION fletcher32( dat, dat_size ) BIND(C,name="fletcher32") RESULT(t)
          USE ISO_C_BINDING
          integer(kind=c_int16_t) :: dat(*)
          integer(kind=c_int32_t) :: dat_size
          integer(kind=c_int32_t) :: t
       END FUNCTION fletcher32
    END INTERFACE
CONTAINS
      SUBROUTINE fletcher32_i1(msg, cksum) !!this compiles
         IMPLICIT NONE
         INTEGER, INTENT(IN) :: msg
         INTEGER, INTENT(OUT) :: cksum
         INTEGER(2) :: dat(1)

         cksum = fletcher32(transfer(msg,dat),size(transfer(msg,dat)))

      END SUBROUTINE fletcher32_i1
      SUBROUTINE fletcher32_iv(msg, cksum) !! this does not
         IMPLICIT NONE
         INTEGER, INTENT(IN) :: msg(:)  !!!!<<<==== the only difference wrt previous subroutine
         INTEGER, INTENT(OUT) :: cksum
         INTEGER(2) :: dat(1)

         cksum = fletcher32(transfer(msg,dat),size(transfer(msg,dat)))

      END SUBROUTINE fletcher32_iv

END MODULE
[rbertoss@mugon bug_report]$ /scratch/rbertoss/llvm/llvm-project/OBJ_ROOT_2/bin/flang bug.f90 -c
bug.f90:27:18: error: Actual argument 'transfer(msg,dat)' associated with dummy argument 'dat=' is not a variable or typed expression
           cksum = fletcher32(transfer(msg,dat),size(transfer(msg,dat)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bug.f90:27:47: error: Actual argument 'transfer(msg,dat)' associated with dummy argument 'array=' is not a variable or typed expression
           cksum = fletcher32(transfer(msg,dat),size(transfer(msg,dat)))
                                                ^^^^^^^^^^^^^^^^^^^^^^^
/scratch/rbertoss/llvm/llvm-project/OBJ_ROOT_2/bin/f18: semantic errors in bug.f90

**Comment by ekieri** [comment]
This one appears to have been fixed, I cannot reproduce it with 0f304ef01702 from today (Ubuntu 21.10, x86, clang 13). Is anybody aware of who fixed it and when?

**Comment by ekieri** [comment]
Closing, as it appears to have been fixed. Please do not hesitate to reopen if the problem persists for you.
