### ISSUE TITLE
Crash on compiling invalid requires expression

### ISSUE THREAD

**Issue by 71aff78a-b839-440a-be17-de1914c304ce** [llvm/llvm-project#46926]
|  |  |
| --- | --- |
| Bugzilla Link | [47582](https://llvm.org/bz47582) |
| Version | trunk |
| OS | MacOS X |
| Attachments | [Files requested by the compiler in the crash message.](https://user-images.githubusercontent.com/93435826/143761227-5ed3f31f-0e64-43eb-b6e4-8b4b69846b27.gz) |
| CC | @darius98,@zygoloid |

## Extended Description 

While writing an experimental implementation of std::is_polymorphic using a requires expression, I made a small mistake in the program. I was expecting a compile error, but Clang crashed instead (with an assertion failure):

template<class T>
inline constexpr bool is_polymorphic = requires {
  typename dynamic_cast<const volatile void*>(declval<T*>());
};

The expected output is a compile error (I strongly believe), the code is an invalid usage of the requires { typename ... } clause.

I attached a bundle with all the files required by the crash. Since it was fully reproducible, I minimized the example as much as I could. "clang-crash.cpp" is the original source code, "cli-output.txt" is the console output for running the command, and the other attachments are files requested in the output of the compiler.

**Comment by royjacobson** [comment]
Doesn't crash in assertions trunk anymore.
