### ISSUE TITLE
Crash running clang-tidy (bugprone-redundant-branch-condition)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46940]
|  |  |
| --- | --- |
| Bugzilla Link | [47596](https://llvm.org/bz47596) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Source code triggering check](https://user-images.githubusercontent.com/60944935/143761234-f2b1e1a9-6ef8-4e86-94a3-f929778ba6b0.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @EugeneZelenko |

## Extended Description 
Hi. I am hitting a crash using clang-tidy from today (21/9/2020). The backtrace follows. I will try and get a code-snippet that reproduces the crash.
---
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /usr/local/llvm-latest/bin/clang-tidy arch2_directoryscanner.cpp -header-filter=.* -warnings-as-errors= -checks=*,-abseil-no-internal-dependencies,-altera-struct-pack-align,-bugprone-narrowing-conversions,-cathexis-refactor-*,-clang-diagnostic-unknown-pragmas,-cppcoreguidelines-init-variables,-cppcoreguidelines-narrowing-conversions,-cppcoreguidelines-owning-memory,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,-fuchsia-*,-google-build-using-namespace,-google-readability-namespace-comments,-google-readability-todo,-google-runtime-int,-google-runtime-references,-hicpp-named-parameter,-hicpp-no-array-decay,-hicpp-signed-bitwise,-llvm-header-guard,-llvm-include-order,-llvm-namespace-comment,-llvmlibc-callee-namespace,-llvmlibc-implementation-in-namespace,-llvmlibc-restrict-system-libc-headers,-misc-misplaced-widening-cast,-misc-non-private-member-variables-in-classes,-misc-unused-parameters,-modernize-use-trailing-return-type,-readability-isolate-declaration,-readability-magic-numbers,-readability-misleading-indentation,-readability-named-parameter,-readability-redundant-access-specifiers,-bugprone-signed-char-misuse,-bugprone-suspicious-include,-bugprone-too-small-loop-variable,-cathexis-quality-*,-cert-dcl21-cpp,-cert-err58-cpp,-cert-oop57-cpp,-clang-analyzer-optin.performance.Padding,-cppcoreguidelines-avoid-non-const-global-variabnles,-cppcoreguidelines-macro-usage,-cppcoreguidelines-non-private-member-variables-in-classes,-cppcoreguidelines-pro-type-const-cast,-cppcoreguidelines-pro-type-reinterpret-cast,-cppcoreguidelines-pro-type-vararg,-misc-no-recursion,-modernize-avoid-c-arrays,-readability-function-size,-cert-dcl37-c,-cert-dcl51-cpp,-cert-str34-c,-cppcoreguidelines-avoid-c-arrays,-cppcoreguidelines-avoid-magic-numbers,-google-readability-function-size,-hicpp-avoid-c-arrays,-hicpp-avoid-goto,-hicpp-deprecated-headers,-hicpp-explicit-conversions,-hicpp-function-size,-hicpp-invalid-access-moved,-hicpp-member-init,-hicpp-move-const-arg,-hicpp-no-malloc,-hicpp-noexcept-move,-hicpp-special-member-functions,-hicpp-uppercase-literal-suffix,-hicpp-use-auto,-hicpp-use-equals-default,-hicpp-use-override,-hicpp-vararg,-llvm-qualified-auto,-readability-use-anyofallof,-performance-move-const-arg, -- -DCAPTURESTATION -DHAS_FG -DPRODUCT=everything -DPLATFORM=Ubuntu_18_04 -DPLATFORM_Ubuntu_18_04=1 -DARCH=x86_64 -DARCH_x86_64=1 -DWORDSIZE64 -DBUILD_VERSION=trunk -DCLANG_TIDY=1 -D_FILE_OFFSET_BITS=64 -DBUILD_ARCH2LIB -isystem ../../../../../pkg/gsl/include -isystem ../../../../../pkg/absl/lib -isystem /usr/include/libxml2 -isystem ../../../../../pkg/libopenssl/include -std=c++14 -fPIC -I../../../../../vms/libs/archive/v100/lib -I../../../../../vms/libs/archive/itemcontainer/lib -I../../../../../vms/libs/archive/v100/definitions -I../../../../../vms/servers/database/timeline/v100/interface -I../../../../../cdl/libs/threads/v200/lib -I../../../../../cdl/libs/kernel/kern -I../../../../../cdl/libs/cat/lib -I../../../../../cdl/libs/imgproc/linearalgebra -I../../../../../cdl/libs/cryptography/lib -I../../../../../cdl/libs/utils -I../../../../../cdl/libs/textmarkup/xml -I../../../../../cdl/libs/textmarkup/json/v200 -I../../../../../cdl/libs/textmarkup/html/v100 -I../../../../../cdl/libs/textmarkup/html/v200 -I../../../../../cdl/libs/core -I../../../../../pkg/absl/build -Ibuild_x86_64_debug_tidy 
1.	<eof> parser at end of file
 #&#8203;0 0x000056202f88688c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/local/llvm-latest/bin/clang-tidy+0x273c88c)
 #&#8203;1 0x000056202f884824 llvm::sys::RunSignalHandlers() (/usr/local/llvm-latest/bin/clang-tidy+0x273a824)
 #&#8203;2 0x000056202f884973 SignalHandler(int) (/usr/local/llvm-latest/bin/clang-tidy+0x273a973)
 #&#8203;3 0x00007f83b25a48a0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x128a0)
 #&#8203;4 0x000056202f517e95 clang::Stmt::getEndLoc() const (/usr/local/llvm-latest/bin/clang-tidy+0x23cde95)
 #&#8203;5 0x000056202d8db2ba clang::tidy::bugprone::RedundantBranchConditionCheck::check(clang::ast_matchers::MatchFinder::MatchResult const&) (/usr/local/llvm-latest/bin/clang-tidy+0x7912ba)
 #&#8203;6 0x000056202f213338 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::MatchVisitor::visitMatch(clang::ast_matchers::BoundNodes const&) (/usr/local/llvm-latest/bin/clang-tidy+0x20c9338)
 #&#8203;7 0x000056202f252d08 clang::ast_matchers::internal::BoundNodesTreeBuilder::visitMatches(clang::ast_matchers::internal::BoundNodesTreeBuilder::Visitor*) (/usr/local/llvm-latest/bin/clang-tidy+0x2108d08)
 #&#8203;8 0x000056202f21597e clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::matchWithFilter(clang::DynTypedNode const&) (/usr/local/llvm-latest/bin/clang-tidy+0x20cb97e)
 #&#8203;9 0x000056202f23967c clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) (.part.5452) (/usr/local/llvm-latest/bin/clang-tidy+0x20ef67c)
#&#8203;10 0x000056202f236d15 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::dataTraverseNode(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) (/usr/local/llvm-latest/bin/clang-tidy+0x20ecd15)
#&#8203;11 0x000056202f2395a9 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) (/usr/local/llvm-latest/bin/clang-tidy+0x20ef5a9)
#&#8203;12 0x000056202f241454 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) (.part.5452.constprop.5585) (/usr/local/llvm-latest/bin/clang-tidy+0x20f7454)
#&#8203;13 0x000056202f24e24d clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseFunctionHelper(clang::FunctionDecl*) (/usr/local/llvm-latest/bin/clang-tidy+0x210424d)
#&#8203;14 0x000056202f23563e clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) (.part.5449) (/usr/local/llvm-latest/bin/clang-tidy+0x20eb63e)
#&#8203;15 0x000056202f236c54 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDeclContextHelper(clang::DeclContext*) (.part.5450) (/usr/local/llvm-latest/bin/clang-tidy+0x20ecc54)
#&#8203;16 0x000056202f2352fa clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) (.part.5449) (/usr/local/llvm-latest/bin/clang-tidy+0x20eb2fa)
#&#8203;17 0x000056202f24d3db clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseClassTemplateDecl(clang::ClassTemplateDecl*) (/usr/local/llvm-latest/bin/clang-tidy+0x21033db)
#&#8203;18 0x000056202f234855 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) (.part.5449) (/usr/local/llvm-latest/bin/clang-tidy+0x20ea855)
#&#8203;19 0x000056202f236c54 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDeclContextHelper(clang::DeclContext*) (.part.5450) (/usr/local/llvm-latest/bin/clang-tidy+0x20ecc54)
#&#8203;20 0x000056202f234edf clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) (.part.5449) (/usr/local/llvm-latest/bin/clang-tidy+0x20eaedf)
#&#8203;21 0x000056202f2365e8 clang::ast_matchers::MatchFinder::matchAST(clang::ASTContext&) (/usr/local/llvm-latest/bin/clang-tidy+0x20ec5e8)
#&#8203;22 0x000056202e67a5a8 clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) (/usr/local/llvm-latest/bin/clang-tidy+0x15305a8)
#&#8203;23 0x000056202e7ff359 clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/llvm-latest/bin/clang-tidy+0x16b5359)
#&#8203;24 0x000056202e659c99 clang::FrontendAction::Execute() (/usr/local/llvm-latest/bin/clang-tidy+0x150fc99)
#&#8203;25 0x000056202e6109fb clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/llvm-latest/bin/clang-tidy+0x14c69fb)
#&#8203;26 0x000056202dfe4e4f clang::tooling::FrontendActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) (/usr/local/llvm-latest/bin/clang-tidy+0xe9ae4f)
#&#8203;27 0x000056202df92abe clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, llvm::StringRef)::ActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) (/usr/local/llvm-latest/bin/clang-tidy+0xe48abe)
#&#8203;28 0x000056202dfdbb1c clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::shared_ptr<clang::CompilerInvocation>, std::shared_ptr<clang::PCHContainerOperations>) (/usr/local/llvm-latest/bin/clang-tidy+0xe91b1c)
#&#8203;29 0x000056202dfe1b01 clang::tooling::ToolInvocation::run() (/usr/local/llvm-latest/bin/clang-tidy+0xe97b01)
#&#8203;30 0x000056202dfe3ea2 clang::tooling::ClangTool::run(clang::tooling::ToolAction*) (/usr/local/llvm-latest/bin/clang-tidy+0xe99ea2)
#&#8203;31 0x000056202df96684 clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, llvm::StringRef) (/usr/local/llvm-latest/bin/clang-tidy+0xe4c684)
#&#8203;32 0x000056202d81e759 clang::tidy::clangTidyMain(int, char const**) (/usr/local/llvm-latest/bin/clang-tidy+0x6d4759)
#&#8203;33 0x00007f83b143cb97 __libc_start_main /build/glibc-2ORdQG/glibc-2.27/csu/../csu/libc-start.c:344:0
#&#8203;34 0x000056202d81ac7a _start (/usr/local/llvm-latest/bin/clang-tidy+0x6d0c7a)
Segmentation fault (core dumped)

**Comment by carlosgalvezp** [comment]
Problem no longer reproducible on trunk.
