### ISSUE TITLE
Bogus fuchsia-trailing-return diagnostic

### ISSUE THREAD

**Issue by igor-akhmetov** [llvm/llvm-project#46958]
|  |  |
| --- | --- |
| Bugzilla Link | [47614](https://llvm.org/bz47614) |
| Version | unspecified |
| OS | Windows NT |
| CC | @EugeneZelenko,@fabianwolff,@juliehockett |

## Extended Description 
On the following snippet clang-tidy erroneously outputs the fuchsia-trailing-return diagnostic (https://gcc.godbolt.org/z/hMEhqj):

template <typename T>
struct RegSomeClass
{
    RegSomeClass(const T& );
};

void foo()
{
   constexpr auto val = 10u;
   const auto someClass = RegSomeClass{val};
}

**Comment by carlosgalvezp** [comment]
Godbolt link no longer reproduces the issue.
