### ISSUE TITLE
Constexpr destructor support causes crash from unhandled cleanup

### ISSUE THREAD

**Issue by smeenai** [llvm/llvm-project#46964]
|  |  |
| --- | --- |
| Bugzilla Link | [47620](https://llvm.org/bz47620) |
| Version | trunk |
| OS | All |
| CC | @bcardosolopes,@DougGregor,@zygoloid |

## Extended Description 
$ cat reduced.cpp
template <class _Tp, _Tp __v> struct integral_constant {
  static constexpr const _Tp value = __v;
};

using true_type = integral_constant<bool, true>;
using false_type = integral_constant<bool, false>;

struct is_constexpr_default_constructible_ {
  template <typename T, int = (void(T()), 0)> static true_type sfinae(T *);
  static false_type sfinae(void *);
  template <typename T>
  static constexpr bool apply =
      decltype(sfinae(static_cast<T *>(nullptr)))::value;
};

template <typename T>
constexpr bool is_constexpr_default_constructible_v =
    is_constexpr_default_constructible_::apply<T>;

struct NonTrivialDtor {
  ~NonTrivialDtor() {}
};

static_assert(!is_constexpr_default_constructible_v<NonTrivialDtor>, "");

$ clang -fsyntax-only reduced.cpp
Unhandled cleanup; missing full expression marker?
UNREACHABLE executed at /home/smeenai/llvm-project/clang/lib/AST/ExprConstant.cpp:12730!

Bisects to 457226e02a6e (https://github.com/llvm/llvm-project/commit/457226e02a6e). If you build the compiler with assertions disabled it doesn't crash (even though the crash itself doesn't look like an assertion failure).

**Comment by Endilll** [comment]
Appears to be fixed on post-17 trunk: https://godbolt.org/z/4dPM9K4P7
