### ISSUE TITLE
-Wdangling-gsl only warns on initialization and not on assignment

### ISSUE THREAD

**Issue by Weverything** [llvm/llvm-project#46984]
|  |  |
| --- | --- |
| Bugzilla Link | [47640](https://llvm.org/bz47640) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie,@gribozavr,@mgehre,@zygoloid,@Xazax-hun |

## Extended Description 
-Wdangling-gsl is a warning that catches dangling pointers.  This warning catches a lot of lifetime bugs, but it only does so during initialization.  Similar code that causes a dangling pointer during assignments does not get a warning.

#include <string>
#include <string_view>
#include <memory>

std::string get_string();
std::unique_ptr<int> get_int();

int main() {
  std::string_view sv = get_string();  // Warning on initialization
  sv = get_string();                   // No warning on assignment
  
  int *p = get_int().get();  // Warning on initialization
  p = get_int().get();       // No warning on assignment
}

**Comment by usx95** [comment]
Duplicate https://github.com/llvm/llvm-project/issues/63310 is fixed now.
