### ISSUE TITLE
assert in clang-12, Lexer.cpp line 88

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46996]
|  |  |
| --- | --- |
| Bugzilla Link | [47652](https://llvm.org/bz47652) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
clang-12: /home/jon/llvm-project/clang/lib/Lex/Lexer.cpp:88: void clang::Lexer::InitLexer(const char *, const char *, const char *): Assertion `BufEnd[0] == 0 && "We assume that the input buffer has a null character at the end" " to simplify lexing!"' failed.

**Comment by cor3ntin** [comment]
This needs a reproduction
