### ISSUE TITLE
【Feature Request】Please consider to provide essential head files for Windows

### ISSUE THREAD

**Issue by byyxx128** [llvm/llvm-project#47]
LLVM/Clang is nice on multiple platforms. However, specifically on Windows, users have to install GCC together as LLVM doesn't provide some essential components e.g. head files. But I really don't want to install a copy of GCC. Why doesn't LLVM provide those components?

**Comment by jyknight** [comment]
It's not actually GCC that that you need. But, yes, you do need to provide platform headers from somewhere -- either from MSVC or from MinGW.

Perhaps https://github.com/mstorsjo/llvm-mingw would be helpful to you?

I don't think there's anything actionable in this bug, closing.

**Comment by byyxx128** [comment]
It is actually not bug, so I said "feature request". (I don't think I'm asking a question)

[This](https://github.com/mstorsjo/llvm-mingw) could be an alternative, however, it is not maintained for a long time, and it is not an official solution as well.

As you mentioned, I definitely need headers from somewhere. That is reason why I'm asking (I'm asking for a request rather than a question, so what I need is a solution not an answer). Hopefully LLVM can provide release with headers as I really don't want install any other components besides LLVM.

**Comment by mstorsjo** [comment]
> [This](https://github.com/mstorsjo/llvm-mingw) could be an alternative, however, it is not maintained for a long time, and it is not an official solution as well.

Just curious - which part of it do you consider not being maintained for a long time, with the latest commit 3 days ago, the latest release with the LLVM 9.0.0 stable release a couple months ago, and using a version of mingw-w64 that is a couple months old?
