### ISSUE TITLE
readability-implicit-bool-conversion false positive for explicit cast with list initialization

### ISSUE THREAD

**Issue by chfast** [llvm/llvm-project#47000]
|  |  |
| --- | --- |
| Bugzilla Link | [47656](https://llvm.org/bz47656) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
For the code converting bool to int with int{}:

int to_int(bool x) { return int{x}; }

clang-tidy --checks=readability-implicit-bool-conversion

produces the warning:

warning: implicit conversion bool -> 'int' [readability-implicit-bool-conversion]

int to_int(bool x) { return int{x}; }

                                ^

                                static_cast<int>( )

And the fixed code looks like:

int to_int(bool x) { return int{static_cast<int>(x)}; }

In my option the `int{x}` should be considered explicit conversion.

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D147551
