### ISSUE TITLE
Nightly test should have some kind of "rotation" mechanism

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#4700]
|  |  |
| --- | --- |
| Bugzilla Link | [4328](https://llvm.org/bz4328) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
It would be nice if NewNightlyTest.pl had some kind of option for "rotating" build directories, in conjunction with -noremove. Keeping the previous N nightly test build directories would make it much easier to quickly analyze failures.

**Comment by EugeneZelenko** [comment]
@gwelymernans: Could you please elaborate on this functionality?

**Comment by gwelymernans** [comment]
@EugeneZelenko: I should have added a comment before simply closing this out. We now have buildbots that perform the majority of our testing (https://lab.llvm.org/buildbot/#/console). Also, `NewNightlyTest.pl` doesn't exist anymore. :-)

If there's still a need for this, please feel free to reopen it. It would be good to update this to meld with the buildbot system.
