### ISSUE TITLE
float128 argument not passed with va_arg

### ISSUE THREAD

**Issue by shibatch** [llvm/llvm-project#47009]
|  |  |
| --- | --- |
| Bugzilla Link | [47665](https://llvm.org/bz47665) |
| Version | 10.0 |
| OS | Linux |
| CC | @DougGregor,@efriedma-quic,@zygoloid |

## Extended Description 
The following testcase shows `0` if compiled with `-O1` option.
```cpp
#include <stdio.h>
#include <stdarg.h>

void func(int n, ...) {
  va_list ap;
  va_start(ap, n);
  __float128 q = va_arg(ap, __float128);
  va_end(ap);
  printf("%g\n", (double)q);
}

int main(void) {
  __float128 q = 0.1Q;
  func(0, q);
}
```
```
$ clang-10 -O1 vargf128.c
$ ./a.out
0
$ clang-10 -O0 vargf128.c
$ ./a.out
0.1
```

**Comment by mahtohappy** [comment]
https://godbolt.org/z/TEa1T3Ms5 Hi, I think this can be closed as the behavior is no longer observed.

**Comment by Endilll** [comment]
Appears to be fixed after Clang 17: https://godbolt.org/z/7dfEc3oGx
