### ISSUE TITLE
Transfer can be constant value, but not now

### ISSUE THREAD

**Issue by foxtran** [llvm/llvm-project#47010]
|  |  |
| --- | --- |
| Bugzilla Link | [47666](https://llvm.org/bz47666) |
| Version | trunk |
| OS | Linux |
| CC | @jeanPerier,@kiranktp,@sscalpone |

## Extended Description 
I have tried to compile the following code: 

real(8), parameter :: zero_int = transfer(0,0D0)
end

And I have got message:

:1:34: error: Must be a constant value
  real(8), parameter :: zero_int = transfer(0,0D0)
                                   ^^^^^^^^^^^^^^^

But in reality, it is a constant value. ifort and gcc can compile this code (See here: https://godbolt.org/z/r83ves)

Locally tested version is commit d2166076b882e38becf3657ea830ffd2b6a5695e of llvm-project.

**Comment by sscalpone** [comment]
Fixed with ae93d8ea426d23cdbcc8e49ab729f635a52c872a

**Comment by psteinfeld** [comment]
This test case works with the current compiler.
