### ISSUE TITLE
Overloading resolved to pointer argument instead of initializer_list

### ISSUE THREAD

**Issue by chfast** [llvm/llvm-project#47048]
|  |  |
| --- | --- |
| Bugzilla Link | [47704](https://llvm.org/bz47704) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@hubert-reinterpretcast,@zygoloid |

## Extended Description 
For the following C++11 code:
```cpp
#include <initializer_list>

struct V
{
    V(int) {}
};

inline int f(void*) { return 1; }

inline int f(std::initializer_list<V>) { return 2; }

int invoke_test() { return f({0}); }
```

The function f invocation `f({0})` is resolved to `f(void*)`.
GCC does the opposite.
I believe it should be initializer_list because `{}` is used.
We also get the -Wbraced-scalar-init warning.

warning: braces around scalar initializer [-Wbraced-scalar-init]

int invoke_test() { return f({0}); }

                             ^~~

https://godbolt.org/z/qj5voh

**Comment by cor3ntin** [comment]
As discussed offline, this looks like a GCC bug. cf Hubert's first comment. `f({{0}}` can be used to call the initializer constructor
