### ISSUE TITLE
Clang :: Sema/offsetof-64.c FAILs on 64-bit Sparc

### ISSUE THREAD

**Issue by rorth** [llvm/llvm-project#47054]
|  |  |
| --- | --- |
| Bugzilla Link | [47710](https://llvm.org/bz47710) |
| Version | trunk |
| OS | All |
| Attachments | [Reduced test case.](https://user-images.githubusercontent.com/3930951/143761258-98af87af-aa03-438f-8f44-63acb13cd77e.gz) |

## Extended Description 
The Clang :: Sema/offsetof-64.c test FAILs on 64-bit Sparc (seen on both
sparcv9-sun-solaris2.11 and sparc64-unknown-linux-gnu):

Assertion failed: (Size == 0 || EltInfo.Width <= (uint64_t)(-1) / Size) && "Overflow in array type bit size evaluation", file /vol/llvm/src/llvm-project/dist/clang/lib/AST/ASTContext.cpp, line 1914

However, the same problem can be seen in a much reduced testcase (attached).

Compile with

$ clang -m64 -O3 -o o64 o64.c o64d.c && ./o64
Assertion failed: Width <= (uint64_t)(-1) / Size, file o64.c, line 7, function main
Abort (core dumped)

The test works with gcc and clang-9, while clang-10 and 11 show the same error.

**Comment by brad0** [comment]
@rorth What is the status of this with Clang 14?

**Comment by rorth** [comment]
> @rorth What is the status of this with Clang 14?

The test `PASS`es with `clang-14.0.1`.
