### ISSUE TITLE
-include doesn't work with a file generated from `<()`

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#47067]
|  |  |
| --- | --- |
| Bugzilla Link | [47723](https://llvm.org/bz47723) |
| Version | unspecified |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
```
clang -include <(some_command)
```
This, with bash, should result in a GCC-like compiler including whatever text `some_command` generates before any of the source file is processed. In GCC, this works, but not in Clang. For example this code :
```cpp
void g()
{
    goto lbl;
lbl:;
}
```
Will compile, even if `-include <(echo '#pragma GCC poison goto')` is given as an option, whereas it will not compile on GCC. (Note: The pragma would work, it's just that Clang doesn't seem to include the file generated by `<()` properly).

**Comment by GabrielRavier** [comment]
Appears to be fixed on trunk.

**Comment by widberg** [comment]
It looks like this was fixed four months after the issue was opened by 245218bb355599771ba43a0fe1449d1670f2666c which was quickly followed up by 3ee43adfb20d5dc56b7043b314bd22f457c55483. Clang 12 was the first version to include these changes. My current output on trunk is

```console
$ echo "#pragma GCC poison goto" | ./bin/clang -c -include /dev/stdin test.cpp
test.cpp:3:6: error: attempt to use a poisoned identifier
            goto lbl;
            ^
1 error generated.
```
