### ISSUE TITLE
cppcoreguidelines-avoid-goto doesn't work on C code

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#47065]
|  |  |
| --- | --- |
| Bugzilla Link | [47721](https://llvm.org/bz47721) |
| Version | unspecified |
| OS | Linux |
| CC | @JonasToth,@EugeneZelenko |

## Extended Description 
void f()
{
    goto label;
label:;
}

If compiled as C++ and then checked with `--checks=cppcoreguidelines-avoid-goto`, it will flag this code. If compiled as C and then checked with the same flag, it will not. This is most likely due to the check in clang-tools-extra/clang-tidy/cppcoreguidelines/AvoidGotoCheck.h for C++ :

  bool isLanguageVersionSupported(const LangOptions &LangOpts) const override {
    return LangOpts.CPlusPlus;
  }

Is this too complicated to implement for C, or is this simply an oversight ? I would appreciate having such checks in C mode without having to pretend to clang-tidy all my code is C++.

See also proof of this on Godbolt here : https://godbolt.org/z/Y9co3h (-xc is to make it so that clang-tidy assumes the code is C)

**Comment by carlosgalvezp** [comment]
Check only works on C++ code by design since there are better replacements of `goto`. There are no such replacements in C so the check could throw too many false positives.
