### ISSUE TITLE
no_unique_address and has_unique_object_representations

### ISSUE THREAD

**Issue by 9fe30eb4-f3af-49a3-9b33-39ba537a5139** [llvm/llvm-project#47066]
|  |  |
| --- | --- |
| Bugzilla Link | [47722](https://llvm.org/bz47722) |
| Version | 10.0 |
| OS | Windows NT |
| CC | @dwblaikie,@kirshamir,@mpolacek,@zygoloid,@yuanfang-chen |

## Extended Description 
From StackOverflow (https://stackoverflow.com/q/64195712/2069064):

#include <type_traits>

struct Empty {};

struct A : public Empty {
    int x;
};

struct B {
    [[no_unique_address]] Empty e;
    int x;
};

static_assert (sizeof(A) == sizeof(int)); // ok
static_assert (sizeof(B) == sizeof(int)); // ok
static_assert(std::has_unique_object_representations_v<A>); // ok
static_assert(std::has_unique_object_representations_v<B>); // error

clang does not consider B to have unique object representations, but it should here.

Note that a similar bug was opened on gcc:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97285

**Comment by xgupta** [comment]
This is fixed on trunk - https://godbolt.org/z/KPv4e5KPr.
