### ISSUE TITLE
infinite recursion with opt -instcombine

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#47096]
|  |  |
| --- | --- |
| Bugzilla Link | [47752](https://llvm.org/bz47752) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#47144  |
| Attachments | [bbi-48251.ll reproducer](https://user-images.githubusercontent.com/55733087/143761274-5432df79-1f0c-4907-a905-943dfa27be5c.gz) |
| CC | @zmodem,@LebedevRI,@RKSimon,@rotateright,@tstellar |
| Fixed by commit(s) | fed0f890e5698a7a408acaf0aa23319e918f6a2a |

## Extended Description 

llvm commit: 1aa8e6a51a0eb

Reproduce with:
 opt -S -o - bbi-48251.ll -instcombine

Result:

PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ../../master/llvm/build-all/bin/opt -S -o - bbi-48251.ll -instcombine 
1.	Running pass 'Function Pass Manager' on module 'bbi-48251.ll'.
2.	Running pass 'Combine redundant instructions' on function '@g'
  #&#8203;0 0x00000000027d2723 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (../../master/llvm/build-all/bin/opt+0x27d2723)
  #&#8203;1 0x00000000027d03ee llvm::sys::RunSignalHandlers() (../../master/llvm/build-all/bin/opt+0x27d03ee)
  #&#8203;2 0x00000000027d2bdc SignalHandler(int) (../../master/llvm/build-all/bin/opt+0x27d2bdc)
  #&#8203;3 0x00007fadc69978a0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x128a0)
  #&#8203;4 0x00000000022e25f2 llvm::Negator::visitImpl(llvm::Value*, unsigned int) (../../master/llvm/build-all/bin/opt+0x22e25f2)
  #&#8203;5 0x00000000022e4323 llvm::Negator::negate(llvm::Value*, unsigned int) (../../master/llvm/build-all/bin/opt+0x22e4323)
  #&#8203;6 0x00000000022e34e1 llvm::Negator::visitImpl(llvm::Value*, unsigned int) (../../master/llvm/build-all/bin/opt+0x22e34e1)
  #&#8203;7 0x00000000022e4323 llvm::Negator::negate(llvm::Value*, unsigned int) (../../master/llvm/build-all/bin/opt+0x22e4323)

etc

This starts happening with commit 67266d879c7 from April 22:

    [InstCombine] Negator: shufflevector is negatible
    
    All these folds are correct as per alive-tv

**Comment by fhahn** [comment]
Sounds like this has been fixed. It doesn't reproduce on current `main`: https://llvm.godbolt.org/z/fnbTGchWM

Please re-open with additional info if it still reproduces on your end.
