### ISSUE TITLE
Failed Profile-i386 tests on new Windows 32bit MSVC buildbot

### ISSUE THREAD

**Issue by ChristianKuehnel** [llvm/llvm-project#47103]
|  |  |
| --- | --- |
| Bugzilla Link | [47759](https://llvm.org/bz47759) |
| Version | trunk |
| OS | Windows 2000 |
| CC | @zygoloid |

## Extended Description 
When setting up a new 32bit WIndows buildbot with MSVC, I noticed a few of the instrprof tests are failing. The buildbot is currently in staging as I want to resolve the failing tests before moving it to production.

http://lab.llvm.org:8014/#/builders/27

**Comment by Endilll** [comment]
@ChristianKuehnel Do you still experience this issue with a newer version?

**Comment by ChristianKuehnel** [comment]
I'm not working on LLVM any more, feel free to ignore that comment if
nobody else is complaining...
