### ISSUE TITLE
clang-format thinks `for (; i < argcnt; m1 = m1 >> 1);` is a template

### ISSUE THREAD

**Issue by jyn514** [llvm/llvm-project#47100]
|  |  |
| --- | --- |
| Bugzilla Link | [47756](https://llvm.org/bz47756) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
clang-format turns this code:

```
int f() {
    for (; i < argcnt; m1 = m1 >> 1);
}
```

into this:

```
int f() {
	for (; i<argcnt; m1 = m1> > 1)
		;
}
```

I think it thinks that `i` is a template being instantiated with `argcnt; m1 = m1`, but that doesn't look like any template syntax I've ever seen. This breaks the build, since `> >` is no longer a right-shift token:

```
tmp.c:919:66: error: expected expression
        for (i = 0, m1 = entry_ptr->input_mask; i<argcnt; i++, m1 = m1> > 1) {
                                                                        ^
```

**Comment by mkurdej** [comment]
Fixed in clang-format 11.
