### ISSUE TITLE
Inconsitency between variable decltype(auto) in variables and templates

### ISSUE THREAD

**Issue by ebdd6ebc-1612-4e9b-aee1-f7d2b6361d5f** [llvm/llvm-project#47136]
|  |  |
| --- | --- |
| Bugzilla Link | [47792](https://llvm.org/bz47792) |
| Version | trunk |
| OS | All |
| CC | @hubert-reinterpretcast,@zygoloid |

## Extended Description 
Consider the following program:

  #include <iostream>
  #include <type_traits>

  template<decltype(auto) N>
  void f()
  {
    std::cout << std::is_same_v<decltype(N), int> << std::endl;
  }

  int main()
  {
    const int i = 0;

    f<i>();

    decltype(auto) N = i;
    std::cout << std::is_same_v<decltype(N), const int> << std::endl;
  }

When compiling it with  -std=c++17 -pedantic-errors  and the running it the following is outputed:

  1
  1

This means that the two decltype(auto) deductions behaved differently since they deduced different types ( N = int and N = const int ). I expect them to behave the same way.

Note that gcc gives the expected result ( N = const int  for both deductions ).

Link to compiler explorer (clang to the left, gcc to the right):

  https://godbolt.org/z/Y5Yc7M

**Comment by mizvekov** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/27f9b0c619c6e1439532434b632ea4f9b98f9f97
