### ISSUE TITLE
CTR not correctly saved for inline assembly clobbering CTR

### ISSUE THREAD

**Issue by programmerjake** [llvm/llvm-project#47156]
|  |  |
| --- | --- |
| Bugzilla Link | [47812](https://llvm.org/bz47812) |
| Version | 11.0 |
| OS | Linux |
| CC | @nemanjai,@programmerjake |

## Extended Description 
The following IR is miscompiled:
https://gcc.godbolt.org/z/s5zcae

target triple = "powerpc64le-unknown-linux-gnu"

define void @&#8203;f(void()* %fn) {
  call void asm sideeffect "mtctr 31", "~{ctr}"()
  tail call void %fn()
  ret void
}

Generated Assembly (trimmed to just f's instructions, comments added):
f:
.Lfunc_gep0:
        addis 2, 12, .TOC.-.Lfunc_gep0@ha
        addi 2, 2, .TOC.-.Lfunc_gep0@l
        mflr 0
        std 0, 16(1)
        stdu 1, -32(1)
        std 2, 24(1)
        mtctr 3
        mr      12, 3
        mtctr   31 # note how ctr not restored before the call on next line
        bctrl
        ld 2, 24(1)
        addi 1, 1, 32
        ld 0, 16(1)
        mtlr 0
        blr

This causes f to call whatever address was in r31 instead of %fn despite the inline assembly including ctr in the clobber list.

**Comment by chenzheng1030** [comment]
Seems like the clobber `ctr` in the inline assembly can not be recognized as same hardware register with the one generated for the tail call:
```
  INLINEASM &"mtctr 31" [sideeffect] [attdialect], $0:[clobber], implicit-def early-clobber $ctr
  MTCTR8 renamable $x3, implicit-def $ctr8
  $x12 = OR8 $x3, killed $x3
  BCTRL8_LDinto_toc 24, $x1, <regmask $zero $cr2 $cr3 $cr4 $f14 $f15 $f16 $f17 $f18 $f19 $f20 $f21 $f22 $f23 $f24 $f25 $f26 $f27 $f28 $f29 $f30 $f31 $r14 $r15 $r16 $r17 $r18 $r19 $r20 $r21 $r22 $r23 $r24 and 62 more...>, implicit-def dead $lr8, implicit-def dead $x2, implicit $ctr8, implicit $rm, implicit $x12, implicit $x2, implicit-def $r1
```

```
SU(0):   INLINEASM &"mtctr 31" [sideeffect] [attdialect], $0:[clobber], implicit-def early-clobber $ctr
  # preds left       : 0
  # succs left       : 0
  # rdefs left       : 0
  Latency            : 1
  Depth              : 0
  Height             : 0
SU(1):   MTCTR8 renamable $x3, implicit-def $ctr8
  # preds left       : 0
  # succs left       : 1
  # rdefs left       : 0
  Latency            : 1
  Depth              : 0
  Height             : 1
  Successors:
    ExitSU: Ord  Latency=1 Artificial
```

After the scheduling:
```
  MTCTR8 renamable $x3, implicit-def $ctr8
  $x12 = OR8 killed $x3, $x3
  INLINEASM &"mtctr 31" [sideeffect] [attdialect], $0:[clobber], implicit-def early-clobber $ctr
  BCTRL8_LDinto_toc 24, $x1, <regmask $zero $cr2 $cr3 $cr4 $f14 $f15 $f16 $f17 $f18 $f19 $f20 $f21 $f22 $f23 $f24 $f25 $f26 $f27 $f28 $f29 $f30 $f31 $r14 $r15 $r16 $r17 $r18 $r19 $r20 $r21 $r22 $r23 $r24 and 62 more...>, implicit-def dead $lr8, implicit-def dead $x2, implicit $ctr8, implicit $rm, implicit killed $x12, implicit $x2, implicit-def $r1
```

If changing the clobber from `~{ctr}` to `~{ctr8}`, we can get expected instructions.

**Comment by bzEq** [comment]
We might need to view `~{ctr}` as `CTR` in 32-bit mode and as `CTR8` in 64-bit mode.

**Comment by bzEq** [comment]
The change in #76926 is no harm to me. However, a more proper solution to me might be viewing `~{ctr}` as CTR in 32-bit mode and as `CTR8` in 64-bit mode.
