### ISSUE TITLE
flang preprocessor fails to parse simple macro alias

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#47162]
|  |  |
| --- | --- |
| Bugzilla Link | [47818](https://llvm.org/bz47818) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @jeanPerier,@kiranktp,@sscalpone |

## Extended Description 
Given the following code:

#define TO_VERSION2(MAJOR, MINOR) ((MAJOR) * 10000 + (MINOR) * 100)
#define TO_VERSION TO_VERSION2

#if TO_VERSION2(1, 11) <= TO_VERSION2(0, 0)
#endif

#if TO_VERSION(1, 11) <= TO_VERSION(0, 0)
#endif

I get with the latest trunk (llvmorg-12-init-8404-gacd0dd3a62d):

$ flang -E prog.F 
/data/tiziano/flang/install/bin/f18: could not scan prog.F
prog.F:8:15: error: excess characters after expression
  #if TO_VERSION(1, 11) <= TO_VERSION(0, 0)
                ^^^

**Comment by klausler** [comment]
https://reviews.llvm.org/D151154
