### ISSUE TITLE
gtest header files shall not be tested by clang-tidy

### ISSUE THREAD

**Issue by wp-seth** [llvm/llvm-project#47167]
|  |  |
| --- | --- |
| Bugzilla Link | [47823](https://llvm.org/bz47823) |
| Version | unspecified |
| OS | Linux |
| CC | @EugeneZelenko |

## Extended Description 
if i include gtest via
```
  #include <gtest/gtest.h>
```
then clang-tidy will check gtest.h.

when i try to avoid this by hiding gtest.h to clang, then clang croaks
```
.../ctor_test.cc:7:10: error: 'gtest/gtest.h' file not found [clang-diagnostic-error]
#include <gtest/gtest.h>
         ^
```
of course,
```
  // NOLINT(clang-diagnostic-error)
```
won't help here, because it's a clang message and not a clang-tidy message.

however: how can i tell clang-tidy to avoid checking gtest.h?

(edit: re-formatted after transfer from bugzilla)

**Comment by carlosgalvezp** [comment]
Third-party headers should be included as system libraries via `-isystem` to avoid compiler warnings and/or linter warnings on them.
