### ISSUE TITLE
[coroutines] Compiler incorrectly caches thread_local address across suspend-points

### ISSUE THREAD

**Issue by fed5e9a7-7d28-4f31-a028-3851a135503d** [llvm/llvm-project#47179]
|  |  |
| --- | --- |
| Bugzilla Link | [47835](https://llvm.org/bz47835) |
| Version | trunk |
| OS | All |
| CC | @bcardosolopes,@zygoloid |

## Extended Description 
The clang compiler is incorrectly caching the address of thread_local variables across a suspend-point. It's possible that a coroutine could suspend and later resume on a different thread, however, which could mean that the thread_local instance from another thread might be accessed.

Godbolt: https://godbolt.org/z/o1djvq

For example compile the following program with: `-std=c++20 -stdlib=libc++ -O2 -pthread`

```
#include <experimental/coroutine>
#include <thread>
#include <unistd.h>
#include <pthread.h>
 
auto switch_to_new_thread(std::thread& out) {
  struct awaitable {
    std::thread* p_out;
    bool await_ready() { return false; }
    void await_suspend(std::experimental::coroutine_handle<> h) {
      std::thread& out = *p_out;
      out = std::thread([h]() mutable {
          h.resume();
        });
    }
    void await_resume() {}
  };
  return awaitable{&out};
}
 
struct task{
  struct promise_type {
    task get_return_object() { return {}; }
    std::experimental::suspend_never initial_suspend() { return {}; }
    std::experimental::suspend_never final_suspend() noexcept { return {}; }
    void return_void() {}
    void unhandled_exception() {}
  };
};

thread_local int tls_variable = 0;

static task resuming_on_new_thread(std::thread& out) {
  int* i = &tls_variable;

  co_await switch_to_new_thread(out);

  int* j = &tls_variable;

  std::puts((i == j) ? "tls_variable address was same" : "tls_variable address was different");
}
 
int main() {
  std::thread out;
  resuming_on_new_thread(out);
  out.join();
}
```

Expected output: "tls_variable address was different"
Actual output: "tls_variable address was same"

If you compile with -O0 then it correctly outputs "tls_variable address was different".

**Comment by ChuanqiXu9** [comment]
Godbolt: https://godbolt.org/z/Th7cb8j6z (Removed experimental namespace)
