### ISSUE TITLE
'Assertion `ResultPass && "getAnalysis*() called on an analysis that was not " "'required' by pass!"' failed.' with "opt -memoryssa -gvn -licm -float2int -slp-vectorizer"

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#47188]
|  |  |
| --- | --- |
| Bugzilla Link | [47844](https://llvm.org/bz47844) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @yuanfang-chen |

## Extended Description 
OS and Platform:
CentOS Linux release 7.8.2003 (Core), x86_64 GNU/Linux
*******************************************************************************
Program:
int main() {return 0;}
*******************************************************************************
Clang Version:
$ clang -v
clang version 12.0.0 (/home/suocy/src/llvm-dev/llvm-project/llvm/tools/clang 568035ac3955790aee2a5dbc2b1f4074c76bb4d7)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/suocy/bin/llvm-dev/bin
Found candidate GCC installation: /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
*******************************************************************************
Command Lines:
$ clang -O3 -mllvm -disable-llvm-optzns -c -emit-llvm a.c -o a.bc
$ opt -memoryssa -gvn -licm -float2int -slp-vectorizer  a.bc -o a.opt.bc
opt: /home/suocy/src/llvm-dev/llvm-project/llvm/include/llvm/PassAnalysisSupport.h:239: AnalysisType& llvm::Pass::getAnalysisID(llvm::AnalysisID) const $with AnalysisType = llvm::BasicAAWrapperPass; llvm::AnalysisID = const void*]: Assertion `ResultPass && "getAnalysis*() called on an analysis that was n$t " "'required' by pass!"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/suocy/bin/llvm-dev/bin/opt -memoryssa -gvn -licm -float2int -slp-vectorizer a.bc -o a.opt.bc
1.      Running pass 'Function Pass Manager' on module 'a.bc'.
2.      Running pass 'Function Alias Analysis Results' on function '@main'
 #&#8203;0 0x00000000029d923c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/suocy/bin/llvm-dev/bin/opt+0x29d923c)
 #&#8203;1 0x00000000029d71e4 llvm::sys::RunSignalHandlers() (/home/suocy/bin/llvm-dev/bin/opt+0x29d71e4)
 #&#8203;2 0x00000000029d7343 SignalHandler(int) (/home/suocy/bin/llvm-dev/bin/opt+0x29d7343)
 #&#8203;3 0x00007ffa57056630 __restore_rt (/lib64/libpthread.so.0+0xf630)
 #&#8203;4 0x00007ffa55c44387 raise (/lib64/libc.so.6+0x36387)
 #&#8203;5 0x00007ffa55c45a78 abort (/lib64/libc.so.6+0x37a78)
 #&#8203;6 0x00007ffa55c3d1a6 __assert_fail_base (/lib64/libc.so.6+0x2f1a6)
 #&#8203;7 0x00007ffa55c3d252 (/lib64/libc.so.6+0x2f252)
 #&#8203;8 0x0000000001951c45 llvm::AAResultsWrapperPass::runOnFunction(llvm::Function&) (/home/suocy/bin/llvm-dev/bin/opt+0x1951c45)
 #&#8203;9 0x000000000223b7e8 llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/suocy/bin/llvm-dev/bin/opt+0x223b7e8)
#&#8203;10 0x000000000223c289 llvm::FPPassManager::runOnModule(llvm::Module&) (/home/suocy/bin/llvm-dev/bin/opt+0x223c289)
#&#8203;11 0x000000000223b093 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/suocy/bin/llvm-dev/bin/opt+0x223b093)
#&#8203;12 0x000000000071ee5e main (/home/suocy/bin/llvm-dev/bin/opt+0x71ee5e)
#&#8203;13 0x00007ffa55c30555 __libc_start_main (/lib64/libc.so.6+0x22555)
#&#8203;14 0x00000000007cfb75 _start (/home/suocy/bin/llvm-dev/bin/opt+0x7cfb75)
Aborted

**Comment by arsenm** [comment]
Old pass manager
