### ISSUE TITLE
dependent template constexpr auto variable has type 'auto'

### ISSUE THREAD

**Issue by f7d9a599-8365-4225-8735-d1e6340786a8** [llvm/llvm-project#47190]
|  |  |
| --- | --- |
| Bugzilla Link | [47846](https://llvm.org/bz47846) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
Example: 

https://godbolt.org/z/hMsffh

**Comment by AaronBallman** [comment]
This issue was fixed in Clang 13.0.0: https://gcc.godbolt.org/z/xzvKKM6jb
