### ISSUE TITLE
Remove mov before sbb reg, reg

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#47201]
|  |  |
| --- | --- |
| Bugzilla Link | [47857](https://llvm.org/bz47857) |
| Version | trunk |
| OS | Linux |
| CC | @adibiagio,@topperc,@LebedevRI,@RKSimon,@phoebewang,@rotateright |

## Extended Description 
As shown here:
https://godbolt.org/z/Tfzj6n

It should be possible to remove mov before sbb with same operands.

..
        mov     esi, 0
        sbb     rsi, rsi
        and     esi, 38
        add     r9, rsi
...

**Comment by RKSimon** [comment]
Test case added at bce954321a627f7159ad2733fbcb40e87505fa02

Fixed in trunk by recent combines for ADC/SBB/ADD/SUB - although we're just avoiding the dependency breaking issue due to a SBB/ADD/SUB combo - please reopen or raise a new bug if you see the original problem again.

**Comment by davidbolvansky** [comment]
Thanks
