### ISSUE TITLE
[aarch64] Redundant masks in downcast long multiply

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#47227]
|  |  |
| --- | --- |
| Bugzilla Link | [47883](https://llvm.org/bz47883) |
| Version | 10.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @Arnaud-de-Grandmaison-ARM,@DMG862,@RKSimon,@smithp35 |

## Extended Description 
All 64-bit backends appear to do this. 

However, I only think this is important on aarch64; x86_64, RISC-V64, MIPS64, and PPC64 don't appear to have similar instructions that are any more efficient than the current method, so I am filing this under aarch64.

Code:

  #include <stdint.h>

  uint64_t umull(uint64_t x0, uint64_t x1) {
    // Downcast + upcast works too
    return (x0 & 0xffffffff) * (x1 & 0xffffffff);
  }

  int64_t smull(int64_t x0, int64_t x1) {
    return (int64_t)(int32_t)x0 * (int64_t)(int32_t)x1;
  }

Expected assembly (and what GCC 9.3.0 emits):

umull:
        umull   x0, w0, w1
        ret

smull:
        smull   x0, w0, w1
        ret

Clang 10.0.1:

umull:
        and     x8, x0, #&#8203;0xffffffff
        and     x9, x1, #&#8203;0xffffffff
        mul     x0, x8, x9
        ret

smull:
        sxtw    x8, w0
        sxtw    x9, w1
        mul     x0, x8, x9
        ret

Note that if the parameters are 32-bit integers, the expected code is emitted. However, LLVM always turns this:

  %2 = trunc i64 %0 to i32
  %3 = zext i32 %2 to i64

to this:

 %2 = and i64 %0, 0xffffffff

so this does not work.

**Comment by easyaspi314** [comment]
I tested this, it has been fixed at least on HEAD.

**Comment by fhahn** [comment]
Thanks @easyaspi314!

Confirmed as fixed on current main, the following assembly is produced ( https://clang.godbolt.org/z/5xTEz5n75 )

```
umull(unsigned long, unsigned long):                             // @umull(unsigned long, unsigned long)
        umull   x0, w1, w0
        ret
smull(long, long):                             // @smull(long, long)
        smull   x0, w1, w0
        ret
```
