### ISSUE TITLE
clang-format puts attribute bracket on a new line

### ISSUE THREAD

**Issue by apolukhin** [llvm/llvm-project#47245]
|  |  |
| --- | --- |
| Bugzilla Link | [47901](https://llvm.org/bz47901) |
| Version | 10.0 |
| OS | Linux |
| CC | @apolukhin |

## Extended Description 
For the following code:

```
struct foo {
  [[deprecated("Construct from bla-bla-bla-bla-bla-bla-bla-bla instead. Deprecated because of bla-bla-bla-bla-bla")]] static void ParseFromFile(const char* path);
};
```

The command `clang-format-10 -style=Google -i bad_clang_format.hpp` produces the following formatting:

```
struct foo {
  [
      [deprecated("Construct from bla-bla-bla-bla-bla-bla-bla-bla instead. "
                  "Deprecated because of bla-bla-bla-bla-bla")]] static void
  ParseFromFile(const char* path);
};

```

That formatting seems wrong. Removing `-style=Google` for that particular case fixes the formatting:

```
struct foo {
  [[deprecated("Construct from bla-bla-bla-bla-bla-bla-bla-bla instead. "
               "Deprecated because of bla-bla-bla-bla-bla")]] static void
  ParseFromFile(const char *path);
};
```

Please fix the behaviour of `-style=Google` for cases like above.

**Comment by rymiel** [comment]
This was fixed by 5a4ddbd69db2b0e09398214510501d0e59a0c30b
