### ISSUE TITLE
Warnings when compiling with 32-bit windows compiler

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#47256]
|  |  |
| --- | --- |
| Bugzilla Link | [47912](https://llvm.org/bz47912) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [Details of complation and warnings](https://user-images.githubusercontent.com/60944935/143761330-af25ab02-9174-4f7e-ab3b-3903ca059f19.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

When I compile my simple file:
#include <clang-c/Index.h>
#include "clang/Tooling/CompilationDatabase.h"
#include "clang/Tooling/Tooling.h"

with the 32-bit Microsoft Visual studio (on Windows 10 64-bit) I get a lot of warnings like:
E:\Programs\LLVM\llvm-project\llvm\include\llvm/Support/type_traits.h(79): warning C4624: 'llvm::detail::copy_construction_triviality_helper<T>': destructor was implicitly defined as deleted
        with
        [
            T=std::string
        ]

The full details can be found in the attachment.

In my case it happens with the 9.0.1. version but I see the same problem with the current master (1e32df2f91f1aa1f8cd400ce50a621578fa0534e) (could not complete this build as there was a compilation crash of LLVM / clang) and I've had a report that it also happens with the 5.0.0 version so it looks like a long standing problem.

**Comment by Endilll** [comment]
> Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27034 for x86

We no longer support Visual Studio 2017, requiring 2019. Feel free to reopen if you see the same warning there.
