### ISSUE TITLE
AfterControlStatement: MultiLine breaks AllowShortFunctionsOnASingleLine

### ISSUE THREAD

**Issue by 29aa2f32-6803-49cf-9ec3-df16cd935c1f** [llvm/llvm-project#47280]
|  |  |
| --- | --- |
| Bugzilla Link | [47936](https://llvm.org/bz47936) |
| Version | 11.0 |
| OS | Linux |
| CC | @KitsuneRal,@elvenfighter,@mydeveloperday |

## Extended Description 
Using the MultiLine setting for BraceWrapping.AfterControlStatement appears to disable AllowShortFunctionsOnASingleLine, even in cases without any control statements. For the input:

void bar() {}
class Foo {
    void shortfunction() { bar(); }
};

The command:

clang-format --style="{BasedOnStyle: llvm, AllowShortFunctionsOnASingleLine: Inline, BreakBeforeBraces: Custom, BraceWrapping: {AfterFunction: true, AfterControlStatement: MultiLine}}"

produces:

void bar() {}
class Foo {
  void shortfunction()
  {
    bar();
  }
};

If MultiLine is replaced with Always or Never, or is left out entirely, we get:

void bar() {}
class Foo {
  void shortfunction() { bar(); }
};

which is the expected result, as no control statements are present.

**Comment by mydeveloperday** [comment]
https://reviews.llvm.org/D114521

**Comment by jefftrull** [comment]
Thanks!
