### ISSUE TITLE
range-loop-analysis checks for trivial copyability, rather than trivial copy-constructibility

### ISSUE THREAD

**Issue by f188e250-2944-49d2-9658-84b6fb47320e** [llvm/llvm-project#47355]
|  |  |
| --- | --- |
| Bugzilla Link | [48011](https://llvm.org/bz48011) |
| Version | 11.0 |
| OS | Linux |
| CC | @dwblaikie,@devincoughlin,@randomnetcat,@pogo59,@zygoloid,@Cry-Thomas |

## Extended Description 
On the Cpplang slack, user Wolle posted a curious warning that came from range-loop-analysis.

Here's a minimal example: https://godbolt.org/z/1cxs43. Note that without the copy assignment operator overload, the warning is not present.

The range-based for loop performs a copy construction, so that is what should be checked for.

At https://clang.llvm.org/doxygen/SemaStmt_8cpp_source.html#l02824, the check is on whether the type is trivially copyable, not whether it is trivially copy constructible, which is a weaker requirement (but the relevant one in this case). I am not intimately familiar with clang sourcecode, but I believe this to be the cause of the warning.

**Comment by 11happy** [comment]
Hello , I am interested to work on this issue @Endilll . I am new to LLVM and would like to contribute to the org.
Thank you.

**Comment by Endilll** [comment]
@11happy Go ahead!

**Comment by 11happy** [comment]
As I have gone through the issue and have tried to understand it I believe the following change should suffice basically instead of checking for `isTriviallyCopyableType` we should check for `isTriviallyCopyConstructibleType` and for that should a new method be implemented or changes should be made in the current method.
Current method `isTriviallyCopyableType`:
```

bool QualType::isTriviallyCopyableType(const ASTContext &Context) const {
  if ((*this)->isArrayType())
    return Context.getBaseElementType(*this).isTriviallyCopyableType(Context);

  if (hasNonTrivialObjCLifetime()){
    return false;

  }
  // C++11 [basic.types]p9 - See Core 2094
  //   Scalar types, trivially copyable class types, arrays of such types, and
  //   cv-qualified versions of these types are collectively
  //   called trivially copyable types.

  QualType CanonicalType = getCanonicalType();
  if (CanonicalType->isDependentType()){
    return false;


  }
  if (CanonicalType->isSizelessBuiltinType())
    return true;
  // Return false for incomplete types after skipping any incomplete array types
  // which are expressly allowed by the standard and thus our API.
  if (CanonicalType->isIncompleteType()){
    return false;

  }
  
  // As an extension, Clang treats vector types as Scalar types.
  if (CanonicalType->isScalarType() || CanonicalType->isVectorType())
    return true;

  if (const auto *RT = CanonicalType->getAs<RecordType>()) {
    if (const auto *ClassDecl = dyn_cast<CXXRecordDecl>(RT->getDecl())) {
      if (!ClassDecl->isTriviallyCopyable()){
        return false;

      } 
    }

    return true;
  }
  // No other types can match.
  return false;
}
```
Here I am requesting for feedback and suggestion regarding this matter. Also my current understanding of the issue , the expected working should be we should have warning in both the cases whether the `=` is overloaded or not.If I misunderstood anything please correct me.
Thank you.

**Comment by Endilll** [comment]
@11happy Can you create a PR with the proposed change?

**Comment by 11happy** [comment]
Sure I will create a PR by tomorrow.
