### ISSUE TITLE
LLVM 11.0.0 build by GCC 10.2.0 failed

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#47387]
|  |  |
| --- | --- |
| Bugzilla Link | [48043](https://llvm.org/bz48043) |
| Version | 11.0 |
| OS | Linux |
| Blocks | llvm/llvm-project#47144  |
| Attachments | [LLVM 11.0.0 by GCC 10.2 failed log](https://user-images.githubusercontent.com/60944935/143761364-05b23ecf-1995-4fb1-acb0-6406396791e6.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@slacka,@zygoloid,@Artem-B,@tstellar |

## Extended Description 

ld: a number of undefined references; see the attached log file for details.

P.S.
Build by GCC 9.3 is OK.
Build of LLVM 12.0.0git by both GCC 9.3 and 10.2 is OK too.

**Comment by arsenm** [comment]
Old build problem on old release, last comment says not reproducible
