### ISSUE TITLE
DNS for LLVM/clangd index server

### ISSUE THREAD

**Issue by ChristianKuehnel** [llvm/llvm-project#47413]
|  |  |
| --- | --- |
| Bugzilla Link | [48069](https://llvm.org/bz48069) |
| Version | unspecified |
| OS | All |
| CC | @asl,@dwblaikie,@kadircet |

## Extended Description 
A copy of Sam McCall's email request:
http://lists.llvm.org/pipermail/clangd-dev/2020-October/000743.html

--------------
Hi llvm-admin folks,

We're developing a "remote index" feature that makes clangd work better on
large codebases:  clangd queries a shared index server instead of parsing
the whole project locally.
It's early days, but our initial target is LLVM itself. We have a public
instance at 34.107.73.68 - Google is providing a GCP VM to run it on, but
the indexer/server is part of llvm-project[1].

We'd like to give it a domain name so we can start sharing with early
testers. Does it make sense to point clangd-index.llvm.org at this server?
If there are concerns, we could also register a different domain, and
either revisit once this is more stable or keep it "unofficial"
indefinitely.

Privacy-wise, we need to write up a policy, but the service accepts limited
context information needed to serve queries (e.g. the incomplete identifier
for code completion). It will *record* only coarse aggregate statistics
like request count/latency distribution/error rate, for monitoring health
and usefulness.

Happy to discuss more about logistics, privacy, the feature itself or
anything else.

Cheers, Sam

[1]
https://github.com/llvm/llvm-project/blob/master/clang-tools-extra/clangd/index/remote/README.md

**Comment by sam-mccall** [comment]
This is live (for a while now): https://clangd-index.llvm.org/
