### ISSUE TITLE
PassAnalysisSupport.h:239: AnalysisType& llvm::Pass::getAnalysisID(llvm::AnalysisID) const [with AnalysisType = llvm::BasicAAWrapperPass; llvm::AnalysisID = const void*]: Assertion `ResultPass && "getAnalysis*() called on an analysis that was not " "'requ

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#47428]
|  |  |
| --- | --- |
| Bugzilla Link | [48084](https://llvm.org/bz48084) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @yuanfang-chen |

## Extended Description 
*******************************************************************************
OS and Platform:
CentOS Linux release 7.8.2003 (Core), x86_64 GNU/Linux
*******************************************************************************
Program:
int main() {return 0;}
*******************************************************************************
clang version:
$ clang -v
clang version 12.0.0 (/home/suocy/src/llvm-dev/llvm-project/llvm/tools/clang 4455f3ce72ba2bb0276200f6f29629afca8812d4)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/suocy/bin/llvm-dev/bin
Found candidate GCC installation: /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
*******************************************************************************
Command Lines:
$ clang -O3 -mllvm -disable-llvm-optzns -c -emit-llvm a.c -o a.bc
$ opt -memoryssa -gvn -licm -float2int -slp-vectorizer  a.bc -o a.opt.bc
opt: /home/suocy/src/llvm-dev/llvm-project/llvm/include/llvm/PassAnalysisSupport.h:239: AnalysisType& llvm::Pass::getAnalysisID(llvm::AnalysisID) const [with AnalysisType = llvm::BasicAAWrapperPass; llvm::AnalysisID = const void*]: Assertion `ResultPass && "getAnalysis*() called on an analysis that was not " "'required' by pass!"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/suocy/bin/llvm-dev/bin/opt -memoryssa -gvn -licm -float2int -slp-vectorizer a.bc -o a.opt.bc
1.      Running pass 'Function Pass Manager' on module 'a.bc'.
2.      Running pass 'Function Alias Analysis Results' on function '@main'
 #&#8203;0 0x0000000002a110fc llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/suocy/bin/llvm-dev/bin/opt+0x2a110fc)
 #&#8203;1 0x0000000002a0f0a4 llvm::sys::RunSignalHandlers() (/home/suocy/bin/llvm-dev/bin/opt+0x2a0f0a4)
 #&#8203;2 0x0000000002a0f203 SignalHandler(int) (/home/suocy/bin/llvm-dev/bin/opt+0x2a0f203)
 #&#8203;3 0x00007f740e6e6630 __restore_rt (/lib64/libpthread.so.0+0xf630)
 #&#8203;4 0x00007f740d2d4387 raise (/lib64/libc.so.6+0x36387)
 #&#8203;5 0x00007f740d2d5a78 abort (/lib64/libc.so.6+0x37a78)
 #&#8203;6 0x00007f740d2cd1a6 __assert_fail_base (/lib64/libc.so.6+0x2f1a6)
 #&#8203;7 0x00007f740d2cd252 (/lib64/libc.so.6+0x2f252)
 #&#8203;8 0x00000000019685a5 llvm::AAResultsWrapperPass::runOnFunction(llvm::Function&) (/home/suocy/bin/llvm-dev/bin/opt+0x19685a5)
 #&#8203;9 0x0000000002263bd8 llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/suocy/bin/llvm-dev/bin/opt+0x2263bd8)
#&#8203;10 0x0000000002264679 llvm::FPPassManager::runOnModule(llvm::Module&) (/home/suocy/bin/llvm-dev/bin/opt+0x2264679)
#&#8203;11 0x0000000002263483 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/suocy/bin/llvm-dev/bin/opt+0x2263483)
#&#8203;12 0x00000000007235ab main (/home/suocy/bin/llvm-dev/bin/opt+0x7235ab)
#&#8203;13 0x00007f740d2c0555 __libc_start_main (/lib64/libc.so.6+0x22555)
#&#8203;14 0x00000000007d7185 _start (/home/suocy/bin/llvm-dev/bin/opt+0x7d7185)
Aborted

**Comment by Endilll** [comment]
I guess the reproducer is `int main() {return 0;}`.

**Comment by nikic** [comment]
This is a legacy PM assertion, so this shouldn't be relevant anymore.

**Comment by Endilll** [comment]
@nikic how can someone not familiar with LLVM codebase determine whether assertions comes from legacy PM and is not relevant anymore? I remember seeing on Discourse that legacy PM is still in use somewhere.

**Comment by nikic** [comment]
The rule of thumb is that legacy PM is not supported in `opt` (middle-end) but is supported in `llc` (back-end).
