### ISSUE TITLE
Incorrect Cost Calculations for Shuffle Ports on Icelake-client / Icelake-server

### ISSUE THREAD

**Issue by 9b82a16b-cfd5-497e-b822-833572ad76a3** [llvm/llvm-project#47454]
|  |  |
| --- | --- |
| Bugzilla Link | [48110](https://llvm.org/bz48110) |
| Version | trunk |
| OS | All |
| Blocks | llvm/llvm-project#31672  |
| CC | @adibiagio,@topperc,@RKSimon,@MattPD,@phoebewang,@rotateright |

## Extended Description 
Hi there,

It looks like llvm-mca is treating icelake-client and icelake-server as having only one shuffle port.  This causes incorrect cost calculations for any operation that would use said shuffle ports.  A block diagram showing the architecture can be found here: https://en.wikichip.org/wiki/intel/microarchitectures/sunny_cove (sunny cove is the core used by both icelake-server and icelake-client).  Similarly, you can find the uops usage for any given shuffle here:  https://uops.info/table.html?search=shuf&cb_lat=on&cb_tp=on&cb_uops=on&cb_ports=on&cb_SKL=on&cb_ICL=on&cb_measurements=on&cb_base=on&cb_avx=on

If the code generating the costs for LLVM-MCA is used by anything else in the toolchain, it's likely this will yield a performance benefit for other users targeting icelake-server and icelake-client.

**Comment by RKSimon** [comment]
https://reviews.llvm.org/D115547 fixes some of the integer shuffles

**Comment by RKSimon** [comment]
https://reviews.llvm.org/D115752 fixes some of the fp shuffles

**Comment by RKSimon** [comment]
Fixed by 74d1fc742af0a5a766dbfa9f7a1a715301e05d3f and 67cce1ceee2d15a570535aabed0aef2bd1314be3
