### ISSUE TITLE
clang-tidy with -std=c++20 ignores -Wno-comment and -Wno-invalid-token-paste

### ISSUE THREAD

**Issue by 8f86e7e5-cf11-44aa-9452-d007e98888f9** [llvm/llvm-project#47460]
|  |  |
| --- | --- |
| Bugzilla Link | [48116](https://llvm.org/bz48116) |
| Version | unspecified |
| OS | Windows NT |
| CC | @AaronBallman |

## Extended Description 
clang-tidy with -std=c++20 ignores some flags to ignore warnings (-Wno-comment and -Wno-invalid-token-paste). With -std=c++17 works as expected (the warnings are ignored).
Most other warnings can be ignored, regardless -std version (such as -Wno-literal-conversion with code `int i = 2.4;`)
Found with clang 11.0.0 win64.

$ cat a.cpp
/* warning
/* nested
/* comments
*/

#define PLUS(x) +##x
void warning_invalid_token_paste() {
    3 PLUS(4);
}

$ clang-tidy a.cpp -- -std=c++17 -Wno-comment -Wno-invalid-token-paste

$ clang-tidy a.cpp -- -std=c++20 -Wno-comment -Wno-invalid-token-paste
2 warnings and 1 error generated.
Error while processing a.cpp.
a.cpp:2:1: warning: '/*' within block comment [clang-diagnostic-comment]
/* nested
^
a.cpp:3:1: warning: '/*' within block comment [clang-diagnostic-comment]
/* comments
^
a.cpp:8:7: error: pasting formed '+4', an invalid preprocessing token [clang-diagnostic-invalid-token-paste]
    3 PLUS(4);
      ^
a.cpp:6:18: note: expanded from macro 'PLUS'
#define PLUS(x) +##x
                 ^
Found compiler error(s).

**Comment by PiotrZSL** [comment]
Should be fixed with b530eeea5e7697d58af2adac66c8b86c79e649bb, at-least this gives some workaround.

**Comment by PiotrZSL** [comment]
Actually correct fix is: 992fa7be3438bce61cfba7c0e0b07d9d1ddcc05b
