### ISSUE TITLE
clang-tidy false positive: suspicious usage of 'sizeof(A*)'; pointer to aggregate

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#47479]
|  |  |
| --- | --- |
| Bugzilla Link | [48135](https://llvm.org/bz48135) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The warning bugprone-sizeof-expression with the text "suspicious usage of 'sizeof(A*)'; pointer to aggregate" comes way too often as a false-positive, in cases that sizeof is applied on template parameter, e.g. sizeof(T).

Example occurence:

        if (e != this->end())
            ::memmove(static_cast<void *>(b), static_cast<void *>(e), (static_cast<T *>(this->end()) - e) * sizeof(T));

as seen at: https://github.com/qt/qtbase/blob/250b69ace47923b51aaeaaea39e0ffc638fa4b4a/src/corelib/tools/qarraydataops.h#L419

**Comment by carlosgalvezp** [comment]
Lacking self-contained reproducible example, last comment seems to indicate the issue is fixed. Please reopen if it persists.
