### ISSUE TITLE
keyword on iso_c_binding intrinsic not allowed

### ISSUE THREAD

**Issue by naromero77** [llvm/llvm-project#47488]
|  |  |
| --- | --- |
| Bugzilla Link | [48144](https://llvm.org/bz48144) |
| Version | trunk |
| OS | All |
| Attachments | [keyword not allowed for ISO_C_BINDING intrinsic](https://user-images.githubusercontent.com/7633854/143761394-c47527fd-72ab-4a3c-bb02-61b134662197.gz) |
| CC | @jeanPerier,@kiranktp,@sscalpone |

## Extended Description 

gFortran and ifort allow this to reduced test case to compile without warning or errors.

Flang front-end does not accept it.

[naromero@naromero-desktop bugs]$ flang -c optional_arg.F90
optional_arg.F90:8:30: error: Keyword 'shape=' may not appear in a reference to a procedure with an implicit interface
    call c_f_pointer(cptr,iptr,shape=(/csize/))

I understand the error -- but if you are using an intrinsic from the iso_c_bindings, shouldn't the procedure interface be considered explicit.

**Comment by kkwli** [comment]
`flang-new` compiles the original reproducer successfully now.

```fortran
$ cat t.f90
subroutine foo(cptr, csize)
  use, intrinsic :: ISO_C_BINDING
  implicit none
  type(C_PTR), intent(in) :: cptr
  integer, intent(in) :: csize
  integer(1), pointer :: iptr(:)

  call c_f_pointer(cptr,iptr,shape=(/csize/))
end subroutine foo
$ flang-new -c t.f90
$ echo $?
0

```

**Comment by kkwli** [comment]
However, the diagnostic of the shape argument seems to be missing - #59177.
