### ISSUE TITLE
alpha.unix.cstring.OutOfBounds wrongly triggers for flexible array members

### ISSUE THREAD

**Issue by 43113a5a-87dd-4095-9c20-18b5be2ae8c3** [llvm/llvm-project#47480]
|  |  |
| --- | --- |
| Bugzilla Link | [48136](https://llvm.org/bz48136) |
| Version | trunk |
| OS | All |
| CC | @devincoughlin |

## Extended Description 
We've been using alpha.unix checks, but OutOfBounds is annoyingly triggering with flexible array members. Apparently it thinks they are 0 sized.

Using clang 12 from git, checked out Oct 27 2020.

# scan-build -enable-checker alpha.unix gcc test.c -o test
test.c:13:2: warning: Memory set function overflows the destination buffer [alpha.unix.cstring.OutOfBounds]
        memset(str->data, 'x', 10);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~

When test.c contains:

#include <stdlib.h>
#include <string.h>

struct str {
	size_t len;
	char data[];
};

int main(void)
{
	struct str *str = malloc(sizeof(str) + 10);
	str->len = 10;
	memset(str->data, 'x', 10);
	return 0;
}

**Comment by balazs-benics-sonarsource** [comment]
Fixed by e5646b9254e0150e7897bd2658fa0b19eef39070. Released with clang-14.
