### ISSUE TITLE
omp critical clause does not allow optional name argument

### ISSUE THREAD

**Issue by naromero77** [llvm/llvm-project#47489]
|  |  |
| --- | --- |
| Bugzilla Link | [48145](https://llvm.org/bz48145) |
| Version | trunk |
| OS | All |
| Attachments | [omp critical clause with name argument](https://user-images.githubusercontent.com/7633854/143761395-d9efda86-fe54-473b-8cef-c61272436ff4.gz) |
| CC | @Sameeranjoshi,@jeanPerier,@kiranktp,@sscalpone |

## Extended Description 

This reduced test case compiles with gfortran and ifort.

The optional [name] argument on the omp critical clause is not accepted by the Flang front-end.

[naromero@naromero-desktop bugs]$ flang -c -fopenmp omp_critical.F90
omp_critical.F90:5:19: error: Internal: no symbol found for 'foo'
    !$OMP CRITICAL (foo)
                    ^^^
omp_critical.F90:7:23: error: Internal: no symbol found for 'foo'
    !$OMP END CRITICAL (foo)

**Comment by kiranchandramohan** [comment]
Fixed by https://reviews.llvm.org/D110502
