### ISSUE TITLE
bugprone-redundant-branch-condition false positive with reference parameters

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#47508]
|  |  |
| --- | --- |
| Bugzilla Link | [48164](https://llvm.org/bz48164) |
| Version | unspecified |
| OS | Windows NT |
| CC | @EugeneZelenko |

## Extended Description 
The check doesn't seem to consider that a reference parameter may be modified between calls in code like:

bool func(int &i);

int main() {
  int i = 12;
  if (func(i) && i) {
    if (func(i) && i) {        
    }
  }
}

The check claims that the `&& i` in the second `if` statement is redundant, but there's no way to know whether `func()` modified `i` on the second call.

**Comment by carlosgalvezp** [comment]
No longer reproducible on latest trunk.
