### ISSUE TITLE
LLVM IR has no floating-point negate operator

### ISSUE THREAD

**Issue by sunfishcode** [llvm/llvm-project#4750]
|  |  |
| --- | --- |
| Bugzilla Link | [4378](https://llvm.org/bz4378) |
| Version | unspecified |
| OS | All |
| CC | @lattner |

## Extended Description 
Sign-bit manipulation operations copysign and abs can be done with
libm calls, but there is currently no simple way to get a proper
floating-point negate operation in LLVM IR.

**Comment by gwelymernans** [comment]
We've had `fneg` for a long while now. (https://llvm.org/docs/LangRef.html#fneg-instruction)
