### ISSUE TITLE
Program run stuck after IndVarSimplify

### ISSUE THREAD

**Issue by Guo-Peilin** [llvm/llvm-project#47502]
|  |  |
| --- | --- |
| Bugzilla Link | [48158](https://llvm.org/bz48158) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [test case](https://user-images.githubusercontent.com/74886391/143761405-ec4b7589-0cc9-43e4-854d-a79b81ee4d27.gz) |
| CC | @Arnaud-de-Grandmaison-ARM,@LebedevRI,@smithp35 |

## Extended Description 

$ opt -indvars test-case.ll -S -o after-loop-indvars.ll
$ llc after-loop-indvars.ll -filetype=obj -o tmp.o
$ clang tmp.o -o tmp.out

I get stuck when I run tmp.out

**Comment by nikic** [comment]
Can't reproduce, so assuming this is fixed.
