### ISSUE TITLE
clang-11's invocation of <coroutine> headers via -fcoroutines flag

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#47516]
|  |  |
| --- | --- |
| Bugzilla Link | [48172](https://llvm.org/bz48172) |
| Version | 11.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @palebedev,@dpacbach,@zygoloid |

## Extended Description 
Compiling a .cpp file that uses the coroutine library with the command.

clang-11 -std=c++20 -stdlib=libstdc++ main.cpp 

The error is as follows:

/usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/coroutine:295:2: error: "the coroutine header requires -fcoroutines"
#error "the coroutine header requires -fcoroutines"

Adding the -fcoroutine flag doesn't help:

clang-11 -std=c++20 -stdlib=libstdc++ main.cpp -fcoroutines

which generates the error:

clang-11: error: unknown argument: '-fcoroutines'

**Comment by ChuanqiXu9** [comment]
This should be addressed in clang trunk and gcc11.
