### ISSUE TITLE
clang-cl support C language standard option /std:c11 and /std:c17

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#47529]
|  |  |
| --- | --- |
| Bugzilla Link | [48185](https://llvm.org/bz48185) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @nico,@P-p-H-d,@zygoloid,@rnk |

## Extended Description 
C language standard option /std:c11 and /std:c17 ware added in Visual Studio 2019 16.8 see https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.8.0

current clang-cl (as of Nov 14, 23cc838099e10b13a32e54105f4db0f1b7e3a842)
clang-cl /c /std:c11 test.c
clang-cl: warning: argument unused during compilation: '/std:c11' [-Wunused-command-line-argument]

though `clang -c -std=c11 test.c` works.

test.c:
```
int add(int x, int y) {
    return x + y;
}
```

**Comment by AaronBallman** [comment]
Implemented in d087d805acb664e885e9c31a916f6cfa5dbc2186
