### ISSUE TITLE
clang-format gets confused by nested blocks

### ISSUE THREAD

**Issue by de9ccd5f-6521-4b39-ab30-f4e04ed39258** [llvm/llvm-project#47575]
|  |  |
| --- | --- |
| Bugzilla Link | [48231](https://llvm.org/bz48231) |
| Version | 11.0 |
| OS | Linux |
| Attachments | [The code in question](https://user-images.githubusercontent.com/92601579/143761438-3fdcc299-74de-48e9-a3d3-637cbd465635.gz) |

## Extended Description 

As a result, the blocks are formatted incorrectly and the namespace-closing comments are put in wrong places.

--- nested_blocks.cpp --
```cpp
namespace A
{
namespace B
{
namespace C
{
void foo()
{
    {
        {
            bar();
        }
    }
    {
        baz();
    }
}

}
}
}
```

```sh
$ /home/brd/soft/llvm-11.0.0/bin/clang-format --version
clang-format version 11.0.0

$ cat nested_blocks.cpp | /home/brd/soft/llvm-11.0.0/bin/clang-format --style=LLVM
namespace A {
namespace B {
namespace C {
void foo() { {{bar(); }
} // namespace C
{ baz(); }
} // namespace B

} // namespace A
}
}
```

**Comment by rymiel** [comment]
Duplicate of https://github.com/llvm/llvm-project/issues/33891
