### ISSUE TITLE
Blank result page with Clang 0.210

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#4757]
|  |  |
| --- | --- |
| Bugzilla Link | [4385](https://llvm.org/bz4385) |
| Version | unspecified |
| OS | MacOS X |
| Attachments | [Safari screen capture.](https://user-images.githubusercontent.com/60944935/143739442-a9aec55b-5fbf-4cde-93fe-e3932284e70d.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @tkremenek |

## Extended Description 

The Safari page (Safari 4.0) comes up, but it is completely blank. Did a View Source, but it comes up blank also.

scan-build -k -V xcodebuild -configuration Debug -sdk iphonesimulator2.2.1
...
** BUILD SUCCEEDED **
scan-build: 17 bugs found.
scan-build: Run 'scan-view /var/folders/Mm/MmqDxtdN2RaLCk+F75uoa++++TM/-Tmp-/scan-build-2009-06-13-2' to examine bug reports.
scan-build: Analysis run complete.
scan-build: Viewing analysis results in '/var/folders/Mm/MmqDxtdN2RaLCk+F75uoa++++TM/-Tmp-/scan-build-2009-06-13-2' using scan-view.
Starting scan-view at: http://127.0.0.1:8181
  Use Ctrl-C to exit.

**Comment by arsenm** [comment]
Latest comment say not reproducible
