### ISSUE TITLE
bugprone-branch-clone should not warn if fallthrough is specified

### ISSUE THREAD

**Issue by SteffenSeckler** [llvm/llvm-project#47588]
|  |  |
| --- | --- |
| Bugzilla Link | [48244](https://llvm.org/bz48244) |
| Version | unspecified |
| OS | Linux |
| CC | @Szelethus,@EugeneZelenko |

## Extended Description 
The check bugprone-branch-clone (https://clang.llvm.org/extra/clang-tidy/checks/bugprone-branch-clone.html) currently throws a warning if consecutive statements of a switch contain [[fallthrough]] 

E.g:

switch(someEnum) {
case a:
[[fallthrough]];
case b:
[[fallthrough]];
case c:
foo();
}

This should not happen, as [[fallthrough]] is exactly what should be specified here.

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D147889
