### ISSUE TITLE
Assertion failure in dependent call to generic lambda with `.operator()` syntax

### ISSUE THREAD

**Issue by ldalessa** [llvm/llvm-project#47594]
|  |  |
| --- | --- |
| Bugzilla Link | [48250](https://llvm.org/bz48250) |
| Version | trunk |
| OS | All |
| CC | @davidstone,@zygoloid |

## Extended Description 
The index sequence seemed necessary to trigger the ICE.

> #include <utility>
> 
> int main() {
>     auto inner = []<std::size_t... Is>() { return 0; };
>     auto outer = [&]<std::size_t... Is>(std::index_sequence<Is...>) {
>         return inner.template operator()<Is...>();
>     };
>     return outer(std::make_index_sequence<5>());
> }

https://godbolt.org/z/njK79P

**Comment by davidstone** [comment]
https://reviews.llvm.org/rG0bff3a965022647fcdd17cc8f2217f5a2cd30b4c has landed -- this issue is resolved, but it doesn't look like I have the power to close tickets.
