### ISSUE TITLE
Bindings/Go/go.test fails on GitHub Action Ubuntu-18.04 runner

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#47619]
|  |  |
| --- | --- |
| Bugzilla Link | [48275](https://llvm.org/bz48275) |
| Version | 11.0 |
| OS | Linux |
| Blocks | llvm/llvm-project#47144  |
| CC | @echristo,@MaskRay,@pcc |

## Extended Description 
From what I can tell, this test started to fail after GitHub dropped golang 1.11 and 1.12 from it's Ubuntu-18.04 runner.  The test fails with this error message:

go build runtime/cgo: invalid flag in go:cgo_ldflag: -Wl,-allow-shlib-undefined

**Comment by arsenm** [comment]
Old release build issue
