### ISSUE TITLE
Large ExtInt cannot convert to/from floating point (DAG, SINT_TO_FP)

### ISSUE THREAD

**Issue by mgehre** [llvm/llvm-project#47646]
|  |  |
| --- | --- |
| Bugzilla Link | [48302](https://llvm.org/bz48302) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@erichkeane,@zygoloid |

## Extended Description 
(see https://godbolt.org/z/hszG4W)

  int main() {
    _ExtInt(129) c = 3;
    double d = c;
    return 0;
  }
causes

Fatal error: error in backend: Unsupported library call operation!
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/clang -g -o ./output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-9.2.0 -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '<source>'.
4.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@main'
 #&#8203;0 0x0000555cba07efcc llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/clang+0x2e0bfcc)
 #&#8203;1 0x0000555cba07cd64 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-trunk/bin/clang+0x2e09d64)
 #&#8203;2 0x0000555cba07cff5 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-trunk/bin/clang+0x2e09ff5)
 #&#8203;3 0x0000555cb9febac2 llvm::CrashRecoveryContext::HandleExit(int) (/opt/compiler-explorer/clang-trunk/bin/clang+0x2d78ac2)
 #&#8203;4 0x0000555cba075c1e llvm::sys::Process::Exit(int, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+0x2e02c1e)
 #&#8203;5 0x0000555cb817be0e LLVMErrorHandler(void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+0xf08e0e)
 #&#8203;6 0x0000555cb9ff2329 llvm::report_fatal_error(llvm::Twine const&, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+0x2d7f329)
 #&#8203;7 0x0000555cb9ff2478 (/opt/compiler-explorer/clang-trunk/bin/clang+0x2d7f478)
 #&#8203;8 0x0000555cbadcc0a8 llvm::TargetLowering::makeLibCall(llvm::SelectionDAG&, llvm::RTLIB::Libcall, llvm::EVT, llvm::ArrayRef<llvm::SDValue>, llvm::TargetLowering::MakeLibCallOptions, llvm::SDLoc const&, llvm::SDValue) const (/opt/compiler-explorer/clang-trunk/bin/clang+0x3b590a8)
 #&#8203;9 0x0000555cbae6066f llvm::DAGTypeLegalizer::ExpandIntOp_SINT_TO_FP(llvm::SDNode*) (/opt/compiler-explorer/clang-trunk/bin/clang+0x3bed66f)

I wonder if this should be solved in LLVM or if clang should forbid those conversions.

**Comment by AaronBallman** [comment]
Closing as a duplicate of https://github.com/llvm/llvm-project/issues/44994.
