### ISSUE TITLE
libMLIR.so.11 linking fails during compilation

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#47641]
|  |  |
| --- | --- |
| Bugzilla Link | [48297](https://llvm.org/bz48297) |
| Version | 11.0 |
| OS | Linux |
| Attachments | [various log files and CMakeCache.txt](https://user-images.githubusercontent.com/60944935/143761473-ea439b36-e813-4a02-b53d-016b2d06168b.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

build node:

* X86 PC
* Linux 5.9.11
* userland package distro: Debian
* toolchain: lvm-11 (from distro - https://packages.debian.org/source/bullseye/llvm-toolchain-11)
* CMake: 3.19.1 (self-compiled)
_____

trying to compile llvm-11 (.0.0) from source with fails late in the compilation process. From the build log (line 55047 onwards) it seems that llibMLIR.so.11 linking fails.

**Comment by arsenm** [comment]
Old build issue
