### ISSUE TITLE
clang-format mismatches braces with nested unnamed scopes

### ISSUE THREAD

**Issue by 5ee67997-95f7-486b-9652-f6a2fe3bdd3d** [llvm/llvm-project#47649]
|  |  |
| --- | --- |
| Bugzilla Link | [48305](https://llvm.org/bz48305) |
| Version | 11.0 |
| OS | Linux |
| CC | @CaseyCarter,@cpplearner,@mateuszzz88 |

## Extended Description 
Hello.
With clang-format -10 and -11 installed from repo on ubuntu 20.11 following c++ code is obviously formatted wrong:
```
clang-format-11 -style=llvm test.cpp 
void foo() {
  {// asdf
   {int a;
}
}
{
  { int b; }
}
}
```
Removing `{// asdf` is sufficient to format it ok.
I expect it to be formatted like this (possibly with comment in new line, but this may be llvm style):
```
void foo() {
  {// asdf
    { int a; }
  }
  {
    { int b; }
  }
}

```

**Comment by AtnNn** [comment]
This issue still exists in version 14:

```
bash$ echo $'void foo(){{//asdf\n{int a;}}{{int b;}}}' | clang-format -style LLVM
void foo() {
  {// asdf
   {int a;
}
}
{
  { int b; }
}
}
```

**Comment by rymiel** [comment]
Duplicate of https://github.com/llvm/llvm-project/issues/33891
