### ISSUE TITLE
struct DefinitionData &clang::CXXRecordDecl::data() const: Assertion `DD && "queried property of class with no definition"' failed

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#47651]
|  |  |
| --- | --- |
| Bugzilla Link | [48307](https://llvm.org/bz48307) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@orivej,@zygoloid |

## Extended Description 
The following code triggered an assertion failure. It might be a dup of bug 12777.

$ cat foo.cc 
namespace NS  {
template<typename T> struct S {
  struct S1;
  struct S2;
  struct S3 : public S1, public S2 {};
};
}

$ clang -v
clang version 12.0.0 (https://github.com/llvm/llvm-project.git 75f50e15bf8fff6fba1d4678adedd33ef6a945e5)
Target: x86_64-unknown-linux-gnu
Thread model: posix

$ clang -c foo.cc 
clang: /backup/work/compilers/compiler-source/llvm-project/clang/include/clang/AST/DeclCXX.h:434: struct DefinitionData &clang::CXXRecordDecl::data() const: Assertion `DD && "queried property of class with no definition"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /backup/work/compilers/compiler-install/llvm-12.0.0-dev/bin/clang -c foo.cc
1.      foo.cc:5:36: current parser token '{'
2.      foo.cc:1:1: parsing namespace 'NS'
3.      foo.cc:2:22: parsing struct/union/class body 'NS::S'
4.      foo.cc:5:3: parsing struct/union/class body 'NS::S::S3'
...

**Comment by usx95** [comment]
This works fine at head.
