### ISSUE TITLE
Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.

### ISSUE THREAD

**Issue by 5c623c95-c4ff-4a7a-9d0a-436fb89424d5** [llvm/llvm-project#47668]
|  |  |
| --- | --- |
| Bugzilla Link | [48324](https://llvm.org/bz48324) |
| Version | 11.0 |
| OS | Linux |
| Attachments | [.ii, .cpp, .sh and backtrace associated files.](https://user-images.githubusercontent.com/92601575/143761481-a23be9f4-ba00-41ad-bc90-6ad42e6272cb.gz) |
| CC | @dwblaikie,@zygoloid |

## Extended Description 

Front-end assertion while compiling [dry-comparison](https://github.com/rollbear/dry-comparisons/tree/drier) library code.

Briefly tested code compilation godbolt.org. Clang-6 compiles. Clang versions subsequent to 6 fail with the noted assertion.

See attached files for details.

Thanks,

**Comment by Endilll** [comment]
Appears to be fixed on post-17 trunk: https://godbolt.org/z/Mj97b3bY4
Reduced by C-Reduce:
```cpp
auto tuple = [](auto... ts) {
  return [](auto f) -> decltype(f(ts...)) {}
} auto or_elements = [](auto func) {
  return [](auto... elements) -> decltype((func(elements) || ...)) {}
};
template <typename Func, typename Tuple> struct op_t {
  Tuple tup;
  Func func;
  template <typename E> auto apply(E e) -> decltype(tup(func(e)));
  op_t(int , Func , Tuple ;
  template < typename RH > auto operator==(RH rh)  -> decltype(apply(rh));
  template < typename LH > friend auto operator==(LH lh, op_t rh) -> decltype(rh == lh)
} auto none_of = [](auto... ts) { return op_t(0, nor_elements, tuple (ts ...)
} void main() {
  0 == none_of(int{})
```
