### ISSUE TITLE
clang-format fails to detect trailing return syntax within a macro

### ISSUE THREAD

**Issue by chandlerc** [llvm/llvm-project#47664]
|  |  |
| --- | --- |
| Bugzilla Link | [48320](https://llvm.org/bz48320) |
| Version | unspecified |
| OS | All |

## Extended Description 
Given:
```
auto TestWithoutMacro() -> int { return 42; }

#define SOME_X_MACRO(NAME) \
  auto NAME() -> int { return 42; }

SOME_X_MACRO(TestWithMacro)
```

Running `clang-format --style=Google test.cpp` produces:
```
auto TestWithoutMacro() -> int { return 42; }

#define SOME_X_MACRO(NAME) \
  auto NAME()->int { return 42; }

SOME_X_MACRO(TestWithMacro)
```

The `->` inside the macro body should retain the spaces around it, as this isn't a member access, this is a trailing return type.

This may be related to llvm/llvm-project#41495  but is pretty clearly different from llvm/llvm-project#42180  which is mentioned there.

**Comment by rymiel** [comment]
Patch: https://reviews.llvm.org/D141811
