### ISSUE TITLE
wrong code with "-mem2reg -instcombine -simplifycfg -inline"

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#47678]
|  |  |
| --- | --- |
| Bugzilla Link | [48334](https://llvm.org/bz48334) |
| Version | trunk |
| OS | Linux |
| Attachments | [bc file](https://user-images.githubusercontent.com/60944935/143761487-0e4d1f87-237d-4d99-bb3a-18ec72e81c46.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

*******************************************************************************
OS and Platform:
CentOS Linux release 7.8.2003 (Core), x86_64 GNU/Linux
*******************************************************************************
Program:
$ cat a.c
int printf(const char *, ...);
int a=0;
int(b)(c) { return 7 >> c; }
void d() { a = b(133); }
int main() {
  d();
  printf("%d\n", a);
}
*******************************************************************************
clang version:
$ clang --version
clang version 12.0.0 (/home/suocy/src/llvm-dev/llvm-project/llvm/tools/clang f15b7869e5afbd6c24ef440b0b62593e80fbd24f)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/suocy/bin/llvm-dev/bin
*******************************************************************************
Command Lines:
$ clang -c -emit-llvm -O3 -mllvm -disable-llvm-optzns a.c -o a.bc
$ opt a.bc -o a.opt1.bc
$ clang a.opt1.bc -o a1.o
$ opt -mem2reg -instcombine -simplifycfg -inline a.bc -o a.opt2.bc
$ clang a.opt2.bc -o a2.o
$ ./a1.o
0
$ ./a2.o
4195600

**Comment by msebor** [comment]
C shift operators are defined for values of the right operand between zero and the width of the promoted left operand minus one.  In the test case the value of the operand, 133, is outside that range, leaving the behavior of the whole program undefined.
