### ISSUE TITLE
Several clang-analyzer-cplusplus checks are not documentated

### ISSUE THREAD

**Issue by firewave** [llvm/llvm-project#47682]
|  |  |
| --- | --- |
| Bugzilla Link | [48338](https://llvm.org/bz48338) |
| Version | unspecified |
| OS | Windows NT |

## Extended Description 
There are several clang-analyzer-cplusplus checks missing on https://clang.llvm.org/extra/clang-tidy/checks/list.html

I haven't checked the source but just from the ones I encountered it's at least:

clang-analyzer-cplusplus.NewDelete
clang-analyzer-cplusplus.NewDeleteLeaks
clang-analyzer-cplusplus.PlacementNew

**Comment by PiotrZSL** [comment]
Fixed by d9cd7b0e5f347fb316c6efa075d009a003c8fc54
