### ISSUE TITLE
Backport fix for --pgo-warn-misexpect from 12 to 11

### ISSUE THREAD

**Issue by 614eaf53-7ecd-4c4f-a941-40bf78db1486** [llvm/llvm-project#47747]
|  |  |
| --- | --- |
| Bugzilla Link | [48403](https://llvm.org/bz48403) |
| Version | 11.0 |
| OS | All |
| Blocks | llvm/llvm-project#47144  |
| CC | @davidbolvansky,@jdoerfert,@LebedevRI,@zygoloid,@tstellar |
| Fixed by commit(s) | 6d2b75e0887ee87e247756c4d51733616bb2f356 |

## Extended Description 
Issue is that invoking a compilation through libclang twice in the same process gives 

"clang (LLVM option parsing): for the --pgo-warn-misexpect option: may only occur zero or one times!" 

and then crashes : https://reviews.llvm.org/D66324#1680232

The trivial fix is in LLVM 12 : https://github.com/llvm/llvm-project/commit/6d2b75e0887ee87e247756c4d51733616bb2f356

It seems to apply without issues in current 11.X - could this be backported please ?

**Comment by chfast** [comment]
Closing as release 11 is very old now.
