### ISSUE TITLE
Crash on "help memory read"

### ISSUE THREAD

**Issue by kparzysz-quic** [llvm/llvm-project#47777]
|  |  |
| --- | --- |
| Bugzilla Link | [48433](https://llvm.org/bz48433) |
| Version | unspecified |
| OS | Linux |
| CC | @JDevlieghere |

## Extended Description 
The command "help memory read" causes a crash. No other action is required, load lldb and ask for help about "memory read".

$ lldb
(lldb) help memory read
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /w/c/org/bin/lldb
 #&#8203;0 0x000000000042cdc3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/w/c/org/bin/lldb+0x42cdc3)
 #&#8203;1 0x000000000042b07e llvm::sys::RunSignalHandlers() (/w/c/org/bin/lldb+0x42b07e)
 #&#8203;2 0x000000000042d405 SignalHandler(int) (/w/c/org/bin/lldb+0x42d405)
 #&#8203;3 0x00007f78efde6890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)
 #&#8203;4 0x00007f78e8980c70 lldb_private::Options::GenerateOptionUsage(lldb_private::Stream&, lldb_private::CommandObject*, unsigned int) (/w/c/org/bin/../lib/liblldb.so.12git+0x1000c70)
 #&#8203;5 0x00007f78e896d8eb lldb_private::CommandObject::GenerateHelpText(lldb_private::Stream&) (/w/c/org/bin/../lib/liblldb.so.12git+0xfed8eb)
 #&#8203;6 0x00007f78e896d75e lldb_private::CommandObject::GenerateHelpText(lldb_private::CommandReturnObject&) (/w/c/org/bin/../lib/liblldb.so.12git+0xfed75e)
 #&#8203;7 0x00007f78ea2ac4be lldb_private::CommandObjectHelp::DoExecute(lldb_private::Args&, lldb_private::CommandReturnObject&) (/w/c/org/bin/../lib/liblldb.so.12git+0x292c4be)
 #&#8203;8 0x00007f78e896e02c lldb_private::CommandObjectParsed::Execute(char const*, lldb_private::CommandReturnObject&) (/w/c/org/bin/../lib/liblldb.so.12git+0xfee02c)
 #&#8203;9 0x00007f78e8964b4c lldb_private::CommandInterpreter::HandleCommand(char const*, lldb_private::LazyBool, lldb_private::CommandReturnObject&, lldb_private::ExecutionContext*, bool, bool) (/w/c/org/bin/../lib/liblldb.so.12git+0xfe4b4c)
#&#8203;10 0x00007f78e8968253 lldb_private::CommandInterpreter::IOHandlerInputComplete(lldb_private::IOHandler&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) (/w/c/org/bin/../lib/liblldb.so.12git+0xfe8253)
#&#8203;11 0x00007f78e88d2d9d lldb_private::IOHandlerEditline::Run() (/w/c/org/bin/../lib/liblldb.so.12git+0xf52d9d)
#&#8203;12 0x00007f78e88b932d lldb_private::Debugger::RunIOHandlers() (/w/c/org/bin/../lib/liblldb.so.12git+0xf3932d)
#&#8203;13 0x00007f78e89695eb lldb_private::CommandInterpreter::RunCommandInterpreter(lldb_private::CommandInterpreterRunOptions&) (/w/c/org/bin/../lib/liblldb.so.12git+0xfe95eb)
#&#8203;14 0x00007f78e85bcd49 lldb::SBDebugger::RunCommandInterpreter(bool, bool) (/w/c/org/bin/../lib/liblldb.so.12git+0xc3cd49)
#&#8203;15 0x0000000000409fb6 Driver::MainLoop() (/w/c/org/bin/lldb+0x409fb6)
#&#8203;16 0x000000000040c215 main (/w/c/org/bin/lldb+0x40c215)
#&#8203;17 0x00007f78e62a3b97 __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344:0
#&#8203;18 0x0000000000406cca _start (/w/c/org/bin/lldb+0x406cca)
Segmentation fault

**Comment by DavidSpickett** [comment]
Building with:
```
$ /home/david.spickett/clang+llvm-15.0.0-aarch64-linux-gnu/bin/clang --version
clang version 15.0.0 (http://git.linaro.org/toolchain/jenkins-scripts.git 700512d472abfe4264c7894c1c1731a4db97183a)
```
I get the help as expected:
```
(lldb) help memory read
Read from the memory of the current target process.

Syntax: memory read <cmd-options> <address-expression> [<address-expression>]
```
Assuming this was indeed a miscompilation by clang, it is far too late to fix 10 or 11. If this were something a distro was hitting, we could consider working around in source but it's very simple to avoid so I don't see that happening.

Closing as incomplete won't fix as we aren't 100% sure that it was a miscompile, which would make it a clang bug anyway. Either way, we aren't going to take any action.
