### ISSUE TITLE
Clang crashed when cross compiling for target x86_64-win32-eabi.

### ISSUE THREAD

**Issue by antlilja** [llvm/llvm-project#47831]
|  |  |
| --- | --- |
| Bugzilla Link | [48487](https://llvm.org/bz48487) |
| Version | 11.0 |
| OS | Linux |
| Attachments | [Backtrace, preprocessed source and run script from crash.](https://user-images.githubusercontent.com/93435692/143761545-22f7b2ea-45c0-4080-966c-e84e103b7122.gz) |
| CC | @DougGregor,@zygoloid |

## Extended Description

**Comment by Endilll** [comment]
Can't reproduce using Clang 10 and 11: https://godbolt.org/z/M9h4cG53K
Feel free to reopen if you still experience this with newer Clang.
