### ISSUE TITLE
Durring compilation from GCC front end to IR signed/unsigned type information gets lost

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#4783]
|  |  |
| --- | --- |
| Bugzilla Link | [4411](https://llvm.org/bz4411) |
| Version | 2.5 |
| OS | Linux |
| Attachments | [Example](https://user-images.githubusercontent.com/60944935/143739455-a3ba7968-a211-41a2-a9a3-bf5f6c6c7fe4.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@nlewycky |

## Extended Description 

Take a look at the attached C source code (typetest.c).

The function open takes a typed function pointer as parameter (nfy parameter with type nfy_fct). nfy_fct function type takes an unsigned int and a short parameter.

link_nfy_fct function (which is from type nfy_fct) is compiled to:
define internal void @&#8203;link_nfy_fct(i32 %event, i16 signext %cond) nounwind

The header of open function is transformed to:
define i32 @&#8203;open(i32 %linktype, i8* %linkname, i8* %linkoptions, i32 %timeout, void (i32, i16)* %nfy) nounwind

where the type for nfy should be void (i32, i16 signext)* instead of void (i32, i16)*. With this the information gets lost in C to IR phase and the C Backend produces code which can not be compiled with some other strict compilers.

**Comment by arsenm** [comment]
GCC front end is obsolete as is the C backend
