### ISSUE TITLE
clang-format Incorrectly Removes Space After C Style Cast When Type Is Not a Pointer

### ISSUE THREAD

**Issue by da2c6997-54e2-4d10-97ab-fe0034f8474f** [llvm/llvm-project#47879]
|  |  |
| --- | --- |
| Bugzilla Link | [48535](https://llvm.org/bz48535) |
| Version | 11.0 |
| OS | Linux |
| Attachments | [Style file](https://user-images.githubusercontent.com/92601472/143761558-26c7e69b-7e42-4d11-877b-b8c70e50cdc8.gz) |
| CC | @mydeveloperday |

## Extended Description 

When I set the option "SpaceAfterCStyleCast" to true, clang-format will remove a space after a C-style cast when the type inside the cast parentheses is not a pointer time.

You can reproduce this by using the attached style file on https://git.yzena.com/Yzena/Yc/src/branch/master/tests/fs/fs_read.c, lines 69 and 107.

If I add an asterisk after the size_t inside the parens, the space is left.

I speculate that clang-format incorrectly thinks that both sets of parens are calls, i.e., that the first set is a call to a function that returns a function pointer and that the second set is a call to that supposed returned function pointer.

**Comment by rymiel** [comment]
This was fixed by 5426b2f9ed9f
