### ISSUE TITLE
clang-format Thinks Minus Is Negative

### ISSUE THREAD

**Issue by da2c6997-54e2-4d10-97ab-fe0034f8474f** [llvm/llvm-project#47881]
|  |  |
| --- | --- |
| Bugzilla Link | [48537](https://llvm.org/bz48537) |
| Version | 11.0 |
| OS | Linux |
| Attachments | [Style file](https://user-images.githubusercontent.com/92601472/143761562-3bbfb854-5a4c-463b-951e-b1bfdad2b4ac.gz) |
| CC | @mydeveloperday |

## Extended Description 

clang-format can be tricked into thinking that a minus operator is a unary negative operator.

Using the attached style file, run clang-format on https://git.yzena.com/Yzena/Yc/src/commit/dadbb62db6023b532bf0bbe7d73303950710937f/src/map/map.h . The spaces after the minus operators on lines 114 and 143 are removed.

**Comment by owenca** [comment]
Works in 18 and main now.
