### ISSUE TITLE
ReflowComments breaks Qt translation comments

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#47883]
|  |  |
| --- | --- |
| Bugzilla Link | [48539](https://llvm.org/bz48539) |
| Version | 10.0 |
| OS | Windows NT |
| CC | @JVApen,@mydeveloperday |

## Extended Description 
Qt has a concept of translation comments (see https://doc.qt.io/qt-5/i18n-source-translation.html#translator-comments)
This gives extra meaning to //:, //=, //~.
This is a bit similar to doxygen using ///, ///<, //! or //!<

When reflown and a part of the comments are added on a new line, it should repeat these extra characters as part of the comment token.

The reproduction:

.clang-format
=============
ColumnLimit:     40
ReflowComments:  true

example.cpp
===========
//: This is a test. AAAAAAAAAA AAAAAAAAA AAAAAAAAAAAAAAA
QString example = tr("Example");

result.cpp
==========
//: This is a test. AAAAAAAAAA AAAAAAAAA
//AAAAAAAAAAAAAAA
QString example = tr("Example");

expected.cpp
============
//: This is a test. AAAAAAAAAA AAAAAAAAA
//: AAAAAAAAAAAAAAA
QString example = tr("Example");

**Comment by mydeveloperday** [comment]
closed by 031743cb5b3c6c2df85a67d8533ef72a95e76cdc
