### ISSUE TITLE
Poor codegen for char loads/compares on arm64

### ISSUE THREAD

**Issue by pervognsen** [llvm/llvm-project#47899]
|  |  |
| --- | --- |
| Bugzilla Link | [48555](https://llvm.org/bz48555) |
| Version | trunk |
| OS | MacOS X |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Here is a repro with a .c file and the corresponding .s file built with clang -O3 -c -S: https://gist.github.com/pervognsen/e1a5ba99ede4b630ed08df8ded87f27e

These redundant instructions are the issue:

and w9, w9, #&#8203;0xff

The defs for w9 are ldrb instructions, so there is no need for these masking operations before the compares.

(This issue was first discovered with Apple's build of clang that ships in the latest Xcode toolchain, but I reproduced it with a self-built version from trunk.)

**Comment by lenary** [comment]
Godbolt: https://godbolt.org/z/Gs5bvnj38

This looks like it got fixed in Clang/LLVM 14, and on the specific example the codegen improved again in Clang/LLVM 15 (that codegen matches today's trunk)
