### ISSUE TITLE
Should LLD not set the RELRO program header when targeting -maarch64elf?

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#47893]
|  |  |
| --- | --- |
| Bugzilla Link | [48549](https://llvm.org/bz48549) |
| Version | unspecified |
| OS | All |
| Blocks | llvm/llvm-project#4440  |
| CC | @MaskRay,@kbeyls,@smithp35,@stephenhines |

## Extended Description 
In
https://lore.kernel.org/lkml/20201214231827.GG8873@bubble.grove.modra.org/
Alan Modra notes about BFD:

  The default linker emulation for an aarch64-linux ld.bfd is
  -maarch64linux, the default for an aarch64-elf linker is
  -maarch64elf.  They are not equivalent.  If you choose -maarch64elf
  you get an emulation that doesn't support -z relro.

Should LLD not set the RELRO program header when targeting -maarch64elf to better match compatibility with GNU BFD?

**Comment by MaskRay** [comment]
Perhaps it would be nicer lld didn't default to `-z relro`. Now it seems that wontfix is a realistic state as we don't plan to complex the code for this corner case.
