### ISSUE TITLE
LLD as a library behaves incorrectly about exiting

### ISSUE THREAD

**Issue by ddobrev** [llvm/llvm-project#47891]
|  |  |
| --- | --- |
| Bugzilla Link | [48547](https://llvm.org/bz48547) |
| Version | unspecified |
| OS | All |
| CC | @dwblaikie,@MaskRay,@smithp35,@tstellar |

## Extended Description 
lld is explicitly documented as invokable as a library at https://lld.llvm.org/ :

"You can embed LLD in your program to eliminate dependencies on external linkers. All you have to do is to construct object files and command line arguments just like you would do to invoke an external linker and then call the linker’s main function, lld::elf::link, from your code."

However, using this method requires passing a Boolean parameter for exiting. If it's true, the entire process dies right away. If it's false, it's left hanging unless llvm::llvm_shutdown() is manually called. This isn't the proper behaviour of a library as the calls should just to the job and not have the caller handle such details.

**Comment by MaskRay** [comment]
After patches like https://reviews.llvm.org/D88348 https://reviews.llvm.org/D70378, you can mimic `lld/tools/lld/lld.cpp`'s use of `lld::safeLldMain`. The interface certainly has rough corners but there are quite a few discussions covering this topic.
