### ISSUE TITLE
buffer deallocation pass crash

### ISSUE THREAD

**Issue by bondhugula** [llvm/llvm-project#47919]
|  |  |
| --- | --- |
| Bugzilla Link | [48575](https://llvm.org/bz48575) |
| Version | unspecified |
| OS | Linux |
| CC | @sherhut,@jpienaar,@River707,@silvasean |

## Extended Description 
With the LLVM/MLIR trunk version (latest) at 3dbe471a260392ec63dda8deb2709160afc56dde, the buffer deallocation pass crashes on the appended input:

-------------------------
$ mlir-opt -buffer-deallocation   buffer_dealloc.mlir
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ../llvm-project-upstream/build/bin/mlir-opt -buffer-deallocation buffer_dealloc.mlir
1.	 #&#8203;0 0x00007f1eb9d248b3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/uday/llvm-project-upstream/build/bin/../lib/libLLVMSupport.so.12git+0x1fa8b3)
 #&#8203;1 0x00007f1eb9d225be llvm::sys::RunSignalHandlers() (/home/uday/llvm-project-upstream/build/bin/../lib/libLLVMSupport.so.12git+0x1f85be)
 #&#8203;2 0x00007f1eb9d24d7c SignalHandler(int) (/home/uday/llvm-project-upstream/build/bin/../lib/libLLVMSupport.so.12git+0x1fad7c)
 #&#8203;3 0x00007f1ebc237dd0 __restore_rt (/lib64/libpthread.so.0+0x12dd0)
 #&#8203;4 0x00007f1ebb33d987 (anonymous namespace)::BufferDeallocationPass::runOnFunction() (/home/uday/llvm-project-upstream/build/bin/../lib/libMLIRTransforms.so.12git+0x52987)
 #&#8203;5 0x00007f1eba604e8c mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool) (/home/uday/llvm-project-upstream/build/bin/../lib/libMLIRPass.so.12git+0x24e8c)
 #&#8203;6 0x00007f1eba6053a1 mlir::detail::OpToOpPassAdaptor::runPipeline(llvm::iterator_range<llvm::pointee_iterator<std::unique_ptr<mlir::Pass, std::default_delete<mlir::Pass> >*, mlir::Pass> >, mlir::Operation*, mlir::AnalysisManager, bool, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/home/uday/llvm-project-upstream/build/bin/../lib/libMLIRPass.so.12git+0x253a1)
 #&#8203;7 0x00007f1eba60c290 mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_8::operator()(llvm::MutableArrayRef<mlir::OpPassManager>) const (/home/uday/llvm-project-upstream/build/bin/../lib/libMLIRPass.so.12git+0x2c290)
 #&#8203;8 0x00007f1eba60c07e void llvm::parallel::detail::parallel_for_each<llvm::SmallVector<mlir::OpPassManager, 1u>*, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_8>(llvm::SmallVector<mlir::OpPassManager, 1u>*, llvm::SmallVector<mlir::OpPassManager, 1u>*, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_8) (/home/uday/llvm-project-upstream/build/bin/../lib/libMLIRPass.so.12git+0x2c07e)
 #&#8203;9 0x00007f1eba60625f mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool) (/home/uday/llvm-project-upstream/build/bin/../lib/libMLIRPass.so.12git+0x2625f)
#&#8203;10 0x00007f1eba604f27 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool) (/home/uday/llvm-project-upstream/build/bin/../lib/libMLIRPass.so.12git+0x24f27)
#&#8203;11 0x00007f1eba608116 mlir::PassManager::run(mlir::Operation*) (/home/uday/llvm-project-upstream/build/bin/../lib/libMLIRPass.so.12git+0x28116)
#&#8203;12 0x00007f1ebbfa297f performActions(llvm::raw_ostream&, bool, bool, llvm::SourceMgr&, mlir::MLIRContext*, mlir::PassPipelineCLParser const&) (/home/uday/llvm-project-upstream/build/bin/../lib/libMLIROptLib.so.12git+0x697f)
#&#8203;13 0x00007f1ebbfa142d processBuffer(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, bool, bool, bool, bool, mlir::PassPipelineCLParser const&, mlir::DialectRegistry&) (/home/uday/llvm-project-upstream/build/bin/../lib/libMLIROptLib.so.12git+0x542d)
#&#8203;14 0x00007f1ebbfa1af2 mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&, bool) (/home/uday/llvm-project-upstream/build/bin/../lib/libMLIROptLib.so.12git+0x5af2)
#&#8203;15 0x000000000020d31f main (../llvm-project-upstream/build/bin/mlir-opt+0x20d31f)
#&#8203;16 0x00007f1eb8e5a6a3 __libc_start_main (/lib64/libc.so.6+0x236a3)
#&#8203;17 0x000000000020d02e _start (../llvm-project-upstream/build/bin/mlir-opt+0x20d02e)
---------------------------

func @&#8203;main(%arg0: memref<10x1xf32>, %arg1: memref<10x1xf32>) {
  %c10_i32 = constant 10 : i32
  %0 = alloc() : memref<10x1xf32>
  "test.cst"(%0) {value = dense<0.000000e+00> : tensor<10x1xf32>} : (memref<10x1xf32>) -> ()
  %c1_i32 = constant 1 : i32
  %c0_i32 = constant 0 : i32
  %1 = "test.tuple"(%c0_i32, %c10_i32, %arg0, %0, %c0_i32) : (i32, i32, memref<10x1xf32>, memref<10x1xf32>, i32) -> tuple<i32, i32, memref<10x1xf32>, memref<10x1xf32>, i32>
  %2 = "test.bar"(%1) ( {
    ^bb0(%arg2: tuple<i32, i32, memref<10x1xf32>, memref<10x1xf32>>):  // no predecessors
    %4 = "test.foo"(%arg2) {index = 0 : i32} : (tuple<i32, i32, memref<10x1xf32>, memref<10x1xf32>>) -> i32
    %5 = "test.foo"(%arg2) {index = 1 : i32} : (tuple<i32, i32, memref<10x1xf32>, memref<10x1xf32>>) -> i32
    %6 = cmpi "slt", %4, %5 : i32
    "test.yield"(%6) : (i1) -> ()
  },  {
    ^bb0(%arg2: tuple<i32, i32, memref<10x1xf32>, memref<10x1xf32>, i32>):  // no predecessors
    %4 = "test.foo"(%arg2) {index = 0 : i32} : (tuple<i32, i32, memref<10x1xf32>, memref<10x1xf32>, i32>) -> i32
    %5 = "test.foo"(%arg2) {index = 1 : i32} : (tuple<i32, i32, memref<10x1xf32>, memref<10x1xf32>, i32>) -> i32
    %6 = "test.foo"(%arg2) {index = 2 : i32} : (tuple<i32, i32, memref<10x1xf32>, memref<10x1xf32>, i32>) -> memref<10x1xf32>
    %7 = "test.foo"(%arg2) {index = 3 : i32} : (tuple<i32, i32, memref<10x1xf32>, memref<10x1xf32>, i32>) -> memref<10x1xf32>
    %8 = "test.foo"(%arg2) {index = 4 : i32} : (tuple<i32, i32, memref<10x1xf32>, memref<10x1xf32>, i32>) -> i32
    %9 = addi %8, %c1_i32 : i32
    %10 = addi %4, %c1_i32 : i32
    %11 = alloc() : memref<1x1xf32>
    "test.test"(%6, %4, %c0_i32, %11) : (memref<10x1xf32>, i32, i32, memref<1x1xf32>) -> ()
    %12 = alloc() : memref<10x1xf32>
    "test.test-update"(%7, %11, %8, %c0_i32, %12) : (memref<10x1xf32>, memref<1x1xf32>, i32, i32, memref<10x1xf32>) -> ()
    %13 = "test.tuple"(%10, %5, %6, %12, %9) : (i32, i32, memref<10x1xf32>, memref<10x1xf32>, i32) -> tuple<i32, i32, memref<10x1xf32>, memref<10x1xf32>, i32>
    "test.yield"(%13) : (tuple<i32, i32, memref<10x1xf32>, memref<10x1xf32>, i32>) -> ()
  }) : (tuple<i32, i32, memref<10x1xf32>, memref<10x1xf32>, i32>) -> tuple<i32, i32, memref<10x1xf32>, memref<10x1xf32>, i32>
  %3 = "test.foo"(%2) {index = 3 : i32} : (tuple<i32, i32, memref<10x1xf32>, memref<10x1xf32>, i32>) -> memref<10x1xf32>
  "test.abc"(%3, %arg1) : (memref<10x1xf32>, memref<10x1xf32>) -> ()
  "test.terminator"() : () -> ()
}

**Comment by xgupta** [comment]
> The code in the buffer deallocation pass makes a call to findNearestCommonDominator but fails to check if the return value is null.
Haven't find any call to findNearestCommonDominator from BufferDeallocation.cpp, also not able to reproduce the issue with test case. Is it still valid?
