### ISSUE TITLE
ICE using C++20 with latest clang-tidy version from MacPorts

### ISSUE THREAD

**Issue by e84ee981-20b7-441e-8de0-adb2190144d6** [llvm/llvm-project#47934]
|  |  |
| --- | --- |
| Bugzilla Link | [48590](https://llvm.org/bz48590) |
| Version | unspecified |
| OS | All |
| CC | @AlisdairM |

## Extended Description 
I have a simple file, dummy.cpp containing a single #include

#include <atomic>

I compile with the command line:

clang-tidy -extra-arg="-std=c++20" dummy.cpp

and I get the following error dump:

Error while trying to load a compilation database:
Could not auto-detect compilation database for file "dummy.cpp"
No compilation database found in /Users/alisdairmeredith/repositories/alisdairm/sharable_pointer or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
Assertion failed: (LHS.isValid() && RHS.isValid() && "Passed invalid source location!"), function isBeforeInTranslationUnit, file /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_llvm-devel/clang-devel/work/llvm-project/llvm/tools/clang/lib/Basic/SourceManager.cpp, line 1967.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/local/libexec/llvm-devel/bin/clang-tidy -extra-arg=-std=c++20 dummy.cpp
1.	/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread/pthread_impl.h:63:35: current parser token ')'
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libLLVM.dylib            0x000000010cf70182 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 43
1  libLLVM.dylib            0x000000010cf70582 SignalHandler(int) + 162
2  libsystem_platform.dylib 0x00007fff7052cb5d _sigtramp + 29
3  libsystem_platform.dylib 0x0000000000005d38 _sigtramp + 18446603338631713272
4  libsystem_c.dylib        0x00007fff703e66a6 abort + 127
5  libsystem_c.dylib        0x00007fff703af20d basename_r + 0
6  libclang-cpp.dylib       0x0000000108178842 clang::SourceManager::isBeforeInTranslationUnit(clang::SourceLocation, clang::SourceLocation) const + 594
7  clang-tidy               0x000000010795882f clang::tooling::ExpandModularHeadersPPCallbacks::parseToLocation(clang::SourceLocation) + 397
8  libclang-cpp.dylib       0x0000000108212c2e (anonymous namespace)::PragmaAssumeNonNullHandler::HandlePragma(clang::Preprocessor&, clang::PragmaIntroducer, clang::Token&) + 480
9  libclang-cpp.dylib       0x000000010820df41 clang::Preprocessor::HandlePragmaDirective(clang::PragmaIntroducer) + 83
10 libclang-cpp.dylib       0x000000010820e4f5 clang::Preprocessor::Handle_Pragma(clang::Token&) + 1403
11 libclang-cpp.dylib       0x0000000108205ab7 clang::Preprocessor::ExpandBuiltinMacro(clang::Token&) + 643
12 libclang-cpp.dylib       0x00000001082051e9 clang::Preprocessor::HandleMacroExpandedIdentifier(clang::Token&, clang::MacroDefinition const&) + 153
13 libclang-cpp.dylib       0x000000010821a218 clang::Preprocessor::HandleIdentifier(clang::Token&) + 384
14 libclang-cpp.dylib       0x00000001081cc130 clang::Lexer::LexIdentifier(clang::Token&, char const*) + 366
15 libclang-cpp.dylib       0x00000001081cf61b clang::Lexer::LexTokenInternal(clang::Token&, bool) + 699
16 libclang-cpp.dylib       0x00000001081ce69a clang::Lexer::Lex(clang::Token&) + 122
17 libclang-cpp.dylib       0x000000010821a836 clang::Preprocessor::Lex(clang::Token&) + 66
18 libclang-cpp.dylib       0x000000010820e500 clang::Preprocessor::Handle_Pragma(clang::Token&) + 1414
19 libclang-cpp.dylib       0x0000000108205ab7 clang::Preprocessor::ExpandBuiltinMacro(clang::Token&) + 643
20 libclang-cpp.dylib       0x00000001082051e9 clang::Preprocessor::HandleMacroExpandedIdentifier(clang::Token&, clang::MacroDefinition const&) + 153
21 libclang-cpp.dylib       0x000000010821a218 clang::Preprocessor::HandleIdentifier(clang::Token&) + 384
22 libclang-cpp.dylib       0x00000001081cc130 clang::Lexer::LexIdentifier(clang::Token&, char const*) + 366
23 libclang-cpp.dylib       0x00000001081cf61b clang::Lexer::LexTokenInternal(clang::Token&, bool) + 699
24 libclang-cpp.dylib       0x00000001081ce69a clang::Lexer::Lex(clang::Token&) + 122
25 libclang-cpp.dylib       0x000000010821a836 clang::Preprocessor::Lex(clang::Token&) + 66
26 libclang-cpp.dylib       0x000000010822ee5b clang::Parser::ConsumeBrace() + 91
27 libclang-cpp.dylib       0x000000010825328a clang::BalancedDelimiterTracker::consumeClose() + 54
28 libclang-cpp.dylib       0x000000010823cf2e clang::Parser::ParseLinkage(clang::ParsingDeclSpec&, clang::DeclaratorContext) + 592
29 libclang-cpp.dylib       0x000000010829d760 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) + 768
30 libclang-cpp.dylib       0x000000010829d28b clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) + 261
31 libclang-cpp.dylib       0x000000010829c8b8 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) + 1238
32 libclang-cpp.dylib       0x000000010829b842 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) + 640
33 libclang-cpp.dylib       0x000000010822055f clang::ParseAST(clang::Sema&, bool, bool) + 442
34 libclang-cpp.dylib       0x00000001094ded76 clang::FrontendAction::Execute() + 84
35 libclang-cpp.dylib       0x00000001094a8ed4 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 1748
36 libclang-cpp.dylib       0x000000010962c92b clang::tooling::FrontendActionFactory::runInvocation(std::__1::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::__1::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) + 275
37 clang-tidy               0x000000010793b586 clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, llvm::StringRef)::ActionFactory::runInvocation(std::__1::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::__1::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) + 88
38 libclang-cpp.dylib       0x000000010962c7ab clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::__1::shared_ptr<clang::CompilerInvocation>, std::__1::shared_ptr<clang::PCHContainerOperations>) + 195
39 libclang-cpp.dylib       0x000000010962bc2a clang::tooling::ToolInvocation::run() + 1960
40 libclang-cpp.dylib       0x000000010962d7eb clang::tooling::ClangTool::run(clang::tooling::ToolAction*) + 2365
41 clang-tidy               0x0000000107938281 clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, llvm::StringRef) + 861
42 clang-tidy               0x000000010795df02 clang::tidy::clangTidyMain(int, char const**) + 4870
43 libdyld.dylib            0x00007fff703413d5 start + 1
Abort trap: 6

MacPorts version suggests this was built against trunk around 2020/11/23

**Comment by carlosgalvezp** [comment]
No longer reproducible on trunk.
