### ISSUE TITLE
llvm-header-guard style of header guard use reserved identifier

### ISSUE THREAD

**Issue by cfd43508-abed-4b61-9716-b28c9ef59019** [llvm/llvm-project#47957]
|  |  |
| --- | --- |
| Bugzilla Link | [48613](https://llvm.org/bz48613) |
| Version | unspecified |
| OS | Linux |
| CC | @salman-javed-nz |

## Extended Description 
If I run `clang-tidy -fix -checks=llvm-header-guard,bugprone-reserved-identifier a.hpp` in `/tmp` on file `a.hpp`, containing:

#ifndef TMP_A_HPP
#define TMP_A_HPP

#endif // TMP_A_HPP

…it renames the macro definition to `_TMP_A_HPP` (now with leading underscore). But identifiers with a leading underscore and then an uppercase letter are reserved, eg see the doc for this CERT rule:

https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample(HeaderGuard)

Indeed, if I run the command again, `bugprone-reserved-identifier` now complains about the new identifier.

I think this check should always strip any leading underscore off the name it calculates.

(Less importantly, I'd also vote that it allows an option for computing the name from the relative path (rather than absolute) and an option for specifying a prefix for all header-guards.)

Thanks very much for all work on clang-tidy - it's a hugely useful tool.

**Comment by salman-javed-nz** [comment]
Fixed by c7aa358
