### ISSUE TITLE
Crash with LTO and __attribute__((cpu_dispatch(generic, skylake)))

### ISSUE THREAD

**Issue by 43ba373d-51b0-40d9-9b2a-31e324848997** [llvm/llvm-project#47986]
|  |  |
| --- | --- |
| Bugzilla Link | [48642](https://llvm.org/bz48642) |
| Version | 11.0 |
| OS | Linux |
| Attachments | [Stack dump](https://user-images.githubusercontent.com/92601563/143761592-a8110ad3-6367-4b07-96fa-6239de1d72a0.gz), [bug_cpu_dispatch_lto-3864e8.sh](https://user-images.githubusercontent.com/92601563/143761593-3f2c2974-f324-4621-8d54-8407d75aef01.gz), [bug_cpu_dispatch_lto-3864e8.c](https://user-images.githubusercontent.com/92601563/143761594-515b6181-1c26-4244-9dfd-264577c8892d.gz) |
| CC | @nicolas17,@zsrkmyn |

## Extended Description 

source code:

```
__attribute__((cpu_dispatch(generic, skylake)))
void func(double * restrict x, double* restrict y, double* restrict z);

__attribute__((cpu_specific(generic, skylake)))
void func(double * restrict x, double* restrict y, double* restrict z) {
  for(int i = 0; i < 8; i++) {
    z[i] += x[i] + y[i];
  }
}
```

command line:

```
clang -flto bug_cpu_dispatch_lto.c
```

See stack dump attached.

**Comment by MaskRay** [comment]
```cc
__attribute__((cpu_dispatch(generic, skylake)))
void func(double * restrict x, double* restrict y, double* restrict z);

__attribute__((cpu_specific(generic, skylake)))
void func(double * restrict x, double* restrict y, double* restrict z) {
  for(int i = 0; i < 8; i++) {
    z[i] += x[i] + y[i];
  }
}

int main() {
  double x[8]={}, y[8]={}, z[8];
  func(x, y, z);
}
```
`clang a.c -flto && ./a.out` works fine.
