### ISSUE TITLE
[Sparc] Stage2 fails on Linux CI with "error: cannot apply asm label to function after its first use"

### ISSUE THREAD

**Issue by glaubitz** [llvm/llvm-project#47994]
|  |  |
| --- | --- |
| Bugzilla Link | [48650](https://llvm.org/bz48650) |
| Version | trunk |
| OS | Linux |
| Depends On | llvm/llvm-project#48906  |
| Attachments | [Preprocessed source for sanitizer_platform_limits_posix.cpp](https://user-images.githubusercontent.com/92601373/143761598-560f626d-aa25-48ae-bd77-fd92bf52af72.gz) |
| CC | @DimitryAndric,@jrtc27,@rorth |

## Extended Description 
The stage2 build fails on clang-sparc64-linux-multistage with:

FAILED: projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizerNoHooks.sparc.dir/sanitizer_stackdepot.cpp.o 
/var/lib/buildbot/workers/debian-stadler-sparc64/clang-sparc64-linux-multistage/stage1.install/bin/clang++ -DHAVE_RPC_XDR_H=1 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iprojects/compiler-rt/lib/sanitizer_common -I/var/lib/buildbot/workers/debian-stadler-sparc64/clang-sparc64-linux-multistage/llvm/compiler-rt/lib/sanitizer_common -Iinclude -I/var/lib/buildbot/workers/debian-stadler-sparc64/clang-sparc64-linux-multistage/llvm/llvm/include -I/var/lib/buildbot/workers/debian-stadler-sparc64/clang-sparc64-linux-multistage/llvm/compiler-rt/lib/sanitizer_common/.. -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -std=c++14 -Wno-unused-parameter -O3   -m32 -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -nostdinc++ -fno-rtti -Wframe-larger-than=570 -Wglobal-constructors -DSANITIZER_SUPPORTS_WEAK_HOOKS=0 -UNDEBUG -std=c++14 -MD -MT projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizerNoHooks.sparc.dir/sanitizer_stackdepot.cpp.o -MF projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizerNoHooks.sparc.dir/sanitizer_stackdepot.cpp.o.d -o projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizerNoHooks.sparc.dir/sanitizer_stackdepot.cpp.o -c /var/lib/buildbot/workers/debian-stadler-sparc64/clang-sparc64-linux-multistage/llvm/compiler-rt/lib/sanitizer_common/sanitizer_stackdepot.cpp
In file included from /var/lib/buildbot/workers/debian-stadler-sparc64/clang-sparc64-linux-multistage/llvm/compiler-rt/lib/sanitizer_common/sanitizer_stackdepot.cpp:17:
In file included from /var/lib/buildbot/workers/debian-stadler-sparc64/clang-sparc64-linux-multistage/llvm/compiler-rt/lib/sanitizer_common/sanitizer_stackdepotbase.h:16:
In file included from /usr/include/stdio.h:870:
/usr/include/bits/stdio-ldbl.h:26:20: error: cannot apply asm label to function after its first use
__LDBL_REDIR_DECL (vfprintf)
~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/usr/include/sys/cdefs.h:467:26: note: expanded from macro '__LDBL_REDIR_DECL'
  extern __typeof (name) name __asm (__ASMNAME ("__nldbl_" #name));
                         ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

See: http://lab.llvm.org:8014/#/builders/113/builds/37

The issue has existed for a while but I never actually reported it.

**Comment by brad0** [comment]
What happens with Clang 14.0.0 or newer in use?

**Comment by brad0** [comment]
It would be nice to have some feedback from Linux/Sparc with Clang 15.

**Comment by glaubitz** [comment]
The CI results can be found here: https://lab.llvm.org/staging/#/builders/113

The instance was missing the `crypt.h` header which is why I installed the `libcrypt-dev` package.

Multistage builds are fine as long as the compiler-rt build is limited to the native architecture which is what we are doing in Debian:

https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/blob/snapshot/debian/rules#L204

```
ifneq (,$(filter $(DEB_HOST_ARCH),sparc64))
  STAGE_ALL_CMAKE_EXTRA += -DLLVM_HOST_TRIPLE=sparc64-linux-gnu
  STAGE_ALL_CMAKE_EXTRA += -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON
  STAGE_ALL_CMAKE_EXTRA += -DLLVM_PARALLEL_LINK_JOBS=4
endif
```

However, I don't know how to configure this for the CI. FWIW, the mips64el buildbot has a similar problem (but not the same) with the 32-bit compiler-rt build failing on the 64-bit host.

There is also work being done in `glibc` to alleviate the issue:

> https://sourceware.org/bugzilla/show_bug.cgi?id=27558
> https://github.com/zatrazz/glibc/tree/azanella/redir-refactor

**Comment by MaskRay** [comment]
@zatrazz

**Comment by rorth** [comment]
> It would be nice to have some feedback from Linux/Sparc with Clang 15.

I believe all but one (or two) issues with Debian/sparc64 are now resolved on `main`.  They could be backported to the `release/15.x` branch if desired:
- [clang: link libatomic for 32-bit Linux/sparc](https://reviews.llvm.org/D130569)
- [same for compiler-rt](https://reviews.llvm.org/D130571)
- perhaps [clang: default to `-mcpu=v9` for 32-bit Linux/sparc](https://reviews.llvm.org/D130688) if this can be resolved in time

One outstanding issue is the `__asm` issue that started this bug.  For now, I've just hacked around this by having `clang` always predefine `__NO_INLINE__` on Linux/sparc.  I haven't submitted the patch yet because it's no more than a bad hack, but some resolution is necessary to have `compiler-rt` build at all.

**Comment by glaubitz** [comment]
> One outstanding issue is the `__asm` issue that started this bug. For now, I've just hacked around this by having `clang` always predefine `__NO_INLINE__` on Linux/sparc. I haven't submitted the patch yet because it's no more than a bad hack, but some resolution is necessary to have `compiler-rt` build at all.

This might be resolved automatically once the glibc header changes by @zatrazz are merged into glibc upstream.

**Comment by brad0** [comment]
> > It would be nice to have some feedback from Linux/Sparc with Clang 15.
> 
> I believe all but one (or two) issues with Debian/sparc64 are now resolved on `main`. They could be backported to the `release/15.x` branch if desired:
> 
> * [clang: link libatomic for 32-bit Linux/sparc](https://reviews.llvm.org/D130569)
> * [same for compiler-rt](https://reviews.llvm.org/D130571)
> * perhaps [clang: default to `-mcpu=v9` for 32-bit Linux/sparc](https://reviews.llvm.org/D130688) if this can be resolved in time
> 
> One outstanding issue is the `__asm` issue that started this bug. For now, I've just hacked around this by having `clang` always predefine `__NO_INLINE__` on Linux/sparc. I haven't submitted the patch yet because it's no more than a bad hack, but some resolution is necessary to have `compiler-rt` build at all.

I submitted them before even seeing this comment. Thanks.

**Comment by rorth** [comment]
> > > It would be nice to have some feedback from Linux/Sparc with Clang 15.

> I submitted them before even seeing this comment. Thanks.

Great, thanks.  FWIW I've posted a `sparc64-unknown-linux-gnu` tarball of llvm-15.0.0-rc1 today, with the first two patches and the `__NO_INLINE__` hack applied locally, including all but `openmp` and `lldb` (no sparc support in either).

**Comment by rorth** [comment]
> > One outstanding issue is the `__asm` issue that started this bug. For now, I've just hacked around this by having `clang` always predefine `__NO_INLINE__` on Linux/sparc. I haven't submitted the patch yet because it's no more than a bad hack, but some resolution is necessary to have `compiler-rt` build at all.
> 
> This might be resolved automatically once the glibc header changes by @zatrazz are merged into glibc upstream.

True, but how long will this take first to get into upstream `glibc` and then into Debian packages?  While I could even patch the system header on my local T5220 LDom, that's not an option on systems I don't own (like `gcc202` in the cfarm).

**Comment by brad0** [comment]
> > > > It would be nice to have some feedback from Linux/Sparc with Clang 15.
> 
> > I submitted them before even seeing this comment. Thanks.
> 
> Great, thanks. FWIW I've posted a `sparc64-unknown-linux-gnu` tarball of llvm-15.0.0-rc1 today, with the first two patches and the `__NO_INLINE__` hack applied locally, including all but `openmp` and `lldb` (no sparc support in either).

I saw that, that is a good step forward. Hopefully the issue with glibc can be fixed soon enough.

**Comment by brad0** [comment]
@zatrazz

**Comment by glaubitz** [comment]
> True, but how long will this take first to get into upstream `glibc` and then into Debian packages?

I could actually build a patched glibc package just for the sparc64 port, once I know that the patches by @zatrazz fix the issue.

My main problem is that so far I was unable to successfully build clang against a patched version of glibc.

> While I could even patch the system header on my local T5220 LDom, that's not an option on systems I don't own (like `gcc202` in the cfarm).

I have full control over gcc202 and the LLVM CI machine, so I could install a patched package them.

**Comment by brad0** [comment]
> I submitted them before even seeing this comment. Thanks.

and they have all been merged in.

**Comment by brad0** [comment]
If I'm not mistaken the root issue was fixed in glibc and that 1e56821bac02a5d3c6249bbf3ef43b8b569d2551 should now be reverted.

**Comment by brad0** [comment]
Looking at the 2.34 branch I see these backports..

https://github.com/bminor/glibc/commit/2a44960cbc78713c6a2721683a4319d50e71a01f
https://github.com/bminor/glibc/commit/b41c535f46e7e7bbd8ff2ac68b94c2348e2f66e4

**Comment by brad0** [comment]
@rorth

**Comment by thesamesam** [comment]
Based on https://github.com/llvm/llvm-project-release-prs/pull/150#issuecomment-1255001928, does this mean there's nothing to do for 15.x backporting?

**Comment by thesamesam** [comment]
Thanks for explaining @brad0. We've got those fixes in Gentoo as we regularly roll new patches from the release branches. I'll ask some Debian folks if they've got it covered now.

**Comment by glaubitz** [comment]
Debian is already shipping glibc 2.36, so the fixes should be already rolled out.

**Comment by nikic** [comment]
FYI there is one more potential glibc issue with syslog, see https://bugzilla.redhat.com/show_bug.cgi?id=2140618.

**Comment by brad0** [comment]
> Debian is already shipping glibc 2.36, so the fixes should be already rolled out.

From the looks of it only the first patch made it out to 2.36. The second patch missed the release and will be out in 2.36.1.

From the 2.36 branch..
https://github.com/bminor/glibc/commit/d0fa09a7701956036ff36f8ca188e9fff81553d8

Commited in Aug well after the 2.36 release in July.

https://github.com/bminor/glibc/commit/3c791f2031ca8f6b99e96b774ed1c505ceb93595

**Comment by thesamesam** [comment]
I asked in #debian-glibc on OFTC and @aurel32 said:
```
<sam_> we were discussing an issue that ended up being a glibc problem on sparc, I've got no idea if debian has pulled in the patches already, but in case you haven't: https://github.com/llvm/llvm-project/issues/47994#issuecomment-1312914594
<aurel32> sam_: from what I can see those patches went into the upstream stable tree and on debian have been added into 2.34-8 released on 2022-09-10
```

**Comment by brad0** [comment]
Being that the root issue has been resolved I am going to revert the workaround.
