### ISSUE TITLE
clang-format does not transfer brace to the new line for union, if flag Allman is set

### ISSUE THREAD

**Issue by wertyuiopsdfghjklxcvbn** [llvm/llvm-project#48]
Hi. If I set flag BreakBeforeBraces: Allman, clang-format does not transfer brace to the new line for union. Also if I use BasedOnStyle: Mozilla without anything else, it works correctly for union.
clang-format version 9.0.0 (tags/RELEASE_900/final)

**Comment by modocache** [comment]
Yeah, I can confirm this:

```
$ echo "union U { int a; int b; }" | clang-format -style="{BreakBeforeBraces: Allman}"
union U {
  int a;
  int b;
}
```

```
$ echo "union U { int a; int b; }" | clang-format -style="{BasedOnStyle: Mozilla}"
union U
{
  int a;
  int b;
}
```

I'm not an expert on clang-format, but the following works as expected, so maybe there's something weird about the handling of `BreakBeforeBraces: Allman` specifically:

```
$ echo "union U { int a; int b; }" | clang-format -style="{ BreakBeforeBraces: Custom, BraceWrapping: { AfterUnion: true } }"
union U
{
  int a;
  int b;
}
```

**Comment by sylvestre** [comment]
Please use the bug tracker:
http://llvm.org/bugs/

**Comment by jyknight** [comment]
@sylvestre We're allowing folks to report bugs here also.

**Comment by wertyuiopsdfghjklxcvbn** [comment]
I have already opened the issue here:
https://bugs.llvm.org/show_bug.cgi?id=44220

**Comment by jyknight** [comment]
Thank you -- re-closing here, then!
