### ISSUE TITLE
Default to C11 standard and missing __STDC_NO_THREADS__ ( windows)

### ISSUE THREAD

**Issue by P-p-H-d** [llvm/llvm-project#48048]
|  |  |
| --- | --- |
| Bugzilla Link | [48704](https://llvm.org/bz48704) |
| Version | 11.0 |
| OS | Windows XP |
| CC | @AaronBallman,@DougGregor,@zmodem,@nico,@zygoloid,@rnk |

## Extended Description 
Since the switch to default to C11, compliant program fails to build **by default** (without forcing another mode) on windows:

  #if defined(__STDC_VERSION__) && \
      (__STDC_VERSION__ >= 201102L) && \
      !defined(__STDC_NO_THREADS__)
  #  include <threads.h>
  #endif

[ build with only "clang.exe -c test.c"  ]

It is probably the same for other predefined macros.

This may be a library issue, but is it ok to default to C11 if there is known library issue for such support?

**Comment by zmodem** [comment]
> Something like: https://reviews.llvm.org/D112081

That landed in https://reviews.llvm.org/rGbbc690c57213054907284d8964dc0487d38fc57a
