### ISSUE TITLE
no constexpr default constructor if member inherits a constexpr default constructor

### ISSUE THREAD

**Issue by c44d6195-dfe2-40f4-a90f-bebb7462f3a2** [llvm/llvm-project#48107]
|  |  |
| --- | --- |
| Bugzilla Link | [48763](https://llvm.org/bz48763) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie,@DougGregor,@zygoloid |

## Extended Description 
https://godbolt.org/z/G8vY63
```cpp
struct A {
  constexpr A() {}
};

struct B : A {
  using A::A;
  constexpr B(int) {}
};

struct C {
  B b;
};

constexpr C v;
```
Fails on all the version of clang I tested.

**Comment by Endilll** [comment]
Seems to be fixed in Clang 12: https://godbolt.org/z/f6cGdWWbf
