### ISSUE TITLE
coroutine_handle::done() == false after promise's unhandled_exception() has thrown

### ISSUE THREAD

**Issue by mkrausex** [llvm/llvm-project#48114]
|  |  |
| --- | --- |
| Bugzilla Link | [48770](https://llvm.org/bz48770) |
| Version | trunk |
| OS | Linux |
| Attachments | [Reproducer](https://user-images.githubusercontent.com/93435752/143761640-9de22ed6-ad7a-44fe-a0cf-9973369abc14.gz) |
| CC | @DougGregor,@zygoloid,@yuanfang-chen |

## Extended Description 

[dcl.fct.def.coroutine]/14 says: "If the evaluation of the expression promise.unhandled_exception() exits via
an exception, the coroutine is considered suspended at the final suspend point". So, after this exception has
propagated to the caller, I expect that the coroutine_handle's done() function returns true (because of
[coroutine.handle.observers]/3 "Returns: true if the coroutine is suspended at its final suspend point,
otherwise false").

However, the compiler for which I am reporting this makes done() return false in this situation. See the
attached example code (my expectation is 1 instead of 0 in the final two lines of output).

By the way, gcc 10.2, gcc trunk, clang 10.0.0, clang trunk, msvc 14.28 all behave in this way. A fix for msvc
is already underway: https://developercommunity.visualstudio.com/content/problem/1305540/coroutine-handledone-false-after-promises-unhandle.html

**Comment by ChuanqiXu9** [comment]
This should be fixed after: https://reviews.llvm.org/rG320e4efe99d395fcdbc61a65295ecc8b63c9799f. See https://godbolt.org/z/rrTn3Th5x for example.
