### ISSUE TITLE
Review options between using CodeBeads v.s. TSFlags for encoding M68k instructions

### ISSUE THREAD

**Issue by mshockwave** [llvm/llvm-project#48136]
|  |  |
| --- | --- |
| Bugzilla Link | [48792](https://llvm.org/bz48792) |
| Version | trunk |
| OS | All |
| Blocks | llvm/llvm-project#48135  |
| CC | @glaubitz,@RKSimon,@mshockwave,@ricky26 |

## Extended Description 
Normally a backend uses `MCInstrDesc::TSFlags`, a 64-bits bit vector, to carry all the instructions' encoding info. However, M68k's current encoding scheme -- which might not be the optimal one -- requires at least 24 bytes to carry all the necessary info. As a workaround, M68k created a specialized TableGen backend, CodeBeads, to generate an auxiliary encoding table that can carry arbitrary length instruction encodings.

Nevertheless, we always prefer to reuse the existing infrastructures. Therefore this bug is used for tracking the status of refactoring M68k's current encoding scheme into a more concise form. For example, try to fit every encoding info into the 64-bits `TSFlags`, or use `TSFlags` as a index/pointer to another auxiliary encoding table.

For more discussion on this topic, please refer to https://reviews.llvm.org/D88385.

**Comment by mshockwave** [comment]
An on-going patch series is trying to solve this issue: https://reviews.llvm.org/D115128

**Comment by mshockwave** [comment]
I finally had a working tree / preview of using VarLenCodeEmitterGen to replace _all_ instructions: https://github.com/M680x0/M680x0-mono-repo/tree/dev-stream-code-emitter

There are still lots of minors issues need to be ironed out in that tree but I think the VarLenCodeEmitterGen approach is pretty promising.

**Comment by RKSimon** [comment]
@mshockwave Can this ticket be closed?

**Comment by mshockwave** [comment]
Closed by VarLenCodeEmitter introduced in 31f9519d48c26bd542253cc20dc333732c991332

The refactoring in M68k was wrapped up by d68b4dc0a88e7d23090db27613325e35a0ed2799
