### ISSUE TITLE
Pass modifies its input and doesn't report it: Global Value Numbering

### ISSUE THREAD

**Issue by 009b8ea0-6754-41bc-becf-d830f82bdd65** [llvm/llvm-project#48146]
|  |  |
| --- | --- |
| Bugzilla Link | [48802](https://llvm.org/bz48802) |
| Version | trunk |
| OS | Linux |
| Attachments | [IR reproducer.](https://user-images.githubusercontent.com/92601278/143761652-8df98658-cddf-4e0b-b406-2b02cd1a013e.gz) |
| CC | @dstenb,@dwblaikie |

## Extended Description 

Requires an expensive checks build to reproduce.

LLVM commit: 4fd77668b2cc215f0605fe20bb989b90b29f4346

$ ./build-expensive/bin/opt -S -gvn gvn.ll
Pass modifies its input and doesn't report it: Global Value Numbering
Pass modifies its input and doesn't report it
UNREACHABLE executed at /home/david/monorepo/llvm/lib/IR/LegacyPassManager.cpp:1445!

**Comment by mikaelholmen** [comment]
This doesn't crash anymore after https://github.com/llvm/llvm-project/commit/e7618a6361f856a089d6f9eb476f18a9bf4643b8 so I'll close.
