### ISSUE TITLE
apt release version mismatches with https://releases.llvm.org/ for llvm 11 release

### ISSUE THREAD

**Issue by 195adae6-08c2-47ac-bd06-778979fd4945** [llvm/llvm-project#48159]
|  |  |
| --- | --- |
| Bugzilla Link | [48815](https://llvm.org/bz48815) |
| Version | unspecified |
| OS | All |

## Extended Description 
According to https://releases.llvm.org/ last release is 11.0.1 , but apt expects 11.1.0 , for reference: https://travis-ci.com/github/KhronosGroup/SPIRV-LLVM-Translator/jobs/472611318#L484

**Comment by sylvestre** [comment]
correct, it was for preparation!
