### ISSUE TITLE
Concepts with parameter pack not at end silently ignores errors when used

### ISSUE THREAD

**Issue by ec7eeb7f-58bd-4c66-a038-16c3e01dbcce** [llvm/llvm-project#48182]
|  |  |
| --- | --- |
| Bugzilla Link | [48838](https://llvm.org/bz48838) |
| Version | trunk |
| OS | All |
| Attachments | [Patch to reject concepts with parameter packs not at the end](https://user-images.githubusercontent.com/95090548/143761662-08fe1b2d-9e1f-4e2d-8128-4a86af355e69.gz) |
| CC | @zygoloid |

## Extended Description 

There are no errors or warnings compiling the following with `clang++ -std=c++20 -fsyntax-only`:

    template<typename, typename..., typename = int>
    concept invalid = true;

    template<typename> requires invalid<int>
    no errors are printed
    ;

    static_assert(invalid<int> also here ;

    int main() {
        bool b;
        b = invalid<int> not just in declarations;
        return b;
    }

This happens because this assumption is violated with concepts: https://github.com/llvm/llvm-project/blob/39239f9b5666bebb059fa562badeffb9f1c3afab/clang/lib/Sema/SemaTemplate.cpp#L5756-L5760 and no diagnosis is printed beforehand

I have attached a patch that makes concepts like `invalid` which have a parameter pack not at the end an error.

There is currently no wording in the standard that makes these concepts ill-formed (The current C++20 [temp.param]p14 only mentions "primary class template, primary variable template, or alias template"), but I think this is an oversight.

**Comment by luken-google** [comment]
Patch out for review at https://reviews.llvm.org/D138210

**Comment by luken-google** [comment]
Fixed in afd800fc5679ccfe6f32b097586c658628500867
