### ISSUE TITLE
Rejects-valid for overloaded hidden non-template friend functions with mutually exclusive requires-clauses

### ISSUE THREAD

**Issue by 049b648d-2acd-4c6a-a3e9-25ddafb13875** [llvm/llvm-project#48216]
|  |  |
| --- | --- |
| Bugzilla Link | [48872](https://llvm.org/bz48872) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
As per [defns.signature.friend] in N4861, the signature of a non-template friend function includes a trailing requires-clause, if it is present. Moreover, [over.dcl]/1 states that two function declarations declare different functions if they have different trailing requires-clauses.

The following example fails to compile for Clang (-std=c++2b, 12.0.0 trunk):

```cpp
 #include <iostream>

 template<int N>
 struct S {
     friend void foo(int) requires (N == 1) { std::cout << "1\n"; }
     friend void foo(int) requires (N == 2) { std::cout << "2\n"; }
     operator int() const { return 0; }
 };

 int main() {
     foo(S<1>{}); // 1
     foo(S<2>{});
       // error: definition with same mangled 
       //        name '...' as another definition
 }
```

which is arguably incorrect, as the two, separate (by separate requires-clauses) friend declarations (that are also definitions) should not generate the same mangled name.

---

(Constrained hidden non-template friends was added as per NS US115 of P2103R0; http://open-std.org/JTC1/SC22/WG21/docs/papers/2020/p2103r0.html)

**Comment by zygoloid** [comment]
I believe the current thinking on a mangling rule here is described in this comment: https://github.com/itanium-cxx-abi/cxx-abi/issues/24#issuecomment-934977198

**Comment by erichkeane** [comment]
I did a bit of work for that Itanium ABI issue at one point (though my patch desperately needs a rebase, since most of it is invalid now that we do the pre-calculation of constrained-friends), but it was held up on @rjmccall wanting Itanium to accept that comment first.

**Comment by erichkeane** [comment]
Commit I was working on: https://reviews.llvm.org/D126818

**Comment by erichkeane** [comment]
Just did some additional work on the patch, so it should be ready for review.
