### ISSUE TITLE
Accepts-invalid for requires-clause on non-templated function

### ISSUE THREAD

**Issue by 049b648d-2acd-4c6a-a3e9-25ddafb13875** [llvm/llvm-project#48214]
|  |  |
| --- | --- |
| Bugzilla Link | [48870](https://llvm.org/bz48870) |
| Version | 11.0 |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
As per [dcl.decl]/4 in N4861, a requires-clause shall be present only if the declarator declares a templated function.

However, clang accepts the follow program:

 void f() requires true { }
 int main() { f(); }

and we may moreover note that constraint checking is actually enforced, as the following program is rejected (for the wrong reasons) due to overload resolution failure

 void f() requires false { }
 int main() { f(); }  //  // error: no matching function for call to 'f'

whereas the constraints have not been added to the function's signature (which is correct, as per [defns.signature]):

 void f() requires true { }
 void f() requires false { }
   // ^ error: definition with same mangled name '...' as another definition

---

(It may be that the implementation was base on [dcl.decl]/4 from the earlier draft of N4810, which had a weaker requirement: allowing requires-clauses on declarators that were functions).

**Comment by royjacobson** [comment]
Fixed (https://reviews.llvm.org/D125711)
