### ISSUE TITLE
consteval function not allowed in default argument to constexpr constructor

### ISSUE THREAD

**Issue by andreasfertig** [llvm/llvm-project#48230]
|  |  |
| --- | --- |
| Bugzilla Link | [48886](https://llvm.org/bz48886) |
| Version | 11.0 |
| OS | All |
| CC | @AaronBallman,@zygoloid |

## Extended Description 
Hello,

the following valid code is currently rejected by Clang 11 and trunk (https://godbolt.org/z/645McM):
```
consteval int Fun() { return 0; }

struct Test {
  constexpr Test(int loc = Fun()) {}
};

Test t{};
```
The error is:
```
<source>:4:28: error: cannot take address of consteval function 'Fun' outside of an immediate invocation
  constexpr Test(int loc = Fun()) {}
                           ^
<source>:1:15: note: declared here
consteval int Fun() { return 0; }
              ^
1 error generated.
Compiler returned: 1
```

I had a brief communication with Richard Smith who confirmed that the code above is valid.

I assume this bug is similar to llvm/llvm-project#47058 

Best,

   Andreas

**Comment by Izaron** [comment]
Thanks for the issue! I suggested a possible fix, which affects the ParmVarDecl's custom AST visitor - https://reviews.llvm.org/D119646

**Comment by jyknight** [comment]
Note that this bug is causing std::source_location in libstdc++ to be broken -- and also effectively blocking source_location for libc++, https://reviews.llvm.org/D120634 (not much point in committing it if nobody can use it).

**Comment by tstellar** [comment]
@jwakely
