### ISSUE TITLE
Incorrect alignment of __attribute__((aligned)) enum

### ISSUE THREAD

**Issue by mahkoh** [llvm/llvm-project#48234]
|  |  |
| --- | --- |
| Bugzilla Link | [48890](https://llvm.org/bz48890) |
| Version | 11.0 |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Consider
```cpp
enum __attribute__((aligned(8))) E {
        A = 1,
};

int g(void) {
    return _Alignof(enum E);
}
```
gcc returns 4, clang returns 8 on x86_64-unknown-linux-gnu. Gcc appears to ignored this attribute on enums.

**Comment by Endilll** [comment]
GCC respects the attribute since 6: https://godbolt.org/z/hqceEqqs6
