### ISSUE TITLE
Missed optimization: llvm unable to remove bounds check

### ISSUE THREAD

**Issue by 24ae4267-5921-45a9-a006-c88f1b8f1b03** [llvm/llvm-project#48253]
|  |  |
| --- | --- |
| Bugzilla Link | [48909](https://llvm.org/bz48909) |
| Version | unspecified |
| OS | All |
| CC | @davidbolvansky,@fhahn,@LebedevRI,@nelhage,@nikic |

## Extended Description 
https://godbolt.org/z/vEfPYj (also below)

LLVM should be able to remove the branch that leads to the call to abort() -- data.length is known to be the same as block_len, and block_len is known not to be 0. Therefore llvm should know that block_len - is always < data.length.

Source:

#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>

typedef struct {
    uint8_t *data;
    size_t length;
} slice;

static inline uint8_t subscript(slice data, size_t index) {
    if (index >= data.length) {
        abort();
    }
    return data.data[index];
}

bool check_padding(slice data, size_t block_len) {
    if (data.length != block_len || block_len == 0) {
        return false;
    }

    uint8_t pad_size = subscript(data, block_len - 1);
    return pad_size > 7;
}

generated assembly:

check_padding:                          # @&#8203;check_padding
        push    rax
        xor     eax, eax
        cmp     rsi, rdx
        jne     .LBB0_4
        test    rdx, rdx
        je      .LBB0_4
        test    rsi, rsi
        je      .LBB0_5
        cmp     byte ptr [rsi + rdi - 1], 7
        seta    al
.LBB0_4:
        pop     rcx
        ret
.LBB0_5:
        call    abort

**Comment by fhahn** [comment]
After 66400fc, this should get optimized as expected with `-mllvm -enable-constraint-elimination`: https://godbolt.org/z/ev51WehaM

**Comment by alex** [comment]
Great, thank you! I guess this will be closed when #49344 is completed?

**Comment by fhahn** [comment]
> Great, thank you! I guess this will be closed when #49344 is completed?

Yes. I' planning to propose the pass to be enabled by default soon.
