### ISSUE TITLE
float to __int128 conversions completely broken on Mingw

### ISSUE THREAD

**Issue by 20daabd2-3a10-44b0-bc2c-f02427e4a60a** [llvm/llvm-project#48284]
|  |  |
| --- | --- |
| Bugzilla Link | [48940](https://llvm.org/bz48940) |
| Version | 11.0 |
| OS | Windows NT |
| CC | @DougGregor,@mstorsjo,@zygoloid |

## Extended Description 
Converting a float (or indeed double) to an __int128 results in a garbage result, test case:

#include <assert.h>
#include <type_traits>
#include <cmath>

template <class T>
struct wraps
{
   T val;
   template <class U>
   wraps(U val, typename std::enable_if<std::is_floating_point<U>::value>::type* = 0)
   : val(static_cast<T>(std::fabs(val))){}

   T get()const { return val; }
};

int main()
{
   float f(2);
   wraps<unsigned __int128> w(f);

   assert(w.get() == 2);  // always fails for __int128

   return 0;
}

Tested compiler was:

$ clang++ --version
clang version 11.0.0 (https://github.com/msys2/MINGW-packages 587690290e514a13a7a61be3f9116a1d042d2e4e)
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:\compilers\msys64\mingw64\bin

This is a showstopper for Boost.Multiprecision on Mingw.  There are no issues on Ubuntu Linux or with XCode clang that I can see.

**Comment by mahtohappy** [comment]
Hi, I think this can be closed, fixed in LLVM 14 release.
