### ISSUE TITLE
Dereferencing unsigned __int128 segfaults on Mingw

### ISSUE THREAD

**Issue by 20daabd2-3a10-44b0-bc2c-f02427e4a60a** [llvm/llvm-project#48285]
|  |  |
| --- | --- |
| Bugzilla Link | [48941](https://llvm.org/bz48941) |
| Version | 11.0 |
| OS | Windows NT |
| CC | @DougGregor,@zygoloid |

## Extended Description 
This is another showstopper from Boost.Multiprecision, dereferencing an (unsigned) __int128 segfaults.  Test case is:

#include <assert.h>
#include <type_traits>
#include <cmath>
#include <limits>

template <class T>
struct wraps
{
   T val;
   template <class U>
   wraps(U val, typename std::enable_if<std::is_floating_point<U>::value>::type* = 0)
   : val(static_cast<T>(std::fabs(val))){}

   wraps(int i) : val(i) {}

   T get()const { return val; }

   const T* limbs()const { return &val; }
   T* limbs() { return &val; }

   template <class R>
   void convert_to(R* result)
   {
      if (*limbs() > (std::numeric_limits<R>::max)())
      {
         if (get() < 0)
         {
            *result = (std::numeric_limits<R>::min)();
         }
         else
         {
            *result = (std::numeric_limits<R>::max)();
         }
      }
      else
      {
         *result = static_cast<R>(*limbs());
      }
   }
};

int main()
{
   float f;
   wraps<unsigned __int128> w(2);
   w.convert_to(&f);

   assert(f == 2);

   return 0;
}

With:

$ clang++ --version
clang version 11.0.0 (https://github.com/msys2/MINGW-packages 587690290e514a13a7a61be3f9116a1d042d2e4e)
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:\compilers\msys64\mingw64\bin

**Comment by Endilll** [comment]
Both minimized examples do not reproduce using Clang 10 and 11:
https://godbolt.org/z/1cqh89PGE
https://godbolt.org/z/hh6r8WMzh
