### ISSUE TITLE
Release gives Segmentation fault when run with c++ instead of clang++.

### ISSUE THREAD

**Issue by 3b3be5bc-be97-4c5a-a058-de8ddaf7c081** [llvm/llvm-project#48310]
|  |  |
| --- | --- |
| Bugzilla Link | [48966](https://llvm.org/bz48966) |
| Version | 11.0 |
| OS | Linux |
| CC | @hubert-reinterpretcast |

## Extended Description 
Release gives Segmentation fault when run with c++ instead of clang++.

c++ --version
c++ (Ubuntu 10.2.0-13ubuntu1) 10.2.0

clang++ --version
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 7e99bddfeaab2713a8bb6ca538da25b66e6efc59)

tail testing.12.0.0-rc1.log
[  7%] Built target obj.llvm-tblgen
make[1]: Leaving directory '/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase1/Release/llvmCore-12.0.0-rc1.obj'
make: *** [Makefile:152: all] Error 2

grep -n 'error: ' testing.12.0.0-rc1.log
1549:/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/../libcxx/include/utility:341:47: internal compiler error: Segmentation fault
1558:/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/../libcxx/include/utility:341:47: internal compiler error: Segmentation fault
1568:/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/../libcxx/include/utility:341:47: internal compiler error: Segmentation fault

Containing lines in testing.12.0.0-rc1.log
[  1%] Copying compiler-rt's sanitizer/ubsan_interface.h...
make -f projects/compiler-rt/lib/ubsan/CMakeFiles/RTUbsan_cxx.x86_64.dir/build.make projects/compiler-rt/lib/ubsan/CMakeFiles/RTUbsan_cxx.x86_64.dir/depend
cd /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase1/Release/llvmCore-12.0.0-rc1.obj/lib/Demangle && /usr/bin/c++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase1/Release/llvmCore-12.0.0-rc1.obj/lib/Demangle -I/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/llvm/lib/Demangle -I/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase1/Release/llvmCore-12.0.0-rc1.obj/include -I/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/llvm/include  -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -ffunction-sections -fdata-sections -O3 -DNDEBUG    -fno-exceptions -fno-rtti -std=c++14 -o CMakeFiles/LLVMDemangle.dir/ItaniumDemangle.cpp.o -c /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/llvm/lib/Demangle/ItaniumDemangle.cpp
cd /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase1/Release/llvmCore-12.0.0-rc1.obj/projects/compiler-rt/include && /usr/bin/cmake -E copy_if_different /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/compiler-rt/include/sanitizer/ubsan_interface.h /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase1/Release/llvmCore-12.0.0-rc1.obj/./lib/clang/12.0.0/include/sanitizer/ubsan_interface.h
make[2]: Entering directory '/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase1/Release/llvmCore-12.0.0-rc1.obj'
cd /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase1/Release/llvmCore-12.0.0-rc1.obj && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/llvm /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/compiler-rt/lib/ubsan /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase1/Release/llvmCore-12.0.0-rc1.obj /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase1/Release/llvmCore-12.0.0-rc1.obj/projects/compiler-rt/lib/ubsan /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase1/Release/llvmCore-12.0.0-rc1.obj/projects/compiler-rt/lib/ubsan/CMakeFiles/RTUbsan_cxx.x86_64.dir/DependInfo.cmake --color=
In file included from /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/../libcxx/include/memory:674,
                 from /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/src/include/atomic_support.h:17,
                 from /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/src/cxa_default_handlers.cpp:18:
/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/../libcxx/include/utility: In substitution of ‘template<class _T1, class _T2> template<int& ...<anonymous> > static constexpr bool std::__1::pair<_T1, _T2>::_CheckArgs::__enable_implicit_default() [with int& ...<anonymous> = <missing>; _T1 = {}; _T2 = <missing>]’:
/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/../libcxx/include/utility:341:47:   required from here
/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/../libcxx/include/utility:341:47: internal compiler error: Segmentation fault
  341 |               && !__enable_implicit_default<>();
      |                                               ^
[  1%] Building CXX object projects/compiler-rt/lib/interception/CMakeFiles/RTInterception.i386.dir/interception_linux.cpp.o
In file included from /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/../libcxx/include/memory:674,
                 from /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/src/include/atomic_support.h:17,
                 from /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/src/cxa_default_handlers.cpp:18:
/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/../libcxx/include/utility: In substitution of ‘template<class _T1, class _T2> template<int& ...<anonymous> > static constexpr bool std::__1::pair<_T1, _T2>::_CheckArgs::__enable_implicit_default() [with int& ...<anonymous> = <missing>; _T1 = {}; _T2 = <missing>]’:
/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/../libcxx/include/utility:341:47:   required from here
/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/../libcxx/include/utility:341:47: internal compiler error: Segmentation fault
  341 |               && !__enable_implicit_default<>();
      |                                               ^
cd /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase1/Release/llvmCore-12.0.0-rc1.obj/projects/compiler-rt/lib/interception && /usr/bin/c++  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase1/Release/llvmCore-12.0.0-rc1.obj/projects/compiler-rt/lib/interception -I/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/compiler-rt/lib/interception -I/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase1/Release/llvmCore-12.0.0-rc1.obj/include -I/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/llvm/include -I/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/compiler-rt/lib/interception/..  -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -ffunction-sections -fdata-sections -Wall -std=c++14 -Wno-unused-parameter -O3 -DNDEBUG    -m32 -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fvisibility=hidden -fno-lto -O3 -g -Wno-variadic-macros -nostdinc++ -fno-rtti -std=c++14 -o CMakeFiles/RTInterception.i386.dir/interception_linux.cpp.o -c /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/compiler-rt/lib/interception/interception_linux.cpp
In file included from /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/../libcxx/include/algorithm:652,
                 from /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/src/demangle/StringView.h:17,
                 from /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/src/demangle/ItaniumDemangle.h:22,
                 from /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/src/cxa_demangle.cpp:13:
/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/../libcxx/include/utility: In substitution of ‘template<class _T1, class _T2> template<int& ...<anonymous> > static constexpr bool std::__1::pair<_T1, _T2>::_CheckArgs::__enable_implicit_default() [with int& ...<anonymous> = <missing>; _T1 = {}; _T2 = <missing>]’:
/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/../libcxx/include/utility:341:47:   required from here
/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/libcxxabi/../libcxx/include/utility:341:47: internal compiler error: Segmentation fault
  341 |               && !__enable_implicit_default<>();
      |                                               ^
[  1%] Building CXX object projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.i386.dir/sanitizer_linux_libcdep.cpp.o

**Comment by Endilll** [comment]
I don't think this is relevant anymore.
