### ISSUE TITLE
[AVR] Bad optimization of multiplication when mul instruction is available

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#48325]
|  |  |
| --- | --- |
| Bugzilla Link | [48981](https://llvm.org/bz48981) |
| Version | trunk |
| OS | Linux |

## Extended Description 
int square(int num)
{
    return num * num;
}

GCC -O3 generates this:

square(int):
  movw r18,r24
  mul r18,r18
  movw r24,r0
  mul r18,r19
  add r25,r0
  add r25,r0
  clr r1
  ret

LLVM generates this:

square(int):
  muls r25, r24
  mov r18, r0
  clr r1
  muls r24, r25
  mov r19, r0
  clr r1
  mul r24, r24
  mov r20, r1
  clr r1
  add r20, r19
  add r20, r18
  lsl r20
  rol r21
  lsl r20
  rol r21
  lsl r20
  rol r21
  lsl r20
  rol r21
  lsl r20
  rol r21
  lsl r20
  rol r21
  lsl r20
  rol r21
  lsl r20
  rol r21
  mov r24, r0
  clr r25
  or r24, r20
  or r25, r21
  ret

**Comment by benshi001** [comment]
Maybe we need to make a new pseudo `(mul (outs i16), (ins i16, i16))` for that ?

**Comment by benshi001** [comment]
current llvm-16 generates

```
        muls    r25, r24
        mov     r18, r0
        clr     r1
        mul     r24, r24
        mov     r20, r1
        clr     r1
        add     r20, r18
        add     r20, r18
        mov     r21, r20
        clr     r20
        mov     r24, r0
        clr     r25
        or      r24, r20
        or      r25, r21
        ret
```

**Comment by benshi001** [comment]
AVR has gained great optimization on 16-bit mulplication.
