### ISSUE TITLE
[Sparc] Failure to ever optimize out function prologue

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#48327]
|  |  |
| --- | --- |
| Bugzilla Link | [48983](https://llvm.org/bz48983) |
| Version | trunk |
| OS | Linux |

## Extended Description 
void f(){}

With -O3, GCC outputs this:

f():
  jmp %o7+8
  nop

LLVM outputs this:

f():
  save %sp, -128, %sp
  ret
  restore

**Comment by brad0** [comment]
@koachan

**Comment by brad0** [comment]
> This should be fixed by https://reviews.llvm.org/D138532. The necessary optimizations are all in place but it's not enabled by default by clang.

Thank you.

**Comment by brad0** [comment]
Fixed by 17d0a15478e96d8de611c90e760ca4f7b4ff5490
