### ISSUE TITLE
Failure to optimize combined popcount pattern

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#48343]
|  |  |
| --- | --- |
| Bugzilla Link | [48999](https://llvm.org/bz48999) |
| Version | trunk |
| OS | Linux |
| CC | @davidbolvansky,@jsonn,@LebedevRI,@RKSimon,@nikic,@rotateright |

## Extended Description
```
int f(unsigned int a, unsigned int b)
{
    return __builtin_popcount(a & 8) + __builtin_popcount(b & 2);
}
```
This can be optimized to `return __builtin_popcount((a & 8) | (b & 2));`. This transformation is done by GCC, but not by LLVM.

Godbolt comparison: https://godbolt.org/z/zjP3Ys
(If someone can tell me how to use ctpop in alive2 that'd be nice btw, I couldn't get it to work personally)

**Comment by RKSimon** [comment]
Tentatively closing this

@GabrielRavier @davidbolvansky
Feel free to reopen this if you encounter a real world use for ctpop(A) + ctpop(B) => ctpop(X|Y) + ctpop(X&Y)

**Comment by GabrielRavier** [comment]
> Tentatively closing this
> 
> @GabrielRavier @davidbolvansky Feel free to reopen this if you encounter a real world use for ctpop(A) + ctpop(B) => ctpop(X|Y) + ctpop(X&Y)

I have not *personally* encountered this but I've finally found the patch that made GCC optimize it: 	

And it appears to cite a real world use:

> These may seem obscure transformations, but performing these types of
POPCOUNT operations are often the performance critical steps in some cheminformatics
applications.

I've also found slides on a similar subject over [here](https://www.nextmovesoftware.com/talks/Sayle_EvolutionVsRevolution_ICCS_201805.pdf) which suggest that this can also be used to speed up chemical similarity calculations when they are calculated as Tanimoto coefficients.

**Comment by GabrielRavier** [comment]
Actually nvm I just realised this was closed w.r.t. the more generic optimisation, whereas the examples I found are for the original testcase - maybe I shouldn't look at old bug reports at 12 AM
