### ISSUE TITLE
Incorrect help text for memory write -f and -s options

### ISSUE THREAD

**Issue by DavidSpickett** [llvm/llvm-project#48362]
|  |  |
| --- | --- |
| Bugzilla Link | [49018](https://llvm.org/bz49018) |
| Version | 11.0 |
| OS | Linux |
| CC | @JDevlieghere,@RamNalamothu |

## Extended Description 
"memory write" shares "OptionGroupFormat" with a bunch of other commands but the options always have the same help text.

(lldb) help memory read
<...>
       -f <format> ( --format <format> )
            Specify a format to be used for display.
<...>
       -s <byte-size> ( --size <byte-size> )
            The size in bytes to use when displaying with the selected format

(lldb) help memory write
<...>
       -f <format> ( --format <format> )
            Specify a format to be used for display.

       -i <filename> ( --infile <filename> )
            Write memory using the contents of a file.

       -o <offset> ( --offset <offset> )
            Start writing bytes from an offset within the input file.

       -s <byte-size> ( --size <byte-size> )
            The size in bytes to use when displaying with the selected format

Meaning that the description for memory write -f and -s is incorrect. Reading the code I think -s is used for the input file size and -f is used to decide how to interpret the input values.

(lldb) memory write buf 0xcgh -f hex
error: '0xcgh' is not a valid hex string value.

I haven't looked at the other uses in detail but they look like display commands so memory write is the odd one out. ("register write" doesn't use it)

**Comment by RamNalamothu** [comment]
Fixed with 7f05ff8be and 94038c57.
