### ISSUE TITLE
Clang incorrectly rejects default construction of union with nontrivial member

### ISSUE THREAD

**Issue by miscco** [llvm/llvm-project#48416]
|  |  |
| --- | --- |
| Bugzilla Link | [49072](https://llvm.org/bz49072) |
| Version | trunk |
| OS | Windows NT |
| CC | @CaseyCarter,@zygoloid |

## Extended Description 
Consider the following valid TU:

```cpp
struct TriviallyConstructible {};
struct BadNontrivialClass {
    BadNontrivialClass() {}
};

union U {
    TriviallyConstructible first{};
    BadNontrivialClass second;
};

U u;
```

Currently clang rejects this with:

```
<source>:11:3: error: call to implicitly-deleted default constructor of 'U'
U u;
  ^
<source>:8:24: note: default constructor of 'U' is implicitly deleted because variant field 'second' has a non-trivial default constructor
    BadNontrivialClass second;
```

However, according to the standard (https://eel.is/c++draft/class.union#general-4) the member initializer of `first` makes this a valid construct.

**Comment by shafik** [comment]
Notes are non-normative, so you want to refer to [class.default.ctor](https://eel.is/c++draft/class.default.ctor#2) to back up this assertion.
