### ISSUE TITLE
libc++ does not build on riscv32

### ISSUE THREAD

**Issue by kraj** [llvm/llvm-project#48438]
|  |  |
| --- | --- |
| Bugzilla Link | [49094](https://llvm.org/bz49094) |
| Version | unspecified |
| OS | Linux |
| CC | @mclow |

## Extended Description 
libcxx on 12.0.0 release needs a fix

https://reviews.llvm.org/D85095

backported for libcxx to build on rv32

**Comment by philnik777** [comment]
The linked PR has been closed.
