### ISSUE TITLE
compiler-rt fails to buils on musl

### ISSUE THREAD

**Issue by kraj** [llvm/llvm-project#48435]
|  |  |
| --- | --- |
| Bugzilla Link | [49091](https://llvm.org/bz49091) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
compiler-rt fails to build for musl/linux due to size_t definition is missing.

A relevant patch fix is posted to 

https://reviews.llvm.org/D96213

**Comment by rzr** [comment]
Shouldn't this be closed since it's merged at:

https://reviews.llvm.org/rG60e32a1f34e9ea60155a98bbe6ee5ec2a383efa3

**Comment by kraj** [comment]
> Shouldn't this be closed since it's merged in:
> 
> https://reviews.llvm.org/rG60e32a1f34e9ea60155a98bbe6ee5ec2a383efa3

yes its fixed. Closing.
