### ISSUE TITLE
[CostModel]  Assertion "Vector argument does not match VF" failed.

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#48444]
|  |  |
| --- | --- |
| Bugzilla Link | [49100](https://llvm.org/bz49100) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced testcase](https://user-images.githubusercontent.com/55128014/143761765-c102d478-4777-45b6-aa53-23eb03db0ca7.gz) |
| CC | @DMG862,@RKSimon,@JonPsson,@uweigand |

## Extended Description 

502a67d "[CostModel] Remove VF from IntrinsicCostAttributes" seems to be causing the SystemZ build of the test-suite to fail (SingleSource/UnitTests/matrix-types-spec.cpp).

getUserCost() is called with the instruction

%i6 = tail call <275 x double> @&#8203;llvm.matrix.multiply.v275f64.v475f64.v209f64(<475 x double> %i2, <209 x double> undef, i32 25, i32 19, i32 11)

The return type is <275 x double>, but the argument type is <475 x double>. The assertion in getOperandsScalarizationOverhead() is using VF==275, which is the VF of the return type which does not match that of the argument...

opt -mtriple=s390x-linux-gnu -mcpu=z10 -O3 tc.ll -S -o -

llvm-project/llvm/include/llvm/CodeGen/BasicTTIImpl.h:630: unsigned int llvm::BasicTTIImplBase<T>::getOperandsScalarizationOverhead(llvm::ArrayRef<const llvm::Value*>, unsigned int) [with T = llvm::SystemZTTIImpl]: Asser
tion `(VF == 1 || VF == cast<FixedVectorType>(VecTy)->getNumElements()) && "Vector argument does not match VF"' failed.

#&#8203;8 0x000000000210124a llvm::BasicTTIImplBase<llvm::SystemZTTIImpl>::getOperandsScalarizationOverhead
#&#8203;26 0x0000000003261fca llvm::InlinerPass::run

**Comment by Endilll** [comment]
https://reviews.llvm.org/D96287 has successfully landed.
