### ISSUE TITLE
clang incorrectly requires coroutine_handle::from_address to be noexcept

### ISSUE THREAD

**Issue by 0775a785-4f8d-448e-9da0-14f81adf2169** [llvm/llvm-project#48453]
|  |  |
| --- | --- |
| Bugzilla Link | [49109](https://llvm.org/bz49109) |
| Version | 10.0 |
| OS | Windows NT |
| CC | @zygoloid,@yuanfang-chen |

## Extended Description 
from_address() is not required to be noexcept: https://eel.is/c++draft/coroutine.handle

However clang will error with a line pointing to (the end of) coroutine_handle<_Promise>::from_address(), presumably because it is checking for noexcept as per https://eel.is/c++draft/dcl.fct.def.coroutine#15 after generating that call as part of its internal lowering. This feels like a leaking of an implementation detail. In practice, it causes issues when trying to use libstdc++'s <coroutine> because it doesn't mark that method as noexcept. I've filed a bug (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99021) with them asking to change it, but it would be nice if clang didn't require the noexcept, both because it isn't required by the standard, and because it will make it easier to use clang with the already-in-the-wild libstdc++-10 installs.

src/mongo/db/index/columns_index_access_method.cpp:328:28: error: the expression 'co_await __promise.final_suspend()' is required to be non-throwing
    generator<BSONElement> subcellElements() const {
                           ^
/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/coroutine:205:5: note: must be declared with 'noexcept'
    }

**Comment by ChuanqiXu9** [comment]
This should be addressed in https://github.com/llvm/llvm-project/commit/4f4340ee2af36909db77aeedb1d22c2ba52d2dfa.
