### ISSUE TITLE
By-value and by-reference parameters should not have a partial ordering due to constraints

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#48450]
|  |  |
| --- | --- |
| Bugzilla Link | [49106](https://llvm.org/bz49106) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
The following invalid translation unit is accepted by clang:

```
template<typename T>
int f(T);

template<typename T> requires true
int f(T const&);

int i = f(42);
```

See it live: https://godbolt.org/z/Wh41x6

See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96333 for more context.

**Comment by royjacobson** [comment]
Fixed now https://reviews.llvm.org/D123182
