### ISSUE TITLE
[X86] support for -mstack-protector-guard-symbol=

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#48553]
|  |  |
| --- | --- |
| Bugzilla Link | [49209](https://llvm.org/bz49209) |
| Version | trunk |
| OS | All |
| Blocks | llvm/llvm-project#4440  |
| CC | @kees,@zygoloid,@xiangzh1 |

## Extended Description 
via https://lore.kernel.org/lkml/c0ff7dba14041c7e5d1cae5d4df052f03759bef3.1613243844.git.luto@kernel.org/, the Linux kernel is looking to use the pair of flags:

-mstack-protector-guard-reg=fs -mstack-protector-guard-symbol=__stack_chk_guard

for 32b x86 kernels.  It seems that clang does not yet support

-mstack-protector-guard-symbol=__stack_chk_guard

**Comment by nickdesaulniers** [comment]
cc @phoebewang

**Comment by phoebewang** [comment]
I think we have already supported it, see https://github.com/llvm/llvm-project/commit/7c3fea7721e421de235917d9454d448f976500fc
cc @xiangzh1

**Comment by nickdesaulniers** [comment]
> I think we have already supported it, see https://github.com/llvm/llvm-project/commit/7c3fea7721e421de235917d9454d448f976500fc

Almost; there are 4 very similarly named flags:
1. `-mstack-protector-guard=`
2. `-mstack-protector-guard-reg=`
3. `-mstack-protector-guard-offset=`
4. `-mstack-protector-guard-symbol=`

7c3fea7721e421de235917d9454d448f976500fc implements 1-3.  Clang is still missing support for 4 which is used by the Linux kernel when building the 32b x86 Linux kernel.

**Comment by xiangzh1** [comment]
Yes, I remember I implemented some, let me try to support the 4 (some days later).
Please can you give me the requirement of support "-mstack-protector-guard-symbol=" ?

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3fb0fdb3bbe7a

```c
void foo (int *);
void bar (void) {
    int baz [42];
    foo(baz);
}
```
```sh
$ clang -mstack-protector-guard-reg=gs -mstack-protector-guard-symbol=__woof -fstack-protector-strong -O2
```
should produce references to:
```asm
%gs:__woof(%rip)
```
operands rather than `%fs:40` if the first two flags are removed.

**Comment by xiangzh1** [comment]
Sorry for late implement, we are in release these days.
Implement patch: https://reviews.llvm.org/D129346 
thank you!

**Comment by xgupta** [comment]
will it be fine to close this since the patch is committed?
