### ISSUE TITLE
Suboptimal lowering of `mul x, 0b111....` when using SelectionDAG

### ISSUE THREAD

**Issue by mshockwave** [llvm/llvm-project#48588]
|  |  |
| --- | --- |
| Bugzilla Link | [49244](https://llvm.org/bz49244) |
| Version | trunk |
| OS | All |
| Blocks | llvm/llvm-project#48135  |
| CC | @glaubitz,@hasyimibhar,@mshockwave |

## Extended Description 
As described in test/CodeGen/M68k/ASM/Arith/imul-neg.ll, when multiplying value `x` with 2^n - 1 integer, the result will be `-x`, which is preferred to be lowered to `neg x` instruction. However, SelectionDAG ISel will generate `sub 0, x` (FastISel doesn't have this problem though).

**Comment by 0x59616e** [comment]
closed by 78b16ccf2b5c4ba
