### ISSUE TITLE
reference to local binding fails in enclosing function

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#48582]
|  |  |
| --- | --- |
| Bugzilla Link | [49238](https://llvm.org/bz49238) |
| Version | 12.0 |
| OS | FreeBSD |
| Attachments | [testcase-clang.cpp](https://user-images.githubusercontent.com/95090477/143761816-135be0c7-c537-49d8-a060-383d8073efba.gz) |
| CC | @zygoloid |

## Extended Description 

The attached testcase fails in clang++{9,10,11}:

> testcase-clang.cpp:11:16: error: reference to local binding 'a' declared in enclosing function 'f'
>         return a+b;
>                ^
> testcase-clang.cpp:9:11: note: 'a' declared here
>     auto [a, b] = newTuple();
>           ^
> testcase-clang.cpp:11:18: error: reference to local binding 'b' declared in enclosing function 'f'
>         return a+b;
>                  ^
> testcase-clang.cpp:9:14: note: 'b' declared here
>     auto [a, b] = newTuple();
>              ^
> 2 errors generated.

It succeeds in gcc-10.

**Comment by planetmarshall** [comment]
Short test case on Compiler Explorer

https://godbolt.org/z/n99xe57vs

**Comment by chausner** [comment]
> Short test case on Compiler Explorer
> 
> https://godbolt.org/z/n99xe57vs

Seems the issue has been fixed in the latest development version (clang (trunk) on Compiler Explorer).
