### ISSUE TITLE
[sanitizers] Please merge ac6c13bfc49f2d67a77144c839ecf49e48cb994c into 12.0.0

### ISSUE THREAD

**Issue by jprotze** [llvm/llvm-project#48590]
|  |  |
| --- | --- |
| Bugzilla Link | [49246](https://llvm.org/bz49246) |
| Version | unspecified |
| OS | Linux |
| Blocks | llvm/llvm-project#48661  |
| CC | @tstellar |
| Fixed by commit(s) | ed4230732adeb04a23fc25b7a5924e423ba5ac91 |

## Extended Description 
Please merge https://reviews.llvm.org/D96762 / ac6c13bfc49f2d67a77144c839ecf49e48cb994c into 12.0.0.

This patch allows running tests (check-all / check-tsan) while using compiler cache (ccache).

**Comment by arsenm** [comment]
Old release
