### ISSUE TITLE
linalg.fill has a bad interaction with -linalg-generalize-named-ops flag

### ISSUE THREAD

**Issue by agostini01** [llvm/llvm-project#48593]
|  |  |
| --- | --- |
| Bugzilla Link | [49249](https://llvm.org/bz49249) |
| Version | unspecified |
| OS | Linux |
| CC | @joker-eph |

## Extended Description 
While transforming linalg named ops with `-linalg-generalize-named-ops` I stumble on a "`Aborted (core dump)` error" if the mlir code contains a linalg.fill operation.

> // This does not work, and breaks with an Aborted (core dumped) error
> // mlir-opt -linalg-generalize-named-ops -convert-linalg-to-affine-loops %s
>
> // Converting directly to affine loops works
> // mlir-opt -convert-linalg-to-affine-loops %s
>
> func private @&#8203;alloc_4d_filled_f32(%s1 : index, %s2 : index, %s3 : index, %s4 : index, %f : f32) -> memref<?x?x?x?xf32> {
>  %buf = alloc(%s1, %s2, %s3, %s4) : memref<?x?x?x?xf32> 
>  linalg.fill(%buf, %f) : memref<?x?x?x?xf32>, f32
>  return %buf : memref<?x?x?x?xf32>
> }

I think a possible work around is to add `linalg::FillOp` operation to this line:
https://github.com/llvm/llvm-project/blob/e9c11c1934f90725673f8a808fe6fcc390224a87/mlir/lib/Dialect/Linalg/Transforms/Generalization.cpp#L119

excluding it from the `-linalg-generalize-named-ops` pass.

Thanks

**Comment by nicolasvasilache** [comment]
This has been fixed a while back, the following IR does what you'd expect:
```
func.func private @alloc4d(%s1 : index, %s2 : index, %s3 : index, %s4 : index, %f : f32) -> memref<?x?x?x?xf32> {
  %buf = memref.alloc(%s1, %s2, %s3, %s4) : memref<?x?x?x?xf32>
  linalg.fill ins(%f : f32) outs(%buf : memref<?x?x?x?xf32>)
  return %buf : memref<?x?x?x?xf32>
}
```
