### ISSUE TITLE
11.1.0: test suite is failing

### ISSUE THREAD

**Issue by 4084477f-e1df-4024-a410-168c80096e18** [llvm/llvm-project#48658]
|  |  |
| --- | --- |
| Bugzilla Link | [49314](https://llvm.org/bz49314) |
| Version | 11.0 |
| OS | Windows NT |
| CC | @zygoloid |

## Extended Description 
gcc 11.0.1
python lit 0.11.1
Python 3.8.8
llvm 11.1.0 build with using LTO on linking all binaries

[tkloczko@barrel clang-11.1.0.src]$ LD_LIBRARY_PATH=/home/tkloczko/rpmbuild/BUILDROOT/clang-11.1.0-7.fc35.x86_64/usr/lib64  /usr/bin/cmake --build x86_64-redhat-linux-gnu -j48 --verbose --target check-all --verbose -v
[1/2] cd /home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/bindings/python && /usr/bin/cmake -E env CLANG_LIBRARY_PATH=/home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/x86_64-redhat-linux-gnu/lib64 /usr/bin/python3.8 -m unittest discover
........................................................./home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/bindings/python/tests/cindex/test_diagnostics.py:100: DeprecationWarning: Please use assertRegex instead.
  self.assertRegexpMatches(children[0].spelling,
.....................................................................
----------------------------------------------------------------------
Ran 126 tests in 1.087s

OK
[1/2] cd /home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/x86_64-redhat-linux-gnu && /usr/bin/python3.8 /usr/bin/lit -sv --param USE_Z3_SOLVER=0 /home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/x86_64-redhat-linux-gnu/tools/extra/test /home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/x86_64-redhat-linux-gnu/tools/extra/clangd/test/../unittests /home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/x86_64-redhat-linux-gnu/tools/extra/clangd/test /home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/x86_64-redhat-linux-gnu/test
lit: /usr/lib/python3.8/site-packages/lit/llvm/config.py:345: note: using clang: /home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/x86_64-redhat-linux-gnu/bin/clang
lit: /usr/lib/python3.8/site-packages/lit/llvm/config.py:345: note: using clang: /home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/x86_64-redhat-linux-gnu/bin/clang
lit: /usr/lib/python3.8/site-packages/lit/TestingConfig.py:99: fatal: unable to parse config file '/home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/test/utils/update_cc_test_checks/lit.local.cfg', traceback: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lit/TestingConfig.py", line 88, in load_from_path
    exec(compile(data, path, 'exec'), cfg_globals, None)
  File "/home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/test/utils/update_cc_test_checks/lit.local.cfg", line 21, in <module>
    assert os.path.isfile(script_path)
AssertionError

FAILED: CMakeFiles/check-all
cd /home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/x86_64-redhat-linux-gnu && /usr/bin/python3.8 /usr/bin/lit -sv --param USE_Z3_SOLVER=0 /home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/x86_64-redhat-linux-gnu/tools/extra/test /home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/x86_64-redhat-linux-gnu/tools/extra/clangd/test/../unittests /home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/x86_64-redhat-linux-gnu/tools/extra/clangd/test /home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/x86_64-redhat-linux-gnu/test
ninja: build stopped: subcommand failed.

[tkloczko@barrel clang-11.1.0.src]$ cat "/home/tkloczko/rpmbuild/BUILD/clang-11.1.0.src/test/utils/update_cc_test_checks/lit.local.cfg"
import os

import lit.util

# python 2.7 backwards compatibility
try:
    from shlex import quote as shell_quote
except ImportError:
    from pipes import quote as shell_quote

config.test_format = lit.formats.ShTest(execute_external=False)
config.suffixes = ['.test']

clang_path = os.path.join(config.clang_tools_dir, 'clang')
extra_args = '--clang ' + shell_quote(clang_path)
opt_path = os.path.join(config.llvm_tools_dir, 'opt')
extra_args += ' --opt ' + shell_quote(opt_path)
script_path = os.path.join(config.llvm_src_root, 'utils',
                           'update_cc_test_checks.py')
assert os.path.isfile(script_path)
config.substitutions.append(
    ('%update_cc_test_checks', "%s %s %s" % (
        shell_quote(config.python_executable), shell_quote(script_path),
        extra_args)))

**Comment by arsenm** [comment]
Old release
