### ISSUE TITLE
gold: should have a flag to dump the module

### ISSUE THREAD

**Issue by edwintorok** [llvm/llvm-project#4866]
|  |  |
| --- | --- |
| Bugzilla Link | [4494](https://llvm.org/bz4494) |
| Version | unspecified |
| OS | Linux |
| CC | @nlewycky |

## Extended Description 
When bugs are encountered during LTO, it is currently hard to debug, because
llvm-ld doesn't always reproduce the bug.

It would be useful to be able to dump the module after linking, or just before linking.

For example this assertion doesn't reproduce with llvm-ld
 Assertion failed: (ATI != AbstractTypeMap.end() && "Abstract type not in AbstractTypeMap?"), function MoveConstant.

**Comment by MaskRay** [comment]
https://reviews.llvm.org/D56114 Added `--plugin-opt=emit-asm` to `LLVMgold.so`
