### ISSUE TITLE
ICE on consteval constructor

### ISSUE THREAD

**Issue by 358f035c-0228-452d-a182-06fc827c70ea** [llvm/llvm-project#48688]
|  |  |
| --- | --- |
| Bugzilla Link | [49344](https://llvm.org/bz49344) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [Source](https://user-images.githubusercontent.com/93435520/143761834-bd006175-a502-42fe-8669-f4e3ece1124b.gz) |
| CC | @AaronBallman,@zygoloid |

## Extended Description 

https://godbolt.org/z/s14Ec5

struct C
{
    static constexpr int S(const char* cstr)
    {
        return 0;
    }
};

struct B
{
    const char* a;
    const char* b;

    constexpr B(const char* string, size_t size)
        : a(string), b(string + size)
    {
    }
};

struct S : B
{
    consteval S(const char* cstr)
        : B(cstr, C::S(cstr))
    {
    }
};

S f()
{
    return "";
}

**Comment by usx95** [comment]
All the crashes mentioned here seems to be fixed at the trunk.
https://godbolt.org/z/s14Ec5
https://godbolt.org/z/jrG3aP57r
https://godbolt.org/z/W8fsM9vPv
