### ISSUE TITLE
LLVM ERROR: Instruction Combining seems stuck in an infinite loop after 100 iterations.

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#48699]
|  |  |
| --- | --- |
| Bugzilla Link | [49355](https://llvm.org/bz49355) |
| Version | trunk |
| OS | Linux |
| Attachments | [reduced testcase](https://user-images.githubusercontent.com/55128014/143761837-52aaca9d-4200-47cf-8a0a-478377dbc181.gz) |
| CC | @JonPsson,@rotateright |

## Extended Description 

opt -mtriple=s390x-linux-gnu  -mcpu=arch13 -o out.opt.ll -S -O3 -enable-gvn-memdep=false -simplifycfg-sink-common=false -unroll-count=10 crash0_aftercreduce.bc

**Comment by nikic** [comment]
No longer reproduces, presumably fixed by single-iteration InstCombine work.
