### ISSUE TITLE
Unused variable warnings in LinalgNamedStructuredOps

### ISSUE THREAD

**Issue by jpienaar** [llvm/llvm-project#48717]
|  |  |
| --- | --- |
| Bugzilla Link | [49373](https://llvm.org/bz49373) |
| Version | unspecified |
| OS | All |
| CC | @joker-eph,@jpienaar,@stellaraccident,@MaheshRavishankar,@River707 |

## Extended Description 
Getting ~10 warnings like

tools/mlir/include/mlir/Dialect/Linalg/IR/LinalgNamedStructuredOps.tcgen.cpp.inc:2440:24: warning: unused variable '_1' [-Wunused-variable]
    Value _0(args[0]), _1(args[1]), _2(args[2]);
                       ^

**Comment by nicolasvasilache** [comment]
TCGen has been replaced by OpDSL.
