### ISSUE TITLE
mlir 12.0 fails to build on aarch64 with clang 11.0.1

### ISSUE THREAD

**Issue by berolinux** [llvm/llvm-project#48715]
|  |  |
| --- | --- |
| Bugzilla Link | [49371](https://llvm.org/bz49371) |
| Version | trunk |
| OS | Linux |
| CC | @jpienaar,@nicolasvasilache |

## Extended Description 
This is a bug in 11.0.1 that has already been fixed in 12.0, but it makes updating from 11 to 12 hard (you have to first build llvm with mlir disabled, then build it with mlir enabled using the newly built version).

Building 12.0 on aarch64 with 11.0.1 barfs with

FAILED: tools/mlir/include/mlir/Dialect/Linalg/IR/LinalgNamedStructuredOps.td tools/mlir/include/mlir/Dialect/Linalg/IR/LinalgNamedStructuredOps.cpp.inc 
cd /home/bero/abf/llvm/BUILD/llvm-project-release-12.x/build/tools/mlir/include/mlir/Dialect/Linalg/IR && /home/bero/abf/llvm/BUILD/llvm-project-release-12.x/build/bin/mlir-linalg-ods-gen -gen-ods-decl /home/bero/abf/llvm/BUILD/llvm-project-release-12.x/mlir/include/mlir/Dialect/Linalg/IR/LinalgNamedStructuredOpsSpec.tc > /home/bero/abf/llvm/BUILD/llvm-project-release-12.x/build/tools/mlir/include/mlir/Dialect/Linalg/IR/LinalgNamedStructuredOps.td && /home/bero/abf/llvm/BUILD/llvm-project-release-12.x/build/bin/mlir-linalg-ods-gen -gen-impl /home/bero/abf/llvm/BUILD/llvm-project-release-12.x/mlir/include/mlir/Dialect/Linalg/IR/LinalgNamedStructuredOpsSpec.tc > /home/bero/abf/llvm/BUILD/llvm-project-release-12.x/build/tools/mlir/include/mlir/Dialect/Linalg/IR/LinalgNamedStructuredOps.cpp.inc
mlir-linalg-ods-gen: /home/bero/abf/llvm/BUILD/llvm-project-release-12.x/llvm/include/llvm/ADT/DenseMap.h:1261: DenseMapIterator<KeyT, ValueT, KeyInfoT, Bucket, IsConst> &llvm::DenseMapIterator<mlir::ThreadLocalCache<llvm::DenseSet<(anonymous namespace)::ParametricStorageUniquer::HashedStorage, (anonymous namespace)::ParametricStorageUniquer::StorageKeyInfo>> *, std::weak_ptr<llvm::DenseSet<(anonymous namespace)::ParametricStorageUniquer::HashedStorage, (anonymous namespace)::ParametricStorageUniquer::StorageKeyInfo>>, llvm::DenseMapInfo<mlir::ThreadLocalCache<llvm::DenseSet<(anonymous namespace)::ParametricStorageUniquer::HashedStorage, (anonymous namespace)::ParametricStorageUniquer::StorageKeyInfo>> *>, llvm::detail::DenseMapPair<mlir::ThreadLocalCache<llvm::DenseSet<(anonymous namespace)::ParametricStorageUniquer::HashedStorage, (anonymous namespace)::ParametricStorageUniquer::StorageKeyInfo>> *, std::weak_ptr<llvm::DenseSet<(anonymous namespace)::ParametricStorageUniquer::HashedStorage, (anonymous namespace)::ParametricStorageUniquer::StorageKeyInfo>>>, false>::operator++() [KeyT = mlir::ThreadLocalCache<llvm::DenseSet<(anonymous namespace)::ParametricStorageUniquer::HashedStorage, (anonymous namespace)::ParametricStorageUniquer::StorageKeyInfo>> *, ValueT = std::weak_ptr<llvm::DenseSet<(anonymous namespace)::ParametricStorageUniquer::HashedStorage, (anonymous namespace)::ParametricStorageUniquer::StorageKeyInfo>>, KeyInfoT = llvm::DenseMapInfo<mlir::ThreadLocalCache<llvm::DenseSet<(anonymous namespace)::ParametricStorageUniquer::HashedStorage, (anonymous namespace)::ParametricStorageUniquer::StorageKeyInfo>> *>, Bucket = llvm::detail::DenseMapPair<mlir::ThreadLocalCache<llvm::DenseSet<(anonymous namespace)::ParametricStorageUniquer::HashedStorage, (anonymous namespace)::ParametricStorageUniquer::StorageKeyInfo>> *, std::weak_ptr<llvm::DenseSet<(anonymous namespace)::ParametricStorageUniquer::HashedStorage, (anonymous namespace)::ParametricStorageUniquer::StorageKeyInfo>>>, IsConst = false]: Assertion `Ptr != End && "incrementing end() iterator"' failed.

If there is an easy known workaround for this, it may make sense to apply it to ease updating.

**Comment by Endilll** [comment]
We're not supporting 11 anymore.
