### ISSUE TITLE
Add pragma for loop aligning

### ISSUE THREAD

**Issue by ibogosavljevic** [llvm/llvm-project#48724]
|  |  |
| --- | --- |
| Bugzilla Link | [49380](https://llvm.org/bz49380) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor,@LebedevRI,@zygoloid |

## Extended Description 
On modern x86 CPUs, the performance of the loop can vary up to 50% if the loop instructions are not aligned properly. Aligning the loop start on a 32-byte boundary can help get the best performance out of my critical loop, but there is no guarantee that CLANG will align the loops properly.

Workarounds: Putting assembler nops or assembler align directives doesn't help, because the actual assembler loop can have a header of assembly instructions. 

This issue is a very well known one, e.g.: https://stackoverflow.com/questions/45298870/why-does-loop-alignment-on-32-byte-make-code-faster

Repro: I can provide a working example where the same code has different speeds depending on the loop alignment.

Intel's compiler already has a similar pragma: https://software.intel.com/content/www/us/en/develop/articles/intelr-compiler-170-new-feature-code-alignment-for-loops.html

E.g. pragma
```cpp
     for (int i = 0; i < len; i++) {
        int min = a[i];
        int min_index = i;
        #pragma clang loop code_align(32)
        for (int j = i+1; j < len; j++) {
            if (a[j] < min) {
                min = a[j];
                min_index = j;
            }
        }
        std::swap(a[i], a[min_index]);
    }
```

**Comment by marcauberer** [comment]
This is already implemented with the new metadata "llvm.loop.align" in LLVM 18. However the metadata does currently not work correctly, which is tracked here: #102632

**Comment by marcauberer** [comment]
In Clang, one can use e.g. `[[clang::code_align(32)]]` for a loop to align it (in this case) to a 32 byte boundary.
