### ISSUE TITLE
Pack expansion failure with template lambda and std::index_sequence

### ISSUE THREAD

**Issue by vittorioromeo** [llvm/llvm-project#48731]
|  |  |
| --- | --- |
| Bugzilla Link | [49387](https://llvm.org/bz49387) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 

```c++
#include <utility>

struct S 
{
    template <int> using N = int;
    static constexpr int size = 5;
};

static void f()
{
    const auto l = [&]<typename>() {};

    [&]<std::size_t... Is>(std::index_sequence<Is...>)
    {
        ((l
                 .template operator()<typename S::template N<Is>>()),
            ...);
    }
    (std::make_index_sequence<S::size> {});
}
```

The code above results in an incorrect compilation failure with the following message:

```
<source>:17:13: error: pack expansion does not contain any unexpanded parameter packs
            ...);
            ^
1 error generated.
Compiler returned: 1
```

The code should instead compile. Live on Compiler Explorer:
https://gcc.godbolt.org/z/rMvY3o

**Comment by shafik** [comment]
@zygoloid can you provide some more details on where this could be fixed?

**Comment by zygoloid** [comment]
The incorrect dependence calculation is split across two functions:

https://github.com/llvm/llvm-project/blob/main/clang/lib/AST/ComputeDependence.cpp#L614
https://github.com/llvm/llvm-project/blob/main/clang/lib/AST/Expr.cpp#L1732

This dependence calculation appears to be missing quite a few aspects of syntactic dependence:

- The `NameInfo` could be instantiation dependent or could contain an unexpanded parameter pack or an error (looks like we don't even provide an accessor to determine whether a `DeclarationNameInfo` is error-dependent), if it's a conversion function name or a destructor name
- The `TemplateArgs` could contain an unexpanded parameter pack or an error
- The `QualifierLoc` could contain an unexpanded parameter pack or an error

(It looks like only the base expression's syntactic dependence is properly handled and all other components of the member access are not...)

**Comment by Fznamznon** [comment]
https://reviews.llvm.org/D154689

**Comment by shafik** [comment]
@zygoloid do you have a case where it would fail due to `NameInfo` dependence? See comment here: https://reviews.llvm.org/D154689#4479858

**Comment by zygoloid** [comment]
Sure. [Here](https://godbolt.org/z/soG3Phsf9) is a case where we do the wrong thing because there's a purely syntactic dependence on an unexpanded pack in a destructor name:

```c++
struct A {};
template<int> using T = A;
template<int ...Ns> void f(A a) {
  (a.~T<Ns>(), ...);
}
```

And [here](https://godbolt.org/z/5Pej1av7n) is a case where the name is a conversion function name:

```c++
struct A { operator int(); };
template<int> using T = int;
template<int ...Ns> void f(A a) {
  (a.operator T<Ns>(), ...);
}
```

**Comment by Fznamznon** [comment]
Thanks @zygoloid !
