### ISSUE TITLE
Putting std::optional to std::any seems broken with visbility=hidden

### ISSUE THREAD

**Issue by 8574d5df-4f6c-46cc-848c-86d7e751e0ab** [llvm/llvm-project#48743]
|  |  |
| --- | --- |
| Bugzilla Link | [49399](https://llvm.org/bz49399) |
| Version | 10.0 |
| OS | Windows NT |
| CC | @mclow |

## Extended Description 
a.cpp:
```c++
#include <optional>
#include <any>

std::optional<int> f (const std::any &value)
{
  return std::any_cast<std::optional<int>> (value);
}

std::any g ();

int main ()
{
  return f (g ()).value_or (0);
}
```
b.cpp:
```c++
#include <any>
#include <optional>

[[gnu::visibility("default")]] std::any g () { return std::make_optional (1); }
```
Running with:
clang++ -stdlib=libc++ b.cpp -std=c++20 -shared -fPIC -o b.so -fvisibility=hidden
clang++ -stdlib=libc++ a.cpp -std=c++20 -L . -l:b.so
LD_LIBRARY_PATH=. ./a.out

Example works fine with libstdc++, seems like something is wrong with std::optional visbiility

**Comment by philnik777** [comment]
Fixed in LLVM 18: https://godbolt.org/z/Tsed5aE84
