### ISSUE TITLE
[MLIR] [PDL] PDL::AttributeOp doesn't parse Dictionary attribute

### ISSUE THREAD

**Issue by 65aa8a97-08c4-4022-a21c-7077946f4f6d** [llvm/llvm-project#48776]
|  |  |
| --- | --- |
| Bugzilla Link | [49432](https://llvm.org/bz49432) |
| Version | unspecified |
| OS | Linux |
| CC | @jpienaar,@River707,@bondhugula |

## Extended Description 
PDL::AttributeOp has `value` as an OptionalAttr.

Now when we write the following -> `pdl.attribute { a = 4 : i32, b = 5 : i32 }`
Even though the `value` here is DictionaryAttr PDL::AttributeOp recognises it as a user defined attribute list.
I tried printing `op.value()` and it dumps `None`.

If we do the following instead -> `pdl.attribute { value = { a = 4 : i32, b = i32 }}` and try printing `op.value()` in the verifier, we get `{a = 4 : i32, b = 4 : i32}` as output.

Is this an expected behaviour?

**Comment by River707** [comment]
This has since been fixed.
