### ISSUE TITLE
preserve_mostcc on X86 incorrectly restores RAX after storing return value

### ISSUE THREAD

**Issue by 15cb59f3-452d-4aee-ab1b-bf7a4d865bb9** [llvm/llvm-project#48789]
|  |  |
| --- | --- |
| Bugzilla Link | [49445](https://llvm.org/bz49445) |
| Version | trunk |
| OS | Linux |
| CC | @topperc,@ributzka,@RKSimon,@phoebewang,@rotateright |

## Extended Description 
When a function with preserve_mostcc calling convention returns a value through RAX, the epilogue incorrectly restores RAX after the return value has been written into it.

Minimal testcase:
```
target triple = "x86_64-unknown-linux-gnu"
define preserve_mostcc i32 @&#8203;foobar() {
  ret i32 1
}
```

Resulting assembly from `llc -o=- test2.ll`:
```
        .text
        .file   "test2.ll"
        .globl  foobar                          # -- Begin function foobar
        .p2align        4, 0x90
        .type   foobar,@function
foobar:                                 # @&#8203;foobar
        .cfi_startproc
# %bb.0:
        pushq   %rax
        .cfi_def_cfa_offset 16
        .cfi_offset %rax, -16
        movl    $1, %eax
        popq    %rax
        .cfi_def_cfa_offset 8
        retq
.Lfunc_end0:
        .size   foobar, .Lfunc_end0-foobar
        .cfi_endproc
                                        # -- End function
        .section        ".note.GNU-stack","",@progbits

```

I think this essentially means that `__attribute__((preserve_most))` is broken for any function that returns a value on X86?

Simple test with C code:

```
$ cat demo.c
#include <stdio.h>
__attribute__((preserve_most))
__attribute__((noinline))
unsigned int get_number(void) {
  return 0x41414141;
}
int main(void) {
  printf("get_number() = 0x%x\n", get_number());
  return 0;
}
$ /h/git/foreign/llvmp-build-debug/bin/clang-12 -o demo demo.c -Wall
$ ./demo
get_number() = 0x401140
$ 
```

**Comment by zq1997** [comment]
A year later, this problem still looks unsolved. We cannot use `preserve_mostcc` for any function that has a return value.

**Comment by AntonBikineev** [comment]
The issue should be fixed by https://reviews.llvm.org/D143425. Please reopen if you find the calling convention(s) breaking in some other scenarios.

**Comment by RKSimon** [comment]
10629bb96aebfefaadfb0069bc7e276b868fcef9
