### ISSUE TITLE
800x compile time regression for AVR.cpp on sparcv9

### ISSUE THREAD

**Issue by rorth** [llvm/llvm-project#48817]
|  |  |
| --- | --- |
| Bugzilla Link | [49473](https://llvm.org/bz49473) |
| Version | trunk |
| OS | Solaris |
| Attachments | [-ftime report output](https://user-images.githubusercontent.com/3930951/143761866-0c735c08-df5c-44c9-879e-f598c6c047ea.gz) |
| CC | @aeubanks,@dwblaikie,@jrtc27 |

## Extended Description 

The compile time for clang/lib/Driver/ToolChains/AVR.cpp on Solaris/sparcv9 has
exploded recently: it grew from 4.92s to 1h 3m 50.16s, almost a factor of 800
and doubling the wall clock time of ninja -j96 on a Netra SPARC S7-2.

A reghunt identified the new PM as the culprit

commit 669ddd1e9b1226432b003dbba05b99f8e992285b
Author: Arthur Eubanks <aeubanks@google.com>
Date:   Mon Jan 25 11:00:56 2021 -0800

    Turn on the new pass manager by default

and indeed compile time is back to normal with -flegacy-pass-manager.

Unfortunately, a build with -DENABLE_EXPERIMENTAL_NEW_PASS_MANAGER=OFF fails:

FAILED: tools/clang/tools/extra/clangd/CMakeFiles/obj.clangDaemon.dir/ClangdLSPServer.cpp.o
[...]
Did not see access type in access path!
  store i64 %Handler.coerce1, i64* %.fca.1.gep, align 8, !tbaa !&#8203;372
!&#8203;372 = !{#370, !&#8203;6, i64 8}

I'm attaching the -ftime-report output for reference.

**Comment by brad0** [comment]
@rorth Is this still an issue?

**Comment by rorth** [comment]
> @rorth Is this still an issue?

The slowdown has vanished some time ago (cannot say exactly when).
