### ISSUE TITLE
Llvm bug in toolchain when building 4.14.209. Toolchain built with https://github.com/johanlike/tc-build

### ISSUE THREAD

**Issue by 182fb75a-8cda-4ae7-822e-a506d361675b** [llvm/llvm-project#48818]
|  |  |
| --- | --- |
| Bugzilla Link | [49474](https://llvm.org/bz49474) |
| Version | unspecified |
| OS | Linux |
| Blocks | llvm/llvm-project#4440  |
| CC | @dwblaikie,@nathanchance,@nickdesaulniers,@zygoloid |

## Extended Description 
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.  Running pass 'Function Pass Manager' on module 'built-in.o(blk-cgroup.o at 1223376)'.
1.  Running pass 'AArch64 Instruction Selection' on function '@blkg_prfill_rwstat'
LLVM ERROR: Failed to rename temporary file .thinlto-cache/Thin-1f6c9e.tmp.o to .thinlto-cache/llvmcache-5D9F2C79BAD8989D10CD90795F71B8C39A2A608B: No such file or directory

/home/cyberknight/Kernels/weeb_kernel_oneplus_sm8150/scripts/link-vmlinux.sh: line 102: 130302 Aborted                 (core dumped) ${LD} ${LDFLAGS} -r -o ${1} $(lto_lds) ${objects}
make[1]: *** [/home/cyberknight/Kernels/weeb_kernel_oneplus_sm8150/Makefile:1160: vmlinux] Error 134
make[1]: Leaving directory '/home/cyberknight/Kernels/compiled_code'
make: *** [Makefile:146: sub-make] Error 2

**Comment by nickdesaulniers** [comment]
please provide more steps to reproduce
