### ISSUE TITLE
Compilation error when applying std::views::transform to std::array

### ISSUE THREAD

**Issue by 701fd7c4-6d4a-45cf-8ea7-68ce1ca67487** [llvm/llvm-project#48855]
|  |  |
| --- | --- |
| Bugzilla Link | [49511](https://llvm.org/bz49511) |
| Version | trunk |
| OS | Linux |
| CC | @Craffael,@zygoloid |

## Extended Description 
Unfortunately the following code fails to compile (using the STL of g++-10.2):

==== begin test program ====
#include <ranges>
#include <array>

std::array<int,2> points_;

auto foo()  {
    auto v = std::views::transform([](int p) {return p;});
    return points_ | v;
}

int main() {
    auto z = foo();
}
==== end test program ====

The same code compiles without problems using g++-10.2 so I think it should be valid code...

See also https://godbolt.org/z/e1ncvW

**Comment by ldionne** [comment]
Clang on Godbolt uses `libstdc++` by default, you need to pass `-stdlib=libc++`: https://godbolt.org/z/PMeebseeE.

Also note that our ranges implementation is currently incomplete, so you will find missing parts. If you find something that we do implement but we have a bug in it, please report it. If we are missing something, please be patient -- we are tracking the missing parts and will eventually get to it.
