### ISSUE TITLE
[MLIR][SPIR-V] Switch MemRefType memory space to richer attribute mechanism

### ISSUE THREAD

**Issue by vinograd47** [llvm/llvm-project#48851]
|  |  |
| --- | --- |
| Bugzilla Link | [49507](https://llvm.org/bz49507) |
| Version | unspecified |
| OS | All |

## Extended Description 
Recently the new feature was landed: Model MemRefType memory space as Attribute (https://reviews.llvm.org/D96145). It allows to use more descriptive type for memory space instead of raw integer. SPIR-V Dialect can leverage this feature to directly use "local", "private", "global" memory spaces as strings/enums instead of mapping to/from raw integers.

**Comment by antiagainst** [comment]
This is done via https://reviews.llvm.org/D130317, https://reviews.llvm.org/D131410 and others.
