### ISSUE TITLE
Unify mlir::Identifier and mlir::StringAttr?

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#48907]
|  |  |
| --- | --- |
| Bugzilla Link | [49563](https://llvm.org/bz49563) |
| Version | unspecified |
| OS | All |
| CC | @jpienaar,@River707 |

## Extended Description 
MLIR StringAttr and Identifier are both uniqued strings, both are pointer sized and pointerlike.  However, they have differences (including the ::get members taking arguments in different orders) the the lack of interop between them prevents some things where you'd like to have a DenseMap<onething, x> which doesn't work given they get uniqued differently.

Identifier predated StringAttr.  Should we just use StringAttr for everything?

-Chris

**Comment by River707** [comment]
Identifier has been dead for a while now.

**Comment by lattner** [comment]
huzzah!
