### ISSUE TITLE
fix-irreducible pass crashes: Assertion `LI.isLoopHeader(Headers.front())' failed.

### ISSUE THREAD

**Issue by 952e6d5a-d994-4724-a6d1-07613b2d95a8** [llvm/llvm-project#48919]
|  |  |
| --- | --- |
| Bugzilla Link | [49575](https://llvm.org/bz49575) |
| Version | trunk |
| OS | Linux |
| Attachments | [small.bc](https://user-images.githubusercontent.com/92601252/143761903-665d1dc0-8b0c-47c3-aef7-72270c207ddd.gz) |

## Extended Description 

$clang -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 77394c12a48822bb7a9183408f922d90c1d563cd)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Selected multilib: .;@m64

$clang -O3 -c -emit-llvm -femit-all-decls -mllvm -disable-llvm-optzns small.c -o small.bc

$opt -fix-irreducible -simplifycfg -fix-irreducible small.bc -o small-opt.bc
opt: /home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/llvm/lib/Transforms/Utils/FixIrreducible.cpp:297: bool makeReducible(llvm::LoopInfo&, llvm::DominatorTree&, Graph&&) [with Graph = llvm::Loop&]: Assertion `LI.isLoopHeader(Headers.front())' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt -fix-irreducible -simplifycfg -fix-irreducible small.bc -o small-opt.bc
1.	Running pass 'Function Pass Manager' on module 'small.bc'.
2.	Running pass 'Convert irreducible control-flow into natural loops' on function '@c'
 #&#8203;0 0x0000557d90d7a5ec llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x2e865ec)
 #&#8203;1 0x0000557d90d782b4 llvm::sys::RunSignalHandlers() (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x2e842b4)
 #&#8203;2 0x0000557d90d78423 SignalHandler(int) Signals.cpp:0:0
 #&#8203;3 0x00007f62d2f8d8a0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x128a0)
 #&#8203;4 0x00007f62d1bf4f47 raise /build/glibc-2ORdQG/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #&#8203;5 0x00007f62d1bf68b1 abort /build/glibc-2ORdQG/glibc-2.27/stdlib/abort.c:81:0
 #&#8203;6 0x00007f62d1be642a __assert_fail_base /build/glibc-2ORdQG/glibc-2.27/assert/assert.c:89:0
 #&#8203;7 0x00007f62d1be64a2 (/lib/x86_64-linux-gnu/libc.so.6+0x304a2)
 #&#8203;8 0x0000557d90e00b16 FixIrreducibleImpl(llvm::Function&, llvm::LoopInfo&, llvm::DominatorTree&) FixIrreducible.cpp:0:0
 #&#8203;9 0x0000557d90529918 llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x2635918)
#&#8203;10 0x0000557d9052a449 llvm::FPPassManager::runOnModule(llvm::Module&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x2636449)
#&#8203;11 0x0000557d90529196 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x2635196)
#&#8203;12 0x0000557d8e86ac0d main (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0x976c0d)
#&#8203;13 0x00007f62d1bd7b97 __libc_start_main /build/glibc-2ORdQG/glibc-2.27/csu/../csu/libc-start.c:344:0
#&#8203;14 0x0000557d8e933eaa _start (/home/jack-zhou/Documents/llvm/llvm_truck/llvm-project/build/bin/opt+0xa3feaa)
Aborted (core dumped)

The source code of small.c is as follows.
--------------------------------------------------------
int a;
char(b)();
static short c() {
  if (b())
  d:;
  e:
    for (;;) {
      int f;
      if (a)
        goto e;
      for (; 0;)
        goto d;
    }
}

**Comment by Endilll** [comment]
Can't reproduce using Clang 12 and 13: https://godbolt.org/z/Ks1xhWsfj
