### ISSUE TITLE
[RISCV] warning: Possible incorrect use of EVT::getVectorNumElements() for scalable vector.

### ISSUE THREAD

**Issue by nagisa** [llvm/llvm-project#48939]
|  |  |
| --- | --- |
| Bugzilla Link | [49595](https://llvm.org/bz49595) |
| Version | trunk |
| OS | All |
| CC | @asb,@topperc,@frasercrmck |

## Extended Description 
When running the following test case

; RUN: llc -mtriple=riscv64 -mattr=+m,+experimental-v -riscv-v-vector-bits-min=128
define <4 x i1> @&#8203;test_srem_vec(<4 x i33> %X) nounwind {
  %srem = srem <4 x i33> %X, <i33 9, i33 9, i33 -9, i33 -9>
  %cmp = icmp ne <4 x i33> %srem, <i33 3, i33 -3, i33 3, i33 -3>
  ret <4 x i1> %cmp
}

`llc` outputs the following warning:

warning: Possible incorrect use of EVT::getVectorNumElements() for scalable vector. Scalable flag may be dropped, use EVT::getVectorElementCount() instead

Unclear if an actual issue or just something that can be ignored, but reporting to bring your attention to it.

**Comment by frasercrmck** [comment]
We can probably close this issue now. Any new occurrence of this error warrants its own new issue.
