### ISSUE TITLE
11.1.0: clang crashes in libkcapi 1.2.1 test suite

### ISSUE THREAD

**Issue by 4084477f-e1df-4024-a410-168c80096e18** [llvm/llvm-project#48947]
|  |  |
| --- | --- |
| Bugzilla Link | [49603](https://llvm.org/bz49603) |
| Version | 11.0 |
| OS | Windows NT |
| CC | @DougGregor,@zygoloid |

## Extended Description 
All details are in https://github.com/smuellerDD/libkcapi/issues/108

I don't see anuy generated core dumps so I'm not sure how can I delivel back trace details with source code lines numbers.

**Comment by Endilll** [comment]
Can't reproduce using Clang 10 through 12 with assertions enabled.
