### ISSUE TITLE
clang: should support macro definitions when -g3 is used

### ISSUE THREAD

**Issue by edwintorok** [llvm/llvm-project#4898]
|  |  |
| --- | --- |
| Bugzilla Link | [4526](https://llvm.org/bz4526) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
#define X(a) (a+1)
int main()
{
    return X(1);
}

Compiled with gcc -g3 I am able to evaluate the X() macro in gdb:

$ gcc -g3 x.c
$ gdb ./a.out
...
(gdb) b main
(gdb) r
(gdb) p X(1)
$1 = 2
(gdb)

Compiled with clang -g3, it behaves the same as -g: I don't get macro information:
$ clang -g3 x.c
$ gdb ./a.out
...
(gdb) b main
(gdb) r
(gdb) p X(1)
No symbol "X" in current context.

**Comment by Endilll** [comment]
CC @dwblaikie

**Comment by dwblaikie** [comment]
You can get this debug info with the `-fdebug-macro` flag. Think we decided not to turn it on by default owing to the fairly large size and relatively low usage.
