### ISSUE TITLE
Turn off rules on a per file or function basis

### ISSUE THREAD

**Issue by jbreitbart** [llvm/llvm-project#48997]
|  |  |
| --- | --- |
| Bugzilla Link | [49653](https://llvm.org/bz49653) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
It seems to be rather complicated to turn off specific rules on a per-file or per-function basis, yet I think this seems useful.

For example, I have a library that I want to be thread-safe and a simple tool that demonstrates the library. The tool does not use threads and I would like to turn off some checks for the tool. I also have some functions that parse argv and I would like to turn off pointer checks for that function. I can turn it off for every pointer usage, but that I quite cumbersome.

**Comment by carlosgalvezp** [comment]
The `NOLINTBEGIN` and `NOLINTEND` functionality should cover this use case.
