### ISSUE TITLE
Miscompilation in middle-end (pointer arithmetic and comparisons)

### ISSUE THREAD

**Issue by miyuki** [llvm/llvm-project#49006]
|  |  |
| --- | --- |
| Bugzilla Link | [49662](https://llvm.org/bz49662) |
| Version | trunk |
| OS | Linux |
| Attachments | [Reproducer as C source code](https://user-images.githubusercontent.com/4668268/143761928-18f5316d-fc05-449e-ba59-86b072351336.gz), [Reduced reproducer](https://user-images.githubusercontent.com/4668268/143761929-3a4528ac-08e0-43ac-b147-2d24779b3119.gz) |
| CC | @LebedevRI,@RKSimon,@miyuki,@momchil-velikov |

## Extended Description 

The attached source code is miscompiled with trunk build of Clang:

$ clang -O2 test.c -o test && ./test
failed: distance(i, j) >= 2

(the expected output is "passed")

Git bisect points to the following commit: https://github.com/llvm/llvm-project/commit/2ad1f5eb1a47275593bd9baf75dcf3e9c3977473 (although it might not be the root cause)

I tried to reduce the test case in such a way that LLVM IR still looked reasonable to me and got the following result:

$ lli test-reduced.ll
passed
$ opt -indvars -inline -instcombine -jump-threading test-reduced.ll -o test.bc
$ lli test.bc
failed: distance(i, j) >= 2

**Comment by fhahn** [comment]
Passes now https://godbolt.org/z/884EG6b91

Fix should have been acf3279a037f
