### ISSUE TITLE
fatal error: error in backend: Instruction Combining seems stuck in an infinite loop after 100 iterations

### ISSUE THREAD

**Issue by haoxintu** [llvm/llvm-project#49014]
|  |  |
| --- | --- |
| Bugzilla Link | [49670](https://llvm.org/bz49670) |
| Version | trunk |
| OS | All |

## Extended Description 
Hi all.

Clang crashes on this valid program under -O3 only. Note that this issue only occurs in the current trunk version of clang, clang-12 (including) downwards versions handle this case well.

$cat small.c
#include <stdint.h>
uint8_t a, d, c, b;
void e() {
  int64_t *f = e;
  b = a ? *f : 0;
  int g = 10;
  for (; g; g--) {
    c = 0;
    for (; c <= 30; c++)
      ;
    d = 26;
    for (; d <= 42; d++) {
      int64_t *i = e;
      (a -= (a %= *i) < (c > 31)) || (b /= *i);
    }
  }
}

$clang -w -O3 small.c
fatal error: error in backend: Instruction Combining seems stuck in an infinite loop after 100 iterations.
clang-13: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 13.0.0 (https://github.com/llvm/llvm-project bed9933a461e7b3d0c8c5a8fa770aa1b49802660)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/tuhaoxin/github/llvm-project/build-20210320/bin
clang-13: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-13: note: diagnostic msg: /tmp/small-5d6471.c
clang-13: note: diagnostic msg: /tmp/small-5d6471.sh
clang-13: note: diagnostic msg: 

********************

$clang -v
clang version 13.0.0 (https://github.com/llvm/llvm-project bed9933a461e7b3d0c8c5a8fa770aa1b49802660)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/tuhaoxin/github/llvm-project/build-20210320/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64

By the way, I'm not sure if this is the same problem as is reported in
llvm/llvm-project#47132 
and
llvm/llvm-project#46688 
or not.

Thanks,
Haoxin

**Comment by fhahn** [comment]
Still reproduces on current `main`: https://clang.godbolt.org/z/1KsqrxMar

**Comment by fhahn** [comment]
IR reproducer that uses `-instcombine-infinite-loop-threshold=20` to make it a bit smaller https://llvm.godbolt.org/z/cz56v7cGo

**Comment by nikic** [comment]
No longer reproduces, fixed as part of single-iteration InstCombine work.
