### ISSUE TITLE
Coroutine miscompile

### ISSUE THREAD

**Issue by 7de4fff2-681f-4ce5-8b8d-464adbf25ae9** [llvm/llvm-project#49019]
|  |  |
| --- | --- |
| Bugzilla Link | [49675](https://llvm.org/bz49675) |
| Version | 11.0 |
| OS | Linux |
| CC | @avikivity,@michoecho,@zygoloid |

## Extended Description 
clang miscompiles (misoptimizes?) coroutines.

Here's a minimal example for clang 11.0.1: https://godbolt.org/z/EYE16d
Here's a minimal example for both 11.0.1 and trunk: https://godbolt.org/z/7nPG39

The bug only occurs with optimizations enabled. `opt-bisect-limit` shows that the linked test cases break after `BISECT: running pass (64) Combine redundant instructions on function (_Z3foo1A)`. I didn't confirm that this particular pass is the culprit though; maybe it only makes an earlier miscompile apparent.

Perhaps this bug is not coroutine-specific. However, we have encountered this miscompile (we aren't certain that the root cause is always the same, but they all look related) in practice several unrelated times with coroutines, and never without coroutines.

I also mentioned this case under llvm/llvm-project#48201 , but I'm opening a separate bug because I'm not actually sure that it's related to the original case in 48857.

**Comment by ChuanqiXu9** [comment]
It looks like it doesn't fail this time. Could you check again?

**Comment by michoecho** [comment]
It seems it was fixed alongside #48201. This issue can be closed now.
