### ISSUE TITLE
error: option '-mfloat128' cannot be specified with 'ppc64le'

### ISSUE THREAD

**Issue by 3a17e7c4-fca4-4827-b2a7-11a54d73d746** [llvm/llvm-project#49038]
|  |  |
| --- | --- |
| Bugzilla Link | [49694](https://llvm.org/bz49694) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
Using -mfloat128 on ppc64 gives this error:

error: option '-mfloat128' cannot be specified with 'ppc64le'

The docs seem suggest it should be valid:
https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-mfloat128
(although a list of flags with no actual documentation isn't very clear).

clang/lib/Basic/Targets/PPC.cpp has a confusing comment:

  if (!(ArchDefs & ArchDefinePwr9) && (ArchDefs & ArchDefinePpcgr) &&
      llvm::find(FeaturesVec, "+float128") != FeaturesVec.end()) {
    // We have __float128 on PPC but not power 9 and above.
    Diags.Report(diag::err_opt_not_valid_with_opt) << "-mfloat128" << CPU;
    return false;
  }

That comment says the type should be valid for "PPC but not power 9 and above", but what it really means is "only for power 9 and above". If you add -mcpu=power9 then -mfloat128 is accepted. I think the comment is just badly phrased.

The error message would be a lot more useful if it told you that you need power9. The comment in the source should also match the code.

**Comment by xgupta** [comment]
This seems to improved/fix by https://github.com/llvm/llvm-project/commit/d771cf277565f579aba24fef522355f4406323c9.
