### ISSUE TITLE
ICE when binding template template arguments with constrained NTTPs

### ISSUE THREAD

**Issue by f4ab9222-398a-420a-8edd-c1cc0534d525** [llvm/llvm-project#49046]
|  |  |
| --- | --- |
| Bugzilla Link | [49702](https://llvm.org/bz49702) |
| Version | unspecified |
| OS | Windows NT |
| CC | @zygoloid |

## Extended Description 
The following snippet:

```c++
template<typename T>
concept C = true;

template<template<C auto...> typename Templ>
struct template_ {};

template<C auto... Args>
struct template_binder
{
    template<template<C auto...> typename Templ>
    using templ = Templ<Args...>;
};

using T = template_<template_binder<>::template templ>;

```

Live demo: https://godbolt.org/z/7KExM4dh4

What is interesting is that removing the concept eliminates the ICE,
but clang rejects the code in this case (which is wrong).

Also,
gcc rejects the code as well (which is wrong).

MSVC accepts the code.

**Comment by jensmassberg** [comment]
The ICE isn't reproducible with Clang trunk anymore (but with Clang 16.0.0).

**Comment by shafik** [comment]
Confirmed this look good on clang-16: https://godbolt.org/z/9oT37c1hP

CC @erichkeane do you know which commit likely fixed this?

**Comment by erichkeane** [comment]
> Confirmed this look good on clang-16: https://godbolt.org/z/9oT37c1hP
> 
> CC @erichkeane do you know which commit likely fixed this?

That doesn't look particularly familiar.  But a lot happened since Clang 16, particularly around correctly getting the template arguments in place during constraint instantiation (which is what the problem is in that ICE in the OP).
