### ISSUE TITLE
LLVM Passes issue: unknown pass name

### ISSUE THREAD

**Issue by shutupandhack-club** [llvm/llvm-project#49069]
|  |  |
| --- | --- |
| Bugzilla Link | [49725](https://llvm.org/bz49725) |
| Version | trunk |
| OS | Linux |

## Extended Description 
I didn't root cause the issue. However, the current 'main' branch Passes seems broken.

To reproduce, git clone current main branch. Build it, and create any sample C program. Like:

int foo() {
  return 0;
}

int main() {
  foo();
  return 0;
}

and then run:

```
$ ./bin/clang -c -emit-llvm sample.c
$ ./bin/opt -load ./lib/LLVMHello.so -hello < sample.bc

./bin/opt: unknown pass name 'hello'
```

This will happen for any Pass we create too, and that's how I noticed it.

This works fine, if instead of the main branch, we download and build for example the latest release candidate llvm-project-llvmorg-12.0.0-rc3.tar.gz source.

The expected behavior would be:

```
$ ./bin/opt -load ./lib/LLVMHello.so -hello < sample.bc

Hello: foo
Hello: main
```

Thank you.

**Comment by arsenm** [comment]
Old pass manager
