### ISSUE TITLE
AllowShortBlocksOnASingleLine not working for else blocks

### ISSUE THREAD

**Issue by e9b6fe6c-5bea-4b9c-9f5b-bb606af8c13c** [llvm/llvm-project#49066]
|  |  |
| --- | --- |
| Bugzilla Link | [49722](https://llvm.org/bz49722) |
| Version | 11.0 |
| OS | Windows NT |
| CC | @mydeveloperday |

## Extended Description 
Clang-format configuration:
AllowShortBlocksOnASingleLine: Empty,
AllowShortIfStatementsOnASingleLine: false,
BreakBeforeBraces: Custom,
BraceWrapping: { AfterControlStatement: Always, BeforeElse: true, },

Formatted part of code:

// BEFORE
```
if (true)
{}
else
{}
```

// AFTER
```
if (true) {}
else
{}
```

// EXPECTED
```
if (true) {}
else {}
```

```
if (true)
{
    ;
}
else {}

if (true) {}
else
{
    ;
}
```

Is there a way to move the bracket from below to right after the else, like it's done for the if? Is this a bug? I was hoping that's what "AllowShortBlocksOnASingleLine: Empty" implies and tried almost all values of the BreakBeforeBraces property but couldn't get the desired effect.

**Comment by mydeveloperday** [comment]
Using the config you supply I get

```
if (true)
{}
else
{}
```

**Comment by jessesna** [comment]
Oh, this is [solved](https://reviews.llvm.org/rG813d486cbc99836ea4e75996e2667cb38f7113a8). Please close the issue.
