### ISSUE TITLE
3 nested auto lambda invocations crashes the parser

### ISSUE THREAD

**Issue by Matthewacon** [llvm/llvm-project#49087]
|  |  |
| --- | --- |
| Bugzilla Link | [49743](https://llvm.org/bz49743) |
| Version | trunk |
| OS | Linux |
| Attachments | [Compiler crash backtrace](https://user-images.githubusercontent.com/95090482/143761965-3f04baa5-c88a-44f2-a913-794257dff34b.gz), [Run script](https://user-images.githubusercontent.com/95090482/143761966-40119cd8-d7e7-4d68-bdb6-0573b8eecd18.gz) |
| CC | @zygoloid,@oToToT |

## Extended Description 

See attachment for compiler backtrace.

Affected versions:
 - trunk
 - 11.0.1
 - 11.0.0
 - 10.0.1
 - 10.0.0
 - 9.0.1
 - 9.0.0

Driver cmdline:
Note: For versions that do not support -std=c++20, -std=c++2a was used.

clang++ -Xclang -disable-llvm-passes -std=c++20

Code:
Note: Reduction attempts with creduce crashed and emitted incomplete code.

int main() {
 auto const l0 = []<typename T>() {};
 auto const l1 = []<typename T>(auto op) {
  op.template operator()<T>();
 };
 auto const l2 = [&]<typename T>() {
  l0.template operator()<T>();
 };
 l1.template operator()<int>(l2);
 return 0;
}

**Comment by cor3ntin** [comment]
Fixed https://godbolt.org/z/jPnq5ndqv
