### ISSUE TITLE
Cannot use std::array as template-value parameter

### ISSUE THREAD

**Issue by GuillaumeDua** [llvm/llvm-project#49092]
|  |  |
| --- | --- |
| Bugzilla Link | [49748](https://llvm.org/bz49748) |
| Version | 11.0 |
| OS | All |
| CC | @supergrecko |

## Extended Description 
Fixed in trunk, but until clang 11.0.1 :

```log
a non-type template parameter cannot have type std::array
```

https://godbolt.org/z/va8vn8Tdb

**Comment by Endilll** [comment]
Clang 11 is too old by this point to backport anything.
