### ISSUE TITLE
Dumping AST to json triggers assertion with VLA array in function body

### ISSUE THREAD

**Issue by ggeorgakoudis** [llvm/llvm-project#49111]
|  |  |
| --- | --- |
| Bugzilla Link | [49767](https://llvm.org/bz49767) |
| Version | trunk |
| OS | All |
| CC | @AaronBallman,@arichardson,@DougGregor,@eschulte,@jdoerfert,@zygoloid,@oToToT |

## Extended Description 
Dumping AST to json, using the parameter -ast-dump=json, causes an assertion on clang:

clang++: /root/llvm-project/clang/lib/AST/ItaniumMangle.cpp:4968: void {anonymous}::CXXNameMangler::mangleFunctionParam(const clang::ParmVarDecl*): Assertion `parmDepth < FunctionTypeDepth.getDepth()' failed. 

This is a minimum failing example on godbolt:

https://godbolt.org/z/eefYGbcob

**Comment by nikic** [comment]
Candidate patch: https://reviews.llvm.org/D116169

This makes update_cc_test_checks usable again.
