### ISSUE TITLE
basic_string::assign doesn't handle iterators into the string itself

### ISSUE THREAD

**Issue by 7318a870-54d1-4d9b-a5cf-8ce660251251** [llvm/llvm-project#49142]
|  |  |
| --- | --- |
| Bugzilla Link | [49798](https://llvm.org/bz49798) |
| Version | unspecified |
| OS | All |
| CC | @dwblaikie,@mclow,@oToToT |

## Extended Description 
basic_string::assign, unlike the containers', needs to tolerate the case where the iterators refers into the string. See https://wg21.link/string.assign#15, which depicts a temporary string being constructed before any mutation takes place.

Test case:

    std::string s = "abcde";
    s.assign(s.rbegin(), s.rend());
    assert(s == "edcba");

I suspect, but have not checked, that other member functions taking iterator pairs may have similar issues.

**Comment by philnik777** [comment]
This has been fixed somewhere between libc++12 and libc++13. (https://godbolt.org/z/GnsxnboEE)
