### ISSUE TITLE
bugprone-exception-escape reported for boost::beast::http::response

### ISSUE THREAD

**Issue by mmatrosov** [llvm/llvm-project#49151]
|  |  |
| --- | --- |
| Bugzilla Link | [49807](https://llvm.org/bz49807) |
| Version | unspecified |
| OS | Linux |
| CC | @EugeneZelenko |

## Extended Description 
Try this code (https://gcc.godbolt.org/z/oKax7dde3):

struct A {
  using R = boost::beast::http::response<boost::beast::http::string_body>;
  R r;
};

static_assert(std::is_nothrow_move_assignable_v<A>);

A a, b;

void foo() {
    b = std::move(a);
}

clang-tidy generates a warning:
warning: an exception may be thrown in function 'operator=' which should not throw exceptions [bugprone-exception-escape]
struct A {
       ^

However, static_assert ensures the class is no-throw move-assignable, and hence move assignment cannot throw.

**Comment by PiotrZSL** [comment]
Known issue, operator == for R is noexcept, but check ignores it

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D145865
