### ISSUE TITLE
Compiler hits OOM failure

### ISSUE THREAD

**Issue by 9b0a75e8-fd34-465c-ae32-69c28cc43f06** [llvm/llvm-project#49167]
|  |  |
| --- | --- |
| Bugzilla Link | [49823](https://llvm.org/bz49823) |
| Version | unspecified |
| OS | Windows NT |
| CC | @dwblaikie,@DougGregor,@zygoloid |

## Extended Description 
While compiling an in-progress version of a bug fix the compiler went into a memory allocation loop and hit an OOM failure. When I reproduced the bug by rebuilding the problematic target I saw the memory usage hit 20 GB before I got bored of watching and killed it.

The Chromium CL which triggers this bug is uploaded at crrev.com/c/2803616

Supporting information from process_crashreports.py can be found here:

gs://chrome-clang-crash-reports/v1/2021/04/02/user-brucedawson-clipboard_win-3750a6.tgz

**Comment by Endilll** [comment]
After quick googling I created "normal" link out of provided one: https://storage.googleapis.com/chrome-clang-crash-reports/v1/2021/04/02/user-brucedawson-clipboard_win-3750a6.tgz. But it's dead.

Unfortunately, we can't do much without reproducer.
Feel free to reopen if you have additional information
