### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by mrexodia** [llvm/llvm-project#49170]
|  |  |
| --- | --- |
| Bugzilla Link | [49826](https://llvm.org/bz49826) |
| Version | 11.0 |
| OS | Windows NT |
| Attachments | [standalone reproduction](https://user-images.githubusercontent.com/93435706/143761985-a19ebb6a-c689-420a-b1a5-cea18837720c.gz) |
| CC | @dwblaikie,@RKSimon,@zygoloid |

## Extended Description 

The following code appears to cause a strange crash during codegen.

1>fatal error: error in backend: stack allocation size is not a multiple of 8

#define LOG_FIXME(format, ...)

int PS4API sceAjmFinalize(const SceAjmContextId uiContext)
{
	LOG_FIXME("Not implemented");
	return SCE_OK;
}

With

#define _LOG_PRINT_(level, format, ...)    __logger_handle.print(level, __FUNCTION__, __FILE__, __LINE__, format, __VA_ARGS__)
#define LOG_FIXME(format, ...) _LOG_PRINT_(::logsys::Level::kFixme, format, __VA_ARGS__);

There is no crash. Standalone reproduction is in the attachment

**Comment by Endilll** [comment]
Appears to be fixed in Clang 12: https://godbolt.org/z/W3GW9Y5Ka
Reduced by C-Reduce:
```cpp
int __attribute__((sysv_abi)) sceAjmFinalize() { int uiContext; }
```
