### ISSUE TITLE
operator<=> instantiates for templates when it probably shouldn't and has an issue with constexpr.

### ISSUE THREAD

**Issue by e0e1e613-dccb-47a5-85db-3dc989429265** [llvm/llvm-project#49182]
|  |  |
| --- | --- |
| Bugzilla Link | [49838](https://llvm.org/bz49838) |
| Version | trunk |
| OS | All |
| CC | @zygoloid |

## Extended Description 
This example: https://gcc.godbolt.org/z/EYcWh7fbG

Gcc compiles it fine but clang tries to instantiate operator<=> (that's never called).

And also complains about not being able to instantiate a template as constexpr.

**Comment by cor3ntin** [comment]
Fixed in Clang 17
