### ISSUE TITLE
missing auto in `concept auto arg` error diagnostic needs improvement

### ISSUE THREAD

**Issue by ldalessa** [llvm/llvm-project#49192]
|  |  |
| --- | --- |
| Bugzilla Link | [49848](https://llvm.org/bz49848) |
| Version | trunk |
| OS | All |
| CC | @zygoloid |

## Extended Description 
If you forget the `auto` in a `concept auto arg` declaration specifically for a member function template clang provides a confusing diagnostic https://godbolt.org/z/M5859vqjd.

```
template <class T>
concept thing_t = true;

struct Foo {
    void foo(thing_t const&);
};
```

clang produces

```
<source>:5:14: error: expected parameter declarator
    void foo(thing_t const&);
             ^
<source>:5:22: error: expected ')'
    void foo(thing_t const&);
                     ^
<source>:5:13: note: to match this '('
    void foo(thing_t const&);
            ^
2 errors generated.
Compiler returned: 1

```

where gcc produces

```
<source>:5:14: error: expected 'auto' or 'decltype(auto)' after 'thing_t'
    5 |     void foo(thing_t const&);
      |              ^~~~~~~
Compiler returned: 1
```

**Comment by erichkeane** [comment]
It seems we have a similar diagnostic to GCCs, except for the 'const' being there.  So this is a problem it seems doing a 'const east' parse.  

west-const or no-const gives 'expected 'auto' or 'decltype(auto)' after concept name' (note we dont spell the concept name :().

**Comment by erichkeane** [comment]
Pushed an improvement here; ab4c22e2b735c839c667e08be303f7f8cef3ccf6

This should improve the cases for CVR qualifiers always, and much of the uses of a reference variable.  

However in :
``` BinaryConcept<int> &F = bar(); ```

We don't really have a way to tell the difference there between a missing-auto and `BinaryConcept<int> &  1` (or && 1).

Doing better than that isn't particularly possible without looking up the concept and figuring out the arity of the template arguments (that is, if there are fewer arguments specified than parameters, it isn't a conditional, its a reference!), but the work to do so is prohibitive.  For now, I'm counting this patch as 'good enough' to close, as soon as the build bots agree.
