### ISSUE TITLE
FAIL: lldb-api :: tools/lldb-vscode/attach/TestVSCode_attach.py

### ISSUE THREAD

**Issue by 3b3be5bc-be97-4c5a-a058-de8ddaf7c081** [llvm/llvm-project#49234]
|  |  |
| --- | --- |
| Bugzilla Link | [49890](https://llvm.org/bz49890) |
| Version | 11.0 |
| OS | Linux |

## Extended Description 
This bug may be a repeat of bug 49242.

FAIL: lldb-api :: tools/lldb-vscode/attach/TestVSCode_attach.py (87920 of 87920)
******************** TEST 'lldb-api :: tools/lldb-vscode/attach/TestVSCode_attach.py' FAILED ********************
Script:
--
/usr/bin/python3.8 /home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/llvm-project/lldb/test/API/dotest.py -u CXXFLAGS -u CFLAGS --env ARCHIVER=/usr/bin/ar --env OBJCOPY=/usr/bin/objcopy --env LLVM_LIBS_DIR=/home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/./lib --arch x86_64 --build-dir /home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/lldb-test-build.noindex --lldb-module-cache-dir /home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/lldb-test-build.noindex/module-cache-lldb/lldb-api --clang-module-cache-dir /home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/lldb-test-build.noindex/module-cache-clang/lldb-api --executable /home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/./bin/lldb --compiler /home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/./bin/clang --dsymutil /home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/./bin/dsymutil --filecheck /home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/./bin/FileCheck --yaml2obj /home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/./bin/yaml2obj --lldb-libs-dir /home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/./lib /home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/llvm-project/lldb/test/API/tools/lldb-vscode/attach -p TestVSCode_attach.py
--
Exit Code: 1

Command Output (stdout):
--
lldb version 12.0.0 (https://github.com/llvm/llvm-project.git revision 7e99bddfeaab2713a8bb6ca538da25b66e6efc59)
  clang revision 7e99bddfeaab2713a8bb6ca538da25b66e6efc59
  llvm revision 7e99bddfeaab2713a8bb6ca538da25b66e6efc59
Skipping following debug info categories: ['dsym', 'gmodules']
objc tests will be skipped because of unsupported platform
description: breakpoint 1.1
description: breakpoint 1.1
description: breakpoint 1.1

--
Command Output (stderr):
--
PASS: LLDB (/home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/bin/clang-x86_64) :: test_by_name (TestVSCode_attach.TestVSCode_attach)
UNSUPPORTED: LLDB (/home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/bin/clang-x86_64) :: test_by_name_waitFor (TestVSCode_attach.TestVSCode_attach) (requires one of macosx, darwin, ios, tvos, watchos, bridgeos, iphonesimulator, watchsimulator, appletvsimulator) 
PASS: LLDB (/home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/bin/clang-x86_64) :: test_by_pid (TestVSCode_attach.TestVSCode_attach)
PASS: LLDB (/home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/bin/clang-x86_64) :: test_commands (TestVSCode_attach.TestVSCode_attach)
FAIL: LLDB (/home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/bin/clang-x86_64) :: test_terminate_commands (TestVSCode_attach.TestVSCode_attach)
======================================================================
FAIL: test_terminate_commands (TestVSCode_attach.TestVSCode_attach)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/llvm-project/lldb/packages/Python/lldbsuite/test/decorators.py", line 135, in wrapper
    return func(*args, **kwargs)
  File "/home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/llvm-project/lldb/test/API/tools/lldb-vscode/attach/TestVSCode_attach.py", line 225, in test_terminate_commands
    self.verify_commands('terminateCommands', output, terminateCommands)
  File "/home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/llvm-project/lldb/packages/Python/lldbsuite/test/tools/lldb-vscode/lldbvscode_testcase.py", line 116, in verify_commands
    self.assertTrue(output and len(output) > 0, "expect console output")
AssertionError: None is not True : expect console output
Config=x86_64-/home/nnelson/Documents/llvm-project/llvm/utils/release/rc5/Phase3/Release+Asserts/llvmCore-12.0.0-rc5.obj/bin/clang

**Comment by JOE1994** [comment]
From latest buildbot results, test `PASS: lldb-api :: tools/lldb-dap/attach/TestDAP_attach.py`
(test was renamed from `tools/lldb-vscode/attach/TestVSCode_attach.py` in https://github.com/llvm/llvm-project/pull/69264/files)
