### ISSUE TITLE
std::clamp generates suboptimal assembly for primitive types

### ISSUE THREAD

**Issue by vittorioromeo** [llvm/llvm-project#49253]
|  |  |
| --- | --- |
| Bugzilla Link | [49909](https://llvm.org/bz49909) |
| Version | unspecified |
| OS | Windows NT |
| Depends On | llvm/llvm-project#46615  |
| CC | @ldionne,@LebedevRI,@mclow,@mizvekov,@rotateright,@jwakely |
| Fixed by commit(s) | 077bff39d46364035a5dcfa32fc69910ad0975d0 |

## Extended Description 
`std::clamp` generates poor assembly compared to hand-written counterpart for primitive types like `float`, even with `-Ofast -ffast-math`:

```
stdclamp(float, float, float):                         # @stdclamp(float, float, float)
        movss   dword ptr [rsp - 4], xmm0
        movss   dword ptr [rsp - 8], xmm1
        movss   dword ptr [rsp - 12], xmm2
        ucomiss xmm2, xmm0
        lea     rax, [rsp - 12]
        lea     rcx, [rsp - 4]
        cmovb   rcx, rax
        ucomiss xmm0, xmm1
        lea     rax, [rsp - 8]
        cmovae  rax, rcx
        movss   xmm0, dword ptr [rax]           # xmm0 = mem[0],zero,zero,zero
        ret

myclamp(float, float, float):                          # @myclamp(float, float, float)
        maxss   xmm0, xmm1
        minss   xmm0, xmm2
        ret
```

Live example:
https://godbolt.org/z/5oxvocevK

More information on:
https://secret.club/2021/04/09/std-clamp.html

**Comment by Quuxplusone** [comment]
GCC 11.x and Clang 13.x both give suboptimal codegen ( https://godbolt.org/z/4GqenKEYn ), but GCC trunk (the future 12.x) and Clang trunk (the future 14.x) both look fixed now: https://godbolt.org/z/7qvhrxEd6
