### ISSUE TITLE
[coroutines] errno address is reused after context switch

### ISSUE THREAD

**Issue by apolukhin** [llvm/llvm-project#49257]
|  |  |
| --- | --- |
| Bugzilla Link | [49913](https://llvm.org/bz49913) |
| Version | trunk |
| OS | Linux |
| Attachments | [Full example](https://user-images.githubusercontent.com/95090495/143762010-0313d1d8-1eea-49ee-9335-a2a03da25266.gz) |
| CC | @apolukhin,@zygoloid |

## Extended Description 

Consider the example:
```
CoroTask CoroToDealWith() {
    if (errno) first_call();
    co_await writerQueue;
    if (errno) second_call();
}
```

With `-O2 -std=c++20 -stdlib=libc++` flags clang generates code that stores the `errno` address on first call:

```
  call __errno_location
  mov qword ptr [rbx + 24], rax
  cmp dword ptr [rax], 0
  je .LBB1_2
  call first_call()
```

and reuses that address after wakeup:

```
CoroToDealWith() [clone .resume]: # @CoroToDealWith() [clone .resume]
  push rbx
  mov rbx, rdi
  mov rax, qword ptr [rdi + 24]
  cmp dword ptr [rax], 0
  je .LBB2_2
  call second_call()
```

The optimization is wrong: coroutine could be resumed on other thread and the errno address changes.

Godbolt playground: https://godbolt.org/z/Wh9xd9oME

Looks like the common subexpression elimination pass must not be applied between the context switches for the functions with `__attribute__((const))`

**Comment by ChuanqiXu9** [comment]
This one should be resolved in trunk.

**Comment by ChuanqiXu9** [comment]
The related commit should be 97010535171, bacdf80f42b4 and 1cedc51ff5a2.
