### ISSUE TITLE
Coroutine getting inlined causing CoroSplit to fail

### ISSUE THREAD

**Issue by lxfind** [llvm/llvm-project#49264]
|  |  |
| --- | --- |
| Bugzilla Link | [49920](https://llvm.org/bz49920) |
| Version | trunk |
| OS | All |

## Extended Description 
https://godbolt.org/z/ax3aM3r8d

AlwaysInliner runs before CoroEarly, at which point coroutine functions haven't had the presplit attribute added yet. So coroutines still end up getting inlined, violating some of the assumptions in CoroSplit.

**Comment by ChuanqiXu9** [comment]
This should be fixed at: https://github.com/llvm/llvm-project/commit/c75cedc237f9747c5d5fe2a312d5ccc8531e2e70
