### ISSUE TITLE
By-reference variadic init-capture copies objects in lambda

### ISSUE THREAD

**Issue by glebov-andrey** [llvm/llvm-project#49266]
|  |  |
| --- | --- |
| Bugzilla Link | [49922](https://llvm.org/bz49922) |
| Version | trunk |
| OS | All |
| CC | @glebov-andrey,@zygoloid |

## Extended Description 
Overview:
In a by-reference capture with an initializer that is a pack expansion (of the form "&... identifier initializer") the result of the initializer is stored in the lambda object by-copy instead of by-reference.

Steps to reproduce: build and run the following code in C++20 mode.

    void print_arg_addresses(auto &...args) {
        (std::cout << ... << static_cast<const void *>(&args)) << '\n';
    }

    void pass_arg_refs_through_lambda(auto &...args) {
        [&...args = args] { // <-- THE BUG IS HERE!
            print_arg_addresses(args...);
        }();
    }

    int main() {
        auto a = 0;
        print_arg_addresses(a);
        pass_arg_refs_through_lambda(a);
    }

Here is a Compiler Explorer link with more variants of the code: https://godbolt.org/z/Ycaejs9jd

Actual Results: the printed addresses are NOT equal.
Expected Results: the printed addresses are equal.

This bug is reproducible on all versions of Clang starting with 9.0 (when the feature was first implemented) and including the "trunk" version from Compiler Explorer. It has been reproduced on both Linux and Windows (with the clang-cl driver).

GCC and MSVC both compile the code as expected - capture by-reference (MSVC requires an explicit "template<typename... Args>" instead of just "auto &..." though).

Also, normal by-reference captures with initializers (i.e. "&arg = arg") work correctly (see CE example).
Optimization flags don't appear to affect the behavior.

<speculation>
Judging by the behavior of some real-world code, the ref-qualifier is simply ignored, and the capture is treated as if it was "by-copy".
</speculation>

**Comment by ilya-biryukov** [comment]
This bug seems like a huge deal. Two shorter examples:

```cpp
#include <iostream>

void assign_10(int &arg) { arg = 10; }
template <class ...T> void assign_10s(T &...args) {
    [&...args = args] () mutable { 
        ((args = 10), ...);
    }();
}

int main() {
    int a = 11;
    assign_10s(a);
    std::cout << a << "\n"; // must output 10, outputs 11 in Clang.
}
```
https://gcc.godbolt.org/z/9xd5dT4Gq

Should compile, does not compile in Clang due to use of copy constructor:
```cpp
struct X {
    X() = default;
    X(X const&) = delete;
};

void take_by_ref(auto &...args) {
    [&...args = args] {}();
}

int main() {
    X x;
    take_by_ref(x);
}

```
https://gcc.godbolt.org/z/a1cMraf9d
