### ISSUE TITLE
Race condition in libomptarget

### ISSUE THREAD

**Issue by hyviquel** [llvm/llvm-project#49284]
|  |  |
| --- | --- |
| Bugzilla Link | [49940](https://llvm.org/bz49940) |
| Version | unspecified |
| OS | Linux |
| Blocks | llvm/llvm-project#50083  |
| CC | @bryanpkc,@GuilhermeValarini,@jdoerfert,@JonChesterfield,@Meinersbur,@shiltian,@ye-luo |

## Extended Description 
The test "llvm-project/openmp/libomptarget/test/offloading/bug49334.cpp" fails aleatory with both cuda and x86_64 plugins, most probably because of a race condition within the device-agnostic part of libomptarget. This test is implementing a block-based matrix multiplication that has the particularity to create multiple asynchronous offloaded kernels (omp target nowait) that can be executed in parallel (thus the race condition).

The issue can be reproduced by executing the test multiple times: 

- For CUDA plugin
clang++ -O3 -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda ./llvm-project/openmp/libomptarget/test/offloading/bug49334.cpp -o blockmatmul-gpu
for i in {1..100}; do ./blockmatmul-gpu || break; done

- For x86 plugin 
clang++ -O3 -fopenmp -fopenmp-targets=x86_64-pc-linux-gnu ./llvm-project/openmp/libomptarget/test/offloading/bug49334.cpp -o blockmatmul-cpu
for i in {1..100}; do ./blockmatmul-cpu || break; done

The issue happens with the every recent versions of Clang (current development version, v12.x, v11.x)

**Comment by shiltian** [comment]
Fixed in 9584c6fa2fe216522b86ee5422147b511c73cb4a.
