### ISSUE TITLE
clang doesn't support K&R preprocessing (-traditional)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#4929]
|  |  |
| --- | --- |
| Bugzilla Link | [4557](https://llvm.org/bz4557) |
| Version | unspecified |
| OS | NetBSD |
| Attachments | [The example mentioned in the bug report](https://user-images.githubusercontent.com/60944935/143739557-2da76784-8c64-4ce0-916f-d1020a7de7fc.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic,@emaste,@jsonn |

## Extended Description 

"clang -traditional" gives different output compared to "gcc -traditional" on the following example. (This prevents the NetBSD kernel from building using clang, as this construct is used in several .S files...)

Example:
#define INTRSTUB(name, num) \
intr_/**/name/**/num: \
        nop
INTRSTUB(legacy,0)

"clang -traditional -E foo.S" outputs this as "intr_ legacy 0: nop"
"gcc -traditional -E foo.S" outputs this as "intr_legacy0: nop"

The clang version used: svn revision 75635.

**Comment by AaronBallman** [comment]
I do not envision a scenario in which we'd want to implement and support this functionality in Clang; we've been hardening against ancient C practices, and supporting new K&R C functionality goes against that. Closing as "wontfix", but if someone finds a very compelling case for reopening, we can reconsider at that time.
