### ISSUE TITLE
compile crash on template template

### ISSUE THREAD

**Issue by 4654e904-b91a-4b7b-9cc3-9b226e0fb17a** [llvm/llvm-project#49295]
|  |  |
| --- | --- |
| Bugzilla Link | [49951](https://llvm.org/bz49951) |
| Version | unspecified |
| OS | Linux |
| Attachments | [stderrhttps://user-images.githubusercontent.com/93435695/143762019-59156263-7a2b-4b7b-9c8d-148e1d2b465c.gz) |
| CC | @zygoloid,@oToToT |

## Extended Description 

Reproduction test case

Clang segfaults on the following code snippet:
```
template<typename T,
    template<T> class SType,
    template<T, template<T> class> class TT>
void fun() {
    TT<T{}, SType>{};
}
```

https://wandbox.org/permlink/lU7e5aeViujWSRnD

Probably related?
llvm/llvm-project#36200

**Comment by Endilll** [comment]
Still crashing as of Clang 16: https://godbolt.org/z/PenWfWKhj
