### ISSUE TITLE
ICE in clang::RecordDecl::field_begin()

### ISSUE THREAD

**Issue by ldalessa** [llvm/llvm-project#49302]
|  |  |
| --- | --- |
| Bugzilla Link | [49958](https://llvm.org/bz49958) |
| Version | 11.0 |
| OS | All |
| Attachments | [preprocessed source](https://user-images.githubusercontent.com/92601274/143762020-08548d7b-3fc3-472c-a3da-4be80f759aca.gz), [build script](https://user-images.githubusercontent.com/92601274/143762021-88e7b1c8-1d87-4595-85cc-6658d44db00a.gz) |
| CC | @zygoloid |

## Extended Description 
Code compiles without issue with gcc-10.3, so I assume this is valid code.

See attached preprocessed source.

****

PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/bin/clang++ -DFMT_LOCALE -I/home/ldalessa/open/ttl20/include -I/home/ldalessa/open/ttl20/clang/_deps/ce-src/include -I/home/ldalessa/open/ttl20/clang/_deps/eve-src/include -I/home/ldalessa/open/ttl20/clang/_deps/fmt-src/include -fconstexpr-backtrace-limit=0 -ferror-limit=1 -g -std=gnu++20 -o CMakeFiles/test.dir/test.cpp.o -c /home/ldalessa/open/ttl20/tests/test.cpp 
1.	/home/ldalessa/open/ttl20/tests/test.cpp:20:42: current parser token ';'
2.	/home/ldalessa/open/ttl20/tests/test.cpp:19:1: parsing function body 'main'
3.	/home/ldalessa/open/ttl20/tests/test.cpp:19:1: in compound statement ('{}')
 #&#8203;0 0x00007f6e1c43cf8f llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1+0xbd0f8f)
 #&#8203;1 0x00007f6e1c43b2f0 llvm::sys::RunSignalHandlers() (/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1+0xbcf2f0)
 #&#8203;2 0x00007f6e1c43c6dd llvm::sys::CleanupOnSignal(unsigned long) (/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1+0xbd06dd)
 #&#8203;3 0x00007f6e1c380dc0 (/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1+0xb14dc0)
 #&#8203;4 0x00007f6e23615140 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14140)
 #&#8203;5 0x00007f6e2154fa70 clang::RecordDecl::field_begin() const (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xbe5a70)
 #&#8203;6 0x00007f6e215ef0bd (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc850bd)
 #&#8203;7 0x00007f6e215ee91b (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc8491b)
 #&#8203;8 0x00007f6e215df468 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc75468)
 #&#8203;9 0x00007f6e2160ce21 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xca2e21)
#&#8203;10 0x00007f6e215c88ca (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc5e8ca)
#&#8203;11 0x00007f6e215e7909 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc7d909)
#&#8203;12 0x00007f6e215e6739 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc7c739)
#&#8203;13 0x00007f6e215cdae0 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc63ae0)
#&#8203;14 0x00007f6e2160c665 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xca2665)
#&#8203;15 0x00007f6e215ef6b8 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc856b8)
#&#8203;16 0x00007f6e215c88ca (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc5e8ca)
#&#8203;17 0x00007f6e215f18f5 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc878f5)
#&#8203;18 0x00007f6e215c88ca (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc5e8ca)
#&#8203;19 0x00007f6e2162ad73 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xcc0d73)
#&#8203;20 0x00007f6e2162a20f (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xcc020f)
#&#8203;21 0x00007f6e215c9235 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc5f235)
#&#8203;22 0x00007f6e215e654e (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc7c54e)
#&#8203;23 0x00007f6e215e6739 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc7c739)
#&#8203;24 0x00007f6e21614fed (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xcaafed)
#&#8203;25 0x00007f6e215cd5b4 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc635b4)
#&#8203;26 0x00007f6e2160e54e (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xca454e)
#&#8203;27 0x00007f6e215c86d4 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc5e6d4)
#&#8203;28 0x00007f6e2160f8b3 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xca58b3)
#&#8203;29 0x00007f6e215c8f29 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc5ef29)
#&#8203;30 0x00007f6e215ce413 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc64413)
#&#8203;31 0x00007f6e215cd58e (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc6358e)
#&#8203;32 0x00007f6e2160e54e (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xca454e)
#&#8203;33 0x00007f6e2160ef60 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xca4f60)
#&#8203;34 0x00007f6e215c86d4 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc5e6d4)
#&#8203;35 0x00007f6e215e71f2 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc7d1f2)
#&#8203;36 0x00007f6e215e6739 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc7c739)
#&#8203;37 0x00007f6e215cdae0 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc63ae0)
#&#8203;38 0x00007f6e21615bd8 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xcabbd8)
#&#8203;39 0x00007f6e2160ef60 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xca4f60)
#&#8203;40 0x00007f6e215c86d4 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc5e6d4)
#&#8203;41 0x00007f6e215e71f2 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc7d1f2)
#&#8203;42 0x00007f6e215e6739 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc7c739)
#&#8203;43 0x00007f6e215cdae0 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc63ae0)
#&#8203;44 0x00007f6e21615bd8 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xcabbd8)
#&#8203;45 0x00007f6e2160ef60 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xca4f60)
#&#8203;46 0x00007f6e215c86d4 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc5e6d4)
#&#8203;47 0x00007f6e215e71f2 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc7d1f2)
#&#8203;48 0x00007f6e215e6739 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc7c739)
#&#8203;49 0x00007f6e215cdae0 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc63ae0)
#&#8203;50 0x00007f6e21615bd8 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xcabbd8)
#&#8203;51 0x00007f6e2160ef60 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xca4f60)
#&#8203;52 0x00007f6e215c86d4 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc5e6d4)
#&#8203;53 0x00007f6e215e71f2 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc7d1f2)
#&#8203;54 0x00007f6e215e6739 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc7c739)
#&#8203;55 0x00007f6e215cdae0 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc63ae0)
#&#8203;56 0x00007f6e21615bd8 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xcabbd8)
#&#8203;57 0x00007f6e2160ef60 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xca4f60)
#&#8203;58 0x00007f6e215c86d4 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc5e6d4)
#&#8203;59 0x00007f6e215c9a05 clang::Expr::EvaluateAsInitializer(clang::APValue&, clang::ASTContext const&, clang::VarDecl const*, llvm::SmallVectorImpl<std::pair<clang::SourceLocation, clang::PartialDiagnostic> >&) const (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xc5fa05)
#&#8203;60 0x00007f6e215495c3 clang::VarDecl::evaluateValue(llvm::SmallVectorImpl<std::pair<clang::SourceLocation, clang::PartialDiagnostic> >&) const (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xbdf5c3)
#&#8203;61 0x00007f6e21549550 clang::VarDecl::evaluateValue() const (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xbdf550)
#&#8203;62 0x00007f6e21b3a128 clang::Sema::FinalizeVarWithDestructor(clang::VarDecl*, clang::RecordType const*) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x11d0128)
#&#8203;63 0x00007f6e21a8bf85 clang::Sema::CheckCompleteVariableDeclaration(clang::VarDecl*) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1121f85)
#&#8203;64 0x00007f6e21a89b6f clang::Sema::AddInitializerToDecl(clang::Decl*, clang::Expr*, bool) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x111fb6f)
#&#8203;65 0x00007f6e213564cb clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x9ec4cb)
#&#8203;66 0x00007f6e213542c9 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x9ea2c9)
#&#8203;67 0x00007f6e2134f9d9 clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x9e59d9)
#&#8203;68 0x00007f6e2134f683 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, clang::SourceLocation*) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x9e5683)
#&#8203;69 0x00007f6e213c42fe clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xa5a2fe)
#&#8203;70 0x00007f6e213c3e0e clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xa59e0e)
#&#8203;71 0x00007f6e213cac20 clang::Parser::ParseCompoundStatementBody(bool) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xa60c20)
#&#8203;72 0x00007f6e213cb9a5 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xa619a5)
#&#8203;73 0x00007f6e213e28a6 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xa788a6)
#&#8203;74 0x00007f6e213549b6 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x9ea9b6)
#&#8203;75 0x00007f6e213e1aad clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xa77aad)
#&#8203;76 0x00007f6e213e14bc clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xa774bc)
#&#8203;77 0x00007f6e213e0746 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xa76746)
#&#8203;78 0x00007f6e213dec9b clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0xa74c9b)
#&#8203;79 0x00007f6e213416ed clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x9d76ed)
#&#8203;80 0x00007f6e2290d0c8 clang::FrontendAction::Execute() (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1fa30c8)
#&#8203;81 0x00007f6e228c3641 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1f59641)
#&#8203;82 0x00007f6e22973200 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x2009200)
#&#8203;83 0x00000000004131bf cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang+++0x4131bf)
#&#8203;84 0x00000000004115fe (/usr/bin/clang+++0x4115fe)
#&#8203;85 0x00007f6e225f6732 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1c8c732)
#&#8203;86 0x00007f6e1c380bcd llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1+0xb14bcd)
#&#8203;87 0x00007f6e225f5c5f clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1c8bc5f)
#&#8203;88 0x00007f6e225cda7f clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1c63a7f)
#&#8203;89 0x00007f6e225cdc27 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1c63c27)
#&#8203;90 0x00007f6e225e178c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1c7778c)
#&#8203;91 0x00000000004110a3 main (/usr/bin/clang+++0x4110a3)
#&#8203;92 0x00007f6e1b397d0a __libc_start_main ./csu/../csu/libc-start.c:308:16
#&#8203;93 0x000000000040e89a _start (/usr/bin/clang+++0x40e89a)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Debian clang version 11.0.1-2
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/test-cb0e4c.cpp
clang: note: diagnostic msg: /tmp/test-cb0e4c.sh
clang: note: diagnostic msg:

**Comment by Izaron** [comment]
Just downloaded the source code and checked, it compiled successfully. Let me close this ticket =)

You can compile it, too
```
wget https://user-images.githubusercontent.com/92601274/143762020-08548d7b-3fc3-472c-a3da-4be80f759aca.gz
gzip -d 143762020-08548d7b-3fc3-472c-a3da-4be80f759aca.gz
bzip2 -d 143762020-08548d7b-3fc3-472c-a3da-4be80f759aca
mv 143762020-08548d7b-3fc3-472c-a3da-4be80f759aca.out a.cpp
clang++ a.cpp -c -std=gnu++20
```
