### ISSUE TITLE
llvm-c++filt unable to demangle lambda function names

### ISSUE THREAD

**Issue by lxfind** [llvm/llvm-project#49309]
|  |  |
| --- | --- |
| Bugzilla Link | [49965](https://llvm.org/bz49965) |
| Version | trunk |
| OS | All |

## Extended Description 
Compiling some simple code that contains lambdas using trunk Clang:https://godbolt.org/z/5qvqKqEe6

The lambda function name is "_ZZ3foovENK3$_0clEv".
However running llvm-cxxfilt from trunk cannot demangle it.

(godbolt seems to be able to demangle it, though)

**Comment by emaste** [comment]
Looks like it has since been addressed (testing with LLVM c++filt 16 that's part of the FreeBSD base system):

```
$ c++filt --version
c++filt
LLVM (http://llvm.org/):
  LLVM version 16.0.6
  Optimized build with assertions.
$ c++filt '_ZZ3foovENK3$_0clEv'
foo()::$_0::operator()() const
```
