### ISSUE TITLE
[concepts] ambiguous overload accepted as valid

### ISSUE THREAD

**Issue by ldalessa** [llvm/llvm-project#49308]
|  |  |
| --- | --- |
| Bugzilla Link | [49964](https://llvm.org/bz49964) |
| Version | 11.0 |
| OS | All |
| CC | @zygoloid |

## Extended Description 
Clang accepts the following concept code that gcc considers ambiguous (reduced testcase due to Patrick Palka).

```
  template <class T> concept C1 = true;
  template <class T> concept C2 = C1<T> && true;

  template <C1 T, C1 U> int f(T, U);
  template <C1 T, C2 U> int f(U, T);

  int x = f(0, 0); // expect error: ambiguous call
```

Live: https://godbolt.org/z/6K93d1Ye4

I originally submitted this as a gcc bug (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99963) but Patrick and Jason Merrill determined that gcc's behavior is correct.

According to their reading of the standard (I don't have the background to make this statement), this call to f should be ambiguous because the matching between the template argument index and function argument index is different in its two declarations.

**Comment by royjacobson** [comment]
It seems that GCC match the positions of function parameters and template parameters and check that it's the same for both functions. In GCC:

```c++
template <class T> concept C1 = true;
template <class T> concept C2 = C1<T> && true;

//              Switched--                 Switched--
template <C1 T, class V, class U> int f(T, V, U);
template <C2 T, class U, class V> int f(T, U, V);

//              Switched--                 Not switched--
template <C1 T, class V, class U> int g(T, V, U);
template <C2 T, class U, class V> int g(T, V, U);

int x = f(0, 0, 0); // No error.
int y = g(0, 0, 0); // Error: ambiguous call
```

It's a pretty dense part of the standard (P2113R0, #54039), but it seems to me that we need to check function parameters and template parameters separately and both cases should be well formed. Even if the GCC interpretation is correct I'm not sure how this matching would work in the case of more complicated template argument deduction.
