### ISSUE TITLE
LLVM 12 build fails on missing CompletionModelCodegen.py

### ISSUE THREAD

**Issue by jpalus** [llvm/llvm-project#49334]
|  |  |
| --- | --- |
| Bugzilla Link | [49990](https://llvm.org/bz49990) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
Building LLVM with subcomponents extracted in one common directory fails with:

  make[2]: *** No rule to make target '/mnt/data-fast/jan/rpm/BUILD/clang-tools-extra/clangd/quality/CompletionModelCodegen.py', needed by 'tools/clang/tools/extra/clangd/CompletionModel.h'.  Stop.
  make[2]: Leaving directory '/mnt/data-fast/jan/rpm/BUILD/llvm-12.0.0.src/build'

Notice that it tries to find CompletionModelCodegen.py in some odd location compared to real source location. This seems to be caused by quality/CompletionModel.cmake with path being fixed to match some specific build environment:

  set(model_compiler ${CMAKE_SOURCE_DIR}/../clang-tools-extra/clangd/quality/CompletionModelCodegen.py)

**Comment by arsenm** [comment]
Build issue on old release
