### ISSUE TITLE
Question on backporting DR fixes

### ISSUE THREAD

**Issue by a301f30d-0f86-4cec-94e2-271b5f9ba78e** [llvm/llvm-project#49335]
|  |  |
| --- | --- |
| Bugzilla Link | [49991](https://llvm.org/bz49991) |
| Version | trunk |
| OS | All |
| CC | @zygoloid |

## Extended Description 
I spent some time today investigating why Clang was rejecting the following code in C++17 mode, but not C++20. MSVC and GCC both accept it in C++17.

#include <optional>
struct C {
  C(C&) = default;
};
std::optional<C> o;

It seems https://wg21.link/cwg1331 was addressed by https://wg21.link/p641, which was accepted into C++20.

Clang has the following commit which applies the change only in C++20 mode:
https://github.com/llvm/llvm-project/commit/9b2c5e7c44fd28c31f4a0b088d0bf71da4fddfa5

Whereas GCC and MSVC seem to have applied it unconditionally.

Is there any policy for when defect fixes are applied in earlier standard modes?

**Comment by arsenm** [comment]
Question seems to have been answered
