### ISSUE TITLE
templated constexpr variable fails to deduce auto type in template context

### ISSUE THREAD

**Issue by GuillaumeDua** [llvm/llvm-project#49342]
|  |  |
| --- | --- |
| Bugzilla Link | [49998](https://llvm.org/bz49998) |
| Version | trunk |
| OS | Windows NT |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Using clang 12.0.0

Note : Maybe in correlation with llvm/llvm-project#42804 

Looks like Clang cannot evaluate an `auto` type for a constexpr template-variable which depends on another,  
when both depends on a template context.

See live example here on godbolt : https://godbolt.org/z/ofveeGoWe

```cpp
template <typename ... Ts>
struct foo
{
    constexpr inline static auto value = 42;
};

template <typename ... Ts>
struct bar
{
    template <typename U>
    constexpr static inline auto foo_value = foo<Ts...>::value; // KO
    // nb : replacing `auto` with `int` remove the error
};

static_assert(bar<int>::foo_value<int> == 42);
```

Which results in :

```log
<source>:15:40: error: invalid operands to binary expression ('const auto' and 'int')
```

Stackoverflow associated post : https://stackoverflow.com/questions/67127710/clang-invalid-operands-to-binary-expression-const-auto-and-int-with-cons

**Comment by cor3ntin** [comment]
Fixed in 13 https://godbolt.org/z/b1W96zjxK
