### ISSUE TITLE
Enable constraint-elimination by default

### ISSUE THREAD

**Issue by fhahn** [llvm/llvm-project#49344]
|  |  |
| --- | --- |
| Bugzilla Link | [50000](https://llvm.org/bz50000) |
| Version | trunk |
| OS | All |
| CC | @LebedevRI |

## Extended Description 
An umbrella bug to keep track of work towards enabling -constraint-elimination by default.

**Comment by fhahn** [comment]
The following existing issue are handled by `-constraint-elimination`:

- #47888
- #49229
- #53273 


The following issue are candidates that could be handled by `constraint-elimination` with further changes

- #46435
- #48253

**Comment by fhahn** [comment]
#58074 is also handled by ConstraintElimination.

**Comment by fhahn** [comment]
[#51358](https://github.com/llvm/llvm-project/issues/51358) could also be handled by ConstraintElimination, modulo the fact that GEP indices are treated as signed with respect to `inbounds` so we are treating `size_t` indices as possibly signed at the moment.

**Comment by fitzgen** [comment]
Hi @fhahn! Are there any presentations or docs I can read to learn more about `-constraint-elimination`, or is reading the source currently the best way to learn about how it works and its goals and all that? Thanks!

(Apologies if this is the wrong forum for a question like this!)

**Comment by fhahn** [comment]
I did a presentation during a previous LLLVM Dev meeting: https://www.youtube.com/watch?v=1hm5ZVmBEvo
