### ISSUE TITLE
clang-format 11 is no longer available via brew

### ISSUE THREAD

**Issue by paulb777** [llvm/llvm-project#49340]
|  |  |
| --- | --- |
| Bugzilla Link | [49996](https://llvm.org/bz49996) |
| Version | 11.0 |
| OS | All |

## Extended Description 
The missing clang-format 11 on brew is problematic for our CI because of llvm/llvm-project#49339  in clang-format 12

**Comment by paulb777** [comment]
Our CI broke today because clang-format 13 disappeared from brew.

**Comment by rymiel** [comment]
I'm not really sure what is expected here, LLVM doesn't maintain anything related to external package managers (except for maybe apt and dnf listed on the home page?).
If you have a problem with how a package manager does things, maybe complain to the package manager?

**Comment by paulb777** [comment]
Opened https://github.com/Homebrew/homebrew-core/issues/114628

**Comment by JOE1994** [comment]
Closing as this seems unactionable from the LLVM side,
but please re-open if necessary.
