### ISSUE TITLE
Java Unsigned Right Shift Operator >>>

### ISSUE THREAD

**Issue by d239a4d1-7f20-402c-8d05-cc6a9c7257f5** [llvm/llvm-project#49356]
|  |  |
| --- | --- |
| Bugzilla Link | [50012](https://llvm.org/bz50012) |
| Version | trunk |
| OS | Windows NT |

## Extended Description 
ClangFormater wrongly split Java Unsigned Right Shift Operator >>> into parts.

I tried in different configurations - does not work.

you can check on this source for example: 

https://github.com/cheblin/PrimitiveCollections/blob/main/src/org/unirail/collections/BitsList.java

Sincerely yours Serguy.

**Comment by mydeveloperday** [comment]
I'm going to close this issue as its not reproducible with v8, v12 or v13

We need to know what is in your .clang-format and an example file (not in github which can change), its best if you break the problem down.

but this is what I see

```
Language: Java
BasedOnStyle: Google
```


```
import java.util.Arrays;

public interface BitsList {
  long FFFFFFFFFFFFFFFF = ~0L;

  static long mask(int bits) {
    return (1L << bits) - 1;
  }

  static int size(int src) {
    return src >>> 3;
  }

  static int index(int item_X_bits) {
    return item_X_bits >> LEN;
  }

  static int bit(int item_X_bits) {
    return item_X_bits & MASK;
  }

  static long value(long src, int bit, int bits) {
    return src >>> bit & mask(bits);
  }

  static long value(long prev, long next, int bit, int bits) {
    return ((next & mask(bit + bits - BITS)) << BITS - bit | prev >>> bit) & mask(bits);
  }

  int BITS = 64;
  int MASK = BITS - 1;
  int LEN = 6;

  static int len4bits(int bits) {
    return (bits + BITS) >>> LEN;
  }
}
```

I will close this issue, if you still think its a problem please reopen
