### ISSUE TITLE
clang crashes when invoked with full path

### ISSUE THREAD

**Issue by mmozeiko** [llvm/llvm-project#49360]
|  |  |
| --- | --- |
| Bugzilla Link | [50016](https://llvm.org/bz50016) |
| Version | trunk |
| OS | Windows NT |
| CC | @zygoloid |

## Extended Description 
Running clang v12 with "C:\Program Files\LLVM\bin\"clang.exe command line crashes it. The location of quotes are important. It produces following output:

PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.

Running it with "C:\Program Files\LLVM\bin\clang.exe" command line works.

Running other executables with "C:\path\to\"executable.exe works fine on my Windows.

**Comment by Endilll** [comment]
Doesn't reproduce with Clang 16.
