### ISSUE TITLE
python lit modyle dist 12.0.0

### ISSUE THREAD

**Issue by 4084477f-e1df-4024-a410-168c80096e18** [llvm/llvm-project#49362]
|  |  |
| --- | --- |
| Bugzilla Link | [50018](https://llvm.org/bz50018) |
| Version | trunk |
| OS | Windows NT |
| CC | @cmatthew |

## Extended Description 
https://pypi.org/project/lit/ still show that latest version is 0.11.1.
I canot find any details from where is possible to download latest version of the dist tar ball with lit module and as lit module git repo is internal part of the llvm it is hard to extract latest version from git as well.

Can someone publish to pypi latest lit version?

**Comment by serge-sans-paille** [comment]
This got fix a while ago. https://pypi.org/project/lit/#history shows a proper history where the latest tarballs are available.
