### ISSUE TITLE
llc: x86 atomic load i256 crash

### ISSUE THREAD

**Issue by Liblor** [llvm/llvm-project#49376]
|  |  |
| --- | --- |
| Bugzilla Link | [50032](https://llvm.org/bz50032) |
| Version | trunk |
| OS | Linux |
| CC | @topperc,@RKSimon,@phoebewang,@rotateright |

## Extended Description 
Even though an atomic load of i256 isn't possible on x86, it shouldn't crash ideally.

https://godbolt.org/z/6bccv3efq

%V = load atomic i256, i256* %a unordered, align 32

**Comment by JOE1994** [comment]
With the attached godbolt link, llc trunk no longer crashes while compiling the given input IR.
Please re-open if needed.
