### ISSUE TITLE
[clangd] clangd -check always looks for compilation database

### ISSUE THREAD

**Issue by sylvain-audi** [llvm/llvm-project#49409]
|  |  |
| --- | --- |
| Bugzilla Link | [50065](https://llvm.org/bz50065) |
| Version | unspecified |
| OS | Windows NT |

## Extended Description 
Here is a diff with updated tests to show the bug: https://reviews.llvm.org/differential/diff/339267

With the current codebase they fail on the line `// CHECK-NOT: Loaded compilation database from`.

This is not blocking for us, as https://reviews.llvm.org/D98824 fixed the edge effect that was causing tests to fail on our side.

However I think it's worth keeping track of it.

@&#8203;sammccall Can I let you take a look when you have time?

**Comment by HighCommander4** [comment]
@sylvain-audi Is this bug report still relevant? If so, could you describe a bit more what you'd like to see happen here and what the motivation is?

**Comment by sylvain-audi** [comment]
Hello, I  can't recall precisely what the issue was, I don't think it's still relevant.
I will close it, thanks!
