### ISSUE TITLE
Nary Reassociate pass still hangs on min/max code

### ISSUE THREAD

**Issue by clin111** [llvm/llvm-project#49434]
|  |  |
| --- | --- |
| Bugzilla Link | [50090](https://llvm.org/bz50090) |
| Version | trunk |
| OS | All |
| Attachments | [Test case, hangs reassociation](https://user-images.githubusercontent.com/92601583/143762064-b48c30dd-e5b7-432e-b8c8-7f709f805ee0.gz) |

## Extended Description 

Attached test case still hangs between 2 min/min reassociation patterns, even after commit 36b932d6 (which fixed one similar case)

opt --debug --nary-reassociate small.ll

NARY: Found common sub-expr:   %tmp5 = call i64 @&#8203;llvm.umin.i64(i64 %tmp4, i64 16384)
NARY: Deleting:    %tmp10 = call i64 @&#8203;llvm.umin.i64(i64 %tmp9, i64 16384)
NARY: Inserting:   %tmp10.nary = call i64 @&#8203;llvm.umin.i64(i64 %tmp5, i64 %tmp)
NARY: Found common sub-expr:   %tmp2 = call i64 @&#8203;llvm.umin.i64(i64 %tmp, i64 %tmp1)
NARY: Deleting:    %tmp10.nary = call i64 @&#8203;llvm.umin.i64(i64 %tmp5, i64 %tmp)
NARY: Inserting:   %tmp10.nary.nary = call i64 @&#8203;llvm.umin.i64(i64 %tmp2, i64 16384)
NARY: Found common sub-expr:   %tmp5 = call i64 @&#8203;llvm.umin.i64(i64 %tmp4, i64 16384)
NARY: Deleting:    %tmp10.nary.nary = call i64 @&#8203;llvm.umin.i64(i64 %tmp2, i64 16384)
NARY: Inserting:   %tmp10.nary.nary.nary = call i64 @&#8203;llvm.umin.i64(i64 %tmp5, i64 undef)
.....

**Comment by nikic** [comment]
The fix has long since landed, so closing this.
