### ISSUE TITLE
Ability to turned off "--use-color" in run-clang-tidy.py

### ISSUE THREAD

**Issue by d97321dc-6cbe-4326-88f1-0c062d53aa69** [llvm/llvm-project#49441]
|  |  |
| --- | --- |
| Bugzilla Link | [50097](https://llvm.org/bz50097) |
| Version | unspecified |
| OS | Windows NT |

## Extended Description 
Since version 12.0, run-clang-tidy.py calls "clang-tidy" unconditionally with the command line option "--use-color".

See https://reviews.llvm.org/rGa07a2c88d96cc48d7d381a0300565090c24b9770

It would be nice to be able to turn this off with a command line option as the emitted ANSI color characters make parsing the output more complicated. 

One possibility is to allow to pass arbitrary command line options to clang-tidy. With such capability, passing "--use-color=false" would work.

**Comment by kesyog** [comment]
https://reviews.llvm.org/D119562
