### ISSUE TITLE
ASTReader uses `err_pch_langopt_mismatch` wrong

### ISSUE THREAD

**Issue by jdoerfert** [llvm/llvm-project#49451]
|  |  |
| --- | --- |
| Bugzilla Link | [50107](https://llvm.org/bz50107) |
| Version | 8.0 |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
The diagnostic expects 0 or 1, but the usage simply forwards LangOpts.Name, which is often much bigger. Triggers an unrelated assertion when it tries to diagnose that you used pch wrong.

**Comment by Endilll** [comment]
Seems to be addressed by https://github.com/llvm/llvm-project/commit/aba32abe2d93133a46f67764937a1c85d455dce8
CC @ChuanqiXu9

**Comment by ChuanqiXu9** [comment]
Yeah, this should be addressed. Thanks.
