### ISSUE TITLE
SymbolDCE can't see symbols in custom attr storage.

### ISSUE THREAD

**Issue by 850d4ab7-4143-43fb-923e-59c6acbb2120** [llvm/llvm-project#49478]
|  |  |
| --- | --- |
| Bugzilla Link | [50134](https://llvm.org/bz50134) |
| Version | unspecified |
| OS | Windows NT |
| CC | @jpienaar,@River707 |

## Extended Description 
Currently it's possible to put SymbolRefAttrs in custom attr storage but SymbolDCE won't see them and throw away symbols. The scenario where I'm using this happens to work today because there are other references in the IR that walkSymbolRefs can see but that's just by chance.

The issue is that SymbolDCE is using SymbolTable::getSymbolUses to do its liveness analysis however the implementation of getSymbolUses uses walkSymbolRefs that only sees top-level symbol attrs or those nested within array or dictionary attrs. It cannot walk into custom attrs that hold SymbolRefAttrs (or any arbitrary nesting) and thus will not mark the symbol live. The result is that if the only references are in custom attrs DCE will trigger when it shouldn't.

I suspect this could be solved with an attribute interface. I had to solve something similar for walking nested attributes during dialect conversion and used a walkAttributeStorage dialect interface method to do it, however now attribute interfaces exist and the same could probably be done much cleaner.

A workaround is to just throw a marker SymbolRefAttr on an op so that SymbolDCE retains the symbol, even if it's duplicate information with what is in the custom attr.

**Comment by River707** [comment]
This has been fixed. Attributes/Types can opt in to this using the SubElement(Attr|Type)Interfaces.
