### ISSUE TITLE
[PowerPC] [MMA] Add lxvp/stxvp and pair assemble/disassemble builtins with _mma_ prefix

### ISSUE THREAD

**Issue by ahsansaghir** [llvm/llvm-project#49503]
|  |  |
| --- | --- |
| Bugzilla Link | [50159](https://llvm.org/bz50159) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#48661  |
| CC | @DougGregor,@slacka,@nemanjai,@zygoloid,@tstellar |
| Fixed by commit(s) | 25bbff632d018d178272a61c0732203d53d3a2e3 |

## Extended Description 
Vector pair intrinsics and builtins were renamed in
https://reviews.llvm.org/D91974 to replace the _mma_ prefix by _vsx_.
However, some projects used the _mma_ version, so this patch adds
these intrinsics to provide compatibility:

__builtin_mma_lxvp -> __builtin_vsx_lxvp
__builtin_mma_stxvp -> __builtin_vsx_stxvp
__builtin_mma_assemble_pair -> __builtin_vsx_assemble_pair
__builtin_mma_disassemble_pair -> __builtin_vsx_disassemble_pair

**Comment by xgupta** [comment]
We can close this issue, as the patch is committed.
