### ISSUE TITLE
performance-inefficient-vector-operation not detected in member function

### ISSUE THREAD

**Issue by firewave** [llvm/llvm-project#49501]
|  |  |
| --- | --- |
| Bugzilla Link | [50157](https://llvm.org/bz50157) |
| Version | unspecified |
| OS | Windows NT |
| CC | @EugeneZelenko,@hokein |

## Extended Description 
```cpp
#include <vector>

struct A
{
 void f() const
 {
   std::vector<int> v_s;

   for (const auto& s : v_) {
     v_s.emplace_back(s);
   }
 }

  std::vector<int> v_;
};
```

This was reduced from a much bigger class where the variable was actually filled.

If I make both members static or implement it with a function and a global warning the warning is being reported.

Tested with version 11.0.1.

**Comment by njames93** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/0e0b0feff194358e5e68bf36f5a563d269fa8e88
