### ISSUE TITLE
Bindings/Go/go.test fails - lld flag treatment

### ISSUE THREAD

**Issue by bondhugula** [llvm/llvm-project#49539]
|  |  |
| --- | --- |
| Bugzilla Link | [50195](https://llvm.org/bz50195) |
| Version | trunk |
| OS | Linux |

## Extended Description 
[I couldn't find the right component to file this against. There appears to be nothing for Go bindings or even bindings?]

commit 1977c53b2ae425541a0ef329ca10cc8d5cacd0cd (origin/main)
Date:   Wed Apr 28 11:34:45 2021 +0900

A `ninja check-all` yields this single failure.

-------------------------
FAIL: LLVM :: Bindings/Go/go.test (1362 of 44478)
******************** TEST 'LLVM :: Bindings/Go/go.test' FAILED ********************
Script:
--
: 'RUN: at line 1';   /home/uday/llvm-project-upstream/build/bin/llvm-go go=/usr/bin/go test llvm.org/llvm/bindings/go/llvm
--
Exit Code: 1

Command Output (stdout):
--
FAIL	llvm.org/llvm/bindings/go/llvm [build failed]
FAIL

--
Command Output (stderr):
--
go build runtime/cgo: invalid flag in go:cgo_ldflag: -fuse-ld=lld

--

********************
********************
Failed Tests (1):
  LLVM :: Bindings/Go/go.test

Testing Time: 35.14s
  Unsupported      : 19076
  Passed           : 25341
  Expectedly Failed:    60
  Failed           :     1
------------------

cmake -G Ninja ../llvm    -DLLVM_ENABLE_PROJECTS="mlir"  -DLLVM_TARGETS_TO_BUILD="X86;NVPTX"    -DCMAKE_BUILD_TYPE=Release  -DLLVM_ENABLE_ASSERTIONS=ON  -DLLVM_ENABLE_LLD=ON -DLLVM_CCACHE_BUILD=ON

$ /usr/bin/go version
go version go1.14.12 linux/amd64

$ python --version
Python 3.6.8

$ cat /etc/*release*
CentOS Linux release 8.3.2011
Derived from Red Hat Enterprise Linux 8.3
NAME="CentOS Linux"
VERSION="8"

**Comment by xgupta** [comment]
Go binding has been removed from upstream with commit https://github.com/llvm/llvm-project/commit/bc839b4b4e27b6e979dd38bcde51436d64bb3699. We can close this issue now.
