### ISSUE TITLE
Segmentation fault parsing parameter pack expansion

### ISSUE THREAD

**Issue by ce21b4f1-a91e-4e26-ae47-5d7fa714a198** [llvm/llvm-project#49540]
|  |  |
| --- | --- |
| Bugzilla Link | [50196](https://llvm.org/bz50196) |
| Version | 10.0 |
| OS | FreeBSD |
| Attachments | [include-expanded cpp file](https://user-images.githubusercontent.com/92601497/143762089-b8f95553-8c78-42b3-84dc-1e8d4fb1fed8.gz), [run script](https://user-images.githubusercontent.com/92601497/143762090-de3c45f8-9683-42b1-9d3a-92f465ce19b2.gz) |
| CC | @zygoloid |

## Extended Description 
I got segfault compiling this code:

#include <utility>

template <std::size_t ...Ts>
struct Ice<std::make_index_sequence<sizeof(Ts...)>>
{};

I'm using clang 10.0.1, but I also reproduced the issue with clang 12 and trunk on godbolt https://godbolt.org/z/5eEsvWdxd

The issue persists if I omit parameter pack expansion on line 4:

#include <utility>

template <std::size_t ...Ts>
struct Ice<std::make_index_sequence<sizeof(Ts)>>
{};

**Comment by Endilll** [comment]
Fixed in Clang 14: https://godbolt.org/z/enzPqnT56
