### ISSUE TITLE
Bug in DIBuilder::createClassType

### ISSUE THREAD

**Issue by 28903b80-1ea1-43c6-9221-938e8fd8bef7** [llvm/llvm-project#49557]
|  |  |
| --- | --- |
| Bugzilla Link | [50213](https://llvm.org/bz50213) |
| Version | trunk |
| OS | All |

## Extended Description 
There is bug in llvm-project/llvm/lib/IR/DIBuilder.cpp in DICompositeType *DIBuilder::createClassType function. Both methods "createClassType" and "createStructType" use the same tag - "dwarf::DW_TAG_structure_type". So both for the class and for the structure we get "DW_TAG_structure_type" in IR.
For reproduce - just call attachment with "clang -cc1 -S -emit-llvm bug_reproduce.cpp -debug-info-kind=standalone"

**Comment by JOE1994** [comment]
In LLVM trunk, `DIBuilder::createClassType` & `DIBuilder::createStructType` now use different dwarf tags:

https://github.com/llvm/llvm-project/blob/e241964b9373786f327ce24b440e2a82a3c4eeea/llvm/lib/IR/DIBuilder.cpp#L502-L531
