### ISSUE TITLE
InstSimplify: incorrect fold of pointer comparison between globals

### ISSUE THREAD

**Issue by nunoplopes** [llvm/llvm-project#49552]
|  |  |
| --- | --- |
| Bugzilla Link | [50208](https://llvm.org/bz50208) |
| Version | trunk |
| OS | All |
| CC | @aqjune,@RKSimon,@nikic,@rotateright |

## Extended Description 
test: Transforms/InstSimplify/ConstProp/icmp-null.ll
The transformation below is only correct if the gep is over i8*, and not with non-byte-sized types. This is correct: https://alive2.llvm.org/ce/z/S_TsHW

----------------------------------------
@&#8203;g2 = global 4 bytes, align 4
@&#8203;g = global 8 bytes, align 4

define i1 @&#8203;null_gep_ne_global() {
  %__constexpr_0 = ptrtoint * @&#8203;g2 to i64
  %gep = gep * null, 8 x i64 %__constexpr_0  ; <-- notice the 8 x
  %cmp = icmp ne * %gep, @&#8203;g
  ret i1 %cmp
}
=>
@&#8203;g2 = global 4 bytes, align 4
@&#8203;g = global 8 bytes, align 4

define i1 @&#8203;null_gep_ne_global() {
  ret i1 1
}
Transformation doesn't verify!

ERROR: Value mismatch

Example:

Source:
i64 %__constexpr_0 = #x924925b6db6f5564 (10540997870133138788, -7905746203576412828)
* %gep = pointer(non-local, block_id=0, offset=-7905737407482647776)
i1 %cmp = #x0 (0)

SOURCE MEMORY STATE
===================
NON-LOCAL BLOCKS:
Block 0 >       size: 0 align: 1        alloc type: 0   address: 0
Block 1 >       size: 4 align: 4        alloc type: 0   address: 10540997870133138788
Block 2 >       size: 8 align: 4        alloc type: 0   address: 10541006666226903840

Target:
Source value: #x0 (0)
Target value: #x1 (1)

**Comment by nikic** [comment]
I went on a bit of a crusade and deleted a lot of the folds in this function, because they were all subtly incorrect. The one relevant to this report is gone in https://github.com/llvm/llvm-project/commit/6c031780aa2c08996d1351de5e7541c75d6645c5.
