### ISSUE TITLE
Default fp-contract behavior does not match documentation

### ISSUE THREAD

**Issue by andykaylor** [llvm/llvm-project#49566]
|  |  |
| --- | --- |
| Bugzilla Link | [50222](https://llvm.org/bz50222) |
| Version | trunk |
| OS | Windows NT |
| Blocks | llvm/llvm-project#45424  |
| CC | @DMG862,@mibintc,@nico,@zygoloid,@rotateright,@zahiraam |
| Fixed by commit(s) | https://reviews.llvm.org/rG48ad446a0fb2c9b98cb7047e4daf8a84c29cef8f |

## Extended Description 
According to the clang documentation for '-ffp-contract' (https://clang.llvm.org/docs/UsersManual.html#cmdoption-ffp-contract), the fp-contract state defaults to 'on' for languages other than CUDA/HIP . 

The documentation for '-ffp-model' (https://clang.llvm.org/docs/UsersManual.html#cmdoption-ffp-model) says that '-ffp-model=precise' implicitly enables '-ffp-contract=fast' and that 'precise' is the default.

It appears that the current behavior (at least for C input with an x86-64 target) is equivalent to -fp-contract=off when the '-ffp-model' option isn't used.

https://godbolt.org/z/7YM75hK9e

Obviously, the documentation for the default settings for fp-contract and fp-model are contradictory. I think the default described in the fp-contract documentation is correct and that setting should be used by -ffp-model=precise. Apart from the fp-contract setting, the default state is equivalent to fp-model=precise.

So, three things should happen:

1) Fix whatever it is that's causing clang to default to fp-contract=off.
2) The clang toolchain code that handles -ffp-model should be changed to use fp-contract=on instead of fp-contract=fast for the precise model.
3) Update the fp-model documentation.

FWIW, there was at one time a problem with one of the backends that was exposed if fp-contract was enabled at -O0. That may be why the default behavior isn't as documented.

**Comment by RKSimon** [comment]
@andykaylor Resolve this ?

**Comment by RKSimon** [comment]
Closing - the docs and actual fp-contract behavior should now match
