### ISSUE TITLE
Unable to use regular NULL as initializer for atomic function pointer in C

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#49563]
|  |  |
| --- | --- |
| Bugzilla Link | [50219](https://llvm.org/bz50219) |
| Version | trunk |
| OS | All |
| CC | @dwblaikie,@DougGregor,@zygoloid |

## Extended Description 
$ cat test-atomic.c 
typedef void (*fp)(void);
_Atomic fp ptr1 = ((void(*)(void))0);
_Atomic fp ptr2 = ((void*)0);
$ gcc -c test-atomic.c -Wall -Wextra
$ clang -c test-atomic.c
test-atomic.c:3:19: error: initializer element is not a compile-time constant
_Atomic fp ptr2 = ((void*)0);
                  ^~~~~~~~~~
1 error generated.

When initiailizing an _Atomic function pointer, which is a pointer to a function, clang errors out when initializing it to the common NULL define (which often expands to ((void*)0) in C). Using 0 cast to the right function pointer type works.

GCC accepts the construct without warnings.

**Comment by AaronBallman** [comment]
I can confirm that this is an issue. I looked into it briefly and the trouble is that when we go to check the assignment constraints, we first try the constraints on the non-atomic type and then tell the caller it was an atomic conversion. However, the non-atomic assignment creates an implicit bitcast that the constant expression evaluator thinks causes the initialization to be non-constant.

**Comment by gnaggnoyil** [comment]
Not sure if it's the same issue, but Clang C frontend emits a warning when the code tries to assign NULL to an _Atomic function pointer with `-pedantic` flags on.

The code:
```c
#include <stddef.h>

int main(void){
    _Atomic(int (*)(char)) a = NULL;
    (void)a;
    return 0;
}
```

Compile with `clang -std=c11 -pedantic`:
```
source.cpp:4:28: warning: initializing '_Atomic(int (*)(char))' with an expression of type 'void *' converts between void pointer and function pointer [-Wpedantic]
    _Atomic(int (*)(char)) a = NULL;
                           ^   ~~~~
```

**Comment by AaronBallman** [comment]
Potential fix: https://reviews.llvm.org/D148730

> Not sure if it's the same issue, but Clang C frontend emits a warning when the code tries to assign NULL to an _Atomic function pointer with `-pedantic` flags on.

I believe this is the same issue.
