### ISSUE TITLE
Did not see access type in access path!

### ISSUE THREAD

**Issue by berolinux** [llvm/llvm-project#49574]
|  |  |
| --- | --- |
| Bugzilla Link | [50230](https://llvm.org/bz50230) |
| Version | 12.0 |
| OS | Linux |
| Attachments | [Attachment (reduced from audacity 3.0.2)](https://user-images.githubusercontent.com/92601251/143762105-9afab943-fe97-4de5-ad91-291c794fa3f7.gz) |

## Extended Description 

$ clang++ -O -o test.o -c test.cpp
Did not see access type in access path!
  store i64 0, i64* %.fca.1.gep, align 8, !tbaa !&#8203;7
!&#8203;7 = !{#3, !&#8203;5, i64 0}
in function _Z3fn1v
fatal error: error in backend: Broken function found, compilation aborted!
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang++ -O -o test.o -c test.cpp
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'test.cpp'.
4.      Running pass 'Module Verifier' on function '@_Z3fn1v'
 #&#8203;0 0x00007fdaad4c0bc1 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib64/libLLVMSupport.so.12.0+0x235bc1)
 #&#8203;1 0x00007fdaad4c0e9d (/usr/lib64/libLLVMSupport.so.12.0+0x235e9d)
 #&#8203;2 0x00007fdaad4be7ea llvm::sys::RunSignalHandlers() (/usr/lib64/libLLVMSupport.so.12.0+0x2337ea)
 #&#8203;3 0x00007fdaad4bfddb llvm::sys::CleanupOnSignal(unsigned long) (/usr/lib64/libLLVMSupport.so.12.0+0x234ddb)
 #&#8203;4 0x00007fdaad3cff05 (/usr/lib64/libLLVMSupport.so.12.0+0x144f05)
 #&#8203;5 0x00007fdaad3cfe6f llvm::CrashRecoveryContext::HandleExit(int) (/usr/lib64/libLLVMSupport.so.12.0+0x144e6f)
 #&#8203;6 0x00007fdaad4b9ef7 llvm::sys::Process::Exit(int, bool) (/usr/lib64/libLLVMSupport.so.12.0+0x22eef7)
 #&#8203;7 0x0000000000219b46 (/usr/bin/clang-12+0x219b46)
 #&#8203;8 0x00007fdaad3e329b llvm::report_fatal_error(llvm::Twine const&, bool) (/usr/lib64/libLLVMSupport.so.12.0+0x15829b)
 #&#8203;9 0x00007fdaad3e3176 (/usr/lib64/libLLVMSupport.so.12.0+0x158176)
#&#8203;10 0x00007fdaada8827b (/usr/lib64/libLLVMCore.so.12.0+0x48327b)
#&#8203;11 0x00007fdaad9efb26 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib64/libLLVMCore.so.12.0+0x3eab26)
#&#8203;12 0x00007fdaad9f8683 llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/lib64/libLLVMCore.so.12.0+0x3f3683)
#&#8203;13 0x00007fdaad9f0798 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib64/libLLVMCore.so.12.0+0x3eb798)
#&#8203;14 0x00007fdaad9f8ba7 llvm::legacy::PassManager::run(llvm::Module&) (/usr/lib64/libLLVMCore.so.12.0+0x3f3ba7)
#&#8203;15 0x00007fdab0aed813 (/usr/lib64/libclangCodeGen.so.12.0+0x2a1813)
#&#8203;16 0x00007fdab0ae5eb7 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/usr/lib64/libclangCodeGen.so.12.0+0x299eb7)
#&#8203;17 0x00007fdab0e5058f (/usr/lib64/libclangCodeGen.so.12.0+0x60458f)
#&#8203;18 0x00007fdaaaca3495 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib64/libclangParse.so.12.0+0x70495)
#&#8203;19 0x00007fdaaf0d54cf clang::ASTFrontendAction::ExecuteAction() (/usr/lib64/libclangFrontend.so.12.0+0x1ab4cf)
#&#8203;20 0x00007fdab0e4b180 clang::CodeGenAction::ExecuteAction() (/usr/lib64/libclangCodeGen.so.12.0+0x5ff180)
#&#8203;21 0x00007fdaaf0d4b96 clang::FrontendAction::Execute() (/usr/lib64/libclangFrontend.so.12.0+0x1aab96)
#&#8203;22 0x00007fdaaf03a52a clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib64/libclangFrontend.so.12.0+0x11052a)
#&#8203;23 0x00007fdab19b5c38 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib64/libclangFrontendTool.so.12.0+0x5c38)
#&#8203;24 0x000000000021955f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang-12+0x21955f)
#&#8203;25 0x0000000000216e0f (/usr/bin/clang-12+0x216e0f)
#&#8203;26 0x00007fdaaed7c044 (/usr/lib64/libclangDriver.so.12.0+0x115044)
#&#8203;27 0x00007fdaad3cfdea llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/lib64/libLLVMSupport.so.12.0+0x144dea)
#&#8203;28 0x00007fdaaed7b38f clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/usr/lib64/libclangDriver.so.12.0+0x11438f)
#&#8203;29 0x00007fdaaed3c5ec clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/usr/lib64/libclangDriver.so.12.0+0xd55ec)
#&#8203;30 0x00007fdaaed3c8fa clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/usr/lib64/libclangDriver.so.12.0+0xd58fa)
#&#8203;31 0x00007fdaaed58d01 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/usr/lib64/libclangDriver.so.12.0+0xf1d01)
#&#8203;32 0x0000000000215f74 main (/usr/bin/clang-12+0x215f74)
#&#8203;33 0x00007fdaacea25dd __libc_start_main (/lib64/libc.so.6+0x285dd)
#&#8203;34 0x0000000000212a4a _start (/usr/bin/clang-12+0x212a4a)
clang-12: error: clang frontend command failed with exit code 70 (use -v to see invocation)
OpenMandriva 12.0.0-1 clang version 12.0.0 (/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/clang fb397346fdaf8788938313cb6d72bcedcd57d531)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-12: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-12: note: diagnostic msg: /tmp/test-bbfb6e.cpp
clang-12: note: diagnostic msg: /tmp/test-bbfb6e.sh
clang-12: note: diagnostic msg: 

********************

**Comment by shafik** [comment]
This does not reproduce: https://godbolt.org/z/Evjoe8Pqr

If I missed something and you can still reproduce please reopen with instructions on how to reproduce or a godbolt link if you can reproduce there.
