### ISSUE TITLE
Missing APPEND in ACCESS specifier of OPEN statement

### ISSUE THREAD

**Issue by oroppas** [llvm/llvm-project#49584]
|  |  |
| --- | --- |
| Bugzilla Link | [50240](https://llvm.org/bz50240) |
| Version | trunk |
| OS | Linux |
| CC | @jeanPerier,@kiranktp,@sscalpone |

## Extended Description 
Here's the minimal reproducer

program main
    lu = 60
    open(lu,file='dcp.out',status='old',access='append',err=10)
10  continue
end program main

flang-new -fc1 main.f90

./main.f90:3:48: error: Invalid ACCESS value 'append'
      open(lu,file='dcp.out',status='old',access='append',err=10)
                                                 ^^^^^^^^
error: Semantic errors in main.f90

**Comment by ekieri** [comment]
Hi! ACCESS=APPEND is actually not mentioned in the standard, but some compilers implement it as an extension (as an alias for POSITION=APPEND, leaving ACCESS at the default SEQUENTIAL). This extension was implemented in flang as well, in https://reviews.llvm.org/D102350. I can run your reproducer without error. I will close this issue, but please test it on your side, and do not hesitate to reopen if this does not solve your problem.
