### ISSUE TITLE
llc -O1 crashes in 'Canonicalize Freeze Instructions in Loops' with tons of SCEV calls on the call stack

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#49599]
|  |  |
| --- | --- |
| Bugzilla Link | [50255](https://llvm.org/bz50255) |
| Version | trunk |
| OS | Linux |
| Attachments | [bbi-35733_2.ll reproducer](https://user-images.githubusercontent.com/55733087/143762117-81d7584f-6120-45d1-83c3-4b427083368c.gz) |
| CC | @fhahn,@aqjune |

## Extended Description 

Reproduce with:
 llc -O1 -o /dev/null bbi-35733_2.ll

Result:
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /repo/uabelho/master-github/llvm/build-all/bin/llc -O1 -o /dev/null bbi-35733_2.ll
1.	Running pass 'Function Pass Manager' on module 'bbi-35733_2.ll'.
2.	Running pass 'Loop Pass Manager' on function '@g'
3.	Running pass 'Canonicalize Freeze Instructions in Loops' on basic block '%for.body'
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
/repo/uabelho/master-github/llvm/build-all/bin/llc(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamEi+0x23)[0x2803f73]
/repo/uabelho/master-github/llvm/build-all/bin/llc(_ZN4llvm3sys17RunSignalHandlersEv+0xee)[0x2801c2e]
/repo/uabelho/master-github/llvm/build-all/bin/llc[0x2804436]
/lib64/libpthread.so.0(+0xf630)[0x7f464da20630]
/repo/uabelho/master-github/llvm/build-all/bin/llc(_ZN4llvm15ScalarEvolution19createAddRecFromPHIEPNS_7PHINodeE+0x1)[0x19d5231]
[...]
/repo/uabelho/master-github/llvm/build-all/bin/llc(_ZN4llvm15ScalarEvolution10createSCEVEPNS_5ValueE+0x1736)[0x19cf916]
/repo/uabelho/master-github/llvm/build-all/bin/llc(_ZN4llvm15ScalarEvolution7getSCEVEPNS_5ValueE+0x47)[0x19cace7]
Segmentation fault

**Comment by fhahn** [comment]
Should be fixed by https://github.com/llvm/llvm-project/commit/675080a4533b91b3b62e51d3659629bc020fb940.  It would be great if you could verify it fixes the issue on your side.

**Comment by mikaelholmen** [comment]
> Should be fixed by [675080a](https://github.com/llvm/llvm-project/commit/675080a4533b91b3b62e51d3659629bc020fb940). It would be great if you could verify it fixes the issue on your side.

Yes, the fix indeed solves the issue we saw. Thanks!

**Comment by mikaelholmen** [comment]
Hm, of course I didn't mean to reopen the issue.
