### ISSUE TITLE
[[likely]]/[[unlikely]] is sensitive to surrounding braces

### ISSUE THREAD

**Issue by 7d0d9fba-701e-4ffd-be6e-a44841ab82d4** [llvm/llvm-project#49619]
|  |  |
| --- | --- |
| Bugzilla Link | [50275](https://llvm.org/bz50275) |
| Version | trunk |
| OS | MacOS X |
| CC | @dwblaikie,@Flowdalic,@zygoloid |

## Extended Description 
Example adapted from the example code in the standard  (section 9.12.6) (https://godbolt.org/z/58bxzo8oW):

    void g(int);
    int f(int n) {
        if (n > 5) [[unlikely]] {
            g(0);
            return n * 2 + 1;
        } else {
            g(1);
            return n * 5;
        }
    }

The clang-tidy readability-braces-around-statements check (and the hicpp/google equivalents) triggers here, and suggests adding braces before the attribute:

    <source>:3:15: warning: statement should be inside braces [readability-braces-around-statements]
        if (n > 5) [[unlikely]] {
                  ^
                   {
    1 warning generated.

However, inserting the braces as suggested results in the attribute having no effect on the generated assembly.

The assembly produced by GCC 11.1, for comparison, does depend on the presence/absence of [[unlikely]] regardless of the presence of the extra braces.

I'm not entirely sure whether clang-tidy's warning here is correct, but the presence/absence of braces affecting generated code here seems unintuitive.

**Comment by IGR2014** [comment]
Clang 13.0.0 (MSVC VS 2022 (v17.1.0) Preview 2.0) and this issue still not fixed!
I'm keep getting readability-braces-around-statements in clang-tidy

**Comment by IGR2014** [comment]
Mr. @asl , please, note - as i mentioned in my previous comment - same troubles on platform:windows too

**Comment by Izaron** [comment]
@IGR2014 Hi, seems like the bug is fixed in newer Clang versions
https://reviews.llvm.org/D105479
You can use a newer version of Clang. Let me close this bug =)

**Comment by IGR2014** [comment]
Yes, sorry, it's closed now (Clang 14.0.0+ tested by me)
