### ISSUE TITLE
Clang-Tidy reports wrong command line argument even though it is not specified at all

### ISSUE THREAD

**Issue by e1c453b9-0b23-409b-9745-bcb5a9600449** [llvm/llvm-project#49639]
|  |  |
| --- | --- |
| Bugzilla Link | [50295](https://llvm.org/bz50295) |
| Version | unspecified |
| OS | Windows NT |
| Attachments | [Configuration file](https://user-images.githubusercontent.com/93435656/143762127-1446ee25-eb0a-44c6-a877-f993d4e1622f.gz) |
| CC | @EugeneZelenko,@zmodem |

## Extended Description 

OS: Windows 10 (64-Bit)
LLVM Version: 12.0.0 (64-Bit)

I am calling clang-tidy on the regular windows command prompt like this:

"C:/Program Files/LLVM/bin/clang-tidy.exe" -quiet -fix -header-filter=MyFile.h -p=E:/MyProjekt.build ./MyFile.cpp

Please note that especially "-fsyntax-only" and "-resource-dir" are not specified on the command line.

The output of clang-tidy is:

./MyFile.cpp
8809 warnings and 2 errors generated.
Error while processing <..cut..>\MyFile.cpp.
error: no such file or directory: '-fsyntax-only'; did you mean '-fsyntax-only'? [clang-diagnostic-error]
error: no such file or directory: '-resource-dir=C:\Program Files\LLVM\lib\clang\12.0.0'; did you mean '-resource-dir=C:\Program Files\LLVM\lib\clang\12.0.0'? [clang-diagnostic-error]

This is obviously an error.

Attached you can also find my .clang-tidy configuration file.

**Comment by carlosgalvezp** [comment]
Problem does not seem related to clang-tidy, please open a ticket for clang-cl instead if the problem persists.

**Comment by smcpeak** [comment]
This bug was caused by the tooling infrastructure mishandling a `--` switch in the `command` field in `compile_commands.json`.  It was fixed in LLVM-13 or LLVM-14.  See https://stackoverflow.com/a/78460449/2659307 for more information.
