### ISSUE TITLE
opt -enable-loop-distribute -loop-distribute crashes with Assertion `Partition != -2 && "Pointer not belonging to any partition"' failed.

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#49632]
|  |  |
| --- | --- |
| Bugzilla Link | [50288](https://llvm.org/bz50288) |
| Version | trunk |
| OS | Linux |
| Attachments | [bbi-55997.ll reproducer](https://user-images.githubusercontent.com/55733087/143762123-c3f19630-dae9-4622-9c80-6f8ac2994768.gz) |
| CC | @fhahn |

## Extended Description 

Reproduce with:
 opt -enable-new-pm=0 -enable-loop-distribute -loop-distribute -o /dev/null bbi-55997.ll

Result
opt: ../lib/Transforms/Scalar/LoopDistribute.cpp:531: SmallVector<int, 8> (anonymous namespace)::InstPartitionContainer::computePartitionSetForPointers(const llvm::LoopAccessInfo &): Assertion `Partition != -2 && "Pointer not belonging to any partition"' failed.

This starts happening with 1ed7f8ede564

    [LAA] Support pointer phis in loop by analyzing each incoming pointer.
    
    SCEV does not look through non-header PHIs inside the loop. Such phis
    can be analyzed by adding separate accesses for each incoming pointer
    value.
    
    This results in 2 more loops vectorized in SPEC2000/186.crafty and
    avoids regressions when sinking instructions before vectorizing.
    
    Reviewed By: Meinersbur
    
    Differential Revision: https://reviews.llvm.org/D101286

**Comment by fhahn** [comment]
This should be fixed on current `main`: https://llvm.godbolt.org/z/8s44aWMbe

Likely fix is e248d69036da
