### ISSUE TITLE
coroutines + templates + "-fsanitize=undefined" = error in backend: Cannot represent a difference across sections (clang++ 10, 11, 12, trunk)

### ISSUE THREAD

**Issue by b4f3b224-355b-4482-903f-28d170811a09** [llvm/llvm-project#49689]
|  |  |
| --- | --- |
| Bugzilla Link | [50345](https://llvm.org/bz50345) |
| Version | unspecified |
| OS | Linux |
| Blocks | llvm/llvm-project#51489  |
| Attachments | [Code that crashes the compiler](https://user-images.githubusercontent.com/92979731/143762138-8a4d64b4-2885-40d9-82b4-4f2d8ce6679d.gz) |
| CC | @avikivity,@bhalevy,@lxfind,@pcc,@rjmccall,@tstellar,@yuanfang-chen |

## Extended Description 

The attached file causes clang++ to crash given certain compilation flags.
also godbolt: https://godbolt.org/z/j14YMxj5M

$ clang++ --version
    clang version 10.0.1 (Fedora 10.0.1-3.fc32)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
$ clang++ coro-crash.cpp -std=c++20 -stdlib=libc++ -fsanitize=undefined
    fatal error: error in backend: Cannot represent a difference across sections
    Stack dump:
    0.	Program arguments: /usr/bin/clang++ -std=c++20 -fsanitize=undefined -fcolor-diagnostics -stdlib=libc++ -c -o coro-crash.o coro-crash.cpp 
    1.	<eof> parser at end of file
    2.	Code generation
    /lib64/libLLVM-10.so(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x2e)[0x7f60b555e10e]
    /lib64/libLLVM-10.so(_ZN4llvm3sys17RunSignalHandlersEv+0x34)[0x7f60b555c3e4]
    /lib64/libLLVM-10.so(_ZN4llvm20CrashRecoveryContext10HandleExitEi+0x78)[0x7f60b549b768]
    /lib64/libLLVM-10.so(_ZN4llvm3sys7Process4ExitEi+0x1b)[0x7f60b5556ffb]
    /usr/bin/clang++(+0x16372)[0x55988c5f0372]
    /lib64/libLLVM-10.so(_ZN4llvm18report_fatal_errorERKNS_5TwineEb+0x8b)[0x7f60b54a702b]
    /lib64/libLLVM-10.so(+0x1bc7623)[0x7f60b66db623]
    /lib64/libLLVM-10.so(+0x1ba83c6)[0x7f60b66bc3c6]
    /lib64/libLLVM-10.so(_ZN4llvm11MCAssembler11handleFixupERKNS_11MCAsmLayoutERNS_10MCFragmentERKNS_7MCFixupE+0xf2)[0x7f60b66d2ed2]
    /lib64/libLLVM-10.so(_ZN4llvm11MCAssembler6layoutERNS_11MCAsmLayoutE+0x281)[0x7f60b66d40b1]
    /lib64/libLLVM-10.so(_ZN4llvm11MCAssembler6FinishEv+0x3d)[0x7f60b66d42ad]
    /lib64/libLLVM-10.so(_ZN4llvm10AsmPrinter14doFinalizationERNS_6ModuleE+0x731)[0x7f60b5c64b11]
    /lib64/libLLVM-10.so(_ZN4llvm13FPPassManager14doFinalizationERNS_6ModuleE+0x65)[0x7f60b5658895]
    /lib64/libLLVM-10.so(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x460)[0x7f60b5664220]
    /lib64/libclang-cpp.so.10(+0x16123e1)[0x7f60baea73e1]
    /lib64/libclang-cpp.so.10(_ZN5clang17EmitBackendOutputERNS_17DiagnosticsEngineERKNS_19HeaderSearchOptionsERKNS_14CodeGenOptionsERKNS_13TargetOptionsERKNS_11LangOptionsERKN4llvm10DataLayoutEPNSE_6ModuleENS_13BackendActionESt10unique_ptrINSE_17raw_pwrite_streamESt14default_deleteISM_EE+0x2fe)[0x7f60baea805e]
    /lib64/libclang-cpp.so.10(+0x190fb39)[0x7f60bb1a4b39]
    /lib64/libclang-cpp.so.10(_ZN5clang8ParseASTERNS_4SemaEbb+0x499)[0x7f60ba208c09]
    /lib64/libclang-cpp.so.10(_ZN5clang14FrontendAction7ExecuteEv+0xb9)[0x7f60bb83c139]
    /lib64/libclang-cpp.so.10(_ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE+0x1cd)[0x7f60bb7f827d]
    /lib64/libclang-cpp.so.10(_ZN5clang25ExecuteCompilerInvocationEPNS_16CompilerInstanceE+0x95c)[0x7f60bb8b212c]
    /usr/bin/clang++(_Z8cc1_mainN4llvm8ArrayRefIPKcEES2_Pv+0x6c0)[0x55988c5f1440]
    /usr/bin/clang++(+0x15a94)[0x55988c5efa94]
    /lib64/libclang-cpp.so.10(+0x1c8cec9)[0x7f60bb521ec9]
    /lib64/libLLVM-10.so(_ZN4llvm20CrashRecoveryContext9RunSafelyENS_12function_refIFvvEEE+0x27)[0x7f60b549b5e7]
    /lib64/libclang-cpp.so.10(_ZNK5clang6driver10CC1Command7ExecuteEN4llvm8ArrayRefINS2_8OptionalINS2_9StringRefEEEEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPb+0x157)[0x7f60bb524537]
    /lib64/libclang-cpp.so.10(_ZNK5clang6driver11Compilation14ExecuteCommandERKNS0_7CommandERPS3_+0x9d)[0x7f60bb4f8bed]
    /lib64/libclang-cpp.so.10(_ZNK5clang6driver11Compilation11ExecuteJobsERKNS0_7JobListERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0x86)[0x7f60bb4f9156]
    /lib64/libclang-cpp.so.10(_ZN5clang6driver6Driver18ExecuteCompilationERNS0_11CompilationERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0x93)[0x7f60bb501693]
    /usr/bin/clang++(main+0x14a6)[0x55988c5ebb86]
    /lib64/libc.so.6(__libc_start_main+0xf2)[0x7f60b4766042]
    /usr/bin/clang++(_start+0x2e)[0x55988c5ecc1e]

also checked through godbolt: crashes in clang 11 and clang trunk, clang 12 doesn't crash but prints errors.

None of these commands crash:
    clang++ coro-crash.cpp -std=c++20 -stdlib=libc++ -fsanitize=undefined -emit-llvm -Xclang -disable-llvm-passes -c
    clang++ coro-crash.cpp -std=c++20 -stdlib=libc++ -fsanitize=undefined -emit-llvm -Xclang -c

by https://llvm.org/docs/HowToSubmitABug.html#crashing-bugs I deduced that it's a backend bug (as if it wasn't obvious by the error message and the "Code generation" part in the dump).

However, after generating coro_crash.bc using:
    clang++ coro-crash.cpp -std=c++20 -stdlib=libc++ -fsanitize=undefined -emit-llvm -c -o coro_crash.bc
none of these commands crash either:
    llc coro_crash.bc
    llc coro_crash.bc -relocation-model=pic
    llc coro_crash.bc -relocation-model=static
Hence https://llvm.org/docs/HowToSubmitABug.html#backend-code-generator-bugs claims that I should follow instructions for front-end bugs, but every other evidence points to a backend bug, so dunno. Maybe it's a mix of bugs, frontent/middle passing incorrect input to backend or whatever.

Anyway, bugpoint doesn't want to cooperate with me either:
    bugpoint -run-llc coro_crash.bc
    Read input file      : 'coro_crash.bc'
    *** All input ok
    Initializing execution environment: Found llc: /usr/bin/llc
    Sorry, I can't automatically select a safe interpreter!

    Exiting.

So I guess that's all what I can give in this bug report.

**Comment by yuanfang-chen** [comment]
https://reviews.llvm.org/D115844

**Comment by avikivity** [comment]
Ugh, spent some time bisecting only to notice now that there's a patch ready.

Anyway bisected to

commit 5de2d189e6ad466a1f0616195e8c524a4eb3cbc0
Author: Yuanfang Chen <yuanfang.chen@sony.com>
Date:   Tue Feb 23 09:47:15 2021 -0800

    [Diagnose] Unify MCContext and LLVMContext diagnosing
    
    The situation with inline asm/MC error reporting is kind of messy at the
    moment. The errors from MC layout are not reliably propagated and users
    have to specify an inlineasm handler separately to get inlineasm
    diagnose. The latter issue is not a correctness issue but could be improved.
    
    * Kill LLVMContext inlineasm diagnose handler and migrate it to use
      DiagnoseInfo/DiagnoseHandler.
    * Introduce `DiagnoseInfoSrcMgr` to diagnose SourceMgr backed errors. This
      covers use cases like inlineasm, MC, and any clients using SourceMgr.
    * Move AsmPrinter::SrcMgrDiagInfo and its instance to MCContext. The next step
      is to combine MCContext::SrcMgr and MCContext::InlineSrcMgr because in all
      use cases, only one of them is used.
    * If LLVMContext is available, let MCContext uses LLVMContext's diagnose
      handler; if LLVMContext is not available, MCContext uses its own default
      diagnose handler which just prints SMDiagnostic.
    * Change a few clients(Clang, llc, lldb) to use the new way of reporting.
    
    Reviewed By: MaskRay
    
    Differential Revision: https://reviews.llvm.org/D97449

**Comment by avikivity** [comment]
I see the patch is rotting on the review board. Perhaps someone can review it?

**Comment by zhuhan0** [comment]
Hi, can someone with expertise in this area review the diff? Thanks.

**Comment by niekbouman** [comment]
Could this issue please be added to the clang v14 milestone as a release blocker?

**Comment by avikivity** [comment]
It's now been 7 weeks since the patch was posted, and no review activity.

@tstellar perhaps you can enlist a reviewer?

**Comment by tstellar** [comment]
This issue was not resolved in time for 14.0.0 and will need to be fixed in the next release (14.0.1).  If you disagree with this or you feel there was a mistake, please change the milestone back to 'LLVM 14.0.0 Release' so we can discuss.

**Comment by avikivity** [comment]
Another desperate try at getting someone to review this.

**Comment by avikivity** [comment]
Hurray! Can this be backported to 14.0.x please?

Many thanks for the fix.

**Comment by yuanfang-chen** [comment]
@avikivity It seems 14.0.6 is past due.

@tstellar any idea if there will be 14.0.7? Thanks.

**Comment by avikivity** [comment]
I suggest to backport it anyway, it can't hurt. And I do hope 14.0.7 is released. Coroutine users have had no usable compiler since 12.0.1 was released.

**Comment by avikivity** [comment]
@nikic any chance of getting this backported to 14.0.x? and getting a release cut?

**Comment by EugeneZelenko** [comment]
@avikivity: 15 is only maintained release branch.

**Comment by avikivity** [comment]
I see. It is unfortunate, 14 is broken, and 15 is unreleased, so there is no way to deliver a fix to users.

**Comment by kbr-** [comment]
And to think that this issue was once a release blocker for 13.0.1.

**Comment by kbr-** [comment]
@avikivity I recall you have a branch with this fix backported manually.
Maybe you could point to it or make a PR?

**Comment by yuanfang-chen** [comment]
I just checked the patch is already included in the 15.x release branch.

**Comment by kbr-** [comment]
Ah, I thought you were trying to backport it to 14.
Hope dies last :(

**Comment by avikivity** [comment]
> @avikivity I recall you have a branch with this fix backported manually. Maybe you could point to it or make a PR?

The problem is not with performing the backport. It is trivial and mechanical.

The problem is that 14.x is not getting updates, while 15.x is not released.
