### ISSUE TITLE
Assertion failure in absence of -isysroot ...

### ISSUE THREAD

**Issue by jlegare** [llvm/llvm-project#49687]
|  |  |
| --- | --- |
| Bugzilla Link | [50343](https://llvm.org/bz50343) |
| Version | unspecified |
| OS | All |
| Attachments | [Stack trace](https://user-images.githubusercontent.com/92601490/143762136-5abb1557-7580-4506-87d6-0a3568f13af2.gz) |
| CC | @DougGregor,@zygoloid |

## Extended Description 
The following program

   #include <map>

triggers an assert failure when compiled without -isysroot, as in

   $ /Volumes/Data/llvm-project-12.0.0/bld/bin/clang++ stuff.cpp `/Volumes/Data/llvm-project-12.0.0/bld/bin/llvm-config --cxxflags`

yielding

   Assertion failed: (!CodeSynthesisContexts.empty() && "Cannot perform an instantiation without some context on the " "instantiation stack"), function SubstType, file /Volumes/Data/llvm-project-12.0.0/llvm-project-12.0.0.src/clang/lib/Sema/SemaTemplateInstantiate.cpp, line 2071.

**Comment by Endilll** [comment]
Author hasn't got back to us.
