### ISSUE TITLE
Mapping of global scope deep object fails

### ISSUE THREAD

**Issue by 045c6aa7-a544-48c5-acb2-f7a740ee2539** [llvm/llvm-project#49691]
|  |  |
| --- | --- |
| Bugzilla Link | [50347](https://llvm.org/bz50347) |
| Version | unspecified |
| OS | Linux |
| Attachments | [reproducer](https://user-images.githubusercontent.com/92601485/143762139-4c4dd24d-119a-4eb0-b6ce-45f6ddb0d53d.gz) |
| CC | @alexey-bataev,@jdoerfert,@jtramm |

## Extended Description 

The code for this bug report is available here: 

https://github.com/jtramm/omp_target_issues/tree/master/global_test/class_A

When attempting to compile this code with clang++ for a V100 target I get the following error:

clang++ -Wall -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda -Xopenmp-target -march=sm_70 -g -c main.cpp -o main.o
<unknown>:0: error: expected relocatable expression
error: cannot compile inline asm
1 error generated.

The compiler version is:

$ clang++ --version
clang version 13.0.0 (https://github.com/llvm/llvm-project.git c82a0ae70e280c1c40b1af09ef275ddc7ed4254d)

**Comment by alexey-bataev** [comment]
Fixed in 638938117aeae5518d6cacd066ffd9830ef4fc9a
