### ISSUE TITLE
clang-tidy hicpp-signed-bitwise complains about macro expansion from system include

### ISSUE THREAD

**Issue by cfd43508-abed-4b61-9716-b28c9ef59019** [llvm/llvm-project#49695]
|  |  |
| --- | --- |
| Bugzilla Link | [50351](https://llvm.org/bz50351) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
Running `clang-tidy -checks=hicpp-signed-bitwise a.cpp -- -isystem sys-include-dir` on:

./a.cpp:

#include <b.hpp>

constexpr auto value = VALUE;

./sys-include-dir/b.hpp:

#define VALUE ( 'a' | 'b' )

I get:

/tmp/a.cpp:3:24: warning: use of a signed integer operand with a binary bitwise operator [hicpp-signed-bitwise]
constexpr auto value = VALUE;
                       ^
sys-include-dir/b.hpp:2:17: note: expanded from macro 'VALUE'
#define VALUE ( 'a' | 'b' )
                ^

I don't think this warning should fire in this situation because the issue is in a macro definition in a system header.

I'm using a recent build of main (5c8462b5daa2a17eadf5e9f6b976452369aa3a93, 2021-04-07).

**Comment by carlosgalvezp** [comment]
Warnings no longer stem from system headers.
