### ISSUE TITLE
[fuhcsia] Implement InitPrctl once TBI on Fuchsia is finalized

### ISSUE THREAD

**Issue by PiJoules** [llvm/llvm-project#49722]
|  |  |
| --- | --- |
| Bugzilla Link | [50378](https://llvm.org/bz50378) |
| Version | unspecified |
| OS | All |
| CC | @petrhosek,@frobtech |

## Extended Description 
InitPrctl() in the linux hwasan implementation seems to just check if TBI is enabled for the system during hwasan startup. While this can be empty for now in the fuchsia implementation, we should update this to also check for TBI once relevant changes for that are landed in zircon.

**Comment by EugeneZelenko** [comment]
@PiJoules: Could you please elaborate? Is it works in newer version(s)?
