### ISSUE TITLE
SystemZ data layout shouldn't depend on target features

### ISSUE THREAD

**Issue by aaronpuchert** [llvm/llvm-project#49730]
|  |  |
| --- | --- |
| Bugzilla Link | [50386](https://llvm.org/bz50386) |
| Version | trunk |
| OS | Linux |
| CC | @uweigand |

## Extended Description 
The SystemZ backend uses different target layouts depending on target features, specifically it adds v128:64 if vector extensions are used. This means that modules with different target features are not ABI-compatible, and would for example prevent a library using different features than an application. This is unprecedented and unexpected.

The commit message in ce4c10958502 states that

    However, for compatibility with old code that may use vector types, when
    *not* using the vector facility, the old alignment rules (vector types
    are naturally aligned) remain in use.

but I don't think that having the data layout feature-dependent helps compatibility either.

This issue surfaces e.g. in Postgres, where static modules are compiled with the default feature set, but the runtime JIT uses the feature set of the host. Subsequently JITted code and the static modules are incompatible.

In my view the "Vector ABI" should be made the default, or whether it is being used should be made part of the target triple. In any event, the data layout should not depend on the feature set and modules compiled with different features should be compatible. (And run on hardware that supports all of the features.)

**Comment by aaronpuchert** [comment]
@uweigand, it seems like [D131158](https://reviews.llvm.org/D131158) should fix this, right?

**Comment by uweigand** [comment]
> @uweigand, it seems like [D131158](https://reviews.llvm.org/D131158) should fix this, right?

Yes, indeed, this is fixed now.
