### ISSUE TITLE
lld does not clean up __eh_frame section after creating __unwind_info

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#49754]
|  |  |
| --- | --- |
| Bugzilla Link | [50410](https://llvm.org/bz50410) |
| Version | unspecified |
| OS | All |
| CC | @gkmhub,@int3,@thevinster,@smeenai,@oontvoo |

## Extended Description 
Repro:

1. Download https://drive.google.com/file/d/1j6_f55jX1WYjwrDSmQYbr_X043mLG9L2/view?usp=sharing

2. Unpack, cd chromium_framework

3. Remove `-dead_strip` from response.txt

4. `ld @&#8203;response.txt` 

5. `otool -l Chromium.app/Contents/Frameworks/Chromium\ Framework.framework/Chromium\ Framework | grep -A10 eh_frame | grep size`
  => size 0x00000000000ad310

6. `ld64.lld @&#8203;response.txt`, same otool
  => size 0x0000000002859c88

That's 0.676 MiB with ld vs 40.35 MiB with lld. The lld-linked 'Chromium.app/Contents/Frameworks/Chromium Framework.framework/Versions/Current/Chromium Framework' is 55M larger, so this is responsible for 72% of the bigger size.

(There's a "prune __eh_frame entries superseded by __unwind_info" TODO in UnwindInfoSection.cpp for this.)

---

Does anyone know why clang writes __eh_frame in addition to compact unwind? Having  the compiler write it only to have the linker remove it again seems a bit roundabout. There's a OmitDwarfIfHaveCompactUnwind in llvm/lib/MC/MCObjectFileInfo.cpp that seems to control that, but it's set to true only for watchOS, so it does seem intentional. I don't yet understand why though. 

(We should fix it in lld anyways, but maybe we could fix it in the compiler as well -- but I guess there's some reason against the latter that I don't see yet.

**Comment by int3** [comment]
Closed by 183bf8e1599.
