### ISSUE TITLE
wrong code caused by "-early-cse -instsimplify -jump-threading -constraint-elimination"

### ISSUE THREAD

**Issue by 952e6d5a-d994-4724-a6d1-07613b2d95a8** [llvm/llvm-project#49819]
|  |  |
| --- | --- |
| Bugzilla Link | [50474](https://llvm.org/bz50474) |
| Version | trunk |
| OS | Linux |
| Attachments | [small.bc](https://user-images.githubusercontent.com/92601252/143762164-884a8232-9810-4792-a804-02cda99d16f0.gz), [small-opt.bc](https://user-images.githubusercontent.com/92601252/143762165-79bcbe95-59ae-442c-b077-2aab78766a10.gz) |

## Extended Description 

$clang -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git d56729b4a4393da9c65bdfe762b51f8b7b0ce0ca)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/oscar/compiler/llvm-project/build/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Selected multilib: .;@m64

$gcc small.c && ./a.out

$clang -O3 -c -emit-llvm  -femit-all-decls -mllvm -disable-llvm-optzns small.c

$opt -early-cse -instsimplify -jump-threading -constraint-elimination small.bc -o small-opt.bc

$clang small-opt.bc && ./a.out
hello!

---------------------------------------
#include<stdio.h>
char a;
void main() {
  int b = a ?: a;
  if (b)
    printf("hello!\n");
}

**Comment by fhahn** [comment]
Thanks for the report. Should be fixed by 413e47ecd447
