### ISSUE TITLE
I can't build an lldb project on x86

### ISSUE THREAD

**Issue by 14b5c1f9-e0fa-45e0-b97d-4e0b21d670cd** [llvm/llvm-project#49823]
|  |  |
| --- | --- |
| Bugzilla Link | [50479](https://llvm.org/bz50479) |
| Version | 12.0 |
| OS | Linux |
| CC | @JDevlieghere,@nealsid |

## Extended Description 
[ 96%] Building CXX object tools/lldb/source/Plugins/Process/Linux/CMakeFiles/lldbPluginProcessLinux.dir/NativeThreadLinux.cpp.o
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.cpp: In constructor 'lldb_private::process_linux::NativeRegisterContextLinux_x86_64::NativeRegisterContextLinux_x86_64(const lldb_private::ArchSpec&, lldb_private::NativeThreadProtocol&)':
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.cpp:296:34: error: use of deleted function 'lldb_private::process_linux::NativeRegisterContextLinux::NativeRegisterContextLinux()'
       m_reg_info(), m_gpr_x86_64() {
                                  ^
In file included from /builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.h:14:0,
                 from /builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.cpp:11:
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/./Plugins/Process/Linux/NativeRegisterContextLinux.h:18:7: note: 'lldb_private::process_linux::NativeRegisterContextLinux::NativeRegisterContextLinux()' is implicitly deleted because the default definition would be ill-formed:
 class NativeRegisterContextLinux
       ^
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/./Plugins/Process/Linux/NativeRegisterContextLinux.h:18:7: error: no matching function for call to 'lldb_private::NativeRegisterContextRegisterInfo::NativeRegisterContextRegisterInfo()'
In file included from /builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/./Plugins/Process/Linux/NativeRegisterContextLinux.h:12:0,
                 from /builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.h:14,
                 from /builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.cpp:11:
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/./Plugins/Process/Utility/NativeRegisterContextRegisterInfo.h:24:3: note: candidate: lldb_private::NativeRegisterContextRegisterInfo::NativeRegisterContextRegisterInfo(lldb_private::NativeThreadProtocol&, lldb_private::RegisterInfoInterface*)
   NativeRegisterContextRegisterInfo(
   ^
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/./Plugins/Process/Utility/NativeRegisterContextRegisterInfo.h:24:3: note:   candidate expects 2 arguments, 0 provided
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.cpp:296:34: error: use of deleted function 'lldb_private::NativeRegisterContextWatchpoint_x86::NativeRegisterContextWatchpoint_x86()'
       m_reg_info(), m_gpr_x86_64() {
                                  ^
In file included from /builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.h:15:0,
                 from /builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.cpp:11:
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/./Plugins/Process/Utility/NativeRegisterContextWatchpoint_x86.h:16:7: note: 'lldb_private::NativeRegisterContextWatchpoint_x86::NativeRegisterContextWatchpoint_x86()' is implicitly deleted because the default definition would be ill-formed:
 class NativeRegisterContextWatchpoint_x86
       ^
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/./Plugins/Process/Utility/NativeRegisterContextWatchpoint_x86.h:16:7: error: no matching function for call to 'lldb_private::NativeRegisterContextRegisterInfo::NativeRegisterContextRegisterInfo()'
In file included from /builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/./Plugins/Process/Linux/NativeRegisterContextLinux.h:12:0,
                 from /builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.h:14,
                 from /builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.cpp:11:
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/./Plugins/Process/Utility/NativeRegisterContextRegisterInfo.h:24:3: note: candidate: lldb_private::NativeRegisterContextRegisterInfo::NativeRegisterContextRegisterInfo(lldb_private::NativeThreadProtocol&, lldb_private::RegisterInfoInterface*)
   NativeRegisterContextRegisterInfo(
   ^
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/./Plugins/Process/Utility/NativeRegisterContextRegisterInfo.h:24:3: note:   candidate expects 2 arguments, 0 provided
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.cpp: In member function 'virtual llvm::Optional<lldb_private::process_linux::NativeRegisterContextLinux::SyscallData> lldb_private::process_linux::NativeRegisterContextLinux_x86_64::GetSyscallData()':
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.cpp:1043:50: error: could not convert '(const uint8_t*)(& Int80)' from 'const uint8_t* {aka const unsigned char*}' to 'llvm::ArrayRef<unsigned char>'
     return SyscallData{Int80, Args, lldb_eax_i386};
                                                  ^
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.cpp:1043:50: error: could not convert '(const uint32_t*)(& Args)' from 'const uint32_t* {aka const unsigned int*}' to 'llvm::ArrayRef<unsigned int>'
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.cpp:1050:54: error: could not convert '(const uint8_t*)(& Syscall)' from 'const uint8_t* {aka const unsigned char*}' to 'llvm::ArrayRef<unsigned char>'
     return SyscallData{Syscall, Args, lldb_rax_x86_64};
                                                      ^
/builddir/build/BUILD/llvm-project-llvmorg-12.0.0/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_x86_64.cpp:1050:54: error: could not convert '(const uint32_t*)(& Args)' from 'const uint32_t* {aka const unsigned int*}' to 'llvm::ArrayRef<unsigned int>'
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-vla-extension'
cc1plus: warning: unrecognized command line option '-Wno-deprecated-register'
cc1plus: warning: unrecognized command line option '-Wno-redundant-move'
make[2]: *** [tools/lldb/source/Plugins/Process/Linux/CMakeFiles/lldbPluginProcessLinux.dir/build.make:154: tools/lldb/source/Plugins/Process/Linux/CMakeFiles/lldbPluginProcessLinux.dir/NativeRegisterContextLinux_x86_64.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Scanning dependencies of target lldbPluginStructuredDataDarwinLog
[ 96%] Building CXX object tools/lldb/source/Plugins/StructuredData/DarwinLog/CMakeFiles/lldbPluginStructuredDataDarwinLog.dir/StructuredDataDarwinLog.cpp.o
make[1]: *** [CMakeFiles/Makefile2:112814: tools/lldb/source/Plugins/Process/Linux/CMakeFiles/lldbPluginProcessLinux.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Linking CXX static library ../../../../../../lib/liblldbPluginStructuredDataDarwinLog.a
[ 96%] Built target lldbPluginStructuredDataDarwinLog
make: *** [Makefile:152: all] Error 2

**Comment by arsenm** [comment]
Old build issue
