### ISSUE TITLE
[C2x] a label with a declaration should be allowed

### ISSUE THREAD

**Issue by haoxintu** [llvm/llvm-project#49822]
|  |  |
| --- | --- |
| Bugzilla Link | [50478](https://llvm.org/bz50478) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
Hi all.

I think this is a new feature in C2x but it seems clang still can not pass the following code.

$cat small.c
int main(){
L: 
    int a = 0;
    return 0;
}

clang complains "error: expected expression", while GCC accepts this well.

In Godbolt: https://godbolt.org/z/KhdYxrnhf

See also in GCC's implementation: 

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100353

I try to find a dup report but failed, maybe there is a dup case?

Thanks,
Haoxin

**Comment by uecker** [comment]
Also labels at the end of the compound statement are allowed in C2X.

**Comment by AaronBallman** [comment]
This was fixed by 8bd06d5b65845e5e01dd899a2deb773580460b89
