### ISSUE TITLE
TEST 'MemorySanitizer-X86_64 :: fstat.cpp' FAILED

### ISSUE THREAD

**Issue by 3b3be5bc-be97-4c5a-a058-de8ddaf7c081** [llvm/llvm-project#49835]
|  |  |
| --- | --- |
| Bugzilla Link | [50491](https://llvm.org/bz50491) |
| Version | 12.0 |
| OS | Linux |
| Blocks | llvm/llvm-project#51489  |
| CC | @tstellar |

## Extended Description 
Obtained this error on Ubuntu 21.04 12.0.1 rc1 release run.

FAIL: MemorySanitizer-X86_64 :: fstat.cpp (76302 of 87931)
******************** TEST 'MemorySanitizer-X86_64 :: fstat.cpp' FAILED ********************
Script:
--
: 'RUN: at line 1';      /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-12.0.1-rc1.obj/./bin/clang  --driver-mode=g++ -fsanitize=memory -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls  -m64  -gline-tables-only -O0 /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/compiler-rt/test/msan/fstat.cpp -o /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-12.0.1-rc1.obj/projects/compiler-rt/test/msan/X86_64/Output/fstat.cpp.tmp &&  /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-12.0.1-rc1.obj/projects/compiler-rt/test/msan/X86_64/Output/fstat.cpp.tmp
--
Exit Code: 1

Command Output (stderr):
--
==2490251==WARNING: MemorySanitizer: use-of-uninitialized-value
    #&#8203;0 0x49b929 in main /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/compiler-rt/test/msan/fstat.cpp:11:7
    #&#8203;1 0x7f73b634f564 in __libc_start_main csu/../csu/libc-start.c:332:16
    #&#8203;2 0x41d24d in _start (/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-12.0.1-rc1.obj/projects/compiler-rt/test/msan/X86_64/Output/fstat.cpp.tmp+0x41d24d)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/compiler-rt/test/msan/fstat.cpp:11:7 in main
Exiting

**Comment by mgorny** [comment]
FWICS this can be fixed by backporting:

commit 6ab4a6b5cc1e5b03b9de0b35fafa081bc0502fe0 (HEAD -> gentoo-13.x)
Author: Nikita Malyavin <nikitamalyavin@gmail.com>
Date:   2021-10-21 01:53:50 +0200

    [msan] Add stat-family interceptors on Linux
    
    Add following interceptors on Linux: stat, lstat, fstat, fstatat.
    
    This fixes use-of-uninitialized value on platforms with GLIBC 2.33+.
    In particular: Arch Linux, Ubuntu hirsute/impish.
    
    The tests should have also been failing during the release on the mentioned platforms, but I cannot find any related discussion.
    
    Most likely, the regression was introduced by glibc commit [[ https://github.com/bminor/glibc/commit/8ed005daf0ab03e142500324a34087
ce179ae78e | 8ed005daf0ab03e14250032 ]]:
    all stat-family functions are now exported as shared functions.
    
    Before, some of them (namely stat, lstat, fstat, fstatat) were provided as a part of libc_noshared.a and called their __xstat doppl
egangers. This is still true for Debian Sid and earlier Ubuntu's. stat interceptors may be safely provided for them, no problem with th
at.
    
    Closes https://github.com/google/sanitizers/issues/1452.
    See also https://jira.mariadb.org/browse/MDEV-24841
    
    Reviewed By: eugenis
    
    Differential Revision: https://reviews.llvm.org/D111984

CC @FooBarrior

I have mixed feelings whether we should backport it — on one hand, it seems a bit complex, on the other it isn't that long and applies cleanly.

**Comment by mgorny** [comment]
(sorry, wrong commit id in the original comment, fixed now)

**Comment by tstellar** [comment]
Merged: b40f07b048c4

**Comment by DimitryAndric** [comment]
This needs an additional cherry-pick to make it compile on non-Linux platforms.

**Comment by tstellar** [comment]
Merged: b40f07b048c4

**Comment by tstellar** [comment]
Merged: b9a243d1cac2 5869ea6c6254
