### ISSUE TITLE
counting_semaphore constructor is neither explicit or constexpr

### ISSUE THREAD

**Issue by HugGa** [llvm/llvm-project#49865]
|  |  |
| --- | --- |
| Bugzilla Link | [50521](https://llvm.org/bz50521) |
| Version | 11.0 |
| OS | All |
| CC | @mclow |

## Extended Description 
According to the comments at the top of the semaphore file as well as the current draft c++23 standard as provided by eel.is and a draft c++20 standard as provided on the open-std website, counting_semaphore's constructor to be standards compliant must be both explicit and constexpr to be conformant, currently in the github repository itself this is not the case and has never been the case since the original patch was submitted.

**Comment by Quuxplusone** [comment]
Fixed a couple months ago by c9af0e61fa85842ce280ddab8ab491de38a7ae5b and d0eaf75320ea72c4da55060b6c42aad923870814 (both backported to release/13.x).
