### ISSUE TITLE
Split up the transforms library?

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#49874]
|  |  |
| --- | --- |
| Bugzilla Link | [50530](https://llvm.org/bz50530) |
| Version | unspecified |
| OS | All |
| CC | @jpienaar,@River707 |

## Extended Description 
the MLIR lib/Transforms library contains some useful and dialect independent utilities like CSE and Canonicalize, but it also includes some dialect specific stuff and therefore links in a wide array of very domain and generally CPU-specific libraries:

 LINK_LIBS PUBLIC
  MLIRAffine
  MLIRAnalysis
  MLIRCopyOpInterface
  MLIRLinalg
  MLIRLoopLikeInterface
  MLIRMemRef
  MLIRSCF
  MLIRPass
  MLIRTransformUtils
  MLIRVector

TransformUtils also depends on a similar collection:

 LINK_LIBS PUBLIC
  MLIRAffine
  MLIRAnalysis
  MLIRLoopAnalysis
  MLIRMemRef
  MLIRSCF
  MLIRPass
  MLIRRewrite
  MLIRStandard

Should this be split up?

**Comment by River707** [comment]
This has recently been fixed. Both Analysis and Transforms are free from dialect dependencies.

**Comment by lattner** [comment]
Awesome! Thank you
