### ISSUE TITLE
[LNT] Drop python2 support for llvm-lnt

### ISSUE THREAD

**Issue by ju-sh** [llvm/llvm-project#49892]
|  |  |
| --- | --- |
| Bugzilla Link | [50548](https://llvm.org/bz50548) |
| Version | trunk |
| OS | Linux |

## Extended Description 
The repo at https://github.com/llvm/llvm-lnt/ still uses Python2.

Maybe they can be updated to Python3?

To python>=3.6 since 3.6 is the earliest version that hasn't reached end-of-life?

**Comment by JOE1994** [comment]
This has been addressed in March 2022 by https://github.com/llvm/llvm-lnt/commit/0e3a5f745de6dc1008fcfa1f4ae8076329bd217c
