### ISSUE TITLE
LICM regression: lost range metadata

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#49894]
|  |  |
| --- | --- |
| Bugzilla Link | [50550](https://llvm.org/bz50550) |
| Version | trunk |
| OS | Windows NT |
| CC | @fhahn,@jdoerfert,@LebedevRI,@nikic,@rotateright |

## Extended Description 
#include <stddef.h>

bool s;

bool test1() {
    bool r = false;

    for(size_t i = 0; i < 1; ++i) {
        if (s)
            r = true;
    }

    return r;
}

bool test2() {
    bool r = false;

    for(size_t i = 0; i < 2; ++i) {
        if (s)
            r = true;
    }

    return r;
}

test1():                              # @&#8203;test1()
        cmp     byte ptr [rip + s], 0
        setne   al
        ret
test2():                              # @&#8203;test2()
        mov     al, byte ptr [rip + s]
        ret
s:
        .byte   0                               # 0x0

https://godbolt.org/z/rGv7z9q5W

BTW, LLVM 12 and lower produces same ideal codegen for both functions

**Comment by davidbolvansky** [comment]
cc @wsmoses

**Comment by wsmoses** [comment]
Godbolt shows this is now equivalent to the LLVM 12 desired assembly on trunch, presumably due to the recent change I pushed to preserve metadata on LICM: https://github.com/llvm/llvm-project/commit/d9da6a535f21946cfaac1516ef28ac7646211d56

**Comment by davidbolvansky** [comment]
Thanks!
