### ISSUE TITLE
lambda implicit copy capture triggered from within an OpenMP critical section crashes

### ISSUE THREAD

**Issue by b08f556e-6a57-4f9c-9851-0d0a54507e53** [llvm/llvm-project#49904]
|  |  |
| --- | --- |
| Bugzilla Link | [50560](https://llvm.org/bz50560) |
| Version | 12.0 |
| OS | Linux |
| Attachments | [files generated during crash + console log + command line + original source](https://user-images.githubusercontent.com/92601482/143762179-1724a2a3-10bc-4a80-b8a3-0b6f0e4a5b14.gz) |
| CC | @zygoloid |

## Extended Description 

```cpp
// the following code crashes clang (llvm project 12.0.0)
int main()
{
  for(int i=0;i<3;i++)
  {
    auto mylambda = [=](int& x)
    { 
#     pragma omp critical
      x+=i;
    };
    mylambda(i);
  }
  return 0;
}
```

**Comment by hainest** [comment]
I've encountered this with a slightly smaller reproducer. I've tried in all versions from 7 to 17, and only clang-12 is affected.

```c++
int foo(int id) {
  return [id]() {
    #pragma omp critical
    {
      return id;
    }
  }();
}
```

[preprocess-source.txt](https://github.com/llvm/llvm-project/files/13877831/preprocess-source.txt)
[run-script.txt](https://github.com/llvm/llvm-project/files/13877832/run-script.txt)
[stacktrace.txt](https://github.com/llvm/llvm-project/files/13877833/stacktrace.txt)

Likely the same as #49321.

**Comment by Endilll** [comment]
@hainest If this has been fixed in 13, it would be nice to leave a Compiler Explorer link and close both issues. Can you prepare a Compiler Explorer reproducer? Unfortunately, we can't just paste in our `cc1` run scripts there.

**Comment by hainest** [comment]
@Endilll Here's a [godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIM6SuADJ4DJgAcj4ARpjEIAAcpAAOqAqETgwe3r7%2ByanpAiFhkSwxcYl2mA4ZQgRMxARZPn4BldUCtfUERRHRsQm2dQ1NOa1D3aG9pf3xAJS2qF7EyOwcoQQA1PyoEOsbeOizGyYA7FYaAIIbG8SYBEsMxwCsFgcmTwAiEEen51fXxzMAGYksQmMAWEwNqgWEkNshiOlRLQTJcAcczqj/ujbvdiI83kC/ujTh8sddSd8TESsaSOPNaJwnrw/BwtKRUJw3NZrBsFItlphAUCeKQCJp6fMANb%2BMwAOiekkkGhFIq4XEVADZ9JxJCyJRzOLwFCANGKJfM4LAYFAbRAkGhYXRYuRKI6ks64sgDEYuGYNGaaLQCLETRAogaoqF6gBPTiiqPMYgxgDyUW0VXF3F4jrYghTDFocbZvCwUS8wDcYloJuzpCwkKM4hL9bwt2qADdMLX2ZhVFUvCH47x1phGS3aHgomDkx4sAaCIiWMP5lQDMAFAA1PCYADuKaSjGHMkEIjE7CkJ/kSjUBt0XH0hmMPMs%2BinJsg81QSUcAlrAFp%2BEPBhYWpD5JyiGEkl4VAu2IREsA/b5bDHTMMhcBh3E8Zo9GCSYSjKPQUjSX9MmwnIH2IgoGB6Aj%2BgfNpSM6YZyL8BjUPaBhmImYo%2BjiBjxhGNjBi6Wi%2BIkeZ%2BSWFYJJ1DhmVIVl2U5DgNlUeJNX/TVJHhH1gA2P05Q0IyNggXBCBIYUuFmXgsy0WZpRAJ4zXHPVSGXZzFINFTjVNc0S0tO0HSgz1XQgd1PRQPSuCBAM%2BDoENiDDCMW0TWNjzS5M0wzBxj1zRgCALIsDTLCsq1oGtjwbJ9m3ZfB20cLse14PsByHOtR3HdkIJnGM51WdlFzwZds1Xdctx3fdgOPfhT2RC9pFm68VHUFtdACPSUBfGwIKQr8fwyACgMYUCgXAqcoJguCEO7eBJI40iMKw7JhLw3jpn4vISIyISiPyUixI%2BvRGJqQTWOBh7QdE/DxIErpfrhhpAcI6yFmki8GSZfUWxUtSNK0nTvSfAygSMkyzPwIhiCsmz/Ps%2BYEEwJgsDiZCZU81zseUo1bD8uzJTksxeA8s0lJgnn%2BcC%2BArUQEBFgIJJBzCiL6GIcJWFWdTNO03TicM4ze0pkgDj0Jaz3ES8lsUFa7z0XcwSSFc5IUsXDQ4FNB0VzZUCoPHtcJvSDPlA3TI8J1VZp2yLQZpmWcoRyOd1YWnNF7yeZNM1JdIGX7Tlz2lYocKQtV9W2E4LWCd1owg7Jw2LIQ03ZHNhar2t281tye2mEd0bna58X3fz73fYrnWiermLa9D4vYmFMxaclmPmf6NmU7ktzXZ83nM%2BjwXk88zeJd3mUThOOVJCeJ4AE5NQ0%2BJ74v6RxyBfu3ajgLMY4IWvJxo%2BP9IOCaRnCSCAA) link.

**Comment by Endilll** [comment]
Thank you!
Confirmed to not reproduce anymore even on assertion builds.
