### ISSUE TITLE
[coroutines] Incorrectly saving sp across suspension points in optimized builds on aarch64

### ISSUE THREAD

**Issue by 16eba54c-786e-481c-898d-b7ba12a6bc8f** [llvm/llvm-project#49918]
|  |  |
| --- | --- |
| Bugzilla Link | [50574](https://llvm.org/bz50574) |
| Version | trunk |
| OS | All |
| Attachments | [Repro (also shared in Godbolt)](https://user-images.githubusercontent.com/92979733/143762184-fbf4a65d-3068-488f-8163-9229366e42ec.gz) |
| CC | @zygoloid |

## Extended Description 

A simple repro is at https://godbolt.org/z/z8ajGhvcx and attached as well. Compile with "-std=c++2a -g0 -O3 -stdlib=libc++" using "armv8-a clang (trunk)" and found to repro with clang 11 as well.

The essence is this, using fmtlib (version 7.1.3):

void check(int a)
{
  fmt::print("{}\n", a);
}

when writing:

int main()
{
    check(123);
    check(321);
}

compiled code executes correctly and prints 123, 321. In optimized builds, it is noted that the compiler inlines fmt::print and deduplicates some common code for the two calls to check.

When writing:

task<int> f(std::vector<int> v)
{
#if REPRO
    for (auto& x : v)
#endif
    {
        check(123);

        co_await std::experimental::suspend_always();

        check(321);
    }
    co_return 42;
}

the compiled code has an issue, and the executing code prints 123, garbage. Looking at the assembly, it seems that the compiler spills "sp" into the coroutine frame as part of the first call to check:

  mov w10, #&#8203;1
  mov x11, sp               ; sp is here
  stp x10, x11, [x19, #&#8203;32]  ; gets stored here (A)
  cmp x9, x8
  stp x10, x11, [x19, #&#8203;48]  ; gets stored here (B)
  b.eq .LBB3_7
  ldr x8, [x19, #&#8203;64]
.LBB3_5:
  ldp x2, x3, [x19, #&#8203;32]    ; gets loaded here (A) into x3
  str x8, [x19, #&#8203;80]
  mov w8, #&#8203;123
  stp x8, xzr, [sp]
  adrp x0, .L.str
  add x0, x0, :lo12:.L.str
  mov w1, #&#8203;3
  bl fmt::v7::vprint(fmt::v7::basic_string_view<char>, fmt::v7::format_args)

For the second call site of check, after the suspension point, the compiler emits:

  ldp x2, x3, [x19, #&#8203;48]    ; gets loaded here (B) into x3
  mov w8, #&#8203;321
  stp x8, xzr, [sp]
  adrp x0, .L.str
  add x0, x0, :lo12:.L.str
  mov w1, #&#8203;3
  bl fmt::v7::vprint(fmt::v7::basic_string_view<char>, fmt::v7::format_args)

where it is loading the former value of "sp" which gets consumed by vprint, resulting in garbage.

**Comment by avikivity** [comment]
Does not reproduce on clang 15.0.4, but does not prove anything.

I did see coroutine miscompiles on aarch64 with -fsanitize=address and -Og, that went away with -O0.

**Comment by ChuanqiXu9** [comment]
Fixed in trunk. Let's track the new mentioned problem with  `-fsanitize=address -Og` and aarch64 in other issue pages.
