### ISSUE TITLE
Problem in Linking CXX shared library ../../lib/libLTO.so

### ISSUE THREAD

**Issue by c88027e7-b934-4e9a-99ac-8f5412dbf665** [llvm/llvm-project#49956]
|  |  |
| --- | --- |
| Bugzilla Link | [50612](https://llvm.org/bz50612) |
| Version | trunk |
| OS | Linux |
| Attachments | [make output log (after running make second time)](https://user-images.githubusercontent.com/93435611/143762196-2173daa8-18c0-47f0-b234-31099e57c627.gz) |
| CC | @DimitryAndric,@zygoloid |

## Extended Description 

Hello, I have followed the following sequence to build and make Clang Project on my Ubuntu PC (installed with Ubuntu 20.10) - 
Step 1- git clone https://github.com/llvm/llvm-project.git
Step 2- cd llvm-project
Step 3- mkdir build
Step 4- cd build
Step 5- cmake -DLLVM_ENABLE_PROJECTS=clang -G "Unix Makefiles" ../llvm
Step 6- make

I was able to complete cmake without any issue. 
During make process: all LLVM files are compiled except few due to missing header files in CMakeError, and finally the program was struck during libLTO linking process...

I have run it two times:  In the first trial program was automatically terminated after continuing trials for 5-6 hours after displaying some error messages. In the second trial (after enabling verbose flag), after observing the similar situation for continuing this trial for around 3 hours, I have terminated this program.

Please see the terminal display log as per attachment and let me know what additional input is required.

In my PC, I have following configuration -
CMake : 3.16.3
GCC : 10.2.0
Python: 3.8.5
zlib1g: 1:1.2.11.dfsg-2ubuntu4
GNU Make: 4.3

**Comment by Nivekiba** [comment]
I also got the same error.
Please anyone can help ?

**Comment by fhahn** [comment]
Without specifying `-DCMAKE_BUILD_TYPE=xxx`, LLVM is built as unoptimized debug build. This can require a lot of memory when linking. This is likely the reason your job gets killed. 

Please try building with `-DCMAKE_BUILD_TYPE=Release`. For more otptions, please see https://llvm.org/docs/CMake.html#frequently-used-cmake-variables .

I am closing this now, as the provided information does not indicate any issue with LLVM itself. If there's a LLVM related problem, please feel free to re-open with more info.

**Comment by rturrado** [comment]
This issue has been closed by saying: just build in Release mode.

What happens if you are a developer and really need to build in Debug mode?

If  this is a memory issue, isn't there any workarounds to that?

Thanks!
