### ISSUE TITLE
cpp backend does not support new API (LLVMContext, etc)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#4997]
|  |  |
| --- | --- |
| Bugzilla Link | [4625](https://llvm.org/bz4625) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 
; ModuleID = 'test.bc'

define void @&#8203;test(i32 %value) nounwind  {
entry:
    %tmp0 = icmp eq i32 %value, 0
    ret void
}

after llvm-as and llc -march=cpp calling we have this C++ code:

// Generated by llvm2cpp - DO NOT MODIFY!

Module* makeXorEncryptModule(Module *mod) {

mod->setModuleIdentifier("test.ll.bc");

// Type Definitions
std::vector<const Type*>FuncTy_0_args;
FuncTy_0_args.push_back(IntegerType::get(32));
FunctionType* FuncTy_0 = FunctionType::get(
  /*Result=*/Type::VoidTy,
  /*Params=*/FuncTy_0_args,
  /*isVarArg=*/false);

// Function Declarations

Function* func_test = Function::Create(
  /*Type=*/FuncTy_0,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"test", mod); 
func_test->setCallingConv(CallingConv::C);
AttrListPtr func_test_PAL;
{
  SmallVector<AttributeWithIndex, 4> Attrs;
  AttributeWithIndex PAWI;
  PAWI.Index = 4294967295U; PAWI.Attrs = 0  | Attribute::NoUnwind;
  Attrs.push_back(PAWI);
  func_test_PAL = AttrListPtr::get(Attrs.begin(), Attrs.end());
  
}
func_test->setAttributes(func_test_PAL);

// Global Variable Declarations

// Constant Definitions
ConstantInt* const_int32_1 = ConstantInt::get(APInt(32,  "0", 1, 10));

// Global Variable Definitions

// Function Definitions

// Function: test (func_test)
{
  Function::arg_iterator args = func_test->arg_begin();
  Value* int32_value = args++;
  int32_value->setName("value");
  
  BasicBlock* label_entry = BasicBlock::Create("entry",func_test,0);
  
  // Block entry (label_entry)
  ICmpInst* int1_tmp0 = new ICmpInst(ICmpInst::ICMP_EQ, int32_value, const_int32_1, "tmp0", label_entry);
  ReturnInst::Create(label_entry);
  
}

return mod;

}

This code valid for llvm 2.5, but not for top-of-tree(for example ConstantInt::get call at line 39 is obsolete).

**Comment by arsenm** [comment]
cpp backend no longer exists
