### ISSUE TITLE
Backport: "Fix DW_AT_ranges DW_FORM_sec_offset not using DW_AT_rnglists_base (used by GCC)"

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#50009]
|  |  |
| --- | --- |
| Bugzilla Link | [50665](https://llvm.org/bz50665) |
| Version | 12.0 |
| OS | Linux |
| Blocks | llvm/llvm-project#48661  |
| CC | @dwblaikie,@jankratochvil |
| Fixed by commit(s) | a28facba1ccdc957f386b7753f4958307f1bfde8 942cf225650928734e645078beb039b6108080d2 9dd861a4f53968c732531de5d4488ace20d6d075 d1310817194aad488c86f4fb627c33090600a4a9 |

**Comment by arsenm** [comment]
Old release
