### ISSUE TITLE
Warnings about identifier __i0 when the struct contains C array of std::string

### ISSUE THREAD

**Issue by alex65536** [llvm/llvm-project#50006]
|  |  |
| --- | --- |
| Bugzilla Link | [50662](https://llvm.org/bz50662) |
| Version | unspecified |
| OS | Linux |
| Attachments | [The source file to reproduce](https://user-images.githubusercontent.com/93435605/143762216-0f5bd22d-e5a1-4eae-ab31-2fd3479b921c.gz), [.clang-tidy file which was used to reproduce the bug](https://user-images.githubusercontent.com/93435605/143762217-907772c1-e0a4-4642-8415-be084a9aeb23.gz) |
| CC | @alex65536 |

## Extended Description 

When a struct contains a C array of non-trivial type (like std::string), clang-tidy may yield strange warnings about __i0 identifier:

```
test.cpp:5:8: warning: declaration uses identifier '__i0', which is a reserved identifier [bugprone-reserved-identifier,cert-dcl37-c,cert-dcl51-cpp]
struct S {
       ^
note: this fix will not be applied because it overlaps with another fix
test.cpp:5:8: warning: invalid case style for variable '__i0' [readability-identifier-naming]
note: this fix will not be applied because it overlaps with another fix
/home/gepardo/tmp/reproduce/test.cpp:5:9: warning: statement should be inside braces [readability-braces-around-statements]
struct S {
        ^
         {
```

See the attached file to reproduce the bug.

The reason of the bug is as follows. Clang generates a move assignment operator for this class and includes its body into AST. The generated operator contains the variable __i0, which confuses clang-tidy.

**Comment by chfast** [comment]
This is a reproducer for clang-tidy 14.
```cpp
#include <memory>

struct X
{
    std::unique_ptr<X> m[1];

    X f()
    {
        *this = f();
        return {};
    }
};
```

```
> clang-tidy-14 --checks='-*,bugprone-reserved-identifier' source.cpp

source.cpp:3:8: error: declaration uses identifier '__i0', which is a reserved identifier [bugprone-reserved-identifier,-warnings-as-errors]
struct X
       ^
       _i0
```

**Comment by chfast** [comment]
This is fixed in clang-tidy-17.
