### ISSUE TITLE
Backport: "Defer the decision whether to use the CU or TU index until after reading the unit header."

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#50016]
|  |  |
| --- | --- |
| Bugzilla Link | [50672](https://llvm.org/bz50672) |
| Version | 12.0 |
| OS | Linux |
| CC | @dwblaikie,@jankratochvil |
| Fixed by commit(s) | 979ca1c05f83 |

**Comment by arsenm** [comment]
Old release
