### ISSUE TITLE
Backport: "Fix .debug_aranges parsing issues."

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#50015]
|  |  |
| --- | --- |
| Bugzilla Link | [50671](https://llvm.org/bz50671) |
| Version | 12.0 |
| OS | Linux |
| CC | @dwblaikie,@jankratochvil |
| Fixed by commit(s) | eee309068e6e02b6544b2c1809b3f672fa35b979 |

**Comment by arsenm** [comment]
Old release
