### ISSUE TITLE
Backport: "[lldb] Fix handling of `DW_AT_decl_file` according to D91014 (attempt #&#8203;2)"

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#50013]
|  |  |
| --- | --- |
| Bugzilla Link | [50669](https://llvm.org/bz50669) |
| Version | 12.0 |
| OS | Linux |
| CC | @dwblaikie,@jankratochvil |
| Fixed by commit(s) | 3b47bd32f9df4a57db98db5f35e680c7bd9fde3e |

**Comment by arsenm** [comment]
Old release
