### ISSUE TITLE
Backport: "[lldb] Support DWARF-5 DW_FORM_line_strp (used by GCC)"

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#50012]
|  |  |
| --- | --- |
| Bugzilla Link | [50668](https://llvm.org/bz50668) |
| Version | 12.0 |
| OS | Linux |
| Blocks | llvm/llvm-project#48661  |
| CC | @dwblaikie,@jankratochvil |
| Fixed by commit(s) | 4096ae06f47af9db2c2550a2c34979edfbd91b8d |

**Comment by arsenm** [comment]
Old release
