### ISSUE TITLE
Backport: "[lldb] Use CompileUnit::ResolveSymbolContext in SymbolFileDWARF"

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#50017]
|  |  |
| --- | --- |
| Bugzilla Link | [50673](https://llvm.org/bz50673) |
| Version | 12.0 |
| OS | Linux |
| Blocks | llvm/llvm-project#48661  |
| CC | @jankratochvil |
| Fixed by commit(s) | 68dafe40a69f799f69eeeb1f658da6e129c6d832 |

**Comment by arsenm** [comment]
Old release
