### ISSUE TITLE
Backport: "[LLDB] Re-land: Use path relative to binary for finding .dwo files."

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#50014]
|  |  |
| --- | --- |
| Bugzilla Link | [50670](https://llvm.org/bz50670) |
| Version | 12.0 |
| OS | Linux |
| CC | @jankratochvil |
| Fixed by commit(s) | 3dc24bc31edbc01dea085b24a6a6b024d7ae531c |

**Comment by arsenm** [comment]
Old release
