### ISSUE TITLE
Backport: "[lldb] Fix DWARF-5 DW_FORM_implicit_const (used by GCC)"

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#50011]
|  |  |
| --- | --- |
| Bugzilla Link | [50667](https://llvm.org/bz50667) |
| Version | 12.0 |
| OS | Linux |
| Blocks | llvm/llvm-project#48661  |
| CC | @dwblaikie,@jankratochvil |
| Fixed by commit(s) | cf806d91d562736192f91478eb47daa29c2230bf |

**Comment by arsenm** [comment]
Old release
