### ISSUE TITLE
InstCombine breaks calls of casted functions with type attributes

### ISSUE THREAD

**Issue by yotann** [llvm/llvm-project#50041]
|  |  |
| --- | --- |
| Bugzilla Link | [50697](https://llvm.org/bz50697) |
| Version | 12.0 |
| OS | Linux |
| CC | @efriedma-quic,@arsenm |

## Extended Description 
In LLVM 12.0.0, InstCombine can break call instructions of casted functions when type attributes (byval, sret, etc.) are involved. Example input:

%struct0 = type { i32 }
%struct1 = type { float }

declare void @&#8203;callee(%struct0* sret(%struct0))

define void @&#8203;caller() {
  %1 = alloca %struct1
  call void bitcast (void (%struct0*)* @&#8203;callee to void (%struct1*)*)(%struct1* sret(%struct1) %1)
  unreachable
}

When run through `opt -S -instcombine`, the output is:

%struct0 = type { i32 }

declare void @&#8203;callee(%struct0* sret(%struct0))

define void @&#8203;caller() {
  %1 = alloca %struct0, align 8
  call void @&#8203;callee(%struct0* nonnull sret(%struct1) %1)
  unreachable
}

This is invalid because the argument type (%struct0*) no longer matches the attribute type (%struct1).

**Comment by msebor** [comment]
Whoops, I hit Close Issue too soon.
The test case no longer compiles with the current trunk (it gives `error: argument attributes invalid in function type`) so I assume it was never meant to.
