### ISSUE TITLE
Bug: undefined behavior of constexpr static_cast from int to unscoped enum without fixed type outside range compiles fine on C++17

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#50055]
|  |  |
| --- | --- |
| Bugzilla Link | [50711](https://llvm.org/bz50711) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
Hi,

The following code is undefined behavior in C++17. And undefined behavior is not allowed in constant expressions - the compiler is required to diagnose it. Adapted from cppreference:

enum foo { a = 0, b = 1 }; 
constexpr foo x = static_cast<foo>(123); // undefined behavior since C++17

However Clang happily compiles this code:

https://godbolt.org/z/bzhWMxqoE

**Comment by jyknight** [comment]
Closed by shafik's commit b3645353041818f61e2580635409ddb81ff5a272.
