### ISSUE TITLE
std::ranges::size incorrectly uses perfect forwarding

### ISSUE THREAD

**Issue by 3a17e7c4-fca4-4827-b2a7-11a54d73d746** [llvm/llvm-project#50061]
|  |  |
| --- | --- |
| Bugzilla Link | [50717](https://llvm.org/bz50717) |
| Version | 12.0 |
| OS | All |
| CC | @mclow |

## Extended Description 
test/std/ranges/range.access/range.prim/size.pass.cpp has this check:

  assert(std::ranges::size(MoveOnlySizeFunction()) == 42);

which relies on this function being called with an rvalue:

   friend constexpr size_t size(MoveOnlySizeFunction) { return 42; }

However, the relevant part of the standard says an lvalue should be used:

"then ranges::size(E) is expression-equivalent to decay-copy(size(t))"

where 't' is an lvalue, i.e. it should not be forwarded.

As a result, the test fails for libstdc++ trunk (since I fixed the same bug earlier this month).

The spec was changed by https://wg21.link/p2091r0 to use lvalues everywhere except ranges::cdata.

**Comment by Quuxplusone** [comment]
Fixed in cb8a0b07974eb6a6aa681c30ce694e13b33a3db5
