### ISSUE TITLE
Backport LLDB commit 3bea730 to 12.0.x to fix build with GCC <= 6.5

### ISSUE THREAD

**Issue by chandlerc** [llvm/llvm-project#50076]
|  |  |
| --- | --- |
| Bugzilla Link | [50732](https://llvm.org/bz50732) |
| Version | unspecified |
| OS | All |
| Blocks | llvm/llvm-project#48661  |
| CC | @DimitryAndric,@emaste,@JDevlieghere,@jsonn,@tstellar |
| Fixed by commit(s) | 3bea7306e8669f94bacafae68748a9139cfc0b98 |

## Extended Description 
See https://lists.llvm.org/pipermail/lldb-commits/Week-of-Mon-20210614/074591.html

**Comment by arsenm** [comment]
Old release
