### ISSUE TITLE
Backport: "[BPF] add support for 32 bit registers in inline asm"

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#50074]
|  |  |
| --- | --- |
| Bugzilla Link | [50730](https://llvm.org/bz50730) |
| Version | 12.0 |
| OS | Linux |
| Blocks | llvm/llvm-project#48661 llvm/llvm-project#50032  |
| Fixed by commit(s) | 833e9b2ea7a7 |

**Comment by arsenm** [comment]
Old release
