### ISSUE TITLE
Backport: "[X86] add dwarf annotation for inline stack probe"

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#50072]
|  |  |
| --- | --- |
| Bugzilla Link | [50728](https://llvm.org/bz50728) |
| Version | 12.0 |
| OS | Linux |
| Blocks | llvm/llvm-project#48661 llvm/llvm-project#50032  |
| Fixed by commit(s) | 1c268a8ff4e9 |

**Comment by arsenm** [comment]
Old release
