### ISSUE TITLE
Race condition in regression test bug49334.cpp

### ISSUE THREAD

**Issue by Meinersbur** [llvm/llvm-project#50083]
|  |  |
| --- | --- |
| Bugzilla Link | [50739](https://llvm.org/bz50739) |
| Version | unspecified |
| OS | Linux |
| Depends On | llvm/llvm-project#49284  |
| CC | @hyviquel,@shiltian|

## Extended Description 
The regression test bug49334.cpp occasionally fails because of a race condition in the asynchronous data movement. The test case was introduced in https://reviews.llvm.org/D97329 to fix llvm/llvm-project#48678 . llvm/llvm-project#48678  was a null dereference not a race condition.

== https://lab.llvm.org/staging/#/builders/154/builds/540

******************** TEST 'libomptarget :: nvptx64-nvidia-cuda :: offloading/bug49334.cpp' FAILED ********************
Script:
--
: 'RUN: at line 1';   /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/./bin/clang++ -fopenmp  -fno-experimental-isel --cuda-path=/opt/cuda  -I /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.src/openmp/libomptarget/test -I /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/runtime/src -L /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/libomptarget -L /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/runtime/src  -fopenmp-targets=nvptx64-nvidia-cuda /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.src/openmp/libomptarget/test/offloading/bug49334.cpp -o /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/libomptarget/test/nvptx64-nvidia-cuda/offloading/Output/bug49334.cpp.tmp && /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/libomptarget/test/nvptx64-nvidia-cuda/offloading/Output/bug49334.cpp.tmp | /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/./bin/FileCheck /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.src/openmp/libomptarget/test/offloading/bug49334.cpp
--
Exit Code: 2
Command Output (stdout):
--
$ ":" "RUN: at line 1"
$ "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/./bin/clang++" "-fopenmp" "-fno-experimental-isel" "--cuda-path=/opt/cuda" "-I" "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.src/openmp/libomptarget/test" "-I" "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/runtime/src" "-L" "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/libomptarget" "-L" "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/runtime/src" "-fopenmp-targets=nvptx64-nvidia-cuda" "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.src/openmp/libomptarget/test/offloading/bug49334.cpp" "-o" "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/libomptarget/test/nvptx64-nvidia-cuda/offloading/Output/bug49334.cpp.tmp"
# command stderr:
clang-13: warning: Unknown CUDA version. cuda.h: CUDA_VERSION=11030. Assuming the latest supported version 10.1 [-Wunknown-cuda-version]
$ "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/libomptarget/test/nvptx64-nvidia-cuda/offloading/Output/bug49334.cpp.tmp"
note: command had no output on stdout or stderr
error: command failed with exit status: 1
$ "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/./bin/FileCheck" "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.src/openmp/libomptarget/test/offloading/bug49334.cpp"
# command stderr:
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/./bin/FileCheck /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.src/openmp/libomptarget/test/offloading/bug49334.cpp
error: command failed with exit status: 2
--
********************

******************** TEST 'libomptarget :: x86_64-pc-linux-gnu :: offloading/bug49334.cpp' FAILED ********************
Script:
--
: 'RUN: at line 1';   /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/./bin/clang++ -fopenmp  -fno-experimental-isel --cuda-path=/opt/cuda  -I /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.src/openmp/libomptarget/test -I /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/runtime/src -L /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/libomptarget -L /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/runtime/src  -fopenmp-targets=x86_64-pc-linux-gnu /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.src/openmp/libomptarget/test/offloading/bug49334.cpp -o /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/libomptarget/test/x86_64-pc-linux-gnu/offloading/Output/bug49334.cpp.tmp && /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/libomptarget/test/x86_64-pc-linux-gnu/offloading/Output/bug49334.cpp.tmp | /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/./bin/FileCheck /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.src/openmp/libomptarget/test/offloading/bug49334.cpp
--
Exit Code: 2
Command Output (stdout):
--
$ ":" "RUN: at line 1"
$ "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/./bin/clang++" "-fopenmp" "-fno-experimental-isel" "--cuda-path=/opt/cuda" "-I" "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.src/openmp/libomptarget/test" "-I" "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/runtime/src" "-L" "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/libomptarget" "-L" "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/runtime/src" "-fopenmp-targets=x86_64-pc-linux-gnu" "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.src/openmp/libomptarget/test/offloading/bug49334.cpp" "-o" "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/libomptarget/test/x86_64-pc-linux-gnu/offloading/Output/bug49334.cpp.tmp"
$ "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/runtimes/runtimes-bins/openmp/libomptarget/test/x86_64-pc-linux-gnu/offloading/Output/bug49334.cpp.tmp"
note: command had no output on stdout or stderr
error: command failed with exit status: 1
$ "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/./bin/FileCheck" "/home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.src/openmp/libomptarget/test/offloading/bug49334.cpp"
# command stderr:
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.build/./bin/FileCheck /home/buildbot-worker/minipc-1050ti-linux/openmp-offload-cuda-runtime/llvm.src/openmp/libomptarget/test/offloading/bug49334.cpp
error: command failed with exit status: 2
--
********************

**Comment by shiltian** [comment]
As we have a tracker for the issue (https://github.com/llvm/llvm-project/issues/49284), this one will be closed.
