### ISSUE TITLE
[clang-tidy] __has_builtin mishandled when using modules

### ISSUE THREAD

**Issue by a9a17457-d695-4da4-b95c-b6e90b75e085** [llvm/llvm-project#50087]
|  |  |
| --- | --- |
| Bugzilla Link | [50743](https://llvm.org/bz50743) |
| Version | unspecified |
| OS | All |

## Extended Description 
__has_builtin case does not appear to work with clang-tidy with -fmodules-ts or -std=c++20 where it is handled by clang.

$ cat ~/builtin.cpp 
#if !__has_builtin(__builtin_trap)
#error no  __builtin_trap
#endif
$ bin/clang  ~/builtin.cpp  -std=c++20 -fsyntax-only
$ bin/clang-tidy ~/builtin.cpp -- -std=c++20 
1 error generated.
Error while processing /home/ryan_mansfield/builtin.cpp.
/home/ryan_mansfield/builtin.cpp:2:2: error: no  __builtin_trap [clang-diagnostic-error]
#error no  __builtin_trap
 ^
Found compiler error(s).

$ bin/clang-tidy ~/builtin.cpp -- -std=c++11 -fmodules-ts
1 error generated.
Error while processing /home/ryan_mansfield/builtin.cpp.
/home/ryan_mansfield/builtin.cpp:2:2: error: no  __builtin_trap [clang-diagnostic-error]
#error no  __builtin_trap
 ^
Found compiler error(s).

#error directives for both true and false cases are reported.

e.g.

$ cat ~/truefalse.cpp 
#if __has_builtin(__builtin_trap)
#error error has __builtin_trap
#else
#error no has __builtin_trap
#endif

$ bin/clang-tidy ~/truefalse.cpp -- -std=c++11 -fmodules-ts
2 errors generated.
Error while processing /home/ryan_mansfield/truefalse.cpp.
/home/ryan_mansfield/truefalse.cpp:2:2: error: error has __builtin_trap [clang-diagnostic-error]
#error error has __builtin_trap
 ^
/home/ryan_mansfield/truefalse.cpp:4:2: error: no has __builtin_trap [clang-diagnostic-error]
#error no has __builtin_trap
 ^
Found compiler error(s).

This was using:

$ bin/clang -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 2193347e72fad6a78ce4a96c8d89f9a43a028e79)

**Comment by PiotrZSL** [comment]
Workaround added in b530eeea5e7697d58af2adac66c8b86c79e649bb
