### ISSUE TITLE
is_error_condition_enum_v and is_error_code_enum_v should be bool, not size_t

### ISSUE THREAD

**Issue by ecatmur** [llvm/llvm-project#50099]
|  |  |
| --- | --- |
| Bugzilla Link | [50755](https://llvm.org/bz50755) |
| Version | 12.0 |
| OS | All |
| Attachments | [main...bug-50755.patch.txt](https://user-images.githubusercontent.com/92601341/143762243-bbba8d3a-4061-443e-ba5d-0a9951db1b05.gz) |
| CC | @mclow |

## Extended Description 
afaict they've always been `bool` in the Standard, so no idea where `size_t` came from.

**Comment by Quuxplusone** [comment]
This was fixed in 93df7b9f75af6b4282565e6e98bb306590375820. Probably just a copy-paste error, originally.
