### ISSUE TITLE
clang crashes on riscv64

### ISSUE THREAD

**Issue by 293bd990-0472-4daa-9230-2d12e1e0d4b5** [llvm/llvm-project#50090]
|  |  |
| --- | --- |
| Bugzilla Link | [50746](https://llvm.org/bz50746) |
| Version | 11.0 |
| OS | Linux |
| CC | @asb,@topperc,@DimitryAndric,@efriedma-quic,@frasercrmck,@luismarques,@zygoloid |

## Extended Description 
I use Debian 11 installed on RISC-V platform: Nezha board with Allwinner D1 processor.

I installed clang as usual: "sudo apt install clang". The version is 1:11.0-51+nmu5. The source of the packages is http://ftp.ports.debian.org/debian-ports/.

When I run clang from command line without parameters, it crashes with message:

$ clang
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang 
1.	Compilation construction
/usr/lib/riscv64-linux-gnu/libLLVM-11.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x28)[0x3fec874c08]
Illegal instruction

Other compilers seem to work fine. I checked gcc, rustc, go.

Information about the system:

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

$ uname -a
Linux nezha 5.4.61 #&#8203;68 PREEMPT Tue Jun 1 04:18:22 UTC 2021 riscv64 GNU/Linux

$ /usr/sbin/hwinfo --short
cpu:                                                            
                       rv64imafdcvu
keyboard:
  /dev/ttyS0           serial console
network:
  eth0                 ARM Ethernet controller
  wlan0                ARM Ethernet controller
                       Network controller
network interface:
  eth0                 Ethernet network interface
  lo                   Loopback network interface
  sit0                 Network Interface
  wlan0                WLAN network interface
disk:
  /dev/mmcblk0         Disk
partition:
  /dev/mmcblk0p1       Partition
  /dev/mmcblk0p2       Partition
  /dev/mmcblk0p3       Partition
  /dev/mmcblk0p4       Partition
  /dev/mmcblk0p5       Partition
  /dev/mmcblk0p6       Partition
  /dev/mmcblk0p7       Partition
  /dev/mmcblk0p8       Partition
hub:
                       Linux Foundation 2.0 root hub
                       Linux Foundation 1.1 root hub
memory:
                       Main Memory

Thanks,
--Serge

**Comment by jrtc27** [comment]
Not a bug, and reporter says it's also no longer causing issues

**Comment by sanderjo** [comment]
> Anyway, I managed to build clang-13 from sources (https://github.com/llvm/llvm-project.git) and it works pretty well. Seems like the FENCE.TSO issue has been resolved somehow. I build clang directly on the RISC-V board itself, under Debian. I took a few days

Can you tell how you did that? Because even the plain

`git clone https://github.com/llvm/llvm-project.git`

failed on my Sipeed Lichee (D1, 512MB RAM) with 

`fatal: fetch-pack: invalid index-pack output`

So if that's already too much for my D1, I have doubts about the real compiling process.

**Comment by brucehoult** [comment]
> Can you tell how you did that? Because even the plain
> 
> `git clone https://github.com/llvm/llvm-project.git`
> 
> failed on my Sipeed Lichee (D1, 512MB RAM) with

512 MB is just barely enough to run a modern Linux desktop and do light development work.

LLVM is not light development work.

The git repo is 1.1 GB. Git expects to be able to hold a repo in RAM, to process it quickly.

You may be able to make it work using a large enough swap space. This will be very slow.

I wouldn't recommend trying to build LLVM on a machine with less than 8 GB RAM. At minimum, maximise what you can do with that 512 MB by not running a GUI.

**Comment by brucehoult** [comment]
You should be able to copy the SD card to a PC/Mac and boot it on qemu-system-riscv64 with lots of RAM and maybe lots of CPU cores. 

You can most definitely do that with the Ubuntu images for the HiFive Unmatched, which should build binaries compatible with Debian and with the Nezha boards (they are all RV64GC after all).

https://wiki.ubuntu.com/RISC-V

The qemu instructions there might also help with booting the D1 image on qemu.
