### ISSUE TITLE
Function __attribute__((nodebug)) inconsistency causes crash

### ISSUE THREAD

**Issue by brunodefraine** [llvm/llvm-project#50111]
|  |  |
| --- | --- |
| Bugzilla Link | [50767](https://llvm.org/bz50767) |
| Version | trunk |
| OS | All |
| CC | @adrian-prantl,@dwblaikie,@JDevlieghere,@dobbelaj-snps,@pogo59,@pogo59,@zygoloid,@yuanfang-chen |

## Extended Description 
When the nodebug attribute of a function appears only at its definition (so an earlier declaration of the function did not have the attribute) this crashes clang.

Example:

  void foo();

  void use() { foo(); }

  __attribute__((nodebug)) void foo() { }

Command:
   clang -c -g1 -O nodbg.cpp

Godbolt link: https://godbolt.org/z/nTYKW66Gf

On an assertion build, I think the error message is "function definition may only have a distinct !dbg attachment" then "fatal error: error in backend: Broken module found, compilation aborted!"

If needed that you annotate earlier declarations with nodebug, clang should enforce this?

**Comment by Endilll** [comment]
Appears to be fixed in Clang 13: https://godbolt.org/z/oj5MeW8x1
