### ISSUE TITLE
ClangdTests.exe/TUSchedulerTests.ManyUpdates flaky on windows

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#50117]
|  |  |
| --- | --- |
| Bugzilla Link | [50773](https://llvm.org/bz50773) |
| Version | unspecified |
| OS | All |
| CC | @sam-mccall |

## Extended Description 
https://lab.llvm.org/buildbot/#/builders/123/builds/4487/steps/12/logs/stdio :

```
Reusing preamble version 0 for version 5 of C:\clangd-test\foo2.cpp
Assertion failed: Requests.empty() && "No new normal tasks can be scheduled concurrently with " "blockUntilIdle(): ASTWorker isn't threadsafe", file C:\b\slave\clang-x64-windows-msvc\llvm-project\clang-tools-extra\clangd\TUScheduler.cpp, line 1390
********************
Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
********************
Failed Tests (1):
  Clangd Unit Tests :: ./ClangdTests.exe/TUSchedulerTests.ManyUpdates
```

Same on https://lab.llvm.org/buildbot/#/builders/123/builds/4485/steps/12/logs/stdio

Same on https://lab.llvm.org/buildbot/#/builders/123/builds/4481/steps/12/logs/stdio

Same on https://lab.llvm.org/buildbot/#/builders/123/builds/4564/steps/12/logs/stdio

From a random sample, it looks like the majority of failures on https://lab.llvm.org/buildbot/#/builders/123 is due to this.

**Comment by nico** [comment]
This is happening a lot right now:

http://45.33.8.238/win/80342/step_9.txt
http://45.33.8.238/win/80320/step_9.txt
http://45.33.8.238/win/80314/step_9.txt
http://45.33.8.238/win/80293/step_9.txt
http://45.33.8.238/win/80291/step_9.txt

5 failures in the last 1.5 days.

**Comment by nico** [comment]
@ilya-biryukov added this test over 5 years ago in https://reviews.llvm.org/D42174.

**Comment by HighCommander4** [comment]
See also https://github.com/clangd/clangd/issues/1712

**Comment by kadircet** [comment]
Hi all, sorry for missing those.

Hi @nico, I was checking the failures in the past week, and they don't seem to be from clangd. Is this still relevant for the build bot you're running?
