### ISSUE TITLE
CMake Warning (dev)

### ISSUE THREAD

**Issue by ikitayama** [llvm/llvm-project#50122]
|  |  |
| --- | --- |
| Bugzilla Link | [50778](https://llvm.org/bz50778) |
| Version | unspecified |
| OS | All |

## Extended Description 
Upon CMake configuration I observe:

[...]
-- Not building amdgpu-arch: hsa-runtime64 not found
CMake Warning (dev) at /p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/cmake-3.20.3-empeclcrdya6gf3e3f3yotgsaojjunci/share/cmake-3.20/Modules/ExternalProject.cmake:2218 (message):
  Policy CMP0114 is not set: ExternalProject step targets fully adopt their
  steps.  Run "cmake --help-policy CMP0114" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  ExternalProject target 'runtimes' would depend on the targets for step(s)
  'clean' under policy CMP0114, but this is being left out for compatibility
  since the policy is not set.
Call Stack (most recent call first):
  cmake/modules/LLVMExternalProjectUtils.cmake:333 (ExternalProject_Add_StepTargets)
  runtimes/CMakeLists.txt:226 (llvm_ExternalProject_Add)
  runtimes/CMakeLists.txt:353 (runtime_default_target)
This warning is for project developers.  Use -Wno-dev to suppress it.
[...]

If this is not written soley by the openmp project folks, can you tell me
where to post?

**Comment by nickdesaulniers** [comment]
@ikitayama can you test if the diff posted in https://github.com/llvm/llvm-project/issues/54944#issue-1206202938 resolves the issue for you? If so, I will send a formal patch.

**Comment by ikitayama** [comment]
@nickdesaulniers I've verified that with your patch applied today's master no longer emits the message reported here.

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D126923

**Comment by ikitayama** [comment]
Thanks!
