### ISSUE TITLE
lld/mac mislinks binaries (protoc, chromium, ...) on arm with --deduplicate-literals

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#50135]
|  |  |
| --- | --- |
| Bugzilla Link | [50791](https://llvm.org/bz50791) |
| Version | unspecified |
| OS | All |
| Attachments | [csd.proto](https://user-images.githubusercontent.com/3487/143762254-20def78d-4536-4620-9f9b-989c130a66da.gz) |
| CC | @gkmhub,@int3,@smeenai |

## Extended Description 
Repro: https://drive.google.com/file/d/1RJe4CRLk3_ULWolz4xZApy6XIJvxMl1R/view?usp=sharing

Link using the response file, then run like so:

./protoc csd.proto --cpp_out .          

Then look at csd.pb.h in the output. Line 45 will say

  static const ::r_PROTO_NAMESPACE_ID::internal::ParseTableField entries[]

There's a \0 character in the middle of the line, and the line's all wrong.

Remove --deduplicate-literals from that line, link again, and that line looks like

  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]

like it's supposed to do.

**Comment by int3** [comment]
https://reviews.llvm.org/D104835
