### ISSUE TITLE
linalg.fill custom op parser crashes

### ISSUE THREAD

**Issue by silvasean** [llvm/llvm-project#50163]
|  |  |
| --- | --- |
| Bugzilla Link | [50819](https://llvm.org/bz50819) |
| Version | unspecified |
| OS | Linux |
| CC | @joker-eph,@MaheshRavishankar |

## Extended Description 
repro:
```
func @&#8203;f(%arg0: tensor<?x?xf32>, %arg1: f32) -> tensor<?x?xf32> {
  %6 = linalg.fill(%arg0, %arg1) : tensor<?x?xf32>, f32 -> tensor<?x?xf32>
  return %6 : tensor<?x?xf32>    
}
```

See stacktrace here: https://reviews.llvm.org/P8268

**Comment by nicolasvasilache** [comment]
This was fixed a while back when we uniformized `linalg.fill` with the rest of the infra.

```
func.func @foo() {
  %A = memref.alloc() : memref<1xf64>
  %cf1 = arith.constant 1.00000e+00 : f64
  linalg.fill ins(%cf1: f64) outs(%A: memref<1xf64>)
  return
}
```

Parses properly.
