### ISSUE TITLE
[AVX] Incorrect code created for 12.0

### ISSUE THREAD

**Issue by 9b8c04c6-8356-4ba3-92db-4b51b57a26c6** [llvm/llvm-project#50167]
|  |  |
| --- | --- |
| Bugzilla Link | [50823](https://llvm.org/bz50823) |
| Version | 12.0 |
| OS | Windows NT |
| Blocks | llvm/llvm-project#48661  |
| CC | @dbabokin,@topperc,@RKSimon,@phoebewang,@rotateright |
| Fixed by commit(s) | 9ab99f773fec7da4183495a3fdc655a797d3bea2 |

## Extended Description 
This seem to be a regression from 11.0 -> 12.0.

See diff in godbolt(https://godbolt.org/z/x9Ms6ETor)

**Comment by RKSimon** [comment]
resolving - this missed the 12.x window but was fixed in 13.x
