### ISSUE TITLE
ICE: llvm/include/llvm/Support/MathExtras.h:729: uint64_t llvm::alignTo(uint64_t, uint64_t, uint64_t): Assertion `Align != 0u && "Align can't be 0."' failed.

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#50179]
|  |  |
| --- | --- |
| Bugzilla Link | [50835](https://llvm.org/bz50835) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
$ clang-trunk -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 5c8659801a4976ef2b327f4071d98086efd42a36)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$ cat mutant.c
int veci __attribute__((vector_size(4 * -1)));

$ clang-trunk  mutant.c
clang-13: /tmp/tmp.FIfHBNID2p-clang-builder/llvm-project/llvm/include/llvm/Support/MathExtras.h:729: uint64_t llvm::alignTo(uint64_t, uint64_t, uint64_t): Assertion `Align != 0u && "Align can't be 0."' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /scratch/software/clang-trunk/bin/clang-13 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -main-file-name mutant.c -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fcoverage-compilation-dir=/scratch/cnsun/workspace/perses-fuzzer/default_c_finding_folder/crash_20210623_101557_0153/delta/perses_result -resource-dir /scratch/software/clang-trunk/lib/clang/13.0.0 -c-isystem . -c-isystem /usr/local/include/cmsith -internal-isystem /scratch/software/clang-trunk/lib/clang/13.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir=/scratch/cnsun/workspace/perses-fuzzer/default_c_finding_folder/crash_20210623_101557_0153/delta/perses_result -ferror-limit 19 -fgnuc-version=4.2.1 -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/mutant-fb1de2.o -x c mutant.c
1.	<eof> parser at end of file
 #&#8203;0 0x0000564861333c64 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #&#8203;1 0x000056486133141e SignalHandler(int) Signals.cpp:0:0
 #&#8203;2 0x00007ff634fbf3c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #&#8203;3 0x00007ff634a5e18b raise /build/glibc-ZN95T4/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #&#8203;4 0x00007ff634a3d859 abort /build/glibc-ZN95T4/glibc-2.31/stdlib/abort.c:81:7
 #&#8203;5 0x00007ff634a3d729 get_sysdep_segment_value /build/glibc-ZN95T4/glibc-2.31/intl/loadmsgcat.c:509:8
 #&#8203;6 0x00007ff634a3d729 _nl_load_domain /build/glibc-ZN95T4/glibc-2.31/intl/loadmsgcat.c:970:34
 #&#8203;7 0x00007ff634a4ef36 (/lib/x86_64-linux-gnu/libc.so.6+0x36f36)
 #&#8203;8 0x0000564861822c79 (/scratch/software/clang-trunk/bin/clang-13+0x3e3dc79)
 #&#8203;9 0x00005648641b8523 clang::ASTContext::getTypeInfoImpl(clang::Type const*) const (/scratch/software/clang-trunk/bin/clang-13+0x67d3523)
#&#8203;10 0x00005648641a82ff clang::ASTContext::getTypeInfo(clang::Type const*) const (/scratch/software/clang-trunk/bin/clang-13+0x67c32ff)
#&#8203;11 0x00005648641b7103 clang::ASTContext::getPreferredTypeAlign(clang::Type const*) const (/scratch/software/clang-trunk/bin/clang-13+0x67d2103)
#&#8203;12 0x00005648641b8bfb clang::ASTContext::getDeclAlign(clang::Decl const*, bool) const (/scratch/software/clang-trunk/bin/clang-13+0x67d3bfb)
#&#8203;13 0x0000564861765e83 clang::CodeGen::CodeGenModule::GetOrCreateLLVMGlobal(llvm::StringRef, llvm::Type*, unsigned int, clang::VarDecl const*, clang::CodeGen::ForDefinition_t) (/scratch/software/clang-trunk/bin/clang-13+0x3d80e83)
#&#8203;14 0x00005648617683cb clang::CodeGen::CodeGenModule::GetAddrOfGlobalVar(clang::VarDecl const*, llvm::Type*, clang::CodeGen::ForDefinition_t) (/scratch/software/clang-trunk/bin/clang-13+0x3d833cb)
#&#8203;15 0x000056486176431f clang::CodeGen::CodeGenModule::EmitGlobalVarDefinition(clang::VarDecl const*, bool) (/scratch/software/clang-trunk/bin/clang-13+0x3d7f31f)
#&#8203;16 0x00005648617657bd clang::CodeGen::CodeGenModule::EmitTentativeDefinition(clang::VarDecl const*) (/scratch/software/clang-trunk/bin/clang-13+0x3d807bd)
#&#8203;17 0x0000564863689062 clang::Sema::ActOnEndOfTranslationUnit() (/scratch/software/clang-trunk/bin/clang-13+0x5ca4062)
#&#8203;18 0x0000564863555a5e clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/scratch/software/clang-trunk/bin/clang-13+0x5b70a5e)
#&#8203;19 0x0000564863547ff9 clang::ParseAST(clang::Sema&, bool, bool) (/scratch/software/clang-trunk/bin/clang-13+0x5b62ff9)
#&#8203;20 0x000056486248f678 clang::CodeGenAction::ExecuteAction() (/scratch/software/clang-trunk/bin/clang-13+0x4aaa678)
#&#8203;21 0x0000564861d3f029 clang::FrontendAction::Execute() (/scratch/software/clang-trunk/bin/clang-13+0x435a029)
#&#8203;22 0x0000564861cd21e6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/scratch/software/clang-trunk/bin/clang-13+0x42ed1e6)
#&#8203;23 0x0000564861e1ceb0 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/scratch/software/clang-trunk/bin/clang-13+0x4437eb0)
#&#8203;24 0x000056485ec456f6 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/scratch/software/clang-trunk/bin/clang-13+0x12606f6)
#&#8203;25 0x000056485ec41a38 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#&#8203;26 0x000056485eb6f0a6 main (/scratch/software/clang-trunk/bin/clang-13+0x118a0a6)
#&#8203;27 0x00007ff634a3f0b3 __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:342:3
#&#8203;28 0x000056485ec415ae _start (/scratch/software/clang-trunk/bin/clang-13+0x125c5ae)
clang-13: error: unable to execute command: Aborted (core dumped)
clang-13: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 5c8659801a4976ef2b327f4071d98086efd42a36)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
clang-13: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-13: note: diagnostic msg: /tmp/mutant-993fc4.c
clang-13: note: diagnostic msg: /tmp/mutant-993fc4.sh
clang-13: note: diagnostic msg:

********************

**Comment by shafik** [comment]
It looks like this no longer reproduces on latest clang trunk: https://godbolt.org/z/9v8o6Ms7M
