### ISSUE TITLE
ICE: UNREACHABLE executed at llvm-project/clang/lib/AST/ASTContext.cpp:10247!

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#50175]
|  |  |
| --- | --- |
| Bugzilla Link | [50831](https://llvm.org/bz50831) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
$ clang-trunk -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 5c8659801a4976ef2b327f4071d98086efd42a36)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$ cat mutant.c
#include <stdarg.h>
#include <stdbool.h>
bar() { va_arg(ap, bool); }

$ clang-trunk  mutant.c
mutant.c:3:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
bar() { va_arg(ap, bool); }
^
Unexpected unsigned integer or fixed point type
UNREACHABLE executed at /tmp/tmp.FIfHBNID2p-clang-builder/llvm-project/clang/lib/AST/ASTContext.cpp:10247!
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /scratch/software/clang-trunk/bin/clang-13 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -main-file-name mutant.c -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fcoverage-compilation-dir=/scratch/cnsun/workspace/perses-fuzzer/default_c_finding_folder/crash_20210623_145313_037e/delta/perses_result -resource-dir /scratch/software/clang-trunk/lib/clang/13.0.0 -c-isystem . -c-isystem /usr/local/include/cmsith -internal-isystem /scratch/software/clang-trunk/lib/clang/13.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir=/scratch/cnsun/workspace/perses-fuzzer/default_c_finding_folder/crash_20210623_145313_037e/delta/perses_result -ferror-limit 19 -fgnuc-version=4.2.1 -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/mutant-975802.o -x c mutant.c
1.	mutant.c:3:25: current parser token ';'
2.	mutant.c:3:7: parsing function body 'bar'
3.	mutant.c:3:7: in compound statement ('{}')
 #&#8203;0 0x000055d2938d9c64 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #&#8203;1 0x000055d2938d741e SignalHandler(int) Signals.cpp:0:0
 #&#8203;2 0x00007f9f411803c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #&#8203;3 0x00007f9f40c1f18b raise /build/glibc-ZN95T4/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #&#8203;4 0x00007f9f40bfe859 abort /build/glibc-ZN95T4/glibc-2.31/stdlib/abort.c:81:7
 #&#8203;5 0x000055d29382614e (/scratch/software/clang-trunk/bin/clang-13+0x389b14e)
 #&#8203;6 0x000055d29672bba0 clang::ASTContext::getCorrespondingSignedType(clang::QualType) const (/scratch/software/clang-trunk/bin/clang-13+0x67a0ba0)
 #&#8203;7 0x000055d295f82e2a clang::Sema::BuildVAArgExpr(clang::SourceLocation, clang::Expr*, clang::TypeSourceInfo*, clang::SourceLocation) (/scratch/software/clang-trunk/bin/clang-13+0x5ff7e2a)
 #&#8203;8 0x000055d295f82f2a clang::Sema::ActOnVAArg(clang::SourceLocation, clang::Expr*, clang::OpaquePtr<clang::QualType>, clang::SourceLocation) (/scratch/software/clang-trunk/bin/clang-13+0x5ff7f2a)
 #&#8203;9 0x000055d295b51b74 clang::Parser::ParseBuiltinPrimaryExpression() (/scratch/software/clang-trunk/bin/clang-13+0x5bc6b74)
#&#8203;10 0x000055d295b49859 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/scratch/software/clang-trunk/bin/clang-13+0x5bbe859)
#&#8203;11 0x000055d295b4c23b clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (/scratch/software/clang-trunk/bin/clang-13+0x5bc123b)
#&#8203;12 0x000055d295b4c2dd clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/scratch/software/clang-trunk/bin/clang-13+0x5bc12dd)
#&#8203;13 0x000055d295b4f83d clang::Parser::ParseExpression(clang::Parser::TypeCastState) (/scratch/software/clang-trunk/bin/clang-13+0x5bc483d)
#&#8203;14 0x000055d295bb743e clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/scratch/software/clang-trunk/bin/clang-13+0x5c2c43e)
#&#8203;15 0x000055d295bae9d2 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributesWithRange&) (/scratch/software/clang-trunk/bin/clang-13+0x5c239d2)
#&#8203;16 0x000055d295baf3ba clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/scratch/software/clang-trunk/bin/clang-13+0x5c243ba)
#&#8203;17 0x000055d295bb0339 clang::Parser::ParseCompoundStatementBody(bool) (/scratch/software/clang-trunk/bin/clang-13+0x5c25339)
#&#8203;18 0x000055d295bb294a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/scratch/software/clang-trunk/bin/clang-13+0x5c2794a)
#&#8203;19 0x000055d295af8c22 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/scratch/software/clang-trunk/bin/clang-13+0x5b6dc22)
#&#8203;20 0x000055d295b25580 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/scratch/software/clang-trunk/bin/clang-13+0x5b9a580)
#&#8203;21 0x000055d295af3426 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/scratch/software/clang-trunk/bin/clang-13+0x5b68426)
#&#8203;22 0x000055d295af3a11 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#&#8203;23 0x000055d295afa217 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/scratch/software/clang-trunk/bin/clang-13+0x5b6f217)
#&#8203;24 0x000055d295afb7ae clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/scratch/software/clang-trunk/bin/clang-13+0x5b707ae)
#&#8203;25 0x000055d295aedff9 clang::ParseAST(clang::Sema&, bool, bool) (/scratch/software/clang-trunk/bin/clang-13+0x5b62ff9)
#&#8203;26 0x000055d294a35678 clang::CodeGenAction::ExecuteAction() (/scratch/software/clang-trunk/bin/clang-13+0x4aaa678)
#&#8203;27 0x000055d2942e5029 clang::FrontendAction::Execute() (/scratch/software/clang-trunk/bin/clang-13+0x435a029)
#&#8203;28 0x000055d2942781e6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/scratch/software/clang-trunk/bin/clang-13+0x42ed1e6)
#&#8203;29 0x000055d2943c2eb0 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/scratch/software/clang-trunk/bin/clang-13+0x4437eb0)
#&#8203;30 0x000055d2911eb6f6 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/scratch/software/clang-trunk/bin/clang-13+0x12606f6)
#&#8203;31 0x000055d2911e7a38 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#&#8203;32 0x000055d2911150a6 main (/scratch/software/clang-trunk/bin/clang-13+0x118a0a6)
#&#8203;33 0x00007f9f40c000b3 __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:342:3
#&#8203;34 0x000055d2911e75ae _start (/scratch/software/clang-trunk/bin/clang-13+0x125c5ae)
clang-13: error: unable to execute command: Aborted (core dumped)
clang-13: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 5c8659801a4976ef2b327f4071d98086efd42a36)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
clang-13: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-13: note: diagnostic msg: /tmp/mutant-4191f4.c
clang-13: note: diagnostic msg: /tmp/mutant-4191f4.sh
clang-13: note: diagnostic msg:

********************

**Comment by Endilll** [comment]
This was a regression in Clang 13 that appears to be fixed in Clang 14: https://godbolt.org/z/e6ehxnKEs
