### ISSUE TITLE
ICE on valid code: const T* clang::Type::castAs() const [with T = clang::PointerType]: Assertion `isa<T>(CanonicalType)' failed.

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#50176]
|  |  |
| --- | --- |
| Bugzilla Link | [50832](https://llvm.org/bz50832) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
$ clang-trunk -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 5c8659801a4976ef2b327f4071d98086efd42a36)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$ cat mutant.c
foo(a) { __atomic_is_lock_free(2, a); }

$ clang-trunk  mutant.c
mutant.c:1:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
foo(a) { __atomic_is_lock_free(2, a); }
^
mutant.c:1:35: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const volatile void *' [-Wint-conversion]
foo(a) { __atomic_is_lock_free(2, a); }
                                  ^
mutant.c:1:39: warning: non-void function does not return a value [-Wreturn-type]
foo(a) { __atomic_is_lock_free(2, a); }
                                      ^
clang-13: /tmp/tmp.FIfHBNID2p-clang-builder/llvm-project/clang/include/clang/AST/Type.h:7230: const T* clang::Type::castAs() const [with T = clang::PointerType]: Assertion `isa<T>(CanonicalType)' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /scratch/software/clang-trunk/bin/clang-13 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -main-file-name mutant.c -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fcoverage-compilation-dir=/scratch/cnsun/workspace/perses-fuzzer/default_c_finding_folder/crash_20210623_052549_009a/delta/perses_result -resource-dir /scratch/software/clang-trunk/lib/clang/13.0.0 -c-isystem . -c-isystem /usr/local/include/cmsith -internal-isystem /scratch/software/clang-trunk/lib/clang/13.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir=/scratch/cnsun/workspace/perses-fuzzer/default_c_finding_folder/crash_20210623_052549_009a/delta/perses_result -ferror-limit 19 -fgnuc-version=4.2.1 -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/mutant-276899.o -x c mutant.c
1.	<eof> parser at end of file
2.	mutant.c:1:1: LLVM IR generation of declaration 'foo'
3.	mutant.c:1:1: Generating code for declaration 'foo'
 #&#8203;0 0x000055c41ff29c64 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #&#8203;1 0x000055c41ff2741e SignalHandler(int) Signals.cpp:0:0
 #&#8203;2 0x00007f968bc6d3c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #&#8203;3 0x00007f968b70c18b raise /build/glibc-ZN95T4/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #&#8203;4 0x00007f968b6eb859 abort /build/glibc-ZN95T4/glibc-2.31/stdlib/abort.c:81:7
 #&#8203;5 0x00007f968b6eb729 get_sysdep_segment_value /build/glibc-ZN95T4/glibc-2.31/intl/loadmsgcat.c:509:8
 #&#8203;6 0x00007f968b6eb729 _nl_load_domain /build/glibc-ZN95T4/glibc-2.31/intl/loadmsgcat.c:970:34
 #&#8203;7 0x00007f968b6fcf36 (/lib/x86_64-linux-gnu/libc.so.6+0x36f36)
 #&#8203;8 0x000055c4202ca3d7 clang::PointerType const* clang::Type::castAs<clang::PointerType>() const (/scratch/software/clang-trunk/bin/clang-13+0x3cef3d7)
 #&#8203;9 0x000055c423040d14 (anonymous namespace)::IntExprEvaluator::VisitBuiltinCallExpr(clang::CallExpr const*, unsigned int) ExprConstant.cpp:0:0
#&#8203;10 0x000055c423040ffa (anonymous namespace)::IntExprEvaluator::VisitCallExpr(clang::CallExpr const*) ExprConstant.cpp:0:0
#&#8203;11 0x000055c422ffe0d8 clang::StmtVisitorBase<llvm::make_const_ptr, (anonymous namespace)::IntExprEvaluator, bool>::Visit(clang::Stmt const*) ExprConstant.cpp:0:0
#&#8203;12 0x000055c422fed37e Evaluate(clang::APValue&, (anonymous namespace)::EvalInfo&, clang::Expr const*) ExprConstant.cpp:0:0
#&#8203;13 0x000055c422ff7319 EvaluateAsRValue((anonymous namespace)::EvalInfo&, clang::Expr const*, clang::APValue&) ExprConstant.cpp:0:0
#&#8203;14 0x000055c422ff93df clang::Expr::EvaluateAsRValue(clang::Expr::EvalResult&, clang::ASTContext const&, bool) const (/scratch/software/clang-trunk/bin/clang-13+0x6a1e3df)
#&#8203;15 0x000055c4205175d8 clang::CodeGen::CodeGenFunction::EmitBuiltinExpr(clang::GlobalDecl, unsigned int, clang::CallExpr const*, clang::CodeGen::ReturnValueSlot) (/scratch/software/clang-trunk/bin/clang-13+0x3f3c5d8)
#&#8203;16 0x000055c4205d56e7 clang::CodeGen::CodeGenFunction::EmitCallExpr(clang::CallExpr const*, clang::CodeGen::ReturnValueSlot) (/scratch/software/clang-trunk/bin/clang-13+0x3ffa6e7)
#&#8203;17 0x000055c42060e8e2 (anonymous namespace)::ScalarExprEmitter::VisitCallExpr(clang::CallExpr const*) CGExprScalar.cpp:0:0
#&#8203;18 0x000055c42060bdd9 (anonymous namespace)::ScalarExprEmitter::Visit(clang::Expr*) CGExprScalar.cpp:0:0
#&#8203;19 0x000055c42060df9a clang::CodeGen::CodeGenFunction::EmitScalarExpr(clang::Expr const*, bool) (/scratch/software/clang-trunk/bin/clang-13+0x4032f9a)
#&#8203;20 0x000055c4205b5287 clang::CodeGen::CodeGenFunction::EmitAnyExpr(clang::Expr const*, clang::CodeGen::AggValueSlot, bool) (/scratch/software/clang-trunk/bin/clang-13+0x3fda287)
#&#8203;21 0x000055c4205d3bfe clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(clang::Expr const*) (/scratch/software/clang-trunk/bin/clang-13+0x3ff8bfe)
#&#8203;22 0x000055c4202b8aba clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/scratch/software/clang-trunk/bin/clang-13+0x3cddaba)
#&#8203;23 0x000055c4202bee5c clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/scratch/software/clang-trunk/bin/clang-13+0x3ce3e5c)
#&#8203;24 0x000055c4203162a1 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::Stmt const*) (/scratch/software/clang-trunk/bin/clang-13+0x3d3b2a1)
#&#8203;25 0x000055c420327afc clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/scratch/software/clang-trunk/bin/clang-13+0x3d4cafc)
#&#8203;26 0x000055c420381406 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/scratch/software/clang-trunk/bin/clang-13+0x3da6406)
#&#8203;27 0x000055c42037cfa5 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/scratch/software/clang-trunk/bin/clang-13+0x3da1fa5)
#&#8203;28 0x000055c42037d40b clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl) (/scratch/software/clang-trunk/bin/clang-13+0x3da240b)
#&#8203;29 0x000055c420385e72 clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) (.part.0) CodeGenModule.cpp:0:0
#&#8203;30 0x000055c4210884f9 (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) ModuleBuilder.cpp:0:0
#&#8203;31 0x000055c42107a6e0 clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) (/scratch/software/clang-trunk/bin/clang-13+0x4a9f6e0)
#&#8203;32 0x000055c42213dfe4 clang::ParseAST(clang::Sema&, bool, bool) (/scratch/software/clang-trunk/bin/clang-13+0x5b62fe4)
#&#8203;33 0x000055c421085678 clang::CodeGenAction::ExecuteAction() (/scratch/software/clang-trunk/bin/clang-13+0x4aaa678)
#&#8203;34 0x000055c420935029 clang::FrontendAction::Execute() (/scratch/software/clang-trunk/bin/clang-13+0x435a029)
#&#8203;35 0x000055c4208c81e6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/scratch/software/clang-trunk/bin/clang-13+0x42ed1e6)
#&#8203;36 0x000055c420a12eb0 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/scratch/software/clang-trunk/bin/clang-13+0x4437eb0)
#&#8203;37 0x000055c41d83b6f6 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/scratch/software/clang-trunk/bin/clang-13+0x12606f6)
#&#8203;38 0x000055c41d837a38 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#&#8203;39 0x000055c41d7650a6 main (/scratch/software/clang-trunk/bin/clang-13+0x118a0a6)
#&#8203;40 0x00007f968b6ed0b3 __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:342:3
#&#8203;41 0x000055c41d8375ae _start (/scratch/software/clang-trunk/bin/clang-13+0x125c5ae)
clang-13: error: unable to execute command: Aborted (core dumped)
clang-13: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 5c8659801a4976ef2b327f4071d98086efd42a36)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
clang-13: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-13: note: diagnostic msg: /tmp/mutant-296fb2.c
clang-13: note: diagnostic msg: /tmp/mutant-296fb2.sh
clang-13: note: diagnostic msg:

********************

**Comment by k-mana** [comment]
This no longer reproduces on trunk: https://godbolt.org/z/4fE8b1K3x
This has been fixed: 2cb2cd2
