### ISSUE TITLE
ICE: fatal error: error in backend: Broken function found, compilation aborted!

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#50188]
|  |  |
| --- | --- |
| Bugzilla Link | [50844](https://llvm.org/bz50844) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
$ clang-trunk -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 24d48d45cc302a6abeab139d87ba87f7a2335323)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$ cat mutant.c
void __attribute__((interrupt)) foo(struct ucontext *) {}

$ clang-trunk  mutant.c
mutant.c:1:44: warning: declaration of 'struct ucontext' will not be visible outside of this function [-Wvisibility]
void __attribute__((interrupt)) foo(struct ucontext *) {}
                                           ^
mutant.c:1:54: warning: omitting the parameter name in a function definition is a C2x extension [-Wc2x-extensions]
void __attribute__((interrupt)) foo(struct ucontext *) {}
                                                     ^
Attribute 'byval' does not support unsized types!
void (%struct.ucontext*)* @&#8203;foo
in function foo
fatal error: error in backend: Broken function found, compilation aborted!
clang-13: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 24d48d45cc302a6abeab139d87ba87f7a2335323)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
clang-13: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-13: note: diagnostic msg: /tmp/mutant-454061.c
clang-13: note: diagnostic msg: /tmp/mutant-454061.sh
clang-13: note: diagnostic msg:

********************

**Comment by AaronBallman** [comment]
This has the same underlying cause as #50170, so closing as a duplicate.
