### ISSUE TITLE
An example code from the standard (templates and concepts) does not compile

### ISSUE THREAD

**Issue by mmatrosov** [llvm/llvm-project#50208]
|  |  |
| --- | --- |
| Bugzilla Link | [50864](https://llvm.org/bz50864) |
| Version | trunk |
| OS | Linux |
| CC | @erichkeane,@zygoloid,@viccie30,@jwakely |

## Extended Description 
According to `[temp.constr.decl]/4` the following example should compile:

```
template <class T> concept C = true;
template <class T> struct A {
  template <class U> U f(U) requires C<typename T::type>;   // #1
  template <class U> U f(U) requires C<T>;                  // #2
};

template <> template <class U>
U A<int>::f(U u) requires C<int> { return u; }              // OK, specializes #2
```

However, clang gives an error:

```
<source>:3:49: error: type 'int' cannot be used prior to '::' because it has no members
  template <class U> U f(U) requires C<typename T::type>;   // #1
                                                ^
```

I believe this is the reason why clang cannot compile `libstdc++` ranges: llvm/llvm-project#46091

**Comment by royjacobson** [comment]
Still doesn't work after https://reviews.llvm.org/D126907 but I think it's a different bug now.

```
<source>:8:11: error: out-of-line definition of 'f' does not match any declaration in 'A<int>'
U A<int>::f(U u) requires C<int> { return u; }              // OK, specializes #2
          ^
```

**Comment by royjacobson** [comment]
`Sema::isOverload` compares the concepts of the definition to the uninstantiated constraints of the initial declaration, and they're differnt. So `Sema::CheckOverload` in `Sema::CheckFunctionDeclaration` thinks this is an overload and not a definition.

I think we need to instantiate the specialized struct and then do a lookup or something like that, I'm not sure how this is only a problem for constrained methods so I probably missed something.

**Comment by usx95** [comment]
The left over bug is same as https://github.com/llvm/llvm-project/issues/49620.
