### ISSUE TITLE
Wzero-as-null-pointer-constant when using defaulted operator<=>

### ISSUE THREAD

**Issue by 46f415b9-2cc1-4a30-bcb5-8bfc957ecc1e** [llvm/llvm-project#50221]
|  |  |
| --- | --- |
| Bugzilla Link | [50877](https://llvm.org/bz50877) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [possible patch for the problem](https://user-images.githubusercontent.com/92601751/143762262-7e62fc8b-6f6a-4161-a773-b55cf116a069.gz) |
| CC | @zygoloid |

## Extended Description 

See bug llvm/llvm-project#43670  for what is happening that produces the 0 -> nullptr conversion.

Compiling this code with -Wzero-as-null-pointer-constant

#include <compare>
struct Point {
    int x{}, y{}, z{};
    auto operator<=>(const Point&) const = default;
};

int main() {
    return Point{} < Point{};
}

Produces three -Wzero-as-null-pointer-constant warnings, one for each member of Point. Fortunately suppressing the warning at the implementation site of operator<=> suppresses it for users.

Live example: https://gcc.godbolt.org/z/3n9Kf3baa

The fix is seemingly very close the fix to #&#8203;44325, but the build environment I have that can build clang doesn't have "enough" to actually run the tests so I don't know if my possible fix ends up suppressing the warning in other cases.

**Comment by ilya-biryukov** [comment]
Related issue in clang-tidy: #53961
