### ISSUE TITLE
ICE with -g: fatal error: error in backend: Cannot select: intrinsic %llvm.preserve.array.access.index

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#50242]
|  |  |
| --- | --- |
| Bugzilla Link | [50898](https://llvm.org/bz50898) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
$ clang-trunk -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 2e9c75daffddd65e37c3236708b5b133e6f5f2f5)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$ cat mutant.c
invalid3(*arg) { return __builtin_preserve_access_index(arg[1]); }

$ clang-trunk -g mutant.c
mutant.c:1:11: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
invalid3(*arg) { return __builtin_preserve_access_index(arg[1]); }
          ^
mutant.c:1:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
invalid3(*arg) { return __builtin_preserve_access_index(arg[1]); }
^
fatal error: error in backend: Cannot select: intrinsic %llvm.preserve.array.access.index
clang-13: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 2e9c75daffddd65e37c3236708b5b133e6f5f2f5)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
clang-13: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-13: note: diagnostic msg: /tmp/mutant-0430e5.c
clang-13: note: diagnostic msg: /tmp/mutant-0430e5.sh
clang-13: note: diagnostic msg:

********************

**Comment by Endilll** [comment]
Fixed in Clang 15: https://godbolt.org/z/18qn6cP3q
