### ISSUE TITLE
Regression: null pointers no longer generate warnings

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5024]
|  |  |
| --- | --- |
| Bugzilla Link | [4652](https://llvm.org/bz4652) |
| Version | unspecified |
| OS | MacOS X |
| Attachments | [nonnull-3.c from GCC DejaGNU testsuite](https://user-images.githubusercontent.com/60944935/143739626-fa649d7b-5e16-47d7-be34-9feb136fa5bf.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description

**Comment by philnik777** [comment]
llvm-gcc has been discontinued quite a while ago, so I think it's safe to close this.
