### ISSUE TITLE
ICE: clang::Expr::ClassifyImpl(clang::ASTContext&, clang::SourceLocation*) const: Assertion `getValueKind() == VK_PRValue' failed.

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#50247]
|  |  |
| --- | --- |
| Bugzilla Link | [50903](https://llvm.org/bz50903) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
$ clang-trunk -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 2e9c75daffddd65e37c3236708b5b133e6f5f2f5)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$ cat mutant.c
a(int b) __attribute__((overloadable, enable_if(b, "")));
a(void) {
  int bar;
  a = baz;
}

$ clang-trunk  mutant.c
mutant.c:1:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
a(int b) __attribute__((overloadable, enable_if(b, "")));
^
mutant.c:2:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
a(void) {
^
clang-13: /tmp/tmp.xjN6dMkdrg-clang-builder/llvm-project/clang/lib/AST/ExprClassification.cpp:68: Cl clang::Expr::ClassifyImpl(clang::ASTContext&, clang::SourceLocation*) const: Assertion `getValueKind() == VK_PRValue' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /scratch/software/clang-trunk/bin/clang-13 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -main-file-name mutant.c -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fcoverage-compilation-dir=/scratch/cnsun/workspace/perses-fuzzer/default_c_finding_folder/crash_20210624_122138_0476/delta/perses_result -resource-dir /scratch/software/clang-trunk/lib/clang/13.0.0 -c-isystem . -c-isystem /usr/local/include/cmsith -internal-isystem /scratch/software/clang-trunk/lib/clang/13.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir=/scratch/cnsun/workspace/perses-fuzzer/default_c_finding_folder/crash_20210624_122138_0476/delta/perses_result -ferror-limit 19 -fgnuc-version=4.2.1 -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/mutant-742da6.o -x c mutant.c
1.	mutant.c:5:1: current parser token '}'
2.	mutant.c:2:9: parsing function body 'a'
3.	mutant.c:2:9: in compound statement ('{}')
 #&#8203;0 0x0000558b13f96184 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #&#8203;1 0x0000558b13f9393e SignalHandler(int) Signals.cpp:0:0
 #&#8203;2 0x00007f1827f1c3c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #&#8203;3 0x00007f18279bb18b raise /build/glibc-ZN95T4/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #&#8203;4 0x00007f182799a859 abort /build/glibc-ZN95T4/glibc-2.31/stdlib/abort.c:81:7
 #&#8203;5 0x00007f182799a729 get_sysdep_segment_value /build/glibc-ZN95T4/glibc-2.31/intl/loadmsgcat.c:509:8
 #&#8203;6 0x00007f182799a729 _nl_load_domain /build/glibc-ZN95T4/glibc-2.31/intl/loadmsgcat.c:970:34
 #&#8203;7 0x00007f18279abf36 (/lib/x86_64-linux-gnu/libc.so.6+0x36f36)
 #&#8203;8 0x0000558b1705c978 clang::Expr::ClassifyImpl(clang::ASTContext&, clang::SourceLocation*) const (/scratch/software/clang-trunk/bin/clang-13+0x6a21978)
 #&#8203;9 0x0000558b1705cb71 clang::Expr::isModifiableLvalue(clang::ASTContext&, clang::SourceLocation*) const (/scratch/software/clang-trunk/bin/clang-13+0x6a21b71)
#&#8203;10 0x0000558b1661b7a6 CheckForModifiableLvalue(clang::Expr*, clang::SourceLocation, clang::Sema&) SemaExpr.cpp:0:0
#&#8203;11 0x0000558b1664ec05 clang::Sema::CheckAssignmentOperands(clang::Expr*, clang::ActionResult<clang::Expr*, true>&, clang::SourceLocation, clang::QualType) (/scratch/software/clang-trunk/bin/clang-13+0x6013c05)
#&#8203;12 0x0000558b1664fecb clang::Sema::CreateBuiltinBinOp(clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*) (/scratch/software/clang-trunk/bin/clang-13+0x6014ecb)
#&#8203;13 0x0000558b16650e14 clang::Sema::BuildBinOp(clang::Scope*, clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*) (/scratch/software/clang-trunk/bin/clang-13+0x6015e14)
#&#8203;14 0x0000558b167622c4 clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformBinaryOperator(clang::BinaryOperator*) SemaExprCXX.cpp:0:0
#&#8203;15 0x0000558b16723544 (anonymous namespace)::TransformTypos::RecursiveTransformLoop(clang::Expr*, bool&) SemaExprCXX.cpp:0:0
#&#8203;16 0x0000558b167251bc clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) (/scratch/software/clang-trunk/bin/clang-13+0x60ea1bc)
#&#8203;17 0x0000558b167266e1 clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool) (/scratch/software/clang-trunk/bin/clang-13+0x60eb6e1)
#&#8203;18 0x0000558b1697defb clang::Sema::ActOnExprStmt(clang::ActionResult<clang::Expr*, true>, bool) (/scratch/software/clang-trunk/bin/clang-13+0x6342efb)
#&#8203;19 0x0000558b162747c3 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/scratch/software/clang-trunk/bin/clang-13+0x5c397c3)
#&#8203;20 0x0000558b1626bce2 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributesWithRange&) (/scratch/software/clang-trunk/bin/clang-13+0x5c30ce2)
#&#8203;21 0x0000558b1626c6ca clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/scratch/software/clang-trunk/bin/clang-13+0x5c316ca)
#&#8203;22 0x0000558b1626d649 clang::Parser::ParseCompoundStatementBody(bool) (/scratch/software/clang-trunk/bin/clang-13+0x5c32649)
#&#8203;23 0x0000558b1626fc5a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/scratch/software/clang-trunk/bin/clang-13+0x5c34c5a)
#&#8203;24 0x0000558b161b5ef2 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/scratch/software/clang-trunk/bin/clang-13+0x5b7aef2)
#&#8203;25 0x0000558b161e2850 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/scratch/software/clang-trunk/bin/clang-13+0x5ba7850)
#&#8203;26 0x0000558b161b06f6 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/scratch/software/clang-trunk/bin/clang-13+0x5b756f6)
#&#8203;27 0x0000558b161b0ce1 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#&#8203;28 0x0000558b161b74e7 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/scratch/software/clang-trunk/bin/clang-13+0x5b7c4e7)
#&#8203;29 0x0000558b161b8a7e clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/scratch/software/clang-trunk/bin/clang-13+0x5b7da7e)
#&#8203;30 0x0000558b161ab2c9 clang::ParseAST(clang::Sema&, bool, bool) (/scratch/software/clang-trunk/bin/clang-13+0x5b702c9)
#&#8203;31 0x0000558b150f2968 clang::CodeGenAction::ExecuteAction() (/scratch/software/clang-trunk/bin/clang-13+0x4ab7968)
#&#8203;32 0x0000558b149a2599 clang::FrontendAction::Execute() (/scratch/software/clang-trunk/bin/clang-13+0x4367599)
#&#8203;33 0x0000558b149357e6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/scratch/software/clang-trunk/bin/clang-13+0x42fa7e6)
#&#8203;34 0x0000558b14a80480 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/scratch/software/clang-trunk/bin/clang-13+0x4445480)
#&#8203;35 0x0000558b118a0696 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/scratch/software/clang-trunk/bin/clang-13+0x1265696)
#&#8203;36 0x0000558b1189c9d8 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#&#8203;37 0x0000558b117ca0e6 main (/scratch/software/clang-trunk/bin/clang-13+0x118f0e6)
#&#8203;38 0x00007f182799c0b3 __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:342:3
#&#8203;39 0x0000558b1189c54e _start (/scratch/software/clang-trunk/bin/clang-13+0x126154e)
clang-13: error: unable to execute command: Aborted (core dumped)
clang-13: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 2e9c75daffddd65e37c3236708b5b133e6f5f2f5)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
clang-13: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-13: note: diagnostic msg: /tmp/mutant-0aeb64.c
clang-13: note: diagnostic msg: /tmp/mutant-0aeb64.sh
clang-13: note: diagnostic msg:

********************

**Comment by Endilll** [comment]
Appears to be fixed in Clang 15: https://godbolt.org/z/sGW7zc1TP
