### ISSUE TITLE
Address of function template in concept should cause concept to evaluate to false

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#50278]
|  |  |
| --- | --- |
| Bugzilla Link | [50934](https://llvm.org/bz50934) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
The following valid translation unit

```
template<typename T>
concept foo = requires {
	&T::f;
};

struct S {
	template<typename T>
	void f(T);
};

static_assert(!foo<S>);
```

Is incorrectly rejected by clang with the error message

```
<source>:11:1: error: static_assert failed due to requirement '!foo<S>'
static_assert(!foo<S>);
^             ~~~~~~~
1 error generated.
Compiler returned: 1
```

See it live: https://godbolt.org/z/h7vTqo1Yb

**Comment by Quuxplusone** [comment]
Looks okay now in trunk. Probably fixed by f6ce456707898f0ae2c70748e896130e1c897960, which also fixed #52905 #52909 #53075.
