### ISSUE TITLE
type traits fails with __int128

### ISSUE THREAD

**Issue by victorstewart** [llvm/llvm-project#50281]
|  |  |
| --- | --- |
| Bugzilla Link | [50937](https://llvm.org/bz50937) |
| Version | 12.0 |
| OS | All |
| CC | @mclow |

## Extended Description 
std::is_same_v and std::is_integral_v both fail to recognize unsigned __int128 and any typedef made against it.

reproducer program in compiler explorer below:
https://gcc.godbolt.org/z/T8nP84qqM

**Comment by Quuxplusone** [comment]
Not a Bug: this is just perfect-forwarding in action. https://gcc.godbolt.org/z/WPrq5ej5d
```
template<class T> void test(T&& t) {
    static_assert(not std::is_same_v<T, int>);  // because int& is not int
    static_assert(not std::is_integral_v<T>);  // because int& is not integral
}
int main() {
    int i;
    test(i);
}
```
