### ISSUE TITLE
format-pedantic warns about passing `nullptr` to `%p`

### ISSUE THREAD

**Issue by eyalroz** [llvm/llvm-project#50290]
|  |  |
| --- | --- |
| Bugzilla Link | [50946](https://llvm.org/bz50946) |
| Version | 12.0 |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Godbolt: https://godbolt.org/z/1dMKE1W81

If we compile:
```cpp
  #include <stdio.h>
  
  int main()
  {
      printf("%p\n", nullptr);
  }
```
with `clang++ -Wformat -pedantic`, we get:
```
<source>:5:20: warning: format specifies type 'void *' but the argument has type 'nullptr_t' [-Wformat-pedantic]
    printf("%p\n", nullptr);
            ~~     ^~~~~~~
```
I believe that's _too_ pedantic. It is well and proper to pass `nullptr` to a `%p` without casting it.

**Comment by frederick-vs-ja** [comment]
Fixed by #104704.
