### ISSUE TITLE
[AVR] Struct pointer is nil after a for loop which reads SPI

### ISSUE THREAD

**Issue by 50b495eb-7352-45dc-8c57-57c5bcd5a494** [llvm/llvm-project#50303]
|  |  |
| --- | --- |
| Bugzilla Link | [50959](https://llvm.org/bz50959) |
| Version | unspecified |
| OS | other |

## Extended Description 
Below is the link to the particular commit which implemented a workaround to the bug: https://github.com/soypat/enc28j60/commit/c7cbf9e0f0b06c53e394035f548f8b92b5f14997#diff-4f427d2b022907c552328e63f137561f6de92396d7a6e8f6c2ea1bcf0db52654L18

This issue was observed in an Arduino Mega 2560. Compiling with tinygo default settings (opt=z i believe)

As mentioned in the comment in the commit, moving the declaration of the Packet struct variable after the for loop fixed the issue. The program being tested was the following (please take a look at the comments):

```
package main

import (
	"machine"
	"unsafe"

	"github.com/soypat/net"

	"github.com/soypat/enc28j60"
	swtch "github.com/soypat/ether-swtch"
)

func main() {
	println("start")
	// SPI Chip select pin. Can be any Digital pin
	var spiCS = machine.D53
	// Inline declarations so not used as RAM
	var (
		MAC = net.HardwareAddr{0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xFF}
		// MyIP = net.IP{192, 168, 1, 5} //static setup is the only one available
	)

	machine.SPI0.Configure(machine.SPIConfig{Frequency: 8e6})

	e := enc28j60.New(spiCS, machine.SPI0)
	enc28j60.SDB = true
	err := e.Init(MAC)
	if err != nil {
		println(err.Error())
	}

	c := swtch.NewTCPConn(e, nil, MAC)
        // Decode calls e.NextPacket() which returns the Packet
        // Packet's Read() method is called in Decode() which panics due to accessing nil `ic` field
        // Repeating these calls in main() does no reproduce the issue.
        // I could not manage to get a MWE working.
	err = c.Decode() 
	if err != nil {
		println(err.Error())
	}
}
```

**Comment by aykevl** [comment]
@soypat is this still an issue? A lot of AVR bugs have been fixed, there is a good chance this now works correctly.

The 256kB parts aren't fully supported yet so it might still not work.

**Comment by soypat** [comment]
I'll share that I have archived the project that had this issue and am no longer available to attempt to reproduce the issue.

**Comment by benshi001** [comment]
not reproducible
