### ISSUE TITLE
Clang 11.0 and 12.0 errorneous codegen on Windows x64 when using Visual Studio 2019 STL.

### ISSUE THREAD

**Issue by 375f5d7a-e277-487e-b103-96457dd07676** [llvm/llvm-project#50306]
|  |  |
| --- | --- |
| Bugzilla Link | [50962](https://llvm.org/bz50962) |
| Version | 12.0 |
| OS | Windows NT |
| CC | @zygoloid |

## Extended Description 
Rephrased title to better match the problem, originally from [Structured Bindings Miscompilation(?) on Windows x64](#50731 ). As the problem is not limited to structured bindings but operator[] and std::get.

Microsoft also doesn't seem to find anything wrong with their STL, for more info, see [Clang 11.0 and 12.0 generates erroneous code when using STL](https://developercommunity.visualstudio.com/t/Clang-110-and-120-generates-erroneous/1464106).

The code in question,
```cpp
#include <immintrin.h>

#include <array>

namespace my {

template <class T, size_t N>
struct array {
  T data_[N];
};

template <size_t I, class T, size_t N>
constexpr typename std::enable_if<(I < N), T&>::type get(
    my::array<T, N>& a) noexcept {
  return a.data_[I];
}

template <size_t I, class T, size_t N>
constexpr typename std::enable_if<(I < N), T const&>::type get(
    my::array<T, N> const& a) noexcept {
  return a.data_[I];
}

template <size_t I, class T, size_t N>
constexpr typename std::enable_if<(I < N), T&&>::type get(
    my::array<T, N>&& a) noexcept {
  return std::move(a.data_[I]);
}

}  // namespace my

namespace std {

template <class T, size_t N>
struct tuple_size<my::array<T, N>> {
  static constexpr auto value = N;
};

template <size_t I, class T, size_t N>
struct tuple_element<I, my::array<T, N>> {
  static_assert(I < N);

  using type = T;
};

}  // namespace std

#if 0
using std::array;  // Results in memory violation in x64 Debug.
#else
using my::array;  // Fine.
#endif

int main() {
  auto lambda = [](std::array<__m256i, 2> in) noexcept {
    auto [in0, in1] = in;

    return _mm256_add_epi8(in0, in1);
  };

  const __m256i a = _mm256_set1_epi8(1);
  const __m256i b = _mm256_set1_epi8(2);

  (void)lambda({a, b});
}
```

**Comment by StephanTLavavej** [comment]
This may have been fixed - I am no longer able to reproduce it with VS 2022 17.10 Preview 1 and Clang 17.0.3. You may want to check again, and close this bug if you observe the same thing.
