### ISSUE TITLE
ICE on valid code with -O1: fatal error: error in backend: Instruction Combining seems stuck in an infinite loop after 100 iterations.

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#50313]
|  |  |
| --- | --- |
| Bugzilla Link | [50969](https://llvm.org/bz50969) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
$ clang-trunk -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 65eb4028ad0322115ff5420499806db79a27289e)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$ cat mutant.c
mul_double ()
{
int j, *prod;
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (j = 0; j < 4; j++)
for (; j < 4; j++)
*prod = 0;
}

$ clang-trunk -O1 -w mutant.c
fatal error: error in backend: Instruction Combining seems stuck in an infinite loop after 100 iterations.
clang-13: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 65eb4028ad0322115ff5420499806db79a27289e)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
clang-13: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-13: note: diagnostic msg: /tmp/mutant-000f7c.c
clang-13: note: diagnostic msg: /tmp/mutant-000f7c.sh
clang-13: note: diagnostic msg:

********************

**Comment by nikic** [comment]
No longer reproduces, fixed as part of single-iteration InstCombine work.
