### ISSUE TITLE
ICE: {anonymous}::LValue::setFrom(clang::ASTContext&, const clang::APValue&): Assertion `V.isLValue() && "Setting LValue from a non-LValue?"' failed.

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#50323]
|  |  |
| --- | --- |
| Bugzilla Link | [50979](https://llvm.org/bz50979) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
$ clang-trunk -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 6b0d266036f73f5ee9556d211a7d0946091ff3b2)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$ cat mutant.c
x() { &&e - &&b < x; }

$ clang-trunk -w mutant.c
clang-13: /tmp/tmp.OKn6kNiY8c-clang-builder/llvm-project/clang/lib/AST/ExprConstant.cpp:1576: void {anonymous}::LValue::setFrom(clang::ASTContext&, const clang::APValue&): Assertion `V.isLValue() && "Setting LValue from a non-LValue?"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /scratch/software/clang-trunk/bin/clang-13 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -main-file-name mutant.c -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fcoverage-compilation-dir=/scratch/cnsun/workspace/perses-fuzzer/default_c_finding_folder/crash_20210629_185746_0127/delta/perses_result -resource-dir /scratch/software/clang-trunk/lib/clang/13.0.0 -c-isystem . -c-isystem /usr/local/include/cmsith -internal-isystem /scratch/software/clang-trunk/lib/clang/13.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -w -fdebug-compilation-dir=/scratch/cnsun/workspace/perses-fuzzer/default_c_finding_folder/crash_20210629_185746_0127/delta/perses_result -ferror-limit 19 -fgnuc-version=4.2.1 -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/mutant-d1a43a.o -x c mutant.c
1.	mutant.c:1:22: current parser token '}'
2.	mutant.c:1:5: parsing function body 'x'
3.	mutant.c:1:5: in compound statement ('{}')
 #&#8203;0 0x0000562559cc1714 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #&#8203;1 0x0000562559cbeece SignalHandler(int) Signals.cpp:0:0
 #&#8203;2 0x00007f2d7ba993c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #&#8203;3 0x00007f2d7b53818b raise /build/glibc-ZN95T4/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #&#8203;4 0x00007f2d7b517859 abort /build/glibc-ZN95T4/glibc-2.31/stdlib/abort.c:81:7
 #&#8203;5 0x00007f2d7b517729 get_sysdep_segment_value /build/glibc-ZN95T4/glibc-2.31/intl/loadmsgcat.c:509:8
 #&#8203;6 0x00007f2d7b517729 _nl_load_domain /build/glibc-ZN95T4/glibc-2.31/intl/loadmsgcat.c:970:34
 #&#8203;7 0x00007f2d7b528f36 (/lib/x86_64-linux-gnu/libc.so.6+0x36f36)
 #&#8203;8 0x000056255cda1835 (/scratch/software/clang-trunk/bin/clang-13+0x6a75835)
 #&#8203;9 0x000056255cdb2eab (anonymous namespace)::LValue::setFrom(clang::ASTContext&, clang::APValue const&) ExprConstant.cpp:0:0
#&#8203;10 0x000056255ce1f2f2 (anonymous namespace)::PointerExprEvaluator::VisitCastExpr(clang::CastExpr const*) ExprConstant.cpp:0:0
#&#8203;11 0x000056255cdee0b5 clang::StmtVisitorBase<llvm::make_const_ptr, (anonymous namespace)::PointerExprEvaluator, bool>::Visit(clang::Stmt const*) ExprConstant.cpp:0:0
#&#8203;12 0x000056255cdef346 EvaluatePointer(clang::Expr const*, (anonymous namespace)::LValue&, (anonymous namespace)::EvalInfo&, bool) ExprConstant.cpp:0:0
#&#8203;13 0x000056255ce24bf0 (anonymous namespace)::IntExprEvaluator::VisitBinaryOperator(clang::BinaryOperator const*) ExprConstant.cpp:0:0
#&#8203;14 0x000056255cde1115 clang::StmtVisitorBase<llvm::make_const_ptr, (anonymous namespace)::IntExprEvaluator, bool>::Visit(clang::Stmt const*) ExprConstant.cpp:0:0
#&#8203;15 0x000056255cdcf86e Evaluate(clang::APValue&, (anonymous namespace)::EvalInfo&, clang::Expr const*) ExprConstant.cpp:0:0
#&#8203;16 0x000056255cdd9809 EvaluateAsRValue((anonymous namespace)::EvalInfo&, clang::Expr const*, clang::APValue&) ExprConstant.cpp:0:0
#&#8203;17 0x000056255cddb012 clang::Expr::EvaluateForOverflow(clang::ASTContext const&) const (/scratch/software/clang-trunk/bin/clang-13+0x6aaf012)
#&#8203;18 0x000056255c0738a5 clang::Sema::CheckForIntOverflow(clang::Expr*) (/scratch/software/clang-trunk/bin/clang-13+0x5d478a5)
#&#8203;19 0x000056255c0c30f1 clang::Sema::CheckCompletedExpr(clang::Expr*, clang::SourceLocation, bool) (/scratch/software/clang-trunk/bin/clang-13+0x5d970f1)
#&#8203;20 0x000056255c465cb2 clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool) (/scratch/software/clang-trunk/bin/clang-13+0x6139cb2)
#&#8203;21 0x000056255c6bd42b clang::Sema::ActOnExprStmt(clang::ActionResult<clang::Expr*, true>, bool) (/scratch/software/clang-trunk/bin/clang-13+0x639142b)
#&#8203;22 0x000056255bfb3723 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/scratch/software/clang-trunk/bin/clang-13+0x5c87723)
#&#8203;23 0x000056255bfaac42 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributesWithRange&) (/scratch/software/clang-trunk/bin/clang-13+0x5c7ec42)
#&#8203;24 0x000056255bfab62a clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/scratch/software/clang-trunk/bin/clang-13+0x5c7f62a)
#&#8203;25 0x000056255bfac5a9 clang::Parser::ParseCompoundStatementBody(bool) (/scratch/software/clang-trunk/bin/clang-13+0x5c805a9)
#&#8203;26 0x000056255bfaebba clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/scratch/software/clang-trunk/bin/clang-13+0x5c82bba)
#&#8203;27 0x000056255bef4e52 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/scratch/software/clang-trunk/bin/clang-13+0x5bc8e52)
#&#8203;28 0x000056255bf217b0 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/scratch/software/clang-trunk/bin/clang-13+0x5bf57b0)
#&#8203;29 0x000056255beef636 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/scratch/software/clang-trunk/bin/clang-13+0x5bc3636)
#&#8203;30 0x000056255beefc21 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#&#8203;31 0x000056255bef6447 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/scratch/software/clang-trunk/bin/clang-13+0x5bca447)
#&#8203;32 0x000056255bef79de clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/scratch/software/clang-trunk/bin/clang-13+0x5bcb9de)
#&#8203;33 0x000056255bef7d89 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/scratch/software/clang-trunk/bin/clang-13+0x5bcbd89)
#&#8203;34 0x000056255beea1da clang::ParseAST(clang::Sema&, bool, bool) (/scratch/software/clang-trunk/bin/clang-13+0x5bbe1da)
#&#8203;35 0x000056255ae312a8 clang::CodeGenAction::ExecuteAction() (/scratch/software/clang-trunk/bin/clang-13+0x4b052a8)
#&#8203;36 0x000056255a6d4399 clang::FrontendAction::Execute() (/scratch/software/clang-trunk/bin/clang-13+0x43a8399)
#&#8203;37 0x000056255a6673b6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/scratch/software/clang-trunk/bin/clang-13+0x433b3b6)
#&#8203;38 0x000056255a7b20c0 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/scratch/software/clang-trunk/bin/clang-13+0x44860c0)
#&#8203;39 0x00005625575a4846 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/scratch/software/clang-trunk/bin/clang-13+0x1278846)
#&#8203;40 0x00005625575a0b88 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#&#8203;41 0x00005625574ce156 main (/scratch/software/clang-trunk/bin/clang-13+0x11a2156)
#&#8203;42 0x00007f2d7b5190b3 __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:342:3
#&#8203;43 0x00005625575a06fe _start (/scratch/software/clang-trunk/bin/clang-13+0x12746fe)
clang-13: error: unable to execute command: Aborted (core dumped)
clang-13: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 6b0d266036f73f5ee9556d211a7d0946091ff3b2)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
clang-13: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-13: note: diagnostic msg: /tmp/mutant-682b7f.c
clang-13: note: diagnostic msg: /tmp/mutant-682b7f.sh
clang-13: note: diagnostic msg:

********************

**Comment by Endilll** [comment]
Still crashing as of Clang 16: https://godbolt.org/z/n8M1P1h6b

**Comment by shafik** [comment]
Duplicate of: https://github.com/llvm/llvm-project/issues/30358
