### ISSUE TITLE
type mismatch assertion violation when generating code for function declaration

### ISSUE THREAD

**Issue by karineek** [llvm/llvm-project#50332]
|  |  |
| --- | --- |
| Bugzilla Link | [50988](https://llvm.org/bz50988) |
| Version | trunk |
| OS | Linux |
| Attachments | [trace and additional information](https://user-images.githubusercontent.com/93435480/143762285-e90152fd-1750-4629-9d38-a0e0f0343d0f.gz) |
| CC | @aeubanks,@dwblaikie,@karineek,@nikic |

## Extended Description 

The following code crashed Clang when adding debug information. 

static int d, b, k;
static char c[];
static int e[];
static int *f = e;
static short h();
short h() {
  int *n = &b;
  char *o = &d;
  *n = ((&c == o) > 40, 1); /* HERE */
  return 0;
}
int main() { h(); }

Compile: clang-13  0e836490069ceb4a485d852034e50a9c_878_test2520436154.c -o del.o

Version: the trace here is created from the trunk of today compiled with an address sanitizer.
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 5db826e4ce63a4d45a4695e5486841d08b86cd24)
Target: x86_64-unknown-linux-gnu

I am not sure that the bugs are actually related, because this trace doesn't pass through the loop vectorization part, but I still tested with the fix for bug #&#8203;45943; the crash still happens, as well as with previous versions: clang-13, clang-12 and clang-10.

It failed with an assertion violation: llvm/include/llvm/IR/Instructions.h:1215: void llvm::ICmpInst::AssertOK(): Assertion `getOperand(0)->getType() == getOperand(1)->getType() && "Both operands to ICmp instruction are not of the same type!"' failed.

Trace: see the attachment. 

One interesting thing is that removing the line "static short h();" eliminates the crash.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 15: https://godbolt.org/z/Y7336xczK
