### ISSUE TITLE
constness mismatch on defaulted copy constructor / assignment incorrectly prevents triviality

### ISSUE THREAD

**Issue by ec04fc15-fa35-46f2-80e1-5d271f2ef708** [llvm/llvm-project#50360]
|  |  |
| --- | --- |
| Bugzilla Link | [51016](https://llvm.org/bz51016) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Testcase:

struct Q {
  Q(Q&) noexcept(false) = default;
  Q &operator=(Q&) & noexcept(false) = default;
};
static_assert(__is_trivially_copyable(Q), "");

The assertion here should pass: changing the ref-qualifier, exception specification, or the constness of the parameter type should not affect the triviality of a defaulted special member function.

Clang incorrectly treats the special member functions as being non-trivial here because their parameter types don't have the expected constness.

**Comment by royjacobson** [comment]
Fixed: https://reviews.llvm.org/D127593
