### ISSUE TITLE
RFE: add mlir dist tar ball

### ISSUE THREAD

**Issue by 4084477f-e1df-4024-a410-168c80096e18** [llvm/llvm-project#50383]
|  |  |
| --- | --- |
| Bugzilla Link | [51039](https://llvm.org/bz51039) |
| Version | unspecified |
| OS | Windows NT |
| CC | @jpienaar,@River707 |

## Extended Description 
IMO it would be niece to add mlir dist tar ball like for other LLVM components.

**Comment by JOE1994** [comment]
MLIR tarballs are currently provided
