### ISSUE TITLE
SimpleLoopUnswitch hoists branches on poison/undef (Wrong code at -O3 on x86_64-linux-gnu)

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#50387]
|  |  |
| --- | --- |
| Bugzilla Link | [51043](https://llvm.org/bz51043) |
| Version | trunk |
| OS | All |
| CC | @aeubanks,@alinas,@aqjune,@nunoplopes,@regehr,@sjoerdmeijer,@rotateright |

## Extended Description 
[706] % clangtk -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 4a3b0556536d5a2555f7a19f953f0eec0f79f1a9)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
[707] % 
[707] % clangtk -O2 small.c; ./a.out
[708] % 
[708] % clangtk -O3 small.c
[709] % ./a.out
Aborted
[710] % 
[710] % cat small.c
int a = 1, b = 1;
int main() {
  short d, g, i;
  int e = 34000, h;
  d = b;
  g = 100 | b;
L1:
  i = g;
L2:
  g = ~(d / e);
  e = ~((2 / g) & d);
  h = a;
  while (!e) {
    a = b;
    e = ~(1L << i);
  }
  if (g > 0)
    goto L2;
  if (!g)
    goto L1;
  if (h < e)
    __builtin_abort ();
  return 0;
}

**Comment by fhahn** [comment]
the original clang reproducer doesn't cause any issues now, but the underlying issue is still there. @aqjune do you know if there are any remaining blockers for enabling `-freeze-loop-unswitch-cond=true`?

**Comment by aqjune** [comment]
No, I am not aware of any blockers..!
Time to finally set it to false?

**Comment by fhahn** [comment]
> No, I am not aware of any blockers..!

let me collect some numbers to sanity check

**Comment by fhahn** [comment]
> > No, I am not aware of any blockers..!
> 
> let me collect some numbers to sanity check

Finally got around to that. There were no performance regressions on the AArch64 system I tried with O3 in SPEC2006,SPEC2017 and an internal benchmark suite.

Patch to flip the default:  https://reviews.llvm.org/D124252

**Comment by nunoplopes** [comment]
Thanks, this fixed 3 tests:
-  LLVM :: Transforms/SimpleLoopUnswitch/delete-dead-blocks.ll
-  LLVM :: Transforms/SimpleLoopUnswitch/guards.ll
-  LLVM :: Transforms/SimpleLoopUnswitch/nontrivial-unswitch-cost.ll

3 more to go, though!

**Comment by fhahn** [comment]
@nunoplopes what are the remaining 3?

**Comment by nunoplopes** [comment]
- Transforms/SimpleLoopUnswitch/LIV-loop-condtion.ll
 - Transforms/SimpleLoopUnswitch/nontrivial-unswitch.ll
 - Transforms/SimpleLoopUnswitch/trivial-unswitch.ll

See here: https://web.ist.utl.pt/nuno.lopes/alive2/index.php?hash=1fb52562ffabc05d

**Comment by fhahn** [comment]
Sounds good, I'll look in to trivial unswitching case tomorrow. Is there an issue for those?

**Comment by nunoplopes** [comment]
Thank you!
There's no bug report on those AFAIK. I didn't reduce those test cases as I thought they were all the same, sorry.

**Comment by fhahn** [comment]
I put up https://reviews.llvm.org/D124554, https://reviews.llvm.org/D124549, https://reviews.llvm.org/D124526 to fix some of the remaining issues. After that, there's one failure left I think. Lots of tests seem to time out though.

**Comment by fhahn** [comment]
> I put up https://reviews.llvm.org/D124554, https://reviews.llvm.org/D124549, https://reviews.llvm.org/D124526 to fix some of the remaining issues. After that, there's one failure left I think. Lots of tests seem to time out though.

All patches have now landed, I'm not seeing any verification failures for SimpleLoopUnswitch locally any longer.

**Comment by nunoplopes** [comment]
> > I put up https://reviews.llvm.org/D124554, https://reviews.llvm.org/D124549, https://reviews.llvm.org/D124526 to fix some of the remaining issues. After that, there's one failure left I think. Lots of tests seem to time out though.
> 
> All patches have now landed, I'm not seeing any verification failures for SimpleLoopUnswitch locally any longer.

Confirmed, all SLU tests pass now. Thank you @fhahn!
