### ISSUE TITLE
clang uses a lot of memory when compiling new T[big number]

### ISSUE THREAD

**Issue by df24fb27-6869-485f-ad93-24759d6d7307** [llvm/llvm-project#50421]
|  |  |
| --- | --- |
| Bugzilla Link | [51077](https://llvm.org/bz51077) |
| Version | 11.0 |
| OS | Linux |
| Attachments | [clang stderr](https://user-images.githubusercontent.com/93435569/143762304-7a3f9808-3e97-4ec4-8f8c-160b8394a09c.gz) |
| CC | @zygoloid |

## Extended Description 

Steps to reproduce:
1. Create file source.cpp with following content:
struct T {
    char x;
};

T* f() {
    return new T[100000000];
}

2. Run clang++ -v -c source.cpp -o source.o

Expected outcome:
clang creates object file without using too much memory
Actual outcome:
clang uses about 8GB of memory (and then on my machine is killed for OOM)
clang output attached.

This is easily reproducible on godbolt.org: clang 9 compiles this code just fine, clang 10.0 or above reports out of memory https://godbolt.org/z/d9oej9a57

If we replace struct T with using T = char, everything works fine.
If we replace T[100000000] with T[10000000], clang uses about 1.6GB of memory but compiles successfully.

On other machine, clang 12 compiles this file, but uses about 12GB of memory in process.

**Comment by JOE1994** [comment]
Issue seems resolved as of `clang 19.1.0` : https://godbolt.org/z/EqxWcT977
