### ISSUE TITLE
Extraneous enum record in DWARF with type units

### ISSUE THREAD

**Issue by jmorse** [llvm/llvm-project#50431]
|  |  |
| --- | --- |
| Bugzilla Link | [51087](https://llvm.org/bz51087) |
| Version | trunk |
| OS | Linux |
| CC | @adrian-prantl,@dwblaikie,@pogo59 |

## Extended Description 
This PR is a summary of an interesting scenario I've run into, where using type units increases binary size, although only compared to constructor homing de-duplication of types. Take a look at this reproducer, compiled with the following flags using main / ee8da6369225f4:

clang++ test.cpp -o test.o -c -g -O2 -fdebug-types-section -gdwarf-5

--------8<--------
class fudge {
public:
  enum blah {
    a = 1,
    b = 2
  };

  blah baz;

  fudge() { }
};

fudge bar;
-------->8--------

If you take a look with llvm-dwarfdump at the output file, there are type units for "fudge" and "blah" as expected, and for the "bar variable:

  0x0000001e:   DW_TAG_variable
                  DW_AT_name      ("bar")
                  DW_AT_type      (0x00000029 "class ")
                  DW_AT_external  (true)
                  DW_AT_decl_file ("test.cpp")
                  DW_AT_decl_line (13)
                  DW_AT_location  (DW_OP_addrx 0x0)

  0x00000029:   DW_TAG_class_type
                  DW_AT_declaration       (true)
                  DW_AT_signature (0x1c93e96b85e3f5c8)

  0x00000032:     DW_TAG_enumeration_type
                    DW_AT_declaration     (true)
                    DW_AT_signature       (0x9b7ed24ce9445148)

To me, the DW_TAG_enumeration_type in the class definition is unexpected, as the "fudge" type unit completely describes the contents of the class. Nothing in the DWARF refers to the enum type. To me, this seems like an inefficiency.

Not shown is the larger project I've looked at, where there are enough redundant child-enum-DIEs and child-class-DIEs in each class DIE to add a few Mb of .debug_info (out of ~160Mb of .debug_info). The net effect is that running with "-Xclang -fuse-ctor-homing -fdebug-types-section" is larger than just using "-Xclang -fuse-ctor-homing"

**Comment by OCHyams** [comment]
Should be fixed by [D115325](https://reviews.llvm.org/D115325): 78d15a112cbd545fbb6e1aa37c221ef5aeffb3f2 (and follow up bot-break fix 54586582d3e17c0bba76258d2930486a6dfaaf2a).

Opened up two related issues #52775 and #52777.
