### ISSUE TITLE
wrong code at -O3 on x86_64-linux-gnu

### ISSUE THREAD

**Issue by 2b5303c8-21ec-41c3-ac18-7401cc1fc384** [llvm/llvm-project#50430]
|  |  |
| --- | --- |
| Bugzilla Link | [51086](https://llvm.org/bz51086) |
| Version | trunk |
| OS | All |
| CC | @aqjune,@zygoloid,@rotateright |

## Extended Description 
It appears to be a recent regression. clang-12 works fine.

$ clang-trunk -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 20176bc7dd3f431db4c3d59b51a9f53d52190c82)
Target: x86_64-unknown-linux-gnu
Thread model: posix

$ clang-trunk abc.c ; ./a.out
-26

$ clang-trunk -O3 abc.c ; ./a.out
0

$ cat abc.c
int a, b;
static int c = 92;
long d;
short(e)(f) { return f; }
long g() {
  short h;
  int i = d >= 0;
  for (; b > -26; --b) {
    if (i)
      continue;
    for (; i - 30; i--) {
      h = a << c;
      if (h)
        return 7;
    }
  }
}
int main() {
  g();
  if (e(0))
    c++;
  printf("%d\n", b);
}

**Comment by fhahn** [comment]
Clang/LLVM now produces the same output with both -O1/-O3: https://godbolt.org/z/baE67qj5d
