### ISSUE TITLE
Error in MIPSISelLowering performMADD_MSUBCombine for sub (mul r1, r2), r3 case

### ISSUE THREAD

**Issue by digitalseraphim** [llvm/llvm-project#50458]
|  |  |
| --- | --- |
| Bugzilla Link | [51114](https://llvm.org/bz51114) |
| Version | unspecified |
| OS | Linux |
| Attachments | [test code](https://user-images.githubusercontent.com/93435565/143762313-03ca4611-fde6-48a0-b27e-cf046060ed23.gz) |

## Extended Description 

When combining a sub instruction with a mul instruction, and the mul is the "left" argument, the resulting code is incorrect. Because of how the msub instruction works, combining always puts the mul on the right. This means the result in this case is the negative of what the value should be. `[ r1 - (r2*r3) = -((r2*r3) - r1) ]`. I have attached sample c code that shows this error. I left out error handling to simplify it, but passing "7 7 7" (no quotes, obv.) should result in "c = 42, d = -42", but on mips it results in "c = -42, d = -42".

**Comment by RKSimon** [comment]
CC @atanasyan

**Comment by sdardis** [comment]
Patch posted to https://reviews.llvm.org/D124742

**Comment by sdardis** [comment]
Fix committed as [a35add4c54be96a42fefc01ae1d74a23e3c16030](https://reviews.llvm.org/rGa35add4c54be96a42fefc01ae1d74a23e3c16030).

If there's anything wrong with the fix, can you file a new report?

Thanks for the bug report!
