### ISSUE TITLE
Multiple immediate invocation expression-statements of lambda expressions should be constant expressions

### ISSUE THREAD

**Issue by 976866b7-fc02-4d23-a1c0-197b08fd7c0e** [llvm/llvm-project#50455]
|  |  |
| --- | --- |
| Bugzilla Link | [51111](https://llvm.org/bz51111) |
| Version | trunk |
| OS | Linux |
| CC | @JohelEGP,@zygoloid |

## Extended Description 
See https://godbolt.org/z/YqG7P977v.
```C++
void f() {
  []() consteval { int i{}; }();
  []() consteval { int i{}; ++i; }();
}
void g() {
  (void)[](int i) consteval { return i; }(0);
  (void)[](int i) consteval { return i; }(0);
}
```

**Comment by royjacobson** [comment]
@usx95 did you consider backporting to Clang 15.x? Seems like a pretty safe fix.

**Comment by usx95** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/e7eec38246560781e0a4020b19c7eb038a8c5655
