### ISSUE TITLE
Wrong location for unexpanded parameter pack in function template

### ISSUE THREAD

**Issue by 3a17e7c4-fca4-4827-b2a7-11a54d73d746** [llvm/llvm-project#50462]
|  |  |
| --- | --- |
| Bugzilla Link | [51118](https://llvm.org/bz51118) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
template<typename... Elements>
class tuple
{ };

template<typename... Elements>
tuple<Elements>
get(const tuple<Elements...>& t)
{
  return t;
}

The error shows the wrong location:

t2.C:7:1: error: declaration type contains unexpanded parameter pack 'Elements'
get(const tuple<Elements...>& t)
^
1 error generated.

The error is on the previous line, not the one shown.

**Comment by wheatman** [comment]
This was fixed between 16 and trunk(68e94f1f27b658183c3ebbce4aaadc437d0cee3a)
https://godbolt.org/z/zMr8qdz6n

code
```
template<typename... Elements>
class tuple
{ };

template<typename... Elements>
tuple<Elements>
get(const tuple<Elements...>& t)
{
  return t;
}

```

old error
```
<source>:7:1: error: declaration type contains unexpanded parameter pack 'Elements'
get(const tuple<Elements...>& t)
^
1 error generated.
Compiler returned: 1
```

new error
```
<source>:7:1: error: declaration type contains unexpanded parameter pack 'Elements'
    6 | tuple<Elements>
      |       ~~~~~~~~
    7 | get(const tuple<Elements...>& t)
      | ^
1 error generated.
Compiler returned: 1
```
