### ISSUE TITLE
Clang segfaults when compiling code with std::variant

### ISSUE THREAD

**Issue by cerg2010cerg2010** [llvm/llvm-project#50471]
|  |  |
| --- | --- |
| Bugzilla Link | [51127](https://llvm.org/bz51127) |
| Version | 12.0 |
| OS | Linux |
| Attachments | [stacktrace output](https://user-images.githubusercontent.com/93435563/143762315-b4cbb48c-1f7f-487c-b236-456c366734c9.gz), [preprocessed output](https://user-images.githubusercontent.com/93435563/143762316-7001c3d5-c309-44ea-9f8f-3ae1da5e5f21.gz), [run script](https://user-images.githubusercontent.com/93435563/143762317-2bd60d3e-c19a-4ca5-bab3-d594d82a0d40.gz) |
| CC | @zygoloid |

## Extended Description 

Consider this code snippet:

#include <variant>

struct Foo
{
    operator std::variant<int, float>()
    {
        return 0;
    }
};

constexpr void foo()
{
  std::variant<int, float, Foo> var1 = 0;
  std::variant<int, float> var2;
  var2 = std::visit([](auto arg) -> decltype(var2) { return arg; }, var1);
}

int main(int argc, char** argv)
{
    return 0;
}

Latest Clang release version (12.0.1 atm), as well as trunk and older versions up to 3.9.0 which has -std=c++1z and variant header (tested on godbolt.org) segfault when compiling this. GCC handles this code fine. Also it crashes with both -stdlib=libc++ and -stdlib=libstdc++.

One particular thing which is interesting here is that if you replace return 0 in conversion function with return {}, the trunk version will compile this, but 12.0.1 will not. I've also had other variants of this code when adding a newline at the end of file and removing it will determine the result. The example provided here is the most stable to reproduce.

I've tried this mostly on godbolt.org, but it also successfully reproduces on my local machine with Arch Linux (with clang version 12.0.1)

**Comment by Endilll** [comment]
Fixed in Clang trunk (17): https://godbolt.org/z/EE47d4K6z
