### ISSUE TITLE
errors on declaration returning an abstract class

### ISSUE THREAD

**Issue by 91b604ff-5b4e-4821-a182-129f49d1a44c** [llvm/llvm-project#50489]
|  |  |
| --- | --- |
| Bugzilla Link | [51145](https://llvm.org/bz51145) |
| Version | trunk |
| OS | Windows NT |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Clang errors with the following code. MSVC and GCC compile fine.

https://godbolt.org/z/n9YqEPEMe

struct S
{
    virtual void m() = 0;
};

S f();

I believe MSVC and GCC have implemented P0929R2
http://open-std.org/JTC1/SC22/WG21/docs/papers/2018/p0929r2.html

**Comment by wheatman** [comment]
This was fixed between 16 and 17.0.1, and the code now compiles 
https://godbolt.org/z/4cGsEjKe9
