### ISSUE TITLE
typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = clang::CXXRecordDecl; Y = clang::DeclContext; typename llvm::cast_retty<X, Y*>::ret_type = clang::CXXRecordDecl*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' f

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#50536]
|  |  |
| --- | --- |
| Bugzilla Link | [51192](https://llvm.org/bz51192) |
| Version | trunk |
| OS | All |
| CC | @zygoloid |

## Extended Description 
$ clang-trunk -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git ab5ac659c81a453a3f58df94f39fe8ba3cd35918)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$ cat mutant.c

```c
union {
  struct {
    char x;
  } char z[x];
};
```

$ clang-trunk  mutant.c
mutant.c:4:4: error: expected ';' after struct
  } char z[x];
   ^
   ;
clang-13: /tmp/tmp.Gcp8nSn9Hr-clang-builder/llvm-project/llvm/include/llvm/Support/Casting.h:269: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = clang::CXXRecordDecl; Y = clang::DeclContext; typename llvm::cast_retty<X, Y*>::ret_type = clang::CXXRecordDecl*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /scratch/software/clang-trunk/bin/clang-13 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -main-file-name mutant.c -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fcoverage-compilation-dir=/scratch/cnsun/workspace/perses-fuzzer/temp_testing_campaigns/default_finding_folder_c/crash_20210715_061514_6d58/delta/perses_result -resource-dir /scratch/software/clang-trunk/lib/clang/13.0.0 -c-isystem . -c-isystem /usr/local/include/cmsith -internal-isystem /scratch/software/clang-trunk/lib/clang/13.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir=/scratch/cnsun/workspace/perses-fuzzer/temp_testing_campaigns/default_finding_folder_c/crash_20210715_061514_6d58/delta/perses_result -ferror-limit 19 -fgnuc-version=4.2.1 -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/mutant-475b95.o -x c mutant.c
1.	mutant.c:4:13: current parser token ']'
2.	mutant.c:1:1: parsing struct/union body '(anonymous)'
 #&#8203;0 0x00005634745f8754 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #&#8203;1 0x00005634745f5e6e SignalHandler(int) Signals.cpp:0:0
 #&#8203;2 0x00007efc49de13c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #&#8203;3 0x00007efc4988018b raise /build/glibc-ZN95T4/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #&#8203;4 0x00007efc4985f859 abort /build/glibc-ZN95T4/glibc-2.31/stdlib/abort.c:81:7
 #&#8203;5 0x00007efc4985f729 get_sysdep_segment_value /build/glibc-ZN95T4/glibc-2.31/intl/loadmsgcat.c:509:8
 #&#8203;6 0x00007efc4985f729 _nl_load_domain /build/glibc-ZN95T4/glibc-2.31/intl/loadmsgcat.c:970:34
 #&#8203;7 0x00007efc49870f36 (/lib/x86_64-linux-gnu/libc.so.6+0x36f36)
 #&#8203;8 0x0000563476e3e17b clang::Sema::BuildPossibleImplicitMemberExpr(clang::CXXScopeSpec const&, clang::SourceLocation, clang::LookupResult&, clang::TemplateArgumentListInfo const*, clang::Scope const*, clang::UnresolvedLookupExpr*) (/scratch/software/clang-trunk/bin/clang-13+0x636b17b)
 #&#8203;9 0x0000563476ce7a27 clang::Sema::ActOnIdExpression(clang::Scope*, clang::CXXScopeSpec&, clang::SourceLocation, clang::UnqualifiedId&, bool, bool, clang::CorrectionCandidateCallback*, bool, clang::Token*) (/scratch/software/clang-trunk/bin/clang-13+0x6214a27)
#&#8203;10 0x00005634768ad977 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/scratch/software/clang-trunk/bin/clang-13+0x5dda977)
#&#8203;11 0x00005634768afa1b clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (/scratch/software/clang-trunk/bin/clang-13+0x5ddca1b)
#&#8203;12 0x00005634768afabd clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/scratch/software/clang-trunk/bin/clang-13+0x5ddcabd)
#&#8203;13 0x000056347688a7d9 clang::Parser::ParseBracketDeclarator(clang::Declarator&) (/scratch/software/clang-trunk/bin/clang-13+0x5db77d9)
#&#8203;14 0x000056347688f323 clang::Parser::ParseDirectDeclarator(clang::Declarator&) (/scratch/software/clang-trunk/bin/clang-13+0x5dbc323)
#&#8203;15 0x0000563476877f98 clang::Parser::ParseDeclaratorInternal(clang::Declarator&, void (clang::Parser::*)(clang::Declarator&)) (/scratch/software/clang-trunk/bin/clang-13+0x5da4f98)
#&#8203;16 0x0000563476889634 clang::Parser::ParseStructDeclaration(clang::ParsingDeclSpec&, llvm::function_ref<void (clang::ParsingFieldDeclarator&)>) (/scratch/software/clang-trunk/bin/clang-13+0x5db6634)
#&#8203;17 0x0000563476889ddf clang::Parser::ParseStructUnionBody(clang::SourceLocation, clang::TypeSpecifierType, clang::RecordDecl*) (/scratch/software/clang-trunk/bin/clang-13+0x5db6ddf)
#&#8203;18 0x00005634768a5996 clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::ParsedAttributesWithRange&) (/scratch/software/clang-trunk/bin/clang-13+0x5dd2996)
#&#8203;19 0x00005634768846e5 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) (/scratch/software/clang-trunk/bin/clang-13+0x5db16e5)
#&#8203;20 0x0000563476855fd3 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/scratch/software/clang-trunk/bin/clang-13+0x5d82fd3)
#&#8203;21 0x0000563476856761 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#&#8203;22 0x000056347685cf87 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/scratch/software/clang-trunk/bin/clang-13+0x5d89f87)
#&#8203;23 0x000056347685e51e clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/scratch/software/clang-trunk/bin/clang-13+0x5d8b51e)
#&#8203;24 0x000056347685e8c9 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/scratch/software/clang-trunk/bin/clang-13+0x5d8b8c9)
#&#8203;25 0x0000563476850d1a clang::ParseAST(clang::Sema&, bool, bool) (/scratch/software/clang-trunk/bin/clang-13+0x5d7dd1a)
#&#8203;26 0x000056347578b2f8 clang::CodeGenAction::ExecuteAction() (/scratch/software/clang-trunk/bin/clang-13+0x4cb82f8)
#&#8203;27 0x0000563475029419 clang::FrontendAction::Execute() (/scratch/software/clang-trunk/bin/clang-13+0x4556419)
#&#8203;28 0x0000563474fbf07e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/scratch/software/clang-trunk/bin/clang-13+0x44ec07e)
#&#8203;29 0x0000563475107710 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/scratch/software/clang-trunk/bin/clang-13+0x4634710)
#&#8203;30 0x0000563471e7315d cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/scratch/software/clang-trunk/bin/clang-13+0x13a015d)
#&#8203;31 0x0000563471e6f4a8 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#&#8203;32 0x0000563471d9a126 main (/scratch/software/clang-trunk/bin/clang-13+0x12c7126)
#&#8203;33 0x00007efc498610b3 __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:342:3
#&#8203;34 0x0000563471e6f01e _start (/scratch/software/clang-trunk/bin/clang-13+0x139c01e)
clang-13: error: unable to execute command: Aborted (core dumped)
clang-13: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 13.0.0 (https://github.com/llvm/llvm-project.git ab5ac659c81a453a3f58df94f39fe8ba3cd35918)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
clang-13: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-13: note: diagnostic msg: /tmp/mutant-19f4ac.c
clang-13: note: diagnostic msg: /tmp/mutant-19f4ac.sh
clang-13: note: diagnostic msg:

********************

**Comment by shafik** [comment]
Confirmed: https://godbolt.org/z/bPqEo4Wz5

**Comment by shafik** [comment]
This looks like a duplicate of: https://github.com/llvm/llvm-project/issues/31295
