### ISSUE TITLE
Missed opportunities for register promotion

### ISSUE THREAD

**Issue by momchil-velikov** [llvm/llvm-project#50537]
|  |  |
| --- | --- |
| Bugzilla Link | [51193](https://llvm.org/bz51193) |
| Version | trunk |
| OS | Windows NT |
| CC | @DMG862,@efriedma-quic,@shubhamnarlawar77 |

## Extended Description 
Considering this example (https://gcc.godbolt.org/z/55dfPrc8T), compiled with 
`clang -target aarch64-linux -Ofast`

```
int u, v;

void f(int a[restrict], int b[restrict], int n) {
    for (int i = 0; i < n; ++i) {
        if (a[i]) {
            ++u;
            break;
        }
        ++u;
        if (b[i])
            ++v;
    }
}
```

Clang emits 

```
f:                                      // @&#8203;f
        cmp     w2, #&#8203;1                          // =1
        b.lt    .LBB0_7
        adrp    x8, u
        ldr     w10, [x8, :lo12:u]
        mov     w9, w2
        add     w12, w10, #&#8203;1                    // =1
        adrp    x10, v
        b       .LBB0_3
.LBB0_2:                                //   in Loop: Header=BB0_3 Depth=1
        add     w12, w11, #&#8203;1                    // =1
        add     x1, x1, #&#8203;4                      // =4
        subs    x9, x9, #&#8203;1                      // =1
        add     x0, x0, #&#8203;4                      // =4
        b.eq    .LBB0_6
.LBB0_3:                                // =>This Inner Loop Header: Depth=1
        ldr     w13, [x0]
        mov     w11, w12
        cbnz    w13, .LBB0_6
        ldr     w12, [x1]
        cbz     w12, .LBB0_2
        ldr     w12, [x10, :lo12:v]
        add     w12, w12, #&#8203;1                    // =1
        str     w12, [x10, :lo12:v]
        b       .LBB0_2
.LBB0_6:
        str     w11, [x8, :lo12:u]
.LBB0_7:
        ret
```

where the updates to `u` are performed with a single store instruction after the loop, for the case the loop body is executed at least once. In contrast, updates to `v` are performed on each loop iteration, since moving them outside the loop may introduce traps or data race. 

In the output for the same code, compiled with GCC with `-Ofast` even updates to `v` are moved out of the loop, since `-Ofast` enables ` -fallow-store-data-races`. But even compiled with `-O2`, the
updates to `v` are still moved outside the loop, only that the store that writes to `v` is conditional, , i.e:

```
f:
        cmp     w2, 0
        ble     .L1
        adrp    x10, .LANCHOR0
        add     x11, x10, :lo12:.LANCHOR0
        mov     x3, 0
        mov     w8, 0
        ldr     w9, [x10, #:lo12:.LANCHOR0]
        mov     w7, 0
        ldr     w6, [x11, 4]
        add     w5, w2, w9
        mov     w2, w9
        b       .L7
.L3:
        ldr     w4, [x1, x3]
        add     w2, w2, 1
        add     x3, x3, 4
        mov     w7, 1
        cbz     w4, .L6
        add     w6, w6, w7
        mov     w8, w7
.L6:
        cmp     w2, w5
        beq     .L22
.L7:
        ldr     w4, [x0, x3]
        cbz     w4, .L3
        cbz     w8, .L4
        str     w6, [x11, 4]
.L4:
        cmp     w7, 0
        csel    w9, w9, w2, eq
        add     w9, w9, 1
        str     w9, [x10, #:lo12:.LANCHOR0]
.L1:
        ret
.L22:
        cbz     w8, .L8
        str     w6, [x11, 4]
.L8:
        str     w2, [x10, #:lo12:.LANCHOR0]
        ret
```

Clang/LLVM could take advantage of a command line option, function or variable attribute that allows transformations that could potentially introduce data races. That sounds reasonable for single-threaded programs or for part of code where absence of data races is guaranteed at a different level of abstraction.

Even without introducing violations of the C/C++/LLVM memory model, LLVM could hoist the load, e.g. transform

```
for ... {
  ...
  if cond {
   x0 = *a
   x1 = x0 + 1
   *a = x1
  }
  ...
}
```

into

```
x0 = *a
for ... {
  ...
  x1 = phi(x0, x3)
  if cond {
    x2 = x1 + 1
    *a = x2
  }
  x3 = phi(x1, x2)
  ...
}
```

if `a` is determined to be dereferenceable.

**Comment by shubhamnarlawar77** [comment]
> 1. LICM could hoist the load without hoisting the store, by inserting appropriate PHI nodes.

I have created a draft patch to discuss above points - https://reviews.llvm.org/D130466

**Comment by shubhamnarlawar77** [comment]
> Bugzilla Link 	[51193](https://llvm.org/bz51193)
> Version 	trunk
> OS 	Windows NT
> CC 	@DMG862,@efriedma-quic,@shubhamnarlawar77
> ## Extended Description
> 
> Considering this example (https://gcc.godbolt.org/z/55dfPrc8T), compiled with `clang -target aarch64-linux -Ofast`
> 
> ```
> int u, v;
> 
> void f(int a[restrict], int b[restrict], int n) {
>     for (int i = 0; i < n; ++i) {
>         if (a[i]) {
>             ++u;
>             break;
>         }
>         ++u;
>         if (b[i])
>             ++v;
>     }
> }
> ```
> 
> Clang emits
> 
> ```
> f:                                      // @&#8203;f
>         cmp     w2, #&#8203;1                          // =1
>         b.lt    .LBB0_7
>         adrp    x8, u
>         ldr     w10, [x8, :lo12:u]
>         mov     w9, w2
>         add     w12, w10, #&#8203;1                    // =1
>         adrp    x10, v
>         b       .LBB0_3
> .LBB0_2:                                //   in Loop: Header=BB0_3 Depth=1
>         add     w12, w11, #&#8203;1                    // =1
>         add     x1, x1, #&#8203;4                      // =4
>         subs    x9, x9, #&#8203;1                      // =1
>         add     x0, x0, #&#8203;4                      // =4
>         b.eq    .LBB0_6
> .LBB0_3:                                // =>This Inner Loop Header: Depth=1
>         ldr     w13, [x0]
>         mov     w11, w12
>         cbnz    w13, .LBB0_6
>         ldr     w12, [x1]
>         cbz     w12, .LBB0_2
>         ldr     w12, [x10, :lo12:v]
>         add     w12, w12, #&#8203;1                    // =1
>         str     w12, [x10, :lo12:v]
>         b       .LBB0_2
> .LBB0_6:
>         str     w11, [x8, :lo12:u]
> .LBB0_7:
>         ret
> ```
> 
> where the updates to `u` are performed with a single store instruction after the loop, for the case the loop body is executed at least once. In contrast, updates to `v` are performed on each loop iteration, since moving them outside the loop may introduce traps or data race.
> 
> In the output for the same code, compiled with GCC with `-Ofast` even updates to `v` are moved out of the loop, since `-Ofast` enables ` -fallow-store-data-races`. But even compiled with `-O2`, the updates to `v` are still moved outside the loop, only that the store that writes to `v` is conditional, , i.e:
> 
> ```
> f:
>         cmp     w2, 0
>         ble     .L1
>         adrp    x10, .LANCHOR0
>         add     x11, x10, :lo12:.LANCHOR0
>         mov     x3, 0
>         mov     w8, 0
>         ldr     w9, [x10, #:lo12:.LANCHOR0]
>         mov     w7, 0
>         ldr     w6, [x11, 4]
>         add     w5, w2, w9
>         mov     w2, w9
>         b       .L7
> .L3:
>         ldr     w4, [x1, x3]
>         add     w2, w2, 1
>         add     x3, x3, 4
>         mov     w7, 1
>         cbz     w4, .L6
>         add     w6, w6, w7
>         mov     w8, w7
> .L6:
>         cmp     w2, w5
>         beq     .L22
> .L7:
>         ldr     w4, [x0, x3]
>         cbz     w4, .L3
>         cbz     w8, .L4
>         str     w6, [x11, 4]
> .L4:
>         cmp     w7, 0
>         csel    w9, w9, w2, eq
>         add     w9, w9, 1
>         str     w9, [x10, #:lo12:.LANCHOR0]
> .L1:
>         ret
> .L22:
>         cbz     w8, .L8
>         str     w6, [x11, 4]
> .L8:
>         str     w2, [x10, #:lo12:.LANCHOR0]
>         ret
> ```
> 
> Clang/LLVM could take advantage of a command line option, function or variable attribute that allows transformations that could potentially introduce data races. That sounds reasonable for single-threaded programs or for part of code where absence of data races is guaranteed at a different level of abstraction.
> 
> Even without introducing violations of the C/C++/LLVM memory model, LLVM could hoist the load, e.g. transform
> 
> ```
> for ... {
>   ...
>   if cond {
>    x0 = *a
>    x1 = x0 + 1
>    *a = x1
>   }
>   ...
> }
> ```
> 
> into
> 
> ```
> x0 = *a
> for ... {
>   ...
>   x1 = phi(x0, x3)
>   if cond {
>     x2 = x1 + 1
>     *a = x2
>   }
>   x3 = phi(x1, x2)
>   ...
> }
> ```
> 
> if `a` is determined to be dereferenceable.

I have achieved above in this patch - https://reviews.llvm.org/D130466#3718942

**Comment by shubhamnarlawar77** [comment]
> I see three potential optimizations here:
> 
>     1. LICM could hoist the load without hoisting the store, by inserting appropriate PHI nodes.
> 
>     2. LICM can sink the store if there are aren't any abnormal loop exits; we just need to make the store conditional on whether the value was written to.
> 
>     3. We could teach LICM to special-case single-threaded code.  I don't really like -fallow-store-data-races; it seem hard to define a coherent model for it.  If you have multiple threads, they're almost certainly accessing shared data; otherwise, how would the threads know what they're supposed to do?  Maybe we could use -mthread-model, though.

Hello @efriedma-quic,

I have achieved all above 3 cases. But I am still not sure whether you are open to keep flag approach here - https://reviews.llvm.org/D130466

What do you think about above approach? Let me know if you have any better suggestions on above. In the worst case scenario, we have a flag approach for which user will be responsible to write single threaded code.

**Comment by efriedma-quic** [comment]
D130466 is the third case of the three I mentioned.  The other two cases involve implementing optimizations that are legal on code that isn't single-threaded.

The general idea seems okay; I'll comment on the review about the details.

**Comment by shubhamnarlawar77** [comment]
> D130466 is the third case of the three I mentioned. The other two cases involve implementing optimizations that are legal on code that isn't single-threaded.
> 
> The general idea seems okay; I'll comment on the review about the details.

@efriedma-quic - I have updated the patch as per your comments. Can you please take look at it and suggest changes if any?

1. I am sinking store from the loop of thread model is single
2. I have renamed licm flag to -force-licm-thread-model-single

**Comment by shubhamnarlawar77** [comment]
@efriedma-quic @momchil-velikov - Any suggestions on my latest patch on phabricator?

**Comment by shubhamnarlawar77** [comment]
I have submitted requested LIT tests on phabricator - https://reviews.llvm.org/D130466

@efriedma-quic @nikic @momchil-velikov - Can you please give review on it? Is it ready to merge?

**Comment by shubhamnarlawar77** [comment]
Addressed all the review comments on the phabricator - https://reviews.llvm.org/D130466

**Comment by shubhamnarlawar77** [comment]
Review request - @momchil-velikov @davemgreen @efriedma-quic @nikic @fhahn 

Can someone give final review? If this patch is fine, is it ready to merge?
-> https://reviews.llvm.org/D130466

All review comments have been addressed with no regression.

I have added requested minimal testcase derived from original testcase which is attached above in this github thread. More details about the minimal testcases can be found here - https://reviews.llvm.org/D130466#3821839

**Comment by shubhamnarlawar77** [comment]
PING.

Review request on https://reviews.llvm.org/D130466 for merging it.

**Comment by shubhamnarlawar77** [comment]
> Review request - @momchil-velikov @davemgreen @efriedma-quic @nikic @fhahn
> 
> Can someone give final review? If this patch is fine, is it ready to merge? -> https://reviews.llvm.org/D130466
> 
> All review comments have been addressed with no regression.
> 
> I have added requested minimal testcase derived from original testcase which is attached above in this github thread. More details about the minimal testcases can be found here - https://reviews.llvm.org/D130466#3821839

PING.

**Comment by shubhamnarlawar77** [comment]
> Review request - @momchil-velikov @davemgreen @efriedma-quic @nikic @fhahn
> 
> Can someone give final review? If this patch is fine, is it ready to merge? -> https://reviews.llvm.org/D130466
> 
> All review comments have been addressed with no regression.
> 
> I have added requested minimal testcase derived from original testcase which is attached above in this github thread. More details about the minimal testcases can be found here - https://reviews.llvm.org/D130466#3821839

PING.

**Comment by shubhamnarlawar77** [comment]
> PING.
> 
> Review request on https://reviews.llvm.org/D130466 for merging it.

PING.

Any thoughts on above? Can someone approve it?
