### ISSUE TITLE
Can no longer set custom section flags in LLVM IR

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#50551]
|  |  |
| --- | --- |
| Bugzilla Link | [51207](https://llvm.org/bz51207) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#50580  |
| CC | @MaskRay,@cuviper,@tstellar |
| Fixed by commit(s) | 1c198b3032e899003b5c1ffaa15c7648f24f1e69 |

## Extended Description 
After https://github.com/llvm/llvm-project/commit/82d0749749fafb0303414131dc570781376fdcfb this IR

module asm ".section .llvmbc,\22e\22"
@&#8203;rustc.embedded.module = private constant [3 x i8] c"ABC", section ".llvmbc"

when run through llc results in an "Unknown section kind" assertion failure.

rustc emits this IR here, which has a comment explaining why it does so: https://github.com/rust-lang/rust/blob/bddb59cf07efcf6e606f16b87f85e3ecd2c1ca69/compiler/rustc_codegen_llvm/src/back/write.rs#L970-L1017

I'm not sure where the bug is here -- what rustc is doing certainly looks fishy, but I'm not sure what it is supposed to be doing instead. Any advice?

**Comment by asl** [comment]
@tstellar Move to 13.0.1?

**Comment by nikic** [comment]
This issue has been addressed on the rust side (see https://github.com/rust-lang/rust/issues/90326), so closing this. Adding proper support for section flags in LLVM would still be nice, but it's no longer relevant as far as the release is concerned.
