### ISSUE TITLE
[RISCV] Improve gorc2 detection

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#50553]
|  |  |
| --- | --- |
| Bugzilla Link | [51209](https://llvm.org/bz51209) |
| Version | trunk |
| OS | Windows NT |
| CC | @asb,@topperc |

## Extended Description 
As encountered on D77804, the gorc2 matching (and the gorc2, gorc2 -> gorc2 combines) are incredibly brittle.

llvm/test/CodeGen/RISCV/rv32zbp.ll
llvm/test/CodeGen/RISCV/rv64zbp.ll

The gorc2, gorc2 -> gorc2 tests that D77804 breaks aren't likely to occur as InstCombine will already optimize the IR in a similar manner, preventing the match.

**Comment by asb** [comment]
Support for Zbp was removed as the extension seemed to fall off the path towards ratification. Marking as closed.
