### ISSUE TITLE
-O3 compile randomly ICE: Running pass 'CodeGen Prepare' on ubuntu aarch64 machine

### ISSUE THREAD

**Issue by yansendao** [llvm/llvm-project#50569]
|  |  |
| --- | --- |
| Bugzilla Link | [51225](https://llvm.org/bz51225) |
| Version | 12.0 |
| OS | Linux |
| Attachments | [creduce testcase file](https://user-images.githubusercontent.com/92601361/143762358-5cca7814-885c-4079-bf07-f28263cd5eb2.gz) |
| CC | @DougGregor,@zygoloid,@yansendao |

## Extended Description 

$ ~/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang++ -O3 test-creduce.cpp
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12 -cc1 -triple aarch64-unknown-linux-gnu -emit-obj --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test-creduce.cpp -mrelocation-model static -mframe-pointer=non-leaf -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu generic -target-feature +neon -target-abi aapcs -fallow-half-arguments-and-returns -fno-split-dwarf-inlining -debugger-tuning=gdb -resource-dir /home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/lib/clang/12.0.0 -internal-isystem /usr/lib64/gcc/aarch64-linux-gnu/7.5.0/../../../../include/c++/7.5.0 -internal-isystem /usr/lib64/gcc/aarch64-linux-gnu/7.5.0/../../../../include/aarch64-linux-gnu/c++/7.5.0 -internal-isystem /usr/lib64/gcc/aarch64-linux-gnu/7.5.0/../../../../include/aarch64-linux-gnu/c++/7.5.0 -internal-isystem /usr/lib64/gcc/aarch64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/backward -internal-isystem /usr/local/include -internal-isystem /home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/lib/clang/12.0.0/include -internal-externc-isystem /usr/include/aarch64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -fdeprecated-macro -fdebug-compilation-dir /home/yansendao/history/issue/boole-issue2475 -ferror-limit 19 -fno-signed-char -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -faddrsig -o /tmp/test-creduce-2cb6b8.o -x c++ test-creduce.cpp
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'test-creduce.cpp'.
4.      Running pass 'CodeGen Prepare' on function '@_Z1bbPA8_A4_A5_c'
 #&#8203;0 0x0000000002147364 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x2147364)
 #&#8203;1 0x0000000002145440 llvm::sys::RunSignalHandlers() (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x2145440)
 #&#8203;2 0x00000000021478b8 SignalHandler(int) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x21478b8)
 #&#8203;3 0x0000ffffbb92f688 (linux-vdso.so.1+0x688)
 #&#8203;4 0x00000000017f6f18 (anonymous namespace)::TypePromotionHelper::getAction(llvm::Instruction*, llvm::SmallPtrSet<llvm::Instruction*, 16u> const&, llvm::TargetLowering const&, llvm::DenseMap<llvm::Instruction*, llvm::PointerIntPair<llvm::Type*, 2u, (anonymous namespace)::ExtType, llvm::PointerLikeTypeTraits<llvm::Type*>, llvm::PointerIntPairInfo<llvm::Type*, 2u, llvm::PointerLikeTypeTraits<llvm::Type*> > >, llvm::DenseMapInfo<llvm::Instruction*>, llvm::detail::DenseMapPair<llvm::Instruction*, llvm::PointerIntPair<llvm::Type*, 2u, (anonymous namespace)::ExtType, llvm::PointerLikeTypeTraits<llvm::Type*>, llvm::PointerIntPairInfo<llvm::Type*, 2u, llvm::PointerLikeTypeTraits<llvm::Type*> > > > > const&) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x17f6f18)
 #&#8203;5 0x00000000017f68fc (anonymous namespace)::CodeGenPrepare::tryToPromoteExts((anonymous namespace)::TypePromotionTransaction&, llvm::SmallVectorImpl<llvm::Instruction*> const&, llvm::SmallVectorImpl<llvm::Instruction*>&, unsigned int) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x17f68fc)
 #&#8203;6 0x00000000017eb6f0 (anonymous namespace)::CodeGenPrepare::optimizeInst(llvm::Instruction*, bool&) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x17eb6f0)
 #&#8203;7 0x00000000017e3270 (anonymous namespace)::CodeGenPrepare::runOnFunction(llvm::Function&) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x17e3270)
 #&#8203;8 0x0000000001b877cc llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x1b877cc)
 #&#8203;9 0x0000000001b8ce2c llvm::FPPassManager::runOnModule(llvm::Module&) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x1b8ce2c)
#&#8203;10 0x0000000001b87cbc llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x1b87cbc)
#&#8203;11 0x00000000022f3238 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x22f3238)
#&#8203;12 0x0000000002c44648 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x2c44648)
#&#8203;13 0x00000000035d35e4 clang::ParseAST(clang::Sema&, bool, bool) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x35d35e4)
#&#8203;14 0x0000000002758508 clang::FrontendAction::Execute() (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x2758508)
#&#8203;15 0x00000000026f4c90 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x26f4c90)
#&#8203;16 0x00000000027e776c clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x27e776c)
#&#8203;17 0x00000000009d0d98 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x9d0d98)
#&#8203;18 0x00000000009cf704 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x9cf704)
#&#8203;19 0x00000000009cf23c main (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x9cf23c)
#&#8203;20 0x0000ffffbb432720 __libc_start_main /build/glibc-D9JkfM/glibc-2.27/csu/../csu/libc-start.c:344:0
#&#8203;21 0x00000000009cc758 _start (/home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin/clang-12+0x9cc758)
clang-12: error: unable to execute command: Segmentation fault (core dumped)
clang-12: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 12.0.0
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/yansendao/software/clang+llvm-12.0.0-aarch64-linux-gnu/bin
clang-12: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-12: note: diagnostic msg: /tmp/test-creduce-ab5ae7.cpp
clang-12: note: diagnostic msg: /tmp/test-creduce-ab5ae7.sh
clang-12: note: diagnostic msg:

**Comment by wheatman** [comment]
This seems to have been fixed between 12 and 13
https://godbolt.org/z/35j1TT3Wh

code
```
char a;
void b(bool c, char d[][8][4][5]) {
  for (int e = 0; e < 6014478850ULL; e += 80ULL)
    for (short f = 0; f < 4; f = 9)
      for (signed char g(0 < a); g < c + 4; g++)
        for (; d[0][e][f][g];)
          ;
}
int main() {}

```

old dump
```
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-12.0.0/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-10.3.0 -fcolor-diagnostics -fno-crash-diagnostics -O3 --target=aarch64-linux-gnu <source>
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '<source>'.
4.	Running pass 'CodeGen Prepare' on function '@_Z1bbPA8_A4_A5_c'
 #0 0x000055a3b629ebd1 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x318fbd1)
 #1 0x000055a3b629c994 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x318d994)
 #2 0x000055a3b629cc31 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x318dc31)
 #3 0x000055a3b6205748 CrashRecoverySignalHandler(int) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x30f6748)
 #4 0x00007fbb9b3c6420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #5 0x000055a3b553787f (anonymous namespace)::TypePromotionHelper::getAction(llvm::Instruction*, llvm::SmallPtrSet<llvm::Instruction*, 16u> const&, llvm::TargetLowering const&, llvm::DenseMap<llvm::Instruction*, llvm::PointerIntPair<llvm::Type*, 2u, (anonymous namespace)::ExtType, llvm::PointerLikeTypeTraits<llvm::Type*>, llvm::PointerIntPairInfo<llvm::Type*, 2u, llvm::PointerLikeTypeTraits<llvm::Type*> > >, llvm::DenseMapInfo<llvm::Instruction*>, llvm::detail::DenseMapPair<llvm::Instruction*, llvm::PointerIntPair<llvm::Type*, 2u, (anonymous namespace)::ExtType, llvm::PointerLikeTypeTraits<llvm::Type*>, llvm::PointerIntPairInfo<llvm::Type*, 2u, llvm::PointerLikeTypeTraits<llvm::Type*> > > > > const&) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x242887f)
 #6 0x000055a3b553dfad (anonymous namespace)::CodeGenPrepare::tryToPromoteExts((anonymous namespace)::TypePromotionTransaction&, llvm::SmallVectorImpl<llvm::Instruction*> const&, llvm::SmallVectorImpl<llvm::Instruction*>&, unsigned int) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x242efad)
 #7 0x000055a3b55656ad (anonymous namespace)::CodeGenPrepare::optimizeInst(llvm::Instruction*, bool&) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x24566ad)
 #8 0x000055a3b556727f (anonymous namespace)::CodeGenPrepare::runOnFunction(llvm::Function&) (.part.0) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x245827f)
 #9 0x000055a3b5a5bc00 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x294cc00)
#10 0x000055a3b5a5d239 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x294e239)
#11 0x000055a3b5a5ae50 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x294be50)
#12 0x000055a3b6582cb5 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x3473cb5)
#13 0x000055a3b7287949 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x4178949)
#14 0x000055a3b81d14f9 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x50c24f9)
#15 0x000055a3b7286626 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x4177626)
#16 0x000055a3b6be0ab1 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x3ad1ab1)
#17 0x000055a3b6b7debb clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x3a6eebb)
#18 0x000055a3b6cb2940 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x3ba3940)
#19 0x000055a3b40955f1 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0xf865f1)
#20 0x000055a3b4092bbb ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0xf83bbb)
#21 0x000055a3b6a24299 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::'lambda'()>(long) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x3915299)
#22 0x000055a3b6205847 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x30f6847)
#23 0x000055a3b6a24d96 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (.part.0) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x3915d96)
#24 0x000055a3b69f922c clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x38ea22c)
#25 0x000055a3b69f9c49 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x38eac49)
#26 0x000055a3b6a05381 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0x38f6381)
#27 0x000055a3b3fd541a main (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0xec641a)
#28 0x00007fbb9ae74083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#29 0x000055a3b409274e _start (/opt/compiler-explorer/clang-12.0.0/bin/clang+++0xf8374e)
clang-12: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Compiler returned: 139
```
