### ISSUE TITLE
BugPoint tests are failing when compiled with LTO

### ISSUE THREAD

**Issue by petrhosek** [llvm/llvm-project#50574]
|  |  |
| --- | --- |
| Bugzilla Link | [51230](https://llvm.org/bz51230) |
| Version | unspecified |
| OS | All |
| CC | @gkmhub,@MaskRay,@int3,@thevinster,@nico,@smeenai,@oontvoo |

## Extended Description 
I tried enabling the use of ld64.lld in our toolchain build that uses (regular) LTO but I see a number of BugPoint tests failure which all looks the same:

```
Error opening '/opt/s/w/ir/x/w/staging/llvm_build/tools/clang/stage2-bins/lib/BugpointPasses.dylib': dlopen(/opt/s/w/ir/x/w/staging/llvm_build/tools/clang/stage2-bins/lib/BugpointPasses.dylib, 9): Symbol not found: __ZNK4llvm4Pass11getPassNameEv
  Referenced from: /opt/s/w/ir/x/w/staging/llvm_build/tools/clang/stage2-bins/lib/BugpointPasses.dylib
  Expected in: flat namespace
 in /opt/s/w/ir/x/w/staging/llvm_build/tools/clang/stage2-bins/lib/BugpointPasses.dylib
  -load request ignored.
bugpoint: Unknown command line argument '-bugpoint-crashcalls'.  Try: '/opt/s/w/ir/x/w/staging/llvm_build/tools/clang/stage2-bins/bin/bugpoint --help'
bugpoint: Did you mean '--print-after-all'?
```

I suspect it's related to the use of -flat_namespace, see https://github.com/llvm/llvm-project/blob/e69a8c42135606e60446d5e78144357a9e429c77/llvm/cmake/modules/HandleLLVMOptions.cmake#L174, which should be supported under LTO according to https://github.com/llvm/llvm-project/blob/d7d2e4545e6b04ea29ffd05ebef2f7c26590b925/lld/MachO/LTO.cpp#L83 but perhaps it doesn't behave the same way as ld64?

**Comment by int3** [comment]
I have confirmed that https://reviews.llvm.org/D119372 fixes this.
