### ISSUE TITLE
clang segfaults compiling mozjs

### ISSUE THREAD

**Issue by kraj** [llvm/llvm-project#50578]
|  |  |
| --- | --- |
| Bugzilla Link | [51234](https://llvm.org/bz51234) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Attached testcase has failed to compile because clang segfaults. 

1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'Unified_cpp_js_src6-6831e2.cpp'.
4.      Running pass 'Loop Pass Manager' on function '@_ZN2js2gc9GCRuntime23beginSweepingSweepGroupEPNS_6FreeOpERNS_11SliceBudgetE'
5.      Running pass 'Loop Strength Reduction' on basic block '%1166'

**Comment by wheatman** [comment]
the link is dead so closing this as unreproducible
