### ISSUE TITLE
[DWARF] DW_AT_alignment incorrect when attribute((__aligned__)) is present but ignored

### ISSUE THREAD

**Issue by wolfy1961** [llvm/llvm-project#50621]
|  |  |
| --- | --- |
| Bugzilla Link | [51277](https://llvm.org/bz51277) |
| Version | trunk |
| OS | Windows NT |
| CC | @dwblaikie,@DougGregor,@pogo59,@zygoloid |

## Extended Description 
// Given the following source,

struct MyType { int m; } __attribute__((aligned(1)));
MyType mt;

when simply compiled with clang++ -c -g, produces a DW_TAG_structure_type DIE for MyType, with DW_AT_alignment having a value of 1.

However, the actual alignment of the type is 4, since, according to the gcc documentation, the alignment attribute, when used on structs, can only increase alignment, and not decrease it (unless attribute "packed" is also specified). clang does return the correct value from alignof(). See 
https://gcc.gnu.org/onlinedocs/gcc-11.2.0/gcc/Common-Type-Attributes.html#Common-Type-Attributes.

g++ generates a type DIE for MyType with DW_AT_alignment being 4.

**Comment by MaggieYingYi** [comment]
[D124006](https://reviews.llvm.org/D124006) has been accepted and committed into the main branch https://github.com/llvm/llvm-project/commit/b09ba42620768c0092b20cf526a30b14752a5dc9.
