### ISSUE TITLE
[InstCombine] Failure to narrow splatting shifts

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#50648]
|  |  |
| --- | --- |
| Bugzilla Link | [51306](https://llvm.org/bz51306) |
| Version | trunk |
| OS | Linux |
| CC | @RKSimon,@rotateright |

## Extended Description 
Extension of, llvm/llvm-project#50647 
https://alive2.llvm.org/ce/z/Ris5vE
we manage to push truncation through math, but not the shifty variant of the pattern.

**Comment by RKSimon** [comment]
Alive2: https://alive2.llvm.org/ce/z/JCa6C9
```ll
define i8 @src(i16 %x) {
  %i1 = shl i16 %x, 15
  %i2 = ashr i16 %i1, 15
  %i3 = trunc i16 %i2 to i8
  ret i8 %i3
}

define i8 @tgt(i16 %x) {
  %i1 = trunc i16 %x to i8
  %i2 = shl i8 %i1, 7
  %i3 = ashr i8 %i2, 7
  ret i8 %i3
}
```
Instcombine now fold both:
```ll
define i8 @src(i16 %x) {
  %1 = trunc i16 %x to i8
  %2 = and i8 %1, 1
  %i3 = sub nsw i8 0, %2
  ret i8 %i3
}

define i8 @tgt(i16 %x) {
  %1 = trunc i16 %x to i8
  %2 = and i8 %1, 1
  %i3 = sub nsw i8 0, %2
  ret i8 %i3
}
```
