### ISSUE TITLE
FAIL: Profile-x86_64 :: Linux/binary-id.c

### ISSUE THREAD

**Issue by 3b3be5bc-be97-4c5a-a058-de8ddaf7c081** [llvm/llvm-project#50672]
|  |  |
| --- | --- |
| Bugzilla Link | [51330](https://llvm.org/bz51330) |
| Version | 12.0 |
| OS | Linux |
| Blocks | llvm/llvm-project#51489  |
| CC | @tstellar |

## Extended Description 
Obtained on 13.0.0 release run.

clang+llvm-13.0.0-rc1-x86_64-linux-gnu-ubuntu-21.04

FAIL: Profile-x86_64 :: Linux/binary-id.c (82933 of 101468)
******************** TEST 'Profile-x86_64 :: Linux/binary-id.c' FAILED ********************
Script:
--
: 'RUN: at line 2';      /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/./bin/clang   -m64  -ldl  -fprofile-instr-generate -Wl,--build-id=none -O2 -o /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/compiler-rt/test/profile/Linux/binary-id.c
: 'RUN: at line 3';   env LLVM_PROFILE_FILE=/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw  /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp
: 'RUN: at line 4';   llvm-profdata show --binary-ids  /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw > /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.out
: 'RUN: at line 5';   FileCheck /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/compiler-rt/test/profile/Linux/binary-id.c --check-prefix=NO-BINARY-ID < /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.out
: 'RUN: at line 6';   llvm-profdata merge -o /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profdata /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw
: 'RUN: at line 8';      /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/./bin/clang   -m64  -ldl  -fprofile-instr-generate -Wl,--build-id -O2 -o /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/compiler-rt/test/profile/Linux/binary-id.c
: 'RUN: at line 9';   env LLVM_PROFILE_FILE=/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw  /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp
: 'RUN: at line 10';   llvm-profdata show --binary-ids  /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw > /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw.out
: 'RUN: at line 11';   FileCheck /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/compiler-rt/test/profile/Linux/binary-id.c --check-prefix=BINARY-ID-RAW-PROF < /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/Phase3/Release+Asserts/llvmCore-13.0.0-rc1.obj/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw.out
--
Exit Code: 1

Command Output (stderr):
--
/home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/compiler-rt/test/profile/Linux/binary-id.c:35:29: error: BINARY-ID-RAW-PROF-NEXT: expected string not found in input
// BINARY-ID-RAW-PROF-NEXT: Binary IDs:
                            ^
<stdin>:4:32: note: scanning from here
Maximum internal block count: 0
                               ^

Input file: <stdin>
Check file: /home/nnelson/Documents/llvm-project/llvm/utils/release/rc1/llvm-project/compiler-rt/test/profile/Linux/binary-id.c

-dump-input=help explains the following input dump.

Input was:
<<<<<<
         1: Instrumentation level: Front-end 
         2: Total functions: 3 
         3: Maximum function count: 1 
         4: Maximum internal block count: 0 
next:35                                    X error: no match found
>>>>>>

**Comment by tstellar** [comment]
The deadline for requesting fixes for the release has passed.  This bug is being removed from the LLVM 13.0.1 release milestone.  If you have a fix or think this bug is important enough to block the release, please explain why in a comment and add the bug back to the LLVM 13.0.1 release milestone.

**Comment by arsenm** [comment]
Old release
