### ISSUE TITLE
llvm::Optional doesn't work well with move-only types

### ISSUE THREAD

**Issue by tlemo** [llvm/llvm-project#50690]
|  |  |
| --- | --- |
| Bugzilla Link | [51348](https://llvm.org/bz51348) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie |

## Extended Description 
`llvm::Optional<T>` doesn't work well when T is a move-only type.

Repro: https://godbolt.org/z/adPEfaaEa

#include <llvm/ADT/Optional.h>

#include <vector>
#include <optional>

int main() {
    using X = std::unique_ptr<int>;

    using Y = llvm::Optional<X>; // fails to compile
    //using Y = std::optional<X>; // compiles fine

    std::vector<Y> z;
    z.push_back(std::make_unique<int>(42));
}

The problem seems to be traced to the following?

std::_Construct(std::__addressof(*__cur), *__first);

**Comment by arsenm** [comment]
llvm::Optional was replaced with std::optional
