### ISSUE TITLE
cannot build openmp project in debug config with Ninja on Windows

### ISSUE THREAD

**Issue by glevner** [llvm/llvm-project#50722]
|  |  |
| --- | --- |
| Bugzilla Link | [51380](https://llvm.org/bz51380) |
| Version | unspecified |
| OS | other |
| Attachments | [error messages](https://user-images.githubusercontent.com/92601594/143762399-998052a8-1a5c-4ef7-a45f-ab2c4a8b691d.gz) |
| CC | @Meinersbur |

## Extended Description 

Debug build of LLVM 11 fails on a Windows 7 machine with Visual Studio 2019 installed, using Ninja (or NMake).

Build commands:

set CXXFLAGS=/bigobj
cmake -G Ninja
    -D CMAKE_BUILD_TYPE=Debug 
    -D LLVM_ENABLE_PROJECTS=clang;openmp
    -D LLVM_TARGETS_TO_BUILD=X86
    -D LIBOMP_COPY_EXPORTS=OFF
    ..\llvm-project\llvm
ninja

Error messages: see attachment.

There is a workaround, however. In openmp/runtime/src/kmp_config.h.cmake, comment out the the line:

    # define KMP_DEBUG 1

before running cmake. The compilation errors are triggered by calls to KF_TRACE, which is an empty macro if KMP_DEBUG is not defined.

**Comment by arsenm** [comment]
Old build issue on old release
