### ISSUE TITLE
[llvm-profdata] nodeduplicate has been violated!

### ISSUE THREAD

**Issue by wolfy1961** [llvm/llvm-project#50736]
|  |  |
| --- | --- |
| Bugzilla Link | [51394](https://llvm.org/bz51394) |
| Version | trunk |
| OS | Windows NT |
| CC | @gregbedwell,@pogo59,@petrhosek |

## Extended Description 
After https://github.com/llvm/llvm-project/commit/c24b7a16b1001a8978335183d958fd0aa482c1d9 we get the error in the subject line with -flto -fprofile-instr-generate:

1.cpp:
__attribute__((weak)) void f(){};

2.cpp:
int main(){}

> clang -flto -fprofile-instr-generate -c 1.cpp -o 1.o
> clang -flto -fprofile-instr-generate -c 2.cpp -o 2.o
> llvm-link -o a.o 1.o 1.o 2.o

error: Linking COMDATs named '__profc__Z1fv': nodeduplicate has been violated!

This is a reduction from a large application (game) from one of our licensees.
Not using LTO works fine.

**Comment by Endilll** [comment]
Solution has landed.
