### ISSUE TITLE
Invalid modernize-use-equals-default on an uncompilable code

### ISSUE THREAD

**Issue by igor-akhmetov** [llvm/llvm-project#50740]
|  |  |
| --- | --- |
| Bugzilla Link | [51398](https://llvm.org/bz51398) |
| Version | unspecified |
| OS | Windows NT |

## Extended Description 
Running trunk clang-tidy on this snippet incorrectly triggers modernize-use-equals-default (https://gcc.godbolt.org/z/xrzdr3Tj6):

#include <xxx>
#define _XXX

template <class T>
struct X {
    X(const T*);
};

struct Base {
  Base(X<char> strName);
};

struct Derived : Base {
  Derived() : Base("Derived") {}
};

**Comment by PiotrZSL** [comment]
No reproduction on trunk, last yer there were lot of changes to this checks.
I would assume that this is already fixed.

**Comment by carlosgalvezp** [comment]
No longer reproducible on trunk.
