### ISSUE TITLE
support --fix-v4bx

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#50764]
|  |  |
| --- | --- |
| Bugzilla Link | [51422](https://llvm.org/bz51422) |
| Version | unspecified |
| OS | All |
| Blocks | llvm/llvm-project#4440  |
| CC | @arndb,@efriedma-quic,@MaskRay,@nathanchance,@smithp35 |

## Extended Description 
In order to link armv4 Linux kernel images with LLD, it's required that LLD support --fix-v4bx, otherwise we get the warning:

>> ld.lld: warning: lld uses blx instruction, no object with architecture supporting feature detected

IIUC, there's even a relocation type for this: R_ARM_V4BX.

https://github.com/ClangBuiltLinux/linux/issues/964

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/rG62c605771a30 looks perhaps related? cc @stuij

**Comment by stuij** [comment]
Ah, this is bad timing! I was unaware of this ticket.

Yes, so my patch stops lld inserting BLX instructions for v4(t), and instead now creates veneers that are sensible for these architectures. Currently I only added support for absolute relocations, but PIC relocations are high on the list and should follow shortly. I think it's just two cases that we should still account for, and adding them is trivial. Which includes v4 PIC thunks not generating a BX which right now they still do.

And as we don't insert BLX anymore, the LLD BLX warning is not emitted anymore.

Let me know if I'm missing more things that need fixing. ATM I'm quite motivated to get v4(t) working for LLVM, so happy to help out where I can on this.

**Comment by stuij** [comment]
I just put up a review for LLD that will make it support position independent thunks for v4/v4T:
https://reviews.llvm.org/D141272

I think that would fix this issue, and no more work would be needed on the LLVM side. To summarise:
- We now (after patch lands) support both v4 and v4t relocations in linker, for both absolute and position independent configs. 
- We won't need support for `--fix-v4bx` or `R_ARM_V4BX`, as no `BX` is generated on v4, either by compiler or linker.
- No special linker flag is needed for v4 as target architecture is inferred from build attributes.
- We don't generate a `BLX` warning anymore, so no need to guard against that.

Am I missing anything?

This would mean the https://github.com/intel-lab-lkp/linux/commit/6a7ee50f8f56dc181e1150cc101896053b02d220 patch can be reverted. Would we need to wait until say LLVM 16 is released (assuming this patch lands before that)?

By the way, relatedly, I just pushed a fix (https://github.com/llvm/llvm-project/commit/747fc27ee44d934bc25ecc7a62b0c87fc3af1fd0) for v4/v5/v6 where a `b.w` would be generated (not supported for these arches) if a range extension is needed and the distance between thunk section and target is smaller than b.w. So this would affect jumps spanning more than 32MB. Seeing the lack of a bug report, I guess this doesn't happen very often.

**Comment by linusw** [comment]
I just tested this with clang 17.0.6 on the Gemini FA526 target, close to ARMv4T.
It works like a charm:

sl-boot>go 0x400000
Booting Linux on physical CPU 0x0
Linux version 6.8.0-rc1+ (linus@lino) (clang version 17.0.6 (https://github.com/llvm/llvm-project 6009708b4367171ccdbf4b5905cb6a803753fe18), LLD 17.0.6) #49 PREEMPT Thu Feb  8 23:02:26 CET 2024
CPU: FA526 [66015261] revision 1 (ARMv4), cr=0000397f
CPU: VIVT data cache, VIVT instruction cache
OF: fdt: Machine model: D-Link DIR-685 Xtreme N Storage Router
(...)

It boots all the way to userspace, gets network, routes packets and has framebuffer.

**Comment by linusw** [comment]
Also tested with clang 17.0.6 on the SA1100 Netwinder, which is a pure ARMv4 targer.
It boots fine and works as expected:

Press '*' TWICE to enter debug......Booting kernel...
Uncompressing Linux... done, booting the kernel.
Booting Linux on physical CPU 0x0
Linux version 6.8.0-rc4-00034-g8d3dea210042 (linus@lino) (clang version 17.0.6 (https://github.com/llvm/llvm-project 6009708b4367171ccdbf4b5905cb6a803753fe18), LLD 17.0.6) #8 Th4
CPU: StrongARM-110 [4401a103] revision 3 (ARMv4), cr=0000517f
CPU: VIVT data cache, VIVT instruction cache
Machine: Rebel-NetWinder
(...)

All the way to userspace, network and graphics.

**Comment by stuij** [comment]
Yay! Tackar for posting this, and I bet I speak for all armv4(t) fans all over the world.

I Googled the Gemini SoC, and landed on a page you wrote. I'm tempted to buy a router, or perhaps one of those strongarm servers.
