### ISSUE TITLE
Namespace inline mismatch diagnostic refers to unhelpful previous definition

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#50794]
|  |  |
| --- | --- |
| Bugzilla Link | [51452](https://llvm.org/bz51452) |
| Version | trunk |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
See: https://godbolt.org/z/x87K78TnW

Take this C++ code:

1:  inline namespace abc {};
2:  namespace abc {};
3:  namespace abc {};

Clang will emit a warning for line 2, because the namespace is re-opened as non-inline, while the previous definition was inline. It will add a Note for the previous definition, in this case line 1.

However, it will also emit the same warning for line 3. In this case, it would be helpful to have the Note refer to the definition in line 1, but it instead refers to line 2. That is confusing since the problem is the inline mismatch, but the Note refers to a definition that is not inline.

**Comment by FabianWolff** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/528e6eba2f7906d974594b1fc50362dfad239609.
