### ISSUE TITLE
Segmentation fault in frontend while parsing spdlog

### ISSUE THREAD

**Issue by 72d99862-3d9e-4037-83f7-3da90e1ddc47** [llvm/llvm-project#50798]
|  |  |
| --- | --- |
| Bugzilla Link | [51456](https://llvm.org/bz51456) |
| Version | 12.0 |
| OS | MacOS X |
| Attachments | [Zip file containing preprocessed source, associated run script, and crash backtrace](https://user-images.githubusercontent.com/93435528/143762412-2d790898-e20e-4e1b-a319-8c3104f673d7.gz) |
| CC | @zygoloid |

## Extended Description 

Ran into this frontend crash when compiling the spdlog library on the current version of Apple Clang. The only workaround I have found so far is to downgrade from Xcode 12.5.1 to Xcode 12.4 (which comes with an earlier version of clang).

Building CXX object spdlog/spdlog/CMakeFiles/spdlog.dir/src/file_sinks.cpp.o
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Zip file containing preprocessed source, associated run script, and crash backtrace attached.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 12: https://godbolt.org/z/EsMEo3eqP
Reduced by C-Reduce:
```cpp
template class basic_format_string {
public:
  template <typename S, enable_if_t = 0>
  consteval basic_format_string(const S &s) : str_0
};

template <typename... Args>
using format_string = basic_format_string;

template <typename... T>
__attribute__() auto format(format_string<> fmt, T &&...args) -> int;

using filename_t = int;

filename_t calc_filename_basename;

template <typename Mutex> class rotating_file_sink final : public base_sink {
  static filename_t calc_filename();
};

template <typename Mutex>
filename_t rotating_file_sink<Mutex>::calc_filename() {
  return format(".", calc_filename_basename, calc_filename_index,
                calc_filename_ext);
}

template class rotating_file_sink<int>;
```
