### ISSUE TITLE
Clang should not warn "capture 'this' is not used" if it is used in another branch of if-constexpr.

### ISSUE THREAD

**Issue by zoecarver** [llvm/llvm-project#50807]
|  |  |
| --- | --- |
| Bugzilla Link | [51465](https://llvm.org/bz51465) |
| Version | trunk |
| OS | All |
| CC | @dwblaikie,@zygoloid |

## Extended Description 
The following will fail to compile, even though the member "p" is used in another branch of the if-constexpr: https://godbolt.org/z/hWbjbWYjq

**Comment by wheatman** [comment]
duplicate of https://github.com/llvm/llvm-project/issues/34798
