### ISSUE TITLE
New compile time regressions (12 vs 13) on znver3 (LoopMicroOpBufferSize too large?)

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#50802]
|  |  |
| --- | --- |
| Bugzilla Link | [51460](https://llvm.org/bz51460) |
| Version | trunk |
| OS | All |
| CC | @alinas,@LebedevRI,@preames,@RKSimon,@MattPD,@nikic,@rotateright,@tstellar |

## Extended Description 
Phoronix reported some significant CT regressions for mplayer and ffmpeg

https://www.phoronix.com/scan.php?page=article&item=clang13-initial-epyc&num=4

**Comment by RKSimon** [comment]
Closing this - the znver3/4 case was addressed by #91340 / 54e52aa5ebe68de122a3fe6064e0abef97f6b8e0

(The more general threshold limit at #67657 was reverted but should be re-committed at some point)
