### ISSUE TITLE
clang 12.0.1 segfaults while compiling for arm target

### ISSUE THREAD

**Issue by vadimcn** [llvm/llvm-project#50819]
|  |  |
| --- | --- |
| Bugzilla Link | [51477](https://llvm.org/bz51477) |
| Version | 12.0 |
| OS | Linux |
| Attachments | [Compiler invocation](https://user-images.githubusercontent.com/92601452/143762419-9c1af7fe-947b-4015-a0a7-388d21c512a3.gz) |
| CC | @zygoloid |

## Extended Description 
clang 12.0.1 segfaults while building LLVM (WebAssemblyISelLowering.cpp) for arm target.

Stack dump:
0.	Program arguments: /usr/local/bin/clang-12 -cc1 -triple armv6kz-unknown-linux-gnueabihf -emit-obj --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name WebAssemblyISelLowering.cpp -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -target-cpu arm1176jzf-s -target-feature +strict-align -target-abi aapcs-linux -mfloat-abi hard -fallow-half-arguments-and-returns -fno-split-dwarf-inlining -debugger-tuning=gdb -ffunction-sections -fdata-sections -sys-header-deps -D GTEST_HAS_RTTI=0 -D _FILE_OFFSET_BITS=64 -D _GNU_SOURCE -D _LARGEFILE_SOURCE -D __STDC_CONSTANT_MACROS -D __STDC_FORMAT_MACROS -D __STDC_LIMIT_MACROS -D NDEBUG -Os -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -pedantic -std=c++14 -fdeprecated-macro -ferror-limit 19 -fvisibility hidden -fvisibility-inlines-hidden -fno-rtti -fno-signed-char -fgnuc-version=4.2.1 -fcolor-diagnostics -vectorize-loops -vectorize-slp -faddrsig -x c++ WebAssemblyISelLowering-6ae354.cpp
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'WebAssemblyISelLowering-6ae354.cpp'.
4.	Running pass 'ARM Instruction Selection' on function '@_ZN4llvm25WebAssemblyTargetLoweringC2ERKNS_13TargetMachineERKNS_20WebAssemblySubtargetE'
 #&#8203;0 0x00000000024c18a3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/local/bin/clang-12+0x24c18a3)
 #&#8203;1 0x00000000024bf7ee llvm::sys::RunSignalHandlers() (/usr/local/bin/clang-12+0x24bf7ee)
 #&#8203;2 0x00000000024c1d4f SignalHandler(int) (/usr/local/bin/clang-12+0x24c1d4f)
 #&#8203;3 0x00007f422977e390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
 #&#8203;4 0x0000000002451b24 llvm::FoldingSetBase::RemoveNode(llvm::FoldingSetBase::Node*) (/usr/local/bin/clang-12+0x2451b24)
 #&#8203;5 0x000000000309b185 llvm::SelectionDAG::MorphNodeTo(llvm::SDNode*, unsigned int, llvm::SDVTList, llvm::ArrayRef<llvm::SDValue>) (/usr/local/bin/clang-12+0x309b185)
 #&#8203;6 0x00000000030b7845 llvm::SelectionDAGISel::MorphNode(llvm::SDNode*, unsigned int, llvm::SDVTList, llvm::ArrayRef<llvm::SDValue>, unsigned int) (/usr/local/bin/clang-12+0x30b7845)
 #&#8203;7 0x00000000030b8776 llvm::SelectionDAGISel::SelectCodeCommon(llvm::SDNode*, unsigned char const*, unsigned int) (/usr/local/bin/clang-12+0x30b8776)
 #&#8203;8 0x0000000000ed9cf3 (anonymous namespace)::ARMDAGToDAGISel::Select(llvm::SDNode*) (/usr/local/bin/clang-12+0xed9cf3)
 #&#8203;9 0x00000000030b38af llvm::SelectionDAGISel::DoInstructionSelection() (/usr/local/bin/clang-12+0x30b38af)
#&#8203;10 0x00000000030b2f00 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/usr/local/bin/clang-12+0x30b2f00)
#&#8203;11 0x00000000030b22aa llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/usr/local/bin/clang-12+0x30b22aa)
#&#8203;12 0x00000000030b00d2 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/usr/local/bin/clang-12+0x30b00d2)
#&#8203;13 0x0000000000eceb51 (anonymous namespace)::ARMDAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/usr/local/bin/clang-12+0xeceb51)
#&#8203;14 0x0000000001b1626e llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/usr/local/bin/clang-12+0x1b1626e)
#&#8203;15 0x0000000001e6ca1d llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/local/bin/clang-12+0x1e6ca1d)
#&#8203;16 0x0000000001e726f3 llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/local/bin/clang-12+0x1e726f3)
#&#8203;17 0x0000000001e6d08f llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/local/bin/clang-12+0x1e6d08f)
#&#8203;18 0x000000000269d436 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/usr/local/bin/clang-12+0x269d436)
#&#8203;19 0x000000000319415f clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/usr/local/bin/clang-12+0x319415f)
#&#8203;20 0x0000000003be7554 clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/bin/clang-12+0x3be7554)
#&#8203;21 0x0000000002bea627 clang::FrontendAction::Execute() (/usr/local/bin/clang-12+0x2bea627)
#&#8203;22 0x0000000002b75151 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/bin/clang-12+0x2b75151)
#&#8203;23 0x0000000002c7f38c clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/bin/clang-12+0x2c7f38c)
#&#8203;24 0x0000000000a06e72 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/bin/clang-12+0xa06e72)
#&#8203;25 0x0000000000a056b7 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/usr/local/bin/clang-12+0xa056b7)
#&#8203;26 0x0000000000a0544b main (/usr/local/bin/clang-12+0xa0544b)
#&#8203;27 0x00007f4228716840 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20840)
#&#8203;28 0x0000000000a023d9 _start (/usr/local/bin/clang-12+0xa023d9)
Segmentation fault (core dumped)

**Comment by Endilll** [comment]
@vadimcn Do you still experience this issue on trunk?
