### ISSUE TITLE
LICM incorrect load/store promotion in presence of poison

### ISSUE THREAD

**Issue by danilaml** [llvm/llvm-project#50813]
|  |  |
| --- | --- |
| Bugzilla Link | [51471](https://llvm.org/bz51471) |
| Version | trunk |
| OS | All |
| Attachments | [reproducer, run with opt -licm](https://user-images.githubusercontent.com/2046350/143762417-e44bdfa7-fb00-46a2-802f-e37ca1c59810.gz) |
| CC | @aqjune,@LebedevRI,@nikic,@nunoplopes,@DaniilSuchkov |

## Extended Description 

If there are two groups of memory accesses in the loop all to the same memory but one is done via "poisoned" pointer, basic-aa can just place them into two non-aliasing sets. LICM would then promote both of these groups leading to a miscompile: https://llvm.godbolt.org/z/KKxdb5e9v
The load/store with a poison pointer is a dead code and would never execute at runtime.
Similar IR was produced on an actual example after value propagation through a switch case.

**Comment by nikic** [comment]
The non-MSSA implementation has been dropped in the meantime, so I think this is effectively fixed.

**Comment by danilaml** [comment]
This was fixed in LICM, although the underlying issue still possibly exists in other passes.
