### ISSUE TITLE
ThinLTO Bitcode Writer crash

### ISSUE THREAD

**Issue by h0tc0d3** [llvm/llvm-project#50820]
|  |  |
| --- | --- |
| Bugzilla Link | [51478](https://llvm.org/bz51478) |
| Version | 12.0 |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
I think bug from glibc 2.34. 
Similar bug llvm/llvm-project#50819 

llvm configuration https://github.com/h0tc0d3/arch-packages/tree/master/llvm
glibc configuration https://github.com/h0tc0d3/arch-packages/tree/master/glibc

PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang++ -MMD -MF obj/chrome/browser/ui/ui/tab_strip_region_view.o.d -DUSE_DBUS -DUSE_DBUS_MENU -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DUSE_X11=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-13-init-10392-gd3676d4b-2\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DUSE_CUPS -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DGL_GLEXT_PROTOTYPES -DUSE_GLX -DUSE_EGL -DVK_USE_PLATFORM_XCB_KHR -D_WTL_NO_AUTOMATIC_NAMESPACE -DON_FOCUS_PING_ENABLED -DTOOLKIT_VIEWS=1 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_HAS_WUFFS_LIBRARY -DSK_VULKAN_HEADER=\"../../skia/config/SkVulkanConfig.h\" -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DVK_USE_PLATFORM_XCB_KHR -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -DU_IMPORT=U_EXPORT -DWEBRTC_ENABLE_AVX2 -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DWEBRTC_USE_BUILTIN_ISAC_FIX=0 -DWEBRTC_USE_BUILTIN_ISAC_FLOAT=1 -DWEBRTC_USE_X11 -DWEBRTC_HAVE_SCTP -DNO_MAIN_THREAD_WRAPPING -DLEVELDB_PLATFORM_CHROMIUM=1 -DLEVELDB_PLATFORM_CHROMIUM=1 -DCRASHPAD_ZLIB_SOURCE_EXTERNAL -DUSE_SYSTEM_ZLIB=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DATK_LIB_DIR=\"/usr/lib\" -DUSE_ATK_BRIDGE -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_SHARED_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_DEPRECATION_WARNINGS -DCPPGC_CAGED_HEAP -DI18N_ADDRESS_VALIDATION_DATA_URL=\"https://chromium-i18n.appspot.com/ssl-aggregate-address/\" -DFLATBUFFERS_LOCALE_INDEPENDENT=0 -DVK_NO_PROTOTYPES -DUSE_VULKAN_XCB -I../.. -Igen -Igen/shim_headers/zlib_shim -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -Igen/shim_headers/re2_shim -Igen/shim_headers/snappy_shim -I../../third_party/libyuv/include -I../../third_party/jsoncpp/source/include -Igen/shim_headers/opus_shim -Igen/shim_headers/ffmpeg_shim -Igen/shim_headers/libpng_shim -Igen/shim_headers/libwebp_shim -I../../third_party/vulkan-deps/vulkan-headers/src/include -I../../third_party/khronos -I../../gpu -Igen/third_party/dawn/src/include -I../../third_party/dawn/src/include -I../../third_party/wtl/include -Igen/shim_headers/minizip_shim -Igen/shim_headers/flac_shim -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -Igen/net/third_party/quiche/src -I../../net/third_party/quiche/overrides -I../../net/third_party/quiche/src/common/platform/default -I../../net/third_party/quiche/src -Igen -Igen/third_party/metrics_proto -I../../third_party/skia -I../../third_party/wuffs/src/release/c -I../../third_party/vulkan/include -I../../third_party/vulkan-deps/vulkan-headers/src/include -I../../third_party/ced/src -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../third_party/mesa_headers -I../../third_party/crashpad/crashpad -I../../third_party/crashpad/crashpad/compat/linux -I../../third_party/crashpad/crashpad/compat/non_win -I../../third_party/libwebm/source -I../../v8/include -Igen/v8/include -Igen -Igen/components/policy/proto -Igen/third_party/private_membership/src -Igen/third_party/shell-encryption/src -Igen/components/policy/proto -Igen -Igen -Igen -Igen -Igen -Igen -I../../third_party/libaddressinput/src/cpp/include -I../../third_party/tflite/src -Igen/third_party/tflite/src -I../../third_party/flatbuffers/src/include -I../../third_party/tflite-support/src -I../../third_party/tflite-support/src/tensorflow_lite_support -Igen/third_party/tflite-support/src -Igen -Igen -I../../third_party/brotli/include -Igen -Igen -Igen -Igen -Igen -Igen -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -flto=thin -fsplit-lto-unit -fwhole-program-vtables -m64 -march=znver2 -msse3 -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-max-tokens -O2 -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g2 -Xclang -debug-info-kind=constructor -ggnu-pubnames -ftrivial-auto-var-init=pattern -fprofile-instr-use=../../chrome/build/pgo_profiles/chrome-linux-4515-1627572323-7b80f2d12f40afe6f7872c5528a069e31662276b.profdata -Wno-profile-instr-unprofiled -Wno-profile-instr-out-of-date -Wno-backend-plugin -fsanitize=cfi-vcall -fsanitize-blacklist=../../tools/cfi/ignores.txt -fsanitize=cfi-icall -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -DPROTOBUF_ALLOW_DEPRECATED=1 -Wno-shorten-64-to-32 -Wno-header-guard -I/usr/include/nss -I/usr/include/nspr -I/usr/include/atk-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -Wno-deprecated-declarations -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -fdiagnostics-color=always -pipe -O2 -march=znver2 -fstack-protector-strong --param ssp-buffer-size=4 -fstack-clash-protection -Wno-builtin-macro-redefined -Wno-unknown-warning-option -c ../../chrome/browser/ui/views/frame/tab_strip_region_view.cc -o obj/chrome/browser/ui/ui/tab_strip_region_view.o
1.      <eof> parser at end of file
2.      Per-module optimization passes
3.      Running pass 'ThinLTO Bitcode Writer' on module '../../chrome/browser/ui/views/frame/tab_strip_region_view.cc'.
 #&#8203;0 0x00007fda12855181 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/bin/../lib/libLLVM-12.so+0x29c6181)
 #&#8203;1 0x00007fda12852ec0 llvm::sys::RunSignalHandlers() (/usr/bin/../lib/libLLVM-12.so+0x29c3ec0)
 #&#8203;2 0x00007fda1285454b llvm::sys::CleanupOnSignal(unsigned long) (/usr/bin/../lib/libLLVM-12.so+0x29c554b)
 #&#8203;3 0x00007fda1279a76f (/usr/bin/../lib/libLLVM-12.so+0x290b76f)
 #&#8203;4 0x00007fda0fabd000 __restore_rt (/usr/bin/../lib/libc.so.6+0x42000)
 #&#8203;5 0x00007fda131895f5 (/usr/bin/../lib/libLLVM-12.so+0x32fa5f5)
 #&#8203;6 0x00007fda13172060 (/usr/bin/../lib/libLLVM-12.so+0x32e3060)
 #&#8203;7 0x00007fda1316f2a2 llvm::BitcodeWriter::writeModule(llvm::Module const&, bool, llvm::ModuleSummaryIndex const*, bool, std::array<unsigned int, 5ul>*) (/usr/bin/../lib/libLLVM-12.so+0x32e02a2)
 #&#8203;8 0x00007fda137c7132 (/usr/bin/../lib/libLLVM-12.so+0x3938132)
 #&#8203;9 0x00007fda137c7e9f (/usr/bin/../lib/libLLVM-12.so+0x3938e9f)
#&#8203;10 0x00007fda12987d97 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/bin/../lib/libLLVM-12.so+0x2af8d97)
#&#8203;11 0x00007fda173b1848 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/usr/bin/../lib/libclang-cpp.so.12+0x1b72848)
#&#8203;12 0x00007fda1766560e (/usr/bin/../lib/libclang-cpp.so.12+0x1e2660e)
#&#8203;13 0x00007fda166e5564 clang::ParseAST(clang::Sema&, bool, bool) (/usr/bin/../lib/libclang-cpp.so.12+0xea6564)
#&#8203;14 0x00007fda17661ffe clang::CodeGenAction::ExecuteAction() (/usr/bin/../lib/libclang-cpp.so.12+0x1e22ffe)
#&#8203;15 0x00007fda17e25705 clang::FrontendAction::Execute() (/usr/bin/../lib/libclang-cpp.so.12+0x25e6705)
#&#8203;16 0x00007fda17da2f91 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/bin/../lib/libclang-cpp.so.12+0x2563f91)
#&#8203;17 0x00007fda17e9004d clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/bin/../lib/libclang-cpp.so.12+0x265104d)
#&#8203;18 0x00005605dea37434 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang-12+0x13434)
#&#8203;19 0x00005605dea35713 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/usr/bin/clang-12+0x11713)
#&#8203;20 0x00007fda17a57cc2 (/usr/bin/../lib/libclang-cpp.so.12+0x2218cc2)
#&#8203;21 0x00007fda1279a52d llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/bin/../lib/libLLVM-12.so+0x290b52d)
#&#8203;22 0x00007fda17a574df clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/usr/bin/../lib/libclang-cpp.so.12+0x22184df)
#&#8203;23 0x00007fda17a21612 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/usr/bin/../lib/libclang-cpp.so.12+0x21e2612)
#&#8203;24 0x00007fda17a2189a clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/usr/bin/../lib/libclang-cpp.so.12+0x21e289a)
#&#8203;25 0x00007fda17a3c027 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/usr/bin/../lib/libclang-cpp.so.12+0x21fd027)
#&#8203;26 0x00005605dea35132 main (/usr/bin/clang-12+0x11132)
#&#8203;27 0x00007fda0faa831c __libc_start_call_main (/usr/bin/../lib/libc.so.6+0x2d31c)
#&#8203;28 0x00007fda0faa83c8 __libc_start_main_impl (/usr/bin/../lib/libc.so.6+0x2d3c8)
#&#8203;29 0x00005605dea32571 _start (/usr/bin/clang-12+0xe571)
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
clang version 12.0.1 (/srcdest/llvm-project fed41342a82f5a3a9201819a82bf7a48313e296b)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang++: note: diagnostic msg: 
********************
 
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: ../../tools/clang/crashreports/tab_strip_region_view-922460.cpp
clang++: note: diagnostic msg: ../../tools/clang/crashreports/tab_strip_region_view-922460.sh
clang++: note: diagnostic msg: 
 

Files https://drive.google.com/file/d/1NqKzsdVEvSKz7gr8kZpApIq1W3XyyAbd/view?usp=sharing

**Comment by MaskRay** [comment]
> Files https://drive.google.com/file/d/1NqKzsdVEvSKz7gr8kZpApIq1W3XyyAbd/view?usp=sharing

"Sorry, the file you have requested does not exist."

Possibly not an issue now. If this still reproduces, we need new reproduce:)
