### ISSUE TITLE
[Sparc] `__builtin_longjmp` wrongly reported as being available

### ISSUE THREAD

**Issue by 2e1c2d01-a631-41c2-93fe-8d40b95d8607** [llvm/llvm-project#50831]
|  |  |
| --- | --- |
| Bugzilla Link | [51489](https://llvm.org/bz51489) |
| Version | trunk |
| OS | Linux |
| Attachments | [Repro: minimal code using `__builtin_longjmp`](https://user-images.githubusercontent.com/95090385/143762421-8cdf2202-fc23-4710-bd9c-9ff69a973e73.gz), [hasSjLjLowering() should return false for Sparc](https://user-images.githubusercontent.com/95090385/143762422-689f8dda-632a-4926-a370-a8e8558a7e50.gz) |
| CC | @zygoloid |

## Extended Description 

$ cat builtin_longjmp.c

void *jmp_buf[5];

void foo(void)
{
  __builtin_longjmp(jmp_buf, 1);
}

$ /usr/lib/llvm/12/bin/clang --target=sparc64-sun-solaris builtin_longjmp.c -c -o builtin_longjmp.o

$ llvm-objdump -d builtin_longjmp.o

builtin_longjmp.o:      file format elf64-sparc

Disassembly of section .text:

0000000000000000 <foo>:
       0: 9d e3 bf 80   save %sp, -128, %sp

$

**Comment by brad0** [comment]
Fixed wih eeb4266f8137c232f0f218a727dd12b5d4f52adc.
