### ISSUE TITLE
[concepts] [ice] substitution into constraint expression resulted in a non-constant expression

### ISSUE THREAD

**Issue by marehr** [llvm/llvm-project#50845]
|  |  |
| --- | --- |
| Bugzilla Link | [51503](https://llvm.org/bz51503) |
| Version | trunk |
| OS | Linux |
| CC | @AaronBallman,@JohelEGP,@zygoloid |

## Extended Description 
Hi clang-team,

the following code does not compile with clang trunk:

```c++
template <typename urng_t>
struct contiguous_range
{
    template <bool const_range>
        requires (const_range == false)
    using basic_iterator = int;

    auto begin()
    {
        return basic_iterator<false>{};
    }
};
```

https://godbolt.org/z/jobYveoe3

with the error

```
<source>:5:19: error: substitution into constraint expression resulted in a non-constant expression
        requires (const_range == false)
                  ^~~~~~~~~~~~~~~~~~~~
<source>:10:16: note: while checking constraint satisfaction for template 'basic_iterator<false>' required here
        return basic_iterator<false>{};
               ^~~~~~~~~~~~~~~~~~~~~
<source>:5:19: note: subexpression not valid in a constant expression
        requires (const_range == false)
                  ^
```

MSVC 16.11, and gcc 11.2 are able to compile this code. A curious side note: If you remove `template <typename urng_t>` clang does compile this code snippet.

**Comment by usx95** [comment]
Works as intended at trunk.
https://godbolt.org/z/K67bbMz3q
