### ISSUE TITLE
'*this' captured by copy does not preserve constness of '*this' in mutable lambda

### ISSUE THREAD

**Issue by 049b648d-2acd-4c6a-a3e9-25ddafb13875** [llvm/llvm-project#50866]
|  |  |
| --- | --- |
| Bugzilla Link | [51524](https://llvm.org/bz51524) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie,@zygoloid |

## Extended Description 
The following program:

```cpp
#include <type_traits>

struct S;

void f(S *) = delete;  // #&#8203;1
void f(const S *){};   // #&#8203;2

struct S {
  void g() const {
    [*this]() mutable { f(this); }();
  }
};

int main() {
  S s{};
  s.g();
}
```

is well-formed. As per [expr.prim.lambda.closure]/12 [1]

> [...] but for purposes of name lookup, **determining the type**
> and value **of this** [...] the compound-statement is considered
> in the context of the lambda-expression. 

and [class.this]/1 [2]

> In the body of a non-static ([class.mfct]) member function, the 
> keyword this is a prvalue whose value is a pointer to the object
> for which the function is called. **The type of this** in a member 
> function whose type has a cv-qualifier-seq cv and whose class is 
> X is “pointer to cv X”.

the type of 'this' in a lambda defined in a const-qualified member function, even when referred to from in the compound-statement of a lambda, is a const-qualified type. This also holds even if the lambda is mutable and the '*this' object is captured by copy. Thus, the 'f(this)' call in the program above should resolve to overload #&#8203;2, not overload #&#8203;1.

However, Clang (for various versions and for {std=c++17, -std=c++2a}) rejects the program as 'this' when referred to from within the lambda's compound-statement is considered to be of non-const type, thus picking the deleted overload #&#8203;1. GCC and MSVC (various versions) both accept the program, picking overload #&#8203;2.

The relevant wording (afaict) is aligned e.g. with CWG 756 [3] but for a copy-capture of the '*this' object (CWG 756 covers intentionally preserving constness for variables captured by value, even in mutable lambdas).

[1] https://timsong-cpp.github.io/cppwp/n4861/expr.prim.lambda.closure#12
[2] https://timsong-cpp.github.io/cppwp/n4861/class.this#1
[3] http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#756

**Comment by royjacobson** [comment]
We're explicitly stripping the CV qualifiers from a value captured `this` in `Sema::CheckCXXThisCapture`:

https://github.com/llvm/llvm-project/blob/890e6c871d31dca9e461c01118cf25fb303b9cad/clang/lib/Sema/SemaExprCXX.cpp#L1372

This code has been introduced in https://github.com/llvm/llvm-project/commit/67b04465c00e0be4fe0b6b30f27f3112d5ee875f

**Comment by shafik** [comment]
This was a while ago, I am guessing a lot of wording has changed since then. CC @cor3ntin 

I think the obvious fix is quick to try and run `check-clang`, the work is making sure we have sufficient test coverage. 

@Fznamznon recently looked at this area of the standard and might be able to identify some areas we are lacking coverage in.

**Comment by cor3ntin** [comment]
Interestingly, none of the major implementation are consistent https://godbolt.org/z/WYn7YEnG1
https://eel.is/c++draft/expr.prim.lambda.closure#13 is the current relevant wording. 

By that wording, i think GCC is right and clang is not, and that issue does need fixing. I think.
My understanding is that if the lambda is _not_ mutable, the constness should be preserved, and we no not seem to do that for `this`

**Comment by royjacobson** [comment]
https://eel.is/c++draft/expr.prim.lambda#capture-10.sentence-4 sounds pretty convincing to me, and GCC agrees.

This patch:
```diff
diff --git a/clang/lib/Sema/SemaExprCXX.cpp b/clang/lib/Sema/SemaExprCXX.cpp
index e7f3852ae34c..5510617046d4 100644
--- a/clang/lib/Sema/SemaExprCXX.cpp
+++ b/clang/lib/Sema/SemaExprCXX.cpp
@@ -1135,7 +1135,6 @@ static QualType adjustCVQualifiersForCXXThisWithinLambda(
     auto C = CurLSI->getCXXThisCapture();
 
     if (C.isCopyCapture()) {
-      ClassType.removeLocalCVRQualifiers(Qualifiers::CVRMask);
       if (!CurLSI->Mutable)
         ClassType.addConst();
       return ASTCtx.getPointerType(ClassType);
@@ -1175,7 +1174,6 @@ static QualType adjustCVQualifiersForCXXThisWithinLambda(
     while (Closure &&
            IsThisCaptured(Closure, IsByCopyCapture, IsConstCapture)) {
       if (IsByCopyCapture) {
-        ClassType.removeLocalCVRQualifiers(Qualifiers::CVRMask);
         if (IsConstCapture)
           ClassType.addConst();
         return ASTCtx.getPointerType(ClassType);
@@ -1362,15 +1360,7 @@ bool Sema::CheckCXXThisCapture(SourceLocation Loc, const bool Explicit,
 
     // The type of the corresponding data member (not a 'this' pointer if 'by
     // copy').
-    QualType CaptureType = ThisTy;
-    if (ByCopy) {
-      // If we are capturing the object referred to by '*this' by copy, ignore
-      // any cv qualifiers inherited from the type of the member function for
-      // the type of the closure-type's corresponding data member and any use
-      // of 'this'.
-      CaptureType = ThisTy->getPointeeType();
-      CaptureType.removeLocalCVRQualifiers(Qualifiers::CVRMask);
-    }
+    QualType CaptureType = ByCopy ? ThisTy->getPointeeType() : ThisTy;
 
     bool isNested = NumCapturingClosures > 1;
     CSI->addThisCapture(isNested, Loc, CaptureType, ByCopy);
```

fixes the stripped const, and only the obvious (`SemaCXX/cxx1z-lambda-star-this.cpp`) test fails.

**Comment by royjacobson** [comment]
Let's agree that this is really a bug, then I'll send the patch :)

**Comment by cor3ntin** [comment]
I *think* i agree with that change
