### ISSUE TITLE
[clang][ParseEnum] Crashed: Enum with invalid use of incomplete type

### ISSUE THREAD

**Issue by Guo-Peilin** [llvm/llvm-project#50896]
|  |  |
| --- | --- |
| Bugzilla Link | [51554](https://llvm.org/bz51554) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid,@sam-mccall |

## Extended Description 
I have a test case where clang should give an error message rather than a crash.
The test command is `clang++ -O2 test.cpp`
The test case is as follows:
enum E { e = E() };

int main() {
  return 0;
}

The error message should be like the following:
test.cpp:1:14: error: invalid use of incomplete type 'E'
enum E { e = E() };
             ^~~
test.cpp:1:6: note: definition of 'E' is not complete until the closing '}'
enum E { e = E() };

However, the trunk get crashed with the assertion
The bug message:
```
./clang/include/clang/AST/Type.h:677: const clang::ExtQualsTypeCommonBase* clang::QualType::getCommonPtr() const: Assertion `!isNull() && "Cannot retrieve a NULL type pointer"' failed.
```

I did a simple analysis. 
In ParseDecl.cpp:
1. llvm-10: 
   AssignedVal.get(): NULL
   
2. llvm-12(Context.getLangOpts().RecoveryASTType: default false)(early-version):
   AssignedVal.get(): RecoveryExpr 0xaaaaba19df20 '<dependent type>' contains-errors lvalue
   
3. llvm-12(Context.getLangOpts().RecoveryASTType: default true) (latest-version, Finally crashed):
   AssignedVal.get()->dump(): RecoveryExpr 0xaaaabb4d9500 'enum E' contains-errors
   
In CheckEnumConstant(), EltTy(type: QualType, value: EnumType 0xaaaabb517dd0 'enum E') cannot use getIntWidth(), so crashed. But the code doesn't seem to be wrong around here.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 14: https://godbolt.org/z/jaE8bxTxq
