### ISSUE TITLE
Missed optimization for (X * odd number) & 1

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#50893]
|  |  |
| --- | --- |
| Bugzilla Link | [51551](https://llvm.org/bz51551) |
| Version | trunk |
| OS | Linux |
| CC | @RKSimon,@rotateright |

## Extended Description 
----------------------------------------
define i1 @&#8203;src(i32 %0, i32 %1) {
%2:
  %3 = and i32 %1, 1
  %4 = icmp ne i32 %3, 0
  assume i1 %4
  %5 = mul i32 %1, %0
  %6 = and i32 %5, 1
  %7 = icmp eq i32 %6, 0
  ret i1 %7
}
=>
define i1 @&#8203;tgt(i32 %0, i32 %1) {
%2:
  %3 = and i32 %0, 1
  %4 = icmp eq i32 %3, 0
  ret i1 %4
}
Transformation seems to be correct!

https://godbolt.org/z/eee8ETo4h

**Comment by RKSimon** [comment]
@rotateright Not sure how much crossover this has with https://reviews.llvm.org/D119060 which was for self-multiplies

**Comment by rotateright** [comment]
We can propagate undemanded high bits of the mul value to the undemanded bits of its operands (if we don't care about high bits in the result, then we don't care about the high bits in the operands). 

That is done in SDAG, but it's missing in IR for mul (it is also already done in IR for add/sub).

Note that we also have a proposal for a pattern match solution starting from icmp: https://reviews.llvm.org/D114272 @FabianWolff

**Comment by rotateright** [comment]
Proposal for another demanded bits enhancement:
https://reviews.llvm.org/D119369

**Comment by rotateright** [comment]
@davidbolvansky - the example in the description uses an 'assume'. Do you know if that was introduced as part of the reduction or if the motivating code really has an 'assume'?

**Comment by davidbolvansky** [comment]
No, assume was used just for proof.

**Comment by rotateright** [comment]
Thanks. The tests intended to provide coverage for this issue are fixed after a series of demanded bits improvements

This was the last one that I found:
995d400f3a3c

I filed #53687 to track another potential improvement for mul patterns in IR.
