### ISSUE TITLE
Variable not visible at Og

### ISSUE THREAD

**Issue by FiorellaArtuso** [llvm/llvm-project#50901]
|  |  |
| --- | --- |
| Bugzilla Link | [51559](https://llvm.org/bz51559) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie,@JDevlieghere,@jmorse,@walkerkd,@pogo59 |

## Extended Description 
Comment:
When stepping on line 4 the variable g_3012 is not visible.

Steps to reproduce bug:

root@e60e0a2bba1a:/home/stepping/output# clang -v
clang version 14.0.0 (https://github.com/llvm/llvm-project.git 957334382cd12ec07b46c0ddfdcc220731f6d80f)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

root@e60e0a2bba1a:/home/stepping/output# lldb -v
lldb version 14.0.0 (https://github.com/llvm/llvm-project.git revision 957334382cd12ec07b46c0ddfdcc220731f6d80f)
  clang revision 957334382cd12ec07b46c0ddfdcc220731f6d80f
  llvm revision 957334382cd12ec07b46c0ddfdcc220731f6d80f

root@e60e0a2bba1a:/home/stepping/output# cat a.c
int g_97 ;
       static short g_3012 ;
       void  func_30() {
         g_97 = g_3012;
       }
       int main()      {
             {
              func_30();
            }
           }

root@e60e0a2bba1a:/home/stepping/output# cat -n a.c
     1  int g_97 ;
     2         static short g_3012 ;
     3         void  func_30() {
     4           g_97 = g_3012;
     5         }
     6         int main()      {
     7               {
     8                func_30();
     9              }
    10             }

root@e60e0a2bba1a:/home/stepping/output# clang -g -Og a.c -o opt

root@e60e0a2bba1a:/home/stepping/output# lldb opt
(lldb) target create "opt"
Current executable set to '/home/stepping/output/opt' (x86_64).
(lldb) b main
Breakpoint 1: where = opt`main [inlined] func_30 at a.c:4:15, address = 0x0000000000400490
(lldb) r
Process 68731 launched: '/home/stepping/output/opt' (x86_64)
Process 68731 stopped
* thread #&#8203;1, name = 'opt', stop reason = breakpoint 1.1
    frame #&#8203;0: 0x0000000000400490 opt`main [inlined] func_30 at a.c:4:15
   1    int g_97 ;
   2           static short g_3012 ;
   3           void  func_30() {
-> 4             g_97 = g_3012;
   5           }
   6           int main()      {
   7                 {
(lldb) p g_3012
error: expression failed to parse:
error: <user expression 0>:1:1: use of undeclared identifier 'g_3012'
g_3012

**Comment by hashemthomas1** [comment]
I recently encountered a crash which was a result of the patch that closed this issue.

The crash happens in the function getExpressionForConstant that SCCP pass utilizes, when reaching the following code section that deals with floating point values.

````cpp
if (Ty.isFloatTy() || Ty.isDoubleTy()) {
    const APFloat &APF = cast<ConstantFP>(&C)->getValueAPF();
    return DIB.createConstantValueExpression(
        APF.bitcastToAPInt().getZExtValue());
  }
````

It specifically happens in the cast operation when the value of the float is undef.

A very simple OpenCL reproducer of the crash with x86 architecture: https://godbolt.org/z/sTqaW6MvE

**Comment by Endilll** [comment]
I mentioned the comment above in https://github.com/llvm/llvm-project/pull/66745

**Comment by fhahn** [comment]
Fixed the crash in b46638dc7. @CarlosAlbertoEnciso please could you check if there's more appropriate debug data for `undef`/`poison`. Also, the original code only checked for float and double FP types, but there are others, like `half`. Could you extend the test coverage to include those types as well?

**Comment by CarlosAlbertoEnciso** [comment]
@fhahn Thanks for fixing the crash. I just returned this week from PTO.

**Comment by CarlosAlbertoEnciso** [comment]
Uploaded a patch to extend the test coverage for `half`, `bfloat` and `undef`.
https://github.com/llvm/llvm-project/pull/77901
