### ISSUE TITLE
Enable math headers for OpenMP AMDGCN

### ISSUE THREAD

**Issue by pdhaliwal-amd** [llvm/llvm-project#50923]
|  |  |
| --- | --- |
| Bugzilla Link | [51581](https://llvm.org/bz51581) |
| Version | trunk |
| OS | All |

## Extended Description 
Hi,

These three patches are required for working libm on OpenMP AMDGPU target offloading. These were reverted multiple times because of some issues.

Patches to be cherry-picked,

 [1] https://github.com/llvm/llvm-project/commit/9830f902e4d087ecb1706912b730c046f20600ee
 [2] https://github.com/llvm/llvm-project/commit/713a5d12cde58a5dff90cc3e2d1e67c2a78fe52f
 [3] https://github.com/llvm/llvm-project/commit/f3eb5f900d2ae6c8e1c03d1b250415a7b7aa39b1

These have already been through CI and have been in main for sometime. I have confirmed that these apply cleanly to release/13.x branch. Apologies for being late, I had originally mistakenly commented on the release bug ticket.

Thanks,
Pushpinder

**Comment by arsenm** [comment]
Issue description didn't make it clear this was for the release.

Old release
