### ISSUE TITLE
ICE on valid code (Heisenbug): clang::DeclContext::removeDecl(clang::Decl*): Assertion `I && "decl not found in linked list"' failed.

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#50928]
|  |  |
| --- | --- |
| Bugzilla Link | [51586](https://llvm.org/bz51586) |
| Version | trunk |
| OS | All |
| CC | @zygoloid |

## Extended Description 
The bug is non-deterministic, and you might need to run the test multiple times to reproduce it.

$ clang-trunk -v
clang version 14.0.0 (https://github.com/llvm/llvm-project.git 2c6ffb4eb20a2598148fdcc819e62f856ccaa373)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$ cat mutant.c
#include <immintrin.h>
avx512f_test(struct S2 { enum { One = 1, Two }; }) {}

$ clang-trunk  mutant.c
mutant.c:2:21: warning: declaration of 'struct S2' will not be visible outside of this function [-Wvisibility]
avx512f_test(struct S2 { enum { One = 1, Two }; }) {}
                    ^
mutant.c:2:26: warning: declaration of 'enum S2::(unnamed at mutant.c:2:26)' will not be visible outside of this function [-Wvisibility]
avx512f_test(struct S2 { enum { One = 1, Two }; }) {}
                         ^
mutant.c:2:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
avx512f_test(struct S2 { enum { One = 1, Two }; }) {}
^
clang-14: /tmp/tmp.3UVJ8ItY1w-clang-builder/llvm-project/clang/lib/AST/DeclBase.cpp:1496: void clang::DeclContext::removeDecl(clang::Decl*): Assertion `I && "decl not found in linked list"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /scratch/software/clang-trunk/bin/clang-14 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -main-file-name mutant.c -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fcoverage-compilation-dir=/scratch/cnsun/workspace/perses-fuzzer/temp_testing_campaigns/default_finding_folder_c/crash_20210819_194308_0502/delta/perses_result -resource-dir /scratch/software/clang-trunk/lib/clang/14.0.0 -c-isystem . -c-isystem /usr/local/include/cmsith -internal-isystem /scratch/software/clang-trunk/lib/clang/14.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir=/scratch/cnsun/workspace/perses-fuzzer/temp_testing_campaigns/default_finding_folder_c/crash_20210819_194308_0502/delta/perses_result -ferror-limit 19 -fgnuc-version=4.2.1 -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/mutant-dbdd46.o -x c mutant.c
1.	mutant.c:2:52: current parser token '{'
 #&#8203;0 0x0000556132f71314 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #&#8203;1 0x0000556132f6ea2e SignalHandler(int) Signals.cpp:0:0
 #&#8203;2 0x00007f49cc00c3c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #&#8203;3 0x00007f49cbaab18b raise /build/glibc-ZN95T4/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #&#8203;4 0x00007f49cba8a859 abort /build/glibc-ZN95T4/glibc-2.31/stdlib/abort.c:81:7
 #&#8203;5 0x00007f49cba8a729 get_sysdep_segment_value /build/glibc-ZN95T4/glibc-2.31/intl/loadmsgcat.c:509:8
 #&#8203;6 0x00007f49cba8a729 _nl_load_domain /build/glibc-ZN95T4/glibc-2.31/intl/loadmsgcat.c:970:34
 #&#8203;7 0x00007f49cba9bf36 (/lib/x86_64-linux-gnu/libc.so.6+0x36f36)
 #&#8203;8 0x0000556136033432 clang::DeclContext::removeDecl(clang::Decl*) (/scratch/software/clang-trunk/bin/clang-14+0x6c7c432)
 #&#8203;9 0x00005561354d9665 clang::Sema::ActOnFunctionDeclarator(clang::Scope*, clang::Declarator&, clang::DeclContext*, clang::TypeSourceInfo*, clang::LookupResult&, llvm::MutableArrayRef<clang::TemplateParameterList*>, bool&) (/scratch/software/clang-trunk/bin/clang-14+0x6122665)
#&#8203;10 0x00005561354dd751 clang::Sema::HandleDeclarator(clang::Scope*, clang::Declarator&, llvm::MutableArrayRef<clang::TemplateParameterList*>) (/scratch/software/clang-trunk/bin/clang-14+0x6126751)
#&#8203;11 0x00005561354de357 clang::Sema::ActOnStartOfFunctionDef(clang::Scope*, clang::Declarator&, llvm::MutableArrayRef<clang::TemplateParameterList*>, clang::Sema::SkipBodyInfo*) (/scratch/software/clang-trunk/bin/clang-14+0x6127357)
#&#8203;12 0x000055613520482f clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/scratch/software/clang-trunk/bin/clang-14+0x5e4d82f)
#&#8203;13 0x0000556135231800 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/scratch/software/clang-trunk/bin/clang-14+0x5e7a800)
#&#8203;14 0x00005561351ff3f6 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/scratch/software/clang-trunk/bin/clang-14+0x5e483f6)
#&#8203;15 0x00005561351ff9e1 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#&#8203;16 0x0000556135206207 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/scratch/software/clang-trunk/bin/clang-14+0x5e4f207)
#&#8203;17 0x000055613520779e clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/scratch/software/clang-trunk/bin/clang-14+0x5e5079e)
#&#8203;18 0x00005561351f9f79 clang::ParseAST(clang::Sema&, bool, bool) (/scratch/software/clang-trunk/bin/clang-14+0x5e42f79)
#&#8203;19 0x000055613411a0a8 clang::CodeGenAction::ExecuteAction() (/scratch/software/clang-trunk/bin/clang-14+0x4d630a8)
#&#8203;20 0x00005561339ae899 clang::FrontendAction::Execute() (/scratch/software/clang-trunk/bin/clang-14+0x45f7899)
#&#8203;21 0x0000556133943fae clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/scratch/software/clang-trunk/bin/clang-14+0x458cfae)
#&#8203;22 0x0000556133a8d770 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/scratch/software/clang-trunk/bin/clang-14+0x46d6770)
#&#8203;23 0x0000556130783dad cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/scratch/software/clang-trunk/bin/clang-14+0x13ccdad)
#&#8203;24 0x00005561307800f8 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#&#8203;25 0x00005561306a7f59 main (/scratch/software/clang-trunk/bin/clang-14+0x12f0f59)
#&#8203;26 0x00007f49cba8c0b3 __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:342:3
#&#8203;27 0x000055613077fc6e _start (/scratch/software/clang-trunk/bin/clang-14+0x13c8c6e)
clang-14: error: unable to execute command: Aborted (core dumped)
clang-14: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 14.0.0 (https://github.com/llvm/llvm-project.git 2c6ffb4eb20a2598148fdcc819e62f856ccaa373)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
clang-14: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-14: note: diagnostic msg: /tmp/mutant-9cd720.c
clang-14: note: diagnostic msg: /tmp/mutant-9cd720.sh
clang-14: note: diagnostic msg:

********************

**Comment by Endilll** [comment]
Fixed in Clang 13.0.1 and Clang 14: https://godbolt.org/z/nK39zbd87
