### ISSUE TITLE
Failure to vectorize none-of 4xbyte

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#50933]
|  |  |
| --- | --- |
| Bugzilla Link | [51591](https://llvm.org/bz51591) |
| Version | trunk |
| OS | Linux |
| CC | @alexey-bataev,@anton-afanasyev,@RKSimon,@rotateright |

## Extended Description 
https://godbolt.org/z/4WcY9aW5r
https://alive2.llvm.org/ce/z/RgJ439

We need to either/or do a better job of canonicalizing this in instcombine,
or teach SLPVectorizer about this.

SLP: Analyzing blocks in _Z3fooPKh.
SLP:  bundle:   %cmp.i.i.i.i.i.i = icmp eq i8 %2, -1
SLP:  initialize schedule region to   %cmp.i.i.i.i.i.i = icmp eq i8 %2, -1
SLP:  extend schedule region end to   %cmp.i.i59.i.i.i.i = icmp eq i64 %3, 65280
SLP:  extend schedule region end to   %cmp.i.i60.i.i.i.i = icmp eq i64 %4, 16711680
SLP:  extend schedule region end to   %cmp.i.i61.i.i.i.i = icmp eq i64 %5, 4278190080
SLP: try schedule bundle [  %cmp.i.i.i.i.i.i = icmp eq i8 %2, -1;  %cmp.i.i59.i.i.i.i = icmp eq i64 %3, 65280;  %cmp.i.i60.i.i.i.i = icmp eq i64 %4, 16711680;  %cmp.i.i61.i.i.i.i = icmp eq i64 %5, 4278190080] in block entry
SLP:       update deps of [  %cmp.i.i.i.i.i.i = icmp eq i8 %2, -1;  %cmp.i.i59.i.i.i.i = icmp eq i64 %3, 65280;  %cmp.i.i60.i.i.i.i = icmp eq i64 %4, 16711680;  %cmp.i.i61.i.i.i.i = icmp eq i64 %5, 4278190080]
SLP:       update deps of /   %cmp.i.i59.i.i.i.i = icmp eq i64 %3, 65280
SLP:       update deps of /   %cmp.i.i60.i.i.i.i = icmp eq i64 %4, 16711680
SLP:       update deps of /   %cmp.i.i61.i.i.i.i = icmp eq i64 %5, 4278190080
SLP:       update deps of   %or.cond27 = select i1 %or.cond, i1 true, i1 %cmp.i.i60.i.i.i.i
SLP:     gets ready on update:   %or.cond27 = select i1 %or.cond, i1 true, i1 %cmp.i.i60.i.i.i.i
SLP:       update deps of   %or.cond = or i1 %cmp.i.i.i.i.i.i, %cmp.i.i59.i.i.i.i
SLP:   schedule   %or.cond27 = select i1 %or.cond, i1 true, i1 %cmp.i.i60.i.i.i.i
SLP:    gets ready (def):   %or.cond = or i1 %cmp.i.i.i.i.i.i, %cmp.i.i59.i.i.i.i
SLP:   schedule   %or.cond = or i1 %cmp.i.i.i.i.i.i, %cmp.i.i59.i.i.i.i
SLP:    gets ready (def): [  %cmp.i.i.i.i.i.i = icmp eq i8 %2, -1;  %cmp.i.i59.i.i.i.i = icmp eq i64 %3, 65280;  %cmp.i.i60.i.i.i.i = icmp eq i64 %4, 16711680;  %cmp.i.i61.i.i.i.i = icmp eq i64 %5, 4278190080]
SLP: We are able to schedule this bundle.
SLP:  cancel scheduling of [  %cmp.i.i.i.i.i.i = icmp eq i8 %2, -1;  %cmp.i.i59.i.i.i.i = icmp eq i64 %3, 65280;  %cmp.i.i60.i.i.i.i = icmp eq i64 %4, 16711680;  %cmp.i.i61.i.i.i.i = icmp eq i64 %5, 4278190080]
SLP: Gathering cmp with different predicate.
SLP: Check whether the tree with height 1 is fully vectorizable .
SLP: Trying to vectorize a list of length = 2.
SLP: Analyzing 2 operations 
SLP:  bundle:   %cmp.i.i.i.i.i.i = icmp eq i8 %2, -1
SLP:  initialize schedule region to   %cmp.i.i.i.i.i.i = icmp eq i8 %2, -1
SLP:  extend schedule region end to   %cmp.i.i59.i.i.i.i = icmp eq i64 %3, 65280
SLP: try schedule bundle [  %cmp.i.i.i.i.i.i = icmp eq i8 %2, -1;  %cmp.i.i59.i.i.i.i = icmp eq i64 %3, 65280] in block entry
SLP:       update deps of [  %cmp.i.i.i.i.i.i = icmp eq i8 %2, -1;  %cmp.i.i59.i.i.i.i = icmp eq i64 %3, 65280]
SLP:       update deps of /   %cmp.i.i59.i.i.i.i = icmp eq i64 %3, 65280
SLP:     gets ready on update:   %cmp.i.i.i.i.i.i = icmp eq i8 %2, -1
SLP: We are able to schedule this bundle.
SLP:  cancel scheduling of [  %cmp.i.i.i.i.i.i = icmp eq i8 %2, -1;  %cmp.i.i59.i.i.i.i = icmp eq i64 %3, 65280]
SLP: Gathering cmp with different predicate.
SLP: Check whether the tree with height 1 is fully vectorizable .

**Comment by LebedevRI** [comment]
cc @max-quazan

**Comment by alexey-bataev** [comment]
The result after SLP is 
define dso_local void @foo(unsigned char const*)(ptr nocapture noundef readonly %input) local_unnamed_addr #0 {
entry:
  %0 = load i64, ptr %input, align 1
  %1 = insertelement <4 x i64> poison, i64 %0, i64 0
  %2 = shufflevector <4 x i64> %1, <4 x i64> poison, <4 x i32> zeroinitializer
  %3 = and <4 x i64> %2, <i64 65280, i64 255, i64 16711680, i64 4278190080>
  %4 = icmp eq <4 x i64> %3, <i64 65280, i64 255, i64 16711680, i64 4278190080>
  %5 = bitcast <4 x i1> %4 to i4
  %.not = icmp eq i4 %5, 0
  br i1 %.not, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  tail call void @bar()()
  br label %if.end

if.end:                                           ; preds = %entry, %if.then
  tail call void @baz()()
  ret void
}

declare void @bar()() local_unnamed_addr #1

Looks like it is fixed
