### ISSUE TITLE
opt -passes='function-specialization' crashes with Assertion `I != ValueState.end() && "V not found in ValueState nor Paramstate map!"' failed.

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#50942]
|  |  |
| --- | --- |
| Bugzilla Link | [51600](https://llvm.org/bz51600) |
| Version | trunk |
| OS | Linux |
| Attachments | [bbi-59059.ll](https://user-images.githubusercontent.com/55733087/143762464-d426b891-ced6-45db-904c-b146420179f1.gz) |
| CC | @sjoerdmeijer |

## Extended Description 

llvm commit: ebf35370ff596

Reproduce with:
 opt -passes='function-specialization' -o - -S bbi-59059.ll

Result:
opt: ../lib/Transforms/Utils/SCCPSolver.cpp:423: const llvm::ValueLatticeElement &llvm::SCCPInstVisitor::getLatticeValueFor(llvm::Value *) const: Assertion `I != ValueState.end() && "V not found in ValueState nor Paramstate map!"' failed.

**Comment by fhahn** [comment]
Looks fixed on current `main` https://llvm.godbolt.org/z/9W6eKj9jK

As per comment history likely fixed by eba76056a364
