### ISSUE TITLE
opt -enable-new-pm=1 -loop-load-elim -indvars -loop-distribute -enable-loop-distribute crashes with Assertion `Ptr != End && "dereferencing end() iterator"' failed.

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#50940]
|  |  |
| --- | --- |
| Bugzilla Link | [51598](https://llvm.org/bz51598) |
| Version | trunk |
| OS | Linux |
| Attachments | [bbi-58974.ll reproducer](https://user-images.githubusercontent.com/55733087/143762463-231d9d4c-c2db-43b7-a840-0db1f351f352.gz) |
| CC | @aeubanks,@alinas,@bjope |

## Extended Description 

llvm commit ebf35370ff59

Reproduce with:
 opt -enable-new-pm=1 -loop-load-elim -indvars -loop-distribute -enable-loop-distribute -o /dev/null bbi-58974.ll

Result:
opt: ../include/llvm/ADT/DenseMap.h:1242: llvm::DenseMapIterator::pointer llvm::DenseMapIterator<llvm::PointerIntPair<llvm::Value *, 1, bool, llvm::PointerLikeTypeTraits<llvm::Value *>, llvm::PointerIntPairInfo<llvm::Value *, 1, llvm::PointerLikeTypeTraits<llvm::Value *> > >, std::vector<unsigned int, std::allocator<unsigned int> >, llvm::DenseMapInfo<llvm::PointerIntPair<llvm::Value *, 1, bool, llvm::PointerLikeTypeTraits<llvm::Value *>, llvm::PointerIntPairInfo<llvm::Value *, 1, llvm::PointerLikeTypeTraits<llvm::Value *> > > >, llvm::detail::DenseMapPair<llvm::PointerIntPair<llvm::Value *, 1, bool, llvm::PointerLikeTypeTraits<llvm::Value *>, llvm::PointerIntPairInfo<llvm::Value *, 1, llvm::PointerLikeTypeTraits<llvm::Value *> > >, std::vector<unsigned int, std::allocator<unsigned int> > >, true>::operator->() const [KeyT = llvm::PointerIntPair<llvm::Value *, 1, bool, llvm::PointerLikeTypeTraits<llvm::Value *>, llvm::PointerIntPairInfo<llvm::Value *, 1, llvm::PointerLikeTypeTraits<llvm::Value *> > >, ValueT = std::vector<unsigned int, std::allocator<unsigned int> >, KeyInfoT = llvm::DenseMapInfo<llvm::PointerIntPair<llvm::Value *, 1, bool, llvm::PointerLikeTypeTraits<llvm::Value *>, llvm::PointerIntPairInfo<llvm::Value *, 1, llvm::PointerLikeTypeTraits<llvm::Value *> > > >, Bucket = llvm::detail::DenseMapPair<llvm::PointerIntPair<llvm::Value *, 1, bool, llvm::PointerLikeTypeTraits<llvm::Value *>, llvm::PointerIntPairInfo<llvm::Value *, 1, llvm::PointerLikeTypeTraits<llvm::Value *> > >, std::vector<unsigned int, std::allocator<unsigned int> > >, IsConst = true]: Assertion `Ptr != End && "dereferencing end() iterator"' failed.

**Comment by fhahn** [comment]
Still crashing: https://llvm.godbolt.org/z/4bqhae9hd

**Comment by fhahn** [comment]
Proposed fix is to change LAA to a function analysis: https://reviews.llvm.org/D134606

**Comment by mikaelholmen** [comment]
Thanks!
