### ISSUE TITLE
SoftenFloatOp_FP_TO_SINT assertion

### ISSUE THREAD

**Issue by 1ba3d143-a64b-4671-82b2-0b31cfb91709** [llvm/llvm-project#5097]
|  |  |
| --- | --- |
| Bugzilla Link | [4725](https://llvm.org/bz4725) |
| Version | trunk |
| OS | All |
| Attachments | [Test case for Blackfin back-end](https://user-images.githubusercontent.com/92601353/143739686-5884d737-a031-4f92-a56f-047faa7c1d78.gz) |

## Extended Description 

The attached test case fails with

Assertion failed: (LC != RTLIB::UNKNOWN_LIBCALL && "Unsupported FP_TO_SINT!"), function SoftenFloatOp_FP_TO_SINT, file /Users/stoklund/llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp, line 693.

I believe this happens when using soft-float on any target with legal i8 or i16 types:

llc -march=x86 -soft-float
llc -march=x86-64 -soft-float
llc -march=pic16
llc -march=bfin
llc -march=msp430

**Comment by arsenm** [comment]
Seems to work fine now
