### ISSUE TITLE
Regression: clang-tidy ignores -Wno-unknown-cuda-version and -Xcuda-ptxas

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#50987]
|  |  |
| --- | --- |
| Bugzilla Link | [51645](https://llvm.org/bz51645) |
| Version | unspecified |
| OS | Linux |
| CC | @carlosgalvezp |

## Extended Description 
Hi,

We are switching from clang-tidy 12 to 13, and have been using it successfully to analyze our CUDA code.

However in version 13 clang-tidy ignores the following command-line argument:

clang-tidy foo.cu -- -Wno-unknown-cuda-version

error: Unknown CUDA version. version.txt: 10.2.311. Assuming the latest supported version 10.1 [clang-diagnostic-unknown-cuda-version,-warnings-as-errors]

It also fails to understand CUDA-specific flags, like -Xcuda-ptxas:

error: argument unused during compilation: '-Xcuda-ptxas -Werror' [clang-diagnostic-unused-command-line-argument,-warnings-as-errors]

clang compiler, on the other hand, works fine for both flags.

Why is that?

**Comment by jaeseok4104** [comment]
@carlosgalvezp  did you use clang-tidy in CMAKE for .cu file? i am trying to do this, but I couldn't find a solution.

**Comment by carlosgalvezp** [comment]
@jaeseok4104 Nope, regular command-line invocation, which I later use in Bazel. As said, it was easier to just get an updated Clang that supports newer CUDA.

**Comment by jaeseok4104** [comment]
how can i use clang-tidy and cmake about cuda?

**Comment by jaeseok4104** [comment]
I don't think I can find this topic through search.

**Comment by jaeseok4104** [comment]
Hi @carlosgalvezp :)

i have more question about check cuda file using clang-tidy.

i tried your solution, but i could have this error comment from clang-tidy.

`error: parameter 'input_image' is unused [misc-unused-parameters,-warnings-as-errors]
void ConvertRGBtoGray(const cv::Mat& input_image, cv::Mat& output_image)
                                     ^~~~~~~~~~~
                                      /*input_image*/
error: static member accessed through instance [readability-static-accessed-through-instance,-warnings-as-errors]
        const int x = threadIdx.x + blockIdx.x * blockDim.x + 3;
                                                 ^~~~~~~~~
                                                 __cuda_builtin_blockDim_t::

`


it seems like wrong error for cuda. how can i solve this problem?

if you have solution about this problem, let me know :)

**Comment by carlosgalvezp** [comment]
That was fixed [here](https://github.com/llvm/llvm-project/commit/b43a2aee4ee946d8897880e824f4b09fe4c46143), make sure to update your clang-tidy :)

**Comment by carlosgalvezp** [comment]
@EugeneZelenko why did you close the issue? It has not been fixed AFAIK. The thread did become a bit off-topic which I guess I'm partly responsible for :flushed:

**Comment by EugeneZelenko** [comment]
Sorry, if I interpreted your previous comment incorrectly.

**Comment by carlosgalvezp** [comment]
Actually I have tested this issue on a recent commit and the problem seems to be gone! Don't know if intentionally or by luck, but I'm happy and can close this issue :)
