### ISSUE TITLE
libsanitizer/asan/asan_errors.cpp:387:32: warning: Function 'ErrorGeneric' argument order different:

### ISSUE THREAD

**Issue by marxin** [llvm/llvm-project#50983]
|  |  |
| --- | --- |
| Bugzilla Link | [51641](https://llvm.org/bz51641) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
Move here from:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102085

libsanitizer/asan/asan_errors.cpp:387:32: warning: Function 'ErrorGeneric' argument order different: declaration 'tid, addr, pc_, bp_, sp_, is_write_, access_size_' definition 'tid, pc_, bp_, sp_, addr, is_write_, access_size_' [funcArgOrderDifferent]

Another small problem found by static analyser cppcheck.

**Comment by vitalybuka** [comment]
Fixed with 78f7a6fbe5bbe6c3e3e1552f265964b189c57c25
