### ISSUE TITLE
llvm-dwarfdump --statistics crashes on large binary

### ISSUE THREAD

**Issue by amykhuang** [llvm/llvm-project#50994]
|  |  |
| --- | --- |
| Bugzilla Link | [51652](https://llvm.org/bz51652) |
| Version | trunk |
| OS | All |
| CC | @dwblaikie,@djtodoro,@OCHyams |

## Extended Description 
When running llvm-dwarfdump --statistics on the chrome binary, it crashes with the error

Assertion failed: GlobalStats.ScopeBytesCovered <= GlobalStats.ScopeBytes, file ../llvm-project/llvm/tools/llvm-dwarfdump/Statistics.cpp, line 397

**Comment by oltolm** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/c450e47a8c2d7f73ddeb370725e163d418e215e7.
