### ISSUE TITLE
wrong code at -O1 and above with -fPIC on x86_64-linux-gnu

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#51025]
|  |  |
| --- | --- |
| Bugzilla Link | [51683](https://llvm.org/bz51683) |
| Version | trunk |
| OS | All |
| CC | @topperc,@RKSimon,@phoebewang,@rotateright |

## Extended Description 
[653] % clangtk -v
clang version 14.0.0 (https://github.com/llvm/llvm-project.git 705d00578128c6089fe05adb175a5306f46c695c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
[654] %
[654] % clangtk -O1 small.c; ./a.out
[655] %
[655] % clangtk -O1 -fPIC small.c
[656] % ./a.out
Segmentation fault
[657] %
[657] % cat small.c
int printf(const char *, ...);
int a = -2094967296, b = 6, h, i;
char c;
static const int d, *e[2] = {&d, &d};
int f;
unsigned g = 1;
int main() {
  int j, k = ~a;
 L:;
  unsigned m = (2 / ~c) / g;
  int o = c = m % b;
  if (g >= o && c) {
    printf("%d", f);
    for (; h; h++)
      printf("0");
    i = *e[j];
    goto L;
  }
  if (b < 6)
    j++;
  if (k <= 0)
    goto L;
  return 0;
}

**Comment by fhahn** [comment]
I cannot reproduce this on current `main`, so this has likely been fixed. Please re-open the issue if it still reproduces on your end.
