### ISSUE TITLE
Clang not emitting destructor call when assignment constructed with list

### ISSUE THREAD

**Issue by lxfind** [llvm/llvm-project#51037]
|  |  |
| --- | --- |
| Bugzilla Link | [51695](https://llvm.org/bz51695) |
| Version | trunk |
| OS | All |
| CC | @dwblaikie,@zygoloid |

## Extended Description 
In the following code: https://godbolt.org/z/TK7ersK1M

#include <string>
#include <utility>

void doSomething();

class FooClass {
 public:
  FooClass() noexcept : ptr_() {}

  FooClass(FooClass&& other) noexcept
      : ptr_(std::exchange(other.ptr_, {})) {}

  ~FooClass() {
    doSomething();
  }

  FooClass& operator=(FooClass other) noexcept {
    std::swap(ptr_, other.ptr_);
    return *this;
  }

 private:
  void *ptr_;
};

template <typename T>
class WrapperClass {
 public:
  void run() noexcept {
    wrapper_ = {};
  }

 private:
  FooClass wrapper_;
};

void foo(WrapperClass<std::string> &A) {
    A.run();
}

When compiled with either GCC (any std version) or Clang with C++14, the line "wrapper_ = {};" in WrapperClass::run() will always generate a destructor call in the end, which is expected.
However when compiled with Clang C++17, the destructor call is not generated, which seems wrong to me.

**Comment by wheatman** [comment]
This was fixed between 16 and 17
https://godbolt.org/z/1E9szWeaq
code
```
// compile with -std=c++17
struct t1 {
  t1() noexcept;

  ~t1();

  t1& operator=(t1 other) noexcept;
};

template <typename T>
void run(t1 &W) noexcept {
  W = {};
}

template void run<int>(t1&);
```
old assembly
```
void run<int>(t1&):                         # @void run<int>(t1&)
        push    rbp
        mov     rbp, rsp
        sub     rsp, 16
        mov     qword ptr [rbp - 8], rdi
        lea     rdi, [rbp - 16]
        call    t1::t1()@PLT
        mov     rdi, qword ptr [rbp - 8]
        lea     rsi, [rbp - 16]
        call    t1::operator=(t1)@PLT
        add     rsp, 16
        pop     rbp
        ret
```

new assembly
```
void run<int>(t1&):                         # @void run<int>(t1&)
        push    rbp
        mov     rbp, rsp
        sub     rsp, 16
        mov     qword ptr [rbp - 8], rdi
        lea     rdi, [rbp - 9]
        call    t1::t1()@PLT
        mov     rdi, qword ptr [rbp - 8]
        lea     rsi, [rbp - 9]
        call    t1::operator=(t1)@PLT
        lea     rdi, [rbp - 9]
        call    t1::~t1()@PLT
        add     rsp, 16
        pop     rbp
        ret
```
