### ISSUE TITLE
LiveDebugValues pass incorrectly handles register spill for indirect debug values

### ISSUE THREAD

**Issue by kpdev** [llvm/llvm-project#51046]
|  |  |
| --- | --- |
| Bugzilla Link | [51704](https://llvm.org/bz51704) |
| Version | trunk |
| OS | All |
| Attachments | [Archive contains build script, source files and gdb commands for reproducing this bug](https://user-images.githubusercontent.com/3104234/143762496-d2a7005a-0208-4927-b2cd-b178b0bc4e29.gz) |
| CC | @dwblaikie,@JDevlieghere,@walkerkd,@pogo59 |

## Extended Description 

When handling register spill for indirect debug value LiveDebugValues pass doesn't add
DW_OP_deref operator which may in some cases cause debugger to return value address, instead
of value while machine register holding that address is spilled.

Attached file contains reproducer for this issue, which is actualy made from one of LLVM
integration tests (DebugInfo/MIR/X86/live-debug-values-restore.mir). To reproduce:

- compile the sample with build.sh script from the attached archive
- invoke gdb with command file: gdb -x gdb-commands.txt ldv-indir-test

You should see something like following in the output:

```
Breakpoint 2, 0x00000000002018df in j (t=274877906976) at test2.c:106
106     test2.c: No such file or directory.
1: x/3i $pc
=> 0x2018df <j+15>:     mov    %rdi,-0x8(%rsp)
   0x2018e4 <j+20>:     mov    -0x8(%rsp),%rdi
   0x2018e9 <j+25>:     pop    %rbx
(gdb) p/x t
$1 = 0x4000000020
(gdb) si
107     in test2.c
1: x/3i $pc
=> 0x2018e4 <j+20>:     mov    -0x8(%rsp),%rdi
   0x2018e9 <j+25>:     pop    %rbx
   0x2018ea <j+26>:     pop    %r12
(gdb) p/x t
$2 = 0x7fffffffd894
```

So the value of t ($1) changes to ($2) while t's address (%rdi) is spilled
to -0x8(%rsp).

If you look at DW_AT_location entries for `t` you can see why this happens:

```
DW_TAG_formal_parameter
  DW_AT_location        (0x00000181:
	 [0x00000000002018a3, 0x00000000002018b7): DW_OP_breg5 RDI+0
	 [0x00000000002018b7, 0x00000000002018bc): DW_OP_breg7 RSP-8
	 [0x00000000002018bc, 0x00000000002018ca): DW_OP_breg5 RDI+0)
  DW_AT_name    ("t")
```

The second location entry (RSP-8) is created without DW_OP_deref, so debugger
shows an address instead of value.

**Comment by OCHyams** [comment]
This works using clang 17.0.0 (and possibly earlier versions).

Using the reproducer (after renaming RETQ to RET in the .mir file) and commands in the report I can see we now get a `DW_OP_deref`.

`$ llvm-dwarfdump ldv-indir-test -name t`
```
ldv-indir-test:	file format elf64-x86-64

0x0000013a: DW_TAG_formal_parameter
              DW_AT_location	(0x00000181: 
                 [0x0000000000001952, 0x0000000000001966): DW_OP_breg5 RDI+0
                 [0x0000000000001966, 0x000000000000196b): DW_OP_breg7 RSP-8, DW_OP_deref
                 [0x000000000000196b, 0x0000000000001978): DW_OP_breg5 RDI+0)
              DW_AT_name	("t")
              DW_AT_decl_file	("test2.c")
              DW_AT_decl_line	(105)
              DW_AT_type	(0x00000156 "looong int")
```
And the expected value is now shown while stepping through the function in gdb.
```
Breakpoint 1, 0x0000555555555961 in j (t=274877906976) at test2.c:106
106	test2.c: No such file or directory.
(gdb) display /3i $pc
1: x/3i $pc
=> 0x555555555961 <j+15>:	mov    %rdi,-0x8(%rsp)
   0x555555555966 <j+20>:	mov    -0x8(%rsp),%rdi
   0x55555555596b <j+25>:	pop    %rbx
(gdb) p/x t
$1 = 0x4000000020
(gdb) si
107	in test2.c
1: x/3i $pc
=> 0x555555555966 <j+20>:	mov    -0x8(%rsp),%rdi
   0x55555555596b <j+25>:	pop    %rbx
   0x55555555596c <j+26>:	pop    %r12
(gdb) p/x t
$2 = 0x4000000020
```
