### ISSUE TITLE
Ability to customize indentation of designated initializers

### ISSUE THREAD

**Issue by vlovich** [llvm/llvm-project#51070]
|  |  |
| --- | --- |
| Bugzilla Link | [51728](https://llvm.org/bz51728) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
When a designated initializer needs to spilled onto a new line, it uses `ContinuationIndentWidth`. However in the KJ style guide (https://github.com/capnproto/capnproto/blob/master/kjdoc/style-guide.md), such a case should have `IndentWidth` applied.

Currently (undesirable):
IndentWidth: 2
ContinuationIndentWidth: 2

    return SomeStruct {
        .x = 5,
        .y = 6,
        .z = 7
    };

Desired:
IndentWidth: 2
ContinuationIndentWidth: 2

    return SomeStruct {
      .x = 5,
      .y = 6,
      .z = 7
    };

**Comment by mydeveloperday** [comment]
For clarity can you show us your .clang-format configuration or it will format as

`return SomeStruct{.x = 5, .y = 6, .z = 7};`
