### ISSUE TITLE
Suboptimal auto vectorized code with accumulator

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#51088]
|  |  |
| --- | --- |
| Bugzilla Link | [51746](https://llvm.org/bz51746) |
| Version | trunk |
| OS | Linux |
| CC | @alexey-bataev,@anton-afanasyev,@fhahn,@preames,@RKSimon,@rotateright,@dtemirbulatov |

## Extended Description
```
typedef int v4si __attribute__ ((vector_size (16)));
int
test1 (int acc, v4si v1, v4si v2, v4si v3, v4si v4)
{
  acc &= v1[0] & v1[1] & v1[2] & v1[3];
  acc &= v2[0] & v2[1] & v2[2] & v2[3];
  acc &= v3[0] & v3[1] & v3[2] & v3[3];
  acc &= v4[0] & v4[1] & v4[2] & v4[3];
  return acc;
}
```

GGC -O3:
```
test1(int, int __vector(4), int __vector(4), int __vector(4), int __vector(4)):
        pand    xmm0, xmm1
        pand    xmm2, xmm3
        pand    xmm2, xmm0
        pshufd  xmm0, xmm2, 85
        movd    edx, xmm2
        movd    eax, xmm0
        movdqa  xmm0, xmm2
        and     eax, edx
        punpckhdq       xmm0, xmm2
        pshufd  xmm2, xmm2, 255
        and     eax, edi
        movd    edx, xmm0
        and     edx, eax
        movd    eax, xmm2
        and     eax, edx
        ret
```

Clang -O3:
```
test1(int, int __vector(4), int __vector(4), int __vector(4), int __vector(4)):                   # @&#8203;test1(int, int __vector(4), int __vector(4), int __vector(4), int __vector(4))
        movd    eax, xmm1
        pshufd  xmm4, xmm1, 85                  # xmm4 = xmm1[1,1,1,1]
        movd    ecx, xmm4
        and     ecx, eax
        pshufd  xmm4, xmm1, 238                 # xmm4 = xmm1[2,3,2,3]
        movd    eax, xmm4
        and     eax, ecx
        pshufd  xmm1, xmm1, 255                 # xmm1 = xmm1[3,3,3,3]
        movd    ecx, xmm1
        movd    edx, xmm2
        pshufd  xmm1, xmm2, 85                  # xmm1 = xmm2[1,1,1,1]
        movd    esi, xmm1
        and     esi, ecx
        and     esi, edx
        pshufd  xmm1, xmm2, 238                 # xmm1 = xmm2[2,3,2,3]
        movd    ecx, xmm1
        and     ecx, esi
        pshufd  xmm1, xmm2, 255                 # xmm1 = xmm2[3,3,3,3]
        movd    edx, xmm1
        and     edx, ecx
        movd    ecx, xmm3
        pshufd  xmm1, xmm3, 85                  # xmm1 = xmm3[1,1,1,1]
        movd    esi, xmm1
        and     esi, ecx
        pshufd  xmm1, xmm3, 238                 # xmm1 = xmm3[2,3,2,3]
        movd    ecx, xmm1
        and     ecx, esi
        pshufd  xmm1, xmm3, 255                 # xmm1 = xmm3[3,3,3,3]
        movd    esi, xmm1
        and     esi, ecx
        pshufd  xmm1, xmm0, 238                 # xmm1 = xmm0[2,3,2,3]
        pand    xmm1, xmm0
        pshufd  xmm0, xmm1, 85                  # xmm0 = xmm1[1,1,1,1]
        pand    xmm0, xmm1
        movd    ecx, xmm0
        and     eax, edi
        and     eax, ecx
        and     eax, edx
        and     eax, esi
        ret
```

Codegen: https://godbolt.org/z/Y86fodv5j

**Comment by RKSimon** [comment]
SLP recognises some of the reduction (and we even concat 2 of the vectors together, although with an unnecessary permute) but it looks like the scalar accumulator still interferes.
```
define noundef i32 @PR51746(i32 noundef %0, <4 x i32> noundef %1, <4 x i32> noundef %2, <4 x i32> noundef %3, <4 x i32> noundef %4) {
  %6 = shufflevector <4 x i32> %1, <4 x i32> %2, <8 x i32> <i32 1, i32 0, i32 2, i32 3, i32 5, i32 4, i32 6, i32 7>
  %7 = extractelement <4 x i32> %4, i64 0
  %8 = extractelement <4 x i32> %4, i64 1
  %9 = extractelement <4 x i32> %4, i64 2
  %10 = extractelement <4 x i32> %4, i64 3
  %11 = call i32 @llvm.vector.reduce.and.v8i32(<8 x i32> %6)
  %12 = call i32 @llvm.vector.reduce.and.v4i32(<4 x i32> %3)
  %13 = and i32 %11, %12
  %14 = and i32 %13, %8
  %15 = and i32 %14, %7
  %16 = and i32 %15, %9
  %17 = and i32 %16, %0
  %18 = and i32 %17, %10
  ret i32 %18
}
declare i32 @llvm.vector.reduce.and.v8i32(<8 x i32>)
declare i32 @llvm.vector.reduce.and.v4i32(<4 x i32>)
```

**Comment by alexey-bataev** [comment]
define dso_local noundef i32 @test1(int, int __vector(4), int __vector(4), int __vector(4), int __vector(4))(i32 noundef %acc, <4 x i32> noundef %v1, <4 x i32> noundef %v2, <4 x i32> noundef %v3, <4 x i32> noundef %v4) local_unnamed_addr {
entry:
  %0 = shufflevector <4 x i32> %v2, <4 x i32> %v1, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %1 = shufflevector <4 x i32> %v4, <4 x i32> %v3, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %2 = tail call i32 @llvm.vector.reduce.and.v8i32(<8 x i32> %1)
  %3 = tail call i32 @llvm.vector.reduce.and.v8i32(<8 x i32> %0)
  %op.rdx = and i32 %2, %3
  %op.rdx47 = and i32 %op.rdx, %acc
  ret i32 %op.rdx47
}

define dso_local noundef i32 @test2(int, int __vector(4), int __vector(4), int __vector(4), int __vector(4))(i32 noundef %acc, <4 x i32> noundef %v1, <4 x i32> noundef %v2, <4 x i32> noundef %v3, <4 x i32> noundef %v4) local_unnamed_addr {
entry:
  %0 = shufflevector <4 x i32> %v2, <4 x i32> %v1, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %1 = shufflevector <4 x i32> %v4, <4 x i32> %v3, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %2 = tail call i32 @llvm.vector.reduce.and.v8i32(<8 x i32> %1)
  %3 = tail call i32 @llvm.vector.reduce.and.v8i32(<8 x i32> %0)
  %op.rdx = and i32 %2, %3
  %op.rdx54 = and i32 %op.rdx, %acc
  ret i32 %op.rdx54
}

declare void @llvm.dbg.value(metadata, metadata, metadata) #1

declare i32 @llvm.vector.reduce.and.v8i32(<8 x i32>) #1

Looks like it is fixed

**Comment by RKSimon** [comment]
Fixed between 14.x and 15.x https://godbolt.org/z/j1P6sWYq8
