### ISSUE TITLE
[AArch64] LLVM 13 regression: Crash in selectCopy when using x12-x15 as input for inline asm

### ISSUE THREAD

**Issue by Amanieu** [llvm/llvm-project#51114]
|  |  |
| --- | --- |
| Bugzilla Link | [51772](https://llvm.org/bz51772) |
| Version | trunk |
| OS | All |
| CC | @Arnaud-de-Grandmaison-ARM,@smithp35 |

## Extended Description 
Input IR:

define void @&#8203;foo() {
  call void asm sideeffect "", "{x15}"(i32 0)
  ret void
}

This crash only happens on -O0 and only if the register is x12, x13, x14 or x15. Works correctly in LLVM 12.

Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/llc -o /app/output.s -x86-asm-syntax=intel -mtriple=aarch64 -O0 <source>
1.	Running pass 'Function Pass Manager' on module '<source>'.
2.	Running pass 'InstructionSelect' on function '@foo'
 #&#8203;0 0x000055fc4b6d5c3f PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #&#8203;1 0x000055fc4b6d34ed SignalHandler(int) Signals.cpp:0:0
 #&#8203;2 0x00007f056708d3c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #&#8203;3 0x000055fc4976a6e3 selectCopy(llvm::MachineInstr&, llvm::TargetInstrInfo const&, llvm::MachineRegisterInfo&, llvm::TargetRegisterInfo const&, llvm::RegisterBankInfo const&) AArch64InstructionSelector.cpp:0:0
 #&#8203;4 0x000055fc49773c09 (anonymous namespace)::AArch64InstructionSelector::select(llvm::MachineInstr&) AArch64InstructionSelector.cpp:0:0
 #&#8203;5 0x000055fc4bcdde57 llvm::InstructionSelect::runOnMachineFunction(llvm::MachineFunction&) (.part.87) InstructionSelect.cpp:0:0
 #&#8203;6 0x000055fc4ab36da8 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x1f36da8)
 #&#8203;7 0x000055fc4af5dad9 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x235dad9)
 #&#8203;8 0x000055fc4af5dd71 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x235dd71)
 #&#8203;9 0x000055fc4af5efe7 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x235efe7)
#&#8203;10 0x000055fc494d71e1 compileModule(char**, llvm::LLVMContext&) llc.cpp:0:0
#&#8203;11 0x000055fc494034b6 main (/opt/compiler-explorer/clang-trunk/bin/llc+0x8034b6)
#&#8203;12 0x00007f0566b3d0b3 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b3)
#&#8203;13 0x000055fc494cef5a _start (/opt/compiler-explorer/clang-trunk/bin/llc+0x8cef5a)
Compiler returned: 139

**Comment by Amanieu** [comment]
This commit needs to be backported: 5dd9e019ddb4b3e1d9fe425ae8bfe5a01b3f66fa

**Comment by tstellar** [comment]
@TNorthover What do you think about backporting this?

**Comment by TNorthover** [comment]
Yep, can't really go far wrong here.

**Comment by tstellar** [comment]
Merged: 69fcfdedc505
