### ISSUE TITLE
llvm.aarch64.ldxr incompatible with opaque pointers

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#51165]
|  |  |
| --- | --- |
| Bugzilla Link | [51823](https://llvm.org/bz51823) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#46018  |
| CC | @Arnaud-de-Grandmaison-ARM,@DMG862,@efriedma-quic,@smithp35 |

## Extended Description 
The AArch64 ldxr/ldxar/stxr/stlxr family of intrinsics currently works like this:

call i64 @&#8203;llvm.aarch64.ldxr.p0i8(i8* %addr)

The return value is always i64, and the size of the loaded/stored value is determined by the pointer element type of the address.

To support opaque pointers, this could be changes in two ways. We could keep the current approach and require an elementtype attribute:

call i64 @&#8203;llvm.aarch64.ldxr.p0i8(i8* elementtype(i8) %addr)

Or we could change the definition of the intrinsic to return the loaded type, rather than i64:

call i8 @&#8203;llvm.aarch64.ldxr.i8.p0i8(i8* %addr)

The latter variant looks preferable to me. However, I think that needs some significant changes to how these are lowered/selected. I tried to work on this, but didn't get far (https://gist.github.com/nikic/9b6d48d89d4b6e735d4f100e18c9b08a).

**Comment by aeubanks** [comment]
Fixed just with elementtype (didn't bother with new isel nodes) in https://reviews.llvm.org/D120527
