### ISSUE TITLE
[zorg] stage-1 SVE builds use unsupported flags with system compiler

### ISSUE THREAD

**Issue by peterwaller-arm** [llvm/llvm-project#51178]
|  |  |
| --- | --- |
| Bugzilla Link | [51836](https://llvm.org/bz51836) |
| Version | unspecified |
| OS | All |
| CC | @DavidSpickett,@maxim-kuvyrkov,@peterwaller-arm,@zygoloid |

## Extended Description 
The builders clang-aarch64-sve-vla-2stage and clang-aarch64-sve-vls-2stage both use flags not understood by the stage1 compiler provided by the host which at the moment is clang-12.

https://github.com/llvm/llvm-zorg/commit/6fc25a74c84e064b375e320b918b62fed3a2bde0

At stage 1:

* The VLA bot silently ignores the -mllvm -scalable-vectorization=preferred flag passed to it.

* The VLS bot compiles with -msve-vector-bits=...

It seems to me it would be preferable to have a three-stage build, where the first stage uses relatively boring flags. If that's not possible, at least there needs to be a way to specify different flags between stage1 and stage2 which it seems isn't supported by zorg.

If at some point these builders are using clang-13, and it turns out there are latent SVE codegen bugs, then this builder could fail in surprising ways when stage1 executes and it won't be possible to fix it by submitting a patch to the main branch. We're effectively in that situation in clang-12, although happily I think the flags are being mostly ignored. The linked patch did change the behaviour of the stage-1 build however, where previously it was testing the vls codegen (because it understood -mllvm -aarch64-sve-vector-bits-min) but now it does not.

**Comment by Endilll** [comment]
Is this still an issue?

**Comment by peterwaller-arm** [comment]
Closing as likely stale. CC @DavidSpickett in case anyone wants to follow up on my questions above, but I believe things have changed a bit since I was asking.

**Comment by DavidSpickett** [comment]
For reference the current host compiler is Clang 16.0.4 on the SVE bots.

1. The wrapper has been removed. Should it be needed again we could do this in zorg, it is always a tradeoff of transparency vs. the turnaround time to get changes into the buildbot system.

2. All SVE bots are now generating SVE code in all build stages. The single stage builds are also some of our fastest so hitting generic problems is part of their purpose now.
