### ISSUE TITLE
Implied shape only partially implemented

### ISSUE THREAD

**Issue by f1c75e60-3df5-4d76-9640-642b0a387427** [llvm/llvm-project#51177]
|  |  |
| --- | --- |
| Bugzilla Link | [51835](https://llvm.org/bz51835) |
| Version | 12.0 |
| OS | Linux |
| CC | @jeanPerier,@kiranchandramohan,@kiranktp,@sscalpone |

## Extended Description 
Hello,

the following code compiles and works fine with GNU, Intel, NVIDIA, and NAG.

It is however not fully working with flang-12 or flang-13 that comes with
AMD ROCm:

  integer,       parameter :: list1(*)     = [1,2]             ! ok
  character(1),  parameter :: gnss1(*)     = ["G","R","E","C"] ! ok
  integer,       parameter :: list2(42:*)  = [1,2]             ! fails
  character(1),  parameter :: gnss2(401:*) = ["G","R","E","C"] ! fails
  print *, gnss2
end

It would be nice to have this available in a future LLVM release.

Thanks,
Harald

**Comment by psteinfeld** [comment]
It looks like this issue is not for this compiler.  I'm closing it.
