### ISSUE TITLE
clang crashes (-O1 and above) at lib/CodeGen/RegisterCoalescer.cpp:2707 Assertion `(TrackSubRegLiveness || V.RedefVNI) && "Instruction is reading nonexistent value"' failed

### ISSUE THREAD

**Issue by haoxintu** [llvm/llvm-project#51172]
|  |  |
| --- | --- |
| Bugzilla Link | [51830](https://llvm.org/bz51830) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Hi all.

$cat small.c
#include <stdint.h>
int a, b, c, d, e, f, g, i;
fn1() {
  uint16_t j;
  uint8_t *k;
  for (; a; a++) {
    if (e) {
      if ((e = j) ? d : 0) {
        j = a;
        k = &j;
        e ^= b + b;
      }
      c = g;
    }
    j *= f;
    for (; b; b++)
      ;
  }
  for (d = 4; d <= 83; d++)
    k = &e;
  *k %= i;
}

$clang -w -m32 -O2 small.c (same as -O3 and -Os)
clang-14: /home/haoxin/haoxin-data/compilers/llvm-project/llvm/lib/CodeGen/RegisterCoalescer.cpp:2707: {anonymous}::JoinVals::ConflictResolution {anonymous}::JoinVals::analyzeValue(unsigned int, {anonymous}::JoinVals&): Assertion `(TrackSubRegLiveness || V.RedefVNI) && "Instruction is reading nonexistent value"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14 -cc1 -triple i386-unknown-linux-gnu -emit-obj --mrelax-relocations -disable-free -main-file-name small.c -mrelocation-model static -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -target-cpu pentium4 -tune-cpu generic -debugger-tuning=gdb -fcoverage-compilation-dir=/home/haoxin/haoxin-data/dut-research/covsmith-test/20210819/5 -resource-dir /home/haoxin/haoxin-data/compilers/llvm-project/build/lib/clang/14.0.0 -internal-isystem /home/haoxin/haoxin-data/compilers/llvm-project/build/lib/clang/14.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -Os -w -fdebug-compilation-dir=/home/haoxin/haoxin-data/dut-research/covsmith-test/20210819/5 -ferror-limit 19 -fgnuc-version=4.2.1 -fcolor-diagnostics -vectorize-loops -vectorize-slp -faddrsig -o /tmp/small-55019d.o -x c small.c
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'small.c'.
4.	Running pass 'Simple Register Coalescing' on function '@fn1'
 #&#8203;0 0x0000564593633404 PrintStackTraceSignalHandler(void*) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x3b80404)
 #&#8203;1 0x0000564593630b1e SignalHandler(int) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x3b7db1e)
 #&#8203;2 0x00007f6bc37853c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #&#8203;3 0x00007f6bc322418b raise /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #&#8203;4 0x00007f6bc3203859 abort /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:81:7
 #&#8203;5 0x00007f6bc3203729 get_sysdep_segment_value /build/glibc-eX1tMB/glibc-2.31/intl/loadmsgcat.c:509:8
 #&#8203;6 0x00007f6bc3203729 _nl_load_domain /build/glibc-eX1tMB/glibc-2.31/intl/loadmsgcat.c:970:34
 #&#8203;7 0x00007f6bc3214f36 (/lib/x86_64-linux-gnu/libc.so.6+0x36f36)
 #&#8203;8 0x00005645929818bc (anonymous namespace)::JoinVals::computeAssignment(unsigned int, (anonymous namespace)::JoinVals&) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x2ece8bc)
 #&#8203;9 0x0000564592981931 (anonymous namespace)::JoinVals::mapValues((anonymous namespace)::JoinVals&) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x2ece931)
#&#8203;10 0x000056459298a0e0 (anonymous namespace)::RegisterCoalescer::joinVirtRegs(llvm::CoalescerPair&) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x2ed70e0)
#&#8203;11 0x000056459298bdfb (anonymous namespace)::RegisterCoalescer::joinCopy(llvm::MachineInstr*, bool&) (.constprop.0) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x2ed8dfb)
#&#8203;12 0x000056459298e022 (anonymous namespace)::RegisterCoalescer::copyCoalesceWorkList(llvm::MutableArrayRef<llvm::MachineInstr*>) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x2edb022)
#&#8203;13 0x0000564592991855 (anonymous namespace)::RegisterCoalescer::runOnMachineFunction(llvm::MachineFunction&) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x2ede855)
#&#8203;14 0x00005645927e01e8 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.localalias) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x2d2d1e8)
#&#8203;15 0x0000564592cd2395 llvm::FPPassManager::runOnFunction(llvm::Function&) (.localalias) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x321f395)
#&#8203;16 0x0000564592cd25d9 llvm::FPPassManager::runOnModule(llvm::Module&) (.localalias) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x321f5d9)
#&#8203;17 0x0000564592cd36c2 llvm::legacy::PassManagerImpl::run(llvm::Module&) (.localalias) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x32206c2)
#&#8203;18 0x00005645939783b8 (anonymous namespace)::EmitAssemblyHelper::EmitAssemblyWithNewPassManager(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x3ec53b8)
#&#8203;19 0x000056459397bf35 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x3ec8f35)
#&#8203;20 0x00005645947f4d6f clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x4d41d6f)
#&#8203;21 0x0000564595537799 clang::ParseAST(clang::Sema&, bool, bool) (.localalias) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x5a84799)
#&#8203;22 0x00005645947f38a8 clang::CodeGenAction::ExecuteAction() (.localalias) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x4d408a8)
#&#8203;23 0x0000564594077ec9 clang::FrontendAction::Execute() (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x45c4ec9)
#&#8203;24 0x000056459400912e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (.localalias) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x455612e)
#&#8203;25 0x00005645941583e0 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x46a53e0)
#&#8203;26 0x0000564590e1483d cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x136183d)
#&#8203;27 0x0000564590e10a98 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x135da98)
#&#8203;28 0x0000564590d44b59 main (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x1291b59)
#&#8203;29 0x00007f6bc32050b3 __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:342:3
#&#8203;30 0x0000564590e1060e _start (/home/haoxin/haoxin-data/compilers/llvm-project/build/bin/clang-14+0x135d60e)
clang-14: error: unable to execute command: Aborted (core dumped)
clang-14: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 14.0.0 (https://github.com/llvm/llvm-project 4e408aae2c55a8fd71b5a96eb86db350a7acc443)
Target: i386-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/haoxin/haoxin-data/compilers/llvm-project/build/bin
clang-14: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-14: note: diagnostic msg: /tmp/small-bcd439.c
clang-14: note: diagnostic msg: /tmp/small-bcd439.sh
clang-14: note: diagnostic msg: 

********************

Thanks,
Haoxin

**Comment by Endilll** [comment]
The first test case appears to be fixed in Clang 14: https://godbolt.org/z/z5z8EaoW9
The second test case appears to be fixed in Clang 16 (I added a couple of casts to make 15 crash): https://godbolt.org/z/xWTc65Yne
