### ISSUE TITLE
inconsistent handling of #pragma message

### ISSUE THREAD

**Issue by wolfy1961** [llvm/llvm-project#51179]
|  |  |
| --- | --- |
| Bugzilla Link | [51837](https://llvm.org/bz51837) |
| Version | trunk |
| OS | Windows NT |
| CC | @pogo59,@zygoloid |

## Extended Description 
// Given a simple source like
#pragma message("foobar")

we get a warning when compiled with no extra options, -Werror, or -W#pragma-messages:

> clang -c test2.cpp
test2.cpp:1:9: warning: foobar [-W#pragma-messages]
#pragma message("foobar")
        ^
1 warning generated.

> clang -c -Werror test2.cpp
test2.cpp:1:9: warning: foobar [-W#pragma-messages]
#pragma message("foobar")
        ^
1 warning generated.

> clang -c -W#pragma-messages test2.cpp
test2.cpp:1:9: warning: foobar [-W#pragma-messages]
#pragma message("foobar")
        ^
1 warning generated.

However, when compiled with both -Werror and -W#pragma-messages we get an error:
> clang -c  -Werror  -W#pragma-messages test2.cpp
test2.cpp:1:9: error: foobar [-Werror,-W#pragma-messages]
#pragma message("foobar")
        ^
1 error generated.

The reason seems to be that the "NoWarningAsError" flag (which is present in the descriptor for the pragma messages warning) is dropped during warning options processing (probably in DiagnosticsEngine::setSeverity()) or thereabouts.

**Comment by jyknight** [comment]
Fixed by @wolfy1961 in d789ea713372d44e50ff52a85a198ac6bbedaef9 (committed back in January, part of LLVM 14).

**Comment by BFlemingFDI** [comment]
In gcc you can use #pragma message("") to print out notes that won't trigger a warning. Is there a way to get similar behavior or an equivalent feature from clang? (preferably it could use the same pragma for existing software)
