### ISSUE TITLE
The partial comment produced by deleting splice is accepted by Clang

### ISSUE THREAD

**Issue by 8084cac4-606c-41d3-baea-106d693787ba** [llvm/llvm-project#51186]
|  |  |
| --- | --- |
| Bugzilla Link | [51844](https://llvm.org/bz51844) |
| Version | trunk |
| OS | All |
| CC | @AaronBallman,@zygoloid |

## Extended Description 
Given the source file: 
````
int main(){
}
//\

````
According to [lex.phases] p2

> Each sequence of a backslash character (\) immediately followed by zero or more whitespace characters other than new-line followed by a new-line character is deleted, splicing physical source lines to form logical source lines.

That means the source file will end with `/`, after the above phase. "//" starts a comment and the comment is terminated by a new-line as per [lex.comment] p1

> The characters // start a comment, which terminates immediately before the next new-line character.  

According to [lex.phases] p3  
> A source file shall not end in a partial preprocessing token or in a partial comment.

Since there is no new-line to terminate the comment, hence it is a partial comment and the source file ends with that partial comment, the program should be ill-formed.

**Comment by cor3ntin** [comment]
resolved by https://cplusplus.github.io/CWG/issues/2747.html
