### ISSUE TITLE
Sink: moves calls that may not return

### ISSUE THREAD

**Issue by nunoplopes** [llvm/llvm-project#51188]
|  |  |
| --- | --- |
| Bugzilla Link | [51846](https://llvm.org/bz51846) |
| Version | trunk |
| OS | All |
| CC | @fhahn,@MaskRay |

## Extended Description 
Test: Transforms/Sink/call.ll

Transformation only valid if willreturn & nounwind attributes are present.

define i32 @&#8203;test_sink_no_stores(i1 %z) {
%0:
  %l = call i32 @&#8203;f_load_global() nowrite nofree
  br i1 %z, label %true, label %false

%false:
  ret i32 0

%true:
  ret i32 %l
}
=>
define i32 @&#8203;test_sink_no_stores(i1 %z) {
%0:
  br i1 %z, label %true, label %false

%false:
  ret i32 0

%true:
  %l = call i32 @&#8203;f_load_global() nowrite nofree
  ret i32 %l
}
Transformation doesn't verify!
ERROR: Source is more defined than target

Example:
i1 %z = undef

Source:
i32 %l = UB triggered!

SOURCE MEMORY STATE
===================
NON-LOCAL BLOCKS:
Block 0 >	size: 0	align: 1	alloc type: 0
Block 1 >	size: 0	align: 1

Target:
UB triggered on br

**Comment by nikic** [comment]
I just realized that there is still a remaining failure:
```

@A = global 4 bytes, align 4
@B = global 4 bytes, align 4

define i32 @test_sink_argmem_multiple(i1 %z) {
%0:
  %l = call i32 @f_load_arg(ptr @A) nowrite argmemonly nofree willreturn
  call void @f_readonly_arg(ptr @A, ptr @B) argmemonly willreturn
  br i1 %z, label %true, label %false

%false:
  ret i32 0

%true:
  ret i32 %l
}
=>
@A = global 4 bytes, align 4
@B = global 4 bytes, align 4

define i32 @test_sink_argmem_multiple(i1 %z) {
%0:
  call void @f_readonly_arg(ptr @A, ptr @B) argmemonly willreturn
  br i1 %z, label %true, label %false

%false:
  ret i32 0

%true:
  %l = call i32 @f_load_arg(ptr @A) nowrite argmemonly nofree willreturn
  ret i32 %l
}
Transformation doesn't verify!
ERROR: Source is more defined than target

Example:
i1 %z = #x1 (1)

Source:
i32 %l = poison
  >> Jump to %true

SOURCE MEMORY STATE
===================
NON-LOCAL BLOCKS:
Block 0 >	size: 0	align: 1	alloc type: 0
Block 1 >	size: 4	align: 4	alloc type: 0
Block 2 >	size: 4	align: 4	alloc type: 0
Block 3 >	size: 4	align: 4	alloc type: 0

Target:
  >> Jump to %true
i32 %l = UB triggered!
```
However, I don't really understand what alive is trying to tell me here. Why is this a miscompile? Relevant signatures are:
```
declare i32 @f_load_arg(i32*) nounwind willreturn readonly argmemonly
declare void @f_readonly_arg(i32* readonly, i32*) nounwind willreturn argmemonly
```

**Comment by nunoplopes** [comment]
I think that's a bug in Alive2. Or rather a feature that is not implemented. The call to `@f_readonly_arg` doesn't have the `readonly` attribute in the argument.
