### ISSUE TITLE
LLVM fails to build on PPC with GCC>=9 and -fno-plt

### ISSUE THREAD

**Issue by h-vetinari** [llvm/llvm-project#51205]
|  |  |
| --- | --- |
| Bugzilla Link | [51863](https://llvm.org/bz51863) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#50580  |
| CC | @h-vetinari,@nemanjai,@tstellar,@xtkoba |

## Extended Description 
Originally when building v11.1.0 for conda-forge (https://github.com/conda-forge/llvmdev-feedstock/pull/115), there was an issue with using GCC 9 (only on PPC), so we kept using GCC 8.

Now, two major versions later, GCC 8 fails for other reaons (unrelated to LLVM), and I wanted to try upgrading the version again, see https://github.com/conda-forge/llvmdev-feedstock/pull/131.

As it turns out the same error persists with GCC 11.1 & LLVM 13. I cannot tell where the fault lies exactly, because there's not much output from the linker to go on.

```
[...]
[ 88%] Building CXX object tools/llvm-exegesis/lib/X86/CMakeFiles/LLVMExegesisX86.dir/X86Counter.cpp.o
collect2: error: ld returned 1 exit status
make[2]: *** [tools/llvm-shlib/CMakeFiles/LLVM.dir/build.make:299: lib/libLLVM-13.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:30826: tools/llvm-shlib/CMakeFiles/LLVM.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 88%] Linking CXX static library ../../../../lib/libLLVMExegesisX86.a
[ 88%] Built target LLVMExegesisX86
make: *** [Makefile:156: all] Error 2
```

Sample CI run is here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=376252

**Comment by asl** [comment]
@tstellar Move to 13.0.1?

**Comment by h-vetinari** [comment]
> @tstellar Move to 13.0.1?

I think this never got removed from 13.0.0, but since it has no patch/solution, I don't think it makes sense to add it to 13.0.1.
