### ISSUE TITLE
AlignConsecutiveDeclarations and PointerAlignment is wrong with double pointers

### ISSUE THREAD

**Issue by 51ab0863-01bd-45af-a1cd-0586867222bf** [llvm/llvm-project#51203]
|  |  |
| --- | --- |
| Bugzilla Link | [51861](https://llvm.org/bz51861) |
| Version | trunk |
| OS | Linux |
| CC | @jadahl |

## Extended Description 
When using a config including:

```
PointerAlignment: Right
AlignConsecutiveDeclarations: true
```

with code such as:

```
static void
foo_function (int *ptr,
              const char *path,
              GError **error)
```

We get:

```
static void
foo_function (int        *ptr,
              const char *path,
              GError    **error)
```

While an extra space is expected:

```

static void
foo_function (int         *ptr,
              const char  *path,
              GError     **error)
```

Not sure if this should be available through another `AlignConsecutivePointerDeclarationStyle` option.

**Comment by mydeveloperday** [comment]
I think this is a subjective, it always ensure there is one space if the variable becomes the maximum it will push everything out

```
  static void
  foo_function(int        *ptr,
               const char *path,
               GErrorXXX **error,
               GError    **error);
```

as the variable becomes equal to the longest type

```
  static void
  foo_function(int         *ptr,
               const char  *path,
               GErrorXXXX **error,
               GError     **error);
```

I think this is functioning as designed no?

**Comment by mydeveloperday** [comment]
Closing as no comment, please feel free to reopen this if you want to discuss it more

**Comment by 3v1n0** [comment]
@mydeveloperday sorry, I didn't see the notification in time.

Indeed that's a subjective option, but some projects like to have an extra space, so it would be nice to have a clang-format flag to control this.
