### ISSUE TITLE
check-expression.cpp fold-integer.cpp

### ISSUE THREAD

**Issue by 3b3be5bc-be97-4c5a-a058-de8ddaf7c081** [llvm/llvm-project#51215]
|  |  |
| --- | --- |
| Bugzilla Link | [51873](https://llvm.org/bz51873) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#50580 llvm/llvm-project#51489  |
| CC | @tstellar |

## Extended Description 
These two errors occurred early on Ubuntu 21.04 13.0.0-rc3.

make[2]: *** [tools/flang/lib/Evaluate/CMakeFiles/obj.FortranEvaluate.dir/build.make:108: tools/flang/lib/Evaluate/CMakeFiles/obj.FortranEvaluate.dir/check-expression.cpp.o] Error 137

make[2]: *** [tools/flang/lib/Evaluate/CMakeFiles/obj.FortranEvaluate.dir/build.make:225: tools/flang/lib/Evaluate/CMakeFiles/obj.FortranEvaluate.dir/fold-integer.cpp.o] Error 137

**Comment by tstellar** [comment]
The deadline for requesting fixes for the release has passed.  This bug is being removed from the LLVM 13.0.1 release milestone.  If you have a fix or think this bug is important enough to block the release, please explain why in a comment and add the bug back to the LLVM 13.0.1 release milestone.

**Comment by arsenm** [comment]
Old release
