### ISSUE TITLE
scan-build-py fails to find analyze-cc

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#51239]
|  |  |
| --- | --- |
| Bugzilla Link | [51897](https://llvm.org/bz51897) |
| Resolution | FIXED |
| Resolved on | Sep 27, 2021 00:25 |
| Version | unspecified |
| OS | Linux |
| CC | @serge-sans-paille |
| Fixed by commit(s) | e45f67f31e22ce9808f4e64ab3f54fadad640d97 |

## Extended Description 
Regression from https://reviews.llvm.org/D109659
---
******************** TEST 'LLVM regression suite :: scanbuild_py_makefile.txt' FAILED ********************
Script:
--
: 'RUN: at line 6';   rm -rf /check/build/tests/Output/scanbuild_py_makefile.txt.tmp
: 'RUN: at line 7';   mkdir -p /check/build/tests/Output/scanbuild_py_makefile.txt.tmp
: 'RUN: at line 8';   cp /check/tests/scanbuild_py.cpp /check/build/tests/Output/scanbuild_py_makefile.txt.tmp
: 'RUN: at line 9';   cd /check/build/tests/Output/scanbuild_py_makefile.txt.tmp && /usr/bin/scan-build-py-14 make -f /check/tests/scanbuild_py_makefile.txt|grep "to examine bug reports"
: 'RUN: at line 10';   cd /check/build/tests/Output/scanbuild_py_makefile.txt.tmp && /usr/bin/scan-build-py-14 --intercept-first make -f /check/tests/scanbuild_py_makefile.txt && test -f compile_commands.json
--
Exit Code: 1

Command Output (stderr):
--
make: /usr/bin/../libexec/analyze-cc: No such file or directory
make: *** [/check/tests/scanbuild_py_makefile.txt:13: all] Error 127

--
---

In debian, it is located in:
/usr/lib/llvm-13/libexec/analyze-cc

**Comment by tstellar** [comment]
@serge-sans-paille Is this safe to backport?

**Comment by tstellar** [comment]
@serge-sans-paille Also, this does not backport cleanly could you push a release/13.x version of it to a github for?

**Comment by serge-sans-paille** [comment]
@tstellar: you need to pick the two last commits from https://github.com/serge-sans-paille/llvm-project/tree/release/13.x

**Comment by xgupta** [comment]
This can be closed.
