### ISSUE TITLE
clang format break syntax of C++ lambdas with BeforeLambdaBody true and trailing comment

### ISSUE THREAD

**Issue by tophoo** [llvm/llvm-project#51234]
|  |  |
| --- | --- |
| Bugzilla Link | [51892](https://llvm.org/bz51892) |
| Version | unspecified |
| OS | All |
| Attachments | [clang format file](https://user-images.githubusercontent.com/93435495/143762547-d6edadf9-1e12-4e67-8c9d-d02cdca100a9.gz) |
| CC | @mydeveloperday |

## Extended Description 

Related to Bug 45791 there is another Bug regarding the brace wrapping option (BeforeLambdaBody: true) in combination with a lambda statement and a trailing comment on the return statement:

```
foo([]() {
  return 1; // comment
}());
```

becomes:

```
foo([]()
    {
  return 1; // comment }());
```

using the .clang-format file:

```
BreakBeforeBraces: Custom
BraceWrapping: {
    BeforeLambdaBody: true,
}
ColumnLimit: 0
```

**Comment by kalinnikovv** [comment]
Should be noted that this isn't an issue just with comments.
The closing brace of the lambda body _always_ gets folded into the line before it. 

```
foo(param, [] {
return 1;
}());
```
gets formatted into
```
foo(param, []
    {
         return 1;  });
```
while I expect it to become
```
foo(param, []
    {
         return 1;
    });
```

**Comment by owenca** [comment]
https://reviews.llvm.org/D122301

**Comment by owenca** [comment]
@tophoo, can you open a separate issue for the non-`invalid-code-generation` part?
