### ISSUE TITLE
Clang segfaults with loop unroll(enable)

### ISSUE THREAD

**Issue by Vsevolod-Livinskij** [llvm/llvm-project#51265]
|  |  |
| --- | --- |
| Bugzilla Link | [51923](https://llvm.org/bz51923) |
| Version | trunk |
| OS | Linux |
| Attachments | [Original reproducer](https://user-images.githubusercontent.com/92601286/143762555-f3ef5b11-2554-4ce9-bf8c-dc124378464a.gz) |
| CC | @dbabokin,@fhahn,@preames,@regehr,@Vsevolod-Livinskij |

## Extended Description 

The bus is reproducible with -O2 and -O3, but it takes about one minute to fail.
I suspect that "if" statement is not required, we need it to avoid UB at runtime.

I didn't investigate the bug, but it looks like clang tries to unroll the loop too many times and either gets stuck or ignores the internal limit.

I've also attached the original reproducer (it fails with -O3), because it failed with a slightly different stack trace.

Reproducer:
extern short var_16;
extern short arr_99[];
void test() {
  if (!var_16)
#pragma clang loop unroll(enable)
    for (short a = 5652; a; a += 2)
      for (long b = 0; b < -6ULL; b += -18446744073709551612ULL)
        arr_99[b] = 0;
}

Error:
> clang++ -O2 -c func.cpp
Segmentation fault

Stack trace from GDB:
 #&#8203;35 0x000055bc1b532567 StrengthenNoWrapFlags(llvm::ScalarEvolution*, llvm::SCEVTypes, llvm::ArrayRef<llvm::SCEV const*>, llvm::SCEV::NoWrapFlags) ScalarEvolution.cpp:0:0
 #&#8203;36 0x000055bc1b5362f6 llvm::ScalarEvolution::getAddExpr(llvm::SmallVectorImpl<llvm::SCEV const*>&, llvm::SCEV::NoWrapFlags, unsigned int) (/testing/llvm/bin/bin/clang-14+0x145d2f6)
 #&#8203;37 0x000055bc1b527008 llvm::ScalarEvolution::createSCEV(llvm::Value*) (.part.0) ScalarEvolution.cpp:0:0
 #&#8203;38 0x000055bc1b527a4e llvm::ScalarEvolution::getSCEV(llvm::Value*) (.part.0) ScalarEvolution.cpp:0:0
 #&#8203;39 0x000055bc1b546505 llvm::ScalarEvolution::applyLoopGuards(llvm::SCEV const*, llvm::Loop const*) (/testing/llvm/bin/bin/clang-14+0x146d505)
 #&#8203;40 0x000055bc1b54c959 llvm::ScalarEvolution::howFarToZero(llvm::SCEV const*, llvm::Loop const*, bool, bool) (/testing/llvm/bin/bin/clang-14+0x1473959)
 #&#8203;41 0x000055bc1b54e3bd llvm::ScalarEvolution::computeExitLimitFromICmp(llvm::Loop const*, llvm::ICmpInst*, bool, bool, bool) (/testing/llvm/bin/bin/clang-14+0x14753bd)
 #&#8203;42 0x000055bc1b54e972 llvm::ScalarEvolution::computeExitLimitFromCondImpl(llvm::ScalarEvolution::ExitLimitCache&, llvm::Loop const*, llvm::Value*, bool, bool, bool) (/testing/llvm/bin/bin/clang-14+0x1475972)
 #&#8203;43 0x000055bc1b54eb83 llvm::ScalarEvolution::computeExitLimitFromCondCached(llvm::ScalarEvolution::ExitLimitCache&, llvm::Loop const*, llvm::Value*, bool, bool, bool) (/testing/llvm/bin/bin/clang-14+0x1475b83)
 #&#8203;44 0x000055bc1b54ecbd llvm::ScalarEvolution::computeExitLimitFromCond(llvm::Loop const*, llvm::Value*, bool, bool, bool) (/testing/llvm/bin/bin/clang-14+0x1475cbd)
 #&#8203;45 0x000055bc1b51f9f0 llvm::ScalarEvolution::computeExitLimit(llvm::Loop const*, llvm::BasicBlock*, bool) (/testing/llvm/bin/bin/clang-14+0x14469f0)
 #&#8203;46 0x000055bc1b51fef7 llvm::ScalarEvolution::computeBackedgeTakenCount(llvm::Loop const*, bool) (/testing/llvm/bin/bin/clang-14+0x1446ef7)
 #&#8203;47 0x000055bc1b520aa2 llvm::ScalarEvolution::getBackedgeTakenInfo(llvm::Loop const*) (/testing/llvm/bin/bin/clang-14+0x1447aa2)
 #&#8203;48 0x000055bc1b521b40 llvm::ScalarEvolution::getConstantMaxBackedgeTakenCount(llvm::Loop const*) (/testing/llvm/bin/bin/clang-14+0x1448b40)
 #&#8203;49 0x000055bc1b530fec llvm::ScalarEvolution::getRangeRef(llvm::SCEV const*, llvm::ScalarEvolution::RangeSignHint) (/testing/llvm/bin/bin/clang-14+0x1457fec)

LLVM version:
clang version 14.0.0 (https://github.com/llvm/llvm-project.git 55f0b337087136554122f942fea951a357bc4a49)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /testing/llvm/bin/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

**Comment by fhahn** [comment]
Unfortunately I am unable to reproduce this locally any longer. We still unroll a LOT, but there's no crash.

Please re-open with additional details if it still reproduces on your end.
