### ISSUE TITLE
Complete JITLink ELF/AArch64 backend.

### ISSUE THREAD

**Issue by lhames** [llvm/llvm-project#51266]
|  |  |
| --- | --- |
| Bugzilla Link | [51924](https://llvm.org/bz51924) |
| Version | trunk |
| OS | All |
| CC | @AlexDenisov,@lhames,@weliveindetail |

## Extended Description 
Once we have a fully working ELF/AArch64 backend for JITLink we can use it rather than RuntimeDyld. This will help us to fix https://bugs.swift.org/browse/SR-15213 (though slab memory allocation may still be required for that bug).

**Comment by sunho** [comment]
We close this now. ELF/AARCH64 is complete enough to be usable in julia. (https://github.com/JuliaLang/julia/pull/45859)
