### ISSUE TITLE
Non-standard code managed to crash the parser

### ISSUE THREAD

**Issue by Mrkol** [llvm/llvm-project#51279]
|  |  |
| --- | --- |
| Bugzilla Link | [51937](https://llvm.org/bz51937) |
| Version | 12.0 |
| OS | Linux |
| Attachments | [clang++ stderr](https://user-images.githubusercontent.com/93435489/143762562-317797be-e65a-4540-9151-ecaf7fb3ec02.gz), [preprocessed sources](https://user-images.githubusercontent.com/93435489/143762563-6252229a-946d-45bc-b9a5-2a3a63956af5.gz), [associated run script](https://user-images.githubusercontent.com/93435489/143762564-9d3e8c2e-0f23-4d78-85ea-b429fb0ee1f1.gz) |
| CC | @zygoloid |

## Extended Description 
Clang allows for nested template specialization, which is strictly speaking non-standard, but when the main specialization has constrained arguments, the parser dies with a segfault. Logs and stuff are attached.

**Comment by royjacobson** [comment]
Fixed in trunk, apparently.
