### ISSUE TITLE
llvm-rc: not merging string literals for paths

### ISSUE THREAD

**Issue by jeremyd2019** [llvm/llvm-project#51286]
|  |  |
| --- | --- |
| Bugzilla Link | [51944](https://llvm.org/bz51944) |
| Version | 12.0 |
| OS | Windows NT |
| CC | @mstorsjo |

## Extended Description 
I'm not really sure if this is something that only works in windres or if it also works in rc.exe.  I came across this rc in virt-viewer

  llvm-rc: Error in ICON statement (ID 2): 
  Is a directory
'['D:/a/_temp/msys/msys64/clang64/bin/windres.EXE', '-DICONDIR=\\"C:/_/mingw-w64-virt-viewer/src/build-x86_64-w64-mingw32/icons\\"', '-DMANIFESTDIR=\\"C:/_/mingw-w64-virt-viewer/src/virt-viewer-10.0/src\\"', '-i', 'src/virt-viewer.rc', '-o', 'src/virt-viewer-rc.o']' returned non-zero exit status 1.

The RC file in question is https://gitlab.com/virt-viewer/virt-viewer/-/blob/v10.0/src/virt-viewer.rc.in , and the ICON statement is

2 ICON ICONDIR "/virt-viewer.ico"

I assume they meant for that to somehow transform into `2 ICON "C:/_/mingw-w64-virt-viewer/src/build-x86_64-w64-mingw32/icons/virt-viewer.ico"`.  This reminded me of https://reviews.llvm.org/D105621#inline-1004064 but this is in an ICON statement not a user defined resource.

**Comment by jeremyd2019** [comment]
Another, more common instance seems to exist in an rc file provided by wxWidgets (intended to be included in the rc file for programs using wxWidgets) for their default manifest: https://github.com/wxWidgets/wxWidgets/blob/866cdfe20000178145896497c23ce4598cc88068/include/wx/msw/wx.rc#L122

**Comment by hmartinez82** [comment]
I was able to reproduce this while building GIMP for Windows using Clang in MSYS2.

**Comment by mstorsjo** [comment]
I finally took some time to finish my half-done attempt at fixing this, and posted it for review at https://github.com/llvm/llvm-project/pull/68685.

**Comment by mstorsjo** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/6f41510d4f4848ca4dde203d24bae26587be1f8c.

@mati865 and others - you may want to cherrypick this into msys2.

I'm not entirely sure about requesting a backport to 17.x here for this (it's too late for 17.0.3 which is cut tomorrow, and we're pretty far down the release branch already so the threshold for what to backport is pretty high by 17.0.4). Or any opinions from @cjacek or @tru?

**Comment by tru** [comment]
It doesn't look like a regression to me. So my vote is for it to wait until 18.x unless I am misunderstanding the PR.

**Comment by mstorsjo** [comment]
> It doesn't look like a regression to me. So my vote is for it to wait until 18.x unless I am misunderstanding the PR.

Yep, not a regression; I was contemplating the backport-worthyness in the category "other small and safe bugfix/improvement", but I agree that this can wait to 18.x.
