### ISSUE TITLE
linalg fill op parser crash

### ISSUE THREAD

**Issue by bondhugula** [llvm/llvm-project#51313]
|  |  |
| --- | --- |
| Bugzilla Link | [51971](https://llvm.org/bz51971) |
| Version | unspecified |
| OS | Linux |
| CC | @joker-eph,@MaheshRavishankar |

## Extended Description 
With the latest upstream version 897eb579c615260d68fee7ecc11a5d1773fa3781 (Sep 25):

$ cat | mlir-opt
func @&#8203;crash() {
  %A = memref.alloc() : memref<1xf64>
  %cf1 = constant 1.00000e+00 : f64
  linalg.fill(%A, %cf1) : memref<1xf64>, f64
  return
}

mlir-opt: /home/uday/llvm-project-upstream/mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp:2835: void fillStructuredOpRegion(mlir::OpBuilder&, mlir::Region&, mlir::TypeRange, mlir::TypeRange, std::function<void(unsigned int, unsigned int)>) [with NamedStructuredOpType = mlir::linalg::FillOp]: Assertion `llvm::all_of(outputTypes, [](Type t) { return t.isa<ShapedType>(); })' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ../build/bin/mlir-opt /home/uday/mlirx/mlir/crash.mlir
1.	MLIR Parser: custom op parser 'builtin.func'
2.	MLIR Parser: custom op parser 'linalg.fill'
 #&#8203;0 0x0000000000b93e3f PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #&#8203;1 0x0000000000b916ce SignalHandler(int) Signals.cpp:0:0
 #&#8203;2 0x00007f18fff9eb20 __restore_rt sigaction.c:0:0
 #&#8203;3 0x00007f18fec6e37f raise (/lib64/libc.so.6+0x3737f)
 #&#8203;4 0x00007f18fec58db5 abort (/lib64/libc.so.6+0x21db5)
 #&#8203;5 0x00007f18fec58c89 _nl_load_domain.cold.0 loadmsgcat.c:0:0
 #&#8203;6 0x00007f18fec66a76 .annobin___GI___assert_fail.end assert.c:0:0
 #&#8203;7 0x0000000000ce81b0 void fillStructuredOpRegion<mlir::linalg::FillOp>(mlir::OpBuilder&, mlir::Region&, mlir::TypeRange, mlir::TypeRange, std::function<void (unsigned int, unsigned int)>) LinalgOps.cpp:0:0
 #&#8203;8 0x0000000000ce869d parseFillOpRegion(mlir::OpAsmParser&, mlir::Region&, mlir::Type, mlir::Type) (../build/bin/mlir-opt+0xce869d)
 #&#8203;9 0x0000000000ce88dd mlir::linalg::FillOp::parse(mlir::OpAsmParser&, mlir::OperationState&) (../build/bin/mlir-opt+0xce88dd)
#&#8203;10 0x000000000183d44a (anonymous namespace)::OperationParser::parseOperation() Parser.cpp:0:0
#&#8203;11 0x00000000018409ed (anonymous namespace)::OperationParser::parseRegionBody(mlir::Region&, llvm::SMLoc, llvm::ArrayRef<std::pair<(anonymous namespace)::OperationParser::SSAUseInfo, mlir::Type> >, bool) Parser.cpp:0:0
#&#8203;12 0x0000000001840e3c (anonymous namespace)::OperationParser::parseRegion(mlir::Region&, llvm::ArrayRef<std::pair<(anonymous namespace)::OperationParser::SSAUseInfo, mlir::Type> >, bool) Parser.cpp:0:0
#&#8203;13 0x0000000001840fcb (anonymous namespace)::CustomOpAsmParser::parseRegion(mlir::Region&, llvm::ArrayRef<mlir::OpAsmParser::OperandType>, llvm::ArrayRef<mlir::Type>, bool) Parser.cpp:0:0
#&#8203;14 0x00000000018412af (anonymous namespace)::CustomOpAsmParser::parseOptionalRegion(mlir::Region&, llvm::ArrayRef<mlir::OpAsmParser::OperandType>, llvm::ArrayRef<mlir::Type>, bool) Parser.cpp:0:0
#&#8203;15 0x00000000019d08e3 mlir::function_like_impl::parseFunctionLikeOp(mlir::OpAsmParser&, mlir::OperationState&, bool, llvm::function_ref<mlir::Type (mlir::Builder&, llvm::ArrayRef<mlir::Type>, llvm::ArrayRef<mlir::Type>, mlir::function_like_impl::VariadicFlag, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)>) (../build/bin/mlir-opt+0x19d08e3)
#&#8203;16 0x000000000199ea97 mlir::FuncOp::parse(mlir::OpAsmParser&, mlir::OperationState&) (../build/bin/mlir-opt+0x199ea97)

**Comment by nicolasvasilache** [comment]
This was fixed a while back, the proper form is now:
```
func.func @foo() {
  %A = memref.alloc() : memref<1xf64>
  %cf1 = arith.constant 1.00000e+00 : f64
  linalg.fill ins(%cf1: f64) outs(%A: memref<1xf64>)
  return
}
```
