### ISSUE TITLE
The allocation function shall not be called when existing an erroneous expression in noptr-new-declarator

### ISSUE THREAD

**Issue by 8084cac4-606c-41d3-baea-106d693787ba** [llvm/llvm-project#51335]
|  |  |
| --- | --- |
| Bugzilla Link | [51993](https://llvm.org/bz51993) |
| Version | trunk |
| OS | All |
| CC | @zygoloid |

## Extended Description 
```cpp
struct C{
    void* operator new[](std::size_t N) noexcept(false){  // #1
        std::cout<<"abc\n";
        auto p =  malloc(10);
        return p;
    }
};
int n = -1;
auto ptr = new C[n];
std::cout<< ptr;
delete [] ptr;
```

Clang prints that `#1` is called and the address `ptr` is non-null. According to [expr.new] p9, the function at `#1` shall not be called, and since the function has potential throwing specification, the new-expression should terminate by throwing an exception. The address shall be null.  

Example 2: 
```cpp
struct C2{
    void* operator new[](std::size_t N) noexcept{  // #2
        std::cout<<"abc\n";
        auto p =  malloc(10);
        return p;
    }
};
int n = -1;
auto ptr = new C2[n];
std::cout<< ptr;
delete [] ptr;
```
Clang calls `#2`, and the address `ptr` is non-null.

**Comment by frederick-vs-ja** [comment]
This is [CWG1061](https://cplusplus.github.io/CWG/issues/1061.html). Removing incorrect `c++20` tag.
