### ISSUE TITLE
13.0.0-rc4: compile time warnings

### ISSUE THREAD

**Issue by 4084477f-e1df-4024-a410-168c80096e18** [llvm/llvm-project#51340]
|  |  |
| --- | --- |
| Bugzilla Link | [51998](https://llvm.org/bz51998) |
| Version | unspecified |
| OS | Windows NT |
| Attachments | [llvm compile time warnings](https://user-images.githubusercontent.com/92601379/143762582-39068ab8-049c-4e45-ad21-7bd7f3029268.gz) |

## Extended Description 

gcc 11.2.1.
First just summary stats:

[tkloczko@barrel SPECS]$ cat llvm.out  | grep -- -W | sed 's/.*\[//; s/\]//' | sort | uniq -c | sort -nr
     37 -Wuninitialized
     12 -Wnonnull
      5 -Walloc-size-larger-than=
      3 -Wodr
      3 -Wcast-function-type
      2 -Wtype-limits
      2 -Wstringop-overflow=
      2 /home/tkloczko/rpmbuild/BUILD/llvm-13.0.0rc4.src/include/llvm/Support/SourceMgr.h:241: note: '-Wmisleading-indentation' is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
      1 -Wunused-but-set-parameter
      1 -Wextra
      1 /home/tkloczko/rpmbuild/BUILD/llvm-13.0.0rc4.src/x86_64-redhat-linux-gnu/lib/Target/X86/X86GenDAGISel.inc:287031: note: '-Wmisleading-indentation' is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
      1 /home/tkloczko/rpmbuild/BUILD/llvm-13.0.0rc4.src/x86_64-redhat-linux-gnu/lib/Target/RISCV/RISCVGenDAGISel.inc:656342: note: '-Wmisleading-indentation' is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
      1 /home/tkloczko/rpmbuild/BUILD/llvm-13.0.0rc4.src/x86_64-redhat-linux-gnu/lib/Target/AMDGPU/AMDGPUGenSearchableTables.inc:959: note: '-Wmisleading-indentation' is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
      1 /home/tkloczko/rpmbuild/BUILD/llvm-13.0.0rc4.src/x86_64-redhat-linux-gnu/lib/Target/AMDGPU/AMDGPUGenInstrInfo.inc:123444: note: '-Wmisleading-indentation' is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
      1 /home/tkloczko/rpmbuild/BUILD/llvm-13.0.0rc4.src/x86_64-redhat-linux-gnu/lib/Target/AMDGPU/AMDGPUGenDAGISel.inc:210602: note: '-Wmisleading-indentation' is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
      1 /home/tkloczko/rpmbuild/BUILD/llvm-13.0.0rc4.src/lib/Target/AMDGPU/AsmParser/AMDGPUAsmParser.cpp:1814: note: '-Wmisleading-indentation' is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
      1 /home/tkloczko/rpmbuild/BUILD/llvm-13.0.0rc4.src/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp:487: note: '-Wmisleading-indentation' is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers

In attachment are all those warnings extracerd from stderr.

**Comment by arsenm** [comment]
Warnings in old release
