### ISSUE TITLE
clang cannot deduce return type for the implicit instantiation of template specialization

### ISSUE THREAD

**Issue by harashimahashi** [llvm/llvm-project#51367]
|  |  |
| --- | --- |
| Bugzilla Link | [52025](https://llvm.org/bz52025) |
| Version | 12.0 |
| OS | All |
| CC | @zygoloid |

## Extended Description 
The following code fails to compile, however must to.
```cpp
template <typename T>
struct S
{
    template <typename U>
    decltype(auto) operator[](U u);
};

template <>
template <typename U>
decltype(auto) S<int>::operator[](U u)
{
    return u;
}

int main()
{
    S<int> s;
    std::cout << s[1] <<std::endl;
    return 0;
}
```
https://godbolt.org/z/MqqY5cTjx

Impicit instantiation of `S<int>` definition implies implicit instantiation of the `operator[]` template declaration at the line 13(https://eel.is/c++draft/temp#inst-3.1). After that a[1] shall be resolved in favor of declaration instantiated from template at the line 13(https://eel.is/c++draft/temp#inst-10), which implies implicit instantiation of the `operator[]` definition(https://eel.is/c++draft/temp#inst-4), which allows compiler to deduce return type(https://eel.is/c++draft/dcl.spec.auto#general-12)

**Comment by wheatman** [comment]
This was fixed between 18.0.1 and current trunk (20.0.0 8644a2aa0f3540c69464f56b3d538e888b6cbdcb)

https://godbolt.org/z/v93berenf
