### ISSUE TITLE
s390x: libc++ trunk fails to build on "no member named 'abort' in namespace 'std'"

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#51364]
|  |  |
| --- | --- |
| Bugzilla Link | [52022](https://llvm.org/bz52022) |
| Version | unspecified |
| OS | Linux |
| CC | @mclow,@JonPsson,@uweigand |

## Extended Description 
Regression between e2f780fba96c and 4f352d444ecf
https://github.com/llvm/llvm-project/compare/e2f780fba96c..4f352d444ecf (I didn't look yet)

"/build/llvm-toolchain-snapshot-14~++20210930115134+230a6edb49c3/build-llvm/./bin/clang++"  -D_GNU_SOURCE -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_DISABLE_EXTERN_TEMPLATE -D_LIBCXXABI_BUILDING_LIBRARY -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iprojects/libcxxabi/src -I"/build/llvm-toolchain-snapshot-14~++20210930115134+230a6edb49c3/libcxxabi/src" -Iinclude -I"/build/llvm-toolchain-snapshot-14~++20210930115134+230a6edb49c3/llvm/include" -I"/build/llvm-toolchain-snapshot-14~++20210930115134+230a6edb49c3/libcxxabi/include" -I"/build/llvm-toolchain-snapshot-14~++20210930115134+230a6edb49c3/libcxxabi/../libcxx/src" -fuse-ld=gold -fPIC -Wno-unused-command-line-argument -Wno-unknown-warning-option -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections --target=s390x-ibm-linux-gnu  -O2 -DNDEBUG -g1 -fPIC   --target=s390x-ibm-linux-gnu -D_DEBUG "-I/build/llvm-toolchain-snapshot-14~++20210930115134+230a6edb49c3/build-llvm/tools/clang/stage2-bins/include/c++/v1" -std=c++2a -MD -MT projects/libcxxabi/src/CMakeFiles/cxxabi_shared.dir/cxa_demangle.cpp.o -MF projects/libcxxabi/src/CMakeFiles/cxxabi_shared.dir/cxa_demangle.cpp.o.d -o projects/libcxxabi/src/CMakeFiles/cxxabi_shared.dir/cxa_demangle.cpp.o -c '/build/llvm-toolchain-snapshot-14~++20210930115134+230a6edb49c3/libcxxabi/src/cxa_demangle.cpp'
In file included from /build/llvm-toolchain-snapshot-14~++20210930115134+230a6edb49c3/libcxxabi/src/cxa_demangle.cpp:13:
In file included from /build/llvm-toolchain-snapshot-14~++20210930115134+230a6edb49c3/libcxxabi/src/demangle/ItaniumDemangle.h:22:
In file included from /build/llvm-toolchain-snapshot-14~++20210930115134+230a6edb49c3/libcxxabi/src/demangle/StringView.h:17:
In file included from /build/llvm-toolchain-snapshot-14~++20210930115134+230a6edb49c3/build-llvm/tools/clang/stage2-bins/include/c++/v1/algorithm:649:
In file included from /build/llvm-toolchain-snapshot-14~++20210930115134+230a6edb49c3/build-llvm/tools/clang/stage2-bins/include/c++/v1/__debug:25:
In file included from /build/llvm-toolchain-snapshot-14~++20210930115134+230a6edb49c3/build-llvm/tools/clang/stage2-bins/include/c++/v1/cstdlib:85:
In file included from /build/llvm-toolchain-snapshot-14~++20210930115134+230a6edb49c3/build-llvm/tools/clang/stage2-bins/include/c++/v1/stdlib.h:93:
/usr/lib/gcc/s390x-linux-gnu/8/../../../../include/c++/8/stdlib.h:38:12: error: no member named 'abort' in namespace 'std'
using std::abort;
      ~~~~~^
/usr/lib/gcc/s390x-linux-gnu/8/../../../../include/c++/8/stdlib.h:39:12: error: no member named 'atexit' in namespace 'std'
using std::atexit;
      ~~~~~^
/usr/lib/gcc/s390x-linux-gnu/8/../../../../include/c++/8/stdlib.h:40:12: error: no member named 'exit' in namespace 'std'
using std::exit;
      ~~~~~^

**Comment by ldionne** [comment]
Is there anything to do here? It looks like using that option is simply not supported on that platform.

Closing, please reopen if you are expecting an action from us.
