### ISSUE TITLE
Missed loop vectorization with reduction and ptr load/store inside loop

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#51380]
|  |  |
| --- | --- |
| Bugzilla Link | [52038](https://llvm.org/bz52038) |
| Version | trunk |
| OS | Windows NT |
| CC | @DMG862,@fhahn,@AnnaZaks,@RKSimon,@nikic |

## Extended Description 
void test1(int *p, int *t, int N) {
    for (int i = 0; i != N; i++) *t += p[i];
}

void test2(int *p, int *t, int N) {
    if (N > 1024) // hint, N is not small
        for (int i = 0; i != N; i++) *t += p[i];
}

void test3(int *p, int *t, int N) {
    if (N > 1024) { // hint, N is not small
        int s = 0;
        for (int i = 0; i != N; i++) s += p[i];
        *t += s;
    }
}

test3 is successfully vectorized with LLVM, GCC, ICC. Sadly, only ICC can catch test1 and test2.

https://godbolt.org/z/PzoYd4eEK

**Comment by fhahn** [comment]
All 3 functions are now vectorization (with a memory runtime check)
