### ISSUE TITLE
clang-13 regression:  -Rpass=inline doesn't display anything on a simple test case

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#51402]
|  |  |
| --- | --- |
| Bugzilla Link | [52060](https://llvm.org/bz52060) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#50580 llvm/llvm-project#51489  |
| CC | @zygoloid,@tstellar |

## Extended Description 
$ export VERSION=12
$ echo "
int foo(int x, int y) __attribute__((always_inline));
int foo(int x, int y) { return x + y; }
int bar(int j) { return foo(j, j - 2); }" > foo.cc

$ clang-$VERSION -O2 -Rpass=inline foo.cc -c
foo.cc:4:25: remark: _Z3fooii inlined into _Z3bari with (cost=always): always inline attribute at callsite bar:0:25; [-Rpass=inline]
int bar(int j) { return foo(j, j - 2); }

$ export VERSION=13 
$ echo "
int foo(int x, int y) __attribute__((always_inline));
int foo(int x, int y) { return x + y; }
int bar(int j) { return foo(j, j - 2); }" > foo.cc

$ clang-$VERSION -O2 -Rpass=inline foo.cc -c

=> Empty

**Comment by tstellar** [comment]
The deadline for requesting fixes for the release has passed.  This bug is being removed from the LLVM 13.0.1 release milestone.  If you have a fix or think this bug is important enough to block the release, please explain why in a comment and add the bug back to the LLVM 13.0.1 release milestone.
