### ISSUE TITLE
Failure to optimize out dead store when address is of one of two unused locals

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#51408]
|  |  |
| --- | --- |
| Bugzilla Link | [52066](https://llvm.org/bz52066) |
| Version | trunk |
| OS | Linux |

## Extended Description 
```
int foo(bool c)
{
  int a, b;
  return *(c ? &a : &b) = 0;
}
```
This can be optimized to `return 0;`. This optimization is done by GCC, but not LLVM.

**Comment by GabrielRavier** [comment]
Appears to be fixed on trunk.

**Comment by EugeneZelenko** [comment]
@GabrielRavier: It'll be very useful to provide links to https://godbolt.org as proof.

**Comment by GabrielRavier** [comment]
> @GabrielRavier: It'll be very useful to provide links to https://godbolt.org as proof.

https://godbolt.org/z/YG1GT7W96

**Comment by nikic** [comment]
This was fixed by SROA select to CFG promotion.
