### ISSUE TITLE
out of line definition should reject template parameter with lambda of unevaluated context

### ISSUE THREAD

**Issue by nickhuang99** [llvm/llvm-project#51416]
|  |  |
| --- | --- |
| Bugzilla Link | [52074](https://llvm.org/bz52074) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie,@zygoloid |

## Extended Description 
The following code should be rejected as no matching declaration found as GCC/MSVC++ does. clang-13 incorrectly passes without considering that two lambda expressions are never considered as equivalent. [temp.over.link#5.sentence-4]

1. 
template <class T> 
struct A{    
void spam(decltype([]{}) );
};

template<class T>
void A<T>::spam(decltype([]{}))
{}

2.
struct A{   
template <class T>  
void spam(decltype([]{}) );
};

template<class T>
void A::spam(decltype([]{}))
{}

Both of above should be rejected as no declaration found.

**Comment by tstellar** [comment]
@AaronBallman Is this safe to backport? https://github.com/llvm/llvm-project/commit/3784e8ccfbdaaab31f9e9c221daa59a218279999

**Comment by AaronBallman** [comment]
> @AaronBallman Is this safe to backport? [3784e8c](https://github.com/llvm/llvm-project/commit/3784e8ccfbdaaab31f9e9c221daa59a218279999)

Yes, I think it is (I also double-checked with @erichkeane).

**Comment by tstellar** [comment]
@cor3ntin We can't merge the patch as is, because there are ABI breaking changes to CreateLambda() and createLambdaClosureType().  Is there someway to rework the patch without changing the ABI?

**Comment by cor3ntin** [comment]
@tstellar That seems pretty difficult if not impossible. I guess if we can't backport this, we might need to consider reverting https://reviews.llvm.org/rG22aa3680eaccb9b77ca224711c4da3a354aa2d45 in the 14x branche instead, would that be possible?

The state of affair in the 14 branch is pretty sad, as it crashes on very simple and non unusual code, like
https://godbolt.org/z/P3qPorsq1, such that having that commit in is likely to do more harm that good (to the extent that users use C++20 features).

What would be the process for that?

**Comment by tstellar** [comment]
@AaronBallman I'm just talking about the ABI of libclang-cpp.so.  Is there another ABI issue with the code that the complier generates with this patch?

**Comment by tstellar** [comment]
@cor3ntin I think you can fix it by adding an overload of createLambdaClosureType() with the old parameter types and have that wrap the new implementation.
