### ISSUE TITLE
The --print-multiarch option outputs a target triple new in llvm / clang version 13 which seems at odds with gcc

### ISSUE THREAD

**Issue by 98e28c64-05c8-4773-b7e0-0524ce0339cb** [llvm/llvm-project#51458]
|  |  |
| --- | --- |
| Bugzilla Link | [52116](https://llvm.org/bz52116) |
| Version | unspecified |
| OS | MacOS X |
| CC | @debohman,@zygoloid |

## Extended Description 
The new --print-multiarch option to clang outputs a target triple which seems at odds with gcc's behavior and documentation.

The clang-13 documentation says:

-print-multiarch, --print-multiarch

Print the multiarch target triple

The gcc 11.2.0 documentation says:

-print-multiarch

Print the path to OS libraries for the selected multiarch, relative to some lib subdirectory.

It is unclear to me the rationale for the clang-13 behavior. GCC outputs nothing for this option, and clang outputs a target triple. Why the change in clang-13?

This change breaks the configuration of recent Python builds using clang as the compiler.

**Comment by daltenty** [comment]
This seems to be a dup of https://github.com/llvm/llvm-project/issues/51469 and is likely resolved by https://reviews.llvm.org/D133170.
