### ISSUE TITLE
clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz missing LLDB

### ISSUE THREAD

**Issue by kalcutter** [llvm/llvm-project#51463]
|  |  |
| --- | --- |
| Bugzilla Link | [52121](https://llvm.org/bz52121) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
The LLVM 13 binary release `clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz` is missing LLDB.

**Comment by Endilll** [comment]
It is the case (https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz), but I don't think we have the bandwidth to care about a release that happened more than 2 years ago.
