### ISSUE TITLE
[InstSimplify] fold compare of no-wrap subtract

### ISSUE THREAD

**Issue by rotateright** [llvm/llvm-project#51477]
|  |  |
| --- | --- |
| Bugzilla Link | [52135](https://llvm.org/bz52135) |
| Version | trunk |
| OS | All |
| CC | @RKSimon |

## Extended Description 
Noticed in https://reviews.llvm.org/rGda210f5d3425 :

define i1 @&#8203;test_negative_combined_sub_signed_overflow(i8 %x) {
  %y = sub nsw i8 127, %x
  %z = icmp slt i8 %y, -1
  ret i1 %z
}

This is always false.

define i1 @&#8203;test_negative_combined_sub_unsigned_overflow(i64 %x) {
  %y = sub nuw i64 10, %x
  %z = icmp ult i64 %y, 11
  ret i1 %z
}

This is always true.

--------------------------------------------------------------------------

-instcombine will now handle those transforms in multiple steps, but it won't work if the subtract has an extra use. 

This should be added to -instsimplify, so we don't have that limitation, and the analysis can be used by other passes. 

The transforms should not be limited to "less-than" predicates. The check might be implemented with a ConstantRange or an overflow check on constant math.

**Comment by hasyimibhar** [comment]
Potential fix: https://reviews.llvm.org/D115459

**Comment by nikic** [comment]
This is already implemented: https://llvm.godbolt.org/z/1fsdh3dPh
