### ISSUE TITLE
Failure to vectorize accumulation when result is stored in memory

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#51470]
|  |  |
| --- | --- |
| Bugzilla Link | [52128](https://llvm.org/bz52128) |
| Version | trunk |
| OS | Linux |
| CC | @davidbolvansky,@rotateright |

## Extended Description 
void mac(const int *b, int *sum)
{
  int dotp = 0;
  for (int i = 0; i < 32; i++)
    dotp += b[i];

  *sum = dotp;
}

This is not vectorized, but could be. This is done by GCC, but not by LLVM.

PS: Oddly, this can easily be changed to vectorize, but only by making it so `dotp` is returned instead of stored into memory.

**Comment by fhahn** [comment]
This is now vectorized on current `main`: https://clang.godbolt.org/z/neobsMj1W
