### ISSUE TITLE
[X86] Failure to produce chained PAVG's

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#51473]
|  |  |
| --- | --- |
| Bugzilla Link | [52131](https://llvm.org/bz52131) |
| Version | trunk |
| OS | Linux |
| CC | @abadams,@topperc,@RKSimon,@phoebewang,@rotateright |

## Extended Description 
As noted in https://github.com/halide/Halide/pull/6302

https://godbolt.org/z/9nY77r35q

Haven't really looked at what is actually going wrong yet,
just documenting.

**Comment by RKSimon** [comment]
This was fixed by https://reviews.llvm.org/D111571 / 5f4f5da634ce196210c47ddf3d3a011c4c7e254f - any additional handling can be added after #92096
