### ISSUE TITLE
Implement -load_hidden

### ISSUE THREAD

**Issue by calebzulawski** [llvm/llvm-project#51505]
|  |  |
| --- | --- |
| Bugzilla Link | [52163](https://llvm.org/bz52163) |
| Version | 12.0 |
| OS | MacOS X |
| CC | @smithp35 |

## Extended Description 
I use this option on macOS with ld64 and would like to use it with LLD instead.

From the manpage:

     -load_hidden path_to_archive
                 Uses specified static library as usual, but treats all global symbols from the static library to as if they are visibility hidden.  Useful when building a dynamic library that uses a static library but does not want to export
                 anything from that static library.

**Comment by BertalanD** [comment]
https://reviews.llvm.org/D130473
