### ISSUE TITLE
Using  -fsanitize=undefined with -static segfault the binary

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#51538]
|  |  |
| --- | --- |
| Bugzilla Link | [52196](https://llvm.org/bz52196) |
| Version | unspecified |
| OS | Linux |
| CC | @Kojoley |

## Extended Description 
With

-- foo.cpp --
```cpp
int main() {
	return 0;
}
```
```console
$ clang-14 -static -fsanitize=undefined foo.cpp -lstdc++ && ./a.out
segmentation fault  ./a.out
```

With gcc
```console
$ gcc-10 -static -fsanitize=undefined foo.cpp -lstdc++ && ./a.out && echo $?
0
```

**Comment by bruno-kakele** [comment]
Can confirm: it works only with `-fsanitize-minimal-runtime`

**Comment by MaskRay** [comment]
Perhaps we should add `UbsanDoesNotSupportStaticLinkage` to create an artificial reference on `_DYNAMIC` for ELF targets to ensure that `-static -fsanitize=undefined` leads to a linker error.
