### ISSUE TITLE
[mlir-tblgen/ods] Invalid printer generated when using kEmitAccessorPrefix_Prefixed

### ISSUE THREAD

**Issue by maerhart** [llvm/llvm-project#51544]
|  |  |
| --- | --- |
| Bugzilla Link | [52202](https://llvm.org/bz52202) |
| Version | unspecified |
| OS | Linux |
| CC | @jpienaar,@River707 |

## Extended Description 
Hi all,

Mlir-tblgen generates an invalid printer because it does not consider the chosen format of the accessors as introduced in https://reviews.llvm.org/D111033

I'm only using the prefixed format (not both).

E.g., when having an operation with an argument called `$value` then the accessor is called `getValue()` but the generated printer (when using an assemblyFormat) calls `value()`.

Bigger example printer:
```
void ExampleOp::print(::mlir::OpAsmPrinter &p) {
  p << ' ';
  p << value();
  p << ",";
  p << ' ';
  p.printAttributeWithoutType(indexAttr());
  p.printOptionalAttrDict((*this)->getAttrs(), /*elidedAttrs=*/{"index"});
  p << ' ' << ":";
  p << ' ';
  p << ::llvm::ArrayRef<::mlir::Type>(value().getType());
  p << ' ' << "->";
  p << ' ';
  p << ::llvm::ArrayRef<::mlir::Type>(result().getType());
}
```
used assembly format:
```
  let assemblyFormat = [{
    $value `,` $index attr-dict `:` type($value) `->` type($result)
  }];
```

Position in code: OpFormatGen.cpp line 1646 onwards. Not sure if this also happens at other places.

Best regards,
Martin

**Comment by jpienaar** [comment]
I believe this has been fixed, please reopen if not.
