### ISSUE TITLE
Adding char const * and std::string  with -DLIBCPP_DEBUG yields segfault

### ISSUE THREAD

**Issue by eike-fokken** [llvm/llvm-project#51551]
|  |  |
| --- | --- |
| Bugzilla Link | [52209](https://llvm.org/bz52209) |
| Version | 11.0 |
| OS | Linux |
| Attachments | [full stack trace of the segfault](https://user-images.githubusercontent.com/95090436/143762647-a40ea482-94bb-4097-a260-07d9ddee8d82.gz) |
| CC | @mclow |

## Extended Description 

Compiling the following with clang++ -DLIBCPP_DEBUG -stdlib=libc++

```c++
#include <iostream>

int main() {
  std::pair<bool, double> minimum_{true, 1};

  std::cerr << "instance is below minimum of " + std::to_string(minimum_.second)
            << "\n";

  return 0;
}
```

and executing yields a segfault. g++ or clang++ with libstdc++ instead output the expected:

```sh
instance is below minimum of 1.000000
```

I've added a full stack trace.

See also https://github.com/pboettch/json-schema-validator/issues/177
Hope it helps!

**Comment by philnik777** [comment]
`std::to_string` doesn't tag the string properly if the dylib isn't build with the debug-mode enabled. Running the debug-mode without a debug-dylib isn't a supported configuration anymore, so I'm closing it.
