### ISSUE TITLE
Missing register aliases for AVR for compatibility with gcc-avr's inline assembly

### ISSUE THREAD

**Issue by maribu** [llvm/llvm-project#51557]
|  |  |
| --- | --- |
| Bugzilla Link | [52215](https://llvm.org/bz52215) |
| Version | 12.0 |
| OS | other |

## Extended Description 
E.g. the avr-libc but also other AVR code written for gcc-avr heavily uses the following aliases:

__tmp_reg__
__SREG__
__zero_reg__
__SP_H__
__SP_L__

also the aliases __RAMPZ__ and __EIND__ are occasionally used.

See [1] for their definitions.

This is the first time I looked into the LLVM source code, so I might be talking nonsense here. I tried to fix this by amending lib/Target/AVR/AVRRegisterInfo.td like this:

-def R0  : AVRReg<0,  "r0">,  DwarfRegNum<[0]>;
-def R1  : AVRReg<1,  "r1">,  DwarfRegNum<[1]>;
+def R0  : AVRReg<0,  "r0", [], ["__tmp_reg__"]>,  DwarfRegNum<[0]>;
+def R1  : AVRReg<1,  "r1", [], ["__zero_reg__"]>,  DwarfRegNum<[1]>;

etc. - but to no avail.

I also tried to just emit assignments for the alias via `void AVRAsmPrinter::emitStartOfAsmFile(Module &M)`, but this didn't work for me either.

I think that adding the aliases should be relatively trivial for someone with same basic understanding of the LLVM code - which I sadly lack.

Also note that according to [1] the AVRtiny family has a different mapping (e.g. __tmp_reg__ usually is r0, but on AVRtiny it is r16).

https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=libgcc/config/avr/lib1funcs.S;h=ac101b49f03e340e93e16283eb47146ef47290c2;hb=HEAD

**Comment by benshi001** [comment]
This issue is fixed in https://reviews.llvm.org/D119807,

It needs someone to approve.

**Comment by tstellar** [comment]
This issue was not resolved in time for 14.0.0 and will need to be fixed in the next release (14.0.1).  If you disagree with this or you feel there was a mistake, please change the milestone back to 'LLVM 14.0.0 Release' so we can discuss.

**Comment by benshi001** [comment]
> ed in time for 14.0.0 and will need to be fixed in the next release (14.0.1). If you disagree with

Can anybody help me review it? The code owner of AVR and other AVR contributors do not give me any feedback. Actually this is a simple change.

**Comment by benshi001** [comment]
fixed and committed as https://github.com/llvm/llvm-project/commit/d7afea9eb84274a4c5046253f4d78a8fdd262803

**Comment by benshi001** [comment]
This is a feature, so no need to back port.

**Comment by tstellar** [comment]
@benshi001 Ok.
