### ISSUE TITLE
Casting.h:269: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::FixedVectorType; Y = llvm::VectorType; typename llvm::cast_retty<X, Y*>::ret_type = llvm::FixedVectorType*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompa

### ISSUE THREAD

**Issue by f67703c9-448b-4bbf-aeb5-5554a97140f6** [llvm/llvm-project#51550]
|  |  |
| --- | --- |
| Bugzilla Link | [52208](https://llvm.org/bz52208) |
| Version | trunk |
| OS | All |
| Attachments | [The main program](https://user-images.githubusercontent.com/95090437/143762645-f5587f8e-cfaa-41b8-ad0a-e801ca59d915.gz), [The script](https://user-images.githubusercontent.com/95090437/143762646-2e4abde6-d564-4bf5-86a7-e645ea95b602.gz) |

## Extended Description 

Error:
clang++: /data/neil/llvm-project/llvm/include/llvm/Support/Casting.h:269: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::FixedVectorType; Y = llvm::VectorType; typename llvm::cast_retty<X, Y*>::ret_type = llvm::FixedVectorType*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.

Stack dump:
0.	Program arguments: /data/neil/llvm-project/build/bin/clang++ -Wall --gcc-toolchain=/data/phil/riscv-rv64g/ --sysroot=/data/phil/riscv-rv64g/sysroot/usr --target=riscv64-unknown-linux-gnu -march=rv64gv0p10 -O3 -ffast-math -fno-math-errno -DENABLE_AUTOVEC -menable-experimental-extensions -mllvm -scalable-vectorization=on -Rpass-analysis=loop-vectorize -c pathfinder.cpp -o autovec
1.	<eof> parser at end of file
2.	Optimizer
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
/data/neil/llvm-project/build/bin/clang++(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamEi+0x36)[0x542da7d]
/data/neil/llvm-project/build/bin/clang++[0x542db34]
/data/neil/llvm-project/build/bin/clang++(_ZN4llvm3sys17RunSignalHandlersEv+0x7f)[0x542bafb]
/data/neil/llvm-project/build/bin/clang++(_ZN4llvm3sys15CleanupOnSignalEm+0x6f)[0x542d3dc]
/data/neil/llvm-project/build/bin/clang++[0x536a8fe]
/data/neil/llvm-project/build/bin/clang++[0x536adaa]
/lib64/libpthread.so.0(+0xf630)[0x7f094b98b630]
/lib64/libc.so.6(gsignal+0x37)[0x7f094a578387]
/lib64/libc.so.6(abort+0x148)[0x7f094a579a78]
/lib64/libc.so.6(+0x2f1a6)[0x7f094a5711a6]
/lib64/libc.so.6(+0x2f252)[0x7f094a571252]
/data/neil/llvm-project/build/bin/clang++[0x241266c]
/data/neil/llvm-project/build/bin/clang++[0x368a911]
/data/neil/llvm-project/build/bin/clang++[0x3686cd9]
/data/neil/llvm-project/build/bin/clang++(_ZNK4llvm19TargetTransformInfo14getShuffleCostENS0_11ShuffleKindEPNS_10VectorTypeENS_8ArrayRefIiEEiS3_+0x67)[0x40d9ded]
/data/neil/llvm-project/build/bin/clang++(_ZN4llvm26LoopVectorizationCostModel19getUniformMemOpCostEPNS_11InstructionENS_12ElementCountE+0x134)[0x561c290]
/data/neil/llvm-project/build/bin/clang++(_ZN4llvm26LoopVectorizationCostModel28setCostBasedWideningDecisionENS_12ElementCountE+0x305)[0x561e74b]
/data/neil/llvm-project/build/bin/clang++[0x563fc20]
/data/neil/llvm-project/build/bin/clang++(_ZN4llvm24LoopVectorizationPlanner4planENS_12ElementCountEj+0x55b)[0x5621fb9]
/data/neil/llvm-project/build/bin/clang++(_ZN4llvm17LoopVectorizePass11processLoopEPNS_4LoopE+0xc7d)[0x562d1f3]
/data/neil/llvm-project/build/bin/clang++(_ZN4llvm17LoopVectorizePass7runImplERNS_8FunctionERNS_15ScalarEvolutionERNS_8LoopInfoERNS_19TargetTransformInfoERNS_13DominatorTreeERNS_18BlockFrequencyInfoEPNS_17TargetLibraryInfoERNS_12DemandedBitsERNS_9AAResultsERNS_15AssumptionCacheERSt8functionIFRKNS_14LoopAccessInfoERNS_4LoopEEERNS_25OptimizationRemarkEmitterEPNS_18ProfileSummaryInfoE+0x38e)[0x562e5e6]
/data/neil/llvm-project/build/bin/clang++(_ZN4llvm17LoopVectorizePass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE+0x282)[0x562e976]
/data/neil/llvm-project/build/bin/clang++[0x6c40e50]
/data/neil/llvm-project/build/bin/clang++(_ZN4llvm11PassManagerINS_8FunctionENS_15AnalysisManagerIS1_JEEEJEE3runERS1_RS3_+0x15a)[0x49715f0]
/data/neil/llvm-project/build/bin/clang++[0x281a78c]
/data/neil/llvm-project/build/bin/clang++(_ZN4llvm27ModuleToFunctionPassAdaptor3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE+0x1c9)[0x4970ed5]
/data/neil/llvm-project/build/bin/clang++[0x281a6f0]
/data/neil/llvm-project/build/bin/clang++(_ZN4llvm11PassManagerINS_6ModuleENS_15AnalysisManagerIS1_JEEEJEE3runERS1_RS3_+0x15a)[0x497126e]
/data/neil/llvm-project/build/bin/clang++[0x5834efa]
/data/neil/llvm-project/build/bin/clang++(_ZN5clang17EmitBackendOutputERNS_17DiagnosticsEngineERKNS_19HeaderSearchOptionsERKNS_14CodeGenOptionsERKNS_13TargetOptionsERKNS_11LangOptionsEN4llvm9StringRefEPNSE_6ModuleENS_13BackendActionESt10unique_ptrINSE_17raw_pwrite_streamESt14default_deleteISK_EE+0x4bb)[0x5835fa9]
/data/neil/llvm-project/build/bin/clang++[0x6b0fbf7]
/data/neil/llvm-project/build/bin/clang++(_ZN5clang8ParseASTERNS_4SemaEbb+0x37e)[0x840c17c]
/data/neil/llvm-project/build/bin/clang++(_ZN5clang17ASTFrontendAction13ExecuteActionEv+0x141)[0x61865c3]
/data/neil/llvm-project/build/bin/clang++(_ZN5clang13CodeGenAction13ExecuteActionEv+0x57)[0x6b0c7db]
/data/neil/llvm-project/build/bin/clang++(_ZN5clang14FrontendAction7ExecuteEv+0x8b)[0x6185f13]
/data/neil/llvm-project/build/bin/clang++(_ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE+0x36a)[0x60d0e1a]
/data/neil/llvm-project/build/bin/clang++(_ZN5clang25ExecuteCompilerInvocationEPNS_16CompilerInstanceE+0x39d)[0x63075a9]
/data/neil/llvm-project/build/bin/clang++(_Z8cc1_mainN4llvm8ArrayRefIPKcEES2_Pv+0x5d6)[0x23b8277]
/data/neil/llvm-project/build/bin/clang++[0x23ad1a1]
/data/neil/llvm-project/build/bin/clang++[0x5fbbcf3]
/data/neil/llvm-project/build/bin/clang++[0x5fbc24b]
/data/neil/llvm-project/build/bin/clang++[0x5360320]
/data/neil/llvm-project/build/bin/clang++(_ZN4llvm20CrashRecoveryContext9RunSafelyENS_12function_refIFvvEEE+0xc3)[0x536af63]
/data/neil/llvm-project/build/bin/clang++(_ZNK5clang6driver10CC1Command7ExecuteEN4llvm8ArrayRefINS2_8OptionalINS2_9StringRefEEEEEPSsPb+0x1d3)[0x5fbbed1]
/data/neil/llvm-project/build/bin/clang++(_ZNK5clang6driver11Compilation14ExecuteCommandERKNS0_7CommandERPS3_+0x34d)[0x5f71be1]
/data/neil/llvm-project/build/bin/clang++(_ZNK5clang6driver11Compilation11ExecuteJobsERKNS0_7JobListERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0xa1)[0x5f71f13]
/data/neil/llvm-project/build/bin/clang++(_ZN5clang6driver6Driver18ExecuteCompilationERNS0_11CompilationERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0x161)[0x5f80bfb]
/data/neil/llvm-project/build/bin/clang++(main+0xe9f)[0x23ae1fd]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f094a564555]
/data/neil/llvm-project/build/bin/clang++[0x23abb35]
clang-14: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 14.0.0 (/data/neil/llvm-project/clang 64eaffb613d0cb7fa7542fa48281a2e617ad8ee9)
Target: riscv64-unknown-linux-gnu
Thread model: posix
InstalledDir: /data/neil/llvm-project/build/bin

**Comment by junparser** [comment]
see https://reviews.llvm.org/D116362
