### ISSUE TITLE
Failure to compile void{}

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#51552]
|  |  |
| --- | --- |
| Bugzilla Link | [52210](https://llvm.org/bz52210) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid,@xgupta |

## Extended Description
```cpp
void f()
{
    void{};
}
```

This has been considered valid since http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#2351 was accepted as a DR in 2018, but Clang fails to compile it, with this error:

```console
<source>:3:9: error: illegal initializer type 'void'
    void{};
        ^
```

**Comment by frederick-vs-ja** [comment]
Fixed by #78060.
