### ISSUE TITLE
[Modules] Non-exported aliased type used through exported type alias is not reachable

### ISSUE THREAD

**Issue by 976866b7-fc02-4d23-a1c0-197b08fd7c0e** [llvm/llvm-project#51623]
|  |  |
| --- | --- |
| Bugzilla Link | [52281](https://llvm.org/bz52281) |
| Version | trunk |
| OS | Linux |
| CC | @JohelEGP,@zygoloid |

## Extended Description 
See https://godbolt.org/z/qzd1aaqP3

mod.cpp:
```C++
export module mod;
struct t { };
export using u = t;
```

test.cpp:
```C++
import mod;
int main() {
  u v{};
}
```

Output:
```
test.cpp:3:5: error: definition of 't' must be imported from module 'mod' before it is required
  u v{};
    ^
mod.cpp:2:8: note: definition here is not reachable
struct t { };
       ^
```

With templates: https://godbolt.org/z/81f3ocjfW.

**Comment by ChuanqiXu9** [comment]
This should be fixed in https://github.com/llvm/llvm-project/commit/9c04851cf5809c80862183481f8ced0b3e9ee301
