### ISSUE TITLE
Generalize sparse_tensor.new beyond just filename pointer (intermediate level starter)

### ISSUE THREAD

**Issue by aartbik** [llvm/llvm-project#51648]
|  |  |
| --- | --- |
| Bugzilla Link | [52306](https://llvm.org/bz52306) |
| Version | unspecified |
| OS | Linux |
| CC | @joker-eph |

## Extended Description 
Generalize the abstractions to initialize sparse tensors. Right now we have the “sparse_tensor.new” operator, which is intended to be the “Swiss army knife” for materializing sparse tensors from code or external formats. Right now, the value passed to this operator is interpreted as a filename pointer. However, we could come up with other ways of initializing sparse tensors using this operator, e.g. by attaching a block of code that fills the values. That code could e.g. fill particular regions like bands or diagonals with deterministic or random values, or pick a random structure based on a given sparsity factor (viz. 99% sparse).

(note that we also have sparse_tensor.convert which is great to construct sparse tensors from constants, so that feature has been taken care of).

**Comment by Gxiandy** [comment]
Hi Aart,
I would like to start on this task. 

I have read the source code of SparseTensorNewConverter and SparseTensorReader. My first thought to implement the `code block initialization` you metioned above is to add new constructor&readXXX methods in the SparseTensorReader class, and there might be an function pointer of the initialization code in the arguments list of these new constructor&read methods.

But there are some questions that confuse me:
(1)  Who implements these initialization code blocks? Us？Or the users?
(2)  If we allows users to implement these code blocks? How and whese do they define them?
(3) What should these initialization functions look like？A function to fill the whole tensor(with 0 and other interesting value)? Or just to fill some interseting region? 

Thank you,
Ding

**Comment by aartbik** [comment]
Discusses this a bit more offline. The new "from file" and convert "from constant" are already done, so this would involve something along the lines of "tensor.generate" (either [re]using that op for sparse operands, or defining a new op in the sparse tensor dialect).

**Comment by aartbik** [comment]
We have many different ways of materializing sparse tensors now, including the assemble/disassemble (aka pack/unpack) ops. So this tracker is no longer needed.
