### ISSUE TITLE
Refactor file I/O in sparse runtime support library (medium level starter)

### ISSUE THREAD

**Issue by aartbik** [llvm/llvm-project#51647]
|  |  |
| --- | --- |
| Bugzilla Link | [52305](https://llvm.org/bz52305) |
| Version | unspecified |
| OS | Linux |
| CC | @joker-eph |

## Extended Description 
The sparse compiler currently uses a “one size fits all” sparse runtime support library (in lieu of elaborate codegen for those parts, which could be an alternative approach).

The code lives at:

https://github.com/llvm/llvm-project/blob/main/mlir/lib/ExecutionEngine/SparseUtils.cpp

Right now, the file I/O part of this is really hardcoded (viz. fgets). It would be nice to refactor some of the file I/O parts out into proper read/write classes so that it is easier to "inject" tests that read from memory instead of external files.

Note that we also have setup methods from MLIR constants. Perhaps some parts can be shared with proper refactoring.

**Comment by SamanKazemkhani** [comment]
Hi @aartbik, I'm interested in taking on this task to familiarize myself with sparse tensors in MLIR.

According to your [recent update](https://discourse.llvm.org/t/mlir-sparse-compiler-progress/60479/7), the runtime library supporting sparse tensors is being replaced with codegen. Does that initiative render this task defunct?

**Comment by aartbik** [comment]
Thanks for bringing this to my attention. Indeed, we have codegen besides library support now, but we plan to have both co-exist for a while. But the refactoring alluded to in this bug is a bit outdated, so closing this tracker.
