### ISSUE TITLE
lambda in unevaluated-context is parsed incorrectedly

### ISSUE THREAD

**Issue by nickhuang99** [llvm/llvm-project#51641]
|  |  |
| --- | --- |
| Bugzilla Link | [52299](https://llvm.org/bz52299) |
| Version | trunk |
| OS | Linux |
| CC | @AaronBallman,@zygoloid |

## Extended Description 
The following code is accepted incorrectly by clang while GCC and MSVC++ all spot the failure of assertion. The type of "foo<int>" is obviously NOT "void" at all.

template<class T>
void foo(decltype(+[](T){}) lambda, T param);

static_assert(__is_same(decltype(foo<int>), void));

**Comment by tstellar** [comment]
@AaronBallman Is this safe to backport? https://github.com/llvm/llvm-project/commit/3784e8ccfbdaaab31f9e9c221daa59a218279999

**Comment by AaronBallman** [comment]
> @AaronBallman Is this safe to backport? [3784e8c](https://github.com/llvm/llvm-project/commit/3784e8ccfbdaaab31f9e9c221daa59a218279999)

I believe it is safe to backport (I also double-checked with @erichkeane).

**Comment by tstellar** [comment]
The backport of https://github.com/llvm/llvm-project/commit/3784e8ccfbdaaab31f9e9c221daa59a218279999 was also requested in https://github.com/llvm/llvm-project/issues/51416 , so I'm dropping the release milestone from this issue. We'll track the progress in https://github.com/llvm/llvm-project/issues/51416.
