### ISSUE TITLE
Implement reductions in parallel loops (easy starter)

### ISSUE THREAD

**Issue by aartbik** [llvm/llvm-project#51654]
|  |  |
| --- | --- |
| Bugzilla Link | [52312](https://llvm.org/bz52312) |
| Version | unspecified |
| OS | Linux |
| CC | @joker-eph |

## Extended Description 
Support parallel reductions. Currently only vector loops support reductions, but forall loops (viz. scf::ParallelOp ) can deal with reductions too.

Relevant entry point: isParallelFor() method in https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/SparseTensor/Transforms/Sparsification.cpp

**Comment by aartbik** [comment]
Removing these flags is of course the first step, but the existing infrastructure will not just simply take care of the rest, since you will end up with a parallel loop construct that has a loop-carried dependence.  Please have a look at the ParallelOp in the SCF dialect, in particular the scf.reduce/return constructs to see what else is required.

**Comment by PeimingLiu** [comment]
I can try to take a look at it.

**Comment by PeimingLiu** [comment]
Checkout https://reviews.llvm.org/D135927

**Comment by aartbik** [comment]
Completed by Peiming.
