### ISSUE TITLE
target-features are not preserved in LTO object files that contain no functions

### ISSUE THREAD

**Issue by sbc100** [llvm/llvm-project#51680]
|  |  |
| --- | --- |
| Bugzilla Link | [52338](https://llvm.org/bz52338) |
| Version | trunk |
| OS | Linux |

## Extended Description 
LLVM target features are attached to functions, so if there are no functions in a given TU then the resulting LTO object file will not include any target-features.

For native object files problem does not occurs.

The problem arrises, for example, in emscripten when one does 

```
$ emcc -s SIDE_MODULE -O2 -fPIC empty.c
wasm-ld: error: mutable global imported but 'mutable-globals' feature not present in inputs: `__stack_pointer`. Use --no-check-features to suppress.
```

This is because clang injects the mutable-globals features when `RelocationModel == llvm::Reloc::PIC_`, but when there is no function in the object file this information is lost, and then when the LTO/bitcode object is compiled it lacks this feature.

**Comment by tlively** [comment]
Somehow imported as a dup of #51681.
