### ISSUE TITLE
wasm64: Crash with register use before def

### ISSUE THREAD

**Issue by alexcrichton** [llvm/llvm-project#51694]
|  |  |
| --- | --- |
| Bugzilla Link | [52352](https://llvm.org/bz52352) |
| Version | trunk |
| OS | All |
| Attachments | [bugpoint-reduced IR](https://user-images.githubusercontent.com/92601335/143762672-332bad55-9e80-430f-adad-ffdebcab8847.gz), [original IR](https://user-images.githubusercontent.com/92601335/143762673-45a551d9-b032-44cf-b63d-16594e23c2b1.gz) |
| CC | @aardappel,@dschuff |

## Extended Description 

I apologize in advance for the bad title here. In an effort to test out Rust on the wasm64 backend I was curious to test out the performance of a wasm32-vs-wasm64 program and the first thing I was going to test was a wasm program that itself implements a wasm text parser. In compiling this program though (Rust source code) I got a crash in LLVM:

llc: /home/acrichto/code/rust/src/llvm-project/llvm/lib/CodeGen/MachineLoopInfo.cpp:199: bool llvm::MachineLoop::isLoopInvariant(llvm::MachineInstr&) const: Assertion `MRI->getVRegDef(Reg) && "Machine instr not mapped for this vreg?!"' failed.

Using bugpoint on the suspect LLVM module I was able to reduce the original test case but it unfortunately gives a different crash now:

llc: /home/acrichto/code/rust/src/llvm-project/llvm/lib/CodeGen/LiveVariables.cpp:129: void llvm::LiveVariables::HandleVirtRegUse(llvm::Register, llvm::MachineBasicBlock*, llvm::MachineInstr&): Assertion `MRI->getVRegDef(Reg) && "Register use before def!"' failed.

In any case this seemed like a good point to open up a bug. I've attached both the un-minimized module as well as the bugpoint-reduced module here in case fixing the bugpoint issue is distinct from the original issue.

**Comment by aardappel** [comment]
I assume this is fixed.
