### ISSUE TITLE
code coverage ignores lines after assert(...)

### ISSUE THREAD

**Issue by hanickadot** [llvm/llvm-project#51706]
|  |  |
| --- | --- |
| Bugzilla Link | [52364](https://llvm.org/bz52364) |
| Version | 13.0 |
| OS | All |
| Attachments | [minimal example](https://user-images.githubusercontent.com/93352303/143762678-a3cd76e0-a2f1-4fc6-9ba1-d71563c6a963.gz) |
| CC | @dwblaikie,@zygoloid |

## Extended Description 

Hi I noticed an error in clang-13 code coverage reporting.

If you follow these steps:

```
clang test.c -fprofile-instr-generate -fcoverage-mapping -g -O0 -DDEBUG -o test

./test

llvm-profdata merge -sparse ./default.profraw -o ./test.profdata

llvm-cov show ./test -instr-profile=./test.profdata
```

The resulting coverage report is:
```
    1|       |#include <assert.h>
    2|       |#include <stdio.h>
    3|       |
    4|      1|int main() {
    5|      1|	assert(1);
    6|      0|	puts("not covered"); // line after assert is not covered
    7|      1|	puts("covered");
    8|      1|	assert(1);
    9|      0|	puts("not covered"); // line after assert is not covered
   10|      1|	assert(1);
   11|      0|	assert(1); // line after assert is not covered
   12|      0|	puts("not covered"); // line after assert is not covered
   13|      1|}
```

as you can see all lines after an `assert(...)` are ignored, this is a regression as clang-12 doesn't have this behaviour

**Comment by dtellenbach** [comment]
This is the same as https://github.com/llvm/llvm-project/issues/59030 and has been fixed in https://github.com/llvm/llvm-project/commit/94dd4766a61bb18b263415e17e745dc2fa609162.
