### ISSUE TITLE
Kaleidoscope-Ch4 is not working as expected and is missing documentation

### ISSUE THREAD

**Issue by yarlB** [llvm/llvm-project#51723]
|  |  |
| --- | --- |
| Bugzilla Link | [52381](https://llvm.org/bz52381) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie,@lhames,@xgupta |

## Extended Description 
First, according to the tutorial, we should be able to do
    ready> def foo(x) x + 1;
    ready> foo(2);
    Evaluated to 3.000000

    ready> def foo(x) x + 2;
    ready> foo(2);
    Evaluated to 4.000000

but if I try this (I compiled llvm with examples):
    sh-5.1$ ./Kaleidoscope-Ch4
    ready> def foo(x) x + 1;
    ready> Read function definition:define double @&#8203;foo(double %x) {
    entry:
      %addtmp = fadd double %x, 1.000000e+00
      ret double %addtmp
    }

    ready> def foo(x) x + 2;
    ready> Read function definition:define double @&#8203;foo(double %x) {
    entry:
      %addtmp = fadd double %x, 2.000000e+00
      ret double %addtmp
    }

    Duplicate definition of symbol 'foo'
    sh-5.1$

Second, this line https://github.com/llvm/llvm-project/blob/052a2913f5ced0d266e946f1e697815df1d1fcc0/llvm/examples/Kaleidoscope/Chapter4/toy.cpp#L612 in the full code listing is not present on its corresponding snippet and thus, not explained.

Thank you!

**Comment by PatriotRossii** [comment]
It' specific of OrcV2 JIT. It doesn't allows duplicate symbols in separate modules:

https://discourse.llvm.org/t/duplicate-symbols-in-separate-modules-no-longer-allowed/1805

**Comment by xgupta** [comment]
Documentation is updated by this patch https://reviews.llvm.org/D130613 and it is committed in https://github.com/llvm/llvm-project/commit/fdc950958ed0970159071cc4367a66149971586f
