### ISSUE TITLE
Implement `--icf=safe` using addrsig tables

### ISSUE THREAD

**Issue by int3** [llvm/llvm-project#51756]
|  |  |
| --- | --- |
| Bugzilla Link | [52414](https://llvm.org/bz52414) |
| Version | unspecified |
| OS | All |
| CC | @gkmhub,@int3,@smeenai |

**Comment by BertalanD** [comment]
Implemented in https://github.com/llvm/llvm-project/commit/e29dc0c6fde284e7f05aa5f45b05c629c9fad295.

**Comment by int3** [comment]
It doesn't really work right yet though, see discussion in https://discourse.llvm.org/t/problems-with-mach-o-address-significance-table-generation/63392/9
