### ISSUE TITLE
[M68k] Unused tablegen template args warnings

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#51775]
|  |  |
| --- | --- |
| Bugzilla Link | [52433](https://llvm.org/bz52433) |
| Version | trunk |
| OS | Windows NT |
| CC | @glaubitz,@mshockwave,@ricky26 |

## Extended Description 
https://reviews.llvm.org/D109359 enabled warnings for unused tablegen template args

M68k has a large number of these warnings that need fixing.

**Comment by RKSimon** [comment]
#d2b68c4476162d20cea850d1105eba4a17e62496 fixes the warnings in M68kInstrControl.td

**Comment by mshockwave** [comment]
Thank you @RKSimon ! I was going to fix this as part of #48136 .

**Comment by RKSimon** [comment]
c64ffa22d143fc58858bdb1105a22a5fc73ad26e fixed the warnings in M68kInstrArithmetic.td

**Comment by RKSimon** [comment]
all tablegen warnings are now fixed
