### ISSUE TITLE
[mlir] "Deprecate" StructAttr

### ISSUE THREAD

**Issue by Mogball** [llvm/llvm-project#51799]
|  |  |
| --- | --- |
| Bugzilla Link | [52457](https://llvm.org/bz52457) |
| Version | unspecified |
| OS | All |
| CC | @joker-eph,@jpienaar,@River707 |

## Extended Description 
StructAttr is inefficient, because values are stored as attributes inside a DictionaryAttr. With the introduction of Attribute formats, most uses of StructAttr can be replaced with an AttrDef.

StructAttr still has some useful properties - because everything is an attribute, introspection is possible. To "deprecate" will be to remove uses of StructAttr that do not benefit from/need this feature.

**Comment by joker-eph** [comment]
Is it completed? Or what's the current state?

**Comment by Mogball** [comment]
`StructAttr` was removed.

**Comment by EugeneZelenko** [comment]
@Mogball: Could you please provide commit hash?

**Comment by Mogball** [comment]
d883a02a7c2bb89000d0685749f062c9206ac40c
