### ISSUE TITLE
Support P1689 dependency format

### ISSUE THREAD

**Issue by mathstuf** [llvm/llvm-project#51792]
|  |  |
| --- | --- |
| Bugzilla Link | [52450](https://llvm.org/bz52450) |
| Version | unspecified |
| OS | All |
| CC | @zygoloid |

## Extended Description 
Clang should support the P1689 dependency format for modules:

    https://wg21.link/p1689

I have a patch to GCC (https://github.com/mathstuf/cxx-modules-sandbox/blob/docker/trtbd.diff) to submit that uses the following command line flags:

`-fdep-format=` The format to write dependency information out in. Currently, it uses `trtbd` which stands for "TR to be determined", but bikeshedding needs to commence at some point I suppose. Ideas: `p1689`, `tr2222` (the SG15 TR reserved number).

`-fdep-output=` is the name of the primary output for the future compilation (the `-o` the real compile will see). This is analogous to `-MT`.

`-fdep-file=` is the file to write the information to.

**Comment by krayfaus** [comment]
Any update on this?

Sorry to bump, but I've searched and couldn't find anything other than this issue regarding the support of P1689 on Clang.

**Comment by mathstuf** [comment]
I've started plumbing the flags through and have them mostly working locally (the plumbing is laid down but there are clogs/hookups that need dealt with yet). However, there needs to be a new mode added to make the dependency mechanisms get the information necessary to where it can be output (that is, abusing `-E` is not suitable). That requires more LLVM/Clang knowledge than I have right now.

FWIW, GCC is in the same boat for any header imports but name-only modules at least work there (with my patch).

**Comment by ChuanqiXu9** [comment]
> 

May I ask if there is any update? Or if there is anything that other developers could help?

**Comment by aaronmondal** [comment]
#57293
