### ISSUE TITLE
[mlir][ods] Deprecate StrEnumAttr / BitEnumAttr

### ISSUE THREAD

**Issue by joker-eph** [llvm/llvm-project#51794]
|  |  |
| --- | --- |
| Bugzilla Link | [52452](https://llvm.org/bz52452) |
| Version | unspecified |
| OS | All |
| CC | @jpienaar,@River707 |

## Extended Description 
These predate the AttrDef infrastructure, and to some extent are redundant with it.
StrEnumAttr in particular store an enum as a StringAttr, which seems highly inefficient: it seems that the conversion to string would better be handled at the parse/print boundary rather than materializing these in-memory.

We should try to replace existing users of these with AttrDef-based attributes, and deprecate the two constructs when we're satisfied with the result.

**Comment by Mogball** [comment]
`StrEnumAttr` has been purged from the MLIR core codebase. Its removal is upcoming.

**Comment by joker-eph** [comment]
Any update on the current state of things?

**Comment by Mogball** [comment]
I know there were some recent changes to BitEnumAttr that might have made it possible to remove.

**Comment by Mogball** [comment]
StrEnumAttr is gone, but BitEnumAttr is not. Given that BitEnumAttr has *grown* since this issue was created, I'm just going to close it for now...
