### ISSUE TITLE
Clang failed to compile LLVM IR file to executable

### ISSUE THREAD

**Issue by f081691f-7427-4774-929b-915052056f3d** [llvm/llvm-project#51801]
|  |  |
| --- | --- |
| Bugzilla Link | [52459](https://llvm.org/bz52459) |
| Version | 11.0 |
| OS | Windows NT |

## Extended Description 
Run script: 
# Crash reproducer for clang version 11.0.1
# Driver args: "--driver-mode=g++" "-g" "-O0" "qir_driver_simple.cpp" "Development.ll" "-I" "./" "-L./" "-lMicrosoft.Quantum.Qir.Runtime" "-lMicrosoft.Quantum.Qir.Qsharp.Core" "-lMicrosoft.Quantum.Qir.QSharp.Foundation" "-o" "dev-driven.exe"
# Original command:  "C:\\Program Files\\LLVM\\bin\\clang++.exe" "-cc1" "-triple" "x86_64-pc-windows-msvc19.29.30136" "-emit-obj" "-mrelax-all" "-mincremental-linker-compatible" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "Development.ll" "-mrelocation-model" "pic" "-pic-level" "2" "-mframe-pointer=none" "-fmath-errno" "-fno-rounding-math" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-gno-column-info" "-gcodeview" "-debug-info-kind=limited" "-resource-dir" "C:\\Program Files\\LLVM\\lib\\clang\\11.0.1" "-O0" "-fdebug-compilation-dir" "C:\\Users\\t-ryanmoreno\\source\\repos\\MorenoRyan2021\\Testing" "-ferror-limit" "19" "-fmessage-length=204" "-fno-use-cxa-atexit" "-fms-extensions" "-fms-compatibility" "-fms-compatibility-version=19.29.30136" "-fdelayed-template-parsing" "-fcolor-diagnostics" "-faddrsig" "-o" "C:\\Users\\T-RYAN~1\\AppData\\Local\\Temp\\Development-6641d6.o" "-x" "ir" "Development.ll"
 "C:\\Program Files\\LLVM\\bin\\clang++.exe" "-cc1" "-triple" "x86_64-pc-windows-msvc19.29.30136" "-emit-obj" "-mrelax-all" "-mincremental-linker-compatible" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "Development.ll" "-mrelocation-model" "pic" "-pic-level" "2" "-mframe-pointer=none" "-fmath-errno" "-fno-rounding-math" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-gno-column-info" "-gcodeview" "-debug-info-kind=limited" "-O0" "-ferror-limit" "19" "-fmessage-length=204" "-fno-use-cxa-atexit" "-fms-extensions" "-fms-compatibility" "-fms-compatibility-version=19.29.30136" "-fdelayed-template-parsing" "-fcolor-diagnostics" "-faddrsig" "-x" "ir" "qir_driver_simple-2cc965.cpp"

Stack dump:
0.      Program arguments: C:\Program Files\LLVM\bin\clang++.exe -cc1 -triple x86_64-pc-windows-msvc19.29.30136 -emit-obj -mrelax-all -mincremental-linker-compatible -disable-free -disable-llvm-verifier -discard-value-names -main-file-name Development.ll -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -gno-column-info -gcodeview -debug-info-kind=limited -resource-dir C:\Program Files\LLVM\lib\clang\11.0.1 -O0 -fdebug-compilation-dir C:\Users\t-ryanmoreno\source\repos\MorenoRyan2021\Testing -ferror-limit 19 -fmessage-length=204 -fno-use-cxa-atexit -fms-extensions -fms-compatibility -fms-compatibility-version=19.29.30136 -fdelayed-template-parsing -fcolor-diagnostics -faddrsig -o C:\Users\T-RYAN~1\AppData\Local\Temp\Development-6641d6.o -x ir Development.ll
1.      Code generation
2.      Running pass 'Function Pass Manager' on module 'Development.ll'.
3.      Running pass 'X86 Assembly Printer' on function '@Microsoft__Quantum__Qir__Development__MainFunc__body'
 #&#8203;0 0x00007ff7b52e5d82 C:\Program Files\LLVM\bin\clang++.exe 0x22d5d82 C:\Program Files\LLVM\bin\clang++.exe 0x22d71d2
 #&#8203;1 0x00007ff7b52e5d82 C:\Program Files\LLVM\bin\clang++.exe 0x229739a C:\Program Files\LLVM\bin\clang++.exe 0x228cfba
 #&#8203;2 0x00007ff7b52e5d82 C:\Program Files\LLVM\bin\clang++.exe 0x227f393 C:\Program Files\LLVM\bin\clang++.exe 0xbfde4c
 #&#8203;3 0x00007ff7b52e5d82 C:\Program Files\LLVM\bin\clang++.exe 0x1163e5d C:\Program Files\LLVM\bin\clang++.exe 0x136bf89
 #&#8203;4 0x00007ff7b52e5d82 C:\Program Files\LLVM\bin\clang++.exe 0x1371a23 C:\Program Files\LLVM\bin\clang++.exe 0x136c570
 #&#8203;5 0x00007ff7b52e5d82 C:\Program Files\LLVM\bin\clang++.exe 0x1b5e4ad C:\Program Files\LLVM\bin\clang++.exe 0x3b3c39f
 #&#8203;6 0x00007ff7b52e5d82 C:\Program Files\LLVM\bin\clang++.exe 0x206b572 C:\Program Files\LLVM\bin\clang++.exe 0x203245c
 #&#8203;7 0x00007ff7b52e5d82 C:\Program Files\LLVM\bin\clang++.exe 0x20d1248 C:\Program Files\LLVM\bin\clang++.exe 0x6be8
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
clang++: note: diagnostic msg:

**Comment by Endilll** [comment]
Unfortunately, we can't do much without a reproducer.
Feel free to reopen if you have additional information.
