### ISSUE TITLE
Backport 8f101971b6d54e2fc470e853e413fd01cfff20b5 to 13.0.1

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#51814]
|  |  |
| --- | --- |
| Bugzilla Link | [52472](https://llvm.org/bz52472) |
| Version | unspecified |
| OS | Linux |
| Blocks | llvm/llvm-project#51489  |
| Fixed by commit(s) | 8f101971b6d54e2fc470e853e413fd01cfff20b5 |

**Comment by tstellar** [comment]
@topperc What do you think about backporting this? 8f10197

**Comment by topperc** [comment]
I think this is ok to backport. Any objections @rnk or @phoebewang ?

**Comment by rnk** [comment]
I think it's OK too.

**Comment by tstellar** [comment]
This fix does not apply cleanly to the release branch.  Could someone resolve the merge conflicts and push it to a github fork.

**Comment by tstellar** [comment]
Merged: 19b8368225dc9ec5a0da547eae48c10dae13522d
