### ISSUE TITLE
llc crash due to large structure return

### ISSUE THREAD

**Issue by tclin914** [llvm/llvm-project#51817]
|  |  |
| --- | --- |
| Bugzilla Link | [52475](https://llvm.org/bz52475) |
| Version | trunk |
| OS | Linux |
| CC | @asb,@topperc,@frasercrmck,@tclin914 |

## Extended Description 
Testcase:

define <128 x i32> @&#8203;ret_split_v128i32(<128 x i32>* %x) {
  %v = load <128 x i32>, <128 x i32>* %x
  ret <128 x i32> %v
}

This testcase is extracted from llvm/test/CodeGen/RISCV/rvv/fixed-vectors-calling-conv.ll

Execution command:

llc -mtriple=riscv64 -mattr=+experimental-v -riscv-v-vector-bits-min=128 -riscv-v-fixed-length-vector-lmul-max=4 -pre-RA-sched=list-burr foo.ll --disable-machine-cse test.ll

Change schedule policy for pre-RA to list-burr and disable machine-cse.

Execution result:

Use of %2 does not have a corresponding definition on every path:                                                                                                                    48r %3:gpr = ADDI %2:gpr, 448                                                                                                                                                        LLVM ERROR: Use not jointly dominated by defs.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.                                                                                                Stack dump:
...

I think this bug is that DemoteRegister copied out in return bb doesn't be chained with DemoteRegister copied in in entry bb.

**Comment by frasercrmck** [comment]
Thanks for the bug report! It should now be fixed by b0319ab79bf5. Your hunch was correct: it was an issue with chaining DemoteRegister.
