### ISSUE TITLE
KERN_INVALID_ADDRESS crash with lld but not ld64

### ISSUE THREAD

**Issue by keith** [llvm/llvm-project#51822]
|  |  |
| --- | --- |
| Bugzilla Link | [52480](https://llvm.org/bz52480) |
| Version | unspecified |
| OS | All |
| CC | @gkmhub,@int3,@smeenai,@oontvoo |

## Extended Description 
Here is an iOS sample project https://drive.google.com/file/d/1H1P5BsnfC_Q5Ebd1ddBVMqQ2OWuCAvlH/view

Where the app crashes when exercising some specific codepaths.

Repro steps:

1. The attached project currently links with ld64 and should build + run on the simulator out of the box
2. Launch the app on the simulator and click "Basic map", the map should load fine
3. Change OTHER_LD_FLAGS to point to lld, I was using `--ld-path=/Users/ksmiley/dev/llvm-project/build-dylibs/bin/ld64.lld` for this
4. Repeat 2, but this time it will crash.

Here's a snippet from the crash log:

```
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000030
Exception Codes: 0x0000000000000001, 0x0000000000000030
VM Region Info: 0x30 is not in any region.  Bytes before following region: 4377145296
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      104e5f000-1053e5000    [ 5656K] r-x/r-x SM=COW  ...ogleMapsDemos
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [58739]
```

This could likely be reduced more if needed

**Comment by keith** [comment]
Here's a repro case that shows at least 1 potential case of the issue:

```c
// main.c
#include "include.h"
#include <stdio.h>

static char *foo = "first";

int main(int argc, const char * argv[]) {
    printf("equal? %s\n", foo == bar ? "yes" : "no");
    return 0;
}
```

```c
// include.h
extern char *bar;
```

```c
// include.c
char *bar = "first";
```

```sh
# repro.sh
#!/bin/bash

set -euo pipefail

rm -f /tmp/main

echo "lld no dedup:"
clang --ld-path=build-dyn/bin/ld64.lld main.c -o /tmp/main -Wl,--icf=none include.c
/tmp/main

echo "lld w/ dedup:"
clang --ld-path=build-dyn/bin/ld64.lld main.c -o /tmp/main -Wl,--icf=all include.c
/tmp/main

echo "ld64:"
clang main.c -o /tmp/main include.c
/tmp/main
```

output:

```
lld no dedup:
equal? no
lld w/ dedup:
equal? yes
ld64:
equal? yes
```

The issue here is using `==` for the comparison, but I guess I wouldn't put it past libraries if it works when they tested it!

**Comment by int3** [comment]
@keith do you think we can close this now that https://reviews.llvm.org/D117250 has landed, or would you prefer to keep it around until we figure out how the proposed `--ld64-compat` flag would work?

**Comment by keith** [comment]
Yep happy to close, thanks for the bump, I'm hoping we can avoid that flag anyways
