### ISSUE TITLE
wrong code at -O2 and above on x86_64-linux-gnu (affecting clang-6.0 and above versions)

### ISSUE THREAD

**Issue by haoxintu** [llvm/llvm-project#51837]
|  |  |
| --- | --- |
| Bugzilla Link | [52495](https://llvm.org/bz52495) |
| Version | trunk |
| OS | Linux |
| CC | @josephcsible |

## Extended Description 
Hi all.

I guess the following program is well-defined but makes clang produce wrong code across many versions.

$cat small.c
#include <stdio.h>
#include <stdint.h>

union a {
  int16_t b;
  uint64_t c;
} d;

uint64_t *e = &d.c;
static uint16_t f(int16_t a, int32_t b, uint64_t c);
static int64_t g(int32_t aa, uint8_t h, union a bb) {
  int16_t *i = &d.b;
  f(0, h, 0);
  *i = h;
  return 0;
}
uint16_t f(int16_t a, int32_t b, uint64_t c) {
  for (d.c = 0; 0;)
    ;
  *e = 0;
  return 0;
}

int main() {
  uint32_t j = 8;
  g(1, j, d);
  printf("%d\n", d.b);
  return 0;
}

$clang -w -O1 small.c ; ./a.out
8

$clang -w -O2 small.c ; ./a.out
0

$clang -w -O3 small.c ; ./a.out
0

$clang-5.0 -w -O small.c ; ./a.out
8

Please check more in Godbolt: https://godbolt.org/z/c3YzvYe7a

Thanks,
Haoxin

**Comment by fhahn** [comment]
Still reproduces on current main: https://godbolt.org/z/84x77vvYx

And here for the reduced test case by @josephcsible https://godbolt.org/z/Y9h9Gojzs

**Comment by nikic** [comment]
The program exhibits undefined behavior: While you can type-pun through direct union member access, you cannot type-pun through a pointer to a union member. Both examples work fine with `-fno-strict-aliasing`.
