### ISSUE TITLE
[Support] Request cherry-pick of 7b25fa8c7a15 (Attempt to fix deadlock in ThreadGroup) into 13.x release branch

### ISSUE THREAD

**Issue by nga888** [llvm/llvm-project#51864]
|  |  |
| --- | --- |
| Bugzilla Link | [52522](https://llvm.org/bz52522) |
| Version | 13.0 |
| OS | All |
| Blocks | llvm/llvm-project#51489  |
| Fixed by commit(s) | 7b25fa8c7a15 |

## Extended Description 
I queried whether this should be cherry-picked in https://reviews.llvm.org/D109914 but didn't get much response. Therefore, I assume that the various linked issues do not actually require it for 13.x. However, given than it also relates to llvm/llvm-project#40853  which was "fixed" in 8.x, it feels like it probably should be applied to 13.x.

Thanks,
Andrew

**Comment by tstellar** [comment]
Merged: 87ca22cba2fa
