### ISSUE TITLE
[InstSimplify] missed X==0 fold of bool value

### ISSUE THREAD

**Issue by rotateright** [llvm/llvm-project#51888]
|  |  |
| --- | --- |
| Bugzilla Link | [52546](https://llvm.org/bz52546) |
| Version | trunk |
| OS | All |
| CC | @RKSimon |

## Extended Description 
Forking this off from bug 52543 :

define i1 @&#8203;src(i1 %b) {
  %not = xor i1 %b, true
  %s = sext i1 %not to i32
  %cmp = icmp eq i32 %s, 0
  ret i1 %cmp
}

define i1 @&#8203;tgt(i1 %b) {
  ret i1 %b
}

Note that "opt -instcombine" gets this example, and "opt -instsimplify" gets the sibling fold when the predicate is "ne", but we miss this:
https://alive2.llvm.org/ce/z/vGKMJA

**Comment by hasyimibhar** [comment]
Fixed by https://reviews.llvm.org/D114666.
