### ISSUE TITLE
[clang-cl] Predefine _MSVC_EXECUTION_CHARACTER_SET to the encoding for narrow string literals

### ISSUE THREAD

**Issue by CaseyCarter** [llvm/llvm-project#51891]
|  |  |
| --- | --- |
| Bugzilla Link | [52549](https://llvm.org/bz52549) |
| Version | unspecified |
| OS | Windows NT |
| CC | @RKSimon,@zygoloid |

## Extended Description 
As of VS 2022 17.1 the MSVC compiler will predefine a macro `_MSVC_EXECUTION_CHARACTER_SET` to the codepage corresponding to the encoding used as the ordinary literal encoding (as defined in N4901 [lex.charset]/5). For example, the value `65001` is used for UTF-8, and `1252` for the default English Windows-1252 encoding. It would be nice if clang-cl could also predefine this macro similarly.

If I understand correctly, clang-cl always uses UTF-8 as its ordinary literal encoding (See llvm/llvm-project#40881 ) so this shouldn't be a big ask =)

**Comment by zero9178** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/7ba70d32736aef0c640b9d0e7b9081fc208c81c2
