### ISSUE TITLE
Canonicalizer reversing order of constant ops

### ISSUE THREAD

**Issue by ScottTodd** [llvm/llvm-project#51892]
|  |  |
| --- | --- |
| Bugzilla Link | [52550](https://llvm.org/bz52550) |
| Version | unspecified |
| OS | All |
| CC | @jpienaar,@River707 |

## Extended Description 
When using the default "top down processing enabled" for Canonicalizer's GreedyPatternRewriteDriver, the order of constant ops is reversed with each application of the canonicalize pass:

```mlir
func @&#8203;constantOrdering() -> (i32, i32, i32) {
  %c1 = arith.constant 1 : i32
  %c2 = arith.constant 2 : i32
  %c3 = arith.constant 3 : i32
  return %c1, %c2, %c3 : i32, i32, i32
}
```

Running canonicalize once reverses the ordering:

```
> mlir-opt constant_ordering.mlir -canonicalize

module  {
  func @&#8203;constantOrdering() -> (i32, i32, i32) {
    %c3_i32 = arith.constant 3 : i32
    %c2_i32 = arith.constant 2 : i32
    %c1_i32 = arith.constant 1 : i32
    return %c1_i32, %c2_i32, %c3_i32 : i32, i32, i32
  }
}
```

Running canonicalize twice restores the original ordering:

```
> mlir-opt constant_ordering.mlir -canonicalize -canonicalize

module  {
  func @&#8203;constantOrdering() -> (i32, i32, i32) {
    %c1_i32 = arith.constant 1 : i32
    %c2_i32 = arith.constant 2 : i32
    %c3_i32 = arith.constant 3 : i32
    return %c1_i32, %c2_i32, %c3_i32 : i32, i32, i32
  }
}
```

For large pipelines, we're seeing ripple effects based on the number of times we run canonicalization that make IR diffs more difficult to follow and change behavior where ordering is load-bearing (such as when packing constant data into storage buffers).

Setting `useTopDownTraversal` in the Canonicalizer's config to false does preserve ordering, but that is less efficient (see https://llvm.discourse.group/t/speeding-up-canonicalize/3015).

Also see: https://mlir.llvm.org/docs/Canonicalization/. There are good reasons why canonicalizations aren't always guaranteed to converge in a single iteration, but they should not have this sort of cyclic behavior.

**Comment by River707** [comment]
@Mogball Are you looking into this? If not I can fix it this weekend.

**Comment by okkwon** [comment]
Is it being addressed? I am going through the IR dump after passes, and found this problem and it causes unwanted diff outputs.

**Comment by River707** [comment]
Sent out https://reviews.llvm.org/D122692

**Comment by rkayaith** [comment]
Is this fully resolved? The `-test-patterns` pass used in this test doesn't re-order the constants, but `-canonicalize` still does: https://github.com/llvm/llvm-project/blob/098e80707413bebfe804ed5a1a500e623d6236b8/mlir/test/Transforms/test-operation-folder.mlir#L26
