### ISSUE TITLE
-fno-approx-funcs doesn't override -Ofast or -ffast-math

### ISSUE THREAD

**Issue by andykaylor** [llvm/llvm-project#51907]
|  |  |
| --- | --- |
| Bugzilla Link | [52565](https://llvm.org/bz52565) |
| Version | trunk |
| OS | All |
| CC | @RKSimon,@msdataei,@zygoloid,@xgupta,@rotateright |

## Extended Description 
If I compile the following code with 'clang -O2 -ffast-math -fno-approx-funcs' the IR generated sets the 'fast' flag (implying 'afn' on the call and issues no diagnostic indicating that the -fno-approx-funcs option was ignored.

```
#include <math.h>

float f(float x) {
  return logf(x);
}
```

```
define dso_local float @&#8203;f(float %0) local_unnamed_addr #&#8203;0 {
  %2 = tail call fast float @&#8203;llvm.log.f32(float %0)
  ret float %2
}

attributes #&#8203;0 = { mustprogress nofree nosync nounwind readnone uwtable willreturn "approx-func-fp-math"="true" "denormal-fp-math"="preserve-sign,preserve-sign" "denormal-fp-math-f32"="ieee,ieee" "frame-pointer"="none" "min-legal-vector-width"="0" "no-infs-fp-math"="true" "no-nans-fp-math"="true" "no-signed-zeros-fp-math"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" "unsafe-fp-math"="true" }
```

D106191 needed many more changes to clang/lib/Driver/ToolChains/Clang.cpp to get this option to interact correctly with the other floating point options.

**Comment by arsenm** [comment]
Linked patch is committed
