### ISSUE TITLE
std::variant<std::string> not working with -std=c++20 in TRUNK Clang of GodBolt

### ISSUE THREAD

**Issue by 57c37552-1ea1-438a-ac03-4b2b401d9202** [llvm/llvm-project#51918]
|  |  |
| --- | --- |
| Bugzilla Link | [52576](https://llvm.org/bz52576) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [Errors log](https://user-images.githubusercontent.com/93435501/143762730-5af1c03d-b803-406c-b8ce-529f02bf3fe5.gz) |
| CC | @zygoloid |

## Extended Description 

If I compile on godbolt's trunk Clang with option -std=c++20 following code:

#include <variant>
#include <string>

int main() { std::variant<std::string> s = std::string("abc"); }

I get lots of errors:

==================================================

In file included from <source>:1:
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/12.0.0/../../../../include/c++/12.0.0/variant:460:2: error: attempt to use a deleted function
        _Variant_storage(in_place_index_t<_Np>, _Args&&... __args)
        ^
............... MANY MORE ERRORS HERE .......................

==================================================

but if I compile same code with -std=c++17 or with release 13.0.0 CLang, then everything compiles and works.

I got this error with -std=c++20 on current TRUNK in GodBolt https://godbolt.org/z/x4o8GKbTv

while -std=c++17 on TRUNK works https://godbolt.org/z/on9EbeY7z and also release 13.0.0 works with -std=c++20 https://godbolt.org/z/vGhj7q63z

Attaching full log "errors.txt" of errors in case if godbolt updates TRUNK to some other working version.

**Comment by ilya-biryukov** [comment]
This now compiles both in clang 14 and in trunk: https://godbolt.org/z/9oa4M375P
