### ISSUE TITLE
conflicting collapsed shape requirement for memref reshape and linalg reshape ops

### ISSUE THREAD

**Issue by cathyzhyi** [llvm/llvm-project#51911]
|  |  |
| --- | --- |
| Bugzilla Link | [52569](https://llvm.org/bz52569) |
| Version | unspecified |
| OS | All |
| CC | @joker-eph,@MaheshRavishankar |

## Extended Description 
with the following IR:
func @&#8203;bufferize_tensor_expand_shape(%arg0: tensor<20x?xf32>) -> tensor<4x5x?xf32> {
  %out = linalg.tensor_expand_shape %arg0 [[0, 1], [2]] :
     tensor<20x?xf32> into tensor<4x5x?xf32>
  return %out : tensor<4x5x?xf32>
}

memref verification would complain:
bufferize.mlir:2:10: error: 'memref.expand_shape' op expected collapsed type to be 'memref<?x?xf32>', but got 'memref<20x?xf32>'
  %out = linalg.tensor_expand_shape %arg0 [[0, 1], [2]] :
         ^
bufferize.mlir:2:10: note: see current operation: %1 = "memref.expand_shape"(%0) {reassociation = [[0, 1], [2]]} : (memref<20x?xf32>) -> memref<4x5x?xf32>

However, changing the dims according to the memref verification error would make linalg verification complain:
func @&#8203;bufferize_tensor_expand_shape(%arg0: tensor<?x?xf32>) -> tensor<4x5x?xf32> {
  %out = linalg.tensor_expand_shape %arg0 [[0, 1], [2]] :
     tensor<?x?xf32> into tensor<4x5x?xf32>
  return %out : tensor<4x5x?xf32>
}

bufferize.mlir:8:10: error: 'linalg.tensor_expand_shape' op expected dimension 0 of collapsed type to be static value of 20
  %out = linalg.tensor_expand_shape %arg0 [[0, 1], [2]] :
         ^
bufferize.mlir:8:10: note: see current operation: %0 = "linalg.tensor_expand_shape"(%arg0) {reassociation = [[0, 1], [2]]} : (tensor<?x?xf32>) -> tensor<4x5x?xf32>

**Comment by nicolasvasilache** [comment]
```
func.func @foo(%arg0: tensor<20x?xf32>) -> tensor<4x5x?xf32> {
  %out = tensor.expand_shape %arg0 [[0, 1], [2]] :
  tensor<20x?xf32> into tensor<4x5x?xf32>
  return %out : tensor<4x5x?xf32>
}
```

bufferizes to:

```
#map0 = affine_map<(d0, d1)[s0, s1, s2] -> (d0 * s1 + s0 + d1 * s2)>
#map1 = affine_map<(d0, d1, d2)[s0, s1, s2, s3] -> (d0 * s1 + s0 + d1 * s2 + d2 * s3)>
module {
  func.func @foo(%arg0: tensor<20x?xf32>) -> tensor<4x5x?xf32> {
    %0 = bufferization.to_memref %arg0 : memref<20x?xf32, #map0>
    %1 = memref.expand_shape %0 [[0, 1], [2]] : memref<20x?xf32, #map0> into memref<4x5x?xf32, #map1>
    %2 = bufferization.to_tensor %1 : memref<4x5x?xf32, #map1>
    return %2 : tensor<4x5x?xf32>
  }
}
```

When invoked with: `mlir-opt -one-shot-bufferize /tmp/aaa.mlir`.

The old bufferization passes (`-xxx-bufferize`) where problematic (see e.g. https://discourse.llvm.org/t/properly-using-bufferization-related-passes/2913).

The issue you were seeing before were refactored and cleaned up.
