### ISSUE TITLE
Overriding currently unsupported ... on this target  should list the bad option

### ISSUE THREAD

**Issue by dbc7d0cf-60de-4ba2-bc9a-c1b7219315df** [llvm/llvm-project#51914]
|  |  |
| --- | --- |
| Bugzilla Link | [52572](https://llvm.org/bz52572) |
| Version | 12.0 |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Messages of the form:
  warning: overriding currently unsupported ... on this target
should list what option it is about.
I am running clang with about 15 command line options and have little idea which option those messages are complaining about.
This is an ARM based laptop

Aside:  Seems like ARM should be added to the list of Hardware for bug reports.

**Comment by AaronBallman** [comment]
I don't think it can tell you specifically which option is the problematic one -- both of those diagnostics relate to the default rounding and exception modes, which can be controlled via different flags (the target itself could be the issue, as could options like `-frounding-math` or `-ffp-exception-behavior` or `-ftrapping-math`).

I don't think we'll be able to improve this diagnostic too much, so closing the report as WONTFIX.
