### ISSUE TITLE
Removed /Zd flag still mentioned in documentation

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#51913]
|  |  |
| --- | --- |
| Bugzilla Link | [52571](https://llvm.org/bz52571) |
| Version | trunk |
| OS | Windows NT |
| CC | @JVApen,@zygoloid |

## Extended Description 
https://reviews.llvm.org/D93458 removed the /Zd flag as MSVC doesn't support that syntax. Instead users should be using -gline-tables-only

The /Zd flag is still mentioned at https://clang.llvm.org/docs/UsersManual.html#clang-cl :   /Zd                     Emit debug line number tables only

Can this be removed as well?

**Comment by zero9178** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/a3b099b68c0c
