### ISSUE TITLE
ICE while generating debug information

### ISSUE THREAD

**Issue by mordante** [llvm/llvm-project#51926]
|  |  |
| --- | --- |
| Bugzilla Link | [52584](https://llvm.org/bz52584) |
| Version | trunk |
| OS | Linux |
| Attachments | [backtrace of the crash](https://user-images.githubusercontent.com/1362617/143762734-40660ab9-89db-45bf-b45e-5c5c1943d800.gz), [Reduced source](https://user-images.githubusercontent.com/1362617/143762735-819c4a2b-a7d7-449b-835f-44c906951ac7.gz), [Reduced run script](https://user-images.githubusercontent.com/1362617/143762736-2874c57e-e681-4e73-8144-671fb114de1e.gz) |
| CC | @dwblaikie,@JDevlieghere,@walkerkd,@pogo59 |

## Extended Description 

While testing https://reviews.llvm.org/D70631 with the libc++ buildkite CI this build results in an crash https://buildkite.com/llvm-project/libcxx-ci/builds/6587#d7ec64f2-e31a-4d73-8d6c-e118e63a0cc1

The CI job builds clang and uses that Clang to build the patch.
https://github.com/llvm/llvm-project/blob/main/libcxx/utils/ci/run-buildbot#L470
Two work-arounds are
- Remove -DLLVM_ENABLE_ASSERTIONS=ON
- Change the build type to Release

Attached the backtrace and reduced reproducer.

**Comment by rickyz** [comment]
This should be fixed by c7c84b90879f

**Comment by mordante** [comment]
I landed https://reviews.llvm.org/D70631  and there are no more issues so this bug has been fixed.
