### ISSUE TITLE
About Bugzilla migration to GitHub

### ISSUE THREAD

**Issue by bc29c4d5-3138-4d40-8261-e7f5a79433a4** [llvm/llvm-project#51943]
|  |  |
| --- | --- |
| Bugzilla Link | [52601](https://llvm.org/bz52601) |
| Version | unspecified |
| OS | Windows NT |
| CC | @kbeyls,@rnk,@TNorthover,@tstellar |

## Extended Description 
Hi,

I saw a an announcement about the migration to GitHub starting soon.

There were some concerns about people submitting issues during the migration. I want just to point that there is an option to restrict interaction with the repository under setting->Temporary interaction limits (/settings/interaction_limits) which let you forbid other people from submitting issues.

Sorry I couldn't subscribe the mailing-list to post the suggestion. 

Mehdi Chinoune

**Comment by asl** [comment]
Thanks for the suggestion! We are are done here.
