### ISSUE TITLE
Generated dot graph from llc is not in correct format to view by xdot

### ISSUE THREAD

**Issue by xgupta** [llvm/llvm-project#52610]
When trying view the DAG graphs with llc, dot file is not correctly generated. 

$./clang -mllvm -fast-isel=false -emit-llvm -S sizeof.c -o sizeof.ll
$./llc -fast-isel=false  -view-sched-dags sizeof.ll

Writing '/tmp/dag.fill_structs-95807e.dot'...  done. 
Trying 'xdg-open' program... Remember to erase graph file: /tmp/dag.fill_structs-95807e.dot
Writing '/tmp/dag.fill-7de5e1.dot'...  done. 
Trying 'xdg-open' program... Remember to erase graph file: /tmp/dag.fill-7de5e1.dot
Writing '/tmp/dag.fill-45abdb.dot'...  done. 
Trying 'xdg-open' program... Remember to erase graph file: /tmp/dag.fill-45abdb.dot
Writing '/tmp/dag.fill-6a5721.dot'...  done. 
Trying 'xdg-open' program... Remember to erase graph file: /tmp/dag.fill-6a5721.dot
Writing '/tmp/dag.fill-9430d0.dot'...  done. 
Trying 'xdg-open' program... Remember to erase graph file: /tmp/dag.fill-9430d0.dot
Writing '/tmp/dag.fill-275a7c.dot'...  done. 
Trying 'xdg-open' program... Remember to erase graph file: /tmp/dag.fill-275a7c.dot
Writing '/tmp/dag.main-9fa748.dot'...  done. 
Trying 'xdg-open' program... Remember to erase graph file: /tmp/dag.main-9fa748.dot
xgupta@archlinux ~/llvm/llvm-project/build1/bin (main?) $ Error: bad label format {EntryToken|t0|{<d0>ch}
Error: bad label format {TargetConstant\<0\>|t1|{<d0>i32}
Error: bad label format {{<s0>0|<s1>1}|RET|t2|{<d0>ch}
Warning: node Node0x55f7ac253ec0, port s1 unrecognized
Warning: node Node0x55f7ac1cd4c8, port d0 unrecognized
Warning: node Node0x55f7ac253ec0, port s0 unrecognized
Warning: node Node0x55f7ac251ea0, port d0 unrecognized
Warning: node Node0x55f7ac253ec0, port d0 unrecognized
Error: bad label format {EntryToken|t0|{<d0>ch}
Error: bad label format {BasicBlock\<for.end 0x55f7ac273328\>|t12|{<d0>ch}
Error: bad label format {BasicBlock\<for.body 0x55f7ac273168\>|t14|{<d0>ch}
Error: bad label format {TargetConstant\<13\>|t25|{<d0>i8}
Error: bad label format {{<s0>0|<s1>1|<s2>2|<s3>3|<s4>4|<s5>5}|MOVSX64rm32\<Mem:(dereferenceable load (s32) from %ir.i)\>|t19|{<d0>i64|<d1>ch}
Error: bad label format {TargetFrameIndex\<3\>|t34|{<d0>i64}
Error: bad label format {TargetConstant\<1\>|t30|{<d0>i8}
Error: bad label format {Register $noreg|t31|{<d0>i64}
Error: bad label format {TargetConstant\<0\>|t32|{<d0>i32}
Error: bad label format {Register $noreg|t33|{<d0>i16}
Error: bad label format {{<s0>0|<s1>1|<s2>2|<s3>3|<s4>4|<s5>5}|MOV64rm\<Mem:(dereferenceable load (s64) from %ir.sizeof_buf.addr)\>|t7|{<d0>i64|<d1>ch}
Error: bad label format {TargetFrameIndex\<1\>|t29|{<d0>i64}
Error: bad label format {{<s0>0|<s1>1}|SUB64rr|t24|{<d0>i64|<d1>i32}
Error: bad label format {{<s0>0|<s1>1|<s2>2|<s3>3}|JCC_1|t26|{<d0>ch}
Error: bad label format {{<s0>0|<s1>1|<s2>2}|CopyToReg|t28|{<d0>ch|<d1>glue}
Error: bad label format {{<s0>0|<s1>1}|JMP_1|t15|{<d0>ch}
Error: bad label format {Register $eflags|t27|{<d0>i32}
Warning: node Node0x55f7ac253638, port s5 unrecognized
Warning: node Node0x55f7ac1cd4c8, port d0 unrecognized
Warning: node Node0x55f7ac253638, port s0 unrecognized
Warning: node Node0x55f7ac251ea0, port d0 unrecognized
Warning: node Node0x55f7ac253638, port s1 unrecognized
Warning: node Node0x55f7ac251e38, port d0 unrecognized
Warning: node Node0x55f7ac253638, port s2 unrecognized
Warning: node Node0x55f7ac2521e0, port d0 unrecognized

sizeof.c - https://gist.github.com/xgupta/a833d86b9233acbff3ace22cb72b1c16
/tmp/dag.fill-7de5e1.dot - https://gist.github.com/xgupta/903717dcf3633592a7278703285d017b

I tested this on arch/gentoo/ubuntu linux so I am sure something is missing on llvm side.

**Comment by jrtc27** [comment]
Broken by https://reviews.llvm.org/D87202

**Comment by xgupta** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/6fef0ffa14a38c2146c395cc4f39d80844ecc639.
