### ISSUE TITLE
Please merge c4582a689c2c74e0635309979176c7ada086f066 into release/13.x

### ISSUE THREAD

**Issue by nathanchance** [llvm/llvm-project#52633]
Please consider merging https://github.com/llvm/llvm-project/commit/c4582a689c2c74e0635309979176c7ada086f066 into release/13.x. This resolves a false positive `-Wuninitialized` instance in the Linux kernel and will prevent further instances as asm goto with outputs is adopted by more architectures.

cc @gwelymernans @nickdesaulniers @tstellar in case there are any objections.

**Comment by tstellar** [comment]
Merged: d904698b53e4f21a675d4ca0463843432ff4d590
