### ISSUE TITLE
Nested call of consteval functions with a reference argument

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#52648]
This is a valid code:
```
template<class T>
consteval auto foo(const T&) {
   return 0;
}

template<class T>
consteval auto bar(const T& t) {
   auto n = foo(t);
   return n;
}

int main() {
   static_assert(bar("abc") == 0);
}
```
accepted by GCC and MSVC, but unfortunately not Clang. Demo: https://gcc.godbolt.org/z/6b7PMY3Es

Related discussion: https://stackoverflow.com/q/70165418/7325599

**Comment by Izaron** [comment]
Thank you for the issue! I proposed a fix here - https://reviews.llvm.org/D119651

**Comment by usx95** [comment]
Duplicate of #51182
