### ISSUE TITLE
Requires-expression too eagerly completes associated type

### ISSUE THREAD

**Issue by Quuxplusone** [llvm/llvm-project#52643]
https://godbolt.org/z/j453na433
```
template<class T>
concept C = requires (T t) {
    t.foo();
};

struct Incomplete;
template<class T> struct Holder { T t; };

static_assert(not C<Holder<Incomplete>*>);
```

Clang trunk (i.e. 14) says:
```
<source>:8:37: error: field has incomplete type 'Incomplete'
template<class T> struct Holder { T t; };
                                    ^
<source>:4:6: note: in instantiation of template class 'Holder<Incomplete>' requested here
    t.foo();
     ^
<source>:4:5: note: in instantiation of requirement here
    t.foo();
    ^~~~~~~
```

GCC and MSVC both think the code is fine. I agree: Clang should know that `t.foo()` is invalid when `t` is of pointer type. It seems to be trying to complete the type in order to do ADL (argument-dependent lookup)... but member function calls aren't supposed to do ADL!

**Comment by CaseyCarter** [comment]
This doesn't seem to be concepts-specific, this C++14 program demonstrates the issue as well (https://godbolt.org/z/rv5vYdvvj):
```c++
template <class T> T declval();

template <class...> using void_t = void;

template <class, class = void>
constexpr bool meow = false;

template <class T>
constexpr bool meow<T, void_t<decltype(declval<T&>().foo())>> = true;

struct incomplete;
template <class T> struct wrapper { T t; };

static_assert(!meow<wrapper<incomplete>*>);
```
Looks like we're trying to determine the associated namespaces and entities _before_ determining if the expression before '.' has class type. Or maybe there's some weirdness involved in trying to determine if `foo` names the pseudo-destructor of `wrapper<incomplete>*` per [expr.ref]/3?

**Comment by Quuxplusone** [comment]
This is essentially a duplicate of #52970.
