### ISSUE TITLE
Please cherry-pick: [ELF] Do not report undefined weak references in shared libraries

### ISSUE THREAD

**Issue by igorkudrin** [llvm/llvm-project#52663]
ce25eb12dd5abae6c769168a70a8f377b608228c fixes an issue introduced in 70c23e232e50b190c9e0d8e4b5b6a8ddfc19b80c. According to [the report](https://reviews.llvm.org/D101996#3168916), "A FreeBSD port hit this regression and now fails to build with LLD 13".

**Comment by tstellar** [comment]
Merged: 52bfd2c1ccd8

**Comment by tstellar** [comment]
Merged: 52bfd2c1ccd8
