### ISSUE TITLE
Clang doesn't create epilogue information even at -O0

### ISSUE THREAD

**Issue by billionai** [llvm/llvm-project#52661]
Running clang with -O0 -g doesn't create epilogue information for trivial epilogues. A code like

```
1 int main(){
2   fun_a( fun_b(), fun_c());
3   return 0;
4 }
```

when debugged using GDB will go from line 3 directly to __libc_start_call_main(). This creates a problem for GDB's testsuite, since it expects being able to step once again, to line 4. 

It also can make the debugging experience confusing for users, since if they step into fun_c and use the command `next` , the program will already be at line 3 here, instead of back at line 3 and able to step into fun_b or fun_a.

**Comment by EugeneZelenko** [comment]
@billionaiL Could you please elaborate?

**Comment by billionai** [comment]
What I meant to ask was that clang link the epilogue line to the closing brace of the function, rather than the final statement line (in the example, line 4 as opposed to line 3). This would match GCC behavior more closely, which felt more "correct" to me because I was used to it.

However, talking to other GDB developers, I came to understand that this is just a compiler choice, not a bug in clang. That's why I decided to close the issue.

**Comment by dwblaikie** [comment]
I think we had a discussion about this recently maybe on another bug or on discourse?... but I don't remember where, unfortunately :/

**Comment by jryans** [comment]
@dwblaikie Maybe you are thinking of https://github.com/llvm/llvm-project/issues/57567? This issue is essentially a duplicate of that one, I think.

**Comment by dwblaikie** [comment]
> @dwblaikie Maybe you are thinking of #57567? This issue is essentially a duplicate of that one, I think.

Yep, that looks like the one - thanks!
