### ISSUE TITLE
There is no mechanism to provide default values for `ListOption`

### ISSUE THREAD

**Issue by pifon2a** [llvm/llvm-project#52667]
It is possible to use `llvm::cl::init(some_value)` to specify a default value for `Option<type>`. Unfortunately, there is currently no way to do smth like `llvm::cl::init({value_1, value_2})` if one wants to provide default values for `ListOption<type>`.

**Comment by tyb0807** [comment]
Fixed in [a4deb14fdfaa183da938e40b54954afa9c7a11c1](https://github.com/llvm/llvm-project/commit/a4deb14fdfaa183da938e40b54954afa9c7a11c1), closing.
