### ISSUE TITLE
C++ header files have no comments for Intellisense in VScode

### ISSUE THREAD

**Issue by mikekenn** [llvm/llvm-project#52678]
Are their plans to include doxygen comments to the c++ header files so that vsCode my use them in IntelliSense?

Thanks,
M

**Comment by dwblaikie** [comment]
What comments are required/got a link to a formal description of the requirement?

LLVM headers do have one mark in the comment that's enough for some unix-like tools to detect that they're c++ (eg, see the first line here: https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/ADT/StringRef.h#L1 `-*- C++ -*-`) not sure if vsCode has a configuration point for adding that sort of mark so it can recognize these existing marks.
