### ISSUE TITLE
Merge 353fe72ca3d77f4bbe53132577a88424def172e8 and ce25eb12dd5abae6c769168a70a8f377b608228c

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#52676]
(Requested few days ago. Put here to be clearer) @tstellar  Please merge

* 353fe72ca3d77f4bbe53132577a88424def172e8: `[ELF] Hint -z nostart-stop-gc for __start_ undefined references`
* ce25eb12dd5abae6c769168a70a8f377b608228c: `[ELF] Do not report undefined weak references in shared libraries`

into 13.0.1 (→ 13.0.1 Meta Issue #51489).

I have checked that `ninja check-lld` passes with them in release/13.x

**Comment by tstellar** [comment]
/cherry-pick 353fe72ca3d77f4bbe53132577a88424def172e8 ce25eb12dd5abae6c769168a70a8f377b608228c

**Comment by tstellar** [comment]
This fix does not apply cleanly to the release branch.  Could someone resolve the merge conflicts and push it to a github fork.

**Comment by MaskRay** [comment]
Merged in release/13.x
