### ISSUE TITLE
Crash @llvm_unreachable in ARMBaseRegisterInfo::isFrameOffsetLegal

### ISSUE THREAD

**Issue by glandium** [llvm/llvm-project#52681]
We're getting a clang crash when building Firefox with PGO on clang trunk. I bisected it to https://reviews.llvm.org/D114638, and the following patch fixes it:
```
diff --git a/llvm/lib/Target/ARM/ARMBaseRegisterInfo.cpp b/llvm/lib/Target/ARM/ARMBaseRegisterInfo.cpp
index b53efe58e8de..c94b75c2ad0e 100644
--- a/llvm/lib/Target/ARM/ARMBaseRegisterInfo.cpp
+++ b/llvm/lib/Target/ARM/ARMBaseRegisterInfo.cpp
@@ -529,7 +529,7 @@ getFrameIndexInstrOffset(const MachineInstr *MI, int Idx) const {
   int Scale = 1;
   unsigned ImmIdx = 0;
   switch (AddrMode) {
-  case ARMII::AddrModeT2_i8:
+  case ARMII::AddrModeT2_i8neg:
   case ARMII::AddrModeT2_i12:
   case ARMII::AddrMode_i12:
     InstrOffs = MI->getOperand(Idx+1).getImm();
@@ -727,7 +727,7 @@ bool ARMBaseRegisterInfo::isFrameOffsetLegal(const MachineInstr *MI,
   unsigned Scale = 1;
   bool isSigned = true;
   switch (AddrMode) {
-  case ARMII::AddrModeT2_i8:
+  case ARMII::AddrModeT2_i8neg:
   case ARMII::AddrModeT2_i12:
     // i8 supports only negative, and i12 supports only positive, so
     // based on Offset sign, consider the appropriate instruction
```

I don't know whether the `AddrModeT2_i8` should be kept and/or whether `i8pos` should be covered too.
ARMHazardRecognizer.cpp and ARMLoadStoreOptimizer.cpp were also not touched by the original patch, I don't know whether they need to be adjusted as well.

Cc: @davemgreen

**Comment by davemgreen** [comment]
Thanks for the report. Do you have a reproducer of it crashing?

**Comment by glandium** [comment]
The source is https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/YD8XqoJlRbCc8T7oH2uU0Q/runs/0/artifacts/public/build/Unified_cpp_netwerk_dns1-ddd185.cpp.
The crashing command line is (modified from the associated script): `clang -cc1 -triple thumbv7-unknown-linux-android -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name Unified_cpp_netwerk_dns1.cpp -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=all -relaxed-aliasing -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=1 -target-cpu generic -target-feature +soft-float-abi -target-feature +vfp2 -target-feature +vfp2sp -target-feature +vfp3 -target-feature +vfp3d16 -target-feature +vfp3d16sp -target-feature +vfp3sp -target-feature -fp16 -target-feature -vfp4 -target-feature -vfp4d16 -target-feature -vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature -fp-armv8d16 -target-feature -fp-armv8d16sp -target-feature -fp-armv8sp -target-feature -fullfp16 -target-feature +fp64 -target-feature +d32 -target-feature +neon -target-feature -sha2 -target-feature -aes -target-feature -fp16fml -target-feature +strict-align -target-abi aapcs-linux -mfloat-abi soft -fallow-half-arguments-and-returns -debug-info-kind=constructor -dwarf-version=4 -debugger-tuning=gdb -mllvm -crash-diagnostics-dir=. -ffunction-sections -fdata-sections -fprofile-instrument-use-path=merged.profdata -sys-header-deps -D NDEBUG=1 -D TRIMMED=1 -D OS_POSIX=1 -D OS_LINUX=1 -D MOZ_HAS_MOZGLUE -D MOZILLA_INTERNAL_API -D IMPL_LIBXUL -D STATIC_EXPORTABLE_JS_API -D MOZILLA_CLIENT -D __ANDROID_API__=16 -Oz -Wall -Wbitfield-enum-conversion -Wdeprecated-this-capture -Wempty-body -Wformat-type-confusion -Wignored-qualifiers -Wpointer-arith -Wshadow-field-in-constructor-modified -Wsign-compare -Wtype-limits -Wno-error=tautological-type-limit-compare -Wunreachable-code -Wunreachable-code-return -Wunused-but-set-parameter -Wno-invalid-offsetof -Wclass-varargs -Wempty-init-stmt -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wloop-analysis -Wno-range-loop-analysis -Wc++2a-compat -Wcomma -Wenum-compare-conditional -Wimplicit-fallthrough -Werror=non-literal-null-conversion -Wstring-conversion -Wno-inline-new-delete -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=backend-plugin -Wno-error=free-nonheap-object -Wno-error=return-std-move -Wno-error=atomic-alignment -Wno-error=deprecated-copy -Wformat -Wformat-security -Wno-gnu-zero-variadic-macro-arguments -Wno-psabi -Wno-unknown-warning-option -Werror -Wno-error=backend-plugin -std=gnu++17 -fdeprecated-macro -ferror-limit 19 -stack-protector 2 -fno-rtti -fno-signed-char -fgnuc-version=4.2.1 -fno-legacy-pass-manager -fno-aligned-allocation -fcolor-diagnostics -vectorize-slp -mllvm -enable-machine-outliner=never -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ Unified_cpp_netwerk_dns1-ddd185.cpp`
You'll also need this file: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Exqrpyw1Qhq7KTvm5i2pTw/runs/0/artifacts/public/build/profdata.tar.xz. Extract its content in the same directory as the .cpp file. The crash doesn't happen without `-fprofile-instrument-use-path`.
Note: these files expire in 3 to 4 weeks.

**Comment by glandium** [comment]
Also note that because llvm_unreachable is involved, unless you build clang without `NDEBUG`, you'll also get a crash while processing the crash.

**Comment by davemgreen** [comment]
Thanks. I'm surprised to see a stack object with a negative offset. I feel that would read into another stack object.

The files pretty large and my attempts to reduce it are not going very fast - it's still 0.0% through a creduce. I'll try and put together a test case and a fix to get things unblocked. Then I might look more into why there is a negative frame offset to begin with.
