### ISSUE TITLE
compiler-rt tests binary-id.c and binary-id-padding.c failing on Tumbleweed x86_64 Linux

### ISSUE THREAD

**Issue by slacka** [llvm/llvm-project#52695]
The recently added tests:
       Profile-x86_64 :: Linux/binary-id-padding.c
       Profile-x86_64 :: Linux/binary-id.c

Are failing on openSUSE Tumbleweed 20211211 x86_64 on clang 14.0.0  b04c64671150 release builds. Below is the build log: 

FAIL: Profile-x86_64 :: Linux/binary-id-padding.c (79450 of 83045)
 TEST 'Profile-x86_64 :: Linux/binary-id-padding.c' FAILED 
Script:

: 'RUN: at line 5';      /llvm-project/build/./bin/clang   -m64  -ldl  -fprofile-instr-generate -Wl,--build-id=sha1 -o /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id-padding.c.tmp /llvm-project/compiler-rt/test/profile/Linux/binary-id-padding.c
: 'RUN: at line 6';   env LLVM_PROFILE_FILE=/llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id-padding.c.tmp.profraw  /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id-padding.c.tmp
: 'RUN: at line 7';    /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id-padding.c.tmp /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id-padding.c.tmp.profraw

Exit Code: 1

Command Output (stderr):

Invalid binary ID size Success

FAIL: Profile-x86_64 :: Linux/binary-id.c (79451 of 83045)
 TEST 'Profile-x86_64 :: Linux/binary-id.c' FAILED 
Script:

: 'RUN: at line 2';      /llvm-project/build/./bin/clang   -m64  -ldl  -fprofile-instr-generate -Wl,--build-id=none -O2 -o /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp /llvm-project/compiler-rt/test/profile/Linux/binary-id.c
: 'RUN: at line 3';   env LLVM_PROFILE_FILE=/llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw  /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp
: 'RUN: at line 4';   llvm-profdata show --binary-ids  /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw > /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.out
: 'RUN: at line 5';   FileCheck /llvm-project/compiler-rt/test/profile/Linux/binary-id.c --check-prefix=NO-BINARY-ID < /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.out
: 'RUN: at line 6';   llvm-profdata merge -o /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profdata /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw
: 'RUN: at line 8';      /llvm-project/build/./bin/clang   -m64  -ldl  -fprofile-instr-generate -Wl,--build-id -O2 -o /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp /llvm-project/compiler-rt/test/profile/Linux/binary-id.c
: 'RUN: at line 9';   env LLVM_PROFILE_FILE=/llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw  /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp
: 'RUN: at line 10';   llvm-profdata show --binary-ids  /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw > /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw.out
: 'RUN: at line 11';   FileCheck /llvm-project/compiler-rt/test/profile/Linux/binary-id.c --check-prefix=BINARY-ID-RAW-PROF < /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw.out
: 'RUN: at line 13';   rm -rf /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profdir
: 'RUN: at line 14';   env LLVM_PROFILE_FILE=/llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profdir/default_%m.profraw  /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp
: 'RUN: at line 15';   env LLVM_PROFILE_FILE=/llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profdir/default_%m.profraw  /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp
: 'RUN: at line 16';   env LLVM_PROFILE_FILE=/llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profdir/default_%m.profraw  /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp
: 'RUN: at line 17';   llvm-profdata show --binary-ids  /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profdir/default_*.profraw > /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw.out
: 'RUN: at line 18';   FileCheck /llvm-project/compiler-rt/test/profile/Linux/binary-id.c --check-prefix=BINARY-ID-MERGE-PROF < /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp.profraw.out

Exit Code: 1

Command Output (stderr):

/llvm-project/compiler-rt/test/profile/Linux/binary-id.c:42:29: error: BINARY-ID-RAW-PROF-NEXT: expected string not found in input
// BINARY-ID-RAW-PROF-NEXT: Binary IDs:
                            ^
<stdin>:4:32: note: scanning from here
Maximum internal block count: 0
                               ^

Input file: <stdin>
Check file: /llvm-project/compiler-rt/test/profile/Linux/binary-id.c

-dump-input=help explains the following input dump.

Input was:
<<<<<<
         1: Instrumentation level: Front-end 
         2: Total functions: 3 
         3: Maximum function count: 1 
         4: Maximum internal block count: 0 
next:42                                    X error: no match found

**Comment by vitalybuka** [comment]
@gulfemsavrun Looks similar to the failure on https://lab.llvm.org/staging/#/builders/sanitizer-x86_64-linux

**Comment by slacka** [comment]
@gulfemsavrun 
Asked me:

Could you please run the following commands, and show me the output of the second file?
1) Generate the binary:
/llvm-project/build/./bin/clang -m64 -ldl -fprofile-instr-generate -Wl,--build-id -O2 -o /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp /llvm-project/compiler-rt/test/profile/Linux/binary-id.c
2) Ready build id from the binary via readelf or llvm-readelf:
readelf -n /llvm-project/build/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp

I would like to see whether build id is supported in OpenSuse.
If it is supported, then it should have the output like that:

~/llvm/llvm-project/test-build-id$ readelf -n code


Displaying notes found in: .note.gnu.build-id

  Owner                Data size        Description

  GNU                  0x00000014       NT_GNU_BUILD_ID (unique build ID bitstring)

    Build ID: 49301ed881601695e18525a71387dd4fdc943925

3) Do you know whether build ids are supported in OpenSuse?
In case it is not supported, how can I disable these tests for OpenSuse?

**Comment by slacka** [comment]
I'm not an OpenSuse dev and just a volunteer for the clang project. Here are the results of your request:


build> readelf -n projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/binary-id.c.tmp

Displaying notes found in: .note.gnu.property
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_PROPERTY_TYPE_0
      Properties: x86 ISA needed: x86-64-baseline

Displaying notes found in: .note.gnu.build-id
  Owner                Data size 	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: d26e83a69f2fb1ad3067f685962e2aa99d47f4af

Displaying notes found in: .note.ABI-tag
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 3.2.0

**Comment by gulfemsavrun** [comment]
Thanks @slacka and @vitalybuka helping me to figure out the issue.
I pushed a fix via https://reviews.llvm.org/D115830.

**Comment by Endilll** [comment]
Aforementioned fix has landed.
