### ISSUE TITLE
[libcxx] Microsoft extensions break __itoa in <charconv> when sizeof(T) > 4

### ISSUE THREAD

**Issue by duk-37** [llvm/llvm-project#52709]
[Relevant piece of code in libcxx](https://github.com/llvm/llvm-project/blob/f6f0409f6f267bf60126e373a8d60305f8e3e3f4/libcxx/include/charconv#L170)
[Repro of the underlying issue](https://godbolt.org/z/qzvTEhv4e)

Since this code is used in most int-to-string conversions in libcxx, every conversion that has a type >4 bytes [gets truncated with Microsoft extensions on.](https://godbolt.org/z/secjsKWjd)

**Comment by ldionne** [comment]
@mordante or @mstorsjo Any appetite to take a look?

**Comment by mstorsjo** [comment]
Sorry, I have no experience with these language extensions and these levels, and don't really follow what happens in these templates, so I don't think I can be of much help here. :-(

**Comment by mordante** [comment]
I'm also not familiar with these language extensions.
I don't mind to investigate it further, but I first need to finish some patches I'm working on.

**Comment by duk-37** [comment]
I think the template specializations here are a little overkill, something like this would offer essentially the same functionality and work with MS:

```cpp
template <typename _Tp, typename = void>
struct _LIBCPP_HIDDEN __traits_base
{
	static_assert(sizeof(_Tp) <= 8);

    using type = uint64_t;

    static _LIBCPP_INLINE_VISIBILITY int __width(_Tp __v)
    {
        auto __t = (64 - _VSTD::__libcpp_clz(static_cast<type>(__v | 1))) * 1233 >> 12;
        return __t - (__v < __pow10_64[__t]) + 1;
    }

    _LIBCPP_AVAILABILITY_TO_CHARS
    static _LIBCPP_INLINE_VISIBILITY char* __convert(_Tp __v, char* __p)
    {
        return __u64toa(__v, __p);
    }

    static _LIBCPP_INLINE_VISIBILITY decltype(__pow10_64)& __pow() { return __pow10_64; }
};

template <typename _Tp>
struct _LIBCPP_HIDDEN
    __traits_base<_Tp, std::enable_if_t<sizeof(_Tp) <= 4>>
{
    using type = uint32_t;

    static _LIBCPP_INLINE_VISIBILITY int __width(_Tp __v)
    {
        auto __t = (32 - _VSTD::__libcpp_clz(static_cast<type>(__v | 1))) * 1233 >> 12;
        return __t - (__v < __pow10_32[__t]) + 1;
    }

    _LIBCPP_AVAILABILITY_TO_CHARS
    static _LIBCPP_INLINE_VISIBILITY char* __convert(_Tp __v, char* __p)
    {
        return __u32toa(__v, __p);
    }

    static _LIBCPP_INLINE_VISIBILITY decltype(__pow10_32)& __pow() { return __pow10_32; }
};
```

**Comment by mordante** [comment]
That's what I also expect. In fact I've been wondering about the original constrains in the past, but never looked at why they were written that way. But if it ain't broke don't fix it ;-)

**Comment by ldionne** [comment]
Possible patch based on the suggestion above:

```diff
diff --git a/libcxx/include/charconv b/libcxx/include/charconv
index 06634fe7bc39..cd05e381b593 100644
--- a/libcxx/include/charconv
+++ b/libcxx/include/charconv
@@ -148,6 +148,8 @@ static _LIBCPP_CONSTEXPR uint32_t __pow10_32[] = {
 template <typename _Tp, typename = void>
 struct _LIBCPP_HIDDEN __traits_base
 {
+    static_assert(sizeof(_Tp) <= sizeof(uint64_t), "Integer would be truncated");
+
     using type = uint64_t;
 
     static _LIBCPP_INLINE_VISIBILITY int __width(_Tp __v)
@@ -166,8 +168,7 @@ struct _LIBCPP_HIDDEN __traits_base
 };
 
 template <typename _Tp>
-struct _LIBCPP_HIDDEN
-    __traits_base<_Tp, decltype(void(uint32_t{declval<_Tp>()}))>
+struct _LIBCPP_HIDDEN __traits_base<_Tp, std::enable_if_t<sizeof(_Tp) <= sizeof(uint32_t)>>
 {
     using type = uint32_t;
 
```

It would be awesome to find a way to add a test -- perhaps we can add a `.sh.cpp` test that adds `-fms-extensions` to the command line flags?

**Comment by mordante** [comment]
We use a normal `pass.cpp` test and add `// ADDITIONAL_COMPILE_FLAGS:  fms-extensions`.

**Comment by mstorsjo** [comment]
> It would be awesome to find a way to add a test -- perhaps we can add a `.sh.cpp` test that adds `-fms-extensions` to the command line flags?

Wouldn't it be enough to just have the code as is without explicitly adding that option somehow? As long as we have the clang-cl CI configurations, those would always build it with MS extensions (as clang-cl and clang's msvc mode implicitly enable those extensions). The option is just useful for enabling those extensions for other targets.

**Comment by ldionne** [comment]
> as clang-cl and clang's msvc mode implicitly enable those extensions

Oh, I didn't know that. Yes, that should be sufficient.

**Comment by mordante** [comment]
> > It would be awesome to find a way to add a test -- perhaps we can add a `.sh.cpp` test that adds `-fms-extensions` to the command line flags?
> 
> Wouldn't it be enough to just have the code as is without explicitly adding that option somehow? As long as we have the clang-cl CI configurations, those would always build it with MS extensions (as clang-cl and clang's msvc mode implicitly enable those extensions). The option is just useful for enabling those extensions for other targets.

The odd part is we have tests like `test(12345678901234567890UL, "12345678901234567890");` that pass, including on clang-cl.

**Comment by mordante** [comment]
I've done some investigation by running all tests with `-fms-extensions` using this patch 
https://llvm.org/D116119 resulting in https://buildkite.com/llvm-project/libcxx-ci/builds/7399.
(Expect most formatting failures are due to `to_chars` since that's used under the hood.)

So if we want to support `-fms-extensions` we should add a CI job. The issue with `to_chars` seems to be narrowing. I fixed it as suggested and then the tests fail.
```
template <typename To, typename From>
constexpr auto
is_non_narrowing(From a) -> decltype(To{a}, true_type())
{
    return {};
}
```
will be a `true_type` even when narrowing it considers `To{a}` well formed. I had a look at the clang code and whether narrowing is an error depends on whether Microsoft Extensions are enabled. I don't foresee huge issues to fix it for `to_chars`, but didn't investigate the other issues.

@ldionne let's discuss after the holidays whether or not we we want to support `-fms-extensions` properly.

**Comment by duk-37** [comment]
This seems to have been fixed by [this commit](https://github.com/llvm/llvm-project/commit/3f78683353e272224e9bcc223f7ba05ab374a8c2). 🙂

**Comment by mordante** [comment]
I expected that, but the lit tests haven't been adjusted in a similar fashion. So they probably still fail. Therefore I hadn't closed the ticket yet. However I won't object against closing it.
I had this ticket in mind during that change and I feel the new way improves readability.

Thanks for the feedback!

**Comment by duk-37** [comment]
> I expected that, but the lit tests haven't been adjusted in a similar fashion. So they probably still fail. Therefore I hadn't closed the ticket yet. However I won't object against closing it. I had this ticket in mind during that change and I feel the new way improves readability.
> 
> Thanks for the feedback!

Ah, okay, I didn't realize there was something else failing here. It might be a good idea to open another issue for that though. Either way, thanks for fixing this!
