### ISSUE TITLE
Function stubs on the PLT show as __lldb_unnamed_symbol

### ISSUE THREAD

**Issue by HFDan** [llvm/llvm-project#52702]
Whenever i use LLDB to debug my application, and i disassemble a function, calls to libc functions look like this:

`call 0x1030 ; stub for __lldb_unnamed_symbol67`

When i use GDB, calls to libc functions look like this:

`call 0x1030 <puts@plt>`

Why does LLDB not resolve symbol names for plt function stubs?

**Comment by poyaoc97** [comment]
Potential fix: https://reviews.llvm.org/D116217

**Comment by poyaoc97** [comment]
Closed by 633b002.

**Comment by Endilll** [comment]
Commit: 633b002944b966ddb64c85f4a8c017a858afb4fc
