### ISSUE TITLE
[AMDGPU][MC] Incorrect disassembly of s_waitcnt

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#52716]
s_waitcnt with default _expcnt_, _vmcnt_ and _lgkmcnt_ values is disassembled without arguments.

An example of failed test for GFX10:
`
    0x7f,0xff,0x8c,0xbf
`
Expected result:
`
    s_waitcnt 0xff7f
`
Actual output:
`
    s_waitcnt
`

**Comment by jayfoad** [comment]
In the patch https://reviews.llvm.org/D117305 it looks like you decided to print `s_waitcnt vmcnt(15) expcnt(7) lgkmcnt(15)` instead of `s_waitcnt 0xff7f`?

**Comment by dpreobra** [comment]
> In the patch https://reviews.llvm.org/D117305 it looks like you decided to print `s_waitcnt vmcnt(15) expcnt(7) lgkmcnt(15)` instead of `s_waitcnt 0xff7f`?

I tried both options but finally decided that ‘s_waitcnt 0xff7f’ is not user-friendly.

**Comment by dpreobra** [comment]
b5fb7e485e0f2d189d450fc120ede9ae5fbf27e7
