### ISSUE TITLE
https://scan.coverity.com/projects/llvm has stopped updating

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#52717]
@sylvestre I think you used to manage this - do you know why the regular checks stopped in October?

**Comment by sylvestre** [comment]
Yeah, it is broken since the move to the cloud:
https://blog.llvm.org/posts/2021-11-02-apt.llvm.org-moving-from-physical-server-to-the-cloud/

I will have a look on how to fix it

**Comment by sylvestre** [comment]
(tbh, I didn't know that people were looking at it :)

**Comment by RKSimon** [comment]
I'd gotten into the habit of triaging coverity over lunch (also https://llvm.org/reports/scan-build/ which is also broken)

**Comment by sylvestre** [comment]
good news for your lunch: it is back :)
![image](https://user-images.githubusercontent.com/733326/146737246-b7effd9c-08b9-4502-ac27-0c6c86001265.png)
