### ISSUE TITLE
Wrong formatting last line with UT_ForIndentation and BreakBeforeTernaryOperators=false

### ISSUE THREAD

**Issue by dmyger** [llvm/llvm-project#52724]
`clang-format` version `13.0.0`
macOS 12.0.1

Style file `.clang-format`
```
Language: Cpp
BasedOnStyle: LLVM
BreakBeforeTernaryOperators: false
IndentWidth: 4
TabWidth: 4
UseTab: ForIndentation
```
Code sample:
```c++
enum class TooLongEnumClassName {
  ValueWithVeryLongNameToExceedLineBreakLimit1,
  ValueWithVeryLongNameToExceedLineBreakLimit2,
};

const char *foo(int choose) {
  return static_cast<TooLongEnumClassName>(choose) ==
    TooLongEnumClassName::ValueWithVeryLongNameToExceedLineBreakLimit1 ?
    "Some text string or any other types" : "Another text string or any another types";
}
```

Actual result after apply formatting:
![image](https://user-images.githubusercontent.com/7373914/146194147-5eb4a4ae-e7ad-4745-b4ab-6662f7eca4a3.png)

Expected result: last line should start with `tab` symbol, like all previous.

Note: in case if set **`BreakBeforeTernaryOperators: true`** all lines would be formatted as expected.

**Comment by mydeveloperday** [comment]
What are the tabs doing in the original code? case you show that please.

**Comment by mkurdej** [comment]
Tentative fix: https://reviews.llvm.org/D115803.
