### ISSUE TITLE
How to uppercase or lowercase a string when writing TableGen language?

### ISSUE THREAD

**Issue by zhonhel** [llvm/llvm-project#52721]
Hi all, 

I know there is bang operator !strconcat can concatenate strings, but it seems there is no bang operator can do string uppercase or lowercase.

So, I wonder how to do this when writing TableGen language.

Can anyone help me?

Thank you very much!

**Comment by madhur13490** [comment]
I don't think there is any language supported way to do this.

**Comment by zhonhel** [comment]
@madhur13490 
just like python:
 str.upper() 
 str.lower()

why you think not exist?

**Comment by Paul-C-Anagnostopoulos** [comment]
!upcase and !downcase are on my to-do list. I will try to get to them soon.

I supposed I should name them !toupper and !tolower.

**Comment by Paul-C-Anagnostopoulos** [comment]
> @madhur13490 just like python: str.upper() str.lower()
> 
> why you think not exist?

@zhonhel meant that TableGen has no way to upcase or downcase strings.

**Comment by zhonhel** [comment]
@Paul-C-Anagnostopoulos 
Thank you, I now get his meaning.

**Comment by madhur13490** [comment]
> !upcase and !downcase are on my to-do list. I will try to get to them soon.
> 
> I supposed I should name them !toupper and !tolower.

I will vote for !toupper and !tolower.
