### ISSUE TITLE
[Clang] Wrong order of destruction of temporaries

### ISSUE THREAD

**Issue by JohelEGP** [llvm/llvm-project#52729]
Someone commented at https://cpplang.slack.com/archives/CBTFTLR9R/p1633107202113600
> Hello, I was trying to understand http://eel.is/c++draft/class.temporary#5. Therefore I wrote a snippet to trace the construction and destruction of temporary objects but it seems that GCC and Clang (https://godbolt.org/z/b7WvYE68o) (and also Circle https://godbolt.org/z/xsMdPEcbW) disagree on the output. Which of the three is correct?

**Comment by zygoloid** [comment]
Looks like GCC had a bug here that they fixed in GCC 12. Recent GCC now agrees with Clang and Circle.
