### ISSUE TITLE
[GVN] miscompile of `callbr`

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#52735]
Consider the following code:
```llvm
%struct.percpu_list_node = type { i64, %struct.percpu_list_node* }

define %struct.percpu_list_node* @this_cpu_list_pop() {
  %head = alloca %struct.percpu_list_node*, i32 0, align 8
  br label %for.cond

for.cond:
  callbr void asm sideeffect "", "i,i"(i8* blockaddress(@this_cpu_list_pop, %cleanup), i8* blockaddress(@this_cpu_list_pop, %cleanup.thread19))
          to label %cleanup.thread [label %cleanup, label %cleanup.thread19]

cleanup.thread:
  %x = load %struct.percpu_list_node*, %struct.percpu_list_node** %head, align 8
  br label %return

cleanup:
  br label %for.cond

cleanup.thread19:
  br label %return

return:                                           ; preds = %cleanup.thread, %cleanup.thread19
  %retval.118 = phi %struct.percpu_list_node* [ %x, %cleanup.thread ], [ null, %cleanup.thread19 ]
  ret %struct.percpu_list_node* %retval.118
}
```
```sh
$ opt -passes=gvn reduced.ll -S -o -
```
```llvm
source_filename = "reduced.ll"

%struct.percpu_list_node = type { i64, %struct.percpu_list_node* }

define %struct.percpu_list_node* @this_cpu_list_pop() {
  %head = alloca %struct.percpu_list_node*, i32 0, align 8
  br label %for.cond

for.cond:                                         ; preds = %cleanup, %0
  callbr void asm sideeffect "", "i,i"(i8* blockaddress(@this_cpu_list_pop, %cleanup), i8* blockaddress(@this_cpu_list_pop, %cleanup.thread19))
          to label %cleanup.thread [label %cleanup, label %cleanup.thread19]

cleanup.thread:                                   ; preds = %for.cond
  br label %return

cleanup:                                          ; preds = %for.cond
  br label %for.cond

cleanup.thread19:                                 ; preds = %for.cond
  br label %return

return:                                           ; preds = %cleanup.thread19, %cleanup.thread
  ret %struct.percpu_list_node* null
}
```
That doesn't look quite right to me; we're now unconditionally returning `null`. cc @gwelymernans @jyknight @efriedma-quic @eefriedman 

Reported-by: @compudj

**Comment by efriedma-quic** [comment]
Doesn't look like a miscompile to me.  %x is a load from an uninitialized variable, i.e. undef.  phi of undef and null is null.

**Comment by nickdesaulniers** [comment]
ah, sorry, I missed that.

**Comment by nickdesaulniers** [comment]
I think is a more demonstrative test case:
```c
int* foo (void) {
  int *head;
  asm goto(""::"m"(head):"memory":null);
  return head;
null:
  return (void*)0;
}
```
```sh
$ gcc -O2 /tmp/x.c -S -o -
```
```asm
foo:
.LFB0:
        .cfi_startproc
        movq    -8(%rsp), %rax
        ret
        .p2align 4,,10
        .p2align 3
.L3:
.L2:
        xorl    %eax, %eax
        ret
```
```sh
$ clang -O2 /tmp/x.c -S -o -
```
```asm
foo:                                    # @foo
        .cfi_startproc
# %bb.0:                                # %entry
        #APP
        #NO_APP
.Ltmp0:                                 # Block address taken
# %bb.1:                                # %cleanup
        xorl    %eax, %eax
        retq
```

**Comment by duk-37** [comment]
[see here](https://godbolt.org/z/exscrvqqG)

`-mllvm -enable-gvn-memdep=false` mitigates the issue.

What's seems to be happening is one of two things:
1. GVN is not properly querying MemDep for `callbr` instructions
2. MemDep isn't properly handling `callbr.

**Comment by rickyz** [comment]
Took a look at this, and it looks like AA was missing a case for callbr instructions here:
https://github.com/llvm/llvm-project/blob/591371f7df3cee0429c85f2aeb4a848df8888386/llvm/lib/Analysis/AliasAnalysis.cpp#L685-L708

Sent out https://reviews.llvm.org/D115992, which fixes the test case in https://github.com/llvm/llvm-project/issues/52735#issuecomment-996017004 for me.

**Comment by nickdesaulniers** [comment]
Thanks @rickyz and @duk-37 ! Reopening to request a backport into the 13.0.1 release.

**Comment by tstellar** [comment]
@nikic Is this OK to backport? 9927a06

**Comment by nikic** [comment]
Yeah, should be fine to backport.

**Comment by tstellar** [comment]
Merged: 59289a837b00

**Comment by compudj** [comment]
The following test-case also seems to be fixed by "[AA] Handle callbr instructions in alias analysis" (provided for future reference). The "call 0x2" disappears from the assembler output, likely because the compiler is not aware that the asm goto can modify the variable "a":

void foo (void) {
    int a = 1;
    asm goto ("call 0x0\n\t" : : "m" (a) : "memory" : next1);
next1:
  if (a) {
      asm volatile ("call 0x1\n\t");
  } else {
      asm volatile ("call 0x2\n\t");
  }
}

**Comment by compudj** [comment]
Another test-case provided for future reference:

/*
 * Breaks clang 12/13. I suspect that dead code elimination
 * removes the store to "head" because it is not aware of
 * asm goto. Seems to be fixed by
 * "[AA] Handle callbr instructions in alias analysis".
 */

void foo (void) {
  int *head;
  head = (void*)1;
  asm goto("ud2\n\t"::"m"(head):"memory":null);
null:
  return;
}
