### ISSUE TITLE
[clang] access to extern constinit variable is over-optimized in noexcept block

### ISSUE THREAD

**Issue by bhalevy** [llvm/llvm-project#52742]
See https://godbolt.org/z/jnbaYbf9G for example.

```
#include <memory>

extern constinit int critical_alloc_section;

struct scoped {
    scoped() { ++critical_alloc_section; }
    ~scoped() { --critical_alloc_section; }
};

auto foo() noexcept {
    scoped s;   // optimized away, no side effects happen
    return new char;
}

auto bar() {
    scoped s;   // ok
    return new char;
}
```

Looks like this started in clang 12.0.0 and exists in 13.0.0 through to current trunk.

**Comment by LebedevRI** [comment]
The load/store isn't atomic/volatile, so i don't see why that increment/decrement should be preserved.

**Comment by avikivity** [comment]
Is the compiler assuming the user-replacable `::operator new` can't see the variable `critical_alloc_section`?

**Comment by bhalevy** [comment]
> The load/store isn't atomic/volatile, and there are no fences or anything, so i don't see why that increment/decrement should be preserved.

I would see a point in eliminating them if they were done in sequence, like
```
{
    ++critical_alloc_section;
    --critical_alloc_section;
    return new char;
}
```
But in this case, since the decrement is done in `~scoped`, it needs to be serialized after the call to new, as follows, no?
{
    ++critical_alloc_section;
    auto p = new char;
    --critical_alloc_section;
    return p;
}

(See https://godbolt.org/z/bKenYWqav)

**Comment by LebedevRI** [comment]
> Is the compiler assuming the user-replacable `::operator new` can't see the variable `critical_alloc_section`?

Ah, right. Basically, yes. The fact that it's user-replaceable isn't lowered by clang in any way:
```
  %1 = invoke noalias nonnull dereferenceable(1) i8* @_Znwm(i64 1) #4
<...>
attributes #4 = { builtin allocsize(0) }
```

**Comment by avikivity** [comment]
Isn't this a bug? Does the standard allow the compiler to assume global variables aren't visible to `::operator new`?

**Comment by LebedevRI** [comment]
> Isn't this a bug?

I guess. It's essentially a duplicate of #48366.

> Does the standard allow the compiler to assume global variables aren't visible to `::operator new`?

I believe so, but the problem is that it's probably not so for *replacements*,
and clang provided no indication that said replacement might happen.

Though i'm not sure how it can do that, i suspect it would pessimize the usual case with no replacement,
It can be workarounded via `-fno-builtin` https://godbolt.org/z/d1rsj5odv though.
