### ISSUE TITLE
[clang] Warn on throwing an exception not derived from std::exception

### ISSUE THREAD

**Issue by apolukhin** [llvm/llvm-project#52743]
Throwing an exception that is derived from std::exception is a common practice. Cases when that practice should be skipped are very rare. However, many beginners do not know about that and erroneously do not derive their exceptions from std::exception. There are also cases when classes have close names and users throw the wrong type by a typo.

Please add a warning about throwing an exception not derived from std::exception.

Godbolt playground: https://godbolt.org/z/7Phf3nafW

**Comment by LebedevRI** [comment]
I'm not sure this meets the bar for clang warning, however there's already a clang-tidy check for it:
https://godbolt.org/z/vf75MPha1
