### ISSUE TITLE
Cherry-pick debuginfo non-determinism fixes

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#52757]
Rust backports https://github.com/llvm/llvm-project/commit/3c47c5ca13b8a502de3272e8105548715947b7a8 and https://github.com/llvm/llvm-project/commit/badcd585897253e94b7b2d4e6f9f430a2020d642 to fix debuginfo related non-determinism. Probably these should make it into 13.0.1 as well.

**Comment by tstellar** [comment]
@Melamoto What do you think about backporting these?

**Comment by glandium** [comment]
If you're going to cherry-pick non-determinism fixes, you might want to add 93a20ecee4b6 too.

**Comment by tstellar** [comment]
@glandium Can you open a separate ticket for this?

**Comment by Melamoto** [comment]
LGTM, they are both straightforward changes that should be included.

**Comment by tstellar** [comment]
Merged: 0f915e755eae 35df3f98639e
