### ISSUE TITLE
Calling consteval function for non-type template parameter causes error

### ISSUE THREAD

**Issue by shtirlitz-dev** [llvm/llvm-project#52768]
The following code:

```
consteval int foo(int x) {
    return x;
}

template<int X> constexpr int bar() {
    return foo(X);
}

int main() {
    static_assert(bar<15>() == 15);
}

```
can be compiled in GCC and MSVC but not in clang - [Demo https://gcc.godbolt.org/z/oGfPE6ax9](https://gcc.godbolt.org/z/oGfPE6ax9)
clang says  "call to consteval function 'foo' is not a constant expression" on "foo(X)", although X is a compile-time constant

**Comment by Izaron** [comment]
A possible fix - https://reviews.llvm.org/D119375
