### ISSUE TITLE
ld64.lld: error: relocation BRANCH26 is out of range: -165194492 is not in [-134217728, 134217727]; references _calloc

### ISSUE THREAD

**Issue by glandium** [llvm/llvm-project#52767]
Building Firefox for arm64 macos with disabled optimizations and with lld fails with:
```
ld64.lld: error: relocation BRANCH26 is out of range: -165194492 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165196704 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165196676 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165196144 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165196116 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165196088 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165195984 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165299108 is not in [-134217728, 134217727]; references _malloc
ld64.lld: error: relocation BRANCH26 is out of range: -165308144 is not in [-134217728, 134217727]; references _malloc
ld64.lld: error: relocation BRANCH26 is out of range: -165208212 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165311620 is not in [-134217728, 134217727]; references _malloc
```

STR:
- download https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Fald_IyiRO-ljidFJwvZig/runs/0/artifacts/public/build/testcase.tar.zstd
- `tar --zstd -xf testcase.tar.zstd`
- `cd testcase/toolkit/library/build`
- `clang++ --sysroot /path/to/MacOSX11.0.sdk -F/path/to/MacOSX11.0.sdk/System/Library/PrivateFrameworks -mmacosx-version-min=11.0 -stdlib=libc++ --target=aarch64-apple-darwin -o XUL -Wl,-filelist,XUL.list   -fuse-ld=lld -framework Cocoa -lobjc -framework AudioToolbox -lresolv  ../../../security/nss/lib/crmf/crmf_crmf/libcrmf.a ../../../js/src/build/libjs_static.a ../../../aarch64-apple-darwin/debug/libgkrust.a ../../../security/libnss3.dylib ../../../config/external/lgpllibs/liblgpllibs.dylib ../../../mozglue/build/libmozglue.dylib -dynamiclib -lbsm -framework IOSurface -framework IOKit -framework AudioToolbox -framework CoreMedia -framework VideoToolbox -framework LocalAuthentication -framework Security -lm -framework OpenGL -framework SystemConfiguration -framework AVFoundation -framework CoreUI -framework CoreSymbolication -lcups -framework Foundation -framework CoreFoundation -framework CoreLocation -framework QuartzCore -framework Carbon -framework CoreAudio -framework CoreVideo -framework AudioToolbox -framework AudioUnit -framework AddressBook -framework OpenGL -framework Security -framework ServiceManagement -framework CoreServices -framework ApplicationServices -framework AppKit -weak_framework Metal -weak_framework MediaPlayer`

Cc: @nico @int3 @keith

**Comment by keith** [comment]
I am able to repro, note I had to add `-F/Applications/Xcode-13.2.0-RC1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/PrivateFrameworks` to the args to find `CoreUI`

**Comment by keith** [comment]
@thevinster is this the same as what https://reviews.llvm.org/D116705 should fix?

**Comment by smeenai** [comment]
I patched that locally and it didn't fix this issue :( The error sounds like a thunk isn't getting created at all, which is strange. I imagine `_calloc` is just a reference to the C standard library function, in which case this would be a thunk pointing to a stub; perhaps that's a case we hadn't run into before?

**Comment by glandium** [comment]
BTW, the testcase tarball expires next week, should I upload it somewhere else?

**Comment by smeenai** [comment]
> BTW, the testcase tarball expires next week, should I upload it somewhere else?

Yup, I think that'd be helpful.

CC @nico, who I think looked at the range extension thunk code recently.

**Comment by glandium** [comment]
Here's the same testcase, which shouldn't expire until next year: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Fald_IyiRO-ljidFJwvZig/runs/0/artifacts/public/build/testcase.tar.zstd (I'll update the original comment with this url too)

**Comment by keith** [comment]
I noticed this also doesn't link with ld64:

```
ld: b(l) ARM64 branch out of range (195733676 max is +/-128MB): from _mdb_env_stat.island (0x07C1413C) to _mdb_env_stat (0x136BE9E8) in '_mdb_env_stat.island' for architecture arm64
```

**Comment by int3** [comment]
This issue inspired me to finally implement better diagnostic info for LLD :)

This is what I've got:
```
ld64.lld: error: ../../../aarch64-apple-darwin/debug/libgkrust.a(mdb.o):(symbol _mdb_env_create+0x20): relocation BRANCH26 is out of range: -165194492 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: ../../../aarch64-apple-darwin/debug/libgkrust.a(mdb.o):(symbol _mdb_env_open+0x3d4): relocation BRANCH26 is out of range: -165196704 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: ../../../aarch64-apple-darwin/debug/libgkrust.a(mdb.o):(symbol _mdb_env_open+0x3b8): relocation BRANCH26 is out of range: -165196676 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: ../../../aarch64-apple-darwin/debug/libgkrust.a(mdb.o):(symbol _mdb_env_open+0x1a4): relocation BRANCH26 is out of range: -165196144 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: ../../../aarch64-apple-darwin/debug/libgkrust.a(mdb.o):(symbol _mdb_env_open+0x188): relocation BRANCH26 is out of range: -165196116 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: ../../../aarch64-apple-darwin/debug/libgkrust.a(mdb.o):(symbol _mdb_env_open+0x16c): relocation BRANCH26 is out of range: -165196088 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: ../../../aarch64-apple-darwin/debug/libgkrust.a(mdb.o):(symbol _mdb_env_open+0x104): relocation BRANCH26 is out of range: -165195984 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: ../../../aarch64-apple-darwin/debug/libgkrust.a(mdb.o):(symbol _mdb_fname_init+0x90): relocation BRANCH26 is out of range: -165299108 is not in [-134217728, 134217727]; references _malloc
ld64.lld: error: ../../../aarch64-apple-darwin/debug/libgkrust.a(mdb.o):(symbol _mdb_reader_check0+0xa0): relocation BRANCH26 is out of range: -165308144 is not in [-134217728, 134217727]; references _malloc
ld64.lld: error: ../../../aarch64-apple-darwin/debug/libgkrust.a(mdb.o):(symbol _mdb_env_init_meta+0x54): relocation BRANCH26 is out of range: -165208212 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: ../../../aarch64-apple-darwin/debug/libgkrust.a(mdb.o):(symbol _mdb_env_cwalk+0x120): relocation BRANCH26 is out of range: -165311620 is not in [-134217728, 134217727]; references _malloc
```

I noticed that all the problematic symbols were in a section called `text_env`. This section gets placed late in `__TEXT`, after the `__stubs` section. I believe our branch island code assumes that `__stubs` always occurs after the sections with branches, but in fact this is only true of the `__text` section.

I wouldn't be surprised if ld64's implementation has a similar (wrong) assumption...

**Comment by stheophil** [comment]
We hit the same issue when we compile a large C++ project with Xcode, enable Asan/UBSan, **and** place some code in dedicated sections.

**Comment by stheophil** [comment]
No, ld64 is the Xcode linker right? So we use ld64 and it fails to link.

**Comment by calvin2021y** [comment]
Try 15.0.7 still has this kind problem.   any way to work around ?

**Comment by nullhook** [comment]
i just came across this issue. has anyone found a workaround yet?
