### ISSUE TITLE
Frontend Compile Error: spdlog fails to build on multiple arguments passed to a variadic template function

### ISSUE THREAD

**Issue by batuhanbozyel** [llvm/llvm-project#52770]
Refer to the issue opened here for more information: https://github.com/gabime/spdlog/issues/2212

Preprocessed sources and associated run scripts: [ClangBugReport.zip](https://github.com/llvm/llvm-project/files/7734501/ClangBugReport.zip)

**Comment by Endilll** [comment]
Can't reproduce using Clang 13 and 14 with assertions enabled.
I had to remove a bunch of Apple-specific flags, so there's always a chance that it's actually a downstream issue.
