### ISSUE TITLE
MIPS: .cpsetup broken for n32

### ISSUE THREAD

**Issue by chmeeedalf** [llvm/llvm-project#52785]
MIPS n32 ABI requires '.cpsetup <r>, <off | reg>, <label>' to generate the following sequence:

```
sd $gp, off ($sp)
lui $gp, label    // top half
addiu $gp, label  // bottom half
addu $gp, $gp, r
```

The MIPS code generator currently does not include the final `addu`, leading to crashes in n32 ABI position independent code.

**Comment by chmeeedalf** [comment]
Looking at it more, n32 is supposed to use whatever label, not fixed at __gnu_local_gp

**Comment by atanasyan** [comment]
Could you check that this patch fixes the issue? The patch adds the `addu` instruction only. `__gnu_local_gp` is a separate problem.
[pr52785.patch.txt](https://github.com/llvm/llvm-project/files/7738827/pr52785.patch.txt)

**Comment by rasul247** [comment]
On Fri, Dec 18

**Comment by chmeeedalf** [comment]
Unfortunately that's incomplete.  It's adding the "absolute" address of __gnu_local_gp, which won't work to get a relative address.  It really should be doing what is done for N64 below in the function, from what I can tell.

**Comment by wzssyqa** [comment]
It's due to a typo in `MipsTargetELFStreamer::emitDirectiveCpsetup`
This patch should work:

```
-  if (getABI().IsN32()) {
+#if 0
+  // We haven't support -mabicalls -mno-shared yet.
+  if (-mno-shared) {
     MCSymbol *GPSym = MCA.getContext().getOrCreateSymbol("__gnu_local_gp");
     const MipsMCExpr *HiExpr = MipsMCExpr::create(
         MipsMCExpr::MEK_HI, MCSymbolRefExpr::create(GPSym, MCA.getContext()),
@@ -1273,6 +1275,7 @@ void MipsTargetELFStreamer::emitDirectiveCpsetup(unsigned RegNo,
 
     return;
   }
+#endif
```
