### ISSUE TITLE
Please backport "[asan] Fix "no matching function" on GCC" (Posix/unpoison-alternate-stack test) to 13.x

### ISSUE THREAD

**Issue by mgorny** [llvm/llvm-project#52789]
ommit 4b768eeb976ec15a2701f9a7b3eac2b0b43e8a7d
Author: Vitaly Buka <vitalybuka@google.com>
Date:   2021-11-13 02:41:50 +0100

    [asan] Fix "no matching function" on GCC

CC @vitalybuka

**Comment by tstellar** [comment]
@vitalybuka Is this OK to backport? 4b768ee

**Comment by vitalybuka** [comment]
> @vitalybuka Is this OK to backport? [4b768ee](https://github.com/llvm/llvm-project/commit/4b768eeb976ec15a2701f9a7b3eac2b0b43e8a7d)

yes

**Comment by tstellar** [comment]
Merged: 2c6c3e4b713b
