### ISSUE TITLE
With LTO, it's not clear which TU errors from inline asm come from

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#52781]
Here's a file using intel inline asm:

```
% cat asm.c
int main() {
  asm("int3");
}
```

When we compile it for arm64, we get a nice diag at compile time:

```
% out/gn/bin/clang --target=arm64-linux-unknown asm.c -fuse-ld=lld --sysroot ~/src/chrome/src/build/linux/debian_sid_arm64-sysroot
asm.c:2:7: error: unrecognized instruction mnemonic, did you mean: hint?
  asm("int3");
      ^
<inline asm>:1:2: note: instantiated into assembly here
        int3
        ^
1 error generated.
```

But if we use LTO, we get a less nice diag at link time:

```
% out/gn/bin/clang --target=arm64-linux-unknown asm.c -fuse-ld=lld --sysroot ~/src/chrome/src/build/linux/debian_sid_arm64-sysroot -flto=thin
ld.lld: error: <inline asm>:1:2: unrecognized instruction mnemonic, did you mean: hint?
        int3
        ^

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Showing the line number is probably difficult (I guess clang stashes the asm sourceloc before it calls into the asm parser and then refers to it from an error callback, and that information is long gone at link time. But maybe clang could insert a line marker in inline asm in lto mode or something?). But printing the current TU should be easy and would limit things at least a bit – in a project with many TUs it'd at least be clear which TU the error is for.

**Comment by MaskRay** [comment]
Created https://reviews.llvm.org/D118434 (`[lld] Add module name to LTO inline asm diagnostic`), which can improve the ThinLTO case. It's very difficult to improve the regular LTO case.

**Comment by nico** [comment]
Sorry, I missed the fix for this back then. Thanks much for the fix! Much better :)
