### ISSUE TITLE
[OpenMP] clang option for selecting OpenMP spec version

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#52784]
`clang --help` doesn't print one
No luck with https://openmp.llvm.org/index.html
Need documentation

**Comment by chrstphrchvz** [comment]
Is this referring to https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-fopenmp-version (e.g. `-fopenmp-version=45` to select OpenMP 4.5)?

**Comment by shiltian** [comment]
@chrstphrchvz right. That's the one. It is supposed to show in `clang --help`, but because there is no corresponding helper text, it doesn't show.

**Comment by shiltian** [comment]
Fixed in 0060060fef5da582799a706b6ba8c6ec9fcda2a2.
