### ISSUE TITLE
Please backport "[msan] Disabled test failing on new GLIBC" to 13.x

### ISSUE THREAD

**Issue by mgorny** [llvm/llvm-project#52798]
Good news: this is the last backport necessary to make compiler-rt sanitizer tests pass again.

commit 118757af11954ffd43c16a41e39348e0907bba92
Author: Vitaly Buka <vitalybuka@google.com>
Date:   2021-11-15 20:18:40 +0100

    [msan] Disabled test failing on new GLIBC

CC @vitalybuka

**Comment by tstellar** [comment]
@vitalybuka Is this OK to backport?

**Comment by vitalybuka** [comment]
> @vitalybuka Is this OK to backport?

Yes.

**Comment by tstellar** [comment]
Merged: c1b51f098751
