### ISSUE TITLE
Wrong operand returned in InstructionSimplify: simplifyDivRem

### ISSUE THREAD

**Issue by choller** [llvm/llvm-project#52793]
This piece of code is returning the wrong value:

https://github.com/llvm/llvm-project/blob/936a67f089efd31354cf1f1f3b864b81fb5aad0e/llvm/lib/Analysis/InstructionSimplify.cpp#L1012

The author probably meant to return `Op0` but returned `X` because that's what the comment has as `Op0`. However, `X` also happens to be the tempval used for matching, so this likely returns some garbage.

Cc @davidtgoldblatt @sylvestre

**Comment by choller** [comment]
Looking closer, X is populated in the latter two parts of the condition, so the bug likely only triggers if one of the first two conditions is true. This probably needs to be broken up into multiple returns?

**Comment by rickyz** [comment]
Please correct me if I'm mistaken, but returning `X` here looks correct to me - `Op0` corresponds to `X * Y` in the comments above, which wouldn't be the correct result.

`X` should be populated by the `m_Value` match at line 1004:
https://github.com/llvm/llvm-project/blob/936a67f089efd31354cf1f1f3b864b81fb5aad0e/llvm/lib/Analysis/InstructionSimplify.cpp#L1001-L1014
(see the comments at https://github.com/llvm/llvm-project/blob/ff94bd1bc92efb2a116fb2963d0425a529d3be89/llvm/include/llvm/IR/PatternMatch.h for an example of how this matching API is used)

**Comment by choller** [comment]
@rickyz thanks for clarifying, I think I misunderstood how the pattern matching API binds variables here and you are right. I am seeing a weird local result in this optimization that gave me the impression that this is wrong. I will double check if this is not some folding issue and I am misinterpreting the result. Thanks for checking :)
