### ISSUE TITLE
Please backport "[sanitizer] Don't test __pthread_mutex_lock with GLIBC 2.34" to 13.x

### ISSUE THREAD

**Issue by mgorny** [llvm/llvm-project#52796]
commit e60b3fcefa62311a93a9f7c8589a1da5f25b1ba9
Author: Vitaly Buka <vitalybuka@google.com>
Date:   2021-11-13 08:38:59 +0100

    [sanitizer] Don't test __pthread_mutex_lock with GLIBC 2.34

Applies cleanly.

CC @vitalybuka

**Comment by tstellar** [comment]
@vitalybuka Is this OK to backport? e60b3fc

**Comment by vitalybuka** [comment]
yes

> @vitalybuka Is this OK to backport? [e60b3fc](https://github.com/llvm/llvm-project/commit/e60b3fcefa62311a93a9f7c8589a1da5f25b1ba9)

**Comment by tstellar** [comment]
Merged: bdd28a2a138f
