### ISSUE TITLE
Please backport "[sanitizer] Intercept lstat on Linux" to 13.x

### ISSUE THREAD

**Issue by mgorny** [llvm/llvm-project#52797]
commit 39ead64e3f73045c7e0c72aed08c14b277828fb4
Author: Vitaly Buka <vitalybuka@google.com>
Date:   2021-11-06 08:49:51 +0100

    [sanitizer] Intercept lstat on Linux
    
    It's availible from GLIBC 2.33
    Fixes use-of-uninitialized-value llvm/lib/Support/Unix/Path.inc:467:29 in llvm::sys::fs::remove(llvm::Twine const&, bool)

CC @vitalybuka 

This fixes test failures for me.

**Comment by tstellar** [comment]
This fix does not apply cleanly to the release branch.  Could someone resolve the merge conflicts and push it to a github fork.

**Comment by vitalybuka** [comment]
you need both:
4e1a6c07052b466a2a1cd0c3ff150e4e89a6d87a
and then
39ead64

**Comment by mgorny** [comment]
Ah, sorry, I didn't notice because I applied 4e1a6c07052b466a2a1cd0c3ff150e4e89a6d87a earlier.

**Comment by tstellar** [comment]
Merged: b40f07b048c4 abc0cf92bb14
