### ISSUE TITLE
Assertion failed: (types.size()), function getMLIRType, file clang-mlir.cc, line 5402.

### ISSUE THREAD

**Issue by tipparajuv** [llvm/llvm-project#52795]
Hello, can you please recommend an investigation path? Compilation fails with:

RecordType 0x1429b7fc0 'struct __sFILEX'
`-Record 0x1429b7f38 '__sFILEX'
ST: %struct.__sFILEX = type opaque
fields
types
Assertion failed: (types.size()), function getMLIRType, file clang-mlir.cc, line 5402.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: build/bin/mlir-clang tools/mlir-clang/Test/polybench/linear-algebra/blas/gemm/gemm.c -I llvm-project/mlir/tools/polymer/example/polybench/utilities/ --raise-scf-to-affine -S
1.	<eof> parser at end of file
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mlir-clang               0x0000000102b11584 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 68
1  mlir-clang               0x0000000102b11a78 PrintStackTraceSignalHandler(void*) + 28
2  mlir-clang               0x0000000102b0fbec llvm::sys::RunSignalHandlers() + 124
3  mlir-clang               0x0000000102b13758 SignalHandler(int) + 220
4  libsystem_platform.dylib 0x00000001a1ed04e4 _sigtramp + 56
5  libsystem_pthread.dylib  0x00000001a1eb8eb0 pthread_kill + 288
6  libsystem_c.dylib        0x00000001a1df6314 abort + 164
7  libsystem_c.dylib        0x00000001a1df572c err + 0
8  mlir-clang               0x00000001003fca74 MLIRASTConsumer::getMLIRType(clang::QualType, bool*, bool) + 3136
9  mlir-clang               0x00000001003fbec4 MLIRASTConsumer::getMLIRType(clang::QualType, bool*, bool) + 144
10 mlir-clang               0x00000001003fd120 MLIRASTConsumer::getMLIRType(clang::QualType, bool*, bool) + 4844
11 mlir-clang               0x00000001003fc7c0 MLIRASTConsumer::getMLIRType(clang::QualType, bool*, bool) + 2444
12 mlir-clang               0x00000001003fbec4 MLIRASTConsumer::getMLIRType(clang::QualType, bool*, bool) + 144
13 mlir-clang               0x00000001003fbfd4 MLIRASTConsumer::getMLIRType(clang::QualType, bool*, bool) + 416
14 mlir-clang               0x00000001003fd120 MLIRASTConsumer::getMLIRType(clang::QualType, bool*, bool) + 4844
15 mlir-clang               0x00000001003fd120 MLIRASTConsumer::getMLIRType(clang::QualType, bool*, bool) + 4844
16 mlir-clang               0x000000010042f158 MLIRScanner::VisitDeclRefExpr(clang::DeclRefExpr*) + 976
17 mlir-clang               0x0000000100401c9c clang::StmtVisitorBase<std::__1::add_pointer, MLIRScanner, ValueCategory>::Visit(clang::Stmt*) + 5072
18 mlir-clang               0x00000001004315f8 MLIRScanner::VisitCastExpr(clang::CastExpr*) + 4564
19 mlir-clang               0x0000000100485654 clang::StmtVisitorBase<std::__1::add_pointer, MLIRScanner, ValueCategory>::VisitImplicitCastExpr(clang::ImplicitCastExpr*) + 32
20 mlir-clang               0x0000000100401bdc clang::StmtVisitorBase<std::__1::add_pointer, MLIRScanner, ValueCategory>::Visit(clang::Stmt*) + 4880
21 mlir-clang               0x000000010041d7e0 MLIRScanner::VisitCallExpr(clang::CallExpr*)::$_5::operator()(clang::Expr*) const + 48
22 mlir-clang               0x000000010041b0bc MLIRScanner::VisitCallExpr(clang::CallExpr*) + 25716
23 mlir-clang               0x0000000100401a8c clang::StmtVisitorBase<std::__1::add_pointer, MLIRScanner, ValueCategory>::Visit(clang::Stmt*) + 4544
24 mlir-clang               0x00000001004d5988 MLIRScanner::VisitCompoundStmt(clang::CompoundStmt*) + 136
25 mlir-clang               0x0000000100400eec clang::StmtVisitorBase<std::__1::add_pointer, MLIRScanner, ValueCategory>::Visit(clang::Stmt*) + 1568
26 mlir-clang               0x00000001003fb3c0 MLIRScanner::MLIRScanner(MLIRASTConsumer&, mlir::FuncOp, clang::FunctionDecl const*, mlir::OwningOpRef<mlir::ModuleOp>&, LowerToInfo&) + 4404
27 mlir-clang               0x00000001004035ec MLIRScanner::MLIRScanner(MLIRASTConsumer&, mlir::FuncOp, clang::FunctionDecl const*, mlir::OwningOpRef<mlir::ModuleOp>&, LowerToInfo&) + 68
28 mlir-clang               0x0000000100436160 MLIRASTConsumer::run() + 684
29 mlir-clang               0x0000000100437048 MLIRASTConsumer::HandleTopLevelDecl(clang::DeclGroupRef) + 1292
30 mlir-clang               0x00000001087f46e8 clang::ParseAST(clang::Sema&, bool, bool) + 484
31 mlir-clang               0x0000000104f16338 clang::ASTFrontendAction::ExecuteAction() + 264
32 mlir-clang               0x0000000104f15a34 clang::FrontendAction::Execute() + 120
33 mlir-clang               0x000000010043d124 parseMLIR(char const*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, mlir::OwningOpRef<mlir::ModuleOp>&, llvm::Triple&, llvm::DataLayout&) + 4204
34 mlir-clang               0x000000010043a000 main + 2808
35 dyld                     0x000000012a8810f4 start + 520
Abort trap: 6

**Comment by joker-eph** [comment]
> build/bin/mlir-clang 

This isn't something that exist in this repo, you likely should report this issue to the relevant project.
