### ISSUE TITLE
Please backport b432583d28ee99313fa834139be9535639957d76 and 2d8c18fbbdd1b07ab0d36ac49ef63f4d243afb8b

### ISSUE THREAD

**Issue by brooksdavis** [llvm/llvm-project#52808]
b432583d28ee99313fa834139be9535639957d76  - updates to tests which allow 2d8c18f to apply cleanly
2d8c18fbbdd1b07ab0d36ac49ef63f4d243afb8b -  fixes a regression in llvm11 for Via Padlock instructions. We've applied this to all relevant LLVM versions in FreeBSD's base system and ports collection.

**Comment by brooksdavis** [comment]
Should be part of the "LLVM 13.0.1 release" milestone, but I don't seem to have permission to do that.

**Comment by tstellar** [comment]
@topperc What do you think about backporting these?

**Comment by topperc** [comment]
We can backport them.

**Comment by tstellar** [comment]
Merged: c95753ff5c11 ae24102617c9
