### ISSUE TITLE
cppcoreguidelines-prefer-member-initializer: bad fix-it for delegating constructor

### ISSUE THREAD

**Issue by sfc-gh-sgiesecke** [llvm/llvm-project#52818]
`cppcoreguidelines-prefer-member-initializer` produces a bad fix-it for delegating constructor that set member in their body, e.g.
```
struct Foo  {
    Foo() = default;
    Foo(int) : Foo() { m_bar = 3; }

    int m_bar;
};
```

The suggested fix-it would rewrite this as:
```
    Foo(int) : Foo(), m_bar(3) {}
```
which is invalid.

See https://godbolt.org/z/Yvb1ovnsr

In fact, it doesn't seem it makes sense for the rule to diagnose this case at all. While this may be considered bad style, it can't be easily changed without introducing a new constructor overload.

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D157242
