### ISSUE TITLE
Visibility of current scope is not properly considered when evaluating a concept.

### ISSUE THREAD

**Issue by oberdorc** [llvm/llvm-project#52816]
I have a concept 'visible' which checks if a certain member function of T is present. It will evaluate to 1 if the function is public and 0 íf it is private. Things, however change if the concept is evaluated from a befriended scope, i.e. 'struct Pred' in the example.Then the concept evaluates to 1 regardless of scope and despite the member function being private. The GNU compiler produces the expected correct output in this case. Output and demonstration source code is attached.

[concepts_console.txt](https://github.com/llvm/llvm-project/files/7750934/concepts_console.txt)

[concepts_source.txt](https://github.com/llvm/llvm-project/files/7750915/concepts_source.txt)

**Comment by usx95** [comment]
This looks like a bug in gcc which was fixed. Both gcc and clang produce same output at trunk.
https://godbolt.org/z/8xahsWeTz
Feel free to reopen to discuss more.

**Comment by oberdorc** [comment]
First, I am not an expert on interpreting the C++ standard. However, I believe that the former result seen in GCC should be the correct one - so after the 'fix' it became wrong?!

Let me argue on this: Purpose of the applied concept constraint is to verify that a certain member function is present and can be invoked (from the current scope). So for Foo_1, it is expected to evaluate to false in all cases. The same is true for Foo_3/Foo_4 as we look for a public member function and the evaluation result is true in all cases. Critical is the case with Foo_3: private member but with class Pred as a friend. The evalution from within Pred should pass as it is a friend. In all other cases, however, this should fail. After the fix  in gcc trunk the concept now always evaluates to true although the respective function cannot be seen nor acceesed from outside scope.

The standard says the following (13.7.9 Concept Definitions, paragraph 5): 
"A concept is not instantiated ([[temp.spec]](https://eel.is/c++draft/temp.spec))[.](https://eel.is/c++draft/temp.concept#5.sentence-1)
[Note [1](https://eel.is/c++draft/temp.concept#note-1): A concept-id ([[temp.names]](https://eel.is/c++draft/temp.names)) is evaluated as an expression[.](https://eel.is/c++draft/temp.concept#5.sentence-2)
A concept cannot be explicitly instantiated ([[temp.explicit]](https://eel.is/c++draft/temp.explicit)), explicitly specialized ([[temp.expl.spec]](https://eel.is/c++draft/temp.expl.spec)), or partially specialized ([[temp.spec.partial]](https://eel.is/c++draft/temp.spec.partial))[.](https://eel.is/c++draft/temp.concept#5.sentence-3)
— end note]"

From this, I conclude that the concept needs to be evaluated ("as an expression") whenever and wherever it occurs at compile-time. So, within the assignment in the definition of Pred I would expect that the current scope matters (which is that of Pred and access to Foo_2  is permitted considering friendship). Later "visible" shall be reevaluted in the scope of the main function and should therefore return a different result.

So this is my take on the matter: The current answer is wrong for both gcc and clang and the real issue has not been solved despite that the inconstency between gcc/clang was resolved. Behavior should be like before with gcc-10.4!
