### ISSUE TITLE
[clang-format] Wrong indent in namespace after trailing requires clause

### ISSUE THREAD

**Issue by higaski** [llvm/llvm-project#52834]
A trailing requires clause on a function seems to confuse clang-formats indentation rules for namespaces. Although my .clang-format files contains `NamespaceIndentation: None` I get some indentation on the following snippet

```cpp
template<int I>
constexpr void foo requires(I == 42) {}

namespace ns {

  void foo() {}

}  // namespace ns
```

This happens with version 13.0.0, I haven't tested anything else.
Removing the requires clause or placing it after the closing angle bracket works as expected.

[clang-format.zip](https://github.com/llvm/llvm-project/files/7762456/clang-format.zip)

**Comment by mkurdej** [comment]
That's very closely related to #50645, which has been fixed in commit https://github.com/llvm/llvm-project/commit/960712ccc7103ded3d95e10c61516126836a1eba.
But this one is still present on main (tested with clang-format at commit a2120f6b).

**Comment by mkurdej** [comment]
Review: https://reviews.llvm.org/D116183.
