### ISSUE TITLE
readability-make-member-function-const: misses opportunity to make function const with extra parentheses in return statement

### ISSUE THREAD

**Issue by sfc-gh-sgiesecke** [llvm/llvm-project#52838]
The clang-tidy check readability-make-member-function-const misses the opportunity to make function const with an extra parentheses in return statement, e.g.
```
struct Foo  {
    int getFoo() { return (m_bar); }

    int m_bar;
};
```

When the extra parentheses are removed, it is diagnosed:
```
struct Foo  {
    int getFoo() { return m_bar; }

    int m_bar;
};
```

See https://godbolt.org/z/sMKKfPaqq

**Comment by Izaron** [comment]
Thanks for the issue! A possible fix here: https://reviews.llvm.org/D122075
