### ISSUE TITLE
Permission for flang in 11.1.0 is only user-executable

### ISSUE THREAD

**Issue by zerothi** [llvm/llvm-project#52832]
When installing llvm 11.1.0 with flang support using this:
```shell
cmake .. -DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra;compiler-rt;libcxx;libclc;libcxxabi;lld;lldb;openmp;polly;parallel-libs;flang'
cmake --build .
cmake --build . --target install
```
then the flang executable has permission, 700, and not 755 as it should be?
I am currently testing this in 12 as well.

**Comment by kiranchandramohan** [comment]
The driver named `flang` is a temporary driver and will be replaced with the driver named `flang-new`. Are the permissions of `flang-new` correct? Did you see this in 12 as well?

**Comment by zerothi** [comment]
> The driver named `flang` is a temporary driver and will be replaced with the driver named `flang-new`. Are the permissions of `flang-new` correct? Did you see this in 12 as well?

In 12 the permission is correct, but no `flang-new` is present? Should there be ?

**Comment by zerothi** [comment]
ping

**Comment by zerothi** [comment]
I'll close this, and re-open if it happens again :)
