### ISSUE TITLE
weird incosistent instrumented lld behaviour

### ISSUE THREAD

**Issue by meongmeongasd** [llvm/llvm-project#52836]
Windows 11 
C:\0>lld-link --version
LLD 14.0.0 

set LLVM_PROFILE_FILE=code-%p.profraw

C:\0>D:\Program_Files\llvm-14-msvc2\bin\lld
lld is a generic driver.
Invoke ld.lld (Unix), ld64.lld (macOS), lld-link (Windows), wasm-ld (WebAssembly) instead
//produce 46mb .profraw

C:\0>D:\Program_Files\llvm-14-msvc2\bin\lld-link
lld-link: error: no input files
//produce empty  .profraw

C:\0>D:\Program_Files\llvm-14-msvc2\bin\ld.lld
ld.lld: error: no input files
//produce empty  .profraw

C:\0>D:\Program_Files\llvm-14-msvc2\bin\ld64.lld
ld64.lld: error: must specify -arch
//produce 46mb .profraw

C:\0>D:\Program_Files\llvm-14-msvc2\bin\wasm-ld
wasm-ld: error: no input files
//produce empty  .profraw

C:\0>D:\Program_Files\llvm-14-msvc2\bin\lld.exe -flavor link
lld: error: no input files
//produce empty  .profraw

C:\0>D:\Program_Files\llvm-14-msvc2\bin\lld-link.exe /nologo tools\lld\tools\lld\CMakeFiles\lld.dir\lld.cpp.obj tools\lld\tools\lld\CMakeFiles\lld.dir\D_\Program_Files\GitHub\llvm-project\llvm\resources\windows_version_resource.rc.res  /out:bin\lld.exe /implib:lib\lld.lib /pdb:bin\lld.pdb /version:0.0 /STACK:10000000 /libpath:D:/Program_Files/llvm-14-msvc/lib/clang/14.0.0/lib/windows /INCREMENTAL:NO /subsystem:console  lib\LLVMSupport.lib  lib\lldCommon.lib  lib\lldCOFF.lib  lib\lldELF.lib  lib\lldMachO.lib  lib\lldMinGW.lib  lib\lldWasm.lib  lib\lldCOFF.lib  lib\LLVMDebugInfoPDB.lib  "D:\Program_Files\VS2022\IDE\DIA SDK\lib\amd64\diaguids.lib"  lib\LLVMLibDriver.lib  lib\LLVMWindowsManifest.lib  lib\lldCommon.lib  lib\LLVMOption.lib  lib\LLVMX86CodeGen.lib  lib\LLVMAsmPrinter.lib  lib\LLVMDebugInfoMSF.lib  lib\LLVMGlobalISel.lib  lib\LLVMSelectionDAG.lib  lib\LLVMCFGuard.lib  lib\LLVMX86AsmParser.lib  lib\LLVMX86Desc.lib  lib\LLVMX86Disassembler.lib  lib\LLVMMCDisassembler.lib  lib\LLVMX86Info.lib  lib\LLVMLTO.lib  lib\LLVMCodeGen.lib  lib\LLVMExtensions.lib  lib\Polly.lib  lib\PollyISL.lib  lib\LLVMPasses.lib  lib\LLVMTarget.lib  lib\LLVMObjCARCOpts.lib  lib\LLVMCoroutines.lib  lib\LLVMipo.lib  lib\LLVMBitWriter.lib  lib\LLVMInstrumentation.lib  lib\LLVMLinker.lib  lib\LLVMFrontendOpenMP.lib  lib\LLVMScalarOpts.lib  lib\LLVMAggressiveInstCombine.lib  lib\LLVMInstCombine.lib  lib\LLVMIRReader.lib  lib\LLVMAsmParser.lib  lib\LLVMVectorize.lib  lib\LLVMTransformUtils.lib  lib\LLVMAnalysis.lib  lib\LLVMProfileData.lib  lib\LLVMDebugInfoDWARF.lib  lib\LLVMObject.lib  lib\LLVMBitReader.lib  lib\LLVMCore.lib  lib\LLVMRemarks.lib  lib\LLVMBitstreamReader.lib  lib\LLVMTextAPI.lib  lib\LLVMMCParser.lib  lib\LLVMMC.lib  lib\LLVMBinaryFormat.lib  lib\LLVMDebugInfoCodeView.lib  lib\LLVMSupport.lib  psapi.lib  shell32.lib  ole32.lib  uuid.lib  advapi32.lib  delayimp.lib  -delayload:shell32.dll  -delayload:ole32.dll  lib\LLVMDemangle.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
//produce empty  .profraw

built by
C:\0>clang-cl -v
clang version 14.0.0 (https://github.com/llvm/llvm-project.git 1448aa9dbdd9e3e194486bc8fbfe2ed4e480217b)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: D:\Program_Files\llvm-14-msvc\bin

tested with -fprofile-instr-generate or -fprofile-generate
my intent here to profile lld-link thin-lto process then found these behaviour
cant profile lld-link :(

https://user-images.githubusercontent.com/80136789/147093042-2ebaeeee-e8e9-4a50-995c-a8afd46084b0.mp4

**Comment by MaskRay** [comment]
This is expected behavior. In the simplest case, these linkers can be used via `ld.lld a.o`. When there is no input file, the platform linkers they try to be a drop-in replacement have the `no input files` (the diagnostic may or may not be different; for ld.lld GNU ld's diagnostic is exactly the same).

**Comment by meongmeongasd** [comment]
Thanks for the answer, sir. Should i make separate issue for lld-link behaviour that produce empty .profraw?

**Comment by MaskRay** [comment]
> Thanks for the answer, sir. Should i make separate issue for lld-link behaviour that produce empty .profraw?

Yes, try not to mix issues in one PR.

(I was going to suggest "For lld-link, considering re-linking with `lld-link /reproduce:repro.tar` and uploading the reproduce tarball." but you invocation used no file.)

**Comment by rasul247** [comment]
Hey
