### ISSUE TITLE
Failed to compile project with my build of llvm (macOS)

### ISSUE THREAD

**Issue by rruipinheiro** [llvm/llvm-project#52842]
Hello,
I'm trying to compile my project with my build of llvm, for some reason I get a lot of compile errors.

My main.cpp file:
```
#include <iostream>

int main() {
  std::cout << "Hello world!" << std::endl;

  return 0;
}
```

If I call clang++ like this:
``` 
./path/bin/clang++ main.cpp -o main 
```
I get this error:

```
In file included from /path/main.cpp:1:
In file included from /usr/local/bin/../include/c++/v1/iostream:37:
In file included from /usr/local/bin/../include/c++/v1/ios:214:
In file included from /usr/local/bin/../include/c++/v1/__locale:15:
In file included from /usr/local/bin/../include/c++/v1/string:519:
In file included from /usr/local/bin/../include/c++/v1/__debug:14:
In file included from /usr/local/bin/../include/c++/v1/iosfwd:98:
/usr/local/bin/../include/c++/v1/wchar.h:119:15: fatal error: 'wchar.h' file not found
#include_next <wchar.h>
              ^~~~~~~~~
```

If I call clang and add the headers like this:

``` 
./path/bin/clang++ main.cpp -o main -I /Library/Developer/CommandLineTools/usr/include/c++/v1/
```

I get this error:

```
In file included from /path/main.cpp:1:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/iostream:37:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/ios:214:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:95:
/Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:136:77: error: use of undeclared identifier 'wcschr'
wchar_t* __libcpp_wcschr(const wchar_t* __s, wchar_t __c) {return (wchar_t*)wcschr(__s, __c);}
                                                                            ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:143:87: error: use of undeclared identifier 'wcspbrk'
wchar_t* __libcpp_wcspbrk(const wchar_t* __s1, const wchar_t* __s2) {return (wchar_t*)wcspbrk(__s1, __s2);}
                                                                                      ^
.........
```

I already try to add other header paths and compile flags like: `-std=c++11` and `-stdlib=libc++` but nothing seems to work...
Thanks!

**Comment by keith** [comment]
I've seen issues like this that are specific to Xcode's command line tools. If you point it at a full version of Xcode instead (most easily done by running your command prefixed with `xcrun`) does it work in this same case?

Not saying that's a good solution, but it would help narrow this down

**Comment by Naville** [comment]
You'll almost always certainly need a toolchain ``-DLLVM_CREATE_XCODE_TOOLCHAIN=ON`` for proper Xcode support

**Comment by Naville** [comment]
You could try adding ``-v`` to your invocation, something like this:

```
./path/bin/clang++ -v main.cpp -o main -I /Library/Developer/CommandLineTools/usr/include/c++/v1/
```

which gives your something like the following:

```
#include "..." search starts here:
#include <...> search starts here:
 /Library/Developer/Toolchains/XXX.xctoolchain/usr/bin/../include/c++/v1
 /Library/Developer/Toolchains/XXX.xctoolchain/usr/lib/clang/12.0.0/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/Library/Frameworks (framework directory)
```

Note the ``12.0.0`` in ``usr/lib/clang/12.0.0/include``, that part is your clang's LLVM version.
If your LLVM's version is not the same as Apple has configured theirs, (Plot twist: They **ARE** different) Clang will also fail to find those headers

**Comment by rruipinheiro** [comment]
Building with the flag `-DLLVM_CREATE_XCODE_TOOLCHAIN=ON`  and having the same version of apple clang doesn't resolve the errors... also, `ignoring nonexistent directory "XXXXXXXX"` this doesn't appear... I'm missing something else, for sure...

**Comment by fhahn** [comment]
I think you need to specify `-isysroot` to clang, with the path to the SDK to use. You can use `xcrun` to get the SDK path, e.g. `xcrun --sdk macosx --show-sdk-path`.

**Comment by Naville** [comment]
Or, just use Apple's llvm fork

**Comment by fhahn** [comment]
> Or, just use Apple's llvm fork

I might be wrong, but I don't think the fork tries to find a sys root to use automatically either.

@rruipinheiro please feel free to re-open the issue if `-isysroot` doesn't work for you

**Comment by Naville** [comment]
> I might be wrong, but I don't think the fork tries to find a sys root to use automatically either.

I mean the fully packaged Swift Toolchain, which from personal experience works the best with Xcode
