### ISSUE TITLE
[coroutine] Clang fails to compile when promise_type doesn't have return_void

### ISSUE THREAD

**Issue by debashish-ghosh** [llvm/llvm-project#52847]
In [this](https://godbolt.org/z/5f744nbbc) code, when the control reaches the end of the coroutine, it should be able to call `promise_type::return_void()`. If the method is not defined, then it is UB. When control doesn't reach the end of coroutine, then the behaviour is well-defined (which is the case here). **Clang fails to compile this**.

**Comment by ChuanqiXu9** [comment]
This should be addressed like: https://godbolt.org/z/1vxvbrq4o

**Comment by debashish-ghosh** [comment]
Looks like the LLVM source contains the fix now. It would be better to link it to this bug for tracking purposes.
