### ISSUE TITLE
Using an enum constant defined within a struct and brought into scope using a `using enum` statement within a compound expression causes a segfault

### ISSUE THREAD

**Issue by Qix-** [llvm/llvm-project#52856]
Relevant Godbolt: https://godbolt.org/z/9cqnvTG3q

The following snippet fails to compile:

```c++
//namespace Bar { // fixes everything
struct Bar {
	enum Foo {
		A = 1,
		B = 2,
		C = 4
	};
};

using B = Bar;

int main() {
	using enum B::Foo;

	// Using individual `using`
	// statements per-constant
	// doesn't make any difference,
	// except when lowering from
	// -std=c++20 to -std=c++17, which
	// compiles fine.
	//using B::Foo::A;
	//using B::Foo::B;

	int f = (A|B); // segfault
	//int f = (A); // weird error
	//int f = A|B; // OK
}
```

Uncommenting the various marked lines will demonstrate a few different strange failure cases, namely:

- Putting the `using`'d enum into a `namespace` as opposed to a `struct` fixes the issue entirely, including the following cases.
- If the child of the compound expresson node is another expression type (that isn't an enum constant expression), then the compiler segfaults.
- If the child of the compound expresson node is simply an enum constant (as opposed to another expression type), the compiler fails with a diagnostic about overloaded function addresses (not sure what that's about).
- Not putting the constants into a compound expresson (`()`) at all causes no error.

**Comment by JJL772** [comment]
Also hit this on a C++20 project, clang version:
```
LLVM.org clang version 14.0.0 (https://github.com/llvm/llvm-project cc45a13422ca78ea750cce0fc502ac44b784d811)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```


This seems to happen when `using enum` is in function scope, moving the `using enum` into a non-function parent scope will work fine. The following code compiles fine, for example:
```cc
class Thing {
public:
    enum MyEnum {
        A = 1, B = 2
    };
};

class Other {
    using enum Thing::MyEnum;
    void Test() {
        auto n =(A|B); // Compiles fine 
        auto b = (A); // Compiles fine too, if using enum was in this function, it would fail with a funny error.
    }
};
```

[Another reproduction of the bug in case there aren't enough already :)](https://godbolt.org/z/67e4jYeqe)

**Comment by Qix-** [comment]
Thanks for the update!
