### ISSUE TITLE
Failed to build LLVM on OS X Mavericks 10.9.4 using GCC 5.1

### ISSUE THREAD

**Issue by cozycactus** [llvm/llvm-project#52871]
Can i get a help?

cozys-iMac:build cozy$ CC=$HOME/toolchains/bin/gcc CXX=$HOME/toolchains/bin/g++ cmake -G "Ninja" ../llvm -DCMAKE_CXX_LINK_FLAGS="-Wl,-rpath,$HOME/toolchains/lib64 -L$HOME/toolchains/lib64"
-- The C compiler identification is GNU 5.1.0
-- The CXX compiler identification is GNU 5.1.0
-- The ASM compiler identification is GNU
-- Found assembler: /Users/cozy/toolchains/bin/gcc
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /Users/cozy/toolchains/bin/gcc
-- Check for working C compiler: /Users/cozy/toolchains/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /Users/cozy/toolchains/bin/g++
-- Check for working CXX compiler: /Users/cozy/toolchains/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to Debug
-- Found libtool - /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for errno.h
-- Looking for errno.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for link.h
-- Looking for link.h - not found
-- Looking for malloc/malloc.h
-- Looking for malloc/malloc.h - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for signal.h
-- Looking for signal.h - found
-- Looking for sys/ioctl.h
-- Looking for sys/ioctl.h - found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - found
-- Looking for sys/param.h
-- Looking for sys/param.h - found
-- Looking for sys/resource.h
-- Looking for sys/resource.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for sysexits.h
-- Looking for sysexits.h - found
-- Looking for termios.h
-- Looking for termios.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for valgrind/valgrind.h
-- Looking for valgrind/valgrind.h - not found
-- Looking for fenv.h
-- Looking for fenv.h - found
-- Looking for FE_ALL_EXCEPT
-- Looking for FE_ALL_EXCEPT - found
-- Looking for FE_INEXACT
-- Looking for FE_INEXACT - found
-- Looking for mach/mach.h
-- Looking for mach/mach.h - found
-- Looking for histedit.h
-- Looking for histedit.h - found
-- Looking for CrashReporterClient.h
-- Looking for CrashReporterClient.h - not found
-- Performing Test HAVE_CRASHREPORTER_INFO
-- Performing Test HAVE_CRASHREPORTER_INFO - Success
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Looking for pthread_getspecific in pthread
-- Looking for pthread_getspecific in pthread - found
-- Looking for pthread_rwlock_init in pthread
-- Looking for pthread_rwlock_init in pthread - found
-- Looking for pthread_mutex_lock in pthread
-- Looking for pthread_mutex_lock in pthread - found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
-- Looking for pfm_initialize in pfm
-- Looking for pfm_initialize in pfm - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.5") 
-- Looking for compress2
-- Looking for compress2 - found
-- Found LibXml2: /usr/lib/libxml2.dylib (found version "2.9.0") 
-- Looking for xmlReadMemory
-- Looking for xmlReadMemory - found
-- Looking for el_init in edit
-- Looking for el_init in edit - found
-- Performing Test Terminfo_LINKABLE
-- Performing Test Terminfo_LINKABLE - Success
-- Found Terminfo: /usr/lib/libcurses.dylib  
-- Looking for xar_open in xar
-- Looking for xar_open in xar - found
-- The xar file format has been deprecated: LLVM_HAVE_LIBXAR might be removed in the future.
-- Looking for arc4random
-- Looking for arc4random - found
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /usr/include  
-- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW
-- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW - Failed
-- Looking for __register_frame
-- Looking for __register_frame - found
-- Looking for __deregister_frame
-- Looking for __deregister_frame - found
-- Looking for __unw_add_dynamic_fde
-- Looking for __unw_add_dynamic_fde - not found
-- Looking for _Unwind_Backtrace
-- Looking for _Unwind_Backtrace - found
-- Looking for getpagesize
-- Looking for getpagesize - found
-- Looking for sysconf
-- Looking for sysconf - found
-- Looking for getrusage
-- Looking for getrusage - found
-- Looking for setrlimit
-- Looking for setrlimit - found
-- Looking for isatty
-- Looking for isatty - found
-- Looking for futimens
-- Looking for futimens - not found
-- Looking for futimes
-- Looking for futimes - found
-- Looking for lseek64
-- Looking for lseek64 - not found
-- Looking for mallctl
-- Looking for mallctl - not found
-- Looking for mallinfo
-- Looking for mallinfo - not found
-- Looking for mallinfo2
-- Looking for mallinfo2 - not found
-- Looking for malloc_zone_statistics
-- Looking for malloc_zone_statistics - found
-- Looking for getrlimit
-- Looking for getrlimit - found
-- Looking for posix_spawn
-- Looking for posix_spawn - found
-- Looking for pread
-- Looking for pread - found
-- Looking for sbrk
-- Looking for sbrk - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for strerror_r
-- Looking for strerror_r - found
-- Looking for strerror_s
-- Looking for strerror_s - not found
-- Looking for setenv
-- Looking for setenv - found
-- Looking for dlopen
-- Looking for dlopen - found
-- Looking for dladdr
-- Looking for dladdr - found
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC_TV_NSEC
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC_TV_NSEC - Success
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM_TV_NSEC
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM_TV_NSEC - Failed
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - not found
-- Looking for pthread_getname_np
-- Looking for pthread_getname_np - found
-- Looking for pthread_setname_np
-- Looking for pthread_setname_np - found
-- Looking for proc_pid_rusage
-- Looking for proc_pid_rusage - found
-- Performing Test HAVE_STD_IS_TRIVIALLY_COPYABLE
-- Performing Test HAVE_STD_IS_TRIVIALLY_COPYABLE - Success
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB - Success
-- Performing Test LLVM_HAS_ATOMICS
-- Performing Test LLVM_HAS_ATOMICS - Success
-- Performing Test SUPPORTS_VARIADIC_MACROS_FLAG
-- Performing Test SUPPORTS_VARIADIC_MACROS_FLAG - Success
-- Performing Test SUPPORTS_GNU_ZERO_VARIADIC_MACRO_ARGUMENTS_FLAG
-- Performing Test SUPPORTS_GNU_ZERO_VARIADIC_MACRO_ARGUMENTS_FLAG - Failed
-- Performing Test HAS_MAYBE_UNINITIALIZED
-- Performing Test HAS_MAYBE_UNINITIALIZED - Success
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings enabled.
-- Ninja version: 1.6.0
-- Found ld64 - /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- OCaml bindings disabled.
-- Could NOT find Python module pygments
-- Could NOT find Python module pygments.lexers.c_cpp
-- Could NOT find Python module yaml
-- LLVM host triple: x86_64-apple-darwin13.3.0
-- LLVM default target triple: x86_64-apple-darwin13.3.0
-- Performing Test C_SUPPORTS_FPIC
-- Performing Test C_SUPPORTS_FPIC - Success
-- Performing Test CXX_SUPPORTS_FPIC
-- Performing Test CXX_SUPPORTS_FPIC - Success
-- Building with -fPIC
-- Performing Test C_SUPPORTS_FNO_SEMANTIC_INTERPOSITION
-- Performing Test C_SUPPORTS_FNO_SEMANTIC_INTERPOSITION - Success
-- Performing Test CXX_SUPPORTS_FNO_SEMANTIC_INTERPOSITION
-- Performing Test CXX_SUPPORTS_FNO_SEMANTIC_INTERPOSITION - Success
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG - Success
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME - Success
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME - Success
-- Performing Test CXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW
-- Performing Test CXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW - Failed
-- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG
-- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG - Success
-- Performing Test C_SUPPORTS_CXX98_COMPAT_EXTRA_SEMI_FLAG
-- Performing Test C_SUPPORTS_CXX98_COMPAT_EXTRA_SEMI_FLAG - Failed
-- Performing Test CXX_SUPPORTS_CXX98_COMPAT_EXTRA_SEMI_FLAG
-- Performing Test CXX_SUPPORTS_CXX98_COMPAT_EXTRA_SEMI_FLAG - Failed
-- Performing Test C_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG
-- Performing Test C_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG - Failed
-- Performing Test CXX_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG
-- Performing Test CXX_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG - Failed
-- Performing Test C_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG
-- Performing Test C_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG - Failed
-- Performing Test CXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG
-- Performing Test CXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG - Failed
-- Performing Test CXX_SUPPORTS_CLASS_MEMACCESS_FLAG
-- Performing Test CXX_SUPPORTS_CLASS_MEMACCESS_FLAG - Failed
-- Performing Test CXX_SUPPORTS_REDUNDANT_MOVE_FLAG
-- Performing Test CXX_SUPPORTS_REDUNDANT_MOVE_FLAG - Failed
-- Performing Test CXX_SUPPORTS_PESSIMIZING_MOVE_FLAG
-- Performing Test CXX_SUPPORTS_PESSIMIZING_MOVE_FLAG - Failed
-- Performing Test CXX_SUPPORTS_NOEXCEPT_TYPE_FLAG
-- Performing Test CXX_SUPPORTS_NOEXCEPT_TYPE_FLAG - Failed
-- Performing Test CXX_WONT_WARN_ON_FINAL_NONVIRTUALDTOR
-- Performing Test CXX_WONT_WARN_ON_FINAL_NONVIRTUALDTOR - Failed
-- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE_FLAG
-- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE_FLAG - Success
-- Performing Test CXX_WSUGGEST_OVERRIDE_ALLOWS_ONLY_FINAL
-- Performing Test CXX_WSUGGEST_OVERRIDE_ALLOWS_ONLY_FINAL - Failed
-- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP
-- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP - Failed
-- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG
-- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG - Failed
-- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG
-- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG - Failed
-- Performing Test C_SUPPORTS_MISLEADING_INDENTATION_FLAG
-- Performing Test C_SUPPORTS_MISLEADING_INDENTATION_FLAG - Failed
-- Performing Test CXX_SUPPORTS_MISLEADING_INDENTATION_FLAG
-- Performing Test CXX_SUPPORTS_MISLEADING_INDENTATION_FLAG - Failed
-- Performing Test LINKER_SUPPORTS_COLOR_DIAGNOSTICS
-- Performing Test LINKER_SUPPORTS_COLOR_DIAGNOSTICS - Failed
-- Looking for os_signpost_interval_begin
-- Looking for os_signpost_interval_begin - not found
-- Found Python3: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 (found suitable version "3.10.1", minimum required is "3.6") found components:  Interpreter 
-- Linker detection: ld64
-- Performing Test HAS_WERROR_GLOBAL_CTORS
-- Performing Test HAS_WERROR_GLOBAL_CTORS - Failed
-- Found Git: /usr/bin/git (found version "1.9.5 (Apple Git-50.3)") 
-- Targeting AArch64
-- Targeting AMDGPU
-- Targeting ARM
-- Targeting AVR
-- Targeting BPF
-- Targeting Hexagon
-- Targeting Lanai
-- Targeting Mips
-- Targeting MSP430
-- Targeting NVPTX
-- Targeting PowerPC
-- Targeting RISCV
-- Targeting Sparc
-- Targeting SystemZ
-- Targeting VE
-- Targeting WebAssembly
-- Targeting X86
-- Targeting XCore
-- Registering Bye as a pass plugin (static build: OFF)
-- Failed to find LLVM FileCheck
-- git version: v0.0.0 normalized to 0.0.0
-- Version: 1.6.0
-- Looking for shm_open in rt
-- Looking for shm_open in rt - not found
-- Performing Test HAVE_CXX_FLAG_STD_CXX11
-- Performing Test HAVE_CXX_FLAG_STD_CXX11 - Success
-- Performing Test HAVE_CXX_FLAG_WALL
-- Performing Test HAVE_CXX_FLAG_WALL - Success
-- Performing Test HAVE_CXX_FLAG_WEXTRA
-- Performing Test HAVE_CXX_FLAG_WEXTRA - Success
-- Performing Test HAVE_CXX_FLAG_WSHADOW
-- Performing Test HAVE_CXX_FLAG_WSHADOW - Success
-- Performing Test HAVE_CXX_FLAG_WSUGGEST_OVERRIDE
-- Performing Test HAVE_CXX_FLAG_WSUGGEST_OVERRIDE - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC
-- Performing Test HAVE_CXX_FLAG_PEDANTIC - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS - Success
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 - Failed
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED_DECLARATIONS
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED_DECLARATIONS - Success
-- Performing Test HAVE_CXX_FLAG_FNO_EXCEPTIONS
-- Performing Test HAVE_CXX_FLAG_FNO_EXCEPTIONS - Success
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WD654
-- Performing Test HAVE_CXX_FLAG_WD654 - Failed
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY - Failed
-- Performing Test HAVE_CXX_FLAG_COVERAGE
-- Performing Test HAVE_CXX_FLAG_COVERAGE - Success
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/cozy/llvm-project/build
cozys-iMac:build cozy$ ninja
[92/3187] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/PrettyStackTrace.cpp.o
/Users/cozy/llvm-project/llvm/lib/Support/PrettyStackTrace.cpp:126:41: warning: ‘__crashreporter_info__’ initialized and declared ‘extern’
     __attribute__((visibility("hidden"))) = 0;
                                         ^
[308/3187] Building IntrinsicsXCore.h...
FAILED: cd /Users/cozy/llvm-project/build && /Users/cozy/llvm-project/build/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=xcore -I /Users/cozy/llvm-project/llvm/include/llvm/IR -I/Users/cozy/llvm-project/build/include -I/Users/cozy/llvm-project/llvm/include /Users/cozy/llvm-project/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsXCore.h -d include/llvm/IR/IntrinsicsXCore.h.d
Included from /Users/cozy/llvm-project/llvm/include/llvm/IR/Intrinsics.td:1918:
/Users/cozy/llvm-project/llvm/include/llvm/IR/IntrinsicsAArch64.td:797:1: error: Parameter #0 has out of bounds matching number 0
def int_aarch64_crypto_bcaxs : Crypto_SHA3_3Arg_Intrinsic;
^
Included from /Users/cozy/llvm-project/llvm/include/llvm/IR/Intrinsics.td:1918:
/Users/cozy/llvm-project/llvm/include/llvm/IR/IntrinsicsAArch64.td:797:1: error: ParamTypes is [anonymous_17, anonymous_17, anonymous_17]
def int_aarch64_crypto_bcaxs : Crypto_SHA3_3Arg_Intrinsic;
^
[308/3187] Building IntrinsicImpl.inc...
FAILED: cd /Users/cozy/llvm-project/build && /Users/cozy/llvm-project/build/bin/llvm-tblgen -gen-intrinsic-impl -I /Users/cozy/llvm-project/llvm/include/llvm/IR -I/Users/cozy/llvm-project/build/include -I/Users/cozy/llvm-project/llvm/include /Users/cozy/llvm-project/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicImpl.inc -d include/llvm/IR/IntrinsicImpl.inc.d
Included from /Users/cozy/llvm-project/llvm/include/llvm/IR/Intrinsics.td:1918:
/Users/cozy/llvm-project/llvm/include/llvm/IR/IntrinsicsAArch64.td:797:1: error: Parameter #0 has out of bounds matching number 0
def int_aarch64_crypto_bcaxs : Crypto_SHA3_3Arg_Intrinsic;
^
Included from /Users/cozy/llvm-project/llvm/include/llvm/IR/Intrinsics.td:1918:
/Users/cozy/llvm-project/llvm/include/llvm/IR/IntrinsicsAArch64.td:797:1: error: ParamTypes is [anonymous_17, anonymous_17, anonymous_17]
def int_aarch64_crypto_bcaxs : Crypto_SHA3_3Arg_Intrinsic;
^
[308/3187] Building IntrinsicEnums.inc...
FAILED: cd /Users/cozy/llvm-project/build && /Users/cozy/llvm-project/build/bin/llvm-tblgen -gen-intrinsic-enums -I /Users/cozy/llvm-project/llvm/include/llvm/IR -I/Users/cozy/llvm-project/build/include -I/Users/cozy/llvm-project/llvm/include /Users/cozy/llvm-project/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicEnums.inc -d include/llvm/IR/IntrinsicEnums.inc.d
Included from /Users/cozy/llvm-project/llvm/include/llvm/IR/Intrinsics.td:1918:
/Users/cozy/llvm-project/llvm/include/llvm/IR/IntrinsicsAArch64.td:797:1: error: Parameter #0 has out of bounds matching number 0
def int_aarch64_crypto_bcaxs : Crypto_SHA3_3Arg_Intrinsic;
^
Included from /Users/cozy/llvm-project/llvm/include/llvm/IR/Intrinsics.td:1918:
/Users/cozy/llvm-project/llvm/include/llvm/IR/IntrinsicsAArch64.td:797:1: error: ParamTypes is [anonymous_17, anonymous_17, anonymous_17]
def int_aarch64_crypto_bcaxs : Crypto_SHA3_3Arg_Intrinsic;
^
[308/3187] Building IntrinsicsAArch64.h...
FAILED: cd /Users/cozy/llvm-project/build && /Users/cozy/llvm-project/build/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=aarch64 -I /Users/cozy/llvm-project/llvm/include/llvm/IR -I/Users/cozy/llvm-project/build/include -I/Users/cozy/llvm-project/llvm/include /Users/cozy/llvm-project/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsAArch64.h -d include/llvm/IR/IntrinsicsAArch64.h.d
Included from /Users/cozy/llvm-project/llvm/include/llvm/IR/Intrinsics.td:1918:
/Users/cozy/llvm-project/llvm/include/llvm/IR/IntrinsicsAArch64.td:797:1: error: Parameter #0 has out of bounds matching number 0
def int_aarch64_crypto_bcaxs : Crypto_SHA3_3Arg_Intrinsic;
^
Included from /Users/cozy/llvm-project/llvm/include/llvm/IR/Intrinsics.td:1918:
/Users/cozy/llvm-project/llvm/include/llvm/IR/IntrinsicsAArch64.td:797:1: error: ParamTypes is [anonymous_17, anonymous_17, anonymous_17]
def int_aarch64_crypto_bcaxs : Crypto_SHA3_3Arg_Intrinsic;
^
[308/3187] Building IntrinsicsHexagon.h...
FAILED: cd /Users/cozy/llvm-project/build && /Users/cozy/llvm-project/build/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=hexagon -I /Users/cozy/llvm-project/llvm/include/llvm/IR -I/Users/cozy/llvm-project/build/include -I/Users/cozy/llvm-project/llvm/include /Users/cozy/llvm-project/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsHexagon.h -d include/llvm/IR/IntrinsicsHexagon.h.d
Included from /Users/cozy/llvm-project/llvm/include/llvm/IR/Intrinsics.td:1918:
/Users/cozy/llvm-project/llvm/include/llvm/IR/IntrinsicsAArch64.td:797:1: error: Parameter #0 has out of bounds matching number 0
def int_aarch64_crypto_bcaxs : Crypto_SHA3_3Arg_Intrinsic;
^
Included from /Users/cozy/llvm-project/llvm/include/llvm/IR/Intrinsics.td:1918:
/Users/cozy/llvm-project/llvm/include/llvm/IR/IntrinsicsAArch64.td:797:1: error: ParamTypes is [anonymous_17, anonymous_17, anonymous_17]
def int_aarch64_crypto_bcaxs : Crypto_SHA3_3Arg_Intrinsic;
^
[308/3187] Building CXX object lib/MC/CMakeFiles/LLVMMC.dir/MCWinCOFFStreamer.cpp.o
ninja: build stopped: subcommand failed.
cozys-iMac:build cozy$

**Comment by fhahn** [comment]
What version of LLVM are you trying to build? The error message seems to indicate a problem in the LLVM source. Can you try a build in a fresh directory and the latest `main` of LLVM? Or alternatively one of the release branches.

Please re-open with more details if the problem persists.

**Comment by cozycactus** [comment]
> What version of LLVM are you trying to build? The error message seems to indicate a problem in the LLVM source. Can you try a build in a fresh directory and the latest `main` of LLVM? Or alternatively one of the release branches.
> 
> Please re-open with more details if the problem persists.

i tried to build latest version with many possible -D flags for cmake...
after that i built successfully version 7..
i would be happy to have at least clangd on this old os x version (10.9.4).

**Comment by fhahn** [comment]
> after that i built successfully version 7..

Clang version 7? Can you use that version of clang to build a more recent version of Clang?

**Comment by cozycactus** [comment]
do you know what defines to use in cmake? 

cozys-iMac:build cozy$ cmake -DCMAKE_BUILD_TYPE=Release \
> -DLLVM_TARGETS_TO_BUILD=X86 \
> -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" \
> -DCMAKE_C_COMPILER=clang-7 \
> -DCMAKE_CXX_COMPILER=clang-7 \
> $HOME/llvm-project/llvm
-- The C compiler identification is Clang 7.0.0
-- The CXX compiler identification is Clang 7.0.0
-- The ASM compiler identification is Clang
-- Found assembler: /usr/local/bin/clang-7
-- Check for working C compiler: /usr/local/bin/clang-7
-- Check for working C compiler: /usr/local/bin/clang-7 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/clang-7
-- Check for working CXX compiler: /usr/local/bin/clang-7 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- clang project is enabled
-- clang-tools-extra project is enabled
-- compiler-rt project is disabled
-- cross-project-tests project is disabled
-- libc project is disabled
-- libclc project is disabled
-- libcxx project is disabled
-- libcxxabi project is disabled
-- libunwind project is disabled
-- lld project is disabled
-- lldb project is disabled
-- mlir project is disabled
-- openmp project is disabled
-- parallel-libs project is disabled
-- polly project is disabled
-- pstl project is disabled
-- flang project is disabled
-- Found libtool - /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Performing Test LLVM_LIBSTDCXX_MIN
-- Performing Test LLVM_LIBSTDCXX_MIN - Failed
CMake Error at cmake/modules/CheckCompilerVersion.cmake:97 (message):
  libstdc++ version must be at least 5.1.
Call Stack (most recent call first):
  cmake/config-ix.cmake:14 (include)
  CMakeLists.txt:684 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/cozy/build/CMakeFiles/CMakeOutput.log".
See also "/Users/cozy/build/CMakeFiles/CMakeError.log".

**Comment by cozycactus** [comment]
SOLVED!

i downloaded [https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/clang+llvm-9.0.1-x86_64-apple-darwin.tar.xz](url)
then compiled successfully with : 

cmake -DCMAKE_BUILD_TYPE=Release \
 -DLLVM_TARGETS_TO_BUILD=X86 \
 -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" \
 -DCMAKE_C_COMPILER=$HOME/clang+llvm-9.0.1-x86_64-apple-darwin/bin/clang \
 -DCMAKE_CXX_COMPILER=$HOME/clang+llvm-9.0.1-x86_64-apple-darwin/bin/clang++ \
 $HOME/llvm-project/llvm
