### ISSUE TITLE
Where to get the version number of all extension ISA that LLVM used?

### ISSUE THREAD

**Issue by CodeDance364** [llvm/llvm-project#52879]
Hi,
  Where can we get the version number of all extension ISA that LLVM used,such as LLVM+Clang 13.0?Since we need to make sure the ISA version that LLVM used match with ISA version that core used.
  Thanks!

**Comment by efriedma-quic** [comment]
LLVM generally only implements CPU architecture extensions in their finalized form; you shouldn't need a version number.

The only exception I can think of is for RISCV, where we've implemented some experimental ISA extensions... but clang won't generate code using those unless you explicitly use -menable-experimental-extensions, and specify precisely the version of the extension that LLVM supports.

The llvm-dev mailing list (llvm-dev@lists.llvm.org; https://lists.llvm.org/cgi-bin/mailman/listinfo/llvm-dev) is generally a better place for this sort of question.

**Comment by CodeDance364** [comment]
Yes,what I asked was just RISCV,and what I want to see is some extension version tables,maybe in the source code,just like the links Jim responded in RISCV-GNU.
https://github.com/riscv-collab/riscv-gnu-toolchain/issues/1006
In this way,I can choose a verison in the table list to match the compiler.

**Comment by asb** [comment]
Thanks for clarifying - I've got a couple of suggestions for you:

You could take a look at llvm/test/CodeGen/RISCV/attributes.ll (not guaranteed to be exhaustive, but we try).

We also aim to list the version numbers in the files that specify the instructions - llvm/lib/Target/RISCV/RISCVInstrInfo*.td.
