### ISSUE TITLE
[clang-format] [doc] Deadlink for Mozilla Style

### ISSUE THREAD

**Issue by ksyx** [llvm/llvm-project#52889]
The Mozilla style guide link referred at <https://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options> is a deadlink now.

**Comment by mkurdej** [comment]
Should we link to https://firefox-source-docs.mozilla.org/code-quality/coding-style/coding_style_cpp.html?

**Comment by ksyx** [comment]
As in <https://web.archive.org/web/20210309172458/https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style>, it looks this is an official alternative.

**Comment by ksyx** [comment]
> Should we link to https://firefox-source-docs.mozilla.org/code-quality/coding-style/coding_style_cpp.html?

Should we just link to its homepage instead of cpp part since clangfmt also deal with some Java/JS code?
