### ISSUE TITLE
__attribute__((no_stack_protector)) is overridden by inlining

### ISSUE THREAD

**Issue by duk-37** [llvm/llvm-project#52886]
[Repro](https://godbolt.org/z/s91d7Y8K9)

Root cause seems to be that `Attributes.cpp::adjustCallerSSPLevel` does not have a way to check whether this attribute was added.

**Comment by dongAxis** [comment]
Thanks, after checking the code, I think it might be a bug.   Do you try to fix it? If not, I will fix it

**Comment by duk-37** [comment]
> Thanks, after checking the code, I think it might be a bug. Do you try to fix it? If not, I will fix it

Well I _think_ a decent solution here would be to add a string attribute like no-jump-tables that just tells that function that changing stack protection levels on the caller is a no-no.

**Comment by dongAxis** [comment]
after checking the review, https://reviews.llvm.org/D91816, always_inline might be a special case for ssp and no-ssp

**Comment by duk-37** [comment]
> after checking the review, https://reviews.llvm.org/D91816, always_inline might be a special case for ssp and no-ssp

Hm, so this might be intended behavior?

**Comment by dongAxis** [comment]
might be cc @nickdesaulniers

**Comment by nickdesaulniers** [comment]
yes, that's the intention, though @zmodem also brought up that maybe we should change this for always_inline (further weakening the "always" part of "always inline").

**Comment by duk-37** [comment]
> yes, that's the intention, though @zmodem also brought up that maybe we should change this for always_inline (further weakening the "always" part of "always inline").

I don't really know how I feel about this.. I'd rather have something marked always_inline be, well, inlined, without a stack protector; for example, if you have a set of functions separated out to not duplicate code and using always_inline, or some thirdparty dependency that you expect to be inlined when using `always_inline`, behavior like this would very much subvert expectations. I don't know what the right answer is here, but either way the documentation for this should probably be very explicit.

**Comment by dongAxis** [comment]
> > yes, that's the intention, though @zmodem also brought up that maybe we should change this for always_inline (further weakening the "always" part of "always inline").
> 
> I don't really know how I feel about this.. I'd rather have something marked always_inline be, well, inlined, without a stack protector; for example, if you have a set of performance-critical functions separated out to not duplicate code, or some thirdparty dependency that you expect to be inlined when using `always_inline`, behavior like this would very much subvert expectations. I don't know what the right answer is here, but either way the documentation for this should probably be very explicit.

I will try to update the document in clang and try to connect with @nickdesaulniers .

**Comment by zmodem** [comment]
(The discussion from Chromium is here: https://crbug.com/1274129)

My preference would be to not bring along the stack protector when inlining.

**Comment by zmodem** [comment]
Taking a stab at this here: https://reviews.llvm.org/D116589

**Comment by zmodem** [comment]
> Taking a stab at this here: https://reviews.llvm.org/D116589

Committed as 2bc57d85ebf244f19a3046295b58eb8c667f947d.
