### ISSUE TITLE
InstCombineCalls.cpp:786: llvm::Instruction* moveAddAfterMinMax(llvm::IntrinsicInst*, llvm::InstCombiner::BuilderTy&): Assertion `!Overflow && "Expected simplify of min/max"' failed.

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#52884]
https://gcc.godbolt.org/z/z7c3xx86Y

`opt -instcombine` crashes on this IR:

```declare i8 @llvm.smax.i8(i8, i8) nofree nosync nounwind readnone speculatable willreturn

define i8 @smax_offset(i8 %x) {
  %1 = add nuw nsw i8 50, %x
  %m = call i8 @llvm.smax.i8(i8 %1, i8 -124)
  ret i8 %m
}
```

this was found by my student @Hatsunespica

**Comment by rotateright** [comment]
InstCombine is expecting InstSimplify to squash the pattern before it gets too far, but the analysis got thwarted by having both "nuw" and "nsw" on the add. 

Proposed fix:
https://reviews.llvm.org/D116322
