### ISSUE TITLE
Overloaded static member function cannot be resolved unlike overloaded global function 

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#52883]
In the following code:
```
void g(int) {}
void g(double) {}

struct A {
    static void m(int) {}
    static void m(double) {}
};

int main() {
   (&g)(0);    //ok
   (&A::m)(0); //error in GCC and Clang
}
```
the resolution of overloaded global function `g` goes fine, but as to similar static member function `A::m` the overload resolution fails, which looks wrong. 

MSVC has not problem with either case. Demo: https://gcc.godbolt.org/z/585e5Gc4b

Related discussion: https://stackoverflow.com/q/68947849/7325599

**Comment by Endilll** [comment]
Still reproduces on trunk.

**Comment by shafik** [comment]
As far as I can tell [CWG704](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#704) applies here and clang and gcc are correct to reject the second case.

CC @zygoloid @hubert-reinterpretcast

**Comment by cor3ntin** [comment]
There has been some clarification recently as part of https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2797r0.html (c++23, off shoot of deducing this)


https://eel.is/c++draft/over.call.func


The reflector thread "[isocpp-core] "invocation"?" Is also of relevance, and points to the need of further clarification as to what counts as a call expression.

I am not sure the thread and the wording example reached the same conclusion though.


Either way, it doesn't seem particularly useful to behave differently in each case here.

**Comment by cor3ntin** [comment]
Fixed in Clang 19
