### ISSUE TITLE
[PowerPC] fatal error: error in backend: Incomplete scavenging after 2nd pass

### ISSUE THREAD

**Issue by pkubaj** [llvm/llvm-project#52894]
clang version 13.0.0
FreeBSD 13.0-RELEASE
powerpc64le

Reduced test case:
```
int a[4096];
template <int b> struct d {
  int ak[1 << b];
  void e();
};
void h(d<17>);
void g(d<17>) {
  d<17> c;
  for (int f = 0; f < 4096; f++)
    a[f] = f;
  c.e();
  for (int f = 0; f < 4096; f++)
    a[f] = f;
  h(c);
}
```

Compile with:
`clang++13 -cc1 -triple powerpc64le-unknown-freebsd13.0 -emit-obj -target-cpu ppc64le -O2 -vectorize-loops organ-5b291c.cpp`

The issue doesn't happen after removing `-vectorize-loops` or after replacing `-O2` with `-O1`.

**Comment by adalava** [comment]
Using opt-bisect-limit clang++ can generate a binary when limited to "Two-Address instruction pass on function". It returns error when "Machine Instruction Scheduler on function" is added:

FreeBSD clang version 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c3fe) on powerpc64 

clang++ -cc1 -triple powerpc64le-unknown-freebsd13.0 -emit-obj -target-cpu ppc64le -O2 -vectorize-loops a.cpp -mllvm -opt-bisect-limit=140


```
BISECT: running pass (136) PowerPC MI Peephole Optimization on function (_Z1g1dILi17EE)
BISECT: running pass (137) Remove dead machine instructions on function (_Z1g1dILi17EE)
BISECT: running pass (138) Modulo Software Pipelining on function (_Z1g1dILi17EE)
BISECT: running pass (139) Two-Address instruction pass on function (_Z1g1dILi17EE)
BISECT: running pass (140) Machine Instruction Scheduler on function (_Z1g1dILi17EE)   <----- error when this is included
BISECT: NOT running pass (141) PowerPC VSX FMA Mutation on function (_Z1g1dILi17EE)
BISECT: NOT running pass (142) Stack Slot Coloring on function (_Z1g1dILi17EE)
BISECT: NOT running pass (143) Machine Copy Propagation Pass on function (_Z1g1dILi17EE)
BISECT: NOT running pass (144) Machine Loop Invariant Code Motion on function (_Z1g1dILi17EE)
BISECT: NOT running pass (145) Fixup Statepoint Caller Saved on function (_Z1g1dILi17EE)
BISECT: NOT running pass (146) PostRA Machine Sink on function (_Z1g1dILi17EE)
BISECT: NOT running pass (147) Shrink Wrapping analysis on function (_Z1g1dILi17EE)
fatal error: error in backend: Incomplete scavenging after 2nd pass
```

**Comment by pkubaj** [comment]
On BE, optimizing for power8 fails:
`clang++13 -cc1 -triple powerpc64-unknown-freebsd13.0 -emit-obj -target-cpu pwr8 -O2 -vectorize-loops organ-5b291c.cpp`

But optimizing for power7 is ok:
`clang++13 -cc1 -triple powerpc64-unknown-freebsd13.0 -emit-obj -target-cpu pwr7 -O2 -vectorize-loops organ-5b291c.cpp`

**Comment by nemanjai** [comment]
Thanks for reporting this. I'll take a look at what's going on.

**Comment by nemanjai** [comment]
Proposed fix in https://reviews.llvm.org/D124841
