### ISSUE TITLE
ICE on concept with member function call that lacks parentheses

### ISSUE THREAD

**Issue by TmLev** [llvm/llvm-project#52905]
MRE: https://godbolt.org/z/Kdsoz1eGP

Code for indexing:
```cpp
#include <concepts>
#include <vector>

template <class T>
concept Beginable = requires(T t) {
    { t.begin } -> std::convertible_to<typename T::iterator>;
    // ^~~  should be `t.begin()`
};

static_assert(Beginable<std::vector<int>>);
```

**Comment by ChuanqiXu9** [comment]
A reduced example: https://godbolt.org/z/ebr9YTbdr

**Comment by ChuanqiXu9** [comment]
This should be fixed in: https://github.com/llvm/llvm-project/commit/8de2d06251c30751bdc0fd7b89133610797759e6.

**Comment by Quuxplusone** [comment]
I have an alternative fix for this at https://reviews.llvm.org/D118552
