### ISSUE TITLE
cross-project-tests & mlir fails on `no member named 'Kind' in 'mlir::Value'`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#52918]
```
/home/sylvestre/dev/debian/pkg-llvm/llvm-toolchain/branches/llvm-toolchain-snapshot_14~++20211229090811+7df7586a0b09/cross-project-tests/debuginfo-tests/llvm-prettyprinters/gdb/mlir-support.cpp:13:33: error: no member named 'Kind' in 'mlir::Value'
                   mlir::Value::Kind::OutOfLineOpResult});
                   ~~~~~~~~~~~~~^
1 error generated.

```

Seems to be caused by:
3dfa86149e14ebb7fa40c55749ae435641940ff6

cc @joker-eph

**Comment by joker-eph** [comment]
We already break these pretty-printer :(

We should have a bot for these...

**Comment by joker-eph** [comment]
mlir/utils/MLIRVisualizers/mlir.natvis also has obsolete references to `mlir::Value::Kind::TrailingOpResult`

**Comment by joker-eph** [comment]
Fixing the build is trivial, I did it in eec312ee7f97

However the test isn't passing (but these tests only run if you build with DebugInfo so it shouldn't block you anymore): I don't even know how the test ever passed actually.
@chsigg : any hint / help on this?

**Comment by telans** [comment]
https://github.com/llvm/llvm-project/issues/48872

**Comment by joker-eph** [comment]
Closing as duplicate! Thanks @telans
