### ISSUE TITLE
Add a `FunctionLikeOpInterface`

### ISSUE THREAD

**Issue by stellaraccident** [llvm/llvm-project#52917]
The existing `FunctionLike` trait is useful for building components that can operate generically on ops which carry it. However, its definition predates the more modern concepts of op interfaces, necessitating that generic code be written similar to the following:

```
assert(funcOp->hasTrait<FunctionLike>());
function_like_impl::getFunctionBody(funcOp)
```

instead of:

```
auto funcOp = cast<FunctionLikeOpInterface>(op);
funcOp.getBody()
```

Propose adding `FunctionLikeOpInterface` and retiring the original `function_like_impl` namespace.

**Comment by River707** [comment]
Update: looking into this in the next day or two.

**Comment by stellaraccident** [comment]
You rock! Thanks.
