### ISSUE TITLE
[openmp] build wrongly picking up AMDGCN target on linux for 13.0.1-rc1

### ISSUE THREAD

**Issue by h-vetinari** [llvm/llvm-project#52910]
Trying to build openmp 13.0.1-rc1 for [conda-forge](https://github.com/conda-forge/openmp-feedstock/pull/55), during the config phase, it seems AMDGCN is wrongly activated, despite clang-tools not being available.
```
-- LIBOMPTARGET: Building offloading runtime library libomptarget.
-- LIBOMPTARGET: Not building aarch64 offloading plugin: machine not found in the system.
-- LIBOMPTARGET: Not building AMDGPU plugin: LIBELF not found
-- LIBOMPTARGET: Not building CUDA offloading plugin: libelf dependency not found.
-- LIBOMPTARGET: Not building PPC64 offloading plugin: machine not found in the system.
-- LIBOMPTARGET: Not building PPC64le offloading plugin: machine not found in the system.
-- LIBOMPTARGET: Not building nec-aurora plugin: libveo or libveosinfo not found.
-- LIBOMPTARGET: Not building x86_64 offloading plugin: libelf dependency not found.
-- LIBOMPTARGET: Building AMDGCN device RTL. Using clang: CLANG_TOOL-NOTFOUND
-- LIBOMPTARGET: Not building NVPTX deviceRTL by default on CUDA free system.
-- LIBOMPTARGET: Not building NVPTX deviceRTL by default on CUDA free system.
-- LIBOMPTARGET: Building the llvm-omp-device-info tool
```

This later leads to a build-error.

Given the solitary "Building AMDGCN [...]" in a sea of "Not building [...]", I'm thinking there's something off here with the detection.

**Comment by h-vetinari** [comment]
@llvm/issue-subscribers-openmp 
This is still an issue with 13.0.0.rc2

**Comment by jdoerfert** [comment]
```
[  3%] Generating task.gfx701.bc [...]/src/task.cu -o task.gfx701.bc
/bin/sh: CLANG_TOOL-NOTFOUND: command not found
```
Maybe you should put `CLANG_TOOL-NOTFOUND` on your path ;) 

@JonChesterfield Can you (or someone you ask) repair the AMDGPU device runtime cmake to not attempt a build w/o clang, please :)

**Comment by JonChesterfield** [comment]
Fixed by https://reviews.llvm.org/D117230, will need to be backported to 13 rc

**Comment by h-vetinari** [comment]
> Fixed by https://reviews.llvm.org/D117230, will need to be backported to 13 rc

@tstellar, this doesn't apply directly (actually, just the second half of the patch would be enough). @JonChesterfield and I were wondering on phabricator what the post-bugzilla process is to pick this up. I pushed a version of this to https://github.com/h-vetinari/llvm-project/tree/backport_D112859, for which I could raise a PR here on github against `release/13.x`, if desired.

**Comment by h-vetinari** [comment]
PS. Happy to report that the simplified backport does its job well in https://github.com/conda-forge/openmp-feedstock/pull/55

**Comment by h-vetinari** [comment]
@tstellar 
This didn't make it to rc3 AFAICT. I cannot add the milestone here, so wanted to ask you to have a look. A few comments up I provided a backportable version of the patch as it landed.

**Comment by tstellar** [comment]
@h-vetinari I'll add the milestone, but it's more than likely too late to get this into 13.0.1.

**Comment by h-vetinari** [comment]
Closing, as no more 13.0.x releases are [planned](https://discourse.llvm.org/t/llvm-13-0-1-final-has-been-tagged/59710/11).
