### ISSUE TITLE
llvm/include/llvm/Support/Casting.h:269: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::AnyCoroIdInst; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::AnyCoroIdInst*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#52912]
https://gcc.godbolt.org/z/aK4ndMWqP

this IR crashes `opt -O2`:

```
%g.Frame = type { void (%g.Frame*)*, void (%g.Frame*)*, i32, i1, i32 }

@g.resumers = private constant [3 x void (%g.Frame*)*] [void (%g.Frame*)* bitcast (void ()* @g.dummy to void (%g.Frame*)*), void (%g.Frame*)* bitcast (void ()* @g.dummy to void (%g.Frame*)*), void (%g.Frame*)* bitcast (void ()* @g.dummy to void (%g.Frame*)*)]

declare void @g.dummy()

define i8* @f() #0 {
entry:
  %innerhdl = call i8* @llvm.coro.begin(token none, i8* null)
  ret i8* null
}

declare i8* @llvm.coro.begin(token, i8* writeonly)

attributes #0 = { "coroutine.presplit"="1" }
```

found by @hatsunespica

**Comment by ChuanqiXu9** [comment]
It lacks a necessary instrinic: @llvm.coro.id. It wouldn't crash after we use @llvm.coro.id: https://gcc.godbolt.org/z/GoTq6o669. According to https://llvm.org/docs/Coroutines.html, an @llvm.coro.id is necessary. The design of coroutine intrinsics are tied with each other, so that it is easy to crash if we write coroutine intrinsics by hand.
(It might be helpful if there is a verification pass to give nicer diagnostic messages)

**Comment by Hatsunespica** [comment]
Hi ChuangqiXu,

The test case is a shorted version. The original test file is from : 
https://github.com/llvm/llvm-project/blob/main/llvm/test/Transforms/Coroutines/coro-spill-corobegin.ll
and it causes -O2 failed, which gcc link is here https://gcc.godbolt.org/z/hvWvffc9M
The example above is just a reduced case of this original test and we didn't write it by hand. 
What do you think of this test case. Is it valid? 
Thanks for your response!

**Comment by ChuanqiXu9** [comment]
> Hi ChuangqiXu,
> 
> The test case is a shorted version. The original test file is from : https://github.com/llvm/llvm-project/blob/main/llvm/test/Transforms/Coroutines/coro-spill-corobegin.ll and it causes -O2 failed, which gcc link is here https://gcc.godbolt.org/z/hvWvffc9M The example above is just a reduced case of this original test and we didn't write it by hand. What do you think of this test case. Is it valid? Thanks for your response!

Hi Spica,

    The test case isn't correct too. I have fixed it in: https://github.com/llvm/llvm-project/commit/ea6a3f9f960e52ea39edd5edddf5afad3c11f7a0. Although you didn't write it by hand, almost all the test cases in llvm/test/Coroutines/ are made up by hand. So it is possible that the author made an oversight. I guess there are other similar issues there. I would check it later.  Thanks for reporting this.
