### ISSUE TITLE
Kernel 5.15.11 (and higher) C syntax parse error

### ISSUE THREAD

**Issue by ErichLoew** [llvm/llvm-project#52923]
Compiler: clang version 14.0.0 (https://github.com/llvm/llvm-project.git 946eb7a037d5f83ea9cdc99bac0f939ddd344e09)
          Target: x86_64-unknown-linux-gnu
          Thread model: posix
Kernel:   5.15.11 vanilla
Module:   source/drivers/gpu/drm/i915/intel_pm.c
Method:   snb_wm_latency_quirk(struct drm_i915_private *dev_priv)
Observations:
  --> Compiles fine with "gcc (GCC) 11.2.0" without changes of source code
  --> clang 14.0.0 fails on original source code --> source code mitigation changes are required.
Mitigation for clang 14.0.0:
        A) Change ilk_increase_wm_latency() to return int instead of bool
        B) Updated statement:
           changed = (bool)(ilk_increase_wm_latency(dev_priv, dev_priv->wm.pri_latency, 12) |
                            ilk_increase_wm_latency(dev_priv, dev_priv->wm.spr_latency, 12) |
                            ilk_increase_wm_latency(dev_priv, dev_priv->wm.cur_latency, 12));
Guess: clang-14 refuses usage of data type bool inside of bit logic evaluating statements.

**Comment by nathanchance** [comment]
We have been tracking this: https://github.com/ClangBuiltLinux/linux/issues/1473

Apply [this patch](https://cgit.freedesktop.org/drm/drm-intel/commit/?id=2e70570656adfe1c5d9a29940faa348d5f132199) to fix the warning, it will be merged into Linus's tree within the next few weeks, after which it can be backported to the 5.15 series.

**Comment by nathanchance** [comment]
This is not really an LLVM bug so this issue can probably be closed.

**Comment by ErichLoew** [comment]
Observation at fresh GIT clone of latest LLVM and clang-18 not visible
