### ISSUE TITLE
No-aggregate assertion in getPtrStride() triggered by LoopAccessInfo::analyzeLoop()

### ISSUE THREAD

**Issue by dnadlinger** [llvm/llvm-project#52920]
This

```llvm
; ModuleID = 'bugpoint-reduced-simplified.bc'
source_filename = "copyto_unaliased!"
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128-ni:10:11:12:13"
target triple = "arm64-apple-darwin21.2.0"

define void @"julia_copyto_unaliased!_3275"() {
top:
  br label %L69

L69:                                              ; preds = %L69, %top
  %0 = load { i64 }, { i64 }* undef
  store { i64 } undef, { i64 }* undef
  br i1 undef, label %L185.loopexit, label %L69

L185.loopexit:                                    ; preds = %L69
  ret void
}
```

hits an assertion with e.g. `-loop-load-elim` on 1dd5e6fed5dbfe105451277d749e3c4240b925c4, as `LoopAccessInfo::analyzeLoop` calls `getPtrStride` on the aggregate.

Immediate fix is to revert 0a00d64e322f28f5f65f5b2d507d12757883478a, which turned a previous graceful check into an assertion.

**Comment by nikic** [comment]
@fhahn Can we just drop this check entirely? It's not clear to me how aggregates are relevant to this code.

**Comment by fhahn** [comment]
> @fhahn Can we just drop this check entirely? It's not clear to me how aggregates are relevant to this code.

Yeah, the code should be agnostic to the element type. I removed the assert and added tests for symbolic strides with aggregate types for both the analysis and LoopLoadElim in d8276208be76
