### ISSUE TITLE
[IR] 'indirect' arguments on calls to inlineasm should be annotated with explicitly pointee type information

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#52928]
This is scattered througout backend, but here's one example:
https://github.com/llvm/llvm-project/blob/1c6b740d4b1bb8f74c8eb2fa38b21d684d32ca75/llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp#L4781-L4788

https://github.com/llvm/llvm-project/blob/1c6b740d4b1bb8f74c8eb2fa38b21d684d32ca75/llvm/test/CodeGen/X86/asm-indirect-mem.ll reproduces it.

**Comment by nikic** [comment]
My plan was to require the `elementtype` attributes on indirect inline asm call operands.
