### ISSUE TITLE
Feature request: accept -fPIC and -Wl,--as-needed flags

### ISSUE THREAD

**Issue by brechtsanders** [llvm/llvm-project#52947]
I'm trying to build a large amount of libraries with LLVM/Clang for Windows with MinGW-w64.
A lot of sources won't build out of the box because of errors relating to flags that don't exist like `-fPIC` (sometimes also `-fpic`) and `-Wl,--as-needed flags`. 

On Windows these specific flags have no actual effect (at least not in GCC).

If these flags would get accepted as dummy flags for Windows targets, they would allow building a lot more sources without modifications.

**Comment by mstorsjo** [comment]
Out of curiosity, can you point to some examples of projects ending up building with `-Wl,--as-needed`? (The fix for ignoring the flags probably is fine.)

As for `-fPIC`, yeah, I've run into lots of those. I think there might be intent around why it does error out on that instead of just silently accepting it, I have vague memories of digging into it in the version control history, but I don't remember any of it right now. So I think it might be necessary to at least revisit and browse earlier talks on that issue before setting out to change it.

**Comment by zero9178** [comment]
The original commit that added the warnings for -fPIC & friends was https://github.com/llvm/llvm-project/commit/d133dc226f58d09d12b10c14b4241cc50f3d56f1. Sadly I seem to not be able to find any code review associated with the change. 

Changing the condition to only warn on MSVC would roughly be a fix to the issue and changing the MinGW toolchain to always return true for `isPICDefaultForced` would basically solve the issue (it currently only does for platforms where PIC is the default, but AFAIK, `-fPIC` shouldn't have an effect on i686 either, therefore the platform default should be forced)

**Comment by mstorsjo** [comment]
> Changing the condition to only warn on MSVC would roughly be a fix to the issue

That sounds like a sensible way forward to me

> and changing the MinGW toolchain to always return true for `isPICDefaultForced` would basically solve the issue

Hmm, I don't think I see how that would affect where this error/warning is emitted?

**Comment by zero9178** [comment]
Changing `isPICDefaultForced` to always return true would ensure that `-fPIC` and friends don't actually affect the codegen in any way. 
This is currently the case of x86_64 and aarch64, but not for `i686`. It has so far not been an issue as using `-fPIC` at the moment is an error anyways. If we were to instead ignore the error however, `-fPIC` would not be ignored and would lead to it impacting codegen on `i686`.

**Comment by mstorsjo** [comment]
> Changing `isPICDefaultForced` to always return true would ensure that `-fPIC` and friends don't actually affect the codegen in any way.
> This is currently the case for x86_64 and aarch64, but not for `i686`. It has so far not been an issue as using `-fPIC` at the moment is an error anyways. If we were to instead ignore the error however, `-fPIC` would not be ignored and would lead to it impacting codegen on `i686`.

Oh, I see - good catch. Yeah that sounds sensible to me.

**Comment by brechtsanders** [comment]
Sorry, I don't have an example of a specific project using `-Wl,--as-needed`, but I do have a lot of build scripts that have it, usually to add libraries that are needed in some cases to avoid bloating the resulting output.

However, I read that `-Wl,--as-needed` is default in GCC on MinGW (if `-Wl,--no-as-needed` is not specified), so if you don't accept the request to treat it as a dummy flag I can always go and change my build scripts (a few thousand of them).

Having `-fPIC` as a dummy would already help a lot. I also see some package use `-fpic` (lowercase), for example libbz2.

**Comment by mstorsjo** [comment]
> Sorry, I don't have an example of a specific project using `-Wl,--as-needed`, but I do have a lot of build scripts that have it, usually to add libraries that are needed in some cases to avoid bloating the resulting output.
> 
> However, I read that `-Wl,--as-needed` is default in GCC on MinGW (if `-Wl,--no-as-needed` is not specified), so if you don't accept the request to treat it as a dummy flag I can always go and change my build scripts (a few thousand of them).

Ok, that explains it. I don’t mind adding it to the recognized but ignored options (https://reviews.llvm.org/D116484) as GNU ld ignores it too.

Maybe the one option that GNU ld accepts silently, that we’ve decided not to accept, is `--allow-shlib-undefined`, because undefined symbols really aren’t supported in DLLs. (Meson used to accidentally pass this option on mingw targets.)

**Comment by mstorsjo** [comment]
> However, I read that `-Wl,--as-needed` is default in GCC on MinGW (if `-Wl,--no-as-needed` is not specified), so if you don't accept the request to treat it as a dummy flag I can always go and change my build scripts (a few thousand of them).

(As it's a no-op, changing your build scripts might be sensible anyway, if it's not a huge chore.)

In the review of ignoring those commits, it was pointed out that it might not be a good idea to blindly accept and ignore possibly conflicting options meant for another object file format: https://reviews.llvm.org/D116484#3216409 But we later agreed that we can probably ignore `--as-needed` as that's pretty much how DLL linking works anyway, but we'd still error out on `--no-as-needed` (as we can't really achieve that with DLLs). Would that still help for your case @brechtsanders?

**Comment by brechtsanders** [comment]
Okay that's fine.

I understand `--no-as-needed` is not a noop in gcc for static libraries. I'm not sure how gcc handles it for shared libraries (DLLs). But it's an option I rarely come across, and usually it's people using it to work around issues that should be solved otherwise.

**Comment by mstorsjo** [comment]
> I understand `--no-as-needed` is not a noop in gcc for static libraries. I'm not sure how gcc handles it for shared libraries (DLLs). But it's an option I rarely come across, and usually it's people using it to work around issues that should be solved otherwise.

I did a quick test with GNU ld wrt static libraries and `--no-as-needed`, and it didn't seem to have any effect there. You might be thinking of the `--whole-archive` option which causes the following static libraries to be included in full, instead of only pulling in the necessary object files.

**Comment by brechtsanders** [comment]
In that case you can just ignore `--no-as-needed` too.
