### ISSUE TITLE
[clang-tidy] add_new_check.py writes out files with native line endings

### ISSUE THREAD

**Issue by LegalizeAdulthood** [llvm/llvm-project#52968]
The current advice is for Windows uses to checkout from git with `autocrlf=false`, which preserves Unix line endings on the checked out files.

However, when `add_new_check.py` is run to add a new clang-tidy check, it writes out all the files with native line endings and this results in the modified files having diffs that say "delete all the lines of the old file and add all the lines of the new file", which is undesirable.

**Comment by LegalizeAdulthood** [comment]
Can we assume it is safe to force unix line endings all the time?

Or should a command-line arg to `add_new_check.py` be provided to opt-in to forcing unix line endings?

**Comment by Quuxplusone** [comment]
> I have a patch

What is the patch?

libc++'s Python scripts uniformly use

    with open(out_path, 'w', newline='\n') as f:

to solve this issue, and I am pretty confident that this is the right fix and that everyone else's Python scripts should adopt the same idiom.

**Comment by LegalizeAdulthood** [comment]
That's pretty much what I did too.
