### ISSUE TITLE
[optimaztion] do away with the infinite loop unexpectedly

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#52972]
clang compiler do away with the infinite loop unexpectedly after optimaztion with -O1,
see detail with https://gcc.godbolt.org/z/eex8rzT9z

--- test.c ----

int startcond;
static int myvar = 1;

int main(void)
{
  startcond = 1;
  if(1 == startcond)
  {
     startcond = 0;
  }
  while(1);
  return 0;
}

**Comment by vfdff** [comment]
a more smart case seems also can reproduce this issue
`int main(void)
{
  while(1);
  return 0;
}`

**Comment by ChuanqiXu9** [comment]
This is not a bug. It is an optimization. Compiler wouldn't eliminate the loop if there is a (potential) side effect: https://gcc.godbolt.org/z/des5sKP7f

**Comment by vfdff** [comment]
I find https://reviews.llvm.org/D38336 support for infinite loops with side effects with Rust, and not for C.

**Comment by nikic** [comment]
Infinite loops without side-effects are undefined behavior in C++. C special cases the `while (1)` case. In either case, you can compile with `-fno-finite-loops` to disable the forward progress assumption.

**Comment by vfdff** [comment]
ok, thanks very much, I think this issue can be closed now.
