### ISSUE TITLE
[clang-format] SeparateDefinitionBlocks always puts a break between a comment and the function the comment it for

### ISSUE THREAD

**Issue by mydeveloperday** [llvm/llvm-project#52976]
I'm seeing some odd behaviour in SeperateDefinitionBlocks..

`SeparateDefinitionBlocks: Always`

```
void foo() {}
/* ABC */
void bar() {}
```
becomes

```
void foo() {}

/* ABC */

void bar() {}
```
If the ABC comment is a doxygen style comment it doesn't make sense to separate it from the function below

**Comment by mydeveloperday** [comment]
This is also true for line comments

```
void foo() {}

/* ABC */

void bar() {}

void foo() {}

// bar function

void bar() {}
```

**Comment by mydeveloperday** [comment]
Also true for namespaces

```
// mynamespace

namespace {}
```

I kind of feel this level of separation is not required

**Comment by mkurdej** [comment]
Review: https://reviews.llvm.org/D116663.
