### ISSUE TITLE
IndentExternBlock: NoIndent is not working

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#52988]
I want to achieve the following result:

```
extern "C"
{
void foo();
}
```
For which I've set `IndentExternBlock: NoIndent`. However when running `clang-format` in the above code it will indent the function declaration, which I don't want.

I have also set `AfterExternBlock: true` in the `BraceWrapping` section.

I'm also having trouble to understand the very first option for `IndentExternBlock`:

> Backwards compatible with AfterExternBlock’s indenting.

Backwards compatible in what sense? What's the expected result if I use this option?

I see this should have been resolved in https://github.com/llvm/llvm-project/issues/49804, but I can see the problem in a more recent trunk 104a827ea6de0cbe0f5faef4407552ede31d165c.

**Comment by carlosgalvezp** [comment]
Reading through the unit tests of #49804, it seems I need to set `BreakBeforeBraces: Custom` instead of `BreakBeforeBraces: Allman` to make this work.

**Comment by mydeveloperday** [comment]
@carlosgalvezp that is correct `BraceWrapping` does not work for anything other than `BreakBeforeBraces: Custom`,  all other settings are presets of `BraceWrapping` none of which we can really change now without uses complaining about backwards compatibility

**Comment by carlosgalvezp** [comment]
@mydeveloperday Sure, that makes sense, but why would `BreakBeforeBraces` have any impact on `IndentExternBlock`? They look like 2 orthogonal parameters to me, one is about where to put the braces, and the other whether to indent the block or not. All combinations of such parameters are possible, or?
