### ISSUE TITLE
Assertion errors in llvm/lib/IR/Constants.cpp at ToT clang

### ISSUE THREAD

**Issue by zeroomega** [llvm/llvm-project#52994]
We are seeing assertion errors in `llvm/lib/IR/Constants.cpp` after change https://github.com/llvm/llvm-project/commit/bbeaf2aac678633749e7385466da10a1c0120b3b was landed. The error message was:

```
clang++: llvm/lib/IR/Constants.cpp:2281: static llvm::Constant *llvm::ConstantExpr::getBitCast(llvm::Constant *, llvm::Type *, bool): Assertion `CastInst::castIsValid(Instruction::BitCast, C, DstTy) && "Invalid constantexpr bitcast!"' failed.
```

The error disappeared after this change was reverted locally.

Reproducer is attached: 
[builds_8825975828562758241_command_parser-85c711.zip](https://github.com/llvm/llvm-project/files/7809888/builds_8825975828562758241_command_parser-85c711.zip)

**Comment by nikic** [comment]
Reduction:

```
; RUN: opt -S -globalopt < %s
@llvm.global_ctors = appending global [1 x { i32, void ()*, i8* }] [{ i32, void ()*, i8* } { i32 65535, void ()* @ctor, i8* null }]

define internal void @ctor() {
  %coerce = alloca { i64, i64 }, align 8
  store { i64, i64 } zeroinitializer, { i64, i64 }* %coerce, align 8
  ret void
}
```
