### ISSUE TITLE
How to use clang-cl with libc++

### ISSUE THREAD

**Issue by tumagonx** [llvm/llvm-project#53004]
clang: 10.0.1
windows: XP SP3 32-bit
MS CRT: VCRuntime 2019 16.7, UCRT 10.1.18362.1
step to reproduce: `clang-cl -stdlib=libc++ -fms-compatibility-version=19.27 test.cpp`
result: `clang-cl: warning: unknown argument ignored in clang-cl: '-stdlib=libc++' [-Wunknown-argument]`
reference: https://releases.llvm.org/5.0.0/projects/libcxx/docs/UsingLibcxx.html

I want to bootstrap clang with clang+libc++ in msvc ABI mode (I could do this with gnu ABI mode).

**Comment by JVApen** [comment]
From the manual: (https://clang.llvm.org/docs/UsersManual.html#clang-cl)
  -Xclang <arg>           Pass <arg> to the clang compiler

So -Xclang -stdlib=libc++ could get you started.
No clue what the actual result would be.

I think I once tried it with explicitly setting /I in the past. Couldn't use it due to external libs like PPL.

**Comment by tumagonx** [comment]
thanks, while it get rid the warning clang still doesn't pick up [clangdir]\include\c++\v1 in msvc mode 

the order is
[clangdir]\lib\clang\10.0.1\include 
msvc includes, ucrt
wsdk include

that's all. I have tried manually -I before but get lots of errors. 
In msvc mode it picked ONLY what specified in %INCLUDE% env OR search trough registry for msvc location
In mingw mode it ignore above existences
so IMHO in msvc + libc++ mode clang should include c++\v1 + ucrt  only.. but ucrt only separated in VS2015 or later, previously STL and CRT are lumped together. 
Is this not supported? why libc++ exist for msvc then? 
I was think using libc++ to backport some python library to version 2.7 (e.g. python Qt) that is using libc++ and msvcr90.dll.

**Comment by tumagonx** [comment]
ahh I forgot, libc++ also took something in ms STL as replacement for libcxxabi + unwinding handler (in case of mingw) so maybe the two can't really be separated.

**Comment by fsb4000** [comment]
I use clang-cl and Windows and libc++.

This is my usual test command:
```
$ "C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/Llvm/x64/bin/clang-cl.exe" "C:\Dev\STL\llvm-project\libcxx\test\std\utilities\smartptr\unique.ptr\unique.ptr.special\cmp_nullptr.pass.cpp" "--driver-mode=g++" "--target=x86_64-pc-windows-msvc" "-nostdinc++" "-I" "C:/Dev/STL/llvm-project/build/include/c++/v1" "-I" "C:/Dev/STL/llvm-project/build/include/c++/v1" "-I" "C:/Dev/STL/llvm-project/libcxx/test/support" "-D_CRT_SECURE_NO_WARNINGS" "-D_CRT_NONSTDC_NO_WARNINGS" "-D_CRT_STDIO_ISO_WIDE_SPECIFIERS" "-DNOMINMAX" "-std=c++2b" "-Werror" "-Wall" "-Wextra" "-Wshadow" "-Wundef" "-Wno-unused-command-line-argument" "-Wno-attributes" "-Wno-pessimizing-move" "-Wno-c++11-extensions" "-Wno-noexcept-type" "-Wno-atomic-alignment" "-Wno-user-defined-literals" "-Wno-tautological-compare" "-Wsign-compare" "-Wunused-variable" "-Wunused-parameter" "-Wunreachable-code" "-Wno-unused-local-typedef" "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER" "-D_LIBCPP_ENABLE_EXPERIMENTAL" "-D_LIBCPP_DISABLE_AVAILABILITY" "-fcoroutines-ts" "-Werror=thread-safety" "-Wuser-defined-warnings" "-DTEST_WINDOWS_DLL" "-llibc++experimental" "-nostdlib" "-L" "C:/Dev/STL/llvm-project/build/lib" "-lc++" "-lmsvcrt" "-lmsvcprt" "-loldnames" "-o" "C:\Dev\STL\llvm-project\build\test\std\utilities\smartptr\unique.ptr\unique.ptr.special\Output\cmp_nullptr.pass.cpp.dir\t.tmp.exe"
```

I hope it helps.

I didn't bootstrap clang...

**Comment by ldionne** [comment]
Closing since this is a question which seems to have been answered.

**Comment by jcm93** [comment]
Does anyone know the appropriate way to use clang-cl with libc++ instead of the Microsoft C++ standard library today? Preferably without using the `--driver-mode` option as the suggestion does here? it seems that clang-cl does not understand the `/NODEFAULTLIB` option, and I'm somewhat at a loss beyond that trying to figure out the appropriate way to accomplish this.

**Comment by sharadhr** [comment]
@jcm93 Have you tried `/clang:-stdlib=libc++`?

**Comment by iSplasher** [comment]
@sharadhr this gives `clang-cl: warning: argument unused during compilation: '-stdlib=libc++' [-Wunused-command-line-argument]` without fixing the issue

**Comment by oold** [comment]
Specifying `-stdlib=libc++` never works here as long as the target is `*-windows-msvc`:
```c++
case llvm::Triple::MSVC:
case llvm::Triple::UnknownEnvironment:
  if (Args.getLastArgValue(options::OPT_fuse_ld_EQ)
          .starts_with_insensitive("bfd"))
    TC = std::make_unique<toolchains::CrossWindowsToolChain>(
        *this, Target, Args);
  else
    TC =
        std::make_unique<toolchains::MSVCToolChain>(*this, Target, Args);
  break;
}
```
```c++
void MSVCToolChain::AddClangCXXStdlibIncludeArgs(const ArgList &DriverArgs,
                                                 ArgStringList &CC1Args) const {
  // FIXME: There should probably be logic here to find libc++ on Windows.
}
```
Doesn't matter how you pass it or which driver mode you pick.
