### ISSUE TITLE
LLVM 13.0.0 'opt' tool does not recognize '-print-memoryssa' option

### ISSUE THREAD

**Issue by adriaanjacobs** [llvm/llvm-project#53005]
As stated in the title.
```
$ ./opt --version
LLVM (http://llvm.org/):
  LLVM version 13.0.0
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: znver1
$ ./opt --print-memoryssa file.ll
WARNING: You're attempting to print out a bitcode file.
This is inadvisable as it may cause display problems. If
you REALLY want to taste LLVM bitcode first-hand, you
can force output with the `-f' option.

./opt: unknown pass name 'print-memoryssa'
$ ./opt -print-memoryssa file.ll
WARNING: You're attempting to print out a bitcode file.
This is inadvisable as it may cause display problems. If
you REALLY want to taste LLVM bitcode first-hand, you
can force output with the `-f' option.

./opt: unknown pass name 'print-memoryssa'
```

opt-12 does recognize these options. In opt 13, they are still listed under the `-help` output:
```
$ ./opt --version
LLVM (http://llvm.org/):
  LLVM version 13.0.0
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: znver1
$ ./opt -help | grep print-memoryssa
      --print-memoryssa                                                    - Memory SSA Printer
```

**Comment by fhahn** [comment]
This is a bit unfortunate, but works as expected I think. `-print-memoryssa` invokes a legacy pass and the new pass manager became the default in 13.0. The new way is to use `-passes='print<memoryssa>'`. Or pass `-enable-new-pm=0` to use the legacy pass manager.

**Comment by fhahn** [comment]
Reopening, as the help message should not print invalid options

**Comment by fhahn** [comment]
Note that `-help` already includes `  Optimizations available (use '-passes=' for the new pass manager)`

**Comment by adriaanjacobs** [comment]
Thanks for the quick response. I forgot to keep in mind that the way passes are run had changed between 12 and 13.

**Comment by fhahn** [comment]
> Thanks for the quick response. I forgot to keep in mind that the way passes are run had changed between 12 and 13. Can this then be closed anyway since the help message already mentions it?

Yeah, I think it makes sense to close this!
