### ISSUE TITLE
Create a team for lld:MachO label

### ISSUE THREAD

**Issue by keith** [llvm/llvm-project#53019]
I assume we generally want to mirror https://reviews.llvm.org/project/members/90/

Thanks for doing this

Reference https://lists.llvm.org/pipermail/llvm-dev/2022-January/154537.html

**Comment by tstellar** [comment]
> I assume we generally want to mirror https://reviews.llvm.org/project/members/90/
> 
If we were to autopopulate the teams, I think it would be better to get the names from bugzilla rather than Phabricator.

> Thanks for doing this
> 
> Reference https://lists.llvm.org/pipermail/llvm-dev/2022-January/154537.html

I've added the team, you can request access to the team now.

**Comment by keith** [comment]
Thanks!

**Comment by keith** [comment]
FYI @int3 @oontvoo @nico @MaskRay @thevinster in case you want to auto-subscribe to lld macho issues you can now request to join https://github.com/orgs/llvm/teams/issue-subscribers-lld-macho/members
