### ISSUE TITLE
Make [[clang::nomerge]] work for trap intrinsics such as __debugbreak and __builtin_trap

### ISSUE THREAD

**Issue by rnk** [llvm/llvm-project#53011]
Consider:
https://gcc.godbolt.org/z/esvPqdfn9

```
#define NOMERGE [[clang::nomerge]]
bool condition();
void mergeChecks() {
    if (condition())
      NOMERGE __builtin_trap();
      if (condition())
      NOMERGE __builtin_trap();
      if (condition())
      NOMERGE __builtin_trap();
}
```

LLVM folds all these traps together:
```
_Z11mergeChecksv: # @_Z11mergeChecksv
  push rax
  call _Z9conditionv
  test al, al
  jne .LBB0_4
  call _Z9conditionv
  test al, al
  jne .LBB0_4
  call _Z9conditionv
  test al, al
  jne .LBB0_4
  pop rax
  ret
.LBB0_4: # %if.then
  ud2
```

Ideally, the nomerge attribute should prevent this. Currently the attribute only really works with call expressions.

**Comment by davidben** [comment]
We currently use an inline asm block in Chromium, basically to work around not being able to say this in `CHECK`s. If `[[clang::nomerge]] __builtin_trap()` worked, I suspect we could switch to that!

**Comment by rnk** [comment]
@ZequanWu  started work on this in https://reviews.llvm.org/D146164 , but I think it stalled out over the concern of extending support to all the other builtins which generate calls (`__builtin_printf`, etc).
