### ISSUE TITLE
Create teams for every MLIR label

### ISSUE THREAD

**Issue by joker-eph** [llvm/llvm-project#53024]
As requested in the email to llvm-dev.

**Comment by tstellar** [comment]
Ok, I've created all the teams, you can request to join them now.

**Comment by joker-eph** [comment]
Are they supposed to show up here: https://github.com/orgs/llvm/teams ? I don't see any right now (I see 13 teams)

**Comment by joker-eph** [comment]
<img width="1009" alt="Screen Shot 2022-01-05 at 8 48 38 PM" src="https://user-images.githubusercontent.com/3372300/148329785-7c4822e3-67f3-416e-9651-43419454524d.png">

**Comment by tstellar** [comment]
@joker-eph I've fixed it, so they should be visible now.
