### ISSUE TITLE
Create a team for lld:wasm label

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#53028]
Thanks for doing this for https://github.com/llvm/llvm-project/labels/lld:wasm

Reference https://lists.llvm.org/pipermail/llvm-dev/2022-January/154537.html

**Comment by tstellar** [comment]
I've created the team, you can request to join it now.

**Comment by MaskRay** [comment]
@sbc100 in case you are interested:

* Visit https://github.com/orgs/llvm/teams/issue-subscribers-lld-wasm/ (this URL is available on https://github.com/orgs/llvm/teams)
* Click the "Members" tab
* Click the "Request to join" button

**Comment by sbc100** [comment]
Thanks!  Done.
