### ISSUE TITLE
Create a team for lld:ELF label

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#53023]
Thanks for doing this for https://github.com/llvm/llvm-project/labels/lld:ELF

Reference https://lists.llvm.org/pipermail/llvm-dev/2022-January/154537.html

**Comment by tstellar** [comment]
I've created the team, you can request to join it now.

**Comment by MaskRay** [comment]
FYI @bd1976bris @GeorgiiR @igorkudrin @smithp35 in case you want to auto-subscribe to lld:ELF issues you can now request to join https://github.com/orgs/llvm/teams/issue-subscribers-lld-elf/members
