### ISSUE TITLE
Create a team for lld:COFF label

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#53027]
Thanks for doing this for https://github.com/llvm/llvm-project/labels/lld:COFF

Reference https://lists.llvm.org/pipermail/llvm-dev/2022-January/154537.html

**Comment by tstellar** [comment]
I've created the team, you can request to join it now.

**Comment by MaskRay** [comment]
FYI @aganea @amykhuang @rnk @mstorsjo in case you want to auto-subscribe to lld:COFF issues you can now request to join https://github.com/orgs/llvm/teams/issue-subscribers-lld-coff/members
