### ISSUE TITLE
[MLIR] Faulty *.md format for StaticInterfaceMethod

### ISSUE THREAD

**Issue by ZoranZomborat** [llvm/llvm-project#53036]
Thread started in https://llvm.discourse.group/t/faulty-md-format-for-staticinterfacemethod/5096 .

Tablegen compilation to .md file generates faulty format whenever an interface with StaticInterfaceMethod is defined.

We’re seeing a lack of new line after the StaticInterfaceMethod declaration in .md, and thus subsequent contents does not start at a new line.

```
//
// ToyInterface
//

def ToyInterface : OpInterface<“ToyInterface”> {
let description = “Interface to toy around”;

let cppNamespace = "toy";

let methods = [
    StaticInterfaceMethod<
        "Check presence of new line.",
        "bool", "hasNewline", (ins),
        [{
            return false;
        }]
    >
];
}

```

**Comment by jpienaar** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/794056e86a53beff8e80f3a4fd8926e776a1f65e
