### ISSUE TITLE
New "team" request for subscribing to various tools

### ISSUE THREAD

**Issue by jh7370** [llvm/llvm-project#53035]
I was previously subscribed to the following components on bugzilla, and would like to have equivalent subscriptions on them, but don't see equivalent teams for them yet. Please could you add them:

llvm-cxxfilt
llvm-dwarfdump
llvm-nm
llvm-objcopy/strip
llvm-readobj
llvm-size
llvm-strings
llvm-symbolizer

Also @MaskRay, as I imagine he'd like to be subscribed on some of these teams once they've been created.

**Comment by tstellar** [comment]
@jh7370 I've created the teams, please submit a request to join  them.

**Comment by jh7370** [comment]
Thanks, I've requested to join them all. I'll close this now, on the assumption there's nothing else that's needed.
