### ISSUE TITLE
Create a team for clang-tidy and clang-query

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#53041]
Can we have issue subscriber lists for these two tools? Thanks!

**Comment by tstellar** [comment]
I've created the team, please submit a request to join.

**Comment by AaronBallman** [comment]
Thanks, I've joined!

**Comment by whisperity** [comment]
Hey @AaronBallman or @tstellar!
Could you please add me to the **clang-tidy** team too? I did not find where I could add myself...

**Comment by AaronBallman** [comment]
@whisperity -- you can join https://github.com/orgs/llvm/teams/issue-subscribers-clang-tidy/members

**Comment by whisperity** [comment]
@AaronBallman Ah! (Snark: Just goes to show how non-trivial GH's interface is...)
