### ISSUE TITLE
Create team for language modes

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#53040]
Thanks for putting together teams so we can subscribe to issue labels! I'd like to see teams added for the following categories (so that I can be added to them):

C, C2X, C11, C18 (which desperately needs to be renamed to C17 because there is no such thing as C18)
C++, C++11, C++14. C++17, C++20

**Comment by tstellar** [comment]
I've created the teams, so you can request to join them, but I need to fix the notifier to work with teams with ++ in the name.

**Comment by tstellar** [comment]
Let's leave it open.

**Comment by tstellar** [comment]
I've submitted a fix for the ++ issue here: https://reviews.llvm.org/D116762

**Comment by AaronBallman** [comment]
I believe that a2adebf409ce2559618720039f19d61281b182bc addresses the special character issues, so this can be closed. Do you agree @tstellar?

**Comment by tstellar** [comment]
@AaronBallman Do you also want a team for c++2b ?

**Comment by AaronBallman** [comment]
I think we do, but I've been assuming it'll be easy for us to rename these "variable" team names once the standards are finalized without requiring team members to take action. e.g., the `c2x` team will become the `c23` team and the `c++2b` team becomes the `c++23` team, rather than having two separate teams for each release.

**Comment by AaronBallman** [comment]
I think this can now be closed, so closing (feel free to reopen if you think there's more to be done here).
