### ISSUE TITLE
Create a team for tools:llvm-exegesis

### ISSUE THREAD

**Issue by oontvoo** [llvm/llvm-project#53043]
https://github.com/llvm/llvm-project/labels/tools:llvm-exegesis

Thanks!

**Comment by oontvoo** [comment]
FYI: @legrosbuffle @gchatelet Ondrej

**Comment by tstellar** [comment]
I've created the team, you can request membership here: https://github.com/orgs/llvm/teams/issue-subscribers-tools-llvm-exegesis

**Comment by oontvoo** [comment]
Thanks!
