### ISSUE TITLE
Please create team for "debuginfo"

### ISSUE THREAD

**Issue by pogo59** [llvm/llvm-project#53053]
Thanks for doing this for https://github.com/llvm/llvm-project/labels/debuginfo

Reference https://lists.llvm.org/pipermail/llvm-dev/2022-January/154537.html

**Comment by tstellar** [comment]
The team has been created, you can request membership here: https://github.com/orgs/llvm/teams/issue-subscribers-debuginfo

**Comment by pogo59** [comment]
Thanks @tstellar !
