### ISSUE TITLE
Please backport "[InlineCost] model calls to llvm.is.constant* more carefully" to 13.x

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#53058]
commit 9697f93587f46300814f1c6c68af347441d6e05d
helps fix a kernel modpost warning: https://github.com/ClangBuiltLinux/linux/issues/1302
This was also reported by Linus Torvalds on clang-13.0
https://lore.kernel.org/llvm/CAHk-=wh-f=eyP3i6nc8Hj49E4UKtgYionLs4LZbZYDorh3OLjQ@mail.gmail.com/
cc @tstellar @nathanchance @kazutakahirata

**Comment by tstellar** [comment]
@kazutakahirata Do you have an opinion on backporting this?

**Comment by tstellar** [comment]
Merged: 52a400d8e4c4
