### ISSUE TITLE
llvm installer on windows missing LLVMConfig.cmake

### ISSUE THREAD

**Issue by funchal** [llvm/llvm-project#53052]
I have tried both the LLVM 13 and 12 installers (win64 versions) available on github on the Releases page -- both seem to be missing LLVMConfig.cmake, which causes cmake to error with

```
    CMake Error at CMakeLists.txt:9 (find_package):
      Could not find a package configuration file provided by "LLVM" with any of
      the following names:

        LLVMConfig.cmake
        llvm-config.cmake
```

I can see this file in the source distribution, so it seems to be just missing in the installer.

**Comment by funchal** [comment]
`LLVMConfigExtensions.cmake` is added in this `install(` statement but not `LLVMConfig.cmake`.

https://github.com/llvm/llvm-project/blob/a44ef999fb5e9243df9c4459df1b17b66aa3fd23/llvm/cmake/modules/AddLLVM.cmake#L1057

**Comment by kleinesfilmroellchen** [comment]
Can confirm that the installer for 13 is missing llvm-config.

**Comment by retrooper** [comment]
Still?

**Comment by retrooper** [comment]
Any news on this as I can't get it working

**Comment by retrooper** [comment]
Even downgrading to llvm 11 didn't help

**Comment by retrooper** [comment]
Building LLVM is over 40 gigabytes on my system. Please fix the installer.

**Comment by ongamex** [comment]
Still an issue with 15.0.4

These is just this file LLVMConfigExtensions.cmake , containing a single line:
set(LLVM_STATIC_EXTENSIONS )

I need this in order to build - https://github.com/KhronosGroup/SPIRV-LLVM-Translator

**Comment by atorstling** [comment]
I'd like to resurface this one. I was trying to install https://github.com/p-ranav/fccf on windows, and now it turns out I need to build LLVM from source for that. So this might be a big usability problem for downstream tools that aren't shipping pre-built binaries. 

I would vote instead of commenting if I could, sorry for the noise.

**Comment by hYdos** [comment]
Still an issue. Its a shame its not getting any attention and lowers usability

**Comment by joshfinley** [comment]
> Tries to install LLVM from source - massive roadblocks
> Tries to install LLVM from release - missing integral components
> Looks up issue - unresolved for 568 days (its one file)

I understand that this project is a monster to maintain and there's only a handful.

**Comment by zmodem** [comment]
The Windows installer is focused on shipping LLVM as a toolchain: clang, lld, and related tools. It does not provide the LLVM development tools like opt, llc, etc. and also not the libraries and llvm-config.

There has been some discussion about shipping more tools in #51192, but shipping libraries is trickier. First of all we don't have a good way of building LLVM as a dll. We would also have to make sure the c runtime library matches what the client is using.

For these reasons, for users who want to use LLVM as a library or use the development tools, it's recommended to build LLVM from source.

If folks want to work on making LLVM easier to ship as a library on Windows, patches are welcome.

**Comment by kleinesfilmroellchen** [comment]
> The Windows installer is focused on shipping LLVM as a toolchain: clang, lld, and related tools. It does not provide the LLVM development tools like opt, llc, etc. and also not the libraries and llvm-config.

One of the most useful and common applications of LLVM is embedding it as a library in another tool like a compiler. Not providing binaries for this purpose for a project that's so incredibly resource-intensive to build (on all accounts; disk space, memory usage, time) makes LLVM on Windows much less useful than it could be. I'm not convinced that shipping highly compatible libraries on Windows is a big issue given the high degree of compatibility in the Windows API layers, MSVC, and C library.

**Comment by GanbaruTobi** [comment]
llvm-config is still missing

**Comment by bamiaux** [comment]
This pr exports a tarball containing llvm-config

**Comment by akrisfx** [comment]
Still an issue. llvm-config is still missing on 18 llvm [](https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/LLVM-18.1.8-win64.exe)

**Comment by zmodem** [comment]
> Still an issue. llvm-config is still missing on 18 llvm [this](https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/LLVM-18.1.8-win64.exe)

It's in the tarball: https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang+llvm-18.1.8-x86_64-pc-windows-msvc.tar.xz

**Comment by chris-stones** [comment]
bump - still an issue on llvm-20.

**Comment by dkaszews** [comment]
Still an issue in 20.1.8, installed from official winget repo. Downloading 1GB tarball to get a single missing file is not a convenient solution. Please add it to the installer.

**Comment by 3DGISKing** [comment]
same for me

**Comment by newclarityex** [comment]
bump
