### ISSUE TITLE
Please create team for "lldb"

### ISSUE THREAD

**Issue by JDevlieghere** [llvm/llvm-project#53055]
Inspired by @pogo59's request for a debuginfo team (#53053), please also create one for lldb: https://github.com/llvm/llvm-project/labels/lldb

Reference https://lists.llvm.org/pipermail/llvm-dev/2022-January/154537.html

**Comment by tstellar** [comment]
The team has been created, you can request membership here: https://github.com/orgs/llvm/teams/issue-subscribers-lldb

**Comment by JDevlieghere** [comment]
Thanks Tom!
