### ISSUE TITLE
Please create a team for 'clang:static analyzer'

### ISSUE THREAD

**Issue by martong** [llvm/llvm-project#53065]
FYI @steakhal @haoNoQ @ASDenysPetrov @Szelethus @gamesh411 , subscribe to this team to be notified on the new issues, see https://lists.llvm.org/pipermail/cfe-dev/2022-January/069666.html

**Comment by steakhal** [comment]
@Snape3058

**Comment by martong** [comment]
@whisperity

**Comment by haoNoQ** [comment]
Thanks Gabor!
