### ISSUE TITLE
please backport "[Clang][CFG] check children statements of asm goto"

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#53076]
please consider backporting 3a604fdbcd5fd9ca41f6659692bb4ad2151c3cf4 to the 13.0.1 release.

It was creating false positives warnings that are hampering our [efforts](https://github.com/ClangBuiltLinux/linux/issues/1439) to enable -Warray-bounds coverage in the Linux kernel.

cc @tstellar @nathanchance @gwelymernans @efriedma-quic @jyknight @jyu2-git

**Comment by tstellar** [comment]
@efriedma-quic @jyknight @gwelymernans  @jyu2-git Any objections to backporting this?

**Comment by gwelymernans** [comment]
No objection.

**Comment by tstellar** [comment]
Merged: 1ac6bb3c4dd4
