### ISSUE TITLE
[optimization] gcc generate better code than clang base on conditionally selection

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#53071]
test case: 
```
int test_32(int a, int b) { 
    return a ? b-1 : b+1; 
}
```

Compared to gcc, clang produces slightly more verbose code for a sequence
https://godbolt.org/z/5PeYYzvGK

**Comment by RKSimon** [comment]
CC @rotateright
This is not dissimilar to Issue #53006 and the x86 codegen could be improved as well: https://godbolt.org/z/r8Yb3aTnf

**Comment by vfdff** [comment]
> CC @rotateright This is not dissimilar to Issue #53006 and the x86 codegen could be improved as well: https://godbolt.org/z/r8Yb3aTnf

It has a some dissimilar,  Issue #53006 need improve the match of select itself, while here need improve the match of select + add
```
      t15: i32 = select_cc t2, Constant:i32<0>, Constant:i32<1>, Constant:i32<-1>, seteq:ch
      t4: i32,ch = CopyFromReg t0, Register:i32 %1
    t11: i32 = add nsw t15, t4
```

**Comment by rotateright** [comment]
The fix for #53006 alters the x86 asm on this example to:
```
negl %edi
sbbl %eax, %eax
orl $1, %eax
addl %esi, %eax
```
The gcc output (which does not sink the inc/dec math after the select) looks like this:
```
leal -1(%rsi), %eax
addl $1, %esi
testl %edi, %edi
cmove %esi, %eax
```

I don't see a clear winner (depends on whether cmov is implemented as a fast 1-uop instruction?).

**Comment by vfdff** [comment]
@rotateright  I add a patch on https://reviews.llvm.org/D116915, can you help to review, thanks very much!

**Comment by vfdff** [comment]
spilt to alternative patch https://reviews.llvm.org/D119105
