### ISSUE TITLE
Backport [Clang][Sema] Avoid crashing for va_arg expressions with bool argument

### ISSUE THREAD

**Issue by egorzhdan** [llvm/llvm-project#53078]
Could you please backport c033f0d to 13.0.1?

It fixes a compiler crash introduced in another change recently.

Review: https://reviews.llvm.org/D116272

**Comment by tstellar** [comment]
@AaronBallman What's your opinion on backporting this?

**Comment by tstellar** [comment]
> @AaronBallman What's your opinion on backporting this?

I see you've already answered this here: https://reviews.llvm.org/D116272

**Comment by tstellar** [comment]
Merged: bfb1bd1b9906
