### ISSUE TITLE
openMP on macbook

### ISSUE THREAD

**Issue by 23navi** [llvm/llvm-project#53086]
Unable to use openMP on macbook pro 2021 model. The brew install llvm downloads the files to opt and not usr, and the compiler is set to use the usr, and even when I try to change the directory and path, the compiler is not able to find the header file

**Comment by 23navi** [comment]
Someone please help me with this as I am not able to run my college project and it is important

**Comment by fhahn** [comment]
This sounds like an issue with your setup and not a bug in LLVM/Clang. Are you using the compiler installed via `brew`? It should know where to look for the openmp headers. 

It looks like there is plenty of information available online on that topic, https://stackoverflow.com/questions/43555410/enable-openmp-support-in-clang-in-mac-os-x-sierra-mojave looks promising.
