### ISSUE TITLE
CONTRIBUTING.md discourages GitHub usage for issues, but crash backtraces refer to GitHub for issue reporting

### ISSUE THREAD

**Issue by creator1creeper1** [llvm/llvm-project#53091]
According to CONTRIBUTING.md, "Please note that at the moment the LLVM project does not use either Github pull requests or Github issues.".
However, according to a crash backtrace I got just now, I should "PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/".
I think CONTRIBUTING.md should be updated.

**Comment by TestingPlant** [comment]
References to the Bugzilla also exist at:
- https://llvm.org/docs/HowToSubmitABug.html
- https://llvm.org/docs/Contributing.html

**Comment by keith** [comment]
Thanks for filing this! I submitted a patch for the cases mentioned here https://reviews.llvm.org/D116898

**Comment by keith** [comment]
Please file any more you find!
