### ISSUE TITLE
Directory name issue in 12.0.1 release asset

### ISSUE THREAD

**Issue by jidicula** [llvm/llvm-project#53101]
When expanding the [x86_64 GNU Ubuntu-16.04 tarball](https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz) of binaries for [12.0.1](https://github.com/llvm/llvm-project/releases/tag/llvmorg-12.0.1), the resulting directory has a different name from the tarball:

tarball: `clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz`
directory: `clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-`

Would it be possible to upload the correctly formed tarball to the same release?

**Comment by Endilll** [comment]
I don't think it's possible without changing checksum as well, which is unfortunate.
Anyway, this is unsupported release by this point. Feel free to reopen if you run into this with recent releases.
