### ISSUE TITLE
Severe compile-time time regression in GlobalISel / Legalizer with Swift exposed by d0af732bd00c0390fbcc6f900e8a59eb3954106c

### ISSUE THREAD

**Issue by asl** [llvm/llvm-project#53109]
The downstream issue is https://bugs.swift.org/browse/SR-15531

Consider the attached bitcode. Running `llc ConnectionStateMachine.swift.o -O0` after d0af732bd00c0390fbcc6f900e8a59eb3954106c bumps the compilation time from 5 seconds to 90 seconds. The majority of time is spent in Legalizer. Adding https://reviews.llvm.org/D109154 reduces the compilation time down to ~25 seconds, but still a huge difference.

As far as I can see, this is a severe compile time regression for Swift 5.5 vs 5.6 affecting e.g. https://github.com/vapor/postgres-nio/issues/205 and some other downstream projects on aarch64

Tagging @TNorthover @ornata 

[ConnectionStateMachine.swift.o.zip](https://github.com/llvm/llvm-project/files/7838413/ConnectionStateMachine.swift.o.zip)

**Comment by ornata** [comment]
Taking a look at this right now...

**Comment by asl** [comment]
@ornata I think that the problem is only exposed by this revision

**Comment by ornata** [comment]
Using trunk LLVM @ acb8de565eaa2638d18362085085deb4628435b4:

With d0af732
```
$ time bin/llc -O0 ~/Downloads/ConnectionStateMachine.swift.o
real	0m10.582s
user	0m10.453s
sys	0m0.118s
```

Without d0af732
```
$ time bin/llc -O0 ~/Downloads/ConnectionStateMachine.swift.o
real	0m10.673s
user	0m10.554s
sys	0m0.111s
```

This is on an intel machine though. I'll try a M1 to verify that doesn't make a difference.

(Which LLVM commit is Swift at?)

**Comment by asl** [comment]
@ornata I'm checking with LLVM ToT right now and will keep you updated. Swift is ~ Aug 2021

**Comment by asl** [comment]
Ok, here is the full story. The issue was exposed by https://github.com/llvm/llvm-project/commit/d0af732bd00c0390fbcc6f900e8a59eb3954106c and fixed in mainline by https://github.com/llvm/llvm-project/commit/64bef13f083b3d980. The underlying issue seems to be quite clear.

Swift is currently using https://github.com/apple/llvm-project/tree/stable/20210726 branch, so was unlucky enough to make this branch in a ~3 week window between these changes :)

I submitted https://github.com/apple/llvm-project/pull/3804 which backports https://github.com/llvm/llvm-project/commit/64bef13f083b3d980

**Comment by asl** [comment]
The PR was merged. So, not it's up to Swift folks to cherry pick to appropriate branches as necessary.
