### ISSUE TITLE
Miscompile with opt -constraint-elimination

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#53123]
llvm commit: 4a42ce25088
Reproduce with:
 opt -passes='constraint-elimination' -S -o - bbi-64641.ll
[bbi-64641.ll.gz](https://github.com/llvm/llvm-project/files/7844990/bbi-64641.ll.gz)

Result:
The branch
  br i1 %cmp11, label %bb.3, label %bb.2
is changed to
  br i1 false, label %bb.3, label %bb.2
in bb.1 which I think this is wrong.

I added some comments in the input file showing the values of some instructions which would make the function end up at bb.3. But after the rewrite of the branch we end up at bb.2 instead.

This starts happening with https://reviews.llvm.org/rG1f1f037ed3101d3074f65faceca81218c88a505c
`
[ConstraintElimination] Improve index handing during constraint building.

This patch improves the index management during constraint building.
Previously, the code rejected constraints which used values that were not
part of Value2Index, but after combining the coefficients of the new
indices were 0 (if ShouldAdd was 0).

In those cases, no new indices need to be added. Instead of adding to
Value2Index directly, add new indices to the NewIndices map. The caller
can then check if it needs to add any new indices.

This enables checking constraints like a + x <= a + n to x <= n,
even if there is no constraint for a directly.
`

**Comment by fhahn** [comment]
Thanks for the report. The issue was that the wrong coefficient was used for the second operand of a subtraction. Should be fixed in 8a15caaae561
