### ISSUE TITLE
[BPF] rust BPF one critical bound check is opt out lead to load failure

### ISSUE THREAD

**Issue by kevi-sun** [llvm/llvm-project#53121]
**Environment**
OS: Linux 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux, it is a ubuntu 20.4 based docker, with "priviledge" enabled
Rust: rustc 1.56.1 (59eed8a2a 2021-11-01)
llvm version: 13
The application is based on rust crate [redbpf](https://github.com/foniod/redbpf)

**Description about the application**
The application would like to analyse the TCP packet based on dedicated port, extract various information on IP and TCP layer, including the tcp options, you can think of [p0f](https://github.com/p0f/p0f).

The simplified application framework that related with issue is as following 
[bpf_code.txt](https://github.com/llvm/llvm-project/files/7844454/bpf_code.txt)

when loading the application, it report the following errors

```
regs=8 stack=0 before 80: (bf) r4 = r5
regs=8 stack=0 before 79: (0f) r5 += r4
regs=8 stack=0 before 78: (71) r4 = *(u8 *)(r4 +0)
regs=8 stack=0 before 77: (2d) if r8 > r2 goto pc+10
 R0_r=pkt(id=2,off=14,r=14,umax_value=120,var_off=(0x0; 0x7c),s32_max_value=124,u32_max_value=124) R1_r=ctx(id=0,off=0,imm=0) R2_r=pkt_end(id=0,off=0,imm=0) R3_r=invP0 R4_r=pkt(id=1,off=35,r=35,umax_value=60,var_off=(0x0; 0x3c)) R5_r=pkt(id=1,off=34,r=35,umax_value=60,var_off=(0x0; 0x3c)) R6_w=invP0 R7=inv4 R8_rw=pkt(id=1,off=36,r=35,umax_value=60,var_off=(0x0; 0x3c)) R9_r=inv1 R10=fp0 fp-56_w=00000000 fp-64_w=00000000 fp-72_w=00000000 fp-80_r=inv
parent already had regs=8 stack=0 marks
88: safe
142: R0=pkt(id=2,off=14,r=14,umax_value=120,var_off=(0x0; 0x7c),s32_max_value=124,u32_max_value=124) R1=ctx(id=0,off=0,imm=0) R2=pkt_end(id=0,off=0,imm=0) R3=inv0 R4=pkt(id=3,off=34,r=33,umax_value=315,var_off=(0x0; 0x1ff),s32_max_value=511,u32_max_value=511) R5=invP0 R6=invP0 R7=inv4 R8=pkt(id=1,off=36,r=36,umax_value=60,var_off=(0x0; 0x3c)) R9=inv1 R10=fp0 fp-56=00000000 fp-64=00000000 fp-72=00000000 fp-80=inv
142: (b7) r9 = 2
143: R0=pkt(id=2,off=14,r=14,umax_value=120,var_off=(0x0; 0x7c),s32_max_value=124,u32_max_value=124) R1=ctx(id=0,off=0,imm=0) R2=pkt_end(id=0,off=0,imm=0) R3=inv0 R4=pkt(id=3,off=34,r=33,umax_value=315,var_off=(0x0; 0x1ff),s32_max_value=511,u32_max_value=511) R5=invP0 R6=invP0 R7=inv4 R8=pkt(id=1,off=36,r=36,umax_value=60,var_off=(0x0; 0x3c)) R9_w=inv2 R10=fp0 fp-56=00000000 fp-64=00000000 fp-72=00000000 fp-80=inv
143: (71) r5 = *(u8 *)(r4 +0)
invalid access to packet, off=34 size=1, R4(id=3,off=34,r=33)
R4 offset is outside of the packet
processed 142 insns (limit 1000000) max_states_per_insn 0 total_states 9 peak_states 9 mark_read 7
```

**Initial analysis:**
When extract the elf with debug information [bpf_objdump.txt](https://github.com/llvm/llvm-project/files/7844491/bpf_objdump.txt), I couldn't find the bound check setense of the following is gone from the ELF. 

```rust
if tcp_option_pos + 1 > data_end {
    break;
}
let tcp_opt = *(tcp_option_pos as *const u8);
```

I guess it was opt-out during completing the rust to llvm IR code for some reason:
- Since it is a common pattern in C BPF, tho I think it is not opt out for C to BPF code.
- there are quite a lot of boundary check for tcp_option_pos before changing the values, from the language perspective, this might be not necessary, while it is necessary to make sure the BPF register offset/range correct
- If I change the above application in the "match tcp_opt" part, for each cases (including TCPOPT_SACK that has 4 possible values) use the literal number (that is known during the compiler phase) to update the tcp_option_pos rather than the variable len , then the application could be passed by the Linux BPF verifier and work properly. But unfortunately, adding other application logic, those extra branches will lead to error of "BPF program is too large".

I think opt-out this critical bound-check for BPF is a potential bug.

**Comment by Endilll** [comment]
@kevi-sun Can you test this with a newer Clang?

**Comment by kevi-sun** [comment]
Hi @Endilll thanks for your reply, I would like to close this ticket since this task was suspended for quite long time and I don't have a test env for that now. I'll retest this if I back to this task in the future.
