### ISSUE TITLE
Aarch64: why clang combines sqadd + sqrdmulh into sqrdmlah?

### ISSUE THREAD

**Issue by Nekotekina** [llvm/llvm-project#53120]
Hello, I accidentally peeked at arm_neon.h definitions in clang and noticed that vqrdmlahq_s16 iintrinsic is composed from saturating add and saturating rounding doubling multiplication. I tried to test it, and it seems that in the edge case (saturated multiplication of INT16_MIN * INT16_MIN producing INT16_MAX) the result of saturating addition is wrong if MLA would not saturate at all. I'm only learning the basics and can only test in emulator, so I may be missing something. In the godbolt example gcc does not combine.

https://godbolt.org/z/E9WvPTbWG
```C++
#include <arm_neon.h>

int16x8_t good(int16x8_t a, int16x8_t b, int16x8_t c)
{
    return vqrdmlahq_s16(c, a, b);
}

int16x8_t bad(int16x8_t a, int16x8_t b, int16x8_t c)
{
    return vqaddq_s16(c, vqrdmulhq_s16(a, b));
}
```

**Comment by DavidSpickett** [comment]
I tried making a reproducer: [neon_test.c.txt](https://github.com/llvm/llvm-project/files/7845429/neon_test.c.txt) (remove/ignore the .txt, seems like Github is refusing attachments of .c type, anyway)

I do see different behaviour between gcc and clang on an AArch64 system natively.

```
$ ./bin/clang /tmp/test.c -o /tmp/test.o -O3 -march=armv8.1-a && /tmp/test.o
Good:
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
Bad:
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
```
```
$ gcc /tmp/test.c -o /tmp/test.o -O3 -march=armv8.1-a && /tmp/test.o
Good:
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
Bad:
0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff,
```

Though at first I wasn't sure what the addition parameter values should be. INT_MIN behaves differently so I assume that's what you meant, please correct me if not.

I agree that on first read it seems like a mul plus add would be an mla. But I'm not familiar enough with the details to explain your case. Could you elaborate with an example, perhaps with just one element?

Here are links to the intrinsics docs for their exact descriptions:
https://developer.arm.com/architectures/instruction-sets/intrinsics/vqrdmlahq_s16
https://developer.arm.com/architectures/instruction-sets/intrinsics/vqrdmulhq_s16
https://developer.arm.com/architectures/instruction-sets/intrinsics/vqaddq_s16

My instinct says that this part of the `vqrdmlahq_s16` description might be the key, but just a guess.

"multiplies the vector elements of the first source SIMD&FP register with the corresponding vector elements of the second source SIMD&FP register **without** saturating the multiply results"

**Comment by vfdff** [comment]
so the user need to prevent the result will overflow with  vqrdmlahq_s16 in clang to keep the identical?
