### ISSUE TITLE
[AMDGPU][MC][GFX10] Add support of vaddr=saddr=off for FLAT SCRATCH opcodes

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#53136]
GFX10 should support vaddr=saddr=off for scratch opcodes. This is specified by encoding SADDR=EXEC_HI. Note that in this mode inst.offset must be >= 0.

LLVM assembler currently expects that either vaddr=off or saddr=off but not both:

          scratch_load_sbyte v1, off, s3     // ok
          scratch_load_sbyte v1, v2, off     // ok

When both vaddr and saddr are set to off, the assembler triggers an error.

          scratch_load_sbyte v1, off, off    // sp3 ok, llvm fails

**Comment by Flakebi** [comment]
There are hardware bugs before gfx10.3, you need to have either a vgpr or an sgpr before that. It should work fine on gfx10.3+.

```sh
$ echo 'scratch_load_sbyte v1, off, off' | bin/llvm-mc -triple amdgcn-amd-amdhsa -mcpu=gfx1010
        .text
        .amdgcn_target "amdgcn-amd-amdhsa--gfx1010+xnack"
<stdin>:1:1: error: operands are not valid for this GPU or mode
scratch_load_sbyte v1, off, off
^

$ echo 'scratch_load_sbyte v1, off, off' | bin/llvm-mc -triple amdgcn-amd-amdhsa -mcpu=gfx1030
        .text
        .amdgcn_target "amdgcn-amd-amdhsa--gfx1030"
        scratch_load_sbyte v1, off, off
```

**Comment by dpreobra** [comment]
I see, thanks!
