### ISSUE TITLE
Missing teams for some popular clang labels

### ISSUE THREAD

**Issue by bcardosolopes** [llvm/llvm-project#53135]
As suggested by Tom in https://lists.llvm.org/pipermail/llvm-dev/2022-January/154537.html, here's a request for a few more teams on the following labels:

clang:codegen
clang:driver
clang:frontend
clang:modules

Thanks!

**Comment by tstellar** [comment]
I've created the team.  You can apply for membership at https://github.com/orgs/llvm/teams/issue-subscribers-clang:driver

**Comment by tstellar** [comment]
I've created the team.  You can apply for membership at https://github.com/orgs/llvm/teams/issue-subscribers-clang:frontend

**Comment by tstellar** [comment]
I've created the team.  You can apply for membership at https://github.com/orgs/llvm/teams/issue-subscribers-clang:modules

**Comment by bcardosolopes** [comment]
It all seems to be working, thanks Tom!
