### ISSUE TITLE
Cherry-pick SOURCE_DATE_EPOCH preservation in lit

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#53137]
It would probably make sense to cherry-pick https://github.com/llvm/llvm-project/commit/46c947af7ead0a939fbd7a93c370e7ead2128d07 into the 13.0.1 release.

It is needed to avoid some zlib related test failures on s390x. We currently have this as a patch in Fedora. cc @serge-sans-paille

**Comment by tstellar** [comment]
@sylvestre @dwblaikie Are you OK with backporting this?

**Comment by sylvestre** [comment]
sure, it is a trivial!

**Comment by tstellar** [comment]
Merged: 1ac6bb3c4dd4 bfb1bd1b9906 eecd0f055baa
