### ISSUE TITLE
Failed to pick up MLIR installation from `MLIRConfig.cmake`

### ISSUE THREAD

**Issue by jackalcooper** [llvm/llvm-project#53134]
- I am trying to setup a VSCode devcontainer with MLIR pre-built.
- This is my dockerfile and CMakeLists.txt. Very basic stuff:
```
FROM elixir
RUN apt update && apt install -y lsb-release wget software-properties-common
RUN wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 14
RUN apt update && apt install -y cmake ccache ninja-build libmlir-14-dev mlir-14-tools
```
```
cmake_minimum_required(VERSION 3.13.4)
project(standalone-dialect LANGUAGES CXX C)

set(CMAKE_BUILD_WITH_INSTALL_NAME_DIR ON)

set(CMAKE_CXX_STANDARD 14 CACHE STRING "C++ standard to conform to")

find_package(MLIR REQUIRED CONFIG)
```
- After running cmake (`cmake .. -DMLIR_DIR=$(llvm-config-14  --libdir)/cmake/mlir`):
```
CMake Error at /usr/lib/llvm-14/lib/cmake/mlir/MLIRTargets.cmake:1563 (message):
  The imported target "obj.MLIRCAPIDebug" references the file

     "/usr/lib/llvm-14/lib/objects-Release/obj.MLIRCAPIDebug/Debug.cpp.o"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/llvm-14/lib/cmake/mlir/MLIRTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/llvm-14/lib/cmake/mlir/MLIRConfig.cmake:30 (include)
  llvm-built/CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
See also "/workspaces/mlir_ex/cmake-build-dev/CMakeFiles/CMakeOutput.log".
```
- Note: RelWithDebInfo/ Release/ Debug `CMAKE_BUILD_TYPE` all tested, no difference. Couldn't find `Debug.cpp.o` anywhere after running `find`.

**Comment by jackalcooper** [comment]
cc @jpienaar

**Comment by joker-eph** [comment]
@stellaraccident @sylvestre : FYI

**Comment by joker-eph** [comment]
@stephenneuendorffer may have thoughts as well?

**Comment by jackalcooper** [comment]
I just checked current LLVM 14 apt release, same problem. @joker-eph

**Comment by sylvestre** [comment]
I am removing the files
`/usr/lib/llvm-14/lib/objects-Release/obj.MLIRCAPIDebug/` (with an ugly rm)
when generating the package but it seems that cmake still consider them as present
So, they should not be generated by cmake itself
how can i do that?

**Comment by jackalcooper** [comment]
@sylvestre Here is a reply by Stella Laurenzo I found in the Discord MLIR channel.

https://discord.com/channels/636084430946959380/642426447167881246/930634238926147634

> Stella Laurenzo — 01/12/2022
> I have limited exposure to the nightly releases, etc, but I've seen folks disabling emission of these objects: sounds like these releases were build with this OFF: https://github.com/llvm/llvm-project/blob/d23fa4f2f1319039b7d939a4bf68c493ba26b07a/mlir/CMakeLists.txt#L109
> GitHub
> [llvm-project/CMakeLists.txt at d23fa4f2f1319039b7d939a4bf68c493ba26...](https://github.com/llvm/llvm-project/blob/d23fa4f2f1319039b7d939a4bf68c493ba26b07a/mlir/CMakeLists.txt)[](https://opengraph.githubassets.com/be5a16a956b7e06edced841555c67be55850497c8528e52cbc03db92481d4f8e/llvm/llvm-project)
> The LLVM Project is a collection of modular and reusable compiler and toolchain technologies. Note: the repository does not accept github pull requests at this moment. Please submit your patches at...
> 
> It is tested at head (the standalone example does test this configuration, albeit imperfectly since it is on the same machine and is easy to think it is working when it is not).

**Comment by sylvestre** [comment]
I am now using -DMLIR_INSTALL_AGGREGATE_OBJECTS=Off, it should fix the issues once they are rebuilt

**Comment by jackalcooper** [comment]
It works now. Many thanks!

**Comment by sylvestre** [comment]
As you probably saw, we now have a test to make sure we don't regress:
https://github.com/opencollab/llvm-toolchain-integration-test-suite/pull/78/files

**Comment by jackalcooper** [comment]
> As you probably saw, we now have a test to make sure we don't regress: https://github.com/opencollab/llvm-toolchain-integration-test-suite/pull/78/files

That's cool👍

**Comment by jackalcooper** [comment]
@sylvestre in llvm 15 apt release the object files disappear again. Running `ls /usr/lib/llvm-15/lib | grep objects` shows nothing.  
MLIR libs installed:
```
root@55416f437bd0:/workspaces/met_linux# apt search  mlir
Sorting... Done
Full Text Search... Done
libmlir-15/now 1:15~++20220419072122+0f4ba02db398-1~exp1~20220419072212.225 arm64 [installed,local]
  Multi-Level Intermediate Representation library

libmlir-15-dev/now 1:15~++20220419072122+0f4ba02db398-1~exp1~20220419072212.225 arm64 [installed,local]
  Multi-Level Intermediate Representation library

mlir-15-tools/now 1:15~++20220419072122+0f4ba02db398-1~exp1~20220419072212.225 arm64 [installed,local]
  Multi-Level Intermediate Representation tools
```

Here is my command:
```
RUN --mount=type=cache,id=apt-dev,target=/var/cache/apt \
    wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh &&  \
    ./llvm.sh ${LLVM_VERSION} all && \
    rm llvm.sh &&  \
    apt-get install -y libmlir-${LLVM_VERSION}-dev mlir-${LLVM_VERSION}-tools && \
    rm -rf /var/lib/apt/lists/*
```

**Comment by sylvestre** [comment]
Could you please send me a simple CMake test case so that I can reproduce it?

My unit test still works

`2022-04-20T03:37:05.7226345Z PASS: LLVM regression suite :: minimal_mlir_cmake.txt (26 of 43)`
with
`15~++20220419063809+3de29ad20955`

**Comment by jackalcooper** [comment]
I opened a PR https://github.com/opencollab/llvm-toolchain-integration-test-suite/pull/82
