### ISSUE TITLE
[Coroutines] Coroutine frame allocated with a wrong alignment

### ISSUE THREAD

**Issue by ezhulenev** [llvm/llvm-project#53148]
Example: https://godbolt.org/z/Ea8rPzG18

If a value is used across suspension points and it is stored into the coroutine frame, it might have an invalid alignment. It seems that memory for the coroutine frame is allocated with a plain call to `operator new(size)`.

We stumbled upon this problem when generating LLVM IR from MLIR, but it's easy to reproduce it with C++20 coroutines as well.

```
struct alignas(512) overaligned {
 overaligned() { std::cout << "Consructed: " << ((intptr_t)(this) % 512) << "\n"; }
 ~overaligned() { std::cout << "Destructed: " << ((intptr_t)(this) % 512) << "\n"; }
 int n;
};

void sink(overaligned&) {

cppcoro::generator<const std::uint64_t> fibonacci()
{
  std::uint64_t a = 0, b = 1;
  overaligned st;
  sink(st);
  while (true)
  {
    co_yield b;
    auto tmp = a;
    a = b;
    b += tmp;
    sink(st);
  }
}
```

output:

```
Run
Consructed: 0       <--- this is from stack allocated value in main
Consructed: 176   <--- this is from the coroutine
```

**Comment by ChuanqiXu9** [comment]
Yeah, this is a known issue that the alignment requirement couldn't be satisfied if the alignment requirement of elements is large than 16... This issue shows we would better handle this in middle end since there are other users for switch based coroutine intrinsics.

**Comment by ezhulenev** [comment]
In our particular MLIR example the problem is in unaligned `vmovaps ymm0`

**Comment by ChuanqiXu9** [comment]
> In our particular MLIR example the problem is in unaligned `vmovaps ymm0`

This is lowered assembly. Could you offer the generated LLVM IR from MLIR?

**Comment by ezhulenev** [comment]
@d0k do you have a LLVM IR from your debugging session?

**Comment by d0k** [comment]
I don't have that IR anymore, but it happens whenever an AVX2 `__m256` gets spilled. Adapted the test case from above, segfaults: https://godbolt.org/z/z6jd3P4PM

**Comment by ChuanqiXu9** [comment]
If it lacks a  LLVM IR, I could only assume the problem in the case is same with the problem in C++ (The alignment of elements couldn't large than15). BTW, it should be possible to fix the above problem in frontend. For example, the frontend could call `std::new(size_t, align_t)` if it detects elements whose alignment is larger than 16. We couldn't do this in clang now since it violates the C++ standard. But I guess it might be possible to do it in MLIR.

**Comment by d0k** [comment]
MLIR calls malloc directly instead of `operator new`. I guess it could align that block of memory, but to what value?

https://github.com/llvm/llvm-project/blob/d4d016869d6cbd5fa1fa50fd178697028576ab1a/mlir/lib/Conversion/AsyncToLLVM/AsyncToLLVM.cpp#L370

**Comment by ChuanqiXu9** [comment]
Yeah, it should be the frontend to generate calls to allocation functions (no matter `std::new` or `malloc`).
>  I guess it could align that block of memory, but to what value?

Yeah, now it lacks an intrinsic that the frontend could get the value of the alignment. I would try to provide one recently.

**Comment by ChuanqiXu9** [comment]
Now we sent https://reviews.llvm.org/D117542 to offer llvm.coro.align intrinsic. So we should be able to solve the problem by fulfilling the corresponding alignment to aligned_alloc when emitting LLVM IR.
