### ISSUE TITLE
JSON compilation database spec is ambiguous

### ISSUE THREAD

**Issue by rtbo** [llvm/llvm-project#53143]
Hello,
While addressing issue [#8649](https://github.com/microsoft/vscode-cpptools/issues/8649) for `vscode-cpptools` extension, we noticed that the Clang compilation database format specification is ambiguous.

While the quotes escaping for the `"command"` field is clearly specified, there is no such specification for the `"arguments"` field. 
 1. Should each argument in the array be escaped for shell as is the `"command"` field?
 2. Or should the array be read "as is", like if it is sent directly to `execv`?

From what I have [tested](https://github.com/microsoft/vscode-cpptools/issues/8649#issuecomment-1010205199), the 2nd seems to apply, but it would be better to have the specification explicitly document this.

**Comment by sam-mccall** [comment]
Yeah, the latter is the intent.

I believe `command` was originally supported, required handling shell escaping that was bound to lead to confusion between implementations, so `arguments` was added to avoid the issue entirely.

I'll send a doc patch on Monday to clarify this.
