### ISSUE TITLE
//comment prefix spacing not working v13

### ISSUE THREAD

**Issue by mplexor** [llvm/llvm-project#53179]
```
---
Language:        Cpp
BasedOnStyle:  LLVM
SpacesInLineCommentPrefix:
  Minimum: 1
  Maximum: 0
```

```
switch (0) {
   case 0: test(); break; //should have prefix spacing
}
```

**Comment by mydeveloperday** [comment]
Is there a reason you are using a Maximum of 0? if you have a Minimum of 1?

What ever we do we have to make one of these 2 win? 

```
Minimum: 1
Maximum: 0
```

**Comment by mkurdej** [comment]
I agree with @mydeveloperday, having `Minimum > Maximum` doesn't make sense.
Making `Maximum: -1` (what you wanted) or `Maximum: 1` gives the expected result.

The documentation is pretty clear about it.
> SpacesInLineCommentPrefix (SpacesInLineComment) clang-format 14
> How many spaces are allowed at the start of a line comment. To disable the maximum set it to -1, apart from that the maximum takes precedence over the minimum.

Closing it. I let you reopen if you have an argument against.

**Comment by mplexor** [comment]
prefix spacing still doesnt work with ReflowComments:  false
ReflowComments:  false            #should not, not to touch comments due to diff contexts per line

**Comment by mplexor** [comment]
Thanks.
