### ISSUE TITLE
Please backport to 13.x: "[Driver][test] Fix undefined-libs.cpp when CLANG_DEFAULT_UNWINDLIB is libunwind"

### ISSUE THREAD

**Issue by mgorny** [llvm/llvm-project#53172]
Hopefully this one is trivial enough:

commit 3db1ade368e538ba795486eea4923e331a8dde5a
Author: Fangrui Song <i@maskray.me>
Date:   2021-10-08 23:40:22 +0200

    [Driver][test] Fix undefined-libs.cpp when CLANG_DEFAULT_UNWINDLIB is libunwind

**Comment by tstellar** [comment]
@MaskRay What do you think about this?

**Comment by MaskRay** [comment]
LGTM

**Comment by tstellar** [comment]
Merged: 1f1854ce0fe5
