### ISSUE TITLE
AArch64: Linker not removing unused functions (gc-sections related)

### ISSUE THREAD

**Issue by rovka** [llvm/llvm-project#53185]
I'm seeing 6 new check-all failures between rc1 and rc2 for llvm-13.0.1 on AArch64:
Profile-aarch64 :: Linux/coverage-linkage-lld.cpp
Profile-aarch64 :: Linux/coverage-weak-lld.cpp
Profile-aarch64 :: instrprof-gc-sections.c
libFuzzer :: gc-sections.test
libFuzzer :: gc-sections.test
libFuzzer :: gc-sections.test 

Attaching log here:
[rc2-new-failures.txt](https://github.com/llvm/llvm-project/files/7864550/rc2-new-failures.txt)

On a very superficial investigation it seems the linker is not removing some unused functions.

**Comment by tstellar** [comment]
@MaskRay Is this related to 9d9efb1 ?

**Comment by MaskRay** [comment]
> @MaskRay Is this related to [9d9efb1](https://github.com/llvm/llvm-project/commit/9d9efb1f67ff70e996b1cb7fa00e24b9121be226) ?

Yes. So people know that I object to default (`-z nostart-stop-gc`) in release/13.x: https://llvm.discourse.group/t/lld-default-nostart-stop-gc-default-on-release-13-x-and-main/5369

(In Debian Code Search, there may be like 20+ packages using the feature. After deduplication, they may be fewer. Wow, some people argue that it is supported linker interface while in practice it wasn't. And I've spent so much time on it....)

**Comment by rovka** [comment]
For the record, this is also affecting armv7.
I'm not sure if this is a blocker, since it seems to be a known issue. Is there something I can/should do on my side before shipping the release binaries?

**Comment by tstellar** [comment]
@rovka Can you re-test the release/13.x branch?  I've reverted the commit that I think caused this.

**Comment by rovka** [comment]
@tstellar That works, thanks!
