### ISSUE TITLE
[inline asm] Intel syntax: errors when combining an array variable and a register in an address expression

### ISSUE THREAD

**Issue by Tomsod** [llvm/llvm-project#53197]
OS: Linux (but I was cross-compiling for win32 when I first noticed this)
Clang & LLVM version: reproducible on 13.0.0, but was a problem before

Consider this C code (compile with -fasm-blocks):
```
static int test[3] = { 1, 2, 3 };

int __attribute__((naked)) main(void)
{
    asm
      {
        mov eax, 4
        inc dword ptr [test+eax]
        mov eax, [test+eax]
        ret
      }
}
```
The second assembly command fails compiling because of "ambiguous operand size" (despite the `dword`).  Removing it will instead cause an error during linking (because of the third command).  But replacing the addresses with a constant `[test+4]` will produce a correct code.

**Comment by Endilll** [comment]
Appears to be fixed in Clang 14: https://godbolt.org/z/oY31Yznfc

**Comment by Tomsod** [comment]
The linker error was still present in v14, but as of 16.0.6 it's fixed as well.  Great!
