### ISSUE TITLE
clang-format: breaking before closing parentheses of parameter and argument lists

### ISSUE THREAD

**Issue by bertie-wheen** [llvm/llvm-project#53192]
It would be nice if I could break parentheses like braces.

For example:

```c++
function_1(
  argument_1,
  function_2(
    argument_2,
    argument_3
  ),
  argument_4
);
```

Rather than:

```c++
function_1(
  argument_1,
  function_2(
    argument_2,
    argument_3),
  argument_4);
```

**Comment by jeslaspravin** [comment]
Does this answer your issue?
**https://stackoverflow.com/a/53935614/18816213**

**Comment by bertie-wheen** [comment]
> Does this answer your issue? **https://stackoverflow.com/a/53935614/18816213**

I haven't tried it, but it looks like it does! Cheers for the heads up :)

**Comment by Zingam** [comment]
https://reviews.llvm.org/D109557

 AlignAfterOpenBracket: BlockIndent
