### ISSUE TITLE
Assertion failures in clang direct people to Bugzilla instead of GitHub

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#53215]
"PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script." should be changed to https://github.com/llvm/llvm-project/issues/

**Comment by fhahn** [comment]
Should be changed to reference GitHub in bbce75e352be0637305a1b59ac5eca7175bceece
