### ISSUE TITLE
libcxx freestanding mode???

### ISSUE THREAD

**Issue by tearosccebe** [llvm/llvm-project#53222]
https://en.cppreference.com/w/cpp/freestanding

ISO C++ requires to provide headers for freestanding mode, but I do not see where libcxx supports this while GCC's libstdc++ does support it with --disable-hosted-libstdcxx.

**Comment by philnik777** [comment]
There isn't a `-ffreestanding` ore something like that AFAIK, but you can disable things you can't use. You can disable threads, debug mode, filesystem, random device, locale, unicode, wide chars and exceptions. I think everything else shouldn't need a hosted environment. If there is anything I'm sure we can provide a config option.

**Comment by tearosccebe** [comment]
> There isn't a `-ffreestanding` ore something like that AFAIK, but you can disable things you can't use. You can disable threads, debug mode, filesystem, random device, locale, unicode, wide chars and exceptions. I think everything else shouldn't need a hosted environment. If there is anything I'm sure we can provide a config option.

I am talking about environments where you do not even have a libc at all. Only freestanding headers should be provided.

**Comment by tearosccebe** [comment]
> What would you want to use without at least some part of libc? Pretty much everything depends at least on `stddef.h` or something like that.

stddef.h is C's freestanding. You can assume they exist.

**Comment by philnik777** [comment]
Then what is the problem? Are we depending somewhere on hosted libc? I don't think so, since many people use libc++ in a non-hosted environment, and the implementation is free to provide more headers than the required ones in a freestanding environment.

**Comment by tearosccebe** [comment]
yes. Rely on newlib is already a huge issue.

**Comment by tearosccebe** [comment]
libstdc++ provides that. libc++ should absolutely provide the same standard-compliant feature. People like you are exactly why C++ is terrible for writing operating kernel.

**Comment by philnik777** [comment]
> yes. Rely on newlib is already a huge issue.

You mean we require `operator new` for some things to work? If yes, you are free to not use these parts or provide your own `operator new`. http://eel.is/c++draft/compliance#2 clearly states that an implementation may provide any headers that are part of the hosted environment, but _must_ provide at least the ones in the table. I don't know where you got that providing `std::move` or `std::forward` isn't allowed. These are just casts. There is literally no need for anything other than the C++ type system.

**Comment by tearosccebe** [comment]
> > yes. Rely on newlib is already a huge issue.
> 
> You mean we require `operator new` for some things to work? If yes, you are free to not use these parts or provide your own `operator new`. http://eel.is/c++draft/compliance#2 clearly states that an implementation may provide any headers that are part of the hosted environment, but _must_ provide at least the ones in the table. I don't know where you got that providing `std::move` or `std::forward` isn't allowed. These are just casts. There is literally no need for anything other than the C++ type system.

But it is not guaranteed to be there. This means you use them you got huge portability issues since utility and memory headers are not there. Yes my freestanding GCC do not provide them example.

https://github.com/tearosccebe/fast_io/blob/master/include/fast_io_core_impl/freestanding/addressof.h

This is why a portable library MUST write std::addressof, std::move by yourself.
https://www.youtube.com/watch?v=DorYSHu4Sjk

The problem is that C++ is poorly designed for freestanding at all.

Providing operator new/delete is not guaranteed to work either. Since many environments might not provide heap. 

What's worse is that some environments like windows kernel do provide heap, but they have multiple heaps. One for interrupt safe, one is not interrupt-safe. Making any of them default is not right.

Also C++ operator new/delete relies on exceptions which are another huge issue.

**Comment by tearosccebe** [comment]
In fact, you do even have std::array because .at() method report logic_error.

Please, follow the standard, provide a mode where only freestanding C++ headers are provided as libstdc++ does.

**Comment by philnik777** [comment]
> Custom allocators are not going to work either. C++ allocators are poorly designed.

Write a paper.

> There are a lot of problems with using things like std::vector. They will report things like logic_error, which will randomly bloat binary size.

As I said, libc++ supports `-fno-exceptions`

> build libcxx with no-exceptions support they will return nullptr, causing undefined behaviors which is not standard compliant either.

Pick one. Use exceptions and have the bloat or be not strictly standards compliant.

> It is quite funny you think people would use std::vector in the kernel.

Where did I say people would use it? I simply said that it would be _possible_.

> Quite funny you talk about std::vector when std::addressof is not provided.

We only support clang and GCC and both provide `__builtin_addressof`, so we can define our own.

> Please, follow the standard, provide a mode where only freestanding C++ headers are provided as libstdc++ does.

We _are_ standards compliant in that regard. We are providing everything that is required and things that are allowed to be provided. We aren't doing anything that isn't standards compliant in that regard.

By the way, why would you be interested in portable code in a freestanding environment? You are controlling literally everything in this environment.

**Comment by tearosccebe** [comment]
> By the way, why would you be interested in portable code in a freestanding environment? You are controlling literally everything in this environment.

but it still requires a libc which might be problematic.

**Comment by philnik777** [comment]
> but it still requires a libc which might be problematic. You got into chicken egg problem when you use C++ to write libc itself which means C++ as a language is not self-host.

I'm not entirely sure, but I think you can write `cstddef` without including `stddef.h`. So this might be only an implementation "problem".

> __builtin_addressof, yes, but std::addressof is not there.

`std::addressof` is provided by the C++ standard library. libc++ _is_ the standard library, so libc++ provides it.

**Comment by tearosccebe** [comment]
> > but it still requires a libc which might be problematic. You got into chicken egg problem when you use C++ to write libc itself which means C++ as a language is not self-host.
> 
> I'm not entirely sure, but I think you can write `cstddef` without including `stddef.h`. So this might be only an implementation "problem".

That is why the job leaves to the compiler, not the user.
> 
> > __builtin_addressof, yes, but std::addressof is not there.
> 
> `std::addressof` is provided by the C++ standard library. libc++ _is_ the standard library, so libc++ provides it.

No. std::addressof in NOT provided by the freestanding C++ library. If you use it, it is not portable in freestanding.  It is so hard for you to understand?

**Comment by tearosccebe** [comment]
std::addressof is in the <memory> header which is not freestanding. This is exactly why a portable library or code should ALWAYS use __builtin_addressof instead of std::addressof (of course you still get into trouble in theory since __builtin_addressof is not guaranteed to be there either).

**Comment by philnik777** [comment]
> No. std::addressof in NOT provided by the freestanding C++ library. If you use it, it is not portable in freestanding. It is so hard for you to understand?

I understand that it isn't portable, but libc++ doesn't _try_ to be portable in a freestanding environment. It is completely OK if libc++ provides it. Nothing in the standard is saying libc++ isn't allowed to.

**Comment by tearosccebe** [comment]
> > No. std::addressof in NOT provided by the freestanding C++ library. If you use it, it is not portable in freestanding. It is so hard for you to understand?
> 
> I understand that it isn't portable, but libc++ doesn't _try_ to be portable in a freestanding environment. It is completely OK if libc++ provides it. Nothing in the standard is saying libc++ isn't allowed to.

So you are basically saying libc++ is not designed to be freestanding usable. You are not allowed to use libc++ to write operating system kernel right?

**Comment by tearosccebe** [comment]
[stdio.h.txt](https://github.com/llvm/llvm-project/files/8101168/stdio.h.txt)

I give you an example why hosted C++ is extremely problematic for a lot of workflows. Like this stdio.h in pdp11, completely unusable in C++. That is why you need freestanding C++ to prevent those headers to be included in any form.

**Comment by philnik777** [comment]
> So you are basically saying libc++ is not designed to be freestanding usable. You are not allowed to use libc++ to write operating system kernel right?

Where did you get that from? _Nothing_ is preventing you from not using the parts you don't want to use. It's as easy as _not using_ them.

> It is equal to not to when you write portable code. Is it that hard for you to understand?

Did you not get the message where I said "libc++ doesn't _try_ to be portable"? Wait, you did. You responded to that message.

> What you are saying is basically standard is toilet paper, you can provide whatever extensions you want.

No. IIUC you are not allowed to add headers which are not part of C++. But the standard clearly says that an implementation can provide more than what's required.

**Comment by tearosccebe** [comment]
> Where did you get that from? _Nothing_ is preventing you from not using the parts you don't want to use. It's as easy as _not using_ them.
> 
> >

You are forcing me to use a libc which is not provided. That is the part i do not want to use.

**Comment by philnik777** [comment]
> You are forcing me to use a libc which is not provided. That is the part i do not want to use.

There are conforming libc implementations for all platforms we support AFAIK.

**Comment by tearosccebe** [comment]
> > You are forcing me to use a libc which is not provided. That is the part i do not want to use.
> 
> There are conforming libc implementations for all platforms we support AFAIK.

There are a lot of platforms where you do not have working implementations. You are saying i am not allowed to build libc++ with pdp11. Yeah. That is what you are trying to say.

**Comment by philnik777** [comment]
> So you are saying [for] libc++ [you] must provide a WORKING libc to build. How could that be portable in any form?

It isn't.

> There are a lot of platforms where you do not have working implementations. You are saying i am not allowed to build libc++ with pdp11. Yeah. That is what you are trying to say.

You are allowed to try, but we don't support it.

**Comment by tearosccebe** [comment]
I am not allowed to use cstddef in pdp11 because pdp11 does not provide a working one.

**Comment by tearosccebe** [comment]
> > So you are saying [for] libc++ [you] must provide a WORKING libc to build. How could that be portable in any form?
> 
> It isn't.
> 
> > There are a lot of platforms where you do not have working implementations. You are saying i am not allowed to build libc++ with pdp11. Yeah. That is what you are trying to say.
> 
> You are allowed to try, but we don't support it.

LOL. So all operating systems and embeded systems people use you do not support yeah.

I write an operating system and i am not allowed to use cstddef with clang. That is what you are suggesting.

**Comment by tearosccebe** [comment]
I am not allowed to use clang to write operating system. You are saying that yeah.

**Comment by philnik777** [comment]
libc++ and clang are not the same thing. libc++ is a standard library implementation, clang is a compiler. There are libc implementations for x86, amd64, arm, aarch64, powerpc and powerpc64. We don't support other platforms (I think).
Closing this as not an issue.

**Comment by tearosccebe** [comment]
> libc++ and clang are not the same thing. libc++ is a standard library implementation, clang is a compiler. There are libc implementations for x86, amd64, arm, aarch64, powerpc and powerpc64. We don't support other platforms (I think). Closing this as not an issue.

This is a fucking issue.

**Comment by tearosccebe** [comment]
https://github.com/managarm/cxxshim

You think it is fun for people to write this? Why? Because you are the problem.

Sure libc++ is not the same thing as clang. you are saying i am not allowed to use libc++ to write kernel with clang. Okay. What is the alternative implementation?

**Comment by tearosccebe** [comment]
> > Where is the alternative implementation?
> 
> Write one.

Write one LOL. Why should I do compiler's work? The freestanding C++ is super compiler dependant.
