### ISSUE TITLE
clang-format: `SeparateDefinitionBlocks` wrongly changed multiline comments indentation

### ISSUE THREAD

**Issue by akien-mga** [llvm/llvm-project#53227]
Follow-up to #45895 and #52976, CC @ksyx.

The new `SeparateDefinitionBlocks: Always` clang-format option (as of nightly build `clang-format-14_14~++20220114111422+ed30a968b5d6-1_exp1_20220114111520.246_amd64`) seems to wrongly change the indentation of some multiline comments, as seen in https://github.com/akien-mga/godot/commit/c814da35e9eec8b8cb017b4b85fcb3ce318c0172 on a few occurrences (search for the 15 deletions):

```diff
diff --git a/platform/android/java/lib/src/org/godotengine/godot/Godot.java b/platform/android/java/lib/src/org/godotengine/godot/Godot.java
index 3fbbd8fbcc..d1e8a1d826 100644
--- a/platform/android/java/lib/src/org/godotengine/godot/Godot.java
+++ b/platform/android/java/lib/src/org/godotengine/godot/Godot.java
@@ -808,18 +808,18 @@ public class Godot extends Fragment implements SensorEventListener, IDownloaderC
 	}
 
 	/*
-	@Override public boolean dispatchKeyEvent(KeyEvent event) {
-		if (event.getKeyCode()==KeyEvent.KEYCODE_BACK) {
-			System.out.printf("** BACK REQUEST!\n");
+		@Override public boolean dispatchKeyEvent(KeyEvent event) {
+			if (event.getKeyCode()==KeyEvent.KEYCODE_BACK) {
+				System.out.printf("** BACK REQUEST!\n");
 
-			GodotLib.quit();
-			return true;
-		}
-		System.out.printf("** OTHER KEY!\n");
+				GodotLib.quit();
+				return true;
+			}
+			System.out.printf("** OTHER KEY!\n");
 
-		return false;
-	}
-	*/
+			return false;
+		}
+		*/
 
 	public void onBackPressed() {
 		boolean shouldQuit = true;
```

```diff
diff --git a/scene/gui/control.h b/scene/gui/control.h
index bf79f790e7..0dad2ab50f 100644
--- a/scene/gui/control.h
+++ b/scene/gui/control.h
@@ -318,7 +318,7 @@ public:
 
 	};
 
-	/* EDITOR */
+/* EDITOR */
 #ifdef TOOLS_ENABLED
 	virtual Dictionary _edit_get_state() const override;
 	virtual void _edit_set_state(const Dictionary &p_state) override;
```

```diff
diff --git a/servers/physics_2d/godot_shape_2d.cpp b/servers/physics_2d/godot_shape_2d.cpp
index 1e8799a727..ba55733204 100644
--- a/servers/physics_2d/godot_shape_2d.cpp
+++ b/servers/physics_2d/godot_shape_2d.cpp
@@ -926,9 +926,9 @@ void GodotConcavePolygonShape2D::cull(const Rect2 &p_local_aabb, QueryCallback p
 	};
 
 	/*
-	for(int i=0;i<bvh_depth;i++)
-		stack[i]=0;
-	*/
+		for(int i=0;i<bvh_depth;i++)
+			stack[i]=0;
+		*/
 
 	if (segments.size() == 0 || points.size() == 0 || bvh.size() == 0) {
 		return;
```

### Minimal reproduction project

From a quick test I didn't see right away how to reproduce these quirks in a simple project, so this zip instead includes three files from https://github.com/godotengine/godot where `SeparateDefinitionBlocks: Always` exhibits this issue (with a Git repository initialized so it's easy to check the `git diff` after running `clang-format`).

[clang-format-SeparateDefinitionBlocks-multiline-comments.zip](https://github.com/llvm/llvm-project/files/7876942/clang-format-SeparateDefinitionBlocks-multiline-comments.zip)

**Comment by ksyx** [comment]
Thanks for the feedback! I resolved this first as it has relatively large negative impact on formatting. The revision is here https://reviews.llvm.org/D117520 and please see if this solves the problem and are there anything to improve.

**Comment by ksyx** [comment]
Hi, the patch for this has recently been merged and please see if this matches your need or any other issues comes out. Thanks for your feedback again.
