### ISSUE TITLE
clang-format: `SeparateDefinitionBlocks` wrongly adding line in Objective-C++

### ISSUE THREAD

**Issue by akien-mga** [llvm/llvm-project#53229]
Follow-up to #45895 and #52976, CC @ksyx.

Using `SeparateDefinitionBlocks: Always` (as of nightly build clang-format-14_14~++20220114111422+ed30a968b5d6-1_exp1_20220114111520.246_amd64) on https://github.com/godotengine/godot:

```diff
diff --git a/platform/osx/display_server_osx.mm b/platform/osx/display_server_osx.mm
index 27d302a984..5d3277bbea 100644
--- a/platform/osx/display_server_osx.mm
+++ b/platform/osx/display_server_osx.mm
@@ -93,6 +93,7 @@ static void _push_to_key_event_buffer(const DisplayServerOSX::KeyEvent &p_event)
 static NSCursor *_cursorFromSelector(SEL selector, SEL fallback = nil) {
 	if ([NSCursor respondsToSelector:selector]) {
 		id object = [NSCursor performSelector:selector];
+
 		if ([object isKindOfClass:[NSCursor class]]) {
 			return object;
 		}
@@ -544,6 +545,7 @@ static const NSRange kEmptyRange = { NSNotFound, 0 };
 	NSEvent *event = [NSApp currentEvent];
 
 	NSString *characters;
+
 	if ([aString isKindOfClass:[NSAttributedString class]]) {
 		characters = [aString string];
 	} else {
```

I don't know much about Objective-C++ but this looks like a wrong change from `SeparateDefinitionBlocks`, those are not definition blocks but method calls IINM.

**Comment by ksyx** [comment]
Thanks for the feedback and its fix is at https://reviews.llvm.org/D119067. Please check if any change needed :)

**Comment by ksyx** [comment]
Hi, the fix for this is landed and please see if any further improvements required.
