### ISSUE TITLE
SPEC17/parest will not build with increased inliner threshold

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#53236]
dof_tools.bc (clang input):
[dof_tools.tar.gz](https://github.com/llvm/llvm-project/files/7878060/dof_tools.tar.gz)

Experimental patch to adjust inliner threshold multiplier via CL:
[InlinePatch.tar.gz](https://github.com/llvm/llvm-project/files/7878062/InlinePatch.tar.gz)

Experimentally increasing the inliner threshold on a benchmark inlines a function entirely whithin one file while still called from another causes linker to fail with 'undefined reference'.

I tried to do a bisect, but it seems this has been failing all the way back to at least 2017 (f78b75f), so I instead started to isolate the problem.

I have applied an experimental patch to be able to adjust the InliningThresholdMultiplier (attached). On SystemZ this is by default '3'. I found that parest compiles fine up to '5', but not with '6'. I could then actually compile all files with '6', and just one with '5', and successfully link.

The one file that was troublesome is dof_tools.cc. With the patch applied (all other files with '6'):

clang++ -c -o source/dofs/dof_tools.o  -O3 -march=z14 -w ./dof_tools.bc -mllvm -inline-thresh-mult=5
[link success]

clang++ -c -o source/dofs/dof_tools.o  -O3 -march=z14 -w ./dof_tools.bc -mllvm -inline-thresh-mult=6
[link FAILURE]

The function in question seems to be 'dof_couplings_from_component_couplings'. It is removed from dof_tools.s with '6', but this doesn't work as it is called from mg_dof_tools.s as well.

I find it suspicious that the function is not '.global' but '.weak' when still emitted in dof_tools.s. Looking at the Clang FE output (.bc file), dof_couplings_from_component_couplings is marked as 'dso_local', but not 'internal'.

**Comment by fhahn** [comment]
> [link FAILURE]

What's the link failure?

**Comment by fhahn** [comment]
> > [link FAILURE]
> 
> What's the link failure?

ok looks like `undefined reference`, never mind

**Comment by nikic** [comment]
How is this function declared in source code?

In the bitcode file the function is linkonce_odr, so it's legal to drop it from the translation unit if it is unused. The expectation is that linkonce_odr functions are emitted into each TU that uses them. This might be a result of incorrect qualifiers in the C code.

**Comment by JonPsson** [comment]
> ok looks like undefined reference, never mind

yeah...

> How is this function declared in source code?

The function dof_couplings_from_component_couplings is a public static member function of the class DoFTools, declared in dof_tools.h:

class DoFTools
{
  public:
...
    template <int dim, int spacedim>
    static
    Table<2,Coupling>
    dof_couplings_from_component_couplings (const FiniteElement<dim,spacedim> &fe,
                                            const Table<2,Coupling> &component_couplings);
...
};

It is defined in dof_tools.cc, and as well used there by another static member function make_flux_sparsity_pattern().

In the other file it is used - mg_dof_tools.cc - it is called from static two different members of MGTools (without object).

The function has template parameters: In dof_tools.cc they are <const FiniteElement<DH::dimension>, const Table<2,Coupling> >, while in mg_dof_tools.cc the dim parameter is also a template parameter of the caller. Not sure if this could lead to any problems maybe...?

**Comment by nikic** [comment]
@JonPsson If you only declare the template in the header, then it is necessary to perform an explicit template instantiation for any combination of template arguments that are used by other translation units. See https://cpp.godbolt.org/z/6r49zWKaf for how the explicit template instantiation switches linkage from linkonce_odr to weak_odr.

Does dof_tools.cc contain the necessary template instantiations?

**Comment by JonPsson** [comment]
> @JonPsson If you only declare the template in the header, then it is necessary to perform an explicit template instantiation for any combination of template arguments that are used by other translation units. See https://cpp.godbolt.org/z/6r49zWKaf for how the explicit template instantiation switches linkage from linkonce_odr to weak_odr.
> 
> Does dof_tools.cc contain the necessary template instantiations?

No - not that I can see... Should they all then be placed in dof_tools.cc (including the ones used by the other file)?

**Comment by nikic** [comment]
> > @JonPsson If you only declare the template in the header, then it is necessary to perform an explicit template instantiation for any combination of template arguments that are used by other translation units. See https://cpp.godbolt.org/z/6r49zWKaf for how the explicit template instantiation switches linkage from linkonce_odr to weak_odr.
> > Does dof_tools.cc contain the necessary template instantiations?
> 
> No - not that I can see... Should they all then be placed in dof_tools.cc (including the ones used by the other file)?

Yeah. Either that, or move the function definition into the header.

**Comment by JonPsson** [comment]
Ahh - I moved the definition into the header, and it now links also with the increased inlining :-)

I am however not sure exactly what it means that the compiler output now has a lot more total instructions in the output - with the same options otherwise. Is this expected and acceptable?

Would it be the same if I provided the explicit template instantiations?

**Comment by nikic** [comment]
> Ahh - I moved the definition into the header, and it now links also with the increased inlining :-)
> 
> I am however not sure exactly what it means that the compiler output now has a lot more total instructions in the output - with the same options otherwise. Is this expected and acceptable?

That is, the number of instructions increases if you move it into the header, while keeping inlining threshold the same?

Yes, that can happen, because you have now made the function available for inlining in both dof_tools.cc and any other files using this function. It will be emitted into all translation units. If it ends up not being inlined, the linker will only keep one copy. But if they get inlined, the instruction count may increase accordingly.

> Would it be the same if I provided the explicit template instantiations?

In that case only dof_tools.cc would have the function definition, and it could only be inlined there.

Explicit template instantiations are generally used specifically to avoid instantiating big templates many times and thus reduce compile-time and/or code size.

**Comment by JonPsson** [comment]
> That is, the number of instructions increases if you move it into the header, while keeping inlining threshold the same?

Yes - that's what I meant but I now think I may have gotten something wrong with the numbers so I am not sure...

Anyhow, I now managed to provide just the one missing template instantiation with:

```
--- dofs/dof_tools.cc
+++ dofs/dof_tools.cc

 @@ -752,7 +752,10 @@ DoFTools::dof_couplings_from_component_couplings
   return dof_couplings;
 }
 
-
+template Table<2,DoFTools::Coupling>
+DoFTools::dof_couplings_from_component_couplings<3, 3>(
+     const FiniteElement<3,3> &fe,
+     const Table<2, DoFTools::Coupling> &component_couplings);
 
 // TODO: look whether one can employ collective add operations in sparsity
```
This builds identically compared to before, and also builds with a higher multiplier ('6') :-)

Thanks for the help!
