### ISSUE TITLE
Demand for copy constructor definition when mandatory copy elision must take place

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#53245]
In next code copy constructor shall not be called and checked because of mandatory copy elision:
```
struct A {       
    consteval A() {}
    consteval A(const A&);
    consteval void f() {}
};

int main() {
    A{A{}}.f();
}
```
GCC and MSVC accept the code. But Clang does not:
```
undefined constructor 'A' cannot be used in a constant expression
```
Demo: https://gcc.godbolt.org/z/cKboT3qf6

**Comment by Izaron** [comment]
Proposed fix at https://reviews.llvm.org/D119095

**Comment by usx95** [comment]
This is actually the same crash as of #53244.
Duplicate of #53244
