### ISSUE TITLE
[clang-format] Inconsistent formatting with rvalue references and functions

### ISSUE THREAD

**Issue by AMS21** [llvm/llvm-project#53249]
Example code before formatting:

```cpp
using f1 = void (&)();
using f2 = void (&&)();
```

Code after running `clang-format -style=LLVM test.cpp > test-f.cpp`:

```cpp
using f1 = void (&)();
using f2 = void(&&)();
```

clang-format version: `clang-format version 13.0.0`

**Comment by mkurdej** [comment]
This has been fixed in main branch in commit c94667a810e44c44fd355f9f014ffe161d75d761.
