### ISSUE TITLE
Insufficient permissions to edit post containing multiple links

### ISSUE THREAD

**Issue by asb** [llvm/llvm-project#53257]
I've [posted](https://llvm.discourse.group/t/llvm-weekly-420-january-17th-2022/5757) today's issue of LLVM Weekly to discourse (thanks for creating the LLVM Weekly subcategory). This was initially held in moderation and is now approved. I've gone to edit it to fix the formatting (sadly discourse's markdown implementation doesn't like the fact it's wrapped at 80 characters), but upon attempting to save the edit I get "Sorry, new users can only put 2 links in a post."

There's perhaps two issues here:
* If this is intentional, can I perhaps get [my account](https://llvm.discourse.group/u/asb/summary) bumped up to allow me to at least edit these posts
* Is there some kind of misconfiguration or discourse bug? Being able to make a post but not then edit it seems like surprising behaviour.

**Comment by asl** [comment]
Hi Alex,

This is default Discourse behaviour wrt "trust levels": https://blog.discourse.org/2018/06/understanding-discourse-trust-levels/ I bumped your account – enjoy :)
