### ISSUE TITLE
Missing vectorization with stride

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#53262]
```
void pred8x8l_vertical_add_c(unsigned char *pix, const short *block,
                             int stride) {
    int i;
    for (i = 0; i < 8; i++) {
        int j;
        for (j = 0; j < 8; j++) {
            pix[j] = pix[j - stride] + block[j];
        }
        pix += stride;
        block += 8;
    }
}
```

ICC can vectorize this code, LLVM cannot.

https://godbolt.org/z/Wqc57vh6z

**Comment by davidbolvansky** [comment]
cc @fhahn

**Comment by caojoshua** [comment]
Looks intended:

```
LV: Found trip count: 8
LV: Not allowing scalar epilogue due to low trip count.
```

We can vectorize if I change the inner loop upper bound to 16: https://godbolt.org/z/Pzo3Mn4v1.

The default minimum trips is 16 [[source](https://github.com/llvm/llvm-project/blob/ccc13241208f3b6975bbef384f0a01b1b6e83e8e/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp#L193-L197)].
