### ISSUE TITLE
llvm-c: LLVMBuildGlobalString crashing

### ISSUE THREAD

**Issue by ssmid** [llvm/llvm-project#53263]
I'm new to LLVM, so forgive me if this turns out to be a non-issue (deprecated feature, I'm doing something wrong or whatever). It looks like LLVMBuildGlobalString() is broken since 10.0.0. I think it calls llvm::IRBuilderBase::CreateGlobalString() with insufficient arguments.

https://github.com/llvm/llvm-project/blob/202d590a017b76926c9e327927d9c144bc8f5cfb/llvm/lib/IR/Core.cpp#L3742
https://github.com/llvm/llvm-project/blob/f9f865d86c822db6078a3f219d328249406635e1/llvm/lib/IR/IRBuilder.cpp#L43

LLVM version: 10.0.0, 12.0.0 (Ubuntu repositories)

CLion says:
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

Reproducer:

```c
void hello_world() {
    LLVMModuleRef module = LLVMModuleCreateWithName("hello_world");
    //LLVMSetDataLayout(module, "");
    LLVMSetTarget(module, LLVMGetDefaultTargetTriple());
    LLVMBuilderRef builder = LLVMCreateBuilder();

    LLVMValueRef string_hello = LLVMBuildGlobalString(builder, "Hello, world!\n", "s");  // crashing here
    ...
}
```

**Comment by nikic** [comment]
The C API requires the builder to have an insertion point, see https://github.com/llvm/llvm-project/blob/f9f865d86c822db6078a3f219d328249406635e1/llvm/lib/IR/IRBuilder.cpp#L49. You did not specify one.

One could expose a new C API function that accepts an explicit Module.

**Comment by ssmid** [comment]
I'm calling `LLVMPositionBuilderAtEnd(builder, entry)` later. I've put the `LLVMBuildGlobalString()` call beneath now and it seems to work (even though it's crashing in a different place now). Maybe I misunderstood the function's job. It's probably meant for declaring string literals from inside functions? Anyway, thanks for you help!
