### ISSUE TITLE
[lld] Reduce binary size

### ISSUE THREAD

**Issue by keith** [llvm/llvm-project#53275]
I'm currently distributing ld64.lld as a pre-compiled binary for our team. In the future when development slows down maybe it won't be necessary and we can use one that ships with the LLVM release or Xcode, but for the foreseeable future this seems like a reasonable thing to do.

Currently with a macOS arm64 only release binary, lld is ~100mbs. Stripping the binary with `strip -SXTx bin/lld` reduces it to ~75mbs. This is clearly a large download. For reference ld64 is ~2mbs, ld.gold is ~2mbs, and mold is ~8mbs. None of these are great comparisons, but still shows an order of magnitude difference.

I'm curious if anyone else has ever taken a look at any low hanging fruit for binary size, or if I should look into this a bit (or if I shouldn't!).

**Comment by sbc100** [comment]
I would imagine that the vast majority of that code size comes from libLLVM, which is used by lld to perform LTO.   I assume you are building statically which mean that large parts libLLVM and other llvm core libraries will end up getting linked into lld. 

The version of lld that we builds part of the emscripten SDK comes it at ~6Mb, but with ` -DLLVM_LINK_LLVM_DYLIB=ON` and `-DLLVM_BUILD_LLVM_DYLIB=ON`.

**Comment by keith** [comment]
In that case in order to distribute it you'd still have to distribute the things that were built as dylibs though right? So I think that would just punt the issue a bit?

**Comment by MaskRay** [comment]
https://maskray.me/blog/2021-12-19-why-isnt-ld.lld-faster#new-hope I have made lld 400KiB smaller since 13.0.1. Most size contribution is from linking LLVM LTO. If you remove it, an disabling other binary formats, you can get something like ~3MiB (https://github.com/MaskRay/picolld). But disabling LTO is probably not many users want.

Because of LTO, most libraries linked into clang will be linked into lld. This is the usual size bloat problem. It is just non-stoppable.
Recently there was a post `On Proebsting's Law`.
I agree with the comment `This “law” was never really reasonable or sensible.` on https://news.ycombinator.com/item?id=29855611 but I also understand how some people are getting at.
There is also the sociology problem that it is difficult for llvm-project to reject a thing or remove obsoleted things.
So executables will just get larger and larger.

**Comment by sbc100** [comment]
> In that case in order to distribute it you'd still have to distribute the things that were built as dylibs though right? So I think that would just punt the issue a bit?

I agree that we are punting on the issue by saying that its because of LLVM itself being included for LTO that the size of the required distribution is large.. but aside from removing LTO from lld, then this bug sounds like its amounts to a request for a reduction in size the llvm compiler itself.. which is much larger than an lld bug.

**Comment by alexander-shaposhnikov** [comment]
The size depends on which backends are included, e.g. one can pass -DLLVM_TARGETS_TO_BUILD='ARM;X86' 
-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD='AArch64' to cmake to avoid building other targets.
If I am not mistaken (I've done some quick measurements on MacOS) for the default configuration (all the available targets are enabled) the size of LLD is approximately ~104MB, if one specify DLLVM_TARGETS_TO_BUILD='ARM;X86' 
-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD='AArch64'  the size drops to 59M. Furthermore, if you strip it with strip -SXTx the size drops to 53M.

**Comment by psiha** [comment]
Why are dynamic/DLL/dylib builds of LLVM not the default?
The current default produces huge distributions (which then for example get 'passed on' with the Android NDK, MS VS LLVM integration, ...)

**Comment by psiha** [comment]
Is there a policy @ LLVM that a https://github.com/google/bloaty -like pass/analysis is done every once in a while?

**Comment by smithp35** [comment]
The Build Shared Libraries is suggested for developers only in the LLVM Build System https://llvm.org/docs/CMake.html#llvm-related-variables . I think one of the major reasons for this is that Windows DLLs have a relatively low maximum symbol table size and keeping LLVM under this limit can be challenging. There is also a case that for the other LLVM tools the statically linked executables have faster startup times than those using shared libraries. This is less of an issue for LLD as this is invoked a lot less than the compiler for example.

There's no policy on tracking executable size that I know of. Runtime performance is usually a higher concern.

As LTO is accessed from only a small part of LLD, I think it could be possible to exclude it entirely as a build option. However:
- this wouldn't be the default for the release as too many people use LTO.
- Someone would have to implement it.
- Someone would need to maintain a build bot to stop it breaking.
- Maintainers would need to agree to it.

I don't think that is high on anyones to-do list though.

**Comment by rnk** [comment]
The documentation is correct: distributors should not use `-DBUILD_SHARED_LIBS=ON`. Instead, they should use `-DLLVM_BUILD_LLVM_DYLIB=ON`, which was mentioned earlier. If you build clang and LLD this way, LLVM will be built as a library and it will be shared between them, resulting in size savings.

It's also worth noting that LLD has a hard dependency on LLVM support libraries, so it's not possible to factor LLVM out of LLD as an optional plugin without more rearchitecture.

Beyond what @maskray has already done to reduce code size, I don't think there is anything else to do here besides focusing on making `-DLLVM_BUILD_LLVM_DYLIB=ON` builds better. Previously, @compnerd proposed adding explicit visibility attributes to our LLVM headers, which would help us move to `-fvisibility=hidden`. In any case, I think we should close this and distributors can feel free to file new issues about improving LLVM's general distribution-friendliness, which, admittedly, needs work.
