### ISSUE TITLE
[lld-macho] lld eagerly loads duplicate objects in archives

### ISSUE THREAD

**Issue by keith** [llvm/llvm-project#53280]
Someone testing lld reported this issue to me, that's a bit weird, but isn't an issue with ld64, so I wanted to file for visibility.

If you have an archive file with duplicate object files in it, for example created with `ar rcs libFoo.a foo.o foo.o` (libtool warns when doing this, `ar` does not), lld fails with a duplicate symbol error, where ld64 ignores it. It appears that ld64 dedups based on the basename in the archive. Specifically this test fails with lld but not ld64:

```s
# REQUIRES: x86
# RUN: rm -rf %t; split-file %s %t
# RUN: llvm-mc -filetype=obj -triple=x86_64-apple-darwin %t/obj.s -o %t/obj.o
# RUN: llvm-mc -filetype=obj -triple=x86_64-apple-darwin %t/main.s -o %t/main.o
# RUN: llvm-ar rcs %t/test.a %t/obj.o %t/obj.o
# RUN: %lld %t/main.o %t/test.a -o %t/main -ObjC

# RUN: llvm-nm %t/main | FileCheck %s
# CHECK: T _OBJC_CLASS_$_MyObject
# CHECK: T _main

#--- obj.s
.globl _OBJC_CLASS_$_MyObject
_OBJC_CLASS_$_MyObject:

#--- main.s
.globl _main
_main:
  ret
```

If you add `-all_load` to the invocation ld64 also fails.

Realistically I'm not sure if we should change the behavior here, it seems like this could lead to scary issues where differences between object files are somehow ignored (although I haven't looked into ld64 to see if it does anything smart for that), but I'm curious what others think?

**Comment by oontvoo** [comment]
I think this WAI :) We've already noted this in the ld64-vs-lld.rst doc.
FWIW, I believe this might be a bug in LD64 that it doesn't report the duplicate symbols. (Looking at the code, it kept a hashmap of the symbols' name -> archives, so naturally symbols would get de-dupped)

**Comment by keith** [comment]
I should have looked there first, sorry about that! For future readers the relevant section is:

>There are differences in how LLD and LD64 handle ObjC symbols loaded from archives.
>- LD64:
>   * Duplicate ObjC symbols from the same archives will not raise an error. LD64 will pick the first one.
>   * Duplicate ObjC symbols from different archives will raise a "duplicate symbol" error.
>- LLD:
>   * Duplicate symbols, regardless of which archives they are from, will raise errors.

https://github.com/llvm/llvm-project/blob/4372e629a9a98577a6a2d130109c3dc7da84dc62/lld/MachO/ld64-vs-lld.rst#L9
