### ISSUE TITLE
find-cycles.pl incompatible with MinGW headers

### ISSUE THREAD

**Issue by ohmantics** [llvm/llvm-project#5329]
|  |  |
| --- | --- |
| Bugzilla Link | [4957](https://llvm.org/bz4957) |
| Version | trunk |
| OS | Windows XP |
| CC | @asl |

## Extended Description 
When I build a stage2 compiler hosted on MinGW, find-cycles.pl fails. (Stage 1 is darwin->mingw32.)

The culprits are the ctype.h functions provided in MinGW. They're "inline" in C++ and an out-of-line copy of isalnum() is generated inside libLLVMCppBackend.a (among others).

MinGW uses "extern __inline__" and "extern inline __attribute__((__gnu_inline__)) in C depending on the version of GCC, but just "inline" in C++.

Some crazy thoughts:

1. Build with -ffunction-sections and have a libbing step remove all out-of-line ctype functions during MinGW builds.

2. Implement the gnu_inline attribute in llvm-gcc and clang and then change _mingw.h accordingly. The original implementation of gnu_inline is after GCC went GPLv3, so this would have to be done from scratch.

3. Find some other way to mark these functions with availableExternally instead of linkonce_odr.

This blocks non-debug builds on MinGW.

**Comment by gwelymernans** [comment]
This script doesn't seem to exist anymore. Closing unless it's been consumed by another utility and this issue still exists. If the issue still exists, then please file a new issue.
