### ISSUE TITLE
DSE removes some stores that are not dead

### ISSUE THREAD

**Issue by wjristow** [llvm/llvm-project#53307]
We've come across an example where DSE is incorrectly removing some stores, causing a runtime failure.  I've reduced it to the following test-case:

```c++
struct VecDbl3 {
  double X, Y, Z;
  inline __attribute__((__always_inline__)) VecDbl3() {}
  inline __attribute__((__always_inline__)) VecDbl3(double InX, double InY, double InZ) : X(InX), Y(InY), Z(InZ) {}
  inline __attribute__((__always_inline__)) double operator|(const VecDbl3& V) const {
    return X*V.X + Y*V.Y + Z*V.Z;
  }
  inline __attribute__((__always_inline__)) static double CombineVecs(const VecDbl3& A, const VecDbl3& B) {
    return A | B;
  }
  inline __attribute__((__always_inline__)) double& operator[](int Index) {
    return (&X)[Index];
  }
  inline __attribute__((__always_inline__)) double operator[](int Index)const {
    return (&X)[Index];
  }
  inline __attribute__((__always_inline__)) double GetSumOfSquares() const {
    return X*X + Y*Y + Z*Z;
  }
  VecDbl3 operator-() const {
    return VecDbl3(-X, -Y, -Z);
  }
  VecDbl3 operator-(const VecDbl3& Other) const {
    return VecDbl3(X - Other[0], Y - Other[1], Z - Other[2]);
  }
};
struct Shape {
  VecDbl3 CenterOfGravity;
  double Margin;
};
extern VecDbl3 RefineVector(const VecDbl3* Vec);
extern VecDbl3 VMin, VMax;

inline __attribute__((__always_inline__)) VecDbl3 ChoosePoint(const VecDbl3& Direction, double Amount) {
 VecDbl3 ChosenPt;  // At '-Os', following loop isn't unrolled (at '-O2' it is, and SROA keeps everything in regs).
 for (int i = 0; i < 3; ++i)  // 'NegatedV' passed to 'Direction'; Direction[1] and [2] loaded from mem ([0] OK).
  ChosenPt[i] = Direction[i] < 0 ? VMin[i] + Amount : VMax[i] - Amount;
 return ChosenPt;
}

bool CheckShapes(const Shape& A, const Shape& B, double ThickA, const VecDbl3& InitDir, double ThickB) {
  VecDbl3 V = -InitDir;
  bool bFoundSmaller = false;
  bool bNextIsSmaller = false;
  double PrevVal = 1.0e+30;
  const double StartingThickness = ThickA + ThickB + 1.0e-3;
  do {
    const VecDbl3 NegatedV = -V;  // DSE removes the 3 stores into NegatedV.{X,Y,Z}.
    const VecDbl3 VecA = ChoosePoint(NegatedV, A.Margin);  // This call is inlined.
    const VecDbl3 VecB = B.CenterOfGravity;
    const VecDbl3 W = VecA - VecB;
    if (VecDbl3::CombineVecs(V, W) > StartingThickness)
      return false;
    V = RefineVector(&W);
    double NextVal = V.GetSumOfSquares();
    bNextIsSmaller = NextVal < PrevVal;
    PrevVal = NextVal;
    bFoundSmaller |= bNextIsSmaller;
  } while (bNextIsSmaller);
  return bFoundSmaller;
}
```

As noted in the code-comments in the above test-case, the three stores into `NegatedV` (`NegatedV.X`, `NegatedV.Y` and `NegatedV.Z`) are eliminated by DSE   But a reference to `NegatedV` is passed to the function `ChoosePoint`, which loads from that memory.  More precisely, the call to `ChoosePoint(NegatedV, A.Margin)` is inlined, and there is a 3-iteration loop that references these 3 values of `NegatedV`.  One of them (`NegatedV.X`) is not loaded, and instead is referenced as a register, and so that one is fine.  But the other two do get loaded from memory, causing a run-time failure.

The failure is happening when compiled at `-Os` (compiling at `-Os` suppresses loop unrolling in `ChoosePoint`).  If it is compiled at `-O2`, loop unrolling is done, and then SROA successfully keeps _all_ of the members of `NegatedV` in registers, so the problem doesn't happen.  (That said, as expected, the bug can also manifest at `-O2` in a different test-case -- our customer has reported encountering it elsewhere at `-O2`.)  I believe this problem is target-independent, but for reference, the testing I did was with the target `x86_64-unknown-linux-gnu`.

I've bisected this to [llvmorg-12-init-9154-g2e5801020822](https://github.com/llvm/llvm-project/commit/2e580102082293f9f80160bc86413e401c566d8f).  This isn't an area I'm familiar with, but FWIW, that commit looks fine to me.  I suspect it's exposing a latent bug.

The problem still happens with the head of `main` (FTR, I tested [llvmorg-14-init-16451-g5a4bf4c2b33f](https://github.com/llvm/llvm-project/commit/5a4bf4c2b33fcc329d74c9c251f50fa38759dd90), and it also failed).

As an aside, in tracking this down, I found a commit that looked relevant ([llvmorg-14-init-7877-gfbc0c308d599](https://github.com/llvm/llvm-project/commit/fbc0c308d599fe3300ab6516650b65b41979446d), which is a BasicAA fix).  Specifically, that commit changed the behavior, leaving one of the three stores in place.  Somewhat ironically, the store that remains after that commit is the store into `NegatedV.X`, which is the one that is actually safe to remove, as that memory isn't loaded from in the loop of `CheckShapes`.  If the root problem of this bug is in BasicAA, _possibly_ the work of that commit will provide a clue (although I'm not optimistic that it will).

**Comment by nikic** [comment]
Dumping IR before DSE I get https://gist.github.com/nikic/5c75ae4a4ec025e5d578808862eb9fc5, but `opt -dse` doesn't do anything on that, so there might be an analysis preservation issue involved here.

**Comment by nikic** [comment]
Ah, looks like this needs `opt -tbaa -dse`. And indeed, the TBAA metadata on
```
  %.pre = load double, double* %arrayidx.i.i.phi.trans.insert, align 8, !tbaa !3, !noalias !18
```
looks wrong:
```
!3 = !{!4, !5, i64 0}
```
Even though this load is used for all three of the struct members, not just the first.

**Comment by nikic** [comment]
Though actually, now that I look at your code again, I think the TBAA metadata is correct: `(&X)[Index]` is undefined behavior, I believe.

**Comment by nikic** [comment]
Found the normative reference, see [[expr.new].4](http://eel.is/c++draft/expr.add#4).

**Comment by fhahn** [comment]
Agreed that this looks like UB in the source. Thanks for tracking this down!

**Comment by wjristow** [comment]
Thanks @nikic and @fhahn for the quick analysis!  Your link to the reference in the Standard is quite authoritative.

The one hesitancy I had on seeing your response, is that I have a vague memory that when a struct/class has a sequence of members of the same type, then taking the address one of those members in the sequence, and incrementing it, produces a valid pointer to the next element in the sequence.  But the test-case I posted isn't quite that.  And if I modify the test-case slightly, so that the function `ChoosePoint` is:

```c++
inline __attribute__((__always_inline__)) VecDbl3 ChoosePoint(const VecDbl3& Direction, double Amount) {
 VecDbl3 ChosenPt;
 const double *dp = &Direction.X;
 for (int i = 0; i < 3; ++i)
  ChosenPt[i] = dp[i] < 0 ? VMin[i] + Amount : VMax[i] - Amount;
 return ChosenPt;
}
```

then the problem disappears.  Very happy to have this closed, 

Thanks again!

**Comment by wjristow** [comment]
A final wrapup comment here, mostly for my own reference on the background of this.

Since the test-case I posted here is substantially reduced from the original customer-provided test-case, I was a little concerned that in reducing the test-case, I may have introduced the undefined behavior.  On checking, I can see that the original test-case has the same problem.

As expected, fixing the `operator[]` methods, such as:

```c++
  inline __attribute__((__always_inline__)) double& operator[](int Index) {
    return (static_cast<double*>(&X))[Index];
  }
  inline __attribute__((__always_inline__)) double operator[](int Index)const {
    return (static_cast<const double*>(&X))[Index];
  }
```

cleanly solves the problem.

Also, if I'm understanding the Standard correctly, then for any non-zero value of `Index` in `(&X)[Index]`, this is undefined behavior.  So the following loop clearly has undefined behavior:

```c++
 for (int i = 0; i < 3; ++i)
  ChosenPt[i] = Direction[i] < 0 ? VMin[i] + Amount : VMax[i] - Amount;
```

Yet, clang doesn't warn about the dangerous code.

This doesn't require UBSan at run-time to detect the dangerous code, so it's somewhat surprising to me that no compile-time warning is produced.  FTR, the test-case I posted doesn't get any warnings by default.  And even with `-Weverything`, the only warning produced is about the lack of a prototype for `CheckShapes`.  In fact, warnings aren't produced even if methods with explicit non-zero `Index` values are added to the class, as in:

```c++
struct VecDbl3 {
  double X, Y, Z;
    ...
  inline __attribute__((__always_inline__)) double operator[](int Index) const {
    return (&X)[Index];
  }
  inline __attribute__((__always_inline__)) double getX() const {
    return (&X)[0];
  }
  inline __attribute__((__always_inline__)) double getY() const {
    return (&X)[1];
  }
  inline __attribute__((__always_inline__)) double getZ() const {
    return (&X)[2];
  }
}
```

Here, `getY()` and `getZ()` _blatantly_ are undefined behavior, and yet no warnings are produced.  (I should note that I also tried GCC and MSVC with these additional methods, and neither of them warned about violating the rules of the Standard.  So we're not unusual in not producing a warning here.  Given this behavior of multiple compilers not producing warnings, I suspect that distinguishing between Standard-compliant and Standard-breaking computations like this may may be difficult to detect in the front-end.)

Of course, this is all tangential to the original question about the stores being eliminated.  Regardless, I wanted to record these observations here, for completeness.

**Comment by fhahn** [comment]
> Of course, this is all tangential to the original question about the stores being eliminated. Regardless, I wanted to record these observations here, for completeness.

It might be worth creating a new issue to improve diagnostics/static analysis in clang.

**Comment by wjristow** [comment]
> > Of course, this is all tangential to the original question about the stores being eliminated. Regardless, I wanted to record these observations here, for completeness.
> 
> It might be worth creating a new issue to improve diagnostics/static analysis in clang.

Good point.  I've just created #53347.
