### ISSUE TITLE
segfault from selectCopy on AArch64 with LTO

### ISSUE THREAD

**Issue by pnkfelix** [llvm/llvm-project#53315]
This bug is spawned off of https://github.com/rust-lang/rust/issues/91671#issuecomment-1004901138

The AArch64InstructionSelector.cpp code has this line:

https://github.com/llvm/llvm-project/blob/6d45284618f08fa28dc515cab96fa573c4c4479e/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp#L925

The problem is that RBI.getRegBank can return null, and does so during rustc's use of LLVM.

You can see the problematic behavior atop this trace that I've uploaded to [pernos.co, here](https://pernos.co/debug/RZH6sUOHPr1TI7z0036Y-g/index.html#f{m[rJs,AA_,t[Bg,Gkvv_,f{e[rJE,Fyo_,s{af40gofAA,bFg,uKem8tA,oKf1Paw___/). That trace is derived from code that I've put into a dedicated repository, here: https://github.com/pnkfelix/issue-91671-a64-doctestfail
  

I have not yet managed to narrow the test case down to something that I can replicate atop `llc` or `opt` alone, but I wanted to start tracking the issue here in the LLVM organization so that LLVM developers could help me narrow this down further.

**Comment by nikic** [comment]
Reduced:
```
; RUN: llc -O0 < %s
target triple = "aarch64-unknown-linux-gnu"

define void @test() {
  %x = call i128 @returns_arg(i128 0)
  call void @accepts_arg(i128 %x)
  ret void
}

declare i128 @returns_arg(i128 returned)
declare void @accepts_arg(i128)
```

**Comment by nikic** [comment]
Here's the `-verify-machineinstrs` output:
```
# After IRTranslator
# Machine code for function test: IsSSA, TracksLiveness

bb.1 (%ir-block.0):
  %1:_(s128) = G_CONSTANT i128 0
  ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  %2:_(s64), %3:_(s64) = G_UNMERGE_VALUES %1:_(s128)
  $x0 = COPY %2:_(s64)
  $x1 = COPY %3:_(s64)
  BL @returns_arg, <regmask $fp $lr $b8 $b9 $b10 $b11 $b12 $b13 $b14 $b15 $d8 $d9 $d10 $d11 $d12 $d13 $d14 $d15 $h8 $h9 $h10 $h11 $h12 $h13 $h14 $h15 $s8 $s9 $s10 $s11 $s12 $s13 $s14 and 55 more...>, implicit-def $lr, implicit $sp, implicit $x0, implicit $x1
  %4:_(s64) = COPY %2:_(s64)
  %4:_(s64) = COPY %2:_(s64)
  %0:_(s128) = G_MERGE_VALUES %4:_(s64), %5:_(s64)
  ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  %6:_(s64), %7:_(s64) = G_UNMERGE_VALUES %0:_(s128)
  $x0 = COPY %6:_(s64)
  $x1 = COPY %7:_(s64)
  BL @accepts_arg, <regmask $fp $lr $b8 $b9 $b10 $b11 $b12 $b13 $b14 $b15 $d8 $d9 $d10 $d11 $d12 $d13 $d14 $d15 $h8 $h9 $h10 $h11 $h12 $h13 $h14 $h15 $s8 $s9 $s10 $s11 $s12 $s13 $s14 and 53 more...>, implicit-def $lr, implicit $sp, implicit $x0, implicit $x1
  ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  RET_ReallyLR

# End machine code for function test.

*** Bad machine code: Multiple virtual register defs in SSA form ***
- function:    test
- basic block: %bb.1  (0x891c1c0)
- instruction: %4:_(s64) = COPY %2:_(s64)
- operand 0:   %4:_

*** Bad machine code: Multiple virtual register defs in SSA form ***
- function:    test
- basic block: %bb.1  (0x891c1c0)
- instruction: %4:_(s64) = COPY %2:_(s64)
- operand 0:   %4:_

*** Bad machine code: Reading virtual register without a def ***
- function:    test
- basic block: %bb.1  (0x891c1c0)
- instruction: %0:_(s128) = G_MERGE_VALUES %4:_(s64), %5:_(s64)
- operand 2:   %5:_
```

**Comment by nikic** [comment]
Presumably this code:
https://github.com/llvm/llvm-project/blob/d03c5bc8d437e47ae424ac9611ae441cd5225526/llvm/lib/Target/AArch64/GISel/AArch64CallLowering.cpp#L1170-L1184
Fails to handle values stored in multiple registers in some form.

**Comment by nikic** [comment]
Candidate patch: https://reviews.llvm.org/D117866
