### ISSUE TITLE
Any projected timeline for LLVM IR generation by Flang?

### ISSUE THREAD

**Issue by Goob115** [llvm/llvm-project#53323]
Hello,

According to the release notes for Flang 13.0.0, it is not yet able to generate LLVM IR. If any, is there any known timeline or ETA for the completion of this feature specifically? Any information would be helpful.

Thanks

**Comment by clementval** [comment]
Hi, 

We are in the process of upstreaming all the necessary parts to have LLVM IR generation from Fortran code. There is no ETA or timeline on this. We are just trying to make this happen as soon as possible.

**Comment by VitalyAnkh** [comment]
flang-new can generate LLVM IR now. Should this issue be closed?
