### ISSUE TITLE
Verifier error after "X86 FP Stackifier" with clang -O1 -g

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#53336]
llvm commit: e7762653d3b0
Reproduce with:
 clang --target=x86_64-unknown-linux -c -O1 -g bbi-65026.c -o /dev/null -mllvm -verify-machineinstrs

Result:
 After X86 FP Stackifier
 Machine code for function c: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
Frame Objects:
  fi#0: size=4, align=4, at location [SP+8]
  fi#1: size=4, align=4, at location [SP+8]
  fi#2: size=4, align=4, at location [SP+8]
  fi#3: size=2, align=2, at location [SP+8]
  fi#4: size=2, align=2, at location [SP+8]

bb.0.entry:
  successors: %bb.1(0x30000000), %bb.2(0x50000000); %bb.1(37.50%), %bb.2(62.50%)

  renamable $ecx = MOV32rm $rip, 1, $noreg, @b, $noreg, debug-location !20 :: (dereferenceable load (s32) from @b, !tbaa !22); bbi-65026.c:4:7
  renamable $eax = MOV32rm $rip, 1, $noreg, @a, $noreg, debug-location !27 :: (dereferenceable load (s32) from @a, !tbaa !22); bbi-65026.c:0
  TEST32rr renamable $ecx, renamable $ecx, implicit-def $eflags, debug-location !26; bbi-65026.c:4:9
  JCC_1 %bb.2, 5, implicit $eflags, debug-location !28; bbi-65026.c:4:7
  JMP_1 %bb.1, debug-location !28; bbi-65026.c:4:7

bb.1.if.then:
; predecessors: %bb.0
  successors: %bb.3(0x80000000); %bb.3(100.00%)
  liveins: $eax
  MOV32mr %stack.1, 1, $noreg, 0, $noreg, killed renamable $eax, debug-location !29 :: (store (s32) into %stack.1); bbi-65026.c:5:9
  ILD_F32m %stack.1, 1, $noreg, 0, $noreg, implicit-def dead $fpsw, implicit $fpcw, implicit-def $st0, debug-location !29 :: (load (s32) from %stack.1); bbi-65026.c:5:9
  DBG_INSTR_REF 2, 0, !17, !DIExpression(), debug-location !30; bbi-65026.c:0
  JMP_1 %bb.3, debug-location !31; bbi-65026.c:5:5

bb.2.if.else:
; predecessors: %bb.0
  successors: %bb.3(0x80000000); %bb.3(100.00%)
  liveins: $eax, $ecx
  CDQ implicit-def $eax, implicit-def $edx, implicit $eax, debug-location !32; bbi-65026.c:7:11
  IDIV32r killed renamable $ecx, implicit-def $eax, implicit-def dead $edx, implicit-def dead $eflags, implicit $eax, implicit killed $edx, debug-location !32; bbi-65026.c:7:11
  MOV32mr %stack.0, 1, $noreg, 0, $noreg, killed renamable $eax, debug-location !33 :: (store (s32) into %stack.0); bbi-65026.c:7:9
  nofpexcept LD_F1 implicit-def dead $fpsw, implicit $fpcw, implicit-def $st0
  CHS_F implicit-def dead $fpsw
  ADD_FI32m %stack.0, 1, $noreg, 0, $noreg, implicit-def dead $fpsw, implicit $fpcw, debug-location !34 :: (load (s32) from %stack.0); bbi-65026.c:7:15
  DBG_INSTR_REF 1, 0, !17, !DIExpression(), debug-location !30; bbi-65026.c:0

bb.3.if.end:
; predecessors: %bb.2, %bb.1

  DBG_PHI $fp0, 3
  DBG_INSTR_REF 3, 0, !17, !DIExpression(), debug-location !30; bbi-65026.c:0
  FNSTCW16m %stack.3, 1, $noreg, 0, $noreg, implicit-def $fpsw, implicit $fpcw, debug-location !35 :: (store (s16) into %stack.3); bbi-65026.c:8:10
  renamable $eax = MOVZX32rm16 %stack.3, 1, $noreg, 0, $noreg, debug-location !35 :: (load (s16) from %stack.3); bbi-65026.c:8:10
  renamable $eax = OR32ri killed renamable $eax(tied-def 0), 3072, implicit-def dead $eflags, debug-location !35; bbi-65026.c:8:10
  MOV16mr %stack.4, 1, $noreg, 0, $noreg, renamable $ax, implicit killed $eax, debug-location !35 :: (store (s16) into %stack.4); bbi-65026.c:8:10
  FLDCW16m %stack.4, 1, $noreg, 0, $noreg, implicit-def $fpsw, implicit-def $fpcw, debug-location !35 :: (load (s16) from %stack.4); bbi-65026.c:8:10
  IST_FP32m %stack.2, 1, $noreg, 0, $noreg, implicit-def $fpsw, implicit $fpcw, implicit $st0, debug-location !35; bbi-65026.c:8:10
  FLDCW16m %stack.3, 1, $noreg, 0, $noreg, implicit-def $fpsw, implicit-def $fpcw, debug-location !35 :: (load (s16) from %stack.3); bbi-65026.c:8:10
  renamable $eax = MOV32rm %stack.2, 1, $noreg, 0, $noreg, debug-location !35 :: (load (s32) from %stack.2); bbi-65026.c:8:10
  RET 0, $eax, debug-location !36; bbi-65026.c:8:3

 End machine code for function c.

*** Bad machine code: Using an undefined physical register ***
- function:    c
- basic block: %bb.3 if.end (0xa768b70)
- instruction: DBG_PHI $fp0, 3
- operand 0:   $fp0
fatal error: error in backend: Found 1 machine code errors.

[bbi-65026.c.gz](https://github.com/llvm/llvm-project/files/7913030/bbi-65026.c.gz)

**Comment by mikaelholmen** [comment]
It starts failing with commit 6a605b97a20, https://reviews.llvm.org/D116821:
    [DebugInfo] Move flag for instr-ref to LLVM option, from TargetOptions

The failure goes away if adding
 -mllvm -experimental-debug-variable-locations=false

**Comment by jmorse** [comment]
Thanks for bisecting back and reporting, the patch in https://reviews.llvm.org/D117891 should fix this. This seems to just be a case of the verifier not treating the DBG_PHI instructions the same as DBG_VALUEs.

It looks like both variable location mechanisms drop the "d" variable, alas.

**Comment by jmorse** [comment]
(Forgot to close this; patch in D117891 has landed).
