### ISSUE TITLE
clang -fopenmp bug with scan inclusive directive

### ISSUE THREAD

**Issue by richardbleikamp** [llvm/llvm-project#53344]
I'm running a test from the newest OpenMP examples document, that tests the openmp scan directive.  When compiled without the -fopenmp flag, the test "passes" (gets expected answers).  With the -fopenmp flag, the final value for the variable specified in the scan inclusive directive ("w") does NOT have its final value copied back to the master thread.  This is all host code, no target regions.  I've tested with with:
Ubuntu clang version 14.0.0-++20211220052850+329b0181c3f1-1~exp1~20211220172956.94
and with
AOMP_STANDALONE_14.0-0 clang version 14.0.0 (https://github.com/radeonopencompute/llvm-project 266c945e349a1bee3626faf3cfdb169441db5269)

I can provide OpenMP spec references if desired.  Let me know if there's anything else I can do to help.  

Test case:

#include <stdio.h>
 #define N 100

 int main(void)
 {
 int a[N], b[N];
 long long  w = 0;

 // initialization
 for (int k = 0; k < N; k++)
 a[k] = k + 1;

 // a[k] is included in the computation of producing results in b[k]
 // #pragma omp parallel for simd reduction(inscan,+: w)
 #pragma omp parallel for reduction(inscan, +: w) 
 for (int k = 0; k < N; k++) {
  w += a[k]; 
 #pragma omp scan inclusive(w)
  b[k] = w; 
 }

 printf("w=%lld, b[0]=%d b[1]=%d b[2]=%d\n", w, b[0], b[1], b[2]);
 // 5050, 1 3 6

 if( w!=5050 || b[0]!=1 || b[1]!=3 || b[2]!=6 ){
    printf("Fail!\n");
    return 1;
 }
 printf("Success!\n");
 return 0;

 }

**Comment by shiltian** [comment]
```
➜  clang -fopenmp -O3 53344.c -o test
➜  env OMP_NUM_THREADS=16 ./test
w=5050, b[0]=1 b[1]=3 b[2]=6
Success!
```
Cannot reproduce it on my side. Since it's been one year, I suppose it has been fixed. Feel free to reopen it if necessary.
