### ISSUE TITLE
Preprocessor error on nested macro with brace-initializer

### ISSUE THREAD

**Issue by pogo59** [llvm/llvm-project#53350]
I'm getting an unexpected set of errors from the preprocessor, which I think I've traced down to using a brace-initializer on a data item declared inside a macro. It seems like it has to be a few levels deep in order to trigger the bug, and also has to have more than one element in the brace-list.  I've worked around it by changing the braces to parens and defining a constructor, but the errors look pretty strange.
Here's the reduced source:
```
struct static_item {
  const char *file;
  bool executed;
  static_item(const char *file, bool executed)
    : file(file), executed(executed) {}
};

#ifdef CLEAN
#define GTEST_DECLARE_ \
  static static_item GTEST_item_ ( __FILE__, false );
#else
#define GTEST_DECLARE_ \
  static static_item GTEST_item_ { __FILE__, false };
#endif

#define GTEST_DEATH_TEST_(statement) \
  if (true) { statement; }

#define ASSERT_EXIT(statement) \
  GTEST_DEATH_TEST_(statement)

#define EXPECT_TRUE(condition) \
  if (condition) { GTEST_DECLARE_ }

void DiesMacroDeath() {
  ASSERT_EXIT({ EXPECT_TRUE(true); });
}
```
Compiling with `-DCLEAN` is fine, without that it gets two errors as follows.
```
~/projects/RGT/DEBUG_DEATH$ $LLUP/clang -o test.cpp.o -c test.cpp 
test.cpp:26:17: error: too many arguments provided to function-like macro invocation
  ASSERT_EXIT({ EXPECT_TRUE(true); });
                ^
test.cpp:23:20: note: expanded from macro 'EXPECT_TRUE'
  if (condition) { GTEST_DECLARE_ }
                   ^
test.cpp:13:46: note: expanded from macro 'GTEST_DECLARE_'
  static static_item GTEST_item_ { __FILE__, false };
                                             ^
test.cpp:16:9: note: macro 'GTEST_DEATH_TEST_' defined here
#define GTEST_DEATH_TEST_(statement) \
        ^
test.cpp:26:3: note: cannot use initializer list at the beginning of a macro argument
  ASSERT_EXIT({ EXPECT_TRUE(true); });
  ^
test.cpp:20:3: note: expanded from macro 'ASSERT_EXIT'
  GTEST_DEATH_TEST_(statement)
  ^
test.cpp:26:3: error: use of undeclared identifier 'GTEST_DEATH_TEST_'
  ASSERT_EXIT({ EXPECT_TRUE(true); });
  ^
test.cpp:20:3: note: expanded from macro 'ASSERT_EXIT'
  GTEST_DEATH_TEST_(statement)
  ^
2 errors generated.
```
Observe the "note: macro 'GTEST_DEATH_TEST_' defined here" followed by "error: use of undeclared identifer 'GTEST_DEATH_TEST_'" which seems pretty confused.
Also "cannot use initializer list at the beginning of a macro argument" is just not the problem, the initializer list is nowhere near the beginning of any macro argument.  I suspect that note comes up because the argument is a brace-enclosed block?

gcc is less verbose but also has the same problem:
```
~/projects/RGT/DEBUG_DEATH$ gcc -c test.cpp
test.cpp:26:37: error: macro "GTEST_DEATH_TEST_" passed 2 arguments, but takes just 1
   ASSERT_EXIT({ EXPECT_TRUE(true); });
                                     ^
test.cpp: In function ‘void DiesMacroDeath()’:
test.cpp:20:3: error: ‘GTEST_DEATH_TEST_’ was not declared in this scope
   GTEST_DEATH_TEST_(statement)
   ^
test.cpp:26:3: note: in expansion of macro ‘ASSERT_EXIT’
   ASSERT_EXIT({ EXPECT_TRUE(true); });
   ^~~~~~~~~~~
```
which does make me wonder if I'm tripping over some especially obscure bit of defined preprocessor behavior.  It would have to involve the commas inside the braces being interpreted differently than the commas inside the parens, somehow, and really it seems like that shouldn't happen.

**Comment by Quuxplusone** [comment]
I believe this is "not a bug." The C preprocessor doesn't treat angle-brackets or curly-braces specially; it knows only about parentheses. This comes up a lot with type-traits in C++:
```
assert(std::is_same_v<int, int>); // syntax error
assert((std::is_same_v<int, int>)); // OK
```
On the first line, we're expanding `assert` with two macro arguments, namely `std::is_same_v<int` and `int>`. On the second line, we're expanding it with just one macro argument, namely `(std::is_same_v<int, int>)`. As you see, the traditional user-side fix is just to use `MACRO(( ... ))` instead of `MACRO( ... )`.

If you have control over the macro — or feel like submitting a patch upstream — the traditional _library-side_ fix is to change the single-argument macro to a variadic macro, like this:
```
#define ASSERT_EXIT(...) \
  GTEST_DEATH_TEST_(__VA_ARGS__)
```

**Comment by pogo59** [comment]
Thanks, Arthur.  I figured it was something like that.

What I'm trying to achieve is guaranteed compile-time initialization even when control does not pass over the declaration; and if control *does* pass over the declaration, it sets the "executed" flag (not shown in the above example).  I believe using a ctor does not guarantee compile-time initialization, and using constexpr would make the item immutable so I can't set the "executed" flag.  The scheme above has been working in simpler contexts, but I've gotten stuck on this one.

**Comment by Quuxplusone** [comment]
@pogo59: That sounds like a great question for https://cppalliance.org/slack/ or StackOverflow, but not here. (From your description it sounds like you should be looking at a C++14 `constexpr` constructor and/or the C++20 `constinit` keyword, and I don't see how it has _anything_ to do with macros. But that's off-topic for this bug tracker.)

**Comment by pogo59** [comment]
@Quuxplusone I got to this point based on info gleaned from StackOverflow!  Macros are involved because I'm instrumenting existing gtest macros; I don't have any choice there.
Was not aware that `constexpr` could be applied to a ctor, thanks!  And you're right, this bug is not the place to pursue the solution.
