### ISSUE TITLE
Missing tranformation (x & y) + ~(x | y) -> ~(x ^ y)

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#53357]
https://alive2.llvm.org/ce/z/EiJo7c

**Comment by RKSimon** [comment]
FTR, the equivalent demorgan identity ((x & y) + (~x & ~y)) gets transformed to ((x & y) + ~(x | y)) so has the same problem

https://alive2.llvm.org/ce/z/zpJ-j5

**Comment by rotateright** [comment]
Either we recognize this pattern as-is, or we recognize a special-case of "haveNoCommonBitsSet" to convert the 'add' into 'or':
https://alive2.llvm.org/ce/z/XSsio9

**Comment by ChuanqiXu9** [comment]
Sent https://reviews.llvm.org/D118094
