### ISSUE TITLE
Error when structured binding an array type by {} initialization

### ISSUE THREAD

**Issue by 992678220** [llvm/llvm-project#53365]
I've tried the below code in Compiler Explorer. Both msvc and gcc compile but clang cannot. (I've tried almost every clang's version)

```
void f() {
  int a[2]{1, 2};
  auto [x, y]{a};
}
```

https://godbolt.org/z/qWWe3M6MG

**Comment by frederick-vs-ja** [comment]
Duplicate of #31813.
