### ISSUE TITLE
Bogus unique_ptr-to-shared_ptr conversions should be forbidden

### ISSUE THREAD

**Issue by CaseyCarter** [llvm/llvm-project#53368]
Every converting construction/assignment from `unique_ptr` to `shared_ptr` in https://godbolt.org/z/drYoErG6v should fail. The problematic cases are:
* construction/assignment to `shared_ptr<T>` from `unique_ptr<T[]>`, and
* construction/assignment to `shared_ptr<base[]>` from `unique_ptr<derived[]>`
both of which fail the "`Y*` is compatible with `T*`" constraint.

(Related: https://reviews.llvm.org/D117996)

**Comment by Quuxplusone** [comment]
Should probably fix https://wg21.link/LWG3548 "deleters should be moved, not copied" at the same time.

**Comment by huixie90** [comment]
should be fixed already by
https://github.com/llvm/llvm-project/commit/a38a4654ce4b1d2ae8a03797d2e520e415150492
