### ISSUE TITLE
NSUInteger variables don't get updated in variables window

### ISSUE THREAD

**Issue by swainwri** [llvm/llvm-project#53363]
When debugging in XCode 13.2.1, any NSUInteger variable in the variables window not get updated, simply shows 0. One has to highlight variable and show info or p the variable in debug window....quite a nuisance.

**Comment by EugeneZelenko** [comment]
Are you referring to LLDB? Could problem be reproduced in standalone LLDB session?

**Comment by swainwri** [comment]
I have never seen the need to use lldb standalone if I’m programming with Xcode.


Create a new app with Xcode in the ViewController.m

//
//  ViewController.m
//  NSUIntegerVariable
//
//  Created by Steve Wainwright on 23/01/2022.
//

#import "ViewController.h"

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    NSUInteger uivariable = 100;
    NSInteger ivariable = 100;
    
    NSLog(@"%ld, %ld", uivariable, ivariable);
}


@end

On debugging this you will see that in the variable window the NSUInteger uivariable is not updated to 100, one has to get info for the variable, yet the NSInteger variable is updated

Perhaps this is an XCode issue

**Comment by EugeneZelenko** [comment]
> Perhaps this is an XCode issue

This is why it's good idea to run executable in standalone LLDB: just to narrow down source of problem.

**Comment by swainwri** [comment]
For me to get fully au fait with using lldb standalone, I may have to use up a couple of precious days. I put together a file to show the problem, which incidentally took me less than a minute, obviously this hasn’t helped you to identify the problem…..so let’s leave it at that.

be safe.

**Comment by EugeneZelenko** [comment]
See #53284 as example of resolution of issues not strictly confirmed in LLVM code.
