### ISSUE TITLE
Suboptimal code generated for vectors equality check on X86

### ISSUE THREAD

**Issue by d-makogon** [llvm/llvm-project#53379]
[Repro](https://godbolt.org/z/MTc4e48KG)

The code in `@and_reduce` function is an output of instcombine pass run on this function:
```llvm
define i1 @reduce_icmp_eq(<4 x i32> %lhs, <4 x i32> %rhs) {
  %cmp = icmp eq <4 x i32> %lhs, %rhs
  %r = call i1 @llvm.vector.reduce.and.v4i1(<4 x i1> %cmp)
  ret i1 %r
}
```
The code generated for `@sub` function is more optimal than for `@and_reduce`, I guess.
For some reason codegen replaces the comparsion against 0 with comparison against 0xF.
Here is where it's done in the output of `llc -print-after-all`:
```
*** IR Dump After Module Verifier (verify) ***
define i1 @reduce_icmp_eq(<4 x i32> %lhs, <4 x i32> %rhs) #0 {
  %cmp = icmp ne <4 x i32> %lhs, %rhs
  %1 = bitcast <4 x i1> %cmp to i4
  %2 = icmp eq i4 %1, 0
  ret i1 %2
}


# *** IR Dump After X86 DAG->DAG Instruction Selection (amdgpu-isel) ***:
# Machine code for function reduce_icmp_eq: IsSSA, TracksLiveness
Function Live Ins: $xmm0 in %0, $xmm1 in %1

bb.0 (%ir-block.0):
  liveins: $xmm0, $xmm1
  %1:vr128 = COPY $xmm1
  %0:vr128 = COPY $xmm0
  %2:vr128 = VPCMPEQDrr %0:vr128, %1:vr128
  %3:gr32 = VMOVMSKPSrr killed %2:vr128
  %4:gr32 = SUB32ri8 %3:gr32(tied-def 0), 15, implicit-def $eflags
  %5:gr8 = SETCCr 4, implicit $eflags
  $al = COPY %5:gr8
  RET 0, $al

# End machine code for function reduce_icmp_eq.```

**Comment by max-quazan** [comment]
Some more details: instcombine turns the original code
```
define i1 @reduce_icmp_eq(<4 x i32> %lhs, <4 x i32> %rhs) {
  %cmp = icmp eq <4 x i32> %lhs, %rhs
  %r = call i1 @llvm.vector.reduce.and.v4i1(<4 x i1> %cmp)
  ret i1 %r
}
```
into
```
define i1 @reduce_icmp_eq(<4 x i32> %lhs, <4 x i32> %rhs) #0 {
  %cmp = icmp ne <4 x i32> %lhs, %rhs
  %1 = bitcast <4 x i1> %cmp to i4
  %2 = icmp eq i4 %1, 0
  ret i1 %2
}
```
which is used as input for LLC. After LLC, the resulting code is
```
        vpcmpeqd        %xmm1, %xmm0, %xmm0
        vmovmskps       %xmm0, %eax
        cmpl    $15, %eax
        sete    %al
        retq
```
The suggested better solution is
```
        vpsubd  %xmm1, %xmm0, %xmm0
        vptest  %xmm0, %xmm0
        sete    %al
        retq
```
which is 1 instruction less and doesn't use 0xff-like constants.

**Comment by RKSimon** [comment]
We normally do convert to PTEST where we can - I'll see what's going wrong here.

**Comment by RKSimon** [comment]
Godbolt link: https://gcc.godbolt.org/z/zY5hExWcb

**Comment by max-quazan** [comment]
Wow, that was fast! Thanks Simon!

**Comment by RKSimon** [comment]
thanks for the confirmation - resolving

**Comment by max-quazan** [comment]
Err, I checked performance on our original motivating test, and things there only got worse. :( Will try to file a more specific repro.

**Comment by max-quazan** [comment]
@RKSimon you might as well be interested in looking at https://github.com/llvm/llvm-project/issues/53416, which is a follow-up for this one.
