### ISSUE TITLE
Builtin ModuleOp is privileged by translations

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#53370]
There is a general goal to move to allow "custom" top level operations instead of requiring builtin.ModuleOp, but the translation infrastructure hard codes ModuleOp, e.g. in:

```
/// Interface of the function that translates MLIR to a different format and
/// outputs the result to a stream. It is allowed to modify the module.
using TranslateFromMLIRFunction =
    std::function<LogicalResult(ModuleOp, llvm::raw_ostream &output)>;
```

It would be nice to move towards just using Operation* here or something.

**Comment by rkayaith** [comment]
ed90f8026e45b9f922002ad03c6f37c4881be1d8 fixed this
