### ISSUE TITLE
.arm directive doesn’t align 32-bit code instructions and sections by 4 bytes

### ISSUE THREAD

**Issue by evodius96** [llvm/llvm-project#53386]
For Arm targets (e.g. cortex-r5), using the “.arm” directive in hand-coded assembly does not have the same behavior with the LLVM integrated assembler as for GNU as. The directive will ensure that succeeding instructions are correctly interpreted as Arm-mode instructions, but _it won’t enforce a 4byte alignment on instructions (or corresponding sections)_. In order to do this, a user has to explicitly align sections using an alignment directive.

There is no Arm-determined specification governing the “.arm” directive alignment behavior.  Further, the documentation for the .arm and .thumb directives in the GNU assembler makes no mention of alignment ([https://sourceware.org/binutils/docs/as/ARM-Directives.html#ARM-Directives](https://sourceware.org/binutils/docs/as/ARM-Directives.html#ARM-Directives))

However, because the GNU assembler (GAS) implements the 4-byte alignment behavior, the LLVM integrated Arm assembler should match that behavior.  This was recommended by Arm in a (now-abandoned) code review: [https://reviews.llvm.org/D110580 ](https://reviews.llvm.org/D110580 )

See attached [sample.s.txt](https://github.com/llvm/llvm-project/files/7927623/sample.s.txt)
Build for GCC cross-compiler: arm-none-eabi-gcc -nostartfiles -mcpu=cortex-r5 -o sample sample.s

**Comment by antangelo** [comment]
I am interested in working on this issue. I believe it can be solved by emitting an alignment after the code switch in the `.arm` directive parser.
