### ISSUE TITLE
lld: linker script with .note section doesn't generate a PT_NOTE

### ISSUE THREAD

**Issue by bluca** [llvm/llvm-project#53383]
The following works when compiling with gcc and linking with bfd.

Tested with clang and lld version 1:13.0.1~+rc3-1~exp1 from Debian Unstable.

Sample program test.c:

```
int main(void) { return 0; }
```

Linker script test.ld:

```
SECTIONS
{
    .note.package : ALIGN(4) {
        BYTE(0x04) BYTE(0x00) BYTE(0x00) BYTE(0x00) /* Length of Owner including NUL */
        BYTE(0x1d) BYTE(0x00) BYTE(0x00) BYTE(0x00) /* Length of Value including NUL */
        BYTE(0x7e) BYTE(0x1a) BYTE(0xfe) BYTE(0xca) /* Note ID */
        BYTE(0x46) BYTE(0x44) BYTE(0x4f) BYTE(0x00) /* Owner: 'FDO\x00' */
        BYTE(0x7b) BYTE(0x22) BYTE(0x6e) BYTE(0x61) /* Value: '{"name":"foo","version":"1"}\x00\x00\x00\x00' */
        BYTE(0x6d) BYTE(0x65) BYTE(0x22) BYTE(0x3a)
        BYTE(0x22) BYTE(0x66) BYTE(0x6f) BYTE(0x6f)
        BYTE(0x22) BYTE(0x2c) BYTE(0x22) BYTE(0x76)
        BYTE(0x65) BYTE(0x72) BYTE(0x73) BYTE(0x69)
        BYTE(0x6f) BYTE(0x6e) BYTE(0x22) BYTE(0x3a)
        BYTE(0x22) BYTE(0x31) BYTE(0x22) BYTE(0x7d)
        BYTE(0x00) BYTE(0x00) BYTE(0x00) BYTE(0x00)
    }
}
INSERT AFTER .note.gnu.build-id;
/* HINT: add -Wl,-dT,/path/to/this/file to $LDFLAGS */
```

```
clang -Wall -o ./test -fuse-ld=lld -g test.c -Wl,-T,./test.ld
```

Output of readelf:

```
$ readelf -a test | grep package
  [ 4] .note.package     NOBITS           0000000000000000  000008e0
   01     .interp .note.package 
   10     .note.ABI-tag .note.gnu.build-id .note.package
```

On a binary linked with bfd:

```
$ readelf -a test.bfd | grep package
  [ 3] .note.package     NOTE             00000000000002e8  000002e8
   02     .interp .note.gnu.build-id .note.package .note.ABI-tag .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn 
   07     .note.gnu.build-id .note.package .note.ABI-tag 
Displaying notes found in: .note.package
```

I've tried setting various types in the linker script, to no avail. Is this supposed to be supported like in bfd? Or are there llvm-specific flags that need to be used?

**Comment by MaskRay** [comment]
The behavior looks ad-hoc. I think the proper way to do this is to support specifying the output section type in the linker script.

It's perhaps better to customize the section content in an assembly file or a C file with inline assembly.
The assembler recognizes `.note*` sections and set `SHT_NOTE` on them.

**Comment by bluca** [comment]
Well, the assembler behavior is ad-hoc too :-) anyway, using compiled code is really not an option for our use case, it needs to be a linker script. And adding a new option that breaks when using the script with bfd would make things worse. There's a very simple fix, will send a patch today.
