### ISSUE TITLE
compiler-rt/test/profile/Linux/instrprof-debug-info-correlate.c fails after dwarf 4 -> 5 version change

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#53387]

**Comment by zmodem** [comment]
(sorry, accidentally hit enter too soon)

On Linux:

$ ninja -C build.release -j900 check-profile
[...]
Exit Code: 134

Command Output (stderr):
--
llvm-profdata: /work/llvm.monorepo/llvm/lib/ProfileData/InstrProf.cpp:444: llvm::Error llvm::collectPGOFuncNameStrings(ArrayRef<std::string>, bool, std::string &): Assertion `!NameStrs.empty() && "No name data to emit"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: llvm-profdata "llvm-profdata merge" -o /work/llvm.monorepo/build.release/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/instrprof-debug-info-correlate.c.tmp.profdata --debug-info=/work/llvm.monorepo/build.release/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/instrprof-debug-info-correlate.c.tmp /work/llvm.monorepo/build.release/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/instrprof-debug-info-correlate.c.tmp.proflite
 #0 0x000000000069dda3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/work/llvm.monorepo/build.release/bin/llvm-profdata+0x69dda3)
 #1 0x000000000069bf0e llvm::sys::RunSignalHandlers() (/work/llvm.monorepo/build.release/bin/llvm-profdata+0x69bf0e)
 #2 0x000000000069e25a SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f1e1efd0200 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x13200)
 #4 0x00007f1e1ea65891 raise ./signal/../sysdeps/unix/sysv/linux/raise.c:50:1
 #5 0x00007f1e1ea4f536 abort ./stdlib/abort.c:81:7
 #6 0x00007f1e1ea4f41f get_sysdep_segment_value ./intl/loadmsgcat.c:509:8
 #7 0x00007f1e1ea4f41f _nl_load_domain ./intl/loadmsgcat.c:970:34
 #8 0x00007f1e1ea5e212 (/lib/x86_64-linux-gnu/libc.so.6+0x35212)
 #9 0x00000000004f2147 llvm::collectPGOFuncNameStrings(llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (/work/llvm.monorepo/build.release/bin/llvm-profdata+0x4f2147)
#10 0x00000000004f94a8 llvm::InstrProfCorrelatorImpl<unsigned long>::correlateProfileData() (/work/llvm.monorepo/build.release/bin/llvm-profdata+0x4f94a8)
#11 0x0000000000415cbe merge_main(int, char const**) llvm-profdata.cpp:0:0
#12 0x00000000004108dc main (/work/llvm.monorepo/build.release/bin/llvm-profdata+0x4108dc)
#13 0x00007f1e1ea507ed __libc_start_main ./csu/../csu/libc-start.c:332:16
#14 0x000000000040b4da _start (/work/llvm.monorepo/build.release/bin/llvm-profdata+0x40b4da)
/work/llvm.monorepo/build.release/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/instrprof-debug-info-correlate.c.script: line 7: 2411755 Aborted                 llvm-profdata merge -o /work/llvm.monorepo/build.release/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/instrprof-debug-info-correlate.c.tmp.profdata --debug-info=/work/llvm.monorepo/build.release/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/instrprof-debug-info-correlate.c.tmp /work/llvm.monorepo/build.release/projects/compiler-rt/test/profile/Profile-x86_64/Linux/Output/instrprof-debug-info-correlate.c.tmp.proflite

--

********************
********************
Failed Tests (2):
  Profile-i386 :: Linux/instrprof-debug-info-correlate.c
  Profile-x86_64 :: Linux/instrprof-debug-info-correlate.c


Bisection points to @dwblaikie 's

commit d3b26dea16108c427b19b5480c9edc76edf8f5b4 (refs/bisect/skip-d3b26dea16108c427b19b5480c9edc76edf8f5b4)
Author: David Blaikie <dblaikie@gmail.com>
Date:   Sun Jan 23 20:45:25 2022 -0800

    Clang: Change the default DWARF version to 5
    
    (except on platforms that already opt in to specific versions - SCE,
    Android, and Darwin using DWARFv4 explicitly, for instance)


I couldn't find any buildbots failing, but I also don't really know which ones run these tests.

**Comment by zmodem** [comment]
Passing -gdwarf-4 makes the test pass, so doing this for now (38e16e1cebb891ad47b85727bf46f7dac6d7da94) but this should probably be investigated.

**Comment by nico** [comment]
@dwblaikie

**Comment by dwblaikie** [comment]
Thanks for the workaround @zmodem - I'll look into it further once I've looked at the other remaining/live failures.

**Comment by dwblaikie** [comment]
Yep, looks like https://github.com/llvm/llvm-project/blob/902184e6cc263e4c66440c95a21665b6fdffe57c/llvm/lib/ProfileData/InstrProfCorrelator.cpp#L175 that doesn't handle DWARFv5 `OP_addrx` type encodings.

(also, this causes `llvm-profdata` to crash - and it shouldn't crash even on corrupt/invalid DWARF (even though this is valid DWARF))

@ellishg Could you fix this? I'm happy to help/consult/explain what DWARFv5 looks like in this case.

**Comment by ellishg** [comment]
Thanks for investigating @dwblaikie. It looks like this can be fixed relatively easily. I'm also seeing the crash on the latest main and I can add more checks to gracefully fail instead of crashing.

**Comment by ellishg** [comment]
I've created https://reviews.llvm.org/D118098 which should fix this.
