### ISSUE TITLE
Migrate SparseTensor commandline options to enums

### ISSUE THREAD

**Issue by wrengr** [llvm/llvm-project#53389]
The SparseTensor passes currently use opaque numbers for the CLI, despite using an enum internally. So we should expose the enum names to the CLI. (See D117919 for slightly more discussion.)

**Comment by nkreeger** [comment]
Patch here: https://reviews.llvm.org/D123876

**Comment by nkreeger** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/30ceb783e232ff625cb25b9a264ae60519241f30
