### ISSUE TITLE
cpuid.h has incorrect value for bit_AVXVNNI

### ISSUE THREAD

**Issue by wch0x01** [llvm/llvm-project#53392]
Apologies if this has been addressed already.

In /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/cpuid.h
Leaf 7, subleaf 1, register EAX
#define bit_AVXVNNI       0x00000008

It should be
#define bit_AVXVNNI       0x00000010

According to
Intel 64 and IA-32 Architectures Software Developer's Manual
Volume 2 (2A, 2B, 2C, & 2D): Instruction SetReference, A-Z
325383-076US, December 2021
https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html

There are other bits in leaf 7 that should probably be defined for newer CPUs.

**Comment by RKSimon** [comment]
This was fixed in trunk at f6984b299afcbeddefe53db7ee1ce62e5d68cc4f

@phoebewang @topperc @tstellar  Is it too late to get this into 13.x do you think? The report was from a xcode toolchain so who knows if it'd even reach there tbh......

**Comment by phoebewang** [comment]
I support it if it's in time.

**Comment by RKSimon** [comment]
Tentatively closing this - its unlikely we'll see another 13.x general release now that 14.x development has started
