### ISSUE TITLE
Test producing different output after commit a7a2860d0eee37d9e0fd0b6a8e3d884f8ee4ec16

### ISSUE THREAD

**Issue by dyung** [llvm/llvm-project#53401]
A test in one of our internal test suites recently started failing due to different output being produced than was expected. I bisected the issue to commit a7a2860d0eee37d9e0fd0b6a8e3d884f8ee4ec16.

Here is a reduced test case:
```
extern "C" void printf(...);
void init(char pred, void *data, unsigned size) {
  unsigned char *bytes = (unsigned char *)data;
  for (unsigned i = 0; i != size; ++i)
    bytes[i] = pred + i;
}
typedef char schar;
typedef short __attribute__((ext_vector_type(2))) short2;
typedef schar __attribute__((ext_vector_type(2))) schar2;
typedef struct {
  int b;
} union_uint_int;
typedef struct {
  schar2 a;
} union_schar2_short;
typedef union {
  short2 a;
  int b;
} union_short2_int;
int main() {
  short2 id38647{(short)263526363}, id38653{(short)92147483648},
      id38654{(short)-1245903328};
  union_schar2_short id38652;
  id38652.a = 2;
  volatile short2 id38650(__builtin_convertvector(id38652.a, short2));
  short2 id38649(id38650 && id38653);
  short2 id38648(id38649 * id38654);
  short2 id38646(id38647 - id38648);
  union_short2_int id38656;
  union_uint_int id38658;
  init(97, &id38658, sizeof(id38658));
  id38656.b = id38658.b;
  short2 id38645(id38646 + id38656.a);
  printf("id38645:%x %x\n", id38645[0], id38645);
}
```
If compiled with `-O2 -mavx`, the output produced changes. Here is the output of a "good" compiler and what we expected:
```
$ ~/src/upstream/4c1dc65015ae8ba4b7e0ac56f4d88d29e712ce25-linux/bin/clang++ -O2 -mavx repro.cpp -o repro.good.out
$ ./repro.good.out
id38645:ffff805c 6463805c
```
But after a7a2860d0eee37d9e0fd0b6a8e3d884f8ee4ec16, the compiler is now producing the following:
```
$ ~/src/upstream/a7a2860d0eee37d9e0fd0b6a8e3d884f8ee4ec16-linux/bin/clang++ -O2 -mavx repro.cpp -o repro.bad.out
$ ./repro.bad.out
id38645:7a3c 64637a3c
```
@spatel-gh This was your commit, could you take a look?

**Comment by rotateright** [comment]
Thanks, @dyung! 
(I have both of those github IDs, but the rotateright account is where my commits were attributed, so I'm primarily using that.)
The transform in question appears to be correct in your example, so something else must be going wrong:
https://alive2.llvm.org/ce/z/RU8y_5

**Comment by rotateright** [comment]
It took me a while to narrow it down because the bug still happens with -O0 passed to the backend (llc), but this looks like a bug in codegen type legalization.

**Comment by rotateright** [comment]
Adding x86 label. Here's a reduction that shows the bug with llc:
```
@.str = private unnamed_addr constant [4 x i8] c"%x\0A\00", align 1

define noundef i32 @main() #0 {
  %two_short = alloca <2 x i16>, align 4
  store volatile <2 x i16> <i16 2, i16 2>, <2 x i16>* %two_short, align 4
  %two_short.0.two_short.0.two_short.0. = load volatile <2 x i16>, <2 x i16>* %two_short, align 4
  %cmp = icmp ne <2 x i16> %two_short.0.two_short.0.two_short.0., zeroinitializer
  %t0 = and <2 x i1> %cmp, <i1 true, i1 false>
  %sub3 = select <2 x i1> %t0, <2 x i16> <i16 2, i16 0>, <2 x i16> <i16 1, i16 0>
  %t1 = bitcast <2 x i16> %sub3 to i32
  call void (...) @printf(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i32 noundef %t1)
  ret i32 0
}

declare void @printf(...) local_unnamed_addr #1


```

**Comment by rotateright** [comment]
We get the right answer without sse4.1:
% llc 53401.ll -o - -O0 -mattr=ssse3 | clang -x assembler - && ./a.out
2
% llc 53401.ll -o - -O0 -mattr=sse4.1 | clang -x assembler - && ./a.out
1

**Comment by rotateright** [comment]
At legalized selection DAG, we have:
                  t92: v8i16 = X86ISD::ANDNP t69, t94
                t80: v8i16 = X86ISD::VSHLI t92, TargetConstant:i8<15>
              t81: v8i16 = X86ISD::VSRAI t80, TargetConstant:i8<15>
            t82: v16i8 = bitcast t81
          t85: v16i8 = vselect t82, t83, t84

But we kill the shifts:
Replacing.2 t81: v8i16 = X86ISD::VSRAI t80, TargetConstant:i8<15>
With: t92: v8i16 = X86ISD::ANDNP t69, t130

But that's a miscompile because we need the high bits to be set when the vselect becomes an x86 pblendvb.

**Comment by rotateright** [comment]
After much stepping through recursive calls into ComputeNumSignBits, I see a bug. We peek into a vector target constant and assume it has the same type as its load, but that's not always true:
` t108: i64 = X86ISD::WrapperRIP TargetConstantPool:i64<<4 x i32> <i32 1, i32 0, i32 0, i32 0>> 0`

The bug is visible in the clang 13 release and has been around since:
ad298f86b7ad2ab09a05 / https://reviews.llvm.org/D62777
...but it takes a long sequence of late-stage transforms to uncover the problem.

**Comment by RKSimon** [comment]
Thanks @rotateright !
