### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by beiyinghu** [llvm/llvm-project#53415]
how to delete the variable after the declaration
<img width="976" alt="截屏2022-01-26 下午2 35 13" src="https://user-images.githubusercontent.com/47131226/151116588-b2e403bf-27c5-4c00-bec6-fc75fdc06dca.png">

**Comment by medismailben** [comment]
AFAIK, you can't redeclare a persistante variable (i.e. to change it's type) but you can update its value:

```
(lldb) e int $foo = 5
(lldb) e $foo
(int) $foo = 5
(lldb) e int $foo = 32
error: expression failed to parse:
error: redefinition of persistent variable '$foo'
error: Internal error [IRForTarget]: Couldn't rewrite the creation of a persistent variable

(lldb) e $foo = 42
(int) $0 = 42
(lldb) e $foo 
(int) $foo = 42
(lldb) 
```

**Comment by jimingham** [comment]
We used to allow you to change the type of a convenience variable as well, but people felt that was confusing and could lead to unintentionally overwriting a variable, so lldb was changed to not allow that.

**Comment by phyBrackets** [comment]
It seems the question has been answered.
