### ISSUE TITLE
flang >=13 requires uuidgen to be installed

### ISSUE THREAD

**Issue by zerothi** [llvm/llvm-project#53418]
After having installed llvm 13.0.0 I keep getting errors with flang:
```shell
flang: line 338: uuidgen: command not found
```
I know this is a system command (https://man7.org/linux/man-pages/man1/uuidgen.1.html) but not all distro's has it installed by default.

Could you make a work-around for this, I have no idea whether it breaks stuff... :)

**Comment by kiranchandramohan** [comment]
This was observed before and the latest revision of the `flang` driver script errors out if there is no `uuidgen`. See https://reviews.llvm.org/D110694.

Since the `flang` script is a temporary driver, I don't think there are plans for improvements here.

**Comment by zerothi** [comment]
OK, fine. I searched issues here, but didn't find anything. Great it is resolved!
