### ISSUE TITLE
clang-12 generates wrong code for (uint8_t >> 8)

### ISSUE THREAD

**Issue by cyb70289** [llvm/llvm-project#53421]
See test code at https://godbolt.org/z/TzYWfcP1E
clang-11 and clang-13 generates correct code (return 2), but clang-12 is wrong (return 1). Looks it over optimized the code. There should be no UB in the code due to integer promotion.

**Comment by nikic** [comment]
The LLVM project only supports the latest release. As this works correctly in Clang 13, I don't believe there is anything to do here from our side?

**Comment by RKSimon** [comment]
AFAICT this was fixed in trunk by 6d949a9c8fa440b0b91c9a96a30a9b7c1b7cf1e1 (for 13.x and later) - as @nikic says we're not intending to backport any further patches to 12.x
