### ISSUE TITLE
Cannot create an object of a class having parent with protected destructor

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#53449]
This code
```
struct A {
protected:
  ~A() = default;
};

struct B : A {};
B b{};
```
fails in Clang with the error:
```
error: temporary of type 'A' has protected destructor
```
Demo: https://gcc.godbolt.org/z/ExvjPWhhj

**Comment by zero9178** [comment]
Interestingly, compilation succeeds when writing `B b;` instead of `B b{};`

**Comment by shafik** [comment]
I believe clang may be correct here [\[dcl.init\]/p9](http://eel.is/c++draft/dcl.init#aggr-9) says:

> The destructor for each element of class type is potentially invoked ([class.dtor]) from the context where the aggregate initialization occurs

and [\[dcl.init\]p2](http://eel.is/c++draft/dcl.init#aggr-2.2) says that the direct bases are elements:

>The elements of an aggregate are
> ...
> - for a class, the direct base classes in declaration order, followed by the direct non-static data members ([class.mem]) that are not members of an anonymous union, in declaration order.

and [\[class.dtor\]p15](http://eel.is/c++draft/class.dtor#15) says:

>A program is ill-formed if a destructor that is potentially invoked is deleted or not accessible from the context of the invocation.

**Comment by Fedr** [comment]
I see, thanks.

I was also pointed on a related discussion: https://stackoverflow.com/questions/56745324/temporary-of-type-a-has-protected-destructor-but-its-type-is-b

I think the issue can be closed, sorry for disturbing.
