### ISSUE TITLE
Missed optimization for value range of std::rand()

### ISSUE THREAD

**Issue by AMS21** [llvm/llvm-project#53452]
While watching Fedor Pikus talk on branchless programming from [cppcon2021](https://www.youtube.com/watch?v=g-WPhYREFjk) I've learned that nether clang nor gcc optimize the following examples.
1. Example [godbolt](https://godbolt.org/z/5hqx8o8nz)
```cpp
#include <cstdlib>

int main()
{
    return std::rand() >= 0;
}
```

2. Example [godbolt](https://godbolt.org/z/T51Eq76rP)
```cpp
#include <cstdlib>

int main()
{
    return std::rand() <= RAND_MAX;
}
```

Both of these cases should be possible to be optimized to simply
```asm
push rax
call rand
mov eax, 1
pop rcx
ret
```

Because as [cppreference](https://en.cppreference.com/w/cpp/numeric/random/rand) points out std::rand "returns a pseudo-random integral value between ​0​ and RAND_MAX (​0​ and RAND_MAX included)."

**Comment by njames93** [comment]
`std::rand` has side_effects so this would be a dangerous optimization
"Each time rand() is seeded with std::srand(), it must produce the same sequence of values on successive **calls.**"

The best you could realistically get would be
```asm
push rax
call rand
mov eax, 1
pop rcx
ret
```

**Comment by AMS21** [comment]
Good point. I've updated the post

**Comment by nunoplopes** [comment]
I'm closing this as I don't think we should spend time fixing this.
Sure, we could implement this optimization, and it's not even hard. But would it trigger in the real world? No!
The number of possible optimizations is infinite, so we need to focus on the ones that matter.

**Comment by njames93** [comment]
Closing point, the <= RAND_MAX case would be impossible to optimise as it's an implementation defined constant that's only guaranteed to be at least 0X7FFF. As it's defined as a macro, once LLVM sees it, it wouldn't know that the constant refers to RAND_MAX
