### ISSUE TITLE
[AVR] Support avrtiny devices

### ISSUE THREAD

**Issue by benshi001** [llvm/llvm-project#53459]
Some jobs needed for avrtiny:

1. Clang ABI for avrtiny: https://gcc.gnu.org/wiki/avr-gcc#Reduced_Tiny
2. Mark R0~R15 are reserved in `BitVector AVRRegisterInfo::getReservedRegs(const MachineFunction &MF)`
3. There are many hard coded use of R1 and R0 everywhere, which should be changed to 
```
Register getRegZero(void) { return avrtiny ? R17 : R1; }
Register getRegTemp(void) { return avrtiny ? R16 : R0; }
```
4. The assembler should deny r0-r15.
5. The available registers for passing arguments in AVRISelLowering.cpp should be truncated to `AVR::R18`.
```
static const MCPhysReg RegList8[] = {
    AVR::R25, AVR::R24, AVR::R23, AVR::R22, AVR::R21, AVR::R20,
    AVR::R19, AVR::R18, AVR::R17, AVR::R16, AVR::R15, AVR::R14,
    AVR::R13, AVR::R12, AVR::R11, AVR::R10, AVR::R9,  AVR::R8};
```

**Comment by benshi001** [comment]
Currently command `clang xx.c --target=avr -mmcu=attiny40` leads to wrong assembly generated.

**Comment by benshi001** [comment]
There is partial fix: https://reviews.llvm.org/D121672

**Comment by benshi001** [comment]
The above partial fix is committed as https://github.com/llvm/llvm-project/commit/f319c24570f93c8a5a4401768b3ecfba9ef2fdba

**Comment by benshi001** [comment]
The crash is caused by

```
--- a/clang/lib/CodeGen/CGVTables.cpp
+++ b/clang/lib/CodeGen/CGVTables.cpp
@@ -808,8 +808,11 @@ void CodeGenVTables::addVTableComponent(ConstantArrayBuilder &builder,
       return addRelativeComponent(
           builder, fnPtr, vtableAddressPoint, vtableHasLocalLinkage,
           component.getKind() == VTableComponent::CK_CompleteDtorPointer);
-    } else
-      return builder.add(llvm::ConstantExpr::getBitCast(fnPtr, CGM.Int8PtrTy));
+    } else {
+      unsigned AS = CGM.getDataLayout().getProgramAddressSpace();
+      return builder.add(llvm::ConstantExpr::getBitCast(
+          fnPtr, CGM.Int8PtrTy->getPointerTo(AS)));
+    }
   }
```

The `fnPtr` has `addrspace(1)` while `CGM.Int8PtrTy` has `addrspace(0)`.

**Comment by benshi001** [comment]
> 2\. getReservedRegs

It seems all these 5 initial points have been implemented in the main branch. But there are still many spots need to be removed. Some invalid instructions are still emitted on AVRTiny.

**Comment by benshi001** [comment]
> Some jobs needed for avrtiny:
> 
> 1. Clang ABI for avrtiny: https://gcc.gnu.org/wiki/avr-gcc#Reduced_Tiny
> 2. Mark R0~R15 are reserved in `BitVector AVRRegisterInfo::getReservedRegs(const MachineFunction &MF)`
> 3. There are many hard coded use of R1 and R0 everywhere, which should be changed to
> 
> ```
> Register getRegZero(void) { return avrtiny ? R17 : R1; }
> Register getRegTemp(void) { return avrtiny ? R16 : R0; }
> ```
> 
> 4. The assembler should deny r0-r15.
> 5. The available registers for passing arguments in AVRISelLowering.cpp should be truncated to `AVR::R18`.
> 
> ```
> static const MCPhysReg RegList8[] = {
>     AVR::R25, AVR::R24, AVR::R23, AVR::R22, AVR::R21, AVR::R20,
>     AVR::R19, AVR::R18, AVR::R17, AVR::R16, AVR::R15, AVR::R14,
>     AVR::R13, AVR::R12, AVR::R11, AVR::R10, AVR::R9,  AVR::R8};
> ```

It seems all these 5 initial points have been implemented in the main branch. But there are still many spots need to be removed. Some invalid instructions are still emitted on AVRTiny.

**Comment by aykevl** [comment]
> But there are still many spots need to be removed. Some invalid instructions are still emitted on AVRTiny.

Can you give an example? When I tested my last patch I didn't see any incorrect instructions (but I could have missed some of course).

**Comment by benshi001** [comment]
> > But there are still many spots need to be removed. Some invalid instructions are still emitted on AVRTiny.
> 
> Can you give an example? When I tested my last patch I didn't see any incorrect instructions (but I could have missed some of course).

Sorry, it is my mistake to make that conclusion. I mean, the assembly generated on AVRTiny need further optimization. I often see longer assembly for AVRTiny than AVR, such as https://github.com/llvm/llvm-project/blob/main/llvm/test/CodeGen/AVR/return.ll.

If you think the correctness for AVRTiny has already been resolved, you can close this issue, and we can create another issue to track AVRTiny's code optimization.

**Comment by aykevl** [comment]
> Sorry, it is my mistake to make that conclusion. I mean, the assembly generated on AVRTiny need further optimization. I often see longer assembly for AVRTiny than AVR, such as https://github.com/llvm/llvm-project/blob/main/llvm/test/CodeGen/AVR/return.ll.

Ah I understand. Yeah, it produces really long code currently. This is also something I'd like to investigate some day. Can't promise anything.

But yes, it appears to produce correct code. I'll close it now, I guess we can create new issues if there are still bugs.

**Comment by aykevl** [comment]
I have some ideas how code quality can be improved, but I need to prove them first. They may result in large changes.
