### ISSUE TITLE
clang++ failure with "-Wreserved-identifier"

### ISSUE THREAD

**Issue by shrek1402** [llvm/llvm-project#53464]
```
namespace mi {
  // Переводит КилоБайты в Байты
  constexpr unsigned long long operator"" _kb(const unsigned long long n_kilobytes) {
    return n_kilobytes * 1024;
  }
}
```

`clang++ -std=c++17 -Weverything main.cpp`
`error: identifier '_kb' is reserved because it starts with '_' at global scope [-Werror,-Wreserved-identifier]`

For me, this error looks strange because the declaration is not in the global space and because the literal operator can only start with `'_'`. I'm in a desperate situation.

**Comment by AaronBallman** [comment]
This was fixed during Clang 14, so closing as WORKSFORME.
