### ISSUE TITLE
codegen crash handling zero-sized byref arguments

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5346]
|  |  |
| --- | --- |
| Bugzilla Link | [4974](https://llvm.org/bz4974) |
| Version | trunk |
| OS | All |
| Attachments | [failing input](https://user-images.githubusercontent.com/60944935/143739899-2fa1efe0-bb53-4259-a9a6-11aedf6d41fc.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@sunfishcode |

## Extended Description 
ddunbar@giles:tmp$ cat t.ll
; ModuleID = 'inputs/test.2.b.c'
target datalayout = "e-p:32:32:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-i64:32:32-f32:32:32-f64:32:32-v64:64:64-v128:128:128-a0:0:32"
target triple = "thumbv7-apple-darwin9.3.0"

%0 = type <{ [0 x i32] }>
%struct.T0 = type { }

@.str = private constant [25 x i8] c"fn2: testing arguments.\0A\00" ; <[25 x i8]*> [#uses=1]
@&#8203;T0_values = internal global [1 x %struct.T0] zeroinitializer, align 1 ; <[1 x %struct.T0]*> [#uses=2]

define arm_apcscc void @&#8203;test_fn2() nounwind {
entry:
  %agg.tmp = alloca %struct.T0                    ; <%struct.T0*> [#uses=2]
  %call = call arm_apcscc  i32 (i8*, ...)* @&#8203;printf(i8* getelementptr inbounds ([25 x i8]* @.str, i32 0, i32 0)) ; <i32> [#uses=0]
  %tmp = bitcast %struct.T0* %agg.tmp to i8*      ; <i8*> [#uses=1]
  call void @&#8203;llvm.memcpy.i32(i8* %tmp, i8* bitcast ([1 x %struct.T0]* @&#8203;T0_values to i8*), i32 0, i32 1)
  %0 = bitcast %struct.T0* %agg.tmp to %0*        ; <%0*> [#uses=1]
  %1 = load %0* %0, align 1                       ; <%0> [#uses=1]
  call arm_apcscc  void @&#8203;fn2(%0 %1)
  ret void
}

declare arm_apcscc i32 @&#8203;printf(i8*, ...)

declare arm_apcscc void @&#8203;fn2(%0)

declare void @&#8203;llvm.memcpy.i32(i8* nocapture, i8* nocapture, i32, i32) nounwind
ddunbar@giles:tmp$ llc < t.ll
	.syntax unified
Assertion failed: (InReg && "Value not in map!"), function getValue, file /Volumes/Data/Users/ddunbar/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuild.cpp, line 933.
0   llc               0x0000000100b73187 PrintStackTrace(void*) + 38
1   llc               0x0000000100b73715 SignalHandler(int) + 336
2   libSystem.B.dylib 0x00007fff8726214a _sigtramp + 26
3   libSystem.B.dylib 0x00007fff00000000 _sigtramp + 2027544272
4   libSystem.B.dylib 0x00007fff872de104 __pthread_markcancel + 0
5   llc               0x00000001007a4d4e llvm::SelectionDAGLowering::getValue(llvm::Value const*) + 4080
6   llc               0x00000001007a9bb0 llvm::SelectionDAGLowering::LowerCallTo(llvm::CallSite, llvm::SDValue, bool, llvm::MachineBasicBlock*) + 304
7   llc               0x00000001007baba9 llvm::SelectionDAGLowering::visitCall(llvm::CallInst&) + 3167
8   llc               0x00000001007c676a llvm::SelectionDAGLowering::visit(unsigned int, llvm::User&) + 1242
9   llc               0x00000001007c682e llvm::SelectionDAGLowering::visit(llvm::Instruction&) + 44
10  llc               0x00000001007dffb8 llvm::SelectionDAGISel::SelectBasicBlock(llvm::BasicBlock*, llvm::ilist_iterator<llvm::Instruction>, llvm::ilist_iterator<llvm::Instruction>) + 96
11  llc               0x00000001007e0b8b llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function&, llvm::MachineFunction&, llvm::MachineModuleInfo*, llvm::DwarfWriter*, llvm::TargetInstrInfo const&) + 2439
12  llc               0x00000001007e1a30 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) + 982
13  llc               0x00000001008a8a59 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) + 83
14  llc               0x0000000100af229b llvm::FPPassManager::runOnFunction(llvm::Function&) + 341
15  llc               0x0000000100af2889 llvm::FunctionPassManagerImpl::run(llvm::Function&) + 111
16  llc               0x0000000100af2a38 llvm::FunctionPassManager::run(llvm::Function&) + 112
17  llc               0x000000010002f458 main + 3233
18  llc               0x000000010002e0a8 start + 52
Stack dump:
0.	Program arguments: llc 
1.	Running pass 'ARM Instruction Selection' on function '@test_fn2'
Abort trap

**Comment by gwelymernans** [comment]
Updating the example for today's syntax, it no longer crashes:

```
$ cat pr.ll
; ModuleID = 'inputs/test.2.b.c'
target datalayout = "e-p:32:32:32-i1:8:32-i8:8:32-i16:16:32-i32:32:32-i64:32:32-f32:32:32-f64:32:32-v64:64:64-v128:128:128-a0:0:32"
target triple = "thumbv7-apple-darwin9.3.0"

%0 = type <{ [0 x i32] }>
%struct.T0 = type { }

@.str = private constant [25 x i8] c"fn2: testing arguments.\0A\00" ; <[25 x i8]> [#uses=1]
@T0_values = internal global [1 x %struct.T0] zeroinitializer, align 1 ; <[1 x %struct.T0]> [#uses=2]

define arm_apcscc void @test_fn2() nounwind {
entry:
        %agg.tmp = alloca %struct.T0
        %call = call arm_apcscc i32 (i8*, ...) @printf(i8* getelementptr inbounds ([25 x i8], [25 x i8]* @.str, i32 0, i32 0))
        %tmp = bitcast %struct.T0* %agg.tmp to i8*
        call void @llvm.memcpy.p0i8.p0i8.i32(i8* %tmp, i8* bitcast ([1 x %struct.T0]* @T0_values to i8*), i32 0, i1 false)
        %0 = bitcast %struct.T0* %agg.tmp to %0*
        %1 = load %0, %0* %0, align 1
        call arm_apcscc void @fn2(%0 %1)
        ret void
}

declare arm_apcscc i32 @printf(i8*, ...)

declare arm_apcscc void @fn2(%0)

declare void @llvm.memcpy.p0i8.p0i8.i32(i8* nocapture, i8* nocapture, i32, i1) nounwind

$ llc < pr.ll
	.section	__TEXT,__text,regular,pure_instructions
	.macosx_version_min 10, 5
	.syntax unified
	.globl	_test_fn2                       @ -- Begin function test_fn2
	.p2align	1
	.code	16                              @ @test_fn2
	.thumb_func	_test_fn2
_test_fn2:
@ %bb.0:                                @ %entry
	str	lr, [sp, #-4]!
	sub	sp, #4
	movw	r0, :lower16:(l_.str-(LPC0_0+4))
	movt	r0, :upper16:(l_.str-(LPC0_0+4))
LPC0_0:
	add	r0, pc
	bl	_printf
	bl	_fn2
	add	sp, #4
	ldr	lr, [sp], #4
	bx	lr
                                        @ -- End function
	.section	__TEXT,__const
	.p2align	4                               @ @.str
l_.str:
	.asciz	"fn2: testing arguments.\n"

.zerofill __DATA,__bss,_T0_values,1,0   @ @T0_values
.subsections_via_symbols
```
