### ISSUE TITLE
windows release13.0.0: missing llvm-pdbutil in package

### ISSUE THREAD

**Issue by yuanfang-chen** [llvm/llvm-project#53461]

**Comment by aganea** [comment]
Agreed, this is a bit annoying. @zmodem is this on intent?

**Comment by zmodem** [comment]
The intent is to include only "toolchain tools" (clang, lld, etc.) and not "llvm internal tools" (opt, llc, etc.).

I suppose for llvm-pdbutil the category isn't entirely clear. But I can see it's useful not just for llvm devs, so let's add it: https://reviews.llvm.org/D118606
