### ISSUE TITLE
Elide printing attribute fields when value is set to default.

### ISSUE THREAD

**Issue by MaheshRavishankar** [llvm/llvm-project#53476]
I have an attribute defined as 

```
def FooAttr : AttrDef<MyDialect, "foo", []> {
  ....
  let parameters = (ins
    AttrParamater<"ArrayAttr", "">:$f1;
    AttrParameter<"ArrayAttr", "">:$f2;
  )
  ...
  let assemblyFormat = [{
    `<` `f1` `=` $f1 `,` `f2` `=` $f2 `>`
  }]
}
```

`f1` is an `ArrayAttr` of `ArrayAttr` of `IntegerAttr`s, and `f2` is an `ArrayAttr` of `IntegerAttr`. They have default values of `{}` and `{}` (i.e. empty). What would be the recommended way to not print `f1` or `f2` if their values are the default values.

**Comment by Mogball** [comment]
https://reviews.llvm.org/D118544

**Comment by MaheshRavishankar** [comment]
> [reviews.llvm.org/D118544](https://reviews.llvm.org/D118544)
> 
> Introduces default-valued parameters (after a dependent patch that introduces the notion optional parameters), with full support in assembly formats.

Thanks Jeff. Been tracking that patch. I dont have comments, but looking forward for this to land.

**Comment by Mogball** [comment]
Close by 761bc83af4ee70c6c5156f73ed88947a5d9f013f
