### ISSUE TITLE
ROCm integration tests failing in the presense of multiple kernels

### ISSUE THREAD

**Issue by krzysz00** [llvm/llvm-project#53475]
https://github.com/llvm/llvm-project/blob/main/mlir/test/Integration/GPU/ROCM/two-modules.mlir and https://github.com/llvm/llvm-project/blob/main/mlir/test/Integration/GPU/ROCM/vector-transferops.mlir , which are distinguished from the other tests in that batch by having more than one kernel present, fail with errors such as the following

```
ld.lld: error: section: .dynamic is not contiguous with other relro sections
ld.lld: error: section .text virtual address range overlaps with .rodata
>>> .text range is [0x1600, 0x1627]
>>> .rodata range is [0x1600, 0x163F]

ld.lld: error: section .text load address range overlaps with .rodata
>>> .text range is [0x1600, 0x1627]
>>> .rodata range is [0x1600, 0x163F]
<unknown>:0: error: lld invocation error
```

(for the above failures, `%chip` is `gfx908`).

@aganea since you were on the other LLD change that broke us and might know more about how this happened - if I've @-ed the wrong person, apologies.

**Comment by aganea** [comment]
This is more @MaskRay's expertise.

**Comment by krzysz00** [comment]
@aganea This seems to be yours, https://github.com/ROCmSoftwarePlatform/D108850-lld-bug-reproduction showed that the commit that makes LLD have less global state was the problem

**Comment by aganea** [comment]
Thanks for the detailed report, I will take a look and report back.

**Comment by aganea** [comment]
@krzysz00 Ah I see the problem. I didn't know that you were calling the `lld::elf::link` several times in the MLIR code. I'm not sure the ELF driver is ready for that yet - @MaskRay. My patch is only providing a cornerstone for multi-call in lldCommon; more work is then needed in the respective drivers to make them safe, see for example https://reviews.llvm.org/D110450 for the COFF side. (after that patch, another one will be needed to make ThinLTO work for COFF in this multi-call scenarios).

Also you should go through the `lld::safeLldMain()` API and you *must* check the return value see if further calls are possible. There are currently some issues in ELF (try running ELF unittests with LLD_IN_TEST=2, see `lld/test/ELF/invalid/symtab-sh-info.s`) where memory corruption can occur. For an explanation see https://reviews.llvm.org/D88348.

**Comment by aganea** [comment]
Just for demonstration purposes the following works: [use_safe_call.zip](https://github.com/llvm/llvm-project/files/7991140/use_safe_call.zip)

Should we create another .lib (lldLib) that only has everything in `lld/tools/lld/lld.cpp` but `main()`? Do you only need ELF or other drivers as well? This wasn't quite ready for prime-time. Or I guess I can try to re-structure the drivers' code as it was before to make things work for LLVM 14? (not quite happy with this option, but I understand if you have a need for that) Please let me know.

**Comment by krzysz00** [comment]
We need to be able to, by some means, perform actions equivalent to `lld -shared <some object file from mc> -o <somewhere>`, but we don't have the requirement these be files - heck, if we could have those be in-memory buffers it might be nice. And this is ELF only.

This is because the HIP runtime expects GPU kernels to be packaged in an ELF shared library.

**Comment by krzysz00** [comment]
The in-real-code context is https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/GPU/Transforms/SerializeToHsaco.cpp#L441 , which can be called arbitrarily many times within a single process.

**Comment by aganea** [comment]
It this code on a critical path? Can the call to `lld::elf::link` be replaced by a system call to ld.lld like @MaskRay has suggested in the past? I think that'd be the easiest for 14.0. After, we can make a better change.

**Comment by krzysz00** [comment]
We could probably replace this by a process spawn for the moment.

This code is invoked every time we compile a GPU kernel for an AMD GPU. I wouldn't say it's a particularly hot path - the kernels themselves are - but it does need to work.

**Comment by krzysz00** [comment]
Further notes: no, we can't call `lld` as a separate binary. That would prevent us from bundling the entire system up into a single `.a`, which is a requirement for some clients.

**Comment by aganea** [comment]
That's what I thought, it would introduce a new dependency. I'll fix the exiting lib use-case. Sorry for the delay, I was busy with other things.

**Comment by MaskRay** [comment]
Thanks to @aganea for working on this. I agree that lld/ELF is not ready for library usage.

It is unsupported and may happen to work for some use cases. But please move away from the library usage, or expect that it may break at any time, and don't use "it worked for some time for us" as an argument for reverts like https://reviews.llvm.org/D119257

**Comment by joker-eph** [comment]
I believe we will have to live with revert like the one above until you collaborate actively to find a supported way and move there though.
Just asking "please move away from the library usage" alone won't be enough.

**Comment by krzysz00** [comment]
We can't spawn `lld` as a subprocess due to customer requirements around having the kernel generator/compiler delivered as a static library in some cases. (And there's LLVM version compatibility concerns, but those might be less of an issue in this case)

**Comment by MaskRay** [comment]
> I believe we will have to live with revert like the one above until you collaborate actively to find a supported way and move there though. Just asking "please move away from the library usage" alone won't be enough.

There is work fixing this particular issue. I think this attitude against the unsupported usage is fine.

Then how can we prevent unsupported in-tree usage from creeping in? There is no visibility attribute that we can use to stop in-tree users from adding unsupported dependencies. Now I spot this usage and I can report the issue.

We don't want to move headers from public to private just to stop such usage. If some use cases work with the public APIs, I want that they keep working. Being in-tree should not automatically grant them SLA (if we consider maintaining the linker as a service) if they have unsupported usage.

**Comment by MaskRay** [comment]
> We can't spawn `lld` as a subprocess due to customer requirements around having the kernel generator/compiler delivered as a static library in some cases. (And there's LLVM version compatibility concerns, but those might be less of an issue in this case)

Can the `lld` executable be bundled in your distribution? The LLVM version compatibility concern does not apply if you bundle the relevant executables requiring version locking.

For example, a Clang distribution ships Clang resource directory and sometimes a bunch of PGO/sanitizer/XRay/etc runtime files/ignorelists. The runtime files are version locked with the compiler. The recent clang-offload-bundler may be another example.

lld/ELF is still far away from we can comfortably say "the library usage is now supported". Contributions making it better suited for library usage is welcome, but I don't want them to be hassled with "we have unsupported lld::elf::link usage disturbed by your change, we need to revert your change".

**Comment by aganea** [comment]
This whole thing has been discussed many times in the past. I find it's hard for contributors to support all possible end-user/developers/downstream use-cases. The main issue here is that there's no out-of-the-box coverage -- one needs to have the AMD ROC libs to compile & exercise this code, and that only works on Linux. A bot and tests in MLIR would certainly help for visibility.

**Comment by krzysz00** [comment]
I'm actively looking into adding a `mlir-amd` buildbot and I'll try and get it done sooner rather than later.

**Comment by krzysz00** [comment]
Both due to the workaround landing and since we've found a better long-term solution, closing
