### ISSUE TITLE
function defined but not used.

### ISSUE THREAD

**Issue by phyBrackets** [llvm/llvm-project#53487]
https://github.com/llvm/llvm-project/blob/fcd8817da509f0b5dfbc7014f288ab7a5b69f28b/llvm/lib/CodeGen/MLRegallocEvictAdvisor.cpp#L483 
This function defined here but it is not used anywhere . I'm not sure if this function trigger at the time of build or something.

**Comment by phyBrackets** [comment]
Sorry, It looks like this is specific to development . 
`// ===================================
// Development mode-specifics
// ===================================
//
// Features we log`  
But would anyone tell me that how this gonna work?

**Comment by ksyx** [comment]
Not too familiar with this part of code and looked too deep into it, but it seems it is a constructor parent(super) class of another class whose constructor is used.
https://github.com/llvm/llvm-project/blob/bc3b372161716a4c4845d47a877e4892df0d08da/llvm/lib/CodeGen/MLRegallocEvictAdvisor.cpp#L230-L232
https://github.com/llvm/llvm-project/blob/bc3b372161716a4c4845d47a877e4892df0d08da/llvm/lib/CodeGen/MLRegallocEvictAdvisor.cpp#L365-L371
https://github.com/llvm/llvm-project/blob/52a1346b78b0971b6a89c53a6881cb9655e81245/llvm/lib/CodeGen/MLRegallocEvictAdvisor.cpp#L460-L462

Hope this helps :)
