### ISSUE TITLE
If CMAKE_LINKER is set to `ld64.lld` the version passed to -mlinker-version gives an error

### ISSUE THREAD

**Issue by tru** [llvm/llvm-project#53498]
This is related to 13.0.1-rcX but I checked the `main` branch and the logic seems the same.

I build a two stage compiler on macOS and use LLD to link the second stage. This leads to the following error when trying to use the second stage:

```
clang-13: error: invalid version number in '-mlinker-version=64.'
```

I digged and it seems like the clang cmakefile detects the linker version here: https://github.com/llvm/llvm-project/blob/main/clang/CMakeLists.txt#L406

which end's up failing but makes HOST_LINK_VERSION `64` with lld as `CMAKE_LINKER`.

I see two fixes:
1) Change clang's cmake file to properly detect when lld is passed as the linker and set HOST_LINK_VERSION to the version of LLVM at this point or we change it to always use the host linker when detecting HOST_LINK_VERSION
2) change the clang driver to accept this version - I am unsure how this is used later in the driver and if it actually makes any special decisions based on this.

Happy to write a patch if I can get some feedback on what a proper solution would be.

**Comment by sztomi** [comment]
I think this is resolved by https://github.com/llvm/llvm-project/commit/c624cc252738c30ada3f00a498e971a7a3a84196

**Comment by tru** [comment]
Correct!
