### ISSUE TITLE
[TBAA] TBAA information dropped for memcpy/memmove/memset

### ISSUE THREAD

**Issue by wsmoses** [llvm/llvm-project#53506]
Fixed by `8cb9c7360944b1e4dd2e8125a48ede3628b459f1`

/cherry-pick 8cb9c7360944b1e4dd2e8125a48ede3628b459f1

@tstellar can we backport this to 13.x

**Comment by nikic** [comment]
I don't think this should be backported. Unless I'm missing something, this is a pure feature addition, and a risky one at that.

**Comment by wsmoses** [comment]
This does break codebases (like Enzyme: https://github.com/wsmoses/Enzyme) which partially rely on TBAA information, which is eliminated during the loopidiompass. The code/test case works on LLVM7-14, excluding 13 so it would be nice to have this backported.

**Comment by fhahn** [comment]
> This does break codebases

What does "break" mean here? It might be helpful to provide a bit more context.
