### ISSUE TITLE
Possible bug when using convert-std-to-llvm=emit-c-wrappers when function has argument attributes

### ISSUE THREAD

**Issue by srcarroll** [llvm/llvm-project#53503]
I'm not sure if this is a bug, or it's expected behavior and my input IR is not appropriate.

Suppose I have the following IR in test.mlir
```
module {
  func @main(%arg0: memref<1xi32> {test.test}, %arg1: memref<2xf32>) -> (memref<f32>) {
    %0 = memref.alloc() : memref<f32>
    return %0 : memref<f32>
  }
```

and I run
```
mlir-opt test.mlir --convert-std-to-llvm=emit-c-wrappers
```
I get the following error
```
'llvm.func' op expects argument attribute array `arg_attrs` to have the same number of elements as the number of function arguments, got 2, but expected 3
```

My hypothesis is that the `arg_attrs` attribute is not being updated/set correctly when creating the C wrapper function.  What's happening is that the wrapper function's arguments consists of the union of the original functions input arguments and the return arguments.  So the number of arguments changes.  However, after printing some stuff for debugging in `wrapForExternalCallers` (https://github.com/llvm/llvm-project/blob/main/mlir/lib/Conversion/StandardToLLVM/StandardToLLVM.cpp#L73) I found that the number of arg attrs for `wrapperFuncOp` is the same as `funcOp`, when the list really should have increased in size to take into account the new input arguments coming from the return of the original function.  For my mlir file, printing out arg_attrs for `wrapperFuncOp` shows `arg_attrs = [{test.test}, {}]`

Besides printing, I've found support for this hypothesis by verifying that returning nothing works fine with `emit-c-wrappers`
```
module {
  func @main(%arg0: memref<1xi32> {test.test}, %arg1: memref<2xf32>) {
    return
  }
  ```
I've also verified that not having an attribute for some arguments is fine too since, when any arg attributes are present, empty attributes get added to correspond to arguments without attributes.

Any thoughts?  Thanks in advance.

**Comment by joker-eph** [comment]
> My hypothesis is that the arg_attrs attribute is not being updated/set correctly when creating the C wrapper function. 

It seems you're absolutely right! We should likely propagate the attributes to the individual "expanded" individual new args in the process.

**Comment by joker-eph** [comment]
@srcarroll let us know if you intend to try to fix this?

**Comment by srcarroll** [comment]
I already started looking into this. I just need to confirm with my manager at work that it will be OK to push (I found this bug while working on my work machine).

**Comment by srcarroll** [comment]
There is one issue I'm having trouble with that maybe someone can point me in the right direction.  I'm not really sure how to add `{}` to an `ArrayAttr`.  For example if I start with `arg_attrs = [{test.test}]` how would I append to get `arg_attrs = [{test.test}, {}]`.  Thanks

**Comment by joker-eph** [comment]
ArrayAttr is a fixed-size array of Attributes. The way to expand it is to turn it into a `SmallVector<Attribute>`, mutate the vector, and then create a new `ArrayAttr`.

That said there are helper functions to manipule function arguments attributes in `include/mlir/IR/FunctionInterfaces.h` and `include/mlir/IR/FunctionInterfaces.td`

**Comment by srcarroll** [comment]
Right.  Sorry, I wasn't clear.  That's what I'm trying to do.  The problem is I don't know what `{}` is in terms of an element of `SmallVector<Attribute>`. Or in other words I don't know how to create a `{}` `Attribute`.  It's hard for me to find directly, and everything I try that I think might work just results in a null attribute.

I'll take a look at the helper functions.

**Comment by joker-eph** [comment]
Ah I see: isn't a null Attribute just suitable here?

**Comment by srcarroll** [comment]
I'm not sure actually.  Obviously, somewhere these `{}` (sorry I don't know what name to call these) get added when some function arguments don't have attributes.  I just can't find where this is done.  I'm mainly just trying to be consistent with this format.

When I use `dump()` on `arg_attrs` that already have this, they show up as `{}`.  However my version shows up as `<<NULL ATTRIBUTE>>` in the printout

**Comment by joker-eph** [comment]
An empty `DictionaryAttr` will get you this, but the code to access the argument attributes is tolerant to an empty entry in the array so I wasn't sure about the expectations!
I won't hurt if you use an empty DictionaryAttr I think...

**Comment by srcarroll** [comment]
I was trying that before and I still got NULL ATTRIBUTE.  But I naively tried it using something like `DictionaryAttr emptyDictAttr = {}` or `DictionaryAttr()`.  I did see there is a `DictionaryAttr::getEmpty`, but it is a private function.  My understanding is that passing an `MLIRContext` will make it accessible, but I haven't found the right context yet.  Although I have some experience with MLIR, I'm still new enough to struggle with subtle things like this sometimes.

**Comment by joker-eph** [comment]
You can get the context from any piece of IR you have at hand. If you are in a function creating IR "ex-nihilo" you need the context explicitly passed in, but that's fairly rare.
Instead any existing attribute has a `getContext()` method, similarly for `Type` and `Operation`.

You'll get the empty dictionary with `DictionaryAttr::get(entity.getContext())`

**Comment by srcarroll** [comment]
I have access to a `FuncOp` and `OpBuilder`.  I would think one of these would suffice but trying to get context from either gives the error
```error: ‘static mlir::DictionaryAttr mlir::DictionaryAttr::getEmpty(mlir::MLIRContext*)’ is private within this context```.

**Comment by joker-eph** [comment]
Are you trying to call `getEmpty()`? You need to call `get` as I mentioned above: `DictionaryAttr::get(funcOp.getContext())`

**Comment by joker-eph** [comment]
See for example this call: https://github.com/llvm/llvm-project/blob/e188aae406f3fecaed65a1f7e6562205f0de937e/mlir/lib/IR/FunctionInterfaces.cpp#L53-L54

Which is anecdotally in the help function to manipulate function argument attributes :)

**Comment by srcarroll** [comment]
Oh my mistake.  For some reason I read your `get` as `getEmpty`.  I'm also a little out of date because my version doesn't have `FunctionInterfaces.cpp`.  But the suggestion works perfectly.  Thanks for the help!

**Comment by srcarroll** [comment]
Actually, something just occurred to me.  I have not taking into account when a function has multiple returns.  Am I correct that any time there are multiple returns (whether they are memref or not), the returns become wrapped into a single function arg?  If so, how are the result attributes intended to be used in this case?  I assume that they get all get combined into a single DictionaryAttr, but wanted to double check here.

**Comment by srcarroll** [comment]
So it turns out that `res_attrs` did indeed get propagated.  I just had a little bug where the format wasn't quite right.  This took me a while to figure out because I thought I was using the same attributes for both the wrapper function and new function, and it printed out fine for the former.

After discussing with a coworker, we came to the conclusion that my original idea for combining the result attributes together wasn't quite appropriate because it wouldn't retain the relationship between each result and their corresponding attribute.  So we opted to place all result attributes into an array and create a new DictionaryAttr with key "llvm.struct_attrs", and value the array.  Here is the resulting IR after this change (same input IR)

```
module attributes {llvm.data_layout = ""} {
  llvm.func @main(%arg0: !llvm.ptr<f32> {test.argOne}, %arg1: !llvm.ptr<f32> {test.argOne}, %arg2: i64 {test.argOne}, %arg3: f32) -> (!llvm.struct<(struct<(ptr<f32>, ptr<f32>, i64)>, struct<(ptr<i32>, ptr<i32>, i64)>)> {llvm.struct_attrs = [{test.returnOne}, {test.returnTwo}]}) {
    %0 = memref.alloc() : memref<f32>
    %1 = builtin.unrealized_conversion_cast %0 : memref<f32> to !llvm.struct<(ptr<f32>, ptr<f32>, i64)>
    %2 = memref.alloc() : memref<i32>
    %3 = builtin.unrealized_conversion_cast %2 : memref<i32> to !llvm.struct<(ptr<i32>, ptr<i32>, i64)>
    %4 = llvm.mlir.undef : !llvm.struct<(struct<(ptr<f32>, ptr<f32>, i64)>, struct<(ptr<i32>, ptr<i32>, i64)>)>
    %5 = llvm.insertvalue %1, %4[0] : !llvm.struct<(struct<(ptr<f32>, ptr<f32>, i64)>, struct<(ptr<i32>, ptr<i32>, i64)>)>
    %6 = llvm.insertvalue %3, %5[1] : !llvm.struct<(struct<(ptr<f32>, ptr<f32>, i64)>, struct<(ptr<i32>, ptr<i32>, i64)>)>
    llvm.return %6 : !llvm.struct<(struct<(ptr<f32>, ptr<f32>, i64)>, struct<(ptr<i32>, ptr<i32>, i64)>)>
  }
  llvm.func @_mlir_ciface_main(%arg0: !llvm.ptr<struct<(struct<(ptr<f32>, ptr<f32>, i64)>, struct<(ptr<i32>, ptr<i32>, i64)>)>> {llvm.struct_attrs = [{test.returnOne}, {test.returnTwo}]}, %arg1: !llvm.ptr<struct<(ptr<f32>, ptr<f32>, i64)>> {test.argOne}, %arg2: f32) {
    %0 = llvm.load %arg1 : !llvm.ptr<struct<(ptr<f32>, ptr<f32>, i64)>>
    %1 = llvm.extractvalue %0[0] : !llvm.struct<(ptr<f32>, ptr<f32>, i64)>
    %2 = llvm.extractvalue %0[1] : !llvm.struct<(ptr<f32>, ptr<f32>, i64)>
    %3 = llvm.extractvalue %0[2] : !llvm.struct<(ptr<f32>, ptr<f32>, i64)>
    %4 = llvm.call @main(%1, %2, %3, %arg2) : (!llvm.ptr<f32>, !llvm.ptr<f32>, i64, f32) -> !llvm.struct<(struct<(ptr<f32>, ptr<f32>, i64)>, struct<(ptr<i32>, ptr<i32>, i64)>)>
    llvm.store %4, %arg0 : !llvm.ptr<struct<(struct<(ptr<f32>, ptr<f32>, i64)>, struct<(ptr<i32>, ptr<i32>, i64)>)>>
    llvm.return
  }
}```

**Comment by laszlo-luminous** [comment]
@joker-eph I believe this issue can be closed now. Thank you!

**Comment by ftynse** [comment]
If you put "Closes #number" in the commit description, the issue is closed automatically.

**Comment by laszlo-luminous** [comment]
Will do in the future, thanks!
