### ISSUE TITLE
[OpenMP][AMDGCN] Memory access fault by GPU node-1 

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#53505]
Code execution stops at
```
ParticleSetPool::randomize 0 ParticleSets.
[GPU Memory Error] Addr: 0x4100000000 Reason: Page not present or supervisor privilege. 
Memory access fault by GPU node-1 (Agent handle: 0x76ba70) on address 0x4100000000. Reason: Page not present or supervisor privilege.
```

Reproducer
```
git clone https://github.com/QMCPACK/qmcpack
cd  qmcpack
git checkout d69bce8c77060d69d35f78861e501a6408c3cfee
mkdir build_amdgcn; cd build_amdgcn
cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DQMC_MPI=OFF -DENABLE_OFFLOAD=ON -DUSE_OBJECT_TARGET=ON -DOFFLOAD_TARGET=amdgcn-amd-amdhsa -DQMC_OFFLOAD_ROCM_WORKAROUND_BRANCH_IN_PARALLEL=OFF -DOFFLOAD_ARCH=gfx906 -DCMAKE_EXE_LINKER_FLAGS=-lm ..
make -j32 test_particle
./src/Particle/tests/test_particle
```
It seems like being caused by incorrect code generation. If I comment
https://github.com/ye-luo/qmcpack/blob/eeb38dd57886fd5b4ca423afdfe1e3033f11d00b/src/Particle/SoaDistanceTableABOMPTarget.h#L227
the test passes. The test code runs without issue when offloading to NVIDIA GPUs.

**Comment by jdoerfert** [comment]
Could be one of the races we recently discovered. Need to reevaluate on the `upupup` branch or in upstream once things are merged.

**Comment by ye-luo** [comment]
This test passes with `upupup` branch.

**Comment by jdoerfert** [comment]
I'm assuming/hoping this is fixed on mainline now.

**Comment by ye-luo** [comment]
Confirmed. Fixed.
