### ISSUE TITLE
[DAGCombiner]  Wrong code after optimizing load with and mask

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#53528]
It seems this is due to https://reviews.llvm.org/D117457 "[DAG] Extend SearchForAndLoads with any_extend handling", as a bisect lead to 5780087 which was the original commit, but it is also failing on trunk with the added recommit fix included.

Reduced test case:

llc -O3 -mcpu=z14 -o - ./wrong0.ll
[testcase.tar.gz](https://github.com/llvm/llvm-project/files/7981209/testcase.tar.gz)

Before DAGCombine of t59 (two anyext i8->i32 loads (t54, t55) are OR:ed, and then effectively compared as i64s, with an AND mask for low byte):

```
            t56: i32 = or t54, t55
          t57: i64 = any_extend t56
        t59: i64 = and t57, Constant:i64<255>
      t60: i32 = setcc t59, Constant:i64<1>, setlt:ch
    t19: ch = store<(store (s32) into @b)> t18, t60, GlobalAddress:i64<i32* @b> 0, undef:i64
  t42: i64,ch = load<(dereferenceable load (s32) from @b), sext from i32> t19, GlobalAddress:i64<i32* @b> 0, undef:i64
  t54: i32,ch = load<(dereferenceable load (s8) from @a, align 2), anyext from i8> t5, GlobalAddress:i64<i8* @a> 0, undef:i64
  t55: i32,ch = load<(dereferenceable load (s8) from @c, align 2), anyext from i8> t5, GlobalAddress:i64<i8* @c> 0, undef:i64
```

=> DAGCombine t59 =>

This transformation seems broken: now the two loads are zeroextending from i8->i32, and AND:ed as before, and then OR:ed. The OR is then any_extended to i64 which is used for the i64 comparison (t60) without any masking.

```
      t60: i32 = setcc t57, Constant:i64<1>, setlt:ch
    t19: ch = store<(store (s32) into @b)> t18, t60, GlobalAddress:i64<i32* @b> 0, undef:i64
  t42: i64,ch = load<(dereferenceable load (s32) from @b), sext from i32> t19, GlobalAddress:i64<i32* @b> 0, undef:i64
      t64: i32 = and t65, Constant:i32<255>
      t66: i32 = and t67, Constant:i32<255>
    t56: i32 = or t64, t66
  t57: i64 = any_extend t56
  t59: i64 = and t57, Constant:i64<255>
  t65: i32,ch = load<(dereferenceable load (s8) from @a, align 2), zext from i8> t5, GlobalAddress:i64<i8* @a> 0, undef:i64
  t67: i32,ch = load<(dereferenceable load (s8) from @c, align 2), zext from i8> t5, GlobalAddress:i64<i8* @c> 0, undef:i64
```

This leads to wrong code as the upper 32 bits of the compared value are undefined. If t57 would have been zero-extending this would have worked....

In the output:

```
        ork     %r0, %r0, %r1
        cghi    %r0, 0
```

If I comment out the added handling in SearchForAndLoads() like
```
+    // case ISD::ANY_EXTEND: {
+    //   unsigned ActiveBits = Mask->getAPIntValue().countTrailingOnes();
...
```
, the output is correct as it uses a Test under Mask instruction to only test the low byte:

```
       ork     %r0, %r0, %r1
       tmll    %r0, 255
```

**Comment by fhahn** [comment]
IIUC the problematic commit has been reverted in c89cfbd4ddfa.

@JonPsson is this still an issue?  If so, please re-open the issue.
