### ISSUE TITLE
RISC-V auto vectorization code not optimized

### ISSUE THREAD

**Issue by siddiksaurav** [llvm/llvm-project#53521]
I have used this command to generate vector assembly.

./clang -S test1.c -menable-experimental-extensions -march=rv64gv0p10 -target riscv64 -O3 -o test1.s -mllvm --riscv-v-vector-bits-min=2048
test1.c contains
void test_add(int *A, int *B, int *C, int n)
{
    for (int i = 0; i < n; i++)
        C[i] = A[i] + B[i];
}

generated assembly code:

test_add(int*, int*, int*, int):                     # @test_add(int*, int*, int*, int)
        blez    a3, .LBB0_15
        slli    a4, a3, 32
        li      a5, 32
        srli    a7, a4, 32
        bgeu    a3, a5, .LBB0_3
        li      t0, 0
        j       .LBB0_13
.LBB0_3:
        slli    a4, a7, 2
        add     a5, a2, a4
        add     a6, a0, a4
        add     t0, a1, a4
        sltu    a6, a2, a6
        sltu    a4, a0, a5
        and     a6, a6, a4
        sltu    a4, a2, t0
        sltu    a5, a1, a5
        and     a4, a4, a5
        or      a4, a6, a4
        li      t0, 0
        bnez    a4, .LBB0_13
        li      a4, 1
        slli    a4, a4, 32
        li      t1, 64
        addi    a6, a4, -64
        bgeu    a3, t1, .LBB0_6
        li      t0, 0
        j       .LBB0_10
.LBB0_6:
        and     t0, a7, a6
        mv      t2, t0
        mv      a5, a2
        mv      a4, a1
        mv      a3, a0
.LBB0_7:                                # =>This Inner Loop Header: Depth=1
        vsetvli zero, t1, e32, m1, ta, mu
        vle32.v v8, (a3)
        vle32.v v9, (a4)
        vadd.vv v8, v9, v8
        vse32.v v8, (a5)
        addi    a3, a3, 256
        addi    a4, a4, 256
        addi    t2, t2, -64
        addi    a5, a5, 256
        bnez    t2, .LBB0_7
        beq     t0, a7, .LBB0_15
        andi    a3, a7, 32
        beqz    a3, .LBB0_13
.LBB0_10:
        mv      a3, t0
        addi    a4, a6, 32
        and     t0, a7, a4
        slli    a5, a3, 2
        add     a6, a0, a5
        add     a4, a1, a5
        add     a5, a5, a2
        sub     a3, a3, t0
        li      t1, 32
.LBB0_11:                               # =>This Inner Loop Header: Depth=1
        vsetvli zero, t1, e32, mf2, ta, mu
        vle32.v v8, (a6)
        vle32.v v9, (a4)
        vadd.vv v8, v9, v8
        vse32.v v8, (a5)
        addi    a6, a6, 128
        addi    a4, a4, 128
        addi    a3, a3, 32
        addi    a5, a5, 128
        bnez    a3, .LBB0_11
        beq     t0, a7, .LBB0_15
.LBB0_13:
        slli    a3, t0, 2
        add     a2, a2, a3
        add     a1, a1, a3
        add     a0, a0, a3
        sub     a3, a7, t0
.LBB0_14:                               # =>This Inner Loop Header: Depth=1
        lw      a4, 0(a0)
        lw      a5, 0(a1)
        addw    a4, a4, a5
        sw      a4, 0(a2)
        addi    a2, a2, 4
        addi    a1, a1, 4
        addi    a3, a3, -1
        addi    a0, a0, 4
        bnez    a3, .LBB0_14
.LBB0_15: 
        ret
 https://godbolt.org/z/1f8oz57za

 Is there any way to optimize this code generation? please help

**Comment by uenoku** [comment]
It is not possible to vectorize if pointer C overlaps A or B. You would have to annotate pointer C with `__restrict__` keyword or something to indicate that C is exclusive to A and B, e.g:

```cpp
void test_add(int  *A, int  *B, int* __restrict__ C, int n)
{
    for (int i = 0; i < n; i++)
        C[i] = A[i] + B[i];
}
```

**Comment by fhahn** [comment]
I am closing this as working as expected, the pointer overlap checks are required for correctness. Please feel free to re-open the issue with more details, if the generated checks are less efficient than they can be.
