### ISSUE TITLE
Please cherry-pick several debug-info patches for llvm-14-rc1

### ISSUE THREAD

**Issue by jmorse** [llvm/llvm-project#53548]
Hi Tom / release-engineering team,

I've been working on a debug-info variable location feature which missed the llvm-14 branch by a few hours. It was enabled on main for x86_64 for 2 weeks without much trouble, but I turned it off after receiving a reproducer for excessive memory consumption, for which I now have patches. I've got several commits that would need to be cherry picked (below), would you be alright with this being
in llvm14-rc1?

A few faults reported from the initial landing are here, https://reviews.llvm.org/D116821, which I can summarise if needs be, but they're all now fixed. I ended up disabling the feature after some auto-generated code in https://reviews.llvm.org/D116821#3278089 led to a 5x increase in memory consumption, fixed by https://reviews.llvm.org/D118601 adding an upper bound on tracking too much debug-info.

The patches to cherry-pick in would be:
 * 14aaaa12366f7d1328b5ec81c71c63de9d878e75 (Re-)Apply max an upper-bound on the amount of debug-info to track,

 * d556eb7e27c25ae20befb0811bc8a3423241431d A performance patch (memoize some queries)
 * a80181a81ea44215e49e5da1457614ec0bd44111 Early-free some data structures
 * 9fd9d56dc6bdeeddf8cf2af834c6c39d00cd7244 Optimise an algorithm to reduce max-rss
 * 206cafb680cea0741f8c7b276351db516ff27f81 Follow up to the above for an accident with asan

 * 43de305704a50983bf134d8fb916f752a02eb076 Fix for a crash introduced by an unrelated performance opt

 * 6e03a68b776dc06826dacbdab26d24a90bb2173b Re-enable this feature by default for x86_64

The last of these just landed a few minutes ago, so it's worth leaving things ~24h to settle on main. As mentioned, it was on for 2 weeks beforehand without any major incidents.

(If needs be I can cherry-pick -x these to the release branch myself, exactly what the protocol is before -rc1 is unclear to me).

**Comment by jmorse** [comment]
NB: I've put all the cherry picks on this branch: https://github.com/jmorse/llvm-project/tree/release-14-instr-ref , for ease of access if these get merged.

Note that this also features 4654fa89eacca375ff860203697982b873bbd7c8, a temporary fix to keep asan happy while [D118774](https://reviews.llvm.org/D118774) is finished. It's a very shallow object lifetime problem that I wasn't paying enough attention to, rather than a deep-seated issue.

**Comment by tstellar** [comment]
/cherry-pick 14aaaa12366f7d1328b5ec81c71c63de9d878e75 d556eb7e27c25ae20befb0811bc8a3423241431d a80181a81ea44215e49e5da1457614ec0bd44111 9fd9d56dc6bdeeddf8cf2af834c6c39d00cd7244 206cafb680cea0741f8c7b276351db516ff27f81 43de305704a50983bf134d8fb916f752a02eb076 6e03a68b776dc06826dacbdab26d24a90bb2173b

**Comment by jmorse** [comment]
For the avoidance of doubt: 4654fa89eacca375ff860203697982b873bbd7c8 will also be required to avoid a memory leak found by LeakSanitizer. As mentioned in my previous comment there's a generalised solution to this problem in [D118774](https://reviews.llvm.org/D118774) being developed, but that's likely to only be ready for -rc2.

**Comment by tstellar** [comment]
Merged: 54a83652eeba
