### ISSUE TITLE
Please backport d919d027ba2a41df5d51ce82ae7f2fb64d2cba41 to 14.0.0

### ISSUE THREAD

**Issue by steakhal** [llvm/llvm-project#53541]
d919d027ba2a41df5d51ce82ae7f2fb64d2cba41 Fixes a deadlock in the scan-build libear library.
It's just a couple of lines, so it's probably worths the effort backporting.

/CC @AaronBallman @petrhosek You might want to know about this.

**Comment by AaronBallman** [comment]
The fix certainly looks reasonable to me from my looking at it.

**Comment by steakhal** [comment]
@tstellar please have a look at this commit.

**Comment by tstellar** [comment]
Merged: 9fa896f9e48f
