### ISSUE TITLE
cannot build llvm-libc-13 with gcc

### ISSUE THREAD

**Issue by braindevices** [llvm/llvm-project#53574]
I try to build it with following command:
```
cmake -G Ninja -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;compiler-rt;debuginfo-tests;libc;libclc;libcxx;libcxxabi;libunwind;lld;lldb;mlir;openmp;parallel-libs;polly;pstl -DCMAKE_BUILD_TYPE=Release -Wno-dev -DLLVM_CCACHE_BUILD=True -DOPENMP_ENABLE_LIBOMPTARGET=False -DLLVM_PARALLEL_LINK_JOBS=6 -DLLVM_ENABLE_BINDINGS=False -DLLVM_BINUTILS_INCDIR=/usr/include
```
However it fails with:
```
c++: error: unrecognized command line option ‘-mllvm’
c++: error: unrecognized command line option ‘-combiner-global-alias-analysis’
```
Does this means the llvm cannot be build with gcc any more? I did not have this problem with 10 and 11.

**Comment by efriedma-quic** [comment]
Don't pass "libc" to LLVM_ENABLE_PROJECTS.

That said, it probably shouldn't fail like this. @gchatelet ?

**Comment by gchatelet** [comment]
Yes it currently fails with `gcc`. This is on my plate, I'll fix ASAP.

**Comment by gchatelet** [comment]
@lntue @michaelrj-google @sivachandra we have a bunch of errors when compiling with `gcc`.
I'm currently fixing the ones linked to `CMakeLists.txt` and memory functions but there are many more.

In particular I think we'll have to enable C++17 to get away with floating point errors and `constexpr if`.
We'll have to deal with flavors of `asm` too.

```
/redacted/git/llvm-project/libc/src/math/generic/logf.cpp:176:30: error: exponent has no digits
/redacted/git/llvm-project/libc/src/math/generic/logf.cpp:176:51: warning: use of C++17 hexadecimal floating constant
  176 |       0x1.5555513bc679ap-2, -0x1.fff4805ea441p-3, 0x1.930180dbde91ap-3);
      |                                                   ^~~~~~~~~~~~~~~~~~

/redacted/git/llvm-project/libc/src/math/generic/logf.cpp:134:26: note: use ‘-fext-numeric-literals’ to enable more built-in suffixes
/redacted/git/llvm-project/libc/src/math/generic/logf.cpp:138:26: error: unable to find numeric literal operator ‘operator""f’
  138 |       return 0x1.45c146p+5f;
      |                          ^~
/redacted/git/llvm-project/libc/src/__support/FPUtil/generic/sqrt.h: In function ‘__llvm_libc::cpp::EnableIfType<__llvm_libc::cpp::IsFloatingPointType<Type>::Value, T> __llvm_libc::fputil::sqrt(T)’:
/redacted/git/llvm-project/libc/src/__support/FPUtil/generic/sqrt.h:111:6: warning: ‘if constexpr’ only available with ‘-std=c++17’ or ‘-std=gnu++17’
  111 |   if constexpr (internal::SpecialLongDouble<T>::VALUE) {
      |      ^~~~~~~~~
In file included from /redacted/git/llvm-project/libc/src/__support/FPUtil/sqrt.h:15,
                 from /redacted/git/llvm-project/libc/src/math/generic/sqrtl.cpp:10:
/redacted/git/llvm-project/libc/src/__support/FPUtil/x86_64/sqrt.h: In function ‘long double __llvm_libc::__sqrtl_impl__(long double)’:
/redacted/git/llvm-project/libc/src/__support/FPUtil/x86_64/sqrt.h:37:3: error: output operand 0 must use ‘&’ constraint
   37 |   __asm__ __volatile__("fsqrt" : "=t"(result) : "t"(x));
      |   ^~~~~~~

```

**Comment by lntue** [comment]
> @lntue @michaelrj-google @sivachandra we have a bunch of errors when compiling with `gcc`. I'm currently fixing the ones linked to `CMakeLists.txt` and memory functions but there are many more.
> 
> In particular I think we'll have to enable C++17 to get away with floating point errors and `constexpr if`.
> 
> ```
> /redacted/git/llvm-project/libc/src/math/generic/logf.cpp:176:30: error: exponent has no digits
> /redacted/git/llvm-project/libc/src/math/generic/logf.cpp:176:51: warning: use of C++17 hexadecimal floating constant
>   176 |       0x1.5555513bc679ap-2, -0x1.fff4805ea441p-3, 0x1.930180dbde91ap-3);
>       |                                                   ^~~~~~~~~~~~~~~~~~
> 
> /redacted/git/llvm-project/libc/src/math/generic/logf.cpp:134:26: note: use ‘-fext-numeric-literals’ to enable more built-in suffixes
> /redacted/git/llvm-project/libc/src/math/generic/logf.cpp:138:26: error: unable to find numeric literal operator ‘operator""f’
>   138 |       return 0x1.45c146p+5f;
>       |                          ^~
> /redacted/git/llvm-project/libc/src/__support/FPUtil/generic/sqrt.h: In function ‘__llvm_libc::cpp::EnableIfType<__llvm_libc::cpp::IsFloatingPointType<Type>::Value, T> __llvm_libc::fputil::sqrt(T)’:
> /redacted/git/llvm-project/libc/src/__support/FPUtil/generic/sqrt.h:111:6: warning: ‘if constexpr’ only available with ‘-std=c++17’ or ‘-std=gnu++17’
>   111 |   if constexpr (internal::SpecialLongDouble<T>::VALUE) {
>       |      ^~~~~~~~~
> ```
> 
> We'll have to deal with flavors of `asm` too.
> 
> ```
> In file included from /redacted/git/llvm-project/libc/src/__support/FPUtil/sqrt.h:15,
>                  from /redacted/git/llvm-project/libc/src/math/generic/sqrtl.cpp:10:
> /redacted/git/llvm-project/libc/src/__support/FPUtil/x86_64/sqrt.h: In function ‘long double __llvm_libc::__sqrtl_impl__(long double)’:
> /redacted/git/llvm-project/libc/src/__support/FPUtil/x86_64/sqrt.h:37:3: error: output operand 0 must use ‘&’ constraint
>    37 |   __asm__ __volatile__("fsqrt" : "=t"(result) : "t"(x));
>       |   ^~~~~~~
> ```

@gchatelet : I'm enabling C++17  for llvm-libc by default in https://reviews.llvm.org/D118871.  Just added you to that review.

**Comment by gchatelet** [comment]
I think this issue is now fixed with the submission of the following patches:
 - [D119142: [libc][NFC] moving template specialization outside class declaration](https://reviews.llvm.org/D119142)
 - [D119143: [libc] Don't use Clang flags on other compilers](https://reviews.llvm.org/D119143)
 - [D119145: [libc] Replace type punning with bit_cast](https://reviews.llvm.org/D119145).
 - [D119242: [libc] undefined reference in LibcTest.cpp](https://reviews.llvm.org/D119242).

@braindevices I'm closing this now, feel free to reopen if needed.
