### ISSUE TITLE
RISC-V vector compiler uses incorrect vsetivli

### ISSUE THREAD

**Issue by stevobailey** [llvm/llvm-project#53577]
https://godbolt.org/z/srjKc3Y6x

This loop performs the dot product of two vectors using the vector intrinsics. Line 10 of the compiled code sets the vector length for the reduction sum instruction:
```
vsetvli         zero, a4, e16, m2, tu, mu
vredsum.vs      v8, v12, v8
```
With `VLEN=256`, `SEW=16`, and `LMUL=2`, this gives us `VLMAX=2*VLEN/SEW=32`. After the loop finishes, I move the result to a scalar register (line 18). Line 17 sets the vector length for this move operation:
```
vsetivli        zero, 0, e16, m1, ta, mu
vmv.x.s         a0, v8
```
Because both rs1 and rd are x0, this is a special version of the `vsetivli` instruction (image from the RISC-V V spec version 1.0:
![image](https://user-images.githubusercontent.com/2245626/152394140-c6aaf659-e747-4e81-8476-de02e2a724f8.png)

Since `SEW=16` and `LMUL=1` after this new instruction, `VLMAX=VLEN/SEW=16`. But this is different from before. According to the spec, this is a "reserved" case, and the implementation I use sets `vill`.

I ran OptBisect and found this issue appears before any optimization passes. I also see the same issue in GCC.

This problem can be "solved" by manually setting the vector length before the move instruction. The only change in the output is that the new `vsetivli` instruction has rd=a0. But this is enough to avoid the requirement that VLMAX cannot change. See https://godbolt.org/z/ePK858qbT

Finally, the original code simulates as expected without error in Spike, despite the erroneous instruction.

Is this an issue with my code? I thought using LLVM and intrinsics meant I didn't have to keep careful track of the vector length. And this move intrinsic doesn't take a vl argument, either. I think this is an issue with Clang. Either it should report the problem in my code, or it should generate the correct `vsetivli` instruction.

**Comment by topperc** [comment]
The instruction generated is `vsetivli` which is a different instruction than `vsetvli`. There's an extra 'i' in the middle. As far as I know `vsetivli` allows an immediate of 0. This should be different than the x0, x0 encoding for `vsetvli`.

**Comment by stevobailey** [comment]
Thanks, this is an issue in my understanding, then. I think the bug I'm describing is true for GCC (see the linked issue https://github.com/vproc/vicuna/issues/37). But I'll close this issue since LLVM looks to be correct.
