### ISSUE TITLE
Request to cherry-pick eaee477edafe onto release/14.x

### ISSUE THREAD

**Issue by sdesmalen-arm** [llvm/llvm-project#53585]
This patch improves the ability to choose a better epilogue VF when the main loop is vectorised using scalable vectors, and fixes a deficiency in https://reviews.llvm.org/D118688. The patch has no effect outside of scalable vectors and we'll be doing additional release testing on scalable vectors for LLVM 14. No issues have shown up on the build-bot that tests scalable-vectorization.

**Comment by tstellar** [comment]
Merged: e6b508f49ae9
