### ISSUE TITLE
some libc calls are slower in clang-14 according to callgrind

### ISSUE THREAD

**Issue by firewave** [llvm/llvm-project#53587]
While looking into a slight performance regression in `clang-14` I came across something rather strange in the `callgrind` output.

Using `clang-14` the Ir for a `__memchr_sse2` call increased by 10-20% from an almost constant `20` to `22` or `24`.

I am also seeing something similar with `__strncmp_sse42`. `__memcmp_sse4_1` and `__strlen_sse2` on the other hand are not affected at all.

With clang-12 I am seeing the same values as with clang-13.

It is rather strange that this could be affected by the compiler since these are library calls. Checking the IR shows no differences in the call invocation.

Maybe this is just a shortcoming of `callgrind` but it really throws off the profiling when functions utilizing those calls are suddenly using > 10% Ir.

I am using `Ubuntu clang version 12.0.0-3ubuntu1~20.04.4`, `Ubuntu clang version 13.0.1-++20220120110924+75e33f71c2da-1~exp1~20220120231001.58` and `Ubuntu clang version 14.0.0-++20220131052853+016956b68081-1~exp1~20220131172951.142` on Ubuntu 20.04.

**Comment by LebedevRI** [comment]
As usual, it would be good to have at least some sort of a standalone reproducer.

**Comment by firewave** [comment]
> As usual, it would be good to have at least some sort of a standalone reproducer.

Obviously. But I thought I post the scenario first so somebody can call me out for doing/expecting/understanding something totally wrong.

**Comment by firewave** [comment]
I am having a hard time reproducing this and some other "micro regressions" in clang-14 in isolated samples. It appears they only occur in certain contexts and these are very deep into the workflows of the applications I am experiencing them with.

I have an idea on how to extract these parts but it will take some time. Hopefully they will still experience the issues then.

Though I am seeing the issue outlined here in another application as well so it doesn't appear to be a fluke.

**Comment by firewave** [comment]
I also see this with exactly the same toolchain in different binaries in code unrelated to the changes done in-between the binaries. So something in the binary or the execution seems to throw off callgrind for libc calls.

**Comment by firewave** [comment]
I am closing this as it appears to be "just" some imprecision within callgrind. I have seen this several with only changing a single file in a project and re-running it.
