### ISSUE TITLE
Different code after adce when line number info on a branch is available

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#53582]
llvm commit: 31fa3a4d44

With
 opt -passes='cgscc(devirt<4>(inline,function-attrs,simplifycfg,adce))' -S -o - bbi-58214_x86.ll

[bbi-58214_x86.ll.gz](https://github.com/llvm/llvm-project/files/8002833/bbi-58214_x86.ll.gz)

we get a function b like

define i16 @b() #0 {
entry:
  %call = call i16 @b()
  unreachable, !dbg !8
}

But if we remove the debug info from

  br label %for.cond, !dbg !24

and run opt again as above we will get a function be like this:

define i16 @b() {
entry:
  %call = call i16 @b()
  br label %for.cond.i

for.cond.i:                                       ; preds = %for.cond.i, %entry
  br label %for.cond.i
}

**Comment by fhahn** [comment]
It looks like the same code is generated with and without debug info on the branch now: https://llvm.godbolt.org/z/zz7T8sb8d

Please re-open the issue with an updated reproducer if it still reproduces on your end.
