### ISSUE TITLE
Cherry-pick 6b73a4cc7db96af1dd02db68c07fe4a807104c53 into LLVM 14

### ISSUE THREAD

**Issue by brads55** [llvm/llvm-project#53580]
6b73a4cc7db96af1dd02db68c07fe4a807104c53 brings SVE floating point converts into line with other unary operations, with regards to breaking false dependencies.

**Comment by brads55** [comment]
@tstellar I'm not sure what is going on here with this new action, apologies if this wasn't ready for use yet. (The first failure was my fault, but the second seems to be a permissions issue somewhere).

**Comment by tstellar** [comment]
Merged: 2bae96d8a349
