### ISSUE TITLE
cherry pick request: [x86] enable fast sqrtss/sqrtps tuning for AMD Zen cores

### ISSUE THREAD

**Issue by rotateright** [llvm/llvm-project#53592]
fff3e1dbaa9e

**Comment by rotateright** [comment]
This will require cherry pick for the preliminary test changes. That was:
1eb4f88bfef1ab93b828

**Comment by tstellar** [comment]
/cherry-pick 1eb4f88bfef1ab93b8286fdfd05a8b814507e329 fff3e1dbaa9ee2d91dc15b39defa88346f03a4c2

**Comment by tstellar** [comment]
Merged: ebe5b447270c 0f27bf28d255
