### ISSUE TITLE
Clang parser crash

### ISSUE THREAD

**Issue by colavitam** [llvm/llvm-project#53605]
The following code causes a parser crash in clang when run with no options:
```
template < a >
class b {
    struct XXXXXXXXXXXXZZZZilsABCDEFGHI
    struct : XXXXXXXXXXXXZZZZilsABCDEFGHI,
            XXXXXXXXXXXXYYYYYYYYYingABCDEFGHI
```

**Comment by penagos** [comment]
Can you please confirm which build you're using to exercise this crash? I tried running your sample code through clang++, yet was not able to reproduce a parser crash using:

```
$ clang input.cpp
```

With build:
```
clang version 15.0.0 (https://github.com/llvm/llvm-project c77f4bf1bfcc1d332c0d60940d601245f1cb159f)
```

**Comment by shafik** [comment]
[godbolt with this crashing on 13.0.1](https://godbolt.org/z/onn4abed9) It does not look like it reproduces on trunk though.

**Comment by fhahn** [comment]
As @shafik mentioned, it looks like this has been fixed on current `main`: https://godbolt.org/z/c5dd1Tahf

Please re-open the issue with additional info, if it still reproduces on current `main` on your end.
