### ISSUE TITLE
function signature with templated lambda as parameter is uncertain 

### ISSUE THREAD

**Issue by nickhuang99** [llvm/llvm-project#53611]
This code (https://www.godbolt.org/z/Gcsqh7YT7)  shows clang cannot resolve function template due to function signature confused.  Only MSVC is giving the correct answer, GCC is even stumbled in the first place for function signature. But clang seems to consider parameter type of template lambda could **be both "int" and function pointer "void(*)(int)"**. This probably why clang cannot resolve function in the end.

1. given a template lambda type which effectively just function pointer because of "+" operator
`template<typename T>`
`using Lambda=decltype(+[](T){});`

2. now "foo" wants to take this type as parameter
`template<typename T>`
`auto foo(T&&, Lambda<T>)->T;`
  
3. The obvious issue is that how can these two asserts both be true? clang is uncertain about the function signature
`static_assert(is_same_v<decltype(&foo<int>),  int(*)(int&&,  void(*)(int))>);`
`static_assert(is_same_v<decltype(&foo<int>),   int(*)(int&&,  int)>);`

4. So, that is probably why we cannot call foo with any type of parameter: function pointer, lambda etc. because clang always gives no matching error.

`int main(){`
    `auto funptr=+[](int n){};`
    `static_assert(is_same_v<decltype(funptr),void(*)(int)>);`
   ` void(*ptr)(int)=funptr;`
   ` foo<int>(5, ptr);`    //clang rejects
    `foo<int>(5, [](int n){});// lambda conversion operator!`  //clang rejects
    `foo<int>(5, funptr); //lambda is function pointer`        //clang rejects
`}`

**Comment by cor3ntin** [comment]
I believe this was fixed in clang 15. https://www.godbolt.org/z/71nq9rMq1 
Feel free to reopen if you think there is still a bug there.
