### ISSUE TITLE
Cherry-pick lld cmake fix

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#53616]
https://reviews.llvm.org/D118792 addresses a backwards-compatibility issue in the lld build system.

/cherry-pick e0eeae9a447004cc346d9bf36c0d02f45e276a7c

**Comment by nikic** [comment]
Maybe this only works in comments, not the issue description?

/cherry-pick e0eeae9a447004cc346d9bf36c0d02f45e276a7c

**Comment by tstellar** [comment]
Merged: 319f4b2d52e3
