### ISSUE TITLE
[DAG] Add knownbits/signbits handling for ISD::AVG* nodes

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#53622]
https://reviews.llvm.org/D106237 adds the ISD::AVGFLOORS/AVGFLOORU/AVGCEILS/AVGCEILU nodes which we will require value tracking handling for in SelectionDAG.

CC @davemgreen

**Comment by RKSimon** [comment]
ISD::AVGCEILU handling - https://reviews.llvm.org/D119629

**Comment by snikitav** [comment]
I can take this as well
