### ISSUE TITLE
[optimization] gcc use less register than clang base on updating common offset

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#53625]
test case:

```
int nex_group;
int *ex1_bit,*ex2_bit;

int exclusion(void) {

  if (nex_group) { // generate smarter assemble with if (1)
    for (int m = 0; m < nex_group; m++) {
      if (ex1_bit[m] & ex2_bit[m]) return 1;
    }
  }

  return 0;
}
```

Compared to gcc, clang use two different registers for offset **m**,  then is need two independence add instructions to update address .  https://godbolt.org/z/nMGf94Wrn

- clang

```
.LBB0_3:                                // =>This Inner Loop Header: Depth=1
        ldr     w11, [x9]
        ldr     w12, [x10]
        tst     w12, w11
        b.ne    .LBB0_6
        add     x10, x10, #4  -- update address
        add     x9, x9, #4      -- update address
        subs    x8, x8, #1
        b.ne    .LBB0_3
```
- gcc
```
.L8:
        cmp     x3, x1
        beq     .L1
.L3:
        ldr     w0, [x5, x1]
        ldr     w2, [x4, x1]
        add     x1, x1, 4
        ands    w0, w0, w2
        beq     .L8
```

**Comment by vfdff** [comment]
Fold the operands of update address into load/store may be also alternative, such as https://github.com/llvm/llvm-project/issues/29497

**Comment by rotateright** [comment]
Adding target-specific label based on comparison with x86-64 asm. That code has a single 'add' or 'inc' instruction to offset the addresses. This might be something that can be adjusted in TTI or TLI to let the backend (LSR?) know about the preferred addressing modes.

**Comment by davemgreen** [comment]
I feel like if LSR had added the geps to the right block, it would have managed to produce this (through luck or not), which would have been nice:
```
.LBB0_3:                                // =>This Inner Loop Header: Depth=1
        ldr     w11, [x9], #4
        ldr     w12, [x10], #4
        tst     w12, w11
        b.ne    .LBB0_6
        subs    x8, x8, #1
        b.ne    .LBB0_3
```

**Comment by bcl5980** [comment]
> I feel like if LSR had added the geps to the right block, it would have managed to produce this (through luck or not), which would have been nice:
> 
> ```
> .LBB0_3:                                // =>This Inner Loop Header: Depth=1
>         ldr     w11, [x9], #4
>         ldr     w12, [x10], #4
>         tst     w12, w11
>         b.ne    .LBB0_6
>         subs    x8, x8, #1
>         b.ne    .LBB0_3
> ```

https://godbolt.org/z/GoW8eqj69
For LSR, I guess the question is where the SCEV update.
If the SCEV update on `for.body` block, the code you show here is correct.
But if the SCEV update on `for.condition` block, we can't combine to post-index load.
