### ISSUE TITLE
Please cherry-pick a LLDB performance improvement

### ISSUE THREAD

**Issue by JDevlieghere** [llvm/llvm-project#53630]
Please consider cherry-picking the following series of patches which improve LLDB performance and memory usage by not demangling the full symbol name when indexing the symbol table. 

The main change is https://reviews.llvm.org/rGaed965d55d46 

/cherry-pick fa52788b7a6da1eab9fec0f2db5f74a8db555196 aed965d55d460ebcc2b442b9d799b4c1ab929157 edbb0f6df76b04100357c7c9438f3b5b978e0200 ef3fade14b32c20e0a35b8fca30e7d2f20e0c983

**Comment by tstellar** [comment]
/cherry-pick fa52788b7a6da1eab9fec0f2db5f74a8db555196 aed965d55d460ebcc2b442b9d799b4c1ab929157 edbb0f6df76b04100357c7c9438f3b5b978e0200 ef3fade14b32c20e0a35b8fca30e7d2f20e0c983

**Comment by tstellar** [comment]
Merged: dbf2f560947f bee0279abeda 39b1d3d27ae3 47ea1e198cec
