### ISSUE TITLE
lldb-mi hangs and starts consuming more and more memory when stopping at certain breakpoints in vscode-cpptools

### ISSUE THREAD

**Issue by mlangiu** [llvm/llvm-project#53634]
Hi, I wanted to notify you of several issues that crop up with debugging via the cpptools package for Visual Studio Code, which appear to be caused by an error in lldb-mi.
In summary stopping at (or in some cases near) uninitialized memory.
More details can be found in the following related issues
- https://github.com/microsoft/vscode-cpptools/issues/1899
- https://github.com/microsoft/vscode-cpptools/issues/5805
- https://github.com/microsoft/vscode-cpptools/issues/7240

 I hope I came to the right place.

Kind Regards

Marco

**Comment by labath** [comment]
lldb-mi is no longer a part of lldb. You can try filing a bug here <https://github.com/lldb-tools/lldb-mi>, but I don't know how active the project is. Feel free to file a new bug if you're able to reproduce the problem with lldb alone.
