### ISSUE TITLE
[lldb][iOS] Crash when tried to attach to mediaserverd

### ISSUE THREAD

**Issue by akholaif-github** [llvm/llvm-project#53637]
~ root# lldb
(lldb) process attach --name mediaserverd
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  lldb                     0x00000001027ef990 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 80
1  lldb                     0x00000001027eff3c PrintStackTraceSignalHandler(void*) + 32
2  lldb                     0x00000001027edec0 llvm::sys::RunSignalHandlers() + 152
3  lldb                     0x00000001027f26dc SignalHandler(int) + 272
4  libsystem_platform.dylib 0x00000001ff44ab70 <redacted> + 56
5  libsystem_platform.dylib 0xffffff8189b5be10 <redacted> + 18446743521981436632
6  libdyld.dylib            0x0000000189b5c8a0 <redacted> + 72
7  libdyld.dylib            0x0000000189b5c818 <redacted> + 128
8  libdyld.dylib            0x0000000189b5c72c <redacted> + 272
9  libdyld.dylib            0x0000000189b5eba4 dyld_for_each_installed_shared_cache + 104
10 LLDB                     0x0000000116c96b18 ObjectFileMachO::ParseSymtab() + 5928
11 LLDB                     0x0000000116c95374 ObjectFileMachO::GetSymtab() + 132
12 LLDB                     0x0000000116d93da0 SymbolFileDWARFDebugMap::InitOSO() + 264
13 LLDB                     0x0000000116d947cc SymbolFileDWARFDebugMap::CalculateNumCompileUnits() + 24
14 LLDB                     0x00000001169d12f4 lldb_private::SymbolFile::GetNumCompileUnits() + 132
15 LLDB                     0x0000000116d94784 SymbolFileDWARFDebugMap::CalculateAbilities() + 24
16 LLDB                     0x00000001169d0ff8 lldb_private::SymbolFile::FindPlugin(std::__1::shared_ptr<lldb_private::ObjectFile>) + 492
17 LLDB                     0x00000001169d2054 lldb_private::SymbolVendor::AddSymbolFileRepresentation(std::__1::shared_ptr<lldb_private::ObjectFile> const&) + 104
18 LLDB                     0x0000000116dad09c SymbolVendorMacOSX::CreateInstance(std::__1::shared_ptr<lldb_private::Module> const&, lldb_private::Stream*) + 4288
19 LLDB                     0x00000001169d1d8c lldb_private::SymbolVendor::FindPlugin(std::__1::shared_ptr<lldb_private::Module> const&, lldb_private::Stream*) + 64
20 LLDB                     0x00000001168c42e0 lldb_private::Module::GetSymbolFile(bool, lldb_private::Stream*) + 208
21 LLDB                     0x00000001168c5ac0 lldb_private::Module::PreloadSymbols() + 80
22 LLDB                     0x0000000116a4d3cc lldb_private::Target::GetOrCreateModule(lldb_private::ModuleSpec const&, bool, lldb_private::Status*) + 2288
23 LLDB                     0x0000000116b09e64 lldb_private::DynamicLoaderDarwin::FindTargetModuleForImageInfo(lldb_private::DynamicLoaderDarwin::ImageInfo&, bool, bool*) + 1056
24 LLDB                     0x0000000116b0e040 lldb_private::DynamicLoaderDarwin::AddModulesUsingImageInfos(std::__1::vector<lldb_private::DynamicLoaderDarwin::ImageInfo, std::__1::allocator<lldb_private::DynamicLoaderDarwin::ImageInfo> >&) + 504
25 LLDB                     0x0000000116b074f4 DynamicLoaderMacOS::DoInitialImageFetch() + 656
26 LLDB                     0x0000000116b097e4 lldb_private::DynamicLoaderDarwin::DidAttach() + 184
27 LLDB                     0x0000000116a10110 lldb_private::Process::CompleteAttach() + 1784
28 LLDB                     0x0000000116a0f9b0 lldb_private::Process::AttachCompletionHandler::PerformAction(std::__1::shared_ptr<lldb_private::Event>&) + 424
29 LLDB                     0x0000000116a0de88 lldb_private::Process::HandlePrivateEvent(std::__1::shared_ptr<lldb_private::Event>&) + 200
30 LLDB                     0x0000000116a13338 lldb_private::Process::RunPrivateStateThread(bool) + 1440
31 LLDB                     0x0000000116a1290c lldb_private::Process::PrivateStateThread(void*) + 32
32 LLDB                     0x0000000116950f3c lldb_private::HostNativeThreadBase::ThreadCreateTrampoline(void*) + 108
33 libsystem_pthread.dylib  0x00000001ff4529d4 _pthread_start + 144
34 libsystem_pthread.dylib  0x00000001ff451eb4 thread_start + 8
Segmentation fault: 11

**Comment by JDevlieghere** [comment]
This is an Apple internal report. @akholaif-github please reach out to me via e-mail or Slack.
