### ISSUE TITLE
[instcombine] dropped inreg function argument attribute

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#53645]
[inreg langref](https://llvm.org/docs/LangRef.html#parameter-attributes)

When instcombine replace calls to `memcmp` with `bcmp`, it happens to NOT carry over the `inreg` flags on the arguments when they exist.  `inreg` is set by `-mregparm=3` for `-m32` (32b x86) linux kernel builds.

blocks #4440

example: https://godbolt.org/z/z3fjveP4h

This is creating fun crashes at boot time because we've now totally messed up the calling convention.

**Comment by nickdesaulniers** [comment]
`emitLibCall` in llvm/lib/Transforms/Utils/BuildLibCalls.cpp potentially should be copying over the `AttributeSet` from the previous call to the newly synthesized call. Or at least just the `AttributeList::getParamAttrs`.

**Comment by efriedma-quic** [comment]
If all the utilities in BuildLibCalls.h are broken, we need a general fix for all of them.  Copying the attributes from another call isn't going to work in general; we don't have a call with the relevant attributes from in some cases.  I guess we need something equivalent to X86TargetLowering::markLibCallAttributes.

**Comment by nickdesaulniers** [comment]
Maybe something like:
```diff
diff --git a/llvm/lib/Transforms/Utils/BuildLibCalls.cpp b/llvm/lib/Transforms/Utils/BuildLibCalls.cpp
index 97f11ca71726..7a2938ba26d6 100644
--- a/llvm/lib/Transforms/Utils/BuildLibCalls.cpp
+++ b/llvm/lib/Transforms/Utils/BuildLibCalls.cpp
@@ -1231,6 +1231,23 @@ static Value *emitLibCall(LibFunc TheLibFunc, Type *ReturnType,
   FunctionCallee Callee = M->getOrInsertFunction(FuncName, FuncType);
   inferLibFuncAttributes(M, FuncName, *TLI);
   CallInst *CI = B.CreateCall(Callee, Operands, FuncName);
+
+  // If the Operand is an Argument, use its ArgNo to find its ParamAttrs. Copy
+  // them to the new CallInst's ParamAttrs.
+  unsigned NewArgNo = 0;
+  for (Value *Operand : Operands) {
+    if (auto *A = dyn_cast<Argument>(Operand)) {
+      Function *F = A->getParent();
+      AttributeList AL = F->getAttributes();
+      unsigned ArgNo = A->getArgNo();
+      AttributeSet ParamAttrs = AL.getParamAttrs(ArgNo);
+
+      for (const Attribute &A : ParamAttrs)
+        CI->addParamAttr(NewArgNo, A);
+      ++NewArgNo;
+    }
+  }
+
   if (const Function *F =
           dyn_cast<Function>(Callee.getCallee()->stripPointerCasts()))
     CI->setCallingConv(F->getCallingConv());
```

**Comment by efriedma-quic** [comment]
The correct number of "inreg" markings for a call to bcmp should be computed based on its signature and the module flag NumRegisterParameters.  Anything else is irrelevant, including the inputs to the call, or any aspect of the call it's replacing.

**Comment by davidbolvansky** [comment]
As inreg is not a "hint" which can be dropped, maybe just create list of attributes which cannot be dropped as they are important? Then just skip SimplifyLibCalls pass for such calls with those attributes? And yes, .. current managment of call attributes in SLC is not ideal.

**Comment by efriedma-quic** [comment]
To give a specific testcase, consider the following:

```
#include <string.h>
char* f (const char z) {
    return strchr("foobar", z);
}
```

The strchr gets converted to memchr.  With `-mregparm=3`, all three arguments to the memchr need to be marked inreg.  Where does the "7" get its inreg marking?   The only way we know it needs an inreg marking is by querying NumRegisterParameters.

The "libcall" handling in SelectionDAG only gets called for libcalls that are generated by SelectionDAG (e.g. from lowering intrinsics like llvm.memcpy).  If we're generating libcalls at the IR level, I think we need an equivalent codepath that works on IR.  Or some sort of marking to let the backend know the inreg attributes are missing.

**Comment by nickdesaulniers** [comment]
Is https://reviews.llvm.org/rG0f8c626723d2 how I should be solving this?

cc @JonPsson @nikic

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D125285

**Comment by nickdesaulniers** [comment]
/cherry-pick c167c0a4dcdb998affb2756ce76903a12f7d8ca5

@efriedma-quic thoughts on allowing this into clang 14.0.4?

**Comment by efriedma-quic** [comment]
On its own, I'd say fine.  But I'm not sure about cherry-picking 0f8c6267

**Comment by nickdesaulniers** [comment]
yeah, ok, np, this one can ride the trains.
