### ISSUE TITLE
[OpenMP] complex reductions in the OvO test suite produce NaNs

### ISSUE THREAD

**Issue by jdoerfert** [llvm/llvm-project#53647]
Some complex reductions in the OvO test suite (among other things) produce NaNs because the Attributor introduces `unreachable` in "semi-random" places.

Can be reproduced with OvO on NVIDIA hardware, very likely on AMD as well.

**Comment by tstellar** [comment]
Merged: 61c8cf97479f37c63724f63fd4c727cd2b433ae9
