### ISSUE TITLE
[llvm] Clarify whether aarch64 supports `gc.statepoints`

### ISSUE THREAD

**Issue by zero9178** [llvm/llvm-project#53655]
The documentation (https://llvm.org/docs/Statepoints.html#supported-architectures) currently states that it is only supported for X86_64 , yet by chance I just came across https://reviews.llvm.org/D66012 which seems to have landed some time ago. 

The commit message does imply that the transition flag is not supported, but I believe it might be worth documenting either way, if the rest of the functionality works (and seems to be in use by GraalVM)

**Comment by preames** [comment]
I can confirm that Aarch64 supports gc.statepoint.  A patch to fix the documentation would be welcomed.
