### ISSUE TITLE
backport request: [x86] invert a vector select IR canonicalization with a binop identity constant

### ISSUE THREAD

**Issue by rotateright** [llvm/llvm-project#53656]
This will mitigate a potential perf regression from the last release as discussed here:
https://reviews.llvm.org/D113442

/cherry-pick 6592bcecd4

**Comment by tstellar** [comment]
@rotateright The milestone is correct.  The only thing is that the cherry-pick command only works in a comment at the moment and not in in the issue body (i.e. the first comment), but I'm working on fixing that.

If you have other commits, it's going to be easier to just create a new issue for them.

**Comment by rotateright** [comment]
> @rotateright The milestone is correct. The only thing is that the cherry-pick command only works in a comment at the moment and not in in the issue body (i.e. the first comment), but I'm working on fixing that.

Aha - I didn't know about that detail.

> If you have other commits, it's going to be easier to just create a new issue for them.

Sure, will do. The other parts just went into main today, so I'll give them at least a day to bake.

**Comment by tstellar** [comment]
Merged: a2f583280e48
