### ISSUE TITLE
Merge f2f4080c10f4319adf75c660425911cd4e0e1843 into 14.0.0

### ISSUE THREAD

**Issue by ecnelises** [llvm/llvm-project#53657]
[PowerPC] Fix SSE translation on FreeBSD

This patch drops throws specifier in posix_memalign declaration because
that's different between glibc and other libc, and Clang has a hack.

Differential Revision: https://reviews.llvm.org/D117972

**Comment by tstellar** [comment]
Merged: 4f624dd81687
