### ISSUE TITLE
Merge 424e850f1ebc3e7011cb4af44cb2d62c02a58fbe into 14.0.0

### ISSUE THREAD

**Issue by amilendra** [llvm/llvm-project#53663]
Please merge 424e850f1ebc
[clang][ARM] Re-word PACBTI warning.

The original warning added in [D115501](https://reviews.llvm.org/D115501) when pacbti is used with an
incompatible architecture was not exactly correct because it was
not really ignored and can affect codegen.

Therefore reword to say that the pacbti option is incompatible with
the given architecture.

Reviewed By: chill

Differential Revision: https://reviews.llvm.org/D119166

**Comment by tstellar** [comment]
Merged: 7246d583d601
