### ISSUE TITLE
generate same code with different logic code

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#53667]
For the function initArray and initArray1, they have different const value, while they have same assemble, even with O0.

test case, https://godbolt.org/z/7czd443ss
```
float initArray(void) {
  return float(0x7fffffff);
}

float initArray1(void) {
  return float(0x7ffffff0);
}
```

**Comment by topperc** [comment]
Those integer values can't be represented exactly as a float so they were rounded.

**Comment by vfdff** [comment]
thanks very much.

Yes, gcc rounded it at very early stage, https://godbolt.org/z/7K8fGP4sj
