### ISSUE TITLE
Clang won't compile C++20 module implementation units

### ISSUE THREAD

**Issue by rnburn** [llvm/llvm-project#53661]
If I have the following module interface file

```c++
// a.cc
export module a;

import <string>;
import <string_view>;

export std::string speak(std::string_view s);
```

and the following source file for module a

```c++
// a-impl.cc
module a;

import <string>;
import <string_view>;

std::string speak(std::string_view s) {
  if (s == "Hello") {
    return "Hola";
  }
  return "???";
}
```

I compile `a.cc` to a PCM file using
```
clang++-15 -x c++-module -std=c++20 -fmodules -fbuiltin-module-map -stdlib=libc++ --precompile a.cc
```
But then if I try to compile `a-impl.cc` using
```
clang++-15 -std=c++20 -fmodules -fbuiltin-module-map -fmodule-file=a=a.pcm -stdlib=libc++ -c a-impl.cc
```
I get the error
```
a-impl.cc:2:1: error: definition of module 'a' is not available; use -fmodule-file= to specify path to precompiled module interface
module a;
^
1 error generated.
```
even though I specified the module file.

This is using a version of clang built from the development branch
```
clang++-15 --version
Ubuntu clang version 15.0.0-++20220208104503+215aba771264-1~exp1~20220208104559.278
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by njames93** [comment]
`-fmodule-file=a=a.pcm` could that syntax error in your invocation be the reason it's failing?

**Comment by rnburn** [comment]
That's not a syntax error. From the [docs](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-fmodule-file)

> -fmodule-file=\[\<name\>=\]\<file\>
> Specify the mapping of module name to precompiled module file, or load a module file if name is omitted.

**Comment by rnburn** [comment]
ok - after investigating further, it looks like when compiling an implementation unit, I need to use the `-fmodule-file=<file>` form of the option. I was able to get it to work after changing to
```
clang++-15 -std=c++20 -fmodules -fbuiltin-module-map -fmodule-file=a.pcm -stdlib=libc++ -c a-impl.cc
```
