### ISSUE TITLE
Remove GNU ld incompatible --[no-]define-common and obscure -dc/-dp

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#53660]
Cross-posted to https://discourse.llvm.org/t/remove-gnu-ld-incompatible-no-define-common-and-obscure-d-dc-dp/59894 (with more information).
https://maskray.me/blog/2022-02-06-all-about-common-symbols has more background.

Before 2017-01, ld.lld used to allocate space for COMMON symbols in `-r` mode. This was fixed by https://reviews.llvm.org/D28984 . https://reviews.llvm.org/D28984 added some options as the fix:

* `--define-common` and `--no-define-common`: inherited from gold and incompatible with GNU ld (https://sourceware.org/bugzilla/show_bug.cgi?id=28871). According to https://codesearch.debian.net/search , there is no usage.
* `-d`, `-dc`, and `-dp`: I've tried a few patterns and am convinced that grub has something like `-W,-r,-d`. `-dc` and `-dp` do not have usage.

For `-d`, `-dc`, and `-dp`, the option is only effective in `-r` mode. Ignoring the option is a correct implementation, unless (hypothetically) a project takes `-r` output and interprets it in its own way and somehow doesn't support `SHN_COMMON` input. This seems extremely unlikely as if it deals with normal relocatable object files printed by the assembler, it needs to support `SHN_COMMON`.

So I suggest we remove `--define-common` and `--no-define-common`, and make `-d`/`-dc`/`-dp` a no-op. Since `-dc` and `-dp` do look like unused, remove them.

edit: patch for 15.0.0: https://reviews.llvm.org/D119108
`-d` and `-dc` are used by projects but a no-op implementation works. `-dp` will be removed.

**Comment by emaste** [comment]
FreeBSD crunch passes -dc: https://github.com/freebsd/freebsd-src/blob/main/usr.sbin/crunch/crunchgen/crunchgen.c#L1126

This is used to produce a Makefile for linking a crunched binary - see man page at https://www.freebsd.org/cgi/man.cgi?query=crunchgen&sektion=1 for details

Here's a portion of the makefile produced by crunchgen:
```
# -------- cat

cat_OBJDIR=/usr/obj/.../rescue/rescue/.../main/bin/cat
cat_OBJPATHS= $(cat_OBJDIR)/cat.o
$(cat_OBJPATHS): .NOMETA
cat_SRCDIR=/.../rescue/rescue/../../bin/cat
cat_REALSRCDIR=/.../bin/cat
cat_OBJS= cat.o
cat_OPTS+= DIRPRFX=rescue/rescue/cat/
cat_make:
        (cd $(cat_SRCDIR) && \
                $(CRUNCHMAKE) $(BUILDOPTS) $(cat_OPTS) depend &&\
                $(CRUNCHMAKE) $(BUILDOPTS) $(cat_OPTS) $(cat_OBJS))
cat_clean:
        (cd $(cat_SRCDIR) && $(CRUNCHMAKE) $(BUILDOPTS) clean cleandepend)

cat_stub.c:
        echo "extern int main(int argc, char **argv, char **envp); int _crunched_cat_stub(int argc, char **argv, char **envp);int _crunched_cat_stub(int argc, char **argv, char **envp){return main(argc,argv,envp);}" >cat_stub.c
cat.lo: cat_stub.o $(cat_OBJPATHS)
        $(CC) -nostdlib -Wl,-dc -r -o cat.lo cat_stub.o $(cat_OBJPATHS)
        crunchide -k _crunched_cat_stub cat.lo


```

**Comment by MaskRay** [comment]
> FreeBSD crunch passes -dc: https://github.com/freebsd/freebsd-src/blob/main/usr.sbin/crunch/crunchgen/crunchgen.c#L1126
> 
> This is used to produce a Makefile for linking a crunched binary - see man page at https://www.freebsd.org/cgi/man.cgi?query=crunchgen&sektion=1 for details
> 
> Here's a portion of the makefile produced by crunchgen:
> 
> ```
> # -------- cat
> 
> cat_OBJDIR=/usr/obj/.../rescue/rescue/.../main/bin/cat
> cat_OBJPATHS= $(cat_OBJDIR)/cat.o
> $(cat_OBJPATHS): .NOMETA
> cat_SRCDIR=/.../rescue/rescue/../../bin/cat
> cat_REALSRCDIR=/.../bin/cat
> cat_OBJS= cat.o
> cat_OPTS+= DIRPRFX=rescue/rescue/cat/
> cat_make:
>         (cd $(cat_SRCDIR) && \
>                 $(CRUNCHMAKE) $(BUILDOPTS) $(cat_OPTS) depend &&\
>                 $(CRUNCHMAKE) $(BUILDOPTS) $(cat_OPTS) $(cat_OBJS))
> cat_clean:
>         (cd $(cat_SRCDIR) && $(CRUNCHMAKE) $(BUILDOPTS) clean cleandepend)
> 
> cat_stub.c:
>         echo "extern int main(int argc, char **argv, char **envp); int _crunched_cat_stub(int argc, char **argv, char **envp);int _crunched_cat_stub(int argc, char **argv, char **envp){return main(argc,argv,envp);}" >cat_stub.c
> cat.lo: cat_stub.o $(cat_OBJPATHS)
>         $(CC) -nostdlib -Wl,-dc -r -o cat.lo cat_stub.o $(cat_OBJPATHS)
>         crunchide -k _crunched_cat_stub cat.lo
> ```

If ld.lld makes `-dc` a no-op, does it still work? If stills works, seems a good idea to remove this option.

BTW: if your Clang has picked https://reviews.llvm.org/D117388 , you can drop `-nostdlib`.

**Comment by emaste** [comment]
I was trying to find out when -dc was introduced, and it has been there for more than 25 years since this utility was created. https://github.com/freebsd/freebsd-src/commit/de5663609e4ccd3c6a0845b917a2bf2b7b6ee0e7

**Comment by emaste** [comment]
Ah but I see this in a comment:
```
 * crunchide.c - tiptoes through a symbol table, hiding all defined
 *      global symbols.  Allows the user to supply a "keep list" of symbols
 *      that are not to be hidden.  This program relies on the use of the
 *      linker's -dc flag to actually put global bss data into the file's
 *      bss segment (rather than leaving it as undefined "common" data).
```

**Comment by MaskRay** [comment]
I think the comment is wrong. COMMON symbols don't lead to duplicate definition errors, but STB_GLOBAL ones (-dc -r output) do. Presumably `-dc` is never needed. Sent https://reviews.freebsd.org/D34215 with more detail.

**Comment by MaskRay** [comment]
Close by ce45c956942e4fe301102ed807efc726399623f9

**Comment by emaste** [comment]
Just to leave confirmation here - @MaskRay is correct, the comment was correct when written, but became invalid after a change and was not updated. From the FreeBSD review mentioned above:
 
> Looking more at [R10:7420b323a0148511e97e0467eec9919b2ec2c00e](https://reviews.freebsd.org/R10:7420b323a0148511e97e0467eec9919b2ec2c00e) confirms the above - crunchide previously operated by making the "hidden" symbols local, which was incompatible with common. -dc was unnecessary after that change.
