### ISSUE TITLE
makeNull needs deprecation in favor of makeNullWithType

### ISSUE THREAD

**Issue by vabridgers** [llvm/llvm-project#53664]
A recent issue uncovered with address spaces and the CString Checker exposed the need to deprecate makeNull in SValBuilder in favor of a method to make a null pointer that "right sized" per the prototype pointer's address space. See https://reviews.llvm.org/D118050 for details of the problem. 

This will involve the following steps:

1. Replace instances of makeNull with makeNullWithType
2. Replace instances of makeIntValWithPtrWidth with a more appropriate method to comprehend expected pointer size
3. Replace instances of getIntWithPtrWidth with a more appropriate method to comprehend expected pointer size

**Comment by steakhal** [comment]
+1

**Comment by steakhal** [comment]
Only the first patch has landed out of three if I'm correct.

**Comment by steakhal** [comment]
The rest of the patchset has landed.
