### ISSUE TITLE
Cherry-pick openmp fix to 14.x 

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#53676]
I don't know how this works, but

/cherry-pick 6be7c21

**Comment by tstellar** [comment]
@zmodem The commands aren't supported in the issue body (i.e. the first comment) yet (see https://reviews.llvm.org/D119312)

/cherry-pick https://github.com/llvm/llvm-project/commit/6be7c21b57e4a45b012209974ab9038b679134f5

**Comment by tstellar** [comment]
@jpeyton52 What do you think about backporting this? https://github.com/llvm/llvm-project/commit/6be7c21b57e4a45b012209974ab9038b679134f5

**Comment by jpeyton52** [comment]
Sounds good to me.

**Comment by jpeyton52** [comment]
Is there anything I need to do?

**Comment by tstellar** [comment]
Merged: 78f8449e01f7
