### ISSUE TITLE
exclude-libs will remove symbols of  whole-archive

### ISSUE THREAD

**Issue by CatDroid** [llvm/llvm-project#53675]
I use the following command: 
"-Wl,--whole-archive" lib1.a lib2.a " -Wl,--no-whole-archive"
with 
"-Wl,--exclude-libs=ALL" 
to a shared library "libShared.so "

In lib1.a and lib2.a static library，I export some function using "__attribute__((visibility("default")))".  But when I use exclude-libs flag , "libShared.so " shared library do not have these symbol . 

How I can export the symbol of lib1.a lib2.a,  but any other static libraries(lots of) do not ? 

https://reviews.llvm.org/D39353  this commit change it ?  "exclude-libs=ALL" will remove the symbols of "--whole-archive" ?

**Comment by MaskRay** [comment]
### `--exclude-libs`

If a matched archive (either regular or surrounded by `--whole-archive`/`--no-whole-archive`) defines a non-local symbol, don't export the symbol.

As an example, `clang++ -static-libstdc++ -Wl,--export-dynamic,--exclude-libs=libstdc++.a a.cc` does not export libstdc++ defined symbols.

Another way to suppress some exported symbols is to use a version script `local:`.
