### ISSUE TITLE
Cherry-pick "[clang] [MinGW] Recognize -lcrtdll as a library replacing -lmsvcrt" to 14.x

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#53688]

**Comment by tstellar** [comment]
@rnk What do you think about backporting this? https://github.com/llvm/llvm-project/commit/079b6d02d1f52301e2d3276fadba822bf87b75b2

**Comment by rnk** [comment]
Sounds good to me, seems safe, no ABI concerns.

**Comment by tstellar** [comment]
Merged: 1bdeb1b87719 816988d19a7a 200390c3c171
