### ISSUE TITLE
clang throws `error: expected expression` on valid code

### ISSUE THREAD

**Issue by kraj** [llvm/llvm-project#53692]
Following example fails to compile with clang 13 or clang 14

```c
void foo(int key, char *arg);

void foo(int key, char *arg)
{
        switch (key) {
                case 256:
                        char *s = arg ? arg : "mac";
        }
}

```

clang version 13.0.1

```
% clang man.c -c

man.c:7:4: error: expected expression
                        char *s = arg ? arg : "mac";
                        ^
1 error generated.
```
gcc version 11.1.0

```
% gcc man.c -c
```

it looks like clang is erroring on valid C code.

**Comment by kraj** [comment]
I see that below code
```c
void foo(int key, char *arg);

void foo(int key, char *arg)
{
        switch (key) {
                case 0:
                        ;
                        char *s = arg ? arg : "mac";
        }
}

```
compiles fine with clang

**Comment by EugeneZelenko** [comment]
GCC does not compile it too: https://godbolt.org/z/KsqEK6djr. And `"mac"` is literal, so should be `const chat*`.

**Comment by kraj** [comment]
> GCC does not compile it too: https://godbolt.org/z/KsqEK6djr. And `"mac"` is literal, so should be `const chat*`.

```
static const char astr[] = "mac";
void foo(int key, char *arg);

void foo(int key, char *arg)
{
        switch (key) {
                case 0:
                        char *s = arg ? arg : astr;
        }
}
```
fails in same way

**Comment by kraj** [comment]
I see godbolt uses `g++` to compile C files, so I made the example a bit better which compiles with g++ too but fails with `clang`  surprisingly it compiles ok with `clang++` now.

```
static const char astr[] = "mac";
void foo(int key, const char *arg);

void foo(int key, const char *arg)
{
        switch (key) {
                case 0:
                        const char *s = arg ? arg : astr;
        }
}

```

**Comment by EugeneZelenko** [comment]
Just use brackets in cases with local variable declarations.

**Comment by Endilll** [comment]
Confirmed on 17: https://godbolt.org/z/jnYeYKM4e

**Comment by Endilll** [comment]
CC @AaronBallman as this is C-specific.

**Comment by AaronBallman** [comment]
This code is not valid until C23; in C17 and earlier, the grammar for `compound-statement` and `labeled-statement` did not allow for a label to be followed by a `declaration`, it had to be followed by a `statement` (and declarations are not statements in C).

With https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2508.pdf, the grammar changed to allow a label to be followed by a declaration or a statement. We claim to implement that paper in Clang 16, but it seems we only handled the case where the label is at the end of a compound statement: https://godbolt.org/z/PrdbfTcjh

**Comment by AaronBallman** [comment]
This was addressed by https://github.com/llvm/llvm-project/commit/8bd06d5b6584 and should now be fixed.
