### ISSUE TITLE
OpenMP test fails on AArch64

### ISSUE THREAD

**Issue by rovka** [llvm/llvm-project#53696]
While running test-release.sh on AArch64, we get a failure in one of the OpenMP tests:
```
******************** TEST 'libomp :: atomic/kmp_atomic_float10_max_min.c' FAILED ********************
$ "/home/tcwg-buildslave/workspace/tcwg-llvm-release/tcwg-jade-03/rc1/Phase3/Release/llvmCore-14.0.0-rc1.obj/./bin/clang" "-fopenmp" "-pthread" "-fno-experimental-isel" "-I" "/home/tcwg-buildslave/workspace/tcwg-llvm-release/tcwg-jade-03/rc1/Phase3/Release/llvmCore-14.0.0-rc1.obj/projects/openmp/runtime/src" "-I" "/home/tcwg-buildslave/workspace/tcwg-llvm-release/tcwg-jade-03/rc1/llvm-project/openmp/runtime/test" "-L" "/home/tcwg-buildslave/workspace/tcwg-llvm-release/tcwg-jade-03/rc1/Phase3/Release/llvmCore-14.0.0-rc1.obj/lib" "-I" "/home/tcwg-buildslave/workspace/tcwg-llvm-release/tcwg-jade-03/rc1/llvm-project/openmp/runtime/test/ompt" "/home/tcwg-buildslave/workspace/tcwg-llvm-release/tcwg-jade-03/rc1/llvm-project/openmp/runtime/test/atomic/kmp_atomic_float10_max_min.c" "-o" "/home/tcwg-buildslave/workspace/tcwg-llvm-release/tcwg-jade-03/rc1/Phase3/Release/llvmCore-14.0.0-rc1.obj/projects/openmp/runtime/test/atomic/Output/kmp_atomic_float10_max_min.c.tmp" "-lm" "-latomic" "-mlong-double-80"
# command stderr:
clang-14: error: unsupported option '-mlong-double-80' for target 'aarch64-unknown-linux-gnu'
```

It looks like the [test file](https://github.com/llvm/llvm-project/blob/main/openmp/runtime/test/atomic/kmp_atomic_float10_max_min.c#L3) is requiring the x86 target to be available, but actually expects it to be the host target.

**Comment by tstellar** [comment]
This issue was not resolved in time for 14.0.0 and will need to be fixed in the next release (14.0.1).  If you disagree with this or you feel there was a mistake, please change the milestone back to 'LLVM 14.0.0 Release' so we can discuss.

**Comment by AndreyChurbanov** [comment]
> 
> It looks like the [test file](https://github.com/llvm/llvm-project/blob/main/openmp/runtime/test/atomic/kmp_atomic_float10_max_min.c#L3) is requiring the x86 target to be available, but actually expects it to be the host target.

Could you please elaborate more on what is "but actually expects it to be the host target"?
ARM people fixed the test (https://reviews.llvm.org/rG4ae885b1e3e783330b2914fde2be0791fb0a0302) so that is should run on x86 only, adding:
// REQUIRES: x86-registered-target
Was this fix incorrect? Should it be changed to something like
// REQUIRES: x86-target-arch
?
Sorry, I am not LIT testing expert, so please bear with my questions.

**Comment by rovka** [comment]
Hi @AndreyChurbanov, thanks for having a look. I don't think the fix is sufficient. If I understand correctly, x86-registered-target just means that we've built llvm with the x86 backend enabled (along with potentially other backends too), so we can cross-compile to x86. However, the test doesn't seem to be cross-compiling (and it probably doesn't intend to, otherwise it wouldn't call %libomp-run afterwards?), so it shouldn't pass -mlong-double-80, which is only supported on x86. 
Something like x86-target-arch would probably be a good idea, but I'm not sure if that exists for the openmp tests (I don't know anything about opnemp testing; there's one for [compiler-rt](https://github.com/llvm/llvm-project/blob/main/compiler-rt/test/lit.common.cfg.py#L349), but I'd have to dig more to figure out how the openmp tests are configured/run).

**Comment by shiltian** [comment]
This will be fixed in https://reviews.llvm.org/D142172. Thank @rovka for pointing to that file. I used exactly the same method.
