### ISSUE TITLE
Binary Build Naming Scheme Question

### ISSUE THREAD

**Issue by M3TIOR** [llvm/llvm-project#53691]
I was curious who uploaded the binary builds for the last release, and if they were uploaded manually, or if there's a reproducible naming scheme within the build pipeline. I'm currently trying to select a pre-built binary package in a personal C project of mine to extract the latest / a consistent version of clang-format from. I don't know if the Rust project is connected to LLVM internally at all or if y'all network, but some really good design went into the [Rust build target system](https://rust-lang.github.io/rfcs/0131-target-specification.html) and your binary builds follow a similar but not quite the same naming pattern. I was curious if maybe it's supposed to be the same and someone made a mistake, or if it's automated and using a publishing process with different logic.

**Comment by tstellar** [comment]
This would be a great question to ask on Discourse.  There is a sub-category specifically for the release testers: https://discourse.llvm.org/c/infrastructure/release-testers/

**Comment by M3TIOR** [comment]
@tstellar You're the one who uploaded the releases though 😆 !? You're tagged in the metadata. Should I just direct all my future inquiries to Discourse? Are you recommending that because you're just a product manager person who authors releases and has literally no idea what goes on during the build process?

**Comment by tstellar** [comment]
@M3TIOR It's other people that are doing the builds, I just verify and sign them.  It's up to the testers how to name the binaries, I'm not sure how each person decides which triple to use.

In general, questions like this will get more attention on Discourse, but if you have bugs please file them here.
