### ISSUE TITLE
Miscompile after b4b97ec813a02585000f30ac7d532dda74e8bfda

### ISSUE THREAD

**Issue by dyung** [llvm/llvm-project#53695]
A few of our internal tests started to fail recently which I bisected to commit b4b97ec813a02585000f30ac7d532dda74e8bfda. And when the commit was later reverted, the tests started to pass again.

I was able to create the following smaller test case that reproduces the issue:
```
extern "C" void printf(...);
template <typename T, typename> T protect_num(T in, int) { return in; }
template <typename T> T protect_den(T in, int) { return in; }
typedef int sint;
typedef unsigned uint;
typedef uint __attribute__((ext_vector_type(8))) uint8;
typedef sint __attribute__((ext_vector_type(8))) sint8;
typedef union {
  sint8 a;
  uint8 b;
} union_sint8_uint8;
struct {
  uint8 a;
} test69_struct_id14463;
uint8 test69_id14598{8036795, (uint)-1};
int main() {
  uint8 id14594 = test69_struct_id14463.a;
  test69_struct_id14463.a = test69_id14598;
  volatile union_sint8_uint8 id14600;
  id14600.a = -9;
  uint8 id14591(protect_num<uint8, uint>(id14594, 8) /
                protect_den(id14600.b, 8));
  printf("%x %x %x\n", id14591[2], id14591[1], id14591[2]);
}
```
To reproduce the issue, compile with optimizations and AVX enabled. Here is the output of the program before the change (correct code):
```
$ ~/src/upstream/588f121ada6d5418290e271bcaf2d1bada500912-linux/bin/clang -O2 -mavx test.cpp -o test.good.elf
$ ./test.good.elf 
0 0 0
```
After b4b97ec813a02585000f30ac7d532dda74e8bfda the program outputs the following:
```
$ ~/src/upstream/b4b97ec813a02585000f30ac7d532dda74e8bfda-linux/bin/clang -O2 -mavx test.cpp -o test.bad.elf
$ ./test.bad.elf
0 1 0
```

@rotateright this hopefully helps you to reproduce the problem with your change so that you can investigate it.

**Comment by rotateright** [comment]
Thanks @zeroomega ! I don't think we'll need your binaries, but I would definitely appreciate if you can check for failures after I post an updated patch.

I have a good handle on the bug in the old patch (although it's proving hard to minimize/isolate a test that is independent of other transforms), so I'm hoping to have an update for review/testing shortly.

**Comment by rotateright** [comment]
I reopened https://reviews.llvm.org/D118376 for review after updating the patch.
