### ISSUE TITLE
Merge 98936aee7d41 onto LLVM 14

### ISSUE THREAD

**Issue by brads55** [llvm/llvm-project#53705]
This commit fixes a selection failure for SVE when building with certain sized fixed length vectors.

**Comment by tstellar** [comment]
@TNorthover What do you think about backporting this? https://github.com/llvm/llvm-project/commit/98936aee7d41f9ae60dd06558fbbb1e6a4a89e17

**Comment by brads55** [comment]
@tstellar, @TNorthover Any update on this? We're keen to get this (as well as #53754) into the release as they both fix compilation failures in relevant workloads.

**Comment by tstellar** [comment]
@brads55 I pinged @TNorthover on Discord about this.

**Comment by tstellar** [comment]
Merged: 03d9a4094763
