### ISSUE TITLE
mlir/lib/ExecutionEngine/SparseTensorUtils.cpp doesn't compile on Solaris

### ISSUE THREAD

**Issue by rorth** [llvm/llvm-project#53702]
As described in [D119323](https://reviews.llvm.org/D119323), `mlir/lib/ExecutionEngine/SparseTensorUtils.cpp` doesn't compile on Solaris.  This is now fixed on `main`, but the `release/14.x` branch suffers the same issue (it was first discovered there) and it breaks the build.

/cherry-pick d2215e79ac27301c2a7cad36b5bfe20bd12837fb

**Comment by tstellar** [comment]
Failed to create pull request for 53702

**Comment by tstellar** [comment]
@aartbik What do you think about backporting this? https://github.com/llvm/llvm-project/commit/d2215e79ac27301c2a7cad36b5bfe20bd12837fb

**Comment by aartbik** [comment]
I am not very familiar with our branching model, but I approved the cherry pick. Do you need anything else from me for this bug?
Thanks for fixing!

**Comment by tstellar** [comment]
@aartbik You don't need to do anything else.  I just wanted your opinion on if this should be backported.

**Comment by tstellar** [comment]
Merged: 46266b3518b6
