### ISSUE TITLE
clang doesn't find gcc installations on Solaris

### ISSUE THREAD

**Issue by rorth** [llvm/llvm-project#53709]
Solaris can have multiple parallel GCC installations in `/usr/gcc/<N>`.  Until LLVM 13, all of them were found and the latest selected
```
clang version 13.0.0
Target: sparcv9-sun-solaris2.11
Thread model: posix
InstalledDir: /var/llvm/reghunt/gccinstdetector/./389486/bin
Found candidate GCC installation: /usr/gcc/10/lib/gcc/sparcv9-sun-solaris2.11/10.3.0
Found candidate GCC installation: /usr/gcc/11/lib/gcc/sparcv9-sun-solaris2.11/11.2.0
Found candidate GCC installation: /usr/gcc/7/lib/gcc/sparcv9-sun-solaris2.11/7.5.0
Found candidate GCC installation: /usr/gcc/9/lib/gcc/sparcv9-sun-solaris2.11/9.4.0
Selected GCC installation: /usr/gcc/11/lib/gcc/sparcv9-sun-solaris2.11/11.2.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
```
Afterwards, that got broken and only a apparently random one of those is ever considered:
```
clang version 13.0.0
Target: sparcv9-sun-solaris2.11
Thread model: posix
InstalledDir: /var/llvm/reghunt/gccinstdetector/./389487/bin
Found candidate GCC installation: /usr/gcc/10/lib/gcc/sparcv9-sun-solaris2.11/10.3.0
Selected GCC installation: /usr/gcc/10/lib/gcc/sparcv9-sun-solaris2.11/10.3.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```
It turns out this is the first one **in directory order** (`ls -f /usr/gcc`), so even when the same set of versions is installed on two systems, the selected one depends on the installation order.

I could trace this change to
```
commit 28d58d8fe2094af6902dee7b4d68ec30a3e9d737
Author: Fangrui Song <i@maskray.me>
Date:   Fri Mar 19 20:35:59 2021 -0700

    [Driver] Stop searching other prefixes once a GCC installation is found in one prefix
```

**Comment by MaskRay** [comment]
I don't have a Solaris or Sparc installation and cannot test or contribute fixes.

As you can see from the commit message, this more deterministic behavior is desired for generic GCC detection. Note that `ScanLibDirForGCCTriple` picks the larger version.

What's the value of `Prefixes` for your case?

**Comment by rorth** [comment]
> As you can see from the commit message, this more deterministic behavior is desired for generic GCC detection. Note that `ScanLibDirForGCCTriple` picks the larger version. `Prefixes` is ordered and we should stop when an installation is found to give precedence to options like `--sysroot`.

> What's the value of `Prefixes` for your case?

Omitting `$InstalledDir/..`, I have
```
  /usr/gcc/10
  /usr/gcc/7
  /usr/gcc/13
  /usr/gcc/11
  /usr/gcc/12
```
i.e. all parallel GCC installations in directory order (so effectively random).  `ScanLibDirForGCCTriple` doesn't help here since the different GCC versions live in different `Prefix`es.  With `Generic_GCC::GCCInstallationDetector::init` stopping after the first version found, the others are never even looked at.

**Comment by rorth** [comment]
@MaskRay I've initially tested a patch that just disabled the skip on Solaris, arguing that breaking the common case on that target in favor of a corner case (sysroot with older version) is justifiable.

However, afterwards I tried to reproduce the issue you describe in the commit message on an Ubuntu 20.04 system with versions 7, 8, 9, and 10 of gcc installed in parallel in `/usr/lib/gcc` and a minimal sysroot consisting of only gcc 4.7.  I couldn't reproduce your issue at all, neither with `clang-12` (where your patch is not yet present), `clang-13` (where it is), or `main` with the `Gnu.cpp` part of your patch reverted.  In all cases, only the tree specified with `--sysroot` was ever considered, and `strace` showed no hint of ever accessing gcc installations below `/usr/lib/gcc`.  This makes me wonder what exact scenariou you were seeing that prompted your patch.

That said, I believe that rather than stopping the iteration over gcc versions, the better approach would be to avoid getting non-sysroot prefixes into `Prefixes` in the first place (which already seems to happen).  Consider me confused...

**Comment by MaskRay** [comment]
I made a comment to your https://reviews.llvm.org/D157275 (`[Driver] Select newest GCC installation on Solaris`) that the special case seems to be added to an odd place.

`Generic_GCC::GCCInstallationDetector::AddDefaultGCCPrefixes` has special cases for Solaris and Linux with `/opt/rh`. I wonder whether you can update Solaris to have a better `Prefixes` that we don't change the early break code introduced in ` [Driver] Stop searching other prefixes once a GCC installation is found in one prefix`.

**Comment by rorth** [comment]
> `Generic_GCC::GCCInstallationDetector::AddDefaultGCCPrefixes` has special cases for Solaris and Linux with `/opt/rh` `[redhat]`. I wonder whether you can update Solaris to have a better `Prefixes` that we don't change the early break code introduced in ` [Driver] Stop searching other prefixes once a GCC installation is found in one prefix`.

I don't see how, unfortunately.  The Solaris directory structure is
- `Prefix = /usr/gcc/<V>`
- below that: `/lib/gcc/<triple>/<version>`

whereas on Linux (Ubuntu) you have

- `Prefix  = ` /usr`
- below that: `/lib/gcc/<triple>/<version>`

In both cases, the subdirectory structure is exactly what `ScanLibDirForGCCTriple` relies on.

However, one question remains unanswered: what is the exact situation your patch 28d58d8fe2094af6902dee7b4d68ec30a3e9d737 is meant to fix?  As described, I haven't yet been able to reproduce the failure from the commit message with or without the patch or in older versions of `clang` before the patch landed.

Instead, I've reverted the patch locally and re-tested on Ubuntu 20.04: no additional testsuite failures and the test described earlier (`--sysroot` pointing to to minimal sysroot with a gcc version smaller than any of the versions installed on the system) still reliably used the sysroot version.

**Comment by rorth** [comment]
I've now repeated my experiment (sysroot older than the earliest system gcc version) with the parent rev of your original patch.  Same outcome: only the sysroot version is printed with `clang -v`, none of the system ones.

**Comment by MaskRay** [comment]
> I don't see how, unfortunately. The Solaris directory structure is
> 
> Prefix = /usr/gcc/<V>
> below that: /lib/gcc/<triple>/<version>

OK, I see `Generic_GCC::GCCInstallationDetector::AddDefaultGCCPrefixes` `if (TargetTriple.getOS() == llvm::Triple::Solaris)` now.
IIUC the `/usr/gcc/<V>` directories are appended (`Prefixes.push_back(CandidatePrefix);`) in the directory iteration order.
I think we should sort the entries that will be appended to `Prefixes`.

The sorting is similar to `Prefixes.push_back("/opt/rh/gcc-toolset-12/root/usr");` below.

> However, one question remains unanswered: what is the exact situation your patch 28d58d8 is meant to fix? As described, I haven't yet been able to reproduce the failure from the commit message with or without the patch or in older versions of clang before the patch landed.

Previously, when `--sysroot=/sysroot` is specified and we find a GCC installation at `/sysroot/lib/gcc/6`, it may be overridden by `/usr/lib/gcc/7` (under `/usr`). This is an unexpected behavior as it's clear that the user doesn't want to use the system GCC installation.

**Comment by rorth** [comment]
> > I don't see how, unfortunately. The Solaris directory structure is
> > Prefix = /usr/gcc/
> > below that: /lib/gcc//
> 
> OK, I see `Generic_GCC::GCCInstallationDetector::AddDefaultGCCPrefixes` `if (TargetTriple.getOS() == llvm::Triple::Solaris)` now. IIUC the `/usr/gcc/<V>` directories are appended (`Prefixes.push_back(CandidatePrefix);`) in the directory iteration order, which is an unspecified order. I think we should sort the entries (by version) that will be appended to `Prefixes`.
> 
> The sorting is similar to `Prefixes.push_back("/opt/rh/gcc-toolset-12/root/usr");` below.

I've updated the patch accordingly now and will upload it shortly.  However, I'm concerned that this will hide all but the newest GCC version, unlike e.g. on Linux where the candiates are still listed.

> > However, one question remains unanswered: what is the exact situation your patch 28d58d8 is meant to fix? As described, I haven't yet been able to reproduce the failure from the commit message with or without the patch or in older versions of clang before the patch landed.
> 
> Previously, when `--sysroot=/sysroot` is specified and we find a GCC installation at `/sysroot/lib/gcc/6`, it may be overridden by `/usr/lib/gcc/7` (under `/usr`). This is an unexpected behavior as it's clear that the user doesn't want to use the system GCC installation. This old behavior can even cause some `clang/test/Driver` tests to fail when certain cross GCC packages are installed under `/usr/lib/gcc{,-cross}`.

I understand that, but as I've stated several times I've never been able to reproduce that behaviour: both with the parent rev of your patch and with your patch reverted locally on `main`, only the sysroot GCC inststallation is considered with `clang -v --sysroot`, never anything in `/usr`.  Being unable to reproduce that failure makes it difficult to argue with your patch or consider alternatives.

**Comment by MaskRay** [comment]
> > > I don't see how, unfortunately. The Solaris directory structure is
> > > Prefix = /usr/gcc/
> > > below that: /lib/gcc//
> > 
> > 
> > OK, I see `Generic_GCC::GCCInstallationDetector::AddDefaultGCCPrefixes` `if (TargetTriple.getOS() == llvm::Triple::Solaris)` now. IIUC the `/usr/gcc/<V>` directories are appended (`Prefixes.push_back(CandidatePrefix);`) in the directory iteration order, which is an unspecified order. I think we should sort the entries (by version) that will be appended to `Prefixes`.
> > The sorting is similar to `Prefixes.push_back("/opt/rh/gcc-toolset-12/root/usr");` below.
> 
> I've updated the patch accordingly now and will upload it shortly. However, I'm concerned that this will hide all but the newest GCC version, unlike e.g. on Linux where the candiates are still listed.

Using the newest GCC installation is by design. Specify `--gcc-install-dir=` to use an older GCC version.

> > > However, one question remains unanswered: what is the exact situation your patch 28d58d8 is meant to fix? As described, I haven't yet been able to reproduce the failure from the commit message with or without the patch or in older versions of clang before the patch landed.
> > 
> > 
> > Previously, when `--sysroot=/sysroot` is specified and we find a GCC installation at `/sysroot/lib/gcc/6`, it may be overridden by `/usr/lib/gcc/7` (under `/usr`). This is an unexpected behavior as it's clear that the user doesn't want to use the system GCC installation. This old behavior can even cause some `clang/test/Driver` tests to fail when certain cross GCC packages are installed under `/usr/lib/gcc{,-cross}`.
> 
> I understand that, but as I've stated several times I've never been able to reproduce that behaviour: both with the parent rev of your patch and with your patch reverted locally on `main`, only the sysroot GCC inststallation is considered with `clang -v --sysroot`, never anything in `/usr`. Being unable to reproduce that failure makes it difficult to argue with your patch or consider alternatives.

https://reviews.llvm.org/D157275 LGTM. As you've touched `Generic_GCC::GCCInstallationDetector::AddDefaultGCCPrefixes` and `Prefixes`, you shall see why keeping iteration on `Prefixes` (i.e. no early return) will cause `--sysroot=` to be overridden by a system GCC installation :)

**Comment by rorth** [comment]
/cherry-pick ae84ad15efd7ef7da95146e900ec72ceadf98058

It would be good to add this follow-on patch, too, which fixes `-Werror` builds:

/cherry-pick 18252e6c8e2b1bb9901b5cca9e9a75edfeda2c4e

**Comment by rorth** [comment]
It seems you can't have two cherry picks or additional text in one comment, so try again.

**Comment by tru** [comment]
you need to specify the both commits after each other so `cherry-pick one two` otherwise it will just overwrite them.

**Comment by rorth** [comment]
Ok, I see, thanks.  However, in this case the first of the two got taken, not the second overriding the first.

**Comment by rorth** [comment]
So it tried to cherry pick the second rev without the first one.  I guess I'll just wait what's decided for the first patch: if this is accepted and merged, I'll cherry pick the second again, when the merge conflict will resolve itself without intervention.  Without it, it's pointless anyway.

**Comment by tru** [comment]
/cherry-pick ae84ad15efd7ef7da95146e900ec72ceadf98058 18252e6c8e2b1bb9901b5cca9e9a75edfeda2c4e

**Comment by tru** [comment]
@rorth should be fixed now.
