### ISSUE TITLE
OCaml tests don't run with ounit-2-2.4

### ISSUE THREAD

**Issue by mgorny** [llvm/llvm-project#53708]
It seems that ounit upstream has changed the package name from `oUnit` to `ounit2`, and the rules inside LLVM's CMake files no longer run it. As a result, the respective tests are marked as unsupported and never run.

I've submitted a fix as https://reviews.llvm.org/D119079 but we might have trouble finding anyone to review it.

**Comment by tstellar** [comment]
Merged: 3d913ec92308
