### ISSUE TITLE
mlir/lib/Analysis/Presburger/Utils.cpp doesn't compile on Solaris

### ISSUE THREAD

**Issue by rorth** [llvm/llvm-project#53703]
As described in [D119324](https://reviews.llvm.org/D119324), `mlir/lib/Analysis/Presburger/Utils.cpp` doesn't compile on Solaris.  The issue is fixed for `main` now, but the same patch needs to go on the `release/14.x` branch where is was first discovered.

/cherry-pick 91596755359e29c677bfa84d86edcaa1e70df955

**Comment by tstellar** [comment]
@Superty What do you think about backporting this? https://github.com/llvm/llvm-project/commit/91596755359e29c677bfa84d86edcaa1e70df955

**Comment by Superty** [comment]
@tstellar That looks good to me.

**Comment by tstellar** [comment]
Merged: 9672d11441fd
