### ISSUE TITLE
[clang-format] Do not align explicitly-defaulted and deleted definitions via AlignConsecutiveAssignments: add a new style option for it

### ISSUE THREAD

**Issue by dfrib** [llvm/llvm-project#53718]
Hi,

I've noticed some inconsistencies with `AlignConsecutiveAssignments` that I would be happy to try to address myself, as an instructive journey (I haven't contributed to LLVM/clang-format before, beyond bug reports), as per the proposal below (/variations of it), if this is something of interest to fix.

### Inconsistent semantics

`AlignConsecutiveAssignments` applies not only to assignments but also to explicitly-defaulted ([\[dcl.fct.def.default\]](https://timsong-cpp.github.io/cppwp/n4868/dcl.fct.def.default)) and deleted ([\[dcl.fct.def.delete\]](https://timsong-cpp.github.io/cppwp/n4868/dcl.fct.def.delete)) function definitions, which are not _assignments_.

```cpp
// AlignConsecutiveAssignments: None
struct S
{
    S() = default;
    S(S const&) = default;
    S(S&&) = delete;
    void f() = delete;
};

void foo() = delete;
void foobar() = delete;
```
```cpp
// AlignConsecutiveAssignments: Consecutive
S()         = default;
S(S const&) = default;
S(S&&)      = delete;

void f()  = delete;
void ff() = delete;
```

### Inconsistent formatting
The semantic inconsistency is arguably nitpicking, but when we add copy and/or move assignment operators we start seeing some unexpected behavior, where apparently the leftmost `=` among the two in the assignment operator definition is use to align preceding "assignments" (/default/deleted defs), whereas the rightmost `=` is used to aligned "assignments" that follows:

```cpp
// AlignConsecutiveAssignments: AcrossComments
struct S
{
    S()        = default;
    S(S&&)     = delete;
    //         | <-- prior declarations align to leftmost = (operator=)
    S& operator=(S const&) = default;
    S& operator=(S&&) = delete;
    //                | <-- following declarations align to rightmost =
    void f()          = delete;
};

void foo()    = delete;
void foobar() = delete;
```

## Proposal

I propose that `AlignConsecutiveAssignments` should not affect alignment of explicitly-defaulted and deleted function definitions, and instead introduce a new style options for this use case, say the (the handful) `AlignConsecutiveDefaultedOrDeletedDefinitions`, which, when applied, would result in:

```cpp
struct S
{
    S()                    = default;
    S(S&&)                 = delete;
    S& operator=(S const&) = default;
    S& operator=(S&&)      = delete;
    void f()               = delete;
};

void foo()    = delete;
void foobar() = delete;
```

**Comment by dfrib** [comment]
@mkurdej Nice, thanks (I see https://github.com/llvm/llvm-project/commit/480a1fab72f4e367a5986d572914d252c318431d merged just three weeks ago :tada:).

Should we close this issue, or would it still be of interest to sort out the semantic inconsistency (`AlignConsecutiveDefaultedOrDeletedDefinitions`)?

**Comment by mkurdej** [comment]
I'm not a big fan of separating this and I guess there would be little to no traction to implement this.
I'm OK to close it.

**Comment by dfrib** [comment]
Ok, closing :+1:
