### ISSUE TITLE
[clang][integrated-as] "expected absolute expression" diffing symbols

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#53728]
```asm
.text
start:
  nop
end:
.if (end - start) == 0
.err
.endif
```
```
$ clang test-label.s -c
$
```
```asm
.text
.set start, .;
  nop
.set end, .;
.if (end - start) == 0
.err
.endif
```
```
$ clang test-symbol.s
test-symbol.s:6:5: error: expected absolute expression
.if (end - start) == 0
    ^
test-symbol.s:7:1: error: .err encountered
.err
^
$ as test-symbol.s 
$
```

reported [via lkml](https://lore.kernel.org/lkml/YgUmvuJYfycnhODA@FVFF77S0Q05N/)

**Comment by nickdesaulniers** [comment]
slightly reduced case:
```asm
.text
.set start, .
  nop
.set end, .
.if end - start
.err
.endif
```

From what I can tell, it looks like when recursive evaluating the `MCBinaryExpr::Sub` in `evaluateAsRelocatableImpl`, the call to `EvaluateSymbolicAdd` returns `true`. `MCExpr::evaluateAsAbsolute` thinks the `MCExpr` is relocatable but not absolute.

I would think if `.` is in the same section, we might be able to compute the difference.

Even
```asm
.text

.set start, .
  nop
.set end, .

.ifeq end, start
.err
.endif
```

**Comment by nickdesaulniers** [comment]
`AttemptToFoldSymbolOffsetDifference` in llvm/lib/MC/MCExpr.cpp looks like it might be helpful.

I feel like if the two symbols are in the same section (or at least the same fragment), we should be able to verify that their offsets are the same or different.

See also:
https://github.com/llvm/llvm-project/blob/ceb5dc55c2e395c085cd9d16c4152c5a1923d7e2/llvm/lib/MC/MCObjectWriter.cpp#L52
https://github.com/llvm/llvm-project/blob/ceb5dc55c2e395c085cd9d16c4152c5a1923d7e2/llvm/lib/MC/MCExpr.cpp#L649-L655

**Comment by pskocik** [comment]
Hi. I seem to be experiencing a relevant issue in that while code such as your test-label.s works from an assembly file
(on both gcc and clang):

```
.text
start:
  nop
end:
.if (end - start) == 0
.err
.endif
```
a straightforward re-rendering of it in a C file fails on clang (not gcc) with "expected absolute expression":

```
__asm(
".text\n"
"start:\n"
"  nop\n"
"end:\n"
".if (end - start) == 0\n"
".err\n"
".endif\n"
);
```

**Comment by musamaanjum** [comment]
I've hit the same bug. Clang gives an error with the following extended asm:
```
asm (
	".pushsection \".text\", \"ax\"\n\t"
	".balign 4096\n\t"
	"test_page: .globl test_page\n\t"
	".fill 4094,1,0xcc\n\t"
	"test_syscall_insn:\n\t"
	"syscall\n\t"
	".ifne . - test_page - 4096\n\t"
	".error \"test page is not one page long\"\n\t"
	".endif\n\t"
	".popsection"
    );
```

But clang builds fine if the asm is moved to the assembly file, or by generating the asm by GCC and then building the asm to binary by clang.

**Comment by MaskRay** [comment]
The original report of expression folding in `.if` for MCObjectStreamer has been fixed https://reviews.llvm.org/D69411 and my followups.

The last two comments are about `getUseAssemblerInfoForParsing()` and should be discussed at #62520
