### ISSUE TITLE
TestSNAP is stuck in applyToShadowMapEntries

### ISSUE THREAD

**Issue by shiltian** [llvm/llvm-project#53727]
OpenMP version of TestSNAP is stuck in `applyToShadowMapEntries` because `Itr` is not incremented in `CB`.

**Comment by tstellar** [comment]
@jdoerfert What do you think about backporting this? https://github.com/llvm/llvm-project/commit/c27f530d4c6306b2010306131f66e771d6a66594

**Comment by jdoerfert** [comment]
> @jdoerfert What do you think about backporting this? [c27f530](https://github.com/llvm/llvm-project/commit/c27f530d4c6306b2010306131f66e771d6a66594)

Yes, please. I broke this and it causes applications to be simply stuck in an endless loop :(
