### ISSUE TITLE
Backport f6685f774697 to LLVM 14.x

### ISSUE THREAD

**Issue by shiltian** [llvm/llvm-project#53723]

**Comment by tstellar** [comment]
@jdoerfert What do you think about backporting this? https://github.com/llvm/llvm-project/commit/f6685f774697c85d6a352dcea013f46a99f9fe31

**Comment by jdoerfert** [comment]
> @jdoerfert What do you think about backporting this? [f6685f7](https://github.com/llvm/llvm-project/commit/f6685f774697c85d6a352dcea013f46a99f9fe31)

Would be good. Not as important as some other fixes we have but also not risky. Fixes problematic behavior in some corner cases which is really hard to debug/understand.

**Comment by tstellar** [comment]
Merged: 9bc22aa50780
