### ISSUE TITLE
[Attributor] Loads in readonly functions are replaced with wrong value

### ISSUE THREAD

**Issue by jdoerfert** [llvm/llvm-project#53726]
Readonly function calls are assumed dead if the return value is assumed dead. This is OK but we cannot ignore them when we determine reachability as part of the identification of memory content, e.g., what value is loaded from some ptr. If we ignore the call, the load is not reachable from a store prior to the call, which then leads us to believe the load will result in a different value, often undef.

**Comment by tstellar** [comment]
Merged: 13fdc7afa8565810fb28793bd60b9a5cf8d0d978
