### ISSUE TITLE
Python 3.6 End of Life

### ISSUE THREAD

**Issue by astrelsky** [llvm/llvm-project#53738]
The Windows Release build are still being linked directly to Python 3.6 which reached it's end of life on December 23, 2021. It should be built with `Py_LIMITED_API` set to the lowest supported version or built with the latest and greatest.

Users shouldn't have to choose between installing an ancient version of python or building lldb from source just to use lldb. It also makes users more inclined to use an old version of python since it is much faster and easier to install an old version than it is to build lldb from source.

I'm aware this issue has been raised before and this will likely be closed. However, "...yell loud enough and somebody will eventually come over to see what all the fuss is about... not that they will actually do anything about it..."

Also as you can see [here](https://github.com/llvm/llvm-project/runs/5147017331?check_suite_focus=true#step:5:435) the tests on windows are being run with a build of lldb using python 3.10.1. Running the tests on one version and releasing a build with a much older one is not wise.

**Comment by JDevlieghere** [comment]
I don't think we've shipped prebuilt binaries for LLDB in a long time. Can you elaborate on what the "Windows Release build" is that you're referring to?

**Comment by astrelsky** [comment]
> I don't think we've shipped prebuilt binaries for LLDB in a long time. Can you elaborate on what the "Windows Release build" is that you're referring to? 

https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.1/LLVM-13.0.1-win64.exe

**Comment by JDevlieghere** [comment]
@tstellar do you know who builds the Windows installer?

**Comment by tstellar** [comment]
@JDevlieghere It's @zmodem .

**Comment by zmodem** [comment]
I'll try to look into this today. If it works, I'll use Python 3.10.1 going forward.

**Comment by astrelsky** [comment]
> I'll try to look into this today. If it works, I'll use Python 3.10.1 going forward.

What if the user has 3.9 installed? That doesn't actually solve anything. On windows for it to link to the installed version of python it needs to be compiled with `PY_LIMITED_API` which will result in it being linked to `python3.dll` instead of `python310.dll`. 

https://docs.python.org/3/c-api/stable.html#stable-application-binary-interface

**Comment by labath** [comment]
> I can't find any notes on this, but I seem to recall previous discussions about this concluding that LLDB uses more than what's available in the Limited API, so I'm not sure the flag would actually work.

Yes, I'd be surprised if it was simple as setting a cmake flag. LLDB does some fairly weird stuff with python so, I don't know whether it's even technically feasible to restrict ourselves to that, but in either case, someone with an interest in supporting this would have to step up and drive this effort.

Shiping lldb built with a non-EOLed python should be fairly easy, and definitely an improvement over the current situation.

Technically, it should also be possible to also ship python inside the lldb package, so that the user does not have to find a matching python version, but I don't know if that's something we can (or want to) do.

**Comment by astrelsky** [comment]
> > > I'll try to look into this today. If it works, I'll use Python 3.10.1 going forward.
> > 
> > 
> > What if the user has 3.9 installed? That doesn't actually solve anything. On windows for it to link to the installed version of python it needs to be compiled with `PY_LIMITED_API` which will result in it being linked to `python3.dll` instead of `python310.dll`.
> > https://docs.python.org/3/c-api/stable.html#stable-application-binary-interface
> 
> It seems to me the right place to set Py_LIMITED_API would be in the CMake files, so patches welcome.
> 
> I can't find any notes on this, but I seem to recall previous discussions about this concluding that LLDB uses more than what's available in the Limited API, so I'm not sure the flag would actually work.

Is the code which uses the Python C API generated by SWIG or is it manually written? If it isn't generated by SWIG then I can most certainly take a swing at it. This has bothered me for the longest time because lldb would be useless to me unless I built it myself.

There is some overhead involved with using the stable abi. The tl;dr is that instead of accessing some struct fields directly or via macros they are accessed via an exported function in the `python3.dll` that is essentially a thunk to the corresponding python version dll. Would it be preferred to set up a CMake option for this so that it can only be enabled for distributions?

**Comment by labath** [comment]
> Is the code which uses the Python C API generated by SWIG or is it manually written?

We have both. :) The main bindings are generated by swig, but there is also a fair amount of hand-written support code surrounding it.



> Would it be preferred to set up a CMake option for this so that it can only be enabled for distributions?

Ideally, we would just have a single build mode, and everything would "just work" everywhere, but it's hard to say without knowing what kind of changes would that entail. If you would be able to create some WIP/demo patches that demonstrate the idea, then we would be able to discuss this more meaningfully.

(BTW, note that lldb currently still has some python2 support code, but that functionality is on life support. As a part of this feature, we can definitely consider bumping the minimum supported version (to 3.7 maybe?), if that makes your job easier...)

**Comment by astrelsky** [comment]
> > Is the code which uses the Python C API generated by SWIG or is it manually written?
> 
> We have both. :) The main bindings are generated by swig, but there is also a fair amount of hand-written support code surrounding it.
> 
> 
> 
> > Would it be preferred to set up a CMake option for this so that it can only be enabled for distributions?
> 
> Ideally, we would just have a single build mode, and everything would "just work" everywhere, but it's hard to say without knowing what kind of changes would that entail. If you would be able to create some WIP/demo patches that demonstrate the idea, then we would be able to discuss this more meaningfully.
> 
> (BTW, note that lldb currently still has some python2 support code, but that functionality is on life support. As a part of this feature, we can definitely consider bumping the minimum supported version (to 3.7 maybe?), if that makes your job easier...)

I would completely destroy any python 2 support without hesitation or even mentioning it. 

I have yet to take a look at the code base. If it is a possibility what would you think about having the support code use the limited api and thus be forward compatible and then have pip packages for the swig generated code and let setuptools build it and/or have pre-built wheels on pypi? This is just a thought I had but once again I haven't looked at the code base yet so I don't know if it is even a possibility yet.

**Comment by labath** [comment]
I'm not against it, but I am having trouble imagining how such a thing would work.

Lldb is in a somewhat unique position of both offering a python api to other applications (so you can do "import lldb" in python), and also embedding python into itself (so you can do "script print(sys.path)" from within lldb). So even if you're just using the command line lldb, then you still need to have the swig code for /a/ python available (e.g. pretty printers may need it).

If it is possible to split things up such that the user can install a generic lldb package, and then also an lldb-python package matching his favourite python version, then I don't see any hard reason to not do that. (but note that I am not the one who is going to be building those packages, and the more complicated the process gets, the bigger the chance that noone will want to build a binary lldb package).

**Comment by zmodem** [comment]
For the time being, I've installed Python 3.10 (and coaxed the LLVM/LLDB build to use it, which was much harder than I expected), so the LLDB binaries from 14.0.0-rc2 and forward will be built against that.

Building LLDB is already the most complicated part of the Windows packages by far, so I'm hoping it won't get more complex. But having it not depend on a specific Python version would of course be a huge improvement.

**Comment by astrelsky** [comment]
I see where the Python usage is within LLDB itself. It is under `lldb/source/Plugins/ScriptInterpreter/Python`. I'll see what I can do but I make no promises.

**Comment by astrelsky** [comment]
This will take me a few weeks as I only have a small amount of free time to work on it. At the moment it looks like all that is needed is to remove stuff that is no longer applicable and to replace the `PyRunSimpleString` calls.

**Comment by astrelsky** [comment]
Are `PythonString`  or any of the classes in `PythonDataObjects.h` intended to be used outside of lldb? `PythonString::AsUTF8` can't return `llvm::StringRef` because `PyUnicode_AsUTF8String` returns a new reference to a bytes object and `PyUnicode_AsUTF8AndSize` isn't part of the stable api until 3.10.

I basically just need to know if I can completely remove functions or if I have to deprecate things.

**Comment by labath** [comment]
We are free to change the PythonDataObjects implementations as we see fit. We're only committed to maintaining the stability of the public lldb API (basically, the stuff in `include/lldb/API`)

**Comment by astrelsky** [comment]
> We are free to change the PythonDataObjects implementations as we see fit. We're only committed to maintaining the stability of the public lldb API (basically, the stuff in `include/lldb/API`)

Great thank you.

**Comment by astrelsky** [comment]
Just an update on progress. I think I have everything replaced with stable API components except for `PyRun_SimpleString` and `PyRun_String`. The `ScriptInterpreterPythonImpl` looks like it will be a challenge and I'll need to see if and what actually needs to be evaluated as a python string instead of just done through the c api. I will also take a look into accessing the loader and module api so that python itself will take care of compiling entire scripts and caching and whatever else it does under the hood. Once that is out of the way lldb itself will be free of a pre-set version and all that will be left is figuring  out what to do about the `pyd` and swig generated stuff.

If that doesn't make sense it is because I'm tired :sweat_smile:

**Comment by astrelsky** [comment]
I've decided to put this aside for now. I haven't had the free time to put any work into recently. If anyone wants to pick up where I left off I have what I did here.

https://github.com/astrelsky/llvm-project/tree/py_limited_api
