### ISSUE TITLE
polly uses `opt -analyze`

### ISSUE THREAD

**Issue by aeubanks** [llvm/llvm-project#53733]
the `-analyze` flag in `opt` is a legacy PM specific option and I'm trying to remove it. I've done some cleanup and at this point I believe polly is the only project left that uses `opt -analyze`.
Generally the preferred method to do something like this is some print pass that explicitly prints whatever you're looking to print.

**Comment by Meinersbur** [comment]
What is the downside of keeping it around when using `-enable-new-pm=0`?

**Comment by Meinersbur** [comment]
I can add print-passes that could replace the `-analyze` output. However, I would add these only for legacy PM and those that have already been ported to NPM (some passes are just difficult to pass to NPM and are not added to a default pass pipeline)

**Comment by aeubanks** [comment]
Using the legacy PM for the optimization pipeline is already deprecated and that support will be removed at some point (it was supposed to be removed after the LLVM 15 branch but there are some specific inliner issues preventing that right now, but should be sorted out soonish). Given that polly is part of the optimization pipeline, the legacy PM polly passes won't work at some point.

**Comment by aeubanks** [comment]
in other words, `-enable-new-pm=0` will only work with passes that are part of the codegen pipeline, since the codegen pipeline doesn't work with the new PM yet but still contains some IR passes.

**Comment by aeubanks** [comment]
this was fixed at some point given that `-analyze` no longer exists
