### ISSUE TITLE
Flang `bbc` printer may print IR that can't be parsed back.

### ISSUE THREAD

**Issue by banach-space** [llvm/llvm-project#53749]
## Summary
This issue came up recently on flang-compiler.slack.com (CC @joker-eph ). It looks like MLIR's verifier is failing to complain about orphan Ops floating around in the module.

## Note
Currently, this can only be reproduced with LLVM Flang from https://github.com/flang-compiler/f18-llvm-project. 

Tested with [7bf55bdf6f3](https://github.com/flang-compiler/f18-llvm-project/commit/7bf55bdf6f3b2447c02010a89c51d26a28313b8e). Please make sure to use the **fir-dev** branch!

#### Input file:
```fortran
block data
  real :: x
  common /block/ x
end
real :: x
common /block/ x
end
``` 
#### Run with Flang's compiler driver:
```bash
$ flang-new -fc1 -emit-mlir file.f90 -o -
module attributes {fir.defaultkind = "a1c4d8i4l4r4", fir.kindmap = "", llvm.target_triple = "aarch64-unknown-linux-gnu"}  {
  %0 = fir.address_of(@_QBblock) : !fir.ref<!fir.array<4xi8>>
  %1 = fir.convert %0 : (!fir.ref<!fir.array<4xi8>>) -> !fir.ref<!fir.array<?xi8>>
  %c0 = arith.constant 0 : index
  %2 = fir.coordinate_of %1, %c0 : (!fir.ref<!fir.array<?xi8>>, index) -> !fir.ref<i8>
  %3 = fir.convert %2 : (!fir.ref<i8>) -> !fir.ref<f32>
  fir.global common @_QBblock(dense<0> : vector<4xi8>) : !fir.array<4xi8>
  func @_QQmain() {
    return
  }
}
```
#### Run with Flang's bbc driver (lowers from Fortran to MLIR):
```bash
bbc -emit-fir file.f90 -o -
%0 = fir.address_of(@_QBblock) : !fir.ref<!fir.array<4xi8>>
%1 = fir.convert %0 : (!fir.ref<!fir.array<4xi8>>) -> !fir.ref<!fir.array<?xi8>>
%c0 = arith.constant 0 : index
%2 = fir.coordinate_of %1, %c0 : (!fir.ref<!fir.array<?xi8>>, index) -> !fir.ref<i8>
%3 = fir.convert %2 : (!fir.ref<i8>) -> !fir.ref<f32>
fir.global common @_QBblock(dense<0> : vector<4xi8>) : !fir.array<4xi8>
func @_QQmain() {
  return
}
```

## Discussion
The generated code is not valid - note the operations at module level. However, In both cases the MLIR's [verifier](https://github.com/llvm/llvm-project/blob/81cde474e2c5a6280cb693b777ddcf473825ae8a/flang/include/flang/Lower/Support/Verifier.h#L23-L30) pass is run and **does not** flag this up:
* In `flang-new` this is implemented [here](https://github.com/flang-compiler/f18-llvm-project/blob/fir-dev/flang/lib/Frontend/FrontendActions.cpp#L95-L99)
* In `bbc` this is implemented [here](https://github.com/flang-compiler/f18-llvm-project/blob/fir-dev/flang/tools/bbc/bbc.cpp#L260-L261)

All pointers are much appreciated, thanks!

**Comment by joker-eph** [comment]
From the point of view of MLIR this isn't invalid code: the "module" op is a simple container that is fairly non opinionated  and won't forbid someone from doing this.
You could enforce more with a "FIR module" that would only accept a specific list of operations (`FuncOp` and `GlobalOp`?).

This can be implemented with a specific attribute: dialect attribute have a verifier and so you can add an attribute `#fir.module` on the module op which will invoke your custom verifier on the module.

**Comment by joker-eph** [comment]
The original report in the chat was slightly different though in that:
```
$ cat case.f90 
block data
  real :: x
  common /block/ x
  data x / 1.234 /
end
real :: x
common /block/ x
print *,x
end
$ bbc -emit-fir case.f90 
$ tco case.mlir 
loc("case.mlir":7:3): error: redefinition of SSA value '%0'
Error can't load file case.mlir
```

Here bbc would emit an MLIR file that can't be parsed back. It does not seem to me that the test case you describe in the description here have the same behavior/

**Comment by banach-space** [comment]
Sorry, my bad, I focused on the wrong thing then. You will need this input instead:
```Fortran
block data
  real :: x
  common /block/ x
  data x / 1.234 /
end
real :: x
common /block/ x
print *,x
end
```

Next:
```bash
$ bin/bbc -emit-fir file.f90 -o - | bin/tco
loc("<stdin>":7:3): error: redefinition of SSA value '%0'
Error can't load file -
```

**Comment by joker-eph** [comment]
Ok this is buggy:
```
// Print the module without the "module { ... }" wrapper.
static void printModule(mlir::ModuleOp mlirModule, llvm::raw_ostream &out) {
  for (auto &op : *mlirModule.getBody())
    out << op << '\n';
  out << '\n';
}
```

It's in `bbc.cpp`

**Comment by joker-eph** [comment]
Actually re-opened and sending to flang

**Comment by kiranchandramohan** [comment]
The provided test works nows. @agozillon added the module wrapper in bbc (https://reviews.llvm.org/D144869).

Please reopen if there is still an issue.
