### ISSUE TITLE
Merge c53ad72aa936 onto LLVM 14

### ISSUE THREAD

**Issue by brads55** [llvm/llvm-project#53754]
This commit fixes another selection failure to do with Neon DAG combine code not being able to handle SVE fixed types.

**Comment by tstellar** [comment]
@TNorthover What do you think about backporting this? https://github.com/llvm/llvm-project/commit/c53ad72aa93646a3ab1b9b2307319a7389a51039

**Comment by TNorthover** [comment]
Yep, another very simple change.

**Comment by tstellar** [comment]
Merged: 1362f8bdfce7
