### ISSUE TITLE
Backport 2937b28 onto LLVM 14

### ISSUE THREAD

**Issue by DavidSpickett** [llvm/llvm-project#53753]
This commit allows the "memory region" command to be used when the address argument has non address bits. Pointer signatures, top byte tags or memory tags.
(and if approved for backport I'll remove the release notes entry from `main`)

**Comment by tstellar** [comment]
@omjavaid Does this look OK to backport? https://github.com/llvmbot/llvm-project/pull/43

**Comment by omjavaid** [comment]
LGTM

**Comment by tstellar** [comment]
Merged: af19ae529271f9ae96927662d7d876489115fb26
