### ISSUE TITLE
VectorCombine::scalarizeLoadExtract - suspicous null check after use

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#53761]
https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/Vectorize/VectorCombine.cpp#L1024
```
    // Check if any instruction between the load and the extract may modify
    // memory.
    if (LastCheckedInst->comesBefore(UI)) {
      for (Instruction &I :
           make_range(std::next(LI->getIterator()), UI->getIterator())) {
        // Bail out if we reached the check limit or the instruction may write
        // to memory.
        if (NumInstChecked == MaxInstrsToScan || I.mayWriteToMemory())
          return false;
        NumInstChecked++;
      }
    }

    if (!LastCheckedInst)
      LastCheckedInst = UI;
    else if (LastCheckedInst->comesBefore(UI))
      LastCheckedInst = UI;
```
Not only are we checking for !LastCheckedInst after we've already dereferenced LastCheckedInst, we also have a second LastCheckedInst->comesBefore(UI) check.

CC @fhahn and @rotateright

**Comment by fhahn** [comment]
Thanks, the checks were indeed redundant and the `LastCheckedInst = UI;` assignment can be moved to the preceding if. Should be done in c141d158e5d330c751966ed9814161eadcae086b
