### ISSUE TITLE
Backport ba9a7ae798053d7cf741143739351b5a4ac29d8b f35ac872b8224f771808a9ecd5c4da0fe307ac9c 541c9ba842256023611e5a6c5f01e01c40688044 to LLVM 14

### ISSUE THREAD

**Issue by topperc** [llvm/llvm-project#53772]
Please backport these patches to LLVM 14

ba9a7ae798053d7cf741143739351b5a4ac29d8b  <- new test case
f35ac872b8224f771808a9ecd5c4da0fe307ac9c <- reverts broken patch
541c9ba842256023611e5a6c5f01e01c40688044 <- alternate fix for original bug

**Comment by asb** [comment]
LGTM.

**Comment by tstellar** [comment]
/cherry-pick ba9a7ae798053d7cf741143739351b5a4ac29d8b f35ac872b8224f771808a9ecd5c4da0fe307ac9c 541c9ba842256023611e5a6c5f01e01c40688044

**Comment by tstellar** [comment]
Merged: 8f8a31ec88b5 e22573ab7b2d 3b544440f631
