### ISSUE TITLE
[ld.lld] Add `-z pack-relative-relocs` with the GLIBC_ABI_DT_RELR version lockout mechanism

### ISSUE THREAD

**Issue by joebonrichie** [llvm/llvm-project#53775]
Binutils 2.38 was recently released with support for packed relative relocs however, they used their own naming convention for the option.

Unfortunately it is generally up to LLVM to add interoperability with GCC toolchain bits rather than the other way around, therefore, hopefully lld can provide an alias to `-z,pack-relative-relocs` to avoid ifdefs when enabling support for this feature.

**Comment by MaskRay** [comment]
The option is spelled as `-z pack-relative-relocs`. The comma form is for the compiler driver option: `-Wl,-z,pack-relative-relocs`.

`-z pack-relative-relocs` is not quite an alias. It adds a version definition `GLIBC_ABI_DT_RELR` if there is a version node called `GLIBC_2.*`. This is to implement a (Solaris calls it) "time travel compatibility" / (some glibc folks call it) "version lockout" mechanism: https://maskray.me/blog/2021-10-31-relative-relocations-and-relr

I am mostly waiting on the glibc status update (search `DT_RELR` on https://sourceware.org/pipermail/libc-alpha/2022-February/). I think it is not urgent to add this to ld.lld.

**Comment by sunnyflunk** [comment]
I've been looking at enabling RELR in Serpent OS (which is only at the container stage atm) as testing suggests faster startup on top of the reduced size. There's no problems for us in terms of different linker names to enable them as we handle flags per toolchain.

All the problems have related to `GLIBC_ABI_DT_RELR`, and how LLD doesn't add the dependency, in particular:
"Issue an error if there is a DT_RELR entry without GLIBC_ABI_DT_RELR dependency nor GLIBC_PRIVATE definition." [1]

My experience was that building with LLD `--pack-dyn-relocs=relr` no longer works (links but glibc won't load it) with the full `[PATCH v3 0/5] Support DT_RELR relative relocation format` patch set. Currently I am reverting two patches [1-2] and early testing (but a full rebuild is needed) suggests it works for both gcc/bfd and clang/lld RELR builds:

[1] https://sourceware.org/pipermail/libc-alpha/2022-February/136288.html
[2] https://sourceware.org/git/?p=binutils-gdb.git;a=patch;h=72aa81732b3aff00e5bf1f69bb794513b3b37464

**Comment by MaskRay** [comment]
I created https://reviews.llvm.org/D120701 to add `-z pack-relative-relocs` which implements the glibc `GLIBC_ABI_DT_RELR` version dependency.

**Comment by joebonrichie** [comment]
Thanks, we'll enable DT_RELR by default in Solus once everything is ready, we needed the interoperability as we default to lld for clang builds.
