### ISSUE TITLE
Merge `[asan] Always skip first object from dl_iterate_phdr` into release/14.x

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#53782]
Fix `clang -shared-libsan/-shared-libasan` and GCC's default (shared-libasan) on Linux musl.

/cherry-pick d75a5650dbdc595f836db4711f2a480f87243593

**Comment by MaskRay** [comment]
/cherry-pick d75a5650dbdc595f836db4711f2a480f87243593

(the command in the first comment doesn't work?)

**Comment by tstellar** [comment]
> /cherry-pick [d75a565](https://github.com/llvm/llvm-project/commit/d75a5650dbdc595f836db4711f2a480f87243593)
> 
> (the command in the first comment doesn't work?)

Not yet, but I have a patch to fix this: https://reviews.llvm.org/D119312

**Comment by tstellar** [comment]
It looks like this was reverted upstream?

**Comment by tstellar** [comment]
This issue was not resolved in time for 14.0.0 and will need to be fixed in the next release (14.0.1).  If you disagree with this or you feel there was a mistake, please change the milestone back to 'LLVM 14.0.0 Release' so we can discuss.

**Comment by MaskRay** [comment]
/cherry-pick 795b07f5498c7e5783237418f34d7ea69e801f87

The new try fixed the issue with glibc<2.15 (and some patched by distributions like Fedora/Ubuntu).

**Comment by tstellar** [comment]
Merged: a36801750327
