### ISSUE TITLE
Many missed uninit bugs by address/memory sanitizers

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#53787]
Inspired by this post
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/S75EUIQ5Y3MXNXVPFFX4XHE7CW3SKULU/

+ changed func7 tu return local variable instead of global (which is zero initialized)

LINK: https://godbolt.org/z/TbP4jdGbf

clang-12 l.c -Wall -Wextra
variable 'j' is uninitialized when used here [-Wuninitialized]
variable 'num' is uninitialized when used here [-Wuninitialized]
2/8

clang-12 -fsanitize=address l.c
no detected errors

clang-12 -fsanitize=memory l.c
SUMMARY: MemorySanitizer: use-of-uninitialized-value in func2
1/8

clang-12 -fsanitize=undefined l.c
no errors

clang-12 -g l.c ; valgrind  ./a.out 
valgrind catches all bugs

**Comment by vitalybuka** [comment]
as-is msan reports branching on uninitialized value, similar to valgrind

func1/func2 detects https://godbolt.org/z/h45cP91bd
func3 detects https://godbolt.org/z/ve85Ynh9f
func4/5 detects https://godbolt.org/z/f74KMYcKb
func6 detects https://godbolt.org/z/aM9MqKqrc
printfs ignores as is https://godbolt.org/z/5b79jcbf9
func7  ignores as is, but valgrind as well
func8 detects https://godbolt.org/z/7jfb4cP6M
switch (color) neither msan nor valgrind detects it

New clang 15 supports -fsanitize-memory-param-retval which will report func7 and printfs https://godbolt.org/z/P43744o3Y

**Comment by vitalybuka** [comment]
I assume this can be closed?
