### ISSUE TITLE
Clang 14 regression in HIP and CUDA mode: error: dynamic initialization is not supported for __device__, __constant__, __shared__, and __managed__ variables.

### ISSUE THREAD

**Issue by Oblomov** [llvm/llvm-project#53780]
The following test case:

```cpp
template<typename Option>
struct option_range
{
	static constexpr bool defined = false;
};

#define DEFINE_OPTION_RANGE(_option, _names,_min, _max) \
template<> \
struct option_range<_option> \
{ \
	static constexpr _option min = _min; \
	static constexpr _option max = _max; \
	static constexpr bool defined = true; \
	static constexpr auto names = _names; \
}

enum Op
{
	OP1, OP2, OP3
};

//! Name of the viscous model
const char* OpName[OP3+1]
{
	"OP1",
	"OP2",
	"OP3",
};

DEFINE_OPTION_RANGE(Op, OpName, OP1, OP3);
```
fails to build with `clang++-14 -c -x hip`  or  `clang++-14 -c -x cuda`, with the error:
```
error: dynamic initialization is not supported for __device__, __constant__, __shared__, and __managed__ variables.
DEFINE_OPTION_RANGE(Op, OpName, OP1, OP3);
^                       ~~~~~~
<stdin>:14:24: note: expanded from macro 'DEFINE_OPTION_RANGE'
        static constexpr auto names = _names; \
                              ^       ~~~~~~
```
The code works with Clang 13, again when building for either HIP or CUDA, and with any other compiler (GCC, Clang 11 to 13) when building for host.

**Comment by yxsamliu** [comment]
@Artem-B 

It can be reproduced here: https://godbolt.org/z/Gd8jPnfcq

Problem is that OpName is not a const array. Users can change its content in host code, and the change cannot be seen by device code. Therefore, we cannot assume it is the same constant on device and host, therefore we cannot promote it as a constant variable on device side.

Change it to "const char* const OpName[OP3+1]" will make the variable promotable to constant on device side and let the test pass.

**Comment by Oblomov** [comment]
Oh, interesting. I should const-ify the array(s) anyway, but why would simply declaring the structure (that never gets used device side, even in the real code) lead to this error? The error message is also confusing because it appears at a point where none of the mentioned attributes is used.

**Comment by Artem-B** [comment]
> const char* const OpName[OP3+1]

`constexpr char* OpName[OP3+1]` works, too: https://godbolt.org/z/GzPd5b8KG

**Comment by yxsamliu** [comment]
https://reviews.llvm.org/D119615

**Comment by Oblomov** [comment]
In the mean time I found out that in the real code the added `const` isn't actually sufficient as solution/workaround because these declarations are in a header file, with a preprocessor switch around the array definition that puts _either_ an  `extern` attribute _or_ the definition of the entries, like:

```c
#ifndef DEFINE_ENTRIES
extern
#endif
const char* OpName[OP3+1]
#ifdef DEFINE_ENTRIES
= {
	"OP1",
	"OP2",
	"OP3",
}
#endif
;
```
and apparently the `extern` in this case is interfering again, see e.g. https://godbolt.org/z/oroovsoYM
I'm guessing we could take the opportunity to simplify all this, turning them into `constexpr` arrays per @Artem-B's suggestion (assumig this doesn't end up ODR-biting us in our setup ...).

That being said, the proposed patch sounds reasonable, and it avoids the current violation of the principle of least surprise (device-related error message for something that isn't used on device).
