### ISSUE TITLE
clang-format crash

### ISSUE THREAD

**Issue by AlanGillespie** [llvm/llvm-project#53790]
I have been using clang-format 14.0.0-rc1 to format the tinycc sources at https://repo.or.cz/w/tinycc.git, and it crashes on three of the files - i386-asm.c, tccmacho.c, and tccrun.c. The crash reports are:

PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: clang-format-14.0.0-rc1.exe --verbose --style=file -i i386-asm.c
0x00007FF7F195B140 (0x0000000000000000 0x000000000013BC30 0x0000245A00000004 0x000000000000253A)
0x00007FF7F195A1CE (0x000000000000253A 0x000000005038C7B0 0x000000300000002E 0x000000095038B088)
0x00007FF7F195999E (0x000000305038E500 0x000000305038C7B0 0x000000305038ACC8 0x000000305038C7B0)
0x00007FF7F1955E76 (0x000001591EAA0000 0x00007FFA00000000 0x00000000003F002F 0x0000000000000096)
0x00007FF7F191DC48 (0x000000305038BA30 0x00007FF7F193B6CF 0x2F2A20636E202A2F 0x202C333000000000)
0x00007FF7F193B09A (0x0000000000000002 0x0000000000000003 0x000000015038CBF0 0x000000000000004F)
0x00007FF7F192C0B4 (0x00000000000009FB 0x0000000000000000 0x00000000000009FB 0x00000159AA0814B6)
0x00007FF7F191539A (0x000001591EAC05B0 0x00007FFA18B547B1 0x0000000000000000 0x000001591EAA0000)
0x00007FF7F1915F19 (0x0000BC83FFFBFABB 0x000000305038E840 0x000000000000014C 0x00007FFA163910D3)
0x00007FF7F18844B8 (0x000001591EAC9E60 0x0000000000000002 0x0000000000000000 0x000000000000000E)
0x00007FF7F18827C6 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x006C006C0064002E)
0x00007FF7F1A42BF8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFA171C7034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFA18B82651 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)

Assertion failed: idx < size(), file C:\src\llvm_package_1400-rc1\llvm-project\llvm\include\llvm/ADT/SmallVector.h, line 277
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: clang-format-14.0.0-rc1.exe --verbose --style=file -i tccmacho.c
0x00007FF7F18B5D96 (0x000036EC76F147F2 0x00007FFA1692FDE6 0x0000000000000016 0x00007FF7F18B5D90)
0x00007FFA16991881 (0x0000000000000101 0x00007FF700000000 0x0000000000000000 0x000000D48AB8A8E0), raise() + 0x1E1 bytes(s)
0x00007FFA16992851 (0x00007FFA00000003 0x00007FFA00000003 0x00007FF7F1A45A04 0x00007FF7F1A45968), abort() + 0x31 bytes(s)
0x00007FFA169941B5 (0x0000000000000115 0x00007FF7F1A45A04 0x0000000000000000 0x000000D48AB8AFB8), _get_wpgmptr() + 0x18A5 bytes(s)
0x00007FFA169944F1 (0x000000D48AB8AFB8 0x00000000D3582560 0x0000000000000016 0x0000025DD57D8040), _wassert() + 0x71 bytes(s)
0x00007FF7F195BB2C (0x0000000000000081 0x0000000000009812 0x00000000000019FE 0x0000001600000004)
0x00007FF7F195B7DB (0x0000000000000000 0x00000000000DFF48 0x000019FC00000002 0x0000000000001A6D)
0x00007FF7F195A1D9 (0x0000000000001A6D 0x000000008AB8C6E0 0x000000D40000000E 0x000000058AB8AFB8)
0x00007FF7F195999E (0x000000D48AB8E430 0x000000D48AB8C6E0 0x000000D48AB8ABF8 0x000000D48AB8C6E0)
0x00007FF7F1955E76 (0x0000000000000000 0x0000000000000000 0x0000025D00000000 0x0000025DD3596C60)
0x00007FF7F191DC48 (0x000000D48AB8B960 0x00007FF7F193B6CF 0x4545525F434C2020 0x59445F5400000000)
0x00007FF7F193B09A (0x0000000000000002 0x0000000000000003 0x000000D48AB8CB20 0x000000000000004F)
0x00007FF7F192C0B4 (0x0000000200000003 0x0000010100000000 0x00000000000003FF 0x0000000000000000)
0x00007FF7F191539A (0x0000025DD355ED50 0x00007FFA18B547B1 0x0000000000000000 0x0000025DD3540000)
0x00007FF7F1915F19 (0x000036EC76F10D52 0x000000D48AB8E770 0x000000000000014C 0x00007FFA163910D3)
0x00007FF7F18844B8 (0x0000025DD3566CA0 0x0000000000000002 0x0000000000000000 0x000000000000000E)
0x00007FF7F18827C6 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x006C006C0064002E)
0x00007FF7F1A42BF8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFA171C7034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFA18B82651 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)

PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: clang-format-14.0.0-rc1.exe --verbose --style=file -i tccrun.c
0x00007FF7F195B140 (0x0000000000000000 0x0000000000089430 0x0000102C00000009 0x000000000000102E)
0x00007FF7F195A1CE (0x000000000000102E 0x000000000A18C670 0x0000008500000001 0x000000010A18AF48)
0x00007FF7F195999E (0x000000850A18E3C0 0x000000850A18C670 0x000000850A18AB88 0x000000850A18C670)
0x00007FF7F1955E76 (0x000001D367E9A150 0x0000000000000000 0x000001D36843E630 0x000000000000016B)
0x00007FF7F191DC48 (0x000000850A18B8F0 0x00007FF7F193B6CF 0x5F74725F203D2070 0x230A3B7200000000)
0x00007FF7F193B09A (0x0000000000000002 0x0000000000000003 0x000000850A18CAB0 0x000000000000004D)
0x00007FF7F192C0B4 (0x00007FF9000003FF 0x0000000000000000 0x0000000000000807 0x00007FFA49090040)
0x00007FF7F191539A (0x000001D365F3E300 0x00007FFA18B547B1 0x0000000000000000 0x000001D365F20000)
0x00007FF7F1915F19 (0x00009B771F6A67D0 0x000000850A18E700 0x000000000000004C 0x00007FFA163910D3)
0x00007FF7F18844B8 (0x000001D365F487E0 0x0000000000000002 0x0000000000000000 0x000000000000000E)
0x00007FF7F18827C6 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x006C006C0064002E)
0x00007FF7F1A42BF8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFA171C7034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFA18B82651 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)

clang-format from all the LLVM 13 releases fail in a similar fashion. The last release that completes successfully is LLVM 12.

**Comment by mkurdej** [comment]
Hi, could you please send a minimal repro (removing parts of the file that don't provoke the crash) as well as the .clang-format config file?

**Comment by mydeveloperday** [comment]
@AlanGillespie your repo doesn't contain a .clang-format file? can you add it here?

**Comment by mydeveloperday** [comment]
For default LLVM style these 3 files do format, I suspect you are hitting something specific? we need your .clang-format file to know what.

**Comment by mkurdej** [comment]
Closing because of lacking info. @AlanGillespie, please provide more information (.clang-format file) and reopen.
