### ISSUE TITLE
[M68k] Rewrite the current disassembler upon code beads deprecation

### ISSUE THREAD

**Issue by mshockwave** [llvm/llvm-project#53798]
Following up #48320 : Since the current disassembler relies on code beads to distinguish different operand addressing modes, it needs an overhaul when the code beads infrastructure is being deprecated.

We can adopt prefix tree or similar ideas (credit @ricky26 ) in this new disassembler. We can even generalize it with a TableGen backend (i.e. generating disassembler from instruction encoding info), as counterpart of the existing `FixedLenDecoderEmitter`.

**Comment by 0x59616e** [comment]
@mshockwave have you started on this ? If not, I would like to do this.

**Comment by mshockwave** [comment]
> @mshockwave have you started on this ? If not, I would like to do this.

I'm not working on it right now. @ricky26 are you working on this?

**Comment by ricky26** [comment]
No, not yet. I was planning to take a look when I got time but I'm happy to let someone else have it. :slightly_smiling_face:

**Comment by 0x59616e** [comment]
I'm looking into FixedLenDecoderEmitter to see whether it's possible to adopt M68k's VarLen infrastucture. I'll reach out to you if I have ideas.

**Comment by 0x59616e** [comment]
> I'm looking into FixedLenDecoderEmitter to see whether it's possible to integrate M68k's VarLen infrastucture. I'll reach out to you if I have ideas.

We can use this TableGen backend to generate decoder by pretending our instructions **to be the same length** (i.e. maximum possible length). 

This method has a drawback: we have to give decoder the instruction with maximum length (since we pretend all the instructions have that length) even the instruction is not that long.

Would you prefer a new TableGen backend, or reuse the existing FixedLenDecoderEmitter ?

**Comment by 0x59616e** [comment]
see [here](https://github.com/0x59616e/llvm-project/blob/reuse_disassembler/llvm/lib/Target/M68k/Disassembler/M68kDisassembler.cpp#L466) for detail

**Comment by mshockwave** [comment]
Thank you for the prototype. Though I only skimmed through your code, I think in addition to the length issue, another one is how to handle sub-operands properly. If we can tell the decoder that a particular bit range maps to a sub-operand -- which I didn't see related changes in your code -- I believe it can simplify a lot of things.

**Comment by mshockwave** [comment]
> If we can tell the decoder that a particular bit range maps to a sub-operand -- which I didn't see related changes in your code -- I believe it can simplify a lot of things.

This is just a rough idea that popped into my mind though, feel free to explore other options as your will :-)

**Comment by 0x59616e** [comment]
Thanks for sharing ideas ;). You're right, I have yet to consider the operand decoding.

I'll keep exploring this way.

**Comment by 0x59616e** [comment]
FYI
- The disassembler now can decode data register and immediate.
- The problem about instruction length is solved by adding additional instruction length table and a callback function to adjust the instruction encoding. See [here](https://github.com/0x59616e/llvm-project/commit/789e9ca1857ed76a0999558b38f7ab55c907127b) for more detail

Example:
```
$ cat bits.txt 
# CHECK: btst #0, %d3
0x08 0x03 0x00 0x23

$ llvm-mc -disassemble -triple=m68k bits.txt --debug
Args: llvm-mc -disassemble -triple=m68k bits.txt --debug 
        .text
0: OPC_ExtractField(12, 4): 0
3: OPC_FilterValue(0, 1581): PASS: continuing at 8
8: OPC_ExtractField(4, 5): 0
11: OPC_FilterValue(0, 65): PASS: continuing at 16
16: OPC_ExtractField(9, 3): 4
19: OPC_FilterValue(4, 11): PASS: continuing at 24
24: OPC_CheckField(24, 1, 0, 5514): FieldValue = 0, ExpectedValue = 0: PASS
31: OPC_Decode: opcode 408, using decoder 0: PASS
        btst    #35, %d3
```

I think the disassembler is almost done. Stay tuned ;)

**Comment by 0x59616e** [comment]
I've created to patches: [D120605](https://reviews.llvm.org/D120605), [D120606](https://reviews.llvm.org/D120606).
