### ISSUE TITLE
Phabricator x64-debian build host constantly has build failures

### ISSUE THREAD

**Issue by brad0** [llvm/llvm-project#53801]
Can anything be done about the constant timeouts and other minor build failures with the x64-debian host being used by Phabricator for build checks? It reduces it's value a bit when it constantly has issues.

99% of the tests pass but it seems like there will always be something like 1 - 5 tests that will randomly timeout or maybe 1 - 2 fail that has nothing to do with the patches being posted.

**Comment by brad0** [comment]
Just to add to this I see there is an x64-windows host that I have never seen any timeouts or errors from. So I was wondering if there is any room for improvement on the Debian host.

**Comment by metaflow** [comment]
@brad0 I would love to improve the situation and I thought that it's just normal to have these tests flaky. Maybe there is something missing in deps? I will try to compare premerge bot setup with e.g. buildbots.

**Comment by brad0** [comment]
When I look at build logs of both the Debian and Windows hosts I see tests that pass on the Windows host that for example timeout on the Debian host.
