### ISSUE TITLE
[DSE] Unreachable terminator (exit call) prevents store elimination

### ISSUE THREAD

**Issue by wsmoses** [llvm/llvm-project#53800]
See: https://godbolt.org/z/7rhP5rdrP

```llvm
define void @nodse(i64* noalias nocapture noundef writeonly %domain, i1 noundef zeroext %bad) {
entry:
  store i64 1, i64* %domain, align 8
  br i1 %bad, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  tail call void @exit(i32 noundef 1) #3
  unreachable

if.end:                                           ; preds = %entry
  store i64 0, i64* %domain, align 8
  ret void
}

declare dso_local void @exit(i32 noundef) local_unnamed_addr #3

attributes #3 = { noreturn nounwind }
```

The first store of 1 should be eliminated by dse.

However, the call to exit/subsequent unreachable prevents DSE. Changing the unreachable to a branch to if.end restores DSE.

Presumably this is because the postdominatortree considers unreachable's separate exit points. In any case, a call to a program-terminating call shouldn't prevent DSE from applying.

Possibly related to: https://reviews.llvm.org/D12676

**Comment by davidbolvansky** [comment]
@fhahn 

(there was a patch for such “partial” DSE, no?)

**Comment by fhahn** [comment]
> (there was a patch for such “partial” DSE, no?)

I don't think so. But we should be able to fall back to the regular backwards CFG scan, if we have root nodes in the post-dominator tree that have unreachable terminators. This means we execute the slower scan potentially more often, but it looks like there's no noticeable compile-time impact if we do that: https://llvm-compile-time-tracker.com/compare.php?from=e967d97a35a93c883528a9672159edff05f5addb&to=aa43d315d1560285aa302017dd07067ee8e8565a&stat=instructions

I'll share the patch

**Comment by fhahn** [comment]
Proposed patch https://reviews.llvm.org/D119760
