### ISSUE TITLE
[AMDGPU] Whether SI can support for HIP dynamic shared variable from non-kernel in one moudle（AMDPAL or AMDHSA）

### ISSUE THREAD

**Issue by Jasonmessage** [llvm/llvm-project#53816]

**Comment by arsenm** [comment]
Not sure what the bug is here, but the LDS handling isn't different on SI. HIP doesn't support SI in general due to the lack of flat addressing

**Comment by Jasonmessage** [comment]
Thanks your reply！
I understand that  the LDS handling isn't different on SI, and SI can support symbol relocation(use GOT or  at compile process) for LDS. But I want to know whether SI can support dynamic shared variable from non-kernel (device function) when not use GOT way, because CUDA can support it.

**Comment by Jasonmessage** [comment]
Thank you for your reply! I understand.
