### ISSUE TITLE
LLVM can't reading archives coming with Windows SDK for Windows 11 (10.0.22000.194)

### ISSUE THREAD

**Issue by AlexeySachkov** [llvm/llvm-project#53814]
The issue was discovered in [intel/llvm](https://github.com/intel/llvm) downstream project, where we use `clang-offload-bundler` tool.

When it is used on a system library (like `kernel32.lib`) from the latest Windows SDK for Windows 11 (10.0.22000.194) (see [Windows SDK archive](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/)), it exits with the following error:

```
error: truncated or malformed archive (long name offset characters after the '/' are not all decimal numbers: '<XFGHASHMAP>/' for archive member header at offset 148966)
```

Apparently, the problem is not with the tool itself, but with `Archive` component library, which is also used by `llvm-ar` and `llvm-lib`

**Comment by tru** [comment]
ping @mstorsjo

**Comment by mstorsjo** [comment]
This looks like a new kind of long symbol name offset encoding. The first instance where I heard of it was in https://reviews.llvm.org/D118692, and apparently we don't support handling of it elsewhere either. CC @npmiller who wrote that patch.

I'd guess this kind of symbol offset mangling probably needs handling in llvm/lib/Object/COFF*, and possibly also in lld/COFF.

**Comment by mstorsjo** [comment]
Sorry for the distraction - the thing I referenced above was about a new offset format used in the object files themselves (new to me at least, but apparently not that new in practice) - and the Object library does already seem to support reading it.

But this seems like a new format in the archive headers, which is a different thing. So sorry for the noise.

**Comment by psamolysov-intel** [comment]
I've opened a small patch on Fabricator: https://reviews.llvm.org/D120645 Your comments are welcome.

**Comment by mstorsjo** [comment]
> I've opened a small patch on Fabricator: https://reviews.llvm.org/D120645 Your comments are welcome.

I'm unable to interact with that review; the history seems to print "created this object with edit policy "Administrators"."

**Comment by psamolysov-intel** [comment]
@mstorsjo Thank you for the information, my bad. Fixed.
