### ISSUE TITLE
Missing Python36.dll on Windows 10

### ISSUE THREAD

**Issue by GoodluckNkem** [llvm/llvm-project#53817]
After Installation of the Windows 64-bit package, lldb will not run because it says it is missing the python36.dll.
I have re-installed multiple times, same error.

**Comment by tru** [comment]
@zmodem any thoughts?

**Comment by GoodluckNkem** [comment]
> @zmodem any thoughts?

I'm wondering if there is an official patch for this.
Or something I will have to install that is legit.
I came across a few sites, but they are providing me with the raw dll, which could be dangerous to my computer.

So any help will be appreciated.

**Comment by zmodem** [comment]
Users are supposed to bring their own Python, I believe. You should be able to download Python 3.6 with that dll from python.org See also #53738 about updating that to a newer version.

**Comment by GoodluckNkem** [comment]
> Users are supposed to bring their own Python, I believe. You should be able to download Python 3.6 with that dll from python.org See also #53738 about updating that to a newer version.

@zmodem
After python 3.6 installation, LLDB found the dll, but ran into further errors.
Seems rather strange the errors.
Any thoughts?
![Screenshot (51)](https://user-images.githubusercontent.com/54841873/153867247-f5001a60-5aed-48df-9742-96fe20e89aa4.png)

**Comment by ZequanWu** [comment]
I never saw this on my Windows. 
The error says "No module named 'encodings'. Maybe something like this https://stackoverflow.com/questions/42512817/fatal-python-error-on-windows-10-modulenotfounderror-no-module-named-encodings (setting environment variables) will work?

**Comment by GoodluckNkem** [comment]
Since there was no eventual solution to the python issue, I uninstalled the package and used MSYS2 to install clang & lldb instead.
Now I have it working fine.
I guess I should close the issue now since no apparent solution for 2 weeks now.
