### ISSUE TITLE
 Backport patches for GAS optionality in OpenCL 3.0 to 14.0.0

### ISSUE THREAD

**Issue by AnastasiaStulova** [llvm/llvm-project#53822]
These are the patches for generic address space optionality (includes minor refactoring + fixes) committed by @svenvh:

https://github.com/llvm/llvm-project/commit/e0e6f3a6a2e13ee11b014ca45a48997e78d3efc5 [OpenCL] Test -fdeclare-opencl-builtins with CL3 and CLC++2021
https://github.com/llvm/llvm-project/commit/d97a4dfea6c2781494f6fe54ce265128f5c08dc2 [OpenCL] Move most _explicit atomics into multiclass; NFC
https://github.com/llvm/llvm-project/commit/31fa3a4d44316fd36e11f92729ea9596ee3bf3f8 [OpenCL] Move OpenCL 2.0 atomics into multiclass; NFC
https://github.com/llvm/llvm-project/commit/fe690587bedb23dec2753549d4216059a7f894a1 [OpenCL] Fix atomic_fetch_add/sub with half type
https://github.com/llvm/llvm-project/commit/8d37043520f57e63e032c9d0ba4cba8701a3cd35 [OpenCL] Refactor cl_ext_float_atomics declarations; NFC
https://github.com/llvm/llvm-project/commit/50f8abb9f40a6c4974ec71e760773a711732648f [OpenCL] Add OpenCL 3.0 atomics to -fdeclare-opencl-builtins

These are patches to complete OpenCL 3.0 and they are not affecting widespread functionality as they are OpenCL parsing specific so they should ideally not impact the release cycle at this point although it would be good to cherry-pick them sooner rather than later.

**Comment by AnastasiaStulova** [comment]
/cherry-pick e0e6f3a6a2e13ee11b014ca45a48997e78d3efc5 d97a4dfea6c2781494f6fe54ce265128f5c08dc2 31fa3a4d44316fd36e11f92729ea9596ee3bf3f8 fe690587bedb23dec2753549d4216059a7f894a1 8d37043520f57e63e032c9d0ba4cba8701a3cd35 50f8abb9f40a6c4974ec71e760773a711732648f

**Comment by tstellar** [comment]
Merged: 6e7a837fdd55 d6f290ec136b 2a2286e9859a 8b3ba440a2f0 174dffbae24f 865a18c94d50 84260978cbf5 f4c48b2015cb fa24d7e3e0ea
