### ISSUE TITLE
inline asm: Ran out of registers during register allocation!

### ISSUE THREAD

**Issue by berolinux** [llvm/llvm-project#5382]
|  |  |
| --- | --- |
| Bugzilla Link | [5010](https://llvm.org/bz5010) |
| Version | trunk |
| OS | Linux |
| Attachments | [Preprocessed source showing the problem](https://user-images.githubusercontent.com/92601251/143739937-86c4133f-7ba9-4abc-811d-4be01d80b0aa.gz) |
| CC | @asl,@lattner,@efriedma-quic,@regehr |

## Extended Description 
llvm-gcc -DHAVE_AV_CONFIG_H -I. -I"/usr/src/ark/BUILD/ffmpeg" -D_ISOC99_SOURCE -D_POSIX_C_SOURCE=200112 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -m32 -O2 -march=i686 -fomit-frame-pointer -fweb -frename-registers -mmmx -g -fomit-frame-pointer -ffast-math --std=gnu99 -O2  -std=c99 -pthread -I/usr/include/dirac -g -Wdeclaration-after-statement -Wall -Wno-switch -Wdisabled-optimization -Wpointer-arith -Wredundant-decls -Wno-pointer-sign -Wcast-qual -Wwrite-strings -Wundef -O3 -fno-math-errno -fno-tree-vectorize         -MMD -MF libavcodec/x86/dsputilenc_mmx.d -MT libavcodec/x86/dsputilenc_mmx.o -c -o libavcodec/x86/dsputilenc_mmx.o libavcodec/x86/dsputilenc_mmx.c
cc1: error in backend: Ran out of registers during register allocation!
Please check your inline asm statement for invalid constraints:
INLINEASM <es:movd %eax, %xmm3
        pshuflw $$0, %xmm3, %xmm3
        punpcklwd %xmm3, %xmm3
        pxor %xmm7, %xmm7
        pxor %xmm4, %xmm4
        movdqa ($2), %xmm5
        pxor %xmm6, %xmm6
        psubw ($3), %xmm6
        mov $$-128, %eax
        .align 1 << 4
        1:
        movdqa ($1, %eax), %xmm0
        movdqa %xmm0, %xmm1
        pabsw  %xmm0, %xmm0
        psubusw %xmm6, %xmm0
        pmulhw %xmm5, %xmm0
        por %xmm0, %xmm4
        psignw %xmm1, %xmm0
        movdqa %xmm0, ($5, %eax)
        pcmpeqw %xmm7, %xmm0
        movdqa ($4, %eax), %xmm1
        movdqa %xmm7, ($1, %eax)
        pandn %xmm1, %xmm0
        pmaxsw %xmm0, %xmm3
        add $$16, %eax
         js 1b
        movhlps %xmm3, %xmm0
        pmaxsw %xmm0, %xmm3
        pshuflw $$0x0E, %xmm3, %xmm0
        pmaxsw %xmm0, %xmm3
        pshuflw $$0x01, %xmm3, %xmm0
        pmaxsw %xmm0, %xmm3
        movd %xmm3, %eax
        movzb %al, %eax
        >, 10, %EAX<def>, 9, %reg1348<kill>, 9, %reg1301<kill>, 9, %reg1345<kill>, 9, %reg1343<kill>, 9, %reg1346<kill>, 2147483657, %EAX, 14, %EFLAGS<earlyclobber,def,dead> [dbg: /usr/src/ark/BUILD/ffmpeg/libavcodec/x86/mpegvideo_mmx_template.c,152,0]

gcc 4.4.x compiles the code without problems.

**Comment by nickdesaulniers** [comment]
```
$ wget https://user-images.githubusercontent.com/92601251/143739937-86c4133f-7ba9-4abc-811d-4be01d80b0aa.gz
$ gunzip 143739937-86c4133f-7ba9-4abc-811d-4be01d80b0aa.gz 
$ mv 143739937-86c4133f-7ba9-4abc-811d-4be01d80b0aa foo.c
$ clang -O -fomit-frame-pointer -c foo.c -m32
$ clang -c -w -Os small.c -m32
```
Thanks for the reports.  I don't think all cases of this error are resolved; I'm going through open reports to find cases that are still reproducible. Since I can't reproduce either test cases in clang-15, closing. Please file new bugs with new test cases.
