### ISSUE TITLE
Backport bee4bd7 and bfb1a33 to 14.0.0

### ISSUE THREAD

**Issue by AnastasiaStulova** [llvm/llvm-project#53823]
These patches are required for the OpenCL 3.0 completion and they are not affecting widespread functionality as they are specific to OpenCL (committed by @azabazno).

https://github.com/llvm/llvm-project/commit/bee4bd70f76952b2c6296feb46a087b497322376 - [OpenCL] Add support of language builtins for OpenCL C 3.0
https://github.com/llvm/llvm-project/commit/bfb1a33bec7c88170b0809b8a7c9cb860e7cc19b - [OpenCL] Adjust diagnostic for subgroup support.

Due to dependency, they are grouped together.

**Comment by AnastasiaStulova** [comment]
Unfortunately, this patch doesn't apply cleanly to the release branch:
https://github.com/llvm/llvm-project/issues/53763#issuecomment-1036356440

**Comment by AnastasiaStulova** [comment]
/cherry-pick bee4bd70f76952b2c6296feb46a087b497322376 bfb1a33bec7c88170b0809b8a7c9cb860e7cc19b

**Comment by tstellar** [comment]
Merged: 6e7a837fdd55 d6f290ec136b 2a2286e9859a 95dd9c5f2a06 7bb1dfeeba87
