### ISSUE TITLE
generic lambda as function parameter fails to be converted to pointer to function

### ISSUE THREAD

**Issue by nickhuang99** [llvm/llvm-project#53836]
See compiler explorer (https://www.godbolt.org/z/GGxKoYGsx) both GCC and MSVC accepts the following code. Clange rejects by giving error of conversion lambda.  According to [standard,](https://timsong-cpp.github.io/cppwp/expr.prim.lambda#closure-9) generic lambda should still be convertible to function pointer which is defined by type `decltype(+[](T t )->T{return t+1;}) `

<pre><code>
template&lt;typename T&gt;
auto foo(T t, decltype(+[](T t )-&gt;T{return t+1;}) lam){
	return lam(t);
}
void test(){
	foo&lt;int&gt;(5, [](int t){return t+1;});
}
</code></pre>

clang13 giving error of 
<pre><code>
<source>:8:2: error: no matching function for call to 'foo'
        foo<int>(5, [](int t){return t+1;});
        ^~~~~~~~
 note: candidate function [with T = int] not viable: no known conversion from '(lambda at <source>:8:14)' to 'decltype(+[](int t) -> int {
    return t + 1;
})' for 2nd argument
auto foo(T t, decltype(+[](T t )->T{return t+1;}) lam){
     ^
1 error generated.
Compiler returned: 1
</code></pre>

**Comment by cor3ntin** [comment]
This is fixed https://www.godbolt.org/z/MsThM8jdT
