### ISSUE TITLE
[clang-cl] Support /ZH (Hash algorithm for calculation of file checksum in debug info)

### ISSUE THREAD

**Issue by kokulshan** [llvm/llvm-project#53837]
MSVC lets you control the type of hashing used in debug info. It can be controlled by /ZH flag as outlined here: [https://docs.microsoft.com/en-us/cpp/build/reference/zh?view=msvc-170](https://docs.microsoft.com/en-us/cpp/build/reference/zh?view=msvc-170)

Our team uses [BinSkim](https://github.com/microsoft/binskim) and the latest release v1.9.2 scans PDBs for the hash type and complains if its MD5 and recommends SHA256 using /ZH:SHA_256 due to MD5 being insecure versus SHA-256. To guard against supply chain attacks, BinSkim wants us to use /ZH:SHA_256 as detailed in the error it spits out:
"warning BA2004: 'TestExe.exe' is a native binary that links one or more static libraries that include object files which were hashed using an insecure checksum algorithm (MD5). MD5 is subject to collision attacks and its use can compromise supply chain integrity. Pass '/ZH:SHA_256' on the cl.exe command-line to enable secure source code hashing. The following modules are out of policy:
clang version 12.0.0 : cxx : 12000.0.0.0 : Logger.lib (ConsoleLogger.cpp.obj,FileLogger.cpp.obj)"

It would be great if clang-cl could support /ZH switch so that we can control the hashing type used in PDBs.

**Comment by walbourn** [comment]
It looks like someone started on this, but as far as I can tell this is still not supported in the latest release (15.0.0).

https://reviews.llvm.org/D98438

**Comment by kokulshan** [comment]
Looks like it has been merged: https://github.com/llvm/llvm-project/commit/ea8371247f6339c32a696e9ea2f84080f91f808d
