### ISSUE TITLE
please pick 9dcb0061657e9b7f321fa6c295960c8f829ed6f1 into release/14.x

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#53834]
cc @nikic @rnk 

/cherry-pick 9dcb0061657e9b7f321fa6c295960c8f829ed6f1

**Comment by nickdesaulniers** [comment]
Fixes this build warning for Linux kernel builds
https://github.com/ClangBuiltLinux/linux/issues/1563

**Comment by tstellar** [comment]
@nikic What do you think about backporting this? https://github.com/llvm/llvm-project/commit/9dcb0061657e9b7f321fa6c295960c8f829ed6f1

**Comment by nikic** [comment]
Should be fine to backport.

**Comment by tstellar** [comment]
Merged: 7d8e83dab37a
