### ISSUE TITLE
Please cherry-pick 5257efd and 00b2a9c into LLVM 14

### ISSUE THREAD

**Issue by OCHyams** [llvm/llvm-project#53845]
This is the patch and follow up for [D118468 [cross-project-tests] XFAIL llgdb-tests when gdb can't read clang's DWARF](https://reviews.llvm.org/D118468).

1st commit: 5257efdc5b30212b62a9d68857dc8e66d0e1a863
2nd commit: 00b2a9c9da40ef17c7645bc6cb1a7614cda1aac5

(I've not made one of these requests before - hopefully this is all I need?)
Thanks.

**Comment by ldionne** [comment]
Closing since I don't think this is relevant anymore.
