### ISSUE TITLE
Backport 954ea0f044e0cd836 onto LLVM 14

### ISSUE THREAD

**Issue by anton-afanasyev** [llvm/llvm-project#53846]
This is related to PR52275 (#51617), should be backported before its fix to follow.

**Comment by tstellar** [comment]
@alexey-bataev What do you think about backporting this? https://github.com/llvm/llvm-project/commit/954ea0f044e0cd8368011dbef6efca70f03358e6

**Comment by alexey-bataev** [comment]
It is good to go.

**Comment by tstellar** [comment]
Merged: e1b3afbbdef10a8ee085dddfb24afddef2cf70b2
