### ISSUE TITLE
[X86]  __GCC_ATOMIC_LLONG_LOCK_FREE is inconsistent with gcc on 32-bit platform

### ISSUE THREAD

**Issue by bzEq** [llvm/llvm-project#53840]
Current clang on X86 has a different value of macro `__GCC_ATOMIC_LLONG_LOCK_FREE` compared to gcc.
```bash
gcc -march=i686 -m32 -dM -E -x c /dev/null|grep LLONG_LOCK
#define __GCC_ATOMIC_LLONG_LOCK_FREE 2
gcc version 10.2.1 20210110 (Debian 10.2.1-6)

clang -march=i686 -m32 -dM -E -x c /dev/null|grep LLONG_LOCK
#define __CLANG_ATOMIC_LLONG_LOCK_FREE 1
#define __GCC_ATOMIC_LLONG_LOCK_FREE 1
clang version 15.0.0 (git@github.com:llvm/llvm-project.git b99365a7f4a1c348f1237937e9775b3ce8441e08)
```

**Comment by topperc** [comment]
By default `long long` has 4 byte alignment with -m32. With -malign-double it uses 8 byte alignment.

Section 8.1.1 Guaranteed Atomic Operations of Volume 3A of the Intel Software Developers manual has the following statement

```
The P6 family processors (and newer processors since) guarantee that the following additional memory operation
will always be carried out atomically:
• Unaligned 16-, 32-, and 64-bit accesses to cached memory that fit within a cache line.
```

A 4 byte aligned long long is not guaranteed to fit within a cache line.

So I don't think it is correct for gcc to say that long long is always lock free, but maybe I'm missing something.

**Comment by bzEq** [comment]
I should have posted the origin problem here. This was found in libcxx's test with `-m32` and `--target=i686-unknown-linux-gnu`.
A reduced producer is
```c++
// test.cc
#include <atomic>

void check() {
  std::atomic<long long> a;
  static_assert(a.is_always_lock_free == (ATOMIC_LLONG_LOCK_FREE == 2));
}
```
It compiles with `-march=i486`, failed with '-march=i686`.
```
test.cc:5:3: error: static_assert failed due to requirement 'a.is_always_lock_free == (1 == 2)'
  static_assert(a.is_always_lock_free == (ATOMIC_LLONG_LOCK_FREE == 2));
  ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
[pr53840.tar.xz.txt](https://github.com/llvm/llvm-project/files/8067692/pr53840.tar.xz.txt)
Reproducer attached(should rename it to decompress it).

**Comment by efriedma-quic** [comment]
The problem here is specifically targets where the ABI alignment of `long long` is less than 8.

I guess this is https://reviews.llvm.org/D28213 ?

**Comment by bzEq** [comment]
Thanks for your info @efriedma-quic . I have got what you two mean now. Does it mean that we should not expect `__atomic_always_lock_free` is consistent with `__CLANG_ATOMIC_*_LOCK_FREE == 2`?

**Comment by bzEq** [comment]
Thanks for detailed explanation @topperc , @efriedma-quic , close it.
