### ISSUE TITLE
[clang-format] Unnecessary space added before `// clang-format on` which disables formatting

### ISSUE THREAD

**Issue by mkurdej** [llvm/llvm-project#53844]
Using LLVM style, and given input:
```
// clang-format off
//comment
// clang-format on
int      unformatted;
```

clang-format adds a space before `clang-format on`:
```
// clang-format off
//comment
//  clang-format on
int unformatted;
```

So the line `int unformatted;` gets formatted this time but next time, `//  clang-format on` does not enable the formatting and any code futher down is **not** formatted anymore.
E.g. if know I change the code to:
```
// clang-format off
//comment
//  clang-format on
int         unformatted_again;
```
it will stay as is (because of this additional space in `//  clang-format on`).

**Comment by mkurdej** [comment]
That's a regression in clang-format 13. Version 12 was OK.

**Comment by mkurdej** [comment]
BTW, I thought that it could be worked around using:
```
SpacesInLineCommentPrefix:
  Minimum: 1
  Maximum: 1
```
but that doesn't change anything.

**Comment by penagos** [comment]
I've raised a review request for this at: https://reviews.llvm.org/D120188.
I believe this was a regression introduced by: https://reviews.llvm.org/D92257.
