### ISSUE TITLE
SimplifyCFG merges invokes with different operand bundles

### ISSUE THREAD

**Issue by max-quazan** [llvm/llvm-project#53854]
Tests: https://github.com/llvm/llvm-project/commit/1cd6454ade3953a9e9a71b4c832bed9857bf5ef2

Commit where the issue first seen (but likely smth similar existed before):
```
commit c8ba2b67a0adebd15dcda70766d4ebaa0ec03720
Author: Roman Lebedev <lebedev.ri@gmail.com>
Date:   Tue Feb 8 21:17:23 2022 +0300

    [SimplifyCFG] 'merge compatible invokes': fully support indirect invokes

    As long as *all* the invokes in the set are indirect,
    we can merge them, but don't merge direct invokes into the set,
    even though it would be legal to do.
```

Problem: when SimplifyCFG merges invokes, it may end up merging invokes with different operand bundles, turning things like
```
invoke1 [deopt(i32 0)]
...
invoke2 [deopt(i32 1)]
```
into
```
i32 phi = phi(0, 1)
invoke.merged [deopt(i32 phi )]
```

The comment in the related code suggests that it is not expected behavior, it says
```
  // Ignoring arguments, these `invoke`s must be identical,
  // including operand bundles.
```
In LangRef, the exact content of deopt bundles is left out of language scope and is up to runtime. In fact, some of these values may be required to be compile-time constants, and there is no clear way to express this requirement. Conservative approach requires to only do it when we are adamant that merging is legal, i.e. bundles are the same. But it seems that the actual implementation of invoke merging doesn't behave according to this logic.

I'm not 100% sure it's a bug in SimplifyCFG and not a lack of expressive power when we describe bundles, but just reading through comments, it looks like we didn't intend to do it. @LebedevRI as the author of this transform, do you think it's correct behavior?

**Comment by LebedevRI** [comment]
I don't know what may or may not be missing from langref about operand bundles,
but i'm 100% correct that the current transform as-is is correct.

> The comment in the related code suggests that it is not expected behavior, it says
> 
> ```
>   // Ignoring arguments, these `invoke`s must be identical,
>   // including operand bundles.
> ```

This is expected behavior, by arguments i did mean "`CallBase::data_ops()`", which includes operands of bundles.

**Comment by annamthomas** [comment]
Just summarizing our offline conservation: I think we're infact allowed to merge the deopt bundles, and by itself is a good thing to do. 
We do have other similar transform already occurring through the optimizer: where deopt blocks are merged and the values for the deoptimization bundle is populated through phis with incoming values from predecessor blocks.
Our plan till we figure out how/where to fix this is to just introduce a cl::opt and turn this off downstream.

**Comment by max-quazan** [comment]
Well, I guess langref isn't being specific enough here. It just says
> Exact details of deoptimization is out of scope for the language reference, but it usually involves rewriting a compiled frame into a set of interpreted frames.
which may or may not mean that the runtime may have extra requirements to the bundles. But Anna is right, we're already doing this, so it's too late to assert the opposite. I'm closing this one, thanks for looking.
