### ISSUE TITLE
[InstructionSimplify] AS casts can cause bit-width of constants to be incompatible

### ISSUE THREAD

**Issue by jdoerfert** [llvm/llvm-project#53860]
If we have AS casts mixed with inbounds and non-inbounds GEPs (and probably also in the absence of GEPs) we can run into bit-width issues.

This is similar to #53559 but this time in InstructionSimplify.cpp.

An earlier attempt to fix this (https://reviews.llvm.org/D64768) did not address all potential issues but only a special case.

Proposed fix: https://reviews.llvm.org/D119740

**Comment by jdoerfert** [comment]
Effectively fixed by f35af77573d9e80bf6e61b3fdd20fe55191e962f, see https://reviews.llvm.org/D119740#3325545.

\cherry-pick f35af77573d9e80bf6e61b3fdd20fe55191e962f

**Comment by tstellar** [comment]
@nikic What do you think about backporting this? https://github.com/llvm/llvm-project/commit/f35af77573d9e80bf6e61b3fdd20fe55191e962f

**Comment by nikic** [comment]
@tstellar Should be fine to backport.

**Comment by tstellar** [comment]
Merged: 08ad9ae10f327e3a511f1df7423f508103df1525
