### ISSUE TITLE
Please backport 905abc5b7db2 to 14.0.0

### ISSUE THREAD

**Issue by rotateright** [llvm/llvm-project#53866]
This is an enhancement that would prevent perf regressions from the previous release for x86 with AVX512.
See discussion in:
https://reviews.llvm.org/D113442

Earlier commits in this series have already been backported:
6592bcec (main) -> a2f583280e4 (branch)
a68e0980 (main) -> ae88d88446 (branch)

**Comment by rotateright** [comment]
I missed a test file update that happened between the code changes. 
Trying again:
/cherry-pick 24562babdf16093 905abc5b7db

**Comment by tstellar** [comment]
Merged: 6311bae1b424 b0ae8076cf4c
