### ISSUE TITLE
PDL type and operands CSE behavior is missing side effects

### ISSUE THREAD

**Issue by nicolasvasilache** [llvm/llvm-project#53863]
```
module @patterns {
  pdl.pattern : benefit(1) {
    %0 = pdl.type
    %1 = pdl.type
    %2 = pdl.operand : %0
    %3 = pdl.operand : %1
    %4 = operation "foo"(%2, %3 : !pdl.value, !pdl.value)  -> (%1 : !pdl.type)
    pdl.rewrite %4 {
      pdl.erase %4
    }
  }
}
```

cse's to 
```
module @patterns {
  pdl.pattern : benefit(1) {
    %0 = type
    %1 = operand : %0
    %2 = operation "foo"(%1, %1 : !pdl.value, !pdl.value)  -> (%0 : !pdl.type)
    rewrite %2 {
      erase %2
    }
  }
}
```

which forces the match into filtering only ops "foo" with operands of the same type.

Adding side effects to, at least, ops that implicitly captures from the environment should help.

**Comment by Mogball** [comment]
The PDL ops should not be marked as side-effect free (maybe allocating). The conversion to PDL interp does a kind of constraint CSE anyways.

**Comment by Mogball** [comment]
https://reviews.llvm.org/D120222

**Comment by Mogball** [comment]
I'll open a new issue about the side-effect modeling, but this specific bug is fixed
