### ISSUE TITLE
[Attributor] Do not use liveness of the wrong function

### ISSUE THREAD

**Issue by jdoerfert** [llvm/llvm-project#53872]
If we use AAIsDead of the wrong function all queries will result in "is dead". This problem is at least present in the genericValueTraversal, could be other places too.

**Comment by jdoerfert** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/668c5c688be7ab0af37739bbbe2d653be82d5c6f

**Comment by tstellar** [comment]
@jdoerfert Can you rebase the issue53872 branch?  The patches no longer apply cleanly.

**Comment by jdoerfert** [comment]
Done, I think.

**Comment by tstellar** [comment]
Merged: a98c04d58930814f4ff00293ffd14feca57feafa
