### ISSUE TITLE
Cherry-pick b9f547e and f261e25 into LLVM 13

### ISSUE THREAD

**Issue by gulfemsavrun** [llvm/llvm-project#53870]
Can we please cherry-pick the following patches into LLVM 13?
1st commit: b9f547e
https://github.com/llvm/llvm-project/commit/b9f547e8e51182d32f1912f97a3e53f4899ea6be
2nd commit : f261e25
https://github.com/llvm/llvm-project/commit/f261e258ecc0fc5b8e8a70dbe45752d1bb3c2d69

It is reported in https://reviews.llvm.org/D107143 that binary-id.c fails in release/13.x branch at ToT 75e33f71c2dae584b13a7d1186ae0a038ba98838.

**Comment by ldionne** [comment]
Closing since I don't think this is relevant anymore.
