### ISSUE TITLE
Can't get Clang to work with OpenMP 5.1 loop transformations

### ISSUE THREAD

**Issue by laxel** [llvm/llvm-project#53878]
Been trying to get a version of clang supporting the new OpenMP 5.1 loop transformation directive `unroll` and `tile` without much success.

First tried directly download a binary of Clang+LLVM 13.0.0, and while clang itself worked, some openmp features did not.

When trying to compile code containing the directive
`#pragma omp tile`
I get the error: 
error: directive '#pragma omp tile' requires the 'sizes' clause

And when i change the line to contain the sizes clause:
`#pragma omp tile sizes(8,8,8)`
I instead get the following error
error: unexpected OpenMP clause 'sizes' in directive '#pragma omp tile'

So it seems to recognize that tile is a OpenMP keyword, but it is not possible to actually use it since it gives an error with or without the sizes clause. 

Get a similar error with `unroll`  and the keyword `partial`

I've also tried to compile clang manually from source, but without much success. Have tried with many different cmake options, but here is one of them:
`cmake -DLLVM_ENABLE_RUNTIMES=openmp -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ../llvm`
Then it got to 100% and failed with the message:
```
-- Performing Test OPENMP_HAVE_STD_CPP14_FLAG
-- Performing Test OPENMP_HAVE_STD_CPP14_FLAG - Failed
-- Performing Test LIBOMP_HAVE_FNO_EXCEPTIONS_FLAG
-- Performing Test LIBOMP_HAVE_FNO_EXCEPTIONS_FLAG - Failed
-- Performing Test LIBOMP_HAVE_FNO_RTTI_FLAG
-- Performing Test LIBOMP_HAVE_FNO_RTTI_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_CLASS_MEMACCESS_FLAG
-- Performing Test LIBOMP_HAVE_WNO_CLASS_MEMACCESS_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_COVERED_SWITCH_DEFAULT_FLAG
-- Performing Test LIBOMP_HAVE_WNO_COVERED_SWITCH_DEFAULT_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_FRAME_ADDRESS_FLAG
-- Performing Test LIBOMP_HAVE_WNO_FRAME_ADDRESS_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_STRICT_ALIASING_FLAG
-- Performing Test LIBOMP_HAVE_WNO_STRICT_ALIASING_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WSTRINGOP_OVERFLOW_FLAG
-- Performing Test LIBOMP_HAVE_WSTRINGOP_OVERFLOW_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_STRINGOP_TRUNCATION_FLAG
-- Performing Test LIBOMP_HAVE_WNO_STRINGOP_TRUNCATION_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_SWITCH_FLAG
-- Performing Test LIBOMP_HAVE_WNO_SWITCH_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_UNINITIALIZED_FLAG
-- Performing Test LIBOMP_HAVE_WNO_UNINITIALIZED_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_UNUSED_BUT_SET_VARIABLE_FLAG
-- Performing Test LIBOMP_HAVE_WNO_UNUSED_BUT_SET_VARIABLE_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_RETURN_TYPE_C_LINKAGE_FLAG
-- Performing Test LIBOMP_HAVE_WNO_RETURN_TYPE_C_LINKAGE_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_CAST_QUAL_FLAG
-- Performing Test LIBOMP_HAVE_WNO_CAST_QUAL_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_INT_TO_VOID_POINTER_CAST_FLAG
-- Performing Test LIBOMP_HAVE_WNO_INT_TO_VOID_POINTER_CAST_FLAG - Failed
-- Performing Test LIBOMP_HAVE_MSSE2_FLAG
-- Performing Test LIBOMP_HAVE_MSSE2_FLAG - Failed
-- Performing Test LIBOMP_HAVE_FTLS_MODEL_FLAG
-- Performing Test LIBOMP_HAVE_FTLS_MODEL_FLAG - Failed
-- Performing Test LIBOMP_HAVE_MMIC_FLAG
-- Performing Test LIBOMP_HAVE_MMIC_FLAG - Failed
-- Performing Test LIBOMP_HAVE_M32_FLAG
-- Performing Test LIBOMP_HAVE_M32_FLAG - Failed
-- Looking for shm_open
-- Looking for shm_open - not found
-- Looking for shm_open
-- Looking for shm_open - not found
-- Performing Test LIBOMP_HAVE_X_FLAG
-- Performing Test LIBOMP_HAVE_X_FLAG - Success
-- Performing Test LIBOMP_HAVE_WARN_SHARED_TEXTREL_FLAG
-- Performing Test LIBOMP_HAVE_WARN_SHARED_TEXTREL_FLAG - Success
-- Performing Test LIBOMP_HAVE_AS_NEEDED_FLAG
-- Performing Test LIBOMP_HAVE_AS_NEEDED_FLAG - Success
-- Performing Test LIBOMP_HAVE_VERSION_SCRIPT_FLAG
-- Performing Test LIBOMP_HAVE_VERSION_SCRIPT_FLAG - Success
-- Performing Test LIBOMP_HAVE_STATIC_LIBGCC_FLAG
-- Performing Test LIBOMP_HAVE_STATIC_LIBGCC_FLAG - Success
-- Performing Test LIBOMP_HAVE_Z_NOEXECSTACK_FLAG
-- Performing Test LIBOMP_HAVE_Z_NOEXECSTACK_FLAG - Success
-- Looking for pthread.h
-- Looking for pthread.h - not found
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindThreads.cmake:220 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /home/axel/Downloads/llvm-project-llvmorg-13.0.1/openmp/runtime/cmake/config-ix.cmake:138 (find_package)
  /home/axel/Downloads/llvm-project-llvmorg-13.0.1/openmp/runtime/CMakeLists.txt:240 (include)


-- Configuring incomplete, errors occurred!
See also "/home/axel/Downloads/llvm-project-llvmorg-13.0.1/build/runtimes/runtimes-bins/CMakeFiles/CMakeOutput.log".
See also "/home/axel/Downloads/llvm-project-llvmorg-13.0.1/build/runtimes/runtimes-bins/CMakeFiles/CMakeError.log".
make[2]: *** [runtimes/CMakeFiles/runtimes.dir/build.make:107: runtimes/runtimes-stamps/runtimes-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:37809: runtimes/CMakeFiles/runtimes.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target bugpoint
make: *** [Makefile:152: all] Error 2
```
(When only compiling for Clang without including openmp everything works fine)

**Comment by jdoerfert** [comment]
Try -fopenmp-version=52, https://godbolt.org/z/bMnqWxc37

**Comment by Meinersbur** [comment]
`-fopenmp-version=51` should be sufficient. Currently https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/Frontend/OpenMP/OMP.td defines version requirements for clauses, but not for directives which results in the `sizes` clause being rejected, but apparently the `tile` clause itself being accepted.

**Comment by laxel** [comment]
This solved my problem with the loop transformations. Thank you!

Out of curiosity, is there any documentation that mentions that the -fopenmp-version flag is needed when working with loop transformations? Have been trying to get my code to work for several days now and could not find anything about this solution  online.

**Comment by jdoerfert** [comment]
> This solved my problem with the loop transformations. Thank you!
> 
> Out of curiosity, is there any documentation that mentions that the -fopenmp-version flag is needed when working with loop transformations? Have been trying to get my code to work for several days now and could not find anything about this solution online.

Good point.

1) @Meinersbur can you adjust the OMP.td file to make it consistent and less confusing?
2) We should probably emit a note if we reject something due to the version.
3) We should have an FAQ entry on openmp.llvm.org.

@laxel if you are interested, feel free to pick up task 2 or 3 ;)
