### ISSUE TITLE
There is no output when I use command `clang -cc1 -analyze -analyzer-checker=debug.ViewExplodedGraph test.c` to dump the ExplodedGraph of test.c

### ISSUE THREAD

**Issue by for-just-we** [llvm/llvm-project#53873]
When I use this command, shell output is `Warning: viewing graph requires assertions`, What does that means? And there is no any `.dot` file output. What should I do to view the ExplodedGraph of test.c.

The LLVM version I use is 12.0.0,I directly downloaded the released package instead of compiling from source code, the graphviz version I use is 2.40.1.

**Comment by Snape3058** [comment]
https://github.com/llvm/llvm-project/blob/d97f997eb79d91b2872ac13619f49cb3a7120781/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp#L3222
https://github.com/llvm/llvm-project/blob/d97f997eb79d91b2872ac13619f49cb3a7120781/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp#L3232

These two lines are wrapped with macro `NDEBUG`. If this macro is defined, it will only output this warning and exit directly.
You need to re-compile your tool with assertions enabled.
Although debug checkers are available in release build, such functionality is disabled if assertions are disabled.

**Comment by for-just-we** [comment]
Thank you, may I ask where could I enable this assertion?

**Comment by Snape3058** [comment]
You need to re-compile your clang to enable this.
For debug build (`CMAKE_BUILD_TYPE` is `Debug`), it is enabled by default.
For release build (`CMAKE_BUILD_TYPE` is `Release`/`RelWithDebInfo`/`MinSizeRel`), you need to add `-DLLVM_ENABLE_ASSERTIONS=ON` during cmake.

**Comment by steakhal** [comment]
Proposed fix: https://reviews.llvm.org/D124442

**Comment by xhslyx** [comment]
Please tell me how to solve the following problem when I recompile：
`-- clang project is enabled
CMake Error at CMakeLists.txt:100 (message):
  LLVM_ENABLE_PROJECTS requests clang but directory not found:
  /home/zzh/llvm-source-code/llvm/../clang`
  This is the command I used：
  `zzh@server:~/llvm-source-code/build$ cmake -G "Unix Makefiles" ../llvm -DCMAKE_BUILD_TYPE=Debug -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"`
  I've installed clang before and want to recompile it

**Comment by steakhal** [comment]
I dont understand your problem. Could you please provide more details. What is the observed behavior and what did you expect instead?

**Comment by xhslyx** [comment]
OK, THANKS. 
I previously installed clang by way of release, but ViewCFG this function does not work properly, I saw the previous issue can be solved by recompiling the method to specify `-DLLCM_ENABLE_ASSERTIONS=ON`.
However, I encountered the above problem when recompiling and it did not compile successfully, the above is the error message given and the compile command I used

**Comment by steakhal** [comment]
> However, I encountered the above problem when recompiling and it did not compile successfully, the above is the error message given and the compile command I used the above is the error message given and the compile command I used.

Okay, it seems like something really messed up. What version (commit hash) of `llvm-project` do you try to compile?
There should be a `clang` directory at the same level where the `llvm` directory is.

PS: I was really confused since you mentioned that you got some error during *build* time, but it seems like cmake configure failed.

**Comment by xhslyx** [comment]
> > However, I encountered the above problem when recompiling and it did not compile successfully, the above is the error message given and the compile command I used the above is the error message given and the compile command I used.
> 
> Okay, it seems like something really messed up. What version (commit hash) of `llvm-project` do you try to compile? There should be a `clang` directory at the same level where the `llvm` directory is.
> 
> PS: I was really confused since you mentioned that you got some error during _build_ time, but it seems like cmake configure failed.

Thank you for your answer.
It's my expression wrong, my error happened in the cmake phase, not in the build phase, sorry。
The version i try to compile is `clang version 10.0.0`
I have no `clang` directory at the asme level where the `llvm` directory is, the directory is `source code/llvm/tools/clang`

**Comment by steakhal** [comment]
I would recommend using the monorepo version where `clang` and `llvm` are in a merged repository.
I cannot support the old repository structure. Let me know if using the monorepo worked.

**Comment by xhslyx** [comment]
ok, i'll rebuild in monorepo version. Thanks:)
