### ISSUE TITLE
Clangd crashs after it finishes indexing

### ISSUE THREAD

**Issue by HiTAsm** [llvm/llvm-project#53882]
Assertion failed: DelayedDllExportClasses.empty(), file C:\src\llvm_package_1400-rc1\llvm-project\clang\lib\Sema\Sema.cpp, line 1141
 #0 0x00007ff7bc1ae1f6 D:\Program Files\LLVM\bin\clangd.exe 0xee1f6 (D:\Program Files\LLVM\bin\clangd.exe+0xee1f6)
 #1 0x00007ff7bc1ae1f6 
 #2 0x00007ff7bc1ae1f6 (D:\Program Files\LLVM\bin\clangd.exe+0xee1f6)
 #3 0x00007ffd66371881 (C:\WINDOWS\System32\ucrtbase.dll+0x71881)
 #4 0x00007ffd66372851 (C:\WINDOWS\System32\ucrtbase.dll+0x72851)
 #5 0x00007ffd663741b5 D:\Program Files\LLVM\bin\clangd.exe 0x15ad6e5 D:\Program Files\LLVM\bin\clangd.exe 0x1ddbe4a
 #6 0x00007ffd663741b5 D:\Program Files\LLVM\bin\clangd.exe 0x1dd63ce D:\Program Files\LLVM\bin\clangd.exe 0x14bcb35
 #7 0x00007ffd663741b5 D:\Program Files\LLVM\bin\clangd.exe 0xa7b2d8 D:\Program Files\LLVM\bin\clangd.exe 0xa7da33
 #8 0x00007ffd663741b5 D:\Program Files\LLVM\bin\clangd.exe 0x818ed8 D:\Program Files\LLVM\bin\clangd.exe 0xa7c853
 #9 0x00007ffd663741b5 D:\Program Files\LLVM\bin\clangd.exe 0xad18cf (C:\WINDOWS\System32\ucrtbase.dll+0x741b5)
#10 0x00007ffd663741b5 
#11 0x00007ffd663741b5 (C:\WINDOWS\System32\ucrtbase.dll+0x741b5)
#12 0x00007ffd663744f1 (C:\WINDOWS\System32\ucrtbase.dll+0x744f1)
0x00007FF7BC1AE1F6 (0x0000D75FFCA8FC22 0x0000018221B54840 0x0000000000000016 0x00007FF7BC1AE1F0)
0x00007FFD66371881 (0x0000000000000401 0x00007FF700000000 0x0000000000000000 0x000000365247E520), raise() + 0x1E1 bytes(s)
0x00007FFD66372851 (0x00007FFD00000003 0x00007FFD00000003 0x00007FF7BE5A1396 0x00007FF7BE5A0DA8), abort() + 0x31 bytes(s)
0x00007FFD663741B5 (0x0000000000000475 0x00007FF7BE5A1396 0x0000018222C55B50 0x0000ACAC530DC7E5), _get_wpgmptr() + 0x18A5 bytes(s)
0x00007FFD663744F1 (0x000001823D6BD860 0x000000365247EAE0 0x00000182308C2820 0x0000ACAC530DC7F5), _wassert() + 0x71 bytes(s)
0x00007FF7BD66D6E5 (0x0000ACAC530DCA45 0x000001823D6BD860 0x0000018225B12FB0 0x0000003600000201)
0x00007FF7BDE9BE4A (0x0000000000000000 0x00007FF7BD5868DF 0x000000365247F0B0 0x00007FF7BD583480)
0x00007FF7BDE963CE (0x000000365247EB00 0x0000ACAC530DC485 0x0000000000000000 0x000000000000000F)
0x00007FF7BD57CB35 (0x000001826C2F22B8 0x0000018200000000 0x000001826A678850 0x00007FF7BC8EBF6E)
0x00007FF7BCB3B2D8 (0x000001826A590000 0x000001826A590000 0x0000000000000000 0x000000364E18E5F0)
0x00007FF7BCB3DA33 (0x000001826A6788C0 0x00007FF700000000 0x000001826A6788C0 0x0000000000000000)
0x00007FF7BC8D8ED8 (0x0000000000000000 0x00007FF7BC1C3028 0x0000000000000000 0x0000000000000000)
0x00007FF7BCB3C853 (0x0000000000000003 0x00007FFD66313A81 0x0000000000000000 0x0000000000000000)
0x00007FF7BCB918CF (0x000001826A677010 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFD66321B[Info  - 16:11:24] Connection to server got closed. Server will restart.

I[16:11:24.971] clangd version 14.0.0
I[16:11:24.971] Features: windows+debug
I[16:11:24.972] PID: 29176
I[16:11:24.972] Working directory: d:\project
I[16:11:24.972] argv[0]: D:\Program Files\LLVM\bin\clangd.exe
I[16:11:24.972] argv[1]: --pretty
I[16:11:24.972] argv[2]: --clang-tidy
I[16:11:24.972] argv[3]: --compile-commands-dir=d:\project\compile_commands_dir
I[16:11:24.972] argv[4]: --log=verbose

Note that the same project works fine using version 13.0.0 of clangd.

**Comment by kadircet** [comment]
There's little we can do without any reproducers. Feel free to re-open once you have some steps that'll help us reproduce the crash.
