### ISSUE TITLE
Backport b7574b0 onto LLVM 14

### ISSUE THREAD

**Issue by anton-afanasyev** [llvm/llvm-project#53885]
This follows 954ea0f04, should be backported after it (#53846).

**Comment by tstellar** [comment]
@alexey-bataev What do you think about backporting this? https://github.com/llvm/llvm-project/commit/b7574b092a97ef59631aa3e801b6c04665409147

**Comment by alexey-bataev** [comment]
Should be backported, actually, fixes a bug in SLP vectorizer.

**Comment by tstellar** [comment]
@alexey-bataev Can you rebase the pr53885 branch?

**Comment by anton-afanasyev** [comment]
> /branch anton-afanasyev/llvm-project/pr53885

Done: https://github.com/anton-afanasyev/llvm-project/tree/pr53885

**Comment by anton-afanasyev** [comment]
Hi Tom, this branch pr53885 is rebased on release/14.x rather than on llvmorg-14.0.0-rc1. Is that what you need?

**Comment by tstellar** [comment]
Merged: da33d400682a8cf93062fe61a9f0b6ec1d60c8ad
