### ISSUE TITLE
A Pointer Typedef Causes Clang to Claim a Function and Its Prototype Conflict

### ISSUE THREAD

**Issue by gavinhoward** [llvm/llvm-project#53889]
This might be related to #53886, but I was not sure.

When using a type that has been `typedef`'ed to a pointer type, Clang will claim that a function and its prototype are incompatible if the pointer is `const`-qualified and one uses the `typedef`'ed type while the other does not.

Minimal example:

```
#include <stdlib.h>

typedef unsigned char* my_ptr1;

typedef unsigned char my_int1;

static my_ptr1 g_p1;

void
my_test(const my_ptr1 p1);

void
my_test(const my_int1* p1)
{
	*g_p1 = *p1;
}
```

If the above is saved as `test.c`, this `Makefile` should help:

```
test:
	clang -Werror -Weverything -Wno-cast-align -o test.o -c test.c

clean:
	rm -rf test.o
```

Output of `clang --version`:

```
clang version 13.0.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm/13/bin
```

It is the Clang packaged by Gentoo.

If you run `make`, the output is as follows:

```
clang -Werror -Weverything -Wno-cast-align -o test.o -c test.c
test.c:13:1: error: conflicting types for 'my_test'
my_test(const my_int1* p1)
^
test.c:10:1: note: previous declaration is here
my_test(const my_ptr1 p1);
^
1 error generated.
make: *** [Makefile:2: test] Error 1
```

The use case for this is opaque pointer type declarations on public functions, but using the private type on the actual function, which makes it so GDB can actually print the fields of the type when debugging. So I might have this in a public header:

```
typedef struct map* Map;

bool map_exists(const Map m, const void* key);
```

And in the source file, I would have this:

```
typedef struct map {
    ...
} map;

bool map_exists(const map* m, const void* key) {
    ...
}
```

In that case, GDB would print out `m`'s fields if I was debugging in `map_exists()`.

**Comment by efriedma-quic** [comment]
If I'm following correctly, you're basically doing the following:

```
void my_test(int * const p1);
void my_test(const my_int1* p1);
```

That's not allowed.

Maybe the error message could be improved; gcc's error message expands out the typedef.
