### ISSUE TITLE
backport 76b7d734291c to llvm14

### ISSUE THREAD

**Issue by yonghong-song** [llvm/llvm-project#53896]
Request to backport the following BPF patch to llvm14:

commit 76b7d734291c7991368c7f6f00d9c67c8f160790
Author: Yonghong Song <yhs@fb.com>
Date:   Sun Dec 19 16:58:12 2021 -0800

    BPF: report better error message for BTF_TYPE_ID_REMOTE relo failure

**Comment by yonghong-song** [comment]
cc @4ast

**Comment by tstellar** [comment]
@yonghong-song I just noticed that https://github.com/llvm/llvm-project/commit/76b7d734291c7991368c7f6f00d9c67c8f160790 is not in the r14 branch.  It seems there is a different commit there.

**Comment by tstellar** [comment]
This issue was not resolved in time for 14.0.0 and will need to be fixed in the next release (14.0.1).  If you disagree with this or you feel there was a mistake, please change the milestone back to 'LLVM 14.0.0 Release' so we can discuss.

**Comment by tstellar** [comment]
ping @yonghong-song can you take a look at this?

**Comment by nikic** [comment]
Closing this, as the LLVM 14 release is finished and this is already in LLVM 15.
