### ISSUE TITLE
Get rid off ISD::ADDE and ISD::SUBE nodes from SelectionDAG

### ISSUE THREAD

**Issue by chfast** [llvm/llvm-project#53890]
@RKSimon, in review: https://reviews.llvm.org/D118037#3272270

> how come we still have the ISD::ADDE/SUBE nodes? I thought we were intending to get rid of them as the glue nodes made them difficult to work with.

**Comment by topperc** [comment]
AArch64, AMDGPU, ARC, AVR, Lanai, M68k, Mips, PowerPC, Sparc and WebAssembly all use them. Out of those targets only AMDGPU also has references to ISD::ADDCARRY.

**Comment by RKSimon** [comment]
IIRC the plan was for a gradual transition so we didn't always end up with 2 sets of opcodes like this, but it never happened - in fact M68k was added later on and still used the ADDE/SUBE opcodes.
