### ISSUE TITLE
`clang-format -i` on a read-only file fails with a very ugly backtrace

### ISSUE THREAD

**Issue by tru** [llvm/llvm-project#53902]
On windows if I mark a file as read-only and the run `clang-format -i` on that it will fail with this stack-trace:

```
Assertion failed: getClient() && "DiagnosticClient not set!", file C:\code\llvm-project\clang\lib\Basic\Diagnostic.cpp, line 514
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ..\\llvm-project\\build\\bin\\clang-format.exe -i noaccess.cpp
 #0 0x00007ff717095790 HandleAbort C:\code\llvm-project\llvm\lib\Support\Windows\Signals.inc:408:0
 #1 0x00007ffead91bc31 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0x6bc31)
 #2 0x00007ffead91d889 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0x6d889)
 #3 0x00007ffead9234b5 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0x734b5)
 #4 0x00007ffead923027 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0x73027)
 #5 0x00007ffead921091 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0x71091)
 #6 0x00007ffead923a1f (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0x73a1f)
 #7 0x00007ff716fab122 clang::DiagnosticsEngine::EmitCurrentDiagnostic(bool) C:\code\llvm-project\clang\lib\Basic\Diagnostic.cpp:517:0
 #8 0x00007ff716fb330e clang::DiagnosticBuilder::Emit(void) C:\code\llvm-project\clang\include\clang\Basic\Diagnostic.h:1315:0
 #9 0x00007ff716faebc8 clang::DiagnosticBuilder::~DiagnosticBuilder(void) C:\code\llvm-project\clang\include\clang\Basic\Diagnostic.h:1356:0
#10 0x00007ff71704b607 `anonymous namespace'::AtomicallyMovedFile::~AtomicallyMovedFile C:\code\llvm-project\clang\lib\Rewrite\Rewriter.cpp:444:0
#11 0x00007ff71704b1fc clang::Rewriter::overwriteChangedFiles(void) C:\code\llvm-project\clang\lib\Rewrite\Rewriter.cpp:467:0
#12 0x00007ff716f03874 clang::format::format C:\code\llvm-project\clang\tools\clang-format\ClangFormat.cpp:455:0
#13 0x00007ff716f02562 main C:\code\llvm-project\clang\tools\clang-format\ClangFormat.cpp:551:0
#14 0x00007ff7173f9039 invoke_main d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:79:0
#15 0x00007ff7173f916e __scrt_common_main_seh d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288:0
#16 0x00007ff7173f91ee __scrt_common_main d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331:0
#17 0x00007ff7173f920e mainCRTStartup d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:17:0
#18 0x00007fff1e6c7034 (C:\WINDOWS\System32\KERNEL32.DLL+0x17034)
#19 0x00007fff1f002651 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x52651)
```

This seems to be because no diagnosticsclient is set. AtomicallyMovedFile will try to emit an diagnostic error and then an assert will abort the program because of the missing client. I think clang-format should use a bit more pedagogic error message informing the user about the wrong permissions.

I tried to figure out how to fix this but I am not sure on the exact solution, we could either check if the file is writeable from `Rewriter::overwriteChangedFiles` but I couldn't find a api to check if a file is writeable. Guess I could try to open the file in writable mode and handle the error.

We could do something with atomicallymovedfile so that it won't abort but rather the `File.ok()` call actually would work.

or something about attaching our diagnostics client? but not familiar with this api.

Any thoughts?

**Comment by mkurdej** [comment]
That was fixed by commit https://github.com/llvm/llvm-project/commit/a92cf5a5a0cd01145f8db2ae09334a8b43a1271b.
It works fine with v14-rc1 or newer.
Please reopen if it's not the case for you.

**Comment by tru** [comment]
stupid of me to not check `main` thanks.

**Comment by mydeveloperday** [comment]
I wouldn't worry, this issue kept raising its head, and it annoyed me too because we couldn't fix it without pulling in all of the libFrontEnd library which bloated clang-format more than people wanted. This solution isn't sophisticated but it solves the crashing.
