### ISSUE TITLE
[LV] Should support second order recurrence

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#53900]
Sink casts to unravel first order recurrence is brought in https://reviews.llvm.org/D33058, which has great help to enable vectorization of the loop, while now it is restrictive to second order recurrence , a simple case showed as following.

loop vectorization has diffrent result with the only change of the sequence of float arithmetic, https://godbolt.org/z/KjWP339df
```
void foo_0 (void)
{
// #pragma clang loop vectorize(assume_safety)
   for (int i = 0; i < LEN_1D-1; i++) {
       b[i] += a[i] + a[i+1] + a[i+2];
   }
}

void foo_1(void)
{
// #pragma clang loop vectorize(assume_safety)
   for (int i = 0; i < LEN_1D-1; i++) {
       b[i] += a[i+2] + a[i+1] + a[i];
   }
}
```

**Comment by fhahn** [comment]
There's a patch to fix this: https://reviews.llvm.org/D119661

**Comment by vfdff** [comment]
> There's a patch to fix this: https://reviews.llvm.org/D119661

wonderful, thanks very much!

**Comment by vfdff** [comment]
confirmed, it should combine with the change of D118642
