### ISSUE TITLE
Question Clang(d): Is there a way to activate __cpp_consteval as experimental flag?

### ISSUE THREAD

**Issue by Febbe** [llvm/llvm-project#53906]
When using clangd in combination with an msvc compiler and its STL - impl, it is not possible to use some features which require __cpp_consteval, even it is already (partially) supported.

Therefore I would like to have the ability to activate some experimental features like __cpp_consteval. 
If this is not possible, it might be usefull to add such an option to increase feedback for new features from some bleeding edge devs like me.

**Comment by royjacobson** [comment]
I don't recommend actually doing it, but it's _possible_ to just add `-D__cpp_consteval=201811` to the command line of clang/d until it is mature enough.
