### ISSUE TITLE
opt crashes with "Assertion `ValueExprMap.count(VE.first)' failed." in ScalarEvolution::getSCEVValues

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#53905]
llvm commit: d1cd64ffdd832

Reproduce with:
 opt -passes="function(loop(indvars,loop-deletion),sroa)" -verify-scev-maps -disable-output BBI-65750-reduced.ll

Result:
opt: ../lib/Analysis/ScalarEvolution.cpp:4305: ScalarEvolution::ValueOffsetPairSetVector *llvm::ScalarEvolution::getSCEVValues(const llvm::SCEV *): Assertion `ValueExprMap.count(VE.first)' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: build-all/bin/opt -passes=function(loop(indvars,loop-deletion),sroa) -verify-scev-maps -disable-output BBI-65750-reduced.ll
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
build-all/bin/opt(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamEi+0x23)[0x2d059d3]
build-all/bin/opt(_ZN4llvm3sys17RunSignalHandlersEv+0xee)[0x2d0364e]
build-all/bin/opt[0x2d05d56]
/lib64/libpthread.so.0(+0xf630)[0x7fae21cda630]
/lib64/libc.so.6(gsignal+0x37)[0x7fae1f40d387]
/lib64/libc.so.6(abort+0x148)[0x7fae1f40ea78]
/lib64/libc.so.6(+0x2f1a6)[0x7fae1f4061a6]
/lib64/libc.so.6(+0x2f252)[0x7fae1f406252]
build-all/bin/opt(_ZN4llvm15ScalarEvolution13getSCEVValuesEPKNS_4SCEVE+0x28d)[0x1cb4b0d]
build-all/bin/opt(_ZN4llvm15ScalarEvolution17eraseValueFromMapEPNS_5ValueE+0xdb)[0x1cb4c4b]
build-all/bin/opt(_ZN4llvm15ScalarEvolution14SCEVCallbackVH19allUsesReplacedWithEPNS_5ValueE+0x1cb)[0x1ce377b]
build-all/bin/opt(_ZN4llvm15ValueHandleBase12ValueIsRAUWdEPNS_5ValueES2_+0x3c1)[0x24716d1]
build-all/bin/opt(_ZN4llvm5Value6doRAUWEPS0_NS0_19ReplaceMetadataUsesE+0xaa)[0x247116a]
build-all/bin/opt[0x2b92591]
build-all/bin/opt[0x2b87eaf]
build-all/bin/opt(_ZN4llvm8SROAPass16rewritePartitionERNS_10AllocaInstERNS_4sroa12AllocaSlicesERNS3_9PartitionE+0x12ab)[0x2b85a3b]
build-all/bin/opt(_ZN4llvm8SROAPass11splitAllocaERNS_10AllocaInstERNS_4sroa12AllocaSlicesE+0x591)[0x2b88671]
build-all/bin/opt(_ZN4llvm8SROAPass11runOnAllocaERNS_10AllocaInstE+0x2777)[0x2b8b707]
build-all/bin/opt(_ZN4llvm8SROAPass7runImplERNS_8FunctionERNS_13DominatorTreeERNS_15AssumptionCacheE+0x3f0)[0x2b8d2d0]
build-all/bin/opt(_ZN4llvm8SROAPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE+0xf7)[0x2b8e217]
build-all/bin/opt[0x302ca7d]
build-all/bin/opt(_ZN4llvm11PassManagerINS_8FunctionENS_15AnalysisManagerIS1_JEEEJEE3runERS1_RS3_+0x205)[0x244dc25]
build-all/bin/opt[0xb20a1d]
build-all/bin/opt(_ZN4llvm27ModuleToFunctionPassAdaptor3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE+0x29a)[0x245204a]
build-all/bin/opt[0x7ae17d]
build-all/bin/opt(_ZN4llvm11PassManagerINS_6ModuleENS_15AnalysisManagerIS1_JEEEJEE3runERS1_RS3_+0x208)[0x244cd78]
build-all/bin/opt(_ZN4llvm15runPassPipelineENS_9StringRefERNS_6ModuleEPNS_13TargetMachineEPNS_21TargetLibraryInfoImplEPNS_14ToolOutputFileES8_S8_S0_NS_8ArrayRefIS0_EENS_8opt_tool10OutputKindENSB_12VerifierKindEbbbbb+0x3462)[0x7a63b2]
build-all/bin/opt(main+0x3c84)[0x7b8f94]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fae1f3f9555]
build-all/bin/opt[0x7a183c]
Abort

[BBI-65750-reduced.ll.gz](https://github.com/llvm/llvm-project/files/8089217/BBI-65750-reduced.ll.gz)

**Comment by mikaelholmen** [comment]
Starts happening with commit 2b160e95c8:

    Reland [SCEV] Fix and validate ValueExprMap/ExprValueMap consistency
    
    Relative to the previous landing attempt, this introduces an additional
    flag on forgetMemoizedResults() to not remove SCEVUnknown phis from
    the value map. The invalidation after BECount calculation wants to
    leave these alone and skips them in its own use-def walk, but we can
    still end up invalidating them via forgetMemoizedResults() if there
    is another IR value with the same SCEV. This is intended as a temporary
    workaround only, and the need for this should go away once the
    getBackedgeTakenInfo() invalidation is refactored in the spirit of
    D114263.
    
    -----
    
    This adds validation for consistency of ValueExprMap and
    ExprValueMap, and fixes identified issues:
    
    * Addrec construction directly wrote to ValueExprMap in a few places,
      without updating ExprValueMap. Add a helper to ensures they stay
      consistent. The adjustment in forgetSymbolicName() explicitly
      drops the old value from the map, so that we don't rely on it
      being overwritten.
    * forgetMemoizedResultsImpl() was dropping the SCEV from
      ExprValueMap, but not dropping the corresponding entries from
      ValueExprMap.
    
    Differential Revision: https://reviews.llvm.org/D113349

**Comment by nikic** [comment]
This is fixed by https://reviews.llvm.org/D120311 by dint of removing the problematic functionality.
