### ISSUE TITLE
Backport d03d3d7966d1efdcf0629f037ffee94317385b6b onto LLVM 14 

### ISSUE THREAD

**Issue by wsmoses** [llvm/llvm-project#53910]
/cherry-pick d03d3d7966d1efdcf0629f037ffee94317385b6b

This fixes https://github.com/llvm/llvm-project/issues/53800#event-6083060539 and comes up in a variety of contexts including exits/assertions in C++, bounds checks in Julia, etc.

cc @vchuravy

**Comment by wsmoses** [comment]
/branch wsmoses/llvm-project/dse

@nikic @fhahn let me know if this seems reasonable to you.

**Comment by wsmoses** [comment]
@tstellar the Github action PR bot failed, though I can make a PR manually if desired? Otherwise not sure the right path.

**Comment by tstellar** [comment]
@wsmoses I'll look into it.

**Comment by tstellar** [comment]
@nikic What do you think about backporting this? https://github.com/llvm/llvm-project/commit/d03d3d7966d1efdcf0629f037ffee94317385b6b

**Comment by nikic** [comment]
I think it's safe to backport. Though I should add that this is a feature addition, so a backport isn't really necessary.

**Comment by tstellar** [comment]
Merged: 03cf88fc94da55b989f1c14cb0460777834749c0 453361d5ac0131ca713904bdd87166d429e17612
