### ISSUE TITLE
Request to cherry-pick fc1b21228e39 onto release/14.x

### ISSUE THREAD

**Issue by kmclaughlin-arm** [llvm/llvm-project#53923]
This patch fixes a crash in AArch64InstrInfo::isAArch64FrameOffsetLegal ("unhandled opcode in isAArch64FrameOffsetLegal") when this function is called for a scalable structured load/store instruction. The patch only affects scalable vectors, and we are doing our own additional release testing with scalable vectors for LLVM 14.x.

**Comment by tstellar** [comment]
@TNorthover What do you think about backporting this? https://github.com/llvm/llvm-project/commit/fc1b21228e39d63f1a2ab98026d548de66cb3760

**Comment by TNorthover** [comment]
Yep, simple enough.

**Comment by tstellar** [comment]
Merged: 88f8980a4d95
