### ISSUE TITLE
Backport 0bff3a965022647fcdd17cc8f2217f5a2cd30b4c to LLVM 14

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#53929]
This fixes an assertion failure when calling generic lambdas with `.operator()` syntax.

**Comment by tstellar** [comment]
@zygoloid What do you think about backporting this? https://github.com/llvm/llvm-project/commit/0bff3a965022647fcdd17cc8f2217f5a2cd30b4c

**Comment by tstellar** [comment]
@erichkeane What do you think about backporting this? https://github.com/llvm/llvm-project/commit/0bff3a965022647fcdd17cc8f2217f5a2cd30b4c

**Comment by erichkeane** [comment]
> @erichkeane What do you think about backporting this? [0bff3a9](https://github.com/llvm/llvm-project/commit/0bff3a965022647fcdd17cc8f2217f5a2cd30b4c)

While I'm not as confident/knowledgeable about this patch as Richard I believe it only has an effect on cases that were assertions/crashes before this patch went in, so I believe this to be low enough risk that cherry-picking this to LLVM-14 would be a completely positive effect.

**Comment by tstellar** [comment]
Merged: f7007c570a21
