### ISSUE TITLE
No copy-elision in delegating to copy-constructor

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#53926]
This program
```
struct A {       
    A() = default;
    A(const A&) = delete;
    A(int) : A(A()) {}
};
```
is accepted by GCC and MSVC, but Clang wants to call the copy-constructor:
```
error: call to deleted constructor of 'A'
    A(int) : A(A()) {}
             ^ ~~~
note: 'A' has been explicitly marked deleted here
    A(const A&) = delete;
    ^
```
Demo: https://gcc.godbolt.org/z/ner54ePM5

**Comment by shafik** [comment]
I believe clang is correct here, if we look at [\[class.base.init\]p7](http://eel.is/c++draft/class.base.init#7) says:

>The expression-list or braced-init-list in a mem-initializer is used to initialize the designated subobject (or, in the case of a delegating constructor, the complete class object) according to the initialization rules of [dcl.init] for direct-initialization.

So we should use the rules for *direct-initialization* and [\[direct.init.general\]p16.6.2](http://eel.is/c++draft/dcl.init#general-16.6.2) says:

> Otherwise, if the initialization is direct-initialization, or if it is copy-initialization where the cv-unqualified version of the source type is the same class as, or a derived class of, the class of the destination, constructors are considered.
The applicable constructors are enumerated ([over.match.ctor]), and the best one is chosen through overload resolution ([over.match]).

So we need to consider the constructors. 

Also note the guaranteed copy elision paragraph was the [one right above](http://eel.is/c++draft/dcl.init#general-16.6.2) which does not apply, it says:

> If the initializer expression is a prvalue and the cv-unqualified version of the source type is the same class as the class of the destination, the initializer expression is used to initialize the destination object.
[Example 2: T x = T(T(T())); calls the T default constructor to initialize x.
— end example]

I believe @zygoloid bug report against gcc [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86849) is basically this.

**Comment by Fedr** [comment]
Thanks for the explanation.
