### ISSUE TITLE
clang-format: option to apply only configured formatting options

### ISSUE THREAD

**Issue by rcr** [llvm/llvm-project#53924]
It should be possible to enforce only the formatting options set in a configuration file. For example consider some `.clang-format` in a project where all I want to enforce is tabs over spaces:

```
---
TabWidth: 8
UseTab: Always
---
```

In this case all other options default to either a BasedOnStyle or falsy fallback and the formatting is applied to things I don't care about

**Comment by mkurdej** [comment]
There is already `BasedOnStyle` option that does exactly that.
Cf. https://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options.
Have a look as well at `InheritParentConfig` value of this option.

**Comment by rcr** [comment]
Tabs to spaces is just an example, more generally I'd like the option to only apply the formatting that is configured in a `.clang-format` file. There's a bunch of formatting options that I simply do not want applied in any way.

**Comment by mkurdej** [comment]
So, your code is unformatted or formatted according to a different style?
If it's the former, there's almost nothing that can be done as most options are not orthogonal. Also, clang-format does not work by applying a batch of different transformations one by one for each option.
If your case is the latter, you can just do the following:
1. Format with the base style
2. Set your options, possibly using `BasedOnStyle: InheritParentConfig`.
3. Reformat.

Hope that meets your needs.

**Comment by rcr** [comment]
My code is unformatted and I was hoping to be able to somehow run only a subset of the available transformations on it, but I understand now that likely won't ever be possible. Thanks for the response.

**Comment by mkurdej** [comment]
Well, in this case you can maybe use sed-like tool for some basic changes.
