### ISSUE TITLE
[AMDGPU] unhandled address space (store a double to addrspace(4))

### ISSUE THREAD

**Issue by chichunchen** [llvm/llvm-project#53939]
Reproducer (llc -O0 -mtriple=amdgcn-amd-amdhsa -disable-promote-alloca-to-lds -mcpu=gfx906 -filetype=asm simplified.ll -o simplified.s):
```
; ModuleID = '<stdin>'
source_filename = "llvm-link"
target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7"
target triple = "amdgcn-amd-amdhsa"

@llvm.used = appending addrspace(1) global [1 x i8*] [i8* bitcast (void ()* @__omp_offloading__fe05_c0b470_smallx_log_smallx_l11_ctor to i8*)], section "llvm.metadata"
@_ZL17smallx_log_smallx = addrspace(4) global double 0.000000e+00, align 8

; Function Attrs: convergent noinline nounwind
define internal void @__omp_offloading__fe05_c0b470_smallx_log_smallx_l11_ctor() {
entry:
  store double 1.0, double addrspace(4)* @_ZL17smallx_log_smallx, align 8
  ret void
}
```
https://godbolt.org/z/qqochEGG3

There are two ways to avoid the error:
1. remove @llvm.used
2. change the address space of the store in `@__omp_offloading__fe05_c0b470_smallx_log_smallx_l11_ctor` or just remove the store instruction. (I think the code is valid since there's only one store for the constant (addrspace(4))

**Comment by arsenm** [comment]
Where it's asserting is interesting. However store to 4 is store to constant which is undefined. This IR shouldn't exist in the first place

**Comment by arsenm** [comment]
https://reviews.llvm.org/D120286 will make this error consistent in release vs. debug builds. I'm not sure what we should actually do here. Ideally we would have a target specific IR verifier that would reject constant stores or atomics, but we don't. We could also just incorrectly codegen this as global, or delete the instructions

**Comment by chichunchen** [comment]
Thanks for your patch and quick reply! After doing git bisect, I found that the codegen bug in my codes snippet was already fixed in master branch (https://github.com/llvm/llvm-project/commit/d1327f8a574a0936f462387778adf0dfc14358f6) and I was using release/13.x branch.
