### ISSUE TITLE
Newer glibc needs __GLIBC_FLT_EVAL_METHOD to be defined, but it is not.

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#53931]
Starting with 32b73bc "Add support for floating-point option `ffp-eval-method` and for `pragma clang fp eval_method`", clang fails during compiliation with "#  error "Unknown __GLIBC_FLT_EVAL_METHOD"".

This happens on SystemZ with glibc 2.32, but not 2.30.

GCC defines these macros like:

#define __FLT_EVAL_METHOD__ 0
#define __FLT_EVAL_METHOD_TS_18661_3__ 0

and I suppose that's what is missing in Clang.

It see in llvm sources:

libcxx/include/float.h:#define FLT_EVAL_METHOD __FLT_EVAL_METHOD__

, but no definition of __FLT_EVAL_METHOD__ anywhere...?

**Comment by jdoerfert** [comment]
This happens for X86 as well, just include cmath and add -save-temps: https://godbolt.org/z/W1fWcx5sT

**Comment by zahiraam** [comment]
> This happens for X86 as well, just include cmath and add -save-temps: https://godbolt.org/z/W1fWcx5sT

So presumably this is happening with clang (without the patch

**Comment by zahiraam** [comment]
> This happens for X86 as well, just include cmath and add -save-temps: https://godbolt.org/z/W1fWcx5sT

I looked at the pre-processed output of #include <cmath> and I don't see any reference of FLT_EVAL_METHOD?

**Comment by zahiraam** [comment]
I was able to reproduce the issue and this fix  https://reviews.llvm.org/D120155 (edited with the review comments) will be added to the bigger patch https://reviews.llvm.org/D109239
