### ISSUE TITLE
C++20 operator== ambiguous with derived-to-base conversion

### ISSUE THREAD

**Issue by d0k** [llvm/llvm-project#53954]
```cpp
struct P {
#if 1
    template<class S>
    bool operator==(const S &) const;
#else
    template<class S>
    friend bool operator==(const P &, const S &);
#endif
};

struct A : public P {};
struct B : public P {};

bool check(A a, B b) {
    return a == b;
}
```

The `friend` function works just fine, but the member function dies with
```
<source>:15:14: error: use of overloaded operator '==' is ambiguous (with operand types 'A' and 'B')
    return a == b;
           ~ ^  ~
<source>:4:10: note: candidate function [with S = B]
    bool operator==(const S &) const;
         ^
<source>:4:10: note: candidate function (with reversed parameter order) [with S = A]
```

GCC and MSVC accept both. https://godbolt.org/z/9hj9554fn

@dwblaikie @zygoloid

**Comment by dwblaikie** [comment]
Yeah, I'd have to punt to @zygoloid on the language lawyering and implementation details for this one.

My understanding was that there are (were?) some ambiguity problems with the swappable parameters operator thing in C++20... not sure what the difference in implementation/understanding/etc between Clang and GCC/MSVC, etc is here.

**Comment by jyknight** [comment]
Both these examples should be errors.

GCC and MSVC currently give an error or default-warning for both cases -- only Clang is failing to diagnose the friend-function case.

**Comment by usx95** [comment]
Please do not close this. This is still in progress.

This would be closed by https://github.com/llvm/llvm-project/pull/72213 which have several blockers.
Please refer to https://github.com/llvm/llvm-project/pull/72213#issuecomment-1816001788 for more details and strategy to move forward.
