### ISSUE TITLE
Core Dump When Using OpenMP on AWS Lambda

### ISSUE THREAD

**Issue by stuartmcmahon-h3d** [llvm/llvm-project#53955]
Since AWS Lambda does not support `/dev/shm` the OpenMP runtime causes a core dump. Output below:

```
OMP: Error #179: Function Can't open SHM2 failed:
OMP: System error #2: No such file or directory
```

To fix the issue we have to switch to an OpenMP runtime earlier than this commit:
[changing OMP rtl to use shared memory instead of env variable](https://github.com/llvm/llvm-project/commit/d6a0957467e86d5a87964d45fae18733e212c86f)

Could you please consider adding a runtime check for `/dev/shm` creation and add a fall back?

I see there is already a compile time switch to turn it off for Android, I would guess other embedded systems may have the same issue.

**Comment by jdoerfert** [comment]
@AndreyChurbanov WDYT, can we check and use a tmp folder in case it's not available?

**Comment by stuartmcmahon-h3d** [comment]
`/tmp` is available on AWS Lambda so would definitely work for us.

If the intent of the startup & shutdown code is to handle openMP versioning then a long term solution may be to remove it and let clients handle versioning themselves. Though I realise that is not backwards compatible.
