### ISSUE TITLE
clang-format adds unwanted line breaks when using "private" as name variable

### ISSUE THREAD

**Issue by Julien-Elie** [llvm/llvm-project#53951]
I believe clang-format should not add breaks after `private` in the following code:

```
PRIV_TRADSPOOL *private;
PRIV_TRADSPOOL *othername;

private
= xmalloc(sizeof(PRIV_TRADSPOOL));
othername = xmalloc(sizeof(PRIV_TRADSPOOL));

private
->artlen = sb.st_size;
othername->artlen = sb.st_size;
```

It should be formatted like `othername` is.
Seen with clang-format 13.0.0.

**Comment by mkurdej** [comment]
That was fixed in https://github.com/llvm/llvm-project/commit/d1aed486efc6d35a81ca4acbabb4203c4b91cda9. Could you test with a newer clang-format (14-rc1 or main) and close the issue if it fixes your problem please?

**Comment by Julien-Elie** [comment]
I have just tested with a freshly built 14-rc1 version and I confirm the issue is fixed!
Many thanks.
