### ISSUE TITLE
Wrong permissions of scan-build.1 man page

### ISSUE THREAD

**Issue by Min4sT1r1th** [llvm/llvm-project#53967]
The man page of scan-build.1 is installed with 755 permissions, instead of 644. The culprit is found here:

https://github.com/llvm/llvm-project/blob/main/clang/tools/scan-build/CMakeLists.txt#L77

It's installed as PROGRAMS instead of FILES.

**Comment by telans** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/3ca1098557091247524acef9a3759379ba7a3e59

**Comment by EugeneZelenko** [comment]
@telans: Should issue be closed? Or may be backported to 14.x?

**Comment by telans** [comment]
I'm not the commit author, but FWIW I don't think this warrants a backport

**Comment by steakhal** [comment]
Let's close this. I don't think it's worth backporting either.
