### ISSUE TITLE
[GVN][TBAA][Inlining] After Inlining, GVN ignores stores to a "constant" memory location

### ISSUE THREAD

**Issue by wsmoses** [llvm/llvm-project#53968]
https://godbolt.org/z/acoj66EYo

```llvm
define i64* @keep(i64* %a0) {
  %a4 = alloca i64*, align 8
  store i64* %a0, i64** %a4, align 8
  %a31 = load i64*, i64** %a4, align 8, !tbaa !13
  ret i64* %a31
}

!13 = !{!14, !14, i64 0, i64 1}
!14 = !{!"jtbaa_const", !4, i64 0}
!4 = !{!"jtbaa", !5, i64 0}
!5 = !{!"jtbaa"}
```

run with `-tbaa -gvn` will mistakenly result in:

```
define i64* @keep(i64* %a0) {
  %a4 = alloca i64*, align 8
  store i64* %a0, i64** %a4, align 8
  ret i64* undef
}
```

**Comment by efriedma-quic** [comment]
I don't see a bug.

From [LangRef](https://llvm.org/docs/LangRef.html#representation): "If a fourth field is present, it must be a ConstantInt valued at 0 or 1. If it is 1 then the access tag states that the location being accessed is “constant” (meaning pointsToConstantMemory should return true; see [other useful AliasAnalysis methods](https://llvm.org/docs/AliasAnalysis.html#OtherItfs))."  If you violate the TBAA rules, your load returns undef.

**Comment by wsmoses** [comment]
What is the anticipated scope of `pointsToConstantMemory` Specifically, this comes from a Julia code which emits the corresponding TBAA (among other information) for the load in one function, which is inlined by LLVM into the caller.

The reason I ask is to determine whether the bug is that the inliner does not rewrite the TBAA, or that it actually cannot be marked as constant in that case.

**Comment by efriedma-quic** [comment]
pointsToConstantMemory is true for global constants ("@a = constant i32 0"), and pointers derived from them.  It basically means the value doesn't every change during the lifetime of the program.

**Comment by tstellar** [comment]
Removing milestone since it seems like this is not a bug.
