### ISSUE TITLE
[mlir] TosaOpBase.td is missing an include of mlir/IR/OpBase.td

### ISSUE THREAD

**Issue by rnett** [llvm/llvm-project#53965]
Running tablegen commands on `TosaOpBase.td` gives `error: Couldn't find class 'Dialect'` errors.  `Dialect` is defined in `mlir/IR/OpBase.td` which is included in other dialect's `*OpBase.td` files, but not in TOSA's.  I'm assuming this was just an oversight?  I'm not sure why it hasn't surfaced before.

**Comment by joker-eph** [comment]
I guess no one is running TableGen directly on the "base" file but only where it is itself included. That said I don't think there is a reason to not include the required dependencies...

**Comment by EugeneZelenko** [comment]
@ftynse: Could you please add information about particular commit(s)?
