### ISSUE TITLE
clang-format swaps `constexpr` and expression in requires-clause

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#53962]
## Problem description

Given

```cpp
template<typename F, typename... Args>
requires std::invocable<F, Args..., int*>
constexpr constructor(F create, Deleter destroy, Args const&... args) noexcept
{}
```
clang-format  will restyle this as
```cpp
template<typename F, typename... Args>
requires constexpr
std::invocable<F, Args..., int*> constructor(F create, Deleter destroy, Args const&... args) noexcept
{}
```
which is incorrect syntax.

## System details
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```
```
$ clang-format --version
Ubuntu clang-format version 15.0.0-++20220218052900+34313583331e-1~exp1~20220218173003.163
```

**Comment by mkurdej** [comment]
Could you please provide your .clang-format config?

**Comment by mkurdej** [comment]
Reproduced with:
```
BasedOnStyle: LLVM
QualifierAlignment: Custom
QualifierOrder: ['constexpr', 'type']
```
and
```
template <typename F>
  requires std::invocable<F>
constexpr constructor();
```

This should be simple to fix I guess (@mydeveloperday WDYT?).

**Comment by mkurdej** [comment]
It seems that the problem boils down to the fact that the `QualifierAlignmentFixer` is not aware of the requires clause and skips it only partially.
@HazardyKnusperkeks, given that you implemented the current version of requires parser, is there a way to skip through the whole requires close without re-parsing the whole thing?
Are there, for instance, added fake parens or something alike?

**Comment by HazardyKnusperkeks** [comment]
> 

From `TT_RequiresClause` up until `FormatTok->ClosesRequiresClause` everything belongs to the clause. (Except for the currently open bugs.)
Fake Parens are not explicitly added, but are correctly handled for `&&` and `||`.

**Comment by mkurdej** [comment]
> > 
> 
> From `TT_RequiresClause` up until `FormatTok->ClosesRequiresClause` everything belongs to the clause. (Except for the currently open bugs.) Fake Parens are not explicitly added, but are correctly handled for `&&` and `||`.

Great, thanks!

**Comment by mkurdej** [comment]
Revision URI: https://reviews.llvm.org/D120309
