### ISSUE TITLE
Backport llvm-objcopy COFF section name fixes to 14.x

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#53971]
This would involve backporting 85f4023e731c0c42e45bf32bfcbf5f73c2013384 ("[COFF] Move section name encoding into BinaryFormat") and ddf528b7a092fd24647d7c6186ece7392c92de92 ("[llvm-objcopy][COFF] Fix section name encoding") to the 14.x branch.

This fixes issues found in https://github.com/msys2/MINGW-packages/pull/10555#issuecomment-1046014913.

Preemptively CCing @jh7370 @rnk who were involved in approving these patches, to approve the backport too.

**Comment by mstorsjo** [comment]
/cherry-pick 85f4023e731c0c42e45bf32bfcbf5f73c2013384 ddf528b7a092fd24647d7c6186ece7392c92de92

**Comment by mstorsjo** [comment]
Oh and FWIW, on main, 14f143c9084fc49b45f30a199dc8a16b7506f959 was made later to fix shared lib builds - but that one shouldn't be necessary when backported to 14.x. (The issue was that the original patch was made before objcopy was moved into a separate library - ddf528b7a092fd24647d7c6186ece7392c92de92 got that right for the library layout in 14.x but I missed to fix it up when applying on main.)

**Comment by jh7370** [comment]
@tstellar, what does assigning in this context mean?

**Comment by mstorsjo** [comment]
> @tstellar, what does assigning in this context mean?

Assigning here only means that he wants you to acknowledge whether it's ok to backport these fixes (provided that they built fine in their cherrypicked form).

**Comment by jh7370** [comment]
Yeah, no objections from me.

**Comment by tstellar** [comment]
Merged: 3367c24735c3 cefe6876d6e5
