### ISSUE TITLE
[clang-format] QualifierOrder does not reorder template arguments

### ISSUE THREAD

**Issue by mkurdej** [llvm/llvm-project#53981]
Found when working on #53962.

The following test fails:
```
FormatStyle Style = getLLVMStyle();
Style.QualifierAlignment = FormatStyle::QAS_Custom;
Style.QualifierOrder = {"type", "const"};

verifyFormat("template <typename T>\n"
             "  requires Concept<T const>\n"
             "void f();",
             "template <typename T>\n"
             "  requires Concept<const T>\n"
             "void f();",
             Style);
verifyFormat("TemplateType<T const> t;", "TemplateType<const T> t;", Style);
```

I think it's a legitimate request to be able to reorder qualifiers inside a requires clause or a template type argument list.

That's because we skip all the tokens from `TemplateOpener` till `TemplateCloser`.

**Comment by mydeveloperday** [comment]
@mkurdej thanks for the producer, I'm can't remember if the skipping was a conscious decision.
