### ISSUE TITLE
Merge 912bba5ae25a onto LLVM 14

### ISSUE THREAD

**Issue by DavidSpickett** [llvm/llvm-project#53986]
https://reviews.llvm.org/D119948 fixes the issue reported in https://github.com/llvm/llvm-project/issues/53848 by correcting the test `UNSUPPORTED` line. The test should not be running on armv7 in the first place.

**Comment by tstellar** [comment]
@ldionne Are you OK with backporting this? https://github.com/llvm/llvm-project/commit/912bba5ae25aea1da32ee022a51f063477e5e0f0

**Comment by tstellar** [comment]
@rovka What do you think about backporting this? https://github.com/llvm/llvm-project/commit/912bba5ae25aea1da32ee022a51f063477e5e0f0

**Comment by rovka** [comment]
@tstellar This seems fine to me in theory. I was hoping to give it a try yesterday but we're having some connectivity issues and I haven't managed to reach the machines that we're using for the release. Sorry about the delay, I'll give it a try as soon as I can.

**Comment by tstellar** [comment]
@rovka Were you able to test this?

**Comment by rovka** [comment]
@tstellar It's still in progress, it will probably finish tomorrow (CET).

**Comment by tstellar** [comment]
I'm going to merge this, because I want to get -rc3 out on time.  We can always back it out if it causes issues.

**Comment by tstellar** [comment]
Merged: 569b773323a3a1c174ae794741c7e1191f8deefc

**Comment by rovka** [comment]
Seems to work, thanks!
