### ISSUE TITLE
LLD build failing on OSX with missing xar symbols (despite LLVM_ENABLE_LIBXAR=OFF)

### ISSUE THREAD

**Issue by h-vetinari** [llvm/llvm-project#54001]
One of the blockers in conda-forge for releasing the last bits of LLVM 13 has been that lld builds have been failing on missing xar symbols for a while, despite several tries to work around it through configuration (e.g. LLVM_HAVE_LIBXAR or LLVM_ENABLE_LIBXAR). The lastest PR is [here](https://github.com/conda-forge/lld-feedstock/pull/34).

Error upon linking:
```
[100%] Linking CXX executable ../../bin/lld
Undefined symbols for architecture x86_64:
  "xar_opt_set(__xar_t const*, char const*, char const*)", referenced from:
      lld::macho::BitcodeBundleSection::finalize() in liblldMachO2.a(SyntheticSections.cpp.o)
  "xar_open(char const*, int)", referenced from:
      lld::macho::BitcodeBundleSection::finalize() in liblldMachO2.a(SyntheticSections.cpp.o)
  "xar_close(__xar_t const*)", referenced from:
      lld::macho::BitcodeBundleSection::finalize() in liblldMachO2.a(SyntheticSections.cpp.o)
ld: symbol(s) not found for architecture x86_64
```

The error goes away when building on MACOSX_SDK 10.13 and above, but conda-forge cannot bump that far yet.

CC @llvm/issue-subscribers-lld-macho

**Comment by keith** [comment]
I don't see `LLVM_ENABLE_LIBXAR` anywhere in the codebase, where did that spelling come from? I just did a pass with `-DLLVM_HAVE_LIBXAR=NO` and successfully built lld that does not appear to reference these symbols. Can you confirm you did use this spelling in one of your tests as well?

**Comment by h-vetinari** [comment]
Thanks for the quick response. I'll try again.

> I don't see `LLVM_ENABLE_LIBXAR` anywhere in the codebase, where did that spelling come from?

I had originally tried with `LLVM_HAVE_LIBXAR` and was then lured into a foolish consistency due to the existence of many `LLVM_ENABLE_*` config options (cf. diff below). From that POV, it might make sense to add an alias `LLVM_ENABLE_LIBXAR` for `LLVM_HAVE_LIBXAR`?

<details>

```diff
commit 879438503cb7b9964dff015719ba15a85936be93 (HEAD -> xar)

    correctly reflect inconsistent option name

diff --git a/recipe/build.sh b/recipe/build.sh
index 3569ee3..f3d2586 100644
--- a/recipe/build.sh
+++ b/recipe/build.sh
@@ -25,7 +25,7 @@ fi
 cmake -DCMAKE_INSTALL_PREFIX="${PREFIX}" \
       -DCMAKE_BUILD_TYPE=Release \
       -DHAVE_LIBEDIT=OFF \
-      -DLLVM_ENABLE_LIBXAR=OFF \
+      -DLLVM_HAVE_LIBXAR=OFF \
       -DLLVM_ENABLE_LIBXML2=OFF \
       -DLLVM_ENABLE_RTTI=ON \
       -DLLVM_ENABLE_TERMINFO=OFF \
```

PS. Seems that the same point also applies to `HAVE_LIBEDIT` -> `LLVM_ENABLE_LIBEDIT`.

</details>

**Comment by keith** [comment]
Yea I'm not sure about the history of these, I think there's a chance it goes away at some point given it's now deprecated on macOS but I'm not sure 🤔

I wonder if the naming was intended to reflect that it should always be enabled if it exists, vs a standard flag you're intended to flip, which would beg the question why does your build default it to true and then fail 🤔

**Comment by h-vetinari** [comment]
Indeed, it was the misspelling of the config option (as well as the fact that the option needs to be sets on the build of `/llvm` itself as well, rather than just lld). Sorry for the noise, and thanks for the quick response.

**Comment by keith** [comment]
No worries glad it worked!
