### ISSUE TITLE
libclang produced by 14.0.0.rc1 has wrong so-number

### ISSUE THREAD

**Issue by h-vetinari** [llvm/llvm-project#54004]
Seen in https://github.com/conda-forge/clangdev-feedstock/pull/165, where we explicitly test for presence of `libclang.so.<major_ver>` in the installed environment. Turns out, that `libclang.so.14.0.0` is created, but not the symlink to `libclang.so.14`:
```
-- Installing: /home/conda/feedstock_root/build_artifacts/[...]/lib/libclang.so.14.0.0
-- Installing: /home/conda/feedstock_root/build_artifacts/[...]/lib/libclang.so.13
-- Installing: /home/conda/feedstock_root/build_artifacts/[...]/lib/libclang.so
```

I searched for other issues, _maybe_ https://github.com/llvm/llvm-project/issues/53932 is related.

**Comment by tstellar** [comment]
@h-vetinari This is expected.  libclang.so ABI usually stays stable across major releases, so we've frozen the soname at libclang.so.13.  The plan is to keep it with this name unless the ABI changes.

**Comment by h-vetinari** [comment]
Well, different people can have different expectations. 😅

From LLVM 8 (at least, didn't check back further) to LLVM 13, the version of `libclang.so` matched the LLVM major version, so it's perhaps understandable how one might arrive at the expectation that this pattern would continues

But OK, if this is intentional, then I'll reflect this in our build.

**Comment by tstellar** [comment]
@h-vetinari There is a libclang.so.14.0.0 symlink you can link against if you need a versioned so name.

**Comment by tstellar** [comment]
> @h-vetinari There is a libclang.so.14.0.0 symlink you can link against if you need a versioned so name.

Ah, I guess you already saw that in the first comment.

**Comment by h-vetinari** [comment]
> @h-vetinari There is a libclang.so.14.0.0 symlink you can link against if you need a versioned so name.

Thanks; I can easily live with an ABI version that's different from LLVM-major. Just wanted to verify that that's intentional.

**Comment by h-vetinari** [comment]
@tstellar 
Another question - sorry if those are basic, but just wanting to check. Is it intentional that currently `libclang-cpp.so.14` _does_ bump to 14, whereas `libclang.so.13` does not?

I've [found](https://github.com/llvm/llvm-project/blob/llvmorg-14.0.0-rc1/clang/tools/libclang/CMakeLists.txt#L1-L5) `set(CLANG_SONAME 13)`, which is clear enough, but I couldn't figure out where `libclang-cpp` is created, nor whether it intentionally gets a version or not. The search finds it only [twice](https://github.com/llvm/llvm-project/search?q=libclang-cpp) (and not much different for `clang-cpp`)

**Comment by h-vetinari** [comment]
@EugeneZelenko 
Could you reopen this please until it's clear whether `libclang-cpp` should match `CLANG_SONAME` or not? I'm not in a rush, but I'd like to avoid that it falls through the cracks.

**Comment by EugeneZelenko** [comment]
Sorry, if I was too fast.

**Comment by h-vetinari** [comment]
Gentle ping @tstellar (regarding `CLANG_SONAME` vs. `libclang-cpp`; `libclang` is clear already).

**Comment by tstellar** [comment]
@h-vetinari Changing the soname of libclang-cpp.so is intentional, because the ABI/API is changes with each major version.

**Comment by h-vetinari** [comment]
Thank you very much for clarifying that. Closing.

**Comment by h-vetinari** [comment]
Unfortunately, one more question popped up still: the OSX dylib for libclang still gets produced as `libclang.14.dylib`, even though `CLANG_SONAME` is [set](https://github.com/llvm/llvm-project/blob/llvmorg-14.0.0-rc1/clang/tools/libclang/CMakeLists.txt#L1-L5) to 13 unconditionally.

Or am I overlooking something again? Can the ABI version be platform-dependent (and if so, is that really desirable...)?

**Comment by h-vetinari** [comment]
PS. I tried looking for documentation on this, but couldn't find any on it. Indeed, out of all files in the `clang/*` folder, `CLANG_SONAME` only appears in `clang/tools/libclang/CMakeLists.txt`.

**Comment by h-vetinari** [comment]
Apologies for one last ping @tstellar - `CLANG_SONAME` doesn't appear to take effect on OSX.

**Comment by tstellar** [comment]
@h-vetinari This wasn't implemented for OSX, because it doesn't use a linker script.

**Comment by h-vetinari** [comment]
Thank you very much. What do you think of the following suggestions (not sure if they merit a separate issue)?
1. Make the behaviour of `CLANG_SONAME` uniform across platforms - I see no downside to use it to reflect the ABI version across platforms, even if OSX doesn't strictly need it(?). Certainly, it would be one less behavioural difference to keep in mind.
1. Document the behaviour of `CLANG_SONAME` (independently of the outcome of 1.).

**Comment by dileks** [comment]
You should simply use something else to make clear `ABI = 13` and not use the `CLANG_SONAME`.

As a workaround:
I symlinked all `libclang.so` `libclang.so.13` `libclang.so.14` to `libclang.so.14.0.1`

**Comment by h-vetinari** [comment]
> You should simply use something else to make clear `ABI = 13` and not use the `CLANG_SONAME`.

I think using the SONAME to indicate the ABI is quite a traditional approach. Personally I find it trickier that it's not consistent across platforms.

**Comment by markmi** [comment]
I looked at https://releases.llvm.org/14.0.0/projects/libcxx/docs/ReleaseNotes.html and it lists:
```
[ABI Changes](https://releases.llvm.org/14.0.0/projects/libcxx/docs/ReleaseNotes.html#id5)[](https://releases.llvm.org/14.0.0/projects/libcxx/docs/ReleaseNotes.html#abi-changes)

The C++17 variable templates is_error_code_enum_v and is_error_condition_enum_v are now of type bool instead of size_t.
The C++03 emulation type for std::nullptr_t has been removed in favor of using decltype(nullptr) in all standard modes. This is an ABI break for anyone compiling in C++03 mode and who has std::nullptr_t as part of their ABI. However, previously, these users’ ABI would be incompatible with any other binary or static archive compiled with C++11 or later. If you start seeing linker errors involving std::nullptr_t against previously compiled binaries, this may be the cause. You can define the _LIBCPP_ABI_USE_CXX03_NULLPTR_EMULATION macro to return to the previous behavior. That macro will be removed in LLVM 15. Please comment [on D109459](https://reviews.llvm.org/D109459) if you are broken by this change and need to define the macro.
On Apple platforms, std::random_device is now implemented on top of arc4random() instead of reading from /dev/urandom. Any implementation-defined token used when constructing a std::random_device will now be ignored instead of interpreted as a file to read entropy from.
std::lognormal_distribution::param_type used to store a data member of type std::normal_distribution; now this member is stored in the lognormal_distribution class itself, and the param_type stores only the mean and standard deviation, as required by the Standard. This changes sizeof(std::lognormal_distribution::param_type). You can define the _LIBCPP_ABI_OLD_LOGNORMAL_DISTRIBUTION macro to return to the previous behavior. That macro will be removed in LLVM 15. Please comment [on PR52906](https://llvm.org/PR52906) if you are broken by this change and need to define the macro.
```
as well as API changes.

**Comment by dileks** [comment]
@markmi 

Looks like you edited your original posting.

I asked @tstellar to clarify on these ABI changes listed in [1] via PM.

[1] https://releases.llvm.org/14.0.0/projects/libcxx/docs/ReleaseNotes.html#abi-changes

**Comment by markmi** [comment]
Yea, libclang is not part of libc++ and so I deleted my mistaken reference. As for [0], its libclang section of the page ( https://releases.llvm.org/14.0.0/tools/clang/docs/ReleaseNotes.html#libclang ) is empty, indicating no C ABI change for accessing clang functionality. But that does not mean that using the C interface to clang results in functionally identical behavior in all observable respects, since the clang code has actually changed some compared to 13.

**Comment by kloczek** [comment]
So is it bug or feature? 🤔

**Comment by kloczek** [comment]
Just checked one thing:
```console
[tkloczko@devel-g2v tmp]$ objdump -x libclang.so.14.0.0 libclang-cpp.so.14.0 |grep SONAME
  SONAME               libclang.so.13
  SONAME               libclang-cpp.so.14.0
```
In other words file name ins case of libclang.so.14.0.0 do not match with SONAME.

Issue is that of distributions which have packaged both clang 14.x and 13.x package manager dependencies resolver is totally confused and it causes that clang 14.x main subpackage with executables will be installed with subpackage with packaged clang 13.x libraries 🤔 

As release notes poins that clang 14.x have some ABI changes not changeing main clang library SONAME is IMO bug. and it would be good if someone from LLVM core devel team would confirm that and perepare JFDI commit to fix that.

As LLVM 14.0.1 has alredy many issues which are causing that literally none of the leading distributions in its devel versions decided to move to LLVM 14.0.1 IMO it would be good to clean at least few known 14.x issues and make new 14.0.2 release ASAP.

Personally I wold be interested to sort out https://github.com/llvm/llvm-project/issues/54897

**Comment by tstellar** [comment]
> As release notes poins that clang 14.x have some ABI changes not changeing main clang library SONAME is IMO bug. and it would be good if someone from LLVM core devel team would confirm that and perepare JFDI commit to fix that.

The ABI changes are only in the C++ library (libclang-cpp.so) and not in the C library (libclang.so)

**Comment by kloczek** [comment]
> The ABI changes are only in the C++ library (libclang-cpp.so) and not in the C library (libclang.so)

Nevertheless this is causing some packaging issuew which I've described.
clang and llvm libraries are used by only handfull of projects so it is not big deal to rebuild everything what is using llvm/clang SO.

**Comment by markmi** [comment]
> The ABI changes are only in the C++ library (libclang-cpp.so) and not in the C library (libclang.so)

I'll quote https://gcc.gnu.org/onlinedocs/gcc-12.1.0/gcc/Compatibility.html#Compatibility on the  type of issue:

QUOTE
compatibility
Conformance to the same ABI and the same behavior of implementation-defined features are both relevant for compatibility.
END QUOTE

**Comment by gpakosz** [comment]
On Arch Linux, I have
```
$ /sbin/ldconfig -p | grep clang
        libclang.so.13 (libc6,x86-64) => /usr/lib/libclang.so.13
        libclang.so (libc6,x86-64) => /usr/lib/libclang.so
        libclang-cpp.so.14 (libc6,x86-64) => /usr/lib/libclang-cpp.so.14
        libclang-cpp.so (libc6,x86-64) => /usr/lib/libclang-cpp.so
```

There's no `libclang.so.14` symlink. Is it a packaging problem or an upstream problem?

**Comment by h-vetinari** [comment]
I think this can be considered fixed by https://github.com/llvm/llvm-project/commit/bc39d7bdd4977a953b2e102f8f7eb479ad78984e.
