### ISSUE TITLE
tests should not use source code as input

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5401]
|  |  |
| --- | --- |
| Bugzilla Link | [5029](https://llvm.org/bz5029) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lattner,@MatzeB |

## Extended Description 
Tests in the nightly test suite which need some input file for the test should *not* use their own source code.
  1. If the test needs to be updated this introduces another variable into the performance.
  2. If the test is being miscompiled its possible that editing the source (for debugging) will then mask the bug, but only because the source itself is the input.

We could have a standard set of small/medium/large inputs for the programs which take some arbitrary input, but don't care what it is.

**Comment by gwelymernans** [comment]
This doesn't appear to be actionable anymore, and the one place that ran counter to the suggesting was fixed.
