### ISSUE TITLE
clang-format crashes when formatting "requires" argument after #if-#else

### ISSUE THREAD

**Issue by owenca** [llvm/llvm-project#54019]
@HazardyKnusperkeks, I got some `requires`-related crashes when formatting `.cpp` files under `clang/test/`. Below is one (which I reduced to the bare minimum) of them:
```
$ cat .clang-format
BasedOnStyle: LLVM
$ clang-format --version
clang-format version 15.0.0 (https://github.com/llvm/llvm-project 77e60bc42c48e16d646488d43210b1630cd4db49)
$ clang-format
#if 0
#else
foo();
#endif
bar(requires);
Assertion failed: (RequiresToken->getType() == TT_Unknown), function parseRequiresExpression, file UnwrappedLineParser.cpp, line 3022.
...
```

**Comment by HazardyKnusperkeks** [comment]
Review: https://reviews.llvm.org/D120512

**Comment by HazardyKnusperkeks** [comment]
As seen in the patch it just happens in the presence of preprocessor branches, but what are you doing with `bar(requires)`? Or how did it look before you made it minimal?
