### ISSUE TITLE
Backport 3cc15e2cb6 onto LLVM 14.0.0

### ISSUE THREAD

**Issue by anton-afanasyev** [llvm/llvm-project#54013]
/cherry-pick 3cc15e2cb6

**Comment by tstellar** [comment]
@alexey-bataev What do you think about backporting this? https://github.com/llvm/llvm-project/commit/3cc15e2cb657f3a814c8bd482bb7108782561abd

**Comment by alexey-bataev** [comment]
Need to backport.

**Comment by tstellar** [comment]
Merged: 4fe93c000b20
