### ISSUE TITLE
Major compile-time regression after [SLP] Remove cap on schedule window size 

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#54029]
@preames https://github.com/llvm/llvm-project/commit/6adf4b039e095224edbbecda5972e5e3353b53b6 caused a 60% compile-time regression on [shared_sha256.c](https://github.com/llvm/llvm-test-suite/blob/main/MultiSource/Applications/ClamAV/shared_sha256.c) from llvm-test-suite in `O3` configuration.

**Comment by preames** [comment]
@nikic Do you have links to results?  Is this a noisy result?  Did the test performance improve?  Any other context?

Will take a look in parallel.

**Comment by nikic** [comment]
> @nikic Do you have links to results?

https://llvm-compile-time-tracker.com/compare.php?from=2f906683ed14668ceed1f85922789abffd8429fd&to=6adf4b039e095224edbbecda5972e5e3353b53b6&stat=instructions&details=on

> Is this a noisy result?

This is in terms of instruction count, so it's not noisy. (Though in terms of wall-time, it also regresses by the same amount, but that *is* noisy.)

> Did the test performance improve?

There are no code size changes, so no.

**Comment by preames** [comment]
Looks like the overall results are fairly normal, with this one major outlier.

Reverting now, will investigate offline and report back.

**Comment by nikic** [comment]
Closing this as the change has been reverted.
