### ISSUE TITLE
IR outliner verification issues with musttail + swifttailcc

### ISSUE THREAD

**Issue by ornata** [llvm/llvm-project#54027]
https://godbolt.org/z/f8WeaejPv

When we create an outlined function with `musttail` from a `swifttailcc` caller, we get

```
cannot guarantee tail call due to mismatched calling conv
  musttail call swifttailcc void @musttail()
LLVM ERROR: Broken module found, compilation aborted!
```

This can appear when compiling large Swift programs with the IR outliner enabled.

**Comment by ornata** [comment]
@AndrewLitteken do you have any idea what's going on here?

**Comment by aschwaighofer** [comment]
If the outliner outlines from a function with a `musttail call swifttailcc` call the calling convention of the outlined function must also be set to `swifttailcc` (as was the original function we outlined from).

A `musttail swifttailcc` call requires the enclosing function to be `swiftailcc`.

**Comment by AndrewLitteken** [comment]
The outliner doesn't have any sort of facility for setting the calling convention right now.  So the function gets created without any specific convention, and then fails the checks.

I think the solution would be to add a check for this in `createFunction` in `IROutliner.cpp` and then add this calling convention to the function (potentially extracting this information from the candidate sections extracted by the CodeExtractor, but I am also not sure that the CodeExtractor doesn't have the same issue).

We could also inherent the calling convention from the outlined sections' parent function that has a specified calling convention, but I'm not sure that's generally correct.

**Comment by aschwaighofer** [comment]
You will also want to make sure that you tail call that outlined fragment. Otherwise, you break swift's async functions-- we can't accumulate any non bounded stack space for `swiftailcc` call sequences marked as `musttail` hence the `musttail` attribute usage.

A simple initial solution could be to not outline regions that contain such calls (`musttail swifttailcc`)

**Comment by aschwaighofer** [comment]
This applies to all `musttail` calls btw. Inserting an outlined thunk that is not tail called breaks the desired semantics of that attribute on the original call.

**Comment by AndrewLitteken** [comment]
I'm working on trying to correctly implement it with the tail call, but yes, that would seem to work.  I can add a patch for this later, but in the mean time adding this at `include/Tranforms/IPO/IROutliner.h:376`

```
      if (CI.getCallingConv() == CallingConv::SwiftTail)
        return false;
      if (CI.isMustTailCall())
        return false;
```

Should be the quick fix suggested.

**Comment by ornata** [comment]
I think the quick fix is okay for now for the purposes of unbreaking Swift? I'd just add a TODO with a link to this issue for the time being.

**Comment by AndrewLitteken** [comment]
Quick fix for tail calls: https://reviews.llvm.org/D120733

**Comment by AndrewLitteken** [comment]
Full fix for tail calls: https://reviews.llvm.org/D120867

**Comment by xgupta** [comment]
crash is not there on trunk - https://godbolt.org/z/76v64b6PP. We can remove the crash label.

**Comment by xgupta** [comment]
Fixed on trunk - https://godbolt.org/z/Y6We7j885.
