### ISSUE TITLE
Backport 371fcb720e15906e8c63600253afcb806b9b10d0

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#54033]
/cherry-pick 371fcb720e15906e8c63600253afcb806b9b10d0

**Comment by LebedevRI** [comment]
/cherry-pick c9c93073010d10957bc124e7e4312aa6ce9e70f7 371fcb720e15906e8c63600253afcb806b9b10d0

**Comment by tstellar** [comment]
@nikic What do you think about backporting these? https://github.com/llvm/llvm-project/commit/c9c93073010d10957bc124e7e4312aa6ce9e70f7 https://github.com/llvm/llvm-project/commit/371fcb720e15906e8c63600253afcb806b9b10d0

**Comment by LebedevRI** [comment]
I find this feedback to be rather subjective and dismissive.
Can someone point me to the objective documentation on LLVM stable release lifecycle?

**Comment by tstellar** [comment]
@LebedevRI Let's have a debate on the technical issues, why do you think this patch should be backported?

**Comment by nikic** [comment]
@LebedevRI Sorry, this was not intended to be dismissive. I *assumed* this was about the rust optimization issue because it was mentioned in the review and commit. Is there some other project for which this optimization is important?

As this is a feature addition rather than a bugfix, I do think there needs to be *some* kind of motivation to perform a release backport. Or at least that was my understanding, maybe I'm wrong on that.

**Comment by LebedevRI** [comment]
@tstellar Because it rather straight-forwardly addresses a rather surprising optimization failure.
The backport request was filed even before rc2, so i feel like this is prime backport material.

@nikic i have no current interest in rust, so that seems irrelevant to me :)
I don't know whether or not that change addressed that rust bugreport,
or merely helps it.


But let me ask again, is there a documented procedure/guidelines for the stable release process?

**Comment by tstellar** [comment]
@LebedevRI https://llvm.org/docs/HowToReleaseLLVM.html#id11

**Comment by tstellar** [comment]
I'm on the fence about backporting this, but I think since it is fixing an actual issue reported by a user, that it is worth backporting.

**Comment by tstellar** [comment]
Merged: da3953fb0315c0e65cc12479f3cd56a1dad7bc3f ba9ff030d302910e0d2155536558f71da98d5a5a
