### ISSUE TITLE
Backport d9da6a535f21946cfaac1516ef28ac7646211d56

### ISSUE THREAD

**Issue by wsmoses** [llvm/llvm-project#54031]
/chery-pick 73ee82871e60ab87af7a722ef089ede17e97ea9f

AND

/cherry-pick d9da6a535f21946cfaac1516ef28ac7646211d56

This resolves a performance regression on a variety of places due to a phase ordering change

cc @nikic @davidbolvansky @LebedevRI

**Comment by LebedevRI** [comment]
Needs tests to be cherry-picked first though.

**Comment by wsmoses** [comment]
Updated the comment to include the tests commit as well. Not sure if that will do the intended behavior, if not I'll make a branch with both.

**Comment by tstellar** [comment]
/cherry-pick 73ee82871e60ab87af7a722ef089ede17e97ea9f d9da6a535f21946cfaac1516ef28ac7646211d56

**Comment by nikic** [comment]
/cherry-pick 73ee82871e60ab87af7a722ef089ede17e97ea9f 07cf95942f57a85d9626a1c9ef8b90deb123bdb6 d9da6a535f21946cfaac1516ef28ac7646211d56

**Comment by nikic** [comment]
/cherry-pick 73ee82871e60ab87af7a722ef089ede17e97ea9f a5b9987aab7601176902bf939fed2653f978450c 07cf95942f57a85d9626a1c9ef8b90deb123bdb6 d9da6a535f21946cfaac1516ef28ac7646211d56

**Comment by tstellar** [comment]
Merged: 36bf1a9e628dd086537ec14db3fcf4feed1393e9 1f4613675051f029a769c21996f19aa451ed17db 7d1cd3380add0e3ab6e8040717fc1413604d78bf 2de2a2bba998f4145cfd4298d39bfd5e98485bdd
