### ISSUE TITLE
wrong code at -O1 (all archs)

### ISSUE THREAD

**Issue by olivier-matz-6wind** [llvm/llvm-project#54056]
Hello,

I think clang >= 12 generates a wrong code in -O1 for the following program:

```
#include <stddef.h>

static void *pointer;

void set_pointer(void *data)
{
    pointer = data;
}

int wait_for_pointer(void)
{
    int i = 0;

    while (pointer == NULL)
        i++;

    return i;
}
```

Since "pointer" is not volatile, it is expected to have some optimizations (pointer value should be read once).
The -O2 code looks correct to me:

```
set_pointer:                            # @set_pointer
        mov     qword ptr [rip + pointer], rdi
        ret
wait_for_pointer:                       # @wait_for_pointer
        cmp     qword ptr [rip + pointer], 0
        je      .LBB1_1
        xor     eax, eax
        ret
.LBB1_1:                                # =>This Inner Loop Header: Depth=1
        jmp     .LBB1_1
```

However, in -O1, the code looks over-optimized:

```
set_pointer:                            # @set_pointer
        ret
wait_for_pointer:                       # @wait_for_pointer
        xor     eax, eax
        ret
```

Related link to the compiler explorer : https://godbolt.org/z/r3c9s77ae

**Comment by nikic** [comment]
If pointer is NULL, then wait_for_pointer() goes into an infinite, side-effect-free loop, which is undefined behavior. As such, pointer must be non-NULL.

You can use `-fno-finite-loops` to disable the forward progress requirement.

**Comment by olivier-matz-6wind** [comment]
Hello @nikic, thank you for the explanation.

**Comment by fhahn** [comment]
> The -O2 code looks correct to me:

It looks like with `-O2` / `-O3` LLVM is not removing the store in `set_pointer` while we do at `-O1`: https://godbolt.org/z/h6W6ra5jM

The IR after `-O2`/`-O3` still has a load feeding an `@llvm.assume`, which is what probably keeps the store in the other function alive:

```


@pointer = internal unnamed_addr global i8* null, align 8

define dso_local void @set_pointer(i8* noundef %data) local_unnamed_addr #0 {
entry:
  store i8* %data, i8** @pointer, align 8, !tbaa !3
  ret void
}

define dso_local i32 @wait_for_pointer() local_unnamed_addr #1 {
entry:
  %.pr = load i8*, i8** @pointer, align 8, !tbaa !3
  %phi.cmp = icmp ne i8* %.pr, null
  call void @llvm.assume(i1 %phi.cmp)
  ret i32 0
}

declare void @llvm.assume(i1 noundef) #2

```
