### ISSUE TITLE
Request to cherry-pick ffa4dfc8de52 onto release/14.x

### ISSUE THREAD

**Issue by sdesmalen-arm** [llvm/llvm-project#54054]
ffa4dfc8de52 changes the (assembler) diagnostic message for some of the SME/SVE instructions, but is otherwise NFC.

**Comment by tstellar** [comment]
@TNorthover What do you think about backporting this? https://github.com/llvm/llvm-project/commit/ffa4dfc8de526ba28d12d62a14f984a7e1e9224b

**Comment by TNorthover** [comment]
Yep, looks fine to me.

**Comment by tstellar** [comment]
Merged: 0372676278dd
