### ISSUE TITLE
Clang C++20 Feature: P1814R0 - Wording for Class Template Argument Deduction for Alias Templates

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#54051]
---
id: P1814R0
paper: https://wg21.link/p1814r0

**Comment by alanzhao1** [comment]
Friendly ping, any updates on this?

**Comment by yuanfang-chen** [comment]
@alanzhao1 sorry, I haven't had the time to work on this.

**Comment by yuanfang-chen** [comment]
It turned out this and #54050 are both parts of https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p1021r6.html which I'm currently working on.

**Comment by alanzhao1** [comment]
@yuanfang-chen, I've been looking at this for the past few days, but I saw that you've been pretty active with https://reviews.llvm.org/D139837, which addresses #54050 which is related to this bug. Have you made any progress on this bug? If so, I'll abandon my efforts, as I'm sure you'll have something out before I do and I'd prefer to avoid duplicating work.

**Comment by alanzhao1** [comment]
Thanks for the update! Since you're working on it, I'll abandon my efforts, as you're more experienced in this area.

Feel free to add me as a reviewer to the patch (I'm ayzhao on LLVM's phabricator)

**Comment by robertmaxton42** [comment]
So uh... Any news here? Ran into this pothole today, am vaguely hoping I don't need to switch off of clang to fix it...

**Comment by 13steinj** [comment]
Ran into again today; just for another voice / raised hand.

**Comment by hokein** [comment]
Hi @yuanfang-chen, I wonder what's the status now, are you still working on it? If not, I'm happy to pick it up.

**Comment by hokein** [comment]
Reassign this issue to me. I'm working on it.
