### ISSUE TITLE
Compiler crashes when trying to catch a pybind11::type_error on Windows

### ISSUE THREAD

**Issue by MatthieuHernandez** [llvm/llvm-project#54060]
The compiler Clang v13.0.0 craches at the linking step on Windows when trying to catch a py::type_error from pybind11 libray : 
```cpp
 try {
    auto casted_values = py::cast<std::vector<int32_t>>(values); // Here values is a py::list&.
  } catch (const py::cast_error& e) {
    throw py::type_error("this method expects integers as param");
  }
```
The error is : 
```
LLVM ERROR: Associative COMDAT symbol '??0builtin_exception@pybind11@@QEAA@PEBD@Z' does not exist.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
```
_(Sorry I don't have the backtrace anymore)_
The strange thing is that if I recompile the same code but keep the CMake cache, it works. 🤔 

I have already reported the error in the Pybind11 GitHub, for more information : https://github.com/pybind/pybind11/issues/3746

**Comment by Endilll** [comment]
You say this is crashing at linking step, but can you clarify which linker you are using?
It would also be nice if you can test with with more recent version of Clang.

**Comment by MatthieuHernandez** [comment]
I just tested this same code with Clang v16.0.6 and pybind 2.10.4 and I didn't see any error. This code can now be reintegrated into the project. Thank you for asking 👍
