### ISSUE TITLE
 BOLT-optimized shared object crashes

### ISSUE THREAD

**Issue by KenPatrickLehrmann** [llvm/llvm-project#54066]
Hi,

We ran into an issue using BOLT on one of our (huge) shared library.
BOLT-revision:e0f1dd018e0f94a7d694bc615975c3a7d26d9e50

We currently do not have access to perf counters, we therefore rely on instrumentation. We used the options provided in the README (`-reorder-blocks=cache+ -reorder-functions=hfsort -split-functions=2 -split-all-cold -split-eh -dyno-stats`).

We could not use `--update-debug-sections` because it triggers an assertion, but that's not the issue here. (I'll open a separate issue for this)

The optimized shared library crashes in a part of our code that seems relatively benign. Specifically, it crashes in `DecisionBox_SetContextString` (which is simply calling `PrSr_DecisionBoxSetString` inside a for loop). My experience with assembly is limited but I do find the changes made by BOLT suspicious.

Original binary:
```gdb
Dump of assembler code for function DecisionBox_SetContextString(char const*, char const*):
../src/SearchPersonalization/ConfigManagementSteward/src/decisionboxmanagement.cpp:
155     void DecisionBox_SetContextString(const char *sName, const char *Value) {
156       for (unsigned contextIdx = 0; contextIdx < ssp::EnumTraits<DecisionBoxContext>::kSize; ++contextIdx) {                                                                                                  
   0x0000000001158050 <+0>:     41 54   push   %r12
   0x0000000001158052 <+2>:     49 89 fc        mov    %rdi,%r12                                                                                                                                                  
   0x0000000001158055 <+5>:     55      push   %rbp
   0x0000000001158056 <+6>:     48 89 f5        mov    %rsi,%rbp
   0x0000000001158059 <+9>:     53      push   %rbx
   0x000000000115805a <+10>:    31 db   xor    %ebx,%ebx
   0x000000000115805c <+12>:    0f 1f 40 00     nopl   0x0(%rax)

157         DecisionBoxContext context = ssp::Enum::FromIntegralUnchecked<DecisionBoxContext>(contextIdx);
158         PrSr_DecisionBoxSetString(context, sName, Value);
   0x0000000001158060 <+16>:    89 df   mov    %ebx,%edi
   0x0000000001158062 <+18>:    ff c3   inc    %ebx
   0x0000000001158064 <+20>:    48 89 ea        mov    %rbp,%rdx
   0x0000000001158067 <+23>:    4c 89 e6        mov    %r12,%rsi
   0x000000000115806a <+26>:    67 e8 90 39 ee ff       addr32 callq 0x103ba00 <PrSr_DecisionBoxSetString(DecisionBoxContext, char const*, char const*)>

156       for (unsigned contextIdx = 0; contextIdx < ssp::EnumTraits<DecisionBoxContext>::kSize; ++contextIdx) {
   0x0000000001158070 <+32>:    83 fb 0c        cmp    $0xc,%ebx
   0x0000000001158073 <+35>:    75 eb   jne    0x1158060 <DecisionBox_SetContextString(char const*, char const*)+16>
   0x0000000001158075 <+37>:    5b      pop    %rbx
   0x0000000001158076 <+38>:    5d      pop    %rbp
   0x0000000001158077 <+39>:    41 5c   pop    %r12
   0x0000000001158079 <+41>:    c3      retq
End of assembler dump.

```
BOLT-generated binary:
```gdb
Dump of assembler code for function _Z28DecisionBox_SetContextStringPKcS0_:
   0x00000000011587e0 <+0>:     41 54   push   %r12
   0x00000000011587e2 <+2>:     49 89 fc        mov    %rdi,%r12
   0x00000000011587e5 <+5>:     55      push   %rbp
   0x00000000011587e6 <+6>:     48 89 f5        mov    %rsi,%rbp
   0x00000000011587e9 <+9>:     53      push   %rbx
   0x00000000011587ea <+10>:    31 db   xor    %ebx,%ebx
   0x00000000011587ec <+12>:    0f 1f 40 00     nopl   0x0(%rax)
   0x00000000011587f0 <+16>:    89 df   mov    %ebx,%edi
   0x00000000011587f2 <+18>:    ff c3   inc    %ebx
   0x00000000011587f4 <+20>:    48 89 ea        mov    %rbp,%rdx
   0x00000000011587f7 <+23>:    4c 89 e6        mov    %r12,%rsi
   0x00000000011587fa <+26>:    67 0f af bb 02 ff 83 fb imul   -0x47c00fe(%ebx),%edi
   0x0000000001158802 <+34>:    0c 75   or     $0x75,%al
   0x0000000001158804 <+36>:    eb 5b   jmp    0x1158861 <_Z26DecisionBox_SetContextBoolPKcb+33>
   0x0000000001158806 <+38>:    5d      pop    %rbp
   0x0000000001158807 <+39>:    41 5c   pop    %r12
   0x0000000001158809 <+41>:    c3      retq
End of assembler dump.
```

We believe there's an unexpected change caused by a `callq` instruction, resulting into erroneous code. We tried many options, without any luck.

Removing information about `PrSr_DecisionBoxSetString` from the profile data, or telling BOLT not to process `PrSr_DecisionBoxSetString` makes the problem go away (but then, there are similar issues in other calls).

We're unsure as to whether this is a bug or if we are misusing BOLT. We'd gladly share more information if need be.

**Comment by rafaelauler** [comment]
Thanks for reporting this issue. Do you know which compiler generated this code with addr32 callq?

**Comment by aaupov** [comment]
We can reproduce that BOLT is stripping `addr32` prefix. But turning call into imul is something strange. Can you please dump assembly of the function using
`llvm-bolt <input_binary> -data <fdata> -funcs=DecisionBox_SetContextString -asm-dump` and paste the resulting `DecisionBox_SetContextString.s` file here?

**Comment by KenPatrickLehrmann** [comment]
> Thanks for reporting this issue. Do you know which compiler generated this code with addr32 callq?

We are using g++ (GCC) 9.2.1 20200225, with `-O3 -g -std=gnu++17  -Wl,-Bsymbolic-functions -Wl,--dynamic-list-cpp-new`



> We can reproduce that BOLT is stripping `addr32` prefix. But turning call into imul is something strange. Can you please dump assembly of the function using `llvm-bolt <input_binary> -data <fdata> -funcs= _Z28DecisionBox_SetContextStringPKcS0_ -asm-dump` and paste the resulting `_Z28DecisionBox_SetContextStringPKcS0_.s` file here?

With `-funcs=...`, I get:
```
llvm-bolt: /remote/users/klehrmann/src/llvm-project/bolt/lib/Rewrite/RewriteInstance.cpp:3452: void llvm::bolt::RewriteInstance::mapCodeSections(llvm::RuntimeDyld&): Assertion `TextSection->hasValidSectionID() && ".text section should be valid"' failed.
 #0 0x00007f6a52901aed llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /remote/users/klehrmann/src/llvm-project/llvm/lib/Support/Unix/Signals.inc:565:22
 #1 0x00007f6a52901ba4 PrintStackTraceSignalHandler(void*) /remote/users/klehrmann/src/llvm-project/llvm/lib/Support/Unix/Signals.inc:632:1
 #2 0x00007f6a528ffb60 llvm::sys::RunSignalHandlers() /remote/users/klehrmann/src/llvm-project/llvm/lib/Support/Signals.cpp:97:20
 #3 0x00007f6a52901535 SignalHandler(int) /remote/users/klehrmann/src/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007f6a55980c20 __restore_rt sigaction.c:0:0
 #5 0x00007f6a5187a37f raise (/lib64/libc.so.6+0x3737f)
 #6 0x00007f6a51864db5 abort (/lib64/libc.so.6+0x21db5)
 #7 0x00007f6a51864c89 _nl_load_domain.cold.0 loadmsgcat.c:0:0
 #8 0x00007f6a51872a76 .annobin___GI___assert_fail.end assert.c:0:0
 #9 0x00007f6a55ea35ee llvm::bolt::RewriteInstance::mapCodeSections(llvm::RuntimeDyld&) /remote/users/klehrmann/src/llvm-project/bolt/lib/Rewrite/RewriteInstance.cpp:3452:5
#10 0x00007f6a55ea2fe7 llvm::bolt::RewriteInstance::mapFileSections(llvm::RuntimeDyld&) /remote/users/klehrmann/src/llvm-project/bolt/lib/Rewrite/RewriteInstance.cpp:3418:18
#11 0x00007f6a55ea063b llvm::bolt::RewriteInstance::emitAndLink() /remote/users/klehrmann/src/llvm-project/bolt/lib/Rewrite/RewriteInstance.cpp:3018:43
#12 0x00007f6a55e92d5c llvm::bolt::RewriteInstance::run() /remote/users/klehrmann/src/llvm-project/bolt/lib/Rewrite/RewriteInstance.cpp:794:17
#13 0x000000000040fbc8 main /remote/users/klehrmann/src/llvm-project/bolt/tools/driver/llvm-bolt.cpp:220:73

```

Without -funcs, I only get a few asm dumps... I  tried to hardcode the filter in bolt/lib/Passes/AsmDump.cpp, I get:
```
cat _Z28DecisionBox_SetContextStringPKcS0_-1.s                                                                                                       
        .text
  .globl _Z28DecisionBox_SetContextStringPKcS0_/1
  .type _Z28DecisionBox_SetContextStringPKcS0_/1, %function
_Z28DecisionBox_SetContextStringPKcS0_/1:
        .cfi_startproc
        .cfi_endproc
.size _Z28DecisionBox_SetContextStringPKcS0_/1, .-_Z28DecisionBox_SetContextStringPKcS0_/1
# Jump tables
# BinaryData

```

**Comment by aaupov** [comment]
Heads up that I'm working on preserving addr32 prefix here: https://reviews.llvm.org/D120592.
I'll land this diff today unless there's new feedback on the review.

Not sure it will fix the problem but at least this will reduce the differences between the original and optimized binaries, which should help identify the issue.

**Comment by KenPatrickLehrmann** [comment]
> Heads up that I'm working on preserving addr32 prefix here: https://reviews.llvm.org/D120592. I'll land this diff today unless there's new feedback on the review.
> 
> Not sure it will fix the problem but at least this will reduce the differences between the original and optimized binaries, which should help identify the issue.

Thanks @aaupov, I'll give it a try.

**Comment by KenPatrickLehrmann** [comment]
After a first quick try, I believe this is fixing this issue. Many thanks !

**Comment by aaupov** [comment]
> After a first quick try, I believe this is fixing this issue. Many thanks !

Hi @KenPatrickLehrmann,

I've recently landed diffs to LLVM and BOLT that deal with addr32 prefix:
- LLVM X86 disassembler no longer drops redundant addr32 prefix, so BOLT has the visibility of it.
- However, it's an expected behavior of BOLT to drop this prefix if it's redundant.
- To address that, I've added BOLT functionality to do so, under an option `-x86-strip-redundant-adsize`, which is on by default.

Can you please confirm that this arrangement works with your workload, i.e. the problem doesn't reproduce with the latest BOLT?

**Comment by KenPatrickLehrmann** [comment]
> Can you please confirm that this arrangement works with your workload, i.e. the problem doesn't reproduce with the latest BOLT?

Yes, it looks good to me. Again, many thanks !
