### ISSUE TITLE
huge binaries

### ISSUE THREAD

**Issue by Jolyon0202** [llvm/llvm-project#54075]
# Description

I'm expecting objcopy to create a binary from the attached ELF like this:
llvm-objcopy test.elf -O binary test.bin

Running size tells me that the binary is 2.3GB big. It's Too Big. Is there any way to reduce size??

And I found that the reason of big size is that the section .vectors's and .startup's address (0xffff0000 and 0x70040000) is all filled.

And I am not sure that it's should be all filled. Or How could I reduce size (not modify the layout of sections)?

$ readelf -Sl test.elf
There are 35 section headers, starting at offset 0x45654:

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .vectors          PROGBITS        ffff0000 001000 000078 00  AX  0   0 256
  [ 2] .startup          PROGBITS        70040000 002000 00054a 00  AX  0   0 256
  [ 3] .text             PROGBITS        80000000 003000 001c94 00  AX  0   0 256
  [ 4] .ctors            NOBITS          80001c94 004c94 000000 00  AX  0   0  1
  [ 5] .dtors            NOBITS          80001c94 004c94 000000 00  AX  0   0  1
  [ 6] .api_text         PROGBITS        80001cc0 004cc0 00056c 00  AX  0   0  4
  [ 7] .rodata           PROGBITS        80002240 005240 000600 00 AMS  0   0  8
  [ 8] .stack_sizes      NOBITS          80002840 005840 000000 00  WA  0   0  4
  [ 9] .kernel_bss       NOBITS          80002840 005840 004950 00  WA  0   0  8
  [10] .tbss             PROGBITS        80007190 00a190 000000 00  WA  0   0  8
  [11] .sbss             NOBITS          80007190 00a190 000000 00  WA  0   0  8
  [12] .sbss2            PROGBITS        80007190 00a190 000000 00  WA  0   0  8
  [13] .kernel_data      PROGBITS        80007190 00a190 00008c 00  WA  0   0  4
  [14] .api_bss          NOBITS          80007240 00a21c 000000 00  WA  0   0  8
  [15] .api_data         NOBITS          80007240 00a21c 000000 00  WA  0   0  4
  [16] .app1_bss         PROGBITS        80007240 00a240 000000 00  WA  0   0  8
  [17] .app1_data        NOBITS          80007240 00a240 000000 00  WA  0   0  4
  [18] .bss_cpu0         NOBITS          80007240 00a240 000040 00  WA  0   0  8
  [19] .app1_stack       NOBITS          80007280 00a240 000404 00  WA  0   0  8
  [20] .cpu0.stack       NOBITS          800076c0 00a240 003400 00  WA  0   0 16
  [21] .ARM.attributes   ARM_ATTRIBUTES  00000000 00a240 000047 00      0   0  1
  [22] .debug_str        PROGBITS        00000000 00a287 005379 01  MS  0   0  1
  [23] .debug_loc        PROGBITS        00000000 00f600 004606 00      0   0  1
  [24] .debug_abbrev     PROGBITS        00000000 013c06 0036da 00      0   0  1
  [25] .debug_info       PROGBITS        00000000 0172e0 0180a5 00      0   0  1
  [26] .debug_macinfo    PROGBITS        00000000 02f385 00002a 00      0   0  1
  [27] .comment          PROGBITS        00000000 02f3af 000056 01  MS  0   0  1
  [28] .debug_line       PROGBITS        00000000 02f405 00f93a 00      0   0  1
  [29] .debug_frame      PROGBITS        00000000 03ed40 0012f4 00      0   0  4
  [30] .debug_ranges     PROGBITS        00000000 040034 000480 00      0   0  1
  [31] .debug_aranges    PROGBITS        00000000 0404b4 000088 00      0   0  1
  [32] .symtab           SYMTAB          00000000 04053c 002b60 10     34 398  4
  [33] .shstrtab         STRTAB          00000000 04309c 000164 00      0   0  1
  [34] .strtab           STRTAB          00000000 043200 002453 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings)
  I (info), L (link order), G (group), T (TLS), E (exclude), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)

Elf file type is EXEC (Executable file)
Entry point 0xffff0000
There are 5 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x001000 0xffff0000 0xffff0000 0x00078 0x00078 R E 0x1000
  LOAD           0x002000 0x70040000 0x70040000 0x0054a 0x0054a R E 0x1000
  LOAD           0x003000 0x80000000 0x80000000 0x02840 0x02840 R E 0x1000
  LOAD           0x005840 0x80002840 0x80002840 0x04a00 0x04e44 RW  0x1000
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0

 Section to Segment mapping:
  Segment Sections...
   00     .vectors
   01     .startup
   02     .text .ctors .dtors .api_text .rodata
   03     .stack_sizes .kernel_bss .tbss .sbss .sbss2 .kernel_data .api_bss .api_data .app1_data .bss_cpu0 .app1_stack
   04

**Comment by jh7370** [comment]
I can't really answer your question directly, as I'm not all that familiar with binary output. Does GNU objcopy produce the same output or something different?

I also don't think that input file looks valid to me. The ELF gABI states that addresses are unsigned (so 0xffff0000 is greater than 0x80000000), and that "Loadable segment entries in the program header table appear in ascending order, sorted on the p_vaddr member". Note that the .vectors section is in a PT_LOAD segment that appears before the .startup PT_LOAD, in the file, but has the higher address space.

By the way, I don't see an attachment.

**Comment by jsonn** [comment]
Ignoring whether this is a valid ELF binary, the output is certainly the size I would expect. Binary files have no concept of separately mapped areas, so they should cover the minimum to maximum address in used. In your case, that's in the area of 2GB.

**Comment by Jolyon0202** [comment]
> I can't really answer your question directly, as I'm not all that familiar with binary output. Does GNU objcopy produce the same output or something different?
> 
> I also don't think that input file looks valid to me. The ELF gABI states that addresses are unsigned (so 0xffff0000 is greater than 0x80000000), and that "Loadable segment entries in the program header table appear in ascending order, sorted on the p_vaddr member". Note that the .vectors section is in a PT_LOAD segment that appears before the .startup PT_LOAD, in the file, but has the higher address space.
> 
> By the way, I don't see an attachment.
[test.zip](https://github.com/llvm/llvm-project/files/8145580/test.zip)

Sorry about that. This is test.elf. 

By the way, GNU objcopy produce the same output. Agree with jsonn says "Binary files have no concept of separately mapped areas, so they should cover the minimum to maximum address in used",  we want to find a way to reduce size.

**Comment by Jolyon0202** [comment]
> Ignoring whether this is a valid ELF binary, the output is certainly the size I would expect. Binary files have no concept of separately mapped areas, so they should cover the minimum to maximum address in used. In your case, that's in the area of 2GB.

Agree with you, thanks!

**Comment by guoqiang1991216** [comment]
> Ignoring whether this is a valid ELF binary, the output is certainly the size I would expect. Binary files have no concept of separately mapped areas, so they should cover the minimum to maximum address in used. In your case, that's in the area of 2GB.

thansk for your reply.In the actual application, if I want to generate a smaller binary file, do I support it? (e.g. Intel HEX File, Motorola S-record File) , as shown in the following figure:
![image](https://user-images.githubusercontent.com/65532798/155823276-fc2edc74-34c2-48f5-9d31-67f62c580380.png)

**Comment by MaskRay** [comment]
You may read https://github.com/llvm/llvm-project/blob/main/llvm/lib/ObjCopy/ELF/ELFObject.cpp#L2639 for the `-O binary` layout algorithm. It computes LMA for each non-empty SHF_ALLOC section, then the minimum LMA `MinAddr`. For a section with LMA `O`, it writes its content at file offset `O - MinAddr`.

In your example, `.startup`'s address is 0x70040000, very far away from the end 0xffff0078, so the large size is working as intended. If you want the output to be smaller, make the address gap smaller.
