### ISSUE TITLE
no analyzer checkers or packages are associated with 'example.MainCallChecker'  when I use libMainCallChecker.so

### ISSUE THREAD

**Issue by for-just-we** [llvm/llvm-project#54070]
I build MainCallChecker in [SampleAnalyzer](https://github.com/llvm/llvm-project/tree/main/clang/lib/Analysis/plugins/SampleAnalyzer) out-of-tree with CMake,  when I use compiled checker plugin to test test_files. clang report error:

```
error: unable to load plugin 'libMainCallChecker.so': 'libMainCallChecker.so: undefined symbol: _ZN4llvm18format_object_base4homeEv'
error: no analyzer checkers or packages are associated with 'example.MainCallChecker'
note: use -analyzer-disable-all-checks to disable all static analyzer checkers
```

The content in my Cmakelists.txt is

```
set(LLVM_LINK_COMPONENTS
        Support
        )

set(LLVM_EXPORTED_SYMBOL_FILE ${CMAKE_CURRENT_SOURCE_DIR}/SampleAnalyzerPlugin.exports)

add_library(MainCallChecker MODULE
        MainCallChecker.cpp
        )

#set_target_properties(MainCallChecker PROPERTIES
#        CXX_VISIBILITY_PRESET hidden
#        )

target_include_directories(MainCallChecker
        INTERFACE
        ${CMAKE_CURRENT_SOURCE_DIR}
        )

target_link_libraries(MainCallChecker
        PRIVATE
        clangAnalysis
        clangAST
        clangStaticAnalyzerCore
        clangStaticAnalyzerFrontend
        )

install(TARGETS MainCallChecker DESTINATION lib)
```

How could I fix this error?

**Comment by steakhal** [comment]
You should probably link against the library defining the `_ZN4llvm18format_object_base4homeEv` symbol.
AFAIK that is the `LLVMSupport`, so add it to the `target_link_libraries(MainCallChecker PRIVATE ... LLVMSupport)`

**Comment by for-just-we** [comment]
Thank you very much, I found that  lib `clang-cpp` could solve all the problems.

```
target_link_libraries(MainCallChecker
        PRIVATE
        clang-cpp
        )
```

Now I have another question,  I recently follow [clang-plugins-demo](https://github.com/nsumner/clang-plugins-demo) and [clang-tutor](https://github.com/banach-space/clang-tutor) to learn writing libtooling checkers.  I found some examples that ASTVisitor-based and ASTMatcher-based checkers being called through function chain `main -> PluginASTAction -> ASTConsumer -> checkers`. 

But in CSA-based checkers [example](https://github.com/nsumner/clang-plugins-demo/blob/master/tools/runstreamchecker/main.cpp#L133),  the `clang::ento::AnalysisAction` object just load checker plugin which is compiled into dynamic lib like clang compiler, could `clang::ento::AnalysisAction` call checker in a similar static way like in AST-based checker like `Action -> Consumer -> Checker`? Because for me, it would be easier to debug checkers.

**Comment by steakhal** [comment]
I don't get the question, probably because we are not using plugins. We build our own clang and that's it.
In the past, we also developed CSA plugins, but those are ABI incompatible with any other clang binaries anyway, thus we decided to use our own fork directly.
Unfortunately, I don't have the time to tinker with this issue.
However, we used a different way of bootstrapping the plugin than what is shown in that example I recall - but I'm not sure.
Can I close this?
PS: raise your questions on the static-analyzer channel at Discord if you have any. Feel free to ping me there.

**Comment by for-just-we** [comment]
> I don't get the question, probably because we are not using plugins. We build our own clang and that's it. In the past, we also developed CSA plugins, but those are ABI incompatible with any other clang binaries anyway, thus we decided to use our own fork directly. Unfortunately, I don't have the time to tinker with this issue. However, we used a different way of bootstrapping the plugin than what is shown in that example I recall - but I'm not sure. Can I close this? PS: raise your questions on the static-analyzer channel at Discord if you have any. Feel free to ping me there.

of course, thank you
