### ISSUE TITLE
wrong type conversion(int to uint64_t on x86) under some circumstance

### ISSUE THREAD

**Issue by versaloon** [llvm/llvm-project#54096]
https://developercommunity.visualstudio.com/t/x86%E4%B8%8Bclang-1300%E7%BC%96%E8%AF%91%E5%99%A8%EF%BC%8Cint%E7%B1%BB%E5%9E%8B%E5%8F%98%E9%87%8F%E4%BD%9C%E4%B8%BA%E5%8F%82%E6%95%B0%E8%BD%ACuint64_t/1669439

MS guys suggest me to issue here.

The first post is in Chinese, translation is blow:

The source code is index-pack.c from a patched git source code, which will cal start_progess in progess.c to display progress of git clone.
struct progress *start_progress(const char *title, uint64_t total);

The 1st picture(in the first post of the issue in microsoft community) is before calling start_progress, red lines are title parameter, yellow lines are total which is nr_objects of int type. All the values are right, nr_objects will be pushed into stack  as a 32-bit value.

The 2nd picture is after calling to start_progress, red lines are for title, yellow lines for total. Here total is 2 32-bit value read from stack, with lower 32-bit value corresponding to nr_objects, and wrong higher 32-bit value(should be zero). And afterwards, clone is OK, but the progress displayed is wrong.

I also tried to implement a simple demo to reproduce the issue, but it seems the issue only exists in the code above. And also there is a BUG in x64|Release, as I mentioned in the MS community. x64|Debug is OK.

**Comment by phoebewang** [comment]
Can you find the command of compiling index-pack.c and paste here? Maybe you need `-E` to pre-process it and put the processed file here too.
I can see the problem is lacking of clear for [esp+8]. I can analyze it based on the single file.

**Comment by versaloon** [comment]
The command line options(copied from comand line configuration in Visual Studio):
/MP /GS /W3 /I"Z:\vsf.linux\project\vc_git_hostsock\" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\application" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\application\3rd-party\ncurses\port" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\application\3rd-party\ncurses\awk" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\application\3rd-party\ncurses\raw\include" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\application\3rd-party\ncurses\raw\ncurses" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\application\3rd-party\less\port" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\application\3rd-party\less\autogen" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\application\3rd-party\less\raw" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\application\3rd-party\curl\port" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\application\3rd-party\curl\raw\include" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\application\3rd-party\curl\raw\lib" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\application\3rd-party\git\port" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\application\3rd-party\git\autogen" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\application\3rd-party\git\raw" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\application\3rd-party\git\raw\compat\regex" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\config\3rd-party" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\vsf\example\template\demo\common" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\vsf\source" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\vsf\source\shell\sys\linux\include" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\vsf\source\shell\sys\linux\include\simple_libc" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\vsf\source\shell\sys\linux\include\libusb" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\vsf\source\shell\sys\linux\kernel\fs\vfs\files\terminfo" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\config" /I"Z:\vsf.linux\project\vc_git_hostsock\lib\npcap\Include" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\vsf\source\component\3rd-party\zlib\raw" /I"Z:\vsf.linux\project\vc_git_hostsock\..\..\vsf\source\component\3rd-party\mbedtls\raw\include" /Zi /Od /fp:precise /D "__VSF__" /D "__CPU_X86__" /D "__WIN__" /D "APP_USE_LINUX_LESS_DEMO=ENABLED" /D "APP_USE_LINUX_CURL_DEMO=ENABLED" /D "APP_USE_LINUX_GIT_DEMO=ENABLED" /D "_DEBUG" /D "_CONSOLE" /D "_CRT_SECURE_NO_WARNINGS" /D "_UNICODE" /D "UNICODE" /WX- /Gd /Oy- /MTd /Fa"vsf_linux\Debug\/__sub0/__sub1/__sub2/__sub3/%(RelativeDir)" /nologo /Fo"vsf_linux\Debug\/__sub0/__sub1/__sub2/__sub3/%(RelativeDir)" /Fp"vsf_linux\Debug\vsf_linux.pch" /diagnostics:column 

Extra Options:
-fms-extensions

The -E output:
[index-pack.log](https://github.com/llvm/llvm-project/files/8148047/index-pack.log)

**Comment by versaloon** [comment]
```c
static void parse_pack_objects(unsigned char *hash)
{
	int i, nr_delays = 0;
	struct ofs_delta_entry *ofs_delta = ofs_deltas;
	struct object_id ref_delta_oid;
	struct stat st;

	if (verbose)
		progress = start_progress(
				progress_title ? progress_title :
				from_stdin ? _("Receiving objects") : _("Indexing objects"),
				nr_objects);
	for (i = 0; i < nr_objects; i++) {
```

```c
1>struct __git_builtin_index_pack_ctx_t {
1> struct list_head __work_head;
1> struct list_head __done_head;
1> size_t __base_cache_used;
1> size_t __base_cache_limit;
1> struct object_entry *__objects;
1> struct object_stat *__obj_stat;
1> struct ofs_delta_entry *__ofs_deltas;
1> struct ref_delta_entry *__ref_deltas;
1> struct thread_local __nothread_data;
1> int __nr_objects;                  << __nr_objects is here as int type
......

1>static void parse_pack_objects(unsigned char *hash)
1>{
1> int i, nr_delays = 0;
1> struct ofs_delta_entry *ofs_delta = (((struct __git_builtin_index_pack_ctx_t *)(vsf_linux_dynlib_ctx(&vsf_git_builtin_index_pack)))->__ofs_deltas);
1> struct object_id ref_delta_oid;
1> struct __wrap_stat st;
1> if ((((struct __git_builtin_index_pack_ctx_t *)(vsf_linux_dynlib_ctx(&vsf_git_builtin_index_pack)))->__verbose))
1>  (((struct __git_builtin_index_pack_ctx_t *)(vsf_linux_dynlib_ctx(&vsf_git_builtin_index_pack)))->__progress) = start_progress(
1>    (((struct __git_builtin_index_pack_ctx_t *)(vsf_linux_dynlib_ctx(&vsf_git_builtin_index_pack)))->__progress_title) ? (((struct __git_builtin_index_pack_ctx_t *)(vsf_linux_dynlib_ctx(&vsf_git_builtin_index_pack)))->__progress_title) :
1>    (((struct __git_builtin_index_pack_ctx_t *)(vsf_linux_dynlib_ctx(&vsf_git_builtin_index_pack)))->__from_stdin) ? _("Receiving objects") : _("Indexing objects"),
1>    (((struct __git_builtin_index_pack_ctx_t *)(vsf_linux_dynlib_ctx(&vsf_git_builtin_index_pack)))->__nr_objects));
1> for (i = 0; i < (((struct __git_builtin_index_pack_ctx_t *)(vsf_linux_dynlib_ctx(&vsf_git_builtin_index_pack)))->__nr_objects); i++) {
```

The code is porting git onto MCU without real linux, with a simple linux layer about 20-30KB code size.
In order to make git re-entrant, I put all the .bss&.data in the process local storage, which can be obtained by vsf_linux_dynlib_ctx with a library index parameter. so the nr_objects variable is actually a call to vsf_linux_dynlib_ctx and get the __nr_objects in the structure returned.This works good except here. And I also tried to implement a simpler demo to reproduce the issue, but the simple demo works OK as I mentioned in the MS community.

**Comment by versaloon** [comment]
BTW, there is a similar issue around the same code in Release|x64. start_progress will return the right 64-bit pointer, but only lower 32-bit will be saved. I also mention this in the MS report.

**Comment by phoebewang** [comment]
> The -E output: index-pack.log
Can you use /EP and redirect it to a file?

I also cloned all the submodules, but still got the error:
`../vsf.linux/vsf/source/component/fs/./driver/littlefs/vsf_littlefs.h(28,10): fatal error: 'lfs.h' file not found`
Besides, I didn't find a path `vsf\example\template\demo\common`
Maybe better to package all the code here?

**Comment by versaloon** [comment]
use this project: vsf.linux/project/vc_git_hostsock/vsf_linux.sln
I checked again, there is no littlefs dependency on this project.

https://github.com/vsfteam/vsf/tree/master/example/template/demo/common
The common directory is here, it's in the vsf submodule.

the index-pack.c after proprocessor:
[index-pack.zip](https://github.com/llvm/llvm-project/files/8148989/index-pack.zip)

**Comment by phoebewang** [comment]
This is a problem of header file conflict.
The `index-pack.c` includes `progress.h` which should comes from `git` directory. But it actually comes from `curl`.
So the prototype of `start_progress` defined on `progress.h` is missing. Compiler should have warned it and then assumed the argument is the same with the integer it being passed.
I checked adding the prototype manually can generate different assembly and should solve this problem.
`clang-cl index-pack.c /c /FA -m32  -fms-extensions /fp:precise`

![image](https://user-images.githubusercontent.com/5205802/155921314-82cc4f08-7f30-4427-b083-ce70efee90d5.png)

You may need to fix the problem by adjusting the making process.

**Comment by versaloon** [comment]
Thanks, I remember the problem.
Visual Studio does not support setting include path parameter for virtual folder, so has to include all the path in the project configuration.
I will try to switch to cmake.

**Comment by versaloon** [comment]
I found the corresponding warning among a lot of compiler warnings.
I will close the issue, thanks again.
