### ISSUE TITLE
Minimum CMake version is too low

### ISSUE THREAD

**Issue by Kobzol** [llvm/llvm-project#54099]
The minimum supported CMake version is currently set to `3.13.4` (https://github.com/llvm/llvm-project/blob/main/llvm/CMakeLists.txt#L3). However, the `bolt` subproject uses the `TYPE` parameter for the `install` command (https://github.com/llvm/llvm-project/blob/main/bolt/tools/driver/CMakeLists.txt#L38), which does not seem to work in this version. It seems that the minimum CMake version should be bumped to `3.14.0`.

CMake 3.13: https://cmake.org/cmake/help/v3.13/command/install.html#programs (TYPE is missing)
CMake 3.14: https://cmake.org/cmake/help/v3.14/command/install.html#programs (TYPE is present)

I hit this while trying to build BOLT with LLVM 3.13.4 in a `rustc` CI workflow.

This has also been noticed in other projects: https://github.com/coelckers/prboom-plus/pull/126/files.

**Comment by nikic** [comment]
It would be preferable to make it compatible with cmake 3.13.4 instead. It's annoying/confusing to have a single subproject with a different cmake version requirement.

**Comment by tschuett** [comment]
https://reviews.llvm.org/D120625

**Comment by aaupov** [comment]
@tschuett, @nikic
I've put up this diff before I saw the comment about different cmake requirements. I agree with it, so will try to remove/rework the incompatible line to stay compatible with the LLVM CMake requirement.

**Comment by aaupov** [comment]
https://reviews.llvm.org/D121012

**Comment by aaupov** [comment]
Committed to both main and release/14.x
