### ISSUE TITLE
clang-format: AlignArrayOfStructures is broken

### ISSUE THREAD

**Issue by epixinvites** [llvm/llvm-project#54095]
Currently running on: `clang-format version 13.0.1`
[Here](https://termbin.com/lmch)'s my clang-format

So, here's a piece of code
```cpp
std::vector<std::pair<int, int>> input {
{1, 5},
{4, 8},
{1, 3},
{9, 10},
{3, 9},
{6, 10},
{2, 8}
};
```
with `AlignArrayOfStructures` set to `Left`, it returns me this
```cpp
std::vector<std::pair<int, int>> input {
{1, 5 },
{4, 8 },
{1, 3 },
{9, 10},
 {3, 9 },
 {6, 10},
  {2, 8 }
};
```
which clearly isn't the same as what is shown [here](https://clang.llvm.org/docs/ClangFormatStyleOptions.html).

I've attached my clang-format above because I have no idea if any other options I have are conflicting options.

Here's my expected result from my configuration:
```cpp
std::vector<std::pair<int, int>> input {
	{1, 5 },
	{4, 8 },
	{1, 3 },
	{9, 10},
	{3, 9 },
	{6, 10},
	{2, 8 }
};
```

Why is `AlignArrayOfStructures: Left` giving me weird indentations and why isn't it indenting the sub-initializations by a tab? (You can see in the above that clang-format doesn't indent my sub-initializations.)

**Comment by epixinvites** [comment]
I've solved the problem

**Comment by WillOnGit** [comment]
@epixinvites I'm having similar weird issues with clang-format 15, what was the problem and solution?
