### ISSUE TITLE
Cherry-pick 6aa8521fdb7a551e32927cce71ecb0c424b51955 to LLVM 14

### ISSUE THREAD

**Issue by jrtc27** [llvm/llvm-project#54107]
/cherry-pick 6aa8521fdb7a551e32927cce71ecb0c424b51955

**Comment by tstellar** [comment]
@asb What do you think about backporting this? https://github.com/llvm/llvm-project/commit/6aa8521fdb7a551e32927cce71ecb0c424b51955

**Comment by asb** [comment]
I think this definitely makes sense to backport.

**Comment by tstellar** [comment]
Merged: cdd8cca0c33c 8400036358c8 f8ca5fabdb54 4de8e5698278
