### ISSUE TITLE
clang-format improperly formats concept definitions with Clang builtins

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#54106]
Given
```
template<class T>
concept integral = __is_integral(T);
```
clang-format reformats this as
```
template<class T>
concept integral =
__is_integral(T);
```
This behaviour isn't observed for non-builtins.

## System details
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```
```
$ clang-format --version
Ubuntu clang-format version 15.0.0-++20220225053013+37e84d9be06d-1~exp1~20220225173121.170
```

## clang-format style options

This [.clang-format] is very close to the style options that are actually being used.

[.clang-format]: https://github.com/cjdb/project_template/blob/main/.clang-format

**Comment by HazardyKnusperkeks** [comment]
Okay, this forced me to learn something new.

Review: https://reviews.llvm.org/D120774
