### ISSUE TITLE
`ReadabilityModuleTest` including clang's `ASTMatchersTest.h` breaks standalone builds

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#54116]
The very first line of `clang-tools-extra/unittests/clang-tidy/ReadabilityModuleTest.cpp` is:

```
#include "../../clang/unittests/ASTMatchers/ASTMatchersTest.h"
```

but in the case of standalone builds, clang-tidy can't just include a file from the clang source tree, as it might not be there at all. I'm not familiar with the code base so I'm not sure what to do about the test.

**Comment by whisperity** [comment]
Are standalone builds still a supported ideology, since the move to the monorepo?

**Comment by tbaederr** [comment]
The feedback on https://discourse.llvm.org/t/standalone-build-for-clang-lld-fix-or-remove/59977 was that they are needed, yes.

**Comment by nikic** [comment]
The problematic include was removed in https://github.com/llvm/llvm-project/commit/6357f1c1aa7694240a3b18e164faa977383dc9b6.
