### ISSUE TITLE
program crash when run clang static analyzer

### ISSUE THREAD

**Issue by hyxl1017** [llvm/llvm-project#54111]
Hi, I am using CSA framework to implement a checker which is used to check the circular reference of share_ptr, so in the implementation I want to get the return value of the constructor of share_ptr as the key of map and update its point relation afterwards. And finally check for circular dependencies in the checkDeadSymbols callback function.
Here is the line of code that causes the program to crash
![image](https://user-images.githubusercontent.com/98010764/155975906-083ad70a-a487-4fd0-beb0-176ed8df0e01.png)
Here is the crash message printed from the command line
`1.	<eof> parser at end of file
2.	While analyzing stack: 
	#0 Calling A::A(int)
3.	tst.cpp:7:9: Error evaluating statement
4.	tst.cpp:7:9: Error evaluating statement
 #0 0x000055a9541beed8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/hyx/mysrc/llvm-project/llvm/lib/Support/Unix/Signals.inc:565:0
 #1 0x000055a9541bef8f PrintStackTraceSignalHandler(void*) /home/hyx/mysrc/llvm-project/llvm/lib/Support/Unix/Signals.inc:632:0
 #2 0x000055a9541bcc43 llvm::sys::RunSignalHandlers() /home/hyx/mysrc/llvm-project/llvm/lib/Support/Signals.cpp:97:0
 #3 0x000055a9541be859 SignalHandler(int) /home/hyx/mysrc/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:0
 #4 0x00007fe04e49a980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
 #5 0x000055a9569ac15a clang::ento::SymExpr::getKind() const /home/hyx/mysrc/llvm-project/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymExpr.h:56:0
 #6 0x000055a9569a5d2b (anonymous namespace)::SharedPtrCircularReferenceChecker::checkPostCall(clang::ento::CallEvent const&, clang::ento::CheckerContext&) const /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Checkers/SharedPtrCircularReferenceChecker.cpp:120:0
 #7 0x000055a9569a89ac void clang::ento::check::PostCall::_checkCall<(anonymous namespace)::SharedPtrCircularReferenceChecker>(void*, clang::ento::CallEvent const&, clang::ento::CheckerContext&) /home/hyx/mysrc/llvm-project/clang/include/clang/StaticAnalyzer/Core/Checker.h:184:0
 #8 0x000055a9572bf20a clang::ento::CheckerFn<void (clang::ento::CallEvent const&, clang::ento::CheckerContext&)>::operator()(clang::ento::CallEvent const&, clang::ento::CheckerContext&) const /home/hyx/mysrc/llvm-project/clang/include/clang/StaticAnalyzer/Core/CheckerManager.h:73:0
 #9 0x000055a9572b8e94 (anonymous namespace)::CheckCallContext::runChecker(clang::ento::CheckerFn<void (clang::ento::CallEvent const&, clang::ento::CheckerContext&)>, clang::ento::NodeBuilder&, clang::ento::ExplodedNode*) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Core/CheckerManager.cpp:290:0
#10 0x000055a9572bc4ee void expandGraphWithCheckers<(anonymous namespace)::CheckCallContext>((anonymous namespace)::CheckCallContext, clang::ento::ExplodedNodeSet&, clang::ento::ExplodedNodeSet const&) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Core/CheckerManager.cpp:137:0
#11 0x000055a9572b8f69 clang::ento::CheckerManager::runCheckersForCallEvent(bool, clang::ento::ExplodedNodeSet&, clang::ento::ExplodedNodeSet const&, clang::ento::CallEvent const&, clang::ento::ExprEngine&, bool) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Core/CheckerManager.cpp:307:0
#12 0x000055a95733c1d0 clang::ento::CheckerManager::runCheckersForPostCall(clang::ento::ExplodedNodeSet&, clang::ento::ExplodedNodeSet const&, clang::ento::CallEvent const&, clang::ento::ExprEngine&, bool) /home/hyx/mysrc/llvm-project/clang/include/clang/StaticAnalyzer/Core/CheckerManager.h:320:0
#13 0x000055a957339870 clang::ento::ExprEngine::handleConstructor(clang::Expr const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Core/ExprEngineCXX.cpp:683:0
#14 0x000055a957339a1e clang::ento::ExprEngine::VisitCXXConstructExpr(clang::CXXConstructExpr const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Core/ExprEngineCXX.cpp:690:0
#15 0x000055a95730a183 clang::ento::ExprEngine::Visit(clang::Stmt const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:1839:0
#16 0x000055a957305d6a clang::ento::ExprEngine::ProcessStmt(clang::Stmt const*, clang::ento::ExplodedNode*) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:998:0
#17 0x000055a957304ffb clang::ento::ExprEngine::processCFGElement(clang::CFGElement, clang::ento::ExplodedNode*, unsigned int, clang::ento::NodeBuilderContext*) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:843:0
#18 0x000055a9572d59e9 clang::ento::CoreEngine::HandlePostStmt(clang::CFGBlock const*, unsigned int, clang::ento::ExplodedNode*) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:470:0
#19 0x000055a9572d452a clang::ento::CoreEngine::dispatchWorkItem(clang::ento::ExplodedNode*, clang::ProgramPoint, clang::ento::WorkListUnit const&) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:192:0
#20 0x000055a9572d41bb clang::ento::CoreEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int, llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:147:0
#21 0x000055a95694dee4 clang::ento::ExprEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int) /home/hyx/mysrc/llvm-project/clang/include/clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h:192:0
#22 0x000055a9568de4de (anonymous namespace)::AnalysisConsumer::RunPathSensitiveChecks(clang::Decl*, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:680:0
#23 0x000055a9568de263 (anonymous namespace)::AnalysisConsumer::HandleCode(clang::Decl*, unsigned int, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:649:0
#24 0x000055a9568dcfcb (anonymous namespace)::AnalysisConsumer::VisitFunctionDecl(clang::FunctionDecl*) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:327:0
#25 0x000055a9568f30d6 clang::RecursiveASTVisitor<(anonymous namespace)::AnalysisConsumer>::WalkUpFromFunctionDecl(clang::FunctionDecl*) /home/hyx/mysrc/llvm-project/build/tools/clang/include/clang/AST/DeclNodes.inc:421:0
#26 0x000055a9568f373c clang::RecursiveASTVisitor<(anonymous namespace)::AnalysisConsumer>::WalkUpFromCXXMethodDecl(clang::CXXMethodDecl*) /home/hyx/mysrc/llvm-project/build/tools/clang/include/clang/AST/DeclNodes.inc:431:0
#27 0x000055a9568f37ac clang::RecursiveASTVisitor<(anonymous namespace)::AnalysisConsumer>::WalkUpFromCXXConstructorDecl(clang::CXXConstructorDecl*) /home/hyx/mysrc/llvm-project/build/tools/clang/include/clang/AST/DeclNodes.inc:435:0
#28 0x000055a9568e7979 clang::RecursiveASTVisitor<(anonymous namespace)::AnalysisConsumer>::TraverseCXXConstructorDecl(clang::CXXConstructorDecl*) /home/hyx/mysrc/llvm-project/clang/include/clang/AST/RecursiveASTVisitor.h:2128:0
#29 0x000055a9568df554 clang::RecursiveASTVisitor<(anonymous namespace)::AnalysisConsumer>::TraverseDecl(clang::Decl*) /home/hyx/mysrc/llvm-project/build/tools/clang/include/clang/AST/DeclNodes.inc:435:0
#30 0x000055a9568ebbdc clang::RecursiveASTVisitor<(anonymous namespace)::AnalysisConsumer>::TraverseDeclContextHelper(clang::DeclContext*) /home/hyx/mysrc/llvm-project/clang/include/clang/AST/RecursiveASTVisitor.h:1395:0
#31 0x000055a9568e4f79 clang::RecursiveASTVisitor<(anonymous namespace)::AnalysisConsumer>::TraverseCXXRecordDecl(clang::CXXRecordDecl*) /home/hyx/mysrc/llvm-project/clang/include/clang/AST/RecursiveASTVisitor.h:1908:0
#32 0x000055a9568df158 clang::RecursiveASTVisitor<(anonymous namespace)::AnalysisConsumer>::TraverseDecl(clang::Decl*) /home/hyx/mysrc/llvm-project/build/tools/clang/include/clang/AST/DeclNodes.inc:283:0
#33 0x000055a9568dd9ec (anonymous namespace)::AnalysisConsumer::runAnalysisOnTranslationUnit(clang::ASTContext&) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:529:0
#34 0x000055a9568ddc1e (anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(clang::ASTContext&) /home/hyx/mysrc/llvm-project/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:568:0
#35 0x000055a9574a47f8 clang::ParseAST(clang::Sema&, bool, bool) /home/hyx/mysrc/llvm-project/clang/lib/Parse/ParseAST.cpp:178:0
#36 0x000055a954ff8f37 clang::ASTFrontendAction::ExecuteAction() /home/hyx/mysrc/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1074:0
#37 0x000055a954ff8800 clang::FrontendAction::Execute() /home/hyx/mysrc/llvm-project/clang/lib/Frontend/FrontendAction.cpp:971:0
#38 0x000055a954f35ce4 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/hyx/mysrc/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:1030:0
#39 0x000055a9551924c9 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/hyx/mysrc/llvm-project/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:261:0
#40 0x000055a950dd60d8 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /home/hyx/mysrc/llvm-project/clang/tools/driver/cc1_main.cpp:246:0
#41 0x000055a950dca5c5 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) /home/hyx/mysrc/llvm-project/clang/tools/driver/driver.cpp:317:0
#42 0x000055a950dcac93 main /home/hyx/mysrc/llvm-project/clang/tools/driver/driver.cpp:388:0
#43 0x00007fe04d12ebf7 __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:344:0
#44 0x000055a950dc8d3a _start (/home/hyx/mysw/clang-12.x/bin/clang-14+0x303fd3a)
Segmentation fault (core dumped)
`
Because in the subsequent code when SymbolReaper runs isDead() it will execute the function getKind() and then it will crash, so I wanted to print it in advance on line 120 to see if there would be any problem. The command line crash message shows that there is a problem with getKind()

If I'm not using the CSA framework in the right way please tell me what to do, thank you very much

**Comment by haoNoQ** [comment]
Looks like you're dereferencing a null pointer produced by `getAsSymbol()`. Return values of constructors typically aren't symbols.

**Comment by hyxl1017** [comment]
> Looks like you're dereferencing a null pointer produced by `getAsSymbol()`. Return values of constructors typically aren't symbols.

I checked that it was indeed what you said. Is there any other way to get the symbol of a in decl “share_ptr<A>a=make_share<A>()” if there is no way to treat the value returned by the constructor as a symbol as you said?thank you very much

**Comment by haoNoQ** [comment]
Symbols are unknown numeric values. They can represent pointers. But they don't represent structures such as smart pointers. I believe you should be tracking _regions_ instead. Regions are segments of memory. You should also look into `CallEvent::getReturnValueUnderConstruction()` for memory regions that are targeted by constructors. Construct-expression's result type is a prvalue which doesn't necessarily carry a region but that doesn't mean the region doesn't exist.

**Comment by steakhal** [comment]
I guess, we can close this.

**Comment by hyxl1017** [comment]
thank you all
