### ISSUE TITLE
`misc-redundant-expression` should ignore redundant expressions in concepts

### ISSUE THREAD

**Issue by philnik777** [llvm/llvm-project#54114]
clang-tidy warns with `misc-redundant-expression` in
```
#include <concepts>

template <class I>
concept Iter = requires(I i) {
    { i - i } -> std::same_as<long>; // here
};
```
`i - i` is obviously a redundant expression, but it can make sense inside a concept.

**Comment by Izaron** [comment]
Why would one write a requirement in such a way? No offence =) I just want to know if there is a serious justification to prohibit the checker looking inside concepts.

**Comment by philnik777** [comment]
This came up specifically in https://github.com/llvm/llvm-project/blob/1bcc28b884ff4fbe2ecc011b8ea2b84e7987167b/libcxx/include/__iterator/iterator_traits.h#L202. Everything in concepts is purely syntactic, while this check looks for semantic redundant expressions. In the concept I just want to check that `operator-(T, T)` returns some specific type. I don't care that subtracting something from itself always returns the same value.

**Comment by Izaron** [comment]
Thanks! A possible fix here: https://reviews.llvm.org/D122078
