### ISSUE TITLE
LLVM-15 - LLVM ERROR: LICM requires MemorySSA (loop-mssa)

### ISSUE THREAD

**Issue by rabeidas** [llvm/llvm-project#54134]
Please find below a simple example to trigger the problem, followed by running commands and stack dump.

**test.c**
```
extern int A[1024];
extern int INIT;
extern int DIV;
extern int SUM;

void foo() {

  int s = INIT;

  for( int i = 4; i < 1024; i++ ) {
    int tmp = A[i - 3] * A[123] / DIV;
    A[i] = tmp;
    s += tmp;
  }

  SUM = s;
}
```

**$ clang-15 -emit-llvm -S -Os test.c -fno-vectorize
$ opt-15 -load-pass-plugin ./libCgrameKernels.so -passes='loop(loop-flatten),licm' -disable-output test.ll**
LLVM ERROR: LICM requires MemorySSA (loop-mssa)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: opt-15 -load-pass-plugin ./libCgrameKernels.so -passes=loop(loop-flatten),licm -disable-output test.ll
 #0 0x00007f981ffeebe1 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0xe61be1)
 #1 0x00007f981ffec93e llvm::sys::RunSignalHandlers() (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0xe5f93e)
 #2 0x00007f981ffef10b (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0xe6210b)
 #3 0x00007f981f16e3c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #4 0x00007f981ec6118b raise /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007f981ec40859 abort /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:81:7
 #6 0x00007f981ff2a297 (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0xd9d297)
 #7 0x00007f981ff2a0b6 (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0xd9d0b6)
 #8 0x00007f9820e18bfc llvm::LICMPass::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&) (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0x1c8bbfc)
 #9 0x00007f9822b92f4d (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0x3a05f4d)
#10 0x00007f9820e6359e llvm::FunctionToLoopPassAdaptor::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0x1cd659e)
#11 0x00007f9822b928bd (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0x3a058bd)
#12 0x00007f982015dfce llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0xfd0fce)
#13 0x00007f9821dacb0d (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0x2c1fb0d)
#14 0x00007f9820161ee1 llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0xfd4ee1)
#15 0x00007f9821dac92d (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0x2c1f92d)
#16 0x00007f982015cbee llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0xfcfbee)
#17 0x000055f386bc2cbc llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::StringRef>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool) (/usr/lib/llvm-15/bin/opt+0x24cbc)
#18 0x000055f386bd63ac main (/usr/lib/llvm-15/bin/opt+0x383ac)
#19 0x00007f981ec420b3 __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:342:3
#20 0x000055f386bbc43e _start (/usr/lib/llvm-15/bin/opt+0x1e43e)
Aborted (core dumped)

**Comment by nikic** [comment]
As the error message indicates, you need to use `loop-mssa(licm)` if you're using licm as part of a larger pipeline.

**Comment by rabeidas** [comment]
Thank you. I am actually new to LLVM and the commands used to work for LLVM-13, hence the reported issue.

**Comment by nikic** [comment]
Right, in LLVM 13 LICM still supported using AST instead of MSSA. This is no longer the case in newer versions.
