### ISSUE TITLE
Please cherry-pick ab49dce01f211fd80 into llvm-14

### ISSUE THREAD

**Issue by jmorse** [llvm/llvm-project#54130]
Hi,

Please could ab49dce01f211fd80 be cherry-picked into llvm-14. It's NFC, unremarkable, but moderately important to clean up a small pointer-ownership mess that I made around branching time. While it's technically not needed, our lives will be harder if any fixes have to be applied to this part of the compiler at a later date.

**Comment by jmorse** [comment]
(Put the wrong hash in the title, curses, now fixed)

**Comment by tstellar** [comment]
@dwblaikie What do you think about backporting this? https://github.com/llvm/llvm-project/commit/ab49dce01f211fd80f76f449035d771f5e2720b9

**Comment by dwblaikie** [comment]
@tstellar I don't have strong feelings - it seems harmless enough. I'm not sure if this code is more/less likely to need other patches backported to the release branch or later point releases.

LLVM gets these sort of refactorings all the time, so my gut instinct would be that unless this particular code is more likely than average to need backports, I don't see why this particular patch would be worth backporting more than all the other refactoring changes that are made regularly.

@Jmorse are there already other patches you expect to backport on top of this? Particular reason this is likely to be more backport-heavy than other areas of the project?

**Comment by jmorse** [comment]
> @jmorse are there already other patches you expect to backport on top of this? Particular reason this is likely to be more backport-heavy than other areas of the project?

No reason, it's just messy and required some follow-up commits that didn't get reviewed -- I figured it's better to have the known-to-be-correct version over the hacked-to-be-correct. If there's a nonzero risk / cost to backporting this at this stage, lets not do it. I'm not aware of any other patches in this area that'll need to be backported right now.

**Comment by tstellar** [comment]
@jmorse So do we need to backport the follow-up commits too?

**Comment by jmorse** [comment]
We don't; I pestered people into cherry picking those at the time, there would have been asan failures otherwise.

This patch was entirely about neatness, and a desire to not rely on the (correct and working, but unreviewed) fix immediately before branching. I sense this isn't a compelling reason to cherry pick so will close. There's zero functional impact on the release.
