### ISSUE TITLE
[MLIR] Attribute assemblyFormat doesn't handle `custom`

### ISSUE THREAD

**Issue by bzcheeseman** [llvm/llvm-project#54136]
I would like the following to work: 
```let assemblyFormat = "`<` custom<snip>($type) custom<snip>($bytes) `>`";``` 

but it fails with the following: 
```error: 'custom' not supported (yet)```

To reproduce, use the following Tablegen Attr def with a dialect of choice (most of the functions necessary won't exist but the TableGen generation should still fail):
```
def MyAttr : AttrDef<MyDialect, "MyAttr"> {
  let mnemonic = "my_attr";

  let parameters = (ins "unsigned":$type, "std::string":$bytes);
  let assemblyFormat = "`<` custom<DecodedEnum>($type) custom<PrintedBytes>($bytes) `>`";
}
```

**Comment by Mogball** [comment]
I'll work on this at some point soon (tm)

**Comment by zero9178** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/4767e267757fa56d40248b759d7b17ac1c6fb2ef
