### ISSUE TITLE
Cherry-pick JIT fixes for EPCIndirectionUtils, BuildingAJIT-Ch3 to LLVM 14.0.0

### ISSUE THREAD

**Issue by lhames** [llvm/llvm-project#54141]
`EPCIndirectionUtils::writeResolverBlock` was failing to set `ResolverBlockAddr` (broken in `962a2479b57`) which broke lazy compilation support via EPCIndirectionUtils. This was fixed in `34e539dcd78ab828210ecf7f7d2e9d2c986511b3`.

This bug should have broken Chapter 3 of the Bulding-A-JIT tutorial, but we were accidentally bypassing the `CODLayer` (and consequently bypassing the bug). This has been fixed in `1e16272ba793e5a6e7308898ecf6ef0dc99e2ad3`.

Could 34e539dcd78ab828210ecf7f7d2e9d2c986511b3 and 1e16272ba793e5a6e7308898ecf6ef0dc99e2ad3 please be cherry-picked to LLVM 14? Both are very low risk, being in example code and in new, little-used JIT APIs that are broken without these fixes.

**Comment by tstellar** [comment]
Merged: 4fde843cd5c0 6d5afef3a7e6
