### ISSUE TITLE
[Formatter] Recognize `if consteval`

### ISSUE THREAD

**Issue by JohelEGP** [llvm/llvm-project#54140]
No `.clang-format`.
Input and expected formatted result (because replacing `consteval` with `(true)` looks just like that):
```C++
void f() {
  if consteval {
    ok;
  }
}
```
Actual output:
```C++
void f() {
  if
    consteval { ok; }
}
```

**Comment by mkurdej** [comment]
Revision URI: https://reviews.llvm.org/D120806
