### ISSUE TITLE
'Invoke' llvm instruction does not function per documentation

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5414]
|  |  |
| --- | --- |
| Bugzilla Link | [5042](https://llvm.org/bz5042) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The invoke / unwind functionality does not work as per the documentation.  It is now my understanding that exception handling in C, C++ is implemented using other libraries.  Currently (in svn) when a unwind instruction is encountered, the program unwinds (Good), but the invoke does not handle it.  The following code will throw a segmentation fault on my system.

My system:
triple=powerpc-unknown-linux-gnu
llvm from svn 9/23/2009

Proposed resolution:
 * Change Documentation if this will not be supported without other libraries
 * Change llvm to adhear to the docs.  Which could be hard to do.

To Reproduce:

Run the following code through llvm-as then lli or llc.

//====---- Code Start -----========//
@.str = internal constant [6 x i8] c"Hello\00"		; <[6 x i8]*> [#uses=1]
@.strFunctionError = internal constant [36 x i8] c"Could not call function! Exiting...\00"		; <[36 x i8]*> [#uses=1]

define i32 @&#8203;main() nounwind {
entry:
	%0 = tail call i32 @&#8203;puts(i8* getelementptr ([6 x i8]* @.str, i32 0, i32 0)) nounwind		; <i32> [#uses=0]
	%a = invoke i32 @&#8203;functionToFail() to label %normal unwind label %exception

exception:
	tail call i32 @&#8203;puts(i8* getelementptr ([36 x i8]* @.strFunctionError, i32 0, i32 0)) nounwind
	ret i32 -1	
normal:
	%.fo = tail call i32 @&#8203;puts(i8* getelementptr ([6 x i8]* @.str, i32 0, i32 0)) nounwind	
	ret i32 0
}

define i32 @&#8203;functionToFail()
{
entry:
	unwind
	ret i32 0
}

declare i32 @&#8203;puts(i8*)
//====---- Code End -----========//

**Comment by gwelymernans** [comment]
The exception handling system changed dramatically since this bug, as has the documentation. If it's still not sufficient, please open a new bug with more up-to-date information.
