### ISSUE TITLE
check-all target runs much less regression tests if check-runtimes fails

### ISSUE THREAD

**Issue by DimitryAndric** [llvm/llvm-project#54154]
Now that releases via the `llvm/utils/release/test-release.sh` script are using `LLVM_ENABLE_RUNTIMES` for e.g. compiler-rt and libcxx, it turns out that the `check-all` target may run much less regression tests. This is most likely because `check-all` depends (via CMake's `add_dependencies()`) on `check-runtimes`, if runtimes are enabled. I.e., if `check-runtimes` results in any failure whatsoever, none of the other tests under `check-all` are even tried.

We might need to make `check-runtimes` failures not block the rest of `check-all` to run, or maybe splice all the tests from `check-runtimes` and `check-all` into one big bucket?

See also https://discourse.llvm.org/t/14-0-0-rc2-has-been-tagged/60621/3

**Comment by ldionne** [comment]
I'm looking at this, however I'm struggling to make a fix that actually works. I'll ping Petr Hosek for assistance.

**Comment by petrhosek** [comment]
I came up with a solution but I need a bit more time to clean it up.

**Comment by tstellar** [comment]
@petrhosek Any progress on a fix?  @ldionne if we don't get a fix in time, can we fix this at least for the release testers by reverting c8bb1777fff5d1ae28a2deac0d6677e081d4200f?

**Comment by tstellar** [comment]
> See https://reviews.llvm.org/D121258 for the revert on `release/14.x`.

I've merged this patch to the release/14.x branch.  We can switch it back to the new runtime builds for 14.0.1 when this is fixed.

**Comment by petrhosek** [comment]
https://reviews.llvm.org/D121276 is a candidate solution.

**Comment by DimitryAndric** [comment]
So it appears that due to reverts, this problem is still not fixed? How are the regression tests for the runtimes then guaranteed for the releases?

In any case for my own release builds, I will *disable* the runtimes for now, until this has been sorted. I think some people should take a very serious look at how the runtimes are built, and sort out all the various problems with them.
