### ISSUE TITLE
Incorrect behaviour with O2 compile when integer overflow

### ISSUE THREAD

**Issue by xuechiyaobai** [llvm/llvm-project#54169]
I complie C++ program with below code:
```
#include <iostream>

volatile int b = 0x7fffffff;
volatile int d = 0x0;

int main(int argc, const char * argv[]) {
    void* a = malloc(0x10);
    *(int*)a = d;
    int c = std::max(*(int*)a, b + 1);
    printf("%d\n", c);
    return 0;
}
```

If I complie with -O0, the output is "0"
when I compile with -O2, the output is "-2147483648", and I think it is incorrect behaviour

**Comment by LebedevRI** [comment]
`(int)0x7fffffff + 1` is UB.
https://godbolt.org/z/c1q8189a1
