### ISSUE TITLE
[mlir][rewrite] Need a new API for function match and rewrite 

### ISSUE THREAD

**Issue by Mogball** [llvm/llvm-project#54162]
We used to have an API for passing values between the `match` and `rewrite` of a pattern. The old API was awkward to use and was removed at some point. The vast majority of patterns are written as `matchAndRewrite`, but with PDLL hailing a new rewrite paradigm, it might be time to introduce a new API for separate `match` and `rewrite`.

In theory, every conformant `matchAndRewrite` pattern can be separated into `match` and `rewrite`. Maybe it should look like this:

```
struct MyPattern : FunctionalOpRewritePattern<MyPattern, FooOp> {
  auto match(FooOp op) const {
    // ...
    return make_match_result(/*bar=*/1, "baz");
  }

  void rewrite(int bar, StringRef baz, FooOp op, PatternRewriter &rewriter) const {
  }
}
```

**Comment by River707** [comment]
I'd really want to see some strong justification here. I have strong hesitation for reviving this in the C++ API.
