### ISSUE TITLE
Backport "[LLD] [COFF] Order .debug_* sections at the end, to avoid leaving gaps if stripped" to 14.x

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#54175]
We could backport 4c3b74b7f5d6192d1731c88f1aeb396bc51d4949, "[LLD] [COFF] Order .debug_* sections at the end, to avoid leaving gaps if stripped", to 14.x. It's not a fix for a critical bug, but fixing it in this release now instead of in 6 months would still be nice, as the fix is rather safe IMO (WDYT @rnk?).

**Comment by rnk** [comment]
I think it's reasonable to backport, .debug_ sections were already sorted to the end, they are just now *more* towards the end of the binary after other discardable sections.

**Comment by tstellar** [comment]
Merged: 65d53279b1fd 43b4544023b7
