### ISSUE TITLE
C: _Static_assert doesn't work with NULL

### ISSUE THREAD

**Issue by dfarley1** [llvm/llvm-project#54187]
[Demo here](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,selection:(endColumn:2,endLineNumber:9,positionColumn:2,positionLineNumber:9,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:'%23include+%3Cstddef.h%3E%0A%0Aint+main()%0A%7B%0A++++_Static_assert(NULL+%3D%3D+NULL,+%22%22)%3B%0A++++_Static_assert(NULL+%3D%3D+0,+%22%22)%3B%0A++++_Static_assert(((void*)0)+%3D%3D+0,+%22%22)%3B%0A++++_Static_assert(0+%3D%3D+0,+%22%22)%3B%0A%7D'),l:'5',n:'0',o:'C+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:cclang1201,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,libs:!(),options:'-std%3Dc11+-Wall+-Wextra+-Werror',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x86-64+gcc+11.2+(C,+Editor+%231,+Compiler+%231)',t:'0')),k:50,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compiler:1,editor:1,fontScale:14,fontUsePx:'0',tree:'1',wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+clang+12.0.1+(Compiler+%231)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:50,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

```
#include <stddef.h>

int main()
{
    _Static_assert(NULL == NULL, "");
    _Static_assert(NULL == 0, "");
    _Static_assert(((void*)0) == 0, "");
    _Static_assert(0 == 0, "");
}
```
Results in the following compiler error:
```
<source>:5:20: error: static_assert expression is not an integral constant expression
    _Static_assert(NULL == NULL, "");
                   ^~~~~~~~~~~~
/opt/compiler-explorer/clang-12.0.1/lib/clang/12.0.1/include/stddef.h:89:16: note: expanded from macro 'NULL'
#  define NULL ((void*)0)
               ^
<source>:6:20: error: static_assert expression is not an integral constant expression
    _Static_assert(NULL == 0, "");
                   ^~~~~~~~~
/opt/compiler-explorer/clang-12.0.1/lib/clang/12.0.1/include/stddef.h:89:16: note: expanded from macro 'NULL'
#  define NULL ((void*)0)
               ^
<source>:7:20: error: static_assert expression is not an integral constant expression
    _Static_assert(((void*)0) == 0, "");
                   ^~~~~~~~~~~~~~~
3 errors generated.
```

Clang doesn't like the `void*` cast for some reason. None of the recent (or trunk) versions work but GCC is totally fine with it.

**Comment by efriedma-quic** [comment]
gcc -pedantic gives exactly the same message.

Without -pedantic, gcc uses some extended rules... what those rules are, I have no idea.  We're not going to try to guess gcc's undocumented rules, so I'm closing this.  If they do decide to document their rules at some point, we can reconsider.
