### ISSUE TITLE
Backport "Add cmake to source release tarballs" to 14.x

### ISSUE THREAD

**Issue by mati865** [llvm/llvm-project#54183]
Could https://github.com/llvm/llvm-project/commit/32a0482a65b86cf0d84ea7e784cca9852df5c67c be backported to 14.x ?
I think it's rather critical because without it trying to build various LLVM projects from tarballs fails with errors like:
```
CMake Error at D:/Projekty/msys2/MINGW-packages/mingw-w64-clang/src/compiler-rt/CMakeLists.txt:31 (include):
  include could not find requested file:

    SetPlatformToolchainTools


CMake Error at D:/Projekty/msys2/MINGW-packages/mingw-w64-clang/src/compiler-rt/cmake/base-config-ix.cmake:9 (include):
  include could not find requested file:

    ExtendPath
```

First noticed it with LLVM 14 RC1 but seeing the fix was in the works I though it would be fixed with RC2. It's not the case though and IIUC backporting that commit should fix building from tarballs for the next RC/release.

**Comment by h-vetinari** [comment]
It doesn't cherry-pick cleanly, but there's a backport waiting in https://github.com/llvmbot/llvm-project/pull/110, see also #53281

**Comment by mati865** [comment]
Sorry couldn't find it due to different error order. Should I close this one?

**Comment by h-vetinari** [comment]
Backport happened (thanks!), so this can be closed. :)

**Comment by mati865** [comment]
Thank you!

**Comment by tstellar** [comment]
Merged: 1e3d5ccab6b616baa91448462951b43f28bd5601

**Comment by rubyFeedback** [comment]
Just ran into this issue. Could a new minor 14.x release be made with the fix? Somehow the more recent cmake versions seemed to have issues, whereas I think I remember having compiled llvm just fine with an older cmake version.

**Comment by seppeon** [comment]
> Just ran into this issue. Could a new minor 14.x release be made with the fix? Somehow the more recent cmake versions seemed to have issues, whereas I think I remember having compiled llvm just fine with an older cmake version.
> 
> Edit: the error was
> 
> ```
> -- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG - Failed
> -- Looking for include file sys/inotify.h
> -- Looking for include file sys/inotify.h - found
> -- Not building amdgpu-arch: hsa-runtime64 not found
> CMake Error at tools/clang/cmake/modules/CMakeLists.txt:1 (include):
>   include could not find requested file:
> 
>     ExtendPath
> 
> 
> CMake Error at tools/clang/cmake/modules/CMakeLists.txt:3 (include):
>   include could not find requested file:
> 
>     FindPrefixFromConfig
> 
> CMake Error at tools/clang/cmake/modules/CMakeLists.txt:42 (find_prefix_from_config):
>   Unknown CMake command "find_prefix_from_config".
> ```
We have the same issue when trying to build [compiler-rt-15.0.2.src.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.2/compiler-rt-15.0.2.src.tar.xz)
