### ISSUE TITLE
Always invoke lld with the `-lSystem` argument in MachO tests

### ISSUE THREAD

**Issue by int3** [llvm/llvm-project#54184]
It appears that the recent versions of ld64 require `-lSystem` to always be linked into userland binaries and dylibs. (Previously, it only had this requirement for binaries, and that's the current behavior that LLD implements.) It would be nice to have behavior parity here, not least because it makes it easier to swap out ld64 for LLD in our test suite to see if we are implementing the same behaviors. Unfortunately, simply updating the `%lld` substitution to include `-lSystem` results in quite a few errors.

I will be putting up a few fixes that get us closer to the goal of having `-lSystem` in our `%lld` substitution, but I'm not sure when I'll get around to cleaning all the failing tests up -- please feel free to grab this task if you're interested.

**Comment by keith** [comment]
I don't think you wanted the auto-close here

**Comment by keith** [comment]
https://reviews.llvm.org/D135193
