### ISSUE TITLE
UndefinedBehaviorSanitizer:DEADLYSIGNAL with updated SLPVectorizer

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#54198]
llvm commit: 738042711b

Reproduce with:
build-all-builtins/bin/clang -finline-hint-functions -std=c99 -fsanitize=undefined -O2 'vla_sum_1.c' -o 'vla_sum_1.out'
./vla_sum_1.out

This results in:

UndefinedBehaviorSanitizer:DEADLYSIGNAL
==160192==ERROR: UndefinedBehaviorSanitizer: BUS on unknown address (pc 0x00000042b6c9 bp 0x7fff7d630950 sp 0x1000100010001 T160192)
==160192==The signal is caused by a READ memory access.
==160192==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
    #0 0x42b6c9  (/repo/uabelho/master-github/llvm/vla_sum_1.out+0x42b6c9)
    #1 0x42b857  (/repo/uabelho/master-github/llvm/vla_sum_1.out+0x42b857)
    #2 0x7fa2c69b4554  (/lib64/libc.so.6+0x22554) (BuildId: e6847a931dd483773bab779dd3985b17c11caab2)
    #3 0x402cb4  (/repo/uabelho/master-github/llvm/vla_sum_1.out+0x402cb4)

UndefinedBehaviorSanitizer can not provide additional info.
SUMMARY: UndefinedBehaviorSanitizer: BUS (/repo/uabelho/master-github/llvm/vla_sum_1.out+0x42b6c9) 
==160192==ABORTING

This starts happening with 7380427:
Reapply "[SLP] Schedule only sub-graph of vectorizable instructions""
https://reviews.llvm.org/D118538

[vla_sum_1.c.gz](https://github.com/llvm/llvm-project/files/8185806/vla_sum_1.c.gz)

**Comment by mikaelholmen** [comment]
The problem went away again with the revert of 738042711 in deae979a2c:
    Revert "Reapply "[SLP] Schedule only sub-graph of vectorizable instructions"""
    
    This reverts commit 738042711bc08cde9135873200b1d088e6cf11c3. A second, apparently separate, issue has been reported on the original review.

But I suppose there will be new attempts to submit it.

**Comment by mikaelholmen** [comment]
I've verified that this problem disappeared with 6253b77da9 (even with 738042711 reapplied):
 [SLP] Respect control dependence within a block during scheduling

So perhaps we should close this issue now.

**Comment by fhahn** [comment]
> So perhaps we should close this issue now.

If it doesn't reproduce on current main, I *think* it would be good to close it. Or perhaps wait a couple of days in case there are any other related reverts/fixes?

**Comment by mikaelholmen** [comment]
Closing since it's fixed with 6253b77da9f.
