### ISSUE TITLE
[scev] Loop unrolling blocked by finite loop handling of nonstrict inequalities

### ISSUE THREAD

**Issue by mtrofin** [llvm/llvm-project#54191]
[scev-test.zip](https://github.com/llvm/llvm-project/files/8182815/scev-test.zip)

See https://reviews.llvm.org/D118090

To repro, unzip the attachment, then:

```
opt -mtriple=x86_64-linux -mattr=+64bit,+sse3,+ssse3 -passes="require<scalar-evolution>,loop-unroll" /tmp/good-test.ll -scalar-evolution-finite-loop=0 -S -o /tmp/no.ll 
opt -mtriple=x86_64-linux -mattr=+64bit,+sse3,+ssse3 -passes="require<scalar-evolution>,loop-unroll" /tmp/good-test.ll -scalar-evolution-finite-loop=1 -S -o /tmp/yes.ll 

diff /tmp/no.ll /tmp/yes.ll
```

This is causing ~20% regression in an eigen benchmark. The .ll is extracted from there - it could have probably be further reduced, but I wasn't successful.

The interesting loop is the one at block `863`. See `SCEVExpander::isHighCostExpansion`

**Comment by nikic** [comment]
Reduced:
```
; RUN: opt -S -passes='print<scalar-evolution>' < %s
define void @test(i64 %n) mustprogress {
entry:
  %guard = icmp sgt i64 %n, 1
  br i1 %guard, label %loop, label %exit
  
loop:
  %iv = phi i64 [ 2, %entry ], [ %iv.next, %loop ]
  %iv.next = add nuw nsw i64 %iv, 2
  %cmp = icmp sle i64 %iv.next, %n
  br i1 %cmp, label %loop, label %exit
  
exit:
  ret void
} 
```

This gives:

```
; -scalar-evolution-finite-loop=0
Loop %loop: backedge-taken count is ((-2 + %n) /u 2)
; -scalar-evolution-finite-loop=1
Loop %loop: backedge-taken count is ((-3 + (4 smax (1 + %n)<nsw>))<nsw> /u 2)
```

In the latter case, we should be folding `((-3 + (4 smax (1 + %n)<nsw>))<nsw> /u 2)` to either `(1 smax (-2 + %n)) /u 2` or `(-2 + (3 smax %n)) /u 2`, though the precondition wouldn't be quite strong enough to fold away the smax in that case either.
