### ISSUE TITLE
Bug in Libomptarget when state initialization comes from outside the translation unit

### ISSUE THREAD

**Issue by jhuber6** [llvm/llvm-project#54208]
Libomptarget uses some shared variables to track certain internal stated in the runtime. This causes problems when we have code that contains no OpenMP kernels. These variables are normally initialized upon kernel entry, but if there are no kernels we will see no initialization. Currently we load the runtime into each source file when not running in LTO mode, so these variables will be erroneously considered undefined or dead and removed, causing miscompiles.

**Comment by EugeneZelenko** [comment]
For backport.

**Comment by tstellar** [comment]
@jdoerfert What do you think about backporting this? https://github.com/llvm/llvm-project/commit/e2dcc2218c64ae1b6a774f52bd3aec87a6902b58

**Comment by jdoerfert** [comment]
I'm torn. I initially thought we should but I'm not so sure anymore. I fear the performance impact on a lot of codes is not worth it for the few this might help (to actually run). For the next version we'll have to have a proper solution. Let's keep 14 as is.
