### ISSUE TITLE
Please cherry-pick 0e96d95d13d9f into llvm-14

### ISSUE THREAD

**Issue by jmorse** [llvm/llvm-project#54206]
Hi,

0e96d95d13d9f fixes #54190, a debug-info crash caused by direct reads from registers in llvm-ir. All it really needs to replicate is:

    register long a asm("rsp");

or similar, where "a" is assigned to something. This'll certainly causes crashes, and should be in llvm-14, please.

**Comment by jmorse** [comment]
Subscribing @OCHyams who reviewed, as Tom mentions here [0], is this alright to backport?

[0] https://discourse.llvm.org/t/llvm-14-0-0-release-update/60650

**Comment by ldionne** [comment]
Is this still relevant? It seems like we can probably close at this point.

**Comment by jmorse** [comment]
Makes sense to me.
