### ISSUE TITLE
IR Outliner crashes when external phi node is shared by multiple outlined regions.

### ISSUE THREAD

**Issue by AndrewLitteken** [llvm/llvm-project#54209]
Reproduced: https://godbolt.org/z/j9sK47KM7

The IR Outliner is supposed to extract the outputs contained in an external phi node and place them into a phi node contained within the outlined function.  However, when the output values of two outlined functions with two different output sets are contained within the same phi node, they are counted as the same exit path when first analyzed.  In reality, these create two different phi nodes, creating an inconsistency, resulting in a mismatch in the expected number of output paths and a crash.

Patch developed for this, and incoming soon.

**Comment by AndrewLitteken** [comment]
cc @ornata

**Comment by ornata** [comment]
Was there a patch for this? Can we close this?

**Comment by AndrewLitteken** [comment]
Yes, can be closed: https://reviews.llvm.org/D121313
