### ISSUE TITLE
Phi nodes missing predecessor entries when outlined code does not contain branch

### ISSUE THREAD

**Issue by AndrewLitteken** [llvm/llvm-project#54212]
Reproduced: https://godbolt.org/z/roznP99P3

When outlining a phi node, if the the incoming branch is the parent block and the branch from that block is not outlined, we create broken code.  The fix is to recognize when that branch is not contained, and ignore the region.

Patch coming soon.

cc @ornata

**Comment by xgupta** [comment]
This is fixed on trunk -https://godbolt.org/z/hrYh9xEdv.
