### ISSUE TITLE
IR Outliner hits assertion with two identical external phi nodes

### ISSUE THREAD

**Issue by AndrewLitteken** [llvm/llvm-project#54210]
https://godbolt.org/z/63r5hzKsT

When there are two external phi nodes for two different outlined regions, when compressing the created phi nodes between the two regions, the matching for the second phi node in the second region matches the first phi node created for the first region rather than the second phi node created for the first region.  This adds an extra output path where there should not be one.

The fix is the ignore phi nodes that have already been matched for each region. Patch incoming soon.

**Comment by AndrewLitteken** [comment]
@ornata

**Comment by xgupta** [comment]
seems it is fixed on trunk, no assertion triggering - https://godbolt.org/z/cK5G7q6cW.
