### ISSUE TITLE
OpenMP custom state machine optimization fails with a single thread

### ISSUE THREAD

**Issue by jhuber6** [llvm/llvm-project#54214]
The custom state machine had a check for surplus threads that filtered the main thread if the kernel was executed by a single warp only. This prevented us from executing the region if only a single thread was present. Normally a parallel region with one thread had its state machine removed, but this occurs when there is no parallelism in an external call.

**Comment by EugeneZelenko** [comment]
For backport.

**Comment by tstellar** [comment]
Merged: 65d53279b1fd 0205cc086e50
