### ISSUE TITLE
Missed optimization in arm64 neon zip operation

### ISSUE THREAD

**Issue by uncleasm** [llvm/llvm-project#54226]
As in https://godbolt.org/z/xoz5sbTes
the produced code seems slightly unoptimal, as the task should be achievable with a single instruction 
`zip1 v0.16b, v0.16b, v1.16b`

The problem of course is, that the 16-byte register, which shadows the 8-byte register has the top portion undefined -- however the instruction does not actually use those bytes. The various methods proposed below try to workaround the issue, convincing the backend to produce the optimal code, but as can be seen, they fail. One possibility would be to introduce a new intrinsic for the purpose.

```
#include "arm_neon.h"


using u16 = uint8_t  __attribute__((vector_size(16)));
using u8 = uint8_t  __attribute__((vector_size(8)));
uint8x16_t zip(uint8x8_t a, uint8x8_t b) {
    auto A = vzip_u8(a,b);
    return vcombine_u8(A.val[0], A.val[1]);
}
        zip1    v2.8b, v0.8b, v1.8b
        zip2    v0.8b, v0.8b, v1.8b
        mov     v2.d[1], v0.d[0]
        mov     v0.16b, v2.16b

uint8x16_t zip2(uint8x8_t a, uint8x8_t b) {
    auto A = vcombine_u8(a,vdup_n_u8(0));
    auto B = vcombine_u8(b,vdup_n_u8(0));
    return vzip1q_u8(A,B);
}
        zip2    v2.8b, v0.8b, v1.8b
        zip1    v0.8b, v0.8b, v1.8b
        mov     v0.d[1], v2.d[0]

u16 zip3(u8 a, u8 b) {
    return u16{
        a[0],b[0],
        a[1],b[1],
        a[2],b[2],
        a[3],b[3],
        a[4],b[4],
        a[5],b[5],
        a[6],b[6],
        a[7],b[7]
    };
}
        zip2    v2.8b, v0.8b, v1.8b
        zip1    v0.8b, v0.8b, v1.8b
        mov     v0.d[1], v2.d[0]
```

**Comment by davemgreen** [comment]
We can fix this - we just need to concat the zip's together. I'll try to put up a patch
