### ISSUE TITLE
Please backport 5244ef0faf55954 ([libcxxabi] [test] Depend on unwind only if available) to 14.x

### ISSUE THREAD

**Issue by mgorny** [llvm/llvm-project#54230]
This seems to be the last piece needed to use runtimes build in 14.x. Not critical but should be trivial enough:

> [libcxxabi] [test] Depend on unwind only if available
> When building libcxxabi via LLVM_ENABLE_RUNTIMES=libcxxabi the CMake
invocation fails because of missing "unwind" target.  However,
if the extraneous dependency is removed, the library builds just fine
against installed libunwind and tests work fine.  To fix this,
add the dependency only if the target actually exists.
>
> Differential Revision: https://reviews.llvm.org/D119538

https://github.com/llvm/llvm-project/commit/5244ef0faf5595495c1adedfa16c346d35caebdf

**Comment by tstellar** [comment]
@ldionne What do you think about backporting this?https://github.com/llvm/llvm-project/commit/5244ef0faf5595495c1adedfa16c346d35caebdf

**Comment by tstellar** [comment]
I've reviewed the patch and it looks safe to me, so I'm going to backport it.

**Comment by tstellar** [comment]
Merged: e879b2bf82ef2d096d2c0e5147ebac541a7b8828
