### ISSUE TITLE
Please backport 2c5c243bb51 ([llvm] [bindings/OCaml] Remove unused dep on ounit2) to 14.x

### ISSUE THREAD

**Issue by mgorny** [llvm/llvm-project#54231]
Again, not critical but makes it possible to build 14.x without ounit2 dep:

> [llvm] [bindings/OCaml] Remove unused dep on ounit2
> Remove the dependency on ounit2 and the relevant lit code.  It seems
that ounit2 is not used at all and all OCaml binding tests pass without
it installed.
> 
> Thanks for Shiwei Weng and Josh Berdine for bringing this to
my attention.
> 
> Differential Revision: https://reviews.llvm.org/D119884

https://github.com/llvm/llvm-project/commit/2c5c243bb5152de35c41f5880271451fce6165d0

**Comment by tstellar** [comment]
Merged: 6a713120502a
