### ISSUE TITLE
[MLIR] `OpAsmParser::parseRegion` has redundant argLocations array?

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#54237]
The parseRegion signature looks like this:

```
 virtual ParseResult parseRegion(Region &region,
                                  ArrayRef<OperandType> arguments = {},
                                  ArrayRef<Type> argTypes = {},
                                  ArrayRef<Location> argLocations = {},
                                  bool enableNameShadowing = false)
```

However, `OperandType` in the arguments list already carries a SMLoc for the operand location. I think we can drop the `argLocations` array.  Is there any obvious problem with doing that?

-Chris

**Comment by River707** [comment]
No, I think that was just oversight. We should be able to drop the extra param.

**Comment by lattner** [comment]
K I'll take care of it when I get a chance, I'm pretty sure this was my oversight.

**Comment by lattner** [comment]
Oh I see.  This actually is needed for when /actual user source locators/ are used :-). For example, it enables this testcase to work:

```
func @argLocs(%x: i32, %y: i64 loc("hotdog")) {
  return
}
```

User locations must be tracked with `Location` records, the SMLoc in `OperandType` isn't enough.  This is "behaves correctly".

**Comment by River707** [comment]
Nice, I suppose we can just have a simplified overload that uses the locations from the OperandType of the operands?

**Comment by lattner** [comment]
I think that moving the state of the world forward here would be to move the `Location` into the `OperandInfo`.  That would eliminate the parallel array and the extra arguments to all the functions.  We'd want to make it an `Optional<Location>` though because Location cannot be default constructed.
