### ISSUE TITLE
[mlir-opt] error: custom op 'arith.constant' is unknown

### ISSUE THREAD

**Issue by CONGCONGLEEE** [llvm/llvm-project#54243]
when using the command "mlir-opt --convert-affine-for-to-gpu " , it occurs
`error: custom op 'arith.constant' is unknown`
the "arith" Dialect belongs to MLIR, why the command can't identify 'arith.constant' op?

**Comment by joker-eph** [comment]
Can you indicate which version of mlir-opt you're using? The arith dialect is a relatively recent refactoring.

**Comment by CONGCONGLEEE** [comment]
> @llvm/issue-subscribers-mlir

The web link has problem。

**Comment by CONGCONGLEEE** [comment]
> Can you indicate which version of mlir-opt you're using? The arith dialect is a relatively recent refactoring.

The LLVM version is 13.0.0.What can I do to make it?

**Comment by CONGCONGLEEE** [comment]
> Can you indicate which version of mlir-opt you're using? The arith dialect is a relatively recent refactoring.

The LLVM version is 13.0.0.What can I do to make it?

**Comment by CONGCONGLEEE** [comment]
> @llvm/issue-subscribers-mlir
The web link has problem。

**Comment by joker-eph** [comment]
13.0.0 didn't have the arithmetic dialect I think, you can use `std.constant` instead.
Otherwise just build it at HEAD: https://mlir.llvm.org/getting_started/

**Comment by CONGCONGLEEE** [comment]
> 13.0.0 didn't have the arithmetic dialect I think, you can use `std.constant` instead. Otherwise just build it at HEAD: https://mlir.llvm.org/getting_started/

Thank you! The `std.constant` works. And I have another question, when using `memref.alloc` op, the same error occurs. Is there a replaceable op?

**Comment by joker-eph** [comment]
`std.alloc` maybe? The `std` dialect has been removed and broken apart in multiple smaller dialects (arith, memref, func, ...)

**Comment by CONGCONGLEEE** [comment]
> `std.alloc` maybe? The `std` dialect has been removed and broken apart in multiple smaller dialects (arith, memref, func, ...)

It works. Thanks a lot!
