### ISSUE TITLE
clang-format doesn't handle template variables and operators correctly

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#54257]
Given
```cpp
template <class T>
inline constexpr bool signed_integral = std::is_integral_v<T> && std::is_signed_v<T>;
```
clang-format will stylise as
```cpp
template <class T>
inline constexpr bool signed_integral =
    std::is_integral_v<T>&& std::is_signed_v<T>;
```
when it should be stylised as
```cpp
template <class T>
inline constexpr bool signed_integral =
    std::is_integral_v<T> && std::is_signed_v<T>;
//                       ^
```

I'm unable to provide system details or clang-format details at present, but my estimate is that this clang-format build is at most a fortnight old.

**Comment by mkurdej** [comment]
Reproduced with LLVM style (pointer alignment: right):
```
// OK:
bool signed_integral = std::is_integral_v<int> && std::is_signed_v<int>;

// BAD:
template <class T>
bool signed_integral = std::is_integral_v<int> &&std::is_signed_v<int>;
```

**Comment by mkurdej** [comment]
Revision URI: https://reviews.llvm.org/D121456

**Comment by mkurdej** [comment]
Reopening as the patch provoked #54374.

**Comment by cjdb** [comment]
This seems to be happening again close to ToT.

**Comment by cjdb** [comment]
Reopening with my [.clang-format](https://gist.github.com/cjdb/fdb83e0f6e672d6fa63151cafbb6633e) attached.

**Comment by cjdb** [comment]
I also think this might be exclusive to `noexcept`-specifiers now, e.g. `noexcept(is_nothrow_copy_constructible_v<T1> and is_nothrow_copy_constructible_v<T2>)` becomes `noexcept(is_nothrow_copy_constructible_v<T1>and is_nothrow_copy_constructible_v<T2>)`.

**Comment by rymiel** [comment]
That would be a duplicate of  #44543, then

**Comment by cjdb** [comment]
Closing, since this is a duplicate.
