### ISSUE TITLE
Clang-format: Macros which include braces

### ISSUE THREAD

**Issue by fulcrumEFX** [llvm/llvm-project#54264]
Hey,
I have created a .clang-format file to format my code. I noticed a problem that the format of macros, e.g. #defines gets garbled by clang-format when using braces in the define, for example:

`#define FOO_BAR {foo, bar}`
clang format changes it to:

`#define FOO_BAR \`
 ` { foo, bar }`
How can I tell clang format to not move that to a new line? If I have something like

`#define FOO_BAR (foo, bar)`
clang-format does it correctly and aligns it according to my settings. I went through the options on https://clang.llvm.org/docs/ClangFormatStyleOptions.html but none of the options where an obvious solution/cause of the problem for me.

Any help or hints are greatly appreciated.

For reference, here is my .clang-format file:

---
BasedOnStyle: LLVM
AlignAfterOpenBracket: Align
AlignConsecutiveAssignments: 'false'
AlignConsecutiveDeclarations: 'false'
AlignConsecutiveMacros: 'Consecutive'
AlignEscapedNewlines: Left
AlignOperands: 'true'
AlignTrailingComments: 'true'
AllowAllArgumentsOnNextLine: 'false'
AllowAllParametersOfDeclarationOnNextLine: 'false'
AllowShortBlocksOnASingleLine: 'Never'
AllowShortCaseLabelsOnASingleLine: 'false'
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: Never
AllowShortLoopsOnASingleLine: 'false'
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: 'false'
AlwaysBreakTemplateDeclarations: MultiLine
BinPackArguments: 'true'
BinPackParameters: 'true'
BreakBeforeBinaryOperators: None
BreakBeforeBraces: Attach
BreakBeforeTernaryOperators: 'true'
ColumnLimit: '120'
IndentPPDirectives: AfterHash
IndentWidth: '2'
Language: Cpp
PointerAlignment: Right
ReflowComments: 'true'
SpaceAfterCStyleCast: 'false'
SpaceBeforeAssignmentOperators: 'true'
SpaceBeforeParens: ControlStatements
SpacesInCStyleCastParentheses: 'false'
TabWidth: '2'
UseTab: Never
SortIncludes: false
...

**Comment by artizirk** [comment]
I asked in #llvm IRC channel about the same thing few minutes ago and @LebedevRI said that it looks like a bug.

A minimal testcase input file
```c
#define THING { 0, 1, 2 }

#define THANG {0}

#define OTHER 0
```

Formated with `clang-format --style=LLVM t.c`

Outputs:
```c
#define THING                                                                  \
  { 0, 1, 2 }

#define THANG                                                                  \
  { 0 }

#define OTHER 0
```

I'm running clang-format version 13.0.1

**Comment by artizirk** [comment]
This bug seems to be same as https://github.com/llvm/llvm-project/issues/53180 and might be related to https://github.com/llvm/llvm-project/issues/49164

**Comment by fulcrumEFX** [comment]
you are correct, I did not find #53180 during my search, sorry.
