### ISSUE TITLE
clang-format: Setting to control C++ attributes

### ISSUE THREAD

**Issue by martingalvan-nordic** [llvm/llvm-project#54265]
See https://stackoverflow.com/questions/45740466/clang-format-setting-to-control-c-attributes

If we have e.g.

```
template <typename TChar>
[[gnu::always_inline]]
static ptr<TChar> within_limit(ptr<TChar> first, ptr<TChar> last);

template <typename TChar, typename FApply, typename... FApplyRest>
[[gnu::always_inline]]
static ptr<TChar> overflow(ptr<TChar> first, ptr<TChar> last, const FApply& apply, const FApplyRest&... apply_rest);
```

No matter how we tweak clang-format, the output is always something like this:

```
[[gnu::always_inline]] static ptr<TChar> within_limit(ptr<TChar> first, ptr<TChar> last);

[[gnu::always_inline]] static ptr<TChar>
overflow(ptr<TChar> first, ptr<TChar> last, const FApply& apply, const FApplyRest&... apply_rest);
```

There should be a way to configure clang-format not to move the attributes like that, as it complicates readability.

**Comment by martingalvan-nordic** [comment]
@EugeneZelenko this is related to clang-format. Should it be tagged as clang-tidy?

**Comment by EugeneZelenko** [comment]
@martingalvan-nordic: I'm sorry for my mistake.

**Comment by mydeveloperday** [comment]
I've looked into this once before with some sort of naive  BreakAfterAttributes, but this then did strange things to 

```c
[[nodiscard]] bool foo();
```

which maybe I don't want as

```c
[[nodiscard]] 
bool foo();
```

It would need some sort of subtle control.

**Comment by martingalvan-nordic** [comment]
Why wouldn't you want

```
[[nodiscard]] 
bool foo();
```

in this case? The idea is precisely that the attributes are on their own line, so that they're not interfering with the function signature.

**Comment by mydeveloperday** [comment]
I guess I mean you might want different behaviour for declaration and definition (like BreakReturnType)

but also you might want to allow "ShortFunctions" where you don't break.

that what I mean by my previous implementation being a little naive, it likely needs a more considered approach as to the options

**Comment by martingalvan-nordic** [comment]
AFAIK attributes only belong in the function declaration, not its defnition. But I might be wrong.

The idea behind this isn't that function declarations end up being too long, but that the attributes belong to a separate category of interest than the function signature. Same thing happens with e.g. template machinery, where you'll often want

```
template <typename T1, typename T2>
void f(T1 t1, T2 t2);
```

instead of

`template <typename T1, typename T2> void f(T1 t1, T2 t2);`

It's not about line lenght, but about separating different categories of information. For example, to me attributes are useless noise, so I'd prefer to move them out of the way when I'm reading a function signature. Conversely, template information is important enough that I want it to be visually separated from the rest of the signature.

In any case, just having an option for disabling any automatic placement of attributes would be a huge improvement IMHO. Let the users arrange them as they wish.

**Comment by AaronBallman** [comment]
> AFAIK attributes only belong in the function declaration, not its defnition. But I might be wrong.

It depends on the syntax of the attribute and the particular attribute in question. For C++-style attributes, almost all of them can be written on the definition (and frequently are). For GNU-style attributes, that's a Clang extension.

> Let the users arrange them as they wish.

In general, that's hard. e.g., these are equivalent and I don't think clang-format should have a formatting option to decide which style to use:
```
[[attr]] void func();
void func [[attr]] ();

[[attr]] int a, b;
int a [[attr]], b [[attr]];
```
However, for things like "on their own line" vs "squished together as tightly as possible", I think that's much more reasonable for formatting options.

**Comment by martingalvan-nordic** [comment]
> > Let the users arrange them as they wish.
> 
> In general, that's hard. e.g., these are equivalent and I don't think clang-format should have a formatting option to decide which style to use:

That's not what I meant. What I meant is, have an option for clang-format not to touch attributes at all. That way, if I want to place them on their own line, or on the same line, or a mix of both, I can do so and clang-format won't interfere.

**Comment by AaronBallman** [comment]
> > > Let the users arrange them as they wish.
> > 
> > 
> > In general, that's hard. e.g., these are equivalent and I don't think clang-format should have a formatting option to decide which style to use:
> 
> That's not what I meant. What I meant is, have an option for clang-format not to touch attributes at all. That way, if I want to place them on their own line, or on the same line, or a mix of both, I can do so and clang-format won't interfere.

Ah, thank you for clarifying! That also sounds sensible to me.

**Comment by mydeveloperday** [comment]
There seems to be with this sudden request for clang-format to NOT do things and I feel that's quite hard to do in isolation when clang-format is modifying the things around it. but feel free to submit a patch.

**Comment by martingalvan-nordic** [comment]
> There seems to be with this sudden request for clang-format to NOT do things and I feel that's quite hard to do in isolation when clang-format is modifying the things around it. but feel free to submit a patch.

clang-format seems to have at least some awareness of attributes, as indicated in the StackOverflow link I posted, so maybe they can be treated as an exception to whatever rule applies there. Unfortunately I don't have the time to fix this myself, sorry.

**Comment by AaronBallman** [comment]
+1 to the request to please support attributes as first class features of clang-format. clang-format over functions is basically a two-step process for me when attributes are involved: format the function, then go manually fix what clang-format did so the attribute isn't on the same line as the rest of the declaration.

I don't worry too much when the attribute is short and the function is short, as in: `[[attr]] void f() {}` but it becomes much more frustrating with `[[clang::annotate("test", 1, 2, 3, "this is also a test")]] int i = 12;` where the attribute is overwhelming the rest of the declaration, but it all still fits on a single line.

FWIW, I'd also love it if the same would apply to macros that expand to attributes, e.g.,
```
#define AWESOME(...) [[clang::annotate(__VA_ARGS__)]]
AWESOME("test", 1, 2, 3, "this is also a test") int i = 12;
```
but if that turns out to be hard/impossible, I'd be happy if at least the usual attribute syntaxes were covered.

**Comment by rymiel** [comment]
> It would need some sort of subtle control.

A new option for this could be modeled after `AlwaysBreakTemplateDeclarations`, which has the option `MultiLine`, meaning declarations spanning only a single line will stay inline, that sounds like acceptable prior precedent.

**Comment by owenca** [comment]
> I don't worry too much when the attribute is short and the function is short, as in: `[[attr]] void f() {}` but it becomes much more frustrating with `[[clang::annotate("test", 1, 2, 3, "this is also a test")]] int i = 12;` where the attribute is overwhelming the rest of the declaration, but it all still fits on a single line.

`BreakAfterAttributes` now handles both [variable declarations](https://github.com/owenca/llvm-project/commit/199fc973ced20016b04ba540cf63a1d4914fa513) (in addition to function/ctor/dtor declarations) and [control statements](https://github.com/llvm/llvm-project/commit/40671bbdefb6ff83e2685576a3cb041b62f25bbe).
