### ISSUE TITLE
clang Codemodell: Fehler: Der clangbackend-Prozess wurde unerwartet beendet und neu gestartet.

### ISSUE THREAD

**Issue by bronski2** [llvm/llvm-project#54267]
Hello,
I get continually this error message:
clang Codemodell: Fehler: Der clangbackend-Prozess wurde unerwartet beendet und neu gestartet.
(The clangbackend-process was unexpected stopped and will be restart.)
This happens since I upgraded the clang rpm package on SUSE Tumbleweed to Version 13.0.1-1.1
The clang13 package was updatet too, to version 13.0.1-3.1

I tried to  update qt creator and tried to compile with a new user (new qt-creator config files )
This message happen to all my older project including "Hello world"

How can I solve the problem  ?

**Comment by bronski2** [comment]
No,
I tried to deselect the clang-tidy default settings, in Extras -> Einstellungen-> Analyzer (Extras->Preferences->Analyzer),it was not possible.
The path in the clang-tidy textbox is greyed.
The Qt-Creator Version is 6.0.2.

Where can I make a stack trace ?

From the QTCreatorBug-20171
_Probably the problem was reintroduced. I see this with Qt Creator 4.10.1. And now it marks all std::string(s) as "no member named 'string'"
It's with one boost based project on Ubuntu 18.04.3. I guess it just can't parse this huge amount of templates._

The Problem occurred when I tried to compile a source-code wit several nested templates.

**Comment by EugeneZelenko** [comment]
Could you please try to run Clang-tidy standalone?

**Comment by bronski2** [comment]
david@linux:~/C++/Hello_World> clang-tidy ./hello_world.cpp 
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "./hello_world.cpp"
No compilation database found in /home/david/C++/Hello_World or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
clang-tidy: symbol lookup error: clang-tidy: undefined symbol: LLVMInitializeM68kTargetInfo, version LLVM_13



It seems a compilation database is missing. Where can I get one ? Should thee not be a 'default databse' in the package ?

**Comment by EugeneZelenko** [comment]
Do you use CMake for your project? If so, you could use `CMAKE_EXPORT_COMPILE_COMMANDS` parameter.

**Comment by bronski2** [comment]
This is the output from a gimp plugin's compilation where I used CMake: 

Führe /usr/bin/cmake -S /home/david/Dokumente/gimp/Programmierung/Hallo_welt/gimp_hallo_welt_plug_in -B /home/david/Dokumente/gimp/Programmierung/Hallo_welt/build-gimp_hallo_welt_plug_in-Desktop-Debug in /home/david/Dokumente/gimp/Programmierung/Hallo_welt/build-gimp_hallo_welt_plug_in-Desktop-Debug aus.
compile commands:

-- Configuring done
-- Generating done
-- Build files have been written to: /home/david/Dokumente/gimp/Programmierung/Hallo_welt/build-gimp_hallo_welt_plug_in-Desktop-Debug
Verstrichene Zeit: 00:00.



The message("compile commands:\n${CMAKE_EXPORT_COMPILE_COMMANDS}") prints nothing.
Another error message which I found in the output from QtCreator:

Compiler feature detection failure!
The command "/bin/clang -x c -E -dM -" terminated with exit code 127.
/bin/clang: symbol lookup error: /bin/clang: undefined symbol: LLVMInitializeM68kTargetInfo, version LLVM_13

**Comment by bronski2** [comment]
Sorry, the exit code 127 seems to be  misleading.
I have rewritten Hello World with using CMake and got this output:

Führe /usr/bin/cmake -S /home/david/C++/Hello_world2/Hello_world2 -B /home/david/C++/Hello_world2/build-Hello_world2-Desktop-Debug in /home/david/C++/Hello_world2/build-Hello_world2-Desktop-Debug aus.
-- Configuring done
compile commands:
 
-- Generating done
-- Build files have been written to: /home/david/C++/Hello_world2/build-Hello_world2-Desktop-Debug
Verstrichene Zeit: 00:00.


Here is  ${CMAKE_EXPORT_COMPILE_COMMANDS} also empty.

I wonder that the /bin/clang: symbol lookup error: /bin/clang: undefined symbol: LLVMInitializeM68kTargetInfo, version LLVM_13 disappear. But perhaps it was already there. It's a little bit difficult because it's in the same window which is littered with the "Der clangbackend-Prozess wurde unerwartet beendet und neu gestartet." - Message

symbol lookup-error could indicate that there is aproblem with the open suse tumbleweed distribution.
I'm really the only one who has this problem ?

**Comment by EugeneZelenko** [comment]
Result of `CMAKE_EXPORT_COMPILE_COMMANDS` is `compile_commands.json` file in build directory. Than you need to use Clang-tidy's `-p=<build directory>` command-line option to point it to this file.

**Comment by bronski2** [comment]
I have searched with kfind for compile_commands.json files and found only one in the folder of my last c++ project.
It seems that clang doesn't generate new compile_commands.json files and/or deletes the old files.

**Comment by EugeneZelenko** [comment]
`compile_commands.json` is generated by CMake.

**Comment by bronski2** [comment]
The compile_command_commands.json file is in the project-desktop-Debug folder and a copy in the .qtc-clangd folder which is also in the  project-desktop-Debug folder.
The project was made with qmake.
How can I continue ?

**Comment by EugeneZelenko** [comment]
See [Clang-tidy documentation](https://clang.llvm.org/extra/clang-tidy/index.html). I mentioned `-p` command-line option already.

**Comment by bronski2** [comment]
david@localhost:~/C++/davids_meta_struct> clang-tidy davids_meta_struct.cpp -p ../build-davids_meta_struct-Desktop-Debug/compile_commands.json 
clang-tidy: symbol lookup error: clang-tidy: undefined symbol: LLVMInitializeM68kTargetInfo, version LLVM_13

david@localhost:~/C++/davids_meta_struct> clang-tidy davids_meta_struct.cpp -p ../build-davids_meta_struct-Desktop-Debug/
clang-tidy: symbol lookup error: clang-tidy: undefined symbol: LLVMInitializeM68kTargetInfo, version LLVM_13
david@localhost:~/C++/davids_meta_struct>

**Comment by bronski2** [comment]
I have solved the problem.
The problem was that you have to update llvm - packages especially the libLLVM13 and the lvm13 package.
It seems that necessary dependencies in the clang-tools.rpm were not set.

Thank you all for your help. :)

**Comment by EugeneZelenko** [comment]
So ticket could be closed?
