### ISSUE TITLE
Merge 5b7941ad7c893b4bb019e3c96b760b0f2670ccfc into LLVM 14

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#54278]
This fixes the test suite on ppc64le when a glibc >= 2.32 is installed.

@ecnelises Are you okay with backporting this to clang 14?

/cherry-pick 5b7941ad7c893b4bb019e3c96b760b0f2670ccfc

**Comment by tstellar** [comment]
@ecnelises OK to backport?

**Comment by ecnelises** [comment]
Yes, okay to backport.

**Comment by tstellar** [comment]
Merged: d843bde69aab
