### ISSUE TITLE
[clang-format] AlignConsecutiveAssignments aligns = in operator= with =delete. 

### ISSUE THREAD

**Issue by DanielSeemaier** [llvm/llvm-project#54271]
clang-format config:
```
AlignConsecutiveAssignments: true
```

With otherwise default options aligns the equal sign in `operator=` with the equal sign that deletes the copy assignment operator: 

```
struct F {
  void operator=(F const &) = delete;
  void operator             =(F &&) {
    // stuff
  }
};
```

**Comment by mydeveloperday** [comment]
Can you please tell us which version you are using?

**Comment by mydeveloperday** [comment]
I believe this was recently fixed, please try the latest version.

$ clang-format test2.cpp
struct F {
  void operator=(F const &) = delete;
  void operator=(F &&) {
    // stuff
  }
};
$ clang-format --version
clang-format version 15.0.0 (https://github.com/llvm/llvm-project.git c88deef0a7
218dd5c30500e7d3f58fc23283d3e5)

**Comment by DanielSeemaier** [comment]
Oh, must have missed that. Sorry for the troubles, thanks!
