### ISSUE TITLE
[C++20] [Modules] Crash if we enable `-std=c++20` and `-fmodule-ts`

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#54270]
Here is the reproducer
```
// m.cppm
export module m;

export int m() {
    return 0;
}
```

Run:
```
clang++ -std=c++20 -fmodules-ts --precompile -c m.cppm -o m.pcm 
```

Then it would crash at 
```
clang/lib/Sema/SemaModule.cpp:187: clang::Sema::DeclGroupPtrTy clang::Sema::ActOnModuleDecl(clang::SourceLocation, clang::SourceLocation, clang::Sema::ModuleDeclKind, clang::ModuleIdPath, clang::ModuleIdPath, clang::Sema::ModuleImportState&): Assertion `(!getLangOpts().CPlusPlusModules || SeenGMF == (bool)GlobalModuleFragment) && "mismatched global module state"' failed.
```

It would be OK if we remove the flag ` -fmodules-ts`.

It is meaningless to run `-std=c++20` and `-fmodules-ts` together. But crash is bad after all.

**Comment by operativeF** [comment]
It appears that this was solved in the commit [[C++20][Modules] Correct an assert for modules-ts.](https://github.com/llvm/llvm-project/commit/cf396c56e7df756d460a456f99ceab1b5d2c2e37) and I could not reproduce this assert upon recent compilation.

**Comment by ChuanqiXu9** [comment]
OK, if is fixed in trunk. I'll close this.
