### ISSUE TITLE
[AArch64] fold shift into cmp

### ISSUE THREAD

**Issue by rotateright** [llvm/llvm-project#54283]
```
define @high_mask1(i64 %x) {
  %r = icmp ugt i64 %x, 8191
  ret i1 %r
}

define i1 @high_mask2(i32 %0) {
  %r = icmp ugt i32 %x, 8191
  ret i1 %r
}
```

These become a shift and compare with zero, but those could be combined into "cmp xzr, x0, lsr 13":
https://godbolt.org/z/Pjeq7TshY

**Comment by efriedma-quic** [comment]
We should prefer `cmp x0, #2, lsl #12` over `cmp xzr, x0, lsr 13`; it's faster on most targets.

**Comment by efriedma-quic** [comment]
(or `tst x0, #-8192`)

**Comment by rotateright** [comment]
Note that if the compares are inverted, then we get the 'lsl' variation:
https://godbolt.org/z/M3x56PMoj

So the fold does exist somewhere, but it needs to be made more flexible.
