### ISSUE TITLE
clang misoptimize the 40bit bitfield

### ISSUE THREAD

**Issue by zxcuiop** [llvm/llvm-project#54289]
the code:
```c
struct foo
{
  unsigned long long b:40;
} x;

extern void abort (void);

void test1(unsigned long long res)
{
  /* Build a rotate expression on a 40 bit argument.  */
  if ((x.b<<8) + (x.b>>32) != res)
    abort ();
}

int main()
{
  x.b = 0x0100000001;
  test1(0x0000000101);
  x.b = 0x0100000000;
  test1(0x0000000001);
  return 0;
}
```

compile it with gcc:
```
$ gcc a.c -o a.out && ./a.out
```

compile it with clang-12
```
$ clang-12 a.c -o a.out && ./a.out
[1]    2736023 abort (core dumped)  ./a.out
```

**Comment by nikic** [comment]
Also occurs with current trunk. Clang performs the shifts promoted to unsigned long long, while GCC presumably performs them in the bitfield type, but I don't know which of those is correct.

**Comment by efriedma-quic** [comment]
clang follows the C++ rules here, for both C and C++ code.

gcc follows the C++ rules for C++ code, but uses different rules for C.  The rules gcc uses aren't entirely clear.

The C standard is ambiguous, despite a defect report raised a couple decades ago, so there isn't really any "right" answer.  We've chosen not to try to emulate gcc here.
