### ISSUE TITLE
[BUG] Broken loops with malloc-dependent conditions

### ISSUE THREAD

**Issue by hiornso** [llvm/llvm-project#54284]
**Minimal reproducing code:**
```c
#include <stdio.h>
#include <stdlib.h>

int main() {
	for (int i = 0; i < 100; ++i) {
		printf("%i\n", i);
	}
	
	void *ret = malloc(1);
	
	while(ret);
	
	return 0;
}
```
### **Expected behaviour:**
Prints integers from 0-99 inclusive, then gets stuck in the loop (because the malloc returned a nonzero pointer, since it is impossibly unlikely that we couldn't allocate that one byte).
This is always what happens when compiling using `gcc`.

**Observed behaviour:**
With `-O0`, as expected
With `-O1`: prints integers starting at 0 but never stops. Disassembly of produced object file shows that there is no loop exit condition for the `for` loop.

Using `-opt-bisect-limit`, it seems that when the following is enabled:
`BISECT: running pass (51) LoopDeletionPass on Parallel Loop at depth 1 containing: %7<header><latch>`
the behaviour changes from as expected to printing 0-99 then segfaulting, and then enabling
`BISECT: running pass (58) SimplifyCFGPass on main`
causes the behaviour to change again to simply never stop printing.
I'm not sure how to enable 58 without 51.

**System:**
Manjaro Linux, `5.16.11-2-MANJARO` kernel
Output of `clang -v`:
```
clang version 13.0.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/10.2.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/11.2.0
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.2.0
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.2.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```
Clang/LLVM installed via `pacman` from Manjaro repos

**Comment by LebedevRI** [comment]
> ```c
> 	while(ret);
> ```

Is UB in C. That is an infinite loop without side-effects, and it's **not** one of the forms
that are explicitly allowed by the standard to be infinite - the condition must be a constant true,
not just always evaluate to true.

**Comment by nikic** [comment]
You can use `-fno-finite-loops` to disable the forward progress requirement.
