### ISSUE TITLE
Clang C++20 Feature: P0315R4 - Lambdas in unevaluated contexts

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#54296]
id: P0315R4
paper: https://wg21.link/p0315r4
partially implemented: status unknown

**Comment by ecnelises** [comment]
Can we rename issue-subscribers-c-20 to issue-subscribers-cpp-20 (or something like that) to avoid confusion?

**Comment by cor3ntin** [comment]
This is marked partial because `[temp.deduct] p/9` is not implemented
https://eel.is/c++draft/temp.deduct#general-9
 

https://godbolt.org/z/jPKr6zv7P

**Comment by cor3ntin** [comment]
This is now fully implemented (in clang 17)
