### ISSUE TITLE
Clang C++20 Feature: P1073R3 - Immediate functions

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#54299]
id: P1073R3
paper: https://wg21.link/p1073r3
partially implemented: status unknown

**Comment by alanzhao1** [comment]
This can probably be closed as P1073R3 was marked complete in 3d2629dd3aab17098813c68b5b76bb864bc5e285 after being implemented in https://reviews.llvm.org/D119646

**Comment by alanzhao1** [comment]
This can probably be closed as P1073R3 was marked complete in 3d2629dd3aab17098813c68b5b76bb864bc5e285 after being implemented in https://reviews.llvm.org/D119646

**Comment by alanzhao1** [comment]
This can probably be closed as P1073R3 was marked complete in 3d2629dd3aab17098813c68b5b76bb864bc5e285 after being implemented in https://reviews.llvm.org/D119646

**Comment by alanzhao1** [comment]
This can probably be closed as P1073R3 was marked complete in 3d2629dd3aab17098813c68b5b76bb864bc5e285 after being implemented in https://reviews.llvm.org/D119646

**Comment by alanzhao1** [comment]
This can probably be closed as P1073R3 was marked complete in 3d2629dd3aab17098813c68b5b76bb864bc5e285 after being implemented in https://reviews.llvm.org/D119646

**Comment by alanzhao1** [comment]
This can probably be closed as P1073R3 was marked complete in 3d2629dd3aab17098813c68b5b76bb864bc5e285 after being implemented in https://reviews.llvm.org/D119646

**Comment by alanzhao1** [comment]
This can probably be closed as P1073R3 was marked complete in 3d2629dd3aab17098813c68b5b76bb864bc5e285 after being implemented in https://reviews.llvm.org/D119646

**Comment by alanzhao1** [comment]
This can probably be closed as P1073R3 was marked complete in 3d2629dd3aab17098813c68b5b76bb864bc5e285 after being implemented in https://reviews.llvm.org/D119646

**Comment by alanzhao1** [comment]
This can probably be closed as P1073R3 was marked complete in 3d2629dd3aab17098813c68b5b76bb864bc5e285 after being implemented in https://reviews.llvm.org/D119646

**Comment by alanzhao1** [comment]
This can probably be closed as P1073R3 was marked complete in 3d2629dd3aab17098813c68b5b76bb864bc5e285 after being implemented in https://reviews.llvm.org/D119646
