### ISSUE TITLE
Clang C++20 Feature: P0857R0 - functionality gaps in constraints

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#54293]
id: P0857R0
paper: https://wg21.link/p0857r0
partially implemented: Constraining template template parameters is not yet supported.

**Comment by h-vetinari** [comment]
This was marked completed in https://github.com/llvm/llvm-project/commit/ae48d1c76a6c14cdbf3a3e73f6c2c2befd0a81b0 - presumably this issue can be closed.
