### ISSUE TITLE
Clang C++20 Feature: P0732R2 - Class Types in Non-Type Template Parameters

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#54297]
id: P0732R2
paper: https://wg21.link/p0732r2
partially implemented: status unknown

**Comment by trueqbit** [comment]
I'd like to know the status of this feature.
cppreference's [compiler support matrix](https://en.cppreference.com/w/cpp/compiler_support#cpp20) lists "Class types in non-type template parameters" as partially implemented in clang 12. What does this mean exactly?

`__cpp_nontype_template_args` is still at version `201411L`, however the 'string literal operator template' and constant evaluation of string literals works perfectly, see [example](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxCBmAOykAA6oCoRODB7evnrJqY4CQSHhLFEx8baY9vkMQgRMxASZPn5cFVXptfUEhWGR0bEJCnUNTdmtQ109xaUDAJS2qF7EyOwc5gDMwcjeWADUJutuQ8TBwAfYJhoAghtbO5j7h2LAJIQILOeXN2abDNteewObicx0wrE%2B11uf3ujzcXkctEIAE8ITdIT88FQIAB9bHIRKJbEMWRIxKYbEETAsRIGSnY%2BrABSPC7rAAiuzMGi4AE4uFxZvs4m4TELdhAsDQQugcXiDEZcQLzAA2ZVi3HbQzAbEsJjaEi45kHdlcMyzWZfDYS4IPNwBK5CIQAFQAmspsNjHdgALLKO2e7FXABKAHEhNihHJlMoAPKBz2si0/VyYi3ozZUCW7W32p2u92en1%2B91B0PhyMxuPYBPXXa13bHLwOXZiPBMBQUpjAQVWOIJ9ZWSE1uvMNgKRJMFa7YKU4jMWjdr51pe7SnU2mYIHIBD1XZXUi7Lf1AB0J92AA1Ucu6w2m2gsgx6Yi27sQM2n%2B26l2RQOrlerxNHGQesCHQEAQGOU5dmATACAgRU4h/P8kN2YgYKWBhuz3c8TyPEU%2B0Q5Dazwxc/2I/tU1/P9VxpJhKSBVIAC9yQIXZQkvP8bxYiD5TwLBBExPBogpKkaMpBch0IgC8CAtAGCGTBVESYh6zwJiKRUpi4PEyjCKXVCCHQ1jdgAWl2LgDgIwjiMHb5012DQAHoHMzbEvSENxsQANWwQMSMI2T5MU5TuK1XjGEcGghOo9cIACljD2UiBlV480AFYLDY1LWQFV9eO/PLewXXsKN0g8BCGA9t0S5L0DSjKTCyizE3WSolD85C4oUpTgJOHi%2BIiwTiGEtdaMwWLyviqqxRqurMuy7TSqXIZQJQVBEiRIkIF4/dQn3AgEDwBRjPOFKmok5DrLRHSOqmvL0rms7bOTKh2qXMif1eutotGoFvrow4Epw84DwMBQmSud99xC7Ewv4yKhr%2Bh4CCh1TmJw3YAEl0FUdir06gA3MRm3hVAV1QR9WwUCBlrA4IsFUbElAARy8RgViBLHVCB9ZsHgyzkP0wyIcp36jzuixOYa1luYuBD3s%2BojivOy6l0RoFp2iOcwOh2GBqikT1xXXH9nShqLGJfAFFEYh0ClqWyrkylCfnJgSd2NbolokhzDMH3djxTwtO/BWULQ2cp0ETWxDAogKbbdXI9naPVvvOOFD285qZAsCdQAa3JOmFMZzAWbZjdDgII9GLG80eeD3ta/5y6Nmeijp12HVgjgi05bTTFM2zB0XTdD1vV9K5/RLMMIyjWN43azqguJogD0edkfaYH2A9oR6luz1b4VhIF9jMMx1QJIkSTJYbRPJBkFFfP2gWP8/CWJQRSWYg3RvpYhGSPw4J9fapTcAwH2u9rz7zQIfZ%2BgCfZ3maG%2BSmj9T4ALcAeI80FYKKkOMfcBICwGn0ei3WgbU0zRGICQXYxIsx2iHnmUehYJ7FhDNPcsc8qzNVbpCJWVwODzFoJwVKvA/AcC0KQVAnBhSWGsPWRYywHgbB4KQAgmh%2BHzFziAVKAAOI86x9EGMMYYpU%2BhOCSBEWoiRnBeAPw0CotR8w4CwBgIgVa1I6DRHIJQNA7j6AxA1EYLgqUNB2KwPjaSmBPKCQAO7RjJKI5RNBaAzgfhACIliIjBHqEiTgyjMnMGIEiaMERtCYAcLk3gPi2CCGjAwWgOSxG8CwDqIw4hGmkHwKhBweB8aYAfu0hSZT4SrGURrQR7TEQRGINkjwWBLEEBOCwCp8wqAGEZFEzAsT4kVJkIIEQYh2BSF2fIJQahLG6FaHKYw1hrD6DwBEB%2BkB5hrWqP04yy0jSmBkZYTkNjKhlOqC4Bg7hPDNH8MCqYfQYitFyGkAQowWhJBSHChgkKSj9HGP87pAhOgjFBWMNoAKOjDG6NaaYGLbAkoRXoCYDQ0UzH5AsJYKwJACKERY9pkiOC7FUNopUxklSSBBpqMyqUjwaHFWKXAhAqFKNmLwVRjSzSkAQGCLAMQ4KkE0esOIR5UqmI4OY0gSzgmkFEeIrlNiQB2MVVoRxLiIBIEWAQRI8IvHjV8dEUIrBVi8v5YKqCyAgImiPGYXgmB8BEBOKBVo/A9miHEEcuNJyVDqHaRc0g0TpmJGWQa4RZrLFcujPCV1LFUBUB5XygVQqAldiCeKyVEAPCeuUnKhVDj5iqqYOqygbLDW8BNXY81vBLW2GtfYpVGiQCSC4EeJU86F2LoXQkcZ6wOUWusROu1faw0Fs5Zu216jSC9OIKkZwkggA%3D) on godbolt.

The reason I ask is that I am implementing a feature in the sqlite_orm library that relies heavily on "compile time" strings as template parameters.

**Comment by bolshakov-a** [comment]
I think it is fully implemented (in Clang 12) except some issues with MSVC compatibility (see https://reviews.llvm.org/D146386). [Clang C++ status table](https://clang.llvm.org/cxx_status.html) has just a common cell for it and P1907R1. Even P1907R1 was almost fully implemented back in 2021 but reverted.

**Comment by nitnelave** [comment]
It doesn't seem _quite_ fully implemented, for instance it's missing floats: https://godbolt.org/z/aa8n5qPYs

**Comment by bolshakov-a** [comment]
No, it's another feature: [P1907R1](https://github.com/llvm/llvm-project/issues/54298).

**Comment by JVApen** [comment]
Status page indicates this is available from LLVM 12
