### ISSUE TITLE
clang optimizes overflow situation away

### ISSUE THREAD

**Issue by pfef-to** [llvm/llvm-project#54307]
I had a weird overflow situation in my code that never showed up during tests. Turns out clang optimized it away. Have a minimal example here: https://godbolt.org/z/5rjqsfs47

PS: I tried using bugpoint as pointed out in the docs, but it seems like this issue happens before translating the bc 🤔 creduce only made things less clear

**Comment by LebedevRI** [comment]
```
/app/example.cpp:12:23: runtime error: signed integer overflow: 2000 - -9223372036854775807 cannot be represented in type 'long long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /app/example.cpp:12:23 in 
```
https://godbolt.org/z/ecx739KTe
