### ISSUE TITLE
Clang C++20 Feature: P1874R1 - Dynamic Initialization Order of Non-Local Variables in Modules

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#54303]
id: P1874R1
paper: https://wg21.link/p1874r1
partially implemented: status unknown

**Comment by ChuanqiXu9** [comment]
This one should be fixed in [afda39a566d9](https://reviews.llvm.org/rGafda39a566d9b076bbcbeac1a6a1d4f6aecb3274)
