### ISSUE TITLE
IR Outliner should not add optsize to optnone functions (or outline from them at all)

### ISSUE THREAD

**Issue by ornata** [llvm/llvm-project#54317]
In the below example, we enable the IR outliner on two `optnone` functions:

https://godbolt.org/z/8498MaYEj

```
Attributes 'optsize and optnone' are incompatible!
void (i32*)* @outlined_ir_func_0
LLVM ERROR: Broken module found, compilation aborted!
```

If a function is marked as `optnone`, it should not be outlined from.

**Comment by ornata** [comment]
CC @AndrewLitteken

**Comment by AndrewLitteken** [comment]
https://reviews.llvm.org/D121567

**Comment by xgupta** [comment]
Fixed on the trunk - https://godbolt.org/z/vvKer5aq5.
