### ISSUE TITLE
SimplifyCFG or InstCombine incorrect in the presence of overflow

### ISSUE THREAD

**Issue by alinas** [llvm/llvm-project#54311]
[overflow_simplifycfg.ll.log](https://github.com/llvm/llvm-project/files/8217868/overflow_simplifycfg.ll.log)

Running: `opt -simplifycfg overflow_simplifycfg.ll` shows the issue.
The branching is removed and the difference is done unconditionally. In the original test, the difference overflows.

This was found following the change in https://reviews.llvm.org/D98152. The test does not overflow following the SimplifyCFG transform but does overflow after Instcombine. I haven't understood why this is yet. 

Pertinent diffs from original test:

Before SimplifyCFG:
```
40:                                               ; preds = %38, %13
  %41 = load i64, i64* %4, align 8
  %42 = getelementptr inbounds %"c442", %"c442"* %0, i64 0, i32 1
  %43 = load i64, i64* %42, align 8
  %44 = icmp slt i64 %41, %43
  br i1 %44, label %47, label %45

45:                                               ; preds = %40
  %46 = sub nsw i64 %41, %43
  br label %47

47:                                               ; preds = %45, %40
  %48 = phi i64 [ %46, %45 ], [ 0, %40 ]
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %9)
  ret i64 %48
```

After SimplifyCFG:

```
32:                                               ; preds = %29, %12
  %33 = load i64, i64* %4, align 8
  %34 = getelementptr inbounds %"c442", %"c442"* %0, i64 0, i32 1
  %35 = load i64, i64* %34, align 8
  %36 = icmp slt i64 %33, %35
  %37 = sub nsw i64 %33, %35
  %spec.select = select i1 %36, i64 0, i64 %37
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %7)
  ret i64 %spec.select
```

Before instcombine:
```
%112 = icmp slt i64 %.0, %111
%113 = sub nsw i64 %.0, %111
%spec.select = select i1 %112, i64 0, i64 %113
ret i64 %spec.select
```
After instcombine:
```
%112 = sub nsw i64 %.0, %111
%113 = call i64 @llvm.smax.i64(i64 %112, i64 0)
ret i64 %113
```

**Comment by alinas** [comment]
@nikic @spatel-gh

**Comment by LebedevRI** [comment]
Hm, yes: https://alive2.llvm.org/ce/z/b2fxWg

**Comment by LebedevRI** [comment]
Ok, the problem is in instcombine: https://alive2.llvm.org/ce/z/wGWQAo

**Comment by nikic** [comment]
Probably these SPF patterns needs to be removed: https://github.com/llvm/llvm-project/blob/abc8ca65c3de07f12c2f019d78b7e182ae1b46d7/llvm/lib/Analysis/ValueTracking.cpp#L5805-L5817

**Comment by nikic** [comment]
These were added in https://github.com/llvm/llvm-project/commit/cfcc42bdc2b880a3036337ac259f329ae56d8c22.

**Comment by rotateright** [comment]
Thanks for the report and analysis! I'll make a patch to remove the wrong analysis.
