### ISSUE TITLE
libclc CMake error: unknown arguments specified

### ISSUE THREAD

**Issue by hwnam831** [llvm/llvm-project#54315]
I cannot build libclc in both llvm-13 and llvm-15 due to the following error:

`LLVM version: 
CMake Error at /home/hwnam/llvm-project/libclc/CMakeLists.txt:51 (if):
  if given arguments:

    "VERSION_LESS" "3.9.0"

  Unknown arguments specified`

It seems like the following function does not set the environmental variable $LLVM_VERSION correctly.
`execute_process( COMMAND ${LLVM_CONFIG} "--version"
                 OUTPUT_VARIABLE LLVM_VERSION
                 OUTPUT_STRIP_TRAILING_WHITESPACE )
message( "LLVM version: ${LLVM_VERSION}" )

if( ${LLVM_VERSION} VERSION_LESS ${LIBCLC_MIN_LLVM} )
        message( FATAL_ERROR "libclc needs at least LLVM ${LIBCLC_MIN_LLVM}" )
endif()`

Is there any additional argument/environment I need to build libclc?

**Comment by JOE1994** [comment]
The aforementioned parts of `libclc/CMakeLists.txt` no longer seems to exist.

With LLVM @ recent `main` commit `8663b8777e8108f74f91a2a33115b3a00d57c043`,
I don't see any CMake errors when building `libclc` from source.

**Comment by JOE1994** [comment]
Please file a new issue if you see a similar issue with the latest stable llvm
