### ISSUE TITLE
[AVR] Illegal "call" instruction is generated on avr2 and avr25

### ISSUE THREAD

**Issue by benshi001** [llvm/llvm-project#54345]
For the following C code, 
```
int foo0(int a, int b);
int foob(int a, int b, int c) {
  return add(a, c) - b;
}
```

Build it with 
```
clang a.c -O3 --target=avr -mmcu=at90s8515 -S
```

Then the following assembly is generated
```
foob:                                   ; @foob
; %bb.0:
        push    r16
        push    r17
        mov     r16, r22
        mov     r17, r23
        mov     r22, r20
        mov     r23, r21
        call    foo0
        sub     r24, r16
        sbc     r25, r17
        pop     r17
        pop     r16
        ret
```

However the call instruction (long call) is available on avr3 and above, for avr2/avr25/avrtiny, rcall (show call) should be used.

**Comment by benshi001** [comment]
Fixed by https://reviews.llvm.org/D121539

**Comment by benshi001** [comment]
fixed in commit 

https://github.com/llvm/llvm-project/commit/45638931fb7c7a1b9c850e47601541b398868538

**Comment by tstellar** [comment]
@aykevl @dylanmckay What do you think about backporting this? https://github.com/llvm/llvm-project/commit/45638931fb7c7a1b9c850e47601541b398868538

**Comment by tstellar** [comment]
I have been unable to get in touch with the AVR maintainers, but this seems fine to me, so I'll merge it.
