### ISSUE TITLE
Bug:  without -std=c++17, clang will abort by llvm_unreachable when handle EST_Uninstantiated

### ISSUE THREAD

**Issue by zhouzhouyi-hub** [llvm/llvm-project#54342]
When compile following code without -std=c++17, clang will abort by llvm_unreachable, I proposed a solution: 
https://reviews.llvm.org/D121498

template<class T>
void foo() noexcept(T::value);

struct S {

static const bool value;

};

const bool S::value = 0;

template<class... Args, bool is_noexcept>
constexpr bool is_noexcept_function(void(Args...) noexcept(is_noexcept)) {

return is_noexcept;

}

void fn()
{

is_noexcept_function(foo<S>);

}

**Comment by zhouzhouyi-hub** [comment]
my solution to this bug: https://reviews.llvm.org/D121498

**Comment by zhouzhouyi-hub** [comment]
I close this issue because https://reviews.llvm.org/D121498 has been committed

**Comment by EugeneZelenko** [comment]
Fixed in 30adb9fd279785d18f9902ba980c7d8b31a6c8d7.
