### ISSUE TITLE
Please backport 26cd258420c774254cc48330b1f4d23d353baf05 ([AArch64] Use correct calling convention for each vararg)

### ISSUE THREAD

**Issue by lephilousophe** [llvm/llvm-project#54346]
This will fix #54025.

/cherry-pick 26cd258420c774254cc48330b1f4d23d353baf05

@efriedma-quic @rnk Are you OK with backporting this? Thanks.

**Comment by lephilousophe** [comment]
I don't understand why but the bot tried to cherry-pick in main instead of doing it in 14.x branch.

**Comment by brad0** [comment]
> I don't understand why but the bot tried to cherry-pick in main instead of doing it in 14.x branch.

You didn't file the bug report as part of the 14 milestone.

**Comment by lephilousophe** [comment]
It's against 14.0.1 milestone which contains "branch: release/14.x" in its description.

**Comment by efriedma-quic** [comment]
I'm fine with backporting, assuming it applies cleanly.

Cherry-picking to 14.0.1 might not be fully set up yet; 14.0 hasn't actually been tagged yet. @tstellar

**Comment by tstellar** [comment]
Merged: d150523f0776
