### ISSUE TITLE
[libc++] `std::fpclassify()` on non-floats that are convertible to float is an error?

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#54356]
I don't know if this is a bug, but it's an inconsistency with libstdc++:
https://godbolt.org/z/dKGxhndEj

**Comment by philnik777** [comment]
This should indeed be implicitly converted to double according to http://eel.is/c++draft/cmath.syn.

**Comment by antl-m** [comment]
Is this bug still relevant? I would like to work on it

**Comment by ldionne** [comment]
> Is this bug still relevant? I would like to work on it

Yes, I think it's still relevant! It'd be great if you can work on a PR for it, let us know once you have something!

**Comment by antl-m** [comment]
Created PR: #67913

**Comment by ldionne** [comment]
Closing since https://github.com/llvm/llvm-project/pull/67913 was merged.
