### ISSUE TITLE
Clang fails to compile calls to static consteval methods through references

### ISSUE THREAD

**Issue by jcelerier** [llvm/llvm-project#54366]
Repro: https://gcc.godbolt.org/z/3T9ccYjcn

```
struct S { 
    static consteval auto name() { return "foo"; }
 };

void f(S& s) {
    s.name();
}
```

- The same works with gcc.
- Removing the reference on the parameter does work, e.g. `void f(S s) { s.name(); }` is fine
- Calling through the typename does work, e.g. `void f(S s) { S::name(); }` is fine
- `constexpr` instead of `consteval` does work
- But assigning to a constexpr variable also fails (with the same remediations than above):

```
struct S { 
    static constexpr auto name() { return "foo"; }
 };

void f(S& s) {
    constexpr auto res = s.name();
}
```

**Comment by jcelerier** [comment]
@cor3ntin I'm sure that this is something dumb in the code (famous last words), would you have any pointers as to where to look ?

**Comment by cor3ntin** [comment]
@jcelerier Alas, I think clang is conforming here.
See https://wg21.link/p2280r3 for an exact description of this scenario and fix in C++23.
