### ISSUE TITLE
Failure to merge blend of negation and multiply into a single multiply

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#54364]
https://simd.godbolt.org/z/P3jfPz5G6

SLP recognises the mul/sub alt bin opcodes and vectorizes the operations, but InstCombine fails to recognise that the sub is a negation that would allow it to be merged into the multiply.

```
void mul_and_neg(int * __restrict dst, const int * src) {
  *dst++ = *src++ * 257;
  *dst++ = *src++ * -3;
  *dst++ = *src++ * -1;
  *dst++ = *src++ * -9;
}
```
clang -g0 -O3 -march=btver2
```
define void @mul_and_neg(i32* noalias nocapture noundef writeonly %dst, i32* nocapture noundef readonly %src) {
entry:
  %0 = bitcast i32* %src to <4 x i32>*
  %1 = load <4 x i32>, <4 x i32>* %0, align 4
  %2 = mul nsw <4 x i32> %1, <i32 257, i32 -3, i32 poison, i32 -9>
  %3 = sub nsw <4 x i32> <i32 poison, i32 poison, i32 0, i32 poison>, %1
  %4 = shufflevector <4 x i32> %2, <4 x i32> %3, <4 x i32> <i32 0, i32 1, i32 6, i32 3>
  %5 = bitcast i32* %dst to <4 x i32>*
  store <4 x i32> %4, <4 x i32>* %5, align 4
  ret void
}

vs

define void @mul_and_neg(i32* noalias nocapture noundef writeonly %dst, i32* nocapture noundef readonly %src) {
entry:
  %0 = bitcast i32* %src to <4 x i32>*
  %1 = load <4 x i32>, <4 x i32>* %0, align 4
  %2 = mul nsw <4 x i32> %1, <i32 257, i32 -3, i32 -1, i32 -9>
  %3 = bitcast i32* %dst to <4 x i32>*
  store <4 x i32> %2, <4 x i32>* %3, align 4
  ret void
}
```

**Comment by RKSimon** [comment]
@rotateright Not sure if we can easily extend foldSelectShuffleWith1Binop to handle this - otherwise maybe just add the pattern in foldSelectShuffle ?

**Comment by LebedevRI** [comment]
I suspect we should extend
https://github.com/llvm/llvm-project/blob/59630917d6cc7c4a273f617f92bf6190ee2992e1/llvm/lib/Transforms/InstCombine/InstCombineVectorOps.cpp#L1913-L1917
and use it here
https://github.com/llvm/llvm-project/blob/59630917d6cc7c4a273f617f92bf6190ee2992e1/llvm/lib/Transforms/InstCombine/InstCombineVectorOps.cpp#L2065
