### ISSUE TITLE
Bug in either C++17 (maybe 20?) spec, or llvm implementation, shared_ptr

### ISSUE THREAD

**Issue by timprepscius** [llvm/llvm-project#54365]
Hey there,

I'm not sure where to post this, I feel like I should be posting to some spec committee.  Not sure.

In the Xcode 12.5.1 std memory, there is the snippet:
```

template <class _Tp, class _Alloc>
void
__shared_ptr_emplace<_Tp, _Alloc>::__on_zero_shared() _NOEXCEPT
{
    __data_.second().~_Tp();
}

```

What this snippet does, is when a control block of a shared_ptr detects that there are no more references, it destructs/destroys the object.

Right now the code snippet calls the destructor explicitly, which leaves out the exciting things the allocator might do before destructing the object.

I believe this code snippet should be something like this (writing off the top of my head):

```
using value_allocator = _Alloc::template rebind<the_value_type>::other;
value_allocator allocator;
allocator.destroy(&__data_.second());

```

Or using allocator_traits, or what not.  But in the end, not calling the destructor, but rather using the allocator to call the destructor.

---

If this were the case I could write an allocator which might do something like:

```
void destroy(T *p)
{
  object_is_about_to_be_destroyed_template_function(p);
  other_allocator.destroy(p);
}

```
---

Should I take this issue somewhere else?  Does anyone know who I might talk to about this.

---

There is, of course, a work around, but it isn't pretty, and uses classes which I probably should be using.

**Comment by frederick-vs-ja** [comment]
This is a defect ([LWG2070](https://cplusplus.github.io/LWG/issue2070)) in old revisions of the C++ standard which is resolved by [P0674R1](https://wg21.link/p0674r1). P0674R1 is adopted for C++20.

Currently libc++ has implemented the resolution for LWG2070 in C++20 and later modes (in the PR [D91201](https://reviews.llvm.org/D91201)). But it seems that libstdc++ and MSVC STL are applying the resolution to all modes that have `std::allocate_shared`.

**Comment by ldionne** [comment]
I think it is reasonable to apply the resolution of [LWG2070](https://cplusplus.github.io/LWG/issue2070) as a DR in C++17 since this is what we normally do for LWG issues. I believe the reason why this wasn't done is probably just an oversight. IIRC I was the one to implement [P0674R1](https://wg21.link/p0674r1) and per our policy, I didn't apply the changes before C++20. But I must have missed that this part of the changes was resolving a LWG issue.
