### ISSUE TITLE
 TEST 'lld :: MachO/stabs.s' FAILED

### ISSUE THREAD

**Issue by codemzs** [llvm/llvm-project#54378]
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
 #0 0x00000000016e6903 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/mnt/vss/_work/1/b/llvm/Release/bin/lld+0x16e6903)
 #1 0x00000000016e462e llvm::sys::RunSignalHandlers() (/mnt/vss/_work/1/b/llvm/Release/bin/lld+0x16e462e)
 #2 0x00000000016e6eff SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f758b6cc3c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x143c0)
 #4 0x00000000019e55d7 lld::macho::TrieBuilder::makeNode() (/mnt/vss/_work/1/b/llvm/Release/bin/lld+0x19e55d7)
 #5 0x00000000019e5893 lld::macho::TrieBuilder::sortAndBuild(llvm::MutableArrayRef<lld::macho::Symbol const*>, lld::macho::TrieNode*, unsigned long, unsigned long) (/mnt/vss/_work/1/b/llvm/Release/bin/lld+0x19e5893)
 #6 0x00000000019e5a97 lld::macho::TrieBuilder::sortAndBuild(llvm::MutableArrayRef<lld::macho::Symbol const*>, lld::macho::TrieNode*, unsigned long, unsigned long) (/mnt/vss/_work/1/b/llvm/Release/bin/lld+0x19e5a97)
 #7 0x00000000019e5c75 lld::macho::TrieBuilder::build() (/mnt/vss/_work/1/b/llvm/Release/bin/lld+0x19e5c75)
 #8 0x0000000001a02b8e lld::macho::ExportSection::finalizeContents() (/mnt/vss/_work/1/b/llvm/Release/bin/lld+0x1a02b8e)
 #9 0x0000000001a2315c std::_Function_handler<void (), llvm::ThreadPool::createTaskAndFuture(std::function<void ()>)::'lambda'()>::_M_invoke(std::_Any_data const&) Writer.cpp:0:0
#10 0x0000000001a34801 void* llvm::thread::ThreadProxy<std::tuple<llvm::ThreadPool::grow(int)::$_0> >(void*) ThreadPool.cpp:0:0
#11 0x00007f758b6c0609 start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8609)
#12 0x00007f758b081163 __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f163)
/mnt/vss/_work/1/b/llvm/Release/tools/lld/test/MachO/Output/stabs.s.script: line 21: 385839 Segmentation fault      (core dumped) ld64.lld -arch x86_64 -platform_version macos 10.15 11.0 -syslibroot /mnt/vss/_work/1/s/llvm-project/lld/test/MachO/Inputs/MacOSX.sdk -fatal_warnings -lSystem test.o foo.o no-debug.o -oso_prefix "/mnt/vss/_work/1/b/llvm/Release/tools/lld/test/MachO/Output/stabs.s.tmp" -o /mnt/vss/_work/1/b/llvm/Release/tools/lld/test/MachO/Output/stabs.s.tmp/test-rel

**Comment by oontvoo** [comment]
Seems to crash because the TrieBuilder is alloc'ing new nodes with the bump-alloc [here](https://github.com/llvm/llvm-project/blob/294eca35a00f89dff474044ebd478a7f83ccc310/lld/MachO/ExportTrie.cpp#L149)

**Comment by oontvoo** [comment]
no the builder has not changed but the parallelisation is recent. (the allocator is not thread safe - and this sort of bug is random )

**Comment by codemzs** [comment]
Ah that would make sense, I'm actually consistently seeing it fail on my end.

**Comment by oontvoo** [comment]
> @oontvoo any idea when this fix will be checked-in? I'm contemplating disabling this test but first I want to be sure a fix is in works.

We have a quick/dirty fix https://reviews.llvm.org/D121638

**Comment by codemzs** [comment]
Thanks @oontvoo ! Is bump allocator used elsewhere too? If that is the case then the issue remains at large.

**Comment by codemzs** [comment]
@oontvoo Your fix is causing build failures on Windows

FAILED: tools/lld/MachO/CMakeFiles/lldMachO.dir/ExportTrie.cpp.obj 
C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DGTEST_HAS_RTTI=0 -DUNICODE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -ID:\a\_work\1\b\llvm\Debug\tools\lld\MachO -ID:\a\_work\1\llvm-project\lld\MachO -ID:\a\_work\1\llvm-project\lld\include -ID:\a\_work\1\b\llvm\Debug\tools\lld\include -ID:\a\_work\1\b\llvm\Debug\include -ID:\a\_work\1\llvm-project\llvm\include -ID:\a\_work\1\llvm-project\llvm\..\libunwind\include /DWIN32 /D_WINDOWS   /Zc:inline /Zc:__cplusplus /Zc:strictStrings /Oi /Zc:rvalueCast /bigobj /W4 -wd4141 -wd4146 -wd4244 -wd4267 -wd4291 -wd4351 -wd4456 -wd4457 -wd4458 -wd4459 -wd4503 -wd4624 -wd4722 -wd4100 -wd4127 -wd4512 -wd4505 -wd4610 -wd4510 -wd4702 -wd4245 -wd4706 -wd4310 -wd4701 -wd4703 -wd4389 -wd4611 -wd4805 -wd4204 -wd4577 -wd4091 -wd4592 -wd4319 -wd4709 -wd4324 -w14062 -we4238 /MDd /Zi /Ob0 /Od /RTC1   -wd4530 -wd4062  /EHs-c- /GR- -std:c++14 /showIncludes /Fotools\lld\MachO\CMakeFiles\lldMachO.dir\ExportTrie.cpp.obj /Fdtools\lld\MachO\CMakeFiles\lldMachO.dir\lldMachO.pdb /FS -c D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(148): error C2600: 'lld::macho::TrieNode::~TrieNode': cannot define a compiler-generated special member function (must be declared in the class first)
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(149): error C2065: 'nodes': undeclared identifier
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(148): note: This diagnostic occurred in the compiler generated function 'lld::macho::TrieNode::~TrieNode(void)'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(149): error C2672: 'begin': no matching overloaded function found
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(148): note: This diagnostic occurred in the compiler generated function 'lld::macho::TrieNode::~TrieNode(void)'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(150): error C2893: Failed to specialize function template 'unknown-type std::begin(_Container &)'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xutility(1916): note: see declaration of 'std::begin'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(150): note: With the following template arguments:
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(150): note: '_Container=unknown-type'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(148): note: This diagnostic occurred in the compiler generated function 'lld::macho::TrieNode::~TrieNode(void)'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(150): error C2784: 'const _Elem *std::begin(std::initializer_list<_Elem>) noexcept': could not deduce template argument for 'std::initializer_list<_Elem>' from 'unknown-type'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\initializer_list(57): note: see declaration of 'std::begin'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(148): note: This diagnostic occurred in the compiler generated function 'lld::macho::TrieNode::~TrieNode(void)'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(149): error C2672: 'end': no matching overloaded function found
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(148): note: This diagnostic occurred in the compiler generated function 'lld::macho::TrieNode::~TrieNode(void)'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(150): error C2893: Failed to specialize function template 'unknown-type std::end(_Container &)'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xutility(1926): note: see declaration of 'std::end'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(150): note: With the following template arguments:
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(150): note: '_Container=unknown-type'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(148): note: This diagnostic occurred in the compiler generated function 'lld::macho::TrieNode::~TrieNode(void)'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(150): error C2784: 'const _Elem *std::end(std::initializer_list<_Elem>) noexcept': could not deduce template argument for 'std::initializer_list<_Elem>' from 'unknown-type'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\initializer_list(63): note: see declaration of 'std::end'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(148): note: This diagnostic occurred in the compiler generated function 'lld::macho::TrieNode::~TrieNode(void)'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(150): error C3536: '<begin>$L0': cannot be used before it is initialized
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(148): note: This diagnostic occurred in the compiler generated function 'lld::macho::TrieNode::~TrieNode(void)'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(150): error C3536: '<end>$L0': cannot be used before it is initialized
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(148): note: This diagnostic occurred in the compiler generated function 'lld::macho::TrieNode::~TrieNode(void)'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(149): error C2100: illegal indirection
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(148): note: This diagnostic occurred in the compiler generated function 'lld::macho::TrieNode::~TrieNode(void)'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(149): error C2440: 'initializing': cannot convert from 'int' to 'lld::macho::TrieNode *'
D:\a\_work\1\llvm-project\lld\MachO\ExportTrie.cpp(149): note: Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
