### ISSUE TITLE
[RISCV] fpic optimisation 

### ISSUE THREAD

**Issue by abukharmeh** [llvm/llvm-project#54372]
When compiling position independent code for RISC-V and trying to access global variable inside any loop, the compiler tries to get the address of the global variable from GOT in every iteration of the loop, while in ARM, it does it only once before entering the loop. 

I think it only need to do it once in RISC-V as well. 

Example code that illisturate the problem compiled for RISC-V and ARM:
https://godbolt.org/z/YMoxGrY97

Edit: GCC does it before entering the loop for RISC-V

**Comment by luxufan** [comment]
It seems that the problem is caused by that when lowerGlobalAddress in RISCVISelLowering, the MachineMemOperand was not added.

Candidate patch: https://reviews.llvm.org/D121692

**Comment by luxufan** [comment]
@jrtc27 has submitted a patch before me. https://reviews.llvm.org/D121654
