### ISSUE TITLE
Please backport 352453569b2b044ddd5bd4df0074ff9863828b6f '[AARCH64] ssbs should be enabled by default for cortex-x1, cortex-x1c, cortex-a77' to 14.x

### ISSUE THREAD

**Issue by stuij** [llvm/llvm-project#54388]
The change is harmless.
Thanks!

**Comment by tstellar** [comment]
@TNorthover What do you think about backporting this? https://github.com/llvm/llvm-project/commit/352453569b2b044ddd5bd4df0074ff9863828b6f

**Comment by stuij** [comment]
@tstellar @TNorthover those libc++ changes in the pull request already are/were on 14.x. I guess the `/branch` command in my comment above was against perhaps the latest tag at the time?: `llvmorg-14.0.0-rc4`

Should I do anything about this, and if so, what is the correct course of action?

**Comment by tstellar** [comment]
@stuij I will take care of it.

**Comment by stuij** [comment]
thanks!

**Comment by tstellar** [comment]
Merged: add3ab7f4c8a 3f43d803382d
