### ISSUE TITLE
lldb function example fails

### ISSUE THREAD

**Issue by niansa** [llvm/llvm-project#54389]
When running this specific library usage example: `/main/lldb/examples/functions/main.cpp` on Debian with lldb from Debian repo, I get this error: `/main/lldb/examples/functions/main.cpp`

Not sure what it means since the executable is definitely in PATH and working.

Sorry for the initial invalid issue thing, pressed enter too early :D

More details:

 - I am running Debian Unstable
 - LLDB Version is 13.0.1
 - I am trying to use liblldb and I am trying to refer to that example program as reference
 
 niansa aka tuxifan

**Comment by niansa** [comment]
I managed to write a minimal sample to reproduce: https://gist.github.com/niansa/98c9e7dfe2e9ee6033b4857a3dee876c

**Comment by niansa** [comment]
Seems like that binary needs to be in the same directory as the executable for some reason, PATH is not enough

**Comment by labath** [comment]
I haven't been able to reproduce this (but I don't use debian). What's the error that it is supposed to fail with? "lldb-server not found" ? Can you give more details about how you build&run this program, and the locations of the various lldb components (lldb, lldb-server, liblldb) on your system?

**Comment by niansa** [comment]
-> #54391
