### ISSUE TITLE
lldb: lldb-server executable needs to be next to lldb executable

### ISSUE THREAD

**Issue by niansa** [llvm/llvm-project#54391]
I don't know if this is supposed to be like that or not, but the lldb-server executable needs to be next to the lldb executable for it to work.

I tested on lldb 13.0.1 on Linux (Debian Unstable)

**Comment by labath** [comment]
Yes, that is the layout that lldb expects. Are you saying that your layout is different?

(It is possible to override this location via the LLDB_DEBUGSERVER_PATH environment variable, but that is not something that one should normally need to do.)

**Comment by labath** [comment]
(TBE, the lldb-server location is determined relative to liblldb path. So if your liblldb is at $PREFIX/lib/liblldb.so, then lldb-server is expected to be at $PREFIX/bin/lldb-server)

**Comment by niansa** [comment]
When writing a custom application utilizing liblldb it's quite annoying when it only works if installed to `/usr/bin`.

**Comment by labath** [comment]
As I said in the other bug, the lldb-server location is determined relative to the liblldb location. The "search next to the main executable" thingy is a fallback path that should normally be necessary.

I will need to know the locations of the various lldb components (lldb, lldb-server, liblldb, your application) on your system to figure out why this is not working for you.

**Comment by niansa** [comment]
liblldb is in /usr/local/lib64, the executables are in /usr/bin

**Comment by labath** [comment]
That is a strange setup. Where are these binaries coming from? Are you sure that they were installed there by debian.

I find it surprising that an official package would install _any_ binary into /usr/local, let alone installing different parts of the package into different prefixes.

I got my hands on a debian system today, and the lldb package (version 11, though I doubt anything has changed for 13) was installed in /usr/lib/llvm-11/{lib/liblldb.so,bin/lldb-server} (with a /usr/bin/lldb-server -> /usr/lib/llvm-11/bin/lldb-server symlink).

This is a supported setup. Yours is not, so I think we need to figure out why is your system set up the way it is.

**Comment by niansa** [comment]
Huh, weird. Maybe because it is Debian Unstable?

**Comment by labath** [comment]
> Huh, weird. Maybe because it is Debian Unstable?

Maybe, in the sense that this is a bug that they haven't yet caught there.

In any case, I think you'll have to report this bug to debian -- they shouldn't be installing lldb like that. Feel free to cc me in case they have any questions.

**Comment by niansa** [comment]
Turns out I still had residue of a manual LLVM install through `make install`. Didn't realize until apt screamed at me :-)
