### ISSUE TITLE
LLDB: No example on how to wait for LLDB using liblldb in C++

### ISSUE THREAD

**Issue by niansa** [llvm/llvm-project#54392]
Hey,

I am searching myself to hell in trying to find any documentation or example in how to wait for LLDB so it can run callbacks and stuff like that. You might also call it "running the lldb async loop" or something like that, whatever.

Anyways, there needs to be at least one example in how to do that in C++.

The examples I have been basing my project on so far are https://github.com/llvm/llvm-project/tree/main/lldb/examples/lookup and https://github.com/llvm/llvm-project/tree/main/lldb/examples/functions - neither of them implement that.

niansa aka tuxifan

PS: If you could just comment with a very small example or some link to the reference that'd be amazing of you so I don't have to wait until there is a full example!

**Comment by jimingham** [comment]
The Python and C++ variants of the procedural part of the SB API's are pretty much identical, the differences being in small things like how to manage python vrs. C-strings, nothing substantial about the usage.  There is a Python example of how to use events to run a process in:

https://github.com/llvm/llvm-project/blob/main/lldb/examples/python/process_events.py

Transcribing that from Python to C++ should be pretty mechanical.

You can also look at the Driver to see how it works, that's:

https://github.com/llvm/llvm-project/tree/main/lldb/tools/driver

Jim
