### ISSUE TITLE
Source-based code coverage incorrectly handles if constexpr block

### ISSUE THREAD

**Issue by chfast** [llvm/llvm-project#54419]
When a `if constexpr` has a block `{}` and the condition is false, the source-based code coverage always marks the opening `{` as not-executed region (see line 4).

Tested with clang 14.

```
    1|       |template <int C>
    2|      1|int test() {
    3|      1|    if constexpr (C == 0)
  ------------------
  |  Branch (3:19): [Folded - Ignored]
  ------------------
    4|      0|    {
    5|      1|        return 1;
    6|      1|    }
    7|      1|    return 0;
    8|      1|}
    9|       |
   10|       |int main()
   11|      1|{
   12|      1|    return test<1>();
   13|      1|}

```

**Comment by chfast** [comment]
When viewing the AST of this program, the body of `if constexpr` is replaced with `NullStmt`. https://godbolt.org/z/x1zosvM43

```
|     |-IfStmt 0x557733b75ae0 <line:3:5, line:4:5> constexpr
|     | |-ConstantExpr 0x557733b75ab8 <line:3:19, col:24> 'bool'
|     | | |-value: Int 0
|     | | `-BinaryOperator 0x557733b75a98 <col:19, col:24> 'bool' '=='
|     | |   |-SubstNonTypeTemplateParmExpr 0x557733b75a78 <col:19> 'int'
|     | |   | |-NonTypeTemplateParmDecl 0x557733b752e8 <line:1:11, col:15> col:15 referenced 'int' depth 0 index 0 C
|     | |   | `-IntegerLiteral 0x557733b75a58 <line:3:19> 'int' 1
|     | |   `-IntegerLiteral 0x557733b75588 <col:24> 'int' 0
|     | `-NullStmt 0x557733b75ad8 <line:4:5>
```

**Comment by cor3ntin** [comment]
`if consteval` is also not handled correctly. see #57377

**Comment by hanickadot** [comment]
I have a fix in mentioned PR. There was incorrectly marked one character after `if constexpr (condition)` as uncovered. Now whole region of valid THEN or ELSE branch is marked as uncovered. Also there was a similar problem with `if consteval` where always first branch wasn't covered. This is first part of fix. In subsequent PR I will make the code as skipped so it won't glow red.

**Comment by hanickadot** [comment]
And I'm working on continuation of previous PR for `if constexpr` and `if consteval` to be properly skipped...
https://github.com/llvm/llvm-project/pull/78033
