### ISSUE TITLE
--only-keep-debug should suppress default --strip-all

### ISSUE THREAD

**Issue by jh7370** [llvm/llvm-project#54417]
llvm-strip by default specifies `--strip-all` unless certain options are specified. `--only-keep-debug` should be one of those options, but it isn't currently, meaning that the debug data that is desired is subsequently stripped too, unless e.g. `--no-strip-all` is also specified. This differs to GNU strip's behaviour, so is a bug. The fix is to change `--only-keep-debug` for llvm-strip to suppress the default `--strip-all` (if it is specified explicitly, it should still work though).

**Comment by jmciver** [comment]
I am interested in fixing this bug. I am currently working on it.

**Comment by jmciver** [comment]
Submitted patch for review:
https://reviews.llvm.org/D123738
