### ISSUE TITLE
Loop Vectorize regression in clang-14 (llvmorg-14.0.0-rc4) on Arm

### ISSUE THREAD

**Issue by jzern** [llvm/llvm-project#54427]
I initially found the bug was fixed/hidden in llvmorg-15-init-651-gb4c6d1bb3791 [1]. I bisected to a revert of a revert [2] and verified the failure with the original commit [3] and the expected behavior with the revert [4].

In discussion with the author of [1] (@david-arm, david.green@ if that's incorrect), he mentioned https://reviews.llvm.org/D115953 may have independently affected the issue. With [1] reverted and llvmorg-15-init-3042-gb3e8ace19830 [5] present the issue does not reproduce, but the revert + llvmorg-15-init-3042-gb3e8ace19830^ will fail.

Unfortunately I don't have a minimized repro, but observed the behavior in C++ code in libgav1. In the Zone2 predictor [6] the width loop appears to be unrolled and left_base_y initialized improperly. Another engineer who looked at the assembly more closely described it this way:
> It appears that the left_base_y (based on left_y) is calculated incorrectly. The compiler is unrolling the "width loop", processing two dsts per iteration. The compiler creates two left_y variables (we'll name left_y0 and left_y1). During the first "width loop" iteration (assuming y = 0), left_y0 should be -ystep ((0 << 6) - ystep) and left_y1 should be ((0 << 6) - (ystep * 2)),  but the compiler sets left_y0 to -ystep and left_y1 to 0.

The following worked for me on Debian testing:

```
$ git clone https://chromium.googlesource.com/codecs/libgav1/
$ git -C libgav1 clone --depth=1 \
  https://github.com/abseil/abseil-cpp.git third_party/abseil-cpp
$ git -C libgav1 clone --depth=1 \
  https://github.com/google/googletest.git third_party/googletest
$ LD=aarch64-linux-gnu-g++ \
  cmake -G Ninja -S libgav1 -B libgav1-build \
    -DCMAKE_TOOLCHAIN_FILE=libgav1/cmake/toolchains/aarch64-linux-gnu.cmake \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_CXX_FLAGS='-target aarch64-pc-linux-gnu' \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_C_FLAGS='-target aarch64-pc-linux-gnu' \
    -DLIBGAV1_MAX_BITDEPTH=12
$ ninja -C libgav1-build intrapred_directional_test
$ qemu-aarch64 -L /usr/aarch64-linux-gnu \
  libgav1-build/intrapred_directional_test
```

With this you should see failures in the 12-bit tests (the 10-bit passes only because the C code is replaced with NEON by default).

```
[  FAILED  ] C/DirectionalIntraPredTest12bpp.FixedInput/0, where GetParam() = kTransformSize4x4
[  FAILED  ] C/DirectionalIntraPredTest12bpp.FixedInput/1, where GetParam() = kTransformSize4x8
...
```

[1] llvmorg-15-init-651-gb4c6d1bb3791 [LoopVectorizer] Don't perform interleaving of predicated scalar loops
[2] llvmorg-14-init-16029-g42b34facfdfe Recommit "[LV] Inline CreateSplatIV call for scalar VFs."
[3] llvmorg-14-init-15776-g7ce48be0fd83 [LV] Inline CreateSplatIV call for scalar VFs (NFC).
[4] llvmorg-14-init-15898-g073c27b5e585 Revert "[LV] Inline CreateSplatIV call for scalar VFs (NFC)."
[5] llvmorg-15-init-3042-gb3e8ace19830 Recommit "[VPlan] Introduce recipe to build scalar steps."
[6] https://chromium.googlesource.com/codecs/libgav1/+/ae48a01600fe986882bd90a410fde39915172f52/src/dsp/intrapred_directional.cc#98

**Comment by fhahn** [comment]
@jzern Would it be possible to attach the preprocessed file that gets miscompiled + the flags used?

**Comment by jzern** [comment]
Yes, I meant to include the assembly, but didn't see a way to attach anything while creating the issue -- I see there's an area for it now, so I probably missed it.

[llvmorg-14.0.0-rc4-intrapred_directional.cc.ii.gz](https://github.com/llvm/llvm-project/files/8308469/llvmorg-14.0.0-rc4-intrapred_directional.cc.ii.gz)
[llvmorg-15-init-651-gb4c6d1bb3791.txt.gz](https://github.com/llvm/llvm-project/files/8308454/llvmorg-15-init-651-gb4c6d1bb3791.txt.gz)
[llvmorg-15-init-650-gd5a294421910.txt.gz](https://github.com/llvm/llvm-project/files/8308455/llvmorg-15-init-650-gd5a294421910.txt.gz)

DirectionalIntraPredictorZone2_C is the failing function.

Relevant build flags are probably: -target aarch64-pc-linux-gnu -O3 -std=gnu++11

Full command line:
clang++ \
  -DLIBGAV1_CMAKE=1 \
  -DLIBGAV1_ENABLE_AVX2=0 \
  -DLIBGAV1_ENABLE_NEON=1 \
  -DLIBGAV1_ENABLE_SSE4_1=0 \
  -DLIBGAV1_FLAGS_SRCDIR=\".../libgav1\" \
  -DLIBGAV1_FLAGS_TMPDIR=\"/tmp\" \
  -DLIBGAV1_MAX_BITDEPTH=12 \
  -I.../libgav1 \
  -I.../libgav1/src \
  -I.../libgav1/.build-llvm \
  -I.../libgav1/third_party/abseil-cpp \
  -I/usr/aarch64-linux-gnu/include/c++/11/aarch64-linux-gnu \
  -I/usr/aarch64-linux-gnu/include \
  -target \
  aarch64-pc-linux-gnu \
  -O3 \
  -DNDEBUG \
  -Wall \
  -Wextra \
  -Wmissing-declarations \
  -Wno-sign-compare \
  -fvisibility=hidden \
  -fvisibility-inlines-hidden \
  -Wframe-larger-than=196608 \
  -Wextra-semi \
  -Wmissing-prototypes \
  -Wshorten-64-to-32 \
  -Wextra-semi-stmt \
  -std=gnu++11 \
  -MD \
  -MT \
  CMakeFiles/libgav1_dsp.dir/src/dsp/intrapred_directional.cc.o \
  -MF \
  CMakeFiles/libgav1_dsp.dir/src/dsp/intrapred_directional.cc.o.d \
  -o \
  CMakeFiles/libgav1_dsp.dir/src/dsp/intrapred_directional.cc.o \
  -c \
  src/dsp/intrapred_directional.cc

**Comment by jzern** [comment]
While debugging the issue removing __restrict__ from the function parameters would avoid the optimization.

**Comment by jzern** [comment]
@fhahn anything else you need from me on this one?

**Comment by fhahn** [comment]
Ok I tracked down the issue and it looks like the underlying issue has been fixed on `main` already independent of b4c6d1bb3791.

Added a test in 631016a. @jzern could you confirm it works as expected on current `main` with b4c6d1bb3791 reverted?

**Comment by fhahn** [comment]
I also put up a fix for the 14.x branch, as the fix was submitted after the branch. The fix on main is a more invasive refactoring which likely doesn't make sense to pull in.

I put up a targeted fix for the release branch: 8767b7ea874e067912c547a6626acffb32b4032a (test) and 5ebd195cd16a437762afafdaabe395f4409d7b27 (fix).

@tstellar would it be possible to pick those fixes for 14.x?

**Comment by jzern** [comment]
> Ok I tracked down the issue and it looks like the underlying issue has been fixed on `main` already independent of [b4c6d1b](https://github.com/llvm/llvm-project/commit/b4c6d1bb379192cb5b712fda9f60cd105f21194f).
>

This matches my experience when [llvmorg-15-init-3042-gb3e8ace19830](https://github.com/llvm/llvm-project/commit/llvmorg-15-init-3042-gb3e8ace19830) was present.
 
> Added a test in [631016a](https://github.com/llvm/llvm-project/commit/631016a85349a33cd50cb34e6d0d745108afdb1b). @jzern could you confirm it works as expected on current `main` with [b4c6d1b](https://github.com/llvm/llvm-project/commit/b4c6d1bb379192cb5b712fda9f60cd105f21194f) reverted?

Thank you for looking into this. This passes my original test (x86-64, aarch64) and the new one via check-clang (x86-64) at llvmorg-15-init-7089-g8a0406dcc8ec with the other change reverted. I don't think I saw the problem on x86-64 at all, though. I haven't looked into cross compiling the tests.

**Comment by fhahn** [comment]
@tstellar I manually pushed the fix to `release/14.x`.

**Comment by vient** [comment]
Fix makes `release/14.x` branch not build without `-DLLVM_ENABLE_DUMP=ON`, I guess because of this line https://github.com/llvm/llvm-project/blob/release/14.x/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp#L2558
