### ISSUE TITLE
"Trip Count for Loop at depth 2 containing: %for.cond92<header><exiting>,%for.body94<latch> Changed!" with opt -verify-scev

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#54434]
llvm commit: fdcb256f9796
Reproduce with:
 opt -verify-scev -passes='loop-mssa(indvars)' -o /dev/null bbi-67494.ll

Result:

Trip Count for Loop at depth 2 containing: %for.cond92<header><exiting>,%for.body94<latch>
 Changed!
Old: 1
New: 0
Delta: 1
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: build-all/bin/opt -verify-scev -passes=loop-mssa(indvars) -o /dev/null bbi-67494.ll
 #0 0x0000000002cf75c3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (build-all/bin/opt+0x2cf75c3)
 #1 0x0000000002cf523e llvm::sys::RunSignalHandlers() (build-all/bin/opt+0x2cf523e)
 #2 0x0000000002cf7946 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007fc07bf36630 __restore_rt sigaction.c:0:0
 #4 0x00007fc079669387 raise (/lib64/libc.so.6+0x36387)
 #5 0x00007fc07966aa78 abort (/lib64/libc.so.6+0x37a78)
 #6 0x0000000001cd28ce llvm::ScalarEvolution::verify() const (build-all/bin/opt+0x1cd28ce)
 #7 0x000000000351b671 llvm::FunctionToLoopPassAdaptor::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build-all/bin/opt+0x351b671)
 #8 0x0000000003029c7d llvm::detail::PassModel<llvm::Function, llvm::FunctionToLoopPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) crtstuff.c:0:0
 #9 0x0000000002437975 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build-all/bin/opt+0x2437975)
#10 0x0000000000af4b0d llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function> >, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) crtstuff.c:0:0
#11 0x000000000243bd9a llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (build-all/bin/opt+0x243bd9a)
#12 0x0000000000af48ed llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) crtstuff.c:0:0
#13 0x0000000002436ac8 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (build-all/bin/opt+0x2436ac8)
#14 0x000000000077912f llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::StringRef>, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool) (build-all/bin/opt+0x77912f)
#15 0x000000000078b2b0 main (build-all/bin/opt+0x78b2b0)
#16 0x00007fc079655555 __libc_start_main (/lib64/libc.so.6+0x22555)
#17 0x000000000077415c _start (build-all/bin/opt+0x77415c)
Abort
[bbi-67494.ll.gz](https://github.com/llvm/llvm-project/files/8303209/bbi-67494.ll.gz)

**Comment by mikaelholmen** [comment]
This starts happening with d1e880acaa
    [SCEV] Enable verification in LoopPM

but that just enables scev verification so I suppose the actual problem is older.

**Comment by nikic** [comment]
I think this is a false-positive. The verification failure is after indvars on the inner loop:
```
define void @func_52() {
entry:
  br label %for.cond

for.cond:                                         ; preds = %for.end, %entry
  %0 = phi i32 [ %inc105, %for.end ], [ 0, %entry ]
  %cmp = icmp sge i32 %0, 1
  br i1 %cmp, label %for.cond92.preheader, label %for.end106

for.cond92.preheader:                             ; preds = %for.cond
  br label %for.cond92

for.cond92:                                       ; preds = %for.cond92.preheader, %for.body94
  br i1 false, label %for.body94, label %for.end

for.body94:                                       ; preds = %for.cond92
  br label %for.cond92

for.end:                                          ; preds = %for.cond92
  %inc105 = add nsw i32 %0, 1
  br label %for.cond

for.end106:                                       ; preds = %for.cond
  ret void
}
```
Presumably, indvars has determined that the inner loop is unreachable, and optimized the condition. We guard against this when the condition is literally `false`, but here it seems to have determined this through some other logic, though I'm not sure which.

I think in this case the reachability check could be made a bit stronger, but I suspect we'll see more issues like this.

**Comment by mikaelholmen** [comment]
Thanks!
