### ISSUE TITLE
IR Outliner: Instruction does not dominate all uses!

### ISSUE THREAD

**Issue by ornata** [llvm/llvm-project#54430]
When compiling sqlite3 for AArch64 at -O3 using the IR outliner we get

```
Instruction does not dominate all uses!
  %5 = load i32, i32* %rc5, align 4, !tbaa !89
  %13 = phi i32 [ %5, %sqlite3ValueNew.exit.thread.i ], [ %5, %if.then.i50 ]
Instruction does not dominate all uses!
  %5 = load i32, i32* %rc5, align 4, !tbaa !89
  %13 = phi i32 [ %5, %sqlite3ValueNew.exit.thread.i ], [ %5, %if.then.i50 ]
in function outlined_ir_func_7
```

Bugpointed testcase available here: https://godbolt.org/z/s1EascTMW

CC @AndrewLitteken

**Comment by AndrewLitteken** [comment]
I think this is related to this bug: https://reviews.llvm.org/D121313 which, looking at it now, was closed on accident because I copied the wrong differential revision.

**Comment by AndrewLitteken** [comment]
https://reviews.llvm.org/D122206

**Comment by xgupta** [comment]
Fixed on the trunk - https://godbolt.org/z/v54rcTe88.
