### ISSUE TITLE
problem using clang/llvm libraries on Mac OS X with a built libc++

### ISSUE THREAD

**Issue by mppf** [llvm/llvm-project#54438]
I'm running into problems when using `clang` as a library on Mac OS X when linking with the LLVM project `libc++` rather than the system one.

Unfortunately I do not know the nature of this problem. Some possibilities that I am aware of:
 * a problem in LLVM Support
 * a problem in clang
 * a problem in libc++
 * the reproducer doing something unsupported

The reproducer tries to get a file from `clang::FileManager` that doesn't exist and expects an error code that matches `llvm::errc::no_such_file_or_directory`. However the `!=` call to see if it matches indicates that the error is different, even though it has the same message. This is very strange and causes major problems when using clang as a library. (I created the reproducer by pulling out bits of clang that were behaving unexpectedly).

The reproducer reliably reproduces the problem on my own system (Mac OS X Monterey 12.3). This reproducer works by building {LLVM,clang,libc++} twice in order to arrange for the second build of clang/llvm to use a libc++ from the first build. This is by no means the smallest reproducer possible.

I do know of one workaround, which is to add a `-L` flag for the system libraries first in the link path.

Previous versions of this issue on other projects:
 * https://github.com/chapel-lang/chapel/issues/19217
 * https://github.com/Homebrew/homebrew-core/issues/96915
 
Reproducer files are included in the details section below. I will also attach a .zip to make getting all of these more convenient.

Thanks very much for any help with this issue.

<details>

runtest.sh
```
#!/bin/bash

# assumes ../llvm-project is checked out
#  bug report uses 75e33f71c2dae584b13a7d1186ae0a038ba98838 llvmorg-13.0.1
#
# will make ../llvm-build1 and ../llvm-build2
# will install to /tmp/llvm1 and /tmp/llvm2
./cmake1.sh
./build1.sh
./cmake2.sh
./build2.sh
./repro.sh
```

cmake1.sh
```
#!/bin/bash

mkdir -p ../llvm-build1

cd ../llvm-build1

cmake ../llvm-project/llvm \
    -DCMAKE_INSTALL_PREFIX=/tmp/llvm1 \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk \
    -DLLVM_ENABLE_PROJECTS=clang \
    -DLLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi" \
    -DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON \
    -DLLVM_LINK_LLVM_DYLIB=ON \
    -DLLVM_ENABLE_EH=ON \
    -DLLVM_ENABLE_FFI=ON \
    -DLLVM_ENABLE_RTTI=ON \
    -DLLVM_INCLUDE_DOCS=OFF \
    -DLLVM_INCLUDE_TESTS=OFF \
    -DLLVM_ENABLE_Z3_SOLVER=OFF \
    -DLLVM_OPTIMIZED_TABLEGEN=ON \
    -DLLVM_TARGETS_TO_BUILD=Native \
    -DCLANG_PYTHON_BINDINGS_VERSIONS="3.10;3.9;3.8" \
    -DFFI_INCLUDE_DIR=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/ffi \
    -DFFI_LIBRARY_DIR=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/lib \
    -DLLVM_BUILD_LLVM_C_DYLIB=ON \
    -DLLVM_ENABLE_LIBCXX=ON \
    -DDEFAULT_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk \

```

build1.sh
```
#!/bin/bash

export CMAKE_BUILD_PARALLEL_LEVEL=5
cd ../llvm-build1
cmake --build . $CMAKE_PARBUILD --target install-llvm-headers
cmake --build . $CMAKE_PARBUILD --target install-cmake-exports
cmake --build . $CMAKE_PARBUILD --target LLVMSupport
cmake --build . $CMAKE_PARBUILD --target install-LLVMSupport
cmake --build . $CMAKE_PARBUILD --target llvm-config
#cmake --build . --target install-llvm-config
#cmake --build . --target clang
#cmake --build . --target install-clang
cmake --build . $CMAKE_PARBUILD --target install
```

cmake2.sh
```
#!/bin/bash

mkdir -p ../llvm-build2
cd ../llvm-build2

# carlocab's reproducer

cmake ../llvm-project/llvm \
    -DCMAKE_INSTALL_PREFIX=/tmp/llvm2 \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk \
    -DLLVM_ENABLE_PROJECTS=clang \
    -DLLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi" \
    -DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON \
    -DLLVM_LINK_LLVM_DYLIB=ON \
    -DLLVM_ENABLE_EH=ON \
    -DLLVM_ENABLE_FFI=ON \
    -DLLVM_ENABLE_RTTI=ON \
    -DLLVM_INCLUDE_DOCS=OFF \
    -DLLVM_INCLUDE_TESTS=OFF \
    -DLLVM_ENABLE_Z3_SOLVER=OFF \
    -DLLVM_OPTIMIZED_TABLEGEN=ON \
    -DLLVM_TARGETS_TO_BUILD=Native \
    -DCLANG_PYTHON_BINDINGS_VERSIONS="3.10;3.9;3.8" \
    -DFFI_INCLUDE_DIR=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/ffi \
    -DFFI_LIBRARY_DIR=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/lib \
    -DLLVM_BUILD_LLVM_C_DYLIB=ON \
    -DLLVM_ENABLE_LIBCXX=ON \
    -DRUNTIMES_CMAKE_ARGS=-DCMAKE_INSTALL_RPATH="@loader_path/../lib;/tmp/llvm1/lib" \
    -DDEFAULT_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk \
    -DCMAKE_C_COMPILER=/tmp/llvm1/bin/clang \
    -DCMAKE_CXX_COMPILER=/tmp/llvm1/bin/clang++ \
    -DCMAKE_PREFIX_PATH=/tmp/llvm1 \
    -DCMAKE_INSTALL_RPATH="@loader_path/../lib;/tmp/llvm1/lib"

exit 0
```

build2.sh
```
#!/bin/bash

export CMAKE_BUILD_PARALLEL_LEVEL=5
cd ../llvm-build2
cmake --build . $CMAKE_PARBUILD --target install-llvm-headers
cmake --build . $CMAKE_PARBUILD --target install-cmake-exports
cmake --build . $CMAKE_PARBUILD --target LLVMSupport
cmake --build . $CMAKE_PARBUILD --target install-LLVMSupport
cmake --build . $CMAKE_PARBUILD --target llvm-config
#cmake --build . --target install-llvm-config
#cmake --build . --target clang
#cmake --build . --target install-clang
cmake --build . $CMAKE_PARBUILD --target install
```

repro.sh
```
#!/bin/bash

/tmp/llvm2/bin/clang++ -c repro.cpp -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -c -fno-rtti -I/tmp/llvm2/include -std=c++14 -stdlib=libc++ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/usr/local/include

/tmp/llvm2/bin/clang++ repro.o -o a.out -lclangFrontend -lclangSerialization -lclangDriver -lclangCodeGen -lclangParse -lclangSema -lclangAnalysis -lclangEdit -lclangASTMatchers -lclangAST -lclangLex -lclangBasic -Wl,-rpath,/tmp/llvm2/lib -L/tmp/llvm2/lib -Wl,-search_paths_first -Wl,-headerpad_max_install_names -lLLVM -L/usr/local/lib

./a.out

# This adjustment to the link line allows the test to pass,
# for some reason.
#/tmp/llvm2/bin/clang++ repro.o -o a.out -L/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/lib -lclangFrontend -lclangSerialization -lclangDriver -lclangCodeGen -lclangParse -lclangSema -lclangAnalysis -lclangEdit -lclangASTMatchers -lclangAST -lclangLex -lclangBasic -Wl,-rpath,/tmp/llvm2/lib -L/tmp/llvm2/lib -Wl,-search_paths_first -Wl,-headerpad_max_install_names -lLLVM -L/usr/local/lib
```

repro.cpp
```
#include "llvm/Support/Errc.h"
#include "clang/Basic/FileManager.h"

#include <iostream>

int main() {
  clang::FileManager fileMgr((clang::FileSystemOptions()));

  auto file = fileMgr.getFileRef("./nonexistant.h", /*OpenFile=*/true);

  std::error_code EC = llvm::errorToErrorCode(file.takeError());

  std::cout << "EC.message is " << EC.message() << "\n";

  bool not_no_such = (EC != llvm::errc::no_such_file_or_directory);
  bool is_no_such = !not_no_such;

  std::cout << "EC == no_such_file_or_directory is " << is_no_such << "\n";

  if (!is_no_such) {
    std::cout << "FAIL\n";
  }

  return 0;
}
```

</details>

Zip file containing the reproducer: 
[issue-54438.zip](https://github.com/llvm/llvm-project/files/8304826/issue-54438.zip)

**Comment by mppf** [comment]
FYI I have added this to the issue description

> The reproducer tries to get a file from `clang::FileManager` that doesn't exist and expects an error code that matches `llvm::errc::no_such_file_or_directory`. However the `!=` call to see if it matches indicates that the error is different, even though it has the same message. This is very strange and causes major problems when using clang as a library. (I created the reproducer by pulling out bits of clang that were behaving unexpectedly).

**Comment by mppf** [comment]
Hi @adrian-prantl 👋 do you think you might be able to help figure out what is going wrong here (Or refer to somebody else)? In the Chapel project we applied a clunky workaround to get it working with Homebrew LLVM 12 or 13 but I find this problem very unnerving. Any help would be much appreciated.

**Comment by carlocab** [comment]
Just as a quick reference, the following piece of code appears to misbehave when linking against a just-built `libc++` (by passing it to `LLVM_ENABLE_RUNTIMES):
```cpp
#include "llvm/Support/Errc.h"
#include "clang/Basic/FileManager.h"

#include <iostream>

int main() {
  clang::FileManager fileMgr((clang::FileSystemOptions()));

  auto file = fileMgr.getFileRef("./nonexistant.h", /*OpenFile=*/true);

  std::error_code EC = llvm::errorToErrorCode(file.takeError());

  std::cout << "EC.message is " << EC.message() << "\n";

  bool not_no_such = (EC != llvm::errc::no_such_file_or_directory);
  bool is_no_such = !not_no_such;

  std::cout << "EC == no_such_file_or_directory is " << is_no_such << "\n";

  return 0;
}
```
When compiled using a Homebrew-installed LLVM 13:
```
clang++ -c pretend-in-llvm.cpp -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -c -fno-rtti -I/usr/local/Cellar/llvm/13.0.1_1/include -std=c++14 -stdlib=libc++ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/usr/local/include
clang++ pretend-in-llvm.o -o a.out -lclangFrontend -lclangSerialization -lclangDriver -lclangCodeGen -lclangParse -lclangSema -lclangAnalysis -lclangEdit -lclangASTMatchers -lclangAST -lclangLex -lclangBasic -Wl,-rpath,/usr/local/Cellar/llvm/13.0.1_1/lib -L/usr/local/Cellar/llvm/13.0.1_1/lib -Wl,-search_paths_first -Wl,-headerpad_max_install_names -lLLVM-13 -L/usr/local/lib
```
running the produced binary results in
```
EC.message is No such file or directory
EC == no_such_file_or_directory is 0
```
This can also be reproduced by building `clang` and `libc++` from source without using Homebrew.

On the other hand, if you insist on linking against Apple `libc++` at `/usr/lib/libc++.1.dylib` (by modifying the link flags, or not building `libc++`), you get:
```
EC.message is No such file or directory
EC == no_such_file_or_directory is 1
```
@EugeneZelenko, perhaps you could take another look, since I don't think `question` is the correct label here. This seems to be a genuine bug; it's just not clear where exactly the bug lies.

**Comment by mppf** [comment]
@jdoerfert - I'm not sure if this is what you are asking, but I think the answer is `2`.

In particular, if I add this just before the `return 0` in the reproducer

```
  std::cout << "EC.value is " << EC.value() << "\n";
  std::cout << "no_such_file_or_directory.value is " << llvm::errc::no_such_file_or_directory << "\n";
```

it prints out this:

```
EC.message is No such file or directory
EC == no_such_file_or_directory is 0
EC.value is 2
no_such_file_or_directory.value is generic:2
```

where the last two lines are the same whether or we use the workaround to link with the system libc++ instead of the built on / the homebrew one.

**Comment by jdoerfert** [comment]
This helps, I think. Remember, I'm just guessing here.
Check the category of the `std::error_code EC`. I assume it is not `std::generic_category()`, which is the category of the `llvm::errc::...` converted to `std::error_code`. Thus comparison is false.
`EC.value() == llvm::errc::no_such...` should be true though.

**Comment by mppf** [comment]
> This helps, I think. Remember, I'm just guessing here.

Thanks very much for your help.

> Check the category of the `std::error_code EC`. I assume it is not `std::generic_category()`, which is the category of the `llvm::errc::...` converted to `std::error_code`. Thus comparison is false.
> `EC.value() == llvm::errc::no_such...` should be true though.


The `EC` variable has error category `std::generic_category` according to printing out category().name() (where it prints out `generic`); but `EC.category() == std::generic_category` is false (and so is comparing to all of the other categories that I know of). And that goes away with the workaround. Super weird.


<details>

``` c++
#include "llvm/Support/Errc.h"
#include "clang/Basic/FileManager.h"

#include <iostream>
#include <system_error>
#include <future>

int main() {
  clang::FileManager fileMgr((clang::FileSystemOptions()));

  auto file = fileMgr.getFileRef("./nonexistant.h", /*OpenFile=*/true);

  std::error_code EC = llvm::errorToErrorCode(file.takeError());

  std::cout << "EC.message is " << EC.message() << "\n";

  bool not_no_such = (EC != llvm::errc::no_such_file_or_directory);
  bool is_no_such = !not_no_such;

  std::cout << "EC == no_such_file_or_directory is " << is_no_such << "\n";

 
  std::cout << "EC.value is " << EC.value() << "\n";
  std::cout << "EC.category is " << EC.category().name() << "\n";
  std::cout << "no_such_file_or_directory.value is " << llvm::errc::no_such_file_or_directory << "\n";

  std::cout << "EC.value() == no_such_file_or_directory is " << (EC.value() ==
      (int)(llvm::errc::no_such_file_or_directory)) << "\n";

  std::cout << "EC.category() == std::generic_category is " << (EC.category() == std::generic_category()) << "\n";

  std::cout << "EC.category() == std::system_category is " << (EC.category() == std::system_category()) << "\n";

  std::cout << "EC.category() == std::iostream_category is " << (EC.category() == std::iostream_category()) << "\n";

  std::cout << "EC.category() == std::future_category is " << (EC.category() == std::future_category()) << "\n";

  return 0;
}
```

```
clang++ -c pretend-in-llvm.cpp -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -c -fno-rtti -I/usr/local/Cellar/llvm/13.0.1_1/include -std=c++14 -stdlib=libc++ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/usr/local/include
clang++ pretend-in-llvm.o -o a.out -lclangFrontend -lclangSerialization -lclangDriver -lclangCodeGen -lclangParse -lclangSema -lclangAnalysis -lclangEdit -lclangASTMatchers -lclangAST -lclangLex -lclangBasic -Wl,-rpath,/usr/local/Cellar/llvm/13.0.1_1/lib -L/usr/local/Cellar/llvm/13.0.1_1/lib -Wl,-search_paths_first -Wl,-headerpad_max_install_names -lLLVM-13 -L/usr/local/lib
```

```
EC.message is No such file or directory
EC == no_such_file_or_directory is 0
EC.value is 2
EC.category is generic
no_such_file_or_directory.value is generic:2
EC.value() == no_such_file_or_directory is 1
EC.category() == std::generic_category is 0
EC.category() == std::system_category is 0
EC.category() == std::iostream_category is 0
EC.category() == std::future_category is 0
```

With the workaround

```
clang++ -c pretend-in-llvm.cpp -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -c -fno-rtti -I/usr/local/Cellar/llvm/13.0.1_1/include -std=c++14 -stdlib=libc++ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/usr/local/include
clang++ -L/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/lib pretend-in-llvm.o -o a.out -lclangFrontend -lclangSerialization -lclangDriver -lclangCodeGen -lclangParse -lclangSema -lclangAnalysis -lclangEdit -lclangASTMatchers -lclangAST -lclangLex -lclangBasic -Wl,-rpath,/usr/local/Cellar/llvm/13.0.1_1/lib -L/usr/local/Cellar/llvm/13.0.1_1/lib -Wl,-search_paths_first -Wl,-headerpad_max_install_names -lLLVM-13 -L/usr/local/lib
```

```
EC.message is No such file or directory
EC == no_such_file_or_directory is 1
EC.value is 2
EC.category is generic
no_such_file_or_directory.value is generic:2
EC.value() == no_such_file_or_directory is 1
EC.category() == std::generic_category is 1
EC.category() == std::system_category is 0
EC.category() == std::iostream_category is 0
EC.category() == std::future_category is 0
```

</details>

**Comment by jdoerfert** [comment]
My best guess is that you end up with 2 versions of `static __generic_error_category s;`, and from there things go sideways.

I don't know where it comes from though. Maybe something links in the system one already, which is used for `std::generic_category()`, and the one from your libcxx is used by LLVM.

**Comment by mppf** [comment]
@jdoerfert - any idea what to do next / who might be able to investigate further?

**Comment by jdoerfert** [comment]
Not really. Though, this seems to describe your situation:
https://groups.google.com/g/llvm-dev/c/6ZZ0FjiueDY/m/2rsq5BMOBQAJ

"static __generic..." inside of `const error_category& generic_category() noexcept {...}` is pretty much like a global after all. They report the conditions under which things work.

Does `ldd` show extern things being included, maybe one of them has the system libcxx linked in somehow.

**Comment by mppf** [comment]
> Does ldd show extern things being included, maybe one of them has the system libcxx linked in somehow.

We can't use ldd on Mac OS X but IIRC we know from `otool -L` that the system libc++ is loaded in either case.

**Comment by mppf** [comment]
@ldionne - would you be able to help with this issue? There is obviously something wrong but we need help understanding where the bug is. Thanks.

**Comment by jdoerfert** [comment]
> > Does ldd show extern things being included, maybe one of them has the system libcxx linked in somehow.
> 
> We can't use ldd on Mac OS X but IIRC we know from `otool -L` that the system libc++ is loaded in either case.

Good to know in case I ever use a Mac ;).

The way I read the thread, pulling in system libc++ and a custom libc++ will not work. And the reason is basically what you see, globals are not unique.

**Comment by mppf** [comment]
> The way I read the thread, pulling in system libc++ and a custom libc++ will not work. And the reason is basically what you see, globals are not unique.

I may be wrong, but it's my understanding that on Mac OS X, pretty much all C++ programs link with the system libc++. Does that imply that it is impossible to (reliably) use a custom built libc++ on that platform?

**Comment by jdoerfert** [comment]
Doesn't the thread mention example apps that don't link in system libs and use the custom one, e.g., chrome: https://groups.google.com/g/llvm-dev/c/6ZZ0FjiueDY/m/zVwhWzoOBQAJ

**Comment by mppf** [comment]
I'm closing this issue because Homebrew now uses the strategy of installing the LLVM-built libc++ into a different directory from the LLVM libraries which resolves the problem. See https://github.com/Homebrew/homebrew-core/issues/96915 for details.

**Comment by bradcray** [comment]
@mppf: Is there any existing code we have that adds complexity or fragility to work around this issue when it existed, which we could now remove?

**Comment by mppf** [comment]
@bradcray - yes, that is what https://github.com/chapel-lang/chapel/pull/20698 does
