### ISSUE TITLE
OpAsmParser::OperandType name is really confusing

### ISSUE THREAD

**Issue by silvasean** [llvm/llvm-project#54446]
Every time I use this type I get confused by the fact that it has "type" in the name. Even the comment above it says:

```
  /// This is the representation of an operand reference.
  struct OperandType {
```

So wouldn't OperandReference be a better name?

**Comment by lattner** [comment]
Yes, completely agreed.  `OperandUtterance` is even more specific (but no, we shouldn't use that :)  because it really is about a lexical occurrence of an operand reference like `%y` or `%x#4`.

**Comment by zero9178** [comment]
Patch candidate: https://reviews.llvm.org/D122142

**Comment by silvasean** [comment]
Thanks for the quick turnaround time on this @zero9178 !! Really impressive :)
