### ISSUE TITLE
End Users Who Use Termux Desire LLVM

### ISSUE THREAD

**Issue by SDRausty** [llvm/llvm-project#54452]
Since 2015 users who use their smartphones as computers via Termux app have desired LLVM:

[Package]: ipv6calc
https://github.com/termux/termux-packages/issues/9440
[Bug]: clang-13 cannot cross compile
https://github.com/termux/termux-packages/issues/9308
[Bug]: apt install doesnt work but pkg install works
https://github.com/termux/termux-packages/issues/9204
Is lfortran package working?
https://github.com/termux/termux-packages/issues/8884
[Bug]: lldb unable to launch process
https://github.com/termux/termux-packages/issues/8880
[Package]: gnat-llvm
https://github.com/termux/termux-packages/issues/8823
[Package]: lfortran
https://github.com/termux/termux-packages/issues/8822
[Package]: tinygo
https://github.com/termux/termux-packages/issues/8819
[Bug]: pip install failed
https://github.com/termux/termux-packages/issues/8557
[Bug]: pulseaudio won't compile, invalid directory (github action)
https://github.com/termux/termux-packages/issues/8248
LLVM: Add support for other experimental backend
https://github.com/termux/termux-packages/issues/8194
[Bug]: clang: ld: command not found
https://github.com/termux/termux-packages/issues/8191
[Bug]: Failed to compile matplotlib 3.5.0 on aarch64, because of false TERMUX_BUILD_TUPLE
https://github.com/termux/termux-packages/issues/8183
[Bug]: swift cannot locate symbyol '_Unwind_Resume'
https://github.com/termux/termux-packages/issues/8130
[Bug]:
https://github.com/termux/termux-packages/issues/8037
[Bug]: Several configure&make packages give binaries with cannot locate symbol "__extendsftf2"
https://github.com/termux/termux-packages/issues/8029
[Bug]: WARNING: linker: Warning: unable to normalize ""
https://github.com/termux/termux-packages/issues/7968
Some LLVM tools are missing
https://github.com/termux/termux-packages/issues/7952
[Bug]: CANNOT LINK EXECUTABLE "cc": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"... Aborted
https://github.com/termux/termux-packages/issues/7945
[Bug]: i686 clang is broken when compiling code
https://github.com/termux/termux-packages/issues/7938
argon2-cffi fail while installing jupyter
https://github.com/termux/termux-packages/issues/7925
[Bug]: Rust cannot be executed when libllvm is upgraded to 13.0
https://github.com/termux/termux-packages/issues/7851
[Bug]: ModuleNotFoundError: No module named 'symbol'
https://github.com/termux/termux-packages/issues/7832
[Bug]: cmake does not work
https://github.com/termux/termux-packages/issues/7831
[Bug]: clang is broken
https://github.com/termux/termux-packages/issues/7788
[Bug]: Linker seems to be broken in Android 12
https://github.com/termux/termux-packages/issues/7382
Compiling with arm-linux-androideabi-clang instead of just clang creates an executable that gives runtime error
https://github.com/termux/termux-packages/issues/7232
Using clang --coverage option does not produce gcda data file after executing the object file
https://github.com/termux/termux-packages/issues/6998
Can't import function 'link' from module 'os'
https://github.com/termux/termux-packages/issues/6976
CMake C compiler ABI detection fails with GCC
https://github.com/termux/termux-packages/issues/6960
emcc: unable to find python in $PATH
https://github.com/termux/termux-packages/issues/6951
LibLLVM-11.so not found error of rust nightly from unstable repo
https://github.com/termux/termux-packages/issues/6849
Cross compiling termux package on Ubuntu: mv: cannot move '/home/harieamjari/.termux-build/_cache/android-r21d-api-24-v4-tmp' to '/home/harieamjari/.termux-build/_cache/android-r21d-api-24-v4': Permission denied
https://github.com/termux/termux-packages/issues/6831
Please add pkg GCC I have clang but it's not useful
https://github.com/termux/termux-packages/issues/6820
rust 1.51.0 and llvm 11.1.0 conflict
https://github.com/termux/termux-packages/issues/6652
Could you please help enable 'RTTI' feature for LLVM?
https://github.com/termux/termux-packages/issues/6471
How to install 'LLVMPolly.so' with LLVM 11.0.0?
https://github.com/termux/termux-packages/issues/6442
clang++ can't compile code using <filesystem> or <experimental/filesystem>
https://github.com/termux/termux-packages/issues/6275
[Question] Build llvm and clang for termux from source
https://github.com/termux/termux-packages/issues/6257
"libLLVM-10.so" not found on rustc-nightly 1.47
https://github.com/termux/termux-packages/issues/6180
Regarding libomp
https://github.com/termux/termux-packages/issues/6145
ghc-pkg: library "libncursesw.so.6" not found
https://github.com/termux/termux-packages/issues/6092
Package request: mingw-w64
https://github.com/termux/termux-packages/issues/6027
Add ghci
https://github.com/termux/termux-packages/issues/5973
pip install matplotlib always crashes
https://github.com/termux/termux-packages/issues/6225
Postgres 13 can't start
https://github.com/termux/termux-packages/issues/5956
LLVMPolly.so missing from package LLVM
https://github.com/termux/termux-packages/issues/5829
matplotlib 3.3.1 does not build with python 3.8.5 and pip
https://github.com/termux/termux-packages/issues/5787
GDBserver libthread_db dependency
https://github.com/termux/termux-packages/issues/5784
Make ./build-package.sh download and not build from source dependencies by default?
https://github.com/termux/termux-packages/issues/5760
Pandas installation error via pip
https://github.com/termux/termux-packages/issues/5744
Luarocks bugs
https://github.com/termux/termux-packages/issues/5585
Clang upgrade with clangd already installed fails
https://github.com/termux/termux-packages/issues/5550
Clang-10 error PGO
https://github.com/termux/termux-packages/issues/5539
libLLVM-9.so not found on packages ccls
https://github.com/termux/termux-packages/issues/5527
rustc-nightly breaks with latest update of libllvm
https://github.com/termux/termux-packages/issues/5519
clang_10.0.0_aarch64.deb upgrade problem
https://github.com/termux/termux-packages/issues/5506
[Package request] clang-tools-extra
https://github.com/termux/termux-packages/issues/5483
texlive-full package "deadlock" situation, how to recover...
https://github.com/termux/termux-packages/issues/5430
Package request: include-what-you-use
https://github.com/termux/termux-packages/issues/5382
Package request: clang-tidy
https://github.com/termux/termux-packages/issues/5381
Package request: deno
https://github.com/termux/termux-packages/issues/5306
Compiling llvmlite causes Segmentation fault
https://github.com/termux/termux-packages/issues/5170
New Package Request: emsdk
https://github.com/termux/termux-packages/issues/5043
latest clangd's version is 9.0.1 which depends on libllvm 9.0.1, but current version of libllvm is 9.0.1-1
https://github.com/termux/termux-packages/issues/5014
Linker segfaults on arm
https://github.com/termux/termux-packages/issues/4987
libLLVMDemangle.a does not exist.
https://github.com/termux/termux-packages/issues/4791
ziglang
https://github.com/termux/termux-packages/issues/4760
Rust to wasm process?
https://github.com/termux/termux-packages/issues/4696
Segmentation Fault While building libllvm on Docker
https://github.com/termux/termux-packages/issues/4694
Can't link against libexslt
https://github.com/termux/termux-packages/issues/4638
Build-essential Clang-9.0.0 bug?
https://github.com/termux/termux-packages/issues/4621
rust is borked
https://github.com/termux/termux-packages/issues/4613
golang can not build deb package
https://github.com/termux/termux-packages/issues/4530
Package request: GNU libjit
https://github.com/termux/termux-packages/issues/4928
Package yasm is broken
https://github.com/termux/termux-packages/issues/4497
Package request : ccls
https://github.com/termux/termux-packages/issues/4417
ffmpeg with --enable-libdav1d
https://github.com/termux/termux-packages/issues/4412
Rust 1.38.0
https://github.com/termux/termux-packages/issues/4324
-masm=intel doesn't work in clang
https://github.com/termux/termux-packages/issues/4288
Consider building llvm with RTTI
https://github.com/termux/termux-packages/issues/4257
LLVM static libraries missing
https://github.com/termux/termux-packages/issues/4159
PyStan
https://github.com/termux/termux-packages/issues/4085
Clang 8.0.0-2 generating crashing programs
https://github.com/termux/termux-packages/issues/3990
Cross-Compiling with Clang to other android archs?
https://github.com/termux/termux-packages/issues/3804
Package request: flang
https://github.com/termux/termux-packages/issues/3719
32-bit Clang defaults to ARMv4t.
https://github.com/termux/termux-packages/issues/3686
Wrong metadata version in rust-std-wasm32
https://github.com/termux/termux-packages/issues/3670
lldb out of sync with llvm
https://github.com/termux/termux-packages/issues/3630
[Regression] libunwind.8 linker error at launching any new compiled binary
https://github.com/termux/termux-packages/issues/3580
Outdated rust
https://github.com/termux/termux-packages/issues/3534
Aria2c segfaults
https://github.com/termux/termux-packages/issues/3435
Package request: Crystal
https://github.com/termux/termux-packages/issues/3401
Package Request: Nightly Rust
https://github.com/termux/termux-packages/issues/3122
Arm and libatomic
https://github.com/termux/termux-packages/issues/3092
Pip Install Pandas 0.23.4 on Python 3.7
https://github.com/termux/termux-packages/issues/3012
error: command 'aarch64-linux-android-clang' failed with exit status 254
https://github.com/termux/termux-packages/issues/3005
Missing licenses (& manpages)
https://github.com/termux/termux-packages/issues/2901
Discussion: dropping android 5&6 support
https://github.com/termux/termux-packages/issues/2874
Jack Compiler
https://github.com/termux/termux-packages/issues/2812
Package request: nlopt
https://github.com/termux/termux-packages/issues/2647
package request: GCC
https://github.com/termux/termux-packages/issues/2511
Package request: arm embedded toolchain
https://github.com/termux/termux-packages/issues/2482
[package request] Cling
https://github.com/termux/termux-packages/issues/2418
libclang_rt.asan-aarch64-android.so is missing.
https://github.com/termux/termux-packages/issues/2403
Compile kernel with libllvm
https://github.com/termux/termux-packages/issues/2396
package request: ccons
https://github.com/termux/termux-packages/issues/2328
RFE: build llvm / clang / lld / openmp with separate build scripts
https://github.com/termux/termux-packages/issues/2282
can't compile berkeley-db with cxx support
https://github.com/termux/termux-packages/issues/2273
Rounding errors in python
https://github.com/termux/termux-packages/issues/2236
How to install pandas
https://github.com/termux/termux-packages/issues/2231
Issues on libllvm packaging
https://github.com/termux/termux-packages/issues/2154
package request: OpenMP
https://github.com/termux/termux-packages/issues/2139
gcc/clang compatibility with AndroidStudio
https://github.com/termux/termux-packages/issues/2045
Installing opencv-python
https://github.com/termux/termux-packages/issues/1992
Package Request: clang-format
https://github.com/termux/termux-packages/issues/1961
rustc fails when running on Chromebook.
https://github.com/termux/termux-packages/issues/1745
newsboat generates "default.profraw"
https://github.com/termux/termux-packages/issues/1672
Can't build botan
https://github.com/termux/termux-packages/issues/1671
pforth segmentation fault
https://github.com/termux/termux-packages/issues/1617
Package request wine
https://github.com/termux/termux-packages/issues/1423
libc++ cmath math functions not found because of -isystem $PREFIX/include added by CMake
https://github.com/termux/termux-packages/issues/1149
ffmpeg not redistributable
https://github.com/termux/termux-packages/issues/1087
Build clang
https://github.com/termux/termux-packages/issues/882
libllvm does not create a native llvm-config
https://github.com/termux/termux-packages/issues/879
libclang_rt.profile-aarch64-android.a
https://github.com/termux/termux-packages/issues/857
Anyone managed to install python numba ?
https://github.com/termux/termux-packages/issues/845
Package request : cling
https://github.com/termux/termux-packages/issues/834
perl sysroot set to /home/fornwall/...
https://github.com/termux/termux-packages/issues/787
Missing gfortran?
https://github.com/termux/termux-packages/issues/702
llvm-libunwind and lldb v3.9 packages
https://github.com/termux/termux-packages/issues/639
binutils: unable to link command-not-found.c
https://github.com/termux/termux-packages/issues/565
Package request: libc-avr and avr-gcc
https://github.com/termux/termux-packages/issues/561
Package Request: scipy for python
https://github.com/termux/termux-packages/issues/471
llvm-dev package
https://github.com/termux/termux-packages/issues/467
clang and libatomic: another issue
https://github.com/termux/termux-packages/issues/430
Unable to compile Python 3 for aarch64
https://github.com/termux/termux-packages/issues/356
Unable to compile Python 2 for aarch64
https://github.com/termux/termux-packages/issues/355
clang update may have broken something to do with atomic
https://github.com/termux/termux-packages/issues/282
Package request: Rust and Cargo
https://github.com/termux/termux-packages/issues/261
Package Request: R (r-base)
https://github.com/termux/termux-packages/issues/250
package proposal: llvm
https://github.com/termux/termux-packages/issues/149
Can not update using apt
https://github.com/termux/termux-packages/issues/99
Package request: ghc (Glasgow Haskell Compiler)
https://github.com/termux/termux-packages/issues/80
clang requires libgcc from the gcc package to compile anything
https://github.com/termux/termux-packages/issues/72
Package request: ldc
https://github.com/termux/termux-packages/issues/71
Build Android apps from termux?
https://github.com/termux/termux-packages/issues/63
Package request: julia
https://github.com/termux/termux-packages/issues/58

[I have found myself in a bit of a bind with Termux curators](https://github.com/termux/termux-packages/issues/8758) by stating since 2016 that many programs do work.  While some of them state these programs simply do not work.

[TermuxArch](https://github.com/TermuxArch/TermuxArch) uses Termux PRoot and enables using LLVM on Android handheld smartphone and much more.  Many of these issues deal with native Termux that Termux would like to support, but cannot as LLVM still does not work in native Termux;  Can LLVM be made available for native Termux users?

**Comment by SDRausty** [comment]
The motivation is simple:

Root your Android handheld instead of granting Android app privilages logic enforced via bans at Termux along with intimidation.

**Comment by nikic** [comment]
Can you please be more precise in what *exactly* is needed to resolve this issue? It is not actionable in the current form.

**Comment by SDRausty** [comment]
>please be more precise in what exactly is needed to resolve this issue?

Thank you for asking @nikic; [an LLVM packaged for Termux here](https://github.com/termux/termux-packages/pulls) as far as I know.  I am fine with how LLVM works in [TermuxArch](https://github.com/TermuxArch).  A big thank you to the LLVM team;  Great job! Keep up the fine work!

However, Termux users desire a native package.   Does this answer answer your question in full?

**Comment by Yonle** [comment]
Anda menciptakan lawakan yang membuat satu komunitas menertawaimu, kawan.

*Go. Translate ahead*

**Comment by Yonle** [comment]
@nikic, This issue is opened because he person (which is @SDRausty) is banned in @Termux org due to nonsense comment that advertising TermuxArch in wrong place, especially in PR. 

The following image is from another user that involved in this conflic:
![image](https://gitter.ems.host/_matrix/media/v1/download/matrix.org/UPMAOnojkDYPVUaoTUcXhoEq)

Please, Close and lock this issue as it's well completely full of nonsenses.

**Comment by Yonle** [comment]
Some note @SDRausty, Without LLVM, Termux, proot in android, or even your TermuxArch won't even exist. 

## What is Termux?
The following information is **False**:
> Root/crack your Android handheld instead of granting Android app privilages logic enforced via bans and locks at Termux along with intimidation.

Termux is a Terminal Emulator for Android with a package manager called `apt` (with `pkg` as `apt` handler). And they're never focused for pentesting.

**Comment by SDRausty** [comment]
One of the reasons that I have created this issue here is the issues mentioned in the first message and this comment by former Termux curator @xeffyr whose account seems to have been ghosted for possessing multiple accounts at GitHub imitating multiple users judging by the self talk of the now ghost account at Termux:

[> Literally same issue as with rustup. Those installers aren't working with custom distributions. They are pretty much useless unless have added upstream support for Termux and supply compatible toolchain binaries.](https://github.com/termux/termux-packages/issues/8758#issuecomment-1021600273_)

And also this comment here:
[> Termux needs binaries compiled for termux and linked against android's libc. GHCup-hs (and rustup, and tlmgr, and ...) doesn't provide binaries for termux, so no, I don't see any way that this package can work](https://github.com/termux/termux-packages/issues/8758#issuecomment-1046263979_)

**Comment by Yonle** [comment]
As the reason of why this person getting banned from @termux org, See https://github.com/termux/termux-packages/issues/202#issuecomment-1072972799 comment

**Comment by SDRausty** [comment]
>Without LLVM, Termux, proot in android, or even your TermuxArch won't even exist.

LLVM has nothing to do with PRoot in order to run. 
It does enable LLVM, and much more!  It does enable LLVM on Android handheld device.  

[Termux PRoot](https://github.com/termux/proot) is standalone program that is written in C xhich easily compiles in native Termux.  What Termux PRoot does with tweeks is simple amazing, "The power of Linux in the palm of your hand, anywhere that you can take an Android smartphone!"

**Comment by Yonle** [comment]
> >Without LLVM, Termux, proot in android, or even your TermuxArch won't even exist.
> 
> LLVM has nothing to do with Termux PRoot in order to run.  It does enable LLVM inside the PRoot computer environment, and much more!  It enables LLVM on Android handheld device in a fakeroot chroot like environment.
> 
> [Termux PRoot](https://github.com/termux/proot) is a standalone program that is [written in C which easily compiles in native Termux](https://github.com/SDRausty/termux-archlinux/blob/master/taprootuserland.bash).  What Termux PRoot does with tweeks is simple amazing, "The power of Linux in the palm of your hand, anywhere that you can take an Android smartphone!"

And do we really focus on proot development in Termux?
**Think twice of what do you do.** It also seems like that you're not accepting the reason of getting banned in @termux org in any way.

**Comment by Yonle** [comment]
> The power of Linux in the palm of your hand, anywhere that you can take an Android smartphone!

First of all, Do you know what are you doing?

**Comment by SDRausty** [comment]
> > The power of Linux in the palm of your hand, anywhere that you can take an Android smartphone!
> 
> First of all, Do you know what are you doing?

Granting requests and prospering with mine as best as we possibly can!  How about you?

**Comment by Yonle** [comment]
> > > The power of Linux in the palm of your hand, anywhere that you can take an Android smartphone!
> > 
> > First of all, Do you know what are you doing?
> 
> Assisting in granting requests, granting requests, and prospering with mine as best as we possibly can!  How about you?

Watching what in the world was happening. Are you amnesia?

**Comment by Yonle** [comment]
From now on i'm gonna leave this issue alone as is. It's all weird and brutally funny at the same time.

**Comment by nunoplopes** [comment]
Guys, this report is a mess. I'm closing it.
Please file individual bug reports for each issue in **LLVM**. We do not provide packages for any distribution FYI. Packaging is done by downstream developers.

**Comment by SDRausty** [comment]
>Packaging is done by downstream developers.

Sound like a clear and fine answer to me.  Thank you for taking the time to review this topic @nunoplopes.

**Comment by SDRausty** [comment]
https://github.com/agnostic-apollo/agnostic-apollo/issues/1
