### ISSUE TITLE
Please move lldb-mi back to llvm main project.

### ISSUE THREAD

**Issue by kgfly** [llvm/llvm-project#54453]
(In the past, lldb-mi was a part of llvm main project.)

Debugger, such as vs code, Eclipse CDT depends on lldb-mi, https://github.com/lldb-tools/lldb-mi.

However, https://github.com/lldb-tools/lldb-mi does not even have enough maintainers. Etc it's in a bad shape. It cannot even build on Ubuntu 20 LTS, which is most popular Linux dist.
https://github.com/lldb-tools/lldb-mi/issues/90
https://github.com/lldb-tools/lldb-mi/issues/92

That's end up very bad user experience for Linux user when using llvm.

On Linux, Gcc is definitely the bottom line for most developer.

And, IMO, most of dev cannot survive without debugger.

So if llvm group want llvm be popular on Linux, if they want people choose llvm over gcc, please move lldb-mi back to llvm main project and make it a good sharp.

Thanks.

**Comment by kgfly** [comment]
lldb-mi does not even have an install package. People have to build it on their own, which is failing and really frustrating.

**Comment by JDevlieghere** [comment]
`lldb-mi` being unmaintained is exactly the reason it was moved out of llvm-project. Moving it back won't magically change that. What the tool really needs is people who want to make it better and are willing to invest their time to make that happen.

**Comment by kgfly** [comment]
Sounds good.

We the people will use GCC tool chain for now.
