### ISSUE TITLE
Please backport 268371cf7b9f6fd3b9320564f1abd3615eecd2e8 and 4eb59f017903c8b70b5c5aad892bdc73516a6766 to llvm 14 branch

### ISSUE THREAD

**Issue by topperc** [llvm/llvm-project#54461]
I believe this bug exists in llvm 13 as well and hadn't been found before now. So I think it can wait till llvm 14.0.1 since we're late for 14.0.0.

268371cf7b9f6fd3b9320564f1abd3615eecd2e8 adds a test
4eb59f017903c8b70b5c5aad892bdc73516a6766 adds the fix

**Comment by asb** [comment]
Just to be explicit - this definitely makes sense to backport from my perspective. Thanks Craig.

**Comment by tstellar** [comment]
/cherry-pick 268371cf7b9f6fd3b9320564f1abd3615eecd2e8 4eb59f017903c8b70b5c5aad892bdc73516a6766

**Comment by tstellar** [comment]
Merged: add3ab7f4c8a 3f43d803382d e9b26b5b2a70 5b9dd016bec7
