### ISSUE TITLE
[CodeGen] missing MachineOperand::ChangeToCImmediate

### ISSUE THREAD

**Issue by uaex** [llvm/llvm-project#54466]
MachineOperand has `ChangeToImmediate` and `ChangeToFPImmediate`, but `ChangeToCImmediate` is not found.

implementation like:
```
void MachineOperand::ChangeToCImmediate(const ConstantInt *CImm, unsigned TargetFlags) {
  assert((!isReg() || !isTied()) && "Cannot change a tied operand into an imm");

  removeRegFromUses();
  
  OpKind = MO_CImmediate;
  Contents.CI = CImm;
  setTargetFlags(TargetFlags);
}
```

**Comment by fhahn** [comment]
@uaex are there any potential in-tree users?

**Comment by uaex** [comment]
`ChangeToImmediate` will lose type info for the reg from G_CONSTANT.
Now I use Desc to indicate it, `ChangeToImmediate` still works well.

**Comment by fhahn** [comment]
> ChangeToImmediate will lose type info for the reg from G_CONSTANT.
> Now I use Desc to indicate it, ChangeToImmediate still works well.

Ok, so can this issue be closed?
