### ISSUE TITLE
[flang][OpenMP][omp2012] Failure in building omp2012 due to no implementation of OpenMPThreadprivate

### ISSUE THREAD

**Issue by NimishMishra** [llvm/llvm-project#54474]
**Note**: This issue can be reproduced from the monorepo once the upstream from [fir-dev](https://github.com/flang-compiler/f18-llvm-project/tree/fir-dev) has matured. The actual issue came up while building omp2012 with the current state of LLVM flang (lowering enabled)

The following source dumps core with `flang-new -fopenmp -c -o rtc02.o rtc02.f`:
```
! FAIL: flang-new -fopenmp -c -o rtc02.o rtc02.f

      SUBROUTINE rtc02
	double precision var_1, var2
	common/var/var_1,var_2
!$omp threadprivate (/var/)
      RETURN
      END

```

Core dumps as 

```
error: loc("./rtc02.f":3:7): /f18-llvm-project/flang/lib/Lower/OpenMP.cpp:885: 
not yet implemented OpenMPThreadprivate
```

**Comment by PeixinQiao** [comment]
This will be supported by https://github.com/flang-compiler/f18-llvm-project/pull/1135, which is under review.

**Comment by NimishMishra** [comment]
Verified. This issue is no longer observed while building omp2012. Thanks @PeixinQiao
