### ISSUE TITLE
[flang][OpenMP][omp2012] Privatization failed due to existing binding while building omp2012

### ISSUE THREAD

**Issue by NimishMishra** [llvm/llvm-project#54473]
**Note**: This issue can be reproduced from the monorepo once the upstream from [fir-dev](https://github.com/flang-compiler/f18-llvm-project/tree/fir-dev) has matured. The actual issue came up while building omp2012 with the current state of LLVM flang (lowering enabled)

The following source dumps core with `flang-new -ffree-form -fopenmp -c -o rtc01.o rtc01.f`:

```
! FAIL: flang-new -ffree-form -fopenmp -c -o rtc01.o rtc01.f

PROGRAM rtc01
  INTEGER k
  INTEGER, PARAMETER :: limit=100
 
!$OMP PARALLEL DO PRIVATE(k)
        do k=2,limit
        enddo
!$OMP END PARALLEL DO
END PROGRAM
```

Core dumps as

```
flang-new: f18-llvm-project/flang/lib/Lower/OpenMP.cpp:58: 
void createPrivateVarSyms(Fortran::lower::AbstractConverter&, const T*) 
[with T = Fortran::parser::OmpClause::Private]: Assertion `success && "Privatization failed due to existing binding"' failed.
```

**Comment by kiranchandramohan** [comment]
If you check out the commit before https://github.com/flang-compiler/f18-llvm-project/commit/1a3ec76bd6a93d2ba3adca56b5aa12e244862b9b, does it work?

**Comment by NimishMishra** [comment]
> If you check out the commit before [flang-compiler@1a3ec76](https://github.com/flang-compiler/f18-llvm-project/commit/1a3ec76bd6a93d2ba3adca56b5aa12e244862b9b), does it work?

Yes. It is working then.

**Comment by NimishMishra** [comment]
@kiranchandramohan I am still observing this issue while building omp2012. Any chance that https://github.com/flang-compiler/f18-llvm-project/commit/fa2883ff6a2fa36fd42a2bb85c565711709d2c05 has not been upstreamed yet?

**Comment by kiranchandramohan** [comment]
It is in review, has a parent patch. https://reviews.llvm.org/D127249

**Comment by kiranchandramohan** [comment]
@NimishMishra I just submitted this patch (https://reviews.llvm.org/D127249). Could you check again?

**Comment by NimishMishra** [comment]
@kiranchandramohan Thank you. This issue no longer exists.
