### ISSUE TITLE
[flang][OpenMP][omp2012] Failure in building omp2012: parse tree node not analysed when using threadprivate

### ISSUE THREAD

**Issue by NimishMishra** [llvm/llvm-project#54477]
**Note**: This issue can be reproduced from the monorepo once the upstream from [fir-dev](https://github.com/flang-compiler/f18-llvm-project/tree/fir-dev) has matured. The actual issue came up while building omp2012 with the current state of LLVM flang (lowering enabled)

The following source dumps core with `flang-new -fopenmp -c -o rtc03.o rtc03.f`

```
! FAIL: flang-new -fopenmp -c -o rtc03.o rtc03.f
      subroutine rt03(n)
      
      integer n
      double precision var_1(64), var_2(64)
      common /var/ var_1, var_2
!$omp threadprivate(/var/)

      var_1(n) = 0.2
      return
      end
```

Core dumps as 

```
fatal internal error: node has not been analyzed:
Expr -> LiteralConstant -> RealLiteralConstant
| Real = '0.2'
```

**Comment by PeixinQiao** [comment]
This has nothing to do with threadprivate directive. It is the problem of resolving statement function when openmp is enabled (https://github.com/flang-compiler/f18-llvm-project/blob/084e820fd61f1d2c33f60e9cb6c99ecf2d6a21f2/flang/lib/Semantics/resolve-directives.cpp#L284). This should be the same problem as https://github.com/llvm/llvm-project/issues/54161 and https://github.com/llvm/llvm-project/issues/54163.

**Comment by kiranchandramohan** [comment]
If reverting [D93213](https://reviews.llvm.org/D93213) fixes these and similar issues then please go ahead and do it and file a ticket for implementing the semantic check implemented in D93213.
