### ISSUE TITLE
clang pretty stack dumps don't frequently point at a useful location in the source

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5448]
|  |  |
| --- | --- |
| Bugzilla Link | [5076](https://llvm.org/bz5076) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Many IRgen crashes end up just pointing at the end of the file, probably because of deferred code generation. We should do a better job of pointing at the thing we are generating code for. This probably just means dropping a few more well placed PrettyStackTrace calls into IRgen.

**Comment by gwelymernans** [comment]
This is too vague to be actionable. Also, I don't think the current crash information that's dumped has this issue.
