### ISSUE TITLE
backport d2b4a675a8f9 and 98e22744580a to llvm14

### ISSUE THREAD

**Issue by yonghong-song** [llvm/llvm-project#54482]
Requests to back the following two commits to llvm14:

(1). 
commit 98e22744580ab9a7df6a72034e5ff30b42591e65
Author: Yonghong Song <yhs@fb.com>
Date:   Sun Mar 13 22:30:45 2022 -0700

    [BPF] fix a CO-RE bitfield relocation error with >8 record alignment

(2).
commit d2b4a675a8f9895eb06eec8a963c11a84d04ed03
Author: Yonghong Song <yhs@fb.com>
Date:   Wed Mar 16 23:24:15 2022 -0700

    [BPF] Fix a bug in BPFAdjustOpt pass for icmp transformation

**Comment by yonghong-song** [comment]
cc @4ast

**Comment by yonghong-song** [comment]
The full link: https://github.com/yonghong-song/llvm-project/commits/r14-2

**Comment by mgorny** [comment]
@yonghong-song, thanks for the clean backports. It's unfortunate they haven't made it to 14.x after all but I'm going to backport them to Gentoo.

**Comment by nikic** [comment]
Closing this, as the LLVM 14 release is done and these are in LLVM 15.
