### ISSUE TITLE
[clang-format]  [] in template causing indentionation issues

### ISSUE THREAD

**Issue by mydeveloperday** [llvm/llvm-project#54497]
I think a recent change to handling [] in templates is causing indentation problems

clang-format-12

```c
template <typename T> class Foo {
private:
  std::unique_ptr<const T *[]> m_conn;

public:
  const T *const *m_impl;

  explicit Foo() {}
};
```

clang-format version 15.0.0 (https://github.com/llvm/llvm-project.git 51ba13b1aea3d6e04310b80b6bcfc641049b9890)
```c
template <typename T> class Foo {
private:
  std::unique_ptr<const T *[]> m_conn;

      public : const T *const * m_impl;

      explicit Foo() {}
};
```

**Comment by mkurdej** [comment]
Ay, bisecting shows that it's probably caused by my commit https://github.com/llvm/llvm-project/commit/126b37a7.

**Comment by mkurdej** [comment]
FYI:

`clang-format-main-20220314-2507e0a2.exe --style=file test.cpp`:
```
template <typename T> class Foo {
private:
  std::unique_ptr<const T *[]> m_conn;

public:
  const T *const *m_impl;

  explicit Foo() {}
};
```

`clang-format-main-20220315T1133-126b37a7.exe --style=file test.cpp`:
```
template <typename T> class Foo {
private:
  std::unique_ptr<const T *[]> m_conn;

      public : const T *const * m_impl;

      explicit Foo() {}
};
```

**Comment by aeubanks** [comment]
I attempted to update clang-format and ran into this. Leaving clang-format at head in this state isn't great given that this sort of code is not uncommon, any chance this could get looked at?

**Comment by brunowonka** [comment]
I believe I'm hitting that with the following code (snippet formatted by clangd):
```
std::unique_ptr<BufferParts<buffer_region_t>[]> buffer_parts(
      new (&ac) BufferParts<buffer_region_t>[capacity]);
      if (!ac.check()) { return zx::error(ZX_ERR_NO_MEMORY); } for (uint32_t i = 0; i < capacity;
                                                                    i++) {
        tx_buffers[i].data_list = buffer_parts[i].data();
      }
```

If I extract the type parameter out like so:
```
using BufferParts_t = BufferParts<buffer_region_t>[];
std::unique_ptr<BufferParts_t> buffer_parts(new (&ac) BufferParts<buffer_region_t>[capacity]);
```

it seems to go back to normal.

(I'm on the fuchsia prebuilt)
```
$ clang-format --version
Fuchsia clang-format version 15.0.0 (https://llvm.googlesource.com/a/llvm-project 
902f4708fe1d03b0de7e5315ef875006a6adc319)
```

**Comment by aeubanks** [comment]
Thanks for reverting, these issues are no longer at clang-format head.
