### ISSUE TITLE
mmap() addr error through orc jit

### ISSUE THREAD

**Issue by profdevc** [llvm/llvm-project#54494]
for an example code:
```
#include <stdint.h>
#include <cstdio>
#include <unistd.h>
#include <sys/mman.h>
#include <fcntl.h>
int main(){
  uint64_t* p;
  p = (uint64_t*)0x750000;
  printf("p addr: %p\n", p);
  uint64_t* ptr = static_cast<uint64_t*>(mmap((void*)p, 8192, PROT_READ | PROT_WRITE,
                   MAP_PRIVATE | MAP_ANON, -1, 0));
  printf("ptr addr: %p\n", ptr);
  printf("%d\n",ptr==p);
  printf("brk mmap error:%d\n", errno);
  munmap((void*)ptr, 8192);
  return 0;
}
```
if compile through clang/gcc and run it, it will show the output
```
p addr: 0x750000
ptr addr: 0x750000
1
brk mmap error:29
```
but when run it through orcjit (just like [KaleidoscopeJIT.h](https://github.com/llvm/llvm-project/blob/main/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h) and llvm version >=13), output is like
```
p addr: 0x750000
ptr addr: 0xffff74380000
0
brk mmap error:0
```
for given addr for mmap(), the return addr should be the same. But seems in orcjit, the mmap() work at a random address but not the given address.
if this is a bug?and whether there are solutions to fixed it or other alternative solutions. I'm trying to use the code to implement brk(), and error occurs on both x86_64 and aarch64. Hope for help

**Comment by profdevc** [comment]
> You're not passing `MAP_FIXED` to mmap. My understanding is that without `MAP_FIXED` the addr argument is just a hint, in which case the JIT's result is expected (mmap just didn't use the hint, and allocated memory at some other address).
> 
> It's not relevant to the JIT, but out of interest -- do you know why mmap is returning `29` in the precompiled case? What does strerror report?

thanks for your comment. for add MAP_FIXED, the return addr is right. For test of comparsion with MAP_FAILED, it is right. but there is still errno, do you have any idea about it? and I have no idea why the same usage in compiler right but in jit errno.
```
#include <stdint.h>
#include <string.h>
#include <cstdio>
#include <unistd.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <errno.h>
int main(){
  uint64_t* p;
  p = (uint64_t*)0x750000;
  void* a = (void*)p;
  printf("p addr: %p\n", p);
  uint64_t* ptr = static_cast<uint64_t*>(mmap(p, 8192, PROT_READ | PROT_WRITE, MAP_FIXED | MAP_PRIVATE | MAP_ANONYMOUS, -1, 0));
  printf("ptr addr: %p\n", ptr);
  printf("%d\n", ptr == MAP_FAILED);
  printf("%d\n",ptr==p);
  printf("brk mmap error:%s\n", strerror(errno));
  munmap((void*)ptr, 8192);
  return 0;
}
```
output through clang
```
p addr: 0x750000
ptr addr: 0x750000
0
1
brk mmap error:Success
```
output through jit
```
p addr: 0x750000
ptr addr: 0x750000
0
1
brk mmap error:Illegal seek
```
(Illegal seek is the same as error code 29 from [errno.h](https://zh.wikipedia.org/wiki/Errno.h))

**Comment by lhames** [comment]
Assuming that `errno` is 29 before the call you could trace it back to whatever operation failed, but also might not matter for your use case.

Going back to your original comment, that you were trying to implement `brk()` -- Could you explain your motivation for that? Why JIT an implementation of `brk()`?

**Comment by profdevc** [comment]
> Hi @profdevc. If mmap returns a success value it probably doesn't set `errno` at all, in which case that illegal seek value is from an earlier operation.
> 
> What is the value of `errno` before the `mmap` call in both cases?

I tried it and the output indeed is errno 29 at the begin of main(). In this case, there should be no error in mmap through JIT. But why there's errno at the begin. I'm not familiar with errno

**Comment by profdevc** [comment]
> Assuming that `errno` is 29 before the call you could trace it back to whatever operation failed, but also might not matter for your use case.
> 
> Going back to your original comment, that you were trying to implement `brk()` -- Could you explain your motivation for that? Why JIT an implementation of `brk()`?

In fact, our team just want to use JIT to accelerate our project, and implemention of `brk()` is just part of project. One of our leaders told us that JIT can accelerate programs. but yesterday, I have run the program through JIT successfully, the speed is the same as through clang/gcc in error permissible. I hadn't thought about his words before, and I am confused of it now. The JIT seems didn't say that the speed could be faster, but it always says there are advantages compared to static compiler. So could the so-called advantages showed in the program speed? Maybe we need to add other optimizations to JIT that can achieve our goal? Or JIT can accelerate some specific program? Or maybe there has never been a function of accelerating the program through JIT. Seems the LLVM JIT document didn't give info about this. And now I think the problem should be the same to all JIT but not only LLVM JIT. 
Do you have any idea about the question? Maybe someone or academic papers have discussed with the question ago

**Comment by profdevc** [comment]
> Assuming that `errno` is 29 before the call you could trace it back to whatever operation failed, but also might not matter for your use case.
> 
> Going back to your original comment, that you were trying to implement `brk()` -- Could you explain your motivation for that? Why JIT an implementation of `brk()`?

I have talk about the question with my collaborators. I misunderstanded the function of JIT and the condition the JIT suit for. Maybe the errno 29 occur in my JIT code. I'll close the issue.

**Comment by profdevc** [comment]
> Thank you for closing the issue @profdevc.
> 
> > I misunderstanded the function of JIT and the condition the JIT suit for.
> 
> The LLVM JIT's primary purpose is to allow us to dynamically load code from a static compiler. It is useful when parts of the program (e.g. expressions in LLDB or the clang-REPL) need to be compiled at runtime. If your program changes very frequently you might also benefit from running it under the JIT because you won't necessarily have to compile the whole program every time.
> 
> In theory JIT'd code can outperform statically compiled code if dynamic information about program performance is used to optimize the underlying code. In practice we do not do this at the moment, and probably won't for some time yet. We're currently focused on emulating the underlying object runtime environments (for COFF, ELF and MachO), and improving basic lazy compilation.

Thank you for your explanation of JIT.  
By the way, I have another little problem. yesterday I find that the commit [1e16272](https://github.com/llvm/llvm-project/commit/1e16272ba793e5a6e7308898ecf6ef0dc99e2ad3) you push days ago. In my program, when using OptimizeLayer, the speed is as the same as clang, but for the change to CODLayer, the speed is six to eight times slower. This problem should be a new issue, but as I don't master at the class about JIT and the association among each layer, I'm not sure the real reason of the phenomenon. Our project is complex and I think the speed is persuasive. In my future work, we will work with LLJIT/LLazyJIT class but not like KaleidoscopeJIT. So, that's just a remind. You can check out the example code. Hope the above can help the development of LLVM JIT
