### ISSUE TITLE
Compiling CUDA example from llvm docs - 'No available targets are compatible with triple "nvptx64-nvidia-cuda"'

### ISSUE THREAD

**Issue by fbartolic** [llvm/llvm-project#54498]
I am trying to compile the example CUDA code axpy.cu from the [llvm docs](https://llvm.org/docs/CompileCudaWithLLVM.html#invoking-clang) using:

```
clang++ axpy.cu -o axpy --cuda-gpu-arch=sm_86 -L/usr/local/cuda-11.2/lib64 -lcudart_static -ldl -lrt -pthread
```
but I'm getting the following error:
```
error: unable to create target: 'No available targets are compatible with triple "nvptx64-nvidia-cuda"'
```
I built llvm-13.0.0 from source and I've used `clang++` to successfully  compile cuda code a few days ago but something changed on my system and now I'm getting this error message. I have no idea what to do about it.  I'm running CentOS 7.

**Comment by Artem-B** [comment]
You may have built clang w/o NVPTX back-end.

You can check which back-ends were enabled by running `llc --version`.

**Comment by fbartolic** [comment]
@Artem-B 

Here's the output from `llc --version`:
```
LLVM (http://llvm.org/):
  LLVM version 13.0.0
  Optimized build with assertions.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: cascadelake

  Registered Targets:
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
```

How do I build llvm/clang with the NVPTX back-end? I've used the following cmake options when building llvm:
```
cmake -G Ninja ../llvm -DLLVM_TARGETS_TO_BUILD="host" -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_ENABLE_PLUGINS=ON -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON
```

**Comment by Artem-B** [comment]
> -DLLVM_TARGETS_TO_BUILD="host"

This is the source of your problem. You told cmake to build LLVM for your host and that's exactly what it's done.
Removing it will compile in the standard set of back-ends and that includes `nvptx` and `nvptx64`.

You can try changing it to something like `-DLLVM_TARGETS_TO_BUILD="X86;NVPTX".` 
See https://llvm.org/docs/GettingStarted.html#local-llvm-configuration for the details.

**Comment by fbartolic** [comment]
Ah yes, that makes sense. That fixed the problem, thank you so much!
