### ISSUE TITLE
Spurious "invalid type for inline asm constraint string" when compiling IR with LLC

### ISSUE THREAD

**Issue by SixthDot** [llvm/llvm-project#54490]
## description

code containing inline asm and manually compiled in two steps is rejected by LLC.
Happens under linux x86_64.

## IR

```LLVM
; ModuleID = 'asm_exp'
source_filename = "asm_exp"

; Function Attrs: noinline
define i64 @asm_exp.test2() #0 {
entry:
  %0 = call i64 asm "movq $0, $1", "i,=r"(i64 42)
  ret i64 %0
}

attributes #0 = { noinline }
```

## command line

(all version of llc are affected)

```bash
$ llc test.ll --x86-asm-syntax=att --mtriple=x86_64-unknown-linux-gnu
```

## output

> /opt/compiler-explorer/clang-11.0.1/bin/llc: error: /opt/compiler-explorer/clang-11.0.1/bin/llc: <source>:7:17: error: invalid type for  inline asm constraint string
>  %0 = call i64 asm "movq $0, $1", "i,=r"(i64 42)         

## see also

- [test case on compiler explorer](https://godbolt.org/z/dqjKhasrf)      
- #36137, likely the same although the reporter specifies it's related to the `uselistorder` attribute

**Comment by topperc** [comment]
This inline assembly directive is ill-formed according to the langref "The constraints must always be given in that order: outputs first, then inputs, then clobbers." 

'i' is an input and '=r' is an output. So '=r' should come first.

**Comment by SixthDot** [comment]
Indeed `%0 = call i64 asm "movq $1, $0", "=r,i"(i64 42)` works.

Strangely when I use the regular path to compile, and still the ill-formed asm, the IR is checked using the API function `LLVMVerifyModule` before producing objects with `LLVMTargetMachineEmitToFile` but the verifier does not complain about that possible error.
