### ISSUE TITLE
clang format break syntax of C++ with ColumnLimit: 0 and trailing comment

### ISSUE THREAD

**Issue by tophoo** [llvm/llvm-project#54496]
Related to Bug #45136 (https://bugs.llvm.org/show_bug.cgi?id=45791) and  #51234  there is another Bug regarding ColumnLimit: 0 in combination with a lambda statement and a trailing comment:
```
#define MACRO []()

foo(
    1, MACRO { bar(); // comment
    }, []() {}
);
```
becomes:
```
#define MACRO []()

foo(
    1, MACRO { bar(); // comment }, []() {});
```

The clang-format file can be reduced to:
`ColumnLimit: 0`
for reproducing the error. The bug has been reproduced with clang-13.

**Comment by mkurdej** [comment]
Instead of bug #45791, have you meant bug https://bugs.llvm.org/show_bug.cgi?id=45791? (#45136)

**Comment by owenca** [comment]
https://reviews.llvm.org/D122301
