### ISSUE TITLE
How to create a bitcast call Instruction using llvm IR API

### ISSUE THREAD

**Issue by leaflinfeng** [llvm/llvm-project#54509]
I want to create a bitcast call Instruction. like this:
`%18 = call %5* bitcast (i8* (i8*, i8*, ...)* @objc_msgSend to %5* (i8*, i8*, i32)*)(i8* %17, i8* %16, i32 %15), !dbg !263`

I can't find similar usecase 😞

**Comment by Naville** [comment]
``i8* (i8*, i8*, ...)* @objc_msgSend to %5* (i8*, i8*, i32)*)(i8* %17, i8* %16, i32 %15`` is a [ConstantExpr](https://llvm.org/doxygen/classllvm_1_1ConstantExpr.html) , which you pass into ``CreateCall``

**Comment by leaflinfeng** [comment]
> `i8* (i8*, i8*, ...)* @objc_msgSend to %5* (i8*, i8*, i32)*)(i8* %17, i8* %16, i32 %15` is a [ConstantExpr](https://llvm.org/doxygen/classllvm_1_1ConstantExpr.html) , which you pass into `CreateCall`

**Comment by leaflinfeng** [comment]
> `i8* (i8*, i8*, ...)* @objc_msgSend to %5* (i8*, i8*, i32)*)(i8* %17, i8* %16, i32 %15` is a [ConstantExpr](https://llvm.org/doxygen/classllvm_1_1ConstantExpr.html) , which you pass into `CreateCall`

Thanks 😄
