### ISSUE TITLE
Which one is suggested ? Linux or Windows

### ISSUE THREAD

**Issue by omerguzelelectronicguy** [llvm/llvm-project#54519]
Hello,
I started to develop an LLVM Backend to support custom extension of RV32I Processor 2 days ago. I am generally using windows. So I am comfortable in Windows rather than Linux. Although windows is available to develop an LLVM Backend I used Linux because I thought Linux will be better for this job and more people make it in Linux (I should find the solution of a problem easier).
I am currently struggling  on building LLVM Backend structure in Ubuntu 18.04.6 LTS. before I open a new topic in issues, I want to ask.
Are you suggesting to continue with Linux? or come back to Windows?
Thank you for your time.

**Comment by asl** [comment]
Your question is much better suitable for https://llvm.discourse.group/ as it does not contain issue description.

As far as I know, LLVM development could be done on both Linux and Windows (and MacOS as well) without any problems.

**Comment by omerguzelelectronicguy** [comment]
Thank You All.
