### ISSUE TITLE
lld-14.0.0 doesn't skip incompatible lib directories

### ISSUE THREAD

**Issue by FireBurn** [llvm/llvm-project#54515]
```
clang -print-search-dirs
programs: =/usr/lib/llvm/14/bin:/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin
libraries: =/usr/lib/llvm/14/bin/../../../../lib/clang/14.0.0:/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1:/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../lib64:/lib/../lib64:/usr/lib/../lib64:/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/lib:/usr/lib/llvm/14/bin/../lib:/usr/lib/llvm/14/bin/../lib64:/lib:/usr/lib
```

clang sets the library search to be /usr/lib/llvm/14/bin/../lib then /usr/lib/llvm/14/bin/../lib64

This works fine on 32bit but when compiling on 64bit I see errors like:

`ld.lld: error: /usr/lib/llvm/14/bin/../lib/libLLVM-14.so is incompatible with elf64-x86-64`

If I switch to using gold I instead get warnings but things continue to compile:

`/usr/bin/x86_64-pc-linux-gnu-ld.gold: warning: skipping incompatible /usr/lib/llvm/14/bin/../lib/libLLVM-14.so while searching for LLVM-14`

I tried changing the errors in https://github.com/llvm/llvm-project/blob/main/lld/ELF/InputFiles.cpp to warnings but that didn't link either

```
ld.lld: warning: /usr/lib/llvm/14/bin/../lib/libLLVM-14.so is incompatible with elf64-x86-64
ld.lld: error: undefined symbol: LLVMInitializeAMDGPUTargetInfo
```

**Comment by MaskRay** [comment]
Duplicate of #42147. This is an intentional decision to detect brittle system library hierarchy. It has additional benefit we don't need to support `OUTPUT_FORMAT` skipping which may just lead to more inconsistency in practice.

**Comment by FireBurn** [comment]
Can we get clang changed to report the correct library directories?

**Comment by MaskRay** [comment]
What's your Clang configuration and command line leading to `ld.lld: error: /usr/lib/llvm/14/bin/../lib/libLLVM-14.so is incompatible with elf64-x86-64`?

Such issues are usually due to mis-configuration or misuse of cross compiling options.

**Comment by FireBurn** [comment]
clang++  -o src/amd/vulkan/libvulkan_radeon.so src/amd/vulkan/libvulkan_radeon.so.p/meson-generated_.._radv_entrypoints.c.o src/amd/vulkan/libvulkan_radeon.so.p/layers_radv_metro_exodus.c.o src/amd/vulkan/libvulkan_radeon.so.p/layers_radv_sqtt_layer.c.o src/amd/vulkan/libvulkan_radeon.so.p/winsys_null_radv_null_bo.c.o src/amd/vulkan/libvulkan_radeon.so.p/winsys_null_radv_null_cs.c.o src/amd/vulkan/libvulkan_radeon.so.p/winsys_null_radv_null_winsys.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_acceleration_structure.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_android.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_cmd_buffer.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_debug.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_device.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_descriptor_set.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_formats.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_image.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_blit.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_blit2d.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_buffer.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_bufimage.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_clear.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_copy.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_copy_vrs_htile.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_dcc_retile.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_decompress.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_etc_decode.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_fast_clear.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_fmask_copy.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_fmask_expand.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_resolve.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_resolve_cs.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_meta_resolve_fs.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_nir_apply_pipeline_layout.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_nir_lower_ray_queries.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_nir_lower_ycbcr_textures.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_pass.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_perfcounter.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_pipeline.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_pipeline_cache.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_pipeline_rt.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_rt_common.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_sdma_copy_image.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_shader.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_shader_args.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_shader_info.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_spm.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_sqtt.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_query.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_util.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_wsi.c.o src/amd/vulkan/libvulkan_radeon.so.p/si_cmd_buffer.c.o src/amd/vulkan/libvulkan_radeon.so.p/winsys_amdgpu_radv_amdgpu_bo.c.o src/amd/vulkan/libvulkan_radeon.so.p/winsys_amdgpu_radv_amdgpu_cs.c.o src/amd/vulkan/libvulkan_radeon.so.p/winsys_amdgpu_radv_amdgpu_surface.c.o src/amd/vulkan/libvulkan_radeon.so.p/winsys_amdgpu_radv_amdgpu_winsys.c.o src/amd/vulkan/libvulkan_radeon.so.p/radv_llvm_helper.cpp.o src/amd/vulkan/libvulkan_radeon.so.p/radv_nir_to_llvm.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libvulkan_radeon.so -Wl,--whole-archive src/vulkan/wsi/libvulkan_wsi.a src/vulkan/runtime/libvulkan_runtime.a -Wl,--no-whole-archive -O3 -pipe -flto=thin -march=native -O3 -flto=thin -march=native -Wl,-O1 -Wl,--as-needed -fuse-ld=lld -Wl,--thinlto-jobs=16 -Wl,--build-id=sha1 src/amd/common/libamd_common.a src/util/libmesa_util.a src/util/format/libmesa_format.a src/compiler/nir/libnir.a src/compiler/libcompiler.a src/amd/llvm/libamd_common_llvm.a src/amd/addrlib/libaddrlib.a src/amd/compiler/libaco.a src/vulkan/util/libvulkan_util.a src/util/libxmlconfig.a -Wl,--build-id=sha1 -Wl,-Bsymbolic -Wl,--gc-sections -Wl,--version-script /var/tmp/portage/media-libs/mesa-9999/work/mesa-9999/src/amd/vulkan/vulkan.sym -lLLVM-14 -pthread /usr/lib64/libdrm_amdgpu.so /usr/lib64/libelf.so -lm /usr/lib64/libxcb-dri3.so /usr/lib64/libwayland-client.so /usr/lib64/libXrandr.so /usr/lib64/libz.so /usr/lib64/libexpat.so /usr/lib64/libzstd.so -lLLVM-14 -lLLVM-14 /usr/lib64/libxcb.so /usr/lib64/libX11-xcb.so /usr/lib64/libX11.so /usr/lib64/libxcb-present.so /usr/lib64/libxcb-sync.so /usr/lib64/libxcb-randr.so /usr/lib64/libxcb-shm.so /usr/lib64/libxshmfence.so /usr/lib64/libdrm.so /usr/lib64/libudev.so -Wl,--end-group
ld.lld: error: /usr/lib/llvm/14/bin/../lib/libLLVM-14.so is incompatible with elf64-x86-64
ld.lld: error: /usr/lib/llvm/14/bin/../lib/libLLVM-14.so is incompatible with elf64-x86-64
ld.lld: error: /usr/lib/llvm/14/bin/../lib/libLLVM-14.so is incompatible with elf64-x86-64
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by FireBurn** [comment]
32bit clang is configured with:

```
cmake -C /var/tmp/portage/sys-devel/clang-14.0.0/work/x/y/clang-abi_x86_32.x86/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DLLVM_CMAKE_PATH=/usr/lib/llvm/14/lib/cmake/llvm -DCMAKE_INSTALL_P
REFIX=/usr/lib/llvm/14 -DCMAKE_INSTALL_MANDIR=/usr/lib/llvm/14/share/man -DCLANG_RESOURCE_DIR=../../../../lib/clang/14.0.0 -DBUILD_SHARED_LIBS=OFF -DCLANG_LINK_CLANG_DYLIB=ON -DLLVM_DISTRIBUTION_COMPONENTS=clan
g-cmake-exports;clang-headers;clang-resource-headers;libclang-headers;clang-cpp;libclang; -DLLVM_TARGETS_TO_BUILD=AMDGPU;WebAssembly;X86;RISCV;Lanai;SystemZ;VE;PowerPC;AArch64;Mips;BPF;Sparc;Hexagon;AVR;XCore;N
VPTX;ARM;MSP430 -DLLVM_BUILD_TESTS=no -DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_RTTI=ON -DCMAKE_DISABLE_FIND_PACKAGE_LibXml2=no -DCLANG_DEFAULT_OPENMP_RUNTIME=libomp -DCMAKE_DISABLE_FIND_PACKAGE_CUDA=ON -DCLANG_DEFAULT
_CXX_STDLIB= -DCLANG_DEFAULT_RTLIB= -DCLANG_DEFAULT_LINKER=lld -DCLANG_DEFAULT_PIE_ON_LINUX=yes -DCLANG_DEFAULT_UNWINDLIB= -DCLANG_ENABLE_ARCMT=yes -DCLANG_ENABLE_STATIC_ANALYZER=yes -DPython3_EXECUTABLE=/usr/b
in/python3.10 -DLLVM_TOOL_CLANG_TOOLS_EXTRA_BUILD=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sys-devel/clang-14.0.0/work/x/y/clang-abi_x86_32.x86/gentoo_toolchain.cmake /var/tmp/portage/sys-devel/clang-14.0.0/work/clang 
```

64bit:

```
cmake -C /var/tmp/portage/sys-devel/clang-14.0.0/work/x/y/clang-abi_x86_64.amd64/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DLLVM_CMAKE_PATH=/usr/lib/llvm/14/lib64/cmake/llvm -DCMAKE_INSTA
LL_PREFIX=/usr/lib/llvm/14 -DCMAKE_INSTALL_MANDIR=/usr/lib/llvm/14/share/man -DCLANG_RESOURCE_DIR=../../../../lib/clang/14.0.0 -DBUILD_SHARED_LIBS=OFF -DCLANG_LINK_CLANG_DYLIB=ON -DLLVM_DISTRIBUTION_COMPONENTS=
clang-cmake-exports;clang-headers;clang-resource-headers;libclang-headers;clang-cpp;libclang;bash-autocomplete;libclang-python-bindings;c-index-test;clang;clang-format;clang-offload-bundler;clang-offload-wrappe
r;clang-refactor;clang-repl;clang-rename;clang-scan-deps;diagtool;hmaptool;clang-apply-replacements;clang-change-namespace;clang-doc;clang-include-fixer;clang-move;clang-query;clang-reorder-fields;clang-tidy;cl
angd;find-all-symbols;modularize;pp-trace;clang-check;clang-extdef-mapping;scan-build;scan-build-py;scan-view; -DLLVM_TARGETS_TO_BUILD=AMDGPU;WebAssembly;Lanai;Sparc;MSP430;BPF;XCore;RISCV;X86;Hexagon;Mips;ARM;
AArch64;AVR;VE;SystemZ;NVPTX;PowerPC -DLLVM_BUILD_TESTS=no -DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_RTTI=ON -DCMAKE_DISABLE_FIND_PACKAGE_LibXml2=no -DCLANG_DEFAULT_OPENMP_RUNTIME=libomp -DCMAKE_DISABLE_FIND_PACKAGE_CU
DA=ON -DCLANG_DEFAULT_CXX_STDLIB= -DCLANG_DEFAULT_RTLIB= -DCLANG_DEFAULT_LINKER=lld -DCLANG_DEFAULT_PIE_ON_LINUX=yes -DCLANG_DEFAULT_UNWINDLIB= -DCLANG_ENABLE_ARCMT=yes -DCLANG_ENABLE_STATIC_ANALYZER=yes -DPyth
on3_EXECUTABLE=/usr/bin/python3.10 -DLLVM_EXTERNAL_CLANG_TOOLS_EXTRA_SOURCE_DIR=/var/tmp/portage/sys-devel/clang-14.0.0/work/clang-tools-extra -DCLANG_INCLUDE_DOCS=OFF -DCLANG_TOOLS_EXTRA_INCLUDE_DOCS=OFF -DCMA
KE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sys-devel/clang-14.0.0/work/x/y/clang-abi_x86_64.amd64/gentoo_toolchain.cmake /var/tmp/portage/sys-devel/clang-14.0.0/work/clang
```

**Comment by MaskRay** [comment]
Am I right that your host is x86_64, you build a `-m32` Clang, and use it to build an x86_64 program?

The error
```
ld.lld: error: /usr/lib/llvm/14/bin/../lib/libLLVM-14.so is incompatible with elf64-x86-64
```
describes your issue with `-lLLVM-14`. Since `/usr/lib/llvm/14/bin/../lib` (in your case, 32-bit) is in the default library path. You need `-L` to point to a 64-bit LLVM library directory.

**Comment by FireBurn** [comment]
Hi

No I build a 32bit & 64bit llvm & clang

I build 32bit mesa with 64bit clang and -m32 (which is currently succeeding) as the library order above has the 32bit directory first for finding -lLLVM-14

I then build a 64bit mesa with 64bit clang (this is currently failing) as -lLLVM-14 fails, it finds the 32bit version first and doesn't skip past it to the lib64 directory 

This is a regression from llvm/clang/lld 13.0.1

[build.log](https://github.com/llvm/llvm-project/files/8340047/build.log)

**Comment by MaskRay** [comment]
> Hi
> 
> No I build a 32bit & 64bit llvm & clang
> 
> I build 32bit mesa with 64bit clang and -m32 (which is currently succeeding) as the library order above has the 32bit directory first for finding -lLLVM-14
> 
> I then build a 64bit mesa with 64bit clang (this is currently failing) as -lLLVM-14 fails, it finds the 32bit version first and doesn't skip past it to the lib64 directory
> 
> This is a regression from llvm/clang/lld 13.0.1
> 
> [build.log](https://github.com/llvm/llvm-project/files/8340047/build.log)

Should be fixed by https://reviews.llvm.org/D122444 according to Jannik2099.

**Comment by FireBurn** [comment]
Thanks, that fixes things

**Comment by FireBurn** [comment]
I think this fix was missed from 14.0.1

**Comment by EugeneZelenko** [comment]
@FireBurn: patch is not committed to `main` yet.

**Comment by FireBurn** [comment]
https://github.com/llvm/llvm-project/commit/afaefb671fe12e7788d3e8de6b6193b935fbf16c

**Comment by tstellar** [comment]
@MaskRay Are there some follow up commits that we need along with https://github.com/llvm/llvm-project/commit/afaefb671fe12e7788d3e8de6b6193b935fbf16c ?

**Comment by MaskRay** [comment]
If https://github.com/llvm/llvm-project/commit/afaefb671fe12e7788d3e8de6b6193b935fbf16c is cherry picked, fceea4e11028f4bfbafbd6893ddeb319420107d9 for OpenMP will be needed.

**Comment by tstellar** [comment]
/cherry-pick afaefb671fe12e7788d3e8de6b6193b935fbf16c fceea4e11028f4bfbafbd6893ddeb319420107d9

**Comment by tstellar** [comment]
@jdoerfert Are you OK with backporting https://github.com/llvm/llvm-project/commit/fceea4e11028f4bfbafbd6893ddeb319420107d9 ?

**Comment by jdoerfert** [comment]
> @jdoerfert Are you OK with backporting [fceea4e](https://github.com/llvm/llvm-project/commit/fceea4e11028f4bfbafbd6893ddeb319420107d9) ?

Yes, please.

**Comment by tstellar** [comment]
Merged: 5c4cf01f47da35816a252c4656b36404b4b8615c 76c1c1dd2a01fa2b2511cd0da3ec71d03addb107

**Comment by tstellar** [comment]
Failed to create pull request for issue54515

**Comment by tstellar** [comment]
Failed to create pull request for issue54515

**Comment by tstellar** [comment]
Failed to create pull request for issue54515

**Comment by tstellar** [comment]
Failed to create pull request for issue54515
