### ISSUE TITLE
LLVM building confusion

### ISSUE THREAD

**Issue by omerguzelelectronicguy** [llvm/llvm-project#54527]
Hello,
I am trying to build an LLVM to make a backend project.
[Official LLVM website ](https://llvm.org/docs/GettingStarted.html#getting-started-with-llvm)  suggested to use this command
`cmake -G <generator> [options] ../llvm`
However, [github page](https://github.com/llvm/llvm-project) suggest this command:
`cmake -S llvm -B build -G <generator> [options]`
Since the official website suggest also [clang website ](https://clang.llvm.org/get_started.html)I also used this which is written in the cleng website:
`cmake -DLLVM_ENABLE_PROJECTS=clang -G "Unix Makefiles" ../llvm`
The last one worked for me but I am not sure whether it is true or not to develop LLVM Backend.
I confuse which one I should use and what are the differences.
Thank you

**Comment by pogo59** [comment]
Please note that for general questions like this, https://discourse.llvm.org/ is more appropriate; there is a "Beginners" category there, where you might find that getting-started questions might have been answered already. And if not, I think you are more likely to get a useful answer there.

The difference in suggested cmake command options is probably best answered by looking at cmake's own help.  Without looking into it, I suspect the difference is that the first suggestion has you running the cmake command while the current directory is something like "llvm-project/build" while the second has you running the command from the "llvm-project" directory.

Whether you want to enable clang depends on how you plan to test and use your backend. If you plan to write C/C++ code and compile it for your target (which would be very typical), then enabling clang is the best way to meet that goal.  If you plan to use your backend from some other language (say, Rust) then you do not need to enable the clang project.

**Comment by omerguzelelectronicguy** [comment]
Thank you I will use that beginner's website more.
