### ISSUE TITLE
Missing overrides on `MultiplexASTDeserializationListener`

### ISSUE THREAD

**Issue by lingol** [llvm/llvm-project#54521]
Hi, I notice a missing override for [ASTDeserializationListener::ModuleImportRead()](https://github.com/llvm/llvm-project/commit/9c982440a22f2212d749bc9550bf991a3896d7a6) on wrapper [MultiplexASTDeserializationListener](https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Frontend/MultiplexConsumer.h#L29). 
When someone has registered one or more `PluginASTAction` plugins, this bug will cause the bridging header's imported module not handled correctly for Swift.

**Comment by lingol** [comment]
And I did a little dig in, found out that in 2015 a similar case had taken place https://github.com/llvm/llvm-project/commit/5578e44df8e63152e891189ce35005dcf5fcf396. Makes one wonder.

**Comment by lingol** [comment]
@graydon You might check this out.

**Comment by lgxbslgx** [comment]
@lingol @graydon Have you started the work? If not, I would like to take it over.

**Comment by lingol** [comment]
No I have not.

**Comment by lgxbslgx** [comment]
Revision URL: https://reviews.llvm.org/D123452

@lingol Sorry for the delay. Could I get your help to review and verify the patch? Thanks.

**Comment by lingol** [comment]
> Revision URL: https://reviews.llvm.org/D123452
> 
> @lingol Sorry for the delay. Could I get your help to review and verify the patch? Thanks.

I'm not familiar with the LLVM dev flow. Is it OK for a total stranger to review and verify a patch?

**Comment by lgxbslgx** [comment]
> When someone has registered one or more PluginASTAction plugins, this bug will cause the bridging header's imported module not handled correctly for Swift.

> I'm not familiar with the LLVM dev flow. Is it OK for a total stranger to review and verify a patch?

The LLVM committer may review the patch formally in the near future. But it is good for you to verify whether the patch can solve your issue actually, especially the situation you mentioned about Swift. If you don't want to do that, you can wait for the patch to be integrated and the new llvm version to be released.

**Comment by nico** [comment]
d29f8a5f83501f6962

**Comment by lingol** [comment]
Thanks a lot. It's the same as my local modification. So Yes, it does fix my problem.
