### ISSUE TITLE
[clang-format] Logical AND sometimes confused for rvalue reference

### ISSUE THREAD

**Issue by jbms** [llvm/llvm-project#54539]
Input:

```c++
template <typename Foo>
constexpr bool X = A && B;
```

`clang-format -style=Google` output using `clang-format` version 13.0.1:

```c++
template <typename Foo>
constexpr bool X = A&& B;
```

Removing the template prefix avoids the problem:

```c++
constexpr bool X = A && B;
```

This issue is also present in clang-format built from the more recent a54d028895c91da356a4aaf30e27a5a5b90dd313.

Strangely, the version of clang-format on compiler explorer does not exhibit the issue.  However I am not sure what version that is.

**Comment by mkurdej** [comment]
This was fixed in https://github.com/llvm/llvm-project/commit/3227aa3aa83440ff94a3b13a29623e03b05098f2.
