### ISSUE TITLE
[InstCombine] Missing signext attribute on parameter

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#54532]
`a() { printf("\n"); }`

Instcombine replaces the call to printf with a call to putchar, but forgets to add an extension on the new parameter:

`  %call = call signext i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([2 x i8], [2 x i8]* @.str, i64 0, i64 0))`

=> After InstCombinePass

`%putchar = call i32 @putchar(i32 10)`

=>

```
        lhi     %r2, 10
        jg      putchar@PLT
```

This particular case seems perhaps harmless, but I suspect that calls to other library functions might not be: on SystemZ all outgoing parameters less than 32 bits in width must have a sign/zero extension attribute at the call site to conform to the ABI.

**Comment by efriedma-quic** [comment]
Also, https://reviews.llvm.org/D90760 is wrong; it should be replaced with a more appropriate fix.

**Comment by JonPsson** [comment]
> TargetLibraryInfo::getExtAttrForI32Param and TargetLibraryInfo::getExtAttrForI32Return return the right extension attributes for parameters and return values. We should use them from emitPutChar etc.
> Also, https://reviews.llvm.org/D90760 is wrong; it should be replaced with a more appropriate fix.

I think I see what you mean: the attribute should only be added if getExtAttrForI32Param() says it should. I proposed a patch for this at https://reviews.llvm.org/D123030, which also handles (so far) putchar. Please let me know if I am on the right track here before I continue with the many more library function declarations.

**Comment by JonPsson** [comment]
Thanks for review.
