### ISSUE TITLE
clang-tidy: google-runtime-int flags user-defined literals

### ISSUE THREAD

**Issue by gleb-kov** [llvm/llvm-project#54546]
Example:
```
inline constexpr utils::Ts operator""_ms(unsigned long long ms) {
...
}
```
According to https://en.cppreference.com/w/cpp/language/user_literal I cannot put uint64_t or any other option. It would be great to suppress the warning in such cases.

**Comment by Febbe** [comment]
Actually, this check should never mark user defined literals.
@alexfh you previously modified this check, It would be very cool, if you find the time, to fix this issue too.
