### ISSUE TITLE
Backport fed96f31bb5b68f77dd617ee8e698dd8171ee71b to the release/14.x branch

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#54548]
@vhscampos What do you think about backporting this?

/cherry-pick fed96f31bb5b68f77dd617ee8e698dd8171ee71b

**Comment by vhscampos** [comment]
It's a good idea. Will you take this?

**Comment by tstellar** [comment]
Merged: 99c0f85ef992e9aa6465f27a8b05601667412bc7
