### ISSUE TITLE
backport 20e212197a5d84f02da14b567d43ae16d46fc643 to the release/14.x branch

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#54547]
I think 20e212197a5d84f02da14b567d43ae16d46fc643 will likely fix https://developercommunity.visualstudio.com/t/Prev-Issue---with-__assume-isnan-/1597317 and get the windows tests green again.

/cherry-pick 20e212197a5d84f02da14b567d43ae16d46fc643

**Comment by tstellar** [comment]
@RKSimon What do you think about backporting this? https://github.com/llvm/llvm-project/commit/20e212197a5d84f02da14b567d43ae16d46fc643

**Comment by RKSimon** [comment]
Sorry - I missed this notification for some reason.

LGTM

**Comment by tstellar** [comment]
This didn't actually fix the bug, like I thought it would, so I'm going hold off on backporting this one.

**Comment by tstellar** [comment]
> This didn't actually fix the bug, like I thought it would, so I'm going hold off on backporting this one.

It looks like this change is actually a no-op, because ErrorHandling.h in the release/14.x branch has:

`#ifndef NDEBUG
#define llvm_unreachable(msg) \
  ::llvm::llvm_unreachable_internal(msg, __FILE__, __LINE__)
#elif defined(LLVM_BUILTIN_UNREACHABLE)
#define llvm_unreachable(msg) LLVM_BUILTIN_UNREACHABLE
#else
#define llvm_unreachable(msg) ::llvm::llvm_unreachable_internal()
#endif
`
It also looks like a no-op in the main branch too.

**Comment by ldionne** [comment]
Is this still relevant? It seems like we can probably close it at this point.
