### ISSUE TITLE
[X86][Disassembler] vpsubq (%esp), %xmm1, %xmm2 can not be decoded by LLVM's disassembler

### ISSUE THREAD

**Issue by KanRobert** [llvm/llvm-project#54540]
```
bash$ cat 1.s
vpsubq (%esp), %xmm1, %xmm2
bash$ llvm-mc --filetype=obj 1.s -o 1.o
bash$ llvm-objdump -d 1.o

1.o:    file format elf64-x86-64Disassembly of section .text:0000000000000000 <.text>:
       0: 67 c5 f1 fb 14 24             <unknown>
```

**Comment by KanRobert** [comment]
Ongoing patch: https://reviews.llvm.org/D122448

**Comment by hvdijk** [comment]
Thanks for the clear example. The patch that you are reverting fixes an ICE-on-valid-C++ in clang that shows up when building Qt though, so we are in a lousy situation where something important is broken if we do revert, something else also important is broken if we don't. I cannot comment on the relative priorities, I do not know which is worse. I expect to have time over the weekend to look into whether this is easy to fix so that both work, is it okay to wait for that?

**Comment by KanRobert** [comment]
@hvdijk Sure. Let me know if you need my help. I'm familiar w/ X86 encoding/decoding and able to provide a quick solution to support both of them.

**Comment by KanRobert** [comment]
https://reviews.llvm.org/D122537
https://reviews.llvm.org/D122448

These two patches can fix both of them.

**Comment by hvdijk** [comment]
Regardless of whether that would be enough, we cannot commit that as you pushed changes that conflict with those, apparently without going through the review process. I am working on resolving the conflict and I will submit a patch soon. (Please do not be helpful and resolve the conflict yourself. You knew already I'd started work on this. Let me finish that.)

**Comment by hvdijk** [comment]
Created https://reviews.llvm.org/D122540, tested with your https://reviews.llvm.org/D122449 applied on top.

**Comment by hvdijk** [comment]
Thanks for the patience, the fix is now in on main. What would you prefer for the branches? The fix should not cherry-pick cleanly, so we can either decide to leave those as they are or make the required changes. I am fine with either, and can make those changes if you like.

**Comment by KanRobert** [comment]
I work on the main branch most of the time, so I don't have any back-porting request. I think no more work is need until we receive a request. Thank you for the effort.
