### ISSUE TITLE
[InstCombine] Missing `SimplifyUsingDistributiveLaws()` for logical operations

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#54553]
This comes up in e.g. https://github.com/llvm/llvm-project/issues/53861 after the SimplifyCFG part is fixed, we are missing at least the following transform:
https://alive2.llvm.org/ce/z/8NQiXJ
... which is the poison-safe variant of https://alive2.llvm.org/ce/z/zjS4qv

**Comment by rotateright** [comment]
We reduced the example in the alive2 link with one of these:
https://reviews.llvm.org/D139408 / c8647738cd654d9ecfdc0
https://reviews.llvm.org/D139630 / 33794cffcfdadfffda2c78c7

...so I think we can close this report, but please re-open or file another bug if there's still a known missing part. 
cc @bcl5980
