### ISSUE TITLE
lld/mac fails to link against dylib with LC_DYLD_EXPORTS_TRIE

### ISSUE THREAD

**Issue by Kha** [llvm/llvm-project#54550]
ld64.lld currently requires `LC_DYLD_INFO_ONLY` to be present in all dylibs passed to it
```
ld64.lld: error: LC_DYLD_INFO_ONLY not found in /opt/homebrew/lib/libgmp.dylib
```
Apparently this field was replaced by the newer `LC_DYLD_EXPORTS_TRIE` at some point, such as in the above dylib from homebrew. It looks like lldb already gained support for either field: https://reviews.llvm.org/D107673

**Comment by BertalanD** [comment]
Patch: https://reviews.llvm.org/D129430
