### ISSUE TITLE
why libclang soname remains 13 without updating to latest LLVM version?

### ISSUE THREAD

**Issue by nickhuang99** [llvm/llvm-project#54566]
It has been confusing when I keep seeing libclang.so soname remains to be 13 when buidling with llvm-14. This "clang/tools/libclang/CMakeLists.txt" doesn't update the soname "13",  or perhaps as its comment says "clang/tools/libclang/libclang.map" also needs updated.  

It is difficult for me to understand this comment in "clang/tools/libclang/CMakeLists.txt" which makes me feel this behavior is by design?

<pre><code>
# The SOVERSION should be updated only if a change is made to the libclang
# ABI, and when it is updated, it should be updated to the current
# LLVM_VERSION_MAJOR.
# Please also see clang/tools/libclang/libclang.map
set(CLANG_SONAME 13)
</code></pre>

**Comment by DimitryAndric** [comment]
See also c7b3a91017d26266d7556b1ac7c49b06f0109b91, where this was introduced by @tstellar. I think the intent is that the libclang SONAME is *only* bumped when a new symbol is added to `libclang.map`, as indicated.

E.g. `libclang.map` looks like:

```
# If you add a symbol to this file, make sure to add it with the correct
# version.  For example, if the LLVM main branch is LLVM 14.0.0, add new
# symbols with the version LLVM_14.
# On platforms where versions scripts are not used, this file will be used to
# generate a list of exports for libclang.so

LLVM_13 {
  global:
    clang_BlockCommandComment_getArgText;
... much more symbols ...
  local: *;
};

# Example of how to add a new symbol version entry.  If you do add a new symbol
# version, please update the example to depend on the version you added.
# LLVM_X {
# global:
#   clang_newsymbol;
# };
```

So for the moment, the last time symbols were added to the above list, the major version of libllvm was still 13, which is why all the symbols are under a `LLVM_13` version.

Now that 14.0.0 has shipped, adding any *new* symbols to the `libclang` ABI would have to be added to a new version, and as the comment in `CMakeLists.txt` indicates, that should then be done with `LLVM_15` as version. And at the same time, the `libclang` SONAME should then be bumped to 15.

**Comment by nickhuang99** [comment]
hi,

Thank you for your prompt response and explanation.
Be this as by design. The mismatch soname mis-guides user to believe they have a corrupted installation. That is my concern because I actually recompiled several times to make sure my system environment and build configuration is correct.
Why does it matter if no new symbol is added? Many software upgrades to major version with even very little changes. It is sometimes just a periodic release like Ubuntu.
Just want to bring this up as a potential user concern.

Appreciate your effort very much!



my journey is oceans of stars...

________________________________

**Comment by EugeneZelenko** [comment]
See also #53684.

**Comment by nickhuang99** [comment]
thanks.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by aaronpuchert** [comment]
> I think the intent is that the libclang SONAME is _only_ bumped when a new symbol is added to `libclang.map`, as indicated.

The SONAME will only only need to be bumped when there are incompatible changes. New symbols simply get a new symbol version in the map file.

> Now that 14.0.0 has shipped, adding any _new_ symbols to the `libclang` ABI would have to be added to a new version, and as the comment in `CMakeLists.txt` indicates, that should then be done with `LLVM_15` as version.

Correct.

> And at the same time, the `libclang` SONAME should then be bumped to 15.

No, that wouldn't be needed. Somebody linking against `libclang.so.13` could still run with the new library if we only add symbols.
