### ISSUE TITLE
llvm-ranlib can only handle one archive at a time

### ISSUE THREAD

**Issue by brad0** [llvm/llvm-project#54565]
Recently OpenBSD converted over to using llvm-ranlib from GNU binutils ranlib and noticed it only handles one file at a time. This broke a few ports.

.e.g. ranlib foo.a bar.a 123.a

After building the three archives.

**Comment by brad0** [comment]
@MaskRay

**Comment by MaskRay** [comment]
Patch: https://reviews.llvm.org/D131375
