### ISSUE TITLE
[X86] ABI mismatch between Clang and GCC/ICC when arguments are structures with more than one element

### ISSUE THREAD

**Issue by phoebewang** [llvm/llvm-project#54582]
This is found during working on D122104. https://godbolt.org/z/5z4eG6a5P
The comments and the code below seems not correct:
 https://github.com/llvm/llvm-project/blob/d9cea8d3a8fff86672174780312674871729578c/clang/lib/CodeGen/TargetInfo.cpp#L3050-L3056

**Comment by RKSimon** [comment]
This looks suspicious:
```
typedef struct {
  __m256d r1[2];
} __sVector;

double bar(__sVector a) {
    return a.r1[0][4];
}

define dso_local double @bar(%struct.__sVector* nocapture noundef readnone byval(%struct.__sVector) align 32 %0) local_unnamed_addr #2 {
  ret double poison
}
```

**Comment by phoebewang** [comment]
I didn't intend to use the index 4. It should use 0~3 instead.
I'm not sure whether it's a problem of not. The 4 is out of the range of the vector. But if the array is continuous, it should be equal to `a.r1[1][0]`. What do you think?

**Comment by phoebewang** [comment]
Just found it's not a problem if I change it to 3. So it's a mistake of the test case.

**Comment by phoebewang** [comment]
https://godbolt.org/z/vnEh6evxf
