### ISSUE TITLE
Backport https://reviews.llvm.org/D122505 to llvm-14

### ISSUE THREAD

**Issue by kraj** [llvm/llvm-project#54597]
I would like to request backport of https://github.com/llvm/llvm-project/commit/11a8fc685692f56b011f851d974f0cac534f2cb8 to 14.x branch.

**Comment by MaskRay** [comment]
Looks good to me. The code change is small but some test adjustment is needed. In particular, these commits are needed in order. 

* 423af54cbef7b90199e01162dcea6d3e62539e8c `[llvm-objdump][test] dos2unix some files`
* 11a8fc685692f56b011f851d974f0cac534f2cb8 `[llvm-objdump] --private-headers: change errors to warnings for dynamic section dumping`
* f7086401b7c03179b755768845956bc8e84ab266 `[Object][test] Fix invalid.test`

**Comment by tstellar** [comment]
/cherry-pick 423af54cbef7b90199e01162dcea6d3e62539e8c 11a8fc685692f56b011f851d974f0cac534f2cb8 f7086401b7c03179b755768845956bc8e84ab266

**Comment by tstellar** [comment]
Merged: c9ec4902c3e3 1007cb795a3c 311a622edd31
