### ISSUE TITLE
Backport `[ELF] Fix llvm_unreachable failure when COMMON is placed in SHT_PROGBITS output section` to 14.0.1

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#54598]
The lld/ELF change 1db59dc8e28819b1960dae8e7fe6d79ad4b03340 fixed a regression for a linker script like `.data : { ... *(COMMON) }` when COMMON symbols are used. efitools is known to use such a linker script.

**Comment by tstellar** [comment]
Merged: add3ab7f4c8a 3f43d803382d 353068233f21
