### ISSUE TITLE
Backport `[AArch64] Allow .variant_pcs before the symbol is registered` into 14.0.1

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#54604]
cfbd5c8e4aa1ba3fc11fb408eeedbb05bd235956 fixed `.variant_pcs` for some syntax.

**Comment by tstellar** [comment]
@efriedma-quic Is this safe to backport?

**Comment by efriedma-quic** [comment]
Yes, it's safe.

**Comment by tstellar** [comment]
Merged: add3ab7f4c8a 3f43d803382d d53e2603383a
