### ISSUE TITLE
cherry-pick 2aaba44 to release/14.x: [PowerPC] Allow absolute expressions in relocations

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#54607]
@nemanjai 

Should we backport this?

/cherry-pick 2aaba44b5c2265f90ac9f0ae188417ef79201c82

**Comment by tstellar** [comment]
cc @nickdesaulniers

**Comment by tstellar** [comment]
This bug also affects libglvnd: https://gitlab.freedesktop.org/glvnd/libglvnd/-/blob/master/src/GLdispatch/vnd-glapi/entry_ppc64_tls.c#L69

**Comment by nemanjai** [comment]
Yes, this would be nice to backport.

**Comment by tstellar** [comment]
Merged: 33504b3bbe10
