### ISSUE TITLE
Backport `[MC] Fix llvm_unreachable when a STB_GNU_UNIQUE symbol needs a relocation` into 14.0.1

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#54600]
6bdad85b26fbfd064772f2b382b27fbbf0b0afce fixed llvm_unreachable crash when assembling `.type ..., %gnu_unique_object` assembly files (e.g. GCC by default uses -fgnu-unique and may produce such files).

**Comment by tstellar** [comment]
Merged: db07d9f098b3
