### ISSUE TITLE
Backport `[ELF] --emit-relocs: fix missing STT_SECTION when the first input section is synthetic` into 14.0.1

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#54619]
7370a489b1005e424b23bd0009af2365aef4db53 fixed a regression (from 13.x) that `--emit-relocs` reproduced relocations referencing `.bss` were incorrect in the presence of COMMON symbols. This may affect some tools analyzing relocations.

**Comment by tstellar** [comment]
@igorkudrin Is this safe to backport? https://github.com/llvm/llvm-project/commit/7370a489b1005e424b23bd0009af2365aef4db53

**Comment by MaskRay** [comment]
This is safe.

**Comment by tstellar** [comment]
Merged: dc30b0d3320d
