### ISSUE TITLE
[MLIR][VSCode] Unable to resolve server path

### ISSUE THREAD

**Issue by silvasean** [llvm/llvm-project#54627]
For some reason, recently I have been getting the following error.

![image](https://user-images.githubusercontent.com/24583347/160715602-e3bebdfc-b3cb-42a5-a5c1-aaeae162a730.png)

The server path is definitely correct (it's the same as what I was using before, which was `torch-mlir-lsp-server`). I even tried `${env:HOME}/bin/torch-mlir-lsp-server` to point at the binary directly but that doesn't seem to help. Any idea what is going on?

**Comment by River707** [comment]
Thanks for reporting this, I'm pretty sure I screwed this up when reworking things for the pdll server. We never had a good story for actually resolving server paths, we kind of just hoped stuff was good. I sent out https://reviews.llvm.org/D122792 and https://reviews.llvm.org/D122793 which should help fix/improve things.

**Comment by River707** [comment]
@silvasean Can you update to try using `torch-mlir-lsp-server` again?

**Comment by silvasean** [comment]
Update to v0.0.5 of the VSCode extension and still seeing the same dialog. I tried with `${env:HOME}/bin/torch-mlir-lsp-server` and still got the same issue.
