### ISSUE TITLE
[LLVM-COV] Wrong coverage for a switch statement with embedded if-statement

### ISSUE THREAD

**Issue by NJUocean** [llvm/llvm-project#54639]
$ clang -v
clang version 11.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/wangyang/llvm-project/build/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

$ cat test.c
```
/* PR c++/88984 */
/* { dg-do run } */

void foo(int x, int y) {
  while (x > 0)
    switch (({
      if (y)
        break;
      y;
    })) {
    case 2:
      x = 0;
    }
}

int main() {
  foo(1, 1);
  return 0;
}
```

$ clang -w -O0 -g -fcoverage-mapping -fprofile-instr-generate=test.profraw test.c; ./a.out; llvm-profdata merge test.profraw -o test.profdata; llvm-cov show a.out -instr-profile=test.profdata test.c > test.lcov; cat test.lcov
```
    1|       |/* PR c++/88984 */
    2|       |/* { dg-do run } */
    3|       |
    4|      1|void foo(int x, int y) {
    5|      1|  while (x > 0)
    6|      1|    switch (({
    7|      1|      if (y)
    8|      1|        break;
    9|      0|      y;
   10|      0|    })) {
   11|      0|    case 2:
   12|      0|      x = 0;
   13|      0|    }
   14|      1|}
   15|       |
   16|      1|int main() {
   17|      1|  foo(1, 1);
   18|      1|  return 0;
   19|      1|}
```
Line 6 should not  be executed as the loop breaks in line 8 directly.

**Comment by NJUocean** [comment]
INVALID

**Comment by EugeneZelenko** [comment]
@NJUocean: Could you please elaborate? Does latest versions work?

**Comment by NJUocean** [comment]
> @NJUocean: Could you please elaborate? Does latest versions work?

@EugeneZelenko All coverage bugs I reported are uncovered by automatically checking the relationship between statement coverage statistics. From a statement coverage perspective, it should indeed be 5 and it still exists in 14. This issue as well as 48872 have the same coverage in GCov, and the developers of GCov tend to confirm them as "INVALID". Maybe it is the design of coverage tool?

**Comment by NJUocean** [comment]
> @NJUocean: Could you please elaborate? Does latest versions work?

@EugeneZelenko I think 0 or 1 can make sense now as the switch hasn't really started.
