### ISSUE TITLE
[AArch64] Improve "a MOD pow2cst" codegen

### ISSUE THREAD

**Issue by ilinpv** [llvm/llvm-project#54649]
Code generation for modulo operations with a power of two can be improved for aarch64.
```
int
mod2 (int a)
{
  return a % 2;
}

int
mod16 (int a)
{
  return a % 16;
}
```

At -O2 GCC produces shorter code
https://godbolt.org/z/v63WYvzna

Generally:

;; Expansion of signed mod by a power of 2 using CSNEG.
;; For x0 % n where n is a power of 2 produce:
;; negs   x1, x0
;; and    x0, x0, #(n - 1)
;; and    x1, x1, #(n - 1)
;; csneg  x0, x0, x1, mi
For the constant 2 the special case is
```
      cmp    x0, xzr
      and    x0, x0, 1
      cneg   x0, x0, lt.
```

**Comment by bcl5980** [comment]
I'm trying to fix this on https://reviews.llvm.org/D122829
