### ISSUE TITLE
Compiling LLVM 14.x with `clang-cl` and `/arch:AVX` or `-march=sandybridge` crashes.

### ISSUE THREAD

**Issue by tru** [llvm/llvm-project#54645]
Setup:

* Build clang and lld with MSVC.
* configure LLVM with: `cmake -GNinja -DLLVM_ENABLE_LTO=Thin -DCMAKE_CXX_FLAGS="/arch:AVX" -DCMAKE_C_FLAGS="/arch:AVX" -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe -DCMAKE_LINKER=lld-link.exe ..\llvm`
* Build `llvm-profdata` (it probably happens with other binaries - but this is pretty fast and easy to reproduce it with)

crash in:

```
17:01:04  #0 0x00007ff612ca30a1 llvm::SelectionDAG::createOperands(class llvm::SDNode *, class llvm::ArrayRef<class llvm::SDValue>) C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\CodeGen\SelectionDAG\SelectionDAG.cpp:11084:0
17:01:04  #1 0x00007ff612cbbf07 llvm::SelectionDAG::getNode(unsigned int, class llvm::SDLoc const &, struct llvm::EVT, class llvm::ArrayRef<class llvm::SDValue>, struct llvm::SDNodeFlags) C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\CodeGen\SelectionDAG\SelectionDAG.cpp:8420:0
17:01:04  #2 0x00007ff612cbbca2 llvm::SelectionDAG::getNode(unsigned int, class llvm::SDLoc const &, struct llvm::EVT, class llvm::ArrayRef<class llvm::SDValue>) C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\CodeGen\SelectionDAG\SelectionDAG.cpp:8358:0
17:01:04  #3 0x00007ff612b373ce lowerV8I16Shuffle C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\Target\X86\X86ISelLowering.cpp:15804:0
17:01:04  #4 0x00007ff612b39862 lowerVECTOR_SHUFFLE C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\Target\X86\X86ISelLowering.cpp:19171:0
17:01:04  #5 0x00007ff612a6bc27 llvm::X86TargetLowering::LowerOperation(class llvm::SDValue, class llvm::SelectionDAG &) const C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\Target\X86\X86ISelLowering.cpp:31599:0
17:01:04  #6 0x00007ff612e0b294 `anonymous namespace'::SelectionDAGLegalize::LegalizeOp C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\CodeGen\SelectionDAG\LegalizeDAG.cpp:1281:0
17:01:04  #7 0x00007ff612e09413 llvm::SelectionDAG::Legalize(void) C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\CodeGen\SelectionDAG\LegalizeDAG.cpp:4995:0
17:01:04  #8 0x00007ff612d0feb9 llvm::SelectionDAGISel::CodeGenAndEmitDAG(void) C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\CodeGen\SelectionDAG\SelectionDAGISel.cpp:933:0
17:01:04  #9 0x00007ff612d14acd llvm::SelectionDAGISel::SelectAllBasicBlocks(class llvm::Function const &) C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\CodeGen\SelectionDAG\SelectionDAGISel.cpp:1631:0
17:01:04 #10 0x00007ff612d1b404 llvm::SelectionDAGISel::runOnMachineFunction(class llvm::MachineFunction &) C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\CodeGen\SelectionDAG\SelectionDAGISel.cpp:511:0
17:01:04 #11 0x00007ff612978a1d `anonymous namespace'::X86DAGToDAGISel::runOnMachineFunction C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\Target\X86\X86ISelDAGToDAG.cpp:195:0
17:01:04 #12 0x00007ff612f19321 llvm::MachineFunctionPass::runOnFunction(class llvm::Function &) C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\CodeGen\MachineFunctionPass.cpp:72:0
17:01:04 #13 0x00007ff613cbf12b llvm::FPPassManager::runOnFunction(class llvm::Function &) C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\IR\LegacyPassManager.cpp:1434:0
17:01:04 #14 0x00007ff613cbf373 llvm::FPPassManager::runOnModule(class llvm::Module &) C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\IR\LegacyPassManager.cpp:1479:0
17:01:04 #15 0x00007ff613cbf5b8 `anonymous namespace'::MPPassManager::runOnModule C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\IR\LegacyPassManager.cpp:1549:0
17:01:04 #16 0x00007ff613cbee20 llvm::legacy::PassManager::run(class llvm::Module &) C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\IR\LegacyPassManager.cpp:1676:0
17:01:04 #17 0x00007ff612ee782e codegen C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\LTO\LTOBackend.cpp:430:0
17:01:04 #18 0x00007ff612ee62e5 <lambda_e0845f8b0ff363d6d03d2cd977f2ce79>::operator() C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\LTO\LTOBackend.cpp:598:0
17:01:04 #19 0x00007ff612eeb90a llvm::lto::thinBackend(struct llvm::lto::Config const &, unsigned int, class std::function<(unsigned int)>, class llvm::Module &, class llvm::ModuleSummaryIndex const &, class llvm::StringMap<class std::unordered_set<unsigned __int64, struct std::hash<unsigned __int64>, struct std::equal_to<unsigned __int64>, class std::allocator<unsigned __int64>>, class llvm::MallocAllocator> const &, class llvm::DenseMap<unsigned __int64, class llvm::GlobalValueSummary *, struct llvm::DenseMapInfo<unsigned __int64, void>, struct llvm::detail::DenseMapPair<unsigned __int64, class llvm::GlobalValueSummary *>> const &, class llvm::MapVector<class llvm::StringRef, class llvm::BitcodeModule, class llvm::DenseMap<class llvm::StringRef, unsigned int, struct llvm::DenseMapInfo<class llvm::StringRef, void>, struct llvm::detail::DenseMapPair<class llvm::StringRef, unsigned int>>, class std::vector<struct std::pair<class llvm::StringRef, class llvm::BitcodeModule>, class std::allocator<struct std::pair<class llvm::StringRef, class llvm::BitcodeModule>>>> *, class std::vector<unsigned char, class std::allocator<unsigned char>> const &) C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\LTO\LTOBackend.cpp:668:0
17:01:04 #20 0x00007ff612ed6ae7 <lambda_51cf04bbbb9cfc9263f3cfeece7282d7>::operator() C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\LTO\LTO.cpp:1225:0
17:01:04 #21 0x00007ff612ee1727 `anonymous namespace'::InProcessThinBackend::runThinLTOBackendThread C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\LTO\LTO.cpp:1248:0
17:01:04 #22 0x00007ff612ed6520 <lambda_2762ba73044a280da963d9912b490b63>::operator() C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\LTO\LTO.cpp:1277:0
17:01:04 #23 0x00007ff612ed862a std::_Func_impl_no_alloc<std::_Binder<std::_Unforced,<lambda_2762ba73044a280da963d9912b490b63>,llvm::BitcodeModule &,std::reference_wrapper<llvm::ModuleSummaryIndex>,std::reference_wrapper<llvm::StringMap<std::unordered_set<unsigned __int64,std::hash<unsigned __int64>,std::equal_to<unsigned __int64>,std::allocator<unsigned __int64> >,llvm::MallocAllocator> const >,std::reference_wrapper<llvm::DenseSet<llvm::ValueInfo,llvm::DenseMapInfo<llvm::ValueInfo,void> > const >,std::reference_wrapper<std::map<unsigned __int64,enum llvm::GlobalValue::LinkageTypes,std::less<unsigned __int64>,std::allocator<std::pair<unsigned __int64 const ,enum llvm::GlobalValue::LinkageTypes> > > const >,std::reference_wrapper<llvm::DenseMap<unsigned __int64,llvm::GlobalValueSummary *,llvm::DenseMapInfo<unsigned __int64,void>,llvm::detail::DenseMapPair<unsigned __int64,llvm::GlobalValueSummary *> > const >,std::reference_wrapper<llvm::MapVector<llvm::StringRef,llvm::BitcodeModule,llvm::DenseMap<llvm::StringRef,unsigned int,llvm::DenseMapInfo<llvm::StringRef,void>,llvm::detail::DenseMapPair<llvm::StringRef,unsigned int> >,std::vector<std::pair<llvm::StringRef,llvm::BitcodeModule>,std::allocator<std::pair<llvm::StringRef,llvm::BitcodeModule> > > > > >,void>::_Do_call C:\.nuget\dd\vs2019_buildtools.16.11.9\tools\VC\Tools\MSVC\14.29.30133\include\functional:921:0
17:01:04 #24 0x00007ff6128781fc std::_Func_impl_no_alloc<class <lambda_3f890a8f4379cabfb886f101ac7ee7cd>, void>::_Do_call(void) C:\.nuget\dd\vs2019_buildtools.16.11.9\tools\VC\Tools\MSVC\14.29.30133\include\functional:920:0
17:01:04 #25 0x00007ff613ee1a8f <lambda_647dacfb2f54ceb9a051a40a222b4ef4>::operator() C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\lib\Support\ThreadPool.cpp:64:0
17:01:04 #26 0x00007ff613ee143e llvm::thread::ThreadProxy<std::tuple<<lambda_647dacfb2f54ceb9a051a40a222b4ef4> > > C:\code\llvm\llvm.packageci\externals\llvm-project\llvm\include\llvm\Support\thread.h:70:0
17:01:04 #27 0x00007ff613eaeb04 thread_start<unsigned int (__cdecl*)(void *),1> minkernel\crts\ucrt\src\appcrt\startup\thread.cpp:97:0
17:01:04 #28 0x00007ffb51707034 (C:\WINDOWS\System32\KERNEL32.DLL+0x17034)
17:01:04 #29 0x00007ffb52c42651 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x52651)
```

I have also tested with `-march=sandbridge` which equals crash and `-march=skylake` which works.

**Comment by tru** [comment]
I'll try to reduce it tomorrow.

**Comment by tru** [comment]
Ok this issue is a bit stranger than I originally thought. @sylvain-audi was able to reduce the test case to the following:

```
inline void*  operator new(size_t _Size, void* _Where) {
  return _Where;
}
template <typename T>
struct SmallVector {
  T Items[16];
  T *Begin = nullptr;
  unsigned Size = 0;
  template <class _T2>
  void _Construct_in_place3(T& _Obj, _T2&& val) {
    new (&_Obj) T(val);
  }
  template <typename ItTy>
  SmallVector(ItTy S, ItTy E)
  : Begin(&this->Items[0]){
    T* _Last = this->Begin;
    for (; S != E; ++S) {
        this->_Construct_in_place3(*_Last, *S);
        _Last++;
    }
  }
};
bool ExternalTest();
void MainFunc() {
  unsigned long long Values[] = { 1 };
  SmallVector<unsigned long long> Record{ Values, Values + 1 };
  if (ExternalTest()) {
    SmallVector<unsigned short> Elts2(Record.Items, Record.Items + Record.Size);
  }
}
```

This doesn't trigger a crash on Linux with clang - but it happens on Windows. But ONLY if the clang in question is built with MSVC and `/arch:AVX` - but it reproduced consistently - so I was able to bisect it to this commit: https://github.com/llvm/llvm-project/commit/55e4cd8485dc6308211f85c60559a373ae96873e by @RKSimon 

@RKSimon any idea why this commit could lead to bad things happening in MSVC?

I have a case where it reproduces 100% so if you need me to extract anymore data from it I can.

**Comment by tru** [comment]
Can now confirm that reverting this commit from `release/14.x` fixes the issue.

**Comment by RKSimon** [comment]
I have no good ideas tbh - what machine are you running it on?

One (very weak) hunch - in the patch could you try replacing the DWordClearOps variable SmallVector<SDValue> with SmallVector<SDValue, 4>? We haven't had the default size code for long so it might have been something in that?

**Comment by RKSimon** [comment]
Also, can you tell if its an non-aligned memory access? illegal instruction?

**Comment by tru** [comment]
Your hunch was correct

```
-      SmallVector<SDValue> DWordClearOps(4, DAG.getConstant(0, DL, MVT::i32));
+      SmallVector<SDValue, 4> DWordClearOps(4, DAG.getConstant(0, DL, MVT::i32));
```

This makes the crash go away.

**Comment by RKSimon** [comment]
CCing @silvasean who added the ```SmallVector<T>``` support

**Comment by davidbolvansky** [comment]
Which version of MSVC?

**Comment by tru** [comment]
I tested both 2019 16.10.11 and 2022 17.1.0.

**Comment by silvasean** [comment]
`SmallVector<T>` is just an alias for `SmallVector<T, N>` where N is an internally computed number. I wonder if the crash can be reproduced with `SmallVector<T, N>` where N is explicitly written with the same value internally computed by `SmallVector<T>`, or whether MSVC is somehow getting messed up by the automatic inference of N. You can get the inferred number by printing out `CalculateSmallVectorDefaultInlinedElements<T>::value`.

**Comment by tru** [comment]
I'll give this a try tomorrow.

**Comment by RKSimon** [comment]
Do we want to propose the ```SmallVector<SDValue, 4>``` fix for trunk and a 14.x cherry-pick?

**Comment by tru** [comment]
I think we need a fix for 14.0.1 at least. But I'll defer to you guys what the easiest fix is.

**Comment by silvasean** [comment]
Also, I'll mention that `CalculateSmallVectorDefaultInlinedElements<T>::value` depends on sizeof(T), so it can be different for 32 vs 64 bit hosts, ILP64 vs LP64, asserts vs no-asserts, debug vs release, etc.

**Comment by tru** [comment]
I printed the value from `CalculateSmallVectorDefaultInlinedElements<T>::value` and it's `3`, I am guessing this leads to some kind of alignment error? As expected `SmallVector<SDValue, 3>` also crashes. This is when MSVC has the argument `/arch:AVX` on the command line.

When compiling without `/arch:AVX` the value is still `3` so I am guessing this is a problem when the vector is a odd number and the AVX lowering in MSVC still tries to make magic with it? Sorry this is a bit over my head. Let me know if I can provide any more information.

Are we using SmallVector with the default value in many places? Then I think we need a fix for CalculateSmallVectorDefaultInlinedElements - otherwise we can probably just roll back this one.

**Comment by joker-eph** [comment]
This could very well be an issue with alignment indeed, but that may be a bug in MSVC. It seems worth reporting the reduced test case to Microsoft. Does it reproduce with the most recent MSVC available?

I don't think a fix in `CalculateSmallVectorDefaultInlinedElements` is doable unless we really know what the issue is: if this is a vectorizer issue then it is likely highly dependent on the exact code pattern involved.

**Comment by RKSimon** [comment]
MSVC getting the alignment of the stack wrong is not uncommon, often leading it to incorrectly use aligned vector loads. If we can report it with an independent repro that'd be fantastic.

I'll make the ```SmallVector<SDValue, 4>``` fix in X86ISelLowering.cpp

I don't know if we should consider rounding ```CalculateSmallVectorDefaultInlinedElements<T>::value``` up to nextPow2 on MSVC builds to avoid the bug more generally? I don't even know if this will work in all cases.

@rnk Do we have any MSVC 2 stage buildbots that build with /AVX? Or could we?

**Comment by tru** [comment]
> Does it reproduce with the most recent MSVC available?

At least the most recent 2022 version that's publicly available.

**Comment by tru** [comment]
> Do we have any MSVC 2 stage buildbots that build with /AVX? Or could we?

I was thinking about this, I was a bit surprised that this bug turned up at the first place since it should have been found in some testing. But then I realized that maybe the combination of MSVC + /arch:AVX is probably not a very well tested configuration. We only use it for the stage1 compiler and will probably switch to building stage1 with a binary distribution of clang instead to hit a more well tested target.

Do we even test building LLVM with anything but default settings for march/mtune on any OS?

**Comment by tru** [comment]
@silvasean any thoughts on a more permanent fix? I am worried that we use SmallVector with the default size in more places and all these can blow up when using MSVC.

**Comment by silvasean** [comment]
@tru did we actually root-cause the issue? I'd be fine with rounding up the default CalculateSmallVectorDefaultInlinedElements in some way on MSVC, but I'm not sure what the rounding policy should be. Rounding up to next power of 2 sounds a little aggressive to me, but I'm not an expert on these platforms. @RKSimon thoughts?

**Comment by dexonsmith** [comment]
> @tru did we actually root-cause the issue?

Yeah, I'm curious about this too.

Note that if the computed size is `3`, per https://github.com/llvm/llvm-project/issues/54645#issuecomment-1085542670,  then this vector was NEVER in small mode. From https://github.com/llvm/llvm-project/commit/55e4cd8485dc6308211f85c60559a373ae96873e:
```
      SmallVector<SDValue> DWordClearOps(4, DAG.getConstant(0, DL, MVT::i32));
```
Since the small storage was never used, it's not obvious (to me) how its alignment would matter...

Was the problem that it happened to throw off the alignment of whatever followed it on the stack? Or does the unused small storage somehow have some influence?

(Regardless, it doesn't make sense to use the default here. Either 0 for no small storage, or 4 for the exact size needed.)

**Comment by tru** [comment]
I don't think we (or at least I) understand the root cause for this yet. I looked at just testing to move `SmallVector` into it's own file and compile that with MSVC to see if that can reproduce the problem - but the file is very much intertwined with the rest of LLVM and I didn't see a quick and easy way to pull it out and run it separately.

Happy to help and try to diagnose the issue - but I think I need some pointers to what kind of information could be useful here.

**Comment by joker-eph** [comment]
What about the small reproducer you had posted in https://github.com/llvm/llvm-project/issues/54645#issuecomment-1084513789 ?

**Comment by RKSimon** [comment]
> Also, can you tell if its an non-aligned memory access? illegal instruction?

Have we been able to confirm that the crash is due to an aligned vector load (VMOVAPS or VMOVDQA probably) accessing a non-16-byte-aligned stack address?

**Comment by tru** [comment]
> What about the small reproducer you had posted in [#54645 (comment)](https://github.com/llvm/llvm-project/issues/54645#issuecomment-1084513789) ?

That reproducer is causing clang to crash when compiled with MSVC/AVX - not crash itself compiled with MSVC/AVX

**Comment by tru** [comment]
Ok figured out how to catch this in the debugger - it crashes here:

```
if (Ops[I].Val.getValueType() != MVT::Other)
```

The actual crash is:

```
Exception thrown at 0x00007FF6D77A71F9 in clang-cl.exe: 0xC0000005: Access violation reading location 0x0000019935EF9228.
```

Dissembling this part shows this (sorry for the screenshot - but I couldn't figure out how to copy and paste from the disasm view in vscode):

![image](https://user-images.githubusercontent.com/35614/161729416-f6b9d287-b637-405d-98c6-81f27732e90c.png)

**Comment by tstellar** [comment]
> /pull-request [llvmbot#144](https://github.com/llvmbot/llvm-project/pull/144)

Do we want to merge this to the release/14.x branch or are we waiting for a better fix?

**Comment by dexonsmith** [comment]
> > /pull-request [llvmbot#144](https://github.com/llvmbot/llvm-project/pull/144)
> 
> Do we want to merge this to the release/14.x branch or are we waiting for a better fix?

The current fix LGTM for release branch. I think this particular code should have an explicit small size anyway since it's using fixed-size data.

I think the ongoing discussion is just to figure out why it's *necessary*, to understand what issues might be buried elsewhere.

**Comment by RKSimon** [comment]
If at all possible it'd be great to see msvc /AVX and /AVX2 2-stage buildbots added so that we can start tracking this.

@sstamenova @rnk Are either of you to add additional bots?

**Comment by sstamenova** [comment]
> If at all possible it'd be great to see msvc /AVX and /AVX2 2-stage buildbots added so that we can start tracking this.
> 
> @sstamenova @rnk Are either of you to add additional bots?

I can't speak for Reid, but we're not able to right now. We're toying with the idea of maybe adding another `mlir` bot, but that's unlikely as well. I'll keep it in mind in case we get an opportunity, but I think it unlikely.

**Comment by tstellar** [comment]
Merged: ec13fed5867f674bb96ab5502629ec209ef5a73a

**Comment by tru** [comment]
Maybe we should at least warn it's not a tested setup.

**Comment by tru** [comment]
I think that's a bigger discussion - there is probably a lot of people building "unsupported" configurations. I think it makes sense to give warnings when people try to do a configuration that is known to have problems. Just listing and detecting the "supported" configurations is still a huge list.

I suggest we detect MSVC + /arch:AVX and say `This configuration is unsupported and known to have caused problems.` If we implement it generic enough people can add more known broken configurations to that list when they are detected.

**Comment by tstellar** [comment]
I'm removing the Release Milestone, since we've already merged a fix to the release branch and there still seems to be an outstanding issue in main.

**Comment by RKSimon** [comment]
Would we be better off splitting this into new tickets and resolving this one?
 - cmake warning for /AVX (and /AVX2?) builds
 - MSVC crash when built with /AVX - assuming we can provide a self contained test case

**Comment by tru** [comment]
I posted a diff for the CMake warning here: https://reviews.llvm.org/D123777

**Comment by tru** [comment]
Warning has landed. I will close this issue now, feel free to re-open if you think there is more we can do here. Thanks everyone helping out!

**Comment by LukeSkyw** [comment]
@tru I get a:
```
CMake Error at cmake/modules/CheckCompilerVersion.cmake:57 (if):
  if given arguments:

    "(" "GCC" "STREQUAL" "MSVC" ")" "AND" "(" "19.24" "VERSION_LESS_EQUAL" ")" "AND" "(" "VERSION_LESS" "19.25" ")"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/config-ix.cmake:15 (include)
  CMakeLists.txt:774 (include)
```
`CMAKE_CXX_COMPILER_ID` does not seem to be defined at the moment of execution.

**Comment by tru** [comment]
Sounds like a compiler setup problem to me. You should check what the CMake logs say. If compiler ID is not set it means CMake failed to find the compiler or can't recognise it.

**Comment by tru** [comment]
If you have problems with it still and think it's a bug in LLVMs code please file a new issue so we can have the discussion there instead.

**Comment by LukeSkyw** [comment]
Thanks @tru. Compilation goes fine for a while before failing this way, binaries are created. I doubt my compiler setup is the problem. Probably what I am trying to achieve: statically linked clang. Created the issue: https://github.com/llvm/llvm-project/issues/58073
