### ISSUE TITLE
Please backport 2e44b7872bc6 to LLVM 14.0.1 branch

### ISSUE THREAD

**Issue by frasercrmck** [llvm/llvm-project#54640]
This was an issue since LLVM 12 but testing apparently never caught it. It was found/fixed too late for the LLVM 14.0.0 release.

2e44b7872bc6

**Comment by tstellar** [comment]
@LebedevRI Is this safe to backport? https://github.com/llvm/llvm-project/commit/2e44b7872bc638ed884ae4aa86e38b3b47e0b65a

**Comment by LebedevRI** [comment]
lg
