### ISSUE TITLE
Optimise modulo comparison operation

### ISSUE THREAD

**Issue by ilinpv** [llvm/llvm-project#54650]
When the result of a modulo by constant is compared against another constant we can sometimes avoid the expensive modulo instructions as described in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87290

For example

```
int
mod16 (int a, int b)
{
  return a % 16 == 13;
}
```
with -O2 using this on aarch64 GCC produces better code: https://godbolt.org/z/9K8Gd1Eaf

**Comment by rotateright** [comment]
This seems more like a missed generic optimization in IR. Any compare of srem by power-of-2 can be turned into an 'and' mask pattern instead:
https://alive2.llvm.org/ce/z/6daHCq

**Comment by EugeneZelenko** [comment]
@ilinpv: please read comment for `beginner` label.

**Comment by ilinpv** [comment]
@EugeneZelenko could we keep `beginner` label for the ticket to have it in old filter ( compatible with old tickets using `beginner` label only ) ?

**Comment by EugeneZelenko** [comment]
@ilinpv: it was defined as redundant quite awhile ago, You could use `good first issue` in filter too.

**Comment by alexander-shaposhnikov** [comment]
Created https://reviews.llvm.org/D122942
