### ISSUE TITLE
[OpenMP] Possibly incorrect heap-to-stack conversion

### ISSUE THREAD

**Issue by dhruvachak** [llvm/llvm-project#54654]
libomptarget/test/offloading/bug51982.c is the test case. 
```
% ~/git/aomp-trunk/llvm-project/build$ clang -fopenmp  -fno-experimental-isel   -L ./runtimes/runtimes-bins/openmp/libomptarget -L ./runtimes/runtimes-bins/openmp/runtime/src  -fno-openmp-implicit-rpath -Wl,-rpath,./runtimes/runtimes-bins/openmp/libomptarget -Wl,-rpath,./runtimes/runtimes-bins/openmp/runtime/src --libomptarget-amdgcn-bc-path=./runtimes/runtimes-bins/openmp/libomptarget -fopenmp-targets=amdgcn-amd-amdhsa -O1 -Rpass=openmp-opt ../openmp/libomptarget/test/offloading/bug51982.c -o bug51982
../openmp/libomptarget/test/offloading/bug51982.c:12:1: remark: Rewriting generic-mode kernel with a customized state machine. [OMP131] [-Rpass=openmp-opt]
#pragma omp target map(tofrom : aa)
^
../openmp/libomptarget/test/offloading/bug51982.c:7:7: remark: Replaced globalized variable with 4 bytes of shared memory. [OMP111] [-Rpass=openmp-opt]
  int ng = 12;
      ^
../openmp/libomptarget/test/offloading/bug51982.c:14:1: remark: Moving globalized variable to the stack. [OMP110] [-Rpass=openmp-opt]
#pragma omp parallel for
^
% ~/git/aomp-trunk/llvm-project/build$ ./bug51982 
Aborted (core dumped)
```
I started with [D102107](https://reviews.llvm.org/D102107), rebased it on top of trunk, and tested it on amdgpu. The above test case fails at -O1 but passes at -O2. While debugging the -O1 failure, I found what appears to be an incorrect heap-to-stack conversion in OpenMPOpt phase. Here are the steps to repro:

(1) Use -v -save-temps that produces an intermediate bug51982-openmp-amdgcn-amd-amdhsa-gfx906-linked.bc. (Interestingly, usage of -save-temps adds the -disable-llvm-passes to the clang-15 command line, so I used opt to reproduce the above conversion. I verified that the same issue shows up with the clang-15 invocation if -disable-llvm-passes is removed.)

(2) In my environment, pass #158 is OpenMPOpt, so I ran it with bisect as below to get the .bc files before and after OpenMPOpt. Attached is a .ll file that you can use to generate the .bc file used for opt below. (github won't let me upload .ll file, so I renamed it to .txt)
```
% opt bug51982-openmp-amdgcn-amd-amdhsa-gfx906-linked.bc -O1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx906 -o bug51982-openmp-amdgcn-amd-amdhsa-gfx906-gfx906-optimized.bc -opt-bisect-limit=157 
% opt bug51982-openmp-amdgcn-amd-amdhsa-gfx906-linked.bc -O1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx906 -o bug51982-openmp-amdgcn-amd-amdhsa-gfx906-gfx906-optimized.bc -opt-bisect-limit=158
```
Comparing the pre- and post-IR, I see this difference (among others):
pre:
```
for.body:                                         ; preds = %for.cond
  %2 = addrspacecast %struct.anon addrspace(5)* %.tmp.outlined.agg.arg to i8*, !dbg !25
  %3 = call i8* @__kmpc_alloc_shared(i64 16), !dbg !25
  %4 = call i8* @__kmpc_alloc_aggregate_arg(i8* %2, i8* %3), !dbg !25
  %.fca.0.insert = insertvalue %struct.anon poison, i32* %ng_on_stack, 0, !dbg !25
  %.fca.1.insert = insertvalue %struct.anon %.fca.0.insert, i64* %aa, 1, !dbg !25
  %5 = bitcast i8* %4 to %struct.anon*, !dbg !25
  store %struct.anon %.fca.1.insert, %struct.anon* %5, align 8, !dbg !25
  call void @__kmpc_parallel_51(%struct.ident_t* addrspacecast (%struct.ident_t addrspace(1)* @6 to %struct.ident_t*), i32 %1, i32 1, i32 -1, i32 -1, i8* bitcast (void (i32*, i32*, %struct.anon*)* @__omp_outlined__ to i8*), i8* bitcast (void (i16, i32)* @__omp_outlined___wrapper to i8*), i8* %4), !dbg !25
  call void @__kmpc_free_shared(i8* %3, i64 16), !dbg !25
  %inc = add nsw i32 %gid.0, 1, !dbg !26
  br label %for.cond, !dbg !23, !llvm.loop !2
```
post:
```
for.body:                                         ; preds = %for.cond
  %2 = addrspacecast %struct.anon addrspace(5)* %.tmp.outlined.agg.arg to i8*, !dbg !24
  %3 = alloca i8, i64 16, align 1, addrspace(5)
  %malloc_cast = addrspacecast i8 addrspace(5)* %3 to i8*
  %4 = call i8* @__kmpc_alloc_aggregate_arg(i8* %2, i8* nocapture nofree %malloc_cast) #23, !dbg !24
  %.fca.0.insert = insertvalue %struct.anon poison, i32* %ng_on_stack, 0, !dbg !24
  %.fca.1.insert = insertvalue %struct.anon %.fca.0.insert, i64* %aa, 1, !dbg !24
  %5 = bitcast i8* %4 to %struct.anon*, !dbg !24
  store %struct.anon %.fca.1.insert, %struct.anon* %5, align 8, !dbg !24
  call void @__kmpc_parallel_51(%struct.ident_t* addrspacecast (%struct.ident_t addrspace(1)* @6 to %struct.ident_t*), i32 %1, i32 1, i32 -1, i32 -1, i8* bitcast (void (i32*, i32*, %struct.anon*)* @__omp_outlined__ to i8*), i8* bitcast (void (i16, i32)* @__omp_outlined___wrapper to i8*), i8* %4) #22, !dbg !24
  %inc = add nsw i32 %gid.0, 1, !dbg !25
  br label %for.cond, !dbg !22, !llvm.loop !26
```
--------------
Both are in generic mode
@__omp_offloading_802_1f42f03_main_l12_exec_mode = weak addrspace(1) constant i8 1

In generic mode, this heap-to-stack conversion appears incorrect since the corresponding location is passed to parallel_51. 

-------------

I ran opt built from main trunk on the corresponding .bc file (attached is the corresponding LL/txt file) but I got an assertion failure at -O1. Without OpenMPOpt (e.g. at -O0), I don't see any problem.
```
% opt bug51982-openmp-amdgcn-amd-amdhsa-gfx906-linked.bc -O1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx906 -o bug51982-openmp-amdgcn-amd-amdhsa-gfx906-gfx906-optimized.bc
opt: /home/dhchakra/git/aomp-trunk/llvm-project/llvm/lib/Transforms/IPO/OpenMPOpt.cpp:3055: virtual llvm::ChangeStatus {anonymous}::AAHeapToSharedFunction::manifest(llvm::Attributor&): Assertion `Alignment && "HeapToShared on allocation without alignment attribute"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: opt bug51982-openmp-amdgcn-amd-amdhsa-gfx906-linked.bc -O1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx906 -o bug51982-openmp-amdgcn-amd-amdhsa-gfx906-gfx906-optimized.bc
 #0 0x000055908692cec4 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x000055908692a664 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007fc89dd803c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x143c0)
 #3 0x00007fc89d81d03b raise /build/glibc-sMfBJT/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #4 0x00007fc89d7fc859 abort /build/glibc-sMfBJT/glibc-2.31/stdlib/abort.c:81:7
 #5 0x00007fc89d7fc729 get_sysdep_segment_value /build/glibc-sMfBJT/glibc-2.31/intl/loadmsgcat.c:509:8
 #6 0x00007fc89d7fc729 _nl_load_domain /build/glibc-sMfBJT/glibc-2.31/intl/loadmsgcat.c:970:34
 #7 0x00007fc89d80e006 (/lib/x86_64-linux-gnu/libc.so.6+0x34006)
 #8 0x00005590861a4ecd (anonymous namespace)::AAHeapToSharedFunction::manifest(llvm::Attributor&) (.part.0) OpenMPOpt.cpp:0:0
 #9 0x000055908604b49f llvm::Attributor::manifestAttributes() (/home/dhchakra/git/aomp-trunk/llvm-project/build/bin/opt+0x1a2649f)
#10 0x0000559086056413 llvm::Attributor::run() (/home/dhchakra/git/aomp-trunk/llvm-project/build/bin/opt+0x1a31413)
#11 0x00005590861ad1d1 (anonymous namespace)::OpenMPOpt::runAttributor(bool) (.part.0) OpenMPOpt.cpp:0:0
#12 0x00005590861b1144 (anonymous namespace)::OpenMPOpt::run(bool) OpenMPOpt.cpp:0:0
#13 0x00005590861b2010 llvm::OpenMPOptPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/dhchakra/git/aomp-trunk/llvm-project/build/bin/opt+0x1b8d010)
#14 0x0000559086c613c6 llvm::detail::PassModel<llvm::Module, llvm::OpenMPOptPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/dhchakra/git/aomp-trunk/llvm-project/build/bin/opt+0x263c3c6)
#15 0x0000559085f7b73f llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/dhchakra/git/aomp-trunk/llvm-project/build/bin/opt+0x195673f)
#16 0x0000559084cdff0b llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::StringRef>, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool) (/home/dhchakra/git/aomp-trunk/llvm-project/build/bin/opt+0x6baf0b)
#17 0x0000559084c5a2fc main (/home/dhchakra/git/aomp-trunk/llvm-project/build/bin/opt+0x6352fc)
#18 0x00007fc89d7fe0b3 __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:342:3
#19 0x0000559084cd31de _start (/home/dhchakra/git/aomp-trunk/llvm-project/build/bin/opt+0x6ae1de)
Aborted (core dumped)
```
-------------------------
I also noticed that promotion from generic to spmd is not occurring any more on the IR with the aggregate code. This should be reproducible using opt from main trunk on the attached IR. Note that main trunk clang still generates spmd mode when directly applied to this test case.
[bug51982-openmp-amdgcn-amd-amdhsa-gfx906-linked.txt](https://github.com/llvm/llvm-project/files/8383312/bug51982-openmp-amdgcn-amd-amdhsa-gfx906-linked.txt)

This is what I get from clang from the rebased patch, at -O1 and -O2, sample command-line at the top of this issue. 
```
bug51982.c:12:1: remark: Rewriting generic-mode kernel with a customized state machine. [OMP131] [-Rpass=openmp-opt]
#pragma omp target map(tofrom : aa)
^
bug51982.c:7:7: remark: Replaced globalized variable with 4 bytes of shared memory. [OMP111] [-Rpass=openmp-opt]
  int ng = 12;
      ^
bug51982.c:14:1: remark: Moving globalized variable to the stack. [OMP110] [-Rpass=openmp-opt]
#pragma omp parallel for
^
```

**Comment by jdoerfert** [comment]
What version of `opt` are you running above? If I run a recent one there is no heap2stack happening. Heap2shared kicks in though (creating `@_shared`), which is fine:

```
  for.body:                                         ; preds = %for.cond
    %2 = addrspacecast %struct.anon addrspace(5)* %.tmp.outlined.agg.arg to i8*, !dbg !31                                                                                                      
    %3 = call i8* @__kmpc_alloc_aggregate_arg(i8* %2, i8* nofree addrspacecast (i8 addrspace(3)* getelementptr inbounds ([16 x i8], [16 x i8] addrspace(3)* @_shared, i32 0, i32 0) to i8*)) #@
    %.fca.0.insert = insertvalue %struct.anon poison, i32* %ng_on_stack, 0, !dbg !31
    %.fca.1.insert = insertvalue %struct.anon %.fca.0.insert, i64* %aa, 1, !dbg !31
    %4 = bitcast i8* %3 to %struct.anon*, !dbg !31
    store %struct.anon %.fca.1.insert, %struct.anon* %4, align 8, !dbg !31
    call void @__kmpc_parallel_51(%struct.ident_t* addrspacecast (%struct.ident_t addrspace(1)* @6 to %struct.ident_t*), i32 %1, i32 1, i32 -1, i32 -1, i8* bitcast (void (i32*, i32*, %struct@
    %inc = add nsw i32 %gid.0, 1, !dbg !32
    br label %for.cond, !dbg !29, !llvm.loop !33

```

(Don't forget to add the alignment to the kmpc_alloc_shared calls as you otherwise get the assertion.)

---

SPMD-zation does not happen because we also need to tell OpenMP-opt that `__kmpc_alloc_aggregate_arg` can be executed in SPMD-mode w/o problem.
We would do that adding it to the switch in OpenMP-opt.
Further, the type of `__kmpc_parallel_51` changed. While the patch has the adjustment, my local version does not.
With both of those we should get SPMD-mode again, so just add `__kmpc_alloc_aggregate_arg` to the switch if you have the patch applied.

**Comment by dhruvachak** [comment]
> What version of `opt` are you running above? If I run a recent one there is no heap2stack happening. Heap2shared kicks in though (creating `@_shared`), which is fine:
> 
This is opt from the rebased patch on top of main as of yesterday. So there is something in the rebased patch that is triggering the heap2stack promotion.

**Comment by dhruvachak** [comment]
Yes, after adding __kmpc_alloc_aggregate_arg to the switch in OpenMPOpt, I see SPMDization. But the heap2stack promotion in generic mode still remains to be understood.

**Comment by dhruvachak** [comment]
Earlier, I used opt from D102107 rebased on main. 

But I found out why opt from main did not repro the heap2stack promotion -- because of missing attributes in the new API. I patched my main branch with the following diff pulled out of D102107 and reproduced the heap2stack promotion on this patched main. Can you please try this patch on your main branch? I am not sure how the attributor uses these attributes and whether they need an adjustment. 

`diff --git a/llvm/include/llvm/Frontend/OpenMP/OMPKinds.def b/llvm/include/llvm/Frontend/OpenMP/OMPKinds.def
index b110eea959df..4a813457b8cd 100644
--- a/llvm/include/llvm/Frontend/OpenMP/OMPKinds.def
+++ b/llvm/include/llvm/Frontend/OpenMP/OMPKinds.def
@@ -457,6 +457,7 @@ __OMP_RTL(__kmpc_free_shared, false, Void, VoidPtr, SizeTy)
 __OMP_RTL(__kmpc_begin_sharing_variables, false, Void, VoidPtrPtrPtr, SizeTy)
 __OMP_RTL(__kmpc_end_sharing_variables, false, Void, )
 __OMP_RTL(__kmpc_get_shared_variables, false, Void, VoidPtrPtrPtr)
+__OMP_RTL(__kmpc_alloc_aggregate_arg, false, VoidPtr, VoidPtr, VoidPtr)
 __OMP_RTL(__kmpc_parallel_level, false, Int8, )
 __OMP_RTL(__kmpc_is_spmd_exec_mode, false, Int8, )
 __OMP_RTL(__kmpc_barrier_simple_spmd, false, Void, IdentPtr, Int32)
@@ -916,6 +917,9 @@ __OMP_RTL_ATTRS(__kmpc_alloc_shared, AttributeSet(
 __OMP_RTL_ATTRS(__kmpc_free_shared, DeviceAllocAttrs, AttributeSet(),
                 ParamAttrs(NoCaptureAttrs))
 
+__OMP_RTL_ATTRS(__kmpc_alloc_aggregate_arg, DefaultAttrs, ReturnPtrAttrs,
+                ParamAttrs(NoCaptureAttrs, NoCaptureAttrs))
+
 __OMP_RTL_ATTRS(__kmpc_alloc, DefaultAttrs, ReturnPtrAttrs, ParamAttrs())
 __OMP_RTL_ATTRS(__kmpc_aligned_alloc, DefaultAttrs, ReturnPtrAttrs,
                 ParamAttrs())
`

**Comment by jdoerfert** [comment]
> Earlier, I used opt from D102107 rebased on main.
> 
> But I found out why opt from main did not repro the heap2stack promotion -- because of missing attributes in the new API. I patched my main branch with the following diff pulled out of D102107 and reproduced the heap2stack promotion on this patched main. Can you please try this patch on your main branch? I am not sure how the attributor uses these attributes and whether they need an adjustment.
> 
> ```
> diff --git a/llvm/include/llvm/Frontend/OpenMP/OMPKinds.def b/llvm/include/llvm/Frontend/OpenMP/OMPKinds.def
> index b110eea959df..4a813457b8cd 100644
> --- a/llvm/include/llvm/Frontend/OpenMP/OMPKinds.def
> +++ b/llvm/include/llvm/Frontend/OpenMP/OMPKinds.def
> @@ -457,6 +457,7 @@ __OMP_RTL(__kmpc_free_shared, false, Void, VoidPtr, SizeTy)
>  __OMP_RTL(__kmpc_begin_sharing_variables, false, Void, VoidPtrPtrPtr, SizeTy)
>  __OMP_RTL(__kmpc_end_sharing_variables, false, Void, )
>  __OMP_RTL(__kmpc_get_shared_variables, false, Void, VoidPtrPtrPtr)
> +__OMP_RTL(__kmpc_alloc_aggregate_arg, false, VoidPtr, VoidPtr, VoidPtr)
>  __OMP_RTL(__kmpc_parallel_level, false, Int8, )
>  __OMP_RTL(__kmpc_is_spmd_exec_mode, false, Int8, )
>  __OMP_RTL(__kmpc_barrier_simple_spmd, false, Void, IdentPtr, Int32)
> @@ -916,6 +917,9 @@ __OMP_RTL_ATTRS(__kmpc_alloc_shared, AttributeSet(
>  __OMP_RTL_ATTRS(__kmpc_free_shared, DeviceAllocAttrs, AttributeSet(),
>                  ParamAttrs(NoCaptureAttrs))
>  
> +__OMP_RTL_ATTRS(__kmpc_alloc_aggregate_arg, DefaultAttrs, ReturnPtrAttrs,
> +                ParamAttrs(NoCaptureAttrs, NoCaptureAttrs))
> +
>  __OMP_RTL_ATTRS(__kmpc_alloc, DefaultAttrs, ReturnPtrAttrs, ParamAttrs())
>  __OMP_RTL_ATTRS(__kmpc_aligned_alloc, DefaultAttrs, ReturnPtrAttrs,
>                  ParamAttrs())
> ```

This is the alloca_aggregate_arg function:
```
void *__kmpc_alloc_aggregate_arg(void *LocalPtr, void *GlobalPtr) {
  return (__kmpc_is_spmd_exec_mode() ? LocalPtr : GlobalPtr);
}
```
As you see, it may return either argument. As such, they are considered captured. Your patch above marks them as nocapture, which is then probably the source of all your troubles.

**Comment by dhruvachak** [comment]
Thanks. Removing the nocapture fixes this problem. Closing this issue.
