### ISSUE TITLE
On Linux, build fails with "Fatal error: bad defsym; format is --defsym name=value"

### ISSUE THREAD

**Issue by vonbrand** [llvm/llvm-project#54673]
This is Fedora 35, x86_64, `/usr/bin/as` is from binutils-2.37-10.fc35.x86_64
Full message:

[4/3449] Building ASM object lib/Support/BLAKE3/CMakeFiles/LLVMSupportBlake3.dir/blake3_avx512_x86-64_unix.S.o
FAILED: lib/Support/BLAKE3/CMakeFiles/LLVMSupportBlake3.dir/blake3_avx512_x86-64_unix.S.o 
/usr/bin/as --defsym GTEST_HAS_RTTI=0 --defsym _GNU_SOURCE --defsym __STDC_CONSTANT_MACROS --defsym __STDC_FORMAT_MACROS --defsym __STDC_LIMIT_MACROS -I/home/vonbrand/tmp/LLVM/llvm-project/build/lib/Support/BLAKE3 -I/home/vonbrand/tmp/LLVM/llvm-project/llvm/lib/Support/BLAKE3 -I/home/vonbrand/tmp/LLVM/llvm-project/build/include -I/home/vonbrand/tmp/LLVM/llvm-project/llvm/include -fPIC -mavx512vl --MD lib/Support/BLAKE3/CMakeFiles/LLVMSupportBlake3.dir/blake3_avx512_x86-64_unix.S.o.d -o lib/Support/BLAKE3/CMakeFiles/LLVMSupportBlake3.dir/blake3_avx512_x86-64_unix.S.o -c /home/vonbrand/tmp/LLVM/llvm-project/llvm/lib/Support/BLAKE3/blake3_avx512_x86-64_unix.S
Assembler messages:
Fatal error: bad defsym; format is --defsym name=value

**Comment by arsenm** [comment]
Old build issue
