### ISSUE TITLE
[Flang] Implement semantic check for privatization of statement function variables

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#54677]
The [OpenMP standard](https://www.openmp.org/wp-content/uploads/OpenMP-API-Specification-5-2.pdf) (page 108,  Section 4.3) says that "Variables that appear in namelist statements, in variable format expressions, and in expressions for statement function definitions, must not be privatized."

This check was implemented in https://reviews.llvm.org/D93213. This has to be [reverted](https://reviews.llvm.org/D122650) due to some ordering issues.

This ticket is a reminder to re-implement this check.

**Comment by tblah** [comment]
RFC here https://discourse.llvm.org/t/rfc-openmp-remove-support-for-privatisation-of-statement-function-variables/81138
