### ISSUE TITLE
llvm.sh not installing for Ubuntu 20.04 (focal)

### ISSUE THREAD

**Issue by StephenMcConnel** [llvm/llvm-project#54676]
When I download and run "sudo ./llvm.sh" on my Ubuntu 20.04 (x86_64/amd64) system, I get the following message at the end:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clang-14 : Depends: libobjc-9-dev but it is not going to be installed
            Depends: libclang-common-14-dev (= 1:14.0.0~++20220329040648+3f43d803382d-1~exp1~20220329160738.107) but it is not going to be installed
            Recommends: llvm-14-dev but it is not going to be installed
 clangd-14 : Depends: libclang-common-14-dev (= 1:14.0.0~++20220329040648+3f43d803382d-1~exp1~20220329160738.107) but it is not going to be installed
 lldb-14 : Depends: llvm-14-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by michaelvlach** [comment]
Not a solution but possibly a workaround. I found `llvm.sh` not to be very reliable so do essentially what it does internally and I ended up with:
```
readonly llvmVersion=14
sudo apt-get update -y
sudo apt-get install -y lsb-release wget software-properties-common apt-utils
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
sudo add-apt-repository -y "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-${llvmVersion} main"
sudo apt-get update -y
```
and after that you can just for example:
```
sudo apt-get install clang-${llvmVersion}
```
or whatever component(s) you need.

**Comment by MarcoFalke** [comment]
The script works for me on a fresh install of Ubuntu 20.04. Maybe your system is holding incompatible packages?
