### ISSUE TITLE
Backport "[libcxx] [test] Avoid spurious test breakage in clang-cl-dll configs with newer CMake" to the 14.x branch

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#54687]
This should avoid spurious failures if the Windows premerge bots are updated with a newer version of CMake.

**Comment by tstellar** [comment]
@mordante What do you think about backporting this? https://github.com/llvm/llvm-project/commit/b048397db8027fedf9380e7cf9213239d558fa29

**Comment by mordante** [comment]
I think it's a good idea to backport this patch.

**Comment by tstellar** [comment]
Merged: a4681df0202c
