### ISSUE TITLE
parameter types are not renamed when fixing readability-identifier-naming.TypedefCase

### ISSUE THREAD

**Issue by LukasHanel** [llvm/llvm-project#54699]
Using clang-tidy, I try to rename typedefs, and find that clang-tidy fixes the header and variable declarations, but not parameter types in function signatures.
It is similar to this issue: https://github.com/llvm/llvm-project/issues/47147
I could not find other open issue, so I report it.

Using clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-, working with c .h and .c files.

### .clang-tidy
```
Checks: "-*,readability-identifier-naming"
CheckOptions:
    - key:      readability-identifier-naming.TypedefCase
      value:    'camelBack'
    - key:      readability-identifier-naming.TypedefSuffix
      value:    '_t'
```

### test.h
```
typedef struct {
    int x;
} ABC;

```
### test.c
```
#include "test.h"
void fun(ABC a) {
    ABC b;
    size s=sizeof(ABC);
    ABC *c  = (ABC *)NULL;
}
```

is rewritten
### test.h
```
typedef struct {
    int x;
} abc_t;

```
### test.c
```
#include "test.h"
void fun(ABC a) {
    abc_t b;
    size s=sizeof(ABC);
    ABC *c  = (ABC *)NULL;
}
```

Type of parameter `a` not renamed.
Type ABC in sizeof is not renamed.
Pointer Type ABC*  is not renamed.
Type ABC in cast is not renamed.

**Comment by DavidKeller** [comment]
I'm hitting this as well with `clang version 14.0.0 (Fedora 14.0.0-1.fc36)`

**.clang-tidy**
```
Checks: '-*,readability-identifier-naming'
CheckOptions:
  - { key: readability-identifier-naming.TypeAliasCase, value: CamelCase}
```

**test.hpp**
```
using type_to_rename = int;

void f(type_to_rename);
```
->

**test.hpp**
```
using TypeToRename = int;

TypeToRename f(type_to_rename);
```

So there is 2 problems here:

1. The argument type is not updated
2. The return type is incorrectly updated

It seems that fix applies incorrectly to the return type instead of the argument.

**Comment by PiotrZSL** [comment]
Interesting:

Clang-tidy 14-17:

```
test.hpp:1:7: warning: invalid case style for type alias 'TypeToRename' [readability-identifier-naming]
using TypeToRename = int;
      ^~~~~~~~~~~~
      typeToRename
```

But --fix does not change parameters, does not update .cpp file, and provide invalid fix:
```
typeToRename f(TypeToRename);
```

But with #66835 this looks like this:
```
test.hpp:1:7: warning: invalid case style for type alias 'TypeToRename' [readability-identifier-naming]
    1 | using TypeToRename = int;
      |       ^~~~~~~~~~~~
      |       typeToRename
    2 |
    3 | void f(TypeToRename);
      |        ~~~~~~~~~~~~
      |        typeToRename
test.cpp:3:8: note: FIX-IT applied suggested code changes
    3 | void f(TypeToRename) {
      |        ^
test.hpp:1:7: note: FIX-IT applied suggested code changes
    1 | using TypeToRename = int;
      |       ^
test.hpp:3:8: note: FIX-IT applied suggested code changes
    3 | void f(TypeToRename);
```

So #66835 will fix this issue also.
