### ISSUE TITLE
[clang] Missed optimization: Bitwise & generates worse code than && for booleans

### ISSUE THREAD

**Issue by AMS21** [llvm/llvm-project#54692]
Given the following source code: [godbolt link](https://godbolt.org/z/Kvc8fTxMh)

```cpp
bool is_ctrl_1(const char c) { return (c >= 0 && c <= 31) | (c == 127); }

bool is_ctrl_2(const char c) { return (c >= 0 & c <= 31) | (c == 127); }

bool is_ctrl_3(const char c) { return (c >= 0 & c <= 31) || (c == 127); }
```

compiling with `-O3`. We get the following assembly:

```asm
is_ctrl_1(char):                          # @is_ctrl_1(char)
        cmp     dil, 32
        setb    cl
        cmp     dil, 127
        sete    al
        or      al, cl
        ret
is_ctrl_2(char):                          # @is_ctrl_2(char)
        mov     eax, edi
        not     al
        shr     al, 7
        cmp     dil, 32
        setl    cl
        and     cl, al
        cmp     dil, 127
        sete    al
        or      al, cl
        ret
is_ctrl_3(char):                          # @is_ctrl_3(char)
        mov     eax, edi
        not     al
        shr     al, 7
        cmp     dil, 32
        setl    cl
        and     cl, al
        cmp     dil, 127
        sete    al
        or      al, cl
        ret
```

As you can see `is_ctrl_2` and `is_ctrl_3` generates more assembly which is not optimal and could be the same as `is_ctrl_1`. GCC does generate the exact same assembly for all 3 functions.
Note using `||` instead of `|` in `is_ctrl_1` doesn't change the generated code.

**Comment by vfdff** [comment]
all should be same with logic version:

bool is_ctrl_4(const char c) { return (c >= 0 && c <= 31) || (c == 127); }

**Comment by nikic** [comment]
We don't really need the second part of the condition: https://godbolt.org/z/Wc9bc55bK Something pretty wild going on there.

**Comment by bcl5980** [comment]
it looks we have a combine in transformZExtICmp:
  zext (x >s -1) to i32 --> (x>>u31)^1
This optimization break further combinations.

**Comment by rotateright** [comment]
> it looks we have a combine in transformZExtICmp: zext (x >s -1) to i32 --> (x>>u31)^1 This optimization break further combinations.

Yes, that transform is implemented poorly (can create up to 2 extra instructions), and it's generally the wrong direction for IR. InstCombine favored bit-hacks over more direct compare code at the start, and we've been slowly reversing that.

I'm working on a patch to invert that transform.

**Comment by rotateright** [comment]
Reopening - the patch was reverted because it can lead to infinite loops in instcombine.
