### ISSUE TITLE
[AMDGPU][MC][GFX1030] v_dot2c_f32_f16 and v_dot4c_i32_i8 have incorrect _e32 suffices

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#54691]
These opcodes cannot be promoted to VOP3, however they have _e32 suffix when disassembled.

An example of failed test:

    0x01,0x04,0x0a,0x04

Expected result:

    v_dot2c_f32_f16 v5, s1, v2

Actual output:

    v_dot2c_f32_f16_e32 v5, s1, v2

**Comment by shiltian** [comment]
I'm working on this issue. Is there place that documents which VOP2 instructions can be encoded as VOP3? I didn't find it from the reference guide. It looks like https://llvm.org/docs/AMDGPU/AMDGPUAsmGFX1030.html might have some points. I noticed there is a VOP2 instruction `v_max_f16` as well as a VOP3 version `v_max_f16_e64`. Does it imply that if a VOP2 instruction doesn't have a VOP3 version, it can't be encoded as VOP3?

**Comment by arsenm** [comment]
> I'm working on this issue. Is there place that documents which VOP2 instructions can be encoded as VOP3? I didn't find it from the reference guide. It looks like https://llvm.org/docs/AMDGPU/AMDGPUAsmGFX1030.html might have some pointers. I noticed there is a VOP2 instruction `v_max_f16` as well as a VOP3 version `v_max_f16_e64`. Does it imply that if a VOP2 instruction doesn't have a `_e32` version, it can't be encoded as VOP3?

You're better off reading the [ISA manuals](https://gpuopen.com/amd-isa-documentation/). The unfortunate naming convention is we have _e32 for vop1/vop2 variants and _e64 for vop3 variants of instructions. Most VOP1/VOP2 instructions are available in a VOP3 encoding which supports all types of operands in all sources. The assembler supports the un-suffixed names and figures out the optimal encoding
