### ISSUE TITLE
Suboptimal bitfield insertions arm64

### ISSUE THREAD

**Issue by uncleasm** [llvm/llvm-project#54696]
In a case, where the intent is to copy a nibble 0x0000F000 to 0x000000F0, clang trunk
seems to perform almost optimally, except of using two LSR shifts in succession (see https://godbolt.org/z/oMP5Ya78b)

```
uint32_t copy_hex_nibble_from_4_to_1(uint32_t a) {
    auto b = (a >> 20) & 15;
    a &= ~0x00f0;
    a |= b << 4;
    return a;
}
        lsr     w8, w0, #16
        lsr     w8, w8, #4
        bfi     w0, w8, #4, #4
```

Obviously the shifting could happen with a single instruction `lsr w8, w0, #20`

**Comment by bcl5980** [comment]
It looks this case is not easy to fix on IR and SelectionDAG, maybe we need to fix on backend.
I will send a patch fix it on backend but if someone have better solution on IR or DAG I will abandon the backend patch.
