### ISSUE TITLE
[OpenMP] Nondeterministic failures on Windows, x86

### ISSUE THREAD

**Issue by natgla** [llvm/llvm-project#54708]
[pf7.zip](https://github.com/llvm/llvm-project/files/8401036/pf7.zip)

Compile attached file with x86 clang/llvm 14.0.0 on Windows:

clang -O0 -fopenmp pf7.cpp

forever.cmd:
:start
a.exe
if "%errorlevel%" == "0" goto :start

run forever.cmd
in ~10 min it's crashing.

More details:
I've noticed the crash first when compiling this test with MSVC compiler:
cl  -Od  -openmp:llvm pf7.cpp /Zi
run in a loop, fails in ~ 10 min

libomp140.dll has debug info, the stack from there:

STACK_TEXT:  
0608ef58 5bcca66e     00000000 0608efc0 00000000 libomp140_i386!__kmp_wait_template<kmp_flag_64,1,0,1>+0x1f
0608efd4 5bcc9679     00000001 00000000 00000024 libomp140_i386!__kmp_hyper_barrier_release+0xbe
0608f020 5bcb719b     00000024 fffffffe 00cc2a00 libomp140_i386!__kmp_fork_barrier+0x1d9
0608f044 5bce67c7     00cc2a00 00000000 00000000 libomp140_i386!__kmp_launch_thread+0x3b
0608fb8c 763cfa29     00cc2a00 763cfa10 0608fbf8 libomp140_i386!__kmp_launch_worker+0x147
0608fb9c 77177a7e     00cc2a00 778ec5a0 00000000 kernel32!BaseThreadInitThunk+0x19
0608fbf8 77177a4e     ffffffff 77198a1b 00000000 ntdll!__RtlUserThreadStart+0x2f
0608fc08 00000000     5bce6680 00cc2a00 00000000 ntdll!_RtlUserThreadStart+0x1b

The test case has nested parallel region, everything else is irrelevant (I was able to crash it without pragma omp atomic, just takes longer). Let me know if you need more details

**Comment by jpeyton52** [comment]
Hello! Thanks for reporting this. I need just a little more information:
1) What machine are you running on?
2) Are you compiling libomp140.dll with visual studio or clang?
3) What version of visual studio are you using?

**Comment by natgla** [comment]
(1) computer: HP Z240 with windows. Intel Core i7-7700, 4 cores, 8 logical processors, 32GB Ram
(2) I compile libomp140.dll and libomp.dll with visual studio (libomp140.dll - you can take one which ships with Visual studio)
(3) verion of visual studio: VS 2022 and I've seen same with VS 2019
(4) Here is a dump from one of attempts if it'll be helpful:
[parallelIf7.exe.389072.dmp.zip](https://github.com/llvm/llvm-project/files/8592622/parallelIf7.exe.389072.dmp.zip)

**Comment by jpeyton52** [comment]
Patch to fix this is posted: https://reviews.llvm.org/D125013
I ran three instances of the forever script for 24 hours without issue after the patch.

**Comment by natgla** [comment]
@jpeyton52: did you get forever script to fail first? For me it's still crashing even with this change (I applied the change on top of llvm, main branch, on ef7f6f7cd7f7956c8bebaf8b29a9895ebbd35af2 commit, Feb 23. I'll try the latest, but from the context I see these files didn't change much if at all

**Comment by jpeyton52** [comment]
@natgla , I did replicate the issue using the forever script. Whenever I was running it would crash when referencing the `__kmp_threads` (within 10's of minutes) array leading to the discovery of the reallocation problem mentioned in the D125013 review. I'm trying some further investigation to see what else might be amiss.

**Comment by jpeyton52** [comment]
@natgla, 

I've tried multiple configurations to get the bug to reproduce, but unfortunately it only occurs when using the libomp140.dll from Visual Studio 2019. It always fails right where your .dmp file shows in `__kmp_wait_template`. Whenever I try to use a newer libomp140.i386.dll (even one built from ef7f6f7), I cannot get it to reproduce.

The dump file you gave to me showed the libomp140.i386.dll used was from C:\Windows\System32\libomp140.i386.dll where Visual Studio pulls from. The only way I can get pf7.exe to use a different DLL is to put the target DLL in the same directory as pf7.exe, otherwise it always wants to use the Visual Studio DLL. Can you make sure that when you rebuild the library, you are using the newer DLL?

If you are and you are able to reproduce, could you try running the program with a Debug version of libomp140.i386.dll and seeing if you could send the core dump + pdb + DLL of that?

**Comment by natgla** [comment]
will try to get another dump. 
Yes, I know that system32 is the preferred location to search for dlls. To ensure that I don't use any random old libomp dll I always rename all openmp-related dlls in c:\windows\system32 and in wow64, so openmp tests can't run if I don't have environment set up with a fresh dll.

**Comment by natgla** [comment]
@jpeyton52,
Short: thank you, your patch fixes the issue! Can you please proceed with the checkin?

Long: sorry, life was hectic, and I collected more dumps only today.
here is my system32:

f:\repros\parallelIf>dir c:\Windows\System32\libomp140.x86_64.dll
 Volume in drive C is OSDisk
..
 Directory of c:\Windows\System32

File Not Found

I have fresh libomp140 on the path.

Yet when I examined the dump here is what I see:
0:030> lmDvmlibomp140_i386
Browse full module list
start    end        module name
53f50000 53fe1000   libomp140_i386   (private pdb symbols)  C:\ProgramData\dbg\sym\libomp140.i386.pdb\81EE081CC67547C8860D264308F39A212\libomp140.i386.pdb
    Loaded symbol image file: libomp140.i386.dll
    Image path: C:\Windows\System32\libomp140.i386.dll
    Image name: libomp140.i386.dll
    Browse all global symbols  functions  data
    Timestamp:        Sat Mar 26 09:18:54 2022 (623F3CEE)

Looks like Windows cashed this for me somewhere :(

After I copied all needed dlls into the current folder it stopped crashing (ran several hours).

Never thought Windows will be _that_ helpful.

Thank you!

**Comment by jpeyton52** [comment]
No problem :) ! Thanks again for bringing this issue to our attention.
