### ISSUE TITLE
[LLD] Undefined symbol `__gxx_personality_v0` when linking with lld

### ISSUE THREAD

**Issue by Kmeakin** [llvm/llvm-project#54701]
`lld` reports an undefined symbol, while `ld` is able to link this without issue:

main.c:
```c
int main() {}
```

foo.cpp:
```c
inline void f() {}

class Class1 {
public:
  virtual ~Class1() {}
};

class Class2 : Class1 {
public:
  Class2();
};

Class2::Class2() { f(); }
```

```
clang++ -O0 -c foo.cpp -o foo.o
clang -O0 -c main.c -o main.o
clang main.o foo.o -Wl,--gc-sections -fuse-ld=lld
```
produces
```
ld.lld: error: undefined symbol: __gxx_personality_v0
>>> referenced by foo.cpp
>>>               foo.o:(DW.ref.__gxx_personality_v0)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

but removing `-fuse-ld=lld` produces no issues.

`clang --version`:
```
Ubuntu clang version 15.0.0-++20220321012320+9aa52ba574ad-1~exp1~20220321012418.363
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

`ld.lld --version`:
```
Ubuntu LLD 15.0.0 (compatible with GNU linkers)
```

**Comment by MaskRay** [comment]
Usage error. You need to link with `clang++` instead of `clang`. The only difference for the link action is whether the C++ standard library (libstdc++ or libc++/libc++abi) is linked. `__gxx_personality_v0` is defined in libsupc++ in libstdc++, and libc++abi.

**Comment by Kmeakin** [comment]
I believe this should be considered a bug. `lld` is described as "a drop in replacement for bfd and gold". This implies that it should be possible to append `-fuse-ld=lld` to a compiler invocation and get the same behavior.

**Comment by MaskRay** [comment]
https://maskray.me/blog/2020-12-19-lld-and-gnu-linker-incompatibilities See the first few paragraphs around "Piotr Kubaj said that this is a probably more of a marketing term than a technical term, the term tries to lure existing users into thinking "it's the same you know, but better!". "

As I mentioned, clang -fuse-ld=bfd failed for me. The case that it does not fail for you may be a bug, or could be a Ubuntu specific bug. This is not such a widespread thing that we should seek for bug-for-bug compatibility.

**Comment by smithp35** [comment]
FWIW I can't reproduce either on Ubuntu18.04 with a recent clang (rebuilt a few days ago), and GNU ld (GNU Binutils for Ubuntu) 2.30
foo.o:(.eh_frame+0x13): undefined reference to `__gxx_personality_v0'
Nor with an AArch64 GCC toolchain with GNU ld (fsf-10.39) 2.34.0.20200629

I agree with MaskRay that this is within the tolerances of incompatibilities between linkers, especially as linking with clang++ is the way to get the linker driver to put the right libraries on the command line directly. The only things that I can think of are:
* In your ld.bfd the garbage collection is somehow removing the section that references the personality routine. It is questionable whether relying on garbage collection for correctness of output is fair game. For example gold seems to give undefined symbol errors for the parts not removed by gc-sections.
* You may have a library selection difference based on LLD supporting back-references. For example in ld.bfd a later object in a library may be getting searched. The output of the linker option `--verbose` and `--print-map` could be useful.
