### ISSUE TITLE
Regression: clang-14 fails to compile chrony project

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#54715]
clang-14 fails to comple https://chrony.tuxfamily.org/.  This is a regression from clang13, and is caused by this commit: 0f0e31cf511def3e92244e615b2646c1fd0df0cd.

To reproduce run: `clang-build/./bin/clang -x c  -flto  -c client.ii.txt -o client.o && ./clang-build/bin/opt -verify client.o -o /dev/null`
With clang-14, this will crash and print the following error:

Global is external, but doesn't have external or weak linkage!
i64 (i8*, i64, i64, %struct._IO_FILE*)* @fread.inline
./clang-build/bin/opt: client.o: error: input module is broken!

[client.ii.txt](https://github.com/llvm/llvm-project/files/8402273/client.ii.txt)

**Comment by serge-sans-paille** [comment]
The first call is enough to break on an asset, thanks for the reproducer!

**Comment by serge-sans-paille** [comment]
Should be fixed by https://reviews.llvm.org/D123308

**Comment by tstellar** [comment]
@nickdesaulniers Is this safe to backport? https://github.com/llvm/llvm-project/commit/301e0d91354b853addb63a35e72e552e8059413e

**Comment by nickdesaulniers** [comment]
@tstellar I think so; no regressions reported kernel side with llvm-15 related to this.

**Comment by thesamesam** [comment]
Should this be reopened to ensure we don't miss backporting it to 14.0.2?

**Comment by tstellar** [comment]
Merged: 0fbe860711be2af4dc8454feb64506595e928e7f
