### ISSUE TITLE
Support per-directory index files for HTML coverage report

### ISSUE THREAD

**Issue by petrhosek** [llvm/llvm-project#54711]
`llvm-cov` currently generates a single top-level index HTML file. This is fine for smaller projects, for larger codebases this can lead to scalability issues. For example, in case of Fuchsia the [generated index](https://storage.googleapis.com/fuchsia-artifacts/builds/8818061488465309873/coverage/coverage/coverage/coverage/coverage/index.html) has 12M and rendering this file is causing problems for browsers. To address this issues, we would like to support generating per-directory index files which is also an approach [used by lcov](https://llvm.org/reports/coverage/). What's not yet clear is whether this mode should be an opt-in controlled by an option or whether this mode should replace the current model.

**Comment by petrhosek** [comment]
@vedantk do you know if this approach has already been considered in the past?

**Comment by yhgu2000** [comment]
@petrhosek Hi, this issue has been proposed to GSOC: https://discourse.llvm.org/t/coverage-support-a-hierarchical-directory-structure-in-generated-coverage-html-reports by @gulfemsavrun, and I have finished a draft proposal for this: https://yhgu2000.github.io/llvm-cov-example/gsoc.pdf. Will this be OK?

**Comment by chapuni** [comment]
@petrhosek Can we close this?
https://reviews.llvm.org/D151283
