### ISSUE TITLE
`clang-format` does not correctly order qualifiers in template parameter names

### ISSUE THREAD

**Issue by creator1creeper1** [llvm/llvm-project#54721]
If we run `clang-format` on the following file ("`broken_east_const.cpp`"):
```c++
struct A { };

template <typename T>
struct B {
};

struct C {
    B<const A> f() { return {}; }
};
```
like this:
```cmd
clang-format -i -style="{BasedOnStyle: WebKit, QualifierAlignment: Right}" broken_east_const.cpp
```
the file is not changed. However, since qualifiers should be right-aligned, the line
```c++
B<const A> f() { return {}; }
```
should be changed to
```c++
B<A const> f() { return {}; }
```

This came up in the [serenity](https://github.com/SerenityOS/serenity) project, specifically here: [Format.h#L242](https://github.com/SerenityOS/serenity/blob/master/AK/Format.h#L242). The whole project was recently re-formatted in commit [086969277e74d8ba065bf8145d3aeb0dec0bfee5](https://github.com/SerenityOS/serenity/commit/086969277e74d8ba065bf8145d3aeb0dec0bfee5) using the new [`.clang-format` file](https://github.com/SerenityOS/serenity/blob/master/.clang-format) which now specifies the `QualifierAlignment: Right` option.

**Comment by mydeveloperday** [comment]
I think this might be a duplicate of I think this is a duplicate of https://github.com/llvm/llvm-project/issues/53981

**Comment by creator1creeper1** [comment]
This indeed does look like a duplicate.

**Comment by creator1creeper1** [comment]
This indeed does look like a duplicate.
