### ISSUE TITLE
[clang-format] The variable name in the lambda joins to the class name breaking the code after formating

### ISSUE THREAD

**Issue by arsdever** [llvm/llvm-project#54720]
All the files I have collected in [this gist](https://gist.github.com/arsdever/b811514a8e159161d39c83ead286c304). To reproduce, download both files into the same folder and run the `clang-format`.

IMO, the issue is that [on this](https://gist.github.com/arsdever/b811514a8e159161d39c83ead286c304#file-sample-cpp-L10) line the class name goes all the way to the spacebar on the upper line, so after formatting the variable name on that line goes back to match the indentation to the `thread` variables name indentation.

clang-format: version 13.0.1
OS: windows

**Comment by mkurdej** [comment]
This was fixed in 6c7e6fc7.

`clang-format-main-20220209-a7b5e5b4.exe --style=file test.cpp`:
```
std::thread thd { []() {
    classnamapp();
    return result;
} };

std::thread thd { []() {
    classnameverylongapp();
    return result;
} };
```

`clang-format-main-20220210-6c7e6fc7.exe --style=file test.cpp`:
```
std::thread thd { []() {
    classnam app();
    return result;
} };

std::thread thd { []() {
    classnameverylong app();
    return result;
} };
```
