### ISSUE TITLE
[clang-tidy][run-clang-tidy.py] Uninformative error message after changes to binary discovery

### ISSUE THREAD

**Issue by neqochan** [llvm/llvm-project#54728]
Commit 5da83eeb91bab848a096db7521c6d8be29231665 broke our clang-tidy invocation ([here](https://github.com/qogecoin/rules_ll/blob/a9dabb7d2c0d7dba93a100cbce3ee4717c5a1d85/ll/compilation_database.bzl#L87)).
**Edit:** It actually was 9e1f4f13984186984ba37513372c1b7e0c4ba4fd.

I suspect that after the changes the automatic binary discovery somehow does not work with the `-clang-tidy-binary` option.
**Edit:** The issue is a bug in the python code related to wrong `argparse` usage that should break for every user.

My issue is that the error message `Unable to run clang-tidy.` (from [here](https://github.com/llvm/llvm-project/blob/3b1314f4de63db771f1d93e1da06f14e7f3babab/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py#L317)) is not very helpful for debugging (missing binary? threading issue? something else?) 😅. May be a bug as well. Currently looking into it and will post an update as soon as we find a fix on our side.

Tagging @keith as you are the one who wrote this commit.

**Comment by SAtacker** [comment]
Sorry, that's not my commit.

**Comment by SAtacker** [comment]
It's author is @keith as per the differential.

**Comment by neqochan** [comment]
Sorry, my bad. Mixed the commits up.

**Comment by keith** [comment]
Thanks for the ping, is there no other output from clang-tidy in your invocation? Given this code path succeeds I imagine your binary is being taken into account correctly https://github.com/llvm/llvm-project/blob/896770c9a92e88e6adbf109424d9e66ab58905c9/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py#L159-L165

Do you have an example of the path to the binary that is expanded in that command line? Potentially importantly is it something bare like `clang-tidy` or is it a path like `path/to/clang-tidy`?

**Comment by keith** [comment]
Can you easily test this patch to see if it fixes it?

```diff
diff --git a/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py b/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py
index ec1fd6679e2a..6018e8efa4fe 100755
--- a/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py
+++ b/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py
@@ -157,8 +157,9 @@ def merge_replacement_files(tmpdir, mergefile):
 def find_binary(arg, name, build_path):
   """Get the path for a binary or exit"""
   if arg:
-    if shutil.which(arg):
-      return arg
+    expanded_path = shutil.which(arg)
+    if expanded_path:
+      return expanded_path
     else:
       raise SystemExit(
         "error: passed binary '{}' was not found or is not executable"
```

**Comment by neqochan** [comment]
@keith I will try your patch, but I also found the issue with the following patch. Turned out this was caused by a misnamed `args.config_path` that should have been named `args.config_file` (since the argument is called `-config-file`), introduced by commit 9e1f4f13984186984ba37513372c1b7e0c4ba4fd (by @SAtacker :rofl:):

```diff
diff --git a/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py b/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py
index ec1fd6679..c59d3d529 100755
--- a/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py
+++ b/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py
@@ -194,7 +194,7 @@ def run_tidy(args, clang_tidy_binary, tmpdir, build_path, queue, lock,
                                      tmpdir, build_path, args.header_filter,
                                      args.allow_enabling_alpha_checkers,
                                      args.extra_arg, args.extra_arg_before,
-                                     args.quiet, args.config_path, args.config,
+                                     args.quiet, args.config_file, args.config,
                                      args.line_filter, args.use_color)
 
     proc = subprocess.Popen(invocation, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
@@ -304,7 +304,7 @@ def main():
                                      None, build_path, args.header_filter,
                                      args.allow_enabling_alpha_checkers,
                                      args.extra_arg, args.extra_arg_before,
-                                     args.quiet, args.config_path, args.config,
+                                     args.quiet, args.config_file, args.config,
                                      args.line_filter, args.use_color)
     invocation.append('-list-checks')
     invocation.append('-')
@@ -314,7 +314,10 @@ def main():
         subprocess.check_call(invocation, stdout=dev_null)
     else:
       subprocess.check_call(invocation)
-  except:
+  except Exception as err:
+    import traceback
+    print(err, file=sys.stderr)
+    print(traceback.format_exc())
     print("Unable to run clang-tidy.", file=sys.stderr)
     sys.exit(1)
 
```

(ignore the except part, that was just to get the stacktrace)

**Comment by SAtacker** [comment]
`config_path` made sense as it's literally that. `config_file` is vague.

**Comment by neqochan** [comment]
The argument to the `.py` file is `-config-file`. I agree that this should be named `config_path`.

So either the input argument to the `.py` file should be named `-config-path`, but that is confusing with `-config` option :rofl: .

Maybe renaming `-config-file` to `-config-file-path` would be an option? Anyways these two arguments `-config` and `-config-file` are slightly confusing.

**Comment by neqochan** [comment]
To clarify.
Calling the script with `-config-file` requires use of `args.config_file` on the python side.
`-config-path` would require use of `args.config_path` on the python side.
`-config` translates to `args.config` on the python side.

**Comment by neqochan** [comment]
For now I think this should be fine. The actual argument should stay `-config-file` to stay in line with the naming scheme for `clang-tidy`'s `--config-file`. I renamed it on the python side though to avoid confusion with python `file` objects. Ill submit this later today.

```diff
diff --git a/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py b/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py
index ec1fd6679..afe2bfd28 100755
--- a/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py
+++ b/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py
@@ -90,7 +90,7 @@ def make_absolute(f, directory):
 
 def get_tidy_invocation(f, clang_tidy_binary, checks, tmpdir, build_path,
                         header_filter, allow_enabling_alpha_checkers,
-                        extra_arg, extra_arg_before, quiet, config_path,
+                        extra_arg, extra_arg_before, quiet, config_file_path,
                         config, line_filter, use_color):
   """Gets a command line for clang-tidy."""
   start = [clang_tidy_binary]
@@ -121,8 +121,8 @@ def get_tidy_invocation(f, clang_tidy_binary, checks, tmpdir, build_path,
   start.append('-p=' + build_path)
   if quiet:
       start.append('-quiet')
-  if config_path:
-      start.append('--config-file=' + config_path)
+  if config_file_path:
+      start.append('--config-file=' + config_file_path)
   elif config:
       start.append('-config=' + config)
   start.append(f)
@@ -194,7 +194,7 @@ def run_tidy(args, clang_tidy_binary, tmpdir, build_path, queue, lock,
                                      tmpdir, build_path, args.header_filter,
                                      args.allow_enabling_alpha_checkers,
                                      args.extra_arg, args.extra_arg_before,
-                                     args.quiet, args.config_path, args.config,
+                                     args.quiet, args.config_file, args.config,
                                      args.line_filter, args.use_color)
 
     proc = subprocess.Popen(invocation, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
@@ -304,7 +304,7 @@ def main():
                                      None, build_path, args.header_filter,
                                      args.allow_enabling_alpha_checkers,
                                      args.extra_arg, args.extra_arg_before,
-                                     args.quiet, args.config_path, args.config,
+                                     args.quiet, args.config_file, args.config,
                                      args.line_filter, args.use_color)
     invocation.append('-list-checks')
     invocation.append('-')
```

**Comment by aaronmondal** [comment]
Patch submitted to [Phabricator](https://reviews.llvm.org/D123074).
