### ISSUE TITLE
Cannot compile Clang14 source code

### ISSUE THREAD

**Issue by 2283572185** [llvm/llvm-project#54741]
## Description
    The version of source code I tried to compile is LLVM 14.0.0-rc4 Release.
    I also tried LLVM 14.0.0 Release and the main branch.All of them have bugs like "no member named 'getNonOpaquePointerElementType' in 'llvm::Type'".
    Maybe LLVM has changed its api and clang fallen behind?
    I collected some reports of the compiler and show them below.

## Some Errors
``` console
llvm/clang/lib/CodeGen/CGCall.h:115:36: error: no member named 'getNonOpaquePointerElementType' in 'llvm::Type'; did you mean 'getPointerElementType'?

llvm/clang/lib/CodeGen/CGBuiltin.cpp:5877:24: error: no member named 'arm_neon_vqrdmlah' in namespace 'llvm::Intrinsic'; did you mean 'arm_neon_vqrdmulh'?

llvm/clang/lib/CodeGen/CGBuiltin.cpp:9789:37: error: no member named 'aarch64_mops_memset_tag' in namespace 'llvm::Intrinsic'

llvm/clang/lib/CodeGen/CGBuiltin.cpp:18814:23: error: no member named 'riscv_bfp' in namespace 'llvm::Intrinsic'
      ID = Intrinsic::riscv_bfp;

llvm/clang/lib/CodeGen/CGOpenMPRuntime.cpp:8124:21: error: cannot initialize a parameter of type 'llvm::Value *' with an lvalue of type 'llvm::IntegerType *'

llvm/clang/lib/CodeGen/CGOpenMPRuntime.cpp:12288:21: error: use of undeclared identifier 'OMPRTL___kmpc_aligned_alloc'
```
And so on.

**Comment by davidbolvansky** [comment]
Your build steps/commands? Something went wrong on your side, as release and trunk is buildable.

**Comment by 2283572185** [comment]
> It looks like you're mixing LLVM and Clang sources from different versions or something like that.

Well，I just downloaded the " SourceCode.zip" in the release package.I think the versions of them are equal.

**Comment by 2283572185** [comment]
> It looks like you're mixing LLVM and Clang sources from different versions or something like that.

Well，I just downloaded the " SourceCode.zip" in the release package.I think the versions of them are equal.

**Comment by 2283572185** [comment]
> Your build steps/commands? Something went wrong on your side, as release and trunk is buildable.
I compile LLVM and Clang locally on Windows with clang tool chain.
When building LLVM:
``` console
cmake 
-DCMAKE_CXX_COMPILER=D:/Tools/clang/bin/clang++.exe 
-DCMAKE_CXX_COMPILER=D:/Tools/clang/bin/clang.exe 
-DCMAKE_LINKER=D:/Tools/clang/bin/lld-link.exe 
-DLLVM_ABI_BREAKING_CHECKS=FORCE_OFF 
-DLLVM_HOST_TRIPLE=x86_64-pc-windows-msvc //I don't know why cmake scrpits cannot infer the host when I use clang.Using msvc or gcc is okay.
-DLLVM_TARGETS_TO_BUILD=X86 
-DLLVM_ENABLE_EH=TRUE 
-DLLVM_ENABLE_RTTI=TRUE 
-DLLVM_INSTALL_UTILS=TRUE 
-DLLVM_INSTALL_BINUTILS_SYMLINKS=TRUE 
-DLLVM_ENABLE_LLD=TRUE 
-DCMAKE_BUILD_TYPE=Release 
-DLLVM_ENABLE_WARNINGS=FALSE 
-DCMAKE_CXX_FLAGS="-D_ITERATOR_DEBUG_LEVEL=0 -UDEBUG -U_DEBUG" 
-DCMAKE_C_FLAGS="-D_ITERATOR_DEBUG_LEVEL=0 -UDEBUG -U_DEBUG" 
-DCMAKE_CXX_STANDARD_LIBRARIES="-lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames -lmsvcprt" 
-DCMAKE_C_STANDARD_LIBRARIES="-lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames -lmsvcprt"
```
I built LLVM14 successfully.But as you see,I had to modify some flags.Especially I must define "_ITERATOR_DEBUG_LEVEL" as 0 or it will fail to link the targets just becasue _ITERATOR_DEBUG_LEVEL is 2 some objects.And I must modify build.ninja because clang cannot recognize .def files directly.Adding "-Xlinker /Def:" before the full path of .def files can solve the problems.But I hope we will no longer need to fix these points on our own.
When building Clang:
```console
cmake 
-DCMAKE_CXX_COMPILER=D:/Tools/clang/bin/clang++.exe 
-DCMAKE_CXX_COMPILER=D:/Tools/clang/bin/clang.exe 
-DCMAKE_LINKER=D:/Tools/clang/bin/lld-link.exe 
-DCMAKE_BUILD_TYPE=Release 
-DCMAKE_CXX_FLAGS="-w -D_ITERATOR_DEBUG_LEVEL=0 -UDEBUG -U_DEBUG" 
-DCMAKE_C_FLAGS="-w -D_ITERATOR_DEBUG_LEVEL=0 -UDEBUG -U_DEBUG" 
-DCLANG_DEFAULT_CXX_STDLIB=libc++ 
-DCLANG_DEFAULT_LINKER=lld 
-DCLANG_DEFAULT_RTLIB=compiler-rt 
-DCLANG_ENABLE_CLANGD=TRUE 
-DLLVM_TOOL_CLANG_TOOLS_EXTRA_BUILD=TRUE //No matter whether I set it as true or not,I failed.
-DLLVM_EXTERNAL_CLANG_TOOLS_EXTRA_SOURCE_DIR=D:/llvm/clang-tools-extra
```
And then clang reported those errors.
