### ISSUE TITLE
[ASAN] Paths in stacktrace are wrong

### ISSUE THREAD

**Issue by jimis** [llvm/llvm-project#54742]
Here is one line from one stacktrace printed from an executable, compiled with `-fsanitize=address`.

```
    #2 0xa7164f in std::_Sp_counted_ptr<QQmlJS::Dom::ModuleIndex*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() \
        /bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/shared_ptr_base.h:377:9
```

The path can be canonicalized to: `/include/c++/9/bits/shared_ptr_base.h`
Which does not exist, it is missing the `/usr` prefix.

Clang version 13.0.1.

**Comment by pogo59** [comment]
Tagging with debuginfo because setting up paths is almost always a debuginfo thing.

**Comment by dwblaikie** [comment]
Standalone repro steps would be helpful (perhaps see if it reproduces with preprocessed source? A small preprocessed source example would be helpful to understand what's going on)

**Comment by jimis** [comment]
Yes you are right, I can find these silly paths by examining the executable with `strings`. For example
```
/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9
```
and many more. I will recompile in verbose and see if something is wrong in the compiler command line.

**Comment by jimis** [comment]
I found these `/bin/...` paths in the object files and in the end in the pre-processed source too. And even though "compressing" these paths leads to inexistent files, the paths actually exist and resolve correctly, because `/lib` is a symlink towards `/usr/lib`.

Sorry for the noise, it seems this is actually a bug in CodeChecker and not in LLVM, it is compressing the paths without trying to resolve them first. I'll file a ticket in the CodeChecker project, thank you for helping!
