### ISSUE TITLE
git-clang-format: return result from main() with sys.exit()

### ISSUE THREAD

**Issue by jarmar** [llvm/llvm-project#54758]
In edbb8a84, a return value was added to git-clang-format's `main()` function, indicating whether any action was taken. However, this value does not automatically become the script's exit code. Currently, the script's exit code is always 0.

An example:

```bash
# repo is correctly formatted
$ git-clang-format --diff
no modified files to format
$ echo $?
0

# ...mess up the formatting somewhere in your repo...
$ git-clang-format --diff
[...diff output...]
$ echo $?
0
```

The last command should output "1".

One way to fix this is by changing the final lines of the script to:

```python
if __name__ == '__main__':
  sys.exit(main())
```

See #53220.

**Comment by sethrj** [comment]
This is a good feature, but it unfortunately broke [our project's post-commit script](https://github.com/celeritas-project/celeritas/blob/master/scripts/dev/post-commit.git-clang-format) which expects the script to fail only when there's an error, not when the formatting changes...
