### ISSUE TITLE
"error: fixup value out of range" for aarch64-windows, for symbol references with a large offset

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#54753]
CC @efriedma-quic 

In https://github.com/llvm/llvm-project/issues/51720 we fixed issues where relocations against temporary symbols could end up with a too large offset. This is an issue as the ADRP relocations can store a 21 bit immediate (+/- 1 MB) offset against the symbol it points at. For those cases, we inserted extra temp symbols for large sections, to allow relocations against a temporary symbol to use these extra symbols instead of using the start of the section and a large offset.

The same issue can crop up elsewhere too, in code with references to symbols with large offsets.
```c
#define MAX_MEM_HANDLES  0x10000
struct mem_entry {
  void *ptr1, *ptr2; 
};

//extern struct mem_entry mem_entries[];
static struct mem_entry mem_entries[MAX_MEM_HANDLES];

void *getPtr(void) {
  return mem_entries + MAX_MEM_HANDLES;
}
```

```
$ bin/clang -target aarch64-windows -c aarch64-symbol-offset.c -O2 
error: fixup value out of range
1 error generated.
```

```
$ bin/clang -target aarch64-windows -S -o - aarch64-symbol-offset.c -O2
[...]
getPtr:                                 // @getPtr
        adrp    x0, mem_entries+1048576
        add     x0, x0, :lo12:mem_entries+1048576
        ret
```

(In this reduced case, it only triggers when built with `-O2`, but in the original case, it also triggered without `-O2`.)

For references to symbols in the current object file, we could potentially try to rewrite references to use the extra symbols that we've emitted with 1 MB intervals, but that's not correct if the symbol isn't static (and such rewrites aren't necessarily correct e.g. if the symbol can be weak and overridden by another symbol at link time), and clearly doesn't work if the symbol isn't defined in the current object file.

Curiously, if uncommenting the other declaration of `mem_entries`, `extern struct mem_entry mem_entries[];`, it does generate this code instead:
```
getPtr:                                 // @getPtr
        adrp    x8, mem_entries
        add     x8, x8, :lo12:mem_entries
        add     x0, x8, #256, lsl #12           // =1048576
        ret     
```

Therefore, it seems like the best solution would be to avoid forming address expressions in the form `symbol+offset`, if the offset is too large, and just add the offset as a separate operation instead. Where in the code is that decision taken, for how to form an address expression, deciding between an imediate symbol offset or a separate addition?

**Comment by efriedma-quic** [comment]
See performGlobalAddressCombine in AArch64ISelLowering.cpp.  (And the equivalent matchFoldGlobalOffset in AArch64PreLegalizerCombiner.cpp.)

**Comment by mstorsjo** [comment]
> See performGlobalAddressCombine in AArch64ISelLowering.cpp. (And the equivalent matchFoldGlobalOffset in AArch64PreLegalizerCombiner.cpp.)

Perfect, thanks! I posted an initial patch at https://reviews.llvm.org/D123160, which does seem to fix the issue for me.

**Comment by mstorsjo** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/8d7a17b7c8b7151b8453903db96fc7f45d9b1bae.
