### ISSUE TITLE
[AMDGPU][MC] Image instructions with 16-bit gradients should be supported on GFX10 only

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#54762]
image_sample_*_g16 instructions are not supported on GFX6-GFX9.
However they are accepted by assembler.

An example of failed test:

    image_sample_c_cd_cl_g16 v[5:6], v[1:5], s[8:15], s[12:15] dmask:0x3

Expected result:

    error: instruction not supported on this GPU

Actual result (GFX9):

    image_sample_c_cd_cl_g16 v[5:6], v[1:5], s[8:15], s[12:15] dmask:0x3 ; encoding: [0x01,0x03,0xac,0xf1,0x01,0x05,0x62,0x00]

**Comment by gandhi56** [comment]
`image_sample_c_cd_cl_g16_e64 v1, v2, s1, s2` generates the following error message with the compiler in trunk:

`error: e64 variant of this instruction is not supported`

**Comment by dpreobra** [comment]
> `image_sample_c_cd_cl_g16_e64 v1, v2, s1, s2` generates the following error message with the compiler in trunk for gfx9:
> 
> `error: e64 variant of this instruction is not supported`

This is by design.

If an instruction A is supported, but A_e64 is not, you will get this error message. This is also true for other variants - _dpp and _sdwa.

If an instruction A is not supported on this GPU, but it is supported on some other GPU, instructions A, A_e64, A_dpp, etc should result in an error message "instruction not supported on this GPU".

If an instruction A is not supported on any GPU, you should get an "invalid instruction" message.

**Comment by gandhi56** [comment]
https://reviews.llvm.org/D123461

**Comment by gandhi56** [comment]
Thank you, I missed out on adding these instructions.
