### ISSUE TITLE
gcc style inline assembly question

### ISSUE THREAD

**Issue by 0x7cc** [llvm/llvm-project#54788]
my test cpp code:

```cpp
#include <stdint.h>
#include <stddef.h>

constexpr uintptr_t value = 0x11111111;

uintptr_t f(){
    uintptr_t result;
    __asm__  ("call *%[p]" : "=r"(result) : [p]"r"(value));
    return result;
}
```

im using clang 14 on the https://godbolt.org/, compiler options:

```shell
-O3 -target x86_64-pc-windows-msvc
```

generated code;
```
        mov     eax, 286331153
        call    rax
        ret
```

I think the correct one should be:
```
        mov     rax, 286331153
        call    rax
        ret
```

**Comment by nico** [comment]
286331153 fits in 32 bit, so `mov eax, 286331153` has the same effect and needs fewer bytes to encode. Why do you think it shouldn't be emitted?

**Comment by Leporacanthicus** [comment]
Unless the value 286331153 is a relative address, and the code gets relocated to live above 4GB (or 2GB?), I guess?

I know nothing of the original question, but that's a reason why you'd want a 64-bit load.

--
Mats
________________________________

**Comment by 0x7cc** [comment]
> 286331153 fits in 32 bit, so `mov eax, 286331153` has the same effect and needs fewer bytes to encode. Why do you think it shouldn't be emitted?

The code will crash if rax register high 32 bits is not zero

**Comment by Leporacanthicus** [comment]
The specification for x86-64 is that upper 32 bits are set to zero on all 32-bit operations. See section 3.1.2.3 in the AMD specification here:
https://www.amd.com/system/files/TechDocs/24592.pdf
AMD64 Architecture Programmer’s Manual, Volume 1: Application Programming - Welcome to AMD<https://www.amd.com/system/files/TechDocs/24592.pdf>
Advanced Micro Devices Publication No. Revision Date 24592 3.23 October 2020 AMD64 Technology AMD64 Architecture Programmer’s Manual Volume 1: Application Programming
www.amd.com

3.4.1.1 in this says similarly:
https://cdrdv2.intel.com/v1/dl/getContent/671200

--
Mats


________________________________

**Comment by 0x7cc** [comment]
> In general, byte and word operands are stored in the low 8 or 16 bits of GPRs without modifying their
high 56 or 48 bits, respectively. Doubleword operands, however, are normally stored in the low 32 bits
of GPRs and zero-extended to 64 bits. 

sorry!
I don't know the spec. I will close this issue
