### ISSUE TITLE
Backport "[AArch64] Fix the upper limit for folded address offsets for COFF" to 14.x

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#54789]
I'd suggest backporting 8d7a17b7c8b7151b8453903db96fc7f45d9b1bae, "[AArch64] Fix the upper limit for folded address offsets for COFF", to the 14.x release branch.

CC @efriedma-quic to ack that this patch is safe and makes sense to backport.

**Comment by efriedma-quic** [comment]
Yes, this is safe to backport.

**Comment by tstellar** [comment]
Merged: c62053979489
