### ISSUE TITLE
Please backport d09d297c5d28 to LLVM 14.0.1 branch

### ISSUE THREAD

**Issue by luismarques** [llvm/llvm-project#54792]
The d09d297c5d28bd0af4dd8bf3ca66d8dbbd196d9d commit fixes a crash introduced in LLVM 14 that wasn't caught in time.
If there's still time to accept patches for the LLVM 14.0.1 branch please backport this fix.

**Comment by asb** [comment]
This makes sense to backport to me - thanks Luís.

**Comment by tstellar** [comment]
Merged: 0e27d08cdeb3
