### ISSUE TITLE
LLD requires `libatomic` in when compiling for `i686`

### ISSUE THREAD

**Issue by Kobzol** [llvm/llvm-project#54790]
Hi!

We're trying to [migrate](https://github.com/rust-lang/rust/pull/95171) the Rust compiler to use LLVM 14 on CI. I have found a build issue that happens when we try to build `lld 14.0.0` with `clang 14.0.0` when cross-compiling to `i686` from a `x64` host system. Even though the CMake check claims that `LIBATOMIC` is not required:
```
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB - Success
-- Performing Test LLVM_HAS_ATOMICS
-- Performing Test LLVM_HAS_ATOMICS - Success
```
linking `lld` later fails with this error:
```
[100%] Linking CXX executable ../../bin/lld
../../lib/liblldCOFF.a(DebugTypes.cpp.o): In function `void llvm::function_ref<void (unsigned int)>::callback_fn<lld::coff::TypeMerger::mergeTypesWithGHash()::$_5>(int, unsigned int)':
DebugTypes.cpp:(.text._ZN4llvm12function_refIFvjEE11callback_fnIZN3lld4coff10TypeMerger19mergeTypesWithGHashEvE3$_5EEvij+0x15b): undefined reference to `__atomic_load'
DebugTypes.cpp:(.text._ZN4llvm12function_refIFvjEE11callback_fnIZN3lld4coff10TypeMerger19mergeTypesWithGHashEvE3$_5EEvij+0x1d1): undefined reference to `__atomic_compare_exchange'
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/lld] Error 1
make[1]: *** [tools/lld/CMakeFiles/lld.dir/all] Error 2
make: *** [all] Error 2
```
The CMake invocation looks like this:
```
cmake
/checkout/src/llvm-project/lld
-DCMAKE_INSTALL_MESSAGE=LAZY
-DCMAKE_C_COMPILER_LAUNCHER=sccache
-DCMAKE_CXX_COMPILER_LAUNCHER=sccache
-DCMAKE_C_COMPILER=clang
-DCMAKE_CXX_COMPILER=clang++
-DCMAKE_ASM_COMPILER=clang
-DCMAKE_C_FLAGS=-ffunction-sections -fdata-sections -fPIC --target=i686-unknown-linux-gnu -mstackrealign -fdebug-prefix-map=/checkout=/rustc/llvm
-DCMAKE_CXX_FLAGS=-ffunction-sections -fdata-sections -fPIC --target=i686-unknown-linux-gnu -fdebug-prefix-map=/checkout=/rustc/llvm
-DCMAKE_SHARED_LINKER_FLAGS= -Wl,-Bsymbolic -static-libstdc++
-DCMAKE_MODULE_LINKER_FLAGS= -Wl,-Bsymbolic -static-libstdc++
-DCMAKE_EXE_LINKER_FLAGS= -Wl,-Bsymbolic -static-libstdc++
-DLLVM_CONFIG_PATH=/checkout/obj/build/bootstrap/debug/llvm-config-wrapper
-DLLVM_INCLUDE_TESTS=OFF
-DCMAKE_CXX_STANDARD=14
-DCMAKE_INSTALL_PREFIX=/checkout/obj/build/i686-unknown-linux-gnu/lld
-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC --target=i686-unknown-linux-gnu -mstackrealign
-DCMAKE_BUILD_TYPE=Release
```

The full error log can be seen [here](https://github.com/rust-lang-ci/rust/commit/0d989c1dad843f2f127f1f5670d949c43f178dc2/checks/5799020258/logs), the link error is near the bottom. The build has succeeded for numerous other platforms (https://github.com/rust-lang-ci/rust/runs/5799020258?check_suite_focus=true), but it fails for `i686` specifically.

I have tried to install `libatomic` on the build system and link to it, in that case, `lld` is successfully compiled. However, we would like to avoid linking to `libatomic`, and the CMake check seems to be wrong here.
Do you have any suggestions on how this could be fixed? Thanks!

**Comment by efriedma-quic** [comment]
Try the following testcase.

```
#include <atomic>
struct X{uint64_t x;};
std::atomic<uint64_t> x;
std::atomic<X> x2;
void f() { x = {10}; }
void f2() { x2 = {10}; }
```

Does that produce any `__atomic_` calls?  Does it produce any warnings with " -Wsystem-headers"?

**Comment by Kobzol** [comment]
I took this code and put it into `test.cpp`. Then I compiled it with `clang++ 14.0.0` on `x64` Linux:
```bash
$ clang++ --target=i686-unknown-linux-gnu test.cpp
test.cpp:5:16: warning: braces around scalar initializer [-Wbraced-scalar-init]
void f() { x = {10}; }
               ^~~~
1 warning generated.
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../../lib32/crt1.o: in function `_start':
(.text+0x2c): undefined reference to `main'
/usr/bin/ld: /tmp/test-917c45.o: in function `std::atomic<X>::store(X, std::memory_order)':
test.cpp:(.text._ZNSt6atomicI1XE5storeES0_St12memory_order[_ZNSt6atomicI1XE5storeES0_St12memory_order]+0x53): undefined reference to `__atomic_store'
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```
With `-Wsystem-headers` it gives one additional warning:
```
In file included from test.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/atomic:254:9: warning: misaligned atomic operation may incur significant performance penalty; the expected alignment (8 bytes) exceeds the actual alignment (4 bytes) [-Watomic-alignment]
      { __atomic_store(std::__addressof(_M_i), std::__addressof(__i), int(__m)); }
```

The first command is a minimal reproducible example of our issue.

**Comment by Kobzol** [comment]
It also has this error with `clang 13.0.1` btw. So it seems that the problem is not with the newer compiler (this has worked before for Rust with Clang 13 btw), but because something in `lld` now uses atomic functions that are not properly linked when compiled with `clang`.

**Comment by davidbolvansky** [comment]
> It also has this error with `clang 13.0.1` btw. So it seems that the problem is not with the newer compiler (this has worked before for Rust with Clang 13 btw), but because something in `lld` now uses atomic functions that are not properly linked when compiled with `clang`.

I observed this issue as well during transition of our tool to llvm/cland/lld 13.

**Comment by efriedma-quic** [comment]
Okay... so I think what's happening is the following:

1. lld contains `std::atomic<GHashCell>`, which is similar to `std::atomic<X>` from the testcase.
2. clang doesn't like the way libstdc++ implements std::atomic for structs: it think the atomic operation might be misaligned, and therefore generates a call to libatomic.
3. The HAVE_CXX_ATOMICS64_WITHOUT_LIB doesn't catch this because it only contains a test for `std::atomic<uint64_t>` (which uses a different codepath in the library/compiler).

Each of these could be treated as a bug, and fixed separately.

**Comment by efriedma-quic** [comment]
> clang doesn't like the way libstdc++ implements std::atomic for structs: it think the atomic operation might be misaligned, and therefore generates a call to libatomic.

Figured out what's happening here.  The `<atomic>` library in libstdc++ was changed at some point to use `std::__addressof` to compute the address of its member.  The code that computes the alignment of atomic operands treats that as a black box, so it loses the alignment information, and doesn't know the member is actually aligned.  Peeking into the implementation is sort of tricky given the way clang is architected... maybe we can "cheat" and just hardcode the semantics of `std::__addressof`.

**Comment by Kobzol** [comment]
Is there something we can do to help resolve this issue? I don't have a lot of experience with contributing to LLVM, but I can try, with some mentoring.

**Comment by efriedma-quic** [comment]
Opened https://github.com/llvm/llvm-project/issues/54962 to backport the lld fix to LLVM 14.  Opened https://github.com/llvm/llvm-project/issues/54963 for the underlying clang issue.

**Comment by Kobzol** [comment]
I can confirm that with the backported fix, LLD can be built in 32-bit mode. Thank you very much! Once LLVM 14.0.2 is released, I'll try it with `rustc`.
