### ISSUE TITLE
Backport "[RISCV] Fixing stack offset for RVV object with vararg in stack."

### ISSUE THREAD

**Issue by kito-cheng** [llvm/llvm-project#54809]
This bug is about the stack offset, RISC-V backend might generate wrong stack offset to corrupt the stack content if there is scalable vector object and callee-save vaarg objesct.

We hit this bug when compile spec2017 with auto-vectorization and cause wrong result, so I believe this should backport to LLVM 14 branch.

https://github.com/llvm/llvm-project/commit/690085c9b715af720ecbd1c009731ba5478cf493 Serialize some filed in RISCVMachineFunctionInfo into MIR YAML file make the test case reproduce-able.
https://github.com/llvm/llvm-project/commit/7a123890c946beb533c5f7ca460d676f494d5ab3 Add test
https://github.com/llvm/llvm-project/commit/9c5aedfbf53ee8ce75723dec88359403e813499f Fix 
https://github.com/llvm/llvm-project/commit/5286c7aef8b4486c991b13b65eac9dbf01cb51f6 Add missing lit.local.cfg

**Comment by asb** [comment]
This makes sense for backporting from my perspective, thanks Kito.

**Comment by tstellar** [comment]
/cherry-pick 690085c9b715af720ecbd1c009731ba5478cf493 7a123890c946beb533c5f7ca460d676f494d5ab3 9c5aedfbf53ee8ce75723dec88359403e813499f 5286c7aef8b4486c991b13b65eac9dbf01cb51f6

**Comment by kito-cheng** [comment]
@tstellar I've resolve the merge conflict and tested on my local[1], I am not sure what the next step? should I operate llvmbot or you will did that?

Thanks :)

[1] https://github.com/kito-cheng/llvm-project/tree/issue54809-backport

**Comment by tstellar** [comment]
Merged: 87599bdabbd16f109d317af1164de5a02ff0aca4 b6e91d4a331e6e3af178f16347ad308237f90340 d0f27fb449525528a5688b7678dd9a8082bb6c41 2c4d288eae8b21f0f62d4831113b131fdb15f1da
