### ISSUE TITLE
llvm-cov is unable to only generate coverage for source files in given directories

### ISSUE THREAD

**Issue by ZequanWu** [llvm/llvm-project#54806]
We want to generate coverage report using `llvm-show` only for given directories. llvm-cov has the flag `--ignore-filename-regex=` to ignore source files that matches the regex, but it doesn't support negative lookahead (e.g. we only want coverage report for source files recursively inside folder1 `(?!folder1)`). 
I think we should add a flag for this unless there is another way to solve it.

**Comment by mvoorsluys** [comment]
It used to be possible to specify the SOURCES as a directory in the command line, and it would only report coverage for that specific directory. But with version 14 that does not seem to work properly anymore. Might be related to #54769?

**Comment by ZequanWu** [comment]
It's actually supported. Just specifying directories as positional arguments, llvm-cov will only generate coverage for files under those directories.
