### ISSUE TITLE
Unknown type attributes are diagnosed twice with `[[]]` spelling

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#54817]
Consider:
```
void func(void) {
  int [[attr]] i;
  (void)sizeof(int [[attr]]);
}
```
This generates four diagnostics, two for each unknown attribute. See https://godbolt.org/z/r6eGx1W6E for an example. The same does not happen for declaration attributes or statement attributes, and it does not happen for unknown type attributes spelled with `__attribute__`.

**Comment by ps-19** [comment]
Sir can you please give little hint on how can one resolve this issue?

**Comment by AaronBallman** [comment]
The way I'd approach this is to look at all the places where `warn_unknown_attribute_ignored` shows up in diagnostic code. I'd see what code paths are taken that lead to diagnosing it twice, and then see if there's a way to ensure that doesn't happen (without breaking any existing tests).

**Comment by junaire** [comment]
A potential fix: https://reviews.llvm.org/D123447
