### ISSUE TITLE
Wrong Resource Usage for BSR and BSF Instructions in Znver1 Scheduling Model

### ISSUE THREAD

**Issue by fabian-r** [llvm/llvm-project#54811]
When given one of the following 1-instruction basic blocks, llvm-mca reports an Rthroughput of 0.3:
```
bsr %rbx, %rdx
```
and
```
bsf %rbx, %rdx
```

Measurements with nanoBench and uops.info, as well as AMD's Latency Table, say that they are slower:
- BSR has a throughput of 0.25, i.e. an Rthroughput of 4
- BSF has a throughput of 0.5, i.e. an Rthroughput of 2 (according to AMD's table; I did not observe anything lower than 3 with nanoBench experiments)

The problem seems to be that the corresponding [entries in the scheduling model](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/X86/X86ScheduleZnver1.td#L234) only use a single ZnALU resource although the instructions use 6 uops.

According to uops.info data, znver2 is affected as well.

**Comment by davidbolvansky** [comment]
cc @LebedevRI  @RKSimon
