### ISSUE TITLE
Backport `[MC][ELF] Improve st_size propagation rule` to 14.0.1

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#54818]
* 67acc34e2ad89f18a6d66d72ddc30e77c5aff7d9 [MC][test] Improve offset.s
* e07dfa5328b0ca1465ae7b749e1ac2d994741e27 [MC][ELF] Improve st_size propagation rule

This fixes `st_size` for some symbols in some cases (when alias or symbol versioning is used), which may be checked by ABI checking tool. It will also help building glibc with clang 14.0.1 https://sourceware.org/pipermail/libc-alpha/2022-April/137627.html

**Comment by tstellar** [comment]
/cherry-pick 67acc34e2ad89f18a6d66d72ddc30e77c5aff7d9 e07dfa5328b0ca1465ae7b749e1ac2d994741e27

**Comment by tstellar** [comment]
@smithp35 Is this safe to backport? https://github.com/llvm/llvm-project/commit/67acc34e2ad89f18a6d66d72ddc30e77c5aff7d9 https://github.com/llvm/llvm-project/commit/e07dfa5328b0ca1465ae7b749e1ac2d994741e27

**Comment by smithp35** [comment]
Yes this is safe, apologies for the delay in responding.

**Comment by tstellar** [comment]
Merged: 9ed930e5cd74 f3f90ec42ae6
