### ISSUE TITLE
LiveIntervals::getApproximateInstructionCount() some times return 0 (zero)!

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5482]
|  |  |
| --- | --- |
| Bugzilla Link | [5110](https://llvm.org/bz5110) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
LiveIntervals::getApproximateInstructionCount()  some times return 0 (zero) and causes division by zero.

Solution so far looks like this

unsigned getApproximateInstructionCount(LiveInterval& I) 
{
   double IntervalPercentage = getScaledIntervalSize(I) / 1000.0;
   unsigned result = (unsigned)(IntervalPercentage * FunctionSize);
   if(result<=0) result = 1;
   return result;
   //return (unsigned)(IntervalPercentage * FunctionSize);
}

**Comment by gwelymernans** [comment]
Jakob fixed the related bug in r95917. The structures of RA changed a lot over the years. That function no longer exists.

Closing this. If it's still an issue, please open another bug and provide a test case.
