### ISSUE TITLE
Missing Wno-reserved-identifier option

### ISSUE THREAD

**Issue by sommerluk** [llvm/llvm-project#54826]
Clang has a new option Wreserved-identifier.

**Actual behaviour:**
The corresponding Wno-reserved-identifier does not exist.

**Expected behaviour:**
There is a corresponding Wno-reserved-identifier just like for other compile options.

**Comment by baedert** [comment]
Works in https://godbolt.org/z/ecaW9oWr7 ?

**Comment by sommerluk** [comment]
Closing this one.

Apparently it works indeed correctly when using /usr/bin/clang. 

(I got the error because in the debug build of my build system, it goes through clazy instead of clang, and somewhere during the build process something seems to go wrong – though all other -Wno-… options work fine even with clazy.)
