### ISSUE TITLE
When formatting protobuf, clang-format inserts a space after "keyword" inside field options

### ISSUE THREAD

**Issue by hexchain** [llvm/llvm-project#54848]
Protobuf keywords may appear in a field option, e.g. https://github.com/envoyproxy/protoc-gen-validate/blob/main/README.md#repeated. When formatting a file with such field option, `clang-format` insists on inserting a space after the "keyword".

Example file:

```proto
syntax = "proto3";
package proto.test;

message A {
  int32 a = 1;
}

message B {
  repeated A a = 1 [(annotation).int32.repeated.required.optional.oneof.test = true];
}
```

Output of `clang-format --style=Google`:
```proto
syntax = "proto3";
package proto.test;

message A {
  int32 a = 1;
}

message B {
  repeated A a = 1
      [(annotation).int32.repeated .required .optional .oneof.test = true];
}
```

Expected output:

No space should be inserted after "keywords" in a field option.

**Comment by henryjhenry** [comment]
this problem still occur

**Comment by owenca** [comment]
> this problem still occur

Which version did you use? It seems to work with 18.1.8.

**Comment by henryjhenry** [comment]
> > this problem still occur
> 
> Which version did you use? It seems to work with 18.1.8.

clang-format: version `18.1.8`
os: `Apple M2 & OS 14.5 (23F79)`

Using clang-format on `.proto` file:

proto:
```proto
message Req {
    repeated string IDs = 1 [(validate.rules).repeated.min_items = 1];
}
```

command: 
```bash
 clang-format -style="{ IndentWidth: 4, BasedOnStyle: google, AlignConsecutiveAssignments: AcrossEmptyLines, AlignConsecutiveDeclarations: AcrossEmptyLines, ColumnLimit: 0, Language: Proto }"
```

got:
```proto
message Req {
    repeated string IDs = 1 [(validate.rules).repeated .min_items = 1];
}
```

There is a space between `repeated` and `.min_items`
