### ISSUE TITLE
clang-tidy modernize-macro-to-enum confused by `#define FOO (-1)`

### ISSUE THREAD

**Issue by seanm** [llvm/llvm-project#54843]
I tried `modernize-macro-to-enum` on the [vtk](https://gitlab.kitware.com/vtk/vtk) code base.

One suboptimal change was from this:

```
#define VTK_TETRAHEDRALIZE_5 0
#define VTK_TETRAHEDRALIZE_5_FLIP 1
#define VTK_TETRAHEDRALIZE_6 6
#define VTK_TETRAHEDRALIZE_12_CONFORM (-1)
#define VTK_TETRAHEDRALIZE_12_CONFORM_FLIP 2
#define VTK_TETRAHEDRALIZE_12 10
```

to this:

```
enum {
VTK_TETRAHEDRALIZE_5 = 0,
VTK_TETRAHEDRALIZE_5_FLIP = 1,
VTK_TETRAHEDRALIZE_6 = 6
};
#define VTK_TETRAHEDRALIZE_12_CONFORM (-1)
enum {
VTK_TETRAHEDRALIZE_12_CONFORM_FLIP = 2,
VTK_TETRAHEDRALIZE_12 = 10
};
```

It seems the parentheses confuse it?

Interestingly, those parentheses were probably added by [clang-tidy bugprone-macro-parentheses](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-macro-parentheses.html).

**Comment by seanm** [comment]
@LegalizeAdulthood this may interest you.

**Comment by LegalizeAdulthood** [comment]
bugprone parenthesis doesn't put parens around constants AFAIK, only macro argument tokens.

The [constraints on the check](https://clang.llvm.org/extra/clang-tidy/checks/modernize-macro-to-enum.html) state that at the moment only literal tokens with one of three unary operators are recognized.

Whether or not to support parenthesized comments came up in the review and we decided to postpone it to a subsequent commit.

I'll use this issue as the enhancement request

**Comment by LegalizeAdulthood** [comment]
https://reviews.llvm.org/D123479

**Comment by seanm** [comment]
Thanks for the speedy patch!


>bugprone parenthesis doesn't put parens around constants AFAIK

BTW I was pretty sure it did, so I reverted a similar #define in VTK and tried, and indeed:

```
VTK/Common/DataModel/vtkPolygon.cxx:97:29: warning: macro replacement list should be enclosed in parentheses [bugprone-macro-parentheses]
#define VTK_POLYGON_FAILURE -1
                            ^
                            ( )
```

**Comment by LegalizeAdulthood** [comment]
That's good to know and explains why a bunch of people have parens around their negative numbers (and possibly also `+1` and `~1U` style defines as well)
