### ISSUE TITLE
Backport 70046438d02ba1ec6bc2e2fc496b610cc1068b0f to LLVM 14

### ISSUE THREAD

**Issue by kito-cheng** [llvm/llvm-project#54847]
This patch fixed an assertion failure on a valid integer literal value (`-2158497792`) with specific architecture extension combination for RISC-V.

https://github.com/llvm/llvm-project/commit/70046438d02ba1ec6bc2e2fc496b610cc1068b0f

**Comment by asb** [comment]
Backporting this makes sense to me. Thanks Kito.

**Comment by tstellar** [comment]
Merged: 50c6ba751fa2
