### ISSUE TITLE
GVN hoists loads over intrinsics

### ISSUE THREAD

**Issue by jdoerfert** [llvm/llvm-project#54851]
Originally reported here: https://discourse.llvm.org/t/bug-gvn-memdep-bug-in-the-presence-of-intrinsics/59402

> GVN, or probably memdep analysis, seem to think intrinsics are somewhat special
> and consequently assume they cannot "effectively clobber" a memory location. It
> might also be globals-mod-ref or something else that provides AA information.
> 
> The following example ([https://godbolt.org/z/TG6dYvP6M 1](https://godbolt.org/z/TG6dYvP6M)) shows how an unknown function
> prevents an invalid load hoist while an unknown intrinsic does not. Again, the preload
> is not sound in a multi-thread environment.

The simple reproducer can be found here: https://godbolt.org/z/cKMEezbjY
Compiled with `-globals-aa -gvn` the below code will hoist the load above the barrier but not the unknown function.

```
@G = internal global i32 undef

define void @test_barrier(i1 %c) {
  br i1 %c, label %init, label %check
init:
  store i32 0, ptr @G
  br label %check
check:
  call void @llvm.amdgcn.s.barrier()
  %v = load i32, ptr @G
  %cmp = icmp eq i32 %v, 0
  call void @llvm.assume(i1 %cmp)
  ret void
}

define void @test_unknown(i1 %c) {
  br i1 %c, label %init, label %check
init:
  store i32 0, ptr @G
  br label %check
check:
  call void @unknown()
  %v = load i32, ptr @G
  %cmp = icmp eq i32 %v, 0
  call void @llvm.assume(i1 %cmp)
  ret void
}

declare void @unknown()
declare void @llvm.amdgcn.s.barrier()
declare void @llvm.assume(i1 noundef)
```

**Comment by jdoerfert** [comment]
@efriedma-quic @arsenm Any thoughts?

**Comment by efriedma-quic** [comment]
Is this distinct from https://reviews.llvm.org/D115302 ?

**Comment by jdoerfert** [comment]
> Is this distinct from https://reviews.llvm.org/D115302 ?

I think it is. Or at least the fix I'm preparing is. I think the reason for this problem is d4133ac31535ce5176f97e9fc81825af8a808760 which survived one way or another until today.

**Comment by jdoerfert** [comment]
Proposed fix: https://reviews.llvm.org/D123531
