### ISSUE TITLE
symlink libclang.so.14 -> libclang.so.13

### ISSUE THREAD

**Issue by brooksdavis** [llvm/llvm-project#54853]
The libclang.so version wasn't bumped in LLVM 14 due to a lack of ABI-breaking changes, but existing build systems sometimes assume a 1:1 correspondence between the LLVM major version and libclang's version. Adding a symlink would avoid needing to modify them.

**Comment by q66** [comment]
sounds like the existing build systems should be fixed then, doing this sounds absolutely wrong

**Comment by brooksdavis** [comment]
I opened this issue at the request of @tstellar (https://discourse.llvm.org/t/llvm-14-0-1-schedule-and-release-updates/61227/18?u=brooks). I'm proceeding with adding the link to the FreeBSD package as part of 14.0.1.

See also #54004

**Comment by kloczek** [comment]
Someone solved taht alredy? 🤔

**Comment by MaskRay** [comment]
I agree with q66 that this is downstream build system bug. I'd prefer llvm-project does not add more complexity. The downstream should be fixed.

**Comment by brooksdavis** [comment]
Later releases stopped doing this so it's OBE.
