### ISSUE TITLE
[LoopVectorizer] Assertion `hasVectorValue (Def, Instance.Part)' failed.

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#54867]
[testcase.tar.gz](https://github.com/llvm/llvm-project/files/8471505/testcase.tar.gz)
clang -march=z14 -Os crash0.i -o a.out -w

Reduced:
opt -O3 -S -mtriple=s390x-linux-gnu -mcpu=z15 tc_crash0_aftercreduce.ll

Transforms/Vectorize/VPlan.cpp:236: llvm::Value* llvm::VPTransformState::get(llvm::VPValue*, const llvm::VPIteration&): Assertion `hasVectorValue(Def, Instance.Part)' failed.

stack:
...
llvm::InnerLoopVectorizer::fixLCSSAPHIs
llvm::InnerLoopVectorizer::fixVectorizedLoop
llvm::LoopVectorizationPlanner::executePlan
...

**Comment by fhahn** [comment]
Reproduces on godbolt:https://llvm.godbolt.org/z/hEGh489Pr

**Comment by fhahn** [comment]
Same issue as  #51366, which has a linked patch.

**Comment by fhahn** [comment]
Should be fixed by 3bebec6592a4dd8a1fb330382fc8dd4162c6bf44.
