### ISSUE TITLE
workflow: When running cherry-pick twice in an issue - the workflow will fail on creating a new pull request since it's already there.

### ISSUE THREAD

**Issue by tru** [llvm/llvm-project#54862]
See: 

https://github.com/llvm/llvm-project/issues/54487#issuecomment-1096143452
https://github.com/llvm/llvm-project/actions/runs/2153082832

We need to check if the PR is already there - if it's there it shouldn't be created. At least that's my theory. 

I could look into it if you don't have time @tstellar - but I don't have a good way to test this - do you have any setup for testing?

**Comment by tstellar** [comment]
@tru If you wan to fix it, that would be great.

**Comment by tru** [comment]
https://reviews.llvm.org/D123657

**Comment by tru** [comment]
I am not sure if we want to add a comment saying "PR was updated" if we already have one?
