### ISSUE TITLE
BOLT与llvm后期如何融合,后期计划如何

### ISSUE THREAD

**Issue by Wenmj201582** [llvm/llvm-project#54864]
English:
We want to make a requirement in openeuler and understand that the bolt source code is now integrated into the llvm source code, which is a subdirectory under the llvm source code.
I'd like to ask whether bolt wants to build llvm IR from binary code and start the llvm back-end compilation function; Or how to integrate bolt and llvm in the later stage, and whether there are relevant plans?

中文：
我们想在openEuler做一个需求，了解到BOLT源代码现已合入LLVM源代码，是llvm源代码下的一个子目录。
想咨询一下BOLT是否要从二进制代码构建llvm IR，并启动llvm后端编译功能；或者说BOLT与llvm后期如何融合，是否有相关计划？

**Comment by fhahn** [comment]
For this kind of question, please use https://discourse.llvm.org. I am closing the issue, as it sounds like there isn't an actual issue, but please feel free to re-open the issue in case there's any issue or work to track.
