### ISSUE TITLE
[AMDGPU][MC][GFX10] v_mul_lo_i32 should be disabled

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#54877]
v_mul_lo_i32 is only supported on GFX7.

GFX8 SPG and public GCN3 ISA description state explicitly that it is no longer supported: "Removed Instructions: ... V_MUL_LO_I32 (it’s functionally identical to V_MUL_LO_U32)."

LLVM AMDGPU assembler supports v_mul_lo_i32 as an alias for v_mul_lo_u32 on GFX8 and GFX9. It is fine.

However v_mul_lo_i32 is defined as a real GFX10 instruction with an opcode different from v_mul_lo_u32. This looks like a bug because this instruction is not defined in any GFX10 documents. sp3 does not support v_mul_lo_i32 on GFX10 either.

**Comment by gandhi56** [comment]
`v_mul_lo_i32` is removed from gfx1030+ according to this review [https://reviews.llvm.org/D94020](D94020). Is it only supposed to work on gfx7?
