### ISSUE TITLE
Unknown CMake command `add_clang_executable`

### ISSUE THREAD

**Issue by rdwnsjjd** [llvm/llvm-project#54875]
I'm reading [this](https://clang.llvm.org/docs/RAVFrontendAction.html) and I'm trying to build it step-by-step.
my project is just it:
```
root
  |----- FindClassDecls.cpp
  |----- CMakeLists.txt
```
all files are exactly the same as original.
but when I run `cmake CMakeLists.txt` I give `Unknown CMake command add_clang_executable` error.
why? How to fix it?

(CMakeLists.txt content:
```cmake
set(LLVM_LINK_COMPONENTS
  Support
)

add_clang_executable(find-class-decls FindClassDecls.cpp)

target_link_libraries(find-class-decls
  PRIVATE
  clangAST
  clangBasic
  clangFrontend
  clangSerialization
  clangTooling
)
cmake_minimum_required(VERSION 3.18)
project("myProject")

**Comment by mozkeeler** [comment]
@rdwnsjjd I ran into the same issue. How did you resolve it?
