### ISSUE TITLE
`ParseResult` should be in LLVM/Support

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#54884]
OpDefinition.h defines the ParseResult class, which is a refinement for "parser like" situations where you want to chain together logical result things with ||.  This is used by the custom asm parser in MLIR, but is a more general concept.  I think it should be hoisted up to MLIR/LogicalResult.h or something.  While we're talking about this, why is it in MLIR/Support instead of LLVM/Support? :)

**Comment by joker-eph** [comment]
I believe that most of MLIR Support exists because we encountered push back from some LLVM folks about things we did for MLIR that they feel wouldn't generalize enough for being suitable for LLVM Support (not that I agree with the conclusion).

**Comment by lattner** [comment]
I think that was a really long time ago before MLIR entered the monorepo.  Would it make sense to reopen that discussion?  Do you recall who pushed back?

**Comment by tschuett** [comment]
You could put it into a top-level support library as a compromise resp. first step.

**Comment by joker-eph** [comment]
Actually we'd want to move most of the LLVM Support library in a top-level library, but that is a significant amount of work!

**Comment by tschuett** [comment]
I just wanted to propose the idea of doing it in smaller steps.

**Comment by lattner** [comment]
This is the first small step here: https://reviews.llvm.org/D123760

**Comment by lattner** [comment]
I moved it up to LogicalResult.h which is the right logical step for this.  I think there is a broader question about merging mlir/Support into LLVM Support, but that is pretty separable from ParseResult specifically.
