### ISSUE TITLE
[clang-format] command line parameter -lines ignored when using QualifierAlignment

### ISSUE THREAD

**Issue by my-name-is-already-taken** [llvm/llvm-project#54888]
When using the `QualifierAlignment` option, clang-format ignores the command line parameter `-lines`.

Example:
```
// test.cpp
void foo(const int& value){
  // do something
}

void bar(const int& value){
  // do another thing
}
```

This results in
```
> clang-format test.cpp -lines=2:2 -style="{Language: Cpp, QualifierAlignment: Right}"
// test.cpp
void foo(int const &value) {
  // do something
}

void bar(int const &value) {
  // do another thing
}
```

Not only are the qualifiers in line 6 formatted, but rather the whole line. Compare this to the result of formatting without the `QualifierAlignment` option:
```
> clang-format test.cpp -lines=2:2 -style="{Language: Cpp}"
// test.cpp
void foo(const int &value) {
  // do something
}

void bar(const int& value){
  // do another thing
}
```
This is using clang-format version 14.0.0, obtained from the LLVM releases page.

**Comment by michaelkourlas** [comment]
The `--offset` and `--length` parameters seem to be ignored as well.

**Comment by owenca** [comment]
https://reviews.llvm.org/D149643
