### ISSUE TITLE
Failure to fold shift amount offset into shift of a constant

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#54890]
This was noticed in an internal test:
```
define i32 @src(i32 %0) {
%1:
  %2 = sub i32 %0, 1
  %3 = shl nsw i32 2, %2
  ret i32 %3
}
=>
define i32 @tgt(i32 %0) {
%1:
  %2 = shl nsw i32 1, %0
  ret i32 %2
}
Transformation seems to be correct!
```

**Comment by davidbolvansky** [comment]
Related: https://github.com/llvm/llvm-project/issues/41976

**Comment by rotateright** [comment]
Unlike the related bug, this one needs 'nsw/nuw' or 'exact' on the shift to guard against overshift mishaps:
https://alive2.llvm.org/ce/z/nAMU6A

**Comment by rotateright** [comment]
shl nsw:
https://alive2.llvm.org/ce/z/btUaxH

shl nuw propagates nuw:
https://alive2.llvm.org/ce/z/rkTU9K

**Comment by RKSimon** [comment]
Thank you @rotateright !

**Comment by rotateright** [comment]
Reopening - maybe I shouldn't use the auto-close magic text anymore. :)
Something's not right with the matching - some bots failed, so I reverted.

**Comment by rotateright** [comment]
It took a long time for bots to recover...trying again without claiming to fix this just yet:
664ae7bbcc74

**Comment by rotateright** [comment]
Looks like we're good this time - closing.
