### ISSUE TITLE
[llvm-ar question] file too small to be an archive

### ISSUE THREAD

**Issue by 0x7cc** [llvm/llvm-project#54891]
my test code:
```cpp
#include <stdint.h>
#include <stddef.h>

#if defined(__clang__) || defined(__GNUC__)

size_t
vmcs_set_field(size_t field, size_t value)
{
  size_t eflags;
  __asm__ __volatile__("vmwrite %[value], %[field]" : : [field] "r"(field), [value] "r"(value));
  __asm__("\n pushf"
          "\n pop %[to]"
          : [to] "=r"(eflags));
  return eflags & (size_t)0b1000001; // zf and cf
}

#endif
```

compile:

```shell
clang -c -target x86_64-pc-linux-gnu vmx.cxx -ffreestanding -fno-cxx-exceptions -fno-exceptions -fno-rtti -fno-unwind-tables -nogpulib -nostdlib -nostdlibinc -o vmx.o -std=c++17 -O3
```

generate static library:
```shell
llvm-ar rcs --format=gnu vmx.o
```

```
C:\msys64\clang64\bin/llvm-ar.exe: error: unable to load 'x86_64-pc-linux-gnu/vmx.o': file too small to be an archive
```

I tried to write more code, but still getting this error.
I don't know what size it needs to be to qualify.

llvm-ar version in msys2:
```shell
$ llvm-ar --version
LLVM (http://llvm.org/):
  LLVM version 13.0.1
  Optimized build.
  Default target: x86_64-w64-windows-gnu
  Host CPU: znver1
```

**Comment by 0x7cc** [comment]
> @0x7cc, llvm-ar operates on archives, with the following usage pattern: `llvm-ar <options...> <archive> <objects...>`
> 
> You've provided just one input argument, so that is treated as an archive. The `rcs` command means "replace an archive member, don't warn if you need to create the archive, and create the symbol table". As such, you are telling llvm-ar to read in `vmx.o` as an archive, and then rebuild its archive symbol table. As `vmx.o` is not an archive, this will fail. The error message is just one possible error message you may get. Did you mean to do something like `llvm-ar rcs --format=gnu archive.a vmx.o` to add `vmx.o` to a new archive `archive.a`?

thanks for you reply.
I'm sorry for my stupidity, I didn't catch this error in time when copying the command.

**Comment by jh7370** [comment]
No problem - happens to the best of us!
