### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by rdwnsjjd** [llvm/llvm-project#54898]
I got this error while building a tool in clang:
```bash
llvm-project-main/clang/include/clang/Basic/ObjCRuntime.h:21:10: fatal error: llvm/Support/HashBuilder.h: No such file or directory
   21 | #include "llvm/Support/HashBuilder.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

how to fix it?

**Comment by EugeneZelenko** [comment]
Are llvm headers added to Clang include path? What is Clang invocation?

**Comment by rdwnsjjd** [comment]
I just got llvm-project src code and `cd` to `clang` dir and `mkdir build && cd build` and then `cmake ..`.
then `cd` to one of the tools and `make`. this error occurred.

**Comment by EugeneZelenko** [comment]
LLVM must be built first. Please read build procedure documentation.

**Comment by rdwnsjjd** [comment]
Complete build?
I must build it completely?
so I want to use libtooling for my own project. I want clang to get me AST. so I have no scene that what I must do to build my project with libtooling?

**Comment by EugeneZelenko** [comment]
Clang (and tooling) depends on LLVM.

**Comment by rdwnsjjd** [comment]
well, it means, if I want to use it in my project, each time of building, I must build llvm??

**Comment by rdwnsjjd** [comment]
I really have problem in this context. where can I discuss and get help quickly??

**Comment by EugeneZelenko** [comment]
https://discourse.llvm.org is best place to ask questions.

**Comment by fhahn** [comment]
> I must build it completely?
> well I want to use libtooling for my own project. I want clang to get me AST. so I have no scene that what I must do to build my project with libtooling?

I think you need to configure your build using the top-level CMakeLists.txt. Please take a look at the documentation for building LLVM and related projects: https://llvm.org/docs/CMake.html

I am going ahead and close this issue, as it is likely a configuration problem. For help & questions about building LLVM & related projects, https://discourse.llvm.org/ is likely the best place to get help, as @EugeneZelenko mentioned.
