### ISSUE TITLE
Compiler-RT fails to compile

### ISSUE THREAD

**Issue by MarcusJohnson91** [llvm/llvm-project#54903]
Version: Git main as of yesterday

I'm developing a feature for Clang, and my version of Clang is crashing, no big deal that's what debugging is for.

the problem is, Compiler-RT is trying to use the freshly created compiler that crashes to finish building llvm, so llvm doesn't fully compile.

there's a lot more errors, the point is, when the build reinvokes cmake and changes the compiler to `./bin/clang` it all falls apart.

cmake build command:

cmake -G Ninja -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_INSTALL_PREFIX="/Library/Developer" -DLLVM_TARGETS_TO_BUILD="X86" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_CREATE_XCODE_TOOLCHAIN=ON -DLLVM_OPTIMIZED_TABLEGEN=ON -DCMAKE_OSX_DEPLOYMENT_TARGET=12.1 -DLLVM_USE_SANITIZER=Address -DLLVM_CODESIGNING_IDENTITY="lldb_codesign" -DINSTALL_RPATH="/Library/Developer/Toolchains" -DLLVM_LIBC_MPFR_INSTALL_PATH="/usr/local/Cellar/mpfr/4.1.0" /Users/Marcus/Source/External/LLVM/llvm

----

errors:

-- Build files have been written to: /Users/Marcus/Source/LLVM_NINJA/runtimes/builtins-bins
[119/826] Building C object CMakeFiles/clang_rt.cc_kext_i386_osx.dir/os_version_check.c.o
FAILED: CMakeFiles/clang_rt.cc_kext_i386_osx.dir/os_version_check.c.o 
/Users/Marcus/Source/LLVM_NINJA/./bin/clang --target=x86_64-apple-darwin20.6.0 -DKERNEL_USE -I/Users/Marcus/Source/External/LLVM/compiler-rt/lib/builtins/../../include -O2 -g -DNDEBUG -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -mmacosx-version-min=10.5 -fPIC -O3 -fvisibility=hidden -DVISIBILITY_HIDDEN -Wall -fomit-frame-pointer -arch i386 -mkernel -MD -MT CMakeFiles/clang_rt.cc_kext_i386_osx.dir/os_version_check.c.o -MF CMakeFiles/clang_rt.cc_kext_i386_osx.dir/os_version_check.c.o.d -o CMakeFiles/clang_rt.cc_kext_i386_osx.dir/os_version_check.c.o -c /Users/Marcus/Source/External/LLVM/compiler-rt/lib/builtins/os_version_check.c

----

[128/826] Building C object CMakeFiles/clang_rt.cc_kext_x86_64_osx.dir/fixdfdi.c.o
ninja: build stopped: subcommand failed.
FAILED: runtimes/builtins-stamps/builtins-build /Users/Marcus/Source/LLVM_NINJA/runtimes/builtins-stamps/builtins-build 
cd /Users/Marcus/Source/LLVM_NINJA/runtimes/builtins-bins && /usr/local/Cellar/cmake/3.23.0/bin/cmake --build .

**Comment by MarcusJohnson91** [comment]
This seems relevant...

I'mma dig more

----

[3/15] Performing configure step for 'builtins'
-- Found OSX_SYSROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk
CMake Warning at /Users/Marcus/Source/External/LLVM/compiler-rt/cmake/Modules/CompilerRTUtils.cmake:356 (message):
  llvm-config finding testingsupport failed with status 1
Call Stack (most recent call first):
  CMakeLists.txt:28 (load_llvm_config)

**Comment by MarcusJohnson91** [comment]
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_C_COMPILER= /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CMAKE_ASM_COMPILER= /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang

**Comment by fhahn** [comment]
I think the information shared so far doesn't show the actual error/crash. Could you share the actual errors?

**Comment by MarcusJohnson91** [comment]
Ok, here's the crash files from the llvm command.

it's the preprocessed os_version_check.c file and an sh file containing the actual command ran, the zip is about 200kb

https://drive.google.com/file/d/19dCajRhethzQmZk0Z1Jqh2oJf88GqjFt/view?usp=sharing
