### ISSUE TITLE
SEH for Windows aarch64: Invalid RegF count for packed unwind data

### ISSUE THREAD

**Issue by egelke** [llvm/llvm-project#54900]
There is an issue when clang generates a packed unwind data including Float Registers, when you provide a even number of RegF the generated packed unwind data has an odd number (2 -> 1, 4 -> 3, ...).

For example:

```asm
    .global _start
_start:
    .seh_proc _start
    stp  x19,x20,[sp,#-0x30]!
    .seh_save_regp_x x19, 0x30
    stp  d8,d9,[sp,#0x10]
    .seh_save_fregp d8, 0x10
    stp  d10,d11,[sp,#0x20]
    .seh_save_fregp d10, 0x20
    stp  fp,lr,[sp,#-0x10]!
    .seh_save_fplr_x 0x10
    mov  fp,sp
    .seh_set_fp
    .seh_endprologue

    //return value
    mov w0, wzr

    .seh_startepilogue
    ldp  fp,lr,[sp],#0x10
    .seh_save_fplr_x 0x10
    ldp  d10,d11,[sp,#0x20]
    .seh_save_fregp d10, 0x20
    ldp  d8,d9,[sp,#0x10]
    .seh_save_fregp d8, 0x10
    ldp  x19,x20,[sp],#0x30
    .seh_save_regp_x x19, 0x30
    .seh_endepilogue
    ret
    .seh_endfunclet
    .seh_endproc
```

Generates the following pdata (`dumpbin /UNWINDINFO bin\Program.exe`):
```
   Start=40001000  Flag=1  FuncLen=2C  RegF=3  RegI=2  H=0  CR=3  FrameSize=0x40
      [RawPdata=00001000 0262602D]
      +0000 stp  x19,x20,[sp,#-0x30]!; Actual=stp         x19,x20,[sp,#-0x30]!
      +0004 stp  d8,d9,[sp,#0x10]    ; Actual=stp         d8,d9,[sp,#0x10]
      +0008 str  d10,[sp,#0x20]      ; Actual=stp         d10,d11,[sp,#0x20]
**** Expected opcode FD0013EA
      +000C stp  fp,lr,[sp,#-0x10]!  ; Actual=stp         fp,lr,[sp,#-0x10]!
      +0010 mov  fp,sp               ; Actual=mov         fp,sp
   Epilog #1 unwind:  (Offset=18)
      +0018 ldp  fp,lr,[sp],#0x10    ; Actual=ldp         fp,lr,[sp],#0x10
      +001C ldr  d10,[sp,#0x20]      ; Actual=ldp         d10,d11,[sp,#0x20]
**** Expected opcode FD4013EA
      +0020 ldp  d8,d9,[sp,#0x10]    ; Actual=ldp         d8,d9,[sp,#0x10]
      +0024 ldp  x19,x20,[sp],#0x30  ; Actual=ldp         x19,x20,[sp],#0x30
      +0028 ret                      ; Actual=ret
```

Although d8/d9 and d10/d11 are coded exactly the same in asm; the former is saved as pair in the pdata while the later is saved as a singleton.

**Comment by efriedma-quic** [comment]
How confident are you that dumpbin is actually right here?  The spec, clang, msvc, and "llvm-readobj -unwind" all seem to agree that RegF=3 is correct here.

**Comment by egelke** [comment]
It is correct that RegF=3 is what's in the exe, but that means that one got dropped at compile time because I added 4 in my code:

```asm
     stp  d8,d9,[sp,#0x10]
    .seh_save_fregp d8, 0x10
    stp  d10,d11,[sp,#0x20]
    .seh_save_fregp d10, 0x20
```

So, while the code does add both d10 and d11 to the stack and use the correct seh_save_freg**p** directive to tell clang; clang generates a packed unwinding data with RegF=3 instead of RegF=4.  llvm-readobj is correct to report it as RegF=3 because that what pdata segment with value #0262602D means (I checked) but that is not what clang should have generated.

When I do the same for only 2 RegF (i.e. remove `stp  d10,d11,[sp,#0x20]`, `.seh_save_fregp d10, 0x20`), then the outcome is RegF=1 instead of RegF=2.  So it seems that clang does decrease the count of RegF somewhere before writing it to the pdata-segment.

**Comment by efriedma-quic** [comment]
From https://docs.microsoft.com/en-us/cpp/build/arm64-exception-handling :

"RegF is a 3-bit field indicating the number of non-volatile FP registers (d8-d15) saved in the canonical stack location. (RegF=0: no FP register is saved; RegF>0: RegF+1 FP registers are saved)."

**Comment by egelke** [comment]
Excellent, they put some crucial information between brackets.  At least I'm not the only one that over looked, so did the devs of dumpbin.  I guess that I have to open (another) bug there instead.

**Comment by egelke** [comment]
Issue created with Microsoft: [RegF-field-in-packed-unwind-data-incorre #10013430](https://developercommunity.visualstudio.com/t/RegF-field-in-packed-unwind-data-incorre/10013430)
