### ISSUE TITLE
[IROutliner] 'OutputStoreBBs.size() < 2 && "Different store sets not handled!"' when compiling CINT2017rate/502.gcc_r

### ISSUE THREAD

**Issue by ornata** [llvm/llvm-project#54902]
This bugpoints down to the following issue:

https://godbolt.org/z/Yx6TK659b

CC: @AndrewLitteken

**Comment by AndrewLitteken** [comment]
Resolved by this patch: https://reviews.llvm.org/D122207

**Comment by ornata** [comment]
Oh! It's a dupe. Phew :)

**Comment by EugeneZelenko** [comment]
Duplicate of #54431.
