### ISSUE TITLE
Merge `[ELF][AArch64] Fix unneeded thunk for branches to hidden undefined weak` into release/14.x

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#54915]
02eab52866775f1476028129d1b114235fddc127 has fixed an issue impacting the Linux kernel's `ARCH=arm64` build with ld.lld: https://github.com/ClangBuiltLinux/linux/issues/1624

**Comment by tstellar** [comment]
@smithp35 Is this safe to backport.

**Comment by MaskRay** [comment]
I did not notice this missed 14.0.2. It would be good to have this in 14.0.4.

**Comment by smithp35** [comment]
Yes this is safe to backport. My apologies for the delay in responding, I think it scrolled off the top of my inbox and I forgot about it.

**Comment by tstellar** [comment]
Merged: 588b95a2b88e
