### ISSUE TITLE
IIFE in init statement produces redefinition error | clang bug

### ISSUE THREAD

**Issue by alyanser** [llvm/llvm-project#54913]
```
for(int x = []{ int x{}; return x; }();;); // error: redefinition of 'x' 

int x = []{ int x{}; return x; }(); // ok as expected
```
live example : https://godbolt.org/z/oo5qvM35x

**Comment by junaire** [comment]
After spending some time investigating, I think I find where things go wrong: 
https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/IdentifierResolver.cpp#L124
We are checking if the current scope's parent is a `ControlScope` (if/switch/while/for statement), this definitely will cause a redefinition error. However, I'm not sure what's the best way to solve this problem...

**Comment by junaire** [comment]
A naive fix: https://reviews.llvm.org/D123840
