### ISSUE TITLE
Merge `[ELF][ARM] Fix unneeded thunk for branches to hidden undefined weak` into release/14.x

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#54926]
b483ce12281e31311efacf0047f95767517dcde9 has fixed branches to hidden undefined weak for ARM, similar to #54915 for AArch64.

**Comment by tstellar** [comment]
@smithp35 Is this safe to backport? https://github.com/llvm/llvm-project/commit/b483ce12281e31311efacf0047f95767517dcde9

**Comment by smithp35** [comment]
Yes this is safe, apologies for the delay in responding.

**Comment by tstellar** [comment]
@MaskRay The test fails in the release/14.x branch.

**Comment by MaskRay** [comment]
> @MaskRay The test fails in the release/14.x branch.

If you merge the AArch64 version #54915 as well, `ninja check-lld-elf` will pass. I have tested it.

**Comment by tstellar** [comment]
Merged: 5f66e721ec1d
