### ISSUE TITLE
Floating point exception in clang14.0.0 with -mavx2

### ISSUE THREAD

**Issue by KierenP** [llvm/llvm-project#54921]
Hi, I'm hoping someone can look at this and tell me if I've found a legitimate compiler bug.

I am compiling the following the small following test program:

```
#include <cfenv>
#include <iostream>

bool driver(unsigned int value, double lower, double upper) 
{
    return lower <= value && value <= upper;
}

int main() 
{ 
    feenableexcept(FE_INVALID);
    volatile int x = 62;
    volatile double lower = 31;
    volatile double upper = 62;
    volatile int y = driver(x, lower, upper);
}
```

I compile with the command: 
```
clang++ test_file.cpp -mavx2 -O3 -g
```

and when I run, I get: 
```
Floating point exception (core dumped)
```

----------------------

Compiler information: 
```
clang version 14.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/kieren.pearson/.conan/data/clang/14.0.0/_/_/package/2201725ed6c2736f243c00af939498ce6c18440d/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8.0.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
```

---------------------

I have explored this code in godbolt and compared the assembly difference between clang13.0.1 and clang14.0.0:

https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIM6SuADJ4DJgAcj4ARpjEEgBspAAOqAqETgwe3r56KWmOAiFhkSwxcVy2mPYFDEIETMQEWT5%2BAXaYDhl1DQRFEdGxCbb1jc05FQojvaH9pYNcAJS2qF7EyOwc5gDMocjeWADUJltuyFSMAG7H2CYaAILbu/uYRydOk8SYrNe3D/dRqE8B3QxDwF1iEC8DDSwDC6AOoQIBwuYi8mFIwJWUXoB1oqAA7rEMegsTivEkkrEFkd7iYAOxWe4HZkHT4EVYMXEE2KvNzHAAiyNRL3M8VFQu8IpOAoO5MpxGOjIedP5v1%2BiIOLCYoQg1LVDJpdxZB3OjCY2MwmFU6ySBAgADFsAB9ACS4QAancgi7%2BQtFb9jRdPExHDiNapXoL4mZ/UyWUGDKGXiSvBauYTiJGDlsuLGjfHg0nMamyRSeTLo3nA4W6C8NQBPLMgsEQ1QYvEZjFyql5%2Bn8jhLWicACsvD8HC0pFQnD5lmsBwUKzWIrMOd4BE0A6WAGsQJIuAA6MwATgAHGZ4sOzJJjxozBo6fpOJIx5up5xeAoQBpSBuJwPSDgWAYEQFBUBYJJazICgIDQCCoJQAwjC4LYNAqGhaAIWIvwgKI3yiUIGnrTgeFIOC2EEAB5BhaGI/9SCwLUjHEej8E%2BTpwS/eirQ6LwsJI3hESqN9aDwKJiCIjwsAE39QRYASlioAxgAUd08EwfFKMpcdSP4QQRDEdgpBkQRFBUdR6N0CokOMaxrH0MSv1gZg2BAKgWAIUhwTiAhiChbcFiWVBbQyLiAFpKK2A4wq1C5VE/KoOhqFwGHcTwWj0YIZhKMpclSdIBDGPwKjyAqGD6HL5kqaouimIq9HaToBG6RoKoGcphh6eqJimNq5nKJZF1WdY9F8y0FKfDhR1IcdJ2nDhVFPeIwviSQDj2QxgAOFCDw0A8uAOCBZysSwMVwQgSCOVcKgODx4PoTNtkWddN0C0hd0kOkDzpU871W086WHY9hyB09JpfUh5OHH9Zt4ebP2/X9XsAkCICQODIIe8hKAxhCNuQyQNB/DCsOIHC8PogjmGIOjSPIxgCGo2i30YzaWMnNikpbLjJx45A%2BI2UihKHejRPEySMEF9c5ImpSmBUtSNK0xgZL04RRHEYy1bMtQ310AIbJQOzTrFpyoBc9h3M87yQF8/y3uCmpwsi6LYvi6quecCBXHq69AlSvrctQ5J8pqX3pFKmpA8GYPGpqFqmnSnI/bj2qemjuJY7qpPWmkSZ0%2By9qQFQwalxGioxqlwcR1fej5sW5bVvWmztskXbdsO477IOc6iEe66MTuzHy1XMwFhe/83oQL4sDiXVwd4KGYbfeHbERv8tDe3dh1Pb60LpLZPuh486WPLZJq2Wu5o/JHJ%2BrjgzCvuGb43rcvOwjI9yAA%3D%3D

When looking into the clang14.0.0 code:

```
        vcvtsi2sd       xmm0, xmm0, rax
        vmovsd  xmm1, qword ptr [rsp + 24]      # xmm1 = mem[0],zero
        vmovsd  xmm2, qword ptr [rsp + 16]      # xmm2 = mem[0],zero
        vcmplepd        xmm2, xmm0, xmm2
        vcmplepd        xmm0, xmm1, xmm0
        vandpd  xmm0, xmm0, xmm2
        vmovd   eax, xmm0
        and     eax, 1
```

we can see that the integer is first converted into a double in the lower 64 bits of the `xmm0` register. The lower and upper bounds are put into the `xmm1` and `xmm2` registers. Then `vcmplepd` compares each double in the respective registers. Then a logical and is done and we finally extract the very lowest bit. 

I believe clang is going wrong here because it doesn't believe it needs to zero the `xmm0` register. `vcvtsi2sd` leaves the upper 64 bits unchanged and we later discard all but the lowest bit, so this would normally be fine except `vcmplepd` will raise a signal if either of the operands is a `NAN` which I believe is the case here. For whatever reason the register on my computer starts off with a `NAN` in the higher 64 bits.

Clang13.0.1 on the other hand, generates: 

```
        vcvtsi2sd       xmm0, xmm0, rax
        vucomisd        xmm0, qword ptr [rsp + 24]
        vmovsd  xmm1, qword ptr [rsp + 16]      # xmm1 = mem[0],zero
        setae   al
        vucomisd        xmm1, xmm0
        setae   cl
        and     cl, al
```

notably, it uses a different comparison function `vucomisd`, and this comparison function only compares the lowest 32 or 64 bits of the register depending on the operands. This is safe because the unchanged higher bits in xmm0 after `vcvtsi2sd` are not compared. 

It seems the clang14 generated code is wrong.

**Comment by efriedma-quic** [comment]
Normally the compiler assumes you don't call feenableexcept or equivalent.  To change that assumption, you can pass `-ffp-exception-behavior=strict` on the command-line, or use `#pragma STDC FENV_ACCESS ON` in your source file.

**Comment by KierenP** [comment]
Thank you for the help, that's fixed my issue. Feel free to close this issue as it is not an issue with clang itself.
