### ISSUE TITLE
[MLIR:Python] Improve ergonomics of op constructor APIs in Python bindings

### ISSUE THREAD

**Issue by hawkinsp** [llvm/llvm-project#54932]
We've made extensive use of the MLIR Python bindings to build IR in the MHLO dialect (in the TensorFlow tree) in JAX (https://github.com/google/jax).

The experience has been fairly positive overall, but there are two things that would probably significantly improve the ergonomics of building IR in an MLIR dialect via the Python bindings. While this request comes from experience with the out-of-tree MHLO dialect, I strongly suspect the same is true for any dialect, not just that one.

a) support default arguments to op constructors.

Even if an operator has defaults in its tablegen specification, e.g., via `DefaultValuedAttr`, these defaults aren't available or used by the Python constructors. A natural change would be to make operator arguments that have defaults into Python keyword arguments with default values. This would allow users to omit these attributes, which is important both for ergonomics and for compatibility if the dialect changes. Currently adding a new attribute, even one with a default value, is always a breaking change for Python code.

b) support automatic casts from standard Python types (e.g., integers, lists, ...) into corresponding attributes when passed to op constructors.

If an operator accepts, say, a `BoolAttr` as an argument to its constructor, it would be very nice to pass a Python bool (e.g., `False`) rather than writing out `mlir.ir.BoolAttr.get(False)`. The same thing applies for integer attributes from Python integers, string attributes from Python strings, and dense elements attributes from Python lists. The reason to do this is primarily ergonomics: currently it is very verbose to have to write out attribute types each time.

@stellaraccident

**Comment by jpienaar** [comment]
For (a) one could even set to default value None and then convert that to NULL during C API call so that one gets the current C++ constructor behavior there. That would reduce effort in Python generator and reuse the default value attribute behavior C++ side.

**Comment by jpienaar** [comment]
https://github.com/llvm/llvm-project/commit/3781b7905d8d808e5d4e97d597263f8ac48541b8 along with https://github.com/llvm/llvm-project/commit/7d273fde110d7735512c3b71a83eb88e89d189cc should address/enable addressing most of this.
