### ISSUE TITLE
[clang-tidy][ExceptionAnalyzer] Does not model `noexcept` bounds

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#54956]
https://godbolt.org/z/14E6r8a7s

```
bool cond();

void callee() noexcept {
    if(cond())
        throw 42;
}

void caller() noexcept {
    callee();
}
```

Even if an exception is thrown in `callee()`, it will terminate the program,
so as far as `caller()` is concerned, `callee()`does not throw.

**Comment by ngg** [comment]
I've submitted https://reviews.llvm.org/D134588 as a candidate fix.

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D145865

**Comment by carlosgalvezp** [comment]
@LebedevRI Technically you are correct - if a function is marked `noexcept` and there's a `throw` statement in it, an exception won't be thrown, and instead `std::terminate` will be called.

However, is this the spirit of the check? Is it the goal that people silence warnings by adding `noexcept`? (which other guidelines/checks mandate to add). 

The way I see it, the spirit of the check is that there are some special functions that are expected to be safe. They shall not throw exceptions and they shall not lead to unexpected termination of the program (as per the docs). This is clearly stated:

> The functions which should not throw exceptions are the following:
>
> ...
> Functions marked with throw() or noexcept

The technicality of whether an exception is thrown or whether `std::terminate` is called is irrelevant IMHO - both things are "bad" and should not happen in these special functions.
