### ISSUE TITLE
Simple shift in loop body not optimized to eliminate the loop

### ISSUE THREAD

**Issue by zero9178** [llvm/llvm-project#54967]
Given following IR:
```llvm
define i32 @src(i32 %a) {
  %1 = icmp eq i32 %a, 0
  br i1 %1, label %loopexit, label %preheader

loopexit:
  %2 = phi i32 [ 1, %0 ], [ %5, %preheader]
  ret i32 %2

preheader:
  %3 = phi i32 [ 0, %0 ], [%6, %preheader ]
  %4 = phi i32 [ 1, %0 ], [%5, %preheader ]
  %5 = shl i32 %4, 1
  %6 = add nuw i32 %3, 1
  %7 = icmp eq i32 %6, %a
  br i1 %7, label %loopexit, label %preheader
}
```
While the tripcount of the loop is not static, it is equal to `%a`. That should make it possible to optimize the above code to simply:
```llvm
  %c = shl i32 1, %a
  ret i32 %c
```

Corresponding Alive 2 link: https://alive2.llvm.org/ce/z/f_xJrW

**Comment by topperc** [comment]
If %a is >= 32 doesn't the loop produce 0? That's not what the shift by itself would produce.

**Comment by zero9178** [comment]
Ahh true. Since if it were larger than 32 bit it'd result in undefined behaviour instead. Thanks!
