### ISSUE TITLE
Hyperthread detection in LLD LTO

### ISSUE THREAD

**Issue by xkszltl** [llvm/llvm-project#54961]
When using LLD+LTO to build LLVM itself, by default it'll detect hardware concurrency and utilize all cores.
However, seems it only use up to the physical cores.
For example, in the below screenshot from a single socket 18C/36T Xeon Gold 6154, we only observed up to about 1800% of single-process utilization.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/5203025/163800763-b74b91c8-6412-4a25-b56d-1d6c3b148b43.png">

- Is this expected?
- Is this intentional, e.g. maybe lld can already utilize ALU's so well without extra PC.

**Comment by MaskRay** [comment]
This is an deliberate decision. See `heavyweight_hardware_concurrency` and its occurrences in lld's ports.
