### ISSUE TITLE
Almost all OpenMP pre-merge checks failing: error: command failed with exit status: -7

### ISSUE THREAD

**Issue by Meinersbur** [llvm/llvm-project#54966]
Starting with https://buildkite.com/llvm-project/llvm-main/builds/4647#6ddc666e-2096-4205-bfae-470506618958

The diff between the last working is 201c4b9..acc56e5, however there is no obvious change that could cause this. Maybe a change in the builder's configuration?

@metaflow

**Comment by jhuber6** [comment]
All the tests are still passing when I run it locally, so I would assume that the tests themselves are fine. Does anyone know how the builders are configured?

**Comment by Meinersbur** [comment]
The pre-merge BuildKit config is available here: https://github.com/google/llvm-premerge-checks. If the only thing you need is the cmake line, you can look into the log output:
```
Running cmake with these arguments:

cmake ../llvm -D LLVM_ENABLE_PROJECTS="compiler-rt;polly;libunwind;flang;libc;pstl;openmp;libclc;llvm;clang;clang-tools-extra;mlir;lld;bolt" -G Ninja -D CMAKE_BUILD_TYPE=Release -D LLVM_ENABLE_ASSERTIONS=ON -D LLVM_BUILD_EXAMPLES=ON -D LLVM_LIT_ARGS="-v --xunit-xml-output test-results.xml" -D LLVM_ENABLE_LLD=ON -D CMAKE_CXX_FLAGS=-gmlt -DBOLT_CLANG_EXE=/usr/bin/clang -DBOLT_LLD_EXE=/usr/bin/ld.lld -D LLVM_CCACHE_BUILD=ON
```
I cannot reproduce it locally either.

**Comment by jhuber6** [comment]
Maybe there's some problem with the projects build of OpenMP? I only build with the runtimes option so it's possible there was some regression.

**Comment by Meinersbur** [comment]
I usually build the [projects config](https://lab.llvm.org/staging/#/builders/155) and so far it ALWAYS worked more reliable than the runtimes build, which has its own problems, eg. #54857

**Comment by shiltian** [comment]
I think this is not an issue anymore. Close it for now. If you still see it, feel free to reopen it.
