### ISSUE TITLE
[build error] build llvm12 in centos7 with gcc 7.3  

### ISSUE THREAD

**Issue by ZCBing** [llvm/llvm-project#54971]
When build llvm12, I got a build error in centos7 with gcc7.3.

![image](https://user-images.githubusercontent.com/96521335/163943501-e8bc9d1b-210e-4b71-b6d4-32607f404831.png)

Here is my cmake option
cmake -G "Unix Makefiles"                                          \
                 -DCMAKE_INSTALL_PREFIX=$INSTALL       \
                 -DCMAKE_BUILD_TYPE=Release                 \
                 -DLLVM_OPTIMIZED_TABLEGEN=On          \
                 -DLLVM_USE_LINKER=gold      
                 -DLLVM_ENABLE_PROJECTS=clang;compiler-rt;lld;clang-tools-extra      \
                 -DLLVM_LINK_LLVM_DYLIB=On                   \
                 -DLLVM_ENABLE_ZLIB=OFF                         \
                 -DLLVM_ENABLE_TERMINFO=OFF               \
                 -DLLVM_TARGETS_TO_BUILD="X86;RISCV" 

it works in ubuntu.

What can I do to solve it?

**Comment by fhahn** [comment]
It looks like you are hitting a bug in `ld.gold`. I don't think there's anything to fix on the llvm side, hence I am going to close the issue.  You could try with a different linker.

**Comment by DimitryAndric** [comment]
Btw, you might try newer versions of the CentOS 7 `devtoolset` packages. At the moment, the latest is `devtoolset-11`, which has gcc 11.2.1, and binutils 2.36.1.
