### ISSUE TITLE
Infinite loop in MemCpyOpt

### ISSUE THREAD

**Issue by fiesh** [llvm/llvm-project#54983]
The following code makes `clang++` run endlessly until resource exhaustion from 13 on.  <= 12 works.

It only runs endlessly when `-O1` is passed.  It does compile with `-O0`.

```cpp
extern "C" void *memcpy(void *, void *, long);
struct Utf32String {
  void operator=(const Utf32String &that) {
    if (this != &that) {
      _data = new char32_t[_length]();
      _length = that._length;
      memcpy(_data, that._data, sizeof(char32_t) * _length);
    }
  }
  long _length;
  char32_t *_data;
};
struct InputBuffer {
  Utf32String _hint;
  int handle_hints();
};
int InputBuffer::handle_hints() {
  _hint = Utf32String();
  return 0;
}
```

**Comment by DimitryAndric** [comment]
I've narrowed this down to the range [b2f933a6ce8..2468fdd9af3], but my builds are still running and I have to catch some sleep. Looks like either 2902bdeea1a5 or 9080444f3311, both by @nikic, might be the culprit?

**Comment by DimitryAndric** [comment]
Okay, it turns out 2902bdeea1a is where the regression begins.

**Comment by nikic** [comment]
Reduced:
```
; RUN: opt -S -memcpyopt < %s
declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)
declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)
 
define void @test(ptr %p) {
  call void @llvm.memset.p0.i64(ptr %p, i8 0, i64 1, i1 false)
  %size = shl i64 0, 0
  call void @llvm.memcpy.p0.p0.i64(ptr %p, ptr null, i64 %size, i1 false)
  ret void 
} 
```

**Comment by nikic** [comment]
So the issue here is that the processMemSetMemCpyDependence() transform is effectively a no-op if the memcpy size is zero. It will transform the memset into another memset with the same pointer and same size -- just written in a more complicated way. AA is smart enough to see that `p == (p + (0 << 0))`, do we keep doing the transform.

**Comment by nikic** [comment]
I've put up a possible patch at https://reviews.llvm.org/D124078, though I'm not sure this is the right approach.
