### ISSUE TITLE
libc build, for rv64gc

### ISSUE THREAD

**Issue by advancedwebdeveloper** [llvm/llvm-project#54986]
64 bit RISC-V related.

**Comment by EugeneZelenko** [comment]
@advancedwebdeveloper: Please provide more details.

**Comment by jrtc27** [comment]
They want someone to port it (asked on the official RISC-V International Slack and got no response), so just a feature request against LLVM libc, nothing to do with the LLVM RISC-V backend. I don't know why it's of such great interest, it's a nascent project that's not hugely useful in the real world yet.

**Comment by EugeneZelenko** [comment]
@jrtc27: backend label is still relevant because `libc` would be ported for specific hardware architecture.

**Comment by jrtc27** [comment]
No it's not. Backend is for llvm/lib/Target-related things. What someone does in libc/ is totally irrelevant and I don't care about those bugs.

**Comment by jrtc27** [comment]
(It is a bug relating to RISC-V, but it is not a bug relating to the RISC-V _backend_ any more than "my favourite C/C++ program doesn't support RISC-V")

**Comment by advancedwebdeveloper** [comment]
>   Unknown CMake command "llvm_update_compile_flags".

**Comment by sivachandra** [comment]
Duplicate of #55752
