### ISSUE TITLE
Please test documentation generation on precommit CI

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#54998]
It would be nice for precommit CI to also test generation of documentation. We have several post-commit builders that catch when people introduce errors into .rst files, but it would be better if people got that feedback when posting their patches instead of after landing them.

https://llvm.org/docs/SphinxQuickstartTemplate.html#generating-the-documentation

**Comment by boomanaiden154** [comment]
Now that we’re testing documentation builds in GitHub Actions for all subprojects, I think this is done.

Please reopen if something else needs to be done.
