### ISSUE TITLE
Backport e970d2823cf2a666cb597bf06ff8e0d0b880d361 to the release/14.x branch

### ISSUE THREAD

**Issue by SquallATF** [llvm/llvm-project#54997]
llvm-mt add support `/notify_update` which need by Cmake
e970d2823cf2a666cb597bf06ff8e0d0b880d361

**Comment by tstellar** [comment]
@petrhosek Is this safe to backport? https://github.com/llvm/llvm-project/commit/e970d2823cf2a666cb597bf06ff8e0d0b880d361

**Comment by petrhosek** [comment]
Yes, this should be safe.

**Comment by tstellar** [comment]
Merged: 58d5fbe2c20b
