### ISSUE TITLE
How to add c++ function to LLJIT?

### ISSUE THREAD

**Issue by vifird** [llvm/llvm-project#55]
There is no `addGlobalMapping` in LLJIT, i found `InProcessMemoryManager`, but there is no demo to explain it, and also lack of docs.

**Comment by lhames** [comment]
Hi vifird. You should use LLJIT::defineAbsolute instead.

**Comment by vifird** [comment]
@lhames Thanks a lot.

**Comment by vifird** [comment]
@lhames And how to use it? how to get `JITEvaluatedSymbol` of c++ function? I cannot find any example in source code or stackoverflow.

**Comment by lhames** [comment]
defineAbsolute is just a wrapper for the absoluteSymbols function, which is documented in https://llvm.org/docs/ORCv2.html

**Comment by vifird** [comment]
@lhames And i got another problem [https://github.com/llvm/llvm-project/issues/81](https://github.com/llvm/llvm-project/issues/81)
