### ISSUE TITLE
clang-tidy check cppcoreguidelines-init-variables fixes bool variables with '= 0' instead of '= false'

### ISSUE THREAD

**Issue by sean-mcmanus** [llvm/llvm-project#55007]
This is an enhancement request, either by default or via a configuration setting.

I used clang-tidy 14.0.0.

Repro C++ code is

```cpp
int main()
{
bool b;
return 0;
}
```

See https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/init-variables.html.

Workaround: Re-running clang-tidy after this causes the https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-bool-literals.html warning to appear, which can be used to fix it.

**Comment by SimplyDanny** [comment]
I propose a fix [here](https://reviews.llvm.org/D129420).

**Comment by SimplyDanny** [comment]
Fixed by 33e212954430d6116d7743541a7e9be8cdfac196.
