### ISSUE TITLE
C: Non standard compliant behavior in strict standard mode

### ISSUE THREAD

**Issue by DaKnig** [llvm/llvm-project#55017]
the following program compiles, with `clang --std=c18`, when according to the standard it should not:

```c
;
int main() {}
```

notice that the `;` is in the top level of the translation unit. according to the standard:

```
translation-unit:
    (basically a list of at least one external-declaration)

external-declaration:
    function-definition
    declaration

function-definition:
    declaration-specifiers declarator declaration-listopt compound-statement
    (compound-statement *must* contain {} therefore ';' can't be part of this rule since there's no {} there)

declaration:
    declaration-specifiers init-declarator-list (optional) ;
    static_assert-declaration

declaration-specifiers:
    (contains at least one token out of a huge list)
    (therefore can't be empty therefore can't possibly be the empty ';')

static_assert-declaration:
    _Static_assert '(' constant-expression , string-literal ')' ;
    (obviously can't be that)
```
an empty `;` is not a static_assert-declaration and can't be a declaration - those must contain at least one token (some specifier).
it can't be a function definition, as that would end with `}`.
therefore it cannot be `external-declaration`, therefore it cannot be one of the variants of `translation-unit`.
if anything, it must appear inside a function.

an empty `;` is a null-statement; it can't happen outside functions, on the top level.

- obtained `clang-13.0.0-3` from the fedora repositories
- running fedora 35

**Comment by hubert-reinterpretcast** [comment]
Some diagnostics required for conformance are enabled only with `-pedantic`.
```
warning: extra ';' outside of a function [-Wextra-semi]
```

https://godbolt.org/z/1z155Pcz6
