### ISSUE TITLE
Fail to compile anything if `mlir/IR/PatternMatch.h` is included

### ISSUE THREAD

**Issue by jackalcooper** [llvm/llvm-project#55010]
- gcc version

```console
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```

- minimum case

```c
#include "mlir/IR/PatternMatch.h"
int32_t main(int32_t argc, char** argv) {}
```

- error

```console
In file included from XXXXX-opt.cpp:16:
XXXXX/build/oneflow/ir/llvm_monorepo-src/llvm/../mlir/include/mlir/IR/PatternMatch.h:1102:10: error: pack expansion does not contain any unexpanded parameter packs
       0)...};
       ~~^
1 error generated.
```

- source related
https://github.com/llvm/llvm-project/blob/1234b1c6d8113d50beef5801be607ad1d502b2f7/mlir/include/mlir/IR/PatternMatch.h#L1102

**Comment by strikef** [comment]
It seems the code becomes ill-formed when the assertion is erased due to NDEBUG.
This bug hasn't been fixed yet. Is there any update on this issue?

**Comment by zero9178** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/49157fd468521ee482d3f5a0ae1586f9d7c8a550
