### ISSUE TITLE
Allow compiling without emiting calls to __chkstk_ms on Windows

### ISSUE THREAD

**Issue by jcelerier** [llvm/llvm-project#55011]
MSVC allows it but not Clang: https://metricpanda.com/rival-fortress-update-45-dealing-with-__chkstk-__chkstk_ms-when-cross-compiling-for-windows/

**Comment by zero9178** [comment]
clang-cl supports it using the same syntax as MSVC, that is `/Gs<value>`. If using the GNU style driver, usually with MinGW, the corresponding command line flag seems to be `-mstack-probe-size=<value>`. GCC sadly does not support that flag and I haven't checked if there is any equivalent. 

Demo: https://godbolt.org/z/z61jfGPGo

**Comment by duk-37** [comment]
> Sadly it's not enough ; I'd like the same behaviour than linux here: https://godbolt.org/z/oKTfbejdM

If you _really_ want to do this, `-mno-stack-arg-probe` will [work](https://godbolt.org/z/G1zj1c79v).

**Comment by jcelerier** [comment]
>  When you change the alloca to a fixed-size array,

I mean, if I could do that I would not be using alloca in the first place haha. 


>  -mno-stack-arg-probe

Thanks, exactly what I needed !
