### ISSUE TITLE
clang-tidy check readability-container-data-pointer fix adds unnecessary () around expressions with '.'

### ISSUE THREAD

**Issue by sean-mcmanus** [llvm/llvm-project#55025]
This is an "enhancement" request.

With clang-tidy 14.0.0.

Use C++ code 
```cpp
#include <vector>

struct st1
{
    std::vector<int> vint;
    std::vector<int*> vintp;
};

int main()
{
    st1 _st1;
    _st1.vintp.emplace_back(&_st1.vint[0]);
    return 0;
}
```

The generated fix creates: `(_st1.vint).data()` which has an unnecessary extra (), i.e. it would ideally be `_st1.vint.data()`. The extra () doesn't appear unless the '.' is used.

**Comment by SimplyDanny** [comment]
I propose a fix [here](https://reviews.llvm.org/D129596).
