### ISSUE TITLE
clang-format incorrectly updates cursor positions when collapsing include blocks

### ISSUE THREAD

**Issue by bbarenblat** [llvm/llvm-project#55027]
If clang-format removes vertical whitespace from an `#include` block and `--cursor` points past the include block, clang-format will incorrectly compute the new cursor location. Here’s an example:

```sh-session
$ printf '#include "a"\n\n#include "b"\n' | clang-format --cursor=25
{ "Cursor": 24, "IncompleteFormat": false }
#include "a"
#include "b"
$ printf '#include "a"\n\n#include "b"\n' | clang-format --cursor=26
{ "Cursor": 26, "IncompleteFormat": false }
#include "a"
#include "b"
```

In this example, I pass clang-format the 27-byte string ```#include "a"\n\n#include "b"\n```. If I tell clang-format that the cursor is sitting on the close quote of `#include "b"` (byte 25), it correctly moves the cursor to byte 24. But if I tell clang-format the cursor is sitting on the newline immediately after `#include "b"` (byte 26), it keeps the cursor at byte 26. In an editor, this makes the cursor appear to move one byte forward.

This isn’t related to byte 26 being the last byte in the input. For example,

```sh-session
$ printf '#include "a"\n\n#include "b"\nf();\n' | clang-format --cursor=28
{ "Cursor": 28, "IncompleteFormat": false }
#include "a"
#include "b"
f();
```

adds a function call after the includes. Before the format, the cursor is sitting on byte 28, the open parenthesis of the call. Afterwards, it’s still sitting on byte 28, but this is now the closing parenthesis of the call.

This bug only occurs if changes get made to includes. For example,

```sh-session
$ printf 'int f() {\n\n  int value = 0;\n  return value;\n}\n' | clang-format --cursor=30
{ "Cursor": 29, "IncompleteFormat": false }
int f() {
  int value = 0;
  return value;
}
```

starts with the cursor on byte 30, the “r” of `return`. clang-format deletes the spurious blank line at the start of the function body and correctly moves the cursor to byte 29, keeping it on the “r”.

I tested this at commit a571f82a50416b767fd3cce0fb5027bb5dfec58c, but it also occurs in released versions of LLVM (LLVM 11.0.1, for instance).

**Comment by owenca** [comment]
It seems fine in 9be9074:
```
$ cat .clang-format
MaxEmptyLinesToKeep: 0
$ clang-format -version
clang-format version 15.0.0 (https://github.com/llvm/llvm-project 9be90748f1b6956801fa18bff5b0014a8f2f3f73)
$ printf '#include "a"\n\n#include "b"\n' | clang-format --cursor=26
{ "Cursor": 25, "IncompleteFormat": false }
#include "a"
#include "b"
$ printf '#include "a"\n\n#include "b"\nf();\n' | cf --cursor=28
{ "Cursor": 27, "IncompleteFormat": false }
#include "a"
#include "b"
f();
```

**Comment by bbarenblat** [comment]
It looks like `--style=Google` still doesn’t do the right thing:

```sh-session
$ pwd | sed "s|$HOME|~|"
~/projects/llvm/build
$ git describe
llvmorg-15-init-8425-g9be90748f1b6
$ ninja clang-format
ninja: no work to do.
$ bin/clang-format --version
clang-format version 15.0.0 (https://github.com/llvm/llvm-project.git 9be90748f1b6956801fa18bff5b0014a8f2f3f73)
$ rm -f .clang-format
$ printf '#include "a"\n\n#include "b"\n' | bin/clang-format --style=Google --cursor=26
{ "Cursor": 26, "IncompleteFormat": false }
#include "a"
#include "b"
$ echo MaxEmptyLinesToKeep: 0 >.clang-format
$ printf '#include "a"\n\n#include "b"\n' | bin/clang-format --style=file --cursor=26
{ "Cursor": 25, "IncompleteFormat": false }
#include "a"
#include "b"
```

Bisecting the Google configuration, it appears that `IncludeBlocks: Regroup` is the offending setting:

```sh-session
$ printf '#include "a"\n\n#include "b"\n' | bin/clang-format --style='{IncludeBlocks: Regroup}' --cursor=26
{ "Cursor": 26, "IncompleteFormat": false }
#include "a"
#include "b"
```

**Comment by owenca** [comment]
What’s the editor you were using?

**Comment by bbarenblat** [comment]
GNU Emacs out of Debian 11 (i.e., GNU Emacs 27.1 with some patches).

**Comment by owenca** [comment]
https://reviews.llvm.org/D124452
