### ISSUE TITLE
Please backport RISCV BUILD_VECTOR fixes to LLVM 14

### ISSUE THREAD

**Issue by frasercrmck** [llvm/llvm-project#55020]
Two vector codegen bugs made it into LLVM 14. Each has a commit adding a test and a subsequent commit with a fix.

Test 1: 00537946aa29
Fix 1: c5cac48549ed

Test 2: 627e21048a2c
Fix 2: 3e678cb77264

I think they should apply cleanly.

**Comment by tstellar** [comment]
/cherry-pick 00537946aa29928894ba140687de1b6f9494e44d c5cac48549ed254cd5ad5eef770ebfb22ccd9f64 627e21048a2c040d3e353cc4f0eb8f207b6ea61c 3e678cb77264907fbc2899c291ce23af308073ff

**Comment by tstellar** [comment]
@asb What do you think about backporting these?

**Comment by asb** [comment]
> @asb What do you think about backporting these?

LGTM.

**Comment by tstellar** [comment]
Merged: 21ce6cfd1d93 9efcce92b55b e19be4195b87 1f4c7b2a9120
