### ISSUE TITLE
[LLVM-COV] The nightly llvm-cov report is inaccessible due to ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by steakhal** [llvm/llvm-project#55035]
The `llvm.org` has the "Useful Links" section, in which there is the `llvm-cov` link pointing to the [https://lab.llvm.org:8080/coverage/coverage-reports/index.html](https://lab.llvm.org:8080/coverage/coverage-reports/index.html) page.

The site does not load with:
 - Firefox 99.0.1 (64-bit)
 - Microsoft Edge 100.0.1185.50 (Official build) (64-bit)

**Comment by gkistanova** [comment]
Thanks, Balazs!
I'll look into this.

**Comment by gkistanova** [comment]
The link has been fixed.
The correct link is https://lab.llvm.org/coverage/coverage-reports/index.html.

**Comment by steakhal** [comment]
How can I see how is this coverage report produced?

**Comment by gkistanova** [comment]
I think you are after
https://github.com/llvm/llvm-zorg/blob/main/zorg/jenkins/jobs/jobs/llvm-coverage
