### ISSUE TITLE
clang-tidy --quiet is not quite quiet

### ISSUE THREAD

**Issue by igagis** [llvm/llvm-project#55047]
# to reproduce

run `clang-tidy --quiet` with config which filters out, for example, one existing warning from non-user code (e.g. system headers)

# expected result

no `stderr` output is generated

# actual result

```
1 warning generated.
```
is printed to `stderr`

# version
```console
$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 11.0.1
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: haswell
```

**Comment by bjosv** [comment]
Might be a duplicate of #47042.
