### ISSUE TITLE
[ODS] Dialect ctor should be emitted to .cpp file, not .h file

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#55044]
ODS is generating dialect ctors inline in header files like this:

```cpp
class MyDialect : public ::mlir::Dialect {
  explicit MyDialect(::mlir::MLIRContext *context)
    : ::mlir::Dialect(getDialectNamespace(), context,
      ::mlir::TypeID::get<MyDialect>()) {

    initialize();
  }
```

This is annoying because it forces types to be complete and prevents use of unique pointer.  One example of this is when [implementing fallback interfaces](https://github.com/tensorflow/tensorflow/blob/494c7507982e935d2c68a6ced08d6dc11fc8634c/tensorflow/core/ir/dialect.td#L121) where you want to keep the class in the .cpp file, and not put it into the header.  This example should use a unique pointer, but you can't do that because the header-exposed ctor requires the T type to be complete.

**Comment by River707** [comment]
I was literally looking into this recently, will have a patch up today.

**Comment by lattner** [comment]
oh nice, thank you!

**Comment by River707** [comment]
Sent out https://reviews.llvm.org/D124297 to fix this. Also sent out a nice follow-on cleanup that this enabled (and also my original motivation for this): https://reviews.llvm.org/D124298
