### ISSUE TITLE
Compiling libclang without compiling clang

### ISSUE THREAD

**Issue by jcelerier** [llvm/llvm-project#55043]
Hello,
I have a project which uses libclang but not the clang executable (or any llvm executable).

- If I pass `-DLLVM_ENABLE_PROJECTS="clang" -DLLVM_INCLUDE_TOOLS=1  -DLLVM_BUILD_TOOLS=1 ` to CMake, I get libLLVM<everything>.a, libClang<everything>.a and also a ton of binaries that I don't need but waste 1.7 gigabyte of disk space in my install folder's `bin/`

- If I pass `-DLLVM_ENABLE_PROJECTS="clang" -DLLVM_INCLUDE_TOOLS=0  -DLLVM_BUILD_TOOLS=0` instead, then I don't get any tools built (good!) but I also don't get any of the libClang libraries :( it seems that in this case the clang project gets entirely disabled.

How can I get the libClang<...>.a without having a build with all the clang binaries ? I cannot remove them afterwards because they are referenced in the llvm's Targets.cmake generated file which my project uses to link against LLVM, and if any file that was installed is missing, it causes a hard CMake error.

    LLVM_TOOL_CLANG_BUILD 

is set to true in my CMakeCache.txt

**Comment by tstellar** [comment]
There should be a build target specifically for the libclang library that you can pass to ninja.  ninja help lists all the build targets.

**Comment by MaskRay** [comment]
libclang typically refers to the shared object `libclang.so`.

To build just `libclang*.a`, use
```sh
ninja $(ninja -t targets | awk '/libclang[A-Z]/{print substr($1, 1, length($1)-1)}')
```

**Comment by jcelerier** [comment]
@MaskRay this does not work: when I run `ninja install` afterwards (I need to install the toolchain) it builds and installs everything

**Comment by jcelerier** [comment]
@MaskRay @tstellar can you reopen ? the issue is not fixed at all

**Comment by jcelerier** [comment]
bump

**Comment by tstellar** [comment]
@jcelerier Try `ninja install-libclang`

**Comment by jcelerier** [comment]
this only installs libclang.so, not the .a, the libclang headers, the CMake export files, etc

**Comment by jcelerier** [comment]
and i'd be very surprised if it worked: the generated cmake export files (by a full make install, of which I assume install-$target is a strict subset) have references to the clang & friend binaries generated: if they are missing then the app which does find_package(LLVM) in its CMake will fail

**Comment by jcelerier** [comment]
e.g. in lib/cmake/clang/ClangTargets-debug.cmake

```cmake
# Import target "clang" for configuration "Debug"
set_property(TARGET clang APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(clang PROPERTIES
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bin/clang-14"
  )

list(APPEND _IMPORT_CHECK_TARGETS clang )
list(APPEND _IMPORT_CHECK_FILES_FOR_clang "${_IMPORT_PREFIX}/bin/clang-14" )

# Import target "clang-format" for configuration "Debug"
set_property(TARGET clang-format APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(clang-format PROPERTIES
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bin/clang-format"
  )

list(APPEND _IMPORT_CHECK_TARGETS clang-format )
list(APPEND _IMPORT_CHECK_FILES_FOR_clang-format "${_IMPORT_PREFIX}/bin/clang-format" )
```

etc etc... for every built binary - if any is missing then find_package will fail
