### ISSUE TITLE
AArch64: SVE: LLVM ERROR: Error while trying to spill X22 from class GPR64: Cannot scavenge register without an emergency spill slot!

### ISSUE THREAD

**Issue by rscottmanley** [llvm/llvm-project#55041]
llc is getting abort in the Register Scavenger when using `-aarch64-sve-vector-bits-min=256` and the `-mcpu=neoverse-v1` target. It seems to be okay on a64fx and `-aarch64-sve-vector-bits-min=512`.

bugpoint reduced testcase here: https://godbolt.org/z/Er19PW8M1

cc @mcinally @paulwalker-arm

**Comment by rscottmanley** [comment]
Also fine without ` -aarch64-sve-vector-bits-min=256`

**Comment by peterwaller-arm** [comment]
Bisects to 86972f111497bd15df8da181d0d7ac68b866320b -- ping @brads55

**Comment by brads55** [comment]
Review to fix this issue at https://reviews.llvm.org/D124457
