### ISSUE TITLE
Clang hits assertion when using virual consteval functions: VTableBuilder.cpp:2281 `I != MethodVTableIndices.end() && "Did not find index!"' failed.`

### ISSUE THREAD

**Issue by ArXen42** [llvm/llvm-project#55065]
### How to reproduce

```c++
struct Base
{
	consteval virtual int Get() const = 0;
};

struct Derived : Base
{
	consteval int Get() const override
	{
		return 42;
	}
};

int main()
{
	constexpr Derived a;

	auto val = a.Get();
	return 0;
}
```

Compiler explorer link (clang-14, -std=c++20, no optimizations or other options):
https://godbolt.org/z/vhqGqvf1z

Replacing 'consteval' with 'constexpr', moving `a` creation out of the function scope or removing inheritance seems to fix this compiler crash.

Attached cpp/sh crash reproduction files from my local compiler (clang 13.0.1-2 from Arch Linux repos):
[main-fee9e9..zip](https://github.com/llvm/llvm-project/files/8550155/main-fee9e9.zip)

**Comment by fhahn** [comment]
Also crashes with current `main`: https://godbolt.org/z/7n78vf46T

**Comment by nicolas17** [comment]
The assertion happens while generating debug info, so -g is required to reproduce (in godbolt, -g is the default, and -g0 makes it not assert).

Bisect pointed me at 51e4aa87e05c45bebf9658a47980b1934c88be31, which is a re-land of 3bab88b7baa20b276faaee0aa7ca87f636c91877 which also causes the assert.

**Comment by ilya-biryukov** [comment]
Claiming this for @luken-google, who has no commit access yet.

**Comment by luken-google** [comment]
Patch out for review at https://reviews.llvm.org/D132874
