### ISSUE TITLE
Missing space between consecutive right angle brackets

### ISSUE THREAD

**Issue by tambry** [llvm/llvm-project#55064]
After 907ed12d950f8e138620769420e5f84c0c7ece78 compilations using the unstable ABI and including `<bitset>` fail in C++98 and C++03 mode.  
Discovered by [my CMake CI bot](https://open.cdash.org/viewTest.php?buildid=7871843&onlyfailed). [Example failure](https://open.cdash.org/test/677320429).

I know that libc++ implements C++11 and above, but I'm not actually sure from the documentation if support for compiling in an older standard mode is an aim. It seems to have been working so far though.

Cc @philnik777.

**Comment by philnik777** [comment]
AFAIK we support the unstable ABI only with C++11 and beyond but I currently can't find any mention of this. @ldionne Do we actually have an official policy on this, or am I misremembering something?

**Comment by philnik777** [comment]
Fixed by 6b257af82261a526b79c0e65c8eed073e916e711.
