### ISSUE TITLE
Raise default C++ version to C++17?

### ISSUE THREAD

**Issue by davidben** [llvm/llvm-project#55077]
Looks like GCC 11 defaulted to C++17 a couple years ago:
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=0801f419440c14f6772b28f763ad7d40f7f7a580

Is it time to match in Clang?
https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/LangStandards.cpp#L79

**Comment by nikic** [comment]
@keith I believe the request here is for changing the default in clang, not the requirement for the compiler used to build clang.

**Comment by dwblaikie** [comment]
FWIW, here are the tests that failed for me when I tried changing the LangStandards.cpp#L79 line:
```
  Clang :: AST/ast-dump-openmp-begin-declare-variant_11.c
  Clang :: AST/ast-dump-openmp-begin-declare-variant_template_3.cpp
  Clang :: AST/ast-dump-undeduced-expr.cpp
  Clang :: AST/sourceranges.cpp
  Clang :: Analysis/blocks.m
  Clang :: Analysis/exploded-graph-rewriter/objects_under_construction.cpp
  Clang :: CXX/basic/basic.stc/basic.stc.dynamic/p2.cpp
  Clang :: CXX/class.access/class.friend/p1.cpp
  Clang :: CXX/dcl.dcl/dcl.spec/dcl.stc/p2.cpp
  Clang :: CXX/except/except.spec/p2-dynamic-types.cpp
  Clang :: CXX/except/except.spec/p9-dynamic.cpp
  Clang :: CXX/stmt.stmt/stmt.select/p3.cpp
  Clang :: CXX/temp/temp.arg/temp.arg.nontype/p1.cpp
  Clang :: CXX/temp/temp.res/temp.local/p3.cpp
  Clang :: CodeGen/typedef_alignment_mismatch_warning.cpp
  Clang :: CodeGenCXX/align-avx-complete-objects.cpp
  Clang :: CodeGenCXX/copy-constructor-elim-2.cpp
  Clang :: CodeGenCXX/debug-info-template-parameter.cpp
  Clang :: CodeGenCXX/debug-info-template-partial-specialization.cpp
  Clang :: CodeGenCXX/exception-spec-decay.cpp
  Clang :: CodeGenCXX/exceptions-cxx-ehsc.cpp
  Clang :: CodeGenCXX/exceptions-no-rtti.cpp
  Clang :: CodeGenCXX/global-init.cpp
  Clang :: CodeGenCXX/no-exceptions.cpp
  Clang :: CodeGenCXX/override-bit-field-layout.cpp
  Clang :: CodeGenCXX/override-layout.cpp
  Clang :: CodeGenCXX/reference-temporary-ms.cpp
  Clang :: CodeGenCXX/rtti-linkage.cpp
  Clang :: Layout/ms-x86-vtordisp.cpp
  Clang :: Modules/update-exception-spec.cpp
  Clang :: OpenMP/declare_mapper_messages.cpp
  Clang :: PCH/cxx-functions.cpp
  Clang :: Parser/cxx-casting.cpp
  Clang :: Parser/cxx-class.cpp
  Clang :: Parser/cxx-template-argument.cpp
  Clang :: Parser/cxx-template-decl.cpp
  Clang :: Parser/cxx1z-nested-namespace-definition.cpp
  Clang :: Sema/ms_class_layout.cpp
  Clang :: SemaCXX/MicrosoftExtensions.cpp
  Clang :: SemaCXX/PR12778.cpp
  Clang :: SemaCXX/altivec.cpp
  Clang :: SemaCXX/bool.cpp
  Clang :: SemaCXX/default2.cpp
  Clang :: SemaCXX/exception-spec-no-exceptions.cpp
  Clang :: SemaCXX/exceptions.cpp
  Clang :: SemaCXX/expressions.cpp
  Clang :: SemaCXX/inline.cpp
  Clang :: SemaCXX/libstdcxx_is_pod_hack.cpp
  Clang :: SemaCXX/linkage2.cpp
  Clang :: SemaCXX/member-pointer.cpp
  Clang :: SemaCXX/missing-namespace-qualifier-typo-corrections.cpp
  Clang :: SemaCXX/new-delete.cpp
  Clang :: SemaCXX/static-data-member.cpp
  Clang :: SemaCXX/type-definition-in-specifier.cpp
  Clang :: SemaCXX/user-defined-conversions.cpp
  Clang :: SemaCXX/warn-new-overaligned-3.cpp
  Clang :: SemaCXX/warn-new-overaligned.cpp
  Clang :: SemaCXX/writable-strings-deprecated.cpp
  Clang :: SemaSYCL/zero-length-arrays.cpp
  Clang :: SemaTemplate/class-template-id.cpp
  Clang :: SemaTemplate/constructor-template.cpp
  Clang :: SemaTemplate/explicit-instantiation.cpp
  Clang :: SemaTemplate/instantiate-exception-spec.cpp
  Clang :: SemaTemplate/instantiation-default-2.cpp
  Clang :: SemaTemplate/temp_arg.cpp
  Clang :: SemaTemplate/temp_arg_template.cpp
  Clang :: SemaTemplate/typename-specifier-3.cpp
  Clang-Unit :: AST/./ASTTests/Traverse/IgnoreUnlessSpelledInSourceReturns
  Clang-Unit :: AST/./ASTTests/Traverse/IgnoreUnlessSpelledInSourceVars
  ```
  
  (to give someone else a sense of what sort of cleanup might be required - decided I'm not going to work on that cleanup right away, but was curious about how big it might be)

**Comment by junaire** [comment]
> FWIW, here are the tests that failed for me when I tried changing the LangStandards.cpp#L79 line:
> ```
>   Clang :: AST/ast-dump-openmp-begin-declare-variant_11.c
>   Clang :: AST/ast-dump-openmp-begin-declare-variant_template_3.cpp
>   Clang :: AST/ast-dump-undeduced-expr.cpp
>   Clang :: AST/sourceranges.cpp
>   Clang :: Analysis/blocks.m
>   Clang :: Analysis/exploded-graph-rewriter/objects_under_construction.cpp
>   Clang :: CXX/basic/basic.stc/basic.stc.dynamic/p2.cpp
>   Clang :: CXX/class.access/class.friend/p1.cpp
>   Clang :: CXX/dcl.dcl/dcl.spec/dcl.stc/p2.cpp
>   Clang :: CXX/except/except.spec/p2-dynamic-types.cpp
>   Clang :: CXX/except/except.spec/p9-dynamic.cpp
>   Clang :: CXX/stmt.stmt/stmt.select/p3.cpp
>   Clang :: CXX/temp/temp.arg/temp.arg.nontype/p1.cpp
>   Clang :: CXX/temp/temp.res/temp.local/p3.cpp
>   Clang :: CodeGen/typedef_alignment_mismatch_warning.cpp
>   Clang :: CodeGenCXX/align-avx-complete-objects.cpp
>   Clang :: CodeGenCXX/copy-constructor-elim-2.cpp
>   Clang :: CodeGenCXX/debug-info-template-parameter.cpp
>   Clang :: CodeGenCXX/debug-info-template-partial-specialization.cpp
>   Clang :: CodeGenCXX/exception-spec-decay.cpp
>   Clang :: CodeGenCXX/exceptions-cxx-ehsc.cpp
>   Clang :: CodeGenCXX/exceptions-no-rtti.cpp
>   Clang :: CodeGenCXX/global-init.cpp
>   Clang :: CodeGenCXX/no-exceptions.cpp
>   Clang :: CodeGenCXX/override-bit-field-layout.cpp
>   Clang :: CodeGenCXX/override-layout.cpp
>   Clang :: CodeGenCXX/reference-temporary-ms.cpp
>   Clang :: CodeGenCXX/rtti-linkage.cpp
>   Clang :: Layout/ms-x86-vtordisp.cpp
>   Clang :: Modules/update-exception-spec.cpp
>   Clang :: OpenMP/declare_mapper_messages.cpp
>   Clang :: PCH/cxx-functions.cpp
>   Clang :: Parser/cxx-casting.cpp
>   Clang :: Parser/cxx-class.cpp
>   Clang :: Parser/cxx-template-argument.cpp
>   Clang :: Parser/cxx-template-decl.cpp
>   Clang :: Parser/cxx1z-nested-namespace-definition.cpp
>   Clang :: Sema/ms_class_layout.cpp
>   Clang :: SemaCXX/MicrosoftExtensions.cpp
>   Clang :: SemaCXX/PR12778.cpp
>   Clang :: SemaCXX/altivec.cpp
>   Clang :: SemaCXX/bool.cpp
>   Clang :: SemaCXX/default2.cpp
>   Clang :: SemaCXX/exception-spec-no-exceptions.cpp
>   Clang :: SemaCXX/exceptions.cpp
>   Clang :: SemaCXX/expressions.cpp
>   Clang :: SemaCXX/inline.cpp
>   Clang :: SemaCXX/libstdcxx_is_pod_hack.cpp
>   Clang :: SemaCXX/linkage2.cpp
>   Clang :: SemaCXX/member-pointer.cpp
>   Clang :: SemaCXX/missing-namespace-qualifier-typo-corrections.cpp
>   Clang :: SemaCXX/new-delete.cpp
>   Clang :: SemaCXX/static-data-member.cpp
>   Clang :: SemaCXX/type-definition-in-specifier.cpp
>   Clang :: SemaCXX/user-defined-conversions.cpp
>   Clang :: SemaCXX/warn-new-overaligned-3.cpp
>   Clang :: SemaCXX/warn-new-overaligned.cpp
>   Clang :: SemaCXX/writable-strings-deprecated.cpp
>   Clang :: SemaSYCL/zero-length-arrays.cpp
>   Clang :: SemaTemplate/class-template-id.cpp
>   Clang :: SemaTemplate/constructor-template.cpp
>   Clang :: SemaTemplate/explicit-instantiation.cpp
>   Clang :: SemaTemplate/instantiate-exception-spec.cpp
>   Clang :: SemaTemplate/instantiation-default-2.cpp
>   Clang :: SemaTemplate/temp_arg.cpp
>   Clang :: SemaTemplate/temp_arg_template.cpp
>   Clang :: SemaTemplate/typename-specifier-3.cpp
>   Clang-Unit :: AST/./ASTTests/Traverse/IgnoreUnlessSpelledInSourceReturns
>   Clang-Unit :: AST/./ASTTests/Traverse/IgnoreUnlessSpelledInSourceVars
>   ```
>   
>   (to give someone else a sense of what sort of cleanup might be required - decided I'm not going to work on that cleanup right away, but was curious about how big it might be)

I just took a look and I think it should be easy to fix these failures. All we need to do is changing the old `RUN` lines, to tell it use `-std=c++14` or `-std=gnu++14` explicitly.

I would like to do the cleaning up work but I wonder what will happen if we bump the default standard in the future again? Maybe we should tell the driver use which standard explicitly when writing regression tests other time to avoid breaks like this.

**Comment by junaire** [comment]
I've put up https://reviews.llvm.org/D124434

**Comment by davidben** [comment]
Looks like this was done in https://reviews.llvm.org/rGe321c8dd2cea8365045ed44ae1c3c00c6a977d2e (thanks, @MaskRay!). Is there anything else left to be done, or should this bug be closed?
