### ISSUE TITLE
init_priority loses static initializer optimization

### ISSUE THREAD

**Issue by davidben** [llvm/llvm-project#55083]
Clang is able to optimize out some static initializers. However, when some variable in the TU uses the `init_priority` attribute, Clang no longer elides the static initializer, for both it and other variables.

```cpp
// Set this to 1 and *both* foo and bar get their initializers back.
#define USE_INIT_PRIORITY 0

struct NotConstExprButOptimizable {
    explicit NotConstExprButOptimizable(int x) : x_(x) {}
    int x_;
};

NotConstExprButOptimizable foo(5);

#if USE_INIT_PRIORITY
__attribute__((init_priority(101)))
#endif
NotConstExprButOptimizable bar(5);
```
https://godbolt.org/z/hP9rPoqjb

I'm not sure exactly what the semantics are here, but if clang has managed to provide an initializer is elidable, seems to me that should apply independent of init_priority. protobuf seems to use init_priority to control cross-TU ordering, but in cases where the constructor is elidable, that be even more preferable.

**Comment by alexander-shaposhnikov** [comment]
I'm planning to address this issue ~soon.
