### ISSUE TITLE
check-all does not run check-openmp

### ISSUE THREAD

**Issue by jdenny-ornl** [llvm/llvm-project#55082]
Due to [D121276](https://reviews.llvm.org/D121276), check-all does not run check-openmp.  There was some discussion there about this problem.  [D121647](https://reviews.llvm.org/D121647) attempted to fix it, but what landed didn't fix it.

**Comment by shiltian** [comment]
@jdenny-ornl is it still an issue?

**Comment by jdenny-ornl** [comment]
@shiltian Sorry I missed your question until now.  Yes, this appears to have been fixed at least since October.
