### ISSUE TITLE
Enhance readability-simplify-boolean-expr to apply DeMorgan's Theorem

### ISSUE THREAD

**Issue by LegalizeAdulthood** [llvm/llvm-project#55092]
The reasoning here is that fewer operands and parentheses make for easier reading.

- Simplify `!(!a || !b)` to `a && b`
- Simplify `!(!a || b)` to `a && !b`
- Simplify `!(a || !b)` to `!a && b`
- Simplify `!(!a && !b)` to `a || b`
- Simplify `!(!a && b)` to `a || !b`
- Simplify `!(a && !b)` to `!a || b`

**Comment by njames93** [comment]
I'm going to assume these won't break short-circuit rules.

**Comment by LegalizeAdulthood** [comment]
> I'm going to assume these won't break short-circuit rules.

Let's look at all the cases:

1. Simplify `!(!a || !b)` to `a && b`:
   - short circuit rule for `||` says that `!b` is not evaluated if `!a` is `true`.
   - `!a` is `true` if `a` is `false`.
   - If `a` is `false`, then `a && b` would be `false`
   - short circuit rule for `&&` says that `b` is not evaluated if `a` is `false`
2. Simplify `!(!a || b)` to `a && !b`
   - short circuit rule for `||` says that `!b` is not evaluated if `!a` is `true`.
   - `!a` is `true` if `a` is `false`.
   - If `a` is `false`, then `a && !b` would be `false`
   - short circuit rule for `&&` says that `!b` is not evaluated if `a` is `false`
3. Simplify `!(a || !b)` to `!a && b`:
   - short circuit rule for `||` says that `!b` is not evaluated if `a` is `true`.
   - `!a` is `false` if `a` is `true`
   - If `!a` is `false`, then `!a && b` is `false`
   - short circuit rule for `&&` says that `b` is not evaluated if `!a` is `false`
4. Simplify `!(!a && !b)` to `a || b`
   - short circuit rule for `&&` says that `!b` is not evaluated if `!a` is `false`
   - `!a` is `false` if `a` is `true`
   - If `a` is `true`, then `a || b` is `true`
   - short circuit rule for `||` says that `b` is not evaluated if `a` is `true`
5. Simplify `!(!a && b)` to `a || !b`
   - short circuit rule for `&&` says that `b` is not evaluated if `!a` is `false`
   - `!a` is `false` if `a` is `true`
   - If `a` is `true`, then `a || !b` is `true`
   - short circuit rule for `||` says that `!b` is not evaluated if `a` is `true`
6. Simplify `!(a && !b)` to `!a || b`
   - short circuit rule for `&&` says that `!b` is not evaluated if `a` is `false`
   - if `a` is `false`, then `!a || b` is `true`
   - short circuit rule for `||` says that `b` is not evaluated if `!a` is `true`

**Comment by LegalizeAdulthood** [comment]
https://reviews.llvm.org/D124650
