### ISSUE TITLE
Wrong behavior of PointerIntPair due to strict aliasing violation

### ISSUE THREAD

**Issue by brenoguim** [llvm/llvm-project#55103]
For some interfaces like "copy constructor", the PointerIntPair uses the underlying storage as it's declared: `intptr_t`.
However in other interfaces, like `getAddrOfPointer`, it `reinterpret_cast`s the storage into an actual pointer: `PtrType`.

This is a strict aliasing violation and can cause wrong code generation if the compiler decides to optimize based on this information:
https://godbolt.org/z/ah8zcce1T

In the example above the compiler generate the wrong code (abort is invoked). Any small tweak to the code can make it pass.

**Comment by brenoguim** [comment]
Also, one can add `-fno-strict-aliasing` to see that it starts passing.

**Comment by brenoguim** [comment]
Reduced the example even further: https://godbolt.org/z/eYPqKPx9n

**Comment by brenoguim** [comment]
By the way, I found about this issue because I faced a similar thing in another codebase, and came to see how PointerIntPair was implemented.
In the other codebase we solved the issue by using `std::launder` when accessing both the `intptr_t` representation and the `PtrType` representation. I'm not entirely sure if that is the true fix though.

You can see it working in llvm::PointerIntPair here https://godbolt.org/z/rTbef3rrM
Look for the marks ENABLE_FIX

**Comment by brenoguim** [comment]
This would be another solution that works both in clang/gcc but it's hard to tell if I'm really fixing or just tricking the compiler enough to hide the bug: https://godbolt.org/z/79eGKGnvr
Here I introduce `IntThatIsAlso<T>` class to replace `intptr_t Value` and use memcpy to write to the underlying buffer and use `launder` when casting to `T`

**Comment by brenoguim** [comment]
I'll submit a patch

**Comment by brenoguim** [comment]
https://reviews.llvm.org/D124571

**Comment by johnmcfarlane** [comment]
Friendly reminder that there is a Clang-Tidy check, cppcoreguidelines-pro-type-reinterpret-cast, for catching these bugs.

**Comment by brenoguim** [comment]
Resolved with: https://github.com/llvm/llvm-project/commit/875391728c11339c8a6cd3338bcaa5ec0ffc2496
