### ISSUE TITLE
DXIL Writer support for opaque pointers in globals

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#55110]
The DXIL Writer needs to support opaque pointer types in Globals. This will require extending both the pointer type analysis and the DXIL writer as appropriate.

**Comment by python3kgae** [comment]
[D133283 [DirectX backend] Support global ctor for DXILBitcodeWriter. (llvm.org)](https://reviews.llvm.org/D133283)

**Comment by llvm-beanz** [comment]
Merged in a80a888de5b1a96c64ed308dc858cb1820108178
