### ISSUE TITLE
Uninitialized field read is accepted in constant evaluation

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#55112]
In this program:
```
#include <memory>
#include <iostream>

struct A {
    int x = x;
};

constexpr int foo()
{
    A a{1};
    std::construct_at<A>(&a);
    return a.x;
}

constexpr int v = foo();

int main() {
    std::cout << v;
}
```
Clang issues 
```
warning: field 'x' is uninitialized when used here [-Wuninitialized]
    int x = x;
```
but still accepts the program, which prints `0`. But I think the program with uninitialized field read in constant evaluation must be rejected.

Or it shall print `1` as GCC does. Demo: https://gcc.godbolt.org/z/8Ejz9YK86

**Comment by efriedma-quic** [comment]
Do you have any particular reason to believe gcc is correct?  If I remove the "constexpr" marking from the function, both clang and gcc agree it returns zero.

(I think the way std::construct_at is defined, it zero-initializes the memory before it runs the constructor.)

**Comment by Fedr** [comment]
Probably GCC is wrong here. But if Clang can detect the read of uninitialized value, why it does not fail the constant evaluation (and only prints a warning)?

**Comment by Fedr** [comment]
In a similar example:
```
#include <memory>
#include <iostream>

struct A {
    int x;
    constexpr A() {}
    constexpr A(int xx) : x(xx) {}
};

constexpr int foo() { 
    A a{1};
    std::construct_at<A>(&a);
    return a.x; 
}
constexpr int v = foo();

int main() {
    std::cout << v;
}
```
Clang prints the error `read of uninitialized object is not allowed in a constant expression`. Demo: https://gcc.godbolt.org/z/d5nKvx1zT

If `std::construct_at` zero-initializes `a.x`, then it shall not be so?

**Comment by Fedr** [comment]
Thanks for the explanation!

**Comment by shafik** [comment]
So `construct_at` is defined in terms of placement new see [\
[specialized.construct\](https://timsong-cpp.github.io/cppwp/specialized.construct):

> Effects: Equivalent to: return ::new (voidify(*location)) T(std::forward<Args>(args)...);

It looks like implementations zero out memory when using placement new but this is not required by the standard, as far as I can tell.

**Comment by efriedma-quic** [comment]
> It looks like implementations zero out memory when using placement new but this is not required by the standard, as far as I can tell.

If no arguments are passed to construct_at, we have a `()` initializer, so we follow the rules at https://timsong-cpp.github.io/cppwp/dcl.init#general-16.4 , which refers to https://timsong-cpp.github.io/cppwp/dcl.init#general-9.1 , which zeros out the memory.
