### ISSUE TITLE
HLSL cbuffer & tbuffer support

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#55118]
In HLSL the cbuffer and tbuffer keywords denote constant and texture buffer formats.

As a developer I would like to use the cbuffer and tbuffer in LLVM.

Dependent on:  Resource work

AC:
buffer-type codegen is implemented

cbuffer is implemented 
cbuffer tests are implemented
cbuffer tests are integrated in CI pipeline

tbuffer is implemented
tbuffer tests are implemented
tbuffer tests are integrated in CI pipeline

**Comment by python3kgae** [comment]
0. Enable PCH support to test AST node added for buffer.
  https://reviews.llvm.org/D132421
  

1. Add cbuffer AST node.
https://reviews.llvm.org/D129883
   Updated, need review again.

2. D130033 [HLSL] Add resource binding attribute for HLSL.
https://reviews.llvm.org/D130033
    Approved

3. D130131 [HLSL] CodeGen hlsl cbuffer/tbuffer.
https://reviews.llvm.org/D130131
    Need change. Might be affected by 1. Will update once 1 is in.

4. D130951 [HLSL] CodeGen hlsl resource binding.
  https://reviews.llvm.org/D130951
    Need review

5. D131370 [DirectX backend] Translate cbuffer into DXIL.
https://reviews.llvm.org/D131370 
    Might be affected by 3. Will update once 3 is in.

6. legacy cbuffer layout support
https://reviews.llvm.org/D132986
   Need review.

**Comment by python3kgae** [comment]
Got different ideas to implement. I need to update the code.

**Comment by bogner** [comment]
The remaining work here should be captured by DXIL resource lowering in general and the following tasks: https://github.com/llvm/llvm-project/issues/75828, https://github.com/llvm/llvm-project/issues/75829, https://github.com/llvm/llvm-project/issues/75830, https://github.com/llvm/llvm-project/issues/75833
