### ISSUE TITLE
clang-format 13: Additional space in indentation depending on context

### ISSUE THREAD

**Issue by svenihoney** [llvm/llvm-project#55113]
.clang-format: https://termbin.com/9zqm2 (lengthy, I know, but no time to strip down, sorry)...

I have an issue which is introduced with clang-13. I have a code snippet like this:

```c
void VersionLogic::versionsRequested()
{
    QString versionNSDB = localVersions()->property("nsdb_version").toString();
    QString releaseTag  = localVersions()->property("git_tag").toString();
    QString versionCfg  = QStringLiteral("%1%2").arg(
        localVersions()->property("conf_deuta_sw_no").toString(),
        localVersions()->property("conf_deuta_sw_idx").toString());
}
```

If I use clang-format version 13, the localVersions()-> lines are indented 5 spaces instead of 4. With version 12 it is the expected 4 spaces.

* If I remove any of the first two QString lines or comment it out, the indentation is at 4 spaces as expected.
* If I add an empty line after the first two QString lines, the indentation is correct as well.

**Comment by dtrodrigues** [comment]
The behavior changed in https://github.com/llvm/llvm-project/commit/c5243c63cda3c740d6e9c7e501f6518c21688da3.

**Comment by owenca** [comment]
https://reviews.llvm.org/D124868
