### ISSUE TITLE
[clang-tidy] NOLINT not working in macros in clang-tidy-14 (regression)

### ISSUE THREAD

**Issue by paulaltin** [llvm/llvm-project#55134]
Clang-tidy version 13 generates no warnings for this code:

```c
#define CREATE_STRUCT(name)    \
struct name {	/* NOLINT */   \
    int a = 0;                 \
    int b;                     \
}; 				

CREATE_STRUCT(X)
CREATE_STRUCT(Y)
CREATE_STRUCT(Z)
```

when invoked as:

```shell
clang-tidy-13 test.cpp -checks=cppcoreguidelines-pro-type-member-init
```

Clang-tidy version 14 generates warnings on lines 7-9 when invoked the same way.

**Comment by paulaltin** [comment]
It appears from the summary of this patch that the intention is for "clang-tidy [to] look at the line of macro invocation and every line of macro definition for a NOLINT comment."

https://reviews.llvm.org/D24845

**Comment by paulaltin** [comment]
If anyone knows of a workaround for this (short of marking every use of the macro with `NOLINT`), I would be very grateful. Adding NOLINT to every line that uses the macro isn't possible in my case, but I can modify the macro definition.

**Comment by firewave** [comment]
I encountered a similar issue with `NOLINTNEXTLINE` quite a while ago - see #46511.

**Comment by Skylion007** [comment]
I am encountering similar issues with google-explicit-constructor when trying to update clang-tidy to 14 for pybind11: https://github.com/pybind/pybind11/blob/2e331308d38a521c087e7fc0cfee227cd29f3f71/include/pybind11/pytypes.h#L1029 . NOLINTS are ignored. Interestingly, the 'bugprone-macro-*' NOLINT comments seem to work fine. Even NOLINTBEGIN NOLINTEND do not work when used in the multiline macro.

**Comment by Skylion007** [comment]
@paulaltin This implies the issue is not specific to this check, feel free to update the title.

**Comment by paulaltin** [comment]
Checks known to have regressed in version 14:
- cppcoreguidelines-pro-type-member-init
- google-explicit-constructor

Checks that were not working before version 14:
- modernize-avoid-c-arrays

**Comment by Skylion007** [comment]
@paulaltin I have the 'google-explicit ctor' seems to have actually regressed in version 13 as well. The breakage point appears to be sometime after version 12.

**Comment by paulaltin** [comment]
Thanks @Skylion007 – I've updated the comment above.

**Comment by Skylion007** [comment]
I don't have that much experience in the clang-tidy code base, but trying to look around the codebase, I am bit suspicious of this commit: https://github.com/llvm/llvm-project/commit/b9d9968f63ab8f24b300c69be11eadda3d405ac5, but I don't see anything obvious that changed in these checks that could have broken them between 12-13 and 13-14.

I also noticed a lot of the other checks that are working have preprocessor callbacks.

I am really not familiar with the codebase though so I am bit unsure where the regression is coming. Any thoughts @EugeneZelenko ?

**Comment by paulaltin** [comment]
Looks like that commit was authored by @HighCommander4, perhaps they can help?

**Comment by HighCommander4** [comment]
Stepping through the code suggests that [this loop](https://searchfox.org/llvm/rev/77480556c41fbca36b918323c69cb77f8e02b56c/clang-tools-extra/clang-tidy/NoLintDirectiveHandler.cpp#263) iterates twice, and checks the line `CHECK_STRUCT(X)` for a NOLINT comment both times, when the intention is clearly to check the `CHECK_STRUCT(X)` line in one iteration, and the (expanded) `struct X {	/* NOLINT */` line on the other.

**Comment by HighCommander4** [comment]
Looks to be a regression from https://github.com/llvm/llvm-project/commit/5da7c040030c4af72dcc21220f579098469c554e, cc @salman-javed-nz

**Comment by salman-javed-nz** [comment]
Thanks for the discovery. I'll see what I can do to fix this. 

From a brief initial look, it looks like @HighCommander4 is right on the money with the line of code he has isolated this issue to. 

There's a number of `lit` test cases regarding macro expansion so it's interesting that they didn't pick this up. Will have to update the tests to cover this regression. Please continue sharing any other code samples that exhibit this issue. They will help me make sure that the fix works for everyone.

**Comment by paulaltin** [comment]
Thanks @HighCommander4 and @salman-javed-nz, really appreciate your quick responses and attention to this!
