### ISSUE TITLE
14.0.2: `lit` module version has not been updated

### ISSUE THREAD

**Issue by kloczek** [llvm/llvm-project#55137]
https://github.com/llvm/llvm-project/blob/0e27d08cdeb338766a477fba071b3df7a06ea6e2/llvm/utils/lit/lit/__init__.py#L5-L6
Also it woud be good to drop that `dev` suffix in stable release.

**Comment by DoDoENT** [comment]
`clang` also reports version `14.0.1` (I've just built it from source)...

**Comment by kloczek** [comment]
Probably it would be good to take all those places under kind hood of release script which will be injecting all proper values across whole tree before final commit and than tag 😄

**Comment by DoDoENT** [comment]
At least everything is link-compatible with binaries produced by the real `14.0.1` version, even when using libc++ with unstable ABI (we are utilizing the reported version to inform Conan about binary compatibility so it can decide whether dependencies need to be rebuilt or not).

**Comment by tstellar** [comment]
We can't go back and fix this, unfortunately, but here is a patch to prevent the problem in the future: https://reviews.llvm.org/D124539

**Comment by zufuliu** [comment]
Inside https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.2/LLVM-14.0.2-win64.exe
both `14.0.1` and `14.0.2` exists under `lib\clang\` folder, the former contains more headers but less folders.
```
D:.
├─14.0.1
│  └─include
│      ├─cuda_wrappers
│      ├─openmp_wrappers
│      └─ppc_wrappers
└─14.0.2
    ├─include
    │  ├─fuzzer
    │  ├─profile
    │  ├─sanitizer
    │  └─xray
    ├─lib
    │  └─windows
    └─share
```

**Comment by DoDoENT** [comment]
> We can't go back and fix this...

How about making a `14.0.3` release with a fix 😛 ?

**Comment by nickdesaulniers** [comment]
> How about making a 14.0.3 release with a fix 😛 ?

https://discourse.llvm.org/t/llvm-14-0-3-release/62133

**Comment by kloczek** [comment]
Thank you 😃

**Comment by tbaederr** [comment]
@tstellar I guess this can be closed?
