### ISSUE TITLE
Backport 3e6b904f0a5075a3f33683ce38b5a4fd18280e5e to the release/14.x branch

### ISSUE THREAD

**Issue by phoebewang** [llvm/llvm-project#55130]
Trunings for several GLC instructions. It's better to backport to LLVM14.

https://github.com/llvm/llvm-project/commit/3e6b904f0a5075a3f33683ce38b5a4fd18280e5e

**Comment by phoebewang** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/3e6b904f0a5075a3f33683ce38b5a4fd18280e5e

**Comment by phoebewang** [comment]
@tstellar The `/branch` command didn't work?

**Comment by tstellar** [comment]
@RKSimon What do you think about backporting this? https://github.com/llvm/llvm-project/commit/3e6b904f0a5075a3f33683ce38b5a4fd18280e5e

**Comment by phoebewang** [comment]
@RKSimon this is a fix for potential regression. Do you have concern for the backporting?

**Comment by RKSimon** [comment]
The patch is relatively clean and focussed on specific targets so backporting is very unlikely to introduce issues.

Are there specific regressions that this addresses? Yes, it appears to be a performance improvement but I'm not sure if anything already in 13.x or 14.x specifically reduced performance on AlderLake/SapphireRapids?

**Comment by tstellar** [comment]
@phoebewang There are test failures in the release/14.x branch with this change.  Also, this is a huge patch, what is the benefit of having this in the branch?

**Comment by phoebewang** [comment]
Hi @RKSimon and @tstellar, sorry for the late reply. This is to address a microarchitecture false dependency, which is listed in section 2.2.1.4 in Intel optimization reference manual. Although this is not strict software regression, there are still 2 aspects software related, especially in the releases. 1) The `-march=sapphirerapids` was introduced since LLVM 12. With this patch + `-march=sapphirerapids`, user can mitigate the performance regressions; 2) There’s performance impact on AVX512-FP16 instructions, which we enabled in LLVM 14 release. It is expected there will be more users with this release. So, it’s important to these users if we can solve the problem within the release.

**Comment by phoebewang** [comment]
> @phoebewang There are test failures in the release/14.x branch with this change.

Sorry, I didn't notice the failure report. It was caused by a NFC refactor https://github.com/llvm/llvm-project/commit/e58dadf3e2c160d0c405aafd807d8305c5a92c4a plus other minor problems. It is now passed on my local machine. I should have run the test locally at the beginning.

By the way, it seems I can't cherry-pick it again. Is it because we are bumping to 14.0.5? Do I need to add another milestone?

**Comment by RKSimon** [comment]
I'm not going to block this, but its up to @tstellar if he's willing to take a purely perf improvement this late in the 14.x branch

**Comment by tru** [comment]
IMHO - I'll say we wait for 15.x, since it's a performance regression and we are in the last 14.x release. If this one introduces any worse regression we don't have any more point releases to fix it in.

**Comment by phoebewang** [comment]
Thanks all for the evaluation. I agree it's late to the release process. Let's wait for 15.x :)
