### ISSUE TITLE
Error while installing llvm

### ISSUE THREAD

**Issue by Sofianebouaziz1** [llvm/llvm-project#55133]
hello i have been trying to build llvm from source (llvm 13 and lvm using the main branch). But the same error always occurs :
Here is a log : 
[log.txt](https://github.com/llvm/llvm-project/files/8570531/log.txt)

Please I really need an anserw since I am working on a project and I need it.

**Comment by Sofianebouaziz1** [comment]
Can anyone please help ?

**Comment by fhahn** [comment]
I assume this is the same issue as #55148? Please avoid filing multiple bugs for the same issue.  If I missed something and this is not a duplicate, please let me know.
