### ISSUE TITLE
clang-format removes newline after "private:"

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#55132]
Consider:

```console
$ cat /tmp/a.cc
#include <memory>

class A {
 public:
  std::unique_ptr<const char* []> b() {
    return nullptr;
  }

 private:
  int c_ = 0;
};

$ build.release/bin/clang-format -style="{BasedOnStyle: Chromium, Standard: c++17}" /tmp/a.cc
#include <memory>

class A {
 public:
  std::unique_ptr<const char* []> b() { return nullptr; }

  private : int c_ = 0;
};
```

Note the missing newline after `private:` and extra space before the colon. That seems like a bug.

(Originally from https://bugs.chromium.org/p/chromium/issues/detail?id=1320172)

**Comment by zmodem** [comment]
The style is not important, this reproduces also with `-style="{}"`.
I tried running revisions back to sometime in 2017, but always with the same result, so this doesn't look like a regression.

**Comment by mkurdej** [comment]
This bug is indeed present since at least release 3.7.

It seems to happen only with `[]` inside the return type.

E.g. this gets formatted ok:
```
class A {
  char * b() { return {}; }

private:
  int c_ = 0;
};
```
But not this:
```
class A {
  char *[] b() { return {}; }

  private : int c_ = 0;
};
```

**Comment by owenca** [comment]
https://reviews.llvm.org/D124589
