### ISSUE TITLE
Add JITLink support for a ELF/i386

### ISSUE THREAD

**Issue by jkshtj** [llvm/llvm-project#55146]
Creating this issue to track progress for adding JitLink support for ELF/i386.

Parent issue - https://discourse.llvm.org/t/write-jitlink-support-for-a-new-format-architecture/60322 (GSoc proposal originally)

**Comment by jain98** [comment]
@EugeneZelenko could you also assign the issue to me? Thanks!

**Comment by jkshtj** [comment]
We've added support for absolute, PC relative, GOT and PLT relocations for i386. One category of relocations that remain to be added are TLS relocations (there may be some other auxiliary relocations that might be missing as well).

**Comment by jkshtj** [comment]
Closing this issue for now, in favor of adding remaining relocations on demand.
