### ISSUE TITLE
[clang-format] Non-template deduction guides are misformatted

### ISSUE THREAD

**Issue by mkurdej** [llvm/llvm-project#55142]
Example adapted from https://en.cppreference.com/w/cpp/language/class_template_argument_deduction

Using LLVM style here.

Code:

```cpp
template <class T> struct S {
  S(T);
};
S(char const *) -> S<std::string>;

template <class T> S(T) -> S<T>;
```

Is formatted to:

```cpp
template <class T> struct S {
  S(T);
};
S(char const *)->S<std::string>;

template <class T> S(T) -> S<T>;
```

Mind the spaces removed around the arrow `->`.

Interestingly, a templated deduction guide is handled correctly.

I imagine that it's because clang-format isn't able to distinguish (at the point of parsing the arrow) whether it handles a deduction guide or `function_returning_pointer(args)->templated_member<T>;`.
In the case of deduction guides however, `function_returning_pointer` must be the same identifier as `templated_member` IIUC.

**Comment by JohelEGP** [comment]
> In the case of deduction guides however, `function_returning_pointer` must be the same identifier as `templated_member` IIUC.

That's right.

> The [template-name](https://eel.is/c++draft/temp.names#nt:template-name) shall be the same [identifier](https://eel.is/c++draft/lex.name#nt:identifier) as the [template-name](https://eel.is/c++draft/temp.names#nt:template-name) of the [simple-template-id](https://eel.is/c++draft/temp.names#nt:simple-template-id)[.](https://eel.is/c++draft/temp.deduct.guide#3.sentence-3)
> -- https://eel.is/c++draft/temp.deduct.guide#3.sentence-3

**Comment by rymiel** [comment]
Could the following be a deduction guide? This is within FormatTest.cpp, under "Ensure not deduction guide."

```cpp
x()->x<1>;
```

(Removing the check for templates causes that test to fail)

**Comment by rymiel** [comment]
Here's a patch which fixes this by just deletes existing code: <https://reviews.llvm.org/D139416>
