### ISSUE TITLE
[X86] getFauxShuffle ANDNP miscompilation 

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#55157]
Reported here: https://twitter.com/benjinsmith/status/1519274454798458886

```llvm
define <2 x i64> @_Z8do_stuffPKi(ptr %0) {
  %2 = load <16 x i8>, ptr %0, align 16
  %3 = icmp eq <16 x i8> %2, zeroinitializer
  %4 = tail call <16 x i8> @llvm.x86.sse2.pavg.b(<16 x i8> zeroinitializer, <16 x i8> zeroinitializer)
  %5 = select <16 x i1> %3, <16 x i8> <i8 poison, i8 poison, i8 poison, i8 poison, i8 poison, i8 poison, i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, <16 x i8> %4
  %6 = shufflevector <16 x i8> %5, <16 x i8> poison, <16 x i32> <i32 8, i32 8, i32 9, i32 9, i32 10, i32 10, i32 11, i32 11, i32 12, i32 12, i32 13, i32 13, i32 14, i32 14, i32 15, i32 15>
  %7 = bitcast <16 x i8> %6 to <2 x i64>
  ret <2 x i64> %7
}
declare <16 x i8> @llvm.x86.sse2.pavg.b(<16 x i8>, <16 x i8>)
```

GOOD: llc -mcpu=skx

```asm
do_stuff(int const*):                         # @do_stuff(int const*)
        vxorps  %xmm0, %xmm0, %xmm0
        retq
 ```

BAD: llc -mcpu=haswell

```asm
do_stuff(int const*):                         # @do_stuff(int const*)
        retq
```

I suspect this is a select combine issue but I haven't been able to confirm yet.

**Comment by RKSimon** [comment]
Found the problem - the select becomes a ANDN and we wrongly assume when treating that as a faux shuffle that an undef src element can be treated as an undef shuffle mask index (it can't as the other src element might be zero)

**Comment by RKSimon** [comment]
@Benjins Please can you confirm that ed8dffef4c37d831a0bcc713ab56f38d8d9612df fixes the miscompilations you tweeted about?

**Comment by Benjins** [comment]
Yes, I just pulled again from main and all my repro cases related to this have been resolved. Thanks for the quick fix.
I do apologise for not being prompt with filing an actual bug report: I was planning to do so once I had the chance to look into it further. I didn't mean for my tweet to be taken as a bug report before I had the chance to verify it wasn't an issue on my end
