### ISSUE TITLE
[aarch64] clang miscompilation of struct initializer in inline function (not properly zeroed)

### ISSUE THREAD

**Issue by rsms** [llvm/llvm-project#55151]
Initializing a struct with certain union fields inside an inlined function does not properly zero out non-named fields in the initializer.

Minimal repro case attached:
[clang-init-bug.c.zip](https://github.com/llvm/llvm-project/files/8576446/clang-init-bug.c.zip)

Here's a summary demonstration:

```c
typedef struct Attr {
  union { u8 a; u8 b[3]; }; u8 c[3];
} Attr;
typedef struct Foo {
  Attr a;
} Foo;
inline static Foo make_foo(Attr a) { return (Foo){a}; }
int fail() {
  Foo foo = make_foo( ((Attr){ .a = 7 }) );
  return foo.a.b[2] != 0; // bug: foo.a.b[2] is not zero initialized
}
int pass() {
  Foo foo = (Foo){ ((Attr){ .a = 7 }) };
  return foo.a.b[2] != 0;
}
```

Compiling this with `-std=c11`, the `fail` function which uses the `make_foo` helper will not fully initialize foo, while the `pass` function which "manually inlines" the same code from `make_foo` correctly and fully initializes foo.

Note that compiling with optimizations yields correct code. Looking at the IR produced _with_ optimizations the `pass` and `fail` functions ends up doing the exact same thing, but not when disabling (`-O0`) optimizations.

Versions:
- LLVM: 14.0.0 (329fda39c507e8740978d10458451dcdb21563be)
- Target: arm64-apple-darwin21.3.0
- Host: `uname -srm => Darwin 21.3.0 arm64` macOS 12.2.1 (21D62)

**Comment by rsms** [comment]
I also ran bugpoint but the simplified IR ended up identical. Perhaps I'm using bugpoint incorrectly here since there are no(?) optimization passes involved.

```
$ clang -O0 -Wall -Wextra -std=c11 -c -emit-llvm -o clang-init-bug.bc clang-init-bug.c
$ bugpoint -run-llc clang-init-bug.bc
#...
$ clang -O0 -Wall -Wextra -std=c11 -o clang-init-bug2 bugpoint-reduced-simplified.bc
$ ./clang-init-bug2
foo.a.b[2] = 01 (should be 00)
foo byte for byte:
  07 02 01 00 00 00
foo.a.b[2] = 00 (should be 00)
foo byte for byte:
  07 00 00 00 00 00
$ llvm-dis -o bugpoint-reduced-simplified.ll bugpoint-reduced-simplified.bc
```

c, bc and ll files in an archive:
[bugpoint.zip](https://github.com/llvm/llvm-project/files/8576924/bugpoint.zip)

**Comment by efriedma-quic** [comment]
I think your example simplifies to something like this:

```
typedef struct Attr {
  union { int a; int b[3]; };
} Attr;
int f(int x) {
    Attr y = { .a = x };
    return y.b[2];
}
```

"b" is uninitialized, so the function returns undef.  As far as I can tell, this conforms with the standard?

**Comment by rsms** [comment]
Indeed I believe you are correct. So sorry to take up your time with a dud! On the upside, today I learned something new.
