### ISSUE TITLE
fatal error: error in backend: alignment is limited to 32-bytes

### ISSUE THREAD

**Issue by Dajeeba** [llvm/llvm-project#55174]
[rte_cryptodev-a2eeb2.zip](https://github.com/llvm/llvm-project/files/8585508/rte_cryptodev-a2eeb2.zip)
[rte_ethdev-33cdc8.zip](https://github.com/llvm/llvm-project/files/8585510/rte_ethdev-33cdc8.zip)

C:\work\research\dpdk\source\dpdk-21.11>ninja -C build
ninja: Entering directory `build'
[120/549] Compiling C object drivers/libtmp_rte_bus_pci.a.p/bus_pci_windows_pci_netuio.c.obj
../drivers/bus/pci/windows/pci_netuio.c:127:33: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        struct device_info hw_info = { 0 };
                                       ^
                                       {}
1 warning generated.
[341/549] Linking target lib/rte_kvargs-22.dll
   Creating library lib\rte_kvargs.lib and object lib\rte_kvargs.exp
[342/549] Linking target lib/rte_telemetry-22.dll
   Creating library lib\rte_telemetry.lib and object lib\rte_telemetry.exp
[354/549] Generating symbol file lib/rte_kvargs-22.dll.p/rte_kvargs-22.dll.symbols
WARNING: ['lib', 'llvm-lib', 'dlltool'] do not work or were not found. Relinking will always happen on source changes.
'lib' not found
ignoring unknown argument: -list
lib\rte_kvargs.lib: not a COFF object, bitcode or resource file
'dlltool' not found

[420/549] Linking target lib/rte_eal-22.dll
   Creating library lib\rte_eal.lib and object lib\rte_eal.exp
[447/549] Linking target drivers/rte_common_iavf-22.dll
   Creating library drivers\rte_common_iavf.lib and object drivers\rte_common_iavf.exp
[449/549] Linking target lib/rte_ring-22.dll
   Creating library lib\rte_ring.lib and object lib\rte_ring.exp
[450/549] Linking target lib/rte_dmadev-22.dll
   Creating library lib\rte_dmadev.lib and object lib\rte_dmadev.exp
[451/549] Linking target drivers/rte_bus_auxiliary-22.dll
   Creating library drivers\rte_bus_auxiliary.lib and object drivers\rte_bus_auxiliary.exp
[452/549] Linking target drivers/rte_bus_vdev-22.dll
   Creating library drivers\rte_bus_vdev.lib and object drivers\rte_bus_vdev.exp
[453/549] Linking target lib/rte_meter-22.dll
   Creating library lib\rte_meter.lib and object lib\rte_meter.exp
[454/549] Linking target lib/rte_stack-22.dll
   Creating library lib\rte_stack.lib and object lib\rte_stack.exp
[470/549] Linking target lib/rte_pci-22.dll
   Creating library lib\rte_pci.lib and object lib\rte_pci.exp
[481/549] Linking target lib/rte_rcu-22.dll
   Creating library lib\rte_rcu.lib and object lib\rte_rcu.exp
[482/549] Linking target lib/rte_mempool-22.dll
   Creating library lib\rte_mempool.lib and object lib\rte_mempool.exp
[487/549] Linking target drivers/rte_dma_skeleton-22.dll
   Creating library drivers\rte_dma_skeleton.lib and object drivers\rte_dma_skeleton.exp
[502/549] Linking target drivers/rte_bus_pci-22.dll
   Creating library drivers\rte_bus_pci.lib and object drivers\rte_bus_pci.exp
[507/549] Linking target drivers/rte_mempool_stack-22.dll
   Creating library drivers\rte_mempool_stack.lib and object drivers\rte_mempool_stack.exp
[508/549] Linking target drivers/rte_mempool_ring-22.dll
   Creating library drivers\rte_mempool_ring.lib and object drivers\rte_mempool_ring.exp
[509/549] Linking target lib/rte_mbuf-22.dll
   Creating library lib\rte_mbuf.lib and object lib\rte_mbuf.exp
[512/549] Linking target lib/rte_timer-22.dll
   Creating library lib\rte_timer.lib and object lib\rte_timer.exp
[514/549] Linking target lib/rte_cfgfile-22.dll
   Creating library lib\rte_cfgfile.lib and object lib\rte_cfgfile.exp
[515/549] Linking target drivers/rte_dma_idxd-22.dll
   Creating library drivers\rte_dma_idxd.lib and object drivers\rte_dma_idxd.exp
[516/549] Linking target drivers/rte_dma_ioat-22.dll
   Creating library drivers\rte_dma_ioat.lib and object drivers\rte_dma_ioat.exp
[518/549] Compiling C object lib/librte_cryptodev.a.p/cryptodev_rte_cryptodev.c.obj
FAILED: lib/librte_cryptodev.a.p/cryptodev_rte_cryptodev.c.obj
"clang" "-Ilib\librte_cryptodev.a.p" "-Ilib" "-I..\lib" "-Ilib\cryptodev" "-I..\lib\cryptodev" "-I." "-I.." "-Iconfig" "-I..\config" "-Ilib\eal\include" "-I..\lib\eal\include" "-Ilib\eal\windows\include" "-I..\lib\eal\windows\include" "-Ilib\eal\x86\include" "-I..\lib\eal\x86\include" "-Ilib\eal\common" "-I..\lib\eal\common" "-Ilib\eal" "-I..\lib\eal" "-Ilib\kvargs" "-I..\lib\kvargs" "-Ilib\mbuf" "-I..\lib\mbuf" "-Ilib\mempool" "-I..\lib\mempool" "-Ilib\ring" "-I..\lib\ring" "-Ilib\metrics" "-I..\lib\metrics" "-Ilib\telemetry" "-I..\lib\telemetry" "-Ilib\rcu" "-I..\lib\rcu" "-Xclang" "-fcolor-diagnostics" "-pipe" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-O3" "-include" "rte_config.h" "-Wextra" "-Wcast-qual" "-Wdeprecated" "-Wformat" "-Wformat-nonliteral" "-Wformat-security" "-Wmissing-declarations" "-Wmissing-prototypes" "-Wnested-externs" "-Wold-style-definition" "-Wpointer-arith" "-Wsign-compare" "-Wstrict-prototypes" "-Wundef" "-Wwrite-strings" "-Wno-address-of-packed-member" "-Wno-missing-field-initializers" "-D_GNU_SOURCE" "-D_WIN32_WINNT=0x0A00" "-D_CRT_SECURE_NO_WARNINGS" "-march=native" "-DALLOW_EXPERIMENTAL_API" "-DALLOW_INTERNAL_API" "-DRTE_LOG_DEFAULT_LOGTYPE=lib.cryptodev" -MD -MQ lib/librte_cryptodev.a.p/cryptodev_rte_cryptodev.c.obj -MF "lib\librte_cryptodev.a.p\cryptodev_rte_cryptodev.c.obj.d" -o lib/librte_cryptodev.a.p/cryptodev_rte_cryptodev.c.obj "-c" ../lib/cryptodev/rte_cryptodev.c
fatal error: error in backend: alignment is limited to 32-bytes
clang.exe: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
clang.exe: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang.exe: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang.exe: note: diagnostic msg: C:\Users\anadgar\AppData\Local\Temp\rte_cryptodev-a2eeb2.c
clang.exe: note: diagnostic msg: C:\Users\anadgar\AppData\Local\Temp\rte_cryptodev-a2eeb2.sh
clang.exe: note: diagnostic msg:

********************
[519/549] Linking target lib/rte_gpudev-22.dll
   Creating library lib\rte_gpudev.lib and object lib\rte_gpudev.exp
[520/549] Compiling C object lib/librte_ethdev.a.p/ethdev_rte_ethdev.c.obj
FAILED: lib/librte_ethdev.a.p/ethdev_rte_ethdev.c.obj
"clang" "-Ilib\librte_ethdev.a.p" "-Ilib" "-I..\lib" "-Ilib\ethdev" "-I..\lib\ethdev" "-I." "-I.." "-Iconfig" "-I..\config" "-Ilib\eal\include" "-I..\lib\eal\include" "-Ilib\eal\windows\include" "-I..\lib\eal\windows\include" "-Ilib\eal\x86\include" "-I..\lib\eal\x86\include" "-Ilib\eal\common" "-I..\lib\eal\common" "-Ilib\eal" "-I..\lib\eal" "-Ilib\kvargs" "-I..\lib\kvargs" "-Ilib\net" "-I..\lib\net" "-Ilib\mbuf" "-I..\lib\mbuf" "-Ilib\mempool" "-I..\lib\mempool" "-Ilib\ring" "-I..\lib\ring" "-Ilib\metrics" "-I..\lib\metrics" "-Ilib\telemetry" "-I..\lib\telemetry" "-Ilib\meter" "-I..\lib\meter" "-Xclang" "-fcolor-diagnostics" "-pipe" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-O3" "-include" "rte_config.h" "-Wextra" "-Wcast-qual" "-Wdeprecated" "-Wformat" "-Wformat-nonliteral" "-Wformat-security" "-Wmissing-declarations" "-Wmissing-prototypes" "-Wnested-externs" "-Wold-style-definition" "-Wpointer-arith" "-Wsign-compare" "-Wstrict-prototypes" "-Wundef" "-Wwrite-strings" "-Wno-address-of-packed-member" "-Wno-missing-field-initializers" "-D_GNU_SOURCE" "-D_WIN32_WINNT=0x0A00" "-D_CRT_SECURE_NO_WARNINGS" "-march=native" "-DALLOW_EXPERIMENTAL_API" "-DALLOW_INTERNAL_API" "-DRTE_LOG_DEFAULT_LOGTYPE=lib.ethdev" -MD -MQ lib/librte_ethdev.a.p/ethdev_rte_ethdev.c.obj -MF "lib\librte_ethdev.a.p\ethdev_rte_ethdev.c.obj.d" -o lib/librte_ethdev.a.p/ethdev_rte_ethdev.c.obj "-c" ../lib/ethdev/rte_ethdev.c
fatal error: error in backend: alignment is limited to 32-bytes
clang.exe: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
clang.exe: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang.exe: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang.exe: note: diagnostic msg: C:\Users\anadgar\AppData\Local\Temp\rte_ethdev-33cdc8.c
clang.exe: note: diagnostic msg: C:\Users\anadgar\AppData\Local\Temp\rte_ethdev-33cdc8.sh
clang.exe: note: diagnostic msg:

********************
[521/549] Linking target lib/rte_net-22.dll
   Creating library lib\rte_net.lib and object lib\rte_net.exp
ninja: build stopped: subcommand failed.

C:\work\research\dpdk\source\dpdk-21.11>

**Comment by EugeneZelenko** [comment]
Clang 7 is unsupported version. Could you please try version 14 or `main`?

**Comment by Dajeeba** [comment]
Used LLVM 14. That solved the problem. Thank you!
