### ISSUE TITLE
Low perf compared to gcc for benchmark

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5518]
|  |  |
| --- | --- |
| Bugzilla Link | [5146](https://llvm.org/bz5146) |
| Version | 2.6 |
| OS | Linux |
| Attachments | [bearophile.c](https://user-images.githubusercontent.com/60944935/143740021-ef568415-f4a3-43e8-ab9e-c8985550a881.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 

Filed on behalf of bearophile:

See beginning of C file for bearophile's 2.5 timings.  I get with llvm 2.6 and gcc 4.3.4 at his compile options with -fno-math-errno -funsafe-math-optimizations: 2.7 sec and 2.1 sec respectively (Intel Q6600), so what ever is the problem hasn't gone completely away in 2.6.

Some potential items from a quick glance through the asm:

tfo_apply has more mmx adds than the gcc one
atan2 (maybe others) are tail calls in gcc but not llvm

**Comment by gwelymernans** [comment]
When I run this now on my Intel(R) Xeon(R) W-2135 CPU @ 3.70GHz machine, I get both clang and gcc generating code that runs in ~2.5s.
