### ISSUE TITLE
[clang][ADT] SmallVector unable to grow. Requested capacity (4294967296) is larger than maximum value for size type (4294967295)

### ISSUE THREAD

**Issue by dbakunevich** [llvm/llvm-project#55186]
This bug was found by Azul FuzzGen fuzzer for CPP.

Godbolt link: https://godbolt.org/z/a59aEE1da

Run clang -O3 (x86_64) on the test
[test.cpp.txt](https://github.com/llvm/llvm-project/files/8589072/test.cpp.txt)
 
Failure looks like:
```
Execution time: 24220.0 seconds ./gen_02065.cpp
./gen_02065.cpp:306:66: warning: shift count >= width of type [-Wshift-count-overflow]
 switch (abs((((((int64_t)int64_tVar_49)  >=  (int64_tVar_53)))  >>  46 ))) {
                                                                 ^   ~~
./gen_02065.cpp:413:36: warning: unsequenced modification and access to 'uint16_tVar_74' [-Wunsequenced]                                                                                                                                       if ((uint16_t)(((((uint16_tVar_74++) - (true))) * ((uint16_tVector_73.empty() ? (((uint16_t)VECTORuint16_tRefIterator_76) - (uint16_tVar_74)) : uint16_tVector_73.at(((uint16_tVector_73.empty() ? uint16_tVar_74 : uint16_tVector_73[(uint16_tVar_74) % uint16_tVector_73.size()] )) % uint16_tVector_73.size())))))) {                                                                                                                                                                                                   ^                                                                                          ~
./gen_02065.cpp:506:167: warning: unsequenced modification and access to 'uint16_tVar_90' [-Wunsequenced]
uint16_tVector_83.push_back( max((uint16_t)( max((uint16_t)((uint16_t)uint16_tVar_90), (uint16_t)(((uint16_tVar_90) - (uint16_tVar_90)))) ), (uint16_t)(uint16_tVar_90--)) );
                                                                      ~~~~~~~~~~~~~~                                                                                  ^
./gen_02065.cpp:794:149: warning: taking the absolute value of unsigned type 'bool' has no effect [-Wabsolute-value]
int8_tVar_146 *= ((((int8_t)(((int8_tVar_146) + (int8_tVar_146)))) ? ((false) ? ((int8_t)int8_tVar_146) : (int8_tVar_146)) : (int8_tVar_146))  >=  (abs(true)));
                                                                                                                                                    ^                                                                                        ./gen_02065.cpp:794:149: note: remove the call to 'abs' since unsigned values cannot be negative
int8_tVar_146 *= ((((int8_t)(((int8_tVar_146) + (int8_tVar_146)))) ? ((false) ? ((int8_t)int8_tVar_146) : (int8_tVar_146)) : (int8_tVar_146))  >=  (abs(true)));
                                                                                                                                                    ^~~
fatal error: error in backend: SmallVector unable to grow. Requested capacity (4294967296) is larger than maximum value for size type (4294967295)                                                                                           clang-15: error: clang frontend command failed with exit code 70 (use -v to see invocation)
```

**Comment by yurai007** [comment]
It looks more like infinite loop in InstCombine/InstCombineNegator:

Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x000055d132f30571 in llvm::SetVector<llvm::Instruction*, llvm::SmallVector<llvm::Instruction*, 16u>, llvm::SmallDenseSet<llvm::Instruction*, 16u, llvm::DenseMapInfo<llvm::Instruction*, void> > >::remove (this=0x55d13c6d52a8, X=@0x55d13a144610: 0x2010) at /home/programs/llvm-project/llvm/include/llvm/ADT/SetVector.h:157
157	  bool remove(const value_type& X) {
(gdb) bt
#0  0x000055d132f30571 in llvm::SetVector<llvm::Instruction*, llvm::SmallVector<llvm::Instruction*, 16u>, llvm::SmallDenseSet<llvm::Instruction*, 16u, llvm::DenseMapInfo<llvm::Instruction*, void> > >::remove (this=0x55d13c6d52a8, X=@0x55d13a144610: 0x2010)
    at /home/programs/llvm-project/llvm/include/llvm/ADT/SetVector.h:157
#1  0x000055d132f304e0 in llvm::InstructionWorklist::remove (this=0x55d13a9d06e8, I=0x55d13c6d52a8) at /home/programs/llvm-project/llvm/include/llvm/Transforms/Utils/InstructionWorklist.h:93
#2  0x000055d132f2d37e in llvm::InstCombinerImpl::eraseInstFromFunction (this=0x7fff22c61da0, I=...) at /home/programs/llvm-project/llvm/lib/Transforms/InstCombine/InstCombineInternal.h:463
#3  0x000055d132f273ad in llvm::InstCombinerImpl::run (this=0x7fff22c61da0) at /home/programs/llvm-project/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:4060
#4  0x000055d132f29276 in combineInstructionsOverFunction (F=..., Worklist=..., AA=0x55d13c6d5108, AC=..., TLI=..., TTI=..., DT=..., ORE=..., BFI=0x0, PSI=0x55d13c683f98, MaxIterations=1000, LI=0x55d13b9e8138)
    at /home/programs/llvm-project/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:4484
#5  0x000055d132f28ce0 in llvm::InstCombinePass::run (this=0x55d13a9d06e8, F=..., AM=...) at /home/programs/llvm-project/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:4515
#6  0x000055d1359e5ea7 in llvm::detail::PassModel<llvm::Function, llvm::InstCombinePass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (this=0x55d13a9d06e0, IR=..., AM=...)
    at /home/programs/llvm-project/llvm/include/llvm/IR/PassManagerInternal.h:88
#7  0x000055d132b689ec in llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (this=0x55d13a40d788, IR=..., AM=...)
    at /home/programs/llvm-project/llvm/include/llvm/IR/PassManager.h:522
#8  0x000055d134837aa7 in llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (
    this=0x55d13a40d780, IR=..., AM=...) at /home/programs/llvm-project/llvm/include/llvm/IR/PassManagerInternal.h:88
#9  0x000055d132b67331 in llvm::ModuleToFunctionPassAdaptor::run (this=0x55d13a40d7b8, M=..., AM=...) at /home/programs/llvm-project/llvm/lib/IR/PassManager.cpp:127
#10 0x000055d13483bd47 in llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (this=0x55d13a40d7b0, IR=..., AM=...)
    at /home/programs/llvm-project/llvm/include/llvm/IR/PassManagerInternal.h:88
#11 0x000055d132b6791c in llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (this=0x7fff22c62b30, IR=..., AM=...) at /home/programs/llvm-project/llvm/include/llvm/IR/PassManager.h:522

#12 0x000055d134825a80 in (anonymous namespace)::EmitAssemblyHelper::RunOptimizationPipeline (this=0x7fff22c649f0, Action=clang::Backend_EmitObj, Python Exception <class 'gdb.error'>: Request for member '_M_head_impl' is ambiguous in type 'std::tuple<llvm::raw_pwrite_stream*, std::default_delete<llvm::raw_pwrite_stream> >'. Candidates are:
  'std::default_delete<llvm::raw_pwrite_stream> std::_Head_base<1, std::default_delete<llvm::raw_pwrite_stream>, true>::_M_head_impl' (std::tuple<llvm::raw_pwrite_stream*, std::default_delete<llvm::raw_pwrite_stream> > -> std::_Tuple_impl<0, llvm::raw_pwrite_stream*, std::default_delete<llvm::raw_pwrite_stream> > -> std::_Tuple_impl<1, std::default_delete<llvm::raw_pwrite_stream> > -> std::_Head_base<1, std::default_delete<llvm::raw_pwrite_stream>, true>)
  '<unnamed type> std::_Head_base<0, llvm::raw_pwrite_stream*, false>::_M_head_impl' (std::tuple<llvm::raw_pwrite_stream*, std::default_delete<llvm::raw_pwrite_stream> > -> std::_Tuple_impl<0, llvm::raw_pwrite_stream*, std::default_delete<llvm::raw_pwrite_stream> > -> std::_Head_base<0, llvm::raw_pwrite_stream*, false>)
OS=..., Python Exception <class 'gdb.error'>: Request for member '_M_head_impl' is ambiguous in type 'std::tuple<llvm::ToolOutputFile*, std::default_delete<llvm::ToolOutputFile> >'. Candidates are:
  'std::default_delete<llvm::ToolOutputFile> std::_Head_base<1, std::default_delete<llvm::ToolOutputFile>, true>::_M_head_impl' (std::tuple<llvm::ToolOutputFile*, std::default_delete<llvm::ToolOutputFile> > -> std::_Tuple_impl<0, llvm::ToolOutputFile*, std::default_delete<llvm::ToolOutputFile> > -> std::_Tuple_impl<1, std::default_delete<llvm::ToolOutputFile> > -> std::_Head_base<1, std::default_delete<llvm::ToolOutputFile>, true>)
  '<unnamed type> std::_Head_base<0, llvm::ToolOutputFile*, false>::_M_head_impl' (std::tuple<llvm::ToolOutputFile*, std::default_delete<llvm::ToolOutputFile> > -> std::_Tuple_impl<0, llvm::ToolOutputFile*, std::default_delete<llvm::ToolOutputFile> > -> std::_Head_base<0, llvm::ToolOutputFile*, false>)
ThinLinkOS=...) at /home/programs/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:965
#13 0x000055d13481fe34 in (anonymous namespace)::EmitAssemblyHelper::EmitAssembly (this=0x7fff22c649f0, Action=clang::Backend_EmitObj, Python Exception <class 'gdb.error'>: Request for member '_M_head_impl' is ambiguous in type 'std::tuple<llvm::raw_pwrite_stream*, std::default_delete<llvm::raw_pwrite_stream> >'. Candidates are:
  'std::default_delete<llvm::raw_pwrite_stream> std::_Head_base<1, std::default_delete<llvm::raw_pwrite_stream>, true>::_M_head_impl' (std::tuple<llvm::raw_pwrite_stream*, std::default_delete<llvm::raw_pwrite_stream> > -> std::_Tuple_impl<0, llvm::raw_pwrite_stream*, std::default_delete<llvm::raw_pwrite_stream> > -> std::_Tuple_impl<1, std::default_delete<llvm::raw_pwrite_stream> > -> std::_Head_base<1, std::default_delete<llvm::raw_pwrite_stream>, true>)
  '<unnamed type> std::_Head_base<0, llvm::raw_pwrite_stream*, false>::_M_head_impl' (std::tuple<llvm::raw_pwrite_stream*, std::default_delete<llvm::raw_pwrite_stream> > -> std::_Tuple_impl<0, llvm::raw_pwrite_stream*, std::default_delete<llvm::raw_pwrite_stream> > -> std::_Head_base<0, llvm::raw_pwrite_stream*, false>)
OS=...) at /home/programs/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1022
#14 0x000055d13481f26c in clang::EmitBackendOutput (Diags=..., HeaderOpts=..., CGOpts=..., TOpts=..., LOpts=..., TDesc=..., M=0x55d139e36310, Action=clang::Backend_EmitObj, Python Exception <class 'gdb.error'>: Request for member '_M_head_impl' is ambiguous in type 'std::tuple<llvm::raw_pwrite_stream*, std::default_delete<llvm::raw_pwrite_stream> >'. Candidates are:
  'std::default_delete<llvm::raw_pwrite_stream> std::_Head_base<1, std::default_delete<llvm::raw_pwrite_stream>, true>::_M_head_impl' (std::tuple<llvm::raw_pwrite_stream*, std::default_delete<llvm::raw_pwrite_stream> > -> std::_Tuple_impl<0, llvm::raw_pwrite_stream*, std::default_delete<llvm::raw_pwrite_stream> > -> std::_Tuple_impl<1, std::default_delete<llvm::raw_pwrite_stream> > -> std::_Head_base<1, std::default_delete<llvm::raw_pwrite_stream>, true>)
  '<unnamed type> std::_Head_base<0, llvm::raw_pwrite_stream*, false>::_M_head_impl' (std::tuple<llvm::raw_pwrite_stream*, std::default_delete<llvm::raw_pwrite_stream> > -> std::_Tuple_impl<0, llvm::raw_pwrite_stream*, std::default_delete<llvm::raw_pwrite_stream> > -> std::_Head_base<0, llvm::raw_pwrite_stream*, false>)
OS=...) at /home/programs/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1181
#15 0x000055d134df4df4 in clang::BackendConsumer::HandleTranslationUnit (this=0x55d139e34510, C=...) at /home/programs/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:379
#16 0x000055d135eca3d5 in clang::ParseAST (S=..., PrintStats=false, SkipFunctionBodies=false) at /home/programs/llvm-project/clang/lib/Parse/ParseAST.cpp:175
#17 0x000055d134bf17ec in clang::ASTFrontendAction::ExecuteAction (this=0x55d139e011d0) at /home/programs/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1139
#18 0x000055d134deff6b in clang::CodeGenAction::ExecuteAction (this=0x55d139e011d0) at /home/programs/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:1143
#19 0x000055d134bf1119 in clang::FrontendAction::Execute (this=0x55d139e011d0) at /home/programs/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1032
#20 0x000055d134b0f16e in clang::CompilerInstance::ExecuteAction (this=0x55d139df6300, Act=...) at /home/programs/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:1036
#21 0x000055d134dda5f1 in clang::ExecuteCompilerInvocation (Clang=0x55d139df6300) at /home/programs/llvm-project/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:266
#22 0x000055d1314a15b9 in cc1_main (Argv=..., Argv0=0x7fff22c6a352 "/home/programs/llvm-project/build/bin/clang-15", MainAddr=0x55d131492390 <GetExecutablePath[abi:cxx11](char const*, bool)>) at /home/programs/llvm-project/clang/tools/driver/cc1_main.cpp:248
#23 0x000055d131493a8a in ExecuteCC1Tool (ArgV=...) at /home/programs/llvm-project/clang/tools/driver/driver.cpp:317
#24 0x000055d131492ad9 in main (Argc=67, Argv=0x7fff22c68a78) at /home/programs/llvm-project/clang/tools/driver/driver.cpp:388

  
(gdb) 
4059	      if (isInstructionTriviallyDead(I, &TLI)) {
(gdb) 
4060	        eraseInstFromFunction(*I);
(gdb) 
4061	        ++NumDeadInst;
(gdb) 
4062	        continue;
(gdb) 
4059	      if (isInstructionTriviallyDead(I, &TLI)) {
(gdb) 
4060	        eraseInstFromFunction(*I);
(gdb) 
4061	        ++NumDeadInst;
(gdb) 
4062	        continue;
(gdb) 
4059	      if (isInstructionTriviallyDead(I, &TLI)) {


(gdb)
llvm::Negator::negate (this=0x7fffffff5d00, V=0x555562e649c0, Depth=2) at /home/programs/llvm-project/llvm/lib/Transforms/InstCombine/InstCombineNegator.cpp:500
500	  NegationsCache[V] = NegatedV;
(gdb) 
502	  return NegatedV;
(gdb) 
503	}
(gdb) 
llvm::Negator::visitImpl (this=0x7fffffff5d00, V=0x555563ad8f60, Depth=1) at /home/programs/llvm-project/llvm/lib/Transforms/InstCombine/InstCombineNegator.cpp:410
410	        NegatedOps.emplace_back(NegOp); // Successfully negated operand!
(gdb) 
411	        continue;
(gdb) 
407	    for (Value *Op : I->operands()) {
(gdb) 
409	      if (Value *NegOp = negate(Op, Depth + 1)) {
(gdb) 
410	        NegatedOps.emplace_back(NegOp); // Successfully negated operand!
(gdb) 
411	        continue;
(gdb) 
407	    for (Value *Op : I->operands()) {
(gdb) 
419	    assert((NegatedOps.size() + NonNegatedOps.size()) == 2 &&

(gdb) p I->dump()
  %add70.1.2.1.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg. = add i32 %.neg.1.2.1.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.n, -43058

Unlike https://github.com/llvm/llvm-project/issues/55217, this snippet times out Godbolt on Clang 12, 13 and 14 as well.

**Comment by nikic** [comment]
No longer reproduces since Clang 16.
