### ISSUE TITLE
Backport [MC][AArch64] Enable '+v8a' when nothing specified for MCSubtargetInfo

### ISSUE THREAD

**Issue by oToToT** [llvm/llvm-project#55182]
4a31af88a26726f4662a2923618fe45977d09356 fixes some backward compatibility problems of MC tools.  
For example, without this patch, llvm-objdump can't decompile some instructions which can be decompiled before 14.0 with default parameter.

**Comment by tstellar** [comment]
@labrinea What do you think about backporting this? https://github.com/llvm/llvm-project/commit/4a31af88a26726f4662a2923618fe45977d09356

**Comment by oToToT** [comment]
Any update on this?

**Comment by tstellar** [comment]
@TNorthover Do you have any thoughts on this? https://github.com/llvm/llvm-project/commit/4a31af88a26726f4662a2923618fe45977d09356

**Comment by TNorthover** [comment]
Yep, seems like a sensible one to bring in.

**Comment by tstellar** [comment]
Merged: c12386ae247c0d46e1d513942e322e3a0510b126
