### ISSUE TITLE
clang-format doesn't like spaces in the path sent to the "-style" command line argument

### ISSUE THREAD

**Issue by sthompson-crestron** [llvm/llvm-project#55191]
If I have no spaces in the path I pass to the "-style" switch of clang-format, then it runs normally:

```console
$ clang-format -i -style="/Users/sthompson/Projects/myapp-ios/.clang-format" MyApp/main.m
$
```

However, if I have a space in the file name then I am told that I have an "Invalid value for -style":

 Note the use of a space in "myapp iOS)

```console
$ clang-format -i -style="/Users/sthompson/Projects/myapp ios/.clang-format" MyApp/main.m
Invalid value for -style
$
```

I would expect the "-style" option to allow for a quoted file name containing a space.

These commands were run from the terminal on a Mac OS system running Mac OS 12.3.1

**Comment by owenca** [comment]
You need insert `file:` between `-style=` and the file path as documented [here](https://releases.llvm.org/14.0.0/tools/clang/docs/ClangFormat.html).
