### ISSUE TITLE
libc++ implementation's use of "__bound" conflicts with Windows SDK SAL macro

### ISSUE THREAD

**Issue by pkasting** [llvm/llvm-project#55195]
I'm a Chromium dev trying to upgrade Chromium to C++20.  Chromium/Win builds with libc++ and the Windows SDK, and under C++20, the two together have problems because Windows' longstanding SAL macros clash with the libc++ implementation.

Specifically, in various headers (specstrings.h, most notably) Windows #defines "__bound" (and many other leading-double-underscore annotations), while in a few places (at least include/__iterator/{next,prev,advance}.h) libc++ tries to use "__bound" as a parameter name.  This leads to compile errors.

Arguably, SAL never should have used leading-double-underscore annotations, though them being reserved was presumably precisely _why_ they did so.  But now that they have, I suspect there's zero chance of Microsoft changing.  So I propose that libc++ just use a different variable name than "__bound".

**Comment by pkasting** [comment]
Apparently there's some precedent for avoiding SAL macros -- see https://reviews.llvm.org/D103541 .   Probably "__bound" should be added to the "nasty macros" list.

**Comment by mordante** [comment]
Yes we tend to add them to the list when we get some errors. It's indeed a shame the SAL macros didn't get a nice prefix especially since they use some common names.
(I had a look at your patch.)
