### ISSUE TITLE
ICE... SystemZISel?  LICM load hoisting?

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#55204]
I got a test case that resulted in

`fatal error: error in backend: Cannot select: t61: i64 = Constant<8237692794279528316>`

I did a bisect and found that the first bad commit was 2cdc6f2ca62e "Reland "[LICM] Hoist LOAD without sinking the STORE"". I find that it helps to revert that commit on HEAD as well... 

I see in the reduced test case:

```llvm
 %and = and i64 %and12, %conv3       |   %2 = load i64, ptr @e, align 8, !tb
                                      >   %and = and i64 %2, %conv3
  store i64 %and, ptr @e, align 8, !t     store i64 %and, ptr @e, align 8, !t
```

This is inside a loop and it's not for me trivial to see that the hoisting of the load of @e is safe...

In SystemZ isel, it seems that we get an `and` with two constants, which we can't quite handle.

`i64 = and Constant:i64<1064831134304125>, OpaqueConstant:i64<1064831134304126>`

`tryRISBGZero(Node)` is called, which calls `SelectCode(N)` which then fails. N is then a `i64 = Constant<1064831134304124>`

Not sure if `SystemZISel` should be able to handle this type of node or if something earlier has just gone wrong...

[testcase.tar.gz](https://github.com/llvm/llvm-project/files/8597333/testcase.tar.gz)

```console
$ clang -march=z13 -O1 crash0.i -o a.out -w

$ clang -march=z13 -O2 crash0.i -o a.out -w
fatal error: error in backend: Cannot select: t48: i64 = Constant<1064831134304124>

$ llc  -O2 -o out.s crash0.ll
LLVM ERROR: Cannot select: t48: i64 = Constant<1064831134304124>
```

**Comment by uweigand** [comment]
> `tryRISBGZero(Node)` is called, which calls `SelectCode(N)` which then fails. N is then a `i64 = Constant<1064831134304124>`
> 
> Not sure if `SystemZISel` should be able to handle this type of node or if something earlier has just gone wrong...

I'm not completely sure either, but it cannot hurt to be conservative in the backend here.  I don't think it makes sense for `tryRISBGZero` to attempt to handle an expression that is actually a compile-time constant.  Maybe the function should just bail out if `RISGB.Input` is a constant after `expandRxSBG` ?

**Comment by JonPsson** [comment]
@djtodoro  The SystemZ isel issue has been resolved, but it might still be useful if you checked that LICM seems to be on the track as well...

**Comment by djtodoro** [comment]
I think this has nothing related to the conditional `LICM`, especially with partial `load` hoisting.

**Comment by djtodoro** [comment]
> with partial load hoisting.
that has been implemented with the https://github.com/llvm/llvm-project/commit/2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0

**Comment by JonPsson** [comment]
ok, thanks for taking a look!
