### ISSUE TITLE
clang 15.0.0 causes regression on O3 optimisation compared to clang 14.0

### ISSUE THREAD

**Issue by Haiderahandali** [llvm/llvm-project#55213]
here is a test case where clang 14 optimises better than clang trunk (15.0.0)
https://godbolt.org/z/j9zhcrjdz

this happens even when the lookup table is constant and local 
https://godbolt.org/z/61hvEP4Y9

according to https://godbolt.org/z/GWGKsed1f
it seems clang trunk in compiler explorer points to this exact commit
https://github.com/llvm/llvm-project/commit/09325d36061e42b495d1f4c7e933e260eac260ed

**Comment by RKSimon** [comment]
@nikic This might be an opaque pointers issue

14.x:
```
@foo = external dso_local local_unnamed_addr global [0 x i32], align 4
define i32 @lookup(i32 noundef %0) {
  %2 = zext i32 %0 to i64
  %3 = getelementptr inbounds [0 x i32], [0 x i32]* @foo, i64 0, i64 %2
  %4 = load i32, i32* %3, align 4
  ret i32 %4
}
```
trunk:
```
@foo = external local_unnamed_addr global [0 x i32], align 4

define i32 @lookup(i32 noundef %0)  {
  %2 = zext i32 %0 to i64
  %3 = getelementptr inbounds [0 x i32], ptr @foo, i64 0, i64 %2
  %4 = load i32, ptr %3, align 4
  ret i32 %4
}
```

**Comment by Haiderahandali** [comment]
it seems this issue is not related to O2 O3 optimisation, as It is reproducible on all the 7 optimisation flags.
Also, it is not limited to the x86 architecture, but can be reproduced on arm truck and risc-v truck, etc.

**Comment by nikic** [comment]
This is because Clang 15 defaults to position-independent code. You can use something like `-fno-pie` to restore previous behavior.
