### ISSUE TITLE
Clang does not see class member in a 'requires'.

### ISSUE THREAD

**Issue by EdvinVikstrom** [llvm/llvm-project#55216]
Tested with clang-trunk.
Here's the code:

```cpp
template<typename T>
class Test {

public:

    static constexpr int val = 16;
    
    constexpr Test()
        requires (val == 16);
};

template<typename T>
constexpr Test<T>::Test() // error: out-of-line definition of 'Test<T>' does not match any declaration in 'Test<T>'
    requires (val == 16) // error: use of undeclared identifier 'val'
{
}

int main()
{
    Test<int> test();
    return 0;
}
```

I tested with GCC and it gives no errors.
Replacing `val == 16` with `Test<T>::val == 16` removes the 'undeclared identifier...' error but 'out-of-line...' error remains.
With no template parameters the code compiles if you write `Test::val == 16`.

**Comment by ilya-biryukov** [comment]
I'm assigning to myself for visibility, even though @luken-google was about to work on this.
(Luke is not part of the LLVM GH Project yet)

**Comment by luken-google** [comment]
Fix out for review at https://reviews.llvm.org/D132503
