### ISSUE TITLE
libc++: `take_view::__sentinel` has wrong `operator==`

### ISSUE THREAD

**Issue by acd1034** [llvm/llvm-project#55211]
`take_view::__sentinel` in libc++ now defines `operator==` between `const _Iter<_Const>&` and `const __sentinel&`, but I think `operator==` should be defined between `const _Iter<_OtherConst>&` and `const __sentinel&`.
Could you confirm whether this is right or not?

*Reference*: http://eel.is/c++draft/ranges#range.take.sentinel-4

https://github.com/llvm/llvm-project/blob/8a9e2dd48d8102fdb940db87e57192e399e7e61b/libcxx/include/__ranges/take_view.h#L163-L168

**Comment by philnik777** [comment]
CC @var-const

**Comment by var-const** [comment]
@acd1034 Thanks for the report! I'll take a look next week.

**Comment by EugeneZelenko** [comment]
@acd1034: Please elaborate.
