### ISSUE TITLE
Cherry-pick 7d7771f34d14e0108adf02a6fd0b33943afae3da to release/14.x

### ISSUE THREAD

**Issue by nathanchance** [llvm/llvm-project#55234]
Attempting to use BOLT in instrumentation mode on `clang` on `release/14.x` results in `llvm-bolt` getting killed on a machine with 32GB of RAM:

https://github.com/ClangBuiltLinux/tc-build/issues/188

7d7771f34d14e0108adf02a6fd0b33943afae3da makes combining multiple BOLT instrumentation files  (`.fdata`) take up much less space, which makes `llvm-bolt` consume much less memory while running on `clang`.

Current `release/14.x`:

```
$ diskus clang.fdata
126.12 GB (126,116,876,288 bytes)
```

`release/14.x` + 7d7771f34d14e0108adf02a6fd0b33943afae3da:

```
$ diskus clang.fdata
120.33 MB (120,332,288 bytes)
```

I am not sure if this is an acceptable backport request but I figured it was worth discussing :)

cc @llvm/issue-subscribers-bolt

**Comment by nathanchance** [comment]
> Let's wait for some more feedback in a couple of days before the push.

Thanks for the quick response! I am totally okay with waiting a few days for any feedback that might come in. As far as I am aware, Tom always asks the code owners if a backport is okay before he merges it so that should give everyone ample time to assess the risk of this backport.

**Comment by torvic9** [comment]
Please backport.
I tested a build of clang14 with this commit on top, with PGO and BOLT, on two x86 archs (skylake and znver2).
Both  resulting binaries can compile a current Linux kernel without errors.

**Comment by tstellar** [comment]
@maksfb What do you think about backporting this? https://github.com/llvm/llvm-project/commit/7d7771f34d14e0108adf02a6fd0b33943afae3da

**Comment by maksfb** [comment]
Yes, sorry, missed the original post. This should be safe and land cleanly. Do you want me to cherry-pick it on the release branch?

**Comment by tstellar** [comment]
@maksfb I'll take care of it, thanks.

**Comment by maksfb** [comment]
Thank you!
