### ISSUE TITLE
Adopt variable length instruction encoding in web assembly backend.

### ISSUE THREAD

**Issue by 0x59616e** [llvm/llvm-project#55235]
WebAssembly has variable length instructions, which isn't supported by the original `FixedLenDecoder`. So it uses its own custom disassembler.

But now things has changed. With [D115128](https://reviews.llvm.org/D115128) and [D120958](https://reviews.llvm.org/D120958) landed, the `FixedLenDecoder` has officially support for variable length instructions.

This is a bug tracker for deprecating the custom disassembler and migrating to the original disassembler.

See also [here](https://github.com/llvm/llvm-project/blob/main/llvm/utils/TableGen/DisassemblerEmitter.cpp#L127).

**Comment by bubba** [comment]
Hi @0x59616e , I've started to take a look at this. I think the first question around this is how will can we add support for variable length operands that can vary even on the same opcode. 
Immediates are LEB128 encoded in WebAssembly and that means that the size of the operand won't be known until the disassembler attempts to read it.
If I understand correctly the current `makeUp` callback used in the generated `decodeInstruction` method can only read a fixed number of bytes corresponding to each opcode, which is in turn determined by the generated `InstrLenTable`.

**Comment by 0x59616e** [comment]
> Immediates are LEB128 encoded in WebAssembly and that means that the size of the operand won't be known until the disassembler attempts to read it.

Do you mean that the size of the operand is also "variable-length" ? If that is the case, this variable-length decoder have to know the size of every operand in advance, so it's impossible to use the original decoder and we might have to continue on the current one.

**Comment by bubba** [comment]
Likewise, `VarLenCodeEmitterGen.cpp` relies on fixed per-opcode instruction sizes, computed and stored in the generated `Index` table so that will be another blocker for adopting it for WebAssembly

**Comment by 0x59616e** [comment]
It might not be possible without heavy workload. If the current one works perfectly, there is no reason to change that.
