### ISSUE TITLE
Backport [AArch64] Support for Ampere1 core

### ISSUE THREAD

**Issue by ptomsich** [llvm/llvm-project#55244]
64816e68f4419a9e14c23be8aa96fa412bed7e12 [AArch64] Add native CPU detection for Ampere1
7e02bc5237751118efe36c41b0caf004aeed022f [AArch64] Support for Ampere1 core

This adds support for the Ampere1 core to the 14.0.x series to support using the same Makefiles/scripts as with GCC (and the future LLVM 15).

Cherry-picked and tested w/o regressions against llvmorg-14.0.1

@kbeyls @davemgreen Ok to backport?

**Comment by kbeyls** [comment]
I see no issue with backporting these 2 patches, so it's OK from my perspective.

**Comment by ptomsich** [comment]
/cherry pick 7e02bc5237751118efe36c41b0caf004aeed022f 64816e68f4419a9e14c23be8aa96fa412bed7e12 91b24b018062c8650abfbd10f7da80a0c92266a7

**Comment by tstellar** [comment]
Duplicate of #55349
