### ISSUE TITLE
ld.lld doesn't support unresolved references when dynamically linking for MinGW

### ISSUE THREAD

**Issue by shlevy** [llvm/llvm-project#55245]
In particular this breaks building a shared `libc++abi` as a separate standalone build prior to `libc++` due to undefined symbols like `std::__1::__libcpp_execute_once`

**Comment by DimitryAndric** [comment]
So basically, `--allow-shlib-undefined` does not work for MinGW targets? What is the exact lld command line that you are running?

**Comment by shlevy** [comment]
It's true that `--allow-shlib-undefined` is not recognized, but that's expected by default so the actual error that shows up here is that linking a dll with missing symbols fails. E.g. `libc++abi.dll` fails due to missing symbols which are found in `libc++.dll`, thus I have to use `-DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=TRUE`.

If it would help I can recreate the exact error and invocation during the `libc++abi` build.

**Comment by mstorsjo** [comment]
This isn't a bug/missing feature in LLD, but PE-COFF DLLs simply don't support undefined symbols in the way ELF does. Therefore, having separate libc++ and libc++abi DLLs can't really be done. Instead, you can have libc++abi merged into the libc++ DLL.

With current (14.x release and current git main) it's easy to build them in this way - point cmake at `llvm-project/runtimes`, specify `-DLLVM_ENABLE_RUNTIMES="libcxxabi;libcxx"` and pass `-DLIBCXXABI_ENABLE_SHARED=OFF -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON -DLIBCXX_CXX_ABI=libcxxabi` - see e.g. this build setup: https://github.com/mstorsjo/llvm-mingw/blob/master/build-libcxx.sh#L93-L124

**Comment by mstorsjo** [comment]
Ok sorry I saw now that you were aware of the `-DLIBCXX_ENABLE_STATIC_ABI_LIBRARY` setup.

So yeah, that's the primary way to do it, as far as I know, as the DLL file format doesn't support undefined references. (A different way to do it, that afaik should be doable, but which probably is even more messy, is to build two DLLs with circular dependencies on each other.)

**Comment by shlevy** [comment]
I see, I'm not sure why I had the impression that binutils ld supported this. Thanks!

**Comment by mstorsjo** [comment]
> I see, I'm not sure why I had the impression that binutils ld supported this. Thanks!

Well ld.bfd does actually silently accept the `--allow-shlib-undefined` option (as part of common target independent options) - but it doesn't really do anything on PE targets - you still can't have undefined references in the output. In LLD we haven't implemented silently accepting that option, as it's quite contradictory (and doesn't really occur in the wild).
