### ISSUE TITLE
Flang 14.0 release notes

### ISSUE THREAD

**Issue by jme52** [llvm/llvm-project#55243]
The Flang 14.0 release notes, https://releases.llvm.org/14.0.0/tools/flang/docs/ReleaseNotes.html (as linked from https://releases.llvm.org/) currently contain

> "in progress notes for the upcoming 12.0.0 release"

It would be useful if its contents were updated and it contained the actual documentation of the 14.0 version.

**Comment by xgupta** [comment]
I think this particular issue for 14.0 can't be fixed now but a recent change will make sure the version will be picked up automatically - 
https://github.com/llvm/llvm-project/commit/4430e69fbdf59241fffd874e5a1d401c7797981d.

**Comment by xgupta** [comment]
CC @tru @tstellar FYI.
