### ISSUE TITLE
hwasan_report.cpp:472:14: warning: too many arguments for format [-Wformat-extra-args]

### ISSUE THREAD

**Issue by marxin** [llvm/llvm-project#55258]
There's an extra argument in the printf call:
https://github.com/llvm/llvm-project/blob/f1b9245199f3457a4d06d32d1bc6e44573c166e3/compiler-rt/lib/hwasan/hwasan_report.cpp#L472

@dvyukov @kcc

**Comment by fmayer** [comment]
Was fixed in [D147215](https://reviews.llvm.org/D147215).
