### ISSUE TITLE
Missing } gives empty output with no error message

### ISSUE THREAD

**Issue by AgnerF** [llvm/llvm-project#55257]
Compiling the attached cpp file gives an empty output with no error message.

[clangerr2.txt](https://github.com/llvm/llvm-project/files/8618758/clangerr2.txt)

clang version 14.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin

**Comment by AgnerF** [comment]
I get the error with LLVM-14.0.0-win64.exe downloaded from 
https://github.com/llvm/llvm-project/releases/tag/llvmorg-14.0.0
running in Windows 10.0

**Comment by JOE1994** [comment]
Error messages show up with `clang 19.1.0` : https://godbolt.org/z/cee3KK7d7

Closing this as it seems to be fixed :)
