### ISSUE TITLE
NOLINTBEGIN & NOLINTEND not working on Windows

### ISSUE THREAD

**Issue by drcxd** [llvm/llvm-project#55268]
I am using clang-tidy 14.0.3 on Windows, just downloaded the release from github page.
However, the `NOLINTBEGIN` and `NOLINTEND` comment does not work, they do not suppress warnings in between them.
`NOLINT` and `NOLINTNEXTLINE` works pretty well.

**Comment by sean-mcmanus** [comment]
FYI, I tried clang 14.0.0 and 14.0.3 on Windows and this bug doesn't repro for me.

**Comment by drcxd** [comment]
Could this be a client-side bug? How did you verify? 
I was using emacs and lsp-mode as the LSP client and using clang-tidy together with clangd. I'll try using clangd/clang-tidy on the command line later.

**Comment by drcxd** [comment]
I tried `NOLINTBEGIN` and `NOLINTEND` pair on command line and they do work. It might be a client side issue. Thanks.

**Comment by TomBobach** [comment]
I see the same issue using the clangd extension for VSCode on Windows: The live linting does not seem to know about the NOLINTBEGIN/NOLINTEND suppression.

**Comment by njames93** [comment]
This is a server side issue in clangd that has been fixed, it should be all good in the llvm-15 release cycle.

**Comment by TomBobach** [comment]
Excellent, thank you for the quick reply!

From: Nathan James ***@***.***>
Sent: Monday, August 22, 2022 6:37 AM
To: llvm/llvm-project ***@***.***>
Cc: Tom Axel Bobach ***@***.***>; Comment ***@***.***>
Subject: [EXT] Re: [llvm/llvm-project] NOLINTBEGIN & NOLINTEND not working on Windows (Issue #55268)

Sie erhalten nicht oft eine E-Mail von ***@***.******@***.***>. Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>

This is a server side issue in clangd that has been fixed, it should be all good in the llvm-15 release cycle.

-
