### ISSUE TITLE
vectorisation of divisions gives division-by-zero

### ISSUE THREAD

**Issue by TijlCoosemans** [llvm/llvm-project#55267]
The following C code crashes on x86_64 when compiled with "clang13 -O2". The resulting binary uses a divps instruction that does 4 divisions when the code only contains 2. It seems LLVM initialises the unused vector elements in the divisor with zero leading to a division-by-zero exception. Perhaps it should initialise them to one.
```C
#include <fenv.h>

typedef float v4float __attribute__((vector_size(16),aligned(16)));

v4float a = { 5, 5, 5, 5 };

int main(void) {
        feenableexcept(FE_DIVBYZERO);
        a[0] /= 3;
        a[1] /= 3;
        return(0);
}
```

**Comment by efriedma-quic** [comment]
Calling feenableexcept() has undefined behavior unless you specify `-ffp-model=strict` or equivalent.  See https://clang.llvm.org/docs/UsersManual.html#controlling-floating-point-behavior .

**Comment by efriedma-quic** [comment]
Currently, I think we do very few vector optimizations in -ffp-model=strict mode.  If that matters to you, please file a new bug with an appropriate title.
