### ISSUE TITLE
llvm.dbg.value left out by IndVarSimplify

### ISSUE THREAD

**Issue by apolloww** [llvm/llvm-project#55276]
During `sinkUnusedInvariants` step in `IndVarSimplify` pass, it is possible that `llvm.dbg.value` is left out after loop invariant value is sunk into exit block. For example, if I debugify this test https://github.com/llvm/llvm-project/blob/main/llvm/test/Transforms/IndVarSimplify/sink-from-preheader.ll

```shell
opt -debugify -indvars -indvars-predicate-loops=0 -check-debugify -S llvm/test/Transforms/IndVarSimplify/sink-from-preheader.ll
```

It produces

```llvm
; ModuleID = '../llvm-project/llvm/test/Transforms/IndVarSimplify/sink-from-preheader.ll'
source_filename = "../llvm-project/llvm/test/Transforms/IndVarSimplify/sink-from-preheader.ll"
target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:128:128"
target triple = "i386-apple-darwin10.0"

define i32 @test(i32 %a, i32 %b, i32 %N) !dbg !5 {
entry:
  call void @llvm.dbg.value(metadata i32 %add, metadata !9, metadata !DIExpression()), !dbg !15
  br label %loop, !dbg !16

loop:                                             ; preds = %loop, %entry
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ], !dbg !17
  call void @llvm.dbg.value(metadata i32 %iv, metadata !11, metadata !DIExpression()), !dbg !17
  %iv.next = add nuw nsw i32 %iv, 1, !dbg !18
  call void @llvm.dbg.value(metadata i32 %iv.next, metadata !12, metadata !DIExpression()), !dbg !18
  %cmp = icmp slt i32 %iv.next, %N, !dbg !19
  call void @llvm.dbg.value(metadata i1 %cmp, metadata !13, metadata !DIExpression()), !dbg !19
  br i1 %cmp, label %loop, label %exit, !dbg !20

exit:                                             ; preds = %loop
  %add = add i32 %a, %b, !dbg !15
  ret i32 %add, !dbg !21
}

; Function Attrs: nocallback nofree nosync nounwind readnone speculatable willreturn
declare void @llvm.dbg.value(metadata, metadata, metadata) #0

attributes #0 = { nocallback nofree nosync nounwind readnone speculatable willreturn }

!llvm.dbg.cu = !{!0}
!llvm.debugify = !{!2, !3}
!llvm.module.flags = !{!4}

!0 = distinct !DICompileUnit(language: DW_LANG_C, file: !1, producer: "debugify", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
!1 = !DIFile(filename: "../llvm-project/llvm/test/Transforms/IndVarSimplify/sink-from-preheader.ll", directory: "/")
!2 = !{i32 7}
!3 = !{i32 4}
!4 = !{i32 2, !"Debug Info Version", i32 3}
!5 = distinct !DISubprogram(name: "test", linkageName: "test", scope: null, file: !1, line: 1, type: !6, scopeLine: 1, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !8)
!6 = !DISubroutineType(types: !7)
!7 = !{}
!8 = !{!9, !11, !12, !13}
!9 = !DILocalVariable(name: "1", scope: !5, file: !1, line: 1, type: !10)
!10 = !DIBasicType(name: "ty32", size: 32, encoding: DW_ATE_unsigned)
!11 = !DILocalVariable(name: "2", scope: !5, file: !1, line: 3, type: !10)
!12 = !DILocalVariable(name: "3", scope: !5, file: !1, line: 4, type: !10)
!13 = !DILocalVariable(name: "4", scope: !5, file: !1, line: 5, type: !14)
!14 = !DIBasicType(name: "ty8", size: 8, encoding: DW_ATE_unsigned)
!15 = !DILocation(line: 1, column: 1, scope: !5)
!16 = !DILocation(line: 2, column: 1, scope: !5)
!17 = !DILocation(line: 3, column: 1, scope: !5)
!18 = !DILocation(line: 4, column: 1, scope: !5)
!19 = !DILocation(line: 5, column: 1, scope: !5)
!20 = !DILocation(line: 6, column: 1, scope: !5)
!21 = !DILocation(line: 7, column: 1, scope: !5)
```

Even though `-check-debugify` is OK with the result, I find it strange that the `llvm.dbg.value` in `entry` block associates the source variable with a non-existing value. I think it should be set to "undef" and another `llvm.dbg.value` should be created (a copy of the first one) after `%add` in `exit` block to reflect the new value.

### More context:
I am facing a verifier failure in `CoroSplit` pass trigged by this.

Before `IndVarSimplify`:

```llvm
preheader:
  %shr.i.i1076 = lshr i64 %316, 24, !dbg !84650
  %or.i.i1077 = or i64 %shr.i.i1076, 128, !dbg !84650
  call void @llvm.dbg.value(metadata i64 %or.i.i1077, metadata !84646, metadata !DIExpression()), !dbg !84647
  ... ...
  
loop:
 ... ...
 
exit:
 ... ...
```

After `IndVarSimplify`:

```llvm
preheader:
  %shr.i.i1076 = lshr i64 %316, 24, !dbg !84650
  call void @llvm.dbg.value(metadata i64 %or.i.i1077, metadata !84646, metadata !DIExpression()), !dbg !84647
  ... ...
  
loop:
 ... ...
 
exit:
  %or.i.i1077 = or i64 %shr.i.i1076, 128, !dbg !84650
  ... ...
```

After `coro::buildCoroutineFrame` and spilling materializable instructions across suspension points

```llvm
preheader:
... ...
  %or.i.i10772788 = or i64 %shr.i.i1076, 128, !dbg !88824
  %shr.i.i1076 = lshr i64 %272, 24, !dbg !88803
  call void @llvm.dbg.value(metadata i64 %or.i.i10772788, metadata !84646, metadata !DIExpression()), !dbg !84647
  ... ...
  
exit:
  %or.i.i1077 = or i64 %shr.i.i1076, 128, !dbg !84650
  ... ...
```

`%or.i.i1077` is sunk into exit block but its `llvm.dbg.value` is left out. When building coro frame, materializable instructions are reconstructed. `%or.i.i1077` is reconstructed at the beginning of the block containing its user `llvm.dbg.value`: https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/Coroutines/CoroFrame.cpp#L2675. This triggers an assert

```console
Instruction does not dominate all uses!
  %shr.i.i1076 = lshr i64 %272, 24, !dbg !88803
  %or.i.i10772788 = or i64 %shr.i.i1076, 128, !dbg !88824
``` 

Even though I think the spilling code can be improved in this case, `IndVarSimplify` is where things go wrong.

**Comment by jmorse** [comment]
Thanks for the detailed report -- do I understand correctly that the root problem is:
 1) A dbg.value is a use-before-def in an early block,
 2) CoroSplit tries to reconstruct some values to support the dbg.value, after splitting the function,
 3) That causes a use-before-def in "real" instructions.

Item 2 is the part I'm least certain of. If that is what happening, then that would mean we could get different code generated when `-g` is passed to the compiler, and that's a good enough reason to not rematerialize values for the dbg.value. There are already short-circuits in the verifier and similar to avoid checking things for debug uses, plus debug uses don't keep instructions alive when they have no users.

Stepping back a bit, there are at least two approaches we can take with debug-info use-before-defs,
  1) As you suggest, make them `undef`, and sink a dbg.value to the location where the value is now defined,
  2) Tolerating and ignoring use-before-defs

I have a preference for option 2, ignoring use-before-defs wherever possible, without letting them affect the rest of compilation. The reason why is is that if we create a new dbg.value, it might cross the dominance frontier of the old (use-before-def) dbg.value. Working out when that happens is hard, would need to be checked often, and getting it wrong leads to variable values being presented out-of-order.

That being said, other parts of LLVM do this, I don't know that everyone agrees with me on this.

**Comment by apolloww** [comment]
Thanks for the suggestions! 

I tried same compilation with no debug info (`-g0`) and this time it passes, so this does affect codegen.

As for the fix, I agree that option #1 needs more work. I also feel that dbg.value placements are not strictly enforced in general. Even fixing it in `IndVarSimplify` does not make the problem completely go away. 

cc: @ChuanqiXu9

**Comment by ChuanqiXu9** [comment]
I agree that it is bad if the code generated is different when `-g` is enabled. I've removed the code to rematerialize values for dbg.value in CoroSplit: https://github.com/llvm/llvm-project/commit/2d037873a35798319c51c1acf222efc483b34776 (It is not covered by test even. My bad).

@apolloww given that we don't think the use-before-def of dbg.value is not an error. I think the issue should be addressed.

**Comment by apolloww** [comment]
Thanks for the fix! I'll see if I can reduce a test case from the crash.

**Comment by ChuanqiXu9** [comment]
Is this OK to close?

**Comment by fhahn** [comment]
@apolloww could you confirm if this issue can be closed?
