### ISSUE TITLE
Half type not declared if opencl-c-base.h and -fdeclare-opencl-builtins is used with clang

### ISSUE THREAD

**Issue by karolherbst** [llvm/llvm-project#55275]
This is required to get `half` `vstore` and `vload` variants exposed as those do not require `cl_khr_fp16`. I've written a draft patch, but I think this causes multiple other issues:
1. half vectors get defined, which are part of `cl_khr_fp16`
2. math functions, which are part of `cl_khr_fp16` as well.

Any ideas how how we can fix this issue? I'd really like to use `opencl-c-base.h` and `-fdeclare-opencl-builtin` inside mesa as it speeds up compilation of OpenCL C sources a lot, but it makes the `half` OpenCL CTS test fail.

A potential workaround is to define them downstream, but I think this should be fixed in llvm

my patch is here: https://github.com/karolherbst/llvm-project/commit/2b17270e1790e198167fa06f4630e93bde9d519d

**Comment by svenvh** [comment]
> This is required to get `half` `vstore` and `vload` variants exposed as those do not require `cl_khr_fp16`.

Presumably this affects only the `vload_half*` and `vstore_half*` builtins?

> Any ideas how how we can fix this issue?

One solution I can think of is to define an additional `HalfPtr` type that does not carry any extension in `OpenCLBuiltins.td` and use that for the `vload_half*` and `vstore_half*` builtins.  Then you can leave the `Half` type untouched.

> I'd really like to use `opencl-c-base.h` and `-fdeclare-opencl-builtin` inside mesa as it speeds up compilation of OpenCL C sources a lot

Glad to see you're taking the time to look at this now, as we're planning to deprecate the large monolithic header (see [RFC](https://discourse.llvm.org/t/rfc-deprecation-timeline-for-opencl-c-h/61585)).

> I think this should be fixed in llvm

Agreed.

**Comment by karolherbst** [comment]
> > This is required to get `half` `vstore` and `vload` variants exposed as those do not require `cl_khr_fp16`.
> 
> Presumably this affects only the `vload_half*` and `vstore_half*` builtins?
> 

well, and all variants, including e.g. `vloada_half` and all the ones with explicit rounding modes.

> > Any ideas how how we can fix this issue?
> 
> One solution I can think of is to define an additional `HalfPtr` type that does not carry any extension in `OpenCLBuiltins.td` and use that for the `vload_half*` and `vstore_half*` builtins. Then you can leave the `Half` type untouched.
> 

there are actually some restrictions on the half type used without the `fp16` extension, as it's only legal to create a pointer to it. From the spec: "The half data type can only be used to declare a pointer to a buffer that contains half values.". It's not even legal to dereference the pointer as you can't create a `half` value on the stack or something.

Sadly I have close to 0 knowledge about tablegen :) I just wrote the quick patch to verify the issue is indeed inside the tablegen file.

> > I'd really like to use `opencl-c-base.h` and `-fdeclare-opencl-builtin` inside mesa as it speeds up compilation of OpenCL C sources a lot
> 
> Glad to see you're taking the time to look at this now, as we're planning to deprecate the large monolithic header (see [RFC](https://discourse.llvm.org/t/rfc-deprecation-timeline-for-opencl-c-h/61585)).
> 
> > I think this should be fixed in llvm
> 
> Agreed.

**Comment by karolherbst** [comment]
> > Sadly I have close to 0 knowledge about tablegen :) I just wrote the quick patch to verify the issue is indeed inside the tablegen file.
> 
> I won't be able to have a go at this until a week from now or so, but a basic patch could look like this: define a `HalfPtr` type just like `Half` (but without any extensions). Then replace all uses of `Half` with `HalfPtr` in the `VloadVstoreHalf` multiclass. If I'm not mistaken, all of the "offending" vstore/vload_half builtins (including all variants) are defined using that multiclass.

I think one thing which I wasn't explicit enough about is, that this only needs to be done for the scalar `Half`. All the vector variants are gated by `cl_khr_fp16`.

**Comment by svenvh** [comment]
@karolherbst I have put up a patch: https://reviews.llvm.org/D125401
This aligns the vload/vstore builtin guards from `-fdeclare-opencl-builtins` with `opencl-c.h`.
Please let me know if this solves the issue for you.

> one thing, which I think I wasn't explicit enough about, is that this only needs to be done for the scalar `Half`. All the vector variants are gated by `cl_khr_fp16`.

The `VloadVstoreHalf` multiclass only defines the vload/vstore builtins that have "_half" in their name, which should all be available without the extension as far as I can see, and that's what [D125401](https://reviews.llvm.org/D125401) should fix.  That includes scalar and vector variants (e.g. `vload_half4`).

**Comment by karolherbst** [comment]
> @karolherbst I have put up a patch: https://reviews.llvm.org/D125401 This aligns the vload/vstore builtin guards from `-fdeclare-opencl-builtins` with `opencl-c.h`. Please let me know if this solves the issue for you.
> 
> > one thing, which I think I wasn't explicit enough about, is that this only needs to be done for the scalar `Half`. All the vector variants are gated by `cl_khr_fp16`.
> 
> The `VloadVstoreHalf` multiclass only defines the vload/vstore builtins that have "_half" in their name, which should all be available without the extension as far as I can see, and that's what [D125401](https://reviews.llvm.org/D125401) should fix. That includes scalar and vector variants (e.g. `vload_half4`).

cool, thanks for that! And yeah.. the vector variants of the functions need to be there without the extension, but not the vector types.

And the patch indeed seems to fix this issue.
