### ISSUE TITLE
LLVM is not built with curl support on apt.llvm.org

### ISSUE THREAD

**Issue by russelltg** [llvm/llvm-project#55289]
It would be awesome to get the new LLVM_ENABLE_CURL=ON flag for the packages from apt.llvm.org. Is this possible?

Happy to help if someone gives me some guidance, but I assume this is something only @sylvestre can do. 

(this should have the packaging label, but I can't add it)

**Comment by sylvestre** [comment]
Sure, I will have a look

**Comment by sylvestre** [comment]
So, I tried with -DLLVM_ENABLE_CURL=FORCE_ON (and with =ON) and 
`ldd debian/tmp/usr/bin/llvm-debuginfod-find-14|grep curl`
doesn't return anything

And, despite being in verbose mode, the following command only mention curl in the _configure_
```
$  grep curl foo.log
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.82.0")  
-- Looking for curl_easy_init
-- Looking for curl_easy_init - found

```

Any patch I should cherry-pick from main => 14?

**Comment by russelltg** [comment]
Hmm, checking out llvm 14.0.3 and configuring with `cmake ../llvm -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja -DLLVM_ENABLE_CURL=ON` gives. 

```bash
$ ldd ./bin/llvm-debuginfod-find  | grep curl
        libcurl-gnutls.so.4 => /lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f6daf53b000)
```

**Comment by sylvestre** [comment]
oh, i know, i forgot one more time to pass the option to stage2

**Comment by russelltg** [comment]
It seems like this has landed and works great for me! Closing unless I'm missing something
