### ISSUE TITLE
urem+udiv miscompile with global isel on arm64

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#55287]
this is being miscompiled by the arm64 backend with global isel:

```llvm
define i32 @test1(i32 %0) {
  %2 = urem i32 %0, %0
  %3 = udiv i32 %2, %0
  ret i32 %3
}
```
we want it to just return 0 (or something else that always produces 0) but we get:
```console
regehr@john-home:~$ llc foo.ll -o - -global-isel --march=arm64
	.text
	.file	"foo.ll"
	.globl	test1                           // -- Begin function test1
	.p2align	2
	.type	test1,@function
test1:                                  // @test1
	.cfi_startproc
// %bb.0:
	udiv	w0, w0, w0
	ret
.Lfunc_end0:
	.size	test1, .Lfunc_end0-test1
	.cfi_endproc
                                        // -- End function
	.section	".note.GNU-stack","",@progbits
regehr@john-home:~$ 
```

cc @ornata @nunoplopes @ryan-berger @nbushehri @zhengyang92 @aqjune @Hatsunespica

**Comment by nicolas17** [comment]
Testing the original code in compiler explorer:
```llvm
define i32 @test1(i32 %0) {
  %2 = urem i32 %0, %0
  %3 = udiv i32 %2, %0
  ret i32 %3
}
```

LLVM 11 outputs:
```
        udiv    w8, w0, w0
        mul     w8, w8, w0
        subs    w8, w0, w8
        udiv    w0, w8, w0
        ret
```

LLVM 12 outputs:
```
        udiv    w8, w0, w0
        msub    w8, w8, w0, w0
        udiv    w0, w8, w0
        ret
```

I *think* both of these are correct and always result in 0.

LLVM 13 outputs:
```
        udiv    w0, w0, w0
        ret
```
So, it's bisect time...

**Comment by nicolas17** [comment]
Bisect result:

In 4c6ab48fb1149c4f1f1d2953f5d232211b3a6bce, instead of emitting the udiv+msub+udiv posted above, it started failing altogether with `LLVM ERROR: unable to legalize instruction: %2:_(s32), %1:_ = G_UDIVREM %0:_, %0:_ (in function: test1)`.

In ac1647cc805867df95b0c4d271ad20a353ba602c (3986 commits later), it stopped erroring out in the legalizer and started emitting `udiv w0, w0, w0`.

**Comment by ornata** [comment]
cc @TNorthover

**Comment by aemerson** [comment]
https://reviews.llvm.org/D130525 and committed in 5ae0472694f5
