### ISSUE TITLE
SCEV behaves differently between clang-hosted and gcc-hosted

### ISSUE THREAD

**Issue by chapuni** [llvm/llvm-project#55283]
Due to evaluation order in function args.

For example to fix my issue. see; https://github.com/llvm/llvm-project/blob/1f9140064dfbfb0bbda8e51306ea51080b2f7aac/llvm/lib/Analysis/ScalarEvolution.cpp#L14283

Most of differences would not be observable without debug messages, but I have seen difference of object emission in x86-64 regalloc, LoopStrengthReduce.
I will try to make minimal testcase, if required.

Besides of the expression above, I saw bunch of implementation-dependent evaluation order around SCEV.
I will check up and report them when I have time.

They should be serialized not to affected by evaluation order, at least in C++14.

**Comment by efriedma-quic** [comment]
This is specifically cases where there are multiple getSCEV() calls in the argument list to a call?  Hopefully that's not too many places.

Ideally, the ordering of calls to getSCEV() shouldn't matter, but it does at the moment, and I don't think there's any straightforward fix.

**Comment by chapuni** [comment]
https://reviews.llvm.org/D125627
