### ISSUE TITLE
[compiler-rt] when __udivmoddi4 function handles the special case where the divisor is 0

### ISSUE THREAD

**Issue by peter-hash** [llvm/llvm-project#55298]
`    /* n.s.high != 0 */
    if (d.s.low == 0)
    {
        if (d.s.high == 0)
        {
            /* K X
             * ---
             * 0 0
             */
            if (rem)
                *rem = n.s.high % d.s.low;
            return n.s.high / d.s.low;
        }
        ...
     }`
In the code, when the divisor is 0, the dividend and the divisor are directly divided. Why? What is the purpose of this? Why is this case not handled in the libgcc code?

**Comment by topperc** [comment]
I think it's there to trigger a divide by 0 exception.

**Comment by peter-hash** [comment]
> I think it's there to trigger a divide by 0 exception.

I see. Thank you for your answer.
