### ISSUE TITLE
Is there any way to disable Position-independent Code?

### ISSUE THREAD

**Issue by GoodNameGoodGit** [llvm/llvm-project#55290]
My clang version: 
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: arm64-apple-darwin21.4.0

I am trying to build Dynamic Shared Objects with command `clang -shared -o Lib.so Lib.c`. After that, I use `objdump -h Lib.so` to check if there is ".got" section. And I get result showing below.
![image](https://user-images.githubusercontent.com/29964492/166985438-58d49849-5a5d-479c-960d-f5c07b277429.png)
Obviously, there is a ".got" section. But I think there may be no ".got" if I use '-shared' without '-fPIC'. And I also try the command `clang -shared -fno-PIC -o Lib.so Lib.c`. Then, the same result I get.

So is there something(or options) I have missed?

**Comment by efriedma-quic** [comment]
If you want to avoid GOT relocations for some particular symbol, you can mark it visibility "hidden", using an attribute or pragma.

ARM64 Darwin is always treated as PIC, no matter what you pass on the command-line.  See https://github.com/llvm/llvm-project/blob/5140e0d219be490930810778a6dcc63fbe72eac2/llvm/lib/Target/AArch64/AArch64TargetMachine.cpp#L265 .  As far as I know, Apple OSes doesn't really have any support for any other relocation model.  So I'm not sure what you would do with a pure "static" mode.  You could build baremetal MachO binaries, I guess?

**Comment by GoodNameGoodGit** [comment]
> 

Thank you! I just want to know why there is always a GOT section. I learnt from book(using gcc) that code will be treated as PIC when using param "-fPIC".
