### ISSUE TITLE
ABI version 2 C++98/03 support

### ISSUE THREAD

**Issue by tambry** [llvm/llvm-project#55302]
In #55064 it was discovered that libc++ ABI version 2 accidentally lost pre-C++11 support. @philnik777 fixed it in 6b257af82261a526b79c0e65c8eed073e916e711.

The affected CMake tests [were updated to not use C++98](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7206). However, if libc++ ABI version 2 doesn't plan to support older language modes CMake needs to be updated to serve an error to users of ABI version 2 when compiling in non-supported modes, rather than failing during compilation.

What is the stance on C++98/03 support for libc++ ABI version 2?

**Comment by ldionne** [comment]
The ABI version should be orthogonal to the C++ Standards we support. We should support all (supported) standard versions with all (supported) ABI versions. I don't think this issue requires any change since this should be the case right now, but please reopen in case that's incorrect.
