### ISSUE TITLE
Please backport scalable-vector instcombine fix

### ISSUE THREAD

**Issue by frasercrmck** [llvm/llvm-project#55307]
LLVM 14 enhanced some bitwise select optimizations but in doing so introduced new crashes on scalable vectors.

7bad1d281c79 adds an extra test
bafab9c09f68 fixes the crash

CC @rotateright

**Comment by rotateright** [comment]
We don't actually require adding the extra test, but let's see if this works:
/cherry-pick 7bad1d281c798929ae bafab9c09f68

**Comment by tstellar** [comment]
Merged: 39e909731a11 0108630f8bc5
