### ISSUE TITLE
Wdocumentation-pedantic fails to handle \n newline in a description

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#55319]
https://clang.godbolt.org/z/fqncE8MT6

We can use ```<br>``` to start a newline in a description, but ```\n``` gives a warning:
```cpp
/// Test function
/// \returns Value<br>
///          second line
int foo();

/// Another test function
/// \returns Value\n
///          second line
int bar();
```

```console
 warning: unknown command tag name [-Wdocumentation-unknown-command]
/// \returns Value\n
```
CC'ing @aaronpuchert as this will hopefully just be a minor extension to https://reviews.llvm.org/D111190

**Comment by aaronpuchert** [comment]
We don't have the concept of a zero-argument command yet, but I guess it would be easy to introduce. There are other commands that take no argument but that I treated as `VerbatimLineCommand` because they're typically on a line of their own (like `\private`).

**Comment by RKSimon** [comment]
Thanks @aaronpuchert - this is the only remaining blocker for #35297 - unfortunately we can't easily replace ```\n``` with ```<br>``` in the code snippets included in the headers without causing issues downstream

**Comment by aaronpuchert** [comment]
I'll have a look. We actually have a couple of `\n` in our code base as well, and it should be low-hanging fruit.

**Comment by RKSimon** [comment]
Thanks for the fast turnaround @aaronpuchert !
