### ISSUE TITLE
Attributes with a self type parameter cannot use declarative assembly

### ISSUE THREAD

**Issue by stellaraccident** [llvm/llvm-project#55324]
In the test dialect, we have a self-type attribute:

```
// An attribute testing AttributeSelfTypeParameter.
def AttrWithSelfTypeParam : Test_Attr<"AttrWithSelfTypeParam"> {
  let mnemonic = "attr_with_self_type_param";
  let parameters = (ins AttributeSelfTypeParameter<"">:$type);
  let hasCustomAssemblyFormat = 1;
}
```

This prints as:

```
#test<"attr_with_self_type_param i32">
```

It was noted on https://reviews.llvm.org/D124318 that when using declarative assembly, we should not include the self type, but it is unclear what else to do. As an example:

```
def MLProgram_ExternAttr : MLProgram_Attr<"Extern"> {
  let parameters = (ins AttributeSelfTypeParameter<"">:$type);
  let mnemonic = "extern";
  let assemblyFormat = "`<` $type `>`";
}
```

This does indeed work and prints as `#ml_program.extern<i32>`. What I really want is something like the builtin syntax: `#ml_program.extern : i32` but that appears impossible with either declarative or custom printer/parser.

Can we confirm that the above is WAI, and if so, add a corresponding test case to the test dialect showing use of custom assembly with a self type attribute. Separately, can we confirm that the prettier format I really want cannot be done?

**Comment by Mogball** [comment]
fixed in https://reviews.llvm.org/D125724
