### ISSUE TITLE
[mlir] ODS useDefaultAttributePrinterParser does not seem to generate declarations

### ISSUE THREAD

**Issue by stellaraccident** [llvm/llvm-project#55322]
Encountered on [D124318](https://reviews.llvm.org/D124318#inline-1199257), it seems insufficient to just set `useDefaultAttributePrinterParser` on its own. This results in a compiler error like:

```
In file included from /home/stella/src/llvm-project/mlir/lib/Dialect/MLProgram/IR/MLProgramDialect.cpp:22:
tools/mlir/include/mlir/Dialect/MLProgram/IR/MLProgramAttributes.cpp.inc:99:37: error: out-of-line definition of 'parseAttribute' does not match any declaration in 'mlir::ml_program::MLProgramDialect'
::mlir::Attribute MLProgramDialect::parseAttribute(::mlir::DialectAsmParser &parser,
                                    ^~~~~~~~~~~~~~
tools/mlir/include/mlir/Dialect/MLProgram/IR/MLProgramAttributes.cpp.inc:117:24: error: out-of-line definition of 'printAttribute' does not match any declaration in 'mlir::ml_program::MLProgramDialect'
void MLProgramDialect::printAttribute(::mlir::Attribute attr,
```

The workaround (which seems to have been done a couple of times I found in downstreams) is to explicitly declare:

```
  let extraClassDeclaration = [{
  private:
    Attribute parseAttribute(DialectAsmParser& parser, Type type) const override;
    void printAttribute(Attribute attr, DialectAsmPrinter& p) const override;

  public:
  }];
```

**Comment by Mogball** [comment]
This happens because `DialectGen` will check for dialect attributes and that `useDefaultAttributePrinterParser` is set. However, if `mlir-tblgen` doesn't see the attribute definitions, e.g. if they are defined in a separate file, then it doesn't generate the definitions.

**Comment by Mogball** [comment]
Fixed in https://reviews.llvm.org/D125809. Now setting the flag will always result in the declarations being generated.
