### ISSUE TITLE
llvm-as: XXXXX.ll: error: expected top-level entity

### ISSUE THREAD

**Issue by huang-shi-hang** [llvm/llvm-project#55326]
LLVM version 3.8.0, use on docker , I create a linux continer 
**Linux 41a5595c1848 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux**
 Get llvm by **apt-get install llvm**  

I meet a peoblem that when I use the command:
```shell
llvm-as test.ll -o test.bc
```
then I get the error:
```shell
llvm-as: test.ll:2:1: error: expected top-level entity
source_filename = "test.c"
```
I don't Konw how to solve it, and test.c is  simaple.
```c
#include <stdio.h>
int main(){
        printf("Hello World!");
		return 0;
}
```

**Comment by EugeneZelenko** [comment]
3.8.0 is very ancient version. Does same problem exist in 14 and `main`?

**Comment by huang-shi-hang** [comment]
> 3.8.0 is very ancient version. Does same problem exist in 14 and `main`?

It works.I've upgraded it, I didn't specify the version when I first downloaded it. Thanks very much.
