### ISSUE TITLE
Infinite loop in compiler after commit 115c1888077ceff05b827a1b254d24abd6ee2b41

### ISSUE THREAD

**Issue by dyung** [llvm/llvm-project#55345]
One of our internal tests started failing with the compiler timing out and I bisected it back to commit 115c1888077ceff05b827a1b254d24abd6ee2b41. I have reduced the code to the following:
```C
void init(void *data, unsigned size) {
  unsigned char *bytes = (unsigned char *)data;
  for (unsigned i = 0; i != size; ++i)
    bytes[i] = i;
}
typedef char schar;
typedef short __attribute__((ext_vector_type(4))) short4;
typedef schar __attribute__((ext_vector_type(32))) schar32;
typedef short __attribute__((ext_vector_type(16))) short16;
typedef union {
  short4 a;
  long b;
} union_short4_long;
typedef union {
  schar32 a;
  short16 b;
} union_schar32_short16;
long test24_id5239;
void test24() {
  union_schar32_short16 id5231;
  short16 id5233{4};
  union_short4_long id5236;
  init(&test24_id5239, sizeof(test24_id5239));
  id5236.b = test24_id5239;
  short16 id5234 = __builtin_shufflevector(id5236.a, id5236.a, 4, 7, 7, 5, 3, 2,
                                           3, 5, 7, 1, 1, 1, 6, 2, 1, 0);
  short16 id5232(id5233 | id5234);
  id5231.b = id5232;
  volatile schar32 id5230(id5231.a);
}
```
If compiled with `-mavx` and optimizations enabled (`-O2`), with a compiler built from the previous commit 4236a10717013b00f16811fcacb538ea8dc082ea, the compilation completes in a fraction of a second.

If the same compilation is repeated with a compiler built from 115c1888077ceff05b827a1b254d24abd6ee2b41, the compilation runs seemingly forever. Our automation kills the compile after 2 minutes automatically.

Compile command line: `clang -c -O2 -mavx test.cpp -o test.o`.

@davemgreen, can you take a look?

**Comment by mikaelholmen** [comment]
I've also bisected a case of (seemingly) infinite execution to this patch.
llc -march=x86-64 -mcpu=corei7 -o /dev/null foo.ll

[foo.ll.gz](https://github.com/llvm/llvm-project/files/8649357/foo.ll.gz)
The input was generated by llvm-stress.

**Comment by davemgreen** [comment]
Thanks, I'll take a look.

**Comment by RKSimon** [comment]
Its likely that x86 shuffle combining is fighting it somewhere.
