### ISSUE TITLE
Unexpected overflow of a long variable

### ISSUE THREAD

**Issue by danolivo** [llvm/llvm-project#55344]
I wanted to avoid overflow during conversion double -> long, but found an unexpected behaviour. Minimal example:
```
#include "math.h"
#include "stdio.h"
#define Min(x, y)		((x) < (y) ? (x) : (y))
int
main()
{
	long lg;
	double dg = 1.E+23;
	lg = (long) Min(dg, (double) __LONG_MAX__);
	printf("Result: lg=%ld\n", lg);
	return 0;
}
```

Compiling with gcc I see:
Result: lg=9223372036854775807

but with clang:
Result: lg=-9223372036854775808

Why casting of LONG_MAX increases the value by 1?

P.S.
```
clang -v
Homebrew clang version 13.0.1
Target: x86_64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```

P.P.S.
It looks like https://github.com/openvinotoolkit/openvino/issues/7469

**Comment by topperc** [comment]
`(double)LONG_MAX` can't be represented exactly in a double so it needs to be rounded to fit. It rounds to 9223372036854775808 which is LONG_MAX+1.

**Comment by danolivo** [comment]
I see. But why gcc do it in more expected manner?

Moreover,
``` lg = (long) ((double)(__LONG_MAX__-1));```
gives 4706750480
``` lg = (long) ((double)(__LONG_MAX__-1));```
gives 4682440720

INT_MAX haven't such problem, gcc too.

**Comment by topperc** [comment]
Because `(double)__LONG_MAX__` rounded to a value larger than `__LONG_MAX__`, the result of `Min(dg, (double) __LONG_MAX__)` will also be larger than `__LONG_MAX__`. Casting that value to `long` is undefined behavior.

You can enable -fsantize=undefined to get an error for the undefined behavior https://godbolt.org/z/853v11z8G

**Comment by danolivo** [comment]
Thank You for the explanation!
