### ISSUE TITLE
GVN miscompilation

### ISSUE THREAD

**Issue by aeubanks** [llvm/llvm-project#55343]
Reduced test case (uncovered with opaque pointers + PGO) from [here](https://crsrc.org/c/third_party/re2/src/re2/parse.cc;drc=519a2a94bc630eb856ca50ec6d1dc8dee4d795b3;l=2219).

Running GVN on [this](https://gist.github.com/aeubanks/d4562b9909612e9e15b54ea319020853) gives [this](https://gist.github.com/aeubanks/0df3eec10f45d58e40f53e4607a87712) where `%tmp57 = load i64, ptr %tmp22, align 4` is wrong. It should be a `load i64, ptr %tmp3` instead.

**Comment by aeubanks** [comment]
Seems related to https://reviews.llvm.org/D95543.
@nikic @dfukalov

**Comment by aeubanks** [comment]
This has to do with `AliasResult::getOffset()` returning 4 when it should be returning -4. Something is incorrectly getting/not getting swapped.

**Comment by aeubanks** [comment]
I believe this is fixed with https://github.com/aeubanks/llvm-project/commit/dc08b9ebcb79efc9d28a1100290f44d1755532f0. Still need to add test cases and audit other similar call sites.

**Comment by nikic** [comment]
Nice find!
