### ISSUE TITLE
Please backport the HIP include path fix

### ISSUE THREAD

**Issue by cgmb** [llvm/llvm-project#55341]
The /usr include path problem is a significant issue preventing the distro packaging of HIP, but the change to fix it is quite small. See also [Debian bug #1010467](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010467). 

/cherry-pick 6730b44480fcce18bfbbae0c46719250e9eae425

**Comment by cgmb** [comment]
Ah. I didn't understand how this works. My apologies. This is my first LLVM issue, so please bear with me. The cherry-pick failed because this issue would first need to be added to the LLVM 14.0.4 Release milestone.

**Comment by cgmb** [comment]
Thank you! Let's try that cherry-pick again.

/cherry-pick 6730b44480fcce18bfbbae0c46719250e9eae425

**Comment by tstellar** [comment]
@Artem-B Is this safe to backport? https://github.com/llvm/llvm-project/commit/6730b44480fcce18bfbbae0c46719250e9eae425

**Comment by Artem-B** [comment]
I believe so. 
@yxsamliu -- FYI.

**Comment by yxsamliu** [comment]
It is safe. no other dependencies.

**Comment by tstellar** [comment]
Merged: cd597588217a
