### ISSUE TITLE
`CLANG_ENABLE_OPAQUE_POINTERS=OFF` does not prevent `Attempting to get element type of opaque pointer` assertion

### ISSUE THREAD

**Issue by illwieckz** [llvm/llvm-project#55366]
The [documentation](https://llvm.org/docs/OpaquePointers.html) says:

> As of April 2022 both LLVM and Clang have complete support for opaque pointers, and opaque pointers are enabled by default in Clang. It is possible to temporarily restore the old default using the -DCLANG_ENABLE_OPAQUE_POINTERS=OFF cmake option.

But I verified in multiple ways this is not true, building clang with `CLANG_ENABLE_OPAQUE_POINTERS=OFF` does not provide previous behaviour.

- Building Mesa (before the Mesa commit passing `-no-opaque-pointers`) was facing #54970 whatever  `CLANG_ENABLE_OPAQUE_POINTERS` is `ON` or `OFF`,  
 see: [mesa/mesa#6342](https://gitlab.freedesktop.org/mesa/mesa/-/issues/6342#note_1372224) _clover: Assertion `NumContainedTys && "Attempting to get element type of opaque pointer"' failed (comment)_.
- Using llvm-spriv compiled against clang is facing the same problem whatever clang was built with `CLANG_ENABLE_OPAQUE_POINTERS` set to `ON` or `OFF`,
  see: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/1444#issuecomment-1122045927

**Comment by nikic** [comment]
Do mesa / llvm-spir make use of the driver or the cc1 interface? CLANG_ENABLE_OPAQUE_POINTERS affects whether the driver passes `-no-opaque-pointers` to cc1. If they're using cc1, then they need to pass `-no-opaque-pointers` to the cc1 invocation.

**Comment by nikic** [comment]
I've committed https://github.com/llvm/llvm-project/commit/3d888b0491f899d5255653eb2f294c38248a4fc9 to clarify the behavior wrt cc1.

**Comment by illwieckz** [comment]
> Do mesa / llvm-spir make use of the driver or the cc1 interface? CLANG_ENABLE_OPAQUE_POINTERS affects whether the driver passes `-no-opaque-pointers` to cc1. If they're using cc1, then they need to pass `-no-opaque-pointers` to the cc1 invocation.

I don't know but for Mesa I worked it around by making Mesa pass `-no-opaque-pointers` on invocation (I don't know the rest of the Mesa code so I don't know how it is interfaced):

- https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/16129/diffs

On mean term the Mesa code would have to be ported to opaque pointers, but this simple trick made Mesa building again without being too-much intrusive on Mesa code.

Note: I've noticed writing `-Xclang -no-opaque-pointers` instead of `-no-opaque-pointers` in Mesa code makes applications crash, maybe that can help to understand which kind of interface Mesa uses as `-Xclang` seems to not be expected.

**Comment by nikic** [comment]
Based on the linked merge request, mesa is indeed using the cc1 interface.

> Note: I've noticed writing `-Xclang -no-opaque-pointers` instead of `-no-opaque-pointers` in Mesa code makes applications crash, maybe that can help to understand which kind of interface Mesa uses as `-Xclang` seems to not be expected.

Right, `-Xclang` is how you pass options through to cc1 when using the driver interface.

As far as I can tell, there is nothing actionable here on the LLVM side, apart from the documentation update that has already been committed (see https://llvm.org/docs/OpaquePointers.html#transition-state).

**Comment by nikic** [comment]
@illwieckz Opaque pointers are currently enabled by default in Clang, but not in LLVM.

**Comment by illwieckz** [comment]
Ah you're right! That's good then.
