### ISSUE TITLE
LoongArch libunwind support

### ISSUE THREAD

**Issue by kasperk81** [llvm/llvm-project#55398]
Given the nongnu libunwind port on loongarch is completed: https://github.com/libunwind/libunwind/commit/c5f1d12c77dea6a60740730c675fc56b3c52b86a, it should be relatively simpler to port the llvm libunwind (https://github.com/llvm/llvm-project/tree/main/libunwind).

@tangyouling, @SixWeining

**Comment by SixWeining** [comment]
Thanks. We are working on implementing the basic part of the backend. I think it would be better to wait this finish before supporting other sub-projects including clang, lld, compiler-rt, libunwind...

**Comment by MaskRay** [comment]
llvm-project libunwind can be used by libc++/libc++abi, but libc++/libc++abi can use libgcc_s.so.1 as well. If a program does not use C++ exceptions, libunwind is not a critical piece, so I see no reason blocking development of other components on libunwind.

> I think it would be better to wait this finish before supporting other sub-projects including clang, lld, compiler-rt, libunwind...

Speaking of lld, clang driver, builtins part of compiler-rt, etc, I am more curious whether a new port does strange things.

**Comment by SixWeining** [comment]
> Speaking of lld, clang driver, builtins part of compiler-rt, etc, I am more curious whether a new port does strange things.

What does "strange things" mean? Like adding a particular option to clang driver or lld?

**Comment by MaskRay** [comment]
> > Speaking of lld, clang driver, builtins part of compiler-rt, etc, I am more curious whether a new port does strange things.
> 
> What does "strange things" mean? Like adding a particular option to clang driver or lld?

Yes. An example is https://github.com/loongson/LoongArch-Documentation/issues/9 such a relocation resolving design may add significant burden to the linker architecture.

**Comment by kasperk81** [comment]
@SixWeining, thanks for all the work. If some of these components can be worked on in parallel (as @MaskRay has pointed out) that would expedite the overall progress and win for everyone. Case in point, debugger (lldb) support on RISC-V which seems to be stuck: https://github.com/llvm/llvm-project/issues/55383, I hope LoongArch (or any new architecutre for that matter) won't get blocked like that. At the same time i can see how lack of ability to test on bare-metal can be a showstopper for someone porting an important toolchain component such as the debugger, which appears to be the case of RISC-V lldb story.

**Comment by SixWeining** [comment]
> @SixWeining, thanks for all the work. If some of these components can be worked on in parallel (as @MaskRay has pointed out) that would expedite the overall progress and win for everyone. Case in point, debugger (lldb) support on RISC-V which seems to be stuck: #55383, I hope LoongArch (or any new architecutre for that matter) won't get blocked like that. At the same time i can see how lack of ability to test on bare-metal can be a showstopper for someone porting an important toolchain component such as the debugger, which appears to be the case of RISC-V lldb story.

Thanks for your suggestion. But currently we don't have enough people to work on different components in parallel. It would be appreciated if someone in the community could help.

BTW, may I know where do you want to use the llvm libunwind? Does it block your work?
