### ISSUE TITLE
Erroneous optimisation of potentially aliasing assignment to a memcpy

### ISSUE THREAD

**Issue by moon-chilled** [llvm/llvm-project#55399]

**Comment by moon-chilled** [comment]
```c
typedef struct { char b[4096]; } S;
void f(S *x, S *y) { *x = *y; }
```

compiles f to:

```
mov     edx, 4096
jmp     memcpy
```

The use of memcpy is erroneous, as x and y may alias, in which case the use of memcpy is undefined behaviour.

**Comment by DimitryAndric** [comment]
How are you compiling this? What are your exact commando line options?

**Comment by moon-chilled** [comment]
'clang -O2 -c'.  But it happens regardless of optimisation level.

**Comment by nikic** [comment]
LLVM permits llvm.memcpy arguments to either be non-overlapping, or exactly the same (see https://llvm.org/docs/LangRef.html#llvm-memcpy-intrinsic). If you provide your own libcall implementation for memcpy, you also need to follow this rule.
