### ISSUE TITLE
constant propagation can pessimize libcall optimizations.

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#55394]
This case just came up in the context of the Linux kernel.
https://lore.kernel.org/llvm/20220511160319.1045812-2-mailhol.vincent@wanadoo.fr/

Consider the following code:
```c
#define CONST 0x01000000

// try removing static
static unsigned ffs (int x) {
  int r;
  asm("bsfl %1,%0"
      : "=r" (r)
      : "rm" (x), "0" (-1));
  return r;
}

unsigned int foo(void) {
  return ffs(CONST);
}

unsigned int bar(void) {
  return __builtin_ffs(CONST);
}
```
It looks like constprop sinks `CONST` into ffs when ffs is static, but if it wasn't then constprop wouldn't sink CONST.  instcombine will fail to optimize `ffs(CONST)` into 25 since dead arg elimination will remove the parameter after const prop.

cc @fhahn @efriedma-quic 

We're fixing this in the kernel by changing our ffs to dispatch to __builtin_ffs after a __builtin_constant_p check.

**Comment by efriedma-quic** [comment]
If you have a name with internal linkage, no compiler should treat it as a library function.  This is required by the C standard; 7.1.3 says "identifiers with external linkage" are reserved for library functions, but there's no such reservation for names with internal linkage.  The frontend bits of clang handle this correctly... although I guess LLVM optimizations end up violating it in some cases.

Given that, I'm not sure we can do anything here?  I guess we could invent an attribute to override the C standard rule, but not sure that's worth doing.

**Comment by nickdesaulniers** [comment]
Interesting. Thanks for the citation!

It's a common pattern for the kernel to declare functions like ffs as static inline funcitons defined in headers. The kernel is pseudo-freestanding (or "not hosted") but generally provides similar functions with similar semantics that a C library would.

I guess we (kernel) need to keep in this kind of case in mind.
