### ISSUE TITLE
clang-format: PointerAlignment: Right not working with tab indentation.

### ISSUE THREAD

**Issue by ashleypittman** [llvm/llvm-project#55407]
When using PointerAlignment: Right with Tabs then variable names get aligned incorrectly.  This needs a combination of UseTab and PointerAlignment to reproduce, and probably AlignConsecutiveDeclarations as well in order to request the alignment.  It's broken for several values of UseTab, although Never works as expected.

We are also using IndentWidth: 8, without this then UseTab ForIndentation appears to work, at least for first-level indents although UseTab Always is still broken.

Sample input file:
```cpp
struct something_big {
    int value;
};

int main() {
    struct something_big big;
    char *ptr;
    int i;
    return 0;
}
```

Configuration
```yaml
#UseTab: ForIndentation
UseTab: Always
PointerAlignment: Right
AlignConsecutiveDeclarations: true
IndentWidth: 8
```

Observed output, note the incorrect spacing before *ptr.
```cpp
struct something_big {
	int value;
};

int main() {
	struct something_big big;
	char		*ptr;
	int		     i;

	return 0;
}
```

When running with PointerAlignment: Middle we see the output is correct, however this does not match our existing coding style.
```cpp
struct something_big {
  int value;
};

int main() {
  struct something_big big;
  char *	       ptr;
  int		       i;

  return 0;
}
```

Verified on `clang-format version 14.0.0 (Fedora 14.0.0-1.fc36)` (fedora 36) and others.

**Comment by mkurdej** [comment]
Confirmed on main.
There's another problem, when using `UseTab: ForIndentation`, we get a tab after `char` in the line:
```
	char	        *ptr;
```

**Comment by mkurdej** [comment]
Revision URI: https://reviews.llvm.org/D125528

**Comment by ashleypittman** [comment]
Thank you.  I'm doing a half-day today but I'll aim to compile and test this Monday.

**Comment by ashleypittman** [comment]
I can confirm that it works as expected with the patch applied.  Thank you very much for a fast turnaround.

**Comment by ashleypittman** [comment]
Is the fix for this in 14.0.4?  I've installed the release today and am still seeing multiple issues.

**Comment by tstellar** [comment]
@mkurdej Is this OK to backport?

**Comment by mkurdej** [comment]
Yes, absolutely!

**Comment by tru** [comment]
Should be fine to backport @tstellar

**Comment by mkurdej** [comment]
@tstellar, this should fix the automatic merge.

**Comment by tru** [comment]
I think that happens when you use the branch flow - it's a limitation in that one right now - @tstellar fixed a similar issue manually before. If you describe it Tom - I can also help out fixing them until the proper fix is in place.

**Comment by tstellar** [comment]
@tru The fix is to copy the branch to the llvm/llvm-project-release-prs repo and then use the new branch for the pull request.
