### ISSUE TITLE
Unused variables when building Bolt without asserts

### ISSUE THREAD

**Issue by tschuett** [llvm/llvm-project#55404]
My Apple Clang is unhappy about a couple unused variables:
```h
bool DataWritten = false;
bool IsTailCall = isTailCall(Inst);
bool Ret = evaluateMemOperandTarget(*Adrp, Base, AdrpPC, InstSize);
BinaryContext &BC = Function.getBinaryContext();
const bool IsCondBranch = MIB->isConditionalBranch(Instruction);
uint8_t Opcode = ExprBytes[0];
bool Valid = true;
bool Found = false;
bool Erased = false;
```

It is really unhappy about common.h. I have feeling there is a `-std=c++14` missing.

**Comment by aaupov** [comment]
Thanks for bug report. I've reproduced the build issue with Apple Clang.

**Comment by tschuett** [comment]
Sorry, but I believe that you missed:
```cpp
bool Found = false;
bool Valid = true;
bool DataWritten = false;
```

**Comment by aaupov** [comment]
c1532ac should fix the build issue. I've tested it with Apple Clang 12.0.0. 
139744a addresses unused variables.
253b8f0ab fixes misc warnings.

**Comment by aaupov** [comment]
> Sorry, but I believe that you missed:
> 
> ```c++
> bool Found = false;
> bool Valid = true;
> bool DataWritten = false;
> ```

Which Xcode/clang version did you use? Can you please provide the full CMake command?

**Comment by aaupov** [comment]
Additionally, da766cea56df4216ee7911c7b1ab5790c1046038 enables testing on MacOS.
The command line I've used is the following:
```
cmake <llvm-project>/llvm -G Ninja -DLLVM_TARGETS_TO_BUILD="X86;AArch64" -DCMAKE_BUILD_TYPE=Release  -DLLVM_ENABLE_PROJECTS="bolt;lld" -DBOLT_CLANG_EXE=`which clang`
ninja check-bolt
```
We don't have macOS buildbots, so check-bolt is not guaranteed to stay green.

**Comment by tschuett** [comment]
variable 'DataWritten' set but not used:
https://github.com/llvm/llvm-project/blob/6f5f847a36af2f2e9dfce4ed99f1a243161c7d5d/bolt/lib/Rewrite/RewriteInstance.cpp#L4018
variable 'Found' set but not used:
https://github.com/llvm/llvm-project/blob/6f5f847a36af2f2e9dfce4ed99f1a243161c7d5d/bolt/lib/Core/BinaryContext.cpp#L803
variable 'Valid' set but not used:
https://github.com/llvm/llvm-project/blob/6f5f847a36af2f2e9dfce4ed99f1a243161c7d5d/bolt/lib/Core/BinaryContext.cpp#L1163

```bash
> clang --version
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: x86_64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by aaupov** [comment]
@tschuett thanks for clarification! Looks like I've used Clang from the wrong xcode installation. Can confirm the warnings now.

**Comment by aaupov** [comment]
Should be addressed now.
