### ISSUE TITLE
llvm.loop metadata incorrectly moved during loop-simplify pass

### ISSUE THREAD

**Issue by hgreving2304** [llvm/llvm-project#55416]
[loop.ll.txt](https://github.com/llvm/llvm-project/files/8683047/loop.ll.txt)
[cfg.dot.txt](https://github.com/llvm/llvm-project/files/8683048/cfg.dot.txt)

When compiling attached boiled down example of code

```
llc ~/loop.ll -o - -print-after-all
```

The loop simplify pass (Canonicalize natural loops (loop-simplify)) IMO moves loop metadata incorrectly: The llvm.loop metadata attached to _bb6's terminator is moved to the new loop exit. I think the reason for this is that the loop exit is a header for another outer loop (see attached dotty graph). I think the loop metadata in this case should stay with the branch of the inner loop.

Error:

br i1 %cmp, label %_bb6, label %.loopexit, !llvm.loop !0

=> (after loop-simplify)

br i1 %cmp, label %_bb6, label %.loopexit.loopexit

**Comment by hgreving2304** [comment]
You might want to consider the following patch

```
diff --git a/third_party/llvm/llvm-project/llvm/lib/Transforms/Utils/BasicBlockUtils.cpp b/third_party/llvm/llvm-project/llvm/lib/Transforms/Utils/BasicBlockUtils.cpp
--- a/google3/third_party/llvm/llvm-project/llvm/lib/Transforms/Utils/BasicBlockUtils.cpp
+++ b/google3/third_party/llvm/llvm-project/llvm/lib/Transforms/Utils/BasicBlockUtils.cpp
@@ -1157,7 +1157,7 @@ SplitBlockPredecessorsImpl(BasicBlock *B
     UpdatePHINodes(BB, NewBB, Preds, BI, HasLoopExit);
   }
 
-  if (OldLatch) {
+  if (L == LI->getLoopFor(OldLatch) && OldLatch) {
     BasicBlock *NewLatch = L->getLoopLatch();
     if (NewLatch != OldLatch) {
       MDNode *MD = OldLatch->getTerminator()->getMetadata("llvm.loop");
```

**Comment by hgreving2304** [comment]
diff --git a/llvm/lib/Transforms/Utils/BasicBlockUtils.cpp b/llvm/lib/Transforms/Utils/BasicBlockUtils.cpp
--- a/google3/third_party/llvm/llvm-project/llvm/lib/Transforms/Utils/BasicBlockUtils.cpp
+++ b/google3/third_party/llvm/llvm-project/llvm/lib/Transforms/Utils/BasicBlockUtils.cpp
@@ -1157,7 +1157,7 @@ SplitBlockPredecessorsImpl(BasicBlock *B
     UpdatePHINodes(BB, NewBB, Preds, BI, HasLoopExit);
   }
 
-  if (OldLatch) {
+  if (L == LI->getLoopFor(OldLatch) && OldLatch) {
     BasicBlock *NewLatch = L->getLoopLatch();
     if (NewLatch != OldLatch) {
       MDNode *MD = OldLatch->getTerminator()->getMetadata("llvm.loop");

**Comment by fhahn** [comment]
Would you be interested in submitting a patch? It would be good to have an IR test case that shows the problem by just running `loop-simplify`

**Comment by hgreving2304** [comment]
Ok, https://reviews.llvm.org/D125574
