### ISSUE TITLE
readability-identifier-naming.StructCase  not working for .c file

### ISSUE THREAD

**Issue by swordjjjkkk** [llvm/llvm-project#55422]
![image](https://user-images.githubusercontent.com/22972430/168254663-286973b1-495c-4748-8167-4e9e4644d997.png)
here is my config file (path /root/config) .
![image](https://user-images.githubusercontent.com/22972430/168254964-515387e7-6f46-4dfc-8bf0-313b2ca634b1.png)
here is my code.

if i use clang-tidy analyze this file ,i got 1 warning,but expect 2 warning.
![image](https://user-images.githubusercontent.com/22972430/168255671-7d12c3ce-380e-4a25-9ecd-41f489075a4d.png)

if i rename file to .cpp , it works right. struct check works.
![image](https://user-images.githubusercontent.com/22972430/168255551-d87dd34c-7aa2-48ee-8405-c1ac974b383f.png)

is that a bug or my mistake ？

**Comment by JonasToth** [comment]
Thank you for reporting this issue.

The check itself is not specific to C++ and should run in C projects as well. Is this the only option, where your C-code is not processed properly?

**Comment by swordjjjkkk** [comment]
YES , only struct check  not work properly，like structcase or structprefix

**Comment by vincent-tr** [comment]
> Just encountered a similar issue on clang-tidy 10 and 14 where `StructPrefix` is basically ignored unless `-- -std=c++11` is added (or any other C++ dialect).

Indeed.
I tried to run clang-tidy using this additional option, it looks like [this one](https://github.com/sasfermat/fermat/pull/184/commits/be3d29b27a2d1fa2adda6317a1a518ed7e681f23) has been found too.
