### ISSUE TITLE
Document clearly that the Code-of-Conduct applies to office hours

### ISSUE THREAD

**Issue by kbeyls** [llvm/llvm-project#55430]

**Comment by tstellar** [comment]
@dwblaikie Some office hours are video calls.

**Comment by dwblaikie** [comment]
> @dwblaikie Some office hours are video calls.
Ah, figured they'd be video chats on LLVM discord, which would be covered by the CoC - but if they're going to be in private/off the LLVM discord, yeah, worth some extra wording.
