### ISSUE TITLE
Can one build a self contained compiler toolchain on macOS with clang/llvm that does not require Xcode/CLT?

### ISSUE THREAD

**Issue by crazyquark** [llvm/llvm-project#55434]
Hi,

I've been trying to do what is stated in the title:
- First I got rid of `ld` so that clang would use its own linker by default(`lld`)
- Then I tried to get rid of `libxar`
- Then I made it so `libcxx` could actually be linked with `lld` (which does not support symbol re-exporting)
- Then I realized that libcxx's headers, some of them, are wrapper headers that use `#include_next <...>` to include system  headers
And this is where I gave up 😄 
My question is: is there, currently a way to build a Clang/llvm toolchain from sources that is independent of Xcode/CommandLineTools being present on the target machine?

**Comment by fhahn** [comment]
For questions, https://discourse.llvm.org is likely a better place.

**Comment by crazyquark** [comment]
thank you, will go there!

**Comment by fhahn** [comment]
> thank you, will go there!

Sounds good!
