### ISSUE TITLE
Cherry-pick global-isel stack protector fix to 14.x

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#55448]
See https://reviews.llvm.org/D125584 .  This patch fixes a miscompile that's very easy to trigger at -O0 on ARM64 Windows.

CC @ornata

**Comment by tstellar** [comment]
@ornata What do you think about backporting this? https://github.com/llvm/llvm-project/commit/96c2a0c9fff24803be14bfaa579e4f230763d3cc

**Comment by ornata** [comment]
This looks fine to me.
