### ISSUE TITLE
FindLibEdit.cmake somehow ignores CMAKE_SYSROOT

### ISSUE THREAD

**Issue by ilovepi** [llvm/llvm-project#55445]
Fuchsia's Clang CI had a breakage due to `FindLibEdit.cmake` incorrectly finding libedit headers in `/usr/include`, despite the fact that our builders set `CMAKE_SYSROOT` explicitly.

This is incorrect because in our build we set `CMAKE_SYSROOT=/b/s/w/ir/x/w/cipd/linux` so CMake shouldn't be looking in paths like `/usr/include`, because at build time Clang will be invoked with `--sysroot=/b/s/w/ir/x/w/cipd/linux` and it won't consider include paths like `/usr/include`.

More details can be found in a short discussion in the change in https://reviews.llvm.org/D124673.

The initial breakage can be found here:  https://luci-milo.appspot.com/ui/p/fuchsia/builders/toolchain.ci/clang-linux-x64/b8814329895908917697/overview

We were able to work around this in our builders for now, but its concerning that the `CMAKE_SYSROOT` may be ignored. 

Looking at `FindLibEdit.cmake` hasn't highlighted anything obviously suspicious. It uses `find_path` and `find_library`, but the [CMake documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSROOT.html) says that the `find_*` set of utilities will prefix their searches with the path set in `CMAKE_SYSROOT`.

Comparing it to other `Find*` utilities (e.g., from kitware) hasn't highlighted anything immediately obvious either.

cc: @petrhosek @MaskRay @upsj Since you were all on the initial discussion.

**Comment by upsj** [comment]
Sorry for the breakage :) Can you post the output of `cmake --debug-find` in the initial config run? I suspect that might tell us more about the search paths it uses.

**Comment by upsj** [comment]
I played around with it a bit, and it seems like both the invocation of pkg_check_modules and find_library search outside the SYSROOT. We could restrict this further with appropriate flags, but would run the risk of breaking other builds.

**Comment by ilovepi** [comment]
Hi, thanks for looking into this. I'm probably not able to do much until monday, but I can try to dig in then.

If the FindLibEdit.cmake violates the SYSROOT searching it's likely to break people in unexpected ways that they won't know about at all. I'm not sure it's better to silently keep them working. Unfortunately, that probably also means we need to audit other cmake pieces to be sure they don't also exhibit this behavior.

As to the underlying issue ... I really have no clue. My knowledge of CMake is functional, but very incomplete, so I'd need to take some time to do anything more than wildly speculate. But if pkg_check_modules adds paths to common variable used by find_library, the I could see how this would happen, despite what's in the documentation. 

There is also the possibility that this is a bug in CMake itself, or we're just using something in an incompatible way that is non-obvious. 

I'll try to loop in someone on my team that is a bit more experienced w/ CMake on Monday to help out.

**Comment by petrhosek** [comment]
The consistency is most important here in my opinion. We should check the behavior of other modules we already use in LLVM like `FindZLIB.cmake` and `FindLibXml2.cmake` and see what's their handling of `CMAKE_SYSROOT` and make sure that `FindLibEdit.cmake` behaves the same way.
