### ISSUE TITLE
[riscv] Miscompile related to frame alignment w/o frame pointer + exception

### ISSUE THREAD

**Issue by preames** [llvm/llvm-project#55442]
Filing this on Keto's behalf.  This got mentioned in private email, and I wanted a tracking issue.  

MultiSource/C++/frame_layout from llvm-testsuite, failed when
-march=rv64gcv -fno-omit-frame-pointer (and yes, that will broken even
no VLS vectorizer enabled!)

This is believed to be related to both exception handling, and frame alignment with RVV objects, but that has not yet been conclusively confirmed.  No reduced test case available at this time.

Here's Kito's brief writeup on his current thinking on the bug.  

I didn't have a small enough reduced case yet, but that's the
situation for this testcase:

```
try {
  sp adjust for outgoing args. # 1. Sp changed.
  func_call  # 2. Exception raised
  sp restore # Oh, not restored
} catch {
  # 3. And now we are here.
}

# 4. Prepare to return!, restore return address from stack, but...sp is wrong.
# 5. Screw up!

```

**Comment by kito-cheng** [comment]
Command line:
`$ clang++ -target riscv64-unknown-linux-gnu  simple.cpp -O -march=rv64gcv -S -fno-omit-frame-pointer -o -`

Reduced case:
```
void foo(int, int, int, int, int, int, int, int, int, int);

bool check_frame_variant() {
  int exception_value = 1;
  try {
      foo(0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
  } catch (int i) {
    exception_value = i;
  }
  return exception_value;
}
```

**Comment by kito-cheng** [comment]
https://reviews.llvm.org/D126861

**Comment by kito-cheng** [comment]
Issue resolved via https://reviews.llvm.org/D126861, but still another issue isn't resolved created another issue to track that https://github.com/llvm/llvm-project/issues/56008.
