### ISSUE TITLE
[LoopVectorizer]  Assertion `!verifyFunction(*L->getHeader()->getP arent(), &dbgs())' failed.

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#55459]
[testcase.tar.gz](https://github.com/llvm/llvm-project/files/8692827/testcase.tar.gz)

clang -march=arch13 -Os crash0.i -w -o a.out

or

opt -S -mtriple=s390x-linux-gnu -mcpu=z15 tc_crash0_aftercreduce.ll -O3 -o /dev/null

Instruction does not dominate all uses!                                                                                                                                                        
  %8 = getelementptr inbounds [2 x i32], ptr @a, i64 0, i64 %7                                                                                                                                 
  %i8.lcssa = phi ptr [ %i8, %bb26 ], [ %8, %middle.block ]         
...
#8 0x000002aa2c8f1bd8 llvm::LoopVectorizePass::processLoop(llvm::Loop*)
...

**Comment by fhahn** [comment]
I think this is the same underlying issue as #51366 and should be fixed by the patch linked there.

**Comment by fhahn** [comment]
Should be fixed by 3bebec6592a4dd8a1fb330382fc8dd4162c6bf44.
