### ISSUE TITLE
[AArch64] Unnecessary round-trip through GPRs after AdvSIMD reduction ops

### ISSUE THREAD

**Issue by rygorous** [llvm/llvm-project#55452]
The ARM intrinsics for the vector reduction ops have a scalar return type, but the actual result is left in SIMD regs, with awkward consequences when these results are actually meant to then feed into further SIMD computations.

Generally, this results in several extra instructions to shuffle the result to GPRs and back, and a corresponding substantial increase in latency. Simple example reproducer for Clang 14.0.0 targeting AArch64 here: https://godbolt.org/z/MoeY4sYob

Ideally, the `fmov` instructions should disappear entirely and the `dup` and `mov`/`ins` should use the corresponding vector register as source.

**Comment by rygorous** [comment]
Ping?

**Comment by davemgreen** [comment]
We have made some improvements here lately and this doesn't seem to be an issue on trunk. https://godbolt.org/z/TcEzs8W8a

Does that match your expectation?

**Comment by rygorous** [comment]
Yeah, that looks good.
