### ISSUE TITLE
clang-format gets confused by attributes on enum classes

### ISSUE THREAD

**Issue by bsilver8192** [llvm/llvm-project#55457]
This:
```c++
enum class [[nodiscard]] C2 {
  // a comment
  A,
  // a comment
  B
};
```
turns into this:
```c++
enum class [[nodiscard]] C2{// a comment
                            A,
                            // a comment
                            B};
```

Also, this:
```c++
enum class [[nodiscard]] X2 {
  A,
  B,
};
```
turns into this:
```c++
enum class [[nodiscard]] X2{
    A,
    B,
};
```

The same `enum class`es without the `[[nodiscard]]` just get reindented to 4 spaces and are otherwise left as-is like I expect.

Tested with clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04 with all default formatting options.

**Comment by mkurdej** [comment]
Revision URI: https://reviews.llvm.org/D125848
