### ISSUE TITLE
readability-braces-around-statements doesn't work on single-line if statements

### ISSUE THREAD

**Issue by kuszmaul** [llvm/llvm-project#55458]
If I write
```c
if (predicate) foo();
```
I don't get a readability-braces-around-statements warning.

If I write

```c
if (predicate) {
  foo();
}
```
I do.

The documentation at https://clang.llvm.org/extra/clang-tidy/checks/readability-braces-around-statements.html says that the default value 0 for `ShortStatementLines` means that braces will be added to all statements not having them already.

I wondered whether I understood the definition of the number-of-lines value for `ShortStatementLines`. I checked and in the second case I get a warning for `ShortStatementLines` set to 1, but not it's set to 2. So it seems like in my first case, the number of lines is in fact 0, and the check ought to be triggered.

**Comment by PiotrZSL** [comment]
Detected:
```
warning: statement should be inside braces [hicpp-braces-around-statements,readability-braces-around-statements]
  if (Predicate) foo();
```

This check got option ShortStatementLines with default value equal to 0, check if you don't have it set to some other value.

**Comment by PiotrZSL** [comment]
Closing as looks to be already fixed (https://godbolt.org/z/r3E7KT8T4) and wrn is produced.
Clang-tidy 15 also produce warning here, so I would assume issue to be in some older version or is related to some other errors in code. If you still run into this issue, please share version of Clang-tidy that you use. And check for other errors.
