### ISSUE TITLE
class llvm::MCObjectFileInfo has no member named initMCObjectFileInfo

### ISSUE THREAD

**Issue by softwaresale** [llvm/llvm-project#55461]
I just recently upgraded from LLVM-13 to LLVM-14. Upon compilation, I got the following error:
```
/usr/lib/llvm-14/include/llvm/MC/TargetRegistry.h: In member function ‘llvm::MCObjectFileInfo* llvm::Target::createMCObjectFileInfo(llvm::MCContext&, bool, bool) const’:
/usr/lib/llvm-14/include/llvm/MC/TargetRegistry.h:396:13: error: ‘class llvm::MCObjectFileInfo’ has no member named ‘initMCObjectFileInfo’; did you mean ‘InitMCObjectFileInfo’?
  396 |       MOFI->initMCObjectFileInfo(Ctx, PIC, LargeCodeModel);
      |             ^~~~~~~~~~~~~~~~~~~~
      |             InitMCObjectFileInfo
```

I am running on Ubuntu 22.04. I installed the packages `llvm-14`, `llvm-14-runtime`, and `llvm-14-dev`.

It seems like the problem is just that the function was misspelled. Should I submit a PR to fix it?
Thanks

**Comment by MaskRay** [comment]
Likely the package that uses llvm does not adapt the `initMCObjectFileInfo` change in https://reviews.llvm.org/D101462 .

This is not a bug in llvm.
