### ISSUE TITLE
[mlir] Canonicalize command-line options don't seem to do anything

### ISSUE THREAD

**Issue by rkayaith** [llvm/llvm-project#55466]
Printing out the config value used in the pass:
```diff
diff --git a/mlir/lib/Transforms/Canonicalizer.cpp b/mlir/lib/Transforms/Canonicalizer.cpp
index cb532746c448..622cd7943478 100644
--- a/mlir/lib/Transforms/Canonicalizer.cpp
+++ b/mlir/lib/Transforms/Canonicalizer.cpp
@@ -51,6 +51,8 @@ struct Canonicalizer : public CanonicalizerBase<Canonicalizer> {
     return success();
   }
   void runOnOperation() override {
+    llvm::dbgs() << "canonicalizer config.useTopDownTraveral = "
+                 << config.useTopDownTraversal << "\n";
     (void)applyPatternsAndFoldGreedily(getOperation()->getRegions(), patterns,
                                        config);
   }
```

The value seems to always be the same no matter what you specify in the options:
```console
$ echo | mlir-opt --canonicalize
canonicalizer config.useTopDownTraveral = 1
module {
}

$ echo | mlir-opt --canonicalize='top-down=false'
canonicalizer config.useTopDownTraveral = 1
module {
}

$ echo | mlir-opt --canonicalize='top-down=true'
canonicalizer config.useTopDownTraveral = 1
module {
}
```

**Comment by rkayaith** [comment]
After some more digging it looks like the `Pass::Option` members aren't actually set to the parsed values before the pass constructor is run, so these lines end up always reading the default option values: https://github.com/llvm/llvm-project/blob/cf0b6df6dbf57334537f827fc8f14f2d7698c3f0/mlir/lib/Transforms/Canonicalizer.cpp#L33:L37

Reading the option members later fixes things: https://reviews.llvm.org/D125621
but is it expected that you can't use the options from the pass constructor? That seems like a bit of a footgun.

**Comment by River707** [comment]
> is it expected that you can't use the options from the pass constructor?
Yes, that is expected. We don't even know what options a pass has until it's constructed. You can only really rely on options afterwards, i.e. in `initializeOptions`(called when setting command line options) or `initialize`.

**Comment by rkayaith** [comment]
I see, I guess [D125621](https://reviews.llvm.org/D125621) is the right way to fix this then.

It'd be nice if reading the option value too early failed an assertion, but I couldn't see a clean way to add that.
