### ISSUE TITLE
Redundant fptosi of floating point induction is not removed, blocking further optimization

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#55505]
For the two similar case `foo1000` and `foo1001`, gcc do sve for `foo1000`, while llvm does none for the both, see https://godbolt.org/z/njGx95Th5.

- gcc: improve the float compare `if (i_16 > 1.0e+0)` to int compare in `153t.ivcanon` for `foo1000`, so later, it can do sve.
- llvm: maybe need improve in function `isKnownExactCastIntToFP`?
```cpp
int foo1000 (int index){
    int aLength = 1500;
    int a[aLength];

    for(float i = 1000; i > 0; i--){
        a[(int)i] = (int)(i);
    }

    return a[index];
}


int foo1001 (int index){
    int aLength = 1500;
    int a[aLength];

    for(float i = 1001; i > 0; i--){
        a[(int)i] = (int)(i);
    }

    return a[index];
}
```

**Comment by sdesmalen-arm** [comment]
(I accidentally clicked 'close', so reopening it again)

**Comment by vfdff** [comment]
sorry, my bad. I updated the link above.
Yes, I think this is not a scalable-vector or SVE problem. and your comment remaids me that gcc and llvm use different methods to prove the exact cast int -> fp as the gcc doen't vectorize for double1000 and double1001
https://godbolt.org/z/W3W4rvqWb

**Comment by fhahn** [comment]
I put up https://reviews.llvm.org/D129140 and it looks like there's already https://reviews.llvm.org/D125774.

@vfdff it would be very helpful if you could make sure to mention potential patches in the issue discussion.

**Comment by vfdff** [comment]
> I put up https://reviews.llvm.org/D129140 and it looks like there's already https://reviews.llvm.org/D125774.
> 
> @vfdff it would be very helpful if you could make sure to mention potential patches in the issue discussion.

Okay, I'wll do that next time. And I am also glad to  learn much from your good code implementation :)

**Comment by vfdff** [comment]
a new solution: https://reviews.llvm.org/D129191

**Comment by vfdff** [comment]
Reopen as I think we should also support the unsigned integer,  https://reviews.llvm.org/D129358

**Comment by vfdff** [comment]
try to improve more: https://reviews.llvm.org/D129756

**Comment by vfdff** [comment]
try to improve types with different size: https://reviews.llvm.org/D129958

**Comment by fhahn** [comment]
Thanks @vfdff!
