### ISSUE TITLE
LLD-MachO should provide an option to demangle symbol names in warnings

### ISSUE THREAD

**Issue by oontvoo** [llvm/llvm-project#55512]
Eg., in some cases, LD64 emits the following warnings:

```
ld: warning: cannot export hidden symbol typeinfo for foo::bar(transaction.o)
ld: warning: cannot export hidden symbol typeinfo name foo::bar(transaction.o)
```

By contrast, LLD emits the following, which makes the difference bewteen `typeinfo` and `typeinfo name` less obvious:

```
ld64.lld: warning: cannot export hidden symbol <mangled-name>
>>> defined in (transaction.o)

ld64.lld: warning: cannot export hidden symbol <mangled-name>
>>> defined in (transaction.o)
```

**Comment by keith** [comment]
There's also an option for this https://github.com/keith/ld64/blob/eddf3fd275669887e70392a1f7d8355222fa295e/src/ld/Options.cpp#L3694-L3695

**Comment by oontvoo** [comment]
> There's also an option for this
Yeah, unfortunately the warning wasn't respecting it

**Comment by oontvoo** [comment]
https://reviews.llvm.org/D125732
