### ISSUE TITLE
Clang crash starting from 81904454f7cdebe

### ISSUE THREAD

**Issue by m-gupta** [llvm/llvm-project#55510]
@Kmeakin Can you please check?

reduced test case:

```
__int128 a, i;
b, j, l, c, q, r, s, t, u, v, x, y, m;
char f, k, w;
long n, o, p;
aa(*, char *ab, ac, ad, unsigned long ae) {
  a = ac + (__int128)ae;
  b = a >> 64;
  *ab = b;
}
af(*ag, *ab, ac, long ad) {
  i = ac * ad >> 4;
  *ag = *ab = j;
}
ah() {
  char z;
  long ai;
  aa(m, &k, f, o, c);
  aa(ah, &z, k, p, l);
  af(q, &r, n, 18446744073709551615);
  {
    int *d = s, *e = t;
    *d = i;
    *e = j;
  }
  af(u, &ai, n, 18446744069414584320);
  aj(v);
  {
    int g = ai;
    unsigned h = s;
    a = v + (__int128)g + h;
    b = a >> 64;
    char *e = b;
    a = t + q;
    b = a;
    *e = r + h;
    *e = b;
  }
  x = y + z;
}
```

Compile as:
clang -Os  -c  test.c -target "aarch64-linux-gnu" -Wno-error -Wno-error=implicit-function-declaration -fcommon -fPIC

**Comment by fhahn** [comment]
This doesn't reproduce on current `main` with godbolt: https://clang.godbolt.org/z/Pvfsv84bG

Can you reproduce this with the latest version of `main`? Could you also include the stack trace? And possible also the IR file produced with `-emit-llvm`?

**Comment by m-gupta** [comment]
Thanks, it was already fixed by the following commit:

commit 0298cce257f8f8070377baab790eb8cc277904fc
Author: Karl Meakin <karl.meakin@arm.com>
Date:   Thu May 12 22:21:20 2022 +0100

    [AArch64] Add `foldADCToCINC` DAG combine.
    
    Differential revision: https://reviews.llvm.org/D123781
