### ISSUE TITLE
[AArch64] miscompilation when optimizing shuffles involving concatenations with zero literals

### ISSUE THREAD

**Issue by Benjins** [llvm/llvm-project#55545]
The following C++ code is miscompiled on the AArch64 backend under -O1:

[Godbolt link](https://godbolt.org/z/7jfvo87Tz)

```cpp
#include <arm_neon.h>

int8x8x2_t do_stuff(int8x8_t Input) {
	int8x8_t Rev = vrev32_s8(Input);
	int8x8_t Zero = {};
	int8x8x2_t Output = vtrn_s8(Zero, Rev);
	return Output;
}
```

here is the assembly it generates:

```asm
.LCPI0_0:
        .byte   8                               // 0x8
        .byte   0                               // 0x0
        .byte   10                              // 0xa
        .byte   2                               // 0x2
        .byte   12                              // 0xc
        .byte   4                               // 0x4
        .byte   14                              // 0xe
        .byte   6                               // 0x6
.LCPI0_1:
        .byte   9                               // 0x9
        .byte   1                               // 0x1
        .byte   11                              // 0xb
        .byte   3                               // 0x3
        .byte   13                              // 0xd
        .byte   5                               // 0x5
        .byte   15                              // 0xf
        .byte   7                               // 0x7
do_stuff(__Int8x8_t):                // @do_stuff(__Int8x8_t)
        rev32   v1.8b, v0.8b
        adrp    x8, .LCPI0_0
        adrp    x9, .LCPI0_1
        ldr     d0, [x8, :lo12:.LCPI0_0]
        mov     v1.d[1], v1.d[0]
        ldr     d2, [x9, :lo12:.LCPI0_1]
        tbl     v0.8b, { v1.16b }, v0.8b
        tbl     v1.8b, { v1.16b }, v2.8b
        ret
```

If we call this function with the input:

```cpp
{10, 11, 12, 13, 14, 15, 16, 17}
```

we'd expect to see the following output:

```cpp
{0, 13, 0, 11, 0, 17, 0, 15, 0, 12, 0, 10, 0, 16, 0, 14}
```

and we do on -O0. However under -O1 we get this output:

```cpp
{13, 13, 11, 11, 17, 17, 15, 15, 12, 12, 10, 10, 16, 16, 14, 14}
```

The problematic lines in the assembly are these:

```asm
mov     v1.d[1], v1.d[0]
...
tbl     v0.8b, { v1.16b }, v0.8b
tbl     v1.8b, { v1.16b }, v2.8b
```

The upper 64-bits of v1 should be zero, but instead are a duplicate of the lower 64-bits. The output then has these instead of zero bytes.

This seems to involve an optimization introduced in 21a97a2ac11b81240c08753277dc1a234c6a7816. It detects that the latter part of the shuffle is all zero's, and uses the semantics of tbl for out of bounds indices (setting output to 0) to implicitly output 0. However in this case, afaict the indices are all in-bounds. They're all less than 16, and the tbl seems to use [0, 16) indices not [0, 8). So instead of an out of bounds index causing a 0 in the output, it reads a byte from the upper-half of the input and gives the wrong result. I'm not sure if the error is in this transform or something downstream, but reverting that commit seemed to avoid the issue.

I have verified that this still repros on the latest trunk (8527f32f0a16a77edb0b53a5ab8074e518eeff54).

For context: this code was generated by a fuzzer, it was not manually written.

**Comment by davemgreen** [comment]
Thanks for the report. I had missed that the lanes might not be out of range for v8i8's. I'll put together a patch

**Comment by Benjins** [comment]
Looks good now, thanks for the fix!
