### ISSUE TITLE
[AMDGPU][MC][GFX940] Missing smfmac aliases

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#55541]
sp3 defines aliases for smfmac opcodes. For example, the following instructions are identical for sp3 assembler:

    v_smfmac_f32_16x16x32_bf16 v[10:13], acc[2:3], v[4:7], v4 cbsz:3 abid:1
    v_smfmac_f32_16x16x32bf16  v[10:13], acc[2:3], v[4:7], v4 cbsz:3 abid:1

However llvm assembler only supports the first form. Should llvm support smfmac aliases?

**Comment by dpreobra** [comment]
@rampitec, could you take a look?

**Comment by rampitec** [comment]
Yes, we should for compatibility. A simple MnemonicAlias I suppose.

**Comment by dpreobra** [comment]
Fixed by commit 44673278e029d7a6f56c8a3177247026b831720f
