### ISSUE TITLE
clang-cl does not support -fprofile-use

### ISSUE THREAD

**Issue by kinke** [llvm/llvm-project#55564]
Similar to #40597: clang-cl as of v14.0.3 supports all of `-fprofile-[instr-]{generate,use}`, except for `-fprofile-use`. `-Xclang -fprofile-use=…` as workaround doesn't work either.

**Comment by Endilll** [comment]
This arguments appears to be recognized since Clang 15: https://godbolt.org/z/f4bKjbca3
