### ISSUE TITLE
LDAPR Instruction is not generated

### ISSUE THREAD

**Issue by adriantong1024** [llvm/llvm-project#55561]
Older ldar+stlr gives something close to memory_order_seq_cst but the newer ldapr+stlr gives a more true memory_order_acquire + memory_order_release, the compiler does not seem to generate this instruction. https://godbolt.org/z/nes6e49sG

Our experience is ldapr+stlr results in better performance in some internal Google workloads.

**Comment by alexander-shaposhnikov** [comment]
I'm planning to address this issue ~soon.

**Comment by peterwaller-arm** [comment]
Ping @alexander-shaposhnikov I see this landed, can this be closed?
