### ISSUE TITLE
clang-tidy: bugprone-undefined-memory-manipulation fails to catch array of NonTriviallyCopyable types

### ISSUE THREAD

**Issue by nick-schultz** [llvm/llvm-project#55579]
I am using llvm-14.0.3  

Please see the following example:

```cpp
#include <cstring>
#include <vector>

struct my_struct_t {                            
    int counter;
    std::vector<int> my_vector;
};

void foo() {
    my_struct_t bar[10];

    //No warning
    memset(bar, 0, sizeof(bar));

    //Warning: bugprone-undefined-memory-manipulation
    memset(&bar[0], 0, sizeof(bar[0]));
}
```

I would expect the following statement to have triggered the `[bugprone-undefined-memory-manipulation]` clang tidy check, since it is calling `memset` on the entire array of NonTriviallyCopyable structures

```cpp
    //No warning
    memset(bar, 0, sizeof(bar));
```

I suspect there is something wrong with the check's [matcher](https://github.com/llvm/llvm-project/blob/8d03c49f498cb19358aacd28f57a852549d34ebd/clang-tools-extra/clang-tidy/bugprone/UndefinedMemoryManipulationCheck.cpp#L27).  However it's unclear if the matcher expression is incorrect or if perhaps `pointsTo` is not considering `bar` as a pointer.

My knowledge with clang  AST-matchers are extremely limited ,  so any insight or guidance would be much appreciated.  

Thanks,

Nick

**Comment by FabianWolff** [comment]
I've submitted a patch for this in [D127036](https://reviews.llvm.org/D127036).

**Comment by nick-schultz** [comment]
Excellent, thank you so much @FabianWolff !
