### ISSUE TITLE
[AMDGPU][MC][GFX940] buffer_store_lds_dword, buffer_wbinvl1 and buffer_wbinvl1_vol should not be supported

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#55591]
AFAIK, these opcodes are not supported on GFX940.
Examples of failed tests:

    buffer_wbinvl1
    buffer_wbinvl1_vol
    buffer_store_lds_dword s[4:7], s2 offset:4095 lds

@rampitec, should these be disabled?

**Comment by jwanggit86** [comment]
I compared the ISA docs for MI200 and MI300. It seems those instructions are not supported in MI300, although they are supported in MI200.

@rampitec @arsenm Could you confirm this?

**Comment by rampitec** [comment]
- BUFFER_WBINVL1 is removed, BUFFER_INV was added instead.
- BUFFER_WBINVL1_VOL is removed.
- BUFFER_STORE_LDS_DWORD seems to be unsupported by SP3, but do not I see any documentation removing it.

**Comment by arsenm** [comment]
> * BUFFER_STORE_LDS_DWORD seems to be unsupported by SP3, but do not I see any documentation removing it.

I can't find any note dropping it, but it does appear in the mi200 ISA PDF, and not in the mi300 version. So I guess it was removed

**Comment by arsenm** [comment]
> > * BUFFER_STORE_LDS_DWORD seems to be unsupported by SP3, but do not I see any documentation removing it.
> 
> I can't find any note dropping it, but it does appear in the mi200 ISA PDF, and not in the mi300 version. So I guess it was removed

However the LDS modifier was introduced for buffer instructions, so it would be redundant. It was just moved from opcode to modifier on other opcode

**Comment by jwanggit86** [comment]
It seems the 3 instructions mentioned in the original post are not supported in GFX940. Based on the above discussion, I'm closing this issue.

**Comment by dpreobra** [comment]
Well, if these instructions are not supported, assembler should not allow using them for GFX940. However, they are still accepted. I checked this on the latest build.

These instructions should be disabled so that assembler does not allow using them for GFX940.
