### ISSUE TITLE
Particular C++ errors are only reported for arm64 architecture, and not on amd64 or i386

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#55604]
Build of the [dexed](https://github.com/asb2m10/dexed) project on arm64 fails with these errors:
```
/wrkdirs/usr/ports/audio/dexed/work/dexed-0.9.6-16-g1df9a58/Source/PluginData.cpp:113:13: error: taking the absolute value of unsigned type 'char' has no effect [-Werror,-Wabsolute-value]
    value = abs(value);
            ^
/wrkdirs/usr/ports/audio/dexed/work/dexed-0.9.6-16-g1df9a58/Source/PluginData.cpp:113:13: note: remove the call to 'abs' since unsigned values cannot be negative
    value = abs(value);
            ^~~
/wrkdirs/usr/ports/audio/dexed/work/dexed-0.9.6-16-g1df9a58/Source/PluginData.cpp:312:29: error: result of comparison of constant -1 with expression of type 'char' is always true [-Werror,-Wtautological-constant-out-of-range-compare]
    return clipboardContent != -1;
           ~~~~~~~~~~~~~~~~ ^  ~~
2 errors generated.
```

But same code revision succeeds on amd64 and i386.

Relevant code lines:
* https://github.com/asb2m10/dexed/blob/master/Source/PluginData.cpp#L113
* https://github.com/asb2m10/dexed/blob/master/Source/PluginData.cpp#L312

clang versions 11-14
OS: FreeBSD 13

**Comment by topperc** [comment]
The default signedness of char is platform specific. char defaults to signed on x86, but must be unsigned on arm64.

**Comment by MrMetric** [comment]
You may find useful the compilation flags `-funsigned-char` and `-fsigned-char`, to explicitly choose what you want `char` to be. I recommend always using one or the other.
