### ISSUE TITLE
Missing transformation X * Y to (0-X) & Y iff X can be only 0 or 1

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#55618]
```cpp
unsigned long long src(long long a, unsigned long long b)
{
  unsigned long long t = a & 1; // known 0 or 1
  return t * b;
}

unsigned long long tgt(long long a, unsigned long long b)
{
  unsigned long long t = a & 1; // known 0 or 1
  return (0-t) & b;
}
```

```console
----------------------------------------
define i64 @src(i64 %0, i64 %1) {
%2:
  %3 = and i64 %0, 1
  %4 = mul i64 %3, %1
  ret i64 %4
}
=>
define i64 @tgt(i64 %0, i64 %1) {
%2:
  %3 = and i64 %0, 1
  %4 = sub i64 0, %3
  %5 = and i64 %4, %1
  ret i64 %5
}
Transformation seems to be correct!
```

```asm
src(long long, unsigned long long):                               # @src(long long, unsigned long long)
        mov     rax, rdi
        and     eax, 1
        imul    rax, rsi
        ret
tgt(long long, unsigned long long):                               # @tgt(long long, unsigned long long)
        mov     rax, rdi
        and     eax, 1
        neg     rax
        and     rax, rsi
        ret
```

https://godbolt.org/z/fqYcPMfvE

So the backend needs to decide if this is profitable or not.

**Comment by msebor** [comment]
This isn't my area but I wonder if the examples above are representative of a more general pattern that includes all integers (signed as well as unsigned).  Might such a pattern be worth transforming into some canonical representation irrespective of the target?  For instance (for any integer types `T` and `U`):
```
T tgt(T a, U b)
{
  bool x = a & 1;
  return x ? b : 0;
}
```

**Comment by rotateright** [comment]
Yes, this is a candidate for an IR transform (instcombine) as mentioned in this review:
https://reviews.llvm.org/D126040#3530339

There's an existing transform that comes into play and causes an extra instruction, but that does not nullify the general improvement for IR analysis from getting rid of a multiply: 
https://alive2.llvm.org/ce/z/o7rQ5q

The backend may already be capable of restoring the multiply if that is profitable.

**Comment by rotateright** [comment]
The IR should be canonicalized to cmp+select with:
f9f40aa10d98
(and we had the expected codegen with the earlier patches)
