### ISSUE TITLE
clang-tidy fix for check option cppcoreguidelines-prefer-member-initializer.UseAssignment doesn't work and initialization doesn't occur at the declaration

### ISSUE THREAD

**Issue by sean-mcmanus** [llvm/llvm-project#55616]
Use clang-tidy 14.0.3.

Use code
```cpp
class C {
  int n;
public:
  C() {
    n = 1;
  }
};
```

Use command
```shell
clang-tidy.exe --config="{ Checks: 'cppcoreguidelines-prefer-member-initializer', CheckOptions: [{key: cppcoreguidelines-prefer-member-initializer.UseAssignment, value: true}]}" --fix <path>/test.cpp -- -std=c++17
```

Bug: The result is
```cpp
class C {
  int n;
public:
  C() : n(1) {
    
  }
};
```
instead of something like
```cpp
class C {
  int n = 1;
public:
  C() : {
    
  }
};
```

See the documentation at https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/cppcoreguidelines-prefer-member-initializer.html . Maybe the docs should be clarified if there is some reason for the difference.

**Comment by PiotrZSL** [comment]
This is because this check somehow reads modernize-use-default-member-init.UseAssignment config option

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D147929
