### ISSUE TITLE
release management; llvm-config has absolute paths

### ISSUE THREAD

**Issue by nlewycky** [llvm/llvm-project#5563]
|  |  |
| --- | --- |
| Bugzilla Link | [5191](https://llvm.org/bz5191) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
I did an LLVM build with --prefix=/home/nicholas/2.6/llvm-2.6-install. The resulting bin/llvm-config binary has these lines:
  my $PREFIX              = q{/home/nicholas/2.6/llvm-2.6-install};
  my $LLVM_SRC_ROOT       = q{/home/nicholas/2.6/llvm-2.6};
  my $LLVM_OBJ_ROOT       = q{/home/nicholas/2.6/llvm-2.6};
and if I were to also have built with llvm-gcc, these:
  my $LLVMGCCDIR          = q{/home/nicholas/llvm-gcc/install};
  my $LLVMGCC             = q{/usr/local/bin/llvm-gcc};
  my $LLVMGXX             = q{/usr/local/bin/llvm-g++};

There's nothing wrong with this until you start thinking about a release. We don't know where people are going to put their llvm install trees. Can we mandate that they unpack into /usr/local/? Should we have a special "relative to $0" mode for releases?

**Comment by arsenm** [comment]
Refers to autotools build which is dead. I assume cmake handles this correctly at least
