### ISSUE TITLE
14.0.3 libcxx: not possible to build `libcxx` against system installed `lit`

### ISSUE THREAD

**Issue by kloczek** [llvm/llvm-project#55631]
https://github.com/llvm/llvm-project/blob/5f66e721ec1d099cf2370235ce122cf47c287308/libcxx/CMakeLists.txt#L980-L992
Looks like currently on 14.x is not possible to build `libcxx` against system installed `lit` like it is in other parts of the LLVM when `libcxx` is not build from mono repo tree. In such situations cmake fails
```console
CMake Warning at benchmarks/CMakeLists.txt:7 (message):
  The libc++ benchmarks are not available in a standalone build.  Please
  migrate to an official build as documented in
  https://libcxx.llvm.org/BuildingLibcxx.html.


-- Linker detection: GNU ld
-- ABI list file not generated for configuration libcxxabi.v1.stable.exceptions.no_new_in_libcxx, `check-cxx-abilist` will not be available.
CMake Error at CMakeLists.txt:982 (add_subdirectory):
  add_subdirectory given source "/utils/llvm-lit" which is not an existing
  directory.


-- Configuring incomplete, errors occurred!
```

**Comment by philnik777** [comment]
libc++ has to be built inside the monorepo. We don't support anything else anymore AFAIK. Is there any reason you don't want to use the monorepo lit?

**Comment by philnik777** [comment]
Closing this, since we don't support the configuration anymore.

**Comment by kloczek** [comment]
> Closing this, since we don't support the configuration anymore.

So in next release it will be no libcxx  source dist tar ball or libcxx will be removed?
