### ISSUE TITLE
std::is_constant_evaluated returns true in C++2b in manifestly runtime functions

### ISSUE THREAD

**Issue by jzmaddock** [llvm/llvm-project#55638]
Consider the code:

```cpp
#include <type_traits>
#include <cmath>
#include <iostream>

template <class Integer>
constexpr Integer bitwise_sqrt(const Integer& x)
{
   // TODO put real code here, doesn't need it for the bug case though
   return 0;
}
template <class Integer>
constexpr Integer fast_sqrt(const Integer& x)
{
   return static_cast<Integer>(std::sqrt(static_cast<double>(x)));
}
template <class Integer>
constexpr Integer get_sqrt(const Integer& x)
{
  if(std::is_constant_evaluated())
    return bitwise_sqrt(x);
   return fast_sqrt(x);
}


int main()
{
  unsigned i;
  std::cin >> i;
  i = get_sqrt(i);
  std::cout << i << std::endl;
}
```

Input comes from `std::cin`, I assume we can all agree that in this context `get_sqrt()` can not be a constant context.  However, `std::is_constant_evaluated()` is returning true.

Note that:

1) The issue only occurs when compiling with `-std=c++2b`.
2) The issue does not occur prior to clang-14.
3) The issue does not occur if we use `__builtin_is_constant_evaluated()` directly.
4) Reproduced on Ubuntu-22 with `ubuntu clang version 14.0.0-1ubuntu1`

This is a reduced test case from `Boost.Multiprecision` BTW.

**Comment by cpplearner** [comment]
It seems that `if consteval` chooses the wrong branch when the enclosing function is called in the condition of an `if` statement.

```c++
#include <iostream>

constexpr bool is_constant_evaluated() {
    if consteval { return true; } else { return false; }
}

int f1() {
    if (is_constant_evaluated()) { return 2; } else { return 3; }
}

int main() {
    std::cout << f1() << '\n'; // 2, should be 3
}
```

**Comment by philnik777** [comment]
@jzmaddock  https://godbolt.org/z/3zevohnT9 LLVM-clang14 is happy with the code.
@cpplearner's code indeed looks like a bug, but that's a clang frontend bug.

**Comment by jzmaddock** [comment]
OK, the missing bit of information is that I have gcc-12 installed, which apparently changes the definition of std::is_constant_evaluated() to match what @cpplearner had.  Revised test case is:

```
#include <cmath>
#include <iostream>

constexpr inline bool is_constant_evaluated() noexcept
{
  if consteval { return true; } else { return false; }
}


template <class Integer>
constexpr Integer bitwise_sqrt(const Integer& x)
{
   // TODO put real code here, doesn't need it for the bug case though
   return 0;
}
template <class Integer>
constexpr Integer fast_sqrt(const Integer& x)
{
   return static_cast<Integer>(std::sqrt(static_cast<double>(x)));
}
template <class Integer>
constexpr Integer get_sqrt(const Integer& x)
{
  if(::is_constant_evaluated())
    return bitwise_sqrt(x);
   return fast_sqrt(x);
}


int main()
{
  unsigned i;
  std::cin >> i;
  i = get_sqrt(i);
  std::cout << i << std::endl;
}
```

See: https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:37,positionColumn:1,positionLineNumber:37,selectionStartColumn:1,selectionStartLineNumber:37,startColumn:1,startLineNumber:37),source:'%23include+%3Ccmath%3E%0A%23include+%3Ciostream%3E%0A%0Aconstexpr+inline+bool+is_constant_evaluated()+noexcept%0A%7B%0A++if+consteval+%7B+return+true%3B+%7D+else+%7B+return+false%3B+%7D%0A%7D%0A%0A%0Atemplate+%3Cclass+Integer%3E%0Aconstexpr+Integer+bitwise_sqrt(const+Integer%26+x)%0A%7B%0A+++//+TODO+put+real+code+here,+doesn!'t+need+it+for+the+bug+case+though%0A+++return+0%3B%0A%7D%0Atemplate+%3Cclass+Integer%3E%0Aconstexpr+Integer+fast_sqrt(const+Integer%26+x)%0A%7B%0A+++return+static_cast%3CInteger%3E(std::sqrt(static_cast%3Cdouble%3E(x)))%3B%0A%7D%0Atemplate+%3Cclass+Integer%3E%0Aconstexpr+Integer+get_sqrt(const+Integer%26+x)%0A%7B%0A++if(::is_constant_evaluated())%0A++++return+bitwise_sqrt(x)%3B%0A+++return+fast_sqrt(x)%3B%0A%7D%0A%0A%0Aint+main()%0A%7B%0A++unsigned+i%3B%0A++std::cin+%3E%3E+i%3B%0A++i+%3D+get_sqrt(i)%3B%0A++std::cout+%3C%3C+i+%3C%3C+std::endl%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang1400,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-std%3Dc%2B%2B2b',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x86-64+clang+14.0.0+(C%2B%2B,+Editor+%231,+Compiler+%231)',t:'0')),header:(),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

**Comment by jzmaddock** [comment]
> Ok, so this is only a clang bug and has nothing to do with libc++.

Correct.

**Comment by cor3ntin** [comment]
The front end incorrectly folded `if consteval`
https://reviews.llvm.org/D130437
