### ISSUE TITLE
CMAKE not producing x86 build for Windows 

### ISSUE THREAD

**Issue by DibyaTheXPFan** [llvm/llvm-project#55637]
Despite using `-DLLVM_TARGETS_TO_BUILD=X86`, CMAKE produced Visual studio solution file showing only x64 option. 
Will anyone can kindly share CMAKE command to build on Windows for both 32bit and 64bit system. 
I just need Clang LLVM and LibC++

**Comment by arsenm** [comment]
LLVM_TARGETS_TO_BUILD controls only the targets you can emit, not the build itself. X86 covers targeting 32 and 64-bit. If you are trying to create a 32-bit build you want either LLVM_BUILD_32_BITS or look into cmake cross compiling options
