### ISSUE TITLE
_mm256_permute4x64_epi64 generates vpermpd instead of vpermq

### ISSUE THREAD

**Issue by moon-chilled** [llvm/llvm-project#55646]
The following function:

```c
__m256i f(__m256i x) { return _mm256_permute4x64_epi64(x,0x4e); }
```

Compiles to:

```asm
vpermpd ymm0,ymm0,0x4e
```

It should generate vpermq instead of vpermpd.  The use of __m256i is a hint that 'x' is being used for integer operations, so the use of a floating-point instruction is likely to trigger a penalty for switching domains.

GCC generates vpermq for this snippet, and will generate vpermpd instead if __m256d and _mm256_permute4x64_pd are used; this is ideal behaviour.

**Comment by topperc** [comment]
The compiler considers surrounding instructions to decide the domain. It happens to default to fp if there are no surrounding instructions.

Are you seeing this issue in a more complex function with other intrinsics?

**Comment by moon-chilled** [comment]
I am fairly certain I was, but I cannot reproduce it now.

**Comment by moon-chilled** [comment]
closing for now; will repoen if I see it again
