### ISSUE TITLE
LLVM stuck in "X86 DAG->DAG Instruction Selection" after InstCombine change

### ISSUE THREAD

**Issue by OCHyams** [llvm/llvm-project#55648]
`$ cat 1.c`
```C
int a;
short b[101];
void c(int d[][1]) {
  int e;
  long f;
  for (; a < 1; a++)
    b[0] = 0;
  for (; a < 101; a++) {
    for (e = 0; e < 101; e++)
      if (b[e] != 1)
        if (d[a][e] < f)
          f = d[a][e];
  }
  for (; e; e++)
    d[0][e] = f;
}
```

Compiling with the following command takes over an hour:
`$ clang 1.c -O3 -c  --target=x86_64-unknown-linux -march=btver2`

Looking at the "-print-before-all" output it looks like LLVM gets stuck in "X86 DAG->DAG Instruction Selection".

This long compile time appears to start occurring with commit a266af721153fab6452094207b09ed265ab0be7b "[InstCombine] Canonicalize SPF to min/max intrinsic".

**Comment by fhahn** [comment]
IR reproducer for `llc`: https://llvm.godbolt.org/z/68df9P6Yb
