### ISSUE TITLE
Lambda trailing return type spacing different when called within std algorithm

### ISSUE THREAD

**Issue by bbennetts** [llvm/llvm-project#55652]
```console
$ clang-format --version
clang-format version 14.0.0 (Red Hat 14.0.0-1.module_el8.7.0+1142+5343df54)
```

When formatting the attached code a space inserted after the trailing return of the second lambda but not the first.  Is there an option to make this consistent or is it a bug? (FWIW I _want_ the space)

Before :

```cpp
  transform(  begin( v), end( v), back_inserter( vPlusOne ), [](auto thing )->auto{return thing+1;} );

  auto addTwo=[](auto thing)->auto{ return thing + 2;};
```

After calling `clang-format --style=GNU` :

```cpp
  transform (
      begin (v), end (v), back_inserter (vPlusOne),
      [](auto thing) -> auto{ return thing + 1; });

  auto addTwo = [](auto thing) -> auto { return thing + 2; };
```

[main.cpp.txt](https://github.com/llvm/llvm-project/files/8753688/main.cpp.txt)

**Comment by rymiel** [comment]
Fixed by 17fb879764dcaf1f5f6bc505c5c747067ba7c3cd and 4977fd2192fc13e17ea162da15ddbe17cd623757
