### ISSUE TITLE
MLIR Build Fails

### ISSUE THREAD

**Issue by stumpOS** [llvm/llvm-project#55666]
Version: llvmorg-15-init-11158-ga3a85fe59f48
CMAKE command: `cmake -G Ninja ../llvm -DLLVM_ENABLE_PROJECTS=mlir -DCMAKE_BUILD_TYPE=Release -DMLIR_ENABLE_BINDINGS_PYTHON=ON -DPython3_EXECUTABLE=${Python3} -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_C_COMPILER=${GCC_PREFIX}/clang -DCMAKE_CXX_COMPILER=${GCC_PREFIX}/clang++ -DGCC_INSTALL_PREFIX=${GCC_PREFIX}`, where GCC_PREFIX points to LLVM 12.0.1 installed by Brew and Python3 points to a python executable of version 3.9.7
Error: `FAILED: tools/mlir/python_packages/mlir_core/mlir/_mlir_libs/_mlir.cpython-39-darwin.so` with `llvm-strip: error: unsupported load command (cmd=0x80000034)` on every mlir lib

**Comment by Naville** [comment]
I know nothing about MLIR but this seems like a bug of ``llvm-strip`` not recognizing the new MachO LoadCommand LC_DYLD_CHAINED_FIXUPS

**Comment by Naville** [comment]
It's a new lc in iOS15 and above, my bet is on this should be @llvm/issue-subscribers-tools-llvm-objdump

**Comment by keith** [comment]
I added support for this in llvm-strip here https://reviews.llvm.org/D113734 so I'm surprised to see this error. Is the strip being run the one from llvm 15 or llvm 12 though? since this was recent-ish

**Comment by stumpOS** [comment]
It's llvm 12. I'm about to test it with llvm 15.

**Comment by keith** [comment]
Ok yep should work with that

**Comment by keith** [comment]
If you're on macOS that appears to be a security issue, you might have to strip the xattrs from the binary? You can probably see more info in Console.app about why it was killed.

**Comment by stumpOS** [comment]
You are correct. I was able to allow llvm-strip in system settings and the build was able to complete, albeit with a test failure (MLIR :: python/execution_engine.py). I will assume this is a separate issue and close this issue.
