### ISSUE TITLE
clang-tidy check misc-unused-parameters preferably would not report warnings for virtual functions

### ISSUE THREAD

**Issue by sean-mcmanus** [llvm/llvm-project#55665]
Or it would nice if there was a setting to opt-in/out of that behavior.

This could be considered a feature/design request and not a bug.

See https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/misc-unused-parameters.html .

Use code 
```cpp

class baseClass
{
public:
    virtual bool is_valid(int arg) = 0;
};

class derivedClass2: public baseClass
{
public:
    bool is_valid(int arg) override
    {
        return arg == 0;
    }
};

class derivedClass1: public baseClass
{
public:
    bool is_valid(int arg) override
    {
        return false;
    }
};
```

Our team likes the check for the non-virtual case, but in our code base it is "common" for a derived class implementation of a base class virtual method to not need to use all the arguments of the method, so in that case a warning doesn't seem useful to us.

Another potential fix for many cases would be to change the non-StrictMode to include additional simple cases, such as returning a literal value or throwing a not implemented exception, etc. (not sure if that request would be helpful to track separately or not).

**Comment by PiotrZSL** [comment]
Did you consider removing parameter name ? Does it change anything ?

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D147918
