### ISSUE TITLE
Twice as many kernel arguments as specified in SPIR

### ISSUE THREAD

**Issue by jonasbhjulstad** [llvm/llvm-project#55675]
I have defined a simple kernel function that takes one global input argument, which is compiled from OpenCL for C++ (`-cl-std=clc++2021`) in clang.
```cpp
__kernel void foo(global float* x0)
{
    int a = 0;
}
```

The kernel (`kernel.cpp`, contained in same directory as test executable) is compiled to non-readable SPIR with this command:
```shell
clang -c -target spirv32 -cl-kernel-arg-info -Xclang -no-opaque-pointers  -cl-std=clc++2021 kernel.cpp -o kernel.spv
```
It is fully possible to load the kernel into OpenCL (as in the example below), but the recognized number of kernel input arguments is wrong. Two (`float*`) arguments are recognized by OpenCL (using `clGetKernelInfo(kernel, CL_KERNEL_NUM_ARGS, ...)`) but I'm only able to assign one kernel argument using `clSetKernelArg(.)`. Is something missing in the SPIR translation process, or does the additional kernel argument serve another purpose?

Readable format is attained with the following command:
```shell
clang -c -target spirv32 -cl-kernel-arg-info -Xclang -no-opaque-pointers  -cl-std=clc++2021 -emit-llvm kernel.cpp -o kernel.ll
llvm-spirv --spirv-text kernel.ll -o kernel.rspv
```

Which gives the following readable output:
```console
119734787 65536 393230 19 0 
2 Capability Addresses 
2 Capability Linkage 
2 Capability Kernel 
5 ExtInstImport 1 "OpenCL.std" 
3 MemoryModel 1 2 
4 EntryPoint 6 15 "foo" 
3 Source 3 300000 
3 Name 6 "foo" 
3 Name 16 "x0" 
5 Decorate 6 LinkageAttributes "foo" Export 
4 Decorate 7 Alignment 4 
4 Decorate 10 Alignment 4 
4 Decorate 13 Alignment 4 
4 Decorate 16 Alignment 4 
4 TypeInt 11 32 0 
4 Constant 11 14 0 
2 TypeVoid 2 
3 TypeFloat 3 32 
4 TypePointer 4 5 3 
4 TypeFunction 5 2 4 
4 TypePointer 9 7 4 
4 TypePointer 12 7 11 


5 Function 2 6 2 5 
3 FunctionParameter 4 7 

2 Label 8 
4 Variable 9 10 7 
4 Variable 12 13 7 
5 Store 10 7 2 4 
5 Store 13 14 2 4 
1 Return 

1 FunctionEnd 

5 Function 2 15 2 5 
3 FunctionParameter 4 16 

2 Label 17 
5 FunctionCall 2 18 6 16 
1 Return 

1 FunctionEnd 
```

Minimal "working example"
```cpp
#define CL_TARGET_OPENCL_VERSION 300

#include <CL/cl.h>
#include <iostream>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <fstream>
#include <cassert>
#include <array>
#include <random>
#include <sstream>
#include <cmath>
#define SUCCESS 0
#define FAILURE 1

struct CLG_Instance
{
    cl_uint numPlatforms;
    cl_platform_id platform;
    cl_uint numDevices = 0;
    std::vector<cl_device_id> device_ids;
    cl_context context;
    cl_command_queue commandQueue;
    cl_program program;
	size_t global_mem_size;
	size_t global_mem_cache_size;
	size_t max_work_group_size;
};

/* convert the kernel file into a string */
std::string convertToString(const char *filename)
{	
	std::ifstream t(filename);
	std::stringstream buffer;
	buffer << t.rdbuf();
	return buffer.str();
}

const char pwd[] = "/home/deb/Documents/OpenCL-Graph/test/";

int main(int argc, char *argv[])
{

    CLG_Instance clInstance;
	cl_uint numPlatforms; //the NO. of platforms
	cl_int status = clGetPlatformIDs(0, NULL, &numPlatforms);

	if (numPlatforms > 0)
	{
		cl_platform_id* platforms = 
                     (cl_platform_id*)malloc(numPlatforms * sizeof(cl_platform_id));
		status = clGetPlatformIDs(numPlatforms, platforms, NULL);
		clInstance.platform = platforms[0];
		free(platforms);
	}

    cl_uint deviceType = CL_DEVICE_TYPE_GPU;

	status = clGetDeviceIDs(clInstance.platform, deviceType, 0, NULL, &clInstance.numDevices);

    clInstance.device_ids.resize(clInstance.numDevices);

    status = clGetDeviceIDs(clInstance.platform, deviceType, clInstance.numDevices, clInstance.device_ids.data(), NULL);

	clInstance.context = clCreateContext(NULL, 1, clInstance.device_ids.data(), NULL, NULL, NULL);

	clInstance.commandQueue = clCreateCommandQueueWithProperties(clInstance.context, clInstance.device_ids[0], NULL, NULL);
    
    clGetDeviceInfo(clInstance.device_ids[0], CL_DEVICE_GLOBAL_MEM_CACHE_SIZE, sizeof(size_t), &clInstance.global_mem_cache_size, NULL);

    clGetDeviceInfo(clInstance.device_ids[0], CL_DEVICE_GLOBAL_MEM_SIZE, sizeof(size_t), &clInstance.global_mem_size, NULL);

    clGetDeviceInfo(clInstance.device_ids[0], CL_DEVICE_MAX_WORK_GROUP_SIZE, sizeof(size_t), &clInstance.max_work_group_size, NULL);

	

    int err = 0;
    std::string programBinary = convertToString((std::string(pwd) + "kernel.spv").c_str());
    long unsigned int programSize = sizeof(char)*programBinary.length();
    clInstance.program = clCreateProgramWithIL(clInstance.context, (const void*) programBinary.data(), sizeof(char)*programBinary.length(), &err);
    assert(err == CL_SUCCESS);
    status = clBuildProgram(clInstance.program, 1, clInstance.device_ids.data(), NULL, NULL, NULL);
    
    if (status == CL_BUILD_PROGRAM_FAILURE)
    {
        size_t log_size;
        clGetProgramBuildInfo(clInstance.program, clInstance.device_ids[0], CL_PROGRAM_BUILD_LOG, 0, NULL, &log_size);

        // Allocate memory for the log
        char *log = (char *)malloc(log_size);

        // Get the log
        clGetProgramBuildInfo(clInstance.program, clInstance.device_ids[0], CL_PROGRAM_BUILD_LOG, log_size, log, NULL);

        // Print the log
        printf("%s\n", log);
    }



    float x0[3] = {1.0,2.0,3.0};
    float x_res[3] = {-10,-10,-10};

    size_t inputBufferSize = sizeof(float)*3;
    // size_t outputBufferSize = sizeof(float)*3;

    cl_mem inputBuffer = clCreateBuffer(clInstance.context, CL_MEM_READ_ONLY | CL_MEM_COPY_HOST_PTR, inputBufferSize, (void*) x0, &err);
    assert(err == CL_SUCCESS);

    // cl_mem outputBuffer = clCreateBuffer(clInstance.context, CL_MEM_WRITE_ONLY, outputBufferSize, NULL, &err);
    // assert(err == CL_SUCCESS);

    cl_kernel kernel;
    kernel = clCreateKernel(clInstance.program, "foo", &err);
    assert(err == CL_SUCCESS);
    cl_uint num_args = 0;
    size_t numargSize = sizeof(cl_uint);
    status = clGetKernelInfo(kernel, CL_KERNEL_NUM_ARGS, numargSize, &num_args, &numargSize);
    std::cout << "number of arguments: " << num_args << std::endl;
    
    //get kernel argument names
    std::vector<std::string> arg_names;
    std::string arg_name;
    for (cl_uint i = 0; i < num_args; i++)
    {
        size_t arg_name_size = 0;
        status = clGetKernelArgInfo(kernel, i, CL_KERNEL_ARG_NAME, 0, NULL, &arg_name_size);
        arg_name.resize(arg_name_size);
        status = clGetKernelArgInfo(kernel, i, CL_KERNEL_ARG_NAME, arg_name_size, (void*) arg_name.data(), NULL);
        arg_names.push_back(std::string(arg_name));
    }

    for (cl_uint i = 0; i < num_args; i++)
    {
        std::cout << arg_names[i] << std::endl;
    }


    //get kernel argument type names
    std::vector<std::string> arg_type_names;
    std::string arg_type_name;
    for (cl_uint i = 0; i < num_args; i++)
    {
        size_t arg_type_name_size = 0;
        status = clGetKernelArgInfo(kernel, i, CL_KERNEL_ARG_TYPE_NAME, 0, NULL, &arg_type_name_size);
        arg_type_name.resize(arg_type_name_size);
        status = clGetKernelArgInfo(kernel, i, CL_KERNEL_ARG_TYPE_NAME, arg_type_name_size, (void*) arg_type_name.data(), NULL);
        arg_type_names.push_back(std::string(arg_type_name));
    }
    //print arg_type_names
    for (cl_uint i = 0; i < num_args; i++)
    {
        std::cout << arg_type_names[i] << std::endl;
    }


    // err = clSetKernelArg(kernel, 1, sizeof(float), &df);

    assert(err == CL_SUCCESS);

    // err = clSetKernelArg(kernel, 1, sizeof(cl_mem), &outputBuffer);

    // assert(err == CL_SUCCESS);

    size_t globalWorkSize[1] = {8};

    err = clEnqueueNDRangeKernel(clInstance.commandQueue, kernel, 1, NULL, globalWorkSize, NULL, 0, NULL, NULL);

    assert(err == CL_SUCCESS);

    // err = clEnqueueReadBuffer(clInstance.commandQueue, outputBuffer, CL_TRUE, 0, outputBufferSize, x_res, 0, NULL, NULL);

    // assert(err == CL_SUCCESS);

    status = clReleaseKernel(kernel);              //Release kernel.
    status = clReleaseProgram(clInstance.program); //Release the program object.
    status = clReleaseMemObject(inputBuffer);
    // status = clReleaseMemObject(outputBuffer);
    status = clReleaseCommandQueue(clInstance.commandQueue); //Release  Command queue.
    status = clReleaseContext(clInstance.context);           //Release context.



    return SUCCESS;
}
```

**Comment by AnastasiaStulova** [comment]
I have just tried compiling this example into SPIR-V in the same way and then used disassembler from SPIR-V Tools and it looks all fine:

```
; SPIR-V
; Version: 1.0
; Generator: Khronos LLVM/SPIR-V Translator; 14
; Bound: 9
; Schema: 0
               OpCapability Addresses
               OpCapability Kernel
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical32 OpenCL
               OpEntryPoint Kernel %6 "foo"
               OpSource OpenCL_C 300000
               OpName %x0 "x0"
               OpName %entry "entry"
               OpDecorate %x0 FuncParamAttr NoCapture
               OpDecorate %x0 Alignment 4
       %void = OpTypeVoid
      %float = OpTypeFloat 32
%_ptr_CrossWorkgroup_float = OpTypePointer CrossWorkgroup %float
          %5 = OpTypeFunction %void %_ptr_CrossWorkgroup_float
          %6 = OpFunction %void Pure %5
         %x0 = OpFunctionParameter %_ptr_CrossWorkgroup_float
      %entry = OpLabel
               OpReturn
               OpFunctionEnd
```
The relevant part is the last 6 lines where it shows only one parameter (`%x0`).

Can you please let me know the exact version or revision sha of clang and llvm-spirv that you are using.

**Comment by jonasbhjulstad** [comment]
Here is my disassembly output:
```
; SPIR-V
; Version: 1.0
; Generator: Khronos LLVM/SPIR-V Translator; 14
; Bound: 19
; Schema: 0
               OpCapability Addresses
               OpCapability Linkage
               OpCapability Kernel
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical32 OpenCL
               OpEntryPoint Kernel %15 "foo"
               OpSource OpenCL_C 300000
               OpName %foo "foo"
               OpName %x0 "x0"
               OpDecorate %foo LinkageAttributes "foo" Export
               OpDecorate %7 Alignment 4
               OpDecorate %10 Alignment 4
               OpDecorate %13 Alignment 4
               OpDecorate %x0 Alignment 4
       %uint = OpTypeInt 32 0
     %uint_0 = OpConstant %uint 0
       %void = OpTypeVoid
      %float = OpTypeFloat 32
%_ptr_CrossWorkgroup_float = OpTypePointer CrossWorkgroup %float
          %5 = OpTypeFunction %void %_ptr_CrossWorkgroup_float
%_ptr_Function__ptr_CrossWorkgroup_float = OpTypePointer Function %_ptr_CrossWorkgroup_float
%_ptr_Function_uint = OpTypePointer Function %uint
        %foo = OpFunction %void DontInline %5
          %7 = OpFunctionParameter %_ptr_CrossWorkgroup_float
          %8 = OpLabel
         %10 = OpVariable %_ptr_Function__ptr_CrossWorkgroup_float Function
         %13 = OpVariable %_ptr_Function_uint Function
               OpStore %10 %7 Aligned 4
               OpStore %13 %uint_0 Aligned 4
               OpReturn
               OpFunctionEnd
         %15 = OpFunction %void DontInline %5
         %x0 = OpFunctionParameter %_ptr_CrossWorkgroup_float
         %17 = OpLabel
         %18 = OpFunctionCall %void %foo %x0
               OpReturn
               OpFunctionEnd
```
```
spirv-dis --version
SPIRV-Tools v2022.3-dev v2022.2-19-g98340ec5
Target: SPIR-V 1.5
```
```
clang --version
clang version 15.0.0 (https://github.com/llvm/llvm-project.git f6366ef7f4f3cf1182fd70e0c50a9fa54374b612)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by AnastasiaStulova** [comment]
Strangely in your SPIR-V output I can see two functions generated foo and a wrapper to foo that calls it:
```

        %foo = OpFunction %void DontInline %5
          %7 = OpFunctionParameter %_ptr_CrossWorkgroup_float
          %8 = OpLabel
         %10 = OpVariable %_ptr_Function__ptr_CrossWorkgroup_float Function
         %13 = OpVariable %_ptr_Function_uint Function
               OpStore %10 %7 Aligned 4
               OpStore %13 %uint_0 Aligned 4
               OpReturn
               OpFunctionEnd
         %15 = OpFunction %void DontInline %5
         %x0 = OpFunctionParameter %_ptr_CrossWorkgroup_float
         %17 = OpLabel
         %18 = OpFunctionCall %void %foo %x0
               OpReturn
               OpFunctionEnd
```

However only the wrapper is market as an entry point but it has a name foo that might be confusing to the consumer:
`
OpEntryPoint Kernel %15 "foo"`

Could you please let me know version of your `llvm-spirv` tool that you use to generate SPIR-V from LLVM bitcode.

Also if you could paste me the content of your .ll file it would be helpful to look at too.

**Comment by jonasbhjulstad** [comment]
Here is the readable .ll:
```
; ModuleID = 'kernel.cpp'
source_filename = "kernel.cpp"
target datalayout = "e-p:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024"
target triple = "spirv32"

; Function Attrs: convergent mustprogress noinline norecurse nounwind optnone
define spir_kernel void @foo(float addrspace(1)* noundef align 4 %0) #0 !kernel_arg_addr_space !4 !kernel_arg_access_qual !5 !kernel_arg_type !6 !kernel_arg_base_type !6 !kernel_arg_type_qual !7 !kernel_arg_name !8 {
  %2 = alloca float addrspace(1)*, align 4
  %3 = alloca i32, align 4
  store float addrspace(1)* %0, float addrspace(1)** %2, align 4
  store i32 0, i32* %3, align 4
  ret void
}

attributes #0 = { convergent mustprogress noinline norecurse nounwind optnone "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "uniform-work-group-size"="true" }

!llvm.module.flags = !{!0, !1}
!opencl.ocl.version = !{!2}
!llvm.ident = !{!3}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"frame-pointer", i32 2}
!2 = !{i32 3, i32 0}
!3 = !{!"clang version 15.0.0 (https://github.com/llvm/llvm-project.git f6366ef7f4f3cf1182fd70e0c50a9fa54374b612)"}
!4 = !{i32 1}
!5 = !{!"none"}
!6 = !{!"float*"}
!7 = !{!""}
!8 = !{!"x0"}
```


```
llvm-spirv --version
LLVM (http://llvm.org/):
  LLVM version 15.0.0git
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: icelake-client
```

**Comment by AnastasiaStulova** [comment]
> llvm-spirv --version
> LLVM (http://llvm.org/):
>   LLVM version 15.0.0git
>   Optimized build.
>   Default target: x86_64-unknown-linux-gnu
>   Host CPU: icelake-client

Unfortunately, I can't see the revision being listed and with the build on the top of tree (SHA `9de28053fd4525b68f1f0b37c3e4fdeabaa64ff3`) I am not able to compile this example at all as I am getting this error:

```
llvm-spirv: Too many positional arguments specified!
Can specify at most 1 positional arguments: See: /data_sdb/work/sw/SPIRV-LLVM-Translator/build1/tools/llvm-spirv/llvm-spirv --help
```

I get the same error for all OpenCL kernel language modes btw. So it is very possible that ToT is broken for different reasons.

Regardless I would suggest to create a bug for llvm-spirv here: https://github.com/KhronosGroup/SPIRV-LLVM-Translator

Feel free to link this issue for more information.

In the meantime I would suggest using clang and llvm-spirv from release 14, as they seem to generate sensible SPIR-V output.

**Comment by jonasbhjulstad** [comment]
Compiling to SPIRV with clang and llvm-spirv release 14 resulted in the same issue as with 15.
```
clang-14 --version
Ubuntu clang version 14.0.1-++20220426083040+0e27d08cdeb3-1~exp1~20220426083051.129
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```
llvm-spirv --version
Ubuntu LLVM version 14.0.1
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: icelake-client
```

**Comment by AnastasiaStulova** [comment]
Ok I can now reproduce similar SPIR-V output with the release 14 branches compiling for OpenCL 1.2 or C++ for OpenCL 2021:

```
; SPIR-V
; Version: 1.0
; Generator: Khronos LLVM/SPIR-V Translator; 14
; Bound: 13
; Schema: 0
               OpCapability Addresses
               OpCapability Linkage
               OpCapability Kernel
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical32 OpenCL
               OpEntryPoint Kernel %9 "foo"
               OpSource OpenCL_C 102000
               OpName %foo "foo"
               OpName %x0 "x0"
               OpName %entry "entry"
               OpName %x0_0 "x0"
               OpDecorate %foo LinkageAttributes "foo" Export
               OpDecorate %x0 FuncParamAttr NoCapture
               OpDecorate %x0_0 FuncParamAttr NoCapture
       %void = OpTypeVoid
      %float = OpTypeFloat 32
%_ptr_CrossWorkgroup_float = OpTypePointer CrossWorkgroup %float
          %5 = OpTypeFunction %void %_ptr_CrossWorkgroup_float
        %foo = OpFunction %void Pure %5
         %x0 = OpFunctionParameter %_ptr_CrossWorkgroup_float
      %entry = OpLabel
               OpReturn
               OpFunctionEnd
          %9 = OpFunction %void Pure %5
       %x0_0 = OpFunctionParameter %_ptr_CrossWorkgroup_float
         %11 = OpLabel
         %12 = OpFunctionCall %void %foo %x0_0
               OpReturn
               OpFunctionEnd
```

 However, I can't spot anything suspecious and `spirv-val` validates this SPIR-V successfully. 

So it feels to me that this might be an issue with the driver not being able to read the SPIR-V correctly. 

Out of curiosity have you tried to execute any of the SPIR-V kernels on the device (setting only 1 argument) to see whether the result is actually computed correctly irrespective that the number of arguments query being broken?

**Comment by AnastasiaStulova** [comment]
FYI if you are able to use arbitrary tool revisions the following revisions (both dated to Dec last year):

```
clang revision: 0045d01af96ff56c5b62d133be076020a33867ff
llvm-spirv revision: e8f1964d0e58aacfe39c8ce7b43b64d6cabaed49
```

produce SPIR-V without a wrapper function with this command line:

`clang -c -target spirv32 -cl-kernel-arg-info -cl-std=clc++2021 issue55675.cl -S -o -`

 so it is more close to the original source:

```
OpCapability Addresses
OpCapability Kernel
%1 = OpExtInstImport "OpenCL.std"
OpMemoryModel Physical32 OpenCL
OpEntryPoint Kernel %6 "foo"
OpSource OpenCL_C 300000
OpName %x0 "x0"
OpName %entry "entry"
OpDecorate %x0 FuncParamAttr NoCapture
%void = OpTypeVoid
%float = OpTypeFloat 32
%_ptr_CrossWorkgroup_float = OpTypePointer CrossWorkgroup %float
%5 = OpTypeFunction %void %_ptr_CrossWorkgroup_float
%6 = OpFunction %void Pure %5
%x0 = OpFunctionParameter %_ptr_CrossWorkgroup_float
%entry = OpLabel
OpReturn
OpFunctionEnd
```
in case you would like to try importing it in the driver and check whether this the root cause of the issue you are experiencing.

(Alternatively you can just use **spirv-as** on the output I have pasted to create a SPIR-V binary.)

**Comment by jonasbhjulstad** [comment]
> Ok I can now reproduce similar SPIR-V output with the release 14 branches compiling for OpenCL 1.2 or C++ for OpenCL 2021:
> 
> ```
> ; SPIR-V
> ; Version: 1.0
> ; Generator: Khronos LLVM/SPIR-V Translator; 14
> ; Bound: 13
> ; Schema: 0
>                OpCapability Addresses
>                OpCapability Linkage
>                OpCapability Kernel
>           %1 = OpExtInstImport "OpenCL.std"
>                OpMemoryModel Physical32 OpenCL
>                OpEntryPoint Kernel %9 "foo"
>                OpSource OpenCL_C 102000
>                OpName %foo "foo"
>                OpName %x0 "x0"
>                OpName %entry "entry"
>                OpName %x0_0 "x0"
>                OpDecorate %foo LinkageAttributes "foo" Export
>                OpDecorate %x0 FuncParamAttr NoCapture
>                OpDecorate %x0_0 FuncParamAttr NoCapture
>        %void = OpTypeVoid
>       %float = OpTypeFloat 32
> %_ptr_CrossWorkgroup_float = OpTypePointer CrossWorkgroup %float
>           %5 = OpTypeFunction %void %_ptr_CrossWorkgroup_float
>         %foo = OpFunction %void Pure %5
>          %x0 = OpFunctionParameter %_ptr_CrossWorkgroup_float
>       %entry = OpLabel
>                OpReturn
>                OpFunctionEnd
>           %9 = OpFunction %void Pure %5
>        %x0_0 = OpFunctionParameter %_ptr_CrossWorkgroup_float
>          %11 = OpLabel
>          %12 = OpFunctionCall %void %foo %x0_0
>                OpReturn
>                OpFunctionEnd
> ```
> 
> However, I can't spot anything suspecious and `spirv-val` validates this SPIR-V successfully.
> 
> So it feels to me that this might be an issue with the driver not being able to read the SPIR-V correctly.
> 
> Out of curiosity have you tried to execute any of the SPIR-V kernels on the device (setting only 1 argument) to see whether the result is actually computed correctly irrespective that the number of arguments query being broken?

I have tried to run it with `clEnqueueNDRangeKernel` which results in error code `CL_INVALID_KERNEL_ARGS`.

**Comment by jonasbhjulstad** [comment]
> FYI if you are able to use arbitrary tool revisions the following revisions (both dated to Dec last year):
> 
> ```
> clang revision: 0045d01af96ff56c5b62d133be076020a33867ff
> llvm-spirv revision: e8f1964d0e58aacfe39c8ce7b43b64d6cabaed49
> ```
> 
> produce SPIR-V without a wrapper function with this command line:
> 
> `clang -c -target spirv32 -cl-kernel-arg-info -cl-std=clc++2021 issue55675.cl -S -o -`
> 
> so it is more close to the original source:
> 
> ```
> OpCapability Addresses
> OpCapability Kernel
> %1 = OpExtInstImport "OpenCL.std"
> OpMemoryModel Physical32 OpenCL
> OpEntryPoint Kernel %6 "foo"
> OpSource OpenCL_C 300000
> OpName %x0 "x0"
> OpName %entry "entry"
> OpDecorate %x0 FuncParamAttr NoCapture
> %void = OpTypeVoid
> %float = OpTypeFloat 32
> %_ptr_CrossWorkgroup_float = OpTypePointer CrossWorkgroup %float
> %5 = OpTypeFunction %void %_ptr_CrossWorkgroup_float
> %6 = OpFunction %void Pure %5
> %x0 = OpFunctionParameter %_ptr_CrossWorkgroup_float
> %entry = OpLabel
> OpReturn
> OpFunctionEnd
> ```
> 
> in case you would like to try importing it in the driver and check whether this is the root cause of the issue you are experiencing.
> 
> (Alternatively you can just use **spirv-as** on the output I have pasted to create a SPIR-V binary.)

Translating the readable SPIRV with **spirv-as** resulted in code that was possible to execute on in OpenCL, I will try to build the earlier revisions 
```
clang revision: 0045d01af96ff56c5b62d133be076020a33867ff
llvm-spirv revision: e8f1964d0e58aacfe39c8ce7b43b64d6cabaed49
```

**Comment by AnastasiaStulova** [comment]
Cool, it seems to me that the driver might not be able to handle the new SPIR-V format so it might make sense to see if there are any driver updates available where this is fixed or to raise a bug.

**Comment by jonasbhjulstad** [comment]
> Cool, it seems to me that the driver might not be able to handle the new SPIR-V format so it might make sense to see if there are any driver updates available where this is fixed or to raise a bug.

Do you mean that this is an issue from the OpenCL-side?

Building clang revision `0045d01af96ff56c5b62d133be076020a33867ff` did not solve the issue.

**Comment by AnastasiaStulova** [comment]
> > Cool, it seems to me that the driver might not be able to handle the new SPIR-V format so it might make sense to see if there are any driver updates available where this is fixed or to raise a bug.
> 
> Do you mean that this is an issue from the OpenCL-side?

yeah I think that OpenCL runtime might not be able to consume that SPIR-V correctly… it might be getting confused by the wrapper kernel or something.


> 
> Building clang revision `0045d01af96ff56c5b62d133be076020a33867ff` did not solve the issue.

Could you also please double check that you use this revision of llvm-spirv  https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/e8f1964d0e58aacfe39c8ce7b43b64d6cabaed49?

You should then generate identical SPIR-V output as in my previous comment:
 https://github.com/llvm/llvm-project/issues/55675#issuecomment-1137303875

**Comment by jonasbhjulstad** [comment]
> > > Cool, it seems to me that the driver might not be able to handle the new SPIR-V format so it might make sense to see if there are any driver updates available where this is fixed or to raise a bug.
> > 
> > 
> > Do you mean that this is an issue from the OpenCL-side?
> 
> yeah I think that OpenCL runtime might not be able to consume that SPIR-V correctly… it might be getting confused by the wrapper kernel or something.
> 
> > Building clang revision `0045d01af96ff56c5b62d133be076020a33867ff` did not solve the issue.
> 
> Could you also please double check that you use this revision of llvm-spirv [KhronosGroup/SPIRV-LLVM-Translator@e8f1964](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/e8f1964d0e58aacfe39c8ce7b43b64d6cabaed49)?
> 
> You should then generate identical SPIR-V output as in my previous comment: [#55675 (comment)](https://github.com/llvm/llvm-project/issues/55675#issuecomment-1137303875)

My bad, a proper installation of of the llvm-spirv revision resolved the issue. 
The problem has been forwarded to the [SPIRV-LLVM project](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/1486)
