### ISSUE TITLE
Failed to cross-compiling llvm from x86 to RISC-V

### ISSUE THREAD

**Issue by fourdim** [llvm/llvm-project#55671]
After merging https://github.com/llvm/llvm-project/commit/b1aed14bfea07508e4b9d864168c1ae6b5b5c665, we will generate following error when cross-compiling llvm from x86 to RISC-V.
```console
[37/2083] Building CXX object lib/LineEditor/CMakeFiles/LLVMLineEditor.dir/LineEditor.cpp.o
FAILED: lib/LineEditor/CMakeFiles/LLVMLineEditor.dir/LineEditor.cpp.o 
/usr/bin/clang++ -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/username/llvm-project/build_riscv/lib/LineEditor -I/home/username/llvm-project/llvm/lib/LineEditor -I/home/username/llvm-project/build_riscv/include -I/home/username/llvm-project/llvm/include --target=riscv64-unknown-linux-gnu --gcc-toolchain=/home/username/riscv --sysroot=/home/username/riscv/sysroot -march=rv64ifd -latomic -fvisibility-inlines-hidden -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -fdiagnostics-color -g  -fno-exceptions -fno-rtti -std=c++14 -MD -MT lib/LineEditor/CMakeFiles/LLVMLineEditor.dir/LineEditor.cpp.o -MF lib/LineEditor/CMakeFiles/LLVMLineEditor.dir/LineEditor.cpp.o.d -o lib/LineEditor/CMakeFiles/LLVMLineEditor.dir/LineEditor.cpp.o -c /home/username/llvm-project/llvm/lib/LineEditor/LineEditor.cpp
clang-13: warning: -latomic: 'linker' input unused [-Wunused-command-line-argument]
/home/username/llvm-project/llvm/lib/LineEditor/LineEditor.cpp:18:10: fatal error: 'histedit.h' file not found
#include <histedit.h>
         ^~~~~~~~~~~~
1 error generated.
```
It implies that we need libedit-dev(riscv-64) for cross-compiling, which is not expected. Any ideas?

**Comment by efriedma-quic** [comment]
The include is guarded by HAVE_LIBEDIT, so somehow CMake is detecting libedit.  Looks like CMake is picking up the host's libedit.  You can probably fix your CMake invocation to avoid that, but maybe LLVM could make the configuration a bit more friendly.

I suspect the use of pkg_check_modules is making FindLibEdit find host headers in cases where it shouldn't.

CC @MaskRay @upsj

**Comment by upsj** [comment]
related: https://github.com/llvm/llvm-project/issues/55445

**Comment by upsj** [comment]
A partial (though unsatisfying) answer might be given by setting appropriate environment variables for pkg-config/providing a wrapper looking in the right places: https://stackoverflow.com/questions/9221236/pkg-config-fails-to-find-package-under-sysroot-directory

**Comment by efriedma-quic** [comment]
As far as I can tell, there are exactly three references to the CMake PkgConfig package in llvm-project, none of them involving critical functionality.  If we remove all those uses, cross-compiling gets substantially simpler: there's one less tool to worry about configuring.  Can we find the appropriate headers/libraries some other way?

**Comment by upsj** [comment]
Probably, though I am too new to LLVM development to make such statements with any certainty. As a first step, I will try adding a check_include_file step to the FindLibEdit script and ignore the found header if it cannot be compiled

**Comment by upsj** [comment]
@efriedma-quic could you check whether https://reviews.llvm.org/D126450 works for you?

**Comment by fourdim** [comment]
> https://reviews.llvm.org/D126450

Hi, this works for me. I successfully cross-compiling llvm from x86 to riscv by applying this patch.
