### ISSUE TITLE
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.

### ISSUE THREAD

**Issue by ordinary-github-user** [llvm/llvm-project#55687]

**Comment by tstellar** [comment]
I deleted the comment all it contained was a link with no context that looked suspicious.  If you want to report a bug, please provide a description of the problem you are trying to report.

**Comment by ordinary-github-user** [comment]
> it contained was a link with no context that looked suspicious

agreed, godbolt.org is known to steal users bank account sometimes
