### ISSUE TITLE
[clang-optimizer] Arithmetic result truncated with -O1

### ISSUE THREAD

**Issue by venge-vimeo** [llvm/llvm-project#55694]
Sample: https://godbolt.org/z/WEYqe19fb

**Comment by megari** [comment]
There's a signed overflow in the example, which is UB, so clang not technically incorrect here. Try with ``-O1 -fwrapv`` and ``-O1 -fno-wrapv`` to see the difference.

**Comment by megari** [comment]
For a further reduced example, please see: https://godbolt.org/z/rj5T8neP9

**Comment by venge-vimeo** [comment]
thanks for explanation!

**Comment by nikic** [comment]
Closing per above comments. You can also use `-fsanitize=undefined` to detect such issues.
