### ISSUE TITLE
uninitialized member of the class template __policy_func

### ISSUE THREAD

**Issue by jsdejsde** [llvm/llvm-project#55690]
template <class _Rp, class... _ArgTypes> class __policy_func<_Rp(_ArgTypes...)>
https://github.com/llvm/llvm-project/blob/09c2b7c35af8c4bad39f03e9f60df8bd07323028/libcxx/include/__functional/function.h

The  member is not initialized in the first and not always in the second constructor. 
    __policy_storage __buf_;
  
This is problematic since the destructor may use this member in ~__policy_func() and other member functions may as well.

**Comment by philnik777** [comment]
The destructor only accesses `__buf_` if `__policy_->__destroy` is not null. When `__policy_->__destroy != nullptr` `__buf_` is initialized.
