### ISSUE TITLE
Wrong live-out from a simple code after backend optimizations

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5570]
|  |  |
| --- | --- |
| Bugzilla Link | [5198](https://llvm.org/bz5198) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@nlewycky |

## Extended Description 
with this simple code:
```
int f(int a,int b)
{
  if(a>b)
  {
    return a;
  }
  else if(a<-20) 
  {
    return 10-a;
  }
  return a+18;
}
```
and compiled with:
clang-cc -S -verify-machineinstrs --triple=arm-unknown-unknwon test-live.c -debug -o - -O3

output:
```
[...]
*** Bad machine code: Live-in physical register is not live-out from predecessor ***
- function:    f
- basic block: if.else 0xb4f1db0 (#1)
Register R0 is not live-out from MBB #&#8203;0.

*** Bad machine code: Live-in physical register is not live-out from predecessor ***
- function:    f
- basic block: return 0xb4f1e94 (#4)
Register R0 is not live-out from MBB #&#8203;0.
```
same problem with:
--triple=sparc-unknown-unknown
--triple=msp430-unknown-unknown
--triple=thumb-unknown-unknown
(so it's not target dependent)

There is a kill/def problem that seems to occur during SIMPLE REGISTER COALESCING phase.

**Comment by gwelymernans** [comment]
This doesn't fail for me with 13.0.1 or trunk. Probably fixed? If you're still running into this issue, please open another bug.
