### ISSUE TITLE
Backport 9ff4f2d (fix for #55134 clang-tidy) to release/14.x

### ISSUE THREAD

**Issue by Skylion007** [llvm/llvm-project#55717]
Initially copied wrong cherrypick here.

Backport this fix to release/14.x to fix the regression so we have a version of clang-tidy 14 that is actually usable on projects that use nolints in macros. See #55134 for more info. I tried to start the cherry pick PR myself, but as a new contributor I can't add the proper labels or milestones to this issue.

**Comment by EugeneZelenko** [comment]
@Skylion007: just add comment with proper command.

**Comment by Skylion007** [comment]
@EugeneZelenko I did in: https://github.com/llvm/llvm-project/issues/55717#issuecomment-1138726951

**Comment by Skylion007** [comment]
Ah, that worked. :)

**Comment by EugeneZelenko** [comment]
@Skylion007: At that time `Milestone` was not set.

**Comment by AaronBallman** [comment]
@tstellar -- I think it's a good one to backport.
