### ISSUE TITLE
[AArch64] -Ofast worsens optimisation of fnmadd pattern

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#55725]
```cpp
float fnmadd(float a, float b, float c)
{
	return -(a * c + b);
}
```
With `-O3`, LLVM outputs this:
```asm
fnmadd(float, float, float):                           // @fnmadd(float, float, float)
        fnmadd  s0, s0, s2, s1
        ret
```
`-Ofast` instead outputs this:
```asm
fnmadd(float, float, float):                           // @fnmadd(float, float, float)
        fmadd   s0, s2, s0, s1
        fneg    s0, s0
        ret
```
See also [Godbolt comparison](https://godbolt.org/z/Kc8TT4hre)

**Comment by vfdff** [comment]
as the following defined in InstCombineCalls.cpp, so separate fmul + fadd is more faster then a single fmuladd?
···
  case Intrinsic::fmuladd: {
    // Canonicalize fast fmuladd to the separate fmul + fadd.
    if (II->isFast()) {
      BuilderTy::FastMathFlagGuard Guard(Builder);
      Builder.setFastMathFlags(II->getFastMathFlags());
      Value *Mul = Builder.CreateFMul(II->getArgOperand(0),
                                      II->getArgOperand(1));
      Value *Add = Builder.CreateFAdd(Mul, II->getArgOperand(2));
      Add->takeName(II);
      return replaceInstUsesWith(*II, Add);
    }
···

**Comment by vfdff** [comment]
The original logic was introduced in commit 9205760
```
commit 920576042d53ab69298bdd13095f63a9bae2697b
Author: Matt Arsenault <Matthew.Arsenault@amd.com>
Date:   Thu Feb 16 18:46:24 2017 +0000

    InstCombine: Canonicalize fast fmuladd to fmul + fadd
```

**Comment by GabrielRavier** [comment]
If it is, then shouldn't it also be used with `-O3` ? It seems like doing so would result in more accurate code w.r.t. IEEE-754 conformance if my experience with x86 FMA is anything to go by...

**Comment by vfdff** [comment]
Yes, I was also surprised when I saw this code snippet.

**Comment by davemgreen** [comment]
At -O3 the Machine combiner is expected to fold into FMA on AArch64, based on scheduling info and critical path lengths. It is likely missing a pattern.

**Comment by vfdff** [comment]
It seems fixed now, https://godbolt.org/z/8d7M8EqxT

**Comment by davemgreen** [comment]
Sounds good - maybe it was fixed by https://reviews.llvm.org/D149260?
