### ISSUE TITLE
Segmentation fault in the Attributor pass when analyzing store instructions with byval arguments

### ISSUE THREAD

**Issue by ayrivera-intel** [llvm/llvm-project#55726]
Hi,

I attached an example that produces a segmentation fault in the Attributor pass. The example is pretty simple, a function `@foo` that allocates a space which is a structure, the argument of `@foo` is written in one field, then calls `@bar`. Function `@bar` will have the allocated space as parameter but set as byval and will write in another field of this space.

I'm not familiar with this optimization, but will try to explain the best I can. Tracing the issue I found that getAAFor is called in lib/Transform/IPO/AttributorAttributes.cpp line 1495 , the creation of an AA calls a function that updates the information (updateImpl), which calls translateAndAddCalleeState from line 1628 in the same file. In this function, the condition in 1296 (`IsByval && !RAcc.isRead()`) happens for one of the entries of the iterator (It.second). This means that addChange didn't run for a particular access.

Once the AA is created for line 1495, the function translateAndAddCalleeState runs again in line 1498. But now it have states (It) where the second entry in the pair is a null pointer. This produces a segmentation fault when traversing the loop in line 1296. It seems that skipping addChange during the first call of translateAndAddCalleeState prevents updating the access information and populates the map with null pointers.

The issue can be reproduced with the following command:

`opt -passes=attributor simple.ll -S`

I also attached a text file that contains the information of the crash.

[attributor_crash.txt](https://github.com/llvm/llvm-project/files/8783059/attributor_crash.txt)
[simple.zip](https://github.com/llvm/llvm-project/files/8783063/simple.zip)

**Comment by bar** [comment]
@ayrivera-intel Who call me? I'm a little confused here.

**Comment by ayrivera-intel** [comment]
> @ayrivera-intel Who calls me? I'm a little confused here.

Hi @bar,

Sorry for the confusion. I was trying to explain the behavior of the code calling function `@foo` and `@bar`. I didn't meant to tag you, neither @foo. I apologies for the inconveniences.

**Comment by ayrivera-intel** [comment]
Hi @jdoerfert ,

Sorry for taking your time. I wanted to ask if you have any comments or thoughts about this issue since you authored the changes for [AAPointerInfo](https://reviews.llvm.org/D104432). Does AAPointerInfo expects that the states for all attributes are generated? Again, thanks for your time.

**Comment by jdoerfert** [comment]
I'll upstream a fix tonight
