### ISSUE TITLE
`small example` link in `clang/docs/APINotes.rst` is invalid.

### ISSUE THREAD

**Issue by NikolaDucak** [llvm/llvm-project#55748]
On the [API Notes](https://clang.llvm.org/docs/APINotes.html) website page, the example link leads to a [404](https://clang.llvm.org/docs/test/APINotes/Inputs/Frameworks/SomeKit.framework/Headers/SomeKit.apinotes)

**Comment by JohnTitor** [comment]
https://reviews.llvm.org/D126599
