### ISSUE TITLE
```make install``` puts hmaptool in the wrong directory

### ISSUE THREAD

**Issue by danielh2942** [llvm/llvm-project#55753]
I built llvm/clang there and ran ```sudo make install``` and hmaptool was inserted at ```/usr/local/bin}/hmaptool``` rather than ```/usr/local/bin/hmaptool```

OS: openSUSE tumbleweed
latest commit in build:  0a2d2eed4321daa5e43698e0d379c583d151d27a

**Comment by danielh2942** [comment]
I have a patch, I need a reviewer

**Comment by keith** [comment]
I reviewed, do you have commit access? Otherwise I can land for you once CI is green

**Comment by danielh2942** [comment]
I don't have commit access, that'd be great if you can thanks!

**Comment by keith** [comment]
Thanks, done in https://github.com/llvm/llvm-project/commit/50f2e49924566330ea9aa731908f2864603bf4fb
