### ISSUE TITLE
[OpenCL] __opencl_c_work_group_collective_functions is not defined for SPIR-V target on OpenCL 3.0

### ISSUE THREAD

**Issue by haonanya** [llvm/llvm-project#55770]
Hi, @[AnastasiaStulova](https://github.com/AnastasiaStulova), @svenvh, @azabazno
__opencl_c_work_group_collective_functions is not defined for SPIRV https://github.com/llvm/llvm-project/blob/release/14.x/clang/lib/Headers/opencl-c-base.h#L67,L75, the test has compiling errors with the command `clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/clang++ -cc1 -include opencl-c.h -cl-std=CL3.0 -x cl -O2 -emit-llvm-bc -triple spir64 work_group_all.cl `:
work_group_all.cl:5:18: error: implicit declaration of function 'work_group_all' is invalid in OpenCL
    int result = work_group_all((input[tid] > input[tid+1]));
                 ^
./work_group_all.cl:5:18: note: did you mean 'sub_group_all'?
./opencl-c.h:16534:23: note: 'sub_group_all' declared here
int     __ovld __conv sub_group_all(int predicate);

Here is work_group_all.cl source:
__kernel void test_wg_all(global float *input, global int *output)
{
    int  tid = get_global_id(0);

    int result = work_group_all((input[tid] > input[tid+1]));
    output[tid] = result;
}

The test compiles successfully when add -D__opencl_c_work_group_collective_functions=1 or add __opencl_c_work_group_collective_functions definition for SPIRV on opencl-c-base.h.
Is the __opencl_c_work_group_collective_functions missing on opencl-c-base.h? Could you please have a look? Thanks very much.

**Comment by svenvh** [comment]
I've pushed a fix for the immediate issue as https://github.com/llvm/llvm-project/commit/a5cf17f8ae752f1b62b40b907bfee4faa3600b21 .  But I noticed some other discrepancies.  @AnastasiaStulova I wonder if we should merge the OpenCL C 2.0 and 3.0 feature macro blocks in [`clang/lib/Headers/opencl-c-base.h`](https://github.com/llvm/llvm-project/blob/d245974e1a7809f40d994548b46b4694f247fc99/clang/lib/Headers/opencl-c-base.h#L52) ?

**Comment by AnastasiaStulova** [comment]
> I've pushed a fix for the immediate issue as [a5cf17f](https://github.com/llvm/llvm-project/commit/a5cf17f8ae752f1b62b40b907bfee4faa3600b21) . But I noticed some other discrepancies. @AnastasiaStulova I wonder if we should merge the OpenCL C 2.0 and 3.0 feature macro blocks in [`clang/lib/Headers/opencl-c-base.h`](https://github.com/llvm/llvm-project/blob/d245974e1a7809f40d994548b46b4694f247fc99/clang/lib/Headers/opencl-c-base.h#L52) ?

Makes sense. Otherwise we will keep fixing the same issues in multiple places!
