### ISSUE TITLE
Function prototype with an undeclared struct, ends up making and discarding a temporary struct

### ISSUE THREAD

**Issue by russellw** [llvm/llvm-project#55775]
I ran into this problem when trying to compile cpython with clang. A reduced test case:

```c
void square(struct foo *f);
	
struct foo {
    int x;
};
	
void square(struct foo *f) {}
```

Microsoft C is happy with this, but clang treats the undeclared struct as meaning 'make a temporary declaration of the struct, then throw it away' and as such, when it does encounter the function definition, it thinks it is incompatible with the prototype.

**Comment by DimitryAndric** [comment]
clang warns about the first `struct foo` declaration, which is *only* valid for the duration of the declaration of `square()`:

```
pr55775.c:1:20: warning: declaration of 'struct foo' will not be visible outside of this function [-Wvisibility]
void square(struct foo *f);
                   ^
```

To solve this issue, you should declare `struct foo` separately, and before the first occurrence as a parameter in any following function declarations:

```c
struct foo;

void square(struct foo *f);

struct foo {
  int x;
};

void square(struct foo *f) {}
```

**Comment by russellw** [comment]
Indeed, that is the patch I've applied to my local copy of the cpython sources. Note that I am not a cpython maintainer, and have no authority to modify upstream, and this is not a case of me having a problem with using clang to compile my code, just something I ran into when attempting to compile cpython with clang, and figuring now that I understand what's going on here, I might as well report it.

**Comment by DimitryAndric** [comment]
Btw, lots of people seem to compile cpython with clang without any problems, so are you doing something special?

For example, I just built the `lang/python311` port on FreeBSD, which has clang 14.0 as the system compiler, and I saw no warnings or errors.

**Comment by russellw** [comment]
Hmm! Some of the other issues I have had, have been specific to the fact that I am doing it on Windows; I had assumed everyone else trying it, was doing so on Unix. But this particular issue does not seem like it should depend on the operating system. So I do not have an explanation for why it worked for you and not for me.
