### ISSUE TITLE
Comparison of results between clang command and gcc/g++ command

### ISSUE THREAD

**Issue by zzjss12** [llvm/llvm-project#55773]
I have a cpp file containing two simple functions. When I compile it with the clang command, it will generate 1000KB S file and 300KB EXE file, and then using g++ will only produce 5KB S file and 57kb EXE file.

What happened?
 In fact, I need to compile it like GCC so that I can disassemble it later. If I use the clang command, a large number of functions will be generated during disassembly. In fact, these additional functions are of no use to me.

Because I need to add corresponding comments in .s, I have to use clang command

**Comment by fhahn** [comment]
Without the file, there's no way of telling. GCC and LLVM/Clang can make different optimization decisions, leading to vastly different results, especially for larger programs.

Please provide a test case that shows the difference (using https://godbolt.org if possible). The Clang and GCC versions would also be helpful.

I'm closing the issue for now. We can re-open it once we have the required info.

**Comment by zzjss12** [comment]
using https://godbolt.org, The result is normal，You can see it here ：https://godbolt.org/z/6nG9fPGqr
But on my computer, when I use clang -s test.cpp -o test.s command will generate 1028kb .s file 
assembly codes are as follows
[1.txt](https://github.com/llvm/llvm-project/files/8801343/1.txt)
：

**Comment by fhahn** [comment]
`clang -s test.cpp -o test.s` won't build with optimizations, so a large size is not too surprising. The difference is likely due to some differences in the libc++ implementation used. With -O1,-O2,-O3 the differences should be mostly gone.

**Comment by zzjss12** [comment]
I tried three optimization options, and the results were almost the same.Should not be the reason for optimization.

**Comment by fhahn** [comment]
OK, but without knowing *what* exact version is causing the issue, there's not much we can do. It is strange that this doesn't reduce in godbolt, so it sounds like an issue with the specific Clang installation you are using.
