### ISSUE TITLE
Cherry-pick fix for incorrect removal of non-willreturn invoke

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#55777]
This is the fix for https://github.com/rust-lang/rust/issues/97428.

**Comment by nikic** [comment]
/cherry-pick 1f1de06165bb39f66049cdc942151fc6ed193123 2e101cca690645d63ae4de1eb7b0e11d322448fd

**Comment by nikic** [comment]
https://github.com/llvm/llvm-project/runs/6656609686?check_suite_focus=true exits with "PR already exists..." cc @tstellar

**Comment by nikic** [comment]
I think the correct way to check this is `pulls.totalCount != 0`.

**Comment by tru** [comment]
@nikic Ah! I must have missed to test all those cases. Let me NFC push your suggested fix and try it on this one.

**Comment by tru** [comment]
/cherry-pick 1f1de06165bb39f66049cdc942151fc6ed193123 2e101cca690645d63ae4de1eb7b0e11d322448fd

**Comment by tru** [comment]
Ok the "PR already exists" error is fixed - but now there is another problem that I don't understand: https://github.com/llvm/llvm-project/runs/6703381087?check_suite_focus=true#step:4:32

@tstellar do you think this is because of my changes? The error message from github there is really non-descriptive.

**Comment by tstellar** [comment]
Failed to create pull request for cherry-pick-willreturn

**Comment by tstellar** [comment]
Failed to create pull request for cherry-pick-willreturn

**Comment by tstellar** [comment]
@tru I think the problem is that the target repo is not a fork of llvm-project.  You can only create pull requests for forks.  We'll have to modify the script to copy the branch into the llvm-project-release-prs repo before we create the pull request.  I manually did this for this change.

**Comment by tru** [comment]
Ah so instead of pressing `fork` @nikic pushed the repo to his own github user? Maybe we could improve the message when you have to run `/branch ...` meanwhile: "Make sure you fork the main llvm-project" or something like that?

**Comment by nikic** [comment]
@tru The problem here isn't my repo, but rather llvm-project-release-prs, which is *not* a fork of llvm-project. Unfortunately, it seems to currently be impossible to create a fork in the same organization. It's on the roadmap, but not implemented: https://github.com/github/roadmap/issues/330

**Comment by tru** [comment]
I see. I am not sure I understand why this has worked before then, but never mind - it's not the fault of my check PR fix at lest.

**Comment by nikic** [comment]
> I see. I am not sure I understand why this has worked before then, but never mind - it's not the fault of my check PR fix at lest.

This is because we only recently switched to llvm-project-release-prs, previously https://github.com/llvmbot/llvm-project was used (which is a fork). So yes, this is unrelated to your changes.

**Comment by tstellar** [comment]
Merged: 885724c60cdc4b3fb221830d43e2ecd79ace9ce1 99b5eb2d3a61b55a61849cebabf1d5d66b4a13c4
