### ISSUE TITLE
Use of apt-key add is deprecated

### ISSUE THREAD

**Issue by ADKaster** [llvm/llvm-project#55784]
Since apt version 2.4.x, Debian/Ubuntu guidance is to avoid use of apt-key to unconditionally trust third party keys for any old package.

https://wiki.debian.org/DebianRepository/UseThirdParty
https://unix.stackexchange.com/questions/332672/how-to-add-a-third-party-repo-and-key-in-debian/582853#582853

The new approach is to drop the key into a secondary location, e.g. /etc/apt/keyrings or /usr/local/share/keyrings and add an entry to your sources.list for the repository that has a `signed-by` entry pointing to the third party gpg key.

Unfortunately it looks like add-apt-repository doesn't support supplying the signed-by entry yet, so it needs to be added manually.

https://bugs.launchpad.net/ubuntu/+source/software-properties/+bug/1862764

This affects the text of https://apt.llvm.org/ that provides manual instructions for adding the llvm-snapshot gpg key to the apt keyring, and the llvm.sh helper script that pipes the key to apt-key add itself.

Installing llvm 14 via llvm.sh on an ubuntu 22.04 jammy machine gives this deprecation warning on apt update:

```
W: http://apt.llvm.org/jammy/dists/llvm-toolchain-jammy-14/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

**Comment by elvenfighter** [comment]
As a workaround on Ubuntu one can use the following snippet:
```sh
cd /tmp
wget https://apt.llvm.org/llvm-snapshot.gpg.key

gpg --import llvm-snapshot.gpg.key # this will show you the ID of the key in the output
gpg --output llvm-snapshot.gpg --export 15CF4D18AF4F7421 # use the ID from earlier

sudo mv llvm-snapshot.gpg /etc/apt/trusted.gpg.d

gpg --delete-keys 15CF4D18AF4F7421 # clean up our user's keyring
```
This will convert the key from the old format (which APT would complain about) to the new one (OpenPGP v4). And would also get rid of the trusted.gpg deprecation warning.

**Comment by sylvestre** [comment]
fixed, the new method is now showed on apt.llvm.org

**Comment by masbug** [comment]
For anyone else stumbling here:
For Ubuntu:
```bash
curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/llvm-snapshot.gpg
sudo chmod a+r /etc/apt/keyrings/llvm-snapshot.gpg
echo   "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/llvm-snapshot.gpg] http://apt.llvm.org/"$(. /etc/os-release && echo "$VERSION_CODENAME")"/ llvm-toolchain-"$(. /etc/os-release && echo "$VERSION_CODENAME")" main" | sudo tee /etc/apt/sources.list.d/llvm-snapshot.list > /dev/null
echo   "deb-src [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/llvm-snapshot.gpg] http://apt.llvm.org/"$(. /etc/os-release && echo "$VERSION_CODENAME")"/ llvm-toolchain-"$(. /etc/os-release && echo "$VERSION_CODENAME")" main" | sudo tee -a /etc/apt/sources.list.d/llvm-snapshot.list > /dev/null
cat /etc/apt/sources.list.d/llvm-snapshot.list
```

**Comment by shurane** [comment]
Building on @masbug's comment. Since changing from .list to the [.sources](https://wiki.debian.org/SourcesList) format, setting up the keyring looks slightly cleaner now:

```shell
# same as before
curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/llvm-snapshot.gpg
sudo chmod a+r /etc/apt/keyrings/llvm-snapshot.gpg
source /etc/os-release #to source $VERSION_CODENAME

sudo tee /etc/apt/sources.list.d/llvm.sources <<EOF
Enabled: yes
Types: deb
URIs: http://apt.llvm.org/$VERSION_CODENAME/
Suites: llvm-toolchain-$VERSION_CODENAME
Components: main
Signed-By: /etc/apt/keyrings/llvm-snapshot.gpg
EOF
```
