### ISSUE TITLE
docs: Switch to MyST from recommonmark

### ISSUE THREAD

**Issue by polyzen** [llvm/llvm-project#55787]
> **Warning:** recommonmark is now deprecated. We recommend using [MyST](https://github.com/executablebooks/MyST-Parser) for a docutils bridge going forward. See [this issue](https://github.com/readthedocs/recommonmark/issues/221) for background and discussion.

**Comment by xgupta** [comment]
duplicate of https://github.com/llvm/llvm-iwg/issues/30.
