### ISSUE TITLE
Failing to instantiate some members during an explicit instantiation

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#55794]
Consider the following code:
```cpp
template <class RealType>
class TestLib {
 public:
  TestLib();
  void print();
};
template <class RealType>
TestLib<RealType>::TestLib() {}

template class TestLib<double>;

template <class RealType>
void TestLib<RealType>::print() {}

template class TestLib<float>;
```
When compiled with Clang, only `void TestLib<float>::print()` is instantiated, but when compiled with GCC, ICC, and MSVC, `void TestLib<double>::print()` is also instantiated. I believe Clang is incorrect per http://eel.is/c++draft/temp.explicit#10 and should also be instantiating the `double` version of `print()`.

**Comment by royjacobson** [comment]
The next paragraph says

> An explicit instantiation definition that names a class template specialization explicitly instantiates the class template specialization and is an explicit instantiation definition of only those members that have been defined at the point of instantiation[.](http://eel.is/c++draft/temp.explicit#11.sentence-1)

And since `print()` does not have a definition at the PoI I don't think it should be instantiated, unless I'm missing something?
