### ISSUE TITLE
with clang 13, optimization of undefined behavior incorrectly eliminates conditional earlier in the function

### ISSUE THREAD

**Issue by justincady** [llvm/llvm-project#55802]
Beginning with clang 13.0.0, the following behavior is observed beginning at `-O1`:

```c
extern int foo;
void bar(void);
int foo;
void comparison_eliminated() {
    // clang 13+ eliminates this conditional at O1+
    if ( foo ) {
        bar();
    }
    // ...but only in the presence of undefined behavior.
    // Comment out these two lines and the conditional returns.
    char* a = 0;
    *a = '\0';
}
```

[Godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:13,positionColumn:2,positionLineNumber:13,selectionStartColumn:2,selectionStartLineNumber:13,startColumn:2,startLineNumber:13),source:'extern+int+foo%3B%0Avoid+bar(void)%3B%0Aint+foo%3B%0Avoid+comparison_eliminated()+%7B%0A++++//+clang+13%2B+eliminates+this+conditional+at+O1%2B%0A++++if+(+foo+)+%7B%0A++++++++bar()%3B%0A++++%7D%0A++++//+...but+only+in+the+presence+of+undefined+behavior.%0A++++//+Comment+out+these+two+lines+and+the+conditional+returns.%0A++++char*+a+%3D+0%3B%0A++++*a+%3D+!'%5C0!'%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang1300,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-O1',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x86-64+clang+13.0.0+(C%2B%2B,+Editor+%231,+Compiler+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

With clang 12, this behavior does not happen.

I realize with the undefined behavior in place all bets are off to a some degree. But is it expected that eliminating the null dereference here would _also_ result in `bar` being called unconditionally? Or is there a bug within the UB optimization?

Thanks!

**Comment by justincady** [comment]
@fhahn Please forgive me if I'm missing something, but:

> so the only valid non-UB execution of the function is that foo is true and bar executes but never returns.

What about the case of `foo` being false? It's non-const, non-static and its value could change over the lifetime of the program. Even if the null pointer dereference is eliminated, `bar` should only be invoked when `foo` is actually true, correct?

**Comment by fhahn** [comment]
Clang/LLVM assumes UB can never happen. If `foo` would be false, the nullptr dereference would be executed, meaning  we hit UB and technically anything can happen. In this case , it's `bar` being executed. In other words, we assume that UB can never happen, hence `foo` must always be true.

**Comment by justincady** [comment]
Thank you for the explanation. With those additional details I understand your initial response now. 😅
