### ISSUE TITLE
llvm-mt breaks Windows build when not compiled with XML support

### ISSUE THREAD

**Issue by penzn** [llvm/llvm-project#55817]
Windows 10 Enterprise, Visual Studio Enterprise 2022 (17.1.6), 11th Gen Intel(R) Core(TM) i7-1185G7.

Reproduces on `main` and `release/14.x`.

CMake shipped with VS picks up `llvm-mt` as manifest tool, which throws an error if it wasn't compiled with `libxml2` support. To reproduce - build and install `clang` locally, then attempt to use it as a C or C++ compiler from a CMake project. For example, configuring LLVM build with Clang:

```console
> cmake -GNinja -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DLLVM_ENABLE_PROJECTS="llvm;clang" ..\llvm-project\llvm
-- The C compiler identification is Clang 15.0.0 with MSVC-like command-line
-- The CXX compiler identification is Clang 15.0.0 with MSVC-like command-line
-- The ASM compiler identification is Clang with MSVC-like command-line
-- Found assembler: C:/Users/ppenzin/llvm/trunk/bin/clang-cl.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Users/ppenzin/llvm/trunk/bin/clang-cl.exe
-- Check for working C compiler: C:/Users/ppenzin/llvm/trunk/bin/clang-cl.exe - broken
CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "C:/Users/ppenzin/llvm/trunk/bin/clang-cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/ppenzin/Dev/llvm/build-clang/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/PROGRA~1/MICROS~3/2022/ENTERP~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe cmTC_f9408 && [1/2] Building C object CMakeFiles\cmTC_f9408.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_f9408.exe
    FAILED: cmTC_f9408.exe
    cmd.exe /C "cd . && "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_f9408.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\Users\ppenzin\llvm\trunk\bin\llvm-mt.exe --manifests  -- C:\Users\ppenzin\llvm\trunk\bin\lld-link.exe /nologo CMakeFiles\cmTC_f9408.dir\testCCompiler.c.obj  /out:cmTC_f9408.exe /implib:cmTC_f9408.lib /pdb:cmTC_f9408.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    MT: command "C:\Users\ppenzin\llvm\trunk\bin\llvm-mt.exe /nologo /manifest CMakeFiles\cmTC_f9408.dir/intermediate.manifest /out:CMakeFiles\cmTC_f9408.dir/embed.manifest /notify_update" failed (exit code 0x1) with the following output:
    llvm-mt: error: no libxml2
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:55 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/ppenzin/Dev/llvm/build-clang/CMakeFiles/CMakeOutput.log".
See also "C:/Users/ppenzin/Dev/llvm/build-clang/CMakeFiles/CMakeError.log".
```

~It would be reasonable not to provide `llvm-mt` executable when `libxml2` isn't present, because it won't be able to process manifests and would only cause compilation to fail.~ Edit: `llvm-mt` is needed by a number of other targets, just disabling it when libxml isn't present won't work.

**Comment by penzn** [comment]
Discourse discussion containing potential workarounds: https://discourse.llvm.org/t/cannot-cmake-self-hosted-clang-on-windows-for-lack-of-libxml2/58793

**Comment by nico** [comment]
https://reviews.llvm.org/D129571

**Comment by penzn** [comment]
This would be good to add to developer docs or build via external project (like was suggested in review).

**Comment by zmodem** [comment]
145835caaedc32fa9158a5058de9a12df4b22f84 will fix this for the releases. As mentioned on the review I'll try to update the docs too.

Having said that, I think CMake really jumped the gun on this. Even with libxml2 in the build, llvm-mt isn't ready to replace mt.exe in general, so it seems like a bad default choice. I also wonder how they tested this, since as we've seen in this bug it would have failed if they used the official llvm package.

**Comment by penzn** [comment]
> Having said that, I think CMake really jumped the gun on this. Even with libxml2 in the build, llvm-mt isn't ready to replace mt.exe in general, so it seems like a bad default choice. I also wonder how they tested this, since as we've seen in this bug it would have failed if they used the official llvm package.

In discourse somebody mentioned that it is probably worth filing a bug in CMake, and it might be still worth it. I am not familiar with differences between llvm-mt vs mt.

Thank you for adding the note!

**Comment by zmodem** [comment]
It looks like CMake reverted this already, in https://gitlab.kitware.com/cmake/cmake/-/commit/73d0d4e4b5dd937dcc913a94a6ebac3085a01896
I've added a comment to the bug for that: https://gitlab.kitware.com/cmake/cmake/-/issues/23305#note_1217988

**Comment by IGR2014** [comment]
Actually, should llvm-mt be installed from release on Windows ?

During install of Clang 15.0.7 I can't see llvm-mt.exe in the list of installed files.
Also, when trying to use LLVM's clang-cl with CMake and Ninja, sometimes I got error which is caused? I believe, by this part of commandline:

`... --rc=<PATH_TO_LLVM_INSTALLATION>/llvm-rc.exe --mt=CMAKE_MT-NOTFOUND ...`

OS: Windows 7
LLVM: 15.0.7
CMake: 3.25.0
Ninja: 1.11.1

**Comment by IGR2014** [comment]
> You're right, it's not in the installer right now. I suppose no one figured it was ready yet.

Well, now I figured out)
Thanks for the explanation!
