### ISSUE TITLE
libc++: C++17 mathematical special functions not implemented

### ISSUE THREAD

**Issue by SanjayVas** [llvm/llvm-project#55818]
See:

- https://discourse.llvm.org/t/interest-in-p0226r1-mathematical-special-functions-for-c-17/55654
- https://releases.llvm.org/14.0.0/projects/libcxx/docs/Status/Cxx17.html
- https://wg21.link/P0226R1

**Comment by philnik777** [comment]
We are obviously aware of that, but there is nobody interested enough to submit patches currently. If you are interested feel free to submit patches for them, but I wouldn't consider this an issue (that should be tracked on GitHub).
