### ISSUE TITLE
[ARM][ASSEMBLER] literal pool entries are not merged

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#55816]
[reported](https://lore.kernel.org/linux-arm-kernel/20220530112417.2492510-1-ardb@kernel.org/) by @ardbiesheuvel 

Consider the following asm:
```asm
.global foo
foo:
  ldr r0, =foo
  ldr r0, =foo
```
With `arm-linux-gnueabi-as x.s -o x.o; llvm-objdump -dr x.o` we get:
```asm
00000000 <foo>:
       0: 00 00 1f e5  	ldr	r0, [pc, #-0]           @ 0x8 <$d>
       4: 04 00 1f e5  	ldr	r0, [pc, #-4]           @ 0x8 <$d>

00000008 <$d>:
       8:	00 00 00 00	.word	0x00000000
			00000008:  R_ARM_ABS32	foo
```
with `clang --target=arm-linux-gnueabi x.s -c; llvm-objdump -dr x.o` we get:
```asm
00000000 <foo>:
       0: 00 00 9f e5  	ldr	r0, [pc]                @ 0x8 <$d.1>
       4: 00 00 9f e5  	ldr	r0, [pc]                @ 0xc <$d.1+0x4>

00000008 <$d.1>:
       8:	00 00 00 00	.word	0x00000000
			00000008:  R_ARM_ABS32	foo
       c:	00 00 00 00	.word	0x00000000
			0000000c:  R_ARM_ABS32	foo
```
I'm guessing we could save some space by not repeatedly emitting the same data twice with two different relocations.

**Comment by luxufan** [comment]
Candidate patch https://reviews.llvm.org/D127113

**Comment by nickdesaulniers** [comment]
thanks for the patch!
