### ISSUE TITLE
backport 18efa420 - compiler-rt: Allow build without __c11_atomic_fetch_nand

### ISSUE THREAD

**Issue by brooksdavis** [llvm/llvm-project#55813]
Please backport 18efa420da5fa065d88ba451cdcdbd950a2090c1 to fix FreeBSD builds with older compilers (e.g., clang 13) where a toolchain isn't bootstrapped.

**Comment by tstellar** [comment]
@efriedma-quic What do you think about backporting this?

**Comment by efriedma-quic** [comment]
Fine to backport.  Change is very conservative, and the relevant code isn't even built by default.

**Comment by brad0** [comment]
Looks like this would help for OpenBSD and we would trip over the same problem.

**Comment by tru** [comment]
@tstellar should be fine to merge (I can't update status in the project).

**Comment by tstellar** [comment]
Merged: 483db58f3eb5c625615e212283800cea2cb04b3e
