### ISSUE TITLE
[GreedyRA] Assert  triggered: "Non-empty but used interval"

### ISSUE THREAD

**Issue by serguei-katkov** [llvm/llvm-project#55827]
The test below triggers an assert in greedy register allocator.

At the moment I see the following reason of an assert:
1) During last chance recoloring some live interval is unassigned from physical register
2) Then it is split by region split and completely replaces by others live intervals corresponding to new registers. On this stage instructions are updated.
3) If re-coloring failed, the rollback is started. On this stage the original live interval corresponding to original register which does not have any uses now is assigned back to original physical register (it looks very strange).
4) Later on handling another live interval , our live interval is evicted.
5) Finally RegAllocBase in allocatePhysRegs complains with assert that Live interval has no nodbg uses but interval is not empty.

How to reproduce:

```console
$ llc -x mir -mattr="+reserve-x28" --start-before=greedy 5.mir
...RegAllocBase.cpp:152: void llvm::RegAllocBase::allocatePhysRegs(): Assertion `SplitVirtReg->empty() && "Non-empty but used interval"' failed
```

The reproducer is attached as 5.txt in the next comment.

**Comment by serguei-katkov** [comment]
The reproducer:
[5.txt](https://github.com/llvm/llvm-project/files/8820636/5.txt)

**Comment by BlaM** [comment]
Why do I get email notifications for this issue? I don't even know the project?

**Comment by arsenm** [comment]
Could it be picking up "@blam" from the attached testcase?

**Comment by serguei-katkov** [comment]
> Could it be picking up "@BlaM" from the attached testcase?

What does it mean?

**Comment by kito-cheng** [comment]
>> Could it be picking up "@BlaM" from the attached testcase?
> What does it mean?

I guess he mean there is a function called `@blam` in  attached testcase(`5.txt`) and that might be the reason why @BlaM got mail :P

**Comment by serguei-katkov** [comment]
Fixed with 
commit 095bf6be28c5308a7e7c2cbc5a84adbb11bef57d (HEAD -> ZVM-23622-2, origin/main, origin/HEAD)
Author: Serguei Katkov <serguei.katkov@azul.com>
Date:   Wed Jun 8 16:21:01 2022 +0700

    [Greedy RegAlloc] Fix the handling of split register in last chance re-coloring.

    This is a fix for https://github.com/llvm/llvm-project/issues/55827.

    When register we are trying to re-color is split the original register (we tried to recover)
    has no uses after the split. However in rollback actions we assign back physical register to it.
    Later it causes different assertions. One of them is in attached test.

    This CL fixes this by avoiding assigning physical register back to register which has no usage
    or its live interval now is empty.

    Reviewed By: arsenm, qcolombet
    Subscribers: llvm-commits
    Differential Revision: https://reviews.llvm.org/D127281

**Comment by serguei-katkov** [comment]
Fixed.
