### ISSUE TITLE
[Flang] An array store operation is incorrectly recognized as a statement function 

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#55834]
An array store operation is incorrectly recognized as a statement function. This causes updates to the array to be lost. A Walk over the parse-tree (in flang/lib/Semantics/rewrite-parse-tree.cpp)  generally corrects all such statement functions to arrays accesses, but not clear why that did not happen here.
Investigate and create a fix for this issue. A minimum reproducer is given below.
```fortran
module md1
  integer, dimension(1) :: np
end module
subroutine sb(x,y)
  use md1
  integer :: x, y
  np(x) = y
end subroutine
```

This issue was found while investigating 554.roms_r.

**Comment by klausler** [comment]
This bug also cropped up in nvidia's testing; a fix will eventually be pushed to llvm-project, so don't bother trying to fix it redundantly.

**Comment by kiranchandramohan** [comment]
Thanks, @klausler for the info. I am temporarily assigning this to you so that others will not work on it.

**Comment by klausler** [comment]
https://reviews.llvm.org/D127430 is out for review.
