### ISSUE TITLE
Clang can wrongly calculate a value

### ISSUE THREAD

**Issue by ackelcn** [llvm/llvm-project#55878]
When I read the code of TOWNSEMU, I notice that it encountered a possible clang bug. The following commit explains the bug:
https://github.com/captainys/TOWNSEMU/commit/b396b76a0db38c1d1ba84242b500e1b38cf085b2

It complains that when i is -0x80000000, clang does not consider it as a negative number.

**Comment by topperc** [comment]
Negating 0x8000000 in an `int` is undefined behavior in C as it is considered signed integer overflow.

**Comment by fhahn** [comment]
Closing as per @topperc's comment. The code has UB, which makes the optimization correct.
