### ISSUE TITLE
[packaging] Building LLVM 15 source packages from apt.llvm.org fails in clean pbuilder environment

### ISSUE THREAD

**Issue by TheRealCuran** [llvm/llvm-project#55882]
Since recent LLVM versions [break Mesa](https://gitlab.freedesktop.org/mesa/mesa/-/issues/6615) and apt.llvm.org only offers the very latest build, I wanted to build the last known working version (`1:15~++20220601100758+8c8a2679a20f-1~exp1~20220601220850.532`) myself. Therefore I downloaded the source package as offered by https://llvm-jenkins.debian.net/job/llvm-toolchain-source/532/ with `dget` (`dget https://llvm-jenkins.debian.net/job/llvm-toolchain-source/532/artifact/llvm-toolchain-snapshot_15%7E++20220601100758+8c8a2679a20f-1%7Eexp1%7E20220601220850.532.dsc`) and used a clean `pbuilder` ([PTS](https://tracker.debian.org/pkg/pbuilder)) unstable (Sid) environment to build the package. This fails with an error, telling me the stage2 `clang++` binary was not found.

The problem seems to stem from `debian-libfuzzer-build` (`debian-libclc-build` would probably trigger this as well, but for me `debian-libfuzzer-build` is executed first) being executed in parallel to `debian-full-build`, ie. before `debian-full-build` is finished. I have no idea what you do on Jenkins to make it work there, though I guess it's probably something like `-j1`. And since make will wait for all jobs to finish, the time to fail is rather high (`debian-full-build` is run in total).

In addition there is the `CMP0114` warning raised with current CMake versions. But those can easily be suppressed for now by setting the policy to `OLD` (something like [set_cmake_stage_policy.patch](https://github.com/llvm/llvm-project/files/8840018/set_cmake_stage_policy.patch.txt)).

Please enforce a proper rule dependency chain in `debian/rules`. For me it was enough to make the following changes:
```patch
--- a/debian/rules
+++ b/debian/rules
@@ -642,7 +642,7 @@
        fi
        touch $@
 
-debian-libfuzzer-build:
+debian-libfuzzer-build: debian-full-build
 ifeq (${LIBFUZZER_ENABLE},yes)
        cd $(TARGET_BUILD); \
        CFLAGS="$(opt_flags) $(STAGE_2_CFLAGS)"; \
@@ -652,7 +652,7 @@
 endif
        touch $@
 
-debian-libclc-build:
+debian-libclc-build: debian-full-build
 ifeq ($(LLVM_SPIRV_INSTALLED),yes)
 # Builds libclc
        mkdir -p libclc/build
```

**Comment by TheRealCuran** [comment]
Tagging @sylvestre manually, since I did get a notification, that "auto-subscribe" failed from GitHub.

**Comment by sylvestre** [comment]
Would you mind preparing a MR on https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/tree/14 ?
thanks

**Comment by TheRealCuran** [comment]
My account on salsa seems deactivated. I've written to the admins, but I have no idea when it will get reactivated. Could you maybe just change those two lines directly?

**Comment by TheRealCuran** [comment]
This seems to be fixed again. At least v16 packages were building for me.
