### ISSUE TITLE
Compile-time regression in 15.0.0

### ISSUE THREAD

**Issue by Daniel-Atanasov** [llvm/llvm-project#55888]
I've noticed a huge regression in compile-times on one of my projects (Win11-x64):
14.0.4
```
[build] ===-------------------------------------------------------------------------===
[build]                           Clang front-end time report
[build] ===-------------------------------------------------------------------------===
[build]   Total Execution Time: 0.5156 seconds (0.5249 wall clock)
[build] 
[build]    ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
[build]    0.4688 (100.0%)   0.0469 (100.0%)   0.5156 (100.0%)   0.5249 (100.0%)  Clang front-end timer
[build]    0.4688 (100.0%)   0.0469 (100.0%)   0.5156 (100.0%)   0.5249 (100.0%)  Total
```

15.0.0 (ed71a0b45b6c927333fa2c91e16f75a251408691)
```
[build] ===-------------------------------------------------------------------------===
[build]                           Clang front-end time report
[build] ===-------------------------------------------------------------------------===
[build]   Total Execution Time: 7.7188 seconds (7.8246 wall clock)
[build] 
[build]    ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
[build]    7.6719 (100.0%)   0.0469 (100.0%)   7.7188 (100.0%)   7.8246 (100.0%)  Clang front-end timer
[build]    7.6719 (100.0%)   0.0469 (100.0%)   7.7188 (100.0%)   7.8246 (100.0%)  Total
```

Times are from `-ftime-report`, only difference is in "Clang front-end time report" and the rest of the times don't seem any different.
Build is just as slow in debug.
I couldn't reproduce a minimal example, but here are the compile options:
Cmake properties:
```
C_STANDARD 23
C_EXTENSIONS ON
CXX_STANDARD 23
CXX_EXTENSIONS ON
```
Compiler arguments
```
-ftime-report
-fno-exceptions
-fno-rtti
-fno-builtin
-ffreestanding
-fdiagnostics-absolute-paths
-ferror-limit=0
-fmacro-backtrace-limit=0
-fdiagnostics-color
-nodefaultlibs
-nostdlib
-Wno-microsoft-template

Debug:
-Og
-g

Release:
-Ofast
-flto
-march=native
```
Linker arguments:
```
LINKER:/subsystem:console,/entry:entry_point
```

**Comment by tbaederr** [comment]
This isn't really actionable without any way to reproduce...

**Comment by fhahn** [comment]
@Daniel-Atanasov without a reproducer there is not much that can be done unfortunately. Do you know in which functions the frontend spends all that extra time?

**Comment by Daniel-Atanasov** [comment]
Ah, it seems this is the culprit: `#include <Windows.h>`. When removed, compile-time is as expected.

I could reproduce it with this:
```cpp
// main.cpp

#include <Windows.h>

int main() {
  return 0;
}
```
And then just `clang main.cpp`.

**Comment by Daniel-Atanasov** [comment]
Ah my bad - my clang was built without optimizations.
I had configured with Ninja Multi-Config and built with `cmake --build build --config=Release`, but that doesn't actually enable optimizations, for some reason.
Configuring with Ninja and CMAKE_BUILD_TYPE=Release builds properly, and build times are the same as 14.0.4

**Comment by fhahn** [comment]
Ok thanks for confirming. Sound like there's nothing to fix.
