### ISSUE TITLE
ld64.lld reports duplicated symbol error when linking archives created in certain ways

### ISSUE THREAD

**Issue by PRESIDENT810** [llvm/llvm-project#55893]
How to produce:
main.cpp
```C++
int foo();
int bar();

int main(int argc, char** argv) {
  bar();
  foo();
  return 0;
}
```

foo1.cpp
```C++
int foo(){
  return 1;
}
```

foo2.cpp
```C++
int foo(){
  return 1;
}

int bar(){
  return 1;
}
```

```bash
clang -c foo1.cpp foo2.cpp main.cpp
ar rcs libfoo.a foo1.o foo2.o
clang -fuse-ld=/Users/bytedance/github/llvm-project/build/bin/ld64.lld main.o libfoo.a
```
Then lld will report the following error:
```
ld64.lld: error: duplicate symbol: __Z3foov
>>> defined in libfoo.a(foo1.o)
>>> defined in libfoo.a(foo2.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
However, using Apple OSX's ld64 is fine (just remove -fuse-ld option and rerun the last shell command)

It is interesting that if you exchange the content of foo1.cpp and foo2.cpp:

foo1.cpp
```C++
int foo(){
  return 1;
}

int bar(){
  return 1;
}
```

foo2.cpp
```C++
int foo(){
  return 1;
}
```

Move the function `bar()` to foo1.cpp, and then rerun the shell commands above. This time lld would work fine.

I inspected the source code of ld64.lld a little bit, and my guess is that, when ld64.lld was looking for symbol for  `foo()`, it loads the first object file it finds. If this object file contains the symbol for `bar()`, then lld will not bother to load the second object file, because it already has everything it needs to link the final executable file. However, if the first object file contains the symbol for `foo()` only, and doesn't contains the symbol for `bar()`, lld will try to load the second object file in order to search the symbol for `bar()`. At this time, lld realized that it already has loaded the `foo()`, so it throws the duplicated symbol error.

I'm not sure whether this is the correct behavior, but many Apps in my company suffer from this because they have lots of duplicated symbols. When we were using Apple's ld64, it just works magically (maybe because of the certain linking order of our input object files). Therefore, we fail to use lld as a drop-in replacement for ld64.

I know the right way to solve this problem is to refactor our codes (could be difficult, since there are tons of them...), but I'm wondering whether is there any other easier way to work around this?

**Comment by flybrotherlixiang** [comment]
same issue here, has any team been using ld64.lld on their products for release build?

**Comment by PRESIDENT810** [comment]
Some thoughts here. If, we want to make such cases legal for linking by lld, I think we can try this way:

If we encounter a duplicated symbol when trying to locate a new symbol, for example, `bar()` in foo2.cpp in my case, and then we realize that foo2.cpp also introduces `foo()`, which is duplicated because of `foo()` in foo1.cpp. We can "unload" all symbols from foo1.cpp, which is equivalent to the circumstance that we encounter foo2.o first and never loads foo1.o. This is still a legal case since by loading everything from foo2.cpp, we don't need anything else from foo1.cpp, so we will not load it as well. This is the same as reordering the linking order, and this way allows lld to behave exactly as ld64's behavior, makes it more likely a drop-in replacement for ld64.

I'm a novice at llvm, so that's just some naive thought, but I think it, nevertheless, can solve this issue.

**Comment by keith** [comment]
I believe this falls under an expected difference documented here https://github.com/llvm/llvm-project/blob/facbfb121a5c0a78b3cc4ecc41b15dcef8d9c6a5/lld/MachO/ld64-vs-lld.rst#objc-symbols-treatment

**Comment by oontvoo** [comment]
My $0.2: This is an ODR violation - and I don't believe we should implement hacks to allow it. Other ports (ELF/COFF) would all have reported duplicate-symbol errors for this case. (Looking at LD64's code, I'd hazard a guess that it only allows by "accident") 

re: "drop-in replacement for LD64": perhaps we could clarify that the goal is to have a replacement for LD64 as opposed to to have **another** LD64 - as such, replicating bugs needs not be necessary?

**Comment by int3** [comment]
Yeah as @oontvoo says, this seems like an ODR issue.

FWIW this "works" with ld64 only because it looks up symbols from archives alphabetically. If we replace `bar` with `zar` in @PRESIDENT810's example, we get a dup symbol error from ld64 too. (LLD-MachO follows LLD-ELF's behavior of looking up the symbols in CLI argument order instead. This is easier to implement efficiently and does not cause a problem with most builds.)

@PRESIDENT810 your "unload" idea was actually my first guess at how ld64 worked too, back when I first implemented symbol loading :) but yeah ld64 is doing something a lot less clever... and your builds are possibly more fragile than you think ;)

I suppose we could add an option to ignore dup symbols and just pick the first one that we load, but that seems extremely sketchy. I really do think this should be fixed at the build level.

@flybrotherlixiang we (Meta) are using LLD in some major builds internally, and know of several other companies who have adopted it as well.

**Comment by PRESIDENT810** [comment]
Yep, now I understand how this duplicated symbol error is thrown. It seems that lld is just doing what it is supposed to do, and the fact that we can successfully link using ld64 could be purely a matter of luck. Guess the best solution is to solve those duplicated symbol at the build stage (could be painful, since people who wrote those codes are really reluctant to fix them...). Anyway, thank you guys!
