### ISSUE TITLE
how to run libfuzzer on MC layer

### ISSUE THREAD

**Issue by chasays** [llvm/llvm-project#55892]
I see the [libFuzzer document](https://llvm.org/docs/LibFuzzer.html), and build `llvm-mc-assemble|disassemble-fuzzer` binary to run, [the whole command](https://llvm.org/docs/FuzzingLLVM.html#llvm-mc-assemble-fuzzer) as below

`llvm-mc-assemble-fuzzer --fuzzer-args -max_len=100  ./corpus`

but after approximately 1s, the crash(heap_buffer_overflow) found.  I thought the fuzzer didn't deep in layer

1. how to continue when crashes found
2. since using LTS llvm, I think it shouldn't like this, can anyone talk me whether it is right? thx

**Comment by fhahn** [comment]
For questions, please use https://discourse.llvm.org
