### ISSUE TITLE
backport clang-tidy fix in 8b90b25 to clang 14

### ISSUE THREAD

**Issue by Skylion007** [llvm/llvm-project#55902]
Backports a bugfix of clang-tidy to clang-tidy 14. The commit fixes a bug in the use-after-move check the caused it to incorrectly handle move captures for C++14 lambda

/cherrypick 8b90b25

**Comment by tstellar** [comment]
@njames93 What do you think about backporting this? https://github.com/llvm/llvm-project/commit/8b90b2539048a581052a4b0d7628ffba0cd582a9

**Comment by njames93** [comment]
The fix isn't likely to cause any stability issues. However, as the issue wasn't a regression or caused stability issues, it's probably not worth it to backport this.

**Comment by Skylion007** [comment]
@njames93 Also, this is a nit but there is a typo in the changelog (the linked clang-tidy check anchor is incorrect). Someone may want to open a PR on master to fix it.

**Comment by whisperity** [comment]
> Also, this is a nit but there is a typo in the changelog (the linked clang-tidy check anchor is incorrect). Someone may want to open a PR on master to fix it.

@Skylion007 Do you have commit rights to the project? Just push a quick NFC commit about it up. Adding a ` isn't really patch and review worthy.

**Comment by Skylion007** [comment]
@whisperity No, I do not have commit rights to the project.

**Comment by tstellar** [comment]
@njames93 Even though it's not a regression fix, it still meets the criteria for backports, so since it's safe, I'll backport this.

**Comment by tstellar** [comment]
Merged: deb573739df9
