### ISSUE TITLE
PIE Metadata Forces Codegenning Illegal Relocations R_X86_64_TPOFF32 and R_X86_64_PC32 for Shared Libraries 

### ISSUE THREAD

**Issue by EmmaJaneBonestell** [llvm/llvm-project#55909]
On Ubuntu 22.04 / glibc 2.35/ x86_64 

For the past month or so, give or take a few weeks, I've noticed an intermittent issue with LLVM trying to generate (from bitcode) R_X86_64_TPOFF32  (the local-exec tls model) and R_X86_64_PC32 for shared-libraries, which is improper,so it errors out. 

The short of it is that bitcode with PIE metadata >0 cannot be linked into shared libraries without untenable and unreasonable effort. 

A link to a tar with lld's reproducer output for some very simple test code that will result in both improper relocations is at the bottom. 

I primarily ran into this issue when attempting to build the libLLVM dylib; if any of the dependent third-party libraries are linked in as bitcode, and they contain PIE metadata, it may result in many complaints about the symbols declared with LLVM_THREAD_LOCAL, such as PrettyStackTraceEntry and TimeTraceProfilerInstance having improper relocations, even if those functions themselves do not have PIE metadata. So the problem is almost contagious in a way and very misleading in origin.

E.g.:
```
ld.lld: error: relocation R_X86_64_TPOFF32 against ThreadLocalSigInfoGenerationCounter cannot be used with -shared
>>> defined in lto.tmp
>>> referenced by ld-temp.o
>>>               lto.tmp:(llvm::PrettyStackTraceEntry::PrettyStackTraceEntry())
``` 

These wrong relocation types are only guaranteed to happen when several specific conditions are met:
1. You are using LTO (either thin or full)/LLVM bitcode is part of the link even with "--lto-O0".
2. You are trying to output a shared library from the linker or using --lto-emit-asm and then compiling that to a native object file.  
3. At least some of the bitcode libraries were compiled with/have metadata for PIC and PIE. i.e. the bitcode has modules marked ..."PIE Level", i32 1 or 2;
4. In some code, it will not cause improper relocations, and the link will succeed unless the linker "-z defs" flag is used; othertimes, -z defs causes it to report even more improper relocations than it would without it. 
5. For the R_X86_64_TPOFF32 error, you must obviously be using thread local storage in some fashion.

Other tools, such as llc and opt, will generate a native object file created with the proper relocations when passed the same bitcode.

Extracting the library archives, disassembling the bitcode, replacing the PIE Level with 0, assembling, re-archiving -- the link now succeeded and produced a properly working libLLVM.so 

So, it seems that the link mode is not checked, and upon seeing a non-0 PIE Level metadata, regardless of the PIC metadata, it attempts to relax tls (and maybe sometimes other?) relocations in a way that is unsuitable for shared objects. 

When using lld's --save-temps, disassembly of the resulting  bitcode files shows that they are not specified to use any particular tls-model, just simply "thread_local", and it also shows that the PIC-level metadata is properly set. 

Specifying any of the following during the LLVM build and/or at link time did not fix the issue: -ftls-model=global-dynamic, -mno-relax, manually annotating the respective source code with 
__attribute__((__tls_model__("global-dynamic"))), -femulated-tls, -fno-pie. Only manually changing the PIE Level metadata was successful. 

I'd imagine some sort of check for the output type (shared lib, executable, etc.,) before generating/relaxing relocations would prevent this. 

Reproducers: 

https://drive.google.com/file/d/16JCVXczbbsfgouI-evCzeOqG1y5tNgsw/view?usp=sharing 

It contains the response files/command lines to reproduce both relocation errors at once, each error individually, and a successfully linkable version where the included bitcode library (libedit.a in this example) was manually changed to PIE Level 0.

**Comment by MaskRay** [comment]
> The short of it is that bitcode with PIE metadata >0 cannot be linked into shared libraries without untenable and unreasonable effort.

Right. -fpie/-fPIE compiled object files cannot be linked in -shared mode.
It works in many situations unless one thinks of TLS and (missing symbol interposition).
One needs to be aware that this is unsupported and not guaranteed to work.

The "PIE Level" [metadata](https://llvm.org/docs/LangRef.html#module-flags-metadata) uses the "Max" behavior.
When two modules are combined, the larger value takes effect: a -fpie object and a -fpic object mixes into a -fpie object.
```llvm
!2 = !{i32 7, !"PIE Level", i32 1}
```

> I primarily ran into this issue when attempting to build the libLLVM dylib; if any of the dependent third-party libraries are linked in as bitcode, and they contain PIE metadata, it may result in many complaints about the symbols declared with LLVM_THREAD_LOCAL, such as PrettyStackTraceEntry and TimeTraceProfilerInstance having improper relocations, even if those functions themselves do not have PIE metadata. So the problem is almost contagious in a way and very misleading in origin.

From the description this looks like a build issue.
Please give reproducible instructions (people can run).

> Specifying any of the following during the LLVM build and/or at link time did not fix the issue: -ftls-model=global-dynamic, -mno-relax, manually annotating the respective source code with attribute((tls_model("global-dynamic"))), -femulated-tls, -fno-pie. Only manually changing the PIE Level metadata was successful.

Right. Clang just ignores `-ftls-model=`. (GCC `-fpie -ftls-model=global-dynamic` appears to ignore -ftls-model)
-mno-relax is for linker relaxation (e.g. RISC-V). It's ignored on x86.

**Comment by haampie** [comment]
For people stumbling upon this issue, in my case I hit this when using `-fprofile-instr-use=...` trying to build libLLVM, and learned the hard way that LLVM has no fatal error when `-fPIC` support fails, which can fail when the above flag is passed through CFLAGS/CXXFLAGS, as it triggers a warning that no profile data is available for the config test, and LLVM apparently adds -Werror, so the irrelevant warning results in a compilation error, and LLVM does not add `-fPIC`.

**Comment by MaskRay** [comment]
> So I see no reason why the backend should not at least attempt to output a proper shared library, with the "-shared" flag making it ignore the PIE metadata. I suppose the dso_local may cause issues in some cases, but not always.
> 
> Edit: It also seems very wrong to me that "-fPIE" is allowed to override thread_local(model) attributes in bitcode/tls-model attributes in source code, especially without so much as a warning.

I disagree. Currently no optimization actually leverages PIE (other than IR which is generated upfront, e.g. TLS model, dso_local), but that doesn't give license to a user that a -fPIE object file and a -fPIC one merges to a -fPIC one. Note: I agree that the -fPIE tri-state is kinda weird and I'd call it a design mistake. But that has been made ~20 years ago and not going to be fixed.

When a -fno-pic object and object -fpie merge, conceptually the result can only be seen as a -fno-pic one. There are cases it can be linked in -pie mode, but that is not guaranteed.
When a -fpie object and object -fpic merge, the output is a -fpie object. 

The regular LTO IRMover behavior should conceptually match a relocatable linking (aka partial linking). In the ELF relocatable object file, there is really no recording of the -fno-pic/-fpie/-fpic state. LLVM bitcode files don't do worse than ELF relocatable object files here.
