### ISSUE TITLE
clang-format crashes when formatting thousands of levels of nested blocks

### ISSUE THREAD

**Issue by owenca** [llvm/llvm-project#55912]
```console
> clang-format.exe -version
clang-format version 15.0.0 (https://github.com/llvm/llvm-project cf88150c48df4e779edb91a8facf838bea3bd1b7)
> clang-format.exe clang\test\Parser\parser_overflow.c > NUL
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: clang-format.exe clang\\test\\Parser\\parser_overflow.c
```

**Comment by owenca** [comment]
https://reviews.llvm.org/D127183

**Comment by panukulv** [comment]
> ```console
> 
> > clang-format.exe -version
> 
> clang-format version 15.0.0 (https://github.com/llvm/llvm-project cf88150c48df4e779edb91a8facf838bea3bd1b7)
> 
> > clang-format.exe clang\test\Parser\parser_overflow.c > NUL
> 
> PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
> 
> Stack dump:
> 
> 0.      Program arguments: clang-format.exe clang\\test\\Parser\\parser_overflow.c
> 
> ```

**Comment by panukulv** [comment]
Close
