### ISSUE TITLE
Debug info representation of coroutine frame

### ISSUE THREAD

**Issue by pogo59** [llvm/llvm-project#55916]
https://reviews.llvm.org/D99179 by @ChuanqiXu9 added debug info describing a coroutine frame.  This frame is not directly describing anything in the source code, but people debugging coroutines were asking for a way to get the debugger to print the frame in a more human-friendly way.  That's fine.

There are two issues with the generated description; one is minor and one is significant.
The minor issue is that some pointers in the frame are described as address values using DW_ATE_address.  This is an unusual encoding.  It is legal DWARF, but debuggers do not necessarily know what to do with it.  One suggestion in the review is to change the description, so instead of a base type with DW_ATE_address, it uses DW_TAG_pointer_type with no DW_AT_type attribute (a "pointer to nothing" aka "void*").

The significant issue is that some elements in the frame do not have a well understood type, and these elements are *also* described as address values using DW_ATE_address.  It is not clear that this is really a good choice for an "I don't know what it is" element.  In particular, it's not clear (to me, at least) whether these unknown elements are always going to be the size of an address.

Regardless of the description issues, post-commit review comments mention that there is no testing of either of the paths that currently produce DW_ATE_address.  There should be tests for all cases, both to ensure that the code does what is expected, and to guide readers in understanding what these elements are expected to be.

**Comment by ChuanqiXu9** [comment]
Sent https://reviews.llvm.org/D127625 and https://reviews.llvm.org/D127626

**Comment by ChuanqiXu9** [comment]
This should be addressed now.
