### ISSUE TITLE
[OpenMP] Nondeterministic hang on Windows thread start-up

### ISSUE THREAD

**Issue by branh** [llvm/llvm-project#55929]
We've noticed a non-deterministic hang in `__kmp_suspend_initialize_thread` in `z_Windows_NT_util.cpp` on Windows. It occurs most frequently on our test machines when some threads have very little to do, such as in our tests where the entire content of a parallel region is a task executed by a single thread.

[hang64.zip](https://github.com/llvm/llvm-project/files/8856475/hang64.zip)
 
The call stack is

```console
01 000000ed`766ff770 00007ffa`fa029bc2     libomp140_x86_64!__kmp_suspend_initialize_thread(union kmp_info * th = 0x0000026c`1feef380)+0xf2 [D:\a01\_work\8\s\src\vctools\asan\llvm\openmp\runtime\src\z_Windows_NT_util.cpp @ 321] 

02 000000ed`766ff7a0 00007ffa`fa029a30     libomp140_x86_64!__kmp_free_thread(union kmp_info * this_th = 0x0000026c`1feef380)+0x152 [D:\a01\_work\8\s\src\vctools\asan\llvm\openmp\runtime\src\kmp_runtime.cpp @ 5631] 

03 000000ed`766ff7d0 00007ffa`fa026d08     libomp140_x86_64!__kmp_free_team(union kmp_root * root = <Value unavailable error>, union kmp_team * team = 0x0000026c`1fecb9c0, union kmp_info * master = 0x00000000`00000000)+0x2a0 [D:\a01\_work\8\s\src\vctools\asan\llvm\openmp\runtime\src\kmp_runtime.cpp @ 5455] 

04 000000ed`766ff850 00007ffa`fa026eb2     libomp140_x86_64!__kmp_reset_root(int gtid = 0n535586624, union kmp_root * root = 0x0000026c`1fec6740)+0x1c8 [D:\a01\_work\8\s\src\vctools\asan\llvm\openmp\runtime\src\kmp_runtime.cpp @ 3885] 

05 000000ed`766ff8c0 00007ffa`fa02a4d9     libomp140_x86_64!__kmp_unregister_root_current_thread(int gtid = 0n0)+0x112 [D:\a01\_work\8\s\src\vctools\asan\llvm\openmp\runtime\src\kmp_runtime.cpp @ 3977] 

06 000000ed`766ff8f0 00007ffa`fa0270be     libomp140_x86_64!__kmp_internal_end_library(int gtid_req = <Value unavailable error>)+0x99 [D:\a01\_work\8\s\src\vctools\asan\llvm\openmp\runtime\src\kmp_runtime.cpp @ 6149] 
```

Looking at the relevant code, the hang is in this while loop in `_kmp_suspend_initialize_thread` (which is unchanged between the version of `libomp` we are using and the latest in LLVM):

```cpp
void __kmp_suspend_initialize_thread(kmp_info_t *th) {
  int old_value = KMP_ATOMIC_LD_RLX(&th->th.th_suspend_init);
  int new_value = TRUE;                                     // Defined to be 1.
  // Return if already initialized
  if (old_value == new_value)
    return;
  // Wait, then return if being initialized
  if (old_value == -1 ||
      !__kmp_atomic_compare_store(&th->th.th_suspend_init, old_value, -1)) {
    while (KMP_ATOMIC_LD_ACQ(&th->th.th_suspend_init) != new_value) {
      KMP_CPU_PAUSE();
    } else {
    // Claim to be the initializer and do initializations
    __kmp_win32_cond_init(&th->th.th_suspend_cv);
    __kmp_win32_mutex_init(&th->th.th_suspend_mx);
    KMP_ATOMIC_ST_REL(&th->th.th_suspend_init, new_value);
  }
}
```

To summarize, the first thread attempts to execute this logic sets `th->th.th_suspend_init` to `-1` during initialization, then does some initialization, and finally sets `th->th.th_suspend_init` to `1`. Subsequent threads either return immediately if `th->th.th_suspend_init` is set to `1`, or, if `th->th.th_suspend_init` is set to `-1`, recognize that another thread is in the process of initializing and wait until that thread sets `th->th.th_suspend_init` to `1` before continuing.

The problem is that, during a single iteration in the spin loop in `__kmp_suspend_initialize_thread`, the thread that is doing the initializing could not only finish initializing, but also call `__kmp_supsend_uninitialize_thread`:

```cpp
void __kmp_suspend_uninitialize_thread(kmp_info_t *th) {
  if (KMP_ATOMIC_LD_ACQ(&th->th.th_suspend_init)) {
    /* this means we have initialize the suspension pthread objects for this
       thread in this instance of the process */
    __kmp_win32_cond_destroy(&th->th.th_suspend_cv);
    __kmp_win32_mutex_destroy(&th->th.th_suspend_mx);
    KMP_ATOMIC_ST_REL(&th->th.th_suspend_init, FALSE);   // FALSE is defined to be 0.
  }
}
```

If this happens, `th->th.th_suspend_init` is set to `0` and the thread executing `__kmp_suspend_initialize_thread` makes no further progress.

I think I've identified the cause of the hang, but I'm not sure on the correct fix. The very next call from the caller `__kmp_free_thread` is a call to `__kmp_lock_suspend_mx(this_th)`, which relies on `th->th.th_suspend_mx` being in a valid state. The call to `__kmp_suspend_uninitialize_thread` that causes the deadlock will also have destroyed this mutex.

**Comment by natgla** [comment]
@jpeyton52: Can you please look at this? Let us know what other info would be useful for you.

Thank you,
Natalia Glagoleva

**Comment by jpeyton52** [comment]
@branh, can you attach the source file for the test or copy and paste it in here?

**Comment by natgla** [comment]
[parallelIf8.zip](https://github.com/llvm/llvm-project/files/9106127/parallelIf8.zip)

Don't know with which exact flags this one was compiled, but we've seen hangs a lot in the lab, e.g. with this:

-O1 -fp:fast -openmp:llvm

or with 
-O1b1 -openmp:llvm

But we never could reproduce same failure locally. Lab machines have more cores and also have other tests running at same time

**Comment by jpeyton52** [comment]
Hello @natgla, @branh

I've been looking at this for a couple of days and have a few questions (sorry for the number of follow up questions here):

1) This is happening with the dynamic library and not the static library correct?
2) For the stack trace in the original post, is the call to `__kmp_internal_end_library()` come from `DllMain()`?
3) Is the stack trace of the thread that is hung?
4) Is it possible for one of you all to modify the library by adding the attached patchfile (just printfs) and having it run in your test infrastructure for one of these tests. It applies on top of 32eed8828e0c6b2efdd5b31fa3f18aef1c6c7d7b

The library is built to avoid calling the destruction routines of the openmp runtime library on Windows because it is hard to get right and usually too dangerous. We pin the dynamic library for the entirety of the application (line 696 of z_Windows_NT_util.cpp) to prevent any number of `FreeLibrary()` calls from detaching the library until the very end of the application.

I'm trying to understand how its happening within your test infrastructure, because when running a typical program (like the tests you've provided), there is no attempt at library destruction.

Patchfile: [add-prints-to-end.txt](https://github.com/llvm/llvm-project/files/9133981/add-prints-to-end.txt)

Any general description of the test system setup that I could replicate would be helpful too!

**Comment by branh** [comment]
1. Yes, this is a dynamically linked library.
2. Yes, the call to __kmp_internal_end_library comes from DllMain(). The full stack trace is:

00 00000027`68f4f930 00007ffa`7a9d72d8     libomp140_aarch64!__kmp_suspend_initialize_thread(union kmp_info * th = 0x000001db`a1a31b40)+0x118 [D:\a01\_work\7\s\src\vctools\crt\asan\llvm\openmp\runtime\src\z_Windows_NT_util.cpp @ 321]

01 00000027`68f4f960 00007ffa`7a9d70e4     libomp140_aarch64!__kmp_free_thread(union kmp_info * this_th = 0x000001db`a1a31b40)+0x130 [D:\a01\_work\7\s\src\vctools\crt\asan\llvm\openmp\runtime\src\kmp_runtime.cpp @ 5631]

02 00000027`68f4f980 00007ffa`7a9d44a0     libomp140_aarch64!__kmp_free_team(union kmp_root * root = <Value unavailable error>, union kmp_team * team = 0x000001db`a1a24f80, union kmp_info * master = 0x00000000`00000000)+0x1bc [D:\a01\_work\7\s\src\vctools\crt\asan\llvm\openmp\runtime\src\kmp_runtime.cpp @ 5455]

03 00000027`68f4f9f0 00007ffa`7a9d4620     libomp140_aarch64!__kmp_reset_root(int gtid = <Value unavailable error>, union kmp_root * root = 0x000001db`a1a244c0)+0xa8 [D:\a01\_work\7\s\src\vctools\crt\asan\llvm\openmp\runtime\src\kmp_runtime.cpp @ 3885]

04 00000027`68f4fa30 00007ffa`7a9d7c04     libomp140_aarch64!__kmp_unregister_root_current_thread(int gtid = 0n0)+0xf8 [D:\a01\_work\7\s\src\vctools\crt\asan\llvm\openmp\runtime\src\kmp_runtime.cpp @ 3977]

05 00000027`68f4fa70 00007ffa`7a9d4704     libomp140_aarch64!__kmp_internal_end_library(int gtid_req = <Value unavailable error>)+0x9c [D:\a01\_work\7\s\src\vctools\crt\asan\llvm\openmp\runtime\src\kmp_runtime.cpp @ 6149]

06 00000027`68f4fa90 00007ffa`7aa14f60     libomp140_aarch64!DllMain(struct HINSTANCE__ * hInstDLL = <Value unavailable error>, unsigned long fdwReason = <Value unavailable error>, void * lpReserved = <Value unavailable error>)+0xb4 [D:\a01\_work\7\s\src\vctools\crt\asan\llvm\openmp\runtime\src\kmp_runtime.cpp @ 633]

07 00000027`68f4fae0 00007ffa`7aa1507c     libomp140_aarch64!dllmain_dispatch(struct HINSTANCE__ * instance = 0x00007ffa`7a9c0000, unsigned long reason = 0, void * reserved = 0x00000000`00000001)+0xc8 [D:\a01\_work\7\s\src\vctools\crt\vcstartup\src\startup\dll_dllmain.cpp @ 281]

08 00000027`68f4fb40 00007ffa`8cbb95f4     libomp140_aarch64!_DllMainCRTStartup(struct HINSTANCE__ * instance = 0x00007ffa`7a9c0000, unsigned long reason = 0, void * reserved = 0x00000000`00000001)+0x3c [D:\a01\_work\7\s\src\vctools\crt\vcstartup\src\startup\dll_dllmain.cpp @ 334]

09 00000027`68f4fb70 00007ffa`8cbf9f4c     ntdll!LdrpCallInitRoutine(<function> * InitRoutine = 0x00007ffa`7aa15040, void * DllHandle = 0x00007ffa`7a9c0000, unsigned long Reason = 0, struct _CONTEXT * Context = 0x00000000`00000001)+0x84 [minkernel\ntdll\ldr.c @ 231]

0a 00000027`68f4fbc0 00007ffa`8cbf9d10     ntdll!LdrShutdownProcess(void)+0x13c [minkernel\ntdll\ldrinit.c @ 7250]

0b 00000027`68f4fcb0 00007ff7`df2bc0ec     ntdll!RtlExitUserProcess(long ExitStatus = 0n0)+0x150 [minkernel\ntdll\rtlstrt.c @ 1570]

0c 00000027`68f4fd10 00007ff7`df2bc010     task_firstprivate_default_ctest!exit_or_terminate_process+0x5c

0d 00000027`68f4fd30 00007ff7`df2659b8     task_firstprivate_default_ctest!common_exit+0xe0

0e 00000027`68f4fd90 00007ff7`df265e44     task_firstprivate_default_ctest!__scrt_common_main_seh(void)+0x1a0 [D:\a01\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 310]

0f (Inline Function) --------`--------     task_firstprivate_default_ctest!__scrt_common_main(void)+0x8 [D:\a01\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 330]

10 00000027`68f4fdd0 00007ff7`df264bf4     task_firstprivate_default_ctest!mainCRTStartup(void * __formal = <Value unavailable error>)+0x14 [D:\a01\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp @ 16]

11 00000027`68f4fde0 00007ffa`8ba584a8     task_firstprivate_default_ctest!nogpfntStartup(void)+0x1c [D:\a\1\s\nogpf\nogpfnt.c @ 9]

12 00000027`68f4fdf0 00007ffa`8cc02978     kernel32!BaseThreadInitThunk(unsigned long RunProcessInit = <Value unavailable error>, <function> * StartAddress = 0x00007ff7`df25451c, void * Argument = 0x00000027`69086000)+0x38 [clientcore\base\win32\client\thread.c @ 77]

13 00000027`68f4fe30 00000000`00000000     ntdll!RtlUserThreadStart(<function> * StartAddress = 0x00007ff7`df25451c, void * Argument = 0x00000027`69086000)+0x48 [minkernel\ntdll\rtlstrt.c @ 1152]

3. Yes, the stack trace is of the thread that is hung. At the time when the dump was taken, it was the only thread remaining in the process.

4. I'll work on getting a run with the attached patch file and reply back.

LdrShutdownProcess is on the stack, so my interpretation is that the library is still only being detached at the end of the application.

**Comment by jpeyton52** [comment]
No problem and thanks for the update @branh! I'm glad the issue is resolved.
