### ISSUE TITLE
error: non-friend class member cannot have a qualified name

### ISSUE THREAD

**Issue by s2s-k** [llvm/llvm-project#55923]
MSVC: https://godbolt.org/z/h6xKEjsPY
GCC: https://godbolt.org/z/b5feojr7j
Clang: https://godbolt.org/z/4nKPx9TnM

`error: non-friend class member 'C' cannot have a qualified name`

The error only appears in the Clang compiler. And the text of the error itself is very weird. It's not very clear what it says. "non-friend class member"?

**Comment by shafik** [comment]
I believe clang is correct here, if we look at [\[class.pre\]p3](https://eel.is/c++draft/class#pre-3) it says:

>If a class-head-name contains a nested-name-specifier, the class-specifier shall not inhabit a class scope. ...

**Comment by zygoloid** [comment]
I agree, Clang is correct to reject this code. Perhaps we can find a better phrasing for the error? (It's technically correct and does describe the problem, but apparently is not sufficiently comprehensible.)

**Comment by s2s-k** [comment]
@shafik @zygoloid by your logic, Clang should reject [this code](https://godbolt.org/z/rfMMz5Pxv), but it doesn't happen.

**Comment by shafik** [comment]
So your example is a `simple-type-specifier` where the clause I quoted is referring to a `class-head-name`, maybe this helps see it better:

```cpp
struct A {
    struct B;

    struct // class-key 
        B // class-head-name
    {
        int Value = 0;
    };
};

int main() {
    A::B // simple-type-specifier
      b;
}
```

**Comment by s2s-k** [comment]
Yes, I understand what you mean. I didn't carefully read the reference to the standard you provided, so there was a misunderstanding.

Then, it really looks like a bug in MSVC and GCC.
