### ISSUE TITLE
Implement `progmem` attribute available in `avr-gcc`

### ISSUE THREAD

**Issue by KOLANICH** [llvm/llvm-project#55921]
```c++
#define __ATTR_PROGMEM__ __attribute__((__progmem__))
```

I have tried to substitute it with

```c++
#define __ATTR_PROGMEM__ [[gnu::section(".progmem1.data")]]
```

with zero success.

**Comment by benshi001** [comment]
you can use the `__flash`/`__flash1`/`__flash2`/`__flash3`/`__flash4`/`__flash5`, such as 

```
const int __flash1 dat[100]; // put into .section .progmem1.data
```

Please refer to 
https://gcc.gnu.org/wiki/avr-gcc#Pragmas

https://github.com/llvm/llvm-project/blob/main/clang/test/CodeGen/avr/address-space-avr.c

**Comment by KOLANICH** [comment]
Thanks for the info, I'll try it!

**Comment by benshi001** [comment]
You should make your code to "#define __ATTR_PROGMEM__  __attribute__((section(".progmem1.data")))"
