### ISSUE TITLE
Backports a bugfix of the Clang Static Analyzer to clang-14

### ISSUE THREAD

**Issue by steakhal** [llvm/llvm-project#55937]
The commit fixes a bug in the `apiModeling.llvm.CastValue` checker, where the new MLIR constructs formed a null-pointer which it immediately dereferenced causing a crash.
It would be grate to backport this fix since `clang-tidy` users of LLVM developers would likely encounter this crash.
Due to the `clang-tidy` integration to `clangd` even wider scale of developers might be affected.
Consequently, I think this patch deserves to be backported.

Should I create a followup patch mentioning this in some release notes?

/cherry-pick c7fa4e8

**Comment by steakhal** [comment]
@tstellar
It had the following error `github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"resource": "PullRequest", "field": "head", "code": "invalid"}], "documentation_url": "https://docs.github.com/rest/reference/pulls#create-a-pull-request"}`, and I'm not sure how to proceed.

**Comment by tstellar** [comment]
@steakhal This is a known issue that I'm working on fixing.

/branch llvm/llvm-project-release-prs/issue55937

**Comment by tstellar** [comment]
Merged: 4d5dad43b2eb
