### ISSUE TITLE
Concept short circuit doesn't work if requires clause is after function parameters when checking concepts

### ISSUE THREAD

**Issue by andoalon** [llvm/llvm-project#55945]
The compiler behaves differently depending on whether the same requires clause for a function template is written between the template parameters and the function signature or after the function signature. In the former case it performs short-circuit evaluation (and agrees with gcc) whereas in the latter case it doesn't, leading to infinite recursion in my case.

However, short-circuit **doesn't misbehave in all cases**, since I didn't manage to hit the issue in a simpler case I tested (see below my case), so it doesn't seem to be related only to short-circuit evaluation, but concept evaluation as well.

The issue involves a struct `Thing` with a constructor template with a single argument, constrained by `std::copy_constructible<T>`, that could possibly be a better match than the copy constructor (when `T = Thing`). I expected that changing the contraint to `!std::is_same_v<T, Thing> && std::copy_constructible<T>` would solve the issue, but that worked or not depending on the location in which I wrote the `requires` clause.

Possibly related to #44304

My case (reproduction): [Compiler Explorer](https://gcc.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIABykrgAyeAyYAHI%2BAEaYxCAArBqkAA6oCoRODB7evgGp6ZkCoeFRLLHxSbaY9o4CQgRMxAQ5Pn6BdpgOWQ1NBCWRMXGJyQqNza15HeP9YYPlw0kAlLaoXsTI7BzmAMxhyN5YANQmO25oDJspBAqn2CYaAIK7%2B4eYJ2cEAJ4pmAD6BGITEItx29yeD0eY2IXgcRwAKggwsBISYAOxWJ5HbEIpFGCBLD4AESOWCoTC8tAIp0xjxxuOREAuYwZRnMADZCacSWSKVSaaisTiAPTCo4RADy8OwICOTGQaGI%2BCMRyIRwAskIAGpuOW0WhHVBUVUITAsOXEd40cKkSH00VHaJeAgmpgEMAcBRHFLEVDRJjRWhfI4MAQAWjGhnQTXQgrpIrFAHUSABrL0QTCqX4OTDoJZ2hMEM0pAxFj5ub6/ZhsBF3OP2sVE1CYL2S%2BFHADuqaOGazXSLeYL2NFRZYJbd71ObjG6BAKFQKS%2Bf2ZgNhjkD73hdaFw%2BFloAjl48Jb02AwDO5wpWP8mKC3PDSKyUWD8xCd0cHU2W%2BKpZ3u73swHV9413UdxzLKdK0Ya9azBI4DyPE8ewvedF2XARoTXPANynLcXyHE4ITMPYqDJI4ACVsAARTkABJSihD%2BR4ADFpXIv5pXVZRgkeaUCIdZNiDTHtM0A3NgPpMDS0nT4fmgms8PBED4MwQ9j2/CAzxQvAFD%2BK82D%2BAA3XDH0RZE7hOMx2Q5I4ULQNCVxhbocLORSJJxMz8RXWsrI/AAqAg/OFYDdhqJR%2BMbZtW1/LshJ7OQImwAANZRsHvbAiXc3cjg8BhtC8S46gYWyEBIAgw2QY9kCPF10CikNUGpd8HSUM1VVQI4ECYFIqyORVLQcIMQAizqCAIFIFBAUVGAAOmQHrLSoOJGE2ObUBYYUO2FeaUmFAwjC8JhgEwbaMMBYFBFuYjcvywqslud8pIncsoOrTdt2UzzgCZM6fPZfzAuCgiEPU09zwIWcQB0vTryMkynwsjkbLshcl0crCXPvO4QuI1w8CoAj0SsNEiVREmBTfZ4nkM1A8HQVUWwICAwhdJgQoxAiKTVAg8WAYknwgNmKap5SHTMr0BHeaJLSYNNHw7U1iuQU1kBTZEjnxkaTHZDQvu1jQjhYDAwpOHWUYcs6nPXeh9cfWJRC8cLmrFHn3jQMc6DiVViDwb81WVroUxG/GTXeNIFAyQMvgq1GY4YTCHBIDWvSYI5DLEOmRvs4N0cTshOyRZWjnoJh0C9f2VbVtlnY1m4%2Bsti6bkfV3FpIN3K/V/XzbRy2MZtnW5WAC7bRrhW8CLkuy/ajWGGtQh3gG9YMgEQmEisNeWCYL5Yj%2BArHdzEwElJo%2B5WdDqeeRP4jQBXn%2Ba%2BiAL6MfMdlpdFSaeDgVloTgEl4PwOC0KQVAnA3DWGsLZNYGxJzER4KQAgmhP4rBTCAHYaIZrsikOydkkguAJH8OyNEXB/Bon0JwSQf8EFAM4LwSayR4EAM/qQOAsAYCIHnB7egZAKA/Q4cMA4hhgBSA0MkGgVI4iTQgNESh0QwhNC%2BJwWB7s2CCAlAwIaDDSBYE3kYcQGj8ADUcIZFslDMxdGdFsWBLMaiUNoNhIExAvgeCwAo3ggI8AsBcSsKgBhgAKC1L7DsEoqwuJkIIEQYh2BSFCfIJQahKG6C4PoARKAwGWH0NhSakAVgLiKpNDgEYIbclMJYawZgDZhglDsI4YZExiANDUzM50aE1H7FkFwDB3CeDaHoEIcwygVD0OHIo2Qul5ESUMoqAx%2BnDESZ0bo9QZiTD8LMlp8yGC9GaFMoY8RZmLNGcs2wMwtkLB2SsBQkDNh6EBJgCxjDv4cF/qQf%2BgDgEcFUPgsM2C%2Br7T5lIGaGh/k9lASUtJRxcCECTrsRJOV1opE9sQSyOwuBLFcQgpYSCQBmDQZIHY7IACcaJJBon8HivFuCCWkI4OQ0gHiqjPN4K8mhIA6FoqYawiASA1jjWdOQFw%2BAiA%2B1nIk/gYTRDiCiSKmJKh1AaISaQDsQIUieMpY8%2BlVCOASmdCkZ0hpjTvPZJ8yQ3yBFHD%2BQCg2EAPC8IRVClFcC0UrFNKXYYBJKXUtpckNVjLbDMvtQw9FpBkFmASDNPFkh/C4p2AkPFZTCUaHZJSnYFCNHevoVoFYzC2EXH4MQbRmxeU8LhZwzJUB3ZFriLRWc/CjBCOSDk%2B6nACmxh2ESYpVhLBlMYYW%2BFlaQCCLMIk%2BtGFG0ziKakiwnaM1lp7bOQyO0jJcDxX8HYZg/iqGwUA64DaODCgvG20pBthS/FzTpDIRiwxdunZw3t1bBGSGEZu3JI7Cktv3R28pRJKI0XotgRiLE2IcWwFxHi0pL2wpnX2rgA7H3bqbWOkFE6P1frogxJirFsDsU4txXi2AwPWt7XOnqC6l0rrXRuod8dOC7ohikhDZSPzHpYKevA56PxEhAMhn9f70OYaA9h0DU7wPXqrT8gEMIGAphg8O/Jo7X3jsnUwq9FbZy%2BOYBNUqBApOUZky%2B1t8n02KaE8pkAhGUjEb%2BNJMYZHpAUbydRqt%2BmPwSjMAxuITGI4scwBewT%2BGRMCLEwVSTtnn3Nr03RpD1EUO/rQwBrDIHcMBtzBCwVegfk3vHek6IJaA33NVZQ15uUc15veP4zAHYvYQHBQKxFyLTUaGFFwQBabEGBpQeyGaOL8VojMGYSQMaEj3rRAm%2B51KvXUJ9Sy/1X9OBmGTS88bzWA1GOIMvPwkggA%3D%3D)

```cpp
#include <concepts>
#include <type_traits>

struct Thing
{
    Thing() = default;
    Thing(const Thing&) = default;

#ifdef REQUIRES_AFTER_TEMPLATE
    // Works (expected)
    template <typename T>
    requires (!std::is_same_v<T, Thing> && std::copy_constructible<T>)
    Thing(const T& /*t*/)
#else
    // Does NOT work (UNEXPECTED)
    // Conjunction short-circuit does not
    // seem to happen correctly:
    // https://en.cppreference.com/w/cpp/language/constraints#Conjunctions
    template <typename T>
    Thing(const T& /*t*/)
    requires (!std::is_same_v<T, Thing> && std::copy_constructible<T>)
#endif
    {}
};


void test(int a)
{
    auto thing = Thing(a);

    // This one breaks, when checking if
    // `Thing` models `std::copy_constructible`, because
    // the compiler tries to check
    // if the possibly-copy-constructor is a valid
    // copy constructor, which leads to checking
    // its constraints, therefore checking `std::copy_constructible` again,
    // which leads to infinite recursion
    [[maybe_unused]] auto thing_of_thing = Thing(thing);
}
```

Simple case, no issues: [Compiler Explorer](https://gcc.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIMwBspK4AMngMmAByPgBGmMT%2BZqQADqgKhE4MHt6%2B/kGp6Y4CYRHRLHEJZkl2mA6ZQgRMxATZPn6Btpj2RQwNTQQlUbHxibaNza25HQrjA%2BFD5SNVAJS2qF7EyOwc5gDM4cjeWADUJrtuaAxbyQQKZ9gmGgCCewdHmKfnBACeyZgA%2BgRiExCHddg9no8ngRMCxkgYYZ83D8/sw2McACr3KEzYheBzHbBwn5QkwAdisZIAImcrJDnjC4QiPmdkb9GKwPljwVDLjNMKpksRjjFUJ4RcRMEwANYKf54KjyhgzQyOJgw9CfKmE4nfVnc7AgEAANzEXkwtNJz1x%2BIImIQ4WApIpUOObvtjogyy1xywVCYXloBEtz3dp0hZn2VD9xwAStgAIpyACS8aE/yeADEMdhY/8cwBZZQhJ4513ugD0FeOAHUSLLjhABX8HJh0Mty27GfD1Syvuy0VzsaH3ZKAI5ePCShSNsBgGboI14OUKTn/Y360geoz3U6BcwBCVS2XyxXhFWCPC99D6%2B4dkdujEOowQPl2rGBY4VgBUBG/FfvF5Iy6JROy/as62IBsm0FWoNUAsNu2ZJEUQ5dEDTAp9PTfTEDy/X9/wQ0dMAnKdMBnCA5wXJcVzXDdzgxLcsJ3cE9wCPCYklGU5QVJULzVDVb3BQC9lcBUwPJSkaUhakQxeeknmNVA8E1GEZggcI7SYESXQfcDjgsLjoObOC2yIt0qwDIhjgIZ9gH%2BAB3QgECVO0zm1ZjgAgbS5MwuybLsyTyRpXY6Xkp4wxMABWKwYpYJhvjif4vAYLwlBvKKaUy44rNQALHUc5zAX89zty82zHQ7ULnWkp4OFWWhOCi3g/A4LRSFQTg3GsaxjgUdZNhZSMeFIAhNHq1ZpRAXYyQAOgCKQAgCSQuCigAOAIyS4NayX0ThJBa8aOs4XgFBADRRvG1Y4FgGBEBQVA4ToeJyEoNAnvoBJDkMYApA0C6aCDeIzogGIjpicImm%2BTgRvethBAAeQYWhoba3gsHioxxDR0h8ElOpjXIo6BVqLwYRh3hNK6I7aDwTioY8LAKdG4g8BYCnVioAxgAUAA1PBMAchHUWZ/hBBEMR2CkGRBEUFR1Bx3QuH0H6UB6yx9Dps7IFWVAbkyM6OAAWgXdzTEsawzA0Y4jYR3YbZrMRaAdgUgSYU6ujgzIXAYdxPDaPRQnmMoKj0AoMgESY/GV8OekGEORmVmo6gEPoJn93Ik89lPelmePhgSJPZijvQVWafPFkL1Z%2Bo2LY9CBTBth4BqmsOnHOo4VQNqN5bjm%2BoxjikWaNGHxtuotjXCXwIhhT2ZXjg8D74j3XYuGWXgxrR5ZJv8ObJF2AIAE4yUkMk1sPw/VuPvaOAO0h2aii7WvajvTvOy6t9IG77vWAhkjJ16TZp4kBUnoMWwhRDiGluAuWagjpK1IA5YEyQOY32aqQZ%2BvAO4IzJv/O0qAqDHC7gEHukg%2B4GAHkPEe1sICL2SM9Wew114fy0NvUgCApRYASF6G%2Bd8H5PyOq/Ww79N6sJ3mYKKs1D6SDWgfXYUVD5WxPhoIIjUOC7Dbi/E6LD6pfzuhAJAlx%2BDEExlsQB716GfW1lACxDDkyLn7r9SQ/0Or6wEIbE2BAby7CpObKwlgra6NfI9Sx8R7EgF%2BmYZWesegeNNj4vxltWFf1sZ9cJxpkDJGSOuLgh9/i7DMP8VQy1XGxM4BWaiiSAnWwrH8Exy50iEyNkE1JYSHEUKcS4mJBtOCeO8b49WFgrY2ypPGJMqZsDpizDmPMhZiylmwC0kJdjFyROiW45UvT4kDInkM62RtRmJhTGmDM2Zcz5mwEWEsOYllL2IOkzJ2TjS5PyYU4p0hunuPKZUwZwzanxBYA0vATSvxUhAGM45kzTkzIuVchZtzQn3PaT9QEeIGDSlKT0422yql7IRSsiJChmDJAUAgVABBMVfOxV4s2vzknBLuQ8rJOS8nMhmEUkpnzNkcAqV4tWuy/kIzMF%2BOpgKFCNMwM066rSkUoA6ailKGKuVxJpQkulIyIUTKmWc2Zlz5k3LYW2QgIDFzKw6eE3FmsYjWLYWo9BmDjocA8AwYxpiPj80FsvCAuBjWMNXt6LgGgKyBo3ldHeB9Zr7yPmSKokhFFRWcWSVR%2B1NFYO0WdC6oiJo3zMKmx1oat6rEJsQdIzhJBAA%3D%3D%3D)

```cpp
#include <concepts>
#include <type_traits>

template <typename T>
struct Empty
{};

template <typename T>
constexpr bool breaks_if_instantiated = Empty<T>::value;

struct Thing
{
    Thing() = default;
    
#ifdef REQUIRES_AFTER_TEMPLATE
    // Works (expected)
    template <typename T>
    requires (!std::is_same_v<T, Thing> && breaks_if_instantiated<T>)
    Thing(const T& /*t*/)
#else
    // Works (expected)
    template <typename T>
    Thing(const T& /*t*/)
    requires (!std::is_same_v<T, Thing> && breaks_if_instantiated<T>)
#endif
    {}
};


void test(int a)
{
    // Breaks (expected)
    //auto thing_with_int = Thing(a);

    Thing thing{};

    [[maybe_unused]] auto thing_with_thing = Thing(thing);
}
```

**Comment by usx95** [comment]
Fixed at trunk.
