### ISSUE TITLE
`clang` cannot link for `avr` target with `-flto` enabled since `--ld-path` is ignored and `avr-ld` cannot link LLVM bitcode

### ISSUE THREAD

**Issue by KOLANICH** [llvm/llvm-project#55940]
Maybe as a temporary workaround we can link and optimize LLVM bitcode into a single file, on which then call the original `avr-ld` with the libs that are not in bitcode as arguments. Though for now it doesn't work for me.

**Comment by benshi001** [comment]
`avr-ld` can not link llvm bitcode, this is `avr-ld`'s problem, and there is nothing we can do from the clang side.

**Comment by benshi001** [comment]
You should use `llvm-link` to link LLVM bitcode, other than `avr-ld`.

**Comment by benshi001** [comment]
It seems there may be something wrong within the clang driver for AVR, I run
```
./bin/clang a.c --target=avr -mmcu=at90s8515 -flto
```
but get an error
```
clang-15: error: 'avr': unable to pass LLVM bit-code files to linker
```

**Comment by benshi001** [comment]
you can try by this way


1. clang xxx.c --target=avr -flto
2. llvm-link
3. llc
4. avr-ld

**Comment by benshi001** [comment]
fixed by https://reviews.llvm.org/D145646

**Comment by KOLANICH** [comment]
Thank you. Though I'm a bit busy now, so I'm not sure when I'm able to test this.

**Comment by benshi001** [comment]
fixed in https://github.com/llvm/llvm-project/commit/0d37efdbc599e61ce2a0418723a66d6b45aea8d7
