### ISSUE TITLE
Segementation fault when using Legacy Pass Manager FunctionPass

### ISSUE THREAD

**Issue by ndaoud08** [llvm/llvm-project#55941]
Hello,

I have a pass that prints the function name and inserts a call to a function `test` in the beginning of each basic block. Now this pass runs with some programs and crashes with other ones, for example it runs fine with factorial code, however when run on [stream](https://www.cs.virginia.edu/stream/) benchmark (serial) ([stream.c](https://www.cs.virginia.edu/stream/FTP/Code/stream.c)), it crashes with seg. fault. Same with parallel programs, runs on simple hello world mpi program, but when run with jacobi for example it crashes.

Here's the output message when run on stream (serial):

Cmd:
```shell
clang -flegacy-pass-manager -Xclang -load -Xclang ../skeleton/build/libSkeletonPass.so -c stream.c
```
Output:
```console
I saw a function called main!
I saw a function called checktick!
I saw a function called mysecond!
I saw a function called checkSTREAMresults!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang -flegacy-pass-manager -Xclang -load -Xclang ../skeleton/build/libSkeletonPass.so -c stream.c
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'stream.c'.
4.      Running pass 'X86 DAG->DAG Instruction Selection' on function '@main'
Segmentation fault (core dumped)
```

The Pass (Skeleton.cpp):
```cpp
struct SkeletonPass : public FunctionPass {
    static char ID;
    SkeletonPass() : FunctionPass(ID) {}

    virtual bool runOnFunction(Function &F) {

      errs() << "I saw a function called " << F.getName() << "!\n";
      LLVMContext &context = F.getContext();
      auto module                  = F.getParent();
      Type        *Void;
      Void  = Type::getVoidTy(context);

      auto bbFunc = module->getOrInsertFunction("test", Void);

      for (Function::iterator BB = F.begin(), BE = F.end(); BB != BE; ++BB) {
        IRBuilder<> builder(&*BB->begin());
        builder.CreateCall(bbFunc);
      }
      return true;
    }
  };
  ```
And lib.c:
```c
#include "stdio.h"

void test () {
    printf("Inside the instrumented function\n");
}
```

LLVM & Clang versions:

```console
$ llvm-config --version 
14.0.0
``` 
```console
$ clang --version
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by fhahn** [comment]
Please check if the IR your pass is generating is correct.

`getOrInsertFunction` requires a function type to be passed as second argument, but the pass pass in `void`. See https://llvm.org/doxygen/classllvm_1_1Module.html#abb107e4edbf05eae92936cba6801c2d9

Once you verified that your pass creates valid IR, please re-open the issue with the IR at the end of LLVM optimizations (`-emit-llvm`).

**Comment by ndaoud08** [comment]
Okay thank you. This was an issue indeed.

**Comment by for-just-we** [comment]
> Please check if the IR your pass is generating is correct.
> 
> `getOrInsertFunction` requires a function type to be passed as second argument, but the pass pass in `void`. See https://llvm.org/doxygen/classllvm_1_1Module.html#abb107e4edbf05eae92936cba6801c2d9
> 
> Once you verified that your pass creates valid IR, please re-open the issue with the IR at the end of LLVM optimizations (`-emit-llvm`).

Hi, I have also come across the same problem. What's weird is that I register the pass for both `opt` and `clang`, and I can correctly run the pass with `opt`, but for clang, I saw the same error trace. How should I fix this?
