### ISSUE TITLE
[Flang] Lowering for abort (extension)

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#55955]
Flang does not currently support lowering for the abort intrinsic procedure. This is a commonly supported extension in Fortran.

Reproducer:
```fortran
subroutine ab
  call abort
end subroutine
```

Currently the following TODO message is printed by Flang.
`IntrinsicCall.cpp:1415: not yet implemented missing intrinsic lowering: abort`

We need support for this intrinsic procedure to enable `521.wrf_r`

**Comment by PeixinQiao** [comment]
```
$ cat temp.f90 
program main
  call sub()
contains
  subroutine sub()
    call abort
  end
end
```
```
$ gfortran temp.f90 -g && ./a.out

Program aborted. Backtrace:
#0  0x400703 in sub at /.../temp.f90:5
#1  0x40071b in MAIN__ at /.../temp.f90:2
#2  0x400753 in main at /.../temp.f90:2
Aborted (core dumped)
```
Classic-flang:
```
$ flang temp.f90 -g && ./a.out
Aborted (core dumped)
```
```
$ flang temp.f90 -S -emit-llvm
$ cat temp.ll 
...
define void @MAIN_() #0 !dbg !5 {
...
  call void @main_sub(i64* %2), !dbg !9
  ret void, !dbg !10
}
define internal void @main_sub(i64* %.S0000) #0 !dbg !11 {
 ...
  call void @abort_(), !dbg !13
  ret void, !dbg !14
}
declare void @abort_() #0
```
Took one simple investigation.

BTW, `backtrace` extension should be supported, too. Maybe need one discussion after upstream is done. It's important to track one bug using it.

**Comment by PeixinQiao** [comment]
The semantic check and runtime have been supported. Adding the lowering would address this issue. I will prepare one patch.

**Comment by PeixinQiao** [comment]
https://reviews.llvm.org/D130439
