### ISSUE TITLE
[Clang] Poor diagnostics for use of a template class without providing parameters in some contexts

### ISSUE THREAD

**Issue by brycelelbach** [llvm/llvm-project#55962]
[Godbolt](https://godbolt.org/z/Y4YY6Gj5W)

```cpp
template <typename T>
struct x;

template <typename T>
constexpr int y = x::a; // Clang diagnostic doesn't mention that `x` is a template.

using z = x; // Clang diagnostic mentions that `x` is a template.
```

In the definition of `y`, Clang complains that `x` isn't a "class, namespace, or enumeration", but fails to mention that it is a class template and no template parameters have been provided.

In other simpler contexts, such as the definition of the using alias `y`, Clang does explain that `x` is a class template and template parameters need to be provided.

We should improve the quality of the diagnostic for the `y` case - it should explain that `x` is a class template and template parameters are missing.

**Comment by tbaederr** [comment]
Hey @0x59616e, sorry I didn't mention this earlier but we have a fix for this here: https://reviews.llvm.org/D127638 just needs to be pushed (will do so later today)

**Comment by 0x59616e** [comment]
OK. Remember to close this issue after landing ;)
