### ISSUE TITLE
[RISCV] -fprofile-instr-generate fails to assemble with error "Unsupported relocation type"

### ISSUE THREAD

**Issue by topperc** [llvm/llvm-project#55971]
We end up in `RISCVELFObjectWriter::getRelocType` with `Kind==FK_Data_8` and `IsPCRel==true`. This isn't handled in the switch.

I believe the offending code is this
`.quad   .L__profc_foo-.L__profd_foo`

I think we should be generating a R_RISCV_ADD64 and R_RISCV_SUB64 pair for this. I suspect `requiresFixups` isn't returning true when it needs to.

https://godbolt.org/z/xcvdsG7c9

**Comment by topperc** [comment]
@preames @compnerd

**Comment by topperc** [comment]
@luismarques

**Comment by compnerd** [comment]
@topperc hmm, why would it be a R_RISCV_ADD64, R_RISCV_SUB64?  It is a 8-byte PC-relative data reference, so R_RISCV_PCREL_HI20, R_RISCV_PCREL_LO12_I is what I would have guessed.  Although, I've not looked at what we are trying to generate, so perhaps I am incorrect.

**Comment by topperc** [comment]
> @topperc hmm, why would it be a R_RISCV_ADD64, R_RISCV_SUB64? It is a 8-byte PC-relative data reference, so R_RISCV_PCREL_HI20, R_RISCV_PCREL_LO12_I is what I would have guessed. Although, I've not looked at what we are trying to generate, so perhaps I am incorrect.

I think binutils generated R_RISCV_ADD64, R_RISCV_SUB64 so I assumed that was the correct thing.

**Comment by compnerd** [comment]
@luismarques ah, I didn't think to check the compact code model spec.  `R_RISCV_64_PCREL` would definitely be the better option if available.  I think that the profiler already has a reasonable way to emit the table offset (symbolic difference), it just is a limitation of the RISCV target so I think it makes more sense to handle this in the target specific paths as a result.

**Comment by compnerd** [comment]
https://reviews.llvm.org/D127549

**Comment by MaskRay** [comment]
This seems like a 14.0.0 regression (https://reviews.llvm.org/D103539) related to overly strict condition in `llvm/lib/Target/RISCV/MCTargetDesc/RISCVELFStreamer.cpp:requiresFixups`.

**Comment by MaskRay** [comment]
> The other targets generate `R_X86_64_PC64`, `R_AARCH64_PREL64`, etc. Matching this would require `R_RISCV_64_PCREL` which is defined in the compact code model spec but not in the upstream psABI. Notice that this is weird because the symbols are in different sections. Can't we just rewrite the profiler to emit a more sensible way to compute that table offset?

No. -fprofile-instr-generate is correct in using `.quad   .L__profc_bar-.L__profd_bar`. It expects the assembler to use PC-relative relocation(s). For non-RISCV targets, this is typically done by rewriting the expression to be relative to the current location counter.

```
        .type   .L__profc_bar,@object           # @__profc_bar
        .section        __llvm_prf_cnts,"aGw",@progbits,__profc_bar
        .p2align        3
.L__profc_bar:
        .zero   8
        .size   .L__profc_bar, 8
 
        .type   .L__profd_bar,@object           # @__profd_bar
        .section        __llvm_prf_data,"aGw",@progbits,__profc_bar
        .p2align        3
.L__profd_bar:
        .quad   -2012135647395072713            # 0xe413754a191db537
        .quad   24                              # 0x18
        .quad   .L__profc_bar-.L__profd_bar      ########## interesting
        .quad   0
        .quad   0
        .word   1                               # 0x1
        .zero   4
        .size   .L__profd_bar, 48
```
```
