### ISSUE TITLE
std::is_constructible is not the same as GCC and MSVC

### ISSUE THREAD

**Issue by julianlalu** [llvm/llvm-project#55974]
Hello,

This code compile with MSVC 19 and GCC 12.1 but assert with Clang. But clang is able to compile it without the assertions.

https://godbolt.org/z/16n8bP7e8
```c++
#include <type_traits>
struct A{
    int a;
};
struct C : A {};

static_assert(std::is_constructible_v<A, int>);
static_assert(std::is_trivially_constructible_v<C,A>);

int main(){
    A obj{10};
    return obj.a;
}
```

**Comment by royjacobson** [comment]
Indeed, clang has not implemented parenthesized initialization of aggregates yet.

See https://github.com/llvm/llvm-project/issues/54040
