### ISSUE TITLE
llvm operands to a binary operator are not of the same type bug

### ISSUE THREAD

**Issue by jiachao520** [llvm/llvm-project#55987]
#define  ADD(a, b) BinaryOperator::Create(Instruction::Add, a, b, "", bb) 

when i  my project code have  Value *base = ADD(cpu->dyncom_engine->ptr_gpr0, CONST(3))；cpu->dyncom_engine->ptr_gpr0 is i32 * type， build and run project，appear the error and core dump .
ERROR：

Both operands to a binary operator are not of the same type!
  %524 = add i32* %gpr0, i32 3
Both operands to a binary operator are not of the same type!
  %540 = add i32* %gpr0, i32 3
Both operands to a binary operator are not of the same type!
  %547 = add i32* %gpr0, i32 3

this is why  ？ Thanks for anyone to tell me

**Comment by topperc** [comment]
Instruction::Add is only for integer types. To increment a pointer you need to use getelementptr or use ptrtoint to convert the pointer to an integer first.

**Comment by jiachao520** [comment]
> Instruction::Add is only for integer types. To increment a pointer you need to use getelementptr or use ptrtoint to convert the pointer to an integer first.

but my other project use the same method can work  succes，llvm is support this method but need configure llvm ？

  %343 = add i32* %gpr0, i32 3
  %344 = load i32* %15

**Comment by asl** [comment]
>but my other project use the same method can work succes，llvm is support this method but need configure llvm ？

Please refer to LLVM language reference for more information: https://llvm.org/docs/LangRef.html#add-instruction
Likely your "other project" simply has assertions / verifications turned off. The final result is undefined though

**Comment by jiachao520** [comment]
> > but my other project use the same method can work succes，llvm is support this method but need configure llvm ？
> 
> Please refer to LLVM language reference for more information: https://llvm.org/docs/LangRef.html#add-instruction Likely your "other project" simply has assertions / verifications turned off. The final result is undefined though

Thanks very much! other project  turned off verifications
