### ISSUE TITLE
[InstCombine] optimize test for same-signed values

### ISSUE THREAD

**Issue by rotateright** [llvm/llvm-project#55988]
The naive pattern for checking if 2 values have the same sign should be reduced:
```llvm
define i1 @src(i32 %x, i32 %y) {
  %a = and i32 %x, %y
  %lt = icmp slt i32 %a, 0
  %o = or i32 %x, %y
  %gt = icmp sgt i32 %o, -1
  %r = or i1 %lt, %gt
  ret i1 %r
}

define i1 @tgt(i32 %x, i32 %y) {
  %a = xor i32 %x, %y
  %r = icmp sgt i32 %a, -1
  ret i1 %r
}

```
https://alive2.llvm.org/ce/z/qXxEFP

This isn't matched in codegen either, so we get sub-optimal asm:
https://godbolt.org/z/aWf9c6j74

**Comment by rotateright** [comment]
The fix should probably take into account the inverted test too:
https://godbolt.org/z/5Ydn5TehY
https://alive2.llvm.org/ce/z/93AODr
...although that might be an independent patch. 

Also, it looks like it is possible to code the naive patterns in C in ways that do not even reduce to a single basic-block. That might be a more difficult bug for SimplifyCFG.

**Comment by emgullufsen** [comment]
I was hoping to try my hand at adding some pattern-matching code to be called from InstCombinerImpl::visitOr to address this reduction - if that sounds like the correct path and if someone is not already working on this.

**Comment by rotateright** [comment]
Yes - feel free to assign the issue to yourself and take a shot. 

You'll want to add plenty of regression tests to verify that we match the right patterns and only the right patterns. Values may be commuted from what is shown in my example, so the pattern-matching should allow that.

**Comment by emgullufsen** [comment]
Alrighty roger that - sounds good thank you - I'm not sure I can assign this issue to myself since I am not at collaborator level for this repo, but I will start tonight writing the methods to match against the IR and some tests to ensure correctness

**Comment by emgullufsen** [comment]
I am still working, but my plan thus far is to pattern-match within InstCombinerImpl::foldAndOrOfICmps, where a lot of the decomposition of operands and predicates is done already... just need to write the match() logic and ensure we match for commutativity of the icmps. I will submit for review to Phabricator when ready - just working on the match() checks now. The pattern of the reduction as I understand it is:
`(icmp slt (X & Y), 0) | (icmp sgt (X | Y), -1) -> (icmp sgt (X ^ Y), -1)`

**Comment by rotateright** [comment]
Sounds good, and I think you're on the right track. Using InstCombiner::isSignBitCheck() might reduce the patch and make it more flexible.

We can hash out details on a Phab patch review or ask questions here if needed. My Phab handle is 'spatel' if you want to add me as a reviewer there.

**Comment by emgullufsen** [comment]
Ah very cool thanks for the shout regarding InstCombiner::isSignBitCheck() I will look into that, and also for your Phab handle I'll definitely add you as reviewer when I submit.

**Comment by emgullufsen** [comment]
I submitted a patch:
[https://reviews.llvm.org/D127903](https://reviews.llvm.org/D127903)
I may need to ask you a few questions on Phabricator as I write more regression tests - thanks a ton for your help thus far!

**Comment by rotateright** [comment]
Should be fixed after:
73202130e52e69d58c571c60163d1c8994e8d166
