### ISSUE TITLE
Recent `master` compiler bug while compiling OpenMP offloading code written in C++

### ISSUE THREAD

**Issue by ikitayama** [llvm/llvm-project#55990]
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /p/project/cjinb33/kitayama1/dev/clang/bin/clang-15 -cc1 -triple nvptx64-nvidia-cuda -aux-triple x86_64-unknown-linux-gnu -S -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name modelsmodule.cpp -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=all -ffp-contract=on -fno-rounding-math -fno-verbose-asm -no-integrated-as -mlink-builtin-bitcode /p/software/jurecadc/stages/2022/software/CUDA/11.5/nvvm/libdevice/libdevice.10.bc -target-feature +ptx75 -target-sdk-version=11.5 -mlink-builtin-bitcode /p/project/cjinb33/kitayama1/dev/clang/lib/libomptarget-nvptx-sm_80.bc -target-cpu sm_80 -target-feature +ptx75 -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=line-directives-only -dwarf-version=2 -debugger-tuning=gdb -fno-dwarf-directory-asm -resource-dir /p/project/cjinb33/kitayama1/dev/clang/lib/clang/15.0.0 -dependency-file CMakeFiles/models.dir/modelsmodule.cpp.o.d -MT models/CMakeFiles/models.dir/modelsmodule.cpp.o -sys-header-deps -internal-isystem /p/project/cjinb33/kitayama1/dev/clang/lib/clang/15.0.0/include/openmp_wrappers -include __clang_openmp_device_functions.h -D models_EXPORTS -I /p/software/jurecadc/stages/2022/software/Boost/1.78.0-GCCcore-11.2.0/include -I /p/scratch/cjinb33/kitayama1/projects/nest-simulator/thirdparty -I /p/scratch/cjinb33/kitayama1/projects/nest-simulator/libnestutil -I /p/scratch/cjinb33/kitayama1/build/nest-clang-offload/libnestutil -I /p/scratch/cjinb33/kitayama1/projects/nest-simulator/sli -I /p/scratch/cjinb33/kitayama1/projects/nest-simulator/nestkernel -I/p/software/jurecadc/stages/2022/software/DB/18.1.40-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/libreadline/8.1-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/gettext/0.21-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/libxml2/2.9.10-GCCcore-11.2.0/include/libxml2 -I/p/software/jurecadc/stages/2022/software/libxml2/2.9.10-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/expat/2.4.1-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/Boost/1.78.0-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/ICU/70.1-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/CUDA/11.5/nvvm/include -I/p/software/jurecadc/stages/2022/software/CUDA/11.5/extras/CUPTI/include -I/p/software/jurecadc/stages/2022/software/CUDA/11.5/include -I/p/software/jurecadc/stages/2022/software/libarchive/3.5.1-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/XZ/5.2.5-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/cURL/7.78.0-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/OpenSSL/1.1/include -I/p/software/jurecadc/stages/2022/software/bzip2/1.0.8-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/ncurses/6.2-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/binutils/2.37-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/zlib/1.2.11-GCCcore-11.2.0/include -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0 -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/x86_64-pc-linux-gnu -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/backward -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0 -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/x86_64-pc-linux-gnu -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/backward -internal-isystem /p/project/cjinb33/kitayama1/dev/clang/lib/clang/15.0.0/include -internal-isystem /usr/local/include -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -internal-isystem /p/software/jurecadc/stages/2022/software/CUDA/11.5/include -internal-isystem /p/project/cjinb33/kitayama1/dev/clang/lib/clang/15.0.0/include -internal-isystem /usr/local/include -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O2 -Wno-unknown-cuda-version -Wall -std=c++17 -fdeprecated-macro -fdebug-compilation-dir=/p/scratch/cjinb33/kitayama1/build/nest-clang-offload/models -ferror-limit 19 -fvisibility protected -fopenmp -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -fopenmp-is-device -fopenmp-host-ir-file-path /tmp/modelsmodule-db8a92.bc -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/modelsmodule-4d9df0.s -x c++ /p/scratch/cjinb33/kitayama1/projects/nest-simulator/models/modelsmodule.cpp
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/p/scratch/cjinb33/kitayama1/projects/nest-simulator/models/modelsmodule.cpp'.
4.	Running pass 'NVPTX DAG->DAG Pattern Instruction Selection' on function '@_ZNK4nest9ConnectorINS_17bernoulli_synapseINS_24TargetIdentifierPtrRportEEEE19get_target_node_idsEimRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERSt6vectorImNSt3pmr21polymorphic_allocatorImEEE'
 #0 0x00000000030287a1 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x00000000030260a4 SignalHandler(int) Signals.cpp:0:0
 #2 0x0000149cb6153c20 __restore_rt sigaction.c:0:0
 #3 0x000000000095a916 llvm::NVPTXTargetLowering::LowerCall(llvm::TargetLowering::CallLoweringInfo&, llvm::SmallVectorImpl<llvm::SDValue>&) const (.cold) NVPTXISelLowering.cpp:0:0
 #4 0x0000000003f20b1a llvm::TargetLowering::LowerCallTo(llvm::TargetLowering::CallLoweringInfo&) const (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x3f20b1a)
 #5 0x0000000003f24c3f llvm::SelectionDAGBuilder::lowerInvokable(llvm::TargetLowering::CallLoweringInfo&, llvm::BasicBlock const*) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x3f24c3f)
 #6 0x0000000003f3592b llvm::SelectionDAGBuilder::LowerCallTo(llvm::CallBase const&, llvm::SDValue, bool, bool, llvm::BasicBlock const*) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x3f3592b)
 #7 0x0000000003f5fb90 llvm::SelectionDAGBuilder::visitCall(llvm::CallInst const&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x3f5fb90)
 #8 0x0000000003f601bf llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x3f601bf)
 #9 0x0000000003fca0d6 llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, bool&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x3fca0d6)
#10 0x0000000003fcb578 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x3fcb578)
#11 0x0000000003fcddd0 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (.part.0) SelectionDAGISel.cpp:0:0
#12 0x00000000022e2df7 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x22e2df7)
#13 0x0000000002768170 llvm::FPPassManager::runOnFunction(llvm::Function&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x2768170)
#14 0x00000000027682dc llvm::FPPassManager::runOnModule(llvm::Module&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x27682dc)
#15 0x0000000002768c5f llvm::legacy::PassManagerImpl::run(llvm::Module&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x2768c5f)
#16 0x000000000338c949 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x338c949)
#17 0x00000000040f80e1 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) crtstuff.c:0:0
#18 0x0000000004b50879 clang::ParseAST(clang::Sema&, bool, bool) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x4b50879)
#19 0x0000000003a80069 clang::FrontendAction::Execute() (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x3a80069)
#20 0x0000000003a1068b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x3a1068b)
#21 0x0000000003b35450 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0x3b35450)
#22 0x0000000000a48544 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0xa48544)
#23 0x0000000000a41975 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#24 0x0000000000a44076 clang_main(int, char**) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0xa44076)
#25 0x0000149cb53e5493 __libc_start_main (/usr/lib64/libc.so.6+0x23493)
#26 0x0000000000a4146e _start (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15+0xa4146e)
clang-15: error: unable to execute command: Segmentation fault
clang-15: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 15.0.0 (https://github.com/llvm/llvm-project 05d771021ad9de12f3e657d464d18731a13578ab)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /p/project/cjinb33/kitayama1/dev/clang/bin
clang-15: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-15: note: diagnostic msg: /tmp/modelsmodule-2c16b4.cpp
clang-15: note: diagnostic msg: /tmp/modelsmodule-d9f638.cpp
clang-15: note: diagnostic msg: /tmp/modelsmodule-2c16b4.sh
clang-15: note: diagnostic msg:

********************
```

**Comment by ikitayama** [comment]
How do I upload .cpp and .sh files here?

**Comment by mizvekov** [comment]
At the bottom of the comment text box, you can see the instructions:
`Attach files by dragging & dropping, selecting or pasting them.`

**Comment by ikitayama** [comment]
# Crash reproducer for clang version 15.0.0 (https://github.com/llvm/llvm-project 05d771021ad9de12f3e657d464d18731a13578ab)
# Driver args: "--driver-mode=g++" "-D" "models_EXPORTS" "-I" "/p/software/jurecadc/stages/2022/software/Boost/1.78.0-GCCcore-11.2.0/include" "-I" "/p/scratch/cjinb33/kitayama1/projects/nest-simulator/thirdparty" "-I" "/p/scratch/cjinb33/kitayama1/projects/nest-simulator/libnestutil" "-I" "/p/scratch/cjinb33/kitayama1/build/nest-clang-offload/libnestutil" "-I" "/p/scratch/cjinb33/kitayama1/projects/nest-simulator/sli" "-I" "/p/scratch/cjinb33/kitayama1/projects/nest-simulator/nestkernel" "-g" "-Wno-unknown-cuda-version" "-fopenmp" "-fopenmp-targets=nvptx64" "-std=c++17" "-O2" "-Wall" "-fopenmp=libomp" "-g" "-fPIC" "-fopenmp=libomp" "-MD" "-MT" "models/CMakeFiles/models.dir/modelsmodule.cpp.o" "-MF" "CMakeFiles/models.dir/modelsmodule.cpp.o.d" "-o" "CMakeFiles/models.dir/modelsmodule.cpp.o" "-c" "/p/scratch/cjinb33/kitayama1/projects/nest-simulator/models/modelsmodule.cpp"
# Original command:  "/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15" "-cc1" "-triple" "nvptx64-nvidia-cuda" "-aux-triple" "x86_64-unknown-linux-gnu" "-S" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "modelsmodule.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-fhalf-no-semantic-interposition" "-mframe-pointer=all" "-ffp-contract=on" "-fno-rounding-math" "-fno-verbose-asm" "-no-integrated-as" "-mlink-builtin-bitcode" "/p/software/jurecadc/stages/2022/software/CUDA/11.5/nvvm/libdevice/libdevice.10.bc" "-target-feature" "+ptx75" "-target-sdk-version=11.5" "-mlink-builtin-bitcode" "/p/project/cjinb33/kitayama1/dev/clang/lib/libomptarget-nvptx-sm_80.bc" "-target-cpu" "sm_80" "-target-feature" "+ptx75" "-mllvm" "-treat-scalable-fixed-error-as-warning" "-debug-info-kind=line-directives-only" "-dwarf-version=2" "-debugger-tuning=gdb" "-fno-dwarf-directory-asm" "-resource-dir" "/p/project/cjinb33/kitayama1/dev/clang/lib/clang/15.0.0" "-dependency-file" "CMakeFiles/models.dir/modelsmodule.cpp.o.d" "-MT" "models/CMakeFiles/models.dir/modelsmodule.cpp.o" "-sys-header-deps" "-internal-isystem" "/p/project/cjinb33/kitayama1/dev/clang/lib/clang/15.0.0/include/openmp_wrappers" "-include" "__clang_openmp_device_functions.h" "-D" "models_EXPORTS" "-I" "/p/software/jurecadc/stages/2022/software/Boost/1.78.0-GCCcore-11.2.0/include" "-I" "/p/scratch/cjinb33/kitayama1/projects/nest-simulator/thirdparty" "-I" "/p/scratch/cjinb33/kitayama1/projects/nest-simulator/libnestutil" "-I" "/p/scratch/cjinb33/kitayama1/build/nest-clang-offload/libnestutil" "-I" "/p/scratch/cjinb33/kitayama1/projects/nest-simulator/sli" "-I" "/p/scratch/cjinb33/kitayama1/projects/nest-simulator/nestkernel" "-I/p/software/jurecadc/stages/2022/software/DB/18.1.40-GCCcore-11.2.0/include" "-I/p/software/jurecadc/stages/2022/software/libreadline/8.1-GCCcore-11.2.0/include" "-I/p/software/jurecadc/stages/2022/software/gettext/0.21-GCCcore-11.2.0/include" "-I/p/software/jurecadc/stages/2022/software/libxml2/2.9.10-GCCcore-11.2.0/include/libxml2" "-I/p/software/jurecadc/stages/2022/software/libxml2/2.9.10-GCCcore-11.2.0/include" "-I/p/software/jurecadc/stages/2022/software/expat/2.4.1-GCCcore-11.2.0/include" "-I/p/software/jurecadc/stages/2022/software/Boost/1.78.0-GCCcore-11.2.0/include" "-I/p/software/jurecadc/stages/2022/software/ICU/70.1-GCCcore-11.2.0/include" "-I/p/software/jurecadc/stages/2022/software/CUDA/11.5/nvvm/include" "-I/p/software/jurecadc/stages/2022/software/CUDA/11.5/extras/CUPTI/include" "-I/p/software/jurecadc/stages/2022/software/CUDA/11.5/include" "-I/p/software/jurecadc/stages/2022/software/libarchive/3.5.1-GCCcore-11.2.0/include" "-I/p/software/jurecadc/stages/2022/software/XZ/5.2.5-GCCcore-11.2.0/include" "-I/p/software/jurecadc/stages/2022/software/cURL/7.78.0-GCCcore-11.2.0/include" "-I/p/software/jurecadc/stages/2022/software/OpenSSL/1.1/include" "-I/p/software/jurecadc/stages/2022/software/bzip2/1.0.8-GCCcore-11.2.0/include" "-I/p/software/jurecadc/stages/2022/software/ncurses/6.2-GCCcore-11.2.0/include" "-I/p/software/jurecadc/stages/2022/software/binutils/2.37-GCCcore-11.2.0/include" "-I/p/software/jurecadc/stages/2022/software/zlib/1.2.11-GCCcore-11.2.0/include" "-internal-isystem" "/p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0" "-internal-isystem" "/p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/x86_64-pc-linux-gnu" "-internal-isystem" "/p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/backward" "-internal-isystem" "/p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0" "-internal-isystem" "/p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/x86_64-pc-linux-gnu" "-internal-isystem" "/p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/backward" "-internal-isystem" "/p/project/cjinb33/kitayama1/dev/clang/lib/clang/15.0.0/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/include" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-internal-isystem" "/p/software/jurecadc/stages/2022/software/CUDA/11.5/include" "-internal-isystem" "/p/project/cjinb33/kitayama1/dev/clang/lib/clang/15.0.0/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/include" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-O2" "-Wno-unknown-cuda-version" "-Wall" "-std=c++17" "-fdeprecated-macro" "-fdebug-compilation-dir=/p/scratch/cjinb33/kitayama1/build/nest-clang-offload/models" "-ferror-limit" "19" "-fvisibility" "protected" "-fopenmp" "-fgnuc-version=4.2.1" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-vectorize-loops" "-vectorize-slp" "-fopenmp-is-device" "-fopenmp-host-ir-file-path" "/tmp/modelsmodule-db8a92.bc" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-o" "/tmp/modelsmodule-4d9df0.s" "-x" "c++" "/p/scratch/cjinb33/kitayama1/projects/nest-simulator/models/modelsmodule.cpp"
 "/p/project/cjinb33/kitayama1/dev/clang/bin/clang-15" "-cc1" "-triple" "nvptx64-nvidia-cuda" "-aux-triple" "x86_64-unknown-linux-gnu" "-S" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "modelsmodule.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-fhalf-no-semantic-interposition" "-mframe-pointer=all" "-ffp-contract=on" "-fno-rounding-math" "-fno-verbose-asm" "-no-integrated-as" "-mlink-builtin-bitcode" "/p/software/jurecadc/stages/2022/software/CUDA/11.5/nvvm/libdevice/libdevice.10.bc" "-target-feature" "+ptx75" "-target-sdk-version=11.5" "-mlink-builtin-bitcode" "/p/project/cjinb33/kitayama1/dev/clang/lib/libomptarget-nvptx-sm_80.bc" "-target-cpu" "sm_80" "-target-feature" "+ptx75" "-mllvm" "-treat-scalable-fixed-error-as-warning" "-debug-info-kind=line-directives-only" "-dwarf-version=2" "-debugger-tuning=gdb" "-fno-dwarf-directory-asm" "-sys-header-deps" "-D" "models_EXPORTS" "-O2" "-Wno-unknown-cuda-version" "-Wall" "-std=c++17" "-fdeprecated-macro" "-fdebug-compilation-dir=/p/scratch/cjinb33/kitayama1/build/nest-clang-offload/models" "-ferror-limit" "19" "-fvisibility" "protected" "-fopenmp" "-fgnuc-version=4.2.1" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-vectorize-loops" "-vectorize-slp" "-fopenmp-is-device" "-fopenmp-host-ir-file-path" "/tmp/modelsmodule-db8a92.bc" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c++" "modelsmodule-2c16b4.cpp"

**Comment by ikitayama** [comment]
> At the bottom of the comment text box, you can see the instructions: `Attach files by dragging & dropping, selecting or pasting them.`

.cpp can't be uploaded.

**Comment by ikitayama** [comment]
[Uploading modelsmodule-2c16b4.cpp.txt…]()

**Comment by vgvassilev** [comment]
We see this with clang-15 and I cannot download the attached file. Could you bisect it to a particular commit?

cc: @alexander-penev.

**Comment by ikitayama** [comment]
I myself no longer see this.
