### ISSUE TITLE
[flang][omp2012] Redundant explicit save in presence of global SAVE statement

### ISSUE THREAD

**Issue by NimishMishra** [llvm/llvm-project#56003]
For the following source:

```f90
! ERROR: flang-new -c -o rc01.o -fopenmp -ffree-form rc01.f90
! WARNING: gfortran -c -o rc01.o -fopenmp -ffree-form rc01.f90


module sample

	type random_type
        integer   ::  x = 0
       real      ::   y = 0.
	end type random_type

     save
     
     integer, parameter :: param=100
     type(random_type),save :: param_list(100)

end module sample

```

The following semantic error is observed in case of `flang-new`:

```console
error: Semantic errors in rc01.f90

./rc01.f90:15:32: error: Explicit SAVE of 'param_list' is redundant due to global SAVE statement

       type(random_type),save :: param_list(100)

                                 ^^^^^^^^^^

./rc01.f90:12:6: Global SAVE statement

       save
```

**Comment by PeixinQiao** [comment]
This is one portbility issue. https://github.com/llvm/llvm-project/blob/16ca490f450ea3ceaeda92addd8546967af4b2e1/flang/lib/Semantics/resolve-names.cpp#L5234-L5237.

@klausler How do we plan to handle this. Workload uses it. Fix the workload code or change the error into one portbility warning?

**Comment by PeixinQiao** [comment]
> Since it is present in the Spec benchmark (and we cannot change it, at least not 2012), I think it is better not to enforce the constraint like other compilers and issue a warning instead.

Agree. It should not one warning. It should be one portability warning. Will prepare one patch requesting for reviews.

**Comment by PeixinQiao** [comment]
@NimishMishra The patch is merged. Please verify this.

**Comment by NimishMishra** [comment]
@PeixinQiao Verified. Only a warning is issued now; no errors. Closing this issue then.
