### ISSUE TITLE
[flang][OpenMP][omp2012] Not yet implemented OpenMP Block construct clauses

### ISSUE THREAD

**Issue by NimishMishra** [llvm/llvm-project#56004]
OpenMP Block construct clauses still err out.

```f90
! ERROR: flang-new -c -o rtc03.o -fopenmp rc03.f90
! SUCCESS: gfortran -c -o rtc03.o -fopenmp rc03.f90

program sample

integer :: k

!$omp parallel default(shared)
!$omp end parallel
end program sample
```

**Comment by PeixinQiao** [comment]
@NimishMishra You may assign this to yourself. Please wait for the patch of firstprivate clause with barrier or rebase your patch depending on that to proceed the review. Prefer the latter.

**Comment by kiranchandramohan** [comment]
@NimishMishra The reproducer seems to work now? Can this be closed or is there something else that needs to be fixed?

**Comment by NimishMishra** [comment]
@kiranchandramohan The reproducer works now. We can close this.
