### ISSUE TITLE
Exceptions not caught in Linux shared library built with libc++

### ISSUE THREAD

**Issue by bucurb** [llvm/llvm-project#56029]
My team is developing a C++ shared library that is primarily used from C# through P/Invoke. We have noticed a weird behavior with exceptions in the C++ code on Linux, where the following method:
```c++
extern "C" void test()
{
    try
    {
        throw std::runtime_error("test");
    }
    catch (std::exception& e)
    {
        std::cout << "Exception caught: " << e.what() << "\n";
    }
    catch (...)
    {
        std::cerr << "Unknown exception caught\n";
    }
}
```
does not catch the `std::exception` but instead prints-out `Unknown exception caught` when invoked from C#. The code above works as expected when `test()` is invoked from a C++ unit-test executable that was also built with libc++.

We have since diagnosed the issue to how the `__cxa_allocate_exception` is resolved. Our shared library built with libc++ will reference the `__cxa_allocate_exception` symbol as:

``DF *UND*    0000000000000000  Base        __cxa_allocate_exception``

When the  C++ unit-test executable loads our shared library, the `__cxa_allocate_exception` is resolved from `⁠⁠libc++abi.so.1` as expected:
``g    DF .text    000000000000004b  Base        __cxa_allocate_exception``
and everything works fine.

However, when our shared library is executed from C#, the process that loads first is actually `dotnet`, which requires:
`` ⁠libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f54d1b0b000)``

So, before our library is even loaded, libstdc++ will be loaded and will resolve `__cxa_allocate_exception` to its own implementation:
``g    DF .text    000000000000005f  CXXABI_1.3  __cxa_allocate_exception``

When our library is finally loaded, the `__cxa_allocate_exception` is already resolved to libstdc++, but presumably some other exception-related symbols are still unresolved, and they are taken from libc++. We therefore end-up with a mix of libc++ and libstdc++ implementations in our shared library, a thing that is not obvious, is unwanted, and probably is also very dangerous in terms of behavior.

The only workaround we have so far is to statically link libc++ into our shared library as well as hide all its symbols, so they are never resolved by the dynamic loader, but it feels very hacky to have to do this. Is there an alternative, cleaner fix?

**Comment by bucurb** [comment]
Sure, but the point I was trying to make is this is pretty much out of our control, if the shared library we're building is going to be used by more than `dotnet`. What's the expectation for someone that just provides 'middleware' components, to just have different flavors built for either  libc++ or libstdc++? As far as we were concerned, we built with a dependency to libc++ and we never expected parts of our symbols to magically auto-resolve to libstdc++ :) It's also not clear to me why the `__cxa_allocate_exception ` needs to have the same name in both libraries while some other std symbols I believe get an additional `__1`

**Comment by DimitryAndric** [comment]
Well, mixing two different C++ libraries is a recipe for disaster, as it is very hard to ensure that there are no collisions in the global namespace. In this case you are running into collisions for the global ``__cxa_`` related symbols, and there is no way to avoid problems, I think.

That said, usually on a specific operating system, there is a system-wide preferred C++ library, and you should normally compile and link your software against that, *especially* if you are building a shared library that is going to be used by other consumers. E.g. on almost all Linux distributions this is GNU libstdc++, on FreeBSD and macOS this is libc++, etc.

Using your own C++ library is really something that you should attempt if you provide a completely self-contained binary. And in this case, you should still recompile all your C++ dependencies against your own C++ library. I believe that Chromium does something like this, but that is emphatically *not* a shared library that is supposed to be loaded by somebody else. :)

**Comment by jsonn** [comment]
The problem here is not mixing libc++ and libstdc++. That's explicitly a supported configuration. What is not supported and will never work properly is mixing libc++abi and libstdc++. So this is definitely a case of "broken as expected".

**Comment by philnik777** [comment]
The proper way to do this if you want to use a dynamic c++abi is to use the same ABI library, as @DimitryAndric and @jsonn pointed out already. If you don't want to do that you can link libc++ and libc++abi statically and hide all symbols by defining `_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS` and `_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS` and passing `-fvisilibility=hidden`, assuming you only have a C ABI.

> It's also not clear to me why the `__cxa_allocate_exception` needs to have the same name in both libraries while some other std symbols I believe get an additional `__1`

The symbol name is specified by the Itanium ABI (https://itanium-cxx-abi.github.io/cxx-abi/abi-eh.html).
