### ISSUE TITLE
Backport request to 14.x: 2d0c9b64a07c6c430ccfe11ea4c767d788d20461 (OpenMP underlinking fix)

### ISSUE THREAD

**Issue by thesamesam** [llvm/llvm-project#56032]
This would help us with a long-standing downstream issue in Gentoo: https://bugs.gentoo.org/816831.

The gist is that libomp was underlinked before 2d0c9b64a07c6c430ccfe11ea4c767d788d20461 (on main) which makes it difficult to use libomp as a provider of OpenMP.

The change should be safe to backport and I'm not aware of any bug reports involving it, especially given most of the time, it'd be thrown away (the -lm) if unused, as people tend to use `-Wl,--as-needed`. That is, it doesn't affect most people anyway.

**Comment by mgorny** [comment]
CC @MaskRay for approval

**Comment by MaskRay** [comment]
LGTM

**Comment by mgorny** [comment]
FYI, backporting this on Gentoo broke stuff:

```
ninja -v -j12 -l0
ninja: error: '/usr/lib/libhwloc.so -lm', needed by 'runtime/src/libomp.so', missing and no known rule to make it
```

**Comment by thesamesam** [comment]
I don't see why that'd happen but given mgorny reports master works fine and I don't think this is urgent, let's just leave it for now.

If someone spots the follow up or something which we might need, we can revisit.

**Comment by thesamesam** [comment]
Reopening.

We need e27ce281399dca8b08b6ca593172a1bd5dbdd5c1 as a follow up.

So, in total:
1. 2d0c9b64a07c6c430ccfe11ea4c767d788d20461
2. e27ce281399dca8b08b6ca593172a1bd5dbdd5c1

**Comment by thesamesam** [comment]
The 14.x branch is closed, so closing.
