### ISSUE TITLE
Add raw_svector_ostream variant for creating temporary strings.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5603]
|  |  |
| --- | --- |
| Bugzilla Link | [5231](https://llvm.org/bz5231) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lattner,@DougGregor,@tkremenek,@sunfishcode |

## Extended Description 
With the proliferation of raw_ostream, its becoming common to have code which creates a small string just for streaming into:
--
    llvm::SmallString<256> NewSyntax;
    llvm::raw_svector_ostream OS(NewSyntax);
    OS << '.' << FieldName->getName() << " = ";
    return OS.str();
--
it would be nice to have a raw_ostream version which included the small string. Something like:
--
  return (llvm::raw_tmp_ostream() << '.' << FileName->getName() << " = ").str();
--

Good idea, bad idea?

**Comment by arsenm** [comment]
Twine does kind of obsolete this. If this is still useful it's not happening as a result of an antique ticket
