### ISSUE TITLE
Clang C compiler does not support declarations after a label

### ISSUE THREAD

**Issue by ramonpantin** [llvm/llvm-project#56040]
```console
$ clang --version
Debian clang version 13.0.1-3+build2
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ clang -c -std=c17 clang-label-bug.c
clang-label-bug.c:5:8: error: expected expression
retry:  int r = bar();
        ^
clang-label-bug.c:6:7: error: use of undeclared identifier 'r'
        if (!r) goto retry;
             ^
clang-label-bug.c:7:9: error: use of undeclared identifier 'r'
        return r;
               ^
3 errors generated.
$ clang -DWORK_AROUND -c -std=c17 clang-label-bug.c
$
*/

#ifndef WORK_AROUND

int bar();
int foo(int a) {
retry:  int r = bar();
        if (!r) goto retry;
        return r;
}

#else

int bar();
int foo(int a) {
retry:; int r = bar();          /* Clang needs the extra ; after the retry: */
        if (!r) goto retry;
        return r;
}

#endif
```

**Comment by efriedma-quic** [comment]
This is [N2496](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2496.pdf), I guess?

**Comment by ramonpantin** [comment]
Whether the C standard grammar allows for this or not, from a GCC compatibility perspective this is broken, for example it does not work with any of these:

clang -std=gnu89  clang-label-bug.c 
clang -std=gnu90  clang-label-bug.c 
clang -std=gnu11  clang-label-bug.c 
clang -std=gnu17  clang-label-bug.c 
clang -std=gnu18  clang-label-bug.c 

Some people might thing this is an issue with the standard text (it might be) but the compilers are usually years and sometimes decades ahead of the standard, standard documents don't compile code, compilers do.  The same happens with the spec for volatile which has been wrong in the standard for C but the compilers do what programmers intend and ignore the wrong text in the standard (there has been a proposal to fix this in the standard for years, but keeps slipping).

I suggest that this be fixed as a GNU GCC compatibility bug.

**Comment by ramonpantin** [comment]
Large code bases that work on GCC don't move cleanly to Clang easily with this (one more reason not to use Clang for them and just maintain them on GCC).

**Comment by efriedma-quic** [comment]
For reference, gcc implemented this in gcc 11 (I assume as part of implementing C2x).

**Comment by frederick-vs-ja** [comment]
This is a C23 feature.

**Comment by AaronBallman** [comment]
@efriedma-quic -- close, it's [N2508](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2508.pdf)

We don't typically open issues for things tracked on our [implementation status page](https://clang.llvm.org/c_status.html) listed as "No", which this one is, to avoid cluttering the bug database with a bunch of known reports. We'll get around to implementing this feature at some point, but I don't think this report needs to be opened currently.

**Comment by ramonpantin** [comment]
Just trying to let the Clang folks know about this, I guess they are aware of this and prefer to implement as a C2X issue as opposed to a GCC compatibility issue.

**Comment by AaronBallman** [comment]
To be clear on the GCC compat story -- when we do go to implement this, I expect we'll implement it the same way as GCC (which is: to treat it as a conforming extension in older language modes instead of just in C2x). But this is a C2x feature and not a GCC extension (GCC just added support for this in 11.x and I believe it was in response to N2508).
