### ISSUE TITLE
Clang-Format removes empty line at end of file

### ISSUE THREAD

**Issue by GeorgWeinhold** [llvm/llvm-project#56054]
For C and C++ an empty line at the end of each file (header and implementation) is mandatory.

clang format does not add this new line. Moreover, clang-format removes existing empty line at the and of files.

This leads to compiler warnings.

**Comment by mkurdej** [comment]
Can you give a reproducer in which clang-format removes the existing empty line, please?

**Comment by XobSod** [comment]
I have this problem too:
`echo "namespace aaa {}\n\n" | clang-format`
if you don't want to use `echo`, then save this to any kind of file and `cat` it.

**Comment by rongcuid** [comment]
I also have this problem

**Comment by owenca** [comment]
https://reviews.llvm.org/D152305
