### ISSUE TITLE
clang-x86 Missed optimizations with adding and multiplying by constants

### ISSUE THREAD

**Issue by AMS21** [llvm/llvm-project#56061]
Watching Jason Tuners [video](https://youtu.be/NE_v4R1dPMA) sparked my interest and led me to compile a list of examples where clang generates more instructions than gcc for a simple example.

Give the following code:
```cpp
int get_value_2(int x) { return 42 + x * 2; }

int get_value_3(int x) { return 42 + x * 3; }

int get_value_5(int x) { return 42 + x * 5; }

int get_value_6(int x) { return 42 + x * 6; }

int get_value_9(int x) { return 42 + x * 9; }

int get_value_10(int x) { return 42 + x * 10; }
```

generates the following assembly:
```asm
get_value_2(int):                       # @get_value_2(int)
        lea     eax, [rdi + rdi]
        add     eax, 42
        ret
get_value_3(int):                       # @get_value_3(int)
        lea     eax, [rdi + 2*rdi]
        add     eax, 42
        ret
get_value_5(int):                       # @get_value_5(int)
        lea     eax, [rdi + 4*rdi]
        add     eax, 42
        ret
get_value_6(int):                       # @get_value_6(int)
        lea     eax, [rdi + 2*rdi]
        add     eax, eax
        add     eax, 42
        ret
get_value_9(int):                       # @get_value_9(int)
        lea     eax, [rdi + 8*rdi]
        add     eax, 42
        ret
get_value_10(int):                      # @get_value_10(int)
        lea     eax, [rdi + 4*rdi]
        add     eax, eax
        add     eax, 42
        ret
```

While gcc generates the following assembly:
```asm
get_value_2(int):
        lea     eax, [rdi+42+rdi]
        ret
get_value_3(int):
        lea     eax, [rdi+42+rdi*2]
        ret
get_value_5(int):
        lea     eax, [rdi+42+rdi*4]
        ret
get_value_6(int):
        lea     eax, [rdi+rdi*2]
        lea     eax, [rax+42+rax]
        ret
get_value_9(int):
        lea     eax, [rdi+42+rdi*8]
        ret
get_value_10(int):
        lea     eax, [rdi+rdi*4]
        lea     eax, [rax+42+rax]
        ret
```

[godbolt link](https://godbolt.org/z/erKE8GjWf)

**Comment by davidbolvansky** [comment]
3 operand LEA is slow

**Comment by rotateright** [comment]
> 3 operand LEA is slow

Right - by default (and I think for all recent Intel CPU tunings), we intentionally avoid those. If you tune for recent AMD, you should get the requested asm:
https://godbolt.org/z/6o9oxsqfr

If there's evidence that the current tuning leads to worse performance, then we can change the settings. If not, then I don't think the bug is valid.

**Comment by AMS21** [comment]
All right thanks for clearing that up.
Closing as invalid.

**Comment by topperc** [comment]
On this subject, I think we should remove TuningSlow3OpsLEA from Ice Lake tuning. Complex LEAs are 1 cycle latency and execute on 2 ports. Simple LEAs are 1 cycle latency and execute on 4 ports. This is a big improvement from pre-ICL where complex was 3 cycle latency on 1 port and simple were 1 cycle latency on 2 ports.

**Comment by topperc** [comment]
Not sure what the right setting is for Alderlake with it's two different core types.

**Comment by bcl5980** [comment]
I test on my machine(12700k/5950x) for the complex lea.
```
lea rax, [rcx+8*rax+42]
lea rax, [rcx+8*rdx+42]
```
| CPU Name | Latency | Throughput|
|-------------|----------|--------------|
| 12700k big | 2 | 3 |
| 12700k little | 2 | 1 |
| 5950x | 2 | 2 |

For simple lea
| CPU Name | Latency | Throughput|
|-------------|----------|--------------|
| 12700k big | 1 | 5 |
| 12700k little | 1 | 3 ? |
| 5950x | 1 | 4 |

test code : https://github.com/bcl5980/uperf

12700k little core has very wide issue but I don't know why I can only measure throughput 3 for simple lea
I think the only case we can get performance benifit from lea 3ops is 12700k big core. Throughput increase from 2.5 to 3.

@topperc I have a little confuse about your data with complex lea latency is 1 on ICL, can you help to show some documents for it?

**Comment by topperc** [comment]
I took it from here https://www.anandtech.com/show/14664/testing-intel-ice-lake-10nm/3 which I assumed was based on data Intel provided.

**Comment by topperc** [comment]
https://uops.info/table.html?search=lea&cb_lat=on&cb_tp=on&cb_uops=on&cb_ports=on&cb_ICL=on&cb_ADLP=on&cb_measurements=on&cb_base=on

Suggests that complex is 1 cycle on ICL but 2 cycle on Alderlake-P.

**Comment by bcl5980** [comment]
> https://uops.info/table.html?search=lea&cb_lat=on&cb_tp=on&cb_uops=on&cb_ports=on&cb_ICL=on&cb_ADLP=on&cb_measurements=on&cb_base=on
> 
> Suggests that complex is 1 cycle on ICL but 2 cycle on Alderlake-P.

Thanks for the explaination.

**Comment by davidbolvansky** [comment]
Interestingly, ICC generates such LEAs with just -O3.
