### ISSUE TITLE
ld64.lld issue with $ld$previous symbols and macOS 13 SDK

### ISSUE THREAD

**Issue by keith** [llvm/llvm-project#56074]
With this simple swift program:

```swift
import Foundation

print(NSString("hi"))
```

Built with the Xcode 14 beta:

```shell
DEVELOPER_DIR=/Applications/Xcode-14.0.0-beta1.app swiftc basic.swift -emit-object -o basic.o
```

and linked with lld:

```shell
./bin/ld64.lld \
 basic.o \
 /Applications/Xcode-14.0.0-beta1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/clang/lib/darwin/libclang_rt.osx.a \
 -syslibroot \
 /Applications/Xcode-14.0.0-beta1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk \
 -lobjc \
 -lSystem \
 -arch \
 arm64 \
 -L \
 /Applications/Xcode-14.0.0-beta1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx \
 -L \
 /Applications/Xcode-14.0.0-beta1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/lib/swift \
 -platform_version \
 macos \
 12.0.0 \
 13.0.0 \
 -o \
 foo
```

crashes on launch:

```console
% ./foo
dyld[74309]: missing symbol called
zsh: abort      ./foo
```

This binary links fine with ld64 from Xcode 13 and 14. After a bit of debugging I believe the issue is incomplete handling of `$ld$previous` symbols, specifically this omission https://github.com/llvm/llvm-project/blob/272bf0fc41e6a50f89dd01b55a33a3aabcdaf5a8/lld/MachO/InputFiles.cpp#L1754-L1756

Scanning the ld64 source I believe in this case what we need to do is add the specified symbol name using the custom install name provided in the symbol. The specific previous symbol in question here is:

```
$ld$previous$/usr/lib/swift/libswiftFoundation.dylib$$1$10.15$13.0$_$sSo8NSStringC10FoundationE13stringLiteralABs12StaticStringV_tcfC$
```

You can see that we're missing the library specified:

```console
% otool -L from-lld | grep Foundation
        /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1932.101.0)
        /usr/lib/swift/libswiftCoreFoundation.dylib (compatibility version 1.0.0, current version 120.100.0, weak)
```

While linking with ld64 provides it:

```console
% otool -L from-ld64 | grep Foundation
        /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1932.101.0)
        /usr/lib/swift/libswiftCoreFoundation.dylib (compatibility version 1.0.0, current version 120.100.0, weak)
        /usr/lib/swift/libswiftFoundation.dylib (compatibility version 300.0.0, current version 1932.101.0)
```

And you can see the symbol is pointing to the wrong library:

```console
% nm from-lld -m | grep Static
(undefined) external _$sSo8NSStringC10FoundationE13stringLiteralABs12StaticStringV_tcfC (from Foundation)
% nm from-ld64 -m | grep Static
(undefined) external _$sSo8NSStringC10FoundationE13stringLiteralABs12StaticStringV_tcfC (from libswiftFoundation)
```

**Comment by keith** [comment]
I could be totally off on the root cause here. Interested for other folks' takes. If I am right and we need to start handling that symbol name we need https://reviews.llvm.org/D128020

**Comment by nico** [comment]
I think your analysis is correct: https://bugs.chromium.org/p/chromium/issues/detail?id=1334039#c17

I have half a local patch for this.

**Comment by nico** [comment]
Sorry for the delay: https://reviews.llvm.org/D130725

**Comment by nico** [comment]
Should we try to merge this to the 15.0 branch?

(@keith, did you have a chance to check if the patch actually works yet?)

**Comment by nico** [comment]
(...we've by now verified that it did in fact the problem we were seeing in practice: https://bugs.chromium.org/p/chromium/issues/detail?id=1334039#c20)

**Comment by int3** [comment]
Nice! Yeah, merging it into 15.0 makes sense

**Comment by keith** [comment]
@nico yea sorry I did verify, seems good! thanks!
