### ISSUE TITLE
clang doesn't respect partial ordering of templates with parameter packs, reports them as ambiguous

### ISSUE THREAD

**Issue by Bu11etmagnet** [llvm/llvm-project#56090]
```cpp
#include <tuple>

struct Q{};

using TUP = std::tuple<Q>;


template<typename Fn>
inline
void feh(Fn&, const std::tuple<>*)
{}

template<typename Fn, typename H>
inline
void feh(Fn& fn, const std::tuple<H>*)
{
    fn(H{});
}

template<typename  Fn, typename H, typename... R>
inline
void feh(Fn& fn, const std::tuple<H, R...>*)
{
    fn(H{});
    using Rest = const std::tuple<R...>*;
    feh<Fn, R...>(fn, static_cast<Rest>(nullptr));
}

template<typename Tuple, typename Fn>
inline
void fe(Fn& fn, const Tuple  *  tpl =  nullptr)
{
    feh(fn, tpl);
}

int main()
{
    auto r = [] (Q const&) {};
    TUP tup;
    fe<TUP>(r, &tup);
}
```

GCC 8.2 (and 12.1) compiles the code just fine. However, clang 11.0.0 (and 14.0.0) complains  that the call from `fe` to `feh` is ambiguous between `void feh(Fn& fn, const std::tuple<H>*)  [with Fn = (lambda at <source>:38:14), H = Q]` and `void feh(Fn& fn, const std::tuple<H, R...>*) [with Fn = (lambda at <source>:38:14), H = Q, R = <>]`.

<https://godbolt.org/z/5E9M6a5c6>

Discussion at <https://stackoverflow.com/q/72658026>.

**Comment by Maetveis** [comment]
We've hit the same error with a simpler example [godbolt](https://godbolt.org/z/Pvvash74s). It seems that having the template class template with variadic template parameters is important. (`A` in my example, and `tuple` in OPs). If its replaced by a parameter pack, overload resolution works fine.
