### ISSUE TITLE
[lld] --dynamic-linker=VALUE is not ignored when creating a statically linked executable

### ISSUE THREAD

**Issue by leleliu008** [llvm/llvm-project#56105]
step1. create a C source file `test.c`:
```C
#include <stdio.h>

int main() {
    printf("%s\n", "Hello World");
    return 0;
}
```
step2. build a statically linked executable:
```bash
clang -fuse-ld=lld -static -Wl,--dynamic-linker=/lib64/ld-linux-x86-64.so.2 test.c
```
step3. show the Program Headers:
![Screenshot from 2022-06-18 17-37-03](https://user-images.githubusercontent.com/3040852/174432065-ec6044d3-2c97-4eba-bb10-61f565ae8b5f.png)

step4. run the executable:
![Screenshot from 2022-06-18 17-42-27](https://user-images.githubusercontent.com/3040852/174432174-662b4e06-d25b-452d-848c-d7ea617baad5.png)
run the executable failed and report `segmentation fault (core dumped)`

**I think the `-Wl,--dynamic-linker=/system/bin/linker64` shall be ignored when `-static` is given**

**I tried the GNU LD(bfd and gold) works fine as my expected.**

**Clang version:**
![Screenshot from 2022-06-18 17-49-48](https://user-images.githubusercontent.com/3040852/174432463-e6e18305-0dee-4427-bdf2-d096a5bfab88.png)

**related issue:**
https://github.com/android/ndk/issues/1722

**Comment by MaskRay** [comment]
This is an area where either behavior works for real world programs.
I think lld's behavior is better in that the options are more orthogonal, so no need to match GNU ld here.

**Comment by leleliu008** [comment]
LLD's behaver is not good for porting existing projects. If project build script already set `--dynamic-linker=VALUE`, then I pass `-static` to the linker  to build a fully statically linked executable, the executable would not runnable.

**Comment by MaskRay** [comment]
A user project is not supposed to specify --dynamic-linker. The path is usually fixed for a platform and the compiler driver passes the value to ld. If you want to use a different prefix, specify --dyld-prefix instead. The driver will drop --dynamic-linker for some configurations. The lld behavior has the nice property that we can test the behavior of using a rtld in the absense of any DT_NEEDED. In GNU ld the conditions are more complex.
