### ISSUE TITLE
FileCheck should try to fuzzy match forward when checks fail

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5611]
|  |  |
| --- | --- |
| Bugzilla Link | [5239](https://llvm.org/bz5239) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Consider this log taken from a buildbot:
--
******************** TEST 'Clang::CodeGenCXX/references.cpp' FAILED ********************Script:
--
/Users/buildslave/zorg/smooshlab/slaves/clang/build.clang-i386-darwin9/llvm/Debug/bin/clang-cc -verify -emit-llvm -o - /Users/buildslave/zorg/smooshlab/slaves/clang/build.clang-i386-darwin9/llvm/tools/clang/test/CodeGenCXX/references.cpp | FileCheck /Users/buildslave/zorg/smooshlab/slaves/clang/build.clang-i386-darwin9/llvm/tools/clang/test/CodeGenCXX/references.cpp
--
Exit Code: 1
Command Output (stdout):
--
--
Command Output (stderr):
--
/Users/buildslave/zorg/smooshlab/slaves/clang/build.clang-i386-darwin9/llvm/tools/clang/test/CodeGenCXX/references.cpp:124:34: error: expected string not found in input
 // CHECK: call void @&#8203;_ZN1T1B1fEv
                                 ^
<stdin>:245:24: note: scanning from here
 call void @&#8203;_ZN1T1BC1Ev(%struct.A* %tmp)
                       ^
--

********************
--

The failure is probably something about the mangling being different on the platform in question. It would be nice if when there is a check failure, FileCheck would scan forward "fuzzily" trying to find the most likely match. For example, if the next line in the log was 'call void @&#8203;_ZN1T1B$@^@' I would like to see an additional:
--
<stdin>:246:1: note: found likely match here:
call void @&#8203;_ZN1T1B$@^@
^
--

The "fuzzyness" could be something like minimum edit distance within the next 1k characters, or so.

**Comment by arsenm** [comment]
FileCheck does do this
