### ISSUE TITLE
LLDB: GDB remote protocol feature/packet `swbreak` not supported 

### ISSUE THREAD

**Issue by ByteNacked** [llvm/llvm-project#56125]
Hello,
When I was trying to use latest `lldb` with `gdbserver`, I came across an issue of not supported feature/packet `swbreak` in GDB remote protocol. 
As far as I understand, without this feature, software breakpoints do not work correctly then using with `gdbserver`.

On `swbreak` in [gdb manual](https://sourceware.org/gdb/onlinedocs/gdb/Stop-Reply-Packets.html#swbreak-stop-reason):

_On some architectures, such as x86, at the architecture level, when a breakpoint instruction executes the program counter points at the breakpoint address plus an offset. On such targets, the stub is responsible for adjusting the PC to point back at the breakpoint address._

And this is exactly that (not) happens then I trying to use software breakpoints in this setup,
PC register does not adjusted and program crashes.

Is that intendent behaviour?
Will patches adding this feature be accepted?

Ubuntu 20.04.4 LTS x86_64
llvb version : latest master/main
gdbserver version : GNU gdbserver (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2

**Comment by DavidSpickett** [comment]
My point was that you might be arguing to move lldb-server to using swbreak as well/instead, to align it with gdbserver. That is more work and like you said we already have an equivalent for lldb to lldb-server connections.

If you can make lldb understand swbreak and test it without any lldb-server changes that's fine. I know we can test lldb-server by supplying it packets (e.g. `lldb/test/API/tools/lldb-server/memory-tagging/TestGdbRemoteMemoryTagging.py`) but I'm not sure if we can do the same with lldb. The closest I've written is stuff like `lldb/unittests/Process/gdb-remote/GDBRemoteCommunicationClientTest.cpp`.

If the change is small enough it might be able to go in without specific testing.

**Comment by ByteNacked** [comment]
Okay, thanks,
I'll look into `lldb/unittests/Process/gdb-remote/GDBRemoteCommunicationClientTest.cpp` .

**Comment by labath** [comment]
> If you can make lldb understand swbreak and test it without any lldb-server changes that's fine. I know we can test lldb-server by supplying it packets (e.g. `lldb/test/API/tools/lldb-server/memory-tagging/TestGdbRemoteMemoryTagging.py`) but I'm not sure if we can do the same with lldb.

Tests for the opposite direction can be found in `test/API/functionalities/gdb_remote_client/`

**Comment by xusheng6** [comment]
Is there any update on this? This is now causing https://github.com/Vector35/debugger/issues/535 for the Binary Ninja debugger

**Comment by DavidSpickett** [comment]
Zero changes in this area lately. PRs welcome if anyone wants to fix this themselves.

https://lldb.llvm.org/resources/build.html
https://llvm.org/docs/Contributing.html#how-to-submit-a-patch

**Comment by xusheng6** [comment]
> Zero changes in this area lately. PRs welcome if anyone wants to fix this themselves.
> 
> https://lldb.llvm.org/resources/build.html https://llvm.org/docs/Contributing.html#how-to-submit-a-patch

Thanks for letting me know. I will consider it, but do not expect too much :)

**Comment by xusheng6** [comment]
I created a PR that should fix this: https://github.com/llvm/llvm-project/pull/102873, please have a look at it!
