### ISSUE TITLE
[libc] Potential wrong syscall number reference in linux_file.cpp

### ISSUE THREAD

**Issue by gytsen** [llvm/llvm-project#56122]
While browsing the `File` implementation of the new LLVM libc, I spotted what I believe to be a potential typo in the linux file implementation:

The code looks for the `SYS__llseek` syscall number in the `#if defined` statement [on line 78](https://github.com/llvm/llvm-project/blob/aa88161b378ecb49388eefc28abe2926a229bcfc/libc/src/__support/File/linux_file.cpp#L78). However, when doing the actual syscall, `__llvm_libc::syscall` is called with `SYS__lseek` as argument [on line 80](https://github.com/llvm/llvm-project/blob/aa88161b378ecb49388eefc28abe2926a229bcfc/libc/src/__support/File/linux_file.cpp#L80). If I'm not mistaken that is a typo and the call should read
```cpp
long ret = __llvm_libc::syscall(SYS__llseek, lf->get_fd(), offset >> 32,
                                  offset, &result, whence);
```

instead.

If this is not the case, feel free to close this issue as not relevant.

**Comment by sivachandra** [comment]
Fixed by https://reviews.llvm.org/D133022
