### ISSUE TITLE
Segfault, bisected to cc65f3e "[GlobalOpt] Preserve CFG analyses"

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#56131]
[testcase.tar.gz](https://github.com/llvm/llvm-project/files/8942545/testcase.tar.gz)

opt -mtriple=s390x-linux-gnu -march=z14 ./tc_segv.ll -O3 -o out.opt.ll

**Comment by aeubanks** [comment]
I've reverted in 1cd2c72befae87d68842c3c2c3ffe86edd63767b for now, will investigate

**Comment by aeubanks** [comment]
Should be fixed with latest revision of https://reviews.llvm.org/D128145, verified that it fixes the crash. Thanks for the report!
Closing since the patch was already reverted.
