### ISSUE TITLE
[flang] external procedure name generated not consistent with `flang-new` and `bbc + tco`

### ISSUE THREAD

**Issue by PeixinQiao** [llvm/llvm-project#56138]
```console
$ cat conftest.f90 
program main
 external testfunc
 call testfunc(1)
end
$ flang-new -fc1 -emit-llvm conftest.f90 
$ cat conftest.ll 
...
define void @_QQmain() !dbg !3 {
  %1 = alloca i32, i64 1, align 4, !dbg !7
  store i32 1, ptr %1, align 4, !dbg !7
  call void @testfunc_(ptr %1), !dbg !7
  ret void, !dbg !9
}
```
The external procedure name `testfunc_` can be interoperated with C.
```llvm
$ bbc -emit-fir conftest.f90
$ tco conftest.mlir 
...
define void @_QQmain() !dbg !3 {
  %1 = alloca i32, i64 1, align 4, !dbg !7
  store i32 1, ptr %1, align 4, !dbg !9
  call void @_QPtestfunc(ptr %1), !dbg !10
  ret void, !dbg !11
}
```
The external procedure name `_QPtestfunc` cannot be interoperated with C.

Is this designed on purpose? The `flang-new` in `fir-dev` does not support this. Is this new supported feature somewhere in llvm main?
@jeanPerier @schweitzpgi

**Comment by kiranchandramohan** [comment]
Yes, the ExternalNameConversion pass is enabled in the flang-new driver in llvm-project/main. https://reviews.llvm.org/D121171

**Comment by kiranchandramohan** [comment]
We did not cherry-pick that patch to `fir-dev`. So `fir-dev` `flang-new` does not have the `ExternalNameConversion` pass.

**Comment by PeixinQiao** [comment]
@kiranchandramohan @clementval Got it. Thanks a lot.

**Comment by banach-space** [comment]
> This is the normal behavior. `flang-new` has the ExternalNameConversion pass on by default and `bbc` + `tco` don't.

I agree that this is expected (i.e. that's what we implemented), but making `flang-new` and `bbc`+`tco` behave consistently would make more sense to me personally. 

In any case, this is the direction that was decided in https://reviews.llvm.org/D121171.

**Comment by clementval** [comment]
> > This is the normal behavior. `flang-new` has the ExternalNameConversion pass on by default and `bbc` + `tco` don't.
> 
> I agree that this is expected (i.e. that's what we implemented), but making `flang-new` and `bbc`+`tco` behave consistently would make more sense to me personally.

`bbc` and `tco` are purely dev test tool. It makes sense to not have the mangling on by default on them.
