### ISSUE TITLE
How to pass addition arguments to llvm pass registered by new pass manager

### ISSUE THREAD

**Issue by LeoneChen** [llvm/llvm-project#56137]
When I use `clang-13 -fpass-plugin` to load pass, and use `mllvm` to provide addition arguments

![image](https://user-images.githubusercontent.com/35480440/174749033-579b4f68-8af7-4f1d-8d15-dcc35ab09bab.png)

Then I get error

![image](https://user-images.githubusercontent.com/35480440/174749414-d4978b92-6fe3-44e6-b755-47b26463cfad.png)

But when I use `clang-13 -flegacy-pass-manager -Xclang -load -Xclang` to load it, everything is OK

**Comment by Chordp** [comment]
Same question

**Comment by viroulep** [comment]
At the moment the only way to be able to register options and still use the new PM is to provide both the `-Xclang -load -Xclang lib.so` and `-Xclang -fpass-plugin=lib.so`.

The first load will make sure the options defined in the library will be registered before command line arguments are parsed.

**Comment by LeoneChen** [comment]
OK, thanks~

**Comment by OfekShilon** [comment]
@viroulep  On clang 16 I'm getting "Bad options: -load" with this. Has the workaround changed since writing this?

**Comment by viroulep** [comment]
I don't think so, the `load` option seems to be still here, I just compiled the `Bye` example plugin and ran it over some very basic IR and the workaround seemed to still work:
```bash
foo@d366b74ba893:~/llvm/tmp/tests/Bye/build$ clang-16 -Xclang -load -Xclang ./Bye.so -fpass-plugin=./Bye.so -mllvm -wave-goodbye foo.ll -S
Bye: g
Bye: f
Bye: main
```

While looking at the code I also realized the frontend turns `-fplugin` into the appropriate load so this works too:
```bash
foo@d366b74ba893:~/llvm/dockers/tests/Bye/build$ clang-16 -fplugin=./Bye.so -fpass-plugin=./Bye.so -mllvm -wave-goodbye foo.ll -S
Bye: g
Bye: f
Bye: main
```

**Comment by OfekShilon** [comment]
@viroulep  Thank you! Perhaps invoking plugins this way works only on IR? If I change foo.ll into some toy foo.cpp I can no longer see "Bye: foo"

**Comment by viroulep** [comment]
I think it works on cpp as well:
```bash
foo@cf52f006f235:~/llvm/dockers/tests/Bye/build$ cat main.cpp 
int main() { return 0; }
foor@cf52f006f235:~/llvm/dockers/tests/Bye/build$ clang-16 -O1 -fplugin=./Bye.so -fpass-plugin=./Bye.so -mllvm -wave-goodbye main.cpp 
Bye: main
```

If the driver doesn't complain about an unknown option then the plugin is surely loaded and maybe it's just because you compile with `-O0`?
If you don't specify a `-O` then `-O0` is assumed and clang will add an `optnone` attribute to the functions, and therefore `Bye` will not run over them (because the pass implemented in the `Bye` plugin doesn't implement the `isRequired` function).

**Comment by OfekShilon** [comment]
@viroulep Thanks - you're right of course. I now think my problem is different: our plugin implements 2 passes (say "pass1" and "opass2") and according to the existing docs `-mllvm -passes=pass1` should have made just pass1 apply. Is it possible this doesn't work in the new pass manager?

**Comment by StormBytePP** [comment]
> At the moment the only way to be able to register options and still use the new PM is to provide both the `-Xclang -load -Xclang lib.so` and `-Xclang -fpass-plugin=lib.so`.
> 
> The first load will make sure the options defined in the library will be registered before command line arguments are parsed.

Is this still valid for 19 or 20 version? I tested with polly and ```-fplugin=LLVMPolly.so -fpass-plugin=LLVMPolly.so``` (with no ```-Xclang```) and it seems to work (with ```-fplugin-arg-polly-XXXX``` yet I have a question:

Are both needed or just one of them?
