### ISSUE TITLE
ICE when using non-local lambda expression in IILE in requires clause

### ISSUE THREAD

**Issue by ldalessa** [llvm/llvm-project#56132]
While attempting to write a concept that requires that a type has an `operator()()` with a dependent number of arguments, I encountered this ICE (this is a reduced testcase).

live: https://godbolt.org/z/TYbxf5P65

```c++
#include <utility>

template <class T>
concept indexable2 = requires {
    requires []<std::size_t... is>(std::index_sequence<is...>) {
        return requires (T t) { { t(is...) }; };
    }(std::make_index_sequence<2>{});
};

static_assert(not indexable2<int>);
```

Workaround is to use free functions/trait class for the test.

**Comment by oToToT** [comment]
Closing as this seems to be fixed on trunk.

**Comment by ldalessa** [comment]
Thanks, looks like it was fixed in 13.
