### ISSUE TITLE
FYI: consuming too much RAM during build

### ISSUE THREAD

**Issue by DennisYurichev** [llvm/llvm-project#56145]
If to run cmake with no -j option, it may use all CPU cores available.
But during linking phase, this may consume all RAM available, which leads to extensive paging.
I had to build it with "-j 1".

**Comment by topperc** [comment]
You can limit the number of link jobs by passing `-DLLVM_PARALLEL_LINK_JOBS=<num>` to cmake

See https://llvm.org/docs/GettingStarted.html#common-problems

**Comment by DennisYurichev** [comment]
Yes, I built with Ninja.

**Comment by DennisYurichev** [comment]
Of course, I'm a noob and stranger to LLVM folks, maybe I shouldn't give advice, but I think linking phase should be more RAM-friendly...

**Comment by topperc** [comment]
Which linker are you using? And what CMAKE_BUILD_TYPE are you using?

**Comment by fhahn** [comment]
Thanks for the report. As this is not really an actionable issue I'm going to close this one. Some suggestions can be found at the link @topperc mentioned: [ttps://llvm.org/docs/GettingStarted.html#common-problems](https://llvm.org/docs/GettingStarted.html#common-problems)
