### ISSUE TITLE
[OpenMP for MIPS] A "#else" is missed here?

### ISSUE THREAD

**Issue by Peter9606** [llvm/llvm-project#56169]
https://github.com/llvm/llvm-project/blob/1dd2c93a660cd5de0769ff88634fe149904caa17/openmp/runtime/src/kmp_affinity.h#L257

Don't see any reason that `#error` should be put here, but for arch that doesn't support sched_setaffinity and sched_getaffinity. So I guess a "#else" is missed.

**Comment by shiltian** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/3f9d51ab5a1d0bd23acccca13d060ded7dff2086.
