### ISSUE TITLE
clang fails to compile constexpr std::vector from libstdc++

### ISSUE THREAD

**Issue by ldalessa** [llvm/llvm-project#56167]
Now that libstdc++ has a fully constexpr c++20 vector, I'd like to start using it, however it seems to trigger a lifetime tracking bug in llvm.

```c++
#include <vector>

constexpr bool test() {
    std::vector<int> data(10);
    return true;
}

static_assert(test());
```

live: https://godbolt.org/z/qrfxPGxYY

**Comment by JohelEGP** [comment]
This works now: https://compiler-explorer.com/z/hExoM16f8.

**Comment by AaronBallman** [comment]
> This works now: https://compiler-explorer.com/z/hExoM16f8.

That is testing against libc++ and not libstdc++. When you switch to libstdc++, you get an assertion: https://compiler-explorer.com/z/5x91Eo5hT

**Comment by JohelEGP** [comment]
That's probably a libstdc++ bug. At no point in the call stack is `construct_at` used. There are a number of open bugs about lifetimes and constant evaluation in GCC. See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102284, for example.

**Comment by ldalessa** [comment]
It looks to me like <https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/stl_vector.h#L378> should end up calling <https://github.com/gcc-mirror/gcc/blob/16e2427f50c208dfe07d07f18009969502c25dc8/libstdc%2B%2B-v3/include/bits/alloc_traits.h#L259>, at least for some types. Did you trace execution?

**Comment by JohelEGP** [comment]
No. I just looked at the constant evaluation call stack.

**Comment by JohelEGP** [comment]
I tried reducing this: https://compiler-explorer.com/z/vx3GEn4Tc. For some reason, using the `const` overload of the allocator accessor makes it work.

**Comment by usx95** [comment]
Works at trunk
