### ISSUE TITLE
Unable to download tar.gz of certain commits

### ISSUE THREAD

**Issue by npanpaliya** [llvm/llvm-project#56177]
Tensorflow 2.8 and 2.9 needs following commits of llvm in the form of .tar.gz -
1. 55c71c9eac9bc7f956a05fa9258fad4f86565450
2. 1cb299165c859533e22f2ed05eb2abd5071544df

I am able to download .zip of these commits but not .tar.gz. This had been working but suddenly it started failing for me today (after I cleared bazel cache, so probably it started to fail even earlier than today). As a result of these even TF Serving and TF-text are not being built as they build TF during their builds. I can always patch TF to download .zip instead of .tar.gz but it would mess my existing patches of TF serving build which are already too complicated.

Kindly help me to get this working.

**Comment by fhahn** [comment]
Are you referring to be able to download `llvm-project` for a certain commit as tar.gz? I think the file formats for such a download is set by Github and I doubt there is something we can do to change that.

For now, I am going to close this issue as I don't think there's anything we can do. Please check with Tensorflow for instructions on how to build Tensorflow. If I missed anything, please feel free to re-open the issue.

**Comment by npanpaliya** [comment]
It had been working earlier. I don't know what has been changed and where. I've been building TF with these commit of llvm in .tar.gx format for months almost every day.

**Comment by npanpaliya** [comment]
@fhahn - I can't reopen this issue.

**Comment by fhahn** [comment]
It is still not clear to me what is not working exactly. Could you please specify *how* you were downloading the repo?

I just tried to download a tarball of the repo for a specific commit, which still seems to work (see below). Github might have made some changes, but in that case you would have to raise the issue with Github directly.

```
wget -v https://github.com/llvm/llvm-project/tarball/2b4931ef8ad28acbd99cb720959e2bef85b9e67e -o ball.tar.gz --show-progress -O -  | tar xz
```

**Comment by npanpaliya** [comment]
I'm still not able  to download `wget https://github.com/llvm/llvm-project/archive/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz`

Tensorflow downloads all its dependencies during the build. llvm is also one of the TF's dependencies as mentioned here https://github.com/tensorflow/tensorflow/blob/v2.8.2/third_party/llvm/workspace.bzl#L16. 
So, as mentioned in this file bazel tries to download llvm using this URL - `https://github.com/llvm/llvm-project/archive/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz` and it fails with following error -
```
ERROR: An error occurred during the fetch of repository 'llvm-raw':
   Traceback (most recent call last):
        File "/home/builder/.cache/bazel/_bazel_builder/7f1960e17c17f32efa867bcb217eb3f2/external/org_tensorflow/third_party/repo.bzl", line 64, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz, https://github.com/llvm/llvm-project/archive/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz] to /home/builder/.cache/bazel/_bazel_builder/7f1960e17c17f32efa867bcb217eb3f2/external/llvm-raw/temp12603311405036985429/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz: Read timed out
ERROR: /opt/conda/conda-bld/tensorflow-serving_1655987108570/work/WORKSPACE:39:10: fetching _tf_http_archive rule //external:llvm-raw: Traceback (most recent call last):
        File "/home/builder/.cache/bazel/_bazel_builder/7f1960e17c17f32efa867bcb217eb3f2/external/org_tensorflow/third_party/repo.bzl", line 64, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz, https://github.com/llvm/llvm-project/archive/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz] to /home/builder/.cache/bazel/_bazel_builder/7f1960e17c17f32efa867bcb217eb3f2/external/llvm-raw/temp12603311405036985429/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz: Read timed out
ERROR: no such package '@llvm-raw//utils/bazel': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz, https://github.com/llvm/llvm-project/archive/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz] to /home/builder/.cache/bazel/_bazel_builder/7f1960e17c17f32efa867bcb217eb3f2/external/llvm-raw/temp12603311405036985429/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz: Read timed out
```

Then I also tried downloading this commit using wget and it also fails with 504 Gateway Timeout error. 

The commit that you tried is working for me as well. I checked some of the recent commits of llvm and they are being downloaded perfectly.

**Comment by fhahn** [comment]
> Then I also tried downloading this commit using wget and it also fails with 504 Gateway Timeout error.
>
> The commit that you tried is working for me as well. I checked some of the recent commits of llvm and they are being downloaded perfectly.

Right, this all seems to indicate a Github issue, not an issue with `llvm-project`.

**Comment by npanpaliya** [comment]
> > Then I also tried downloading this commit using wget and it also fails with 504 Gateway Timeout error.
> > The commit that you tried is working for me as well. I checked some of the recent commits of llvm and they are being downloaded perfectly.
> 
> Right, this all seems to indicate a Github issue, not an issue with `llvm-project`.

Okay. Thanks for your replies and help.

**Comment by npanpaliya** [comment]
Could you please help me with the link where I can create the issue with Github directly?

**Comment by npanpaliya** [comment]
> Could you please help me with the link where I can create the issue with Github directly?

Got the link.
