### ISSUE TITLE
clang-format: misformatted method body when declared with trailing return type syntax followed by a requires clause

### ISSUE THREAD

**Issue by elevendroids** [llvm/llvm-project#56176]
`clang-format` incorrectly formats methods declared with the trailing return type syntax followed by a `requires` clause.

Tested version:
```
clang-format version 15.0.0 (https://github.com/llvm/llvm-project.git e8716179eb0b57ad6d767bb17f349f32f387c7bd)
```

Platform:
Arch Linux, x86_64

---

Consider this example:

```c++
template<typename T>
struct Foo
{
    auto bar() -> int
    requires(is_integral_v<T>)
    {
        call_something();
        return 0;
    }
};
```

Reformatting it with `clang-format` (using the default configuration) leads to badly indented function body:
```c++
template <typename T> struct Foo {
  auto bar() -> int requires(is_integral_v<T>) {
                      call_something();
                      return 0;
                    }
};
```

When using the regular return type syntax... :
```c++
template<typename T>
struct Foo
{
    int bar()
    requires(is_integral_v<T>)
    {
        call_something();
        return 0;
    }
};
```

... the method is formatted as expected:
```c++
template <typename T> struct Foo {
  int bar()
    requires(is_integral_v<T>)
  {
    call_something();
    return 0;
  }
};
```

**Comment by mkurdej** [comment]
It looks as if the function braces where considered a part of the requires clause (compound requirements).
@HazardyKnusperkeks, WDYT?

**Comment by HazardyKnusperkeks** [comment]
It's parsed as a requires expression, the detection heuristic is flawed.

**Comment by HazardyKnusperkeks** [comment]
Review: https://reviews.llvm.org/D128496

**Comment by helmesjo** [comment]
@HazardyKnusperkeks 

There appears to still be an edge case regarding this.
Tweaking the original example by adding `&` to the trailing return and using `decltype(...)` in the requires statement breaks it in the same way:
```c++
  template<typename T>
  struct Foo
  {
    auto bar(T in) -> int& requires (is_integral_v<decltype(in)>) {
                             call_something();
                             return 0;
                           }
  };
```

Changing one of the following fixes the formatting again:
* `-> int&` to `-> int`
* `decltype(in)` to `T`
* `requires (...)` to `requires ...`

```
$ clang++ --version
Homebrew clang version 17.0.6
```

**Comment by HazardyKnusperkeks** [comment]
I think there will always be edge cases. :) Just open a new issue, you may link to this and tag me.
