### ISSUE TITLE
libc++:  thread::id operators == != (others) won't compile.

### ISSUE THREAD

**Issue by edfvogel** [llvm/llvm-project#56187]
Certain uses of the thread::id operators will not work when using libc++.  

Here is a cut/paste from a cygwin session:

```console
$ cat t.cpp
#include <thread>

std::thread::id id;

bool noexcept00 = noexcept(std::operator==(id, id));
bool noexcept01 = noexcept(std::operator!=(id, id));
bool noexcept02 = noexcept(std::operator< (id, id));

VogelEd@XLB3502Q4E ~/tests/perenstl
$ clang++ -c -std=c++11 t.cpp

VogelEd@XLB3502Q4E ~/tests/perenstl
$ clang++ -c -std=c++11 -stdlib=libc++ t.cpp
t.cpp:5:28: error: no matching function for call to 'operator=='
bool noexcept00 = noexcept(std::operator==(id, id));
                           ^~~~~~~~~~~~~~~
<many more messages follow>
```

VS2019 also compiles this without error.

Not important.  Just wanted to let you know.

Ed Vogel

**Comment by frederick-vs-ja** [comment]
libc++ defines these operators as hidden friends, which seems non-comforming.

**Comment by vogelsgesang** [comment]
In review: https://reviews.llvm.org/D131430

**Comment by vogelsgesang** [comment]
Note that in C++20

```
bool noexcept01 = noexcept(std::operator!=(id, id));
bool noexcept02 = noexcept(std::operator< (id, id));
```

will be broken again. This is because C++20 removes `operator!=` and `operator<` and replaces them the compiler-synthesized comparisons based on `operator<=>`. See https://reviews.llvm.org/D131362

**Comment by jwakely** [comment]
IMHO calling operators using function call syntax instead of operator notation is always wrong. Operator overloads are defined as functions named `operator@` in C++ because that's how the language is defined, but you're not supposed to *call* that named function. IMHO the example here is almost as bad as taking the address of std::lib functions, which is forbidden in the latest standard.

**Comment by vogelsgesang** [comment]
I agree with you in general, @jwakely: Calling comparison operators using `std::operator@` is unusual and a bit unexpected.

As soon as the standard allows us to declare those comparators as hidden friends, I think we should do it. I would love to see the standard changed in that direction. Until then, I guess we should stay standard-compliant.

Also note that there are additional subtle differences between hidden friends and free-standing functions besides the possibility to call free functions as `std::operator@`. See https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1614r2.html#friendship
