### ISSUE TITLE
compiler-rt riscv support

### ISSUE THREAD

**Issue by mttbx** [llvm/llvm-project#56196]
```console
ld.lld: error: unable to find library -lgcc
ld.lld: error: unable to find library -lclang_rt.builtins-riscv64
```

**Comment by MaskRay** [comment]
compiler-rt/lib/builtins (compiled to `linux/libclang_rt.builtins-riscv64.a` or `$triple/libclang_rt.builtins.a`) supports RISC-V, so I think this request is invalid.

If you think something is missing or there is a build system problem, please see http://www.catb.org/~esr/faqs/smart-questions.html and reopen with more information:

* Be precise and informative about your problem

**Comment by dshm** [comment]
Is this issue solved? if so, how to solve it? I meet the same problem when compile llvm and clang for the use of generate code to riscv target
