### ISSUE TITLE
Build failure on AIX due to 30dfe016d4 "[CMake][compiler-rt] Use COMPILE_OPTIONS and LINK_OPTIONS"

### ISSUE THREAD

**Issue by orcguru** [llvm/llvm-project#56200]
FAILED: /buildbot_worker/official-worker/clang-aix-dev/build/lib/clang/15.0.0/lib/aix/libclang_rt.atomic-powerpc.so 
: && "/gsa/rtpgsa-p2/00/xlcmpbldenv/aix/cmake-3.16.0/share/cmake-3.16/Modules/Platform/AIX/ExportImportList" -o CMakeFiles/clang_rt.atomic-dynamic-powerpc.dir/objects.exp CMakeFiles/clang_rt.atomic-dynamic-powerpc.dir/atomic.c.o && /buildbot_worker/official-worker/clang-aix-dev/build/./bin/clang --target=powerpc-ibm-aix -fPIC -Wl,-bE:CMakeFiles/clang_rt.atomic-dynamic-powerpc.dir/objects.exp -O3 -DNDEBUG  -m32 -Wl,-G "-Wl,-H512 -Wl,-D0      -Wl,-T512 -Wl,-bhalt:4 -Wl,-bernotok      -Wl,-bnoentry -Wl,-bexport:/buildbot_worker/official-worker/clang-aix-dev/llvm/compiler-rt/lib/builtins/ppc/atomic.exp      -Wl,-bmodtype:SRE -Wl,-lc" -shared -Wl,-bnoipath -o /buildbot_worker/official-worker/clang-aix-dev/build/lib/clang/15.0.0/lib/aix/libclang_rt.atomic-powerpc.so CMakeFiles/clang_rt.atomic-dynamic-powerpc.dir/atomic.c.o  -Wl,-blibpath:/usr/lib:/lib && strip -e -X32_64 /buildbot_worker/official-worker/clang-aix-dev/build/lib/clang/15.0.0/lib/aix/libclang_rt.atomic-powerpc.so && :

clang-15: error: linker command failed with exit code 255 (use -v to see invocation)
[267/271] Building C object CMakeFiles/clang_rt.atomic-dynamic-powerpc64.dir/atomic.c.o
ninja: build stopped: subcommand failed.
[1090/1112] Linking CXX executable bin/sancov
FAILED: runtimes/builtins-stamps/builtins-build

**Comment by orcguru** [comment]
Code change in compiler-rt/cmake/Modules/CompilerRTUtils.cmake triggered the failure

**Comment by petrhosek** [comment]
Is this issue still active?

**Comment by petrhosek** [comment]
This should be addressed by https://reviews.llvm.org/D128552.
