### ISSUE TITLE
How to get the unique name or identifier of mlir operation's operand(value)?

### ISSUE THREAD

**Issue by jxhekang** [llvm/llvm-project#56214]
Is there a good way to get  the unique name or identifier of mlir operation's operand(value)?
I didn't find the answer from : https://mlir.llvm.org/doxygen/classmlir_1_1Value.html

**Comment by River707** [comment]
The closest thing to getting a "name" would be `printAsOperand`, which would give you the representation a value would have if the IR were printed (i.e. the `%foo`).

**Comment by jxhekang** [comment]
> 

Thanks, that's what I need!
