### ISSUE TITLE
Clang doesn't read Direct X9 commands in referenced  file DBOData.h 

### ISSUE THREAD

**Issue by DeVaughn97** [llvm/llvm-project#56227]
Hi I'm trying to get Clang to generate an assembly file from my C++ file and for some reason clang can't read D3DXMATRIXA16 despite being defined in  DBOData.h 

![image](https://user-images.githubusercontent.com/94544102/175806157-18c82114-e0aa-42c4-b93a-6b9a323014f1.png)

any ideas on why clang can't read this definition?

**Comment by efriedma-quic** [comment]
Missing reproduction steps; see https://llvm.org/docs/HowToSubmitABug.html .

But I suspect D3DXMATRIXA16 isn't actually defined anywhere, and there's something wrong with your headers.
