### ISSUE TITLE
[flang] `flang-new` linking failure: relocation R_X86_64_32 against `.bss' can not be used

### ISSUE THREAD

**Issue by PeixinQiao** [llvm/llvm-project#56223]
```console
$ cat conftest.c 
#include <stdio.h>
#include <stdlib.h>

void size_(char *a, char *b)
{
    int diff = (int) (b - a);
    FILE *f=fopen("conftestval", "w");
    if (!f) exit(1);
    fprintf(f, "%d\n", diff);
}

$ cat conftestf.f90 
program fsize

   external size
   CHARACTER :: x(2)
   call size(x(1),x(2))
end program
```
```console
$ clang conftest.c -c
$ flang-new -flang-experimental-exec conftestf.f90 conftest.o -fPIE
/usr/bin/ld: /tmp/conftestf-e22a08.o: relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIE
flang-new: error: linker command failed with exit code 1 (use -v to see invocation)
$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.34
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```
Is this because flang runtime static library built without `-fPIC`?

**Comment by banach-space** [comment]
Hi @peixin , thanks for reporting this!

While it's been pointed out that this might not be the right approach, https://reviews.llvm.org/D128333 should allow you to work around this for the time being. I'm still looking for the most suitable approach.

-Andrzej

**Comment by banach-space** [comment]
Btw, I've observed this behavior while building SNAP on X86. It works just fine on AArch64 (most likely because some object files on AArch64 just happen to be PIC).

I've updated the title to highlight that:
* this is not specific to any particular application
* it's a linking error

**Comment by PeixinQiao** [comment]
Thanks @banach-space . Assign this to you.

**Comment by banach-space** [comment]
@PeixinQiao I'm not seeing this issue with your particular reproducer (I do see it with SNAP, though). 

I've tested with ld.bfd 2.34 and LLVM's ToT (48eb2bc608e2). How did you build `flang-new` and `clang`? Here's my CMake configuration:
```
cmake -G Ninja -CLLVM_TARGETS_TO_BUILD=host -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=On <llvm-project-dir>
```
Which revision and CMake configuration did you you use?

I would much rather work with your reproduce than with SNAP, but I need to make it fail first :)

Thank you,
-Andrzej

**Comment by PeixinQiao** [comment]
Thanks @banach-space .

I built this on my laptop at home. I will send these info to you later.

**Comment by banach-space** [comment]
Thanks! I don't see anything obviously different in your configuration that would affect this. 

We've continued discussing this in https://reviews.llvm.org/D128333  and it looks like we'll go ahead with that as a valid workaround. At least for now. Long term, we should add support for `-fpic`, `-fpic-level` and `-mrelocation-model` in Flang's frontend driver. And more specifically, refine how [TargetMachine](https://github.com/llvm/llvm-project/blob/be4b40d5bc6c1449090ff102e5f23254fd535cd4/llvm/include/llvm/Target/TargetMachine.h#L77) is [created in Flang](https://github.com/llvm/llvm-project/blob/be4b40d5bc6c1449090ff102e5f23254fd535cd4/flang/lib/Frontend/FrontendActions.cpp#L556-L559). Currently, we specified neither: 
* [Reloc::Model](https://github.com/llvm/llvm-project/blob/be4b40d5bc6c1449090ff102e5f23254fd535cd4/llvm/include/llvm/Support/CodeGen.h#L20-L23), nor
*  [CodeModel::Model](https://github.com/llvm/llvm-project/blob/be4b40d5bc6c1449090ff102e5f23254fd535cd4/llvm/include/llvm/Support/CodeGen.h#L26-L29)

Btw, what output do you get here:
```
$ flang-new -c conftestf.f90 
$ objdump -r conftestf.o | grep R_X86_64_32
0000000000000006 R_X86_64_32       .debug_abbrev
000000000000000c R_X86_64_32       .debug_str
0000000000000012 R_X86_64_32       .debug_str+0x0000000000000005
0000000000000016 R_X86_64_32       .debug_line
000000000000001a R_X86_64_32       .debug_str+0x000000000000000f
0000000000000039 R_X86_64_32       .debug_str+0x0000000000000011
000000000000003d R_X86_64_32       .debug_str+0x0000000000000011
0000000000000006 R_X86_64_32       .debug_info
0000000000000006 R_X86_64_32       .debug_info
```
?

-Andrzej

**Comment by PeixinQiao** [comment]
Here is the output on my laptop.
```
$ flang-new -c conftestf.f90 
$ objdump -r conftestf.o | grep R_X86_64_32
0000000000000002 R_X86_64_32       .bss
0000000000000007 R_X86_64_32       .bss+0x0000000000000001
0000000000000006 R_X86_64_32       .debug_abbrev
000000000000000c R_X86_64_32       .debug_str
0000000000000012 R_X86_64_32       .debug_str+0x0000000000000005
0000000000000016 R_X86_64_32       .debug_line
000000000000001a R_X86_64_32       .debug_str+0x000000000000000f
0000000000000039 R_X86_64_32       .debug_str+0x0000000000000011
000000000000003d R_X86_64_32       .debug_str+0x0000000000000011
0000000000000006 R_X86_64_32       .debug_info
0000000000000006 R_X86_64_32       .debug_info
```

**Comment by banach-space** [comment]
And what triple does `-###` show for you? It's `"-triple" "x86_64-unknown-linux-gnu"` in my set-up.

**Comment by PeixinQiao** [comment]
`"-fc1" "-triple" "x86_64-unknown-linux-gnu" "-emit-obj" "-fcolor-diagnostics" "-o" "/tmp/conftestf-6b82cd.o" "-x" "f95-cpp-input" "conftestf.f90"`

**Comment by PeixinQiao** [comment]
Thanks @banach-space . Built `flang-new` after git pull. Now the problem is solved.
