### ISSUE TITLE
[arith] Documentation out of date

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#56225]
The arith dialect only works on scalar types, but the dialect documentation still pervasively talks about tensors and vectors

```
def Arith_AddIOp : Arith_IntBinaryOp<"addi", [Commutative]> {
  let summary = "integer addition operation";
  let description = [{
    The `addi` operation takes two operands and returns one result, each of
    these is required to be the same type. This type may be an integer scalar
    type, a vector whose element type is integer, or a tensor of integers. It
    has no standard attributes.

    Example:

    ```mlir
    // Scalar addition.
    %a = arith.addi %b, %c : i64

    // SIMD vector element-wise addition, e.g. for Intel SSE.
    %f = arith.addi %g, %h : vector<4xi32>

    // Tensor element-wise addition.
    %x = arith.addi %y, %z : tensor<4x?xi8>
    ```
  }];
```

**Comment by jfurtek** [comment]
> The arith dialect only works on scalar types

Are you sure? The (passing) test below is from [ops.mlir](https://github.com/llvm/llvm-project/blob/main/mlir/test/Dialect/Arithmetic/ops.mlir), and the [ops](https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Dialect/Arithmetic/IR/ArithmeticOps.td) use `FloatLike` or `SignlessIntegerLike`, both of which are derived from `TypeOrContainer`, allowing vectors and tensors.

```
// CHECK-LABEL: test_addi_tensor
func.func @test_addi_tensor(%arg0 : tensor<8x8xi64>, %arg1 : tensor<8x8xi64>) -> tensor<8x8xi64> {
  %0 = arith.addi %arg0, %arg1 : tensor<8x8xi64>
  return %0 : tensor<8x8xi64>
}
```

**Comment by lattner** [comment]
yeah you're right I forgot about this, thanks!
