### ISSUE TITLE
getIntrinsicID() optimization

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5623]
|  |  |
| --- | --- |
| Bugzilla Link | [5251](https://llvm.org/bz5251) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [Initial implementation](https://user-images.githubusercontent.com/60944935/143740077-98b4c21a-abf6-46cd-a173-b0a682add053.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lattner |

## Extended Description 

The Function::getIntrinsicID() method is called all over the place, and in some use cases can take a significant amount of total compilation time. Each time it's called, it determines the intrinsic ID based on the function name. There's great opportunity for optimization by storing the ID for later use.

The attached patch is an implementation of the optimization which adds an intrinsicID field to the Function class and initialized it at construction time. However, extra fields are unwanted, and this implementation assumes the names of intrinsics do not change (though that assumption is already made in the constructor when initializing that argument attributes of intrinsics).

Possibly the SubclassData field could be used for storing the intrinsic ID...

**Comment by gwelymernans** [comment]
We now store the intrinsic ID as an integer for easy checking and access.
