### ISSUE TITLE
DirectX Backend: add intrinsic for DXIL operations.

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#56247]
For all DXIL operations which do not have existing llvm intrinsic, add target-specific intrinsic.

To make the convert to DXIL operation easier, the target-specific intrinsic should match DXIL operation signature if possible,

Handle will be added as i32 to work around intrinsic table gen cannot have struct parameter (it might because cannot match anonymous struct type).
When convert from intrinsic to DXIL operation, handle will be mutated into DXIL handle type.

**Comment by davidcook-msft** [comment]
This task is being subsumed by other tasks in the backlog.  Closing as redundant.
