### ISSUE TITLE
Assertion failure on AIX due to "2faacf61a50e [SLP]Improve shuffles cost estimation where possible"

### ISSUE THREAD

**Issue by orcguru** [llvm/llvm-project#56256]
opt -slp-vectorizer bugpoint-reduced-simplified.ll

opt: /home/tingwa/repo/public/llvm-project/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp:7744: llvm::Value *llvm::slpvectorizer::BoUpSLP::createBuildVector(ArrayRef<llvm::Value *>): Assertion `any_of(VectorizableTree, [VL](const std::unique_ptr<TreeEntry> &TE) { return TE->State == TreeEntry::NeedToGather && TE->isSame(VL); }) && "Non-matching gather node."' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.

[bugpoint-reduced-simplified.ll.txt](https://github.com/llvm/llvm-project/files/8996893/bugpoint-reduced-simplified.ll.txt)

**Comment by orcguru** [comment]
Confirmed https://reviews.llvm.org/D128680 will fix the crash

**Comment by alexey-bataev** [comment]
bf4dcbd2df009ba71d9032379fe8bc37ba0903ff
