### ISSUE TITLE
googletest-crash.py test is failing on Fedora 36

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#56252]
Full test log is here:

https://download.copr.fedorainfracloud.org/results/@fedora-llvm-team/llvm-snapshots/fedora-36-x86_64/04565366-llvm/builder-live.log.gz

It looks like there is an issue with matching the escape character in the FILE variable.

**Comment by yuanfang-chen** [comment]
Just to confirm, does the test environment have two cores?

**Comment by tstellar** [comment]
@yuanfang-chen Yes, it's a 2-core machine: https://download.copr.fedorainfracloud.org/results/@fedora-llvm-team/llvm-snapshots/fedora-36-x86_64/04565366-llvm/hw_info.log.gz

**Comment by yuanfang-chen** [comment]
Thanks for the confirmation. Hopefully 14d3021c10d0853a3ae9931b610afca6d385201e could fix it.

**Comment by yuanfang-chen** [comment]
Fixed in 9d37895a71cb7f2ac. Thanks.
