### ISSUE TITLE
[libc++] std::to_chars precision loss for 80-bit long double

### ISSUE THREAD

**Issue by alvinhochun** [llvm/llvm-project#56261]
`std::to_char` in libc++ converts `long double` to `double`: https://github.com/llvm/llvm-project/blob/3c126d5fe468e703ee3eacfcfc3641879b4fb281/libcxx/src/charconv.cpp#L81-L83

Test shows libc++ `std::to_char` output being different from `printf`/`std::ostream`, and compared to libstdc++: https://godbolt.org/z/GsYfTTjq7

**Comment by mordante** [comment]
The original code was provided by Microsoft, on Windows `double` and `long double` have the same size.
It's on my todo list to improve this at some point, it's also listed at the status page.

https://libcxx.llvm.org/Status/Cxx17.html#note-p0067

**Comment by alvinhochun** [comment]
Before this gets implemented properly, would it be better to delete the `to_chars` overload for `long double` if it has a different size than `double`? Seems to me that having it produce the wrong result can do more harm than making it unavailable.

**Comment by JustAnotherHumanBeing** [comment]
And when will libc++ support `from_chars` for floating types?

**Comment by mordante** [comment]
> Before this gets implemented properly, would it be better to delete the `to_chars` overload for `long double` if it has a different size than `double`? Seems to me that having it produce the wrong result can do more harm than making it unavailable.

During review there were no objections and we already shipped this. So we can no longer remove it. There will be differences in some cases, but I'm not sure how often that happens in practice. I'm not even sure whether anybody still uses `long doubles`.

> And when will libc++ support `from_chars` for floating types?

It's on my todo list, however that list is rather long and this item doesn't have a high priority for me. So I don't expect to work on it this year. Maybe somebody else will pick it up before it's on the top of my list.

**Comment by mordante** [comment]
Since we typically don't use the bug tracker for not implemented features I'm closing this.

**Comment by WarrenWeckesser** [comment]
A very late "strong agree" with @alvinhochun's [comment](https://github.com/llvm/llvm-project/issues/56261#issuecomment-1183240614).  That silent cast to double is an annoying "gotcha".

> I'm not even sure whether anybody still uses long doubles.

The 80 bit extended precision long doubles aren't that useful.  But true IEEE float128 is available on some platforms, and *that* can be useful.
