### ISSUE TITLE
[clang-format] Continuation indent of requires-expression should be configurable

### ISSUE THREAD

**Issue by Vigilans** [llvm/llvm-project#56283]
In clang-13, a concept definition with requires-expression will be formatted like this:
```cpp
template <typename EnvT>
concept Env = requires(EnvT&& env) {
    { step(env) } -> std::convertible_to<int>;
};
```
But after commits in https://reviews.llvm.org/D113319, above code will be formatted to:
```cpp
template <typename EnvT>
concept Env = requires (EnvT&& env) {
                  { step(env) } -> std::convertible_to<int>;
              };
```
After some investigation, it reveals that the difference was rooted in following code:
https://github.com/llvm/llvm-project/blob/24d6cc688fb56eff1a5f2267c238855d048f9982/clang/lib/Format/ContinuationIndenter.cpp#L1399-L1400

It unconditionally sets the indentation to be aligned with `requires` keyword. After removing it and recompile clang-format, the code is formatted as what clang-13 does:
```cpp
template <typename EnvT>
concept Env = requires (EnvT&& env) {
    { step(env) } -> std::convertible_to<int>;
};
```
These two indentations are just different style preferences, therefore should be made configurable in `.clang-format` file.

@HazardyKnusperkeks

**Comment by HazardyKnusperkeks** [comment]
You are very welcome to add an option, I'll gladly review it. But my own time is very limited to work on this.

**Comment by PatriotRossii** [comment]
I'll work on it

**Comment by PatriotRossii** [comment]
Phabricator https://reviews.llvm.org/D129443

**Comment by rymiel** [comment]
I think this issue is assigned to the wrong person?

Also, the patch seems very close to the finish line, seems like it only has a few remaining nits? (If the original author can't, can someone (e.g me) give it the final push?)

**Comment by owenca** [comment]
@rymiel go ahead and re-assign it to yourself and commandeer the patch.
