### ISSUE TITLE
Visual Studio 2022 `lld-link: warning/error: ignoring unknown debug$S subsection kind 0xFF in file libucrt.lib`

### ISSUE THREAD

**Issue by FrancescElies** [llvm/llvm-project#56285]
Related to https://github.com/actions/virtual-environments/issues/5813  

## Problem 

We started seeing `lld-link: warning/error: ignoring unknown debug$S subsection kind 0xFF in file libucrt.lib` with newer windows-sdks in visual studio 2022 (this does not happen with vs2019)

Is the following a problem in windows-sdks with vs2022 or in lld-link?

`example.c`
```c

int main(int argc, char **argv) {
  return 0;
}
```

<details><summary>Invoke-CmdScript (click me)</summary>
<p>

```powershell

# https://stackoverflow.com/questions/41399692/running-a-build-script-after-calling-vcvarsall-bat-from-powershell
function Invoke-CmdScript {
  param(
    [String] $scriptName
  )
  $cmdLine = """$scriptName"" $args && set"
  & $Env:SystemRoot\system32\cmd.exe /c $cmdLine |
  select-string '^([^=]*)=(.*)$' | foreach-object {
    $varName = $_.Matches[0].Groups[1].Value
    $varValue = $_.Matches[0].Groups[2].Value
    set-item Env:$varName $varValue
  }
}
```

</p>
</details>

With a previous win-sdk version: `10.0.19041.0`
```powershell
Invoke-CmdScript "c:/Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 10.0.19041.0
clang -std=c99 --target=x86_64-pc-windows-msvc -fuse-ld=lld -O1 -g "-Wl,/WX,/errorlimit:5" example.c

# No link warnings or errors
```

With newer win-sdk version (WX made warnings errors)
```powershell
Invoke-CmdScript "c:/Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 10.0.22621.0
clang -std=c99 --target=x86_64-pc-windows-msvc -fuse-ld=lld -O1 -g "-Wl,/WX,/errorlimit:5" example.c

lld-link: error: ignoring unknown debug$S subsection kind 0xFF in file libucrt.lib(initialization.obj)
lld-link: error: ignoring unknown debug$S subsection kind 0xFF in file libucrt.lib(argv_data.obj)
lld-link: error: ignoring unknown debug$S subsection kind 0xFF in file libucrt.lib(ncommode.obj)
lld-link: error: ignoring unknown debug$S subsection kind 0xFF in file libucrt.lib(matherr.obj)
lld-link: error: ignoring unknown debug$S subsection kind 0xFF in file libucrt.lib(matherr.obj)
lld-link: error: too many errors emitted, stopping now (use /errorlimit:0 to see all errors)
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

```

### llvm version 
```
❯ clang -v
clang version 14.0.6
Target: x86_64-pc-windows-msvc
Thread model: posix
```

**Comment by rnk** [comment]
This suggests that Microsoft has added additional subsection kinds:
https://github.com/microsoft/microsoft-pdb/blob/master/include/cvinfo.h#L4579
The warning exists to detect if and when this happens, so it's working as intended. Ideally, we should try to loop in someone from Microsoft to advise on what to do with the new subsection.

+various others @zmodem  @ZequanWu @alanzhao1

**Comment by aganea** [comment]
Can @StephanTLavavej @gratianlup help here?

**Comment by StephanTLavavej** [comment]
@aganea I'm very unfamiliar with this area (as I work on the STL), but @rnk's link helped me find the latest enumerators in the internal repo. `DEBUG_S_XFGHASH_TYPE` is the `0xFF` and it's followed by `DEBUG_S_XFGHASH_VIRTUAL` with the next value `0x100`. This was added by internal [MSVC-PR-354509](https://devdiv.visualstudio.com/DevDiv/_git/msvc/pullrequest/354509) (obviously this link is of no use to you, but it might save an MSVC back-end dev from having to look it up).

I know less about XFG than I do about quantum mechanics, so that's all the info I can provide - but I'll mail the backend devs and ask if someone can comment here. Hope this helps!

**Comment by rnk** [comment]
Thanks! XFG appears to be for Xtended Flow Guard, so another security hardening technology similar to Control Flow Guard (CFG), which LLD does not yet implement. I think we should:
- add these enums
- add them to the switch
- ignore them until there is interest in XFG

It would be nice if LLD had a warning suppression infrastructure to allow users to suppress individual warnings if this comes up again in the future, but to date the whole idea has been that it's a linker, it shouldn't have warnings, only errors, so there is no infrastructure to leverage for that purpose.

In the absence of such functionality, I'm glad we have the warning, so I'd like to keep it so we find out about future debug subsection additions.

**Comment by tru** [comment]
Posted a diff here: https://reviews.llvm.org/D129378

I know it needs a test as well - but I couldn't find where other flags that are ignored was tested, so any pointers on how to test it similar to other things that are ignored it would be great.

**Comment by kuzminrobin** [comment]
I got an impression that linker (lld-link) warnings result in non-zero error code returned by the linker console application. This breaks some of our CI builds. 
If that's the case then consider returning zero in case of warnings (as opposed to errors).

**Comment by rnk** [comment]
@kuzminrobin The user has control of whether warnings should be errors via the /WX flag, which should do what you need.

**Comment by tru** [comment]
> I got an impression that linker (lld-link) warnings result in non-zero error code returned by the linker console application. This breaks some of our CI builds.
> If that's the case then consider returning zero in case of warnings (as opposed to errors).

There is no warning / error framework similar to what's there in clang where you can suppress certain warnings or errors. So everything is treated as an error.

I would support if someone wanted to add a framework for this to LLD. But it probably needs someone to step up to do the work and post a RFC to figure out the details with the rest of the community.

**Comment by kuzminrobin** [comment]
Looks like I was wrong. The exit code of `lld-link` corresponds to my expectations.
The exit code of `lld-link` is 0 in case of warnings (including with the flag `/WX:no` and without any flag).
The exit code of `lld-link` is 1 in case of errors (the warnings treated as errors with the `/WX` flag).
Sorry for troubling.

---
Looks like the problem with our CI build is related to the output to the `stderr`. If there is any output to `stderr` in `lld-link` (including warnings) then the CI build script treats that as failure. Investigating.
