### ISSUE TITLE
Trapping math for ARM64 .

### ISSUE THREAD

**Issue by UmeshKalappa0** [llvm/llvm-project#56281]
Mail thread From John and  raised this issue to track current status .
===========================================================================================
I'm currently working on AArch64 strict fp support (which is what's needed to enable -ftrapping-math).
There's a few patches currently in review:
https://reviews.llvm.org/D114946
https://reviews.llvm.org/D115352 (though I need to rebase this)
https://reviews.llvm.org/D115620 (needs some extra work to enable a currently xfailed test)

And I'm working on some other patches:
Miscellaneous fixes for vector instruction lowering
Model FPCR use in AArch64 instructions
Fixes related to GlobalISel (not strictly needed as GlobalISel falls back to default isel when it can't handle things)

Once all of the above is done I think that I can then mark AArch64 as supporting strict fp in clang, so that -ftrapping-math isn't ignored.

John
================================================================================

**Comment by EugeneZelenko** [comment]
@UmeshKalappa0: Could you please elaborate?
