### ISSUE TITLE
Inefficient code generation: bitwise AND of disjoint booleans from equal and bitwise AND may not be optimized to constant 0

### ISSUE THREAD

**Issue by pmor13** [llvm/llvm-project#56294]
`clang -O3` optimizes this code:
```c
_Bool f1(char x)
{
    _Bool b1 = x == 4;
    _Bool b2 = x & 3;
    return b1 & b2;
}
```
to:
```asm
f1:
        xor     eax, eax
        ret
```
However, `clang -O3` does not optimize this code:
```c
_Bool f1(char x)
{
    _Bool b1 = x == 2;
    _Bool b2 = x & 1;
    return b1 & b2;
}
```
```asm
f1:
        cmp     dil, 2
        sete    al
        and     al, dil
        ret
```
Why?

Note: the `&` `b1 & b2` is used intentionally. If `&&` is used, then `clang -O3` optimizes it to:
```asm
f1:
        xor     eax, eax
        ret
```
How it can be explained?

Extra: if `#define LOGIC_AND` is uncommitted [here](https://godbolt.org/z/j8YWeM47b), then the whole program transfers into a no-op. Courtesy of [Lundin](https://stackoverflow.com/users/584518/lundin).

**Comment by nikic** [comment]
IR test case: https://alive2.llvm.org/ce/z/qy4_Hc

**Comment by rotateright** [comment]
This seems likely to be fixed by changing an unusual canonicalization that converts 'trunc X to i1' into 'icmp ne (and X, 1), 0'.

Alternatively, we are missing narrowing transforms for bitwise logic ops when zexts are from different sizes:
https://alive2.llvm.org/ce/z/sYXMLA

**Comment by rotateright** [comment]
Should be fixed after:
b5a9361c90ca

But this example reveals several other potential missing transforms (DeMorgan with i1 + icmp, simplify based on range?), so it's possible that we still don't get optimal code for similar examples. If you still see problems, please do file another bug.
