### ISSUE TITLE
difference due to atoi folding on Darwin

### ISSUE THREAD

**Issue by msebor** [llvm/llvm-project#56293]
As discussed in [D128364](https://reviews.llvm.org/D128364#3618130), by relying on nonportable `strtol` behavior on the host, the `atoi` (and `strtol`) folders can introduce an observable difference between different targets or when cross-compiling.  The following test case passes successfully on Linux but will likely abort when cross-compiling for Darwin on Linux due to the first `atoi` call having been folded to zero (with no change to `errno`) while the second call having resulted in the Darwin implementation of the function setting `errno` to `EINVAL` as POSIX allows but doesn't require.  (I don't have access to Darwin to verify this is what happens but the test failures reported in [D128364](https://reviews.llvm.org/D128364#3618130) suggest this is the case.)
```c
#include <errno.h>
#include <stdlib.h>

char s[] = "";

int main(void)
{
  errno = 0;
  int i0 = atoi("");
  int e0 = errno;

  errno = 0;
  int i1 = atoi(s);
  int e1 = errno;

  if (i0 != i1 || e0 != e1)
    abort();
}
```

**Comment by efriedma-quic** [comment]
Is the idea here just to change the following from convertStrToNumber:

```
  if (errno)
    return nullptr;
```
to something like the following?
```
  if (errno || nptr.c_str() == End)
    return nullptr;
```

That seems reasonable.  (Alternatively, we could switch to using llvm::consumeSignedInteger.)

**Comment by msebor** [comment]
Fixed.
