### ISSUE TITLE
The inialization order of the the "static inline" data members vs CRT is not right

### ISSUE THREAD

**Issue by ujos** [llvm/llvm-project#56309]
It seems the initialization order of the `static inline` variables is not in line with C-Runtime initialization. 

```txt
clang version 14.0.4
Target: x86_64-w64-windows-gnu
Thread model: posix
```

When I compile and run the following code, it prints nothing. Apparently application crashes during the initialization of the `C1::f1` while printing to the `std::cout`

```cpp

// clang++ --std=c++17 2.cpp -o 2.exe

#include <iostream>

struct Field
{
    Field(char const* name) { std::cout << name << "\n"; }
};

struct C1 
{
    static inline const Field f1{"C1::f1"};
};

int main()
{
    std::cout << "Exit\n";
}
```

In case if I remove the body of the `Field::Field` constructor, code compiles and runs just fine.

In case if I convert `static inline` into `static`, code compiles and runs just fine.

```cpp
#include <iostream>

struct Field
{
    Field(char const* name) { std::cout << name << "\n"; }
};

struct C1 
{
    static const Field f1;
};

const Field C1::f1{"C1::f1"};

int main()
{
    std::cout << "Exit\n";
}
```

**Comment by MaskRay** [comment]
Invalid example. The dynamic initialization of listdc++ `__ioinit` is ordered. For `static inline const Field f1{"C1::f1"};`, the dynamic initialization of f1 is partially-ordered (inline non-template). According to C++ `[basic.start.dynamic]`, the two initializations are indeterminate. Clang chooses to initialize f1 before `__ioinit`, therefore a crash.

When the latter example is used, the dynamic initialization of f1 is ordered. `__ioinit` is sequenced before f1.

**Comment by ujos** [comment]
@MaskRay I hardly can understand the language they use in the C++ standard, but I believe you are right. 

From other side it means we cannot use any of STL classes inside the `static inline` variable constructor. I'm not sure that is what developers expect.
