### ISSUE TITLE
Inconsitency in task_state after enabling tasking in the serial team

### ISSUE THREAD

**Issue by mikaoP** [llvm/llvm-project#56307]
```cpp
#include <stdio.h>
#include <unistd.h>
#include <omp.h>

int main() {
    omp_event_handle_t evt;
    #pragma omp task detach(evt)
    {
        omp_fulfill_event(evt);
    }

    #pragma omp parallel num_threads(2)
    #pragma omp master
    {
        #pragma omp task
        printf("hello 1\n");
    }
    int a;
    #pragma omp parallel num_threads(3)
    #pragma omp master
    {
        #pragma omp task depend(out:a)
        printf("hello 2\n");
        #pragma omp task depend(in:a)
        printf("hello 3\n");
    }
}
```
The execution hangs after doing all printfs, and it only happens if the number of threads of the second parallel is greater that the first one.

This program (compiled as `clang -fopenmp t1.c`) enables tasking in the serial team because of creating a detached task. I've been debugging a bit and it seems that task_state stack is used. Without the detached task this data structure is not modified.

I not an expert of this part of the runtime, but I found some places that may be related with the problem: https://github.com/llvm/llvm-project/blob/main/openmp/runtime/src/kmp_runtime.cpp#L2142 and https://github.com/llvm/llvm-project/blob/main/openmp/runtime/src/kmp_runtime.cpp#L2620 **(1)**

The inconsistency I found is in https://github.com/llvm/llvm-project/blob/main/openmp/runtime/src/kmp_runtime.cpp#L5386
where the task_state of the new threads is modified. In a regular nested parallel region the value assigned to the new threads is the same as the value restored by the master thread. In this case this does not happen, since we're in the `level==0` and we assign the value of the master thread at this moment, but the restoring **(1)** happens after that.

**Comment by mikaoP** [comment]
I've found that https://github.com/llvm/llvm-project/commit/d3f2b94d97789590c101ea7e512588deec80c288 adds the `|| master_th->th.th_task_team` check in the if condition. This additional condition makes the difference between this example and the same example withou the detached task.

Removing `|| master_th->th.th_task_team`, the program runs successfully, but running without hot teams (like in https://github.com/llvm/llvm-project/issues/59190), the execution does not end.

**Comment by shiltian** [comment]
All the work threads (let's assume thread 0 is the primary thread, and thread 1 and 2 are work threads) are waiting at:
```
 __kmp_fork_barrier(gtid, KMP_GTID_DNE);
```
This barrier is hit after each work thread finishes their parallel region. Meanwhile the primary thread is waiting at
```
      kmp_flag_32<false, false> flag(
          RCAST(std::atomic<kmp_uint32> *,
                &task_team->tt.tt_unfinished_threads),
          0U);
      flag.wait(this_thr, TRUE USE_ITT_BUILD_ARG(itt_sync_obj));
```
That indicates that, the completion of the second parallel region doesn't trigger the decrement of `task_team->tt.tt_unfinished_thread`, such that the primary thread thought the work threads are still working, but apparently they have moved on.
