### ISSUE TITLE
`lld-link: error: /INFERASANLIBS is not allowed in .drectve` in Visual Studio 2022 but not in 2019 (when including c++ stl)

### ISSUE THREAD

**Issue by FrancescElies** [llvm/llvm-project#56300]
Related to #56285

## Problem

We are compiling and linking our program with ASAN under windows, among other flags we use`target=x86_64-pc-windows-msvc` and `-fuse-ld=lld`, the rest of the flags we still need figure out if they relevant.

We are seeing the following lld-link error on machines with _visual studio 20022_, for the following windows-sdks:
 - 10.0.17763.0
 - 10.0.19041.0
 - 10.0.20348.0
 - 10.0.22000.0

```console
lld-link: error: /INFERASANLIBS is not allowed in .drectve
```

On a machines with _Visual Studio 2019_ and the same _windows-sdks_ _lld-link_ works fine and throws no errors.

## Reprex (vs2022)
```c++
// Compile it as follows:
//  clang++ --target=x86_64-pc-windows-msvc -fuse-ld=lld -v -O2 -fsanitize=address   .\example.cpp
//
// Do as follows to analyze the object file and see .drectve section
//  clang++ --target=x86_64-pc-windows-msvc -fuse-ld=lld -v -O2 -fsanitize=address   -c .\example.cpp -o example.opp
//
//
#include <stdlib.h>  // malloc free
#include <string.h>  // memset
// As soon as you include something from stl, e.g. vector you get the
// /INFERASANLIBS in the .drectve section
//
// As soon as you remove the vector include the .drectve section will
// disapear and lld will work fine again
#include <vector>

int main(int argc, char **argv) {
    (void)(argv);
    char *x = (char*)malloc(10 * sizeof(char));
    memset(x, 0, 10);
    int res = x[argc * 10];  // Boom!

    free(x);
    return res;
}
```

### llvm version 
```console
❯ clang -v
clang version 14.0.6
Target: x86_64-pc-windows-msvc
Thread model: posix
```

**Comment by FrancescElies** [comment]
In one of the problematic object files I could find `/INFERASANLIBS ` still not clear to me how this landed here.

```
3150 0x00054a0f 0x00054a0f 608 609 (.drectve-1066) ascii  /FAILIFMISMATCH:"_CRT_STDIO_ISO_WIDE_SPECIFIERS=0" /FAILIFMISMATCH:"_MSC_VER=1900" /FAILIFMISMATCH:"_ITERATOR_DEBUG_LEVEL=0" /FAILIFMISMATCH:"RuntimeLibrary=MT_StaticRelease" /DEFAULTLIB:libcpmt.lib /INFERASANLIBS /DEFAULTLIB:stl_asan.lib /FAILIFMISMATCH:"annotate_vector=1" /alternatename:__sanitizer_annotate_contiguous_container=__sanitizer_annotate_contiguous_container_default /alternatename:_Asan_vector_should_annotate=_Asan_vector_should_annotate_default /INCLUDE:"?id@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@2V0locale@2@A" /INCLUDE:"?id@?$numpunct@D@std@@2V0locale@2@A"
7589 0x000b13bb 0x000b13bb   8   9 () ascii .drectve
```

**Comment by FrancescElies** [comment]
In general I think it would be great to show which file had a problem with `.drectve`

```diff
diff --git a/lld/COFF/Driver.cpp b/lld/COFF/Driver.cpp
index 1546291e16c6..830e9e31b410 100644
--- a/lld/COFF/Driver.cpp
+++ b/lld/COFF/Driver.cpp
@@ -410,7 +410,7 @@ void LinkerDriver::parseDirectives(InputFile *file) {
     case OPT_throwingnew:
       break;
     default:
-      error(arg->getSpelling() + " is not allowed in .drectve");
+      error(arg->getSpelling() + " is not allowed in .drectve (" + toString(file) +")");
     }
   }
 }
-- 
2.36.1.vfs.0.0

```

**Comment by FrancescElies** [comment]
I updated the issue description with a reprex.

**Comment by FrancescElies** [comment]
I hope it's fine I ping you @StephanTLavavej but I couldn't avoid reading in #56285 that you work on the STL.

Maybe you could tell on why the following section appears under vs2022 when including something from the STL with ASAN but it doesn't under vs2019.

```
3150 0x00054a0f 0x00054a0f 608 609 (.drectve-1066) ascii  /FAILIFMISMATCH:"_CRT_STDIO_ISO_WIDE_SPECIFIERS=0" /FAILIFMISMATCH:"_MSC_VER=1900" /FAILIFMISMATCH:"_ITERATOR_DEBUG_LEVEL=0" /FAILIFMISMATCH:"RuntimeLibrary=MT_StaticRelease" /DEFAULTLIB:libcpmt.lib /INFERASANLIBS /DEFAULTLIB:stl_asan.lib /FAILIFMISMATCH:"annotate_vector=1" /alternatename:__sanitizer_annotate_contiguous_container=__sanitizer_annotate_contiguous_container_default /alternatename:_Asan_vector_should_annotate=_Asan_vector_should_annotate_default /INCLUDE:"?id@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@2V0locale@2@A" /INCLUDE:"?id@?$numpunct@D@std@@2V0locale@2@A"
```

**Comment by miscco** [comment]
I believe I am one of the culprits.

We enabled ASAN support for std::vector and std::string recently. I am less knowledgable about the build system magic, but afaik this is meant to enable asan support when we detected clang as the compiler.

https://github.com/microsoft/STL/blob/main/stl/inc/vector#L429-L447

**Comment by abgeana** [comment]
I incidentally ran into the same problem as OP and landed on this thread. 

> We enabled ASAN support for std::vector and std::string recently. I am less knowledgable about the build system magic, but afaik this is meant to enable asan support when we detected clang as the co
> 
> https://github.com/microsoft/STL/blob/main/stl/inc/vector#L429-L447

Based on the link above, a temporary fix is to compile with the `_DISABLE_VECTOR_ANNOTATION` define, which addresses both the unsupported `/INFERASANLIBS` directive for lld and the `/FAILIFMISMATCH:annotate_vector=1` issue.

For extra pointers regarding what is going on, I also found this page

https://docs.microsoft.com/en-us/cpp/sanitizers/error-container-overflow?view=msvc-170

> In Visual Studio 2022 version 17.2 and later, the MSVC standard library (STL) is partially enlightened to understand the AddressSanitizer.

**Comment by christianbrugger** [comment]
@abgeana Thank you for the workaround. In Visual Studio 17.3.0 I had to define `_DISABLE_STRING_ANNOTATION` in addition to `_DISABLE_VECTOR_ANNOTATION` for this to work. It's part of the checks in xstring.

**Comment by norru** [comment]
Unfortunately the suggested workaround wasn't applicable for me as I'm not using MSVC's STL.

Is there a way to enforce `clang` to *not* produce that `/INFERASANLIBS` in `.drectve` at all? I'm ok with explicitly linking the .lib rather than let the linker guess.

**Comment by norru** [comment]
https://discourse.llvm.org/t/inferasanlibs-coff-directive/62458/2

**Comment by alvinhochun** [comment]
I submitted https://reviews.llvm.org/D149022 and https://reviews.llvm.org/D149023.

**Comment by alvinhochun** [comment]
Let's try backporting this?

/cherry-pick 9b15e9840f5073aa38939fbef1cb0c64dcc5f02f 8fa0cfeb61a12ad5ca7830a8228155de32aa7ab2

**Comment by farzonl** [comment]
It looks like this change made it into LLVM 16. However, I am seeing evidence that it is still an issue:

```bash
lld-link: error: /INFERASANLIBS is not allowed in .drectve
lld-link: error: could not open 'stl_asan.lib': no such file or directory
lld-link: error: /failifmismatch: mismatch detected for 'annotate_string':
```
<img width="400" alt="image" src="https://github.com/llvm/llvm-project/assets/1802579/b1f5703d-fc57-4f7f-8fb5-e6db6a373fed">

Does this change apply to windows arm64 as well?

**Comment by alvinhochun** [comment]
The backport happened after 16.0.3.
