### ISSUE TITLE
Missed oppurtunity to narrow sext byte load pattern

### ISSUE THREAD

**Issue by preames** [llvm/llvm-project#56321]
This is a performance opportunity noted when analyzing sqlite3. Filing this with reproduction instructions for the original observation and some analysis below, plan to follow up with reduced test cases when I have some time.

```console
$ clang -isystem $GNU_TOOLCHAIN_DIR/sysroot/usr/include/ --target=riscv64 -mllvm -riscv-v-vector-bits-min=256 -mllvm -scalable-vectorization=on -Xclang -target-feature -Xclang +v,+f,+m,+c,+d,+zba sqlite-autoconf-3380500/sqlite3.c -c -O2 -g
```

The amalgamation file is taken from the sqlite3 website.

Non optimal assembly observed:
```asm
	ld	a1, 152(sp)
	slli	a2, a1, 56
	srai	a1, a2, 56
```
This is extracting the low byte, and then sign extending it.

This assembly should look something like:
```asm
	lb	a1, 152(sp)
```
There's a second issue here as well.  Even if compiled with `zbb`, the sign extend shift sequence is not replaced with `sext.b`.  Not sure if this is specific to stack fills, or if this is a more general problem.

**Comment by topperc** [comment]
I'm not seeing any `srai xX, xY, 56` instructions with Zbb.

**Comment by preames** [comment]
> I'm not seeing any `srai xX, xY, 56` instructions with Zbb.
You sure?  I went back and double checked I was looking at an assembly file compiled with Zbb, and I still see the assembly as above.  My clang might be a couple days old, but that's the only thing I can think of which might cause a difference.

**Comment by topperc** [comment]
> > I'm not seeing any `srai xX, xY, 56` instructions with Zbb.
> > You sure?  I went back and double checked I was looking at an assembly file compiled with Zbb, and I still see the assembly as above.  My clang might be a couple days old, but that's the only thing I can think of which might cause a difference.

I double checked too. Do you see sext.b in other places? Does the srai 56 show up in many places with Zbb? What function is the example from?
