### ISSUE TITLE
[bug] clang miscompiles coroutine, resuming it from final suspend

### ISSUE THREAD

**Issue by jacobsa** [llvm/llvm-project#56329]
I believe I've found a bug in clang's implementation of symmetric coroutine control transfer ([P0913R0](https://wg21.link/P0913R0)). Under some conditions it seems like **clang will resume a coroutine after it hits its final suspend point, without anything in the program saying it should do so**.

---

Below is a program with a promise type that uses straightforward symmetric control transfer:

* The promise arranges for all coroutines to start out suspended at the initial suspend point.

* The promise supports `co_await`ing calls to other coroutines. It does this by suspending itself, storing its handle in the child to resume when the child is done, and then resuming the child. Later the child resumes the parent from its final suspend point.

* The promise also supports `co_await`ing a special marker type (`ResumeFromAwaitSuspend`) that causes `await_ready` to return false but then `await_suspend` to return the input handle, saying "I decided to resume after all".

* The promise doesn't support being resumed from its final suspend point. If this happens, it writes an error to stderr and then exits.

The program calls a coroutine (`Outer`) that `co_await`s a `ResumeFromAwaitSuspend` marker, and then calls and `co_await`s an inner coroutine that also awaits a `ResumeFromAwaitSuspend`. This seems to cause clang to miscompile, because `Why did we resume from final_suspend??` is printed and the program exits with code `1`.

```c++
#include <unistd.h>

#include <coroutine>
#include <iostream>

class Promise;

// An object that can be co_awaited, but we always resume immediately from
// await_suspend.
struct ResumeFromAwaitSuspend{};

struct Task {
  using promise_type = Promise;
  Promise& promise;
};

struct Promise {
  static std::coroutine_handle<Promise> GetHandle(Promise& promise) {
    return std::coroutine_handle<Promise>::from_promise(promise);
  }

  void unhandled_exception() {}
  Task get_return_object() { return Task{*this}; }
  void return_void() {}

  // Always suspend before starting the coroutine body. We actually run the body
  // when we are co_awaited.
  std::suspend_always initial_suspend() { return {}; }

  // We support awaiting tasks. We do so by configuring them to resume us when
  // they are finished, and then resuming them from their initial suspend.
  auto await_transform(Task&& task) {
    struct Awaiter {
      bool await_ready() { return false; }

      std::coroutine_handle<> await_suspend(
          const std::coroutine_handle<> handle) {
        // Tell the child to resume the parent once it finishes.
        child.resume_at_final_suspend = GetHandle(parent);

        // Run the child.
        return GetHandle(child);
      }

      void await_resume() {
        // The child is now at its final suspend point, and can be destroyed.
        return GetHandle(child).destroy();
      }

      Promise& parent;
      Promise& child;
    };

    return Awaiter{
        .parent = *this,
        .child = task.promise,
    };
  }

  // Make evaluation of `co_await ResumeFromAwaitSuspend{}` go through the
  // await_suspend path, but cause it to resume immediately by returning our own
  // handle to resume.
  auto await_transform(ResumeFromAwaitSuspend) {
    struct Awaiter {
      bool await_ready() { return false; }

      std::coroutine_handle<> await_suspend(const std::coroutine_handle<> h) {
        return h;
      }

      void await_resume() {}
    };

    return Awaiter{};
  }

  // Always suspend at the final suspend point, transferring control back to our
  // caller. We expect never to be resumed from the final suspend.
  auto final_suspend() noexcept {
    struct FinalSuspendAwaitable final {
      bool await_ready() noexcept { return false; }

      std::coroutine_handle<> await_suspend(std::coroutine_handle<>) noexcept {
        return promise.resume_at_final_suspend;
      }

      void await_resume() noexcept {
        std::cerr << "Why did we resume from final_suspend??\n";
        _exit(1);
      }

      Promise& promise;
    };

    return FinalSuspendAwaitable{.promise = *this};
  }

  // The handle we will resume once we hit final suspend.
  std::coroutine_handle<> resume_at_final_suspend;
};

static Task Inner() { co_await ResumeFromAwaitSuspend(); }

static Task Outer() {
  co_await ResumeFromAwaitSuspend();
  co_await Inner();
}

int main(int argc, char** argv) {
  // Call Outer and get a reference to its promise, which is suspended at the
  // initial suspend point.
  Promise& promise = Outer().promise;

  // Tell the promise to terminate the chain of resumptions with a no-op
  // coroutine once it's done.
  promise.resume_at_final_suspend = std::noop_coroutine();

  // Resume it from the initial suspend point.
  const std::coroutine_handle<> promise_handle = Promise::GetHandle(promise);
  promise_handle.resume();

  // The promise's coroutine is now suspended at its final suspend point. Clean
  // up after it.
  promise_handle.destroy();
}
```

---

I've verified this bug happens with clang built from `HEAD`, at `-01` but not `-O0`:

```console
> ./bin/clang++ --version
clang version 15.0.0 (https://github.com/llvm/llvm-project.git 91ab4d4231e5b7456d012776c5eeb69fa61ab994)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/google/home/jacobsa/clients/llvm-project/build/./bin

> ./bin/clang++ -std=c++20 -O0 ~/tmp/foo.cc
> ./a.out
> ./bin/clang++ -std=c++20 -O1 ~/tmp/foo.cc
> ./a.out 
Why did we resume from final_suspend??
```

This also reproduces in [Compiler Explorer](https://godbolt.org/z/Wjnb8Yh6E) with x86-64 clang 14.0.0.

**Comment by jacobsa** [comment]
@ChuanqiXu9 Here's another one for you if you're able to help. :-/

**Comment by ChuanqiXu9** [comment]
Yeah, this should be a bug indeed. I would try to take a look.

**Comment by jacobsa** [comment]
@ChuanqiXu9 I've run into this (or similar issues?) in a few different contexts over the last month; it seems to come up fairly frequently when writing code with good inlining opportunities. Do you have any thoughts on what might cause it or how it can be fixed?

**Comment by ChuanqiXu9** [comment]
> 

I just visited it briefly since my time are limited. The behavior looks like the coroutine at the final suspend point get resumed again. I have no idea about how to fix it properly now. But it looks like we could skip the example by making `await_transform(ResumeFromAwaitSuspend)` return `std::never_suspend{}`. I'm not sure if this works for more complex cases.

**Comment by ChuanqiXu9** [comment]
> Thanks for looking. Yeah, to be clear this is just a toy example. We don't want to return `std::never_suspend` because we need to wake the parent coroutine that is `co_await`ing the child finishing.

I mean `await_transform(ResumeFromAwaitSuspend)::Awaiter::await_ready()` return false directly. (Ignore this if this is not acceptable in your production codes.)

**Comment by jacobsa** [comment]
Oh I see. Yeah, this is just a contrived example that reproduces the bug.

**Comment by ChuanqiXu9** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/e190b7cc90ca5ee712ca3982bf476afa9e8acb3b

**Comment by jacobsa** [comment]
@ChuanqiXu9: excellent, thank you very much!
