### ISSUE TITLE
PowerPC LIT test broken by clang/test/C/drs/dr208.c

### ISSUE THREAD

**Issue by orcguru** [llvm/llvm-project#56325]
Seems the detail output depends on arch.

On ppc64le which has "-triple powerpc64le-linux-unknown" for example I saw:
call signext i32 @dr208_init(i32 noundef signext 2)

https://github.ibm.com/compiler/llvm-project/commit/cce06da1ecf789658551ca5f3b255c361f063abf#diff-73ab68f82ee53e63e7f8b4efd08552e1181ffa023da6f34ff600fbfcbee1f547

Do we need to narrow down the case on some particular arch?

**Comment by hubert-reinterpretcast** [comment]
> Do we need to narrow down the case on some particular arch?

There is another solution. For example in `clang/test/CodeGenCXX/builtins.cpp`:
```
  // CHECK: call {{signext i8|i8}} @memmove()
```
