### ISSUE TITLE
How to add CFLAGS and CXXFLAGS and LDFLAGS to file.cmake?

### ISSUE THREAD

**Issue by ZahraHeydari95** [llvm/llvm-project#56347]
I want to add some flags to the c and c++ compiler in the following file. How should I do this so as not to encounter an error?

FLAGS = `-O3 -g -fno-reorder-blocks-and-partition -Wl,--emit-relocs`

Please also mention the flags that need to be removed for these flags to work.

[file cmake in github](https://github.com/facebook/hhvm/blob/HHVM-3.30/CMake/HPHPCompiler.cmake)

please guide me.

thanks.

this file is `HPHPCompiler.cmake` from HHVM project.

**Comment by dtcxzyw** [comment]
Please pass `-DGENERAL_OPTIONS=<options>` to cmake.
Closed as it is not an issue related to llvm.
