### ISSUE TITLE
[ODS] Generated `getFooAttrName()` helpers are not static

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#56364]
For an operation that has attributes, ODS generates accessors like this:

```cpp
  static ::llvm::ArrayRef<::llvm::StringRef> getAttributeNames() {
    static ::llvm::StringRef attrNames[] = {::llvm::StringRef("function_type"), ::llvm::StringRef("foo")};
    return ::llvm::makeArrayRef(attrNames);
  }

  ::mlir::StringAttr getFunctionTypeAttrName() {
    return getAttributeNameForIndex(0);
  }

  static ::mlir::StringAttr getFunctionTypeAttrName(::mlir::OperationName name) {
    return getAttributeNameForIndex(name, 0);
  }

  ::mlir::StringAttr getFooAttrName() {
    return getAttributeNameForIndex(1);
  }

  static ::mlir::StringAttr getFooAttrName(::mlir::OperationName name) {
    return getAttributeNameForIndex(name, 1);
  }
```

The `getFunctionTypeAttrName` and `getFooAttrName` should be static so they can be used in build methods etc.

**Comment by River707** [comment]
build methods should be using the ones that take an OperationName, this provides a StringAttr that is in the OperationName. ODS generated build methods already do this.

**Comment by River707** [comment]
An example of how to do that would be: https://github.com/llvm/llvm-project/blob/f9f40aa10d9862b8db1b99bb9e7f5898a90b35f7/mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp#L1752

**Comment by lattner** [comment]
Got it , thanks!
