### ISSUE TITLE
libc++: source_location not implemented

### ISSUE THREAD

**Issue by jgcodes2020** [llvm/llvm-project#56363]
Most of the implementation is trivial, and I'd like to submit a PR for it. However, there are two approaches to `std::source_location::current()`:
- `std::source_location::current()` has 4 default arguments set to `__builtin_FILE()`, etc.
- builtins are added that return the call site of the function that called `std::source_location::current()`

I'd like to see an answer from developers working on libc++ before I consider submitting.

**Comment by philnik777** [comment]
There is https://reviews.llvm.org/D120634 already. It will most likely be part of LLVM 15.
