### ISSUE TITLE
SLP vectorizer hit assert(Vec && "Can't find vectorizable value") when -mcpu=skylake

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#56375]
To repro,
opt.exe -mtriple=x86_64 -mcpu=skylake  -S -slp-vectorizer .\slp_assert_repro.ll.txt

[slp_assert_repro.ll.txt](https://github.com/llvm/llvm-project/files/9041594/slp_assert_repro.ll.txt)

**Comment by vfdff** [comment]
passes base on https://gcc.godbolt.org/z/sqK4j554M

**Comment by python3kgae** [comment]
Passed after sync update.
