### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by Xuefeng-2000** [llvm/llvm-project#56381]
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: llc -filetype=obj 458.sjeng.bc
 #0 0x0000000002e041cf PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x0000000002e0198d SignalHandler(int) Signals.cpp:0:0
 #2 0x00007ff929159390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
 #3 0x00007ff927e8d918 _IO_vfscanf /build/glibc-S7Ft5T/glibc-2.23/stdio-common/vfscanf.c:347:0
 #4 0x00007ff927e9c7e7 fscanf /build/glibc-S7Ft5T/glibc-2.23/stdio-common/fscanf.c:35:0
 #5 0x0000000001efd048 llvm::AsmPrinter::doFinalization(llvm::Module&) (/usr/local/bin/llc+0x1efd048)
 #6 0x00000000025f9667 llvm::FPPassManager::doFinalization(llvm::Module&) (/usr/local/bin/llc+0x25f9667)
 #7 0x0000000002604dfb llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/local/bin/llc+0x2604dfb)
 #8 0x00000000007f34b8 compileModule(char**, llvm::LLVMContext&) llc.cpp:0:0
 #9 0x000000000074aadf main (/usr/local/bin/llc+0x74aadf)
#10 0x00007ff927e52840 __libc_start_main /build/glibc-S7Ft5T/glibc-2.23/csu/../csu/libc-start.c:325:0
#11 0x00000000007e9f89 _start (/usr/local/bin/llc+0x7e9f89)
Segmentation fault (core dumped)

**Comment by fhahn** [comment]
Please provide the files and instructions to reproduce the issue. I am closing the issue for now. Let's re-open the issue once we have all info required to reproduce.
