### ISSUE TITLE
[CUDA] '-x cuda' option can only take effect when it appears before input file

### ISSUE THREAD

**Issue by Peter9606** [llvm/llvm-project#56408]
suppose we have a simplest cuda file, named `test.cc` like following:
```cpp
__global__ void t(char* o) {
    o[threadIdx.x] = 'a';
}
int main() {
    t<<<1, 1>>>(nullptr);
    return 0;
}
```

If we issue `clang++ -x cuda test.cc`, it will success, but if `clang++ test.cc -x cuda`, compiler will complain unrecognized language. Is this a bug or just as design ?

**Comment by Artem-B** [comment]
It works as intended.

E.g. if you run `clang -c -x c++ a.cc -x cuda a.cc -x c++ a.cc -###` you will see that a.cc is compiled as C++, then as CUDA then as C++ again.

**Comment by Peter9606** [comment]
Got it. Thanks for your replying.
