### ISSUE TITLE
clang format error

### ISSUE THREAD

**Issue by ddkwork** [llvm/llvm-project#56416]
clang-format -i --style=file C:\\Users\\Admin\\Desktop\\nvme\\ColdStorageManager-main\\NVMeQuery.dll \

return:

source (from CLion project)\\NVMeQuery.cpp
					from: The term 'from' is not recognized as a name of a cmdlet, function, script file, or executable program.
					Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by mkurdej** [comment]
Not sure I understand this report.
Do you run clang-format on a dll file?

Please be as clear as possible in the reproduce, output and expected result.
