### ISSUE TITLE
[AArch64] improve codegen for shifted mask op

### ISSUE THREAD

**Issue by rotateright** [llvm/llvm-project#56427]
During type legalization, we can end up with a mess of shifts and masks like this:
```ll
define i64 @src(i64 %x) {
  %s1 = lshr i64 %x, 31
  %a = and i64 %s1, 2147483647
  %s2 = shl i64 %a, 31
  ret i64 %s2
}
```

That's equivalent to a shifted mask op (and we do this transform in IR in InstCombine):
```ll
define i64 @tgt(i64 %x) {
  %a = and i64 %x, 4611686016279904256 ; 0x3fffffff80000000
  ret i64 %a
}
```

We also do that in DAGCombiner, but the general pattern is guarded by a TLI hook:
isDesirableToCommuteWithShift()
...and that is set to false for this case by AArch64.

But this example seems like it would be better with the transform because we can represent the mask constant as an immediate value:
`	and	x0, x0, #0x3fffffff80000000`

vs. current codegen:
```
	ubfx	x8, x0, #31, #31
	lsl	x0, x8, #31
```

Note: I noticed this while investigating a similar pattern for a different target's test diff in https://reviews.llvm.org/D77804

**Comment by bcl5980** [comment]
Candidate patch:
https://reviews.llvm.org/D136014

**Comment by bcl5980** [comment]
https://godbolt.org/z/8zqqz58rz
A better case opt can't optimize it.
