### ISSUE TITLE
llvm-g++: creates non-existing debuginfo line

### ISSUE THREAD

**Issue by edwintorok** [llvm/llvm-project#5642]
|  |  |
| --- | --- |
| Bugzilla Link | [5270](https://llvm.org/bz5270) |
| Version | trunk |
| OS | Linux |
| Attachments | [ary.i](https://user-images.githubusercontent.com/92601246/143740085-21d2ea89-c7cc-473c-a639-a9cc187fd9e8.gz) |

## Extended Description 
I wrote a new pass that tests debug info quality, and it found some errors when compiling the nightly test, for example:

while processing instruction   call void @&#8203;_ZNSt8ios_base4InitC1Ev(%"struct.__gnu_cxx::new_allocator<int>"* @&#8203;_ZStL8__ioinit), !dbg !&#8203;20
LLVM ERROR: dbgquality: line number 77 is out of range for file /home/edwin/llvm-svn/llvm-commit/projects/llvm-test/SingleSource/Benchmarks/Shootout-C++//ary3.cpp

That file only has 32 lines
define internal void @&#8203;_Z41__static_initialization_and_destruction_0ii(i32 %__initialize_p, i32 %__priority) {
...
call void @&#8203;_ZNSt8ios_base4InitC1Ev(%"struct.__gnu_cxx::new_allocator<int>"* @&#8203;_ZStL8__ioinit), !dbg !&#8203;1776
...
!&#8203;1776 = metadata !{i32 77, i32 0, metadata !&#8203;1771, null}

It looks like static initialization/destruction creates out-of-file lines.

**Comment by gwelymernans** [comment]
llvm-g++ and DragonEgg are gone. Long live Clang!
