### ISSUE TITLE
Documentation for "min-legal-vector-width" attribute typo.

### ISSUE THREAD

**Issue by zvookin** [llvm/llvm-project#56429]
In the Language Reference documentation for `min-legal-vector-width` it mentions "calling conversion" and likely means "calling convention."

```diff
--- a/llvm/docs/LangRef.rst
+++ b/llvm/docs/LangRef.rst
@@ -2230,7 +2230,7 @@ example:
     about the range of vscale.
 ``"min-legal-vector-width"="<size>"``
     This attribute indicates the minimum legal vector width required by the
-    calling conversion. It is the maximum width of vector arguments and
+    calling convention. It is the maximum width of vector arguments and
     returnings in the function and functions called by this function. Because
     all the vectors are supposed to be legal type for compatibility.
     Backends are free to ignore the attribute if they don't need to support
```

**Comment by zvookin** [comment]
@phoebewang Is this something you can weigh in on? Seems like a simple typo fix, but perhaps I am wrong.

**Comment by phoebewang** [comment]
Good eyes! Yes, it is a typo. Thanks! Do you have plan to fix it?

**Comment by zvookin** [comment]
I am not a committer on the project. I could make a PR I guess.

**Comment by phoebewang** [comment]
> I am not a committer on the project. I could make a PR I guess.

It's OK. I will fix it, just in case you have done that :)
