### ISSUE TITLE
OpenMP 5.0 target offloading: omp_alloc() undefined for nvlink

### ISSUE THREAD

**Issue by vincentadamthefirst** [llvm/llvm-project#56453]
I am currently trying to allocate memory on a target device in OpenMP offloading. For this I use a recently built Clang-15 and CUDA 11.6 (bundled with nvhpc 22.3).

A simple test program:

```c++
#include <omp.h>

int main() {
#pragma omp target teams distribute
    for (int index = 0; index < 100; index++) {
        float *shm = (float *) omp_alloc(20 * 20 * sizeof(float), omp_pteam_mem_alloc);

#pragma omp parallel num_threads(20 * 20) shared(shm) default(none)
        {
            int threadNum = omp_get_thread_num();
            shm[threadNum] = threadNum;
#pragma omp barrier
            // some work on shared memory & write-back
        }
    }
}
```

Compiled using
```bash
clang++ -O3 -std=c++17 -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda -fopenmp-version=51 --cuda-path=/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/cuda/11.6/ main.cpp
```

I expect a successful compilation but I get

```console
nvlink error   : Undefined reference to 'omp_alloc' in '/tmp/test-008605-nvptx64-nvidia-cuda-sm_80-400196.cubin'
/usr/local/bin/clang-linker-wrapper: error: 'nvlink' failed
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```

when it comes to the linking step. Am I missing something crucial? Is `omp_alloc()` not fully supported yet? (According to [the docs](https://clang.llvm.org/docs/OpenMPSupport.html#openmp-5-0-implementation-details) it should be). I have no problems when using the directives that more or less work the same (`#pragma omp allocate(shm) allocator(omp_pteam_mem_alloc)`)...

**Comment by jhuber6** [comment]
`omp_alloc` isn't implemented in the device runtime yet. Last I heard @shiltian was working on it. That being said, if you're trying to allocate a static amount of shared memory at compile time we do support that. Something like the following should be sufficient.
```c++
#include <omp.h>

int main() {
#pragma omp target teams distribute
    for (int index = 0; index < 100; index++) {
        float shm[20 * 20];
#pragma omp allocate(shm) allocator(omp_pteam_mem_alloc)

#pragma omp parallel num_threads(20 * 20) shared(shm) default(none)
        {
            int threadNum = omp_get_thread_num();
            shm[threadNum] = threadNum;
#pragma omp barrier
            // some work on shared memory & write-back
        }
    }
}
```
But for a region like this that shouldn't even be necessary, we have optimizations that should push it to shared memory automatically. If I compile this region without the explicit allocator and with `-Rpass=openmp-opt` it will indicate which optimizations we did for it.
```shell
<input>:4:1: remark: Transformed generic-mode kernel to SPMD-mode. [OMP120] [-Rpass=openmp-opt]
#pragma omp target teams distribute
^
<input>:6:11: remark: Replaced globalized variable with 1600 bytes of shared memory. [OMP111] [-Rpass=openmp-opt]
    float shm[20 * 20];
          ^
```

However, for the dynamic case it's a big more complicated. We do support some form of dynamic shared memory in OpenMP, but it requires calling a built-in function and using an environment variable see [the documentation](https://openmp.llvm.org//design/Runtimes.html#dynamic-shared-memory). We're currently planning on exposing this via `omp_alloc` as you've done above as well as setting the dynamic memory size per-kernel using an extension. But for now you'll need to use the interface in the documentation.

Let me know if this answered your question.

**Comment by vincentadamthefirst** [comment]
@jhuber6 Thank you very much for the answer and explanation! It is unfortunate, that `omp_alloc()` currently does not work but I can work with the automatic optimizations and directive-based control for now.

I will close this issue now.
