### ISSUE TITLE
error when define a move assignment = default (if using type alias)

### ISSUE THREAD

**Issue by TwinKleS-C** [llvm/llvm-project#56456]
For some reason, I used a type alias when defining the move constructor, which compiles successfully on MSVC and GCC, but Clang doesn't allow it
I tested other special member functions, copy constructor, move constructor, copy assignment function can all use the `= default` declaration explicitly in the case of using type alias, only move assignment function does not allow this, but it can use `= delete` explicitly, so is this a bug?
here is my test code

```cpp
// constant reference
template <typename T>
using RC = T const &;

// non-constant reference
template <typename T>
using RV = T &;

// r-value reference
template <typename T>
using RM = T&&;

struct A {

	// default constructor
	A () = default;
	// copy constructor
	A (RC<A>) = default;
	// move constructor
	A (RM<A>) = default;
	
	// copy assignment
	auto operator = (RC<A>) -> RV<A> = default;
	// move assignment
	auto operator = (RM<A>) -> RV<A> = default; // error: only special member functions may be defaulted
	//auto operator = (RM<A>) -> RV<A> = delete;  // OK
	
};

int main () {
	return 0;
}
```

**Comment by shafik** [comment]
Looks like this is failing in `Sema::SetDeclDefaulted`, in particular it looks like `Sema::getDefaultedFunctionKind` is not doing the right thing because `MD->isMoveAssignmentOperator()` comes back `false`.

Looking at `CXXMethodDecl::isCopyAssignmentOperator()` is does the following:

```cpp
  QualType ParamType = getParamDecl(0)->getType();
  if (const auto *Ref = ParamType->getAs<LValueReferenceType>())
    ParamType = Ref->getPointeeType();
```

while `CXXMethodDecl::isMoveAssignmentOperator()` does:

```cpp
 QualType ParamType = getParamDecl(0)->getType();
  if (!isa<RValueReferenceType>(ParamType))
    return false;
  ParamType = ParamType->getPointeeType();
```

If I modify `isMoveAssignmentOperator` to work like `isCopyAssignmentOperator` it seems to fix the issue but I need to make sure this passes `check-clang`.

**Comment by shafik** [comment]
That did not pass but modifying `CXXMethodDecl::isMoveAssignmentOperator()` this way does pass 'check-clang` cleanly:

```cpp
 QualType ParamType = getParamDecl(0)->getType();
  if (!ParamType->isRValueReferenceType())
    return false;
  ParamType = ParamType->getPointeeType();
```

**Comment by TwinKleS-C** [comment]
> That did not pass but modifying `CXXMethodDecl::isMoveAssignmentOperator()` this way does pass 'check-clang` cleanly:
> 
> ```c++
>  QualType ParamType = getParamDecl(0)->getType();
>   if (!ParamType->isRValueReferenceType())
>     return false;
>   ParamType = ParamType->getPointeeType();
> ```

ok, as you said it is working now, thanks for your reply

**Comment by shafik** [comment]
Apologies, I was not clear. I have not put in a fix yet just explaining the steps I have taken so far in looking into the problem. I still need to write some tests to cover this problem and post a PR for a fix. Once I have the PR I will post it to the bug.

**Comment by shafik** [comment]
PR: https://reviews.llvm.org/D129591

**Comment by TwinKleS-C** [comment]
> PR: https://reviews.llvm.org/D129591

ok❤️

**Comment by EugeneZelenko** [comment]
@TwinKleS-C: patch is not merged into `main` yet.
