### ISSUE TITLE
Regression on std::span

### ISSUE THREAD

**Issue by Arthapz** [llvm/llvm-project#56466]
Hi, LLVM 14 don't compile this code with libc++

```cpp
struct Foo {
     
};

static const auto foo = std::vector<Foo> {
    Foo{},
    Foo{},
    Foo{}
};

std::span<const Foo> bar() {
    return foo;
}

int main()
{
    auto b = bar();

    return 0;
}
```

it works with llvm13 and all other compilers
https://godbolt.org/z/5GGcdqfa8

**Comment by shafik** [comment]
It looks like this [works on clang trunk](https://godbolt.org/z/fhK5TjP38) so this looks like it is fixed already.
