### ISSUE TITLE
clang-tidy-14 'omp.h' file not found, but no issue using clang-tidy-10

### ISSUE THREAD

**Issue by Levi-Armstrong** [llvm/llvm-project#56460]
I am in the process of upgrading from clang-tidy-10 to clang-tidy-14 and ran into a clang-diagnostic-error saying 'omp.h' file not found. I am not sure how to resolve this issue when running clang-tidy. 

System: Ubuntu 20.04

**Comment by EugeneZelenko** [comment]
Could you please clarify how did you run Clang-tidy? Do you use compile database? What is Clang-tidy command line?

**Comment by Levi-Armstrong** [comment]
I am using cmake feature

``` cmake
set_target_properties(${target} PROPERTIES CXX_CLANG_TIDY clang-tidy-14)
```

**Comment by Levi-Armstrong** [comment]
I just tried clang-tidy-13 and it has the same issue and now try clang-tidy-12.

**Comment by Levi-Armstrong** [comment]
Current location of which my explain why it works for gcc and clang-tidy-10 but omp.h does not exist under any of the the other llvm-12,13, or 14 directories.

```
/usr/lib/gcc/x86_64-linux-gnu/8/include/omp.h
/usr/lib/gcc/x86_64-linux-gnu/9/include/omp.h
/usr/lib/llvm-10/include/openmp/omp.h
/usr/lib/llvm-10/lib/clang/10.0.0/include/omp.h
```

**Comment by bansan85** [comment]
On my Ubuntu server, I just had to install the package `libomp-14-dev`.

I confirm that `find_package(OpenMP REQUIRED)` / `target_link_libraries(${PROJECT_NAME} PUBLIC Eigen3::Eigen OpenMP::OpenMP_CXX)` / `make` worked well to build with gcc. I didn't tried with clang, our CI uses `gcc` to build and `clang-tidy` as static analyser.

**Comment by Levi-Armstrong** [comment]
I also don't have an issue with gcc, but I do have an issue with clang-tidy. I think the issue is because omp.h is not longer packaged with llvm in the newer versions from what I can tell.

**Comment by bansan85** [comment]
@Levi-Armstrong And does install `libomp-14-dev` solves the problem ?

**Comment by Levi-Armstrong** [comment]
Unfortunately I am unable to install libomp-14-dev because several things would be removed from my system.

**Comment by courros** [comment]
Installing libomp-14-dev on my system (ubuntu 22.04) worked well also with clang.

**Comment by Levi-Armstrong** [comment]
Okay, it sounds like that might be the issue.

**Comment by PiotrZSL** [comment]
External code issue, missing library.
