### ISSUE TITLE
C API type mismatch in ArrayType initializer

### ISSUE THREAD

**Issue by nektro** [llvm/llvm-project#56496]
https://github.com/llvm/llvm-project/blob/23d8eca/llvm/include/llvm/IR/DerivedTypes.h#L372-L373

https://github.com/llvm/llvm-project/blob/23d8eca/llvm/include/llvm-c/Core.h#L1429-L1437

C++ API use `uint64_t` and C API uses `unsigned` and thus gets truncated when trying to create larger `ArrayType`s

**Comment by nikic** [comment]
> Please excuse my ignorance: is it as simple as changing `unsigned` to `uint64_t` in Core.h and Core.cpp?
> 
> https://github.com/llvm/llvm-project/blob/d71a8ad/llvm/lib/IR/Core.cpp#L778-L780

No, that would be an ABI break. Instead LLVMArrayType2 with the new type would have to be added.
