### ISSUE TITLE
[Debug] Dwarf generated incomplete in some case 

### ISSUE THREAD

**Issue by Xinlong-Wu** [llvm/llvm-project#56522]
I try to build the [mold](https://github.com/rui314/mold) by [llvmorg-14.0.6](https://github.com/llvm/llvm-project/tree/llvmorg-14.0.6)

use command `make CXX=clang++ CC=clang CXXFLAGS="-g --gcc-toolchain=/path/to/toolchain/"`
The compilation process is working fine, but when I try to debug the mold using GDB, 
I got the error `Dwarf Error: DW_FORM_strx1 found in non-DWO CU`.

I try to use `gcc 11.0.0` to compile and then debug in same gdb, it works normally.

So I'm wondering where this might be a problem.

**Comment by dwblaikie** [comment]
The version of gdb you have is missing some dwarf-5 support. Either upgrade to a newer gdb with more complete support (I don't know which version got this fixed in) or compile with -gdwarf-4 to request clang use the older dwarf standard.
