### ISSUE TITLE
Add zstd support to utils/bazel

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#56521]
Link: https://discourse.llvm.org/t/rfc-zstandard-as-a-second-compression-method-to-llvm/63399

https://reviews.llvm.org/D128465 added the namespace `llvm::compression::zstd` and several functions. It can be used by 

* clang -gz=zstd
* lld --compress-debug-sections=zstd
* llvm-objcopy --compress-debug-sections=zstd
* clang ASTWriter
* `__llvm_prf_names`
* ...

We need Bazel support. `rg llvm_zlib util/bazel` can give some insight.

**Comment by MaskRay** [comment]
@aaronmondal will you be happy to take this issue as you just posted a similar patch for zlib (https://reviews.llvm.org/D143320) ? ☺️

**Comment by aaronmondal** [comment]
Ah cool I always wanted zstd support! I'm happy to take this one :+1:

**Comment by aaronmondal** [comment]
Revision at https://reviews.llvm.org/D143344.
