### ISSUE TITLE
[X86] Compiling specific AVX2 intrinsics leads to incorrect removal of a shuffle/broadcast in backend

### ISSUE THREAD

**Issue by Benjins** [llvm/llvm-project#56520]
This is a presumed miscompilation in the X86 backend that started occurring recently.

If we compile this IR:

```llvm
; Function Attrs: mustprogress nofree nosync nounwind readonly willreturn uwtable
define <2 x i64> @do_stuff(<16 x i8> %0) #0 {
  %2 = icmp eq <16 x i8> zeroinitializer, %0
  %3 = extractelement <16 x i1> %2, i64 0
  %4 = sext i1 %3 to i32
  %5 = insertelement <2 x i32> zeroinitializer, i32 %4, i64 0
  %6 = zext <2 x i32> %5 to <2 x i64>
  %7 = shufflevector <2 x i64> %6, <2 x i64> zeroinitializer, <2 x i32> zeroinitializer
  ret <2 x i64> %7
}

attributes #0 = { mustprogress nofree nosync nounwind readonly willreturn uwtable "frame-pointer"="none" "min-legal-vector-width"="128" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+avx,+avx2,+crc32,+cx8,+fxsr,+mmx,+popcnt,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+ssse3,+x87,+xsave" "tune-cpu"="generic" }
```

Before commit 72a23cef7e661997118a1c4876c814cfd05d72e4, this would compile to the following assembly:

```asm
      vpxor   xmm1, xmm1, xmm1
      vpcmpeqb        xmm0, xmm0, xmm1
      vmovd   eax, xmm0
      movsx   eax, al
      vmovd   xmm0, eax
      vpbroadcastq    xmm0, xmm0  ; <--- N.B: This line is missing in the trunk case
      ret
```

However, after that commit it produces the following:

```asm
      vpxor   xmm1, xmm1, xmm1
      vpcmpeqb        xmm0, xmm0, xmm1
      vmovd   eax, xmm0
      movsx   eax, al
      vmovd   xmm0, eax
      ret
```

Godbolt link (comparing trunk and 14.0.0): https://godbolt.org/z/Wdase3dM6

The lack of a broadcast means that the upper 64 bits of xmm0 are zero (in this case), instead of being a mirror of the lower half (should be 0xFFFFFFFF if 0 is passed to the function). This is due to undef values, but as far as I can tell there is no UB, because no undef values should be 'seen' by the computations.

A walkthrough of what's happening (apologies that this is somewhat involved, I'm not sure which part to focus on):

First, the IR is lowered to this DAG initially:

```console
SelectionDAG has 23 nodes:
  t0: ch = EntryToken
  t16: v2i64 = BUILD_VECTOR Constant:i64<0>, Constant:i64<0>
          t13: v2i32 = BUILD_VECTOR Constant:i32<0>, Constant:i32<0>
                t6: v16i8 = BUILD_VECTOR Constant:i8<0>, Constant:i8<0>, Constant:i8<0>, Constant:i8<0>, Constant:i8<0>, Constant:i8<0>, Constant:i8<0>, Constant:i8<0>, Constant:i8<0>, Constant:i8<0>, Constant:i8<0>, Constant:i8<0>, Constant:i8<0>, Constant:i8<0>, Constant:i8<0>, Constant:i8<0>
                  t2: i64,ch = CopyFromReg t0, Register:i64 %0
                t4: v16i8,ch = load<(load (s128))> t0, t2, undef:i64
              t8: v16i1 = setcc t6, t4, seteq:ch
            t10: i1 = extract_vector_elt t8, Constant:i64<0>
          t11: i32 = sign_extend t10
        t14: v2i32 = insert_vector_elt t13, t11, Constant:i64<0>
      t15: v2i64 = zero_extend t14
    t18: v2i64 = vector_shuffle<0,0> t15, undef:v2i64
  t21: ch,glue = CopyToReg t0, Register:v2i64 $xmm0, t18
  t22: ch = X86ISD::RET_FLAG t21, TargetConstant:i32<0>, Register:v2i64 $xmm0, t21:1
```

Part of the BeforeLegalizeTypes combine sees that we don't use the second element of t14 here:

```console
t14: v2i32 = insert_vector_elt t13, t11, Constant:i64<0>   ; <--- N.B. t13 is a zero literal
```

so it can be transformed into:

```console
t25: v2i32 = BUILD_VECTOR t11, undef:i32
```

Later, as part of the AfterLegalizeVectorOps combine, we are looking at this part of the DAG:

```console
        t38: v4i32 = BUILD_VECTOR t35, Constant:i32<0>, undef:i32, Constant:i32<0>
      t39: v2i64 = bitcast t38
    t18: v2i64 = vector_shuffle<0,0> t39, undef:v2i64
```

combineShuffleOfSplatVal wants to know if t39 is a splat vector. It thinks it is, because t35 ~ undef, and 0 ~ 0. Because of this, it removes the shuffle since it looks like all the elements are interchangeable.

Previously, we would reject this optimization because isSplatValue would be more strict in not allowing any undef in t38, instead of allowing partially undef elements. This is from this specific change in SelectionDag.cpp:

```cpp
UndefElts |= APIntOps::ScaleBitMask(SubUndefElts, NumElts, /*MatchAllBits=*/true); // N.B. MatchAllBits was effectively false before
```

So to summarise:

 1. An insert is changed to use an undef as the input vector instead of a zero'd one, since its second element is unused
 2. The bitcast vector is considered a splat, since the undef is placed such that it appears that all the elements of it are equivalent
 3. Partially undef elements are now allowed due to 72a23cef7e661997118a1c4876c814cfd05d72e4, and it is still considered a splat for optimization purposes

I'm not sure where the underlying issue is: all these steps seem reasonable to me at a cursory look, but they end up removing the broadcast, which changes the semantics of the code.

Original C++ repro (minimised):

```cpp
// Compiled with -mavx2 -O1
__m128i do_stuff(__m128i I0, __m128i I1) {
	__m128i A = _mm_cmpeq_epi8(I1, I0);
	__m128i B = _mm_cvtepi8_epi32(A);

	int Scalar = _mm_cvtsi128_si32(B);

	__m128i NewVector = _mm_cvtsi32_si128(Scalar);
	__m128i ZextVector = _mm_cvtepu32_epi64(NewVector);
	__m128i DoubledZext = _mm_broadcastq_epi64(ZextVector);

	return DoubledZext;
}
```

Godbolt link (comparing trunk w/ 14.0.0): https://godbolt.org/z/M3exGheG8

I tested this on latest trunk (04419a5f55d7eebc2d2f3c9fb74d3a417b7964c1) and confirmed it's still present.

For context: this was found by a fuzzer to test SIMD codegen, it was not in manually-written code.

**Comment by phoebewang** [comment]
cc @xiangzh1

**Comment by xiangzh1** [comment]
I'll take a look a little late, thanks for remind.
@Benjins the https://github.com/llvm/llvm-project/commit/72a23cef7e661997118a1c4876c814cfd05d72e4 is fix another bug for 32 bit. The Undef values may generated at the middle of DAG optimization (Not directly show in IR).

**Comment by RKSimon** [comment]
@xiangzh1 Are you looking at this? The 15.x branch is very soon. Otherwise I think we're just going to put a temp fix that bails if we find any undefs in bitcasts during splat detection, and a more performant fix can be added later.
