### ISSUE TITLE
[IPSCCP] wrongly replaces result with zero constant

### ISSUE THREAD

**Issue by graham-yiu** [llvm/llvm-project#56533]
IPSCCP optimization somehow propagates constant zero as the program result, which is incorrect.

To reproduce: ``opt <reduct.ll -passes=ipsccp -S``
[reduc.tar.gz](https://github.com/llvm/llvm-project/files/9115531/reduc.tar.gz)

**Comment by nikic** [comment]
Alive thinks this transform is correct: https://alive2.llvm.org/ce/z/k4XsVo

**Comment by nikic** [comment]
Yes, the transform is correct. `icmp sle i32 %conv10, %conv11` where `%conv10` is `0` and `%conv11` is zext is always true, so `select i1 %cmp12, i32 %conv10, i32 %conv11` choses `%conv10` which is 0, so the value stays constant.

**Comment by graham-yiu** [comment]
@nikic Thanks.  I think the problem was the testcase was initializing acc to 0, instead of 0xFFFF.
