### ISSUE TITLE
[clang-tidy] bugprone-shared-ptr-array-mismatch unable to detect alias case

### ISSUE THREAD

**Issue by timxx** [llvm/llvm-project#56546]
When the type is alias with `using` or `typedef`, the `bugprone-shared-ptr-array-mismatch` check will not report array mismatch that really mismatch.
```c++
// report as expected
std::shared_ptr<char> sp1(new char[10]);

// but not the below one
using byte = char;
std::shared_ptr<byte> sp2(new byte[10]);
```

**Comment by timxx** [comment]
I try fixed the problem with following replacement:
original:
```C++
cxxNewExpr(isArray(), hasType(pointerType(pointee(equalsBoundNode(PointerTypeN)))))
```
fixed:
```C++
cxxNewExpr(isArray(), hasType(pointsTo(qualType(hasCanonicalType(equalsBoundNode(PointerTypeN))))))
```

which reference from `clang-tools-extra/clang-tidy/modernize/MakeSmartPtrCheck.cpp`.
I'm not sure is correct or not, but it seems works for the test cases. (I'm pretty new to clang internal LoL)

**Comment by mizvekov** [comment]
This was already fixed by https://reviews.llvm.org/D112374

It just got reverted because of LLDB issues, but I expect to reland it soon.

**Comment by PiotrZSL** [comment]
This issue can be closed.
Warning is correctly raised on main:
```
shared-ptr-array-mismatch.cpp.tmp.cpp:101:31: warning: shared pointer to non-array is initialized with array [bugprone-shared-ptr-array-mismatch]
    std::shared_ptr<byte> sp2(new byte[10]);
```
