### ISSUE TITLE
[AArch64] Suboptimal `memcmp(s1, s2, n) == 0` expansion

### ISSUE THREAD

**Issue by Kmeakin** [llvm/llvm-project#56543]
Calls to `memcmp(s1, s2, n) == 0` which require multiple loads+compares are expanded to suboptimal code which combines the results of multiple comparisons with `eor` and `orr`. The more efficient expansion uses `cmp` and `ccmp`:

# Example ([godbolt](https://godbolt.org/z/bocWhvrbe))
Input:
```c
bool src(uint8_t* s1, uint8_t* s2) { 
    return memcmp(s1, s2, 3) == 0; 
}
```

Compiler generated code:
```asm
ldrh    w8, [x0]
ldrh    w9, [x1]
ldrb    w10, [x0, #2]
ldrb    w11, [x1, #2]
eor     w8, w8, w9
eor     w9, w10, w11
orr     w8, w8, w9
cmp     w8, #0
cset    w0, eq
ret
```

Handwritten code:
```asm
ldrh    w8, [x0]
ldrh    w9, [x1]
ldrb    w10, [x0, #2]
ldrb    w11, [x1, #2]
cmp     w8, w9
ccmp    w10, w11, #0, eq
cset    w0, eq
ret
```

**Comment by bcl5980** [comment]
Candidate Patch:
https://reviews.llvm.org/D136672

**Comment by vfdff** [comment]
I think this is fixed as now both of function **src** and **tgt** have same assemble with the **Handwritten code** above.
https://godbolt.org/z/cfTWdsorY
