### ISSUE TITLE
C# formatter fails with multi-line lambda in constructor

### ISSUE THREAD

**Issue by 3geek14** [llvm/llvm-project#56549]
Using clang-format to format C# files, I'm getting a weird error where it removes some levels of indentation, causing the file to end with several vertically-aligned `}`s.

Invocation:
```shell
path\to\clang-format.exe -style=LLVM Program.cs
```

Program.cs:
```cs
using System;
using System.Threading;

namespace MinimalWorkingExample {
  public class Program {
    public static void Main(string[] args) {
      var thread = new Thread(() =>
      {
        try
        {
          var x = 0;
        } catch {
          Console.WriteLine("This compiles.");
        }
      });
    }
  }
}
```
Console output:
```cs
using System;
using System.Threading;

namespace MyFirstProject {
public class Program {
  public static void Main(string[] args) {
      var thread = new Thread(() =>
      {
        try
        {
          var x = 0;
  }
  catch {
    Console.WriteLine("This compiles.");
  }
});
}
}
}
```

**Comment by PatriotRossii** [comment]
Smaller repro:

```
public void F() {
  var v = new C(() => {
    try {
    } catch {
      ;
    }
  });
}
```

Which formats to:

```
public void F() {
  var v = new C(() => {
    try {
    } catch {
      ;
}
});
}
```

**Comment by PatriotRossii** [comment]
I'll work on it

**Comment by PatriotRossii** [comment]
Phabricator: https://reviews.llvm.org/D129926

**Comment by 3geek14** [comment]
In Phabricator, this is marked as Accepted, does that mean it will be in one of the next patch updates?

**Comment by tru** [comment]
@PatriotRossii do you think it makes sense to backport this to 15.x? Is it a regression that should fixed?

**Comment by PatriotRossii** [comment]
> @PatriotRossii do you think it makes sense to backport this to 15.x? Is it a regression that should fixed?

I don't think so.

I don't see an urgent need in a backporting.

**Comment by 3geek14** [comment]
That's too bad. Even when passing `--lines` to clang-format, everything after the lambda in the file gets formatted to the wrong indentation level, which prevents my team from being able to use clang-format everywhere. (If there are multiple top-level blocks per file, I think subsequent blocks would not be broken by this, but we have a single top-level namespace per file.)

If this doesn't make it into 15.x, will it make it into 16.0? Building from source is still an option for us to have this fix, but we might delay adopting if we know a rough timeline for the fix getting into a release.

**Comment by tru** [comment]
It will definitely go into 16.x.
