### ISSUE TITLE
[bug?] The assumed type and derived type with kind parameter in Fortran 2003 intrinsic module procedure C_LOC

### ISSUE THREAD

**Issue by PeixinQiao** [llvm/llvm-project#56553]
As Fortran 2018 18.2.3.6, see the following:

Argument: X shall have either the POINTER or TARGET attribute. It shall not be a coindexed object. It shall
be a variable with interoperable type and kind type parameters, an assumed-type variable, or a nonpolymorphic
variable that has no length type parameter. If it is allocatable, it shall be allocated. If it is a pointer, it shall be
associated. If it is an array, it shall be contiguous and have nonzero size. It shall not be a zero-length string.

Should the assumed type and derived type with kind parameter be supported in LLVM Flang?

**Comment by PeixinQiao** [comment]
@klausler Is the current semantic error expected for the assumed type or derived type with kind parameter in `C_LOC`?

**Comment by klausler** [comment]
I don't understand your question.  Do you have a test case?

**Comment by PeixinQiao** [comment]
```
$ cat test.f90 
subroutine c_loc_test(typeStar)
  use iso_c_binding
  implicit none
  type(c_ptr) :: ptr
  type t (k)!, l)
    integer, KIND :: k = 4 ! Should this be allowed?
    !integer, LEN :: l = 10 ! Should this be allowed?
    integer :: i
  end type
  type(t), target :: p_i
  type(*), target :: typeStar
  ptr = c_loc(p_i)
  ptr = c_loc(typeStar)
end
$ gfortran test.f90 -c
$ flang-new -fc1 test.f90
error: Semantic errors in test.f90
./test.f90:12:15: error: Parameterized derived type argument requires an explicit interface
    ptr = c_loc(p_i)
                ^^^
./test.f90:13:15: error: Assumed type argument requires an explicit interface
    ptr = c_loc(typeStar)
                ^^^^^^^^
```
Here are two test cases for assumed type and parameterized derived type

**Comment by klausler** [comment]
This subroutine compiles with a compiler built from the current llvm-project/main; closing.
