### ISSUE TITLE
clang crashes for `decltype(co_await x)`

### ISSUE THREAD

**Issue by vogelsgesang** [llvm/llvm-project#56558]
Repro: https://godbolt.org/z/8dqrP5hnb

clang crashes for

```cpp
std::lazy<int> bar();

std::lazy<void> foo() {
    using X = decltype(co_await bar());
}
```

because it chokes on `decltype(co_await ...)`

**Comment by yuanfang-chen** [comment]
I guess we're missing tests for sized deallocation which is not the default at the moment.

https://godbolt.org/z/rfc6h3EY9

The assertion is in
#8 0x0000556f6ce79282 buildCoawaitCalls(clang::Sema&, clang::VarDecl*, clang::SourceLocation, clang::Expr*) SemaCoroutine.cpp:0:0

**Comment by vogelsgesang** [comment]
Note that the crash itself is not related to the sized deallocation.

Here is a repro of the crash without sized deallocations: https://godbolt.org/z/cc41qGoxf

**Comment by EugeneZelenko** [comment]
@ChuanqiXu9: Please file new issue and label it as `infrastructure`.
