### ISSUE TITLE
clang error when partial specialization with a single template parameter

### ISSUE THREAD

**Issue by twinkles-twinstar** [llvm/llvm-project#56556]
I define an adapter class Adapter and two template classes A<...>, B<...>, when I partially specialize Adapter for A and B, for some consideration, I use the requires clause instead of traditional way (like this: template \<typename T1\> struct Adapter\<A\<T1>> {...}), for example:
```cpp
// partial specialization for A<...>
template <typename TType> requires true
	&& IsTemplateInstanceOfT<TType, A> // ok if msvc/gcc, failed if clang
struct Adapter<TType> {
	static auto fun (
	) -> void {
		std::cout << "A" << std::endl;
		return;
	}
};
```
IsTemplateInstanceOfT<TType, A> is a concept to check TType is a A(class template)'s instance or not

I used msvc, gcc, and clang to test this code. When I only partially specialize for A, all three can be successfully compiled, but if I perform partial specialization for A and B at the same time, both msvc and gcc can be successful. But clang doesn't allow this code, it tells me there are ambiguous partial specializations of 'Adapter<A<int>>' and 'Adapter<B<int>>'
```
y.cpp:59:2: error: ambiguous partial specializations of 'Adapter<A<int>>'
        Adapter<A<int>>::fun(); // print : A
        ^
y.cpp:34:8: note: partial specialization matches [with TType = A<int>]
struct Adapter<TType> {
       ^
y.cpp:46:8: note: partial specialization matches [with TType = A<int>]
struct Adapter<TType> {
       ^
1 error generated.
```

To circumvent this error, I need to use std::is_base_of to make clang allow my code, like this:
```cpp
// partial specialization for A<...>
template <typename TType> requires true
	&& std::is_base_of_v<A<typename TType::Value>, TType> // ok if msvc/gcc/clang
struct Adapter<TType> {
	static auto fun (
	) -> void {
		std::cout << "A" << std::endl;
		return;
	}
};
```
Is this a bug?

clang version:
```
Ubuntu clang version 15.0.0-++20220627042157+655dc02cb023-1~exp1~20220627042241.261
Target: x86_64-pc-linux-gnu
Thread model: posix
```

Here is the complete test code:
```cpp
#include <iostream>

// declare a value
template <typename It>
inline constexpr auto declare (
) -> It;

// check a type is template's instance or not
template <typename It, template <typename> typename Template>
concept IsTemplateInstanceOfT = requires {
	{ [] <typename T1> (Template<T1> &) {}(declare<It &>()) };
};

// class A
template <typename TValue>
struct A {
	using Value = TValue;
};

// class B
template <typename TValue>
struct B {
	using Value = TValue;
};

// template
template <typename TType>
struct Adapter;

// partial specialization for A<...>
template <typename TType> requires true
	&& IsTemplateInstanceOfT<TType, A> // ok if msvc/gcc, failed if clang
	//&& std::is_base_of_v<A<typename TType::Value>, TType> // ok if msvc/gcc/clang
struct Adapter<TType> {
	static auto fun (
	) -> void {
		std::cout << "A" << std::endl;
		return;
	}
};

// partial specialization for B<...>
template <typename TType> requires true
	&& IsTemplateInstanceOfT<TType, B> // ok if msvc/gcc, failed if clang
	//&& std::is_base_of_v<B<typename TType::Value>, TType> // ok if msvc/gcc/clang
struct Adapter<TType> {
	static auto fun (
	) -> void {
		std::cout << "B" << std::endl;
		return;
	}
};

// test
auto main (
) -> int {
	std::cout << "A<int> is A ? " << IsTemplateInstanceOfT<A<int>, A> << std::endl; // print : A<int> is A ? 1
	std::cout << "B<int> is A ? " << IsTemplateInstanceOfT<B<int>, A> << std::endl; // print : B<int> is A ? 0
	Adapter<A<int>>::fun(); // print : A
	Adapter<B<int>>::fun(); // print : B
	return 0;
}

```

**Comment by yuanfang-chen** [comment]
Reduced to
```cpp
// declare a value
template <typename It>
inline constexpr It declare ();

// check a type is template's instance or not
template <typename It, template <typename> typename Template>
concept C = requires {
	{ [] <typename T1> (Template<T1> &) {}(declare<It &>()) };
};

// class B
template <typename T>
struct B {};

// template
template <typename T>
struct Adapter;

template <C<B> T>
struct Adapter<T> {};

template struct Adapter<B<int>>;
```

**Comment by zyn0217** [comment]
I scratched the surface a bit and have just realized that this is another case of not currently handling unevaluated lambdas.

To be specific, let's look at @yuanfang-chen's reduced example. We'll be evaluating the (type) constraint expression (`C<B>`) for the class specialization `Adapter<T>` while we're at a ClassTemplatePartialSpecialization DC, which is dependent. This ends up rebuilding a call to a dependent lambda expression and breaking our assumption that the constraint evaluation could only work for independent expressions.

The previous fix for unevaluated lambdas, introduced by https://reviews.llvm.org/D121532, attempted to identify certain cases by checking the current DC, but unfortunately, that doesn't cover this issue which appears to fall into the similar logic mentioned by the comment, "DependencyKind below is wrong when substituting an unevaluated lambda inside of a function's parameter's type".

https://github.com/llvm/llvm-project/blob/d5c9d402f07e7448cd46870a59d981f582682548/clang/lib/Sema/TreeTransform.h#L13474-L13485

I'm unclear if we should follow the same approach to fix *this issue*, for example, checking if the current context is a RequiresExprBodyDecl additionally. D121532 also said that a better fix might be 

> "to inject some kind of transparent declaration with correctly computed dependency for function parameters, variable templates, etc."

@cor3ntin Could you please give some guidance/thoughts? How can we correctly compute the dependency by injecting declarations?
