### ISSUE TITLE
Unexpected behavior after using std::string(const char *, size_t) ctor and std::string::operator+(std::string)

### ISSUE THREAD

**Issue by grendell** [llvm/llvm-project#56561]
My use-case is dealing with a fixed-size string in a file which is padded with '\0's unless it's at max size, in which case there is no null terminator.  Here is the reduced test-case:
```c++
#include <iostream>
#include <string>

int main() {
    char a[] = { 'A', 'B', 'C', 'D', '\0', '\0', '\0', '\0', };
    std::string b(a, 8);
    std::string c = b + "EFG";

    std::cout << a << "\n";
    std::cout << b << "\n";
    std::cout << b.c_str() << "\n";
    std::cout << c << "\n";
    std::cout << c.c_str() << "\n";

    return 0;
}
```
Compiler command:
```
clang++ -std=c++98 string_bug.cpp -o string_bug
```
Please note:  this is reproducible on all std versions.

Output:
```
ABCD
ABCD
ABCD
ABCDEFG
ABCD
```
I would expect the last line to also read "ABCDEFG".

Reproduced on the following versions of clang:
```
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: arm64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
```
clang version 11.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

**Comment by shafik** [comment]
In the `std::cout << c.c_str() << "\n";` case when you call `c.c_str()` you are getting back a `const CharT *` and `cout` will output until the first null terminator.

In the `std::cout << c << "\n";` it will output the full string but the null terminators are unprintable. You can see this more clearly if you do something like this:

```cpp
   for (const auto &ch : c) {
        if (ch == '\0')
          std::cout << "\\0";
        else
          std::cout << ch;
    }
```

Also see godbolt: https://godbolt.org/z/8bWT6hEGY

and you will see the output is consistent across compilers.
