### ISSUE TITLE
Clang generates nonsensical code for "-fsanitize=bool"

### ISSUE THREAD

**Issue by torvalds** [llvm/llvm-project#56568]
This is actually causing problems for us in the kernel, because clang UBSAN ends up generating code that violates our object file sanity checks, calling out to invalid functions in critical code.

It seems to happen only for inline asm with flag output, but it may be that that just happens to be the only place in the kernel where the  sanity checks notice.

I've created a trivial test-case independent of the kernel:

```c
#include <stdbool.h>

#define unlikely(x) __builtin_expect(!!(x), 0)
/*
 * Silly saturating increment implementation.
 * Only really meant to show oddity with UBSAN and
 * inline asm with flag output.
 */
int test(unsigned int val)
{
        bool carry;
 
       /* Overflow if ZF bit set - inc doesn't affect CF */
        asm("incl %0"
                :"=r" (val), "=@ccz" (carry)
                :"0" (val));
        if (unlikely(carry))
                val = ~0;
        return val;
}
```

which should (and, with "-O2" but without "-fsanitize-bool" does), just result in

```asm
test:                           
        movl    %edi, %eax
        incl    %eax
        je      .LBB0_1
        retq
.LBB0_1:
        movl    $-1, %eax
        retq
```

but if you compile that with "-fsanitize-bool" you get this unholy mess:

```asm
test:
        pushq   %rbp
        pushq   %rbx
        pushq   %rax
        movl    %edi, %ebx
        xorl    %esi, %esi
        incl    %ebx
        sete    %bpl
        cmpb    $2, %bpl
        jae     .LBB0_1
        testb   %bpl, %bpl
        jne     .LBB0_3
.LBB0_4:
        movl    %ebx, %eax
        addq    $8, %rsp
        popq    %rbx
        popq    %rbp
        retq
.LBB0_1:
        movb    %bpl, %sil
        movl    $.L__unnamed_1, %edi
        callq   __ubsan_handle_load_invalid_value
        testb   %bpl, %bpl
        je      .LBB0_4
.LBB0_3:
        movl    $-1, %ebx
        jmp     .LBB0_4
```

where clang is literally generating a "undefined behavior test" of the result of the "sete" instruction.

Note that it was clang itself that generated that "sete". And note how "sete" is *defined* to set the result to 0/1. So the undefined test is entirely pointless, and results in problems when code like this runs in a context where function calls are not allowed, and our object file sanity checking tool is understandably unhappy.

**Comment by yuanfang-chen** [comment]
Inserting `__builtin_assume(Carry == 0 || Carry ==1);` does not help either. "-fsanitize=bool" probably should take advantage of compile-time predicate like this. And then mark inline asm flags output with `llvm.assume`.

**Comment by yuanfang-chen** [comment]
> Inserting `__builtin_assume(Carry == 0 || Carry ==1);` does not help either. "-fsanitize=bool" probably should take advantage of compile-time predicate like this. And then mark inline asm flags output with `llvm.assume`.

https://reviews.llvm.org/D129954

**Comment by nickdesaulniers** [comment]
Do we want to cherry-pick this to the clang-15 release?

**Comment by yuanfang-chen** [comment]
> Do we want to cherry-pick this to the clang-15 release?

Sounds good to me.

**Comment by nickdesaulniers** [comment]
Thanks again for the report; this is fixed in clang-16 and has been backported and will also ship in clang-15.
