### ISSUE TITLE
[lld-macho] Compact unwind assert linking swift

### ISSUE THREAD

**Issue by keith** [llvm/llvm-project#56570]
I'm hitting this assert: https://github.com/llvm/llvm-project/blob/6cbfffb3a3a98032f93bc1b686a9d6fe3d9b3d14/lld/MachO/UnwindInfoSection.cpp#L216

When linking [SwiftLint](https://github.com/realm/SwiftLint) with ld64.lld built from this commit https://github.com/llvm/llvm-project/commit/6cbfffb3a3a98032f93bc1b686a9d6fe3d9b3d14

Reproducer: https://drive.google.com/file/d/1T4z39yYozaisRDTmR0wfp29zkp10JzF9/view

**Comment by keith** [comment]
I didn't try to reduce this, but I can if this repro case isn't helpful enough

**Comment by int3** [comment]
https://reviews.llvm.org/D130208
