### ISSUE TITLE
Ask acknowledgement for backporting D119939 to llvm-14

### ISSUE THREAD

**Issue by littlewu2508** [llvm/llvm-project#56577]
I'm ROCm packages maintainer at Gentoo. The current llvm-14 release missed a small feature about gfx1030 target. I confirm that with 6655c5a6bb13a7db483d1eea6e1071972b13a62d fixes [rccl-rocm-5.1.3](https://github.com/ROCmSoftwarePlatform/rccl/releases/tag/rocm-5.1.3) compilation error on gfx1030 targets (see https://bugs.gentoo.org/851702#c15).

I know that there will be no backport  plan for llvm-14 stable releases, however I would like to backport it in Gentoo distribution sys-devel/llvm package, which need the author's acknowledgement @dpreobra .

Also ccing the maintainer of Gentoo llvm @mgorny .

**Comment by dpreobra** [comment]
> Also, while I'm packaging dev-libs/rccl-5.1.3 against rocm-5.1.3 (clang-14 based), I found a compilation error:
> lld: error: ld-temp.o <inline asm>:1:26: specified hardware register is not supported on this GPU 
> when compiling for gfx1030 target.
> After backporting https://reviews.llvm.org/D119939 to llvm, whis is resolved.

I confirm that the path should fix the issue.

**Comment by mgorny** [comment]
@dpreobra, thanks for the confirmation.

Since there are no plans for another 14.x release, I'm going to close this. I've already done the backport in Gentoo.
