### ISSUE TITLE
crash due to invalid eh-frame pointer addresses in TOT lld-macho 

### ISSUE THREAD

**Issue by oontvoo** [llvm/llvm-project#56576]
```
 ld64.lld: (__eh_frame+0x11): unexpected pointer encoding 0x1b
```

Still working on making a smaller repro - but recent changes caused a wide spread crash in our builds.
Recording it here so I dont forget ....

**Comment by oontvoo** [comment]
Simple repro :

```

.globl  _main
_main:
  retq

.section __TEXT,__eh_frame,coalesced,no_toc+strip_static_syms+live_support
EHFrame0:
 .balign 8
AAAA:
 .set Lset0,LECIE-LSCIE
 .long Lset0
LSCIE:
 .long 0
 .byte 1
 .ascii "zR\0"
 .byte 1
 .byte 1
 .byte 1
 .byte 1
 .byte 1
 .byte 1
 .byte 0x80+16, 1

 .balign 8
LECIE:

 .subsections_via_symbols

```

**Comment by int3** [comment]
Thanks for the repro, I'll dig into it soon. Just curious, how did you generate it -- did you pass some particular flags into clang?

**Comment by int3** [comment]
Hmm I see that the repro is manually constructing the `__eh_frame` instead of using the `.cfi_` directives...

**Comment by BertalanD** [comment]
I'm curious how you ended up with an object that uses an `sdata4` encoding. It looks like `LSDAEncoding` is always forced to `absptr` for Mach-O in `llvm/lib/CodeGen/TargetLoweringObjectFileImpl.cpp`. Could it maybe be that LLD mis-parses the CIE?

**Comment by int3** [comment]
> Thanks for the repro, I'll dig into it soon.

I think I'm gonna hold off on that until I understand how the repro was made / how representative that repro is of the actual code that MC / `ld -r` generates

**Comment by oontvoo** [comment]
This snippet comes from `https://github.com/libffi/libffi/tree/master/src/x86`
It didn't involve any `ld -r` or llvm-mc magic :)  Simply

**Comment by int3** [comment]
Oh I see. So there's actually a use case for EH frames not generated from CFI directives... sigh.

Is this libffi the cause of your internal build breakages too?

**Comment by oontvoo** [comment]
Yep!

**Comment by int3** [comment]
https://github.com/libffi/libffi/blob/master/src/x86/unix64.S only uses the 0x1b encoding though. And ld64's source doesn't seem to support the uleb encoding either. I'd assumed that your example over-simplified the libffi code... is there some other libffi file that uses 0x1?

**Comment by oontvoo** [comment]
closing again since the internal builds are good. Sorry for the noise!

**Comment by int3** [comment]
Np, glad it works!

Let's get this into 15.0 since libffi is probably quite widely used.

/cherry-pick 6c9f6812523a706c11a12e6cb4119b0cf67bbb21
