### ISSUE TITLE
error: exponent has no digits

### ISSUE THREAD

**Issue by liam-clink** [llvm/llvm-project#56578]
Compiling LLVM-14.0.6 using GCC 12.1.0 I get several errors compiling `math_utils.cpp` `sincosf_utils.h` `sincosf_data.cpp` which appear to be due to an inability to understand C++17 floats correctly

Error type 1:
```console
/home/liam/Downloads/llvm-project-14.0.6.src/libc/src/math/generic/math_utils.cpp:18:57: error: exponent has no digits
/home/liam/Downloads/llvm-project-14.0.6.src/libc/src/math/generic/math_utils.cpp:19:61: warning: use of C++17 hexadecimal floating constant
   19 | constexpr double XFlowValues<double>::MAY_UNDERFLOW_VALUE = 0x1.8p-538;
      |                                                             ^~~~~~
```
Error type 2:
```console
/home/liam/Downloads/llvm-project-14.0.6.src/libc/src/math/generic/math_utils.cpp:14:60: error: unable to find numeric literal operator ‘operator""f’
   14 | constexpr float XFlowValues<float>::UNDERFLOW_VALUE = 0x1p-95f;
      |                                                            ^~~
```

Pastebin: https://pastebin.com/M4dMGz1y

**Comment by lntue** [comment]
The problem was fixed by enable C++17 by default for the libc project with https://reviews.llvm.org/rG700aebaf745f8b0a7c514ca452de1f60779816a1

**Comment by liam-clink** [comment]
So to clarify, add this to the commands list if this error is encountered?
`CMAKE_CXX_STANDARD 17`

**Comment by lntue** [comment]
@liam-clink : do you still encounter the problem that requires you to add `-DCMAKE_CXX_STANDARD=17` flag to your cmake commands?

**Comment by liam-clink** [comment]
Should I build 15.0.7 or the most recent commit to check? @lntue

**Comment by liam-clink** [comment]
Looks like 15.0.7 does not require that flag, so I will close this issue now
