### ISSUE TITLE
Designator inlay hints from inside a macro are shown

### ISSUE THREAD

**Issue by Trass3r** [llvm/llvm-project#56588]
@sam-mccall after 6b50f2b I noticed this bad corner case:

![image](https://user-images.githubusercontent.com/404623/179491772-1df201c2-0f11-44ce-8911-9cb69d8ba0fc.png)

They come from inside the macro:

![image](https://user-images.githubusercontent.com/404623/179492826-6e5b8d57-5420-4882-bc15-e692b99ded31.png)

**Comment by sam-mccall** [comment]
Closing in favor of https://github.com/clangd/clangd/issues/1289
