### ISSUE TITLE
[SCEV] SCEV drops NSW for add 

### ISSUE THREAD

**Issue by ychen306** [llvm/llvm-project#56596]
I have the following code where SCEV drops `nsw` for the instruction `%add`. What am I missing? Is this intended or a bug?
```llvm
define void @foo(ptr %a, i32 noundef %i) local_unnamed_addr {
entry:
  br i1 true, label %if_true, label %if_false
if_true:
  %add = add nsw i32 %i, 1
  %idxprom3 = sext i32 %add to i64
  %arrayidx4 = getelementptr inbounds i32, ptr %a, i64 %idxprom3
  %i2 = load i32, ptr %arrayidx4, align 4
  ret void
if_false:
  ret void
}
```
If I run `opt -passes=print<scalar-evolution>` ([to reproduce](https://godbolt.org/z/Gezve8Gjo)), I get `(1 + %i)` instead of `(1 + %i)<nsw>`.

I get the desired  `nsw` flag if I remove the branches instead ([to reproduce](https://godbolt.org/z/q67fEvYG4)).
```llvm
; Function Attrs: argmemonly mustprogress nofree norecurse nosync nounwind ssp willreturn uwtable
define void @foo(ptr %a, i32 noundef %i) local_unnamed_addr {
entry:
;  br i1 true, label %if_true, label %if_false
;if_true:
  %add = add nsw i32 %i, 1
  %idxprom3 = sext i32 %add to i64
  %arrayidx4 = getelementptr inbounds i32, ptr %a, i64 %idxprom3
  %i2 = load i32, ptr %arrayidx4, align 4
  ret void
;if_false:
;  ret void
}
```

**Comment by nikic** [comment]
> The flag still gets dropped even in [case](https://godbolt.org/z/Tv3hE3jq5) where I place the add instruction in at a basic block that post-dominates the entry block (thus guaranteeing the instruction always executes regardless of the branch condition).
> 
> Is this case intended?

If it post-dominates the entry block and there no potentially throwing or diverging instructions (i.e. all instructions are guaranteed-to-transfer), then transferring flags could be legal. However, actually doing so is likely not feasible for compile-time reasons.
