### ISSUE TITLE
Missed optimizations even if asm has empty output and clobber lists

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#56597]
```c
int foo(int *x)
{
  *x=5;
  asm("# comment" : : );
  return *x + 42;
}
```

LLVM -O3

```asm
foo:                                    # @foo
        movl    $5, (%rdi)
        movl    (%rdi), %eax
        addl    $42, %eax
        retq

```

GCC -O3
```asm
foo:
        mov     DWORD PTR [rdi], 5
        mov     eax, 47
        ret
```

https://godbolt.org/z/8rzhKer8x

**Comment by topperc** [comment]
The inline asm block is being emitted with the "sideeffect" property. Is this a frontend problem?

**Comment by davidbolvansky** [comment]
Yeah it seems.

https://github.com/llvm/llvm-project/blob/main/clang/lib/CodeGen/CGStmt.cpp#L2681

`  bool HasSideEffect = S.isVolatile() || S.getNumOutputs() == 0;`

**Comment by nickdesaulniers** [comment]
https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html#Volatile:

> asm statements that have no output operands and asm goto statements, are implicitly volatile.

**Comment by davidbolvansky** [comment]
So looks like there is no simple fix

**Comment by nickdesaulniers** [comment]
The presence of `::` in the `asm` or lack thereof changes the behavior of GCC!  Remove them and you get the same codegen from either compilers. That looks like a GCC bug to me.

-EWONTFIX;
