### ISSUE TITLE
Bug in __hash_len_0_to_16, introduced when migrating from City64 to std::hash

### ISSUE THREAD

**Issue by renzibei** [llvm/llvm-project#56606]
On 64bit platform, libc++ use City64 hash as the hash function for bytes or string. There is a bug introduced  in ` __hash_len_0_to_16` when migrating from City64.

The original code in City64 is [here](https://github.com/google/cityhash/blob/00b9287e8c1255b5922ef90e304d5287361b2c2a/src/city.cc#L128). And llvm libc++ code is [here](https://github.com/llvm/llvm-project/blob/c444f037878c61bcc750855c6edbcdac8f0871a5/libcxx/include/__functional/hash.h#L135).  By comparison, it can be seen that the original code in City64 `uint64 a = Fetch32(s);` was changed to `const uint32_t __a = __loadword<uint32_t>(__s);` by mistaken. This change drops 3 bits of information in the following use of `a` or `__a` 
```h
return __hash_len_16(__len + (__a << 3), __b);
```

This mistake caused a problem: The 3 bits from positions 29 to 31 of any string of length 4 to 8 bytes are ignored. The following minimal code shows this problem. In this code, the 8 strings of length 8 differ by only 3 bits, but they all have the same hash value.

```cpp
#include <iostream>
#include <unordered_map>
#include <functional>
#include <string>
#include <sstream>
#include <iomanip>
#include <vector>

std::string ToHex(const std::string& s)
{
    std::stringstream ret;

    for (char ch : s) {
        ret << std::hex << std::setfill('0') << std::setw(2) << uint32_t(uint8_t(ch)) << " ";
    }
    return ret.str();
}

int main() {
    constexpr uint32_t offset = 29;
    uint64_t mask = ~(7ULL << offset);
    uint64_t underlying_bits = UINT64_MAX & mask;
    auto hasher = std::hash<std::string>{};
    std::unordered_map<size_t, std::vector<std::string>> hash_value_count_map;
    for (uint64_t change_part = 0; change_part < 8; ++change_part) {
        uint64_t new_key = underlying_bits | (change_part << offset);
        std::string str_key = std::string(8, 0);
        memcpy(str_key.data(), &new_key, 8);
        size_t hash_value = hasher(str_key);
        hash_value_count_map[hash_value].push_back(str_key);
    }
    for (const auto& [hash_value, str_vec]: hash_value_count_map) {
        std::cout << str_vec.size() << " keys have the same hash value " <<
            hash_value << ":\n";
        for (const std::string& str_key: str_vec) {
            std::cout << ToHex(str_key) << "\n";
        }
    }
    return 0;
}

```

Compiled with `-std=c++17` flag, and run on little endian cpu, the output would be
```console
8 keys have the same hash value 13475952360111484157:
ff ff ff 1f ff ff ff ff
ff ff ff 3f ff ff ff ff
ff ff ff 5f ff ff ff ff
ff ff ff 7f ff ff ff ff
ff ff ff 9f ff ff ff ff
ff ff ff bf ff ff ff ff
ff ff ff df ff ff ff ff
ff ff ff ff ff ff ff ff
```
I test this code with compiler `Homebrew clang version 14.0.6` on macOS 12.4 arm64.

The fix can be assigned to me if needed. 

In addition, the City64 part was introduced before Oct. 2012. There are some new commits between 2012 and 2013 in City64 which change a lot of the codes and enhace the hash quality. e.g. [0469694b4609253742bcd3008c0b3f3ba9fcd9ba](https://github.com/google/cityhash/commit/0469694b4609253742bcd3008c0b3f3ba9fcd9ba). I think we can migrate these new improvements in. Of course, CityHash64 has stopped updating since 2013 though.

**Comment by oToToT** [comment]
A proposed patch: https://reviews.llvm.org/D134124

**Comment by philnik777** [comment]
The patch has been landed.
