### ISSUE TITLE
Clang MSVC and GNU C mode error: redefinition of 'index' as different kind of symbol

### ISSUE THREAD

**Issue by zufuliu** [llvm/llvm-project#56607]
for following C code (see https://godbolt.org/z/rc1bzrY3s, related to issue #16513):
```c
int index;

int get(void) {
	return index;
}
```

clang `-std=gnu99` emits an error:
```
<source>:1:5: error: redefinition of 'index' as different kind of symbol
int index;
    ^
<source>:1:5: note: unguarded header; consider using #ifdef guards or #pragma once
<source>:1:5: note: previous definition is here
<source>:4:9: warning: incompatible pointer to integer conversion returning 'char *(const char *, int)' from a function with result type 'int' [-Wint-conversion]
        return index;
               ^~~~~
1 warning and 1 error generated.
```
however `-std=gnu2x` is OK.

while gcc `-std=gnu99` emits a warning (also in `-std=gnu2x` mode):
```
<source>:1:5: warning: built-in function 'index' declared as non-function [-Wbuiltin-declaration-mismatch]
    1 | int index;
      |     ^~~~~
```

**Comment by zufuliu** [comment]
MSVC mode (`clang-cl`) has same behavior as in GNU C mode.

**Comment by AaronBallman** [comment]
The default C language mode for clang is `gnu17` not `c17`. GNU mode defines more builtin functions than just the ones from the standard, and that includes the very unfortunately named `index` function: https://pubs.opengroup.org/onlinepubs/009604499/functions/index.html. So it's not a bug that `index` is predefined in GNU mode.

However, the `gnu2x` behavior does look like a bug to me. That should behave the same in terms of whether this builtin is predefined or not.

**Comment by zufuliu** [comment]
I think this should turn off for clang-cl driver/mode as MSVC cl.exe doesn't has this extension/error.

**Comment by AaronBallman** [comment]
> I think this should turn off for clang-cl driver/mode as MSVC cl.exe doesn't has this extension/error.

That might be reasonable as well, though I think that's a separate issue (it'd be helpful to file it as one because the review for that change is different than for fixing an obvious bug).

**Comment by AaronBallman** [comment]
I've fixed this on main for Clang 16, but I'm going to see if I can get it backported to 15.x via https://github.com/llvm/llvm-project/issues/58764.
