### ISSUE TITLE
Clang crash at "clang::CastExpr::CastConsistency() const: Assertion `!getType()->isBooleanType() && "unheralded conversion to bool"' failed."

### ISSUE THREAD

**Issue by ZequanWu** [llvm/llvm-project#56622]
Command:
```
$ clang -cc1 -std=c++17 wasm-import-wrapper-cache-4daad3.reduced.cpp
```
[wasm-import-wrapper-cache-4daad3.reduced.zip](https://github.com/llvm/llvm-project/files/9145328/wasm-import-wrapper-cache-4daad3.reduced.zip)

**Comment by shafik** [comment]
Possibly related to: https://github.com/llvm/llvm-project/issues/56560

**Comment by ZequanWu** [comment]
Duplicate.
