### ISSUE TITLE
git clang-format hangs

### ISSUE THREAD

**Issue by korDen** [llvm/llvm-project#56624]
The following C# code hangs clang-format:

```cs
namespace Foo;

public class Bar
{
    public string test()
    {
        return $@"Unsupported Endpoint ""/endpoint?f={Request.Query["f"]}""";
    }
}
```

When I abort, I consistently see the following error message:
```console
error: `git hash-object -w --path=<path to file> --stdin` failed
```

**Comment by korDen** [comment]
Surprisingly, it only hangs on one particular file. I'll see if I can track down what part of file is tripping it.

**Comment by owenca** [comment]
https://reviews.llvm.org/D130411
