### ISSUE TITLE
Create legal clarity around Apache license clause 4b

### ISSUE THREAD

**Issue by nhaehnle** [llvm/llvm-project#56648]
Clause 4b of the Apache license says:

> (4) You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:
>    …
>    (b) You must cause any modified files to carry prominent notices stating that You changed the files; and

While I am not a lawyer myself, here's my understanding of it based on how our corporate lawyers interpret this rule in general:

The normal pull request flow for a contributor on GitHub involves, as a first step, creating and distributing a modified copy of LLVM by uploading it to a personal fork on GitHub. This triggers clause 4b, which means that *files* need to carry prominent notices that the contributor made changes to them. For C++ sources this presumably means a note in the file's header stating the name of the contributor -- which goes against LLVM's current practice. Put the other way around, following our current conventions and GitHub's usual pull request process requires violating the Apache license under a very plausible interpretation, thus creating legal uncertainty for contributors.

There are any number of ways in which this could potentially be resolved:

1. Given that there are many Apache licensed projects out there, perhaps a clear legal statement from somewhere can be obtained that this is just not an issue (Apache Foundation? Relevant precedent somewhere?)
2. Perhaps the LLVM foundation could adjust the relicensing project to add an explicit exemption from this clause, or replace it entirely by a more flexible clause that still serves the same purpose (such as the GPL's "The **work** must carry prominent notices stating that you modified it, and giving a relevant date." -- since it talks about the work as a whole instead of individual files, this requirement would presumably be satisfied by Git history and probably even the context of a personal fork).
3. Perhaps if contributors were free to create branches in the main repository, or some other repository under the github.com/llvm umbrella, one might argue that it is the LLVM Foundation itself which distributes the modified copy and therefore clause 4b doesn't apply -- see https://github.com/llvm/llvm-project/issues/56643.
4. Other ideas?

**Comment by pogo59** [comment]
> Given that there are many Apache licensed projects out there, perhaps a clear legal statement from somewhere can be obtained that this is just not an issue (Apache Foundation? Relevant precedent somewhere?)

How does Apache itself handle this?  Do Apache contributors create branches/forks in order to create pull requests?

**Comment by h-vetinari** [comment]
> How does Apache itself handle this? Do Apache contributors create branches/forks in order to create pull requests?

Yes, the apache [org](https://github.com/apache/) is full of projects that use pull requests (incl. flagship projects like [spark](https://github.com/apache/spark), [kafka](https://github.com/apache/kafka), [flink](https://github.com/apache/flink), [hadoop](https://github.com/apache/hadoop), [airflow](https://github.com/apache/airflow), [arrow](https://github.com/apache/arrow), etc.)

**Comment by rnk** [comment]
I am not a lawyer, but this seems to depend on what you interpret as a "prominent notice". Git and GitHub go to great lengths to track and show who changed what when. A pull request is a pretty prominent way of highlighting to the world exactly what you have changed in your reproduction.

**Comment by tstellar** [comment]
This question has been answered here: https://discourse.llvm.org/t/board-meeting-minutes-may-2022/63628/6

**Comment by rengolin** [comment]
I believe this issue can now be closed.
