### ISSUE TITLE
APFloat optional/default valued parameter in Attrdef

### ISSUE THREAD

**Issue by bhatuzdaname** [llvm/llvm-project#56649]
Hi, I'm trying to create an Attrdef which has a default valued APFloatParameter field.
```
def optionalFloat : APFloatParameter<""> {
  let isOptional = 1;
  let defaultValue = "APFloat(3.0f)";
}

def MyStructAttr : AttrDef<My_Dialect, "StructHMM"> {
  let parameters = (ins optionalFloat:$foo);
  let mnemonic = "struct";
  let assemblyFormat = "`<` struct(params) `>`";
}
```

The problem is that in the generated printer/parser to check if the field exists, we simply generate if(getFoo()). This fails for APFloat as it cannot be implicitly converted to bool. Thinking about this, I am not sure if this is a good strategy even for ints/bools etc, as just because the value ==0, does not mean it is optional..

Errors:
```
 error: invalid argument type 'llvm::APFloat' to unary expression
        if (::mlir::succeeded(_result_foo) && !*_result_foo) {
...
 error: value of type '::llvm::APFloat' is not contextually convertible to 'bool'
    if ((getFoo()) && !(getFoo().bitwiseIsEqual(APFloat(3.0f))))) {
```

**Comment by bhatuzdaname** [comment]
@Mogball @River707

**Comment by Mogball** [comment]
You will want `Optional<APFloat>`

**Comment by bhatuzdaname** [comment]
Thank you!
