### ISSUE TITLE
Possible improvement for SimplifyDemandedBits for Mul

### ISSUE THREAD

**Issue by topperc** [llvm/llvm-project#56645]
If the RHS is a constant with X trailing zeros, then the X MSBs of the LHS are not demanded.

I don't have any plans to do anything with this right now. Just something I thought of while working on https://reviews.llvm.org/D130146 That patch does special isel for (i64 (mul (and X, 0xffffffff), 3 << C)) and requires C < 32. If C >= 32 the AND could be removed, but it doesn't happen today.

FYI @spatel-gh @RKSimon

**Comment by RKSimon** [comment]
I've been able to prove it if the upper bits of x are simplified to zero: https://alive2.llvm.org/ce/z/NLzMby

But I haven't yet managed to create a test that shows that the upper bits don't matter at all.

**Comment by topperc** [comment]
Modified your proof to force the bits to 1 instead of 0 and it also verifies https://alive2.llvm.org/ce/z/f5AL-u

**Comment by RKSimon** [comment]
This is the best I've managed: https://alive2.llvm.org/ce/z/F5CyJW

```
----------------------------------------
define i8 @src(i8 %x, i8 %y, i8 %garbage) {
#0:
  %yz = icmp ne i8 %y, 0
  assume i1 %yz
  %r = mul i8 %x, %y
  ret i8 %r
}
=>
define i8 @tgt(i8 %x, i8 %y, i8 %garbage) {
#0:
  %garbagef = freeze i8 %garbage
  %ytz = cttz i8 %y, 0
  %xm = lshr i8 255, %ytz
  %xmn = xor i8 255, %xm
  %garbagebits = and i8 %xmn, %garbagef
  %xx = or i8 %x, %garbagebits
  %r = mul i8 %xx, %y
  ret i8 %r
}
Transformation seems to be correct!
```
Basically, we can insert whatever we want to the upper bits of X and it should still work.
