### ISSUE TITLE
libclang `clang_getFieldDeclBitWidth` assumes the bit width expression is evaluable 

### ISSUE THREAD

**Issue by chbaker0** [llvm/llvm-project#56644]
[`clang_getFieldDeclBitWidth`](https://github.com/llvm/llvm-project/blob/f494f89b2a88f9de48781f43e7be2386809c7db5/clang/tools/libclang/CXType.cpp#L380) checks if the provided cursor is a bitfield declaration then proceeds to call [`FieldDecl::getBitWidthValue`](https://github.com/llvm/llvm-project/blob/f494f89b2a88f9de48781f43e7be2386809c7db5/clang/lib/AST/Decl.cpp#L4261) which in turn calls [`Expr::EvaluateKnownConstInt`](https://github.com/llvm/llvm-project/blob/f494f89b2a88f9de48781f43e7be2386809c7db5/clang/lib/AST/ExprConstant.cpp#L15222) on the bit width expression.

`EvaluateKnownConstInt` requires the expression not be dependent on any template parameters. However, `clang_getFieldDeclBitWidth` doesn't account for this, and libclang does not expose an obvious way to check if an expression's value depends on a template parameter.

https://github.com/rust-lang/rust-bindgen/issues/2239 is related

**Comment by rnk** [comment]
It looks like this API can return `-1` as a failure value, so this can be fixed with this condition:
      if (FD->isBitField() && FD->getBitWidth()->isValueDependent())
        return FD->getBitWidthValue(getCursorContext(C));

**Comment by chbaker0** [comment]
That's probably a good idea. We could have a separate API to check if the expr's value depends on a template parameter, or the clang_getFieldDeclBitWidth could return a separate error code for this condition. Which seems more reasonable?

**Comment by rnk** [comment]
I went looking through the API to try to find some existing higher level check for "is this AST node at all dependent on template parameters", but I couldn't find anything. I think this API already returns -1 in case of error, so it's better to make it return -1 to make the existing API safe. I think it also makes sense to add a simple boolean predicate that checks if a bitfield's width is non-dependent, so maybe something like `clang_Cursor_isNonDependentBitField`.

**Comment by vedgy** [comment]
This assertion failure makes KDevelop crash while parsing */usr/include/boost/container/string.hpp*: https://bugs.kde.org/show_bug.cgi?id=438249
