### ISSUE TITLE
std::codecvt<char8_t, wchar_t, std::mbstate_t> is not implemented in libc++

### ISSUE THREAD

**Issue by jcelerier** [llvm/llvm-project#56655]
Repro:

```cpp
#include <codecvt>
int x = sizeof(std::codecvt<char8_t, wchar_t, std::mbstate_t>);
```

causes

```console
<source>:4:9: error: implicit instantiation of undefined template 'std::codecvt<char8_t, wchar_t, __mbstate_t>'
int x = sizeof(std::codecvt<char8_t, wchar_t, std::mbstate_t>);
        ^
/opt/compiler-explorer/clang-trunk-20220721/bin/../include/c++/v1/__locale:952:85: note: template is declared here
template <class _InternT, class _ExternT, class _StateT> class _LIBCPP_TEMPLATE_VIS codecvt;
                                                                                    ^
1 error generated.
Compiler returned: 1
```

godbolt repro: https://gcc.godbolt.org/z/E6cEPcMzv

**Comment by jcelerier** [comment]
it's not *technically* standard but MSVC provides it and as such windows apps depend on it.. :[

**Comment by Febbe** [comment]
You can use the MSVC STL, it has the same license as libc++.
`std::codecvt<char8_t, char16_t, std::mbstate_t>` should have the same result on Windows and is standard conform and portable.

**Comment by jcelerier** [comment]
I'm using the same c++ library on all platform because I have been bitten multiple times by tiny differences with large consequences leading to different behaviour across macOS/Linux/Windows, such as different sorting implementation with different performance characteristics, different edge cases for e.g. regex, etc.

And I think in this case the issue was proprietary code outside my control

**Comment by Febbe** [comment]
It's very easy to add that in libc++, if you want to implement this, just check out, how other `std::codecvt`'s are added and do it similar. You could even copy the implementation of `std::codecvt<char8_t, char16_t, std::mbstate_t>` for windows. But I can't recommend implementing this for other platforms than windows, since wchar_t has a size of 4 bytes instead of 2 on those.

**Comment by mordante** [comment]
In general we try to avoid extensions in libc++ nowadays. The `<codecvt>` header has been deprecated in C++17 and will be removed in C++26 https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2871r3.pdf

I don't think it's time well spend to implement an extension to an already removed feature.

**Comment by jcelerier** [comment]
yes, there seems to be confusion, std::codecvt is not deprecated in any way, it even got new standard-blessed specializations in C++20 to account for char8_t: https://en.cppreference.com/w/cpp/locale/codecvt 

Could this be reopened ?

**Comment by mordante** [comment]
The code you posted on godbolt only included `<codecvt>`, hence I expected MSVC STL added them to that header. Note that `codecvt<char16_t, char8_t, mbstate_t>` and `codecvt<char32_t, char8_t, mbstate_t>` have been recently [deprecated](https://cplusplus.github.io/LWG/issue3767). So I still feel it's not really useful to add deprecated extensions.
