### ISSUE TITLE
DCE depends on datatype used (bool vs unsigned)

### ISSUE THREAD

**Issue by ThomasMayerl** [llvm/llvm-project#56653]
In some cases, the compiler's ability to eliminate dead code depends on the datatype used (bool vs unsigned).

LLVM detects that the if expression in the following code snippet evaluates to false and thus removes the dead code:

```c
#include <stdio.h>
#include <stdbool.h>

static void __attribute__ ((noinline)) DCEMarker0_() {printf("DCE2.0");}

void f(bool sc, bool s, bool c) {
    if ((sc && s && c && !(sc))) {
        DCEMarker0_();
    }
}
```

In the following snippet the datatype is switched to unsigned (the semantics stay the same). However, LLVM cannot eliminate the dead code anymore:

```c
#include <stdio.h>
#include <stdbool.h>

static void __attribute__ ((noinline)) DCEMarker0_() {printf("DCE2.0");}

void f(unsigned sc, unsigned s, unsigned c) {
    if ((sc && c && s && !(sc))) {
        DCEMarker0_();
    }
}
```

This can also be seen via the following Compiler Explorer link: https://godbolt.org/z/4aEEeGToj (clang 14.0.0)

**Comment by rotateright** [comment]
This is a limitation of -reassociate and/or -instcombine. Adding canonicalization/reassociation to move a value with multiple uses lower in the logic chain might solve it.

As a work-around, if the source is rewritten to bring the sc and !sc terms closer together, it should reduce.

IR test:
https://alive2.llvm.org/ce/z/9drE3P

define i1 @src(i1 %x, i1 %y, i1 %z)  {
  %xy = and i1 %x, %y
  %xyz = and i1 %xy, %z
  %not_xyz = xor i1 %xyz, true
  %r = or i1 %not_xyz, %x
  ret i1 %r
}

**Comment by rotateright** [comment]
Proposal to reassociate based on number of uses of values:
https://reviews.llvm.org/D131356
