### ISSUE TITLE
 cannot build llvm-libc with gcc 6.3

### ISSUE THREAD

**Issue by kleag** [llvm/llvm-project#56683]
This is maybe related to #53574  ("cannot build llvm-libc-13 with gcc")

Context: I'm trying to build Qt6 using a recent LLVM compiler on manylinux_2_24 in order to use PySide6 to build a native python binding for a C++ project for python 10. That's why I try to build llvm on a so old system.

I read elsewhere that a recent gcc is necessary but if this is the cause of the failure, there should be a check enforcing that.

The Dockerfile doing the build is here: https://github.com/aymara/lima/blob/port-to-qt6/continuous_integration/Dockerfile-manylinux_2_24_with_llvm
The build traces are there: https://github.com/aymara/lima/runs/7475225160

This is the cmake command with the compiler detection trace:
```console
Step 15/22 : RUN cmake -S llvm -B build -G Ninja -DLLVM_PARALLEL_LINK_JOBS=1 -DCMAKE_BUILD_TYPE=Release -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt;libc;libclc;lld;lldb;openmp;pstl" -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" -DCMAKE_INSTALL_PREFIX=/opt/llvm
 ---> Running in 0b757e605084
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- The ASM compiler identification is GNU
```

And the build error:
```console
[1937/7600] Building CXX object projects/libc/src/string/CMakeFiles/libc.src.string.bzero.dir/bzero.cpp.o
FAILED: projects/libc/src/string/CMakeFiles/libc.src.string.bzero.dir/bzero.cpp.o 
/usr/bin/c++ -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/llvm-project-llvmorg-14.0.6/build/projects/libc/src/string -I/llvm-project-llvmorg-14.0.6/libc/src/string -I/llvm-project-llvmorg-14.0.6/build/include -I/llvm-project-llvmorg-14.0.6/llvm/include -I/llvm-project-llvmorg-14.0.6/build/projects/libc/include -I/llvm-project-llvmorg-14.0.6/libc -I/llvm-project-llvmorg-14.0.6/build/projects/libc -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG -fno-builtin-bzero -mllvm -combiner-global-alias-analysis -fpie -ffreestanding -DLLVM_LIBC_PUBLIC_PACKAGING -std=c++14 -MD -MT projects/libc/src/string/CMakeFiles/libc.src.string.bzero.dir/bzero.cpp.o -MF projects/libc/src/string/CMakeFiles/libc.src.string.bzero.dir/bzero.cpp.o.d -o projects/libc/src/string/CMakeFiles/libc.src.string.bzero.dir/bzero.cpp.o -c /llvm-project-llvmorg-14.0.6/libc/src/string/bzero.cpp
c++: error: unrecognized command line option '-mllvm'
c++: error: unrecognized command line option '-combiner-global-alias-analysis'
```

**Comment by kleag** [comment]
I just retried with gcc 10.1.0 but got the same result:
https://github.com/aymara/lima/runs/7480161931?check_suite_focus=true

**Comment by asl** [comment]
Well, just do not include `libc` into a set of projects. It's WIP currently. Looks like for your task you'd just need clang and that's it.

**Comment by kleag** [comment]
> Well, just do not include `libc` into a set of projects. It's WIP currently. Looks like for your task you'd just need clang and that's it.

Oh, I did not know it was a WIP. I in fact tried to buid my project with llvm compiled with clang only. But as it failed in a way I did not understand (see my SO question here: https://stackoverflow.com/questions/73085554/why-configuring-qt6-sources-fails-on-manylinux-2-24-with-llvm), I decided a bit randomly to give a try to the other projects.

In fact, I also suspect that my original problem could come from having compiled llvm with gcc 6.3. That's why I'm currently compiling it with gcc 10.1.0. As I don't understand the cause of the problem I'm trying other things…

This being said, the problem I reported really exist. Should I close this issue because it is a "WIP"?

**Comment by asl** [comment]
It looks like a dup of #53574, but I'd let @gchatelet decide

**Comment by gchatelet** [comment]
There are many things here:
- `llvm-libc` is WIP and intended to be built with a recent `clang`
- you don't need it to compile `clang`
- although theoretically it can be compiled with `gcc`, it has to be built with a recent one; on top of that we cannot guarantee that the codegen will be great
- the error you are facing is fixed on `main` (`-mllvm -combiner-global-alias-analysis` is a compiler option targeted to `clang` and is not valid when compiling with `gcc`)

**Comment by kleag** [comment]
I think that this bug report is in fact invalid. Let me close it.
