### ISSUE TITLE
NTTP to subobject of non-prohibited cases should be allowed

### ISSUE THREAD

**Issue by JohelEGP** [llvm/llvm-project#56695]
See https://godbolt.org/z/nT8nxWTsG and https://eel.is/c++draft/temp.arg.nontype#3.
```C++
struct X { int i; };
constexpr X x{};
template<const int&> struct Y { };
Y<x.i> y;
```
```console
<source>:4:3: error: non-type template argument refers to subobject 'x.i'
Y<x.i> y;
  ^
```

**Comment by shafik** [comment]
It looks like this change was brought in by [p1907r1](https://wg21.link/p1907r1) and according the [clang status page](https://clang.llvm.org/cxx_status.html) it is only partially implemented.

**Comment by cor3ntin** [comment]
Fixed in Clang 18
