### ISSUE TITLE
Create an "issue-subscribers-clangd" team

### ISSUE THREAD

**Issue by HighCommander4** [llvm/llvm-project#56690]
While clangd has its [own issue tracker](https://github.com/clangd/clangd/issues/), some clangd bugs get filed in llvm/llvm-project, and there is a [clangd label](https://github.com/llvm/llvm-project/issues?q=label%3Aclangd) for them.

However, there is no corresponding `issue-subscribers-clangd` team in the [list of teams](https://github.com/orgs/llvm/teams/). Would it be possible to create one, to make it easier to keep on eye on these issues?

**Comment by HighCommander4** [comment]
@tstellar friendly ping on this

**Comment by tru** [comment]
ping @asl (not sure who eles have admin on github org).

**Comment by tstellar** [comment]
Team added.
