### ISSUE TITLE
clang-tidy not respecting -Wno-builtin-macro-redefined with gnu++20

### ISSUE THREAD

**Issue by barci2** [llvm/llvm-project#56709]
If clang-tidy is set to use the gnu++20 language standard (does not work with regular c++ or lower versions of gnu++) then the -Wno-builtin-macro-redefined CDB flag is not respected, even if the macro is redefined as a compilation flag itself. Note that this is not an issue with the regular compiler as it does not throw that error. Minimal reproducer:
`touch test.cc && llvm-project/build/bin/clang-tidy test.cc -- -std=gnu++20 -D__TIME__ -Wno-builtin-macro-redefined`

**Comment by HappyCerberus** [comment]
Is there any workaround?

This just cropped up for me when using the Bazel module for clang-tidy integration: https://github.com/erenon/bazel_clang_tidy

**Comment by igormcoelho** [comment]
Just got into this error, with the same problem using https://github.com/erenon/bazel_clang_tidy.
The clang-tidy fix proposed there (https://github.com/erenon/bazel_clang_tidy/issues/29) resolved this for me, putting this flag into `.clang-tidy` file:  `-clang-diagnostic-builtin-macro-redefined`
So, maybe it's an issue of clang-tidy itself, not clang? Anyway, this resolved the issue for me.

**Comment by HappyCerberus** [comment]
> So, maybe it's an issue of clang-tidy itself, not clang?

This is a clang-tidy bug report (nothing to do with clang).

**Comment by AaronBallman** [comment]
Can confirm this issue: https://godbolt.org/z/ohq19e8Wq Clang silences the diagnostic and clang-tidy continues to issue it.

**Comment by PiotrZSL** [comment]
Related to #61969
