### ISSUE TITLE
Non-temporal hint dropped on a non-temporal load

### ISSUE THREAD

**Issue by kiroma** [llvm/llvm-project#56703]
The following code:
```cpp
#include <immintrin.h>
void copy_non_temporal(const __m128i* src, __m128i* dst)
{
    _mm_stream_si128(dst, _mm_stream_load_si128(src));
}
```
Generates a `vmovntps` for the store, but a `vmovaps` for the load, dropping the non-temporal hint.
Using godbolt, I've noticed that this issue doesn't exit in clang 4.0.1, but starts happening with clang 5

**Comment by nikic** [comment]
Please do provide the godbolt link next time. https://godbolt.org/z/vx8bh3Pv8 occurs at `O3` only.

**Comment by phoebewang** [comment]
Thanks @nikic for the information! The meta data `!nontemporal !9` was lost during ArgumentPromotionPass. The pass only run on O3 and promotes readonly memory arguments to registers. Maybe we can check `nontemporal`? I'm not sure given nontemporal is just a hint and it might be beneficial sometime if we ignore it.

```
*** IR Dump After PostOrderFunctionAttrsPass on (_mm_stream_load_si128) ***
; Function Attrs: alwaysinline argmemonly mustprogress nofree norecurse nosync nounwind readonly willreturn uwtable
define internal fastcc <2 x i64> @_mm_stream_load_si128(ptr nocapture noundef readonly %__V) unnamed_addr #2 {
entry:
  %0 = load <2 x i64>, ptr %__V, align 16, !tbaa !5, !nontemporal !8
  ret <2 x i64> %0
}
*** IR Dump After ArgumentPromotionPass on (_mm_stream_load_si128) ***
; Function Attrs: alwaysinline argmemonly mustprogress nofree norecurse nosync nounwind readonly willreturn uwtable
define internal fastcc <2 x i64> @_mm_stream_load_si128(<2 x i64> %__V.0.val) unnamed_addr #2 {
entry:
  ret <2 x i64> %__V.0.val
}

... ...

*** IR Dump After InlinerPass on (copy_non_temporal) ***
; Function Attrs: nounwind uwtable
define dso_local void @copy_non_temporal(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #0 {
entry:
  %src.val = load <2 x i64>, ptr %src, align 16, !tbaa !5
  store <2 x i64> %src.val, ptr %dst, align 16, !tbaa !5, !nontemporal !8
  ret void
}
```

**Comment by nikic** [comment]
Fixing this is probably as simple as adding nontemporal metadata to this list: https://github.com/llvm/llvm-project/blob/a299539adeede887b39e4a913e98047651656592/llvm/lib/Transforms/IPO/ArgumentPromotion.cpp#L248

**Comment by phoebewang** [comment]
Put a patch [D130536](https://reviews.llvm.org/D130536) as @nikic 's suggestion.
