### ISSUE TITLE
Backport request: 8e218026f8d5eabfdef9141ae5e26aa91d1933e6 ("[clang] [MinGW] Fix paths on Gentoo")

### ISSUE THREAD

**Issue by thesamesam** [llvm/llvm-project#56701]
Please consider backporting https://github.com/llvm/llvm-project/commit/8e218026f8d5eabfdef9141ae5e26aa91d1933e6 to 14.x.

The change was originally made to fix a Gentoo bug: https://bugs.gentoo.org/788430, FWIW.

cc @mgorny @mstorsjo @maharmstone

**Comment by EugeneZelenko** [comment]
As far as I know, backports to 14 were ended.

@tstellar

**Comment by thesamesam** [comment]
Fine with me. It's not urgent at all.

**Comment by nikic** [comment]
Yes, the LLVM 14 release is finished, and this will not need an LLVM 15 backport (because it is already on main).
