### ISSUE TITLE
llvm distribution needs a Version.h

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5671]
|  |  |
| --- | --- |
| Bugzilla Link | [5299](https://llvm.org/bz5299) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @tlattner |

## Extended Description 
It's rude to make clients that care about building with multiple LLVM sources figure out the LLVM version themselves. See also:
  http://article.gmane.org/gmane.comp.compilers.llvm.cvs/40158

At the minimum we should have LLVM_VERSION_{MAJOR,MINOR}. An indication of whether the LLVM version is a released one or TOT would also be nice. LLVM_API_VERSION should be dealt with separately.

**Comment by gwelymernans** [comment]
Clang predefines these:

```
#define __clang_major__ 13
#define __clang_minor__ 0
#define __clang_patchlevel__ 1
#define __clang_version__ "13.0.1 "
```

There are also APIs available to get the versions.
