### ISSUE TITLE
[Bug] clang-tidy: Endless loop

### ISSUE THREAD

**Issue by xiaokang00010** [llvm/llvm-project#56719]
I'm trying to write a loop like
```c++
for (size_t I = 1; I >= 0; I--) {
    // do something here.
}
```
but clang-tidy keep telling me it's an endless loop.
I don't know why, but when I change `size_t` into `int`, it stopped warning me about that.

<img width="675" alt="QQ20220726-135627@2x" src="https://user-images.githubusercontent.com/47490867/180933786-d1a9379d-5ae8-4a89-8928-fba097195343.png">

**Comment by mzyKi** [comment]
may be size_t is a unsigned integer type, when zero--, it will wrap.
