### ISSUE TITLE
[AMDGPU][MC][GFX11] s_waitcnt_*cnt opcodes require src0=null

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#56710]
AFAIK, these opcodes require src0=null, but assembler currently accepts any `SGPR` for src0.

An example of failed test:

    s_waitcnt_expcnt s1, 0x3141

Expected output:

    An error.

Actual result:

    s_waitcnt_expcnt s1, 0x3141             ; encoding: [0x41,0x31,0x01,0xbd]

Is this a bug? Added @Sisyph and @jayfoad for awareness.

**Comment by jayfoad** [comment]
Seems reasonable for the assembler to give an error on this for GFX11.

**Comment by dpreobra** [comment]
Fixed by 485c5393915a
