### ISSUE TITLE
llvm-bolt registers .eh_frames which may refer to unmapped sections

### ISSUE THREAD

**Issue by amharc** [llvm/llvm-project#56726]
BOLT currently [calls](https://github.com/llvm/llvm-project/blob/0d191b7553e7efbf7ce57c77274b83c15b681933/bolt/lib/Rewrite/RewriteInstance.cpp#L3154) `RTDyld->finalizeWithMemoryManagerLocking();`, which is [documented](https://github.com/llvm/llvm-project/blob/0d191b7553e7efbf7ce57c77274b83c15b681933/llvm/include/llvm/ExecutionEngine/RuntimeDyld.h#L271-L273) to do three things:
* apply relocations;
* register `.eh_frame`s;
* update memory permissions.

The second step will ultimately call `__register_frame` if its present (e.g. [here](https://github.com/llvm/llvm-project/blob/ede600377cb6df1bef71f070130d8cfe734cc5b7/llvm/lib/ExecutionEngine/RuntimeDyld/RTDyldMemoryManager.cpp#L83)).

In PIC builds the personality function is [encoded](https://github.com/llvm/llvm-project/blob/ede600377cb6df1bef71f070130d8cfe734cc5b7/llvm/lib/CodeGen/TargetLoweringObjectFileImpl.cpp#L149) with indirection (`DW_EH_PE_indirect`) via a `DW.ref.__gxx_personality_v0` symbol [located](https://github.com/llvm/llvm-project/blob/41fba3c107a5bc99065f3bf8b9f5b9d52eab2d98/llvm/lib/CodeGen/TargetLoweringObjectFileImpl.cpp#L399) in the `.data` section, which is not mapped to the `RuntimeDyld`.

For example, for the following `main.cc`:
```c++
int Foo() {
  throw 42;
}

int main() {
  try {
    return Foo();
  } catch (...) {
    return 0;
  }
}
```
compiled with `clang++ main.cc -o main -fpic -Wl,-q` and processed with BOLT using `llvm-bolt main -o main.bolted -keep-tmp` one can see that the intermediary output object file doesn't contain the `.data` section.

Unfortunately this means that `__register_frame` can read unmapped data, e.g. LLVM's libunwind will do so when trying to [read](https://github.com/llvm/llvm-project/blob/41fba3c107a5bc99065f3bf8b9f5b9d52eab2d98/libunwind/src/DwarfParser.hpp#L380) the address of the personality routine and trying to [handle](https://github.com/llvm/llvm-project/blob/41fba3c107a5bc99065f3bf8b9f5b9d52eab2d98/libunwind/src/AddressSpace.hpp#L353) the `DW_EH_PE_indirect` case there.

I think that `llvm-bolt` doesn't need `.eh_frame`s to be registered in process and probably doesn't need to update memory permissions either (as it won't execute anything from the intermediary output object file in process), so probably the call to `RTDyld->finalizeWithMemoryManagerLocking()` should be changed to a call to `RTDyld->resolveRelocations()` - but I might be wrong and this may need a more careful approach, so filing this as a bug instead of just sending a patch for review.

**Comment by maksfb** [comment]
That's a good suggestion. Thanks! Let me verify how it works.

**Comment by zcfh** [comment]
I still have some questions about this example, can you demonstrate it in assembly?
Another question is whether using older version can cause such problems. Currently I use clang 11.1.0 for compilation, and the bolt is (LLVM version 14.0.0git 88c70afe9d388ad430cc150cc158641701397f70).
