### ISSUE TITLE
possible zext-related miscompile with global isel on AArch64

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#56733]
hi folks, we're pretty sure this is a miscompile, since the argument/return register can contain junk in bits 1..7, right?

```console
Johns-MacBook-Pro:~ regehr$ cat foo.ll
define i8 @f(i1 %0) {
  %2 = zext i1 %0 to i8
  ret i8 %2
}
Johns-MacBook-Pro:~ regehr$ ~/llvm-project/for-alive/bin/llc -global-isel foo.ll -o -
	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 12, 0
	.globl	_f                              ; -- Begin function f
	.p2align	2
_f:                                     ; @f
	.cfi_startproc
; %bb.0:
	ret
	.cfi_endproc
                                        ; -- End function
.subsections_via_symbols
Johns-MacBook-Pro:~ regehr$ 
```

cc @ornata @nunoplopes @ryan-berger @nbushehri @aemerson

**Comment by regehr** [comment]
this bug is wild, every width from 2..64 other than 8 results in a masking instruction being properly emitted

**Comment by aemerson** [comment]
This I believe is correct. This was an optimization added in https://reviews.llvm.org/D107160 but it seems the SelectionDAG side is failing to optimize away the AND.

**Comment by nunoplopes** [comment]
In other words, the ABI implies that zeroext is the default passing mode for i1. (AFAIU)

**Comment by regehr** [comment]
well, zeroext would imply 63 leading zeroes, right?

**Comment by aemerson** [comment]
The zext is only affecting the lower 8 bits, no guarantees are made about the others.

**Comment by regehr** [comment]
thanks!! we'll relax our assumption at function entry and then also enforce it at return points
