### ISSUE TITLE
A few random typos in comments, diagnostic messages and HTML

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#56747]
I've found a few random typos in the current HEAD that seem like they should probably be fixed:

```cpp
clang-tools-extra/clangd/ConfigFragment.h-
clang-tools-extra/clangd/ConfigFragment.h:    /// Directory to search for compilation database (compile_comands.json etc).
clang-tools-extra/clangd/ConfigFragment.h-    /// Valid values are:
--
clang/www/analyzer/installation.html-<li><b>scan-build</b>: <tt>scan-build</tt> is the high-level command line utility for running the analyzer</li>
clang/www/analyzer/installation.html:<li><b>scan-view</b>: <tt>scan-view</tt> a companion comannd line
clang/www/analyzer/installation.html-utility to <tt>scan-build</tt>, <tt>scan-view</tt> is used to view
--
lldb/source/Plugins/Process/minidump/MinidumpParser.cpp-  // with breakpad generated minidumps where if someone has mmap'ed a shared
lldb/source/Plugins/Process/minidump/MinidumpParser.cpp:  // library into memory to accesss its data in the object file, we can get a
lldb/source/Plugins/Process/minidump/MinidumpParser.cpp-  // minidump with two mappings for a binary: one whose base image points to a
--
llvm/lib/Analysis/InstructionSimplify.cpp-
llvm/lib/Analysis/InstructionSimplify.cpp:    // Equality comaprisons are easy to fold.
llvm/lib/Analysis/InstructionSimplify.cpp-  case CmpInst::ICMP_EQ:
--
llvm/lib/Support/FileUtilities.cpp-/// files match, 1 if they are different, and 2 if there is a file error.  This
llvm/lib/Support/FileUtilities.cpp:/// function differs from DiffFiles in that you can specify an absolete and
llvm/lib/Support/FileUtilities.cpp-/// relative FP error that is allowed to exist.  If you specify a string to fill
--
llvm/lib/Target/ARM/MCTargetDesc/ARMAsmBackend.cpp-                      llvm::dbgs()
llvm/lib/Target/ARM/MCTargetDesc/ARMAsmBackend.cpp:                          << "CFI directive not compatiable with comact "
llvm/lib/Target/ARM/MCTargetDesc/ARMAsmBackend.cpp-                             "unwind encoding, opcode=" << Inst.getOperation()
--
llvm/lib/Target/PowerPC/PPCMIPeephole.cpp-    // We cannot optimize an unsupported compare opcode or
llvm/lib/Target/PowerPC/PPCMIPeephole.cpp:    // a mix of 32-bit and 64-bit comaprisons
llvm/lib/Target/PowerPC/PPCMIPeephole.cpp-    if (!isSupportedCmpOp(CMPI1->getOpcode()) ||
--
llvm/test/DebugInfo/macro_link.ll-
llvm/test/DebugInfo/macro_link.ll:; This test checks that DIMacro and DIMacroFile comaprison works correctly.
llvm/test/DebugInfo/macro_link.ll-
--
llvm/tools/llvm-cfi-verify/llvm-cfi-verify.cpp-// This tool verifies Control Flow Integrity (CFI) instrumentation by static
llvm/tools/llvm-cfi-verify/llvm-cfi-verify.cpp:// binary anaylsis. See the design document in /docs/CFIVerify.rst for more
llvm/tools/llvm-cfi-verify/llvm-cfi-verify.cpp-// information.
```

(Correct me if I'm wrong, but I'm pretty sure it's "commands" and not "comands", "command" and not "comannd", "access" and not "accesss", "comparisons" and not "comaprisons", "absolute" and not "absolete", "compact" and not "comact", "comparison" and not "comaprison", "analysis" and not "anaylsis")

PS: I would happily make a PR for this instead if you want, but I think technically I can't test whether I haven't somehow broken something by fixing the typos considering my laptop is essentially a potato that would be woefully inadequate for trying to build LLVM so I'm assuming it is more adequate to submit this issue instead.

**Comment by Naville** [comment]
> PS: I would happily make a PR for this instead if you want, but I think technically I can't test whether I haven't somehow broken something by fixing the typos considering my laptop is essentially a potato that would be woefully inadequate for trying to build LLVM so I'm assuming it is more adequate to submit this issue instead.

Not someone with commit access, but I don't think you are breaking anything so a PR should do it?

**Comment by pogo59** [comment]
>  I don't think you are breaking anything so a PR should do it?

The typos are all in comments, except for one in an .html file, so I agree; go for it.

**Comment by huangperry** [comment]
Hi I'd love to fix these typos as an easy way for me to make my first commit, if you don't mind Gabriel.

**Comment by GabrielRavier** [comment]
> Hi I'd love to fix these typos as an easy way for me to make my first commit, if you don't mind Gabriel.

Well, I was working on a bigger patch actually but if you want you can just do these, I won't mind (as in, I'm now at 290 fixed typos across the entire codebase after searching for them a while more)

**Comment by huangperry** [comment]
Ah in that case I'll let you continue and avoid making another patch.

**Comment by nettle790** [comment]
hi  
 I would like to fix these typos

**Comment by GabrielRavier** [comment]
> hi I would like to fix these typos

All of these are already fixed apart from just a few in https://reviews.llvm.org/D131122 and https://reviews.llvm.org/D131127 which are basically guaranteed to land eventually.

**Comment by AryanGodara** [comment]
Is this issue still open? Or are the typos fixed now in different PRs?
I would like to work on this
