### ISSUE TITLE
X86: Minor regression from llvm 14 with single array access and lea

### ISSUE THREAD

**Issue by SuperCoder7979** [llvm/llvm-project#56742]
## Description
When arrays are accessed once in a function, llvm14 produces a `mov` instruction that references the array in memory. However, trunk produces a lea that moves the array into a register, then performs the `mov`. This change makes sense when the array is accessed multiple times as it removes the extraneous memory reference, but it adds an additional unneeded instruction when there is only a single access of the array.

## Code
Compiling with: `-O3`
Godbolt: https://godbolt.org/z/W4saM9fha

```cpp
constexpr const static int array[5] = {1, 2, 3, 4, 5};

int get(int a) {
    return array[a];
}

int get2(int a, int b) {
    return array[a] + array[b];
}
```

<details>
<summary>trunk codegen</summary>

```asm
get(int):                                # @get(int)
        movsxd  rax, edi
        lea     rcx, [rip + array]
        mov     eax, dword ptr [rcx + 4*rax]
        ret
get2(int, int):                              # @get2(int, int)
        movsxd  rcx, edi
        lea     rdx, [rip + array]
        movsxd  rax, esi
        mov     eax, dword ptr [rdx + 4*rax]
        add     eax, dword ptr [rdx + 4*rcx]
        ret
```

</details>
<details>
<summary>llvm 14 codegen</summary>

```asm
get(int):
        movsxd  rax, edi
        mov     eax, dword ptr [4*rax + array]
        ret
get2(int, int):
        movsxd  rcx, edi
        movsxd  rax, esi
        mov     eax, dword ptr [4*rax + array]
        add     eax, dword ptr [4*rcx + array]
        ret
```

</details>

**Comment by topperc** [comment]
The use of `rip` in the array indicates that we've changed how the address of the array is being computed. Trunk is using a position independent address, but llvm-14 isn't. I'm guessing this is related to -fpie being made the default by https://reviews.llvm.org/D120305

Can you try with `-fno-pie` on the clang command line?

**Comment by SuperCoder7979** [comment]
Oh yep, that does seems to change it to what llvm 14 produces! Would this still qualify as a bug, then?

**Comment by topperc** [comment]
Adding @MaskRay

**Comment by MaskRay** [comment]
This is not a regression. It is a -fno-pic vs -fpie code generation difference. See https://github.com/llvm/llvm-project/issues/57449#issuecomment-1232122016 and https://github.com/compiler-explorer/gcc-cross-builder/issues/33
