### ISSUE TITLE
[OpenMP] offload issue with complex reduction

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#56753]
I got invalid memory access inside the GPU kernel
```shell
clang++ -fopenmp -fopenmp-targets=nvptx64 -Xopenmp-target=nvptx64 -march=sm_80 -O3 complex_reduction.cpp && ./a.out 
```
[code](https://github.com/ye-luo/openmp-target/blob/master/tests/complex/complex_reduction.cpp)

4794bbffb228894de3ca0dad50fc027eb94f743e is good
24c993dab6bec662bfae6ed6dfaf22c6a18cc0ce is bad

affecting main and 15 release

**Comment by tru** [comment]
@ye-luo do you want to backport this commit to 15.x?

**Comment by jdoerfert** [comment]
> @ye-luo do you want to backport this commit to 15.x?

yes please
