### ISSUE TITLE
Documentation: why is "Support for UTF-8 as a portable source file encoding" said to be implemented in Clang 15?

### ISSUE THREAD

**Issue by frederick-vs-ja** [llvm/llvm-project#56750]
AFAIK Clang has been supporting UTF-8 source files since a very first release (if not the first, see also [this](https://godbolt.org/z/9f94fTMed)), as said in [P2295R6](https://wg21.link/p2295r6).

@cor3ntin

**Comment by cor3ntin** [comment]
[P2295R6](https://wg21.link/p2295r6) mandates that a diagnostic is emitted for invalid utf-8 in comments, which Clang only started to do in Clang 15 in pedantic mode. before that it would accept invalid utf-8 in comments which isn't conforming with this paper.

**Comment by cor3ntin** [comment]
@frederick-vs-ja Does my answer satisfies you? If so I think we can close the issue

**Comment by frederick-vs-ja** [comment]
> @frederick-vs-ja Does my answer satisfies you? If so I think we can close the issue

Thanks, the answer is helpful. Let me close the issue.
