### ISSUE TITLE
Are module files in LLVM Flang platform/target agnostic?

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#56764]
If cross compiling with Flang, e.g. I've built the flang executable on x86_64 linux, but I invoke `flang-new` with `--target=aarch64-windows`, Flang would end up including module files that have been generated by the build of `flang-new` for its default target instead of the target I'm currently compiling for. Are those module files usable for other targets than the one they were generated for?

(I'm aware that flang isn't entirely ready for all cross compilation use - I'm trying to take baby steps towards making it work in such cases.)

This issue was brought up for discussion in https://reviews.llvm.org/D130349#3674498.

**Comment by klausler** [comment]
No.
