### ISSUE TITLE
Add `arm64-apple-darwin` binary to releases

### ISSUE THREAD

**Issue by realityforge** [llvm/llvm-project#56767]
The binary release does not currently include a `arm64-apple-darwin` binary release and only includes the `x86_64-apple-darwin` variant. It would be great to include an arm64 variant to simplify downstream users that uses the releases to in their build infrastructure.

**Comment by tstellar** [comment]
@realityforge The binaries are provided by volunteer testers.  You may want to try asking on the release testers on [Discourse](https://discourse.llvm.org/c/infrastructure/release-testers/66).

**Comment by realityforge** [comment]
Thanks for the heads up!

**Comment by keith** [comment]
@realityforge are you planning on doing this? Otherwise I might post instead
