### ISSUE TITLE
clang-format non-idempotency with tabs in comment

### ISSUE THREAD

**Issue by kerrickstaley** [llvm/llvm-project#56769]
When I re-format a file containing the following single line, and then re-format it a second time, it changes again the second time:
```c
//				ofMap(message.velocity, 0, 127, 0, ofGetWidth() * 0.2)
```
After the `//` there are 4 tab characters.

You can reproduce this by running the below commands. You can see from their output that there is a diff: the asterisk moves down a line.
```console
$ echo -e '//\t\t\t\tofMap(message.velocity, 0, 127, 0, ofGetWidth() * 0.2)' | clang-format
//				ofMap(message.velocity, 0, 127, 0, ofGetWidth() *
//0.2)
$ echo -e '//\t\t\t\tofMap(message.velocity, 0, 127, 0, ofGetWidth() * 0.2)' | clang-format | clang-format
//				ofMap(message.velocity, 0, 127, 0, ofGetWidth()
//* 0.2)
```

This example was minimized from some real-world code. Although it's not representative of high-quality production code (it contains commented code), I think this is still a case that clang-format should handle correctly, because it does happen in the wild.

System info:
```console
$ clang-format --version
clang-format version 14.0.6
```

**Comment by HazardyKnusperkeks** [comment]
Review: https://reviews.llvm.org/D138402
