### ISSUE TITLE
[clang-scan-deps] We need to support C++20 Named Modules

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#56770]
In C++20 Named Modules, we introduced `ImportDecl` to describe the dependencies between modules. But this haven't been handled by clang-scan-deps.

For example,

```C++
// A.cppm
export module A;
...

// B.cpp
import A;
```

Currently we can't find that A.cppm is a dependence of B.cpp.

**Comment by tschuett** [comment]
Format for describing dependencies of source files:
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p1689r5.html

How CMake supports Fortran modules and its applicability to C++:
https://mathstuf.fedorapeople.org/fortran-modules/fortran-modules.html

**Comment by Arthapz** [comment]
this is linked to https://github.com/llvm/llvm-project/issues/51792

**Comment by aaronmondal** [comment]
Fixing this would probably also fix https://github.com/llvm/llvm-project/issues/57293.

**Comment by ChuanqiXu9** [comment]
I would take this one.
