### ISSUE TITLE
C++: Clang allows a wrongly-named destructor in Templates.

### ISSUE THREAD

**Issue by JFinis** [llvm/llvm-project#56772]
The following code compiles fine on clang (14.0 and latest trunk), even though the destructor of `Foobar` is not called `~Foobar` but `~Node`. GCC reports an error as expected.

```c++
struct Node {}; 
template <int x> 
struct Foobar { ~Node() {} }; 
Foobar<5> f{};
```

https://godbolt.org/z/T8jTrPYW1

**Comment by royjacobson** [comment]
Thanks for reporting this, @JFinis! It should be fixed now https://reviews.llvm.org/D130936
