### ISSUE TITLE
Missed Optimization: recognize output of round() and trunc() is integral

### ISSUE THREAD

**Issue by RedBeard0531** [llvm/llvm-project#56775]
When doing `round(trunc(in))` and `trunc(round(in))` the outer operation is redundant because the inner operation is guaranteed to emit an integral value. It looks like there is already some optimizations in place to eliminate these calls when the input is known to be integral, but it doesn't seem to cover mixing the functions. GCC seems to handle this correctly.

https://godbolt.org/z/xq3sqjTzb

```cpp
#include <cmath>

// These incorrectly emit both calls
double tr(double in) {
    return trunc(round(in));
}
double rt(double in) {
    return round(trunc(in));
}

// These correctly omit the outer operation
double rr(double in) {
    return round(round(in));
}
double tt(double in) {
    return trunc(trunc(in));
}
double r(long long in) {
    return round(double(in));
}
double t(long long in) {
    return trunc(double(in));
}
```

clang outout:
```asm
tr(double): # @tr(double)
  pushq %rax
  callq round@PLT
  popq %rax
  jmp trunc@PLT # TAILCALL       <--- UNNECESSARY
rt(double): # @rt(double)
  pushq %rax
  callq trunc@PLT
  popq %rax
  jmp round@PLT # TAILCALL       <--- UNNECESSARY
rr(double): # @rr(double)
  jmp round@PLT # TAILCALL
tt(double): # @tt(double)
  jmp trunc@PLT # TAILCALL
r(long long): # @r(long long)
  cvtsi2sd %rdi, %xmm0
  retq
t(long long): # @t(long long)
  cvtsi2sd %rdi, %xmm0
  retq
```

gcc output (using `-Os` to avoid the inline expansion of `trunc()`):
```asm
tr(double):
  jmp round
rt(double):
  jmp trunc
rr(double):
  jmp round
tt(double):
  jmp trunc
r(long long):
  cvtsi2sdq %rdi, %xmm0
  ret
t(long long):
  cvtsi2sdq %rdi, %xmm0
  ret
```

**Comment by rotateright** [comment]
We need a list FP libcalls/intrinsics that are effectively a no-op for an integral value. This isn't limited to round and trunc pairs alone:
https://alive2.llvm.org/ce/z/vFkBUf

The case where we reduce a function on itself is probably handled by InstSimplify using "isIdempotent".

**Comment by rotateright** [comment]
Actually, we already have a list of those functions - we just didn't recognize patterns where they call each other:
https://github.com/llvm/llvm-project/blob/7898426a72440bd68f3d3df5799b1f1bc11f2b04/llvm/lib/Analysis/InstructionSimplify.cpp#L5698-L5713

**Comment by rotateright** [comment]
Should be fixed with:
02b3a358926e7bb
