### ISSUE TITLE
Excessive time spent in `ArrayExprEvaluator::VisitCXXConstructExpr` for large dynamic array allocation

### ISSUE THREAD

**Issue by PerkinsRay** [llvm/llvm-project#56774]
```c++
struct Line_Buffer {
    char line[128];
};
struct DumpHandler {
    DumpHandler() {
        Line_Buffer *A;
        A = new Line_Buffer[1024 * 1024 * 50];
    }
    ~DumpHandler() {}
};
int main(){
    return 0;
}
```

**Comment by PerkinsRay** [comment]
version10 and above are affected

**Comment by PerkinsRay** [comment]
https://godbolt.org/z/3jK5caaEa
![image](https://user-images.githubusercontent.com/9638063/181485378-5ac52af2-962d-49d8-b2f4-03a90c2633b9.png)

**Comment by tbaederr** [comment]
I mean, the array has no filler, but the constructor being called is a trivial default constructor. I wonder if the code could check for that and simply call it once and then plaster the result over the entire array. Or is the constructor guaranteed to be called `1024 * 1024 * 50` times? Any opinion oin this, @AaronBallman? (sorry for asking you again, I just need a second opinion)

**Comment by AaronBallman** [comment]
> I mean, the array has no filler, but the constructor being called is a trivial default constructor. I wonder if the code could check for that and simply call it once and then plaster the result over the entire array. Or is the constructor guaranteed to be called `1024 * 1024 * 50` times? Any opinion oin this, @AaronBallman? (sorry for asking you again, I just need a second opinion)

When we call `VisitCXXConstructExpr()` from there, we're recurse back into the function, and eventually wind up at `RecordExprEvaluator::VisistCXXConstructExpr()`, which does have special logic for trivial default constructors: https://github.com/llvm/llvm-project/blob/2b230d69ad44a4ead1071572e78240e9bdc74e0d/clang/lib/AST/ExprConstant.cpp#L10061 and I can't see anything in there that would vary depending on which array element is being initialized. I think it would be fine to call it once and then reuse that for the entire array (assuming there's no lifetime management issues with the values produced).

**Comment by tbaederr** [comment]
Potential solution here: https://reviews.llvm.org/D130791

With a local debug build, clang needs 35 seconds after this change and 360 seconds before to compile the reproducer.
