### ISSUE TITLE
[AMDGPU][MC][GFX940] Incorrect disassembly of v_cvt_pk_f32_bf8 and v_cvt_pk_f32_fp8

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#56786]
These opcodes may only be encoded as VOP1, however they have `_e32` suffix when disassembled.

An example of failed test:

    0x01,0xae,0x14,0x7e

Expected output:

    v_cvt_pk_f32_bf8 v[10:11], s1

Actual result:

    v_cvt_pk_f32_bf8_e32 v[10:11], s1

**Comment by dpreobra** [comment]
I'm not sure if this is a bug, but SP3 does not support VOP3 encoding for these opcodes. Added @rampitec for awareness.

**Comment by rampitec** [comment]
SP3 does support VOP3 for this opcode.

**Comment by rampitec** [comment]
v_cvt_pk_f32_bf8  v[10:11], s1 vop3                   // 000000000000: D197000A 00000001

**Comment by dpreobra** [comment]
Thanks for the clarification!
