### ISSUE TITLE
Expressions are better optimised by using nested if statements

### ISSUE THREAD

**Issue by ThomasMayerl** [llvm/llvm-project#56780]
In some cases, the compiler's ability to eliminate dead code depends on whether the if statement is nested or not.

LLVM detects that the if expressions in the following code snippet evaluate to false and thus removes the dead code:

```c
#include <stdio.h>
#include <stdbool.h>

static void __attribute__ ((noinline)) DCEMarker0_() {printf("DCE2.0");}

void f(unsigned s, unsigned c) {
    if (!c) {
        if (!s && s) {
            DCEMarker0_();
        }
    }
}
```
In the following snippet the nested if expressions are replaced by one if statement. However, LLVM cannot eliminate the dead code anymore:

```c
#include <stdio.h>
#include <stdbool.h>

static void __attribute__ ((noinline)) DCEMarker0_() {printf("DCE2.0");}

void f(unsigned s, unsigned c) {
    if (!c && (!s && s)) {
        DCEMarker0_();
    }
}
```

Note: This difference can only be seen if the datatype is set to unsigned instead of bool (Might be related to: #56653) and the order of the subexpressions in the if is not changed (Might be related to: #56654).

This was tested using LLVM 14.0.6. The described behaviour can also be seen via the following Compiler Explorer link: https://godbolt.org/z/jGo3Wxq5j

**Comment by ThomasMayerl** [comment]
Another similar example:

Original (one if statement):

```c
#include <stdio.h>
#include <stdbool.h>

static void __attribute__ ((noinline)) DCEMarker0_() {printf("DCE2.0");}

void f(unsigned c, unsigned s) {
    if (!s && !c && s) {
        DCEMarker0_();
    }
}
```

Modified (nested if) - optimises better:

```c
#include <stdio.h>
#include <stdbool.h>

static void __attribute__ ((noinline)) DCEMarker0_() {printf("DCE2.0");}

void f(unsigned c, unsigned s) {
    if (!s){
        if (!c && s) {
            DCEMarker0_();
        }
    }
}
```

Compiler Explorer link: https://godbolt.org/z/E7WWWcG53

**Comment by bcl5980** [comment]
Simpilfy to:
```
void f(unsigned c, unsigned s) {
    if (!s && !c && s) {
        asm volatile("nop");
    }
}
```

**Comment by bcl5980** [comment]
https://alive2.llvm.org/ce/z/2y7ZN8
```
define i1 @src(i8 %x, i8 %y) {
  %cmp1 = icmp ne i8 %x, 0
  %cmp2 = icmp ne i8 %y, 0
  %or = or i1 %cmp1, %cmp2
  %r = select i1 %or, i1 false, i1 %cmp1
  ret i1 %r
} 
```
It looks the transform (x != 0) || (y !=0) to (x | y) != 0 break the further DCE.
