### ISSUE TITLE
clang/lib/ExtractAPI/Serialization/SymbolGraphSerializer.cpp has a typo in the serialized object names

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#56787]
```cpp
clang/lib/ExtractAPI/Serialization/SymbolGraphSerializer.cpp-  serializeObject(Obj, "kind", serializeSymbolKind(Record, API.getLanguage()));
clang/lib/ExtractAPI/Serialization/SymbolGraphSerializer.cpp-  serializeObject(Obj, "names", serializeNames(Record));
clang/lib/ExtractAPI/Serialization/SymbolGraphSerializer.cpp-  serializeObject(
clang/lib/ExtractAPI/Serialization/SymbolGraphSerializer.cpp-      Obj, "location",
clang/lib/ExtractAPI/Serialization/SymbolGraphSerializer.cpp-      serializeSourceLocation(Record.Location, /*IncludeFileURI=*/true));
clang/lib/ExtractAPI/Serialization/SymbolGraphSerializer.cpp:  serializeObject(Obj, "availbility",
clang/lib/ExtractAPI/Serialization/SymbolGraphSerializer.cpp-                  serializeAvailability(Record.Availability));
clang/lib/ExtractAPI/Serialization/SymbolGraphSerializer.cpp-  serializeObject(Obj, "docComment", serializeDocComment(Record.Comment));
clang/lib/ExtractAPI/Serialization/SymbolGraphSerializer.cpp-  serializeArray(Obj, "declarationFragments",
clang/lib/ExtractAPI/Serialization/SymbolGraphSerializer.cpp-                 serializeDeclarationFragments(Record.Declaration));
clang/lib/ExtractAPI/Serialization/SymbolGraphSerializer.cpp-  // TODO: Once we keep track of symbol access information serialize it
```

Seems like it should be "availability" and not "availbility" to me but I'd rather make it a new issue instead of putting it in my patch w.r.t. my previous issue on the subject of typos (https://github.com/llvm/llvm-project/issues/56747) because this would directly change what Clang outputs on what I would assume is a visible API and I'd just like to check if correcting such a typo just like that is fine.

**Comment by GabrielRavier** [comment]
Btw I'm also looking at a function called `registerCanonicalicationPasses` (instead of `registerCanonicalizationPasses`) in polly, and I'm also wondering if it's ok if I also change its name to fix the typo (seems like a similar issue to this so it seems logical to me to ask here)

**Comment by sloorush** [comment]
Will changing this have side effects? If yes, how to test these side effects?

**Comment by GabrielRavier** [comment]
That is pretty much what I'm wondering about since I'm not very familiar with the LLVM codebase

**Comment by sloorush** [comment]
Can someone with experience with LLVM shed some light on the issue? @EugeneZelenko, could you please help?

**Comment by sloorush** [comment]
I have dropped a small Differential for this issue.

https://reviews.llvm.org/D131277

**Comment by inclyc** [comment]
Thanks for working on this, changes on serialization may still cause issue related to backward compatibility. Even though this patch this pass all regression tests, but if in the future some one reports clang must give `availbility`, we may have to revert this change.
