### ISSUE TITLE
llc/clang 15.x not accepting certain opaque pointers code by default

### ISSUE THREAD

**Issue by jmaebe** [llvm/llvm-project#56788]
I have no idea what is so special about the construct in the attached file, but clang/llc (built from the 15.x branch, d77882e66779f) give the following warning/error when trying to compile it:

```
objcrtl/units/x86_64-darwin/objcrtliphoneos.ll:15:19: warning: ptr type is only supported in -opaque-pointers mode
        %reg.1_16 = load ptr, ptr @"\01_TC_$OBJCRTL_$$_DEFAULTOBJCLIBNAME", align 8, !dbg !8
                         ^
objcrtl/units/x86_64-darwin/objcrtliphoneos.ll:15:19: error: expected type
        %reg.1_16 = load ptr, ptr @"\01_TC_$OBJCRTL_$$_DEFAULTOBJCLIBNAME", align 8, !dbg !8
```
It does indeed compile correctly with -opaque-pointers, which is weird because that's the default now and a ton of other code I generate with opaque pointers in it is compiling fine without that parameter.

[objcrtliphoneos.txt](https://github.com/llvm/llvm-project/files/9213991/objcrtliphoneos.txt)

**Comment by nikic** [comment]
```
@"\01_INIT$_$OBJCRTLIPHONEOS" = alias  void (),  void ()* @"\01__OBJCRTLIPHONEOS_$$_init$"
```
You use a typed pointer here, that puts LLVM in typed pointer mode.

**Comment by jmaebe** [comment]
Ah, thanks! Seems I indeed missed a place in my opaque pointer support.
