### ISSUE TITLE
[clang-format] Requires expression misformatted with `BreakBeforeBraces: WebKit`

### ISSUE THREAD

**Issue by BertalanD** [llvm/llvm-project#56791]
Input, taken from cppreference's "Constraints and concepts" example:
```c++
template<typename T>
concept Hashable = requires(T a)
{
    { std::hash<T>{}(a) } -> std::convertible_to<std::size_t>;
};
```

`clang-format --style="{BreakBeforeBraces: WebKit}"` output:
```c++
template <typename T>
concept Hashable = requires(T a) {
                     {
                       std::hash<T>{}(a)
                       } -> std::convertible_to<std::size_t>;
                   };

```

`clang-format` version is 15.0.0, built from commit  37007475ca1b345b4c5d340e228bcd7a62732d81.

**Comment by rymiel** [comment]
Duplicate of #57108 (this one existed first but #57108 has already been fixed)
