### ISSUE TITLE
Conditional constant propagation suboptimal case

### ISSUE THREAD

**Issue by bcl5980** [llvm/llvm-project#56795]
https://godbolt.org/z/rabrEMrva

```cpp
unsigned f(unsigned x, unsigned y) {
    return (x == y) ? x * (x - y) : 0;
}
```
can return 0 direct.

**Comment by rotateright** [comment]
This type of transform usually happens in:
llvm::simplifyWithOpReplaced()
...so stepping through that code might show why we missed the transform for this example.

**Comment by nikic** [comment]
I believe this is because we only replace values one level up, while this requires looking back two instructions.

**Comment by bcl5980** [comment]
Maybe we call isImpliedByDomCondition in computeKnownBitsAddSub to set KnownBits for this case.
But I'm a little worry about the CPU overhead. And I don't know it is a good way or not.

**Comment by bcl5980** [comment]
Candidate Patch:
[D138542](https://reviews.llvm.org/D138542)
