### ISSUE TITLE
Missing ignored-attributes warning for `_Noreturn`

### ISSUE THREAD

**Issue by omern1** [llvm/llvm-project#56800]
### Reproducer:

``` C
static union str {
    _Noreturn int f1;
} s;

static union str2 {
     __attribute__((__noreturn__)) int f1;
} s1;
```

### Current Behaviour
When the reproducer is compiled with top of tree clang, a warning is emitted for the `f1` field in `str2`: `warning: '__noreturn__' only applies to function types; type here is 'int' [-Wignored-attributes]`, but no such warning is emitted for `f1` in `str`.

Observed with both `-std=c99` and `-std=c18`.

### Expected Behaviour
The aforementioned warning (or similar) should also be emitted for `str2.f1`.

**Comment by AaronBallman** [comment]
It's actually a bit worse than that; it's not an ignored attribute, it's a syntax error and we should be diagnosing it as such. See C2x 6.7.4p2: "Function specifiers shall be used only in the declaration of an identifier for a function."
