### ISSUE TITLE
Backport clang-tidy-confusable-chars-gen to 15.x release

### ISSUE THREAD

**Issue by kraj** [llvm/llvm-project#56808]
Currently building 15.x cross builds break in clang-tidy and are fixed in main branch with

https://github.com/llvm/llvm-project/commit/18b4a8bcf3553174f770f09528c9bd01c8cebfe7
https://github.com/llvm/llvm-project/commit/dc95d0c525636aed53a3b38258efa2dff4c83edf

Can these be back-ported to 15.x release branch please ?

**Comment by tstellar** [comment]
/cherry-pick 18b4a8bcf3553174f770f09528c9bd01c8cebfe7 dc95d0c525636aed53a3b38258efa2dff4c83edf
