### ISSUE TITLE
llvm-namespace-comment produces wrong namespace comment

### ISSUE THREAD

**Issue by philnik777** [llvm/llvm-project#56804]
clang-tidy currently produces `// namespace ranges::__cpo` for `namespace ranges::inline __cpo` while clang-format produces the (IMO) correct `// namespace ranges::inline __cpo`

**Comment by njames93** [comment]
Both are technically a correct name, I think the tidy check should be updated to support writing out the inline keyword.

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D157178
