### ISSUE TITLE
[C++23] [Modules] `-fprebuilt-module-path` doesn't work under `-std=c++2b`

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#56803]
It is easy to reproduce. Just change the language standard option to `-std=c++2b -fprebuilt-module-path=.`. Then the compiler would warning for:
```console
warning: argument unused during compilation: '-fprebuilt-module-path=.' [-Wunused-command-line-argument]
```

**Comment by ChuanqiXu9** [comment]
This is a basic issue. This should be good to be back ported to clang15.x.

**Comment by tru** [comment]
Seems fine to me.
