### ISSUE TITLE
How to debug infinite compiling loop?

### ISSUE THREAD

**Issue by Neumann-A** [llvm/llvm-project#56811]
so i am trying to compile everything with clang-cl (14.0.6) within vcpkg (https://github.com/microsoft/vcpkg/pull/25897). 
Unfortunally if I try to build the Release config of ffmpeg the compiler seems to get stuck in an infinite loop. The symptoms are: The output log is not updated for more than 16h and there are four processes running clang-cl at 100% per core. Since the Debug config works I assume it somehow stuck in the optimization passes. 

So I would need some advice on how to start debugging this.

**Comment by DimitryAndric** [comment]
What I typically do on FreeBSD or Linux in such a case, is send a SIGABRT to the stuck clang process, to force it to crash and dump reproduction files, e.g. a preprocessed .c or .cpp file, and a reproducer shell script. These can be used to further narrow down the problem with creduce or cvise.

That said, I'm unsure if such a thing is possible on Windows, where you don't really have signals. Maybe you can attach the Visual Studio debugger, and make it core dump somehow?

**Comment by Neumann-A** [comment]
There was no fix. I timed my build and used bisect until the infinite loop became an ICE.
