### ISSUE TITLE
WRONG code with Instcombine at -O1

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#56810]
This program:
```c
int printf(const char *, ...);
long a;
int b, c;
long d[2];
static long *e = &d[1];
char f;
short g, h;
int *i = &b;
short mod(short k, short l) { return k % l; }
static short add(short k, short l) { return k + l; }

int main() {
  long *n = &a;
  f = 3;
  g = mod(n != e, 51);  // 1, 51 => 1
  h = add(g & 3, 6);    // 1, 6  => 7
  c = f % h;
  *i = c;
  printf("%d\n", b);
}
```
should print `3`, which happens except on `-O1`. I suspect Instcombine is to blame as I can't help to think that it has mixed up the operands in the `urem` instruction:

```llvm
 *** IR Dump After SimplifyCFGPass on main ***
; Function Attrs: nofree nounwind
define dso_local signext i32 @main() local_unnamed_addr #1 {
entry:
  store i8 3, ptr @f, align 2, !tbaa !4
  %rem.i = srem i32 zext (i1 icmp ne (ptr getelementptr inbounds ([2 x i64], ptr @d, i64 0, i64 1), ptr @a) to i32), 51
  %conv2.i = trunc i32 %rem.i to i16
  store i16 %conv2.i, ptr @g, align 2, !tbaa !7
  %0 = and i16 %conv2.i, 3
  %add.i = add i16 %0, 6
  store i16 %add.i, ptr @h, align 2, !tbaa !7
  %conv6 = zext i16 %add.i to i32
  **%rem = urem i32 3, %conv6**
  store i32 %rem, ptr @c, align 4, !tbaa !9
  %1 = load ptr, ptr @i, align 8, !tbaa !11
  store i32 %rem, ptr %1, align 4, !tbaa !9
  %2 = load i32, ptr @b, align 4, !tbaa !9
  %call7 = call signext i32 (ptr, ...) @printf(ptr noundef nonnull @.str, i32 noundef signext %2)
  ret i32 0
}
*** IR Dump After InstCombinePass on main ***
; Function Attrs: nofree nounwind
define dso_local signext i32 @main() local_unnamed_addr #1 {
entry:
  store i8 3, ptr @f, align 2, !tbaa !4
  store i16 zext (i1 icmp ne (ptr getelementptr inbounds ([2 x i64], ptr @d, i64 0, i64 1), ptr @a) to i16), ptr @g, align 2, !tbaa !7
  store i16 add (i16 zext (i1 icmp ne (ptr getelementptr inbounds ([2 x i64], ptr @d, i64 0, i64 1), ptr @a) to i16), i16 6), ptr @h, align 2, !tbaa !7
  **%0 = urem i16 add (i16 zext (i1 icmp ne (ptr getelementptr inbounds ([2 x i64], ptr @d, i64 0, i64 1), ptr @a) to i16), i16 6), 3**
  %rem = zext i16 %0 to i32
  store i32 %rem, ptr @c, align 4, !tbaa !9
  %1 = load ptr, ptr @i, align 8, !tbaa !11
  store i32 %rem, ptr %1, align 4, !tbaa !9
  %2 = load i32, ptr @b, align 4, !tbaa !9
  %call7 = call signext i32 (ptr, ...) @printf(ptr noundef nonnull @.str, i32 noundef signext %2)
  ret i32 0
}
```
After Instcombine the `3` is now the second operand, which can't be right. It now prints `1` instead (`7%3`)...

`clang -target s390x-linux-gnu -march=arch13 -O1 wrong0.i`

**Comment by nikic** [comment]
From a cursory look, I'd guess that the responsible fold is this: https://github.com/llvm/llvm-project/blob/09c41211231578765cdb296bda3b4c7f3c22b4ba/llvm/lib/Transforms/InstCombine/InstCombineMulDivRem.cpp#L1011-L1025

It assumes that only one of the operands is constant, but thanks to the magic of constant expressions, both might be. In that case, it may indeed swap the operands.

**Comment by rotateright** [comment]
Thanks for the analysis! Looks like it's my fault ( https://reviews.llvm.org/D36988 ). 
I'll reduce the test and fix that if nobody has already done it.

**Comment by rotateright** [comment]
There seems to be some target-dependent component to making the source example show the bug. I don't see it on x86.

**Comment by JonPsson** [comment]
I started a bisect of this bug last night, which gave commit 935570b (HEAD, refs/bisect/bad) "[ConstExpr] Don't create div/rem expressions". Now that I see your progress already, I assume that commit must merely have exposed the older bug.

I can confirm that the miscompilation now seems gone as I found it after your fix, thanks :-)

**Comment by rotateright** [comment]
Thanks for finding the bug and verifying the fix! 
I made one more change to that fold to try to stay out of trouble:
f95a6aea1b10505293016b
