### ISSUE TITLE
Can't install clang-tidy-15 on Ubuntu 18.04

### ISSUE THREAD

**Issue by Zitrax** [llvm/llvm-project#56849]
Recently `apt install clang-tidy-15` stopped working (with `Package 'clang-tidy-15' has no installation candidate`) after using the bionic apt llvm repositories from https://apt.llvm.org

I suspected the default changed such that the package `clang-tidy` is now version 15, however I am getting:

```console
$ sudo apt install clang-tidy
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clang-tidy : Depends: clang-tidy-15 (>= 15~) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

The apt repositories were added like so:

```shell
add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main"
```

Am I missing something? How should 15 be installed now?

**Comment by njames93** [comment]
Could only guess it's due to version 15 is only at RC stage. Been a fair few weeks until its actually released.

**Comment by whisperity** [comment]
Usually, when a release is created, it will have a new top-level "channel", e.g. `llvm-toolchain-bionic-15` will point to the 15.y releases, and `llvm-toolchain-bionic` will be the rolling release (so ongoing 16) on top of main.

**Comment by Zitrax** [comment]
Right, I see it has been added now (timestamp 02-Aug-2022 04:18) at https://apt.llvm.org/bionic/pool/main/l/ and it works for me now.

It's still not documented at https://apt.llvm.org however.

**Comment by MarcoFalke** [comment]
Anything left to do here?

**Comment by MarcoFalke** [comment]
Closing for now, but let us know if this should be re-opened or if something else needs to be done.
