### ISSUE TITLE
Request to cherry-pick 41119a0f520d + related patches onto release/15.x

### ISSUE THREAD

**Issue by david-arm** [llvm/llvm-project#56853]
We have a series of 3 small backend patches (DAGCombiner + AArch64ISelLowering) that fix a significant performance regression when compared to LLVM 14. The changes only seem to affect AArch64 tests.

The first patch (6953e754c7a8) is a NFC test pre-commit, the second patch (487fa6f8c3af) is a AArch64ISelLowering.cpp change only, the third patch (41119a0f520d) adds a simple pattern to the DAGCombiner, but only AArch64 tests are affected.

**Comment by tstellar** [comment]
/cherry-pick 6953e754c7a887b22c56ce7b0526506e4aa86e7f 487fa6f8c3af87232f7ff9484568be7782f7f8b2 41119a0f520d07a438f7434f17ce63cc3a942d1b

**Comment by tru** [comment]
@david-arm who would be a good person to review this backport? anyone we should cross-check with or are you happy with us picking it up without a second look?

**Comment by david-arm** [comment]
> @david-arm who would be a good person to review this backport? anyone we should cross-check with or are you happy with us picking it up without a second look?

HI @tru, thanks for taking a look at this! I'm happy for you to pick them up. I landed the patches on main without any issue and I've also privately tested the backports so I'm pretty sure they're safe.
