### ISSUE TITLE
Request to cherry-pick a segv fix for openmp amdgpu onto release/15.x

### ISSUE THREAD

**Issue by JonChesterfield** [llvm/llvm-project#56856]
Segv was from the order in which destructors execute between shared libraries, does not reproduce on all systems. Patch in four pieces, one adds functions to libomptarget.so, two refactor the amdgpu plugin, last one uses the new functions to fix the segv.

1f9d3974e444f95ddb600a6964ed14ded559e89c introduce functions
75aa52106452a1d15ca487af7b408a812012e133 wrap calls to global in () syntax
c214cb6a689581c1b7f3b702b5da6d68de6eaf3f reintroduce `static` missed from previous
ed0f21811544320f829124efbb6a38ee12eb9155 fix the segv

**Comment by tstellar** [comment]
/cherry-pick 1f9d3974e444f95ddb600a6964ed14ded559e89c 75aa52106452a1d15ca487af7b408a812012e133 c214cb6a689581c1b7f3b702b5da6d68de6eaf3f ed0f21811544320f829124efbb6a38ee12eb9155
