### ISSUE TITLE
 cannot find /usr/lib/llvm-10/lib/clang/10.0.0/lib/linux/libclang_rt.profile-aarch64.a: No such file or directory

### ISSUE THREAD

**Issue by shrishailp** [llvm/llvm-project#56862]
Trying to compile edk2 source code with CLANG35 tool chain on AARCH64 architecture 
build -p MdeModulePkg/MdeModulePkg.dsc -m MdeModulePkg/Universal/DriverSampleDxe/DriverSampleDxe.inf -t CLANG35 -a AARCH64

"clang" -MMD -MF /home/bios/Patil/edk2/Build/MdeModule/DEBUG_CLANG35/AARCH64/MdeModulePkg/Universal/DriverSampleDxe/DriverSampleDxe/OUTPUT/Vfr.obj.deps -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common -mlittle-endian -fno-short-enums -fverbose-asm -funsigned-char -ffunction-sections -fdata-sections -Wno-address -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-pic -fno-pie -ffixed-x18 -target aarch64-linux-gnu -mcmodel=small -Wno-parentheses-equality -Wno-tautological-compare -Wno-tautological-constant-out-of-range-compare -Wno-empty-body -Wno-unknown-warning-option   -O1 --coverage -c -o /home/bios/Patil/edk2/Build/MdeModule/DEBUG_CLANG35/AARCH64/MdeModulePkg/Universal/DriverSampleDxe/DriverSampleDxe/OUTPUT/./Vfr.obj -I/home/bios/Patil/edk2/MdeModulePkg/Universal/DriverSampleDxe -I/home/bios/Patil/edk2/Build/MdeModule/DEBUG_CLANG35/AARCH64/MdeModulePkg/Universal/DriverSampleDxe/DriverSampleDxe/DEBUG -I/home/bios/Patil/edk2/MdePkg -I/home/bios/Patil/edk2/MdePkg/Include -I/home/bios/Patil/edk2/MdePkg/Test/UnitTest/Include -I/home/bios/Patil/edk2/MdePkg/Include/AArch64 -I/home/bios/Patil/edk2/MdeModulePkg -I/home/bios/Patil/edk2/MdeModulePkg/Include -I/home/bios/Patil/edk2/MdeModulePkg/Library/BrotliCustomDecompressLib/brotli/c/include /home/bios/Patil/edk2/Build/MdeModule/DEBUG_CLANG35/AARCH64/MdeModulePkg/Universal/DriverSampleDxe/DriverSampleDxe/DEBUG/Vfr.c
rm -f /home/bios/Patil/edk2/Build/MdeModule/DEBUG_CLANG35/AARCH64/MdeModulePkg/Universal/DriverSampleDxe/DriverSampleDxe/OUTPUT/DriverSample.lib
"ar" cr /home/bios/Patil/edk2/Build/MdeModule/DEBUG_CLANG35/AARCH64/MdeModulePkg/Universal/DriverSampleDxe/DriverSampleDxe/OUTPUT/DriverSample.lib  @/home/bios/Patil/edk2/Build/MdeModule/DEBUG_CLANG35/AARCH64/MdeModulePkg/Universal/DriverSampleDxe/DriverSampleDxe/OUTPUT/object_files.lst
"clang" -o /home/bios/Patil/edk2/Build/MdeModule/DEBUG_CLANG35/AARCH64/MdeModulePkg/Universal/DriverSampleDxe/DriverSampleDxe/DEBUG/DriverSample.dll -target aarch64-linux-gnu -Wl,--emit-relocs -nostdlib -Wl,--gc-sections -u _ModuleEntryPoint -Wl,-e,_ModuleEntryPoint,-Map,/home/bios/Patil/edk2/Build/MdeModule/DEBUG_CLANG35/AARCH64/MdeModulePkg/Universal/DriverSampleDxe/DriverSampleDxe/DEBUG/DriverSample.map -z common-page-size=0x20 -z common-page-size=0x1000 -Wl,--start-group,@/home/bios/Patil/edk2/Build/MdeModule/DEBUG_CLANG35/AARCH64/MdeModulePkg/Universal/DriverSampleDxe/DriverSampleDxe/OUTPUT/static_library_files.lst,--end-group -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common -mlittle-endian -fno-short-enums -fverbose-asm -funsigned-char -ffunction-sections -fdata-sections -Wno-address -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-pic -fno-pie -ffixed-x18 -target aarch64-linux-gnu -mcmodel=small -Wno-parentheses-equality -Wno-tautological-compare -Wno-tautological-constant-out-of-range-compare -Wno-empty-body -Wno-unknown-warning-option   -O1 --coverage -Wl,--script=/home/bios/Patil/edk2/BaseTools/Scripts/GccBase.lds -Wl,--defsym=PECOFF_HEADER_SIZE=0x228
/usr/bin/aarch64-linux-gnu-ld: cannot find /usr/lib/llvm-10/lib/clang/10.0.0/lib/linux/libclang_rt.profile-aarch64.a: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [GNUmakefile:329: /home/bios/Patil/edk2/Build/MdeModule/DEBUG_CLANG35/AARCH64/MdeModulePkg/Universal/DriverSampleDxe/DriverSampleDxe/DEBUG/DriverSample.dll] Error 1

build.py...
 : error 7000: Failed to execute command
        make tbuild [/home/bios/Patil/edk2/Build/MdeModule/DEBUG_CLANG35/AARCH64/MdeModulePkg/Universal/DriverSampleDxe/DriverSampleDxe]

build.py...
 : error F002: Failed to build module
        /home/bios/Patil/edk2/MdeModulePkg/Universal/DriverSampleDxe/DriverSampleDxe.inf [AARCH64, CLANG35, DEBUG]

- Failed -
Build end time: 00:33:01, Aug.02 2022
Build total time: 00:00:03

bios@bios-ProLiant-DL20-Gen9:~/Patil/edk2$

**Comment by asl** [comment]
Given that this is some 3rd party clang-based toolchain, I would suggest you to report issue there. Overall you're saying `CLANG35`, but the paths & error says `LLVM 10`.

**Comment by shrishailp** [comment]
Would you please suggest any valid clang based tool chain to build EDK2 source code

**Comment by asl** [comment]
I think you'd better ask EDK2 folks if something "special" is required / assumed, e.g. any particular versions, special settings, etc.

**Comment by shrishailp** [comment]
Thank you for your valuable time.
