### ISSUE TITLE
[AMDGPU][MC][GFX11] v_dot2_f16_f16 and v_dot2_bf16_bf16 do not accept SGPRs for src operands

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#56861]
These instructions do not accept `SGPRs` for src operands.

An example of failed test:

    v_dot2_bf16_bf16 v5, s1, v2, v3

Expected result:

    0x05,0x00,0x67,0xd6,0x01,0x04,0x0e,0x04

Actual output:

    error: invalid operand for instruction

I'm not sure if this is a bug, but SP3 seems to accept `SGPRs` for src operands.

Added @Sisyph for awareness.

**Comment by Sisyph** [comment]
This is a bug, both instructions should take SGPRs. We have llvm.amdgcn.fdot2.f16.f16.ll codegen test which is emitting an SGPR. It looks like the src operand types are correct but the modifier types are wrong, so the ParserMethod and PredicateMethod are getting things wrong.

**Comment by dpreobra** [comment]
Thanks, I see.

**Comment by dpreobra** [comment]
Closed by commit 05b3aadfff13.
