### ISSUE TITLE
[mlir] `DenseArrayAttrBase` returns 1 for an empty array when accessed through `ElementAttr` interface `size()` method

### ISSUE THREAD

**Issue by Mogball** [llvm/llvm-project#56860]
An empty dense array returns 1 for its size when queried through the `ElementsAttr` API. E.g. `[:i32]`

**Comment by joker-eph** [comment]
Is this a parsing issue?

**Comment by joker-eph** [comment]
OK, so this won't dispatch to `DenseArrayAttrBase::size` but will do `getType().cast<ShapedType>().getNumElements();`

**Comment by joker-eph** [comment]
Can you print `DenseArrayAttrBase::getType()` in this situation?

**Comment by Mogball** [comment]
Ah, it prints `vector<i32>`!

**Comment by Mogball** [comment]
This can be fixed by moving to `TensorType` for dense arrays.
