### ISSUE TITLE
[ORC] 15.0.0-rc1 building error with Android clang toolchain

### ISSUE THREAD

**Issue by maurossi** [llvm/llvm-project#56867]
When building libLLVM 15.0.0-rc1 I am getting the following building error in libLLVMOrcJIT

```console
external/llvm-project/llvm/lib/ExecutionEngine/Orc/SimpleRemoteEPC.cpp:223:7: error: too many arguments provided to function-like ma
cro invocation
      llvm_unreachable("Invalid opcode");
      ^
external/llvm-project/llvm/include/llvm/Support/ErrorHandling.h:150:50: note: expanded from macro 'llvm_unreachable'
#define llvm_unreachable(msg) LLVM_BUILTIN_TRAP, LLVM_BUILTIN_UNREACHABLE
                                                 ^
external/llvm-project/llvm/include/llvm/Support/Compiler.h:324:35: note: expanded from macro 'LLVM_BUILTIN_UNREACHABLE'
# define LLVM_BUILTIN_UNREACHABLE __builtin_unreachable()
                                  ^
external/llvm-project/llvm/include/llvm/Support/Debug.h:72:9: note: macro 'DEBUG_WITH_TYPE' defined here
#define DEBUG_WITH_TYPE(TYPE, X) do { } while (false)
        ^
external/llvm-project/llvm/lib/ExecutionEngine/Orc/SimpleRemoteEPC.cpp:207:3: note: cannot use initializer list at the beginning of 
a macro argument
  LLVM_DEBUG({
  ^
external/llvm-project/llvm/include/llvm/Support/Debug.h:101:23: note: expanded from macro 'LLVM_DEBUG'
#define LLVM_DEBUG(X) DEBUG_WITH_TYPE(DEBUG_TYPE, X)
                      ^
external/llvm-project/llvm/lib/ExecutionEngine/Orc/SimpleRemoteEPC.cpp:207:3: error: use of undeclared identifier 'DEBUG_WITH_TYPE'
  LLVM_DEBUG({
  ^
external/llvm-project/llvm/include/llvm/Support/Debug.h:101:23: note: expanded from macro 'LLVM_DEBUG'
#define LLVM_DEBUG(X) DEBUG_WITH_TYPE(DEBUG_TYPE, X)
                      ^
2 errors generated.
```

Considering that a similar `LLVM_DEBUG({ ... });` macro expansion at line [106] is building without errors
I have tried the following diff change and I can build.

```diff
diff --git a/llvm/lib/ExecutionEngine/Orc/SimpleRemoteEPC.cpp b/llvm/lib/ExecutionEngine/Orc/SimpleRemoteEPC.cpp
index 47364a92a451..c68372db53d1 100644
--- a/llvm/lib/ExecutionEngine/Orc/SimpleRemoteEPC.cpp
+++ b/llvm/lib/ExecutionEngine/Orc/SimpleRemoteEPC.cpp
@@ -219,8 +219,6 @@ Error SimpleRemoteEPC::sendMessage(SimpleRemoteEPCOpcode OpC, uint64_t SeqNo,
     case SimpleRemoteEPCOpcode::CallWrapper:
       dbgs() << "CallWrapper";
       break;
-    default:
-      llvm_unreachable("Invalid opcode");
     }
     dbgs() << ", seqno = " << SeqNo
            << ", tag-addr = " << formatv("{0:x}", TagAddr.getValue())
```

Could you please add this issue to LLVM 15.0.0 Release Milestone? 
Could you please check if my proposal to remove `default:` case is acceptable? 
In any case I am available to perform Android build tests with any proposed patch

[106] https://github.com/llvm/llvm-project/blob/release/15.x/llvm/lib/ExecutionEngine/Orc/SimpleRemoteEPC.cpp#L106

**Comment by sunho** [comment]
Since this is wihtin LLVM_DEBUG, I think it makes sense to make it an assert.

**Comment by sunho** [comment]
Candidate patch: https://reviews.llvm.org/D130950
Could you check if this works?

**Comment by maurossi** [comment]
> Candidate patch: https://reviews.llvm.org/D130950
> Could you check if this works?

The patch [D130950](https://reviews.llvm.org/D130950) fixes the Android build, thank you

**Comment by lhames** [comment]
What clang version is the Android toolchain using? We can use the workaround, but does this need to be fixed in clang?

**Comment by lhames** [comment]
(We can use the workaround _if needed_ I mean, but I'd like to understand why this is happening first, and why it's suddenly happening now)

**Comment by lhames** [comment]
@maurossi Can you confirm which compiler and version is generating the error above?

**Comment by maurossi** [comment]
The building error is happening with the all the following clang versions:

clang-r416183b1 (clang 12.0.7) bundled with Android S sources
clang-r383902b1 (clang 11.0.2) bundled with Android R sources
clang-r353983c1 (clang 9.0.3)  bundled with Android Q sources

So it is affecting the build with all Android release still in active development.

**Comment by lhames** [comment]
@maurossi This code was in LLVM 14.0.0 too. Was that not built with the Android toolchain? (Is building LLVM with the Android toolchain a new effort?)

Will there be a buildbot added for this? My concern is that if we apply the workaround to the development branch it's going to get changed back at some point by someone making style edits.

**Comment by maurossi** [comment]
> @maurossi This code was in LLVM 14.0.0 too. Was that not built with the Android toolchain?

LLVM 14.0.0 is builing, but LLVM 15.0.0 has changes in `llvm/include/llvm/Support)/ErrorHandling.h` from 6316129 to 734b8ea which are all involving `llvm_unreachable()`

(https://github.com/llvm/llvm-project/commits/release/15.x/llvm/include/llvm/Support/ErrorHandling.h)

> Is building LLVM with the Android toolchain a new effort?

Not new for AOSP and not new for me, regarding me I've been doing it at each new LLVM release to be able to test mesa build for Android and to test radeonsi/radv drivers with latest version of LLVM during the LLVM release cycle.

> Will there be a buildbot added for this?

Not from my side, because once Android build is fixed for LLVM 15.0.0, my next effort will be only at LLVM 16.0.0 release cycle

> My concern is that if we apply the workaround to the development branch it's going to get changed back at some point by someone making style edits.

Then it is useful to investigate why the changes in `llvm/include/llvm/Support)/ErrorHandling.h` are causing the building error with all clang versions used in active development Android release branches

**Comment by weliveindetail** [comment]
> Will there be a buildbot added for this? My concern is that if we apply the workaround to the development branch it's going to get changed back at some point by someone making style edits.

Agree, especially since the [comment](https://github.com/llvm/llvm-project/commit/734b8eadd7d364d5d8162ba6f43539be3d7850aa#diff-dc48771de64a83a52e8506a56415a4835292e1b114865462142cb6259f3b5089R139-R141) explicitly states that `assert` is not the right way to go here.

**Comment by weliveindetail** [comment]
My guess is that, what we see here is the same issue that can break C++11 braced initialization in macros.

The preprocessor doesn't respect braces as a grouping operator and thus it considers `MACRO(Type{Arg1, Arg2})` as two arguments to the MACRO: `Type{Arg1` and `Arg2}`. That would trigger the `too many arguments provided to function-like macro invocation` error.

Why is it new? In recent releases `llvm_unreachable(msg)` always expanded to a single term, but since https://reviews.llvm.org/D122170 it can expand to `LLVM_BUILTIN_TRAP, LLVM_BUILTIN_UNREACHABLE`. And here is the comma that might cause the preprocessor to bail out from our multi-level expansion.

Maybe we didn't see it so far, because most of us build with the default `LLVM_UNREACHABLE_OPTIMIZE=ON`?

I didn't manage to reproduce it on my machine quickly, but if the guess is correct, then we should probably wrap `llvm_unreachable` in something like `do {} while(false)`:

```diff
--- a/llvm/include/llvm/Support/ErrorHandling.h
+++ b/llvm/include/llvm/Support/ErrorHandling.h
@@ -147,7 +147,8 @@ llvm_unreachable_internal(const char *msg = nullptr, const char *file = nullptr,
 #elif LLVM_UNREACHABLE_OPTIMIZE
 #define llvm_unreachable(msg) LLVM_BUILTIN_UNREACHABLE
 #else
-#define llvm_unreachable(msg) LLVM_BUILTIN_TRAP, LLVM_BUILTIN_UNREACHABLE
+#define llvm_unreachable(msg) \
+  do { LLVM_BUILTIN_TRAP; LLVM_BUILTIN_UNREACHABLE; } while (false)
 #endif
 
 #endif
```

@maurossi Can you check if that fixes your build?
@joker-eph What do you think? Did you see anything similar since D122170 landed?

**Comment by maurossi** [comment]
> @maurossi Can you check if that fixes your build?

the diff mentioned in https://github.com/llvm/llvm-project/issues/56867#issuecomment-1205190498 solves the buidling error with Android

**Comment by weliveindetail** [comment]
Reproduced it on my system and posted the patch here: https://reviews.llvm.org/D131337

**Comment by weliveindetail** [comment]
Landed in mainline with https://reviews.llvm.org/rG7a66fe1075cfc7568554aeea9c40997dfb581979
Let's wait a bit for the bots to digest it and then cherry-pick to the release branch.
