### ISSUE TITLE
Compiler crash with LLVM15 when parsing some omp constructs

### ISSUE THREAD

**Issue by mgabka** [llvm/llvm-project#56884]
I noticed that LLVM15 based clang crashes when compiling a simple code:

```cpp
class A {
  void a() {
    #pragma omp parallel
    a(b);
  }
};
```

When compiler with assertions is used, I am seeing an assertion failure from: 
```console
llvm-project/clang/lib/Sema/SemaOpenMP.cpp:1229: const clang::ValueDecl* getCanonicalDecl(const clang::ValueDecl*): Assertion `FD' failed.
```

a bit of bisecting pointed me to a commit https://reviews.llvm.org/D127803.

When I revert it, clang correctly reports error: `error: use of undeclared identifier 'b'`.

**Comment by jyu2-git** [comment]
Fix in https://reviews.llvm.org/D131024
