### ISSUE TITLE
support %b and %B from WG14 N2630 in format string checking

### ISSUE THREAD

**Issue by enh-google** [llvm/llvm-project#56885]
glibc already added `%b` and `%B` (and apparently GCC knows about this), and i'm adding them to bionic https://android-review.googlesource.com/c/platform/bionic/+/2169037, but needed to use `#pragma` to shut clang up for the tests.

one interesting gnarl here is that for Android whether `%b`/`%B` are allowed or not will depend on the target API level. (similar should be true for `%m` which went into API level 29, but no-one's ever complained that clang doesn't know that, so it probably doesn't matter?)

**Comment by MaskRay** [comment]
printf: https://reviews.llvm.org/D131057

scanf is not done. Fortify source is not done.
