### ISSUE TITLE
Backport "[OpenMP] Fix warnings about unused expressions when OMPT_LOOP_DISPATCH is a  no-op. NFC." to 15.x

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#56898]
I pushed this commit to the main branch without review, as I considered the fix trivial, so there's no reviewers to auto-add to approve the backport, but CC @JonChesterfield @AndreyChurbanov @jdoerfert for backport approval.

**Comment by tru** [comment]
LGTM.

**Comment by mstorsjo** [comment]
> LGTM.

Can you merge the PR, and/or make an approval on the backport PR, or what's necessary here?
