### ISSUE TITLE
Clang C++20 Feature: P1857R3 - Modules Dependency Discovery

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#56917]
id: P1857R3
paper: https://wg21.link/p1857r3
not implemented

**Comment by JVApen** [comment]
Duplicate of https://github.com/llvm/llvm-project/issues/54047 ?

**Comment by ChuanqiXu9** [comment]
> Duplicate of #54047 ?

Yes, this is duplicated.
