### ISSUE TITLE
Need to finish LLVMContextification

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#5692]
|  |  |
| --- | --- |
| Bugzilla Link | [5320](https://llvm.org/bz5320) |
| Version | 1.0 |
| OS | All |
| CC | @asl |

## Extended Description 
LLVM is still using a couple of global variables:

1. TargetOptions.h still needs to go away.
2. lib/Target/X86/X86CodeEmitter.cpp and lib/CodeGen/PseudoSourceValue.cpp are still using getGlobalContext.

-Chris

**Comment by gwelymernans** [comment]
Is this still an issue?

**Comment by lattner** [comment]
This is done, thanks!
