### ISSUE TITLE
ld64.lld: Provide workaround for invalid LC_LINKER_OPTIONs

### ISSUE THREAD

**Issue by keith** [llvm/llvm-project#56939]
ld64 has a somewhat surprising feature where it ignores invalid frameworks / libraries included by `LC_LINKER_OPTION`s: https://github.com/keith/ld64/blob/eddf3fd275669887e70392a1f7d8355222fa295e/src/ld/InputFiles.cpp#L716-L717 unless the entire link fails, in which case it prints warnings about them.

Unfortunately this case exists in the wild because this logic hides these issues, then with lld it fails to link. Ideally users would fix the cases they encounter, but that can be difficult when they don't control the problematic code.

I'm not sure if we should implement the exact version of this that ld64 does, but I think we should at least implement some workaround, as this is a hard blocker for folks to even test lld when they hit it. We could potentially add a flag such as `--ignore-autolinked-framework Foo` for this case.

Also worth noting ld64 has a related flag `-ignore_auto_link` (which lld doesn't currently implement) which ignores _all_ autolink directives. The practical problem with this is that if the code being linked includes Swift you'd have to manually specify some internal libraries like SwiftONoneSupport, which is probably a bit too much work for most folks.

**Comment by nico** [comment]
Did you file a https://feedbackassistant.apple.com/ report about the ld64 behavior? That seems like something ld64 should fix (…with an opt-out flag for existing, broken, software).

(We should have some workaround too of course, but long-term this looks like something ld64 should be stricter about.)

**Comment by keith** [comment]
I brought it up off-hand at LLVM conf last year and it was mentioned that this behavior was required for Apple in general. So I'm not sure it is seen as a bug

**Comment by keith** [comment]
I filed FB11666905 and submitted https://reviews.llvm.org/D135530
