### ISSUE TITLE
[question] Clang 16 default cpp std

### ISSUE THREAD

**Issue by paulocoutinhox** [llvm/llvm-project#56946]
Hi,

What is the default cpp std in clang 16?

Still gnu++14?

Thanks.

**Comment by MaskRay** [comment]
We have standard defaults for C++ and ObjC++. Not familiar with ObjC++ and whether it prefers to stay the same as C++, but  changing the default for C++ makes sense. And, Apple's recent DriverKit support defaults to gnu++17.

I have actually played with changing the default, but a dozen tests need inspection whether they should pin to `-std=c++14` or just condition compiling some C++17 deprecated code to suppress warnings.

**Comment by MaskRay** [comment]
* https://reviews.llvm.org/D131464 `[test] Make tests pass regardless of gnu++14/gnu++17 default`
* https://reviews.llvm.org/D131465 `C++/ObjC++: switch to gnu++17 as the default dialect`

**Comment by fhahn** [comment]
Look like this can be closed. For questions, please consider [https://discourse.llvm.org](https://discourse.llvm.org/t/c-objc-switch-to-gnu-17-as-the-default-dialect/64360)

**Comment by paulocoutinhox** [comment]
This is true?

https://www.phoronix.com/news/LLVM-Clang-16-Default-GNU17
