### ISSUE TITLE
Absolute value of negative maximum in an array becomes 0 at -O2

### ISSUE THREAD

**Issue by Ehu1** [llvm/llvm-project#56947]
When compiling this source code

```c
    long long  a[2]={-9223372036854775807, -9223372036854775808};
    for(int i=0;i<2;i++)
    {
        long long int tmp = a[i] >> 63;
        long long int tmp1 = a[i] ^ tmp;
        long long int ret = tmp1 - tmp;
        printf("%lld\n", ret);
    }
```

With `-O2 -target x86_64-linux`, clang12.0.1 generates the following IR (only showing relevant part)

```llvm
; Function Attrs: nofree nounwind uwtable
define dso_local i32 @main() local_unnamed_addr #0 {
  %1 = tail call i32 (i8*, ...) @printf(i8* nonnull dereferenceable(1) getelementptr inbounds ([6 x i8], [6 x i8]* @.str, i64 0, i64 0), i64 9223372036854775807)
  %2 = tail call i32 (i8*, ...) @printf(i8* nonnull dereferenceable(1) getelementptr inbounds ([6 x i8], [6 x i8]* @.str, i64 0, i64 0), i64 undef)
  ret i32 0
}
```

With `-O2 -target x86_64-linux`, clang10.0.0

```llvm
; Function Attrs: nofree nounwind
define dso_local i32 @main() local_unnamed_addr #0 {
  %1 = tail call i32 (i8*, ...) @printf(i8* nonnull dereferenceable(1) getelementptr inbounds ([6 x i8], [6 x i8]* @.str, i64 0, i64 0), i64 9223372036854775807)
  %2 = tail call i32 (i8*, ...) @printf(i8* nonnull dereferenceable(1) getelementptr inbounds ([6 x i8], [6 x i8]* @.str, i64 0, i64 0), i64 -9223372036854775808)
  ret i32 0
}
```

With LLVM12.0.1, this program gives a correct result at `-O0`, but at `-O2` the value of negative maximum becomes 0.

```console
$ clang test2.c 
$ ./a.out 
9223372036854775807
-9223372036854775808
$ clang test2.c -O2
$ ./a.out 
9223372036854775807
0
```

Does not reproduce with LLVM10.0.0:

```console
$ clang test2.c
$ ./a.out 
9223372036854775807
-9223372036854775808
$ clang test2.c -O2
$ ./a.out 
9223372036854775807
-9223372036854775808
```

**Comment by topperc** [comment]
This line has undefined behavior `long long int ret = tmp1 - tmp;` due to integer overflow.

**Comment by Ehu1** [comment]
Using the ABS function causes the same problem


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "llvm/llvm-project"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月5日(星期五) 下午2:29
***@***.***&gt;;
抄送:&nbsp;"傻喵、 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [llvm/llvm-project] Absolute value of negative maximum in an array becomes 0 at -O2 (Issue #56947)





 
This line has undefined behavior long long int ret = tmp1 - tmp; due to integer overflow.

**Comment by topperc** [comment]
> Using the ABS function causes the same problem
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "llvm/llvm-project" ***@***.***&gt;; 发送时间:&nbsp;2022年8月5日(星期五) 下午2:29 ***@***.***&gt;; 抄送:&nbsp;"傻喵、 ***@***.******@***.***&gt;; 主题:&nbsp;Re: [llvm/llvm-project] Absolute value of negative maximum in an array becomes 0 at -O2 (Issue #56947) This line has undefined behavior long long int ret = tmp1 - tmp; due to integer overflow. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

From  https://en.cppreference.com/w/cpp/numeric/math/abs "Computes the absolute value of an integer number. The behavior is undefined if the result cannot be represented by the return type."

Your original code can be fixed by making `tmp` and `tmp1` be `unsigned long long`

**Comment by Ehu1** [comment]
Thank you for the clues all.&nbsp;
