### ISSUE TITLE
fld1 is not generated

### ISSUE THREAD

**Issue by pmor13** [llvm/llvm-project#56951]
This code:
```
float f(void)
{
    return 1.0f;
}
```
leads to (`-O3`):
```
.LCPI0_0:
        .long   0x3f800000                      # float 1
f:                                      # @f
        movss   xmm0, dword ptr [rip + .LCPI0_0] # xmm0 = mem[0],zero,zero,zero
        ret
```
while it can be:
```
f:                                      # @f
        fld1
        ret
```

Documentation: https://www.felixcloutier.com/x86/fld1:fldl2t:fldl2e:fldpi:fldlg2:fldln2:fldz.

Any ideas / thoughts / comments?

**Comment by phoebewang** [comment]
It is an ABI problem. x86_64 always use SSE registers in arguments passing and returning. `fld1` is a x87 instruction which uses FP stack. Only 32-bits target uses them for arguments.

**Comment by pmor13** [comment]
@phoebewang Thanks! Indeed, `-m32` leads to `fld1`.
