### ISSUE TITLE
Compiler-RT needs crtbegin/crtend for linux/solaris/others.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5695]
|  |  |
| --- | --- |
| Bugzilla Link | [5323](https://llvm.org/bz5323) |
| Version | unspecified |
| OS | Solaris |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@vitalybuka |

## Extended Description 
We have a inital version already in progress, which can be found here:
http://hg.kaworu.ch/crt/summary

Best Regards,
Edward.

**Comment by philnik777** [comment]
Fixed by c8be6e6.
