### ISSUE TITLE
LLVM 15.0.0-rc1: compiler_rt does not build on older version of macOS

### ISSUE THREAD

**Issue by debohman** [llvm/llvm-project#56960]
I am running macOS 10.12.6 on an older machine. The issue is that:

```
TARGET_OS_DRIVERKIT
```
is not defined in `/usr/include/TargetConditionals.h`.

I worked around the problem in the header file:

```h
#define TARGET_OS_DRIVERKIT         0
```

This issue is new in llvm-15.0.0.

**Comment by keith** [comment]
To be clear is the error because of `-Wundef`? If so this should fix it as well https://reviews.llvm.org/D131288

**Comment by debohman** [comment]
Yes.

**Comment by debohman** [comment]
I have verified the fix.

**Comment by keith** [comment]
reopening until cherry pick is figured out
