### ISSUE TITLE
[mlir:llvm] `LLVM::ConstantOp` allows mismatched constant value

### ISSUE THREAD

**Issue by Mogball** [llvm/llvm-project#56962]
These are valid instances of `LLVM::ConstantOp` in MLIR:

```llvm
%cst0 = llvm.mlir.constant(1 : i32) : f64
%cst1 = llvm.mlir.constant(1.0 : f64) : f32
```

But they both fail to export. The former triggers an assert `isa<FloatAttr>` and the latter fails to export due to mismatched float size.

**Comment by Mogball** [comment]
awesome! thanks so much!

**Comment by rikhuijzer** [comment]
Thanks. Note that credits should go for a large extend to @joker-eph! Thanks to him reviewing I can keep learning and moving
