### ISSUE TITLE
ld: error: SHF_MERGE section size (X) must be a multiple of sh_entsize (8)

### ISSUE THREAD

**Issue by brad0** [llvm/llvm-project#56979]
Trying to build some code with the CompCert (3.10) compiler and being built with Clang 13.0.0 I am seeing errors like the following with LLD 13.0.0, this does not happen when built with our ports-gcc (GCC 8.4.0)..

```
../../ccomp -Wl,-z,notext -stdlib ../../runtime -dc -dclight -dasm -o knucleotide.compcert knucleotide.c -lm
ld: error: /tmp/compcerta394d2.o:(.rodata.cst8): SHF_MERGE section size (4) must be a multiple of sh_entsize (8)
```

```
../../ccomp -Wl,-z,notext -stdlib ../../runtime -dparse -dc -dclight -dasm -fall -DARCH_x86 -DMODEL_64 -o floats.compcert floats.c -lm
ld: error: /tmp/compcert71ea76.o:(.rodata.cst8): SHF_MERGE section size (260) must be a multiple of sh_entsize (8)
```

I came across the following, but I was not sure if this is an issue with Clang / lld or something that needs to be fixed with CompCert.

https://reviews.llvm.org/D77368

**Comment by MaskRay** [comment]
CompCert needs to be fixed. sh_entsize%sh_entsize != 0 means CompCert emitted object files break the generic ABI requirement "... hold a table of fixed-size entries".

**Comment by brad0** [comment]
https://github.com/AbsInt/CompCert/issues/447

Opened a ticket. A diff was posted that appears to resolve the issue.
