### ISSUE TITLE
LLVM 15.0.0-rc1: CMake Error at cmake/modules/CMakeLists.txt

### ISSUE THREAD

**Issue by fafryd1125** [llvm/llvm-project#56971]
```console
CMake Error at cmake/modules/CMakeLists.txt:1 (include):
  include could not find requested file:

    GNUInstallPackageDir


CMake Error at cmake/modules/CMakeLists.txt:2 (include):
  include could not find requested file:

    ExtendPath


CMake Error at cmake/modules/CMakeLists.txt:4 (include):
  include could not find requested file:

    FindPrefixFromConfig


CMake Error at cmake/modules/CMakeLists.txt:119 (find_prefix_from_config):
  Unknown CMake command "find_prefix_from_config".


-- Configuring incomplete, errors occurred!
See also "/build/llvm/src/llvm-15.0.0rc1.src/build/CMakeFiles/CMakeOutput.log".
See also "/build/llvm/src/llvm-15.0.0rc1.src/build/CMakeFiles/CMakeError.log".
```

The error occurs with `llvm-15.0.0rc1.src.tar.xz`

**Comment by devnexen** [comment]
I can reproduce easily, not sure the `GNUInstallPackageDir` plugin exists but `GNUInstallDirs` perharps ?

**Comment by nikic** [comment]
You also need the files from [cmake-15.0.0rc1.src.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.0-rc1/cmake-15.0.0rc1.src.tar.xz).

**Comment by devnexen** [comment]
Ah right, thought you would find those on LLVM source directly eventually.

**Comment by fafryd1125** [comment]
> You also need the files from [cmake-15.0.0rc1.src.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.0-rc1/cmake-15.0.0rc1.src.tar.xz).

Thanks for the info.

**Comment by arsenm** [comment]
Old release build issue

**Comment by ashwani-r** [comment]
I am hitting this issue on llvm-16.0.0 build.
Is there a workaround/fix for this?

**Comment by EugeneZelenko** [comment]
@ashwani-r: Could you please try 18 or `main` branch?

**Comment by ashwani-r** [comment]
I tried 3 different versions (14.0.0, 16.0.0, 18.0.0). All of them failed with same error.

I missed this comment above (https://github.com/llvm/llvm-project/issues/56971#issuecomment-1207180969) that notes pre-requisite requirement to copy modules from cmake to corresponding llvm folder to get around this error.
After copying required modules from corresponding cmake source, the build proceeded ahead.

This is a bit tedious way to deal with such errors. Although it is documented in cmake README,

>  These are CMake modules to be shared between LLVM projects strictly at build
>  time. In other words, they must not be included from an installed CMake module,
>  such as the ``Add*.cmake`` ones. Modules that are reachable from installed
>  modules should instead go in ``${project}/cmake/modules`` of the most upstream
>  project that uses them.
> 

one requires to go through llvm existing issues to arrive at the final solution.

**Comment by mati865** [comment]
Please do note past LLVM releases are not supported and this issue was properly addressed in recent versions.

**Comment by ashwani-r** [comment]
@mati865,
I apologise, somehow I missed your update. Could you please point me to the change that addressed this issue in recent versions? Or point to the recent versions that has the fix?

**Comment by mati865** [comment]
@ashwani-r if you look at https://llvm.org/docs/GettingStarted.html#stand-alone-builds, there is a table with required tarballs: 
![image](https://github.com/user-attachments/assets/c9af5132-67c3-444f-bfc5-af14e448c0dc)
