### ISSUE TITLE
Feature request: allow teaching llvm that coroutines can only be destroyed when done

### ISSUE THREAD

**Issue by jacobsa** [llvm/llvm-project#56980]
The following code contains two things:

* A basic coroutine task type that can be awaited from other coroutines returning that task type. It is not possible to do anything with the task except await it. In particular it's not possible to destroy the task's coroutine early: **coroutines are always destroyed only when they are done**.

* A coroutine called `Foo` returning that task type that has several different suspend points, each with a different instance of `GlobalSetter` alive. When `GlobalSetter` is destroyed, it sets `some_global` in a way that can be seen in assembly code.

```c++
#include <coroutine>

class MyTask{
 public:
  struct promise_type {
    MyTask get_return_object() { return MyTask(std::coroutine_handle<promise_type>::from_promise(*this)); }
    std::suspend_always initial_suspend() { return {}; }

    void unhandled_exception();

    void return_void() {} 

    auto await_transform(MyTask task) {
      struct Awaiter {
        bool await_ready() { return false; }
        std::coroutine_handle<promise_type> await_suspend(std::coroutine_handle<promise_type> h) {
          caller.resume_when_done = h;
          return std::coroutine_handle<promise_type>::from_promise(callee);
        }

        void await_resume() {
          std::coroutine_handle<promise_type>::from_promise(callee).destroy();
        }

        promise_type& caller;
        promise_type& callee;
      };

      return Awaiter{*this, task.handle_.promise()};
    }
    
    auto final_suspend() noexcept {
      struct Awaiter {
        bool await_ready() noexcept { return false; }
        std::coroutine_handle<promise_type> await_suspend(std::coroutine_handle<promise_type> h) noexcept {
          return to_resume;
        }

        void await_resume() noexcept;

        std::coroutine_handle<promise_type> to_resume;
      };

      return Awaiter{resume_when_done};
    }

    // The coroutine to resume when we're done.
    std::coroutine_handle<promise_type> resume_when_done;
  };


 private:
  explicit MyTask(const std::coroutine_handle<promise_type> handle)
      : handle_(handle) {}

  // A handle for the coroutine that returned this task. This is not
  // revealed to the user: it can only be used to await the task.
  const std::coroutine_handle<promise_type> handle_;
};

int some_global;

// A type whose destructor takes an action that's easy to see in the output
// assembly code.
struct GlobalSetter {
  int value;

  GlobalSetter(int value) : value(value) {}
  ~GlobalSetter() { some_global = value; }
};

MyTask __attribute__((noinline)) Qux() { co_return; }

MyTask Foo() {
  {
    GlobalSetter gs(0);
    co_await Qux();
  }

  {
    GlobalSetter gs(1);
    co_await Qux();
  }

  {
    GlobalSetter gs(2);
    co_await Qux();
  }

  {
    GlobalSetter gs(3);
    co_await Qux();
  }

  {
    GlobalSetter gs(4);
    co_await Qux();
  }

  {
    GlobalSetter gs(5);
    co_await Qux();
  }

  {
    GlobalSetter gs(6);
    co_await Qux();
  }
}
```

Because it's not possible to destroy the frame for `Foo` until it is completely finished, the cleanup code in theory can be trivial: there is no need to worry about running `~GlobalSetter`, because that will always have already run in the coroutine body itself. But when compiled with `-std=c++20 -O2 -fno-exceptions`, clang is unable to see this and generates a bunch of dead code within `Foo.destroy` ([compiler explorer](https://godbolt.org/z/9K8eKE9Kh)):

```asm
Foo() [clone .destroy]:                        # @Foo() [clone .destroy]
        cmp     qword ptr [rdi], 0
        je      .LBB5_9
        movzx   ecx, byte ptr [rdi + 96]
        xor     eax, eax
        lea     rdx, [rip + .LJTI5_0]
        movsxd  rcx, dword ptr [rdx + 4*rcx]
        add     rcx, rdx
        jmp     rcx
.LBB5_2:
        mov     eax, 1
        jmp     .LBB5_8
.LBB5_3:
        mov     eax, 2
        jmp     .LBB5_8
.LBB5_4:
        mov     eax, 3
        jmp     .LBB5_8
.LBB5_5:
        mov     eax, 4
        jmp     .LBB5_8
.LBB5_6:
        mov     eax, 5
        jmp     .LBB5_8
.LBB5_7:
        mov     eax, 6
.LBB5_8:
        mov     dword ptr [rip + some_global], eax
.LBB5_9:
        jmp     operator delete(void*)@PLT                      # TAILCALL
.LJTI5_0:
        .long   .LBB5_9-.LJTI5_0
        .long   .LBB5_8-.LJTI5_0
        .long   .LBB5_2-.LJTI5_0
        .long   .LBB5_3-.LJTI5_0
        .long   .LBB5_4-.LJTI5_0
        .long   .LBB5_5-.LJTI5_0
        .long   .LBB5_6-.LJTI5_0
        .long   .LBB5_7-.LJTI5_0
```

In theory **this should just be a single instruction**: a tail call to `operator delete`. Instead we get generated code that duplicates all of the logic for destroying the `GlobalSetter` objects that is also in `Foo.resume`.

This is a feature request to **add some facility to teach llvm that generating code for destroying local variables is unnecessary in the coroutine destroy function**. I thought perhaps adding a `__builtin_unreachable` section in the promise's destructor that you hit when the promise's handle is not done might work, but [no such luck](https://godbolt.org/z/jf5K78hn8).

**Comment by ChuanqiXu9** [comment]
Maybe I need think about your proposal. But my first thought is that we can't do this. From the compiler side, the compiler can't know the coroutine is going to be destroyed when the coroutine is done. The language spec only says the coroutine need to be suspended when we call destroy(). 

I understood your proposal wants to bring new more information for the compiler. It is a relatively common request. And generally we do this by attributes like `[[likely]]`.

**Comment by jacobsa** [comment]
Yeah, the idea is that this would be an extension, or just a way to provide an optimizer hint like with `__ __builtin_unreachable`. It seems like a waste to generate duplicate destruction code for every single coroutine in a binary when the code is 100% dead. That is a binary size issue, and then also we waste CPU time on the always-taken branch in the destroy function, setting up the stack frame, etc.

**Comment by ChuanqiXu9** [comment]
> 

Generally, we don't analyze the code in other methods. Or in another word, we won't look at the implementation of the  destructor and decide if we're going to do some optimization. This isn't something we would do. It may be possible to add an attribute. It looks a good extension although it looks like we can't bring it to std since std don't mention any word about it.

**Comment by ChuanqiXu9** [comment]
Sent https://reviews.llvm.org/D134010

**Comment by jacobsa** [comment]
Nice, thank you @ChuanqiXu9!

**Comment by ChuanqiXu9** [comment]
> [Coroutines] Introduce [[clang::coro_only_destroy_when_complete]] (

You're welcome. The idea is valuable. More optimization oppoutinies are wanted : )
