### ISSUE TITLE
clang-tidy-14: NOLINTBEGIN doesn't propagate to included files

### ISSUE THREAD

**Issue by tsdgeos** [llvm/llvm-project#56983]
I would like to have an option so that `NOLINT` propagates to included files so i can do

```cpp
... here the code of my cpp file ...

// NOLINTBEGIN(readability-braces-around-statements)
#include "test-poppler-qt6.moc"
// NOLINTEND(readability-braces-around-statements)

```
Which i need given the moc file is autogenerated by some third party tool and i have no control over it.

**Comment by PiotrZSL** [comment]
Use line --line-filter or --header-filter or include mock as system header to ignore issues from it.
NOLINT's were not designed to cross file boundary.
