### ISSUE TITLE
Clang template template arguments: aliases not desugared

### ISSUE THREAD

**Issue by drec357** [llvm/llvm-project#56984]
```cpp
template<typename> class A;
template<typename T> using B = A<T>;

template<template<typename> class T>
int varTemp = 0;

int main() {
  varTemp<A> += 4;
  varTemp<B> += 6;
  return varTemp <A>;
}
```

clang returns 4, gcc returns 10.  I.e. clang is forming a separate instantiation for the alias argument vs. its underlying class template argument.

**Comment by inclyc** [comment]
https://godbolt.org/z/3TTj6vY8M

**Comment by shafik** [comment]
Note MSVC and icc seem to agree with clang: https://godbolt.org/z/dPEx34M3K

I think [Defect Report 1286](https://open-std.org/JTC1/SC22/WG21/docs/cwg_active.html#1286) applies but it looks like it is still open.

**Comment by drec357** [comment]
> I think [Defect Report 1286](https://open-std.org/JTC1/SC22/WG21/docs/cwg_active.html#1286) applies

Yes that seems right, thanks.

GCC seems to treat them as the same if the alias templates are all "simple", somehow defined, but not if they have any sort of complexity.  E.g.
```
template<typename T> using Identity = T;
template<typename T> using C = A<Identity<T>>;

template<typename T, typename> using First = T;
template<typename T> using D = A<First<T, void>>;
```
GCC treats `varTemp<A>` the same as `varTemp<B>` and `varTemp<C>`, but different from `varTemp<D>`.
Given the arguable arbitrariness of these distinctions, it is reasonable to simply treat them all as different, particularly given that that's what all the other compilers do.
