### ISSUE TITLE
ubuntu bionic: compiler-rt fails to build with `no member named 'string_view' in namespace 'std'`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#56998]
```console
"/build/llvm-toolchain-snapshot-16~++20220808091537+061e0189a3da/build-llvm/./bin/clang++" --target=aarch64-unknown-linux-gnu -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I"/build/llvm-toolchain-snapshot-16~++20220808091537+061e0189a3da/compiler-rt/lib/orc/.." -I"/build/llvm-toolchain-snapshot-16~++20220808091537+061e0189a3da/compiler-rt/lib/orc/../../include" -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/build/llvm-toolchain-snapshot-16~++20220808091537+061e0189a3da/build-llvm/runtimes/runtimes-bins=build-llvm/runtimes/runtimes-bins -ffile-prefix-map=/build/llvm-toolchain-snapshot-16~++20220808091537+061e0189a3da/= -no-canonical-prefixes -Wall -std=c++14 -Wno-unused-parameter -O3 -DNDEBUG -march=armv8-a -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions "-I/build/llvm-toolchain-snapshot-16~++20220808091537+061e0189a3da/build-llvm/include" "-I/build/llvm-toolchain-snapshot-16~++20220808091537+061e0189a3da/llvm/include" -MD -MT compiler-rt/lib/orc/CMakeFiles/RTOrc.aarch64.dir/macho_platform.cpp.o -MF compiler-rt/lib/orc/CMakeFiles/RTOrc.aarch64.dir/macho_platform.cpp.o.d -o compiler-rt/lib/orc/CMakeFiles/RTOrc.aarch64.dir/macho_platform.cpp.o -c '/build/llvm-toolchain-snapshot-16~++20220808091537+061e0189a3da/compiler-rt/lib/orc/macho_platform.cpp'
In file included from /build/llvm-toolchain-snapshot-16~++20220808091537+061e0189a3da/compiler-rt/lib/orc/macho_platform.cpp:13:
In file included from /build/llvm-toolchain-snapshot-16~++20220808091537+061e0189a3da/compiler-rt/lib/orc/macho_platform.h:17:
In file included from /build/llvm-toolchain-snapshot-16~++20220808091537+061e0189a3da/compiler-rt/lib/orc/executor_address.h:20:
/build/llvm-toolchain-snapshot-16~++20220808091537+061e0189a3da/compiler-rt/lib/orc/simple_packed_serialization.h:403:58: error: no member named 'string_view' in namespace 'std'
template <> class SPSSerializationTraits<SPSString, std::string_view> {
                                                    ~~~~~^
/build/llvm-toolchain-snapshot-16~++20220808091537+061e0189a3da/compiler-rt/lib/orc/macho_platform.cpp:178:34: error: no member named 'string_view' in namespace 'std'
      std::vector<std::pair<std::string_view, ExecutorAddrRange>> Secs);
                            ~~~~~^
```

**Comment by nikic** [comment]
Did you clear your cmake cache? You are building with `-std=c++14`, while `-std=c++17` is required now.

**Comment by sylvestre** [comment]
Yeah, I see that with apt.llvm.org, all builds are in new environment.
I guess the libstdc++ on bionic doesn't have string_view ?

**Comment by nikic** [comment]
Hm, it's not entirely clear to me whether the new toolchain requirements are supposed to apply to compiler-rt or not. @tru

**Comment by nikic** [comment]
In either case we currently don't seem to set CMAKE_CXX_STANDARD for compiler-rt, so for now we probably shouldn't use any C++17 functionality there (the relevant change here is presumably https://github.com/llvm/llvm-project/commit/1dcff823db9f4dd5c300507f679cdb2494287442 cc @lhames)

**Comment by BertalanD** [comment]
This looks a bit odd: https://github.com/llvm/llvm-project/blob/72017e9b16b737c5bd7c1dd33abff36f368fa724/compiler-rt/CMakeLists.txt#L299

Is there a reason it's done this way instead of using the standard CMake mechanism for setting the version?

**Comment by tru** [comment]
> Hm, it's not entirely clear to me whether the new toolchain requirements are supposed to apply to compiler-rt or not. @tru

I haven't heard any reason from anyone that it shouldn't. Is compiler-rt special in any case that would create problems with a newer C++ standard? I would assume the same toolchain requirement would apply to the whole ecosystem - except maybe libc++ which is a different story.

> In either case we currently don't seem to set CMAKE_CXX_STANDARD for compiler-rt, so for now we probably shouldn't use any C++17 functionality there (the relevant change here is presumably https://github.com/llvm/llvm-project/commit/1dcff823db9f4dd5c300507f679cdb2494287442 cc @lhames)

@MaskRay have just pushed this diff to fix that: https://reviews.llvm.org/D131382

> Is there a reason it's done this way instead of using the standard CMake mechanism for setting the version?

I don't have the context for that. But it seems like this was changed the last time as well: https://github.com/llvm/llvm-project/commit/4d474e078ac729d74aca406d688060c9638dd9f2

**Comment by tru** [comment]
I think this is fixed in `main` now.

**Comment by tru** [comment]
@sylvestre have you retested this? Can I close this issue?

**Comment by sylvestre** [comment]
Yes, many thanks!
