### ISSUE TITLE
[Format] Comparisons interpreted as template argument list

### ISSUE THREAD

**Issue by JohelEGP** [llvm/llvm-project#57004]
No `.clang-format`.

Input and expected output:
```C++
static_assert(ratio{-1, 2} < ratio{-1, 3} == -1 / 2.0 < -1 / 3.0);
static_assert(ratio{-1, 2} < ratio{-1, 3} == -1 / 3.0 > -1 / 2.0);
```

Actual output:
```C++
static_assert(ratio{-1, 2} < ratio{-1, 3} == -1 / 2.0 < -1 / 3.0);
static_assert(ratio{-1, 2}<ratio{-1, 3} == -1 / 3.0> - 1 / 2.0);
```

**Comment by rymiel** [comment]
Patch: https://reviews.llvm.org/D150629

**Comment by rymiel** [comment]
(The above patch simply bans a `<` from becoming a template parameter if it is preceded by a closing brace `}`, @JohelEGP, I believe you are better versed in C++ edge-cases, do you think there are any valid constructs where `}` followed by `<` is an angle bracket instead of an operator?)

**Comment by JohelEGP** [comment]
I confirm there's none. Thank you for this.

**Comment by HazardyKnusperkeks** [comment]
I like how I knew who posted this bug, just from the added test case.
