### ISSUE TITLE
[lld][elf] warn on missing .note.GNU-stack section

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#57009]
Since https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=ba951afb99912da01a6e8434126b8fac7aa75107, GNU ld (BFD) will warn when an ELF object is missing the `.note.GNU-stack` section.

Generally, we'd like code to not have an executable stack. Because some code could rely on that, we need to start migrating codebases to be built without executable stack.

We see this for the Linux kernel for asm sources. We plan to add `-Wa,--noexecstack` to KBUILD. See also:
https://lore.kernel.org/linux-block/CAKwvOdmD10yK0r1H-M2PcnZgy3M0aA9gdkY0BErDOQ+KpBRxVQ@mail.gmail.com/

**Comment by MaskRay** [comment]
This is a wontfix. lld, since its beginning, has taken the stance to ignore input `.note.GNU-stack` and default to `-z noexecstack`.

The GNU ld transition is more complex because it has the traditional tri-state for a long time and some archaic ports (LLVM does not support) may not finish the transition so smoothly. The diagnostic is only meaningful to GNU ld.

**Comment by nickdesaulniers** [comment]
Thanks for the info, will include it in a kernel commit.

> Note: clang uses do not need -Wa,--noexecstack.

Well, if the default `-fuse-ld` is GNU BFD, they _do_ need it to avoid the warning with GNU BFD.  I guess they don't need it when linking with LLD, but it also doesn't hurt.

**Comment by MaskRay** [comment]
I recommend that kernel uses `-z noexecstack` for LDFLAGS and doesn't add `-Wa,--noexecstack`.

`-z noexecstack` supports all linkers. `--no-warn-execstack` is only supported by GNU ld>=2.38 and I am not sure it's valuable enough to be added to ld.lld (new GNU ld option purely for its transition purpose transiting away from a dangerous traditional behavior that ld.lld never supports in the first place).

`-Wa,--noexecstack` is not necessary: if the built relocatable files are destined to be used with ld with `-z noexecstack`, the input `.note.GNU-stack` sections are really redundant. It is difficult if the relocatable files can leak to the outside world where a GNU ld without `-z noexecstack` may be used. But IMO this is not the case for the kernel.
