### ISSUE TITLE
[CMake] check-all target no longer runs runtime tests after D121276

### ISSUE THREAD

**Issue by amy-kwan** [llvm/llvm-project#57018]
From the https://reviews.llvm.org/D121276 revision, it appears that the `check-all` target no longer runs the runtime tests. 

Us on PowerPC have been building `compiler-rt`,`libcxx`, and `libcxxabi` as runtimes, and have to test runtimes separately by doing a secondary `check-runtimes` invocation.  This affects the current community revisions, as well as the LLVM 15.0.0 RC1 tag. 

More elaboration into this issue is available in the following comments:
https://reviews.llvm.org/D121276#3660827
https://reviews.llvm.org/D121276#3680246

**Comment by amy-kwan** [comment]
@petrhosek Is this something you are able to assist us in looking into?

FYI @lei137 @kamaub

**Comment by amy-kwan** [comment]
Ah, I seem to have missed the reply on Discourse: https://discourse.llvm.org/t/15-0-0-rc1-has-been-tagged/64174/25

It appears this issue has been reverted in `main`. I believe the revert was: https://reviews.llvm.org/rGec10ac750a8ad96983d85263323635f3dabe92fd

**Comment by lei137** [comment]
That revert was in May.  I was still seeing this problem on main end of July and posted a comment stating such in D121276.

**Comment by tru** [comment]
Should be fixed by 3a481d4491b7a63008183f0c0fe689bcbb4ec624
