### ISSUE TITLE
[clang-tidy] modernize-use-equals-default should not be applied when it changes semantics

### ISSUE THREAD

**Issue by jcelerier** [llvm/llvm-project#57027]
https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-equals-default.html

e.g. consider:

```cpp
struct Trivial { };
struct NonTrivial { ~NonTrivial() { } };

struct Container 
{
  private:
    union U
    {
      Trivial a;
      NonTrivial b;
      
      U(): a{} { }
      ~U() { }
    };

    U u; 
    int index = 0;

  public:
    ~Container() 
    {
        if(index == 1)
          u.b.~NonTrivial();
    }
};

Container cont;
```

here, modernize-use-equals-default turns this code into `~U() = default;` which then does not compile due to the non-trivial dtor.

**Comment by PiotrZSL** [comment]
No reproduction on trunk, most probably fixed by 083e3a173d9e9d71733e0445e6f4a93e7f918dfa
