### ISSUE TITLE
DCE sometimes fails with depending if statements

### ISSUE THREAD

**Issue by ThomasMayerl** [llvm/llvm-project#57028]
Sometimes, DCE fails when multiple if statements are used. 

For example, LLVM detects that the following if statement always evaluates to false and thus removes the dead code:

```c
#include <stdio.h>
#include <stdbool.h>

void DCEMarker0_();

void f(bool s, bool r, bool c) {
    if (((!s || c && r) && s && !r)) {
        DCEMarker0_();
    }
}
```

In the next snippet, the if statement is used to set a variable. This variable is then used in another if statement. However, LLVM now fails to detect and eliminate the dead code:

```c
#include <stdio.h>
#include <stdbool.h>

void DCEMarker0_();

void f(bool s, bool r, bool c) {
    int intermediate_result = 0;
    if (((!s || c && r) && s && !r)) {
        intermediate_result = 1;
    }
    if (((!s || c && r) && s && !r) || intermediate_result) {
        DCEMarker0_();
    }
}
```

This is actually a regression: 
In LLVM 12 both snippets can be optimised.
In LLVM 13 neither snippet can be optimised.
In LLVM 14 only the top snippet can be optimised.

This can also be seen via the following Compiler Explorer link: https://godbolt.org/z/EzKWjjMn7

**Comment by rotateright** [comment]
This example reduces to the same pattern as #56653, and it would be fixed with the same patch ( https://reviews.llvm.org/D131356 ).

**Comment by rotateright** [comment]
Fixed with:
15e3d869119289991072679f82622072818468e6
