### ISSUE TITLE
is there some high level way for interpreting ELF `dwarf` in lldb?

### ISSUE THREAD

**Issue by Ma-Y** [llvm/llvm-project#57039]
without using `llvm-dwarfdump`, perfered way is using internals of lldb since eventually i want to build a simple C/C++ debugger

something like ` auto dwarf_data_structure = ParseDwarfToHighLevelRepresentation("./a.elf");`

**Comment by dwblaikie** [comment]
APIs in lldb for parsing DWARF are in https://github.com/llvm/llvm-project/tree/main/lldb/source/Plugins/SymbolFile/DWARF

A similar-but-different API for parsing DWARF (that is used to implement `llvm-dwarfdump`) is in https://github.com/llvm/llvm-project/tree/main/llvm/lib/DebugInfo/DWARF

**Comment by fhahn** [comment]
Please use https://discourse.llvm.org for questions.
