### ISSUE TITLE
[libcxx] Thread-safety analysis: shared_timed_mutex is not annotated

### ISSUE THREAD

**Issue by jcelerier** [llvm/llvm-project#57035]
It would be good to be able to assert the threading semantics with it, too

**Comment by aaronpuchert** [comment]
Annotations have been added to `__shared_mutex_base` in https://reviews.llvm.org/D54290, but not `shared_mutex` and `shared_timed_mutex`. Should be easy to fix though.

**Comment by aaronpuchert** [comment]
Proposed fix: https://reviews.llvm.org/D154354.

**Comment by ldionne** [comment]
Fixed by 5b666cf11e7a913fdfd0a65975ff587452635659.
