### ISSUE TITLE
Why does llvm optimize structures with the same structure? How to avoid this optimization?

### ISSUE THREAD

**Issue by tr4v3ler** [llvm/llvm-project#57043]
The source code demo:

```cpp
struct erase_info_user64 einfo64;
```

But the corresponding LLVM IR is as follows:

```llvm
%einfo64 = alloca %struct.exception_table_entry, align 8
```

`erase_info_user64` and `exception_table_entry` have the same structure, but are different variables in the source code:

```cpp
struct erase_info_user64 {
    __u64 start;          
    __u64 length;         
};                        

struct exception_table_entry  
{                             
    unsigned long insn, fixup;
};                            
```

So why does llvm optimize structures with the same structure? How to avoid this optimization? Or is this a bug?

**Comment by Naville** [comment]
I don't think this affects performance and as far as I know this is very intentional?

**Comment by nikic** [comment]
Can you please provide a complete example on godbolt?

**Comment by tr4v3ler** [comment]
> Can you please provide a complete example on godbolt?

I use the [kernel code of MTK](https://drive.google.com/file/d/0B4XwT5D6qkNmLXdNTk93MjU3SWM/view?usp=sharing&resourcekey=0-cb1ceDme5Fi2xugS7nYl7w)，and the relevant compilation commands are as follows:
```shell
# First, you need to compile the kernel completely to generate some intermediate files for subsequent compilation.
cd /path/of/mtk_kernel
source ./env.sh
cd kernel-3.18
mkdir out
make O=out ARCH=arm64 tubads_defconfig
make -j`nproc` O=out ARCH=arm64

# Use llvm 14.0.6 to compile c code into bitcode, and then further optimize and convert it into ll file.
cd out
clang -emit-llvm -g -w -O0 -target arm64 -Wp,-MD,drivers/mtd/.mtdchar.o.d -isystem /path/of/mtk_kernel/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/../lib/gcc/aarch64-linux-android/4.9.x-google/include -I../arch/arm64/include -Iarch/arm64/include/generated -I../include -Iinclude -I../arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I../include/uapi -Iinclude/generated/uapi -include ../include/linux/kconfig.h -I../drivers/mtd -Idrivers/mtd -D__KERNEL__ -mlittle-endian -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -mgeneral-regs-only -fno-pic -Wframe-larger-than=1400 -fno-stack-protector -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DKBUILD_STR(s)=#s -DKBUILD_BASENAME=KBUILD_STR(mtdchar) -DKBUILD_MODNAME=KBUILD_STR(mtd) -c -o mtdchar.bc ../drivers/mtd/mtdchar.c
opt -mem2reg mtd.bc -o mtd.tmp.bc
llvm-dis mtd.tmp.bc -o mtd.tmp.ll
```

**Comment by fhahn** [comment]
> So why does llvm optimize structures with the same structure? How to avoid this optimization? Or is this a bug?

Could you elaborate why you think this optimization is illegal? AFAICT the optimization seems perfectly fine as long as the struct types are structurally equivalent.

**Comment by tr4v3ler** [comment]
> > So why does llvm optimize structures with the same structure? How to avoid this optimization? Or is this a bug?
> 
> Could you elaborate why you think this optimization is illegal? AFAICT the optimization seems perfectly fine as long as the struct types are structurally equivalent.

The type of some variables has changed, which will have an impact on static program analysis.

**Comment by fhahn** [comment]
I don't think type names have any semantic meaning on LLVM IR unfortunately, so I think this is working as expected.

If you have a tool that relies on struct types not being de-duplicated you might be able to extend the LLVM IR linker to have the option to avoid de-duplication.

Please feel free to re-open the issue in case I missed anything.

**Comment by tr4v3ler** [comment]
> I don't think type names have any semantic meaning on LLVM IR unfortunately, so I think this is working as expected.
> 
> If you have a tool that relies on struct types not being de-duplicated you might be able to extend the LLVM IR linker to have the option to avoid de-duplication.
> 
> Please feel free to re-open the issue in case I missed anything.

I find that the original type information is retained in debuginfo, and I can extract the correct type name through debuginfo.

**Comment by dwblaikie** [comment]
There's also TBAA metadata you could use, if that's suitable for your use case.
