### ISSUE TITLE
[OpenMP] image not compatible with RTL

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#57049]
On one of my workstation with ubuntu 20.04, I got almost half of the libomptarget tests failing on nvptx64-nvidia-cuda
since 080022d8ed6c1bd9ba5ece33cfea248f9473e775

LIBOMPTARGET_DEBUG=1 shows
```
Libomptarget --> Image 0x000055dda143d0e8 is NOT compatible with RTL libomptarget.rtl.cuda.so!
```

**Comment by jhuber6** [comment]
That patch made the embedded image contain a special binary blob with some extra information about the image itself. After that we will only use an image if the architecture matches the host's. I'm unsure why this is causing problems for you. It's possible that the compiler is building for the wrong architecture so `libomptarget` is rejecting it. Could you give me some more system information and an example of an offloading application built with your installation? Also you can use `llvm-objdump --offloading` to show the supported architectures in the binary.
