### ISSUE TITLE
SVE C++ Operator missing + and docs backport for LLVM 15

### ISSUE THREAD

**Issue by DavidTruby** [llvm/llvm-project#57051]
/cherry-pick 286d59e
/cherry-pick e4642d7

**Comment by DavidTruby** [comment]
The commits selected in the PR don't match the one I asked for in the comment. Not sure what to do in this situation

**Comment by tstellar** [comment]
/cherry-pick 286d59ef6f7118c8a0600f3d281593700528a5d3 e4642d78a89930720bc84a4775614c45327bc0dc

**Comment by tstellar** [comment]
@DavidTruby How does it look now?

**Comment by DavidTruby** [comment]
Looks better now thanks! There was a mistake in one of these commits that I need to add a fix for though, so adding that below
/cherry-pick 286d59e e4642d7 bbb30bd 13a784f
