### ISSUE TITLE
-fassociative-math optimization issue with clang 13+

### ISSUE THREAD

**Issue by bkaradzic** [llvm/llvm-project#57053]
I ran into optimizer issue (clang 13 and above) where `else` branch partially gets optimized out when compiling with `-fassociative-math -O2` compiler options.

This code

```cpp
		if (bits == 0)
		{
			c0  = 1.0f;
			c6  = 2.0f;
			c8  = 3.0f;
			c10 = 4.0f;
		}
		else
		{
			c0  = _a;
			c6  = 5.0f;
			c8  = 6.0f;
			c10 = 7.0f;
		}
```

Optimizer turns into:

```cpp
		c6  = 5.0f;
		c8  = 6.0f;
		c10 = 7.0f;

		if (bits == 0)
		{
			c0  = 1.0f;
		}
		else
		{
			c0  = _a;
		}
```

The issue occurs with clang 13 and above (tested with 13, 14, 15, 16), but not in clang 12.

Compiler options: `-fassociative-math -O2`

Compiler Explorer: https://godbolt.org/z/9zvfYo3xa

```cpp
	float test(float _a)
	{
		int bits = int(_a);

		float c0, c6, c8, c10;

		if (bits == 0)
		{
			c0  = 1.0f;
			c6  = 2.0f;
			c8  = 3.0f;
			c10 = 4.0f;
		}
		else
		{
			c0  = _a;
			c6  = 5.0f;
			c8  = 6.0f;
			c10 = 7.0f;
		}

		float tmp0   = c10  * _a + c8;
		float tmp1   = tmp0 * _a + c6;
		float result = tmp1 * c0;

		return result;
    }
```

Output for clang 12.0.1:

```asm
.LCPI0_0:
        .long   0x3f800000                      # float 1
.LCPI0_1:
        .long   0x40000000                      # float 2
.LCPI0_2:
        .long   0x40400000                      # float 3
.LCPI0_3:
        .long   0x40800000                      # float 4
.LCPI0_4:
        .long   0x40a00000                      # float 5
.LCPI0_5:
        .long   0x40c00000                      # float 6
.LCPI0_6:
        .long   0x40e00000                      # float 7
test(float):                               # @test(float)
        cvttss2si       eax, xmm0
        test    eax, eax
        je      .LBB0_1
        movss   xmm2, dword ptr [rip + .LCPI0_4] # xmm2 = mem[0],zero,zero,zero
        movss   xmm4, dword ptr [rip + .LCPI0_5] # xmm4 = mem[0],zero,zero,zero
        movss   xmm1, dword ptr [rip + .LCPI0_6] # xmm1 = mem[0],zero,zero,zero
        movaps  xmm3, xmm0
        jmp     .LBB0_3
.LBB0_1:
        movss   xmm3, dword ptr [rip + .LCPI0_0] # xmm3 = mem[0],zero,zero,zero
        movss   xmm2, dword ptr [rip + .LCPI0_1] # xmm2 = mem[0],zero,zero,zero
        movss   xmm4, dword ptr [rip + .LCPI0_2] # xmm4 = mem[0],zero,zero,zero
        movss   xmm1, dword ptr [rip + .LCPI0_3] # xmm1 = mem[0],zero,zero,zero
.LBB0_3:
        mulss   xmm1, xmm0
        addss   xmm1, xmm4
        mulss   xmm1, xmm0
        addss   xmm1, xmm2
        mulss   xmm1, xmm3
        movaps  xmm0, xmm1
        ret
```

Output for clang 14.0.0

```asm
.LCPI0_0:
        .long   0x3f800000                      # float 1
.LCPI0_1:
        .long   0x40e00000                      # float 7
        .long   0x40800000                      # float 4
.LCPI0_2:
        .long   0x40c00000                      # float 6
        .long   0x40400000                      # float 3
.LCPI0_3:
        .long   0x40a00000                      # float 5
        .long   0x40000000                      # float 2
test(float):                               # @test(float)
        cvttss2si       ecx, xmm0
        xor     eax, eax
        test    ecx, ecx
        sete    cl
        je      .LBB0_1
        movaps  xmm2, xmm0
        jmp     .LBB0_3
.LBB0_1:
        movss   xmm2, dword ptr [rip + .LCPI0_0] # xmm2 = mem[0],zero,zero,zero
.LBB0_3:
        mov     al, cl
        movss   xmm1, dword ptr [4*rax + .LCPI0_1] # xmm1 = mem[0],zero,zero,zero
        mulss   xmm1, xmm0
        addss   xmm1, dword ptr [4*rax + .LCPI0_2]
        mulss   xmm1, xmm0
        addss   xmm1, dword ptr [4*rax + .LCPI0_3]
        mulss   xmm1, xmm2
        movaps  xmm0, xmm1
        ret
```

**Comment by rotateright** [comment]
It's correct that the branch (select) code is optimizing differently, but are you seeing a wrong/different answer?

The constants are now conditionally loaded from different addresses:
```
.LCPI0_1:
        .long   0x40e00000                      # float 7
        .long   0x40800000                      # float 4
...
       test    ecx, ecx
       sete    cl
 ...
       mov     al, cl
       movss   xmm1, dword ptr [4*rax + .LCPI0_1] # xmm1 = mem[0],zero,zero,zero

```
If ecx (the input parameter) is 0, this should load 4.0 into xmm1. If ecx is not zero, this should load 7.0.

**Comment by EugeneZelenko** [comment]
Could you please try `main` branch? https://godbolt.org should be helpful.

**Comment by bkaradzic** [comment]
> but are you seeing a wrong/different answer?

I do have issues with the results, but in more complex example:
https://godbolt.org/z/hYvK35TGj

I just thought that I narrowed it down to branch optimization, since that's most obvious difference between two asm outputs.

**Comment by rotateright** [comment]
> I do have issues with the results, but in more complex example: https://godbolt.org/z/hYvK35TGj

Please create a runnable example (you can enable that on godbolt with the "Execute the code" checkbox), and then reduce it to just before the output no longer shows a difference. If the problem is visible with trunk clang, then choose that option (I don't think there are any more planned releases for the 14.0 branch).

**Comment by bkaradzic** [comment]
Here is better repro (with compiler execution):
https://godbolt.org/z/cnn58f8a5

Incorrect results:

```
  0: 1.000000
  1: 1.000000
  2: -0.000200
  3: 1.000000
  4: 1.000000
  5: 1.000000
  6: 1.000000
  7: 1.000000
  8: -0.000801
  9: -0.000901
 10: 1.000000
```

Correct results:

```
  0: 1.000000
  1: 1.000000
  2: 1.000000
  3: 1.000000
  4: 1.000000
  5: 1.000000
  6: 1.000000
  7: 1.000000
  8: 1.000000
  9: 1.000000
 10: 1.000000
...
```

Even thought locally I can repro issue with `-fassociative-math` only, I had to switch `-ffast-math` to get Compiler Explorer output to behave as on my machine.

Also this is where the issue occurs:

```cpp
	inline BX_CONSTEXPR_FUNC float floor(float _a)
	{
		if (_a < 0.0f)
		{
			const float fr = fract(-_a);
#if 1 // change this to 0 to fix the issue
			const float result = -_a - fr;
#else
			const float result = forceEval(-_a - fr);
#endif

			return -(0.0f != fr
				? result + 1.0f
				: result)
				;
		}

		return _a - fract(_a);
	}

	}
```

`forceEval` could be even simple pass thru value function, still fixes the bug in the code.

**Comment by rotateright** [comment]
I don't think there's a compiler bug here. You told the compiler (via -ffast-math or -fassociate-math) that it could rearrange your FP math, but your code does not seem to expect that possibility. I think it was just lucky that you don't see a bug with the earlier version of clang.

The code on the relevant path tries to compute this:
-(-x - (-x - (int)(x)) + 1.0)

In clang 13 and above, the optimizer turned that into:
x - 1.0 + (-x -(int)x)
(distributed the negate and moved the "+1.0")

With the change in fa68d93d54b0cc8, it should kill the x + -x terms, so we'll just have:
-(int)x - 1.0

You can't compile with -ffast-math and expect reliable results unless you've accounted for all the ways the compiler might (or might not) rearrange your FP math.

**Comment by bkaradzic** [comment]
That makes sense. Thank you!
