### ISSUE TITLE
Issue diagnostic when defining a type in offsetof

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#57065]
https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2350.htm was adopted for C2x and makes it clear that defining a type in `offsetof` is undefined behavior. We already diagnose when referencing a bit-field, which is also UB, so we might as well catch this one as well.

**Comment by inclyc** [comment]
To avoid any duplicated work, this issue has been resolved in [D133574](https://reviews.llvm.org/D133574) and I'm waiting for Linux kernel patch before land [D133574](https://reviews.llvm.org/D133574).
