### ISSUE TITLE
Backport "[clang] Require strict matches for defines for PCH in GCC style directories" to 15.x

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#57067]
I think we should backport c843c921a1a385bb805b2338d980436c94f83f19 to the 15.x branch. Unfortunately it doesn't apply cleanly due to the release notes. (If backported, I would remove the corresponding release note mention from the main branch.)

I've put up a manually backported version of the commit at https://github.com/mstorsjo/llvm-project/commits/clang-pch-15.x - but I can't seem to make a PR from that into https://github.com/llvm/llvm-project-release-prs. How do I best do that, @tru ?

**Comment by tru** [comment]
That should tell the bot to do it. Let's see.

**Comment by tru** [comment]
Hm it failed.   I'll have a look tomorrow when I can check the logs better.

**Comment by tru** [comment]
@mstorsjo done! I don't think I needed the cherry-pick command just the branch command - but I messed up the syntax the first time. Want me to slate this for merge?

**Comment by mstorsjo** [comment]
> @mstorsjo done! I don't think I needed the cherry-pick command just the branch command - but I messed up the syntax the first time. Want me to slate this for merge?

Yes please - thanks!
