### ISSUE TITLE
one-shot-bufferize assertion error with bufferization.to_memref

### ISSUE THREAD

**Issue by srcarroll** [llvm/llvm-project#57071]
The `one-shot-bufferize`  pass throws assertion error `OpOperand was already decided to bufferize inplace` with the following IR
```mlir
func.func @main(%arg0 : tensor<f32>) -> memref<f32> {
    %0 = bufferization.to_memref %arg0 : memref<f32>
    return %0 : memref<f32>
}
```
Although the pass succeeds with the `bufferize-function-boundaries` option, this is a bug.
Moreover, on more complex IR (see below) the same assertion error occurs with the `bufferize-function-boundaries`.
```mlir
module attributes {tf.versions = {bad_consumers = [], min_consumer = 0 : i32, producer = 1099 : i32}} {
  func.func @main(%arg0: tensor<1x4x16xf32>, %arg1: tensor<1x4xi32>) -> tensor<2x16xf32> attributes {tf.entry_function = {control_outputs = "", inputs = "args_0,args_0_1", outputs = "Identity"}} {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c4 = arith.constant 4 : index
    %c16 = arith.constant 16 : index
    %cst = arith.constant dense<0.000000e+00> : tensor<2x16xf32>
    %0 = bufferization.to_memref %cst : memref<2x16xf32>
    %1 = memref.alloc() : memref<2x16xf32>
    memref.copy %0, %1 : memref<2x16xf32> to memref<2x16xf32>
    scf.for %arg2 = %c0 to %c4 step %c1 {
      %3 = tensor.extract %arg1[%c0, %arg2] : tensor<1x4xi32>
      %4 = arith.index_cast %3 : i32 to index
      scf.for %arg3 = %c0 to %c16 step %c1 {
        %5 = memref.load %1[%4, %arg3] : memref<2x16xf32>
        %6 = tensor.extract %arg0[%c0, %arg2, %arg3] : tensor<1x4x16xf32>
        %7 = arith.addf %5, %6 : f32
        memref.store %7, %1[%4, %arg3] : memref<2x16xf32>
      }
    }
    %2 = bufferization.to_tensor %1 : memref<2x16xf32>
    return %2 : tensor<2x16xf32>
  }
}
```
Also, it doesn't seem like the `dialect-filter` filter option  avoids this.
Finally, if anyone has advice for how this should be transformed further before using `one-shot-bufferize` I'd appreciate the feedback.  Thanks!

**Comment by matthias-springer** [comment]
This assertion is badly formulated. IR that contains `bufferization.to_tensor` and/or `bufferization.to_memref` ops is not supported by One-Shot Bufferize.

It looks like you already did some partial bufferization before handing the IR off to One-Shot Bufferize. Can you let One-Shot Bufferize do the entire bufferization?

**Comment by srcarroll** [comment]
I didn't do any partial bufferization before hand.  The `bufferization` ops are a side effect of a different transformation.  Moreover, the same pass works on the most recent `tf-opt` in the `tensorflow` repo.

**Comment by matthias-springer** [comment]
I would be interested to see what transformation generates these ops. They should only be generated by a bufferization pass.

> Moreover, the same pass works on the most recent tf-opt in the tensorflow repo.

Do you also run One-Shot Bufferize? Or do you run one of the partial bufferization passes (e.g., `--tensor-bufferize`)? The latter ones do support `bufferization.to_tensor`/`bufferization.to_memref` but at the cost of additional buffer copies whenever memory is written.

There is certain IR with `bufferization.to_tensor`/`bufferization.to_memref` that can be bufferized with One-Shot Bufferize. But most IR cannot. The main problem is that One-Shot Bufferize analyzes the flow of data through tensor SSA use-def chains. But once it sees a `to_memref`, it cannot continue. The assertion that you are seeing is a consequence of this. We should probably do an initial scan over the input IR to look for `to_memref` ops and abort immediately when we find one (to improve the error handling).

**Comment by srcarroll** [comment]
> I would be interested to see what transformation generates these ops

The transformation is a custom pass we have.  We certainly can try to avoid generation the `to_memref`/`to_tensor` ops.  I was mainly just concerned that there is a version of this pass out there that works with this IR.

But I can think of other situations where a `bufferization.to_memref` can be used before bufferization.  Say you want to make a call to an external lib function.  If you want the function to work on any shape you can declare its argument(s) to be unranked memref.  Then in the IR, convert the tensor to memref with `to_memref`, and cast to unranked with `memref.cast`.  I suppose this call insertion could be done after bufferization, but there may be situations where it makes sense to do so earlier.

> Do you also run One-Shot Bufferize? Or do you run one of the partial bufferization passes (e.g., `--tensor-bufferize`)?
The same exact pass in `tf-opt` works on this IR, i.e. `tf-opt --one-shot-bufferize` as opposed to `mlir-opt --one-shot-bufferize`

**Comment by srcarroll** [comment]
Oh my bad.  It's not the exact same.  It's `tf-opt --one-shot-bufferize="allow-unknown-ops"` that works. But `mlir-opt --one-shot-bufferize="allow-unknown-ops"` does not.  Sorry for the confusion

**Comment by srcarroll** [comment]
Btw without the `allow-unknown-ops`, the `tf-opt` version does throw a proper error that the op was not bufferized

**Comment by matthias-springer** [comment]
> But I can think of other situations where a bufferization.to_memref can be used before bufferization. Say you want to make a call to an external lib function. 

You can declare the external function with an unranked tensor type. The signature will get bufferized and turn into one with unranked memrefs. (At the call site, you can cast the ranked tensor to an unranked one.)

I'm not super familiar with `tf-opt`, but if the same pass as with `mlir-opt` is executed, I would expect the same result. It is possible, though, that `tf-opt` does register external models required for bufferization, which would explain the difference in behavior. (In MLIR, they are registered in `InitAllDialects.h`, `registerBufferizableOpInterfaceExternalModels`).

The IR that you posted is *before* running One-Shot Bufferize, right? Can you run One-Shot Bufferize before running the pass that introduces all the `memref` ops?

If you want to debug this further and find out why the passes behave differently, I'd suggest to put some printf in `Bufferization/Transforms/Bufferize.cpp`, `bufferization::bufferizeOp`. The call to `bufferizableOp.bufferize` triggers the bufferization of the given op.

**Comment by srcarroll** [comment]
> You can declare the external function with an unranked tensor type.

Oh cool, I didn't know that. Thanks.

> The IR that you posted is before running One-Shot Bufferize, right? Can you run One-Shot Bufferize before running the pass that introduces all the memref ops?

Yes it is before.  No I can't run one-shot-bufferize before because then there wouldn't be a tensor to convert to memref.

I think how I got this specific IR is besides the point.  The point is there is valid IR that causes an assertion error with the pass.  Assertion errors getting thrown is indicative of a bug.  So either way, there is something wrong with the pass.  Do you not agree?  It's fine if the pass won't bufferize the to_memref/to_tensor ops, but it should still execute without errors with the `allow-unknown-ops` option.  Otherwise, a properly emitted error should be thrown.

**Comment by srcarroll** [comment]
If I tried to avoid bufferization ops I would have to do something like the following (semantics not verified, but should illustrate the pattern needed)
```
  func.func @main(%arg0: tensor<1x4x16xf32>, %arg1: tensor<1x4xi32>) -> tensor<2x16xf32> attributes {tf.entry_function = {control_outputs = "", inputs = "args_0,args_0_1", outputs = "Identity"}} {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c4 = arith.constant 4 : index
    %c16 = arith.constant 16 : index
    %cst = arith.constant dense<0.000000e+00> : tensor<2x16xf32>
    %result = affine.for %arg2 = %c0 to %c4 step 1 iter_args(%iter = %cst) -> tensor<2x16xf32> {
      %3 = tensor.extract %arg1[%c0, %arg2] : tensor<1x4xi32>
      %4 = arith.index_cast %3 : i32 to index
      %partial = affine.for %arg3 = %c0 to %c16 step 1 iter_args(%iter2 = %iter) -> tensor<2x16xf32> {
        %5 = tensor.extract %iter2[%4, %arg3] : tensor<2x16xf32>
        %6 = tensor.extract %arg0[%c0, %arg2, %arg3] : tensor<1x4x16xf32>
        %7 = arith.addf %5, %6 : f32
        %8 = tensor.insert %7 into %iter2[%4, %arg3] : tensor<2x16xf32>
        affine.yield %8 : tensor<2x16xf32>
      }
      affine.yield %partial : tensor<2x16xf32>
    }
    return %result : tensor<2x16xf32>
  }
  ```
  However, I have problems bufferizing this too.  Specifically the `affine.for`.  Any ideas?

**Comment by srcarroll** [comment]
Oh never mind!  I didn't know I could do the same thing with `scf.for`.  Which does bufferize

**Comment by matthias-springer** [comment]
> The point is there is valid IR that causes an assertion error with the pass. Assertion errors getting thrown is indicative of a bug.

It's garbage in, garbage out. But yes this is bad error handling. I will prepare a change that issues a `signalPassFailure` if a `to_memref` is found during an initial scan.

`affine.for` is currently not supported, but if needed we can implement it the same way as `scf.for`.

**Comment by matthias-springer** [comment]
This addresses the issue: https://reviews.llvm.org/D132027
