### ISSUE TITLE
Backport LLD/COFF support for "exclude-symbols" to 15.x

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#57076]
I'd suggest backporting d1da6469f9ea9b078276ee2e098241f0440468be ("[LLD] [MinGW] Implement the --exclude-symbols option") and 5d513ef6cf4646e64bbb1d5f8610afd530964588 ("[LLD] [COFF] Add support for a new, mingw specific embedded directive -exclude-symbols:") to the 15.x release.

As they touch upon release notes, there will be conflicts in backporting, so I'll manually make a backports branch.

**Comment by MaskRay** [comment]
LGTM
