### ISSUE TITLE
Support for System Z target in LLD

### ISSUE THREAD

**Issue by basedjakfan2** [llvm/llvm-project#57097]
Hello, I noticed that lld does not have support for System Z (s390x) target, I want to use LLVM/Clang toolchain targeting this architecture but unfortunately I can't due to missing support for LLD. Are there plans on supporting s390x in LLD? That could be pretty useful for software developers that do not want to depend on GNU software.

Best wishes

**Comment by dmoody256** [comment]
+1

**Comment by brandond** [comment]
Would love this as well. This appears to be blocking us from building WasmEdge (via containerd/runwasi) on s390x.

**Comment by manogy** [comment]
+1 looking for this to get enabled

**Comment by tuliom** [comment]
@basedjakfan2 there is an on-going work for this.
@uweigand implemented an initial draft for this and I've been testing/validating it with existent open source projects.

**Comment by tstellar** [comment]
Initial Patch: PR#75643

**Comment by uweigand** [comment]
Now fixed via https://github.com/llvm/llvm-project/pull/75643
