### ISSUE TITLE
[mlir] Incorrect lowering of tosa::ReluNOp and tosa::ClampOp

### ISSUE THREAD

**Issue by sabauma** [llvm/llvm-project#57095]
Change 2eb50cee11ccbfac71eeb7687b9f136d95fc7f52 changed the implementation of tosa::ClampOp to use a sequence of maxf and minf operations for floating point value.

The clamp operation is lowered to

   val = min(val, minVal)
   result = max(val, maxVal)

The correct implementation is

   val = max(val, minVal)
   result = min(val, maxVal)

A reproducer can be found in `@test_simple_f32` of `test/Conversion/TosaToLinalg/tosa-to-linalg.mlir`.

**Comment by jpienaar** [comment]
This was fixed in https://github.com/llvm/llvm-project/commit/444b4fda17bca581fab084926b91393bd20478e7.
