### ISSUE TITLE
[clang-format] How to only format new commits content in git

### ISSUE THREAD

**Issue by LimingFang** [llvm/llvm-project#57109]
Suppose we use git for version control, and the project doesn't use clang-format before( use cpp-lint instead). However, from now on, we want to introduce clang-format for better c++ coding style.
My question is, is it possible to only format new commits in order to retain the old committer info.

**Comment by EugeneZelenko** [comment]
Did you try `clang-format-diff.py`?

**Comment by LimingFang** [comment]
> Did you try `clang-format-diff.py`?

Thanks, i'll try it and update questions here.

**Comment by LimingFang** [comment]
It solved my question, thanks!
