### ISSUE TITLE
How to add a custom instruction based on RISCV Vector extension in LLVM

### ISSUE THREAD

**Issue by schwa1z** [llvm/llvm-project#57115]
Hi! Community

Here I want to add a custom instruction based on RISCV Vector extension. In RISCV Vector extension, we know that there is an instruction "**_vwmaccu_**" which function is "**_Vector Widening Integer Multiply-Add_**". I want to add a custom instruction which is parallel to "vwmaccu", in other words, the function is very similar to it. For example, "Vector Widening Integer Multiply-Shift" to realize some specific application. The instruction format could be basically similar, except that funct6 is different to distinguish functions. And then I will add some arithmetic logic to a RISCV core to implement the function(but it is future work). 

I want to know what I need to modify or add in complier level to implement such instruction. 

Thank you in advance!

**Comment by asl** [comment]
Hello

Since this is not an issue, but rather a generic question it'd be better to ask this at LLVM Discourse. See https://llvm.org/docs/GettingInvolved.html#forums-mailing-lists for more information
