### ISSUE TITLE
llvm.memmove intrinsic odd behaviour based on data type layout

### ISSUE THREAD

**Issue by AjaniBilby** [llvm/llvm-project#57111]
Platforms tested;
 - Custom light weight LLVM-IR compiler based on the `release/14.x` branch using c-apis
 - `clang version 13.0.1 Target: x86_64-pc-windows-msvc Thread model: posix`
 - `clang version 10.0.0-4ubuntu1 Target: x86_64-pc-linux-gnu Thread model: posix InstalledDir: /usr/bin`

I'm honestly not sure exactly what's happening, but from my understanding there appears to be a weird interaction between possibly unaligned privative values stored in a struct and the `llvm.memmove.p0i8.p0i8.i64` intrinsic.

I made a test case set which should print out `1.234500` four times, however it does not on the first case.
  1. Creates a local instance of the struct, populates the elements with inital data, transfers the whole struct to the correct location **via mem-move**. `0.000000` ❌
  2. Creates a local instance of the struct, populates the elements with inital data, transfers the whole struct to the correct location **via a load then store instruction**. `1.234500` ✔
  3. Creates a local instance of the struct **with the elements in reverse order**, populates the elements with inital data, transfers the whole struct to the correct location **via mem-move**. `1.234500` ✔
  4. Creates a local instance of the struct **with the elements in reverse order**, populates the elements with inital data, transfers the whole struct to the correct location **via a load then store instruction**. `1.234500` ✔

```llvm
; some global values for fprint and declaring the c-abi functions being used
@.str = private unnamed_addr constant [4 x i8] c"%f\0A\00", align 1
declare dso_local i32 @printf(i8*, ...)

declare dso_local void @llvm.memmove.p0i8.p0i8.i64 (i8*, i8*, i64, i1)


; a data structure which if padding is not present the 64bit float will be incorrectly aligned on some systems
%struct.Blob = type { i1, double }

; a constructor which initializes the structure locally, then memmoves the data to the correct location
define dso_local void @construct.memmove (%struct.Blob* %0) {
  %2 = alloca %struct.Blob, align 4

  %3 = getelementptr inbounds %struct.Blob, %struct.Blob* %2, i32 0, i32 1
  store double 1.2345, double* %3, align 4

  %4 = getelementptr inbounds %struct.Blob, %struct.Blob* %2, i32 0, i32 0
  store i1 1, i1* %4, align 4

  %5 = bitcast %struct.Blob* %2 to i8*
  %6 = bitcast %struct.Blob* %0 to i8*
  call void @llvm.memmove.p0i8.p0i8.i64 (i8* %6, i8* %5, i64 9, i1 0)

  ret void
}

; a constructor which does the same as previous, but instead uses load then store instructions
define dso_local void @construct.restore (%struct.Blob* %0) {
  %2 = alloca %struct.Blob, align 4

  %3 = getelementptr inbounds %struct.Blob, %struct.Blob* %2, i32 0, i32 1
  store double 1.2345, double* %3, align 4

  %4 = getelementptr inbounds %struct.Blob, %struct.Blob* %2, i32 0, i32 0
  store i1 1, i1* %4, align 4

  %5 = load %struct.Blob, %struct.Blob* %2
  store %struct.Blob %5, %struct.Blob* %0

  ret void
}

; duplicate of the earlier test cases but with the struct elements reversed so the double should now be aligned
%struct.Blob.inverse = type { double, i1 }
define dso_local void @construct.inverse.memmove (%struct.Blob.inverse* %0) {
  %2 = alloca %struct.Blob.inverse, align 4

  %3 = getelementptr inbounds %struct.Blob.inverse, %struct.Blob.inverse* %2, i32 0, i32 0
  store double 1.2345, double* %3, align 4

  %4 = getelementptr inbounds %struct.Blob.inverse, %struct.Blob.inverse* %2, i32 0, i32 1
  store i1 1, i1* %4, align 4

  %5 = bitcast %struct.Blob.inverse* %2 to i8*
  %6 = bitcast %struct.Blob.inverse* %0 to i8*
  call void @llvm.memmove.p0i8.p0i8.i64 (i8* %6, i8* %5, i64 9, i1 0)

  ret void
}

define dso_local void @construct.inverse.restore (%struct.Blob.inverse* %0) {
  %2 = alloca %struct.Blob.inverse, align 4

  %3 = getelementptr inbounds %struct.Blob.inverse, %struct.Blob.inverse* %2, i32 0, i32 0
  store double 1.2345, double* %3, align 4

  %4 = getelementptr inbounds %struct.Blob.inverse, %struct.Blob.inverse* %2, i32 0, i32 1
  store i1 1, i1* %4, align 4

  %5 = load %struct.Blob.inverse, %struct.Blob.inverse* %2
  store %struct.Blob.inverse %5, %struct.Blob.inverse* %0

  ret void
}


; Run all four test cases
define dso_local i64 @main () {
  ; case 1
  %1 = alloca %struct.Blob, align 4
  call void @construct.memmove (%struct.Blob* %1)

  %2 = getelementptr inbounds %struct.Blob, %struct.Blob* %1, i32 0, i32 1
  %3 = load double, double* %2, align 4
  %4 = call i32 (i8*, ...) @printf (i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), double %3)

  ; case 2
  %5 = alloca %struct.Blob, align 4
  call void @construct.restore (%struct.Blob* %5)

  %6 = getelementptr inbounds %struct.Blob, %struct.Blob* %5, i32 0, i32 1
  %7 = load double, double* %6, align 4
  %8 = call i32 (i8*, ...) @printf (i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), double %7)

  ; case 3
  %9 = alloca %struct.Blob.inverse, align 4
  call void @construct.inverse.memmove (%struct.Blob.inverse* %9)

  %10 = getelementptr inbounds %struct.Blob.inverse, %struct.Blob.inverse* %9, i32 0, i32 0
  %11 = load double, double* %10, align 4
  %12 = call i32 (i8*, ...) @printf (i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), double %11)

  ; case 4
  %13 = alloca %struct.Blob.inverse, align 4
  call void @construct.inverse.restore (%struct.Blob.inverse* %13)

  %14 = getelementptr inbounds %struct.Blob.inverse, %struct.Blob.inverse* %13, i32 0, i32 0
  %15 = load double, double* %14, align 4
  %16 = call i32 (i8*, ...) @printf (i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), double %15)


  ret i64 0
}
```

Output when running the compiled program (same across all three platforms mentioned):
```
0.000000
1.234500
1.234500
1.234500
```

Expected output
```
1.234500
1.234500
1.234500
1.234500
```

**Comment by topperc** [comment]
`%struct.Blob = type { i1, double }` is not a packed struct so there should be padding between the i1 and the double to keep the double aligned.

**Comment by AjaniBilby** [comment]
@EugeneZelenko I tested with `-O0`, `-O1`, `-O2`, `-O3` on win10 clang14 and it made no difference to the output.
IDK exactly how the internals of LLVM work, but I'd assume that would mean it's not an optimisation parse's fault.

**Comment by AjaniBilby** [comment]
> `%struct.Blob = type { i1, double }` is not a packed struct so there should be padding between the i1 and the double to keep the double aligned.

That makes it even more interesting, because they reversing the struct elements should make no difference in my mind, but case 1 and 3 yield different results 🤔

**Comment by topperc** [comment]
If the struct has padding don't you need to memmove more than 9 bytes to cover the double?

**Comment by AjaniBilby** [comment]
According to the language ref for LLVM-IR I don't see why here would be any issue loading and then storing a 16byte wide structure.
> An alignment of 1 is always safe. The maximum possible alignment is 1 << 32.

**Comment by topperc** [comment]
The two calls to llvm.memmove should have 16 has their third argument, not 9. The struct is 16 bytes long.

**Comment by AjaniBilby** [comment]
Then probably to be more consistent for possible architectures or cases where padding might not be used for whatever case - then this should be used.
```llvm
define dso_local void @construct.memmove (%struct.Blob* %0) {
  %2 = alloca %struct.Blob, align 4

  %3 = getelementptr inbounds %struct.Blob, %struct.Blob* %2, i32 0, i32 1
  store double 1.2345, double* %3, align 4

  %4 = getelementptr inbounds %struct.Blob, %struct.Blob* %2, i32 0, i32 0
  store i1 1, i1* %4, align 4

  ; cast address types
  %5 = bitcast %struct.Blob* %2 to i8*
  %6 = bitcast %struct.Blob* %0 to i8*

  ; calculate struct width
  %7 = getelementptr %struct.Blob, %struct.Blob* null, i64 1
  %8 = ptrtoint %struct.Blob* %7 to i64

  ; move data
  call void @llvm.memmove.p0i8.p0i8.i64 (i8* %6, i8* %5, i64 %8, i1 0)

  ret void
}
```

Is there any advantage to using memmove over a load and store? Does the optimiser actually use the information that the source location will no longer be used because the values where moved?
