### ISSUE TITLE
We should bring NonNull attribute into Intrinsics.td

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#57113]
Currently the intrinsic `llvm.threadlocal.address` would take the address of the global TLS variable and return it. Since the address of the global TLS variable shouldn't be null, the intrinsics itself shouldn't be null too.

But currently we can't set an intrinsic as NonNull directly in Intrinsics.td. And there should be other intrinsics which are not null.
So we might lose some minor optimization chances.

**Comment by alexander-shaposhnikov** [comment]
I've prepared a patch, planning to send it for review ~soon
