### ISSUE TITLE
llvm-ranlib does not support the -t flag

### ISSUE THREAD

**Issue by brad0** [llvm/llvm-project#57129]
GNU ranlib supports a -t flag which OpenBSD utilizes.

```
-t  Update the timestamp of the symbol map of an archive.
```

**Comment by brad0** [comment]
@MaskRay

**Comment by MaskRay** [comment]
Nowaday reproducible build practice discourages this: https://reproducible-builds.org/docs/timestamps/ .
Also, archive timestamps are mostly useless. Is there any reason OpenBSD  needs this?

In binutils ranlib, in the deterministic mode, this operation is a no-op.

**Comment by brad0** [comment]
Looking back at the commit history for (our) GNU libtool, the reason was..

```
revision 1.3
date: 2001/08/20 21:53:03;  author: espie;  state: Exp;  lines: +20 -6;
ranlib -t on install, somewhat faster, sometimes MUCH faster.
```

AFAIK the flag was never added anywhere else, but GNU libtool is so commonly used.

I submitted a patch to start the slow process of having the flag usage removed (Bitrig is long dead and I will clean that up as well) and eventually propagate out to the ecosystem.

https://lists.gnu.org/archive/html/libtool-patches/2022-08/msg00000.html
