### ISSUE TITLE
Merge -fdebug-prefix-map fixes (MC,llvm-dwarfdump) into release/15.x

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#57125]
For #56609 (@rossburton  @kraj )

/cherry-pick b0c4cd35df89479ec152c1f79e18d0264dd276cc d561907f27d721558e4372990ca52a8284b7aafc 53113515cdaa19a86e4b807808b7b99dc1c91685 f62e60fb238146113f84e0efb1a2ebc52f05cc0a 3329cec2f79185bafd678f310fafadba2a8c76d2

**Comment by tru** [comment]
/cherry-pick b0c4cd3 d561907 5311351 f62e60f 3329cec d797c2f
