### ISSUE TITLE
How to add LLVM to existing Visual Studio project

### ISSUE THREAD

**Issue by H3XAGON** [llvm/llvm-project#57134]
I followed the steps on https://llvm.org/docs/GettingStartedVS.html to build LLVM. After building the INSTALL project that was generated I now have the cloned LLVM repo, the 'build' folder generated by CMake, and the 'Debug' folder generated by VS after running the INSTALL project. Now how do I add LLVM to one of my projects so I can for example #include some of the LLVM IR headers?

**Comment by EugeneZelenko** [comment]
Please use https://discourse.llvm.org for questions.
