### ISSUE TITLE
[libc++] `variant` hasn't implemented P1957R2

### ISSUE THREAD

**Issue by CaseyCarter** [llvm/llvm-project#57139]
As witnessed by failure to compile [this TU](https://godbolt.org/z/sTaqn1vdW) which assigns `std::true_type` to a `variant<bool>`. P1957R2 "Converting from `T*` to `bool` should be considered narrowing" was a C++20 core language change with minor library impact. Clang has implemented it (according to cppreference, anyway) I suspect libc++ maintainers didn't realize the CWG paper had changes to library wording as well.

**Comment by philnik777** [comment]
We have P1957R2 on our TODO-list. It's just that nobody felt like implementing it yet.

**Comment by mordante** [comment]
FYI our TODO-list is here https://libcxx.llvm.org/Status/Cxx20.html

**Comment by philnik777** [comment]
Closing this, since we don't track paper implementations here.
