### ISSUE TITLE
lld-link: Undefined symbol llvm::LLVMContext

### ISSUE THREAD

**Issue by H3XAGON** [llvm/llvm-project#57144]
Hi, I have my project set up using Visual Studio 2022. My platform toolset is set to LLVM (clang-cl) and the include path is set correctly. My code for now looks something like this:

```
#include <llvm/IR/IRBuilder.h>

static llvm::LLVMContext context;
static llvm::IRBuilder<> Builder();
static std::unique_ptr<llvm::Module> _module;
static std::map<std::string, llvm::Value*> namedValues;
```

But when I compile I get the following three errors (I use the APInt class somewhere else as well which is why one of the errors references it): 

![image](https://user-images.githubusercontent.com/17811155/184550578-87edbea2-bd96-4ccc-a4af-247f26b42739.png)

Are there any additional libraries that I need to link?

**Comment by fhahn** [comment]
Please use https://discourse.llvm.org for questions about how to use LLVM & related projects.
