### ISSUE TITLE
[AMDGPU] Some confusion about LLVM IR alloca instruction

### ISSUE THREAD

**Issue by GaleSeLee** [llvm/llvm-project#57163]
Hello, develops! 
I use `clang++` and `hipcc` to generate LLVM IR for NVIDIA GPU and AMD GPU. They generate different alloca statements.
Here is an example:
```
__device__ void int_a_kernel() {
    int a = 1;
}
```
NVIDIA GPUs LLVM IR:
```
define dso_local void @_Z12int_a_kernelv() #0 {
  %1 = alloca i32, align 4
  store i32 1, i32* %1, align 4
  ret void
}
```
But AMDGPU's has more memory info
```
define dso_local void @_Z12int_a_kernelv() #0 {
  %1 = alloca i32, align 4, addrspace(5)
  %2 = addrspacecast i32 addrspace(5)* %1 to i32*
  store i32 1, i32* %2, align 4
  ret void
}
```
I wonder is there a way to convert LLVM ir for NVIDIA GPU to ir for AMDGPU?
Thanks!

**Comment by fhahn** [comment]
For questions, please use https://discourse.llvm.org
