### ISSUE TITLE
clang -fsanitize=alignment crashes with __builtin_assume_aligned

### ISSUE THREAD

**Issue by m-gupta** [llvm/llvm-project#57169]
```C
// clang -c -fsanitize=alignment test.c
int main ()
{
(void) __builtin_assume_aligned("", 1);
  return 0;
}
```

```console
llvm/llvm-project/clang/include/clang/AST/Type.h:691: const ExtQualsTypeCommonBase *clang::QualType::getCommonPtr() const: Assertion `!isNull() && "Cannot retrieve a NULL type pointer"' failed.
```

@vitalybuka can you please check?

**Comment by inclyc** [comment]
This assertion fail seems to exist only when -fsanitize=alignment is enabled

https://godbolt.org/z/z8h3x7zd3

**Comment by objwyh** [comment]
This crash seems caused by clang::CodeGen::CodeGenFunction::emitAlignmentAssumption doesn't have implicit cast char[1] to a pointer type
https://github.com/llvm/llvm-project/blob/7f768371a12d121731832b80bc9bef6c2e47e43f/clang/lib/CodeGen/CodeGenFunction.cpp#L2714

**Comment by objwyh** [comment]
I've a patch try to fix it https://reviews.llvm.org/D131979

**Comment by objwyh** [comment]
Thanks for your fix @yronglin

**Comment by AaronBallman** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/6ed21fc515230ac2ea459d8aa90566e9a467bbb0
