### ISSUE TITLE
space removed after auto keyword, clang-format 14 regression

### ISSUE THREAD

**Issue by JohnC32** [llvm/llvm-project#57160]
Given:

```c++
struct Foo {
    static constexpr auto (A::*f)() const = &A::start;
};

static auto toFile = [](auto const& f) -> auto {
    auto p = f->getP();
    return xp(p);
};

```

and `_clang-format`:

```yaml
---
BasedOnStyle: Google
IndentWidth: 4
...
```

Running clang-format 13 gives the expected answer (same as above).

Running clang-format 14 gives:

```c++
struct Foo {
    static constexpr auto(A::*f)() const = &A::start;
};

static auto toFile = [](auto const& f) -> auto{
    auto p = f->getP();
    return xp(p);
};
```

Notice the space after the `auto` keyword has been removed when a '(' or '{' follows the auto. Seems
like clang-format 14 is incorrectly treating auto as a non-keyword, perhaps a user function?

**Comment by owenca** [comment]
https://reviews.llvm.org/D132008
