### ISSUE TITLE
Not able to lower tosa code into llvm code

### ISSUE THREAD

**Issue by HemaSowjanyaMamidi** [llvm/llvm-project#57173]
Hi,
@River707 , @eric-k256 
I am experimenting on how to use different dialects and lower them into LLVM code. Then I came across the TOSA dialect which has the layers supported by the Neural Network models and thought to build a small model out of it. So, initially I took a small operation `tosa.const` and tried to lower to LLVM code and wasn't successful. Can you please help me out what am I missing?

```mlir
module{
func.func @main() -> tensor<3xi32>
{
%2 = "tosa.const"() {value = dense<[3,4,5]> : tensor<3xi32>} : () -> tensor<i32>
return %2 :  tensor<3xi32>
}
}
```

```shell
mlir-opt test_tosa.mlir --tosa-to-arith --arith-expand --convert-arith-to-llvm --convert-func-to-llvm
```

The intermediate representation is not completely lowered. Can you please help me regarding this conversion. 

Thanks,
Hema

**Comment by eric-k256** [comment]
What are the errors or output you are seeing? Is the tosa.const not lowered, or is there an error printed?

At a first check, your tosa.const return type appears wrong. It should be () -> tensor<3xi32>

**Comment by HemaSowjanyaMamidi** [comment]
Thanks for the reply. 
That was a typo. Tosa.const is being lowered into arith.constant and I am not able to lower IR further. Am I missing any flags?
![op1](https://user-images.githubusercontent.com/47590467/185047935-1f157174-0292-4c9f-bb6f-412321dc2cd0.PNG)

**Comment by eric-k256** [comment]
llvm const can't handle a tensor, you'll need to bufferize it, and then convert the bufferization into llvm. Something like this should get you close, but then you're mostly past my area of expertise
 --tosa-to-arith --arith-bufferize --memref-expand --convert-memref-to-llvm
There may be better passes to get you what you want, but this gets you pretty close.

**Comment by HemaSowjanyaMamidi** [comment]
@eric-k256 thanks for the Input. 
![tosa_const](https://user-images.githubusercontent.com/47590467/185310739-4ed019b2-d27f-47a2-9a2d-e2d5775b2df6.PNG)
Along with them I added --func-bufferize --pass-pipeline="func.func(canonicalize, finalizing-bufferize, buffer-deallocation)" --convert-memref-to-llvm --convert-func-to-llvm --reconcile-unrealized-casts these flags and then generated .ll file. But I get a segmentation issue there.

**Comment by rajashekarkasturi** [comment]
Hi @HemaSowjanyaMamidi
restructuring your sample to using tosa.const, if you could try this way and check if it's lowering to LLVM IR.
```
func @addOpTOSA() -> () {
        %a = "tosa.const"() {value = dense<[1,2,3]> : tensor<3xi32>  } : () -> tensor<3xi32>
        %b = "tosa.const"() {value = dense<[3,4,5]> : tensor<3xi32>  } : () -> tensor<3xi32>

        %c = "tosa.add"(%a,%b) : (tensor<3xi32>, tensor<3xi32>) -> tensor<3xi32>
        return
}
```
```
> mlir-opt file_name.mlir --tosa-to-linalg --tosa-to-linalg-named \
--linalg-bufferize --convert-linalg-to-affine-loops --lower-affine \
--tensor-bufferize  --tosa-to-standard --tosa-to-scf --convert-scf-to-std \
--arith-expand --arith-bufferize  --convert-memref-to-llvm  --convert-arith-to-llvm\
 --convert-std-to-llvm --canonicalize --llvm-legalize-for-export \ 
--reconcile-unrealized-casts | mlir-translate --mlir-to-llvmir
```

FYI:
```
> mlir-opt --version
LLVM (http://llvm.org/):
  LLVM version 14.0.6
  Optimized build with assertions.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: broadwell
```

**Comment by jpienaar** [comment]
Anything more to do here or can it be closed?

**Comment by HemaSowjanyaMamidi** [comment]
Thank you that worked..!
