### ISSUE TITLE
[libc++] Array access with potentially uninitialized variable in __hash_table::__emplace_unique_key_args

### ISSUE THREAD

**Issue by jarekpelczar** [llvm/llvm-project#57177]
Found by compiling with Trunk GCC:

https://github.com/llvm/llvm-project/blob/f9d988f1acde945c5cbdabe468c147492108dc81/libcxx/include/__hash_table#L1997

The ``__chash`` variable is not initialized in all code paths if the following if is false:

https://github.com/llvm/llvm-project/blob/f9d988f1acde945c5cbdabe468c147492108dc81/libcxx/include/__hash_table#L2015

but array will be accessed regardless:

https://github.com/llvm/llvm-project/blob/f9d988f1acde945c5cbdabe468c147492108dc81/libcxx/include/__hash_table#L2023

**Comment by philnik777** [comment]
I'm nut sure I understand. If `__bc != 0` it gets initialized in line 2000 and if `__bc == 0` it gets initialized in line 2020. `__bc != 0 || size() + 1 > __bc * max_load_factor() || __bc == 0` is always true.

**Comment by jarekpelczar** [comment]
Ok. I can seen now. Sorry for the confusion. I think the main issue is analyzer itself.
