### ISSUE TITLE
Cuda kernel missing and wrong kernel called when compiling with clang-cl. Fixed by passing /OPT:NOICF to linker.

### ISSUE THREAD

**Issue by Danvil** [llvm/llvm-project#57178]
I am trying to compile a CUDA program with clang-cl under windows. The compiled binary somehow does not contain all kernels and invokes the wrong kernels. See example above:

File `bug.cu`:
```cu
#include <iostream>
#include "cuda.h"

__global__ void a(int* v) {
  v[0] = 0;
}

__global__ void b(int* v) {
  v[0] = 1;
}

int main() {
  int* v;
  cudaMallocManaged(&v, sizeof(int));

  a<<<1,1>>>(v);
  b<<<1,1>>>(v);
  cudaDeviceSynchronize();

  std::cout << (v[0] == 1 ? "SUCCESS" : "ERROR") << std::endl;

  cudaFree(v);

  return 0;
}
```

Compilation command line:
```shell
& "C:\Program Files\LLVM\bin\clang-cl.exe" -clang:--cuda-gpu-arch=sm_75 -clang:--cuda-path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.5"  -clang:-std=c++17 bug.cu -o bug.exe -D__CUDACC_VER_MAJOR__=11 /O2 /link /LIBPATH:"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\lib\x64" cuda.lib cudart_static.lib; .\bug.exe
```

Some observations:
* Debugging this program with nsights shows that CUDA runtime only loads the first kernel "a", and launches it twice.
* If the definition of `a` (and the launch of kernel a) in the example above are removed then the example succeeds.
* If an additional dummy argument is added to kernel b, then the example also succeeds.
* It somehow looks like if multiple kernels with the same function signature appear only the first one is used.
* There don't seem to be any CUDA errors reported.
* When compiling with `clang++.exe` instead of `clang-cl.exe` it works.

System:
* LLVM 14.0.6
* CUDA Toolkit 11.5
* NVIDA driver version 516.94
* Windows 10, 64 bit
* Graphics card 2080 TI, SM75

**Comment by Artem-B** [comment]
> cudaMallocManaged(&v, sizeof(int));

I do not think we support managed memory at all.
If you need to fetch the data from the GPU you may need to do it yourself with `cudaMemcpy`.

**Comment by Artem-B** [comment]
> It somehow looks like if multiple kernels with the same function signature appear only the first one is used.

Oh, wait. This rings a bell. I think we've seen this before and the issue was attributed to windows linker commoning kernel launch stubs which then confused CUDA runtime which relies on the stubs having unique addresses. I think we had to use `[/OPT:NOICF](http://msdn.microsoft.com/en-us/library/bxwfs976%28v=vs.110%29.aspx)` to make it work.

@rnk Reed, does this sound plausible? What would be clang-cl's equivalent of `/OPT:NOICF` ?

**Comment by Artem-B** [comment]
For the purposes of CUDA compilation, it will likely work, but it does not see much testing, and it's been known to bitrot now and then.

AFAICT, there's currently nobody who'd claim to own CUDA compilation w/ clang or clang-cl on windows.

**Comment by Artem-B** [comment]
We should probably document this '/OPT:NOICF' requirement for CUDA compilation with clang on Windows, but other than that there's not much clang can do about it.

**Comment by Artem-B** [comment]
> There are ways to block ICF with various devices,

@rnk what would it look like on IR level? Is it just a matter of making sure we don't add `unnamed_addr` attribute to the generated stub?

**Comment by rnk** [comment]
Unfortunately, the devices are ugly. You can do things like this:
```
void foo() {
  static volatile int icfBlocker;
  ++icfBlocker;
}
```

ICF cannot merge writable data, and if each function updates a different global, ICF cannot merge them.
