### ISSUE TITLE
possible miscompile of signext-of-i1 by aarch64 backend

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#57181]
we think this is getting miscompiled:
```llvm
define i32 @assertsext_sub_1(i1 signext %0, i32 %1) {
  %3 = zext i1 %0 to i32
  %4 = sub i32 %1, %3
  ret i32 %4
}
```

the default aarch64 backend emits:
```asm
assertsext_sub_1:
        add     w0, w1, w0
        ret
```

or see here: https://gcc.godbolt.org/z/rYPc3cqE8

so now let's work through the example. call the function with `%0 = 1` and `%1 = 0` and I think we can agree the function should return -1, but the ARM code returns 1 for this input. 

this feels perhaps related to the fact that the aarch64 ABI implicitly zero-extends an `i1` into an `i8`

cc @aemerson @ornata @nunoplopes @ryan-berger @nbushehri @zhengyang92

**Comment by regehr** [comment]
(sorry, I should have added that the fact that i1 is implicitly zero-extended to i8 on this platform is why we can pass 0x1 as the first argument to this function. in other words, in our understanding, the original 1-bit input gets zero extended to 0x01, which the called is then obligated to sign extend, resulting in 0x00000001 being a legal input value to pass this function in a register. this is just our understanding, apologies if this isn't correct)

**Comment by efriedma-quic** [comment]
Consider the following:

```
define i32 @f(i1 signext %0) {
  %r = sext i1 %0 to i32
  ret i32 %r
}

define i32 @g() {
  %r = call i32 @f(i1 signext true)
  ret i32 %r
}
```

SelectionDAG sign-extends the i1 in the caller to -1, and assumes tha extension was done in the callee.  GlobalISel zero-extends in the caller, and doesn't optimize the callee.  I don't think frontends targeting aarch64 ever emit `i1 signext` arguments, so I'm not sure how we'd decide which behavior is "correct".  We should fix it to be consistent, though.

**Comment by regehr** [comment]
yeah I should emphasize that we're formalizing parts of this ABI and we just need consistent rules, we have no opinions about what the rules actually are.

this implicit zext of i1->i8 is pretty awkward, it's going to create lots of odd corner cases

**Comment by miyuki** [comment]
Just to confirm, was the original code generated by some sort of fuzz-testing tool (e.g., like Csmith but for LLVM IR)? Or can it occur in the wild, e.g. be produced by an LLVM interprocedural optimization pass?

**Comment by regehr** [comment]
@miyuki the code is from `test/CodeGen/AArch64/bool-ext-inc.ll`

**Comment by regehr** [comment]
https://github.com/llvm/llvm-project/blob/main/llvm/test/CodeGen/AArch64/bool-ext-inc.ll#L28-L35

**Comment by miyuki** [comment]
> I should have added that the fact that i1 is implicitly zero-extended to i8 on this platform is why we can pass 0x1 as the first argument to this function.

IIUC, zero-extension stems from the C/C++ ABI: https://github.com/ARM-software/abi-aa/blob/main/aapcs64/aapcs64.rst#arithmetic-types says that bool has machine type "unsigned byte". In LLVM IR we can have different semantics for `i1`, and `signext` arguments should be sign-extended by the caller as the LLVM Language Reference suggests. We just need to ensure that C/C++ `bool` is lowered correctly. 
So, I think there is no miscompilation in the original test case, however, the function `g` in Eli's example is miscompiled when GlobalISel is used.

Anyway, I'll raise this issue internally at Arm, maybe we will get some other options.

**Comment by regehr** [comment]
> IIUC, zero-extension stems from the C/C++ ABI: https://github.com/ARM-software/abi-aa/blob/main/aapcs64/aapcs64.rst#arithmetic-types says that bool has machine type "unsigned byte". In LLVM IR we can have different semantics for `i1`, and `signext` arguments should be sign-extended by the caller as the LLVM Language Reference suggests. We just need to ensure that C/C++ `bool` is lowered correctly. So, I think there is no miscompilation in the original test case, however, the function `g` in Eli's example is miscompiled when GlobalISel is used.

I don't have a sense of the tradeoffs here in terms of codegen quality, and anyhow it's obviously Apple/ARM/etc. who are the big stakeholders

however, I am happy to help with getting this disambiguated, and with getting the decisions documented. do we have a good place to document stuff that's platform-specific, but also too LLVM-specific to be part of the ABI? I guess I'd advocate just putting this in LangRef somewhere.

anyway, the sooner we can all reach a decision here, the sooner my group can get back to making sure y'all have implemented things correctly. looking forward to getting this settled.

**Comment by miyuki** [comment]
We discussed this issue internally at Arm with the team involved with upstream LLVM development and also with ABI maintainers. The consensus is that we don't want to specify LLVM IR ABI in ABI documents maintained by Arm, at least unless language frontends start defining their ABIs in terms of LLVM IR constructs. `signext i1` does not have to follow Arm C/C++ ABI for the type bool.
Regarding the specific behaviour of `signext i1` we think that it would make sense to sign-extend to i32 (like SelectionDAG already does), but no strong opinions on this matter.

**Comment by regehr** [comment]
thanks @miyuki. I'd be interested to hear what the Apple folks think about this issue.

**Comment by aemerson** [comment]
I agree with the SelectionDAG interpretation of the `signext` to i32 taking precedence. This seems to be a relatively recent issue for GlobalISel that was introduced in:
```
commit 7ae8f392a1610992c9a925c867fd7238c70d3ce0
Author: Andrew Savonichev <andrew.savonichev@gmail.com>
Date:   Thu Jul 29 14:16:05 2021 +0300

    [AArch64] Emit AssertZExt for i1 arguments
    
    AAPCS requires i1 argument to be zero-extended to 8-bits by the
    caller. Emit a new AArch64ISD::ASSERT_ZEXT_BOOL hint (or AssertZExt
    for GlobalISel) to enable some optimization opportunities. In
    particular, when the argument is forwarded to the callee, we can avoid
    zero-extension and use it as-is.
    
    Differential Revision: https://reviews.llvm.org/D107160
```

I'm working on a patch to fix this and make GISel consistent with SDAG.

**Comment by aemerson** [comment]
Patch proposed: https://reviews.llvm.org/D133327

**Comment by regehr** [comment]
after this lands I'll propose a change to the signext/zeroext text in langref, perhaps something along the lines of "in some cases this attributes may appear to be in conflict with system-specific ABI rules. here's a list of cases where we've seen this happen so far, with their resolutions"
