### ISSUE TITLE
asm attribute applied after use of function is broken

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5720]
|  |  |
| --- | --- |
| Bugzilla Link | [5348](https://llvm.org/bz5348) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
We should do something different on the following code:
--
ddunbar@ozzy:tmp$ cat t.c
```c++
void f0(void);

void g0() {
  f0();
}

extern void f0(void) __asm__ ("bar");

void f0() {
  extern void f1(void);
  f1();
}
```
ddunbar@ozzy:tmp$ clang -emit-llvm -S -o -  t.c
; ModuleID = 't.c'
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128"
target triple = "x86_64-apple-darwin10.0"

define void @&#8203;g0() nounwind ssp {
entry:
  call void @&#8203;f0() ssp
  ret void
}

declare void @&#8203;f0() ssp

define void @"\01bar"() nounwind ssp {
entry:
  call void @&#8203;f1() ssp
  ret void
}

declare void @&#8203;f1() ssp
ddunbar@ozzy:tmp$ 
--

gcc/llvm-gcc drop the __asm__ attribute and warn about it, perhaps we should just make this an error?

**Comment by philnik777** [comment]
This is an error now: https://godbolt.org/z/ea7x9WY1G

**Comment by MaskRay** [comment]
> This is an error now: https://godbolt.org/z/ea7x9WY1G

Clang rejects the use case: `error: cannot apply asm label to function after its first use`

GCC accepts the use case and accepting this use case aligns more with how attributes are merged.
I think that "Closed" is an acceptable state, given that this is very difficult to match GCC.

https://maskray.me/blog/2021-10-10-when-can-glibc-be-built-with-clang#asm-label-after-first-use
