### ISSUE TITLE
[Flang] input module has no datalayout error

### ISSUE THREAD

**Issue by libin049** [llvm/llvm-project#57211]
When I build spec2017 648.exchange2_r using flang-new, I get an error
```console
$ flang-new -v -Wl,--build-id -fuse-ld=lld -flto=full -ljemalloc -O3 -mcpu=native -DSPEC_OPENMP -fopenmp exchange2.fppized.f90  -o exchange2_s_clang-main
flang-new version 16.0.0
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/musk.li/llvm-main/install/bin
Found candidate GCC installation: /opt/rh/devtoolset-10/root/usr/lib/gcc/aarch64-redhat-linux/10
Selected GCC installation: /opt/rh/devtoolset-10/root/usr/lib/gcc/aarch64-redhat-linux/10
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/home/musk.li/llvm-main/install/bin/flang-new" -fc1 -triple aarch64-unknown-linux-gnu -emit-llvm-bc -D SPEC_OPENMP -fopenmp -fcolor-diagnostics -O3 -o /tmp/exchange2-477325.o -x f95-cpp-input exchange2.fppized.f90
 "/home/musk.li/llvm-main/install/bin/ld.lld" -EL --hash-style=gnu --eh-frame-hdr -m aarch64linux -dynamic-linker /lib/ld-linux-aarch64.so.1 -o exchange2_s_clang-main /lib/../lib64/crt1.o /lib/../lib64/crti.o /opt/rh/devtoolset-10/root/usr/lib/gcc/aarch64-redhat-linux/10/crtbegin.o -L/opt/rh/devtoolset-10/root/usr/lib/gcc/aarch64-redhat-linux/10 -L/opt/rh/devtoolset-10/root/usr/lib/gcc/aarch64-redhat-linux/10/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/lib -L/usr/lib -plugin-opt=mcpu=tsv110 -plugin-opt=O3 --build-id -ljemalloc /tmp/exchange2-477325.o -lFortran_main -lFortranRuntime -lFortranDecimal -lm -lomp -rpath /home/musk.li/llvm-main/install/lib -L/home/musk.li/llvm-main/install/lib -lgcc --as-needed -lgcc_s --no-as-needed -lpthread -lc -lgcc --as-needed -lgcc_s --no-as-needed /opt/rh/devtoolset-10/root/usr/lib/gcc/aarch64-redhat-linux/10/crtend.o /lib/../lib64/crtn.o
ld.lld: error: /tmp/exchange2-477325.o: input module has no datalayout
```

exchange2.fppized.f90 as follows：
[exchange2.fppized.f90.txt](https://github.com/llvm/llvm-project/files/9368068/exchange2.fppized.f90.txt)

It seems than flang-new is not very mature，right？
How can I build classic fortran using newest clang 16？

**Comment by kiranchandramohan** [comment]
We are able to build exchange2 locally. I am assuming that you are building 648.exchange2_s. The following invocation works fine for me.
```
flang-new  -O3 -DSPEC_OPENMP -fopenmp exchange2.fppized.f90  -o exchange2_s_clang-main
```

I see that your invocation uses a lot of non-default flags like `-flto=full`, we do not support these. Could you try removing the extra flags and see whether it works? And could you report on which of those flags causes the issue?

The `llvm/flang` project and the `flang-new` driver are work in progress. It works for Fortran 77 and most of Fortran 95. Some portions of the compiler (parsing, semantics, runtime except co-arrays) work for most of Fortran 2018.

What do you mean by `classic fortran`?

**Comment by kiranchandramohan** [comment]
The issue https://github.com/llvm/llvm-project/issues/57230 is probably related.

**Comment by libin049** [comment]
@kiranchandramohan Yean，it works without `-flto=full`.
classic fortran(classic flang) means  "https://github.com/flang-compiler/flang" I found it was build with llvm release 14x.  When I build it using newest clang 16, I found flang1, flang2 build success，but flang  fails.

**Comment by kiranchandramohan** [comment]
This was fixed by the LTO patch (https://reviews.llvm.org/D142420) and the datalayout patch (https://reviews.llvm.org/D133568).
