### ISSUE TITLE
[AArch64] Suboptimal codegen for `is_power_of_two`

### ISSUE THREAD

**Issue by Kmeakin** [llvm/llvm-project#57225]
The traditional test if an integer is a power of two is `((x - 1) & x) == 0 && x != 0`. However, InstCombine recognises this idiom and rewrites it to `popcount(x) == 1`. This is more efficient on architectures with scalar `popcount`, but AArch64 only supports `popcount` on vectors, so the extra instructions to transfer data between scalar and vector registers makes the resulting code less efficient than the traditional method.

C code ([godbolt](https://godbolt.org/z/bfM6KoTbf)):
```c
bool is_power_of_two(uint32_t x) { return ((x - 1) & x) == 0 && x != 0; }
```

Clang output:
```asm
is_power_of_two: // @is_power_of_two
  mov w8, w0
  fmov d0, x8
  cnt v0.8b, v0.8b
  uaddlv h0, v0.8b
  fmov w8, s0
  cmp w8, #1
  cset w0, eq
  ret
```

GCC output:
```asm
is_power_of_two:
  sub w1, w0, #1
  tst w1, w0
  ccmp w0, 0, 4, eq
  cset w0, ne
  ret
```

**Comment by RKSimon** [comment]
X86 (without popcnt) has a problem with the `popcount(x) == 1` fold as well #47250

Should we move this fold into AggresiveInstCombine so we can check for TTI::getPopcntSupport ? Or handle any expansion in CGP?

CC @rotateright @nikic

**Comment by RKSimon** [comment]
vectors are also having a problem with the fold: #47169

CC @davezarzycki

**Comment by rotateright** [comment]
At first glance, I'd say no, we don't want to make the canonicalization depend on target. The alternate IR is much harder to analyze and would inhibit vectorization and other transforms:

```ll
define i1 @is_power_of_2(i32) {
  %2 = icmp eq i32 %0, 0
  br i1 %2, label %7, label %3

  %4 = add nsw i32 %0, -1
  %5 = and i32 %4, %0
  %6 = icmp eq i32 %5, 0
  br label %7

  %8 = phi i1 [ false, %1 ], [ %6, %3 ]
  ret i1 %8
}

```

**Comment by rotateright** [comment]
Also note that there are multiple popcount transforms, so if we make any one of those target-dependent, we'd probably have to alter them all.

But we fail to canonicalize consistently - commuting the conditions gives a different result:
https://godbolt.org/z/Yxh8Kob3d

**Comment by rotateright** [comment]
We already have the generic expansion as requested, but it's predicated on custom-or-legal lowering:
https://github.com/llvm/llvm-project/blob/ac31781759889226711b801c3833fea280fdb7aa/llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp#L4040

AArch64 explicitly chooses the current lowering for a plain popcount:
https://github.com/llvm/llvm-project/blob/7aadecae404b8d47aabdd874e9018a76fd4d1ffa/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp#L7882

So we either want to change the generic combine to use a TLI hook or duplicate that expansion for AArch64? ( cc @davemgreen )

**Comment by rotateright** [comment]
Proposal to just copy some code (seems easier than the alternative):
https://reviews.llvm.org/D132237
