### ISSUE TITLE
Parallel build error in compile-rt on x86 FreeBSD 13.1

### ISSUE THREAD

**Issue by VoxSciurorum** [llvm/llvm-project#57224]
llvm release/15.x af3707c3b89f80ab7b43feb1345af24080105254 on FreeBSD 13.1 (native compiler clang 14), amd64.

A parallel build with make sometimes fails in compiler-rt with an error that 16 bit float is not supported.

```console
In file included from /data/llvm/llvm-project/compiler-rt/lib/builtins/extendhfsf2.c:11:
In file included from /data/llvm/llvm-project/compiler-rt/lib/builtins/fp_extend_impl.inc:38:
/data/llvm/llvm-project/compiler-rt/lib/builtins/fp_extend.h:44:9: error: _Float16 is not supported on this target
typedef _Float16 src_t;
        ^
1 error generated.
--- CMakeFiles/clang_rt.builtins-i386.dir/extendhfsf2.c.o ---
*** [CMakeFiles/clang_rt.builtins-i386.dir/extendhfsf2.c.o] Error code 1
```

This is a build of an i386 (32 bit) object on an x86_64 host.  i386 does not support 16 bit float unless you use `-msse2` or better.

This is probably a race.  It happens for me in most builds but not all.

Configured with:

```shell
cmake -DLLVM_ENABLE_PROJECTS="clang;flang;lldb;lld" -DLLVM_ENABLE_RUNTIMES=compiler-rt -DLLVM_TARGETS_TO_BUILD="AArch64;ARM;Mips;PowerPC;RISCV;Sparc;X86" -DLLVM_ENABLE_ASSERTIONS=On -DCMAKE_BUILD_TYPE=Release -DLLVM_OPTIMIZED_TABLEGEN=On /data/llvm/llvm-project/llvm
```

**Comment by jwakely** [comment]
I see this same error on x86_64 Fedora 36, also when building extendhfsf2.c with `-m32`

```
ninja: Entering directory `/home/jwakely/src/llvm/build'
[1/2751] Building C object projects/compiler-rt/li...keFiles/clang_rt.builtins-i386.dir/extendhfsf2.c.o
FAILED: projects/compiler-rt/lib/builtins/CMakeFiles/clang_rt.builtins-i386.dir/extendhfsf2.c.o 
/usr/bin/cc -DVISIBILITY_HIDDEN -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/jwakely/src/llvm/build/projects/compiler-rt/lib/builtins -I/home/jwakely/src/llvm/llvm-project/compiler-rt/lib/builtins -I/home/jwakely/src/llvm/build/include -I/home/jwakely/src/llvm/llvm-project/llvm/include -fPIC -fno-semantic-interposition -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -Wno-unused-parameter -O3 -DNDEBUG -m32 -fno-lto -DCOMPILER_RT_HAS_FLOAT16 -std=c11 -MD -MT projects/compiler-rt/lib/builtins/CMakeFiles/clang_rt.builtins-i386.dir/extendhfsf2.c.o -MF projects/compiler-rt/lib/builtins/CMakeFiles/clang_rt.builtins-i386.dir/extendhfsf2.c.o.d -o projects/compiler-rt/lib/builtins/CMakeFiles/clang_rt.builtins-i386.dir/extendhfsf2.c.o -c /home/jwakely/src/llvm/llvm-project/compiler-rt/lib/builtins/extendhfsf2.c
In file included from /home/jwakely/src/llvm/llvm-project/compiler-rt/lib/builtins/fp_extend_impl.inc:38,
                 from /home/jwakely/src/llvm/llvm-project/compiler-rt/lib/builtins/extendhfsf2.c:11:
/home/jwakely/src/llvm/llvm-project/compiler-rt/lib/builtins/fp_extend.h:44:9: warning: ISO C does not support the ‘_Float16’ type [-Wpedantic]
   44 | typedef _Float16 src_t;
      |         ^~~~~~~~
/home/jwakely/src/llvm/llvm-project/compiler-rt/lib/builtins/fp_extend.h:44:9: error: ‘_Float16’ is not supported on this target
/home/jwakely/src/llvm/llvm-project/compiler-rt/lib/builtins/fp_extend_impl.inc: In function ‘__extendXfYf2__’:
/home/jwakely/src/llvm/llvm-project/compiler-rt/lib/builtins/fp_extend_impl.inc:49:33: warning: unsigned conversion from ‘int’ to ‘src_rep_t’ {aka ‘const short unsigned int’} changes value from ‘67107840’ to ‘64512’ [-Woverflow]
   49 |   const src_rep_t srcInfinity = (src_rep_t)srcInfExp << srcSigBits;
      |                                 ^
In file included from /usr/lib/gcc/x86_64-redhat-linux/12/include/stdint.h:9,
                 from /home/jwakely/src/llvm/llvm-project/compiler-rt/lib/builtins/int_lib.h:95,
                 from /home/jwakely/src/llvm/llvm-project/compiler-rt/lib/builtins/fp_extend.h:17:
/home/jwakely/src/llvm/llvm-project/compiler-rt/lib/builtins/fp_extend_impl.inc:50:43: warning: unsigned conversion from ‘int’ to ‘src_rep_t’ {aka ‘const short unsigned int’} changes value from ‘-2147483648’ to ‘0’ [-Woverflow]
   50 |   const src_rep_t srcSignMask = SRC_REP_C(1) << (srcSigBits + srcExpBits);
      |                                           ^
/home/jwakely/src/llvm/llvm-project/compiler-rt/lib/builtins/fp_extend_impl.inc:50:33: note: in expansion of macro ‘SRC_REP_C’
   50 |   const src_rep_t srcSignMask = SRC_REP_C(1) << (srcSigBits + srcExpBits);
      |                                 ^~~~~~~~~
[10/2751] Linking CXX static library lib/x86_64-unknown-linux-gnu/libc++.a
ninja: build stopped: subcommand failed.
```

Configured with:

cmake -G Ninja  -DCMAKE_INSTALL_PREFIX:PATH=$HOME/src/llvm/latest -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_LINK_LLVM_DYLIB=ON -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;compiler-rt;libcxx;libcxxabi" ../llvm-project/llvm

**Comment by jwakely** [comment]
See https://reviews.llvm.org/D130718 and https://discourse.llvm.org/t/how-to-build-compiler-rt-for-new-x86-half-float-abi/63366

**Comment by jrtc27** [comment]
So, what's being done to fix this? This is currently the first issue you hit trying to run test-release.sh for x86_64-unknown-freebsd13, and supposedly there are more involving the libc++(abi) runtimes build (migrated from projects in 15) that are the reason there are no official 15.x binaries for FreeBSD, but aren't even being tracked anywhere.

**Comment by jrtc27** [comment]
Cc @tstellar as this is a release regression that's blocking release binaries

**Comment by MaskRay** [comment]
@phoebewang @DimitryAndric

**Comment by DimitryAndric** [comment]
See also https://reviews.llvm.org/D136044, but that would only solve the case for FreeBSD.

For a lot of system-dependent features (like `CRT_HAS_128BIT`) compiler-rt uses compile-time detection, usually with predefined macros. This will work, regardless of whether you are targeting one or another platform. (Assuming the macros are sufficient.)

However, for `COMPILER_RT_HAS_FLOAT16` and `COMPILER_RT_HAS_BFLOAT16` compiler-rt uses CMake configure-time detection, by compiling a small test program with the _default_ compilation flags, which typically are for the 'main' target, for example in our case x86_64.

But when you then compile the "second leg" of compiler-rt targeting i386, either by using `-m32` or by explicitly using `-target i386-undermydesk-freebsd`, the detected configuration for those flags is no longer valid.

So I think the fundamental problem is in the CMake logic for building the runtimes. E.g., that the CMake configure stage should be re-done for each possible target, and for each selected runtime. At the moment, it does not seem to do so.

**Comment by phoebewang** [comment]
@DimitryAndric has given a great explanation. Thanks @DimitryAndric!
I had suggested to add `-msse2` when using `-m32` in https://reviews.llvm.org/D130718 It still looks a practical method to me.

**Comment by jrtc27** [comment]
Then your baseline is wrong if you cross-compile

**Comment by phoebewang** [comment]
I don't know how cross-compile works, but as @DimitryAndric pointed out, the CMake logic has broken already. The generated configure comes from the host environment. A 64-bit host always set SSE2 to be true accoding to ABI. So I don't see any problem to set `-msse2` for `-m32` too. If this may result in problem in cross-compile, the problem should already exist.

**Comment by jrtc27** [comment]
The problem doesn't already exist, this thread is all about how compiler-rt just fails to build in the case that would be problematic.

**Comment by phoebewang** [comment]
The risk is in theory, but I'm not surprised this is the first problem we met.
I was thinking another way around that enabling `SSE2` with `-m32` in LLVM. Then, I found FreeBSD still has compliance in [supporting 486](https://people.freebsd.org/~rodrigc/doc/handbook/bsdinstall-hardware.html)
So, unless FreeBSD or others bump their minimum requirment on `i386`, we cannot always enable SSE2 with `-m32`.
Anyone could help with @DimitryAndric 's regression in https://reviews.llvm.org/D136044? It looks like the most feasible way we can use for this problem.

**Comment by jrtc27** [comment]
Debian's baseline also excludes SSE2 AFAIR

**Comment by tstellar** [comment]
Do we have a fix for this?

**Comment by MaskRay** [comment]
@arichardson Is your https://reviews.llvm.org/D145237 intended to fix this?

**Comment by arichardson** [comment]
@MaskRay I'm hopeful that it does fix the issue. My testing indicates that it should but it would be good if @DimitryAndric could confirm.

**Comment by hiraditya** [comment]
I verified https://reviews.llvm.org/D145237  and it worked.

**Comment by brad0** [comment]
> The risk is in theory, but I'm not surprised this is the first problem we met. I was thinking another way around that enabling `SSE2` with `-m32` in LLVM. Then, I found FreeBSD still has compliance in [supporting 486](https://people.freebsd.org/~rodrigc/doc/handbook/bsdinstall-hardware.html) So, unless FreeBSD or others bump their minimum requirment on `i386`, we cannot always enable SSE2 with `-m32`. Anyone could help with @DimitryAndric 's regression in https://reviews.llvm.org/D136044? It looks like the most feasible way we can use for this problem.

OpenBSD also targets 586.

**Comment by DimitryAndric** [comment]
Indeed https://reviews.llvm.org/D145237 works for me, and I suspect it will also work for OpenBSD, or other platforms that use -m64/-m32.
