### ISSUE TITLE
[flang] flang driver runs LLVM middle-end without setting DataLayout for the module

### ISSUE THREAD

**Issue by vzakhari** [llvm/llvm-project#57230]
Reproducer:
```f90
subroutine sub()
end subroutine sub
```

`flang-new -O1 -c test.f90 -mllvm -print-after-all -mllvm -print-before-all`:
```llvm
*** IR Dump Before Annotation2MetadataPass on [module] ***
; ModuleID = 'FIRModule'
source_filename = "FIRModule"
target triple = "x86_64-unknown-linux-gnu"

declare ptr @malloc(i64)

declare void @free(ptr)

define void @sub_() !dbg !3 {
  ret void, !dbg !7
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!2}

!0 = distinct !DICompileUnit(language: DW_LANG_C, file: !1, producer: "mlir", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
!1 = !DIFile(filename: "FIRModule", directory: "/")
!2 = !{i32 2, !"Debug Info Version", i32 3}
!3 = distinct !DISubprogram(name: "sub_", linkageName: "sub_", scope: null, file: !4, line: 1, type: !5, scopeLine: 1, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !6)
!4 = !DIFile(filename: "./test.f90", directory: "/tmp")
!5 = !DISubroutineType(types: !6)
!6 = !{}
!7 = !DILocation(line: 2, column: 1, scope: !8)
!8 = !DILexicalBlockFile(scope: !3, file: !4, discriminator: 0)
```

Notice that there is no `target datalayout` defined for the module.  The data layout gets defined late in `CodeGenAction::executeAction()` so this setting only affects LLVM back-end, but LLVM middle-end also relies on the data layout, e.g. `DL` defines behavior of `InstCombine` optimization (see `llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:InstCombinerImpl::shouldChangeType()`).

It looks like the data layout setting has to be moved to `flang/lib/Frontend/FrontendActions.cpp:CodeGenAction::generateLLVMIR()`.

**Comment by vzakhari** [comment]
@banach-space, FYI.

**Comment by vzakhari** [comment]
It seems that MLIR->LLVM `ModuleTranslation` supports `llvm.data_layout` module attribute, but the support is limited:
```
/// Translates the given data layout spec attribute to the LLVM IR data layout.
/// Only integer, float and endianness entries are currently supported.
```

So it may still make sense to explicitly set complete data layout in the driver.

**Comment by vzakhari** [comment]
It seems we may want to set the data layout even earlier - in MLIR.  Possible approach is implemented by `Polygeist` [here](https://github.com/llvm/Polygeist/blob/fc15676b30c80ac1adb10f4fc3e7d7e8fe3ed7b6/tools/cgeist/Lib/clang-mlir.cc#L5513): create `llvm::DataLayout` based on the target and translate it into `mlir::DataLayout` using `translateDataLayout()` (I suppose it is coming from `mlir/lib/Target/LLVMIR/ConvertFromLLVMIR.cpp`, though, I am not sure how complete the implementation is right now).

**Comment by banach-space** [comment]
Good catch @vzakhari !

Moving data layout set-up to `CodeGenAction::generateLLVMIR()` makes sense as that's going to fix the problem that you are reporting here. Setting it up earlier might be needed at some point, but I'd rather cross that bridge when we get to it. Basically, I'm trying to make sure that every change that we make has a clear justification.

It's a strong opinion weakly held ;-)

-Andrzej

**Comment by banach-space** [comment]
> I have an example justifying MLIR data layout :)

👍🏻 Do you have the bandwidth to implement this?

**Comment by vzakhari** [comment]
> 👍🏻 Do you have the bandwidth to implement this?

Not right now, unfortunately.

**Comment by Leporacanthicus** [comment]
Should now be in main.
