### ISSUE TITLE
libc++ 14.0 release notes still say 14.0 is "upcoming"

### ISSUE THREAD

**Issue by maxnoe** [llvm/llvm-project#57236]
See: https://releases.llvm.org/14.0.0/projects/libcxx/docs/ReleaseNotes.html

Seems it hasn't been updated after the release was made.

**Comment by philnik777** [comment]
@tstellar Are you responsible for this? If not, do you know who is?

**Comment by tru** [comment]
Hmm. Tom is out now - I am not 100% sure how fix this - Maybe @zmodem knows since he did the releases before.

**Comment by zmodem** [comment]
Generally these "in-progress" / "upcoming" notices need to be removed from the release notes before the release.

I suppose it's technically possible to remove them on the 14.x branch and re-build and re-publish those docs. That would mean the docs don't match what was in the -final tag though, so I'd leave that decision to Tom.

More importantly, we should make sure not to forget to update the 15.x docs before -final. For example I see that the libcxx ones still have the "in-progress" and "upcoming" wording.

**Comment by tru** [comment]
So this is a manual commit that changes on these branches - no directive to sphinx or similar?

**Comment by zmodem** [comment]
Right, it's a manual change to the docs. I would normally do it when proof reading the release notes towards the end of the release.

**Comment by tru** [comment]
So in short - won't fix this for 14.x - but it will be fixed in 15.x.
