### ISSUE TITLE
Possible miscompilation with volatile in loop

### ISSUE THREAD

**Issue by edliaw** [llvm/llvm-project#57234]
I compiled the following test from the linux test project with clang 14.0.6 (`clang -D_FORTIFY_SOURCE=2 -g -O2 -pthread  signal06.c -o signal06`):
https://gist.github.com/edliaw/a176f4be8455a067bded6fbc9359bd1b

And was running into errors that seemed to suggest that `loop` was being optimized away, despite being evaluated with D (which is tagged volatile) in `while (D == VALUE && loop < LOOPS) {`.  By tagging `volatile int loop = 0` on line 59, I was able to get the test to work.

In the disassembly, incrementing `loop` is using `leal` instead of `addl` (in the working case and gcc).  I'm not familiar with how these instructions work, but hoping someone that knows more can help:

* unmodified with clang https://gist.github.com/edliaw/8a01ca56144672791e3150b0ab7dd0e5
* volatile int loop with clang https://gist.github.com/edliaw/6d4f73a58fb42c10fd78c974d0145c10
* unmodified with gcc https://gist.github.com/edliaw/45e0e14ae55225f4b28deef11e37d590

**Comment by topperc** [comment]
Can you try adding "cx" to the clobber list for the syscall inline asm?

**Comment by edliaw** [comment]
You're right, adding "cx" worked.

**Comment by topperc** [comment]
Can we close this bug then?

**Comment by edliaw** [comment]
Yes, thank you.
