### ISSUE TITLE
[clang tools]How to make clang tool execute the CodeGen process.

### ISSUE THREAD

**Issue by killerloura** [llvm/llvm-project#57244]
I created a clang tool to analyze AST and get the required information. I add a `FrontendAction`.  I also noticed `CodegenAction` class. But I can't use `CodegenAction` class in same way. Thank you.

code: `main()`
```cpp
int main(int argc, const char **argv)
{
    cout<<"tools start"<<endl;
    auto Op = CommonOptionsParser::create(argc, argv, MyToolCategory);
    if(!Op){llvm::errs()<<Op.takeError();return 1;}
    CommonOptionsParser &Opg=Op.get();
    
    ClangTool Tool(Opg.getCompilations(),Opg.getSourcePathList());
    Matrix_ident matrixidenter;
    MatchFinder Finder;
    Finder.addMatcher(MatrixMatcher, &matrixidenter);
    Tool.run(newFrontendActionFactory(&Finder).get());
    
    cout<<"tools finish"<<endl;
    return 0;
}
```

**Comment by killerloura** [comment]
My target is output the information obtained by clangtool to metadata. So I want execute the Codegen process in my clang tool.

**Comment by vfdff** [comment]
it is not llvm issue, probably in the **https://discourse.llvm.org/c/llvm** more appropriate to put your question?

**Comment by killerloura** [comment]
> it is not llvm issue, probably in the **https://discourse.llvm.org/c/llvm** more appropriate to put your question?

It is my fault, thank you.
