### ISSUE TITLE
merge-fdata missed in llvm-project/build/bin

### ISSUE THREAD

**Issue by not4juu** [llvm/llvm-project#57249]
Hi,

Could you please let me know if something change in the build chain as under (any additional flag is needed?):
llvm-project//build/bin
I can only find compiled binaries:
llvm-bolt  llvm-boltdiff  llvm-lit  llvm-tblgen  perf2bolt

and merge-fdata binary is not available in any other folder 

Thanks in advance

**Comment by not4juu** [comment]
As WA https://github.com/llvm/llvm-project/blob/main/bolt/README.md#manual-build I use "ninja" instead of "ninja bolt" but if I carefully check it's not reflected in README.md, I am not sure which is an author's intention

**Comment by aaupov** [comment]
Thanks for flagging! We will add merge-fdata to `bolt` target. 
You can use `ninja bolt merge-fdata` in the meantime.

**Comment by aaupov** [comment]
https://reviews.llvm.org/D139972
