### ISSUE TITLE
 coroutine optimizer too aggressive for thread local variables

### ISSUE THREAD

**Issue by PeterWilliamNorth** [llvm/llvm-project#57260]
Using cpp reference sample: [co_await](https://en.cppreference.com/w/cpp/language/coroutines#co_await)
On godbolt clang trunk with "-std=c++20 -pthread" get correct, expected output... 
_Coroutine started on thread: 140410345137984
New thread ID: 140410345133824
Coroutine resumed on thread: 140410345133824_
Adding any of "-O2" or "-O3" or "-Ofast" gives incorrect output... (thread id in co-routine incorrectly preserved across co_await)
_Coroutine started on thread: 140442470807360
New thread ID: 140442470803200
Coroutine resumed on thread: **140442470807360** _
This seems to be a recent (last month or two) regression.
MSVC had this problem about a year ago ... dis-able 'fiber' optimization was their temporary fix, their trunk now works without /GT.
[fiber-safe thread-local storage](https://docs.microsoft.com/en-us/cpp/build/reference/gt-support-fiber-safe-thread-local-storage?view=msvc-170)

**Comment by vogelsgesang** [comment]
This looks very similar to #47179 and #47177.  @ChuanqiXu9 is currently looking into this calls of issues and from your description, I think https://reviews.llvm.org/D127383 will fix this.
Would be helpful, though, if you could share a link to a self-contained godbolt repro, @PeterWilliamNorth

**Comment by ChuanqiXu9** [comment]
Yes, I think this is duplicated. I wish we could fix this in clang16.. The bug has been reported for 3 years..
