### ISSUE TITLE
clang prints LLVM warnings on the google/filament project: WARNING: :0:0:0: The function '%142 = OpFunction %7 None %134' could not be inlined because the return instruction is not at the end of the function. This could be fixed by running merge-return before inlining.

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#57267]
See details in the [FreeBSD bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265949).

https://github.com/google/filament

clang-14.

**Comment by efriedma-quic** [comment]
The LLVM source code does not contain the text of the warning in question; it appears to be generated by SPIRV-Tools.
