### ISSUE TITLE
clang-format: Consider one statement per line for chained bool equalities

### ISSUE THREAD

**Issue by aeubanks** [llvm/llvm-project#57280]
```c
bool f() {
  return display_id == other.display_id &&
         parent_display_id == other.parent_display_id &&
         position == other.position && offset == other.offset &&
         offset_reference == other.offset_reference;
}
```

personal preference, but it's easy to miss that the third line actually has two equalities

feel free to close if you disagree/not worth the effort

**Comment by gedare** [comment]
It may be worth adding this as an option to the `BreakBinaryOperations` as the current `OnePerLine` introduces counter-intuitive breaks like:
```
-    ( mask & MASK ) != 0 &&
+    ( mask & MASK ) !=
+    0 &&
```

**Comment by owenca** [comment]
`BreakBinaryOperations: RespectPrecedence` already covers this.
