### ISSUE TITLE
clang-format indents java new array expression poorly

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#57294]
Consider:

```console
$ cat | clang-format -style=chromium --assume-filename=x.java
class C {
  public void f() {
    waitForKeyboardStates(3, 1, 5, new Integer[] {TextInputType.NUMBER, TextInputType.NUMBER, TextInputType.NUMBER, TextInputType.TEXT});
  } 
}
```

it prints:

```java
class C {
    public void f() {
        waitForKeyboardStates(3, 1, 5,
                new Integer[] {TextInputType.NUMBER, TextInputType.NUMBER, TextInputType.NUMBER,
                        TextInputType.TEXT});
    }
}
```

It would have been nicer to align the `TextInputType` values, as it would do if we drop the `--assume-filename` argument:

```java
class C {
 public
  void f() {
    waitForKeyboardStates(
        3, 1, 5,
        new Integer[]{TextInputType.NUMBER, TextInputType.NUMBER,
                      TextInputType.NUMBER, TextInputType.TEXT});
  }
}
```

**Comment by mydeveloperday** [comment]
Without looking too deeply this would suggest that without the assume file it doesn't know you are using java, as Chromium inherits its style from Google and both Goolge style and Chromium style make changes if the language is java to the configuration then I think its no that clang-format is doing the wrong thing but that you haven't told clang-format what style you want.

Ultimately we cannot change the default styles.. but if I put your example into a file called test1.java and run both with BasedOnStyle: Google and BasedOnStyle: Chromium then both show the undesired output

If I run it with LLVM its as you desired

(I believe this means its down to the changes in the google style for Java)

```c++
if (Language == FormatStyle::LK_Java) {
    GoogleStyle.AlignAfterOpenBracket = FormatStyle::BAS_DontAlign;
    GoogleStyle.AlignOperands = FormatStyle::OAS_DontAlign;
    GoogleStyle.AlignTrailingComments = false;
    GoogleStyle.AllowShortFunctionsOnASingleLine = FormatStyle::SFS_Empty;
    GoogleStyle.AllowShortIfStatementsOnASingleLine = FormatStyle::SIS_Never;
    GoogleStyle.AlwaysBreakBeforeMultilineStrings = false;
    GoogleStyle.BreakBeforeBinaryOperators = FormatStyle::BOS_NonAssignment;
    GoogleStyle.ColumnLimit = 100;
    GoogleStyle.SpaceAfterCStyleCast = true;
    GoogleStyle.SpacesBeforeTrailingComments = 1;
  }
```

By a process of elimination, this is what you need in your config to get what you want

```yaml
BasedOnStyle: Chromium
AlignAfterOpenBracket: Align
ColumnLimit: 80
```

**Comment by zmodem** [comment]
Thanks for investigating! I don't know how the current style was set exactly, but it sounds like this is working as intended based on that. Let's close.
