### ISSUE TITLE
clang generating wrong relocation info for ARM

### ISSUE THREAD

**Issue by akshaykumars614** [llvm/llvm-project#57296]
when you generate the elf for the following code 
https://godbolt.org/z/aYc6h33j7
using
`$ readelf -a <testcase.o>`
the clang is supposed to generate `R_ARM_NONE` type for `.text.func2` symbol name  in `.rel.debug_loc` relocation section.
tried with clang13.0.1

**Comment by smithp35** [comment]
I'm not sure why R_ARM_NONE is appropriate here. Looking at the DWARF4 spec (.debug_loc has been replaced in DWARF5) the
arm-none-eabi-readelf rel.o --debug-dump=loc
```Contents of the .debug_loc section:

    Offset   Begin            End              Expression
    00000000 ffffffff 00000000 (base address)
    00000008 00000000 00000004 (DW_OP_reg0 (r0))
    00000013 00000004 00000018 (DW_OP_GNU_entry_value: (DW_OP_reg0 (r0)); DW_OP_stack_value)
    00000021 <End of list>  

    Relocation section '.rel.debug_loc' at offset 0x64c contains 1 entry:
    Offset     Info    Type            Sym.Value  Sym. Name
    00000004  00000802 R_ARM_ABS32       00000000   .text.func2

Quoting from DWARF4
A base address selection entry consists of:
1. The value of the largest representable address offset (for example, 0xffffffff when the size of
an address is 32 bits).
2. An address, which defines the appropriate base address for use in interpreting the beginning
and ending address offsets of subsequent entries of the location list.

The relocation is placed on the place of "An address". To generate that address would require an R_ARM_ABS32 relocation as has been provided. A R_ARM_NONE will do nothing, leaving 0. It is only used to identify dependencies between section.

Can you say why the relocation should be R_ARM_NONE

**Comment by UmeshKalappa0** [comment]
@smithp35 ,we have the custom linker and ABS32 reloc makes func2 not to remove from final executable and which is not optimal.

**Comment by smithp35** [comment]
The model for linker's that clang/gcc use is that relocations from debug sections are not sufficient to mark a non-debug section live.

This has consequences, in particular linker's have to handle "dangling" relocations from debug sections to code that has been removed. The usual way to handle this is to set the value to a "tombstone" see LLD's -z dead-reloc-in-nonalloc 
There has been some thought of the linker or another tool rewriting debug information, but nothing concrete as yet https://groups.google.com/g/llvm-dev/c/gcEs4ITJI_A/m/clsFB3fhBQAJ  

I should also mention that by the Arm ABI, the R_ARM_NONE relocation behaves the same as R_ARM_ABS32 when it comes to garbage collection.

In any case I don't think that LLVM developers would consider this a defect. Sadly dangling relocations from debug sections, like in .eh_frame, is a special case that clang (and gcc) expect a linker to handle.
