### ISSUE TITLE
DCE improved when using dependant if statements 

### ISSUE THREAD

**Issue by ThomasMayerl** [llvm/llvm-project#57299]
Sometimes, the compiler's ability to detect and eliminate dead code improves when using dependant if statements. For example, LLVM cannot detect the dead code in the following example:

```c
#include <stdbool.h>

void DCEMarker0_();

void f(bool scr1_scr1_scr2, bool scr1, bool cr1_scr, bool r1, bool c) {
    if (scr1) {
        if (((!scr1_scr1_scr2 == !r1) && (r1 && !(scr1_scr1_scr2)))) {
            DCEMarker0_();
        }
    }
}
```

Now instead of the function call, a variable is assigned. As the if is dead, the variable is always false. Now we also add new if statements having the same formulas as before but we add a disjunction with this variable:

```c
#include <stdbool.h>

void DCEMarker0_();

void f(bool scr1_scr1_scr2, bool scr1, bool cr1_scr, bool r1, bool c) {
    int intermediate_result = 0;
    if (scr1) {
        if (((!scr1_scr1_scr2 == !r1) && (r1 && !(scr1_scr1_scr2)))) {
            intermediate_result = 1;
        }
    }
    if (scr1 || intermediate_result) {
        if (((!scr1_scr1_scr2 == !r1) && (r1 && !(scr1_scr1_scr2))) || intermediate_result) {
            DCEMarker0_();
        }
    }
}
```

LLVM is now able to eliminate the dead code. If the marker function call is added before the assignment within the if, DCE also breaks and generates calls for both markers. However, no additional checks are generated - so, LLVM knows that the if expressions are dependant on each other. 

```c
#include <stdbool.h>

void DCEMarker0_();

void f(bool scr1_scr1_scr2, bool scr1, bool cr1_scr, bool r1, bool c) {
    int intermediate_result = 0;
    if (scr1) {
        if (((!scr1_scr1_scr2 == !r1) && (r1 && !(scr1_scr1_scr2)))) {
            DCEMarker0_();
            intermediate_result = 1;
        }
    }
    if (scr1 || intermediate_result) {
        if (((!scr1_scr1_scr2 == !r1) && (r1 && !(scr1_scr1_scr2))) || intermediate_result) {
            DCEMarker0_();
        }
    }
}

```
This issue is the inverse to #57028. 

This behaviour was observed locally using -O3 and commit f3acb54c1b7b7721cea5c07f64194151dddd3c4b

It was also observed using CompilerExplorer: https://godbolt.org/z/GGMEEMo36

(Might be related to #56711)

**Comment by rotateright** [comment]
Fixed after:
5c759edc57d6
