### ISSUE TITLE
clang-format removes space between 'override' and curly brace when there's a trailing semicolon

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#57305]
Consider:

```console
$ echo 'struct S { void f() override {}; };' | clang-format -style=chromium
struct S {
  void f() override{};
};
```
Note the missing space between `override` and `{`.

This only seems to happen when there's a trailing semicolon --- which is of course unnecessary and `-Wextra-semi` warns about it --- but it would be nice if clang-format could handle it.

**Comment by rymiel** [comment]
Issue is probably somewhere around here: https://github.com/llvm/llvm-project/blob/8856137ce7450f17a892f9aeda2d0e5f39c05283/clang/lib/Format/UnwrappedLineParser.cpp#L696-L713

It is infact doing what the comment says, but I guess it needs extra context that it's parsing a declaration

FWIW, all that's needed to reproduce this is `void f() {};`, which gets formatted into `void f(){};`. Putting any statement in the curly braces correctly makes the braces act as `FunctionLBrace`

**Comment by mydeveloperday** [comment]
Oh! definitely related 
```c++
void a() {}
void a() {}
void a() { return a; }
void a() { return a; }
void a() override {}
void a() override{};
```

**Comment by mydeveloperday** [comment]
Very much seems to come down to what tryToParseBracedList() thinks...

![image](https://user-images.githubusercontent.com/16046346/194754380-ecf982cb-445c-4d0a-9773-2ed37d1e681e.png)

**Comment by mydeveloperday** [comment]
Perhaps we need another pass, after the assignment of TT_FunctionDeclarationName, where we go back over and set the TT_FunctionLBrace, and find the unnecessary `;` after the empty `{}`.

I think this could fix the spacing and mark the ; optional so they get removed later

@owenca any thoughts?

```C++
TokenAnnotator Annotator(Style, Keywords);
 Annotator.annotate(Line);
 Annotator.calculateFormattingInformation(Line);

 Annotator.enusreFunctionLBrace();
 ^^^^^
```

**Comment by mydeveloperday** [comment]
More test cases

```c++
void a() {}
void a(){};
void a() { return a; }
void a() { return a; }
void a() override {}
void a() override{};
void a() noexcept {}
void a() noexcept(false){};
auto a() -> void {}
auto a() -> void{};
```

**Comment by owenca** [comment]
> Perhaps we need another pass, after the assignment of TT_FunctionDeclarationName, where we go back over and set the TT_FunctionLBrace, and find the unnecessary `;` after the empty `{}`.
>
> I think this could fix the spacing and mark the ; optional so they get removed later
>
> @owenca any thoughts?

It might work, but I don't think it's worth fixing, especially at the cost of adding another pass.

BTW I succeeded in fixing all of the above test cases (except `void a() noexcept(false){};`) and passing `FormatTests` (including the empty function test cases for `RemoveSemicolon`) without calling the annotator in the parser. However, I abandoned the work because it didn't cover function definitions with a trailing return type, etc.
