### ISSUE TITLE
Clang fails to deduce template template parameter

### ISSUE THREAD

**Issue by vsadnikapokalipsisa322** [llvm/llvm-project#57318]
Clang: https://godbolt.org/z/hrKKdM4rG
GCC: https://godbolt.org/z/hcooYad34

**Comment by vsadnikapokalipsisa322** [comment]
If I explicitly set the template parameters -- clang still fails
https://godbolt.org/z/4dYbh7q8s
However, if I use alias for map, everithing works:
https://godbolt.org/z/67r1dnWcE
I guess the problem is somewhere near the implicitly-defaulted template parameters of std::unordered_map

**Comment by royjacobson** [comment]
This is a known problem, see #45518.

You might get the intended behavior with the flag `-frelaxed-template-template-args`.

**Comment by vsadnikapokalipsisa322** [comment]
@royjacobson this option help, thank you!
