### ISSUE TITLE
[LoopVectorize] Diff check is not emitted correctly in nested loop

### ISSUE THREAD

**Issue by kpdev** [llvm/llvm-project#57315]
Consider following nested loop

```c
void subtract_arrays(unsigned int *a, unsigned int *b, int len) {
    int i, j;
    for(j = 0; j < len; j++) {
        for(i = 0; i < len; i++) {
            a[j] = a[j] - b[i];
        }
    }
}
```

Generated code will produce incorrect result if loop vectorizer is enabled and arrays a and b overlap.
The reason is that LLVM does not emit runtime check for the nested loop and always executes vectorized version of a loop.
This happens because read access for array ‘a’ is moved by LICM outside of the nested loop to a parent loop and is therefore not seen by loop analysis.

**Comment by kpdev** [comment]
Possible fix: https://reviews.llvm.org/D132490

**Comment by fhahn** [comment]
Thanks for sharing the test case!

I tried to add it to the llvm-test-suite runtime tests, but it seems to pass on X86: https://reviews.llvm.org/D132551
 
Any ideas what could be going on?

**Comment by fhahn** [comment]
Reopening to cherry-pick onto release

**Comment by fhahn** [comment]
/cherry-pick 6e56779e6bc168a3acd14f9bf2c4fd3fd9d86bd1 e117137af0a37ac309d40db57ec7162ef3d22c29 9405af1c850139f6ddd6d35ff395756fe2aef31f

**Comment by fhahn** [comment]
/cherry-pick 3b135ef446d56e8542d55a1b716e9413f50da7aa 6e56779e6bc168a3acd14f9bf2c4fd3fd9d86bd1 e117137af0a37ac309d40db57ec7162ef3d22c29  9405af1c850139f6ddd6d35ff395756fe2aef31f

**Comment by fhahn** [comment]
@tstellar could you help with merging the PR (https://github.com/llvm/llvm-project-release-prs/pull/133) to fix this issue on the release branch? It looks like all tests have passed but it didn't get merged automatically.

**Comment by fhahn** [comment]
I think it should be safe; it's big but mostly because of converting the test file to use opaque pointers and then adding a few additional test cases. So most of the diff should just be NFC test improvements. 

3e6cff23e9bccc3b4a2f726eff8f4debe612a1b2 is the real functional change, the code change is very small and purely restricts existing behavior.

**Comment by tru** [comment]
Ok! I'll queue it for a merge then!

**Comment by fhahn** [comment]
Thank you very much @tru!
