### ISSUE TITLE
[clang] Destroying a coroutine with a throwing promise_type::unhandled_exception() can call destructor of final_suspend() return-value even though final_suspend() was never called

### ISSUE THREAD

**Issue by lewissbaker** [llvm/llvm-project#57339]
See https://godbolt.org/z/9hn3s3a34

Expected output:
```console
maybe_throwing()
final_suspend()
final_awaiter()
final_awaiter::await_ready()
final_awaiter::await_suspend()
coro.destroy()
~final_awaiter()
-------
maybe_throwing()
unhandled_exception()
coro.destroy()
caught X
```

Actual output:
```console
maybe_throwing()
final_suspend()
final_awaiter()
final_awaiter::await_ready()
final_awaiter::await_suspend()
coro.destroy()
~final_awaiter()
-------
maybe_throwing()
unhandled_exception()
coro.destroy()
~final_awaiter()
caught X
```

If the coroutine runs to completion naturally and we suspend at the final-suspend point then `coroutine_handle::destroy()` correctly destroys the temporary object returned from `promise.final_suspend()`.

However, if the same coroutine can also complete with an exception, and the exception is rethrown from `unhandled_exception()` then the coroutine is also considered suspended at the final-suspend point.

Unfortunately, the `destroy()` call follows the same code-path for all final-suspend points which assumes that we are destroying at a point in the program inside the scope of the `co_await promise.final_suspend()` expression, even though we reached a final-suspend point that did not begin evaluating the `co_await promise.final_suspend()` expression.

The logic for suspending at the final-suspend point only stores a nullptr in the resume-function-pointer slot - which indicates that the coroutine is at a final-suspend-point and thus returns `true` from `coroutine_handle::done()`. It does not update the suspend-point index and `[clone .destroy()]` cannot therefore distinguish between the two final-suspend-points.

I think in the case that the `promise_type::unhandled_exception()` method is potentially throwing and thus the coroutine has two potential final-suspend-points, the compiler needs to generate code for the two final-suspend points that stores a unique suspend-point index for each and then uses the suspend-point index to dispatch to the correct path (one that destroys the `final_suspend()` temporaries, and one that does not) rather than looking at the resume-function-pointer.

**Comment by ChuanqiXu9** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/17631ac676bc44b7fd5c79abc66844efb4e1b533.

Thanks for reporting and the precise analysis! It saves me a lot of time!
