### ISSUE TITLE
[clang-tidy] Add a check to find unused variables after copy

### ISSUE THREAD

**Issue by Febbe** [llvm/llvm-project#57344]
clang-tidy does not warn, when a large movable object is copied instead of moved, and when the object is itself unused after the copy.

For example: 
```cpp
MyObj::fun(std::vector<size_t> large_list){
    this->large_list = large_list;
//                     ^_______ expecting "object can be moved" here
}
// ^_______ expecting "object unused before destruction" here
```

It would be useful to add a check, which searches for those objects to increase performance.
I propose `performance-unused-objects`

**Comment by firewave** [comment]
See also #53489.
