### ISSUE TITLE
Should we revert non-POD ABI fix in LLVM 15?

### ISSUE THREAD

**Issue by dwblaikie** [llvm/llvm-project#57346]
Open question from https://reviews.llvm.org/D118511 - the ABI change was reverted from 14 since there were some outstanding/follow-on/related ABI issues still pending (https://reviews.llvm.org/D119051) and those issues are still pending (though gathering some momentum, don't look like they'd make it into 15).

So, we should probably punt the ABI change again? (maybe it'd be best just to revert it on main too until we get the consetllation of pod ABI things sorted out together?)

**Comment by tru** [comment]
@dwblaikie i was planning to do the last rc tomorrow (Eu) time - so it would be good if we knew what to do by then - otherwise I think we probably have to roll another rc before final.

**Comment by dwblaikie** [comment]
I don't have strong feelings either way - I don't think we'll get more data to make a better answer (the constellatio nof ABI issues will not be resolved/fixed within days - maybe weeks at best) - so you should make whatever decision's best for the release, which probably means reverting on the release branch, I think? But I really leave that choice up to you release folks as I don't have a strong sense of what's suitable or not - just extrapolating from the choice in the previous decision - seems we're in the same situation and should make the same decision.

**Comment by tru** [comment]
I read back to the previous revert and I agree. I will revert in the release branch tomorrow before I cut the rc. Thanks!

**Comment by tru** [comment]
@dwblaikie I reverted in https://github.com/llvm/llvm-project-release-prs/commit/12f27d8bef9387e2e3837f604ccd8a457d927053 - the revert was a bit messy because things have shifted around - but I kept the abi14 flag, which I am not sure is entirely correct.

Let me know if it looks alright with you or not. I can still work on it before -final.

**Comment by dwblaikie** [comment]
> but I kept the abi14 flag, which I am not sure is entirely correct.

my understanding is that's probably fine - I believe the versions are accepted by the frontend anyway, even if we don't have an internal specific version flag to map them to - so no harm in having it around, all the version checks are relative anyway so anytihng that's checking for >= some ABI version will keep working whether or not there's an extra unused version number in the enum, etc.

**Comment by tru** [comment]
Thanks - I will consider this closed for 15.x then. I think it would be good to figure it out before 16 so we don't have to revert again :)
