### ISSUE TITLE
Potential Clang miscompilation issue caused by 7171615099142ed49042c0f27af437b05150dd9b

### ISSUE THREAD

**Issue by zeroomega** [llvm/llvm-project#57351]
[clang-crashreports.zip](https://github.com/llvm/llvm-project/files/9419974/clang-crashreports.zip)

We are seeing Fuchsia build failures when using Tip-of-Tree clang after change 7171615099142ed49042c0f27af437b05150dd9b was landed. After examine the failure, we suspect it there might be a bug introduced in change 7171615099142ed49042c0f27af437b05150dd9b causing the clang to miscompile certain code.

In the attachment is the clang reproducer generated from affected TU from Fuchsia source tree.  `test_built_7171615.o` is the output generated from the reproducer using clang revision 7171615099142ed49042c0f27af437b05150dd9b and `test_built_ba8b5f.o` is the output generated from clang revision ba8b5ff874ad438a07ac3cc4f2bc75898b1401f8 (parent revision of 7171615099142ed49042c0f27af437b05150dd9b).  `test_7171615_readelf.txt` and `test_ba8b5f_readelf.txt` are readelf output from compiled TU using 2 different clangs. 

From readelf output, it looks like a large numbers of symbols are missing from the binary compiled using 7171615099142ed49042c0f27af437b05150dd9b. In `.rela.text._Z8TestMainPvN4arch10EarlyTicksE`, number of entries dropped from 139 to 63. The `AddOne` function defined at L194742 in the TU is completely missing from the readelf results from 7171615099142ed49042c0f27af437b05150dd9b. While we have not yet fully understand why change 7171615099142ed49042c0f27af437b05150dd9b causes the differences we are seeing here, we suspect this change introduced a bug that caused the miscompilation issue and need to be investigated and fixed.

**Comment by royjacobson** [comment]
Thanks for the report!

I've reverted for now after I've been able to confirm this locally. This patch shouldn't have changed C++17 code so it definitely seems like a bug.

**Comment by royjacobson** [comment]
Committed the patch with a fix for this problem.

**Comment by EugeneZelenko** [comment]
@royjacobson: Could you please specify commit hash?

**Comment by royjacobson** [comment]
sure, b1c960fc6dc2891c8d2ca09c184572ca0857ba15
