### ISSUE TITLE
Colorize output when searching for symbols in `lldb`

### ISSUE THREAD

**Issue by alichtman** [llvm/llvm-project#57372]
`ripgrep` and `grep` have great colorization options for easily parsing search output.

Here's `rg`, for example: 

<img width="356" alt="image" src="https://user-images.githubusercontent.com/20600565/186795335-eac0c080-45c1-42b2-b207-b3d3797a080a.png">

It would be really great if `lldb` supported this for `image lookup -r -n <REGEXP>` and other like commands.

**Comment by jimingham** [comment]
lldb does support colored output - there's actually dedicated syntax for it in the frame & thread format, and people have been adding color code in other cases where it makes sense.  Should be pretty straightforward to add to the image lookup output as well.  If someone decides to take this on, remember that there's a use-color setting that you have to obey as well.

Jim

**Comment by varunkumare99** [comment]
I would like to look work on this issue.
I'm new to LLVM (gone through kaleidoscope tutorials and building JIT).
Any advice on how to begin?

thanks!

**Comment by DavidSpickett** [comment]
Well first off make sure you can build and run the test suite succesfully: https://lldb.llvm.org/resources/build.html

The conversion from the format Jim mentioned is in `lldb/include/lldb/Utility/AnsiTerminal.h`, but you'll want to find who actually calls that.

A command that uses this already is `frame`. Make a simple hello world and break in main, then:
```
(lldb) frame info
frame #0: 0x0000aaaaaaaaa740 test.o`main at test.cpp:9:3
```
You'll see that line is coloured.

That command is defined in https://github.com/llvm/llvm-project/blob/feea7ef23cb1bef92d363cc613052f8f3a878fc2/lldb/source/Commands/CommandObjectFrame.cpp#L193. See `DoExecute`.

I suggest from there that you follow the callstack down and you'll see where colour tags are inserted. I really recommend using an IDE for this as you can just "go to definition" on each caller.

Or you can debug the debugger if you want, but again, a good IDE should be enough. I replied to someone else about debugging lldb itself here https://discourse.llvm.org/t/how-to-debug-lldb-source-codes/65598/2?u=davidspickett.

Once you get how `frame info` does it, stick some calls in the symbol comands and see what you can come up with. This would be a nice improvement.

**Comment by varunkumare99** [comment]
thank you.
I'm working on it.

**Comment by varunkumare99** [comment]
The color tags for `frame info` are set from `CoreProperties.td `. It has python code, that defines a format string to add color to `frame info`.
I could not figure out how this python code is read by `lldb`.  There seems be no calls to read `CoreProperties.td` from `cpp lldb` code.

**Comment by DavidSpickett** [comment]
So this is an instance of https://discourse.llvm.org/t/cant-find-all-values-of-enum-attrkind-in-attributes-h-file/65869/2?u=davidspickett 

See if that helps any, this is a very common thing to trip over. Still gets me sometimes.

Once you find where the `.inc` is included, there's probably a few more layers to get through before cpp directly reads it. Some macro generation and whatnot.

The other way to do it is to say ok we know this string comes to `frame` somehow, can we find where the command reads the string from, by reading just the command's source. Rather than following the trail from the user provided string all the way to `frame`.

Since what you want to do really is hardcode/generate a similar string but in `image lookup`. So the mechanism where one can override it isn't so important for the moment.

**Comment by varunkumare99** [comment]
The image lookup command is defined in:
https://github.com/llvm/llvm-project/blob/b13f7f9c06604110709a968a2fece4b8d5192708/lldb/source/Commands/CommandObjectTarget.cpp#L3875

regular expression matching is done in function `LookupSymbolInModule`
https://github.com/llvm/llvm-project/blob/b13f7f9c06604110709a968a2fece4b8d5192708/lldb/source/Commands/CommandObjectTarget.cpp#L1527

which calls  ` RegularExpression` match via  `Symtab::AppendSymbolIndexesMatchingRegExAndType`
https://github.com/llvm/llvm-project/blob/f793597f6d5d8eb86388263ce16365ceb10fee23/lldb/source/Utility/RegularExpression.cpp#L28

which further calls,` llvm's Regex match` function
https://github.com/llvm/llvm-project/blob/f793597f6d5d8eb86388263ce16365ceb10fee23/llvm/lib/Support/Regex.cpp#L86

The regular expression operation called in function `LookupSymbolInModule` returns the `indexes of input strings that match`. 
If it could also return the `exact substring` that matched in the` input string`. Then I could split the string accordingly and `colorize the matched part`.

Currently we passing  `matches` as null in regex execute.
https://github.com/llvm/llvm-project/blob/48aea4a36ad39e2ad03f069def19cceb50217660/lldb/source/Symbol/Symtab.cpp#L785
I tried passing matches, as my understanding was that `matches` would the return the vector of strings that matched in the input string. 

> Ex: input string = "foo is not a bar" and regex = "foo | bar"
> matches would return the vector {"foo", "bar"}.

But it is not doing so. It only returns `foo`. Maybe I'm using the API incorrecty or is there any other api which provides this?

**Comment by DavidSpickett** [comment]
Is this a "match" vs. "search" issue? If you have a look at python's re.match and re.search you'll see what I mean. Match goes from the start of the string only in the python versions maybe we copied the names of those functions.

If not I'll give it a look myself tomorrow.

**Comment by varunkumare99** [comment]
The implementation is similar to pythons re.search, where it searches the entire string for the `first match` and not `all the matches`.
```
Ex: input string = "This string foo is not a bar" and regex = "foo | bar"
returns only "foo"
```

unlike ripgrep
![Screenshot from 2022-10-13 22-20-21](https://user-images.githubusercontent.com/74096215/195659114-e92a5483-4789-4e8d-a6d4-5da5bae55e04.png)

**Comment by varunkumare99** [comment]
thanks!
Can I first submit the patch for review and then add the test case later?
I'm expecting there will be lot of changes during review.

**Comment by DavidSpickett** [comment]
Excited to see this progressing! Putting up the code first is fine, we can talk about testing on the review.

Please add me as a reviewer, I am https://reviews.llvm.org/p/DavidSpickett/ on Phabricator.

**Comment by varunkumare99** [comment]
Thanks.
I have added you as a reviewer.

**Comment by DavidSpickett** [comment]
For reference the patch was https://reviews.llvm.org/D136462 but remains in review.

**Comment by taalhaataahir0102** [comment]
> I would like to look work on this issue. I'm new to LLVM (gone through kaleidoscope tutorials and building JIT). Any advice on how to begin?
> 
> thanks!

Hi Varun! Are you still working on it? I'm planning to work on same project and maybe we can collaborate?
