### ISSUE TITLE
clang is missing after ninja build successfully

### ISSUE THREAD

**Issue by quantrpeter** [llvm/llvm-project#57399]
hi
   clang is missing after ninja build successfully, please help

1. git clone https://github.com/llvm/llvm-project.git
2. cd llvm-build
3. cmake ../llvm-project/llvm -G Ninja -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_INSTALL_PREFIX="../llvm-install"
4. ninja -j8
5. ninja install

After build, i only got these files:

```
/Users/peter/workspace/llvm-install/bin>ls
bugpoint		llvm-cat		llvm-diff		llvm-install-name-tool	llvm-ml			llvm-profgen		llvm-split		llvm-xray
dsymutil		llvm-cfi-verify		llvm-dis		llvm-jitlink		llvm-modextract		llvm-ranlib		llvm-stress		opt
llc			llvm-config		llvm-dlltool		llvm-lib		llvm-mt			llvm-rc			llvm-strings		sancov
lli			llvm-cov		llvm-dwarfdump		llvm-libtool-darwin	llvm-nm			llvm-readelf		llvm-strip		sanstats
llvm-addr2line		llvm-cvtres		llvm-dwarfutil		llvm-link		llvm-objcopy		llvm-readobj		llvm-symbolizer		verify-uselistorder
llvm-ar			llvm-cxxdump		llvm-dwp		llvm-lipo		llvm-objdump		llvm-reduce		llvm-tapi-diff
llvm-as			llvm-cxxfilt		llvm-exegesis		llvm-lto		llvm-opt-report		llvm-remark-size-diff	llvm-tblgen
llvm-bcanalyzer		llvm-cxxmap		llvm-extract		llvm-lto2		llvm-otool		llvm-rtdyld		llvm-tli-checker
llvm-bitcode-strip	llvm-debuginfod		llvm-gsymutil		llvm-mc			llvm-pdbutil		llvm-sim		llvm-undname
llvm-c-test		llvm-debuginfod-find	llvm-ifs		llvm-mca		llvm-profdata		llvm-size		llvm-windres
```

thanks
Peter

**Comment by BertalanD** [comment]
Hi,

The default build does not include Clang. only the LLVM library and some utility programs. You can pass ` -DLLVM_ENABLE_PROJECTS="clang"` to CMake to include Clang in the build targets.

More information about the various build options can be found [here](https://llvm.org/docs/CMake.html#id11).

**Comment by BertalanD** [comment]
Feel free to reply to this issue if you have more questions, but I'm closing this issue as it's not a defect in LLVM.

**Comment by BertalanD** [comment]
Feel free to reply to this issue if you have more questions, but I'm closing this issue as it's not a defect in LLVM.

**Comment by quantrpeter** [comment]
thx
