### ISSUE TITLE
clang-format removes spaces between throw and cast

### ISSUE THREAD

**Issue by alanzhao1** [llvm/llvm-project#57391]
First reported in Chromium: https://crbug.com/1018187

Repro steps:

```console
$ cat test_throw.cpp
void foo(int x) { throw (long) x; }

$ clang-format test_throw.cpp
```

Expected behavior:
`clang-format` should not remove the space before `throw` and `(long)`

Actual behavior:
```cpp
void foo(int x) { throw(long) x; }
```

It seems that `clang-format` is treating `throw (long)` as a function-style construct instead of a cast.

**Comment by rymiel** [comment]
Differential: https://reviews.llvm.org/D132762
