### ISSUE TITLE
Merge 396f40a79fc to 15 branch

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#57395]
396f40a79fc fixes a problem with building Catalyst apps with using a hypothetical future SDK. That hypothetical future SDK has possibly been in beta for a while and might be released soon, so it's probably good if the fix is in the 15 release.

@zmodem lgty?

**Comment by nico** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/396f40a79fc98184fb40967db788896263b3b2fa

**Comment by nico** [comment]
Huh, why did that fail?

Locally running

```
% git checkout release/15.x  
% git cherry-pick 396f40a79fc
```

works without issues.

**Comment by zmodem** [comment]
> @zmodem lgty?

It's up to @tobiashieta in the end, but if he's still open for fixes, this seems like a good one.

**Comment by tru** [comment]
Hmm it's a pretty large diff and we are out of RCs for it to be tested. How risky is this change and what is the impact if it's not in the 15.0.0? With the new release schedule 15.0.1 would be very quick after final so that's a possibility if we want to give it a bit more time to be tested.

**Comment by tru** [comment]
@nico @zmodem my vote is to move this to 15.0.1 unless it's critical. Any thoughts?

**Comment by zmodem** [comment]
Sounds reasonable to me.

**Comment by tru** [comment]
Alright seems worth it to pull it into 15.0.0. I'll queue it up for merge.
