### ISSUE TITLE
clang-15.0.0_rc3 fails to compile with: FAILED: lib/Tooling/ASTNodeAPI.json and /bin/sh: -c: line 1: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by stefson** [llvm/llvm-project#57403]
hello everyone, 

I just tried to compile clang-15.0.0_rc3 on gentoo-amd64 with musl-libc, and while llvm-15.0.0_rc3 build fine I got this error when compiling clang: 

```console
2138031-[850/1751] cd /var/tmp/portage/sys-devel/clang-15.0.0_rc3/work/x/y/clang-abi_x86_64.amd64/lib/Tooling && /var/tmp/portage/sys-devel/clang-15.0.0_rc3/work/x/y/clang-abi_x86_64.amd64/bin/clang-ast-dump --skip-processing=0 -I /lib/clang/15.0.0/include -I /var/tmp/portage/sys-devel/clang-15.0.0_rc3/work/clang/include -I /tools/clang/include -I /include -I /include -I /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include/g++-v11 -I /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include/g++-v11/x86_64-gentoo-linux-muslGNU\ assembler\ version\ 2.38\ (x86_64-gentoo-linux-musl)\ using\ BFD\ version\ (Gentoo\ 2.38\ p4)\ 2.38 -I /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include/g++-v11/backward -I /usr/include -I /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include --json-output-path /var/tmp/portage/sys-devel/clang-15.0.0_rc3/work/x/y/clang-abi_x86_64.amd64/lib/Tooling/ASTNodeAPI.json
2138919:FAILED: lib/Tooling/ASTNodeAPI.json /var/tmp/portage/sys-devel/clang-15.0.0_rc3/work/x/y/clang-abi_x86_64.amd64/lib/Tooling/ASTNodeAPI.json 
2139060-cd /var/tmp/portage/sys-devel/clang-15.0.0_rc3/work/x/y/clang-abi_x86_64.amd64/lib/Tooling && /var/tmp/portage/sys-devel/clang-15.0.0_rc3/work/x/y/clang-abi_x86_64.amd64/bin/clang-ast-dump --skip-processing=0 -I /lib/clang/15.0.0/include -I /var/tmp/portage/sys-devel/clang-15.0.0_rc3/work/clang/include -I /tools/clang/include -I /include -I /include -I /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include/g++-v11 -I /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include/g++-v11/x86_64-gentoo-linux-muslGNU\ assembler\ version\ 2.38\ (x86_64-gentoo-linux-musl)\ using\ BFD\ version\ (Gentoo\ 2.38\ p4)\ 2.38 -I /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include/g++-v11/backward -I /usr/include -I /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include --json-output-path /var/tmp/portage/sys-devel/clang-15.0.0_rc3/work/x/y/clang-abi_x86_64.amd64/lib/Tooling/ASTNodeAPI.json
2139937-/bin/sh: -c: line 1: syntax error near unexpected token `('
2139997-/bin/sh: -c: line 1: `cd /var/tmp/portage/sys-devel/clang-15.0.0_rc3/work/x/y/clang-abi_x86_64.amd64/lib/Tooling && /var/tmp/portage/sys-devel/clang-15.0.0_rc3/work/x/y/clang-abi_x86_64.amd64/bin/clang-ast-dump --skip-processing=0 -I /lib/clang/15.0.0/include -I /var/tmp/portage/sys-devel/clang-15.0.0_rc3/work/clang/include -I /tools/clang/include -I /include -I /include -I /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include/g++-v11 -I /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include/g++-v11/x86_64-gentoo-linux-muslGNU\ assembler\ version\ 2.38\ (x86_64-gentoo-linux-musl)\ using\ BFD\ version\ (Gentoo\ 2.38\ p4)\ 2.38 -I /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include/g++-v11/backward -I /usr/include -I /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include --json-output-path /var/tmp/portage/sys-devel/clang-15.0.0_rc3/work/x/y/clang-abi_x86_64.amd64/lib/Tooling/ASTNodeAPI.json'
```

the compressed full build.log is attached: [build-clang-15.0.0_rc3.log.gz](https://github.com/llvm/llvm-project/files/9438281/build-clang-15.0.0_rc3.log.gz)

I've never had an issue like that before, I'm frankly kind of dumbstrucked by it :-( and I can't even find that `ASTNodeAPI.json` file in the source code. 

anyone got an idea?

**Comment by stefson** [comment]
is there a minimal cmake version somewhere specified? asking for friend :-)

**Comment by DimitryAndric** [comment]
I think you should take a look at where the weird parts with `GNU\ assembler\ version\ 2.38\ (x86_64-gentoo-linux-musl)\ using\ BFD\ version\ (Gentoo\ 2.38\ p4)\ 2.38` come from in those command lines.

For some reason, it seems to be appending the output of `as --version` to your `-I /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include/g++-v11/x86_64-gentoo-linux-musl` options? You'll have to attempt to try figuring out where these options are inserted in the Makefiles, and why it is pasting the full GNU as version in those paths.

**Comment by stefson** [comment]
this was solved on my end by upgrading cmake to the very latest version available, so my verdict is this is somehow a cmake problem. Cmake.html says the minimal cmake version is 3.13.4, but I can say that 3.22.4 is too old here. Its either 3.23.x or 3.24.x needed.

**Comment by tru** [comment]
Hm. This sounds worrying - we should check if we can build it with cmake 3.13.4. But not sure I have time to look into that.

**Comment by tru** [comment]
We should also figure out if this is an regression in 15.x

**Comment by stefson** [comment]
https://llvm.org/docs/CMake.html says: 

```
Download and install CMake. Version 3.13.4 is the minimum required.
```

gentoo says cmake-3.16 is minimal: https://github.com/gentoo/gentoo/blob/master/sys-devel/clang/clang-14.0.6-r1.ebuild#L38

**Comment by BertalanD** [comment]
Might be worth grepping for `Parsed CXX implicit include dir info` in `<build dir>/CMakeFiles/CMakeOutput.log`, as the buggy include path seems to be coming from `CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES`.

**Comment by stefson** [comment]
I'm sorry, I did jump to conclusions about a bug in cmake too early: it did fail with cmake-3.22.4, then I upgraded cmake to 3.24.1 and was able to compile and hence thought it was solved. 

But I just downgraded to stable cmake-3.22.4 and recompiled clang, and it didn't crash as before.

**Comment by stefson** [comment]
I believe what has happend is the *json file was not yet generated as it was needed by the build system, so I hope this is not some wacky race condition. 

Will reopen if I hit it again.
