### ISSUE TITLE
Suboptimal code emitted for AVX2 gather intrinsics

### ISSUE THREAD

**Issue by fzhinkin** [llvm/llvm-project#57411]
LLVM explicitly zero out a destination register for AVX2 gather intrinsics, but it's not required as a mask register is always filled with 1's and the destination register will be overridden by `vpgather*` instruction anyway.

For example,
```cpp
__m256i gather(const long long* base, __m256i index) {
    return _mm256_i64gather_epi64(base, index, 8);
}
```
will be compiled into
```asm
vpcmpeqd       ymm2, ymm2, ymm2  ;; set up the mask, all ones
vpxor          xmm1, xmm1, xmm1  ;; redundant op, ymm1 will be overridden below
vpgatherqq     ymm1, ymmword ptr [rdi + 8*ymm0], ymm2
vmovdqa        ymm0, ymm1
ret
```
where `vpxor` is redundant.

For comparison, GCC doesn't  zero out a destination register (at least for intrinsics operating on integer values): https://godbolt.org/z/rcbdo4bKT

**Comment by topperc** [comment]
It’s not functionally required but it does remove a false scheduling dependency on the previous instruction that wrote that destination register. The scheduler in the hardware can’t tell that the mask is all ones.

**Comment by fzhinkin** [comment]
I was confused by the fact that a destination was zeroed even when there were no writes to it prior the gather instruction.

There is already an issue suggesting to let the BreakFalseDeps pass zero out a destination register instead of explicitly doing it during lowering (https://github.com/llvm/llvm-project/issues/31603), so I'm closing this issue.

Sorry for bothering.
