### ISSUE TITLE
[clang-format] Incorrect space for "delete[] *x"

### ISSUE THREAD

**Issue by zzyyyl** [llvm/llvm-project#57418]
Versions: 14 and main

#### Input
``` cpp
void f() {
  char *x[1] = {new char[10]};
  delete[] *x;
}
```

#### Output
``` cpp
void f() {
  char *x[1] = {new char[10]};
  delete[] * x;
}
```

#### Expect

same as input

**Comment by jackhong12** [comment]
Revision: https://reviews.llvm.org/D132911

**Comment by zzyyyl** [comment]
@jackhong12 
It's still incorrect when `--style="{PointerAlignment: Left}"` 

`` delete[] *x;``  -> ``delete[]* x;``
`` delete[] *(x);`` -> ``delete[]*(x);``

**Comment by jackhong12** [comment]
@zzyyyl Thanks for reminding me! I'll look into it soon.
