### ISSUE TITLE
pid does not exist

### ISSUE THREAD

**Issue by GOVYANSONG** [llvm/llvm-project#57414]
I launched a lldb debug session. a pid is shown for the launched program. but when i tried to look it up under /proc, ps, htop, this pid seems non-existent. am i doing something silly here?

is it because the debugged program is in paused/stopped state? it begs the question: how would a 2nd lldb attach to the same debugged program if pid does not seem to exist in the system

**Comment by fhahn** [comment]
For question about using LLDB (or other LLVM projects), please use: https://discourse.llvm.org
