### ISSUE TITLE
[IR] Add alignment for @llvm.threadlocal.address

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#57438]
See https://reviews.llvm.org/D129833 for the reason.

Simply, we introduced @llvm.threadlocal.address to replace the direct use of TLS globals. However, we missed the alignment property after this transition. We need complete it.

**Comment by alexander-shaposhnikov** [comment]
I've prepared a patch, planning to send it for review ~soon.

**Comment by ChuanqiXu9** [comment]
> I've prepared a patch, planning to send it for review ~soon.

Oh, thanks! I was too busy to delay this.
