### ISSUE TITLE
Compiler regression in aggregate initializers with anonymous structs in unions

### ISSUE THREAD

**Issue by flying-kestrel** [llvm/llvm-project#57436]
The following code is, to the best of my knowledge, standards-compliant C++, and compiles on clang 3.6 and all versions of g++ past 4.7.1 that I tried, but does not compile on clang 3.7 and later:

```c++
union flags {
    struct {
        unsigned a: 1;
        unsigned char : 0;
    };
};

template<typename T>
struct Test {
    Test(bool a) : f(flags {
       .a = a,
    }) {}

    flags f;
};

int main() {
    Test<int> ti(false);
    return 0;
}
```

Specifically, the error is: (see [godbolt](https://godbolt.org/z/Kzq9aaY5K))
```console
error: field designator (null) does not refer to any field in type 'flags'
<source>:20:15: note: in instantiation of member function 'Test<int>::Test' requested here
    Test<int> ti(false);
```

Note that if the rvalue `a` in the `flags{.a = a}` is replaced with a constant, this [compiles fine](https://godbolt.org/z/d56hvzKd9).

as such, my tentative hypothesis for cause of bug is that clang seems to be having trouble with finding the anonymous struct members inside the union during non-constant aggregate initialization.

**Comment by shafik** [comment]
Confirmed: https://godbolt.org/z/5a3414s3G

**Comment by Fznamznon** [comment]
I think this is fixed by https://github.com/llvm/llvm-project/pull/69712 , online demo - https://godbolt.org/z/YvTWTznc4 .
