### ISSUE TITLE
Incorrect call-site-info for argument locations

### ISSUE THREAD

**Issue by jmorse** [llvm/llvm-project#57444]
Here's some code that deliberately switches between translation units -- if you compile both together with 07bfbce98872398ab58a4931ee88ccd2749a1ada and `clang test.c test2.c -o a.out -g -O2  -gdwarf-4`, then I get what looks like an incorrect call site variable location in the `foo` function. It doesn't present in a debugger due to being a tail call, and I can't immediately get a reproducer that does present in a debugger, but I think this is indicative of something being broken. The code:

`test.c`:

```c
#include <stdio.h>

int bar(int, int);
int baz();
int foo(long a, long b) {
  baz();
  return bar(a, b);
}

int qux() {
  printf("ohai\n");
  return 0;
}
```

`test2.c`:

```c
int foo(long, long);
int qux();
int main() {
  return foo(1, 2);
}

int bar(int a, int b) {
  qux();
  return 0;
}

int baz() {
  return 0;
}
```

Deliberately tries to set up call-site-info for calling into `bar` from `foo`. The disassembly for foo:

```asm
<foo>:
    push   %r14
    push   %rbx             
    push   %rax             
    mov    %rsi,%r14        
    mov    %rdi,%rbx        
    xor    %eax,%eax        
    callq  670 <baz>
    mov    %ebx,%edi        
    mov    %r14d,%esi       
    add    $0x8,%rsp
    pop    %rbx             
    pop    %r14
    jmpq   660 <bar>
```

The call site info:

    DW_TAG_GNU_call_site
      DW_AT_abstract_origin (0x000000bc "bar")
      DW_AT_GNU_tail_call   (true)
      DW_AT_low_pc  (0x0000000000000622)

        DW_TAG_GNU_call_site_parameter
          DW_AT_location      (DW_OP_reg4 RSI)
          DW_AT_GNU_call_site_value   (DW_OP_breg14 R14+0)

       DW_TAG_GNU_call_site_parameter
         DW_AT_location      (DW_OP_reg5 RDI)
         DW_AT_GNU_call_site_value   (DW_OP_breg3 RBX+0)

The call site info has found that the argument values originate from r14 and rbx, however it's missed the fact that they're clobbered in the intervening few instructions, by the final two pops for the tail call. Were this to not be a tail call, we would then risk the contents of an uncontrolled register being presented as the argument value in the callee. I think this problem is probably limited to scenarios where the value goes out of liveness in the same block as the call that uses the value, and the register is immediately repurposed for something else. This is hard to hit from small test cases, but probably does happen in large code bases.

I'm not especially familiar with how the call site information moves around, but I would imagine that some kind of analysis like machine-sink is needed, i.e. examining whether aliases of the variables register are def'd or not. (CC @djtodoro ). I think I speculated this in the past somewhere, but IMHO this is the kind of area that instruction referencing's exact knowledge of value locations could be useful and complimentary -- it would be straightforwards to search for backup locations for the value, including stack spills slots, once LiveDebugValues runs. (LiveDebugValues doesn't analyse "real" stack variables though, i.e. ones that weren't fully promoted).

**Comment by djtodoro** [comment]
We tried to avoid any extra meta/debug instruction by introducing the (per-target) ```TargetInstrInfo::describeLoadedValue``` predicate that should try interpreting the values of arguments. I guess the easiest way of solving this case is to avoid registers that are clobbered by the call (it should be there already - if not, it is a bug).

Some kind of analysis could actually save more concrete call-site-parameter values for sure, but we will need some extra complexity in the code.

**Comment by jmorse** [comment]
Patch following my best guess: https://reviews.llvm.org/D141279
