### ISSUE TITLE
Increased sizeof of std::atomic with enum as type and -ffreestanding

### ISSUE THREAD

**Issue by pavelkumbrasev** [llvm/llvm-project#57440]
We have faced with a problem of increased sizeof of std::atomic with enum as type with -ffreestanding that leads to broken class layout.
This problem reproduce only with -ffreestanding and C++11/14 with C++17 and higher problem also doesn't reproduce. It is also required to use libc++ standard library because with libstdc++ this issue doesn't reproduce.

We faced with this problem with: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
But this also reproduced on godbolt with clang 14.0.0
There are compilation command and reduced reproducer:
`clang++ -ffreestanding -std=c++11 -stdlib=libc++`
```cpp
#include <atomic>
#include <cstdint>

struct test_struct {
    enum class state : std::uint8_t {
        created
    };
    std::atomic<state> my_state;
};

template <std::size_t S>
struct print;

print<sizeof(test_struct::state)> print_enum_size;
print<sizeof(test_struct)> print_size;
static_assert(sizeof(test_struct) == 1, "Incorrect sizeof");
```
The problem that `sizeof(std::atomic<state>) == 2` but the `sizeof(state) == 1`

**Comment by erichkeane** [comment]
There is seemingly a typo in the command line, it should REALLY be `-stdlib=libc++` from my analysis: https://godbolt.org/z/T3T74davc

So it seems that `libc++`'s `std::atomic` of the enum is larger in `-ffreestanding` for some reason.

**Comment by pavelkumbrasev** [comment]
> There is seemingly a typo in the command line, it should REALLY be `-stdlib=libc++` from my analysis: https://godbolt.org/z/T3T74davc
> 
> So it seems that `libc++`'s `std::atomic` of the enum is larger in `-ffreestanding` for some reason.

Yes, thank you. I corrected command line.

**Comment by erichkeane** [comment]
I'll note that the difference in size seems to be permitted by the standard: https://eel.is/c++draft/atomics#types.generic.general-3

BUT I suspect @ldionne /etc might have a good explanation as to why libc++ needed a larger atomic on freestanding.

**Comment by pavelkumbrasev** [comment]
I would also note that `sizeof(std::atomic<std::uint8_t>) == 1` with freestanding. As the enum has underlying type std::uint8_t and not equal 1 seems strange.

**Comment by erichkeane** [comment]
It appears it IS lock free: https://godbolt.org/z/ab9j9ce9r

**Comment by mordante** [comment]
Interesting!
It seems there's still a lock present https://godbolt.org/z/1Kccods14
hosted:
```
*** Dumping AST Record Layout
         0 | struct std::atomic<enum test_struct::state>
         0 |   struct std::__atomic_base<enum test_struct::state, false> (base)
         0 |     struct std::__cxx_atomic_impl<enum test_struct::state> __a_
         0 |       struct std::__cxx_atomic_base_impl<enum test_struct::state> (base)
         0 |         _Atomic(enum test_struct::state) __a_value
           | [sizeof=1, dsize=1, align=1,
           |  nvsize=1, nvalign=1]
```
freestanding:
```

*** Dumping AST Record Layout
         0 | struct std::atomic<enum test_struct::state>
         0 |   struct std::__atomic_base<enum test_struct::state, false> (base)
         0 |     struct std::__cxx_atomic_impl<enum test_struct::state, struct std::__cxx_atomic_lock_impl<enum test_struct::state> > __a_
         0 |       struct std::__cxx_atomic_lock_impl<enum test_struct::state> (base)
         0 |         enum test_struct::state __a_value
         1 |         struct std::__cxx_atomic_base_impl<_Bool> __a_lock
         1 |           _Atomic(_Bool) __a_value
           | [sizeof=2, dsize=2, align=1,
           |  nvsize=2, nvalign=1]
```
Now to figure out why there's an unused lock.

**Comment by ldionne** [comment]
Thanks for the patience, I am finally getting a moment to look into this. This was introduced in https://reviews.llvm.org/D56913, a while ago. I am doing some research to better understand what's the purpose of `_LIBCPP_ATOMIC_ONLY_USE_BUILTINS`.

Shooting from the hip, before having more context, I would be tempted to say that the correct thing to do is:

1. Freestanding atomics should not have a lock in them whenever possible
2. We should re-break the ABI to make that happen, i.e. the ABI before LLVM 14 was the correct one. We have to live with a (I think fairly minor) ABI break no matter what we do, so we might was well pick the one that results in the best implementation.

**Comment by ldionne** [comment]
Thanks a ton @mordante for the analysis, you basically did all the hard work. I put up a patch for comments here: https://reviews.llvm.org/D133377.
