### ISSUE TITLE
[X86] Suboptimal code for storing double to global (trunk regression)

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#57449]
```
double a[64], b[64];

void foo (int k)
{
   a[k] += b[k];
}
```

LLVM trunk:
```
foo:                                    # @foo
        movsxd  rax, edi
        lea     rcx, [rip + b]
        movsd   xmm0, qword ptr [rcx + 8*rax]   # xmm0 = mem[0],zero
        lea     rcx, [rip + a]
        addsd   xmm0, qword ptr [rcx + 8*rax]
        movsd   qword ptr [rcx + 8*rax], xmm0
        ret
b:
        .zero   512

a:
        .zero   512
```

GCC/ICX/LLVM 14
```
foo:                                    # 
        movsxd  rax, edi
        movsd   xmm0, qword ptr [8*rax + a]     # xmm0 = mem[0],zero
        addsd   xmm0, qword ptr [8*rax + b]
        movsd   qword ptr [8*rax + a], xmm0
        ret
b:
        .zero   512

a:
        .zero   512
```
https://godbolt.org/z/15nMMKGof

Possible caused by opaque pointers? cc @nikic

**Comment by topperc** [comment]
Not opaque pointers. It was caused by the change to default to -fpie. https://reviews.llvm.org/D120305

**Comment by topperc** [comment]
See also #56742

**Comment by MaskRay** [comment]
This is not a regression. This is a longstanding -fno-pic vs -fpie code generation difference.

**Comment by davidbolvansky** [comment]
You patch mentions that “this matches gcc” but codegen of clang and gcc is different here…

**Comment by MaskRay** [comment]
> You patch mentions that “this matches gcc” but codegen of clang and gcc is different here…

It's a somewhat unfortunate issue in GCC. While the GCC upstream default stays with no-pic for Linux target triples (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=103398), all Linux distributions (including a lot of GCC build scripts like glibc's `scripts/build-many-glibcs.py`) I know have switched to default PIE...

**Comment by davidbolvansky** [comment]
Ah, ok, thanks for info.

**Comment by MaskRay** [comment]
https://godbolt.org/ doesn't appear to use default PIE, which might be the source of confusion.
Filed https://github.com/compiler-explorer/gcc-cross-builder/issues/33
