### ISSUE TITLE
readability-container-data-pointer should ignore std::array of non zero size

### ISSUE THREAD

**Issue by stayprivate** [llvm/llvm-project#57445]
Hello,

Would be nice if readability-container-data-pointer ignored std::array of non zero size. The danger of using ?[0] do not apply and when porting code from C where C array are transform into std::array it just create lots of noise.

**Comment by EugeneZelenko** [comment]
I think will be good idea to implement this as option.

**Comment by felix642** [comment]
I will work on this issue.
