### ISSUE TITLE
`-print-changed` doesn't support `-filter-passes` in thinlto mode with lld.

### ISSUE THREAD

**Issue by rlavaee** [llvm/llvm-project#57453]
How to reproduce:

Build a simple program with `-fuse-ld=lld -flto=thin -Wl,-mllvm,-print-changed -Wl,-mllvm,-filter-passes="InstSimplifyPass"`. The log will report diff for every pass (if there are changes), not just for `InstSimplifyPass`.

**Comment by jamieschmeiser** [comment]
This is related to the recent extension of this functionality to machine functions passes in https://reviews.llvm.org/D130434.  The implementation is still in its infancy and does not include all of the options supported by the opt functionality.  Pass filtering was left as a TODO comment.

`clang++ -fuse-ld=lld -flto=thin -Wl,-mllvm,-print-changed -Wl,-mllvm,-filter-passes="InstSimplifyPass" hello.C 2>&1 | grep "\*\*\* IR Dump" | sed "/no change/d;/filtered out/d"` shows that the results are for machine function passes.

**Comment by rlavaee** [comment]
Thanks Jamie. Looks like it isn't too hard to implement.

**Comment by MaskRay** [comment]
I left a TODO for the feature.
```
  // For --print-changed, if the function name is a candidate, save the
  // serialized MF to be compared later.
  // TODO Implement --filter-passes.
```

Patch: https://reviews.llvm.org/D133055
