### ISSUE TITLE
MLIR used by Big Data Query such as SQL

### ISSUE THREAD

**Issue by EdisonZiXing** [llvm/llvm-project#57460]
Hello everyone，
We notice that MLIR is always used by the AI compilers but not on the Big Data Query ,like SQL queries.
So I wanna ask if any researchs or applications that MLIR used on the SQL queries or relatived Relational Algebra Operators？
Thanks for everyone who may reply！！

**Comment by EugeneZelenko** [comment]
Please use https://discourse.llvm.org for questions.
