### ISSUE TITLE
DAG Combiner inserts illegal nodes.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5746]
|  |  |
| --- | --- |
| Bugzilla Link | [5374](https://llvm.org/bz5374) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@lattner,@efriedma-quic,@sunfishcode |

## Extended Description 
TargetLowering::SimplifyDemandedBits() inserts nodes without checking whether they are legal on the target or not.

I ran into this issue with a target which custom lowers srl.

E.g. on ppc32 the following LLVM IR:

define i32 @&#8203;foo(i32 %A, i32 %B) {
bb0:
	%r1 = xor i32 %B, -1
	%r2 = and i32 %r1, %A
	%r3 = sub i32 %A, %B
	%r4 = or i32 %A, %r1
	%r5 = and i32 %r3, %r4
	%r6 = or i32 %r5, %r2
	%r7 = ashr i32 %r6, 31
	%r8 = and i32 %r7, 1
	%r9 = xor i32 %r7, -1
	%r10 = and i32 %r9, 0
	%r11 = or i32 %r10, %r8
	%r12 = and i32 %r11, 1	
	ret i32 %r12
}

triggers the following optimization:

...
Replacing.2 0x2c44030: i32 = sra 0x2c43e40, 0x2c43f38
With: 0x2c44318: i32 = srl 0x2c43e40, 0x2c43f38
...

On ppc32 this transformation is valid, however on targets where slr is custom lowered it is not.

The optimization is done at line 1227 of TargetLowering.cpp.

It seems that SimplifyDemandedBits() never checks whether it is allowed to insert a certain node, so there are possibly many other ways to trigger this bug.

**Comment by gwelymernans** [comment]
We no longer have a CellSPU backend, right? Can we close this?

**Comment by RKSimon** [comment]
SimplifyDemandedBits/SimplifyDemandedVectorElts still doesn't always ensure that a new node is legal if the fold occurs after legalization but we haven't had any cases like this for some time (probably just lucky...).

**Comment by gwelymernans** [comment]
It'll probably be best to open a new bug when / if it happens.
