### ISSUE TITLE
Missing symlink libclang-16.so.1

### ISSUE THREAD

**Issue by joshcangit** [llvm/llvm-project#57473]
Sometimes, Clang can have missing symlinks.
I'm using the development branch `.deb` packages.
I don't remember version 15 having any but version 16 has one.

I fixed it by adding it in.
```
(cd /usr/lib/x86_64-linux-gnu/ && sudo ln -s libclang-16.so.16.0.0 libclang-16.so.1)
```

Now then, which package should this symlink be in?
Is it `libclang1-16` or `libclang-16-dev`?

**Comment by sylvestre** [comment]
i fixed it for 16 a week ago

**Comment by joshcangit** [comment]
:thinking:
It's seems like quite the issue but it's kind of minor actually.
Somehow, that symlink is missing again.
No problem. I just added it back again.
