### ISSUE TITLE
Confusing diagnostics: error: 'extern' variable cannot have an initializer

### ISSUE THREAD

**Issue by pmor13** [llvm/llvm-project#57478]
This C code:
```c
static int x;

void f(void)
{
    extern int x = 1;
}
```
leads to:
```console
error: 'extern' variable cannot have an initializer
```
which is confusing, because `extern` variable CAN have an initializer, which is demonstrated by the C standard (C11, 6.9.2 External object definitions, 4, EXAMPLE 1):
```c
extern int i3 = 3; // definition, external linkage
```
The expected diagnostics is:
```console
error: declaration of block scope identifier x with internal linkage shall have no initializer
```
Relevant quote from C11:
> If the declaration of an identifier has block scope, and the identifier has external or internal linkage, the declaration shall have no initializer for the identifier.

**Comment by AaronBallman** [comment]
C2x 6.7.10p6 and C++2b [dcl.init.general]p5 both agree on the behavior, so I agree that the diagnostic can be reworded in this case. There's only one use of `err_block_extern_cant_init` and it is for this specific situation being diagnosed.

**Comment by pmor13** [comment]
@jakevossen5 @junaire Any interest in fixing this issue?

**Comment by junaire** [comment]
Here's a potential fix: https://reviews.llvm.org/D133088
Sorry @pmor13 I should also add you as a reviewer, but I don't know your phab name.

**Comment by pmor13** [comment]
@junaire What is phab?

Note that this code:
```
int x;
void f(void)
{
    extern int x = 1;
}
```
needs to produce:
```

```
