### ISSUE TITLE
[MLIR] ConversionPatternRewriter::create<tensor::FromElementsOp> generates arith.constant operation

### ISSUE THREAD

**Issue by tjuwhy** [llvm/llvm-project#57470]
Based on the llvmorg-14.0.6 branch, I modified the toy example in order to create a new `tensor.from_element` operation through the following code:

```cpp
LogicalResult
  matchAndRewrite(Operation *op, ArrayRef<Value> operands,
                  ConversionPatternRewriter &rewriter) const final {
    auto loc = op->getLoc();
    mlir::Type elementType = FloatType::getF64(getContext());
    int dim0 = 2;
    int dim1 = 3; 
    SmallVector<Value, 8> extentValues; 

    // Note: get a ranked tensor type, with dim vector and elementType
    auto dataTypeA = mlir::RankedTensorType::get({dim0, dim1}, elementType); 

    // Note: arith::ConstantOp
    auto f64Zero = rewriter.create<arith::ConstantOp>( loc, rewriter.getFloatAttr(elementType, 0));
    for ( int i = 0; i < dim0 * dim1; ++i) { 
      /* code */
      extentValues.push_back(rewriter.create<arith::ConstantOp>(
            loc, rewriter.getFloatAttr(elementType, i))); 
    } 
    
    Value tensorA = rewriter.create<tensor::FromElementsOp>(loc, dataTypeA, extentValues); // point 1

    // ...

   return success();
}
```

However, the point 1 generates `%cst_12 = arith.constant dense<[[0.000000e+00, 1.000000e+00, 2.000000e+00], [3.000000e+00, 4.000000e+00, 5.000000e+00]]> : tensor<2x3xf64>
` instead. 

And I found it cannot be lowered by `mlir-opt --convert-arith-to-llvm`. Please let me know if I used the `create<T>` API in the wrong way?

**Comment by tjuwhy** [comment]
@llvm/issue-subscribers-mlir-llvm

**Comment by tjuwhy** [comment]
@llvmbot I wonder if you missed this post,  I'll appreciate it if you could ask someone to help.

**Comment by jpienaar** [comment]
Sounds like this was folded post creation. If you run with --debug it should show the creation of FromElements and then the folding into constant.

**Comment by tjuwhy** [comment]
@jpienaar Thanks for your reply, now I still wonder why the 'arith.constant' operation is not lowered.

Moreover, in my latest trial, I found many other operations in arith dialect are not lowered down to llvm dialect. Part of the source mlir are shown below:

``` 
%46 = arith.mulf %28, %cst_4 : f32
%47 = arith.maxf %19, %cst_5 : f32
%48 = memref.atomic_rmw assign %32, %26[%c0] : (f32, memref<2xf32>) -> f32
```

after 'mlir-opt --convert-arith-to-llvm arith.mlir', I got the following IR:
```
%76 = llvm.fmul %58, %24  : f32
%77 = arith.maxf %49, %26 : f32
%78 = memref.atomic_rmw assign %62, %56[%22] : (f32, memref<2xf32>) -> f32
```
where the `arith.mulf` is lowered down to `llvm.fmul` but `arith.maxf` is not lowered.

The whole arith.mlir and arith.llvm.mlir file can be found [here](https://drive.google.com/drive/folders/1fUZ_C82pKsYGRHuZyO6JkWI_2hLsQcoO?usp=sharing). My `mlir` is compiled from source, base on the llvmorg-14.0.6 branch. Please tell me if you need more information.

**Comment by tjuwhy** [comment]
I see, I should add the `--arith-expand` option to make those operations convertible.
