### ISSUE TITLE
__builtin_calloc has incorrect semantics on wraparound

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#57477]
When passing values to `calloc` such that the result of `nmemb * size` cannot be represented, the result of the call is null. However, our builtin does not exhibit this behavior, which is especially problematic given that we automatically replace calls to `calloc()` with a call to `__builtin_calloc()`, so even if the platform c standard library implements the correct behavior, the user isn't protected (unless they pass `-fno-builtin`).

Consider:
```
typedef char (*arrayptr)[0x700000000000000];

int main(void) {  
  arrayptr p, q;

  p = __builtin_calloc(32, sizeof *p);
  if (!p) return 0;
  q = p + 32;
  return q - p;
}
```
this returns `-4` instead of `0`: https://gcc.godbolt.org/z/GoeGPrv3x

Note that WG14 adopted https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2810.pdf into C2x to clarify the intent of the standard. While this was adopted into C2x, I do not think the behavior here should be tied to a specific standard version unless there is a very compelling reason to do so.

**Comment by efriedma-quic** [comment]
Duplicate of #36652 ?

**Comment by AaronBallman** [comment]
> Duplicate of #36652 ?

Good catch! I even commented on that issue about this paper, sheesh! :-)

Closing as a duplicate.
