### ISSUE TITLE
Why are my function declarations not aligning in header file?

### ISSUE THREAD

**Issue by dimitris93** [llvm/llvm-project#57488]
I am trying to align my code as follows, using `clang-format`:

[![enter image description here][1]][1]

But, instead I get the following:

[![enter image description here][2]][2]

Why is this happening? I am using `AlignConsecutiveDeclarations: Consecutive`. Here is my full settings:

	# Generated from CLion C/C++ Code Style settings
	BasedOnStyle: LLVM
	AccessModifierOffset: -4
	AlignAfterOpenBracket: Align
	AlignConsecutiveAssignments: Consecutive
	AlignConsecutiveDeclarations: Consecutive
	AlignOperands: AlignAfterOperator
	BreakBeforeBinaryOperators: NonAssignment
	AllowAllArgumentsOnNextLine: false
	PackConstructorInitializers: Never
	AllowAllParametersOfDeclarationOnNextLine: false
	AllowShortBlocksOnASingleLine: Always
	AllowShortCaseLabelsOnASingleLine: true
	AllowShortFunctionsOnASingleLine: None
	AllowShortIfStatementsOnASingleLine: Never
	AllowShortLambdasOnASingleLine: All
	AllowShortLoopsOnASingleLine: false
	AlwaysBreakAfterReturnType: All
	AlwaysBreakTemplateDeclarations: MultiLine
	BreakBeforeBraces: Custom
	BraceWrapping:
	  AfterCaseLabel: false
	  AfterClass: true
	  AfterControlStatement: Always
	  AfterEnum: true
	  AfterFunction: true
	  AfterNamespace: true
	  AfterStruct: true
	  AfterUnion: true
	  BeforeCatch: true
	  BeforeElse: true
	  IndentBraces: false
	  SplitEmptyFunction: false
	  SplitEmptyRecord: false
	BreakBeforeTernaryOperators: false
	BreakConstructorInitializers: AfterColon
	BreakInheritanceList: AfterColon
	ColumnLimit: 0
	CompactNamespaces: false
	#
	ContinuationIndentWidth: 8
	IndentCaseLabels: false
	IndentPPDirectives: AfterHash
	IndentWidth: 4
	KeepEmptyLinesAtTheStartOfBlocks: true
	#
	MaxEmptyLinesToKeep: 1
	NamespaceIndentation: All
	ObjCSpaceAfterProperty: false
	ObjCSpaceBeforeProtocolList: false
	PointerAlignment: Left
	ReflowComments: false
	SpaceAfterCStyleCast: false
	SpaceAfterLogicalNot: false
	SpaceAfterTemplateKeyword: false
	SpaceBeforeAssignmentOperators: true
	# ?
	SpaceBeforeCpp11BracedList: false
	SpaceBeforeCtorInitializerColon: true
	SpaceBeforeInheritanceColon: true
	SpaceBeforeParens: ControlStatements
	SpaceBeforeRangeBasedForLoopColon: true
	SpaceInEmptyParentheses: false
	SpaceInEmptyBlock: true
	SpacesBeforeTrailingComments: 3
	SpacesInAngles: false
	SpacesInCStyleCastParentheses: false
	SpacesInContainerLiterals: false
	SpacesInParentheses: false
	SpacesInSquareBrackets: false
	TabWidth: 4
	UseTab: ForContinuationAndIndentation

  [1]: https://i.stack.imgur.com/TcXX3.png
  [2]: https://i.stack.imgur.com/8mG6b.png

**Comment by dimitris93** [comment]
The main issue was `AlwaysBreakAfterReturnType: All`

**Comment by dwblaikie** [comment]
I'm confused - you've specified `AlwaysBreakAfterReturnType: All` - but the first image (showing what you want) shows not breaking (breaking means line break - ie: put the return type on one line, and the function name on the next line). Sounds like `AlwaysBreakAfterReturnType` is the opposite of what you want?
