### ISSUE TITLE
llvm does not actually support armv2 or armv3

### ISSUE THREAD

**Issue by easyaspi314** [llvm/llvm-project#57486]
llvm accepts the options for `-march=armv2` and `-march=armv3` without properly supporting the architecture. 

Notably, it will use `umull`, `smull`, `ldr(s)h`, and `strh` which do not exist.

```llvm
define i32 @ldrh(i16 *%ptr) {
  %val = load i16, i16 *%ptr, align 2
  %zex = zext i16 %val to i32
  ret i32 %zex
}

define void @strh(i16 *%ptr, i16 %val) {
  store i16 %val, i16 * %ptr, align 2
  ret void
}

define i64 @umull(i32 %x, i32 %y) {
  %x64 = zext i32 %x to i64
  %y64 = zext i32 %y to i64
  %prod = mul nuw i64 %x64, %y64
  ret i64 %prod
}
```
`clang --target=armv2-none-eabi -march=armv2 -O2 -S`
```asm
ldrh:
    ldrh r0, [r0] // invalid
    mov pc, lr

strh:
    strh r1, [r0] // invalid
    mov pc, lr

umull:
    umull r2, r3, r1, r0 // invalid
    mov r0, r2
    mov r1, r3
    mov pc, lr
```
This should be something like this, which is the same code llvm emits for unaligned pointers or when in thumb-1:
```asm
ldrh:
    ldrb r1, [r0]
    ldrb r0, [r0, #1]
    orr r0, r1, r0, lsl #8
    mov pc, lr

strh:
    strb r1, [r0]
    lsr r1, r1, #8
    strb r1, [r0, #1]
    mov pc, lr

umull:
    // manual __aeabi_lmul call 
    mov r2, r1
    mov r1, #0
    mov r3, #0
    b __aeabi_lmul // tail call
```

Either these targets should be removed or these should be fixed.

**Comment by DavidSpickett** [comment]
At least looking at the source the only mentions of v2 and 3 are:
* the architecture versions themselves
* build attributes for them
* target parser support and tests for that
* backend features that we don't reference anywhere
* tests for enabling the arch via asm directives

All of which could be removed.

I can't find a citation for this but my memory is someone telling me that Arm support is really only v4 and above. I will check with the Arm folks to see if there's any reason to keep any of this in.

@nickdesaulniers Do any of the kernel builds go this far back? If they do and they work then it's probably luck given what easyaspi31 has found.

**Comment by DavidSpickett** [comment]
And @easyaspi314, what is your preferred option? It's unlikely that a large amount of people would want it fixed but if you have a use case we could figure something out.

**Comment by DavidSpickett** [comment]
Arm has no objection to removing these options.

From what I'm told supporting Armv2 would be quite the task given an unusual memory config (https://en.wikichip.org/wiki/arm/26-bit_architectures). So supporting that is not just a case of a few missing instructions and would be a whole project in itself.

**Comment by easyaspi314** [comment]
Best play is just flat-out reject -march=armv2 and -marmv3. GCC did this a few years ago. 

There is a good reason why even ARM doesn't mention things before v4T.

**Comment by DavidSpickett** [comment]
https://reviews.llvm.org/D133109

**Comment by easyaspi314** [comment]
Huh, in looking at this I noticed a related v4 bug

**Comment by DavidSpickett** [comment]
RFC'd this just on the off chance https://discourse.llvm.org/t/rfc-removal-of-armv2-2a-3-3m-target-options/65040.

I doubt it will be blocked though. Thanks for reporting this!
