### ISSUE TITLE
release/15.x branch removed clang::Preprocessor::getPredefines()

### ISSUE THREAD

**Issue by bradking** [llvm/llvm-project#57483]
Commit 6bbf51f3ed59ae37f0fec729f25af002111c9e74 removed the `getPredefines()` method.  It has been part of the public API for a long time, and is useful for tooling built against LLVM/Clang to inspect or update the builtin predefines.  In particular, CastXML uses it [here](https://github.com/CastXML/CastXML/blob/v0.4.5/src/RunClang.cxx#L202) for that purpose.

The method's removal seems unnecessary for the commit's stated purpose.  Can it be restored in 15.x, please?

**Comment by bradking** [comment]
For reference, the `getPredefines()` method was added by commit a580a92508ddaafef3746cb28c664e92a26e4fe3 with the purpose of providing an accessor.

**Comment by royjacobson** [comment]
It's used in some other projects as well -

https://github.com/nasa/trick/blob/bcaaeedd894cfef66e3958e9ec47ad82a4c8c654/trick_source/codegen/Interface_Code_Gen/HeaderSearchDirs.cpp#L388
https://github.com/esbmc/esbmc/blob/964d54b072ac22269d1927a94734440758558182/src/clang-c-frontend/AST/esbmc_action.h#L27
https://github.com/microsoft/DirectXShaderCompiler/blob/c9e04c06b0483e90f968ebb6b204ea262fce48ef/tools/clang/tools/libclang/dxcrewriteunused.cpp#L598

There's still time to get this into Clang 15 so let's do that - we won't be able to add this after the release and it seems safe enough. I've opened https://reviews.llvm.org/D133044.

**Comment by bradking** [comment]
Thanks!  I tested D133044 locally, and it fixes CastXML's build.  I've approved it in Phabricator.

**Comment by bradking** [comment]
Thanks folks!
