### ISSUE TITLE
Error: unsupported option '-fsanitize=safe-stack' in macOS

### ISSUE THREAD

**Issue by shaopeng-gh** [llvm/llvm-project#57513]
Hello!
per the document:
https://releases.llvm.org/12.0.0/tools/clang/docs/SafeStack.html
[Supported Platforms](https://releases.llvm.org/12.0.0/tools/clang/docs/SafeStack.html#supported-platforms)
SafeStack was tested on Linux, NetBSD, FreeBSD and macOS.

We are able to generate in Linux but in mac machine with a Intel CPU, the same command will generate error:
```console
clang: error: unsupported option '-fsanitize=safe-stack' for target 'x86_64-apple-darwin19.6.0'
```
We also tried on another mac machine witch is Apple M1 CPU, the error is:
```console
clang: error: unsupported option '-fsanitize=safe-stack' for target 'aarch64-apple-darwin20.6.0'
```

The command we have is a simple compile of one hello world c file:
```shell
clang -Wall helloc.c -O2 -g -gdwarf-5 -o clang.macho.c.safe_stack -fsanitize=safe-stack
```

I dig around the documentation have no luck finding how to resolve this error. 

more info about the machine:

```console
$ sw_vers 
ProductName:      Mac OS X
ProductVersion:   10.15.7
BuildVersion:     19H1922
 
$ clang --version
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

```

**Comment by fhahn** [comment]
It looks like you are using Apple clang 12.0 which is different to the upstream LLVM/Clang 12.0 release. 

You might want to try a newer version of Apple clang or a newer upstream LLVM/Clang release.

**Comment by shaopeng-gh** [comment]
@fhahn thanks for looking!
I used homebrew to install default latest LLVM and not using the apple one, I see it is v14. 
https://formulae.brew.sh/formula/llvm
Same error, please see below:

![image](https://user-images.githubusercontent.com/81775155/188543324-14f08011-8200-44a6-8bde-7f0748128dc2.png)

**Comment by shaopeng-gh** [comment]
btw I noticed the language is the same for "SafeStack was tested on Linux, NetBSD, FreeBSD and macOS."
starting from 4.0.0 to latest, was it tested in 4.0.0 long time ago

https://releases.llvm.org/4.0.0/tools/clang/docs/SafeStack.html
https://releases.llvm.org/5.0.0/tools/clang/docs/SafeStack.html
...
https://releases.llvm.org/14.0.0/tools/clang/docs/SafeStack.html

**Comment by EugeneZelenko** [comment]
Could you please try 15 or `main` branch?

**Comment by shaopeng-gh** [comment]
Thanks for the reply!

No 15 is not available:
https://formulae.brew.sh/formula/llvm
latest is 14.
if you have a macOS script to install 15 I will try it.

And I don't think we want to use source code,
what we are doing is a build pipline, which is a macOS vm, and we just need to quickly install the clang, and then use the clang to build our source code, with `-fsanitize=safe-stack`.

**Comment by shaopeng-gh** [comment]
The same source code we have 3 build pipeline:
Windows build pipeline
Linux build pipeline
macOS build pipeline

only macOS build pipeline have this error  `unsupported option '-fsanitize=safe-stack'` so we are looking how to resolve.

**Comment by shaopeng-gh** [comment]
I have created a pubic repo to repro with builds of just one simple hello world C file:
https://github.com/shaopeng-gh/BinBuild/actions

Linux success.
Windows failed. (should be by design)
Mac failed.

Build workflows is in https://github.com/shaopeng-gh/BinBuild/tree/main/.github/workflows

My main question is just if there is indeed issue for macOS or I missed something to make it work, 
(fix is of no priority for me if there is issue)

Thanks a lot!

**Comment by shaopeng-gh** [comment]
a gentle ping, thanks.

**Comment by alvinhochun** [comment]
By greping the source, I can see that SafeStack support for Darwin was disabled in these changes:

- https://reviews.llvm.org/D50718
- https://reviews.llvm.org/D50724

CC @vlad902

**Comment by shaopeng-gh** [comment]
@alvinhochun Thanks for looking! Likely the doc just need an update. I have no further questions from my side.

```
[Supported Platforms](https://releases.llvm.org/14.0.0/tools/clang/docs/SafeStack.html#supported-platforms)
SafeStack was tested on Linux, NetBSD, FreeBSD and macOS.
```
