### ISSUE TITLE
Taskgroup task_reduction with target in_reduction segfaults

### ISSUE THREAD

**Issue by tomdeakin** [llvm/llvm-project#57522]
The following code segfaults at the end of the taskgroup when waiting for all tasks. If I remove nowait on the target tasks, the segfault goes away, which suggests the synchronisation at the end of the taskgroup construct is failing.

Tested with LLVM at commit 9ad0ace2, built for `-fopenmp-targets=nvtpx64` on a node with four A100 GPUs.
```cpp
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <math.h>

#include <omp.h>

int main(void) {

  int N = 1000000;
  double *A, *B;
  A = malloc(N*sizeof(double));
  B = malloc(N*sizeof(double));

  double sum = 0.0;

  for (int i = 0; i < N; ++i) {
    A[i] = 1.5;
    B[i] = 2.0;
  }
  
  int num_devices = omp_get_num_devices();
  printf("Num devices: %d\n", num_devices);
  assert (N % num_devices == 0);
  int len = N / num_devices;

  #pragma omp taskgroup task_reduction(+:sum)
  {
    for (int dev = 0; dev < num_devices; ++dev) {
      int start = dev * len;
      int end = start + len;
 
      #pragma omp target map(to: A[start:len], B[start:len]) device(dev) in_reduction(+:sum) nowait
      {
        #pragma omp loop
        for (int i = start; i < end; ++i) {
                sum += A[i] * B[i];
        }
      }
    }
  }

  assert(fabs(sum - (3.0*N)) < 1.0E-10);

  printf("Success\n");

}
```

Some preliminary discussion occurred on [Discourse](https://discourse.llvm.org/t/taskgroup-task-reduction-with-target-in-reduction-segfaults/64683)

**Comment by shiltian** [comment]
That looks like a bug in `libomp` when using `in_reduction` on `target nowait` directive because internally it is lowered to something like:
```
#pragma omp hht task in_reduction(...)
#pragma omp target
```

**Comment by rodrigo-ceccato** [comment]
I would like to work on this

**Comment by shiltian** [comment]
> I would like to work on this

K, assigned to you.

**Comment by rodrigo-ceccato** [comment]
A minimal example that segfaults at the same point:
```c
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <math.h>

#include <omp.h>

int main(void)
{

    double sum = 0;
    double A = 311;

    assert(omp_get_num_devices() > 1 && "This example needs at least 2 devices");

#pragma omp taskgroup task_reduction(+ : sum)
    {
#pragma omp target map(to : A) in_reduction(+ : sum) device(0) nowait
        {
            sum += A;
        }

#pragma omp target map(to : A) in_reduction(+ : sum) device(1) nowait
        {
            sum += A;
        }
    }
    printf("[host] sum = %f\n", sum);
    assert(fabs(sum - (311 + 311)) < 1.0E-10 && "Error in sum value");
}
```

**Comment by rodrigo-ceccato** [comment]
Regarding the lowering of the clause, [D125669](https://reviews.llvm.org/D125669) added support for `target in_reduction`, so I think this example was supposed to work.

I have tested a bit and found that it executes correctly if we disable the hidden helper task (`LIBOMP_USE_HIDDEN_HELPER_TASK=0`), or do not use the `nowait` clause:

| Hidden Helper Threads→ | Enabled  | Disabled |
|-----------------------|----------|----------|
| target nowait         | Segfault | Works    |
| target                | Works    | Works    |

The segfault happens in the function `__kmpc_task_reduction_get_th_data`, so it appears that the hidden helper thread does not find the corresponding pointer for the reduction data, but I am not sure yet.

**Comment by shiltian** [comment]
> Regarding the lowering of the clause, [D125669](https://reviews.llvm.org/D125669) added support for `target in_reduction`, so I think this example was supposed to work.
> 
> I have tested a bit and found that it executes correctly if we disable the hidden helper task (`LIBOMP_USE_HIDDEN_HELPER_TASK=0`), or do not use the `nowait` clause:
> 
> Hidden Helper Threads→	Enabled	Disabled
> target nowait	Segfault	Works
> target	Works	Works
> The segfault happens in the function `__kmpc_task_reduction_get_th_data`, so it appears that the hidden helper thread does not find the corresponding pointer for the reduction data, but I am not sure yet.

For `nowait` target region, hidden helper thread is just an uber thread. It is not supposed to be involved in the deduction part. All reduction needs to be done on the device, and on the host it is just a simple hidden helper task without any extra code for reduction. The problem now is, the front end still generates code for reduction. That is problematic.
