### ISSUE TITLE
clang-format regression for whitespace between `}&&` in clang-format 15.0.0-rc3

### ISSUE THREAD

**Issue by vogelsgesang** [llvm/llvm-project#57534]
I just tried to upgrade our (Salesforce, Hyper team) internal toolchain to 15.0.0-rc3 and came across the following regression in clang-format when compared to clang-format 14.0.3:

```diff
-   if (input.size() < 4 || (input[0] == byte{'P'} && input[1] == byte{'A'} && input[2] == byte{'R'} && input[3] == byte{'1'})) {
+   if (input.size() < 4 || (input[0] == byte{'P'}&& input[1] == byte{'A'}&& input[2] == byte{'R'}&& input[3] == byte{'1'})) {
```

clang-format 15.0.0-rc3 incorrectly removes the whitespace between the `}` and the `&&`

**Comment by jackhong12** [comment]
I think this problem has been fixed by https://github.com/llvm/llvm-project/commit/ef71383b0cfbacdbebf495015f6ead5294bf7759.

**Comment by royjacobson** [comment]
Is it possible to cherry pick this into the 15 branch then? @jackhong12

**Comment by vogelsgesang** [comment]
@tru what would be the process to request a backport for this?
@jackhong12 do you foresee any potential issues if ef71383b0cfbacdbebf495015f6ead5294bf7759 was applied to the LLVM 15 release branch?

**Comment by jackhong12** [comment]
@vogelsgesang In https://github.com/llvm/llvm-project/commit/ef71383b0cfbacdbebf495015f6ead5294bf7759, I only reverted some checking rules to the old version and didn't add new features. So, I don't think it will cause other issues.
