### ISSUE TITLE
HLSL Element-wise math operations for vectors

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#57535]
Just going to drop some terrible C++ templates here because this is what I'm thinking...

```c++
#include <math.h>

template<typename element_type, int element_count>
using vector = __attribute__((ext_vector_type(element_count))) element_type;

template<typename element_type, int element_count, element_type(*Fn)(element_type)>
vector<element_type, element_count> element_wise( vector<element_type, element_count> V) {
  vector<element_type, element_count> Out;
  for (int I = 0; I < element_count; ++I)
    Out[I] = Fn(V[I]);
  return Out;
}

vector<float,4> sqrtvf4(vector<float,4> V) {
  return element_wise<float,4, sqrtf>(V);
}

```

**Comment by llvm-beanz** [comment]
I think if we define the element_wise template above in the HLSL external sema source, we can define something like:

```c++
const auto sqrtvf4 = element_wise<float,4, sqrtf>;
```

also in the HLSL Sema source, which will allow us to write a header implementation:

```
namespace hlsl {
  float4 sqrt(float4 v) { return sqrtvf4(v); }
}
```

**Comment by RKSimon** [comment]
Clang already has a number of `__builtin_elementwise_*` intrinsics for int/float vector types - would reusing that work?

https://clang.llvm.org/docs/LanguageExtensions.html#vectors-and-extended-vectors

**Comment by llvm-beanz** [comment]
My question there would be is it better to add a whole lot more of those (we have a lot of functions we support element wise operations), or is it better to add a template expander?

**Comment by RKSimon** [comment]
CC'ing @fhahn who added the original functionality

IMO adding elementwise builtins for all the lang-ref math/bitwise intrinsics shouldn't be a problem: https://llvm.org/docs/LangRef.html#standard-c-c-library-intrinsics

**Comment by llvm-beanz** [comment]
HLSL vectors are just a template alias of Clang ExtVector. We also hope to use the Clang matrix type when we get there too.

**Comment by llvm-beanz** [comment]
I think we have a strategy for this broadly, so I'm going to close this and we'll track separate issues for individual tasks as appropriate.
