### ISSUE TITLE
[clang-format] wrong formatting between requires clause and `bool`

### ISSUE THREAD

**Issue by zzyyyl** [llvm/llvm-project#57538]
#### input

```cpp
template <typename A>
  requires std::is_base_of_v<B, A>
bool f() {
  return false;
}
```

#### output

```cpp
template <typename A>
  requires std::is_base_of_v<B, A> bool
f() {
  return false;
}
```

#### expect

same as input

#### others

The formatting is correct if `bool` is replaced by `int`, `void` or anything else.

**Comment by rymiel** [comment]
Culprit is likely this special case here:

https://github.com/llvm/llvm-project/blob/1169586dcde0376ef291802208daedc4f8107c7e/clang/lib/Format/UnwrappedLineParser.cpp#L3521-L3530

Maybe it should keep track of whether or not it has already created a requirement? (`std::is_base_of_v<B, A>` in this case)
Or maybe even just simply look ahead for the paren before consuming anything

**Comment by rymiel** [comment]
Differential: https://reviews.llvm.org/D134325

**Comment by HazardyKnusperkeks** [comment]
> Maybe it should keep track of whether or not it has already created a requirement? (`std::is_base_of_v<B, A>` in this case) Or maybe even just simply look ahead for the paren before consuming anything

That is a big problem, because we don't know if that's a template or some less and greater operations.
