### ISSUE TITLE
[InstCombine] Combine `x + (x | -x)` into `x & (x - 1)`

### ISSUE THREAD

**Issue by Kmeakin** [llvm/llvm-project#57531]
This is listed in [Synthesizing an instruction selection rule library from semantic specifications](https://dl.acm.org/doi/10.1145/3168821) as an example of patterns that were synthesized by an SMT solver but were missing from both GCC and LLVM. This transformation may be particularly useful on x86-64, because `x & (x - 1)` can be performed by a single `blsr` instruction. 

32-bit example ([godbolt](https://godbolt.org/z/qqTzfznhb), [alive](https://alive2.llvm.org/ce/z/NJU9vK)):
```c
uint32_t src(uint32_t x, uint32_t y) { return x + (x | -x); }

uint32_t tgt(uint32_t x, uint32_t y) { return x & (x - 1); }
```

**Comment by marcauberer** [comment]
I'd like to work on this, may I?

**Comment by Kmeakin** [comment]
> I'd like to work on this, may I?

Of course.

**Comment by marcauberer** [comment]
Solution proposed [here](https://reviews.llvm.org/D133362).
