### ISSUE TITLE
With gcc-12's libstdc++, clang-15 rc2 still cannot compile CUDA/HIP code because of __noinline__

### ISSUE THREAD

**Issue by littlewu2508** [llvm/llvm-project#57544]
Although https://reviews.llvm.org/D124866 aims to fix bugs such as https://github.com/NVIDIA/thrust/issues/1703 or https://bugs.gentoo.org/857126

When I tried clang-15 rc2, the issue still exists.

Reproduce method:

pure C++ test.C
```c++
#define __noinline__ __attribute__((noinline))
#include<future>

int main()
{
        return 0;
}
```

Run `clang++ test.C`

HIP code example test.hip
```c++
#include <hip/hip_runtime.h>
#include<future>

int main()
{
        return 0;
}
```
Run `clang++ -nogpulib -nogpuinc -x hip test.hip`

Both gives error: `g++-v12/bits/shared_ptr_base.h:196:22: error: use of undeclared identifier 'noinline'; did you mean 'inline'?`

**Comment by littlewu2508** [comment]
I looked at the commit blurb between rc3 and rc2, and I guess there is no fix focusing on this, so I decided to report. If it's fixed in rc3, please ignore me

**Comment by littlewu2508** [comment]
@yxsamliu CC'ing  the author of https://reviews.llvm.org/D124866

**Comment by Artem-B** [comment]
It appears that something have changed in libstdc++ headers between gcc-11.3 and 12.1:
https://cuda.godbolt.org/z/EvzG5TPzr

**Comment by littlewu2508** [comment]
> It appears that something have changed in libstdc++ headers between gcc-11.3 and 12.1: https://cuda.godbolt.org/z/EvzG5TPzr

Right, that's why many error emerges when gcc12 released: https://bugs.gentoo.org/857126

I thought https://reviews.llvm.org/D124866 is just for it but it does not.

**Comment by yxsamliu** [comment]
with gcc12.1

/opt/compiler-explorer/gcc-12.1.0/lib/gcc/x86_64-linux-gnu/12.1.0/../../../../include/c++/12.1.0/bits/shared_ptr_base.h:196:22: error: use of undeclared identifier 'noinline'; did you mean 'inline'?
      __attribute__((__noinline__))
                     ^
/opt/compiler-explorer/cuda/11.7.0//include/crt/host_defines.h:83:24: note: expanded from macro '__noinline__'
        __attribute__((noinline))

CUDA header defines `__noinline__` as `__attribute__((noinline))`. gcc12 uses `__attribute__((__noinline__))`. This ends up as `__attribute__((__attribute__((noinline))))`. clang emits error for that. One workaround is to intercept host_defines.h and undef `__noinline__` in clang default include header for CUDA. HIP is not subject to this issue.

**Comment by littlewu2508** [comment]
> CUDA header defines `__noinline__` as `__attribute__((noinline))`. gcc12 uses `__attribute__((__noinline__))`. This ends up as `__attribute__((__attribute__((noinline))))`. clang emits error for that. One workaround is to intercept host_defines.h and undef `__noinline__` in clang default include header for CUDA. 

Yes, that's what I'm currently doing, but it's a bit ugly and requires a big patch for large projects, which means maintaining difficulties.

> HIP is not subject to this issue.
HIP also suffers: https://github.com/ROCm-Developer-Tools/hipamd/blob/bf49b11d07064ec56ea130c3a73beb216d81f582/include/hip/amd_detail/host_defines.h#L51

And that's why bugs like https://bugs.gentoo.org/857126 is present.

**Comment by yxsamliu** [comment]
> > CUDA header defines `__noinline__` as `__attribute__((noinline))`. gcc12 uses `__attribute__((__noinline__))`. This ends up as `__attribute__((__attribute__((noinline))))`. clang emits error for that. One workaround is to intercept host_defines.h and undef `__noinline__` in clang default include header for CUDA.
> 
> Yes, that's what I'm currently doing, but it's a bit ugly and requires a big patch for large projects, which means maintaining difficulties.
> 
> > HIP is not subject to this issue.
> 
> HIP also suffers: https://github.com/ROCm-Developer-Tools/hipamd/blob/bf49b11d07064ec56ea130c3a73beb216d81f582/include/hip/amd_detail/host_defines.h#L51
> 
> And that's why bugs like https://bugs.gentoo.org/857126 is present.

There is a condition for that macro `!__has_feature(cuda_noinline_keyword)`. My patch https://reviews.llvm.org/D124866 enable that feature, therefore HIP no longer defines that macro. In that sense, I said 'HIP is not subject to this issue'.

**Comment by littlewu2508** [comment]
@yxsamliu  I carefully read your patch, and figured out I misunderstood it previously. With your patch, CUDA/HIP can compile without define `#define __noinline__ __attribute__((noinline))` in their api headers (I also made a MWE which confirms that). So with your patch, and removing `#define __noinline__ __attribute__((noinline))` as well, problem with gcc-12 solved.

Thanks for your extra explanation!

**Comment by Artem-B** [comment]
Looks like we do still have this problem:

```
echo '#include <memory>'|  bin/clang --cuda-path=$HOME/local/cuda-12.1.1 -x cuda --offload-arch=sm_60 - -c -stdlib=libstdc++ --cuda-device-only -c
clang: warning: CUDA version is newer than the latest partially supported version 11.8 [-Wunknown-cuda-version]
In file included from <stdin>:1:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/memory:77:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr.h:53:
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:196:22: error: use of undeclared identifier 'noinline'; did you mean 'inline'?
      __attribute__((__noinline__))
                     ^
/usr/local/google/home/tra/local/cuda-12.1.1/include/crt/host_defines.h:83:24: note: expanded from macro '__noinline__'
        __attribute__((noinline))
                       ^
In file included from <stdin>:1:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/memory:77:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr.h:53:
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:196:22: error: type name does not allow function specifier to be specified
/usr/local/google/home/tra/local/cuda-12.1.1/include/crt/host_defines.h:83:24: note: expanded from macro '__noinline__'
        __attribute__((noinline))
                       ^
In file included from <stdin>:1:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/memory:77:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr.h:53:
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:196:22: error: expected expression
/usr/local/google/home/tra/local/cuda-12.1.1/include/crt/host_defines.h:83:33: note: expanded from macro '__noinline__'
        __attribute__((noinline))
                                ^
3 errors generated when compiling for sm_60.
```

Proposed workaround: https://reviews.llvm.org/D149364

**Comment by ewof** [comment]
pls figgs

**Comment by Yaraslaut** [comment]
Hello, is there any news on this issue?

**Comment by Artem-B** [comment]
The workaround has landed in a50e54fbeb48fb8a218a2914d827e1087bae2f8d and should be present in clang-17.

clang-15 or -16 will not have the fix.

**Comment by Yaraslaut** [comment]
I am still see some issues of this kind 
```
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/string:55:
/usr/lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/basic_string.tcc:473:20: error: expected expression
/opt/cuda/include/crt/host_defines.h:83:33: note: expanded from macro '__noinline__'
   83 |         __attribute__((noinline))
      |                                 ^
      ```

**Comment by Artem-B** [comment]
That's a new instance. Looks like we'll be playing this game of whack-a-mole for a while. :-(

**Comment by Yaraslaut** [comment]
full list of `__noinline__` attributes 
```
/u/i/c/13.2.1 ❱ pwd
/usr/include/c++/13.2.1
/u/i/c/13.2.1 ❱ rg "__noinline__"
stacktrace
251:      [[__gnu__::__noinline__]]
267:      [[__gnu__::__noinline__]]
287:      [[__gnu__::__noinline__]]

bits/shared_ptr_base.h
196:      __attribute__((__noinline__))

bits/basic_string.tcc
473:    __attribute__((__noinline__, __noclone__, __cold__)) void

bits/basic_string.h
2532:      __attribute__((__noinline__, __noclone__, __cold__)) void

experimental/bits/simd_detail.h
263:#define _GLIBCXX_SIMD_NEVER_INLINE [[__gnu__::__noinline__]]
```

**Comment by Artem-B** [comment]
If you try to include `<stacktrace>` from a CUDA source, does it compile or fail?

**Comment by Yaraslaut** [comment]
with ` [[__gnu__::__noinline__]]` everything is ok

**Comment by Artem-B** [comment]
I have no way to install new libstdc++ on my machine. Would you be able to test the patch for me?
https://github.com/Artem-B/llvm-project/commit/227d9a75eb3042c5af4cebbe952ed0dffb6943f3

**Comment by Yaraslaut** [comment]
Sure, will test it now

**Comment by Artem-B** [comment]
For the record, here is the full list of occurrences of `__noinline__` in libstdc++:
https://github.com/search?q=repo%3Agcc-mirror%2Fgcc+path%3Alibstd+-path%3Atestsuite+__noinline&type=code

![image](https://github.com/llvm/llvm-project/assets/526795/36ea336b-f2b5-460e-a088-61fc2a8c8429)

**Comment by Yaraslaut** [comment]
> I have no way to install new libstdc++ on my machine. Would you be able to test the patch for me? [Artem-B@227d9a7](https://github.com/Artem-B/llvm-project/commit/227d9a75eb3042c5af4cebbe952ed0dffb6943f3)

you just forgot to add this files in CMakeList.txt
```
diff --git a/clang/lib/Headers/CMakeLists.txt b/clang/lib/Headers/CMakeLists.txt
index 39030d433a61..d1ea5fa1a3e7 100644
--- a/clang/lib/Headers/CMakeLists.txt
+++ b/clang/lib/Headers/CMakeLists.txt
@@ -289,6 +289,8 @@ set(cuda_wrapper_files

 set(cuda_wrapper_bits_files
   cuda_wrappers/bits/shared_ptr_base.h
+  cuda_wrappers/bits/basic_string.tcc
+  cuda_wrappers/bits/basic_string.h
 )

 set(ppc_wrapper_files
 ```
and now I  can finally compile with clang
