### ISSUE TITLE
bolt: fails to build with `/usr/bin/ld.gold: internal error in do_layout, at ../../gold/object.cc:1939`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#57545]
Trying to build bolt in 15 rc3:
```console
: && "/home/sylvestre/dev/debian/pkg-llvm/llvm-toolchain/branches/llvm-toolchain-15-15.0.0~+rc3/build-llvm/./bin/clang++" -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/home/sylvestre/dev/debian/pkg-llvm/llvm-toolchain/branches/llvm-toolchain-15-15.0.0~+rc3/build-llvm/tools/clang/stage2-bins=build-llvm/tools/clang/stage2-bins -ffile-prefix-map=/home/sylvestre/dev/debian/pkg-llvm/llvm-toolchain/branches/llvm-toolchain-15-15.0.0~+rc3/= -no-canonical-prefixes -O3 -DNDEBUG -Wl,-z,relro -Wl,--build-id -fuse-ld=gold    -Wl,--gc-sections  -Xlinker --emit-relocs tools/bolt/tools/merge-fdata/CMakeFiles/merge-fdata.dir/merge-fdata.cpp.o -o bin/merge-fdata  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVM-15.so.1 && :
/usr/bin/ld.gold: internal error in do_layout, at ../../gold/object.cc:1939
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by MaskRay** [comment]
Can you re-link the output with `-fuse-ld=lld -Wl,--reproduce=/tmp/rep.tar` and upload the tarball somewhere?

**Comment by sylvestre** [comment]
Of course, it works with lld  ;)
I uploaded it here: http://sylvestre.ledru.info/bordel/rep.tar.gz

gold version (debian testing)
```
$ ld.gold --version
GNU gold (GNU Binutils for Debian 2.38) 1.16
Copyright (C) 2022 Free Software Foundation, Inc.
Ce logiciel est libre ; vous pouvez le redistribuer selon les termes de la
version 3 ou suivante de la licence GNU General Public License.
Ce programme n'est couvert par AUCUNE garantie.

```

**Comment by aaupov** [comment]
Hi @sylvestre,

Thank you for flagging. It's a known problem that gold linker doesn't support emit-relocs together with icf. Merge-fdata binary is linked with relocs for one BOLT test. You can disable tests for your build with -DBOLT_

**Comment by MaskRay** [comment]
This is https://sourceware.org/bugzilla/show_bug.cgi?id=25968

With `--emit-relocs + (--gc-sections || --icf)`, a very simple object file with `.rela.eh_frame` can trigger the gold assertion bug.
http://sylvestre.ledru.info/bordel/rep.tar.gz uses `--emit-relocs --gc-sections`.

**Comment by sylvestre** [comment]
As I am building with stage2, maybe we could use lld to do the linking ?

**Comment by sylvestre** [comment]
Not ideal but this skips the issue:
```
Index: llvm-toolchain-15-15.0.0~+rc3/bolt/tools/merge-fdata/CMakeLists.txt
===================================================================
--- llvm-toolchain-15-15.0.0~+rc3.orig/bolt/tools/merge-fdata/CMakeLists.txt
+++ llvm-toolchain-15-15.0.0~+rc3/bolt/tools/merge-fdata/CMakeLists.txt
@@ -9,6 +9,6 @@ add_bolt_tool(merge-fdata
 set_target_properties(merge-fdata PROPERTIES FOLDER "BOLT")
 
 # Emit relocations for BOLT meta test (bolt/test/runtime/meta-merge-fdata.test)
-if (BOLT_INCLUDE_TESTS AND UNIX AND NOT APPLE)
-  target_link_options(merge-fdata PRIVATE LINKER:--emit-relocs)
-endif()
+# if (BOLT_INCLUDE_TESTS AND UNIX AND NOT APPLE)
+#   target_link_options(merge-fdata PRIVATE LINKER:--emit-relocs)
+# endif()

```

**Comment by aaupov** [comment]
> As I am building with stage2, maybe we could use lld to do the linking ?

Yes, I think adding `-DLLVM_ENABLE_LLD=ON` is a good idea in a multi-stage build.

**Comment by v01dXYZ** [comment]
Hello,

Any news from the LLVM maintainers of bolt ? The problem is still present https://github.com/llvm/llvm-project/blob/0e9384a6c6ca86e042a1ed75c5f22db7cf14f132/bolt/tools/merge-fdata/CMakeLists.txt#L16

@sylvestre seems to have solved it the hard way in the debian build script (https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/blob/snapshot/debian/patches/bolt-disable-emit-relocs.patch).

**Comment by v01dXYZ** [comment]
I'll go with disabling the bolt tests with `BOLT_INCLUDE_TESTS=OFF` as it seems cleaner than patching the cmake file. The binutils linker issue seems pretty old now ([at least 17 yo](https://binutils.sourceware.narkive.com/uep3O7xM/ld-gc-sections-incompatible-with-emit-relocs#:~:text=Yes.%20The%20problem%20is%20that%20if%20relocations%20are,garbage%20collected%20sections%20should%20be%20emitted%20or%20not)) so I guess it will remain that way forever.

Thank for the response.
