### ISSUE TITLE
[15 regression] LibreOffice fails to start up when built with clang 15

### ISSUE THREAD

**Issue by berolinux** [llvm/llvm-project#57566]
Sorry, no small test case yet:
LibreOffice 7.4.1.1 (as well as 7.4.0.3) fails to start up when built with clang 15 (simply freezes when trying to display the splash screen).
An otherwise identical LibreOffice build works fine when built with either clang 14.0.6 or gcc 12.2.

**Comment by EugeneZelenko** [comment]
I think will be good idea to attach debugger or enable logging (if such facilities are available). Or use tools like `strace`.

**Comment by berolinux** [comment]
This is fixed in 16.0.6
