### ISSUE TITLE
Bazel Build: undefined symbol: environ

### ISSUE THREAD

**Issue by Amzo** [llvm/llvm-project#57560]
When building llvm with Bazel on FreeBSD the follow symbol is considered undefined:

```console
ld: error: undefined symbol: environ
```

However, in FreeBSD the `environ` symbol is not defined in `libc.so.7`, but it exists in `crt1.o`.

```shell
readelf -s work-bazel-out/k8-opt/bin/external/llvm-project/llvm/libSupport.pic.a | grep environ
```

outputs the following

```console
99: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND environ
```

`environ` is used in the file:

```shell
grep environ llvm/lib/Support/Unix/Program.inc
```

Shows this:
```console
extern char **environ;
```

Which is the correct declaration.

Compiling a simple test program and compiling without Bazel shows:

```cpp
extern char **environ;

int main() {
    return 0;
}
```

Results in the `environ` symbol shown as:

```console
$ readelf -s a.out | grep environ
     5: 0000000000203aa0     8 OBJECT  GLOBAL DEFAULT   24 environ
```

So either Bazel is building something it shouldn't on FreeBSD as building with cmake is fine, or the symbols are being hidden somewhere.

**Comment by aaronmondal** [comment]
Full context (`crt_externs.h` seems to only exist on apple):
https://github.com/llvm/llvm-project/blob/91d8324366f405e871aa8174ab61fc66912964dd/llvm/lib/Support/Unix/Program.inc#L51-L62

This seems to be a bug in FreeBSD. Build systems need to opt out of `-Wl,--no-undefined`:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=263265
https://reviews.freebsd.org/D30842
