### ISSUE TITLE
Flang can't find hypotf on Windows on Arm

### ISSUE THREAD

**Issue by rovka** [llvm/llvm-project#57563]
Flang fails to compile this simple snippet (reduced from OpenBLAS by Everton Constantino):
```f90
! RUN: flang-new.exe hypot.f90 -flang-experimental-exec -o hypot
program hello
    real(4) :: x = 1.e0_4, y = 0.5e0_4
    x = hypot(x,y)
    print *, 'Hello, World!'
end program hello
```
The error message is: `lld-link: error: undefined symbol: hypotf`
Note that `clang-cl.exe` manages to compile an equivalent C snippet. The link command generated by `clang-cl.exe` is very similar to that generated by `flang-new.exe`; however the CC1 command used by `clang-cl.exe` contains `"--dependent-lib=libcmt" "--dependent-lib=oldnames"`, which essentially embeds this information for the linker in the object files (I haven't actually inspected the object files, but removing those flags from the CC1 line results in link-time errors). 
Note that at the moment [we intentionally refrain](https://github.com/llvm/llvm-project/blob/1f550d86b236de88d684aeecfde3cc7738640bb7/clang/lib/Driver/ToolChains/MSVC.cpp#L84) from adding `libcmt` and `oldnames` to flang's linker invocation. Adding them to the linker invocation doesn't seem to solve the issue. OTOH, adding `-defaultlib:libucrt` produces errors about duplicate symbols. We should probably be getting hypotf from some of [MSVC's libraries](https://docs.microsoft.com/en-us/cpp/c-runtime-library/floating-point-support?view=msvc-170), but I'm not entirely sure how.

**Comment by efriedma-quic** [comment]
hypotf only exists in the math.h header, not the library; the compiler needs to call _hypotf instead, I think.  (MSVC does a bunch of weird stuff like this with the math functions with an "f" suffix.)

**Comment by Meinersbur** [comment]
To add to @efriedma-quic's answer, Microsoft's ucrt math.h header declares [`hypotf` ](https://github.com/tpn/winsdk-10/blob/9b69fd26ac0c7d0b83d378dba01080e93349c2ed/Include/10.0.16299.0/ucrt/corecrt_math.h#L700) roughly as
```
    inline float hypotf(float X, float Y) {
        return _hypotf(X, Y);
    }
```

Brainstorming solutions:
1. Provide an implementation of `hypotf` in Flang's runtime when compiling for Windows[^1].
2. Modify the lowering in `hypot` in https://github.com/llvm/llvm-project/blob/6a2442e9be2529ee00b0239330df068b91c92aab/flang/lib/Lower/IntrinsicCall.cpp#L1320 to the underscore version when compiling for Windows[^1].

[^1]: excluding Cygwin, probably `Triple::isOSMSVCRT()` is the correct test.

**Comment by rovka** [comment]
Hi, thanks for the comments! I just posted a patch implementing option #2: https://reviews.llvm.org/D134860
I welcome further discussion (either here or in Phab).
Sorry it took so long to circle back to this :D
