### ISSUE TITLE
Please include Apple Silicon build in Releases

### ISSUE THREAD

**Issue by yay** [llvm/llvm-project#57575]
There's only [clang+llvm-14.0.6-x86_64-apple-darwin.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/clang+llvm-14.0.6-x86_64-apple-darwin.tar.xz) build here:

https://github.com/llvm/llvm-project/releases/tag/llvmorg-14.0.6

Please include Apple Silicon build.

**Comment by rubyFeedback** [comment]
Not having anything against this, but just as a general remark: on Linux there are tons of
different distributions. Some projects offer distribution-specific bundles. This in turn means
tons of different downloads. Even managing via scripts this can become cumbersome e. g.
when you try to find the appropriate download (I typically pick "linux-64-bit" aka any
non-distribution specific variant). I understand that it is a bit different for Apple, and llvm
is sufficiently important to consider expanding the use cases for people seeking these
binaries, so I am absolutely not in disagreement with the above. I just wanted to point
at that (small?) issue. In regards to linux distributions I also find it the wrong approach
to take - the binaries should be offered by the corresponding distribution itself. It should
then not be the job of llvm or any other project to do so. (The generic linux 64 bit
download tends to work from my experience in general, so I don't even know why some
projects want to cover every possible linux distribution...)

**Comment by EugeneZelenko** [comment]
15 is only supported release branch.

**Comment by yay** [comment]
> 15 is only supported release branch.

That's fine. Having them going forward would still be great.

**Comment by efriedma-quic** [comment]
CC @DimitryAndric

**Comment by wdlkmpx** [comment]
Please ignore rubyFeedback, I'm kind of worried that the Linux
binaries have not been uploaded, I use the amd64 ones, I imagine it takes hours to compile in a modern PC

**Comment by DimitryAndric** [comment]
Built and uploaded under https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.0, see https://discourse.llvm.org/t/llvm-15-0-0-final-tagged/65097/6

**Comment by yay** [comment]
Thank you!

**Comment by yay** [comment]
<img width="956" alt="Screenshot 2022-09-10 at 11 15 32 AM" src="https://user-images.githubusercontent.com/1799756/189478891-41a985ac-af91-4995-9f2f-43450603a63a.png">

I just tried it out and I'm getting the following error. Shouldn't it come bundled with `libzstd`?

**Comment by DimitryAndric** [comment]
Yeah, I noticed this some time ago in https://discourse.llvm.org/t/please-add-arm64-apple-darwin-binary-to-releases/64135/7, but there was never a good resolution. I guess the easiest way is to install Homebrew on your Mac and install at least the zstd tap.

Otherwise, I'd have to rebuild the whole thing with libzstd disabled somehow, or  with libztd linked in statically. Both of which I don't know how to do, and might have to find the time for...

@tru didn't this issue also affect the x86_64 builds? As it is really architecture-agnostic, it only depends on whether the CMake logic is able to find libzstd on the system that is used to build the release.

**Comment by tru** [comment]
> Yeah, I noticed this some time ago in https://discourse.llvm.org/t/please-add-arm64-apple-darwin-binary-to-releases/64135/7, but there was never a good resolution. I guess the easiest way is to install Homebrew on your Mac and install at least the zstd tap.
> 
> Otherwise, I'd have to rebuild the whole thing with libzstd disabled somehow, or with libztd linked in statically. Both of which I don't know how to do, and might have to find the time for...
> 
> @tru didn't this issue also affect the x86_64 builds? As it is really architecture-agnostic, it only depends on whether the CMake logic is able to find libzstd on the system that is used to build the release.

It was discussed in one thread where I said I would turn off zstd for the release and did so.

**Comment by tru** [comment]
Pass `-configure-flags -DLLVM_ENABLE_ZSTD=OFF` to test-release.sh

**Comment by DimitryAndric** [comment]
I've re-done the release build, with this patch applied:

```diff
--- a/llvm/lib/Support/CMakeLists.txt
+++ b/llvm/lib/Support/CMakeLists.txt
@@ -26,7 +26,7 @@ if(LLVM_ENABLE_ZLIB)
 endif()

 if(LLVM_ENABLE_ZSTD)
-  list(APPEND imported_libs zstd::libzstd_shared)
+  list(APPEND imported_libs zstd::libzstd_static)
 endif()

 if( MSVC OR MINGW )
@@ -300,10 +300,10 @@ if(LLVM_ENABLE_ZSTD)
   # CMAKE_BUILD_TYPE is only meaningful to single-configuration generators.
   if(CMAKE_BUILD_TYPE)
     string(TOUPPER ${CMAKE_BUILD_TYPE} build_type)
-    get_property(zstd_library TARGET zstd::libzstd_shared PROPERTY LOCATION_${build_type})
+    get_property(zstd_library TARGET zstd::libzstd_static PROPERTY LOCATION_${build_type})
   endif()
   if(NOT zstd_library)
-    get_property(zstd_library TARGET zstd::libzstd_shared PROPERTY LOCATION)
+    get_property(zstd_library TARGET zstd::libzstd_static PROPERTY LOCATION)
   endif()
   set(llvm_system_libs ${llvm_system_libs} "${zstd_library}")
 endif()
```

Before I attempt to delete and replace the existing releases tarball, would you please check if the result works for you, and you successfully run clang, opt, lld, etc?

Tarball: https://www.andric.com/llvm/clang+llvm-15.0.0-arm64-apple-darwin21.0.tar.xz

```
SHA256 (clang+llvm-15.0.0-arm64-apple-darwin21.0.tar.xz) = 0561d31e42e3508def0cee0eb1748d35cfcaf2324bea8a94da0fe5b90a15945c
```

**Comment by yay** [comment]
Thank you, that worked!
