### ISSUE TITLE
Miscompilation at -O2/-O3 when Openmp optimistic attributes are enabled 

### ISSUE THREAD

**Issue by malharjajoo** [llvm/llvm-project#57578]
I believe there is a possible miscompilation when the below C file is compiled when clang
has openmp optimistic attributes enabled at higher optimization levels. 

It looks like an issue due to the `omp_get_wtime()` getting CSE'd by EarlyCSE pass.

Following information is provided below:

1. Reproducer file
2. command to reproduce bug
3. current output and expected output
4. Some further information

`reproducer.c`
```c
#include <omp.h>
#include <stdio.h>

void foo()
{
    const double duration_seconds = 5.0;
    const double start = omp_get_wtime();
    double x = 0.5;
    while (omp_get_wtime() - start < duration_seconds) {
        for (int i = 0; i < 100; ++i) x = x*(1.0-x);
    }

    printf("x = %lf\n", x);
}

int main() {
    foo();
    return 0;
}
```

Command to reproduce bug:
```bash
# Note: LLVM needs to be built with openmp enabled
clang reproducer.c -mllvm -openmp-ir-builder-optimistic-attributes -fno-inline -fopenmp -O2  -o reproducer_exe
time ./reproducer_exe
```

Current output:

```console
x = 0.500000

real	0m0.003s
user	0m0.003s
sys	0m0.000s
```

Expected output: 
Use same reproducer command as above, but without the `-mllvm -openmp-ir-builder-optimistic-attributes`
(Note: The time values need not be exact, execution should take around 5 seconds if compiled correctly):

```console
x = 0.000000

real	0m5.003s
user	0m2.402s
sys	0m2.601s
```

On printing some IR + debug info, this can be seen.
```console
$ clang reproducer.c -mllvm -openmp-ir-builder-optimistic-attributes -mllvm -debug-only=early-cse -fno-inline -fopenmp -O2  -S -emit-llvm -o -
// some other debug info
EarlyCSE CSE CALL:   %call1 = call double @omp_get_wtime()  to:   %call = call double @omp_get_wtime()
// some other debug info
```

And then a look at the IR shows that the nested loop has been optimized away leaving only the printf call.
The outer loop control condition contains a call to `omp_get_wtime()` which gets CSE'd with another call 
before it (`start = omp_get_wtime()`). This causes the IR to contain a condition like this

```llvm
%sub = fsub double %call, %call
%cmp = fcmp uge double %sub, 5.000000e+00
```
and I suppose that makes the compiler think that the outer loop will never be executed and hence it removes it completely

**Comment by fhahn** [comment]
Could you share the IR before `EarlyCSE` (using `-mllvm -print-before=earlycse -mllvm -print-module-scope`?

**Comment by malJaj** [comment]
Sure, I have provided it below 

```
; ModuleID = 'tmp.c'
source_filename = "tmp.c"
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

@.str = private unnamed_addr constant [9 x i8] c"x = %lf\0A\00", align 1

; Function Attrs: nofree noinline nounwind uwtable
define dso_local void @foo() local_unnamed_addr #0 {
entry:
  %call = tail call double @omp_get_wtime()
  %sub = fsub double %call, %call
  %cmp = fcmp uge double %sub, 5.000000e+00
  tail call void @llvm.assume(i1 %cmp)
  %call4 = tail call i32 (ptr, ...) @printf(ptr noundef nonnull @.str, double noundef 5.000000e-01)
  ret void
}

; Function Attrs: inaccessiblememonly nofree nosync nounwind readonly willreturn
declare double @omp_get_wtime() local_unnamed_addr #1

; Function Attrs: nofree nounwind
declare noundef i32 @printf(ptr nocapture noundef readonly, ...) local_unnamed_addr #2

; Function Attrs: nofree noinline nounwind uwtable
define dso_local i32 @main() local_unnamed_addr #0 {
entry:
  tail call void @foo()
  ret i32 0
}

; Function Attrs: inaccessiblememonly nocallback nofree nosync nounwind willreturn
declare void @llvm.assume(i1 noundef) #3

attributes #0 = { nofree noinline nounwind uwtable "frame-pointer"="non-leaf" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+neon,+v8a" }
attributes #1 = { inaccessiblememonly nofree nosync nounwind readonly willreturn "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+neon,+v8a" }
attributes #2 = { nofree nounwind "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+neon,+v8a" }
attributes #3 = { inaccessiblememonly nocallback nofree nosync nounwind willreturn }

!llvm.module.flags = !{!0, !1, !2, !3, !4, !5}
!llvm.ident = !{!6}
!nvvm.annotations = !{}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"openmp", i32 50}
!2 = !{i32 8, !"PIC Level", i32 2}
!3 = !{i32 7, !"PIE Level", i32 2}
!4 = !{i32 7, !"uwtable", i32 2}
!5 = !{i32 7, !"frame-pointer", i32 1}
!6 = !{!"clang version 16.0.0 (git@github.com:llvm/llvm-project.git 53f738ce7e6cc22d58c6cc1042c7b49cd81f75ae)"}
```

**Comment by malJaj** [comment]
I don't think the problem is clear in the above IR.

Is EarlyCSE run multiple times ? Because when I tried `-mllvm --print-after-all`
I can see that it's run twice, and the IR before and after the second EarlyCSE pass
clearly shows the issue.

I have attached this below:

```
*** IR Dump After SROAPass on foo ***
; Function Attrs: nofree noinline nounwind uwtable
define dso_local void @foo() local_unnamed_addr #0 {
entry:
  %call = call double @omp_get_wtime()
  br label %while.cond

while.cond:                                       ; preds = %for.cond, %entry
  %x.0 = phi double [ 5.000000e-01, %entry ], [ %x.1, %for.cond ]
  %call1 = call double @omp_get_wtime()
  %sub = fsub double %call1, %call
  %cmp = fcmp olt double %sub, 5.000000e+00
  br i1 %cmp, label %for.cond, label %while.end

for.cond:                                         ; preds = %while.cond, %for.body
  %x.1 = phi double [ %mul, %for.body ], [ %x.0, %while.cond ]
  %i.0 = phi i32 [ %inc, %for.body ], [ 0, %while.cond ]
  %cmp2 = icmp ult i32 %i.0, 100
  br i1 %cmp2, label %for.body, label %while.cond, !llvm.loop !7

for.body:                                         ; preds = %for.cond
  %sub3 = fsub double 1.000000e+00, %x.1
  %mul = fmul double %x.1, %sub3
  %inc = add nuw nsw i32 %i.0, 1
  br label %for.cond, !llvm.loop !9

while.end:                                        ; preds = %while.cond
  %call4 = call i32 (ptr, ...) @printf(ptr noundef nonnull @.str, double noundef %x.0)
  ret void
}
*** IR Dump After EarlyCSEPass on foo ***
; Function Attrs: nofree noinline nounwind uwtable
define dso_local void @foo() local_unnamed_addr #0 {
entry:
  %call = call double @omp_get_wtime()
  br label %while.cond

while.cond:                                       ; preds = %for.cond, %entry
  %x.0 = phi double [ 5.000000e-01, %entry ], [ %x.1, %for.cond ]
  %sub = fsub double %call, %call
  %cmp = fcmp olt double %sub, 5.000000e+00
  br i1 %cmp, label %for.cond, label %while.end

for.cond:                                         ; preds = %while.cond, %for.body
  %x.1 = phi double [ %mul, %for.body ], [ %x.0, %while.cond ]
  %i.0 = phi i32 [ %inc, %for.body ], [ 0, %while.cond ]
  %cmp2 = icmp ult i32 %i.0, 100
  br i1 %cmp2, label %for.body, label %while.cond, !llvm.loop !7

for.body:                                         ; preds = %for.cond
  %sub3 = fsub double 1.000000e+00, %x.1
  %mul = fmul double %x.1, %sub3
  %inc = add nuw nsw i32 %i.0, 1
  br label %for.cond, !llvm.loop !9

while.end:                                        ; preds = %while.cond
  %call4 = call i32 (ptr, ...) @printf(ptr noundef nonnull @.str, double noundef %x.0)
  ret void
}
```

**Comment by fhahn** [comment]
It looks like the issue is that `omp_get_wtime` has the `readonly` attribute. So `EarlyCSE` is doing the correct thing for the provided IR. As far as it is concerned, there are no writes in the loop, so `omp_get_wtime` outside and inside the loop will return the same value.

The question is where the incorrect attribute comes from? Probably whatever ` -openmp-ir-builder-optimistic-attributes` does?

**Comment by malJaj** [comment]
The incorrect attribute is coming from `OMPKinds.def` , where `OptimisticAttributes` is set 
to true by `-mllvm -openmp-ir-builder-optimistic-attributes`

```
__OMP_ATTRS_SET(GetterAttrs,
                OptimisticAttributes
                    ? AttributeSet(EnumAttr(NoUnwind), EnumAttr(ReadOnly),
                                   EnumAttr(NoSync), EnumAttr(NoFree),
                                   EnumAttr(InaccessibleMemOnly),
                                   EnumAttr(WillReturn))
                    : AttributeSet(EnumAttr(NoUnwind)))

// ...
// ... 

__OMP_RTL_ATTRS(omp_get_wtime, GetterAttrs, AttributeSet(), ParamAttrs())
```

**Comment by jhuber6** [comment]
> The `readonly` attribute is coming from `OMPKinds.def` , where `OptimisticAttributes` is set to true by `-mllvm -openmp-ir-builder-optimistic-attributes`
> 
> ```
> __OMP_ATTRS_SET(GetterAttrs,
>                 OptimisticAttributes
>                     ? AttributeSet(EnumAttr(NoUnwind), EnumAttr(ReadOnly),
>                                    EnumAttr(NoSync), EnumAttr(NoFree),
>                                    EnumAttr(InaccessibleMemOnly),
>                                    EnumAttr(WillReturn))
>                     : AttributeSet(EnumAttr(NoUnwind)))
> 
> // ...
> // ... 
> 
> __OMP_RTL_ATTRS(omp_get_wtime, GetterAttrs, AttributeSet(), ParamAttrs())
> ```

I don't think there's any testing configurations that use the optimistic attributes so it's likely that this went under the radar. This particular case is an easy fix, I can make a patch for it if needed.

**Comment by malJaj** [comment]
Thank you, a fix would be helpful.

How do you intend to fix it ?

**Comment by jhuber6** [comment]
> Thank you, a fix would be helpful.
> 
> How do you intend to fix it ?

Just removing the `readonly` attribute from its attribute set. As @fhahn said the problem is the `readonly` attribute on something whose value changes according to some hidden state. The LLVM language states the following, which means that we do not expect the state of the function to change in this way.
> On a function, this attribute indicates that the function does not write through any pointer arguments (including byval arguments) or otherwise modify any state (e.g. memory, control registers, etc) visible outside the readonly function.

**Comment by shiltian** [comment]
@jhuber6 JFYI, `readonly` is needed for target device, as mentioned in https://reviews.llvm.org/D130179.

**Comment by jhuber6** [comment]
made a review [D133360](https://reviews.llvm.org/D133360), it resolved the issue on my side. Can you verify?

**Comment by malJaj** [comment]
Thank you, it resolves the issue at my end too.
