### ISSUE TITLE
how to use clang-format option: assumeFilename

### ISSUE THREAD

**Issue by linzhongzi** [llvm/llvm-project#57574]
When I use `clang-format.assumeFilename` in vscode `settings.json`. It seems does not work.
the code below:
```json-with-comments
"clang-format.executable": "D:/Program Files/LLVM15/bin/clang-format.exe",
  // "clang-format.style": "file:${workspaceRoot}/.clang-format",
  "clang-format.assumeFilename": "D:/Users/tiandy/Desktop/Test/gcc/nnn/.clang-format", //定死了只读取.clang-format,原因不明
  //"clang-format.assumeFilename": "-style=${workspaceRoot}/.clang-format", //定死了只读取.clang-format,原因不明
  // "clang-format.assumeFilename": "${workspaceRoot}/.clang-format", //定死了只读取.clang-format,原因不明
  "clang-format.fallbackStyle": "Google",
```
It only read the file `${workspaceRoot}/.clang-format`. Neither other directory or other filename does not work.

**Comment by mydeveloperday** [comment]
This is not what -assume-filename is used for

![image](https://user-images.githubusercontent.com/16046346/189315574-774a0f6f-4dda-4433-bf33-88457f58ecb1.png)

lets say you do

cat test1.XXX | clang-format 

how does clang-format know what language the test1.XXX is as the filename isn't given to clang-format, this means it might not know how to interpret the file as C#,Cpp,Json,Protobuf etc...

the --assume-filename option is used to tell clang-format this is a particular language

cat test1.XXX | clang-format --assume-filename=Foo.json

now we know that test1.XXX is actually json and we can switch on the correct formatting rules for that languge

**Comment by mydeveloperday** [comment]
I'll close this unless you have other questions, feel free to reopen
