### ISSUE TITLE
[C++20] Documentation example of Standard C++ Modules doesn't compile with clang++-16

### ISSUE THREAD

**Issue by devel4848** [llvm/llvm-project#57571]
The [examples of Header Units](https://clang.llvm.org/docs/StandardCPlusPlusModules.html#header-units) compilation in the  "Standard C++ Modules" documentation page doesn't compile with clang++-16 (linker error).

Here is the log:
```console
$ clang++-16 --version
Ubuntu clang version 16.0.0-++20220905042104+45e2809f711e-1~exp1~20220905042159.402
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
$ cat main.cpp
import <iostream>;
int main() {
  std::cout << "Hello World.\n";
}
$ clang++-16 -std=c++20 -xc++-system-header --precompile iostream -o iostream.pcm
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/iostream:36:13: warning: #pragma system_header ignored in main file [-Wpragma-system-header-outside-header]
#pragma GCC system_header
            ^
1 warning generated.
$ ls -ltr
total 5652
-rw-rw-r-- 1 devel devel      79 sept.  6 07:34 main.cpp
-rw-r--r-- 1  devel devel 5780812 sept.  6 07:34 iostream.pcm
$ clang++-16 -std=c++20 -fmodule-file=iostream.pcm main.cpp
/usr/bin/ld: /tmp/main-68345d.o: in function `std::allocator_traits<std::allocator<char> >::deallocate(std::allocator<char>&, char*, unsigned long)':
main.cpp:(.text._ZNSt16allocator_traitsISaIcEE10deallocateERS0_Pcm[_ZNSt16allocator_traitsISaIcEE10deallocateERS0_Pcm]+0x21): undefined reference to `std::allocator<char>::deallocate(char*, unsigned long)'
/usr/bin/ld: /tmp/main-68345d.o: in function `std::allocator_traits<std::allocator<char> >::allocate(std::allocator<char>&, unsigned long)':
main.cpp:(.text._ZNSt16allocator_traitsISaIcEE8allocateERS0_m[_ZNSt16allocator_traitsISaIcEE8allocateERS0_m]+0x19): undefined reference to `std::allocator<char>::allocate(unsigned long)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by aaronmondal** [comment]
@devel4848 Ah I think there is a `-c` missing. Does this work?
```
clang++-16 -std=c++20 -xc++-system-header --precompile iostream -o iostream.pcm
clang++-16 -std=c++20 -fmodule-file=iostream.pcm main.cpp -c
clang++-16 -std=c++20 main.o
```
At least the second line should pass.

Linking when using header units currently seems to be very buggy and will likely require a few patches until it works. I think symbols declared in header units are registered twice when importing the same header unit multiple times in a build graph (at least when precompilation and compilation happen in different directories).

So I would expect linking to raise **no** errors or **duplicate** symbol errors, but not **undefined** symbol errors.

BTW the `#pragma` warning can be silenced with `-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER` :smiling_imp:

**Comment by operativeF** [comment]
I found this, possibly related, issue:
https://bugs.llvm.org/show_bug.cgi?id=51400

**Comment by operativeF** [comment]
If you were to instead specify libc++ explicitly like the following:
```
clang++ -std=c++20 -xc++-system-header --precompile iostream -o iostream.pcm -stdlib=libc++
clang++ -std=c++20 -fmodule-file=iostream.pcm main.cpp -c -stdlib=libc++
clang++ -std=c++20 main.o -stdlib=libc++ -lc++abi // <- Note the additional link to libc++abi here
```
It will work. Trying to use the GCC system headers / library won't work, and that's being implicitly used otherwise.

**Comment by ChuanqiXu9** [comment]
Reproduced with libstdc++12. Previously when I wrote this, I only tested libstdc++10.3. And it is a goal of clang to support libstdc++. So this is definitely a bug.
