### ISSUE TITLE
Non linear time on the size of a function argument

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5758]
|  |  |
| --- | --- |
| Bugzilla Link | [5386](https://llvm.org/bz5386) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I would expect that we would take constant time to produce assembly for

----------------------------
%0 = type <{ [FOO x i32] }>

define void @&#8203;verify(%0)  {
entry:
  ret void
}
----------------------------
but it looks like we take time O(FOO^2).

100:  0m0.018s
200:  0m0.023s
400:  0m0.032s
800:  0m0.064s
1600: 0m0.190s
3200: 0m0.597s
6400: 0m2.335s

**Comment by gwelymernans** [comment]
This doesn't seem relevant anymore. Compiling with `FOO == 6400` happens around the same amount of time as `FOO == 100`. If it still exists in some form, please open up a new bug.
