### ISSUE TITLE
flang crash

### ISSUE THREAD

**Issue by ghdpc** [llvm/llvm-project#57586]
I'm new to Fortran and apparently my Fortran is so bad it makes the compiler crash. This is on macOS 11.3.1(20E241). I've attached the source file in question. It's likely related to the declaration of `type(Card)` and the addition of the contained function `name`. I've also attached the crash log from my machine. Note that I had to rename the Fortran file to get GitHub to accept it as an attachment, so it's name "Solitaire.f90.txt" instead of just "Solitaire.f90".
[flang-new.crash.txt](https://github.com/llvm/llvm-project/files/9499781/flang-new.crash.txt)
[Solitaire.f90.txt](https://github.com/llvm/llvm-project/files/9499782/Solitaire.f90.txt)

**Comment by klausler** [comment]
Thanks for the bug report; I'll look at it soon.

**Comment by klausler** [comment]
Minimal reproducer:

**Comment by klausler** [comment]
https://reviews.llvm.org/D134504

**Comment by klausler** [comment]
Fix has been merged into llvm-project/main.
