### ISSUE TITLE
-march=ANYTHING is simply ignored silently for ppc64 targets

### ISSUE THREAD

**Issue by luke-jr** [llvm/llvm-project#57587]
On amd64:

```console
$ clang -march=BLAH a.c
error: unknown target CPU 'BLAH'
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, rocketlake, icelake-server, tigerlake, sapphirerapids, alderlake, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, znver3, x86-64, x86-64-v2, x86-64-v3, x86-64-v4
```

But on ppc64:

```console
$ clang -march=BLAH a.c
$ ls a.out  -lh
-rwxr-xr-x 1 luke-jr luke-jr 7.2K Sep  6 15:18 a.out
```

This can hypothetically cause problems if a configure script checks for (eg) `-march=armv8-a+crc+crypto` being valid, and then tries to actually use those ARM features.

**Comment by MaskRay** [comment]
I recently noticed this as well: https://maskray.me/blog/2022-08-28-march-mcpu-mtune#powerpc . I'll prepare a Driver patch rejecting -march= for ppc.

**Comment by luke-jr** [comment]
I wonder if it would be better to alias it to -mcpu so it works like other architectures

**Comment by ecnelises** [comment]
Currently it emits a warning:

```
clang: warning: argument unused during compilation: '-march=BLAH' [-Wunused-command-line-argument]
```

**Comment by MaskRay** [comment]
> I wonder if it would be better to alias it to -mcpu so it works like other architectures

No, this will be a bad idea. Many architectures don't support `-march=` and we should not alias `-march=` to `-mcpu=`.
x86 is actually odd one here that uses `-march=` for something like `-mcpu=` on other architectures (aarch64,ppc,riscv...).

I created https://reviews.llvm.org/D145141 to reject `-march=` for ppc like we did recently for Sparc.
