### ISSUE TITLE
[MLIR Core] `Attribute` shouldn't be implicitly convertible to `TypedAttr`

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#57592]
I ran into a runtime crash today that should have been caught at compile time, this:

```c
void foo(TypedAttr ta);
void bar(Attribute a) {
  foo(a);
}
```

While we should support an /explicit/ cast from Attribute to TypedAttr, this shouldn't be implicit.

**Comment by jpienaar** [comment]
Was crash/failure here due to cast reporting invalid conversion at runtime? (I'm assuming assert in debug mode here and crash was in non-assert but wanted to check).

**Comment by lattner** [comment]
Yeah it was an assertion fail at runtime

**Comment by lattner** [comment]
This got fixed, thanks!
