### ISSUE TITLE
IPSCCP and LibCallSimplifier

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#57599]
An interesting (perhaps) case from the Linux kernel:
https://lore.kernel.org/llvm/20220905003732.752-2-mailhol.vincent@wanadoo.fr/

So it looks like IPSCCP sinks constants into `ffs`, dead arg elimination removes the argument, then `LibCallSimplifier::optimizeFFS` fails to optimize this case.

Maybe IPSCCP should be trying to match such functions BEFORE sinking constants?

cc @fhahn @efriedma-quic @davidbolvansky

**Comment by fhahn** [comment]
@nickdesaulniers could you share the IR before IPSCCP for the example in the thread? It looks like it requires access to the Linux kernel headers.

**Comment by nickdesaulniers** [comment]
We basically have: https://godbolt.org/z/61o54WhKe

```c
//#include <strings.h>

static inline int ffs (int x) {
    int r;
    asm("bsfl %1,%0"
        : "=r" (r)
        : "rm" (x), "0" (-1));
    return r + 1;
}

  #define CONST 0x01000000

  unsigned int foo(void)
  {
  	return ffs(CONST);
  }

  unsigned int bar(void)
  {
  	return __builtin_ffs(CONST);
  }
```

**Comment by efriedma-quic** [comment]
If you have "static inline int ffs", we won't recognize that as a library function no matter what optimizations have/have not run.

**Comment by nickdesaulniers** [comment]
Ah, right. I feel like you may have mentioned that to me before...
