### ISSUE TITLE
[Flang] Compile spec2017 without using pgmath

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#57602]
Spec benchmark contains calls to several math functions. Recent work by @vzakhari incorporated lowerings to the math dialect of MLIR to handle floating point and integer math intrinsic functions. The complex intrinsic functions continue to rely on the pgmath library. This causes some linking errors if the library is not available. Ideally, in the default mode, we should use the MLIR complex dialect or calls to libm functions or custom calls to flang runtime functions to handle complex math functions. 
Note 1: Using the complex dialect operations might get us some benefits in folding.
Note 2: Check whether ABI or target specific transformations should be added to the complex dialect.

List of pgmath functions currently being called in spec.
```console
wrf:
ld.lld: error: undefined symbol: __fc_sqrt_1
ld.lld: error: undefined symbol: __fc_exp_1
ld.lld: error: undefined symbol: __fz_sqrt_1
ld.lld: error: undefined symbol: __fz_powi_1
ld.lld: error: undefined symbol: __fz_log_1

cam4:
ld.lld: error: undefined symbol: __fz_sqrt_1
ld.lld: error: undefined symbol: __fz_powi_1
ld.lld: error: undefined symbol: __fz_exp_1
ld.lld: error: undefined symbol: __fz_pow_1

fotonik:
ld.lld: error: undefined symbol: __fz_exp_1
```

**Comment by ggouaillardet** [comment]
I am facing a similar problem with `flang-new` built from the `llvm-project-15.0.0.src.tar.xz` tarball on `aarch64`:

```
$ cat test.f90 
program foo

    complex :: c
    c = 2.0
    write(*,*) sqrt(c)

end program
$ flang-new test.f90 -L/opt/llvm-15.0.0/lib
/opt/binutils-2.38/bin/ld: /tmp/test-f595ae.o: in function `_QQmain':
/home/rist/r00018/./test.f90:5: undefined reference to `__fc_sqrt_1'
flang-new: error: linker command failed with exit code 1 (use -v to see invocation)
```

A workaround is to manally build `libpgmath` and add it to the link command line

```
$ flang-new test.f90 -L/opt/llvm-15.0.0/lib -L$HOME/local/libpgmath/lib -lpgmath
$
```

One disturbing (at least for me) part is that `libpgmath` is not part of the `llvm-project-15.0.0.src.tar.xz` tarball.

**Comment by kiranchandramohan** [comment]
Fixed by https://reviews.llvm.org/D134889, https://reviews.llvm.org/D135882

Closing. @ggouaillardet If you still see issues then please let us know.
