### ISSUE TITLE
Wrong loop-metadata for nested loop after loop-simplify splitting out a new outer loop

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#57603]
llvm commit: 4bf84e433d
Reproduce with: ```opt < bbi-73295.ll -passes='print<loops>,loop-simplify,print<loops>' -S -debug```
[bbi-73295.ll.gz](https://github.com/llvm/llvm-project/files/9505467/bbi-73295.ll.gz)

Result:
```console
Parallel Loop at depth 1 containing: %while.cond<header>,%lor.end<exiting>,%while.body<latch>,%while.body.thread<latch>
LoopSimplify: Splitting out a new outer loop
Parallel Loop at depth 1 containing: %while.cond.outer<header>,%lor.end<exiting>,%while.body<latch>,%while.body.thread,%while.cond
    Parallel Loop at depth 2 containing: %while.cond<header><exiting>,%while.body.thread<latch>
; ModuleID = 'bbi-73295.ll'
source_filename = "bbi-73295.ll"

define i16 @foo() {
entry:
  br label %while.cond.outer

while.cond.outer:                                 ; preds = %while.body, %entry
  %i.0.ph = phi i16 [ %inc, %while.body ], [ 0, %entry ]
  %j.0.ph = phi i16 [ %spec.select7, %while.body ], [ 0, %entry ]
  br label %while.cond

while.cond:                                       ; preds = %while.cond.outer, %while.body.thread
  %i.0 = phi i16 [ %inc4, %while.body.thread ], [ %i.0.ph, %while.cond.outer ]
  %cmp = icmp slt i16 %i.0, 10
  br i1 %cmp, label %while.body.thread, label %lor.end

while.body.thread:                                ; preds = %while.cond
  %inc4 = add nsw i16 %i.0, 1
  br label %while.cond, !llvm.loop !5

lor.end:                                          ; preds = %while.cond
  %cmp1.not = icmp eq i16 %j.0.ph, 5
  br i1 %cmp1.not, label %while.end, label %while.body

while.body:                                       ; preds = %lor.end
  %inc = add nuw nsw i16 %i.0, 1
  %cmp2 = icmp eq i16 %inc, 12
  %spec.select7 = select i1 %cmp2, i16 5, i16 %j.0.ph
  br label %while.cond.outer, !llvm.loop !5

while.end:                                        ; preds = %lor.end
  ret i16 %i.0
}

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 7, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
!2 = !{i32 1, !"wchar_size", i32 1}
!3 = !{i32 7, !"frame-pointer", i32 2}
!4 = !{!"clang version 16.0.0.prerel"}
!5 = distinct !{!5, !6}
!6 = !{!"llvm.loop.usefulinfo"}
```
So instead of having one loop with two latches, after LoopSimplifyCFG we have two nested loops with one latch each.
Since these are two different loops, then I really think that they should have different loop ID:s.
Also the "usefulinfo" metadata should be dropped, at least for the inner loop, but not sure if we can guarantee that it is valid for the outer loop either.

(We originally found this for our out-of-tree target where the loop-metadata specified made sense for the original program, but it did not do it for the inner loop after loop-simplify's rewrite to nested loops.)

**Comment by Narutoworld** [comment]
Hi, I am interested in this issue and want to check if some body have already worked on it.

**Comment by mikaelholmen** [comment]
@Narutoworld I'm not aware of anyone working on this.

**Comment by Narutoworld** [comment]
@mikaelholmen Do you know what is the semantic of `llvm.loop.usefulinfo` ?
IIUC, with a bug fix, the newly created inner loop should have different loop ID and does not have `llvm.loop.usefulinfo` attribute.

**Comment by mikaelholmen** [comment]
Originally the metadata was "minitercount" which we've introduced in our downstream compiler. It describes a known minimum iteration count for the loop, specified by the user in a pragma.

But I think the problem is not specific for our "minitercount" metadata but it is strange that the new inner loop get the same loop ID.

**Comment by Narutoworld** [comment]
Hi @mikaelholmen

**Comment by Narutoworld** [comment]
Based on the discusstion we have over here [patch](https://reviews.llvm.org/D136102).
This is not a bug, we can close this issue.

**Comment by mikaelholmen** [comment]
@Narutoworld : Thank you for sorting this out.
