### ISSUE TITLE
[mlir][math] Polynomial Approx tests are broken

### ISSUE THREAD

**Issue by Mogball** [llvm/llvm-project#57613]
Many of `math` dialect operations now have folders, but that means the tests in [math-polynomial-approx.mlir](https://github.com/llvm/llvm-project/blob/main/mlir/test/mlir-cpu-runner/math-polynomial-approx.mlir) are broken because they are not testing the numerical approximation of the ops but instead the folders.

The test needs to be rewritten to pass in the constants via function arguments so that the ops don't fold.

**Comment by jacquesguan** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/d67603a654880879cb42340e52195e52ad694b35.

**Comment by Mogball** [comment]
Thanks!
