### ISSUE TITLE
[ELF] ld.lld not honoring --no-warn-mismatch

### ISSUE THREAD

**Issue by Nimrag2000** [llvm/llvm-project#57623]
Since [D125074](https://reviews.llvm.org/D125074) using NOLOAD for .bss sections throws the 'section type mismatch' warning because the linker incorrectly assumes that .bss sections should be assigned the SHT_PROGBIT attribute.  We cannot suppress the warning because --no-warn-mismatch is quietly ignored.  Can we either revert this change or add support for the --no-warn-mismatch?

Embedded systems have relied on adding .bss sections to NOLOAD output sections for years.  The 15.0.0 release broke this, and we can not take the 15.0.0 release.  Our products require zero warnings.

**Comment by MaskRay** [comment]
`--no-warn-mismatch` is for different ELF classes, not for different section types for input sections. `--no-warn-mismatch` isn't useful, does not significant uses in the wild, cannot be realistically supported, so it's just silently ignored.

You likely have an incorrect linker script that inserts some SHT_PROGBITS input sections to intended-to-be-SHT_NOBITS `.bss`, and you need to fix that.
