### ISSUE TITLE
The expression of `static_assert` is not an immediate function context

### ISSUE THREAD

**Issue by JohelEGP** [llvm/llvm-project#57627]
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106485#c2.

See https://godbolt.org/z/4GMxo13vv.
```C++
#include <string>
consteval auto s() { return std::string(); }
static_assert(s().empty()); // Only Clang accepts.
// static_assert([]() consteval { return s().empty(); }()); // All accept.
// static_assert([]() { return s().empty(); }()); // All reject.
```

I think `static_assert(s().empty());` should also be rejected by Clang.

**Comment by shafik** [comment]
If we look at:

```cpp
constexpr auto y = s().empty();
```

it feels like clang is not being consistent. Either `s().empty()` is a constant expression or not.

**Comment by AaronBallman** [comment]
It seems MSVC also accepts what Clang accepts, while ICC rejects the same way GCC does.

**Comment by cor3ntin** [comment]
All compilers now accept all 4 static_asserts https://godbolt.org/z/naeoWYfWq
Clang was changed in 17.0
