### ISSUE TITLE
SPARC lacks support for over-aligned dynamic alloca

### ISSUE THREAD

**Issue by rorth** [llvm/llvm-project#57626]
The SPARC backend lacks support for over-aligned dynamic alloca.  So far, I've encountered the issue in the testsuite ([D133493](https://reviews.llvm.org/D133493):
```console
FAILED: MultiSource/UnitTests/C++11/frame_layout/CMakeFiles/frame_layout.dir/frame_layout.cpp.o
[...]
fatal error: error in backend: Function "_Z10test_frameILj4096ELb1ELj2048ELb0ELb0EJEEvDpT4_jPKcP13trace_elementd": over-aligned dynamic alloca not supported.
void test_frame<4096u, true, 2048u, false, false>(, unsigned int, char const*, trace_element*, double)
```
Additionally, it breaks asan support with several instances of the same issue:
```console
      4 fatal error: error in backend: Function "_Z21MemSetOOBTestTemplateIcEvj": over-aligned dynamic alloca not supported.
      3 fatal error: error in backend: Function "_Z21StrLenOOBTestTemplatePcjN12_GLOBAL__N_17OOBKindE": over-aligned dynamic alloca not supported.
      4 fatal error: error in backend: Function "_Z24asan_write_sized_alignedPhj": over-aligned dynamic alloca not supported.
      4 fatal error: error in backend: Function "_ZN48AddressSanitizerInternalInterface_SetShadow_Test8TestBodyEv": over-aligned dynamic alloca not supported.
      4 fatal error: error in backend: Function "_ZN52AddressSanitizer_HasFeatureAddressSanitizerTest_Test8TestBodyEv": over-aligned dynamic alloca not supported.
      4 fatal error: error in backend: Function "_ZN56AddressSanitizerInterface_GetEstimatedAllocatedSize_Test8TestBodyEv": over-aligned dynamic alloca not supported.
      4 fatal error: error in backend: Function "_ZN7testing8internal16BoolFromGTestEnvEPKcb": over-aligned dynamic alloca not supported.
      3 fatal error: error in backend: Function "main": over-aligned dynamic alloca not supported.
```
which caused be to disable asan completely.

This puts `clang` at a considerable advantage to `gcc` which handles both just fine.

**Comment by rorth** [comment]
The commit hash is for the `llvm-test-suite` repo, not `llvm-project`.  How would I request a backport there?  I don't believe a fork is necessary here.

**Comment by tru** [comment]
You can just manually cherry-pick it over to the `release/15.x` branch for the test-suite.

**Comment by rorth** [comment]
... which would have required approval first ;-)  Alternatively, I've now created a fork before seeing your message:

/branch rorth/llvm-test-suite/issue57626

**Comment by rorth** [comment]
Seems I shouldn't go near the keyboard during weekends, especially with git being as unintuitive as ever and me being ignorant of git ;-(  Here's a new branch based on `release/15.x` with **only** my patch:

/branch rorth/llvm-test-suite/issue57626-15.x

**Comment by tru** [comment]
Seems like you still didn't get it correct @rorth - try going to your branch and run `git reset --hard origin/release/15.x` then do `git cherry-pick <sha>`

**Comment by tru** [comment]
Ah but wait - the test-suite doesn't work with the bot at all it only works with the llvm-project repo. You need to push that fix manually instead.

**Comment by rorth** [comment]
Ah, I see.  Done now, thanks.
