### ISSUE TITLE
[mlir][spirv] Plumb through support for int8 dot product

### ISSUE THREAD

**Issue by antiagainst** [llvm/llvm-project#57631]
[SPV_KHR_integer_dot_product](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_integer_dot_product.html) allows performing int8 dot product in an efficient way. It's important for int8 quantized models. To plumb support for it, we need to

- [x] Define the ops in the extension
- [ ] Add patterns with higher benefits to lower to these special ops

**Comment by kuhar** [comment]
Ops defined in:
- https://reviews.llvm.org/D139063
- https://reviews.llvm.org/D139242
- https://reviews.llvm.org/D139243
- https://reviews.llvm.org/D139243
