### ISSUE TITLE
Backport [libc++][format] Updates feature-test macros.

### ISSUE THREAD

**Issue by mordante** [llvm/llvm-project#57633]
@ldionne tried to create a backport request but noticed a merge conflict. So I created the request instead.

/branch mordante/llvm-project/backport-D133271

**Comment by tru** [comment]
/branch mordante/llvm-project/backport-D133271

I think commands have to come in comments.

**Comment by mordante** [comment]
> /branch mordante/llvm-project/backport-D133271
> 
> I think commands have to come in comments.

Thanks for the assistance.
