### ISSUE TITLE
clang-cl does not accept `-fsave-optimization-record`

### ISSUE THREAD

**Issue by OfekShilon** [llvm/llvm-project#57649]
We wish to inspect optimization remarks generated by clang optimization passes, from within Visual Studio. This currently can't be done:
```console
clang-cl : warning : unknown argument ignored in clang-cl: '-fsave-optimization-record' [-Wunknown-argument]
```

**Comment by Maetveis** [comment]
You can use the [/clang:](https://clang.llvm.org/docs/UsersManual.html#the-clang-option) option to pass options unknown to the cl driver.

> When clang-cl is run with a set of /clang:<arg> options, it will gather all of the <arg> arguments and process them as if they were passed to the clang driver. This mechanism allows you to pass flags that are not exposed in the clang-cl options or flags that have a different meaning when passed to the clang driver. Regardless of where they appear in the command line, the /clang: arguments are treated as if they were passed at the end of the clang-cl command line.

You can use it like this
`clang-cl /clang:-fsave-optimization-record <rest-of-options>`

**Comment by OfekShilon** [comment]
@Maetveis  Thanks!   For some reason I wasn't able to get *.opt.yaml files without supplying `-foptimization-record-file=<file>` too.  Is that behavior intentional?  Anyway that's good enough for me and I'm closing the issue.
