### ISSUE TITLE
[M68k] Crash when compiling with fast register allocator

### ISSUE THREAD

**Issue by mshockwave** [llvm/llvm-project#57660]
The following snippet:
```llvm
; Function Attrs: noinline nounwind optnone
define dso_local void @foo() {
entry:
  br label %do.body

do.body:                                          ; preds = %land.end, %entry
  %cmp5 = icmp eq i32 0, 4
  br label %land.end

land.end:                                         ; preds = %do.body
  br i1 %cmp5, label %do.body, label %do.end

do.end:                                           ; preds = %land.end
  ret void
}
```
crashed with the following command:
```shell
llc -mtriple=m68k-linux-gnu --regalloc=fast input.ll
```

It was caused by an assertion:
```console
llc: llvm-project/llvm/lib/Target/M68k/M68kInstrInfo.cpp:750: virtual void llvm::M68kInstrInfo::storeRegToStackSlot(llvm::MachineBasicBlock &, MachineBasicBlock::iterator, llvm::Register, bool, int, const llvm::TargetRegisterClass *, const llvm::TargetRegisterInfo *) const: Assertion `MF.getFrameInfo().getObjectSize(FrameIndex) == 4 && "Stack slot too small for store"' failed.
```
I think this is relatively easy to fix. Putting `good first issue` label here.

**Comment by 0x59616e** [comment]
Is that assertion correct ? Should the size of local stack slot always be 4 bytes no matter what the data type is ?

**Comment by 0x59616e** [comment]
The following this snippet:
```c
void foo(char *ptr, char v) {
  char tmp = 0;
  do {
    tmp += --v;
  } while(v);
  *ptr = v;
}
```
comes with the following assembly generated by gcc:
```asm
foo:
        subq.l #8,%sp
        move.l 16(%sp),%d0
        move.b %d0,%d0
        move.b %d0,2(%sp)
        clr.b 7(%sp)
.L2:
        move.b 2(%sp),%d0
        subq.b #1,%d0
        move.b %d0,2(%sp)
        move.b 2(%sp),%d0
        move.b %d0,%d1
        move.b 7(%sp),%d0
        add.b %d1,%d0
        move.b %d0,7(%sp)
        tst.b 2(%sp)
        jne .L2
        move.l 12(%sp),%a0
        move.b 2(%sp),(%a0)
        nop
        addq.l #8,%sp
        rts
```

It seems that gcc assume 4 bytes local stack slot.

**Comment by mshockwave** [comment]
> It seems that gcc assumes 4 bytes local stack slot.

I'm not sure how did you draw this conclusion, but the size of a "stack slot" is dictated by the alignment of the stack, or more specifically, the alignment of the stack pointer. In GCC ABI, this will be a word (16 bits).

Back to the topic of spill size, I think the current spill size for each register is correct (same as the data type size). IMO, as long as the load and store to a spill slot conforms to the data alignment while stack pointer maintains stack alignment, we should be fine. In other words, I think we should fix the assertion instead. To check the object size against the spill size of the given register class.

**Comment by 0x59616e** [comment]
My  (incorrect) conclusion is drawn from the fact that that snippet uses two stack slot (at 2(%sp) and 7(%sp) respectively). And at the entry of this function, it reserves 8 bytes, so I guess the size of the stack slot is 4 bytes. 

But I'm unsure whether this claim is correct or not, since I cannot find any word regarding this in the document. All is just my guess.

I will fix that assertion instead.
