### ISSUE TITLE
clang-15 compile time regression: 30 seconds -> over 40 minutes

### ISSUE THREAD

**Issue by vogelsgesang** [llvm/llvm-project#57664]
During upgrading an internal code base to clang-15, I noticed to our "VM" (essentially a computed-goto based interpreter loop) is taking over 40 minutes to compile in clang-15 (I do not know the exact time, I ran out of patience). With clang-14 it used to take between 30 and 60 seconds.

While I cannot share the original source code, https://godbolt.org/z/4chMrr99f contains a simplified repro.

Looking at the `perf record` results for the first 5 minutes (I ran out of patience to record a longer time slice), all time is spent in a single function:

```
  99.84%  clang    libLLVM-15.so      [.] llvm::GenericCycleInfoCompute<llvm::GenericSSAContext<llvm::MachineFunction> >::run
```

In particular in a single loop consisting of only 4 instructions

```
  0.00 │ 440:┌─→mov    %rax,%r15
 88.51 │     │  mov    (%rax),%rax
  0.03 │     ├──test   %rax,%rax
  8.72 │     └──jne    440
  ```

Not sure what this loop does on a logical level, but it seems like it's following a linked list until it finds the end of that list marked by a nullptr.

**Comment by vogelsgesang** [comment]
@chenzheng1030 FYI, I think this regression was caused by https://reviews.llvm.org/D123995

**Comment by chenzheng1030** [comment]
Thanks. It would be helpful if you can share more info, for example the loop structure which includes the simple loop in the description or is the simple loop the out-most loop?

**Comment by vogelsgesang** [comment]
Not sure if I understand your question.
https://godbolt.org/z/4chMrr99f by itself already reproduces the issue for me. Are you able to reproduce this, i.e. does it also result in a huge compile time for you?

Note how the computed gotos without any additional "for"/"while" loops already form loops/cycles, in the sense that after leaving a basicblock, the same basic block can be entered again. Just as in this code snippet, our internal source code does not have additional "while"/"for" loops around this goto-structure

**Comment by vogelsgesang** [comment]
Ah, now I understood your question. You were asking whether there was an outer loop visible in the perf profile. Yes, there is:

<details>
   <summary>Outer loop in perf trace (click to expand)</summary>
   
```
       │ 343:   mov    0x8(%rbx),%rax
       │        mov    %edx,%ecx
       │        mov    %r15,(%rax,%rcx,8)
       │        incl   0x10(%rbx)
  0.12 │ 350:┌─→mov    0x88(%rsp),%ebx
  0.01 │     │  mov    0x58(%rsp),%r12
  0.02 │ 35c:│  test   %ebx,%ebx
       │     │↓ je     10f0
  0.02 │ 364:│  mov    0x80(%rsp),%rax
  0.00 │     │  mov    %ebx,%ecx
  0.34 │     │  mov    -0x8(%rax,%rcx,8),%rax
  0.00 │     │  dec    %ebx
       │     │  mov    %ebx,0x88(%rsp)
  0.05 │     │  mov    %rax,0x68(%rsp)
  0.00 │     │  cmp    0x78(%rsp),%rax
       │     │↑ je     35c
  0.01 │     │  mov    (%r14),%rdi
  0.08 │     │  mov    0x10(%rdi),%rcx
  0.08 │     │  mov    0x20(%rdi),%ebx
  0.01 │     │  test   %rbx,%rbx
       │     │↓ je     410
       │     │  mov    %eax,%edx
  0.00 │     │  shr    $0x4,%edx
  0.01 │     │  mov    %eax,%esi
  0.01 │     │  shr    $0x9,%esi
  0.00 │     │  xor    %edx,%esi
       │     │  lea    -0x1(%rbx),%r9d
  0.02 │     │  and    %r9d,%esi
  0.01 │     │  mov    %rsi,%rdx
  0.00 │     │  shl    $0x4,%rdx
  0.42 │     │  mov    (%rcx,%rdx,1),%rbp
  0.02 │     │  cmp    %rax,%rbp
  0.00 │     │↓ jne    3d5
       │     │  cmp    %ebx,%esi
  0.02 │     │↓ jne    3cd
       │     │  mov    0x70(%rsp),%r15
       │     │  mov    %r15,0x60(%rsp)
       │     │↓ jmp    53d
  0.00 │ 3cd:│  add    %rdx,%rcx
       │     │  mov    %rcx,%rdx
  0.02 │     │↓ jmp    42d
  0.07 │ 3d5:│  mov    $0x1,%r8d
  0.01 │ 3db:│  cmp    $0xfffffffffffff000,%rbp
       │     │↓ je     410
  0.00 │     │  add    %r8d,%esi
  0.00 │     │  inc    %r8d
  0.01 │     │  and    %r9d,%esi
  0.01 │     │  mov    %rsi,%rbp
  0.00 │     │  shl    $0x4,%rbp
  0.00 │     │  lea    (%rcx,%rbp,1),%rdx
  0.03 │     │  mov    (%rcx,%rbp,1),%rbp
  0.00 │     │  cmp    %rax,%rbp
  0.00 │     │↓ je     41a
  0.02 │     │↑ jmp    3db
       │     │  data16 data16 data16 cs nopw 0x0(%rax,%rax,1)
       │ 410:│  mov    %rbx,%rdx
       │     │  shl    $0x4,%rdx
       │     │  add    %rcx,%rdx
  0.02 │ 41a:│  mov    %rbx,%rsi
  0.01 │     │  shl    $0x4,%rsi
  0.00 │     │  add    %rcx,%rsi
  0.01 │     │  cmp    %rsi,%rdx
       │     │↓ je     52a
  0.03 │ 42d:│  mov    0x8(%rdx),%rax
  0.00 │     │  data16 data16 data16 data16 data16 cs nopw 0x0(%rax,%rax,1)
  0.00 │ 440:│  mov    %rax,%r15
 88.51 │     │  mov    (%rax),%rax
  0.03 │     │  test   %rax,%rax
  8.72 │     │↑ jne    440
  0.69 │     │  mov    0x70(%rsp),%r13
  0.00 │     ├──cmp    %r13,%r15
  0.02 │     └──je     350
       │        mov    0x28(%rdi),%r12
       │        mov    0x30(%rdi),%rax
       │        cmp    %rax,%r12
       │      ↓ je     482
       │        cs     nopw 0x0(%rax,%rax,1)
```
</details>

However, the clang-15 build I profiled does not have debug info, so I don't know which lines in clang's source code those instructions map to. Probably, it's simpler if you reproduce this locally using the godbolt-repro

**Comment by chenzheng1030** [comment]
Thanks. Start to look at this issue.

**Comment by chenzheng1030** [comment]
`-mllvm -disable-early-taildup` can workaround this issue.

Early tail duplication causes the cfg to become quite complicated and MachineCycle analysis can not analyze the cycle info efficiently.

**Comment by chenzheng1030** [comment]
https://reviews.llvm.org/D134019 is posted

**Comment by vogelsgesang** [comment]
@tru FYI, I think as soon as this fix lands, it might be a good idea to backport it to 15.0.1.
From my rough understanding of the patch, I think it should be low-risk. Do you agree, @chenzheng1030?

**Comment by chenzheng1030** [comment]
> From my rough understanding of the patch, I think it should be low-risk. Do you agree, @chenzheng1030?

Yes, I think so. The patch is with no functionality change

**Comment by nikic** [comment]
@tru I think this is because the milestone is missing the `release/15.x` branch association, but I don't see an interface option to add it.

**Comment by nikic** [comment]
/cherry-pick c941d925b0e47ec166364178edac75cf1cb1ee1a

I thought this was a GitHub feature, but I think it's just part of the milestone description ... let's give it another try.

**Comment by tru** [comment]
> /cherry-pick [c941d92](https://github.com/llvm/llvm-project/commit/c941d925b0e47ec166364178edac75cf1cb1ee1a)
> 
> I thought this was a GitHub feature, but I think it's just part of the milestone description ... let's give it another try.

Ah yes - I always forget to add that branch specifier. I am thinking maybe we could change it to parse the name of the milestone instead. But then we have to remember to name the milestones correctly :)

**Comment by tru** [comment]
Thanks for adding that btw

**Comment by dileks** [comment]
Looks that backport OK to you?

[MachineCycle-NFC-add-a-cache-for-block-and-its-top-level-cycle-backported-to-15-0-1.patch.txt](https://github.com/llvm/llvm-project/files/9621336/MachineCycle-NFC-add-a-cache-for-block-and-its-top-level-cycle-backported-to-15-0-1.patch.txt)

**Comment by chenzheng1030** [comment]
Thanks, the backport LGTM.

**Comment by dileks** [comment]
@chenzheng1030 

Thanks for the feedback.

I wanted to test this on x86-64 arch and normally run tests for clang and lld.

Can you give me a hand on how to check?

Normally, there should exist some llvm tests?

No match:
```
$ git status -s
 M llvm/include/llvm/ADT/GenericCycleImpl.h
 M llvm/include/llvm/ADT/GenericCycleInfo.h
$ grep 'llvm/ADT' llvm/test/
$ grep 'GenericCycle' llvm/test
```

**Comment by chenzheng1030** [comment]
This is a patch without functionality change to the compiler, it adds a cache to improve the compiling time.

You can check the compile time for the case in https://godbolt.org/z/4chMrr99f. There should be some improvement.

Or if you needs compiler LIT tests, is it possible to run the tests added in first CycleInfo patch https://reviews.llvm.org/D112696, like `llvm/test/Analysis/CycleInfo/basic.ll` and `llvm/test/CodeGen/X86/cycle-info.mir`

**Comment by dileks** [comment]
Thanks for the explanation.

Attached v2 of my test-script.
[run_tests-pr57664-v2.sh.txt](https://github.com/llvm/llvm-project/files/9624978/run_tests-pr57664-v2.sh.txt)

**Comment by dileks** [comment]
@chenzheng1030 

Improve the build-time is always and much appreciated.

I use LLVM to compile my Linux-kernels.

How to test with `perf`?

I tried:
```shell
echo "linux-perf: Adjust limited access to performance monitoring and observability operations"
echo 0 | sudo tee /proc/sys/kernel/kptr_restrict /proc/sys/kernel/perf_event_paranoid

# Debian LLVM-15
perf stat --all-cpus --repeat=1 /usr/bin/clang-15 -O2 tests/test-pr57664_godbolt-z-4chMrr99f.cpp

# Selfmade LLVM-15 + PR57664
perf stat --all-cpus --repeat=1 /opt/llvm/bin/clang-15 -O2 tests/test-pr57664_godbolt-z-4chMrr99f.cpp

echo 1 | sudo tee /proc/sys/kernel/kptr_restrict /proc/sys/kernel/perf_event_paranoid
echo "linux-perf: Reset limited access to performance monitoring and observability operations"
```

**Comment by chenzheng1030** [comment]
When I verified the compile time improvement, I simply used `time` command.

**Comment by tru** [comment]
Can someone push the branch with this based on release/15.x if we want to backport it into 15.x?

**Comment by dileks** [comment]
I rebuild a Linux v5.19.10 with LLVM toolchain v15.0.1+ PR57664 (fixed) on x86-64 in the same build-environment.

There is no build-time improvement (and no regression) for me.

**Comment by chenzheng1030** [comment]
> Can someone push the branch with this based on release/15.x if we want to backport it into 15.x?

Not sure if above command works, I cherry-picked the commit to https://github.com/chenzheng1030/llvm-project/tree/backport_D134019

**Comment by dileks** [comment]
Looks like this did not work.

**Comment by chenzheng1030** [comment]
Do you mean the fix can not improve the compile time for case https://godbolt.org/z/4chMrr99f ? I did see big improvement on PPC64 Linux.

**Comment by dileks** [comment]
@chenzheng1030

I applied the fix and build a new LLVM toolchain.

When building a full Linux v5.19.10 kernel from scratch  - on bare metal NOT VM (IIRC the caller of this PR tested on an unspecified ppc64-VM) - I do not see any benefits in build-time on Debian/unstable x86-64 (aka AMD64).

**Comment by chenzheng1030** [comment]
OK. This is some kind of expected. The fix https://reviews.llvm.org/D134019  is targeted for case https://godbolt.org/z/4chMrr99f . Patch https://reviews.llvm.org/D134019 impacts compile time for sources which have complicated cycle/loop structures. And for "normal" case, machinecycle pass has limited impact for compile time. See https://reviews.llvm.org/D123995#3459279

**Comment by dileks** [comment]
OK.

I run the godbolt test-case and this time I was patient enough.

```
[ Selfmade LLVM-15 with fix applied ]

$ /usr/bin/perf stat --all-cpus --repeat=1 /opt/llvm/bin/clang-15 -O2 tests/test-pr57664_godbolt-z-4chMrr99f.cpp
/usr/bin/ld: /lib/x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x17): undefined reference to `main'
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)

 Performance counter stats for 'system wide':

        115.492,14 msec cpu-clock                 #    4,000 CPUs utilized          
            10.917      context-switches          #   94,526 /sec                   
               259      cpu-migrations            #    2,243 /sec                   
            66.818      page-faults               #  578,550 /sec                   
    66.713.920.046      cycles                    #    0,578 GHz                    
    92.630.241.341      stalled-cycles-frontend   #  138,85% frontend cycles idle   
    77.243.296.481      stalled-cycles-backend    #  115,78% backend cycles idle    
   148.579.924.707      instructions              #    2,23  insn per cycle         
                                                  #    0,62  stalled cycles per insn
    35.241.671.060      branches                  #  305,143 M/sec                  
        78.136.051      branch-misses             #    0,22% of all branches        

      28,876629696 seconds time elapsed

[ Debian LLVM-15 ]

$ /usr/bin/perf stat --all-cpus --repeat=1 /usr/bin/clang-15 -O2 tests/test-pr57664_godbolt-z-4chMrr99f.cpp
/usr/bin/ld: /lib/x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x17): undefined reference to `main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

 Performance counter stats for 'system wide':

      2.465.459,35 msec cpu-clock                 #    4,000 CPUs utilized          
           241.801      context-switches          #   98,075 /sec                   
             6.445      cpu-migrations            #    2,614 /sec                   
            90.224      page-faults               #   36,595 /sec                   
 1.415.292.137.069      cycles                    #    0,574 GHz                    
 2.644.407.854.778      stalled-cycles-frontend   #  186,85% frontend cycles idle   
 2.522.285.141.408      stalled-cycles-backend    #  178,22% backend cycles idle    
   658.289.160.766      instructions              #    0,47  insn per cycle         
                                                  #    4,02  stalled cycles per insn
   162.416.217.808      branches                  #   65,877 M/sec                  
       614.734.739      branch-misses             #    0,38% of all branches        

     616,378294645 seconds time elapsed

```

**Comment by dileks** [comment]
Factor 20-21 is fair enough to commit the backport-fix :-).
