### ISSUE TITLE
Clangd cannot find function implementation in C++20 module implementation unit

### ISSUE THREAD

**Issue by vagran** [llvm/llvm-project#57674]
File `a.cppm`:
```cpp
export module A;

export void
TestFunc(); // <<< Finding implementation from here
```

File `a.cpp`:
```cpp
module A;

void
TestFunc()
{
}
```
Placing cursor on `TestFunc()` declaration in cppm and trying to find its implementation in VSCode with `clangd` connected gives no result.

`compile_commands.json`:
```json
[
{
"directory":"/home/artyom/projects/asio-awaitable-module-problem-demo/build",
"file":"../a.cppm",
"output":"a.pcm",
"command":"/opt/clang-latest/bin/clang++ -c -std=c++20 -stdlib=libc++ -Wall -Werror -g -O0 -fmodules -fimplicit-modules -fmodules-cache-path=modules-cache -DMODULES -fretain-comments-from-system-headers --precompile -x c++-module ../a.cppm -o a.pcm -Xclang -emit-module-interface"
}
,
{
"directory":"/home/artyom/projects/asio-awaitable-module-problem-demo/build",
"file":"../a.cpp",
"output":"a.o",
"command":"/opt/clang-latest/bin/clang++ -c -std=c++20 -stdlib=libc++ -Wall -Werror -g -O0 -fmodules -fimplicit-modules -fmodules-cache-path=modules-cache -DMODULES -fretain-comments-from-system-headers -fmodule-file=a.pcm ../a.cpp -o a.o"
}
]

```

Clangd log:
```
V[22:45:33.175] <<< {"id":8,"jsonrpc":"2.0","method":"textDocument/implementation","params":{"position":{"character":4,"line":3},"textDocument":{"uri":"file:///home/artyom/projects/asio-awaitable-module-problem-demo/a.cppm"}}}

I[22:45:33.175] <-- textDocument/implementation(8)
V[22:45:33.175] ASTWorker running Implementations on version 1 of /home/artyom/projects/asio-awaitable-module-problem-demo/a.cppm
I[22:45:33.175] --> reply:textDocument/implementation(8) 0 ms
V[22:45:33.175] >>> {"id":8,"jsonrpc":"2.0","result":[]}
```

Full log [attached](https://github.com/llvm/llvm-project/files/9541324/clangd.log).

Repository with sample project available [here](https://github.com/vagran/asio-awaitable-modules-problem-demo/tree/clangd-problems).

```
$ /opt/clang-latest/bin/clangd --version
clangd version 16.0.0 (https://github.com/llvm/llvm-project.git ee761374f797a47919ec8f9f49f9b8b1b20573e8)
Features: linux
Platform: x86_64-unknown-linux-gnu
```

**Comment by vagran** [comment]
Just noticed this line in the log:
```
E[22:45:27.705] Failed to scan baseline of /home/artyom/projects/asio-awaitable-module-problem-demo/a.cpp: failed BeginSourceFile
```
I already [reported](https://github.com/clangd/clangd/issues/1021) half-year ago about that.

Also noticed that finding declaration from implementation works fine. Placing cursor in `.cpp` file nad jumping to declaration in `.cppm`. So some index for this file is built.

**Comment by sam-mccall** [comment]
Sorry, clangd doesn't have any modules support.
Clang does, and clangd allows flags to be passed through to clang so some things may work or appear to work. But it would need significant design/implementation effort to get it into a usable state.

https://github.com/clangd/clangd/issues/1293 is the tracking bug for this, but nobody is currently working on it :-(

**Comment by ChuanqiXu9** [comment]
@vagran BTW, your implementation asio_impl module is not good. Since C++20 Modules doesn't use the clang's module map now. You can the related things https://clang.llvm.org/docs/StandardCPlusPlusModules.html.
