### ISSUE TITLE
[flang-new] library path must be manually specified

### ISSUE THREAD

**Issue by ggouaillardet** [llvm/llvm-project#57670]
I downloaded the `llvm-project-15.0.0.src.tar.xz` tarball, and built it (on aarch64 - RHEL 8.5) with
```shell
cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DLLVM_ENABLE_PROJECTS='clang;flang;lld;openmp' -DLLVM_ENABLE_RUNTIMES='libunwind;libcxx;libcxxabi' -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/llvm-15.0.0 ../llvm
```

linking a trivial Fortran program fails because `flang-new` does not look for the Fortran runtime into the `<prefix>/lib` directory:

```console
$ cat foo.f90 
program foo
end
$ flang-new foo.f90
/opt/binutils-2.38/bin/ld: cannot find -lFortran_main: No such file or directory
/opt/binutils-2.38/bin/ld: cannot find -lFortranRuntime: No such file or directory
/opt/binutils-2.38/bin/ld: cannot find -lFortranDecimal: No such file or directory
flang-new: error: linker command failed with exit code 1 (use -v to see invocation)
```

A workaround is to manually pass `-L<prefix>/lib` to `flang-new`:
```console
$ flang-new foo.f90 -L/opt/llvm-15.0.0/lib
$
```
(or to add `/opt/llvm-15.0.0/lib` to the `LIBRARY_PATH` environment variable)

**Comment by licy183** [comment]
I have the same problem. You could try to pass `-flang-experimental-exec` or rebuilt clang-driver with the the following patch.

```patch
--- a/clang/lib/Driver/ToolChains/CommonArgs.cpp
+++ b/clang/lib/Driver/ToolChains/CommonArgs.cpp
@@ -763,8 +763,8 @@
   // NOTE: Generating executables by Flang is considered an "experimental"
   // feature and hence this is guarded with a command line option.
   // TODO: Make this work unconditionally once Flang is mature enough.
-  if (!Args.hasArg(options::OPT_flang_experimental_exec))
-    return;
+  // if (!Args.hasArg(options::OPT_flang_experimental_exec))
+  //   return;
 
   // Default to the <driver-path>/../lib directory. This works fine on the
   // platforms that we have tested so far. We will probably have to re-fine
```

**Comment by banach-space** [comment]
As @licy183 pointed out, you need to use `-flang-experimental-exec`:
```
bin/flang-new --help-hidden | grep exec
  -flang-experimental-exec
                          Enable support for generating executables (experimental)
```

For context as to why this flag is needed, please see the discussion for https://reviews.llvm.org/D122008. This was also broadly discussed in our community calls and I tried my best to capture all of that on Phabricator.

I hope that this helps,
-Andrzej

**Comment by ggouaillardet** [comment]
Thanks @licy183 and @banach-space for the explanation!

Per my comment in https://github.com/llvm/llvm-project/issues/57602#issuecomment-1242751655, I also noted the Fortran runtime might invokes subroutines defined in `libpgmath`, but this library is not part of `flang` from the `15.0.0` official tarball, and I did not see any way to have it used automatically. The doc refers the `LIBPGMATH_DIR` macro but it looks like it is out of sync with the sources. Please let me know if you would like me to open a separate issue for that.

Since the initial issue has been addressed, I will now close this ticket.

**Comment by kiranchandramohan** [comment]
There is dependency due to Fortran complex math intrinsics and precision issues. @DavidTruby is working on using the MLIR complex dialect to support Fortran complex math intrinsics. Handling the precision issues might involve disabling some transformations based on the precision required in MLIR math and complex dialects.

**Comment by vzakhari** [comment]
> I think that some folks are already working towards making LLVM Flang work without `libpgmath`. Perhaps @vzakhari ?

I have been working on this, but reduced effort in this area recently.  In any case, if we want to keep `libpgmath` dependency in some configurations it should be introduced late, not during lowering to FIR.  I would rather use as much as possible FIR/MLIR operations that can represent Fortran math intrinsics and then convert them to whatever library calls are desired.
