### ISSUE TITLE
[AArch64][Windows] explicit 'inreg' function argument attribute leads to wrong code generation

### ISSUE THREAD

**Issue by amitin** [llvm/llvm-project#57684]
A function with explicit 'inreg' function argument attribute causes incorrect code generation.
For example, `define fastcc %struct.Foo* @foobar(%struct.Bar* inreg %0, %struct.Foo* inreg %1)`
(`ccc` calling conv affected as well).
Affected is aarch64-pc-windows-msvc target, for aarch64-linux-gnu it generates the code correctly.
It seems the instructions get deleted by TailMergeBlocks() of the BranchFolder pass.

A self-contained sample reproducing this behaviour is attached. 
[aarch64-windows-msvc.zip](https://github.com/llvm/llvm-project/files/9543407/aarch64-windows-msvc.zip)

**Comment by DavidSpickett** [comment]
Thanks for the report, I put it into godbolt: https://godbolt.org/z/MPTjnbon6 . Certainly looks to be wrong at first glance, given the incorrect return type.

@omjavaid Might be interested, or know who is interested in fixing Windows on Arm codegen issues.

**Comment by amitin** [comment]
@DavidSpickett,
Thank you. We have another similar issue here, using our own cc causes lots of unneeded reg spills/loads in prologue/epilogue for aarch64-windows target and works fine for aarch64-linux. So I'll keep an eye on this one while fixing our internal issue. I'll create a pull request if I spot something.

**Comment by bcl5980** [comment]
Simplify the case:
https://godbolt.org/z/P7M6cveeG
