### ISSUE TITLE
General question about variable type of operand in add operation

### ISSUE THREAD

**Issue by Y-chav** [llvm/llvm-project#57699]
Hi,

I want to ask a general question about **add** operation in executable code. We know that type info is lost in executable code, but is there any any assumptions that pointer variable only can be placed at the left-hand side of an **add** instruction in executable code? 

<img width="202" alt="image" src="https://user-images.githubusercontent.com/44321769/189696261-60559d0e-a0a8-440d-ac57-ef163ce14c54.png">

For example, the above instruction contains an add operation **[rax+rcx]**, and at here the left-hand side rax register is a pointer and right-hand side rcx register is a scalar. Does this assumption always hold for all the architecture? Or is it possible that some optimization will break this assumption?

**Comment by EugeneZelenko** [comment]
Please use https://discourse.llvm.org for questions.
