### ISSUE TITLE
Clangd cannot find imported C++20 module defintion

### ISSUE THREAD

**Issue by vagran** [llvm/llvm-project#57690]
In the following example:
```cpp
export module B;

import A; // <<< Trying to open definition of A
```
it is impossible to open definition of `A`. I expect it should open file of `A` module interface unit.

The project is properly setup and compilable. Tested in VSCode with clangd extension.

```
V[11:00:18.676] <<< {"id":89,"jsonrpc":"2.0","method":"textDocument/definition","params":{"position":{"character":8,"line":2},"textDocument":{"uri":"file:///home/artyom/projects/asio-awaitable-module-problem-demo/b.cppm"}}}

I[11:00:18.676] <-- textDocument/definition(89)
V[11:00:18.676] ASTWorker running Definitions on version 156 of /home/artyom/projects/asio-awaitable-module-problem-demo/b.cppm
I[11:00:18.676] --> reply:textDocument/definition(89) 0 ms
V[11:00:18.676] >>> {"id":89,"jsonrpc":"2.0","result":[]}
```

```console
$ /opt/clang-latest/bin/clangd --version
clangd version 16.0.0 (https://github.com/llvm/llvm-project.git ee761374f797a47919ec8f9f49f9b8b1b20573e8)
Features: linux
Platform: x86_64-unknown-linux-gnu
```

**Comment by sam-mccall** [comment]
Sorry, clangd doesn't have any modules support.
Clang does, and clangd allows flags to be passed through to clang so some things may work or appear to work. But it would need significant design/implementation effort to get it into a usable state.

https://github.com/clangd/clangd/issues/1293 is the tracking bug for this, but nobody is currently working on it :-(
