### ISSUE TITLE
Driver/mingw-cfguard.c test is failing

### ISSUE THREAD

**Issue by MikeHolman** [llvm/llvm-project#57705]
There is this check in the test, which I think is invalid.
`// GUARD_CF-NEXT: ld"`
In my environment, this is my ld command, so checking for `ld"` doesn't work:
`"c:\\programdata\\chocolatey\\bin\\ld.exe"`

This check was recently added in https://reviews.llvm.org/D132810

**Comment by pogo59** [comment]
Probably should be `// GUARD_CF-NEXT: ld{{(\.exe)?}}"`
Are you willing to post a patch yourself?

**Comment by MikeHolman** [comment]
Sure, I can post a patch.

**Comment by MikeHolman** [comment]
Looks like this has been fixed by https://reviews.llvm.org/D133773
