### ISSUE TITLE
Clangd exited with code 3221225477

### ISSUE THREAD

**Issue by imsuckatcsharp** [llvm/llvm-project#57720]
Im using ST4 for Editing I downloaded LSP from package manager and choose clangd. It worked perfectly until it said "_clangd_ _exited_ _with_ _code_ _3221225477_ " it gives me 2 options restart clangd which works but annoys me or cancel it and dont use it until restarting the program. What should I do?

**Comment by sam-mccall** [comment]
Sorry that it's been crashing for you.
This isn't a support forum, if you're interested in reporting/fixing a bug please see https://clangd.llvm.org/troubleshooting for the kind of information that might be useful.
