### ISSUE TITLE
[LLD] powerpc64/powerpc64le incorrect linkage of IFUNC symbols on FreeBSD kernel

### ISSUE THREAD

**Issue by adalava** [llvm/llvm-project#57722]
On FreeBSD powerpc64 and powerpc64le kernels panic when copyin/copyout symbols are called by external loadable kernel modules (like pfsync) after change https://reviews.freebsd.org/rG47a57144af25a7bd768b29272d50a36fdf2874ba where the IFUNC copyin/copyout functions are in a struct of function pointers.

While debugging LLD I found that the symbols get `HAS_DIRECT_RELOC` set and the type is changed from `STT_GNU_IFUNC` to `STT_FUNC`. A workaround is wrap the calls in a local function (see workaround code in https://reviews.freebsd.org/D36234). 
The following tentative also makes a good binary, but it's incorrect and may cause other problems: https://reviews.llvm.org/D133745

You can download LLD reproduce tar from: https://people.freebsd.org/~alfredo/tmp/llvm-freebsd-ppc64-kernel-copyout-ifunc.tar.xz
With `readelf -a kernel.full | grep -w copyout` on a good binary you should see two entries of type IFUNC while FUNC on the bad binaries.

Thanks!

**Comment by MaskRay** [comment]
See https://maskray.me/blog/2021-01-18-gnu-indirect-function#address-significance STT_GNU_IFUNC has to be converted to STT_FUNC in this case as satisfy pointer equality. I think FreeBSD has a bug somewhere that incorrectly uses non-GOT-generating non-PLT-generating relocation somewhere. The issue should be discussed on the FreeBSD side.
