### ISSUE TITLE
Missed optimization for flooring division of signed by power of two

### ISSUE THREAD

**Issue by tspiteri** [llvm/llvm-project#57741]
If a signed integer is divided by a power of two it is not a simple shift like for unsigned because division rounds to zero while the shift would round down. If flooring division is implemented, then flooring division by a power of two is equivalent to an arithmetic shift.

Here, `floor_div4_a` and `floor_div4_b` are equivalent, but the code generated for `_a` is not as good as `_c`.

```c
inline int floor_div(int n, int d)
{
    int q = n / d;
    int r = n % d;
    if ((r < 0 && d > 0) || (r > 0 && d < 0))
        q -= 1;
    return q;
}

int floor_div4_a(int i)
{
    return floor_div(i, 4);
}

int floor_div4_b(int i)
{
    return i >> 2;
}
```

\[[Compiler explorer](https://godbolt.org/z/vebf4Waxv)\]

(This is similar to rustc issue https://github.com/rust-lang/rust/issues/71096.)

**Comment by scottmcm** [comment]
Alive2 proof: <https://alive2.llvm.org/ce/z/vpidT9>

**Comment by rotateright** [comment]
Generalized pattern and requirements:
https://alive2.llvm.org/ce/z/MJzlhl

I was hoping there was some sub-pattern we could squash within there, but I don't see it, so I'll try to add the large match.

**Comment by rotateright** [comment]
I typo'd the bug number in the commit message, but this should be fixed with:
86b4a2355e73ff37a785aac74
