### ISSUE TITLE
AArch32 Clang doesn't allow using FP16 floating-point instructions in inline assembly

### ISSUE THREAD

**Issue by Maratyszcza** [llvm/llvm-project#57753]
Floating-point (i.e. non-NEON) FP16 arithmetic instructions use `s0-s31` registers in AArch32, corresponding to inline assembly constraint `"t"`. However, attempting to pass either `__fp16` or `_Float16` variable in a `"t"`-constraint register into inline assembly results in an error "couldn't allocate output register for constraint 't'".

Reproducer (build with `-march=armv8.2-a+fp16 -mfpu=fp-armv8`):
```c
// This one works in GCC
__fp16 f(__fp16 x) {
    __fp16 y;
    __asm__ ("vsqrt.f16 %[y], %[x]"
      : [y] "=t" (y)
      : [x] "t" (x));
    return y;
}

// Using Clang-specific _Float16 type doesn't work either
_Float16 g(_Float16 x) {
    _Float16 y;
    __asm__ ("vsqrt.f16 %[y], %[x]"
      : [y] "=t" (y)
      : [x] "t" (x));
    return y;
}
```

Godbolt: [link](https://gcc.godbolt.org/z/MxEadTTPa)

**Comment by lenary** [comment]
This seems like an oversight. I’m working on a patch to fix it.

**Comment by lenary** [comment]
Patch: https://reviews.llvm.org/D134553 - sorry this took a week, too many distractions.

**Comment by Maratyszcza** [comment]
Thank you for the fix!
