### ISSUE TITLE
clang ensure LC_FUNCTION_STARTS is added to all LC_FILESET_ENTRY entries

### ISSUE THREAD

**Issue by blacktop** [llvm/llvm-project#57752]
I apologize if this is an Apple clang thing and not a llvm clang thing, but in the NEW Apple FILESET kernelcaches none of the fileset entries have LC_FUNCTION_STARTS other than the kernel and they are so useful for disassemblers.

**Comment by yuanfang-chen** [comment]
If you could reproduce the issue with upstream Clang, please attach the test case here. Otherwise, filing this against https://github.com/apple/llvm-project should be better.

**Comment by Endilll** [comment]
Author has never got back to us.
