### ISSUE TITLE
how to analysis the thread idx in cuda

### ISSUE THREAD

**Issue by QinCheng968** [llvm/llvm-project#57755]
just want to know are there some utils to analysis the thread idx in cuda, like use scev to analysis induction variable in loop.
for example:
data[10] = {1,2,3,4,5};
a = data[idx%2];
 how can we kwon the value in every thread lane ?
more than:
how to do the alias analysis in different thread in cuda.

**Comment by fhahn** [comment]
For questions about how to use LLVM please use https://discourse.llvm.org

**Comment by Artem-B** [comment]
I think the only knowledge LLVM has of threadIdx and such is the range metadata added by https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/NVPTX/NVVMIntrRange.cpp

I vaguely recall that there were some issues with it (it didn't set the correct range for some GPU variants, IIRC) and I'm not 100% sure it's currently enabled.
