### ISSUE TITLE
Code Review UI

### ISSUE THREAD

**Issue by micttyl** [llvm/llvm-project#57765]
I am sorry if this is not where Phabricator is taken care of.
On the side of the github page:
```
The LLVM Project is a collection of
modular ...
Please submit your patches at http://reviews.llvm.org.
```
When I follow the link, I expect to see something like `Submit my patch`
as it was instructed so. Is this something you can make a change?

**Comment by keith** [comment]
You can find documentation for this here https://llvm.org/docs/Contributing.html#how-to-submit-a-patch

**Comment by fhahn** [comment]
It would probably be good to link to the contributing page instead of just Phabricator.

@asl do you know who could adjust the link in the GitHub description?
