### ISSUE TITLE
AArch32 vbfdotq_f32 causes internal compiler fault

### ISSUE THREAD

**Issue by fbarchard** [llvm/llvm-project#57770]
A function containing BF16 dot product causes a compiler fault.  Intrinsic looks like this
```vacc0x0 = vbfdotq_f32(vacc0x0, va0, vb0);```

Godbolt function that fails in clang15
https://godbolt.org/z/rxxcPjP9q

From a command line built the error reported is:
```console
fatal error: error in backend: Cannot select: 0x5555564090b8: v4bf16 = ARMISD::VEXT 0x55555640d1c0, 0x55555640d1c0, Constant:i32<2>
  0x55555640d1c0: v4bf16,ch = CopyFromReg 0x5555560e6648, Register:v4bf16 %114
    0x55555640d020: v4bf16 = Register %114
  0x55555640d1c0: v4bf16,ch = CopyFromReg 0x5555560e6648, Register:v4bf16 %114
    0x55555640d020: v4bf16 = Register %114
  0x555556418c40: i32 = Constant<2>
In function: xnn_bf16_gemm_minmax_ukernel_3x4c8__neonbf16_bfdot
```

**Comment by Maratyszcza** [comment]
Further simplifier repro: https://godbolt.org/z/PKP5ob59x

**Comment by fhahn** [comment]
cc @davemgreen

**Comment by Maratyszcza** [comment]
Could this get more attention? Internal compiler error is as bad as it gets.

**Comment by davemgreen** [comment]
> Could this get more attention? Internal compiler error is as bad as it gets.

Miscompiles are worse :)

I can see about some fixes. Unfortunately, the Arm backend only has limited support for bf16 operations at present, relying on the frontend producing errors. That doesn't work for a lot of situations though. I'll see about fixing the issues here.

**Comment by davemgreen** [comment]
All the cases here now appear to work. Let me know if there are any other problems, either for Arm or AArch64.

**Comment by Maratyszcza** [comment]
Thank you. We haven't seen such errors with AArch64, seems to be limited to AArch32.
