### ISSUE TITLE
[C++20][Modules][clang-format] Incorrect format for `export import </>`

### ISSUE THREAD

**Issue by kilasuelika** [llvm/llvm-project#57798]
I'm using clang-format 15. Recently I find that if I write
```cpp
export import <Eigen/Core>;
```
Then `clang-format` will incorrectly convert it to
```cpp
export import <Eigen / Core>;
```
Extrac space will trigger compilation error. If I only use `import <Eigen/Core>;` then it will be OK.

Full code will be:
```cpp
export module MyLib;

import std.core;
using namespace std;

export import <Eigen/Core>;
```

**Comment by owenca** [comment]
https://reviews.llvm.org/D134700
