### ISSUE TITLE
Compiling c++20 code with -Wpre-c++17-compat causes a crash

### ISSUE THREAD

**Issue by Drew-j-Smith** [llvm/llvm-project#57793]
[Compiler Explorer](https://godbolt.org/z/MehKvvE9G)
```cpp
template <typename T>
struct foo {};

template <foo x>
constexpr static auto bar = x;
```
Passing a templated type without specifying the template with `-Wpre-c++17-compat` crashes the compiler

**Comment by mizvekov** [comment]
Duplicate of #57369
