### ISSUE TITLE
fatal error: error in backend: Cannot select: intrinsic %llvm.arm.crc32b

### ISSUE THREAD

**Issue by pkubaj** [llvm/llvm-project#57802]
llvm 16.0.0 from FreeBSD`s llvm-devel-16.0.d20220906 package
FreeBSD 13.1-RELEASE
armv7

Run:
```shell
clang-devel -cc1 -triple armv7-unknown-freebsd13.1-gnueabihf -emit-obj 7zCrc-50d52a.c
```

`7zCrc-50d52a.c`:
```c
int a, b;
int d() {
  return __builtin_arm_crc32b(a, b);
}
```

Output:
```console
fatal error: error in backend: Cannot select: intrinsic %llvm.arm.crc32b
```

**Comment by MaskRay** [comment]
Patch: https://reviews.llvm.org/D134127

**Comment by stefson** [comment]
I just reproduced this with clang-14 for armv7-unknown-linux-gnueabihf, so can you please consider to backport the fix to all supported branches?

**Comment by EugeneZelenko** [comment]
@stefson: Only 15 is supported.

**Comment by stefson** [comment]
if llvm-15 is all supported branches, I take it (:

**Comment by MaskRay** [comment]
> I just reproduced this with clang-14 for armv7-unknown-linux-gnueabihf, so can you please consider to backport the fix to all supported branches?

This issue usually doesn't matter because users are supposed to include `arm_acle.h` and `__crc32*` instead of the underlying `__builtin_arm_crc32*`. `arm_acle.h` uses `#ifdef __ARM_FEATURE_CRC32`, so the issue won't manifest.

**Comment by davemgreen** [comment]
Good stuff. We should reopen this to make sure the AArch64 equivalent happens too, it should be a very similar patch.
https://godbolt.org/z/oMnonzP8o
