### ISSUE TITLE
"Not an int attribute" error when linking objects built by clang-15 with lld-14 and LTO

### ISSUE THREAD

**Issue by vient** [llvm/llvm-project#57817]
I am using Clang 15.0.1 and lld 14.0.6

An empty source
```cpp
int main() {
    return 0;
}
```
compiled naively produces
```
$ clang++-15 --ld-path=/usr/bin/ld.lld-14 -flto=thin main.cpp
ld.lld-14: error: /tmp/main-b7a9b4.o: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM15.0.1' Reader: 'LLVM 14.0.6')
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Adding `-Xclang -no-opaque-pointers` leads to following error
```
$ clang++-15 --ld-path=/usr/bin/ld.lld-14 -flto=thin -Xclang -no-opaque-pointers main.cpp
ld.lld-14: error: /tmp/main-2d1e49.o: Not an int attribute (Producer: 'LLVM15.0.1' Reader: 'LLVM 14.0.6')
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Do I use it wrong? Is it a bug or linking LTO modules is not supported when using different major versions of clang and lld?

**Comment by nikic** [comment]
> Is it a bug or linking LTO modules is not supported when using different major versions of clang and lld?

You can use a *newer* version to perform LTO, but not an older one. Bitcode is backwards compatible, not forwards compatible.
