### ISSUE TITLE
HELP: AddressSanitizer failed to allocate 0x0 (0) bytes of ReadFileToBuffer (error code: 22)

### ISSUE THREAD

**Issue by adonis0147** [llvm/llvm-project#57838]
Hi team,

Recently, I used clang++-14 with asan to compile our project, but I met the following errors when I started the program up.

```console
==417382==ERROR: AddressSanitizer failed to allocate 0x0 (0) bytes of ReadFileToBuffer (error code: 22)
ERROR: Failed to mmap
```

Environment:

1. Macbook Pro 2020 (M1 chip)
2. QEMU 7.1.0
3. Ubuntu 22.04.1 LTS
4. LLVM
    1. `sudo apt install clang-14 lld-14`
    2. `export PATH="/lib/llvm-14/bin:${PATH}"`
5. QEMU 
    ```shell
    qemu-system-aarch64 
        -machine virt,accel=hvf \
        -cpu host \
        -smp 4 \
        -m 8G \
        ...
    ```

I compiled the project in guest OS in QEMU but failed to start the program up.

**Comment by adonis0147** [comment]
I have resolved this problem by myself.

**Comment by EugeneZelenko** [comment]
@adonis0147: Could you please share workaround? Just in case if somebody else would encounter similar problem.

**Comment by adonis0147** [comment]
Hi @EugeneZelenko , this issue is irrelevant to LLVM. In our project, a GLIBC function is masked by the one in MUSL and the masked function doesn't work on aarch64 platform. I recorded some information [apache/doris#13031](https://github.com/apache/doris/pull/13031).
