### ISSUE TITLE
`duration::operator<` (`__duration_lt`) overflows with `std::chrono::milliseconds::max()`

### ISSUE THREAD

**Issue by xroche** [llvm/llvm-project#57839]
The following line should compile with libc++, but doesn't:

```c++
static_assert(std::chrono::nanoseconds{ 42 } <= std::chrono::milliseconds::max());
```

The issue is that `__duration_lt` will at some point multiply `std::chrono::milliseconds::max()` to 1,000,000 to get a nanosecond representation, and will overflow:

```
duration.h(97, 59): Value 9223372036854775807000000 is outside the range of representable values of type 'long long'
```

Tested with `libc++ 1:14.0.6~++20220816122211+f28c006a5895-1~exp1~20220816122246.108` (tag [`llvmorg-14.0.6`](https://github.com/llvm/llvm-project/commit/f28c006a5895fc0e329fe15fead81e37457cb1d1)) on Ubuntu 22.04.1.

**Comment by mordante** [comment]
Based on the [standard](http://eel.is/c++draft/time.duration.comparisons) comparison operations need to cast to the `common_type` and convert the input. This will fail in this case. 

Both libstdc++ and MSVC STL fail to compile this to.
