### ISSUE TITLE
[HLSL] Availability attribute support

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#57849]
HLSL APIs can be available by shader model version and/or pipeline stage. I've added initial support for shader model versions, but also need to extend it to support pipeline stages.

**Comment by damyanp** [comment]
@hekota / @llvm-beanz - how does this relate to #87389?

**Comment by hekota** [comment]
It seems to be a duplicate of #87389.

**Comment by llvm-beanz** [comment]
I think I initially intended this as "extending the annotations to support shader stages" which would be a sub-task of #87389, but feel free to close and create appropriate subtasks.

**Comment by damyanp** [comment]
We're tracking this with the other issues mentioned earlier in the conversations.
