### ISSUE TITLE
libclang: broken symbolic link on Debian

### ISSUE THREAD

**Issue by aykevl** [llvm/llvm-project#57857]
I installed `libclang-15-dev` from [apt.llvm.org](https://apt.llvm.org/) on Debian bullseye but it creates a broken symbolic link for libclang.so:

```
$ ls -l /usr/lib/llvm-15/lib/libclang.so
lrwxrwxrwx 1 root root 39 20 sep 10:03 /usr/lib/llvm-15/lib/libclang.so -> ../../x86_64-linux-gnu/libclang-15.so.1

$ file /usr/lib/llvm-15/lib/libclang.so
/usr/lib/llvm-15/lib/libclang.so: broken symbolic link to ../../x86_64-linux-gnu/libclang-15.so.1
```

This means that it is difficult to link against libclang. Previous versions had this working properly:

```
$ ls -l /usr/lib/llvm-14/lib/libclang.so
lrwxrwxrwx 1 root root 39 27 aug 22:23 /usr/lib/llvm-14/lib/libclang.so -> ../../x86_64-linux-gnu/libclang-14.so.1

$ file /usr/lib/llvm-14/lib/libclang.so
/usr/lib/llvm-14/lib/libclang.so: symbolic link to ../../x86_64-linux-gnu/libclang-14.so.1
```

(This might be a duplicate of #57473).

EDIT: quick fix: `sudo ln -sfn libclang-15.so.15 /usr/lib/x86_64-linux-gnu/libclang-15.so`

**Comment by sylvestre** [comment]
I will have a look quickly

**Comment by sylvestre** [comment]
i pushed the fix in the repo and restarted the builds
