### ISSUE TITLE
[HLSL] Need better name for ParsedAttr::AS_HLSLSemantic

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#57882]
The choice of AS_HLSLSemantic is an unfortunate name for both resources and semantics.

The proposed new name is `ParsedAttr::AS_HLSLAnnotation` 

AC:
- AS_HLSLSemantic enum value is renamed to AS_HLSLAnnotation
- Source and tests are updated appropriately
- Double check if HLSLSemantic phrasing appears in other locations like method names or SEMA that also need to be adjusted to reflect the new spelling

**Comment by bob80905** [comment]
Closed with #89309
