### ISSUE TITLE
[HLSL] Validate system value semantic based on the entry profile instead of shader profile

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#57880]
When report diag::err_hlsl_attr_unsupported_in_stage, the validation for system value semantic is checking shader profile.
But it is OK for a shader to have both pixel entry and compute entry at the same time.
Need to validate system value semantic based on the profile of the entry function.

**Comment by bogner** [comment]
Fixed in ef2b1700f4648816e6a6ce27cfee1c501421ee50
