### ISSUE TITLE
[HLSL] Support semantic on struct field.

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#57889]
Support case like
struct Input {
 int GI : SV_GroupIndex;
 int ID : SV_DispatchThreadID;
};

**Comment by bogner** [comment]
Duplicate of https://github.com/llvm/llvm-project/issues/57875

**Comment by bob80905** [comment]
This may not necessarily be a duplicate. One issue is ensuring that input structs have a semantic on every member.
This issue may be addressing the fact that some semantics aren't parsed on fields at all. A subtle difference.
