### ISSUE TITLE
Install of libc++ headers into an existing tree fails in llvm-15.0.1 using ninja

### ISSUE THREAD

**Issue by debohman** [llvm/llvm-project#57890]
A failure occurs when trying to install the header files into an existing tree. The item ```c++/v1/__string``` changes in the 15 runtime from a regular file to a directory, and that causes the install to fail.

```llvm-15.0.1``` ```cmake-3.24.2``` ```ninja-1.11.0``` ```macOS 10.12.6```

**Comment by philnik777** [comment]
Yes. You can clear your install directory or remove `c++/v1/__string` to solve the problem. If you also install compiler-rt you also have to remove `projects/compiler-rt/lib/fuzzer/libcxx_fuzzer_<platform triple>/include/c++/v1/__string`.

**Comment by debohman** [comment]
That is interesting, I don't have ```projects/compiler-rt/lib/fuzzer/libcxx_fuzzer_<platform triple>/include/c++/v1/__string``` in my build directory. I am using a separate build directory. I have in the top level ```CMakeCache.txt```:

```
LLVM_ENABLE_PROJECTS:STRING=clang
LLVM_ENABLE_RUNTIMES:STRING=libcxx;libcxxabi;libunwind;compiler-rt
```

**Comment by debohman** [comment]
To work around this problem, I installed into a temp tree, then used a tar pipeline to copy the tree into the prefix location. That does not seem to be an optimal solution.

**Comment by philnik777** [comment]
The path might be different in a bootstrapping build, I don't know. If you don't have problems with compiler-rt it should be just fine. Is there a reason you couldn't clear your install directory?

**Comment by debohman** [comment]
The general problem is that the runtimes seem to be building against a macOS SDK, not against the headers contained within the llvm project.

Note that ```runtimes/runtimes-bins/CMakeCache.txt``` contains:

```
CMAKE_OSX_SYSROOT:STRING=
```

That forces it to use the header files from the system SDK, not the headers in llvm. See #57863 for a first inkling about this from a different angle.

**Comment by mordante** [comment]
Since we're now at LLVM17 I feel we can close this. We will not fix this retro-actively. I also feel we are "done" with granularizing our headers so I don't expect this to happen in the future.
