### ISSUE TITLE
Can't install the LLVM 

### ISSUE THREAD

**Issue by Kim1230** [llvm/llvm-project#57895]
Hello, I got a problem when I try to install LLVM 
OS will be Linux 2288HV5-47-26 4.19.90-24.4.v2101.ky10.x86_64 #1 SMP Mon May 24 12:14:55 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
**This is a kylin Operating System**
LLVM: release 14.0.x 
Command:
cd llvm-project
git checkout release/14.x
cmake -S llvm -B build -DCMAKE_INSTALL_PREFIX=/home/yjy/LLVM/ -DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra;openmp' -DLLVM_ENABLE_RUNTIMES='libcxx;libcxxabi;compiler-rt' -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=On

Problem:
make install shows:
![image](https://user-images.githubusercontent.com/107012598/191686461-0c7f32bc-9fa5-475f-a223-a251a7cd7aca.png)
Can someone help me ?
Thanks!

**Comment by Kim1230** [comment]
And when I use the command:
cmake -S llvm -B build -DCMAKE_INSTALL_PREFIX=/home/yjy/LLVM/ -DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra;openmp;libc' -DLLVM_ENABLE_RUNTIMES='libcxx;libcxxabi;compiler-rt;libc' -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=On

The libc installation will get the problem at the cmake command：
![image](https://user-images.githubusercontent.com/107012598/191686740-3db99cfd-c925-4d0b-b9da-27aea683fa93.png)

**Comment by tbaederr** [comment]
If you have _questions_, please ask them on https://discourse.llvm.org/
