### ISSUE TITLE
how to enable `std::execution::par` in libc++ build environments

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [llvm/llvm-project#57898]
Steps to reproduce:

Ubuntu with clang from **apt.llvm.org** and with potential pstl backends installed via libtbb2-dev and clang-15-openmp is not able to compile with C++17 feature std::execution::par.

Dockerfile:
```
FROM ubuntu:22.04

RUN apt-get update && apt-get -y install \
    software-properties-common gpg wget \
    make libssl-dev

RUN apt-get install -y build-essential libthrust-dev libtbb2-dev libtbb2

# https://apt.llvm.org/
RUN wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    ./llvm.sh 15 all
ENV PATH=$PATH:/usr/lib/llvm-15/bin

RUN echo "\
\n#include <execution> \n \
\n#include <algorithm> \n \
\n#include <vector> \n \
int main(void) { \n \
    std::vector<float> images = {1,2,3,4,5}; \n \
    std::vector<float> results; \n \
    results.resize(images.size()); \n \
    std::transform(std::execution::par, images.begin(), images.end(), results.begin(), [](const auto &input){ return input; }); \n \
}" > hello.cpp

RUN clang -std=c++17 -stdlib=libc++ hello.cpp -o hello && ./hello
```

produces following error:

```
hello.cpp:11:26: error: no member named 'execution' in namespace 'std'; did you mean 'exception'?
     std::transform(std::execution::par, images.begin(), images.end(), results.begin(), [](const auto &input){ return input; }); 
                    ~~~~~^~~~~~~~~
                         exception
/usr/lib/llvm-15/bin/../include/c++/v1/exception:100:29: note: 'exception' declared here
class _LIBCPP_EXCEPTION_ABI exception
                            ^
hello.cpp:11:37: error: no member named 'par' in 'std::exception'
     std::transform(std::execution::par, images.begin(), images.end(), results.begin(), [](const auto &input){ return input; }); 
                    ~~~~~~~~~~~~~~~~^
2 errors generated.
The command '/bin/sh -c clang -std=c++17 -stdlib=libc++ hello.cpp -o hello && ./hello' returned a non-zero code: 1
```

Nevertheless, godbold shows that clang-15 should be possible to compile so:
https://godbolt.org/z/3TxoWEMxb

**update:**
godbolt has the same problem, when using libc++ instead of libstdc++
https://godbolt.org/z/eWf7Y1EnW

**Comment by tbaederr** [comment]
It's just missing in libc++. You specified `-stdlib=libc++` in your command line, but godbolt defaults to libstdc++.
Compare https://godbolt.org/z/eWf7Y1EnW

**Comment by cguentherTUChemnitz** [comment]
Ok that is interesting and totally correct. Thanks for pointing out, that i compare here different stuff. 
Let me maybe shortly clarify my motivation of what i want to achieve here. I use conan for dependency management and i do compilation:
 - from pc x86_64 to pc x86_64 
 - from pc x86_64 to pc aarch64 
 - from pc x86_64 to android armv7, armv8, x86, x86_64 using android ndk
 - from pc x86_64 to ios armv7, armv8, x86, x86_64 using xcode apple clang

I have to sync the stdlib used for dependency compilation and my own libs and binaries to enable static linking and link time optimization. Since android ndk and apple clang are libc++ only, i want to sync up the pc compilation paths to use libc++ the same way. 

So the question clarifies to: **how can i enable `std::execution::par` in such libc++ build environments?**
--> i will update the topic of the question for that and fix up the problem description.

**Comment by philnik777** [comment]
The short answer: you can't.
If you really want to use the PSTL you can build your own libc++ with `LIBCXX_ENABLE_PARALLEL_ALGORITHMS` and use that for all your platforms. It doesn't build currently though, so you'd have to apply D103198. That's obviously not supported, so I guess the next best thing is to annoy @ldionne enough to get it into LLVM 16.

**Comment by cguentherTUChemnitz** [comment]
Thank you very much @philnik777 . That is a very important insight for me avoiding a lot of wasted time by the try to fix it by self-compiling llvm with additional flags. I should have found this insight maybe also on my own by looking in the cpp version support:
https://en.cppreference.com/w/cpp/compiler_support/17#C.2B.2B17_library_features
Since there is a red box for `clang libc++` in the line of c++ library feature `Parallel algorithms and execution policies`. So we can summarize with: It is known not working and already documented. This was just not coming to my mind as an option that libc++ was lacking the support here. So i will close this ticket, since there is no further insight to get.

Nevertheless, if others come here by and wonder what to do otherwise in this situation:
It seems there is a good drop-in replacement of the parallel stl here from oneapi:
https://oneapi-src.github.io/oneDPL/parallel_api/execution_policies.html

Since this is already part of the conan package ecosystem, i can already confirm that this is compiling fine with clang and libc+++ using this package: https://conan.io/center/onedpl?version=2021.7.0
