### ISSUE TITLE
The problem of compiling using clang

### ISSUE THREAD

**Issue by Kim1230** [llvm/llvm-project#57891]
Hello,
I have installed clang in the kylin OS.
clang-10.0.1-1.ky10.x86_64
llvm-10.0.1-1.ky10.x86_64
llvm-devel-10.0.1-1.ky10.x86_64
OS is Linux 2288HV5-47-26 4.19.90-24.4.v2101.ky10.x86_64 #1 SMP Mon May 24 12:14:55 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
![image](https://user-images.githubusercontent.com/107012598/191661724-f54f6e7c-e54f-4d2d-beaf-958a12e21e59.png)
`/usr/bin/clang -c -S  test_generative.c  -I /home/yjy/float-precision/new/bin/../include/  -emit-llvm '-g' '-Wall' -o /home/yjy/toolforvel/verificarlo/tests/test_absoluteError/test_generative.kdkvuakb.1.ll`
And then :
![image](https://user-images.githubusercontent.com/107012598/191661820-57385d7d-b30a-4e2c-93e7-d7853873a3d1.png)
`/usr/local/bin/opt /home/yjy/toolforvel/verificarlo/tests/test_absoluteError/test_generative.kdkvuakb.1.ll`
The problem will be:
![image](https://user-images.githubusercontent.com/107012598/191661929-6234367c-c8b2-4cd4-ad2a-9b87f4dac497.png)
And the source code is from
https://github.com/verificarlo/verificarlo
The content of it will be ：/verificarlo/tests/test_absoluteError/test_generative.c
![image](https://user-images.githubusercontent.com/107012598/191662184-c5842c96-0cc6-4533-b0b0-bd20b0c80b55.png)
![image](https://user-images.githubusercontent.com/107012598/191662213-2e3c151a-6952-4c82-80ec-31ea9e114c2e.png)
Hope someone can help me
Thanks!

**Comment by EugeneZelenko** [comment]
10 is too old. Could you please try 15 or `main` branch? https://godbolt.org should be helpful.

**Comment by Kim1230** [comment]
> 10 is too old. Could you please try 15 or `main` branch? https://godbolt.org should be helpful.

Hello, I try to install the release 14.0 x
And when I try the command:
cmake -S llvm -B build -DCMAKE_INSTALL_PREFIX=/home/yjy/LLVM/ -DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra;openmp;libc' -DLLVM_ENABLE_RUNTIMES='libcxx;libcxxabi;compiler-rt;libc' -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=On
It has the problem:
![image](https://user-images.githubusercontent.com/107012598/191675743-bf0c4ee1-6688-45d5-aadc-88896fd7a638.png)
And when I remove libc in the enable runtimes and enable project. It will be ok.

**Comment by Kim1230** [comment]
> 

And the installation of  verificalo comment that :
![image](https://user-images.githubusercontent.com/107012598/191684229-f693d0b0-106a-47ec-929f-c71ced1414f5.png)
So, I think llvm-10.0 is possible. But I will still try to install llvm-14.0.0. But I don't know whether this is the verison problem?

**Comment by fhahn** [comment]
I don't think this is an LLVM issue. The original error message you posted indicates that your version of [verificarlo/verificarlo](https://github.com/verificarlo/verificarlo) does generate textual LLVM IR that's too new for the LLVM version you are using. 

Please check the [verificarlo/verificarlo](https://github.com/verificarlo/verificarlo) on advice on how to use it.
