### ISSUE TITLE
Arm ACLE intrinsics for FRINT are incorrectly named

### ISSUE THREAD

**Issue by minoki** [llvm/llvm-project#57900]
[ACLE](https://arm-software.github.io/acle/main/acle.html#floating-point-data-processing-intrinsics) specifies the following intrinsics in `<arm_acle.h>`:

```c
float __rint32zf(float);
double __rint32z(double);
float __rint64zf(float);
double __rint64z(double);
float __rint32xf(float);
double __rint32x(double);
float __rint64xf(float);
double __rint64x(double);
```

But [the header file for clang](https://github.com/llvm/llvm-project/blob/e030be64d8c43a56b60a90b70765fc795e177e9c/clang/lib/Headers/arm_acle.h#L642-L683) defines them with an extra `f` prefix:

```c
float __frint32zf(float);
double __frint32z(double);
float __frint64zf(float);
double __frint64z(double);
float __frint32xf(float);
double __frint32x(double);
float __frint64xf(float);
double __frint64x(double);
```

A test case:

```c
#include <stdio.h>
#include <math.h>
#include <arm_acle.h>

int main(void) {
#if defined(__ARM_FEATURE_FRINT)
    puts("__ARM_FEATURE_FRINT is defined.");
    printf("__rint32z(%g) = %a\n", INFINITY, __rint32z(INFINITY));
    printf("__rint64x(%g) = %a\n", NAN, __rint64x(NAN));
#else
    puts("__ARM_FEATURE_FRINT is not defined.");
#endif
}
```

**Comment by mplatings** [comment]
I've checked with other Arm folks and I confirm that the names are incorrect in Clang. GCC has the correct names. I guess some confusion came from the `__ARM_FEATURE_FRINT` feature name.

**Comment by mplatings** [comment]
Intrinsics were added in https://reviews.llvm.org/D98269. @jaykang10 FYI

**Comment by mplatings** [comment]
Fix for review: https://reviews.llvm.org/D134824
