### ISSUE TITLE
[HLSL] Support packoffset attribute for cbuffer

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#57914]
Documentation for packoffset is at
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-variable-packoffset

AC
- A design is created that defines how we will lower this to DXIL
- This is only the parsing support for packoffset, does not include the lowering
- Goes through code-gen to IR metadata
- Tests for the IR representation are created

**Comment by davidcook-msft** [comment]
Additional tasks needed:
* IR lowering to DXIL task
* @bogner to create additional task

**Comment by damyanp** [comment]
Waiting on llvm/wg-hlsl#50 before really finalizing what's required here.

**Comment by damyanp** [comment]
The frontend part of this is done, we have other issues tracking the full design and implementation for cbuffers and so this issue is no longer required.
