### ISSUE TITLE
clang - lifetime extensions in default member initializers already supported?

### ISSUE THREAD

**Issue by Torbenx** [llvm/llvm-project#57932]
Consider the following snippet (https://godbolt.org/z/eMTeYba56):
```c++
struct A {
    A();
    ~A();
};

struct B {
    A&& a = {};
    void member();
};

void foo() {
    B b {};
    b.member();
}
```
Currently this emits the warning 
```console
warning: sorry, lifetime extension of temporary created by aggregate initialization using default member initializer is not supported; lifetime of temporary will end at the end of the full-expression [-Wdangling]
```

However as one can see from the generated assembly, the lifetime of the temporary create in the initializer of `B::a` correctly gets its lifetime extended to the lifetime of the `B` object (`~A()` is called after `member()`).

The reason for not supporting lifetime extensions in default member initializers is described in definition of the `PathLifetimeKind` enum:
> We should lifetime-extend, but we don't because (due to technical limitations) we can't. This happens for default member initializers, which we don't clone for every use, so we don't have a unique MaterializeTemporaryExpr to update.

But as one can see in an AST dump, the `MaterializeTemporaryExpr`, that is not getting cloned, already has its lifetime extended by the corresponding `FieldDecl` and thus doesn't need to be updated:
```
|-CXXRecordDecl <line:7:1, line:10:1> line:7:8 referenced struct B definition
| |-...
| |-FieldDecl <line:8:5, col:14> col:9 a 'A &&'
| | `-ExprWithCleanups <col:11, col:14> 'A':'A' xvalue
| |   `-MaterializeTemporaryExpr <col:11, col:14> 'A':'A' xvalue extended by Field 0x558dc5d85618 'a' 'A &&'
| |     `-CXXBindTemporaryExpr <col:11, col:14> 'A':'A' (CXXTemporary 0x558dc5d85ae0)
| |       `-CXXConstructExpr <col:11, col:14> 'A':'A' 'void ()' list
| |-...
```
I don't know if this covers all possible cases but at least in the simple example here the emitted warning is a lie.

**Comment by hubert-reinterpretcast** [comment]
The observed alleged lifetime extension is a symptom of a failure to destroy at the appropriate point in time: https://github.com/llvm/llvm-project/issues/85601
