### ISSUE TITLE
LLD fails due to incorrect file path when emitting thinLTO index files for bitcode object fails that are lazily loaded

### ISSUE THREAD

**Issue by boomanaiden154** [llvm/llvm-project#57963]
Currently when lld is called with the `--thinlto-emit-index-files` option and one of the bitcode object files contains symbols that never end up getting linked into the final output (and thus the InputFile's `lazy` attribute stays set to `false`), the linker fails when emitting empty index files for the lazy input files in `thinLTOCreateEmptyIndexFiles`. I've only seen this issue occurring when linking against thin archives that contain references to files in a separate folder. Minimal reproducible example:
`a.h`:
```c++
int a();
```
`a.cpp`:
```c++
#include "a.h"

int a()
{
  return 1;
}
```
`b.h`:
```c++
int b();
```
`b.cpp`:
```c++
#include "b.h"

int b()
{
  return 2;
}
```
`main.cpp`:
```c++
#include <iostream>

#include "a.h"

int main()
{
  std::cout << a() << "\n";
}
```
compilation commands:
```bash
mkdir other-folder
clang++ -flto=thin a.cpp -c -o ./other-folder/a.o
clang++ -flto=thin b.cpp -c -o ./other-folder/b.o
clang++ -flto=thin main.cpp -c -o main.o
mkdir other-folder-2
llvm-ar -crT ./other-folder-2/library.a other-folder/a.o other-folder/b.o
clang++ -fuse-ld=lld -Wl,--thinlto-emit-index-files -flto=thin main.o ./other-folder-2/library.a -o main
```

It seems like `thinLTOCreateEmptyIndexFiles()` is not prepending the path to the archive to the bitcode file it's trying to emit, but more investigation is necessary. Everything works perfectly when the symbols are actually used, but when they aren't things begin to fail.

Assigning to myself as I'm planning on working on it if I end up having time, but leaving steps to reproduce here in case anyone else decides to pick this up.

@mtrofin

**Comment by MaskRay** [comment]
To the best of my knowledge no build system handles distributed ThinLTO with regular or thin archives.
A major issue is that where to store index files and how the build system relates an index to an archive member isn't clear, e.g. in the case where an archive and its member are in different directories.

If we use absolute paths in the thin archive, we get `other-folder-2/library.a(a.o at 194).thinlto.bc`.
It's unclear the substring `a.o` refers to `other-folder/a.o`.

**Comment by boomanaiden154** [comment]
This is error is coming from a local ThinLTO chromium build with `--thinlto-emit-index-files` also passed to the linker for corpus extraction for MLGO corpus extraction. Ack on the issue of clarity on where to put the `*.thinlto.bc` files. In the case where all the object files in the archive are linked against, the `*.thinlto.bc` files are put in the same directory is the thin archive. Is that the behavior we should be trying to replicate here?

**Comment by mtrofin** [comment]
Added @Northbadge if he has more context.

**Comment by Northbadge** [comment]
Had a quick look with the MRE, seems like `thinLTOCreateEmptyIndexFiles` (or whatever is causing the failure, don't have a dev env to debug) doesn't resolve the relative file paths in thin archives correctly.

It resolves from pwd, instead of from the archive directory, so it complains about not finding `other-folder-2`, one directory up from pwd.

If you run the last command in `other-folder-2` it works as expected. 

Also, this happens with just `-thinlto-index-only`, and when run from `other-folder-2`, does write out the empty index file, so I'm inclined to believe it's to do with the empty file creator.

**Comment by boomanaiden154** [comment]
It looks like passing along the path created in the `BitcodeFile::BitcodeFile(...)` constructor to `thinLTOCreateEmptyIndexFiles()` and then using that path to create the empty index file matches the behavior of the existing `emitFiles()` function in regards to handling thin archives. I'm thinking this (somewhat) avoids the ambiguity that @MaskRay mentioned of how an index relates to an archive member without passing in this additional information given it matches the file path behavior of the default path in `emitFiles()`? Just want to make sure I'm not missing anything in regards to that before I go to write up a patch.
