### ISSUE TITLE
[clang-tidy] can't find <coroutine> when -stdlib=libstdc++

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#57973]
See the top panel for https://godbolt.org/z/d59j5dnTj.

**Comment by kiwixz** [comment]
Godbolt uses libstdc++ 9 (without the `<coroutine>` header).  You can test this with the verbose `-v` flag.

**Comment by cjdb** [comment]
> Godbolt uses libstdc++ 9 (without the `<coroutine>` header). You can test this with the verbose `-v` flag.

Why would Clang use a different standard library to Clang Tidy?

**Comment by kiwixz** [comment]
I don't know, this is just how godbolt is set up.  You can see that the compiler uses clang 15 with libstdc++ 12 but clang-tidy 16 with libstdc++ 9.

**Comment by cjdb** [comment]
Thanks!

**Comment by bogre** [comment]
Hi,
for me locally, the same thing as on godbolt. I cannot make cling-tidy to work with the same stdlib as clang. I compile successfully with clang++-15 and g++-12 (with std=c++20 and for gcc additionally -fcoroutines) but tidy cant see header coroutine, even-though I did not make anything special for tidy.

**Comment by kiwixz** [comment]
Does your `compile_commands.json` have the correct compiler (exactly `clang++-15` with version) ?

If so, try also adding the `-v` flag in there so clang-tidy will tell you what version of clang and stdlib it find and uses.

**Comment by bogre** [comment]
I tried on single spp file, do we still need compile commands, I mean I have it, and it is right, but I would not expect that can be an issue

**Comment by bogre** [comment]
Here is compile_commands.json in the same dir where souce file is
[
{
  "directory": "/home/boki/Projects/CppTrainings/Coroutines/build/out",
  "command": "/usr/bin/clang++-15 -v -I/home/boki/Projects/CppTrainings/Coroutines/incl -fcoroutines -fno-builtin -Wall -Wextra -o CMakeFiles/simplecoro.dir/simplecoro.cpp.o -c /home/boki/Projects/CppTrainings/Coroutines/simplecoro.cpp",
  "file": "/home/boki/Projects/CppTrainings/Coroutines/simplecoro.cpp"
}
]

**Comment by kiwixz** [comment]
You probably got misled by libstdc++ error message, to enable coroutines with clang you just need to pass `-std=c++20` but not `-fcoroutines` which is a g++ flag.

**Comment by bogre** [comment]
yeah, yeah, sorry, I changed that, of course. So that is not issue, I updated what I paste here

**Comment by bogre** [comment]
As I mention, it compiles with clang++-15 ang g++-12. For g++ I set -fcoroutines

**Comment by bogre** [comment]
clang Invocation:
 "clang++" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-fsyntax-only" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "simplecoro.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-mllvm" "-treat-scalable-fixed-error-as-warning" "-debugger-tuning=gdb" "-v" "-fcoverage-compilation-dir=/home/boki/Projects/CppTrainings/Coroutines/build/out" "-resource-dir" "/usr/local/lib/clang/15.0.0" "-I" "/home/boki/Projects/CppTrainings/Coroutines/incl" "-internal-isystem" "/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11" "-internal-isystem" "/../lib/gcc/x86_64-linux-gnu/11/../../../../include/x86_64-linux-gnu/c++/11" "-internal-isystem" "/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/backward" "-internal-isystem" "/usr/local/lib/clang/15.0.0/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/../lib/gcc/x86_64-linux-gnu/11/../../../../x86_64-linux-gnu/include" "-internal-externc-isystem" "/usr/include/x86_64-linux-gnu" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-Wall" "-Wextra" "-fdeprecated-macro" "-fdebug-compilation-dir=/home/boki/Projects/CppTrainings/Coroutines/build/out" "-ferror-limit" "19" "-fno-builtin" "-fgnuc-version=4.2.1" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c++" "/home/boki/Projects/CppTrainings/Coroutines/simplecoro.cpp"

clang -cc1 version 15.0.0 based upon LLVM 15.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/home/boki/Projects/CppTrainings/Coroutines/incl"
ignoring nonexistent directory "/../lib/gcc/x86_64-linux-gnu/11/../../../../x86_64-linux-gnu/include"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11
 /../lib/gcc/x86_64-linux-gnu/11/../../../../include/x86_64-linux-gnu/c++/11
 /../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/backward
 /usr/local/lib/clang/15.0.0/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
1 warning and 21 errors generated.
Error while processing /home/boki/Projects/CppTrainings/Coroutines/simplecoro.cpp.
error: too many errors emitted, stopping now [clang-diagnostic-error]
error: unknown argument: '-fcoroutines' [clang-diagnostic-error]
/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/coroutine:334:2: error: "the coroutine header requires -fcoroutines" [clang-diagnostic-error]

**Comment by kiwixz** [comment]
Message is saying you didnt do what I talked about in my last comment.  Maybe you are usually compiling with g++ so it overrides the compile_commands.json in such a way clang-tidy cant use it anymore ?  Either way the problem is there.

**Comment by bogre** [comment]
yeah, I started tidy again, and updated output above

**Comment by kiwixz** [comment]
You are still not passing `-std=c++20`....

**Comment by bogre** [comment]
OKKKK, you are right, when I build with cmake it generates compile_commands for gcc, and I forgot that I added 
post build command to copy compile_commands to root from build. So, when I start tidy it cant see GNU flags, and fails, btw, cmake generate GNU20 flag for CXX20. Anyway, with proper compile_commands tidy works, as you said.
Thank you very much, and sorry for bothering you.
