### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by gtt1995** [llvm/llvm-project#57980]
llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:861:68: error: invalid suffix 's' on integer constant
                                                                                                 /*TimeOfUnit=*/duration_cast<microseconds>(0s), {0}, DFT,
1 error generated.

**Comment by fhahn** [comment]
Could you please specify which version of LLVM this is for, the full compiler invocation and the compiler version you are using? Without that, it is impossible to say if it is an issue with your build environment or an issue in LLVM

**Comment by gtt1995** [comment]
gutaotao@x1-1:/workspace/llvm-project/compiler-rt/lib/fuzzer$ uname -a
Linux x1-1 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
gutaotao@x1-1:/workspace/llvm-project/compiler-rt/lib/fuzzer$ cat build.sh 
#!/bin/sh
LIBFUZZER_SRC_DIR=$(dirname $0)
CXX="${CXX:-clang}"
for f in $LIBFUZZER_SRC_DIR/*.cpp; do
  clang++ -g -O2 -fno-omit-frame-pointer -std=c++11 $f -c &
#  $CXX -g -O2 -fno-omit-frame-pointer -std=c++11 $f -c &
done
wait
rm -f libFuzzer.a
ar ru libFuzzer.a Fuzzer*.o
rm -f Fuzzer*.o

gutaotao@x1-1:/workspace/llvm-project/compiler-rt/lib/fuzzer$ uname 
Linux
gutaotao@x1-1:/workspace/llvm-project/compiler-rt/lib/fuzzer$ uname  -a
Linux x1-1 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
gutaotao@x1-1:/workspace/llvm-project/compiler-rt/lib/fuzzer$ cat build.sh 
#!/bin/sh
LIBFUZZER_SRC_DIR=$(dirname $0)
CXX="${CXX:-clang}"
for f in $LIBFUZZER_SRC_DIR/*.cpp; do
  clang++ -g -O2 -fno-omit-frame-pointer -std=c++11 $f -c &
#  $CXX -g -O2 -fno-omit-frame-pointer -std=c++11 $f -c &
done
wait
rm -f libFuzzer.a
ar ru libFuzzer.a Fuzzer*.o
rm -f Fuzzer*.o

gutaotao@x1-1:/workspace/llvm-project/compiler-rt/lib/fuzzer$ clang --version
clang version 11.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
gutaotao@x1-1:/workspace/llvm-project/compiler-rt/lib/fuzzer$ clang++ --version
clang version 11.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
gutaotao@x1-1:/workspace/llvm-project/compiler-rt/lib/fuzzer$

**Comment by gtt1995** [comment]
commit bebc96956b76bdbc36f1d82a788c810e5b12e2c5 (HEAD -> main, origin/main, origin/HEAD)
Author: David Green <david.green@arm.com>
Date:   Mon Sep 26 09:55:10 2022 +0100

    [AArch64] Enable FeatureFuseAdrpAdd for all Arm cpus
    
    The commit D120104 enabled FeatureFuseAdrpAdd for -mcpu=generic,
    allowing the linker to relax adrp;add pairs where possible. D132075
    extended that to neoverse-n1, this patch extends it to all other cortex
    and neoverse cpus for the same reasons.
    
    Differential Revision: https://reviews.llvm.org/D134521

**Comment by gtt1995** [comment]
> commit [bebc969](https://github.com/llvm/llvm-project/commit/bebc96956b76bdbc36f1d82a788c810e5b12e2c5) (HEAD -> main, origin/main, origin/HEAD) Author: David Green [david.green@arm.com](mailto:david.green@arm.com) Date: Mon Sep 26 09:55:10 2022 +0100
> 
> ```
> [AArch64] Enable FeatureFuseAdrpAdd for all Arm cpus
> 
> The commit D120104 enabled FeatureFuseAdrpAdd for -mcpu=generic,
> allowing the linker to relax adrp;add pairs where possible. D132075
> extended that to neoverse-n1, this patch extends it to all other cortex
> and neoverse cpus for the same reasons.
> 
> Differential Revision: https://reviews.llvm.org/D134521
> ```

Hello, thank you for your reply.
For the official git repo, I did not change any code.

**Comment by fhahn** [comment]
It looks like you are using manual build commands. Please make sure to use the same flags as if configured by cmake when building.

> clang++ -g -O2 -fno-omit-frame-pointer -std=c++11 $f -c &

This doesn't look correct, latest LLVM requires C++17 to build: https://llvm.org/docs/CodingStandards.html#c-standard-versions
