### ISSUE TITLE
Assertion ` castIsValid(op, S, Ty) && "Invalid cast!"' failed.

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#57986]
clang-16 -cc1 -triple s390x-ibm-linux -S -O2 -o /dev/null  tc_crash0_aftercreduce.ll

...
#9 0x000002aa01a1de90 llvm::InstCombinerImpl::visitCallInst(llvm::CallInst&)
...

[testcase.tar.gz](https://github.com/llvm/llvm-project/files/9647836/testcase.tar.gz)

**Comment by rotateright** [comment]
We're dying on this fold:
    // umin(x, 1) == zext(x != 0)

Reduced IR test that fails with "opt -instcombine":
```ll
@g = external dso_local global [9 x i32], align 4

define i1 @PR57986() {
  %umin = call i1 @llvm.umin.i1(i1 ptrtoint (ptr @g to i1), i1 true)
  ret i1 %umin
}

```

**Comment by rotateright** [comment]
That fold in instcombine is awkward, but we can probably resolve this with a small change to -instsimplify. 
Ie, we really should've killed that instruction before it tried to get transformed because "true" is the max value of i1.

**Comment by rotateright** [comment]
@JonPsson - I think this is fixed with the above 3 commits (the 1st two are enough to avoid crashing). If you agree, we can either close or try to backport to the release branch. I have no preference on that (it is a crasher, but it's probably been there for a long time).

**Comment by JonPsson** [comment]
Thanks for the quick fix! I have verified that the crash is gone also on the unreduced test case now (csmith).

I'll close this then. Don't know if it's worth back porting if it's been there a long time, but I guess it couldn't hurt.
