### ISSUE TITLE
[HLSL] Add Resource "shape" and "ROV" to HLSLResourceAttr

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#57991]
The HLSL Resource attribute currently captures the some of the possible types of resource information, but not all. The attribute should also capture the "Shape" of all resources, and have an optional bool for ROVs.

**Comment by python3kgae** [comment]
shape is done.
Need to ROV next.

**Comment by bogner** [comment]
We'll also need "HasCounter" here. We should check if anything else needs this treatment, but I think things like counts, element type, and stride should already be visible elsewhere in the AST.

**Comment by bogner** [comment]
See #74896

**Comment by bogner** [comment]
This is done as of #74896
