### ISSUE TITLE
[llvm-objcopy] missing support for --gap-fill

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#57995]
This command line flag is being used by u-boot.
https://github.com/u-boot/u-boot/blob/f117c54cc83e3c519883edb5a48062644d38c443/Makefile#L1035
This was briefly mentioned in #55246.

**Comment by asudarsa** [comment]
I think https://github.com/llvm/llvm-project/pull/65815 addresses this. Can we please verify and close? Thanks
