### ISSUE TITLE
Is there a easy way to use c++ objects in IR?

### ISSUE THREAD

**Issue by vifird** [llvm/llvm-project#58]
Thanks for paying attention to my question.

I am developing a new JIT VM, the language is like JavaScript, When i started to design JavaScript's `Object`, i found it's hard to design by hand. And i think `std::map` may be helpful to implement it, i just need to write its header file's IR code, and then link them while running.
But soon i found that the number of its header file' IR code is also huge, i don't know how to use it. The same question happens with `std::list` object.

So, is there a easy way to use c++ object(such as `std::map`, `std::list`) in my new language? Using it directly while building IR? Or using ready-made IR of their header files?

**Comment by gwelymernans** [comment]
To clarify, you want to have `std::map/list` available for your language, but only at the IR level?

If all you need is the functionality of those objects, then you could implement them in whatever language is convenient for you, compile to a library, and use the library with your JIT.

**Comment by vifird** [comment]
@gwelymernans Thanks. I got it.
