### ISSUE TITLE
[HLSL] Move Frontend metadata utilities to libLLVMFrontendHLSL

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#58000]
It will make everyone's lives easier if we can share some code between the backend and frontend for IR and metadata generation. We should be able to move some code out of the frontend and DirectX target into a new libLLVMFrontendHLSL following the pattern used by OpenMP.

**Comment by tschuett** [comment]
MLIR-Clang might also be interested eventually.

**Comment by llvm-beanz** [comment]
Out for review: https://reviews.llvm.org/D135110
