### ISSUE TITLE
Rebuild of lldb-15.0.0 fails with SWIG 4.1.0

### ISSUE THREAD

**Issue by jplesnik** [llvm/llvm-project#58018]
I am testing rebuild of SWIG dependencies with upcoming SWIG 4.1.0 on Fedora Rawhide (Fedora 38).
I found out that rebuild of lldb-15.0.0 fails with this version. 

There are two things which need to be fixed. I reported both issue to Fedora maintainer [BZ#2128646](https://bugzilla.redhat.com/show_bug.cgi?id=2128646). The report contains patches for the issues. The patches are backwards compatible with older versions of SWIG.

**Comment by labath** [comment]
Could you post the patches to the llvm review website (https://reviews.llvm.org/) as well?

**Comment by DavidSpickett** [comment]
Thanks for the early warning. Are you able to submit those patches to llvm yourself? https://llvm.org/docs/Contributing.html#how-to-submit-a-patch

**Comment by serge-sans-paille** [comment]
Patch submitted there: https://reviews.llvm.org/D134877

**Comment by serge-sans-paille** [comment]
Patch commited as https://github.com/llvm/llvm-project/commit/f0a25fe0b746f56295d5c02116ba28d2f965c175 and https://github.com/llvm/llvm-project/commit/81fc5f7909a4ef5a8d4b5da2a10f77f7cb01ba63
