### ISSUE TITLE
[clang-format] AllowBreakingBinaryOperators needed

### ISSUE THREAD

**Issue by Kikadass** [llvm/llvm-project#58014]
I have been searching for this for a long time just to fine large number of people asking for this on StackOverflow and other websites, but I couldn't find a ticket on GitHub actually asking for it. 
Some related StackOverflow questions:
https://stackoverflow.com/questions/50842271/clang-format-stack-all-if-statement-arguments-if-they-are-too-long
https://stackoverflow.com/questions/48247489/prevent-clang-format-from-collapsing-multi-line-if-statements-into-a-single-line

The concept is pretty simple.
We need a Style option for the following to stay as it is. It would be ideal if it also allows it fro parameters setting and other situations where other operands are found instead of just `||` and `&&`, but the minimum would be for those two. 

```c
if( ma[index - 1] > threshold_high
 || ma[index + 1] > threshold_high
 || ma[index - cols] > threshold_high
 || ma[index + cols] > threshold_high
 || ma[index - 1 - cols] > threshold_high
 || ma[index - 1 + cols] > threshold_high
 || ma[index + 1 - cols] > threshold_high
 || ma[index + 1 + cols] > threshold_high )
```

Ideas for naming:
`AllowBreakingBinaryOperators` where it just allows this to happen without formatting the previous statement
`AlwaysBreakBinaryOperators` where every time a Binary operator is found it goes to the new line. In this case it is active formatting. (it would interact together with `BreakBeforeBinaryOperators` too choose whether to have the operator before or after the new line)

Please make this happen :)

**Comment by rymiel** [comment]
Related to https://github.com/llvm/llvm-project/issues/57280?

**Comment by Kikadass** [comment]
That is right, it is similar to 58125. 

In the case of 57280, I think that is going into a very niche and specific case whereas my ticket is a bit more useful and generic. With my ticket you would also take care of 5280, but not the other way round. 

So I would suggest closing 57280 and keep this one Open

**Comment by abdelmaged** [comment]
This enhancement is very useful, I'd like this to be added.
Is there any updates about this ?

**Comment by lursyy** [comment]
Not sure if this deserves a separate issue instead: I came here via SO, looking for a way to influence the formatting of C++20 pipeline expressions. There are [some](https://stackoverflow.com/questions/70942638/tweaking-clang-format-for-c20-ranges-pipelines) [posts](https://stackoverflow.com/questions/77174644/pipe-chain-in-clang-format) about it already.

To me, something like
```cpp
const auto results = some_container
    | ranges::views::transform(function1)
    | ranges::views::filter(function2)
    | ranges::views::filter(function3)
    | ranges::to<std::vector<ResultType>>();
```

looks far better than

```cpp
const auto results =
    some_container | ranges::views::transform(function1)
    | ranges::views::filter(function2) | ranges::views::filter(function3)
    | ranges::to<std::vector<ResultType>>();
```

**Comment by Runner-2019** [comment]
> Not sure if this deserves a separate issue instead: I came here via SO, looking for a way to influence the formatting of C++20 pipeline expressions. There are [some](https://stackoverflow.com/questions/70942638/tweaking-clang-format-for-c20-ranges-pipelines) [posts](https://stackoverflow.com/questions/77174644/pipe-chain-in-clang-format) about it already.
> 
> To me, something like
> 
> ```c++
> const auto results = some_container
>     | ranges::views::transform(function1)
>     | ranges::views::filter(function2)
>     | ranges::views::filter(function3)
>     | ranges::to<std::vector<ResultType>>();
> ```
> 
> looks far better than
> 
> ```c++
> const auto results =
>     some_container | ranges::views::transform(function1)
>     | ranges::views::filter(function2) | ranges::views::filter(function3)
>     | ranges::to<std::vector<ResultType>>();
> ```

Is there any progress on this issue?
