### ISSUE TITLE
Crash when looking up zero-width APInt in DenseMap

### ISSUE THREAD

**Issue by mortbopet** [llvm/llvm-project#58013]
To reproduce: performing a lookup of a non-empty DenseMap with a zero-width APInt causes a crash. I expect this to be due to some issues with hashing of the zero-width APInt.

```C++
    DenseMap<APInt, mlir::Value> m;
    m.insert({APInt(1, 1, false), nullptr});
    m.find(APInt(0, 0, false)); // <--- crashes
```

**Comment by Weverything** [comment]
I suspect what is happening is that one of the special map keys is colliding with a valid zero-width APInt.  You can try going to include/llvm/ADT/APInt.h and find `getEmptyKey()` in `DenseMapInfo<APInt, void>`.  Then change `V.U.VAL = 0;` to `V.U.VAL = 2;` to see if it fixes the crash you found.

**Comment by Weverything** [comment]
Proposed fix:
https://reviews.llvm.org/D135741
