### ISSUE TITLE
[MLIR Core] Rename `FunctionOpInterfaces::getBody()`

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#58030]
Both `FunctionOpInterfaces` and `SingleBlockImplicitTerminator` define a `getBody()` method, so having a function like thing with a single block and implicit terminator requires an ugly using decl like this:

```
using mlir::OpTrait::SingleBlockImplicitTerminator<ReturnOp>::Impl<FuncOp>::getBody;
```

It would be really nice to rename FunctionOpInterfaces::getBody to something like `getFunctionBody` to avoid the conflict.

**Comment by jpienaar** [comment]
SingleBlockImplicitTerminator and the like I've been meaning to remove: it's inconsistent specified as trait on the op rather than constraint on region.
