### ISSUE TITLE
[lld] The indentation of this line is not aligned

### ISSUE THREAD

**Issue by KerangM** [llvm/llvm-project#58036]
https://github.com/llvm/llvm-project/blob/3918ef07c4e65c79939020ac209432eeed6a0f4a/lld/ELF/Relocations.cpp#L1424

**Comment by xgupta** [comment]
Hi @KerangM,
Usually, we don't commit a fix for the indentation of a line.

Fixed by https://github.com/llvm/llvm-project/commit/e8e0e5f3eea86e4707279e418f0d40c67109daf9
