### ISSUE TITLE
Problem in Documentation

### ISSUE THREAD

**Issue by cdemirsoy** [llvm/llvm-project#58044]
Dear Developers,

Can someone please explain me the following lines in the _AST Matcher_ documentation? 

https://github.com/llvm-mirror/clang/blob/master/include/clang/ASTMatchers/ASTMatchers.h#L927

I think that somebody has left this here with a typo and it was probably never noticed again. It simply won't compile!

I suppose the keyword **class** is supposed to be replaced with something that makes a conversion to a QualType...

Looking forward to your response!

**Comment by cdemirsoy** [comment]
@EugeneZelenko Hi again, when do you think you could give an update to this?

**Comment by EugeneZelenko** [comment]
@cdemirsoy: Sorry, I mostly label issues. You could try to use https://discourse.llvm.org for questions.

**Comment by AaronBallman** [comment]
I believe what the documentation was aiming for was:
```
classTemplateSpecializationDecl(hasAnyTemplateArgument(refersToType(recordType(hasDeclaration(recordDecl(hasName("X")))))))
```
