### ISSUE TITLE
Cannot inherit `const &` qualified overloads from base class

### ISSUE THREAD

**Issue by h-2** [llvm/llvm-project#58059]
```c++
#include <string>
#include <vector>
#include <concepts>

struct S
{
    int operator()(auto) const &
    {
        return 3;
    }
};

struct S2 : S
{
    using S::operator();

    int operator()(std::integral auto) const &
    {
        return 4;
    }

};


int main()
{
    std::string str = "foo";

    S2 s2;
    s2(str);
}
```

This fails to build, because the base class's overload is not evaluated for the string argument.
Any of the following will make it build:
1. remove the operator in the derived class entirely
2. make the operator non-generic (e.g. replace `std::integral auto` with `int`)
3. remove the `const &` qualification from either the operator in the base class, or the derived class

Tested with clang-15.0.0 and 16.0.0-++20220929042300+b55e76de8bcf-1~exp1~20220929042408.451

The code works in GCC.

**Comment by shafik** [comment]
Note, for those trying to reproduce on godbolt, it looks like we need to use `-stdlib=libc++` in order to get options 1 to 3 to work for you.

**Comment by h-2** [comment]
> Note, for those trying to reproduce on godbolt, it looks like we need to use -stdlib=libc++ in order to get options 1 to 3 to work for you.

Works withuot `-stdlib=libc++` for me as well: [link](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxCBmZqQADqgKhE4MHt6%2BekkpjgJBIeEsUTFxtpj2eQxCBEzEBBk%2BflzllWk1dQQFYZHRsfEKtfWNWS2Dnd1FJf0AlLaoXsTI7BzmAMzByN5YANQma26DxMHA%2B9gmGgCC65vbmHsHaAzLCQQKZxfXV%2BtYNCE7AHllAAVACSANCOw0OwA9DCdiQdlwEcQdmYUTs1p9PkcvA4dkJsQB2KxXHbknYAN1QeHQCIS0SYRGIEBmECYXiIMx2T0GezMADY9iSTESACLEiVrUlfS64/FCdEgAnEmUUnZeFJGAkgECoBnEJkkVn7GU3KiAkHgyH7KViqGfdXU2n0xnM1kQQboXXBAiYYCG2g7DlcnkCPnmIWiqzi7FmNYVPAWoFgiEPO1ox0U510/Vu41s33c3kEflRkWx77xxPJq1p222zFZ8k512G91sr0%2BwT%2BwPBzmobnR0USqsJhj4KiS03Yq6%2BnYsJjBE3fEVkildkBHE47I7p/lmfiocxmGffdfkxW70/S5vXz0EYgzM/XcUcOa0TgAVl4fg4WlIVBODcaxrF3BYlnudYeFIAhNHfOYAGsQC/DR9E4SRf3gwDOF4BQQDQuD/3fUg4FgGBEBQVAWASOhonISg0BouiYi2QxgC4VC0JoWg/WIfCIAibCImCOoAE9OBgpi2EEAEGFoCTiNILBFyMcQlPwYhMAcPBKUwfClMwVRtM5FYYN9CpsNoPAIkNYgxI8LBsMfPAWEkkiqAMYAFAANTwTAAHcAQZP8YP4QQRDEdgpBkQRFBUdQlN0FoDCMFBQMsfQbPwyA5n1KoDIAWi9W1TEsawzAAuxtKqFwJxGZpSECYIemKPoWhyVIBAa7Jki6hhJl6GIxgqGr2iGBpPCaPRqp0gQOnqQa2uG2wJp6sYJqW6YuDmBQIOWPRH0wMySM/Dgf1IP8AKAjhVAADgFQqBUkHlUuAJEvwAOg0b6dggEDysynZcEIRFoNIHYPGY%2BhUWgmZeCIrQZiQlC0LOzDSDc1DLuwm68II2D4LmMjKIWAgEk5BiICY2iYdCVgVnux7np2YBkGQJEzE%2BsxeEwfBmVpPRwuEURxBi4X4rUbDktIALDQSdyP2/LClJugFOQp0tUAtJmnpetjtU477fv%2B6jaeifk1h2hGibmBBMCYLAYlZdCOAxrG0Ku3g8dsAnEYQ0hkOxs61hV67cMJ4jkddnmcdViP/ejvT%2BLSEBJCAA)

**Comment by erichkeane** [comment]
Simplified a bit: https://godbolt.org/z/heh647KKh

``` 
template<typename T>
concept Fails = false;

struct S {
    int operator()(auto) {
        return 3;
    }
};

struct S2 : S {
    using S::operator();
    int operator()(Fails auto) {
        return 4;
    }
};

int main() {
    int i;
    S2 s2;
    return s2(i);
}
```
This only happens if the `operator()`s match qualification, so I suspect the problem is something where the two candidates are actually being treated as the SAME candidate (so the `Fails` version is the only one being checked).

**Comment by h-2** [comment]
Then it does seem like this is the same issue as #58060, so feel free to close either.
