### ISSUE TITLE
MemRefToSPIRV allocation broken for opencl-spirv

### ISSUE THREAD

**Issue by nirvedhmeshram** [llvm/llvm-project#58058]
Instead of allocating a global variable like
```
spirv.GlobalVariable @__workgroup_mem__0 : !spirv.ptr<!spirv.struct<(!spirv.array<20 x f32>)>, Workgroup>
```
if you change environment from shader to kernel you get a dynamic kind of allocation like this
```
spirv.GlobalVariable @__workgroup_mem__0 : !spirv.ptr<f32, Workgroup>
```
This does not play nice with backends as it becomes a scalar allocation rather than an array
To reproduce change Shader to Kernel in any tests in https://github.com/llvm/llvm-project/blob/main/mlir/test/Conversion/MemRefToSPIRV/alloc.mlir

**Comment by antiagainst** [comment]
Thanks for the report! Yes, for static allocations in workgroup memory we should do something like the Vulkan/Shader side. Concretely:

- We should fix the `SPIRVTypeConverter` to account for the difference between static cases and dynamic cases for OpenCL. Largely we can reuse the flow for Vulkan; just don't need the wrapping struct there.
- Ajust `getOpenCLElementPtr` to check the different flows. It can be done by inspecting the `basePtr`'s type to see whether is a pointer to an array or a pointer to an element type. For the former can use `spirv.AccessChain` to index into it; for the later we keep the existing `spirv.PtrAccessChain` way.

**Comment by nirvedhmeshram** [comment]
Regarding
```
 inspecting the basePtr's type to see whether is a pointer to an array or a pointer to an element type
 ```
 can I do this by just checking the rank of the baseType? if rank=0 then points to element type? else points to array?

**Comment by antiagainst** [comment]
For `getOpenCLElementPtr`, `baseType` is the original `memref` type, while `basePtr`'s type is the converted SPIR-V type from `baseType`. Inspecting `baseType` would mean we need to duplicate the logic in `SPIRVTypeConverter` again. It's preferable to check `basePtr`'s type so we can avoid the duplication and let `SPIRVTypeConverter` to be the sole place deciding how to convert different kinds of `memref`s. Something like `basePtr.getType().cast<spirv::PointerType>().getPointeeType().isa<spirv::ArrayType>()` should do the trick there.

**Comment by antiagainst** [comment]
> can I do this by just checking the rank of the baseType? if rank=0 then points to element type? else points to array?

Rank is actually not a good indication there. We can have `memref<?xf32>` converting to a `!spirv.ptr<f32>`, while `memref<4xf32>` can convert to `!spirv.ptr<!spirv.array<4xf32>>`. They are all rank 1.

**Comment by antiagainst** [comment]
This is fixed via https://reviews.llvm.org/D134908. Thanks @nirvedhmeshram!
