### ISSUE TITLE
[HLSL] Gather resource binding information 

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#58051]
Resource binding information is currently recorded only in HLSLResourceBinding attributes on declarations. The binding can be directly on a resource type, but also there may also be multiple register binding on a user defined type that contains multiple resource types. We need to gather all of this explicit resource binding information and create 1:1 mapping of FieldDecl or VarDecl to explicit. HLSLResourceBindingAttr.

Based on this information we can then:
- fill in implicit bindings (llvm/llvm-project#109861)
- generate `createHandleFromBinding` calls for all used resources during CodeGen (llvm/llvm-project#105076).

We should try to share code between the register binding allocation and the [diagnostics for invalid bindings](https://github.com/llvm/llvm-project/issues/57886). A strawman design for sharing the code would probably look something like this:

1. `SemaHLSL::handleResourceBindingAttr` just diagnoses the simple/local errors:
   - `err_hlsl_binding_type_invalid` - the type isn't valid at all, like `x0`
   - `warn_hlsl_deprecated_register_type_i` - the type is deprecated/removed and ignored
   - `warn_hlsl_deprecated_register_type_b` - the type is deprecated/removed and ignored
   - `warn_hlsl_register_type_c_packoffset` - the type is in the wrong place (in a `cbuffer`)
   - `warn_hlsl_overlapping_binding` - the same binding type is applied more than once

   These shouldn't need any traversal of types to diagnose, so keeping them here is simplest.

2. Add a data member, `Bindings`, to `SemaHLSL` to track the ranges that are already bound and the list of `Decl`s that still need to be bound.

3. In `Sema::ActOnVariableDeclarator` (in `SemaDecl.cpp`) after the call to `ProcessDeclAttributes`, call into `SemaHLSL`:
   ```c++ 
   if (getLangOpts().HLSL && NewVD->hasGlobalStorage()) {
       HLSL()->handleBindings(NewVD);
   ```

   This would recursively walk the type similarly to the traversal described in this proposal, but instead of setting flags we'd calculate the size of the UAV, SRV, CBuffer, and Sampler bindings to add to `SemaHLSL::Bindings`.

   If a binding has zero size but we have an attribute for the binding we diagnose a mismatch:
   - `warn_hlsl_binding_type_mismatch` if it's a UDT
   - `err_hlsl_binding_type_mismatch` if it's a simple type

   This is where we would diagnose a new `warn_hlsl_overlapping_binding` if multiple separate things are bound in overlapping places.

3. In `SemaHLSL::ActOnFinishBuffer`, add the binding for the cbuffer/tbuffer as a whole, using the size we calculate for diagnostics already. This will also need to diagnose a couple of things:
   - `err_hlsl_binding_type_mismatch` if it's a simple type
   - `warn_hlsl_overlapping_binding`

   Note that doing this here simplifies the parts of the design that need to differentiate between `HLSLBufferDecl ` and `VarDecl`, since the two code paths are separate. 

4. Later on in Sema (`ActOnEndOfTranslationUnit`?) we walk the list of unbound `Decl`s and assign them bindings (llvm/llvm-project#109861)

**Comment by bogner** [comment]
Note that I did explicitly call this a strawman ;)

Yes, if we were to do this in Sema we definitely have to make some decisions on how to define a "used" resource. I think a reachability based approach is somewhat tenable if we're allocating the resources during `ActOnEndOfTranslationUnit` - we can track which bindings have been "seen" as we go through Sema and filter them out at this point. This is where diagnosis of things like unused private fields happens so it might be feasible, but we'd need to look into it some more.

As for library behaviour, having explicitly unbound resources is probably necessary. We'll probably want to keep track of whether bindings were user provided or compiler generated anyway.

If on the other hand we really want to stick to the "if it happens to be optimized out, then it's unused" model, then this is a lot less practical indeed.

**Comment by damyanp** [comment]
If I ruled the world, I would require explicit bindings on all resources.  I'm having a quick look to see if I can easily look at my collection of shaders to see how common it is for resources not to have an explicit binding.

**Comment by bogner** [comment]
I've broken this up into three separate issues, covering explicit bindings (#110719), implicit (#110722), and non-local overlap diagnostics (#110723). Closing this one as redundant.
