### ISSUE TITLE
C# verbatim, interpolated strings sometimes break

### ISSUE THREAD

**Issue by 3geek14** [llvm/llvm-project#58062]
I have two files that each have a single verbatim, interpolated string:

mwe-good.cs:

    $@"path\to\{specifiedFile}"

mwe-bad.cs

    @$"path\to\{specifiedFile}"

When running `clang-format --style=LLVM mwe-good.cs`, the output is identical to the file (yay!). When running it on `mwe-bad.cs`, the output is different:

    @$ "path\to\{specifiedFile}"

There's an extra space added, which causes compilation errors (when it's a full file and not a MWE). As of C# 8, [both orderings are accepted](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#enhancement-of-interpolated-verbatim-strings).

As a bug report, I'd like the space to no longer be added. As a small feature request, and only if it's easy to implement/maintain, I think it would be nice if clang-format picked an ordering of the two symbols and made verbatim, interpolated strings always use that order.

**Comment by owenca** [comment]
https://reviews.llvm.org/D135026

**Comment by tru** [comment]
@owenca @3geek14 pinged me and asked me to backport this to the release branch. does that make sense to you? how safe is it? We are late in the 15.x release cycle so I am a bit conservative.
