### ISSUE TITLE
Missed optimization inlining malloc

### ISSUE THREAD

**Issue by levodelellis** [llvm/llvm-project#58071]
Below but you can see it in the explorer if you comment out line 11 and uncomment 12 https://godbolt.org/z/YGbTsTf1G

if you compile the below with `clang -O3 -mllvm -attributor-enable=module` you'll get no mallocs/free. Calling an indirect function like mymalloc will inline but no longer optimize out malloc/free

I tried using clang 14.0.6 on linux, 15.0.0 and the assertion trunk on compiler explorer

```
#include <stdio.h>
#include <stdlib.h>

int getValue() { return 1; }

//void*mymalloc(int i) { return malloc(i); }
void*mymalloc(int i) __THROW __attribute_malloc__
     __attribute_alloc_size__ ((1)) __wur { return malloc(i); }

int main(int argc, char *argv[]) {
    char*buf=malloc(16);
	//char*buf=mymalloc(16);
	buf[0] = getValue() + '0';
	buf[1] = 0;
	puts(buf);
	free(buf);
}

```

**Comment by EugeneZelenko** [comment]
Could you please try 15 or `main` branch?

**Comment by levodelellis** [comment]
Does trying it in compiler explorer count? After doing the comment step to cause the problem I switched to "x86-64 clang 15.0.0" and I continue to see the malloc in main

**Comment by jdoerfert** [comment]
Accidentally closed it.

Attributor module pass runs *before* the inliner, Attributor cgscc pass runs *after*. 
Use -attributor-enable=cgscc (or all, I think) to run the latter:
  https://godbolt.org/z/Y5xMrK61c

**Comment by EugeneZelenko** [comment]
@jdoerfert: Should it be reopened?

**Comment by jdoerfert** [comment]
I think the real solution is to mark the myalloc as allocator, see https://discourse.llvm.org/t/optimize-away-memory-allocations/65587/4
