### ISSUE TITLE
[llvm-objdump] support for `--no-addresses`

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#58088]
When diffing disassembly, it's super helpful to not print the address of individual instructions via `--no-addresses` that GNU objdump has.

I like to use `--no-addresses` in conjunction with `--no-show-raw-insn`.

**Comment by MaskRay** [comment]
In 2020-04, I left some comments when objdump added `--no-addresses`: https://sourceware.org/pipermail/binutils/2020-April/110669.html (see the thread). I think llvm-objdump make this option an alias for `--no-leading-addr` for now.

**Comment by MaskRay** [comment]
https://reviews.llvm.org/D135039 and https://reviews.llvm.org/D135040
