### ISSUE TITLE
[Flang] fircg_Dialect should use prefixed accessors

### ISSUE THREAD

**Issue by River707** [llvm/llvm-project#58090]
The raw accessor form for dialects is going away soon, and fircg_Dialect is the only flang dialect that hasn't been flipped (as far as I could tell). The accessors can be flipped by removing the following:

```
  let emitAccessorPrefix = kEmitAccessorPrefix_Raw;
```

and then updating any API changes that come out of that.

**Comment by clementval** [comment]
Patch up for review here: https://reviews.llvm.org/D135061
