### ISSUE TITLE
Clang rejects valid function declaration involving pack expansion

### ISSUE THREAD

**Issue by ranaanoop** [llvm/llvm-project#58099]
The following program is rejected by clang while accepted by gcc. [Demo](https://godbolt.org/z/rvfqzo5YW).

```C++
template<typename T, typename... V> 
struct C 
{
    T v(V()...);;
};
int main()
{
    
    C<int> c; //works with gcc but rejected in clang 
    C<int, double, int, int> c2; //same here: works with gcc but rejected in clang
}
```

**Comment by EugeneZelenko** [comment]
Could you please try 15 or `main` branch?

**Comment by inclyc** [comment]
> Could you please try 15 or `main` branch?

rejected by godbolt trunk

**Comment by HolyBlackCat** [comment]
The code looks ill-formed to me. The correct pack expansion would be `T v(V...());`.

**Comment by inclyc** [comment]
> The code looks ill-formed to me. The correct pack expansion would be `T v(V...());`.

GCC rejects `T v(V...());` https://godbolt.org/z/59E3P7a5d

**Comment by HolyBlackCat** [comment]
@inclyc Which is their bug. I've reported it [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107113). I've linked the relevant parts of the grammar [here](https://stackoverflow.com/a/73920210/2752075).

**Comment by inclyc** [comment]
> @inclyc Which is their bug. I've reported it [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107113). I've linked the relevant parts of the grammar [here](https://stackoverflow.com/a/73920210/2752075).

Thanks!
