### ISSUE TITLE
Document LLVM_TARGETS_TO_BUILD

### ISSUE THREAD

**Issue by dilyanpalauzov** [llvm/llvm-project#58108]
According to https://llvm.org/docs/CMake.html#frequently-used-llvm-related-variables `LLVM_TARGETS_TO_BUILD` can be used to limit the compilation time of LLVM itself and create binaries, which do not support all targets.

The only documented values for LLVM_TARGETS_TO_BUILD are all, X86, and «"X86;PowerPC"».  Within ccmake the documentation suggests only “all” as valid value.

Please extend the documentation of LLVM_TARGETS_TO_BUILD, both within cland and at https://llvm.org/docs/CMake.html, to list all possible values, as this is done for  LLVM_ENABLE_PROJECTS.

**Comment by adeelahmad81299** [comment]
Working on it..

**Comment by adeelahmad81299** [comment]
I want to work on this

**Comment by MaskRay** [comment]
Closed by c3e073bcbdc523b0f758d44a89a6333e38bff863 (https://reviews.llvm.org/D135431)
