### ISSUE TITLE
[clang-format] Add an option to configure C++ attributes

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#58102]
When there are too many attributes, functions tend to get formatted like this:
```cpp
[[attr1, attr2, attr3, attr4]] __keyword_attr constexpr void
f(args...);
```
It'd be nice if this were configurable, so that we could also have
```cpp
// option 1
[[attr1, attr2, attr3, attr4]] __keyword_attr
constexpr void f(args...);

// option 2
[[attr1, attr2, attr3, attr4]]
__keyword_attr constexpr void f(args...);
```

**Comment by rymiel** [comment]
Related: https://github.com/llvm/llvm-project/issues/54265

**Comment by owenca** [comment]
https://reviews.llvm.org/D140956

**Comment by cjdb** [comment]
Thanks for implementing the initial functionality! I think it would be good if there were a mode so that short lines are preserved and long lines are broken (maybe an `IfTooLong` option?). For example, I don't think the `[[nodiscard]]` below should be on its own line.
```cpp
[[nodiscard]] int zero()
{
  return 0;
}
```

**Comment by owenca** [comment]
It's hard to come up with a single measure for what is "short" and what is "long". Would you use the number of attributes, total length, or something else?

I included `Leave` as an option to not change line breaks after attributes and believe that it should work for your example.

**Comment by cjdb** [comment]
Agreed on the hardness issue. I was imagining with simply having the line break happen after one goes over the maximum column length (plus penalty).

> I included `Leave` as an option to not change line breaks after attributes and believe that it should work for your example.

Oooh, thanks for pointing this out! For some reason I'd processed this a bit differently.

**Comment by owenca** [comment]
Np!
