### ISSUE TITLE
likely miscompile of code involving a usub.sat by AArch64 backend

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#58109]
consider this IR:
```llvm
define i64 @i(i8 signext %0) {
  %2 = add i8 %0, 1
  %3 = call i8 @llvm.usub.sat.i8(i8 %2, i8 1)
  %4 = zext i8 %3 to i64
  ret i64 %4
}

; Function Attrs: nocallback nofree nosync nounwind readnone speculatable willreturn
declare i8 @llvm.usub.sat.i8(i8, i8) #0

attributes #0 = { nocallback nofree nosync nounwind readnone speculatable willreturn }
```

if we generate aarch64 and link the result against this driver:
```c
#include <stdio.h>

unsigned long i(unsigned long);

int main(void) {
  printf("%lx\n", i(0xffffffffffffff81));
}
```

we get:
```console
$ ~/llvm-project/for-alive/bin/llc foo.ll
$ ~/llvm-project/for-alive/bin/clang foo.c foo.s
$ ./a.out 
ffffff81
$ 
```

I hope it's clear that (1) the chosen input respects the signext constraint on the argument and (2) a function returning a value that's a zext of an i8 should contain zeroes in all of the bits above the first byte

cc @nunoplopes @ryan-berger @nbushehri @Hatsunespica

**Comment by regehr** [comment]
this is the generated code
```
_i:                         
	add	w8, w0, #1
	subs	w8, w8, #1
	csel	w0, wzr, w8, lo
	ret
```

**Comment by davemgreen** [comment]
I believe the code added in https://github.com/llvm/llvm-project/commit/03c627e8a762ea6edf9aac9095cad775f020c31c is the problem, probably because it is not considering extra uses of the `subs`. It removes an `and w0, w0, 0xff` between the `add` and the `subs`, but doesn't consider that the subs could be an actual sub, not just a cmp.

**Comment by davemgreen** [comment]
https://reviews.llvm.org/D135043

**Comment by davemgreen** [comment]
Thanks for the report - let us know if anything else comes up.
