### ISSUE TITLE
How to debug a truly remote android?

### ISSUE THREAD

**Issue by mark2185** [llvm/llvm-project#58114]
I want to be able to run a process on a truly remote android (connected to a remote server), connect to it via `lldb` and debug C++ code.

My `android device` (let's call it `Ganymede`) is connected to a remote server (`Jupiter`). I can `ssh` to that server from my local PC (codename `Earth`) and create whichever tunnels I need.

I tried running `lldb-server platform --listen "*:54321"` on `Ganymede` as one of the applications on the device (through `adb shell run-as com.company.exerunner.Test ./lldb-server blah`), and I have succeeded in connecting to it from `Jupiter` via:
```
$ ( Jupiter ) > lldb
$ ( Jupiter lldb )> platform select remote-android
$ ( Jupiter lldb )> platform connect connect://localhost:54321
    Triple: aarch64-unknown-linux-android
OS Version: 33 (4.14.276-ge333cb8619d0-ab8811257)
  Hostname: localhost
 Connected: yes
WorkingDir: /data/user/0/com.company.exerunner.Test
    Kernel: #1 SMP PREEMPT Fri Jul 8 12:03:57 UTC 2022
```

But, when I try doing the same through an `ssh` tunnel from `Earth` to `Jupiter`, created with `ssh -L54321:localhost:54321 user@jupiter`, I get `error: failed to connect port`. 

If I've understood correctly `lldb`'s logic behind the scenes, it creates a `gdb-stub` on `Jupiter` (based on [docs](https://lldb.llvm.org/use/remote.html)), on some random free port, and uses `adb` to forward that local port to the port on `Ganymede`. But it forwards from `Jupiter` to the `Ganymede`.

I can verify that through this (I also compiled a debug version of `lldb` and ran it under a debugger and I think that's what it does)
```
$> adb forward --list
0B231JEC202267 tcp:<random-port> tcp:54321
```
That makes sense why won't it work on when I'm `ssh-ing` to `Jupiter`, I need to forward the port `5037` as well, so that `lldb` can talk to the `adb` on the server. And I need to forward that random `gdb-stub` port somehow. 

Based on [the docs](https://lldb.llvm.org/man/lldb-server.html#gdb-server-connections), I can specify the `gdbserver-port` flag to set the `gdbserver` port, instead of it being random (if I understood that part correctly).

So, I run the server with
```
$ (Ganymede) > ./lldb-server platform --listen "*:54321" --gdbserver-port 12345
```

But how do I tell `platform connect` to use that `gdbserver` port instead of spawning a new one?
I have no idea, so I forwarded the port `12345` from `Earth` to `Jupiter`, and used `adb forward tcp:12345 tcp:12345` to forward it from `Jupiter` to `Ganymede`, and tried running `gdb-remote 12345` within `lldb` from `Jupiter` instead.
I get:
```
error: Connection shut down by remote side while waiting for reply to initial handshake packet
```

So, I can't even connect to `Ganymede` from `Jupiter`, where it is physically plugged into, when setting the `gdbserver port` manually. Maybe I'm holding it wrong, I don't know.

I tried using `lldb-server gdbserver` then instead of `lldb-server platform`, straight on `Ganymede`.

```
$ (Ganymede) > lldb-server gdbserver :12345
$ (Jupiter) > adb forward tcp:12345 tcp:12345
$ (Jupiter) > lldb
$( Jupiter-lldb ) > gdb-remote 12345
error: failed to get reply to handshake packet within timeout of 6.0 seconds
```

Tried it as well with `*:12345` to allow connecting from _any_ host (but that's not in the docs so I may be wrong), but no change.

So, my question is - how do I connect to a `lldb-server` on a truly remote `android device`?

**Comment by mark2185** [comment]
Tried the last experiment again (the one with `lldb-server gdbserver`), with a clean, fresh start - and this time it worked, connection from `Jupiter` to `Ganymede` is successful via `gdb-remote 12345`, there are no timeouts. I can attach to a process on the android.

And now I can use `gdb-remote` from `Earth` as well, as long as I forward `-L12345:localhost:12345`.

Why didn't it work the first time? No idea. 

I'll leave this issue open, in case someone has any tips or insights, and keep you posted if it fails again.

**Comment by mark2185** [comment]
Alright, after digging _a bit_ more, I've concluded that there are two different ports that need forwarding.

The first one is just for communicating with the `lldb platform`, and its `server side` is specified by the flag `--listen "*:<fixed-port>"`. Its `client` counterpart, however, is [random](https://github.com/llvm/llvm-project/blob/8a1e069cc479e501b058bdb1a3d961ee6f852c3d/lldb/source/Plugins/Platform/Android/PlatformAndroidRemoteGDBServer.cpp#L183).

And then, after issuing an `attach` command, a local `gdb-stub` and a remote `gdbserver` are created. The server's port can be specified with `--gdbserver-port`, but the client's counterpart is again, you've guessed it, _[random](https://github.com/llvm/llvm-project/blob/8a1e069cc479e501b058bdb1a3d961ee6f852c3d/lldb/source/Plugins/Platform/Android/PlatformAndroidRemoteGDBServer.cpp#L183)._ (yes, it's the same link as above)

Here's a hopefully helpful illustration.
![image](https://user-images.githubusercontent.com/8365241/196864759-49ac237b-da88-43bc-9229-477c219c3f1f.png)

After fixating those two through a patch and forwarding them through `ssh`, I can finally connect to a truly remote android device via `platform connect`.
After issuing the `attach` command, all the necessary libraries are loaded up and I can set breakpoints and they'll get hit as one would expect.

So, my _newest_ question is - is it possible to do the same using the `lldb-server gdbserver` option? 

Just a reminder - I can connect to it and attach to a process (either through specifying the `PID` when launching the server, or attaching directly through the `lldb` client), but it doesn't load up any libraries, as opposed to the `platform connect` approach where its subsequent `attach` loads up everything that is needed.

**Comment by DavidSpickett** [comment]
> but the client's counterpart is again, you've guessed it, [random](https://github.com/llvm/llvm-project/blob/8a1e069cc479e501b058bdb1a3d961ee6f852c3d/lldb/source/Plugins/Platform/Android/PlatformAndroidRemoteGDBServer.cpp#L183).

I can't answer your questions but I can sympathise here. I hit this trying to connect to a remote qemu where only specific ports were forwarded and "solved" it by some IP tables magic to just map them all.

I respect the effort you're going to though, would you be interested in contributing a guide? (once you have solved the mystery)

I don't know much about Android myself and seemingly few in the community do, so there is clearly a need for this info. I will read through this all again and see if I can help any.

**Comment by mark2185** [comment]
> I can't answer your questions but I can sympathise here. I hit this trying to connect to a remote qemu where only specific ports were forwarded and "solved" it by some IP tables magic to just map them all.
> 
> **I respect the effort** 

I've stumbled upon your name a handful of times during this adventure so that means a lot coming from you! Thanks! :^)

> would you be interested in contributing a guide? (once you have solved the mystery)

I'm willing to submit a guide with the corresponding patch for `lldb` since it's a bit silly that one can configure _remote_ `platform` and `gdbserver` ports, but not their _local_ equivalents. It's just that currently it's a hack since I'm just prototyping (and the prototype seems to work), and I need to make it make sense, but Rome wasn't built in a day so here we are.

> I don't know much about Android myself and seemingly few in the community do, so there is clearly a need for this info. I will read through this all again and see if I can help any.

Even if you don't find the time to read it all, thanks for letting me know I'm not talking to myself!

Now that I have this working prototype, I'm looking into how to make Android Studio work in the same situation as well, but so far it seems I've hit a closed (source) door. But I'll definitely keep knocking.

**Comment by mark2185** [comment]
In short, there are two _local_ ports (local to the device the server is launched on, in this case an android device) one can specify when launching `lldb-server`.

Let's say we're running `lldb-server platform --listen "*:5555" --gdbserver-port 7777`
- `--listen "*:<port>"` specifies the port the `platform` on the device will listen on (`5555` in this case)
- `--gdbserver-port` specifies the port the `gdbserver` on the device will listen on (`7777` in this case)

And when trying to connect to said `lldb-server`, the _local_ (local to the device on is running `lldb` from, in this case a personal computer) ports are random, **unless** one defines the variables `ANDROID_PLATFORM_LOCAL_PORT` and `ANDROID_PLATFORM_LOCAL_GDB_PORT` for the _local_ `platform` and `gdb-stub` ports.

Let's say one sets them to `1234` and `22222` respectively.

Now when running `lldb` and in it connecting to a platform via `platform connect connect://127.0.0.1:5555`, we should see that the local port `1234` is being forwarded to the device's port `5555` when running `adb forward --list`.
And when running `attach <PID>`, we'll see that the local port `22222` is forwarded to the device's port `7777`.
