### ISSUE TITLE
Exceptions crash after calling freeMachineCodeForFunction()

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5811]
|  |  |
| --- | --- |
| Bugzilla Link | [5439](https://llvm.org/bz5439) |
| Version | trunk |
| OS | MacOS X |
| Attachments | [Example application to demonstrate crash](https://user-images.githubusercontent.com/60944935/143740210-a0154b9f-d1b5-4b58-9348-092795f35224.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Hi all,

we're facing a problem when enabling exception handling in JIT and calling ExecutionEngine::freeMachineCodeForFunction(). If an exception is thrown afterwards anywhere in the application (outside of llvm), the whole application crashes.

As far as I can see this is due to an exception frame being registered in JITEmitter::finishFunction() which is not (and currently cannot) be unregistered when the function is freed again.

I've attached a small test program that demonstrates the problem. It needs to be compiled with "make REQUIRES_EH=1". If run without arguments (i.e. no exception handling enabled in JIT), all is fine. If argument "-enable-eh" is used, the test application crashes once the exception is thrown.

Note: A workaround for this problem seems to be to throw and catch a dummy exception before instantiating the execution engine. However, in the project I'm working on the whole llvm code is used in a shared library which may be loaded and unloaded several times during the runtime of the application. In this case the workaround fails.

All tests were done on OS X  10.5.8, using llvm trunk rev. 86536 and llvm 2.6.

Kind regards,

Oliver Schwartz

**Comment by gwelymernans** [comment]
Exception handling changed dramatically since this bug. Also, the `freeMachineCodeForFunction` function no longer exists. If this is still an issue, please file a new bug.
