### ISSUE TITLE
[SimpleLoopUnswitch] Missed Opportunity to unswitch

### ISSUE THREAD

**Issue by barakgla** [llvm/llvm-project#58122]
The code :  [Missed Opportunity to unswitch](https://godbolt.org/z/4xv5Edb85)

If I compiled the code with trunk clang (clang -O3 -emit-llvm) I get the below if-condition is not unswitched although it is looked profitable to unswitch in this case : 
`if(size >= size_z)
      val = 256;`

If I compiled the code with older version of Clang(14.0.0) and with the legacy PM I got that the code is unswitched.

I know the legacy PM did used the LoopUnswitch as default where in new PM there is only the SimpleLoopUnswitch.

In this case , I think problem is the SimpleLoopUnswitch doesn't even try to unswitch SelectInst like the instruction : 
`%15 = select i1 %7, i32 %14, i32 64`
where this is not the terminator of the basic block.
The original LoopUnswitch on the other hand did try to unswitch the SelectInst instructions within the basic block even if those instructions aren't terminators.

**Comment by caojoshua** [comment]
fix in https://reviews.llvm.org/D138526

**Comment by caojoshua** [comment]
This was fixed at some point. See https://godbolt.org/z/Kbe3cq6fj. Clang 14 and trunk have the same behavior, but Clang 15 does not unswitch.
