### ISSUE TITLE
Assertion `!isInvalid() && "Loop not in a valid state!"' failed. with opt -verify-scev

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#58136]
llvm commit: 7ec6dde83ae6
Reproduce with: ```opt -passes="loop-mssa(loop-simplifycfg,require<iv-users>,licm<allowspeculation>,simple-loop-unswitch<nontrivial;trivial>)" bbi-74333.ll -S -o /dev/null -verify-scev```
Result:
```
opt: ../include/llvm/Analysis/LoopInfo.h:149: bool llvm::LoopBase<llvm::BasicBlock, llvm::Loop>::contains(const BlockT *) const [BlockT = llvm::BasicBlock, LoopT = llvm::Loop]: Assertion `!isInvalid() && "Loop not in a valid state!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ../../main-github/llvm/build-all/bin/opt -passes=loop-mssa(loop-simplifycfg,require<iv-users>,licm<allowspeculation>,simple-loop-unswitch<nontrivial;trivial>) bbi-74333.ll -S -o /dev/null -verify-scev
 #0 0x0000000002e5ad33 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (../../main-github/llvm/build-all/bin/opt+0x2e5ad33)
 #1 0x0000000002e58a4e llvm::sys::RunSignalHandlers() (../../main-github/llvm/build-all/bin/opt+0x2e58a4e)
 #2 0x0000000002e5b0b6 SignalHandler(int) (../../main-github/llvm/build-all/bin/opt+0x2e5b0b6)
 #3 0x00007f4de7d06630 __restore_rt (/lib64/libpthread.so.0+0xf630)
 #4 0x00007f4de544d387 raise (/lib64/libc.so.6+0x36387)
 #5 0x00007f4de544ea78 abort (/lib64/libc.so.6+0x37a78)
 #6 0x00007f4de54461a6 __assert_fail_base (/lib64/libc.so.6+0x2f1a6)
 #7 0x00007f4de5446252 (/lib64/libc.so.6+0x2f252)
 #8 0x0000000001e85b31 (../../main-github/llvm/build-all/bin/opt+0x1e85b31)
 #9 0x0000000001e84741 llvm::ScalarEvolution::getLoopDisposition(llvm::SCEV const*, llvm::Loop const*) (../../main-github/llvm/build-all/bin/opt+0x1e84741)
#10 0x0000000001e89139 llvm::ScalarEvolution::verify() const (../../main-github/llvm/build-all/bin/opt+0x1e89139)
#11 0x00000000037e687b llvm::FunctionToLoopPassAdaptor::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (../../main-github/llvm/build-all/bin/opt+0x37e687b)
#12 0x00000000031c4acd llvm::detail::PassModel<llvm::Function, llvm::FunctionToLoopPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (../../main-github/llvm/build-all/bin/opt+0x31c4acd)
#13 0x000000000263ef5c llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (../../main-github/llvm/build-all/bin/opt+0x263ef5c)
#14 0x0000000000ae661d llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function> >, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (../../main-github/llvm/build-all/bin/opt+0xae661d)
#15 0x000000000264323e llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (../../main-github/llvm/build-all/bin/opt+0x264323e)
#16 0x0000000000ae63fd llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (../../main-github/llvm/build-all/bin/opt+0xae63fd)
#17 0x000000000263e20c llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (../../main-github/llvm/build-all/bin/opt+0x263e20c)
#18 0x000000000071ffa0 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::StringRef>, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool) (../../main-github/llvm/build-all/bin/opt+0x71ffa0)
#19 0x0000000000732371 main (../../main-github/llvm/build-all/bin/opt+0x732371)
#20 0x00007f4de5439555 __libc_start_main (/lib64/libc.so.6+0x22555)
#21 0x0000000000718590 _start (../../main-github/llvm/build-all/bin/opt+0x718590)
Abort
```
[bbi-74333.ll.gz](https://github.com/llvm/llvm-project/files/9703351/bbi-74333.ll.gz)

**Comment by mikaelholmen** [comment]
This starts happening with commit 8ae0d9aa072:
```
[LoopDeletion] Clear block & loop dispo cache after breaking backedge.

breakLoopBackedge may remove blocks and loops. Also clear block &
loop disposition to avoid the cache containing invalid blocks and loops.

The coverage for the change is provided when using an ASAN build of opt
to run the LoopDeletion unit tests; without the fix, pointers to invalid
objects would be used.

Reviewed By: nikic

Differential Revision: https://reviews.llvm.org/D134663```

**Comment by fhahn** [comment]
Thanks for the report! Should be fixed. I expect there may be other places where we miss invalidation and that need similar fixes.

**Comment by mikaelholmen** [comment]
Thanks!

**Comment by mikaelholmen** [comment]
> Thanks for the report! Should be fixed. I expect there may be other places where we miss invalidation and that need similar fixes.

Seems like it. I ran more tests with -verify-scev and wrote
 https://github.com/llvm/llvm-project/issues/58158

**Comment by mikaelholmen** [comment]
And this: https://github.com/llvm/llvm-project/issues/58159

**Comment by fhahn** [comment]
Great, thanks for the additional test cases! Should be fixed.

**Comment by mikaelholmen** [comment]
> Great, thanks for the additional test cases! Should be fixed.

Yes, thanks!
I'll continue with more tests with -verify-scev to see if we can find some more.

**Comment by mikaelholmen** [comment]
Another one: https://github.com/llvm/llvm-project/issues/58179

**Comment by fhahn** [comment]
> Another one: https://github.com/llvm/llvm-project/issues/58179

Thanks, please keep them coming!

**Comment by mikaelholmen** [comment]
This one doesn't hit the same error as the other ones above, but at least it's a failure with -verify-scev:
 https://github.com/llvm/llvm-project/issues/58262

**Comment by fhahn** [comment]
> This one doesn't hit the same error as the other ones above, but at least it's a failure with -verify-scev:
> #58262

Yeah that's exactly what the verifier should catch.

**Comment by fhahn** [comment]
@mikaelholmen there's a check in the SCEV verifier, please let me know if you find any other issues!

**Comment by mikaelholmen** [comment]
Another: https://github.com/llvm/llvm-project/issues/58291

**Comment by mikaelholmen** [comment]
And: https://github.com/llvm/llvm-project/issues/58314

I'm wondering, how serious are these bugs? Could there be miscompiles?

**Comment by fhahn** [comment]
> I'm wondering, how serious are these bugs? Could there be miscompiles?

The SCEV verifier failures surface incorrectly cached values, which could result in miscompiles. The verifier has recently been extended to check the block and loop disposition caches, after incorrectly cached values in both have caused mis-compiles.

**Comment by mikaelholmen** [comment]
> > I'm wondering, how serious are these bugs? Could there be miscompiles?
> 
> The SCEV verifier failures surface incorrectly cached values, which could result in miscompiles. The verifier has recently been extended to check the block and loop disposition caches, after incorrectly cached values in both have caused mis-compiles.

Ok, thanks. Then I'll continue running with -verify-scev and report what I find.

**Comment by mikaelholmen** [comment]
Another one here: https://github.com/llvm/llvm-project/issues/58439

**Comment by mikaelholmen** [comment]
And: https://github.com/llvm/llvm-project/issues/58440

No idea #58439 and #58440 are actually the same problem or not.

**Comment by fhahn** [comment]
Thanks again, they were both different issues.

**Comment by mikaelholmen** [comment]
Another: https://github.com/llvm/llvm-project/issues/58489

**Comment by mikaelholmen** [comment]
And: https://github.com/llvm/llvm-project/issues/58515

**Comment by mikaelholmen** [comment]
Another week, another failure: https://github.com/llvm/llvm-project/issues/58564

**Comment by mikaelholmen** [comment]
Another: https://github.com/llvm/llvm-project/issues/58702

**Comment by mikaelholmen** [comment]
https://github.com/llvm/llvm-project/issues/58750

**Comment by mikaelholmen** [comment]
https://github.com/llvm/llvm-project/issues/58751

**Comment by mikaelholmen** [comment]
Cool! I think all the above issues are fixed now.

The only open problem I'm currently aware of with -verify-scev is
 https://github.com/llvm/llvm-project/issues/55689

I'll continue running and see if something more shows up.

**Comment by mikaelholmen** [comment]
https://github.com/llvm/llvm-project/issues/58865

**Comment by fhahn** [comment]
> Cool! I think all the above issues are fixed now.


Thanks for all the test cases! Looking forward to any other issues the additional verification surfaces!

**Comment by mikaelholmen** [comment]
Ok, this looks pretty good now. I saw three different cases of https://github.com/llvm/llvm-project/issues/55689 in my weekend testing but nothing else.

**Comment by mikaelholmen** [comment]
It's been a while but here is a new one:
 https://github.com/llvm/llvm-project/issues/59534

**Comment by mikaelholmen** [comment]
Another here: https://github.com/llvm/llvm-project/issues/68182
