### ISSUE TITLE
libcxx/test/std/utilities/format/format.functions/format_to_n.locale.pass.cpp very slow to compile

### ISSUE THREAD

**Issue by arichardson** [llvm/llvm-project#58141]
I am trying to run the libc++ test suite (using a release+assertions clang) with a 120 second timeout per test and this test times out. It takes a very long time to compile (about two minutes): `libcxx/test/std/utilities/format/format.functions/format_to_n.locale.pass.cpp`

I am not sure if this is a clang frontend/codegen performance issue or a problem with the way the test is written: Running the compilation command with -ftime-trace=foo.json shows that a bit over 1 minute is spent in the frontend (almost all of that inside InstantiateFunction) and almost one minute in the backend.

**Comment by mordante** [comment]
I've noticed this too. There is a different approach to write these test which I want to test. If that doesn't help I want to reduce the number of tests in this file.

**Comment by mordante** [comment]
https://reviews.llvm.org/D135288 improves the speed a bit, but there I still want to make further improvements.

**Comment by mordante** [comment]
https://reviews.llvm.org/D140115 did more improvements. For now I consider this done. Removing more would lower the test coverage.
