### ISSUE TITLE
Backport "[LoopVersioning,LLE] Clear LoopAccessInfoManager after making changes." to 15.x

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#58152]
This fixes the rest of #57825.

**Comment by nikic** [comment]
This is only the last patch of a larger patch stack, and I don't think we can backport the primary change for ABI compatibility reasons.

Is it possible to revert 20d798bd47ec5191de1b2a8a031da06a04e612e1 from the release branch instead? It seems to have caused many different issues.

cc @fhahn

**Comment by fhahn** [comment]
Sure, reverting  https://github.com/llvm/llvm-project/commit/20d798bd47ec5191de1b2a8a031da06a04e612e1  for the release branch makes sense.

**Comment by fhahn** [comment]
@mstorsjo would you mind updating your PR to do the revert?

**Comment by mstorsjo** [comment]
> @mstorsjo would you mind updating your PR to do the revert?

I tried reverting that commit on the release/15.x branch, but when I run `check-llvm` on it, it fails the `Transforms/LoopVectorize/create-induction-resume.ll` testcase. That testcase stems from 8f891b7c391e3a233373cc02c38be5d90e9b27d9 (which came after 20d798bd47ec5191de1b2a8a031da06a04e612e1) - should that commit be reverted too?

**Comment by tru** [comment]
/branch mstorsjo/llvm-project/revert-scev

(rebase)
