### ISSUE TITLE
Segfault when calling LLVMBuildICmp / LLVMBuildFCmp

### ISSUE THREAD

**Issue by vanelk** [llvm/llvm-project#58153]
I am currently building a compiler and using the LLVM C API  when I call LLVMBuildICmp or LLVMBuildFCmp on any value it causes me to get a segfault. I first thought I got the wrong opcodes/predicates so I tested with LLVMConstICmp and LLVMConstFCmp and they work perfectly. The issue is I cannot use LLVMConst functions on variables. I debugged the segfault and all seem to it crashes in the function. `llvm::Constant::isNullValue()` and `llvm::APFloat::Storage::Storage(llvm::detail::IEEEFloat, llvm::fltSemantics const&)` for my ints and floats respectively. I would be grateful for any help.

**Comment by EugeneZelenko** [comment]
Please use https://discourse.llvm.org for questions.
