### ISSUE TITLE
Get variable names from the llvm code

### ISSUE THREAD

**Issue by tareq97** [llvm/llvm-project#58162]
Hi,

I would like to know if I can get variable names of the source code in llvm pass Would also like to know how llvm pass is storing the variable name information while executing the llvm bitcode symbolically.

For example : From the below C code I want to get the buffer variable name is it possible or not.

int main(int argc, char *argv[])
{
       char *buffer = malloc(5);
       buffer[6] = 'a';
       return 0;
}

**Comment by fhahn** [comment]
Please use https://discourse.llvm.org for questions on how to use LLVM.
