### ISSUE TITLE
[Clang] improve diagnostics of -Wframe-larger-than=

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#58168]
When encountering an instance of `-Wframe-larger-than=`, it can be tricky to know which variables from which function are larger than the rest.  Due to inlining, some of the largest variables may have been from an inlined function, which may not be immediately obvious when browsing the source of the function that produced the diagnostic.

The way I debug these is to rebuild with debug info, then either use a hacky+broken [script I wrote](https://github.com/ClangBuiltLinux/frame-larger-than) or `llvm-dwarfdump` to try to understand the size of variables within the frame.  Dumping the IR then running `llc` and observing the output of prolog+epilog insertion can also lead to clues.

@ilovepi and I were discussing this. Perhaps the diagnostic could provide more info to track down the causes of these warnings?  I suspect we may have lost the identifier used in the sources at the point we generate the diagnostic.

**Comment by ilovepi** [comment]
quick prototype here: https://reviews.llvm.org/D135488. That would absolutely need a rewrite, but I think that style of output or dumping to a graphviz file is doable.

When the warning is emitted, MachineFrameInfo still has access to all of the stack slot information, and, when available, debug information. 

While that's a good detailed way to examine the stack, for the purpose of the diagnostic, what if we printed the largest slot size (or maybe the N largest)? That probably isn't a controversial change to the diag's default behavior, and we can enable dumping the frame layout through an additional flag.
