### ISSUE TITLE
[AMDGPU][GFX8+] Incorrect src1 handling for v_cmpx_class_f16, v_cmp_class_f16, v_ldexp_f16

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#58167]
GFX8+ hardware incorrectly handles floating-point inline constants when they are used with 16-bit integer operands. We have a patch to workaround the issue: https://reviews.llvm.org/D81841.

However, opcodes `v_cmpx_class_f16`, `v_cmp_class_f16` and `v_ldexp_f16` are an exception. These opcodes have 16-bit integer `src1` operand but hardware treats this operand as if it has f16 type.

Currently, `src1` is handled incorrectly by the compiler. The operand either has a wrong type or it is affected by the patch (though it should not be).

**Comment by jwanggit86** [comment]
@dpreobra Could you pls provide an example? Thanks!

**Comment by arsenm** [comment]
I think @shiltian fixed this?

**Comment by dpreobra** [comment]
The issue is not reproducible in the latest build. I think it has been fixed.
