### ISSUE TITLE
Optimized code quality for horizontal add worse after ab9a81f

### ISSUE THREAD

**Issue by dyung** [llvm/llvm-project#58177]
We have some internal tests which attempt to verify that the compiler is generating horizontal adds for various code constructs. After commit ab9a81f736acfb927b0e0b4f0de8710fc2379f70 it was noticed that one such pattern was not generating what we were expecting. Consider the following code:
```c++
#include <x86intrin.h>

__attribute__((noinline))
__m256d add_pd_001(__m256d a, __m256d b) {
  __m256d r = (__m256d){ a[0] + a[1], a[2] + a[3], b[0] + b[1], b[2] + b[3] };
  return __builtin_shufflevector(r, a, -1, 1, 2, 3);
}
```
If we compile this with optimizations targeting btver2 (`clang -O2 -S -march=btver2`) using a compiler without ab9a81f736acfb927b0e0b4f0de8710fc2379f70, the compiler generates the following assembly for the function:
```asm
        vperm2f128      ymm0, ymm0, ymm1, 49
        vinsertf128     ymm1, ymm1, xmm1, 1
        vhaddpd ymm0, ymm1, ymm0
        ret
```
Note the use of a single vhadd instruction along with the ymm registers.

However, if we generate the same assembly with the same options for the function using a compiler that includes ab9a81f736acfb927b0e0b4f0de8710fc2379f70, the compiler now generates the function like this:
```asm
        vextractf128    xmm0, ymm0, 1
        vhaddpd xmm0, xmm1, xmm0
        vextractf128    xmm1, ymm1, 1
        vhaddpd xmm1, xmm1, xmm1
        vinsertf128     ymm0, ymm0, xmm0, 1
        vextractf128    xmm2, ymm0, 1
        vblendpd        xmm1, xmm1, xmm2, 1
        vinsertf128     ymm0, ymm0, xmm1, 1
        ret
```

**Comment by alexey-bataev** [comment]
Fixed in 1be3428ea05c
