### ISSUE TITLE
Add optimization remarks for likelihood attribute disagreements

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#58187]
C++20 added the `[[likely]]` and `[[unlikely]]` attributes as optimization hints. Some users expect these hints to be an escape hatch that instructs the optimizer to ignore what it thinks it knows about a particular branch probability. Other users expect these hints to be ignored when the optimizer has more information about the probability of taking a branch (such as through PGO).

It would be nice to have optimization remarks issued for any situation where the optimizer elects to ignore an explicitly-annotated branch so that users have some way to know if their expectations are being met or not.

**Comment by ilovepi** [comment]
@AaronBallman we already have `-Wmisexpect` and `-Rpass=misexpect`, does that cover this use-case?  https://clang.llvm.org/docs/MisExpect.html

IIRC the current behavior between Frontend/Sampling and IR profiles differ in how they handle adding branch weights, if they already exist. Both Sampling and Frontend instrumentation will not update the branch weights if they are present, but IR based instrumentation will always take what is in the profile. 

https://github.com/llvm/llvm-project/blob/4c3d7bc210f04788e5200830ab68f97e8e341cec/llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp#L2313

https://github.com/llvm/llvm-project/blob/4c3d7bc210f04788e5200830ab68f97e8e341cec/llvm/lib/Transforms/IPO/SampleProfile.cpp#L1746

**Comment by AaronBallman** [comment]
@ilovepi -- thank you for pointing that out! It sure looks like this covers the concern I had. It doesn't seem to diagnose situations where the marking and the code are just in disagreement: https://godbolt.org/z/f99T5sdMb but it does seem to at least bark about PGO disagreeing with the marking which is the important bit.

I think I'm comfortable closing this issue as being resolved. Thank you!
