### ISSUE TITLE
[Flang][OpenMP] Reduction support for arrays

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#58186]
Support reduction of arrays in Flang. 

Check: Does OpenMP MLIR dialect or lowering need an extension for this?

```f90
subroutine reduction_array(y)
  integer :: x(100), y(100,100)
  !$omp parallel
  !$omp do reduction(+:x)
  do i=1, 100
    x = x + y(:,i)
  end do
  !$omp end do
  !$omp end parallel
  print *, x
end subroutine
```

**Comment by tblah** [comment]
Reduction support for some array reductions landed here https://github.com/llvm/llvm-project/pull/84958

Arrays with dynamic shape and allocatable arrays will follow in later patches.
