### ISSUE TITLE
[clang++] Clang-15 vs Clang-14 local static init guards

### ISSUE THREAD

**Issue by esky-software** [llvm/llvm-project#58184]
I'm using Clang++ to compile for a Cortex-M0+ target, and in moving from version 14 to version 15 I've found a difference in the code generated for guard variables for local statics.

So, for example:
```cpp
int main()
{
    static knl::QueueN<uint32_t, 8> valQueue;
    ...
}
```
Clang-14 generates the following:
```asm
ldr r0, .LCPI0_4
ldrb    r0, [r0]
dmb sy
lsls    r0, r0, #31
beq .LBB0_8
```
Clang-15 now generates:
```asm
ldr r0, .LCPI0_4
movs    r1, #2
bl  __atomic_load_1
lsls    r0, r0, #31
beq .LBB0_8
```

An important consequence of this is that the second case actually requires an implementation of `__atomic_load_1` to be provided from somewhere external to the compiler (e.g. `-latomic`?), whereas the first doesn't.  

Note that the source code doesn't explicitly use atomics, only the implied usage by the statics (which can of course be disabled with `-fno-threadsafe-statics`).

**Comment by eskimo-software** [comment]
See https://godbolt.org/z/KeE19sPb6

**Comment by eskimo-software** [comment]
I'm linking to the standard libraries provided with the [ARM GNU Toolchain](https://developer.arm.com/Tools%20and%20Software/GNU%20Toolchain) version 11.3, which it turns out provides an implementation of `__cxa_guard_acquire` that doesn't even use barrier instructions:

```
2000ea10 <__cxa_guard_acquire>:
__cxa_guard_acquire():
/data/jenkins/workspace/GNU-toolchain/arm-11/src/gcc/libstdc++-v3/libsupc++/guard.cc:232
2000ea10:	2301      	movs	r3, #1
2000ea12:	6802      	ldr	r2, [r0, #0]
2000ea14:	421a      	tst	r2, r3
2000ea16:	d106      	bne.n	2000ea26 <__cxa_guard_acquire+0x16>
/data/jenkins/workspace/GNU-toolchain/arm-11/src/gcc/libstdc++-v3/libsupc++/guard.cc:235
2000ea18:	7842      	ldrb	r2, [r0, #1]
2000ea1a:	2a00      	cmp	r2, #0
2000ea1c:	d000      	beq.n	2000ea20 <__cxa_guard_acquire+0x10>
/data/jenkins/workspace/GNU-toolchain/arm-11/src/gcc/libstdc++-v3/libsupc++/guard.cc:222
2000ea1e:	deff      	udf	#255	; 0xff
/data/jenkins/workspace/GNU-toolchain/arm-11/src/gcc/libstdc++-v3/libsupc++/guard.cc:213
2000ea20:	7043      	strb	r3, [r0, #1]
/data/jenkins/workspace/GNU-toolchain/arm-11/src/gcc/libstdc++-v3/libsupc++/guard.cc:239
2000ea22:	0018      	movs	r0, r3
/data/jenkins/workspace/GNU-toolchain/arm-11/src/gcc/libstdc++-v3/libsupc++/guard.cc:363
2000ea24:	4770      	bx	lr
/data/jenkins/workspace/GNU-toolchain/arm-11/src/gcc/libstdc++-v3/libsupc++/guard.cc:233
2000ea26:	2000      	movs	r0, #0
/data/jenkins/workspace/GNU-toolchain/arm-11/src/gcc/libstdc++-v3/libsupc++/guard.cc:362
2000ea28:	e7fc      	b.n	2000ea24 <__cxa_guard_acquire+0x14>
```

In contrast with the Clang implementation that seems to use an inline fast check before calling it, the GCC static initialisation code just calls `__cxa_guard_acquire` directly, so a compiler-generated atomic load doesn't even come into it:

```
	static Fred fred = CreateFred();
20003e0a:	4d50      	ldr	r5, [pc, #320]	; (20003f4c <main+0x154>)
20003e0c:	0028      	movs	r0, r5
20003e0e:	f00a fdff 	bl	2000ea10 <__cxa_guard_acquire>
20003e12:	2800      	cmp	r0, #0
20003e14:	d012      	beq.n	20003e3c <main+0x44>
	<... call CreateFred()>
```

**Comment by efriedma-quic** [comment]
> In contrast with the Clang implementation that seems to use an inline fast check before calling it, the GCC static initialisation code just calls __cxa_guard_acquire directly

That's actually a good way to avoid the issue.  Hadn't thought of that.  (The fast path is usually a worthwhile optimization, but if it involves a call, it isn't worth it.)

**Comment by pcordes** [comment]
This seems like a big pessimization, especially for single-core Cortex-M0+ systems which I think are relatively common for that core(?). Uniprocessor makes memory reordering impossible.  (All code runs on the same core, which guarantees that it observes its own operations in program order.)

Do we want a `-mcpu=cortex-m0+-uniprocessor` to restore the old code-gen?

And tearing a bool is always impossible (right?), so even on multi-core M0+ you'd hope that there'd be some way to arrange for ldrb + dmb to be sufficient for readers once the dust settles after the first call.  Whether or not atomic RMWs are supported, a byte load should be atomic, and if `dmb sy` or `dmb ish` work as an acquire load we're all set.
(There are multi-core M0+ CPUs; wikipedia says Raspberry Pi RP2040 has two M0+ cores.)

But that's not based on reading any docs; we'd probably want some on-paper guarantee of byte load/store atomicity before doing this.

----

If the first call that set the guard arranged for all other cores to sync with this core, the `dmb sy` wouldn't even be needed (i.e. even a relaxed load of the guard variable can only read as true if all cores have already synced with the static initializer).
But that's something users can maybe implement themselves if they need even cheaper guards at the expense of (much?) slower code in `__cxa_guard_acquire`, which would need an IPI or OS support to run_on all other cores, or something equivalent like Linux RCU does.

**Comment by efriedma-quic** [comment]
See also https://reviews.llvm.org/D137980 .

In general, uniprocessor can still be multithreaded, and if you're multithreaded, you need some way to make a cmpxchg atomic.  Depending on how you do that, atomic load/store might not be safe, even if they would be "atomic" in a world where cmpxchg doesn't exist, which is why we're in this situation.  (The static guard is effectively an atomic variable.)

As far as I know, load and store instructions are as atomic on cortex-m0 as they are on other cores.

**Comment by pcordes** [comment]
> See also https://reviews.llvm.org/D137980 .
> 
> In general, uniprocessor can still be multithreaded, and if you're multithreaded, you need some way to make a cmpxchg atomic. Depending on how you do that, atomic load/store might not be safe, even if they would be "atomic" in a world where cmpxchg doesn't exist, which is why we're in this situation. (The static guard is effectively an atomic variable.)
> 
> As far as I know, load and store instructions are as atomic on cortex-m0 as they are on other cores.

That was exactly my point: if we pay whatever it costs to make cmpxchg atomic in a way that can interact correctly with pure loads, then the common case (repeated calls) can be cheap.

On a uniprocessor, disabling interrupts around the RMW is an easy way to do this.

If we could assume non-multithreaded, we'd just eliminate the guard vars entirely, unless signal handlers could still "interrupt".  Or actual hardware interrupt handlers.

**Comment by efriedma-quic** [comment]
"Pay whatever it costs" is essentially D137980.  (Unless you're suggesting we invent a different form of atomics specifically for static init guards on cortex-m0.)

> If we could assume non-multithreaded, we'd just eliminate the guard vars entirely

We have `-fno-threadsafe-statics` and `-mthread-model single` already; I don't think we need another flag here.
