### ISSUE TITLE
[Flang][OpenMP] Adding reduction to non-worksharing loop constructs

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#58193]
Flang lowering only supports reduction in worksharing loops now. Extend this to other constructs like parallel, sections etc.

CHECK: Does lowering of non-worksharing loop constructs require modifications to the OpenMP MLIR dialect or in the lowering of the OpenMP dialect to LLVM.

**Comment by tblah** [comment]
Flang supports reduction on parallel, sections, wsloop, simd (I think? The code appears to be there but I can't see any unit tests), taskloop

Teams and taskloop are still TODO.

Closing because parallel and sections (mentioned in the ticket) are both complete.
