### ISSUE TITLE
[Flang][OpenMP] Implement robust lowering for Reduction

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#58190]
The current method for lowering depends on detecting operation patterns in the generate FIR. This is problematic due to a few reasons,
-> The patterns differ for variables like pointers and allocatable.
-> Deleting operations with FIROpBuilder does not seem to be appropriate.

There are probably a few alternative ways in which Reductions can be lowered. One approach is to detect that an Assignment Statement implies a reduction and then lower the Assignment Statement in a different way. This is explored in https://reviews.llvm.org/D130601 but needs more work for completion.

Another possibility is to create separate parse-tree nodes or expression nodes to signify reduction.

It is also possible that the presence of higher level ops (https://reviews.llvm.org/D134285) might simplify this task.

**Comment by tblah** [comment]
There was a lot of work on reduction this year and this ticket is quite old. Closing.
