### ISSUE TITLE
Clang accepts invalid narrowing conversion

### ISSUE THREAD

**Issue by ranaanoop** [llvm/llvm-project#58200]
The following invalid program is accepted by x86-64 clang 13.0.1 with C++17. [Demo](https://godbolt.org/z/hso9rG7as). 

```
void f() noexcept(5) //compiles with x86-64 clang 13.0.1 with C++17
{

}
```

**Comment by EugeneZelenko** [comment]
Could you please try 15 or `main` branch? https://godbolt.org should be helpful.

**Comment by shafik** [comment]
clang trunk rejects this: https://godbolt.org/z/KjsPeTK9a

So this looks like it is fixed.
