### ISSUE TITLE
Flaky  "invalid forward reference to function"

### ISSUE THREAD

**Issue by PiJoules** [llvm/llvm-project#58209]
```ll
@glob = constant i64 ptrtoint (i64* @glob to i64)

define void @call_func() {
  call void @func()
  ret void
}

define i32 @func() {
   ret i32 1
}
```

This IR will fail with:

```console
./bin/llc: error: ./bin/llc: /tmp/test4.ll:4:13: error: invalid forward reference to function 'func' with wrong type: expected 'i32 ()*' but was 'void ()*'
  call void @func()
            ^
```

but if I comment out `@glob`, there is no error. Adding some printfs, it looks like the types when `@glob` is not commented out are:

```ll
void ()*
i32 ()*
```

but when it is commented out, the types are both `ptr`. I imagine the failure should persist independently of `@glob`.

**Comment by nikic** [comment]
The IR is valid with opaque pointers, you are effectively calling a bitcasted function.

**Comment by PiJoules** [comment]
If the IR is valid, shouldn't there be no error then if `@glob` is present?

**Comment by nikic** [comment]
The validity of the IR depends on whether opaque pointers are used. If you change the `i64*` to `ptr`, the IR becomes valid with the `@glob` declaration.
