### ISSUE TITLE
GNU attributes preceding standard attributes are rejected

### ISSUE THREAD

**Issue by compnerd** [llvm/llvm-project#58229]
The following exemplifies the problem:

```c
__attribute__((__visibility__("default"))) [[nodiscard]] int f();
[[nodiscard]] __attribute__((__visibility__("default"))) int f();
```

While GCC accepts both, clang will refuse the first one.

This is currently "expected" behaviour: https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Parse/Parser.h#L2774-L2778

**Comment by AaronBallman** [comment]
I put the "rejects-valid" tag on this because the code is accepted by GCC and we typically want to follow GCC's behavior with their extensions.

**Comment by compnerd** [comment]
Mostly complete patch at https://reviews.llvm.org/D137979 ... there is one failure that is unclear that remains to be resolved.

**Comment by compnerd** [comment]
The differential revision fully passes now and should resolve the issue.

**Comment by buttaface** [comment]
@AaronBallman, since this was a regression in clang 15, any chance there can be a final 15.0.7 patch release with this added? It would fix issues like apple/swift#61468.

**Comment by AaronBallman** [comment]
> @AaronBallman, since this was a regression in clang 15, any chance there can be a final 15.0.7 patch release with this added? It would fix issues like [apple/swift#61468](https://github.com/apple/swift/issues/61468).

It's not a regression in Clang 15; we've never accepted attribute lists in an arbitrary order here (https://godbolt.org/z/3xMKGrKnM as an example). I don't think this would qualify for a patch release (it's complex enough of a fix that I'd want more time for it to be proven in the field).

**Comment by buttaface** [comment]
OK, I don't know exactly what clang 14 was doing, but it would silently compile the same code, while clang 15 errors because of this.

**Comment by AaronBallman** [comment]
> Since the Swift compiler builds fine with clang 14, would there be any interest in narrowing down the cause of that clang 15 regression, if not this issue alone, and issuing another clang 15 patch release with that fix, or has that ship sailed?

I don't think the ship has sailed if Clang 15 had a regression somewhere in this vicinity. Having a reduced test case that passes in 14, fails in 15, and passes again in 16 would be really interesting.

**Comment by buttaface** [comment]
OK, I'll get that test case and open a separate issue.

**Comment by buttaface** [comment]
@AaronBallman, got it, the Swift compiler source has several method definitions like this:
```
[[clang::warn_unused_result]]  [[gnu::returns_nonnull]]  extern "C" __attribute__((__visibility__("default"))) void* swift_allocEmptyBox();
```
clang 14 compiles this, but clang 15 errors for the exact same source:
```
error: an attribute list cannot appear here
[[clang::warn_unused_result]]  [[gnu::returns_nonnull]]  extern "C" __attribute__((__visibility__("default")))
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I'm not familiar with C++ attribute lists: is this a regression in clang 15 or something that needs to be updated in the Swift code?

**Comment by buttaface** [comment]
Looked through previous issues: is this example I pasted simply another instance of #56077?
