### ISSUE TITLE
[libcxx] macOS SDK 12.3: fatal error: 'string.h' file not found

### ISSUE THREAD

**Issue by H-G-Hristov** [llvm/llvm-project#58224]
During CMake configuration of a project I'm seeing:

> [cmake] -- System SDK Path: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk
[cmake] -- Bulding as exportable library is ON
[cmake] -- Architecture is "arm64;x86_64"
[cmake] -- Found ccache. It will be used for building (conan packages won't be affected)
[cmake] -- Conan: Automatic detection of conan settings from cmake
[cmake] In file included from <stdin>:1:
[cmake] In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:506:
[cmake] In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string_view:175:
[cmake] In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__string:57:
[cmake] In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:641:
[cmake] In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:60:
[cmake] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string.h:60:15: fatal error: 'string.h' file not found
[cmake] #include_next <string.h>
[cmake]               ^~~~~~~~~~
[cmake] 1 error generated.
[cmake] -- Conan: Settings= -s;build_type=Debug;-s;compiler=apple-clang;-s;compiler.version=13.1;-s;compiler.libcxx=libc++;-s;compiler.cppstd=20;-s;arch=arm64;-s;arch_build=arm64;-s;os.version=10.12

The project uses Conan 1.53.0, CMake 3.24.2, Xcode 13 on macOS Monterrey.

**Comment by asl** [comment]
Please report problems with Apple-provided tools to Apple bugtrackers.
