### ISSUE TITLE
LLVM Clang for ARM64 linux

### ISSUE THREAD

**Issue by XFaonAE** [llvm/llvm-project#58239]
I have a Linux Arm64 server and im compiling my code on it. But I cannot find any Arm64 builds for clang

**Comment by EugeneZelenko** [comment]
At least 15.0.1 has Aarch64 build: https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.1.

**Comment by XFaonAE** [comment]
Does AArch64 work on ARM linux systems

**Comment by XFaonAE** [comment]
> At least 15.0.1 has Aarch64 build: https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.1.

I want to use the latest version of LLVM clang, is there a reason they stopped building AArch

**Comment by XFaonAE** [comment]
Some of my friends claim that the perofmrnace will be horible on arm, is that true?

**Comment by DavidSpickett** [comment]
> I want to use the latest version of LLVM clang, is there a reason they stopped building AArch

Background, the "they" here is a volunteer, as it is for all the builds. The llvm project doesn't have a build farm making these. Also, 15.0.2 was only released recently so if you are patient they will likely upload an Arch build in the next couple of weeks (or perhaps wait until 15.0.3, it's a best effort scenario).

Unless you really need a change listed here: https://discourse.llvm.org/t/llvm-15-0-2-released/65695/1

I wouldn't be too bothered about getting hold of the latest. Building from source is always an option too, even if you only use it to test while you wait for a final build to be uploaded.

> Some of my friends claim that the perofmrnace will be horible on arm, is that true?

Background: I am an Arm employee, take that for what you will.

Your friends should file issues for the performance problems :) We welcome all feedback.

**Comment by XFaonAE** [comment]
Alright!
