### ISSUE TITLE
`ranges::rotate` is not inlined as `std::rotate`

### ISSUE THREAD

**Issue by SainoNamkho** [llvm/llvm-project#58231]
Compiled with `-std=c++20 -O2 -stdlib=libc++`, clang v15.0.0
```c++
#define _LIBCPP_ENABLE_EXPERIMENTAL
#include <algorithm>
#include <ranges>

using namespace std;

int main()
{
    // ranges::rotate is not inlined
    int a[9] {1, 2, 4, 5, 9, 535, 2, 4, 6};
    ranges::rotate(ranges::subrange{a+2, a+7}, a+6);

    // std::rotate is inlined
    int b[9] {1, 2, 4, 5, 9, 535, 2, 4, 6};
    rotate(b+2, b+7, b+6);


    // ranges::copy_backward is inlined
    int c[9] {1, 2, 4, 5, 9, 535, 2, 4, 6};
    int temp = c[6];
    ranges::copy_backward(ranges::subrange{c+2, c+7}, c+6);
    c[2] = temp;

    return 0;
}
```
https://godbolt.org/z/z5Kxarerc

**Comment by philnik777** [comment]
Ok, what exactly is the problem? I wouldn't expect that two functions are always inlined the same. Also, your example is broken. The `rotate` should be called with `b + 2, b + 6, b + 7`. If you use `-O3` everything gets inlined the same: https://godbolt.org/z/rKxExbPoY, so it's probably just the inlining heuristic not liking the ranges overload.
