### ISSUE TITLE
[llvm][peephole] merge successive stack pointer modifications

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#58237]
for an i386 linux kernel build, I noticed in the prolog of core_sys_select() that we have:

```asm
     380: 55                            pushl   %ebp
     381: 89 e5                         movl    %esp, %ebp
     383: 53                            pushl   %ebx
     384: 57                            pushl   %edi
     385: 56                            pushl   %esi
     386: 83 e4 f8                      andl    $-8, %esp
     389: 81 ec f0 03 00 00             subl    $1008, %esp
```
Can't we merge the `and` of a negative value with the `sub` of a positive value into one instruction? I don't see control flow reliant on one of those vs both.

**Comment by asl** [comment]
@nickdesaulniers How? It's `and` not `add`. It is used for stack realignment here...

**Comment by nickdesaulniers** [comment]
d'oh! For some reason I was reading that as `ADD`...
