### ISSUE TITLE
Clang allows consteval constructor to be created on heap

### ISSUE THREAD

**Issue by phyBrackets** [llvm/llvm-project#58247]
```c++
struct A {       
    consteval A() {}
};

int main() {
    new A{};
}
```

using `consteval` make `A::A()` an immediate function and `new` is not a way to call immediate function. This behaviour is false by other compilers (gcc/msvc) but it accepted by clang as it requires diagnostic . 
https://godbolt.org/z/fdPPxTjPM

**Comment by phyBrackets** [comment]
I can work to resolve this!

**Comment by inclyc** [comment]
> I can work to resolve this!

❤️

**Comment by shafik** [comment]
I think clang is correct here, for example these cases accepted by all compiler, except the last one by MSVC: https://godbolt.org/z/17sWb4r6a

```cpp
consteval int f(int x) {
    return x + 1;
}

struct A {
    consteval A() {}
    consteval operator int() { return 1;}
};

int main() {
   f(10);
   new int[f(10)];
   new int[A{}]; // Only MSVC does not like this one
                         // with error " error C2100: illegal indirection"
}
```

**Comment by shafik** [comment]
I believe clang is correct here as per [expr.const p14](https://timsong-cpp.github.io/cppwp/expr.const#14) this is an immediate invocation.

I received confirmation that MSVC front end devs consider this a bug and plan on fixing it.

I would file a gcc bug report.
