### ISSUE TITLE
[clang-format] Incorrectly identifies empty function as bracedList

### ISSUE THREAD

**Issue by mydeveloperday** [llvm/llvm-project#58251]
Because clang-format cannot determine `{}`  as an empty function is leaves out a space between the `)` and the `{` as it doesn't identify the `{` as a `TT_FunctionLBrace` 

Add an issue for tracking a potential change to fix that.

```c++
void function(){};
void function() { int a; };
```

**Comment by mydeveloperday** [comment]
While working on a fix for #58217 (namely https://reviews.llvm.org/D135466) we identified that `foo(){}` was not being identified the same as `foo() { retrun; }`

**Comment by rymiel** [comment]
Also see https://github.com/llvm/llvm-project/issues/57305#issuecomment-1224718704. Not *exactly* a duplicate but the same underlying bug, i'm assuming

**Comment by mydeveloperday** [comment]
The more I look at this the more I think this is harder than we first think, simply assuming `) {`  to be a function would change, would then identify the `{` as a FunctionLBrace, which in turn RemoveSemicolons would remove the trailing `;` which is needed i.e.

this
```c++
auto i = decltype(x) {};
```
to this
```c++
auto i = decltype(x) {}
```
which would be a compile error

So we'd really need yet more semantic (or derived semantic) information about what makes   {}; a function body.

The unwrappered parser when we are determining the block type is before the annotator which identified the ')' as a TypeDeclarationParen, but this would be useful information to have.

I wonder if there is something we can do after the function name has been identified as `FunctionDeclarationName`

At present we get this..

Expected & Input
```c++
void a() {}
void a() {};
void a() { return a;}
void a() { return a;};
```

Clang-Format current output
```c++
void a() {}
void a(){};
void a() { return a; }
void a() { return a; };
```

**Comment by rymiel** [comment]
> The more I look at this the more I think this is harder than we first think

I definitely couldn't fix it. I concluded that determining if a function declaration is being dealt with (i.e. `Line.MightBeFunctionDecl`) happens way later and I couldn't find a non-invasive heuristic that didn't involve lots of duplicated work

**Comment by mydeveloperday** [comment]
feel free to have a go.
