### ISSUE TITLE
Backend code generator bug

### ISSUE THREAD

**Issue by CamJN** [llvm/llvm-project#58269]
All of the following commands crash:
```shell
llc bugpoint-reduced-simplified.bc
llc bugpoint-reduced-simplified.bc -relocation-model=pic
llc bugpoint-reduced-simplified.bc -relocation-model=static
```
[bugpoint-reduced-simplified.tar.gz](https://github.com/llvm/llvm-project/files/9747949/bugpoint-reduced-simplified.tar.gz)

llvm was tested from the homebrew repo for macOS (llvm@14) and also from apple (Apple clang version 14.0.0 (clang-1400.0.29.201)).

**Comment by EugeneZelenko** [comment]
Could you please try 15 or `main` branch?

**Comment by CamJN** [comment]
15.0.2 (from homebrew) still crashes for all three commands, as does HEAD (16.0.0) built with homebrew's help.

**Comment by RKSimon** [comment]
Gobolt: https://gcc.godbolt.org/z/sed55M4or

```
llc: /root/llvm-project/llvm/lib/Target/X86/X86FloatingPoint.cpp:318: unsigned int getFPReg(const llvm::MachineOperand&): Assertion `Reg >= X86::FP0 && Reg <= X86::FP6 && "Expected FP register!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/llc -o /app/output.s <source>
1.	Running pass 'Function Pass Manager' on module '<source>'.
2.	Running pass 'X86 FP Stackifier' on function '@_ZN5boost4json6detail3ryu14d2s_buffered_nEdPc'
 #0 0x000055cc2b290f64 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x000055cc2b28e724 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f05f3e1c420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007f05f38e900b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #4 0x00007f05f38c8859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #5 0x00007f05f38c8729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #6 0x00007f05f38d9fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #7 0x000055cc29959f7f (anonymous namespace)::FPS::handleSpecialFP(llvm::MachineInstrBundleIterator<llvm::MachineInstr, false>&) X86FloatingPoint.cpp:0:0
 #8 0x000055cc2995a748 (anonymous namespace)::FPS::processBasicBlock(llvm::MachineFunction&, llvm::MachineBasicBlock&) (.isra.0) X86FloatingPoint.cpp:0:0
 #9 0x000055cc2995ced7 (anonymous namespace)::FPS::runOnMachineFunction(llvm::MachineFunction&) (.part.0) X86FloatingPoint.cpp:0:0
#10 0x000055cc2a447a6e llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
#11 0x000055cc2a970515 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x2e1d515)
#12 0x000055cc2a970759 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x2e1d759)
#13 0x000055cc2a970fa2 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x2e1dfa2)
#14 0x000055cc286b204b compileModule(char**, llvm::LLVMContext&) llc.cpp:0:0
#15 0x000055cc285f5ab2 main (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0xaa2ab2)
#16 0x00007f05f38ca083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#17 0x000055cc286a943e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0xb5643e)
Compiler returned: 139
```

**Comment by phoebewang** [comment]
The actual crash reason is you missing the required feature before using VAES intrinsics:
```
LLVM ERROR: Cannot select: intrinsic %llvm.x86.aesni.aesenc
```
It passed if adding the feature `llc < bugpoint-reduced-function.bc -mattr=vaes`

**Comment by CamJN** [comment]
Ok, I think it might be bugpoint that introduced those things? I don't specify a cpu to target nor do I use AES instructions:

`c++ -o buildout/common/libpassenger_common/StrIntTools/StrIntUtilsNoStrictAliasing.o  -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -Isrc/cxx_supportlib/vendor-modified/libev -Wno-ambiguous-member-template -DUSE_VENDORED_LIBEV -Isrc/cxx_supportlib/vendor-copy/libuv/include -O2 -fno-strict-aliasing -mno-sse2 -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -Wno-ambiguous-member-template -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -DHAS_ALLOCA_H -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -g -fno-limit-debug-info -std=gnu++11 -Wno-unused-local-typedefs -Wno-format-nonliteral -DHAS_UNORDERED_MAP -c src/cxx_supportlib/StrIntTools/StrIntUtilsNoStrictAliasing.cpp`

https://github.com/phusion/passenger/blob/stable-6.0/src/cxx_supportlib/StrIntTools/StrIntUtilsNoStrictAliasing.cpp

And further, clang should tell me what's wrong instead of crashing right? So i don't have to bother people in the bug tracker?

**Comment by CamJN** [comment]
Passing `-mno-aes` doesn't help.

**Comment by phoebewang** [comment]
I don't have macOS, I build `StrIntUtilsNoStrictAliasing.o` successfully on RHEL 8.4 with the main trunk.
I'd suggest you use `-mllvm -print-after-all` to find the guilty pass that introduced `llvm.x86.aesni.aesenc`
