### ISSUE TITLE
[AMDGPU] Implement ISel for V_SAT_PK_U8_I16 

### ISSUE THREAD

**Issue by Sisyph** [llvm/llvm-project#58266]
It appears we have no way to select into this instruction.
It likely could be selected from llvm.sadd.sat

See https://reviews.llvm.org/D135478

**Comment by jayfoad** [comment]
> It likely could be selected from llvm.sadd.sat

I don't see how. This instruction does not do an add. It is more like a saturating truncate from 16-bit signed to 8-bit unsigned.

**Comment by Pierre-vh** [comment]
I'm looking at this and will submit a patch if I finish it - assigning to myself in the meantime
