### ISSUE TITLE
License link in https://llvm.org is broken

### ISSUE THREAD

**Issue by RiyazVP** [llvm/llvm-project#58278]
On llvm.org, click on "View the open-source license". The link fails because `https://llvm.org/releases/15.0.0/LICENSE.TXT` doesn't exist:

```
View the open-source
[license](https://llvm.org/releases/15.0.0/LICENSE.TXT)
```

**Comment by RiyazVP** [comment]
It should perhaps be changed to point to:

```
https://raw.githubusercontent.com/llvm/llvm-project/main/llvm/LICENSE.TXT
```

**Comment by tbaederr** [comment]
CCing @tru since I know he can change the website

**Comment by tru** [comment]
I fixed the 404 - but it might be cached so check back in a bit.

**Comment by tbaederr** [comment]
Works now.
