### ISSUE TITLE
LLVM 15 infinite execution loop with arc4random and glibc 2.36

### ISSUE THREAD

**Issue by bsferrazza** [llvm/llvm-project#58279]
This discovered when building rustc-1.64.0 with LLVM 15.0.1 and 15.0.2, and reported to the rustc issues page, thinking it was an issue with rust. Turns out it is caused by LLVM. Please see [rustc issue #102897](https://github.com/rust-lang/rust/issues/102897) for the details.

**Comment by adonis0147** [comment]
This issue still exists in LLVM-16.0.1.

**Comment by Endilll** [comment]
Does this reproduce with LLVM 17?

**Comment by adonis0147** [comment]
Hi @Endilll , under my scenario, this issue disappears in LLVM 17. I tested both LLVM-17.0.1 and LLVM-17.0.2 .

**Comment by Endilll** [comment]
Thank you for checking!
