### ISSUE TITLE
pthread_getaffinity_np tests fail on a system using Docker with fixed container cores

### ISSUE THREAD

**Issue by DavidSpickett** [llvm/llvm-project#58283]
`compiler-rt/test/sanitizer_common/TestCases/Linux/pthread_getaffinity_np.cpp` checks that `pthread_getaffinity_np` returns the same number of cores as `get_nprocs` does. Presumably to check that interception of the former has been done correctly.

I have a bot that uses Docker with a fixed set of cores. This test fails on that bot: https://lab.llvm.org/staging/#/builders/158/builds/368

This is because `get_nprocs` doesn't account for cgroups. On the machine `nproc` gives:
```
/# nproc --all
160
/# nproc
10
```
(I have assigned it 10 fixed cores)

Adding some printfs to the test I get:
```
# /tmp/test.o
sizeof cpu_set_t: 128
CPU_COUNT_S is 10
nprocs is 160
test.o: /tmp/test.c:16: main: Assertion `CPU_COUNT_S(sizeof(set_x), set_x) == get_nprocs()' failed.
```

I dug into `nproc` and found that it in fact calls `pthread_getaffinity_np` so it can work when cgroups are used.

https://github.com/coreutils/gnulib/blob/48a6c46b0b7e993aecf5c09386afd554165506ff/lib/nproc.c#L68

Seems a shame to disable this for all AArch64 (and Arm, I intend to move more bots to fixed core counts) to this test.

**Comment by DavidSpickett** [comment]
Yes, we can detect this from Python:
```
# python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.cpu_count()
160
>>> os.sched_getaffinity(0)
{10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29}
>>> len(os.sched_getaffinity(0))
20
```

**Comment by DavidSpickett** [comment]
https://reviews.llvm.org/D135677

**Comment by MaskRay** [comment]
I wonder whether we should just relax the test, instead of introducing a lit feature based on if os.cpu_count() != len(os.sched_getaffinity(0)).

I can confirm that the test also fails if I restrict affinity with something like numactl -C 0-3 /tmp/RelA/bin/llvm-lit -a /tmp/RelA/projects/compiler-rt/test/sanitizer_common/asan-x86_64-Linux/Linux/pthread_getaffinity_np.cpp
