### ISSUE TITLE
opt -passes="default<O0>" -print-pipeline-passes results in bad "CoroConditionalWrapper" printout

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#58280]
llvm commit: 66046e6e65e5
Reproduce with:
```shell
opt -passes="default<O0>" empty.ll -o /dev/null -print-pipeline-passes
```
on an empty file `empty.ll`
Result:
```console
verify,always-inline,CoroConditionalWrapper,function(annotation-remarks),verify,BitcodeWriterPass
```

If you then pass the above printed pipeline to opt you get
```console
opt: unknown module pass 'CoroConditionalWrapper'
```
This is e.g. an issue when trying to use `utils/reduce-pipeline.py` to automatically reduce an opt pipeline.

`CoroConditionalWrapper` is missing in `llvm/lib/Passes/PassRegistry.def`

But I don't even know what to add there since the pass looks like some kind of hack conditionally running passes in it's own pass manager:
```cpp
CoroConditionalWrapper::CoroConditionalWrapper(ModulePassManager &&PM)
    : PM(std::move(PM)) {}

PreservedAnalyses CoroConditionalWrapper::run(Module &M,
                                              ModuleAnalysisManager &AM) {
  if (!coro::declaresAnyIntrinsic(M))
    return PreservedAnalyses::all();

  return PM.run(M, AM);
}
```

**Comment by ChuanqiXu9** [comment]
@aeubanks

**Comment by aeubanks** [comment]
https://reviews.llvm.org/D135703
