### ISSUE TITLE
[clang] Compile fail on struct of bool vector element.

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#58281]
clang fails to compile the following code while gcc compiles fine.
https://godbolt.org/z/Yn71rzavn

```cpp
typedef bool bool4 __attribute__((ext_vector_type(4)));
struct B4 {
   bool4 v;
};
B4 foo(B4 a) {
  return a;
}
```

**Comment by to268** [comment]
It looks like that this issue has been fixed between Clang 15 and the git version.
