### ISSUE TITLE
make check-lit uses opt from PATH instead of Debug/bin/opt

### ISSUE THREAD

**Issue by 1ba3d143-a64b-4671-82b2-0b31cfb91709** [llvm/llvm-project#5829]
|  |  |
| --- | --- |
| Bugzilla Link | [5457](https://llvm.org/bz5457) |
| Version | trunk |
| OS | MacOS X |
| CC | @modocache |

## Extended Description 
I have a Release-build opt tool in my PATH. When I run "make check-lit" in a debug build, the Feature/load_module.ll test fails.

~/b/llvm$ make check-lit
llvm[0]: Running test suite
Making a new site.exp file...
Making LLVM 'lit.site.cfg' file...
Making LLVM unittest 'lit.site.cfg' file...
( ulimit -t 600 ; ulimit -d 512000 ; ulimit -m 512000 ; ulimit -v 512000 ; \
	  /Users/jolesen/g/llvm/utils/lit/lit.py -s -v . )
FAIL: LLVM::Feature/load_module.ll (2862 of 4892)
******************** TEST 'LLVM::Feature/load_module.ll' FAILED ********************
Script:
--
opt < /Users/jolesen/g/llvm/test/Feature/load_module.ll -load=/Users/jolesen/b/llvm/Debug/lib/LLVMHello.dylib -hello    -disable-output |& grep Hello
--
Exit Code: 1
Command Output (stdout):
--
Error opening '/Users/jolesen/b/llvm/Debug/lib/LLVMHello.dylib': dlopen(/Users/jolesen/b/llvm/Debug/lib/LLVMHello.dylib, 9): Symbol not found: __ZN4llvm12FunctionPass11runOnModuleERNS_6ModuleE
  Referenced from: /Users/jolesen/b/llvm/Debug/lib/LLVMHello.dylib
 in /Users/jolesen/b/llvm/Debug/lib/LLVMHello.dylib
--
Command Output (stderr):
--
--

********************
Testing Time: 34.81s
********************
Failing Tests (1):
    LLVM::Feature/load_module.ll

  Expected Passes    : 4815
  Expected Failures  : 36
  Unsupported Tests  : 40
  Unexpected Failures: 1
make[1]: *** [check-local-lit] Error 1
make: *** [check-lit] Error 2

I believe it is using the "opt" tool from my $PATH rather than the one on Debug/bin:

~/b/llvm$ which opt
/Users/jolesen/bin/opt
~/b/llvm$ opt < /Users/jolesen/g/llvm/test/Feature/load_module.ll -load=/Users/jolesen/b/llvm/Debug/lib/LLVMHello.dylib -hello -disable-output
Error opening '/Users/jolesen/b/llvm/Debug/lib/LLVMHello.dylib': dlopen(/Users/jolesen/b/llvm/Debug/lib/LLVMHello.dylib, 9): Symbol not found: __ZN4llvm12FunctionPass11runOnModuleERNS_6ModuleE
  Referenced from: /Users/jolesen/b/llvm/Debug/lib/LLVMHello.dylib
  Expected in: flat namespace
 in /Users/jolesen/b/llvm/Debug/lib/LLVMHello.dylib
  -load request ignored.
opt: Unknown command line argument '-hello'.  Try: 'opt --help'
~/b/llvm$ Debug/bin/opt < /Users/jolesen/g/llvm/test/Feature/load_module.ll -load=/Users/jolesen/b/llvm/Debug/lib/LLVMHello.dylib -hello -disable-output
Hello: somefunk
~/b/llvm$ opt --version
Low Level Virtual Machine (http://llvm.org/):
  llvm version 2.7svn
  Optimized build with assertions.
  Built Nov 10 2009 (09:32:14).
  Host: x86_64-apple-darwin10

  Registered Targets:
    (none)
~/b/llvm$ Debug/bin/opt --version
Low Level Virtual Machine (http://llvm.org/):
  llvm version 2.7svn
  DEBUG build with assertions.
  Built Nov 10 2009 (09:17:37).
  Host: x86_64-apple-darwin10

  Registered Targets:
    (none)

When I run "make check", all tests pass.

I am on Mac OS X 10.6.1

**Comment by arsenm** [comment]
Pretty sure this has worked correctly the entire time I've worked on the project
