### ISSUE TITLE
`Incorrect alignment of argument passed to called function!` on packed struct

### ISSUE THREAD

**Issue by pirama-arumuga-nainar** [llvm/llvm-project#58304]
Command:
```console
$ clang "-cc1" "-triple" "aarch64-unknown-linux-android10000" "-emit-obj" "--mrelax-relocations" "-mnoexecstack" "-disable-free"  "-target-cpu" "cortex-a55" "-target-feature" "+neon" "-target-feature" "+v8.2a" "-target-feature" "+fix-cortex-a53-835769" "-target-abi" "aapcs"  "-O2"  "-std=gnu++17"   "-vectorize-loops" "-vectorize-slp" "-x" "c++" "packed_struct_align.cpp"
Incorrect alignment of argument passed to called function!
  %19 = tail call i8488 @llvm.vector.reduce.or.v16i8488(<16 x i8488> %18)
in function _Z1qv
fatal error: error in backend: Broken function found, compilation aborted!
```
Source:
```cpp
struct __attribute__((__packed__)) {
  short : 8411;
  char a : 8;
  char b : 8;
  char c : 8;
  char d : 8;
  char e : 6;
  char f : 6;
  char g : 6;
  char h : 6;
  char i : 4;
  char j : 4;
  char k : 4;
  char l : 4;
  char m : 1;
  char n : 1;
  char aa : 1;
  char ab : 1;
} am;
int al[64];
int o, p;
void q() {
  am.a = p;
  am.e = o;
  am.i = al[4];
  am.m = al[5];
  am.b = al[0];
  am.f = al[1];
  am.j = p;
  am.n = am.c = al[8];
  am.g = al[9];
  am.k = al[0];
  am.aa = am.d = al[56];
  am.h = al[57];
  am.l = al[8];
  am.ab = al[9];
}
```

**Comment by pirama-arumuga-nainar** [comment]
(Adding @kparzysz-quic @ilinpv @stephenhines )

**Comment by pirama-arumuga-nainar** [comment]
I forgot to tag @kbeyls.  (Sorry for the wrong tag @kparzysz-quic :) )

I also forgot to mention that this surfaced after https://reviews.llvm.org/rG321cbf75be2c0f4f33856f4b1246f09800cc91d0 which tightened IR verification.

**Comment by pirama-arumuga-nainar** [comment]
Another point of note is that if we remove the `__attribute__((packed))` from the struct, the bug doesn't reproduce.  Without `packed`, SLP Vectorizer doesn't vectorize this code.

**Comment by pirama-arumuga-nainar** [comment]
@LuoYuanke FYI, this break is due to https://reviews.llvm.org/D121898.

**Comment by LuoYuanke** [comment]
I think that is what https://reviews.llvm.org/D121898 want to prevent. The big vector size is not supported in backend lowering. If it is not checked in IR, it would finally fail in backend lowering.

**Comment by davemgreen** [comment]
Not in this case no. The very large bitfield is creating an i8488 integer, which the SLP vectorizer is turning into:
```
  %16 = and <16 x i32> %shuffle, <i32 255, i32 63, i32 15, i32 1, i32 255, i32 63, i32 15, i32 255, i32 1, i32 63, i32 15, i32 255, i32 1, i32 63, i32 15, i32 1>
  %17 = zext <16 x i32> %16 to <16 x i8488>
  %18 = shl nuw nsw <16 x i8488> %17, <i8488 8411, i8488 8443, i8488 8467, i8488 8483, i8488 8419, i8488 8449, i8488 8471, i8488 8427, i8488 8484, i8488 8455, i8488 84
75, i8488 8435, i8488 8485, i8488 8461, i8488 8479, i8488 8486>
  %19 = call i8488 @llvm.vector.reduce.or.v16i8488(<16 x i8488> %18)
  %op.rdx = or i8488 %19, %bf.clear
  store i8488 %op.rdx, ptr @am, align 16
```

The `@llvm.vector.reduce.or.v16i8488(<16 x i8488> %18)` is the instruction that fails verification, but is not a real call. It will only be expanded into other instructions if it is not supported, and shouldn't give the same verifier error as other calls.
Alternatively the SLP vectorizer (and any other passes) need to be taught that there is a limit on the size of integers that they can create intrinsics for.

**Comment by LuoYuanke** [comment]
It sounds reasonable, thanks. Candidate patch https://reviews.llvm.org/D136330 to fix it.

**Comment by LuoYuanke** [comment]
D136330 landed. Close this issue.

**Comment by pirama-arumuga-nainar** [comment]
Thanks for fixing the issue @LuoYuanke!
