### ISSUE TITLE
Clang-format might cause compilation errors if a local library header is included with angle brackets 

### ISSUE THREAD

**Issue by doruktiktiklar** [llvm/llvm-project#58300]
The code excerpt below compiles. But if I run clang-format on it, clang-format reorders these include definitions, causing some compilation errors. These compilation errors happen because `glad.h` redefines some macros
```c
#include <glad/glad.h>
#include <GLFW/glfw3.h>
```
If I instead write it like below, the code compiles properly because clang-format does not reorder in this case.
```c
#include "glad/glad.h"
#include <GLFW/glfw3.h>
```

This issue is somewhat related to the issue https://github.com/llvm/llvm-project/issues/53013

**Comment by dwblaikie** [comment]
I assume clang-format assumes headers are safely re-orderable. If you have headers that can't be reordered, I guess you have to turn off clang-format's include sorting.

**Comment by doruktiktiklar** [comment]
Yes there is a ``` --sort-includes``` flag and there is a ```SortIncludes``` flag in clang format style options as well. https://clang.llvm.org/docs/ClangFormatStyleOptions.html . As such, this is not an issue
