### ISSUE TITLE
Missed optimisation opportunity for `xor` lowering

### ISSUE THREAD

**Issue by ljmf00-wekaio** [llvm/llvm-project#58313]
I noticed that compiling the following D code on LLVM 12 and LLVM 13 yields different results:
```d
bool xor(bool lhs, bool rhs)
{
    return (lhs && !rhs) || (!lhs && rhs);
}
```
https://godbolt.org/z/WTW1qeEMY

Eventhough I'm not entirely sure this is a regression with LLVM itself or perhaps a different approach LDC takes to glue the LLVM backend, but it seems that it is not a correctness issue. Running alive2 against the different generated IRs, it can validate the transformation successfully. https://alive2.llvm.org/ce/z/cWdpvA

Perhaps this can be seen as an improvement to add this logic simplifiation in a transformation pass.

**Comment by EugeneZelenko** [comment]
Could you please try 15 or `main` branch? 13 is too old.

**Comment by rotateright** [comment]
We may want to enhance a conditional branch fold in instcombine that swaps the destination blocks to also match a select-of-bools:
https://alive2.llvm.org/ce/z/__bcRG

Note that currently we would canonicalize the new select in that sequence to include another 'not' instruction; I'm not sure yet what overall changes would occur if we alter that decision.

**Comment by rotateright** [comment]
> https://alive2.llvm.org/ce/z/8fQRvn 
> Both are equivelent to `xor` instruction.

That one looks like an obvious missing reduction, so:
d85505a9323a
(not sure if that changes anything for the motivating source example)

**Comment by ljmf00-wekaio** [comment]
> > https://alive2.llvm.org/ce/z/8fQRvn
> > Both are equivelent to `xor` instruction.
> 
> That one looks like an obvious missing reduction, so: [d85505a](https://github.com/llvm/llvm-project/commit/d85505a9323aadcfd3a34e9ba2e088a0d670b6bd) (not sure if that changes anything for the motivating source example)

Yes, the expressions I showed above is the equivelent translation to the IR showed in alive2, so the second one should generate optimized code now.

**Comment by rotateright** [comment]
I think the examples here are fixed now, so closing. We still have missing folds for logical-and and logical-or:
#58589
...so if you find other examples, please do file another bug report. Thanks!
