### ISSUE TITLE
Out-of-line Definition of Partially Constrained Members 

### ISSUE THREAD

**Issue by matekelemen** [llvm/llvm-project#58310]
Clang rejects defining member functions of partially specialized classes with constraints out of line.

Reduced example on [godbolt](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyahUAUgBMAIUtXyKxqiIEh1ZpgDC6egFc2TA3cAGQImbAA5PwAjbFIQCx5yAAd0JWIXJi9ffwMUtOchELDIthi4hPtsRwKmESIWUiIsvwDEh2wnDLqGoiKI6Nj4tvrG5pzhnr6SsqGASnt0H1JUTi5LAGZQ1F8cAGozdY8MJhWkoiUD3DMtAEFrm6JsNiSjR/3D7ZYlJV2AFUv7koiKQfE5diJ9gB2Gy3XZw3YAN3QBEwuxoEFmUJskIAIvczLiDjC7rdHs9Xth3h4gZgQCBQo9gKQJH8AbcgSCwSIDh5/usrrcCcT4Yjkaj0bMifjCetifcyS8WG8eTS6QzsEyWXyBTckSjwTztXSJViCXjBbcGbs2CxQhjpXLBYTblx5vRuABWfgBLg6cjobgeWy2XZKRbLSkbPjkIjaV3zJDYFg4OIY8gAaxAHp4ADp1tIAGwADi0PHzxdL6wLhm40n4bCzWnIPr9Aa4/CUICbsd9rvIcFgKGw6g6PhIFCoEAawCUqmMVRESHQAHcfdGMM8GEqMnOwvRFyuW/wN0kGIMZ6wkkol0RyCez6QAPJjg%2BruPkYcdG6kGfcfif1A6kIH1%2BEEYQxAkTgZDkYRlDUTRe3IfR1kMYxTGDaxDAIKJO0geZ0DODJOy4ABaGkDhxcxrFsCw/TDJYVgMGlQl3BclzfXh%2BGBbBVmjZdmSSbg%2BDdT1vXfNtcBHVAxzIXZ1CLAsSILaRdmAVBUF2CBgR8Jh00xCAg2ozDdnwYhZKjWYuLjWYEyTFNqBErg63IBsPSbI9/T/ewuxjaz5kzbM80LEsy2Cytq3dLh1jExC2ys3t5gHBB4AgIcpJkidqGnWd533di12PdBN1eHdctfDz70YOJPhMGQtCbSrYmfUR8vfADv1/dsPykoDQi8sDRHESRoIGuCNHffREiMEw0Awux6Gw3C0wImpiLIohMAoqibGsWiO3DRjhmA1i8sPISuNIHjzvIfiWEEzjHK9ZtxO4STR3HOSFKUlSauAXYZBzLRAc0wydrsEzCA%2Biz4p0GzyETZNBjTSLnIbdZIRzIt1mxyESyLaQeAsAsPQU57Yq8ztu2s/tEFSkAAIyygsp/HK93K67Ku3IQTvZxDGriBFUCSJIAH0ER4ABOEWKSBEX5Orfnmt5v12pZryAN6kCYMGyCpFkUaVHGxD9AsVCZu22wsJw%2BB8MIoRiIAelVC3drog6oPsDaWLK1rOJjS7eP4W77uEmsuCejyJPSj75etJRBcRSWcxlogQbm8gIbM0h9gsdYeEs3yEtsxHU0c1GQALCwcx4Ata4SCWeBJyF81NyOKZ8ntYf8kBpCLHNibziWFI9QeFIi7horJ1svM7%2BMw4sGLp662e4YRWI0lcaQgA):
```cpp
#include <concepts>

template <class T>
struct S {
    void f() {}
};

template <std::integral T>
struct S<T>
{
    void f();
};

template <std::integral T> // error: type constraint differs in template redeclaration
void S<T>::f() {}

int main()
{

}
```

Yes, this is a duplicate of #47364 (but it hasn't received any attention so far).

**Comment by usx95** [comment]
Duplicate of #49620 (more activity).
