### ISSUE TITLE
Implement global-isel support for llvm.amdgcn.icmp and llvm.amdgcn.fcmp

### ISSUE THREAD

**Issue by Sisyph** [llvm/llvm-project#58326]
Compares of 16 bit values need to be implemented in `AMDGPUInstructionSelector::getV_CMPOpcode` for GlobalIsel to work for `llvm.amdgcn.icmp`. `True16` version of compare instructions should be used on GFX11

`llvm.amdgcn.fcmp` whole implementation is TODO

**Comment by Pierre-vh** [comment]
- (landed) https://reviews.llvm.org/D136446
- (review) https://reviews.llvm.org/D136448
- (review) https://reviews.llvm.org/D136591
- (review) https://reviews.llvm.org/D136592
