### ISSUE TITLE
[HLSL] enable lambda support

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#58329]
Now we'll report error on auto l = []()  {}; like:
error: expected expression

It reports "expected expression" because we don't enable C++11 in langOpts.
The code for starting lambda parsing is in Parser::ParseCastExpression under case tok::l_square:

Once we enabled lambda support, we could report a better error message for lower versions of HLSL which does not support lambda.

**Comment by llvm-beanz** [comment]
Closing this because we have no plans to enable lambdas at this time since lambdas aren't supported by HLSL. If we want to add lambdas to HLSL that needs to start in the language design process.
