### ISSUE TITLE
[X86] Redundant instructions when shuffling and returning lower 128-bit of 256-bit register

### ISSUE THREAD

**Issue by damageboy** [llvm/llvm-project#58339]
The following code ([Compiler-Explorer Link](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:5,endLineNumber:5,positionColumn:5,positionLineNumber:5,selectionStartColumn:5,selectionStartLineNumber:5,startColumn:5,startLineNumber:5),source:'%23include+%22immintrin.h%22%0A%0Aextern+__m128i+not_so_great_for_clang(__m256i+u1,+__m256i+u2,+short+*p)+%7B%0A++++auto+packed+%3D+_mm256_packus_epi32(u1,+u2)%3B%0A++++packed+%3D+_mm256_permute4x64_epi64(packed,+0b11!'01!'10!'00)%3B%0A%0A++++return+_mm256_castsi256_si128(packed)%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:42.347908745247146,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:g111,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:fmt,ver:trunk)),options:'-std%3Dc%2B%2B20+-march%3Dnative+-O2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x86-64+gcc+11.1+(C%2B%2B,+Editor+%231,+Compiler+%231)',t:'0')),k:47.97605072595937,l:'4',m:46.87493678757056,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang1500,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:2,lang:c%2B%2B,libs:!((name:fmt,ver:'811')),options:'-std%3Dc%2B%2B20+-march%3Dnative+-O2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x86-64+clang+15.0.0+(C%2B%2B,+Editor+%231,+Compiler+%232)',t:'0')),header:(),l:'4',m:53.12506321242945,n:'0',o:'',s:0,t:'0')),k:57.65209125475286,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)):

```c
#include "immintrin.h"

extern __m128i not_so_great_for_clang(__m256i u1, __m256i u2, short *p) {
    auto packed = _mm256_packus_epi32(u1, u2);
    packed = _mm256_permute4x64_epi64(packed, 0b11'01'10'00);

    return _mm256_castsi256_si128(packed);
}
```

Triggers promotion into shuffles and fails in lowering this efficiently:

```asm
        vpackusdw       ymm0, ymm0, ymm0
        vextracti128    xmm1, ymm0, 1
        vpunpcklqdq     xmm0, xmm0, xmm1        # xmm0 = xmm0[0],xmm1[0]
        vzeroupper
        ret
```

Compared to the optimal code-gen with GCC, for example:

```asm
        vpackusdw       ymm0, ymm0, ymm1
        vpermq  ymm0, ymm0, 216
        ret
```

**Comment by RKSimon** [comment]
Already looking at this :-) 7055751115eb1002e25ab03093d0aecae856120f
