### ISSUE TITLE
Regression missed optimization with constant signed division going from version 9 to 10

### ISSUE THREAD

**Issue by jeaiii** [llvm/llvm-project#58348]
Clang 10 and newer produce sub-optimal code when doing a signed floor division for the same LLVM IR.

I have 3 versions of `floor_div` that preform division with rounding towards -inf instead of 0.
https://godbolt.org/z/dbfWhEdGY

```cpp
long long xfloor_div_16(long long a)
{
     return (a + 0x8000000000000000ULL) / 16 - 0x8000000000000000 / 16;
}

long long yfloor_div_16(long long a)
{ 
    return (long long)((unsigned long long)(a) / 16 * 16) / 16;
}

long long zfloor_div_16(long long a)
{
    unsigned long long q = a; return (long long)(q - q % 16) / 16;
}
```

Current versions of Clang/LLVM compile the first version to a single arithmetic shift right for power of 2 constants, whereas version 9 and older compile all three to optimal code even though both old and new versions produce the same LLVM IR.
Current versions of GCC compile the the last 2 optimally, but not the first. :-(

The first version gets optimized directly to optimal LLVM IR:
```ll
%2 = ashr i64 %0, 4, !dbg !17
```
Versions 2 & 3 both produce:
```ll
%2 = and i64 %0, -16, !dbg !23
%3 = sdiv i64 %2, 16, !dbg !24
```

Which gets turned into a single x86 `sar` instruction in version <= 9:
```asm
sar     rax, 4
```
While it becomes an adjustment + conditional move before the `sar` in versions >= 10:

```asm
and     rdi, -16
lea     rax, [rdi + 15]
test    rdi, rdi
cmovns  rax, rdi
sar     rax, 4
```

**Comment by topperc** [comment]
This seemed to be happening via a very happy accident of DAGCombine optimizing the expanded sdiv by constant code. When `X86TargetLowering::BuildSDIVPow2` was added, it broke. RISC-V for example still generates an arithmetic right shift because it doesn't have `BuildSDIVPow2`.

@rotateright can InstCombine detect the and+sdiv and turn it into a ashr?

**Comment by topperc** [comment]
Looks like if I add the `exact` flag to the sdiv and run InstCombine, we do turn it into a shift. So I guess we're missing logic to set the `exact` flag based on the and?

**Comment by rotateright** [comment]
> Looks like if I add the `exact` flag to the sdiv and run InstCombine, we do turn it into a shift. So I guess we're missing logic to set the `exact` flag based on the and?

That sounds likely. We should check if the dividend has more trailing zeros than the divisor or something like that. I can take a look tomorrow.

**Comment by rotateright** [comment]
https://reviews.llvm.org/D135970
