### ISSUE TITLE
Please update docs for fuse-ctor-homing

### ISSUE THREAD

**Issue by rnk** [llvm/llvm-project#58367]
These docs look stale:
https://clang.llvm.org/docs/UsersManual.html#cmdoption-fuse-ctor-homing
"This flag is not enabled by default, and needs to be used with -cc1 or -Xclang."

I believe it is enabled by default at this point. I wasn't able to find it in any past release notes, though.

**Comment by rnk** [comment]
+@dwblaikie , since we were discussing docs

**Comment by rnk** [comment]
Amy, did we do this?

**Comment by amykhuang** [comment]
apparently, yes https://reviews.llvm.org/D136188
