### ISSUE TITLE
Clang static analyzer could try catching invariant loop conditions

### ISSUE THREAD

**Issue by ryao** [llvm/llvm-project#58369]
Recently, I wrote this C code in a patch that refactored a mature codebase to avoid a very rare bug:

`for (zv = avl_first(t); zv != NULL; AVL_NEXT(t, zv)) { stuff(); }`

Unfortunately, the result had been an infinite loop since it should have been:

`for (zv = avl_first(t); zv != NULL; zv = AVL_NEXT(t, zv)) { stuff(); }`

The loop block has been simplified since it is not important here.

I ran Clang 14's static analyzer on this to try to get a hint as to what I did wrong, but it missed this. I missed it despite looking at the patch many times. Another developer looked at the patch multiple times and missed this too.

While this mistake is more common for new C programmers, it is incredibly rare for experienced C programmers, which causes us to miss it when we make it. I ended up using a mix of dynamic tracing and print statements (because the dynamic tracing was a little quirky) before finally identifying the problem. This was in kernel code. It caused a memory leak that took down the system in less than 2 minutes and the system would take several minutes to reboot, so I had very little time try to diagnose what I did wrong at runtime until I finally identified the problem loop and put a `msleep(100);` call into it. :/

A loop invariant condition like this seems like something that would be fairly easy to check. It would be nice if Clang's static analyzer could warn about this (while not warning about the obviously intentional `while(1) { doSomething(); }`.

**Comment by haoNoQ** [comment]
There's a clang-tidy check for this (`bugprone-infinite-loop`), could you see if it covers your case?

I'm definitely interested in seeing if the static analyzer could do better, as the problem is somewhat path-sensitive (i.e, the problem of finding an individual execution path that's stuck in an infinite loop, is something that the static analyzer's path-sensitive engine is supposed to be naturally good at) but my initial experiments didn't go well because in a lot of cases it boils down to very good constraint solving, which we something don't have.

**Comment by ryao** [comment]
Is there documentation on how to use clang-tidy with a build system that passes various include directories to it?

At the moment, I get:

```
$ clang-tidy --checks=bugprone-infinite-loop module/zfs/zil.c 
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "module/zfs/zil.c"
No compilation database found in /home/richard/zfs/module/zfs or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
1 error generated.
Error while processing /home/richard/zfs/module/zfs/zil.c.
/home/richard/zfs/module/zfs/zil.c:30:10: error: 'sys/zfs_context.h' file not found [clang-diagnostic-error]
#include <sys/zfs_context.h>
         ^~~~~~~~~~~~~~~~~~~
Found compiler error(s).
```

As it is, I need to modify the build system to run it, so I cannot give you an immediate answer (unless I make a minimal test case, but this working there would not always mean it works on the real thing).

**Comment by EugeneZelenko** [comment]
@ryao: Do you use CMake in your project? If so, set `CMAKE_EXPORT_COMPILE_COMMANDS` to `ON`. Then point to Clang-tidy to compile database with `-p` command-line option,

**Comment by ryao** [comment]
@EugeneZelenko Unfortunately, no. We use autotools + make.

I had deleted my previous comment since I thought that I was being lazy by asking, since I could manually get the include directories and defines, but clang-tidy is not happy with something like:

```
(cd /usr/src/linux && clang-tidy -nostdinc -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/compiler-version.h -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -include /home/richard/zfs/zfs_config.h -I/home/richard/zfs/include -I/home/richard/zfs/include/os/linux/kernel -I/home/richard/zfs/include/os/linux/spl -I/home/richard/zfs/include/os/linux/zfs -I/home/richard/zfs/include -D_KERNEL -DDEBUG -UNDEBUG  -DMODULE  -DKBUILD_BASENAME='"zil"' -DKBUILD_MODNAME='"zfs"' -D__KBUILD_MODNAME=kmod_zfs /home/richard/zfs/module/zfs/zil.c)
```

I will figure this out when I get back from dinner.

**Comment by haoNoQ** [comment]
IIRC clang-tidy accepts compiler flags after an `--`.

**Comment by EugeneZelenko** [comment]
@ryao: you could use https://github.com/rizsotto/Bear to intercept compile commands from `make`. Actually this code should be part of Static Analyzer as `scan-build`, but I'm didn't use myself.

**Comment by ryao** [comment]
Thanks. It found it:

```
/home/richard/zfs/module/zfs/zil.c:1455:27: warning: variable 'zv' used in loop condition not modified in loop body [clang-diagnostic-for-loop-analysis]
                for (zv = avl_first(t); zv != NULL; AVL_NEXT(t, zv)) {
                                        ^~
Suppressed 1 warnings (1 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
```

I will let you close this unless you think there is some reason to keep this open.

**Comment by ryao** [comment]
Actually, that leaves me with one question. Can I get clang-tidy to run using `scan-build`? That is how I typically do things.

**Comment by haoNoQ** [comment]
Not yet. I was working on it in https://reviews.llvm.org/D95403 but got distracted :(

**Comment by EugeneZelenko** [comment]
@ryao: I don't think so, Clang-tidy should just be run on compile database. `run-clang-tidy.py` allows to run Clang-tidy in parallel.

**Comment by ryao** [comment]
Alright. Should I close this? I am not sure if there is anything left to do here.
