### ISSUE TITLE
[Flang] Compilation error in pop2

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#58374]
I have a small reproducer. I get the following error
```console
error: Semantic errors in my_test.f90
./my_test.f90:5:12: error: Internal error: Expression analysis failed on: Expr -> ArrayConstructor -> AcSpec
| AcValue -> Expr -> FunctionReference -> Call
| | ProcedureDesignator -> Name = 'trim'
| | ActualArgSpec
| | | ActualArg -> Expr -> Designator -> DataRef -> Name = 'n'

    call sb1((/trim(n)/))
```
in
```f90
program mn
  character(len=6) :: n
  n = 'hello '
  call sb1((/trim(n)/))
contains                                 
subroutine sb1(nm)
  character(*) :: nm(:)
  print *, len(nm(1))
end subroutine
end program
```
It was previously computing an incorrect result. So it is probably not a regression but pop2 test version used to build and run correctly before the change eb1eb7a144ba.

**Comment by kiranchandramohan** [comment]
The frontend error is fixed by https://reviews.llvm.org/D139041. Now the same program hits a TODO in lowering.

```
/llvm-project/flang/lib/Lower/ConvertExpr.cpp:4351: not yet implemented: character array expression temp with dynamic length
```

**Comment by jeanPerier** [comment]
To answer @ceseo related question  (https://github.com/llvm/llvm-project/issues/63319#issue-1757637279), the feature has been implemented in HLFIR (but pop2_s is still blocked in HLFIR with a TODO about user defined assignment, I am currently working on this).

**Comment by kiranchandramohan** [comment]
HLFIR fixes the pop2 issue. This can be closed when we enable HLFIR by default.

**Comment by ceseo** [comment]
I can confirm this is working now. We can close this, if there are no objections.

**Comment by kiranchandramohan** [comment]
Please go ahead and close.
