### ISSUE TITLE
make_cxx_dr_status is currently broken

### ISSUE THREAD

**Issue by royjacobson** [llvm/llvm-project#58382]
Our DR documentation relies on make_cxx_dr_status.py to update cxx_dr_status.html to automatically update the table. However, we've been doing some manual updates to the table in recent months and it's currently not possible to run the script. Current problems are:

DR2565' test (https://github.com/llvm/llvm-project/commit/3d7946c580055dade1dcf4b632738cc54e1a25a9) is marked with the wrong number - dr252 instead of dr2565. Because the DR's status is 'open', fixing this typo makes the script hit the assert in make_cxx_dr_status.py:169. What's our policy on DRs where we implemented the obvious fix even if the committee hasn't yet voted that in?
DR692 and DR1395 (https://reviews.llvm.org/D128745) doesn't have a DR test so the status gets reverted to 'Unknown'.
DR2338 (https://reviews.llvm.org/D130058) has a test that's not updated to a recent fix in https://reviews.llvm.org/D130058 so the 'fixed-in' version is reverted to 12 from 16.

@shafik @erichkeane @yuanfang-chen Could you maybe have a look at those DRs fixes and their tests?

**Comment by erichkeane** [comment]
Woops! Thanks for the heads up.  I'm not sure what we should do for 2565... we were in a position where we had 1/2 of it implemented, and GCC had it already, so I figured we should finish it. I also suspect that is the direction core will go.  

I suspect we should replace the markup-comment with one that just says that we implement the proposal, and remind ourselves to fix the comment when it is fixed.

**Comment by yuanfang-chen** [comment]
> What's our policy on DRs where we implemented the obvious fix even if the committee hasn't yet voted that in?

Most of the time, "Open" DRs have no solutions. But sometimes it needs a speculative fix to avoid regressions in other places. I think the simplest thing to do is to handle these in the 
`make_cxx_dr_status.py` script. I'll send out a patch.

DR2338 (https://reviews.llvm.org/D130058) should update the dr test with the newest test cases and then change `namespace dr2338 { // dr2338: 12` to `namespace dr2338 { // dr2338: 16`.

**Comment by AaronBallman** [comment]
Can this issue now be closed as resolved?

**Comment by royjacobson** [comment]
The script works now, so this can be closed

But I noticed `cxx_dr_status.html` says Clang 12 for DR2338, which was 'fixed' in https://reviews.llvm.org/D138835, perhaps accidentally. 

@shafik, could you maybe take a quick look at this?
