### ISSUE TITLE
DIE address ranges are not contained in its parent's ranges when use LTO

### ISSUE THREAD

**Issue by DianQK** [llvm/llvm-project#58393]
When linking these two LLVM IRs,  dsymutil will report no mapping for range or inconsistent range data warnings.

`foo.swift`
```swift
import AppKit.NSLayoutConstraint

public class Foo {
    
    public var c: Int {
        get {
            Int(NSLayoutConstraint().constant)
        }
        set {
        }
    }

}
```

`main.swift`
```swift
// no mapping for range
let f: Foo! = nil
// inconsistent range data
//let l: Foo = Foo()
```

I made an Xcode project for this example.

[no-mapping-for-range.zip](https://github.com/llvm/llvm-project/files/9795006/no-mapping-for-range.zip)

And https://reviews.llvm.org/D136039 should fix the issue.

**Comment by dwblaikie** [comment]
FWIW, You don't need to file bugs for issues already under review - you can attach extra info/etc to the review & it's probably easier to keep all the discussion in one place when that happens.

**Comment by DianQK** [comment]
Okay, I closed the issue.
