### ISSUE TITLE
Incorrect code generation when we use __builtin_constant_p built-in function

### ISSUE THREAD

**Issue by alex-curiou** [llvm/llvm-project#58400]
Incorrect codegeneration from version 8.0.0:
 - with -O2 flag the return NOT CORRECT value 13 (https://godbolt.org/z/xs9EzP4Mo);
 - with -Og flag the return CORRECT value 60 (https://godbolt.org/z/v8E3xGvT6);

From version 13.0.0 and till 15.0.0 INCORRECT code generation for both -Og and -O2,
the return value is 13, but the bar func code is generated to calculate 60:
 - with -O2 flag: https://godbolt.org/z/nzn5zT65e
 - with -Og flag: https://godbolt.org/z/4osxW8fnz

The minimized example of code:

~~~
#define test(val1) \
  __builtin_constant_p(val1) ? (val1 + 10) : (val1 * 20);


unsigned int bar(unsigned int value1) {
    return test(value1);
}

int main(void) {
    unsigned int a = bar(3);

    return a;
}
~~~

The __builtin_constant_p considers the val1 value to be NOT known to be constant at compile time. So the generated code is
val1 * 20

But optimizer considers that the value is WELL known and can WELL be calculated.
So, the return value of func bar is calculated at compile time and the call to the bar func is dropped away.

And the final return value is WRONG:
val1 + 10

As a result we have different return values with -O2 and -Og optimization flags, 13 and 60 accordingly.

For example, here is the compiler output for version 8.0.0:

-O2 will return 13
https://godbolt.org/z/xs9EzP4Mo

~~~
bar:                                    # @bar
        shl     edi, 2
        lea     eax, [rdi + 4*rdi]
        ret
main:                                   # @main
        mov     eax, 13
        ret
~~~

-Og will return 60
https://godbolt.org/z/v8E3xGvT6

~~~
bar:                                    # @bar
        shl     edi, 2
        lea     eax, [rdi + 4*rdi]
        ret
main:                                   # @main
        mov     edi, 3
        jmp     bar
~~~

**Comment by bwendling** [comment]
This doesn't seem like a fault in the implementation of `__builtin_constant_p`. The behavior you're looking at here is depends upon resolving `__builtin_constant_p` after inlining. At different optimization levels, the inlining *will* occur. At `-Og` it doesn't occur (and is turned into a tail call).

From GCC's documentation (https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html):

> Built-in Function: int __builtin_constant_p (exp)
>
> > You can use the built-in function __builtin_constant_p to determine if a value is known to be constant at compile time and hence that GCC can perform constant-folding on expressions involving that value. The argument of the function is the value to test. The function returns the integer 1 if the argument is known to be a compile-time constant and 0 if it is not known to be a compile-time constant. **A return of 0 does not indicate that the value is not a constant, but merely that GCC cannot prove it is a constant with the specified value of the -O option.**
> >
> > _[snip]_
> >
> > You may use this built-in function in either a macro or an inline function. However, if you use it in an inlined function and pass an argument of the function as the argument to the built-in, GCC never returns 1 when you call the inline function with a string constant or compound literal (see Compound Literals) and **does not return 1 when you pass a constant numeric value to the inline function unless you specify the -O option.**
