### ISSUE TITLE
Possible objcopy regression in LLVM 15

### ISSUE THREAD

**Issue by dimpolo** [llvm/llvm-project#58407]
`objcopy -O binary` produces a broken binary from the [test.elf](https://github.com/llvm/llvm-project/files/9800058/test.zip) file.

Regressed version:
```console
$ rust-objcopy -V                        
llvm-objcopy, compatible with GNU objcopy
LLVM (http://llvm.org/):
  LLVM version 15.0.2-rust-1.66.0-nightly
  Optimized build.
  Default target: x86_64-pc-windows-msvc
  Host CPU: znver1
```
Version it worked on:
```console
$ rust-objcopy -V
llvm-objcopy, compatible with GNU objcopy
LLVM (http://llvm.org/):
  LLVM version 14.0.6-rust-1.64.0-stable
  Optimized build.
  Default target: x86_64-pc-windows-msvc
  Host CPU: znver1
```

Note that I was using LLVM tools shipped with Rust, but presumably this doesn't make a difference here?

[Corresponding Rust issue](https://github.com/rust-lang/rust/issues/102983)

Quoting @adamgreig's initial analysis:

> The elf in question has the following sections:
> 
> ```
> Program Header:
>     LOAD off    0x000000f4 vaddr 0x08004000 paddr 0x08004000 align 2**2
>          filesz 0x000000c0 memsz 0x000000c0 flags r--
>     LOAD off    0x000001b4 vaddr 0x080040c0 paddr 0x080040c0 align 2**2
>          filesz 0x00006764 memsz 0x00006764 flags r-x
>     LOAD off    0x00006924 vaddr 0x0800a824 paddr 0x0800a824 align 2**4
>          filesz 0x00000ff8 memsz 0x00000ff8 flags r--
>     LOAD off    0x0000791c vaddr 0x20000000 paddr 0x20000000 align 2**2
>          filesz 0x00000000 memsz 0x00000444 flags rw-
> ```
> Notably the third section has an offset of 0x6924 and an alignment of 16 which doesn't match, but since the first section has an offset of 0xf4 the resulting start of the third section in the output is 0x6830 which is aligned. In the working binary, which is identical between GCC, LLVM14, and probe-rs, that third section starts at byte 0x6830, while in the new LLVM15-produced binary the third section starts at address 0x683C, 12 bytes later, which would be 16-byte aligned if it weren't for the initial 0xf4 offset.
> 
> I think the only relevant commit in LLVM is https://github.com/llvm/llvm-project/commit/0c01f42fad413163320c24ab4e513fbd282e4168.
> 
> I am not entirely sure what the correct behaviour is but I guess it's the old behaviour. I don't know why this ELF has such a weird set of offsets and different alignments, either.

**Comment by berkus** [comment]
Hit this issue with 

```
llvm-objcopy, compatible with GNU objcopy
LLVM (http://llvm.org/):
  LLVM version 16.0.5-rust-1.72.0-nightly
  Optimized build.
```
(as part of rust-objcopy)

The resulting binary's .rodata was offset by 12 bytes as well....

**Comment by MaskRay** [comment]
`test.elf` has an invalid alignment for `.rodata` as `sh_addr%sh_addralign!=0`. 
```
% llvm-readelf -WS ./test.elf
There are 22 section headers, starting at offset 0x13bd84:

Section Headers:
  [Nr] Name              Type            Address  Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .vector_table     PROGBITS        08004000 0000f4 0000c0 00   A  0   0  4
  [ 2] .text             PROGBITS        080040c0 0001b4 006764 00  AX  0   0  4
  [ 3] .rodata           PROGBITS        0800a824 006924 000ff8 00  AM  0   0 16
...
```

https://www.sco.com/developers/gabi/latest/ch4.sheader.html says

> The value of sh_addr must be congruent to 0, modulo the value of sh_addralign.

You may want to check how the executable is created.

**Comment by berkus** [comment]
Could we maybe at least fail the objcopy if ELF file is apparently invalid, like `sh_addr%sh_addralign!=0`? Or produce some visible diagnostic. 

I don't know how binutils' objcopy makes it work correctly in this case, but if llvm's objcopy gonna produce an invalid binary, I'd rather it fail with an error instead.

**Comment by berkus** [comment]
> You may want to check how the executable is created.

It was created with rust-lld.

**Comment by workingjubilee** [comment]
Using a linker script.
