### ISSUE TITLE
misc-const-correctness hurts clangd interactive performance on large files

### ISSUE THREAD

**Issue by sam-mccall** [llvm/llvm-project#58412]
This is superlinear (+60% reparse time on clang-tools-extra/clangd/AST.cpp, +1600% reparse time on clang/lib/Sema/SemaExpr.cpp).

This check was added in the 15.x cycle, and people can enable it inadvertently. We blocked it on trunk, would be great to get this into the 15.x branch.

**Comment by JonasToth** [comment]
Thats really unfortunate :/

**Comment by drcxd** [comment]
I was using this check with llvm 15.0.0. After I upgrade to 15.0.6 I found that this check does not work anymore. Then after some search I came here, is there any chance this check become viable in the future? I think it is helpful.

**Comment by kadircet** [comment]
@drcxd i think you should bring it up to the chekc's maintainer so that they can try to improve its performance.

**Comment by drcxd** [comment]
@kadircet Thanks, I'll try that!
