### ISSUE TITLE
[clang-format]: Cannot align declarations in lambda when initializing lambda with uniform initialization.

### ISSUE THREAD

**Issue by aleksanderostrup** [llvm/llvm-project#58436]
In modern C++ we like to have a uniform initialization of our variables. For this we uses the {} syntax.
However, when using this to initialize a lambda function with variable declarations, we get wrong formatting:

I have reduced the error to the following minimum example:

**.clang-format
---
Language:        Cpp
AlignConsecutiveDeclarations: Consecutive
Cpp11BracedListStyle: false**

And a cpp file:
```cpp
#include <mutex>

void SomeFnc() {
  auto const callback{ []() {
    std::mutex m;
    std::scoped_lock lk{ m };
  } };
}
```

Formatting with the above .clang-format gives:
```cpp
#include <mutex>

void SomeFnc() {
  auto const callback{ []() {
    std::mutexm;
    std::scoped_locklk{ m };
  } };
}
```

I.e., it removes the space between the type and the identifier. This produces uncompilable code.

A short-term fix is to initialize without {}. This produces:

```cpp
#include <mutex>

void SomeFnc() {
  auto const callback = []() {
    std::mutex       m;
    std::scoped_lock lk{ m };
  };
}
```

But a {} style would be preferable to stay consistent in initialization.

**Comment by rymiel** [comment]
This was fixed by 6c7e6fc7b6654b7ecd364f352f8ffd6dfecbf77b (it is fixed in clang-format 15)
