### ISSUE TITLE
miscompile from aarch64 backend with global isel

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#58431]
Let's take this function:
```llvm
define i32 @f(i64 %0) {
  %2 = trunc i64 %0 to i32
  %3 = freeze i32 %2
  %4 = zext i32 %3 to i64
  %5 = urem i64 %4, 10
  %6 = trunc i64 %5 to i32
  ret i32 %6
}
```
When `0xa8552d4928501120` is passed as an argument, the Selection DAG backend and also Alive2 believe that it returns 4. On the other hand, the global ISel backend generates code that returns 0.

Selection DAG gives:
```asm
f:                                      // @f
        mov     x8, #-3689348814741910324
        and     x9, x0, #0xffffffff
        movk    x8, #52429
        umulh   x8, x9, x8
        mov     w9, #10
        lsr     x8, x8, #3
        msub    w0, w8, w9, w0
        ret
```

Whereas global ISel gives:
```asm
f:                                      // @f
        mov     w8, #10
        udiv    x9, x0, x8
        msub    x0, x9, x8, x0
        ret
```

https://gcc.godbolt.org/z/xM44TYnbb

Test driver:
```c
#include <stdio.h>

unsigned f(unsigned long);

int main(void) {
  printf("%x\n", f(0xa8552d4928501120L));
}
```

cc @aemerson @ornata @nunoplopes @ryan-berger @nbushehri @efriedma-quic @hatsunespica

**Comment by bcl5980** [comment]
It looks SUBREG_TO_REG also can't coalesce.
`%3:gpr64 = SUBREG_TO_REG 0, %0.sub_32:gpr64common, %subreg.sub_32`
