### ISSUE TITLE
Wrong code at -Os on x86_64-linux_gnu (LoopFlattenPass)

### ISSUE THREAD

**Issue by shao-hua-li** [llvm/llvm-project#58441]
```console
% clang-tk -v
clang version 16.0.0 (https://github.com/llvm/llvm-project.git faf0e1fbf90f14a92042a83f6cb1239791674412)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /zdata/shaoli/compilers/ccbuilder-compilers
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
%
% clang-tk -w -O0 a.c && ./a.out
6
% clang-tk -w -Os a.c && ./a.out
1
% cat a.c
void printf();
int c;
int a(int b) {
    int t = 0;
    while (t < 7 && b) t++;
    return t;
}
int e() {
    int l;
    for (l = 0; l < 6; l = l + 1)
        for (c = 0; c < 6; c = (a(6) ^ 7) + c + 1)
            ;
}
int main() {
    e();
    printf("%d\n", c);
}
%
```
Compiler explorer: https://godbolt.org/z/x1jvrPj9a
`opt-bisect-limit` suggests that the issue might be in `LoopFlattenPass`.

**Comment by nikic** [comment]
cc @sjoerdmeijer

**Comment by sjoerdmeijer** [comment]
Thanks for the report and the ping. 
I am away from keyboard for 2 hours, but will revert it as soon as I am back. But please go ahead and revert it if you want to see this done earlier.

**Comment by sjoerdmeijer** [comment]
Reverted the enabling of loopflatten by default in: 
https://reviews.llvm.org/rG5b9597f59a445523bd59b5251ab1c2865e74919f

Going to take a look at this miscompilation, thanks again for reporting.

**Comment by sjoerdmeijer** [comment]
Fixed by @davemgreen in https://reviews.llvm.org/D138404

**Comment by davidbolvansky** [comment]
> Reverted the enabling of loopflatten by default in: https://reviews.llvm.org/rG5b9597f59a445523bd59b5251ab1c2865e74919f
> 
> Going to take a look at this miscompilation, thanks again for reporting.

Now fixed so can you enable it by default again ?

**Comment by nikic** [comment]
@davidbolvansky It was enabled and then reverted again due to https://github.com/llvm/llvm-project/issues/59339.

**Comment by davidbolvansky** [comment]
Thanks for info
