### ISSUE TITLE
[coroutines] incorrect transformation removes co_await side effects in non-taken branch

### ISSUE THREAD

**Issue by jacobsa** [llvm/llvm-project#58459]
Here is a simple program that contains a chain of two coroutines, with one awaiting the other. The awaiter returned by `await_transform` calls an external function (`SomeExternalFunc`) in its `await_suspend` method:

```c++
#include <coroutine>
#include <cstddef>

// A function defined in another translaiton unit.
void SomeExternalFunc();

struct MyTask{
  struct promise_type {
    MyTask get_return_object() { return {std::coroutine_handle<promise_type>::from_promise(*this)}; }
    std::suspend_always initial_suspend() { return {}; }

    void unhandled_exception();
    void return_void() {} 

    auto await_transform(MyTask task) {
      struct Awaiter {
        bool await_ready() { return false; }

        // Resume the lazy coroutine, first calling the external function.
        std::coroutine_handle<promise_type> await_suspend(std::coroutine_handle<promise_type> h) {
          callee.resume_when_done = h;
          SomeExternalFunc();
          return std::coroutine_handle<promise_type>::from_promise(callee);
        }

        // Clean up and then evaluate to null.
        std::nullptr_t await_resume() {
          std::coroutine_handle<promise_type>::from_promise(callee).destroy();
          return nullptr;
        }

        promise_type& caller;
        promise_type& callee;
      };

      return Awaiter{*this, task.handle.promise()};
    }
    
    // Resume the coroutine that started us when we're done.
    auto final_suspend() noexcept {
      struct Awaiter {
        bool await_ready() noexcept { return false; }
        std::coroutine_handle<promise_type> await_suspend(std::coroutine_handle<promise_type> h) noexcept {
          return to_resume;
        }

        void await_resume() noexcept;

        std::coroutine_handle<promise_type> to_resume;
      };

      return Awaiter{resume_when_done};
    }

    // The coroutine to resume when we're done.
    std::coroutine_handle<promise_type> resume_when_done;
  };

  // A handle for the coroutine that returned this task.
  std::coroutine_handle<promise_type> handle;
};

MyTask DoSomethingElse() {
  co_return;
}

// A coroutines that awaits a call to another.
MyTask DoSomething() {
  co_await DoSomethingElse();
  co_return;
}
```

When [compiled](https://godbolt.org/z/e9Mrz9hEa) with `-std=c++20 -O1`, this correctly generates a call to `SomeExternalFunc` from `DoSomething.resume`:

```asm
DoSomething() [clone .resume]:                # @DoSomething() [clone .resume]
[...]
        call    SomeExternalFunc()@PLT
[...]
```

However if we [change](https://godbolt.org/z/WGbdG9r8c) the `co_await DoSomethingElse();` statement to be a branch:

```c++
if (co_await DoSomethingElse() != nullptr) {}
```

then all mentions of `SomeExternalFunc` are gone from the [generated code](https://gist.github.com/jacobsa/c6f5515f4ed66c93aae56627279b91a6).

**I believe clang is wrong to eliminate this branch.** Although it's true that the branch can never be taken, evaluating the `co_await` expression may have a side effect through the call to `SomeExternalFunc`. (Indeed I found this bug because clang incorrectly removed such side effects in a real codebase.)

**Comment by jacobsa** [comment]
@ChuanqiXu9

**Comment by ChuanqiXu9** [comment]
Yeah, it should be true that this is a bug. And it looks like it occurs in the frontend and it is not related to optimizer. It is interesting that we can avoid the problem by changing the return of `await_resume` from `std::nullptr_t` to `void*`: https://godbolt.org/z/Wrc3fcE35

**Comment by ChuanqiXu9** [comment]
After some simple experiment,  I feel like this only happens with `std::nullptr_t`

**Comment by jacobsa** [comment]
Hah very strange. I guess it makes sense, in that `std::nullptr_t` is special in having only one state.

**Comment by ChuanqiXu9** [comment]
> Hah very strange. I guess it makes sense, in that `std::nullptr_t` is special in having only one state.

Yeah, and the interesting part here is that if we define a type which has only one state: https://godbolt.org/z/v5Wd3Mn4M. It is the same if we define an empty class: https://godbolt.org/z/q3vEc3oTn.

**Comment by ChuanqiXu9** [comment]
This looks to get fixed in trunk: https://godbolt.org/z/jEdah61KT.

Feel free to reopen this if I made an oversight.

**Comment by jacobsa** [comment]
@ChuanqiXu9 I think that's the wrong link; it's your workaround from [this comment](https://github.com/llvm/llvm-project/issues/58459#issuecomment-1283473790) where the return type is `void*`. If you use `std::nullptr_t` as in the original report, the call to `SomeExternalFunc` is still eliminated at trunk: https://godbolt.org/z/WGbdG9r8c

Could you please reopen? I don't have permission to do so.

**Comment by ChuanqiXu9** [comment]
Oh, sorry for the oversight.

**Comment by jacobsa** [comment]
No worries, thanks!

**Comment by ChuanqiXu9** [comment]
It turns out that this is not a coroutine issue: https://github.com/llvm/llvm-project/issues/64923 and let's track the issue there and close this one.

**Comment by jacobsa** [comment]
Wow, it's surprising that it's not coroutine-specific. Thanks for narrowing it down.
