### ISSUE TITLE
[AArch64] Fold the mul and add into mla

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#58467]
Test case: https://gcc.godbolt.org/z/Yaa1sj9qc
```cpp
void f(int * __restrict__ a, int * __restrict__ b, int * __restrict__ r) {
  for (int m = 0; m < 64; m++) {
    int c = 0;
    // #pragma unroll
    for (int i = 0; i < 32; i++) {
      c += a[i] * b[m * 32 + i];
    }
    r[m] = c;
  }
}
```
This case first reported in https://bugs.llvm.org/show_bug.cgi?id=35448, and now both GCC and LLVM can generate the SLP for the loops, but the Clang's version still have less mla in the kernel body.
**GCC: 7 mla** VS **Clang: 4 mla**

**Comment by vfdff** [comment]
* Machine combine don't fold into mla as some of the adds have no MUL operands
* Type-legalized selection DAG bring in the above issue, such as, we can see the **node t117** no MUL operands（clang++ -march=armv8.2-a -O3 -w -ffast-math ../test.c -S -mllvm -opaque-pointers -mllvm -debug-only=isel）
![image](https://user-images.githubusercontent.com/6094516/196953219-6acc6a27-28c5-4a86-9016-40e5f33881d5.png)

**Comment by bcl5980** [comment]
Gcc compile to a mla chain but llvm choice to break the chain and execute parallel. I believe llvm's perf should be better if cpu float port is enough.

**Comment by vfdff** [comment]
It sounds reasonable , thanks, I think this issue can be closed now.
Yes, llvm break the mla chain and it use 4 group parallel **mul + mla**, so it leaves more **add** instrunctions.
