### ISSUE TITLE
C‘s library file missing how to solve?

### ISSUE THREAD

**Issue by Stark-qan** [llvm/llvm-project#58460]
C library file missing error when using toolchain.
Error is as follows：
```console
In file included from hello.c:1:
/usr/include/stdio.h:27:10: fatal error: 'bits/libc-header-start.h' file not found
#include <bits/libc-header-start.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
But once I referenced the GCC C library, compilation worked.

**Comment by Stark-qan** [comment]
The compilation options I used are as follows:
`cmake -DLLVM_PARALLEL_LINK_JOBS=1 -DLLVM_TARGETS_TO_BUILD="RISCV" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_INSTALL_PREFIX=/$USER/opt/llvm  -DLLVM_DEFAULT_TARGET_TRIPLE="riscv64-unknown-linux-gnu"  -G "Ninja" ../llvm`
Are my compilation options causing errors?

**Comment by EugeneZelenko** [comment]
@Stark-qan: Could you please provide more details: OS, Clang version, etc?

**Comment by xgupta** [comment]
related - https://stackoverflow.com/questions/54082459/fatal-error-bits-libc-header-start-h-no-such-file-or-directory-while-compili.
`sudo apt-get install gcc-multilib` should fix the issue.
