### ISSUE TITLE
-Wimplicit-function-declaration emitted with atomic builtins

### ISSUE THREAD

**Issue by thesamesam** [llvm/llvm-project#58478]
Hello,

It looks like the following test program emits a `-Wimplicit-function-declaration` warning (which becomes an error with Clang 16):
```c
#include <stdint.h>
int main() {
    char i;
    __atomic_exchange_1(&i, 1, 0);
    return 1;
}
```

```console
$ gcc /tmp/foo.c -o /tmp/foo && /tmp/foo
$
$ clang /tmp/foo.c -o /tmp/foo
/tmp/foo.c:4:5: error: call to undeclared function '__atomic_exchange_1'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    __atomic_exchange_1(&i, 1, 0);
    ^
1 error generated.
$
```

This breaks building systemd with newer Clang: https://github.com/systemd/systemd/issues/25057 (originally reported at https://bugs.gentoo.org/877259).

I don't see what could provide the prototype for builtins, so I _think_ it's a Clang bug, given GCC compiles it fine.

**Comment by thesamesam** [comment]
cc @AaronBallman

**Comment by AaronBallman** [comment]
Thanks for the report! We don't have a builtin named `__atomic_exchange_1` and we get link errors trying to use the implicit function declaration: https://godbolt.org/z/vE1d3aosc -- that symbol is being provided by `-latomic` and is not a compiler builtin (at least for Clang). As best I can tell from a quick reading of https://gcc.gnu.org/wiki/Atomic/GCCMM/LIbrary, it seems like those are external interfaces.

**Comment by thesamesam** [comment]
Oh I see, this comes back to some of the bits like https://reviews.llvm.org/D85044 which I keep getting confused about! I think this is definitely an issue on the systemd side then. Cheers fo the explanation.

**Comment by thesamesam** [comment]
I've thrown back to systemd at https://github.com/systemd/systemd/issues/25057#issuecomment-1284477060. Thanks!

**Comment by medhefgo** [comment]
Sorry, this is silly. There is no header for this because they are gcc builtins. And clang supports these builtins except where they don't and then everyone else is supposed to work around this? A quick glance tells me that `__atomic_exchange_n` seems to be supported, so why not the other variants that gcc offers?!?! What am I missing here?!?

**Comment by thesamesam** [comment]
Clang _doesn't_ support these builtins with `compiler-rt`. It only does when using `libgcc`.

**Comment by AaronBallman** [comment]
> I don't know if there's a solid list of the builtins `compiler-rt` has.

I don't know how up-to-date this is, but: https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/builtins/README.txt

**Comment by medhefgo** [comment]
> Clang _doesn't_ support these atomic builtins with `compiler-rt`. It only does when using `libgcc`. When trying to use `compiler-rt`, you end up hitting problems like this :(

Since when is compiler-rt the default? It's using libgcc (otherwise, according to you, the other builtins wouldn't work?) and yet the test case fails (I've added `-rtlib=libgcc` just to be sure).

Also there is `compiler-rt/lib/builtins/atomic.c`, which sounds to me like they are supported.

**Comment by thesamesam** [comment]
> > Clang _doesn't_ support these atomic builtins with `compiler-rt`. It only does when using `libgcc`. When trying to use `compiler-rt`, you end up hitting problems like this :(
> 
> Since when is compiler-rt the default? It's using libgcc (otherwise, according to you, the other builtins wouldn't work?) and yet the test case fails (I've added `-rtlib=libgcc` just to be sure).
> 
> Also there is `compiler-rt/lib/builtins/atomic.c`, which sounds to me like they are supported.

It's not the default, but distributors and users may choose to enable it by default.

I'm confused based on https://llvm.org/docs/Atomics.html#libcalls-atomic. It seems to claim LLVM should support these.

**Comment by nikic** [comment]
There are two things involved here: Atomic builtins exposed by the compiler to the user, and atomic libcalls emitted by the compiler backend and provided by libatomic. Confusingly, both of these have similar, and in some cases overlapping, names, but are completely distinct concepts. An `__atomic` builtin might lower to a native atomic instruction, a `__sync` libcall, or a `__atomic` libatomic libcall.

The names of the compiler builtins are `__atomic_exchange` and `__atomic_exchange_n`. These might ultimately be backed by `__atomic_exchange`, `__atomic_exchange_1`, etc. libatomic libcalls on some platforms, but those don't have any direct relation to the builtins.

C code should not be using `__atomic_exchange_1`, unless the intention is to actually hardcode a call to libatomic, which is very likely not intended.
