### ISSUE TITLE
Broken link to googleTest repos

### ISSUE THREAD

**Issue by DerKasper** [llvm/llvm-project#58497]
In the file: 
readability-avoid-underscore-in-googletest-name.rst
 which should be the source for https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/google-readability-avoid-underscore-in-googletest-name.html
the given link to the googltest repo is not up to date. It links to: 
https://github.com/google/googletest/blob/main/googletest/docs/faq.md#why-should-test-suite-names-and-test-names-not-contain-underscore

but some time ago, the documentation was moved within that repository to:
https://github.com/google/googletest/blob/main/docs/faq.md#why-should-test-suite-names-and-test-names-not-contain-underscore

**Comment by DerKasper** [comment]
Same link is old within:
C:\a\llvm\clang-tools-extra\test\clang-tidy\checkers\readability\avoid-underscore-in-googletest-name.cpp
And also in readability-avoid-underscore-in-googletest-name.rst the _disable individual tests: https://github.com/google/googletest/blob/master/googletest/docs/faq.md#why-should-test-suite-names-and-test-names-not-contain-underscore should point to https://google.github.io/googletest/advanced.html#temporarily-disabling-tests

Further the links within llvm\utils\unittest are brocken, as the googletest used is not the newest version, which contains updated links. => Not part of this issue. 

I will try to provide a patch, but setting up a contribution with Arcanist etc. seems a lot of work for that. I hope my motivation holds...

**Comment by DerKasper** [comment]
Successfully provided a patch (without ever getting arcanist to get running, but just using git worked fine)
https://reviews.llvm.org/D136424

**Comment by carlosgalvezp** [comment]
AFAICS the issue is fixed, great!
