### ISSUE TITLE
CFI annotations in inline asm with -f[no-]asynchronous-unwind-tables

### ISSUE THREAD

**Issue by dvyukov** [llvm/llvm-project#58493]
Consider:
```c
void foo() {
  asm volatile(".cfi_adjust_cfa_offset 8;");
}

void bar() {
  asm volatile(".cfi_startproc; .cfi_adjust_cfa_offset 8; .cfi_endproc;");
}
```

When compiling with `-fasynchronous-unwind-tables` I am getting:
```console
$ clang test.c -c -fasynchronous-unwind-tables
test.c:6:16: error: starting new .cfi frame before finishing the previous one
  asm volatile(".cfi_startproc; .cfi_adjust_cfa_offset 8; .cfi_endproc;");
               ^
```

When compiling with `-fno-asynchronous-unwind-tables` I am getting:
```console
$ clang test.c -c -fno-asynchronous-unwind-tables
test.c:2:16: error: this directive must appear between .cfi_startproc and .cfi_endproc directives
  asm volatile(".cfi_adjust_cfa_offset 8;");
               ^
```

So there is no way to write code that would work for both modes.
Clang should either require `.cfi_start/endproc` or not regardless of compilation flags.

`clang version 16.0.0 (https://github.com/llvm/llvm-project.git 5942456a30ea3b71523886d9fa7dc9aa786f5c61)`

**Comment by MaskRay** [comment]
You may dispatch on the macro `__GCC_HAVE_DWARF2_CFI_ASM` which I implemented in https://reviews.llvm.org/D97743

Note: adjusting CFI usually requires you place everything which may be related in one single `asm`

**Comment by dvyukov** [comment]
Aha! Thanks!
I've looked at `compiler-rt/lib/sanitizer_common/sanitizer_asm.h` and seen `__GCC_HAVE_DWARF2_CFI_ASM` there. But it does it wrong, so I concluded that it won't help:
```
#if defined(__clang__) ||                                                      \
    (defined(__GNUC__) && defined(__GCC_HAVE_DWARF2_CFI_ASM))
# define CFI_INL_ADJUST_CFA_OFFSET(n) ".cfi_adjust_cfa_offset " #n ";"
...
```
