### ISSUE TITLE
Missing llvm-bat-dump

### ISSUE THREAD

**Issue by joshcangit** [llvm/llvm-project#58495]
I had an error for `llvm-bat-dump` when building `ccls`
```console
CMake Error at /usr/lib/llvm-16/lib/cmake/llvm/LLVMExports.cmake:1713 (message):
  The imported target "llvm-bat-dump" references the file

     "/usr/lib/llvm-16/bin/llvm-bat-dump"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/llvm-16/lib/cmake/llvm/LLVMExports.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/llvm-16/lib/cmake/llvm/LLVMConfig.cmake:338 (include)
  /usr/lib/cmake/clang-16/ClangConfig.cmake:10 (find_package)
  CMakeLists.txt:72 (find_package)
```

Couldn't find any information about this error online.
Is there a package I haven't installed?
Was a symlink missing?
Is this a deprecated file?

**Comment by lerno** [comment]
This issue is also referenced here: https://github.com/llvm/llvm-project/issues/58317
It's a bug in the cmake scripts. As a workaround: pull in bolt-16 and it works for me at least.

**Comment by joshcangit** [comment]
Yeah, thanks. I was looking for a `bolt-llvm`.
There's no dependency package. It's just `bolt-16`.

**Comment by lerno** [comment]
Don't close this. It's still an issue.

**Comment by joshcangit** [comment]
Oh. So, it supposed to work even without the `bolt-16` package?

**Comment by lerno** [comment]
Yes.

**Comment by rymiel** [comment]
This seems to be fixed for 16? This action: <https://github.com/rymiel/llvm-58075-repro/actions/runs/3323458507/jobs/5493826067> succeeded, whereas it failed a week ago: <https://github.com/rymiel/llvm-58075-repro/actions/runs/3272334321/jobs/5383210930>. Thank you @sylvestre

**Comment by sylvestre** [comment]
yeah, probably
but this is a cmake bizarre change ... 
I don't get why some binaries are added as deps

**Comment by lerno** [comment]
Note that 16 works now.

**Comment by sylvestre** [comment]
yeah, it is because i fixed it with an ugly workaround
https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/commit/d916c393aec45cc4625d867fb0c3181b68c40553
