### ISSUE TITLE
run-clang-tidy.py should only search for clang-apply-replacements if really needed

### ISSUE THREAD

**Issue by rhaschke** [llvm/llvm-project#58508]
Currently, `clang-apply-replacements` is also searched for when `-export-fixes` options is given, but `-fix` isn't:
https://github.com/llvm/llvm-project/blob/3fee9358baab54e4ed646a106297e7fb6f1b4cff/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py#L303-L307

However, the binary is only needed to actually fix issues:
https://github.com/llvm/llvm-project/blob/3fee9358baab54e4ed646a106297e7fb6f1b4cff/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py#L382-L386

**Comment by aabhinavg** [comment]
added the changes at https://reviews.llvm.org/D145477

**Comment by aabhinavg** [comment]
fixed by https://reviews.llvm.org/D145477
