### ISSUE TITLE
Cannot lower "icmp uge <4 x i32> zeroinitializer, ..." for ARMv7

### ISSUE THREAD

**Issue by aaronpuchert** [llvm/llvm-project#58514]
This is reduced from a larger file:
```llvm
define <4 x i32> @vcmpz(<4 x i32> %0) {
  %2 = icmp uge <4 x i32> zeroinitializer, %0
  %3 = sext <4 x i1> %2 to <4 x i32>
  ret <4 x i32> %3
}
```
Compilation with `llc -O2 -march=arm --float-abi=hard -mattr=+armv7-a` fails with:
```
LLVM ERROR: Cannot select: t17: v4i32 = ARMISD::VCMPZ t3, Constant:i32<2>
  t3: v4i32 = bitcast t2
    t2: v2f64,ch = CopyFromReg t0, Register:v2f64 %0
      t1: v2f64 = Register %0
  t16: i32 = Constant<2>
```
The larger file had a more complex tree, but I think it boils down to the `VCMPZ`. Other comparisons are not (necessarily) an issue, e.g. for the opposite `icmp ult` we get
```asm
        vceq.i32        q8, q0, #0
        vmvn    q0, q8
        bx      lr
```

**Comment by davemgreen** [comment]
The backend is probably assuming that `%2 = icmp uge <4 x i32> zeroinitializer, %0` has been simplified into `%2 = icmp eq <4 x i32> %0, zeroinitializer`, but that is not always reliably done.

There is a fix in https://reviews.llvm.org/D136447

**Comment by Vogtinator** [comment]
That fits.

This particular failure was caused by Mesa not doing optimization passes with LLVM 15: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/19217

With the `instcombine` pass the selection failure is gone.

For completeness, the downstream bug report: http://bugzilla.opensuse.org/show_bug.cgi?id=1204267

**Comment by davemgreen** [comment]
I see. Makes sense.

FYI, You likely don't need instsimplify, instcombine should be a super-set of it. But from the look of "After:" in the PR I don't see instsimplify running between `PromotePass` and `InstCombinePass` anyway.

**Comment by aaronpuchert** [comment]
> This particular failure was caused by Mesa not doing optimization passes with LLVM 15

Adding optimizations could make it disappear, but backends should be able to lower non-optimized code.
