### ISSUE TITLE
Missed combination of sub+and

### ISSUE THREAD

**Issue by chfast** [llvm/llvm-project#58523]
I've found a case of `sub+and+sub` which can be combined into single `and`.

```llvm
define i64 @src(i64 %0) {
  %2 = sub nuw i64 71, %0
  %3 = and i64 %2, -8
  %4 = sub i64 64, %3
  ret i64 %4
}

define i64 @tgt(i64 %0) {
  %2 = and i64 %0, 120
  ret i64 %2
}
```
https://alive2.llvm.org/ce/z/MrCTxL

**Comment by RKSimon** [comment]
Any chance that you can generalize this further?

**Comment by bcl5980** [comment]
It looks we can do it like:
https://alive2.llvm.org/ce/z/TmpJVn

But not sure it is most simple transform or not.

**Comment by RKSimon** [comment]
I'm not sure the alive2 test was correct try this? https://alive2.llvm.org/ce/z/UmSzxd

**Comment by bcl5980** [comment]
> I'm not sure the alive2 test was correct try this? https://alive2.llvm.org/ce/z/UmSzxd

Yeah, icmp eq should be 1 if it is pow2. I'm wrong.

**Comment by bcl5980** [comment]
This should be the correct version. But looks much complicated.
https://alive2.llvm.org/ce/z/xzj9Ez

**Comment by chfast** [comment]
Thank you @bcl5980
