### ISSUE TITLE
Clang ignores a constraint in a partial specialization of a class template

### ISSUE THREAD

**Issue by Dann239** [llvm/llvm-project#58534]
I'm trying to create a specialization of the `Foo` class template that only accepts specializations of the `Bar` class template as a template argument. However, clang ignores my `IsBar<T>` constraint and accepts `int` as a template argument.
```cpp
template<typename>
struct Foo;

template<typename>
struct Bar {};

template<typename T>
concept IsBar = requires (T t) { [] <typename U> (Bar<U>& c) {} (t); };

template<IsBar T>
struct Foo<T> {
    static void test() {}
};

int main() {
    Foo<Bar<int>>::test(); // OK

    // static_assert(!IsBar<int>);

    // the following line compiles
    // unless i uncomment the static_assert:
    Foo<int>::test(); // this should not compile
}
```
`static_assert`'ing `!IsBar<int>` seems to make it correctly reject `int`

**Comment by usx95** [comment]
This looks more specific to lambda in the simple-requirement
```cpp
template<typename>
struct Foo;

template<typename T>
concept Add = requires(T t) {
    [](T t) { t++; }(t);
};

template<Add T>
struct Foo<T> {
    static void test() {}
};

int main() {
    Foo<int>::test(); // this should not compile
}
```
gives an assertion failure. It tries to evaluate the dependent lambda without instantiating it properly.
https://godbolt.org/z/fWqbj9Poz

**Comment by zyn0217** [comment]
This should have been fixed by https://github.com/llvm/llvm-project/pull/83997.
I'll close the PR once the patch gets on godbolt.

**Comment by zyn0217** [comment]
And here it is: https://godbolt.org/z/474vsh8MP
Closing.
