### ISSUE TITLE
OpenMP compilation hang on windows

### ISSUE THREAD

**Issue by h-vetinari** [llvm/llvm-project#58541]
Sometime between [14.0.4](https://github.com/conda-forge/openmp-feedstock/pull/67) and [14.0.5](https://github.com/conda-forge/openmp-feedstock/pull/68), our openmp recipe stopped working. Since it was a hang in - apparently - some ASM compilation, I thought it might be our infra and didn't raise an issue right away. But it has not gone away for every release since then, and we're still at the same point with 15.0.3, see https://github.com/conda-forge/openmp-feedstock/pull/72.

Our build script is [here](https://github.com/conda-forge/openmp-feedstock/blob/main/recipe/bld-llvm-openmp.bat) and doesn't do much fancy things, and we're compiling with vs2019. Here's a fresh [CI run](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=593753&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802) (old ones get deleted after a month) as well as a [previous one](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=572846&view=results)

The last logs before the hang look something like
```
-- The ASM_MASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/ml64.exe

[...]

[33/39] Building ASM_MASM object runtime\src\CMakeFiles\omp.dir\z_Windows_NT-586_asm.asm.obj

[hangs until killed by infra]
```

or 
```
[...]
[33/39] Building CXX object runtime\src\CMakeFiles\omp.dir\kmp_version.cpp.obj

[hangs until killed by infra]
```

**Comment by EugeneZelenko** [comment]
Could you please try 15 or `main` branch?

**Comment by h-vetinari** [comment]
As mentioned in the OP, this also happens with the latest release 15.0.3 (as well as all previous 15.x releases including the rc's)

**Comment by h-vetinari** [comment]
So, it turns out that the issue was down to symlinks in llvm (plus perhaps quirks of our infrastructure), and solved by https://github.com/conda-forge/llvmdev-feedstock/blob/main/recipe/patches/no-windows-symlinks.patch. In any case, it was impossible for me to diagnose at the point where things were failing... Thankfully @isuruf managed to track this down.

Interestingly, the break between 14.0.4 and 14.0.5 was not precipitated by any change in the respective [file](https://github.com/llvm/llvm-project/blame/llvmorg-15.0.4/llvm/cmake/modules/LLVMInstallSymlink.cmake), but must have been surfaced by something else.

It's IMO a bit of a loose footgun to do symlinks on windows - at least I think it's not a good default. What are people's thoughts about raising an RFC to change the default?

**Comment by shiltian** [comment]
Since https://github.com/llvm/llvm-project/issues/58893 is closed, I will close this one as well. Feel free to reopen it if it still exists.
