### ISSUE TITLE
[C] (1024 > 2048) evaluating as true

### ISSUE THREAD

**Issue by paulprocacci** [llvm/llvm-project#58544]
* Compiler Optimizations > O0 affect the outcome.  O0 compiler option works just fine.
* Works on gcc regardless of optimizations

I was toying with a custom memory allocator as I had an idea to implement lzcnt when I ran into a strange phenomenon where a part of my program should not have been ran when indeed it was.
At first I thought this was a bug in my program so I debugged a bit until I reached an if statement which absolutely should evaluate as false but instead was evaluating as true.

Attached on line 80, you'll find the if in question.  It reads as follows:

if(blksize > 2048)

blksize is a uint64_t which had the value of 1024.  Given this, clearly the statement is false, yet the "return directMap(blksize);" which followed was being executed and shouldn't have been.

Examples:
```
# clang -Wall -O3 -fomit-frame-pointer -march=native -o alloc.o -c alloc.c
# cc -o test test.c alloc.o
# ./test
1024 > 2048
You should never get here!
```

With gcc this does not happen and works as expected:
```
# gcc -Wall -O3 -fomit-frame-pointer -march=native -o alloc.o -c alloc.c
# gcc -o test test.c alloc.o
# ./test
1024 > 2048
```

test.c in the above cases is just a simple: `alloc(512);`

You'll notice if you're so inclined to check the return value you will find a usable pointer instead of that "You should never get here!" so it is indeed working in the gcc case.

```console
# clang -v
FreeBSD clang version 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a303)
Target: x86_64-unknown-freebsd13.1
Thread model: posix
InstalledDir: /usr/bin
```
```console
# uname -a
FreeBSD nas.myhome 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC amd64
```

Not sure what other information I can provide, but please let me know if any questions arise!

[alloc.txt](https://github.com/llvm/llvm-project/files/9843814/alloc.txt)

**Comment by shafik** [comment]
I would recommend always testing code with `-fsanitize=undefined,address` this will catch a lot of runtime undefined behavior. To really get the most out of sanitizers you need to make sure you have a good set of tests.

Indeed if we run your code [UBSan](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) we see the following issue:

```console
runtime error: shift exponent 42 is too large for 32-bit type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /app/example.cpp:80:16 in 
```

So you have a shift that is undefined behavior.

Second you are not seeing the correct value of `blksize` if you use the following instead:

```c
printf("%" PRIu64 " > 2048\n", blksize);
```

you will see the output is something more like this:

```console
1073741824 > 2048
```

which is clearly not what you were expecting. 

FYI also see [ASan docs](https://clang.llvm.org/docs/AddressSanitizer.html).

**Comment by paulprocacci** [comment]
I appreciate your response and agree with the undefined behavior part of shifting a value greater than 31 bits.
What I disagree with however is that clang is unable to deduce that a given value could be greater than 31 and instead use a different set of instructions.

I've already written an ASM version of the above code and was transposing it to C.  My ASM version looked as follows:

                xor     esi, esi
                lzcnt   rdi, rdi                                ; count leading zeros
                add     rdi, 0xFFFFFFFFFFFFFFBF   ; + (-bit length + 1)
                not     rdi                                     ; !rdi
                bts     rsi, rdi                                ; Set bit in result

I'm not saying the asm version here is ideal, only that there are ways to account for values greater than 31.

As for the comments regarding the constant PRIu64 and the additional flags, I appreciate those.  My strength is asm, whereas C is generally an afterthought.  Your comments are welcome and appreciated.

Cheers!

**Comment by shafik** [comment]
In both C and C++ once you invoke undefined behavior then all bets are off and we can no longer rely on any specific behavior. In fact the optimizer will often optimize based on the assumption that there is no undefined behavior.

The C standard defines undefined behavior as follows (emphasis mine):

> behavior, upon use of a nonportable or erroneous program construct or of erroneous data,
for which this **International Standard imposes no requirements**

A good classic on undefined behavior wrt C and C++ and what to expect is [What Every C Programmer Should Know About Undefined Behavior](http://blog.llvm.org/2011/05/what-every-c-programmer-should-know.html) and I would also recommend any of [John Regehr's posts](https://blog.regehr.org/archives/213) on the topic.
