### ISSUE TITLE
Build spits out lots of warnings with '-amxfp16' is not a recognized feature for this target (ignoring feature) on Haswell-EP

### ISSUE THREAD

**Issue by ms178** [llvm/llvm-project#58545]
Compiling llvm-git (b483349c5f4f), I've noticed a lot of these `'-amxfp16' is not a recognized feature for this target (ignoring feature)` warnings when building the compiler-rt and openmp runtime.

This is on a Haswell-EP CPU, with march=native set in my flags. This CPU doesn't support AMX, but it seems to me that it is set somewhere automatically albeit I did not specify it?! Or there is something wrong with the warning. 

After all it doesn't make sense to set that feature flag on Haswell-EP as the CPU is quite old and doesn't support it.

**Comment by ms178** [comment]
Furthermore, this warning is now also present when using llvm-git (https://github.com/llvm/llvm-project/commit/b483349c5f4f61a67cfd9add21dbee2d69833b77) for building other projects.

**Comment by phoebewang** [comment]
I think it's related to https://github.com/llvm/llvm-project/commit/661881d43633c00e1ba2ec0ebbc1806d81ad9a11, I'll take a look.
