### ISSUE TITLE
Using Polly to build Zstd 1.5.3 leads to a crash in the Linux Kernel and htop

### ISSUE THREAD

**Issue by ms178** [llvm/llvm-project#58567]
For a couple of days I've noticed that I could not compile a Linux Kernel successfully any longer with either GCC 12.2.1 or Clang-16 (latest tested revision: 12c62a67183e1b390e625f29cb832c15eba5089c). The system does not shutdown cleanly after such event, also htop would crash on startup. The rest of the system is still usable though. The Kernel compilation would just stop at the end of the module linking phase (with Clang) or abort with an error there (GCC).

```console
  LD [M]  sound/usb/usx2y/snd-usb-us122l.ko
  LD [M]  sound/usb/usx2y/snd-usb-usx2y.ko
  LD [M]  sound/usb/snd-usbmidi-lib.ko
```
After a lots of experiments I found out that the issue came from compiling the system's zstd library with the following Polly flags. 

```shell
export CC=clang
export CXX=clang++
export CC_LD=mold
export CXX_LD=mold
export AR=llvm-ar
export NM=llvm-nm
export STRIP=llvm-strip
export OBJCOPY=llvm-objcopy
export OBJDUMP=llvm-objdump
export READELF=llvm-readelf
export RANLIB=llvm-ranlib
export HOSTCC=clang
export HOSTCXX=clang++
export HOSTAR=llvm-ar
export CFLAGS="-O3 -march=native -mllvm -polly -mllvm -polly-position=early -mllvm -polly-parallel=true -fopenmp -fopenmp-version=50 -mllvm -polly-dependences-computeout=5000000 -mllvm -polly-detect-profitability-min-per-loop-insts=40 -mllvm -polly-tiling=true -mllvm -polly-prevect-width=256 -mllvm -polly-vectorizer=stripmine -mllvm -polly-omp-backend=LLVM -mllvm -polly-num-threads=36 -mllvm -polly-scheduling=dynamic -mllvm -polly-scheduling-chunksize=1 -mllvm -polly-invariant-load-hoisting -mllvm -polly-loopfusion-greedy -mllvm -polly-run-inliner -mllvm -polly-run-dce -mllvm -polly-enable-delicm=true -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -fno-math-errno -fno-trapping-math -falign-functions=32 -funroll-loops -fno-semantic-interposition -fcf-protection=none -mharden-sls=none -fomit-frame-pointer -mprefer-vector-width=256 -flto"
export CXXFLAGS="${CFLAGS}"
export LDFLAGS="-Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto -fuse-ld=mold -Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000"
CCLDFLAGS="$LDFLAGS"
CXXLDFLAGS="$LDFLAGS"
export ASFLAGS="-D__AVX__=1 -D__AVX2__=1 -msse2avx -D__FMA__=1"
```
All is fine when I compile ZSTD with the following CFLAGS instead, keeping the other flags the same:

```shell
export CFLAGS="-O3 -march=native -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -fno-math-errno -fno-trapping-math -falign-functions=32 -funroll-loops -fno-semantic-interposition -fcf-protection=none -mharden-sls=none -fomit-frame-pointer -mprefer-vector-width=256 -flto"
```

As Zstd happened to work fine with Polly before, I wonder if the recent change in https://github.com/llvm/llvm-project/commit/b4b7fa234cfaea5267449654de8297ee860f094e might have been the cause of the regression?  Pinging @Meinersbur for awareness. Sorry in advance for not being able to reduce this further.

**Comment by Meinersbur** [comment]
b4b7fa234cfaea5267449654de8297ee860f094e should have no effect without using `-polly-detect-keep-going` and otherwise only results in Polly doing less (unless I made a mistake).

Using `-fopenmp` or `-polly-parallel` (which uses OpenMP) is not a good idea and should fail at link-time when any OpenMP is actually being used. See https://dl.acm.org/doi/10.1145/3458817.3476183 for an effort to run OpenMP in the kernel.

The problem with compiling zstd is more convernign though. Do you have a reproducer compiling and linking only zstd?

**Comment by ms178** [comment]
Thanks, unfortunately I have no short reproducer for this with zstd.

Speaking of Polly-use within the Kernel though, my custom config runs fine with Zstd as built with the more conservative flags from above and the following Kernel patch introducing Polly use there (with the exception that I do not use polly-parallel for building the modules any longer as discussed in https://github.com/ClangBuiltLinux/linux/issues/1460#issuecomment-927472719 - I think that is exactly the issue you mentioned here as well).

[0001-makefile-clang-polly-ms178.txt](https://github.com/llvm/llvm-project/files/9855594/0001-makefile-clang-polly-ms178.txt)

**Comment by Meinersbur** [comment]
I tried the mentioned compile flags on the upstream [zstd](https://github.com/facebook/zstd) and could not reproduce the problem.

**Comment by ms178** [comment]
@Meinersbur For reference, I use three patches from Clear Linux on top, see: https://github.com/ms178/archpkgbuilds/tree/main/packages/zstd

My Kernel also carries a lot of patches on top, see: https://github.com/ms178/archpkgbuilds/tree/main/packages/linux-cachyos-bore

**Comment by ms178** [comment]
Closing for now as you could not reproduce it.

**Comment by ms178** [comment]
Some experiements later, this must have been either an issue with my patched Linux Kernel or a broken Kernel due to a miscompile with my used Polly-flags. At least I could not reproduce the crashes when having a standard distro Kernel installed; I backed off of some Kernel patches and don't use Polly right now as a workaround.
