### ISSUE TITLE
[LoopUnrollAndJam] Instruction does not dominate all uses!

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#58565]
Not sure if this is the loop pass unroll-and-jam or a later optimization that messes up...

```shell
clang-16 -cc1 -triple s390x-ibm-linux -S -O2 -w -mllvm -enable-unroll-and-jam -mllvm -allow-unroll-and-jam -mllvm -unroll-and-jam-count=8 -o crash0_aftercreduce.s -x ir  tc_crash0_aftercreduce.ll
```

[testcase.tar.gz](https://github.com/llvm/llvm-project/files/9850183/testcase.tar.gz)

```console
Instruction does not dominate all uses!
  %i9.i = and i64 %i8.i, %i4017
  %i10.not.i = icmp eq i64 %i9.i, 0
Instruction does not dominate all uses!
  %i4017 = zext i16 %i10 to i64
...

```

**Comment by fhahn** [comment]
Looks like this is caused by LoopUnrollAndJam: https://llvm.godbolt.org/z/PWovdoWrx, possibly the same issue as #50005

**Comment by caojoshua** [comment]
fix submitted for review https://reviews.llvm.org/D140255
