### ISSUE TITLE
clang++-16: Linking error when importing virtual classes.

### ISSUE THREAD

**Issue by mls-m5** [llvm/llvm-project#58560]
I get a linker error when trying to import and inherit from a virtual class.

A minimal test case. (Could be smaller if the std-lib stuff is removed)

```c++
// base.cppm
export module base;

export struct Base {
    virtual void hello() = 0;
    virtual ~Base() = default;
};
```

```c++
// derived.cppm

export module derived;

import <iostream>;
export import base;

export class Derived : public Base {
public:
    void hello() override {
        std::cout << "hello from derived\n";
    }
};

```

```c++
// main.cpp
import derived;
import <memory>;
import <iostream>;

int main(int argc, char *argv[]) {
    // This does not seem to link properly
    auto derived = std::make_shared<Derived>();
    std::cout << "hello from main" << std::endl;
    derived->hello();

    Base &b = *derived;
    b.hello();

    return 0;
}
```

Building with
```bash
clang++-16 -std=c++20 -stdlib=libc++ "base.cppm"  -MD -MF "base.pcm.d"  --precompile -o  "base.pcm"
clang++-16 -std=c++20 -stdlib=libc++ "base.pcm"   -c -o  "base.o" 
clang++-16 -std=c++20 -stdlib=libc++ -xc++-system-header --precompile memory  -o  "memory.pcm" 
clang++-16 -std=c++20 -stdlib=libc++ -xc++-system-header --precompile iostream  -o  "iostream.pcm"
clang++-16 -std=c++20 -stdlib=libc++ "derived.cppm"  -fmodule-file="iostream.pcm" -fmodule-file="base.pcm" -MD -MF "derived.pcm.d"  --precompile -o  "derived.pcm" 
clang++-16 -std=c++20 -stdlib=libc++ "derived.pcm"   -c -o  "derived.o" 
clang++-16 -std=c++20 -stdlib=libc++ "main.cpp"  -fmodule-file="derived.pcm" -fmodule-file="memory.pcm" -fmodule-file="iostream.pcm"  -c -o  "main.o" 
clang++-16 -std=c++20 -stdlib=libc++   "base.o" "derived.o" "main.o"  -o  "build/default/main" 
```

Get a linker error like

```console
/usr/bin/ld: main.o: in function `_ZNSt3__120__shared_ptr_emplaceIW7derived7DerivedNS_9allocatorIS2_EEED0Ev':
main.cpp:(.text._ZNSt3__120__shared_ptr_emplaceIW7derived7DerivedNS_9allocatorIS2_EEED0Ev[_ZNSt3__120__shared_ptr_emplaceIW7derived7DerivedNS_9allocatorIS2_EEED0Ev]+0x1e): undefined reference to `_ZW4basedlPv'
/usr/bin/ld: main.o: in function `_ZNW7derived7DerivedD0Ev':
main.cpp:(.text._ZNW7derived7DerivedD0Ev[_ZNW7derived7DerivedD0Ev]+0x1e): undefined reference to `_ZW4basedlPv'
/usr/bin/ld: main.o: in function `void std::__1::__libcpp_operator_delete[abi:v160000]<void*>(void*)':
main.cpp:(.text._ZNSt3__124__libcpp_operator_deleteB7v160000IJPvEEEvDpT_[_ZNSt3__124__libcpp_operator_deleteB7v160000IJPvEEEvDpT_]+0x11): undefined reference to `_ZW4basedlPv'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It is possible to create include-file of the `base` class, but for my real example that solution would not work.

**Comment by dwblaikie** [comment]
Where/when does that libcxx operator delete function ever get code generated? (is it possible that the libc++ you're linking with ended up built with a different ABI version than the source code got built with - so might be /less/ modules related than it appears)

**Comment by mls-m5** [comment]
@dwblaikie  

Do you mean that the linker is looking for a non existing symbol in libc++? I thought that since undefined refernces was for `_ZW4basedlPv` and `_ZW4basedlPv` it was code code in my file `base.cpppm`. The error message

```bash
main.cpp:(.text._ZNSt3__124__libcpp_operator_deleteB7v160000IJPvEEEvDpT_[_ZNSt3__124__libcpp_operator_deleteB7v160000IJPvEEEvDpT_]+0x11): undefined reference to `_ZW4basedlPv'
```

looks to me like the compiler tries to inline operator delete, but then cannot find `_ZW4basedlPv` (from base.cppm) as part of the linker step, but also does not inline it (whatever symbol it is) because it is not supposed to be inlined. (But I'm guessing)

I do not know how working with different ABI-versions work but
- Should'n there be a linker error also when including the file instead of importing it? (as of now including works fine, or just moving the base struct to derived.cppm)
- How come there is only linker errors from the file base.cppm and not from for example libc++?
- What would trigger the ABI versions to differ?

**Comment by dwblaikie** [comment]
Ah, yeah, I misread the diagnostic, sorry about that. Right you are that an operation for base is missing.

**Comment by mls-m5** [comment]
Ok, right. I always feel like I do something wrong when trying to use c++modules and get issues like this.

**Comment by ChuanqiXu9** [comment]
Reproduced with libstdc++ too. I'll take a look.

**Comment by ChuanqiXu9** [comment]
Update: now my process shows the problem is header unit related. And it looks like the reason is that we didn't take care of the linkage for header units carefully.

The following example can be compiled:
```
// base.cppm
module;
#include <new>
export module base;

export struct Base {
    virtual void hello() = 0;
    virtual ~Base() = default;
};


// derived.cppm
module;
#include <iostream>
export module derived;
export import base;

export class Derived : public Base {
public:
    void hello() override {
        std::cout << "hello from derived\n";
    }
};

// main.cpp
#include <memory>
#include <iostream>
import derived;

int main(int argc, char *argv[]) {
    // This does not seem to link properly
    auto derived = std::make_shared<Derived>();
    std::cout << "hello from main" << std::endl;
    derived->hello();

    Base &b = *derived;
    b.hello();

    return 0;
}
```

The odd `#include <new>` in the base.cppm is a workaround for another bug (https://github.com/llvm/llvm-project/issues/58975).

The temporary conclusion here may be the standard c++ modules are in the early stage and issue reports are really valuable.
And the named modules are relatively more stable than header units now. (I prefer named modules personally)

**Comment by mls-m5** [comment]
Awesome. I will try it as soon as I have some time left over. Some questions:

- Do you mean that including <new> solves the problem without any changes to clang?
- Also I see that you changed `import <iostream>` to `#include <iostream>` etc. Is this required in this case or can you still import the rest of the standard headers except for <new>.

And do you have a example of how to run the same program with named modules instead of what is used in this example?

**Comment by ChuanqiXu9** [comment]
> Awesome. I will try it as soon as I have some time left over. Some questions:
> 
> * Do you mean that including `<new>` solves the problem without any changes to clang?

Yes. If we include <new>, the allocation functions are not implicitly declared and things goes will. (I'm looking at this and I think we can import it without the unnecessary `include`)

> * Also I see that you changed `import <iostream>` to `#include <iostream>` etc. Is this required in this case or can you still import the rest of the standard headers except for `<new>`.

I am not sure if this is necessary. **Personally**, I don't like header units and I don't use them in my codes. So I just tried to remove them. You can try if things still goes well with the `import <iostream>`;.

> 
> And do you have a example of how to run the same program with named modules instead of what is used in this example?

```
clang++ -std=c++20 base.cppm --precompile -o base.pcm
clang++ -std=c++20 derived.cppm --precompile -o derived.pcm -fmodule-file=base.pcm
clang++ -std=c++20 main.cpp -fmodule-file=derived.pcm -c -o main.o
clang++ -std=c++20 main.o base.pcm derived.pcm -o a.out
```

**Comment by mls-m5** [comment]
Ok nice. Will try it out

Aha, I thought you meant using named modules instead of for example importing like `import std`. Will try with importing and se if there is a problem and report back here.

**Comment by mls-m5** [comment]
It seems to work when using `import` as well. Thanks!

**Comment by ChuanqiXu9** [comment]
> It seems to work when using `import` as well. Thanks!

It may be more helpful to share the successes example : )

**Comment by mls-m5** [comment]
When i fixed it it showed up for me as linked to the issue, but apparently it was only visible to me.

Here is a link to the working code: https://github.com/mls-m5/matmake3/tree/master/demos/06-virtual-classes

**Comment by mls-m5** [comment]
Here is the flags I'm using

```c++
clang++-16 -std=c++20 -stdlib=libc++  -xc++-system-header --precompile new -o "build/.mm3/default/new.pcm" -Wno-pragma-system-header-outside-header -Wno-user-defined-literals 
clang++-16 -std=c++20 -stdlib=libc++  "base.cppm"  -fmodule-file="build/.mm3/default/new.pcm" -MD -MF "build/.mm3/default/base.pcm.d" --precompile -o "build/.mm3/default/base.pcm" 
clang++-16 -std=c++20 -stdlib=libc++  "build/.mm3/default/base.pcm"  -c -o "build/.mm3/default/base.pcm.o" 
clang: warning: argument unused during compilation: '-stdlib=libc++' [-Wunused-command-line-argument]
clang++-16 -std=c++20 -stdlib=libc++  -xc++-system-header --precompile memory -o "build/.mm3/default/memory.pcm" -Wno-pragma-system-header-outside-header -Wno-user-defined-literals 
clang++-16 -std=c++20 -stdlib=libc++  -xc++-system-header --precompile iostream -o "build/.mm3/default/iostream.pcm" -Wno-pragma-system-header-outside-header -Wno-user-defined-literals 
clang++-16 -std=c++20 -stdlib=libc++  "derived.cppm"  -fmodule-file="build/.mm3/default/iostream.pcm" -fmodule-file="build/.mm3/default/base.pcm" -MD -MF "build/.mm3/default/derived.pcm.d" --precompile -o "build/.mm3/default/derived.pcm" 
clang++-16 -std=c++20 -stdlib=libc++  "build/.mm3/default/derived.pcm"  -c -o "build/.mm3/default/derived.pcm.o" 
clang: warning: argument unused during compilation: '-stdlib=libc++' [-Wunused-command-line-argument]
clang++-16 -std=c++20 -stdlib=libc++  "main.cpp"  -fmodule-file="build/.mm3/default/derived.pcm" -fmodule-file="build/.mm3/default/memory.pcm" -fmodule-file="build/.mm3/default/iostream.pcm" -c -o "build/.mm3/default/main.cpp.o" 
clang++-16 -std=c++20 -stdlib=libc++    "build/.mm3/default/base.pcm.o" "build/.mm3/default/derived.pcm.o" "build/.mm3/default/main.cpp.o" -o "build/default/main" 
```

**Comment by mls-m5** [comment]
@ChuanqiXu9 Is it solved? Adding `<new>` seems like a workaround...? Or is it going to be solved under another issue?
