### ISSUE TITLE
clang: Regression trivially constructible and trivially copyable type not trivial

### ISSUE THREAD

**Issue by AMS21** [llvm/llvm-project#58578]
[Godbolt link](https://godbolt.org/z/dWG5PKvKj)

Given the following source code:
```cpp
#include <type_traits>

struct A {
    A() = default;

    template <typename... T>
    A(T&&...) {}
};

static_assert(std::is_trivially_copyable<A>::value, "");
static_assert(std::is_trivially_default_constructible<A>::value, "");

static_assert(std::is_trivial<A>::value, "");

```

clang since version 11.0.0 reports
```shell
error: static assertion failed due to requirement 'std::is_trivial<A>::value':
```

Although it is both `trivially_copyable` and `trivially_default_constructible` and should thus be `trivial`

**Comment by philnik777** [comment]
I'm quite sure this is a clang bug. AFAIK both libc++ and libstdc++ use `__is_trivial(...)` to check for triviality. I also wouldn't know of any way to check this without a builtin. @cjdb you are currently working on type traits builtins, right? Are you interested in looking into this?

**Comment by cjdb** [comment]
@erichkeane has advised me that dealing with triviality is a nightmare due to ABI and versioning issues, and I thus probably won't be able to look into this before December or maybe even January.

**Comment by royjacobson** [comment]
AFAICT this is DR 1363 and working as intended, since the templated constructor is a non trivial default constructor. Indeed, this is inconsistent with the is_trivially_default_constructible.

https://cplusplus.github.io/CWG/issues/1363.html
