### ISSUE TITLE
Bug with function returns in LLVM

### ISSUE THREAD

**Issue by vanelk** [llvm/llvm-project#58591]
Booleans returns for some reason don't work on LLVM15.
**Source code:**
![image](https://user-images.githubusercontent.com/23521035/197757395-506792bc-654a-4014-9ae2-99d38de89f05.png)
**LLVM IR:**
![image](https://user-images.githubusercontent.com/23521035/197757237-d9547b57-061f-4c91-93b1-364a7832f984.png)

**Comment by nikic** [comment]
Please clarify what you mean by "don't work".

**Comment by vanelk** [comment]
I get this error at module verification.
![image](https://user-images.githubusercontent.com/23521035/197778042-bf1c15d3-fe3f-4265-bd1f-4d57f2e0222f.png)

**Comment by nikic** [comment]
You are likely using types from different LLVMContexts. Please double check that you are only ever using a single LLVMContext.

**Comment by vanelk** [comment]
Thanks! I'll check asap.

**Comment by vanelk** [comment]
I feel extremely stupid. You were right! thanks.
