### ISSUE TITLE
Print name of uninitialized subobject (instead of type)

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#58601]
There is currently a weird diagnostic in clang when a constructor doesn't fully initialize an object:

```c++
class Foo {
public:
    int a;
    constexpr Foo(){}
};

constexpr Foo F;
```
https://godbolt.org/z/5WdT8d4GE

The diagnostics for this example are a little weird. First we note that the subobject is of type 'int' for some reason and then we actually note where the subobject was declared.

I think mentioning the subobject name instead of the type in the original diagnostic would make much more sense.

**Comment by ebresafegaga** [comment]
Hi, please let me fix this issue.

**Comment by iamrahul823** [comment]
I think in initialization part there is bug

class Foo {
public:
    int a;
    constexpr Foo() : a(0) {} 
};


constexpr Foo F;

**Comment by shafik** [comment]
Interesting to note that gcc just says "is not a constant expression because it refers to an incompletely initialized variable" and MVSC actually names the uninitialized member like you want "note: see usage of 'Foo::a'"

godbolt: https://godbolt.org/z/an4PoPzbd

**Comment by hazohelet** [comment]
Proposed fix: https://reviews.llvm.org/D146358

**Comment by erichkeane** [comment]
It was unfortunately necessary to revert this patch, but @hazohelet has said they can take a look again soon.
