### ISSUE TITLE
[AMDGPU][MC] Create tests for VOP3 True16

### ISSUE THREAD

**Issue by Sisyph** [llvm/llvm-project#58609]
For the upcoming support of VOP3 encoded instructions with 16 bit operands referencing hi register halves on GFX11 (part of True16), we need assembler and disassembler tests.

This includes: 

- VOP1,2,C promoted to VOP3
- dpp & dpp8 versions of the VOP3 instructions
- Tests for hi and lo halves of VGPRs

**Comment by dpreobra** [comment]
Sure. What is the deadline?

**Comment by Sisyph** [comment]
> Sure. What is the deadline?

Thanks! Does Oct 4 seem reasonable?

**Comment by dpreobra** [comment]
It looks doable.

**Comment by dpreobra** [comment]
Please let me know if I understood you correctly:
- These tests shall use `.h/.l` suffices _instead of_ `op_sel` modifier.
- These tests shall not specify `op_sel` modifier. (Another option is to specify both suffices and `op_sel`.)
- These tests may include SGPR operands; in this case `op_sel` must be set to 0 for these operands. (Another option is to disable tests with SGPRs specified for 16 bit operands.)

> dpp & dpp8 versions of the VOP3 instructions

Do you mean only promoted opcodes?

**Comment by Sisyph** [comment]
> Please let me know if I understood you correctly:
> 
>     * These tests shall use `.h/.l` suffices _instead of_ `op_sel` modifier.
> 
Correct.
>     * These tests shall not specify `op_sel` modifier. (Another option is to specify both suffices and `op_sel`.)
> 
Correct. 
I have not yet determined whether the op_sel operand should be allowed on true16 instructions as an alternative. The current tests in tree using op_sel can be considered tests for that behavior, so new ones are not needed. I believe there is no benefit to allowing both .l/.h suffices and the op_sel operand simultaneously. In particular because they could conflict.
I suppose I will want to test what happens when both are present, and make that an assembly error. 
I plan for VOP3P to still use op_sel. This will be consistent with sp3
>     * These tests may include SGPR operands; in this case `op_sel` must be set to 0 for these operands. (Another option is to disable tests with SGPRs specified for 16 bit operands.)
> 
This is an interesting point. Certainly I would not require an assembly op_sel operand if an SGPR operand is specificed, and I would set the op_sel bit in the encoding to 0 by default.

Why do you think op_sel must be 0 for SGPRs? For example, sp3 will accept the following
`v_min3_f16 v5.h, sel_hi(v1), v0, s2.h dpp8:[7,6,5,4,3,2,1,0]`
I'm not sure of op_sel operates differently for VOP3P than for VOP3, but for VOP3P the docs state "OPSEL works for 16-bit VGPR, SGPR and literal-constant sources; for inline constant sources OPSEL must be zero"

But I haven't considered yet if we can or should support that syntax (i.e. s2.h) in llvm and what it would do.
> 
> > dpp & dpp8 versions of the VOP3 instructions
> 
> Do you mean only promoted opcodes?

I'm not exactly sure what your question means, but I would like tests for native VOP3 and VOP1/2/C promoted to VOP3, without dpp, with dpp16, and with dpp8. 
I already have tests for true16 VOP1, VOP2, and VOPC with and without dpp and dpp8 which you supplied.

**Comment by dpreobra** [comment]
> Why do you think op_sel must be 0 for SGPRs?

I’m sorry, my questions were ambiguous. I contemplated different possibilities in test generation, that’s all. My impression was that you had no support for 16-bit SGPRs. SP3 seems to allow that (with exceptions).

I just want to know how you would like to handle 16 bit SGPRs and could tests include them.

> v_min3_f16 v5.h, v1.h, v0.l, s2.h dpp8:[7,6,5,4,3,2,1,0]

Should tests include something like this?

> VOP1,2,C promoted to VOP3
> dpp & dpp8 versions of the VOP3 instructions

Looking at this description I decided you only wanted promoted VOP3, so I asked if tests for dpp should only include promoted opcodes. Looks like it was a misunderstanding, tests for VOP3/VOP3_DPP8/VOP3_DPP16 shall be for both native and promoted opcodes.

**Comment by Sisyph** [comment]
> I just want to know how you would like to handle 16 bit SGPRs and could tests include them.
> 
> > v_min3_f16 v5.h, v1.h, v0.l, s2 dpp8:[7,6,5,4,3,2,1,0]
> 
> Should tests include something like this?

Yes, that would be a good test.

However, I wouldn't want the following test, because I don't know what to do with the hi half of an SGPR
v_min3_f16 v5.h, v1.h, v0.l, **s2.h** dpp8:[7,6,5,4,3,2,1,0]

> 
> > VOP1,2,C promoted to VOP3
> > dpp & dpp8 versions of the VOP3 instructions
> 
> Looking at this description I decided you only wanted promoted VOP3, so I asked if tests for dpp should only include promoted opcodes. Looks like it was a misunderstanding, tests for VOP3/VOP3_DPP8/VOP3_DPP16 shall be for both native and promoted opcodes.

Great, thanks.

**Comment by dpreobra** [comment]
I've updated test generator and started testing the results. There are some issues which I'm not sure how to handle.

First, many 16-bit VOP3 opcodes do not currently support `op_sel` (but they should). These include all True16 opcodes promoted from VOP1/VOP2/VOPC and some native VOP3 opcodes (`v_ashrrev_i16`, `v_max_i16`, etc.). For these opcodes there will be tests with `.l` and no tests with `.h`. Is this what you expect?

Second, there are opcodes with 16 bit operands which are incorrectly defined in llvm as b32. Known cases are:

  - v_alignbit_b32
  - v_alignbyte_b32
  - v_cmp_class_f16_e64
  - v_cmpx_class_f16_e64

There may be other opcodes with similar issues, but my test scripts cannot detect these cases automatically.

For known cases like `v_alignbit_b32` tests will have no `.l/.h` suffices. For unknown cases tests will have `.l/.h` suffices for some operands, but assembler will fail on these. It this acceptable?

**Comment by Sisyph** [comment]
These are great findings!

> I've updated test generator and started testing the results. There are some issues which I'm not sure how to handle.
> 
> First, many 16-bit VOP3 opcodes do not currently support `op_sel` (but they should). These include all True16 opcodes promoted from VOP1/VOP2/VOPC and some native VOP3 opcodes (`v_ashrrev_i16`, `v_max_i16`, etc.). For these opcodes there will be tests with `.l` and no tests with `.h`. Is this what you expect?

I would like to add op_sel support for those instructions either immediately or in the medium term if it is unexpectedly complex. 
The best case for what you would provide is two sets of test. One which passes with current op_sel support ( only test with .l) and a second set with the .h tests.

> Second, there are opcodes with 16 bit operands which are incorrectly defined in llvm as b32. Known cases are:
> 
>     * v_alignbit_b32
> 
>     * v_alignbyte_b32
> 
>     * v_cmp_class_f16_e64
> 
>     * v_cmpx_class_f16_e64
> 
> 
> There may be other opcodes with similar issues, but my test scripts cannot detect these cases automatically.
> 
> For known cases like `v_alignbit_b32` tests will have no `.l/.h` suffices. For unknown cases tests will have `.l/.h` suffices for some operands, but assembler will fail on these. It this acceptable?

The assembler failing on those sounds good. 
I would like to correct those instructions to use 16-bit operands if possible. Failing tests will be a good way for me to discover the affected ones. In addition, if you are emitting test with no suffices for any known cases in addition to the above please let me know.

**Comment by dpreobra** [comment]
> The best case for what you would provide is two sets of test. One which passes with current op_sel support ( only test with .l) and a second set with the .h tests.

Sure. I have an option to generate tests for each instruction in a separate file. If it is more convenient for you, I can provide set#2 as separate files. Running these tests will immediately indicate instructions with missing or problematic op_sel support.

**Comment by dpreobra** [comment]
> In addition, if you are emitting test with no suffices for any known cases in addition to the above please let me know.

There is another special case I forgot about: `v_permlane16_b32` and `v_permlanex16_b32`. They have 32 bit operands but `op_sel` modifier is enabled to indicate DPP `bound_ctrl` and `fi`. I think tests for `permlane` require no changes for now. We should consider switching to SP3 syntax in the future.

**Comment by dpreobra** [comment]
> The best case for what you would provide is two sets of test. One which passes with current op_sel support (only test with .l) and a second set with the .h tests.

Attached is the first set of tests - those for current `op_sel` support. In other words, only opcodes which currently support `op_sel` have tests with `.h`.

To simplify future test updates I've separated generated and manually written tests. The latter have `_feature` suffix.

[gfx11_dasm_vop3_true16_lit.zip](https://github.com/llvm/llvm-project/files/9904153/gfx11_dasm_vop3_true16_lit.zip)
[gfx11_asm_vop3_true16_lit.zip](https://github.com/llvm/llvm-project/files/9904154/gfx11_asm_vop3_true16_lit.zip)

You can also try using \*dbg* tests. They are functionally equivalent to \*lit* tests except that they are for W32 only. These tests may be useful during development to identify opcodes with issues.

[gfx11_dasm_vop3_true16_dbg.zip](https://github.com/llvm/llvm-project/files/9904161/gfx11_dasm_vop3_true16_dbg.zip)
[gfx11_asm_vop3_true16_dbg.zip](https://github.com/llvm/llvm-project/files/9904162/gfx11_asm_vop3_true16_dbg.zip)

I'll send set#2 in a couple of days.

**Comment by dpreobra** [comment]
Attached is the second set of tests with `op_sel` enabled for all VOP3 opcodes.

[gfx11_asm_vop3_true16_opsel_lit.zip](https://github.com/llvm/llvm-project/files/9910023/gfx11_asm_vop3_true16_opsel_lit.zip)
[gfx11_dasm_vop3_true16_opsel_lit.zip](https://github.com/llvm/llvm-project/files/9910024/gfx11_dasm_vop3_true16_opsel_lit.zip)

I do not think these tests are very useful because it is not possible to turn on/off individual opcodes. But \*dbg* tests may be handy.

[gfx11_asm_vop3_true16_opsel_dbg.zip](https://github.com/llvm/llvm-project/files/9910049/gfx11_asm_vop3_true16_opsel_dbg.zip)
[gfx11_dasm_vop3_true16_opsel_dbg.zip](https://github.com/llvm/llvm-project/files/9910050/gfx11_dasm_vop3_true16_opsel_dbg.zip)

When you finish adding `op_sel` support, you may send me your patch and I'll update the \*lit* tests.

**Comment by Sisyph** [comment]
Great, thanks for working on that! I will give those a try with my implementation.

**Comment by Sisyph** [comment]
I have put up the draft of my MC only implementation for True16, in case it is of interest. Note, you may need to build with -DLLVM_OPTIMIZED_TABLEGEN=ON, because there are many ISel pattern issues that need to be suppressed. 

https://github.com/Sisyph/llvm-project/pull/1

**Comment by Sisyph** [comment]
In that patch, the op_sel asm operand is ignored, in the sense that the .l/.h suffix on the operands completely controls the bits when assembling. Setting HasOpSel = 0 for these instructions is a possible but poor option, because ISel patterns and other codegen stuff is built around undersanding opsel, and I don't want to unwravel all that unless necessary. I am wondering if in this patch it would be good to throw an error in the parser if op_sel is specified, and how to accomplish that.

**Comment by dpreobra** [comment]
Thanks, I've built your draft implementation. I found that I forgot about VINTERP opcodes and did not send you updated tests for them. Sorry about that. Anyway, I tested the implementation and found no issues. Everything works fine and all opcodes which missed `op_sel` support now have it.

I see that you added `v_mov_b16` but `v_swap_b16` is still missing.

> I am wondering if in this patch it would be good to throw an error in the parser if `op_sel` is specified, and how to accomplish that.

I think it is perfectly fine to report an error for opcodes with `op_sel` modifier. You could use `getImmLoc` for that purpose. An example may be found here: https://github.com/llvm/llvm-project/blob/9b83935672cf8be67b0bd485b10e655a7764182a/llvm/lib/Target/AMDGPU/AsmParser/AMDGPUAsmParser.cpp#L4603

An alternative is to use `checkEarlyTargetMatchPredicate` to reject opcodes with `op_sel` but in this case it will not be possible to provide a meaningful error message and error position.

**Comment by Sisyph** [comment]
Great, thanks for trying it out. I'm glad you haven't found any issues so far. Yes, v_swap_b16 is still TODO. Thanks for the info on getImmLoc, I will give that a try. I intend to upstream that stuff as soon as possible when CodeGen support is completed. I will close this issue as completed, but please reach out if anything related comes to mind.
