### ISSUE TITLE
clang-format crashed

### ISSUE THREAD

**Issue by BrentWilkins** [llvm/llvm-project#58606]
I was running `clang-format -style=f -i <file name>` and that crashed. Running the VS2022 version via bash in WSL2.

```console
Stack dump:
0.      Program arguments: clang-format.exe -style=file -i ./\<redacted\>.cpp
0x00007FF7EBC5E901 (0x0000000000000000 0x0000000000000000 0x0000002E00000000 0x00007FF7EBC07F11)
0x00007FF7EBC5D648 (0x0000002E9478AF08 0x0000000000000000 0x0000002E00000000 0x0000002E9478C630)
0x00007FF7EBC5CD1C (0x0000000000000000 0x0000002E00000000 0x0000002E9478AB48 0x00007FF9B7EBF05B)
0x00007FF7EBC59EF7 (0x0000000000000404 0x0000013500000000 0x0000000000000000 0x0000001000000000)
0x00007FF7EBC26397 (0x0000002E9478B8B0 0x00007FF7EBC4292E 0x0000000000000002 0x00007FF900000000)
0x00007FF7EBC42519 (0x0000000000000000 0x0000002E9478C620 0x0000002E9478CAA0 0x000000000000002A)
0x00007FF7EBC34664 (0x0000013507557430 0x0000000000000000 0x0000000000000004 0x0000000000000004)
0x00007FF7EBC1DD6E (0x0000013507564A20 0x00007FF9BA6B47B1 0x000001350759FBF0 0x0000013507550000)
0x00007FF7EBC1EC69 (0x0000013507557D12 0x0072006700000000 0x0000013507557C70 0x0000000000A200A0)
0x00007FF7EBBA545C (0x0000013507558100 0x000000000000000E 0x0000000000000000 0x0000013507556510)
0x00007FF7EBBA36F6 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF7EBD243D8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF9BA3F7034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FF9BA6E26A1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
```

**Comment by BrentWilkins** [comment]
The BSD command `file` reported this on the failed file:
> C++ source, ASCII text, with very long lines (324)

**Comment by BrentWilkins** [comment]
Same file crashed it again:
> Stack dump:
> 0.      Program arguments: clang-format.exe -style=file -i ./\<redacted\>.cpp
> 0x00007FF7EBC5E8E0 (0x0000000000000000 0x0000000000000000 0x000000D600000000 0x00007FF7EBC07F11)
> 0x00007FF7EBC5D648 (0x000000D6A318ADE8 0x0000000000000000 0x000000D600000000 0x000000D6A318C510)
> 0x00007FF7EBC5CD1C (0x0000000000000000 0x000000D600000000 0x000000D6A318AA28 0x00007FF9B7EBF05B)
> 0x00007FF7EBC59EF7 (0x000002149F8BED00 0x0000000000000000 0x0000000000000000 0x0000001000000000)
> 0x00007FF7EBC26397 (0x000000D6A318B790 0x00007FF7EBC4292E 0x000002149F87AFBC 0x00007FF900000000)
0x00007FF7EBC42519 (0x0000000000000000 0x000000D6A318C500 0x000000D6A318C980 0x000000000000002A)
0x00007FF7EBC34664 (0x000002149F8BD310 0x0000000000000000 0x0000000000000002 0x0000000000000002)
0x00007FF7EBC1DD6E (0x000002149F883610 0x00007FF9BA6B47B1 0x000002149F8C0870 0x000002149F870000)
0x00007FF7EBC1EC69 (0x000002149F877632 0x0072006700000000 0x000002149F877590 0x0000000000A200A0)
0x00007FF7EBBA545C (0x000002149F877D00 0x000000000000000E 0x0000000000000000 0x000002149F877AF0)
0x00007FF7EBBA36F6 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF7EBD243D8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF9BA3F7034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FF9BA6E26A1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)

**Comment by rymiel** [comment]
I don't think there's much to do here without the symbols, the source file, the version, or the .clang-format file, but I'm willing to bet AlignArrayOfStructures is involved (see https://github.com/llvm/llvm-project/issues/57558, https://github.com/llvm/llvm-project/issues/56682, https://github.com/llvm/llvm-project/issues/56670, https://github.com/llvm/llvm-project/issues/56104, https://github.com/llvm/llvm-project/issues/55685, https://github.com/llvm/llvm-project/issues/55493, https://github.com/llvm/llvm-project/issues/55269, https://github.com/llvm/llvm-project/issues/54815, https://github.com/llvm/llvm-project/issues/53748, https://github.com/llvm/llvm-project/issues/51277, https://github.com/llvm/llvm-project/issues/58047, https://github.com/llvm/llvm-project/issues/57228, https://github.com/llvm/llvm-project/issues/51767)

**Comment by HazardyKnusperkeks** [comment]
Without an input on which it crashes there is no point in reporting it. Either provide the source code (maybe obfuscated), or even better bring a minimal example.
