### ISSUE TITLE
Wrong formatting of the pretty-printed return value of clang_getTypeSpelling(); clang-format breaks valid C++ code

### ISSUE THREAD

**Issue by vedgy** [llvm/llvm-project#58602]
When `clang_getTypeSpelling()` returns a value that contains `operator>`, `operator<=` or `operator-` followed by a closing angle bracket or `operator<` followed by an opening angle bracket, it does not insert whitespace between these two tokens. This makes the returned value invalid C++ and prevents *libclang* users from parsing it correctly. For example:

```cpp
namespace FormattingBug {
class X{};
bool operator>(X, int) { return true; }
bool operator<=(X, int) { return true; }
bool operator-(X, int) { return true; }
template<typename T> bool operator<(T, int) { return true; }

template<decltype(operator>)> class C{};
C<&operator> > gt;      // pretty-printed as "C<&operator>>"
C<&operator<= > le;     // pretty-printed as "C<&operator<=>"
C<&operator- > minus;   // pretty-printed as "C<&operator->"
C<&operator< <X>> lt;   // pretty-printed as "C<&operator<<FormattingBug::X>>"
}
```

When the space between the tokens is removed in the source code, like in the pretty-printed string, it does not compile. In simple cases like these, the user of `clang_getTypeSpelling()` can count the number of angle brackets and distinguish parts of operators from angle brackets. But this becomes unfeasible for more complicated types.

I believe `clang_getTypeSpelling()`, or more likely `QualType::print()` used by it, should insert a tab character between such tokens to pretty-print compilable code. The tab character is preferable to the space character here, because the users may rely on the fact that pretty-printed binary operators are surrounded by spaces to distinguish them from angle brackets.

**Comment by vedgy** [comment]
I think workaround code for the closing-angle-bracket part of this bug can be added into [`TemplateArgs::printLeft()`](https://github.com/llvm/llvm-project/blob/2e999b7dd1934a44d38c3a753460f1e5a217e9a5/llvm/include/llvm/Demangle/ItaniumDemangle.h#L1393). If the last printed template parameter was `operator>`, `operator<=` or `operator-`, insert a tab: `OB += "\t";` before the `OB += ">";` line.

**Comment by vedgy** [comment]
I confirm that the *clang-format* part of this bug has been fixed. But the libclang `clang_getTypeSpelling()` bug remains. Can someone please reopen this issue?

**Comment by owenca** [comment]
Can you open a separate issue for the libclang part (and mention this issue if you like)?
