### ISSUE TITLE
unsigned integer overflow in llvm::djbHash

### ISSUE THREAD

**Issue by ibmibmibm** [llvm/llvm-project#58620]
in `llvm/include/llvm/Support/DJB.h`:
```c++
inline uint32_t djbHash(StringRef Buffer, uint32_t H = 5381) {
  for (unsigned char C : Buffer.bytes())
    H = (H << 5) + H + C;
  return H;
}
```
`(H << 5) + H` may overflow, should cast to uint64_t before calculation:
`H = static_cast<uint32_t>((static_cast<uint64_t>(H) << 5) + H + C);`

Likewise, in `llvm/lib/Support/DJB.cpp`:
```c++
static Optional<uint32_t> fastCaseFoldingDjbHash(StringRef Buffer, uint32_t H) {
  bool AllASCII = true;
  for (unsigned char C : Buffer) {
    H = H * 33 + ('A' <= C && C <= 'Z' ? C - 'A' + 'a' : C);
    AllASCII &= C <= 0x7f;
  }
  if (AllASCII)
    return H;
  return None;
}
```
`H = static_cast<uint32_t>(static_cast<uint64_t>(H) * 33 + ('A' <= C && C <= 'Z' ? C - 'A' + 'a' : C));`

**Comment by nunoplopes** [comment]
Overflows are normal in hash functions. Not a bug.
