### ISSUE TITLE
libc++-dev seems to be 14 rather than 16 in apt.llvm.org of Debian sid

### ISSUE THREAD

**Issue by hushanjushi** [llvm/llvm-project#58625]
libc++-dev seems to be 14 rather than 16 in apt.llvm.org

It show:
```
The following additional packages will be installed:
  libc++-14-dev libc++1-14 libc++abi1-14 libunwind-14 libunwind-14-dev
Suggested packages:
  clang
The following NEW packages will be installed:
  libc++-14-dev libc++-dev libc++1-14 libc++abi1-14 libunwind-14 libunwind-14-dev
```

**Comment by MarcoFalke** [comment]
I just tried `./llvm.sh 16 all` and it works. What are the steps to reproduce?

**Comment by hushanjushi** [comment]
> I just tried `./llvm.sh 16 all` and it works. What are the steps to reproduce?

The llvm.sh in Debian sid doesn't work. You need to add llvm.list manually to /etc/apt/source.list.d.

**Comment by MarcoFalke** [comment]
Can you add full steps to reproduce, ideally starting from a fresh install of the OS?

**Comment by hushanjushi** [comment]
> Can you add full steps to reproduce, ideally starting from a fresh install of the OS?

It seems work now.
