### ISSUE TITLE
Clang Tidy enable for only reachable source code

### ISSUE THREAD

**Issue by cdemirsoy** [llvm/llvm-project#58622]
Hi there,

I have a basic problem, which I am not able to solve.

I am analyzing some data types, and I need to make further analysis only when the source code is reachable.

For example, when I use an std::vector, its source code is not reachable.

But when I use a custom type from an header defined by myself e.g myStruct.h, it is reachable so I can apply some checks.

Is there such a capability implemented in Clang-tidy options to enable the checks only when the source/header is reachable and the used utility is not pre-compiled?

**Comment by PiotrZSL** [comment]
Clang-tidy require code to "compile" in order to build a valid AST tree and provide valid diagnostic.
For ignoring issues from some header files "header-filter" option could be used.
If you got any new questions please re-open this issue, or create new one.
