### ISSUE TITLE
[flang-format]: Variable repeat factor / Variable Format Expressions

### ISSUE THREAD

**Issue by GHNewbiee** [llvm/llvm-project#58623]
Does `flang` support **Variable repeat factor** / **Variable Format Expressions**?

Example
```fortran
write(*, '(1x, <neg>i3, <zero>('@',i1), <pos>i2)')
```
where
`neg`, `zero` and `pos` are variables (natural non-zero numbers).

 *Tia*

**Comment by klausler** [comment]
No.

**Comment by LecrisUT** [comment]
Question, there is no `flang-format` yet right? Are there ways to adapt `clang-format` for fortran, some people working or a matrix/IRC channel to discuss this, or any tips for getting started on this?

**Comment by LecrisUT** [comment]
Oh, why is it under `clang/tools/clang-format` then? Shouldn't it be more general? Like alias `llvm-format`?
