### ISSUE TITLE
_Alignas on a struct declaration gives a low-quality diagnostic

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#58637]
```c
_Alignas(int) struct T {
  int i;
};
```
gives the diagnostic:  `warning: attribute '_Alignas' is ignored, place it after "struct" to apply attribute to type declaration` which seems like a really helpful message at first glance. However, C does not allow you to put an `_Alignas` specifier on the struct type itself. So following that advice:
```c
struct _Alignas(int) T {
  int i;
};
```
gives: `error: declaration of anonymous struct must be a definition` and `warning: declaration does not declare anything`.

The original diagnostic should say the attribute is ignored without the helpful message about placement (which is correct for C++).

**Comment by theo-lw** [comment]
Here's an attempt at a fix:

https://reviews.llvm.org/D141177

**Comment by Unique-Usman** [comment]
@AaronBallman , I will like work on this issue, @theo-lw are you still working on this?
