### ISSUE TITLE
assembler error when using flang -fno-integrated-as

### ISSUE THREAD

**Issue by laurent-alfonsi-linaro** [llvm/llvm-project#58647]
Pb in generated `.s` when using `flang -fno-integrated-as` on almost any Fortran file.

Here is the small example I'm using:
```console
$ cat func.f90
module logic
contains
subroutine new_solver()
end subroutine new_solver
end module logic
$ flang -O2 -fno-integrate-as -c func.f90 -save-temps=obj
func.s: Assembler messages:
func.s:8: Error: junk at end of line, first unrecognized character is `"'
flang-new: error: assembler command failed with exit code 1 (use -v to see invocation)
```

Thus in `.s` file I can see at line 8:
```s
  .file	1 "/home/laurent.alfonsi/" "./func.i"
```

The name of the file is cut between directory and filename.

**Comment by clementval** [comment]
Are you using classic-flang? If so, you should open an issue on the classic-flang repo.

**Comment by xgupta** [comment]
This is working when using with flang-new - 

$ flang-new -O2 -fno-integrated-as -c test.f90 -save-temps=obj
$ ls
logic.mod  test.bc  test.f90  test-fir.mlir  test.i  test-llvmir.mlir  test.o  test.s
