### ISSUE TITLE
llvm-symbolizer fails to find the line info when there are garbage DWARF units.

### ISSUE THREAD

**Issue by liudangyi** [llvm/llvm-project#58641]
Ways to reproduce:

```console
$ cat test.cc
#include <vector>

static std::vector<int> unused;  // This ensures the compile unit contains DW_AT_ranges.

int main() {
    return 0;
}

$ cat lib.cc 
#include <vector>

static std::vector<int> unused;  // This ensures the compile unit contains DW_AT_ranges.

// A large function.
void f() {
    asm(".fill 0x2000, 1, 0xCC");
}

$ clang++ test.cc lib.cc -o test -Wl,--gc-sections -g

$ nm test | grep main
00000000000011f0 T main

$ llvm-symbolizer --obj test 0x11f0
main
??:0:0
```

If we remove `-Wl,--gc-sections` then it works. The problem is because function `f` is garbage collected, but its DWARF info is kept and in `llvm-dwarfdump test`, there are

```
0x000010a0: DW_TAG_compile_unit
              DW_AT_producer	("Debian clang version 14.0.6-2")
              DW_AT_language	(DW_LANG_C_plus_plus_14)
              DW_AT_name	("lib.cc")
...
              DW_AT_ranges	(indexed (0x0) rangelist = 0x00000062
...
                 [0x0000000000000000, 0x0000000000002006)
...
```

So `llvm-symbolizer` incorrectly find the wrong compile unit and the wrong line table.

Clang version: 

```console
Debian clang version 14.0.6-2
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by liudangyi** [comment]
I've uploaded a fix in https://reviews.llvm.org/D136652 but it unfortunately breaks existing test cases.

**Comment by jh7370** [comment]
Which linker are you using? @MaskRay, does LLD use tombstone values these days to prevent this sort of issue?

**Comment by liudangyi** [comment]
I'm using ld, but the same behavior (tombstone) also applies to gold and lld.

**Comment by MaskRay** [comment]
`f` is large. It may have a size of 0x2006.

With DWARF v4, this works fine with GNU ld and lld. DW_AT_ranges for libc.cc uses [1,1) (a relocation refererencing a discarded symbol in `.debug_ranges` resolves to 1) to encode the range, which will be ignored.
You get correct file:line.

With DWARF v5, if the lookup address falls into [0,0x2006), llvm-symbolizer may pick the GCed `f` range and show `??:0:0`.
To get correct file:line, link `test` using lld with `-Wl,-z,dead-reloc-in-nonalloc=.debug_addr=0xffffffffffffffff`.
In the range list, a `DW_RLE_base_addressx` entry kind refers to the reserved address value (in future DWARF)(aka "tombstone address value") 0xffffffffffffffff in `.debug_addr`.
llvm-symbolizer ignores `DW_RLE_offset_pair` entry kinds preceded by the special `DW_RLE_base_addressx`.

There may be some DWARF consumers which don't like `.debug_addr=0xffffffffffffffff`, so we are conservative and haven't changed lld's default for `.debug_addr` yet.
