### ISSUE TITLE
[AMDGPU] can't select pointer dereference

### ISSUE THREAD

**Issue by DataCorrupted** [llvm/llvm-project#58640]
https://godbolt.org/z/7fe68Ev8P

When compiling the following code with `llc -mtriple=amdgcn`, the compiler complains "Cannot select: 0x55b665b71a90: i32,ch = load<(load (s32) from %ir.0)> # D:1 0x55b665adab28, 0x55b665b71940, undef:i64"

```
define i32 @f(i32* %0) {
BB:
  %R = load i32, i32* %0
  ret i32 %R
}
```

**Comment by DataCorrupted** [comment]
cc @arsenm

**Comment by arsenm** [comment]
This is expected to not work. SI didn't have hardware flat support, so flat pointer accesses fail to select. We could implement software emulation of these. This should work with newer -mcpu specified

**Comment by DataCorrupted** [comment]
https://godbolt.org/z/83xa3b4M7

Can verify that it's working when "newer -mcpu specified". Thanks for the help. Closing.
