### ISSUE TITLE
[flang] Refine how Clang dependencies are expressed

### ISSUE THREAD

**Issue by banach-space** [llvm/llvm-project#58663]
> FYI: This came up in a discussion for https://reviews.llvm.org/D136606 (CC @MaskRay @mgorny ). 

Currently, Flang is quite verbose when defining its dependencies on Clang libraries, see e.g. https://github.com/llvm/llvm-project/blob/beb997799d823aece097494f156c6d277d26571c/flang/lib/FrontendTool/CMakeLists.txt#L18-L28 

Instead, Flang could follow LLDB's example and tweak [add_flang_library](https://github.com/llvm/llvm-project/blob/beb997799d823aece097494f156c6d277d26571c/flang/cmake/modules/AddFlang.cmake#L19-L94) by adding something like this: https://github.com/llvm/llvm-project/blob/beb997799d823aece097494f156c6d277d26571c/lldb/cmake/modules/AddLLDB.cmake#L97-L101

This would be more idiomatic, allow better code re-use and make scripts shorter and more explicit. Volunteers are most welcome :) 

-Andrzej

**Comment by mgorny** [comment]
Yes, that sounds like a nicer approach. That said, I had something else in mind but not sure how feasible it would be.

I was thinking that clang could actually define a variation of its cmake targets like `clangBasic::or_dylib` that would either map to the original static `clangBasic` or `clang-cpp` depending on the configuration.

**Comment by banach-space** [comment]
I guess that you'd like this logic to be shared between LLDB and Flang (and any other project that uses Clang libs)? Since these are Clang dependencies, it would make sense for this logic to be present in Clang.

In fact, Clang already uses similar: https://github.com/llvm/llvm-project/blob/beb997799d823aece097494f156c6d277d26571c/clang/cmake/modules/AddClang.cmake#L209-L213

So, your approach could benefit LLDB, Flang and Clang :)

**Comment by Da-Viper** [comment]
I would like to try out this issue can I be assigned to it ?

**Comment by Da-Viper** [comment]
created a patch please check if this is what I am meant to do https://reviews.llvm.org/D140998

**Comment by banach-space** [comment]
@Da-Viper , what's the status of this?

**Comment by Da-Viper** [comment]
> 

@banach-space  It is all done, waiting for a review

**Comment by banach-space** [comment]
> > 
> 
> @banach-space It is all done, waiting for a review

I've reviewed it and there's one outstanding comment from me:

> LGTM, but please address my comment in flang/lib/FrontendTool/CMakeLists.txt first. Do you have commit access for llvm-project?

;-) Btw, do you have commit access?

**Comment by Da-Viper** [comment]
> > > 
> > 
> > 
> > @banach-space It is all done, waiting for a review
> 
> I've reviewed it and there's one outstanding comment from me:
> 
> > LGTM, but please address my comment in flang/lib/FrontendTool/CMakeLists.txt first. Do you have commit access for llvm-project?
> 
> ;-) Btw, do you have commit access?

I do not have commit access

**Comment by banach-space** [comment]
What e-mail address should I use in the commit message then?

**Comment by Da-Viper** [comment]
> What e-mail address should I use in the commit message then?

57949090+Da-Viper@users.noreply.github.com

**Comment by banach-space** [comment]
> > What e-mail address should I use in the commit message then?
> 
> [57949090+Da-Viper@users.noreply.github.com](mailto:57949090+Da-Viper@users.noreply.github.com)

This is what I have from the Phab PR:
```
author: Ezike Ebuka <yerimyah1@gmail.com>
```

If that's OK, I'll just use that.

**Comment by Da-Viper** [comment]
Yes it is ok

**Comment by banach-space** [comment]
Thank you for contributing! 🙏🏻
