### ISSUE TITLE
flang-new with libpgmath doesn't work properly on aarch64

### ISSUE THREAD

**Issue by licy183** [llvm/llvm-project#58686]
I built libpgmath in https://github.com/flang-compiler/flang, then build `llvm-flang` with `LIBPGMATH_DIR` and then tried to build the source in https://github.com/llvm/llvm-project/issues/57736#issue-1372973724 and execute the binary, but some error occurs.

```console
root@7960fedcbef2:~# cat main.f90 
program foo

    complex :: c
    c = 2.0
    write(*,*) sqrt(c)

end program
root@7960fedcbef2:~# flang-new main.f90 -lpgmath
root@7960fedcbef2:~# ./a.out 
Error during math dispatch processing...
__pgmath_abort:Math dispatch table is either misconfigured or corrupted.root@7960fedcbef2:~# 
root@7960fedcbef2:~# 
```

Furthermore, I set environment variable `MTH_I_STATS=7` and `MTH_I_DEBUG=1` according to https://github.com/flang-compiler/flang/issues/1107, and got the following output.

[a.out.log](https://github.com/llvm/llvm-project/files/9894111/a.out.log)

Is this a bug in `libpgmath` or `llvm-flang`, or just my misconfiguration?

**Comment by kiranchandramohan** [comment]
Is your build of `llvm/flang` up to date? This issue that you are facing was fixed with https://reviews.llvm.org/D134655 and https://reviews.llvm.org/D135882.

**Comment by licy183** [comment]
Thanks for your information. I built llvm-flang using llvm-15 source tarball. I will try to build the master branch of llvm-project and try again.
