### ISSUE TITLE
Merge 7a84624079a2656c684bed6100708544500c5a32 into 15 release branch

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#58698]
Fixes some infinite looping compiles with vector types

**Comment by tstellar** [comment]
@arsenm This doesn't apply cleanly.

**Comment by arsenm** [comment]
The conflicts look like it's only test updates to files which don't exist in the release branch. I'm building and seeing if any other tests need updating

**Comment by arsenm** [comment]
[0001-AMDGPU-Make-various-vector-undefs-legal.patch.zip](https://github.com/llvm/llvm-project/files/9915145/0001-AMDGPU-Make-various-vector-undefs-legal.patch.zip)
Resolved patch (just removing the two newer tests)

**Comment by tstellar** [comment]
https://github.com/llvm/llvm-project-release-prs/pull/206

**Comment by arsenm** [comment]
This was merged already
