### ISSUE TITLE
[mlir][arith] `arith.div*` ops should not be marked as `AlwaysSpeculatable`

### ISSUE THREAD

**Issue by kuhar** [llvm/llvm-project#58700]
Currently all arith ops are [marked as 'Pure'](https://github.com/llvm/llvm-project/blob/aceb67eeb516fd4ca762de6bd8194ca7f31c9f45/mlir/include/mlir/Dialect/Arith/IR/ArithOps.td#L24) which [entails 'AlwaysSepculatable'](https://github.com/llvm/llvm-project/blob/cb33ef7ca71d864b5fb8efbe59d77e895ba6e9a0/mlir/include/mlir/Interfaces/SideEffectInterfaces.td#L133). Instead, they should be marked as `ConditionallySpeculatable` and take into account possible division by 0 or division by -1 in the signed case.

**Comment by kuhar** [comment]
cc: @sanjoy, @Mogball

**Comment by sanjoy** [comment]
Fix: https://reviews.llvm.org/D137814
