### ISSUE TITLE
SLP vectorizer is slow on some large input

### ISSUE THREAD

**Issue by gezalore** [llvm/llvm-project#58705]
Attached is a large input file that shows compilation-time issues in the SLP vectorizer. (The input file is from machine generated C++ emitted by Verilator.). Observe:

```console
% time opt -O3 slowSLP.bc -disable-output
opt -O3 slowSLP.bc -disable-output  64.34s user 0.02s system 99% cpu 1:04.37 total
% time opt -O3 slowSLP.bc -disable-output -vectorize-slp=0
opt -O3 slowSLP.bc -disable-output -vectorize-slp=0  2.62s user 0.02s system 99% cpu 2.648 total
```

Worse yet I don't think we actually end up vectorizing anything, so we spend a lot of time analyzing the code to no effect.

LLVM version (main at time of writing): 1258747a59db5200112fca7c6140d184f3b8748e

I did some digging and there are at least two sections that have big impact, but I don't think I will have time in the near term to immerse myself enough to provide a fix:

---

First is the building of the `ValueToTEs` map in `BoUpSLP::isGatherShuffledEntry` (50%+ of time):
https://github.com/llvm/llvm-project/blob/a784de783af5096e593c5e214c2c78215fe303f5/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp#L7568-L7577

We call this function in a loop from `getTreeCost` via `getElementCost`:
https://github.com/llvm/llvm-project/blob/a784de783af5096e593c5e214c2c78215fe303f5/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp#L7358
https://github.com/llvm/llvm-project/blob/a784de783af5096e593c5e214c2c78215fe303f5/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp#L6222-L6223

I *think* (and might be wrong) that `VectorizableTree` does not change during that loop in `getTreeCost`, so lazy/pre-computing `ValueToTEs` once might be an easy win?

---

Another significant performance hog (20%+ of total runtime) is this loop in `clusterSortPtrAccesses`:
https://github.com/llvm/llvm-project/blob/a784de783af5096e593c5e214c2c78215fe303f5/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp#L3723-L3743

This gets called both from `reorderTopToBottom` and `reorderBottomToTop` with this input. The passed `VL` is ~16 entries long and AFAICT none of the pointers can be clustered, eventually hitting the early `return` in the loop, but evaluating `getPointersDiff` repeatedly appears expensive:
https://github.com/llvm/llvm-project/blob/a784de783af5096e593c5e214c2c78215fe303f5/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp#L3738

[slowSLP.bc.gz](https://github.com/llvm/llvm-project/files/9900888/slowSLP.bc.gz)

**Comment by alexey-bataev** [comment]
$ time opt -O3 slowSLP.bc -disable-output -vectorize-slp=0                                                                 opt -O3 slowSLP.bc -disable-output   2.58s user 0.04s system 98% cpu 2.650 total
$ time opt -O3 slowSLP.bc -disable-output
opt -O3 slowSLP.bc -disable-output  14.05s user 0.03s system 99% cpu 14.132 total
