### ISSUE TITLE
clang/test/Driver/hip-link-bc-to-bc.hip failing

### ISSUE THREAD

**Issue by pogo59** [llvm/llvm-project#58711]
This test was added in [D124151](https://reviews.llvm.org/D124151) and has a `REQUIRES: clang-driver` clause, however the `clang-driver` keyword is never defined (see 63fbc771 which removed all uses of `clang-driver` except this one).

I'll be removing the `clang-driver` keyword and adding `XFAIL: *` shortly. Then the test will report XFAIL instead of UNSUPPORTED.

Tagging the author (@lamb-j) and reviewer (@yxsamliu) of D124151, hoping one of them will fix this test.

**Comment by pogo59** [comment]
See 7af01fe for the change to XFAIL the test.

**Comment by lamb-j** [comment]
Thanks for looking into this! I'll track down why this test is failing and upload a fix.

**Comment by lamb-j** [comment]
Fix posted here https://reviews.llvm.org/D137275
