### ISSUE TITLE
[libomptarget] Linker error on functions with the same name as zlib functions when enabling LTO and OpenMP offload on RHEL9

### ISSUE THREAD

**Issue by dwoodwor-intel** [llvm/llvm-project#58712]
I'm seeing an "undefined reference to symbol" linker error with some functions that have the same name as functions in zlib when linking with LTO and OpenMP Offload enabled on Red Hat Enterprise Linux 9:

```console
$ cat zlib-omptarget-clash.c
int main() { return 0; }

void crc32_z(void) {}
$ clang -flto -fopenmp -fopenmp-targets=x86_64-pc-linux-gnu zlib-omptarget-clash.c -o zlib-omptarget-clash
/usr/bin/ld: /tmp/zlib-omptarget-clash-e5456a.o (symbol from plugin): undefined reference to symbol 'crc32_z@@ZLIB_1.2.9'
/usr/bin/ld: /usr/lib64/libz.so.1: error adding symbols: DSO missing from command line
/iusers/dwoodwor/llvm-upstream/deploy/bin/clang-linker-wrapper: error: 'ld' failed
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```

This is reproducible on the main branch starting with dc52712a063241bd0d3a0473b4e7ed870e41921f, which links a couple LLVM libraries (and, indirectly, zlib) into libomptarget.

The linker error only appears if `-flto` is used. It also doesn't appear on RHEL8 even with LTO enabled. RHEL8 seems to use the same version of zlib (1.2.11) but does have a different version of ld (GNU ld 2.30-93.el8 vs. RHEL9's GNU ld 2.35.2-17.el9). I've tried a few different OS versions in VMs and these are the only ones where I could reproduce this bug:

* RHEL 9.0 (GNU ld 2.35.2-17.el9)
* Fedora 34 (GNU ld 2.35.1-41.fc34)

These OS versions are not affected and don't show this linker error:

* RHEL 8.4 (GNU ld 2.30-93.el8)
* Ubuntu 20.04.3 (GNU ld 2.34)
* Ubuntu 21.04 (GNU ld 2.36.1)
* Fedora 33 (GNU ld 2.35-18.fc33)
* Fedora 35 (GNU ld 2.37-17.fc35)
* openSUSE Leap 15.4 (GNU ld 2.37.20211103-150100.7.37)
* SLES 15.4 (GNU ld 2.37.20211103-150100.7.37)

**Comment by dwoodwor-intel** [comment]
It looks like this is a bug specific to certain Red Hat builds of the gold linker; I managed to narrow the cause down to a specific distro patch in Fedora 34 (and presumably RHEL 9.0). I filed a Red Hat bug here: https://bugzilla.redhat.com/show_bug.cgi?id=2162798

Meanwhile, it looks like some more possible workarounds are to link against zlib directly (with `-lz`) or to use the lld linker instead (with `-fuse-ld=lld`).

**Comment by shiltian** [comment]
@dwoodwor-intel Thanks for the followup. Then I'll close this issue now as we are approaching release. Feel free to reopen it in the future if anything turns out to be wrong on our side.
