### ISSUE TITLE
Incorrect number of digits for std::format("{:+#.6g}", 1234.0)

### ISSUE THREAD

**Issue by jwakely** [llvm/llvm-project#58714]
The result of `std::format("{:+#.6g}", 1234.0)` should be `+1234.00` but libc++ prints `+1234.0`

It appears to count the `+` character as one of the significant digits.

**Comment by mordante** [comment]
Thanks for the report. As you mentioned on the reflector there is an issue with `#` and floating-point. I've a fix locally and I'll upload the fix when there's an LWG issue. (There are some test that are now correctly according the Standard, but need modification when `#` behaves as in printf.)

**Comment by mordante** [comment]
I've posted a fix https://reviews.llvm.org/D145306
