### ISSUE TITLE
Regressions from bc886e9b587b9d009f49b12eaaa9ebc1c71905a1

### ISSUE THREAD

**Issue by glandium** [llvm/llvm-project#58717]
- In Firefox, this causes multiple errors in e.g. the PNG test suite (which look like off-by-one in some computations).
- In clang itself (when built with a clang that contains bc886e9b587b9d009f49b12eaaa9ebc1c71905a1), this causes "error: out of range pc-relative fixup value" when compiling Firefox for ARMv7 android. (reproducer: https://gist.github.com/glandium/273f01e7c825750854e68d9bf6049d4f ; I didn't try to reduce the source)

Both the failures above have been bisected to bc886e9b587b9d009f49b12eaaa9ebc1c71905a1.

Cc: @rotateright

**Comment by jrtc27** [comment]
https://github.com/llvm/llvm-project/commit/bc886e9b587b9d009f49b12eaaa9ebc1c71905a1#diff-efa3000dc7eaa975d0cbb3243b500a049024a2c5698d4d6666f72e87769a9c9dR182 should be CreateSub

**Comment by glandium** [comment]
This was apparently reverted in e1de7ac20ff35aab00942f8adbc37a35ad67eaa4. https://reviews.llvm.org/rGbc886e9b587b9d009f49b12eaaa9ebc1c71905a1

**Comment by rotateright** [comment]
Thanks for the report and analysis! Sorry about the bug. 

Yes, the "add" that was copied from the earlier code was supposed to be a "sub", and I missed it. 

On the plus side, I wasn't sure if this pattern existed in real code, but the fallout from screwing up the patch says it occurs quite a bit. :)
