### ISSUE TITLE
[flang] Parse failure after spurious "Possible truncated Hollerith literal"

### ISSUE THREAD

**Issue by hawkinsp** [llvm/llvm-project#58732]
flang-new (built from LLVM commit 748922b31f7f1f48af76efc66a7af0674b1c4c06) fails to parse
https://github.com/python-control/Slycot/blob/v0.3.5/slycot/src/MC03MD.f

```console
$ flang-new -c slycot/src/MC03MD.f
./slycot/src/MC03MD.f:318:19: warning: Possible truncated Hollerith literal
                 DO 100 H = 1, CP2
                    ^^^^^^^^^^^^^^
error: Semantic errors in slycot/src/MC03MD.f
./slycot/src/MC03MD.f:318:30: error: No explicit type declared for 'CP2'
                 DO 100 H = 1, CP2
                               ^^^
```

`gfortran` 12.2.0 is happy with this file.

**Comment by adegomme** [comment]
same messages and error encountered when trying compiling https://github.com/Reference-ScaLAPACK/scalapack with flang-new
