### ISSUE TITLE
[flang] Semantic check for C723 is not implemented yet

### ISSUE THREAD

**Issue by PeixinQiao** [llvm/llvm-project#58757]
```f90
module test
contains
subroutine foo(proc_pointer)
  character(*), external, pointer :: proc_pointer
  print *, proc_pointer()
end subroutine

subroutine as_length2()
 character(2), external :: assumed_length
 character(2), external, pointer :: p
 p => assumed_length
 call foo(p)
end subroutine

subroutine as_length4()
 character(4), external :: assumed_length
 character(4), external, pointer :: p
 p => assumed_length
 call foo(p)
end subroutine
end module

character(*) function assumed_length()
 assumed_length = "abcdefghi"
end function

 use test
 call as_length2()
 call as_length4()
end
```
This expects one semantic error according to Fortran 2018 C723 (A function name declared with an asterisk type-param-value shall not be an array, a pointer, elemental, or pure.).

**Comment by tislam-git** [comment]
I would like to work on this issue. @PeixinQiao, could you please assign the issue to me (my git-id is tislam-git)?

**Comment by PeixinQiao** [comment]
@tislam-git Thanks for working on this. Assigned to you.

**Comment by tislam-git** [comment]
Fix submitted at https://reviews.llvm.org/D139333

**Comment by tislam-git** [comment]
Fix commit: https://github.com/llvm/llvm-project/commit/7fdd0c00e0ab030b64618778c24dc329ce3d1535

**Comment by PeixinQiao** [comment]
Thanks @tislam-git for the fix.
