### ISSUE TITLE
unnecessary pessimistic implementation of unordered_map and unordered_set

### ISSUE THREAD

**Issue by egawrilow** [llvm/llvm-project#58761]
As of llvm-15, the search loop in __hash table::__emplace_unique_key_args compares node keys even when hash codes are different, while the find method correctly compares hash codes first.  The fix is trivial: insert ```(__nd->__hash() == __hash) && ``` before ```key_eq()```.

**Comment by ilvokhin** [comment]
Patch: https://reviews.llvm.org/D140779

**Comment by philnik777** [comment]
The above PR has been landed.
