### ISSUE TITLE
[AMDGPU][MC][GFX10+] v_permlane16_b32 and v_permlanex16_b32 do not accept literals for src1 and src2

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#58762]
SP3 seems to allow literals for src1 and src2.

An example of failed test:

    v_permlane16_b32 v5, v1, s2, 0x12345678

Expected output:

    0x05,0x00,0x77,0xd7,0x01,0x05,0xfc,0x03,0x78,0x56,0x34,0x12

Actual result:

    error: invalid operand for instruction

Could anybody check if literals are allowed for these instructions?
Added @Sisyph and @jayfoad for awareness.

**Comment by jayfoad** [comment]
> Could anybody check if literals are allowed for these instructions?

As far as I know they are allowed. At least, I can't find any documentation saying they are _not_ allowed.

**Comment by dpreobra** [comment]
Fixed in 6e279f5bb663.
