### ISSUE TITLE
[flang] Bad function result for call to memcpy

### ISSUE THREAD

**Issue by psteinfeld** [llvm/llvm-project#58772]
Here's a test program:
```f90
program test_memcpy
  use iso_c_binding
  interface
    function memcpy(dest, src, len) bind(c)
      import c_ptr
      type(c_ptr), value :: dest, src
      integer(kind=4), value :: len
      type(c_ptr) memcpy
    end
  end interface
  integer(kind=4), target :: src, dest
  type(c_ptr) tmp
  src = 343
  tmp = memcpy(c_loc(dest), c_loc(src), 4)
  if (c_associated(tmp, c_loc(dest))) then
    print *, "OK"
  else
    print *, "Bad memcpy result"
    print *, "memcpy result: ", tmp
    print *, "c_loc(dest): ", c_loc(dest)
  end if
end
```
When I compile and execute it with gfortran, it prints "OK".  But I get messages that start with "Bad memcpy result" when I do: `flang-new -L lib && a.out`.

@PeixinQiao, is this in your area?

**Comment by PeixinQiao** [comment]
@psteinfeld Yes. Thanks for this case. This is what I want I to test later.

The problem is the function result type. The varaible `tmp` is returned by `VALUE` in gfortran and ifort. LLVM Flang return the result for `tmp` not by `VALUE`. I verified this by generating LLVM IR and hand-rewriting the LLVM IR. It prints `OK` now. Will fix this.

**Comment by psteinfeld** [comment]
> @psteinfeld Yes. Thanks for this case. This is what I want I to test later.
> 
> Will fix this.

Thanks, @PeixinQiao.  You're the best.

**Comment by PeixinQiao** [comment]
https://reviews.llvm.org/D137548

**Comment by PeixinQiao** [comment]
https://reviews.llvm.org/rGc336e72c82b11732f1728ab2f608ed99c7843258

**Comment by psteinfeld** [comment]
All looks good.  Thanks so much for fixing this.  You're hotter than a chili pepper!
