### ISSUE TITLE
Failed to use flang-new building CPU2017 548.exchange2_r

### ISSUE THREAD

**Issue by TaoTao-real** [llvm/llvm-project#58773]
Hi, I am trying to use flang-new in llvm-project to build CPU2017 benchmarks.
1. First `cd` the benchmark src file folder
```console
$ cd /path/to/exchange2_r/src
```
2. Try to use gfortran build, success
```console
$ gfortran exchange2.F90
```
4. Now I try to build with flang-new, failed with ld error
```console
$ flang-new exchange2.F90
/usr/local/bin/ld: cannot find -lFortran_main
/usr/local/bin/ld: cannot find -lFortranRuntime
/usr/local/bin/ld: cannot find -lFortranDecimal
flang-new: error:  linker command failed with exit code 1 (use -v to see invocation)
```
5. Find `libFortran_main.a` `libFortranDecimal.a` `libFortranRuntime.a` in `~/llvm-project/build/lib/`, add lib path to `PATH` envvariable
```console
$ ls ~/llvm-project/build/lib/*Fortran*
/home/llvm-project/build/lib/libFortranCommon.a
/home/llvm-project/build/lib/libFortranDecimal.a
/home/llvm-project/build/lib/libFortranEvaluate.a
/home/llvm-project/build/lib/libFortranEvaluateTesting.a
/home/llvm-project/build/lib/libFortranLower.a
/home/llvm-project/build/lib/libFortran_main.a
/home/llvm-project/build/lib/libFortranParser.a
/home/llvm-project/build/lib/libFortranRuntime.a
/home/llvm-project/build/lib/libFortranSemantics.a
$ export PATH=~/llvm-project/build/lib:$PATH
```
6. Try to build with flang-new, failed again with same ld error
```console
$ flang-new exchange2.F90
/usr/local/bin/ld: cannot find -lFortran_main
/usr/local/bin/ld: cannot find -lFortranRuntime
/usr/local/bin/ld: cannot find -lFortranDecimal
flang-new: error:  linker command failed with exit code 1 (use -v to see invocation)
```

Did I still forget to add some ld path to `PATH` env avariable caused this failure?

I build LLVM 16.0.0 (https://github.com/llvm/llvm-project.git a8085ffc924ca4f04303ea2635f9c76732689205) in x86 with command:
```console
$ cd ~/llvm-project
$ cmake -S llvm -B build -G "Unix Makefiles" -DLLVM_ENABLE_PROJECTS="bolt;clang;clang-tools-extra;compiler-rt;cross-project-tests;libclc;lld;lldb;mlir;openmp;polly;pstl;flang" -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" -DCMAKE_INSTALL_PREFIX=~/.local -DCMAKE_BUILD_TYPE=Release
$ cmake --build build -j 8
```

**Comment by kiranchandramohan** [comment]
`llvm/flang` is not ready for use by general users. If you are a developer then you can use the `flang-new` driver with the `-flang-experimental-exec` option. Adding this option will link the relevant libraries and create executables.
`exchange2_r` is known to work with `llvm/flang`.

**Comment by TaoTao-real** [comment]
> 

Thanks for your reply, it works!
