### ISSUE TITLE
Clang rejects valid constraint

### ISSUE THREAD

**Issue by ranaanoop** [llvm/llvm-project#58785]
The following valid program is rejected by clang but accepted by gcc and msvc. [Demo](https://godbolt.org/z/qf84qnn5v)

```
#include <iostream>
#include <type_traits>
#include <vector>
#include <string>
#include <functional>
#include <map>
#include <algorithm>
using namespace std;
struct t {
    constexpr auto b() const noexcept
    { return true; }
};

template<typename T>
concept c = requires (T t) {
    requires t.b();
};

static_assert(c<t>);
```

The clang error says:

```
<source>:19:1: error: static assertion failed
static_assert(c<t>);
^             ~~~~
<source>:19:15: note: because 't' does not satisfy 'c'
static_assert(c<t>);
              ^
<source>:16:14: note: because 't.b()' would be invalid: constraint variable 't' cannot be used in an evaluated context
    requires t.b();
             ^
```

**Comment by ranaanoop** [comment]
Looks like this is ill-formed as per [expr.prim.req.general#4](https://timsong-cpp.github.io/cppwp/n4868/expr.prim.req.general#4.sentence-4).

**Comment by ranaanoop** [comment]
Looks like this is ill-formed as per [expr.prim.req.general#4](https://timsong-cpp.github.io/cppwp/n4868/expr.prim.req.general#4.sentence-4) and clang is correct but gcc and msvc are wrong.

**Comment by EugeneZelenko** [comment]
@inclyc: Please elaborate.

**Comment by inclyc** [comment]
> @inclyc: Please elaborate.

Hi, I just looked at this issue and it was closed "as complete" but the author said "clang is correct".

**Comment by inclyc** [comment]
Did I just do something wrong?

**Comment by EugeneZelenko** [comment]
@inclyc: It was my fault, I should read entire thread. However, please add relevant label when closing as not planned.

**Comment by inclyc** [comment]
> ot planned.

Thanks!
