### ISSUE TITLE
swift error

### ISSUE THREAD

**Issue by ryannewcomer** [llvm/llvm-project#58796]
Hi, I just install swift on window and run swift repl and type 1 + 2, which will print out 3. but it said this instead:

![Screenshot 2022-11-03 201525](https://user-images.githubusercontent.com/88273136/199825047-59498ead-4419-4acd-b1ad-bd4ffc791a3d.png)

happy coding ! 👨‍💻

**Comment by asl** [comment]
Tagging @compnerd

**Comment by dwblaikie** [comment]
This should probably be reported in the Swift repo, not here - the SwingLanguangeRuntime.cpp isn't in the LLVM project - it's an extension in https://github.com/apple/swift-lldb

**Comment by compnerd** [comment]
This really is not the right place for reporting this.  I'm going to close the issue as this is not part of this project.  However, the REPL is known to require some hand-holding to work (see the Swift forums).
