### ISSUE TITLE
Some errors about  when intall LLVM andClang

### ISSUE THREAD

**Issue by Hope10086** [llvm/llvm-project#58804]
I try to install the latest LLVM and Clang   which could  complie in  C++20  on Ubuntu 18.01LTS  after reading the  information on [LLVM Debian/Ubuntu nightly packages](url ：https://apt.llvm.org/)
Probably because of my incorrect installation process,  when I run the command `"bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"`"the terminal would show me as following:

The word in Chinese "依赖"means  “ dependencies".
```
The following packages have unmet dependencies:
 clang-15 : 
            依赖: libclang-cpp15 (>= 1:15.0.4~++20221102053248+5c68a1cb1231) 但是它将不会被安装
            依赖: libgcc-s1 (>= 3.0) 但无法安装它//translation：But you can't install it
            依赖: libllvm15 但是它将不会被安装 ///translation：But it will not be installed
            依赖: libstdc++-9-dev 但无法安装它
            依赖: libgcc-9-dev 但无法安装它
            依赖: libobjc-9-dev 但无法安装它
            依赖: libclang-common-15-dev (= 1:15.0.4~++20221102053248+5c68a1cb1231-1~exp1~20221102053256.89) 但是它将不会被安装
            依赖: llvm-15-linker-tools (= 1:15.0.4~++20221102053248+5c68a1cb1231-1~exp1~20221102053256.89) 但是它将不会被安装
            依赖: libclang1-15 (= 1:15.0.4~++20221102053248+5c68a1cb1231-1~exp1~20221102053256.89) 但是它将不会被安装
            推荐: llvm-15-dev 但是它将不会被安装
 clangd-15 : 依赖: libc6 (>= 2.29) 但是 2.27-3ubuntu1.6 正要被安装
             依赖: libclang-cpp15 (>= 1:15.0.4~++20221102053248+5c68a1cb1231) 但是它将不会被安装
             依赖: libgcc-s1 (>= 3.0) 但无法安装它
             依赖: libllvm15 但是它将不会被安装
             依赖: libclang-common-15-dev (= 1:15.0.4~++20221102053248+5c68a1cb1231-1~exp1~20221102053256.89) 但是它将不会被安装
 lld-15 : 依赖: libgcc-s1 (>= 3.0) 但无法安装它
          依赖: libllvm15 (= 1:15.0.4~++20221102053248+5c68a1cb1231-1~exp1~20221102053256.89) 但是它将不会被安装
 lldb-15 : 依赖: libclang-cpp15 (>= 1:15.0.4~++20221102053248+5c68a1cb1231) 但是它将不会被安装
           依赖: libgcc-s1 (>= 3.0) 但无法安装它
           依赖: liblldb-15 但是它将不会被安装
           依赖: libllvm15 (= 1:15.0.4~++20221102053248+5c68a1cb1231-1~exp1~20221102053256.89) 但是它将不会被安装
           依赖: libncurses6 (>= 6) 但无法安装它
           依赖: libtinfo6 (>= 6) 但无法安装它
           依赖: llvm-15-dev 但是它将不会被安装
           依赖: python3-lldb-15 但是它将不会被安装
E: You cannot fix the bug because you require certain packages to remain as they are, breaking dependencies between packages
```

Some details about my operations when installing.

1. **Following  has been added  to the   **source.list**  (its path is  /etc/apt) :**

#LLVM    bionic-source
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main
deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic main
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-14 main
deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-14 main
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-15 main
deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-15 main
##LLVM  focal -source
deb http://apt.llvm.org/focal/ llvm-toolchain-focal main
deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal main

deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main
deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main

deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main
deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main

2. ** I also try to run other command on the   *https://apt.llvm.org* 
like： 
```
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
sudo ./llvm.sh-14
Or
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
sudo ./llvm.sh -14  all
Or
apt-get install clang-14 lldb-14 lld-14
etc...
```
And the results are same .
What should I do？

**Comment by xgupta** [comment]
>What should I do？

Building Clang from source is the best to get the latest C++ features. Here you can follow the documentation - https://clang.llvm.org/get_started.html.
