### ISSUE TITLE
[llvm-reduce] Replace invoke with call

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#58815]
llvm-reduce currently often leaves behind unnecessary invokes. We should try to replace

```ll
%x = invoke @foo()
  to label %cont unwind label %lpad
```
with
```ll
%x = call @foo()
br label %cond
```

**Comment by nikic** [comment]
On a related note, once all the invokes are gone, we should also drop the `personality` function.

**Comment by nikic** [comment]
cc @arsenm @aeubanks as you've been doing a lot of llvm-reduce work recently.

**Comment by arsenm** [comment]
These should just cover it:
https://reviews.llvm.org/D140862
https://reviews.llvm.org/D140863
https://reviews.llvm.org/D140864
