### ISSUE TITLE
URL in Benchmarking tips documentation gives 404

### ISSUE THREAD

**Issue by sloorush** [llvm/llvm-project#58813]
>>! In D137418#3907994, @sloorush wrote:
> I also found another mistake on the same page of the docs that https://www.cis.upenn.edu/~cis501/papers/producing-wrong-data.pdf URL opens a 404 page. I was not sure what to replace it with, if someone can point me in the right direction, I will be happy to fix that as well.

_Copied from https://reviews.llvm.org/D137418 comment by me_

This URL is in in the page https://llvm.org/docs/Benchmarking.html#introduction

**Comment by JOE1994** [comment]
URL no longer gives 404 error (as of March 13, 2024 UTC 04:00 )
