### ISSUE TITLE
"initializer-string for char array is too long" is a poor diagnostic

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#58829]
See https://godbolt.org/z/8na7nozro

```c++
constexpr char foo[3] = "abc";
```

What's the expected length? Why is the length wrong? The diagnostic here is pretty bad.

**Comment by EugeneZelenko** [comment]
Also `fix-it` is possible.

**Comment by shafik** [comment]
Note, this is valid C: https://godbolt.org/z/1q99Pfob4

C does not require space for the terminating null character: https://stackoverflow.com/a/20694830/1708801

**Comment by tbaederr** [comment]
That's alright, but still good to know for someone working on this, thanks.

**Comment by evansmal** [comment]
I'm interested in picking this up. Are people normally assigned to issues here?

**Comment by dwblaikie** [comment]
We're usually pretty casual, but feel free to assign it to yourself to indicate you're looking into it.

**Comment by evansmal** [comment]
I have opened a pull request here: https://reviews.llvm.org/D141283. 

@dwblaikie Is this the expected way to submit a patch?

**Comment by dwblaikie** [comment]
> I have opened a pull request here: https://reviews.llvm.org/D141283.
> 
> @dwblaikie Is this the expected way to submit a patch?

Yep, that's good - looks like some folks have provided feedback/started the discussion.

**Comment by karishmaupreti** [comment]
I want to work on this issue,please assign me this issue.

**Comment by tbaederr** [comment]
I think this issue is already resolved as soon as https://reviews.llvm.org/D141283 gets pushed.

**Comment by evansmal** [comment]
> I think this issue is already resolved as soon as https://reviews.llvm.org/D141283 gets pushed.

Speaking of - @tbaederr are you able to push https://reviews.llvm.org/D141283? I'm not able to commit it myself.
