### ISSUE TITLE
Where is the correct forum to suggest a change to the std c++ std future standard?

### ISSUE THREAD

**Issue by timprepscius** [llvm/llvm-project#58824]
Where is the correct forum to suggest a change to the std c++ std future standard?

I would like to suggest an implementation detail for std::future's then.

In a nutshell, I've been working on an implementation of futures with "then" enabled.  I assume C++2? at some point will have futures with thens.  Hopefully they will implement them so they do not need threads.

In any case -
If they have the future<X>::then call out to a non class member future_then(future, then), it allows for some neat things.
Like having the thens' gets returning another future, which can then be thened against, without any weird code.

I figure you guys would know the best forums to post this suggestion, with some examples, etc.

**Comment by tbaederr** [comment]
Questions are usually better to be asked on Discourse: https://discourse.llvm.org/
