### ISSUE TITLE
Unable to call method with forward-declared template variable: "implicit instantiation of undefined template"

### ISSUE THREAD

**Issue by danakj** [llvm/llvm-project#58835]
These code examples compile in GCC and MSVC in C++11 or newer modes. They fail in Clang in C++11 and newer modes.

# Template methods with forward-declared templated type

Here two methods are templated to avoid knowing the full type of ForwardDecl in their definitions. The template has a default value which is the forward declared type.

Simply constructing the template type works ok, as in `works()`. However calling from one method to the other does not, it tries to instantiate the ForwarDecl template and fails. This works in GCC and MSVC.

```console
<source>:8:16: error: implicit instantiation of undefined template 'ForwardDecl<int>'
        return works();
               ^
<source>:2:7: note: template is declared here
class ForwardDecl;
      ^
1 error generated.
```

https://godbolt.org/z/53sf4Ed5T

```cpp
template <class T>
class ForwardDecl;

struct S {
    template <class Alias = ForwardDecl<int>>
    Alias doesntwork() {
        // This fails to compile in Clang. Calling `works<Alias>()` succeeds.
        return works();
    }

    template <class Alias = ForwardDecl<int>>
    Alias works() {
        return Alias();
    }
};

template <class T>
class ForwardDecl {};

int main() {
    S().doesntwork();
    S().works();
}
``` 

# Template methods with forward-declared non-templated type

While minimizing the above, I noticed that the compiler error is different if the forward-declared type is not itself templated. In this case, it says `works()` has an incomplete return type. Again, this works in GCC and MSVC.

```console
<source>:7:16: error: calling 'works<ForwardDecl>' with incomplete return type 'ForwardDecl'
        return works();
               ^~~~~~~
<source>:11:11: note: 'works' declared here
    Alias works() {
          ^
<source>:1:7: note: forward declaration of 'ForwardDecl'
class ForwardDecl;
      ^
1 error generated.
```

https://godbolt.org/z/sdsE49Mo3

```cpp
class ForwardDecl;

struct S {
    template <class Alias = ForwardDecl>
    Alias doesntwork() {
        // This fails to compile in Clang. Calling `works<Alias>()` succeeds.
        return works();
    }

    template <class Alias = ForwardDecl>
    Alias works() {
        return Alias();
    }
};

class ForwardDecl {};

int main() {
    S().doesntwork();
    S().works();
}
```

**Comment by alanzhao1** [comment]
This can be further reduced by removing `struct S`:

```cpp
class ForwardDecl;

template <class Alias = ForwardDecl>
Alias works() {
    return Alias();
}

template <class Alias = ForwardDecl>
Alias doesntwork() {
    return works(); // <-- Incomplete return type error here according to Clang
}

class ForwardDecl {};

int main() {
    doesntwork();
    works();
}
```

See: https://godbolt.org/z/rdzsssWhf

It looks like according to Clang, the complete type definition for `ForwardDecl` must be available at the exact point where template deduction for `works()` is performed, even if template deduction for `works()` is done inside a templated function itself. Therefore, the example works if `ForwardDecl` is defined before `doesntwork()`:

```cpp
class ForwardDecl;

template <class Alias = ForwardDecl>
Alias works() {
    return Alias();
}

class ForwardDecl {};

template <class Alias = ForwardDecl>
Alias doesntwork() {
    return works(); // actually works
}

int main() {
    doesntwork();
    works();
}
```

(see https://godbolt.org/z/GEYjhq6Pe)

and the call to `works()` in `main()` fails if `ForwardDecl` is defined after `main()` (in both Clang and GCC, not just Clang):

```cpp
class ForwardDecl;

template <class Alias = ForwardDecl>
Alias works() {
    return Alias();
}

template <class Alias = ForwardDecl>
Alias doesntwork() {
    return works();
}

int main() {
    doesntwork(); // incomplete type
    works(); // also incomplete type
}

class ForwardDecl {};
```
(see https://godbolt.org/z/1oe31faqE)

TBH I'm not sure what the standard says in this case...

**Comment by zygoloid** [comment]
This code is invalid; see https://clang.llvm.org/compatibility.html#undep_incomplete

**Comment by danakj** [comment]
Thanks for the link. As I understand it, types that don't depend on the template must be complete. In `doesntwork()` the return type is `Alias` from `works()`, which happens to be the same type as the template parameter to `doesntwork()` but it doesn't _depend_ on the template parameter, it's chosen independently. So this is rejected.
