### ISSUE TITLE
function template fails with a 'float' template argument

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#58830]
This code:
```c++
template<float M> 
static float F()  {
        return M;
}


int main() {
        F<0.1f>();

        return 0;
}
```
fails with Clang version 16.0.0:
```console
testcase.cpp:10:2: error: no matching function for call to 'F'
        F<0.1f>();
        ^~~~~~~
testcase.cpp:4:14: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'M'
static float F()  {
             ^
1 error generated.
```

**Comment by wangyantian1** [comment]
The c++ standard doesn't allow floating points as non-type template-arguments. The `g++` also failed to compile your example.

**Comment by yurivict** [comment]
GCC-11 compiles this example successfully.

**Comment by shafik** [comment]
I believe this is also: https://github.com/llvm/llvm-project/issues/58352

and so this is not implemented yet.

**Comment by AaronBallman** [comment]
> I believe this is also: #58352
> 
> and so this is not implemented yet.

Agreed, closing this as a duplicate.
