### ISSUE TITLE
DW_AT_name is not same for "long long int" type from clang-14

### ISSUE THREAD

**Issue by UmeshKalappa0** [llvm/llvm-project#58838]
Hi,
Our DWARF consumer is breaking with the change from clang-14 like 
https://godbolt.org/z/5h1cTjPGK

was
```asm
.Linfo_string4:
        .asciz  "long long int"
```

But from clang-14
we have
```asm
.Linfo_string4:
        .asciz  "long long"
```

**Comment by dwblaikie** [comment]
Yeah - intended change. These were originally implemented I think for really precise reproduction of GCC's type naming - but debuggers are more flexible now & we don't need to name types identically.

Specifically I made this change to make the names consistent with template naming (eg: `t1<long long>`) to help `-fsimple-template-names` verification & improve Clang's self-consistency.

**Comment by UmeshKalappa0** [comment]
Thank you @dwblaikie  for the info  and we need to change the our dwarf consumer here then ?.

**Comment by dwblaikie** [comment]
> Thank you @dwblaikie for the info and we need to change the our dwarf consumer here then ?.

Yep!

**Comment by dwblaikie** [comment]
(I'd suggest making a consumer resilient to minor changes in spelling of these sort of types - eg: "long long int" could be written as things like "long long signed int" (or putting those words in different orders) or "long long", etc)
