### ISSUE TITLE
--quiet does not silence "N warnings generated." message

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#58842]
Hi,

We find that the `--quiet` option of clang-tidy does not silence the "N warnings generated" text. Example: https://godbolt.org/z/fPofGEa97

This message clutters the build logs quite a lot for code that doesn't have warnings (either they are in system headers, or have been suppressed).

Would it be possible to also silence this message with the `--quiet` option? Not sure if this is a bug or an enhancement, so I'll add both tags :)

**Comment by AaronBallman** [comment]
Closing as a duplicate of #47042
