### ISSUE TITLE
ASAN causes crash after overriding function with backward jmp

### ISSUE THREAD

**Issue by gregstoll** [llvm/llvm-project#58846]
To reproduce: Download and run the latest [Firefox ASAN build](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.mozilla-central.latest.firefox.win64-asan-opt/artifacts/public/build/target.zip) on Windows 11 (version 10.0.22621 Build 22621)
; it will crash on launch. 

The problem seems to be that when overriding the `memset` function in `OverrideFunctionWithRedirectJump()`, the `relative_offset` is stored as a `uptr`. Per the [Intel x64 instruction set reference](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf) (warning: large PDF), on page 646 the `jmp` instruction (specifically the near jump flavors that start with `E9`, which are the ones the `OverrideFunctionWithRedirectJump()` considers) treats the offset as a signed displacement. This causes an incorrect value to be stored for `REAL(memset)` which points to uninitialized memory, and a crash the next time that gets called.

The fix is to simply treat that offset as signed. I have attached a patch that I believe will fix it, along with a test; unfortunately I've been struggling to build and run these tests so I haven't been able to verify that it works.

[0001-compiler-rt-windows-Correctly-override-functions-wit.patch.txt](https://github.com/llvm/llvm-project/files/9952943/0001-compiler-rt-windows-Correctly-override-functions-wit.patch.txt)

**Comment by alvinhochun** [comment]
Can you submit the patch as a code review? See https://llvm.org/docs/Phabricator.html

**Comment by gregstoll** [comment]
I would love to, but I haven't been able to build LLVM or run the new test I wrote to make sure it passes. Will the test I modified get run as part of the code review process? Or should I just submit it anyway?

Thanks!

**Comment by alvinhochun** [comment]
Submitting the patch will trigger some pre-merge check though I do not know whether it runs tests for the sanitizers. Please do submit the patch for review so things can move forward. Probably a reviewer will check the tests. And even if it breaks something after merging, we can always revert the commit.

**Comment by gregstoll** [comment]
Thanks! I put [D137788](https://reviews.llvm.org/D137788) up for review.
