### ISSUE TITLE
[avr] Tools won't understand their own assembly code.

### ISSUE THREAD

**Issue by sprintersb** [llvm/llvm-project#58853]
Compile the following C module with
```console
> clang --target=avr -c -save-temps
```

```c++
int r25, x;
void foo (void)
{
    r25 = x;
}
```

This will throw 4 errors at you:
```console
*.s:8:11: error: invalid operand for instruction
        lds     r24, x
                     ^
*.s:9:11: error: invalid operand for instruction
        lds     r25, x+1
                     ^
*.s:10:6: error: invalid operand for instruction
        sts     r25+1, r25
                ^
*.s:11:6: error: invalid operand for instruction
        sts     r25, r24
                ^
```
The generated assembly code is all fine:
```asm
foo:
	lds	r24, x
	lds	r25, x+1
	sts	r25+1, r25
	sts	r25, r24
	ret
```

* The 2nd operand of `lds` is an absolute address, hence legitimate operands are: symbol, symbol+offset or integer.  Hence its obvious that `x` names a symbol, not a register.

*  The 1st operand of `sts` is an absolute address, hence legitimate operands are: symbol, symbol+offset or integer.  Hence its obvious that `r25` in the 1st operand names a symbol, not a register.

The appropriate RELOCs are of type `R_AVR_16` in all the cases.

**Comment by benshi001** [comment]
fixed by https://reviews.llvm.org/D140777

**Comment by benshi001** [comment]
fixed by https://github.com/llvm/llvm-project/commit/7a45b13cd726d04139006fa9aea32940d3158b0f

**Comment by sprintersb** [comment]
Let ma add that the same problem also occurs with `[r]jmp` and `[r]call` when they are targetting a symbol like `r24` or `x`. Again, compile with '-save-temps':
```c++
int r24 (void);
int x (void);

int main (void)
{
    return x() + r24();
}
```
`x` and `r24` are symbols that are perfectly fine, and let me add that with AVR ISA, there is no ambiguitiy of which kind an operand is.  In the case above, it's a symbol or symbol+offset or int (any absolute constant that's known at link time or earlier).

**Comment by benshi001** [comment]
> ymbols that are perfectly fine, and let me add that with AVR ISA, the

This case is also fixed in the main branch. I have tested your new case with `--save-temps` and there is no failure report.
