### ISSUE TITLE
[avr] Code links __do_clear_bss and __do_copy_data even if respective sections are empty.

### ISSUE THREAD

**Issue by sprintersb** [llvm/llvm-project#58857]
Clang will issue 
```s
.globl	__do_copy_data
.globl	__do_clear_bss
```
even for modules that don't have objects in `.data` or `.bss` or `COMMON`, (or in `.rodata` for devices that do not see flash in RAM address space).

Result is that useless code from libgcc is dragged, which just increases code size without any benefit or purpose.

**Comment by aykevl** [comment]
Here is a patch: https://reviews.llvm.org/D140830
