### ISSUE TITLE
[avr] Built-in macro __flash clobbers namespace of the application

### ISSUE THREAD

**Issue by sprintersb** [llvm/llvm-project#58855]
Identifiers like `address_space` live in the namespace of the application, thus the implementation (compiler in this case) should avoid them whenever possible. C code like following is completely fine and supposed to compile:

```c
#define address_space 1
const __flash int xxx;
```
The problem is that `__flash` is built-in defined as, here from a pre-processed source file with `-dM`:
```c
#define __flash __attribute__((address_space(1)))
```
where the correct definition would read:
```c
#define __flash __attribute__((__address_space__(1)))
```
Notice that identifier `__address_space__` is in the namespace of the implementation, thus the application is not supposed to mess with it.

**Comment by benshi001** [comment]
fixed by https://reviews.llvm.org/D141598

**Comment by benshi001** [comment]
fixed in https://github.com/llvm/llvm-project/commit/16f9451b07619cd84e0b88ff17ca2b27a2c1f9cc
