### ISSUE TITLE
bin/../include/c++/v1/stdio.h:107:15: fatal error: 'stdio.h' file not found

### ISSUE THREAD

**Issue by fujian26** [llvm/llvm-project#58867]
```console
clang+llvm-15.0.3-x86_64-apple-darwin/bin/../include/c++/v1/stdio.h:107:15: fatal error: 'stdio.h' file not found
#include_next <stdio.h>
```

when I run
```shell
./clang+llvm-15.0.3-x86_64-apple-darwin/bin/clang++ test.cc -o test
```

In MacOS Montery, I downloaded `clang+llvm-15.0.3-x86_64-apple-darwin.tar.xz`.

`test.cc` code:
```cpp
#include <stdio.h>

int main(int argc, char *argv[]) {

	printf("ok\n");

	return 0;
}
```

**Comment by DimitryAndric** [comment]
You still need to install either Xcode or the Command Line Tools, to get the system headers and libraries that are necessary for this to work.

E.g. run:

```
sudo xcode-select --install
```

and follow the prompts, or install Xcode from the App Store.
