### ISSUE TITLE
[avr] Wrong code for avrtiny core family: wrong encoding of LDS / STS.

### ISSUE THREAD

**Issue by sprintersb** [llvm/llvm-project#58876]
Compile the following C code with `--target=avr -Os -mmcu=attiny40`:
```c++
int xx;
int main (void)
{
    return xx;
}
```
Disassembling the final ELF will read something like:
```objdump
0000005c <main>:
  5c:	80 91 40 00 	lds	r24, 0x0040	; 0x800040 <xx>
  60:	90 91 41 00 	lds	r25, 0x0041	; 0x800041 <xx+0x1>
  64:	08 95       	ret
```
which is wrong code because on reduced tiny, `lds` and `sts` are 16-bit instructions. Compiling the same code with avr-gcc and `-mabsdata`, the disassembly reads:
```objdump
00000046 <main>:
  46:	80 a1       	lds	r24, 0x40	; 0x800040 <xx>
  48:	91 a1       	lds	r25, 0x41	; 0x800041 <xx+0x1>
  4a:	08 95       	ret
```
Notice that not all of SRAM can be accessed by means of `lds`/`sts`, so special care must be taken when using absolute addresses for SRAM.

**Comment by benshi001** [comment]
Three patches will fix this bug,

https://reviews.llvm.org/D139621
https://reviews.llvm.org/D139687
https://reviews.llvm.org/D139807

**Comment by benshi001** [comment]
fixed by
https://github.com/llvm/llvm-project/commit/77249ea6bc6601d2637cf6c1d73c87c25faf1b71
https://github.com/llvm/llvm-project/commit/a59e96f1a1649580df8bf19d1ff296ab1a027a1f
