### ISSUE TITLE
[avr] Inline assembly constraint "i" not working.

### ISSUE THREAD

**Issue by sprintersb** [llvm/llvm-project#58879]
[Inline assembly documentation](https://clang.llvm.org/compatibility.html#inline-asm) states that:
> *"Clang is highly compatible with the GCC inline assembly extensions, allowing the same set of constraints, modifiers and operands as GCC inline assembly."*

Clang doesn't even document generic constraints, so all constraints should work like in GCC, in particular `"i"` which means *"immediate"* in GCC, which is a value that's known at link time or earlier.

The following code just loads `&gc` (which is known at link time, thus satisfies `"i"`) to `addr`:
```c++
char gc;

char* func (void)
{
    char *addr;
    __asm ("ldi %A0, lo8(%1)" "\n\t"
           "ldi %B0, hi8(%1)"
           : "=d" (addr)
           : "i" (&gc));
    return addr;
}
```

The following crazy code is generated with `-target avr -Os -save-temps -mmcu=atmega168`:
```asm
func:
	;APP
	ldi	r24, lo8(94043489596112)
	ldi	r25, hi8(94043489596112)
	;NO_APP
	ret
```
where avr-gcc generates:
```asm
func:
/* #APP */
	ldi r24, lo8(gc)
	ldi r25, hi8(gc)
/* #NOAPP */
	ret
```
and symbol `gc` resolves to the SRAM address of `gc`

**Comment by benshi001** [comment]
Fixed in https://reviews.llvm.org/D142096

**Comment by sprintersb** [comment]
Just for the record: This should work for all variables in static storage (like taking the address of a member of a struct), not only global ones.  An example is
```c++
typedef struct { int a[2]; } a_t;

int* func (void)
{
    static a_t var[2];
    int *addr;
    __asm ("ldi %A0, lo8(%1)" "\n\t"
           "ldi %B0, hi8(%1)"
           : "=d" (addr)
           : "i" (&var[1].a[1]));
    return addr;
}
```
Resulting code should be something like:
```
func:
/* #APP */
	ldi r24, lo8(var.1511+6)
	ldi r25, hi8(var.1511+6)
/* #NOAPP */
	ret
	.size	func, .-func
	.local	var.1511
	.comm	var.1511,8,1
```

**Comment by benshi001** [comment]
With my patch, the following assembly is generated against your new test case.

```
        .text
.set __tmp_reg__, 0
.set __zero_reg__, 1
.set __SREG__, 63
.set __SP_H__, 62
.set __SP_L__, 61
        .file   "a.c"
        .globl  func                            ; -- Begin function func
        .p2align        1
        .type   func,@function
func:                                   ; @func
; %bb.0:
        ;APP
        ldi     r24, lo8(func.var+6)
        ldi     r25, hi8(func.var+6)
        ;NO_APP
        ret
.Lfunc_end0:
        .size   func, .Lfunc_end0-func
                                        ; -- End function
        ; Declaring this symbol tells the CRT that it should
        ;clear the zeroed data section on startup
        .globl  __do_clear_bss
        .type   func.var,@object                ; @func.var
        .local  func.var
        .comm   func.var,8,1
        .addrsig
        .addrsig_sym func.var
```

**Comment by sprintersb** [comment]
> With my patch, the following assembly is generated
Great! Thank you for fixing this issue.

**Comment by benshi001** [comment]
fixed as commit https://github.com/llvm/llvm-project/commit/c919ea5b486041021a48b487145120fe0bcb70a8
