### ISSUE TITLE
[avr] Wrong operand in inline asm.

### ISSUE THREAD

**Issue by sprintersb** [llvm/llvm-project#58874]
Take the following C code:

```c++
char func (char *x)
{
    char c;
    __asm ("ld %0, %a1" : "=r" (c) : "x" (x));
    return c;
}
```
and compile with `--target=avr -Os -save-temps -mmcu=atmega2560`.  The generated assembly will read
```asm
func:
	movw	r26, r24
	;APP
	ld	r24, Y
	;NO_APP
	...
```
which is wrong code because `"x"` specifies register class with regs R26, R27.  But Y is R28, R29.

Strangely enough, `x` is moved to `r26` which is correct, but the operand printed for `%a1` is wrong.

**Comment by benshi001** [comment]
fixed in https://github.com/llvm/llvm-project/commit/3730f134281375671a5eeeecec42eabe901c2379, please retry your code with the newest llvm main branch.
