### ISSUE TITLE
is_trivially_copyable returns wrong result with constrained ctor and assignment operators

### ISSUE THREAD

**Issue by AMDG2** [llvm/llvm-project#58870]
Hello, we are rolling out our own optional implementation. While making sure our optional is trivially copyable and movable for types that are trivially copyable/movable themselves we found an inconsistency between Clang against both GCC and MSVC compilers.

A complete test case can be found here: https://godbolt.org/z/c38rYx8zq

The most reduced one I could find is this (https://godbolt.org/z/GeszesT6q):
```cpp
template <typename T>
struct Optional {
public:
    // Trivial copy/move constructors
    Optional(const Optional& other) noexcept requires(std::is_trivially_copy_constructible_v<T>) = default;
    Optional(Optional&& other) noexcept requires(std::is_trivially_move_constructible_v<T>) = default;

    // Non-Trivial copy/move constructors
    Optional(const Optional& other) requires(!std::is_trivially_copy_constructible_v<T>);
    Optional(Optional&& other) requires(!std::is_trivially_move_constructible_v<T>);

    // Trivial assignment operators
    Optional& operator=(const Optional& other) noexcept requires (std::is_trivially_copy_assignable_v<T>) = default;
    Optional& operator=(Optional&& other) noexcept requires (std::is_trivially_move_assignable_v<T>) = default;

    // Non-Trivial assignment operators
    Optional& operator=(const Optional& other) requires (!std::is_trivially_copy_assignable_v<T>);
    Optional& operator=(Optional&& other) requires (!std::is_trivially_move_assignable_v<T>);
};

// The following assertion works with GCC and MSVC, but not with Clang.
static_assert(std::is_trivially_copyable<Optional<int>>::value);
// This works on GCC, MSVC and Clang.
static_assert(!std::is_trivially_copyable<Optional<std::string>>::value);
```

We have reproduced this issue on Windows using Clang and the Microsoft STL, and as shown in Godbolt it also fail on Linux with Clang and stdlibc++. From our point of view it is a compiler bug in Clang.

I would be happy to help fix this, but I have no experience with Clang codebase.

**Comment by royjacobson** [comment]
This is P0848 (conditionally trivial member functions) which only got into 16. (https://reviews.llvm.org/D128619)

Closing as completed.
