### ISSUE TITLE
[avr] Return values are promoted to (unsigned) int for no reason.

### ISSUE THREAD

**Issue by sprintersb** [llvm/llvm-project#58877]
Compile with `--target=avr -mmcu=atmega8 -Os -save-temps` the following code:
```c++
char func (char c)
{
    return c;
}
```
The generated assembly reads:
```asm
func:
	mov	r25, r24
	lsl	r25
	sbc	r25, r25
	ret
```
which just wastes 3 cycles and 6 bytes for integer promotion that's not required.

**Comment by benshi001** [comment]
That is a patch to fix this bug, https://reviews.llvm.org/D139908

**Comment by benshi001** [comment]
fixed by https://github.com/llvm/llvm-project/commit/b2638a7a34d97066caa234999055bf580cbab02f
