### ISSUE TITLE
[DAGCombiner] WRONG code (visitSTORE)

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#58883]
[testcase.tar.gz](https://github.com/llvm/llvm-project/files/9966027/testcase.tar.gz)

This program is supposed to print some `0`s:

```c
struct a {
  short b;
  unsigned c;
} e = {9, 0}, *f = &e;

unsigned d = 0;
void h(struct a i) {
  *f = i;
  e.b = 0;
  d = i.c;
}

int main() {
  h(e);
  for (int g = 0; g < 10; g++)
    printf("%d\n", e.b);
}
```

It instead prints some `9`s with these options:
```shell
clang -march=arch13 -O3 wrong0.i -o a.out -mllvm -pre-RA-sched=list-ilp -mllvm -disable-sched-live-uses=false
```

(The extra options are for the scheduler which are needed to expose an earlier incorrect transformation by DAGCombiner.)

The initial DAG is created with the storing of the `0` chained after the previous two stores to the `e` struct:

```
t13: ch = store<(store (s32) into %ir.1)> t12, t8, t11, undef:i64
  t27: i64 = SystemZISD::PCREL_WRAPPER TargetGlobalAddress:i64<ptr @printf> 0
            t15: i64 = add nuw t11, Constant:i64<4>
          t16: ch = store<(store (s32) into %ir.i.sroa.2.0..sroa_idx.i)> t13, t9, t15, undef:i64
        t18: ch = store<(store (s16) into @e, align 8, !tbaa !14)> t16, Constant:i16<0>, GlobalAddress:i64<ptr @e> 0, undef:i64
        t55: ch = store<(store (s32) into @d, !tbaa !11)> t13, t9, GlobalAddress:i64<ptr @d> 0, undef:i64
```
Here `t18` does not alias `t16` so it is effectively removed from the ordering deps of `t18`, which is correct. This is done by `DAGCombiner::FindBetterChain()` / `GatherAllAliases()` which returns BetterChain: t13. After this `t18` is chained only after `t13`, and not `t16`.

Then `t16` is visited by `DAGCombiner::visitSTORE() : mergeTruncStores(ST)`

```
Combining: t16: ch = store<(store (s32) into %ir.i.sroa.2.0..sroa_idx.i)> t13, t9, t15, undef:i64
 ... into: t60: ch = store<(store (s64) into %ir.1, align 4)> t12, t4, t11, undef:i64
```

This is problematic as the first optimization of `t18` was based on `t16` not aliasing (as long as it was only writing 32-bits), which now `t60` does (it writes its original 32-bits and now also the same bits as the constant `0` is supposed to end up in)!

 ```
 t13: ch = store<(store (s32) into %ir.1)> t12, t8, t11, undef:i64
  t27: i64 = SystemZISD::PCREL_WRAPPER TargetGlobalAddress:i64<ptr @printf> 0
          t9: i32 = truncate t4
        t55: ch = store<(store (s32) into @d, !tbaa !11)> t13, t9, GlobalAddress:i64<ptr @d> 0, undef:i64
        t60: ch = store<(store (s64) into %ir.1, align 4)> t12, t4, t11, undef:i64
        t57: ch = store<(store (s16) into @e, align 8, !tbaa !14)> t13, Constant:i16<0>, GlobalAddress:i64<ptr @e> 0, undef:i64
```

The end result is that the constant `0` stored by `t18`/`t57` which must come last ends up going before `t60` in the final schedule, giving an incorrect result.

**Comment by rotateright** [comment]
Thanks for the report and analysis. Can you push a codegen test to main that shows the failure and mark it with a FIXME comment? That way, we can be sure we have the right test settings to verify a fix (though I'm not sure what the fix is yet!).

**Comment by JonPsson** [comment]
I tried a bisect and it seems this was present at least a year back on the reduced test case, so this seems like a pretty old and nasty bug. Not sure exactly what kind of test would be needed, something like an XFAIL? I don't quite understand the workflow here... someone commits something that causes the XFAIL not to fail and is then supposed to figure out how to make that XFAIL fail again..?

**Comment by rotateright** [comment]
No, it shouldn't be an XFAIL. It should be a regular test, but it shows a miscompile, so it has a FIXME label.

I came up with a possible solution, so I just want to be sure that we're getting a valid fix that will show up as an asm diff. And then you can probably easily verify if the fix works...I'm SystemZ illiterate, so I'm not sure what I'm seeing in the instructions. :)

**Comment by rotateright** [comment]
And I agree, this bug has likely been around for a long time. I was staring at our other store merging SDAG transforms all day, and wow, it's a complicated mess!

**Comment by JonPsson** [comment]
Yeah, I am a little nervous about that code that just replaces the 32-bit store with a 64-bit one... Wouldn't that mean that it would have to check all stores somehow connected (chained) if ther is an alias with the *new* store...? That would not necessarily have the same connections as the original store had... But I don't really know much about that optimization...

Maybe a test that stops after isel? Looking at the .mir dump there I think you could see on the memory operands at least where the store of constant 0 occurs...  It must come after the 64-bit store overlapping the same address.

**Comment by rotateright** [comment]
If we stop after isel, the store of 0 (`t57` in the original description) isn't before the 64-bit store (`t60`) though, right?

This is what I see if I output the source to SystemZ asm using the scheduler options from the original description :
	srlg	%r0, %r2, 32
	st	%r0, 0(%r1)
	lhi	%r0, 0
	stg	%r2, 0(%r1)  <-- 64-bit store
	sthrl	%r0, e  <-- store of 0
	strl	%r2, d

Is my understanding of the asm correct?

**Comment by rotateright** [comment]
Patch posted for review:
https://reviews.llvm.org/D137791

**Comment by JonPsson** [comment]
> If we stop after isel, the store of 0 (`t57` in the original description) isn't before the 64-bit store (`t60`) though, right?
> 
> This is what I see if I compile the source to SystemZ asm using the scheduler options from the original description :
> 
> ```
> 	srlg	%r0, %r2, 32
> 	st	%r0, 0(%r1)
> 	lhi	%r0, 0
> 	stg	%r2, 0(%r1)  <-- 64-bit store
> 	sthrl	%r0, e  <-- store of 0
> 	strl	%r2, d
> ```
> 
> Is my understanding of the asm correct?

Sorry for the delay... Yes, you are right about those instructions, but I wonder if you are looking at 'h:'? The problem is in main where h() was inlined:

```
        lhi     %r1, 0
        sthrl   %r1, e
        stg     %r0, 0(%r2)
```
For some reason this seems to happen only in main(), but of course the important thing is that we identified the corrupt chaining produced by DAGCombiner...

**Comment by rotateright** [comment]
> Sorry for the delay... Yes, you are right about those instructions, but I wonder if you are looking at 'h:'? The problem is in main where h() was inlined:

Aha! Yes, I assumed the buggy code was in `h`, and `main` was just there to expose it. :)
I'll try to update/reduce the test file that I committed with 244ac4f, but I may not get to it until Monday.

**Comment by JonPsson** [comment]
Thanks for the fix!
