### ISSUE TITLE
reg2mem should ignore EH instructions

### ISSUE THREAD

**Issue by Naville** [llvm/llvm-project#58890]
[Godbolt](https://llvm.godbolt.org/z/d7czEe3dY)

My attempted fix was to add CatchSwitchInst ignoring logic in reg2mem's ``valueEscapes``, which worked for me in this case, but not sure if there are other cases missing

**Comment by Naville** [comment]
Submitted as [D137700](https://reviews.llvm.org/D137700)

**Comment by EugeneZelenko** [comment]
@Naville: Looks like https://reviews.llvm.org/D137700 is still in review stage.

**Comment by Naville** [comment]
@EugeneZelenko  Thanks, I thought you close the issue once a patch is in review process

**Comment by Naville** [comment]
Accepted, closing this issue
