### ISSUE TITLE
no file inttypes.h for building lld

### ISSUE THREAD

**Issue by d-vetrenyy** [llvm/llvm-project#58898]
fatal error C1083: Не удается открыть файл включение: inttypes.h: No such file or directory,
ninja: build stopped: subcommand failed.

-- Windows 10
-- x64
-- -G "Ninja"

**Comment by AaronBallman** [comment]
inttypes.h started being supported in Visual Studio 2013; it's definitely there in the 2019 and 2022 versions that I've got access to.

Our current build requirements (https://llvm.org/docs/GettingStarted.html#host-c-toolchain-both-compiler-and-standard-library) require MSVC 2019 16.7 or later which I verified does have inttypes.h, so I'm closing this as not reproducible. However, if you're using a supported MSVC that doesn't have inttypes.h, please reopen the issue with more details.
