### ISSUE TITLE
[InstCombine] GEP-swap optimization should bitcast typed pointers

### ISSUE THREAD

**Issue by clin111** [llvm/llvm-project#58901]
After 6c767cef, the attached test case (using typed pointers) will assert on the types of the swapped GEPs. If typed pointers are not supposed to work any more, please let me know, we can make some workarounds in our local branch.
[reduced.txt](https://github.com/llvm/llvm-project/files/9974101/reduced.txt)

**Comment by nikic** [comment]
At this time we do still accept fixes for typed pointers (but without test coverage), so feel free to submit a patch.

**Comment by huangjd** [comment]
Here is a fix in https://reviews.llvm.org/D137752. Since we are moving to opaque pointers, I just add a stricter check to typed pointers so that it will not perform such swap if the swapped types are incompatible, instead of adding several bitcasts.
