### ISSUE TITLE
Concept expansion segfault

### ISSUE THREAD

**Issue by mwalcott3** [llvm/llvm-project#58919]
clang 15.0.0 crashes with a segfault when compiling the following code:

 ```c++
template <class U, class T>
concept always_true = true;

template <class T>
struct foo {
    T value;
};

template <class... T>
struct bar : foo<T>... {
    template <always_true<T>... U>
    auto func(U&&... values) {
    }
};


int main() {
    using T = bar<bar<float, int>, bar<float, char>, bar<float, double>>;
    T{};
}
```

[crash_backtrace.txt](https://github.com/llvm/llvm-project/files/9983944/crash_backtrace.txt)
[godbolt](https://godbolt.org/z/1rE4bME4q)

**Comment by junaire** [comment]
Looks like it has been fixed in main (https://godbolt.org/z/1bczddMbc)
