### ISSUE TITLE
ICE in clang while compiling

### ISSUE THREAD

**Issue by charles-lunarg** [llvm/llvm-project#58925]
[test_util-903373.zip](https://github.com/llvm/llvm-project/files/9985411/test_util-903373.zip)

Was doing development, saw clang crash on me. Not sure what the issue is nor could I figure out how to 'reduce it' (will work on that later).

**Comment by EugeneZelenko** [comment]
@charles-lunarg: Could you please provide version information, command-line arguments and call stack?

**Comment by charles-lunarg** [comment]
Clang 14, Ubuntu 22.10 LTS
Command line args are gonna be whatever ninja used, and call stack is hard to get to since it occurred when I compiled a typo, and have since moved on...

I want to try to reproduce this tomorrow as well as get creduce to do something useful.

**Comment by EugeneZelenko** [comment]
Could you please try 15 or `main` branch?

**Comment by charles-lunarg** [comment]
I can do that tomorrow. Would be nice to find its already been fixed.

**Comment by AaronBallman** [comment]
Closing as not reproducible, but if you are able to reproduce with trunk or Clang 15, please reopen the issue with additional details.
