### ISSUE TITLE
[clang-tidy] Disable readability-identifier-naming.HungarianNotation.PrimitiveType

### ISSUE THREAD

**Issue by GlebchanskyGit** [llvm/llvm-project#58938]
I want to leave only `readability-identifier-naming.HungarianNotation.DerivedType.Pointer`, how can I disable Hungarian notation for primitive types or at least explicitly give them all an empty prefix? In my opinion, it's very oddly done that if I just want to add a prefix `p` to all pointers (whether it's a class field or any other pointer), then I'll also have to face those prefixes for all the primitive types I don't need.

For example, I just want `int* m_somePointerField` to be renamed `m_pSomePointerField`, but not `m_piSomePointerField`.
`- { key: readability-identifier-naming.HungarianNotation.PrimitiveType.int, value: "" }` doesn't work.

**Comment by GlebchanskyGit** [comment]
Sorry for duplicate, my wrong

**Comment by ChillerDragon** [comment]
Duplicate of which issue?
