### ISSUE TITLE
Description of confusable-identifiers.rst refers to wrong Unicode code point

### ISSUE THREAD

**Issue by rillig** [llvm/llvm-project#58934]
The documentation says:
> int 𝐟o; // Initial character is U+1234 (SUPER COOL AWESOME UPPERCASE NOT LATIN F) not U+0066 (LATIN SMALL LETTER F).

The shown code point is [U+1D41F](https://unicode.org/charts/PDF/U1D400.pdf), not [U+1234](https://unicode.org/charts/PDF/U1200.pdf).
The correct name of U+1D41F is "MATHEMATICAL BOLD SMALL F".

**Comment by rferrandop** [comment]
Hi, I will take a look into this.
