### ISSUE TITLE
[15, LTO] gnu::warning attribute not useful w/ LTO

### ISSUE THREAD

**Issue by psiha** [llvm/llvm-project#58933]
With LTO gnu::warning reports on the 'unwanted function' being used only at link time (expectedly) but it then reports only the mangled symbol name (and no source and call site information etc).

e.g.:
lld-link : warning : call to ??0?$Something@M@Namespace@NN@MB@@QEAA@AEBV0123@@Z marked "dontcall-warn": Warning message

**Comment by dwblaikie** [comment]
did you compile with debug info? (that might give you file/line) - but yeah, we should probably demangle that too, if it's mangled - might be more legible.

**Comment by psiha** [comment]
Yes, compiled with debug info (debugging works on the binary) yet no demangling or source info for gnu::warning.

**Comment by ChoKyuWon** [comment]
Proposed patch submitted for code review: https://reviews.llvm.org/D142844
