### ISSUE TITLE
[clang-doc][yaml] Yaml Output does not include Info.InfoType for root objects

### ISSUE THREAD

**Issue by mnesarco** [llvm/llvm-project#58943]
Hi Friends,
I am trying to use clang-doc's yaml output to feed a documentation database.
clang-doc dumps each Info into a yaml file, but it does not output InfoType field, so it is impossible to identify the type of Info when parsing the output files.

Reference:

https://github.com/llvm/llvm-project/blob/57416d872ae0fd3b8ee1808fed5c6b2ad4925bd8/clang-tools-extra/clang-doc/YAMLGenerator.cpp#L301

Pseudocode to fix this:

`clang-doc/YAMLGenerator.cpp`:
```cpp
llvm::Error YAMLGenerator::generateDocForInfo(Info *I, llvm::raw_ostream &OS,
                                              const ClangDocContext &CDCtx) {
  llvm::yaml::Output InfoYAML(OS);

  // InfoYAML << "Type: " << I->IT;  <------ (I know this is not how it is done, but it illustrates what is required)
  
  switch (I->IT) {
  case InfoType::IT_namespace:
    InfoYAML << *static_cast<clang::doc::NamespaceInfo *>(I);
    break;
  case InfoType::IT_record:
    InfoYAML << *static_cast<clang::doc::RecordInfo *>(I);
    break;
  case InfoType::IT_enum:
    InfoYAML << *static_cast<clang::doc::EnumInfo *>(I);
    break;
  case InfoType::IT_function:
    InfoYAML << *static_cast<clang::doc::FunctionInfo *>(I);
    break;
  case InfoType::IT_typedef:
    InfoYAML << *static_cast<clang::doc::TypedefInfo *>(I);
    break;
  case InfoType::IT_default:
    return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                   "unexpected InfoType");
  }
  return llvm::Error::success();
}
```

**Comment by mnesarco** [comment]
In the mean time, an indirect way to identify the file type is that if there is a `TagType` field, it is a Record, otherwise it is a namespace. Looks a bit fragile, explicit would be better than implicit info.

**Comment by EugeneZelenko** [comment]
@mnesarco: Could you please elaborate?

**Comment by mnesarco** [comment]
This issue is not relevant anymore.
