### ISSUE TITLE
[clang-format][Feature Request] Styling option to automatically add `C++14` `1'000'000` integer literal single quote separators

### ISSUE THREAD

**Issue by Eshnek** [llvm/llvm-project#58949]
I find these quite nice, and it would be amazing if `clang-format` could enforce them automatically.

```cpp
0b1001'1001
100'000'000'000'000'000
```
vs
```cpp
0b10011001
100000000000000000
```

Ideally you could configure the separator rules per literal format, though quite complex.

**Comment by dwblaikie** [comment]
my understanding is that clang-format usually only changes whitespace (with a few exceptions, like reordering includes) - so adding the separator characters would be outside that purview - though maybe the bar for non-whitespace changes isn't as high as I'm thinking - just a thought

**Comment by HazardyKnusperkeks** [comment]
> my understanding is that clang-format usually only changes whitespace (with a few exceptions, like reordering includes) - so adding the separator characters would be outside that purview - though maybe the bar for non-whitespace changes isn't as high as I'm thinking - just a thought

It isn't anymore. We have added a few options recently which modify not only whitespace: `InsertBraces`, `RemoveBracesLLVM`, `QualifierAlignment`, and `RemoveSemicolon`. So I think this request would be in the realm of the possible accepted patches. But if one of the regular developers would pick it up is a different question.

**Comment by dwblaikie** [comment]
> > my understanding is that clang-format usually only changes whitespace (with a few exceptions, like reordering includes) - so adding the separator characters would be outside that purview - though maybe the bar for non-whitespace changes isn't as high as I'm thinking - just a thought
> 
> It isn't anymore. We have added a few options recently which modify not only whitespace: `InsertBraces`, `RemoveBracesLLVM`, `QualifierAlignment`, and `RemoveSemicolon`. So I think this request would be in the realm of the possible accepted patches. But if one of the regular developers would pick it up is a different question.

ah, thanks for the context - good to know!

**Comment by owenca** [comment]
https://reviews.llvm.org/D140543
