### ISSUE TITLE
Clang++ 14.0.6 does not generate PDB file

### ISSUE THREAD

**Issue by Scr3amer** [llvm/llvm-project#58957]
Hello,

**My objective:**
Generate corresponding PDB file along my `.exe` with Clang++ 14.0.6 + lld + MinGW UCRT
I do **not** want to use clang-cl nor clang-cpp

**My attempt:**
```shell
clang++ -march=native -O3 -g -gcodeview main.cpp -o app.exe
```

**My problem**
No PDB file is generated.

From my understanding Clang supports generating PDB from both frontends, the GCC-like and MSVC-like ones.
LLD seems to support that too.
I even found the gcodeview in the `--help` of clang++.
But nothing happens when I do it.

What am I missing?

**Comment by EugeneZelenko** [comment]
Could you please try 15 or `main` branch?

**Comment by Scr3amer** [comment]
I tried today on LLVM15, same issue.
Where is the doc of LLD ? With absolutely all the possible flags ?
I checked https://lld.llvm.org/ and https://lld.llvm.org/windows_support.html but there is nothing at all in them.

**Comment by Scr3amer** [comment]
Thank you ! I also stumbled upon that info from mstorsjo but I kept the ticket open so that people can tell me where that information came from, the actual primary source.

How do we get the list of all possible values for that -m flag ?

**Comment by alvinhochun** [comment]
> How do we get the list of all possible values for that -m flag ?

https://github.com/llvm/llvm-project/blob/cb3f8d53e6c35e6538ccbb54fdd848de2b3d0d1e/lld/MinGW/Driver.cpp#L368-L380

**Comment by Scr3amer** [comment]
I was scared that was the answer xD.
Come on guys, where is the nice PDF / HTML doc :)) ?

Thank you @alvinhochun for your precious help !
