### ISSUE TITLE
[clang] `__builtin_FUNCSIG()` intrinsic.

### ISSUE THREAD

**Issue by fsb4000** [llvm/llvm-project#58951]
Microsoft C++ supports `__builtin_FUNCSIG()` since the latest preview ( VS 2022 17.5 Preview 1).
It is similar to `__builtin_FUNCTION()` but returns the same string as `__FUNCSIG__`.
It would be great if `clang-cl` supports the intrinsic too.

**Comment by JMazurkiewicz** [comment]
I've opened https://reviews.llvm.org/D150183.
