### ISSUE TITLE
[clang, trunk, c++20] Constrained functions with differing reference qualifiers cannot be "overloaded"

### ISSUE THREAD

**Issue by CalebAdrianXYZ** [llvm/llvm-project#58962]
Given the following class definition:

```cpp
template<unsigned R>
struct type
{
    void func() requires (R == 0);
    void func() & requires (R == 1);
    void func() && requires (R == 2);
};
```

I would expect the following test code to pass:
```cpp
#include <utility>

template<typename T>
concept test = requires { std::declval<T>().func(); };

static_assert(test<type<0>&>);
static_assert(test<type<0>&&>);
static_assert(test<type<1>&>);
static_assert(not test<type<1>&&>);
static_assert(not test<type<2>&>);
static_assert(test<type<2>&&>);
```

Both the class definition, and the test code successfully compiles on GCC, MSVC, and NVC++, however Clang++ rejects the class definition with the following errors:

```console
<source>:7:10: error: cannot overload a member function with ref-qualifier '&' with a member function without a ref-qualifier
    void func() & requires (R == 1);
         ^
<source>:6:10: note: previous declaration is here
    void func() requires (R == 0);
         ^
<source>:8:10: error: cannot overload a member function with ref-qualifier '&&' with a member function without a ref-qualifier
    void func() && requires (R == 2);
         ^
<source>:6:10: note: previous declaration is here
    void func() requires (R == 0);
```

Given that these functions have disjoint constraints, they should not conflict, and clang should accept this code as provided.

Corresponding CE link: https://godbolt.org/z/oE36nGMMo

**Comment by royjacobson** [comment]
I tried to understand where this is forbidden even without concepts and it seems that the wording from over.load was completely rewritten in 'declarations and where to find them'. Could find out where it moved to.. maybe it's just allowed now?

**Comment by CalebAdrianXYZ** [comment]
Without concepts I believe it should just be ambiguous, similar to how `foo(T);` and `foo(T const&);` would be.

Thankfully for my use case I think I can work around this by only providing the ref-qualified overloads and enabling both/one when desired.

**Comment by hubert-reinterpretcast** [comment]
This should be [basic.scope.scope] paragraphs 3 through 5. Because the trailing requires-clauses are different, they do not "correspond" and thus do not "potentially conflict".

**Comment by royjacobson** [comment]
proposed fix: https://reviews.llvm.org/D138749
