### ISSUE TITLE
OpenMP found but omp.h missing error in Pixman

### ISSUE THREAD

**Issue by ms178** [llvm/llvm-project#58966]
As first reported in https://github.com/llvm/llvm-project/issues/58941#issuecomment-1312080062, Pixman errors out with LLVM-git main due to missing `omp.h` since the OpenMP changes on that day (as it did work okay with a build from a day before that):

```console
WARNING: OpenMP found but omp.h missing.
Run-time dependency OpenMP found: NO (tried system)

pixman/meson.build:398:2: ERROR: Dependency "openmp" not found, tried system
```

[meson-log.txt](https://github.com/llvm/llvm-project/files/9998626/meson-log.txt)

This reproduces with 378778a0d10c2f8d5df8ceff81f95b6002984a4b. Also note, that a brand new 0.64 Meson is used on my system.

This is my LLVM-configuration: 
[PKGBUILD.txt](https://github.com/llvm/llvm-project/files/9998643/PKGBUILD.txt)

My custom llvm-toolchain can be found here: https://github.com/ms178/archpkgbuilds/tree/main/toolchain-experimental/llvm-git

**Comment by thesamesam** [comment]
Please try to bisect the issue.

**Comment by jhuber6** [comment]
I'm guessing it's caused by https://reviews.llvm.org/D125860. I'll look into it, but if you can revert that patch and let me know if the issue goes away I'd appreciate it.

**Comment by ms178** [comment]
@jhuber6 Thanks for finding and fixing the issue, I can confirm that all is fine again on latest LLVM-git. Also the other problem that i mentioned in the comment last week, a problem with my llvm-bolt-script, was fixed on Sunday.
