### ISSUE TITLE
[MLIR] Bug in `mlir::parseType` handling stringrefs

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#58964]
The signature for `mlir::parseType` takes a StringRef for the type to parse, which doesn't need to be null terminated.  It is implemented with this logic:

```cpp
template <typename T, typename ParserFn>
static T parseSymbol(StringRef inputStr, MLIRContext *context, size_t &numRead,
                     ParserFn &&parserFn) {
  SourceMgr sourceMgr;
  auto memBuffer = MemoryBuffer::getMemBuffer(
      inputStr, /*BufferName=*/"<mlir_parser_buffer>",
      /*RequiresNullTerminator=*/false);
 ```

Which forms a memory buffer around that and then goes and uses the MLIR parser to parse it.  The problem with this is that the MLIR asm parser does in fact require the memory buffer to be null terminated, which causes crashes.  I think the implementation of parseSymbol should use `getMemBufferCopy` when the input buffer isn't already nul terminated.

**Comment by rkayaith** [comment]
After f5f8a46bb0ce3dd2f3e024696d5a0aef5fb12a29 that call now uses `RequiresNullTerminator=true`: https://github.com/llvm/llvm-project/blob/f5f8a46bb0ce3dd2f3e024696d5a0aef5fb12a29/mlir/lib/AsmParser/DialectSymbolParser.cpp#L317
Which still crashes if you pass it a non-null terminated string, but at least there's an assert: https://github.com/llvm/llvm-project/blob/f5f8a46bb0ce3dd2f3e024696d5a0aef5fb12a29/llvm/lib/Support/MemoryBuffer.cpp#L49-L52

And `mlir::parseSourceString` has the same behaviour (the default is `RequiresNullTerminator=true`): https://github.com/llvm/llvm-project/blob/f5f8a46bb0ce3dd2f3e024696d5a0aef5fb12a29/mlir/lib/Parser/Parser.cpp#L90-L93

**Comment by rkayaith** [comment]
> I think the implementation of parseSymbol should use `getMemBufferCopy` when the input buffer isn't already nul terminated.

I don't think this can be detected automatically though, without potentially dereferencing uninitialized memory. Is there any advantage to `getMemBufferCopy` over having the caller copy to `std::string` if they have a (potentially) non-null-terminated string?

**Comment by lattner** [comment]
Yeah fair point, you can't access one off the last byte in general (could be at the end of a memory page).  I think this could unconditionally copy it though inside the API, given types and attributes aren't large?
