### ISSUE TITLE
[flang] Compilation error in cray pointer

### ISSUE THREAD

**Issue by ohno-fj** [llvm/llvm-project#58971]
```
Version of flang-new : 16.0.0(e0fb01e97b6b7d2fe66b17b36eeb98aa78c6e3bb)
```

cray pointer results in a compilation error.
GNU's Fortran compiler terminates normally with programs that use cray pointer when the option `-fcray-pointer` is used.

The following are the test program, flang-new compilation results, and gfortran compilation results.  

`snggn856_.f90`:
```f90
subroutine s(i,k)
 type x
   integer,pointer::p1(:),p2(:)
 end type
 type (x),pointer:: v(:)
 integer,target::t1(3)=(/1,2,3/)
 integer,target::t2(4)=(/4,5,6,7/)
integer j(2)
 pointer(n1,d1)
 pointer(n2,d2)
 allocate(v(k))
 select case(i)
  case (1)
   allocate(v(2)%p1(2))
   v(2)%p1=(/11,12/)
   v(2)%p2=>t1(1:3:2)
end select
n1=loc(v(2)%p1)
n2=loc(v(2)%p2)
j=jfoo(v(k)%p1,v(k)%p2,n1,n2,i)+jfoo(v(k)%p1,v(k)%p2,n1,n2,i)
if (j(1)/=i*2)write(6,*) "NG"
if (j(2)/=i*2+2)write(6,*) "NG"
deallocate(v)
contains
function jfoo(i1,i2,n1,n2,i)
integer i1(2),i2(2),jfoo(2)
 pointer(n1,d1)
 pointer(n2,d2)
select case(i)
 case (1)
   if (i1(1)/=11)write(6,*) "NG"
   if (i1(2)/=12)write(6,*) "NG"
   if (i2(1)/=1)write(6,*) "NG"
   if (i2(2)/=3)write(6,*) "NG"
   if (loc(i1)/=n1)write(1,*) i,'i1 copied'
   if (loc(i2)==n2)write(1,*) i,'i2 no copied'
end select
jfoo(1)=i
jfoo(2)=i+1
end function
end
call s(1,2)
print *,'snggn856 : pass'
end
```

```console
$ flang-new -flang-experimental-exec snggn856_.f90
error: Semantic errors in snggn856_.f90
./snggn856_.f90:27:13: error: 'd1' was already declared as a Cray pointee
   pointer(n1,d1)
              ^^
./snggn856_.f90:28:13: error: 'd2' was already declared as a Cray pointee
   pointer(n2,d2)
              ^^
$
```

GNU's Fortran compiler terminates normally with programs that use cray pointer when the option `-fcray-pointer` is used.  

```console
$ gfortran snggn856_.f90
snggn856_.f90:9:8:

  pointer(n1,d1)
        1
Error: Cray pointer declaration at (1) requires -fcray-pointer flag
snggn856_.f90:10:8:

  pointer(n2,d2)
        1
Error: Cray pointer declaration at (1) requires -fcray-pointer flag
snggn856_.f90:27:8:

  pointer(n1,d1)
        1
Error: Cray pointer declaration at (1) requires -fcray-pointer flag
snggn856_.f90:28:8:

  pointer(n2,d2)
        1
Error: Cray pointer declaration at (1) requires -fcray-pointer flag
$
```

```console
$ gfortran snggn856_.f90 -fcray-pointer
$ ./a.out
 snggn856 : pass
$
```

**Comment by ohno-fj** [comment]
Cray pointer is an extension, so I will close this issue.

**Comment by kkwli** [comment]
I will take a look of this.

**Comment by PeixinQiao** [comment]
@kkwli Please check if LLVM Flang plan to support cray pointer in upstream with @sscalpone (or others) before your proceed. Maybe slack is the right place to discuss this.

**Comment by sscalpone** [comment]
Cray based POINTER(p,x) and LOC() intrinsic (with %LOC() as an alias) are both listed in the Extensions, deletions, and legacy features supported by default section of https://github.com/llvm/llvm-project/blob/fe93da22aa7bd57e277571cd692c7c0cc51c0478/flang/docs/Extensions.md.

Thanks!

**Comment by PeixinQiao** [comment]
> Cray based POINTER(p,x) and LOC() intrinsic (with %LOC() as an alias) are both listed in the Extensions, deletions, and legacy features supported by default section of https://github.com/llvm/llvm-project/blob/fe93da22aa7bd57e277571cd692c7c0cc51c0478/flang/docs/Extensions.md.
> 
> Thanks!

@sscalpone Thanks for the confirmation. @kkwli Sorry to disturb you. Please feel free to work on this.

**Comment by klausler** [comment]
https://reviews.llvm.org/D153385

**Comment by klausler** [comment]
Fix merged.
