### ISSUE TITLE
[JITLink][RISCV] JIT session error: Unsupported riscv relocation:28: R_RISCV_LO12_S

### ISSUE THREAD

**Issue by dkurt** [llvm/llvm-project#58979]
I have an example which throws this error with ORC JIT on RISC-V with [Halide](https://github.com/halide/Halide/) project. What kind of dump/minimal working example can I provide? Or, maybe, does it make sense to make a patch for https://github.com/llvm/llvm-project/blob/main/llvm/lib/ExecutionEngine/JITLink/ELF_riscv.cpp by myself?

**Comment by dkurt** [comment]
Problem solved by adding `CodeModel::Medium` to TargetMachine:
```
setCodeModel(llvm::CodeModel::Medium);
``

**Comment by lhames** [comment]
Doesn't hurt to leave this open -- we should get it implemented sooner or later.

CC'ing @luxufan and @hahnjo, since they've both worked on that backend.

**Comment by luxufan** [comment]
Candidate patch: https://reviews.llvm.org/D138030
