### ISSUE TITLE
[flang] Compilation error in volatile statement(VOLATILE dummy argument)

### ISSUE THREAD

**Issue by ohno-fj** [llvm/llvm-project#58973]
```
Version of flang-new : 16.0.0(e0fb01e97b6b7d2fe66b17b36eeb98aa78c6e3bb)
```

Actual argument associated with `VOLATILE` dummy argument results in a compilation error.  
GNU's Fortran compiler is OK.  

The following are the test program, flang-new compilation results, and gfortran compilation results.  

`snem0601_012_.f90`
```f90
  module mod
    contains
    subroutine sub(m6,error)
    integer,intent(inout) :: error

!    integer       :: m6
    integer,volatile :: m6

    if (any ((/m6/).ne.(/6/))) &
   & then
       error = 1
    end if
    end subroutine
  end module

  program fe1nvol12

    use mod
    integer :: error = 0

    call sub(6,error)

    if (error .ne. 0) then
      print *,'NG: snem0601_012'
    end if

    print *,'pass: snem0601_012'

  end program fe1nvol12
```

```console
$ flang-new -flang-experimental-exec snem0601_012_.f90
error: Semantic errors in snem0601_012_.f90
./snem0601_012_.f90:21:14: error: Actual argument associated with VOLATILE dummy argument 'm6=' must be definable
      call sub(6,error)
               ^
./snem0601_012_.f90:21:14: '6_4' is not a variable
      call sub(6,error)
               ^
$
```

```console
$ gfortran snem0601_012_.f90
$ ./a.out
 pass: snem0601_012
$
```

**Comment by klausler** [comment]
This diagnostic message should be a warning, not a fatal error.

**Comment by cabreraam** [comment]
Hi @ohno-fj,

Are you able to reproduce this with the current version of the repository? (At the time of this post, it was commit hash `6a70b846a44189481656f0cb5201add396a1ed41`).

**Comment by ohno-fj** [comment]
Thanks @cabreraam for your comment

In the current version, I have seen the following error message:
```
  not yet implemented: VOLATILE in procedure interface
```

**Comment by cabreraam** [comment]
My fix is nearing completion. Just need to write the test case. @ohno-fj, do you have any objection to the source code you provided being used as part of the [Semantic tests](https://github.com/llvm/llvm-project/tree/main/flang/test/Semantics)?

**Comment by cabreraam** [comment]
Fixed in [this commit](https://github.com/llvm/llvm-project/commit/9c87746de7cdbb2b60a3fc274831aee43ddd9b7c).

Closing issue now!
