### ISSUE TITLE
[JITLink][i386] JIT session error: Unsupported i386 relocation:4

### ISSUE THREAD

**Issue by dkurt** [llvm/llvm-project#58978]
During migration from MCJIT to ORC JIT facing "`JIT session error: Unsupported i386 relocation:4`" on `i386` target. As far as I can see, a patch https://github.com/llvm/llvm-project/commit/2a3b257a935aa49886ccd073695e75b385b3822f which introduced support of other relocations was merged just few weeks ago. Does it mean that it make sense to use MCJIT for i386 at this moment or there is a workaround?

/cc @jain98

**Comment by dkurt** [comment]
As a workaround added a switch from `ObjectLinkingLayer` to `RTDyldObjectLinkingLayer` for `i386` target.

**Comment by jain98** [comment]
@dkurt the i386 backend for ORC JITLink APIs is still a work in progress and support exists for only a small subset of the possible relocations. 

I cannot comment on the validity of your workaround, however. While it works for you, I'm wondering if there is a "proper" way to do what you intend to do. Perhaps @lhames and/or @sunho can comment.

You could also ask your question in the #jit channel on the LLVM server and get a much faster response there.

**Comment by dkurt** [comment]
Thanks, @jain98, @weliveindetail! Will keep on touch. For now `RTDyldObjectLinkingLayer` is fine for my solution, at least in terms of correctness.

**Comment by sunho** [comment]
It is okay to rely on RuntimeDyld if you don't have to use the latest features of ORC. And for this case, JITLink is not a viable option yet. Hoepfully, @jain98 will complete the backend soon though.

**Comment by lhames** [comment]
Looks like @jkshtj added support for i386 relocation 4 (`R_386_PLT32`) and a number of other relocations in cd9fd4255b48e.

I'm going to close this as complete. @dkurt -- If you get a chance to try JITLink again and hit another issue with this relocation please feel free to reopen this. If you hit an error with other i386 relocations please file a new issue.

**Comment by dkurt** [comment]
@lhames, @jkshtj , many thanks! Sure, I will try.
