### ISSUE TITLE
Pointer and allocatable assignment problem

### ISSUE THREAD

**Issue by PeixinQiao** [llvm/llvm-project#58983]
```f90
  integer, parameter :: n = 5
  integer :: x(n), y(n) = [1,2,3,4,5]
  integer, pointer :: w(:)
  integer, allocatable :: z(:)
  allocate(w(n))
  allocate(z(n))
  call test(x, y, w, z, n)
contains
  subroutine test(x, y, w, z, n)
    integer :: x(n), y(n)
    integer, pointer :: w(:)
    integer, allocatable :: z(:)
    x = y(1:4)
    w = y(1:4)
    z = y(1:4)
    print *, size(x), x
    print *, size(w), w
    print *, size(z), z
  end
end
```
```console
$ cat run.sh 
#!/bin/bash

echo "---------- gfortran ----------"
gfortran $1 $2 && ./a.out

echo && echo "---------- ifort ----------"
ifort $1 $2 && ./a.out

echo && echo "---------- flang-new ----------"
flang-new -flang-experimental-exec $1 $2 && ./a.out
```
```console
$ bash run.sh test.f90 
---------- gfortran ----------
           5           1           2           3           4           0
           5           1           2           3           4           0
           4           1           2           3           4

---------- ifort ----------
           5           1           2           3           4           0
           5           1           2           3           4           0
           4           1           2           3           4

---------- flang-new ----------
 5 1 2 3 4 5
 5 1 2 3 4 5
 4 1 2 3 4
```

This code will have one execution error when runtime check is enabled.
```console
$ gfortran test.f90 -fcheck=bounds && ./a.out
At line 13 of file test.f90
Fortran runtime error: Array bound mismatch for dimension 1 of array 'x' (5/4)
```
If the array is large, which is common in real HPC applications, LLVM Flang would not be efficient as gfortran and ifort. For example, assign one array of 50,000 elements to an array of 100,000 elements.

**Comment by klausler** [comment]
The program is assigning 4-element array values to the 5-element explicit-shape dummy array `x` and to the 5-element array pointer `w`.  Both of these assignment are errors.

The assignment of a 4-element array to the 5-element allocatable array `z` causes reallocation at execution time and is not an error.

**Comment by PeixinQiao** [comment]
> The program is assigning 4-element array values to the 5-element explicit-shape dummy array x and to the 5-element array pointer w. Both of these assignment are errors.

Yes, I knew they are standard non-conforming. I report this since it is impossible to guarantee that users always write the correct code. If this kind of standard non-conforming code is not the LLVM Flang's target, it is OK to close this issue. It is reasonable to ignore this if the real applications do not have this problem. Maybe we can get back to this if we capture this case in reall applications.
