### ISSUE TITLE
[DirectX backend] support DIAssignID

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#58989]
llvm3.7 used by DXIL doesn't support DIAssignID.
We'll need to translate it into debug info which llvm3.7 can understand if DIAssignedID is generated from clang by default.

RFC for DIAssignID is at
https://discourse.llvm.org/t/rfc-assignment-tracking-a-better-way-of-specifying-variable-locations-in-ir/62367

**Comment by davidcook-msft** [comment]
Closing as too narrow and will be addressed when the Debug Information work stream kicks off.
