### ISSUE TITLE
clang format is confused by function-try-block + complex initializers

### ISSUE THREAD

**Issue by dvirtz** [llvm/llvm-project#58987]
Input:
```cpp
namespace good {
struct S {
    S() : i{[]() { return 42; }()} 
    {}
    int i;
};
}

namespace bad {
struct S {
    S() try 
        : i{[]() { return 42; }()} 
    {} 
    catch(...) {throw;}
    int i;
};
}
```

output:
```cpp
namespace good {
struct S {
  S() : i{[]() { return 42; }()} {}
  int i;
};
} // namespace good

namespace bad {
struct S {
  S() try : i{[](){return 42;}
    ()
} {
}
catch (...) {
  throw;
}
int i;
}; // namespace bad
}
```

End of namespace comment is being put at the wrong place and initializer formatting is strange.

https://godbolt.org/z/91hYr5aoj

**Comment by rymiel** [comment]
FWIW, function-try-blocks in general are poorly supported in clang-format (#58183, #20989), probably because of how obscure of a language feature it is

**Comment by dvirtz** [comment]
How else can you catch exceptions from member initializers?

**Comment by rymiel** [comment]
I'm not saying it's an unnecessary language feature (because you can't any other way), it's an obscure one
