### ISSUE TITLE
[SVE] Missing combine optimaztion related to incw

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#58995]
* case: https://gcc.godbolt.org/z/MMeEv8jWW
```cpp
void testWhileWR(int *data1, int *data2, int size) {
  for (int i = 0; i < size; i++) {
    data2[i] = data1[i];
  }
}
```

* As the IR node `%6` will be hoist out the `vector.body` in pass LCSSAPass, then it place in different BB with the node `%index.next`, so it can't be folded in combine.
```ll
vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %active.lane.mask = phi <vscale x 4 x i1> [ %active.lane.mask.entry, %vector.ph ], [ %active.lane.mask.next, %vector.body ]
  %3 = getelementptr inbounds i32, ptr %data1, i64 %index
  %wide.masked.load = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr %3, i32 4, <vscale x 4 x i1> %active.lane.mask, <vscale x 4 x i32> poison), !tbaa !6
  %4 = getelementptr inbounds i32, ptr %data2, i64 %index
  call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> %wide.masked.load, ptr %4, i32 4, <vscale x 4 x i1> %active.lane.mask), !tbaa !6
  %5 = call i64 @llvm.vscale.i64()
  %6 = shl nuw nsw i64 %5, 2
  %index.next = add i64 %index, %6
  %active.lane.mask.next = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 %index.next, i64 %wide.trip.count)
  %7 = extractelement <vscale x 4 x i1> %active.lane.mask.next, i64 0
  br i1 %7, label %vector.body, label %for.cond.cleanup.loopexit12, !llvm.loop !10
```

**Comment by vfdff** [comment]
may be similar to https://discourse.llvm.org/t/arm-sve-zi-instructions-would-not-be-selected-in-loop-bodies-sveallactive-cannot-see-through-bb-boundaries/65113, part insturctions moved out of the loop body, then missing combine as values across basic blocks.

**Comment by vfdff** [comment]
it crashes when I try with **-global-isel** （but ok with -global-isel-abort=0）
* clang -march=armv9-a+sve2 -O3 -w ../test.c -S -mllvm -print-after-all -O2 -march=armv9-a+sve2 -mllvm -prefer-predicate-over-epilogue=predicate-else-scalar-epilogue -Xclang -target-feature -Xclang +use-scalar-inc-vl -mllvm -global-isel

**Comment by PeixinQiao** [comment]
> it crashes when I try with **-global-isel** （but ok with -global-isel-abort=0）
> 
> * clang -march=armv9-a+sve2 -O3 -w ../test.c -S -mllvm -print-after-all -O2 -march=armv9-a+sve2 -mllvm -prefer-predicate-over-epilogue=predicate-else-scalar-epilogue -Xclang -target-feature -Xclang +use-scalar-inc-vl -mllvm -global-isel

GlobalSel does not support ScalableVectorType, yet. Check https://github.com/llvm/llvm-project/blob/19c42f672f942518b4d711a0c734693a9244f78c/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp#L23123-L23125. The original PR is https://reviews.llvm.org/D81557.

**Comment by vfdff** [comment]
maybe fixed by https://github.com/llvm/llvm-project/pull/70304

**Comment by vfdff** [comment]
close this issue as the https://github.com/llvm/llvm-project/pull/70304 fixed this issue indeed with local check
- clang -march=armv8.3-a+**sve2** -mllvm -prefer-predicate-over-epilogue=predicate-else-scalar-epilogue  -O3 test.c -S
