### ISSUE TITLE
How to dump crash trace

### ISSUE THREAD

**Issue by Colloportus0** [llvm/llvm-project#59004]
I am a beginner to llvm-project and I have questions about debugging. When developing, I found a crash that beyond the code I write, and it tells liitle about the error message like only: 

```
Assertion failed: (Index < this->size() && "Invalid index!"), function operator[], file ArrayRef.h, line 442.
```

I hope there is an option to provide more infomation about the error I triggered, for example, the crash trace.

**Comment by EugeneZelenko** [comment]
Please use https://discourse.llvm.org for questions.
