### ISSUE TITLE
regression on main with packed pod types (POD type detection fails, sizeof packed types is bigger)

### ISSUE THREAD

**Issue by adrianimboden** [llvm/llvm-project#59000]
https://godbolt.org/z/xnPc7bxMY

```cpp
#include <type_traits>
#include <cstdint>

class Foo {
public:
    constexpr explicit Foo(int64_t v) : value_{v} {
        
    }

    int get_value(){
        return value_;
    }
    
    constexpr explicit Foo() = default;


private:
    int64_t value_;
};


static_assert(std::is_trivial<Foo>::value);
static_assert(std::is_standard_layout<Foo>::value);
static_assert(std::is_pod<Foo>::value);

struct __attribute__((packed)) Bar {
    uint8_t a;
    Foo member;
};
static_assert(sizeof(Bar) == 9);

Bar b{.a=1, .member=Foo{4}};
```

I did not do a bisect, but on Clang 15, it behaves correctly.
- Type traits say `Foo` is a POD type (I think that is correct)
- The warning says that `Foo` is not a POD type
- Packing does not pack because compiler actually thinks it is not a POD type (`sizeof` is bigger)

**Comment by adrianimboden** [comment]
Ok i did a bisect and 277123376ce08c98b07c154bf83e4092a5d4d3c6 did this ABI break.

According to the comment, this is indended.
I don't really care about the ABI break per se.

But when the text is correct (`GCC doesn't pack non-POD members...`), there is still something wrong going on here. `Foo` is a POD type according to the static_asserts, but it is not treated like a POD type. The check ist here: https://github.com/llvm/llvm-project/blob/main/clang/lib/AST/RecordLayoutBuilder.cpp#L1973

It now matches the gcc implementation: https://godbolt.org/z/bzq784Mzz

One of these is wrong:
- The packing implementation
- The type_trait is wrong
- The warning text
All three cases would mean, that gcc is equally at fault (behavior and warnings are the same)

@dwblaikie, do you have an idea what is going on here?

**Comment by dwblaikie** [comment]
The relevant POD here isn't the language-level POD like a type trait, but "POD for the purposes of layout" as defined by the Itanium ABI spec here: https://itanium-cxx-abi.github.io/cxx-abi/abi.html#POD

So it's expected that this POD is different from the language-accessible type trait POD for historical reasons.

**Comment by adrianimboden** [comment]
Alright, make sense :)

But what I don't understand is, why does having an additional constructor or making a member private make the class a non-pod as seen by the itanium spec?
The Itanium ABI link does not state anything related to the visibility or existence of constructors as far as I have seen. I don't see why that should be relevant.

What is it that I oversee here?

**Comment by dwblaikie** [comment]
> But what I don't understand is, why does having an additional constructor or making a member private make the class a non-pod as seen by the itanium spec?
> The Itanium ABI link does not state anything related to the visibility or existence of constructors as far as I have seen. I don't see why that should be relevant.

The Itanium spec says "In general, a type is considered a POD for the purposes of layout if it is a POD type (in the sense of ISO C++ [basic.types])" plus some extra itanium-specific bits. And also says:

> There have been multiple published revisions to the ISO C++ standard, and each one has included a different definition of POD. To ensure interoperation of code compiled according to different revisions of the standard, it is necessary to settle on a single definition for a platform. A platform vendor may choose to follow a different revision of the standard, but by default, the definition of POD under this ABI is the definition from the 2003 revision (TC1).
> 
> Being tied to the TC1 definition of POD does not prevent compilers from being fully compliant with later revisions. This ABI uses the definition of POD only to decide whether to allocate objects in the tail-padding of a base-class subobject. While the standards have broadened the definition of POD over time, they have also forbidden the programmer from directly reading or writing the underlying bytes of a base-class subobject with, say, memcpy. Therefore, even in the most conservative interpretation, implementations may freely allocate objects in the tail padding of any class which would not have been POD in C++98. This ABI is in compliance with that.

So, looking at the old (98) definition of POD in cppreference: https://en.cppreference.com/w/cpp/language/classes#POD_class it says:

> A POD class is a class that...
> * is an aggregate... [until C++11]

And then following that to the definition of aggregate ( https://en.cppreference.com/w/cpp/language/aggregate_initialization ):

> An aggregate is one of the following types:
> * a class type that has:
>   *no user-declared constructors [until C++11]

Does that cover it?

**Comment by adrianimboden** [comment]
that is the reason why I test this with property `std::is_pod`. C++/stdlib says its POD, but packing says its not.

I can live with adding packed to the members, I am just confused.

**Comment by dwblaikie** [comment]
Right - the type trait doesn't implement the definition of POD that the Itanium ABI depends on - the ABI depends on the 98 definition of POD, but the type trait implements the C++11 definition of POD, which is different in ways that matter here - if you read through the cppreference links at the 11 definition, you should see the difference.

**Comment by adrianimboden** [comment]
Alright, starts to make sense now.

Would it be reasonable to change the warning text or shall we leave everything as-is?

**Comment by dwblaikie** [comment]
I'd be open to a patch to change the wording of the diagnostic? Got any particular suggestions for wording you think would suit?

**Comment by adrianimboden** [comment]
I thought about something like `not packing field 'member' as it is non-POD in this context [-Werror,-Wpacked-non-pod]`
or maybe `not packing field 'member' as it is non-POD for the purposes of layout [-Werror,-Wpacked-non-pod]`

but now, after I know the facts, I may be not the best judge of that anymore.

**Comment by adrianimboden** [comment]
you mean by 9df8ba631d4612eb8f930c9fe7c6cf39e5deb3af (only for future reference).

Thank you very much for your effort. It is greatly appreciated.

**Comment by dwblaikie** [comment]
> you mean by [9df8ba6](https://github.com/llvm/llvm-project/commit/9df8ba631d4612eb8f930c9fe7c6cf39e5deb3af) (only for future reference).
> 
> Thank you very much for your effort. It is greatly appreciated.

Ah, right, thanks for the catch!

**Comment by stsp** [comment]
Hi guys, so what is the proper work-around
for this? It seems like marking the non-pod
member as packed itself, will allow it unaligned
in a container structure. But that looks a bit
odd to me, as the intention here is to tell the
container structure to pack its members, rather
than telling some non-POD member to became
somehow "packed". That non-POD member
is already packed in a sense that it has no gaps
within (having just 1 field, for example), so
applying the packing to it sounds weird?

**Comment by stsp** [comment]
Hi guys, I can't get my code parted to
clang-16 because of this. :(
Basically I have 3 problems.

Problem 1:

As I stated earlier, these non-POD
members have no gaps, so packing
them looks senseless, and in fact, even
clang itself thinks that way:

/home/stas/src/fdpp/fdpp/farobj.hpp:29:7: warning: packed attribute is unnecessary for 'NearPtr_DO<exec_blk>' [-Wpacked]

So I am getting dozens of a -Wpacked
warnings now, but the resulting code
works, so at least I could work around
that by removing -Wpacked. Even though
I think its very bad that clang now contradicts
itself and suggests to remove the packing,
after which the code breaks completely.

Problem 2:

The resulting code gives those -Wpacked
warnings also on older clangs, which were
working perfectly for years, so I am introducing
a regression to my code base. Of course
getting rid of -Wpacked would help also here...

Problem 3:

The resulting code is not portable to gcc
because it hits this:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=36566
gcc doesn't allow to bind the packed field
to a reference, while clang allows that w/o
any problems.

So the results of porting my code base to
clang-16 are:
1. Have to add unneeded packings to what
    was already packed.
2. Got a well-deserved -Wpacked warnings
    for doing so.
3. Got them even on systems with older clangs
4. Got the clang-specific code that can't be
    compiled by gcc.

What should I do?

**Comment by dwblaikie** [comment]
You could build with the old ABI: `-fclang-abi-compat=15.0` I think would be what would get you back to the old packing behavior.

Ultimately, this is all for GCC compatibility - Clang needs to be ABI compatible with GCC, and cases where it isn't are bugs that get fixed when we find them.

The only leftover part of this is the `-Wpacked` warning on a non-pod type, that you filed (thanks for that!) as #62353 and I've sent out a patch for.

I can't fix the warning on old clang - but if you are hitting this issue on older clangs, know that your code isn't ABI compatible with GCC, which may be a problem for you.

The packed attribute isn't unneeded, even if it wasn't needed in Clang 15 and before - that was a bug (ABI incompatibility with GCC), not a feature.

As for the code not being able to be compiled with GCC - once you add the packed attribute to the non-pod type per Clang's warnings, you're now getting the same layout in Clang and GCC, and GCC is rightly warning (well, error, which seems a bit aggressive, but that's their call) you about the subsequent issue. The code isn't "clang specific" - it's the same layout in Clang and GCC.

If you /don't/ want the non-pod member packed (this isn't the old behavior) you can ignore the `-Wpacked-non-pod` warning - it was added so you'd know that the layout of the struct was changing in your codebase (& maybe helps people who wanted to pack a non-pod).

Admittedly there's no way to silence that warning on a case-by-case basis if you don't want to pack the non-pod member - maybe we want some spelling for that, but probably just disable the warning in general.
