### ISSUE TITLE
`__is_aggregate` should accept arrays of incomplete types

### ISSUE THREAD

**Issue by frederick-vs-ja** [llvm/llvm-project#59002]
Current this code snippet doesn't compile with Clang ([Godbolt link](https://godbolt.org/z/9KEEMosj8)), because Clang's `__is_aggregate` rejects array of incomplete type:
```C++
#include <type_traits>
struct incomplet;
static_assert(std::is_aggregate_v<incomplet[]>);
```

This snippet is made well-formed and well-defined via [LWG issue 3823](https://cplusplus.github.io/LWG/issue3823). While a workaround using `std::disjunction_v` is implementable without compiler change, it may be more efficient to fix `__is_aggregate` instead.

**Comment by shafik** [comment]
CC @cjdb

**Comment by royjacobson** [comment]
It's not a hard fix - I think we just have to move `case UTT_IsAggregate` to the correct line in `CheckUnaryTypeTraitTypeCompleteness` - but maybe we should wait a bit until CWG publishes a new issues revision, it's annoying to update the DRs tests otherwise.

**Comment by royjacobson** [comment]
NVM, it's a LWG issue :confused: 
Not sure how we handle those :)
