### ISSUE TITLE
Incorrect codegen for int128 parameters with x64-systemv calling conv

### ISSUE THREAD

**Issue by T0b1-iOS** [llvm/llvm-project#59011]
## Description

When compiling C/C++ code that takes an __int128 as its sixth argument, llvm splits it into two 64bit ints that get passed in a register and on the stack. According to the SysV ABI __int128 should be treated like a struct of two 64bit ints and therefore be passed completely in memory in that case.

## Reproduction
[https://godbolt.org/z/o8MMMYdY6](https://godbolt.org/z/o8MMMYdY6)

Input C++:
```cpp
using uint128_t = unsigned __int128;

unsigned long long tmpfn(uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint128_t t) {
    return (t >> 64) & 0xFFFFFFFFFFFFFFFF;
}

unsigned long long tmpfn2(uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint128_t t) {
    return t & 0xFFFFFFFFFFFFFFFF;
}
```

Output from clang 15:
```assembly
tmpfn:
        mov     rax, qword ptr [rsp + 8]
        ret
tmpfn2:
        mov     rax, r9
        ret
```
        
Output from gcc 12:
```assembly
tmpfn:
        mov     rax, QWORD PTR [rsp+16]
        ret
tmpfn2:
        mov     rax, QWORD PTR [rsp+8]
        ret
```

**Comment by tgross35** [comment]
There is a WIP patch that should fix this: https://reviews.llvm.org/D86310

**Comment by nikic** [comment]
I don't think that patch will fix this issue. This is not an alignment problem.

**Comment by tgross35** [comment]
Not the current patch, but I think resolving this is part of the wanted fix

Also, this is related to https://github.com/llvm/llvm-project/issues/41784

**Comment by RalfJung** [comment]
Looks like https://reviews.llvm.org/D158169 is the patch to fix this?

**Comment by tgross35** [comment]
Unfortunately not yet - that fixes only the register passing component which means clang and GCC are now compatible, but the alignment produced by LLVM is still incorrect, so rust still isn't compatible. The fix for that is in https://reviews.llvm.org/D86310, which I think is just waiting for a review.

So not yet but close :)

**Comment by T0b1-iOS** [comment]
Seems that https://reviews.llvm.org/D86310 landed in October 2023, so this should be fixed now.
