### ISSUE TITLE
[X86KCFI] llvm_unreachable("Unexpected CFI call opcode") is reached

### ISSUE THREAD

**Issue by ebiggers** [llvm/llvm-project#59017]
When compiling a file with `-O2 -fsanitize=kcfi`, a debug build of clang crashes from hitting `llvm_unreachable("Unexpected CFI call opcode")` in `llvm/lib/Target/X86/X86KCFI.cpp`.  Crash backtrace, preprocessed source, and associated run script for a minimal reproducer are attached.

[backtrace.txt](https://github.com/llvm/llvm-project/files/10018542/backtrace.txt)
[repro-bf6755.c.txt](https://github.com/llvm/llvm-project/files/10018493/repro-bf6755.c.txt)
[repro-bf6755.sh.txt](https://github.com/llvm/llvm-project/files/10018502/repro-bf6755.sh.txt)

**Comment by ebiggers** [comment]
Code was introduced by cff5bef948c91e4919de8a5fb9765e0edc13f3de by @samitolvanen.

**Comment by ebiggers** [comment]
Maybe related to this bug: with a release build of clang (to avoid the crash in `X86KCFI.cpp`), the KCFI checks in the Linux kernel seem to be incorrect.  For example:

```
ffffffff811bf058:       41 ba 32 27 20 47       mov    $0x47202732,%r10d
ffffffff811bf05e:       44 03 50 fc             add    -0x4(%rax),%r10d
ffffffff811bf062:       74 02                   je     ffffffff811bf066 <vfs_mkdir+0xe6>
ffffffff811bf064:       0f 0b                   ud2
ffffffff811bf066:       ff 50 48                call   *0x48(%rax)
```

The kCFI check is done against `%rax`, but the actual function pointer that is called is `*0x48(%rax)`.

**Comment by samitolvanen** [comment]
Thanks for the reproducer, Eric! This happens because the KCFI pass doesn't handle `TAILJMPm64`. I'll submit a patch to add a test case and fix the issue.

**Comment by ebiggers** [comment]
Here is the Linux kernel config that I used above, with v6.1-rc5: [config.txt](https://github.com/llvm/llvm-project/files/10023977/config.txt).

Use `objdump -d vmlinux | grep -A75 '<vfs_mkdir>:` to find the code I mentioned.  `%rax` points to a `struct inode_operations`, and `*0x48(%rax)` is the `mkdir` member of the struct.
