### ISSUE TITLE
ld.lld: error: unable to find library -lclang_rt.builtins-riscv64 for using clang to compile hello word for riscv

### ISSUE THREAD

**Issue by dshm** [llvm/llvm-project#59026]
I want use LLVM to generate code to RISC-V target, and  I following the following step:
```shell
cmake -G "Unix Makefiles" -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;libcxx;libcxxabi;libunwind;lldb;compiler-rt;lld;polly;debuginfo-tests" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=On -DDEFAULT_SYSROOT="/data/dushaomin/task20221109/test2/install/riscv64-unknown-elf" -DGCC_INSTALL_PREFIX="/data/dushaomin/task20221109/test2/install" -DLLVM_TARGETS_TO_BUILD="RISCV" ../llvm
```

`/data/dushaomin/task20221109/test2/install` is where I install `riscv-gnu-toolchains`
 
`make -j`

The above steps build successfully. 

But when I use the generated Clang to compile hello world to RISC-V, it get `ld.lld: error: unable to find library -lclang_rt.builtins-riscv64`. I have seen https://github.com/llvm/llvm-project/issues/56196 . The issue said it was the problem of compiler-rt, but my compiler-rt is built successful. 

The `hello.c` I use is:
```c
#include<stdio.h>
int main()
{

	printf("hello\n");
	return 0;
}
```

the command I use is
```shell
clang --target=riscv64 -march=rv64gc ./hello.c -o helloclang
```

As I have set `-DDEFAULT_SYSROOT` and `-DGCC_INSTALL_PREFIX` when CMake, I think it is not need to set `--sysroot` and `--gcc-toolchain` when using Clang. refering to https://stackoverflow.com/questions/68580399/using-clang-to-compile-for-risc-v/68583104#68583104  
The llvm-project I use is tag llvmorg-12.0.0-rc5. I also tried latter version but they can't make successful. Do I miss some important steps? And how can I solve the problem `ld.lld: error: unable to find library -lclang_rt.builtins-riscv64`?  Thank you and wait for help!

**Comment by MaskRay** [comment]
This is a pilot error. riscv64 compiler-rt works fine.

> `clang --target=riscv64 -march=rv64gc ./hello.c -o helloclang`

The `--target=` value needs to match the full target triple in `$build/lib/clang/16/lib/$triple`.

**Comment by dshm** [comment]
> This is a pilot error. riscv64 compiler-rt works fine.
> 
> > `clang --target=riscv64 -march=rv64gc ./hello.c -o helloclang`
> 
> The `--target=` value needs to match the full target triple in `$build/lib/clang/16/lib/$triple`. It's likely `riscv64-unknown-linux-gnu`

I tried  "clang --target=riscv64-unknown-linux-gnu -march=rv64gc ./hello.c -o helloclang", but I get the error below:
/usr/bin/ld: unrecognised emulation mode: elf64lriscv
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386linux elf_l1om elf_k1om i386pep i386pe
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)

the contents in $build/lib/clang/16/lib/ is:

/data/dushaomin/task20221114/llvm-project-llvmorg-12.0.0-rc5/build3/lib/clang/12.0.0/lib$ ls
linux

/data/dushaomin/task20221114/llvm-project-llvmorg-12.0.0-rc5/build3/lib/clang/12.0.0/lib$ ls linux
clang_rt.crtbegin-i386.o                  libclang_rt.hwasan_cxx-x86_64.a          libclang_rt.scudo_standalone_cxx-x86_64.a
clang_rt.crtbegin-x86_64.o                libclang_rt.hwasan_cxx-x86_64.a.syms     libclang_rt.scudo_standalone-i386.a
clang_rt.crtend-i386.o                    libclang_rt.hwasan-x86_64.a              libclang_rt.scudo_standalone-x86_64.a
clang_rt.crtend-x86_64.o                  libclang_rt.hwasan-x86_64.a.syms         libclang_rt.scudo-x86_64.a
libclang_rt.asan_cxx-i386.a               libclang_rt.hwasan-x86_64.so             libclang_rt.scudo-x86_64.so
libclang_rt.asan_cxx-x86_64.a             libclang_rt.lsan-i386.a                  libclang_rt.stats_client-i386.a
libclang_rt.asan_cxx-x86_64.a.syms        libclang_rt.lsan-x86_64.a                libclang_rt.stats_client-x86_64.a
libclang_rt.asan-i386.a                   libclang_rt.memprof_cxx-x86_64.a         libclang_rt.stats-i386.a
libclang_rt.asan-i386.so                  libclang_rt.memprof_cxx-x86_64.a.syms    libclang_rt.stats-x86_64.a
libclang_rt.asan-preinit-i386.a           libclang_rt.memprof-preinit-x86_64.a     libclang_rt.tsan_cxx-x86_64.a
libclang_rt.asan-preinit-x86_64.a         libclang_rt.memprof-x86_64.a             libclang_rt.tsan_cxx-x86_64.a.syms
libclang_rt.asan-x86_64.a                 libclang_rt.memprof-x86_64.a.syms        libclang_rt.tsan-x86_64.a
libclang_rt.asan-x86_64.a.syms            libclang_rt.memprof-x86_64.so            libclang_rt.tsan-x86_64.a.syms
libclang_rt.asan-x86_64.so                libclang_rt.msan_cxx-x86_64.a            libclang_rt.ubsan_minimal-i386.a
libclang_rt.builtins-i386.a               libclang_rt.msan_cxx-x86_64.a.syms       libclang_rt.ubsan_minimal-i386.so
libclang_rt.builtins-x86_64.a             libclang_rt.msan-x86_64.a                libclang_rt.ubsan_minimal-x86_64.a
libclang_rt.cfi_diag-i386.a               libclang_rt.msan-x86_64.a.syms           libclang_rt.ubsan_minimal-x86_64.a.syms
libclang_rt.cfi_diag-x86_64.a             libclang_rt.profile-i386.a               libclang_rt.ubsan_minimal-x86_64.so
libclang_rt.cfi-i386.a                    libclang_rt.profile-x86_64.a             libclang_rt.ubsan_standalone_cxx-i386.a
libclang_rt.cfi-x86_64.a                  libclang_rt.safestack-i386.a             libclang_rt.ubsan_standalone_cxx-x86_64.a
libclang_rt.dd-x86_64.a                   libclang_rt.safestack-x86_64.a           libclang_rt.ubsan_standalone_cxx-x86_64.a.syms
libclang_rt.dfsan-x86_64.a                libclang_rt.scudo_cxx-i386.a             libclang_rt.ubsan_standalone-i386.a
libclang_rt.dfsan-x86_64.a.syms           libclang_rt.scudo_cxx_minimal-i386.a     libclang_rt.ubsan_standalone-i386.so
libclang_rt.dyndd-x86_64.so               libclang_rt.scudo_cxx_minimal-x86_64.a   libclang_rt.ubsan_standalone-x86_64.a
libclang_rt.fuzzer-i386.a                 libclang_rt.scudo_cxx-x86_64.a           libclang_rt.ubsan_standalone-x86_64.a.syms
libclang_rt.fuzzer_interceptors-i386.a    libclang_rt.scudo-i386.a                 libclang_rt.ubsan_standalone-x86_64.so
libclang_rt.fuzzer_interceptors-x86_64.a  libclang_rt.scudo-i386.so                libclang_rt.xray-basic-x86_64.a
libclang_rt.fuzzer_no_main-i386.a         libclang_rt.scudo_minimal-i386.a         libclang_rt.xray-fdr-x86_64.a
libclang_rt.fuzzer_no_main-x86_64.a       libclang_rt.scudo_minimal-i386.so        libclang_rt.xray-profiling-x86_64.a
libclang_rt.fuzzer-x86_64.a               libclang_rt.scudo_minimal-x86_64.a       libclang_rt.xray-x86_64.a
libclang_rt.gwp_asan-i386.a               libclang_rt.scudo_minimal-x86_64.so
libclang_rt.gwp_asan-x86_64.a             libclang_rt.scudo_standalone_cxx-i386.a

Thank you and wait for your reply!

**Comment by dshm** [comment]
> > This is a pilot error. riscv64 compiler-rt works fine.
> > > `clang --target=riscv64 -march=rv64gc ./hello.c -o helloclang`
> > 
> > 
> > The `--target=` value needs to match the full target triple in `$build/lib/clang/16/lib/$triple`. It's likely `riscv64-unknown-linux-gnu`
> 
> I tried "clang --target=riscv64-unknown-linux-gnu -march=rv64gc ./hello.c -o helloclang", but I get the error below: /usr/bin/ld: unrecognised emulation mode: elf64lriscv Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386linux elf_l1om elf_k1om i386pep i386pe clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> the contents in $build/lib/clang/16/lib/ is:
> 
> /data/dushaomin/task20221114/llvm-project-llvmorg-12.0.0-rc5/build3/lib/clang/12.0.0/lib$ ls linux
> 
> /data/dushaomin/task20221114/llvm-project-llvmorg-12.0.0-rc5/build3/lib/clang/12.0.0/lib$ ls linux clang_rt.crtbegin-i386.o libclang_rt.hwasan_cxx-x86_64.a libclang_rt.scudo_standalone_cxx-x86_64.a clang_rt.crtbegin-x86_64.o libclang_rt.hwasan_cxx-x86_64.a.syms libclang_rt.scudo_standalone-i386.a clang_rt.crtend-i386.o libclang_rt.hwasan-x86_64.a libclang_rt.scudo_standalone-x86_64.a clang_rt.crtend-x86_64.o libclang_rt.hwasan-x86_64.a.syms libclang_rt.scudo-x86_64.a libclang_rt.asan_cxx-i386.a libclang_rt.hwasan-x86_64.so libclang_rt.scudo-x86_64.so libclang_rt.asan_cxx-x86_64.a libclang_rt.lsan-i386.a libclang_rt.stats_client-i386.a libclang_rt.asan_cxx-x86_64.a.syms libclang_rt.lsan-x86_64.a libclang_rt.stats_client-x86_64.a libclang_rt.asan-i386.a libclang_rt.memprof_cxx-x86_64.a libclang_rt.stats-i386.a libclang_rt.asan-i386.so libclang_rt.memprof_cxx-x86_64.a.syms libclang_rt.stats-x86_64.a libclang_rt.asan-preinit-i386.a libclang_rt.memprof-preinit-x86_64.a libclang_rt.tsan_cxx-x86_64.a libclang_rt.asan-preinit-x86_64.a libclang_rt.memprof-x86_64.a libclang_rt.tsan_cxx-x86_64.a.syms libclang_rt.asan-x86_64.a libclang_rt.memprof-x86_64.a.syms libclang_rt.tsan-x86_64.a libclang_rt.asan-x86_64.a.syms libclang_rt.memprof-x86_64.so libclang_rt.tsan-x86_64.a.syms libclang_rt.asan-x86_64.so libclang_rt.msan_cxx-x86_64.a libclang_rt.ubsan_minimal-i386.a libclang_rt.builtins-i386.a libclang_rt.msan_cxx-x86_64.a.syms libclang_rt.ubsan_minimal-i386.so libclang_rt.builtins-x86_64.a libclang_rt.msan-x86_64.a libclang_rt.ubsan_minimal-x86_64.a libclang_rt.cfi_diag-i386.a libclang_rt.msan-x86_64.a.syms libclang_rt.ubsan_minimal-x86_64.a.syms libclang_rt.cfi_diag-x86_64.a libclang_rt.profile-i386.a libclang_rt.ubsan_minimal-x86_64.so libclang_rt.cfi-i386.a libclang_rt.profile-x86_64.a libclang_rt.ubsan_standalone_cxx-i386.a libclang_rt.cfi-x86_64.a libclang_rt.safestack-i386.a libclang_rt.ubsan_standalone_cxx-x86_64.a libclang_rt.dd-x86_64.a libclang_rt.safestack-x86_64.a libclang_rt.ubsan_standalone_cxx-x86_64.a.syms libclang_rt.dfsan-x86_64.a libclang_rt.scudo_cxx-i386.a libclang_rt.ubsan_standalone-i386.a libclang_rt.dfsan-x86_64.a.syms libclang_rt.scudo_cxx_minimal-i386.a libclang_rt.ubsan_standalone-i386.so libclang_rt.dyndd-x86_64.so libclang_rt.scudo_cxx_minimal-x86_64.a libclang_rt.ubsan_standalone-x86_64.a libclang_rt.fuzzer-i386.a libclang_rt.scudo_cxx-x86_64.a libclang_rt.ubsan_standalone-x86_64.a.syms libclang_rt.fuzzer_interceptors-i386.a libclang_rt.scudo-i386.a libclang_rt.ubsan_standalone-x86_64.so libclang_rt.fuzzer_interceptors-x86_64.a libclang_rt.scudo-i386.so libclang_rt.xray-basic-x86_64.a libclang_rt.fuzzer_no_main-i386.a libclang_rt.scudo_minimal-i386.a libclang_rt.xray-fdr-x86_64.a libclang_rt.fuzzer_no_main-x86_64.a libclang_rt.scudo_minimal-i386.so libclang_rt.xray-profiling-x86_64.a libclang_rt.fuzzer-x86_64.a libclang_rt.scudo_minimal-x86_64.a libclang_rt.xray-x86_64.a libclang_rt.gwp_asan-i386.a libclang_rt.scudo_minimal-x86_64.so libclang_rt.gwp_asan-x86_64.a libclang_rt.scudo_standalone_cxx-i386.a
> 
> Thank you and wait for your reply! Is it the reason the build unsuccessful for riscv64? as I can't see libs with "riscv" suffix in llvm-project-llvmorg-12.0.0-rc5/build3/lib/clang/12.0.0/lib, but the make process is successful and 100%. What is wrong? @MaskRay  @llvmbot

**Comment by dshm** [comment]
> > > This is a pilot error. riscv64 compiler-rt works fine.
> > > > `clang --target=riscv64 -march=rv64gc ./hello.c -o helloclang`
> > > 
> > > 
> > > The `--target=` value needs to match the full target triple in `$build/lib/clang/16/lib/$triple`. It's likely `riscv64-unknown-linux-gnu`
> > 
> > 
> > I tried "clang --target=riscv64-unknown-linux-gnu -march=rv64gc ./hello.c -o helloclang", but I get the error below: /usr/bin/ld: unrecognised emulation mode: elf64lriscv Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386linux elf_l1om elf_k1om i386pep i386pe clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
> > the contents in $build/lib/clang/16/lib/ is:
> > /data/dushaomin/task20221114/llvm-project-llvmorg-12.0.0-rc5/build3/lib/clang/12.0.0/lib$ ls linux
> > /data/dushaomin/task20221114/llvm-project-llvmorg-12.0.0-rc5/build3/lib/clang/12.0.0/lib$ ls linux clang_rt.crtbegin-i386.o libclang_rt.hwasan_cxx-x86_64.a libclang_rt.scudo_standalone_cxx-x86_64.a clang_rt.crtbegin-x86_64.o libclang_rt.hwasan_cxx-x86_64.a.syms libclang_rt.scudo_standalone-i386.a clang_rt.crtend-i386.o libclang_rt.hwasan-x86_64.a libclang_rt.scudo_standalone-x86_64.a clang_rt.crtend-x86_64.o libclang_rt.hwasan-x86_64.a.syms libclang_rt.scudo-x86_64.a libclang_rt.asan_cxx-i386.a libclang_rt.hwasan-x86_64.so libclang_rt.scudo-x86_64.so libclang_rt.asan_cxx-x86_64.a libclang_rt.lsan-i386.a libclang_rt.stats_client-i386.a libclang_rt.asan_cxx-x86_64.a.syms libclang_rt.lsan-x86_64.a libclang_rt.stats_client-x86_64.a libclang_rt.asan-i386.a libclang_rt.memprof_cxx-x86_64.a libclang_rt.stats-i386.a libclang_rt.asan-i386.so libclang_rt.memprof_cxx-x86_64.a.syms libclang_rt.stats-x86_64.a libclang_rt.asan-preinit-i386.a libclang_rt.memprof-preinit-x86_64.a libclang_rt.tsan_cxx-x86_64.a libclang_rt.asan-preinit-x86_64.a libclang_rt.memprof-x86_64.a libclang_rt.tsan_cxx-x86_64.a.syms libclang_rt.asan-x86_64.a libclang_rt.memprof-x86_64.a.syms libclang_rt.tsan-x86_64.a libclang_rt.asan-x86_64.a.syms libclang_rt.memprof-x86_64.so libclang_rt.tsan-x86_64.a.syms libclang_rt.asan-x86_64.so libclang_rt.msan_cxx-x86_64.a libclang_rt.ubsan_minimal-i386.a libclang_rt.builtins-i386.a libclang_rt.msan_cxx-x86_64.a.syms libclang_rt.ubsan_minimal-i386.so libclang_rt.builtins-x86_64.a libclang_rt.msan-x86_64.a libclang_rt.ubsan_minimal-x86_64.a libclang_rt.cfi_diag-i386.a libclang_rt.msan-x86_64.a.syms libclang_rt.ubsan_minimal-x86_64.a.syms libclang_rt.cfi_diag-x86_64.a libclang_rt.profile-i386.a libclang_rt.ubsan_minimal-x86_64.so libclang_rt.cfi-i386.a libclang_rt.profile-x86_64.a libclang_rt.ubsan_standalone_cxx-i386.a libclang_rt.cfi-x86_64.a libclang_rt.safestack-i386.a libclang_rt.ubsan_standalone_cxx-x86_64.a libclang_rt.dd-x86_64.a libclang_rt.safestack-x86_64.a libclang_rt.ubsan_standalone_cxx-x86_64.a.syms libclang_rt.dfsan-x86_64.a libclang_rt.scudo_cxx-i386.a libclang_rt.ubsan_standalone-i386.a libclang_rt.dfsan-x86_64.a.syms libclang_rt.scudo_cxx_minimal-i386.a libclang_rt.ubsan_standalone-i386.so libclang_rt.dyndd-x86_64.so libclang_rt.scudo_cxx_minimal-x86_64.a libclang_rt.ubsan_standalone-x86_64.a libclang_rt.fuzzer-i386.a libclang_rt.scudo_cxx-x86_64.a libclang_rt.ubsan_standalone-x86_64.a.syms libclang_rt.fuzzer_interceptors-i386.a libclang_rt.scudo-i386.a libclang_rt.ubsan_standalone-x86_64.so libclang_rt.fuzzer_interceptors-x86_64.a libclang_rt.scudo-i386.so libclang_rt.xray-basic-x86_64.a libclang_rt.fuzzer_no_main-i386.a libclang_rt.scudo_minimal-i386.a libclang_rt.xray-fdr-x86_64.a libclang_rt.fuzzer_no_main-x86_64.a libclang_rt.scudo_minimal-i386.so libclang_rt.xray-profiling-x86_64.a libclang_rt.fuzzer-x86_64.a libclang_rt.scudo_minimal-x86_64.a libclang_rt.xray-x86_64.a libclang_rt.gwp_asan-i386.a libclang_rt.scudo_minimal-x86_64.so libclang_rt.gwp_asan-x86_64.a libclang_rt.scudo_standalone_cxx-i386.a
> > Thank you and wait for your reply! Is it the reason the build unsuccessful for riscv64? as I can't see libs with "riscv" suffix in llvm-project-llvmorg-12.0.0-rc5/build3/lib/clang/12.0.0/lib, but the make process is successful and 100%. What is wrong?
> 
> @MaskRay @llvmbot

additionly, the generated commands of clang is as below
/data/dushaomin/riscvgnutoolchaintest/testdir$ /data/dushaomin/task20221114/llvm-project-llvmorg-12.0.0-rc5/build3/bin/clang -### --target=riscv64-unknown-linux-gnu -march=rv64gc ./hello.c -o helloclang2
clang version 12.0.0
Target: riscv64-unknown-linux-gnu
Thread model: posix
InstalledDir: /data/dushaomin/task20221114/llvm-project-llvmorg-12.0.0-rc5/build3/bin
 "/data/dushaomin/task20221114/llvm-project-llvmorg-12.0.0-rc5/build3/bin/clang-12" "-cc1" "-triple" "riscv64-unknown-linux-gnu" "-emit-obj" "-mrelax-all" "--mrelax-relocations" "-disable-free" "-main-file-name" "hello.c" "-mrelocation-model" "static" "-mframe-pointer=all" "-fmath-errno" "-fno-rounding-math" "-mconstructor-aliases" "-target-feature" "+m" "-target-feature" "+a" "-target-feature" "+f" "-target-feature" "+d" "-target-feature" "+c" "-target-feature" "+relax" "-target-feature" "-save-restore" "-target-abi" "lp64d" "-msmall-data-limit" "8" "-fno-split-dwarf-inlining" "-debugger-tuning=gdb" "-resource-dir" "/data/dushaomin/task20221114/llvm-project-llvmorg-12.0.0-rc5/build3/lib/clang/12.0.0" "-isysroot" "/data/dushaomin/task20221109/test2/install/riscv64-unknown-elf" "-internal-isystem" "/data/dushaomin/task20221109/test2/install/riscv64-unknown-elf/usr/local/include" "-internal-isystem" "/data/dushaomin/task20221114/llvm-project-llvmorg-12.0.0-rc5/build3/lib/clang/12.0.0/include" "-internal-externc-isystem" "/data/dushaomin/task20221109/test2/install/riscv64-unknown-elf/include" "-internal-externc-isystem" "/data/dushaomin/task20221109/test2/install/riscv64-unknown-elf/usr/include" "-fdebug-compilation-dir" "/data/dushaomin/riscvgnutoolchaintest/testdir" "-ferror-limit" "19" "-fno-signed-char" "-fgnuc-version=4.2.1" "-fcolor-diagnostics" "-faddrsig" "-o" "/tmp/hello-267e8b.o" "-x" "c" "./hello.c" "/usr/bin/ld" "--sysroot=/data/dushaomin/task20221109/test2/install/riscv64-unknown-elf" "-z" "relro" "--hash-style=gnu" "--eh-frame-hdr" "-m" "elf64lriscv" "-dynamic-linker" "/lib/ld-linux-riscv64-lp64d.so.1" "-o" "helloclang2" "crt1.o" "crti.o" "crtbegin.o" "-L/data/dushaomin/task20221109/test2/install/riscv64-unknown-elf/lib" "/tmp/hello-267e8b.o" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "-lc" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "crtend.o" "crtn.o"

**Comment by dshm** [comment]
Is there any update? @MaskRay  @llvmbot

**Comment by BertalanD** [comment]
I think your issue is that the command you ran does *not* build the `compiler-rt` library, just the compiler. Check out [the documentation](https://llvm.org/docs/HowToCrossCompileBuiltinsOnArm.html) for how to cross-compile the builtins library.

**Comment by BertalanD** [comment]
Or this might also work and is a bit simpler: add `-DLLVM_BUILTIN_TARGETS=riscv64-unknown-elf -DBUILTINS_riscv64-unknown-elf_CMAKE_SYSROOT=<path to sysroot>`. And then you can run do `make builtins` in the build directory.

**Comment by dshm** [comment]
> ```shell
> -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;libcxx;libcxxabi;libunwind;lldb;compiler-rt;lld;polly;debuginfo-tests"
> ```

I write compiler-rt in the -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;libcxx;libcxxabi;libunwind;lldb;compiler-rt;lld;polly;debuginfo-tests" when doing cmake operation, but it seems not take effect. Is it an bug?

**Comment by dshm** [comment]
> I think your issue is that the command you ran does _not_ build the `compiler-rt` library, just the compiler. Check out [the documentation](https://llvm.org/docs/HowToCrossCompileBuiltinsOnArm.html) for how to cross-compile the builtins library.

I write compiler-rt in the -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;libcxx;libcxxabi;libunwind;lldb;compiler-rt;lld;polly;debuginfo-tests" when doing cmake operation, but it seems not take effect. Is it an bug?

**Comment by dshm** [comment]
> Or this might also work and is a bit simpler: add `-DLLVM_BUILTIN_TARGETS=riscv64-unknown-elf -DBUILTINS_riscv64-unknown-elf_CMAKE_SYSROOT=<path to sysroot>` to the CMake arguments. And then you can run do `make builtins` in the build directory.

Thank you for your reply! I will try as you said and reply later!

**Comment by BertalanD** [comment]
The two are different. If you write compiler-rt in `LLVM_ENABLE_PROJECTS` it will use the compiler you built LLVM with and not the just-built Clang to build the builtins *for the system Clang is running on*. That's why your directory listing above only shows x86_64 compiler-rt libraries.

**Comment by dshm** [comment]
> Or this might also work and is a bit simpler: add `-DLLVM_BUILTIN_TARGETS=riscv64-unknown-elf -DBUILTINS_riscv64-unknown-elf_CMAKE_SYSROOT=<path to sysroot>` to the CMake arguments. And then you can run do `make builtins` in the build directory.

I tried as you said, but it report error "make: *** No rule to make target 'builtins'.  Stop." Could you please give me the whole commands, process and code version you use?  I also tried set compiler-rt in LLVM_ENABLE_RUNTIMES, but it will give error "Please use architecture with 4 or 8 byte pointers " . I search the issues of llvm-project and it doesn't give a solution. Thank you and wait for you reply! 

@BertalanD @llvmbot

**Comment by dshm** [comment]
> > Or this might also work and is a bit simpler: add `-DLLVM_BUILTIN_TARGETS=riscv64-unknown-elf -DBUILTINS_riscv64-unknown-elf_CMAKE_SYSROOT=<path to sysroot>` to the CMake arguments. And then you can run do `make builtins` in the build directory.
> 
> I tried as you said, but it report error "make: *** No rule to make target 'builtins'. Stop." Could you please give me the whole commands, process and code version you use? I also tried set compiler-rt in LLVM_ENABLE_RUNTIMES, but it will give error "Please use architecture with 4 or 8 byte pointers " . I search the issues of llvm-project and find there are people who meet same error but it doesn't give a solution. Thank you and wait for you reply!
> 
> @BertalanD @llvmbot

Is there any update for this problem? Or is there a whole process to build compiler-rt or builtins for RISCV? Or is it possible to build compiler-rt or builtins for RISCV? Does it support RISCV? I searched issues of llvm-project and google much time, and I find there are lost of people ask similar problem but rhere is no complete answer to solve this. Thank you a lot!

@BertalanD @llvmbot
