### ISSUE TITLE
llvm-mc miscompiles some indirect jumps and calls in Intel syntax

### ISSUE THREAD

**Issue by LegionMammal978** [llvm/llvm-project#59038]
As a minimal example:
```asm
.intel_syntax noprefix
.text
jmp [addr]
.data
addr: .4byte 0x01234567
```

This is the observed output from `llvm-mc --arch=x86 --filetype=obj -o example.o example.s` (commit e989b8bb5fb36abac6e8f82809f06144dd762113), using `objdump -dr`:
```objdump
example.o:     file format elf32-i386


Disassembly of section .text:

00000000 <.text>:
   0:	e9 fc ff ff ff       	jmp    1 <.text+0x1>
			1: R_386_PC32	.data
```

But this is the expected output from `as -o example.o --32 example.s` (binutils 2.38-4ubuntu2):
```objdump
example.o:     file format elf32-i386


Disassembly of section .text:

00000000 <.text>:
   0:	ff 25 00 00 00 00    	jmp    *0x0
			2: R_386_32	.data
```

llvm-mc is converting the indirect `jmp [addr]` to a direct `jmp addr`, contrary to GNU as. This issue extends to all absolute indirect jumps and calls which refer to a displacement with no segment override.

In particular, llvm-mc produces direct jumps and calls for these syntaxes, contrary to GNU as:
```asm
jmp [addr]
jmp word ptr addr
jmp word ptr [addr]
jmp dword ptr addr   /* 32-bit */
jmp dword ptr [addr] /* 32-bit */
jmp qword ptr addr   /* 64-bit */
jmp qword ptr [addr] /* 64-bit */
jmp fword ptr addr
jmp fword ptr [addr]
call [addr]
call word ptr addr
call word ptr [addr]
call dword ptr addr   /* 32-bit */
call dword ptr [addr] /* 32-bit */
call qword ptr addr   /* 64-bit */
call qword ptr [addr] /* 64-bit */
call fword ptr addr
call fword ptr [addr]
```

(As a side note, GNU as recognizes these syntaxes, but llvm-mc does not:)
```asm
jmp near [addr]
jmp near ptr addr /* direct */
jmp near ptr ds:addr
jmp near ptr [addr]
jmp near ptr ds:[addr]
jmp far [addr]
jmp far ptr ds:addr
jmp far ptr [addr]
jmp far ptr ds:[addr]
call near [addr]
call near ptr addr /* direct */
call near ptr ds:addr
call near ptr [addr]
call near ptr ds:[addr]
call far [addr]
call far ptr ds:addr
call far ptr [addr]
call far ptr ds:[addr]
```

This issue can also be observed from inline assembly in C. This program compiles and runs successfully with `gcc -m32 -masm=intel -no-pie -o example example.c`, but produces a segmentation fault with `clang -m32 -masm=intel -no-pie -o example example.c`:
```c
#include <stdio.h>

static void target(void) {
    puts("Hello, world!");
}
void (*target_addr)(void) = target;

void indirect(void);
__asm__ (
    ".text\n"
    "indirect:\n\t"
    "jmp [target_addr]"
);

int main(void) {
    indirect();
}
```

**Comment by MaskRay** [comment]
Fixed by https://reviews.llvm.org/D149920 and https://reviews.llvm.org/D149579

For x86-32:

If we remove

    jmp qword ptr addr   /* 64-bit */
    jmp qword ptr [addr] /* 64-bit */

llvm-mc -triple=i686 output now matches as --32.

For x86-64, the following instructions are assembled differently.
```
jmp word ptr addr
jmp word ptr [addr]
jmp dword ptr addr   /* 32-bit */
jmp dword ptr [addr] /* 32-bit */

call word ptr addr
call word ptr [addr]
call dword ptr addr   /* 32-bit */
call dword ptr [addr] /* 32-bit */
```

I am not so familiar but they feel invalid to me.

For your C example,
```
#include <stdio.h>

static void target(void) {
    puts("Hello, world!");
}
void (*target_addr)(void) = target;

void indirect(void);
__asm__ (
    ".text\n"
    "indirect:\n\t"
    "jmp [target_addr]"
);

int main(void) {
    indirect();
}
```

`gcc -m32 -masm=intel -no-pie` and `clang -m32 -masm=intel -no-pie` now match.
