### ISSUE TITLE
not ignoring -plugin-opt=...lto-wrapper.exe on Windows in the same way as other OS's

### ISSUE THREAD

**Issue by bwerl** [llvm/llvm-project#59049]
When using GCC cross-compiled for Windows, but with the LLVM linker, the argument "-plugin-opt=<Windows path to>\lto-wrapper.exe" is not being ignored in the same was as it is on, e.g. an Ubuntu 18.04 machine doing the same thing (GCC to compile, LLVM to link)

**Comment by bwerl** [comment]
I'm sure I haven't done this correctly, but my intention is to hopefully get the upstream change backported to the 15.0.x release if possible. As this is my first attempt at such a thing, would appreciate any help that anyone can provide!

**Comment by aganea** [comment]
@tru
