### ISSUE TITLE
BOLT instrumented LLD generates no profile

### ISSUE THREAD

**Issue by vient** [llvm/llvm-project#59059]
Hi, I'm trying to optimize Clang with BOLT. I've encountered problems with lld. I instrument clang-15 and lld binaries with BOLT, then build system calls `clang`/`clang++` and `ld.lld` symlinks. While clang fdata profiles are successfully created, lld does not produce any profile when run.

Here is my code
```bash
...

function instrument_with_bolt {
    "${BASE_COMPILER_DIR}/install/bin/llvm-bolt" "$1" \
        -instrument \
        -instrumentation-file-append-pid \
        -instrumentation-file="$1.bolt" \
        -o "$1.bolt_inst"
    mv "$1" "$1.bak"
    mv "$1.bolt_inst" "$1"
}

CPATH="${TOPLEV}/stage2-prof-use-lto/install/bin"
instrument_with_bolt "${CPATH}/clang-${CLANG_VERSION}"
instrument_with_bolt "${CPATH}/lld"
```
and results after running it
```console
# cd stage2-prof-use-lto/install/bin
# ls *clang-15* *lld*
clang-15  clang-15.bak  ld64.lld  ld.lld  lld  lld.bak  lld-link
# ./clang
clang-15: error: no input files
# ./ld.lld
ld.lld: error: no input files
# ls *clang-15* *lld*
clang-15  clang-15.bak  clang-15.bolt.5423.fdata  ld64.lld  ld.lld  lld  lld.bak  lld-link
```

Am I doing something wrong? Why is profile created for clang but not for lld?

I am using `llvmorg-15.0.5` source from github, bootstrapped it using gcc, then built again with itself.
`stage2-prof-use-lto` is built like this, if that matters
```bash
DEBUG_FLAGS="-gdwarf-4 -g1"
CLANG_C_FLAGS="-march=x86-64-v2 -fno-pie ${DEBUG_FLAGS}"
CLANG_CXX_FLAGS="${CLANG_C_FLAGS}"
CLANG_EXE_LINKER_FLAGS="-Wl,--emit-relocs,-znow -fno-pie -no-pie ${DEBUG_FLAGS}"

cmake -G Ninja "${TOPLEV}/llvm-project/llvm" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER="${CPATH}/clang" \
    -DCMAKE_C_FLAGS="${CLANG_C_FLAGS} -Wno-backend-plugin" \
    -DCMAKE_CXX_COMPILER="${CPATH}/clang++" \
    -DCMAKE_CXX_FLAGS="${CLANG_CXX_FLAGS} -Wno-backend-plugin" \
    -DCMAKE_INSTALL_PREFIX="${TOPLEV}/stage2-prof-use-lto/install" \
    -DCMAKE_EXE_LINKER_FLAGS="${CLANG_EXE_LINKER_FLAGS}" \
    -DLLVM_BINUTILS_INCDIR="${BINUTILS_INCLUDE_DIR}" \
    -DLLVM_ENABLE_LTO=Thin \
    -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld;bolt" \
    -DLLVM_ENABLE_RUNTIMES="compiler-rt" \
    -DLLVM_ENABLE_TERMINFO=OFF \
    -DLLVM_PARALLEL_LINK_JOBS=2 \
    -DLLVM_PROFDATA_FILE="${TOPLEV}/stage2-prof-gen/profiles/clang.profdata" \
    -DLLVM_TARGETS_TO_BUILD=X86 \
    -DLLVM_USE_LINKER=lld
ninja install
```

**Comment by vient** [comment]
I also tried to `cp lld ld.lld` and instrument ld.lld directly then, it still does not generate a profile when used.

**Comment by rafaelauler** [comment]
I don't know what might be happening, but one thing I can guess is that because you are not setting an absolute path to the profile, the process is going use whatever is set as the current working dir. Maybe lld is changing CWD?

lld sets a bunch of symlinks to it, but that shouldn't affect the profile collection.

**Comment by vient** [comment]
I am passing absolute paths here
```
instrument_with_bolt "${CPATH}/clang-${CLANG_VERSION}"
instrument_with_bolt "${CPATH}/lld"
```
It looks like this
```
TOPLEV="$(realpath work)"
...
CPATH="${TOPLEV}/stage2-prof-use-lto/install/bin"
# "${CPATH}/clang-${CLANG_VERSION}" = /test/work/stage2-prof-use-lto/install/bin/clang-15
```
so after substituting it in the function it becomes
```bash
"/test/work/stage1/install/bin/llvm-bolt" "/test/work/stage2-prof-use-lto/install/bin/clang-15" \
    -instrument \
    -instrumentation-file-append-pid \
    -instrumentation-file="/test/work/stage2-prof-use-lto/install/bin/clang-15.bolt" \
    -o "/test/work/stage2-prof-use-lto/install/bin/clang-15.bolt_inst"
mv "/test/work/stage2-prof-use-lto/install/bin/clang-15" "/test/work/stage2-prof-use-lto/install/bin/clang-15.bak"
mv "/test/work/stage2-prof-use-lto/install/bin/clang-15.bolt_inst" "/test/work/stage2-prof-use-lto/install/bin/clang-15"
```

I'm pretty sure that I did not see ld.lld trying to open profile file under strace, deleted build folder since then. Will re-check later.

**Comment by aaupov** [comment]
Hi @vient

It's a known issue that LLD doesn't shut down cleanly by default, and that's where BOLT instrumentation adds code to dump the profile. There's an environment variable for forcing it that I forgot but @maksfb knows.

**Comment by aaupov** [comment]
> Hi @vient
> 
> It's a known issue that LLD doesn't shut down cleanly by default, and that's where BOLT instrumentation adds code to dump the profile. There's an environment variable for forcing it that I forgot but @maksfb knows.

LLD_IN_TEST=1
