### ISSUE TITLE
Failure to build with zstd with 15.0.3 or ToT on OpenBSD

### ISSUE THREAD

**Issue by brad0** [llvm/llvm-project#59056]
Ever since https://github.com/llvm/llvm-project/issues/58205 went in it has broken the build on OpenBSD. If I use 15.0.2 it's fine. 15.0.3 or ToT and it's broken. If I use `-DLLVM_ENABLE_ZSTD=OFF` it skips the test and completes the CMake configuration.

```console
CMake Error at lib/Support/CMakeLists.txt:312 (get_property):
  get_property could not find TARGET zstd::libzstd_static.  Perhaps it has
  not yet been created.

CMake Error at lib/Support/CMakeLists.txt:315 (get_property):
  get_property could not find TARGET zstd::libzstd_static.  Perhaps it has
  not yet been created.

CMake Error at lib/Support/CMakeLists.txt:317 (get_library_name):
  get_library_name Function invoked with incorrect arguments for function
  named: get_library_name
```

**Comment by mgorny** [comment]
Could you give us more information how zstd is built on OpenBSD? Which build system is used, which files are installed?

**Comment by brad0** [comment]
I'm not familiar with zstd. But looking at our port it appears to be using a GNU Makefile.

```
fubar$ pkg_info -L zstd
Information for inst:zstd-1.5.2

Files:
/usr/local/bin/unzstd
/usr/local/bin/zstd
/usr/local/bin/zstdcat
/usr/local/bin/zstdgrep
/usr/local/bin/zstdless
/usr/local/bin/zstdmt
/usr/local/include/zdict.h
/usr/local/include/zstd.h
/usr/local/include/zstd_errors.h
/usr/local/lib/libzstd.a
/usr/local/lib/libzstd.so.6.1
/usr/local/lib/pkgconfig/libzstd.pc
/usr/local/man/man1/unzstd.1
/usr/local/man/man1/zstd.1
/usr/local/man/man1/zstdcat.1
/usr/local/man/man1/zstdgrep.1
/usr/local/man/man1/zstdless.1
```

**Comment by mgorny** [comment]
That looks pretty normal.

How about:

```
grep zstd CMakeCache.txt
```

**Comment by DimitryAndric** [comment]
I reported the same problem in https://discourse.llvm.org/t/llvm-15-0-3-tagged/66031/5?u=dimitryandric, and I simply rolled back b4840279846e1eea44c3dca575395a90c9d77ca0 to work around it.

**Comment by DimitryAndric** [comment]
> I reported the same problem in https://discourse.llvm.org/t/llvm-15-0-3-tagged/66031/5?u=dimitryandric

That was on macOS, btw. Where zstd is installed by Homebrew, into `/opt/homebrew`. You have to force it to link statically in that case, otherwise end users can't run it without also installing Homebrew and the zstd package.

**Comment by brad0** [comment]
> I reported the same problem in https://discourse.llvm.org/t/llvm-15-0-3-tagged/66031/5?u=dimitryandric, and I simply rolled back [b484027](https://github.com/llvm/llvm-project/commit/b4840279846e1eea44c3dca575395a90c9d77ca0) to work around it.

I saw that, but it would be nice to try and come up with a resolution to the issue. I don't mind using the command line param to disable zstd for the time being.

Does macOS not have something like rpath?

**Comment by DimitryAndric** [comment]
Well, macOS does have something like rpath, but in the spirit of "think different", [it is rather different than how BSDs and Linux implement it](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/RunpathDependentLibraries.html). :) You would still have copy `libzstd.1.dylib` into your final installation directory, and I'm unsure how you do that in CMake land. I'm not going to touch it, in any case.

Btw it seems to work OK with main (as of fcd5098a03da from just now), but still errors out with `release/15.x` as of 154e88af7ec9, if you specify `-D LLVM_USE_STATIC_ZSTD=ON`:

```
command: cmake -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/Users/dim/llvm/llvmorg-15.0.5-0-g154e88af7ec9-1 -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ -D LLVM_ENABLE_PROJECTS=clang -D LLVM_USE_STATIC_ZSTD=ON /Users/dim/src/llvm/release-15/llvm
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
...
-- Looking for __x86_64__
-- Looking for __x86_64__ - not found
CMake Error at lib/Support/CMakeLists.txt:309 (get_property):
  get_property could not find TARGET zstd::libzstd_static.  Perhaps it has
  not yet been created.


CMake Error at lib/Support/CMakeLists.txt:312 (get_property):
  get_property could not find TARGET zstd::libzstd_static.  Perhaps it has
  not yet been created.


CMake Error at lib/Support/CMakeLists.txt:314 (get_library_name):
  get_library_name Function invoked with incorrect arguments for function
  named: get_library_name


-- Found Git: /usr/bin/git (found version "2.37.1 (Apple Git-137.1)")
...
-- Configuring incomplete, errors occurred!
See also "/Users/dim/obj/llvmorg-15.0.5-0-g154e88af7ec9-1/CMakeFiles/CMakeOutput.log".
See also "/Users/dim/obj/llvmorg-15.0.5-0-g154e88af7ec9-1/CMakeFiles/CMakeError.log".
```

It does show zstd in `CMakeCache.txt`:

```
% grep -i zstd CMakeCache.txt
//Use zstd for compression/decompression if available. Can be ON,
LLVM_ENABLE_ZSTD:STRING=ON
//Use static version of zstd. Can be TRUE, FALSE
LLVM_USE_STATIC_ZSTD:BOOL=ON
zstd_INCLUDE_DIR:PATH=/opt/homebrew/include
zstd_LIBRARY:FILEPATH=/opt/homebrew/lib/libzstd.dylib
//ADVANCED property for variable: zstd_INCLUDE_DIR
zstd_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: zstd_LIBRARY
zstd_LIBRARY-ADVANCED:INTERNAL=1
```

At first sight it looks like @mgorny fixed this in main with 56f94ede2af9a327e59fe84dbf8cbbb7bb1dfa79 ?

**Comment by brad0** [comment]
> Btw it seems to work OK with main (as of [fcd5098](https://github.com/llvm/llvm-project/commit/fcd5098a03dadcd11d4cc8b7155a4c07581999de) from just now), but still errors out with `release/15.x` as of [154e88a](https://github.com/llvm/llvm-project/commit/154e88af7ec97d9b9f389e55d45bf07108a9a097), if you specify `-D LLVM_USE_STATIC_ZSTD=ON`:
> 
> ```
> command: cmake -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/Users/dim/llvm/llvmorg-15.0.5-0-g154e88af7ec9-1 -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ -D LLVM_ENABLE_PROJECTS=clang -D LLVM_USE_STATIC_ZSTD=ON /Users/dim/src/llvm/release-15/llvm
> -- The C compiler identification is AppleClang 14.0.0.14000029
> -- The CXX compiler identification is AppleClang 14.0.0.14000029
> -- The ASM compiler identification is Clang with GNU-like command-line
> -- Found assembler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
> ...
> -- Looking for __x86_64__
> -- Looking for __x86_64__ - not found
> CMake Error at lib/Support/CMakeLists.txt:309 (get_property):
>   get_property could not find TARGET zstd::libzstd_static.  Perhaps it has
>   not yet been created.
> 
> 
> CMake Error at lib/Support/CMakeLists.txt:312 (get_property):
>   get_property could not find TARGET zstd::libzstd_static.  Perhaps it has
>   not yet been created.
> 
> 
> CMake Error at lib/Support/CMakeLists.txt:314 (get_library_name):
>   get_library_name Function invoked with incorrect arguments for function
>   named: get_library_name
> 
> 
> -- Found Git: /usr/bin/git (found version "2.37.1 (Apple Git-137.1)")
> ...
> -- Configuring incomplete, errors occurred!
> See also "/Users/dim/obj/llvmorg-15.0.5-0-g154e88af7ec9-1/CMakeFiles/CMakeOutput.log".
> See also "/Users/dim/obj/llvmorg-15.0.5-0-g154e88af7ec9-1/CMakeFiles/CMakeError.log".
> ```
> 
> It does show zstd in `CMakeCache.txt`:
> 
> ```
> % grep -i zstd CMakeCache.txt
> //Use zstd for compression/decompression if available. Can be ON,
> LLVM_ENABLE_ZSTD:STRING=ON
> //Use static version of zstd. Can be TRUE, FALSE
> LLVM_USE_STATIC_ZSTD:BOOL=ON
> zstd_INCLUDE_DIR:PATH=/opt/homebrew/include
> zstd_LIBRARY:FILEPATH=/opt/homebrew/lib/libzstd.dylib
> //ADVANCED property for variable: zstd_INCLUDE_DIR
> zstd_INCLUDE_DIR-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: zstd_LIBRARY
> zstd_LIBRARY-ADVANCED:INTERNAL=1
> ```
> 
> At first sight it looks like @mgorny fixed this in main with [56f94ed](https://github.com/llvm/llvm-project/commit/56f94ede2af9a327e59fe84dbf8cbbb7bb1dfa79) ?

I'm still seeing the same error even with main.

```
fubar$ grep -i zstd CMakeCache.txt
//Use zstd for compression/decompression if available. Can be ON,
LLVM_ENABLE_ZSTD:STRING=ON
//Use static version of zstd. Can be TRUE, FALSE
LLVM_USE_STATIC_ZSTD:BOOL=FALSE
zstd_INCLUDE_DIR:PATH=/usr/local/include
zstd_LIBRARY:FILEPATH=/usr/local/lib/libzstd.so.6.1
zstd_STATIC_LIBRARY:FILEPATH=/usr/local/lib/libzstd.a
//ADVANCED property for variable: zstd_INCLUDE_DIR
zstd_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: zstd_LIBRARY
zstd_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: zstd_STATIC_LIBRARY
zstd_STATIC_LIBRARY-ADVANCED:INTERNAL=1
```

**Comment by mgorny** [comment]
Ok, I think I know what the problem is, or at least part of the problem. For some reason, your CMake sets path to the library as `/usr/local/lib/libzstd.so.6.1` whereas it just gives `/usr/lib64/libzstd.so` here. The SOVERSION causes the `zstd_SHARED_LIBRARY_SUFFIX` not to match. Any clue why it behaves like that?

CC @petrhosek.

**Comment by brad0** [comment]
> Ok, I think I know what the problem is, or at least part of the problem. For some reason, your CMake sets path to the library as `/usr/local/lib/libzstd.so.6.1` whereas it just gives `/usr/lib64/libzstd.so` here. The SOVERSION causes the `zstd_SHARED_LIBRARY_SUFFIX` not to match. Any clue why it behaves like that?
> 
> CC @petrhosek.

OpenBSD handles shared libs differently from other ELF OS's.

**Comment by mgorny** [comment]
@brad0, could you test the patch I've submitted as https://reviews.llvm.org/D138361 ? I think it should fix your problem but I'm not 100% sure.

**Comment by ToCodeABluejay** [comment]
This issue is still active. I can myself confirm that neither 15.0.6 nor 15.0.7 will build on OpenBSD. I receive the same CMake error as originally posted. I don't know why, if this issue was seemingly patched, this keeps being reproduced upon further releases.

**Comment by thesamesam** [comment]
The fixes didn't seem to get backported in 15.x but I assume @brad0 has either backported them in OpenBSD or is on it.
