### ISSUE TITLE
-freroll-loops command line option broken

### ISSUE THREAD

**Issue by m9710797** [llvm/llvm-project#59065]
Hi,

The option `-freroll-loop` is a documented option (https://clang.llvm.org/docs/ClangCommandLineReference.html), and Clang still accepts it. Though it doesn't seem to have any effect anymore.

It seems it got broken since the switch to the new pass manager. See here for some experiments/testcases:
    https://godbolt.org/z/377dfonoj

* It still works with clang-12.
* It no longer works with clang-13. 
* clang-13 with the option `-flegacy-pass-manager` does work.

Wouter

**Comment by xgupta** [comment]
Yeah, with opt it is working - https://godbolt.org/z/xG4ra15TK. but not running with clang - https://godbolt.org/z/T8xsv768W. 

CC @aeubanks.
