### ISSUE TITLE
Suboptimal code generated for inline asm doing `pop %0` to a memory operand

### ISSUE THREAD

**Issue by ramosian-glider** [llvm/llvm-project#59069]
Godbolt link: https://godbolt.org/z/x9s3Toxbz

For the following code snippet:

```c
/*
 * Code snippet taken from the Linux kernel except for the flags = 0
 * assignment, which is excessive.
 */
extern unsigned long native_save_fl(void)
{
        unsigned long flags = 0;

        /*
         * "=rm" is safe here, because "pop" adjusts the stack before
         * it evaluates its effective address -- this is part of the
         * documented behavior of the "pop" instruction.
         */
        asm volatile("# __raw_save_flags\n\t"
                     "pushf ; pop %0"
                     : "=rm" (flags)
                     : /* no input */
                     : "memory");

        return flags;
}
```

trunk Clang with `-O3` generates unnecessary memory accesses to a local, failing to place it onto a register:

```asm
native_save_fl:                         # @native_save_fl
        movq    $0, -8(%rsp)
        pushfq
        popq    -8(%rsp)
        movq    -8(%rsp), %rax
        retq
```

, whereas GCC just reuses `%rax`:

```asm
native_save_fl:
        pushf ; pop %rax
        ret
```

Removing the assignment of 0 to `flags` does save a memory store, but Clang's output is still different from what GCC does:

```asm
native_save_fl:                         # @native_save_fl
        pushfq
        popq    -8(%rsp)
        movq    -8(%rsp), %rax
        retq
```

**Comment by topperc** [comment]
LLVM ignores the "r" if you put "rm". There's no code to make an intelligent decision. We just pick the most conservative.

**Comment by ramosian-glider** [comment]
Thanks for clarifying this. Regarding the original code, looks like there are better ways to save flags anyway: https://lkml.org/lkml/2021/12/28/566

CC @nickdesaulniers @isanbard for visibility

**Comment by nickdesaulniers** [comment]
This is a duplicate of https://github.com/llvm/llvm-project/issues/20571.
