### ISSUE TITLE
[llvm-exegesis] Remove "Check generated assembly with..." line from yaml dumps

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#59082]
https://github.com/llvm/llvm-project/blob/aae08b1d372a45b8bef95e86e5fe9110045eb78d/llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp#L202-L203

These require manual stripping before the exegesis output can be used for analysis, which when performing an 'all instructions' dump can be rather annoying - is it actually useful or can we remove the output entirely?

**Comment by LebedevRI** [comment]
You can just pass `--dump-object-to-disk=0`. I think we might want to flip the default on that.

**Comment by LebedevRI** [comment]
https://reviews.llvm.org/D140700
