### ISSUE TITLE
llvm 16 linker crash with segmentation fault 11 on compiling chromium iOS

### ISSUE THREAD

**Issue by sonatans** [llvm/llvm-project#59092]
Stack dump:
0.	Program arguments: ../../third_party/llvm-build/Release+Asserts/bin/ld64.lld @/var/folders/s0/q_pbm52x5mxg0vj573m09wx00000gn/T/response-08143e.txt
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  lld                      0x0000000100d0a414 llvm::SmallVectorBase<unsigned long long>::set_size(unsigned long) + 316996
1  lld                      0x0000000100d0a7fc llvm::SmallVectorBase<unsigned long long>::set_size(unsigned long) + 317996
2  libsystem_platform.dylib 0x00000001a66a34a4 _sigtramp + 56
3  lld                      0x0000000100f7e620 void lld::macho::ObjFile::parse<lld::macho::LP64>() + 140144
4  lld                      0x0000000100fa3650 void lld::macho::writeResult<lld::macho::LP64>() + 272
5  lld                      0x0000000100f49610 void lld::elf::writeResult<llvm::object::ELFType<(llvm::support::endianness)0, true>>() + 196804
6  lld                      0x0000000100ca5b08 llvm::SymbolTableListTraits<llvm::Function>::removeNodeFromList(llvm::Function*) + 5372
7  lld                      0x0000000100ca54c8 llvm::SymbolTableListTraits<llvm::Function>::removeNodeFromList(llvm::Function*) + 3772
8  dyld                     0x0000000103e6d08c start + 520
clang++: error: unable to execute command: Segmentation fault: 11

**Comment by BertalanD** [comment]
The backtrace looks similar to a crash [previously reported](https://bugs.chromium.org/p/chromium/issues/detail?id=1372389) on the Chromium issue tracker. That issue was fixed in 82ca390062d1. Could you check if updating your Chromium checkout fixes the crash?

**Comment by jonathanshim** [comment]
Thanks, @BertalanD. 
Indeed it is the same bug and the new llvm version fixed it. You can resolve the issue.
