### ISSUE TITLE
Debian bullseye - can't find libraries (z3, grpc++) in stage 2

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#59097]
Recently, stage 2 on debian bullseye (amd64) is failing with:

```

-- flang project is disabled
CMake Warning at cmake/modules/FindZ3.cmake:116 (message):
  Failed to determine Z3 library version, defaulting to 0.0.0.
Call Stack (most recent call first):
  CMakeLists.txt:506 (find_package)


-- Could NOT find Z3: Found unsuitable version "0.0.0", but required is at least "4.7.1" (found Z3_LIBRARIES-NOTFOUND)
CMake Error at CMakeLists.txt:515 (message):
  LLVM_ENABLE_Z3_SOLVER cannot be enabled when Z3 is not available.

```

Enabling the debug `-DCMAKE_FIND_DEBUG_MODE=ON`
it is searching the libs in 
`/usr/lib/x86_64-pc-linux-gnu/`
while the lib is in 
`/usr/lib/x86_64-linux-gnu/`

de4364f1ecaa was ok

@MaskRay any idea what changed recently ?  thanks!

**Comment by sylvestre** [comment]
Log:
https://llvm-jenkins.debian.net/view/Debian%2011%20-%20bullseye/job/llvm-toolchain-bullseye-binaries/architecture=amd64,distribution=bullseye,label=amd64/392/console

**Comment by nickdesaulniers** [comment]
> Recently
> https://github.com/llvm/llvm-project/commit/de4364f1ecaa6a5d631cff036b8f31e02841e73d was ok

Was de4364f1ecaa6a5d631cff036b8f31e02841e73d the last known good revision? What's the first known bad revision? Can you bisect @sylvestre ?

**Comment by sylvestre** [comment]
Seems that it is caused by the cmake search is now 
`/usr/lib/x86_64-pc-linux-gnu/`
while libs are installed in:
`/usr/lib/x86_64-linux-gnu/`

**Comment by sylvestre** [comment]
I did and it is actually that these options on the packaging side have been removed during a merge...
my bad
```
	-DBUILTINS_CMAKE_ARGS="-DCMAKE_C_FLAGS=$(STAGE_1_CFLAGS);-DCMAKE_CXX_FLAGS=$(STAGE_1_CXXFLAGS);-DCMAKE_EXE_LINKER_FLAGS=$(STAGE_1_LDFLAGS);-DCMAKE_SHARED_LINKER_FLAGS=$(STAGE_1_LDFLAGS);-DCMAKE_MODULE_LINKER_FLAGS=$(STAGE_1_LDFLAGS);-DCMAKE_BUILD_TYPE=Release;-DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF" \
	-DRUNTIMES_CMAKE_ARGS="-DCMAKE_C_FLAGS=$(STAGE_1_CFLAGS);-DCMAKE_CXX_FLAGS=$(STAGE_1_CXXFLAGS);-DCMAKE_EXE_LINKER_FLAGS=$(STAGE_1_LDFLAGS);-DCMAKE_SHARED_LINKER_FLAGS=$(STAGE_1_LDFLAGS);-DCMAKE_MODULE_LINKER_FLAGS=$(STAGE_1_LDFLAGS);-DCMAKE_BUILD_TYPE=Release;-DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF" \
```
