### ISSUE TITLE
FixItHint: return -> co_return

### ISSUE THREAD

**Issue by hidva** [llvm/llvm-project#59094]
I'm currently doing a refactoring that automatically rewrites `future.then(callback)` to `callback(co_await future)`. After the refactor, there are a lot of `err_return_in_coroutine` errors. Could we add a `FixItHint` to `err_return_in_coroutine`?

I have implemented this `FixItHint` simply now, I am not very familiar with clang, the following patch may seem a bit naive.

```diff
-    Diag(Fn->FirstReturnLoc, diag::err_return_in_coroutine);
+    auto FixItRange = SourceRange(Fn->FirstReturnLoc, getLocForEndOfToken(Fn->FirstReturnLoc, 1));
+    Diag(Fn->FirstReturnLoc, diag::err_return_in_coroutine)
+            << FixItHint::CreateReplacement(FixItRange, "co_return");
```

**Comment by ChuanqiXu9** [comment]
There are additional works which seems not so meaningful for the general case. We need to verify `co_return expression` is valid before suggesting to replace `return expression` to `co_return expression`. Also it is not always the case that the `co_return` and `return` have similar semantics. For your use cases, I feel it is better to work on the transformer side.

**Comment by hidva** [comment]
Thanks.
