### ISSUE TITLE
[AArch64] Crash on function combineSVEReductionInt

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#59108]
* Unexpected element type for vector as the return type is `MVT::i1` for `@llvm.aarch64.sve.orv.nxv4i1`.

* A reduced case, https://gcc.godbolt.org/z/T61G7hb3P
```ll
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64"

define void @test() {
entry:
  %or = call i1 @llvm.aarch64.sve.orv.nxv4i1(<vscale x 4 x i1> zeroinitializer, <vscale x 4 x i1> zeroinitializer)
  br i1 %or, label %exit, label %vector.ph

vector.ph:                                        ; preds = %entry
  store volatile i32 0, ptr null, align 4
  br label %exit

exit:                                             ; preds = %vector.ph, %entry
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare i1 @llvm.aarch64.sve.orv.nxv4i1(<vscale x 4 x i1>, <vscale x 4 x i1>) 
```

**Comment by vfdff** [comment]
it works base on llvm9, so the case itself is ok. https://gcc.godbolt.org/z/sT9hfnzYY

**Comment by davemgreen** [comment]
Where did the `call i1 @llvm.aarch64.sve.orv.nxv4i1` intrinsics come from? It looks like an invalid intrinsic to me.

All the tests in tree are of wider vectors, not predicates. This would make sense for `orv` instructions:
```
call i32 @llvm.aarch64.sve.orv.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a)
```

**Comment by vfdff** [comment]
As the condition branch instrunction need **the type of condition** is **MVT::i1**, so I try to use the llvm.aarch64.sve.orv.nxv4i1 transform the type **<vscale x 4 x i1>**  into **i1**

**Comment by davemgreen** [comment]
If you want to reduce a nxv4i1 to a i1, could you use a `llvm.vector.reduce.or.nxv4i1`?
https://gcc.godbolt.org/z/sq6Mj3MbG

**Comment by vfdff** [comment]
Yes, thanks very much. so this issue  also should be closed as the invalid input.
