### ISSUE TITLE
Assertion failed: "List initialization must have initializer list as expression."

### ISSUE THREAD

**Issue by dcci** [llvm/llvm-project#59100]
```console
$ ./clang "-cc1" "-o" "/dev/null" -std=c++1y "-x" "c++"  pat.cpp
Assertion failed: ((!ListInitialization || (Exprs.size() == 1 && isa<InitListExpr>(Exprs[0]))) && "List initialization must have initializer list as expression."), function BuildCXXTypeConstructExpr, file SemaExprCXX.cpp, line 1457.
```

```console
$ cat pat.cpp
namespace std {
template <class _Tp> class vector {};
} // namespace std                                                                                                                        

template <typename T>
class Vector : public std::vector<T> {};

struct S {
  S();
  template <class Dummy> void f();
  const Vector<int> &g();
};

S::S() {
  f<int>();
}

template <class Dummy>
void S::f() {
  __attribute__((unused)) auto _ =
    decltype(g()){};
}
```

**Comment by dcci** [comment]
cc: @AaronBallman

**Comment by AaronBallman** [comment]
At first I thought this might be a duplicate of #58302 because the assertions happen in the "same" place (line numbers are different but that's not unexpected), however, they seem to be distinct cases. This bug report only asserts in C++14 mode (works fine in C++17 and C++20).

**Comment by AaronBallman** [comment]
> I am on vacation but @AaronBallman have you checked if we are getting a CXXTemporaryObjectExpr like the other case.

Yes, that is what's happening. There's one expression in the init list and it's a temporary object expr. I'll leave this one to you (and if you think it's the same as the other report, feel free to close one as a duplicate of the other). However, most importantly: go enjoy your vacation!

**Comment by dcci** [comment]
@shafik are you looking at this one, or you'd like me to look at? We're hitting this internally.

**Comment by shafik** [comment]
I reduced the reproducer slightly:

```cpp
class v {};

template <typename T>
class V : public v {};

using T = const V<int> &;

template <class D>
void f() {
    T{};
}

void z()  {
    f<int>();
}
```

This stops asserting on C++17 and above. It is interesting to note that although this is the same problem as https://github.com/llvm/llvm-project/issues/58302 we are hitting it via a different code path. Commit 1ae689c2b8759e4cb5bc9ff334b02c58752f2717 seems to indicate that we expect list initialization to sometimes not use `InitListExpr` and that `CXXTemporaryObjectExpr` may have some design issues. 

After stepping through the cases several times, I am pretty convinced the assert is not correct although it is hard to point to a specific reason why but we have two different cases of valid code that hit this assert and seem to generate valid ASTs.

**Comment by shafik** [comment]
PR: https://reviews.llvm.org/D138947

**Comment by dcci** [comment]
Fixed.
