### ISSUE TITLE
Clang-tidy: Allow wildcards in bugprone-reserved-identifier.AllowedIdentifiers

### ISSUE THREAD

**Issue by ke-kx** [llvm/llvm-project#59119]
Currently it doesn't seem to be possible to use wildecards in the `bugprone-reserved-identifier.AllowedIdentifiers` option for the [bugprone-reserved-identifier](https://clang.llvm.org/extra/clang-tidy/checks/bugprone/reserved-identifier.html) check.

This would be useful for avoiding false positives on functions prefixed with `__wrap` which are often used to mock functions in unit tests. 

See also:
* https://linux.die.net/man/1/ld --wrap option
* https://cmocka.org/talks/cmocka_unit_testing_and_mocking.pdf

**Comment by carlosgalvezp** [comment]
To clarify - are you getting these warnings on the mocking framework itself (third-party code), not on your own source code? To solve that problem, make sure you include the third-party code as system headers, then clang-tidy won't throw warnings in there.
