### ISSUE TITLE
When linked with LLD, static constructors are only executed if the .o is produced by LLC

### ISSUE THREAD

**Issue by SixthDot** [llvm/llvm-project#59145]
## description

When linked with LLD, static constructors and destructors are only executed if the _.o_ files are produced by LLC. If I use the C API then they are not.

This seems related to fact that _ld.bfd_ or _ld.gold_ handle correctly the `.ctors` while _ld.lld_ does not. Yet this is not clear why the problem does not happen when LLC is used, instead of the C API, to produce objects.

## System info

- linux x86_64
- LLVM13

## reproduction

- decompress the attached archive ([tc.tar.gz](https://github.com/llvm/llvm-project/files/10073120/tc.tar.gz))
  - the *.o file is produced using the C API (v13)
  - the *.ll file is produced using the C API (v13)
- check the paths in the shell script, those used are for Fedora
- `sh test.sh`

## output

```
LD.BFD+OBJ produced using the C API
called

LD.LLD+OBJ produced using the C API

LD.LLD+OBJ produced using LLC
called
```
## expected output

```
LD.BFD+OBJ produced using the C API
called

LD.LLD+OBJ produced using the C API
called

LD.LLD+OBJ produced using LLC
called
```

## notes

I'm opened to workarounds (maybe using `LLVMSetSection()` ?) as if even the bug is confirmed then fixed I'll not be in measure to use the fix before several months. Also explanations on what is the secret sauce added by LLC for the static ctors are welcome.

**Comment by dwblaikie** [comment]
might need more details - could you provide minimal IR/bitcode files, perhaps? Or other repro steps?

**Comment by SixthDot** [comment]
@dwblaikie, you can reproduce using this script

```bash
# get the compiler
if [ ! -f styx ] ; then
  curl -J -L -f -ostyx.tar "https://gitlab.com/styx-lang/styx/-/releases/v0.9.8/downloads/binaries/styx-0.9.8-0-linux-x86_64.tar"
  tar -xf ./styx.tar
fi

# A program that returns 0 if the static ctor `f` is run and 1 otherwise
SRC="unit temp;
var s32 r = 1; 
@constructor function f() { r = 0; } 
function main(): s32 { return r; }"

# produce obj and textual IR
echo $SRC > "temp.sx"
./styx temp.sx --be=obj
./styx temp.sx --be=ir

LIB_PATH="/usr/lib64"
DYN_LNK="/lib64/ld-linux-x86-64.so.2"
ARGS1="-L$LIB_PATH $LIB_PATH/crt1.o $LIB_PATH/crti.o .styx/temp.o $LIB_PATH/crtn.o -lc -dynamic-linker $DYN_LNK -o test"
ARGS2="-L$LIB_PATH $LIB_PATH/crt1.o $LIB_PATH/crti.o llc-temp.o $LIB_PATH/crtn.o -lc -dynamic-linker $DYN_LNK -o test"       

# link and run, return is 0, meaning static ctor is called
echo "LD.BFD, OBJ produced using the C API"
ld.bfd $ARGS1 && ./test echo $? && rm test
echo $?

# link and run, return is 1, meaning static ctor is not called
echo "LD.LLD, OBJ produced using the C API"
ld.lld $ARGS1 && ./test echo $? && rm test
echo $?

# emit object using LLC, link and run, return is 0, meaning static ctor is called
echo "LD.LLD, LL produced using the C API, OBJ produced using LLC"
llc .styx/temp.ll --filetype=obj -o llc-temp.o
ld.lld $ARGS2 && ./test && echo $? && rm test

```

**Comment by SixthDot** [comment]
@dwblaikie you can reproduce using this script

```bash
# get the compiler
if [ ! -f styx ] ; then
  curl -J -L -f -ostyx.tar "https://gitlab.com/styx-lang/styx/-/releases/v0.9.8/downloads/binaries/styx-0.9.8-0-linux-x86_64.tar"
  tar -xf ./styx.tar
fi

# A program that returns 0 if the static ctor `f` is run and 1 otherwise
SRC="unit temp;
var s32 r = 1; 
@constructor function f() { r = 0; } 
function main(): s32 { return r; }"

# produce obj and textual IR
echo $SRC > "temp.sx"
./styx temp.sx --be=obj
./styx temp.sx --be=ir

LIB_PATH="/usr/lib64"
DYN_LNK="/lib64/ld-linux-x86-64.so.2"
ARGS1="-L$LIB_PATH $LIB_PATH/crt1.o $LIB_PATH/crti.o .styx/temp.o $LIB_PATH/crtn.o -lc -dynamic-linker $DYN_LNK -o test"
ARGS2="-L$LIB_PATH $LIB_PATH/crt1.o $LIB_PATH/crti.o llc-temp.o $LIB_PATH/crtn.o -lc -dynamic-linker $DYN_LNK -o test"       

# link and run, return is 0, meaning static ctor is called
echo "LD.BFD, OBJ produced using the C API"
ld.bfd $ARGS1
./test
echo $?

# link and run, return is 1, meaning static ctor is not called
echo "LD.LLD, OBJ produced using the C API"
ld.lld $ARGS1 
./test
echo $?

# emit object using LLC, link and run, return is 0, meaning static ctor is called
echo "LD.LLD, LL produced using the C API, OBJ produced using LLC"
llc .styx/temp.ll --filetype=obj -o llc-temp.o
ld.lld $ARGS2 
./test 
echo $?
```

**Comment by MaskRay** [comment]
See https://maskray.me/blog/2021-11-07-init-ctors-init-array#ctors-to-.init_array-transition styx generates relocatable files with legacy `.ctors.*`. ld.lld doesn't implement `.ctors.*` to `.init_array` conversion. I mentioned a linker script using `OVERWRITE_SECTIONS` to work with prebuilt relocatable files. The right call is to fix styx.

**Comment by SixthDot** [comment]
can you explain me why and how LLC fixes this ? The last step of the scipt shows clearly that LLC does something particular.

**Comment by SixthDot** [comment]
It turns out that the C++ API allows to instruct programmatically to use `.ctors` and `.dtors`, that's why LLC does not exibit the problem as it's programmed in c++...
The C API does not have such an option, that should be an argument of `LLVMTargetMachineEmitToFile`.

**Comment by dwblaikie** [comment]
> It turns out that the C++ API allows to instruct programmatically to use `.ctors` and `.dtors`, that's why LLC does not exibit the problem as it's programmed in c++...
> The C API does not have such an option, that should be an argument of `LLVMTargetMachineEmitToFile`.

If LLC (& clang, presumably) defaults to .ctors/dtors, perhaps the C API should as well?

**Comment by SixthDot** [comment]
The more funny thing in the end is that it's not a LLD issue. It's a C API issue.
