### ISSUE TITLE
[Buildsystem]Downstream projects can't override CPack arguments

### ISSUE THREAD

**Issue by Naville** [llvm/llvm-project#59148]
[llvm/CMakeLists.txt](https://github.com/llvm/llvm-project/blob/a11cd0d94ed3cabf0998a0289aead05da94c86eb/llvm/CMakeLists.txt#L328)

This essentially overwrites the install directories the user passed in during configuration time?

We should add checks like we did with LLVM_VERSION_MAJOR

**Comment by Naville** [comment]
Overriding with cmake -C, still dont think this is a good practice though

**Comment by Naville** [comment]
Also, I feel like Windows installations should not override each other
Instead, there should be C:\ProgramFiles\LLVM\14.0.6 C:\ProgramFiles\LLVM\13.0.0 etc

**Comment by EugeneZelenko** [comment]
@Naville: Please elaborate.

**Comment by Naville** [comment]
Fixed in it 27c4b50

**Comment by EugeneZelenko** [comment]
@Naville: Thank you!
