### ISSUE TITLE
Backport zstd cmake module fixes to 15.x

### ISSUE THREAD

**Issue by brad0** [llvm/llvm-project#59144]
Please backport the zstd cmake module fixes to the 15.x branch.

56f94ede2af9a327e59fe84dbf8cbbb7bb1dfa79
e7fc7540daa9333f0be4f380fc9c619236d17f57
5279e6a7d677cdf4488883b77aacab911318100c

**Comment by thesamesam** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/56f94ede2af9a327e59fe84dbf8cbbb7bb1dfa79 https://github.com/llvm/llvm-project/commit/e7fc7540daa9333f0be4f380fc9c619236d17f57 https://github.com/llvm/llvm-project/commit/5279e6a7d677cdf4488883b77aacab911318100c
