### ISSUE TITLE
Confusing error reporting while parsing a nested pass pipeline

### ISSUE THREAD

**Issue by shabalind** [llvm/llvm-project#59151]
I'm currently working on a project that invokes an MLIR pass pipeline using Python bindings:
```python
mypm = pm.PassManager.parse(f"""builtin.module(
    mypass1,
    func.func(mypass2,mypass3)
)""")
```
Somewhat surprisingly this pass pipeline is not valid according to the pipeline parser, it tells me to add `,` at the end after `func.func(...)`. At the same time if you do add that comma, it errors as well since there is no valid pass name after the comma. 

As a workaround I added a dummy pass that does nothing just to make it happy:
```python
mypm = pm.PassManager.parse(f"""builtin.module(
    mypass1,
    func.func(mypass2,mypass3),
    dummy-do-nothing-pass
)""")
```
It would be great if this was not necessary in the first place, and parser accepted the initial snippet right away.

**Comment by boschmitt** [comment]
@River707 you can close this issue, the commit fixes it (Poor choice of wording on my part, but I was unsure how the info in the review process would land in the commit)

**Comment by shabalind** [comment]
@boschmitt Thanks for the fix!
