### ISSUE TITLE
Unable to find libclang: "the `libclang` shared library

### ISSUE THREAD

**Issue by hyper-self** [llvm/llvm-project#59159]
# apk info clang-dev
clang15-dev-15.0.5-r0 description:
A C language family front-end for LLVM (development files)

clang15-dev-15.0.5-r0 webpage:
https://llvm.org/

clang15-dev-15.0.5-r0 installed size:
21 MiB

# cat /etc/alpine-release
3.15.1

--- stderr
  thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib/libclang.so.15.0.5 could not be opened: Dynamic loading not supported"', /root/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/bindgen-0.60.1/src/lib.rs:2172:31

**Comment by tbaederr** [comment]
This seems unrelated to clang or llvm; the software you're using doesn't support dynamic loading. You should ask the developer of that software about this issue.
