### ISSUE TITLE
clang forbids empty return in non-void function for C89

### ISSUE THREAD

**Issue by Humm42** [llvm/llvm-project#59176]
In C89, non-void functions may have empty return statements.

```
$ cat a.c
f(){return;}
$ clang -c -std=c89 a.c
a.c:1:5: error: non-void function 'f' should return a value [-Wreturn-type]
f(){return;}
    ^
1 error generated.
```
https://godbolt.org/z/G361PK41r

See also [the same issue on Bugzilla](https://bugs.llvm.org/show_bug.cgi?id=12216).

**Comment by rymiel** [comment]
All bugzilla bugs were migrated over. You are refering to #12588, which probably makes this issue a duplicate

**Comment by Humm42** [comment]
I see; sorry for the noise.
