### ISSUE TITLE
[clang-doc] sqlite3 output format

### ISSUE THREAD

**Issue by mnesarco** [llvm/llvm-project#59191]
Hi Friends,

I am working on a documentation generator based on clang-doc and python. What I am doing is generating yaml output with clang-doc and then parsing it with python and generating an sqlite3 database.

The database contains all the information generated by clang-doc in a relational way. So any tool can be used to generate documentation from there or even to create an interactive index/explorer.

I think that this generation into an sqlite file can be done directly from clang-doc as another output format along with html, md and yaml.

I can add this to clang-doc if you are interested in having this built-in output format. I don't know if this kind of contributions are accepted or not or if embedding sqlite3 is not allowed.

**Comment by rickmark** [comment]
I'd love a `LLVM_ENABLE_YAMLDOC` flag that would output the YAML API

**Comment by mnesarco** [comment]
> I'd love a `LLVM_ENABLE_YAMLDOC` flag that would output the YAML API

Hi rickmark, what do you mean? clang-doc already generates YAML output out of the box.

**Comment by rickmark** [comment]
> > I'd love a `LLVM_ENABLE_YAMLDOC` flag that would output the YAML API
> 
> Hi rickmark, what do you mean? clang-doc already generates YAML output out of the box.

I created a different issue - what I meant was a way to enable the usage of `clang-doc` on the LLVM project itself like we do with doxygen and sphynx to produce YAML out

(making a LLVM_ENABLE_CLANGDOC=ON and LLVM_CLANGDOC_OUTPUT=yaml build settings)

**Comment by EugeneZelenko** [comment]
@mnesarco: Could you please elaborate?
