### ISSUE TITLE
clang: constexpr does not honor -fwrapv, leading to compilation error

### ISSUE THREAD

**Issue by markus-oberhumer** [llvm/llvm-project#59195]
Godbolt link: https://godbolt.org/z/8KhvbcWr6

Reproducible with clang-trunk

```console
$ clang++ -fwrapv -Wno-integer-overflow -c test.cpp
test.cpp:15:16: error: constexpr variable 'b2' must be initialized by a constant expression
```

```console
$ cat test.cpp
// compile with: clang++ -fwrapv -Wno-integer-overflow -c test.cpp
//
// extra rant: -Wno-integer-overflow should not be needed here!

#include <limits.h>

#define wrap_inc(x)     ((x) + 1 < (x))

constexpr int int_max = INT_MAX;

bool b0 = wrap_inc(int_max);
const bool b1 = wrap_inc(int_max);

// error: constexpr variable 'b2' must be initialized by a constant expression
constexpr bool b2 = wrap_inc(int_max);
```

**Comment by shafik** [comment]
We seem to be consistent with gcc in most cases although the `bool` case stands out, I believe that is a gcc bug b/c that case should be treated the same way, see: https://godbolt.org/z/ad3391Eh3

I believe command line options should not modify whether an expression is considered well-formed in a constant expression or not b/c this has wider impacts on portability due to use in templates and other scenarios that required constant expression such as support for variable length arrays as an extension. Although I will leave it open to allow for more feedback if others want to weigh in.

**Comment by jwakely** [comment]
> I believe command line options should not modify whether an expression is considered well-formed in a constant expression or not b/c this has wider impacts on portability

100% agreed

**Comment by jwakely** [comment]
Not the same. The standard says it's unspecified whether char is signed or unsigned. It doesn't say it's unspecified whether `INT_MAX+1` is valid.

**Comment by shafik** [comment]
[Unspecified behavior](https://github.com/llvm/llvm-project/issues/59195#issuecomment-1327798800) still results in a well-formed program:

> behavior, for a well-formed program construct and correct data, that depends on the implementation

Even though unspecified behavior is well-formed it is not portable and developers need to be aware of that and design accordingly.

[Undefined behavior](https://eel.is/c++draft/intro.defs#defns.undefined) is never well-formed. It is a runtime behavior and even though we have command line options to define the behavior at runtime [undefined behavior is not allowed in a constant expression](https://eel.is/c++draft/expr.const#5.8):

> An expression E is a [core constant expression](https://eel.is/c++draft/expr.const#def:expression,core_constant) unless the evaluation of E, following the rules of the abstract machine ([[intro.execution]](https://eel.is/c++draft/intro.execution)), would evaluate one of the following:

and includes the following bullet:

> an operation that would have undefined behavior as specified in [[intro]](https://eel.is/c++draft/intro) through [[cpp]](https://eel.is/c++draft/cpp), excluding [[dcl.attr.assume]](https://eel.is/c++draft/dcl.attr.assume);
