### ISSUE TITLE
clang-format-16 `AlignTrailingComments: Kind: Leave` moves comments

### ISSUE THREAD

**Issue by MartinsSmirnovs** [llvm/llvm-project#59203]
Given following `.clang-format` file:
```yaml
AlignTrailingComments:
  Kind: Leave

ColumnLimit: 0
```
And following `.cpp` source file:
```cpp
// comment 1

   // comment 2
// comment 3
```
I expect that `clang-format-16 foo.cpp` will not perform formatting, however, it does:
```console
$ clang-format-16 foo.cpp
// comment 1

     // comment 2
 // comment 3
```

`clang-format-16` version:
```console
$ clang-format-16 --version
Ubuntu clang-format version 16.0.0 (++20221123042319+910204cfbdf3-1~exp1~20221123042440.568)
```

**Comment by mairacanal** [comment]
Hi! Can I take this issue? I wrote a fix for it, and I intend to send it soon.

**Comment by EugeneZelenko** [comment]
@mairacanal: Sure. Just add yourself to assignees and link to Phabricator after you create patch review.

**Comment by mairacanal** [comment]
> @mairacanal: Sure. Just add yourself to assignees and link to Phabricator after you create patch review.

As it is my first contribution to LLVM, I believe that I'm not able to assign the issue to myself. I submitted the patch on Phabricator: https://reviews.llvm.org/D139029
