### ISSUE TITLE
llvm-objdump section header format does not match GNU objdump

### ISSUE THREAD

**Issue by emaste** [llvm/llvm-project#59204]
In FreeBSD we are planning to install llvm-objdump as `/usr/bin/objdump`. One third-party software failed when we tried building with this change, due to llvm-objdump's `-h` section header output having a different format.

GNU objdump:
```objdump
/usr/bin/true:     file format elf64-x86-64-freebsd

Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .interp       00000015  00000000000002a8  00000000000002a8  000002a8  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  1 .note.tag     00000048  00000000000002c0  00000000000002c0  000002c0  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  2 .dynsym       000000c0  0000000000000308  0000000000000308  00000308  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  3 .gnu.version  00000010  00000000000003c8  00000000000003c8  000003c8  2**1
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  4 .gnu.version_r 00000020  00000000000003d8  00000000000003d8  000003d8  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  5 .gnu.hash     00000024  00000000000003f8  00000000000003f8  000003f8  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  6 .hash         00000048  000000000000041c  000000000000041c  0000041c  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
...
```

llvm-objdump:
```objdump
/usr/bin/true:  file format elf64-x86-64

Sections:
Idx Name           Size     VMA              Type
  0                00000000 0000000000000000 
  1 .interp        00000015 00000000000002a8 DATA
  2 .note.tag      00000048 00000000000002c0 
  3 .dynsym        000000c0 0000000000000308 
  4 .gnu.version   00000010 00000000000003c8 
  5 .gnu.version_r 00000020 00000000000003d8 
  6 .gnu.hash      00000024 00000000000003f8 
...
```

See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=267854 and https://reviews.freebsd.org/D37445 for more detail from the FreeBSD build and code review.

**Comment by MaskRay** [comment]
I object to make changes to llvm-objdump in this area. These BFD specific flags don't fit into llvm-objdump's model.

The software seabios can migrate to readelf/llvm-readelf -S instead. https://github.com/MaskRay/seabios/tree/readelf https://mail.coreboot.org/hyperkitty/list/seabios@seabios.org/thread/KBHQU4OLW2THG5Q5F5X7EWTQDJHKNVYC/
I've personally pinged the patch series for 10 (if not more) times. @brad0 helped me ping them once but there is still no response. Perhaps you are kind enough to help ping them as well? :)

**Comment by emaste** [comment]
OK - I'll try to prod seabios upstream, and for the port for now we'll patch it to honour `${OBJDUMP}` and thus use GNU objdump.
