### ISSUE TITLE
[RISC-V, RVV, Vector, LLVM16] Turn off auto-vectorization

### ISSUE THREAD

**Issue by mp-17** [llvm/llvm-project#59239]
Hello everyone. I have just started using LLVM 16, and I noticed that the auto-vectorization is on by default.
How can I turn it off completely, to be sure that the scalar part of the compiled program will not be vectorized?

I tried with: 
`clang -march=rv64gcv -mllvm -scalable-vectorization=off ...`
But I still find vector code where it shouldn't be.

Thanks a lot,
Matteo

**Comment by topperc** [comment]
Have you tried -fno-vectorize ?

**Comment by topperc** [comment]
You can try -mno-implicit-float

**Comment by topperc** [comment]
Or -mllvm -riscv-v-vector-bits-min=0

**Comment by mp-17** [comment]
Boom, `-mllvm -riscv-v-vector-bits-min=0` worked, thanks for the tip! 
Is it normal that vector instructions are inserted even if `-scalable-vectorization=off`? From my understanding, we only have the scalable vectorization on by default with LLVM 16

**Comment by topperc** [comment]
We briefly had SLP vectorization enabled, but I think it is disabled currently.

We have fixed vector length vector support enabled to support attribute(vector_size).

I suspect what you’re seeing is the backend using fixed length vectors to merge adjacent scalar loads or stores. Does that match what you’re seeing?

**Comment by mp-17** [comment]
I am working with `typedef float fp32_complex_t  __attribute__((vector_size(b)));` vector variables to easily manage real and imaginary parts of complex numbers. 
I see that the compiler vectorizes the operations between variables of this type.

e.g.
```c
typedef float fp32_complex_t  __attribute__((vector_size(b)));

fp32_complex_t *foo = ...;
fp32_complex_t *bar = ...;
fp32_complex_t tmp = ...; 
fp32_complex_t cat = ...;

tmp    = foo[i] - bar[j];
foo[i] = foo[i] + bar[j];
bar[j] = fp32_cplx_mul(tmp, cat);
```

Becomes:

```
80000482: 57 70 71 cd  	vsetivli	zero, 2, e32, mf2, ta, ma
80000486: 07 e4 04 02  	vle32.v	v8, (s1)
8000048a: b3 87 e4 00  	add	a5, s1, a4
8000048e: 87 e4 07 02  	vle32.v	v9, (a5)
80000492: 57 95 84 0a  	vfsub.vv	v10, v8, v9
80000496: 57 14 94 02  	vfadd.vv	v8, v9, v8
8000049a: 27 e4 04 02  	vse32.v	v8, (s1)
8000049e: 57 11 a0 42  	vfmv.f.s	ft2, v10
800004a2: 57 f0 70 cd  	vsetivli	zero, 1, e32, mf2, ta, ma
800004a6: 57 b4 a0 3e  	vslidedown.vi	v8, v10, 1
800004aa: d7 11 80 42  	vfmv.f.s	ft3, v8
800004ae: 53 f2 11 10  	fmul.s	ft4, ft3, ft1
800004b2: 47 72 01 20  	fmsub.s	ft4, ft2, ft0, ft4
800004b6: d3 f1 01 10  	fmul.s	ft3, ft3, ft0
800004ba: 43 71 11 18  	fmadd.s	ft2, ft2, ft1, ft3
800004be: 57 70 71 cd  	vsetivli	zero, 2, e32, mf2, ta, ma
800004c2: 57 54 01 5e  	vfmv.v.f	v8, ft2
800004c6: 57 70 70 09  	vsetvli	zero, zero, e32, mf2, tu, ma
800004ca: 57 54 02 42  	vfmv.s.f	v8, ft4
800004ce: 27 e4 07 02  	vse32.v	v8, (a5)
```

It tries to vectorize with `vl == 2` the vector operations between complex numbers :-)

**Comment by topperc** [comment]
That’s not really vectorization. The code used vector_size so it asked for a vector.

With riscv-v-vector-bits-min=0 the compiler performs scalarization.

**Comment by mp-17** [comment]
I see! This is what you said with:
 
> We have fixed vector length vector support enabled to support attribute(vector_size).

Thanks a lot; everything's clear now.
