### ISSUE TITLE
OpenSSH: signature verification nondeterministic spurious failure

### ISSUE THREAD

**Issue by bwendling** [llvm/llvm-project#59242]
There appears to be a bug with `-fzero-call-used-regs` in OpenSSH

  https://bugzilla.mindrot.org/show_bug.cgi?id=3475

**Comment by thesamesam** [comment]
See also https://github.com/llvm/llvm-project/issues/57692.

**Comment by thesamesam** [comment]
cc @nikic

**Comment by nickdesaulniers** [comment]
https://github.com/llvm/llvm-project/issues/57692 has been closed. Is this fixed, or is there more than one bug with `-fzero-call-used-regs`?

**Comment by nikic** [comment]
The bugzilla comments indicate that this still occurs with 15.0.6 which should include the aforementioned patch, so this should be another issue.

**Comment by nickdesaulniers** [comment]
https://github.com/ClangBuiltLinux/linux/issues/1766 is another crash that seems to be with clang 15.0.6.

**Comment by bwendling** [comment]
It looks like https://reviews.llvm.org/D139679 fixes the OpenSSH issue.

**Comment by nickdesaulniers** [comment]
https://github.com/llvm/llvm-project/commit/14d4cddc5506fb0fd3c4ac556b4edd970aa151eb has landed. I would kindly ask the release folks if this warrants a 15.0.7 release; it's a pretty bad bug affecting both the Linux kernel and OpenSSL.

cc @tstellar

**Comment by nickdesaulniers** [comment]
cc @tru

**Comment by tru** [comment]
Hm, we have generally closed the book on 15.x and are planning to rev up 16.x release in the beginning of next year. This does seem bad though, so I am sure we can consider it.

Tom is out until early January and I suspect most release testers are as well, so I doubt we can get a release out before then. I'll note it down and talk to Tom about it when he's back online.

**Comment by tstellar** [comment]
This seems severe enough to me to warrant another release.  I think we could do one Tue Jan 10.

**Comment by thesamesam** [comment]
There's also https://github.com/llvm/llvm-project/issues/59792 which is quite serious.
