### ISSUE TITLE
ld64.lld: error: finalize: FIXME: thunk range overrun

### ISSUE THREAD

**Issue by glandium** [llvm/llvm-project#59259]
When building some recent revisions of the Firefox source code on arm64 mac using lld, we're getting this `thunk range overrun` message. I've [recently increased the slop](https://reviews.llvm.org/D138174) after it happened a few times, but this reoccurred after a while even with the new value.

A (unfortunately large) reproducer can be found at https://drive.google.com/file/d/1VXF0FzHEg5baosH8uYs9jPZ2B8ggPekb/view?usp=sharing. The `command` file in there contains the `clang` invocation that reproduces the problem, assuming `SDKROOT` is set to the location of the SDK (in case it matters, we're using the 11.3 SDK).

Cc: @llvm/issue-subscribers-lld-macho

**Comment by int3** [comment]
Hmm, the reproducer doesn't trigger the message for me (even when I bump down the slop factor to 128. I'm using the XCode 14 SDK, but I doubt it matters. Could you generate a linker-only reproducer using LLD's `--reproduce` option?

**Comment by glandium** [comment]
I can confirm it doesn't reproduce with current trunk, but it does reproduce from trunk from when I opened the issue. I'm going to bisect to find out why.

**Comment by glandium** [comment]
This was fixed by 6736bce6db5fe15bcb765b976c99fff34500d1eb

**Comment by glandium** [comment]
Can you reopen? The underlying issue is still there, and we reproduced again with today's trunk. I can provide a new testcase based on that if necessary.

**Comment by int3** [comment]
New test case would be helpful!

**Comment by glandium** [comment]
FWIW, this is happening more and more frequently.
