### ISSUE TITLE
Target "cxx_static" requires the language dialect "CXX20" Occurs in version 15.0.4

### ISSUE THREAD

**Issue by beijishiqidu** [llvm/llvm-project#59267]
**The error log is below:**

```console
CMake Error in /build/llvm-project-llvmorg-15.0.4/libcxx/src/CMakeLists.txt:
  Target "cxx_experimental" requires the language dialect "CXX20" , but CMake
  does not know the compile flags to use to enable it.

CMake Error in /build/llvm-project-llvmorg-15.0.4/libcxx/src/CMakeLists.txt:
  Target "cxx_static" requires the language dialect "CXX20" , but CMake does
  not know the compile flags to use to enable it.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**The following are the commands for building**
```shell
cmake -S ../llvm-project-llvmorg-15.0.4/llvm -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/build/target/llvm-15.0.1 -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" -DLLVM_INSTALL_UTILS=ON

ninja -j8 & ninja install

cmake ../llvm-project-llvmorg-15.0.4/compiler-rt -G Ninja -DLLVM_CONFIG_PATH=/build/target/llvm-15.0.1/bin/llvm-config -DCMAKE_INSTALL_PREFIX=/build/llvm-15.0.1-compile-rt/ -DLLVM_DIR=/build/build/ -DClang_DIR=/build/build/

ninja -j8 & ninja install
```

**Also, I tried the 12.0.1 build on my environment, and the results were good.**

**Comment by philnik777** [comment]
Which CMake version are you using? You probably have to upgrade to a version that knows about C++20.

**Comment by beijishiqidu** [comment]
> Which CMake version are you using? You probably have to upgrade to a version that knows about C++20.

Yes, I have upgrade Cmake to 3.20.5, and also upgrade gcc to 10.3.0

when compile the compile-rt module, I have faced anther error

```shell
export PATH=/usr1/ckbuild/gcc/bin:$PATH
export LD_LIBRARY_PATH=/usr1/ckbuild/isl/lib:/usr1/ckbuild/gmp/lib:/usr1/ckbuild/mpc/lib:/usr1/ckbuild/mpfr/lib:/usr1/ckbuild/gcc/lib:/usr1/ckbuild/gcc/lib64:/usr/local/lib64:$LD_LIBRARY_PATH

cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

gcc --version
gcc (GCC) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

mkdir -p /build/llvm-15.0.4/
mkdir -p /build/llvm/build
cd /build/llvm/build
/build/cmake/cmake-3.20.5-linux-aarch64/bin/cmake -DCMAKE_CXX_COMPILER='g++' -DCMAKE_C_COMPILER='gcc' -S ../llvm-project-llvmorg-15.0.4/llvm -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/build/llvm-15.0.4/ -DLLVM_ENABLE_PROJECTS="clang"

ninja -j32 && ninja install


mkdir -p /build/llvm-15.0.1-compile-rt/
mkdir -p /build/llvm/compile-rt-build/
cd /build/llvm/compile-rt-build/
/build/cmake/cmake-3.20.5-linux-aarch64/bin/cmake -DCMAKE_CXX_COMPILER='g++' -DCMAKE_C_COMPILER='gcc' ../llvm-project-llvmorg-15.0.4/compiler-rt -G Ninja -DLLVM_CONFIG_PATH=/build/llvm-15.0.4/bin/llvm-config -DCMAKE_INSTALL_PREFIX=/build/llvm-15.0.1-compile-rt/ -DLLVM_DIR=/build/llvm/build/ -DClang_DIR=/build/llvm/build/ -DLIBCXX_ENABLE_SHARED=ON

ninja -j32 && ninja install
```

But I face some error message below this

FAILED: libcxx/src/CMakeFiles/cxx_static.dir/utility.cpp.o
/usr1/ckbuild/gcc/bin/g++ -DLIBCXX_BUILDING_LIBCXXABI -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_DISABLE_NEW_DELETE_DEFINITIONS -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS="" -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/build/llvm/llvm-project-llvmorg-15.0.4/libcxx/src -Iinclude/c++/v1 -I/build/llvm/llvm-project-llvmorg-15.0.4/libcxxabi/include -march=armv8-a -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wimplicit-fallthrough -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -fdata-sections -O3  -fPIC -nostdinc++ -fvisibility-inlines-hidden -Wall -Wextra -W -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wextra-semi -Wundef -Wformat-nonliteral -Wno-attributes -Wno-literal-suffix -Wno-c++14-compat -Wno-noexcept-type -Wno-suggest-override -Wno-error -fno-exceptions -std=c++2a -MD -MT libcxx/src/CMakeFiles/cxx_static.dir/utility.cpp.o -MF libcxx/src/CMakeFiles/cxx_static.dir/utility.cpp.o.d -o libcxx/src/CMakeFiles/cxx_static.dir/utility.cpp.o -c /build/llvm/llvm-project-llvmorg-15.0.4/libcxx/src/utility.cpp
In file included from include/c++/v1/__compare/strong_order.h:12,
                 from include/c++/v1/__compare/weak_order.h:14,
                 from include/c++/v1/__compare/partial_order.h:14,
                 from include/c++/v1/__compare/compare_partial_order_fallback.h:13,
                 from include/c++/v1/compare:145,
                 from include/c++/v1/utility:251,
                 from /build/llvm/llvm-project-llvmorg-15.0.4/libcxx/src/utility.cpp:9:
include/c++/v1/__bit/bit_cast.h: In function ‘constexpr _ToType std::__Fuzzer::bit_cast(const _FromType&)’:
include/c++/v1/__bit/bit_cast.h:29:36: error: expected primary-expression before ‘,’ token
   29 |   return __builtin_bit_cast(_ToType, __from);
      |                                    ^
[809/856] Building CXX object libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o
FAILED: libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o
/usr1/ckbuild/gcc/bin/g++ -DLIBCXX_BUILDING_LIBCXXABI -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_DISABLE_NEW_DELETE_DEFINITIONS -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS="" -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/build/llvm/llvm-project-llvmorg-15.0.4/libcxx/src -Iinclude/c++/v1 -I/build/llvm/llvm-project-llvmorg-15.0.4/libcxxabi/include -march=armv8-a -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wimplicit-fallthrough -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -fdata-sections -O3  -fPIC -nostdinc++ -fvisibility-inlines-hidden -Wall -Wextra -W -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wextra-semi -Wundef -Wformat-nonliteral -Wno-attributes -Wno-literal-suffix -Wno-c++14-compat -Wno-noexcept-type -Wno-suggest-override -Wno-error -fno-exceptions -std=c++2a -MD -MT libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o -MF libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o.d -o libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o -c /build/llvm/llvm-project-llvmorg-15.0.4/libcxx/src/charconv.cpp
In file included from include/c++/v1/__functional/operations.h:14,
                 from /build/llvm/llvm-project-llvmorg-15.0.4/libcxx/src/include/to_chars_floating_point.h:26,
                 from /build/llvm/llvm-project-llvmorg-15.0.4/libcxx/src/charconv.cpp:12:
include/c++/v1/__functional/binary_function.h:45:27: warning: ‘template<class _Arg1, class _Arg2, class _Result> struct std::__Fuzzer::binary_function’ is deprecated [-Wdeprecated-declarations]


--END--

**Comment by beijishiqidu** [comment]
Actually, I need the complie-rt module, So I found another way to solve the problem.
To use this option `-DLLVM_ENABLE_RUNTIMES="compiler-rt"`

the whole command is:

```shell
/build/cmake/cmake-3.20.5-linux-aarch64/bin/cmake -DCMAKE_CXX_COMPILER='g++' -DCMAKE_C_COMPILER='gcc' -S ../llvm-project-llvmorg-15.0.4/llvm -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/build/ck-llvm-15.0.4/ -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_ENABLE_RUNTIMES="compiler-rt"
```

@philnik777 Thank you, friend;
