### ISSUE TITLE
Do not set `errno` in libc internal code

### ISSUE THREAD

**Issue by sivachandra** [llvm/llvm-project#59278]
Some parts of libc internal code in `src/__support` and elsewhere set `errno` on error. Internal code should not set `errno` but rather return the error values. Setting `errno` should be done only in the implementations of the public libc functions. This will also make the solution to address #59276 simpler.

**Comment by michaelrj-google** [comment]
The last piece of this is fixed with this patch: https://reviews.llvm.org/D144597
