### ISSUE TITLE
Severe memory usage regression since "[clang] Instantiate concepts with sugared template arguments"

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#59271]
CC @mizvekov @erichkeane @AaronBallman

Since commit b8064374b217db061213c561ec8f3376681ff9c8, "[clang] Instantiate concepts with sugared template arguments", Clang uses a lot more memory (and runs much slower) when compiling some C++ sources.

Previously, the libcxx testsuite ran successfully on Windows on GitHub Actions runners (2 cores, 7 GB of RAM), now after this, at least a handful of testcases fail, running out of memory when compiling them. The libcxx pre-merge CI (which is absolutely central to libcxx development) currently runs with existing stable releases of Clang on Windows - it's not known if they would run successfully with the very latest Clang on the runners used there.

Attached is the preprocessed source of one testcase that runs out of memory: [ranges_merge_preproc.zip](https://github.com/llvm/llvm-project/files/10127365/ranges_merge_preproc.zip)

On Linux, when compiled with Clang 59f0827e2cf3755834620e7e0b6d946832440f80 (the commit preceding b8064374b217db061213c561ec8f3376681ff9c8):
```console
$ /usr/bin/time -v clang -target x86_64-windows-gnu -w -c ranges_merge_preproc.cpp -std=c++2b
[...]
        User time (seconds): 10.21
        System time (seconds): 0.31
[...]
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.53
[...]
        Maximum resident set size (kbytes): 295716
[...]
```

When compiled with Clang b8064374b217db061213c561ec8f3376681ff9c8:
```console
$ /usr/bin/time -v clang -target x86_64-windows-gnu -w -c ranges_merge_preproc.cpp -std=c++2b
[...]
        User time (seconds): 37.39
        System time (seconds): 2.04
[...]
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:39.46
[...]
        Maximum resident set size (kbytes): 1605712
[...]
```
The memory usage rises from ~288 MB to ~1568 MB, and runtime goes from 10 seconds to 39 seconds.

On Windows, when timed with https://github.com/sgraham/tim. Before:
```console
> tim clang++.exe -w -c ranges_merge_preproc.cpp -std=c++2b

peak memory: 210.67MB
real: 0m5.796s
qpc: 5807460us
```
After:
```console
> tim clang++.exe -w -c ranges_merge_preproc.cpp -std=c++2b

peak memory: 1570.73MB
real: 0m19.125s
qpc: 19137796us
```

So the memory usage rises from ~210 MB to ~1570 MB, and runtime goes from 6 seconds to 19 seconds.

**Comment by mstorsjo** [comment]
Also CC @ldionne, as it might be relevant to know about this and the effect it has on being able to run the libcxx tests.

**Comment by AaronBallman** [comment]
> The memory usage rises from ~288 MB to ~1568 MB, and runtime goes from 10 seconds to 39 seconds.

Oof, that's not a reasonable regression IMO. Every time we increase memory usage (even by much smaller increments), we reduce the max template instantiation depth because of the extra overhead. Such a drastic increase in memory usage is likely to impact more than just performance of non-test code.

@mizvekov, do you think you'll be able to look into this relatively soon (before the Clang 16 branch which is roughly at the end of this year)? If not, I think it's reasonable to explore reverting the commit, but given that it's been in the tree for over a month, that might require nontrivial effort.

**Comment by mizvekov** [comment]
Yeah, I will be able to take a look before the llvm-16 branch of date.

**Comment by erichkeane** [comment]
I think this amount of memory usage is unacceptable unfortunately.  If  this is something that cannot be fixed (or at least SEVERELY alleviated) by the branch date, we need to revert.  A regression like that cannot be allowed to make the release.

**Comment by mstorsjo** [comment]
> Yeah, I will be able to take a look before the llvm-16 branch of date.

Any progress on this? (I haven't re-measured the memory usage recently.) If not, I think we need to start looking into our alternatives...

**Comment by AaronBallman** [comment]
The branch date for Clang 16 is approaching (approx Jan 24) and this needs to be resolved before we branch for the release. If @mizvekov (or someone else) doesn't have a solution by Jan 13, @erichkeane and/or I will start to revert the problematic commits as code owners.

**Comment by erichkeane** [comment]
The troublesome commit has been reverted in 12cb1cb3720de8d164196010123ce1a8901d8122

**Comment by mstorsjo** [comment]
> The troublesome commit has been reverted in [12cb1cb](https://github.com/llvm/llvm-project/commit/12cb1cb3720de8d164196010123ce1a8901d8122)

Thanks! I’m starting a new test build now to see if the libcxx testsuite passes in that environment again, or if there are other similar issues that have piled up meanwhile - I’ll let you know how it fares.

**Comment by mstorsjo** [comment]
I would conclude that this issue is gone now, with that commit reverted. Thanks!

Overall, the libcxx testsuite now still runs successfully on github actions runners like it did before.

I did try running the same testsuite with clang built in i386 mode though, and there I ran into one single test which fails (running out of memory) - libcxx's `std/algorithms/alg.modifying.operations/alg.transform/ranges.transform.pass.cpp` test. The memory usage issue here isn't a (significant) regression though; compiling that testcase (the current version) used to take 2.7 GB of memory with Clang 15.0, while it now takes 2.9 GB with current git main - in either case it's too large to be built with a 32 bit process. So that's not a Clang issue, but more of a question of those testcases being big.

**Comment by alexfh** [comment]
Unfortunately, the revert of b8064374b217db061213c561ec8f3376681ff9c8 causes compilation errors in (IIUC, valid) code.  This is one example I reduced from https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/stringpiece_8h_source.html and some code using it: https://gcc.godbolt.org/z/W5x1s9KbK

More details and discussion here: https://reviews.llvm.org/rG12cb1cb3720de8d164196010123ce1a8901d8122#1167950

**Comment by mizvekov** [comment]
I am reopening since the original patch is up for relanding: https://github.com/llvm/llvm-project/pull/101782

It fixes the performance regression reported here, it was only a satisfaction cache indexing problem.
