### ISSUE TITLE
[C++20 modules] Preprocess module file

### ISSUE THREAD

**Issue by Arthapz** [llvm/llvm-project#59287]
Hi,
i'm trying to preprocess a module file (to parse the imports in waiting for p1689 implementation), working on [XMake](https://github.com/xmake-io/xmake/pull/3122) C++20 modules support) with `-E` flag, but when i'm enabling `-std=c++20`, Clang try to resolve import; (which can't be done at this stage), is this a bug or is there an alternative way?

```console
[  0%]: generating.cxx.module.deps build/include/stormkit/core/Configure.mpp
glm /home/arthapz/.xmake/packages/g/glm/0.9.9+8/274f33e70c12413283cc256b6f0574e0/include
fmt /home/arthapz/.xmake/packages/f/fmt/9.1.0/6b418c00a9f24c389215064874fdaf71/include
/usr/sbin/clang -Istd-modules/modules -I/home/arthapz/.xmake/packages/g/glm/0.9.9+8/274f33e70c12413283cc256b6f0574e0/include -I/home/arthapz/.xmake/packages/f/fmt/9.1.0/6b418c00a9f24c389215064874fdaf71/include -DSTORMKIT_BUILD -DSTORMKIT_ASSERT=0 -DGLM_FORCE_RADIANS -DGLM_FORCE_DEPTH_ZERO_TO_ONE -std=c++20 -E -x c++ build/include/stormkit/core/Configure.mpp -o build/.gens/stormkit-core/linux/x86_64/release/rules/modules/cache/build/include/stormkit/core/Configure.mpp.i
build/include/stormkit/core/Configure.mpp:7:8: fatal error: module 'std' not found
import std;
~~~~~~~^~~
1 error generated.
```

**Comment by iains** [comment]
the behaviour you see is intentional (that a missing import is an error).

However, it is also recognised that this is a problem for dependency discovery - and is under discussion between various tooling folks as to how to fix it.

( I realise this is not an answer to the posted bug, but it is the status at present )

**Comment by ChuanqiXu9** [comment]
This should be a bug. And if I understand things right, https://reviews.llvm.org/D137526 will fix this.
