### ISSUE TITLE
InstCombine: incorrect copysign formation

### ISSUE THREAD

**Issue by nunoplopes** [llvm/llvm-project#59280]
Alive2 reports a bug in the following transformation from `Transforms/InstCombine/select.ll`:
```llvm
define float @copysign1(float %x) {
  %i = bitcast float %x to i32
  %ispos = icmp sgt i32 %i, 4294967295
  %r = select i1 %ispos, float 1.000000, float -1.000000
  ret float %r
}
=>
define float @copysign1(float %x) {
  %r = copysign float 1.000000, %x, exceptions=ignore
  ret float %r
}
Transformation doesn't verify!

ERROR: Value mismatch

Example:
float %x = #xff800008 (NaN)

Source:
i32 %i = #xff800008 (4286578696, -8388600)
i1 %ispos = #x0 (0)
float %r = #xbf800000 (-1)

Target:
float %r = #x3f800000 (1)
Source value: #xbf800000 (-1)
Target value: #x3f800000 (1)
```

**Comment by nunoplopes** [comment]
cc @rotateright

**Comment by rotateright** [comment]
I'm not following. The sign of "ff800008" is negative, so copysign should transfer that bit to its result value, but Alive2 is saying the bit is still clear in the target?

**Comment by nunoplopes** [comment]
the 2nd argument of copysign is NaN. And I found in some man page (https://www3.physnet.uni-hamburg.de/physnet/Tru64-Unix/HTML/MAN/MAN3/0869____.HTM) this text:
> IEEE 754 requires copysign(x,NaN) and copysignf(x,NaN) to return +x or -x.

Hence I implemented the semantics as non-deterministic choice between -x/+x.
But let me know if you want to remove this behavior. I guess it's related with https://github.com/llvm/llvm-project/issues/59279

**Comment by rotateright** [comment]
I don't think there's any ambiguity in IEEE-754 2008, section 5.5.1 at least:
1. "copySign(x, y) copies a floating-point operand x to a destination in the same format as x, but with the sign bit of y."
2. "The operations treat floating-point numbers and NaNs alike, and signal no exception."

So yes, I'd remove the non-determinism and say this example is ok as-is. We may need to check for more "nnan" to reconcile some of the other tests.

**Comment by nunoplopes** [comment]
Alright, I've changed the semantics in Alive2. Will rerun the tests now and report back if there's any failure.
Thanks!
