### ISSUE TITLE
clangd does not recognise gcc compilation flags

### ISSUE THREAD

**Issue by drakari7** [llvm/llvm-project#59283]
Using clangd as a language server protocol in neovim. It normally does a fairly good job of delivering correct diagnostics. However, it cannot recognise these 2 compilation options.

```
1. Unknown argument: '-ftrack-macro-expansion=1'
2. Unknown argument: '-mno-avx256-split-unaligned-load'
```

Any ideas why this might be? I can see that the first option is specified on gnu's website https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html .

**Comment by kadircet** [comment]
Because clangd uses `clang` infra not `gcc`. You can use clangd's config mechanism to [remove](https://clangd.llvm.org/config#remove) compiler flags that aren't supported by clang.
