### ISSUE TITLE
'+d16' is not a recognized feature for this target /  SIGILL

### ISSUE THREAD

**Issue by kwizart** [llvm/llvm-project#59286]
When running glxgears on ARM device (Tegra20) that lacks neon (despite been armv7-a), I'm experiencing the following message followed by a SIGILL:

`'+d16' is not a recognized feature for this target (ignoring feature).`

This error occurs since some time already (it worked at some point , but it's hard to tell when it failed again).
This also probably has to do with triplet assumptions on ARM. (running on the Fedora 36 context where llvm is set to armv7l-redhat-linux-gnueabihf )

Also to note that when running on gdb, I have an additonal message:

`warning: JITed object file architecture armv7 is not compatible with target architecture armv3m.`

**Comment by DavidSpickett** [comment]
> warning: JITed object file architecture armv7 is not compatible with target architecture armv3m.

Do you run any commands to get this or does it just come up when you attach? If you can provide the full output that would be useful. Might be a clue, I can find out from one of my colleagues where that is coming from.

**Comment by kwizart** [comment]
>Can you confirm where the SIGILL happens? You can just paste the disassembly here we can figure out what the encoding is. 
Once the SIGILL is emit, I cannot do a backtrace and see this message:
`Backtrace stopped: previous frame identical to this frame(corrupt stack?).`
I cannot disassemble anything then...
>Maybe a NEON instruction is being used.
I would assume that.

> Do you run any commands to get this or does it just come up when you attach?
Just running : "LIBGL_ALWAYS_SOFTWARE=1 gdb glxgears"  shows:

LIBGL_ALWAYS_SOFTWARE=1 gdb glxgears
```
GNU gdb (GDB) Fedora 12.1-2.fc36
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "armv7hl-redhat-linux-gnueabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from glxgears...

This GDB supports auto-downloading debuginfo from the following URLs:
https://debuginfod.fedoraproject.org/ 
Enable debuginfod for this session? (y or [n]) n
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
Reading symbols from .gnu_debugdata for /usr/bin/glxgears...
(No debugging symbols found in .gnu_debugdata for /usr/bin/glxgears)
Missing separate debuginfos, use: dnf debuginfo-install glx-utils-8.4.0-13.20210504git0f9e7d9.fc36.armv7hl
(gdb) run
Starting program: /usr/bin/glxgears 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
[New Thread 0xaf63f3a0 (LWP 2033)]
[New Thread 0xaecff3a0 (LWP 2034)]
[New Thread 0xae2ff3a0 (LWP 2035)]
[New Thread 0xad8ff3a0 (LWP 2036)]
[New Thread 0xacfbd3a0 (LWP 2037)]
'+d16' is not a recognized feature for this target (ignoring feature)
warning: JITed object file architecture armv7 is not compatible with target architecture armv3m.
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
warning: JITed object file architecture armv7 is not compatible with target architecture armv3m.
'+d16' is not a recognized feature for this target (ignoring feature)
warning: JITed object file architecture armv7 is not compatible with target architecture armv3m.

Thread 1 "glxgears" received signal SIGILL, Illegal instruction.
0xb6ff15f0 in ?? ()
(gdb) bt
#0  0xb6ff15f0 in ?? ()
#1  0xfffffffe in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?
```

**Comment by kwizart** [comment]
I'm indeed suspecting a neon usage, but that would be too simple.
At least I'm trying this change...
https://github.com/llvm/llvm-project/commit/2d8dc7f2e5c0b035fcb363ec0ec8f23459db9e2e

**Comment by kwizart** [comment]
(llvm still compiling).

Interesting is that I've managed to workaround the issue by using DRAW_USE_LLVM=0  LIBGL_ALWAYS_SOFTWARE=1 with glmark2
https://docs.mesa3d.org/envvars.html
But then I have a score of "5".

**Comment by efriedma-quic** [comment]
For the "'+d16' is not a recognized feature" warning, LLVM was changed to remove the "d16" feature in https://reviews.llvm.org/D60691 because it didn't compose correctly with other features.  I guess that might cause a crash?

**Comment by efriedma-quic** [comment]
It looks like maybe there's a leftover "d16" from D60691; see https://github.com/llvm/llvm-project/blob/a74c5707be279bdddb51fe49aa9383c1ddc99fbe/llvm/lib/Support/Host.cpp#L1792

**Comment by DavidSpickett** [comment]
https://reviews.llvm.org/D139304 to fix that part.

It could be that before we were adding `d16` and that made us use vfp, now that it's not recognised it's taking the default which is NEON for armv7-a (so it makes sense you'd try https://github.com/llvm/llvm-project/commit/2d8dc7f2e5c0b035fcb363ec0ec8f23459db9e2e).

**Comment by kwizart** [comment]
Test result: This is a good way forward as the previous messages with 
`'+d16' is not a recognized feature for this target (ignoring feature)`
But the SIGILL is still present.

Maybe I will have to rebuild mesa with this new version of llvm... (in progress).

**Comment by kwizart** [comment]
SIGILL still persist after mesa rebuilt...

**Comment by DavidSpickett** [comment]
We're need more information here.

* At what llvm/mesa version did this last work?
* What options is mesa passing to llvm?
* What source is mesa passing to llvm?

**Comment by kwizart** [comment]
> *    At what llvm/mesa version did this last work?
Hard to tell, I think it could be broken for 2/3 years, worked for one year before that.
But not really sure.

>  *    What options is mesa passing to llvm?
>  *   What source is mesa passing to llvm?
Not sure to understand the question right. 
This is llvm-14.0.5 / mesa-22.2.4 (with grate-driver patches, but theses are unrelated to llvmpipe usage).
Right now I'm compiling with clang (that I've not yet rebuilt with the llvm change... in progress).

**Comment by efriedma-quic** [comment]
LLVM developers aren't really familiar with Mesa, so if the reproduction steps involve "run Mesa", nobody here is really going to be able to understand what's happening.

If you don't know how to extract a testcase from Mesa, you should get in touch with Mesa developers. (https://docs.mesa3d.org/bugs.html)

**Comment by kwizart** [comment]
The reproducer is just to run " LIBGL_ALWAYS_SOFTWARE=1 glxgears" on any device lacking neon.
If not having this device at hands, it should be reproducible using an ARM virtual machine and filtering neon cpu capability (I know if work on x86, never tried on arm, I will).

But I guess you mean a simple reproducer that would narrow the exact case for llvm ?...

The problem I'm facing with this bug is that the backtrace doesn't work. So maybe I should find a way to have a "forth trace" like printing any function that the codepath enter until the SIGILL is encountered.

FYI, I've tried to debug with valgrind and gdb, but then I'm using some amount of CMA memory and this debug case seems to exhaust CMA memory very easily. (the device only has 512M of RAM).

Reported to mesa upstream at https://gitlab.freedesktop.org/mesa/mesa/-/issues/7868

Thanks for your hints.

**Comment by kwizart** [comment]
This commit is interesting as it's probably a time where one has managed to disable neon on mesa llvmpipe
https://gitlab.freedesktop.org/mesa/mesa/-/commit/e983a975c6843c307380d7caa083eee89e02bd3c

Now I wonder with the "-neon alone is not sufficient to disable emission of NEON instructions" that with current LLVM others "keywords" needs to be also disabled along to fully disable "neon" ?

**Comment by efriedma-quic** [comment]
Not sure what it's referring to about the features.  At least in current versions of LLVM, "-neon" should implicitly disable "crypto".  And "-vfp2" should implicitly disable both "neon" and "crypto".  (I can't rule out the possibility of bugs, of course.)

It is right that the armv7 target triples imply NEON by default; that default can be overridden by explicitly specifying "-mfpu" to clang (or the equivalent in the LLVM API).  See #30190 for further discussion.

**Comment by kwizart** [comment]
Fedora default to gcc with theses flags on armhfp " -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard"
vfpv3-d16 can be assumed to be enabled by default on Fedora (at least, maybe not on armv6 rpi based distros).
So I don't get what vfp2 stands for in llvm and why it is disabled in mesa ? (question for Lubomir, trying to ping on gitlab ticket).

Also I wonder where all theses features are defined in llvm, because maybe some other assumptions are made above neon that cannot be assumed on the tegra20 device ?

**Comment by efriedma-quic** [comment]
Feature flags are generated from llvm/lib/Target/ARM/ARM.td

Before 760df47b / ddf5e86c, disabling "vfp2" would have disabled all floating-point instructions, I think?  I don't think it does now, since the rewrite of the VFP feature flags.

If you have a target that implies NEON, and need to get to vfpv3-d16 from that, specifying "-d32" should disable all the relevant target features.

**Comment by kwizart** [comment]
Fish caught !

glmark2 xorg with llvmpipe on Tegra20 score: 8

I've added +fp64 along -d32 as it's mentioned here:
https://github.com/llvm/llvm-project/commit/760df47b778a530e9368a4b8706940ba103d57ba#diff-a3e21ffe48a032428ba55b3c57e7318c3712c645497a68f9f59aa50f2003a660R202-R203

Preparing a patch for mesa, this bug can be closed.
Thanks for the help with this issue !

**Comment by kwizart** [comment]
Patch submitted for gitlab https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/20766

Still one question, llvmpipe uses llvm::sys::getHostCPUFeatures, that is supposed to use cpuid. But why this isn't automatically detected (on ARM and others arches) ? I wonder if newer llvm could have improved facility to detect various options. (unless it imply catching SIGILL or any other kernel mode register to detect the feature)...

I'm also wondering about a sane default with current llvm wrt soft-float ABI...

**Comment by efriedma-quic** [comment]
I think the issue is the "armv7" triple; LLVM assumes "armv7" implies NEON, and getHostCPUFeatures() currently doesn't try to override that even if it doesn't detect NEON support.  If you used an "arm" or "armv6" triple, getHostCPUFeatures() would detect the right features, I think.

hardfloat vs softfloat ABI is separate from the architecture version.
