### ISSUE TITLE
[SOLVED][BUG] Template return type requirement

### ISSUE THREAD

**Issue by IamLupo** [llvm/llvm-project#59298]
Today playing with macOS compiling and Clang 9.0. And apparently I noticed a bug in it.

Normally when you create a template like this:
`example.cpp`

```cpp
template<typename T>
void execute(T v)
{
    /* Your code */
}
```

Because `execute` haven't been used anywhere in the `example.cpp` this means this function wont get compiled. You have to define it in your C++ file on the bottom the following code to get it compiled:

```cpp
template void execute<int>(int v);
```

Now we have a basic understanding what is required we can go to the Clang bug.
When you create a class constructor. It wont return any type. This means at the end of a function it doesn't have a type. When you declare the template type as before you see we have a void as a return value. And in Clang 9.0 it has a type as requirement. And this shouldn't be happening.

The following will fail in Clang 9.0 but it should be valid

```cpp
template CPubKey::CPubKey<unsigned char*>(unsigned char*, unsigned char*);
```

Error clang++ gives:
```console
src/cpubkey.cpp:261:20: fatal error: qualified reference to 'CPubKey' is a constructor name rather than a type in this context
```

I had a discussion on the discord channel[1][2] about this bug a year ago and looks like it didnt got fixed in the latest version.
In this discussion someone made a example code over here[3]. It clearly shows that GCC is accepting this as valid and Clang doesn't.

Reference:
[1] https://discord.gg/DgjWY7DK
[2] https://discord.com/channels/636084430946959380/636808521371090956/850316658605293578
[3] https://godbolt.org/z/o39MahhKz

**Comment by EugeneZelenko** [comment]
9 is too old. Could you please try 15 or `main` branch? https://godbolt.org should be helpful.

**Comment by IamLupo** [comment]
> 9 is too old. Could you please try 15 or `main` branch? https://godbolt.org should be helpful.

I add the bodbolt.org link in my story with example code and even 15 has this case.

**Comment by shafik** [comment]
This looks like [DR 581: Can a templated constructor be explicitly instantiated or specialized?](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#581).

The code from the OP is as follows:

```cpp
// foo.h
class CPubKey
{
public:
    template<typename T>
    CPubKey(T foo);
};

// foo.cpp
template<typename T>
CPubKey::CPubKey(T foo)
{
}

template CPubKey::CPubKey<char*>(char*);
```

After reading the resolution to DR 581 I believe conforming code would look as follows:

```cpp
class CPubKey {
public:
    template<typename T>
    CPubKey(T foo);
};

template<typename T>
CPubKey::CPubKey(T foo){}

template <>
CPubKey::CPubKey(char*);
```

See godbolt which clang/gcc/MSVC accept: https://godbolt.org/z/ncv3er9hW

CC @erichkeane @AaronBallman @hubert-reinterpretcast for more eyes on this since this feels like a particularly odd case and I want some more opinions on what we think a conforming implementation should accept here.

**Comment by erichkeane** [comment]
I think I agree with Shafik, the example in the bug report is wrong, and I think we are properly rejecting it, though GCC is not.  I'd love to hear Hubert's response here though.

**Comment by IamLupo** [comment]
> This looks like [DR 581: Can a templated constructor be explicitly instantiated or specialized?](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#581).
> 
> The code from the OP is as follows:
> 
> ```c++
> // foo.h
> class CPubKey
> {
> public:
>     template<typename T>
>     CPubKey(T foo);
> };
> 
> // foo.cpp
> template<typename T>
> CPubKey::CPubKey(T foo)
> {
> }
> 
> template CPubKey::CPubKey<char*>(char*);
> ```
> 
> After reading the resolution to DR 581 I believe conforming code would look as follows:
> 
> ```c++
> class CPubKey {
> public:
>     template<typename T>
>     CPubKey(T foo);
> };
> 
> template<typename T>
> CPubKey::CPubKey(T foo){}
> 
> template <>
> CPubKey::CPubKey(char*);
> ```
> 
> See godbolt which clang/gcc/MSVC accept: https://godbolt.org/z/ncv3er9hW
> 
> CC @erichkeane @AaronBallman @hubert-reinterpretcast for more eyes on this since this feels like a particularly odd case and I want some more opinions on what we think a conforming implementation should accept here.

Oke i test your  case and i think there is a misunderstanding, the reason i do this is to forcly generate the template with the last line.

I realize the example case i gave you miss a concept like i adjust the example case:

```c++
// foo.h
class CPubKey
{
public:
    template<typename T>
    CPubKey(T foo);
};

// foo.cpp
template<typename T>
CPubKey::CPubKey(T foo)
{
    foo++;
}

template CPubKey::CPubKey<int>(int);
template CPubKey::CPubKey<char*>(char*);
```

If you compile this case in gcc you will see he generate the two functions assembly.

With your recommended fix at the end It doesnt generate the two functions in clang:
```c++
template <>
> CPubKey::CPubKey(int);
template <>
> CPubKey::CPubKey(char*);
```

**Comment by shafik** [comment]
Your reference godbolt did not work, I fixed it: https://godbolt.org/z/WG6cxa6E4

and from what I can see both clang and gcc generate assembly for both functions clang generates:

```asm
CPubKey::CPubKey<int>(int):                    # @CPubKey::CPubKey<int>(int)
        push    rbp
        mov     rbp, rsp
        mov     qword ptr [rbp - 8], rdi
        mov     dword ptr [rbp - 12], esi
        mov     eax, dword ptr [rbp - 12]
        add     eax, 1
        mov     dword ptr [rbp - 12], eax
        pop     rbp
        ret
CPubKey::CPubKey<char*>(char*):                   # @CPubKey::CPubKey<char*>(char*)
        push    rbp
        mov     rbp, rsp
        mov     qword ptr [rbp - 8], rdi
        mov     qword ptr [rbp - 16], rsi
        mov     rax, qword ptr [rbp - 16]
        add     rax, 1
        mov     qword ptr [rbp - 16], rax
        pop     rbp
        ret
```

**Comment by IamLupo** [comment]
> 

Ow I see now, really thx for solving, then this means clang and gcc has different way of doing this!

<3
