### ISSUE TITLE
clang_rt_asan_dynamic_x86_64 crash running ASan build of Firefox&chromium on Windows 11 22h2(OS Build 22621.819)

### ISSUE THREAD

**Issue by cooolie** [llvm/llvm-project#59295]
detail i reported here
https://bugs.chromium.org/p/chromium/issues/detail?id=1391704

firefox download address
https://firefoxci.taskcluster-artifacts.net/a-3FnV7HQ6qcVw_q5w8XSA/0/public/build/target.zip

Similar to this issue
#51063

**Comment by alvinhochun** [comment]
Is this the same issue as https://github.com/llvm/llvm-project/issues/58846?

**Comment by cooolie** [comment]
yes,i think so.
