### ISSUE TITLE
[Clang (all versions][x86-64 backend] Incorrect handling of uint64_t bitfields

### ISSUE THREAD

**Issue by g0blue** [llvm/llvm-project#59306]
# Overview

**TL;DR:** See godbolt link: https://godbolt.org/z/GhWdrnv5s

# Details

There seems to be an "optimization" for bitfield members that are <= 32bits but have a 64-bit data type.  Specifically, reading the value returns a signed int32, not an unsigned int64.  Most of the time this does not cause a problem, but when shifting the bitfield value directly the result can meet or exceed 32 bits and the result is incorrect.

## Reproduction

Compile and run the below Example Code

## Example Code

```cpp
#include <stdint.h>
#include <stdio.h>
#include <inttypes.h>

static constexpr uint32_t NUM_BITS = 27;

struct foo
{
    foo() { Fields.data = 0;}
    union Fields
    {
        struct Bits
        {
            uint64_t                 FlagValue      : 1;
            uint64_t                 Reserved_0     : 5;
            uint64_t                 Value          : NUM_BITS;
	} Bits;

        uint64_t data;
    } Fields;

    enum VALUE
    {
        VALUE_BIT_SHIFT  = 6,
    };

    void SetValue( const uint64_t value )
    {
        Fields.Bits.Value = value >> VALUE_BIT_SHIFT;
    }

    // MSVC will note that GetValue and GetValue2 are identical and the
    // linker will remove GetValue and make both calls from main() call
    // GetValue2. All versions of MSVC work correctly.
    //
    // All versions of clang fail
    // GCC versions >= 10.1 fail (older versions work correctly)
    uint64_t GetValue( void ) const 
    {
        // This function may return INCORRECT results when:
        // (32 - VALUE_BIT_SHIFT) <= NUM_BITS <= 32!!
        //
        // In these error cases a 32-bit register is left shifted
        // and x86-64 HW will sign extend the result.
        // So, we could lose MSBs, or we could incorrectly get a sign-extended result
        //
        // For Clang - it's even in the IR!!
        //   %8 = trunc i64 %7 to i32, !dbg !144
        //   %9 = shl i32 %8, 6, !dbg !146
        //   %10 = sext i32 %9 to i64, !dbg !147
        return (Fields.Bits.Value << VALUE_BIT_SHIFT);
    }

    uint64_t GetValue2( void ) const 
    {
        // This version correctly left shifts a 64-bit register
        return (static_cast<uint64_t>(Fields.Bits.Value) << VALUE_BIT_SHIFT);
    }
};

int main()
{
    foo f;
    uint64_t start = ((uint64_t(3) << (NUM_BITS-2)) - 1) << foo::VALUE_BIT_SHIFT;
    f.SetValue(start);
        
    uint64_t val = f.GetValue();
    uint64_t val2 = f.GetValue2();

    printf("Start: 0x%" PRIx64 "\n", start);
    printf("Get:   0x%" PRIx64 "\n", val);
    printf("Get2:  0x%" PRIx64 "\n", val2);
    printf("%s", (val == val2 && val == start) ? "Correct Results" : "Bug detected!!");

    return int(val != val2 || val != start);
}
```

**Comment by LebedevRI** [comment]
https://godbolt.org/z/W3xPvKfT9
```
/app/example.cpp:50:35: runtime error: left shift of 100663295 by 6 places cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /app/example.cpp:50:35 in 
```

**Comment by g0blue** [comment]
Where does type 'int' come from?  The bitfield type is uint64_t.

**Comment by shafik** [comment]
> Where does type 'int' come from? The bitfield type is uint64_t.

[expr.shift p1](https://eel.is/c++draft/expr.shift#1) says:

> The operands shall be of integral or unscoped enumeration type and integral promotions are performed[.](https://eel.is/c++draft/expr.shift#1.sentence-2) The type of the result is that of the promoted left operand[.](https://eel.is/c++draft/expr.shift#1.sentence-3) The behavior is undefined if the right operand is negative, or greater than or equal to the width of the promoted left operand[.](https://eel.is/c++draft/expr.shift#1.sentence-4)

and [conv.prom p5](https://eel.is/c++draft/conv.prom#5) says:

> A prvalue for an integral bit-field ([[class.bit]](https://eel.is/c++draft/class.bit)) can be converted to a prvalue of type int if int can represent all the values of the bit-field;

**Comment by g0blue** [comment]
Wow, that's ... dumb.  I guess I can use this as a reference for a bug filed against the C++ standard.  Thank you for your investigation.

**Comment by g0blue** [comment]
Can we add an option / pragma / anything that disables integral promotion of bitfields?

**Comment by AaronBallman** [comment]
> Wow, that's ... dumb. I guess I can use this as a reference for a bug filed against the C++ standard. Thank you for your investigation.

It's not a bug in the C++ standard and changing it would break ABI in things like vararg passing.

> Can we add an option / pragma / anything that disables integral promotion of bitfields?

I don't think that's an extension we'd be interested in given how special-case the situation is an how trivial the workaround is.
