### ISSUE TITLE
[clang] Accept -std=c++23/gnu++23 rather than c++2b, like gcc does

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [llvm/llvm-project#59300]
Hi,

gcc already accepts the C++ dialects `c++23`/`gnu++23`, and checking right now on Compiler Explorer it seems clang does not. C++23 isn't finalized yet, however it is shaping up and has already reached the feature freeze phase. Most likely it will be officially formalized in 2023. Is it time to start accepting `-std=c++23`/`-std=gnu++23` in clang ?

Cheers,
Romain

**Comment by AaronBallman** [comment]
We typically wait for the standard to be ratified before doing that, but at the end of the day, if the standard is ratified in 2024, we'd just accept c++23 as an alias for c++24 same as we do with c90/c89. Interestingly, GCC does not accept `-std=c23` yet.

**Comment by Romain-Geissler-1A** [comment]
Hi,

I am not sure this if this is ok to implement this now. Last time for C++20 it seems it was done in February 2020: https://github.com/llvm/llvm-project/commit/24ad121582454e625bdad125c90d9ac0dae948c8

**Comment by AaronBallman** [comment]
I think we're good to go for renaming C++2b to C++23 now (any ballot comments received by WG21 at this stage will be handled as issues against C++2c instead). CC @hubert-reinterpretcast as C++ conformance code owner

**Comment by Romain-Geissler-1A** [comment]
This is implemented on the main branch now, so closing this.
