### ISSUE TITLE
Debian packages are missing llvm-reduce

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#59303]
I install the debian packages from https://apt.llvm.org/, and llvm-reduce is missing. It does provide bugpoint and the other tools

**Comment by sylvestre** [comment]
is llvm-reduce installed with a ninja/make install ?

I am installing all binaries

**Comment by arsenm** [comment]
Yes, I get it with a regular install

**Comment by sylvestre** [comment]
on my system, with `apt install llvm-15`:

```
$  llvm-reduce-15 --version
Debian LLVM version 15.0.6
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: haswell

```

**Comment by sylvestre** [comment]
if you are talking about the link llvm-reduce-15 -> llvm-reduce, I will upload a new version with the fix soon

**Comment by arsenm** [comment]
I also noticed FileCheck-16 is missing the link

**Comment by sylvestre** [comment]
i fixed it
$ ls -al /usr/bin/llvm-reduce
lrwxrwxrwx 1 root root 30 Feb 13 23:43 /usr/bin/llvm-reduce -> ../lib/llvm-14/bin/llvm-reduce
