### ISSUE TITLE
Ambiguity between empty parameter pack and function with default argument

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#59314]
The following code used to be accepted by Clang (up until Clang 15), and is not anymore:

```cpp
#include <type_traits>

template <typename ...Args>
void f(int, Args&& ...args) { }

template <typename T = int>
void f(int, std::enable_if_t<sizeof(T) != 0, int> = 0) { }

int main() {
    f(0);
}
```

This is now ambiguous. Repro: https://godbolt.org/z/9sjv74M6f

It seems that GCC and MSVC are happy with it. I'm not sure whether this is a Clang regression and I didn't find the commit after a quick check through the `git log`, but Clang folks may know whether this was intended or not.

**Comment by royjacobson** [comment]
This sounds like https://reviews.llvm.org/D128745, I'm not sure if the change is intended. cc @yuanfang-chen

**Comment by yuanfang-chen** [comment]
The second parameter is not considered for partial ordering because, in the call context, there is only an argument for the first parameter. Basically, the `g(42)` example in https://eel.is/c++draft/temp.func.order#example-4
