### ISSUE TITLE
llvm 11.x release build failure

### ISSUE THREAD

**Issue by claudeyj** [llvm/llvm-project#59333]
Hi, I was trying to build llvm 11.x release on my local ubuntu machine, but it failed with an error saying that "error: ‘numeric_limits’ is not a member of ‘std’". It seems that the <limits> library is missing in llvm/utils/benchmark/src/benchmark_register.h. Add "include <limits>" can fix this issue.

**Comment by claudeyj** [comment]
Thank you for your prompt reply. Yes, 11 is very old. But some projects require llvm11. So it can also be annoying if 11.x release cannot build successfully.

**Comment by EugeneZelenko** [comment]
Only last release is maintained.

**Comment by claudeyj** [comment]
OK, thank you for your comments. I should close this issue then.

**Comment by mirusu400** [comment]
Who are struggled with this issue: add `#include <limits>` in `llvm/utils/benchmark/src/benchmark_register.h`, then build it.
