### ISSUE TITLE
Debug lines present in llvm ir but not propagated in final binary

### ISSUE THREAD

**Issue by AnFunctionArray** [llvm/llvm-project#59331]
Here is basically the issue:

https://stackoverflow.com/questions/74665224/llvm-wont-generate-debug-line-information

**Comment by AnFunctionArray** [comment]
I had to do:
```
dyn_cast<llvm::Function> (currfuncval)->setSubprogram(llvmsub);
```

**Comment by EugeneZelenko** [comment]
Please use https://discourse.llvm.org for questions.

**Comment by pogo59** [comment]
I see there's a comment on the stackoverflow question which is largely correct. I suspect the locations are emitted to assembler/object-file, but line 0 is special in DWARF and generally will be ignored by debuggers. Try using line 1 instead.
