### ISSUE TITLE
[AArch64][SVE] Missed optimisation for _x variants of multiply-accumulate intrinsics

### ISSUE THREAD

**Issue by Sevenarth** [llvm/llvm-project#59343]
There is a missed optimisation which affects all of the following intrinsics in their predicated "don't care" form: [svmad](https://developer.arm.com/architectures/instruction-sets/intrinsics/svmad[_s32]_x), [svmla](https://developer.arm.com/architectures/instruction-sets/intrinsics/svmla[_s32]_x), [svmsb](https://developer.arm.com/architectures/instruction-sets/intrinsics/svmsb[_s32]_x), [svmls](https://developer.arm.com/architectures/instruction-sets/intrinsics/svmls[_s32]_x) and their negated counterparts: [svnmad](https://developer.arm.com/architectures/instruction-sets/intrinsics/svnmad[_s32]_x), [svnmla](https://developer.arm.com/architectures/instruction-sets/intrinsics/svnmla[_s32]_x), [svnmsb](https://developer.arm.com/architectures/instruction-sets/intrinsics/svnmsb[_s32]_x) and [svnmls](https://developer.arm.com/architectures/instruction-sets/intrinsics/svnmls[_s32]_x). This is related to the case when a second or third operand is loaded in the same register used to store the result.

This behaviour can be reproduced by shifting the arguments in a shim function as follows:
```cpp
svint32_t test(svint32_t op3, svint32_t op1, svint32_t op2) {
    return svmad_s32_x(svpfalse(), op1, op2, op3);
}
```
which compiles to:
```asm
pfalse  p0.b
mad     z1.s, p0/m, z2.s, z0.s
mov     z0.d, z1.d
ret
```
whereas gcc 12.2.0 compiles it correctly to:
```asm
pfalse  p0.b
mla     z0.s, p0/m, z1.s, z2.s
ret
```

**Comment by paulwalker-arm** [comment]
Fixed by https://reviews.llvm.org/D150553 and https://reviews.llvm.org/D143767.
