### ISSUE TITLE
[flang] how to get ast using f18

### ISSUE THREAD

**Issue by PressFforlove** [llvm/llvm-project#59340]
hello there, i'm new to llvm and f18, i have installed f18 and it can generate IR by -llvm-emit option(which means it can generate ast either).
But unlike clang, it can't use -ast-dump to translate code to ast.
I also tried -q , -qq, -Hq, -Mq options, which are unknow argument.
By the way, i have found a article about flang names 
"How The Flang Frontend  Works",
(https://llvm-hpc4-workshop.github.io/slides/Osmialowski.pdf) 
and i wonder whether f18 still has flang1 and flang2? 
by the way , where can i find -xflang arg readme in flang src code?
Thank you very much for answering this question!

**Comment by kiranchandramohan** [comment]
`f18`/`llvm/flang` is a new compiler written from scratch and does not support the options of the Classic Flang compiler (https://github.com/flang-compiler/flang) detailed in the presentation you listed.

The option to use here would be either of the following depending on whether you want the output before or after the Semantics phase.
-> `flang-new -fc1 -fdebug-dump-parse-tree simple.f90`
-> `flang-new -fc1 -fdebug-dump-parse-tree-no-sema simple.f90`

**Comment by PressFforlove** [comment]
> `f18`/`llvm/flang` is a new compiler written from scratch and does not support the options of the Classic Flang compiler (https://github.com/flang-compiler/flang) detailed in the presentation you listed.
> 
> The option to use here would be either of the following depending on whether you want the output before or after the Semantics phase. -> `flang-new -fc1 -fdebug-dump-parse-tree simple.f90` -> `flang-new -fc1 -fdebug-dump-parse-tree-no-sema simple.f90`
> 
> For the compiler options, you can check the help messages from the Driver: -> User options : `flang-new --help` -> Developer options : `flang-new -fc1 --help`

thank you very much~

**Comment by PressFforlove** [comment]
by the way, is some one want to dump ast to xxx.txt, try to  append  >xxx.txt at the end.
