### ISSUE TITLE
SVE VLA miscompiles GCC torture scal-to-vec1.c

### ISSUE THREAD

**Issue by DavidSpickett** [llvm/llvm-project#59357]
Since https://lab.llvm.org/buildbot/#/builders/197/builds/3475 we have been seeing https://github.com/llvm/llvm-test-suite/blob/main/SingleSource/Regression/C/gcc-c-torture/execute/scal-to-vec1.c fail to execute.

Looking at it locally it is coredumping because abort is called during one of the vector compares.

Bisecting this I got down to https://reviews.llvm.org/D138872 / e71b81cab09bf33e3b08ed600418b72cc4117461.

At this commit, the program aborts when compiled with:
```console
$ /home/david.spickett/build-llvm-aarch64/bin/clang -mcpu=a64fx -O3 /home/david.spickett/llvm-test-suite/SingleSource/Regression/C/gcc-c-torture/execute/scal-to-vec1.c -o /tmp/test.o && /tmp/test.
```

Note that that is compiling with `-O3`. Turns out that it fails at 0, 1, 2 and 3.

One commit prior (d5b0de35bdd9a3f4d4a093e7938b06add34678eb) it will only crash when compiled with `-O0`. 1, 2 and 3 all work.

Which sounds to me like the "bad" commit changed some process that was covering up some bad decision making.

Reproducer and testing against previous released versions to follow.

**Comment by DavidSpickett** [comment]
| Clang version | -O0 | -O1 | -O2 | -O3 |
|---|---|---|---|---|
| 14.0.6 | Pass | Pass | Pass | Pass |
| 15.0.0 | Fail | Pass | Pass | Pass |
| `d5b0de35bdd9a3f4d4a093e7938b06add34678eb` (prior commit) | Fail | Pass | Pass | Pass |
| `e71b81cab09bf33e3b08ed600418b72cc4117461` ("bad" commit) | Fail | Fail | Fail | Fail |

**Comment by DavidSpickett** [comment]
C reproducer(s):
```
volatile int one = 1;

int main (int argc, char *argv[]) {
    __attribute__((vector_size((8)*sizeof(short)))) short v0 = {one, 1, 2, 3, 4, 5, 6, 7};
    __attribute__((vector_size((8)*sizeof(short)))) short v1;

    // Passes with clang 15.0.0
    // Fails at O1/2/3 with the bad commit.
    v1 = 2 / v0; do { int __i; for (__i = 0; __i < 8; __i++) { if ((*((short *) &(v1) + __i)) != (2 / (*((short *) &(v0) + __i)))) __builtin_abort (); }} while (0);

    // Fails at O0 with clang 15.0.0
    // Fails at any level with bad commit.
    v1 = 2 % v0; do { int __i; for (__i = 0; __i < 8; __i++) { if ((*((short *) &(v1) + __i)) != (2 % (*((short *) &(v0) + __i)))) __builtin_abort (); }} while (0);

    return 0;
}
```
Compile with:
```
./bin/clang -mcpu=a64fx -O1 /tmp/test.c -o /tmp/test.o && /tmp/test.o
```
There are 2 failure points, both around divides which might be relevant.

The corefile just points to abort, I will see what the content of the vectors actually is.

**Comment by DavidSpickett** [comment]
On second thought I'm not sure exactly what I'm looking for anyway.  The assembly has some suspicious elements (setting a vector length of 4 not 8?) but as usual that could be me getting the wrong end of the SVE stick.

If anyone else knows how to track this down that would be much appreciated.

**Comment by peterwaller-arm** [comment]
Candidate fix is up at https://reviews.llvm.org/D139618.
