### ISSUE TITLE
RISC-V: Redundant VSETVLI

### ISSUE THREAD

**Issue by jan-wassenberg** [llvm/llvm-project#59359]
Per this [repro](https://gcc.godbolt.org/z/9Ysfs1KjP), calling vsetvlmax() once in several inlined functions results in several actual VSETVLI instructions. The expected result is a single VSETVLI at the start of the loop, or better yet, hoisted outside.

From personal communication with Craig Topper, this seems to be caused by the intrinsic being marked as having side effects.

**Comment by topperc** [comment]
CC: @preames

**Comment by kito-cheng** [comment]
Personally I prefer vsetvl and vsetvlmax intrinsic should default to no side effect version - that's more fit our intrinsic programming model I think.

**Comment by topperc** [comment]
@jan-wassenberg Kito and I have also talked about special casing a -1ULL passed as the vl argument the intrinsics to request vlmax without needing a separate vlmax intrinsic. Would that help highway?

**Comment by topperc** [comment]
Side effect removal patch https://reviews.llvm.org/D143220
