### ISSUE TITLE
Put in appropriate checks in the libc CMake setup if it cannot be built with non-clang compilers anymore

### ISSUE THREAD

**Issue by sivachandra** [llvm/llvm-project#59368]
Instead of mysteriously failing while building, it is better to provide the users a good error message when they attempt to build with an unsupported compiler.

@gchatelet - I am assigning this to you because IIRC, the memory functions use some features which are only available in clang? The resolution for this bug need not actually be to error out from CMake. We can consider putting in alternate code paths for non-clang compilers if it makes sense. Also, feel free to assign it back to me to actually do the work.

**Comment by gchatelet** [comment]
As discussed offline, we will support GCC for compilation but we will not be making any performance promises.
I'm working on a bunch of patches to support GCC but we really need a bot to make sure we don't regress.

**Comment by tschuett** [comment]
Could you put on libc.llvm.org the minimal requirements, i.e., gcc > 12 and clang > 14?

**Comment by gchatelet** [comment]
> Could you put on libc.llvm.org the minimal requirements, i.e., gcc > 12 and clang > 14?

I've started https://reviews.llvm.org/D141045 to announce that we will support GCC under some conditions.
I'm waiting for a CI bot to be up and running to actually claim that we support it.

**Comment by gchatelet** [comment]
as of [abcdc26](https://github.com/llvm/llvm-project/commit/abcdc26a81d183e3256ce2751530a971ef6c4191) llvm libc compiles with GCC 12.2. It can probably compile with an earlier version.
Assigning back to you @sivachandra to get a build bot up and running. Once it's done we can advertise the compiler support.

**Comment by sivachandra** [comment]
We now have a gcc builder for libc: https://lab.llvm.org/buildbot/#/builders/250. It is cycling green as of build 150. The green builds before that were with clang. I will close this bug now. Please file new bugs for any new issues you see with gcc.
