### ISSUE TITLE
How to use equivalent eu-unstrip with llvm-objcopy + llvm-strip

### ISSUE THREAD

**Issue by nimit25** [llvm/llvm-project#59370]
Using the toolchain from ndk 23. I have an exectuable A. I'm using llvm-objcopy to keep debug symbols in a separate file
`llvm-objcopy --only-keep-debug A A.debug` and then I do `llvm-strip --strip-debug --strip-unneeded A`
Now, how do I something  like `eu-unstrip A A.debug -o fullA` using llvm tools? At the moment I get 
`eu-unstrip: cannot write output file: invalid section alignment`

**Comment by EugeneZelenko** [comment]
Please use https://discourse.llvm.org for questions.

**Comment by nimit25** [comment]
No permission to create a Topic

**Comment by nimit25** [comment]
Can I please get permissions to post?

**Comment by nimit25** [comment]
Thank you so much! it's because of this that my account doesn't my permission 
![Screen Shot 2022-12-07 at 4 22 59 PM](https://user-images.githubusercontent.com/31580737/206299348-1e8282f3-9480-4dc8-8466-47029a2b86fb.png)

**Comment by nimit25** [comment]
@keith Sorry, I can't reply to your comment due to the above issue. I forgot to add, I'm also using --add-gnu-debuglink 
```
llvm-objcopy --only-keep-debug A A.debug 
llvm-strip --strip-debug --strip-unneeded A
llvm-objcopy --add-gnu-debuglink A.debug A
```
The issue is persistent. The use case is for ndk-stack to symbolize crashes.
