### ISSUE TITLE
The function call should be ambiguous if the partial ordering succeeds in both directions but the length of template parameters differs.

### ISSUE THREAD

**Issue by xmh0511** [llvm/llvm-project#59375]
````cpp
#include <iostream>
struct Test{
    using type = void;
};
template<class T>
struct Void_t{
    using type = void;
};
template<class T>  // #1
concept HasType = requires(T a){
    typename T::type;
};
template<HasType T, class U = T>  // #2
void fun(T){ 
    std::cout<<"#1";
}
template<class T>
void fun(T){
    std::cout<<"#2";
}

int main(){
   fun(Test{});
}
````

The call of `fun` should be ambiguous according to [over.match.best.general] p2.5 and [temp.func.order] p6
> If deduction against the other template succeeds for both transformed templates, **constraints can be considered as follows**: 
>> - If **their template-parameter-lists** (possibly including template-parameters invented for an abbreviated function template ([dcl.fct])) or function parameter lists **differ in length**, **neither template is more specialized than the other**.

In this example, deduction against the other template succeeds for both transformed templates but `#1` and `#2` differ in their length of template parameters, therefore neither template is more specialized than the other. Hence, the call should be ambiguous. GCC rejects this example, but Clang accepts it and considers `#1` as the best viable one. https://godbolt.org/z/r8r1Gjfbn

**Comment by royjacobson** [comment]
This has been fixed recently in https://reviews.llvm.org/D128750.
