### ISSUE TITLE
[flang] One simple loop cannot be vectorized

### ISSUE THREAD

**Issue by PeixinQiao** [llvm/llvm-project#59388]
```f90
subroutine test(is, ie, js, je, a, b, c, d)
  implicit none
  integer :: i, j
  integer :: is, ie, js, je
  real, intent(inout) :: a(:,:), b(:,:), c(:,:), d(:,:)

  do j = js, je
    do i = is, ie
      a(i,j)=b(i,j) + c(i,j) * d(i,j)
    end do
  end do
end
```
```console
$ flang-new -fc1 -emit-llvm -O3 test.f90
```
No vectorization instructions generated.

**Comment by kiranchandramohan** [comment]
One of the issues here is that the actual arguments passed to assumed shape dummy arrays could have strides. This requires the stride to be extracted from the descriptor and used inside the loop to calculate the offset of the next element. @Leporacanthicus is investigating this. We discussed this issue a bit in the following discourse post.
https://discourse.llvm.org/t/transformations-to-aid-optimizer-for-subroutines-functions-with-assumed-shape-arguments/66447

**Comment by kiranchandramohan** [comment]
Thanks @rofirrim for your comment. To clarify, I was not saying that the one I listed above is the primary issue or the only issue. There are, I guess, multiple issues here including aliasing. 

For the loop that you provided, we can see gfortran versioning it for stride=1.
```
gfortran -O3 -fopt-info vadd.f90
vadd.f90:7:0: optimized: versioned this loop for when certain strides are 1
vadd.f90:7:0: optimized: loop vectorized using 16 byte vectors
```

Contiguous arrays are easier to vectorize. I am not sure whether it is only the cost of using gather-scatter or something more.

**Comment by kiranchandramohan** [comment]
After the addition of TBAA to distinguish descriptor access from array access and the versioning pass, both loops provided in this ticket are vectorised.
Please reopen if there is something being missed.
