### ISSUE TITLE
TypePromotion is an IR pass, but lacks a NewPM wrapper

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#59385]
Someone should implement it, so that the tests can actually stop using `-type-promotion`.

**Comment by sparker-arm** [comment]
Patch for review: https://reviews.llvm.org/D140893

**Comment by sparker-arm** [comment]
[Fix](https://github.com/llvm/llvm-project/commit/615333bc09c42cdac4d69ea171e610cdcb06e803) committed.
