### ISSUE TITLE
[mlir][SparseTensor] Sparsification pass crashes with subi in reduction loop

### ISSUE THREAD

**Issue by qcolombet** [llvm/llvm-project#59394]
I don't know if I'm somehow building the IR incorrectly, but I can crash the `sparsification` pass with a somewhat simple IR example (See attached [tmp.txt](https://github.com/llvm/llvm-project/files/10184899/tmp.txt) for the mlir file. Github doesn't like `.mlir` file extension.)

Essentially I'm doing: `res = sparse_input[i] - res` and the sparsification chokes on it.
If I do `res = res - sparse_input[i]` everything is fine (i.e., swap the argument of the `arith.subi` operation)
If I do `res = sparse_input[i] * res` everything is fine as well (i.e., replace `arith.subi` with `arith.muli`).

To reproduce:
```shell
mlir-opt -sparsification repro.mlir -o - 
```

Where `repro.mlir` is:
```mlir
#SparseVector = #sparse_tensor.encoding<{dimLevelType = ["compressed"]}>

#trait = {
  indexing_maps = [ 
    affine_map<(i) -> (i)>,  // a (in)
    affine_map<(i) -> ()>    // x (out)
  ],  
  iterator_types = ["reduction"]
}

func.func @sparse_reduction_subi(%argx: tensor<i32>,
                             %arga: tensor<?xi32, #SparseVector>)
 -> tensor<i32> {
  %0 = linalg.generic #trait
     ins(%arga: tensor<?xi32, #SparseVector>)
      outs(%argx: tensor<i32>) {
      ^bb(%a: i32, %x: i32):
        %t = arith.subi %a, %x: i32 
        linalg.yield %t : i32 
  } -> tensor<i32>
  return %0 : tensor<i32>
}
```

**Comment by PeimingLiu** [comment]
https://reviews.llvm.org/D139659.

After discussing with @aartbik, we decided that we should not do sparsification on your cases. This is because the reduction relying on the negation of the output tensor create cyclic dependency.

You could probably change `%t = arith.subi %a, %x: i32` to `%t = arith.subi %x, %a: i32` to test your code
