### ISSUE TITLE
ld64.lld gets killed on MacOS

### ISSUE THREAD

**Issue by jlpettersson** [llvm/llvm-project#59406]
I tried to use the ld64.lld from the latest release, 15.0.6. But it gets killed when I try to run it.

I followed the instructions on https://lld.llvm.org/MachO/index.html

Should the binary be signed in some way? Any other documentation about how to run `ld64.lld` on MacOS?

**Comment by keith** [comment]
The binary is signed it looks like:

```
Executable=/Users/ksmiley/Downloads/clang+llvm-15.0.6-arm64-apple-darwin21.0/bin/lld
Identifier=lld
Format=Mach-O thin (arm64)
CodeDirectory v=20400 size=774300 flags=0x20002(adhoc,linker-signed) hashes=24194+0 location=embedded
VersionPlatform=1
VersionMin=787968
VersionSDK=851968
Hash type=sha256 size=32
CandidateCDHash sha256=f3e2b6493c9d0888dfa3548abb94d337560567a9
CandidateCDHashFull sha256=f3e2b6493c9d0888dfa3548abb94d337560567a98d53ed4506549fa9300373eb
Hash choices=sha256
CMSDigest=f3e2b6493c9d0888dfa3548abb94d337560567a98d53ed4506549fa9300373eb
CMSDigestType=2
Executable Segment base=0
Executable Segment limit=76955648
Executable Segment flags=0x1
Page size=4096
Launch Constraints:
	None
CDHash=f3e2b6493c9d0888dfa3548abb94d337560567a9
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements=none
```

Assuming you downloaded [clang+llvm-15.0.6-arm64-apple-darwin21.0.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.6/clang+llvm-15.0.6-arm64-apple-darwin21.0.tar.xz) this one?

Do the other tools like `clang` work? Is there any more info about the kill in Console.app? If you sign it yourself with:

```
codesign -f -s - ld64.lld
```

Does it fix it?

**Comment by jlpettersson** [comment]
I tried to sign it my self with the command you listed, but it did not help. MacOS does not trust the binary.
All other clang tools I use, is the tools that is provided by default by Apple. I wanted to use a non-Apple lld, to be able to cross-compile to Linux.

**Comment by keith** [comment]
What about if you run `sudo xattr -d com.apple.quarantine ld64.lld`? If that doesn't work you can see all the `xattrs` with `xattr -l ld64.lld`.

**Comment by keith** [comment]
If that does work the real solution is likely to install with a package manager, or sidestep by downloading with `curl` 😕

**Comment by jlpettersson** [comment]
> sudo xattr -d com.apple.quarantine ld64.lld

This worked!! Thank you!!

**Comment by DimitryAndric** [comment]
FWIW ideally these binaries would get signed, but I don't have a paid Apple Developer account, so. :)

**Comment by keith** [comment]
Fwiw the binaries are signed with a default signature that is valid. This quarantine problem is another issue.
