### ISSUE TITLE
aarch64 globalisel crash compiling "atomicrmw add i128"

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#59407]
Test case (compile with `llc -mtriple=aarch64 -global-isel=1`):

```ll
@var = global i128 0
define void @fetch_and_add(i128* %p, i128 %bits) {
  %val = atomicrmw add i128* %p, i128 %bits seq_cst
  store i128 %val, i128* @var, align 16
  ret void
}
```

Gives:

```console
LLVM ERROR: cannot select: %31:gpr64(s64), %34:gpr(s32) = G_UADDE %5:gpr, %3:gpr, %35:gpr (in function: fetch_and_add)
```

Godbolt: https://godbolt.org/z/8WGq495d1

There's some interaction with optimizations here; it works fine with `-O0`.

CC @aemerson @ornata

**Comment by fhahn** [comment]
Still crashing

**Comment by niwinanto** [comment]
The issue is because, `UADDE` is not selected when `global-isel` enabled. 
Here is the fix prototype. https://reviews.llvm.org/D153165
