### ISSUE TITLE
[C++20 Modules, Question] Module named "module"

### ISSUE THREAD

**Issue by Arthapz** [llvm/llvm-project#59404]
Hi, when trying to build a C++20 module named 

```cpp
export module module:parta;

export int a() {
    return 0;
}
```

```
/usr/sbin/clang -c -x c++-module --precompile -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++2b -fmodules -fbuiltin-module-map -fimplicit-modules -DNDEBUG -fmodules-cache-path=build/.gens/with_named_modules/linux/x86_64/release/rules/modules/cache -o build/.gens/with_named_modules/linux/x86_64/release/rules/modules/cache/MyModule-part.pcm build/.gens/with_named_modules/linux/x86_64/release/cpp_to_mpp/mymodule_part.mpp
```

```
error: 'module' is an invalid name for a module
```

Shouldn't "module" keyword to be contextual allowing this ? (work fine with gcc and msvc)
i'm using llvm builded from main branch

**Comment by shafik** [comment]
Clang is correct to reject these names see [modules.unit p1](https://eel.is/c++draft/module#unit-1.sentence-3):

> ... The identifiers *module* and *import* shall not appear as [identifier](https://eel.is/c++draft/lex.name#nt:identifier)s in a [module-name](https://eel.is/c++draft/module#nt:module-name) or [module-partition](https://eel.is/c++draft/module#nt:module-partition) ...
