### ISSUE TITLE
source_location providing inconsistent output from gcc when compiling with -stdlib=libstdc++

### ISSUE THREAD

**Issue by danielh2942** [llvm/llvm-project#59422]
In this minimal example obtained from cppreference: https://en.cppreference.com/w/cpp/utility/source_location

https://godbolt.org/z/brM8WjT6z

source_location::function_name() should return a non-zero NTBS
where on clang++-15 it does not
however, when run on GCC it seemingly returns the output of ```__PRETTY_FUNCTION__``` for the calling function
I'm not sure if this is a libstdc++ issue or a clang++ issue so I'm going to report it in both locations

thanks :)

gcc bugtracker 
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108035

**Comment by tbaederr** [comment]
Related: https://github.com/llvm/llvm-project/issues/56379 

@cor3ntin, does your patch fix this issue as well?

**Comment by cor3ntin** [comment]
@tbaederr yes, both issues are the same.

**Comment by tbaederr** [comment]
Duplicate of https://github.com/llvm/llvm-project/issues/56379
