### ISSUE TITLE
Ubuntu Bionic packages for LLVM-14 depend on libgcc-s1

### ISSUE THREAD

**Issue by tcm0116** [llvm/llvm-project#59423]
As described in https://github.com/f4exb/sdrangel/issues/524 for a different project, it appears that the build environment for the LLVM-14 Ubuntu Bionic packages has additional packages installed which are not part of the Ubuntu Bionic official repositories, namely `libgcc-s1`, which appears to be part of `gcc-10`.

I was able to build LLVM-14 from the source packages on a fresh Ubuntu 18.04 Docker container, so it appears that these extra dependencies are not required.

Slightly related, building the packages required a newer version of CMake that supports the `-S` parameter, which is nut supported by version 3.10.2 included in the default Bionic repositories.

**Comment by asl** [comment]
Tagging @sylvestre

**Comment by sylvestre** [comment]
yeah, it is documented on apt.llvm.org:
# Needs 'sudo add-apt-repository ppa:ubuntu-toolchain-r/test' for libstdc++ with C++20 support

the gcc (and therefore libstdc++) provided on bionic is too old to work out of the box.

About cmake, i am backporting it too.
