### ISSUE TITLE
Pointer to thread_local variable accepted in a constant expression 

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#59426]
The following program is accepted despite constant expression `b` includes evaluation of a pointer to `thread_local` variable:
```cpp
constexpr thread_local int a = 0;
constexpr int b = *&a;
```

A similar problem seems to exist in GCC, and only MSVC properly rejects the code. Only demo: https://gcc.godbolt.org/z/TxK7KKnPE

**Comment by zygoloid** [comment]
Looks like an MSVC bug to me; as far as I can see, the given testcase is valid. The restriction on thread-local variables in constant expressions only applies to the final result of the evaluation, not to intermediate evaluations. So this is invalid:
```
constexpr thread_local int a = 0;
constexpr const int *p = &a;
```
... and Clang and GCC reject it, but the original testcase is valid and MSVC is wrong to reject.

**Comment by Fedr** [comment]
I am not absolutely sure, but it looks similar to this answer https://stackoverflow.com/a/32926471/7325599, which explains that subexpression of a constant expression must be constant expression as well. Is there any exception for `thread_local` here?

**Comment by zygoloid** [comment]
> I am not absolutely sure, but it looks similar to this answer https://stackoverflow.com/a/32926471/7325599, which explains that subexpression of a constant expression must be constant expression as well.

That's not accurate -- note that @shafik's answer there says:

> Do constant expressions strictly require every sub-expression to be a constant expression? No

The way the rules work is: first there's an evaluation under the C++11 "core constant evaluation" rules to determine a symbolic value (which has no restrictions on `thread_local`), and then there's a final check that the value produced is in fact "sufficiently" constant -- that it doesn't contain any references to local variables or `thread_local` state or similar.

**Comment by Fedr** [comment]
Thanks. Indeed, I probably misunderstood the referenced answer. I was confused that `0 * arg` can be proven symbolically to has the value of constant `0` and does not contain any reference on local variable and so on.
