### ISSUE TITLE
Assertion failed: false && "called into swift language runtime stub"

### ISSUE THREAD

**Issue by songwentong** [llvm/llvm-project#59439]
1> 1+2
Assertion failed: false && "called into swift language runtime stub", file D:\a\1\s\llvm-project\lldb\source\Plugins\LanguageRuntime\Swift\SwiftLanguageRuntime.cpp, line 392
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
 #0 0x00007ff649174bd5 (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\lldb.exe+0x24bd5)
 #1 0x00007ffa606ee5f5 (C:\WINDOWS\System32\ucrtbase.dll+0x7e5f5)
 #2 0x00007ffa606ef601 (C:\WINDOWS\System32\ucrtbase.dll+0x7f601)
 #3 0x00007ffa606f106a (C:\WINDOWS\System32\ucrtbase.dll+0x8106a)
 #4 0x00007ffa606f0f5d (C:\WINDOWS\System32\ucrtbase.dll+0x80f5d)
 #5 0x00007ffa606f11f1 (C:\WINDOWS\System32\ucrtbase.dll+0x811f1)
 #6 0x00007ff9568a1559 PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x6d1559)
 #7 0x00007ff95bac4ce4 PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x58f4ce4)
 #8 0x00007ff95baca93b PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x58fa93b)
 #9 0x00007ff95bac7eea PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x58f7eea)
#10 0x00007ff95bac233b PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x58f233b)
#11 0x00007ff9565b6bac PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x3e6bac)
#12 0x00007ff9565c5802 PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x3f5802)
#13 0x00007ff956593206 PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x3c3206)
#14 0x00007ff95653e62a PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x36e62a)
#15 0x00007ff95653c4ee PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x36c4ee)
#16 0x00007ffa60699363 (C:\WINDOWS\System32\ucrtbase.dll+0x29363)
#17 0x00007ffa618e247d (C:\WINDOWS\System32\KERNEL32.DLL+0x1247d)
#18 0x00007ffa62badfb8 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x5dfb8)

**Comment by EugeneZelenko** [comment]
Please provide OS and LLVM version information as well as reproducer.

**Comment by labath** [comment]
For swift issues, you'll need to file a bug at <https://github.com/apple/llvm-project> (as the that's where swift support is implemented).
