### ISSUE TITLE
llvm-exegesis -mode=latency -repetition-mode=min -opcode-index=-1 never ends

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#59441]
Using the -repetition-mode=min to try and help determine minimum latency numbers seems to be causing some tests to never end.

I've been trying to use "-mode=latency -repetition-mode=min -opcode-index=-1" to help improve the latency numbers for various x86 models (currently Silvermont + Core2 running SandyBridgeModel) and in both cases there appears to be a hang somewhere early on, although I haven't had much luck tracking it down so far. uops/inverse_throughput seem to run fine.

@LebedevRI - have you seen this at all?

**Comment by LebedevRI** [comment]
Works for me.
Which `-mtriple= -mcpu=` ?

**Comment by RKSimon** [comment]
-mtriple=x86_64-linux -mcpu=slm / -mcpu=penryn so far - although I'm not specifying these on the command line as I've never had to in the past.

This is for measurements, not just dry run

**Comment by LebedevRI** [comment]
If you specify `-repetition-mode=min`/`-repetition-mode=loop`, you also want to specify `--loop-body-size=` explicitly.
Can you please confirm that it finishes in dry-run mode?

**Comment by RKSimon** [comment]
Thanks I will try that and report back - do you recommend any particular -loop-body-size= value?

**Comment by RKSimon** [comment]
Updating to latest trunk seems to be working - maybe 2ffe225d113031cc211d20d8d2cb82eeaa1a34a2 helped?

**Comment by RKSimon** [comment]
OK - this is still happening, just intermittently 

tried on a slm box with `--mode=latency --opcode-index=-1 -repetition-mode=min -x86-disable-upper-sse-registers --loop-body-size=64`

--skip-measurements doesn't seem to have a problem (although it still takes a long time to run so I've only tried it a couple of times so far).

It seems to stop quite early on, the BSF instructions are the last outputs - but individually testing various BSR/BSWAP/BT instructions hasn't caused a hang yet - although I'm suspicious of the BT instruction chains it creates

**Comment by LebedevRI** [comment]
FWIW, i expect to make some exponential improvements to the speed of `-skip-measurements`,
there is no reason the baseline code has to be this slow.

**Comment by LebedevRI** [comment]
> FWIW, i expect to make some exponential improvements to the speed of `-skip-measurements`, there is no reason the baseline code has to be this slow.

https://reviews.llvm.org/D140271

Looks like i can reproduce that "deadlock", and only for latency+loop measurement.
I will take a look.

**Comment by LebedevRI** [comment]
This is quite funny, see if you can spot it:
```
/tmp/snippet-e4a9df.o:     file format elf64-x86-64


Disassembly of section .text:

0000000000000000 <foo>:
   0:   41 b8 00 00 00 00       mov    $0x0,%r8d
   6:   66 41 b8 00 00          mov    $0x0,%r8w
   b:   49 b8 88 13 00 00 00    movabs $0x1388,%r8
  12:   00 00 00 
  15:   41 0f ba e0 01          bt     $0x1,%r8d
  1a:   66 41 c1 d0 01          rcl    $0x1,%r8w
  1f:   49 83 c0 ff             add    $0xffffffffffffffff,%r8
  23:   75 f0                   jne    15 <foo+0x15>
  25:   c3                      ret
```
(we are modifying loop counter in loop.)
`AliasingConfigurations` failed to account for forbidden registers.
