### ISSUE TITLE
[AMDGPU][MC][GFX11] v_fmac_f16_e64 cannot be disassembled

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#59467]
This instruction cannot be disassembled when dst is v209..v234, v249, v250, v255.
An example of failed test:

    0xff,0x00,0x36,0xd5,0x01,0x05,0x02,0x00

Expected result:

    v_fmac_f16_e64 v255, v1, v2 ; encoding: [0xff,0x00,0x36,0xd5,0x01,0x05,0x02,0x00]

Actual result:

    warning: invalid instruction encoding

**Comment by Sisyph** [comment]
It looks to me like the output is your expected result in ToT

**Comment by dpreobra** [comment]
> It looks to me like the output is your expected result in ToT
I'm sorry!

Fixed by commit e7a306310b0bfbd97cdce8f77686b6453fc76bca.

**Comment by dpreobra** [comment]
Fixed by commit e7a306310b0bfbd97cdce8f77686b6453fc76bca.
