### ISSUE TITLE
bug: non-selfcontained headers are suggested to remove

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#59476]
Running `clang-include-cleaner` on `StandardLibrary.cpp`, it suggests to remove these two [lines](https://github.com/llvm/llvm-project/blob/main/clang/lib/Tooling/Inclusions/Stdlib/StandardLibrary.cpp#L29-L30)

```
- "clang/Tooling/Inclusions/CSymbolMap.inc"
- "clang/Tooling/Inclusions/StdSymbolMap.inc"
```

For non self-contained headers, they should never be considered as unused (as these headers have side effects).

**Comment by kadircet** [comment]
as discussed offline, i believe this is WAI. expansion of those sources into the main file are in a way that's against our IWYU policy. so those headers should be explicitly marked with `IWYU pragma: keep`. if this turns into a more common theme, we can try and special case non-selfcontained includes (treat them as always keep). but i'd rather not do that both for maintenance and hiding real findings.

if you agree, please close. we can re-open in the future if this bites us more often.

**Comment by hokein** [comment]
This is fixed by a recent commit https://github.com/llvm/llvm-project/commit/d3cfc7126c160641bc2630cdf2cbdb61abf8bc6d, now we always keep non-selfcontained headers in include-cleaner.
