### ISSUE TITLE
[clang-tidy] modernize-avoid-c-arrays option to ignore C-style strings

### ISSUE THREAD

**Issue by KindDragon** [llvm/llvm-project#59475]
Please provide option to ignore char* arrays from this rule, it would allow to skip a lot of warnings

**Comment by carlosgalvezp** [comment]
I'm not sure the check should increase in complexity to support this use case, when the code can be easily fixed:

```cpp
-char x[] = "foo";
+char* x = "foo";
```

Doing this transformation would also give you the benefit of avoiding the other warning about array-to-pointer decay. Would that work for you?

**Comment by carlosgalvezp** [comment]
Since you mention `span` (C++20), perhaps you can then use `string_view` instead? It's essentially identical to `span` but offers additional string manipulation functions.

```cpp
std::string_view x = "foo";
```

**Comment by KindDragon** [comment]
Yes, sometimes it works well, but it does not guarantee that it will be nul-terminated.

**Comment by carlosgalvezp** [comment]
Yes, that can be the case if you do further manipulation e.g. with substrings, but you also can have the same problem with `span`, right? If you just construct the `string_view` with the raw string, the `data` pointer points to the static string, which is null-terminated.

Do you have some concrete use case in mind where a C-style char array would work but not the equivalent `string_view` implementation?

**Comment by AaronBallman** [comment]
It's worth pointing out that some of the static analysis folks have reasons to prefer `span` over `string_view`. See the discussion about span vs string_view in https://reviews.llvm.org/D136811.

**Comment by carlosgalvezp** [comment]
Thanks for the info! From what I can see, the main issue is that it's hard to automatically know if an array of chars is a string or something else? `span<char>` could then be a safe choice to recommend in an automated check. I see they could consider using `string_view` for e.g. `const` array of chars which are typically strings. 

It would be nice to see some concrete use case here to understand if `string_view` could be a reasonable replacement.

**Comment by carlosgalvezp** [comment]
By the way, you can still easily use  `span` directly:

```cpp
int main()
{
    std::span<char const> x = "foo";
    std::cout << x.size() << std::endl;  // prints 4
}
```

**Comment by belobrov-andrey** [comment]
@carlosgalvezp I see that technically string_view would work since "If you just construct the string_view with the raw string, the data pointer points to the static string, which is null-terminated."
But in general string_view does not provide guarantee of null-termination, so it might be bug-prone to have code blocks in large project where it is implicitly assumed that string_view's data() is null terminated.

**Comment by carlosgalvezp** [comment]
@belobrov-andrey I understand that. I was referring to [this comment](https://github.com/llvm/llvm-project/issues/59475#issuecomment-1352785460) where I propose a solution based on `std::span` (which as per [this comment](https://github.com/llvm/llvm-project/issues/59475#issuecomment-1348500922) is what you intend to do?)

As I said, if you could provide a minimal example of your use case it would easier to understand why none of the above options would work.

I'm not against adding the option, but I think not having it offers opportunities for re-thinking and re-designing the code in more modern and safer ways, which is the spirit of the check.
