### ISSUE TITLE
Flaky test llvm\test\Transforms\MergeFunc\fold-weak.ll

### ISSUE THREAD

**Issue by pogo59** [llvm/llvm-project#59481]
I've seen two cases where this test crashed opt with no obvious reason, on different bots.  See:
https://lab.llvm.org/buildbot/#/builders/216/builds/14311
https://lab.llvm.org/buildbot/#/builders/214/builds/4806

The assertion on the first bot was:
```console
Assertion failed: (!Align || *Align <= MaximumAlignment) && "Alignment is greater than MaximumAlignment!", file C:\buildbot-root\llvm-clang-x86_64-sie-win\llvm-project\llvm\lib\IR\Globals.cpp, line 123
```
The previous and next builds both had this test pass. The change where it failed had only test changes, and not to this test.

The second bot hasn't finished its next build yet.

The last person to touch the test was @LebedevRI last week, changing opt command syntax to NPM. Which doesn't mean it's an NPM problem, but that might be when the problem started.

**Comment by LebedevRI** [comment]
Sounds like nondeterminizm?

**Comment by nikic** [comment]
Sanitizer failures indicate that this is due to @gchatelet's changes.

**Comment by gchatelet** [comment]
The change has been reverted. Can you confirm that it's gone?
I'll dig into it to find the root cause.

**Comment by pogo59** [comment]
I can confirm that I haven't seen it again :) although the second bot reported above has been having other issues and hasn't had a clean build since.

**Comment by pogo59** [comment]
https://lab.llvm.org/buildbot/#/builders/236/builds/1395 is the next build on one of the sanitizer bots that caught the test.  These are slow, it may be another hour or two before it reports. Checking on that one should tell us whether the problem has been solved.

**Comment by pogo59** [comment]
Build is green, I'm happy to close this as resolved.
