### ISSUE TITLE
New assert triggered by numba code (https://reviews.llvm.org/D133296)

### ISSUE THREAD

**Issue by folded** [llvm/llvm-project#59490]
The assert triggers because Bits = 1 in 

  assert(Bits % 8 == 0 && "unexpected bit count");

I suspect that it's this IR that's triggering it, but I've attached the whole debug log in case that helps.

  %".141" = alloca i1
  store i1 0, i1* %".141"

[numba_debug.txt](https://github.com/llvm/llvm-project/files/10216523/numba_debug.txt)

**Comment by folded** [comment]
@OCHyams - it looks like this should be assigned to you?

**Comment by OCHyams** [comment]
> @OCHyams - it looks like this should be assigned to you?

Yeah. I've fixed and recommitted ([f354716b052d](https://reviews.llvm.org/rGf354716b052d19b4543617dfe3954503a6827ff8)), thanks!
