### ISSUE TITLE
Emulated TLS does not work on RISC-V

### ISSUE THREAD

**Issue by vit9696** [llvm/llvm-project#59500]
For some reason LLVM does not generate `__emutls_get_address` calls when using `-femulated-tls` on RISC-V.  Example: `clang -C -target riscv32-gnu-linux -O3 -femulated-tls`.

```c
_Thread_local int a;

int fn(void)
{
    if (a)
    {
        return 1;
    }
    return 0;
}
```

```asm
fn():
        lui     a0, %tprel_hi(a)
        add     a0, a0, tp, %tprel_add(a)
        lw      a0, %tprel_lo(a)(a0)
        snez    a0, a0
        ret
```

REF: https://godbolt.org/z/fovqox7az

**Comment by kito-cheng** [comment]
RISC-V ABI has defined a dedicated register for thread pointer, so we don't need to support emulated TLS in theory.

**Comment by vit9696** [comment]
We make private use of generic emutls abi on one of our targets for portability and easier certification reasons.

**Comment by jrtc27** [comment]
Up until now it’s been a deliberate decision to not support emulated TLS, it’s terrible for performance and adds toolchain complexity.

**Comment by vit9696** [comment]
- All other targets support this without an issue. So does gcc.
- Checking target lowering code shows me that the support for emutls is as large as adding one if.

**Comment by jrtc27** [comment]
https://reviews.llvm.org/D102527 has the previous discussion

**Comment by vit9696** [comment]
Well, we are not using OpenBSD and the reasons in that differential are irrelevant for us. We do not use `libclang_rt.builtins` and its lazy allocations with `malloc`, our emutls implementation is deterministic and statically allocated at compile time.

**Comment by hiraditya** [comment]
Should we add `-fno-emulated-tls` to default compiler flags for RISC-V and possibly add a warning/error when `-femulated-tls` is passed?

**Comment by arichardson** [comment]
Silently ignoring the flag when GCC supports it seems bad to me, so IMO emitting an error that `-femulated-tls` is not supported would be a good idea.

**Comment by ilovepi** [comment]
https://reviews.llvm.org/D143619 and https://reviews.llvm.org/D143619 should improve the situation.

**Comment by appujee** [comment]
> https://reviews.llvm.org/D143619 and https://reviews.llvm.org/D143619 should improve the situation.

you wanted to mention two different patches?

**Comment by hiraditya** [comment]
> https://reviews.llvm.org/D143619 and https://reviews.llvm.org/D143619 should improve the situation.

you wanted to mention two different patches?

**Comment by ilovepi** [comment]
It helps to `CTRL-C` `CTRL-V` correctly ...

https://reviews.llvm.org/D143692 and https://reviews.llvm.org/D143619
