### ISSUE TITLE
[ADT] APSInt::getExtValue() - assumes signed bounds

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#59515]
This was noticed on D139683 by @DataCorrupted 
```cpp
  /// Get the correctly-extended \c int64_t value.
  int64_t getExtValue() const {
    assert(getMinSignedBits() <= 64 && "Too many bits for int64_t");
    return isSigned() ? getSExtValue() : getZExtValue();
  }
```
For the unsigned case we should be asserting `getActiveBits() <= 64` instead

**Comment by DataCorrupted** [comment]
I'll try to fix it and include a `tryExtValue()`.

**Comment by efriedma-quic** [comment]
> we should be asserting `getActiveBits() <= 64`

Do you mean `getActiveBits() <= 63`?  We don't want to turn a positive number into a negative number.

**Comment by DataCorrupted** [comment]
This... is the tricky part. I wrote `<= 63`, but then crashed ~10 unit tests. Still working on it. Seems people **expected** to get negative number

**Comment by DataCorrupted** [comment]
> This... is the tricky part. I wrote `<= 63`, but then crashed ~10 unit tests. Still working on it. Seems people **expected** to get negative number

nvm, my own mistake. The patch is ready for review here: https://reviews.llvm.org/D140059

**Comment by DataCorrupted** [comment]
Closed as done by https://github.com/llvm/llvm-project/commit/7859d6e79ca90df2f3f206192a1dfa89e3cb10f1

**Comment by DataCorrupted** [comment]
Closed as done by https://github.com/llvm/llvm-project/commit/0a89825a289d149195be390003424adad026067f
