### ISSUE TITLE
[clang] Initialise static in templated class

### ISSUE THREAD

**Issue by Ignition** [llvm/llvm-project#59514]
```cpp
//template definition
template<typename T>
struct S
{
    static int thing;
};
// extern template instantiation
extern template struct S<double>;


// in .cpp
// template instantiation
template struct S<double>;

// initialise the static storage
template<> int S<double>::thing = 42;
```

Works in GCC and MSVC [godbolt](https://godbolt.org/z/TjEc6vqWT)

**Comment by shafik** [comment]
I believe clang is correct here according to [temp.expl.spec p7](https://eel.is/c++draft/temp.expl.spec#7) which says:

> ... If the program does not provide a definition for an explicit specialization and either the specialization is used in a way that would cause an implicit instantiation to take place or the member is a virtual member function, the program is ill-formed, no diagnostic required[.](https://eel.is/c++draft/temp.expl.spec#7.sentence-2) ...

The [tests here](https://github.com/llvm/llvm-project/blob/main/clang/test/CXX/temp/temp.spec/temp.expl.spec/examples.cpp) also cover similar situations.

If you move the specialization before the `extern template` all compilers accept it godbolt:  https://godbolt.org/z/rnTjqrzE1
