### ISSUE TITLE
Dependent static_assert fails inside if constexpr

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#59520]
The following doesn't compile, but it seems like it should:

```shell
cat <<EOF | clang++ -xc++ - -std=c++20 -fsyntax-only
#include <type_traits>

template <typename T>
void f() {
	auto lambda = []<typename U>(U) {
		if constexpr (std::is_same_v<T, bool> && std::is_same_v<U, int>) {
			static_assert(std::is_same_v<T, bool>);
		}
	};
    lambda(0);
}

int main() {
	f<long>();
}
EOF
```

Fails with:

```console
<stdin>:7:4: error: static assertion failed due to requirement 'std::is_same_v<long, bool>'
                        static_assert(std::is_same_v<T, bool>);
                        ^             ~~~~~~~~~~~~~~~~~~~~~~~
<stdin>:14:2: note: in instantiation of function template specialization 'f<long>' requested here
        f<long>();
        ^
1 error generated.
```

It seems like this should work since the `if constexpr` condition is dependent on `T`?

Godbolt: https://godbolt.org/z/jf7hWdYWz

GCC accepts this. MSVC fails like Clang.

**Comment by shafik** [comment]
I believe this is IFNDR (ill-formed no diagnostic required) due to [temp.res p6.1](http://eel.is/c++draft/temp.res#general-6.1):

> The program is ill-formed, no diagnostic required, if:
> - no valid specialization can be generated for a template or a substatement of a [constexpr if](http://eel.is/c++draft/stmt.if#def:constexpr_if) statement within a template and the template is not instantiated, or

If we remove the `&& std::is_same_v<U, int>` all the compilers accept it: https://godbolt.org/z/x7rYqWr8b

**Comment by cor3ntin** [comment]
This was fixed (Most likely CWG2518)
