### ISSUE TITLE
Updating lldb to latest version 15.0.6

### ISSUE THREAD

**Issue by Hermit97** [llvm/llvm-project#59527]
I am trying update my lldb to the latest stable version 15.0.6. I'm currently on 10.0.0. My os is Linux mint. The way I was trying was downloading the release from https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.6 but after extracting it i'm not sure what to do next.

**Comment by Hermit97** [comment]
So I added it to my path export PATH="/home/tools/clang+llvm-15.0.6-x86_64-linux-gnu-ubuntu-18.04/bin:$PATH"
but after doing source /.bashrc the version of lldb still says 10.0.0

**Comment by EugeneZelenko** [comment]
@Hermit97: What does `which llbd`  print? Could you try to invoke LLDB 15 via full path to binary?

**Comment by Hermit97** [comment]
I'm not sure how to do that could you elaborate a bit more please.

**Comment by Hermit97** [comment]
I figured it out, I had downloaded the aarch64 instead of x86-64. 
I got it to work now you can close this thank you.
