### ISSUE TITLE
[clang-format] `C++20` `SpacesInSquareBrackets` Lambda Failure Case with Template Non-Type Parameter Pack

### ISSUE THREAD

**Issue by Eshnek** [llvm/llvm-project#59522]
I am having an issue with the `clang-format` `SpacesInSquareBrackets` option:
```cpp
constexpr int i {};
[ &i]< size_t... > {};
```

It appears this is an edge failure case:
```cpp
[ & ]< size_t... > {};
```
```cpp
constexpr int i {};
[ &i ]< size_t > {};
```
```cpp
constexpr int i {};
[ &i ]< typename... T > {};
```

**Comment by rymiel** [comment]
This was (probably inadvertently) fixed by 247613548bac55b47eed88e83d5c8640fd4b200a. This fix isn't yet present in any released version, but will be present in `clang-format 16`
