### ISSUE TITLE
libcxx: when libcxx is compiled on Windows 8+ and chrono is used, the resulting binaries are unable to run on Windows 7.

### ISSUE THREAD

**Issue by LukeUsher** [llvm/llvm-project#59539]
We recently received a bug report that the latest nightly builds of one of our products no longer function on Windows 7; throwing an error that GetSystemTimePreciseAsFileTime can not be found.

We have not updated our application to use this function, and neither have any of our third party components, but we did recently switch from gcc to clang for automated builds.

After investigating, a specific codepath within libcxx appears to be the problem.

libcxx contains the following code

https://github.com/llvm/llvm-project/blob/2e999b7dd1934a44d38c3a753460f1e5a217e9a5/libcxx/src/chrono.cpp#L105
```c++
#if (_WIN32_WINNT >= _WIN32_WINNT_WIN8 && WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)) || \
    (_WIN32_WINNT >= _WIN32_WINNT_WIN10)
  GetSystemTimePreciseAsFileTime(&ft);
#elif !WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
  GetSystemTimeAsFileTime(&ft);
#else
  GetSystemTimeAsFileTimeFunc.fp(&ft);
#endif
```

When libcxx is compiled on Windows 8+, this results in generating a code path that makes use of GetSystemTimePreciseAsFileTime, which is unavailable on Windows 7; when an affected build of libcxx is shipped as a pre-compiled binary, for example, by mingw-w64/msys2, linking against it results in an application that can not run on Windows 7, despite being otherwise compatible.

Interestingly, there is already a runtime check for this, so perhaps the #if chain is not required and `GetSystemTimeAsFileTimeFunc.fp(&ft);` can be used in all cases?

See
https://github.com/llvm/llvm-project/blob/2e999b7dd1934a44d38c3a753460f1e5a217e9a5/libcxx/src/chrono.cpp#L76
```c++
typedef void(WINAPI *GetSystemTimeAsFileTimePtr)(LPFILETIME);

class GetSystemTimeInit {
public:
  GetSystemTimeInit() {
    fp = (GetSystemTimeAsFileTimePtr)GetProcAddress(
        GetModuleHandleW(L"kernel32.dll"), "GetSystemTimePreciseAsFileTime");
    if (fp == nullptr)
      fp = GetSystemTimeAsFileTime;
  }
  GetSystemTimeAsFileTimePtr fp;
};
```

**Comment by efriedma-quic** [comment]
CC @mstorsjo

**Comment by mstorsjo** [comment]
> When libcxx is compiled on Windows 8+

It’s not about what OS you’re compiling it _on_, but about what the `_WIN32_WINNT` define is set to. This is customarily set to the lowest OS level you want to target when building the library. Thus, if you set it to a lower version, it will try to load the function at runtime instead.

See https://reviews.llvm.org/D104987 for the review that lead up to this code.

**Comment by LukeUsher** [comment]
> > When libcxx is compiled on Windows 8+
> 
> It’s not about what OS you’re compiling it _on_, but about what the `_WIN32_WINNT` define is set to. This is customarily set to the lowest OS level you want to target when building the library. Thus, if you set it to a lower version, it will try to load the function at runtime instead.
> 
> See https://reviews.llvm.org/D104987 for the review that lead up to this code.

So it is expected that all users of llvm compile from source code to set the target platform rather than use binary distributions that may ship with operating systems or tool chains? 

It’s not always practical to compile llvm from source as well as our projects in the ci pipeline when binary packages are provided, especially when charged per-minute of build time.

**Comment by efriedma-quic** [comment]
> So it is expected that all users of llvm compile from source code to set the target platform rather than use binary distributions that may ship with operating systems or tool chains?

No, we expect the people building those operating systems/tool chains to pick appropriate defaults.  In most cases, that's not llvm.org; we do ship release binaries, but most people get builds from various vendors.

If mingw-w64 binaries aren't built correctly, I think you need to report the issue directly to them.

**Comment by efriedma-quic** [comment]
> If mingw-w64 binaries aren't built correctly, I think you need to report the issue directly to them.

Looking a bit more closely, I guess the actual package you're referring to question is built by the msys2 project.

**Comment by LukeUsher** [comment]
Thank for pointing me in the right direction; it looks like mingw-w64 has updated their minver to Windows 8.1 now, which is why this manifested on our Github Actions CI.

**Comment by mstorsjo** [comment]
This issue should have been resolved downstream now, in https://github.com/msys2/MINGW-packages/pull/14774.
