### ISSUE TITLE
ld.lld: error: undefined symbol but the symbol exists?

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#59536]
Hi!

We are bumping our compiler from 1ae33bf42680b156fe0f5cd6163bf24ef45d8cd3 to 61311f3c9363534eda3bc9b8a5edbab80048cdd4 and now we get the following linker error in our code:

```
ld.lld: error: undefined symbol: Eigen::Matrix<double, 2, 1, 0, 2, 1>::Matrix()
>>> referenced by foo.cpp
>>>               foo.pic.o
>>> did you mean: Eigen::Matrix<double, 2, 1, 0, 2, 1>::Matrix()
>>> defined in: bar.a
```

I'm not sure what the error message is trying to tell me - the symbol is clearly available, what exactly is the problem? I don't know what action I should take as a user to fix this.

To clarify, `foo.cpp` includes `<Eigen/Core>` which should provide the definition for `Eigen::Matrix` so I can't really tell what the problem is.

**Comment by EugeneZelenko** [comment]
@carlosgalvezp: Could you please provide reproducer?

**Comment by carlosgalvezp** [comment]
Sure, will do!

**Comment by carlosgalvezp** [comment]
It seems the problem is fixes on latest master. In case someone wants to investigate further and reproduce, here's a minimal example. The problem lies on Clang, not LLD:

```cpp
#include <Eigen/Core>

class Foo
{
 private:  // Making this public solves the problem!
    Eigen::Vector2d x_{};
};

struct Bar  // Removing this struct solves the problem!
{
    Foo y_{};
};

int main()
{
    Foo z{};
    return 0;
}

```

Full build script:

```bash
#!/usr/bin/env bash
wget https://gitlab.com/libeigen/eigen/-/archive/3.3.8/eigen-3.3.8.tar.gz
tar -xzf eigen-3.3.8.tar.gz
clang -std=c++14 -isystem eigen-3.3.8 main.cpp
```

Error:
```
/usr/bin/ld: /tmp/main-1ebc66.o: in function `Foo::Foo()':
main.cpp:(.text._ZN3FooC2Ev[_ZN3FooC2Ev]+0x11): undefined reference to `Eigen::Matrix<double, 2, 1, 0, 2, 1>::Matrix()'
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```
