### ISSUE TITLE
How to apply optimization passes to a single function?

### ISSUE THREAD

**Issue by yuemonangong** [llvm/llvm-project#59532]
The command `opt -S src.ll -o des.ll -pass1 -pass2 -pass3` can apply the specific passes to a '.ll' file. 
The question is, how to apply `-pass1 -pass2 -pass3` to a specific function in `src.ll` without modifying other functions.
Is there an API or command line to achieve this?
Thank you very much.

**Comment by nikic** [comment]
I don't think so, but possibly using `llvm-extract` to extract only the function and then running opt might be useful? You could also link the two IR modules again afterwards (though don't ask me how, maybe llvm-link).

**Comment by yuemonangong** [comment]
> I don't think so, but possibly using `llvm-extract` to extract only the function and then running opt might be useful? You could also link the two IR modules again afterwards (though don't ask me how, maybe llvm-link).

Thank you. It seems to work. I'll try it. Thanks again.

**Comment by fhahn** [comment]
For questions about using LLVM, please use https://discourse.llvm.org
