### ISSUE TITLE
Could Not Compile Normally: UNREACHABLE executed at /root/llvm-project/clang/lib/Driver/ToolChains/MinGW.cpp:138!

### ISSUE THREAD

**Issue by LeGend-wLw** [llvm/llvm-project#59545]
Even HelloWorld Could Not Pass Compile

When define `--target=x86_x64-pc-windows-gnu`,

```console
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: "C:\\Program Files\\LLVM\\bin\\clang++.exe" --target=x86_x64-pc-windows-gnu d:\\Algorithm\\10-1.cpp -fdiagnostics-color=always -m64 -g -I d:\\Algorithm\\include -o d:\\Algorithm\\Out\\10-1.exe -std=c++17 -Wall -O0 -fexec-charset=utf-8 -finput-charset=utf-8
1.      Compilation construction
2.      Building compilation jobs
3.      Building compilation jobs
Exception Code: 0xC0000005
#0 0x00007ff76e58cfb0 C:\Program Files\LLVM\bin\clang++.exe 0x189cfb0 C:\Program Files\LLVM\bin\clang++.exe 0x7b6ff0
#1 0x00007ff76e58cfb0 C:\Program Files\LLVM\bin\clang++.exe 0x7b483e C:\Program Files\LLVM\bin\clang++.exe 0x7a952e
#2 0x00007ff76e58cfb0 C:\Program Files\LLVM\bin\clang++.exe 0x7a1eb0 C:\Program Files\LLVM\bin\clang++.exe 0x40bf
#3 0x00007ff76e58cfb0 C:\Program Files\LLVM\bin\clang++.exe 0x41ea730 (C:\Program Files\LLVM\bin\clang++.exe+0x189cfb0)
#4 0x00007ff76e58cfb0
#5 0x00007ff76e58cfb0 (C:\Program Files\LLVM\bin\clang++.exe+0x189cfb0)
0x00007FF76E58CFB0, C:\Program Files\LLVM\bin\clang++.exe(0x00007FF76CCF0000) + 0x189CFB0 byte(s)
0x00007FF76D4A6FF0, C:\Program Files\LLVM\bin\clang++.exe(0x00007FF76CCF0000) + 0x7B6FF0 byte(s)
0x00007FF76D4A483E, C:\Program Files\LLVM\bin\clang++.exe(0x00007FF76CCF0000) + 0x7B483E byte(s)
0x00007FF76D49952E, C:\Program Files\LLVM\bin\clang++.exe(0x00007FF76CCF0000) + 0x7A952E byte(s)
0x00007FF76D491EB0, C:\Program Files\LLVM\bin\clang++.exe(0x00007FF76CCF0000) + 0x7A1EB0 byte(s)
0x00007FF76CCF40BF, C:\Program Files\LLVM\bin\clang++.exe(0x00007FF76CCF0000) + 0x40BF byte(s)
0x00007FF770EDA730, C:\Program Files\LLVM\bin\clang++.exe(0x00007FF76CCF0000) + 0x41EA730 byte(s)
0x00007FFFE23255A0, C:\WINDOWS\System32\KERNEL32.DLL(0x00007FFFE2310000) + 0x155A0 byte(s), BaseThreadInitThunk() + 0x10 byte(s)
0x00007FFFE3C4485B, C:\WINDOWS\SYSTEM32\ntdll.dll(0x00007FFFE3C40000) + 0x485B byte(s), RtlUserThreadStart() + 0x2B byte(s)
```

When Define `--target=x86_x64-pc-windows-msvc`

```console
clang++: error: unable to execute command: program not executable
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by fhahn** [comment]
Please provide more details.  Are you using a version of clang built yourself with your own changes? Please also include that file where the compiler crashes (the preprocessed sources should be created by clang on crash)

**Comment by LeGend-wLw** [comment]
I'm using Realese Version 15.x and The Compiler dose not generate any other file.

**Comment by LeGend-wLw** [comment]
I build A debug version clang .it seem provide more information

`D:/llvm-project-release-15.x/build/Debug/bin/clang++.exe --target=x86_x64-pc-windows-gnu d:\Algorithm\10-1.cpp -fdiagnostics-color=always -m64 -g -I d:\Algorithm\include -o d:\Algorithm\Out\10-1.exe -std=c++17 -Wall -O0 -fexec-charset=utf-8 -finput-charset=utf-8 

Unsupported target architecture.
UNREACHABLE executed at D:\llvm-project-release-15.x\clang\lib\Driver\ToolChains\MinGW.cpp:138!     
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: D:\\llvm-project-release-15.x\\build\\Debug\\bin\\clang++.exe --target=x86_x64-pc-windows-gnu d:\\Algorithm\\10-1.cpp -fdiagnostics-color=always -m64 -g -I d:\\Algorithm\\include -o d:\\Algorithm\\Out\\10-1.exe -std=c++17 -Wall -O0 -fexec-charset=utf-8 -finput-charset=utf-8
1.      Compilation construction
2.      Building compilation jobs
3.      Building compilation jobs
Exception Code: 0x80000003
 #0 0x00007ff7974f852c HandleAbort D:\llvm-project-release-15.x\llvm\lib\Support\Windows\Signals.inc:414:0
 #1 0x00007ffba69590ed (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0xa90ed)
 #2 0x00007ffba695ae49 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0xaae49)
 #3 0x00007ff7974cb58f llvm::llvm_unreachable_internal(char const *, char const *, unsigned int) D:\llvm-project-release-15.x\llvm\lib\Support\ErrorHandling.cpp:218:0
 #4 0x00007ff798aeb06f clang::driver::tools::MinGW::Linker::ConstructJob(class clang::driver::Compilation &, class clang::driver::JobAction const &, class clang::driver::InputInfo const &, class llvm::SmallVector<class clang::driver::InputInfo, 4> const &, class llvm::opt::ArgList const &, char const *) const D:\llvm-project-release-15.x\clang\lib\Driver\ToolChains\MinGW.cpp:141:0
 #5 0x00007ff79893eb49 clang::driver::Driver::BuildJobsForActionNoCache(class clang::driver::Compilation &, class clang::driver::Action const *, class clang::driver::ToolChain const *, class llvm::StringRef, bool, bool, char const *, class std::map<struct std::pair<class clang::driver::Action const *, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>>, class llvm::SmallVector<class clang::driver::InputInfo, 4>, struct std::less<struct std::pair<class clang::driver::Action const *, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>>>, class std::allocator<struct std::pair<struct std::pair<class clang::driver::Action const *, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>> const, class llvm::SmallVector<class clang::driver::InputInfo, 4>>>> &, enum clang::driver::Action::OffloadKind) const D:\llvm-project-release-15.x\clang\lib\Driver\Driver.cpp:5495:0
 #6 0x00007ff798936ce3 clang::driver::Driver::BuildJobsForAction(class clang::driver::Compilation &, class clang::driver::Action const *, class clang::driver::ToolChain const *, class llvm::StringRef, bool, bool, char const *, class std::map<struct std::pair<class clang::driver::Action const *, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>>, class llvm::SmallVector<class clang::driver::InputInfo, 4>, struct std::less<struct std::pair<class clang::driver::Action const *, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>>>, class std::allocator<struct std::pair<struct std::pair<class clang::driver::Action const *, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>> const, class llvm::SmallVector<class clang::driver::InputInfo, 4>>>> &, enum clang::driver::Action::OffloadKind) const D:\llvm-project-release-15.x\clang\lib\Driver\Driver.cpp:5189:0
 #7 0x00007ff79893118a clang::driver::Driver::BuildJobs(class clang::driver::Compilation &) const D:\llvm-project-release-15.x\clang\lib\Driver\Driver.cpp:4731:0
 #8 0x00007ff79892b34a clang::driver::Driver::BuildCompilation(class llvm::ArrayRef<char const *>) D:\llvm-project-release-15.x\clang\lib\Driver\Driver.cpp:1390:0
 #9 0x00007ff7927a5dce clang_main(int, char **) D:\llvm-project-release-15.x\clang\tools\driver\driver.cpp:484:0
#10 0x00007ff7927e678c main D:\llvm-project-release-15.x\build\tools\clang\tools\driver\clang-driver.cpp:11:0
#11 0x00007ff79f0170b9 invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:79:0
#12 0x00007ff79f016f5e __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288:0
#13 0x00007ff79f016e1e __scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331:0
#14 0x00007ff79f01714e mainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:17:0
#15 0x00007ffc681b244d (C:\WINDOWS\System32\KERNEL32.DLL+0x1244d)
#16 0x00007ffc691cdfb8 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x5dfb8)`

**Comment by BertalanD** [comment]
The `x86_x64-pc-windows-gnu` target triple is invalid. The architecture needs to be `x86_64` instead of `x86_x64`. 

We probably should verify and diagnose it rather than crash, though.

**Comment by LeGend-wLw** [comment]
Yes,when It changed to x86_64 it really normal. And I found target dose not have any verification.

**Comment by k-mana** [comment]
Still crashes on current `trunk`: https://godbolt.org/z/8e5zohE9T
### backtrace:
```
Unsupported target architecture.
UNREACHABLE executed at /root/llvm-project/clang/lib/Driver/ToolChains/MinGW.cpp:138!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -target x86_x64-pc-windows-gnu <source> -L. -Wl,-rpath,. -Wl,-rpath,/opt/compiler-explorer/gcc-snapshot/lib64 -Wl,-rpath,/opt/compiler-explorer/gcc-snapshot/lib32
1.	Compilation construction
2.	Building compilation jobs
3.	Building compilation jobs
 #0 0x000055a4b244026f llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3c7926f)
 #1 0x000055a4b243d994 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007fd4b035b420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007fd4afe2800b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #4 0x00007fd4afe07859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #5 0x000055a4b23963fe (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3bcf3fe)
 #6 0x000055a4b2dba297 clang::driver::tools::MinGW::Linker::ConstructJob(clang::driver::Compilation&, clang::driver::JobAction const&, clang::driver::InputInfo const&, llvm::SmallVector<clang::driver::InputInfo, 4u> const&, llvm::opt::ArgList const&, char const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x45f3297)
 #7 0x000055a4b2ca1fbc clang::driver::Driver::BuildJobsForActionNoCache(clang::driver::Compilation&, clang::driver::Action const*, clang::driver::ToolChain const*, llvm::StringRef, bool, bool, char const*, std::map<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, llvm::SmallVector<clang::driver::InputInfo, 4u>, std::less<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>, std::allocator<std::pair<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>> const, llvm::SmallVector<clang::driver::InputInfo, 4u>>>>&, clang::driver::Action::OffloadKind) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44dafbc)
 #8 0x000055a4b2ca3620 clang::driver::Driver::BuildJobsForAction(clang::driver::Compilation&, clang::driver::Action const*, clang::driver::ToolChain const*, llvm::StringRef, bool, bool, char const*, std::map<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, llvm::SmallVector<clang::driver::InputInfo, 4u>, std::less<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>, std::allocator<std::pair<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>> const, llvm::SmallVector<clang::driver::InputInfo, 4u>>>>&, clang::driver::Action::OffloadKind) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44dc620)
 #9 0x000055a4b2ca3dd1 clang::driver::Driver::BuildJobs(clang::driver::Compilation&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44dcdd1)
#10 0x000055a4b2cb4d75 clang::driver::Driver::BuildCompilation(llvm::ArrayRef<char const*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44edd75)
#11 0x000055a4af9a537c clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x11de37c)
#12 0x000055a4af8b1605 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x10ea605)
#13 0x00007fd4afe09083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#14 0x000055a4af99edce _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x11d7dce)
Compiler returned: 139
```

Other patterns: `x86_x64-pc-windows-itanium`
### backtrace:
```
unsupported architecture
UNREACHABLE executed at /root/llvm-project/clang/lib/Driver/ToolChains/CrossWindows.cpp:97!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -target x86_x64-pc-windows-itanium <source> -L. -Wl,-rpath,. -Wl,-rpath,/opt/compiler-explorer/gcc-snapshot/lib64 -Wl,-rpath,/opt/compiler-explorer/gcc-snapshot/lib32
1.	Compilation construction
2.	Building compilation jobs
3.	Building compilation jobs
 #0 0x000055c3646f63ef llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3c6b3ef)
 #1 0x000055c3646f3b14 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f953c26b420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007f953bd3800b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #4 0x00007f953bd17859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #5 0x000055c36464c57e (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3bc157e)
 #6 0x000055c364ff3c06 clang::driver::tools::CrossWindows::Linker::ConstructJob(clang::driver::Compilation&, clang::driver::JobAction const&, clang::driver::InputInfo const&, llvm::SmallVector<clang::driver::InputInfo, 4u> const&, llvm::opt::ArgList const&, char const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4568c06)
 #7 0x000055c364f5811c clang::driver::Driver::BuildJobsForActionNoCache(clang::driver::Compilation&, clang::driver::Action const*, clang::driver::ToolChain const*, llvm::StringRef, bool, bool, char const*, std::map<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, llvm::SmallVector<clang::driver::InputInfo, 4u>, std::less<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>, std::allocator<std::pair<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>> const, llvm::SmallVector<clang::driver::InputInfo, 4u>>>>&, clang::driver::Action::OffloadKind) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44cd11c)
 #8 0x000055c364f59780 clang::driver::Driver::BuildJobsForAction(clang::driver::Compilation&, clang::driver::Action const*, clang::driver::ToolChain const*, llvm::StringRef, bool, bool, char const*, std::map<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, llvm::SmallVector<clang::driver::InputInfo, 4u>, std::less<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>, std::allocator<std::pair<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>> const, llvm::SmallVector<clang::driver::InputInfo, 4u>>>>&, clang::driver::Action::OffloadKind) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44ce780)
 #9 0x000055c364f59f31 clang::driver::Driver::BuildJobs(clang::driver::Compilation&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44cef31)
#10 0x000055c364f6aed5 clang::driver::Driver::BuildCompilation(llvm::ArrayRef<char const*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44dfed5)
#11 0x000055c361c6828c clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x11dd28c)
#12 0x000055c361b74605 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x10e9605)
#13 0x00007f953bd19083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#14 0x000055c361c61cde _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x11d6cde)
Compiler returned: 139
```

**Comment by fhahn** [comment]
> Can I send a patch?

Sure that would be great! Please see https://llvm.org/docs/Contributing.html for information about how to contribute to LLVM/Clang

**Comment by k-mana** [comment]
https://reviews.llvm.org/D148944
