### ISSUE TITLE
Compiler Crush On Windows 

### ISSUE THREAD

**Issue by LeGend-wLw** [llvm/llvm-project#59544]
Even Hello Wold Could Not Pass Compile

When define "--target=x86_x64-pc-windows-gnu",

PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: "C:\\Program Files\\LLVM\\bin\\clang++.exe" --target=x86_x64-pc-windows-gnu d:\\Algorithm\\10-1.cpp -fdiagnostics-color=always -m64 -g -I d:\\Algorithm\\include -o d:\\Algorithm\\Out\\10-1.exe -std=c++17 -Wall -O0 -fexec-charset=utf-8 -finput-charset=utf-8
1.      Compilation construction
2.      Building compilation jobs
3.      Building compilation jobs
Exception Code: 0xC0000005
#0 0x00007ff76e58cfb0 C:\Program Files\LLVM\bin\clang++.exe 0x189cfb0 C:\Program Files\LLVM\bin\clang++.exe 0x7b6ff0
#1 0x00007ff76e58cfb0 C:\Program Files\LLVM\bin\clang++.exe 0x7b483e C:\Program Files\LLVM\bin\clang++.exe 0x7a952e
#2 0x00007ff76e58cfb0 C:\Program Files\LLVM\bin\clang++.exe 0x7a1eb0 C:\Program Files\LLVM\bin\clang++.exe 0x40bf
#3 0x00007ff76e58cfb0 C:\Program Files\LLVM\bin\clang++.exe 0x41ea730 (C:\Program Files\LLVM\bin\clang++.exe+0x189cfb0)
#4 0x00007ff76e58cfb0
#5 0x00007ff76e58cfb0 (C:\Program Files\LLVM\bin\clang++.exe+0x189cfb0)
0x00007FF76E58CFB0, C:\Program Files\LLVM\bin\clang++.exe(0x00007FF76CCF0000) + 0x189CFB0 byte(s)
0x00007FF76D4A6FF0, C:\Program Files\LLVM\bin\clang++.exe(0x00007FF76CCF0000) + 0x7B6FF0 byte(s)
0x00007FF76D4A483E, C:\Program Files\LLVM\bin\clang++.exe(0x00007FF76CCF0000) + 0x7B483E byte(s)
0x00007FF76D49952E, C:\Program Files\LLVM\bin\clang++.exe(0x00007FF76CCF0000) + 0x7A952E byte(s)
0x00007FF76D491EB0, C:\Program Files\LLVM\bin\clang++.exe(0x00007FF76CCF0000) + 0x7A1EB0 byte(s)
0x00007FF76CCF40BF, C:\Program Files\LLVM\bin\clang++.exe(0x00007FF76CCF0000) + 0x40BF byte(s)
0x00007FF770EDA730, C:\Program Files\LLVM\bin\clang++.exe(0x00007FF76CCF0000) + 0x41EA730 byte(s)
0x00007FFFE23255A0, C:\WINDOWS\System32\KERNEL32.DLL(0x00007FFFE2310000) + 0x155A0 byte(s), BaseThreadInitThunk() + 0x10 byte(s)
0x00007FFFE3C4485B, C:\WINDOWS\SYSTEM32\ntdll.dll(0x00007FFFE3C40000) + 0x485B byte(s), RtlUserThreadStart() + 0x2B byte(s)

When Define --target=x86_x64-pc-windows-msvc

clang++: error: unable to execute command: program not executable
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by EugeneZelenko** [comment]
Duplicate of #59545.
