### ISSUE TITLE
Any options that enable loop inversion?

### ISSUE THREAD

**Issue by 2994186010** [llvm/llvm-project#59565]
Are there any options that enable loop inversion?  More specifically，can LLVM transform the while form loop into do-while form loop as the following.

Before the transformation, the code is:
```
void foo(unsigned a, unsigned& ret) {
  bool undone = true;
  #pragma unroll 4
  while((a > 0) && undone) {
    ++ret;
    if(ret > 2)  undone = false;
    if(undone)   --a;
  }
}
```

After the transformation, the code is:
```
void foo(unsigned a, unsigned& ret) {
  bool undone = true;
  #pragma unroll 4
  if((a > 0) && undone) {
    do {
      ++ret;
      if(ret > 2)  undone = false;
      if(undone)   --a;
    while((a > 0) && undone);
  }
}
```

**Comment by 2994186010** [comment]
@rafaelauler @FPar @spupyrev , can bolt/Passes/LoopInversionPass.cpp implement the loop inversion transformation mentioned in this issue?

**Comment by nikic** [comment]
The canonical name of this transform is "loop rotation", performed by the [LoopRotation](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/Scalar/LoopRotation.cpp) pass in LLVM.

**Comment by 2994186010** [comment]
@nikic , is there any command in LLVM that can implement the result like "./one-LLVM-cmd -in transform-before.cpp -out transform-after.cpp"?

**Comment by nikic** [comment]
LLVM does not perform optimizations on C++ code, so no.
