### ISSUE TITLE
[avr] Wrong code: Incorrect resolution of operand modifier

### ISSUE THREAD

**Issue by sprintersb** [llvm/llvm-project#59577]
Compile with
` --target=avr -mmcu=atmega8 -Os -c`
the following C code:
```c
void func (void)
{
    __asm volatile ("ldi r16, -hi8(0x3ff)");
}
```
Resulting disassembly from `x.o`  reads:
```none
Disassembly of section .text:

00000000 <func>:
   0:	0c ef       	ldi	r16, 0xFC	; 252
   2:	08 95       	ret
```
which is wrong: It's `hi8(0x3ff) = 0x3` and `-0x3 = -hi8(0x3ff) = 0xfd` in 2's complement.

What the assembler appears to be computing is `hi8(-(val))`, at least that's what follows from code for address computations  into static arrays like in:
```c
extern int var[];
// Link with -Wl,--defsym,var=0x3ff
void func (int n)
{
    return var[n];
}
```
where `x.s` reads:
```
func:
	lsl	r24
	rol	r25
	subi	r24, -lo8(var) ; should be lo8(-(x))
	sbci	r25, -hi8(var) ; should be hi8(-(x))
	...
```
Notice that the semantically correct expressions are `lo8(-(x))` and `hi8(-(x))` because you want to subtract the negative of a 16-bit value, cf. for example what avr-gcc is doing.

Strangely, that offset computation is correct even when the negation produces a borrow from bit 7 to bit 8.

**Comment by benshi001** [comment]
I tried to compile your code with avr-gcc-5.4, but avr-gcc reported an error 

```
(base) benshi@BJSW-T026:/tmp$ avr-gcc a.c -O3 -Wall -c -mmcu=atmega328
/tmp/ccDLJnbh.s: Assembler messages:
/tmp/ccDLJnbh.s:17: Error: garbage at end of line
/tmp/ccDLJnbh.s:17: Error: can't resolve `0' {*ABS* section} - `hi8' {*UND* section}
/tmp/ccDLJnbh.s:17: Error: expression too complex
```

**Comment by sprintersb** [comment]
> I tried to compile your code with avr-gcc-5.4,

avr-as won't assemble it because such RELOCs don't exists to begin with. So presumably, clang is doing correct code but displays it in the wrong way.

My guess is that llvm is printing `-hi8(x)` where it should actually print `hi8(-(x))`.  The latter *is* supported as RELOC, and it's what avr-gcc will use to add 16-bit symbolic offsets (by SUBI-subtracting `lo8(-(x))` from the low byte and SBCI `hi8(-(x))` from the high byte).

**Comment by benshi001** [comment]
clang should explicitly reject such assembly

```
	subi	r24, -lo8(var)
	sbci	r25, -hi8(var)
```

**Comment by benshi001** [comment]
fixed by patch https://reviews.llvm.org/D140473

**Comment by benshi001** [comment]
fixed in https://github.com/llvm/llvm-project/commit/c41d425030dfd5cd84eb89b861e157821f2bf45f
