### ISSUE TITLE
[llvm-cov]Why do all my swift files get 0 branch coverage

### ISSUE THREAD

**Issue by ZhengXiuQun** [llvm/llvm-project#59583]
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/6290069/208396303-b9aad779-f5f5-4507-a993-34146cfd73ea.png">

**Comment by fhahn** [comment]
This is probably a Swift issue and should be reported on the Swift issue tracker

**Comment by keith** [comment]
Branch coverage is relatively new in llvm. It's likely the swift compiler doesn't yet support this at all, in which case there's nothing you can do to your swift code to make it work yet. You should file an issue on the apple/swift repo for supporting this
