### ISSUE TITLE
miscompilation? with 3010f60381bcd828d1b409cfaa576328bcd05bbc on RISCV

### ISSUE THREAD

**Issue by compnerd** [llvm/llvm-project#59594]
With 3010f60381bcd828d1b409cfaa576328bcd05bbc the following code seems to yield unexpected results:

```c
void Fill(unsigned char* buffer, int n) {
  for (int i = 0; i < n; i++)
    buffer[i] = (i & 0xff);
}
```

This behavioural change only appears on optimized builds with the v extension).

BB2 seems to loose the advancement of the indicies value (`vadd.vx v8, v8, a3`).

Before:
```asm
_Z4FillPhi:
        blez    a1, .LBB0_3
        li      a2, 0
        csrr    a3, vlenb
        add     a4, a3, a1
        addi    a4, a4, -1
        neg     a5, a3
        and     a4, a4, a5
        vsetvli a5, zero, e8, m1, ta, ma
        vid.v   v8
        vsetvli zero, zero, e64, m8, ta, ma
        vid.v   v16
.LBB0_2:
        vsetvli zero, zero, e64, m8, ta, ma
        vsaddu.vx       v24, v16, a2
        vmsltu.vx       v0, v24, a1
        add     a5, a0, a2
        vse8.v  v8, (a5), v0.t
        add     a2, a2, a3
        vsetvli zero, zero, e8, m1, ta, ma
        vadd.vx v8, v8, a3
        bne     a4, a2, .LBB0_2
.LBB0_3:
        ret
.Lfunc_end0:
        .size   _Z4FillPhi, .Lfunc_end0-_Z4FillPhi
```

After:
```asm
_Z4FillPhi:
        blez    a1, .LBB0_3
        li      a2, 0
        csrr    a3, vlenb
        add     a4, a3, a1
        addi    a4, a4, -1
        neg     a5, a3
        and     a4, a4, a5
        vsetvli a5, zero, e8, m1, ta, ma
        vid.v   v8
        vsetvli zero, zero, e64, m8, ta, ma
        vid.v   v16
.LBB0_2:
        vsaddu.vx       v24, v16, a2
        vmsltu.vx       v0, v24, a1
        add     a5, a0, a2
        add     a2, a2, a3
        vse8.v  v8, (a5), v0.t
        bne     a4, a2, .LBB0_2
.LBB0_3:
        ret
.Lfunc_end0:
        .size   _Z4FillPhi, .Lfunc_end0-_Z4FillPhi
```

The removals of the `vsetvli` should be harmless as the vtype is not changing (questionable if it is correct due to the tail handling, but lets ignore that).  The `add a2, a2, a3` is being scheduled differently but that should be save as the `vse8.v` is not impacted by that.  At that point, the only difference is the `vadd.vx v8, v8, a3`, where `a3` is `vlenb` which would be the stride, and thus is simply forwarding the index base by the stride which is being unrolled here through the vector unit.

**Comment by MacDue** [comment]
I'm not sure what's happening in this case, but I would get the vscale range is being reported with some unexpected value (possible zero?).

**Comment by MacDue** [comment]
It would be helpful if you gave the compiler flags you used or a https://godbolt.org/ link.

**Comment by compnerd** [comment]
Sorry about that, not sure how I missed including the RUN command.  `clang -target riscv64-unknown-linux-musl -march=rv64gcv -Os -S -o - %s` is what I was using.

**Comment by compnerd** [comment]
https://godbolt.org/z/Kf1zGn4nP is this reproduced under compiler explorer (unfortunately, I don't see a newer clang that is not off of trunk that can show the before).

**Comment by compnerd** [comment]
Okay, I _think_ that I have a possible fix for this.  The issue is the `APInt` handling, which UBSan caught as well.  I can put up a DR to revert the revert with the change and the additional test case later today.

**Comment by MacDue** [comment]
I don't think UBSan caught anything around the APInt (though maybe I missed that). In an earlier patch there was UB (possible overflow), which was corrected by converting things over to APInts. 

Anyway, thanks a lot for looking into this. I was going to try diagnoses things myself, but I don't have access to a fast machine right now so I'm still building `main`.

**Comment by compnerd** [comment]
> I don't think UBSan caught anything around the APInt (though maybe I missed that). In an earlier patch there was UB (possible overflow), which was corrected by converting things over to APInts.

Ah, I missed that when comparing the original diff and the commit diff, sorry about that.

> Anyway, thanks a lot for looking into this. I was going to try diagnoses things myself, but I don't have access to a fast machine right now so I'm still building main.

You're welcome :)  I can completely understand the build times, it is always a pain.  I am going to have to ask you for help though - I don't know the right people to ask for a review for this (but I will be including you), and I don't understand this code deeply enough to be comfortable with a post-commit review for this.

**Comment by MacDue** [comment]
I would include some of the reviewers from the original patch, [dmgreen](https://reviews.llvm.org/p/dmgreen/) and [paulwalker-arm](https://reviews.llvm.org/p/paulwalker-arm/) reviewed previous versions of this patch and ones like it. Though, It may take a while to get a review now (since it's the holidays and a lot of people are off till after Christmas)

**Comment by MacDue** [comment]
Ah, I see what happened here (I imagine this is your fix). That `APInt::operator*=(uint64_t)` does not work how I expected and truncates the result. The solution here is to extend both operands to matching APInts then multiply them.

**Comment by compnerd** [comment]
Yeap, that is exactly what I found and am adding the test case for this as well.

**Comment by compnerd** [comment]
https://reviews.llvm.org/D140347 is the differential for this.

**Comment by MacDue** [comment]
Sorry, can you tag `benmxwl-arm` instead, I don't use that MacDue account.
