### ISSUE TITLE
Clang Backend Error after D131047

### ISSUE THREAD

**Issue by rpbeltran** [llvm/llvm-project#59599]
I bisected a clang backend crash to https://reviews.llvm.org/D131047 and made minimal reproducer:

```
int main() {
    long j = __builtin_neon_vmull_p64(0, 0);
    return __builtin_arm_crc32cd(0, j) ;
}
```

Crashes with:

```
fatal error: error in backend: Cannot select: t23: v16i8 = AArch64ISD::PMULL t22, t22
  t22: v1i64 = scalar_to_vector Constant:i64<0>
    t3: i64 = Constant<0>
  t22: v1i64 = scalar_to_vector Constant:i64<0>
    t3: i64 = Constant<0>
In function: main
```

When compiled with `clang -cc1 -triple aarch64-cros-linux-gnu -emit-obj -target-feature +crc reduced_test_case.cpp`

Compiler Explorer Link: https://godbolt.org/z/7EbTxWqsn

This bug is still present at TOT.

**Comment by rpbeltran** [comment]
Tagging @minglotus-6 

I was able to bisect this to your patch https://reviews.llvm.org/D131047. Any chance there's a missing case in there?

**Comment by minglotus-6** [comment]
Thanks for the report.

Adding `+aes` (that supports `pmull` instruction) would work (see https://godbolt.org/z/xTo7jnEjE).

How https://reviews.llvm.org/D131047 makes a difference
- The patch replaces the original pattern [1] into `defm PMULL  : SIMDDifferentThreeVectorBD<0,0b1110,"pmull", AArch64pmull>;` which requires `HasAES` ([tablegen pattern link](https://github.com/llvm/llvm-project/blob/c42e50fede53bbcce79095e7c8115f26826c81ae/llvm/lib/Target/AArch64/AArch64InstrFormats.td#L6649))  - [1] doesn't require `HasAES` to compile but the code execution of `pmull` would require `AES`, so I think asking for `+aes` in the compilation command is fine for `pmull`.

[1]

```
// Patterns for 64-bit pmull
def : Pat<(int_aarch64_neon_pmull64 V64:$Rn, V64:$Rm),
          (PMULLv1i64 V64:$Rn, V64:$Rm)>;
def : Pat<(int_aarch64_neon_pmull64 (extractelt (v2i64 V128:$Rn), (i64 1)),
                                    (extractelt (v2i64 V128:$Rm), (i64 1))),
          (PMULLv2i64 V128:$Rn, V128:$Rm)>;
```

**Comment by rpbeltran** [comment]
Thanks for the extra flag and fast response, this is very helpful and seems like it should fix my immediate issue!

Would be great if this was a compile error of course so that we could get a clearer diagnostic from it, but requiring `+aes` or `+crypto` makes a lot of sense now.

**Comment by minglotus-6** [comment]
Thanks for the update! Glad to know the immediate issue is resolved.

I agree that the compile error could be improved for better hint.

The `cannot select` error message is emitted [here](https://github.com/llvm/llvm-project/blob/b6e344ce91c8796331fca7644eb8c748ac5391ec/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp#L3796) and it seems no  existing diagnostic options (https://clang.llvm.org/docs/DiagnosticsReference.html) cover the case here (missed extension in clang options). I'm not familiar with the diagnostic implementation in Clang and LLVM enough to think through a good implementation at this point though. Maybe it makes sense to file a separate FR.

Going to close this but let me know if there are following up questions!

**Comment by davemgreen** [comment]
Yes - The intrinsics definitions in arm_neon.td should be guarded by an "aes" TargetGuard. There should really be a FEAT_PMULL, but llvm has always combined them into aes. That should then give an error about using the intrinsics where they are not valid.

**Comment by minglotus-6** [comment]
> Yes - The intrinsics definitions in arm_neon.td should be guarded by an "aes" TargetGuard. There should really be a FEAT_PMULL, but llvm has always combined them into aes. That should then give an error about using the intrinsics where they are not valid.

Thanks for enlighten me on this! Send out https://reviews.llvm.org/D140432 for review for better hint
