### ISSUE TITLE
Clang C++23 Feature P0847R7 Deducing This

### ISSUE THREAD

**Issue by cor3ntin** [llvm/llvm-project#59619]
https://wg21.link/P0847

Creating that to track progress and signal that I'm working on it

Core issues

- [x] [2561. Conversion to function pointer for lambda with explicit object parameter](https://wg21.link/CWG2561) : Open, Implemented
- [x] [2553. Restrictions on explicit object member functions](https://wg21.link/CWG2553): Open, Implemented
- [x] [2653. Can an explicit object parameter have a default argument?](https://wg21.link/CWG2653): Approved, implemented
- [x] [2687. Calling an explicit object member function via an address-of-overload-set](https://wg21.link/CWG2687): Unknown
- [ ] [2688. Calling explicit object member functions](https://wg21.link/CWG2688): Unknown
- [ ] [2660. Confusing term "this parameter"](https://wg21.link/CWG2660): Unknown
- [x] [2564. Conversion to function pointer with an explicit object parameter](https://wg21.link/CWG2564): Unknown
- [x] [2586. Explicit object parameter for assignment and comparison](https://wg21.link/CWG2586): Accepted, Unknown
- [x] [2674. Prohibit explicit object parameters for constructors](https://wg21.link/CWG2674): Accepted, Implemented
- [ ] [2692. Static and explicit object member functions with the same parameter-type-lists](https://wg21.link/p2797r0): Accepted, Unknown
- [x] [2754. Using *this in explicit object member functions that are coroutines](https://wg21.link/CWG2754): Unknown

**Comment by royjacobson** [comment]
Good luck! 🥇 

Did you think yet about what to do with mangling? I tried asking on https://github.com/itanium-cxx-abi/cxx-abi/issues/148 a while ago but got no answer.

**Comment by cor3ntin** [comment]
Nah.
It will be an issue because, unfortunately

```
struct S {
  static void f(S);
  void f(this S);
};
```

is valid. I suspect that's why msvc has different mangling
I'm hoping someone can solve that before i get there :)

**Comment by frederick-vs-ja** [comment]
> Nah. It will be an issue because, unfortunately
> 
> ```
> struct S {
>   static void f(S);
>   void f(this S);
> };
> ```
> 
> is valid. I suspect that's why msvc has different mangling I'm hoping someone can solve that before i get there :)

[CWG2692](https://cplusplus.github.io/CWG/issues/2692.html) would make this invalid. I guess we can just implement the proposed resolution.

**Comment by cor3ntin** [comment]
@frederick-vs-ja Unfortunately, [the adopted resolution](https://isocpp.org/files/papers/P2797R0.html) reinforce that this should be valid

**Comment by abbator** [comment]
Are there any updates on progress here? Very interested in this feature and eagerly awaiting support for it by Clang.

**Comment by cor3ntin** [comment]
> Are there any updates on progress here? Very interested in this feature and eagerly awaiting support for it by Clang.

PR here https://reviews.llvm.org/D140828 .

I'm hoping we can work on review over the next few weeks. Clang 18 sounds like a realistic release target. No promise!

**Comment by Endilll** [comment]
CWG2692 is resolved by [P2797R0](https://wg21.link/p2797r0) and is implemented in #93430, which declares the feature complete in the release notes.
Corentin suggested to me offline that this should be closed. Unimplemented Core issues can be handled as usual when they got resolved.
