### ISSUE TITLE
When linking the iOS Signal app with Mach-O lld, it errors out

### ISSUE THREAD

**Issue by michaeleisel** [llvm/llvm-project#59627]
After building the Signal app following the basic [steps](https://github.com/signalapp/Signal-iOS/blob/main/BUILDING.md) and linking with ld64, it works. However, when I switch to lld by adding `-fuse-ld=/path/to/ld64.lld` to the linker command, I get the following error message:
```
ld64.lld: error: library not found for -lsignal_ffi
ld64.lld: error: library not found for -lringrtc
...
```

This is on an arm 13.0 mac with Xcode 14.1. I tried it with llvm at recent commit 70ac5981972 and on latest homebrew version of llvm, which appears to be on 15.0.6. In both cases, I got the same error result.

Here's the .tar.gz from `--reproduce=...`: https://drive.google.com/file/d/1eR65b2xTUgGasqduXRMoZBOKyVAG-V6H/view?usp=share_link

**Comment by keith** [comment]
Some discussion on this issue here https://reviews.llvm.org/D140225, in the meantime you can pass `-Wl,--ignore-auto-link-option=signal_ffi` `-Wl,--ignore-auto-link-option=ringrtc` to avoid these issues
