### ISSUE TITLE
Clang-format: Multiplication in macro in C is formatted wrong

### ISSUE THREAD

**Issue by veckan** [llvm/llvm-project#59634]
I'm using clang-format 15.0.3 and I have set up the `.clang-format` file to my liking. I'm running it through my whole existing project, but there is a problem in more complicated macros. 
It seems like clang-format recognizes `*` as a pointer, and not a multiplication operator if there are closed parenthesis before them.
For example:
```c
#define MILLIS_TO_TICKS(x) (((uint64_t) (x) *RTC_TICKS_PER_SECOND) / 1000)
```

I want it to look like this:
```c
#define MILLIS_TO_TICKS(x) (((uint64_t) (x) * RTC_TICKS_PER_SECOND) / 1000)
```

There should have been a space between `*` and `RTC_TICKS_PER_SECOND`, and there was in code before formatting, but Clang removed it for some reason.
I can't find an option in `.clang-format` file to disable it, and it bothers me a lot.
If I put parenthesis around `RTC_TICKS_PER_SECOND`, then space is not removed:
```c
#define MILLIS_TO_TICKS(x) (((uint64_t) (x) * (RTC_TICKS_PER_SECOND)) / 1000)
```

Is it a bug, or I just can't find the option that exists?

**Comment by veckan** [comment]
Just to give some more information about the issue, the same happens if the second operand is a number, not another define:
`#define DECI_TO_CENTI(x) ((x) *10)`
So it's not up to a define not being in parenthesis...

**Comment by owenca** [comment]
https://reviews.llvm.org/D153745
