### ISSUE TITLE
No thread switched in coroutine example from cppreference.com

### ISSUE THREAD

**Issue by IGR2014** [llvm/llvm-project#59638]
Consider the following code example from cppreference.com ([link](https://en.cppreference.com/w/cpp/language/coroutines#Example)) with small modification (assert added):

```C++
#include <cassert>
#include <coroutine>
#include <iostream>
#include <stdexcept>
#include <thread>
 
auto switch_to_new_thread(std::jthread& out)
{
    struct awaitable
    {
        std::jthread* p_out;
        bool await_ready() { return false; }
        void await_suspend(std::coroutine_handle<> h)
        {
            std::jthread& out = *p_out;
            if (out.joinable())
                throw std::runtime_error("Output jthread parameter not empty");
            out = std::jthread([h] { h.resume(); });
            // Potential undefined behavior: accessing potentially destroyed *this
            // std::cout << "New thread ID: " << p_out->get_id() << '\n';
            std::cout << "New thread ID: " << out.get_id() << '\n'; // this is OK
        }
        void await_resume() {}
    };
    return awaitable{&out};
}
 
struct task
{
    struct promise_type
    {
        task get_return_object() { return {}; }
        std::suspend_never initial_suspend() { return {}; }
        std::suspend_never final_suspend() noexcept { return {}; }
        void return_void() {}
        void unhandled_exception() {}
    };
};
 
task resuming_on_new_thread(std::jthread& out)
{
    const auto thread0 = std::this_thread::get_id();
    std::cout << "Coroutine started on thread: " << thread0 << '\n';
    co_await switch_to_new_thread(out);
    // awaiter destroyed here
    const auto thread1 = std::this_thread::get_id();
    std::cout << "Coroutine resumed on thread: " << thread1 << '\n';
    // Oops Clang
    assert(thread0 != thread1);
}
 
int main()
{
    std::jthread out;
    resuming_on_new_thread(out);
}
```

The results among Clang 15.0, GCC 12.2 and MSVC 19.33 are following ([link](https://godbolt.org/z/sj8zeKeMo)):
![image](https://user-images.githubusercontent.com/10415461/208910337-324e8de9-84dd-4a73-bffc-32131b9497d7.png)

So it looks like Clang is not resuming coroutine on other thread but on the previous. The description of this example on cppreference.com states the following:

> Note that because the coroutine is fully suspended before entering awaiter.await_suspend(), that function is free to transfer the coroutine handle across threads, with no additional synchronization. For example, it can put it inside a callback, scheduled to run on a threadpool when async I/O operation completes. In that case, since the current coroutine may have been resumed and thus executed the awaiter object's destructor, all concurrently as await_suspend() continues its execution on the current thread, await_suspend() should treat *this as destroyed and not access it after the handle was published to other threads.

**Comment by Abstract-Everything** [comment]
Do note that using 'x86-64 clang (trunk)' results in the same behaviour as the other compilers.

**Comment by ChuanqiXu9** [comment]
Yeah, this was a well known problem and we've already fixed it in trunk. We tried to fix it in 15 but we failed and there won't be new 15.x releases. So let's wait fo 16 for this issue.

**Comment by IGR2014** [comment]
Yes, sorry, my bad, didn't checked it with latest version. sorry again
