### ISSUE TITLE
clangd unittest random failures on clang-aarch64-global-isel

### ISSUE THREAD

**Issue by pogo59** [llvm/llvm-project#59644]
I got bot fail-mail from clang-aarch64-global-isel which turned out to be a clangd unittest failure. "?" I thought, as I haven't touched any source code in weeks, and even then don't usually touch anything that clangd cares about.

According to that bot's history, there were four clangd unittest failures in the past 28 runs (that's as far back as I looked). These are the four failures and what looks like the particular test it was running.

https://lab.llvm.org/buildbot/#/builders/183/builds/9601 (TUSchedulerTests.PreambleThrottle)
https://lab.llvm.org/buildbot/#/builders/183/builds/9604 (ClangdServerTest.ForceReparseCompileCommandDefines)
https://lab.llvm.org/buildbot/#/builders/183/builds/9619 (CrossFileRenameTests.WithUpToDateIndex)
https://lab.llvm.org/buildbot/#/builders/183/builds/9628 (TUSchedulerTests.ManyUpdates)

(My coworker who runs the llvm-clang-x86_64-gcc-ubuntu bot says he got tired of all the unreproduceable clangd random failures when he was setting up that bot, and just disabled them.)

I know random failures are the hardest, but I figured I should at least report it.

**Comment by kadircet** [comment]
hi @pogo59 I couldn't see any more flakiness in this build bot for the build in the past week. please do re-open if the issue persists
