### ISSUE TITLE
[clang-tidy] Wrong information displayed with `--enable-check-profile`

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#59642]
Hi,

I'm investigating a performance regression - clang-tidy takes now around 7 minutes (!) to process one of our .cpp files. If I enable `--enable-check-profile`, it says that it took in total around 18 seconds, with the most expensive check taking 1.48 seconds, which is clearly not true, so I can't really tell where the performance regression comes from.

Thus `--enable-check-profile` should be fixed to display accurate information.

**Comment by njames93** [comment]
Enable check profile just times the actual running of each check, not all the other code needed to run clang-tidy. Having said that, the disparity between total checks time and total time seems too far off. Can you try timing clang when building the translation unit only using fsyntax-only. Or use -ftime-report

**Comment by carlosgalvezp** [comment]
Thanks for the reply! That's a good point, will run those experiments and get back.

**Comment by carlosgalvezp** [comment]
So here's my experiments:

* Running clang alone, with `-ftime-report`, and **without** `fsyntax-only`, yields:
```
===-------------------------------------------------------------------------===
                          Clang front-end time report
===-------------------------------------------------------------------------===
  Total Execution Time: 3.6346 seconds (3.6484 wall clock)

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
   3.2670 (100.0%)   0.3676 (100.0%)   3.6346 (100.0%)   3.6484 (100.0%)  Clang front-end timer
   3.2670 (100.0%)   0.3676 (100.0%)   3.6346 (100.0%)   3.6484 (100.0%)  Total
```

This is in agreement with Ubuntu time measurements:

```
real	0m3.704s
user	0m3.290s
sys	0m0.399s
```

* If I run clang-tidy and pass `-ftime-report` to it, I get:
```
===-------------------------------------------------------------------------===
                          Clang front-end time report
===-------------------------------------------------------------------------===
  Total Execution Time: 406.5559 seconds (406.8332 wall clock)

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
  396.9933 (100.0%)   9.5626 (100.0%)  406.5559 (100.0%)  406.8332 (100.0%)  Clang front-end timer
  396.9933 (100.0%)   9.5626 (100.0%)  406.5559 (100.0%)  406.8332 (100.0%)  Total

```
I do not get any more detailed information, unlike with Clang where I can see all the different passes.

Not sure where to look next? Clearly it's the clang front-end part that is taking all the time.

**Comment by carlosgalvezp** [comment]
The baseline (1ae33bf42680b156fe0f5cd6163bf24ef45d8cd3) takes around 15 seconds to check, so the performance regression has been introduced between that and d8b0f007cb98ae261b65204f3e9c452937f8b91f

**Comment by firewave** [comment]
That sounds strange since just a few months ago someone was able to get information out of that flag - see https://github.com/llvm/llvm-project/issues/57527.

**Comment by carlosgalvezp** [comment]
You are right. It's still strange that "Clang front-end" takes 3 seconds when running clang and 400 seconds when running clang-tidy. Should we continue to investigate this here, or would you prefer I close this one and open a new one? I still don't know if this is clang-tidy or clang's problem.

**Comment by carlosgalvezp** [comment]
More precisely:

* Regular clang compilation:
```
real	0m3.143s
user	0m2.986s
sys	0m0.156s

```

* Clang compilation with `-fsyntax-only`:
```
real	0m1.966s
user	0m1.820s
sys	0m0.146s
```

* Clang tidy:
```
real	6m57.662s
user	6m50.667s
sys	0m6.892s
```

**Comment by whisperity** [comment]
How are you executing Clang-Tidy? I've only ever interfaced with the JSON output of checker profiling... You might be getting just one TU's data, not the entire project... Are you able to produce the JSON, at least? It should be very easy to sum it up for an entire project. If you check out https://github.com/Xazax-hun/csa-testbench you can mine out some Python code that can sum it all up for you.

**Comment by carlosgalvezp** [comment]
JSON output gives me 16 seconds in total if I sum up all the `wall` times for each check on this single TU. Seems consistent with the stderr output from `--enable-check-profile`.

**Comment by carlosgalvezp** [comment]
One thing I **do** notice, however, is that the profile output (both stderr, JSON) only shows information about 200 checks. I am running 333 checks ( :D ) as per `--list-checks`. Could it be that the check that is causing the problem is simply not shown?

**Comment by EugeneZelenko** [comment]
@carlosgalvezp: You could try to enable only particular group of checks and than individual checks.

**Comment by carlosgalvezp** [comment]
So it seems that indeed 6 minutes and 42 seconds (out of 7 minutes total) are spent on `clang-analyzer*` checks. Almost 5 minutes for `clang-analyzer-core*`. Is this reasonable/expected? Let me know if you'd like me to open a separate ticket for this.

Now, to my original question - would it make sense/be possible to display the profiling information of the `clang-analyzer` checks with the `--enable-check-profile` option? These checks are listed in the table of "groups of checks" in clang-tidy, so as a user it seems reasonable to expect that the profiling includes that info.

**Comment by firewave** [comment]
The `clang-analyzer-*` checks are also processing system includes whereas the other checks are only processing non-system ones (and then even if configured to do so). In one project (I no longer have access to that) we had lots of findings inside boost headers from those checks.

IIRC when I pointed this out there was mention of the static analyzer using a different framework than the other checks which was causing that. It is quite possible that is outdated information though as that was several years ago.
