### ISSUE TITLE
LLVM IR: struct alignment is wrong

### ISSUE THREAD

**Issue by jitao21432060** [llvm/llvm-project#59652]
I'm new to LLVM framework and using LLVM to generate JIT code. But the code generated about struct is a bit problematic:
```ll
source_filename = "test1"
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
target triple = "arm64-apple-macosx12.0.0"

%Coordinate = type { i32, i32 }

define i32 @main() {
entry:
  %0 = call %Coordinate @PSnative_create_coordinate(i32 5, i32 6)
  %coordinate1 = alloca %Coordinate, align 8
  ...
```

I think the struct alignment of alloc should be 4, but here is 8.

Thanks.

**Comment by dwblaikie** [comment]
Probably not JIT related - how did you create this IR? It's probably up to the IR creation code to choose what alignment to use here.

**Comment by jitao21432060** [comment]
> Probably not JIT related - how did you create this IR? It's probably up to the IR creation code to choose what alignment to use here.

The alloc IR is created throug CreateAlloc():
`AllocaInst *CreateAlloca(Type *Ty, Value *ArraySize = nullptr,
                           const Twine &Name = "")`
The argument Ty is just a StructType with a struct body which has two  Int32 type. The other two arguments is not passed.

**Comment by lhames** [comment]
This is not JIT related.

I think that you're just getting the default alignment for aggregates because your module's data-layout doesn't contain an overriding entry for aggregates: `a:<abi>[:<pref>]` -- see https://llvm.org/docs/LangRef.html#langref-datalayout.

It's nice to know for curiosity's sake, but I'd be inclined to just stick with the default unless you have a good reason to override it.

**Comment by jitao21432060** [comment]
> I think that you're just getting the default alignment for aggregates because your module's data-layout doesn't contain an overriding entry for aggregates: `a:<abi>[:<pref>]` -- see https://llvm.org/docs/LangRef.html#langref-datalayout.
 
Thank you very much. It works. The alignment of the struct is changed to 4 now.

> It's nice to know for curiosity's sake, but I'd be inclined to just stick with the default unless you have a good reason to override it.

The reason why I want to modify the alignment is that there is a bug in my generated machine code which is caused by the layout. Just modify the default alignment may not be a good solution and  I will take your suggestion into serious consideration. Thanks again.
