### ISSUE TITLE
clang++ crash with nested template, concept and explicit template instantiation

### ISSUE THREAD

**Issue by AlexPuchmayr** [llvm/llvm-project#59656]
clang++ 15 (also 14) crashes with the source file attached. Unfortunately it also makes kdevelop crash as it uses it for background parsing.

[test1-output.txt](https://github.com/llvm/llvm-project/files/10287972/test1-output.txt)
[test-docs-998515.tar.gz](https://github.com/llvm/llvm-project/files/10288012/test-docs-998515.tar.gz)

**Comment by royjacobson** [comment]
Looks fixed in trunk: https://godbolt.org/z/8aeEWYa65

**Comment by AlexPuchmayr** [comment]
Confirmed. The provided test program as well as the big project now compile fine with latest version (16) from trunk :-)
