### ISSUE TITLE
[llvm-reduce] Missing command documentation.

### ISSUE THREAD

**Issue by Meinersbur** [llvm/llvm-project#59657]
https://llvm.org/docs/CommandGuide/ has documentation for [bugpoint](https://llvm.org/docs/CommandGuide/bugpoint.html), but not for llvm-reduce. 

The only mention I could find is in https://www.llvm.org/docs/HowToSubmitABug.html.

Also, https://llvm.org/docs/Bugpoint.html could be updated and a "see also" be added to https://llvm.org/docs/CommandGuide/bugpoint.html.

@aeubanks

**Comment by aabhinavg** [comment]
Fix by the patch : https://reviews.llvm.org/D146020
