### ISSUE TITLE
[mlir] `Type::dump()` should print a `\n` at the end

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#59673]
This has been a long annoyance of mine: the "dump" methods on IR objects are intended to be used in a debugger, but type has never printed a \n at the end.  This makes it inconsistent with everything else, and makes it very difficult to understand in LLDB at least.

Is there any objection to adding a \n to the dump method?  There is no behavior change needed on print etc.

**Comment by joker-eph** [comment]
Seems like an oversight.

**Comment by theo-lw** [comment]
Here's attempt at a fix: https://reviews.llvm.org/D141201

**Comment by lattner** [comment]
amazing, thank you! :)
