### ISSUE TITLE
Clang does not optimize trivial case with bit operations

### ISSUE THREAD

**Issue by socketpair** [llvm/llvm-project#59680]
https://godbolt.org/z/5e3eKqPqs

```C

#include <stdint.h>

int firewall3(const uint8_t *restrict data) {
    const uint32_t src = *((const uint32_t *)data);

    if ((src & 0xFFFF0000) == 0x11220000) return 1;
    if ((src & 0xFFFFFF00) == 0x11223300) return 1;

    return 0;
}

int firewall4(const uint8_t *restrict data) {
    const uint32_t src = *((const uint32_t *)data);

    if ((src & 0xFFFFFF00) == 0x11223300) return 1;
    if ((src & 0xFFFF0000) == 0x11220000) return 1;

    return 0;
}
```

```asm
firewall3:                              # @firewall3
        mov     eax, dword ptr [rdi]
        mov     ecx, eax
        and     ecx, -65536
        cmp     ecx, 287440896
        sete    cl
        and     eax, -256
        cmp     eax, 287453952
        sete    al
        or      al, cl
        movzx   eax, al
        ret
firewall4:                              # @firewall4
        mov     eax, dword ptr [rdi]
        mov     ecx, eax
        and     ecx, -256
        cmp     ecx, 287453952
        sete    cl
        and     eax, -65536
        cmp     eax, 287440896
        sete    al
        or      al, cl
        movzx   eax, al
        ret
```

GCC:

```asm
firewall3:
        movl    (%rdi), %eax
        xorw    %ax, %ax
        cmpl    $287440896, %eax
        sete    %al
        movzbl  %al, %eax
        ret
```
GCC can optimize such comparisons, but it failed to optimize `firewall4` https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108215

1. It's obvious that order of comparison is not important here. 
2. It's obvious that one condition "contains" another.

So we can leave only one comparison (one, that "checks" fewer bits)

**Comment by nikic** [comment]
Interesting, would have expected foldLogOpOfMaskedICmps() to handle this.

**Comment by inclyc** [comment]
Reduced:

```llvm
define i1 @firewall3(i32 %foo)  {
  %bar = and i32 %foo, -65536
  %eq1 = icmp eq i32 %bar, 287440896
  %bar2 = and i32 %foo, -256
  %eq2 = icmp eq i32 %bar2, 287453952
  %ret = or i1 %eq1, %eq2
  ret i1 %ret
}

define i1 @firewall4(i32 %foo) {
  %bar = and i32 %foo, -256
  %eq1 = icmp eq i32 %bar, 287453952
  %bar2 = and i32 %foo, -65536
  %eq2 = icmp eq i32 %bar2, 287440896
  %ret = or i1 %eq1, %eq2
  ret i1 %ret
}

```

**Comment by inclyc** [comment]
https://reviews.llvm.org/D140666

**Comment by bcl5980** [comment]
https://godbolt.org/z/r1xxh9Yvs
icmp with variables are also not optimized.
```
#include <stdint.h>

int firewall3(const uint8_t *restrict data, int a) {
    const uint32_t src = *((const uint32_t *)data);

    if ((src & 0xFFFF0000) == a) return 1;
    if ((src & 0xFFFFFF00) == a) return 1;

    return 0;
}

int firewall4(const uint8_t *restrict data, int a) {
    const uint32_t src = *((const uint32_t *)data);

    if ((src & 0xFFFFFF00) == a) return 1;
    if ((src & 0xFFFF0000) == a) return 1;

    return 0;
}
```

**Comment by inclyc** [comment]
Looks like this is the correct transform. https://alive2.llvm.org/ce/z/oqtV65

**Comment by bcl5980** [comment]
> > https://godbolt.org/z/r1xxh9Yvs icmp with variables are also not optimized.
> > ```
> > #include <stdint.h>
> > 
> > int firewall3(const uint8_t *restrict data, int a) {
> >     const uint32_t src = *((const uint32_t *)data);
> > 
> >     if ((src & 0xFFFF0000) == a) return 1;
> >     if ((src & 0xFFFFFF00) == a) return 1;
> > 
> >     return 0;
> > }
> > 
> > int firewall4(const uint8_t *restrict data, int a) {
> >     const uint32_t src = *((const uint32_t *)data);
> > 
> >     if ((src & 0xFFFFFF00) == a) return 1;
> >     if ((src & 0xFFFF0000) == a) return 1;
> > 
> >     return 0;
> > }
> > ```
> 
> Could we actually do this optimization? I mean, if a = 0xFFFFFF00, checking fewer bits may cause miscompilation.

You are right. Should be like this:
https://godbolt.org/z/z8TWh9fKE
https://alive2.llvm.org/ce/z/TXuNRT
