### ISSUE TITLE
wrong code at -O1 and above on x86_64-linux_gnu (compiled code hangs)

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#59704]
It appears to be a recent regression and does not reproduce with 15.*. 

Compiler Explorer: https://godbolt.org/z/qqjoW5fes

```console
% clangtk -v
clang version 16.0.0 (https://github.com/llvm/llvm-project.git ff25800d4ba0b577a44dc918da7a1fb3c29fdb13)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
%
% clangtk -O1 small.c
% timeout -s 9 5 ./a.out
Killed
%
% cat small.c
int a;
int main() {
  int b;
  while (a)
    ;
  while (!(~a && (a <= -2UL && a <= -2UL)))
    if (b)
      a = b;
  return 0;
}
```

**Comment by ldrumm** [comment]
`b` is uninitialized when it's used as a branch condition. This is undefined behaviour and llvm correctly transforms the whole function to an infinite loop. 
```shell-session
$ clang -Wall small.c 
small.c:7:23: warning: variable 'b' is uninitialized when used here [-Wuninitialized]
                  if (b)
                      ^
small.c:3:12: note: initialize the variable 'b' to silence this warning
      int b;
           ^
            = 0
1 warning generated.
```
It's correct to do this, because any uses of an undefined value can be any value. Thus, the combination of optimizations that work on distinct parts of the function, result in individual transformations that don't do what you expect when they've combined.

Try following the sequence of `undef` values in the output of the optimization pipeline and see how 2 undef values result in a store being correctly deleted, then a basic block becoming unreachable
```
 clang -O1  small.c -S -o - -fno-asynchronous-unwind-tables -mllvm -debug -mllvm -print-after-all
```

**Comment by zhendongsu** [comment]
@ldrumm: Thank you for taking a look at this issue, but please note that the code has no undefined behaviors: `if (b)` is never executed because the condition in `while (!(~a && (a <= -2UL && a <= -2UL)))` is always false.

**Comment by zhendongsu** [comment]
@EugeneZelenko: Please note that this is a valid issue as the test has no undefined behaviors.

**Comment by EugeneZelenko** [comment]
@zhendongsu: I added label based on @ldrumm conclusion.

**Comment by zhendongsu** [comment]
@EugeneZelenko: I see, but it would be helpful to double check.

**Comment by ldrumm** [comment]
Does your program still enter an infinite loop if you initialize `b`?

**Comment by zhendongsu** [comment]
> Does your program still enter an infinite loop if you initialize `b`?

Why would that be relevant?

**Comment by ldrumm** [comment]
> > Does your program still enter an infinite loop if you initialize `b`?
> 
> Why would that be relevant?

Because that's where the undefined behaviour comes from. UB is not a dynamic property of the program, but one that exists *as written*. Your loop condition depends on an uninitialized variable *as written*, so the optimizer can do anything it likes with the loop during translation.

**Comment by zhendongsu** [comment]
@ldrumm: Please double-check; UB is in fact a dynamic property.

**Comment by ldrumm** [comment]
c99:9899:J2p1

> Undefined Behaviour
> [...]
> - The value of an object with automatic storage duration is used while it is indeterminate (6.2.4, 6.7.8, 6.8).

Indeterminate values are discussed as referenced in 6.2.4p2
> The lifetime of an object is the portion of program execution during which storage is
guaranteed to be reserved for it. An object exists, has a constant address,25) and retains
its last-stored value throughout its lifetime.26) If an object is referred to outside of its
lifetime, the behavior is undefined. The value of a pointer becomes indeterminate when
the object it points to reaches the end of its lifetime

What counts as indeterminate is covered in "Initializers"
6.7.8p10
> If an object that has automatic storage duration is not initialized explicitly, its value is
indeterminate.

In the condition `if (b)`, `b`'s value is indeterminate. `b` is of automatic storage duration. This use of `b` is undefined.

**Comment by zhendongsu** [comment]
> This use of b is undefined.

But `b` is not used. 

Let me cc a few folks: @nikic @fhahn @spatel-gh.

**Comment by nikic** [comment]
Reduced (https://llvm.godbolt.org/z/63713P4YK):

```llvm
define i1 @test(i1 %c, i64 %arg) {
entry:
  br i1 %c, label %if, label %join

if:
  %cmp = icmp ne i64 %arg, 0
  %and = select i1 %cmp, i1 %cmp, i1 false
  br label %join

join:
  %phi = phi i1 [ false, %entry ], [ %and, %if ]
  %not = xor i1 %phi, true
  ret i1 %not
}

; RUN: opt -S -passes=instcombine

define i1 @test(i1 %c, i64 %arg) {
entry:
  br i1 %c, label %if, label %join

if:                                               ; preds = %entry
  br label %join

join:                                             ; preds = %if, %entry
  ret i1 true
}
```

**Comment by rotateright** [comment]
The bug was introduced with:
b20ccccda22b1465
That code doesn't account for the case where the logical-and (or logical-or) operands are the same value. We should probably just bail out if the select hasn't been simplified yet (that's also why a single basic-block test does not show the bug).
