### ISSUE TITLE
clang-format IndentPPDirectives only works if there's code/comments after the final #

### ISSUE THREAD

**Issue by jdiazdelrio** [llvm/llvm-project#59701]
The option `IndentPPDirectives: BeforeHash` on the following code (**Code 1**)
```cpp
#ifndef HAVE_TEST
#define HAVE_TEST
#include "foo.hpp"

namespace space
{}

#endif
```

does no reformat the code. If instead, the code is formatted as expected (**Code 2**)
```cpp
#ifndef HAVE_TEST
   #define HAVE_TEST
   #include "foo.hpp"

namespace space
{}

#endif
```
the code is reformatted to look like in **Code 1**, breaking the expected format. If either code would have either code or a comment after the `#endif`:
```cpp
#ifndef HAVE_TEST
#define HAVE_TEST
#include "foo.hpp"

namespace space
{}

#endif
//
```
or

```cpp
#ifndef HAVE_TEST
   #define HAVE_TEST
   #include "foo.hpp"

namespace space
{}

#endif
int x;
```
Code1 will be reformatted to look like in Code2, and Code2 will remain unchanged, as expected.

**Comment by owenca** [comment]
This works as intended as clang-format skips header guards when counting preprocessor directive indent levels.

**Comment by jdiazdelrio** [comment]
I do not agree. If you try to apply `IndentPPDirectives: BeforeHash` in the following code:

```cpp
#ifndef HAVE_TEST
#define HAVE_TEST
#include "foo.hpp"

namespace space
{}

#endif
```

the Preprocessor directives `#define HAVE_TEST` and `#include "foo.hpp"` should be indented, but they are not.

**Comment by owenca** [comment]
Yes, I had tried it. The [header guard](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.6/clang/lib/Format/UnwrappedLineParser.h#L329) (i.e. the first two lines in your example above) is skipped and thus the `#include` line is not indented because it's at the top level.

**Comment by jdiazdelrio** [comment]
If you think it's doing what it should? Why, in the following code, applying `IndentPPDirectives: BeforeHash`:
```cpp
#ifndef HAVE_TEST
#define HAVE_TEST
#include "foo.hpp"

namespace space
{}

#endif
// End of file.
```
the Preprocessor directives `#define HAVE_TEST` and `#include "foo.hpp"` get indented?

**Comment by owenca** [comment]
That's because the `#endif` of the header guard is not the last non-empty line. Nevertheless, clang-format probably should ignore any comments after the `#endif`.

BTW, I didn't say clang-format _should_ ignore header guards, but this was the intended behavior when `IndentPPDirectives` was added.
