### ISSUE TITLE
[C++20] Implement std::is_pointer_interconvertible_base_of

### ISSUE THREAD

**Issue by jacobsa** [llvm/llvm-project#59709]
As far as I can tell, [`std::is_pointer_interconvertible_base_of`](https://en.cppreference.com/w/cpp/types/is_pointer_interconvertible_base_of) from C++20 is not currently implemented in libc++. This would be useful to me, so filing an issue to cover its absence.

**Comment by philnik777** [comment]
Please don't file unimplemented papers as bugs. We've got https://libcxx.llvm.org/Status/Cxx20.html to track the implemented papers.

**Comment by jacobsa** [comment]
Sorry, I didn't realize. Are you aware of anyone working on this?

**Comment by philnik777** [comment]
I have a patch locally for it, but I don't know how well it works. It's been a while since I touched it.

**Comment by jacobsa** [comment]
Any chance I can convince you to post it for posterity, in case it gives a hint for someone else who wants to work on this?
