### ISSUE TITLE
Entry in FoldCache doesn't match FoldCacheUser

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#59721]
[testcase.tar.gz](https://github.com/llvm/llvm-project/files/10309795/testcase.tar.gz)

opt -mtriple=s390x-linux-gnu -mcpu=z15 -O3 crash1_aftercreduce.bc -S -o out.opt.ll -verify-scev
Entry in FoldCache doesn't match FoldCacheUser: ((zext i16 %0 to i32) /u (zext i16 (trunc i32 %cond.i to i16) to i32)) != ((zext i16 %0 to i32) /u %cond.i)!

#6 0x00000000030747e8 llvm::ScalarEvolution::verify()
#17 0x0000000003b8dd3e llvm::ModuleInlinerWrapperPass

**Comment by fhahn** [comment]
The same issue has been reported by @uabelho  as well and should be fixed now.
