### ISSUE TITLE
LLVMExegesisTests fails (but unable to suppress) on VM

### ISSUE THREAD

**Issue by chapuni** [llvm/llvm-project#59739]
LLVM can be built but `check-llvm` fails.

* `HAVE_LIBPFM` (`libpfm4-dev` is installed on Ubuntu amd64 or aarch64)
* `LLVM_ENABLE_LIBPFM=OFF` is **not specified**
* `LLVM_ENABLE_ASSERTIONS=ON`
* In the VM that doesn't allow accessing performance counters (I can see on AWS c6a and c7g)

```console
[ RUN      ] PerfHelperTest.FunctionalTest
--
  | Unable to open event. ERRNO: Permission denied. Make sure your kernel allows user space perf monitoring.
  | You may want to try:
  | $ sudo sh -c 'echo -1 > /proc/sys/kernel/perf_event_paranoid'
  | llvm_exegesis_tests: external/llvm-project/llvm/tools/llvm-exegesis/lib/PerfHelper.cpp:111: llvm::exegesis::pfm::Counter::Counter(llvm::exegesis::pfm::PerfEvent &&): Assertion `FileDescriptor != -1 && "Unable to open event"' failed.
```

Could we have an option to detect incompatibilities and skip this test? I would like just to build and ship binaries with `HAVE_LIBPFM`.

See also https://github.com/llvm/llvm-project/commit/f92ae6dd300794b5ca6796290716436675be8007

**Comment by gchatelet** [comment]
Fixed in https://reviews.llvm.org/D140898
