### ISSUE TITLE
[clang-tidy] Support multiple casing options for readability-identifier-naming

### ISSUE THREAD

**Issue by brevzin** [llvm/llvm-project#59741]
Currently, for readablity-identifier-naming, I can make one of these choices:

* require `lower_case`
* require `CamelCase`
* don't enforce any casing at all

But what I really want is _either_ `lower_case` _or_ `CamelCase`. Some names simply have to be `lower_case` due to interaction with other libraries (for instance, iterators need to have `value_type`, not `ValueType`, and metafunctions really need to have `type` not `Type`). But other than those, we'd prefer to use `CamelCase` for other types. 

Choosing to enforce one or other style leads to lots of `NOLINT` annotations. But choosing to enforce no style opens the door to names we definitely do not want to allow. Would it be possible to add support for `x|y` in addition to just either `x` or `y`?

**Comment by njames93** [comment]
There is an option called IgnoreRegex, I think that's it's name, that you can use to silence certain names like value_type

**Comment by firewave** [comment]
It's called `*IgnoredRegexp`.

**Comment by njames93** [comment]
Thanks for the clarification, couldn't think of the exact name off there top of my head.

**Comment by brevzin** [comment]
It's true that I can approximate `lower_case|CamelCase` by setting the value to be `CamelCase` and then ignoring `[a-z0-9_]+`.

That seems like a fairly indirect way of expressing intent though.
