### ISSUE TITLE
LLVM no longer optimizes isEven loop to a test

### ISSUE THREAD

**Issue by y21** [llvm/llvm-project#59753]
Up to clang 14.0.0, this (silly) C++ code:
```c++
bool is_even(int n) {
    bool even = true;
    int num = 0;
    while (num != n) {
        even = !even;
        num++;
    }
    return even;
}
```
compiled to just:
```asm
is_even(int):                            # @is_even(int)
        test    dil, 1
        sete    al
        ret
```

Since clang 15.0.0, it doesn't seem to understand this anymore and compiles to a loop.

Godbolt: [before](https://godbolt.org/z/WPYoa4M7K) | [now](https://godbolt.org/z/dc9eoKMze)

**Comment by nikic** [comment]
Looks like this is already fixed in LLVM 16: https://godbolt.org/z/1sMsYvh1f
