### ISSUE TITLE
OpenMP emits assume of compare of globals to null

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#59767]
I see some optimized IR that has this assume in it:

```ll
tail call void @llvm.assume(i1 icmp ne (ptr addrspacecast (ptr addrspace(4) @.str.2.29 to ptr), ptr null))
```

This is trivially true since it's a nonweak global reference, and the assume should have been optimized out somewhere.

**Comment by arsenm** [comment]
This is probably just another instance of #58617

**Comment by jdoerfert** [comment]
Yes, this is some missing optimization. I will eventually teach the attributor to deal with this too. Did you land the InstCombine patch?

**Comment by arsenm** [comment]
> Yes, this is some missing optimization. I will eventually teach the attributor to deal with this too. Did you land the InstCombine patch?

No. It was lower level, in ConstantFolding. It's apparently wrong to optimize icmp based on aliasing logic. I still think the null pointers should go into the datalayout

**Comment by jdoerfert** [comment]
Turns out we also need 7bc88cbe5c0365bba0873ed896a435e57402a5e0.
