### ISSUE TITLE
Double-free of exported global string on program exit

### ISSUE THREAD

**Issue by mordante** [llvm/llvm-project#59765]
The following code is a reduction of a c++20 module application that crashes.
The easiest way to reproduce the crash is by using ASAN. 
When the application terminates, it gives a double-free error.

data.cppm
```c++
module;
#include <string>                                                               
export module data;
export std::string global;
```
main.cpp
```c++
import data;
int main() { global = "A long string that does not fit in the SSO buffer"; }
```

**Comment by ChuanqiXu9** [comment]
**Currently**, when we use global variables from modules, clang will call the corresponding constructor/destructor for these global variables in the importee. This should be wrong clearly.

As a workaround (if you need), you can add `inline` keywords in the declaration for the global variable.

**Comment by ChuanqiXu9** [comment]
Sent https://reviews.llvm.org/D140867
