### ISSUE TITLE
indvars incorrectly making code return poison

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#59777]
here we can see indvars doing something similar to bad behavior we've seen from GVN -- it is merging a couple of add instructions, but then it forgets to drop an UB flag on the merged add instruction, making the code emit poison when it wasn't supposed to do that

https://alive2.llvm.org/ce/z/6EzMpU

cc @nunoplopes @resistor

**Comment by resistor** [comment]
Seems like bug in SCEV, but I don't know much about the internals of it.

**Comment by resistor** [comment]
Candidate fix is in https://reviews.llvm.org/D140836
