### ISSUE TITLE
crashes on generic lambda with lambda in decltype (clang-frontend crash)

### ISSUE THREAD

**Issue by Dino1694** [llvm/llvm-project#59771]
Here's the compiler explorer I have for it:
https://godbolt.org/z/aTMPMMMqa
I compiled it on whatever the current compiler explorer's Clang trunk is.
In case the compiler explorer link goes stale, I have attached the code (`tmp.txt`, its a C++ file)
I used clang flags: `-Wall -std=c++20 -emit-llvm -Xclang -disable-llvm-passes`

I tried to reduce the code by hand as much as I could.
This is my first LLVM bug submission.

[tmp.txt](https://github.com/llvm/llvm-project/files/10328303/tmp.txt)

**Comment by Dino1694** [comment]
I thought I couldn't reduce it more, but I could.
Here's it even more reduced:
https://godbolt.org/z/YExrY91Yr
It seems it is essentially when you have a lambda inside the decltype of a generic lambda
but it may be more nuanced since if you don't have an include at the top, it doesn't crash.

```cpp

// if you comment out the include, it doesnt crash
#include <stdio.h>
// #include <stdbool.h>
// #include <iostream>
// #include <type_traits>

#define WANT_CRASH 1 // change to 1 or 0 to get the crash
auto g(){
    // arg1 has to be generic for it to crash
	[](auto arg1) -> decltype(
        // immediately invoked lambda
        #if WANT_CRASH
        []{
        #endif
           5
        #if WANT_CRASH
        ;
        }()
        #endif
    )
    // lambda body
    {}
    // dummy value passed as arg1
    (12)
    ;
}
```

**Comment by shafik** [comment]
This looks like https://github.com/llvm/llvm-project/issues/57170

**Comment by Dino1694** [comment]
You're right, it does.
Not sure how this works, possibly add the stuff I posted to a list of test cases if that's helpful?
👍

**Comment by EugeneZelenko** [comment]
@Dino1694: Please add new test case on #57170.
