### ISSUE TITLE
[InstCombine] Missing fold for 'and' pattern with multiple used 'xor'

### ISSUE THREAD

**Issue by barakgla** [llvm/llvm-project#59773]
Hi All,

I noticed that there is a pattern of `and(xor(sext(A), -1), B)` that is not being matched if
the `xor` has multiple uses.
In previous version of clang this pattern was matched to select instruction
as you can see here :
https://godbolt.org/z/M9oG6sa1q

From what I investigated I think that the check that was added in the patch https://reviews.llvm.org/rGf0071d43e4d30a0bc224020abb52fa77054d2520 
might caused this mismatch because `xor(sext(A), -1)` can't transform into `sext(xor(A, -1))`
and this caused us to mismatch the pattern :
`and(sext(A), B) -> select A, B, 0`
which was matched in the previous version of Clang.

@rotateright , Do you maybe have insight about this ?

Thanks very much,
Barak

**Comment by rotateright** [comment]
Thanks for the report. The one-use change that I added still looks right. We seem to be missing other folds because one-use restrictions are too conservative. 

It's also possible that we need to adjust canonicalization more towards select (rather than cast+not-of-boolean.

I'll take a look.

**Comment by nikic** [comment]
With https://github.com/llvm/llvm-project/commit/cb9569049c24e513afe215d5ac3b3dbc79dacf43 landed, can this be closed or is something more missing here?

**Comment by rotateright** [comment]
The IR for the C example should match that of LLVM 14 now, so closing. 
If there's anything more we can do in IR or codegen, please re-open or file another issue - thanks!
