### ISSUE TITLE
No known conversion with same type when splitting a module into implementation and interface file

### ISSUE THREAD

**Issue by shangoue** [llvm/llvm-project#59772]
I faced an issue when trying to split a named module into interface and implementation files, but I stumbled upon another very basic problem when trying to create a minimum reproduction case. Maybe I missed something?

I have two modules: `mod1` and `mod2` with a circular dependency.
Here is `mod1.cppm`:
```c++
export module mod1;
import mod2;
export namespace test
{
    struct S
    {
        int a = 1;

        void dump()
        {
            do_dump(this);
        }
    };
}
```
Here is `mod2.cppm` containing the interface:
```c++
export module mod2;
namespace test
{
    struct S;
    export void do_dump(S *);
}
```
And here is the implementation `mod2.impl.cppm` file:
```cpp
module;
#include <iostream>
module mod2;
import mod1;
namespace test
{
    void do_dump(S * s)
    {
        std::cout << s->a << "\n";
    }
}
```
Finally, I build my modules with the following command line:
```console
$ make
clang++-15 --precompile mod2.cppm -o mod2.pcm -std=c++20 -fprebuilt-module-path=. -Wall -I.
clang++-15 --precompile mod1.cppm -o mod1.pcm -std=c++20 -fprebuilt-module-path=. -Wall -I.
mod1.cppm:12:13: error: no matching function for call to 'do_dump'
            do_dump(this);
            ^~~~~~~
/home/etham/test_modules/bug_no_known_conversion/mod2.cppm:5:17: 
note: candidate function not viable: no known conversion from 'test::S *' to 'test::S *' for 1st argument
    export void do_dump(S *);
                ^
1 error generated.
```

Please find enclosed the related files and Makefile:
[bug_split_modules.zip](https://github.com/llvm/llvm-project/files/10328588/bug_split_modules.zip)

**Comment by ChuanqiXu9** [comment]
The implementation module unit is not an interface module unit. So the suffix should be `.cpp` instead of `.cppm`.

**Comment by shangoue** [comment]
Ok, but this wrong naming has no impact on the bug as it happens before the build of `mode2.impl`, isn't it ?

**Comment by ChuanqiXu9** [comment]
Oh, sorry I am confused. Reproduced with trunk. But it works if I refactored it into two partitions in the same module, things look good. And it is a little bit odd that we declare a forward declaration in a module and define it in another module. I am looking at the spec to find if it is valid.

**Comment by ChuanqiXu9** [comment]
It is pretty odd since the declarations in the module purview will be mangled with the corresponding module name. So the `S` in mod2 refers to a different entity with the `S` in mod1.

In the higher level, it is odd since there is cyclic dependency. Since mod1 depends on mod2 but mod2 also depends mod1 to implement `dump()`. So this is incorrect.

**Comment by shangoue** [comment]
Ok, I did not know the mangling of symbols was depending on their module... I understand now that cyclic dependency cannot work between modules like between compilation units.
