### ISSUE TITLE
Full specialization of variable template in module causes multiple definitions

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#59780]
The following set of files

```cpp
export module a;

export template<typename T>
int x = 0;

template<>
int x<int> = 0;
```

```cpp
import a;

int main() {
}
```

causes linking to full with a duplicate symbol error for `x<int>`. Changing to a partial specialization (for instance, using `std::same_as<int>`) appears to fix the issue.

**Comment by thebestnom** [comment]
Sorry for nagging
Is there a time frame which is to be released, it makes my project on hold/a big rewrite 😅 (remind me to never use latest feature, not matter how usefull they are)

**Comment by ChuanqiXu9** [comment]
> Thanks, is there a way to ask for it to be cherrypicked and released as .fix? 😅

No, there won't be new 15.x. And only several regression bug can ask such back ports. But the bug is not a regression bug.
