### ISSUE TITLE
Avoid cmov for conditional negation

### ISSUE THREAD

**Issue by deadalnix** [llvm/llvm-project#59791]
A typical way to do conditional negation would look like:

```c++
int64_t maybeNegateCMOV(uint64_t value, bool neg) {
    return neg ? -value : value;
}
```

Which generates the following codegen:
```asm
maybeNegateCMOV(unsigned long, bool):                  # @maybeNegateCMOV(unsigned long, bool)
        mov     rax, rdi
        neg     rax
        test    esi, esi
        cmove   rax, rdi
        ret
```

However, it is possible to do the same computation using math, and avoid the cmov, the following way:
```c++
int64_t maybeNegateMATH(uint64_t value, bool neg) {
    return (value - neg) ^ -neg;
}
```

Which generate the following codegen:
```asm
maybeNegateMATH(unsigned long, bool):                  # @maybeNegateMATH(unsigned long, bool)
        mov     eax, esi
        sub     rdi, rax
        neg     rax
        xor     rax, rdi
        ret
```

This is a fairly common pattern, and would benefit from being recognized, IMO.

**Comment by topperc** [comment]
If the bool is generated locally won’t we also need a setne to move it to a GPR for the math version?

**Comment by LebedevRI** [comment]
I think the request here is https://alive2.llvm.org/ce/z/gkkgX5

**Comment by deadalnix** [comment]
Indeed, the cmov is probably advantageous in the cases where it can avoid the generation of a setne.

**Comment by LebedevRI** [comment]
Since we already do this for and/or: https://alive2.llvm.org/ce/z/q9-MqK https://alive2.llvm.org/ce/z/2yiJv_
the `xor` case https://alive2.llvm.org/ce/z/dm3Ume seems like a simple oversight.

**Comment by LebedevRI** [comment]
We already do this for and/or: https://alive2.llvm.org/ce/z/q9-MqK https://alive2.llvm.org/ce/z/AUUEMZ
But for `xor` case https://alive2.llvm.org/ce/z/dm3Ume, we canonicalize the other way around.

**Comment by LebedevRI** [comment]
The next question being, under which conditions do we want to undo this during codegen?

**Comment by topperc** [comment]
Why did cf58063 close this ticket? Isn't that doing the exact opposite of the request? The request is not to use cmov(select).

**Comment by rotateright** [comment]
Here's asm for some common targets (arm, aarch64, riscv32, x86-64):
https://godbolt.org/z/Eqhb7xhT6

It doesn't seem like a win unless we're trying to avoid branches on riscv or on x86 and only if we don't need to generate a 'set'. Even x86 may not be a win if 'cmov' is implemented as a 1-cycle op. 

Is there any experimental data that says the math variant performs better?
