### ISSUE TITLE
clang-tidy gives incorrect result for `__has_builtin`

### ISSUE THREAD

**Issue by russellmcc** [llvm/llvm-project#59807]
`clang-tidy` sometimes gives the wrong result for `__has_builtin`.

For example:

```cpp
#if !__has_builtin(__builtin_os_log_format)
#error "Needs built-in"
#endif

int main() {}
```

gives an error (https://godbolt.org/z/fWdz4zx6h), even though the built-in is actually there (https://godbolt.org/z/oE567Yeve)

**Comment by russellmcc** [comment]
Apparently this only happens in `-std=c++20`

**Comment by PiotrZSL** [comment]
Duplicate of #50087.
https://discourse.llvm.org/t/rfc-expand-modular-headers-ppcallbacks-problem-in-c-20/71628
