### ISSUE TITLE
Clang: `sizeof` boolean vector using `__attribute__((ext_vector_type(4)))` evaluates to zero.

### ISSUE THREAD

**Issue by He3lixxx** [llvm/llvm-project#59801]
The documentation on the boolean vector extension [currently says](https://clang.llvm.org/docs/LanguageExtensions.html#boolean-vectors):
> Clang also supports the `ext_vector_type` attribute with boolean element types in C and C++. For example:
> ```c++
> typedef bool bool4 __attribute__((ext_vector_type(4)));
> // Objects of bool4 type hold 8 bits, sizeof(bool4) == 1
> ```

Yet this program doesn't compile ([godbolt](https://godbolt.org/z/h19GEYsar)):
```c++
typedef bool bool4 __attribute__((ext_vector_type(4)));
// Objects of bool4 type hold 8 bits, sizeof(bool4) == 1

static_assert(sizeof(bool4) == 1);
```
with this error
```console
<source>:4:1: error: static assertion failed due to requirement 'sizeof(bool __attribute__((ext_vector_type(4)))) == 1'
static_assert(sizeof(bool4) == 1);
^             ~~~~~~~~~~~~~~~~~~
<source>:4:29: note: expression evaluates to '0 == 1'
static_assert(sizeof(bool4) == 1);
              ~~~~~~~~~~~~~~^~~~
1 error generated.
Compiler returned: 1
```

**Comment by shafik** [comment]
CC @simoll @erichkeane since this documentation was added via commit 0aab344104034e6191114a74f0d9eb5129bf550d by Simon and Erich reviewed it.

**Comment by AaronBallman** [comment]
Something is amiss, `sizeof` should not return `0` (otherwise, how do you make an array of such objects?)

**Comment by erichkeane** [comment]
> Something is amiss, `sizeof` should not return `0` (otherwise, how do you make an array of such objects?)

I'm guessing we never tried :)  These objects aren't commonly put in arrays i suspect.  I was hoping @simoll would come back and fix this, but the getTypeInfoImpl looks like we tried to get it right: https://github.com/llvm/llvm-project/blob/main/clang/lib/AST/ASTContext.cpp#L2001

So either something in that test is wrong, or we are doing something goofy around sizeof that doesn't go through getTypeInfoImpl.  I don't really see what is missing without a debugger.

**Comment by erichkeane** [comment]
Ok, the problem IS in ASTContext.cpp in the handling of ExtVector in getTypeInfoImpl as stated before.  The problem is that the 'Width' is set to the number of bits, but it does NOT make it at least 8.  The number of bits ends up getting 'rounded down' when we convert from bits to bytes, so it gets lost.

It seems to work (thanks to the alignment adjustment) for smaller sizes, but I believe there needs to be a:

`Width = std::max<unsigned>(8, Width)` for the width as well as the alignment, and perhaps a bit of 'round to the nearest whole byte' anyway.

@Fznamznon : I know you were looking for a 'beginner' bug, this one would be an easy way to get started :)

**Comment by Fznamznon** [comment]
> @Fznamznon : I know you were looking for a 'beginner' bug, this one would be an easy way to get started :)

Oh, nice! I'll take a look at this one.

**Comment by Fznamznon** [comment]
Here is the fix https://reviews.llvm.org/D142550

**Comment by Fznamznon** [comment]
Ah, just adding "Fixes #issue_id" to commit message closes the GitHub issue once commit is pushed. Just the same way as with the PRs.
@shafik FYI.

**Comment by steakhal** [comment]
Do we plan to backport this change to `release/16.x`? @Fznamznon

**Comment by Fznamznon** [comment]
> Do we plan to backport this change to `release/16.x`? @Fznamznon

I don't mind, however I'm new here and not involved into release process, so that is probably not up to me.

**Comment by AaronBallman** [comment]
It's not fixing a regression, so I don't think we planned to backport it. However, the changes are simple enough that I don't think it would be harmful to backport either. @steakhal -- do you need it backported for some reason?
