### ISSUE TITLE
[flang] flang-new vs gfortran (elemental functions)

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#59816]
Test code:
https://github.com/gcc-mirror/gcc/blob/master/gcc/testsuite/gfortran.fortran-torture/execute/elemental.f90

flang-new:
```console
$ flang-new -flang-experimental-exec elemental.f90
$ ./a.out
Fortran STOP: code 2
```

gfortran:
```console
$ gfortran -Wall -Wextra elemental.f90
$ ./a.out
$
```

compiler version:
```console
$ flang-new --version
flang-new version 16.0.0 (https://github.com/llvm/llvm-project.git 83d4851436904c005ff0831e38e1814a0a8f00ac)
Target: x86_64-unknown-linux-gnu
Thread model: posix

$ gfortran --version
GNU Fortran (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
```

**Comment by kiranchandramohan** [comment]
Thanks for testing Flang with the gfortran testsuite. 

To have a way to organize the issues, could you add all issues from the gfortran testsuite to the following project board : https://github.com/orgs/llvm/projects/17/views/1 ?

**Comment by k-arrows** [comment]
@kiranchandramohan 

> Thanks for testing Flang with the gfortran testsuite.
> 
> To have a way to organize the issues, could you add all issues from the gfortran testsuite to the following project board : https://github.com/orgs/llvm/projects/17/views/1 ?

Yes, I'm trying to test flang-new with gfortran testsuite. It's a good idea to organize issues.
By the way, it seems that I cannot access the URL you have shown (404: Page not found).
What should I do?

**Comment by kiranchandramohan** [comment]
I think you cannot access the URL because you are not a member of the `llvm-project` github. People are usually added when commit access is given as per the procedure described in https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access.

You can either leave this (adding the project) to existing members or you can ask a question in llvm discourse (https://discourse.llvm.org/) on how to become a member of `llvm-project`.

**Comment by k-arrows** [comment]
> I think you cannot access the URL because you are not a member of the `llvm-project` github. People are usually added when commit access is given as per the procedure described in https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access.
> 
> You can either leave this (adding the project) to existing members or you can ask a question in llvm discourse (https://discourse.llvm.org/) on how to become a member of `llvm-project`.

@kiranchandramohan
Thank you for your detailed explanation. I'm sorry to bother you, but I want to leave the task (=adding issues to the project board) to existing members since I'm a beginner of LLVM community.

**Comment by hakostra** [comment]
This testcase seems to work in most recent main branch flang-new:

```
$ flang-new elemental.f90 
$ ./a.out
$ echo $?
0
$ flang-new --version
flang-new version 20.0.0git (https://github.com/llvm/llvm-project.git cd634f57c10dedbe4f908889dece2c4460b702c9)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/llvm/llvm-project/install/bin
```

**Comment by k-arrows** [comment]
Thank you for your posting the result with recent main branch flang-new. I will close this issue.
