### ISSUE TITLE
Include-cleaner: instantiated template bodies should not (usually) be traversed

### ISSUE THREAD

**Issue by sam-mccall** [llvm/llvm-project#59825]
Consider this template:

```cpp
template <class T>
int get() { return T::value; }
```

Here the definition of `get()` itself clearly isn't a reference to `Foo::value`, even if we later instantiate `get<Foo>`.
(Usually instantiating `get<Foo>` means mentioning `Foo` somewhere and so `Foo.h` will end up being included.)

So we want to walk the body of `get<T>` (the "templated function") but not `get<Foo>` (the "implicit template specialization").

---

This hasn't been a really obvious problem, because normally one of the following applies:
 - the template is in a header, so its instantiation is not in the main file, so we already don't walk it
 - the template is in the main file, and so is the instantiation site, and between them it's reasonable to consider Foo::value used
 - the template is in the main file (which is a header), and the instantiation sites are in other files => not in this TU => we already don't walk them

However we can avoid all these cases and still have this problem:

```cpp
// a.h
struct A { static int value; };

// dispatch.h
#include "a.h"
template <class Getter>
int dispatch() {
  return Getter::template get<A>();
}

// main.cc
struct MyGetter {
  template <class T> int get() { return T::value; }
};
int v = dispatch<MyGetter>();
```

Here, `MyGetter::get<A>()` is defined in `main.cc`, and (indirectly) instantiated from `main.cc`, and yet the reference to `A::value` can't reasonably be associated with `main.cc` since the `A` is only mentioned in `dispatch.h`.

(This seems ridiculous, but is extracted from real code).

---

The most direct solution is to avoid walking functions (and classes, and variables, and aliases, and concepts?) that were instantiated from templates. This might lead to missing references we were previously finding, which would be a regression.

I think we should probably do this first, understand the fall-out, and then deliberately work out heuristics for when it's OK to traverse the instantiated bodies.

A less-direct idea is just preventing instantiation in the first place using SkipFunctionBodies like in clangd, but I don't think this really works: we don't always have full control over the parse (e.g. if embedded in a clang-tidy check), and not all templates are skippable functions (e.g. classes, auto-typed functions).

**Comment by hokein** [comment]
It looks like the default behaviour of `RecursiveASTVisitor` is to not traverse template instantiations (the [shouldVisitTemplateInstantiations](https://github.com/llvm/llvm-project/blob/main/clang/include/clang/AST/RecursiveASTVisitor.h#L167) interface returns false by default). Probably there are some bugs in the RAV.

I recall a relevant patch https://reviews.llvm.org/D120498 (in case you missed that).

**Comment by kadircet** [comment]
> The most direct solution is to avoid walking functions (and classes, and variables, and aliases, and concepts?) that were instantiated from templates. This might lead to missing references we were previously finding, which would be a regression.

> I think we should probably do this first, understand the fall-out, and then deliberately work out heuristics for when it's OK to traverse the instantiated bodies.

I agree with the conclusions here, and I am less worried about the fall-out in general case. As discussed offline, most of the time the type that's used in the instantiation will also be spelled (surely CTAD and other language constructs might make this worse, but hopefully they won't be the general case).
So hopefully we can get away by not traversing, without introducing big regressions.

**Comment by sam-mccall** [comment]
> It looks like the default behaviour of RecursiveASTVisitor is to not traverse template instantiations

Hypothesis: we're capturing these as top-level decls, and explicitly calling TraverseDecl. Filtering of an ignored node tends to happen in the parent rather than the node itself. (Not sure this is right, my point is mostly we need to work out what's going on here).

> I recall a relevant patch https://reviews.llvm.org/D120498 (in case you missed that).

Sure, let me update and land that.

> the type that's used in the instantiation will also be spelled

FWIW I'm more worried about function calls in template bodies that will no longer be resolved (because their args are dependent).

**Comment by hokein** [comment]
> Hypothesis: we're capturing these as top-level decls, and explicitly calling TraverseDecl. Filtering of an ignored node tends to happen in the parent rather than the node itself. (Not sure this is right, my point is mostly we need to work out what's going on here).

Ah, yeah, this is a good point. It is sad that RAV subtly breaks with the captured top-level decls :(
