### ISSUE TITLE
[Clang][concepts] Conditional `explicit` specifier is checked too early in constrained constructor

### ISSUE THREAD

**Issue by JMazurkiewicz** [llvm/llvm-project#59827]
Repro (3rd version, 2nd version reproduced other possible bug; see edit history):

```c++
template<class X>
constexpr X failure() {
    return nullptr;
}

struct T {
    template<class X>
        requires false
    constexpr explicit(failure<X>()) T(X) { }

    T(int) { }
};

static T t(5);
```

Expected: *correct compilation*

Got:

```console
<source>:3:12: error: cannot initialize return object of type 'int' with an rvalue of type 'std::nullptr_t'
    return nullptr;
           ^~~~~~~
<source>:9:24: note: in instantiation of function template specialization 'failure<int>' requested here
    constexpr explicit(failure<X>()) T(X) { }
                       ^
<source>:14:10: note: while substituting deduced template arguments into function template 'T' [with X = int]
static T t(5);
         ^
```

Compiler explorer: https://godbolt.org/z/sPsGh46Gs
Discovered in: https://github.com/microsoft/STL/pull/3323

**Comment by CaseyCarter** [comment]
I think the key wording here is [[over.match.funcs.general]/8](https://eel.is/c++draft/over.match.funcs.general#8): "... If a constructor template or conversion function template has an _explicit-specifier_ whose _constant-expression_ is value-dependent ([[temp.dep]](https://eel.is/c++draft/temp.dep)), template argument deduction is performed first and then, if the context admits only candidates that are not explicit and the generated specialization is explicit ([[dcl.fct.spec]](https://eel.is/c++draft/dcl.fct.spec)), it will be removed from the candidate set. ..."

**Comment by nitnelave** [comment]
Note that it makes clang-17 unable to compile a lot of code with the libstdc++ distributed with GCC 13. You can reproduce by trying to compile `std::is_constructible<std::tuple<int>, std::tuple<>>` (root cause is the same)

**Comment by LYP951018** [comment]
clang couldn't compile this, too https://godbolt.org/z/zvoqxhjWh
`Sema::InstantiateFunctionDefinition` sets `CodeSynthesisContext` to `TemplateInstantiation`
```cpp
InstantiatingTemplate Inst(*this, PointOfInstantiation, Function);
```
which makes `isSFINAEContext` return `false`

**Comment by shafik** [comment]
CC @erichkeane

**Comment by LYP951018** [comment]
i'm hacking on this. Currently I partially instantiate the constructor decl and mutate the AST via `setExplicitSpecifier` after deferred instantiation of explicit speciifer during template argument deduction. Is that reansonable? I want to ensure the decl specialization have resolved explicit specifier... Could you please give me some advice on this? @erichkeane  ;)

**Comment by erichkeane** [comment]
I think that seams reasonable.  I believe there is a version of the exception specifier 'storage' that allows us to have uninstantiated exception specifiers in place, and I think we should be able to use that.  It might 'just work' after that, since i think later lookups/uses of these check and instantiate that.

**Comment by LYP951018** [comment]
This issue is about **_explicit_**  specifier but not exception specifier. Did I miss anything here?

**Comment by erichkeane** [comment]
> This issue is about **_explicit_** specifier but not exception specifier. Did I miss anything here?

Woops, nope, I think I did.  I don't have a good idea here unfortunately on how to give advise then, but what you said in your post at least seems promising.
