### ISSUE TITLE
LoongArch llc tests should not use -disable-verify

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#59839]
These tests explicitly disable the verifier and have broken immarg usage:
llvm/test/CodeGen/LoongArch/intrinsic-la32-error.ll
llvm/test/CodeGen/LoongArch/frameaddr-returnaddr-error.ll

Illegal immarg handling should be a separate IR verifier test in llvm/test/Verifier

**Comment by SixWeining** [comment]
Thanks for reporting the issue. We will fix it as soon as possible.
