### ISSUE TITLE
Worse optimization compared to GCC

### ISSUE THREAD

**Issue by joemalle** [llvm/llvm-project#59834]
Clang compiles this function into 24 instructions compared to 17 for GCC (with `-O3 -ffast-math`)
```c++
void result(double a, double b) {
    bool cond = (a == 0 & b == 0.0);
    double ret = 0.0;
    if (cond) [[likely]] {
        external1();
    }
    external2(!cond);
}
```
https://godbolt.org/z/jWfszY9zE

I think the problem is that LLVM tries to apply De Morgan's law to the expression without realizing it won't be able to remove the original.

**Comment by vfdff** [comment]
There's no issue on AArch64 backend https://godbolt.org/z/f5dY93qsY

**Comment by nikic** [comment]
Not just aarch64, it's already fine in LLVM 16: https://godbolt.org/z/1hc81T4KG
