### ISSUE TITLE
[AMDGPU] LowerSwitchID should be required in the UnifyDivergentExitNodes pass

### ISSUE THREAD

**Issue by gandhi56** [llvm/llvm-project#59830]
As discussed in [D139780](https://reviews.llvm.org/D139780#inline-1360495), insert a requirement for LowerSwitchID.

**Comment by gandhi56** [comment]
Naively inserting a requiredID causes a scheduling error for the PDT construction pass. I am working on a patch to wrap AMDGPUUnifyDivergentExitNodes with a NewPM.

**Comment by gandhi56** [comment]
`Unable to schedule 'Post-Dominator Tree Construction' required by 'Unify divergent function exit nodes'`

**Comment by gandhi56** [comment]
I am not really sure what preserves may be missing, is there a way to figure them out @arsenm ?

**Comment by arsenm** [comment]
Look at -debug-pass=Structure and figure out which analysis might need to be recomputed

**Comment by nhaehnle** [comment]
If I had to guess, LowerSwitch invalidates post-dominator trees, so they have to be rebuilt after LowerSwitch but before UnifyDivergentExitNodes, but that invalidates LowerSwitch.

**Comment by gandhi56** [comment]
Agreed, `PostDominatorTree` needs to be recomputed. `UniformityInfo` also needs to be recomputed but I am not sure how to do so. @ssahasra

**Comment by jayfoad** [comment]
> If I had to guess, LowerSwitch invalidates post-dominator trees, so they have to be rebuilt after LowerSwitch but before UnifyDivergentExitNodes, but that invalidates LowerSwitch.

I didn't realise LowerSwitch was used like an analysis. I guess it should be trivial to mark it as preserved by any pass (like UnifyDivergentExitNodes) that does not spontaneously create new SwitchInsts.

**Comment by gandhi56** [comment]
In my understanding, `LowerSwitch` preserves `DominatorTree` and `UniformityInfo`. It causes an error in the `DomTreeUpdater`:

```
Pass Arguments:  -domtree
  FunctionPass Manager
    Dominator Tree Construction
Pass Arguments:  -cycles
  FunctionPass Manager
    Cycle Info Analysis
	.text
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /Users/gouenji56/workspace/llvm-project/build/bin/llc -march=amdgcn -mcpu=tahiti -verify-machineinstrs -amdgpu-s-branch-bits=4 -simplifycfg-require-and-preserve-domtree=1 --debug-pass=Structure
1.	Running pass 'CallGraph Pass Manager' on module '<stdin>'.
2.	Running pass 'Dominance Frontier Construction' on function '@uniform_unconditional_min_long_backward_branch'
 #0 0x000000010454cc64 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/Users/gouenji56/workspace/llvm-project/build/bin/llc+0x103668c64)
 #1 0x000000010454d1c0 PrintStackTraceSignalHandler(void*) (/Users/gouenji56/workspace/llvm-project/build/bin/llc+0x1036691c0)
 #2 0x000000010454afd8 llvm::sys::RunSignalHandlers() (/Users/gouenji56/workspace/llvm-project/build/bin/llc+0x103666fd8)
 #3 0x000000010454efec SignalHandler(int) (/Users/gouenji56/workspace/llvm-project/build/bin/llc+0x10366afec)
 #4 0x00000001b05742a4 (/usr/lib/system/libsystem_platform.dylib+0x1803fc2a4)
 #5 0x0000000101f5ed6c llvm::ForwardDominanceFrontierBase<llvm::BasicBlock>::calculate(llvm::DominatorTreeBase<llvm::BasicBlock, false> const&, llvm::DomTreeNodeBase<llvm::BasicBlock> const*) (/Users/gouenji56/workspace/llvm-project/build/bin/llc+0x10107ad6c)
 #6 0x0000000101f5eabc llvm::ForwardDominanceFrontierBase<llvm::BasicBlock>::analyze(llvm::DominatorTreeBase<llvm::BasicBlock, false>&) (/Users/gouenji56/workspace/llvm-project/build/bin/llc+0x10107aabc)
 #7 0x0000000101f5f3d0 llvm::DominanceFrontierWrapperPass::runOnFunction(llvm::Function&) (/Users/gouenji56/workspace/llvm-project/build/bin/llc+0x10107b3d0)
 #8 0x0000000103600ecc llvm::FPPassManager::runOnFunction(llvm::Function&) (/Users/gouenji56/workspace/llvm-project/build/bin/llc+0x10271cecc)
 #9 0x0000000101ee502c (anonymous namespace)::CGPassManager::RunPassOnSCC(llvm::Pass*, llvm::CallGraphSCC&, llvm::CallGraph&, bool&, bool&) (/Users/gouenji56/workspace/llvm-project/build/bin/llc+0x10100102c)
#10 0x0000000101ede940 (anonymous namespace)::CGPassManager::RunAllPassesOnSCC(llvm::CallGraphSCC&, llvm::CallGraph&, bool&) (/Users/gouenji56/workspace/llvm-project/build/bin/llc+0x100ffa940)
#11 0x0000000101eddf50 (anonymous namespace)::CGPassManager::runOnModule(llvm::Module&) (/Users/gouenji56/workspace/llvm-project/build/bin/llc+0x100ff9f50)
#12 0x000000010360175c (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) (/Users/gouenji56/workspace/llvm-project/build/bin/llc+0x10271d75c)
#13 0x00000001036012fc llvm::legacy::PassManagerImpl::run(llvm::Module&) (/Users/gouenji56/workspace/llvm-project/build/bin/llc+0x10271d2fc)
```
Smells like a bug in the preparations towards DominatorTree updates in `AMDGPUUnifyDivergentExitNodes`.

**Comment by gandhi56** [comment]
I don't think there is a way to require LowerSwitch without running the PDTWrapperPass and Uniformity analysis. Perhaps its better to not require LowerSwitch?

**Comment by jayfoad** [comment]
I came up with this: https://github.com/jayfoad/llvm-project/commit/c03cbd4d2f584d24e2100fee529f2ba1d18c345d

It's a bit subtle because it only works if you do the requires in this order:
```
  AU.addRequiredID(LowerSwitchID);
  ...
  AU.addRequired<UniformityInfoWrapperPass>();
```
Otherwise UniformityInfo is scheduled first, and then LowerSwitch which does not preserve UniformityInfo.

**Comment by gandhi56** [comment]
Ahh I see, I guess that works!

**Comment by jayfoad** [comment]
@ruiling

**Comment by ruiling** [comment]
I think the current way to declare the dependency on LowerSwitch like analysis pass still sounds surprising even it works with legacy PassManager. We usually maintain function pass dependency by inserting the pass into PM in the order we want. And NewPM does not support such kind of situation "a function pass depends on another function pass". So I think it might be good to stop using LowerSwitch this way. Let's just use it like normal function pass. I have made a change (#68662) to show the idea.
The major benefit would be:
1. It is less surprising
2. It can work well with both LegacyPM and NewPM with less code.
3. We would only insert the LowerSwitch in one way like other function pass here (https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/AMDGPU/AMDGPUTargetMachine.cpp#L1101) instead of the current two ways (explicitly insert into PM and also require it like analysis).

Feel free to leave some comments on the PR @nhaehnle @gandhi56

**Comment by ruiling** [comment]
I think we can close this since my PR was merged.
