### ISSUE TITLE
compiler-rt: 3 tests did not pass

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5985]
|  |  |
| --- | --- |
| Bugzilla Link | [5613](https://llvm.org/bz5613) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The following tests FAILED:
         24 - enable_execute_stack_test (SEGFAULT)
         38 - fixunssfti_test (Failed)
         74 - fixunsdfti_test (Failed)
Errors while running CTest

./test/fixunssfti_test
error in __fixunssfti(-0X1P+0) = 0x0000000000000000FFFFFFFFFFFFFFFF, expected 0x00000000000000000000000000000000

./test/fixunsdfti_test
error in __fixunsdfti(-0X1P+0) = 0x0000000000000000FFFFFFFFFFFFFFFF, expected 0x00000000000000000000000000000000

The OS is an Kubuntu Karmic on an Intel Core 2 Duo (P9500).

For further questions, please ask.

Thanks in advance.

**Comment by arsenm** [comment]
Old test failure
