### ISSUE TITLE
__builtin_object_size(..., 1) of a struct member acts like __bos(..., 0)

### ISSUE THREAD

**Issue by kees** [llvm/llvm-project#59850]
```c
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

struct inside {
    int foo;
    int bar;
};

struct wat {
    struct inside array[20];
    int cow;
};

#define report(x)   printf(#x ": %zu\n", x)

struct wat *thing(void)
{
    struct wat *pool;
    struct wat local;
    struct inside *item;
    int j;

    pool = &local;
    item = pool->array;

    j = 4;

    report(sizeof(*item)); // should be 0x8
    report(__builtin_dynamic_object_size(pool, 0)); // should be 0x164
    report(__builtin_dynamic_object_size(pool, 1)); // should be 0x164
    report(__builtin_dynamic_object_size(item, 0)); // should be 0x164
    report(__builtin_dynamic_object_size(item, 1)); // should be 0x160 <- Clang says 0x164
    report(__builtin_dynamic_object_size(item + j, 1)); // should be 0x132

    return pool;
}
```

For `__builtin_dynamic_object_size(item, 1)` Clang reports 0x164. GCC correctly reports 0x160.

See https://godbolt.org/z/Gb5hMsrdT

Noticed while debugging https://github.com/ClangBuiltLinux/linux/issues/1780
cc @nickdesaulniers @nathanchance @isanbard

**Comment by nikic** [comment]
This is not really specific to __builtin_dynamic_object_size (there are no dynamic sized involved here), it is a general problem with __builtin_object_size, see https://github.com/llvm/llvm-project/issues/55742 for an existing issue on the topic. The TL;DR is that LLVM does not meaningfully support mode 1/3 unless it can get folded in the frontend.

**Comment by kees** [comment]
@bwendling
