### ISSUE TITLE
Missing prebuilt assets for LLVM 12.0.1 releases

### ISSUE THREAD

**Issue by theblackunknown** [llvm/llvm-project#59885]
Hi, 

I am looking to leverage prebuilt assets for LLVM releases and I noticed that some are missing for LLVM 12.0.1.
I am interested in particular on the following ones:
- `win64`
- `x86_64-linux-gnu-ubuntu-16.04` / `x86_64-linux-gnu-ubuntu-18.04`
- `x86_64-apple-darwin` / `arm64-apple-darwin` 

I am willing to help to build some of those myself and add them to the assets list, is the process of doing so documented somewhere ?

**Comment by EugeneZelenko** [comment]
12 is too old. Only most recent release is supported.

**Comment by Naville** [comment]
Previously you'll need to be assigned as a trusted release-tester to test and upload your built binaries, nowadays I think it's all done by GH Actions
