### ISSUE TITLE
clang assumes `this` is aligned, misoptimizes for tagged pointers

### ISSUE THREAD

**Issue by nbuwe** [llvm/llvm-project#59889]
clang 13 and later seem to assume that "this" in C++ is always suitably aligned and optimize aggressively based on that assumption.

The following example is distilled from the [Self](https://selflanguage.org/) VM code.  clang 13+ compiles `foo` to always return 666.  clang 12 emits the code to check the tag.
```
typedef unsigned long uintptr_t;

class T {
public:
    void *data;			// need aligned data memeber to trigger

    int foo() const { return 42; }

    uintptr_t tag() const {
	// clang assumes "this" is aligned and so tag always returns 0
	return reinterpret_cast<uintptr_t>(this) & 0x3;
    }

    T *addr() const {
	return (T *)(reinterpret_cast<uintptr_t>(this) &~ 0x3);
    }
};

// This function is miscompiled to return 666
int
foo(T *t)
{
#if 1
    uintptr_t tag = t->tag();	// <- misoptimized
#else
    uintptr_t tag = reinterpret_cast<uintptr_t>(t) & 0x3; // ok
#endif

    int i;
    if (tag == 1)
	i = t->addr()->foo();
    else
	i = 666;

    return i;
}
```
Self VM uses lower bits in pointers as tags (for the garbage collector, etc) and uses inline methods like `tag` and `addr` above to manipulate such tagged pointers.

**Comment by LebedevRI** [comment]
This is not a miscompile.
Calling member functions of `T` with 'tagged' pointer is UB: https://godbolt.org/z/Kz95djvzx
And honestly, even creating misaligned pointer is UB in the first place.
