### ISSUE TITLE
correlated value propagation misoptimizing @llvm.abs.i1

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#59887]
when this function is invoked as `f(1,1)`  the abs call returns 1 and then we select the true branch so the return value must be 1:

```llvm
define i1 @f(i1 %0, i1 %1) {
  %3 = call i1 @llvm.abs.i1(i1 %0, i1 false)
  %4 = select i1 %1, i1 %3, i1 false
  ret i1 %4
}

declare i1 @llvm.abs.i1(i1, i1 immarg) #0

attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
```

however, CVP is incorrectly transforming it to return a constant 0:

https://alive2.llvm.org/ce/z/s5vlDP

cc @nunoplopes

**Comment by topperc** [comment]
Looks like a bug in ConstantRange::abs.

We hit this code
```
  return ConstantRange(APInt::getZero(getBitWidth()),                            
                       APIntOps::umax(-SMin, SMax) + 1);
```

SMin is -1, SMax is 0. APIntOps::umax(-SMin, SMax) is -1.  Adding 1 gives 0. Which I think creates an empty set.
