### ISSUE TITLE
AArch64 backend miscompile of some funnel shifts

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#59898]
This function is getting miscompiled by the AArch64 backend:
```ll
source_filename = "fuzz"

define noundef i15 @f(i15 %0) {
  %2 = call i15 @llvm.fshr.i15(i15 %0, i15 %0, i15 12)
  %3 = call i15 @llvm.fshl.i15(i15 %2, i15 %2, i15 11)
  ret i15 %3
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i15 @llvm.fshr.i15(i15, i15, i15) #0

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i15 @llvm.fshl.i15(i15, i15, i15) #0

attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
```

Let's work through it. call `f(3)` which gives us a `fshr(3, 3, 12)` which comes down to:

`000000000000011 000000000000011 >> 12` =
`000000000000000 000000000011000` = 
`000000000011000`

now we do the funnel shift left of that value by 11, giving:

`000000000011000 000000000011000 << 11` =
`100000000000001 100000000000000` =
`100000000000001` =
16385

so that's what's supposed to happen. but the AArch64 backend gives:

```asm
_f:
	lsr	w8, w0, #8
	bfi	w8, w0, #7, #25
	mov	w0, w8
	ret
```

when passed 3 as an argument, this gives 384

cc @nunoplopes @nbushehri

**Comment by bcl5980** [comment]
Candidate Patch:
https://reviews.llvm.org/D141363
