### ISSUE TITLE
[AArch64] 16-byte atomic loads using load-pair may not be atomic

### ISSUE THREAD

**Issue by atdt** [llvm/llvm-project#59904]
With -march=arm8.4-a, clang uses an LDP instruction to do a 16-byte atomic load. According to Arm's documentation, LDP [does not guarantee that all 16 bytes are loaded atomically](https://developer.arm.com/documentation/den0024/a/The-A64-instruction-set/Memory-access-instructions/Memory-access-atomicity) "Load pair and store pair instructions to a pair of general-purpose registers, using an aligned memory address are guaranteed to appear as _two_ individual atomic accesses.". So there may be a risk of tearing when the first 64-bits overflows into the second.

Godbolt link: https://godbolt.org/z/TW3Pb1KG7

**Comment by efriedma-quic** [comment]
See the section "Changes to single-copy atomicity in Armv8.4" in the architecture reference (https://developer.arm.com/documentation/ddi0487/latest).

LLVM refers to this internally as "lse2".

**Comment by atdt** [comment]
@efriedma-quic TIL. Thank you.
