### ISSUE TITLE
[AssumptionCache] should consider caching the conditions of intrinsic guards

### ISSUE THREAD

**Issue by caojoshua** [llvm/llvm-project#59901]
Inspired by https://reviews.llvm.org/D141243. There are use cases where the conditions of branches and intrinsic guards and assumes are considered equally. We should consider extending assumption cache to cover branches and guards.

Needs further investigation investigation in the current ways `AssumptionCache` is used and if we should modify or add APIs. For example, should `AssumptionCache::Assumptions()` return all conditions for branches, assumes, and guards? If just assumes, then we can add following functions:

```cpp
AssumptionCache::Branches();
AssumptionCache::Guards();
AssumptionCache::Conditions(); // Covers all three
```

Also consider renaming `AssumptionCache`.

If we add branch conditions, a whole lot more testing would be required. Branches get removed frequently in transformations, and `AssumptionCache` does not seem to be cleaned up very much (my editor finds no references to `AssumptionCache::clear()`.

More discussion/investigation required.

**Comment by nikic** [comment]
I would keep branches out of this. I believe that for all current uses of AssumptionCache, llvm.assume and llvm.experimental.guard can be treated in exactly the same way -- the relevant property we care about is that they establish a condition in dominated code, even if their precise semantics don't match. I don't believe there is a need to separate these into different methods.

As such, I think the implementation would need a) add AssumeOrGuardInst to abstract over these, b) work with AssumeOrGuardInst in AssumptionCache and c) update some callers to do the same, especially things like registerAssumption(). And then drop all the manual guard handling code.

**Comment by caojoshua** [comment]
> I would keep branches out of this. I believe that for all current uses of AssumptionCache, llvm.assume and llvm.experimental.guard can be treated in exactly the same way -- the relevant property we care about is that they establish a condition in dominated code, even if their precise semantics don't match.

The relevant property you have stated can be applied to branches as well. What is the reason to keep branches out of this? Is it just an implementation complexity issue?

**Comment by caojoshua** [comment]
OK thanks. Will just deal with intrinsic guards initially.

**Comment by caojoshua** [comment]
This change was reverted since it increases compile time significantly in some workloads. I don't think this will be revisited. And guards on deprecation path anyway, so this is not as useful.
