### ISSUE TITLE
[packaging] libclang-rt-14-dev conflicts with other clang-14 packages

### ISSUE THREAD

**Issue by vient** [llvm/llvm-project#59903]
At least in Ubuntu Focal repo https://apt.llvm.org/focal, `libclang-common-14-dev=14.0.6~++20230108112125+f28c006a5895-1~exp1~20230108112200.170` has no `include/sanitizer` folder which breaks build with sanitizers.

```console
$ dpkg -L libclang-common-14-dev | grep sani
/usr/lib/llvm-14/lib/clang/14.0.6/include/sanitizer

$ sudo apt install libclang-common-14-dev
....

$ dpkg -L libclang-common-14-dev | grep sani
$
```

It is not possible to downgrade since only latest version is provided.
_____
Update: as @NixFrog noticed, libclang-rt-14-dev (where sanitizers have moved) uses incorrect version schema in its DEBIAN/control which results in
```
$ sudo apt install libclang-rt-14-dev
...
The following packages will be REMOVED:
  clang-14 clang-tidy-14 clang-tools-14 libclang-common-14-dev
The following NEW packages will be installed:
  lib32gcc-s1 libclang-rt-14-dev
```
Also, while clang-15 depends on libclang-rt-15-dev, clang-14 merely recommends to install libclang-rt-14-dev which means that builds with sanitizers (or maybe any builds?) won't work by default.

**Comment by vient** [comment]
Integration tests are failing since yesterday https://llvm-jenkins.debian.net/job/llvm-toolchain-14-integration-test/

**Comment by j-stephan** [comment]
The missing libraries are part of `libclang-rt-14-dev`. However, this conflicts with `libclang-common-14-dev` which in turns leads to `clang-14` being uninstalled.

**Comment by NixFrog** [comment]
I'll try to bring some more information after digging a bit into the issue:
The package available on [the llvm focal repository](https://apt.llvm.org/focal/pool/main/l/llvm-toolchain-14/) for `libclang-rt-14-dev_14.0.6` has a version that stills includes the epoch in the package's version, but not in its dependencies (see `Version`, `Breaks` and `Replaces`):

```
dpkg -I libclang-rt-14-dev_14.0.6\~++20230108112125+f28c006a5895-1\~exp1\~20230108112200.170_amd64.deb
 new Debian package, version 2.0.
 size 3288368 bytes: control archive=3992 bytes.
    1056 bytes,    23 lines      control              
   13976 bytes,   131 lines      md5sums              
 Package: libclang-rt-14-dev
 Source: llvm-toolchain-14
 Version: 1:14.0.6~++20230108112125+f28c006a5895-1~exp1~20230108112200.170
 Architecture: amd64
 Maintainer: LLVM Packaging Team <pkg-llvm-team@lists.alioth.debian.org>
 Installed-Size: 43466
 Depends: lib32gcc-s1 (>= 3.0), lib32stdc++6 (>= 4.1.1), libc6 (>= 2.17), libc6-i386 (>= 2.17), libgcc-s1 (>= 3.0), libstdc++6 (>= 4.1.1)
 Breaks: libclang-common-14-dev (<< 1:14.0.6-10~exp4)
 Replaces: libclang-common-14-dev (<< 1:14.0.6-10~exp4)
```

The issue here being that `libclang-common-14-dev` also has an epoch in its version, which if I understand things correctly will not work with the specified `Breaks`

When looking at the [latest available package from debian](https://packages.debian.org/sid/libclang-rt-14-dev) the issue is fixed: there is no longer an epoch in the `Version` of the various packages & requirements:
```
dpkg -I libclang-rt-14-dev_14.0.6-10+b1_amd64.deb
 new Debian package, version 2.0.
 size 3274056 bytes: control archive=4000 bytes.
    1020 bytes,    23 lines      control              
   14069 bytes,   132 lines      md5sums              
 Package: libclang-rt-14-dev
 Source: llvm-toolchain-14 (1:14.0.6-10)
 Version: 1:14.0.6-10+b1
 Architecture: amd64
 Maintainer: LLVM Packaging Team <pkg-llvm-team@lists.alioth.debian.org>
 Installed-Size: 43008
 Depends: lib32gcc-s1 (>= 3.0), lib32stdc++6 (>= 4.1.1), libc6 (>= 2.34), libc6-i386 (>= 2.34), libgcc-s1 (>= 3.0), libstdc++6 (>= 4.1.1)
 Breaks: libclang-common-14-dev (<< 1:14.0.6-10~exp4)
 Replaces: libclang-common-14-dev (<< 1:14.0.6-10~exp4)
```

Note that the fixed package seems to be the result of fixes from the following [mail thread](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1027699) that relates to missing epochs in packages.

I don't have enough knowledge to dig deeper, but I hope that this may help any maintainer looking at this issue.

**Comment by j-stephan** [comment]
A possible workaround: The clang-15 packages seem fine. So if you can upgrade your test infrastructure to clang-15 this is a quick fix.

**Comment by xroche** [comment]
Workaround (courtesy of @Turanic):

```shell
apt-get update && apt download libclang-rt-14-dev && dpkg --force-all -i libclang-rt-14-dev*
```

**Comment by opajonk** [comment]
I can confirm the issue and the workaround. Thanks! Also looking forward to a real fix, of course ;-)

**Comment by peter-toft-greve** [comment]
Focal Fossa / Ubuntu 20.04 is clearly hit by this problem right now

**Comment by j-stephan** [comment]
> The clang-15 packages seem fine. 

Disregard that, they are broken now, too. I really hope someone from the packaging team picks this up soon.

**Comment by vient** [comment]
clang-15 looks fine to me, it now pulls `libclang-rt-15-dev` where sanitizers moved, it is not broken like `libclang-rt-14-dev` is.

**Comment by j-stephan** [comment]
Huh, maybe a glitch then. I'm quite certain that it failed in our CI with a similar error message but it is working now.

**Comment by peter-toft-greve** [comment]
@j-stephan do you mean that it works for you?
I have just now upgraded to lastest on Ubuntu 20.04 where I have an apt sources line:
deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main

and I have lost the needed libclang_rt.asan_static-x86_64.a needed for ASAN with clang-14

**Comment by j-stephan** [comment]
Sorry, that was a bit unclear. I was talking about the clang-15 packages in my previous comment. The clang-14 packages are still broken.

**Comment by peter-toft-greve** [comment]
For sake of understanding - were the new clang-14 packages released while having integration test failures in https://llvm-jenkins.debian.net/view/14/, or did those fails appear after release?

**Comment by opajonk** [comment]
Did anyone who could in theory fix this issue already see this? Or did it get lost in the 5k+ issues...

**Comment by peter-toft-greve** [comment]
I just rechecked - no new packages for Ubuntu 20.04 but https://llvm-jenkins.debian.net/job/llvm-toolchain-14-integration-test/ is happy but several others in https://llvm-jenkins.debian.net/ are red

**Comment by MMory** [comment]
Actually, the integration test https://llvm-jenkins.debian.net/job/llvm-toolchain-14-integration-test/ dates back to the date where the issue was not there yet and more recent runs disappeared.

**Comment by vient** [comment]
I suppose this is some standard mechanism in Jenkins where only last successful and unsuccessful builds are stored.

**Comment by peter-toft-greve** [comment]
@MMory yep - very odd :)

**Comment by peter-toft-greve** [comment]
Anyone who know more about progress for this one?

**Comment by nathanchance** [comment]
For what it's worth, this appears fixed for me and the source seems to agree with me.

https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/commit/a569b6dcf72b6f6f3a0ae7cfd7fed8e647ed9a65

I only tried on bullseye though.

**Comment by MMory** [comment]
These integration tests keep failing: https://llvm-jenkins.debian.net/view/14/

**Comment by opajonk** [comment]
Same here. We cannot simply switch to Clang 15 :crying_cat_face:

**Comment by peter-toft-greve** [comment]
If there is anything test-wise or alike we can contribute with - please share.

**Comment by vient** [comment]
Posted this to LLVM discord and it seems that it was fixed two weeks ago. Checked myself, `libclang-rt-14-dev` does not break anything on bionic anymore (but it is still optional to install).

**Comment by peter-toft-greve** [comment]
Seems to work fine after also installing libclang-rt-14-dev + latest of all others.
@opajonk - I guess you also would like to test now

**Comment by opajonk** [comment]
Many thanks for the hint! I will give it a spin first thing tomorrow ;-)

**Comment by opajonk** [comment]
Yep, I can confirm that the asan build works again when I install libclang-rt-14-dev via apt. The new package seems to be from 2023-01-31.

**Comment by vient** [comment]
So it seems to be fixed, great
