### ISSUE TITLE
lifetimebound attribute on std::move/std::forward

### ISSUE THREAD

**Issue by higher-performance** [llvm/llvm-project#59900]
It would be great if the `lifetimebound` attribute could be added to `std::move`/`std::forward` for compilers that support it.

**Comment by philnik777** [comment]
Could you give some details on what this attribute does? i.e. specific examples where it finds bugs. I guess that's it's purpose?

**Comment by alexander-shaposhnikov** [comment]
https://reviews.llvm.org/D141744

**Comment by zygoloid** [comment]
Perhaps this should be added to `as_const` and `addressof` too?

**Comment by philnik777** [comment]
> Perhaps this should be added to `as_const` and `addressof` too?

Does this add any additional value? The rvalue overloads of these functions are already deleted.

**Comment by philnik777** [comment]
> That sounds like a great idea. `const &` can bind to r-values as well. If there are any other similar functions (e.g., `std::forward_like`? `std::get`?) it might be worth adding the same for them too.

The rvalue overloads are specifically deleted. See https://en.cppreference.com/w/cpp/utility/as_const for example. I've already added the attribute to `std::forward_like` and `std::move_if_noexcept`.

**Comment by zygoloid** [comment]
> > Perhaps this should be added to `as_const` and `addressof` too?
> 
> Does this add any additional value? The rvalue overloads of these functions are already deleted.

The lvalue cases are still potentially problematic:

```
struct A {
  int n;
  int &get() [[clang::lifetimebound]] { return n; }
}
// Warns
int *p = &A().get();
// Does not warn without `[[lifetimebound]]`
int *q = std::addressof(A().get());
```

But Clang trunk automatically infers `[[lifetimebound]]` on `addressof` (as well as `move`, `forward`, etc.) these days, so I'm not sure there's any value in also adding it to libc++.
