### ISSUE TITLE
clang 16 doesn't add the "crc" feature when using -march=armv8.2-a while it should

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [llvm/llvm-project#59911]
Hi,

The following snippet:

```cpp
#include <arm_acle.h>

int f()
{
    return __crc32cd(1, 1);
}
```

compiled with `-march=armv8.2-a` doesn't compile anymore with clang 16. It was working with clang 15 (and a `crc32cx w0, w8, x9` instruction was emitted), but fails with clang 16:

```console
<source>:5:12: error: always_inline function '__crc32cd' requires target feature 'crc', but would be inlined into function 'f' that is compiled without support for 'crc'
    return __crc32cd(1, 1);
           ^
1 error generated.
Compiler returned: 1
```

Compiler explorer link: https://godbolt.org/z/K5saKnYWE

In practice, this make building the scudo library part of the compiler-rt runtime fail when trying to build with `-march=armv8.2-a`.

**Comment by davemgreen** [comment]
Thanks for the bug report - we need to be adding dependant features for architecture revisions.
There is a patch in https://reviews.llvm.org/D141411 for that.
