### ISSUE TITLE
asan: No such file or directory

### ISSUE THREAD

**Issue by sdarwin** [llvm/llvm-project#59919]
Hi,

We're running CI tests on C++ code using asan and ubsan.
A new problem just appeared in the last couple of days that was not seen before.
Installed clang-14 from llvm on Ubuntu 22.04.   The same scripts as before.   
New result:

```
/usr/bin/ld: cannot find /usr/lib/llvm-14/lib/clang/14.0.6/lib/linux/libclang_rt.asan_static-x86_64.a: No such file or directory
/usr/bin/ld: cannot find /usr/lib/llvm-14/lib/clang/14.0.6/lib/linux/libclang_rt.asan-x86_64.a: No such file or directory
/usr/bin/ld: cannot find /usr/lib/llvm-14/lib/clang/14.0.6/lib/linux/libclang_rt.asan_cxx-x86_64.a: No such file or directory
```

Has anything changed? Perhaps the apt package:
```
Get:1 https://apt.llvm.org/jammy llvm-toolchain-jammy-14/main amd64 libllvm14 amd64 1:14.0.6~++20230109103106+f28c006a5895-1~exp1~20230109223114.123 [24.0 MB]
```

**Comment by NixFrog** [comment]
For me this is a duplicate of https://github.com/llvm/llvm-project/issues/59903, the root cause is the same: there are packaging issues for `libclang-rt-14-dev`

**Comment by sdarwin** [comment]
@NixFrog that is very possible. Ok closing this as a dup of 59903.
