### ISSUE TITLE
[BOLT] hugify option doesn't work and no use of AnonHugePages.

### ISSUE THREAD

**Issue by PeterYang12** [llvm/llvm-project#59913]
According to options, hugify could put hot code on 2MB page(s) (hugify) at runtime automatically. I see it uses transparent hugepages.
But I didn't see any use of AnonHugePages after applying hugify.

My bolt commands with hugify are as follows:

```shell
llvm-bolt -hugify ./test_pie -o ./test_pie.hugify -data=./test_pie.fdata
```

My SUT is Ubuntu 22.04 and the kernel version is 5.15.0-56-generic.

**Comment by PeterYang12** [comment]
By the way, THP is enabled:
```
~$ cat /sys/kernel/mm/transparent_hugepage/enabled
always [madvise] never
```

**Comment by EugeneZelenko** [comment]
@PeterYang12: Could you please elaborate?

**Comment by PeterYang12** [comment]
> 

Sure, what can I do for you?
