### ISSUE TITLE
Miscompile with opt -passes=loop-reroll

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#59921]
LLVM commit: 41c6c75333c8
Reproduce with:
```shell
opt -passes=loop-reroll bbi-77532.ll -S -o -
```

In the input the loop is executed 23 rounds
```ll
%i.021 = phi i16 [ 4, %entry ], [ %add45, %while.body ]
[...]
%add45 = add nsw i16 %i.021, 4
%sub = sub nsw i16 97, %add45
%cmp = icmp sge i16 %sub, 4
br i1 %cmp, label %while.body, label %while.end
```
and as seen above each round `%add45` is incremented by 4:
```ll
%add45 = add nsw i16 %i.021, 4
```
After the loop `%add45` is returned from the function:
```ll
%i.0.lcssa = phi i16 [ %add45, %while.body ]
ret i16 %i.0.lcssa
```

After loop-reroll, the loop executes 92 rounds
```ll
%indvar = phi i16 [ %indvar.next, %while.body ], [ 0, %entry ]
[...]
%indvar.next = add i16 %indvar, 1
%exitcond = icmp eq i16 %indvar, 91
br i1 %exitcond, label %while.end, label %while.body
```
but `%add45` is still incremented by 4 each round
```ll
%add45 = add nsw i16 %i.021, 4
```
and it's still returned after the loop
```ll
%i.0.lcssa = phi i16 [ %add45, %while.body ]
ret i16 %i.0.lcssa
```
So the return value from the function is changed by the loop-reroll pass.
[bbi-77532.ll.gz](https://github.com/llvm/llvm-project/files/10389587/bbi-77532.ll.gz)

**Comment by sun-jacobi** [comment]
@EugeneZelenko @mikaelholmen  Hi, can I work on this issue?

**Comment by mikaelholmen** [comment]
@sun-jacobi : I don't mind, but I don't know if it makes sense either.

There are several tickets about loop-reroll miscompiles and e.g.
 https://github.com/llvm/llvm-project/issues/68182
was closed since it was only reproducible with
 "the unsupported / broken loop-reroll pass"

I don't know what the plan is for loop-reroll.

**Comment by fhahn** [comment]
FWIW see https://reviews.llvm.org/D150684 for a summary of the issues and a proposal to remove the pass (temporarily)

**Comment by nikic** [comment]
The LoopReroll pass has been removed by https://github.com/llvm/llvm-project/pull/80972.
