### ISSUE TITLE
[OpenMP][5.1] `parallel masked` is ignored

### ISSUE THREAD

**Issue by jdoerfert** [llvm/llvm-project#59939]
We don't error out but simply ignore the region, kinda bad:

https://godbolt.org/z/eb7a9oTEo
```c
void foo();

void masked() {
    #pragma omp parallel masked
    {
        foo();
    }
}
```
results in
```ll
define dso_local void @masked() #0 !dbg !11 {
  ret void, !dbg !16
}
```

See also: https://github.com/SOLLVE/sollve_vv/blob/master/tests/5.1/runtime_calls/test_teams_region_routines.c

**Comment by shiltian** [comment]
It's not ignored I think. It is a bug as we already have the `masked` support.

**Comment by shiltian** [comment]
It's not ignored. https://godbolt.org/z/ncbdar4na If assertion is enabled, it will crash. I think what we should do here is to error out.

**Comment by randreshg** [comment]
I couldn't assign the bug to myself because I didn't have the necessary permissions. However, here is the Phabricator patch:
https://reviews.llvm.org/D143527

**Comment by jdoerfert** [comment]
@randreshg any progress implementing this feature (not implementing an error message)?

**Comment by randreshg** [comment]
@jdoerfert it will be done soon. I'll update the patch by the end of this week
