### ISSUE TITLE
__builtin_cpu_supports doesn't understand x86-64 micro-architecture levels

### ISSUE THREAD

**Issue by chfast** [llvm/llvm-project#59961]
This does not work: `__builtin_cpu_supports("x86-64-v2")`.

**Comment by MaskRay** [comment]
Patch: https://reviews.llvm.org/D158811

**Comment by ecatmur** [comment]
This PR appears to imply that `[[gnu::target("x86-64-v2")]]` should work: https://github.com/llvm/llvm-project/blob/27da15381cbe2ac6fd1319f6409dbbab9a857b7b/clang/lib/CodeGen/CodeGenFunction.cpp#L2686-L2689

However this is not tested, and current trunk does not accept:
```
<source>:3:36: error: function multiversioning doesn't support architecture 'x86-64'
    3 | [[gnu::target("arch=x86-64")]] int f() { return 2; }
      |                                    ^
```

This appears to be rejected at https://github.com/llvm/llvm-project/blob/966d564e43e650b9c34f9c67829d3947f52add91/clang/lib/Sema/SemaDecl.cpp#L11066-L11068 Should I report a new issue?
