### ISSUE TITLE
[nonlocal DSE] Loop is not eliminated

### ISSUE THREAD

**Issue by asl** [llvm/llvm-project#5997]
|  |  |
| --- | --- |
| Bugzilla Link | [5625](https://llvm.org/bz5625) |
| Version | trunk |
| OS | Linux |
| CC | @lattner,@hfinkel,@sunfishcode |

## Extended Description 
Consider the following simple C code:

```
int* a;
int b;

void foo(unsigned N, int c) {
 unsigned i;

 a = &b;

 for (i=0; i< N; ++i) {
   *a = c;
   a = &b;
 }
}
```

Obviously the assignments in the loop are redundant. running llvm-gcc -O3 does not eliminate the loop, however "llvm-gcc t.c -S -o - -emit-llvm -O3 | opt -std-compile-opts -S" does. 

Chris suggested there might be a pass ordering problem

**Comment by gwelymernans** [comment]
Still an issue now too. :-)

**Comment by nikic** [comment]
Godbolt: https://c.godbolt.org/z/v74TsMKWo

As far as I can tell, this is already optimized as well as it can be. There is one store to `a` and one conditional (but non-loop) store to `b`.

**Comment by fhahn** [comment]
> As far as I can tell, this is already optimized as well as it can be. There is one store to a and one conditional (but non-loop) store to b.

Yes, it looks like the loop is now removed and Clang codegen is similar to GCC: https://c.godbolt.org/z/fr6WrYva1

I think it's time to close this one, but please feel free to re-open with more details in case there's anything left to do.
