### ISSUE TITLE
wrong type for `auto&` parameter when deducing a class template partial specialization

### ISSUE THREAD

**Issue by zygoloid** [llvm/llvm-project#59981]
Clang rejects this valid code:

```c++
template<auto &X, int> struct A;
template<auto &X> struct A<X, 0> {};

const int n = 0;
A<n, 0> a;
```

... apparently because it thinks that the expression `X` in `struct A<X, 0>` is an lvalue of type `int`, not an lvalue of type `const int`, when considering partial specializations of `A<n, 0>`.

**Comment by cor3ntin** [comment]
Fixed in Clang 19
