### ISSUE TITLE
[packaging] Clang 15 with AddressSanitizer unusable since 2023-01-13 (with at least Ubuntu focal/20.04)

### ISSUE THREAD

**Issue by hartwork** [llvm/llvm-project#60008]
Hi!

Maybe it's because today is Friday the 13th but Clang 15 of https://apt.llvm.org/ started being unusable today for Ubuntu focal/20.04 with `-fsanitize=address`, failing to link even tiniest programs with this link error:
```console
/usr/bin/ld: cannot find /usr/lib/llvm-15/lib/clang/15.0.7/lib/linux/libclang_rt.asan_static-x86_64.a: No such file or directory
/usr/bin/ld: cannot find /usr/lib/llvm-15/lib/clang/15.0.7/lib/linux/libclang_rt.asan-x86_64.a: No such file or directory
```
The full log can be seen at https://github.com/libexpat/libexpat/actions/runs/3907902403/jobs/6687221899#step:6:108 and I'm attaching a copy of the full log here: [clang-15-error.txt](https://github.com/llvm/llvm-project/files/10412860/clang-15-error.txt).

Any chance this can be fixed? I'm expecting this affects a lot more projects than just libexpat.

Let me use the occasion to thank you for all the work you do on Clang and LLVM: in particular Clang's sanitizers have been invaluable again and again and to have clang-format is also great. Thank you!

Best, Sebastian

**Comment by j-stephan** [comment]
See #59903. The sanitizers for clang-15 should work by installing `libclang-rt-15-dev`.

**Comment by hartwork** [comment]
@j-stephan thanks for the hint on `libclang-rt-15-dev`!

**Comment by MarcoFalke** [comment]
Anything left to do here?

**Comment by calvin2021y** [comment]
The only x86 linux llvm15 package is https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.6/clang+llvm-15.0.6-x86_64-linux-gnu-ubuntu-18.04.tar.xz,  not work because this problem.

Hope release a fixed downloadable x86 package for llvm15.

**Comment by sylvestre** [comment]
yeah, i split them

**Comment by hyunjungg** [comment]
Can you tell me how you resolved it?

**Comment by hartwork** [comment]
> Can you tell me how you resolved it?

@hyunjungg did you see https://github.com/uriparser/uriparser/pull/160 ?

**Comment by hyunjungg** [comment]
@hartwork 

"I am using clang-15, and I tried to install libclang-rt-15-dev using the apt command, but I couldn't download it because it said it was a non-existent package name.

I found another cause.

It's that ld cannot find the lib path of clang-15. It is pointing to a different path. To solve this, I tried to copy using the command below, but the copy was not successful. I am still trying to solve this problem.

`sudo cp -R /usr/lib/clang/15.0.7/lib /usr/local/lib/clang/15.0.0/"
`


Thank you for answering. 😭😭😭

**Comment by hartwork** [comment]
> "I am using clang-15, and I tried to install libclang-rt-15-dev using the apt command, but I couldn't download it because it said it was a non-existent package name.

@hyunjungg you're not using the right (or not the LLVM) repository then? This is the best way I know to activate the right LLVM one for your distro (or release):
https://github.com/tenox7/ttyplot/blob/07ce2f904f0a24ab46c0af170fa65cbb3bfe62bb/.github/workflows/linux_and_macos.yml#L51-L57

> I found another cause.
> 
> It's that ld cannot find the lib path of clang-15. It is pointing to a different path. To solve this, I tried to copy using the command below, but the copy was not successful. I am still trying to solve this problem.
> 
> `sudo cp -R /usr/lib/clang/15.0.7/lib /usr/local/lib/clang/15.0.0/" `

`/usr/local` is never owned by a distro package or the package is misbehaving, you are mixing things that were not meant to be used together, quite probably?

This repository here is about the offical LLVM Debian/Ubuntu repositories at https://apt.llvm.org/ with the latest versions that are not yet in mainstream Debian/Ubuntu (and I'm a guest here). If that's what you want to use, there should be no `/usr/local` involved. And you may want 17 over 15 then, because every release the compiler gets stricter and you probably want to see these errors early. Just my 2 cents.
