### ISSUE TITLE
RISCV: suboptimal trucation of int to short

### ISSUE THREAD

**Issue by hiraditya** [llvm/llvm-project#60014]
test case:

``` c
short foo(short i, short j) {
    return i + j;
}
```

$ rv64gc-clang -O3 -S -o -

```asm
foo(short, short):                               # @foo(short, short)
        add     a0, a0, a1
        slli    a0, a0, 48
        srai    a0, a0, 48
        ret
```

link: https://godbolt.org/z/o5jYEzeT9

**Comment by jrtc27** [comment]
In what way is this suboptimal?

**Comment by topperc** [comment]
I suppose you don't need to sign extend since signed wrap is poison. Was that where you going with this @hiraditya

**Comment by hiraditya** [comment]
I was wondering if it is possible to convert int to short in lesser instructions?

**Comment by topperc** [comment]
> I was wondering if it is possible to convert int to short in lesser instructions?

-march=rv64i_zbb

**Comment by jrtc27** [comment]
This isn't signed overflow, the arithmetic is done on int not short and then truncated, which gives an implementation-defined result (or signal).

**Comment by hiraditya** [comment]
can't we just add these as ints and return the result without truncating?

The caller should typecast to appropriate type no?

Just like arm: https://godbolt.org/z/8xTM38G6d

**Comment by jrtc27** [comment]
No. Read the psABI.

**Comment by topperc** [comment]
> This isn't signed overflow, the arithmetic is done on int not short and then truncated, which gives an implementation-defined result (or signal).

Oops. You're right the promotion happens before signed wrap applies.

**Comment by jrtc27** [comment]
> > This isn't signed overflow, the arithmetic is done on int not short and then truncated, which gives an implementation-defined result (or signal).
> 
> Oops. You're right the promotion happens before signed wrap applies.

Yeah. In fact we've lost even the i32 nsw part by this point as InstCombine turns the `trunc (add nsw i32) to i16` into `add i16`.

**Comment by jrtc27** [comment]
No missed optimisation here.

**Comment by hiraditya** [comment]
Thanks for clarifying!
