### ISSUE TITLE
need stack slot coloring of allocas

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#6001]
|  |  |
| --- | --- |
| Bugzilla Link | [5629](https://llvm.org/bz5629) |
| Version | trunk |
| OS | All |
| Attachments | [Output of clang -O0 -S test.c at r89911](https://user-images.githubusercontent.com/60944935/143740308-2f646c19-dfed-4f4a-b923-63e5a8c08f65.gz), [Output of clang -O3 -S test.c at r89911](https://user-images.githubusercontent.com/60944935/143740309-ae0c6a6c-c89d-40a3-9b4c-a2627020d5f8.gz), [Output of gcc-4.4.1 -O0 -S test.c](https://user-images.githubusercontent.com/60944935/143740310-b77e06f5-ff27-40c3-84e2-976b056c5c7a.gz), [Output of gcc-4.4.1 -O3 -S test.c](https://user-images.githubusercontent.com/60944935/143740311-a6de432e-87af-4e7c-b538-7aff0f020275.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 

$ cat test.c
typedef struct BigStruct {
  char member[10000];
} BigStruct;

extern void use(BigStruct*);

void foo() {
  { BigStruct s; use(&s); }
  { BigStruct s; use(&s); }
}

With clang -O0 and -O3, this function uses 20000 bytes of stack space, even though only one of the objects is alive at any given time. With gcc-4.4.1 -O0 and -O3, it only uses 10000 bytes (although I've seen C++ functions get gcc to fail to reuse stack space too).

This can be a significant problem in programs with small stacks, especially in C++ where we can have lots of invisible temporary objects. Because the small stack problem exists in -O0 builds too, I don't think clang can get away with only reusing stack space at -O>0.

**Comment by arsenm** [comment]
Stack slot coloring does exist with the lifetime markers. The given example uses the 10k stack:
```
	subq	$10008, %rsp                    # imm = 0x2718
	.cfi_def_cfa_offset 10016
	leaq	8(%rsp), %rdi
	callq	use@PLT
	leaq	8(%rsp), %rdi
	callq	use@PLT
	addq	$10008, %rsp                    # imm = 0x2718
	.cfi_def_cfa_offset 8
	retq

```
