### ISSUE TITLE
The C function `ecvt(...)` outputs a string one digit longer than expected

### ISSUE THREAD

**Issue by tim-lyon** [llvm/llvm-project#60010]
Given a floating point number consisting of repeating digit `9`, the function `ecvt` incorrectly returns a string of length `n + 1` where `n` is the expected length.

Minimal example:
```C++
#include <iostream>
#include <stdlib.h>

int main() {
  int dec, sign;
  std::cout << ecvt(999, 2, &dec, &sign);
}
```

- Expected output: `10` (two digits, as per second argument)
- Clang (trunk): `100` (three digits)
- gcc: `100` (same issue)
- MSVC: `10` (as expected)

Example in compiler explorer
https://godbolt.org/z/zYzfT7EP6

**Comment by efriedma-quic** [comment]
LLVM doesn't know anything about the semantics of "ecvt"; you're just getting whatever behavior glibc implements.

See https://sourceware.org/glibc/wiki/FilingBugs for instructions on how to report a glibc bug.

**Comment by ftschindler** [comment]
Could be that you're seeing https://sourceware.org/bugzilla/show_bug.cgi?id=29556

**Comment by ftschindler** [comment]
> Could be that you're seeing https://sourceware.org/bugzilla/show_bug.cgi?id=29556

Btw., thx for pointing out the relation to `glibc`, @efriedma-quic!
