### ISSUE TITLE
automatically add `lifetimebound` attribute to `move` and `forward` builtins

### ISSUE THREAD

**Issue by zygoloid** [llvm/llvm-project#60020]
We have a family of builtin functions in namespace `std` that Clang recognizes: `move`, `forward`, `move_if_noexcept`, `addressof`, `as_const`.

Under #59900, libc++ added `[[clang::lifetimebound]]` to these, but that does nothing for libstdc++. (Also, it missed `as_const` and `addressof`.) We should add this attribute automatically to functions that we recognize as being these builtins.

We should also extend Clang's builtin recognition to handle the new function `std::forward_like`, which has the same behavior as the others.

**Comment by AaronBallman** [comment]
This was implemented in 31b0be4eba9e8e9244799f0ebcb18175faff69ab.
