### ISSUE TITLE
Dead links on https://clang.llvm.org/extra/clang-tidy/

### ISSUE THREAD

**Issue by rillig** [llvm/llvm-project#60023]
https://clang.llvm.org/extra/clang-tidy/#suppressing-undesired-diagnostics

In that section, the links to the individual checks, such as [bugprone-use-after-move](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-use-after-move.html), lead to a 404.

**Comment by s-pratik** [comment]
Hi, I am new to open source can anyone help me with how can I start to contribute here

**Comment by s-pratik** [comment]
Hi, I am very new to open source can you help me with how can I start contributing here

**Comment by AaronBallman** [comment]
> Hi, I am new to open source can anyone help me with how can I start to contribute here

The broken documentation lives at: https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/docs/clang-tidy/index.rst?plain=1#L302 It looks like the RST (https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html) has the links pointing to targets that no longer exist.

Once you have a fix worked out, we do all of our code review via Phabricator, more details can be found at: https://llvm.org/docs/Phabricator.html You can submit a patch via https://reviews.llvm.org and feel free to assign me as a code reviewer for the patch.

**Comment by s-pratik** [comment]
okay i think i understood the issue just i want to know what to do with the dead links do i have to remove them or replace them with other links

**Comment by AaronBallman** [comment]
I believe those checks still exist but the documentation moved to a new location. Assuming that's the case, you should replace the links with new ones.

**Comment by s-pratik** [comment]
okay i got it .. i found out the link of bugprone-use-after-move ( https://clang.llvm.org/extra/clang-tidy/checks/bugprone/use-after-move.html ) can you check is it the correct one so i can replace this and other dead links also..

**Comment by s-pratik** [comment]
and also can you assign me this issue

**Comment by njames93** [comment]
Yes these are the correct links. They now have the form `<module>/<check-name>.html`

**Comment by s-pratik** [comment]
Okay I have done all the necessary changes but i am having hard time to install arcanist on windows for that reason I can't able to create review request. Can anyone help me with the detailed guide how can I do that . Thanks!

**Comment by AaronBallman** [comment]
I've never used arcanist myself, so I'm not of much help there. FWIW, I use the web interface directly. I generate a patch with `git diff -U9999 > whatever.patch` (or `git diff --cached -U9999 > whatever.patch` if I've already staged for commit), then I go to https://reviews.llvm.org/differential/, click on `Create Diff` (it's a button in the upper right corner of the page), select `whatever.patch` and click `Create Diff`, then I click `Continue` (to create a new diff), give it a title, summary, select some reviewers, etc. You can set `rG LLVM Github Monorepo` as the `Repository` and add `cfe-commits` as a `Subscriber`. Then click `Create New Revision` to post the patch for review.

**Comment by s-pratik** [comment]
Thanks for the detailed guide @AaronBallman. I have done all the steps you mentioned and chosen you as a reviewer and submitted the patch. after that what do I have to do?

**Comment by AaronBallman** [comment]
The patch made it to the mailing lists (https://reviews.llvm.org/D142377), so the next steps are on the community side (we need to review it and accept the patch once it's ready). I'll try to review it for you today or tomorrow when I get the chance, thank you!
