### ISSUE TITLE
"Do not know how to split the result of this operator" on x86-64 with cryptographic instructions

### ISSUE THREAD

**Issue by newpavlov** [llvm/llvm-project#60039]
In [RustCrypto](https://github.com/RustCrypto) we got several issues from users who try to compile some of our crates which support hardware acceleration on "bare" targets (e.g. `x86_64-unknown-uefi` and `x86_64-unknown-none`). The said crates by default use AES-NI, SHA-NI, and CLMUL instructions after runtime CPUID-based check. For some reason LLVM fails to compile such code with the aforementioned error. For now users can work around this issue by disabling the hardware acceleration support using configuration flags, but it's far from ideal.

Here is a godbolt link with a (bit noisy) sample LLVM IR and resulting error: https://llvm.godbolt.org/z/MGhsG6noG

**Comment by topperc** [comment]
The target features have disabled sse and enabled soft floating point

`"target-features"="-mmx,-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2,-3dnow,-3dnowa,-avx,-avx2,+soft-float,+sha"`

**Comment by newpavlov** [comment]
@topperc 
So basically, SIMD registers are not available on "bare" targets, thus we can not use hardware acceleration in principle, correct?

What would be your recommendation? Should we disable hardware acceleration support for such targets or can we somehow enable necessary target features locally for a function?
