### ISSUE TITLE
Miscompilation: Illegal instruction

### ISSUE THREAD

**Issue by corwinn** [llvm/llvm-project#60046]
Code: https://gist.github.com/corwinn/726e0c7e61482f7be1494e5ec634dabe
Compile: clang++ -O0 clang_issue_a.cpp -o clang_issue_a
Compile: clang++ -march=core2 -mtune=core2 -O0  clang_issue_a.cpp -o clang_issue_a
Platform: X86_64-pc-linux-musl
March: core2
LLVM, clang, compiler-rt, libunwind, libc++, lld : 14.0.6
LLDB: ->  0x555555555da8 <+88>: ud2
No GCC.
Reproducible with: 12.0.1, and 10.0.1
Workarounds: Using -O1, -O2, -O3, or -Os "resolves" the issue.

**Comment by fhahn** [comment]
Input program is

```
int no_return_proc() {}
int main()
{
    no_return_proc();
}
```

The issue here is that the code exits a function that returns an `int` via a path that is missing a return statement. This is undefined behavior and not a compiler bug: https://timsong-cpp.github.io/cppwp/n4140/stmt.return#2
