### ISSUE TITLE
.gdb-index section generated by lld is many times smaller than gdb output.

### ISSUE THREAD

**Issue by pawelsopensource** [llvm/llvm-project#60049]
attached simple c++ example generates different size of the .gdb_index section.

$ llvm-readelf -SW example-via-lld | grep gdb_index
  [35] .gdb_index        PROGBITS        0000000000000000 020108 **002a78** 00      0   0  1
$ llvm-readelf -SW example-via-gdb | grep gdb_index
  [38] .gdb_index        PROGBITS        0000000000000000 024f05 **00aed7** 00      0   0  1

```
#include <iostream>
#include <string>
#include <vector>
int main()
{
    std::vector< std::string > v{ "foo", "bar", "zoo" };
    for ( auto const& s : v )
        std::cout << s << std::endl;
    return 0;
}
```

```
TARGET=x86_64-unknown-linux-gnu
TOOLCHAIN=${HOME}/src/toolchain/deploy
export PATH=${TOOLCHAIN}/bin:${PATH}
export LD_LIBRARY_PATH=${TOOLCHAIN}/lib/${TARGET}:${LD_LIBRARY_PATH}

CXXFLAGS="-target ${TARGET} -Wall -ggdb -g2 -gdwarf-5 -stdlib=libc++"
LDFLAGS="-target ${TARGET} -fuse-ld=lld -stdlib=libc++ -Wl,-rpath,${TOOLCHAIN}/lib/${TARGET}"

clang++ ${CXXFLAGS} example.cpp -c

clang++ ${LDFLAGS} example.o -o example-via-lld -Wl,--gdb-index

clang++ ${LDFLAGS} example.o -o example-via-gdb
rm -rf tmp && mkdir tmp
gdb -batch -ex="save gdb-index tmp" -ex=quit example-via-gdb
llvm-objcopy --add-section .gdb_index=tmp/example-via-gdb.gdb-index example-via-gdb example-via-gdb

llvm-readelf -SW example-via-lld | grep gdb_index
llvm-readelf -SW example-via-gdb | grep gdb_index
```

**Comment by MaskRay** [comment]
https://maskray.me/blog/2022-10-30-distribution-of-debug-information

`-ggnu-pubnames` implied by `-gsplit-dwarf` generates `.debug_gnu_pubnames` and `.debug_gnu_pubtypes` sections.
(`-ggnu-pubnames` can be used without `-gsplit-dwarf`, but it is uncommon.)

`--gdb-index` supported by some ELF linkers (gold, ld.lld, mold) causes the linker to read `.debug_gnu_pubnames`, `.debug_gnu_pubtypes`, and other debug sections (`.debug_info`, `.debug_addr`, `.debug_rnglists`, etc) to construct `.gdb_index`.
`.debug_gnu_pubnames` and `.debug_gnu_pubtypes` are then discarded.

When gdb loads a symbol file, it constructs an internal symbol table. [`.gdb_index`](https://sourceware.org/gdb/onlinedocs/gdb/Index-Files.html) can improve startup time.
With split DWARF, the `.dwo` files as referenced by the executable or shared object will be fully parsed on demand.

**Comment by dwblaikie** [comment]
Perhaps put a different way: I believe lld doesn't support building indexes from raw .debug_info, but gold and gdb do support this. If you want an equivalent gdb index from lld, you need to compile the objects with `-ggnu-pubnames` (which is implied by `-gsplit-dwarf`, if you are already using that)
