### ISSUE TITLE
[llvm][mlir]Request for adding dlfcn relative function to llvm intrinsic function.

### ISSUE THREAD

**Issue by 95833** [llvm/llvm-project#60059]
I want to use runtime dynamic load library in my language and i only know two relative  library : dlfcn.h and llvm dynamicLibrary.h. but the former is only UNIX and the latter is a c++ class. 

 i wan't expose the platform dependent code to IR. so, whether or not they can be added to llvm intrinsic function? Or how should i do use a c++ class in LLVMIR ?

**Comment by joker-eph** [comment]
Is this discussed here https://discourse.llvm.org/t/request-for-add-a-dynamiclibrary-dialect/67707/9 ? 

We can re-open if I am misunderstanding the request here.
