### ISSUE TITLE
[C++14] Enable sized deallocation by default

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#60061]
Sized deallocation is a C++14 feature and it was disabled in clang due to potential ABI breaking (https://reviews.llvm.org/D8467). There was guys trying to enable it by default 2 years ago (https://reviews.llvm.org/D112921) but the work suspended later.

**Comment by Romain-Geissler-1A** [comment]
Hi @wangpc-pp,

Do you have any status on enabling this by default which you last tried this summer (https://reviews.llvm.org/D112921) ?

**Comment by shafik** [comment]
This feels like a duplicate of: https://github.com/llvm/llvm-project/issues/56505

We should try and keep one main bug and updates and queries should go to that.

**Comment by wangpc-pp** [comment]
> Hi @wangpc-pp,
> 
> Do you have any status on enabling this by default which you last tried this summer (https://reviews.llvm.org/D112921) ?

There were some buildbot failures (Windows, AMDGPU) and I don't have such environments, so I suspended the progress.
I'm glad to have another try, but I need some help to fix these failures.

**Comment by vitalybuka** [comment]
Reverted with #90299
