### ISSUE TITLE
[C++20][Modules] deleted definitions should be allowed in header units

### ISSUE THREAD

**Issue by kaimfrai** [llvm/llvm-project#60079]
Since non-inline external definitions in header units were disallowed in [commit/335668b](https://github.com/llvm/llvm-project/commit/335668b116439d13c7555616e126acdc608ce59e), using standard header units has become impractical.
In particular, the example given at https://clang.llvm.org/docs/StandardCPlusPlusModules.html#header-units
```shell
clang++ -std=c++20 -xc++-system-header --precompile iostream -o iostream.pcm
```
no longer compiles with current Clang 16 (tried libc++ and libstdc++) while it did work before.

Errors include but are not limited to:
### libstdc++
```console
include/c++/12/new:206:8: error: non-inline external definitions are not permitted in C++ header units
  void launder(volatile void*) = delete;
```
```console
include/c++/12/type_traits:2125:27: error: non-inline external definitions are not permitted in C++ header units
      static const size_t _S_alignment = 0;
```

### libc++
```console
 include/c++/v1/__type_traits/aligned_union.h:29:25: error: non-inline external definitions are not permitted in C++ header units
    static const size_t value = _I0;
```
```console
include/c++/v1/__functional/reference_wrapper.h:100:27: error: non-inline external definitions are not permitted in C++ header units
template <class _Tp> void ref(const _Tp&&) = delete;
```

Unfortunately, this issue isn't limited to libstdc++ and libc++. Not only do other headers often include standard headers, but it's entirely resonable to have = delete; in header files. They are therefore also unusable as header units. Transitioning from headers to header units is thus limited to a small subset of headers, while Clang 15 allowed many more. While I think it's the correct default to error out in these cases, I would appreciate an explicit flag that skips over this rule, at least until P1502R1 (Standard library Header Units) or P2465R3 (std module) are implemented. For example:

```shell
clang++ -std=c++20 -xc++-system-header -fallow-non-inline-external-definitions-in-header-units --precompile iostream -o iostream.pcm
```

Without such a flag I would find it very hard to make use of standard header units as they are implemented right now.

**Comment by dwblaikie** [comment]
Might be simpler to consider deleted definitions to be implicitly inline - it's more like how it works in practice.

**Comment by dwblaikie** [comment]
I think it's a pretty simple either implementation or spec bug/omission.

I doubt anyone intended to disallow deleted definitions in header units.

**Comment by ChuanqiXu9** [comment]
> Might be simpler to consider deleted definitions to be implicitly inline - it's more like how it works in practice.

Yeah, it sounds good.

> I think it's a pretty simple either implementation or spec bug/omission.

According to @iains , wg21 wants to remove such rules in future.

For this issue report, I feel it makes sense to skip the rule. Although LLVM16 is going to be branched, we don't need to be hurry  since it should be possible to backport the patch since this is a (severe) regression bug. 

---

(This section is not related to the issue report),

Out of curiosity, I want to ask how do you use header units? What is the build system you're using? Currently, wg21 is still discussing how to support header units. It looks like cmake wouldn't support header units until they get a conclusion. I want to say that I feel the header units is not well tested and used a lot in practice now. So I am curious about your practice and using experience for header units.

**Comment by ChuanqiXu9** [comment]
Sent https://reviews.llvm.org/D141894

**Comment by iains** [comment]
well, we anticipated that this could cause some code to flag an error.

**For clarification: there are some WG21 members who are saying the think this rule should be removed.   I am not aware of any paper that actually proposes its removal (so that as far as I know, the rule is the same in C++23).**

I think that the 
`include/c++/12/type_traits:2125:27: error: non-inline external definitions are not permitted in C++ header units
      static const size_t _S_alignment = 0;`

 - cases look like a bug, tu-local declarations are allowed. (https://eel.is/c++draft/module#import-6
)  I guess the `const` has somehow tripped up the logic.
 
 - perhaps we should seek clarification from core on whether this was intended to apply to deleted functions.

Otherwise - from an engineering perspective

 If a header contains a non-inline external definition, then it can only be used once (since multiple imports are an ODR violation), therefore actually it probably makes little sense to make it into a header unit, that is just extra build-time work -  (it might as well be included textually in the single place it is used).

**Comment by iains** [comment]
The issue with the deleted function is that it is a definition - if it was a declaration, the rule would not fire.

I suppose that we could implement @dwblaikie 's suggestion to make them implicitly inline.  I wonder if there are other similar cases that will trip us up.

I will file a question with core now - obviously, clang can elect to make a dialect as @ChuanqiXu9 has proposed in https://reviews.llvm.org/D141894 but let's see what answer we get first?

**Comment by ChuanqiXu9** [comment]
> well, we anticipated that this could cause some code to flag an error.
> 
> **For clarification: there are some WG21 members who are saying the think this rule should be removed. I am not aware of any paper that actually proposes its removal (so that as far as I know, the rule is the same in C++23).**

Thanks for the clarification. That's what I understood. Maybe I didn't tell things clearly.

> 
> I think that the `include/c++/12/type_traits:2125:27: error: non-inline external definitions are not permitted in C++ header units static const size_t _S_alignment = 0;`
> 
> * cases look like a bug, tu-local declarations are allowed. (https://eel.is/c++draft/module#import-6
>   )  I guess the `const` has somehow tripped up the logic.

I think the behavior is correct. Since the name '_S_alignment' has not internal linkage. According to http://eel.is/c++draft/basic.link, `_S_alignment` doesn't live in namespace scope so [basic.link]p3 doesn't apply for it. And `_S_alignment ` lives in `aligned_union` and `aligned_union` has external linkage, so `_S_alignment ` has external linkage according to [basic.link]p4. So I think the behavior here is fine. 

> * perhaps we should seek clarification from core on whether this was intended to apply to deleted functions.
> 
> Otherwise - from an engineering perspective
> 
> If a header contains a non-inline external definition, then it can only be used once (since multiple imports are an ODR violation), therefore actually it probably makes little sense to make it into a header unit, that is just extra build-time work - (it might as well be included textually in the single place it is used).

Year, since this is the defect of the language spec. It would be better to ask this in core. But clang16 is going to be branched. Even if we can backport patches before the formal release, the time is really limited. I really feel upset that we can't compile a hello example for header units. So I think we should accept the patch  and ask questions in wg21. Otherwise, we have to mark header units is not usable in clang16.

**Comment by ChuanqiXu9** [comment]
> The issue with the deleted function is that it is a definition - if it was a declaration, the rule would not fire.
> 
> I suppose that we could implement @dwblaikie 's suggestion to make them implicitly inline. I wonder if there are other similar cases that will trip us up.

Since Clang16 is going to be branched. I don't think we should perform the action now. It has wider impact.

> 
> I will file a question with core now - obviously, clang can elect to make a dialect as @ChuanqiXu9 has proposed in https://reviews.llvm.org/D141894 but let's see what answer we get first?

Yeah, it should be fine to wait for few days.

**Comment by ChuanqiXu9** [comment]
> 

Yeah, it looks like we did some bad for the deleted function in header units or modules. Since clang have already handle the case in `Sema::SetDeclDeleted()`.

**Comment by ChuanqiXu9** [comment]
@iains After I took a quick look, I found the reasons.

https://github.com/llvm/llvm-project/blob/951cf656b2faaf6fc0baa867293c0cb0ab131951/clang/lib/Parse/Parser.cpp#L1392-L1417

We diagnose in the call of the  line 1392. But the deleted function is marked as implicit inline at line 1414. So here is the problem. We should find other place to diagnose this.

**Comment by iains** [comment]
> Yeah, it looks like we did some bad for the deleted function in header units or modules. Since clang have already handle the case in `Sema::SetDeclDeleted()`.

Well, in the commit referenced - we are checking isInlined() so that should be set for setImplicitlyInline(..) [it obviously already works for friend cases] so some debugging is needed.

**Comment by ChuanqiXu9** [comment]
The form `static const size_t _S_alignment = 0;` should be fine too since the spec says it is only a declaration even if it has the initializer.

**Comment by ChuanqiXu9** [comment]
So it looks like we can fix things properly.

**Comment by iains** [comment]
yeah, I have a patch in test for the deleted/defaulted functions.

**Comment by iains** [comment]
https://reviews.llvm.org/D141908

**Comment by kaimfrai** [comment]
> (This section is not related to the issue report),
> 
> Out of curiosity, I want to ask how do you use header units? What is the build system you're using? Currently, wg21 is still discussing how to support header units. It looks like cmake wouldn't support header units until they get a conclusion. I want to say that I feel the header units is not well tested and used a lot in practice now. So I am curious about your practice and using experience for header units.

I am using CMake, however I have some custom functions set up that make modules and header units usable for Clang with custom commands. While by no means perfect, complete, or even well portable to other proejcts, it's sufficient to experiment until official support lands. 
There are 3 ways I use header units right now: 

The first is a header that includes all of the standard library. The reason for this are some functions (-objects) marked static, which are defined in one header and used in another. With both being header units, the function (-object) becomes unavailable due to internal linkage, so I put all of the standard library into one header unit for now. That header unit is re-exported by a named module Std, which I import throughout one project until import std; becomes available.

The second is precompiling third party headers (such as boost). Even though they are only used at one place each, I found this useful to separate the build times for measuring how long a specific module takes to compile if all dependencies are already precompiled.

The third is for headers that contain (almost) only macros. It's true however that there would be no need for a header unit in this case and it could as well stay an include.

In general, I prefer using named modules to header units though. My overall experience with header units and modules has been great. Build times can go way down, it's easier to narrow down the location of bugs, and for tests cases it's possible to simply omit one import and replace it with a mock. That wouldn't be possible with transitive headers. The most trouble I had was transitioning from headers with a lot of type forward declarations to named modules, as you can't have a forward declaration in one module and it's definition in another. The related link errors aren't the most intuitive, but that's what I expect from new features.

**Comment by iains** [comment]
> > (This section is not related to the issue report),
> > Out of curiosity, I want to ask how do you use header units? What is the build system you're using? 
.... snip....

> My overall experience with header units and modules has been great. Build times can go way down, it's easier to narrow down the location of bugs, and for tests cases it's possible to simply omit one import and replace it with a mock. 

That is very encouraging.

**Comment by ChuanqiXu9** [comment]
Thanks for the written-up! It is helpful. I didn't image that the named modules are helpful for testing. Interesting.

> The most trouble I had was transitioning from headers with a lot of type forward declarations to named modules, as you can't have a forward declaration in one module and it's definition in another.

Yeah, it needs some refactoring. I am not sure if you know you can have a forward declaration in a partition module unit and define it in another partition module unit. In this way, we may avoid the link errors you mentioned.

**Comment by kaimfrai** [comment]
> I didn't image that the named modules are helpful for testing.
Let me clarify that this works only for free functions found by ADL. For example defining operator == for Class in a submodule Class.Compare. You import that throughout the project, but in the test you import Class.CompareMock instead. Class.CompareMock may import but not export Class.Compare. As long as the mock operator == can be found by lookup (using declaration in the test file or global namespace) and the other one can't, this works great. 

> I am not sure if you know you can have a forward declaration in a partition module unit and define it in another partition module unit. In this way, we may avoid the link errors you mentioned.

I have made use of partitions for exactly that reason. However there are 2 different uses of forward declarations. One is for cyclic dependencies in which case there is no way around partitions. This isn't a problem as files with cyclic dependencies are often close together on the filesystem and putting them in the same module is easy. Of course, resolving the cycles in the first place would be preferable.

The other use case  is to save an include in the header to shorten build time. This can happen with 2 files that are in very different parts of the project (or even 2 different projects). Putting those in the same module may just require putting most of the entire project in the same module due to dependency chains. That defeats one of the main purposes of modules. With modules however, there is no need for these kinds of forward declarations and they should just be imports. Finding just those forward declarations and replacing them by imports can be bothersome, but given the improved build time I think it's worth the effort. I think include-what-you-use with --no_fwd_decls can be helpful in replacing forward-declarations with includes before transitioning to modules, but it's not perfect either.

**Comment by ChuanqiXu9** [comment]
Interesting. 

> One is for cyclic dependencies in which case there is no way around partitions. This isn't a problem as files with cyclic dependencies are often close together on the filesystem and putting them in the same module is easy. Of course, resolving the cycles in the first place would be preferable.

Yeah, it would be best to solve the dependencies in the first place. Another solution may be the use of `extern "C++"` in module units. The spec related note is http://eel.is/c++draft/module#unit-7.2.2. In short, the declarations in `extern "C++" of module units` are considered to be the declarations in the global module fragment. So their mangled name wouldn't change. An example can be found at: https://github.com/alibaba/async_simple/blob/8408bb47f8fb4ff6aa4afc83d4a3634c42e3ce55/async_simple/uthread/internal/thread_impl.h#L37-L40. (Although this uses `extern "C"`)

**Comment by kaimfrai** [comment]
> Another solution may be the use of `extern "C++"` in module units. The spec related note is http://eel.is/c++draft/module#unit-7.2.2. In short, the declarations in `extern "C++" of module units` are considered to be the declarations in the global module fragment. So their mangled name wouldn't change.

I had to make use of this once for a function, where a thirdparty C-Header required a macro defined to a function name, while the definition of the function required imports (used to be only includes before transitioning). So the declaration and the macro needed to be before the C include in the global module fragment but the definition after the imports in the named module fragment. That's only possible with extern "C"/ extern "C++". While I find the practice of injecting a declaration into a header with a macro strange, it is an interesing case to use extern "C" in modules.

That being said, I haven't considered using extern "C++" for class declarations too. I'll keep this option in mind, thank you. I hope this didn't go too far off topic.

**Comment by kaimfrai** [comment]
Thanks for the quick fixes so far. I just tried it with an updated local build of clang again. Unfortunately there are still some errors remaining. They all appear to be related to templates in headers not being inline.

With `clang++ -std=c++20 -stdlib=libc++ -xc++-system-header iostream --precompile -o iostream` I get errors like these:
```
include/c++/v1/exception:222:1: error: non-inline external definitions are not permitted in C++ header units
make_exception_ptr(_Ep __e) _NOEXCEPT
...
include/c++/v1/new:264:7: error: non-inline external definitions are not permitted in C++ header units
void* __libcpp_operator_new(_Args ...__args) {
...
include/c++/v1/__memory/unique_ptr.h:566:1: error: non-inline external definitions are not permitted in C++ header units
operator<=>(const unique_ptr<_T1, _D1>& __x, const unique_ptr<_T2, _D2>& __y) {
```

Using libstdc++12 with
`clang++ -std=c++20 -stdlib=libstdc++ -xc++-system-header execution --precompile -o execution -ferror-limit=0`
I get similar errors and finally a crash, only with the execution header. I'm unsure whether this one would need a separate issue.

**Comment by iains** [comment]
thanks for rechecking, will take a look at the templates cases.

**Comment by iains** [comment]
https://reviews.llvm.org/D142704 as a patch to handle function templates.

**Comment by kaimfrai** [comment]
> https://reviews.llvm.org/D142704 as a patch to handle function templates.

I just applied the patch locally. While some of the errors go away, there are still more unfortunately.
I spotted 4 different cases, all present in:
`clang++ -std=c++20 -stdlib=libc++ -xc++-system-header memory --precompile -ferror-limit=0`

### Variable templates
```
include/c++/v1/variant:364:22: error: non-inline external definitions are not permitted in C++ header units
constexpr _IndexType __variant_npos = static_cast<_IndexType>(-1);

include/c++/v1/variant:436:18: error: non-inline external definitions are not permitted in C++ header units
constexpr _Trait __trait =
```
### Free variadic template functions

```
include/c++/v1/new:264:7: error: non-inline external definitions are not permitted in C++ header units
void* __libcpp_operator_new(_Args ...__args) {

include/c++/v1/new:287:12: note: in instantiation of function template specialization 'std::__libcpp_operator_new<unsigned long, std::align_val_t>' requested here
    return __libcpp_operator_new(__size, __align_val)

include/c++/v1/new:297:6: error: non-inline external definitions are not permitted in C++ header units
void __do_deallocate_handle_size(void *__ptr, size_t __size, _Args ...__args) {

include/c++/v1/new:316:14: note: in instantiation of function template specialization 'std::__do_deallocate_handle_size<>' requested here
      return __do_deallocate_handle_size(__ptr, __size);
```

### Member functions of class templates

```
include/c++/v1/__memory/shared_ptr.h:235:41: error: non-inline external definitions are not permitted in C++ header units
__shared_ptr_pointer<_Tp, _Dp, _Alloc>::__get_deleter(const type_info& __t) const _NOEXCEPT

include/c++/v1/__memory/shared_ptr.h:1643:16: error: non-inline external definitions are not permitted in C++ header units
weak_ptr<_Tp>::~weak_ptr()
```

### Free template functions with deduced template argument
```
include/c++/v1/atomic:955:5: error: non-inline external definitions are not permitted in C++ header units
_Tp __cxx_atomic_load(__cxx_atomic_base_impl<_Tp> const volatile* __a, memory_order __order) _NOEXCEPT {

include/c++/v1/atomic:2356:51: note: in instantiation of function template specialization 'std::__cxx_atomic_load<bool>' requested here
        {return _LIBCPP_ATOMIC_FLAG_TYPE(true) == __cxx_atomic_load(&__a_, __m);}

include/c++/v1/atomic:1512:32: error: non-inline external definitions are not permitted in C++ header units
_LIBCPP_INLINE_VISIBILITY bool __cxx_atomic_wait(_Atp* __a, _Tp const __val, memory_order __order)

include/c++/v1/atomic:2376:10: note: in instantiation of function template specialization 'std::__cxx_atomic_wait<const volatile std::__cxx_atomic_impl<bool>, bool>' requested here
        {__cxx_atomic_wait(&__a_, _LIBCPP_ATOMIC_FLAG_TYPE(__v), __m);}
```
There might be more cases that I missed, it's quite a lot of errors with -ferror-limit=0

**Comment by iains** [comment]
OK thanks, hmm the instantiations are a surprise, since they are supposed to be implicitly inline (AFAIU).  I will look more at this ...

**Comment by dwblaikie** [comment]
> OK thanks, hmm the instantiations are a surprise, since they are supposed to be implicitly inline (AFAIU). I will look more at this ...

I think there's some needle that's threaded there where template instantiations aren't /technically/ inline, but some linkage or other wording covers similar sort of behavior.

**Comment by Arthapz** [comment]
Concepts too

```
error: In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.0.0/../../../../include/c++/13.0.0/string:42:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.0.0/../../../../include/c++/13.0.0/bits/char_traits.h:56:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.0.0/../../../../include/c++/13.0.0/compare:37:
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.0.0/../../../../include/c++/13.0.0/concepts:121:22: error: non-inline external definitions are not permitted in C++ header units
      constexpr bool __destructible_impl = false;
                     ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.0.0/../../../../include/c++/13.0.0/concepts:124:22: error: non-inline external definitions are not permitted in C++ header units
      constexpr bool __destructible_impl<_Tp> = true;
                     ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.0.0/../../../../include/c++/13.0.0/concepts:127:22: error: non-inline external definitions are not permitted in C++ header units
      constexpr bool __destructible = __destructible_impl<_Tp>;
                     ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.0.0/../../../../include/c++/13.0.0/concepts:129:22: error: non-inline external definitions are not permitted in C++ header units
      constexpr bool __destructible<_Tp&> = true;
                     ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.0.0/../../../../include/c++/13.0.0/concepts:131:22: error: non-inline external definitions are not permitted in C++ header units
      constexpr bool __destructible<_Tp&&> = true;
                     ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.0.0/../../../../include/c++/13.0.0/concepts:133:22: error: non-inline external definitions are not permitted in C++ header units
      constexpr bool __destructible<_Tp[_Nm]> = __destructible<_Tp>;
```

**Comment by iains** [comment]
firstly, I apologise that this is taking some time (and iterations) to resolve;  I fell into the trap (I should know better) of looking at the line in the standard and the examples and thinking it looked straight forward.  As often happens, it is the exclusions that are most tricky to pin down.

https://reviews.llvm.org/D142704 is now updated and (locally at least) consumes the libc++ headers individually.

Of course, we can also consider backing out of the original patch and the two follow-on ones if we are not converging on a working solution.

**Comment by Arthapz** [comment]
tryied the patch seems to work

```
> clang --version                                                                                                                                                                           
clang version 17.0.0 (/home/arthapz/llvm-git/llvm-project fc5da3969f2fd6065ab6b93f9586ece9002366ce)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

>rm -rf .xmake build; xmake f --toolchain=clang; xmake b                                                                                                                                    
checking for platform ... linux
checking for architecture ... x86_64
[  0%]: generating.module.deps src/main.cpp
[  0%]: generating.module.deps src/hello.mpp
[ 11%]: compiling.headerunit.release iostream
[ 33%]: compiling.module.release hello
[ 66%]: compiling.release src/main.cpp
[ 77%]: linking.release stl_headerunit
[100%]: build ok!

> rm -rf .xmake build; xmake f --toolchain=clang --cxxflags="-stdlib=libc++"; xmake b                                                                                                        
checking for platform ... linux
checking for architecture ... x86_64
[  0%]: generating.module.deps src/main.cpp
[  0%]: generating.module.deps src/hello.mpp
[ 11%]: compiling.headerunit.release iostream
[ 33%]: compiling.module.release hello
[ 66%]: compiling.release src/main.cpp
[ 77%]: linking.release stl_headerunit
[100%]: build ok!
```

**Comment by Arthapz** [comment]
with a more complexe scenario i get

```
> rm -rf .xmake build; xmake f --toolchain=clang; xmake b
checking for platform ... linux
checking for architecture ... x86_64
[  0%]: generating.module.deps src/main.cpp
[  4%]: compiling.headerunit.release iostream
[  4%]: compiling.headerunit.release utility
[  4%]: compiling.headerunit.release cstdio
[  4%]: compiling.headerunit.release vector
[  4%]: compiling.headerunit.release fstream
[  4%]: compiling.headerunit.release memory
[  4%]: compiling.headerunit.release queue
[  4%]: compiling.headerunit.release string
[  4%]: compiling.headerunit.release map
[  4%]: compiling.headerunit.release complex
[  4%]: compiling.headerunit.release deque
[  4%]: compiling.headerunit.release iomanip
[  4%]: compiling.headerunit.release cstdlib
[  4%]: compiling.headerunit.release set
[  4%]: compiling.headerunit.release algorithm
[  4%]: compiling.headerunit.release exception
[  4%]: compiling.headerunit.release stack
[  4%]: compiling.headerunit.release list
[ 88%]: compiling.release src/main.cpp
[ 92%]: linking.release stl_headerunit_cpp_only
[100%]: build ok!

> rm -rf .xmake build; xmake f --toolchain=clang --cxxflags="-stdlib=libc++"; xmake b                                                                                               
checking for platform ... linux
checking for architecture ... x86_64
[  0%]: generating.module.deps src/main.cpp
[  4%]: compiling.headerunit.release memory
[  4%]: compiling.headerunit.release exception
[  4%]: compiling.headerunit.release queue
[  4%]: compiling.headerunit.release iomanip
[  4%]: compiling.headerunit.release vector
[  4%]: compiling.headerunit.release utility
[  4%]: compiling.headerunit.release deque
[  4%]: compiling.headerunit.release set
[  4%]: compiling.headerunit.release map
[  4%]: compiling.headerunit.release fstream
[  4%]: compiling.headerunit.release cstdio
[  4%]: compiling.headerunit.release complex
[  4%]: compiling.headerunit.release cstdlib
[  4%]: compiling.headerunit.release iostream
[  4%]: compiling.headerunit.release list
[  4%]: compiling.headerunit.release string
[  4%]: compiling.headerunit.release stack
[  4%]: compiling.headerunit.release algorithm
[ 88%]: compiling.release src/main.cpp
error: /usr/bin/../include/c++/v1/ostream:254:20: error: 'std::basic_ostream<char>::operator<<' from module '/usr/bin/../include/c++/v1/complex' is not present in definition of 'std::ostream' in module '/usr/bin/../include/c++/v1/iostream'
    basic_ostream& operator<<(basic_streambuf<char_type, traits_type>* __sb);
                   ^
/usr/bin/../include/c++/v1/ostream:221:20: note: declaration of 'operator<<' does not match
    basic_ostream& operator<<(basic_ostream& (*__pf)(basic_ostream&))
                   ^
/usr/bin/../include/c++/v1/ostream:225:20: note: declaration of 'operator<<' does not match
    basic_ostream& operator<<(basic_ios<char_type, traits_type>&
                   ^
/usr/bin/../include/c++/v1/ostream:230:20: note: declaration of 'operator<<' does not match
    basic_ostream& operator<<(ios_base& (*__pf)(ios_base&))
                   ^
/usr/bin/../include/c++/v1/ostream:233:20: note: declaration of 'operator<<' does not match
    basic_ostream& operator<<(bool __n);
                   ^
/usr/bin/../include/c++/v1/ostream:234:20: note: declaration of 'operator<<' does not match
    basic_ostream& operator<<(short __n);
  > in src/main.cpp
  
> cat src/main.cpp
import <iostream>;
import <algorithm>;
import <deque>;
import <iostream>;
import <map>;
import <memory>;
import <set>;
import <utility>;
import <vector>;
import <string>;
import <queue>;
import <cstdlib>;
import <utility>;
import <exception>;
import <list>;
import <stack>;
import <complex>;
import <fstream>;
import <cstdio>;
import <iomanip>;

using namespace std;

int main(int argc, char** argv)
{
    cout << "hello world!" << endl;
    return 0;
}
```

**Comment by iains** [comment]
> with a more complexe scenario i get
> 
> ```
> <SNIP>
> [ 88%]: compiling.release src/main.cpp
> error: /usr/bin/../include/c++/v1/ostream:254:20: error: 'std::basic_ostream<char>::operator<<' from module '/usr/bin/../include/c++/v1/complex' is not present in definition of 'std::ostream' in module '/usr/bin/../include/c++/v1/iostream'
>     basic_ostream& operator<<(basic_streambuf<char_type, traits_type>* __sb);
>                    ^
> /usr/bin/../include/c++/v1/ostream:221:20: note: declaration of 'operator<<' does not match
>     basic_ostream& operator<<(basic_ostream& (*__pf)(basic_ostream&))
>                    ^
> <SNIP>
> 
> using namespace std;
> 
> int main(int argc, char** argv)
> {
>     cout << "hello world!" << endl;
>     return 0;
> }
> ```

That seems to be a different diagnostic - do you find it to be in some way related ?

**Comment by Arthapz** [comment]
you're right it more a bug in libc++ maybe ?

**Comment by iains** [comment]
> maybe it is not a header unit support problem but a bug of libc++ ?

perhaps, but when I  build ostream in isolation, this does not fire:
`./bin/clang++ -std=c++20 -stdlib=libc++ -xc++-system-header ostream --precompile --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -ferror-limit=5 -v`

gives only a warning about `#pragma system_header`

my changes are based on main `7a3e87298e2f`

**Comment by Arthapz** [comment]
i just build a llvm from df34581d2b004e20fda85b4c8617bf436e826f6c with ChianXqi p1689 and clang-scan-deps patches

**Comment by Arthapz** [comment]
```
/usr/bin/clang -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -fmodules -fno-implicit-module-maps -stdlib=libc++ -DNDEBUG -fmodules-cache-path=build/stlmodules/cache -c -Wno-everything -o build/stlmodules/cache/iostream.pcm -x c++-system-header iostream

/usr/bin/clang -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -fmodules -fno-implicit-module-maps -stdlib=libc++ -DNDEBUG -fmodules-cache-path=build/stlmodules/cache -c -Wno-everything -o build/stlmodules/cache/complex.pcm -x c++-system-header complex

/usr/bin/clang -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -fmodules -fno-implicit-module-maps -stdlib=libc++ -DNDEBUG -fmodule-file=build/stlmodules/cache/iostream.pcm -fmodule-file=build/stlmodules/cache/complex.pcm -o build/.objs/stl_headerunit_cpp_only/linux/x86_64/release/src/main.cpp.o src/main.cpp
```

```cpp
import <iostream>;
import <complex>;

using namespace std;

int main(int argc, char** argv)
{
    cout << "hello world!" << endl;
    return 0;
}
```

**Comment by iains** [comment]
I can repeat with my build, but cannot yet see any connection to the diagnostic that is the subject of this PR.

**Comment by Arthapz** [comment]
so it is not, i'll make an other issue

**Comment by kaimfrai** [comment]
> firstly, I apologise that this is taking some time (and iterations) to resolve

No worries, I'm well aware this can happen when using unreleased builds. I've been using a build from January 8th in the meantime. The patch seems to work this time, no issues with either libc++ or libstdc++, so thank you. I hope this lands soon on apt.llvm.org.

Regarding the other issue #60358 it seems to be the same issue as #58540.
I've ran into this before. My conclusion at the time was that some implementation detail headers are included into multiple standard headers. When compiling to a header unit, the declarations are bound to multiple units resulting in mismatches. It is solvable by explicitly specifying -fmodule-file="included-header.pcm" for every header included into each header unit. This is very cumbersome to do, will break when header includes change (e.g. granularization of includes) and is very slow to compile. I assume this isn't meant to work without  P1502R1 (Standard Library Header units for C++20).

The best current workaround I could come up with was to include all of the standard library headers into one header std.hpp and using this one as the only header unit for the standard library. By force importing it with a header import_std.hpp
`import <std.hpp>;`

and 

`--include/path/to/import_std.hpp -fmodule-file=std.hpp.pcm`

into third party files, the include guards exported by std.hpp.pcm will disable all includes of the standard library and use the header unit instead.
Not the most elegant solution, but a working one regardless (at least for open source).

**Comment by ChuanqiXu9** [comment]
@kaimfrai @Arthapz Could you help to test if the issue remains? Then we can close the issue.

**Comment by Arthapz** [comment]
work on my setup

> @kaimfrai @Arthapz Could you help to test if the issue remains? Then we can close the issue.

**Comment by kaimfrai** [comment]
No issues here. Tested libc++, libstdc++, C++20 and C++2b mode.
Thank you!
