### ISSUE TITLE
expandAddress() crashes on freeze node.

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#60107]
Csmith discovered a test case which had a comparison between pointer and int, which caused some optimizer to insert a freeze instruction. After `DAGCombining` this resulted in a DAG where `expandAddress()` got an `ISD::FREEZE` instead of a `PCREL_WRAPPER` node.

It seems it would be ideal to handle this somehow other than triggering the assert when casting to `GlobalAddressSDNode`.  Seems like there could be many places where this could show up, and not sure if it is something to try to handle everywhere or if it's ok to ignore - after all the input is kind of broken... I guess I am not quite sure what the benefit would be - to allow undefined values and still complete the compilation?

One fix for this test particular case might be:

```diff
--- a/llvm/lib/Target/SystemZ/SystemZISelDAGToDAG.cpp
+++ b/llvm/lib/Target/SystemZ/SystemZISelDAGToDAG.cpp
@@ -491,6 +491,8 @@ bool SystemZDAGToDAGISel::expandAddress(SystemZAddressingMode &AM,
   if (Opcode == SystemZISD::PCREL_OFFSET) {
     SDValue Full = N.getOperand(0);
     SDValue Base = N.getOperand(1);
+    if (Base->getOpcode() == ISD::FREEZE)
+      Base = Base->getOperand(0);
     SDValue Anchor = Base.getOperand(0);
     uint64_t Offset = (cast<GlobalAddressSDNode>(Full)->getOffset() -
                        cast<GlobalAddressSDNode>(Anchor)->getOffset());
```

Reduced C program:
```shell
./bin/clang crash0_aftercreduce.i -o -  -fno-inline -fno-PIC -O3
```

```console
crash0_aftercreduce.c:14:7: warning: comparison between pointer and integer ('char *' and 'char') [-Wpointer-integer-compare]

Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed. 
...
 #8 0x0000000002b04e30 (anonymous namespace)::SystemZDAGToDAGISel::expandAddress
...
```

llc input:
```shell
./bin/llc -mtriple=s390x-linux-gnu ./crash0_aftercreduce.ll
```

[testcase.tar.gz](https://github.com/llvm/llvm-project/files/10437766/testcase.tar.gz)

**Comment by RKSimon** [comment]
Maybe add SystemZ::isGuaranteedNotToBeUndefOrPoisonForTargetNode and return true for SystemZISD::PCREL_OFFSET opcodes?

Otherwise, what did the dag look like just before the SystemZISD::PCREL_OFFSET got created? There might be a generic node that needs better freeze/poison handling.

**Comment by JonPsson** [comment]
Thanks for pointing that out. This is what happens in this test case:


```
@b = dso_local global [6 x [6 x [3 x i8]]] zeroinitializer, align 2

define dso_local void @f(i8 noundef zeroext %g) local_unnamed_addr #0 {
entry:
  %agg.tmp.ensured.sroa.0 = alloca i8, align 2
  %conv = zext i8 %g to i64
  %0 = inttoptr i64 %conv to ptr
  %.fr = freeze ptr getelementptr inbounds ([6 x [6 x [3 x i8]]], ptr @b, i64 0, i64 1, i64 2, i64 1)
  %cmp = icmp eq ptr %.fr, %0
  %1 = load i8, ptr getelementptr inbounds ([6 x [6 x [3 x i8]]], ptr @b, i64 0, i64 5, i64 4, i64 2), align 2
  %conv2 = zext i8 %1 to i32
  br i1 %cmp, label %for.cond.us.preheader, label %for.cond.preheader
...

Type-legalized selection DAG: %bb.0 'f:entry'
SelectionDAG has 17 nodes:
  t0: ch,glue = EntryToken
        t37: i32,ch = load<(dereferenceable load (s8) from `ptr getelementptr inbounds ([6 x [6 x [3 x i8]]], ptr @b, i64 0, i64 5, i64 4, i64 2)`, align 2), zext from i8> t0, GlobalAddress:i64<ptr @b> + 104, undef:i64
      t31: ch = CopyToReg t0, Register:i32 %0, t37
      t17: i64 = freeze GlobalAddress:i64<ptr @b> + 25
        t2: i64,ch = CopyFromReg t0, Register:i64 %1
      t39: i64 = AssertZext t2, ValueType:ch:i8
    t36: ch = br_cc t31, seteq:ch, t17, t39, BasicBlock:ch<for.cond.us.preheader 0x5906cc0>
  t35: ch = br t36, BasicBlock:ch<for.cond.preheader 0x5906bc8>

Legalized selection DAG: %bb.0 'f:entry'
SelectionDAG has 24 nodes:
  t0: ch,glue = EntryToken
  t47: i64 = SystemZISD::PCREL_WRAPPER TargetGlobalAddress:i64<ptr @b> 0
          t49: i64 = SystemZISD::PCREL_OFFSET TargetGlobalAddress:i64<ptr @b> + 104, t47
        t37: i32,ch = load<(dereferenceable load (s8) from `ptr getelementptr inbounds ([6 x [6 x [3 x i8]]], ptr @b, i64 0, i64 5, i64 4, i64 2)`, align 2), zext from i8> t0, t49, undef:i64
      t31: ch = CopyToReg t0, Register:i32 %0, t37
          t51: i64 = add t47, Constant:i64<25>
        t17: i64 = freeze t51
          t2: i64,ch = CopyFromReg t0, Register:i64 %1
        t39: i64 = AssertZext t2, ValueType:ch:i8
      t42: i32 = SystemZISD::ICMP t17, t39, TargetConstant:i32<0>
    t45: ch = SystemZISD::BR_CCMASK t31, TargetConstant:i32<14>, TargetConstant:i32<8>, BasicBlock:ch<for.cond.us.preheader 0x5906cc0>, t42
  t35: ch = br t45, BasicBlock:ch<for.cond.preheader 0x5906bc8>

Combining: t17: i64 = freeze t51
 ... into: t51: i64 = add t52, Constant:i64<25>

Optimized legalized selection DAG: %bb.0 'f:entry'
SelectionDAG has 24 nodes:
  t0: ch,glue = EntryToken
    t47: i64 = SystemZISD::PCREL_WRAPPER TargetGlobalAddress:i64<ptr @b> 0
  t52: i64 = freeze t47
          t49: i64 = SystemZISD::PCREL_OFFSET TargetGlobalAddress:i64<ptr @b> + 104, t52
        t37: i32,ch = load<(dereferenceable load (s8) from `ptr getelementptr inbounds ([6 x [6 x [3 x i8]]], ptr @b, i64 0, i64 5, i64 4, i64 2)`, align 2), zext from i8> t0, t49, undef:i64
      t31: ch = CopyToReg t0, Register:i32 %0, t37
        t51: i64 = add t52, Constant:i64<25>
          t2: i64,ch = CopyFromReg t0, Register:i64 %1
        t39: i64 = AssertZext t2, ValueType:ch:i8
      t42: i32 = SystemZISD::ICMP t51, t39, TargetConstant:i32<0>
    t45: ch = SystemZISD::BR_CCMASK t31, TargetConstant:i32<14>, TargetConstant:i32<8>, BasicBlock:ch<for.cond.us.preheader 0x5906cc0>, t42
  t35: ch = br t45, BasicBlock:ch<for.cond.preheader 0x5906bc8>
```

So as you suspected it seems that the second DAGCombine pass optimizes the freeze node so that the target node PCREL_OFFSET ends up using a freeze node instead of the expected PCREL_WRAPPER. It seems to me that PCREL_OFFSET really always expects the PCREL_WRAPPER operand, so it seems likely better to somehow make dagcombiner not optimize the freeze in that way...?

**Comment by uweigand** [comment]
I agree with @RKSimon that this is probably best handled via `isGuaranteedNotToBeUndefOrPoisonForTargetNode`.  The specification states:
```
  /// Return true if this function can prove that \p Op is never poison
  /// and, if \p PoisonOnly is false, does not have undef bits. The DemandedElts
  /// argument limits the check to the requested vector elements.
```
Both `PCREL_OFFSET` and `PCREL_WRAPPER` are never poison and never have undef bits, so it should be safe to just always return true for those in `isGuaranteedNotToBeUndefOrPoisonForTargetNode`.

(We might also want to consider implementing `isGuaranteedNotToBeUndefOrPoisonForTargetNode` and/or `canCreateUndefOrPoisonForTargetNode` for the other platform-specific opcodes.  Even if not required for functional correctness, it might still improve codegen.)

**Comment by JonPsson** [comment]
Yes, I can cofirm that returning true from isGuaranteedNotToBeUndefOrPoisonForTargetNode() fixes the test case.

I am wondering if returning true here means that e.g. a memory access into an array is never out-of-bounds, or if it rather means that e.g. no vector elements / bits are unused (insignificant/undefined)...?

**Comment by uweigand** [comment]
> Yes, I can cofirm that returning true from isGuaranteedNotToBeUndefOrPoisonForTargetNode() fixes the test case.
> 
> I am wondering if returning true here means that e.g. a memory access into an array is never out-of-bounds, or if it rather means that e.g. no vector elements / bits are unused (insignificant/undefined)...?

There is no memory access in `PCREL_WRAPPER` / `PCREL_OFFSET`.  Both of these operations return an **address**, and `isGuaranteedNotToBeUndefOrPoisonForTargetNode` here simply says that that address itself never has any undefined bits and never is poison.

**Comment by JonPsson** [comment]
https://reviews.llvm.org/D142971

**Comment by RKSimon** [comment]
That patch looks fine to me, but I'm wondering if we can avoid the issue with generic DAG handling:
```
Type-legalized selection DAG: %bb.0 'f:entry'
SelectionDAG has 17 nodes:
  t0: ch,glue = EntryToken
        t37: i32,ch = load<(dereferenceable load (s8) from `ptr getelementptr inbounds ([6 x [6 x [3 x i8]]], ptr @b, i64 0, i64 5, i64 4, i64 2)`, align 2), zext from i8> t0, GlobalAddress:i64<ptr @b> + 104, undef:i64
      t31: ch = CopyToReg t0, Register:i32 %0, t37
      t17: i64 = freeze GlobalAddress:i64<ptr @b> + 25
        t2: i64,ch = CopyFromReg t0, Register:i64 %1
      t39: i64 = AssertZext t2, ValueType:ch:i8
    t36: ch = br_cc t31, seteq:ch, t17, t39, BasicBlock:ch<for.cond.us.preheader 0x5906cc0>
  t35: ch = br t36, BasicBlock:ch<for.cond.preheader 0x5906bc8>
```
We don't currently have any handling of `freeze GlobalAddress:i64<ptr @b> + 25` - my guess is that would help us more.

@nunoplopes any suggestions on what we can do here, are we OK to always drop the freeze on a GlobalAddressSDNode?

**Comment by nunoplopes** [comment]
You're stretching my knowledge of the backend (which is close to null..)
If GlobalAddress is the address of a global variable, then you can drop freeze, yes, as that value is produced by the linker, so we can assume it's always valid.
