### ISSUE TITLE
llvm 15.0.7 breaks API with 15.0.6

### ISSUE THREAD

**Issue by tcanabrava** [llvm/llvm-project#60124]
This is not API compatible.

HeaderCallbacks::InclusionDirective(clang::SourceLocation, cons
t clang::Token&, llvm::StringRef, bool, clang::CharSourceRange, const clang::FileEntry*,
llvm::StringRef, llvm::StringRef, const clang::Module*, clang::SrcMgr::CharacteristicKind
)’ marked ‘override’, but does not override

The class is defined as:

class HeaderCallbacks : public clang::PPCallbacks

PPCallbacks changed File* to Optional<File> on the method InclusionDirective, this breaks the API promise.

➜ diagram-server clang --version
clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Used to work on llvm 15.0.6

**Comment by nikic** [comment]
Can you please clarify which change (commit) you are talking about? I don't see any changes to clang in the 15.0.7 release at all.

**Comment by tcanabrava** [comment]
give me a moment, I'm downloading the source code to check what commit added this.

**Comment by tcanabrava** [comment]
*sigh*. aparently this was an *archlinux* bug, I'm trully sorry.
The package for 15.0.0 untill 15.0.6 contained a wrong header, and that made me believe that the 0.7 had broken things.
