### ISSUE TITLE
[packaging] `clang-16` and `libclang-common-16-dev` version mismatch using apt.llvm.org on s390x

### ISSUE THREAD

**Issue by danielocfb** [llvm/llvm-project#60128]
This issue appears very similar to https://github.com/llvm/llvm-project/issues/60108, but is about s390x and on `focal` (https://apt.llvm.org/focal/). We are hitting what appears to be the same version mismatch when installing the nightly snapshot:

```console
$ apt-get install clang-16
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clang-16 : Depends: libclang-common-16-dev (= 1:16~++20230114053028+b1e92f8def98-1~exp1~20230114173136.508) but it is not going to be installed
            Recommends: llvm-16-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Checking the [`Packages` file](https://apt.llvm.org/focal/dists/llvm-toolchain-focal/main/binary-s390x/Packages) it appears that what is in there is:
```
Package: libclang-common-16-dev
Source: llvm-toolchain-snapshot
Version: 1:16~++20230116052734+48e862d06d2f-1~exp1~20230116172838.510
```
So the versions don't match up exactly.

**Comment by danielocfb** [comment]
For what it's worth, the issue seems to be resolved. The current snapshot seems coherent. Leaving this open to understand the root cause and whether an additional fix should be necessary.

**Comment by trxcllnt** [comment]
Seems the issue is back today:

```shell
$ apt install -y --no-install-recommends clang-16 libclang-common-16-dev
The following packages have unmet dependencies:
 clang-16 : Depends: libclang-common-16-dev (= 1:16~++20230124042256+c3728d28821e-1~exp1~20230124042412.704) but 1:16~++20230124031324+d63e492562f2-1~exp1~20230124151444.705 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Looking at the files in the [llvm-toolchain-snapshot](https://apt.llvm.org/jammy/pool/main/l/llvm-toolchain-snapshot/), I see:

* `clang-16` ([~20230124151444.705_amd64.deb](https://apt.llvm.org/jammy/pool/main/l/llvm-toolchain-snapshot/clang-16_16~%2b%2b20230124031324%2bd63e492562f2-1~exp1~20230124151444.705_amd64.deb))
* `clang-16` ([20230124042412.704_arm64.deb](https://apt.llvm.org/jammy/pool/main/l/llvm-toolchain-snapshot/clang-16_16~%2b%2b20230124042256%2bc3728d28821e-1~exp1~20230124042412.704_arm64.deb))
* `libclang-common-16-dev` [~20230124151444.705_all.deb](https://apt.llvm.org/jammy/pool/main/l/llvm-toolchain-snapshot/libclang-common-16-dev_16~%2b%2b20230124031324%2bd63e492562f2-1~exp1~20230124151444.705_all.deb)

There's one `libclang-common-16-dev` deb (*.705_all.deb, presumably used for all architectures). This aligns with amd64, but the arm64 package still pins to `libclang-common-16-dev` 704.

**Comment by chantra** [comment]
We have had similar issue yesterday:
```
2023-02-22T20:35:15.6306167Z Some packages could not be installed. This may mean that you have
2023-02-22T20:35:15.6306712Z requested an impossible situation or if you are using the unstable
2023-02-22T20:35:15.6307256Z distribution that some required packages have not yet been created
2023-02-22T20:35:15.6307708Z or been moved out of Incoming.
2023-02-22T20:35:15.6308175Z The following information may help to resolve the situation:
2023-02-22T20:35:15.6308454Z 
2023-02-22T20:35:15.6308666Z The following packages have unmet dependencies:
2023-02-22T20:35:15.7256529Z  clang-16 : Depends: libclang-common-16-dev (= 1:16.0.0~++20230222063320+4c0da2726e7f-1~exp1~20230222063432.36) but it is not going to be installed
2023-02-22T20:35:15.7405509Z E: Unable to correct problems, you have held broken packages.
```
  
I just checked  https://apt.llvm.org/focal/dists/llvm-toolchain-focal-16/main/binary-arm64/Packages

```
Package: clang-16
Source: llvm-toolchain-16
Version: 1:16.0.0~++20230222063320+4c0da2726e7f-1~exp1~20230222063432.36
Architecture: arm64
Maintainer: LLVM Packaging Team <pkg-llvm-team@lists.alioth.debian.org>
Installed-Size: 383
Depends: libc6 (>= 2.17), libclang-cpp16 (>= 1:16.0.0~++20230222063320+4c0da2726e7f), libgcc-s1 (>= 3.0), libllvm16, libstdc++6 (>= 5.2), libstdc++-9-dev, libgcc-9-dev, libobjc-9-dev, libclang-common-16-dev (= 1:16.0.0~++20230222063320+4c0da2726e7f-1~exp1~20230222063432.36), llvm-16-linker-tools (= 1:16.0.0~++20230222063320+4c0da2726e7f-1~exp1~20230222063432.36), libclang1-16 (= 1:16.0.0~++20230222063320+4c0da2726e7f-1~exp1~20230222063432.36), libc6-dev, binutils
```

**Comment by chantra** [comment]
Another instance today with llvm-17 for s390x: https://github.com/kernel-patches/bpf/actions/runs/4308025693/jobs/7513810282#step:9:1324

```
  Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
  Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
  Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
  Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
  Hit:5 https://apt.llvm.org/focal llvm-toolchain-focal InRelease
  Reading package lists...
  Reading package lists...
  Building dependency tree...
  Reading state information...
  Some packages could not be installed. This may mean that you have
  requested an impossible situation or if you are using the unstable
  distribution that some required packages have not yet been created
  or been moved out of Incoming.
  The following information may help to resolve the situation:
  
  The following packages have unmet dependencies:
   clang-17 : Depends: libclang-common-17-dev (= 1:17~++20230227052932+2e7311170201-1~exp1~20230227173052.553) but it is not going to be installed
  E: Unable to correct problems, you have held broken packages.
  clang install failed
  ```

**Comment by yonghong-song** [comment]
@tstellar Tom, seems this becoming a recurring issue. Could you refer this to somebody maintaining the snapshot to investigate? Maybe this is just a script or cleanup issue or something like this? So fixing it properly can avoid the issue mentioned here? Thanks!

**Comment by sylvestre** [comment]
Interesting (and surprising)
is it only happening with focal?

**Comment by danielocfb** [comment]
> is it only happening with focal?

https://github.com/llvm/llvm-project/issues/60108 is reported for `jammy`.

**Comment by chantra** [comment]
@sylvestre from our own vantage point on Focal, it has affected pretty much any architecture that we use (amd64,, arm64, s390x), as well as both llvm-16 and llvm-17 repos.

I don't have data to back this up, but I believe this only started this year when we opened this issue (Jan 18), #60108 is from Jan 17, so probably any changes that got pushed around that time could be the reason.

**Comment by chantra** [comment]
Another example for llvm-17: https://github.com/kernel-patches/bpf/actions/runs/4429610238/jobs/7770295647?pr=4767

**Comment by sylvestre** [comment]
OK, looking at your logs, it is because the all packages (not arch specific) don't match the any packages (arch specific).
Examples:
https://apt.llvm.org/focal/pool/main/l/llvm-toolchain-snapshot/clang-17_17~%2b%2b20230314052649%2b641939baa928-1~exp1~20230314172755.568_s390x.deb
https://apt.llvm.org/focal/pool/main/l/llvm-toolchain-snapshot/libclang-common-17-dev_17~%2b%2b20230313052650%2b831e99fee90e-1~exp1~20230313172755.567_all.deb

The issue happened because the build worked on s390x but failed on amd64 (on which the all packages are built):
![image](https://user-images.githubusercontent.com/733326/225426969-09471f55-8dcb-458f-aa72-7f24b51710a0.png)

I will do two things:
* fix the builds
* make sure that the sync doesn't happened if all builds aren't completed
thanks for the ping

**Comment by chantra** [comment]
Thanks @sylvestre , really appreciated.

**Comment by sylvestre** [comment]
I think it is fixed. the sync to the repo is blocked when such issues are identified.

**Comment by chantra** [comment]
Thanks @sylvestre !

**Comment by trxcllnt** [comment]
@sylvestre does your fix apply to the dev releases as well? Seeing this issue again on arm64 today:
```
  #24 23.32  clang-17 : Depends: libclang-common-17-dev (= 1:17~++20230329042310+e4918d43763e-1~exp1~20230329042440.833) but 1:17~++20230329031506+d4879d769095-1~exp1~20230329151616.834 is to be installed
  #24 23.32  clangd-17 : Depends: libclang-common-17-dev (= 1:17~++20230329042310+e4918d43763e-1~exp1~20230329042440.833) but 1:17~++20230329031506+d4879d769095-1~exp1~20230329151616.834 is to be installed
  #24 23.33  libclang-17-dev : Depends: libclang-common-17-dev (= 1:17~++20230329042310+e4918d43763e-1~exp1~20230329042440.833) but 1:17~++20230329031506+d4879d769095-1~exp1~20230329151616.834 is to be installed
  #24 23.33  libclang-common-17-dev : Depends: libllvm17 (< 1:17~++20230329031506+d4879d769095-1~exp1~20230329151616.834.1~) but 1:17~++20230329042310+e4918d43763e-1~exp1~20230329042440.833 is to be installed
```

**Comment by chantra** [comment]
I have seen this issue again too (llvm-16 on s390x)

https://github.com/kernel-patches/vmtest/actions/runs/4864382599/jobs/8674241310#step:6:1330

```
 The following information may help to resolve the situation:
  The following packages have unmet dependencies:
   clang-16 : Depends: libclang-common-16-dev (= 1:16.0.3~++20230502043251+93e555fbd794-1~exp1~20230502043415.81) but it is not going to be installed
  E: Unable to correct problems, you have held broken packages.
  clang install failed
  Error: Process completed with exit code 1.
```

**Comment by trxcllnt** [comment]
@yonghong-song I cannot help, I am not an LLVM maintainer.

**Comment by anakryiko** [comment]
@sylvestre can you please take a look at this again? Currently aarch64 arch has broken clang-17 (https://github.com/kernel-patches/bpf/actions/runs/4986294006/jobs/8926872954?pr=3924), while s390x has both clang-16 and clang-17 broken (https://github.com/kernel-patches/bpf/actions/runs/4986294006/jobs/8926873121?pr=3924 for v16, https://github.com/kernel-patches/vmtest/actions/runs/4988185700/jobs/8930672396?pr=225 for v17).

**Comment by sylvestre** [comment]
@anakryiko sure, which distro version ?

**Comment by anakryiko** [comment]
I believe we use GithubAction's `ubuntu-latest`, so that must be Ubuntu-22.04. Thanks!

**Comment by chantra** [comment]
On Tue, May 16, 2023 at 10:08 AM Andrii Nakryiko ***@***.***>
wrote:

> I believe we use GithubAction's ubuntu-latest, so that must be
> Ubuntu-22.04. Thanks!
>
> —
>

Correction. We still use 20.04.

**Comment by kyle-figure** [comment]
Seeing this today on Ubuntu 22.04 aarch64. Is there any workaround besides building from source?
```
$ sudo ./llvm.sh 16
...
The following packages have unmet dependencies:
 clang-16 : Depends: libclang-common-16-dev (= 1:16.0.5~++20230519033354+5729e63ac7b4-1~exp1~20230519033407.92) but it is not going to be installed
 clangd-16 : Depends: libclang-common-16-dev (= 1:16.0.5~++20230519033354+5729e63ac7b4-1~exp1~20230519033407.92) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by sylvestre** [comment]
@kyle-figure I retriggered a build for this. Should be fine in a few hours

**Comment by sylvestre** [comment]
So, sharing the reason of the problem.
Currently, 15, 16 and 17 are built. 
15 and 16 are built where there are changes. 17 is built twice a day.

It happens often that 16 and 17 are built in parallel for the same distro.
Once one of the build on all architectures if completed, a sync will be done to the apt.llvm.org repo.
However, if 17 is synced and 16 didn't finished, it will sync the 2 versions at the same time.
if 16 on s390x or arm64 failed, it will trigger this kind of inconstancy.

I added  a check to make sure this situation doesn't happen anymore:
https://github.com/opencollab/llvm-jenkins.debian.net/blob/master/sync-to-llvm.sh#LL20C2-L20C2
