### ISSUE TITLE
Operator new and -fno-exceptions

### ISSUE THREAD

**Issue by asl** [llvm/llvm-project#60129]
Current implementation of `operator new` in libcxx / libcxxabi effectively makes plain `new` and nothrow `new` to coincide when exceptions are disabled: both will return nullptr. However, there is one important difference: for nothrow `new` the constructor is not called when the return value is null. This does not happen for ordinary `new` in `-fno-exceptions` case making impossible to check the return value as constructor might just segfault. From the user perspective it might be better to stick to one of the following:
  * Just call `abort()`. This seems what is currently done for things like `std::__throw_out_of_range` in `-fno-except` case
  * Make `operator new` and nothrow `operator new` to behave identically and do not call constructor

Any thoughts on what might be the better solution?

**Comment by BetzalelG** [comment]
Calling `abort()` is the right call in my opinion.
- This is how libstdc++ and VS implementations handle it.
- This is how it's done for every other exception in libcxx, including other places where `__throw_bad_alloc()` is called.
- This will retain the C++ standard that says operator new shouldn't return a nullptr.
