### ISSUE TITLE
[ARM] signaling NaN constant gets lowerd to quiet NaN

### ISSUE THREAD

**Issue by Hardy7cc** [llvm/llvm-project#60130]
Edit: incorporated amilendra's  comment.

Version `llc 15.0.0`

When compiling the following llvm-ir with `llc -mtriple arm-linux-none` the constant value `0xH7C01` seems to get turned into `#1 '+' #32256` => `(0x7E01)` __inverting the signaling bit__ ~and discarding the payload of the float value~.
```ll
define dso_local void @entry() #0 {
Entry:
    %0 = alloca half, align 2
    store half 0xH7C01, ptr %0, align 2
    ret void
}
```
Generated assembler:
```asm
entry:
        sub     sp, sp, #4
        mov     r0, #1
        orr     r0, r0, #32256
        strh    r0, [sp, #2]
        add     sp, sp, #4
        mov     pc, lr
```

I originally discovered this during investigating this zig code with godbolt (https://godbolt.org/z/487zsYsnq) ~this example is even more weird~. The zig example code does switch from `0xH7C01` to `#32257 (0x7E01)` inverting the signaling bit ~but preserving the payload~.

**Comment by amilendra** [comment]
I could be missing something, but doesn't this assembly code eventually result in `0x7E01` in `r0`?
```
        mov     r0, #1
        orr     r0, r0, #32256
```
But if I am correct, then the issue simply becomes the inversion of the signaling bit?

**Comment by Hardy7cc** [comment]
With llvm 19 this problem is fixed. e.g. the signaling bit of floating point values is not altered.
