### ISSUE TITLE
Broken link to SourceWeb (aka CxxCodeBrowser) project in "External Clang Examples" page

### ISSUE THREAD

**Issue by i-ky** [llvm/llvm-project#60142]
https://github.com/llvm/llvm-project/blob/9308014195e2f091c0025ef4aa26ece080b7da8d/clang/docs/ExternalClangExamples.rst#L36-L37

The link was added (https://github.com/llvm/llvm-project/commit/03bfc678c50d9545bb3521869b4a1b69123f1d95) just before [GitHub Pages moved from `.com` to `.io`](https://github.blog/2013-04-05-new-github-pages-domain-github-io/), but it is extra wrong now, since [SourceWeb has been renamed to CxxCodeBrowser](https://github.com/rprichard/CxxCodeBrowser/commit/a2fa83d2fe06119f0a7a1827b8167fab88b53561). Correct link is https://rprichard.github.io/CxxCodeBrowser/ nowadays.

@rprichard, FYI

**Comment by s-pratik** [comment]
Hi , I would like to contribute
