### ISSUE TITLE
Libc++ 16.0.0 (In-Progress) Release Notes don't say when it will be released

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#60150]
[Libc++ 16.0.0 (In-Progress) Release Notes](https://libcxx.llvm.org/ReleaseNotes.html)

Clang still doesn't support many C++20 features, some of them are supposed to be released in libc++16. It is important to know when it will be released.

**Comment by brad0** [comment]
The tentative release dates are on the LLVM website.
