### ISSUE TITLE
[libc++][format] Some contiguous ranges cannot be formatted due to lack of `data` or `size` member functions

### ISSUE THREAD

**Issue by JMazurkiewicz** [llvm/llvm-project#60164]
Example:

```c++
#include <format>
#include <ranges>

using namespace std;

struct Conti {
    const char* begin() const;
    const char* end() const; 
    // const char* data() const;
    // size_t size() const; 
};

static_assert(ranges::contiguous_range<Conti>);
static_assert(ranges::sized_range<Conti>);
static_assert(formattable<Conti, char>);

int main() {
    Conti conti;
    (void) format("{}\n", conti);
}
```

Expected: *correct compilation with `-fsyntax-only`*

Got:
```console
/opt/compiler-explorer/clang-trunk-20230120/bin/../include/c++/v1/__format/range_formatter.h:172:67: error: no member named 'data' in 'Conti'
      return __formatter.format(basic_string_view<_CharT>{__range.data(), __range.size()}, __ctx);
                                                          ~~~~~~~ ^
[MORE LINES]
```

Possible solution:
https://github.com/llvm/llvm-project/blob/097f42602d83926a9d5e7fbe3d0bb8ef5c733183/libcxx/include/__format/range_formatter.h#L172

We should use `ranges::data` and `ranges::size` here.

Compiler explorer: https://godbolt.org/z/M4jPhM9Pv

**Comment by mordante** [comment]
Thanks for another report. I will have to take a look. It seems a contiguous range is not a sized range. So I guess fixing data, won't resolve this issue.

**Comment by mordante** [comment]
I've created a fix https://reviews.llvm.org/D142302

**Comment by mordante** [comment]
landed https://reviews.llvm.org/rGa6c43e8ca8f622ee2da4bad5458ebf5cecf6dd90
