### ISSUE TITLE
simplify logical selects

### ISSUE THREAD

**Issue by sftlbcn** [llvm/llvm-project#60167]
https://alive2.llvm.org/ce/z/ptZcJH
```ll
define i1 @src(i1 %x, i1 %y) {
  %a = select i1 %x, i1 %y, i1 false
  %r = select i1 %a, i1 true, i1 %y
  ret i1 %r
}
define i1 @tgt(i1 %x, i1 %y) {
  ret i1 %y
}
```

**Comment by rotateright** [comment]
This plus a related fold should be fixed now with the above commits. 
There are still missing transforms for related patterns though, so please file more bug reports if you find them.
