### ISSUE TITLE
[clang-14, C++20] Link error when calling GNU string literal operator template from a function template

### ISSUE THREAD

**Issue by ronhe** [llvm/llvm-project#60185]
Minimal code to reproduce the error:
```c++
// literal.hpp

#include <array>
#include <iostream>

template<typename Char, Char... chars>
consteval std::array<Char, sizeof...(chars) + 1> operator ""_arr()
{
    return { chars..., '\0' };
}

template <typename T>
void print(T t) {
    std::string s(("abcd"_arr).data());
    std::cout << s << std::endl;
}
```

```c++
// main.cpp

#include <iostream>
#include "string_literal.hpp"

int main() {
    print(7);
    return 0;
}
```
Compiling:
```console
$ c++ -std=c++20 -o program main.cpp
In file included from main.cpp:2:
./literal.hpp:12:50: warning: string literal operator templates are a GNU extension [-Wgnu-string-literal-operator-template]
consteval std::array<Char, sizeof...(chars) + 1> operator ""_arr()
                                                 ^
1 warning generated.
/usr/bin/ld: /tmp/main-333f4a.o: in function `void print<int>(int)':
main.cpp:(.text._Z5printIiEvT_[_Z5printIiEvT_]+0xc): undefined reference to `std::array<char, (4)+(1)> operator"" _arr<char, (char)97, (char)98, (char)99, (char)100>()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

More information:
1. Compilation fails with Clang 14.0.6, but succeeds with Clang 15.0.7 (or GCC 11.3.0).
2. Compilation succeeds if the call to the string literal template is done from a regular function (*not* function template), i.e.:
```c++
// main.cpp

int main() {
    std::string s(("abcd"_arr).data());
    std::cout << s << std::endl;
    return 0;
}
``` 
3. Compliation succeeds if the string literal template is decalred as `constexpr` rather than `consteval`, i.e.
```c++
// literal.hpp
template<typename Char, Char... chars>
constexpr std::array<Char, sizeof...(chars) + 1> operator ""_arr()
{
    return { chars..., '\0' };
}
...
```

**Comment by EugeneZelenko** [comment]
Could you please try 15 or `main` branch? https://godbolt.org should be helpful.

**Comment by ronhe** [comment]
> Could you please try 15 or `main` branch? https://godbolt.org should be helpful.

Hi,
As I've written in the original post, this error does not occur in clang-15.

**Comment by EugeneZelenko** [comment]
Only recent release in maintained. However, you could try to backport fixes on your branch yourself.

**Comment by ronhe** [comment]
> Only recent release in maintained. However, you could try to backport fixes on your branch yourself.

I understand, thanks for the quick response.

**Comment by AaronBallman** [comment]
We're not currently planning to release any further updates to Clang 14.x (or 15.x for that matter), so closing this issue as being fixed.
