### ISSUE TITLE
[AVR] link failure: clang passes broken option `-T text=` and `-T data=` to the GNU linker

### ISSUE THREAD

**Issue by sprintersb** [llvm/llvm-project#60203]
The GNU linker supports options `-Ttext=`,  `-Tdata=` etc.  But when clang passes these options to GNU `ld`, it adds an additional blank after `T`:

```console
> echo 'int main(){};' | avr-gcc -xc - -o x.elf -mmcu=atmega2560 -Ttext=0x10000 -v # ok
```
shows that `ld` gets `-Ttext=0x10000`.  With clang however it passes `-T text=0x10000`:

```console
> echo 'int main(){};' | avr-clang -xc - -o x.elf -mmcu=atmega2560 -Ttext=0x10000 -v
...
"/usr/bin/avr-ld" -o x.elf --gc-sections -L... -Tdata=0x800200 --start-group -l:crtatmega2560.o -lgcc -lm -lc -latmega2560 /tmp/--17d6c3.o --end-group -T text=0x10000 -mavr6
/usr/bin/avr-ld: cannot open linker script file text=0x10000: No such file or directory
clang: error: avr-ld command failed with exit code 1 (use -v to see invocation)
```

Using `-Wl,Tdata=` to pass options through to the linker is not a good idea, because the driver program must omit `-Tdata=` if the user specifies `-Tdata=`.  Using `-Wl,-Tdata=` would lead to two incompatible specifictions of data start.

**Comment by benshi001** [comment]
These `-Ttext`/`-Tdata`/`-Tbss` have already been removed in https://github.com/llvm/llvm-project/commit/89df4e4825ee6136bebbe5f70de29eb80456aaa4, we have to find another way to handle the conflict between user speficied `-Wl,-Tdata=` and the default `-Tdata`.

**Comment by sprintersb** [comment]
So why were they removed? I didn't try other targets but this should be pretty uniform across targets? No?

**Comment by benshi001** [comment]
> So why were they removed? I didn't try other targets but this should be pretty uniform across targets? No?
> 

I do not know the reason. But actually all targets are affected.

**Comment by benshi001** [comment]
Sorry, my fault. I deleted your comment by mistake, due to the poor internet connection. But I just want to clarify your doubt.

**Comment by benshi001** [comment]
One solution is using a linker script, if `-T xx.lds` is specified, the default `-Tdata=xxx` option won't be emitted to the linker.

**Comment by benshi001** [comment]
I created a patch, https://reviews.llvm.org/D142595, it is not perfect but works.

**Comment by sprintersb** [comment]
Is there a page that lists incompatibilities between avr-gcc and clang/llvm? Ans that points to work-arounds?

There are already many differences that will be confising.

* Extent, handling and semantics of command line options.
* How to support new targets (spec-files for avr-gcc so no need to touch / re-build compiler or libc).
* ...

And whether these incompatibilities are planned to go away or will persist.

**Comment by benshi001** [comment]
I am sorry I do not known such a page, but I guess there is no. Current active developers on clang-lllvm-ir are Ayke and me. I work on llvm in my spare time, at least I have no strict plan or long term plan for llvm-avr development work. 

My rough plan is 
1. making lld works and fully replaces avr-ld, 
2. fix reported bugs.

**Comment by MaskRay** [comment]
> Using `-Wl,Tdata=` to pass options through to the linker is not a good idea, because the driver program must omit `-Tdata=` if the user specifies `-Tdata=`. Using `-Wl,-Tdata=` would lead to two incompatible specifictions of data start.

I don't understand this. The compiler driver forwards `-Wl,` to the linker. While some linker options with identical semantics in the driver are recommended to be used without `-Wl,` (e.g. `-l` `-L`), options like `-Tdata=` are not. They are always preferred to be used with `-Wl,`. It's not a problem to have multiple `-Tdata=`. The last wins.

`clang -Tdata=0x100` never works. It passes `-T data=0x100` to ld while `-T` is interpreted as another option.
Since it never works, and AFAICT there isn't a compelling reason adding a driver option `-Tdata=`, I prefer that we never add it, i.e. this probably should be a wontfix.

**Comment by benshi001** [comment]
Though two conflict `-Tdata` options can be speicified and the last one win, there is another underlying issue.

If user explicitly specifies a linker script, the default added `-Tdata` by clang driver will overwrite the value in the user's linker script. We should not emit default `-Tdata` is a linker script is specified.

**Comment by benshi001** [comment]
I will close this issue and open another issue for my above concern.

**Comment by benshi001** [comment]
https://github.com/llvm/llvm-project/issues/60362
