### ISSUE TITLE
[AVR] clang "error: invalid % escape in inline assembly string" for `%~` and `%!`

### ISSUE THREAD

**Issue by sprintersb** [llvm/llvm-project#60204]
avr-gcc supports the following zero-argument % sequences in inline assembly that has arguments:

* `%!` resolves to the letter `e` if the device suports `eicall` and `eijmp`. Otherwise, it resolves to the empty string.
* `%~` resolves to the letter `r` for devices with at most 8KiB of program memory. Otherwise, it resolves to the empty string.

This allows to emit appropriate call and jmp instructions depending on the device:
```c++
int main (void)
{
    __asm ("%~call 0" :);
    __asm ("%~jmp 0" :);
    __asm ("%!icall" :);
    __asm ("%!ijmp" :);
}
```
Compiled for ATmega8, the inline asm part will compile to
```asm
	rcall 0
	rjmp 0
	icall
	ijmp
```
whereas on ATmega2560, it will be:
```asm
	call 0
	jmp 0
	eicall
	eijmp
```
A work-around is to have several versions of the code depending on `__AVR_3_BYTE_PC__` and similar.

**Comment by benshi001** [comment]
fixed by https://reviews.llvm.org/D145659

**Comment by benshi001** [comment]
fixed by https://github.com/llvm/llvm-project/commit/96cc2d07e15a5ce9ad134ed8db0a88d7c6c0d657
