### ISSUE TITLE
[MLIR][Presburger] Expensive check in assert mode - hasConsistentState

### ISSUE THREAD

**Issue by bondhugula** [llvm/llvm-project#60207]
This seems to be  prohibitively expensive to justify even in assert mode: https://github.com/llvm/llvm-project/blob/3c560dd0ae676e28a2560b1041c9411908e999a5/mlir/lib/Analysis/Presburger/Matrix.cpp#L370

Is this really needed? One wouldn't expect entire parts of a buffer checked in an assert that would have otherwise been O(1). It significantly slows down Release assert build (a common configuration) and would be dominant in nearly anything that is heavy on affine analysis.

CC: @Groverkss

**Comment by bondhugula** [comment]
@Superty @Groverkss - any comments here?

**Comment by Superty** [comment]
Sorry about the delay, see https://reviews.llvm.org/D143728

**Comment by Superty** [comment]
Closed by https://github.com/llvm/llvm-project/commit/057cae64ebc48e994afd85bebfbdcd03b2d23c41
