### ISSUE TITLE
[flang] Compilation error of omission of actual argument

### ISSUE THREAD

**Issue by ohno-fj** [llvm/llvm-project#60225]
```
Version of flang-new : 16.0.0(77f2f34d696b77fe5bf05afbe7386966b6bcc8ba)
```

Omission of actual argument results in a compilation-time error.

The following are the test program, flang-new, gfortran and ifort compilation result.

`snggj359_4.f90`:
```f90
program main
  call sub1
  print *,'OK'
end program main

module m1
contains
  recursive subroutine sub(a1,a2)
    optional::a1
    interface
       function a1(i) result(r)
         character(len=i),pointer::r
       end function a1
    end interface
    character(len=*),allocatable,optional::a2(:)
  end subroutine sub
end module m1

subroutine sub1
  use m1
  interface
     function func1(i) result(r)
       character(len=i),pointer::r
     end function func1
  end interface
  character,pointer:: a1
  character,allocatable:: a2(:)
  allocate(a1,a2(2))
! a1='0'; a2='1'; call sub(a1=func1,a2=a2); write(6,*) "a1 = ", a1, "  a2 = ", a2
  a1='0'; a2='2'; call sub(         a2=a2); write(6,*) "a1 = ", a1, "  a2 = ", a2
  deallocate (a1,a2)
end subroutine sub1

function func1(i) result(r)
  character(len=i),pointer::r
  allocate(r);r='1234'
end function func1
```

```console
$ flang-new -flang-experimental-exec snggj359_4.f90
error: loc("./snggj359_4.f90":30:19): 'fir.absent' op result #0 must be any reference or box like, but got 'tuple<!fir.boxproc<() -> ()>, i64>'
error: verification of lowering to FIR failed
$
```

```console
$ gfortran snggj359_4.f90
$
```

```console
$ ifort snggj359_4.f90
$
```

**Comment by luporl** [comment]
Something goes wrong when omitting an optional function argument.
If the function return type is integer or real, for instance, no errors occur, but character is not handled properly.
The following reduced example illustrates this:

```f90
module m1
contains
  subroutine sub(a1)
    optional :: a1
    interface
       character function a1(i)
       end function
    end interface
  end subroutine sub
end module m1

subroutine sub1
  use m1
  call sub()
end subroutine sub1
```

**Comment by luporl** [comment]
It turns out the MLIR type of a dummy argument that is a function that returns a `character` is really a `tuple<!fir.boxproc<() -> ()>, i64>`, where the second tuple element is the `character` length.

Would modifying `fir.absent` to allow this type as a result be a good solution?

**Comment by luporl** [comment]
Proposed fix: https://reviews.llvm.org/D144743

**Comment by luporl** [comment]
> It turns out the MLIR type of a dummy argument that is a function that returns a `character` is really a `tuple<!fir.boxproc<() -> ()>, i64>`, where the second tuple element is the `character` length.
> 
> Would modifying `fir.absent` to allow this type as a result be a good solution?

Just modifying `fir.absent` to allow tuples such as the one above doesn't work, as `fir.absent` value end up becoming a null pointer, that can't be cast to a tuple or struct.
A better approach is to modify lowering to create a new tuple in this case, that can then be filled with an absent function address and a dummy character length.
