### ISSUE TITLE
aarch64-w64-windows-gnu: OpenMP SEGFAULTs

### ISSUE THREAD

**Issue by hmartinez82** [llvm/llvm-project#60220]
#### Clang information:
```
clang version 15.0.7
Target: aarch64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/clangarm64/bin
```
#### Description
After OpenMP started being build for CLANGARM64  many dependent packages started using it for their aarch64 builds too. 
Then, applications like Inskscape, Darktable and GraphicksMagic started crashing during execution or while running unit tests.
None of these crashes were happening in CLANGARM64 with OpenMP disabled in their builds,  and none with these crashes happen in CLANG64 of MINGW64 builds of the same applications with OpenMP enabled.

#### Option 1 - Run OpenMP unit tests in MSYS2's CLANGARM64
- In a Windows on ARM machine, uncomment the  `clangarm64` repo in `/etc/pacman.conf` (https://www.msys2.org/docs/repos-mirrors/) and update all packages with `pacman -Syu`
- Install pip with `pacman -S ${MINGW_PACKAGE_PREFIX}-python-pip`
- Install lit with `pip install lit`
- Edit `mingw-w64-openmp/PKGBUILD` and add an extra `OPENMP_LLVM_LIT_EXECUTABLE` to the CMake call. E.g:
```
      -B "build-${MSYSTEM}-${shared_libs}" \
      -DOPENMP_LLVM_LIT_EXECUTABLE:FILEPATH="${MINGW_PREFIX}/bin/lit-script.py"
```
- Build OpenMP package
- cd to `src/build-${MSYSTEM}-shared` and run `ninja check-openmp`
The unit tests fails, some even error out: https://gist.github.com/hmartinez82/02a36d1471c1f24c66f2c37b8e07ce2f

#### Option 2 - Run Darktable or Darktable's cltest
- Install Darktable with `pacman -S mingw-w64-clang-aarch64-darktable`
- Run `darktable-cltest.exe`. It crashes at https://github.com/darktable-org/darktable/blob/5253d9a8f7e5d33581e457203353a99baf21ae03/src/common/gaussian.c#L219
LLDB's output:
```
lldb) target create "darktable-cltest"
(rrent executable set to 'C:\msys64\clangarm64\bin\darktable-cltest.exe' (aarch64).
(lldb) process handle SIGSEGV --notify true --pass true --stop true
NAME         PASS     STOP     NOTIFY
===========  =======  =======  =======
SIGSEGV      true     true     true
(lldb) r
(lldb) Process 13060 launched: 'C:\msys64\clangarm64\bin\darktable-cltest.exe' (aarch64)
Process 13060 stopped
* thread #10, stop reason = Exception 0xc0000005 encountered at address 0x7ffd5fd1976c: Access violation reading location 0xffffe5b86ff1e840
    frame #0: 0x00007ffd5fd1976c libdarktable.dll`.omp_outlined. at gaussian.c:219:15
```

#### Option 3 - Open Inkscape's about dialog
- Install Inkscape with `pacman -S mingw-w64-clang-aarch64-inkscape`
- Run Inkscape and create a new empty document
- Open the about box with Help -> About Inkscape
LLDB's output:
```
$ lldb -- inkscape
(lldb) target create "inkscape"
(rrent executable set to 'C:\msys64\clangarm64\bin\inkscape.exe' (aarch64).
(lldb) process handle SIGSEGV --notify true --pass true --stop true
NAME         PASS     STOP     NOTIFY
===========  =======  =======  =======
SIGSEGV      true     true     true
(lldb) r
(lldb) Process 7340 launched: 'C:\msys64\clangarm64\bin\inkscape.exe' (aarch64)
Process 7340 stopped
* thread #27, stop reason = Exception 0xc0000005 encountered at address 0x7ffd491acb0c: Access violation reading location 0x100000001
    frame #0: 0x00007ffd491acb0c libinkscape_base.dll`Inkscape::Filters::FilterGaussian::~FilterGaussian() + 3524
libinkscape_base.dll`Inkscape::Filters::FilterGaussian::~FilterGaussian:
->  0x7ffd491acb0c <+3524>: ldrsw  x11, [x29]
    0x7ffd491acb10 <+3528>: madd   x13, x10, x8, x9
    0x7ffd491acb14 <+3532>: ldrsw  x9, [x19]
    0x7ffd491acb18 <+3536>: sub    x10, x9, #0x1
```

**Comment by alvinhochun** [comment]
I would think that it is expected for OpenMP on aarch64 mingw-w64 in LLVM 15 to not work correctly. After all, the support upstream has only been filled in for trunk/16 and not officially backported. The OpenMP test suite has only been verified for mingw-w64 since then, not before.

I would be very interested to see you test with LLVM trunk, but I guess it is probably non-trivial to do with MSYS2.

**Comment by mstorsjo** [comment]
The openmp backports in the msys2 repo are insufficient for aarch64. If you backport all of my commits in the openmp subdirectory from git main (although patches that only touch tests can be skipped), it should work though.

**Comment by mstorsjo** [comment]
In particular, fb947c358661b3bd3d5e1fa776ec74cc0f308854 (and the follow-up fix in d6ab42dec492ccd3f1b515796d9d2fb020c520bd) are essential.

**Comment by hmartinez82** [comment]
@mstorsjo I'll give backporting those two commits a try. Thank you. I'll this posted with my findings

**Comment by lazka** [comment]
> In particular, [fb947c3](https://github.com/llvm/llvm-project/commit/fb947c358661b3bd3d5e1fa776ec74cc0f308854) (and the follow-up fix in [d6ab42d](https://github.com/llvm/llvm-project/commit/d6ab42dec492ccd3f1b515796d9d2fb020c520bd)) are essential.

Thanks for the further hints on potential backports.

Note that since the aarch64 openmp support in MSYS2 is not very well tested and based on backports please feel free to close this. I'd hate for upstream to have to do unnecessary work because of our uninformed patching.

**Comment by hmartinez82** [comment]
@lakza Thank you for applying those patches. I just got from work and you already did it!.
@mstorsjo  I can confirm that after those patches the SEGFAULTs are gone in Inkscape and GraphicsMagick 🚀

**Comment by mstorsjo** [comment]
> @mstorsjo I can confirm that after those patches the SEGFAULTs are gone in Inkscape and GraphicsMagick 🚀

Awesome, thanks! Good to know that there aren't further known issues with the library on aarch64 at this point.
