### ISSUE TITLE
[OpenMP] better error message

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#60221]
I sometimes miscompile the offload code with an architecture different from the one to run on.
I only get an offload failure and need to use `LIBOMPTARGET_DEBUG=1` to figure out the following.
```
Target AMDGPU RTL --> Incompatible: Processor mismatch 	[Image: gfx90a]	:	[Env: gfx906:sramecc+:xnack-]
Libomptarget --> Image 0x0000561fe7b34ce0 is NOT compatible with RTL !
```
I was running with `OMP_TARGET_OFFLOAD=mandatory`
Is there a way t make this error immediately visible without rerun with `LIBOMPTARGET_DEBUG=1`

**Comment by jhuber6** [comment]
That will trigger if, for example, the user compiled with `--offload-arch=gfx1030,gfx90a` on a machine with just a `gfx90a` processor. We could probably keep track and print if we don't find any and the offloading is mandatory.

**Comment by jhuber6** [comment]
I've been tempted to do a complete rewrite of error handling in `libomptarget` to use the LLVM error handling, basically like what the nextgen plugins do.

**Comment by shiltian** [comment]
That's gonna be great. :-) However, still, error handling between plugins and `libomptarget` will not support it because of the C API limitation.

**Comment by jhuber6** [comment]
Proposed [D142369](https://reviews.llvm.org/D142369).
