### ISSUE TITLE
[Documentation] Dead link on

### ISSUE THREAD

**Issue by bertulli** [llvm/llvm-project#60238]
Hi! I found a dead link in one of the documentation pages.

Documentation > Getting Started/Tutorials > Architecture & Platform Information for Compiler Writers > [Miscellaneous Resources](https://llvm.org/docs/CompilerWriterInfo.html#miscellaneous-resources): the link [Executable File Format library](http://www.nondot.org/sabre/os/articles/ExecutableFileFormats/) is broken, and a Google `site:` search seems not able to find the original. On the Wayback machine, the [latest saved copy I could find](https://web.archive.org/web/20150520091725/http://www.nondot.org/sabre/os/articles/ExecutableFileFormats/) is of the 20th of May 2015 (whereas since the 10th of August the page is a 404).

I'm opening this and not a PR because I don't know whether do you prefer to place a link to the archived version (old(?)), or to a different resource. I don't know much about the topic to provide an alternative suggestion, except maybe for [these summaries](https://github.com/corkami/pics) (I don't know if they satisfy the purposes for which the page was included in the docs in the first place, may be completely useless).

Thanks!

**Comment by AaronBallman** [comment]
CC @lattner and @tlattner -- that link is to your server, any chance you can resurrect the document? We can link to somewhere new if you've moved the resource.

**Comment by lattner** [comment]
Aha, that is a truly ancient link and I don't have any of the docs anymore, it probably exists in the wayback machine?

**Comment by AaronBallman** [comment]
> Aha, that is a truly ancient link and I don't have any of the docs anymore, it probably exists in the wayback machine?

It does; are you fine if we pull a copy out of the wayback machine and host it on the LLVM website? Or do you think the information in the link is sufficiently outdated that the link should be removed instead?

**Comment by lattner** [comment]
Honestly I think we should just drop the link or change it, there has to be a better reference for the ELF format than there was 25 years ago :)

**Comment by AaronBallman** [comment]
Okay, I'll replace the link with something that seems reasonable and if I don't find anything, I'll remove it entirely.
