### ISSUE TITLE
[clang] -fuse-ld option does not accept value with space

### ISSUE THREAD

**Issue by nektro** [llvm/llvm-project#60244]
clang version 15.0.7

```
$ touch empty.c

$ clang empty.c -fuse-ld='zig ld.lld'
error: invalid linker name in argument '-fuse-ld=zig ld.lld'
```

**Comment by LebedevRI** [comment]
Is there really a file named `zig ld.lld` (with space) ?

**Comment by nektro** [comment]
`zig` is the file (a program in path), `ld.ldd` is an argument

**Comment by MaskRay** [comment]
`-fuse-ld=` has overloaded semantics which makes it error-prone. `-fuse-ld=a/b` and `-fuse-ld=/a/b` are legacy and lead to a warning under `-Wextra`.

Use `--ld-path=/path/to/a b` if you want to have a space. https://github.com/bazelbuild/bazel/issues/13252

**Comment by nektro** [comment]
using `--ld-path='zig ld.lld'` also produces the same warning, so i will create the wrapper. thanks for the quick feedback :)
