### ISSUE TITLE
[instcombine] cmp no longer optimized

### ISSUE THREAD

**Issue by sftlbcn** [llvm/llvm-project#60242]
https://godbolt.org/z/zzbMjY1oG
```
bool test(int x, int y) { return (x < 0) == (y >= 0); }
```
ir llvm 14
```
define i1 @test14(i32 %0, i32 %1) {
  %3 = xor i32 %1, %0
  %4 = icmp slt i32 %3, 0
  ret i1 %4
}
```
ir trunk
```
define i1 @test(i32 %0, i32 %1) {
  %3 = lshr i32 %0, 31
  %4 = icmp sgt i32 %1, -1
  %5 = zext i1 %4 to i32
  %6 = icmp eq i32 %3, %5
  ret i1 %6
}
```

**Comment by rotateright** [comment]
We might have changed canonicalization on a sub-pattern, so we need to recognize this check-of-signbits-for-a-pair-of-values pattern.

**Comment by rotateright** [comment]
This example should be fixed with:
7cbfc39c77cafe925c0599ab121a67f94bf3870a

There are related patterns that are still not optimized though, so please do file more bugs if you are seeing them. I will try to improve the ones I am aware of either way.
