### ISSUE TITLE
getDiagnosticDocURI may generate dead links for ClangTidy

### ISSUE THREAD

**Issue by rillig** [llvm/llvm-project#60245]
The URLs for ClangTidy diagnostics have changed. For example, the actual URL for `bugprone-use-after-move` has a `/` instead of the first `-`.

https://clang.llvm.org/extra/clang-tidy/checks/bugprone-use-after-move.html (have)
https://clang.llvm.org/extra/clang-tidy/checks/bugprone/use-after-move.html (want)

Related to https://github.com/llvm/llvm-project/issues/60023.

**Comment by PiotrZSL** [comment]
Should be fixed by 4c106c93eb68f8f9f201202677cd31e326c16823
