### ISSUE TITLE
[OpenMP] old cuda plugin not working

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#60248]
I got error "Invalid plugin as necessary interface is not found" when not using nextgen plugin and nvidia
Due to missing implementation in the cuda plugin.
Run app with `LIBOMPTARGET_NEXTGEN_PLUGINS=0`
```console
$ grep -R __tgt_rtl_launch_kernel 
libomptarget/plugins/generic-elf-64bit/src/rtl.cpp:int32_t __tgt_rtl_launch_kernel(int32_t DeviceId, void *TgtEntryPtr,
libomptarget/plugins/amdgpu/src/rtl.cpp:int32_t __tgt_rtl_launch_kernel(int32_t DeviceId, void *TgtEntryPtr,
libomptarget/plugins/ve/src/rtl.cpp:int32_t __tgt_rtl_launch_kernel(int32_t DeviceId, void *TgtEntryPtr,
libomptarget/plugins/remote/src/rtl.cpp:int32_t __tgt_rtl_launch_kernel(int32_t DeviceId, void *TgtEntryPtr,
libomptarget/plugins-nextgen/common/PluginInterface/PluginInterface.cpp:int32_t __tgt_rtl_launch_kernel(int32_t DeviceId, void *TgtEntryPtr,
libomptarget/src/rtl.cpp:            DynLibrary->getAddressOfSymbol("__tgt_rtl_launch_kernel")))
```

**Comment by shiltian** [comment]
I'll remove the old plugins soon.

**Comment by ye-luo** [comment]
The release 16 must be fixed.

**Comment by ye-luo** [comment]
I would say since anyway release 16 must be fixed. It is low effort to apply the fix to main as well before deleting the old plugins. So my recommendation is fix the main and backport it to 16 release.

**Comment by shiltian** [comment]
Yeah, that is reasonable.

**Comment by shiltian** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/ad95b0e977506228155a3fd4f97635f56341800f

**Comment by shiltian** [comment]
Hmm, why I never made the back port right…

**Comment by tru** [comment]
@shiltian, in this case, automatic merging failed - so you need to create a fork and branch on your github repo, and fix the merge with `release/16.x` manually and then call `branch shiltian/llvm-project/mybranch`

**Comment by shiltian** [comment]
branch shiltian/llvm-project/PR60248

**Comment by shiltian** [comment]
@tru Looks like working now. Thanks for the explanation!
