### ISSUE TITLE
[flang] Compilation error (associate)

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#60247]
Test code:
https://github.com/gcc-mirror/gcc/blob/master/gcc/testsuite/gfortran.dg/associate_42.f90

Result (gfortran vs flang-new):
```console
$ gfortran associate_42.f90
$ ./a.out
$

$ flang-new -flang-experimental-exec associate_42.f90
error: Semantic errors in associate_42.f90
./associate_42.f90:25:7: error: The left-hand side of a pointer assignment is not definable
        point => tgt2
        ^^^^^^^^^^^^^
./associate_42.f90:25:7: because: 'point' is not a pointer
        point => tgt2
        ^^^^^^^^^^^^^
./associate_42.f90:20:16: Declaration of 'point'
      associate (point => obj%p)
```

**Comment by jeanPerier** [comment]
I believe gfortran test expectations are wrong here. The associating entity in an ASSOCIATE loses the POINTER (and ALLOCATBLE) attribute. Ifort also rejects this code.

See Fortran 2018 11.1.3.3 point 1: "_Within an ASSOCIATE, CHANGE TEAM, or SELECT TYPE construct. [...] The associating entity does not have the ALLOCATABLE or POINTER attributes; it has the TARGET attribute if and only if the selector is a variable and has either the TARGET or POINTER attribute._"
