### ISSUE TITLE
move_alloc does not support polymorphic or unlimited polymorphic descriptors

### ISSUE THREAD

**Issue by clementval** [llvm/llvm-project#60250]
The `RUNTIME_CHECK` is too restrictive for polymorphic and unlimited polymorphic descriptor.

```f90
module move_alloc_issue
  type p1
  end type
  type, extends(p1) :: p2
    integer, allocatable :: i
  end type
contains

  subroutine sub1
    class(*), allocatable :: up
    Call inner1

  contains
    subroutine inner1
      type(p2), allocatable :: tp2
      allocate(tp2)
      allocate(tp2%i)
      call move_alloc(tp2, up)
    end subroutine
  end subroutine
end module
program test
  use move_alloc_issue
  call sub1()
end program
```

```console
fatal Fortran runtime error(./dummy.f90:18): Internal error: RUNTIME_CHECK(to.type() == from.type()) failed at llvm-project/flang/runtime/allocatable.cpp(48)
./run_and_check.sh: line 14: 36287 Aborted                 ./a.out
```

**Comment by DavidTruby** [comment]
I'd be happy just removing this check, as it should be handled by semantic analysis anyway. What do you think?

**Comment by clementval** [comment]
> I'd be happy just removing this check, as it should be handled by semantic analysis anyway. What do you think?

I think we still need a check when one is unlimited polymorphic because the check cannot be done in semantic.

**Comment by DavidTruby** [comment]
I was having a look at this today; I am really struggling to work out what the semantics should be where the types are unlimited polymorphic and contained in arrays.
Should the runtime have to iterate the entire array and check each type in the array to see if it matches the type in the second array?
e.g. when we have `class(*) :: from(:)` and `class(p2) :: to(:)` should we have to check every type in `from` to check if it is type compatible to `to`?
FWIW I tried to test this with gfortran and it simply forbids it at semantic analysis. I agree that the standard doesn't say that we _should_ forbid this in sema but I also have no idea what the semantics become if we don't.

**Comment by clementval** [comment]
An unlimited polymorphic descriptor has only a single type at a time. So I think it is just important to check if the from `from` is compatible with `class(p2)` in this case.

**Comment by DavidTruby** [comment]
Ok, I understand the case where they are both scalars, but what `from` is an array? I thought an array of unlimited polymorphic variables could contain multiple distinct types at runtime; have I misunderstood that and every variable in the array has to have the same array type?

**Comment by clementval** [comment]
The array has a single type at runtime which can be an intrinsic type or a derived type. What you are describing could be achieved with smth like:

```
type :: element
  class(*), allocatable :: item
end type

type(element), allocatable :: array(:)
```

**Comment by klausler** [comment]
Can this bug be closed?  The test program above seems to work now.

**Comment by clementval** [comment]
Yes.
