### ISSUE TITLE
[llvm-bolt] Way to know whether the binary was converted by BOLT

### ISSUE THREAD

**Issue by corona10** [llvm/llvm-project#60253]
For example, CPython failed to pass the `test_gdb` if the binary is converted by BOLT and it's intended.
But it would be great if there is a way to know if the binary was converted by BOLT.

**Comment by corona10** [comment]
cc @@aaupov

**Comment by corona10** [comment]
https://github.com/llvm/llvm-project/blob/728d817becaa53cc9db1a440becc5c269a55ace2/bolt/lib/Rewrite/RewriteInstance.cpp#L461-L468

It looks like there is a section that can be a hint for it.

**Comment by aaupov** [comment]
```
readelf -p .note.bolt_info <executable> | grep BOLT
```

Example output:
```
  [    10]  BOLT revision: <unknown>, command line: /home/worker/bolt-worker2/bolt-x86_64-ubuntu-shared/build/bin/llvm-bolt /home/worker/bolt-worker2/bolt-x86_64-ubuntu-shared/build/tools/bolt/test/Output/re-optimize.test.tmp.exe -o /home/worker/bolt-worker2/bolt-x86_64-ubuntu-shared/build/tools/bolt/test/Output/re-optimize.test.tmp
```

**Comment by aaupov** [comment]
The section is added by default but can be omitted if `-bolt-info=0` is passed

**Comment by corona10** [comment]
Okay Thanks looks like it should be solved by reading self-binary :)
