### ISSUE TITLE
[flang] MOVE_ALLOC with the same actual passed to TO and FROM fails with "Invalid descriptor"

### ISSUE THREAD

**Issue by sscalpone** [llvm/llvm-project#60267]
This example calls the intrinsic `MOVE_ALLOC` passing the same variable to both actual arguments.  When the resulting code is executed, it generates a runtime error saying "Invalid descriptor".  All other compilers process this call as a no-op, except for GNU, which generates the following message at compile time:
```console
Error: The FROM and TO arguments at (1) violate aliasing restrictions (F2003 12.4.1.7)
```
The request is to clarify the runtime message.

Here's a small program the reproduces the problem:
```f90
program p
  real, allocatable :: a1(:)

  allocate(a1(0:10))
  call MOVE_ALLOC(a1,a1)
end
```

**Comment by DavidTruby** [comment]
What would your preference be here? I'm happy to either add a better error message or change this oppression operation to a noop. The standard explicitly forbids it which is why I added this check in the first place but I'm not wedded to forbidding it.

**Comment by sscalpone** [comment]
I like the check.  None of the other compilers that I tried enforce the check.

@psteinfeld What would you prefer?

**Comment by psteinfeld** [comment]
This is most likely a mistake from the user.  I think we should produce a user visible error when it happens.

Perhaps we should try to detect the cases at compile time where possible.  @klausler, what do you think about adding a compile time check in cases where we determine that both arguments are identical?

**Comment by klausler** [comment]
Not a great idea to have a specific `MOVE_ALLOC` check in the compiler, which can't catch all cases (`CALL MOVE_ALLOC(X(J)%A, X(K)%A)`), and the cases that could be caught at compilation time are less likely to appear in real codes than in artificial tests.  But if somebody wanted to do a general aliasing rule violation checker for callers of explicit interfaces, that would also handle this case too as well as it could be, and might be worth the effort.

**Comment by DavidTruby** [comment]
I believe this has been fixed by https://reviews.llvm.org/D142899
Thanks!
