### ISSUE TITLE
Imaginary types are not supported, violating ISO C Annex G

### ISSUE THREAD

**Issue by Keith-S-Thompson** [llvm/llvm-project#60269]
This program:
```c
#include <stdio.h>
#include <complex.h>
int main(void) {
#ifdef __STDC_IEC_559_COMPLEX__
    printf("__STDC_IEC_559_COMPLEX__ is defined as %d\n", __STDC_IEC_559_COMPLEX__);
#else
    printf("__STDC_IEC_559_COMPLEX__ is NOT defined\n");
#endif

#ifdef _Imaginary_I
    printf("Imaginary types are supported\n");
#else
    printf("Imaginary types are NOT supported\n");
#endif
}
```
compiled with `clang -Wall -Wextra -std=c11 -pedantic-errors` (llvm version 15.0.0) produces this output:
```console
__STDC_IEC_559_COMPLEX__ is defined as 1
Imaginary types are NOT supported
```

ISO C Annex G was informative in C99, but was made normative in C11. 
Imaginary types are optional in C11, but are mandatory for any
implementation that predefines `__STDC_IEC_559_COMPLEX__`.
(Complex types were made optional in C11, but that's not relevant here.)

To conform to C11 (and later), clang should either implement imaginary types
as defined in Annex G or remove the definition of `__STDC_IEC_559_COMPLEX__`.

**Comment by shafik** [comment]
CC @AaronBallman

**Comment by Keith-S-Thompson** [comment]
gcc equivalent:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108531

**Comment by Keith-S-Thompson** [comment]
FYI, I've sent an email to the C standard editors (the addresses at
the top of the N3054 draft) suggesting that imaginary number support
should be optional even if `__STDC_IEC_559_COMPLEX__` and
`__STDC_IEC_60559_COMPLEX__` are defined.

It's probably too late to make such a change in C23.

(`__STDC_IEC_60559_COMPLEX__` is replacing `__STDC_IEC_559_COMPLEX__`,
which is obsolescent.)

**Comment by Keith-S-Thompson** [comment]
Since the definition comes from glibc's `stdc-predef.h` header, `__STDC_IEC_60559_COMPLEX__ ` is defined if and only if any C standard header is included. (I'm assuming that all C standard headers implicitly include `std-predef.h`; I haven't verified that).

That's pretty clearly a bug in glibc.

For example, this program:
```
int main(void) {
#ifdef __STDC_IEC_60559_COMPLEX__
    return 0;
#else
    return 1;
#endif
}
```
returns with a status of 1, indicating that `__STDC_IEC_60559_COMPLEX__` is not defined. If I add `#include <stdio.h>`, it returns a status of 0.

(And this would not affect implementations that use clang with a library implementation other than glibc.)

**Comment by thesamesam** [comment]
> Since the definition comes from glibc's `stdc-predef.h` header, `__STDC_IEC_60559_COMPLEX__ ` is defined if and only if any C standard header is included. (I'm assuming that all C standard headers implicitly include `std-predef.h`; I haven't verified that).
> 

They do not. See https://reviews.llvm.org/D137043 and https://bugs.gentoo.org/870001.

**Comment by Keith-S-Thompson** [comment]
My assumption was meant to apply only to glibc-based implementations. I probably didn't make that clear enough.

The idea that non-glibc-based implementations should have all C sources files implicitly include a glibc-provided header seems ... odd. (There's some discussion in the bug reports linked from the previous comment. I haven't read them in enough depth to offer an opinion.)

**Comment by thesamesam** [comment]
musl has `std-predef.h`, it's not a solely-glibc-provided header, and the issues then manifest on other libcs for other defines (like __STDC_IEC_559__) as Aaron pointed out. It's a fuzzy area that we don't seem to handle well at the moment.

**Comment by AaronBallman** [comment]
Yeah, the trouble is deciding whose bug it is. It could be argued this is a glibc bug (as you did), it could be argued this is a Clang bug (we could be defining the proper macros to work with glibc, in theory), it could be argued this is a standards bug (the standard refuses to admit existing implementation practice where the standard library and the compiler are decoupled), etc.

**Comment by AaronBallman** [comment]
Note, support for imaginary types was removed from Annex G for C2y as part of: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3274.pdf

**Comment by cor3ntin** [comment]
With the complete removal of _Imaginary in #97436 , I think we can close this
