### ISSUE TITLE
Do not use backticks in assertion failures

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#60279]
Assertion failures print messages like

> Assertion `I != ValueState.end() && "V not found in ValueState nor Paramstate map!"' failed.

Because the quoting style uses \` as the opening quote (and then ' as the closing quote), this behaves poorly when pasting messages into anything that uses markdown. Rather than trying to emulate "smart quotes", we should just use ' to open the quote as well.

**Comment by AaronBallman** [comment]
This is an issue with the C Standard Library, which is outside of the control of Clang. See glibc source: https://sourceware.org/git/?p=glibc.git;a=blob;f=assert/assert.c;h=b7c7a4a1ba31087ad3d0c33bc7edff27d513914c;hb=HEAD#l101
