### ISSUE TITLE
[llvm-link] Crash on linking global_ctors without opaque pointers

### ISSUE THREAD

**Issue by Dinistro** [llvm/llvm-project#60287]
`llvm-link` runs into verification errors when linking two files with `global_ctors` that do not use opaque pointers.

Executing `llvm-link --opaque-pointers=0 f0.ll f1.ll` (see files further down) results in the following crash:

```console
invalid uses of intrinsic global variable
[2 x { i32, void ()*, i8* }]* @llvm.global_ctors
./bin/llvm-link: error: linked module is broken!
```

**Files:**

`f0.ll`:
```llvm
@llvm.global_ctors = appending global [1 x { i32, void()*, i8* }] [{ i32, void()*, i8* } { i32 0, void()* @foo, i8* null }]

define void @foo() {
  ret void
}
```

`f1.ll`:
```llvm
@llvm.global_ctors = appending global [1 x { i32, void()*, i8* }] [{ i32, void()*, i8* } { i32 0, void()* @bar, i8* null }]

define void @bar() {
  ret void
}
```

---

git bisect indicates that this crash starts to occur since b67c16ff6af557174e498d6d82df9936e333f3d6 by @arsenm. However, this commit only adds a verifier that checks an assumption used all over the place, so this is not the root cause of this problem. Note that the commit message even indicates that there were some unexpected problems. 

After some debugging, I found out that the introduced bitcasts in `IRLinker::linkAppendingVarProto` seem to stick around, even though they should have no usages . 

See: https://github.com/llvm/llvm-project/blob/117ecdd5789e6efd28505a8b84680020fd935cd1/llvm/lib/Linker/IRMover.cpp#L975 https://github.com/llvm/llvm-project/blob/117ecdd5789e6efd28505a8b84680020fd935cd1/llvm/lib/Linker/IRMover.cpp#L986

I tried to address this issue by avoiding these bitcasts for magic globals (`llvm.global_ctors` and `llvm.global_dtors`) but I'm getting issues with unmaterialized values in tests using `llvm-lto`.

**Comment by arsenm** [comment]
I debugged the same issues initially. After the change to auto upgrade all bitcode to opaque pointers it stopped mattering. Does your example work if you simply assemble with old llvm-as and link with new llvm-link?

**Comment by Dinistro** [comment]
We use both `llvm-as` and `llvm-link` from HEAD, but we explicitly deactivate opaque pointers. While activating opaque pointers does not trigger the bug, it points to a fundamental issue in the handling of globals with appending linkage. As you noted in your commit message, only appending linkage only makes sense for magic globals, so being forced to use RAUW seems odd. Still, I do not understand why other tests break when I remove the bitcasts only for magic globals.

**Comment by arsenm** [comment]
The casts are an implementation detail for the linker that in principle shouldn't be inserted. But since this is a typed pointer issue, this isn't getting fixed. I'd consider a patch to revert  b67c16f from the 16 release branch, but tip of tree should start removing the code to handle the pointer casts

**Comment by Dinistro** [comment]
Given that opaque pointers should still be supported in the 16 release that makes sense to me. As we are working directly with HEAD, we will have to prioritise the move to opaque pointers.

**Comment by arsenm** [comment]
I filed #60298 to revert this for the release branch
