### ISSUE TITLE
[flang] incorrect result (mvbits)

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#60302]
Test code:
https://github.com/gcc-mirror/gcc/blob/master/gcc/testsuite/gfortran.dg/mvbits_4.f90

Result (gfortran vs flang-new)
```console
$ gfortran mvbits_4.f90
$ ./a.out
 17 18 11  4 13 22  7 16  9 18
 17 18 11  4 13 22  7 16  9 18
 17 18 11  4 13 22  7 16  9 18

$ flang-new -flang-experimental-exec mvbits_4.f90
$ ./a.out
 17 18 11 36 77 22 39 16 41 18
Fortran STOP: code 1
```

**Comment by k-arrows** [comment]
still reproducible with recent flang-new:
```console
$ flang-new -flang-experimental-exec mvbits_4.f90
$ ./a.out
 17 18 11 36 77 22 39 16 41 18
Fortran STOP: code 1
$ flang-new --version
flang-new version 17.0.0 (https://github.com/llvm/llvm-project.git 5679379cc7df198a73c137e69134608833ffff8f)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

Now llvm-test-suite also catches this failure, but it has not been confirmed as a bug or a result of unimplemented features.
https://github.com/llvm/llvm-test-suite/blob/2666b1f4b90b0f0157f33f5a13d19f6206abebb0/Fortran/gfortran/regression/CMakeLists.txt#L1726

**Comment by kiranchandramohan** [comment]
There is a bug here and it is likely in lowering. Using the same array or different arrays as the source and destination do not seem to cause issues. It is likely the usage of the vector array that is causing the difference. 

The relevant portion of the test is the following.

```
  integer, dimension(10) :: ila1 = (/1,2,3,4,5,6,7,8,9,10/)
  integer, parameter :: SHOULD_BE(10) = (/17,18,11,4,13,22,7,16,9,18/)
  integer, parameter :: INDEX_VECTOR(10) = (/9,9,6,2,4,9,2,9,6,10/)

  call mvbits (ila1(INDEX_VECTOR), 2, 4, ila1, 3)
  write (*,'(10(I3))') ila1
  if (any (ila1 /= SHOULD_BE)) STOP 1

  end
  ```

**Comment by k-arrows** [comment]
> It looks like there is no temporary that is used for the operand arrays of the `MVBITS` intrinsic. Hence if we use the same array but with differing indices (as would be the case here because of the index_vector), we will end up using the updated value rather than the original value in the computation.

I have understood thanks to your explanation. The following should be self-explanatory for you, so please ignore it.
I will write it down to help myself understand.

MVBITS(FROM, 2, 4, TO, 3) moves 4 bits from positions 2 through 5 of FROM to positions 3 through 6 of TO. Consider the computation of ila1(4). It should be processed as follows. Only the lower 6bits are shown in the table.

|  FROM  |  TO  |  MVBITS(FROM, 2, 4, TO, 3)  |  
| ---- | ---- | ---- |
|  000010  | 000100  | 000100 |

In fact, since flang-new mistakenly uses the updated ila(2) instead of the original ila(2) as FROM, it is processed as follows.

|  FROM  |  TO  |  MVBITS(FROM, 2, 4, TO, 3)  |  
| ---- | ---- | ---- |
|  010010  | 000100  | 100100 |

**Comment by kiranchandramohan** [comment]
Confirmed that this is fixed by the HLFIR flow.

```
$ flang-new -flang-experimental-hlfir mvbits_4.f90 
$ ./a.out 
 17 18 11  4 13 22  7 16  9 18
 17 18 11  4 13 22  7 16  9 18
 17 18 11  4 13 22  7 16  9 18
```

**Comment by k-arrows** [comment]
The `-flang-experimental-hlfir` option is now the default, and I think this issue is obsolete. I will close this issue.
