### ISSUE TITLE
[NVPTX] No output from `ptxas` when compiling with `--target=nvptx64-nvidia-cuda`

### ISSUE THREAD

**Issue by jhuber6** [llvm/llvm-project#60301]
Recently we added support for directly targeting the `nvptx` architecture via cross-compilation. There's a bug that causes the output from `clang foo.c -c --target=nvptx64-nvidia-cuda` to be removed as a temp file. This is because of erroneous comparison of `const char *` values instead of string comparisons.

**Comment by tru** [comment]
Reopen until it has landed in release branch. Please create a PR with the `/cherry-pick` command to queue it for inclusion.

**Comment by jhuber6** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/11656f204aa5fd972564e76641c00ca058ba8c0d

**Comment by jhuber6** [comment]
@tru Any clue why https://github.com/llvm/llvm-project/commit/11656f204aa5fd972564e76641c00ca058ba8c0d is failing? I don't see any artifacts in the action.

**Comment by jhuber6** [comment]
Seems so, the diff applied cleanly here so I don't know what the previous problem was. Let's try again.

/branch jhuber6/llvm-project/Issue60301
