### ISSUE TITLE
dsymutil produces broken lines info (probably) with LTO on mac

### ISSUE THREAD

**Issue by glandium** [llvm/llvm-project#60307]
Bisect says this started with 8bb4451a651ac00432d04e020d83f43c445aaebb. Cc @adrian-prantl, @avl-llvm 

Testcase 1 (produced with ld64):
- Download and extract https://drive.google.com/file/d/10ylLkhdTl-_eA4VOFDI4GvOwP7t9BDA0/view?usp=sharing (sorry, I didn't reduce the testcase)
- Change working directory to the extracted `testcase` directory
- Run `dsymutil XUL --user-reproducer .`
- Run `llvm-addr2line -pCfi -e XUL.dSYM/Contents/Resources/DWARF/XUL 0x17e6880`
Expected output:
```
XRE_InitChildProcess(int, char**, XREChildData const*) at /builds/worker/checkouts/gecko/toolkit/xre/nsEmbedFunctions.cpp:262
```
Actual output:
```
XRE_InitChildProcess(int, char**, XREChildData const*) at ??:0
```

Testcase 2 (same build as Testcase 1, but relinked with lld)
- Download and extract https://drive.google.com/file/d/1T4mM0iOEvFnLAB4-MD1KORkxy5Rpvpug/view?usp=sharing (sorry, I didn't reduce the testcase)
- Change working directory to the extracted `testcase` directory
- Run `dsymutil XUL --user-reproducer .`
- Run `llvm-addr2line -pCfi -e XUL.dSYM/Contents/Resources/DWARF/XUL 0x1109ed4`
Expected output:
```
XRE_InitChildProcess(int, char**, XREChildData const*) at /builds/worker/checkouts/gecko/toolkit/xre/nsEmbedFunctions.cpp:262
```
Actual output:
```
mozilla::LazyLogModule::operator mozilla::LogModule*() at /builds/worker/fetches/MacOSX11.3.sdk/usr/include/c++/v1/atomic:990
 (inlined by) GetNSS3Directory(nsTString<char>&) at /builds/worker/checkouts/gecko/security/manager/ssl/nsNSSComponent.cpp:978
 (inlined by) ListPossibleLoadableRootsLocations(mozilla::Vector<nsTString<char>, 0ul, mozilla::MallocAllocPolicy>&) at /builds/worker/checkouts/gecko/security/manager/ssl/nsNSSComponent.cpp:998
 (inlined by) XRE_InitChildProcess(int, char**, XREChildData const*) at /builds/worker/checkouts/gecko/security/manager/ssl/nsNSSComponent.cpp:1944
```
This output actually looks doubly broken (the inlining info is bogus).

In both cases, a build of clang 15's dsymutil with 8bb4451a651ac00432d04e020d83f43c445aaebb reverted produces the expected output.

(this affects both 15 and trunk)

**Comment by avl-llvm** [comment]
will take a look.

**Comment by dwblaikie** [comment]
This sounds like more of an LLD issue, than an LTO/dsymutil issue? Or was LTO not used with ld64 but was used with lld? (Perhaps a more apples-to-apples comparison would be helpful - one linker  (either ld64 or lld) with/without LTO?)

**Comment by glandium** [comment]
All the .o were unchanged between the two links. The only option changed on the clang link command line is -fuse-ld=ld vs -fuse-ld=lld.

**Comment by glandium** [comment]
Let me be clear: the problem appears in both, but because lld does things different, the broken output is different.

**Comment by glandium** [comment]
And for both cases, reverting 8bb4451a651ac00432d04e020d83f43c445aaebb fixes the problem.

**Comment by avl-llvm** [comment]
The 8bb4451 introduces possibility to unite overlapped or adjacent address ranges.
The AddressRangesMap keeps address ranges and value of relocated address.
The AddressRangesMap should not unite adjacent address ranges with different relocated addresses.
Current AddressRangesMap unites following into single range:

`{0,24,17e685c} {24,d8,55afe20} -> {0,d8,55afe20}`

**Comment by dwblaikie** [comment]
> Let me clarify: the problem appears in both, but because lld does things different, the broken output is different.

Ah, I see - sorry for the confusion. Thanks for explaining!

**Comment by avl-llvm** [comment]
https://reviews.llvm.org/D142936

**Comment by glandium** [comment]
Can you nominate this for a backport for 16.0.1?

**Comment by avl-llvm** [comment]
done https://github.com/llvm/llvm-project/issues/61564
