### ISSUE TITLE
[OpenMP] kernel performance regression on AMDGPU

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#60300]
regression caused by 5d1dc9fa043f8ee239cbc16347025a4f0831e132

Using https://github.com/ye-luo/miniqmc testing commit 6f526b6062682ec892fb02d2919484c8b4db0875

```shell
mkdir build_llvm_offload_real; cd build_llvm_offload_real
cmake -DCMAKE_CXX_COMPILER=clang++ -DENABLE_OFFLOAD=ON -DOFFLOAD_TARGET=amdgcn-amdhsa -DOFFLOAD_ARCH=gfx906 ..
make -j32 check_spo_batched; OMP_NUM_THREADS=8 rocprof --stats ./bin/check_spo_batched -m 2 -g "2 2 1" -w 80 -n 1
cat results.stats.csv
```

```
"Name","Calls","TotalDurationNs","AverageNs","Percentage"
"__omp_offloading_10304_1c0438c__ZN11qmcplusplus17einspline_spo_ompIfE18multi_evaluate_vghERKSt6vectorIPNS_6SPOSetESaIS4_EERKS2_IPNS_11ParticleSetESaISA_EEib_l406.kd",1536,320975426,208968,99.85018277279889
```
time 320975426 is much larger than previous one 192408385

**Comment by ye-luo** [comment]
Adding `CMAKE_CXX_FLAGS=-foffload-lto`, I got 320684008.

**Comment by jdoerfert** [comment]
@jhuber6 will fix this and backport it.

**Comment by jhuber6** [comment]
Please backport 6185246f4f62345d0cfdaef62da7e15b01d52557 and 0bdde9dfb9b1dbfabee147c196db820e1f5dca1f.

**Comment by tstellar** [comment]
/cherry-pick 6185246f4f62345d0cfdaef62da7e15b01d52557 0bdde9dfb9b1dbfabee147c196db820e1f5dca1f
