### ISSUE TITLE
surprise with the Fortran preprocessor

### ISSUE THREAD

**Issue by mfvalin** [llvm/llvm-project#60317]
the flang-new preprocessor substitutes macros inside of a #include <filename> directive
#define IgnoreTypeKindRank zz
#include <rmn/IgnoreTypeKindRank.hf>
produced
#include <rmn/zz.hf>
different from the usual behavior of gfortran/pgfortran/flang(old)/xlf/ifort/ifx
i am curious about the rationale for this feature

**Comment by klausler** [comment]
There is no rationale, it's a bug.

**Comment by pscoro** [comment]
If the problem is just that #include directives shouldn't be run through macro replacement then this https://reviews.llvm.org/D143606 should be all thats needed to fix the issue.
