### ISSUE TITLE
Confusing error messages about non-literal types being used in constant expressions

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#60311]
Consider this example code:
```c++
class Base {
public:
  virtual ~Base() {}
};
constexpr int test() {
  Base b;
  return 0;
}
```

`clang -std=c++20` complains:
```console
<source>:8:8: error: variable of non-literal type 'Base' cannot be defined in a constexpr function before C++2b
  Base b;
       ^
<source>:3:11: note: 'Base' is not literal because its destructor is not constexpr
  virtual ~Base() {}
          ^
1 error generated.
```

However, using `-std=c++2b` instead gives:
```console
<source>:7:15: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
constexpr int test() {
              ^
<source>:8:8: note: non-literal type 'Base' cannot be used in a constant expression
  Base b;
       ^
1 error generated.
```
See: https://godbolt.org/z/aEbYKxfjT

**Comment by shafik** [comment]
I think clang is just being more aggressive in diagnosing that `test()` can never be used in a constant expression, see this godbolt: https://godbolt.org/z/xcsEY98sf where I add `constexpr` to the variable declaration of `b`.

The error message could be improved.

**Comment by tbaederr** [comment]
Right, but why is is saying that part about using C++2b? Are non-literal types allowed in constexpr functions in C++2b or not?
