### ISSUE TITLE
[Clang] Enable `-fdata-sections` and `-ffunction-sections` automatically in Clang

### ISSUE THREAD

**Issue by 3119369616** [llvm/llvm-project#60331]
Is it possible to turn on `-fdata-sections` and `-ffunction-sections` automatically in Clang? And is it possible to turn on `--gc-sections` in LLD? Up to now, these flags must be given manually.
In my advice,
```bash
clang -c example.c -o example.o
```
should be the same as
```bash
clang -c -fdata-sections -ffunction-sections example.c -o example.o
```

**Comment by thesamesam** [comment]
Could also put them in `/etc/clang` in the config files.

**Comment by MaskRay** [comment]
This feature request can be achieved with https://clang.llvm.org/docs/UsersManual.html#configuration-files . As others might imply, I don't think it is a good idea to add more cmake options to toggle such behaviors.
