### ISSUE TITLE
if-conversion creating dead references to removed MachineBasicBlocks in INLINEASM_BR

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#60346]
via @arndb :
```c
_Bool arch_static_branch_branch;

inline _Bool arch_static_branch() {
  asm goto(".word b, %l[l_yes], %c0\n\t"
           :
           : "i"(&arch_static_branch_branch)
           :
           : l_yes);
  return 0;
l_yes:
  return 1;
}

void __dynamic_dev_dbg(char *, ...);
static void tusb1210_chg_det_set_type(int type) {
  if (arch_static_branch())
    __dynamic_dev_dbg("", type);
}

void tusb1210_chg_det_work(char v) {
  if (v)
    tusb1210_chg_det_set_type(1);
  else
    tusb1210_chg_det_set_type(0);
}
```
`-O2 --target=arm-linux-gnueabi` produces an invalid `.long   ".LBB0_-1"` where before it would produce `.long   .Ltmp2`.

Bisection converged on https://reviews.llvm.org/D130316.

This specific test case seems specific to the arm backend; x86 and aarch64 don't repro.  Will dig more next week.

cc @nikic @bwendling @efriedma-quic @jyknight

**Comment by nickdesaulniers** [comment]
branch-folder combines the then/else branches. if-converter (my nemesis) blows away the indirect destination leaving a dangling reference behind.

**Comment by nickdesaulniers** [comment]
I don't think this was a regression from https://reviews.llvm.org/D130316; if-conversion looks broken for the above even before https://reviews.llvm.org/D130316 landed.  Before https://reviews.llvm.org/D130316 (ie. at 1c9f0408bc0f), we produce:
```asm
...
tusb1210_chg_det_work:
...
	.long	.Ltmp0
...
.Ltmp0:                                 @ Address of block that was removed by CodeGen
...
```
That said, we should still fix if-conversion!

**Comment by efriedma-quic** [comment]
Maybe see the change to llvm/lib/CodeGen/BranchFolding.cpp in https://reviews.llvm.org/D102817 ?  Just blindly guessing, though.

**Comment by nickdesaulniers** [comment]
> Maybe see the change to llvm/lib/CodeGen/BranchFolding.cpp in https://reviews.llvm.org/D102817 ? Just blindly guessing, though.

That might fix it, but I suspect it might be papering over a deeper issue. I'll comment on that change once I have a more complete understanding of the issue though.

It does look like perhaps `IfConverter::IfConvertDiamond` is drawing a `INLINEASM_BR`s from then/else into the top of the diamond, without updating the successor list correctly. This leads branch folding to think that the `machine-block-address-taken, inlineasm-br-indirect-target` indirect target has no predecessors and is dead.

https://reviews.llvm.org/D102817 change to `BranchFolder::OptimizeBranches` just says "don't do that to `machine-block-address-taken` blocks, even if their preds list is empty."  My question is "well, why the preds list empty? That looks wrong."

**Comment by efriedma-quic** [comment]
I think that change was addressing an issue where the pred list was legitimately dead to to other optimizations.  If it isn't actually dead here, there's probably some other underlying issue, yes.

**Comment by nickdesaulniers** [comment]
Right, it's not dead.

I suspect that `IfConverter::MergeBlocks` needs to check whether `FromMBB.mayHaveInlineAsmBr()` and update the successor list accordingly.

**Comment by nickdesaulniers** [comment]
1. [precommit test for pr60346](https://reviews.llvm.org/D142923)
2. [[llvm][IfConversion] update successor list when merging INLINEASM_BR](https://reviews.llvm.org/D142924)

**Comment by nickdesaulniers** [comment]
/cherry-pick 1cecfa407c1a1a114d75c8b85fbe97e4c1275c1f 07c7784d7bf69b9944b92ecc283cac823bcfce16
