### ISSUE TITLE
Add a needs-reduction label

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#60343]
I'd like us to tag issues that have massive reproducers with `needs-reduction`. I think this gives pertinent information to folks triaging issues that more work is needed before the issue is likely to be acted on and also helps reporters understand if they can help "bump" an issue to get it looked at sooner.

The idea is to add this label to an issue if the only way to reproduce the bug requires a significantly large amount of preprocessed source code (including non-preprocessed bugs with nontrivial `#include` directives like pulling in STL or OS headers). I think it's fine to leave "significantly large" up to the person triaging the report rather than trying to nail it down concretely.

**Comment by tstellar** [comment]
This is fine with me.  I think anyone with commit access can create a label.

**Comment by AaronBallman** [comment]
> This is fine with me. I think anyone with commit access can create a label.

They can (unfortunately), but we have a documented process (https://www.llvm.org/docs/BugLifeCycle.html#maintenance-of-metadata) for adding new labels to try to reduce the amount of label spam.

I've gone ahead and added this label and will close this issue. Thanks!
