### ISSUE TITLE
clang-cl incorrectly replaces strrchr to (abscent on windows/MS toolchain) memrchr

### ISSUE THREAD

**Issue by virt00l** [llvm/llvm-project#60340]
Repro-ed on clang-cl version `15.0.7` + link vc std lib of vc2019 (16.10.3, cl.exe output is `19.29.30038.1`)
Sorry, about not following bug report guidelines properly, doesn't have time to do it properly right now, but I believe that bug should be self-evident ? 
Please, ping be back if you need more details.
@msebor @nikic 
PS: I guess that  https://github.com/llvm/llvm-project/commit/0d68ff87d2b03522ac43646a491d731586518e4c might have to do with this

**Comment by nikic** [comment]
This has already been fixed by https://github.com/llvm/llvm-project/commit/4f30c5808a49ba85b052cb65bbe7b34109187bad. That probably should have been backported to clang 15, but that release cycle is closed now and this will be part of clang 16.
