### ISSUE TITLE
[AVR] Do not emit a default `-Tdata` option to the linker when a user script is specified

### ISSUE THREAD

**Issue by benshi001** [llvm/llvm-project#60362]
We usually emit a default `-Tdata` option in the Clang driver, to help user set SRAM's start address according to each individual AVR device. 

However if a user linker script is specifed, we should not do that and follow the user's willing.

**Comment by sprintersb** [comment]
There's two types of linker script: One that specifies the comptete story, and one that's just some augmentation with, say, `INSERT BEFORE <section>` at the end.

**Comment by benshi001** [comment]
> There's two types of linker script: One that specifies the comptete story, and one that's just some augmentation with, say, `INSERT BEFORE <section>` at the end.

Clang driver can not check such complex case. It it up to the user to make sure the correctness. At least, user can specify both a linker script and a `-Tdata` for the second case you mentioned.

**Comment by benshi001** [comment]
As discussed in https://reviews.llvm.org/D142595, the clang driver can not know a linker script passed via `-Wl,-T,xx.lds`.

So the best solution may be: Use the default linker script provided by avr-libc, which will be overwritten by user's specification.
