### ISSUE TITLE
clang-format option request: function parameter ALWAYS one per line

### ISSUE THREAD

**Issue by HantaoPan** [llvm/llvm-project#60360]
I would like to have the option in clang-format which ALWAYS puts one parameter per line for a function declaration, even if they are short enough to be fit in one line!

Prospective solution: adding a `Never` in `BinPackParameters`, other than `false` and `true`. 

Expecting effect,
```c
int add(int a,
        int b,
        int c)
{
    return a + b + c;
} 
```

**Comment by Stadly** [comment]
This would be solved with #62676, as we could set `ParameterList::Pack: Never`.

**Comment by Stadly** [comment]
No, #62676 is still work in progress.

**Comment by owenca** [comment]
You can use `BinPackParameters: AlwaysOnePerLine` now.
