### ISSUE TITLE
Clang on Windows didn't initialize __thread variable

### ISSUE THREAD

**Issue by YWtheGod** [llvm/llvm-project#60382]
test program test.c :
```
#include <stdio.h>
static __thread int a = 100;
int main()
{
    printf("Hello, World!\n");
    printf("%d\n",a);
    return 0;
}
```
compiled with
`clang -target x86_64-w64-windows-gnu test.c -o test_gnu.exe`
compile and link successfully, but test_gnu.exe hung when accessing variable a since a didn't get initialized

compiled with
`clang -target x86_64-pc-windows-msvc test.c -o test_msvc.exe`
test_msvc.exe run successfully, value of a get printed.

compiled and run with gcc without any problem.

same llvm source build in linux can run same test program without any problem.
[test.zip](https://github.com/llvm/llvm-project/files/10534899/test.zip)

**Comment by alvinhochun** [comment]
I cannot reproduce this using [llvm-mingw](https://github.com/mstorsjo/llvm-mingw). The test program runs, prints `100` and exits normally. Which Clang build and mingw-w64 toolchain are you using?

(It may have to do with Clang using native TLS by default and most if not all GCC-based toolchains using emulated TLS.)

**Comment by YWtheGod** [comment]
@alvinhochun I just pull the llvm-project repo and build from souce today, don't know how to descript what build it is
some more test:
I compile the test.c to test_gcc.o with gcc compiler
and link it with clang:
`clang -target x86_64-w64-windows-gnu test_gcc.o -o test_gcc.exe`
got linker errors:
```
D:/MSYS64/MINGW64/BIN/ld: D:/MSYS64/MINGW64/lib/gcc/x86_64-w64-mingw32/12.2.0/libgcc_eh.a(emutls.o):(.text+0x5e): undefined reference to `pthread_mutex_init'
D:/MSYS64/MINGW64/BIN/ld: D:/MSYS64/MINGW64/lib/gcc/x86_64-w64-mingw32/12.2.0/libgcc_eh.a(emutls.o):(.text+0x71): undefined reference to `pthread_key_create'
D:/MSYS64/MINGW64/BIN/ld: D:/MSYS64/MINGW64/lib/gcc/x86_64-w64-mingw32/12.2.0/libgcc_eh.a(emutls.o):(.text+0xad): undefined reference to `pthread_getspecific'
D:/MSYS64/MINGW64/BIN/ld: D:/MSYS64/MINGW64/lib/gcc/x86_64-w64-mingw32/12.2.0/libgcc_eh.a(emutls.o):(.text+0xf7): undefined reference to `pthread_once'
D:/MSYS64/MINGW64/BIN/ld: D:/MSYS64/MINGW64/lib/gcc/x86_64-w64-mingw32/12.2.0/libgcc_eh.a(emutls.o):(.text+0x106): undefined reference to `pthread_mutex_lock'
D:/MSYS64/MINGW64/BIN/ld: D:/MSYS64/MINGW64/lib/gcc/x86_64-w64-mingw32/12.2.0/libgcc_eh.a(emutls.o):(.text+0x11b): undefined reference to `pthread_mutex_unlock'
D:/MSYS64/MINGW64/BIN/ld: D:/MSYS64/MINGW64/lib/gcc/x86_64-w64-mingw32/12.2.0/libgcc_eh.a(emutls.o):(.text+0x157): undefined reference to `pthread_setspecific'
D:/MSYS64/MINGW64/BIN/ld: D:/MSYS64/MINGW64/lib/gcc/x86_64-w64-mingw32/12.2.0/libgcc_eh.a(emutls.o):(.text+0x220): undefined reference to `pthread_setspecific'```
Add a -pthread options like this:
`clang -target x86_64-w64-windows-gnu -pthread test_gcc.o -o test_gcc.exe`
linking successed. and success on running too, got the value 100 printed.
but 
`clang -target x86_64-w64-windows-gnu -pthread test.c -o test_gnu.exe`
compiled and linked successfully, and failed on running, hung.
link the test_gnu.o with gcc:
`gcc test_gnu.o -o test_gnu.exe`
linked successfully, but also failed on running, hung.
so it's quite sure that something wrong with the test_gnu.o file. linking might be OK.

**Comment by alvinhochun** [comment]
Okay, so you are using a self-built Clang on MSYS2 with the MINGW64 environment, which is GCC-based. You will need to pass `-femulated-tls` to Clang to have it emit code that uses emulated TLS. (I believe the mingw-w64-clang package in MSYS2 for the GCC-based environments is patched to enable this by default, so it doesn't have the same problem.)

Alternatively, you may want to consider using the CLANG64 environment instead. The libraries in there use native TLS.

**Comment by YWtheGod** [comment]
@alvinhochun -femulated-tls works thanks a lot!

**Comment by alvinhochun** [comment]
If you use the CLANG64 environment you have to recompile everything with clang. Reusing objects or static libraries built with GCC will give you plenty of headaches.
