### ISSUE TITLE
[AArch64] [iOS]  'apple-m1' is not a recognized processor for this target

### ISSUE THREAD

**Issue by DaydreamCoding** [llvm/llvm-project#60404]
When I use LLVM-15 with Mesa on iOS, fatal error: 

```console
'apple-m1' is not a recognized processor for this target (ignoring processor)

LLVM ERROR: 64-bit code requested on a subtarget that doesn't support it!
```

![WX20230130-221036@2x](https://user-images.githubusercontent.com/22166516/215676232-ec5bc39a-cf1d-40b7-ad4f-35a6fb02c1d2.png)

**Comment by efriedma-quic** [comment]
The error message is saying that the code is trying to compile with an x86_64 triple, but specifying target features that indicate the CPU isn't 64-bit.

It's not clear LLVM is doing anything wrong here.  I'd suggest filing a bug report against Mesa.
