### ISSUE TITLE
Invalid assembly generated with infinite loop

### ISSUE THREAD

**Issue by sagittarius-a** [llvm/llvm-project#60419]
## Minimal test-case

```c
#include <stdio.h>

#define DO_WAIT 0
#define DO_ACTION 1

int g_lock = DO_WAIT;

void __attribute__((noinline)) worker() {
  for (;;) {

    puts("worker");
    g_lock = DO_WAIT;

    while (g_lock != DO_ACTION) {
    }

    puts("Action");
  }
  return;
}

void dontcallme() { puts("Don't call me"); }

int main() {
  worker();
  return 0;
}
```

The bug occurs when using any optimization level different than `0`.

## Issue description

**Note:** it seems the bug can be reproduced *as is* on x86 only. Still, assembly generated on ARM is invalid.

The assembly generated for the `worker` function does not include the loop waiting for the proper `g_lock` value, and the associated code. Moreover, no epilogue is generated for the function.

An observable side-effect is that the instructions following the function will be unconditionally executed.

```s
$ objdump -dM intel /tmp/bug
[...]
0000000000001160 <worker>:
    1160:       50                      push   rax
    1161:       48 8d 3d 9c 0e 00 00    lea    rdi,[rip+0xe9c]        # 2004 <_IO_stdin_used+0x4>
    1168:       e8 c3 fe ff ff          call   1030 <puts@plt>
    116d:       0f 1f 00                nop    DWORD PTR [rax]

0000000000001170 <dontcallme>:
    1170:       48 8d 3d 94 0e 00 00    lea    rdi,[rip+0xe94]        # 200b <_IO_stdin_used+0xb>
    1177:       e9 b4 fe ff ff          jmp    1030 <puts@plt>
    117c:       0f 1f 40 00             nop    DWORD PTR [rax+0x0]

0000000000001180 <main>:
    1180:       50                      push   rax
    1181:       e8 da ff ff ff          call   1160 <worker>
[...]
```

For additional context, I discovered the bug writing a multithreaded application. This is why the C code itself makes no sense.

## LLVM 

Currently using LLVM from Debian testing repositories. Reproduced the bug using Compiler explorer.

**Comment by asl** [comment]
Infinite loops without side effects are undefined behavior in C/C++: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1528.htm

**Comment by adah1972** [comment]
> Infinite loops without side effects are undefined behavior in C/C++: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1528.htm

No, it is **not** in C. And it is debatable in C++. C and C++ have different wordings on this topic, and C explicitly allows empty loops like `while (1)` or `for (;;)` (my emphasis: ‘An iteration statement may be assumed by the implementation to terminate if its controlling expression is *not* a constant expression’), while C++ states in a completely different way and explicitly says the intention is ‘to allow compiler transformations such as removal of empty loops’. No standard explicitly declares infinite loops without side effects as undefined behavior—removal of a empty loops is not equivalent to making it undefined behavior.

**Comment by leonardopsantos** [comment]
I just hit this issue in RISC-V bare-metal target with `clang 17.0.0`, so most definitively not restricted to x86. My code is fairly similar to the test case above:

```c
#define DO_WAIT 0
#define DO_ACTION 1

int g_lock = DO_WAIT;

void __attribute__((noinline)) worker() {
  for (;;) {

    volatile int i = 0;
    i++;
    g_lock = DO_WAIT;

    while (g_lock != DO_ACTION) {
    }

    i = 0xCAFECAFE;
  }
  return;
}

void dontcallme() {
    volatile int i = 0;
    i++;
}

int main() {
  worker();
  return 0;
}
```

The disassembly for that is:

```asm
worker:                                 # @worker
# %bb.0:                                # %for.cond
	addi	sp, sp, -16
	sw	zero, 12(sp)
	lw	a0, 12(sp)
	addi	a0, a0, 1
	sw	a0, 12(sp)
.Lfunc_end0:
	.size	worker, .Lfunc_end0-worker
                                        # -- End function
	.globl	dontcallme                      # -- Begin function dontcallme
	.p2align	2
	.type	dontcallme,@function
dontcallme:                             # @dontcallme
# %bb.0:                                # %entry
	addi	sp, sp, -16
	sw	zero, 12(sp)
	lw	a0, 12(sp)
	addi	a0, a0, 1
	sw	a0, 12(sp)
	addi	sp, sp, 16
	ret
.Lfunc_end1:
	.size	dontcallme, .Lfunc_end1-dontcallme
                                        # -- End function
	.globl	main                            # -- Begin function main
```

There's no control instruction at the end of `worker`, so it just falls through to `dontcallme`. 

I'm baffled as to how can anyone think that's reasonable.

The workaround is very counter-intuitive:

```c
    while (g_lock != DO_ACTION) {
        asm volatile("");
    }
```

Yields:

```asm
.LBB0_2:                                # %while.body
                                        #   Parent Loop BB0_1 Depth=1
                                        # =>  This Inner Loop Header: Depth=2
	#APP
	#NO_APP
	lw	a3, %pcrel_lo(.Lpcrel_hi0)(a0)
	bne	a3, a1, .LBB0_2
# %bb.3:                                # %while.end
                                        #   in Loop: Header=BB0_1 Depth=1
	sw	a2, 12(sp)
	j	.LBB0_1
.Lfunc_end0:
	.size	worker, .Lfunc_end0-worker
                                        # -- End function
```
