### ISSUE TITLE
Unreachable [[fallthrough]] is diagnosed twice

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#60416]
Consider the following example:
```c++
int n;
void f(void){
     switch (n){
         [[fallthrough]]; // allowed but not useful
         case 1:;
     }
}
```
Clang diagnoses the unreachable fallthrough attribute twice: https://godbolt.org/z/MfK5G9q54. Once for `-Wunreachable-code` and again for `-Wunreachable-code-fallthrough`. We should ensure that only one of those diagnostics is fired instead of two. We should also pay special attention that things like `-Wunreachable-code -Wno-unreachable-code-fallthrough` and `-Wno-unreachable-code -Wunreachable-code-fallthrough` continue to work as expected.

**Comment by tbaederr** [comment]
The `-Wunreachable-code` warning is confusing IMO, that's an empty statement with an attribute I think, why is it even considered "code"?

**Comment by AaronBallman** [comment]
I think "code" is pretty reasonable, but that warning is still pretty strangely worded for this scenario. It'd be a little better if it said "code is not reachable" because you don't really execute null statements. But yeah, I would expect `-Wunreachable-code-fallthrough` to "win" and be the diagnostic issues. That matches `_Generic` in: https://godbolt.org/z/8he8jhrGq

**Comment by hazohelet** [comment]
Proposed fix: https://reviews.llvm.org/D145842
