### ISSUE TITLE
hwasan_setjmp_x86_64.o: relocation R_X86_64_PC32 against symbol `__interceptor_sigsetjmp' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by hjl-tools** [llvm/llvm-project#60426]
The older GNU assemblers generates R_X86_64_PC32 relocation against
defined non-weak global branch targets with default visibility.  A
 linker may issue an error when building a shared library.

**Comment by MaskRay** [comment]
Is that GNU as before circa 2018? We can say such old binutils is unsupported. Normally compiler-rt is built by very new Clang (bootstrap build) or a very new GCC (when imported to gcc libsanitizer).

**Comment by hjl-tools** [comment]
Someone is using binutils 2.24 with GCC 13: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108106
