### ISSUE TITLE
[libc++] Fixes the Clang modular build

### ISSUE THREAD

**Issue by mordante** [llvm/llvm-project#60427]
This addresses the second part as reported in #60271 

https://github.com/llvm/llvm-project/commit/12cb1cb3720de8d164196010123ce1a8901d8122 reverted a commit, which caused some breakage (two separate issues reported), see discussions in https://reviews.llvm.org/rG12cb1cb3720d.

This fixes the module map of libc++. Note the ICE in Clang is not addressed in this issue. @erichkeane do you consider #60336 a different issue or the same?

/pick a7f8ddc4e2e3dac4c123ed8db1704f2753db5722

**Comment by erichkeane** [comment]
I want to see what the modules code-owners believe is the correct behavior here before deciding on #60336, but getting this picked I think makes it not a release blocker.
