### ISSUE TITLE
Handle or reject multiple SHT_SYMTAB sections

### ISSUE THREAD

**Issue by jh7370** [llvm/llvm-project#60448]
According to the ELF gABI, "Currently, an object file may have only one section of each type [SHT_SYMTAB and SHT_DYNSYM], but this restriction may be relaxed in the future.". llvm-objcopy treats the last SHT_SYMTAB in an ELF object as the official symbol table, and ignores all the others. The others are not populated with symbols in memory, which means that `SymbolTableSection::removeSymbols` crashes (it assumes that there is at least one symbol - the null symbol - in the table, which is not the case as the symbol table hasn't been populated).

To fix this, we should either add proper support for multiple SHT_SYMTAB sections, or we should simply emit an error if more than one such section is encountered. For now, the error is probably simpler.

**Comment by MaskRay** [comment]
I agree that an error will be simpler. All ELF producers I have seen hard code special case `SHT_SYMTAB, and without careful crafting by hand object files have at most one `SHT_SYMTAB`.

**Comment by jh7370** [comment]
I've added the `good first issue` label on the basis that we will just go with the error emission, rather than any other approach. Adding multiple `SHT_SYMTAB` support is probably not worth the effort, and unlikely to be within easy reach of a new developer on llvm-objcopy.

**Comment by MosheBerman** [comment]
I'm looking to tackle my first issue. Can I have this issue please? I'll take a stab early this week. Thanks!

**Comment by jh7370** [comment]
I don't think anybody else has picked it up, so feel free to try.

**Comment by MosheBerman** [comment]
Can someone assign to me please? I'm not able top do it myself. Thanks!

**Comment by MosheBerman** [comment]
FYI, I'm keeping notes as I work in a [Google Doc][1].

[1]: https://docs.google.com/document/d/1_RKDzVSugap4AwrsuhTq450FDrYapSdvegFCXj0OszI/edit?usp=sharing

**Comment by MosheBerman** [comment]
Making sure I don't go too far down the wrong rabbit hole, am I correct that the changes we want involve [`ELFObject.cpp`][1]?

[1]: https://github.com/llvm/llvm-project/blob/main/llvm/lib/ObjCopy/ELF/ELFObject.cpp

**Comment by MosheBerman** [comment]
Yes, this helps a lot!

It seems like the change could to add the following right after L1706: 

```
if (Obj.SymbolTable)
    return createStringError(…)
```

> Sorry for the slow response - I work UK hours, so am probably in a different timezone to you. 

Thanks for letting me know, it’s not a problem at all. (FYI, I’m in US Eastern time.)

> Please don't forget to include a test case for this change too. I can assist in creating one if needed.

Yep! Already got the existing tests running. (I have some experience with LIT but none with the ELF format.)

My gut says to test for:
1. multiple sections, and 
2. if we don’t already have a base-case test, this change probably warrants it. 
3. finally, if there are tests for the old behavior of “last section overrides earlier ones” then we might need to fix that. 

I’ll take a stab at putting together a test based on the other ELF tests and then I can share it here or on Phabricator and get some feedback. 

Sound good?

**Comment by jh7370** [comment]
I don't think you likely need more than a single new test, to test that the error message is produced when there are multiple symbol tables. There is already plentry of coverage that symbol tables can be read and modified by llvm-objcopy, when on their own. So I think the only thing your test input needs to have is two symbol tables. Since yaml2obj automatically includes a symbol table called .symtab, you just need to manually add a second one with a different name. Hopefully that information, combined with the existing tests should point you in the direction of how to create an appropriate input.

It's certainly possible that there other tests with multiple symbol tables. It is likely that these are unintentional, though it's hard to say at this point.

**Comment by jh7370** [comment]
> Is there a convention for/against linking GH issues in code comments?

I would say that it's unnecessary in most cases: the behaviour you plan on commenting on is true whether or not this ticket exists. The place to reference this issue is in the Phabricator review that you create for the patch, and in the commit message.

**Comment by MosheBerman** [comment]
Submitted https://reviews.llvm.org/D14350.

**Comment by MosheBerman** [comment]
Updated the diff to address feedback.
