### ISSUE TITLE
[openmp] missing gpu targets for vanilla build on 16.0.0-rc1

### ISSUE THREAD

**Issue by h-vetinari** [llvm/llvm-project#60457]
I have another failure with [trying](https://github.com/conda-forge/openmp-feedstock/pull/77) to build OpenMP 16.0.0-rc1. Can open a separate issue if desired, but since one already exists I start here:
```console
-- Configuring done
CMake Error at libomptarget/plugins/amdgpu/CMakeLists.txt:93 (add_dependencies):
  The dependency target "omptarget.devicertl.amdgpu" of target
  "omptarget.rtl.amdgpu" does not exist.


CMake Error at libomptarget/plugins/cuda/CMakeLists.txt:85 (add_dependencies):
  The dependency target "omptarget.devicertl.nvptx" of target
  "omptarget.rtl.cuda" does not exist.


CMake Error at libomptarget/plugins-nextgen/amdgpu/CMakeLists.txt:93 (add_dependencies):
  The dependency target "omptarget.devicertl.amdgpu" of target
  "omptarget.rtl.amdgpu.nextgen" does not exist.


CMake Error at libomptarget/plugins-nextgen/cuda/CMakeLists.txt:88 (add_dependencies):
  The dependency target "omptarget.devicertl.nvptx" of target
  "omptarget.rtl.cuda.nextgen" does not exist.


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

AFAICT, by default, the GPU targets shouldn't be built, especially if there's no appropriate hardware / drivers around. This is how things used to work the last couple of releases.

_Originally posted by @h-vetinari in https://github.com/llvm/llvm-project/issues/60393#issuecomment-1411813152_

**Comment by h-vetinari** [comment]
> @jhuber6: There isn't anything that should stop us from building the GPU targets even without appropriate hardware / drivers. Can you post the full output of a clean build? The above error suggests that the plugins are not being built but I don't see anything indicating why.

Here's the full [log](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/651103/logs/30). Let me know if you need anything else (e.g. try some patches etc.).

**Comment by jhuber6** [comment]
```
2023-02-01T10:08:58.9614931Z -- LIBOMPTARGET: Not building DeviceRTL. Missing clang: CLANG_TOOL-NOTFOUND, llvm-link: /home/conda/feedstock_root/build_artifacts/openmp_1675245952873/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/llvm-link, opt: /home/conda/feedstock_root/build_artifacts/openmp_1675245952873/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/opt, llvm-extract: /home/conda/feedstock_root/build_artifacts/openmp_1675245952873/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/llvm-extract, or clang-offload-packager: PACKAGER_TOOL-NOTFOUND
```
This would be the problem. I'm wondering why these tools are not being found. Is this being built standalone?

**Comment by h-vetinari** [comment]
Thanks. Indeed we're building stand-alone (for various reasons, not least that public CI is not powerful enough to do LLVM+clang+... at once). So far, clang wasn't necessary for building openmp, but I can add this. I also now stumbled over #58219 which seems to be related.

**Comment by h-vetinari** [comment]
Aside from missing that fallback, there's an issue with the following IMO,

https://github.com/llvm/llvm-project/blob/124f90bd89b97066e01274a9bba1068f3a175d66/openmp/libomptarget/DeviceRTL/CMakeLists.txt#L28-L34

in that clang should not be looked up in `LLVM_TOOLS_BINARY_DIR`, but should be possible to find in its own folder. This distinction is important to us (i.e. whether something is simply a build tool, or a host dependency that has ABI-implications), and so I want to find clang in a different folder (the build environment) than llvm (in the host environment).

**Comment by jhuber6** [comment]
The problem is that we only except to build the `DeviceRTL` with a "just-built" clang. Hence we pull it out of the current build. Otherwise, it's unlikely that a system `clang` would be new enough to build the device runtime correctly. We could potentially add an extra search path to override it.

**Comment by h-vetinari** [comment]
We have the ability to use the same version of clang as the openmp being built, but it's not in the same place as llvm.

Alternatively, I'd be fine to have a fallback that doesn't build `DeviceRTL` when there's no clang as expected (which AFAICT was the state of affairs until LLVM 15).

**Comment by jhuber6** [comment]
> We have the ability to use the same version of clang as the openmp being built, but it's not in the same place as llvm.
We could probably just add an extra CMake option to provide an override path. Would that help?
> Alternatively, I'd be fine to have a fallback that doesn't build `DeviceRTL` when there's no clang as expected (which AFAICT was the state of affairs until LLVM 15).
We could probably check to see if there's a `clang` and disable the GPU portion if that would help as well. It would make the dependency more obvious.

**Comment by h-vetinari** [comment]
Both options are good and worthwhile IMO (independently); any one of them would be enough.

**Comment by jhuber6** [comment]
We currently use `LLVM_TOOLS_BINARY_DIR`, which I think you should be able to set manually already if you're performing a two-step build or a standalone build.

For the latter, I think we should probably skip building the plugins that require the `DeviceRTL` if we don't have that target. That would let us still build for CPU offloading so it can at least be tested.

**Comment by h-vetinari** [comment]
For context: proposed fix in https://reviews.llvm.org/D143196

**Comment by h-vetinari** [comment]
Can this issue be reopened until the backport is merged, please?

/cherry-pick 9f650ae779b4d7e033f5f17290aad50e935424d2

**Comment by h-vetinari** [comment]
Thanks a lot @jhuber6 @shiltian @tru 🙏🙃
