### ISSUE TITLE
libc apparently superfluous option for SCUDO

### ISSUE THREAD

**Issue by liam-clink** [llvm/llvm-project#60461]
In the website [documentation](https://libc.llvm.org/full_host_build.html) for building libc, this command is given to configure it properly.

```shell
cmake ../llvm  \
   -G Ninja  \ # Generator
   -DLLVM_ENABLE_PROJECTS="clang;libc;lld;compiler-rt"   \ # Enabled projects
   -DCMAKE_BUILD_TYPE=<Debug|Release>  \ # Select build type
   -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
   -DLLVM_LIBC_FULL_BUILD=ON      \  # We want the full libc
   -DLLVM_LIBC_INCLUDE_SCUDO=ON   \  # Include Scudo in the libc
   -DCOMPILER_RT_BUILD_SCUDO_STANDALONE_WITH_LLVM_LIBC=ON \
   -DCOMPILER_RT_BUILD_GWP_ASAN=OFF                       \
   -DCOMPILER_RT_SCUDO_STANDALONE_BUILD_SHARED=OFF        \
   -DCMAKE_INSTALL_PREFIX=<SYSROOT>  # Specify a sysroot directory
```

However, upon doing this, apparently one of the options is not used, is this deprecated or new and not fleshed out? Or just not supposed to be there?
```console
CMake Warning:
  Manually-specified variables were not used by the project:

    LLVM_LIBC_INCLUDE_SCUDO
```

**Comment by michaelrj-google** [comment]
Running the following cmake command finishes with no errors on my checkout. If you're still having this problem, try deleting your cmake cache, which should be CMakeCache.txt in the build directory, and rerunning the cmake command.

`cmake ../llvm -G Ninja -DLLVM_ENABLE_PROJECTS="clang;llvm;libc;compiler-rt;lld" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_LIBC_FULL_BUILD=ON -DLLVM_LIBC_INCLUDE_SCUDO=ON -DCOMPILER_RT_BUILD_SCUDO_STANDALONE_WITH_LLVM_LIBC=ON -DCOMPILER_RT_BUILD_GWP_ASAN=OFF -DCOMPILER_RT_SCUDO_STANDALONE_BUILD_SHARED=OFF -DCMAKE_INSTALL_PREFIX=~/install -DCMAKE_INSTALL_LIBDIR=~/install/lib/x86_64-linux-gnu`

**Comment by michaelrj-google** [comment]
Closing this bug for now, if it reoccurs feel free to open a new bug.
