### ISSUE TITLE
[OpenMP] slow linking and huge memory consumption on AMDGPU

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#60494]
A single linking increased from 12 sec to 3min and the linker wrapper memory usage explodes 30GB.
Started by https://github.com/llvm/llvm-project/commit/6185246f4f62345d0cfdaef62da7e15b01d52557

**Comment by jdoerfert** [comment]
@ye-luo is this resolved?

**Comment by ye-luo** [comment]
Huge memory usage has been resolved but the linking speed remains minutes.
In addition, it will be helpful to backport the memory reduction fix to 16 release.

**Comment by jhuber6** [comment]
> Huge memory usage has been resolved but the linking speed remains minutes. In addition, it will be helpful to backport the memory reduction fix to 16 release.

Window for 16.0 has passed, so it'd need to be 16.0.1

**Comment by tru** [comment]
Is there anything more that needs to be done here for 16.x?

**Comment by tstellar** [comment]
Since this has not been fixed, I'm moving the to the 17.0.0 milestone.  If you would like this included in the 16.0.x release, change the milestone back to 16.0.X and explain why it needs to be included.

**Comment by ye-luo** [comment]
The issue has been fixed in upstream. Fixing 16.x is quite unlikely due to the amount of work. Thus I will close this issue.
