### ISSUE TITLE
`unw_get_proc_name` fails on Alpine linux if you don't pass `-rdynamic`

### ISSUE THREAD

**Issue by lolgab** [llvm/llvm-project#60492]
## Motivation
The [Scala Native](https://github.com/scala-native/scala-native) compiler based on LLVM. It relies on libunwind's `unw_get_proc_name` for stack traces. musl libc is prone to static linking which, but linking statically breaks `unw_get_proc_name`.

## Reprodution

Given this c program:
```c
#include <stdio.h>
#include <libunwind.h>

void unwind_by_libunwind()
{
  unw_cursor_t cursor;
  unw_context_t context;

  unw_getcontext(&context);
  unw_init_local(&cursor, &context);

  while (unw_step(&cursor) > 0)
  {
    unw_word_t offset;
    char name[64] = {0};
    int result = unw_get_proc_name(&cursor, name, sizeof(name), &offset);
    
    printf("UNW_EUNSPEC = %d\n", UNW_EUNSPEC);
    printf("UNW_ENOINFO = %d\n", UNW_ENOINFO);
    printf("UNW_ENOMEM = %d\n", UNW_ENOMEM);
    printf("result = %d, name = '%s'\n", result, name);
  }
}

int main() {
  unwind_by_libunwind();
  return 0;
}
```

I installed the dependencies with:
```shell
sudo apk add clang llvm-libunwind-dev
```

Result without passing `-rdynamic`:
```console
$ clang -lunwind -o main main.c && ./main
UNW_EUNSPEC = -6540
UNW_ENOINFO = -6549
UNW_ENOMEM = -6541
result = -6540, name = ''
```

Result when passing `-rdynamic`:
```console
$ clang -lunwind -rdynamic -o main main.c && ./main
UNW_EUNSPEC = -6540
UNW_ENOINFO = -6549
UNW_ENOMEM = -6541
result = 0, name = 'main'
```

**Comment by MaskRay** [comment]
On Linux and most ELF platforms, `unw_get_proc_name` uses `dladdr` to get the function name from the dynamic symbol table (`DT_SYMTAB` and `DT_STRTAB`). Without `-rdynamic` (`ld --export-dynamic`), `main` is not in the dynamic symbol table.

BTW: you can use other means making `main` dynamic: https://maskray.me/blog/2020-11-15-explain-gnu-linker-options#export-dynamic

**Comment by lolgab** [comment]
Thank you for the explanation 🙏
So, since `--export-dynamic` doesn't work with `-static`, it's impossible to use `unw_get_proc_name` in static binaries. Right?
Do I have any alternative to achieve the same goal on a static binary?
