### ISSUE TITLE
LLD Section name with spaces in linker script

### ISSUE THREAD

**Issue by Prabhuk** [llvm/llvm-project#60496]
When a linker script has a section name with whitespaces, its typical to enclose the name with double quotes. The BFD linker, creates an output section with spaces but drops the double quotes.

LLD creates an output section with spaces but also includes the enclosing double quotes as part of the section name.
LLD should drop the enclosing double quotes from the section name in this case.

**Comment by SahilPatidar** [comment]
I am learning about LLD so can I work on this issue to get familiar with the codebase?

**Comment by MaskRay** [comment]
> I am learning about LLD so can I work on this issue to get familiar with the codebase?

This requires support for `OVERWRITE_SECTIONS` which may be niche, so I'll take it  :)
