### ISSUE TITLE
[Question] How do I link with lld (by calling ld.lld) with the OS's standard libraries?

### ISSUE THREAD

**Issue by spidertyler2005** [llvm/llvm-project#60500]
# background

Everything I can find is using clang.... which I do not want to do here. 

I am calling `lld::elf::link` via ctypes in python. Linking works, but the binary that is generated gives me a segfault or "accessing a corrupted shared library".

the command I am running looks similar to `ld.lld -o tests/output tests/output.o <additional args>`

I am using 64 bit arch linux (`uname -r` gives `6.1.6-arch1-3`) and I am using LLVM11.

# My actual question

I have been trying for 2 days at this, but I am an absolute idiot when it comes to linking, compiling, etc. I honestly just need a working example command. I've turned the following ir into an ELF object file:
```llvm
; ModuleID = '<string>'
source_filename = "<string>"
target triple = "x86_64-unknown-linux-gnu"

declare i32 @printf(i8*, ...)

declare void @exit(i32)

declare void @sleep(i32)

declare void @usleep(i32)

; Function Attrs: nounwind
define i32 @main() #0 {
entry:
  ret i32 0
}

attributes #0 = { nounwind }
```
 Once I try to link this, the linker happily spits out a binary, but that binary is useless.
 
 Can I get an example command that would make this work on my OS (or similar linux OS)?
 
 Thanks in advance, I am sorry for the noob question. I just cannot figure this out, and the amount of documentation I can find on lld is close to zero.

**Comment by MaskRay** [comment]
Use discourse.llvm.org for questions and keep here for issues. You can find some articles about how `_start` transitively calls `main`. `lld::elf::link` is discouraged. Use `lld::safeLldMain` instead.

**Comment by spidertyler2005** [comment]
> Use discourse.llvm.org for questions and keep here for issues. You can find some articles about how `_start` transitively calls `main`. `lld::elf::link` is discouraged. Use `lld::safeLldMain` instead.

That function does not exist for LLVM11 as far as I can see.

Also, I did actually figure it out. Just a few minutes ago actually

my python code eventually ended up as (using llvmlite here, but the changes aren't pulled into master yet)
`the function I'm running has the args -- (output_file: str, object_files: list[str], additional_args: list[str])`

```python
import binding from llvmlite
#...
loc: str = ...

binding.lld.lld_linux(f"{loc}",
    [
        "/usr/lib64/crt1.o", "/usr/lib64/crti.o",
        "/usr/lib64/gcc/x86_64-pc-linux-gnu/12.2.1/crtbegin.o", f"{loc}.o",
        "/usr/lib64/gcc/x86_64-pc-linux-gnu/12.2.1/crtend.o",
        "/usr/lib64/crtn.o"
    ], 
    [
        "-Bdynamic", "-no-pie", "--build-id", "--dynamic-linker",
        "/lib64/ld-linux-x86-64.so.2", "-L/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/",
        "-L/usr/lib/", "-L/usr/lib64/", "-L/lib/", "-L/lib64/", "-lc"
    ]
)
```

**Comment by EugeneZelenko** [comment]
11 is too old. Please try 16 release candidate or  `main` branch.

**Comment by MaskRay** [comment]
The complexity of the various `-L` `-l` options and `crt*` files are a main reason that using compiler drivers to invoke the linker is preferred over invoking the linker itself.
