### ISSUE TITLE
libunwind: `unw_step` constantly returns `UNW_EBADREG` on macOS

### ISSUE THREAD

**Issue by CuriousGeorgiy** [llvm/llvm-project#60506]
Description: https://github.com/tarantool/tarantool/issues/7980#issuecomment-1330479294

Could you please comment on this?

> Even if _WIN64 is defined (why the hell should it be defined in a macos version if libunwind?), register 16 (UNW_X86_64_RIP = 16) is not considered valid. Because it falls in neither category. And because UNW_REG_IP == -1 is the accepted representation of the IP register.

Context: https://github.com/llvm/llvm-project/blob/d54d99748db6cc6de9b4601434704e99124289f3/libunwind/src/DwarfInstructions.hpp#L254-L279

https://github.com/llvm/llvm-project/blob/d54d99748db6cc6de9b4601434704e99124289f3/libunwind/src/Registers.hpp#L357-L367

**Comment by DimitryAndric** [comment]
Looks like this was fixed in 2f1ee56f3cb8adb5aeadba3f66a8fc39fba1604d ("[unwind] Handle UNW_X86_64_RIP register") by @vitalybuka, but as far as I can see [Apple's copy of libunwind](https://opensource.apple.com/source/libunwind/libunwind-35.3/src/Registers.hpp.auto.html) does not have this yet:

```c++
inline bool Registers_x86_64::validRegister(int regNum) const
{
...
	if ( regNum > 15 )
		return false;
...
inline uint64_t Registers_x86_64::getRegister(int regNum) const
{
	switch ( regNum ) {
		case UNW_REG_IP:
			return fRegisters.__rip;
...
inline void Registers_x86_64::setRegister(int regNum, uint64_t value)
{
	switch ( regNum ) {
		case UNW_REG_IP:
			fRegisters.__rip = value;
			return;
inline const char* Registers_x86_64::getRegisterName(int regNum)
{
	switch ( regNum ) {
		case UNW_REG_IP:
			return "rip";
```

If there is any sense in Apple's version numbering, https://opensource.apple.com/source/libunwind/libunwind-201/ should be the latest, but it also doesn't have Vitaly's commit.

**Comment by MaskRay** [comment]
@lhames

**Comment by lhames** [comment]
GitHub is for LLVM project bugs, but this seems to be about Apple's libunwind release. As far as I know the best place for filing bugs against Apple is https://developer.apple.com/bug-reporting/.

As a general comment: commits on the LLVM mainline generally make their way into libunwind releases, but (1) this isn't guaranteed, and (2) libunwind releases are rare so commits to the mainline may not show up for some time.

**Comment by ldionne** [comment]
@CuriousGeorgiy Can you check with the macOS 13.3 beta? I just checked and it should be the first release to have the fix.

**Comment by CuriousGeorgiy** [comment]
@ldionne sorry for the late response, just managed to get my hands on macOS 13.3. I can confirm the problem is fixed, thanks a lot for taking part!
