### ISSUE TITLE
RISCV64 buggy generated code  when using inline assembly

### ISSUE THREAD

**Issue by nstavropoulos** [llvm/llvm-project#60512]
This piece of code 
 compiled with clang 15 --target=riscv64-unknown-linux -O2
```
#include "stdint.h"
int main(int num) {
 uint64_t * base = (uint64_t *) 0x10000000;

 uint64_t val32;

 // Init X11 to zero
   __asm__ volatile("mv x10, x0");
  __asm__ volatile ("addi a0, x10, 1":::);
  __asm__ volatile("sw x10, 0(%0)" : : "r"(base));
  __asm__ volatile("lw %0, 0(%1)" : "=r"(val32) : "r"(base));

 return 0;

}
```

generates 

```main:                                   # @main
        li      a0, 0
        addi    a0, a0, 1
        lui     a0, 65536
        sw      a0, 0(a0)
        lw      a0, 0(a0)
        li      a0, 0
        ret
```

Which in my understanding is buggy as it uses register a0 without checking if it is used previously in inline assembly. 

Thanks and apologies if  there is something not clear enough.
Nikos

**Comment by jrtc27** [comment]
Not a bug. Fix your clobbers.

**Comment by topperc** [comment]
This isn’t valid inline assembly. You can’t keep physical registers are live between different inline assembly statements. You should use a single asm statement with multiple instructions in the text.

You must also list every register written in the clobber list. The compiler doesn’t really read the text of the instructions.

**Comment by nstavropoulos** [comment]
Thank you for your answers. It was not clear from what I had read that I should have use a single asm statement nor that I have to declare as clobbered the output register.
