### ISSUE TITLE
libc++ operator<=> string_view is not working properly

### ISSUE THREAD

**Issue by morozyto** [llvm/llvm-project#60511]
https://godbolt.org/z/G515Kc36h

This is libc++ issue, because without `-stdlib=libc++` option this code compiles fine.

As described in https://libcxx.llvm.org/Status/Spaceship.html, [string.view.comparision] considered complete.

**Comment by DimitryAndric** [comment]
This was only implemented in 3818b4df1e102a0886138414c2d05fa66f2260cb ("[libc++] Uses operator<=> in string_view") by @mordante, after 16.0 was branched. It has not been merged to release/15.x or release/14.x, so unfortunately it never made it into a released version.

**Comment by morozyto** [comment]
@DimitryAndric thank you for your response.
