### ISSUE TITLE
[ARM] __fp16 return values can get lost by hard float ABI

### ISSUE THREAD

**Issue by lenary** [llvm/llvm-project#60510]
Here is a simple C program:

```c
__fp16 inner(void);
float other(float);

__fp16 out_call_test(float arg) {
    __fp16 res = inner();
    other(arg);
    return res;
}
```

When compiled with `clang --target=arm-arm-none-eabi -mfpu=fp-armv8 -march=armv8.2-a+fp16 -mfloat-abi=hard -O1 -g0 -S test.c -o -`, it produces the following assembly:

```asm
out_call_test:
        .fnstart
        .save   {r11, lr}
        push    {r11, lr}
        .setfp  r11, sp
        mov     r11, sp
        .vsave  {d8}
        vpush   {d8}
        vmov.f32        s16, s0
        bl      inner
        vmov.f32        s0, s16
        bl      other
        vpop    {d8}
        pop     {r11, pc}
```

My understanding is that all the functions in this example return their values in `s0` according to the hard float ABI. So, we want this function to finish with `s0` containing whatever was in `s0` after the `bl inner` instruction.

But, the `vmov.f32 s0, s16` immediately clobbers that value, and so would the `bl other` return value.

---

We don't get the same issue with `-mfloat-abi=softfp`, where I think the return values all have to be in `r0` instead of `s0`, and they are not clobbered, so something weird is going on:

```asm
out_call_test:
	.fnstart
	.save	{r4, r5, r11, lr}
	push	{r4, r5, r11, lr}
	.setfp	r11, sp, #8
	add	r11, sp, #8
	mov	r4, r0
	bl	inner
	mov	r5, r0
	mov	r0, r4
	bl	other
	vmov.f16	s0, r5
	vmov	r0, s0
	pop	{r4, r5, r11, pc}
```

**Comment by davemgreen** [comment]
I would guess this is to do with the way we lower VMOVhr of bitcast in PerformVMOVhrCombine but don't update the chain on CopyFromReg nodes.

**Comment by lenary** [comment]
Cool, thanks for that pointer, I think I have a fix for it, but I want to do more testing.

**Comment by lenary** [comment]
Fix available here: https://reviews.llvm.org/D143713
