### ISSUE TITLE
[wasm] regression of string literals with prefix "L"

### ISSUE THREAD

**Issue by R32** [llvm/llvm-project#60529]
I just downloaded the new `llvm.exe` and found my WASM module crashed.

```console
> clang.exe --version
clang version 14.0.6
Target: x86_64-pc-windows-msvc
Thread model: posix

# previous version
> old.clang.exe --version
clang version 12.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
```

`main.c`

```c
int main()
{
	unsigned short *str = L"abcd";
}
```

Compile the code above with `-target wasm32` will get a warning:

```console
> clang -target wasm32 main.c
main.c:3:18: warning: incompatible pointer types initializing 'unsigned short *'

      with an expression of type 'int[5]' [-Wincompatible-pointer-types]
        unsigned short *str = L"abcd";
                        ^     ~~~~~~~
1 warning generated.
```

Actually converting `int[5]` to `unsigned short *` is an error, not a warning.

**Comment by ADKaster** [comment]
This fails to compile on trunk. 

https://godbolt.org/z/o447TKdTG

The type of `L"abcd"` is `const wchar_t[5]`, not any particularly sized unsigned integer type.

**Comment by R32** [comment]
The old `clang.exe(ver: 12.0)` works with `-fshort-wchar`, but the new version doesn't

**Comment by R32** [comment]
> This fails to compile on trunk.
> 
> https://godbolt.org/z/o447TKdTG
> 
> The type of `L"abcd"` is `const wchar_t[5]`, not any particularly sized unsigned integer type.

@ADKaster In that link, If you switch C++ to **C** and add `-fshort-wchar` then there will be no warning or error

**Comment by R32** [comment]
I just downloaded the  latest  15.7 version and the problem is gone.

I didn't notice the latest version when I downloaded it from https://releases.llvm.org/download.html yesterday
