### ISSUE TITLE
[X86] -x86-use-fsrm-for-memcpy does not ensure DF = false

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#60527]
https://simd.godbolt.org/z/MGf1qovrW

If we enable Fast Short Rep Mov memcpy codegen, then we should ensure that the direction flag (DF) has been cleared before calling the REP MOV:
```ll
define void @doit(ptr %dst, ptr %src, i64 %len) {
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 %len, i1 0)
  ret void
}
declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1 )
```
`-mcpu=tigerlake -x86-use-fsrm-for-memcpy`
```asm
doit:
        movq    %rdx, %rcx
        rep;movsb (%rsi), %es:(%rdi)
        retq
```
should be:
```asm
doit:
        movq    %rdx, %rcx
        cld
        rep;movsb (%rsi), %es:(%rdi)
        retq
```

**Comment by RKSimon** [comment]
CC @AtariDreams

**Comment by aengelke** [comment]
Should it really emit `cld`? The i386 and the x86-64 System V psABIs mandates `DF` to be cleared on function entry/exit (Section 3.2.1) and IIRC Windows x64 requires the same. Not sure about Windows 32-bit and Mac/Darwin, but I'd be surprised if it was different there.

glibc uses cld on some of its 32-bit rep stos/movs/cmps code (all sources of this are >20 years old), but doesn't on more recent 32-bit code (e.g. sysdeps/i386/memset.S). It doesn't use cld in any 64-bit code.

**Comment by RKSimon** [comment]
Thanks for that - I wrote this bug when I was investigating aliased memcpy performance and I hadn't gone back to look at it since.

Turns out the case that caused all the problem was calling `std` prior to the `rep mov` to copy backwards, and I never reset it.
