### ISSUE TITLE
failure to parse asm emitted by AArch64 + global isel

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#60528]
This looks like probably a different issue than https://github.com/llvm/llvm-project/issues/60369, but I'm not certain about that

This function: 
```llvm
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"

define i64 @f(i64 %0) {
  %2 = mul i64 %0, %0
  %3 = sub i64 %2, -2105098
  ret i64 %3
}
```

compiled to AArch64 with Global Isel gives:
```s
	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 13, 0
	.globl	_f                              ; -- Begin function f
	.p2align	2
_f:                                     ; @f
	.cfi_startproc
; %bb.0:
	add	x8, xzr, #513, lsl #12          ; =2101248
	add	x8, x8, #3850
	madd	x0, x0, x0, x8
	ret
	.cfi_endproc
                                        ; -- End function
.subsections_via_symbols
```

but then this doesn't parse back:
```console
Johns-MacBook-Pro:tmp regehr$ llvm-mc r2.s
	.section	__TEXT,__text,regular,pure_instructions
r2.s:2:2: warning: .build_version macos used while targeting darwin22.3.0
        .build_version macos, 13, 0
        ^
	.build_version macos, 13, 0
	.globl	_f
	.p2align	2
_f:
	.cfi_startproc
r2.s:8:15: error: invalid operand for instruction
        add     x8, xzr, #513, lsl #12          ; =2101248
                         ^
	add	x8, x8, #3850
	madd	x0, x0, x0, x8
	ret
	.cfi_endproc
.subsections_via_symbols
Johns-MacBook-Pro:tmp regehr$ 
```

**Comment by aabhinavg** [comment]
The error is occurring because the AArch64 instruction "add x8, xzr, #513, lsl #12" is being interpreted as invalid. This can happen when the instruction set architecture (ISA) used to generate the assembly code is different from the ISA being used to interpret the assembly code. In this case, the code was generated using a version of the MacOS ISA (13.0) but is being interpreted using a different version of the Darwin ISA (22.3.0). The "lsl #12" operation is likely causing the instruction to be interpreted as invalid. To resolve this issue, try using a consistent ISA for both code generation and interpretation.

**Comment by regehr** [comment]
I'm guessing a bit, but it seems to me that the actual problem here is that for the A64 "add (immediate)" instruction, putting 11111 in either the source or destination register field refers to the stack pointer instead of the zero register. thus, the emitted assembly isn't going to do what it looks like someone had hoped it would do, which is to build a constant value be adding the scaled immediate to the zero register's value.

**Comment by davemgreen** [comment]
Yes - I believe it might be AArch64MIPeepholeOpt pass creating the adds with xzr. It is not expecting "sub xzr, 2105098" to not have been constant-folded, so doesn't handle zero registers correctly.

**Comment by regehr** [comment]
a bit off topic, and perhaps not a good idea, but it would be possible to insist that folding has been performed before the backend gets invoked. is that an idea that has been tossed around?

**Comment by davemgreen** [comment]
In general we like all passes to work in isolation without bugs or relying on canonicalizations from other passes. They don't have to work optimally, but they ideally shouldn't miscompile. I think in this case It was a mixture of GlobalISel producing `SUB x, -C` (as opposed to `ADD x, C`) and the MUL causing transforms in the MachineCombiner, causing the AArch64MIPeepholeOpt pass to see code that would not usually come up from standard ISel. Unfortunately there isn't really a place where all folding can happen (past instcombine in the midend) other than ISel, and Global-ISel is going to take a while to catch up with SelectionDAG.

There is a patch in https://reviews.llvm.org/D143475 to add a bailout to the pass.
