### ISSUE TITLE
libc++ rejects `std::format("{{:{}^1}}", ' ')` 

### ISSUE THREAD

**Issue by hewillk** [llvm/llvm-project#60536]
The following valid format strings are rejected by libc++.

```cpp
#include <format>
#include <iostream>

int main() {
  std::cout << std::format("{{:{}^5}}", ' ');
}
```
https://godbolt.org/z/9bsPP7bjq

**Comment by mordante** [comment]
Thanks for the report. Indeed the constexpr validation code had a bug. I've created a fix https://reviews.llvm.org/D143402.

**Comment by mordante** [comment]
Landed as https://reviews.llvm.org/rGac44dadcbea52e14aab20c0d590d4ec00d615a93
