### ISSUE TITLE
Function parameter 'map' with unknown value cannot be used in a constant expression

### ISSUE THREAD

**Issue by 4465464** [llvm/llvm-project#60548]
```c++
#include <iostream>

namespace cuco{

    template<typename Key,typename Value>
    class static_multimap{
        public:
            static_multimap(std::size_t capacity);
            static constexpr uint32_t cg_size() noexpect{
                return 100;
            }
    };

    template<typename Key,typename Value>
    static_multimap<Key,Value>::static_multimap(std::size_t capicity){

    }

    template <typename Map>
    void test_non_shmem_pair_retrieve(Map& map){
        auto constexpr cg_size =map.cg_size();
    } 

    template<typename Key,typename Value>
    void test_cuco(){
        cuco::static_multimap<Key,Value>map{100};
        auto constexpr cg_size=map.cg_size();             //case1
        test_non_shmem_pair_retrieve(map);                //case2
    }
}

int main(){
    cuco::test_cuco<int64_t,int64_t>();
}
```

**Comment by 4465464** [comment]
error: constexpr variable ‘cg_size' must be initialized by  a constant expression
  auto constexpr cg_size = map.cg_size();

note: in instantiation of function template specialization 'cuco::test_non_shmem_pair_retrieve<cuco::static_multimap<longlong>>' requested here
 test_non_shmem_pair_retrieve(map);   //case2:compile failed

note: in instantiation of function template specialization 
'cuco::test_cuco<long,long>' requested here
  cuco::test_cuco<int64_t,int64_t>();

note:function parameter 'map' with unknown value cannot be used in a contant expression
  auto constexpr cg_size = map.cg_size();

**Comment by 4465464** [comment]
<source>:21:24: error: constexpr variable 'cg_size' must be initialized by a constant expression
        auto constexpr cg_size =map.cg_size();
                       ^        ~~~~~~~~~~~~~
<source>:28:9: note: in instantiation of function template specialization 'cuco::test_non_shmem_pair_retrieve<cuco::static_multimap<long, long>>' requested here
        test_non_shmem_pair_retrieve(map);    //case2
        ^
<source>:33:11: note: in instantiation of function template specialization 'cuco::test_cuco<long, long>' requested here
    cuco::test_cuco<int64_t,int64_t>();
          ^
<source>:21:33: note: function parameter 'map' with unknown value cannot be used in a constant expression
        auto constexpr cg_size =map.cg_size();
                                ^
<source>:20:44: note: declared here
    void test_non_shmem_pair_retrieve(Map& map){
                                           ^
1 error generated.

**Comment by 4465464** [comment]
Call cg_size()  function directly can be compiled, but the call in the template will fail

**Comment by shafik** [comment]
This is `P2280R4` which we can see from the [clang status page](https://clang.llvm.org/cxx_status.html) we don't implement yet.

I am working on this but no ETA yet.

**Comment by cor3ntin** [comment]
This is https://github.com/llvm/llvm-project/pull/95474
