### ISSUE TITLE
Simplify `urem` to `icmp+select` in `(x + 1) % n`

### ISSUE THREAD

**Issue by scottmcm** [llvm/llvm-project#60546]
(Inspired by someone doing `self.write_index = (self.write_index + 1) % self.container.len();` in a circular buffer.)

If `x < n` (such as because it was just used to index an array of that length), then there's no need to modulo in `(x + 1) % n`, since there's only one case where the modulo does anything, and thus we could detect that case instead.

Alive2 proof: <https://alive2.llvm.org/ce/z/UNmz9j>

```llvm
define i64 @src(i64 noundef %x, i64 noundef %n) noundef {
%start:
  %_3 = icmp ult i64 noundef %x, noundef %n
  assume i1 %_3
  %_6 = add nuw i64 noundef %x, 1
  %0 = urem i64 %_6, noundef %n
  ret i64 %0
}
; =>
define i64 @tgt(i64 noundef %x, i64 noundef %n) noundef {
%start:
  %_3 = icmp ult i64 noundef %x, noundef %n
  assume i1 %_3
  %_6 = add nuw i64 noundef %x, 1
  %w = icmp eq i64 %_6, noundef %n
  %0 = select i1 %w, i64 0, i64 %_6
  ret i64 %0
}
; Transformation seems to be correct!
```

Repro in opt: <https://llvm.godbolt.org/z/5vP7T8fE7>

**Comment by vfdff** [comment]
candidate MR: https://reviews.llvm.org/D143883

**Comment by scottmcm** [comment]
Pardon my ignorance for how these checks work, @vfdff, but will that work where it's a dominating condition even if that's not an assume?

A less-simplified but more-realistic (based on [this rust code](https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=494cb827ca92216913172f1957bf8597)) version of this would be something like this <https://llvm.godbolt.org/z/hreKaK5dc> where the `x < n` condition does dominate the `urem`, but where it's not literally an `assume`.

(If `isValidAssumeForContext` already handles this properly, sorry for the noise.)

**Comment by vfdff** [comment]
Thanks for your info , I will try to make enhancements your **2nd case** if this direction is correct.

**Comment by vfdff** [comment]
https://reviews.llvm.org/D144248 is used to address the dominating condition

**Comment by vfdff** [comment]
reopen as https://reviews.llvm.org/D144248 need be review, too
