### ISSUE TITLE
Coroutine codegen confused by top-level const in size parameter of custom delete for promise

### ISSUE THREAD

**Issue by CaseyCarter** [llvm/llvm-project#60545]
Compiling this well-formed TU:
```c++
#include <coroutine>
#include <cstddef>

#ifdef WORKAROUND
#define CONST
#else
#define CONST const
#endif

struct generator {
    struct promise_type {
        generator get_return_object();
        std::suspend_always initial_suspend();
        std::suspend_always final_suspend() noexcept;
        void return_void();
        [[noreturn]] void unhandled_exception();

        static void* operator new(std::size_t size);
        static void operator delete(void* ptr, CONST std::size_t size); // Line 19
    };
};

void f() { delete new generator::promise_type; } // Fine
generator g() { co_return; } // Line 24
```
with `clang -std=c++2b -stdlib=libc++` produces diagnostics (https://godbolt.org/z/7arWY6M98):
```console
<source>:24:11: error: too few arguments to function call, expected 2, have 1
generator g() { co_return; } // Line 24
          ^
<source>:19:21: note: 'operator delete' declared here
        static void operator delete(void* ptr, CONST std::size_t size); // Line 19
                    ^
1 error generated.
```
Defining `WORKAROUND` (so `CONST` becomes empty instead of `const`) makes the problem go away. It would appear that the coroutine frame deallocation machinery in the compiler is confused by the presence of top-level `const` on `operator delete`'s second (`size_t`) parameter.

**Comment by ChuanqiXu9** [comment]
(I believe this is a bug)

Out of curiosity, is there any realistic usage?

**Comment by CaseyCarter** [comment]
> (I believe this is a bug)
> 
> Out of curiosity, is there any realistic usage?

It broke the reference implementation of `std::generator` linked in P2502R2 (https://godbolt.org/z/hse97vqef), which uses MSVC STL style. (We use lots of top-level `const` in function definitions.) I'll have to workaround when I ship `std::generator`.

**Comment by CaseyCarter** [comment]
I forgot to mention in the original submission that this is a regression vs. Clang 15.

**Comment by timsong-cpp** [comment]
Is it possible to get this fix into 16?

**Comment by ChuanqiXu9** [comment]
Possibly not. Since this is late for the release circle of clang16. And we should only backport  patches for very severe bugs. I think this one is not in the kind.

**Comment by AaronBallman** [comment]
Not for 16.0.0 (we just made the final rc for it a few days ago), but the changes seem reasonable for 16.0.1. @ChuanqiXu9 -- if you agree, you could file a backport issue and assign it to the 16.0.1 milestone.

**Comment by AaronBallman** [comment]
> > [d2b0b26](https://github.com/llvm/llvm-project/commit/d2b0b26132ce5d3d9022edbf274f01e9de764673)
> 
> It looks like I misunderstood the policy for backporting patches, I thought we should only backport for severe bugs generally. I'll try to file an issue for 16.0.1 later.

I don't think we have a hard requirement for what gets backported beyond "it needs to be targeted, correct, and not cause further issues" and "it can't change ABI".

If it's fixing a crash, we almost certainly want it. If it's fixing broken functionality and doesn't cause any ABI differences, then we might or might not want it. This one is small enough, and a user requested a backport, so it seems reasonable to me, but if you feel it might not be a good candidate to backport, I'll defer to your expertise.

**Comment by ChuanqiXu9** [comment]
Thanks for the explanation. I got it : )
