### ISSUE TITLE
[AMDGPU][MC][GFX90A][GFX940] Incorrect disassembly of inline constants used with 32-bit VOP3P instructions

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#60563]
Affected opcodes: v_pk_add_f32, v_pk_fma_f32, v_pk_mov_b32, v_pk_mul_f32.

An example of failed test:

    0x0a,0x40,0xb2,0xd3,0x02,0xe1,0x01,0x18

Expected result:

    v_pk_add_f32 v[10:11], v[2:3], 0.5

Actual output:

    v_pk_add_f32 v[10:11], v[2:3], 0

@petar-avramovic, could you take a look?

**Comment by petar-avramovic** [comment]
Thanks for catching this, there were no tests for imms in this case.
I assume that inst printer is correct (imm operand is expected to be 32 bit float for OPERAND_REG_INLINE_C_V2INT32 and OPERAND_REG_INLINE_C_V2FP32) from switch (OpTy) in file AMDGPUInstPrinter::printRegularOperand
Error is in SIRegisterInfo.td 
RegOrV2F32 and RegOrV2B32  from SIRegisterInfo.td should use _Imm32 (not _Imm64!)
this is the decoder that should have been used (it needs to create 32 bit imm operand)
DECODE_OPERAND_SRC_REG_OR_IMM_9(VS_64, OPW64, 32).

**Comment by dpreobra** [comment]
Fixed by 13512f84f342.
