### ISSUE TITLE
No opt-out for LLD including own version in .comment section

### ISSUE THREAD

**Issue by jonhoo** [llvm/llvm-project#60566]
Since [D26487](https://reviews.llvm.org/D26487) / https://github.com/llvm/llvm-project/commit/3da3f06dd3a0e03053b5921e5dfcceffd9d7d399, LLD now includes its own version string in the `.comment` section of linked binaries:

```console
$ cat x.c
int main(void) {}
$ clang -fuse-ld=lld x.c
$ objdump -s -j .comment a.out

a.out:     file format elf64-littleaarch64

Contents of section .comment:
 0000 4c696e6b 65723a20 4c4c4420 31322e30  Linker: LLD 12.0
 0010 2e310063 6c616e67 20766572 73696f6e  .1.clang version
 0020 2031312e 312e3020 28416d61 7a6f6e20   11.1.0 (Amazon
 0030 4c696e75 78203220 31312e31 2e302d31  Linux 2 11.1.0-1
 0040 2e616d7a 6e322e30 2e322900 4743433a  .amzn2.0.2).GCC:
 0050 2028474e 55292037 2e332e31 20323031   (GNU) 7.3.1 201
 0060 38303731 32202852 65642048 61742037  80712 (Red Hat 7
 0070 2e332e31 2d313529 0000               .3.1-15)..
```

Clang also does the same (via [D1720](https://reviews.llvm.org/D1720) and [D1729](https://reviews.llvm.org/D1729)), but provides an opt-out mechanism (like GCC) via `-fno-ident`/`-Qn` (they're equivalent in Clang):

```console
$ clang -fuse-ld=lld -Qn x.c
$ objdump -s -j .comment a.out

a.out:     file format elf64-littleaarch64

Contents of section .comment:
 0000 4c696e6b 65723a20 4c4c4420 31322e30  Linker: LLD 12.0
 0010 2e310047 43433a20 28474e55 2920372e  .1.GCC: (GNU) 7.
 0020 332e3120 32303138 30373132 20285265  3.1 20180712 (Re
 0030 64204861 7420372e 332e312d 31352900  d Hat 7.3.1-15).
 0040 00                                   .
```

(note the absence of a clang version string)

However, LLD provides no such opt-out. Or if it does, it doesn't use the same argument as Clang, and I couldn't find another reference to such a command in any of the docs or in the D that landed the feature:

```console
$ clang -fuse-ld=lld -Qn -Xlinker -Qn x.c
ld.lld: error: unknown argument '-Qn'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
$ clang -fuse-ld=lld -Qn -Xlinker -fno-ident x.c
ld.lld: error: unknown argument '-fno-ident'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

I think the solution here is to add support for `-Qn` and switch on it somewhere around

https://github.com/llvm/llvm-project/blob/4b8fdb61afe3444e9b54c9c1d9fbb6cd928b9541/lld/ELF/SyntheticSections.cpp#L69-L91

**Comment by jonhoo** [comment]
Sure! The use-case in my case is that I'm operating a build orchestration system at `$WORK` where builds cascade — that is, if package A depends on package B, and package B changes, package A is re-built. And I want to ensure that the build outputs of A don't change unnecessarily (i.e., are as reproducible as possible) so that downstream re-builds are necessary less often. The case where this came up was A = Rust, B = Clang. Rust is a bootstrapping compiler, so it builds itself with itself, which means that the version of Clang _mostly_ doesn't matter. The only exception is that rustc still links with LLD, and as a result ends up with this "Linker" stanza. This, in turn, is a problem if the Clang package is updated from, say, 15.0.6 to 15.0.7, because it changes the `rustc` artifacts _solely_ in the form of the `.comment` section — everything else remains the same.

I don't want to remove all the `.comment` sections because Rust _also_ puts things in there (iirc — I can double-check) which I _would_ want to keep. I _just_ want to avoid the specific version of Clang from leaking in there.

**Comment by MaskRay** [comment]
Thanks. I think the argument is not strong... For a version bump from 15.0.6 to 15.0.7, for Clang, it's very likely that the output doesn't change for the majority of cases but there is no guarantee. Linker output likely remains unchanged even across adjacent major versions but there is no guarantee, either.

Note, you can actually customize the message with an environment variable. So you want to drop the minor version numbers, you can do: `LLD_VERSION='Linker: LLD 15' clang -fuse-ld=lld ...`.

**Comment by jonhoo** [comment]
Ah, so, to be clear, I'm not trying to use this to _guarantee_ that builds are the same across Clang upgrades. But rather to minimize the number of re-builds necessary when the _only_ relevant change is the version number.

I did not know this was settable using an environment variable! Is that documented somewhere? Will make use of that, thanks 👍

**Comment by MaskRay** [comment]
`LLD_VERSION` is not documented... It's not something I feel comfortable to advice others to use. (Even if we added an option, I'd not recommend it, either, not to say that gold doesn't support customizing it...)

**Comment by MaskRay** [comment]
Documented in https://reviews.llvm.org/D143600

I'll mention this difference in "LLD and GNU linker incompatibilities" so that hopefully searching `.comment lld` in search engines will find it!
