### ISSUE TITLE
[MSVC] LLVM failed to build due to error LNK2019 on Windows

### ISSUE THREAD

**Issue by Zhaojun-Liu** [llvm/llvm-project#60573]
**Description:**
We update the commit of LLVM, and it built failed due to the below error, could you please take a look? Thanks.
```
NVPTXArch.obj : error LNK2019: unresolved external symbol _cuGetErrorString@8 referenced in function "int __cdecl handleError(enum cudaError_enum)" (?handleError@@YAHW4cudaError_enum@@@Z) [F:\gitP\llvm\llvm-project\build_x86\tools\clang\tools\nvptx-arch\nvptx-arch.vcxproj]
         NVPTXArch.obj : error LNK2019: unresolved external symbol _cuInit@4 referenced in function _main [F:\gitP\llvm\llvm-project\build_x86\tools\clang\tools\nvptx-arch\nvptx-arch.vcxproj]
         NVPTXArch.obj : error LNK2019: unresolved external symbol _cuDeviceGet@8 referenced in function _main [F:\gitP\llvm\llvm-project\build_x86\tools\clang\tools\nvptx-arch\nvptx-arch.vcxproj]
         NVPTXArch.obj : error LNK2019: unresolved external symbol _cuDeviceGetCount@4 referenced in function _main [F:\gitP\llvm\llvm-project\build_x86\tools\clang\tools\nvptx-arch\nvptx-arch.vcxproj]
         NVPTXArch.obj : error LNK2019: unresolved external symbol _cuDeviceGetAttribute@12 referenced in function _main [F:\gitP\llvm\llvm-project\build_x86\tools\clang\tools\nvptx-arch\nvptx-arch.vcxproj]
         F:\gitP\llvm\llvm-project\build_x86\RelWithDebInfo\bin\nvptx-arch.exe : fatal error LNK1120: 5 unresolved externals [F:\gitP\llvm\llvm-project\build_x86\tools\clang\tools\nvptx-arch\nvptx-arch.vcxproj]
```
The commit we used: bccf5999d38f14552f449618c1d72d18613f4285

**Repro steps:**
1. git clone https://github.com/llvm/llvm-project F:\gitP\llvm\llvm-project
2. git -C "F:\gitP\llvm\llvm-project" rev-parse --git-dir
3. git -C "F:\gitP\llvm\llvm-project" clean -xdf
4. git -C "F:\gitP\llvm\llvm-project" fetch --recurse-submodules=no --force
5. git -C "F:\gitP\llvm\llvm-project" reset --hard bccf599
6. git -C "F:\gitP\llvm\llvm-project" remote prune origin
7. mkdir F:\gitP\llvm\llvm-project\build_x86 and cd F:\gitP\llvm\llvm-project\build_x86
8. cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DLLVM_ENABLE_PROJECTS="clang" ..\llvm
9. msbuild /maxcpucount:4 /p:Platform=Win32 /p:Configuration=RelWithDebInfo /p:PreferredToolArchitecture=x64 LLVM.sln /t:Rebuild 2>&1

**Expected result:**
build successfully.

**Actural Result:**
[build.log](https://github.com/llvm/llvm-project/files/10671194/build.log)

Attached a repro file (cd linkrepro folder, execute link.exe @link.rsp):
[linkrepro.zip](https://github.com/llvm/llvm-project/files/10671206/linkrepro.zip)

**Comment by efriedma-quic** [comment]
CC @jhuber6 @shiltian

**Comment by jhuber6** [comment]
I have absolutely zero experience with Windows programming, so bear with me. I do not know why these are unresolved. Does your system have CUDA installed? Or is this using the dynamic fallback.

**Comment by Zhaojun-Liu** [comment]
@jhuber6 I can't find CUDA installed on my system with using command 'where cuda', but I found cuda related path in the environment variable (C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;). This issue appears when we update the commit of LLVM. If there is anything else to offer, please let me know, I will try my best.

**Comment by jhuber6** [comment]
Thanks, I'm just trying to figure out the state of the source file. If there is no CUDA found then we use `DYNAMIC_CUDA` as here https://github.com/llvm/llvm-project/blob/main/clang/tools/nvptx-arch/NVPTXArch.cpp#L20. Do you know if this is set in your build? My guess is that it's finding part of the CUDA library, so it's not building with `DYNAMIC_CUDA` set, but it can't link against it.

**Comment by Zhaojun-Liu** [comment]
Our build steps are as shown above, and no cuda-related settings have been made.

**Comment by jhuber6** [comment]
Here's the relevant line. As you can see it's definitely finding some CUDA library, but for whatever reason it's not linking against it correctly. I don't know if the functions are any different for Windows, but I don't see any library being linked in on the later line. Maybe CMake just doesn't link CUDA properly on Windows?
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x86\CL.exe /c /I"F:\gitP\llvm\llvm-project\build_x86\tools\clang\tools\nvptx-arch" /I"F:\gitP\llvm\llvm-project\clang\tools\nvptx-arch" /I"F:\gitP\llvm\llvm-project\clang\include" /I"F:\gitP\llvm\llvm-project\build_x86\tools\clang\include" /I"F:\gitP\llvm\llvm-project\build_x86\include" /I"F:\gitP\llvm\llvm-project\llvm\include" /I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" /Zi /nologo /W4 /WX- /diagnostics:column /MP /O2 /Ob1 /Oi /Oy- /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D NDEBUG /D _HAS_EXCEPTIONS=0 /D GTEST_HAS_RTTI=0 /D _LARGEFILE_SOURCE /D _FILE_OFFSET_BITS=64 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_SECURE_NO_WARNINGS /D _CRT_NONSTDC_NO_DEPRECATE /D _CRT_NONSTDC_NO_WARNINGS /D _SCL_SECURE_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /D UNICODE /D _UNICODE /D __STDC_CONSTANT_MACROS /D __STDC_FORMAT_MACROS /D __STDC_LIMIT_MACROS /D "CMAKE_INTDIR=\"RelWithDebInfo\"" /Gm- /MD /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /std:c++17 /Fo"nvptx-arch.dir\RelWithDebInfo\\" /Fd"nvptx-arch.dir\RelWithDebInfo\vc142.pdb" /external:W4 /Gd /TP /wd4141 /wd4146 /wd4244 /wd4267 /wd4291 /wd4351 /wd4456 /wd4457 /wd4458 /wd4459 /wd4503 /wd4624 /wd4722 /wd4100 /wd4127 /wd4512 /wd4505 /wd4610 /wd4510 /wd4702 /wd4245 /wd4706 /wd4310 /wd4701 /wd4703 /wd4389 /wd4611 /wd4805 /wd4204 /wd4577 /wd4091 /wd4592 /wd4319 /wd4709 /wd4324 /analyze- /errorReport:queue /we4238  /Zc:__cplusplus /bigobj -w14062 /Gw /EHs-c- "F:\gitP\llvm\llvm-project\clang\tools\nvptx-arch\NVPTXArch.cpp"```

**Comment by efriedma-quic** [comment]
Looking at the log, I think it's linking against the wrong library.  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64\cuda.lib is a 64-bit library, but this is a 32-bit LLVM build.  There's an LNK4272 warning which reports this.

I have no idea how to fix the issue, though.

**Comment by jhuber6** [comment]
There should be a line to specifically disable using the library in a 32-bit build though https://github.com/llvm/llvm-project/blob/main/clang/tools/nvptx-arch/CMakeLists.txt#L15. Is `LLVM_BUILD_32_BITS` not sufficient here?

**Comment by efriedma-quic** [comment]
LLVM_BUILD_32_BITS means "I'm using a compiler for a 64-bit target, but I want to override the target using `-m32`".  (Not sure how well it actually works, though; I vaguely recall some bug reports.)

If you want to detect whether a target is naturally 32-bit, you want something like `CMAKE_SIZEOF_VOID_P EQUAL 4`.

**Comment by jhuber6** [comment]
Let me know if https://github.com/llvm/llvm-project/commit/472393eff45002f60826f04fcc9261eeaa9f8691 fixes it.

**Comment by Zhaojun-Liu** [comment]
> Let me know if [472393e](https://github.com/llvm/llvm-project/commit/472393eff45002f60826f04fcc9261eeaa9f8691) fixes it.

ok, let me try.

**Comment by jhuber6** [comment]
Any update? Can we close the issue?

**Comment by Zhaojun-Liu** [comment]
@jhuber6 I tried the [472393e](https://github.com/llvm/llvm-project/commit/472393eff45002f60826f04fcc9261eeaa9f8691) locally, it worked. Thank you 😃.

**Comment by jhuber6** [comment]
Good to hear.
