### ISSUE TITLE
Bug: clang-format breaks function calls on user-defined-literals

### ISSUE THREAD

**Issue by Clueliss** [llvm/llvm-project#60576]
Currently clang-format removes spaces after user-defined-literals when calling functions on them. 
This makes code not compile anymore.

Clang Format version: `clang-format version 15.0.7 (Fedora 15.0.7-1.fc37)`

Example:
Before Formatting:
> $ cat test.cpp
> ```c++
> #include <chrono>
> using namespace std::chrono_literals;
> 
> int main() { auto x = 5s .count() == 5; }
> ```

> $ clang++ test.cpp && echo $?
> 0

After Formatting:
> $ clang-format test.cpp > testfmt.cpp

> $ cat testfmt.cpp
> ```c++
> #include <chrono>
> using namespace std::chrono_literals;
>
> int main() { auto x = 5s.count() == 5; }
> ```

> $ clang++ testfmt.cpp
> ```
> testfmt.cpp:4:24: error: invalid suffix 's.count' on integer constant
> int main() { auto x = 5s.count() == 5; }
>                        ^
> 1 error generated.
> ```

**Comment by rymiel** [comment]
I'm confused why `s.count` is attempted to be seen as an UDL if `s.count` isn't even a valid identifier. This looks like an issue of more than just clang-format

**Comment by Clueliss** [comment]
Not entirely sure but at least cppreference.com says that it is normal that this doesn't compile.

https://en.cppreference.com/w/cpp/language/user_literal#Notes
"Otherwise, a single invalid preprocessing number token (e.g., 1.0_E+2.0 or 4s.count) is formed, which causes compilation to fail."

**Comment by rymiel** [comment]
Thank you for clarifying, it does appear something that should be preserved, then

**Comment by owenca** [comment]
https://reviews.llvm.org/D143546
