### ISSUE TITLE
llvm-profdata.exe built without Zlib can't parse a profraw built with default settings

### ISSUE THREAD

**Issue by farzonl** [llvm/llvm-project#60593]
Version of LLVM:
 LLVM-15.0.7-win64.exe
OS:
Windows 10 and 11

How I built my project
`gn gen out/Release --args="is_debug=false use_clang_coverage=true"
`
command run:
`llvm-profdata.exe merge -o coverage.profdata default.profraw
`
Error:
```
warning: default.profraw: profile uses zlib compression but the profile reader was built without zlib support
error: no profile can be merged
```

Mitigation steps:
https://lists.llvm.org/pipermail/llvm-dev/2017-July/115565.html
Looks like I would have to recompile my project so that proraws are not compressed for Windows. Or build LLVM myself?

Expected Behavior:
On both Linux and MacOS I can run the profraw attached in the zip  through llvm-profdata

Expected Fix. add Zlib support for the Windows build.

[default.zip](https://github.com/llvm/llvm-project/files/10679786/default.zip)

**Comment by MaskRay** [comment]
This works as intended. You'll have to obtain an `llvm-profdata` with `LLVM_ENABLE_ZLIB` support :(

**Comment by farzonl** [comment]
@MaskRay my ask is if the official windows builds could switch to LLVM_ENABLE_ZLIB so there would be parity of behavior between os versions.

**Comment by MaskRay** [comment]
Raise a topic about this on https://discourse.llvm.org/c/infrastructure/release-testers/66 ?
