### ISSUE TITLE
[libc++] Should `num_get::do_get` accept `"inf"` and `"nan"`?

### ISSUE THREAD

**Issue by frederick-vs-ja** [llvm/llvm-project#60597]
Currently libc++'s `std::num_get::do_get` overloads for floating point types accept characters `'i'`, `'I'`, `'n'`, and `'N'` during parsing in order to parse `"inf"`, `"nan"`, and variants with uppercase letters.

https://github.com/llvm/llvm-project/blob/af128791464810123bcd60a6d9d0902b5c550aef/libcxx/include/locale#L465

https://github.com/llvm/llvm-project/blob/af128791464810123bcd60a6d9d0902b5c550aef/libcxx/include/locale#L553

https://github.com/llvm/llvm-project/blob/af128791464810123bcd60a6d9d0902b5c550aef/libcxx/src/locale.cpp#L4793

However, [LWG2381](https://cplusplus.github.io/LWG/issue2381) clarified that `'i'`, `'I'`, `'n'`, and `'N'` are not parsed (and hence `"inf"` and `"nan"` are rejected).

I guess `'i'`, `'I'`, `'n'`, and `'N'` should only be accepted in some extension mode (e.g. perhapes when `__STRICT_ANSI__` is not defined?), and `'p'` and `'P'` should be rejected in C++03 mode.

This seems implementable by using different end offsets in different modes instead of the fixed 32:
- 26 in C++03 (patched by [LWG221](https://cplusplus.github.io/LWG/issue221)),
- 28 in C++11 and later (patched by [LWG2381](https://cplusplus.github.io/LWG/issue2381)), or
- 32 in extension modes.

**Comment by philnik777** [comment]
We don't have LWG2381 implemented, and we implement C++11 in C++03 mode (as far as possible). Please check https://libcxx.llvm.org/Status/Cxx2b.html before reporting a not-yet implemented paper/LWG issue as a bug to avoid tracking it in multiple places.
