### ISSUE TITLE
[RISCV] Backport db6bee to 16.x release branch

### ISSUE THREAD

**Issue by preames** [llvm/llvm-project#60608]
This change fixes a recent and high impact regression.  The flawed logic was introduced in Dec 22, by change [844430bcc377](https://reviews.llvm.org/rG844430bcc3778094ac0e0dd085062809b7f6d666).

This was recently exposed in a stage2 build of llvm-tablegen when we switched from using llvm::Optional to std::optional. The stars aligned in just the wrong way, and we started actively miscompiling idiomatic optional usage. std::optional<uint32_t> appears to use the top 32 bits of the word on RV64 for its tag.

**Comment by asb** [comment]
/cherry-pick 604cc68b587d8b db6bee5fec0d7fdfc18005c5c5ccd15f1ede945d
