### ISSUE TITLE
LLVM 15 packages don't appear in the downloads page

### ISSUE THREAD

**Issue by pbarrio** [llvm/llvm-project#60604]
When I clock on "Download now: LLVM 15.0.7" in the main llvm.org page, I get redirected to the LLVM Download Page where I can only see releases up to LLVM 14.0.6.

Is there a plan to add LLVM 15 releases to that page? Thanks!

@tru FYI.

**Comment by tru** [comment]
Hmm - all the releases has been there before - maybe it got reverted in the latest things that @tstellar has been working on. You can always find the releases here on GitHub meanwhile.

**Comment by JOE1994** [comment]
As of March 13 2024, UTC 8:38 AM,
links to LLVM 15 package downloads are available at https://releases.llvm.org/download.html .
