### ISSUE TITLE
Clang compiling to WebAssembly with multivalue and wasm-opt fails

### ISSUE THREAD

**Issue by fluffyball9** [llvm/llvm-project#60613]
Compiling to WebAssembly using clang with multivalue and wasm-opt on path build fails because clang doesn't automatically pass `--enable-multivalue` to wasm-opt. This parameter should be automatically passed to wasm-opt.

**Comment by tlively** [comment]
@fluffyball9, can you share a clang driver command that reproduces the issue? I wonder if this is caused by the target features section being stripped somehow.

**Comment by fluffyball9** [comment]
The simplest arguments that reproduces the issue are `--target=wasm32 -mmultivalue -Xclang -target-abi -Xclang experimental-mv -nostdlib -O3 -s -Wl,--export-dynamic,--allow-undefined,--gc-sections`. Based on what I've tried, it fails with any level of optimization except of `O0`.

**Comment by fluffyball9** [comment]
If I run clang with `-c` and use wasm-dis, the sections at the end of the file are
```
 ;; custom section "linking", size 579
 ;; custom section "reloc.CODE", size 299
 ;; custom section "producers", size 93
 ;; features section: mutable-globals, sign-ext, multivalue
```

**Comment by fluffyball9** [comment]
@tlively I'm using wasm-opt version 112. After linking, it seems like the features section is removed.

**Comment by tlively** [comment]
Ah, I noticed that it had optimized `main` out entirely. If I add `--export=main`, then I can reproduce the error. investigating further now.

**Comment by tlively** [comment]
Ok, so the problem is that the `-s` argument tells the linker to strip all sections, so the target feature section is being stripped. @sbc100, should we make it so that `--strip-all` does not actually strip the target features section? IIRC, wasm-objdump and wasm-ld are inconsistent here.

**Comment by dschuff** [comment]
(did you mean `wasm-objcopy` rather than `wasm-objdump`?)

**Comment by dschuff** [comment]
I confirmed that `llvm-opjcopy`/`llvm-strip` does not strip the target feature section with `--strip-all` (see https://github.com/llvm/llvm-project/blob/main/llvm/lib/ObjCopy/wasm/WasmObjcopy.cpp#L76). It only strips sections that it actually understands (linking/reloc, debug, name, producers). Probably makes sense for `wasm-ld` to do the same?

**Comment by sbc100** [comment]
To me that would seem to contradict that meaning of `--strip-all`.    I think if you pass `--strip-all` the linker you are kind of opting out of being able to run any post-link optimizations .    If you want to do post-link stuff like wasm-opt, you should probably be relying on that tool to do that final stripping.

I guess that it might be more ergonomic just to never strip the target-features section, but what if I'm a user who actually wants to pass `--strip-all` and then ship the result of that to production.  I think having a target-features section in that case would go against the user intent.

How about this:  Clang can detect if its going to run wasm-opt after wasm-ld and in that case inject some kind of flag (perhaps a new `--preserve-features`) to tell wasm-ld about this.

**Comment by dschuff** [comment]
Yeah, I guess it's the driver's job to manage the tool pipeline, including any flags that affect post-link opt, so moving the logic to the driver makes sense. I think `llvm-objcopy/llvm-strip`'s `-keep-section` flag overrides the stripping and `remove-section` flags (see link above), but I'm not sure if lld has any logic like that.
