### ISSUE TITLE
[ICE] multidimensional subscript operator segfaults in requires clause

### ISSUE THREAD

**Issue by ldalessa** [llvm/llvm-project#60621]
The following example produces an ICE.
```c++
auto foo(auto a, auto... i) -> decltype(auto) {
    if constexpr (requires { a[i...]; }) {
        return a[i...];
    }
    else {
        return a;
    }
}

int x = foo(1);
```

Live example: https://godbolt.org/z/EMnohMWYh

**Comment by tbaederr** [comment]
Looks similar to https://github.com/llvm/llvm-project/issues/60505

**Comment by shafik** [comment]
Looks fixed in trunk: https://godbolt.org/z/zacMdrznb

CC @cor3ntin

**Comment by cor3ntin** [comment]
I believe this was https://github.com/llvm/llvm-project/commit/2528f1c84588f4a549c12dd1435cbba4a502a077
Not sure why I forgot to tag the issues  :/
