### ISSUE TITLE
Regression Clang-cl 16: Escape sequences in #line

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#60624]
Issue found when testing Clang-cl 16 on our codebase.
We have some files that are created with flex&bison, which contain the following:
#line 264 "path\to\parser.y" // lalr1.cc:598

With clang-cl 13, this is not giving any issues.
In clang-cl 16, it now reports the following: `expected '{' after '\o' escape sequence`

**Comment by tru** [comment]
@AaronBallman any idea if this could indicate a regression or who might know?

**Comment by AaronBallman** [comment]
The `#line` directive of that form is: `# line digit-sequence " s-char-sequence_opt " new-line` and s-char-sequence a sequence of s-char which includes escape sequences. This is true in both C (6.10.5p5 and 6.4.5p1) and C++ (http://eel.is/c++draft/cpp.line#4 and http://eel.is/c++draft/lex.string#nt:s-char-sequence)

`\o{...}` is an octal escape sequence (http://eel.is/c++draft/lex.ccon#nt:octal-escape-sequence), which is a numeric-escape-sequence, which is an escape-sequence.

So I think this behavior is at least somewhat expected. However, there is a Core Issue that just got opened last week about this in C++ (https://wg21.link/cwg2693), so it's a bit of an open question still.

**Comment by tru** [comment]
I am going to close this unless you disagree. It just seems like it behaves as expected now instead of having a more undefined behavior before.

**Comment by JVApen** [comment]
I agree this can be closed
