### ISSUE TITLE
libc++-16 regression: unique_ptr no longer works for incomplete type 

### ISSUE THREAD

**Issue by vogelsgesang** [llvm/llvm-project#60620]
In 16.0.0-rc2, the following code

```cpp
#include <memory>

struct ForwardDeclared;

struct MyStruct {
   std::unique_ptr<ForwardDeclared> member;
   MyStruct() {}
   ~MyStruct();
};
```

now produces the error

```console
In file included from clang_regression.cpp:1:
In file included from external/clang_linux/include/c++/v1/memory:898:
In file included from external/clang_linux/include/c++/v1/__memory/shared_ptr.h:31:
external/clang_linux/include/c++/v1/__memory/unique_ptr.h:63:19: error: invalid application of 'sizeof' to an incomplete type 'ForwardDeclared'
    static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");
                  ^~~~~~~~~~~
external/clang_linux/include/c++/v1/__memory/unique_ptr.h:297:7: note: in instantiation of member function 'std::default_delete<ForwardDeclared>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
external/clang_linux/include/c++/v1/__memory/unique_ptr.h:263:75: note: in instantiation of member function 'std::unique_ptr<ForwardDeclared>::reset' requested here
  _LIBCPP_INLINE_VISIBILITY _LIBCPP_CONSTEXPR_SINCE_CXX23 ~unique_ptr() { reset(); }
                                                                          ^
clang_regression.cpp:7:4: note: in instantiation of member function 'std::unique_ptr<ForwardDeclared>::~unique_ptr' requested here
   MyStruct() {}
   ^
clang_regression.cpp:3:8: note: forward declaration of 'ForwardDeclared'
struct ForwardDeclared;
       ^
1 error generated.
```

To my understanding, this is in violation of the standard which states:
* https://eel.is/c++draft/unique.ptr#general-4.sentence-3: The template parameter T of unique_­ptr may be an incomplete type[.](https://eel.is/c++draft/unique.ptr#general-4.sentence-3)
* https://eel.is/c++draft/unique.ptr#dltr.general-2: The template parameter T of default_­delete may be an incomplete type[.](https://eel.is/c++draft/unique.ptr#dltr.general-2.sentence-1)

AFAICT, the two sentences
* https://eel.is/c++draft/unique.ptr#dltr.dflt-3: T is a complete type for `default_­delete::operator()(T* ptr) const`
* https://eel.is/c++draft/unique.ptr#single.dtor-note-1: for `~unique_ptr`: [Note 1: The use of default_­delete requires T to be a complete type[.](https://eel.is/c++draft/unique.ptr#single.dtor-1.sentence-1) — end note]

do not apply for this code snippet, as I am not calling `~unique_ptr`. The destructor `~MyStruct()` is only declared, but not implemented in the header

**Comment by philnik777** [comment]
This has nothing to do with your destructor. If your default constructor throws, the destructor of the `unique_ptr` gets executed. You might be able to fix it by `= default`ing the default constructor, or by defining the constructor out-of-line if it's non-trivial. https://godbolt.org/z/x4KMeav1b

**Comment by vogelsgesang** [comment]
That makes a lot of sense, thanks for the explanation! I did not understand how the `~unique_ptr` constructor could be called from my `MyStruct` constructor.

This change is breaking quite a bit of code for us. Given that we relied on "sheer luck"/undefined behavior so far, I am more than willing to fix our code base :)

I was caught a bit off-guard by this breakage, though. Do think this might be a more widespread issue also for other projects?

If so, does it make sense to include something in the https://github.com/llvm/llvm-project/blob/release/16.x/libcxx/docs/ReleaseNotes.rst#api-changes ? Happy to draft something and post it for review, if we agree that this is worth mentioning

**Comment by vogelsgesang** [comment]
Ok. Not sure what the exact regression here is. I just realized that my reproducer also doesn't work in libc++ 15.0.7.
However, for our main code base, I am seeing that a similar pattern used to work in 15.0.7 but no longer works in 16.0.0-rc2.

I will keep investigating this on our side and report back afterwards

**Comment by vogelsgesang** [comment]
Closing this bug. Something changed between Clang/libc++ 15 and Clang/libc++ 16, so that the code from our internal code base no longer compiles. I don't know what exactly changed between the versions and unfortunately I am not able to share the original code. My simplified repro above does not show the regression, as that code already didn't compile on Clang/libc++15, either. Based on @philnik777's explanation, I now understand why our code is incorrect, so I will just fix our code base accordingly
