### ISSUE TITLE
clang-tidy: bugprone-unchecked-optional-access docs refer to a google-internal document

### ISSUE THREAD

**Issue by mineo** [llvm/llvm-project#60633]
https://github.com/llvm/llvm-project/blob/e50a508b5c3d3d814340e8818c757295d27c48dd/clang-tools-extra/docs/clang-tidy/checks/bugprone/unchecked-optional-access.rst says "See go/optional-style-recommendations for more information on that topic". I think "go/" is some google-internal thing. I think having access to that document (or a summary of it) would be great to have, especially to understand why `std::optional::value` is not considered safe access, even if it's required to throw an exception if the optional does not contain a value.

**Comment by dc03** [comment]
@ymand Would it be possible for you to provide a link or an explanation for the above? Pinging you as git blame shows you as the committer.

**Comment by whisperity** [comment]
> even if it's required to throw an exception

I would guess the main reason lies somewhere around the fact that `-fno-exceptions` disables this requirement.
