### ISSUE TITLE
Assertion failure in MachineUniformityAnalysis usesValueFromCycle

### ISSUE THREAD

**Issue by jayfoad** [llvm/llvm-project#60638]
On this test case:
```ll
define amdgpu_cs void @f() {
bb:
  br label %bb1
bb1:
  %i = call i32 @llvm.amdgcn.raw.atomic.buffer.load.i32(<4 x i32> zeroinitializer, i32 0, i32 0, i32 0)
  %i2 = icmp eq i32 %i, 0
  br i1 %i2, label %bb3, label %bb1
bb3:
  %i4 = call i32 @llvm.amdgcn.raw.atomic.buffer.load.i32(<4 x i32> zeroinitializer, i32 0, i32 0, i32 0)
  ret void
}
declare i32 @llvm.amdgcn.raw.atomic.buffer.load.i32(<4 x i32>, i32, i32, i32)
```
I get:
```console
$ llc -march=amdgcn -mcpu=gfx1030 -o /dev/null -global-isel
llc: /home/jayfoad2/git/llvm-project/llvm/lib/CodeGen/MachineUniformityAnalysis.cpp:100: bool llvm::GenericUniformityAnalysisImpl<llvm::GenericSSAContext<llvm::MachineFunction>>::usesValueFromCycle(const llvm::MachineInstr &, const llvm::MachineCycle &) const [ContextT = llvm::GenericSSAContext<llvm::MachineFunction>]: Assertion `!isAlwaysUniform(I)' failed.
```
@sameerds @arsenm FYI

**Comment by jayfoad** [comment]
Hmm, maybe this is a dubious test case because it's using something that looks like an intrinsic but isn't (in upstream LLVM): `llvm.amdgcn.raw.atomic.buffer.load.i32`

**Comment by jayfoad** [comment]
Here's a test case that provokes the same assertion failure without using any calls or intrinsics:
```
define void @f() {
bb:
  br label %bb1
bb1:
  %i = phi i32 [ 0, %bb ], [ %i4, %bb11 ]
  %i2 = phi i32 [ 0, %bb ], [ %i12, %bb11 ]
  br label %bb3
bb3:
  %i4 = phi i32 [ %i, %bb1 ], [ 0, %bb3 ]
  %i5 = icmp slt i32 %i, 0
  br i1 %i5, label %bb3, label %bb6
bb6:
  %i7 = getelementptr [2 x i32], ptr null, i32 0, i32 %i2
  %i8 = load i32, ptr %i7
  %i9 = icmp slt i32 %i8, 0
  br i1 %i9, label %bb11, label %bb10
bb10:
  ret void
bb11:
  %i12 = or i32 %i2, 1
  br label %bb1
}
```

**Comment by jayfoad** [comment]
@Pierre-vh FYI

**Comment by ssahasra** [comment]
FYI, @sameerds is my personal ID on github that I rarely check.

**Comment by yashssh** [comment]
assert(!isAlwaysUniform(I)) in [MachineSSAContext::usesValueFromCycle](https://github.com/llvm/llvm-project/blob/8b28500f60b716a353b733a0111aae6a4a5e9854/llvm/lib/CodeGen/MachineUniformityAnalysis.cpp#L98) is failing here when the function is called with an always uniform intrinsic(@llvm.amdgcn.if.break). Either that assert need to be modified to make is consistent with the if condition in [SSAContext::usesValueFromCycle](https://github.com/llvm/llvm-project/blob/8b28500f60b716a353b733a0111aae6a4a5e9854/llvm/lib/Analysis/UniformityAnalysis.cpp#L74) or the caller had to make sure to perform this check before calling this function. I can submit a patch?

**Comment by jayfoad** [comment]
@gandhi56 FYI

**Comment by gandhi56** [comment]
+1 for @yashssh 's comment.

**Comment by jayfoad** [comment]
It looks to me like `analyzeTemporalDivergence` should probably check `isAlwaysUniform` _before_ calling `usesValueFromCycle`, instead of the other way around.
