### ISSUE TITLE
[Flang][OpenMP] Semantic error not issued when constants are present in data-sharing clause

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#60646]
Errors are not issued when constants are present in data-sharing clauses. See reproducer below.

**Reproducer**
```f90
program mn
  integer, parameter :: x = 2
  !$omp parallel shared(x)
  !$omp end parallel
end program
```

**Comment by tblah** [comment]
The 5.2 standard explicitly allows "named constants" in `shared`. (page 99 line 5)
