### ISSUE TITLE
libc fails to build on macos due to regex issue with triple detector

### ISSUE THREAD

**Issue by rickmark** [llvm/llvm-project#60666]
In `LLVMLibCArchitectures.cmake` line 88:

```cmake
string(REGEX MATCH "Target: [-_a-z0-9]+[ \r\n]+"
```

should read:

```cmake
string(REGEX MATCH "Target: [-_a-z0-9.]+[ \r\n]+"
```

Because triples on macOS will include the Darwin version number

**Comment by lntue** [comment]
The fix is applied with https://github.com/llvm/llvm-project/commit/e9e43e31d3bdce4f303793127f8444f16212454f
