### ISSUE TITLE
[clang-tidy] readability-identifier-naming hungarian primitive types is missing "unsigned char"

### ISSUE THREAD

**Issue by amurzeau** [llvm/llvm-project#60670]
Hi,

When formating code with clang-tidy's readability-identifier-naming checker with Hungarian notation enabled, `unsigned char` has no hungarian prefix.
I expect to have `uc` for `unsigned char` type.

`char` is defined and defaults to `c`, likewise `unsigned short` defaults to `us`.

Can `readability-identifier-naming.HungarianNotation.PrimitiveType.unsigned-char` be added and defaulted to `uc` ?

**Comment by amurzeau** [comment]
I think I have a patch that I can put to review on phabricator.
I never done this here on LLVM project, but if patches about this are welcome, I can contribute that patch.

**Comment by EugeneZelenko** [comment]
@amurzeau: See https://llvm.org/docs/Phabricator.html.
