### ISSUE TITLE
ninja check-clang command fails with multiple errors despite no errors during compilation process

### ISSUE THREAD

**Issue by vani2620** [llvm/llvm-project#60676]
Running on Windows Version 10.0.19044.2486

Steps to reproduce:
1) Cloned git repo of [Moore HDL](https://github.com/fabianschuiki/moore)
2) Ran `git submodule update --init --recursive`
3) Built and compiled with `cmake -G Ninja ..\llvm -DCMAKE_BUILD_TYPE=DEBUG -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_PROJECTS="mlir;lld;clang" -DLLVM_INSTALL_UTILS=ON -DLLVM_TARGETS_TO_BUILD="host;RISCV"` followed by `ninja`. Build and compilation both succeeded.
4) Ran `ninja check-mlir` with [this](https://pastebin.com/KF6xeSPx) output. (I have no clue if this is relevant, I included it because it's the last command I ran that I can still view the output of.)
5) Ran `ninja check-clang`. Build subcommand failed, full command line output [here](https://pastebin.com/vfdb7ykr)

**Comment by AaronBallman** [comment]
Looking at the build logs in step 5, I see:

> The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss

I don't think git messes with text encodings when you do a clone (but I could be wrong, I'm far from a git expert), but I think you may need to pass `/utf-8` to MSVC to tell it to interpret the source code as UTF-8 rather than the system code page.

**Comment by vani2620** [comment]
When would I pass that in?

**Comment by vani2620** [comment]
Ah, found it. I have to pass `-DCMAKE_CXX_FLAGS="/utf-8" -DCMAKE_C_FLAGS="/utf-8"` per [this discussion](https://reviews.llvm.org/D90116). Thank you!
