### ISSUE TITLE
PIE Default for Optimizing Table Loads (Was: "Missed Optimization: Superfluous Addressing on Data Load")

### ISSUE THREAD

**Issue by geometrian** [llvm/llvm-project#60685]
Consider the following simple code (which converts a hex digit character, case-insensitive, to an `int`):
```cpp
int hexchar_to_int(char hexchar) {
	constexpr static unsigned char const data[] = {
		255, 10,11,12,13,14,15, 255,255,255,255,255,255,255,255,255, 0,1,2,3,4,5,6,7,8,9
	};
	return data[ hexchar & 0b00011111 ];
}
```
GCC compiles this to:
```asm
hexchar_to_int_table(char):
        and     edi, 31
        movzx   eax, BYTE PTR hexchar_to_int(char)::data[rdi]
        ret
```

However, Clang has an extra instruction:
```asm
hexchar_to_int(char):
        and     edi, 31
        lea     rax, [rip + hexchar_to_int(char)::data]
        movzx   eax, byte ptr [rdi + rax]
        ret
```

I believe GCC's output is strictly superior.

**Comment by zero9178** [comment]
This is not really a code issue but just your clang and GCC using different defaults. In particular, the clang you used to get that output seems to default to using `-fpie`, aka creating a position independent executable, while the GCC you used does not. 

Whether this is a good default is another topic, but Clang recently switched to it by default, as have the GCC installations of many Linux distros (GCCs build system makes this default configurable but turns it off by default).

Compiling with `-fpie` with GCC results in the same assembly as the clang output you showed: <https://godbolt.org/z/z6narrxqb>

Similarily, using Clang and using the `-fno-pie` flag makes clang generate the same assembly as the GCC output you showed:
https://godbolt.org/z/4TK78GTW9

**Comment by geometrian** [comment]
Thank you for the explanation! I thought the different addressing calculation might have a purpose, but I forgot to consider it was for PIE. There is no actual bug here :)
