### ISSUE TITLE
how does a pass written by new passmanager use getAnalysis()?

### ISSUE THREAD

**Issue by PressFforlove** [llvm/llvm-project#60699]
Hi there, I'm trying to use `getAnalysis()` method to get some information about DomTree or loops, and I tried to write a pass following the LLVM 15 document, it's works by use `AM.getResult<HelloAnalysis>(F);`，inside the template is an analysis pass which returns a `std::string`.

In my opinion, DomTree and LoopInfo are also **analysis** passes, so they should work too. when I try to use `auto &DT = getAnalysis<DominatorTree>();`, or `LoopInfo &LI = getAnalysis<LoopInfoWrapperPass>().getLoopInfo();`, which worked fine in a pass I written some month ago by `runOnModule` (by set `getAnalysisUsage`, and include the head of these modules). but when I use it in my pass written by new pass manager, the compiler complain like below:
```console
HelloWorldUse.cpp:62:16: error: ‘getAnalysis’ was not declared in this scope
     auto &DT = getAnalysis<DominatorTree>();
```
and
```console
error: expected primary-expression before ‘>’ token
     auto &DT = getAnalysis<DominatorTree>();
```
now I am so confused to the new pass manager and how to use `getAnalysis()` to use other pass's data or method in a `FunctionPass`. By the way, I also want to know how to get a `FunctionPass`'s data or method in another `FunctionPass`.
Any answer or link will be appreciated, thank you for help!

**Comment by nikic** [comment]
The NewPM syntax is `AM.getResult<DominatorTreeAnalysis>(F)`.
