### ISSUE TITLE
std::is_trivial gives incorrect answer with requires-clause on default constructor

### ISSUE THREAD

**Issue by danakj** [llvm/llvm-project#60697]
A class without a default constructor is not trivial. But a class with default constructors that are not eligible due to `requires` clause still is considered trivial by Clang. GCC and MSVC get this correct.

```cpp
#include <type_traits>

template <class T>
struct S {
    S()
    requires(std::is_trivially_default_constructible_v<T>) = default;

    S()
    requires(!std::is_trivially_default_constructible_v<T> &&
             std::is_default_constructible_v<T>) {}

    T t;
};

struct D {
    D(int i) : i(i) {}
    int i;
};
static_assert(!std::is_trivially_default_constructible_v<D>);
static_assert(!std::is_default_constructible_v<D>);
static_assert(!std::is_trivial_v<D>);

static_assert(!std::is_trivially_default_constructible_v<S<D>>);
static_assert(!std::is_default_constructible_v<S<D>>);

static_assert(std::is_trivial_v<S<int>>);
// Not default constructible should mean not trivial but clang
// incorrectly considers this type trivial.
static_assert(!std::is_trivial_v<S<D>>);
```

Godbolt: https://godbolt.org/z/azKW5YM4h

**Comment by royjacobson** [comment]
Thanks for the report!

I took a quick look and I think the problem is that `QualType::isTrivialType` is not synchronized with `CXXRecordDecl::isTrivial`. The type trait uses `QualType::isTrivialType` which returns the bad result. I think calling `isTrivial` in `isTrivialType` should fix this.

**Comment by royjacobson** [comment]
https://reviews.llvm.org/D143891

Interestingly, GCC also has a related problem: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108769
