### ISSUE TITLE
[AArch64] Indexed FMLA not supported

### ISSUE THREAD

**Issue by rj-jesus** [llvm/llvm-project#60706]
LLVM does not seem to assemble the [FMLA by element](https://developer.arm.com/documentation/ddi0596/2021-12/SIMD-FP-Instructions/FMLA--by-element---Floating-point-fused-Multiply-Add-to-accumulator--by-element--) instruction of the A64 instruction set. For example, the code below builds fine with GCC but fails with LLVM.
```c
int main(void)
{
  asm("fmla V23.2d, V0.2d, V6.2d");  // works
  asm("fmla V23.2d, V0.2d, V6.2d[0]");  // <-- problematic instruction
}
```
https://godbolt.org/z/E4aqvK1jh

Other “by element” instructions such as `fmul` are also affected.

CC @u99127

**Comment by davemgreen** [comment]
I believe it should be `fmla V23.2d, V0.2d, V6.d[0]`, without the 2 in the last element. The reference I have suggests that is correct, and GCC is accepting the other form as a convenience.

**Comment by u99127** [comment]
Ah thanks @davemgreen  - yeah looks right - I'd missed that in my reading earlier of the instruction.

**Comment by rj-jesus** [comment]
Yep thanks @davemgreen, I believe you are correct! I'll close this issue now.
