### ISSUE TITLE
Inline Assembly Dialect Option for clang-cl

### ISSUE THREAD

**Issue by geometrian** [llvm/llvm-project#60715]
Some performance-critical inline assembly for ia-32/amd64 compiles nicely with ordinary clang under Linux. Per [current practice](https://stackoverflow.com/a/58154963), `-masm=intel` is used to select Intel syntax for sanity (note that, as discussed at that link, various alternatives such as `.intel_syntax noprefix` are "problematic" on a technical level.) This works great.

However, on Windows with Visual Studio, there's clang-cl, and clang-cl does not recognize this option:
```text
clang-cl: warning: unknown argument ignored in clang-cl: '-masm=intel' [-Wunknown-argument]
```
Commentary for this specific argument appears to be nonexistent, and the [docs do not list](https://clang.llvm.org/docs/UsersManual.html#id12) it as supported. This is a problem because there does not seem to be an alternative way to select the assembly dialect in clang-cl. The dialect defaults to AT&T, which obviously causes various failures.

Please add support in clang-cl for `-masm=intel` or provide/document an alternate way of selecting inline assembler dialect.

**Comment by alvinhochun** [comment]
Have you tried `/clang:-masm=intel`?

**Comment by geometrian** [comment]
Have now, does what I want. Thanks!

The section "[The /clang: Option](https://clang.llvm.org/docs/UsersManual.html#the-clang-option)" comes immediately after the section for supported args, and `Xclang <arg>`, which I expect would also work, is actually *in* the list of supported arguments, so I really ought to have seen this . . .
