### ISSUE TITLE
Correct docs to say UBSan `unsigned-shift-base` is not actually undefined behaviour

### ISSUE THREAD

**Issue by seanm** [llvm/llvm-project#60712]
`clang/docs/UndefinedBehaviorSanitizer.rst` says:

"-fsanitize=unsigned-shift-base: check that an unsigned left-hand side of a left shift operation doesn’t overflow."

I suggest adding the sentence "Issues caught by this sanitizer are not undefined behavior, but are often unintentional."

According to https://reviews.llvm.org/D86000 it indeed is not UB.

That exact sentence is already present for several other UBSan options that are not actually checking for UB.

**Comment by aabhinavg** [comment]
This patch add the suggested sentences 
https://reviews.llvm.org/D146947

**Comment by seanm** [comment]
Great, thanks!  It looks like you may be missing a space between sentences though...

**Comment by aabhinavg** [comment]
I have updated the patch you can look and approve it if everything seems to be inline from your end . After that I can commit changes inside  clang/docs/UndefinedBehaviorSanitizer.rst and close these issue.
