### ISSUE TITLE
Incorrect use of memcpy in default assignment operator

### ISSUE THREAD

**Issue by zim-tis** [llvm/llvm-project#60734]
The AST of  Foo::operator = (const Foo &) in the following test:

```
struct Foo {
    int t[1000] = {};
};

int main() {
  Foo f;
  f = f;
}
```

obtained with the command line: 

`
clang++ -fsyntax-only -Xclang -ast-dump test.cpp
`

uses `__builtin_memcpy`  in its AST to perform the member copy:

|-CXXRecordDecl 0x5b11b80 <test.cpp:1:1, line:3:1> line:1:8 referenced struct Foo definition
[...]
| |-CXXMethodDecl 0x5b12698 <col:8> col:8 implicit used constexpr operator= 'Foo &(const Foo &) noexcept' inline default trivial
| | |-ParmVarDecl 0x5b127a8 <col:8> col:8 used 'const Foo &'
| | |-CompoundStmt 0x5b406f0 <col:8>
| |   |-CallExpr 0x5b40650 <col:8> 'void *'
| |   | |-ImplicitCastExpr 0x5b40638 <col:8> 'void *(*)(void *, const void *, unsigned long) noexcept' <BuiltinFnToFnPtr>
| |   | | -DeclRefExpr 0x5b405a0 <col:8> '<builtin fn type>' Function 0x5b40330 '__builtin_memcpy' 'void *(void *, const void *, unsigned long) noexcept
[...]

However, calling `memcpy`   is an undefined behavior when the origin and the source overlap, while the test is valid C++.
This link: https://godbolt.org/z/Mj61jzTnj shows that in the final assembly `__builtin_memcpy` is replaced by the standard `memcpy`.

A quick fix could be to use `memmove`/`__builtin_memmove` to do the copy.

**Comment by nikic** [comment]
LLVM's llvm.memcpy intrinsic has weaker requirements than C++ memcpy, see https://llvm.org/docs/LangRef.html#int-memcpy. In particular, the operands are allowed to be the same (but not overlap in any other way). The operands can also be null if the length is zero.

If a libcall lowering occurs, LLVM requires the libcall implementation to satisfy these constraints as well.
