### ISSUE TITLE
SROA does not propagate function attributes when replacing an indirect call

### ISSUE THREAD

**Issue by DavidSpickett** [llvm/llvm-project#60732]
This is best demonstrated on AArch64 but the issue applies to any function attribute.

In this example we have `setjmp`, which is a `returns_twice` function (once when you setup the jump, once when you use it later). On AArch64 we want to place a branch target ID instruction after calls to `setjmp`, in case the implementation jumps there in a specific way.

```
extern int __attribute__((returns_twice)) setjmp(void*);

void bbb(void) {
  setjmp(0);
  int (*fnptr)(void*) = setjmp;
  fnptr(0);
}
```
The example has a direct call to setjmp and an indirect call to setjmp. The latter is rather unlikely to ever happen, but this issue applies to all function attributes so I'm using it to demonstrate.

Compile it with:
```
$ ./bin/clang /tmp/test.c -o - -S -mbranch-protection=bti -O1
```
What I expect to happen is:
* The indirect call is converted into a direct call by SROA
* Since both calls are to a returns twice function, both should have a branch target ID instruction placed after them.

What happens is that only the first call is followed by a bti:
```
        .cfi_offset w29, -16
        mov     x0, xzr
        bl      setjmp
        hint    #36
        mov     x0, xzr
        bl      setjmp
```
GCC gets this right and both have a bti.
```
        mov     x0, 0
        bl      setjmp
        hint    36 // bti j
        mov     x0, 0
        bl      setjmp
        hint    36 // bti j
```
(bti is actually encoded as a hint instruction hence the hint mnemonic)

This is the IR:
```
$ ./bin/clang /tmp/test.c -o - -S -mbranch-protection=bti -O1 -emit-llvm
define dso_local void @bbb() local_unnamed_addr #0 {
entry:
  %call = call i32 @setjmp(ptr noundef null) #2
  %call1 = call i32 @setjmp(ptr noundef null) #3
  ret void
}

declare i32 @setjmp(ptr noundef) local_unnamed_addr #1

attributes #0 = { nounwind uwtable "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+fp-armv8,+neon,+outline-atomics,+v8a,-fmv" }
attributes #1 = { returns_twice "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+fp-armv8,+neon,+outline-atomics,+v8a,-fmv" }
attributes #2 = { nounwind returns_twice }
attributes #3 = { nounwind }
```
You can see that the direct call is tagged returns twice and the converted indirect call is not.

IR before and after SROA:
```
$ ./bin/clang /tmp/test.c -o - -S -mbranch-protection=bti -O1 -emit-llvm -mllvm --print-before-all -mllvm --print-after-all 2>&1 | less
*** IR Dump Before SROAPass on bbb ***
; Function Attrs: nounwind uwtable
define dso_local void @bbb() #0 {
entry:
  %fnptr = alloca ptr, align 8
  %call = call i32 @setjmp(ptr noundef null) #3
  call void @llvm.lifetime.start.p0(i64 8, ptr %fnptr) #4
  store ptr @setjmp, ptr %fnptr, align 8, !tbaa !7
  %0 = load ptr, ptr %fnptr, align 8, !tbaa !7
  %call1 = call i32 %0(ptr noundef null)
  call void @llvm.lifetime.end.p0(i64 8, ptr %fnptr) #4
  ret void
}
*** IR Dump After SROAPass on bbb ***
; Function Attrs: nounwind uwtable
define dso_local void @bbb() #0 {
entry:
  %call = call i32 @setjmp(ptr noundef null) #3
  %call1 = call i32 @setjmp(ptr noundef null)
  ret void
}
```
Prior to SROA the indirect call has no attributes. This is correct as there is no way from C to add them, and in any case, we didn't attempt to.

However, when SROA replaces the indirect call, it knows what its replacing it with. So it seems like it could carry the attributes forward into the new direct call.

I've used AArch64 BTI protection to demonstrate but the same applies to any function attribute.

**Comment by DavidSpickett** [comment]
Example with `cold` in addition to returns twice, to show this is not AArch64 specific.

```
define dso_local void @bbb() local_unnamed_addr #0 {
entry:
  %call = call i32 @setjmp(ptr noundef null) #2
  %call1 = call i32 @setjmp(ptr noundef null) #3
  ret void
}

; Function Attrs: cold returns_twice
declare i32 @setjmp(ptr noundef) local_unnamed_addr #1

attributes #0 = { nounwind uwtable "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+fp-armv8,+neon,+outline-atomics,+v8a,-fmv" }
attributes #1 = { cold returns_twice "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+fp-armv8,+neon,+outline-atomics,+v8a,-fmv" }
attributes #2 = { cold nounwind returns_twice }
attributes #3 = { nounwind }
```
The direct call is cold/nounwind/returns_twice and the converted indirect call is only nounwind.

**Comment by nikic** [comment]
returns_twice is part of the function attributes of `@setjmp`. There is no need for it to be part of the call attributes as well, because function attributes are inherited to the call-site.

The problem is that https://github.com/llvm/llvm-project/blob/8c7cfa357280dd93d33b10bbba0fe33797e27d63/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp#L7164 does that `hasFnAttr` query by manually fetching the AttributeList of just the call, instead of doing the call directory on the CallBase, which will handle attribute inheritance correctly.

**Comment by efriedma-quic** [comment]
In general, indirect calls should have all ABI-relevant attributes already applied by the frontend; there shouldn't be any need to "propagate" attributes from the definition to the call.

For setjmp() specifically, it's undefined behavior to use it like that.

**Comment by DavidSpickett** [comment]
> returns_twice is part of the function attributes of @setjmp. There is no need for it to be part of the call attributes as well, because function attributes are inherited to the call-site.

Ok, so why is returns_twice part of the direct call as well? That's what confused me. If the optimisation is producing code that is "as if" you called the function directly instead of indirectly, why is the result not the same as the first direct call?

```
define dso_local void @bbb() local_unnamed_addr #0 {
entry:
  ; Somehow the returns_twice has been added to this call when it could have been got from setjmp.
  ;  { nounwind returns_twice }
  %call = call i32 @setjmp(ptr noundef null) #2
  ; This which is supposed to be equivalent, does not have it.
  ; { nounwind }
  %call1 = call i32 @setjmp(ptr noundef null) #3
  ret void
}

declare i32 @setjmp(ptr noundef) local_unnamed_addr #1

attributes #1 = { returns_twice ... }
```
> does that hasFnAttr query by manually fetching the AttributeList of just the call, instead of doing the call directory on the CallBase, which will handle attribute inheritance correctly.

Thanks! I will fix that at least.

> In general, indirect calls should have all ABI-relevant attributes already applied by the frontend; there shouldn't be any need to "propagate" attributes from the definition to the call.

This example seems to show that some things are propagated to the call. The first direct call has returns_twice on it, but you're implying that one should look at the attributes of setjmp instead. That said, it didn't bring all the attributes of setjmp with it so perhaps there is a special case for it for other reasons.

> For setjmp() specifically, it's undefined behavior to use it like that.

Cool! I was pretty sure it was very unlikely but neglected to read the specifications.

**Comment by nikic** [comment]
> Ok, so why is returns_twice part of the direct call as well?

This is a frontend choice. Clang tends to apply all function attributes to both the function and the call site, even when not strictly necessary. For direct calls, it is sufficient for the attribute to be either on the function or the call site, but having it on both doesn't hurt either.

**Comment by DavidSpickett** [comment]
Got it. So best practice is to look at the the thing you are calling, as you suggested before. I will fix the BTI code.

Closing as working as expected. Thanks both for your help!
