### ISSUE TITLE
Warn when comparing two objects of the same type via a user-defined conversion

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#6074]
|  |  |
| --- | --- |
| Bugzilla Link | [5702](https://llvm.org/bz5702) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
Consider:

class PointerUnion { public: operator bool(); ... };
// Note: no operator== for PointerUnion

void foo() {
  PointerUnion a = getA(), b = getB();
  if(a == b) { // compares (bool)a == (bool)b
  }
}

Basically, when two objects of the same type T are compared, and semantic analysis succeeds because it converts both objects to some type U, that's almost always the wrong thing to do. Either the programmer meant to do something else, or he forgot to write an operator== for the class he's comparing.

Therefore, Clang should warn about such a situation.

If you can present counterexamples (i.e. cases where you have this situation, and it actually is what you want), please do.

**Comment by Quuxplusone** [comment]
Duplicate of #16355.

> If you can present counterexamples (i.e. cases where you have this situation, and it actually is what you want), please do.

I comment in depth over at #16355, but the TLDR is "`std::reference_wrapper<int>`."
