### ISSUE TITLE
Feat: Add Top Level Token Permissions to GitHub Workflows

### ISSUE THREAD

**Issue by joycebrum** [llvm/llvm-project#60750]
### Description

Hi, I work on behalf of the Google and the OpenSSF to help Open Source Projects to improve their Supply Chain Security.

Looking into some potential security improvements [Scorecard tool](https://github.com/ossf/scorecard) suggest, I saw that the top level permissions are not set on the project's github action workflows, so all write permissions are given ([Token-Permissions Check explanation](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions).

There are some risks involving having too much permissive workflows, such as 

- `statuses` - May allow an attacker to change the result of pre-submit checks and get a PR merged.
- `checks` - May allow an attacker to remove pre-submit checks and introduce a bug.
- `security-events` - May allow an attacker to read vulnerability reports before a patch is available. Should only be granted to recognized actions for uploading SARIF results.
- `deployments` - May allow an attacker to charge repo owner by triggering VM runs, and tiny chance an attacker can trigger a remote service with code they own if server accepts code/location variables unsanitized.
- `contents` - Allows an attacker to commit unreviewed code. Should only be granted to recognized packaging actions or commands.
- `packages` - Allows an attacker to publish packages. Should only be granted to recognized packaging actions or commands.
- `actions` - May allow an attacker to steal GitHub secrets by approving to run an action that needs approval.

If it is ok for you, let me know and I'll suggest a PR with the top level permissions set and all run level permission configured as needed.

### Additional Content
[About Permissions on GHA](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions)
`Use credentials that are minimally scoped` at [GitHub Security Guides](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-secrets)
[GitHub Security Guides - Restricting Permissions for Tokens](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#restricting-permissions-for-tokens)

**Comment by tstellar** [comment]
> If it is ok for you, let me know and I'll suggest a PR with the top level permissions set and all run level permission configured as needed.

Thanks for looking into this.  This would be great.  Thank you.

**Comment by joycebrum** [comment]
Just a FYI, I've opened the Patch at https://reviews.llvm.org/D144119 and added you as reviewer if that's ok.

**Comment by tstellar** [comment]
@joycebrum Would you also be able to review https://reviews.llvm.org/D143535 to check that I got the permissions right.

**Comment by joycebrum** [comment]
Closing this issue as completed. Thanks!
