### ISSUE TITLE
Missed expression re-association

### ISSUE THREAD

**Issue by jeremy-rifkin** [llvm/llvm-project#60754]
```cpp
int foo(int num) {
    if ((num * 3 + 6) / 3 != num + 2) __builtin_unreachable();
    return (num * 3 + 6) / 3 - num - 2;
}

int bar(int num) {
    if ((num * 3 + 6) / 3 != num + 2) __builtin_unreachable();
    return (num * 3 + 6) / 3 - (num + 2);
}
```

Both `foo` and `bar` are optimizable to `return 0;` but only `bar` is optimized fully <https://godbolt.org/z/v1qoqM1jq>, <https://alive2.llvm.org/ce/z/LhFsSL>.

**Comment by inclyc** [comment]
GVN does not treat `- num - 2` as the same as `- (num + 2)`.

https://godbolt.org/z/7Mz1ajr3a

**Comment by rotateright** [comment]
There's a more significant missed reassociation fold when the operations do not wrap:
https://alive2.llvm.org/ce/z/P66io8
https://alive2.llvm.org/ce/z/vghegw

We canonicalize to the mul+add form (rather than add+mul), so we need to look through the 'add' to match the common multiplier/divisor constant.

**Comment by rotateright** [comment]
Should be fixed after:
4966d8ebe1bbe5
And that was improved for an unsigned variation of the example shown here:
703423c26965cd2e

**Comment by jeremy-rifkin** [comment]
Thank you @rotateright!

**Comment by rotateright** [comment]
I think it's still possible to hit a similar bug if you're fuzzing these kinds of sequences. 

We probably need at least one more add/sub reassociation fold in InstCombine. I have a draft of that patch that I will clean up and post. Beyond that, it may still be worthwhile to improve GVN in some way as suggested earlier, but I don't know much about GVN.
