### ISSUE TITLE
[15->17trunk regression] Parameter packs in requires-clauses in deduction guides are considered non-constant

### ISSUE THREAD

**Issue by Alcaro** [llvm/llvm-project#60777]
```c++
template<typename... Ts>
constexpr bool True() { return true; }

template<typename T>
class A {
public:
    template<typename... Ts>
    A(T val, Ts... tail)
    requires (True<Ts...>())
    {}
};

int main() {
    A b(42);
}
```
Works on GCC, MSVC, and Clang 15.0.0. But on 17.0.0-26662ac010ef50e65e2774eab84f325aa09360fe, it fails with
```console
<source>:9:15: error: substitution into constraint expression resulted in a non-constant expression
    requires (True<Ts...>())
              ^~~~~~~~~~~~~
<source>:14:7: note: while checking constraint satisfaction for template '<deduction guide for A><int>' required here
    A b(42);
      ^
<source>:14:7: note: in instantiation of function template specialization '<deduction guide for A><int>' requested here
<source>:9:15: note: non-literal type '<dependent type>' cannot be used in a constant expression
    requires (True<Ts...>())
              ^
<source>:14:7: error: no viable constructor or deduction guide for deduction of template arguments of 'A'
    A b(42);
      ^
<source>:8:5: note: candidate template ignored: failed template argument deduction
    A(T val, Ts... tail)
    ^
<source>:5:7: note: candidate template ignored: could not match 'A<T>' against 'int'
class A {
      ^
```
https://godbolt.org/z/sh7TrPGE1

I also found an ICE-on-invalid that I suspect may have the same root cause and/or same solution: https://godbolt.org/z/7qGTddsYh If it doesn't, feel free to ignore it; if this bug is fixed but the ICE remains, I'll file a new bug.

**Comment by shafik** [comment]
May be related to: https://github.com/llvm/llvm-project/issues/58452

CC @erichkeane

**Comment by AaronBallman** [comment]
Note that there is an assertion with the example code:
```
clang++: /root/llvm-project/clang/lib/AST/ExprConstant.cpp:15320: bool clang::Expr::EvaluateAsConstantExpr(clang::Expr::EvalResult&, const clang::ASTContext&, clang::Expr::ConstantExprKind) const: Assertion `!isValueDependent() && "Expression evaluator can't be called on a dependent expression."' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++2b <source>
1.	<source>:14:12: current parser token ';'
2.	<source>:13:12: parsing function body 'main'
3.	<source>:13:12: in compound statement ('{}')
 #0 0x0000563b9e94c06f llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x40c006f)
 #1 0x0000563b9e949dac llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x40bddac)
 #2 0x0000563b9e897748 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f9b03108420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007f9b02bd500b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007f9b02bb4859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x00007f9b02bb4729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #7 0x00007f9b02bc5fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x0000563ba214ea6d (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x78c2a6d)
 #9 0x0000563ba12b2fe7 clang::ActionResult<clang::Expr*, true> calculateConstraintSatisfaction<calculateConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, clang::SourceLocation, clang::MultiLevelTemplateArgumentList const&, clang::Expr const*, clang::ConstraintSatisfaction&)::'lambda'(clang::Expr const*)>(clang::Sema&, clang::Expr const*, clang::ConstraintSatisfaction&, calculateConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, clang::SourceLocation, clang::MultiLevelTemplateArgumentList const&, clang::Expr const*, clang::ConstraintSatisfaction&)::'lambda'(clang::Expr const*)&&) SemaConcept.cpp:0:0
#10 0x0000563ba12b3572 CheckConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, llvm::ArrayRef<clang::Expr const*>, llvm::SmallVectorImpl<clang::Expr*>&, clang::MultiLevelTemplateArgumentList const&, clang::SourceRange, clang::ConstraintSatisfaction&) SemaConcept.cpp:0:0
#11 0x0000563ba12b3b94 clang::Sema::CheckConstraintSatisfaction(clang::NamedDecl const*, llvm::ArrayRef<clang::Expr const*>, llvm::SmallVectorImpl<clang::Expr*>&, clang::MultiLevelTemplateArgumentList const&, clang::SourceRange, clang::ConstraintSatisfaction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a27b94)
#12 0x0000563ba12b4b52 clang::Sema::CheckInstantiatedFunctionTemplateConstraints(clang::SourceLocation, clang::FunctionDecl*, llvm::ArrayRef<clang::TemplateArgument>, clang::ConstraintSatisfaction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a28b52)
#13 0x0000563ba1ab1938 clang::Sema::FinishTemplateArgumentDeduction(clang::FunctionTemplateDecl*, llvm::SmallVectorImpl<clang::DeducedTemplateArgument>&, unsigned int, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, llvm::SmallVectorImpl<clang::Sema::OriginalCallArg> const*, bool, llvm::function_ref<bool ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7225938)
#14 0x0000563ba1ab269e void llvm::function_ref<void ()>::callback_fn<clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>)::'lambda1'()>(long) SemaTemplateDeduction.cpp:0:0
#15 0x0000563ba115fed5 clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x68d3ed5)
#16 0x0000563ba1abcdaf clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7230daf)
#17 0x0000563ba18d9a7f clang::Sema::AddTemplateOverloadCandidate(clang::FunctionTemplateDecl*, clang::DeclAccessPair, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool, bool, clang::CallExpr::ADLCallKind, clang::OverloadCandidateParamOrder) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x704da7f)
#18 0x0000563ba172195c clang::Sema::DeduceTemplateSpecializationFromInitializer(clang::TypeSourceInfo*, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>)::'lambda'(bool)::operator()(bool) const SemaInit.cpp:0:0
#19 0x0000563ba1736303 clang::Sema::DeduceTemplateSpecializationFromInitializer(clang::TypeSourceInfo*, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6eaa303)
#20 0x0000563ba13426d3 clang::Sema::deduceVarTypeFromInitializer(clang::VarDecl*, clang::DeclarationName, clang::QualType, clang::TypeSourceInfo*, clang::SourceRange, bool, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ab66d3)
#21 0x0000563ba1347c1b clang::Sema::DeduceVariableDeclarationType(clang::VarDecl*, bool, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6abbc1b)
#22 0x0000563ba136c89f clang::Sema::AddInitializerToDecl(clang::Decl*, clang::Expr*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ae089f)
#23 0x0000563ba103b776 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x67af776)
#24 0x0000563ba104c868 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x67c0868)
#25 0x0000563ba104f5c1 clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x67c35c1)
#26 0x0000563ba104fa39 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x67c3a39)
#27 0x0000563ba10f06da clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x68646da)
#28 0x0000563ba10f1395 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6865395)
#29 0x0000563ba10f236a clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x686636a)
#30 0x0000563ba10f3d1a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6867d1a)
#31 0x0000563ba1021971 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6795971)
#32 0x0000563ba104cdb0 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x67c0db0)
#33 0x0000563ba1014fe2 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6788fe2)
#34 0x0000563ba101588f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#35 0x0000563ba101c3a9 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x67903a9)
#36 0x0000563ba101cced clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6790ced)
#37 0x0000563ba1010b8a clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6784b8a)
#38 0x0000563b9fcaa368 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x541e368)
#39 0x0000563b9f50cbe9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4c80be9)
#40 0x0000563b9f490876 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4c04876)
#41 0x0000563b9f5f28b7 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4d668b7)
#42 0x0000563b9bde1c86 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x1555c86)
#43 0x0000563b9bddd78a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#44 0x0000563b9f2f8d5d void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#45 0x0000563b9e897c30 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x400bc30)
#46 0x0000563b9f2f961f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#47 0x0000563b9f2c126c clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4a3526c)
#48 0x0000563b9f2c1d0d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4a35d0d)
#49 0x0000563b9f2c9aed clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4a3daed)
#50 0x0000563b9bde002c clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x155402c)
#51 0x0000563b9bced555 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x1461555)
#52 0x00007f9b02bb6083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#53 0x0000563b9bdd83be _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x154c3be)
```

**Comment by erichkeane** [comment]
That ICE helps actually, that shows it is probably a problem with setting up template arsg, but I'll take a look.

**Comment by erichkeane** [comment]
So the problem is that we're not properly assembling the instantiation args here.  We end up picking up the instantiation args off the Deduction Guide, but are trying to instantiate the constraint from the record decl that is being pointed to.  The result is that these don't match, for obvious reasons.

It isn't clear to me just yet how to properly figure these out, we don't have a good way to get back to the instantiated declaration (as it doesn't exist yet as far as I can tell).  It is also not clear to me whether the deduction guide itself is correct in inheriting the requirements from the constructor it results in...

**Comment by erichkeane** [comment]
So I tracked this down to this : https://reviews.llvm.org/D134145

@royjacobson is the author there.

It seems that moving the constraint to the deduction guide wasn't really a good idea, the template arguments don't "match" for checking.  Unfortunately reverting that patch caused both the dr2628 fix to break, as well as an additional older test (which I don't really know why!).

I think the "right" way to fix dr2628 is to check deduction guide constraints 'differently', and some how figure out the instantiation that is GOING to be selected, and check that instead.

**Comment by royjacobson** [comment]
Tried to debug this for an hour today. For some reason the call expression to `True` is not instantiated correctly during the constraints checks.

I think it might have to do with how we setup the lexical scope for lookups, but I'm not sure and I don't know how much time I will have to investigate this further before the release, unfortunately.

**Comment by AaronBallman** [comment]
> I think it might have to do with how we setup the lexical scope for lookups, but I'm not sure and I don't know how much time I will have to investigate this further before the release, unfortunately.

Do we think this regression warrants delaying the release to address?

**Comment by erichkeane** [comment]
> is for an hour today. For some reason the call expression to `True` (which is an UnresolvedLookupExpr) is not instantiated correctly during the constraints checks.
> 
> I think it might have to do with how we setup the lexical scope for lookups, but I'm not sure and I don't know how much time I will have to investigate this further before the release, unfortunately.

So True isn't instantiated correctly, because we are in the incorrect 'context' here (as mentioned above), because it is attached to the "Deduction Guide", which is wrong.  The trailing requires clause NEEDS to be attached to the entity on which it was originally written: the constructor.   So what is happening, is we are trying to instantiate the constraint with the template arguments of its 'owner' (the deduction guide), and they don't line up.  Basically, the patch that caused this kind of only 'worked' when the template arguments just happened to line up correctly.

 So I think the original fix to DR2628 is incorrect.  I didn't conceptualize (hah!) what you were doing at the time (and didn't know what I didn't know), but looking now, I probably wouldn't approve it now unfortunately.

I think we VERY strongly need to consider reverting DR2628 (https://reviews.llvm.org/D134145), and to answer @AaronBallman : I think that is both a minor enough revert, and a significant enough regression that it warrants a holding up the release.

**Comment by AaronBallman** [comment]
> I think we VERY strongly need to consider reverting DR2628 (https://reviews.llvm.org/D134145), and to answer @AaronBallman : I think that is both a minor enough revert, and a significant enough regression that it warrants a holding up the release.

I added this to the 16.x release milestone so we handle it before the release. CC @tstellar @tru for awareness.

**Comment by tru** [comment]
Thanks for bringing this up. Happy to revert that commit on the release branch if that's what we want to do.

**Comment by erichkeane** [comment]
> Thanks for bringing this up. Happy to revert that commit on the release branch if that's what we want to do.

I DO think that is what we want to do so if you're volunteering to do the work there, please do! But I also want to make sure that the revert doesn't cause regressions, so please make sure it passes pre-commit CI in trunk before putting in the branch.  

Sorry @royjacobson : This is something I wish I knew more at the time to have given proper review feedback.

**Comment by tru** [comment]
I gave it a shot here: https://github.com/tru/llvm-project/commit/d99f42f12665ef5fdf67cc81bfcf60ca05270106

I reverted the changes to SemaTemplate.cpp but left the test intact since that was added over time. Then I ran `check-clang` on my Linux machine and predictable `dr26xx.cpp` fail:

```
FAIL: Clang :: CXX/drs/dr26xx.cpp (1617 of 17924)
******************** TEST 'Clang :: CXX/drs/dr26xx.cpp' FAILED ********************
Script:
--
: 'RUN: at line 1';   /home/tobias/code/llvm-project/build/bin/clang -cc1 -internal-isystem /home/tobias/code/llvm-project/build/lib/clang/16/include -nostdsysteminc -std=c++20 -triple x86_64-unknown-unknown /home/tobias/code/llvm-project/clang/test/CXX/drs/dr26xx.cpp -verify
--
Exit Code: 1

Command Output (stderr):
--
error: 'error' diagnostics expected but not seen:
  File /home/tobias/code/llvm-project/clang/test/CXX/drs/dr26xx.cpp Line 26: call to deleted
error: 'error' diagnostics seen but not expected:
  File /home/tobias/code/llvm-project/clang/test/CXX/drs/dr26xx.cpp Line 26: ambiguous deduction for template arguments of 'foo'
error: 'note' diagnostics expected but not seen:
  File /home/tobias/code/llvm-project/clang/test/CXX/drs/dr26xx.cpp Line 21 (directive at /home/tobias/code/llvm-project/clang/test/CXX/drs/dr26xx.cpp:27): marked deleted here
error: 'note' diagnostics seen but not expected:
  File /home/tobias/code/llvm-project/clang/test/CXX/drs/dr26xx.cpp Line 21: candidate function [with A = false, B = false]
  File /home/tobias/code/llvm-project/clang/test/CXX/drs/dr26xx.cpp Line 22: candidate function [with A = false, B = false]
5 errors generated.

--
```

Nothing else failed locally.

The changes to `dr26xx.cpp` were hard to back out since this was the commit that created the file, and things have been added later. I can figure out the failed tests and back them out - but I would like to know if that's what we want to do or if we want to disable the test altogether.

**Comment by erichkeane** [comment]
> I gave it a shot here: [tru@d99f42f](https://github.com/tru/llvm-project/commit/d99f42f12665ef5fdf67cc81bfcf60ca05270106)
> 
> I reverted the changes to SemaTemplate.cpp but left the test intact since that was added over time. Then I ran `check-clang` on my Linux machine and predictable `dr26xx.cpp` fail:
> 
> ```
> FAIL: Clang :: CXX/drs/dr26xx.cpp (1617 of 17924)
> ******************** TEST 'Clang :: CXX/drs/dr26xx.cpp' FAILED ********************
> Script:
> --
> : 'RUN: at line 1';   /home/tobias/code/llvm-project/build/bin/clang -cc1 -internal-isystem /home/tobias/code/llvm-project/build/lib/clang/16/include -nostdsysteminc -std=c++20 -triple x86_64-unknown-unknown /home/tobias/code/llvm-project/clang/test/CXX/drs/dr26xx.cpp -verify
> --
> Exit Code: 1
> 
> Command Output (stderr):
> --
> error: 'error' diagnostics expected but not seen:
>   File /home/tobias/code/llvm-project/clang/test/CXX/drs/dr26xx.cpp Line 26: call to deleted
> error: 'error' diagnostics seen but not expected:
>   File /home/tobias/code/llvm-project/clang/test/CXX/drs/dr26xx.cpp Line 26: ambiguous deduction for template arguments of 'foo'
> error: 'note' diagnostics expected but not seen:
>   File /home/tobias/code/llvm-project/clang/test/CXX/drs/dr26xx.cpp Line 21 (directive at /home/tobias/code/llvm-project/clang/test/CXX/drs/dr26xx.cpp:27): marked deleted here
> error: 'note' diagnostics seen but not expected:
>   File /home/tobias/code/llvm-project/clang/test/CXX/drs/dr26xx.cpp Line 21: candidate function [with A = false, B = false]
>   File /home/tobias/code/llvm-project/clang/test/CXX/drs/dr26xx.cpp Line 22: candidate function [with A = false, B = false]
> 5 errors generated.
> 
> --
> ```
> 
> Nothing else failed locally.
> 
> The changes to `dr26xx.cpp` were hard to back out since this was the commit that created the file, and things have been added later. I can figure out the failed tests and back them out - but I would like to know if that's what we want to do or if we want to disable the test altogether.

Since we are now no longer implementing DR2628, the stuff in the dr2628 namespace is obviously in need of change.  Change the opening 'comment' to 'no', add a comment that we've reverted this implementation (and say what we EXPECT to happen here), then update the test with the different 'expected' lines to make it pass is what I think is the right way to go.

**Comment by royjacobson** [comment]
Agree that reverting seems sensible, no hard feelings :)

Please make sure to remove the line from the release note when we backport the revert.

**Comment by erichkeane** [comment]
@tru : How is the revert going?  Were you able to get it into the 16.0 branch yet?

**Comment by tru** [comment]
No sorry - I need to fixup the tests, but have been busy with my paying job! Will check today I hope.

**Comment by tru** [comment]
Ok had some time and was able to get the tests function, is there a way to "comment out" a expected-error/note line so that I don't have to remove them from the source?

**Comment by tru** [comment]
Here: https://github.com/tru/llvm-project/commit/1ee3a85a76f37c2c04e62e9f3995c03f61f4f54d

**Comment by AaronBallman** [comment]
> Ok had some time and was able to get the tests function, is there a way to "comment out" a expected-error/note line so that I don't have to remove them from the source?

I've done things like:
```
// expected-error {{whatever}}
// FIXME-expected-error {{whatever else}}
```
so that the comments remain but the FIXME one isn't actually tested.

**Comment by tru** [comment]
Thanks @AaronBallman!

@erichkeane here is the final version of the revert, if you think it looks good I'll queue it up for inclusion in the release

https://github.com/tru/llvm-project/commit/f9daac3a899e8d4fb19a5becbd8281f91305ff98

**Comment by erichkeane** [comment]
@tru: Code in that looks fine, but when going to 16.0, see if you can figure out how to have it removed from the release note:

https://github.com/llvm/llvm-project/blob/release/16.x/clang/docs/ReleaseNotes.rst
"Respect constructor constraints during class template argument deduction (CTAD). This is the suggested resolution to CWG DR2628. "

**Comment by tru** [comment]
Sorry - forgot about that - does it look good now? https://github.com/tru/llvm-project/commit/fe0530b80227be25778e51e8143d5dcd530c5900

**Comment by erichkeane** [comment]
Yep, LGTM!  Thanks!  Apply it to trunk, then go through the request to cherry-pick it to 16.0 (though I don't know how to do that with a different commit?  Perhaps you can just do the fe0530b from your branch?): https://llvm.org/docs/GitHub.html#backporting-fixes-to-the-release-branches

**Comment by tru** [comment]
I pushed https://github.com/llvm/llvm-project/commit/3b6c88331bcd0531d627fe27de5dbd0ac3165300 to `main` (no release note there since they are reset after branching).

Then I have queued up the bots to do their thing for backporting.
