### ISSUE TITLE
libc++ should remove shared_ptr<T>::unique() in C++20 mode

### ISSUE THREAD

**Issue by danakj** [llvm/llvm-project#60785]
https://github.com/llvm/llvm-project/blob/e6fbfb1ff1d352b2f8f0b6d39f4665fd91f0d21d/libcxx/include/__memory/shared_ptr.h#L866-L870

The method is currently always provided by libc++.

**Comment by pkasting** [comment]
(This should also be diagnosed as "deprecated" in C++17 mode)

**Comment by philnik777** [comment]
This is part of P0619R4, which we don't have fully implemented yet. Please check https://libcxx.llvm.org/Status/Cxx20.html before reporting a not-yet-implemented paper as an issue to avoid tracking papers in multiple places.
