### ISSUE TITLE
if constexpr failing on ill-formed code inside untaken branch

### ISSUE THREAD

**Issue by mikhailramalho** [llvm/llvm-project#60780]
Hi folks, 

gcc compiles the following code, while clang doesn't (I tested with clang 11, 13, and 15). Is the compiler required to evaluate the untaken branch?
```
struct A {};

struct B {};

template <typename T> void D(void) {
  if constexpr (T::E) {
    A a;
    B b(a);
  }
}

struct C {
  static constexpr bool E = false;
};

int main() { D<C>(); }
```

**Comment by mikhailramalho** [comment]
From https://en.cppreference.com/w/cpp/language/if: `Note: the discarded statement cannot be ill-formed for every possible specialization`, so I guess clang is right here?

**Comment by shafik** [comment]
Correct, this is Ill-formed No Diagnostic Required (IFNDR) due to [temp.res.general p6](http://eel.is/c++draft/temp.res.general#6.1)

> The program is ill-formed, no diagnostic required, if:
> (6.1) - no valid specialization can be generated for a template or a substatement of a constexpr if statement within a template and the template is not instantiated, or
