### ISSUE TITLE
LLVM_NATIVE_TOOL_DIR does not work for many tools including clang-tools-extra

### ISSUE THREAD

**Issue by trcrsired** [llvm/llvm-project#60784]
This new toggle was proposed by me and it has added into llvm17. Unfortunately, many tools in LLVM does not respect the toggle. This is very annoying for Canadian compilation. Please fix it.

**Comment by mstorsjo** [comment]
It works for me, including for executables in clang-tools-extra. You'll need to provide more details about how to reproduce the issue, or ideally, try to dig into why it doesn't work - the code isn't that complex...

**Comment by trcrsired** [comment]
> It works for me, including for executables in clang-tools-extra. You'll need to provide more details about how to reproduce the issue, or ideally, try to dig into why it doesn't work - the code isn't that complex...

canadian compilation from linux to windows?

**Comment by mstorsjo** [comment]
> > It works for me, including for executables in clang-tools-extra. You'll need to provide more details about how to reproduce the issue, or ideally, try to dig into why it doesn't work - the code isn't that complex...
> 
> canadian compilation from linux to windows?

Yes.

First, on Linux, I do a regular native build of LLVM:
```
# in $HOME/code/llvm-project/llvm/build
$ cmake .. \
    -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=$HOME/clang-trunk \
    -DLLVM_TARGETS_TO_BUILD="ARM;AArch64;X86" \
    -DLLVM_ENABLE_PROJECTS="lld;clang;lldb;clang-tools-extra" \
$ ninja
```

Then I later do a cross compilation (in this case using Clang wrapped in [llvm-mingw](https://github.com/mstorsjo/llvm-mingw/releases):
```
$ cmake .. \
    -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_SYSTEM_NAME=Windows \
    -DLLVM_HOST_TRIPLE=x86_64-w64-mingw32 \
    -DLLVM_TARGETS_TO_BUILD="ARM;AArch64;X86" \
    -DLLVM_ENABLE_PROJECTS="lld;clang;lldb;clang-tools-extra" \
    -DCMAKE_C_COMPILER=x86_64-w64-mingw32-clang \
    -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-clang++ \
    -DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres \
    -DLLVM_NATIVE_TOOL_DIR=$HOME/code/llvm-project/llvm/build/bin \
    -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
    -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
    -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
    -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY \
    -DCMAKE_FIND_ROOT_PATH=$(cd $(dirname $(which x86_64-w64-mingw32-clang++))/../x86_64-w64-mingw32 && pwd)
$ ninja
```

The second build, the cross build, completes successfully, and no `NATIVE` directory is created (i.e. all the build time `*-tblgen` tools and `clang-pseudo-gen` and `clang-tidy-confusable-chars-gen` are used from `LLVM_NATIVE_TOOL_DIR` and not rebuilt).

**Comment by sean-mcmanus** [comment]
Our team is also hitting this issue with 16.0 (15.0 works). We get the error saying it's fails to execute the aarch64 clang-tidy-confusable-chars-gen on our x64 build machine, when it should be using the x64 clang-tidy-confusable-chars-gen LLVM_NATIVE_TOOL_DIR (setting CLANG_TIDY_CONFUSABLE_CHARS_GEN like we did previously also doesn't work).

**Comment by mstorsjo** [comment]
> Our team is also hitting this issue with 16.0 (15.0 works). We get the error saying it's fails to execute the aarch64 clang-tidy-confusable-chars-gen on our x64 build machine, when it should be using the x64 clang-tidy-confusable-chars-gen. We set LLVM_NATIVE_TOOL_DIR (and setting CLANG_TIDY_CONFUSABLE_CHARS_GEN like we did previously also doesn't work).

I’m sorry about that; can you provide me with more details on how to reproduce the issue? What kind of build do you do, on what OS, and what’s your cmake configure line? Do you build the whole monorepo, or only an individual subproject?

**Comment by sean-mcmanus** [comment]
I fixed the build by adding `-DLLVM_USE_HOST_TOOLS=TRUE` (in addition to the LLVM_NATIVE_TOOL_DIR) -- I figured that out via looking more closely at the changes at https://github.com/llvm/llvm-project/commit/d3da9067d143f3d4ce59b6d9ab4606a8ef1dc937 . It would be helpful in the future if there were some build breaking changes documentation page we could check.

**Comment by mstorsjo** [comment]
> I fixed the build by adding `-DLLVM_USE_HOST_TOOLS=TRUE` (in addition to the LLVM_NATIVE_TOOL_DIR) -- I figured that out via looking more closely at the changes at [d3da906](https://github.com/llvm/llvm-project/commit/d3da9067d143f3d4ce59b6d9ab4606a8ef1dc937) . It would be helpful in the future if there were some build breaking changes documentation page we could check.

Well, this wasn't supposed to be a build breaking change - the old options were meant to keep working exactly as they used to, and if you wanted to, you could opt into using the new option to simplify things. The fact that it didn't is a bug that I'd like to fix.

I do see that there's a potential gap where the new behaviour after refactoring doesn't exactly match the previous one - if `LLVM_USE_HOST_TOOLS` isn't set.

But see e.g. https://github.com/llvm/llvm-project/blob/llvmorg-16.0.0/llvm/CMakeLists.txt#L766-L768; if `CMAKE_CROSSCOMPILING` is set, `LLVM_USE_HOST_TOOLS` should be implicitly enabled. So is it the case that you're cross compiling, but cmake doesn't know that you are? So, so far, you've managed to get by in this configuration by providing the tools manually, even if cmake doesn't know you're really cross compiling?

If you look at the refactorings done in d3da9067d143f3d4ce59b6d9ab4606a8ef1dc937, some cases (in `mlir-linalg-ods-gen`) only checked the variable for setting the name of the external tool to use, if `LLVM_USE_HOST_TOOLS` was set, while the ones in clang-tools-extra ignored `LLVM_USE_HOST_TOOLS` and always respected the variables, if set. When refactoring this into `setup_host_tool`, either of the cases would be changed, and I went with ignoring the variables if `LLVM_USE_HOST_TOOLS` wasn't set - as that one is supposed to be set if we can't use the currently built target one.

While the correct fix probably is to make cmake aware that you're cross compiling, it's probably safest to adjust `setup_host_tool` to not look at `LLVM_USE_HOST_TOOLS` here, but always use the external variable (either the tool specific one or one pointed to by `LLVM_NATIVE_TOOL_DIR`) if they're set.

**Comment by sean-mcmanus** [comment]
Yeah, originally we had CLANG_TIDY_CONFUSABLE_CHARS_GEN, DLLVM_TABLEGEN, and CLANG_TABLEGEN set.

And we configure CMake with `-DCMAKE_CROSSCOMPILING=True`, so it seems like it should know we're cross compiling in general.

**Comment by mstorsjo** [comment]
> And we configure CMake with `-DCMAKE_CROSSCOMPILING=True`, so it seems like it should know we're cross compiling in general.

If you're configuring that way, how come https://github.com/llvm/llvm-project/blob/llvmorg-16.0.0/llvm/CMakeLists.txt#L766-L768 doesn't already implicitly enable `LLVM_USE_HOST_TOOLS` for you?

I remember reading a direct suggestion in some docs saying that one shouldn't be setting `CMAKE_CROSSCOMPILING` directly (unfortunately I don't find this statement at the moment), but https://cmake.org/cmake/help/latest/variable/CMAKE_CROSSCOMPILING.html says that it's set implicitly when `CMAKE_SYSTEM_NAME` is set - so the canonical way to cross compile with CMake is to set `CMAKE_SYSTEM_NAME`, even if it's set to the same system as the current host (but for a difference architecture).

I posted https://reviews.llvm.org/D146666 which should hopefully fix this issue - can you give that a try?

**Comment by sean-mcmanus** [comment]
Yeah, I don't understand why CMAKE_CROSSCOMPILING isn't defined or why LLVM_USE_HOST_TOOLS isn't automatically set. We don't set CMAKE_SYSTEM_NAME because we didn't seem to need to and the host and target are both "Linux", but we could try setting that anyway.

How do I try out the fix? Our build is set to use the latest refs/heads/release/16.x branch commit.

**Comment by mstorsjo** [comment]
> Yeah, I don't understand why CMAKE_CROSSCOMPILING isn't defined or why LLVM_USE_HOST_TOOLS isn't automatically set. We don't set CMAKE_SYSTEM_NAME because we didn't seem to need to and the host and target are both "Linux", but we could try setting that anyway.

Yeah, as far as I know, that's the canonical way of telling CMake that you're cross compiling. Maybe CMake clears the user provided `CMAKE_CROSSCOMPILING` flag as it's supposed to be inferred automatically? I can try to test that behaviour.

> How do I try out the fix? Our build is set to use the latest refs/heads/release/16.x branch commit (or we could change it to reference "main").

The fix isn't anywhere in the official repo yet, since it's still up for discussion. I pushed a branch with it to https://github.com/mstorsjo/llvm-project - you can build the `host-tools-var-16.x` branch from that repo (it's the latest 16.x release branch plus that fix).

**Comment by mstorsjo** [comment]
> > Yeah, I don't understand why CMAKE_CROSSCOMPILING isn't defined or why LLVM_USE_HOST_TOOLS isn't automatically set. We don't set CMAKE_SYSTEM_NAME because we didn't seem to need to and the host and target are both "Linux", but we could try setting that anyway.
> 
> Yeah, as far as I know, that's the canonical way of telling CMake that you're cross compiling. Maybe CMake clears the user provided `CMAKE_CROSSCOMPILING` flag as it's supposed to be inferred automatically? I can try to test that behaviour.

Indeed, CMake mostly ignores the variable as it is set by the user and resets it to what itself thinks it is: https://github.com/Kitware/CMake/blob/v3.26.0/Modules/CMakeDetermineSystem.cmake#L159-L181 Thus, the canonical way of telling CMake you're cross compiling is to set `CMAKE_SYSTEM_NAME` only.

**Comment by sean-mcmanus** [comment]
Okay, cool, thanks for the info (we'll switch to using CMAKE_SYSTEM_NAME). I've queued the builds -- I'll let you know the results later today.

**Comment by mstorsjo** [comment]
> @mstorsjo Yeah, switching to `-DCMAKE_SYSTEM_NAME="Linux"` instead of `-DCMAKE_CROSSCOMPILING=True` causes our original builds to not fail. With your changes, our builds work either way. Does that answer all your questions?

Thanks, that's pretty much what I needed to know! The patch was approved in the meantime too, so I'll go ahead and push it and request a backport to 16.x.

**Comment by mstorsjo** [comment]
Reopening, as we want the issue fixed in 16.x too.

**Comment by mstorsjo** [comment]
Also FWIW, see https://gitlab.kitware.com/cmake/cmake/-/merge_requests/8358 for an attempt to make cmake warn about this situation.

**Comment by mstorsjo** [comment]
FYI, The warning about the user-set `CMAKE_CROSSCOMPILING` which gets cleared got merged and will be in CMake 3.27.

**Comment by esaaprillia** [comment]
@mstorsjo 

```NATIVE``` will be built if ```-DLLVM_NATIVE_TOOL_DIR=$HOME/clang-trunk```

i had this problem in openwrt.

1. I built the llvm host after completing the host file I installed in ```@HOME/staging/hostpkg/```

2. build cross compilation.
     
     I added ```-DLLVM_NATIVE_TOOL_DIR=$HOME/staging/hostpkg/```
     
     i see ```NATIVE``` when cross compiling this should not happen.
     
     if I add ```-DLLVM_NATIVE_TOOL_DIR=$HOME/code/llvm-project/llvm/build/bin``` I no longer see ```NATIVE``` created during cross-compilation
     
3. My question is how to build an llvm host and install the llvm host file in the specified place?

**Comment by mstorsjo** [comment]
> `NATIVE` will be built if `-DLLVM_NATIVE_TOOL_DIR=$HOME/clang-trunk`

If you use such a path, you usually need to have this pointing at a path like `$HOME/clang-trunk/bin`.

>    if I add `-DLLVM_NATIVE_TOOL_DIR=$HOME/code/llvm-project/llvm/build/bin` I no longer see `NATIVE` created during cross-compilation

So the problem you have is not related to the `LLVM_NATIVE_TOOL_DIR` option at all. It's just that perhaps not all tools that are needed, are installed when you do `ninja install` or similar. The option `LLVM_INSTALL_TOOLCHAIN_ONLY` may have an effect on this.

All in all, this is unrelated to the `LLVM_NATIVE_TOOL_DIR` option. You use that option to point at preexisting binaries; how those binaries are created and in which cases they are installed, is a different issue.

**Comment by esaaprillia** [comment]
@mstorsjo 
Thank you. now my problem is resolved
