### ISSUE TITLE
Clang accepts GNU-style function attributes followed by C23-style attributes, while GCC doesn't

### ISSUE THREAD

**Issue by thesamesam** [llvm/llvm-project#60793]
`clang -std=c2x` currently allows using a GNU-style `__attribute__` followed by a C23-style attribute specifier, while GCC 13 currently doesn't. This came up in the wild at https://github.com/sudo-project/sudo/issues/239.

I was under the impression it wasn't allowed when I filed a [bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108796) on the GCC side, but then was told it possibly should be, but Joseph Myers weighed in and explained that it likely shouldn't be: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108796#c6:
>The logic is that GNU attributes are declaration specifiers (and can mix 
>anywhere with other declaration specifiers), but standard attributes 
>aren't declaration specifiers; rather, they come in specified positions 
>relative to declaration specifiers (the semantics before and after the 
>declaration specifiers are different), and in the middle isn't such a 
>position.

I'm going to call this _accepts-invalid_ based on that comment for now. If the conclusion is that it's okay to mix these in either order, then we can close this on the basis that GCC should accept it instead.

Reproducer:
```console
$ cat /tmp/foo.c
__attribute__((noreturn)) [[noreturn]]
void foo(void) {
        while(true);
}

$ clang -std=c2x /tmp/foo.c -S # succeeds, clang 16.0.0_rc2

$ gcc -std=c2x /tmp/foo.c -S # fails, 13.0.1 20230212
/tmp/foo.c:2:1: warning: ‘noreturn’ attribute ignored [-Wattributes]
    2 | void foo(void) {
      | ^~~~
/tmp/foo.c:2:1: error: expected identifier or ‘(’ before ‘void’
```

**Comment by erichkeane** [comment]
FWIW, I agree with Aaron here, the appertainment rules of all the individual GNU style attributes prove to me that they aren't really the start of a declaration, they are just bizarrely floating annotations that end up in places with no rhyme/reason as to what they mean in that location (that is, we have plenty of attributes that end up as 'decl' attributes, but are spelled in the 'type' location).

So I don't agree with Joseph's logic here.  `__attribute__`, while called `GNU Style` attributes, they are an implementation defined extension, which Clang has extended separately from GCC.  They don't have to be 100% compatible (though as Aaron says, its a shame that they aren't), so I also don't see this as a bug/accepts-invalid.

**Comment by thesamesam** [comment]
Thanks for the explanation folks, I didn't realise that Clang had extended them in its own right too. It's a shame that we've got something standardised but the migration path to it is painful for developers, but as you say, I'm not sure much can be done about that now.

**Comment by AaronBallman** [comment]
I'm not certain there's much here that's actionable, so I think this issue can be closed. However, maybe we could convert this issue into a request for a diagnostic when Clang accepts `__attribute__(())` in a syntactic location that GCC does not?

**Comment by thesamesam** [comment]
Yeah, that'd be a great UX improvement.

**Comment by AaronBallman** [comment]
Closing this issue as not planned, and I opened https://github.com/llvm/llvm-project/issues/81767 to track the feature request. Thanks!
