### ISSUE TITLE
[C++20] [Modules] Should we ignore the inconsistent `-fvisibility-hidden` options?

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#60797]
Reproducer:

```cpp
// a.cppm
export module a;

// b.cppm
export module b;
import a;
```

Compile them with:

```shell
clang++ -std=c++20 a.cppm --precompile -o a.pcm -fvisibility=hidden -fvisibility-inlines-hidden
clang++ -std=c++20 b.cppm --precompile -o b.pcm -fprebuilt-module-path=.
```

We will get:

```console
error: default visibility for functions and variables [-fvisibility] differs in PCH file vs. current file
```

I meet the problem in practice. And I feel the problem would be pretty common for users. For example, `libb.so` depends on `liba.so` but they have different visibility requirements. So here is the problem. I've ignore the error in our downstream implementation. And it looks good so far. But I want to ask more opinions for potential risks before I make it upstream.

CC @iains @dwblaikie @davidstone

**Comment by iains** [comment]
* I suppose that (modulo the diagnostic referring to 'PCH') the current state is reasonable - it is telling you that you have done something different in the two cases.

* another aspect has already been raised by the tooling folks (i.e how we should define/place an attribute to specify what the default visibility should be for a module).  I will try to locate a reference to that discussion.

**Comment by ChuanqiXu9** [comment]
> Conversely, if everything is defined as internal visibility, then it is unlikely that this module was intended to be imported from outside of the library

It looks like the sentence makes sense. We should put the job to build systems and users. They should take care of this.
