### ISSUE TITLE
Generate better code for X == Y ? 2 : 1 on x86.

### ISSUE THREAD

**Issue by kazutakahirata** [llvm/llvm-project#60805]
Compile:

```cpp
unsigned sel(unsigned X, unsigned Y) {
  return X == Y ? 2 : 1;
}
```

I get:

```asm
  31 c9                      xor    %ecx,%ecx
  39 f7                      cmp    %esi,%edi
  0f 94 c1                   sete   %cl
  b8 02 00 00 00             mov    $0x2,%eax
  29 c8                      sub    %ecx,%eax
```

We could generate:

```asm
  31 c0                      xor    %eax,%eax
  39 f7                      cmp    %esi,%edi
  0f 95 c0                   setne  %al
  ff c0                      inc    %eax
```   

saving 5 bytes.

**Comment by RKSimon** [comment]
We should be able to extend combineSelectOfTwoConstants to handle the case where either value is 1 and we just add/sub the difference.

**Comment by junaire** [comment]
I don't understand, but looks like we do generate the optimized assembly?

https://godbolt.org/z/e5drTcM6M

**Comment by kazutakahirata** [comment]
> I don't understand, but looks like we do generate the optimized assembly?
> 
> https://godbolt.org/z/e5drTcM6M

You are completely right.  Sorry for the noise.  Upon investigating, I was actually looking at `X == Y ? 1 : 2`, where the constants are swapped from what this issue is about.  Rather than salvaging this issue and creating even more confusion, let me file a new issue.

**Comment by kazutakahirata** [comment]
Closing as the compiler already generates the desired code.
