### ISSUE TITLE
Clang 16-rc2 regression: confusion around single-element array class variant member in constexpr

### ISSUE THREAD

**Issue by CaseyCarter** [llvm/llvm-project#60803]
Caught this testing MSVCSTL with 16-rc2. One of the libc++ tests instantiates `std:basic_string` with a 16-byte `struct` type, which results in an SSO buffer large enough to hold a single character. I suspect this is a vanishingly rare use case outside of test suites, so this is not a release blocker, but a "would-be-nice" for LLVM 16.

Compiling this well-formed TU:
```c++
struct CharT { int x; };

struct basic_string {
  constexpr basic_string() { u_.buf_[0] = CharT{}; }

  union U {
    constexpr U() : buf_() {}

    CharT buf_[1];
  } u_;
};

constexpr bool test() {
  basic_string s;
  return true;
}

static_assert(test());
```
with `clang++ -std=c++20` diagnoses:
```console
repro.cpp:18:15: error: static assertion expression is not an integral constant expression
static_assert(test());
              ^~~~~~
repro.cpp:4:41: note: member call on object outside its lifetime is not allowed in a constant expression
  constexpr basic_string() { u_.buf_[0] = CharT{}; }
                                        ^
repro.cpp:14:16: note: in call to 'basic_string()'
  basic_string s;
               ^
repro.cpp:18:15: note: in call to 'test()'
static_assert(test());
              ^
1 error generated.
```
This is particularly strange given that `U`'s default constructor activates `buf_`, and that the assignment `u_.buf_[0] = CharT{}` should activate `buf_` even were it not already the active member of `u_`. Indeed, changing `U`'s default constructor so as to not activate `buf_` - or removing the constructor entirely - results in successful compilation.

**Comment by AaronBallman** [comment]
I can confirm the current behavior on trunk is incorrect and it was working in Clang 15. I don't have the bandwidth at the moment to bisect this down to a commit range, but I'll CC some folks who have been working on constant expressions during Clang 16 to see if this rings any bells. CC @shafik @usx95 @ilya-biryukov @tbaederr

**Comment by tbaederr** [comment]
We get to this if statement with a `None` value in the buffer: https://github.com/llvm/llvm-project/blob/main/clang/lib/AST/ExprConstant.cpp#L3636-L3639.

Without the constructor, the array is empty and only has a filler set (which is set to `Indeterminate`), but with the constructor the array is expanded to one `None` element. And `handler.AccessKind == AK_MemberCall`, so so emit the diagnostic.

I don't know what commit caused the regression or what to do about it exactly, but it seems like the commit just above the if statement is true for `None` values as well...?

**Comment by CaseyCarter** [comment]
Just so we're all on the same page, I'll point out that the `mem-initializer` `buf_()` should value-initialize the array ([[dcl.init.general]/16.4](https://eel.is/c++draft/dcl.init.general#16.4)) which should value-initialize each of its one elements ([[dcl.init.general]/9.2](https://eel.is/c++draft/dcl.init.general#9.2)). In other words, `buf_[0]` should not have an indeterminate value.

I should also mention that the code compiles successfully if `buf_` has extent greater than one.

**Comment by Fznamznon** [comment]
https://reviews.llvm.org/D130791 added an improvement that in case array element has a trivial constructor, it is evaluated once and the result is re-used for remaining elements. However size of array 1 caused constructor not be evaluated even once. I posted https://reviews.llvm.org/D145486 to fix this.
