### ISSUE TITLE
Support nested `enum` in `readability-static-accessed-through-instance`

### ISSUE THREAD

**Issue by firewave** [llvm/llvm-project#60810]
```cpp
class C {
public:
    enum E {
        E0
    };
};

static void f() {
    C c;
    (void)c.E0;
}
```
https://godbolt.org/z/dz6x38418

This is not actually a `static` but it seems quite similar and might fit into this check.

**Comment by HerrCai0907** [comment]
candidate patch: https://reviews.llvm.org/D147315
