### ISSUE TITLE
Generate better code for std::bit_floor on x86

### ISSUE THREAD

**Issue by kazutakahirata** [llvm/llvm-project#60826]
Compile:

```c++
// clang -std=c++20 -march=skylake -O2
#include <bit>
#include <cstdint>

uint32_t my_bit_floor(uint32_t X) {
  return std::bit_floor(X);
}
```

I get:

```llvm
  %2 = icmp ne i32 %0, 0
  %3 = zext i1 %2 to i32
  %4 = tail call i32 @llvm.ctlz.i32(i32 %0, i1 false) #2, !range !5
  %5 = xor i32 %4, 31
  %6 = shl nuw i32 %3, %5
```
```asm
  31 c0                      xor    %eax,%eax      ; 18 bytes, critical path length = 3
  85 ff                      test   %edi,%edi
  0f 95 c0                   setne  %al
  f3 0f bd cf                lzcnt  %edi,%ecx
  f6 d1                      not    %cl
  c4 e2 71 f7 c0             shlx   %ecx,%eax,%eax
```

We could generate:

```asm
  31 c0                   xor    %eax,%eax         ; 16 bytes, critical path length = 3
  f3 0f bd cf             lzcnt  %edi,%ecx
  0f 93 c0                setae  %al
  f7 d1                   not    %ecx
  c4 e2 71 f7 c0          shlx   %ecx,%eax,%eax
```

Note that `lzcnt` sets the carry flag if and only if the input is 0, so `setae` gives us 0 for zero input and 1 for nonzero input.

**Comment by topperc** [comment]
Where did the shr and cmove come from if this is the IR

```
  %2 = icmp ne i32 %0, 0
  %3 = zext i1 %2 to i32
  %4 = tail call i32 @llvm.ctlz.i32(i32 %0, i1 false) #2, !range !5
  %5 = xor i32 %4, 31
  %6 = shl nuw i32 %3, %5
```

**Comment by kazutakahirata** [comment]
> Where did the shr and cmove come from if this is the IR

I apologize.  I must have copy-n-pasted something else.  I've fixed the original post.

The issue now is to get rid of the `test` instruction and start using the carry flag from the `lzcnt` instruction.

**Comment by kazutakahirata** [comment]
I'm closing this issue in favor of:

https://github.com/llvm/llvm-project/issues/61183

The real problem seems to be that we generate suboptimal LLVM IR for `std::floor` from libstdc++.  We generate good LLVM IR for `std::floor` from libc++.

Plus, the compiler generates the final `select` instruction either case, libstdc++ or libc++.  I am not sure where I got the LLVM IR sequence above involving `zext` and `xor`.
