### ISSUE TITLE
[C++20] [Modules] Deprecate the form `-fmodule-file=<path-to-BMI>` for named modules

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#60824]
The form `-fmodule-file=<path-to-BMI>` will load modules eagerly and the form `-fmodule-file=<module-name>=<path-to-BMI>` will load modules lazily. The inconsistency adds additional burdens to the implementations. And the inconsistency looks not helpful and necessary neither. So I want to deprecate the form `-fmodule-file=<path-to-BMI>` for named modules.

Note that header units technically have no name and we still don't have a good idea for header units now. So this proposal doesn't apply to header units.

**Comment by aaronmondal** [comment]
I'm in favor of this. Previously the `-fmodule-file=<module-name>=<path-to-BMI>` was broken, so there was a need for `-fmodule-file=<path-to-BMI>`. But this is no longer the case and the named variant is much more intuitive.

Considering that end users are likely to overspecify module dependencies we don't gain much by having an option that prevents the lazy lookup.
