### ISSUE TITLE
Include -Wpacked in -Wall

### ISSUE THREAD

**Issue by mmarczell-graphisoft** [llvm/llvm-project#60832]
If someone compiles with `-Wall`, https://github.com/llvm/llvm-project/issues/51181 might still bite them. In our scenario we were using a struct like this to write our binary file format. The layout changed silently with the compiler upgrade and wrote invalid files.

```cpp
class Guid {
    uint64_t mLow, mHigh;
};


struct __attribute__ ((packed)) FormatHeader {
    float x;
    bool b;
    Guid guid;
};
```

https://godbolt.org/z/jb1h3eqPK

It would be better if `-Wpacked` would be included in `-Wall`.

**Comment by SlaterLatiao** [comment]
In addition to `-Wpacked-non-pod `, `-Wpacked` also reports warnings of  "packed attribute is unnecessary", which are less informative. So `-Wall` should only include `-Wpacked-non-pod `. This is also consistent with GCC.
