### ISSUE TITLE
Clang analyzer crash when using __builtin_bit_cast()

### ISSUE THREAD

**Issue by pfent** [llvm/llvm-project#60835]
Clang analyzer crashes for the following input:
```cpp
void* data = nullptr;
int main() { return __builtin_bit_cast(long, data) + 1; }
```

With a debug build from `main`, I get an assertion of "No dispatcher registered for an event":
```console
$ clang++ -cc1 -analyze -analyzer-checker=nullability.NullReturnedFromNonnull crash.cpp
clang++: /home/fent/llvm-project/clang/lib/StaticAnalyzer/Core/CheckerManager.cpp:56: void clang::ento::CheckerManager::finishedCheckerRegistration(): Assertion `Event.second.HasDispatcher && "No dispatcher registered for an event"' failed.
...
```

This seems related to #60657, but still reproduces on `main` with @steakhal's fix.

**Comment by steakhal** [comment]
Using the `-cc1` frontend is not officially supported nor documented.
The official way to invoke the Static Analyzer is by using the `--analyze` flag (without the cc1 stuff).
It does more than simply invoke the `-analyze` action; it configures the analyzer in the supported way, like enabling the `core` checker package.

If you modify your invocation to enable the `core` package besides the nullability stuff, you will no longer crash. Hence, I believe, the crash is not related to `bitcasts`.
