### ISSUE TITLE
Linker error on Windows on ARM64 when LLVM is built with LLD_DEFAULT_LD_LLD_IS_MINGW enabled

### ISSUE THREAD

**Issue by brechtsanders** [llvm/llvm-project#60848]
I'm trying to build LLVM (version 15.0.7) natively on Windows on ARM64 with MinGW-w64 (aarch64-w64-mingw32).
I accidentally had the flag `-DLLD_DEFAULT_LD_LLD_IS_MINGW:BOOL=ON` in my CMake flags.

There is support for this platform in binutils since version 2.40 (which I have installed), however I get the following error when trying to link with the LLVM I built from source:
```
D:/Prog/winlibs_clang/mingwARM64/bin/ld: unrecognised emulation mode: arm64pe
Supported emulations: aarch64pe i386pe i386pep
```

So it appears LLVM calls this platform `arm64pe` while binutils expects `aarch64pe`.

Is this something that should be fixed in LLVM?

**Comment by alvinhochun** [comment]
LLD uses`arm64pe` though: https://github.com/llvm/llvm-project/blob/a8831631c7ec74f91c12963e45b062c3366dd10d/lld/MinGW/Driver.cpp#L381
If you ask me I would say it's a Binutils issue for being incompatible with LLD, since Windows ARM64 support in LLD has been around for quite a while longer than Binutils.

**Comment by brechtsanders** [comment]
Maybe LLVM has been around longer, but this architecture is generally referred to as aarch64, for example when targeting Linux on the same CPU (not sure about macOS).

But I guess in theory it would be possible to patch `ld` to translate `arm64pe` to `aarch64pe`.

Anyway, since I don't plan to mix LLVM compiler with binutils linker I guess as far as I'm concerned this doesn't really need fixing.
