### ISSUE TITLE
[clang-format-13] launched in ubuntu22.04 goes to signal 11

### ISSUE THREAD

**Issue by AnneCharlotteh** [llvm/llvm-project#60842]
The error message only appears when
```shell
find source/global/config.c -name '*.h' -or -name '*.c' | xargs clang-format-13 -i -style=file $1
```
concerns some of the files of my project. 

Ubuntu clang-format version 13.0.1-2ubuntu2.1

```console
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: "C:\\Program Files\\LLVM\\bin\\clang-format.exe" -output-replacements-xml -style=file -fallback-style=LLVM -assume-filename=file
 #0 0x00007ff78a82e859 C:\Program Files\LLVM\bin\clang-format.exe 0xbe859 C:\Program Files\LLVM\bin\clang-format.exe 0xbe319
 #1 0x00007ff78a82e859 C:\Program Files\LLVM\bin\clang-format.exe 0xbcd39 C:\Program Files\LLVM\bin\clang-format.exe 0xb9ef7
 #2 0x00007ff78a82e859 C:\Program Files\LLVM\bin\clang-format.exe 0x86397 C:\Program Files\LLVM\bin\clang-format.exe 0xa2519
 #3 0x00007ff78a82e859 C:\Program Files\LLVM\bin\clang-format.exe 0x94664 C:\Program Files\LLVM\bin\clang-format.exe 0x7dd6e
 #4 0x00007ff78a82e859 C:\Program Files\LLVM\bin\clang-format.exe 0x7ec69 C:\Program Files\LLVM\bin\clang-format.exe 0x545c
 #5 0x00007ff78a82e859 C:\Program Files\LLVM\bin\clang-format.exe 0x385b C:\Program Files\LLVM\bin\clang-format.exe 0x1843e8
 #6 0x00007ff78a82e859 (C:\Program Files\LLVM\bin\clang-format.exe+0xbe859)
 #7 0x00007ff78a82e319 (C:\Program Files\LLVM\bin\clang-format.exe+0xbe319)
0x00007FF78A82E859 (0x000000ED00000000 0x00007FF78A7D7F11 0x000002794140BA00 0x0000000000004CFD)
0x00007FF78A82E319 (0x000000ED31D8AE18 0x0000000000000000 0x000000ED00000000 0x000000ED31D8C540)
0x00007FF78A82CD39 (0x0000000000000000 0x000000ED00000000 0x000000ED31D8AA58 0x00007FFB62B9F05B)
0x00007FF78A829EF7 (0x00000000000000A6 0x00007FFB00000000 0x0000000000000000 0x0000001000000000)
0x00007FF78A7F6397 (0x000000ED31D8B7C0 0x00007FF78A81292E 0x000000ED31D8B8A0 0x0000000000000000)
0x00007FF78A812519 (0x0000000000000000 0x000000ED31D8C530 0x000000ED31D8C9B0 0x0000000000000004)
0x00007FF78A804664 (0x0000000000000100 0x0000000000000000 0x000002794141B6B0 0x0000000000000DCB)
0x00007FF78A7EDD6E (0x00000279410D4D70 0x00007FFB651347B1 0x0000000000000000 0x00000279410C0000)
0x00007FF78A7EEC69 (0x00000279410CD994 0x0000027900000000 0x00000279410CD960 0x0000000000340032)
0x00007FF78A77545C (0x00000279410D6D00 0x000000000000000E 0x0000000000000000 0x00000279410C9400)
0x00007FF78A77385B (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF78A8F43E8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFB64D77614 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFB651626A1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
```

**Comment by EugeneZelenko** [comment]
Could you please try 16 or `main` branch? https://godbolt.org should be helpful.

**Comment by rymiel** [comment]
I don't think there's much to be done here without the configuration used, the source file or the symbolized backtrace. It is likely a crash which has been fixed (see https://github.com/llvm/llvm-project/issues/58606, https://github.com/llvm/llvm-project/issues/57558, https://github.com/llvm/llvm-project/issues/56682, https://github.com/llvm/llvm-project/issues/56670, https://github.com/llvm/llvm-project/issues/56104, https://github.com/llvm/llvm-project/issues/55685, https://github.com/llvm/llvm-project/issues/55493, https://github.com/llvm/llvm-project/issues/55269, https://github.com/llvm/llvm-project/issues/54815, https://github.com/llvm/llvm-project/issues/53748, https://github.com/llvm/llvm-project/issues/51277, https://github.com/llvm/llvm-project/issues/58047, https://github.com/llvm/llvm-project/issues/57228, https://github.com/llvm/llvm-project/issues/51767)
Also, I am confused by the mention of an ubuntu version, but a windows backtrace

**Comment by Backl1ght** [comment]
> Also, I am confused by the mention of an ubuntu version, but a windows backtrace

I think this is possible in WSL?

**Comment by AnneCharlotteh** [comment]
> > Also, I am confused by the mention of an ubuntu version, but a windows backtrace
> 
> I think this is possible in WSL?

Yes, I use a docker on my windows machine.

**Comment by AnneCharlotteh** [comment]
> Could you please try 16 or `main` branch? https://godbolt.org should be helpful.

I couldn't find a way to download the clang-format-16 ? Could you help me please ? Thank you  lot

**Comment by AnneCharlotteh** [comment]
> I don't think there's much to be done here without the configuration used, the source file or the symbolized backtrace. It is likely a crash which has been fixed (see #58606, #57558, #56682, #56670, #56104, #55685, #55493, #55269, #54815, #53748, #51277, #58047, #57228, #51767) Also, I am confused by the mention of an ubuntu version, but a windows backtrace

What configuration could be useful to have enough information and find a way to resolve this error I get ?

**Comment by xgupta** [comment]
> > Could you please try 16 or `main` branch? https://godbolt.org should be helpful.
> 
> I couldn't find a way to download the clang-format-16 ? Could you help me please ? Thank you lot

An example to use clang-format on godbolt.org website - https://godbolt.org/z/8hvhzzq5j. Also, you can build clang-format from the source following the instructions here https://clang.llvm.org/get_started.html - (You have to first clone and then add -DLLVM_ENABLE_PROJECTS=clang while running cmake and then do ninja clang-format to build clang-format).

**Comment by xgupta** [comment]
> What configuration could be useful to have enough information and find a way to resolve this error I get ?

You can provide a reduced test case (.c file) that this signal 11. Also your .clang-format file.

**Comment by xgupta** [comment]
> I don't think there's much to be done here without the configuration used, the source file or the symbolized backtrace.

Agreee, closing as not reproducible, feel free to reopen with details.
