### ISSUE TITLE
Backport "[amdgpu-arch] Fix build of amdgpu-arch with CLANG_LINK_CLANG_DYLIB" to 16.x

### ISSUE THREAD

**Issue by littlewu2508** [llvm/llvm-project#60856]
This fixes a build issue of amdgpu-arch in clang tools, which is observed in clang-16.x. [The fix](https://github.com/llvm/llvm-project/commit/067a5c68845c13d45e85ec9eaa11d2b2d829bab4) is in main branch and should be back-ported to 16.x

cc @jhuber6 @aaronmondal

**Comment by jhuber6** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/067a5c68845c13d45e85ec9eaa11d2b2d829bab4

**Comment by tstellar** [comment]
@jhuber6 Are you able to resolve the conflict of the merge?
