### ISSUE TITLE
[16.0-rc2] lld fails to link mesa

### ISSUE THREAD

**Issue by berolinux** [llvm/llvm-project#60859]
Linking mesa 23.0.0-rc5 with lld 16.0-rc2 results in

`ld.lld: error: version script assignment of 'global' to symbol 'HMI' failed: symbol not defined`

(building it with clang 16.0-rc2 using `-fuse-ld=gold` succeeds, as does using lld 15.0.7).

**Comment by ms178** [comment]
I've seen similar errors with a slightly older Clang-16 snapshot: https://gitlab.freedesktop.org/mesa/mesa/-/issues/8003

**Comment by MaskRay** [comment]
This is a Mesa version script bug that some symbols are not defined. Use https://gitlab.freedesktop.org/mesa/mesa/-/issues/8003 to track it. You can work around it with `-Wl,--undefined-version`.

**Comment by berolinux** [comment]
Similar things happen when trying to build Qt (either version 5 or 6):

```
ld.lld: error: src/corelib/CMakeFiles/Core.dir/global/qversiontagging.cpp.o: symbol qt_version_tag@@Qt_6.4 has undefined version Qt_6.4
ld.lld: error: src/corelib/CMakeFiles/Core.dir/global/qversiontagging.cpp.o: symbol qt_version_tag@Qt_6.3 has undefined version Qt_6.3
ld.lld: error: src/corelib/CMakeFiles/Core.dir/global/qversiontagging.cpp.o: symbol qt_version_tag@Qt_6.0 has undefined version Qt_6.0
ld.lld: error: src/corelib/CMakeFiles/Core.dir/global/qversiontagging.cpp.o: symbol qt_version_tag@Qt_6.1 has undefined version Qt_6.1
ld.lld: error: src/corelib/CMakeFiles/Core.dir/global/qversiontagging.cpp.o: symbol qt_version_tag@Qt_6.2 has undefined version Qt_6.2
ld.lld: error: lto.tmp: symbol qt_version_tag@@Qt_6.4 has undefined version Qt_6.4
```

All the test cases work fine with ld.bfd, gold and mold, as well as lld 15.

While it does look like the version scripts are buggy, maybe given compatibility with the other linkers is a goal, this should be a warning rather than a hard error by default?

**Comment by aaronmondal** [comment]
I've read often that things work with mold, so to clarify:

This is a bug. Mold also flags it, but as a warning which often gets lost in all the output. Please try to actually fix the linker scripts and not rely on molds more relaxed defaults.

Ignoring these [lld errors]/[mold warnings] will lead to issues down the line e.g. when using LTO.
