### ISSUE TITLE
Clang 16-rc2 regression: inherited constructor with dependent constraint

### ISSUE THREAD

**Issue by CaseyCarter** [llvm/llvm-project#60868]
Caught this testing MSVCSTL with 16-rc2. Our implementation of `std::ranges::subrange` has the dependent constraint. I suspect inheriting from `subrange` is fairly rare, and have a workaround, so this isn't a release blocker.

Compiling this well-formed TU:
```c++
template <class> struct B {
  static constexpr bool meow = false;
};

template <class T>
struct D : B<T> {
  template <int = 42>
  D(int) requires (!B<T>::meow) {}
};

struct S : D<void> { using D::D; };

int main() { S{42}; }
```
with `clang++ -std=c++20 -fsyntax-only` diagnoses (https://godbolt.org/z/8a7Maa63e):
```console
repro.cpp:8:20: error: substitution into constraint expression resulted in a non-constant expression
  D(int) requires (!B<T>::meow) {}
                   ^~~~~~~~~~~
repro.cpp:13:14: note: while checking constraint satisfaction for function 'D' required here
int main() { S{42}; }
             ^
repro.cpp:8:20: note: non-literal type '<dependent type>' cannot be used in a constant expression
  D(int) requires (!B<T>::meow) {}
                   ^
1 error generated.
```

**Comment by shafik** [comment]
May be related to: https://github.com/llvm/llvm-project/issues/60777

CC @erichkeane

**Comment by erichkeane** [comment]
Yep, looking at this (and the assertion), I'm about 95% sure this is related to our attempt to implement DR2628 as reproted in #60777.  I'm closing this, and we can consider what we're going to do for 16.0 there.

**Comment by erichkeane** [comment]
Looks like we're reverting in #60777 and submitting to 16, so this should fix that too.
