### ISSUE TITLE
[clang-tidy] [coroutines] Stop using `-fcoroutines-ts` in clang-tidy's test

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#60864]
I'm trying to remove `-fcoroutines-ts` in clang. But I met problems in the test of clang-tidy. In clang-tidy/checkers/readability/identifier-naming.cpp, it uses `-std=c++17 -fcoroutines-ts`. But when I replace the combination with `-std=c++20`, it tells me it can't recognize `co_await` anymore.  Then the test log shows:

```
'-std=c++17', '-fcoroutines-ts', '-I/disk2/workspace.xuchuanqi/llvm-project-for-work/clang-tools-extra/test/clang-tidy/checkers/readability/Inputs/identifier-naming', '-isystem', '/disk2/workspace.xuchuanqi/llvm-project-for-work/clang-tools-extra/test/clang-tidy/checkers/readability/Inputs/identifier-naming/system', '-std=c++11', '-nostdinc++'
```

Here is a `-std=c++11` in the ending place so the `-std=c++20` option doesn't work. I don't know how to move on. Could any one who is familiar with clang-tidy remove the use of `-fcoroutines-ts` in clang-tidy?

**Comment by whisperity** [comment]
It could be that you need to move the `--std=c++20` flag either before the `--`. The `%check_clang_tidy` script itself accepts and understands a `--std` argument. https://github.com/llvm/llvm-project/blob/llvmorg-17-init/clang-tools-extra/test/clang-tidy/check_clang_tidy.py#L22

**Comment by ChuanqiXu9** [comment]
> https://github.com/llvm/llvm-project/blob/llvmorg-17-init/clang-tools-extra/test/clang-tidy/check_clang_tidy.py#L22

Thanks!
