### ISSUE TITLE
[LD-LLD] linker doesn't seem to be able to read stdin when using -T flag

### ISSUE THREAD

**Issue by Ma-Y** [llvm/llvm-project#60875]
passing ```-T -``` doesn't seem to be recognized by linker. 

``` ld-lld.exe ... -T -  ....```
Expected behavior : ```-``` as stdin.
Actual behavior : can't find file - 

while ```clang -x c -``` could regard ```-``` as stdin.

**Comment by Ma-Y** [comment]
I thought i can circumvent this ,but after some digging,I still can't seem to  find a good solution, reopening the issue.

**Comment by MaskRay** [comment]
Whether a file argument interprets `-` as stdin is ad-hoc but ld.bfd doesn't intrepret `-T -` as reading from stdin, either. So the current behavior is intended.
