### ISSUE TITLE
Allocate character with source returns stat = 0 when already allocated

### ISSUE THREAD

**Issue by clementval** [llvm/llvm-project#60897]
The issue comes from the fact that `AllocatableInitCharacter` is called before `AllocatableAllocateSource` and resets the descriptor before the check is done. 

```f90
program test
  character(:), allocatable :: ch
  ch = 'dummy'
 
  allocate(ch, stat=istat, source='fail?')
  if (istat == 0) then
    print*, 'fail to report correct stat'
  end if
end program
```

**Comment by clementval** [comment]
FYI @peixin 
Might be a simple enough issue for someone who wants to contribute.

**Comment by PeixinQiao** [comment]
> Might be a simple enough issue for someone who wants to contribute.

Agree. More people are welcome to contribute. Thanks @clementval.

**Comment by sankeerth125** [comment]
Hi @clementval, is anyone working on it? if not can I do this?

**Comment by clementval** [comment]
@sankeerth125 You can take it. I just assigned it to you.

**Comment by sankeerth125** [comment]
@clementval  Thank You

**Comment by clementval** [comment]
Let me know if anything is unclear

**Comment by ipriyanshi1708** [comment]
I want to contribute to this issue. Please help me how can I contribute like directory level and all.

**Comment by clementval** [comment]
There are two patches accepted that solve this so you should look at other issues.

**Comment by EugeneZelenko** [comment]
@clementval: Could you please provide commits information?
