### ISSUE TITLE
-fuse-ld causes "argument unused warning" which causes Linux Kernel kconfig to fail.

### ISSUE THREAD

**Issue by starlabmtb** [llvm/llvm-project#60902]
Building the Linux kernel with Clang will cause Kconfig to believe that `CONFIG_CC_HAVE_SHADOW_CALL_STACK` is not supported on AArch64.

This is because the Kconfig rule:

```
# Supported by clang >= 7.0
config CC_HAVE_SHADOW_CALL_STACK
        def_bool $(cc-option, -fsanitize=shadow-call-stack -ffixed-x18)
```

Which is further decomposed into a command:

```shell
$CC -Werror $CLANG_FLAGS -fsanitize=shadow-call-stack -ffixed-x18 -c -x c /dev/null -o tmp.o
```

The kernel build will pass Kconfig a fairly lengthy value for `$CC` but it happens to include:

```shell
-fuse-ld=lld
```

Since the Kconfig command is only compiling the dummy source (`-c`), Clang warns that 

```console
clang-14: error: argument unused during compilation: '-fuse-ld=ldd' [-Werror,-Wunused-command-line-argument]
```

It appears Clang sets `-Wunused-command-line-argument` by default.  GCC on the other hand, does not have an unused command line argument warning and so does not experience the issue.   Although we can work around this issue through the kernel makefiles, it is fair to consider whether this is really the correct behavior.

**Comment by MaskRay** [comment]
This is a bug on the Linux kernel side. For most driver options which only affect link actions, we have the `-Wunused-command-line-argument` warning. If a user doesn't want to see the warning, remove it for compile actions (e.g. `-c` `-S` `-fsyntax-only`).
