### ISSUE TITLE
clang std::source_location::current() fail

### ISSUE THREAD

**Issue by PaltryProgrammer** [llvm/llvm-project#60912]
greetings kind regards clang std::current_location::current() results in error as shown MSVC compiles w/o error kindly advise Thank You Kindly
![source_location-current fail](https://user-images.githubusercontent.com/48535920/220535389-9f4e3aa6-345e-4ea1-8130-f1e9e086610f.png)

**Comment by EugeneZelenko** [comment]
Could you please create reproducer on https://godbolt.org ?

**Comment by PaltryProgrammer** [comment]
i do not know what a "reproducer" is . however w/ clang 15.0.0 as i did not see a 17.0.0 it seems to work as you can see 
![clang source_location-current success on godbolt](https://user-images.githubusercontent.com/48535920/220548643-adb8d494-1383-484e-90ab-25671d8fea61.png)

**Comment by fsb4000** [comment]
It's expected.

Microsoft STL requires `__cpp_consteval` to be defined for working `source_location` https://github.com/microsoft/STL/blob/e7f52446c6f41fddbed31904f594a1f711f85601/stl/inc/source_location#L11

And clang 15 doesn't fully implement `cpp_consteval` so it doesn't define that macro.

https://godbolt.org/z/soxeEaxnT

**Comment by fsb4000** [comment]
Actually it looks like compiler devs just forgot to define that macro: https://github.com/llvm/llvm-project/issues/57094

**Comment by PaltryProgrammer** [comment]
if `__cpp_consteval` is required but not provided why was the compile shown [here](https://github.com/llvm/llvm-project/issues/60912#issuecomment-1439537309)  successful ?

**Comment by fsb4000** [comment]
> if `__cpp_consteval` is required but not provided why was the compile shown [here](https://github.com/llvm/llvm-project/issues/60912#issuecomment-1439537309) successful ?

Microsoft STL implementation checks that macro but libc++ and libstdc++ don't check.

**Comment by fsb4000** [comment]
>if `__cpp_consteval` is required

`std::current_location::current()` needs `__cpp_consteval` 100%.

Look: https://en.cppreference.com/w/cpp/utility/source_location/current

It's `consteval`

![изображение](https://user-images.githubusercontent.com/4289847/220586229-856211db-b00a-4afc-b019-7b33328a1c14.png)

**Comment by fsb4000** [comment]
Hi @AaronBallman !

Could you give us some update about `__cpp_consteval` macro?

**Comment by PaltryProgrammer** [comment]
i merely added the macro and it seems to have worked 
![success by adding macro](https://user-images.githubusercontent.com/48535920/220605381-8981374f-92e3-469f-bff4-d4c404bbbeeb.png)

**Comment by AaronBallman** [comment]
> Hi @AaronBallman !
> 
> Could you give us an update about the `__cpp_consteval` macro?

I know we're at least missing support for https://wg21.link/P2564R3 in terms of setting the value to `202211L`, but we might be at the point to define it to `201811L`. I know we're certainly close these days, but a quick look through the bug database shows ~40 open issues related to consteval (not all of these are going to be issues holding us back from claiming conformance though).

One thing that would help is if someone was able to run an experiment defining the macro to the 2018 value and trying to compile a bunch of large C++ relatively modern projects to see if that points out bugs we're not aware of.

**Comment by fsb4000** [comment]
Well, I have pretty slow PC (AMD FX8300) but I could run some projects too.

Do you have a list of such projects?

Also, look what I've found: https://github.com/chromium/subspace/commit/e18b44396169db7e7f46cbef1ead2d0b59b19f88#diff-eb105f54978bac9a1111fa159977cd7cf6d3372ce522c53019c294c4d5142f8eR95

and https://github.com/marzer/muu/commit/25ff4e5513212f46fcffed925fae1140d5739341#diff-9fee50b957f0636d37f5d5ed34361016c89b77729fdd415316d06598e1530ed1R412-R418

**Comment by AaronBallman** [comment]
> Do you have a list of such projects?

Chromium was one such project, but you found something out there! :-D The other projects I usually use for this sort of thing (uncertain of how much consteval use they have, though) are Qt, kokkos, boost, and Folly.
