### ISSUE TITLE
Track source location information in exception specifications

### ISSUE THREAD

**Issue by DougGregor** [llvm/llvm-project#6091]
|  |  |
| --- | --- |
| Bugzilla Link | [5719](https://llvm.org/bz5719) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
They should be part of the type location information for function types, but they aren't. This leads to poor diagnostics with template instantiation, e.g.,

blackthorn:~ dgregor$ cat t.C
```c++
template<typename T> void f1(T*) throw(T);
struct Incomplete;
void test_f1(Incomplete *incomplete_p) {
  f1(incomplete_p); 
}
```
blackthorn:~ dgregor$ clang t.C
```c++
t.C:1:27: error: incomplete type 'struct Incomplete' is not allowed in exception
      specification
template<typename T> void f1(T*) throw(T);
                          ^~
t.C:1:27: note: in instantiation of function template specialization
      'f1<struct Incomplete>' requested here
template<typename T> void f1(T*) throw(T);
                          ^
t.C:2:8: note: forward declaration of 'struct Incomplete'
struct Incomplete;
       ^
3 diagnostics generated.
```

**Comment by philnik777** [comment]
IIUC this is about the caret position not pointing to the exception specification. This has been fixed in Clang 3.6: https://godbolt.org/z/GPf3qcMh6
