### ISSUE TITLE
aliases with internal linkage don't work very well

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#6092]
|  |  |
| --- | --- |
| Bugzilla Link | [5720](https://llvm.org/bz5720) |
| Version | unspecified |
| OS | Linux |
| Attachments | [fpcmp.ll](https://user-images.githubusercontent.com/60944935/143740354-4be84f46-2922-4f90-848c-6e2f29442bc1.gz), [CommandLine.ll.gz (gzipped)](https://user-images.githubusercontent.com/60944935/143740355-eaaa2f79-00f7-4633-aa3c-b35c91d1fb52.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@lattner |

## Extended Description 

If an alias A with internal linkage points to a symbol S with linkonce linkage,
then if the linker throws away the copy of S it is pointing to then you can get a
link-time error, of the sort "A referenced in section .text, defined in discarded
section .B.section".  What would be convenient is for this situation to behave
exactly the same as you would get by replacing all uses of A by B everywhere.

It is true that aliases with internal linkage are in some sense pointless -
because you can just RAUW+delete them, and indeed GlobalOpt does this
(probably the constant folder should fold them too).  However there are also
advantages to allowing them - for example the Internalize pass can produce
them, and it looks like they are convenient for llvm-gcc (ok, dragonegg) in
some circumstances - and you can't always rely on GlobalOpt or the constant
folder being run.

I suggest teaching codegen to use the aliasee B whenever the alias A has
internal linkage, and not output aliases with internal linkage.  This
effectively results in RAUW A with B at codegen time.  It also avoids
requiring support from linkers etc for this odd sort of alias.

As for the testcase, do:

llc CommandLine.ll && llc fpcmp.ll && g++ -o fpcmp fpcmp.s CommandLine.s `llvm-config --libs`

and observe how it fails to link:
`llvm::cl::desc::desc(char const*)' referenced in section `.text' of /tmp/cc2rAgh5.o: defined in discarded section `.gnu.linkonce.t._ZN4llvm2cl4descC2EPKc' of /tmp/cc2rAgh5.o
...

fpcmp attached here, will attach CommandLine.ll later.

**Comment by philnik777** [comment]
Closing, since the only reproducer available doesn't work on any somewhat up-to-date llc.
