### ISSUE TITLE
[OpenMP] invalid access when offload to amdgpu

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#60937]
Use this branch https://github.com/ye-luo/miniqmc/tree/amd-invalid-access
```shell
mkdir build_mi250_llvm_offload_real; cd build_mi250_llvm_offload_real
cmake -DCMAKE_CXX_COMPILER=clang++ -DENABLE_OFFLOAD=ON -DOFFLOAD_TARGET=amdgcn-amdhsa -DOFFLOAD_ARCH=gfx90a ..
make -j32 check_spo_batched_reduction
./bin/check_spo_batched_reduction -n 1 -s 1 -w 2
```
Error
```console
AMDGPU fatal error 1: Memory access fault by GPU 2 (agent 0x5616e63e14c0) at virtual address 0x7f9f19c55000. Reasons: Unknown (0)
Aborted
```
Please ignore the following message when using the reproducer.
```console
Fail in evaluate_vgh, V error =0.294828
Fail in evaluate_vgh, G error =1.1027
```
```console
$ clang++ -v
clang version 17.0.0 (https://github.com/llvm/llvm-project.git 3a3ab2147d7a6673c7b22bd14d8bf33ab1276d85)
```

**Comment by jdoerfert** [comment]
I went on another deep dive and I think the problem is in the AMDGPU backend.
Attached are 4 files: {good, bad}.{ll,s}
As the name suggests, they represent the IR and asm of a "good" and a "bad" version, though neither version is exactly the source program.
The IR was obtained right after the InferAddrSpace pass, and the difference between the two IR files is a single GEP merge + AS deduction on the following load.
The assembly file has interesting differences, and I expect those should not be there. However, I hope @arsenm can shed some light on it.

Funnily, the broken version is super slow (kernel time) compared to the non-broken version.

[Archive.zip](https://github.com/llvm/llvm-project/files/10821081/Archive.zip)

**Comment by nhaehnle** [comment]
I was curious and took a quick look. The main differences I can see are:

* It looks like a flat_load_dwordx2 becomes a ds_read_b64. This is expected given that the bad.ll file uses a different address space. The actual details of this are more complex: a ds_read2_b64 becomes a ds_read_b64, and a ds_read2_b64 appears later on, which is presumably the combined read of what used to be part of the original ds_read2_b64 and the flat_load_dwordx2.
* Way further down in the assembly, the placement of v_readfirstlane instructions changes. That feels a lot more suspicious to me.

**Comment by ye-luo** [comment]
@arsenm Any clue?

**Comment by arsenm** [comment]
This seems to have unfenced barriers. Could this just be a timing issue that https://reviews.llvm.org/D145290 also resolves?

**Comment by ye-luo** [comment]
> This seems to have unfenced barriers. Could this just be a timing issue that https://reviews.llvm.org/D145290 also resolves?

I tested it and still fails

**Comment by jdoerfert** [comment]
[repro_kernel.tar.gz](https://github.com/llvm/llvm-project/files/10939227/repro_kernel.tar.gz)

Another try reducing it. This time the difference between working and broken is a single load replaced by GVN. The broken version consistently crashes (kernel that ends with _l504) while the working one finishes w/o error.

Not sure if/how I should reduce this. If @arsenm or @nhaehnle see anything in the log output (m.*.ll) that would be helpful.

**Comment by jdoerfert** [comment]
[repro.tar.gz](https://github.com/llvm/llvm-project/files/10963429/repro.tar.gz)

Two more reproducers. This time I make them run into a trap that they should not run into (see picture).
<img width="641" alt="Screenshot 2023-03-13 at 6 52 59 PM" src="https://user-images.githubusercontent.com/6248191/224871832-2e014589-b353-40bc-8ad0-db7507a04793.png">

Modifying unrelated parts makes it run fine. I assume some reg-alloc or similar issue.
I included two different minimal modifications that make it run, as well as the suprisingly different assembly.
I think with the executable, and a dynamic library build of LLVM w/ OpenMP offload, one can even reproduce the issue on a GFX90a, see README.

@arsenm, @nhaehnle Can you please take a look?

**Comment by arsenm** [comment]
The materialization of the 1 in bb1696 is move out of the block by MachineCSE. Greedy then decides to rematerialize it in the odd position

**Comment by jdoerfert** [comment]
> The materialization of the 1 in bb1696 is moved out of the block by MachineCSE. Greedy then decides to rematerialize it in the odd position

Good news, disabling MachineCSE prevents the trapping tests from trapping.
Bad news, it doesn't help the reported issue...

**Comment by jdoerfert** [comment]
Since my reproducers seem to expose other issues so far, I'll put them in new bugs and we link whatever solved this later.

**Comment by jdoerfert** [comment]
https://reviews.llvm.org/D145329 seems to fix this.

**Comment by jdoerfert** [comment]
Yeah, https://reviews.llvm.org/D145329 seems to fix this.

**Comment by ye-luo** [comment]
My reproducer no more fails in the nightly build with ff0aabf14dfa0a369c38f6e267c56a83ee48d647

**Comment by ye-luo** [comment]
0fc63d4e642fcf79e9806dc3ae7a49defaae2479 fixed the issue.
More interestingly. I noticed this issue is only reproducible with rocm 5.4.0.
If I use rocm 5.4.3 bits (I guess math/hsa), the old compiler 3a3ab2147d7a6673c7b22bd14d8bf33ab1276d85 also passes.

**Comment by jdoerfert** [comment]
FWIW, there was no fix. We only successfully hid the issue until the next time.
