### ISSUE TITLE
[lld] cref option doesn't accept single dash form

### ISSUE THREAD

**Issue by imciner2** [llvm/llvm-project#60932]
There is an incompatibility between the options handled by `ld` and `lld` in the parsing of the `cref` option. `ld` will accept either one or two dashes in front of the option (i.e. `-cref` or `--cref`) since it has multiple letters. `lld` refuses to accept the single dash option, instead erroring out saying `ld.lld: error: unknown argument '-cref', did you mean '--cref'`.

It looks like the original implementation for `cref` allowed for compatibility with `ld`'s use of both 1 and 2 dashes (https://reviews.llvm.org/D44336), but it was changed in https://github.com/llvm/llvm-project/commit/89e66a3ab3b2958285842ed3705b2264c0f67473 for some reason claiming, "Also delete the single dash form which does not appear to be used.". That broke the compatibility of older code that used to work with both `ld` and `lld`, and we were in fact using the single dash option in our code (https://github.com/KiCad/kicad-source-mirror/blob/cdbb868198389a265fe0a676ea9fcfe87b7a2c10/cvpcb/CMakeLists.txt#L96), and have been for a long time.

**Comment by MaskRay** [comment]
Sorry for the trouble. GNU ld only documents the double-dash form `--cref`, `-cref` doesn't see wildspread uses, `--cref` is an analysis/debugging option anyway. Newer GNU ld options tend to only support `--` (at least for options I added to it). So I am inclined to say that this is probably a wontfix.

**Comment by imciner2** [comment]
> GNU ld only documents the double-dash form --cref

The man page for ld on my up-to-date Fedora 37 install says:

> For options whose names are multiple letters, either one dash or two can precede the option name; for example, -trace-symbol and --trace-symbol are equivalent.  Note---there is one exception to this rule.  Multiple letter options that start with a lower case 'o' can only be preceded by two dashes.  This is to reduce confusion with the -o option.  So for example -omagic sets the output file name to magic whereas --omagic sets the NMAGIC flag on the output.

So I think the support for both `-cref` and `--cref` is documented (and if GNU ld is really only adding support for double dash in newer options, then I guess they have a documentation bug as well because then that paragraph in the man page is wrong).

> we try to be compatible if reasonable, but may avoid doing that if there is some code complexity

Looking at things, I think there isn't much complexity in the support. It should be a case of changing
```
def cref: FF<"cref">, HelpText<"Output cross reference table">;
```
to
```
def cref: F<"cref">, HelpText<"Output cross reference table">;
```
I might be able to do a patch for that even, but I haven't ever submitted anything through phabricator before, so I would need a link to a guide for it.

**Comment by MaskRay** [comment]
ld.bfd(1) is not precise. There are more and more options in binutils-gdb/ld using `EXACTLY_TWO_DASHES`, e.g. `--export-dynamic-symbol, --undefined-version`. `-c` is a short option, so a misspelled `-cref`, say, `-creff` will be recognized as `-c reff`. The documented form for `--cref` is `--cref`. It's an analysis/debugging option, not really for normal uses. I'd object to changes to bring back the previous state...
