### ISSUE TITLE
fatal error: error in backend: Cannot select: intrinsic %llvm.ppc.altivec.vabsduw

### ISSUE THREAD

**Issue by pkubaj** [llvm/llvm-project#60959]
FreeBSD on powerpc64le and powerpc64, LLVM 16.0.0 rc2

Compile:
```c
vector int vec_absd(vector int __a, vector int __b) {
  return __builtin_altivec_vabsduw(__a, __b);
}
```

With:
```shell
/usr/local/llvm16/bin/clang-16 -cc1 -triple powerpc64le-portbld-freebsd13.2 -emit-obj -target-cpu ppc64le cpu_vsx3-30c54f.c
```

Output:
```console
fatal error: error in backend: Cannot select: intrinsic %llvm.ppc.altivec.vabsduw
```

**Comment by chenzheng1030** [comment]
For the `__builtin_altivec_vabsduw` builtin, the CPU must be set to Power9 and above. See https://www.ibm.com/docs/en/openxl-c-and-cpp-aix/17.1.0?topic=functions-vec-absd

**Comment by stefanp-ibm** [comment]
I've given this a try with the latest Top of Trunk and I get the following:
```
$ clang -cc1 -triple powerpc64le-portbld-freebsd13.2 -emit-obj -target-cpu ppc64le vabsduw.c
vabsduw.c:2:10: error: '__builtin_altivec_vabsduw' needs target feature power9-vector
```
We now have the correct error that specifies Power 9 is required for the builtin.

The compilation also succeeds with 
```
$ clang -cc1 -triple powerpc64le-portbld-freebsd13.2 -emit-obj -target-cpu pwr9 vabsduw.c
```

I think that this is expected behaviour.
@pkubaj Can we close this issue?
