### ISSUE TITLE
[slp-vectorizer] IR test hangs on opt (trunk)

### ISSUE THREAD

**Issue by TatyanaDoubts** [llvm/llvm-project#60955]
This bug was found by Azul FuzzGen IR test generator.

https://godbolt.org/z/vY36Mz6o7

Run opt with `-passes='slp-vectorizer'`
Test passes on stable opt 15.0.0

**Comment by RKSimon** [comment]
This is probably a duplicate of #61224 - fixed by c411965820eb803dd7eac39f80357cad663b7ba0
