### ISSUE TITLE
[clang][ExtractAPI] Availability does not handle platform specific unavailability correctly

### ISSUE THREAD

**Issue by daniel-grumberg** [llvm/llvm-project#60954]
ExtractAPI does not emit correct availability information for symbols marked as unavailable on a specific platform, e.g.
```c
void foo(void) __attribute__((availability(ios,unavailable)));
```
will yield an availability section that looks like this in symbol graph JSON:
```
{
  domain: ios
}
```
the expectation is instead that the availability section for that symbol looks like:
```
{
  domain ios,
  isUnconditionallyUnavailable: true
}
```
The spec for the symbol graph output can be found at https://github.com/apple/swift-docc-symbolkit/blob/main/openapi.yaml

**Comment by sankeerth125** [comment]
Hi @daniel-grumberg , is anyone working on it? if not can I do this?

**Comment by Arsenic-ATG** [comment]
> Hi @daniel-grumberg , is anyone working on it? if not can I do this?

Hi @sankeerth125 I was actually planning to work on this as my introductory project to ExtractAPI and LLVM in general

**Comment by sankeerth125** [comment]
Hi @Arsenic-ATG, Thanks for the info.

**Comment by Arsenic-ATG** [comment]
marking it as done after 65f7a84cf38b9839de0f29877d5ba4895848ea73
