### ISSUE TITLE
Clang -E incorrect -Wunicode diagnostic

### ISSUE THREAD

**Issue by andyhhp** [llvm/llvm-project#60958]
Discovered entirely accidentally while trying to work around #60792

Given
```console
$ cat hdr.h 
.macro test uniq
    mov $\uniq, %eax
.endm

$ cat src.c
#include "hdr.h"

$ clang-15 -E src.c -o out.i
In file included from src.c:1:
./hdr.h:2:11: warning: \u used with no following hex digits; treating as '\' followed by identifier [-Wunicode]
    mov $\uniq, %eax
          ^
```

But there's are no strings here, and no context AFAICT where it would be legitimate to interpret `\u` as a Unicode escape in the first place.

But if I rename `src.c` to `src.S`, it behaves differently
```console
$ cp src.c src.S
$ clang-15 -E src.S -o out.i
$
```
and completes with no complaints.

Clearly this diagnostic is conditional on the file extension (which isn't great behaviour to start with), but I don't think it's a legitimate diagnostic for `*.c` files in the first place either.

It's worth saying for completeness that macros written entirely at the C level work fine, because they have to be written as 
```c
asm (".macro test uniq; mov $\\uniq, %eax; .endm");
```
with the backslash needing to be escaped, rather than the `u`.

**Comment by andyhhp** [comment]
I didn't know this previously, but it turns out that the C grammar explicitly includes `universal-character-name` in `identifier-nondigit`, meaning it is legal to write code such as:
```c
void \u0024(void) {}
```
to create a function named `$`.

I've worked around this in Xen by renaming a specific `.c` file to `.S`, because it's more correct generally (after all, we are generating assembly code, not C).

I agree that the diagnostic is appropriate for code being compiled as C, but I'd still argue that simply preprocessing a file (which produces text as an output) oughtn't to trigger the diagnostic.

**Comment by AaronBallman** [comment]
> I agree that the diagnostic is appropriate for code being compiled as C, but I'd still argue that simply preprocessing a file (which produces text as an output) oughtn't to trigger the diagnostic.

I believe it should still produce the diagnostic, as the preprocessor also works with identifiers. e.g. `#ifdef identifier` and the `identifier` production includes `universal-character-name` which is what \u leads to.

As best I can tell, this is behaving as expected -- renaming the source to no longer be considered C code is the correct solution (or using `-x` to specify a different language mode).

**Comment by andyhhp** [comment]
> > I agree that the diagnostic is appropriate for code being compiled as C, but I'd still argue that simply preprocessing a file (which produces text as an output) oughtn't to trigger the diagnostic.
> 
> I believe it should still produce the diagnostic, as the preprocessor also works with identifiers. e.g. `#ifdef identifier` and the `identifier` production includes `universal-character-name` which is what \u leads to.

Oh, of course.  That's subtle.

> As best I can tell, this is behaving as expected -- renaming the source to no longer be considered C code is the correct solution (or using `-x` to specify a different language mode).

Yeah ok - you've convinced me.  Sorry for the noise.
