### ISSUE TITLE
[MLIR] Invalid IRs generated by irrelevant optimization pass

### ISSUE THREAD

**Issue by sweead** [llvm/llvm-project#60969]
This is a very interesting test case. I found that there are some passes on it that output invalid IRs. There is no `scf` dialect in this test case, so `-scf-for-to-while` should not take effect, but actually produces invalid IRs with no content in funcOp. 

I also found several similar bugs on this test case. Maybe the reason behind this problem may be similar, I will try to find the root cause of the bugs.

Reproduce cmd:
```shell
mlir-opt -scf-for-to-while core-ops.mlir
```
IR:
```mlir
func.func @affine_apply() {
  %i = "arith.constant"() {value = 0: index} : () -> index
  %j = "arith.constant"() {value = 1: index} : () -> index
  %a = "affine.apply" (%i) { map = affine_map<(d0) -> (d0 + 1)> } :
    (index) -> (index)
  %b = affine.apply affine_map<()[x] -> (x+1)>()[%i]
  return
}
```
Outputs:
```mlir
module {
  func.func @affine_apply1() {
    return
  }
}
```

**Comment by joker-eph** [comment]
How is the output "invalid IR"? Seems like well formed to me right now.

Also, about whether the transformation is correct: the input IR has no side-effect and the values aren't used, they can be just removed freely I believe.

**Comment by sweead** [comment]
> Also, about whether the transformation is correct: the input IR has no side-effect and the values aren't used, they can be just removed freely I believe

Thanks for pointing this out! 
I added input and output to rewrite this IR and now it works. 

IR:
```
func.func @affine_apply(%i:index) -> index  {
  %j = "arith.constant"() {value = 1: index} : () -> index
  %a = "affine.apply" (%i) { map = affine_map<(d0) -> (d0 + 1)> } :
    (index) -> (index)
  %b  = affine.apply affine_map<()[x] -> (x+1)>()[%i]
  return %b :index
}
```
Output:
```
#map = affine_map<()[s0] -> (s0 + 1)>
module {
  func.func @affine_apply(%arg0: index) -> index {
    %0 = affine.apply #map()[%arg0]
    return %0 : index
  }
}
```
