### ISSUE TITLE
mlir::Inliner default textual representation doesn't canonicalize when recreated with MlirOptMain

### ISSUE THREAD

**Issue by changm** [llvm/llvm-project#60960]
The [mlir::createInlinerPass()](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Transforms/Inliner.cpp#L824) by default creates a pipline that always runs [canonicalization](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Transforms/Inliner.cpp#L39). When this pass is dumped to text for MLIR reproduction, it is output as such:

`inline{default-pipeline= max-iterations=4 }`

When the pass is recreated with [MLIROptMain](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp), the Canonicalizer is not run, so there's a slight difference in how the pass works when created with dumped pipelines versus what happens when the pipeline is created programatically.

Example program is attached:
[inliner.txt](https://github.com/llvm/llvm-project/files/10818693/inliner.txt)

The `%cst_1` is folded out when run with a pipeline with `mlir::createInlinerPass` but is not when run via MlirOptMain.

This seems to be happening because the [defaultPipeline](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Transforms/Inliner.cpp#L811) gets erased when the flag `default-pipeline` exists, but the `default-pipeline` doesn't dump `canonicalize`, but I could be way off :). Thanks!

**Comment by wpmed92** [comment]
@changm
I modified your example to use a built-in dialect, so that it can be run without the tensorflow dialect:

```mlir
{-# external_resources: { mlir_reproducer: { pipeline: "builtin.module(inline{default-pipeline= max-iterations=4 })", disable_threading: true, verify_each: true } } #-}

module {
  func.func @inline_canonicalize() -> tensor<2xi32>  {
    %cst = "arith.constant"() { value = dense<2> : tensor<2xi32> } : () -> tensor<2xi32>
    %cst_1 = "arith.constant"() { value = dense<3> : tensor<3xi32> } : () -> tensor<3xi32>
    func.return %cst : tensor<2xi32>
  }
}
```

> This seems to be happening because the [defaultPipeline](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Transforms/Inliner.cpp#L811) gets erased when the flag default-pipeline exists, but the default-pipeline doesn't dump canonicalize, but I could be way off :)

You're right. Commenting out setting `defaultPipeline` to `nullptr` solves the problem, and the constant is folded out. However, the main problem to me seems to be why ` max-iterations=4` is dumped and not `canonicalize{max-iterations=4}` in which case canonicalization runs fine.:

```mlir
{-# external_resources: { mlir_reproducer: { pipeline: "builtin.module(inline{default-pipeline=canonicalize{max-iterations=4}})", disable_threading: true, verify_each: true } } #-}

module {
  func.func @inline_canonicalize() -> tensor<2xi32>  {
    %cst = "arith.constant"() { value = dense<2> : tensor<2xi32> } : () -> tensor<2xi32>
    %cst_1 = "arith.constant"() { value = dense<3> : tensor<3xi32> } : () -> tensor<3xi32>
    func.return %cst : tensor<2xi32>
  }
}
```

Out:
```
module {
  func.func @inline_canonicalize() -> tensor<2xi32> {
    %cst = arith.constant dense<2> : tensor<2xi32>
    return %cst : tensor<2xi32>
  }
}
```

cc: @River707

**Comment by wpmed92** [comment]
The dumping error is reproducable my running:
`./mlir-opt  ../../inliner.txt -pass-pipeline="builtin.module(inline)" -dump-pass-pipeline`


Out:
```
Pass Manager with 1 passes:
builtin.module(inline{default-pipeline= max-iterations=4 })

module {
  func.func @inline_canonicalize() -> tensor<2xi32> {
    %cst = arith.constant dense<2> : tensor<2xi32>
    return %cst : tensor<2xi32>
  }
}
```

**Comment by wpmed92** [comment]
I submitted a patch for this: https://reviews.llvm.org/D145066

**Comment by changm** [comment]
Thank you for fixing this!

**Comment by wpmed92** [comment]
@River707 Could you please have a look at my patch?
