### ISSUE TITLE
std::default_initializable in libc++ accepts an std::unordered_set of a type with no hash

### ISSUE THREAD

**Issue by captaincrutches** [llvm/llvm-project#61007]
Godbolt: https://clang.godbolt.org/z/aqahhrdvK

Code to reproduce:
```cpp
#include <concepts>
#include <unordered_set>

struct foo {};

static_assert(!std::default_initializable<std::unordered_set<foo>>);
```

This compiles correctly in GCC as far back as 10, and indeed Clang also accepts it when using `libstdc++` as far back as Clang 13.

When using libc++ however, it fails (on Clang 13, 14, 15, and trunk):
```console
<source>:6:1: error: static assertion failed due to requirement '!std::default_initializable<std::unordered_set<foo, std::hash<foo>, std::equal_to<foo>, std::allocator<foo>>>'
static_assert(!std::default_initializable<std::unordered_set<foo>>);
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Compiler returned: 1
```

Each component of `default_initializable` (`constructible_from` and a default constructor itself) also pass the `static_assert`.  But in all cases, clang does correctly fail to actually construct an `std::unordered_set<foo>`.

It does correctly conclude that `std::default_initializable<std::hash<foo>>` is false.

**Comment by shafik** [comment]
This does look specific to libc++ CC @mordante @ldionne wdyt is this expected?

**Comment by mclow** [comment]
More:
```
#include <unordered_set>
#include <type_traits>

struct Foo {};

int main () {
    // std::unordered_set<Foo> us;
    static_assert(!std::default_initializable<std::unordered_set<Foo>>, ""); // <<== FAILS on libc++
    static_assert( std::default_initializable<Foo>, "");
    static_assert( std::default_initializable<std::less<Foo>>, "");
    static_assert(!std::default_initializable<std::hash<Foo>>, "");
    static_assert( std::default_initializable<std::allocator<Foo>>, "");
}
```

All of the static_asserts pass on libstdc++, but the first one fails on libc++

**Comment by frederick-vs-ja** [comment]
`std::unordered_set`'s default constructor is unconstrained per standard ([[unord.set.cnstr]](https://eel.is/c++draft/unord.set.cnstr)), so I think libc++ & MSVC STL's behavior (considering it well-formed when not instantiated, hard error on instantiation) is OK.

**Comment by captaincrutches** [comment]
What `default_initializable` is checking though is "can we initialize this type _right now_?" - which we can't.

> Access checking is performed as if in a context unrelated to T. Only the validity of the immediate context of the variable initialization is considered. 

So either the default constructor should work at the point of the `static_assert`, or `default_initializable` should fail.   
The default constructor fails here, so it isn't `default_initializable`.

**Comment by philnik777** [comment]
> What `default_initializable` is checking though is "can we initialize this type _right now_?" - which we can't.
> 
> > Access checking is performed as if in a context unrelated to T. Only the validity of the immediate context of the variable initialization is considered.
> 
> So either the default constructor should work at the point of the `static_assert`, or `default_initializable` should fail. The default constructor fails here, so it isn't `default_initializable`.

The standard library containers are generally not SFINAE-friendly. In fact, most template classes out there aren't, since most classes are unconstrained.

**Comment by captaincrutches** [comment]
I'm not sure what SFINAE has to do with whether the default constructor should succeed here?  SFINAE removes the `unordered_set<foo>()` constructor from overload resolution, and because there are no candidates left after that, it should fail.  Thus, not `default_initializable`.

**Comment by philnik777** [comment]
> I'm not sure what SFINAE has to do with whether the default constructor should succeed here? SFINAE removes the `unordered_set<foo>()` constructor from overload resolution, and because there are no candidates left after that, it should fail. Thus, not `default_initializable`.

That's the whole point. The default constructor _doesn't_ get SFINAEd away.

**Comment by captaincrutches** [comment]
> The default constructor doesn't get SFINAEd away.

Okay, I misunderstood you there.  It makes sense that SFINAE doesn't come into play here - we're calling an unambiguous constructor, and that fails.

In fact, I can make a similarly unconstrained template myself, and it behaves as I'd expect here (i.e. differently from `std::unordered_set`):
```cpp
struct foo {};

template <typename T, typename hash = std::hash<T>>
struct bar
{
    hash h;
};

// Fails due to implicitly deleted default constructor
bar<foo> b;
// Passes because we can't instantiate the type
static_assert(!std::default_initializable<bar<foo>>);

// Fails due to implicitly deleted default constructor
std::unordered_set<foo> s;
// Fails even though we can't instantiate the type (this issue)
static_assert(!std::default_initializable<std::unordered_set<foo>>);
```
That said, the error messages are slightly different in each case.

When instantiating a `bar<foo>`, both `libstdc++` and `libc++` tell me that `bar<foo>` has an implicitly deleted default constructor because `hash<foo>`'s default constructor is deleted.

When instantiating an `unordered_set<foo>`, `libstdc++` tells me essentially the same thing, just with a couple more layers in between the implicitly-deleted constructor and the deleted `hash` constructor.

`libc++` however jumps right to the `hash` constructor being deleted (because `__enum_hash`'s constructor is deleted) while instantiating the `unordered_set` constructor, pointing at a failed `static_assert`.  In other words, it doesn't directly tell me the `unordered_set` constructor is implicitly deleted, it just fails to instantiate it.

Try it here: https://clang.godbolt.org/z/s4dnq4f9n

In either case, however, the end result is we fail to instantiate the default constructor of `unordered_set<foo>`, so we can't default initialize the type.

**Comment by philnik777** [comment]
> > The default constructor doesn't get SFINAEd away.
> 
> Okay, I misunderstood you there. It makes sense that SFINAE doesn't come into play here - we're calling an unambiguous constructor, and that fails.
> 
> In fact, I can make a similarly unconstrained template myself, and it behaves as I'd expect here (i.e. differently from `std::unordered_set`):
> 
> ```c++
> struct foo {};
> 
> template <typename T, typename hash = std::hash<T>>
> struct bar
> {
>     hash h;
> };
> 
> // Fails due to implicitly deleted default constructor
> bar<foo> b;
> // Passes because we can't instantiate the type
> static_assert(!std::default_initializable<bar<foo>>);
> 
> // Fails due to implicitly deleted default constructor
> std::unordered_set<foo> s;
> // Fails even though we can't instantiate the type (this issue)
> static_assert(!std::default_initializable<std::unordered_set<foo>>);
> ```
> 
> That said, the error messages are slightly different in each case.
> 
> When instantiating a `bar<foo>`, both `libstdc++` and `libc++` tell me that `bar<foo>` has an implicitly deleted default constructor because `hash<foo>`'s default constructor is deleted.
> 
> When instantiating an `unordered_set<foo>`, `libstdc++` tells me essentially the same thing, just with a couple more layers in between the implicitly-deleted constructor and the deleted `hash` constructor.
> 
> `libc++` however jumps right to the `hash` constructor being deleted (because `__enum_hash`'s constructor is deleted) while instantiating the `unordered_set` constructor, pointing at a failed `static_assert`. In other words, it doesn't directly tell me the `unordered_set` constructor is implicitly deleted, it just fails to instantiate it.
> 
> Try it here: https://clang.godbolt.org/z/s4dnq4f9n
> 
> In either case, however, the end result is we fail to instantiate the default constructor of `unordered_set<foo>`, so we can't default initialize the type.

I think there is a slight disconnect somewhere. SFINAE _does_ come into play here (not literally, in the sense of constraints). In your example, the default constructor _is_ constrained in a sense. Not explicitly, but it implicitly doesn't exist. The slight difference in the error message is here _very_ important. "Failed to instantiate" means that there is a default constructor, but it's ill-formed. "implicitly-deleted" means that the is no default constructor. Let's break it down a bit. We have a class without a default constructor and a class template which declares a default constructor:
```c++
#include <concepts>

struct NoDefaultCtor {
  NoDefaultCtor(int);
};

template <class T>
class MyClass {
public:
  MyClass();

private:
  T val;
};
static_assert(std::default_initializable<MyClass<NoDefaultCtor>>);
```
[This is perfectly valid C++ code](https://godbolt.org/z/rhYMnv8aK). The question is now: What would happen if I let the compiler know how `MyClass::MyClass` is defined? Here are two potential implementations:
```c++
template <class T>
MyClass<T>::MyClass() : val(69) {}
```
```c++
template <class T>
MyClass<T>::MyClass() {}
```
When instantiating `MyClass<NoDefaultCtor>`, the first one will work just fine, while the second one will be ill-formed. Note that the compiler will be completely happy until you actually try to use the default constructor. IOW, `std::default_initializable` is an unevaluated context. This means that the compiler will only check whether there is a function (in this case a constructor) that can be called. Kind-of like you can declare a functions, but have an error in the definition. The function could be called, the definition is just ill-formed. This could be changed by constraining it, e.g. add an `enable_if` (literal SFINAE) or `requires` clause to the declaration.

Now, back to the `unordered_map`. The standard defines [here](http://eel.is/c++draft/unord.map.cnstr) how the default constructor for it looks. Much more interesting for us is the synopsis though. That's defined [here](http://eel.is/c++draft/unord.map#overview-3). Note that it just says `unordered_map();`. This is basically all the compiler has to find out whether the type is default constructible. Since it's unconstrained, the type basically says "yep, I'm always default constructible". This might be wrong from a conceptual point of view, but that's how the standard defines it.

**Comment by philnik777** [comment]
Closing this, since the standard clearly allows this behaviour (and arguably even mandates it).
