### ISSUE TITLE
std::string unnecessarily maintains a null terminated char array all the time.

### ISSUE THREAD

**Issue by hiraditya** [llvm/llvm-project#61013]
This is probably out of convenience to simplify `data()` or `c_str()`. There is no need to maintain a null terminated char-array inside std::string. Because of this all the operations that increase the size of string has a redundant operation that adds a null-byte at the end of the string.

e.g., insert, push_back

```cpp
basic_string<_CharT, _Traits, _Allocator>::insert(const_iterator __pos, value_type __c)
{
...
    traits_type::assign(__p[__ip], __c);
    traits_type::assign(__p[++__sz], value_type()); // extra assignment
```

for push_back
```cpp
void
basic_string<_CharT, _Traits, _Allocator>::push_back(value_type __c)
{
...
    traits_type::assign(*__p, __c);
    traits_type::assign(*++__p, value_type()); // extra assignment
```

This extra assignment hurts performance. For example `std::getline` calls `string::push_back` for each character [#21566]

**Comment by philnik777** [comment]
No, this is mandated by the standard: http://eel.is/c++draft/basic.string#general-3. As long as the capacity doesn't change, this null terminator can be assumed, even if the call to `data()` was before the size change. To fix the `push_back` in `getline` you can use the `__resize_default_init`. This obviously doesn't work for non-internal stuff, but `resize_and_overwrite` exists in C++23 for this exact problem.

**Comment by hiraditya** [comment]
Thanks for the clarification. If we grow the string with null-terminated array then will it be possible to remove all the redundant `traits_type::assign(*++__p, value_type());` ?

**Comment by philnik777** [comment]
> Thanks for the clarification. If we grow the string with null-terminated array then will it be possible to remove all the redundant `traits_type::assign(*++__p, value_type());` ?

What do you mean with "grow the string with null-terminated array"?

**Comment by hiraditya** [comment]
> What do you mean with "grow the string with null-terminated array"?

sorry I meant array filled with zeros or `value_type()` 

When string needs to grow in size with operations that increase the size of the string like `string::push_back` or `string::operator+` , if we allocate an array filled with `value_type()`, the extra `traits_type::assign(*++__p, value_type())` can be avoided in each case.

**Comment by philnik777** [comment]
> > What do you mean with "grow the string with null-terminated array"?
> 
> sorry I meant array filled with zeros or `value_type()`
> 
> When string needs to grow in size with operations that increase the size of the string like `string::push_back` or `string::operator+` , if we allocate an array filled with `value_type()`, the extra `traits_type::assign(*++__p, value_type())` can be avoided in each case.

Yeah, we could just `resize()` the string to some large-ish value and then `resize()` it back to the correct size in the end. I thought the idea was to remove the extra null termination entirely? Or is it already such a performance improvement to `memset()` the array once and then overwrite only the new elements?

**Comment by hiraditya** [comment]
> I thought the idea was to remove the extra null termination entirely?

My intent was to remove the extra `traits_type::assign(*++__p, value_type())` as this occurs every time we add something to the string.

> Or is it already such a performance improvement to memset() the array once and then overwrite only the new elements?

So just doing memset every time string grows in size should be sufficient.
