### ISSUE TITLE
ld.lld: Symbol in executable has `NULL` instead of a reloc value

### ISSUE THREAD

**Issue by MasterAwesome** [llvm/llvm-project#61017]
I'm trying to compile a binary, and export a symbol, but when it requires relocation, ld.lld emits `0x0` whereas GNU linker correctly generates the relocation value.

# Reproduction
```c
// main.c
__attribute__((visibility("default"))) const char *EXPORTED_VAR = "HelloWorld";

int main() {
    return 0;
}
```

# Expected (GNU Linker)
```sh
$ clang ./main.c -fPIC -o main -Wl,--export-dynamic 
$ gdb -nx -batch -q ./main  -ex "p/s (char*) EXPORTED_VAR" 
    $1 = 0x2004 "HelloWorld"
```

# Actual (LD.LLD)
```sh
$ clang ./main.c -fPIC -o main -Wl,--export-dynamic -fuse-ld=lld
$ gdb -nx -batch -q ./main  -ex "p/s (char*) EXPORTED_VAR" 
    $1 = 0x0
```

The only difference between the commands is `-fuse-ld=lld`. Even though I've mentioned `-Wl,--export-dynamic`, lld seems to not relocate the symbol in the resultant binary. Is there something I'm missing in terms of LLD specific flags?

## Tested on
```
Ubuntu clang version 15.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
This bug is still present in the `master` branch

When I disable PIE using `-nopie` this generates correct address of `EXPORTED_VAR`

```sh
$ clang ./main.c -nopie -o main -Wl,--export-dynamic -fuse-ld=lld 
$ gdb -nx -batch -q ./main  -ex "p/s (char*) EXPORTED_VAR" 
    $1 = 0x200564 "HelloWorld"
```

**Comment by arichardson** [comment]
This sounds like expected behaviour to me. The symbol value should be correct once you actually allow GDB to run the program up to `main` and relocations have been processed by the runtime linker.
It appears that ld.bfd is defaulting to non-PIE binaries whereas with ld.lld you get PIE binaries.

**Comment by MasterAwesome** [comment]
You're correct. Turns out the platform I was testing on didn't do this correctly and it ended up always being NULL. I'll close this now
