### ISSUE TITLE
gvn-hoist hoists uses of inline assembly results before inline assembly

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#61023]
LLVM commit: f4a78830b80
Reproduce with
```shell
opt -passes=gvn-hoist bbi-79336_2.ll -o /dev/null
```
Result:
```console
Instruction does not dominate all uses!
  %0 = callbr { i32, i32 } asm sideeffect "somestuff", "=r,=r,!i"()
          to label %asm.fallthrough [label %err.split]
  %asmresult = extractvalue { i32, i32 } %0, 0
LLVM ERROR: Broken module found, compilation aborted!
```
So gvn-hoist has hoisted the use of `%0` before the definition of `%0`:
```ll
  %asmresult = extractvalue { i32, i32 } %0, 0
  %0 = callbr { i32, i32 } asm sideeffect "somestuff", "=r,=r,!i"()
          to label %asm.fallthrough [label %err.split]
```
The input in `bbi-79336_2.ll` is what we get from Clang nowadays after 329ef60f3e2
```
[Clang] support for outputs along indirect edges of asm goto

Initial support for asm goto w/ outputs (D69876) only supported outputs
along the "default" (aka "fallthrough") edge.

We can support outputs along all edges by repeating the same pattern of
stores along the indirect edges that we allready do for the default
edge.  One complication is that these indirect edges may be critical
edges which would need to be split. Another issue is that mid-codgen of
LLVM IR, the control flow graph might not reflect the control flow of
the final function.

To avoid this "chicken and the egg" problem assume that any given
indirect edge may become a critical edge, and pro-actively split it.
This is unnecessary if the edge does not become critical, but LLVM will
optimize such cases via tail duplication.

Fixes: https://github.com/llvm/llvm-project/issues/53562

Reviewed By: void

Differential Revision: https://reviews.llvm.org/D136497
```
[bbi-79336_2.ll.gz](https://github.com/llvm/llvm-project/files/10838440/bbi-79336_2.ll.gz)

**Comment by bjope** [comment]
I suspect that GVNHoist isn't expecting that a terminator such as callbr can be defining a value. So when it hoists it sets the insertion point to just before the terminator of a BB.

Something like this might work around the problem:
`diff --git a/llvm/lib/Transforms/Scalar/GVNHoist.cpp b/llvm/lib/Transforms/Scalar/GVNHoist.cpp
index 88dba4d3c869..d7ff5fae69ef 100644
--- a/llvm/lib/Transforms/Scalar/GVNHoist.cpp
+++ b/llvm/lib/Transforms/Scalar/GVNHoist.cpp
@@ -922,7 +922,8 @@ bool GVNHoist::allOperandsAvailable(const Instruction *I,
                                     const BasicBlock *HoistPt) const {
   for (const Use &Op : I->operands())
     if (const auto *Inst = dyn_cast<Instruction>(&Op))
-      if (!DT->dominates(Inst->getParent(), HoistPt))
+      if (!DT->dominates(Inst->getParent(), HoistPt) ||
+          Inst->isTerminator())
         return false;
 
   return true;
@@ -932,7 +933,8 @@ bool GVNHoist::allGepOperandsAvailable(const Instruction *I,
                                        const BasicBlock *HoistPt) const {
   for (const Use &Op : I->operands())
     if (const auto *Inst = dyn_cast<Instruction>(&Op))
-      if (!DT->dominates(Inst->getParent(), HoistPt)) {
+      if (!DT->dominates(Inst->getParent(), HoistPt) ||
+          Inst->isTerminator())) {
         if (const GetElementPtrInst *GepOp =
                 dyn_cast<GetElementPtrInst>(Inst)) {
           if (!allGepOperandsAvailable(GepOp, HoistPt))

`

But I'm not sure that is the prettiest of solutions. We could probably detect this scenario earlier, to rule out this. And there is some logic to handle exceptions (GVNHoist::hasEH etc) which I suspect is a bit similar.

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D144927

Thanks for the report. If I may ask, what project were you compiling where you found this?
