### ISSUE TITLE
Tip of tree ld64.lld report "No available targets" when using `-object_path_lto`

### ISSUE THREAD

**Issue by zeroomega** [llvm/llvm-project#61031]
We recently rolled LLVM toolchain and noticed a linker error on the Mac builder:
```console
[3356/6995] LINK ./geometry_benchmarks
[3357/6995] SOLINK libtessellator.dylib libtessellator.dylib.TOC
FAILED: libtessellator.dylib libtessellator.dylib.TOC 
if [ ! -e ./libtessellator.dylib -o ! -e ./libtessellator.dylib.TOC ] || otool -l ./libtessellator.dylib | grep -q LC_REEXPORT_DYLIB ; then ../../buildtools/mac-x64/clang/bin/clang++ -shared -isysroot /Volumes/Work/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk -mmacosx-version-min=10.14.0  -Wl,-object_path_lto,./lto_libtessellator.o -arch x86_64 -nostdlib++ -Wl,-search_paths_first -L. -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -o ./libtessellator.dylib -Wl,-filelist,./libtessellator.dylib.rsp   -framework Foundation && { otool -l ./libtessellator.dylib | grep LC_ID_DYLIB -A 5; nm -gP ./libtessellator.dylib | cut -f1-2 -d' ' | grep -v U$$; true; } > ./libtessellator.dylib.TOC; else ../../buildtools/mac-x64/clang/bin/clang++ -shared -isysroot /Volumes/Work/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk -mmacosx-version-min=10.14.0  -Wl,-object_path_lto,./lto_libtessellator.o -arch x86_64 -nostdlib++ -Wl,-search_paths_first -L. -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -o ./libtessellator.dylib -Wl,-filelist,./libtessellator.dylib.rsp   -framework Foundation && { otool -l ./libtessellator.dylib | grep LC_ID_DYLIB -A 5; nm -gP ./libtessellator.dylib | cut -f1-2 -d' ' | grep -v U$$; true; } > ./libtessellator.dylib.tmp && if ! cmp -s ./libtessellator.dylib.tmp ./libtessellator.dylib.TOC; then mv ./libtessellator.dylib.tmp ./libtessellator.dylib.TOC ; fi; fi
ld64.lld: error: No available targets are compatible with triple ""
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
We did a bisecting and we believe this error starts to manifest after patch aa0883b59ae17e5465906dad51b5561b5292a28d .

Upon inspection, the patch itself doesn't seem to introduce the bug, instead it enabled a few features by default and likely one of them doesn't have the target triple properly propagated, therefore we are seeing failures like this.

The error can be reproduced on a Mac x64 machine with following steps:

* Create a source file `foo.c` containing `int foo() { return 123; }`
* Run `clang++ -c -o foo.o foo.c` 
* Run `clang++ -shared -nostdlib -Wl,-object_path_lto,foo.o -o foo.dylib foo.o`

With aa0883b59ae17e5465906dad51b5561b5292a28d, it will output: `ld64.lld: error: No available targets are compatible with triple ""`. Without aa0883b59ae17e5465906dad51b5561b5292a28d, the Clang++ will return 0.

**Comment by int3** [comment]
@nico wanna have a look at this?

**Comment by zeroomega** [comment]
I looked into this problem a bit on my Mac, I think the root issue is that the `DefaultTriple` variable from https://github.com/llvm/llvm-project/blob/aa0883b59ae17e5465906dad51b5561b5292a28d/llvm/include/llvm/LTO/Config.h#L109 is not set in function `createConfig` in file lld/MachO/LTO.cpp : https://github.com/llvm/llvm-project/blob/aa0883b59ae17e5465906dad51b5561b5292a28d/lld/MachO/LTO.cpp#L54-L78 . This Config is propagated to `initAndLookupTarget` at https://github.com/llvm/llvm-project/blob/aa0883b59ae17e5465906dad51b5561b5292a28d/llvm/lib/LTO/LTOBackend.cpp#L475 and it is an empty string, eventually causes the `No available targets are compatible with triple ""` error we saw. 

I am not familiar this part of code. But I assume we can infer the target triple from the input files and set the `DefaultTriple` and it should fix it.

**Comment by keith** [comment]
Here's a potential fix: https://reviews.llvm.org/D145268

**Comment by keith** [comment]
alternative fix: https://reviews.llvm.org/D145273
