### ISSUE TITLE
Cleanup libc time functions wrt their use of errno

### ISSUE THREAD

**Issue by sivachandra** [llvm/llvm-project#61035]
This cleanup is to aid with https://discourse.llvm.org/t/rfc-improving-the-hermeticity-of-tests-with-respect-to-errno/68684. Couple of things to be done:

1. Make the helper functions more idiomatic wrt setting `errno`. We do not want to set `errno` in helper functions. The helper functions should instead return `cpp::optional` or `__llvm_libc::ErrorOr` as appropriate.
2. If a standard spec requires that a libc function set `errno` on error, then it should be just before returning from that function.

**Comment by sivachandra** [comment]
Umbrella bug #61037

**Comment by sivachandra** [comment]
When you are preparing the patches, use the new `libc_errno` macro which was added by https://reviews.llvm.org/D144928.

**Comment by rtenneti-google** [comment]
I will upload a patch this evening for CR (I will use libc_errno macro).

Thanks for the macro. I will use the following CL as a template to make the
changes to llvm_libc's time code that is already checked in.

-Raman
