### ISSUE TITLE
[Modules] EvaluateAsInitializer executed on used variable templates in every importer

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#61040]
Given the following two translation units:

```cpp
export module a;

#define REPEAT8(x) \
	(x), \
	(x), \
	(x), \
	(x), \
	(x), \
	(x), \
	(x), \
	(x)


unsigned a() {
	unsigned x = 0;
	REPEAT8(REPEAT8(REPEAT8(REPEAT8(REPEAT8(REPEAT8(++x))))));
	return x;
}

template<typename>
unsigned aa = a();

void aaa() {
	aa<int>;
}
```

```cpp
export module b;

import a;
```

And compiled with

```shell
clang++ -std=c++20 -x c++-module --precompile -c a.cpp -o a.pcm
clang++ -std=c++20 -fmodule-file=a=a.pcm -x c++-module -c b.cpp
```

Causes the compilation of b.cpp to take longer than expected, especially if optimizations are turned on. Passing -ftime-trace shows that most of the non-optimizer time is spent in EvaluateAsInitializer on `aa`. If optimizations are turned on, it then spends a bunch of extra time compiling `module b` for optimizations, primarily SROAPass, but that is possibly just a duplicate of https://github.com/llvm/llvm-project/issues/60996

**Comment by davidstone** [comment]
In this example, if I declare `unsigned a()` as `constexpr unsigned a()` and thereby cause `aa` to have constant initialization, then in this example `module b` no longer spends time in `EvaluateAsInitializer`. However, the real program I reduced this from has a module that spends time on `EvaluateAsInitializer` even when the module contains nothing but imports, and the variable templates it is evaluating are all declared `constexpr`.

**Comment by ChuanqiXu9** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/af86957cbbffd3dfff3c6750ebddf118aebd0069.
