### ISSUE TITLE
update_cc_test_checks --function-signature --check-attributes ignores return type and attributes

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#61058]
The type and return attributes are ignored with {{[^@]+}}, so this is missing part of the story if you're trying to test ABI code:

```
// CFINITEONLY-LABEL: define {{[^@]+}}@defined_func_f32
// CFINITEONLY-SAME: (float noundef nofpclass(nan inf) [[A:%.*]], float noundef nofpclass(nan inf) [[B:%.*]], float noundef nofpclass(nan inf) [[C:%.*]]) #[[ATTR0:[0-9]+]] {
// CFINITEONLY-NEXT:  entry:
```

**Comment by nikic** [comment]
See https://reviews.llvm.org/D133943, https://reviews.llvm.org/D142373, https://reviews.llvm.org/D142473. Rebased patch: https://gist.github.com/nikic/6ecc3e9ab75bd2345c282b8d70b4dc10

**Comment by nikic** [comment]
I've put up the patch: https://reviews.llvm.org/D144963
