### ISSUE TITLE
Backport "Fix assertion failure in SMT conversion for unary operator on floats"

### ISSUE THREAD

**Issue by steakhal** [llvm/llvm-project#61097]
While rebasing our fork I observed that 3674421c4bc0cd3b65b8f1feaaf7038ac2d47ca8 is on `main` but missing from `release/16.x`.
I think we should backport this crash fix to clang-16.
WDYT @haoNoQ @Xazax-hun ?

**Comment by Xazax-hun** [comment]
Sounds good to me!

**Comment by steakhal** [comment]
@tstellar Could you please merge this?
