### ISSUE TITLE
[Flang] Implement MLIR RegionBranchOpInterface for `fir.if`

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#61091]
The RegionBranchOpInterface is used by some MLIR transformations. Implementing it for `fir.if` might provide some benefits (compile time or performance).

Note: This came up while implementing the StackArrays pass. https://reviews.llvm.org/D140415

**Comment by SachaBallantyne** [comment]
Implemented by https://github.com/llvm/llvm-project/commit/1b0ec3981c7eeecaf478997e7d94d4d0a8d7ad60
