### ISSUE TITLE
crash with RISC-V scalable vectorization and kernel address sanitizer

### ISSUE THREAD

**Issue by nathanchance** [llvm/llvm-project#61096]
Initially reported on LKML: https://lore.kernel.org/llvm/202302250924.ukv4ZxOc-lkp@intel.com/

After commit 15c645f7ee67 ("[RISCV] Enable (scalable) vectorization by default"), there is an assertion failure when `-fsanitize=kernel-address` is used. A trivial reproducer from `cvise`:

```c
int get_boot_config_from_initrd_size, __attribute__start_kernel_ret;
void __attribute__((__cold__)) __attribute__start_kernel() {
  char *p;
  while (get_boot_config_from_initrd_size--)
    __attribute__start_kernel_ret += *p++;
}
```

```console
$ clang --target=riscv64-linux-gnu -march=rv64imafdcv -O2 -fsanitize=kernel-address -c -o /dev/null main.i
warning: Invalid size request on a scalable vector; Cannot implicitly convert a scalable size to a fixed-width size in `TypeSize::operator ScalarTy()`
clang: /home/nathan/cbl/src/llvm-project/llvm/include/llvm/Support/Casting.h:578: decltype(auto) llvm::cast(From *) [To = llvm::FixedVectorType, From = llvm::Type]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang --target=riscv64-linux-gnu -march=rv64imafdcv -O2 -fsanitize=kernel-address -c -o /dev/null main.i
1.      <eof> parser at end of file
2.      Optimizer
 #0 0x0000aaaad8e30c28 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (../install/llvm-bad/bin/clang+0x4cd0c28)
 #1 0x0000aaaad8e2ee18 llvm::sys::RunSignalHandlers() (../install/llvm-bad/bin/clang+0x4ccee18)
 #2 0x0000aaaad8db2c6c (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) CrashRecoveryContext.cpp:0:0
 #3 0x0000aaaad8db2e1c CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #4 0x0000ffffabc8086c (linux-vdso.so.1+0x86c)
 #5 0x0000ffffab73da38 __pthread_kill_implementation (/lib64/libc.so.6+0x8da38)
 #6 0x0000ffffab6f4980 gsignal (/lib64/libc.so.6+0x44980)
 #7 0x0000ffffab6e0284 abort (/lib64/libc.so.6+0x30284)
 #8 0x0000ffffab6eda84 __assert_fail_base (/lib64/libc.so.6+0x3da84)
 #9 0x0000ffffab6edb00 __assert_perror_fail (/lib64/libc.so.6+0x3db00)
#10 0x0000aaaad8a2d77c (anonymous namespace)::AddressSanitizer::instrumentFunction(llvm::Function&, llvm::TargetLibraryInfo const*) AddressSanitizer.cpp:0:0
#11 0x0000aaaad8a29664 llvm::ModuleAddressSanitizerPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (../install/llvm-bad/bin/clang+0x48c9664)
#12 0x0000aaaad871d61c llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (../install/llvm-bad/bin/clang+0x45bd61c)
#13 0x0000aaaad95b0e24 (anonymous namespace)::EmitAssemblyHelper::RunOptimizationPipeline(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>&, std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile>>&) BackendUtil.cpp:0:0
#14 0x0000aaaad95aaba4 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>) (../install/llvm-bad/bin/clang+0x544aba4)
#15 0x0000aaaad99064ec clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) CodeGenAction.cpp:0:0
#16 0x0000aaaada0db138 clang::ParseAST(clang::Sema&, bool, bool) (../install/llvm-bad/bin/clang+0x5f7b138)
#17 0x0000aaaad984d810 clang::FrontendAction::Execute() (../install/llvm-bad/bin/clang+0x56ed810)
#18 0x0000aaaad97dac74 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (../install/llvm-bad/bin/clang+0x567ac74)
#19 0x0000aaaad990080c clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (../install/llvm-bad/bin/clang+0x57a080c)
#20 0x0000aaaad72ce060 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (../install/llvm-bad/bin/clang+0x316e060)
#21 0x0000aaaad72cc114 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#22 0x0000aaaad96b34bc void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::$_0>(long) Job.cpp:0:0
#23 0x0000aaaad8db2b14 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (../install/llvm-bad/bin/clang+0x4c52b14)
#24 0x0000aaaad96b2f7c clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (../install/llvm-bad/bin/clang+0x5552f7c)
#25 0x0000aaaad967f390 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (../install/llvm-bad/bin/clang+0x551f390)
#26 0x0000aaaad967f610 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (../install/llvm-bad/bin/clang+0x551f610)
#27 0x0000aaaad96945e0 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (../install/llvm-bad/bin/clang+0x55345e0)
#28 0x0000aaaad72cb7b0 clang_main(int, char**) (../install/llvm-bad/bin/clang+0x316b7b0)
#29 0x0000ffffab6e0598 __libc_start_call_main (/lib64/libc.so.6+0x30598)
#30 0x0000ffffab6e0670 __libc_start_main@GLIBC_2.17 (/lib64/libc.so.6+0x30670)
#31 0x0000aaaad72c90b0 _start (../install/llvm-bad/bin/clang+0x31690b0)
clang-16: error: clang frontend command failed with exit code 134 (use -v to see invocation)
ClangBuiltLinux clang version 16.0.0 (https://github.com/llvm/llvm-project 15c645f7ee678d85a7ec8db9a3b1a78b6548baba)
Target: riscv64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/nathan/tmp/cvise.tHJkfPN5TK/install/llvm-bad/bin
clang-16: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
```

I have been unable to reproduce this crash with just `opt` but my LLVM-fu is not too strong. I am not really sure whose bug this is so I am just putting it under the RISC-V label for now but please adjust it as necessary.

**Comment by kito-cheng** [comment]
And the work around is compile with `-fno-vectorize`.

**Comment by luismarques** [comment]
Please go ahead @kito-cheng, you're very welcome to take on that work. I'll try to test and review those patches.

**Comment by nickdesaulniers** [comment]
cc @preames @topperc

**Comment by ConchuOD** [comment]
> And the work around is compile with `-fno-vectorize`.

The solution in this particular case is not `-fno-vectorize`, it's "don't pass v in march to begin with"!
The patchset's attempt to remove v, fails when the C extension is present or CONFIG_FPU is disabled:
```
# ISA string setting
riscv-march-$(CONFIG_ARCH_RV32I)	:= rv32ima
riscv-march-$(CONFIG_ARCH_RV64I)	:= rv64ima
riscv-march-$(CONFIG_FPU)		:= $(riscv-march-y)fd
riscv-march-$(CONFIG_RISCV_ISA_C)	:= $(riscv-march-y)c
riscv-march-$(CONFIG_RISCV_ISA_V)	:= $(riscv-march-y)v

KBUILD_CFLAGS += -march=$(subst fdv,,$(riscv-march-y))
```
That randconfig has CONFIG_RISCV_ISA_C=y, so it's the former.
I don't think, unless the zstd makefile is doing something wacky, that this is something we need to work around in kernel land.

**Comment by nathanchance** [comment]
Okay, so that kernel is not supposed to pass `v` to `-march`, just like `fd`. It would still be nice for LLVM not to crash in that case but it sounds like this will be avoided once the kernel fixes removing `v` from `-march` altogether, without an additional workaround [like I suggested](https://lore.kernel.org/Y%2F+SoGfspjGwlH7g@dev-arch.thelio-3990X/).

**Comment by preames** [comment]
Here's a reduced reproducer.

$ opt -passes=asan ksan.ll -S
(CRASH AS ABOVE)
$ cat ksan.ll 
```
; ModuleID = 'ksan.c'
source_filename = "ksan.c"
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-unknown-linux-gnu"

define dso_local void @__attribute__start_kernel(ptr %p, <vscale x 2 x i1> %active.lane.mask) local_unnamed_addr sanitize_address {
entry:
  %wide.masked.load = tail call <vscale x 2 x i8> @llvm.masked.load.nxv2i8.p0(ptr %p, i32 1, <vscale x 2 x i1> %active.lane.mask, <vscale x 2 x i8> poison)
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: read)
declare <vscale x 2 x i8> @llvm.masked.load.nxv2i8.p0(ptr nocapture, i32 immarg, <vscale x 2 x i1>, <vscale x 2 x i8>)
```

As already mentioned, the problem appears to be that the asan instrumentation code assumes masked loads are fixed length vectors.  Should be an easy fix (for this specific issue).  @kito-cheng feel free to tag me as a reviewer.

**Comment by AndybnACT** [comment]
> > And the work around is compile with `-fno-vectorize`.
> 
> The solution in this particular case is not `-fno-vectorize`, it's "don't pass v in march to begin with"! The patchset's attempt to remove v fails when the C extension is present or CONFIG_FPU is disabled:
> 
> ```
> # ISA string setting
> riscv-march-$(CONFIG_ARCH_RV32I)	:= rv32ima
> riscv-march-$(CONFIG_ARCH_RV64I)	:= rv64ima
> riscv-march-$(CONFIG_FPU)		:= $(riscv-march-y)fd
> riscv-march-$(CONFIG_RISCV_ISA_C)	:= $(riscv-march-y)c
> riscv-march-$(CONFIG_RISCV_ISA_V)	:= $(riscv-march-y)v
> 
> KBUILD_CFLAGS += -march=$(subst fdv,,$(riscv-march-y))
> ```
> 
> That randconfig has CONFIG_RISCV_ISA_C=y, so it's the former. I don't think, unless the zstd makefile is doing something wacky, that this is something we need to work around in kernel land.

Yes, that was my mistake. V and auto-vec should not be enabled unless specially specified for now.

**Comment by preames** [comment]
@kito-cheng FYI, I ended up taking a look at this yesterday evening and expect to have a couple patches posted shortly.

**Comment by preames** [comment]
I've landed two preparatory changes (45b6a33b and 67dab19), one test coverage improvement (1fb6cc7e), and have one change on review: https://reviews.llvm.org/D145175

There will be a couple of changes required to get all of ASAN working with scalable vector types.

From a quick glance, it looks like HWSAN and TSAN need work too.  Haven't looked at the other instrumentation passes, but it wouldn't surprise me to learn those haven't been updated either.

**Comment by preames** [comment]
Patch for masked load and store is up: https://reviews.llvm.org/D145198

**Comment by preames** [comment]
Patch for load and store to scalable alloca is up: https://reviews.llvm.org/D145259

There's a few more patches needed for ASAN, and a bunch more for the other sanitizers.  I'm going to stop for the moment, and wait for these to make there way through review before proceeding.

**Comment by kito-cheng** [comment]
@preames I read the LLVM IR ref and collect all potential IR we might need to fix, want to see if you have plans or interested to fix those stuffs? or maybe our folks could pick up and doing the follow up works? 

LLVM IR:
load: D145175
store: D145175
alloca: D145259

VP familiy:
- ‘llvm.vp.load’ Intrinsic
- ‘llvm.vp.store’ Intrinsic
- ‘llvm.experimental.vp.strided.load’ Intrinsic
- ‘llvm.experimental.vp.strided.store’ Intrinsic
- ‘llvm.vp.gather’ Intrinsic
- ‘llvm.vp.scatter’ Intrinsic

Masked family
- ‘llvm.masked.gather.’ Intrinsics
- ‘llvm.masked.scatter.’ Intrinsics
- ‘llvm.masked.load.’ Intrinsics : D145198
- ‘llvm.masked.store.’ Intrinsics : D145198
- ‘llvm.masked.expandload.’ Intrinsics
- ‘llvm.masked.compressstore.’ Intrinsics

RISC-V vector intrinsic

**Comment by preames** [comment]
@kito-cheng None of the intrinsics you mention above have existing dedicated support for fixed length vectors.  (Unless I'm missing something?)  I am only focused on feature parity between scalable and fixed.  It does look like the instrumentation has a bunch of gaps, but as long as those gaps are equal for scalable and fixed, I'm not focusing on that.

**Comment by kito-cheng** [comment]
@preames Thanks for the response, just make sure we won't duplicate work on those stuffs :)

**Comment by nickdesaulniers** [comment]
What's the status of this issue?

**Comment by preames** [comment]
> What's the status of this issue?
To my knowledge, the original reported crash is fixed.  I picked off a number of the obvious (from code inspection) cases in the various sanitizer instrumentation passes and added support for scalable vectors.  I have not done any end to end testing of the sanitizers on a rv64gcv setup, and suspect there are other undiscovered problems.  

I'm going to close this issue as the reported problem is addressed.  If anyone has specific bug reports (with IR reproducers) I'm happy to investigate other sanitizer instrumentation issues as reported.
