### ISSUE TITLE
Helper libraries for unit testing

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#6110]
|  |  |
| --- | --- |
| Bugzilla Link | [5738](https://llvm.org/bz5738) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
We're starting to write a collection of functions and classes helpful for unit testing, but we don't have anywhere to put them. For example, http://llvm.org/viewvc/llvm-project/llvm/trunk/unittests/ExecutionEngine/JIT/JITTest.cpp?view=markup contains a RecordingJITMemoryManager class and a LoadAssembly(char*) helper function, both of which could be useful for other tests.

We probably want a couple different helper libraries with different dependencies so that the VMCore unit tests don't have to depend on the JIT.

I'd like someone who knows the build system to set up the Makefiles appropriately so that individual test writers like me can just add files/functions to the right places to share them.

**Comment by arsenm** [comment]
There are more unit tests now, and this is old and open ended
