### ISSUE TITLE
[MLIR]`-convert-spirv-to-llvm` failed to legalize operation 'spirv.Constant'

### ISSUE THREAD

**Issue by BealZephyr** [llvm/llvm-project#61109]
I encountered an error when using `-convert-spirv-to-llvm` pass.`%1` can be lowered, but failed to lower ` %cst`. 
How to deal with `spirv.Constant`  with !spirv.array<6 x i32>?

Test on commit: #[6740991](https://github.com/llvm/llvm-project/tree/67409911353323ca5edf2049ef0df54132fa1ca7)
Steps to reproduce:
```
mlir-opt test.mlir -convert-func-to-spirv -convert-spirv-to-llvm
```
Test case:
```
module {
  func.func @main() {
    %cst = spirv.Constant dense<[92, 46, 90, 96, 101, 50]> : tensor<6xi32> : !spirv.array<6 x i32>
    %1 = spirv.Constant false
    return
  }
}
```
Error message:
```
test.mlir:3:12: error: failed to legalize operation 'spirv.Constant' that was explicitly marked illegal
    %cst = spirv.Constant dense<[92, 46, 90, 96, 101, 50]> : tensor<6xi32> : !spirv.array<6 x i32>
           ^
test.mlir:3:12: note: see current operation: %0 = "spirv.Constant"() {value = dense<[92, 46, 90, 96, 101, 50]> : tensor<6xi32>} : () -> !spirv.array<6 x i32>
```

**Comment by EugeneZelenko** [comment]
@BealZephyr: Could you please elaborate?

**Comment by BealZephyr** [comment]
This issue is repeated with https://github.com/llvm/llvm-project/issues/60105

**Comment by EugeneZelenko** [comment]
@BealZephyr Thank you! I added relevant label.
