### ISSUE TITLE
[mlir] Generated interface definitions should respect their order in ODS

### ISSUE THREAD

**Issue by StrongerXi** [llvm/llvm-project#61102]
Given

```tablegen
// foo.td
include "mlir/IR/OpBase.td"

def XInterface : OpInterface<"XInterface"> {
}

def AInterface : OpInterface<"AInterface", [XInterface]> {
}
```

Run
```shell
mlir-tblgen -gen-op-interface-decls -I./llvm-project/mlir/include ./foo.td > foo.h
```

We get

```cpp
...

class AInterface;
namespace detail {
struct AInterfaceInterfaceTraits {
  struct Concept {
    /// The methods defined by the interface.
    /// The base classes of this interface.
    const XInterface::Concept *implXInterface = nullptr;
...

class XInterface;
```
The generated `.h` file won't compile because `AInterface`'s definition requires _complete definition_ of `XInterface`, yet the former appears before the latter.

**Comment by jpienaar** [comment]
These are indeed sorted today, I don't know if we actually can guarantee same order as in file (I tried looking the other day and it didn't seem like this was guaranteed by traversal in tblgen). But we could at least emit these in order as we know ordering requirement.

**Comment by StrongerXi** [comment]
> at least emit these in order as we know ordering requirement.

Agree (I assume by ordering requirement you mean things like the inheritance relationship here). It should suffice to resolve this issue. Otherwise it's a pretty surprising blocker for some uses of interface inheritance.

**Comment by jpienaar** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/5f036799f4d39c1aa5a6fac0e972050373e9fa78
