### ISSUE TITLE
missing parameter

### ISSUE THREAD

**Issue by kerravon86** [llvm/llvm-project#61112]
This looks like a compiler bug to me.

Function mystart takes 2 parameters. I can see the second parameter:

	movl	%eax, 4(%esp)

but I don't see the first parameter, which I expect to be inserted
at 0(%esp)

This is linstart.s:

_start:                                 # @_start
# %bb.0:
	pushl	%esi
	subl	$8, %esp
	leal	12(%esp), %eax
	movl	%eax, paul
	leal	16(%esp), %eax
	movl	%eax, 4(%esp)
	calll	__mystart
	movl	%eax, %esi
	movl	%eax, (%esp)
	calll	__exita
	movl	%esi, %eax
	addl	$8, %esp
	popl	%esi
	retl

mystart (in start.s) is expecting that first (missing) parameter:

__mystart:                              # @__mystart
# %bb.0:
	pushl	%ebp
	pushl	%ebx
	pushl	%edi
	pushl	%esi
	subl	$76, %esp
	movl	96(%esp), %esi

The offset 96 is correct:

	movl	96(%esp), %esi

(after the various stack manipulations, plus the return address)

The value in %esi is tested to make sure it is 1, and because it isn't, it freezes.

	cmpl	$1, %esi
	jne	.LBB0_8

.LBB0_8:
	movl	$.L.str, (%esp)
	calll	printf
	.p2align	4, 0x90
.LBB0_9:                                # =>This Inner Loop Header: Depth=1
	jmp	.LBB0_9

.L.str:
	.asciz	"argc is not 1 - freezing\n"

Here is the version information:

.ident "Android (7714059, based on r416183c1) clang version 12.0.8 (https://android.googlesource.com/toolchain/llvm-project c935d99d7cf2016289302412d708641d52d2f7ee)"

Being compiled with:

-c -O2 -fno-builtin -DUSE_MEMMGR -I . -m32 -fno-stack-protector
[clangprm.zip](https://github.com/llvm/llvm-project/files/10867702/clangprm.zip)

**Comment by kerravon86** [comment]
Oh, source code can also be found here:

https://sourceforge.net/p/pdos/gitcode/ci/master/tree/pdpclib/

**Comment by topperc** [comment]
I believe the address `*(int *)(&p - 1)` in this code is undefined behavior so it was optimized out.

`__mystart(*(int *)(&p - 1), &p)`

**Comment by kerravon86** [comment]
If it's going to do something as diabolical as drop a parameter, shouldn't it issue a warning? The code looks perfectly valid to me though. I just want it to inspect the stack as requested.

**Comment by topperc** [comment]
> If it's going to do something as diabolical as drop a parameter, shouldn't it issue a warning? The code looks perfectly valid to me though. I just want it to inspect the stack as requested.

Pointer arithmetic is only defined if the result is within the object it started from. Or the byte one past the end of the object.

**Comment by kerravon86** [comment]
Perhaps it is only well-defined in that case, otherwise it will be implementation-defined, and in the case of x86 there is something very obvious to do, which is the exact same thing that happens when the code is unoptimized and works. And again - if the optimizer wants to produce a very different result (total failure) compared to what unoptimized does, it should at least give a warning that "hey, thanks to you switching on optimizations we've done some extra checks, and you've entered undefined behavior, and our response to that is to leave the stack empty with uninitialized garbage, so good luck with that, ha ha ha".
