### ISSUE TITLE
Clang issue/question: call to func with variadic templates is ambiguous

### ISSUE THREAD

**Issue by samuelpmish** [llvm/llvm-project#61129]
Hi,

the following code fails to compile with clang:

```cpp
template < int ... dimensions >
struct tensor{};

template < int m, int n >
void foo(tensor< m >, tensor < m, n >);

template < int m, int n, int ... rest >
void foo(tensor< m >, tensor < m, n, rest ... >);

int main() {
    tensor< 2 > a;
    tensor< 2, 3 > b;

    // error: call to 'foo' is ambiguous
    // note: candidate function [with m = 2, n = 3]
    // void foo(tensor< m >, tensor < m, n >);
    //
    // note: candidate function [with m = 2, n = 3, rest = <>]
    // void foo(tensor< m >, tensor < m, n, rest ... >);
    foo(a, b);
}
```

I would have guessed that the first overload is preferable, so there would be no ambiguity. MSVC and gcc compile it without problems, with ties going to the non-variadic overload (https://godbolt.org/z/dTsv5q6Pq).

I don't know the precise wording of the standard on this, so it's unclear to me if this is an issue with clang, or an issue with MSVC and gcc, but I thought I'd post it here to find out more information.

**Comment by shafik** [comment]
It looks like this is fixed on clang trunk: https://godbolt.org/z/YssK7rzPK although I am not sure what commit fixed it CC @royjacobson
