### ISSUE TITLE
[DAG] SimplifySetCC - failure to simplify icmp(not(x),not(y)) -> icmp(y, x) patterns

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#61120]
https://godbolt.org/z/E4rjf9se4

This is handled in instcombine, but under certain circumstances they can appear in the DAG as well (noticed while trying to improve ABD expansion on x86).

We do get the EQ/NE cases indirectly via the fold: (X^Y) == (X^Z) --> Y == Z

**Comment by junaire** [comment]
Hi @RKSimon , I would like to work on this. I've created https://reviews.llvm.org/D146512.
