### ISSUE TITLE
UniformityAnalysis much slower than DivergenceAnalysis in some cases

### ISSUE THREAD

**Issue by jayfoad** [llvm/llvm-project#61123]
Test case: [r.txt](https://github.com/llvm/llvm-project/files/10873764/r.txt)

```shell
opt -passes="print<uniformity>" r.txt -o /dev/null -time-passes
```
shows that UniformityInfoAnalysis takes around 800 ms on my machine.

```shell
opt -passes="print<divergence>" r.txt -o /dev/null -time-passes
```
shows that DivergenceAnalysis takes around 0.1 ms.

**Comment by jayfoad** [comment]
@ssahasra @piotrAMD FYI

**Comment by ssahasra** [comment]
Fix available for upstream review:
https://reviews.llvm.org/D145216

**Comment by jayfoad** [comment]
Fixed by https://reviews.llvm.org/D145216
