### ISSUE TITLE
Strangely suboptimal code generation when summing variables set in branches

### ISSUE THREAD

**Issue by MC-DeltaT** [llvm/llvm-project#61137]
Consider this code:

```c++
unsigned func(unsigned i, unsigned f) {
    unsigned x = 0;
    unsigned y = 0;
    if (f == 0) {
        x = i;
    }
    else if (f == 1) {
        y = i;
    }
    return x + y;
}
```

Note that if `f <= 1`, the result is `i`, otherwise the result is 0.

Clang/LLVM generates the following machine code, which is strangely unoptimised:

```asm
func(unsigned int, unsigned int):
        test    esi, esi
        je      .LBB0_1
        xor     eax, eax
        cmp     esi, 1
        jne     .LBB0_3
        add     eax, edi
        ret
.LBB0_1:
        mov     eax, edi
        add     eax, esi
        ret
.LBB0_3:
        xor     edi, edi
        add     eax, edi
        ret
```

Demo here: https://godbolt.org/z/PdW1jo8vb

Two things that are suboptimal here:

- The `f==0` and `f==1` cases are handled separately, rather than noticing that the result is the same in both cases (GCC does this optimisation).
- All 3 `add` instructions add registers which are already guaranteed to be 0 (`eax`, `esi`, `edi`), which is rather odd.

This code is faster than GCC's if the condition on `f` is predictable, due to the use of branches rather than conditional moves, but still significantly slower than what I'd think is optimal:

```asm
    cmp   esi, 1
    ja    zero
    mov   eax, edi
    ret
zero:
    xor   eax, eax
    ret
```

Or the optimal code using conditional moves:

```asm
    xor     eax, eax
    cmp     esi, 1
    cmovbe  eax, edi
    ret
```

**Comment by luxufan** [comment]
I reduced to a small test as follows and I think the problem is instcombine doesn't fold `%x.0` and `%y.0` to a new phi node.
```
define dso_local i32 @func(i1 %c, i32 %i)  {
entry:
  br i1 %c, label %if.then2, label %if.end3
if.then2:                                         ; preds = %entry
  br label %if.end3

if.end3:                                          ; preds = %entry, %if.end3.fold.split, %if.then2
  %x.0 = phi i32 [ 0, %if.then2 ], [ %i, %entry ]
  %y.0 = phi i32 [ %i, %if.then2 ], [ 0, %entry ]
  %add = add i32 %y.0, %x.0
  ret i32 %add
}
```

**Comment by nikic** [comment]
Candidate patch: https://reviews.llvm.org/D145223
