### ISSUE TITLE
[Wasm] likely incorrect optimization of fp-int-fp conversion with fsz

### ISSUE THREAD

**Issue by malcom** [llvm/llvm-project#61130]
With `fno-signed-zeros` optimization enabled, the `fptosi/sitofp` and `fptoui/uitofp` roundtrip (fp-int-fp) is emitted as simple wasm `f64.trunc` instruction, even when a type with size less than f64 is used between conversions. This leads to unexpected results, always return orginal value without fraction part.

For example:
```llvm
define double @test(double %d) {
	%n = fptosi double %d to i32	; c: int n = (int)d;
	%o = sitofp i32 %n to double	; c: double o = (double)n;
	ret double %o
}
```

emits:
```wasm
test:
	.functype	test (f64) -> (f64)
	local.get	0
	f64.trunc
	end_function
```

return:
```
test(123.123)		// 123.0
test(9876543210.123)	// 9876543210.0
```

I would expect a value of `-2147483648.0`, as the standalone `ftopsi` operation return during overflow conversion on wasm (and other platforms) or at least some other value not exceeding 32 bits in this case.

I know, overflow in fp-int conversion is undefined behavior, so should this issue also be considered as UB or fsz optimization bug?

**Comment by efriedma-quic** [comment]
This is working as intended; "fptosi double 9876543210.123 to i32" produces poison.  If you don't want poison, use llvm.fptosi.sat.  (clang has an option -fno-strict-float-cast-overflow.)

**Comment by malcom** [comment]
A poison value is not a problem for me in this case ;)

I was curious about the strange for me emitting code with `trunc` on the wasm platform under certain circumstances. I didn't know about the 'fold fp-int-fp' optimization that was going on here, and why it only happens with 'fsz' enabled.

Looking at `foldFPToIntToFP` in `DAGCombiner` probably dispelled my doubts and gave me the answers.
