### ISSUE TITLE
clang/test/Interpreter/global-dtor.cpp fails on AArch64 since 6747fc07d1aa94e22622e278e5a02ba70675ac9b

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#61144]
With gcc-13.0.1, the clang/test/Interpreter/global-dtor.cpp has been failing on AArch64 ever since commit 6747fc07d1aa94e22622e278e5a02ba70675ac9b.  Older versions of gcc work fine, however.

See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108994

@lhames

**Comment by thesamesam** [comment]
Patch in review: https://reviews.llvm.org/D146067

**Comment by thesamesam** [comment]
Backport is being handled in https://github.com/llvm/llvm-project/issues/61423.
