### ISSUE TITLE
Clang omits call to move constructor with aggregate init from template type

### ISSUE THREAD

**Issue by danakj** [llvm/llvm-project#61145]
cc: @alanzhao1 

This code double frees with Clang, when it should not: https://godbolt.org/z/5sfT8sW4j

```cpp
#include <iostream>
#include <utility>

struct VecIter;

struct Vec {
    Vec() : i(new int[3]) {
        std::cerr << this << " Vec::Vec()\n";
        i[0] = 1;
        i[1] = 2;
        i[2] = 3;
    }
    Vec(Vec&& o) : i(o.i) {
        std::cerr << this << " Vec::Vec&&\n";
        o.i = nullptr;
    }
    Vec& operator=(Vec&& o) {
        std::cerr << this << " Vec::operator=&&\n";
        delete[] i;
        i = o.i;
        o.i = nullptr;
        return *this;
    }
    ~Vec() {
        std::cerr << this << " Vec::~Vec\n";
        delete[] i;
    }

    int* i;
};

struct S {
    static S make(auto&& vec) {
        Vec v;
        std::cerr << "Building Vec for S " << &v << "\n";
        v.i[0] = vec.i[0];
        v.i[1] = vec.i[1];
        v.i[2] = vec.i[2];
        std::cerr << "Construct S from Vec " << &v << "\n";
        // Clang bug:
        // The Vec::Vec(Vec&&) constructor is omitted here when constructing S
        // and S::vec.
        //
        // * This does not happen if the parameter is `Vec&&` instead of `auto&&`.
        // * It also does not happen if we uncomment the explicit constructor for S
        //   below.
        return S(std::move(v));
    }

    // Defining this constructor fixes the bug in S::make() and causes the Vec
    // move constructor to be called.
    // S(Vec vec) : vec(std::move(vec)) {}

    Vec vec;
};

int main() {
    auto s = S::make(Vec());
    std::cerr << s.vec.i[0] << "\n";
    std::cerr << s.vec.i[1] << "\n";
    std::cerr << s.vec.i[2] << "\n";
}
```

Output in GCC:
```
0x7ffe7c534788 Vec::Vec()
0x7ffe7c534758 Vec::Vec()
Building Vec for S 0x7ffe7c534758
Construct S from Vec 0x7ffe7c534758
0x7ffe7c534780 Vec::Vec&&
0x7ffe7c534758 Vec::~Vec
0x7ffe7c534788 Vec::~Vec
1
2
3
0x7ffe7c534780 Vec::~Vec
```

Output in Clang:
```
0x7ffe481779b0 Vec::Vec()
0x7ffe48177958 Vec::Vec()
Building Vec for S 0x7ffe48177958
Construct S from Vec 0x7ffe48177958
0x7ffe48177958 Vec::~Vec
0x7ffe481779b0 Vec::~Vec
0
0
493486096
0x7ffe481779b8 Vec::~Vec
free(): double free detected in tcache 2
```

Can't show the output of MSVC from godbolt but the code works there.

**Comment by danakj** [comment]
For what it's worth, in case it's helpful or not, I found this not with an `auto&&` parameter but with a `ConceptName auto&&` parameter. Though the use of a concept there is not important in causing the bug to occur, please keep it in mind in case it needs to be considered when fixing this.

**Comment by shafik** [comment]
Note if we change the move line to:

```cpp
  return S{std::move(v)};
```

Then gcc and clang match behavior: https://godbolt.org/z/4MeGTvv6E

This looks like a clang bug but not sure what is going wrong.

**Comment by danakj** [comment]
Any chance of this being fixed in Clang 16? Without it the guidance will likely have to be to avoid paren aggregate init, and write tooling to enforce it doesn't happen.

**Comment by shafik** [comment]
I believe the clang-16 window has closed, I am not really sure where to begin here or how far reaching the issue is. Maybe @zygoloid has an idea of where to poke this.

**Comment by zygoloid** [comment]
The broken ASTs here will also [crash the constant evaluator](https://godbolt.org/z/G88zerqnK) pretty easily.

**Comment by shafik** [comment]
I think that would be https://reviews.llvm.org/D129531 then

**Comment by AaronBallman** [comment]
> I've not been keeping up to date with the parenthesized aggregate init work, but it looks broken enough that I think we should disable it in the Clang 16 release.

Ugh, that's not good. :-( @tstellar @tru -- is it too late for 16.0.0? @zygoloid -- if it is too late for 16.0.0, would it be reasonable to revert in 16.0.1 instead (assuming we can't get the issues resolved in time for .0.1 or they're too large/risky for the dot release)?

**Comment by zygoloid** [comment]
> I think that would be https://reviews.llvm.org/D129531 then

FYI: that was reverted and relanded in https://reviews.llvm.org/D141546

That's a very big patch to revert right before a release, even if we have time. :(

**Comment by shafik** [comment]
So I reverted the patch locally but realized this code does not work w/ parens anymore, so it fixes the problem in a way but not very nicely since folks who now rely on this feature will be broken.

I don't have the bandwidth right now to dig into this too much more today.

**Comment by tstellar** [comment]
The 16.0.0 is planned for tomorrow, so I don't think we are going to be able to get this done in time especially if there isn't already a fix.  Can we document this issue in the release notes?

**Comment by alanzhao1** [comment]
So I took a naive stab at this per @zygoloid 's comments and I wrapped the `CXXParenListInitExpr` with a `CXXBindTemporaryExpr`

```
diff --git a/clang/lib/Sema/SemaInit.cpp b/clang/lib/Sema/SemaInit.cpp
index ddb2b5cf5cd1..908642e00058 100644
--- a/clang/lib/Sema/SemaInit.cpp
+++ b/clang/lib/Sema/SemaInit.cpp
@@ -9180,6 +9180,15 @@ ExprResult InitializationSequence::Perform(Sema &S,
                                         /*VerifyOnly=*/false, &CurInit);
       if (CurInit.get() && ResultType)
         *ResultType = CurInit.get()->getType();
+      if (shouldBindAsTemporary(Entity)) {
+        llvm::errs() << "should bind as temporary, dumping entity\n";
+        Entity.dump();
+        llvm::errs() << "should bind as temporary, dumping CurInit\n";
+        CurInit.get()->dump();
+        CurInit = S.MaybeBindToTemporary(CurInit.get());
+        llvm::errs() << "Dumping CurInit after bind to temporary\n";
+        CurInit.get()->dump();
+      }
       break;
     }
     }
```

I tried building the crashing example (https://godbolt.org/z/G88zerqnK) and we are indeed creating the `CXXBindTemporaryExpr`, but it looks like that's not sufficient to fix the crash:

```
should bind as temporary, dumping entity
Temporary 'S'
should bind as temporary, dumping CurInit
CXXParenListInitExpr 0x559f26228c00 'S':'struct S'
`-CXXConstructExpr 0x559f26228bd0 'Vec':'struct Vec' 'void (Vec &&)'
  `-CallExpr 0x559f26228ab0 'typename std::remove_reference<struct Vec &>::type':'struct Vec' xvalue
    |-ImplicitCastExpr 0x559f26228a98 'typename std::remove_reference<struct Vec &>::type &&(*)(struct Vec &) noexcept' <BuiltinFnToFnPtr>
    | `-DeclRefExpr 0x559f26228a08 '<builtin fn type>' Function 0x559f26228810 'move' 'typename std::remove_reference<struct Vec &>::type &&(struct Vec &) noexcept' (FunctionTemplate 0x559f24f58670 'move')
    `-DeclRefExpr 0x559f262280d8 'Vec':'struct Vec' lvalue Var 0x559f26227f18 'v' 'Vec':'struct Vec'
Dumping CurInit after bind to temporary
CXXBindTemporaryExpr 0x559f26228c68 'S':'struct S' (CXXTemporary 0x559f26228c68)
`-CXXParenListInitExpr 0x559f26228c00 'S':'struct S'
  `-CXXConstructExpr 0x559f26228bd0 'Vec':'struct Vec' 'void (Vec &&)'
    `-CallExpr 0x559f26228ab0 'typename std::remove_reference<struct Vec &>::type':'struct Vec' xvalue
      |-ImplicitCastExpr 0x559f26228a98 'typename std::remove_reference<struct Vec &>::type &&(*)(struct Vec &) noexcept' <BuiltinFnToFnPtr>
      | `-DeclRefExpr 0x559f26228a08 '<builtin fn type>' Function 0x559f26228810 'move' 'typename std::remove_reference<struct Vec &>::type &&(struct Vec &) noexcept' (FunctionTemplate 0x559f24f58670 'move')
      `-DeclRefExpr 0x559f262280d8 'Vec':'struct Vec' lvalue Var 0x559f26227f18 'v' 'Vec':'struct Vec'
clang++: /usr/local/google/home/ayzhao/src/llvm-project/clang/include/clang/AST/APValue.h:544: clang::APValue &clang::APValue::getStructField(unsigned int): Assertion `isStruct() && "Invalid accessor"' failed.

(followed by the same stacktrace from godbolt.)
```

**Comment by zygoloid** [comment]
There are two different bugs here; the constant evaluator crash is due to the template instantiation bug. You should be able to see whether the bind-to-temporary fix is effective by compiling `S(std::move(v));` outside of a template and checking whether `S`'s destructor gets called at the end of the statement.

**Comment by tru** [comment]
I will push 68b3396 to the release branch.

**Comment by danakj** [comment]
When there's a potential patch fix, I will be happy to try it against subspace, which is where I found this bug among others.

**Comment by alanzhao1** [comment]
I have a patch on my desktop that fixes this bug, but I still need to write tests for it. I'm looking to get a review out early next week. The general problem is that:

1. TreeTransform loses the `CXXConstructExpr` for both `CXXParenListInitExpr` and `InitListExpr`
2. Clang treats both as a cast because there's a single argument
3. For `InitListExpr`, Clang reperforms the `InitializationSequence` for its arguments, which regenerates the `CXXConstructExpr`, but for `CXXParenListInitExpr`, Clang as a functional-style cast and doesn't do anything with `InitializationSequence`, so its `CXXConstructExpr` is permanently lost.

It's also possible that this fix messes up the implementation of [p1975r0](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1975r0.html), which previously Just Works(TM), but I haven't tested that out yet.

**Comment by royjacobson** [comment]
It appears to still be in the release notes: https://releases.llvm.org/16.0.0/tools/clang/docs/ReleaseNotes.html

**Comment by alanzhao1** [comment]
Candidate patch: https://reviews.llvm.org/D146465

**Comment by danakj** [comment]
FWIW, I ran the candidate patch against Subspace tests with aggregate init re-enabled and no failures occurred. :)

**Comment by alanzhao1** [comment]
Now that I pushed https://github.com/llvm/llvm-project/commit/7df3c71b508b65284483225685f1ba19777f2bbb to `main`, do I have to cherry pick that change to another branch @royjacobson?

**Comment by H-G-Hristov** [comment]
Are P0960R3 and P1975R0 considered unsupported still?


Parenthesized initialization of aggregates | P0960R3 | No
-- | -- | --
Parenthesized initialization of aggregates | [P0960R3](https://wg21.link/p0960r3) |	No

https://clang.llvm.org/cxx_status.html

**Comment by alanzhao1** [comment]
@H-G-Hristov There is also #61567, but (I _think_) that isn't a miscomple and unlike this bug, that bug doesn't cause the compiler to crash. @AaronBallman any thoughts?

**Comment by AaronBallman** [comment]
> @H-G-Hristov There is also #61567, but (I _think_) that isn't a miscomple and unlike this bug, that bug doesn't cause the compiler to crash. @AaronBallman any thoughts?

I think these are distinct issues, yes.

**Comment by alanzhao1** [comment]
Sorry, I was unclear - my question was whether resolving this issue is sufficient to mark P0960R3 as supported in Clang 16.x, or do we still need to resolve #61567 before doing so?

**Comment by AaronBallman** [comment]
Oh, thank you for clarifying! :-) Hmm this is a tough one. #61567 is about false positive warning diagnostics, which is usually a matter of QoI and so not really something that would hold us back from claiming support for P0960R3. However, this bit worries me:

> This will affect uses of C++23 [std::ranges::elements_of](http://eel.is/c++draft/range.elementsof), which is an aggregate with a reference member that is intended to be used exactly like this.

largely because there's a significant number of users who compile with `-Werror` and I worry those folks will need to disable the warning more aggressively (and then forget to ever enable it again) in order to accept idiomatic code.  I think we want to be more conservative than we've been in the past with claiming support for features, so I think I'd err on the side of not claiming full support (but certainly we can change the `No` into `Partial` with a \<details\> tag). WDYT?

**Comment by timsong-cpp** [comment]
> Oh, thank you for clarifying! :-) Hmm this is a tough one. #61567 is about false positive warning diagnostics, which is usually a matter of QoI and so not really something that would hold us back from claiming support for P0960R3.

It's also about false positive errors, not just warnings.

**Comment by alanzhao1** [comment]
Agreed on holding off on claiming full support especially since I have a patch for #61567 (https://reviews.llvm.org/D148274)

**Comment by Peach1** [comment]
Template struct members don't get default initialized when using () parenthesis initialization.
Is a fix needed for this?:

```cpp
#include <iostream>

template <typename T>
struct Object
{
    T t;
    bool shouldBeTrue = true;
};

int main()
{
    std::cout << Object<int>(123).shouldBeTrue << std::endl; // 0, broken
    std::cout << Object<int>{123}.shouldBeTrue << std::endl; // 1, as expected
}
```

Example: https://godbolt.org/z/nbdxhcWMT

**Comment by alanzhao1** [comment]
@Peach1 that issue is tracked in #62266
