### ISSUE TITLE
[MLIR]Failed to materialize error on `-convert-tensor-to-spirv` pass

### ISSUE THREAD

**Issue by sweead** [llvm/llvm-project#61148]
Commit: https://github.com/llvm/llvm-project/commit/c2d6cc9ac41cf83833b3d995aa1bb3b17b8204ea

IR:
```mlir
//mlir-opt test.mlir -convert-tensor-to-spirv

module {
  func.func @main(%arg0: memref<4xi64>, %arg1: memref<92xi64>) {
    %c0 = arith.constant 0 : index
    %c96 = arith.constant 96 : index
    %c1 = arith.constant 1 : index
    %c0_i64 = arith.constant 0 : i64
    %0 = bufferization.to_tensor %arg1 : memref<92xi64>
    %1 = bufferization.to_tensor %arg0 : memref<4xi64>
    %2 = memref.alloc() {alignment = 128 : i64} : memref<96xi64>
    scf.for %arg2 = %c0 to %c96 step %c1 {
      memref.store %c0_i64, %2[%arg2] : memref<96xi64>
    }
    return
  }
}
```
Output:
```console
error: failed to materialize conversion for result #0 of operation 'arith.constant' that remained live after conversion
    %c0 = arith.constant 0 : index
          ^
test.mlir:5:11: note: see current operation: %1 = "arith.constant"() {value = 0 : index} : () -> index
test.mlir:12:5: note: see existing live user here:
"scf.for"(%1, %3, %5) ({
^bb0(%arg2: index):
  "memref.store"(%6, %9, %arg2) : (i64, memref<96xi64>, index) -> ()
  "scf.yield"() : () -> ()
}) : (index, index, index) -> ()
    scf.for %arg2 = %c0 to %c96 step %c1 {
    ^
```

**Comment by kuhar** [comment]
In this specific case the error happens inside the for loop which does not touch any of the tensors, so a more 'isolated' reproducer would help to tell if things are processed as expected or not.

I'm going to close his for now. Feel free to reopen with more details or file a new issue.

**Comment by joker-eph** [comment]
> In this specific case the error happens inside the for loop which does not touch any of the tensors

Why is the pass failing then? If the pass is about handling tensor shouldn't it leave the loop alone?

**Comment by kuhar** [comment]
> > In this specific case the error happens inside the for loop which does not touch any of the tensors
> 
> Why is the pass failing then? If the pass is about handling tensor shouldn't it leave the loop alone?

I'm not very familiar with tensor conversion specifically, but I think this is a manifestation of some scf lowering bug like https://github.com/llvm/llvm-project/issues/61107. Once I deal with those, I'll come back to this issue and see if it gets resolved.

Maybe @antiagainst has better intuition on what could be happening here?
