### ISSUE TITLE
Clang-format: QualifierAlignment moves const to wrong location

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#61189]
````
void f()
{
      NS::C const *p = &v;
}
````
becomes
````
void f()
{
      NS const ::C *p = &v;
}
````
instead of
````
void f()
{
      const NS::C *p = &v;
}
````

[reproduction.zip](https://github.com/llvm/llvm-project/files/10891555/reproduction.zip)

**Comment by JVApen** [comment]
Found on clang-format 16-rc2, after manual correction it stays stable.

**Comment by rymiel** [comment]
Duplicate of https://github.com/llvm/llvm-project/issues/60898
