### ISSUE TITLE
[LLD] C++20 Modules - unclosed quote

### ISSUE THREAD

**Issue by kassane** [llvm/llvm-project#61198]
As described in the title, it would be the error referring to trying to link using `ld.lld`, unlike other platforms.

This was a test with Zig (LLVM 15.0.7) toolchain.
https://gist.github.com/kassane/7e9a2da137e13eb6e1dbab726693bdb7

```console
$ zig c++ -std=c++20 -fmodules -fbuiltin-module-map -fmodules-ts -Xclang -emit-module-interface -c moduleTest.cpp -o moduleTest.pcm
LLD Link... ld.lld: error: /home/kassane/.cache/zig/o/ec639bf9d5e7c589c4e222dd65d28017/moduleTest.o:995: unclosed quote
```
Fix:

```console
$ cp $(zig c++ -std=c++20 -fmodules -fbuiltin-module-map -fmodules-ts -Xclang -emit-module-interface -c moduleTest.cpp -o moduleTest.pcm 2>&1 | grep "ld.lld: error" | sed 's/.*error: \(.*\):[0-9]\+.*/\1/g') moduleTest.pcm
```

**Comment by ChuanqiXu9** [comment]
I don't understand the problem fully. But `-fmodules -fbuiltin-module-map -fmodules-ts` is not needed for modules. Also it will be better to use `--precompile` than ` -Xclang -emit-module-interface`.

**Comment by kassane** [comment]
> -Xclang -emit-module-interface

Based on: https://releases.llvm.org/15.0.0/tools/clang/docs/StandardCPlusPlusModules.html#quick-start

```bash
# LLVM 15.0.6 (ubuntu 22.04)
$> clang++ -std=c++20 Hello.cppm --precompile -o Hello.pcm

Hello.cppm:2:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.

$> clang++ -std=c++20 Hello.cppm --precompile -o Hello.pcm -stdlib=libc++ # no issue

# zig v0.10.1 - LLVM 15.0.7
$> zig c++ -std=c++20 Hello.cppm --precompile -o Hello.pcm

LLD Link... ld.lld: error: Hello.cppm:1: unknown directive: module
>>> module;
>>> ^
```

**Comment by MaskRay** [comment]
This is an issue in Zig or the user. ld.lld recognizes several object file formats and treats others as linker scripts.
