### ISSUE TITLE
Demote --no-undefined-version to warning

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#61208]
LLVM 16 enabled `--no-undefined-version` by default in https://reviews.llvm.org/D135402. This caused wide-spread breakage, including in LLVM itself.

We should consider demoting this to a warning, at least for the LLVM 16 release. This will make people aware that there is an issue, without breaking builds.

**Comment by nikic** [comment]
@MaskRay Any thoughts on this? Would it make sense to make this a warning first, before making it a hard error?

**Comment by MaskRay** [comment]
We should quantify "wide-spread breakage". As I know Gentoo sees issues from ~10 packages: https://github.com/gentoo/gentoo/pull/29097 I have reported issues in their issue trackers or fixed the issue myself.

If the issue is using ld.lld with old versions of these packages, changing `error` to `warn` for just `release/16.x` is fine.
You can cherry pick https://github.com/MaskRay/llvm-project/tree/no-undefined-version into `release/16.x`.
There is no sufficient evidence to change the main branch decision, though.

**Comment by nikic** [comment]
> We should quantify "wide-spread breakage". As I know Gentoo sees issues from ~10 packages: [gentoo/gentoo#29097](https://github.com/gentoo/gentoo/pull/29097) I have reported issues in their issue trackers or fixed the issue myself.

Also breaks Rust on two different levels.
 
> If the issue is using ld.lld with old versions of these packages, changing `error` to `warn` for just `release/16.x` is fine. You can cherry pick https://github.com/MaskRay/llvm-project/tree/no-undefined-version into `release/16.x`. There is no sufficient evidence to change the main branch decision, though.

I think that's fine. The only problem is that this went directly to an error. If there is a warning cycle in between, it should be okay.

**Comment by haampie** [comment]
@MaskRay how are packages that conditionally export certain symbols supposed to deal with this nicely?

Typically `version.map` is declarative and defined ahead of time, and maybe it refers to symbols that are only added conditionally based on some configure script.

A generated `version.map` does not feel right, the declarative way is easier to manage.

Setting `-Wl,--no-undefined-version` feels too global.

**Comment by MaskRay** [comment]
> @MaskRay how are packages that conditionally export certain symbols supposed to deal with this nicely?
> 
> Typically `version.map` is declarative and defined ahead of time, and maybe it refers to symbols that are only added conditionally based on some configure script.
> 
> A generated `version.map` does not feel right, the declarative way is easier to manage.
> 
> Setting `-Wl,--undefined-version` feels too global.

@haampie
If different configurations in a project lead to different sets of defined versioned symbols, consider preprocessing a template that generates the version script like the following:

```
v1 {
  x;
#ifdef Y
  x;
#endif
#ifdef Z
  z;
#endif
};
```

If it doesn't want to deal with the complexity, specify `-Wl,--undefined-version`.
