### ISSUE TITLE
libc++ declval not rejected on all odr-uses

### ISSUE THREAD

**Issue by randomnetcat** [llvm/llvm-project#61202]
Clang 15.0.0 with libc++ fails to reject the following invalid program (https://godbolt.org/z/oW74s73Y3):
```cpp
#include <utility>

int main() {
    if (false) {
        int i = std::declval<int>();
    }
}
```

Per N4868 [declval]/2 (https://timsong-cpp.github.io/cppwp/n4868/declval#2):
> Mandates: This function is not odr-used.

The example program odr-uses `std::declval` and thus violates the Mandates clause, making it ill-formed.

**Comment by shafik** [comment]
I think this has to be handled on the libc++ side CC @mordante

**Comment by fsb4000** [comment]
Yes,  we did this for Microsoft STL: https://github.com/microsoft/STL/pull/2101

I think we should did the same for libc++.

**Comment by fsb4000** [comment]
I've created https://reviews.llvm.org/D145376
