### ISSUE TITLE
Investigate the possiblity of using CMake alias libraries when creating entrypoint aliases

### ISSUE THREAD

**Issue by sivachandra** [llvm/llvm-project#61222]
CMake has the ability to add alias libraries: https://cmake.org/cmake/help/latest/command/add_library.html#alias-libraries. libc's CMake infrastructure has its own alias implementation. This issue is about:

1. Investigate if libc's alias infrastructure can be replaced by CMake's alias libraries.
2. If it is possible, then actually do it.

**Comment by michaelrj-google** [comment]
Closing as out of date.
