### ISSUE TITLE
[IR] IRBuilderBase::CreateBinaryIntrinsic - attempt constant folding

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#61240]
c411965820eb803dd7eac39f80357cad663b7ba0 has to handle constant folding of many common intrinsics because `IRBuilderBase` doesn't currently handle it:

`Intrinsic::smax`
`Intrinsic::smin`
`Intrinsic::umax`
`Intrinsic::umin`
`Intrinsic::maxnum`
`Intrinsic::minnum`

Can we add a suitable `IRBuilderFolder::FoldBinaryIntrinsics` function?

**Comment by agentcooper** [comment]
@RKSimon @fhahn I'm attempting to do this in https://github.com/llvm/llvm-project/pull/80743 and need some guidance. Could you please take a look and say if the general direction is right? I've left a few TODOs in the PR as well.

**Comment by RKSimon** [comment]
Reopening as SLP still can't make use of constant folding builders
