### ISSUE TITLE
[clang][ExtractAPI] --extract-api-ignores=<value> should allow multiple files

### ISSUE THREAD

**Issue by daniel-grumberg** [llvm/llvm-project#61242]
Today `clang -extract-api` supports providing a new line separated file containing symbol names to ignore in the output by using the flag`--extract-api-ignores=<file-path>`. We should allow users to specify multiple such files.

**Comment by TheInferentialImp** [comment]
Could be implemented as such:

`
#include <iostream>
#include <fstream>
#include <vector>
#include <string>

int main(int argc, char* argv[]) {
    std::vector<std::string> ignore_files;

    // Parse command line arguments
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg.substr(0, 20) == "--extract-api-ignores=") {
            ignore_files.push_back(arg.substr(20));
        }
    }

    // Read ignore files
    std::vector<std::string> ignored_symbols;
    for (const auto& file : ignore_files) {
        std::ifstream input(file);
        if (input) {
            std::string line;
            while (std::getline(input, line)) {
                ignored_symbols.push_back(line);
            }
        } else {
            std::cerr << "Error: failed to open ignore file " << file << std::endl;
        }
    }

    // Print ignored symbols
    std::cout << "Ignored symbols:" << std::endl;
    for (const auto& symbol : ignored_symbols) {
        std::cout << "  " << symbol << std::endl;
    }

    return 0;
}
`

**Comment by daniel-grumberg** [comment]
Hi @Himanshiii-14, someone else is already working on this but feel free to email me at dgrumberg@apple.com to discuss more opportunities to contribute.
