### ISSUE TITLE
clang 15.0.7 (and 16) armv7 code generation error that later stopped build of gcc12 (or 13) from making progress

### ISSUE THREAD

**Issue by markmi** [llvm/llvm-project#61255]
The problem that I report here was first discovered on FreeBSD but I report based on replication on openSUSE Tumbleweed, Linux being the common/familiar context for most folks. I only tested the small reproducer on Armv7 Linux, not the original problem.

I show the small reproducer and its output but the original issue was build failures for a non-bootstrap build of FreeBSD's lang/gcc12 [I put back the actual FreeBSD port name, which is case sensitive and has the "12" as part of the name, no spaces] (and 13) port in/for an Armv7 context. (I did not try anything older.) The reproducer is a minor change to part of the GCC source code, making the code extracted simpler for the purpose.

In the output shown later from the test program, the 2nd hexadecimal number (0x prefix) in each numbered line should be the same as the first hexadecimal number (0x prefix) in the line but usually is not. In the GCC build context, this produced a violation of invariants and unbounded looping in GCC at one stage of the build, blocking later stages from happening. 

(FYI: On/for AMD64 and AArch64 no failure was observed in the reproducer or in building lang/gcc12 [again: I put back the actual FreeBSD port name] [or 13] . So: Armv7 specific of the 3.)

I show the source code for the reproducer last.

```console
# uname -ap
Linux localhost.localdomain 6.2.0-1-lpae #1 SMP Mon Feb 20 06:22:59 UTC 2023 (89e2785) armv7l armv7l armv7l GNU/Linux

# clang-15 -v
clang version 15.0.7
Target: armv7hl-suse-linux-gnueabihf
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/armv7hl-suse-linux-gnueabi/12
Selected GCC installation: /usr/bin/../lib/gcc/armv7hl-suse-linux-gnueabi/12
Candidate multilib: .;@m32
Selected multilib: .;@m32
```

(Note: on FreeBSD both Clang 15 and 16 get the problem for Armv7. I only tested 15 on openSUSE.)

```console
# clang-15 -g -O2 partition.c ; ./a.out
0: 0x498044 : next?: 0x498044
1: 0x498050 : next?: 0x498044
2: 0x49805c : next?: 0x498044
3: 0x498068 : next?: 0x498044
4: 0x498074 : next?: 0x498074
5: 0x498080 : next?: 0x498074
6: 0x49808c : next?: 0x498074
7: 0x498098 : next?: 0x498074
8: 0x4980a4 : next?: 0x4980a4
9: 0x4980b0 : next?: 0x4980a4
10: 0x4980bc : next?: 0x4980a4
11: 0x4980c8 : next?: 0x4980a4
12: 0x4980d4 : next?: 0x4980d4
13: 0x4980e0 : next?: 0x4980d4
14: 0x4980ec : next?: 0x4980d4
15: 0x4980f8 : next?: 0x4980d4
16: 0x498104 : next?: 0x498104
17: 0x498110 : next?: 0x498104
18: 0x49811c : next?: 0x498104
19: 0x498128 : next?: 0x498104
20: 0x498134 : next?: 0x498134
21: 0x498140 : next?: 0x498134
22: 0x49814c : next?: 0x498134
23: 0x498158 : next?: 0x498134
24: 0x498164 : next?: 0x498164
25: 0x498170 : next?: 0x498164
26: 0x49817c : next?: 0x498164
27: 0x498188 : next?: 0x498164
28: 0x498194 : next?: 0x498194
29: 0x4981a0 : next?: 0x498194
30: 0x4981ac : next?: 0x498194
31: 0x4981b8 : next?: 0x498194
```

(On FreeBSD only `-O2` style builds got the failure. The `-g` use vs. not did not matter. I did not test such variations on openSUSE.)

The comments in the source code for the reproducer suggest how to run the test (in a FreeBSD context). The reproducer source code is:

```c
// Minor variation of part of some GCC source code!

// For system-clang 15: cc      -g -O2 partition.c ; ./a.out
// For devel/llvm16:    clang16 -g -O2 partition.c ; ./a.out

#include <stdio.h>

#define NUM_ELEMENTS 32

struct partition_elem
{
  struct partition_elem* next;
  int class_element;
  unsigned class_count;
};

typedef struct partition_def
{
  int num_elements;
  struct partition_elem elements[NUM_ELEMENTS];
} *partition;

struct partition_def partition_storage;

partition
partition_new (int num_elements)
{
  int e;

  if (NUM_ELEMENTS < num_elements) num_elements = NUM_ELEMENTS;

  partition part= &partition_storage;
  part->num_elements = num_elements;
  for (e = 0; e < num_elements; ++e)
    {
      part->elements[e].class_element = e;
      part->elements[e].next = &(part->elements[e]);
      part->elements[e].class_count = 1;
    }

  for (e = 0; e < num_elements; ++e)
      printf("%d: %p : next?: %p\n",e,(void*)&part->elements[e],(void*)part->elements[e].next);

  return part;
}

int main(void)
{
    partition part;
    part= partition_new(NUM_ELEMENTS);

    return !part;
}
```

**Comment by markmi** [comment]
Now that FreeBSD build server(s) for building packages from ports for FreeBSD 14-CURRENT have switched to vintages of materials that use clang15, at least the following port builds get stuck on Armv7:

```console
3 | gcc11-11.3.0_7 | lang/gcc11 | build/runaway | 32 | runaway_process | 03:00:43
4 | gcc12-12.2.0_5 | lang/gcc12 | build/runaway | 1608 | runaway_process | 03:00:45
5 | gcc11-devel-11.3.1.s20230224 | lang/gcc11-devel | build/runaway | 0 | runaway_process | 03:00:41
6 | gcc12-devel-12.2.1.s20230225 | lang/gcc12-devel | build/runaway | 0 | runaway_process | 03:00:45
7 | gcc13-devel-13.0.1.s20230226 | lang/gcc13-devel | build/runaway | 0 | runaway_process | 03:12:45
11 | avr-gcc-11.2.0 | devel/avr-gcc | build/runaway | 9 | runaway_process | 02:48:56
26 | aarch64-none-elf-gcc-11.3.0 | devel/aarch64-none-elf-gcc | build/runaway | 27 | runaway_process | 02:36:44
39 | arm-none-eabi-gcc-11.3.0 | devel/arm-none-eabi-gcc | build/runaway | 34 | runaway_process | 02:36:42
84 | riscv64-none-elf-gcc-11.3.0 | devel/riscv64-none-elf-gcc | build/runaway | 3 | runaway_process | 02:24:42
165 | riscv32-unknown-elf-gcc-11.3.0 | devel/riscv32-unknown-elf-gcc | build/runaway | 0 | runaway_process | 02:24:43
372 | gcc-msp430-ti-toolchain-9.3.1.2.20210722 | devel/gcc-msp430-ti-toolchain | build/runaway | 0 | runaway_process | 02:37:02
```

**Comment by VoxSciurorum** [comment]
On FreeBSD 13 the test program works if compiled
```
clang16 -O2 61255.c -target armv7-portbld-freebsd13.2
```
and fails if compiled with
```
clang16 -O2 61255.c -target armv7-portbld-freebsd13.2-gnueabihf
```

**Comment by VoxSciurorum** [comment]
The bug is apparently in LoopVectorizePass.  The loop has two induction variables, an incrementing pointer and an incrementing integer.  Only one of them is handled correctly.

The test program initializes a structure whose first field, `next`, points to the structure itself.  When compiled with loop vectorization (-O2) and hardware floating point the field is initialized incorrectly.  Runs of four structures all share a common `next` field.  This error is introduced in LoopVectorizePass.

Here is the loop initializing the array, with my comment added after semicolon:
```
.LBB1_1:                                @ =>This Inner Loop Header: Depth=1
        add     r2, r0, r1 
        add     r1, r1, #48
        cmp     r1, #388
        vdup.32 q8, r2       ; d16 and d17 get the same value here
        vadd.i32        q13, q9, q12
        vst3.32 {d16, d18, d20}, [r2]!
        vst3.32 {d17, d19, d21}, [r2]
        vorr    q9, q13, q13
        bne     .LBB1_1 
```
Register r2 holds the base address of the block of four three word structures.  That pointer is broadcast into the four words of q8.  Register q8 is stored using the alias d16/d17.  So four copies of the same pointer are stored, consistent with observed behavior.

In the last pass before LoopVectorizePass the store to the pointer field has the expected form
```
  store ptr %1, ptr %1, align 4, !tbaa !18
```
which can not help but initialize each structure to point to itself

After LoopVectorizePass the block looks like:
```
vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i32 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %vec.ind = phi <4 x i32> [ <i32 0, i32 1, i32 2, i32 3>, %vector.ph ], [ %vec.ind.next, %vector.body ]
  %1 = add i32 %index, 0
  %2 = getelementptr inbounds %struct.partition_def, ptr @partition_storage, i32 0, i32 1, i32 %1
  %broadcast.splatinsert = insertelement <4 x ptr> poison, ptr %2, i64 0
  %broadcast.splat = shufflevector <4 x ptr> %broadcast.splatinsert, <4 x ptr> poison, <4 x i32> zeroinitializer
  %3 = getelementptr inbounds %struct.partition_def, ptr @partition_storage, i32 0, i32 1, i32 %1, i32 2
  %4 = getelementptr inbounds i32, ptr %3, i32 -2
  %5 = ptrtoint <4 x ptr> %broadcast.splat to <4 x i32>
  %6 = shufflevector <4 x i32> %5, <4 x i32> %vec.ind, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %7 = shufflevector <8 x i32> %6, <8 x i32> <i32 1, i32 1, i32 1, i32 1, i32 undef, i32 undef, i32 undef, i32 undef>, <12 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11>
  %interleaved.vec = shufflevector <12 x i32> %7, <12 x i32> poison, <12 x i32> <i32 0, i32 4, i32 8, i32 1, i32 5, i32 9, i32 2, i32 6, i32 10, i32 3, i32 7, i32 11>
  store <12 x i32> %interleaved.vec, ptr %4, align 4, !tbaa !10
  %index.next = add nuw i32 %index, 4
  %vec.ind.next = add <4 x i32> %vec.ind, <i32 4, i32 4, i32 4, i32 4>
  %8 = icmp eq i32 %index.next, 32
  br i1 %8, label %middle.block, label %vector.body, !llvm.loop !22
```
Value `%broadcast.splat` contains four copies of the pointer.  Value `%5` is the same bits treated as integers.  Values `%6`, `%7`, and `%interleaved.vec` propgate those bits without changing them.

Value `%vec.ind` holds the incrementing integer, which is handled correctly.

Note that due to inlining there are two very similar copies of the initialization loop.

**Comment by nikic** [comment]
cc @fhahn Store pointer to itself being miscompiled sounds very familiar. I think something like this got fixed but maybe not on the release branch, or maybe this is a different case.

**Comment by VoxSciurorum** [comment]
> Store pointer to itself being miscompiled sounds very familiar. I think something like this got fixed but maybe not on the release branch, or maybe this is a different case.

The problem is still present in the main branch.

I attached an IR file to run the loop-vectorize pass on.  If the output contains a broadcast of a pointer value the bug is present.

```
  %10 = getelementptr inbounds [32 x %struct.partition_elem], ptr %9, i32 0, i32 %8
  %broadcast.splatinsert = insertelement <4 x ptr> poison, ptr %10, i64 0
  %broadcast.splat = shufflevector <4 x ptr> %broadcast.splatinsert, <4 x ptr> poison, <4 x i32> zeroinitializer
```

[61255-prevec.txt](https://github.com/llvm/llvm-project/files/11735522/61255-prevec.txt)

**Comment by nikic** [comment]
I think https://github.com/llvm/llvm-project/issues/61396 was the issue.

**Comment by markmi** [comment]
> @fhahn You are right, this is fixed in main. What I thought was my main build was in fact release/16.x. What is the fix? Even though 15.x is old from LLVM's point of view it is current in FreeBSD and the change might be worth incorporating into FreeBSD.

And when FreeBSD updates to 16.0.5 the same point will apply there.

**Comment by VoxSciurorum** [comment]
> I think #61396 was the issue.

It was.  The same fix works in llvm 15 and 16.  Can it be backported to release/16.x?

**Comment by nikic** [comment]
/cherry-pick 565b98e793422efbffaa2928f03bc943a1346a3e a4bb0374189a4121508beebf1cfb59875ece45cd 962c306a11d0a21c884c12e18825b8a41ba1bd7d

**Comment by nikic** [comment]
Submitting the cherry-pick just in case. I'm not sure if @tstellar will be able to pick it up, as the final 16.x release is today, and it's only supposed to fix a regression from the last one.

For context, this fixes a miscompile that apparently has some non-trivial real-world impact.
