### ISSUE TITLE
"lifetime extension of temporary created by aggregate initialization" diagnostic is weirdly apologetic

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#61256]
See: https://godbolt.org/z/xKW4EP7zP

The full text of this diagnostic is:

"sorry, lifetime extension of temporary created by aggregate initialization using default member initializer is not supported; lifetime of temporary will end at the end of the full-expression [-Wdangling]"

Why the "sorry"? This sounds weird and is not in line with other diagnostics.

I think this can be improved by simply rewording the diagnostic.

**Comment by shafik** [comment]
Minimal code, I think:

```cpp
struct A { int &&r = 0; };
struct B { A x, y; };
B b = {}; 
```

@tbaederr I think it is better to include a minmal inline code example, godbolt can go down (although rare)

**Comment by junaire** [comment]
It's not the only place, Clang seems very polite...
```
include/clang/Basic/DiagnosticCommonKinds.td:  "sorry, unsupported: file '%0' is too large for Clang to process">;
include/clang/Basic/DiagnosticCommonKinds.td:  "sorry, this include generates a translation unit too large for"
include/clang/Basic/DiagnosticSemaKinds.td:  "sorry, non-type template argument of type %0 is not yet supported">;
include/clang/Basic/DiagnosticSemaKinds.td:  "sorry, non-type template argument of pointer-to-member type %1 that refers "
include/clang/Basic/DiagnosticSemaKinds.td:  "sorry, lifetime extension of "
lib/Sema/SemaDeclAttr.cpp:    // to insert Decl at TU scope, sorry.
test/CXX/drs/dr16xx.cpp:    // expected-warning-re@-4 {{sorry, lifetime extension {{.*}} not supported}}
test/Lexer/SourceLocationsOverflow.c:// CHECK-NEXT: inc1.h{{.*}}: fatal error: sorry, this include generates a translation unit too large for Clang to process.
test/SemaTemplate/temp_arg_nontype_cxx1z.cpp:    void type_affects_identity(B<(int Y::*)&X::n>) {} // FIXME: expected-error {{sorry}}
test/SemaTemplate/temp_arg_nontype_cxx1z.cpp:    void type_affects_identity(B<(const int Y::*)&X::n>) {} // FIXME: expected-error {{sorry}}
test/SemaTemplate/temp_arg_nontype_cxx20.cpp:using F1 = Float<1.0f>; // FIXME expected-error {{sorry}}
test/SemaTemplate/temp_arg_nontype_cxx20.cpp:using F1 = Float<2.0f / 2>; // FIXME expected-error {{sorry}}
test/SemaTemplate/temp_arg_nontype_cxx20.cpp:using CI = ComplexInt<1 + 3i>; // FIXME: expected-error {{sorry}}
test/SemaTemplate/temp_arg_nontype_cxx20.cpp:using CI = ComplexInt<1 + 3i>; // FIXME: expected-error {{sorry}}
test/SemaTemplate/temp_arg_nontype_cxx20.cpp:using CF = ComplexFloat<1.0f + 3.0fi>; // FIXME: expected-error {{sorry}}
test/SemaTemplate/temp_arg_nontype_cxx20.cpp:using CF = ComplexFloat<1.0f + 3.0fi>; // FIXME: expected-error {{sorry}}
```

**Comment by s-pratik** [comment]
Hello, I Would Like to take this just I wanted to know that, is just I have to replace the word "Sorry". Do I understand the issue correctly?

**Comment by timsong-cpp** [comment]
Presumably the "sorry" is because the standard says that this _is_ lifetime-extended, and clang doesn't implement what the standard says?

**Comment by xgupta** [comment]
Pasting the link to patch - https://reviews.llvm.org/D146041.

**Comment by pav-code** [comment]
I saw this has been opened for a while so I figured no one was actively working on it!

I scanned through the files in `clang/include/clang/Basic/Diagnostic*Kinds.td` removing the 'sorries'. I hope I fixed all the tests associated (I ran `check-clang`). 

Please let me know if there are other things to do.

**Comment by tbaederr** [comment]
This was fixed by https://github.com/justinfargnoli/llvm-project/commit/40659cac6481bcceee791ea03eb5823c6e2afada
