### ISSUE TITLE
driver does not support f03 file extension

### ISSUE THREAD

**Issue by clementval** [llvm/llvm-project#61260]
Using a file with the *.f03 extension will trigger an error. The gfortran test-suite uses various file extension.

```
file format not recognized; treating as linker script
```

**Comment by banach-space** [comment]
Weird, that suffix has been there for quite a while: https://github.com/llvm/llvm-project/blob/7a078b65fb880eb97bb47a26e938cdbd23531688/flang/lib/Frontend/FrontendOptions.cpp#L29

Anyway, happy to help with this if there's a volunteer :)

**Comment by sunshaoce** [comment]
I submitted a patch to fix this: https://reviews.llvm.org/D145845
