### ISSUE TITLE
clang-format doesn't understand forwarding refs in C++20 lambda syntax 

### ISSUE THREAD

**Issue by usx95** [llvm/llvm-project#61269]
Your suggested formatting:
```cpp
  [&]<typename Callable>(Callable&& callable)
    requires std::is_invocable_v<Callable>
  {
    static_cast<void>(callable);
  };
```

clang-format's current output:
```cpp
  [&]<typename Callable>(Callable && callable)
    requires std::is_invocable_v<Callable>
  {
    static_cast<void>(callable);
  };
```

clang-format doesn't seem to understand that `Callable` in the expression above is a templated type, so the `&&` should group with `Callable` and be formatted in the usual manner for forwarding or rvalue references. Instead it seems to think that `&&` is a boolean operator and `Callable` is an operand.

**Comment by usx95** [comment]
CC: @HazardyKnusperkeks from clang format contributors for C++20 constructs.

**Comment by rymiel** [comment]
Annotator patch: https://reviews.llvm.org/D145642
