### ISSUE TITLE
WRONG code: likely instcombine of multiple i1:s.

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#61268]
This program should print 0:

```c
int printf(const char *, ...);
long a = 0, d = -1L, h = 0;
char b = 0, c = 0;
unsigned char g = 0;
int ****e = 0;
int *****f = &e;
int main() {
  long i = 0;
  for (g = 4; g; g++) {
    c = 0 >= a;
     //  -1      int64_max                        1          0 
    i = d > (9223372036854775807 - c) ? : (d + c);
    if (i) {
      char *j = &b;
      //  0                      int64_max         -1
      h = a > 9223372036854775807 - d; // OF 
      *j = h;
      *f = 0;
    }
  }
  printf("%d\n", b);
}
```

I think this program is well defined, as `i` will always be 0, and the overflowing subtract in the inner clause will never happen. 

```console
$ clang -O0 -march=z13 wrong0.i -o a.out ; ./a.out
0
$ clang -O1 -march=z13 wrong0.i -o a.out ; ./a.out
1
```

I have found this transformation by InstCombine which I think look suspicious:

```ll
for.body:                                         ; preds = %for.cond  
  %1 = load i64, ptr @a, align 8, !tbaa !7
  %cmp = icmp sge i64 0, %1
  %C = zext i1 %cmp to i32
  %D = load i64, ptr @d, align 8, !tbaa !7
  %MAX_min_C = sub nuw nsw i64 9223372036854775807, %C
  %CC_DGT = icmp sgt i64 %D, %MAX_min_C
  %BOOL_DGT = zext i32 %CC_DGT to i64
  %add = add nsw i64 %D, %C
  %cond = select i1 %CC_DGT, i64 %BOOL_DGT, i64 %add
  %tobool7 = icmp ne i64 %cond, 0
  br i1 %tobool7, label %enter, label %for.inc

*** IR Dump After InstCombinePass on main ***

for.body:                                         ; preds = %for.cond  
  %A = load i64, ptr @a, align 8, !tbaa !7
  %C_CC = icmp slt i64 %A, 1
  %D = load i64, ptr @d, align 8, !tbaa !7
  %C_BOOL = sext i1 %C_CC to i64
  %D_NE_MAX = icmp ne i64 %D, 9223372036854775807
  %NOT_C = xor i1 %C_CC, true
  %NOT_C_or_D_NE_MAX = select i1 %NOT_C, i1 true, i1 %D_NE_MAX
  %D_EQ_C = icmp eq i64 %D, %C_BOOL
  %tobool = select i1 %NOT_C_or_D_NE_MAX, i1 %D_EQ_C, i1 false
  br i1 %tobool, label %for.inc, label %enter
```

Before instcombine, it all makes sense, but then it seems that something has gone wrong: `%tobool` will be false (`d` is not equal to `c`), and as the branch targets have been swapped, the inner clause will now be entered, which is wrong.

I bisected this to b751da4 (HEAD, refs/bisect/bad) "[InstCombine] Handle integer extension in `select` patterns using the condition as value", which might be related as it indeed changes InstCombine.

**Comment by nikic** [comment]
Alive says the transform is correct: https://alive2.llvm.org/ce/z/5SPBfr Note that `%C_BOOL` is sexted, so it will be -1, not 1.

The final IR also looks correct to me. The s390x IR does not differ materially. As such, this looks like an s390x backend bug.

**Comment by JonPsson** [comment]
> Note that %C_BOOL is sexted, so it will be -1, not 1.

Ah, I missed that... I will take a look again then in the back end.

**Comment by JonPsson** [comment]
The program has a well defined behavior in that it has a single correct result, but it also has a signed subtraction that overflows in a non-executed block (given the initial values at least). This subtraction has been hoisted out into the entry block even though the branching doesn't depend on it in the isel input.

However, during isel lowering, the SystemZ method adjustForSubtraction() finds this subtraction and decides to base the comparison on that instead (the NSW flag is not checked for). 

I guess this is a matter of whether it's ok to propagate this UB in the CFG so that this program alters it's output after optimizations. Given that the values in this test case are global, they could be considered alterable so there is no real guarantee that the inner clause is not executed. So I guess if there is an overflowing signed computation somewhere in the program it cannot be guaranteed to be well defined even in cases like this where it might seem like it..?

**Comment by JonPsson** [comment]
Well, the SystemZ backend decides to instead of doing the comparison D != MAX (which never overflows), it reuses an existing MAX - D (which has NSW set), which in this case overflows. Is this acceptable or is it wrong to risk changing the dynamic execution path like this?

**Comment by uweigand** [comment]
I think the argument behind that back-end transform is that *in terms of SystemZ ISA semantics*, our subtract instruction returns a four-valued condition code: 0 if result zero, 1 if result < 0, 2 if result > 0, 3 if overflow happened.

Therefore, it is under every circumstance correct to transform a test "A == B" to "subtract(A, B) sets CC 0" at the ISA level.

However, I'm now no longer sure it is correct to make that transformation on the DAG level already.  It certainly seems incorrect to replace a "A == B" with a "(sub nsw A, B) == 0" at the DAG level, as we cannot guarantee that no overflow happens.  Transforming the comparison to a sub *without* nsw (or nuw) should still be good.

This might cause us to miss some optimization opportunities - this would need to be evaluated.  If this is significant, maybe we can compensate by a later optimization at the MI level that does the equivalent thing.

**Comment by JonPsson** [comment]
ok - patch proposed at https://github.com/llvm/llvm-project/issues/61268
