### ISSUE TITLE
clang rejects-valid(?) on lambda template with requires-clause following template-parameter-list consisting of a variable template

### ISSUE THREAD

**Issue by rymiel** [llvm/llvm-project#61278]
Compiler Explorer demonstration: https://godbolt.org/z/x8oT5Y9bz

According [to the C++ grammar](https://eel.is/c++draft/expr.prim.lambda.general#nt:lambda-expression), a *lambda-expression* can contain a *requires-clause* after its *template-parameter-list* (added in [p0857r0](https://wg21.link/p0857r0))

However, when said *requires-clause* consists of a single bool variable template, as is common with std type trait `_v` helpers, clang seems to get confused and fails to properly parse the lambda, such as the following:

```c++
[&]<typename Callable>
  requires foo_v<Callable>
(Callable&& callable)
{
  static_cast<void>(callable);
};
```

Resulting in odd errors such as:
```console
error: 'Callable' does not refer to a value
  (Callable&& callable)
   ^
note: declared here
  [&]<typename Callable>
               ^
error: use of undeclared identifier 'callable'
  (Callable&& callable)
              ^
```

Note that for other similar cases, such as a type-trait-esque static member constant, or a concept, this seems to work fine, as demonstrated in the Compiler Explorer link above.
Also note that this example works for GCC, also demonstrated on Compiler Explorer.

Related to https://github.com/llvm/llvm-project/issues/46720

If I had to guess, it probably has to do with the fact that, syntactically, this construct is very weird due to the parentheses immediately following the requires clause, and is possibly being parsed as a cast or something. I also am not sure if this is a bug at all, since I'm not well versed in standardese, and the grammar is only informative, to my knowledge.

**Comment by shafik** [comment]
CC @erichkeane for confirmation but it looks like we should accept this, BTW MSVC also accepts: https://godbolt.org/z/bjfsd6xs9

**Comment by erichkeane** [comment]
That definitely seems like it is something we should parse.  I suspect the suspicion that we're thinking this is a cast of some sort is perhaps spot-on.  I've not dug too deep into parsing here, but we could perhaps just be using the wrong parse calls for a requirement.

**Comment by rymiel** [comment]
I took a crack at trying to solve this myself, and while I did successfully identify the cause, I don't know how to actually solve the issue due to my lack of any kind of experience with clang internals.

Everything parses successfully, however the issue is caused by the following check, performed after parsing:
https://github.com/llvm/llvm-project/blob/507c67d00e083995f0deb013300b03a1d1a65b70/clang/lib/Sema/SemaConcept.cpp#L110-L118

Meaning it is indeed caused by "the parentheses immediately following the requires clause". This explains why the issue only arises when using `foo_v`, because it is the only case where the requires clause is an `UnresolvedLookupExpr`.

Removing this check entirely fixes the issue, but that also gets rid of the diagnostic check for cases in which it might be useful, which was its original intent! I do not know how to improve this heuristic, since I don't actually know what an "UnresolvedLookupExpr" is

**Comment by rymiel** [comment]
> It is also odd that something in "Sema" is checking what the next token is, so I'm a little surprised here for a number of reasons!
> In this case, I'd probably suggest searching the CWG core issues list to see if something like this came up since this code was written to disambiguate this, or at least what in the standard DOES disambiguate it. Often that makes it clear how a condition like this might need to change.

I think there's been a bit of a misunderstanding: from what I understand, this part of the code performs nothing semantically significant, everything has already been parsed (correctly!), with no ambiguities. It is a heuristic ran *after* parsing to detect if maybe someone has written something that is misinterpreted by the parser, and offers a possible explanation and solution. It's only purpose is diagnostics, but it fires incorrectly here. And as a consequence it attempts to do recovery, but it "recovers" from a completely valid parse, resulting in an invalid parse instead!

> Though, I don't know why that bit is what catches it, since even following the comment and wrapping the requires condition in parens still triggers this problem ([godbolt.org/z/555PbWrTn](https://godbolt.org/z/555PbWrTn)).

It's because the original check never anticipated a legitimate *requires-clause* to ever be followed by a left paren. It assumes we're dealing with a pattern as shown in the comment above the check `template<typename> requires func(0) struct S { };`, but that is simply not the case, therefore it misfires.


Nevertheless, I made an attempt at fixing this, This fix is definitely not efficient, or pretty, and it's also my first change to the clang frontend itself:
https://reviews.llvm.org/D146140

**Comment by erichkeane** [comment]
> > It is also odd that something in "Sema" is checking what the next token is, so I'm a little surprised here for a number of reasons!
> > In this case, I'd probably suggest searching the CWG core issues list to see if something like this came up since this code was written to disambiguate this, or at least what in the standard DOES disambiguate it. Often that makes it clear how a condition like this might need to change.
> 
> I think there's been a bit of a misunderstanding: from what I understand, this part of the code performs nothing semantically significant, everything has already been parsed (correctly!), with no ambiguities. It is a heuristic ran _after_ parsing to detect if maybe someone has written something that is misinterpreted by the parser, and offers a possible explanation and solution. It's only purpose is diagnostics, but it fires incorrectly here. And as a consequence it attempts to do recovery, but it "recovers" from a completely valid parse, resulting in an invalid parse instead!
> 
> > Though, I don't know why that bit is what catches it, since even following the comment and wrapping the requires condition in parens still triggers this problem ([godbolt.org/z/555PbWrTn](https://godbolt.org/z/555PbWrTn)).
> 
> It's because the original check never anticipated a legitimate _requires-clause_ to ever be followed by a left paren. It assumes we're dealing with a pattern as shown in the comment above the check `template<typename> requires func(0) struct S { };`, but that is simply not the case, therefore it misfires.
> 
> Nevertheless, I made an attempt at fixing this, This fix is definitely not efficient, or pretty, and it's also my first change to the clang frontend itself: https://reviews.llvm.org/D146140

I think I get what you mean in that first bit now that I've seen the patch.  I think it is a little incorrect, but I've commented on the patch.  It is pretty reasonable looking to me, but I left those comments on the patch.  Thanks for the patch!
