### ISSUE TITLE
clang-format messes up the formatting of constrained templates

### ISSUE THREAD

**Issue by usx95** [llvm/llvm-project#61270]
Some, but not all, C++20 requires expressions are severely mangled. This seems to be much more likely when ref qualifications are involved. Examples:

1.  This:

    ```c++
    template <typename F>
    auto Bind (F f) && requires true;
    ```
    
    is turned into this:
    
    ```c++
    template <typename F>
        auto Bind(F f) &&
          requires true;
    ```

2.  This:

    ```c++
    template <internal::coroutine_result T>
    template <typename F>
    auto CoFuture<T>::Bind(F f) &&
      requires true {
      return 0;
    }
    ```
    
    is turned into this:
    
    ```c++
    template <internal::coroutine_result T>
        template <typename F>
        auto CoFuture<T>::Bind(F f) &&
          requires true
    {
      return 0;
    }
    ```
3.  This:
    ```cpp
    template <typename T>
    int foofoofoofoofoofoofoo(T t) &&
      requires { abcdabcdabcdabcdabcd;abcdabcdabcdabcdabcd; }
    {
      return 0;
    }
    ```
    is turned into this: 
    ```cpp
    template <typename T>
        int foofoofoofoofoofoofoo(T t) &&    requires {
          abcdabcdabcdabcdabcd;
          abcdabcdabcdabcdabcd;
        } {
      return 0;
    }
    ```

**Comment by usx95** [comment]
CC: @HazardyKnusperkeks from clang format contributors for C++20 constructs.

**Comment by HazardyKnusperkeks** [comment]
So it seems it is always after the ref qualifier. I myself are going on a vacation, so no time to investigate. But @rymiel has proven quite good in this code and I'm sure she will find the reason and a fix, if not I'll look in about two weeks into it.

**Comment by rymiel** [comment]
Patch: https://reviews.llvm.org/D145656
