### ISSUE TITLE
C compiler unable to perform vectorized ternary operator

### ISSUE THREAD

**Issue by stolk** [llvm/llvm-project#61274]
Using the latest CLANG compiler, when compiling this snippet **as C**:

```
// Vector with 8 elements of 4 bytes each.
typedef float floatx8 __attribute__( ( vector_size(32) ) );

floatx8 add(floatx8 a, floatx8 b)
{
	return a+b;
}

floatx8 min(floatx8 a, floatx8 b)
{
	return a < b ? a : b;
}
```

will result in this error:
```
<source>:17:22: error: used type '__attribute__((__vector_size__(8 * sizeof(int)))) int' (vector of 8 'int' values) where arithmetic or pointer type is required
        return a < b ? a : b;
               ~~~~~ ^
1 error generated.
Compiler returned: 1
```

However, **if the exact same code is fed to the C++ compiler**, clang will happily compile those functions into single instruction vector operations on x86-64.

## ACTUAL RESULT

The C compiler [fails](https://godbolt.org/z/hzfc6M9vd).

The C++ compiler [succeeds](https://godbolt.org/z/Ts6GcP7Ys).

## EXPECTED RESULT

Clang treats this code the same both in C and C++ mode.

## Version

clang 15.0.0

**Comment by topperc** [comment]
This behavior is intentional and is documented https://clang.llvm.org/docs/LanguageExtensions.html#id1 but I don't know the reasons.

**Comment by topperc** [comment]
gcc's documentation also says its only available in C++ https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html

**Comment by stolk** [comment]
@topperc Ok, thank you for finding that. Not a bug then.
Although rather disappointing. I guess it means I have to write my code in C++ instead of C.

**Comment by topperc** [comment]
It's ugly but this does work

```
floatx8 min(floatx8 a, floatx8 b)
{
    intx8 c = a < b;
	return (floatx8)((c & (intx8)a) | (~c & (intx8)b));
}
```
