### ISSUE TITLE
Backport ffdd5a330c05fa2b4339f64402f650df068c5767 to LLVM 16

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#61287]
I'd like to propose we backport ffdd5a330c05fa2b4339f64402f650df068c5767 to LLVM 16

The znver4 cpu made it in time for the 16.x branch but the scheduler model was delayed and has only recently been committed

https://reviews.llvm.org/D144010

/cherry-pick ffdd5a330c05fa2b4339f64402f650df068c5767

CC @ganeshgit

**Comment by ganeshgit** [comment]
@RKSimon Thanks a ton!

**Comment by ganeshgit** [comment]
Thank you @EugeneZelenko @tru @RKSimon
