### ISSUE TITLE
[clangd] move function body to out of line should remove inline

### ISSUE THREAD

**Issue by Febbe** [llvm/llvm-project#61295]
Having a function 
```c
inline void test() {}
```

I would expect clangd, to also removing the `inline` when refactoring it with `move function body to out of line`.

**Comment by 5chmidti** [comment]
The issue was fixed in commit [fe7afcf](https://github.com/llvm/llvm-project/commit/fe7afcf70c93223a16ec7a2a5e07c4ace16c9a04) linked above. Can someone please close this issue?
