### ISSUE TITLE
[Clang] Condition is always true which is caused by a possible copy-pasted bug in CGOpenMPRuntime.cpp

### ISSUE THREAD

**Issue by ustchcs-bugfinder** [llvm/llvm-project#61319]
https://github.com/llvm/llvm-project/blob/7b338a691ec916cde3fd293123e32b490d260922/clang/lib/CodeGen/CGOpenMPRuntime.cpp#L11173

`kind == ` is likely omitted. Therefore the condition on L11173 is always true.

Correct code:

``` cpp
if (Kind == ParamKindTy::LinearUVal ||  kind == ParamKindTy::LinearRef)   // Line 11173
```

Current code:

```cpp
/// Maps To Vector (MTV), as defined in 4.1.1 of the AAVFABI (2021Q1).
static bool getAArch64MTV(QualType QT, ParamKindTy Kind) {
  QT = QT.getCanonicalType();

  if (QT->isVoidType())
    return false;

  if (Kind == ParamKindTy::Uniform)
    return false;

  if (Kind == ParamKindTy::LinearUVal || ParamKindTy::LinearRef)   // Line 11173
    return false;

  if ((Kind == ParamKindTy::Linear || Kind == ParamKindTy::LinearVal) &&
      !QT->isReferenceType())
    return false;

  return true;
}
```

**Comment by shiltian** [comment]
Yes, thanks for pointing out. Do you want to post a fix?

**Comment by ustchcs-bugfinder** [comment]
You are welcome.  We are glad to know this issue is useful to the community. That's enough.

**Comment by samuelmaina** [comment]
@SamTebbs33 , Do I have to modify the failing tests and create new ones to regress for the added conditions?

**Comment by SamTebbs33** [comment]
I'm not familiar with that file, so I'm not sure what tests are failing but you can try fixing the condition and changing any tests that need to be changed as as a result of that.

**Comment by s-pratik** [comment]
Hi, I want to take this issue. As I am a beginner I just wanted to know how can I run the test cases after fixing the condition.

**Comment by samuelmaina** [comment]
Hi @s-pratik I am working on this issue.No one is assigning issues as far as I know.Just pick any as if it's not closed.

**Comment by jhuber6** [comment]
> Hi, I want to take this issue. As I am a beginner I just wanted to know how can I run the test cases after fixing the condition.

You can run the `clang-clang` target in the build directory, assuming you've built clang like in https://llvm.org/docs/CMake.html. E.g. `ninja check-clang` if you're using Ninja. The tests use `llvm-lit` https://llvm.org/docs/CommandGuide/lit.html which should be present in your build directory's `./bin` directory. You can run a single test manually if you do not with to use the target. For example:
```
./bin/llvm-lit -vv ../clang/test/Driver/clang_cpp.c
```

Generally, if all the tests still pass after making a change you can try modifying the tests to catch the new change.

**Comment by samuelmaina** [comment]
@jhuber6 How do I get which tests are failing?  I have changed some tests to test the current condition but I can't see the details of which tests are failing, I am only getting a summary. I have tried the -v (--verbose) flag but I can't get the tests .How can I get the files and the details?
Here is the is code
`llvm-lit: /home/samuelmayna/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using clang: /home/samuelmayna/llvm-project/build/bin/clang

Testing Time: 2577.47s
  Skipped          :     8
  Unsupported      :   134
  Passed           : 33312
  Expectedly Failed:    27`

**Comment by samuelmaina** [comment]
`Testing Time: 1496.56s
  Unsupported      :  1777
  Passed           : 34455
  Expectedly Failed:   150
  Failed           :  9400`
Here is output. So many of them are failing

**Comment by samuelmaina** [comment]
The first unit tests I could find are for functions that are 6 levels higher from this function .The function is very low level and couldn't find a way to affect it from the higher functions.

**Comment by jhuber6** [comment]
This fix is extremely minor. Adding a new test that stimulates it will be difficult. Personally I wouldn't bother making a new test.

**Comment by samuelmaina** [comment]
Thanks @jhuber6 . Can you please approve the patch at  [https://reviews.llvm.org/D146370](https://reviews.llvm.org/D146370)? I am in outreachy intern and I need to document  an approved patch.

**Comment by xgupta** [comment]
Fixed by -https://github.com/llvm/llvm-project/commit/c1ab19850d5c42a6f76d9bd6049f9cba6e08fba1.
