### ISSUE TITLE
[libc++][format] Should `formatter<vec-bool-ref>` be default constructible without `<format>` include?

### ISSUE THREAD

**Issue by JMazurkiewicz** [llvm/llvm-project#61314]
According to [[vector.syn]](http://eel.is/c++draft/vector.syn), `formatter` specialization for `vector<bool>::reference` should be available in `<vector>` header and (since it satisfies [*BasicFormatter*](http://eel.is/c++draft/format#formatter.requirements)) it should be also default constructible.

Repro:

```c++
#include <concepts>
#include <vector>

using R = std::vector<bool>::reference;
using F = std::formatter<R>;
static_assert(std::default_initializable<F>);
```

Expected: *correct compilation*
Got: *failed static assertion, because `<format>` include is missing*
Compiler explorer: https://godbolt.org/z/sW8dM8cvd

**Comment by mordante** [comment]
Thanks for the report, this is indeed a bug. I noticed there's no explicit test to verify this works.

**Comment by mordante** [comment]
This has been addressed in https://reviews.llvm.org/D149543.
