### ISSUE TITLE
Flang-new 15.0.7 core dumped on OpenMP example

### ISSUE THREAD

**Issue by antoine-morvan** [llvm/llvm-project#61323]
Hello, 

I tried compiling an OpenMP example (adapted from this https://people.math.sc.edu/Burkardt/f_src/openmp/compute_pi_openmp.f90).
The command I used was :
```
flang-new -flang-experimental-exec -fopenmp -O3 -march=native -mtune=native openmp_sample.F90 
```

The command crashed with a rather long message, essentially saying: 
```
LLVM ERROR: aborting
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
[...]
flang-new: error: unable to execute command: Aborted (core dumped)
flang-new: error: flang frontend command failed due to signal (use -v to see invocation)
```

Flang is also telling me to attach 2 files for reproducing purposes. I dropped them here, along with the input F90 file and the full command log :
https://github.com/antoine-morvan/openmp_sample-6c3e26

Best.

**Comment by kiranchandramohan** [comment]
This passes with the main branch.

Flang is a compiler under active development. There are several fixes and features that went in after the 15 release. Since the compiler is not yet ready for general purpose use, there is no plan to port fixes or features to release branches.
