### ISSUE TITLE
Clang document on "-fomit-frame-pointer" and  -fno-omit-frame-pointer doesn't have any info on the same 

### ISSUE THREAD

**Issue by UmeshKalappa0** [llvm/llvm-project#61322]
The https://clang.llvm.org/docs/ClangCommandLineReference.html needs updated for "omit-frame-pointer" and other form too .

**Comment by aabhinavg** [comment]
How to update the document i want to take the issue?

**Comment by EugeneZelenko** [comment]
@aabhinavg: See https://llvm.org/docs/Phabricator.html for patch process.

**Comment by aabhinavg** [comment]
Patch for review: https://reviews.llvm.org/D145840
