### ISSUE TITLE
-Wunused-private-field still triggers on [[maybe_unused]] member

### ISSUE THREAD

**Issue by pkasting** [llvm/llvm-project#61334]
The following code triggers a warning with `-Wunused-private-field` (see https://godbolt.org/z/1G944d41q):
```cpp
class [[maybe_unused]] Unused {};

class C {
 private:
  Unused unused_;
};
```

As far as I can tell from https://eel.is/c++draft/dcl.attr.unused, Clang should probably not warn here.

**Comment by pkasting** [comment]
Note: Explicitly marking the field itself as `[[maybe_unused]]` works around.

**Comment by shafik** [comment]
Looking at the code in `Sema::ActOnCXXMemberDeclarator` and I can add 

```cpp
!(FD->getType()->isRecordType() && FD->getType()->getAsCXXRecordDecl()->hasAttr<UnusedAttr>()) &&
```

to this check:

```cpp
if (!FD->isImplicit() && FD->getDeclName() &&
          FD->getAccess() == AS_private &&
          !FD->hasAttr<UnusedAttr>() &&
          !FD->getParent()->isDependentContext() &&
          !(FD->getType()->isRecordType() && FD->getType()->getAsCXXRecordDecl()->hasAttr<UnusedAttr>()) &&
          !InitializationHasSideEffects(*FD))
        UnusedPrivateFields.insert(FD);
    }
```

but not sure if there is a better way @AaronBallman wdyt?

**Comment by AaronBallman** [comment]
Close, but not quite. I think you need to use `FD->getType()->isTagType() && FD->getType()->getAsTagDecl()->hasAttr<UnusedAttr>()`, which solves two issues. 1) In C, `isRecordType()` will return `true` for a `struct`, but `getAsCXXRecordDecl()` will return `nullptr`, and 2) Enumerations also need to be handled. (So be sure to add these as test cases as well, please.)

**Comment by zmodem** [comment]
@shafik are you looking at this? Otherwise I might give it a try based on the excellent hints on the bug already :)

**Comment by zmodem** [comment]
Thanks! Sent https://reviews.llvm.org/D159083
