### ISSUE TITLE
AMDGPU: why is __builtin_amdgcn_global_atomic_fadd_f32 not available for gfx908 / gfx11?

### ISSUE THREAD

**Issue by Epliz** [llvm/llvm-project#61331]
Hi,

It looks like `__builtin_amdgcn_global_atomic_fadd_f32` is only available for gfx90a+ but according to the ISA docs, it is available on gfx908 and gfx11.
Any reason why the builtin is not available for those architectures?

Best regards,
Epliz

**Comment by Epliz** [comment]
Thanks @jayfoad  for pointing to the review.

Based on what I read there, it looks like the builtin is missing for gfx908 as there was no instruction supporting the return of the value. For gfx908 then it makes sense. Calling `atomicAddNoRet` in HIP gives the `global_atomic_add_f32` for gfx908 which is great.

For gfx11, based on the ISA docs it looks like both the with return and no-return versions of `global_atomic_add_f32` are supported. Then I think it would be great to have the intrinsic, and especially to get the no-return version used by `atomicAddNoRet` which is currently not the case.

Would that make sense?

**Comment by gandhi56** [comment]
So if I understood correctly, we need an intrinsic which lowers down to `global_atomic_add_f32` on gfx11. Meanwhile, the builtins are correctly supported. Is that right?

**Comment by Epliz** [comment]
Yes, looks like something is missing for gfx11 as the built-in is not available, and the HIP atomic functions don't seem to leverage the `global_atomic_add_f32` instructions.

gfx908 is fine.

**Comment by arsenm** [comment]
The builtin predicate is based on gfx90a-insts. This is another instance where we really need finer grained features for global FP atomics

**Comment by Epliz** [comment]
@arsenm , what is your policy for naming of the builtins and deprecation of the ones you want to get rid of?

Could the architecture name always be part of the name for the builtins of new instructions and a "proper" built-in not including the arch name would be for things that are determined to likely be stable in the future?

In x86_64 world, avx2 intrinsics all have avx2 in the name for example.

(Not sure if builtins/intrinsics are different end user visible things or they all are made with builtins).

**Comment by arsenm** [comment]
> @arsenm , what is your policy for naming of the builtins and deprecation of the ones you want to get rid of?

Generally shouldn't remove user facing builtins is the general clang policy

> Could the architecture name always be part of the name for the builtins of new instructions and a "proper" built-in not including the arch name would be for things that are determined to likely be stable in the future?

This would be unworkable in general. We don't have the luxury of nicely packaged ISA extensions with compatibility guarantees. It's the edge cases where we have issues (the FP atomics like this are the absolute worst one)


@gandhi56 can you look into using a specific target feature for this instead of the catch-all generation one?

**Comment by gandhi56** [comment]
@arsenm We only need to capture gfx9 and gfx11 right? I am thinking of defining a target feature `isGFX9GFX11`.

**Comment by gandhi56** [comment]
`HasFineGrainedAtomicOps` or `HasFineGrainedAtomicFPOps`?

**Comment by arsenm** [comment]
> `HasFineGrainedAtomicOps` or `HasFineGrainedAtomicFPOps`?

Why "FineGrained"? global-atomic-fadd? Do we need separate return and no return variants?

**Comment by gandhi56** [comment]
Yes, I was hoping to capture all instructions with finer-grained features including `global-atomic-fadd`. I am not sure if we will need both return and no-return variants.

**Comment by gandhi56** [comment]
@arsenm what do you think of `HasFineGrainedAtomicOps`? I can't think of a better feature that is architecture-independent and specifies the ability to generate `global_atomic` FP operations.

**Comment by jayfoad** [comment]
See https://reviews.llvm.org/D146701 for some fine(r)-grained features that are being added for other atomics.

**Comment by Epliz** [comment]
Based on the review pointed by @jayfoad , "atomic_global_add_f32_insts" ?

**Comment by gandhi56** [comment]
https://reviews.llvm.org/D146840

**Comment by Epliz** [comment]
@gandhi56 , based on discussion at the beginning of this thread, gfx908 does NOT support the instruction with return. Only the instruction without return.

**Comment by gandhi56** [comment]
Thanks to clarify, to summarize:

Return version of `__builtin_amdgcn_global_atomic_fadd_f32` should be supported on gfx1100, only.

While the no-return version of `__builtin_amdgcn_global_atomic_fadd_f32` should be supported on gfx908 and gfx90a.

Is the correct?

**Comment by Epliz** [comment]
Hi @gandhi56 ,

From what I understand/know:
* the version without return is supported on gfx908, gfx90a+, gfx11
* the version with return is supported on gfx90a+, gfx11

Best,
Epliz
