### ISSUE TITLE
GVN incorrectly converts load to a constant with the `allockind(alloc,zeroed)` attribute

### ISSUE THREAD

**Issue by aykevl** [llvm/llvm-project#61362]
I have the following IR, which is a simplified version of a real bug I'm hitting over at https://github.com/tinygo-org/tinygo/pull/3540:

```llvm
define i16 @readValue(ptr %addr, ptr %wait) optsize {
entry:
  ; allocate memory for %value
  %value = call ptr @alloc(i32 2)

  ; store this pointer into a hardware register
  %value_int = ptrtoint ptr %value to i32
  store volatile i32 %value_int, ptr %addr

  ; wait until the hardware has written to %value
  br label %loop
loop:
  %ready = load volatile i1, ptr %wait
  br i1 %ready, label %loop, label %done
done:

  ; condition is satisfied, read the result from %value
  %result = load i16, ptr %value
  ret i16 %result
}
```

The code works as follows:

1. An object is allocated on the heap.
2. A pointer to this object is stored in a hardware register.
3. The code waits for the hardware to change the value.
4. The value is loaded, and returned.

After `opt -passes=gvn`, the IR looks like this ([Godbolt link](https://llvm.godbolt.org/z/axoqPx19z)):

```llvm
define i16 @readValue(ptr %addr, ptr %wait) #1 {
  %value = call ptr @alloc(i32 2)
  %value_int = ptrtoint ptr %value to i32
  store volatile i32 %value_int, ptr %addr, align 4
  br label %loop

loop:                                             ; preds = %loop, %entry
  %ready = load volatile i1, ptr %wait, align 1
  br i1 %ready, label %loop, label %done

done:                                             ; preds = %loop
  ret i16 0
}
```

Unfortunately, GVN converts the load and return at the end to a simple constant `ret i16 0`. This is unexpected, and I believe this is a bug in GVN.

The logic in GVN appears to be that the call to `@alloc` returns zeroed memory, it doesn't see any store to the memory, and therefore it believes the load at the end can be replaced with a zero value. However, in this case, the pointer actually escapes before it is loaded at the end so as I see it, GVN should not have assumed the value didn't change.

Some notes:

- It is still reproducible when I use `store volatile ptr %value, ptr %addr` (storing the pointer as a pointer type, instead of as a ptrtoint).
- It also reproduces without the loop, but I put the loop in there to make the code a bit more realistic.

**Comment by aykevl** [comment]
Actually this is unrelated to `allockind`. I can also reproduce it by changing the call to `@alloc` at the beginning with an alloca ([Godbolt link](https://llvm.godbolt.org/z/PKfe3boE5)):

```llvm
  ; allocate memory for %value
  %value = alloca i16
  store i16 0, ptr %value
```

The important part appears to be that GVN sees that the memory has a known value.

**Comment by nikic** [comment]
Please see https://llvm.org/docs/LangRef.html#volatile-memory-accesses for restrictions on volatile operations and in particular:

> The allowed side-effects for volatile accesses are limited. If a non-volatile store to a given address would be legal, a volatile operation may modify the memory at that address. A volatile operation may not modify any other memory accessible by the module being compiled. A volatile operation may not call any code in the current module.

In particular, this means that `load volatile i1, ptr %wait` is not allowed to modify `%value`, even if it has escaped beforehand. As such, the GVN optimization is correct.

You need to use additional synchronization (atomics or fences) to make this work as you want.

**Comment by aykevl** [comment]
Right, I see. Then this is not actually a bug.

I fixed it by making the read from `%value` at the end volatile. This is a single core chip, and "volatile" actually seems like a reasonable way to do it because it really is the hardware that changes the value without the compiler knowing. A kind of synchronization barrier would probably be better, I'll take a look whether I can find one that doesn't insert unnecessary instructions.
