### ISSUE TITLE
std::ranges symbols are missing from stdlib mapping

### ISSUE THREAD

**Issue by kadircet** [llvm/llvm-project#61373]
we can parse them from https://en.cppreference.com/w/cpp/symbol_index/ranges, similar to other sub-namespaces in https://github.com/llvm/llvm-project/blob/main/clang/tools/include-mapping/gen_std.py#L250

**Comment by firewave** [comment]
It looks like the file was modified manually and not by the script. Otherwise the header should have been changed.

From `clang/lib/Tooling/Inclusions/Stdlib/StdSymbolMap.inc`
```
// This file was generated automatically by
// clang/tools/include-mapping/gen_std.py, DO NOT EDIT!
//
// Generated from cppreference offline HTML book (modified on 2022-07-30).
```
