### ISSUE TITLE
[mlir] Convert-scf-to-spirv pass erase the "scf.yield" and reports error " 'scf.parallel' op expects body to terminate with 'scf.yield'"

### ISSUE THREAD

**Issue by Colloportus0** [llvm/llvm-project#61380]
After fixing the issue [59989](https://github.com/llvm/llvm-project/issues/59989) , now `convert-scf-to-spirv` pass report the following error on this example

example:
```mlir
module {
  func.func @func(%arg0: i64) {
    %0 = builtin.unrealized_conversion_cast %arg0 : i64 to index 
    %alloc = memref.alloc() : memref<16xf32> 
    scf.parallel (%arg1) = (%0) to (%0) step (%0) {
      %cst = arith.constant 1.000000e+00 : f32
      memref.store %cst, %alloc[%arg1] : memref<16xf32>
      scf.yield
    }
    return
  }
}
```

error message:
```console
'scf.parallel' op expects body to terminate with 'scf.yield'
temp.mlir:5:5: note: see current operation:
"scf.parallel"(%0, %0, %0) ({
^bb0(%arg1: index):
%2 = "spirv.Constant"() {value = 1.000000e+00 : f32} : () -> f32
"memref.store"(%2, %1, %arg1) : (f32, memref<16xf32>, index) -> ()
}) {operand_segment_sizes = array<i32: 1, 1, 1, 0>} : (index, index, index) -> ()
```
What I am curious about is, the region in the above example terminated with `scf.yield`, but the region in the error message does not. Why would that happen? Is `scf.yield` eliminated by  `--convert-scf-to-spirv` pass?

**Comment by kuhar** [comment]
I can reproduce this. Thanks for reporting, @Colloportus0!

**Comment by kuhar** [comment]
Fix in review: https://reviews.llvm.org/D146080. This should also address similar issues with `scf.yield`.
