### ISSUE TITLE
Crash when building the latest version 14-Mar-2023

### ISSUE THREAD

**Issue by jdanne** [llvm/llvm-project#61399]
```console
$ cd /home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL && ../../../../bin/opt -passes=internalize -internalize-public-api-file=/home/jdanne/src/llvm-project/openmp/libomptarget/DeviceRTL/src/exports /home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL/linked_libomptarget-amdgpu-gfx1033.bc -o /home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL/internalized_libomptarget-amdgpu-gfx1033.bc
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ../../../../bin/opt -O3 -openmp-opt-disable -attributor-enable=module /home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL/internalized_libomptarget-nvptx-sm_90.bc -o /home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL/libomptarget-nvptx-sm_90.bc
[ 76%] Optimizing LLVM bitcode libomptarget-amdgpu-gfx1033.bc
cd /home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL && ../../../../bin/opt -O3 -openmp-opt-disable -attributor-enable=module /home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL/internalized_libomptarget-amdgpu-gfx1033.bc -o /home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL/libomptarget-amdgpu-gfx1033.bc
 #0 0x0000000001e02b11 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (../../../../bin/opt+0x1e02b11)
 #1 0x0000000001e005a4 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f785f1f2630 __restore_rt sigaction.c:0:0
 #3 0x0000000001d90f22 llvm::StringMapImpl::LookupBucketFor(llvm::StringRef) (../../../../bin/opt+0x1d90f22)
 #4 0x000000000183c0d3 llvm::ValueSymbolTable::createValueName(llvm::StringRef, llvm::Value*) (../../../../bin/opt+0x183c0d3)
 #5 0x0000000001836596 llvm::Value::setNameImpl(llvm::Twine const&) (../../../../bin/opt+0x1836596)
 #6 0x00000000018366c9 llvm::Value::setName(llvm::Twine const&) (../../../../bin/opt+0x18366c9)
 #7 0x0000000001f43306 llvm::PredicateInfoBuilder::materializeStack(unsigned int&, llvm::SmallVectorImpl<llvm::ValueDFS>&, llvm::Value*) (../../../../bin/opt+0x1f43306)
 #8 0x0000000001f4c573 llvm::PredicateInfoBuilder::renameUses(llvm::SmallVectorImpl<llvm::Value*>&) (../../../../bin/opt+0x1f4c573)
 #9 0x0000000001f4d241 llvm::PredicateInfoBuilder::buildPredicateInfo() (../../../../bin/opt+0x1f4d241)
#10 0x0000000001f4d523 llvm::PredicateInfo::PredicateInfo(llvm::Function&, llvm::DominatorTree&, llvm::AssumptionCache&) (../../../../bin/opt+0x1f4d523)
#11 0x00000000026d7298 runIPSCCP(llvm::Module&, llvm::DataLayout const&, llvm::AnalysisManager<llvm::Function>*, std::function<llvm::TargetLibraryInfo const& (llvm::Function&)>, std::function<llvm::TargetTransformInfo& (llvm::Function&)>, std::function<llvm::AssumptionCache& (llvm::Function&)>, llvm::function_ref<llvm::AnalysisResultsForFn (llvm::Function&)>, bool) (.constprop.0) SCCP.cpp:0:0
#12 0x00000000026d975c llvm::IPSCCPPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (../../../../bin/opt+0x26d975c)
#13 0x000000000200a87e llvm::detail::PassModel<llvm::Module, llvm::IPSCCPPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (../../../../bin/opt+0x200a87e)
#14 0x000000000076f340 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool) (../../../../bin/opt+0x76f340)
#15 0x00000000006c43c6 main (../../../../bin/opt+0x6c43c6)
#16 0x00007f785dccb555 __libc_start_main (/lib64/libc.so.6+0x22555)
#17 0x00000000007623ca _start (../../../../bin/opt+0x7623ca)
/bin/sh: line 1: 56000 Segmentation fault      ../../../../bin/opt -O3 -openmp-opt-disable -attributor-enable=module /home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL/internalized_libomptarget-nvptx-sm_90.bc -o /home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL/libomptarget-nvptx-sm_90.bc
make[2]: *** [projects/openmp/libomptarget/DeviceRTL/libomptarget-nvptx-sm_90.bc] Error 139
make[2]: Leaving directory `/home/jdanne/src/llvm-project/build-1'
make[1]: *** [projects/openmp/libomptarget/DeviceRTL/CMakeFiles/omptarget-nvptx-sm_90-bc.dir/all] Error 2
[ 76%] Building CXX object tools/llvm-reduce/CMakeFiles/llvm-reduce.dir/deltas/ReduceMemoryOperations.cpp.o
```

**Comment by PavelKopyl** [comment]
Hi,

Could you provide any details of how to reproduce this? How cmake was run?

**Comment by jdanne** [comment]
Hi,

cmake ../llvm -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;compiler-rt;lldb;lld;openmp -DLLVM_ENABLE_RUNTIMES=libcxx;libcxxabi;libunwind -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/jdanne/clang_experimental/16.0.0/clang-16.0.0 -G 'Unix Makefiles' -DCLANG_INCLUDE_DOCS=OFF -DCLANG_INCLUDE_TESTS=OFF -DCOMPILER_RT_INCLUDE_TESTS=OFF -DLIBCXX_INCLUDE_DOCS=OFF -DLIBCXX_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_GO_TESTS=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_TARGETS_TO_BUILD=X86;ARM -DLLDB_DISABLE_LIBEDIT=1 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DPYTHON_LIBRARIES=/home/aptRoot/apttools/python/64/Python-3.8.0/lib/libpython3.8.so -DPYTHON_INCLUDE_DIRS=/home/aptRoot/apttools/python/64/Python-3.8.0/include/python3.8 -DPYTHON_EXECUTABLE=/home/aptRoot/apttools/python/64/Python-3.8.0/bin/python3 -DLLVM_LIBDIR_SUFFIX=64 '-DCMAKE_EXE_LINKER_FLAGS=-Wl,-rpath,/gitworkspace/distributions/gcc/11.2.0/gcc-11.2.0/lib64 -Wl,-rpath,/home/jdanne/clang_experimental/16.0.0/clang-16.0.0/lib64' -DCMAKE_C_COMPILER=/gitworkspace/distributions/gcc/11.2.0/gcc-11.2.0/bin/gcc -DCMAKE_CXX_COMPILER=/gitworkspace/distributions/gcc/11.2.0/gcc-11.2.0/bin/g++ -DCMAKE_ASM_COMPILER=/gitworkspace/distributions/gcc/11.2.0/gcc-11.2.0/bin/gcc -DGCC_INSTALL_PREFIX=/gitworkspace/distributions/gcc/11.2.0/gcc-11.2.0
CMake Warning at CMakeLists.txt:5 (message):
  Your CMake version is 3.15.4.  Starting with LLVM 17.0.0, the minimum
  version of CMake required to build LLVM will become 3.20.0, and using an
  older CMake will become an error.  Please upgrade your CMake to at least
  3.20.0 now to avoid issues in the future!

**Comment by jdanne** [comment]
I retried with cmake 3.21.3 but still get the following backtrace:

0.	Program arguments: ../../../../bin/opt -O3 -openmp-opt-disable -attributor-enable=module /home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL/internalized_libomptarget-nvptx-sm_75.bc -o /home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL/libomptarget-nvptx-sm_75.bc
 #0 0x0000000001e02b11 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (../../../../bin/opt+0x1e02b11)
 #1 0x0000000001e005a4 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f1438014630 __restore_rt sigaction.c:0:0
 #3 0x0000000001d91182 llvm::StringMapImpl::RemoveKey(llvm::StringMapEntryBase*) (../../../../bin/opt+0x1d91182)
 #4 0x000000000179011e llvm::Instruction::eraseFromParent() (../../../../bin/opt+0x179011e)
 #5 0x00000000026d78d2 runIPSCCP(llvm::Module&, llvm::DataLayout const&, llvm::AnalysisManager<llvm::Function>*, std::function<llvm::TargetLibraryInfo const& (llvm::Function&)>, std::function<llvm::TargetTransformInfo& (llvm::Function&)>, std::function<llvm::AssumptionCache& (llvm::Function&)>, llvm::function_ref<llvm::AnalysisResultsForFn (llvm::Function&)>, bool) (.constprop.0) SCCP.cpp:0:0
 #6 0x00000000026d975c llvm::IPSCCPPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (../../../../bin/opt+0x26d975c)
 #7 0x000000000200a87e llvm::detail::PassModel<llvm::Module, llvm::IPSCCPPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (../../../../bin/opt+0x200a87e)
 #8 0x000000000076f340 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool) (../../../../bin/opt+0x76f340)
 #9 0x00000000006c43c6 main (../../../../bin/opt+0x6c43c6)
#10 0x00007f1436aed555 __libc_start_main (/lib64/libc.so.6+0x22555)
#11 0x00000000007623ca _start (../../../../bin/opt+0x7623ca)
[ 80%] Building LLVM bitcode LibC.cpp-gfx1031.bc
cd /home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL && ../../../../bin/clang-17 -c -foffload-lto -std=c++17 -fvisibility=hidden -O3 -mllvm -openmp-opt-disable -DSHARED_SCRATCHPAD_SIZE=512 --offload-device-only -nocudalib -nogpulib -nostdinc -fopenmp -fopenmp-cuda-mode -Wno-unknown-cuda-version -I/home/jdanne/src/llvm-project/openmp/libomptarget/DeviceRTL/include -I/home/jdanne/src/llvm-project/openmp/libomptarget/DeviceRTL/../include -I/home/jdanne/src/llvm-project/llvm/include -I/home/jdanne/src/llvm-project/build-1/include --offload-arch=gfx1031 /home/jdanne/src/llvm-project/openmp/libomptarget/DeviceRTL/src/LibC.cpp -o LibC.cpp-gfx1031.bc
/bin/sh: line 1: 37286 Segmentation fault      ../../../../bin/opt -O3 -openmp-opt-disable -attributor-enable=module /home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL/internalized_libomptarget-nvptx-sm_75.bc -o /home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL/libomptarget-nvptx-sm_75.bc
make[2]: *** [projects/openmp/libomptarget/DeviceRTL/libomptarget-nvptx-sm_75.bc] Error 139
make[2]: Leaving directory `/home/jdanne/src/llvm-project/build-1'
make[1]: *** [projects/openmp/libomptarget/DeviceRTL/CMakeFiles/omptarget-nvptx-sm_75-bc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 80%] Building LLVM bitcode Mapping.cpp-gfx1031.bc

**Comment by jhuber6** [comment]
Is it possible for you to provide the file that seems to cause the issue? We should be able to run `opt -O3` on it and reproduce it.
`/home/jdanne/src/llvm-project/build-1/projects/openmp/libomptarget/DeviceRTL/internalized_libomptarget-nvptx-sm_90.bc`

**Comment by jdanne** [comment]
[internalized_libomptarget-nvptx-sm_90.tar.gz](https://github.com/llvm/llvm-project/files/10971249/internalized_libomptarget-nvptx-sm_90.tar.gz)

**Comment by jhuber6** [comment]
I couldn't reproduce it, does this fail on your machine?
```
opt -O3 -openmp-opt-disable -attributor-enable=module internalized_libomptarget-nvptx-sm_90.bc
```

**Comment by jdanne** [comment]
Very strange, I can't reproduce it, either. The build now works.
