### ISSUE TITLE
[Windows] File IDs aren't properly unique in some file share mounts

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#61401]
CC @tru @aganea @zmodem @nico and others who might know something about Windows.

In https://github.com/mstorsjo/llvm-mingw/issues/327 I got a report of various intermittent random failures with using a LLVM based toolchain. After some digging, we found out that the issues are related to using file share mounts.

Observations:
- Folders shared from the user host with MS Remote Desktop (tested from macOS) show the issue
- Folders shared from the host system with VirtualBox allegedly also show the issue (as reported by the original poster)
- Folders shared from the host system with VMWare Fusion don't show the problem
- Folders mounted from a Samba server don't show the problem

The problem appears in different forms, depending on whether the source files or the toolchain itself (or both) are located on the file share. The problems are nondeterministic.

In the case of linking, the symptom is that LLD fails to resolve a lot of symbols, e.g. like this:
```console
ld.lld: error: undefined symbol: __set_app_type
>>> referenced by ../crt/crtexe.c:0
>>>               z:/llvm-mingw-x86_64/x86_64-w64-mingw32/lib/crt2.o:(pre_c_init)

ld.lld: error: undefined symbol: __p__fmode
>>> referenced by ../crt/crtexe.c:119
>>>               z:/llvm-mingw-x86_64/x86_64-w64-mingw32/lib/crt2.o:(pre_c_init)

ld.lld: error: undefined symbol: __p__commode
>>> referenced by ../crt/crtexe.c:120
>>>               z:/llvm-mingw-x86_64/x86_64-w64-mingw32/lib/crt2.o:(pre_c_init)

ld.lld: error: undefined symbol: _setargv
>>> referenced by ../crt/crtexe.c:125
>>>               z:/llvm-mingw-x86_64/x86_64-w64-mingw32/lib/crt2.o:(pre_c_init)
```
It behaves as if LLD simply is ignoring a number of the input files.

After some digging, I've pinpointed that the issue is with file IDs. Within LLVM, `llvm::sys::fs::UniqueID`, https://github.com/llvm/llvm-project/blob/llvmorg-17-init/llvm/include/llvm/Support/FileSystem/UniqueID.h, is fairly central. This is built on the Windows File ID concept, see https://learn.microsoft.com/en-us/windows/win32/api/fileapi/ns-fileapi-by_handle_file_information:
> The identifier (low and high parts) and the volume serial number uniquely identify a file on a single computer. To determine whether two open handles represent the same file, combine the identifier and the volume serial number for each file and compare them.
> [...]
> The identifier that is stored in the nFileIndexHigh and nFileIndexLow members is called the file ID. Support for file IDs is file system-specific. File IDs are not guaranteed to be unique over time, because file systems are free to reuse them. In some cases, the file ID for a file can change over time.

In the case of LLD, it uses the `UniqueID`s to deduplicate input files. In that case, I'm not sure if it's solely a performance optimization or whether it would have a functional effect too. In other cases throughout LLVM, I'm sure the `UniqueID`s are fairly functionally essential.

To observe the issue, I've made a standalone test program that iterates over a directory and grabs the file unique IDs and inspects them for uniqueness, see https://gist.github.com/mstorsjo/74ea7b1769ae7043e0b784310a9a0d1e. Run the tool like e.g. `uniqueid.exe z:\directory`, where `z:` is a problematic file share mount. On a correctly working mount, it prints unique file IDs for all files and concludes e.g. `Iterated over 918 unique files, found 0 duplicates`, while on a problematic one, it prints e.g. `Iterated over 54 unique files, found 864 duplicates`.

In https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfileinformationbyhandle, it is said that:
> Depending on the underlying network features of the operating system and the type of server connected to, the GetFileInformationByHandle function may fail, return partial information, or full information for the given file.
> 
> You can compare the VolumeSerialNumber and FileIndex members returned in the [BY_HANDLE_FILE_INFORMATION](https://learn.microsoft.com/en-us/windows/desktop/api/fileapi/ns-fileapi-by_handle_file_information) structure to determine if two paths map to the same target; for example, you can compare two file paths and determine if they map to the same directory.

It doesn't say how to know if it actually returned partial information, and whether the FileIndex members can be known bogus.

What's the best way forward wrt this, given how central `UniqueID`s are within LLVM? Just conclude that the tools are incompatible with file share mounts that don't fulfill this file system contract? It's perhaps not so surprising that the VirtualBox mounts fail in this way, but a bit more surprising that Microsoft's own Remote Desktop mounts expose the same issue.

**Comment by alvinhochun** [comment]
Found an old report #22079 about the same issue.

**Comment by mstorsjo** [comment]
> Found an old report #22079 about the same issue.

Thanks, that was a good find. And the observation that the ID might be unique only as long as the HANDLE is open is a good observation.

However it seems like others do make the same assumption that the ID is valid also after closing the handle. The Microsoft STL also has got a similar pattern, with a function that opens a file temporarily only to get a hold of the supposedly unique ID of the file: https://github.com/microsoft/STL/blob/be29af22c049774ae93f2c33e4eb5d801e12216c/stl/src/filesystem.cpp#L441-L453

**Comment by mstorsjo** [comment]
> > Found an old report #22079 about the same issue.
> 
> Thanks, that was a good find. And the observation that the ID might be unique only as long as the HANDLE is open is a good observation.
> 
> However it seems like others do make the same assumption that the ID is valid also after closing the handle. The Microsoft STL also has got a similar pattern, with a function that opens a file temporarily only to get a hold of the supposedly unique ID of the file: https://github.com/microsoft/STL/blob/be29af22c049774ae93f2c33e4eb5d801e12216c/stl/src/filesystem.cpp#L441-L453

I noticed that it's possible to trigger similar false positives for `std::filesystem::equivalent()` on such directory shares, so I filed https://github.com/microsoft/STL/issues/3571 to clarify whether this should be considered a fault with the file shares or with the use of `GetFileInformationByHandle`.

**Comment by aganea** [comment]
@mstorsjo If you leaked that handle in https://gist.github.com/mstorsjo/74ea7b1769ae7043e0b784310a9a0d1e#file-uniqueid-cpp-L54 are you still able to repro?

**Comment by zmodem** [comment]
I don't have any further insights into Windows here, but I do worry that LLVM tools are trying to be too smart with files sometimes. For example, we've run into problems in the other direction, with two logically distinct files sharing the same inode causing surprising behaviour from Clang, e.g. https://reviews.llvm.org/D135220#3856148 and https://github.com/llvm/llvm-project/issues/58726

**Comment by mstorsjo** [comment]
> @mstorsjo If you leaked that handle in https://gist.github.com/mstorsjo/74ea7b1769ae7043e0b784310a9a0d1e#file-uniqueid-cpp-L54 are you still able to repro?

Nope, if I keep the handle open, it no longer reproes.

For things like the STL `std::filesystem::equivalent()` function, that'd be a simple fix (to just keep two handles open at the same time), but for our purposes, it's not quite as simple.

Given that the file IDs are unique even with a closed handle on almost all other filesystems, it's hard to say whether this is the intended usage of `GetFileInformationByHandle` or not. On the other hand, in the end, from the point of view of making LLVM work, we don't really care that much about the semantics about who's right here, the docs or the FS implementations. Thus, the question, is how we can make this more robust within LLVM.

**Comment by mstorsjo** [comment]
> I don't have any further insights into Windows here, but I do worry that LLVM tools are trying to be too smart with files sometimes.

Yep. For the case when LLD deduplicates input files too harshly (essentially leaving out most input files since they end up with the same unique ID), I can trace the code back to quite valid use of it from 4eed6cc43369e2f29a9f4ddfe843fb126657923b though (although I guess it could be possible to do the same based on pathnames too, but that'd be less robust in general).

**Comment by aganea** [comment]
I wonder if on Windows we couldn't keep that `HANDLE` open as a member of `sys::fs::UniqueID` (and inherently `file_status`) instead of closing it through the `ScopedFileHandle` in https://github.com/llvm/llvm-project/blob/main/llvm/lib/Support/Windows/Path.inc#L770. Would that solve the situation?

**Comment by aganea** [comment]
From what I gather, the FileIDs are generated by the mini-filter driver that corresponds to the underlying file system of the volume. In the case of FAT, the FileID is the offset to the file record; in the case of NTFS, the FileID is the MSF index. I would assume in the case of Remote Desktop, it is the Terminal Server driver that keeps a in-memory table of stable FileID, as long as file handles are open.

The current implementations (LLVM and MS-STL) assume the FileIDs are stable at all times, but the doc is quite clear about the fact that the handles have to be kept **_open_** in order for IDs to be stable.

> _To determine whether two **open handles** represent the same file, combine the identifier and the volume serial number for each file and compare them._

https://learn.microsoft.com/en-us/windows/win32/api/fileapi/ns-fileapi-by_handle_file_information
https://learn.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-file_id_info

Therefore both our implementation and MS-STL seem incorrect. We need to drag around the open HANDLEs if we wanted to cover all cases. It seems that currently only NTFS guarantees stable IDs and only by fluke, because of how its [internal structures are designed](https://hetmanrecovery.com/recovery_news/ntfs-file-system-structure.htm). Even in the case of FAT, the FileIDs will change if the disk drive is defragmented.

As for ReFS & 128-bit IDs, I suppose we could hash them with Blake3 (and include the volume info in the calculation) like we do for CodeView type records. In essence, we would keep `struct UniqueID { uint64_t Device, File; } on Unix, and have `struct UniqueID { uint64_t Handle, Hash; }` on Windows (and Close/Duplicate the handle where relevant). I have a patch for something close to this, it passes most of the monorepo tests, except for the clang part. If I manage to fix all tests, I'll post it.

**Comment by mstorsjo** [comment]
> > _To determine whether two **open handles** represent the same file, combine the identifier and the volume serial number for each file and compare them._

Wow, thanks for the emphasis. I've read that phrase a couple times while looking at this, but failed to notice the thing you're pointing out.

So with that in mind, there's no question left whether these filesystem drivers are wrong or not - they're not wrong, they just have even less stable identifiers than most other filesystems, but well within what's promised.

> Therefore both our implementation and MS-STL seem incorrect.

FWIW, libc++'s implementation of `std::filesystem` also contains similar logic. (And since libc++ is cross platform, just like LLVM itself, fixing it there is probably a bit more messy than in MS STL.)

> As for ReFS & 128-bit IDs, I suppose we could hash them with Blake3 (and include the volume info in the calculation) like we do for CodeView type records. In essence, we would keep `struct UniqueID { uint64_t Device, File; }` on Unix, and have `struct UniqueID { uint64_t Handle, Hash; }` on Windows (and Close/Duplicate the handle where relevant). I have a patch for something close to this, it passes most of the monorepo tests, except for the clang part. If I manage to fix all tests, I'll post it.

Awesome, thanks for looking into it!

Why do you think we need to hash the volume info into it - can't we keep the existing members and just add another one, e.g. `struct UniqueID { uint64_t Device, Hash, Handle; }`? From what I remember from looking into the use of `UniqueID` within LLVM, lots of places poke at individual `uint64_t Device` and `File` (or `Hash` in this case) (so extending them to a different size, or requiring a third member for the uniqueness comparison might be problematic), but as long as we don't create a new `UniqueID` in user code out of two extracted fields, that should be fine, no?

As for overhead/performance, my initial gut reaction was to stick the handle in a shared pointer, so we'd just keep one single handle, reference counted - but as the implementation of handles probably do that behind the scenes, you're probably right that it's better to just duplicate the handles whenever we need to copy a `UniqueID`.

And for the issue of potential increased resource usage (handle exhaustion etc) - I guess it's unnecessary to worry about it unless we know it's an issue; I don't offhand know about any usecase which would get `UniqueID`s for significantly more files than what the process actually would keep open at the same time anyway. (In general I believe the linker normally uses more open files at any time than the compiler, and the linker currently already keep all of them open at the same time already so it shouldn't be that much of an issue. If there's a limit on the number of actual open handles at any time, I guess this does end up chewing up O(N) more handles there though...

**Comment by aganea** [comment]
Your suggestion about refcounting the internals of `UniqueID` makes a lot of sense, I'll do that. Both `DuplicateHandle` and `CloseHandle` are going into kernel space and most likely we want to avoid that.

**Comment by aganea** [comment]
Please see https://reviews.llvm.org/D146490
