### ISSUE TITLE
RuntimeDyldELF doesn't clear `GOTOffsetMap` in `finalizeLoad()`, leading to invalid GOT relocations on AArch64

### ISSUE THREAD

**Issue by gmarkall** [llvm/llvm-project#61402]
# Problem

(This was originally discovered in numba/numba#8738 and is reduced down from there)

In `finalizeLoad()` the `GOTSectionID` and `CurrentGOTIndex` are reset to 0 with the intention of resetting everything related to GOT sections for the next object, but the `GOTOffsetMap` isn't cleared:

https://github.com/llvm/llvm-project/blob/ff11d6b6f6e27f5de389002b8f6102b6cf3ed474/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp#L2409-L2410

This leaves stale entries in the map, which can prevent the creation of a GOT section and/or entries in the GOT for subsequent objects. If a GOT relocation in a later object happens to match one in the map when `findOrAllocateGOTEntry()` checks to see if an entry already exists:

https://github.com/llvm/llvm-project/blob/ff11d6b6f6e27f5de389002b8f6102b6cf3ed474/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp#L2259-L2261

then it will never allocate a GOT entry for the new relocation (and doesn't allocate a GOT section at all, e.g. if there was just one GOT relocation). GOT relocations then get replaced with references to addresses in the first section (section 0), which is always invalid.

# Reproducer

This can manifest on AArch64 with the following example:

`accept_pointer.c`:

```c
void accept_pointer(void (*f)(void)) { f(); }
```

`send_pointer1.c`:

```c
void accept_pointer(void *p);
void f1();

void send_pointer1() {
  accept_pointer((void*)f1);
}

void f1() {}
```

`send_pointer2.c`:

```c
void accept_pointer(void *p);
void f1();

void send_pointer2() {
  accept_pointer((void*)f1);
}
```

All compiled with:

```shell
gcc -fPIC -c accept_pointer.c
gcc -fPIC -c send_pointer1.c
gcc -fPIC -c send_pointer2.c
```

(`gcc --version` is `gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0` on my system, but I don't think it matters too much for these simple files).

`send_pointer1()` and `send_pointer2()` have a GOT relocation to `f1()` in them:

```objdump
$ objdump -dr send_pointer1.o 

send_pointer1.o:     file format elf64-littleaarch64


Disassembly of section .text:

0000000000000000 <send_pointer1>:
   0:	a9bf7bfd 	stp	x29, x30, [sp, #-16]!
   4:	910003fd 	mov	x29, sp
   8:	90000000 	adrp	x0, 20 <f1>
			8: R_AARCH64_ADR_GOT_PAGE	f1
   c:	f9400000 	ldr	x0, [x0]
			c: R_AARCH64_LD64_GOT_LO12_NC	f1
  10:	94000000 	bl	0 <accept_pointer>
			10: R_AARCH64_CALL26	accept_pointer
  14:	d503201f 	nop
  18:	a8c17bfd 	ldp	x29, x30, [sp], #16
  1c:	d65f03c0 	ret

0000000000000020 <f1>:
  20:	d503201f 	nop
  24:	d65f03c0 	ret
```

```objdump
$ objdump -dr send_pointer2.o 

send_pointer2.o:     file format elf64-littleaarch64


Disassembly of section .text:

0000000000000000 <send_pointer2>:
   0:	a9bf7bfd 	stp	x29, x30, [sp, #-16]!
   4:	910003fd 	mov	x29, sp
   8:	90000000 	adrp	x0, 0 <f1>
			8: R_AARCH64_ADR_GOT_PAGE	f1
   c:	f9400000 	ldr	x0, [x0]
			c: R_AARCH64_LD64_GOT_LO12_NC	f1
  10:	94000000 	bl	0 <accept_pointer>
			10: R_AARCH64_CALL26	accept_pointer
  14:	d503201f 	nop
  18:	a8c17bfd 	ldp	x29, x30, [sp], #16
  1c:	d65f03c0 	ret
```

Loading these objects with `llvm-rtdyld` and entering `send_pointer2` results in a segfault:

```console
$ llvm-rtdyld --execute --entry send_pointer2 accept_pointer.o send_pointer1.o send_pointer2.o
loaded 'send_pointer2' at: 0xffffb18ac000
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/gmarkall/numbadev/install-llvm/main-20230310/bin/llvm-rtdyld --execute --entry send_pointer2 c/accept_pointer.o c/send_pointer1.o c/send_pointer2.o
Segmentation fault (core dumped)
```

When I attached with GDB and looked at the `send_pointer2` function, it looked like:

```assembly
    ffffafb6a078:       a9bf7bfd        stp     x29, x30, [sp, #-16]!
    ffffafb6a07c:       910003fd        mov     x29, sp
    ffffafb6a080:       90000000        adrp    x0, 0xffffafb6a000
    ffffafb6a084:       f9400000        ldr     x0, [x0]
    ffffafb6a088:       97ffffde        bl      0xffffafb6a000
    ffffafb6a08c:       d503201f        nop
    ffffafb6a090:       a8c17bfd        ldp     x29, x30, [sp], #16
    ffffafb6a094:       d65f03c0        ret
    ffffafb6a098:       d503201f        nop
    ffffafb6a09c:       d65f03c0        ret
```

The address in the `adrp` instruction, `0xffffafb6a000`, is the beginning of the first section, the `.text` section of `accept_pointer()`:

```gdb
(gdb) x/2x 0xffffafb6a000
0xffffafb6a000 <accept_pointer>:        0xd10043ff      0xf90007e0
```

i.e. offset 0 in section 0, which was mistaken for an already-extant GOT entry due to the stale entry in the `GOTOffsetMap`.

## Files

I couldn't attach the objects here because GitHub doesn't support them, but the object files can be obtained from https://github.com/gmarkall/numba-issue-8738/tree/main/c for convenience:

- [accept_pointer.o](https://github.com/gmarkall/numba-issue-8738/raw/main/c/accept_pointer.o)
- [send_pointer1.o](https://github.com/gmarkall/numba-issue-8738/raw/main/c/send_pointer1.o)
- [send_pointer2.o](https://github.com/gmarkall/numba-issue-8738/raw/main/c/send_pointer2.o)

# Patch / fix

I think the way to resolve this is to clear the `GOTOffsetMap` in `finalizeLoad()`:

```diff
diff --git a/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp b/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp
index 3c7f4ec47eb8..205ee5273b27 100644
--- a/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp
+++ b/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp
@@ -2407,6 +2407,7 @@ Error RuntimeDyldELF::finalizeLoad(const ObjectFile &Obj,
   }

   GOTSectionID = 0;
+  GOTOffsetMap.clear();
   CurrentGOTIndex = 0;

   return Error::success();
```

Making this change and rebuilding results in:

- The reproducer above running to completion as expected on AArch64.
- All the failing tests identified in numba/numba#8738 running successfully to completion on AArch64.
- All unit and regression tests (`ninja check-llvm` and `ninja check-llvm-unit`) green (no unexpected passes / fails) on AArch64 and x86_64.

I had planned to submit a patch - however, I'm not quite sure how to go about adding a test case for this scenario given that it involves multiple objects - can you provide any guidance here please?

**Comment by gmarkall** [comment]
> Thank you very much for for the detailed investigation. I hope to test https://reviews.llvm.org/D146938 out in the next day or two.

That's great - many thanks for looking at this!

> Out of interest -- Is Numba using ORC / LLJIT internally?

Not yet - moving to ORC / LLJIT is a work-in-progress, which has been helped along by your advice in the #jit channel of the LLVM Discord - many thanks for spending a little time there helping me over the last couple of months. 

The WIP PR for llvmlite (the binding used by Numba for LLVM) is: https://github.com/numba/llvmlite/pull/919

I have a Numba branch for which basic code generation with LLJIT works, but it wasn't yet stable enough to make a PR, and we need to figure out some lifetime / reference counting issues to move to ORC / LLJIT - the way Numba uses MCJIT is already a bit unorthodox, which is also complicating things somewhat.

**Comment by lhames** [comment]
> > Out of interest -- Is Numba using ORC / LLJIT internally?
>
> Not yet - moving to ORC / LLJIT is a work-in-progress, which has been helped along by your advice in the #jit channel of the LLVM Discord - many thanks for spending a little time there helping me over the last couple of months.

Ok. Great to hear that it's being worked on, and you're very welcome. :)

Is there anything further to do on this issue? If not I'll close it out.

**Comment by gmarkall** [comment]
There's nothing left to do - the Numba / llvmlite RC is working with no issues reported with this patch. I think this issue is good to close - many thanks for wrapping this up!

**Comment by aaronpuchert** [comment]
What do you think about picking this to `release/16.x`, assuming it is still open?

**Comment by aaronpuchert** [comment]
Though perhaps llvmlite will have switched to ORC JIT before it supports LLVM 16?

**Comment by gmarkall** [comment]
> What do you think about picking this to `release/16.x`, assuming it is still open?

I'm not sure if you're asking me, but I don't have much of an opinion on it since the places where llvmlite normally gets built (the Numba conda channel, conda-forge, and possibly some Linux distros) have this patch applied to LLVM 14 to suit llvmlite anyway.

> Though perhaps llvmlite will have switched to ORC JIT before it supports LLVM 16?

Possibly it will have, but this issue isn't specific to llvmlite - anything that uses RuntimeDyldELF on AArch64 can be affected (for example the reproducer in the issue description has no connection to llvmlite).

**Comment by aaronpuchert** [comment]
> the places where llvmlite normally gets built (the Numba conda channel, conda-forge, and possibly some Linux distros) have this patch applied to LLVM 14 to suit llvmlite anyway.

Yes, we'll have it as well. But if we port it back officially, we could drop it downstream.

> Possibly it will have, but this issue isn't specific to llvmlite - anything that uses RuntimeDyldELF on AArch64 can be affected

That's a good point, maybe that warrants a backport.

**Comment by gmarkall** [comment]
> Yes, we'll have it as well. But if we port it back officially, we could drop it downstream.

Just out of interest, who does "we" refer to? Are you maintaining a Linux distro or other build of LLVM somewhere? (I checked your Github profile and googled you, but I couldn't tell)

**Comment by aaronpuchert** [comment]
> Just out of interest, who does the last "we" refer to? Are you maintaining a Linux distro or other build of LLVM somewhere?

I'm helping to maintain LLVM for [openSUSE](https://www.opensuse.org/) Linux, and came here via a [bug on our bug tracker](https://bugzilla.opensuse.org/show_bug.cgi?id=1212264). I'm not really involved with `llvmlite`, but I [came across it before](https://github.com/numba/llvmlite/issues?q=commenter%3Aaaronpuchert).
