### ISSUE TITLE
Compiling atomic builtins for NVPTX emits unhelpful warnings

### ISSUE THREAD

**Issue by jhuber6** [llvm/llvm-project#61410]
Using some atomic builtins emits unhelpful warnings, warning that the maximum lock free size is zero.

```c
void foo(int *ptr) {
    __atomic_store_n(ptr, 1, __ATOMIC_RELAXED);
}
```
```console
$ clang foo.c --target=nvptx64-nvidia-cuda
<foo.c>:2:5: warning: large atomic operation may incur significant performance penalty; the access size (4 bytes) exceeds the max lock-free size (0  bytes) [-Watomic-alignment]
    __atomic_store_n(ptr, 1, __ATOMIC_RELAXED);
    ^
```
And in Godbolt https://godbolt.org/z/3be3rjE9f.

**Comment by Artem-B** [comment]
NVPTX typically derives MaxAtomicInlineWidth from the host, which requires `--aux-triple`.
You're compiling in stand-alone mode and that's what's causing the warning.

AFAICT NVPTX supports 32 and 64-bit atomics, so we should set MaxAtomicInlineWidth to 8 and, possibly, clamp to that value when we derive it from host.

https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/Targets/NVPTX.cpp#L141

**Comment by jhuber6** [comment]
> NVPTX typically derives MaxAtomicInlineWidth from the host, which requires `--aux-triple`. You're compiling in stand-alone mode and that's what's causing the warning.
I see, we can probably base it off of the default device triple if nothing else. Is this even relevant now that Nvidia is retiring 32-bit support?

**Comment by Artem-B** [comment]
For combined host/device compilation we need to keep the value the same. I don't think that we can always assume that the 'cheap' atomics size always matches nominal architecture width.

For the combined compilation (AKA CUDA) we still want to retrieve the value from the host, but for stand-alone mode hardcoding it as 8 should do. We may eventually need to tune it for specific GPU variants. I haven't looked at the SASS atomic instructions produce on different architectures. I would not be surprised to see 64-bit ops to be implemented as a pair of 32-bit updates in a loop.

**Comment by jhuber6** [comment]
Any update on this? I can try to make a patch if you don't have the time.

**Comment by Artem-B** [comment]
A patch would be welcome, as the bug is somewhat low on my todo list.

**Comment by jhuber6** [comment]
https://reviews.llvm.org/D146750
