### ISSUE TITLE
clang crash on invalid parameter type of a lambda

### ISSUE THREAD

**Issue by usx95** [llvm/llvm-project#61441]
```cpp
template <class>
void foo() {
  [&](__fp16) { return 0; };
}

void bar() { foo<int>(); }
```
https://godbolt.org/z/s9xh48aTT
We recently saw this crash coming up in clangd (on invalid code).

**Comment by shafik** [comment]
In `GetFullTypeForDeclarator` we set the type of the parameter to an invalid type while issuing the diagnostic:

```cpp
                } else if (!S.getLangOpts().NativeHalfArgsAndReturns &&
                       !S.Context.getTargetInfo().allowHalfArgsAndReturns()) {
              S.Diag(Param->getLocation(),
                diag::err_parameters_retval_cannot_have_fp16_type) << 0;
              D.setInvalidType();
            }
```

then later on when we retrieve `TypeSourceInfo`

```cpp
    TypeSourceInfo *OldCallOpTSI = E->getCallOperator()->getTypeSourceInfo();
    FunctionProtoTypeLoc OldCallOpFPTL =
        OldCallOpTSI->getTypeLoc().getAs<FunctionProtoTypeLoc>();
```

we can see that `OldCallOpFPTL.getParam(0)` gives us `nullptr` which is not expected by by the subsequent code and from what I can tell from how this code is used in other places this should not be.

Removing `D.setInvalidType();` fixes the crash but I am not sure if this indicates a larger issue or not.

**Comment by shafik** [comment]
PR: https://reviews.llvm.org/D146426
