### ISSUE TITLE
[C++20] [Modules] default -fmodule-output of partitions is inconsistent with -fprebuilt-module-path 

### ISSUE THREAD

**Issue by huangqinjin** [llvm/llvm-project#61456]
### Example

**interface.cppm**
```cxx
export module hello:interface;
export void hello() {}
```

**hello.cppm**
```cxx
export module hello;
export import :interface;
```

**main.cpp**
```cxx
import hello;
int main() { hello(); }
```

### Problem

GCC is able to compile them in single command:
```shell
g++ -std=c++20 -fmodules-ts -x c++ interface.cppm hello.cppm main.cpp -o hello
```

But clang is **not** able to achieve by the command:
```shell
clang++ -std=c++20 -fmodule-output -fprebuilt-module-path=. interface.cppm hello.cppm main.cpp -o hello
```

### Cause
The `-fmodule-output` filename of partition `interface.cppm` is `interface.pcm` by default. (GCC & MSVC are both default to `hello-interface.gcm` / `hello-interface.ifc`). But `-fprebuilt-module-path` requires `hello-interface.pcm`.

**Comment by ChuanqiXu9** [comment]
This is not a bug and by design. (You can say it is a defect.) Given we expect to use modules with build systems generally, this may not be a big deal.
