### ISSUE TITLE
Clang should not re-write .pcm for C++ module if it's unchanged

### ISSUE THREAD

**Issue by rnikander** [llvm/llvm-project#61457]
This came up on the CMake discussion forum. I'm trying to get my project working with C++20 modules, and I noticed everything recompiling when I changed something in the private module segment (ie, after `module :private`)

https://discourse.cmake.org/t/c-20-modules-update/7330/41

I'm not 100% sure myself whether Clang should do this, but it seems like it should. It seems like the compiler is in a better position to do this than the build tool. (?)

**Comment by koplas** [comment]
Is there any workaround for this issue? I tried using `ccache` but it reports only uncacheable calls and my config file only contains `sloppiness = modules`.

**Comment by ChuanqiXu9** [comment]
> Is there any workaround for this issue? I tried using `ccache` but it reports only uncacheable calls and my config file only contains `sloppiness = modules`.

In my downstream, I have a dirty workaround in preprocessor. But I don't want to contribute that. I think the proper solution should live on the  ccache side and I've filed an issue for that.

**Comment by iains** [comment]
agreed, this would require actions that are very "out of band" for the preprocessor or FE.  Some sort of "write temp; move if changed" seems to be required.

Perhaps you could implement something like that in your build system scripts?
 (i.e. specify a temp output for the pcm and then do a move-if-changed on that)

**Comment by koplas** [comment]
I am currently using cmake and ninja. Unfortunately, ninja does not seem to support custom extra build time commands that would allow a move-if-changed step: https://gitlab.kitware.com/cmake/cmake/-/issues/22922#note_1085090
I guess the easiest way is to write a wrapper script around clang.

**Comment by ChuanqiXu9** [comment]
Now I feel clang shouldn't do this since clang would still write the .o object files if the source file is unchanged, right?

Then we should keep the consistency.

**Comment by ChuanqiXu9** [comment]
Just now I did a simple experiment with .o files and the result shows that the clang would still write the .o file if the it is unchanged.

Then I feel we should keep consistent with that. Ideally, I think it would be the job of tools like ccache in the end of the day.

I'd like to close the issue. If you have any different thoughts, feel free to reopen this.

**Comment by mathstuf** [comment]
Note that `make` just assumes that the output of a recipe is updated. Only `ninja` would really be benefiting here with its `restat = 1` feature (or other tools with similar features).

**Comment by mathstuf** [comment]
Oh, I think one reason Fortran modules may not have updated timestamps is because, IIRC, they embedded their timestamps into the module files, so they were never the same even content-wise.

**Comment by iains** [comment]
and AFAIR we had a mode where timestamps could be embedded in (at least) PCH.

I agree with @ChuanqiXu9 , this is not a job for the compiler;
you ask the compiler to compile stuff, it does it;
 it is the job of the build system to decide when to ask the compiler to run (and it is expected that all the outputs will be produced).
Anything else seems like sliding back towards bringing build system actions into the compiler.
