### ISSUE TITLE
[clang][ExtractAPI] Declaration fragments for Obj-C lightweight generics on `id` includes extra pointer indirection

### ISSUE THREAD

**Issue by daniel-grumberg** [llvm/llvm-project#61479]
A common pattern in Objective-C framework code is to have one object delegate to another.
The delegate object conforms to a protocol and is attached to the delegating object via a property. 

The declaration fragments for this pattern in ExtractAPI are wrong. for a property that returns `id <AProtocol>` the declaration fragments are `id <AProtocol> *`, which is incorrect as it implies “pointer to pointer to object” where id is “pointer to object”. We would expect the declaration fragments to look exactly like the sources in this instance.

**Comment by chaitanyav** [comment]
@daniel-grumberg can i look into this

```
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:Qoobjc(pl)Protocol",
          "spelling": "id<Protocol>"
        },
        {
          "kind": "text",
          "spelling": " * "
        },
```

**Comment by daniel-grumberg** [comment]
Yes go for it!
