### ISSUE TITLE
[clang] [ExtractAPI] Declaration fragments for properties include spurious additional attributes.

### ISSUE THREAD

**Issue by daniel-grumberg** [llvm/llvm-project#61478]
Declaration fragments for properties include additional property attributes that were not specified in the sources

```obj-c
@property(nonatomic) BOOL MyProperty;
```

instead the declaration fragments in the generated symbol graph looks

```obj-c
@property(nonatomic, assign, unsafe_unretained, readwrite) BOOL MyProperty;
```

Note the extra assign, unsafe_unretained, readwrite property attributes in the declaration fragments.

**Comment by Unique-Usman** [comment]
Hi Daniel, 

Basically the correction that needs to be done here is to replace *@property(nonatomic) BOOL MyProperty;* in the code base to *(nonatomic, assign, unsafe_unretained, readwrite) BOOL MyProperty;*?

Kindly guide me through, thank you sir.

**Comment by Unique-Usman** [comment]
> clang -extract-api -x objective-c-header ./code.h -o ./output.symbols.json

Hello Daniel, 

I was able to build the llvm and the clnag, after creating the code.h file and running the above command, no ./output.symbols.json was generated.

**Comment by Unique-Usman** [comment]
Also, Kindly point out where the file where the correction need to be made sir. 

Thank you.

**Comment by daniel-grumberg** [comment]
Did you run the command on the just built clang? Since this feature is fairly new, it might not have made it to your Linux's clang distribution.

**Comment by Unique-Usman** [comment]
Yes. 
I am sorry for disturbing you, I am pretty new to the world of Open source. If there is anything I can learn from, kindly suggest. Thank you.

**Comment by daniel-grumberg** [comment]
OK can you send me the output of the command?

**Comment by Unique-Usman** [comment]
![Screenshot from 2023-03-21 20-26-30](https://user-images.githubusercontent.com/86585626/226646911-7a364ec8-0102-4c68-b126-68b12bad9ff0.png)



(base) uniqueusman@uniqueusman-Nitro-AN515-57:~/llvm-project/build$ clang -extract-api -x objective-c-header ./code.h -o ./output.symbols.json
(base) uniqueusman@uniqueusman-Nitro-AN515-57:~/llvm-project/build$ cd ./output.symbols.json
bash: cd: ./output.symbols.json: No such file or directory
(base) uniqueusman@uniqueusman-Nitro-AN515-57:~/llvm-project/build$ vi ./output.symbols.json

**Comment by daniel-grumberg** [comment]
You didn't use your just built clang, to do that you need to run the one in `~/llvm-project/build/bin/clang`

**Comment by Unique-Usman** [comment]
![Screenshot from 2023-03-21 21-24-48](https://user-images.githubusercontent.com/86585626/226665931-1c9d9a60-efb1-44fb-b8ed-accc929ba49d.png)

This is what I get and I added code.h in the current folder

**Comment by Unique-Usman** [comment]
![Screenshot from 2023-03-21 21-42-58](https://user-images.githubusercontent.com/86585626/226670986-53fab729-df5b-449d-9697-f7d30c2198d5.png)

Thanks, the /output.symbols.json file has been generated.

**Comment by daniel-grumberg** [comment]
Well does anything in it seem wrong as mentioned in this issue?

**Comment by Unique-Usman** [comment]
I do not think so sir, what is your take sir?

**Comment by daniel-grumberg** [comment]
```json
"declarationFragments": [
        {
          "kind": "keyword",
          "spelling": "@property"
        },
        {
          "kind": "text",
          "spelling": " ("
        },
        {
          "kind": "keyword",
          "spelling": "nonatomic"
        },
        {
          "kind": "text",
          "spelling": ", "
        },
        {
          "kind": "keyword",
          "spelling": "assign"
        },
        {
          "kind": "text",
          "spelling": ", "
        },
        {
          "kind": "keyword",
          "spelling": "unsafe_unretained"
        },
        {
          "kind": "text",
          "spelling": ", "
        },
        {
          "kind": "keyword",
          "spelling": "readwrite"
        },
        {
          "kind": "text",
          "spelling": ") "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:I",
          "spelling": "int"
        },
        {
          "kind": "text",
          "spelling": " "
        },
        {
          "kind": "identifier",
          "spelling": "MyProperty"
        }
      ],
```
There are additional property attributes here than specified in the sources.

**Comment by Unique-Usman** [comment]
Do not you think the additional property attributes are just the default property which will be overwritten if  the value is passed?

**Comment by daniel-grumberg** [comment]
They are the default, but the user did not write them. For declaration fragments, the aim is to show the user how the symbol was declared without additional noise. If an attribute is the default, we don't want to expose it in the declaration fragments.

**Comment by Unique-Usman** [comment]
Thank you very much sir, I really appreciate. I now understand the problem clearly. 

The next step is to make the output generated by clang -extract-api to only show the user the attribute they write and abstract the other default attribute from them. 

My question now is, where do I find the code base of the clang -extract-api that is generating the output in the llvm-project? 

Thank you sir.

**Comment by Unique-Usman** [comment]
![Screenshot from 2023-03-22 16-19-27](https://user-images.githubusercontent.com/86585626/226881202-22faf2a4-d702-441e-867c-d764033b2cbc.png)
![Screenshot from 2023-03-22 16-19-15](https://user-images.githubusercontent.com/86585626/226881234-6637ba9d-d043-4a38-9d88-a34f551c9798.png)

I checked through the DeclarationFragments.cpp and I saw this part of the code. I am currently hunged at this point

**Comment by Unique-Usman** [comment]
Also sir, if I make any change to the DeclarationFragments.cpp, do I need to do anything to see the effect of my change, I  have tried out couple of changes but, all to no effect.  Thank you.

**Comment by daniel-grumberg** [comment]
Well you would need to build the code, and run clang that is located in your build directory, i.e. `build/bin/clang`. If you can't see a change in the example we looked at earlier, then that means the code you wrote doesn't resolve the issue.

**Comment by Unique-Usman** [comment]
{
  "metadata": {
    "formatVersion": {
      "major": 0,
      "minor": 5,
      "patch": 3
    },
    "generator": "clang version 17.0.0 (https://github.com/llvm/llvm-project.git 23ea2c4f4a928f196730f1e71617ceccb677ce32)"
  },
  "module": {
    "name": "",
    "platform": {
      "architecture": "x86_64",
      "operatingSystem": {
        "name": "linux"
      },
      "vendor": "unknown"
    }
  },
  "relationships": [
    {
      "kind": "memberOf",
      "source": "c:objc(cs)MyInterface(py)MyProperty",
      "target": "c:objc(cs)MyInterface",
      "targetFallback": "MyInterface"
    }
  ],
  "symbols": [
    {
      "accessLevel": "public",
      "declarationFragments": [
        {
          "kind": "keyword",
          "spelling": "@interface"
        },
        {
          "kind": "text",
          "spelling": " "
        },
        {
          "kind": "identifier",
          "spelling": "MyInterface"
        }
      ],
      "identifier": {
        "interfaceLanguage": "objective-c",
        "precise": "c:objc(cs)MyInterface"
      },
      "kind": {
        "displayName": "Class",
        "identifier": "objective-c.class"
      },
      "location": {
        "position": {
          "character": 12,
          "line": 1
        },
        "uri": "file:///home/uniqueusman/llvm-project/build/bin/code.h"
      },
      "names": {
        "navigator": [
          {
            "kind": "identifier",
            "spelling": "MyInterface"
          }
        ],
        "subHeading": [
          {
            "kind": "identifier",
            "spelling": "MyInterface"
          }
        ],
        "title": "MyInterface"
      },
      "pathComponents": [
        "MyInterface"
      ]
    },
    {
      "accessLevel": "public",
      "declarationFragments": [
        {
          "kind": "keyword",
          "spelling": "@property"
        },
        {
          "kind": "text",
          "spelling": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:I",
          "spelling": "int"
        },
        {
          "kind": "text",
          "spelling": " "
        },
        {
          "kind": "identifier",
          "spelling": "MyProperty"
        }
      ],
      "identifier": {
        "interfaceLanguage": "objective-c",
        "precise": "c:objc(cs)MyInterface(py)MyProperty"
      },
      "kind": {
        "displayName": "Instance Property",
        "identifier": "objective-c.property"
      },
      "location": {
        "position": {
          "character": 15,
          "line": 2
        },
        "uri": "file:///home/uniqueusman/llvm-project/build/bin/code.h"
      },
      "names": {
        "navigator": [
          {
            "kind": "identifier",
            "spelling": "MyProperty"
          }
        ],
        "subHeading": [
          {
            "kind": "identifier",
            "spelling": "MyProperty"
          }
        ],
        "title": "MyProperty"
      },
      "pathComponents": [
        "MyInterface",
        "MyProperty"
      ]
    }
  ]
}

**Comment by Unique-Usman** [comment]
Hello sir, 

This is the  content of the ./output.symbols.json that I am generating right now, I think I am able to resolve the issue. 

Sir, what is the next thing I need to do, to be able to ensure that I was able to resolve the matter?

Thank you sir.

**Comment by zixu-w** [comment]
> Hello sir,
> 
> This is the content of the ./output.symbols.json that I am generating right now, I think I am able to resolve the issue.
> 
> Sir, what is the next thing I need to do, to be able to ensure that I was able to resolve the matter?
> 
> Thank you sir.

🎉  Hit us with a code review on Phabricator!
Check out contribution guides:
- https://www.llvm.org/docs/Contributing.html
- https://www.llvm.org/docs/CodeReview.html
- https://www.llvm.org/docs/Phabricator.html

**Comment by Unique-Usman** [comment]
https://reviews.llvm.org/D146759 Kindly, help check for review

**Comment by Unique-Usman** [comment]
![Screenshot from 2023-03-25 18-15-23](https://user-images.githubusercontent.com/86585626/227718070-f390e770-1658-4491-825f-8f5525b1ecbb.png)

Hi @zixu-w , looking at line 629 are we meant to use getPropertyAttributesAsWritten() instead of getPropertyAttributes()?

2. for the RenderAttribute function, looking at line 642, is this where we check for the property specify in the source, also the & in (Attributes & Kind), shouldn't it be &&.

**Comment by Unique-Usman** [comment]
Hi @zixu-w , I already made the change and it seems to work,  I have updated my revision, kindly check so that I will know the further step to take. Thank you very much.

**Comment by Unique-Usman** [comment]
Hi @zixu-w , I already made the change and it seems to work, I have updated my revision, kindly check so that I will know the further step to take. Thank you very much.

**Comment by Unique-Usman** [comment]
@zixu-w kindly review this https://reviews.llvm.org/D146759. Thank you.
