### ISSUE TITLE
[clang][ExtractAPI] Declaration fragments for TagDecl types defined in a typedef is incomplete

### ISSUE THREAD

**Issue by daniel-grumberg** [llvm/llvm-project#61482]
enums and structs declared inside typedefs have incorrect declaration fragments, where the typedef keyword and other syntax is missing.

For the following struct:

```obj-c
typedef struct Test {
    int hello;
} Test;
```

The produced declaration is:

```json
"declarationFragments": [
  {
    "kind": "keyword",
    "spelling": "struct"
  },
  {
    "kind": "text",
    "spelling": " "
  },
  {
    "kind": "identifier",
    "spelling": "Test"
  }
],
```

instead the declaration fragments should represent the following
```obj-c
typedef struct Test {
    …
} Test;
```

**Comment by samuelmaina** [comment]
I am new and don't understand the question clearly. Do we need to produce  nested output to represent  complex language segement?

**Comment by Ruturaj4** [comment]
working on this.

**Comment by Unique-Usman** [comment]
@Ruturaj4 are you still working on this issue?

 I will like to work on it.

**Comment by Ruturaj4** [comment]
@Unique-Usman hi, it has already been accepted, but not yet committed that's why it is still pending.

**Comment by Unique-Usman** [comment]
@Ruturaj4 ok

**Comment by Ruturaj4** [comment]
completed. https://reviews.llvm.org/rG3ac550984e83c2478772c800b1f1b5cffd63a10d
