### ISSUE TITLE
The default build in libc++ documentation fails on macOS

### ISSUE THREAD

**Issue by rnikander** [llvm/llvm-project#61488]
I'm trying to follow the instructions here: https://libcxx.llvm.org/BuildingLibcxx.html

The first section is called "The default build". The command fails for me. Maybe the documentation needs to be updated.

```console
% cmake -G Ninja -S runtimes -B build -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind"
...
...
CMake Error at /Users/rob/Dev/llvm-project/libunwind/src/CMakeLists.txt:109 (message):
  Compiler doesn't support generation of unwind tables if exception support
  is disabled.  Building libunwind DSO with runtime dependency on C++ ABI
  library is not supported.
```

I'm on macOS Ventura 13.2.1.

**Comment by mordante** [comment]
Are you using CMake 3.26? If yes, then this is a known problem and not MacOS specific. I've a patch here https://reviews.llvm.org/D145596. This is abandoned since @petrhosek is working on a better fix, but the patch fixes the issue for me.

**Comment by rnikander** [comment]
> Are you using CMake 3.26?

Yes, I have CMake from HEAD, in order to use the latest C++ modules stuff.

**Comment by ldionne** [comment]
This works for me now. Please reopen if you still have issues with the documented default build.
