### ISSUE TITLE
Error when using Apple's simd.h header with C++ modules

### ISSUE THREAD

**Issue by rnikander** [llvm/llvm-project#61493]
I don't know if this a problem with Clang or with Apple's header or what. But I'm not able to include the simd vector types in certain module files. Here is a minimal example.  I'm using the latest Clang.

`ModuleWithVectors.cc`
```c++
module;

#include <simd/simd.h>

export module ModWithVectors;

export simd::double2 foo() {
    // The include simd.h seems to work as expected for this code.
    double x = 3.0;
    simd::double2 vec = simd_make_double2(x, x);
    return vec;
}
```

`ModImpl.cc`
```c++
module;

#include <simd/simd.h>

module ModWithVectors;

// #include <simd/simd.h>

simd::double2 foo_impl() {
    double x = 3.0;
    simd::double2 vec = simd_make_double2(x, x);   // error about 'no matching function call'
    return vec;
}
```

```sh
CC="/Users/rob/Dev/llvm-project/build/bin/clang++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -std=c++2b"
$CC -x c++-module ModWithVectors.cc --precompile -o ModWithVectors.pcm
$CC -c -fprebuilt-module-path=. ModImpl.cc -o ModImpl.cc.o
```

Fails with:
```console
ModImpl.cc:11:25: error: no matching function for call to 'simd_make_double2'
    simd::double2 vec = simd_make_double2(x, x);
                        ^~~~~~~~~~~~~~~~~
1 error generated.
```

If I try putting the include after the module declaration, I get other errors.

```console
In file included from /Users/rob/Dev/llvm-project/build/lib/clang/17/include/x86gprintrin.h:40:
/Users/rob/Dev/llvm-project/build/lib/clang/17/include/cmpccxaddintrin.h:19:9: error: declaration of '_CMPCCX_ENUM' in module ModWithVectors follows declaration in the global module
typedef enum {
```

The declaration, in `simd/vector_make.h`, looks like this. That should be usable in `ModImpl.cc`, no?

```c++
/*! @abstract Concatenates `x` and `y` to form a vector of two 64-bit
 *  floating-point numbers.                                                   */
static inline SIMD_CFUNC simd_double2 simd_make_double2(double x, double y) {
  simd_double2 result;
  result.x = x;
  result.y = y;
  return result;
}
```

**Comment by ChuanqiXu9** [comment]
@rnikander could you try again with trunk?

**Comment by rnikander** [comment]
@ChuanqiXu9 It compiles and runs without error.

**Comment by rnikander** [comment]
@ChuanqiXu9 I noticed the simd types still aren't working like they used to. For example, I can't multiply a matrix times a vector.


```c++
#include <simd/simd.h>
#include <iostream>
import ModWithVectors;   // comment this out and the code works again.
int main() {
    //  ⎡ 1 2 ⎤ * ⎡1⎤ = ⎡5⎤
    //  ⎣ 3 4 ⎦   ⎣2⎦   ⎣1⎦
    simd::float2 col1{1, 3};
    simd::float2 col2{2, 4};    
    simd::float2x2 mat(col1, col2);
    simd::float2 vec{1, 2};
    auto v = mat * vec;
    std::cout << v.x << ' ' << v.y << "\n";
    return 0;
}

```

```text
/Users/rob/Workspace/MonoRepo/Learning/ModBug3/main.cc:22:18: error: cannot convert between vector and non-scalar values ('simd::float2x2' and 'simd::float2' (aka 'simd_float2'))
    auto v = mat * vec;
             ~~~ ^ ~~~
```

**Comment by ChuanqiXu9** [comment]
> @ChuanqiXu9 I noticed the simd types still aren't working like they used to. For example, I can't multiply a matrix times a vector.
> 
> ```c++
> #include <simd/simd.h>
> #include <iostream>
> import ModWithVectors;   // comment this out and the code works again.
> int main() {
>     //  ⎡ 1 2 ⎤ * ⎡1⎤ = ⎡5⎤
>     //  ⎣ 3 4 ⎦   ⎣2⎦   ⎣1⎦
>     simd::float2 col1{1, 3};
>     simd::float2 col2{2, 4};    
>     simd::float2x2 mat(col1, col2);
>     simd::float2 vec{1, 2};
>     auto v = mat * vec;
>     std::cout << v.x << ' ' << v.y << "\n";
>     return 0;
> }
> ```
> 
> ```
> /Users/rob/Workspace/MonoRepo/Learning/ModBug3/main.cc:22:18: error: cannot convert between vector and non-scalar values ('simd::float2x2' and 'simd::float2' (aka 'simd_float2'))
>     auto v = mat * vec;
>              ~~~ ^ ~~~
> ```

Weird, would you like to give a reproducer without any headrers (e.g., no <simd.h> and no <iostream>) and file an another issue?

**Comment by rnikander** [comment]
> Weird, would you like to give a reproducer without any headrers (e.g., no <simd.h> and no ) and file an another issue?

Here it is: https://github.com/llvm/llvm-project/issues/61807
