### ISSUE TITLE
`ninja check-all` failed for llvm12.0.0

### ISSUE THREAD

**Issue by mzwsw-wjm** [llvm/llvm-project#61490]
I use wsl2 under win10 to build llvm. The linux edition is Ubuntun22.04 and the llvm edition is 12.0.0. I use the following command:
`cmake -G Ninja -DLLVM_ENABLE_PROJECTS=clang ../llvm -DCMAKE_BUILD_TYPE=Release`
`ninja`
`ninja check-all`
And i meet the following error:
![BTNNCYKTL4PX1~6W(%$HF@K](https://user-images.githubusercontent.com/53400616/226092852-04a9a320-8b6c-4a1e-8697-5bf1b7f55f38.png)

The following is the edition of the tools i use:
![KU4B XC@8 N@@H2Z4LW%CJ2](https://user-images.githubusercontent.com/53400616/226092856-7af60999-8154-48b4-98c0-9e5b1497e9bd.png)

I want to know the reason for the error. Thank you!

**Comment by nikic** [comment]
LLVM 12 is not supported, please try LLVM 16.

Besides, this is not actionable without the detailed failure output that should be just above the `***`.
