### ISSUE TITLE
JITTests segfaults when built with gcc 3.4.6

### ISSUE THREAD

**Issue by edwintorok** [llvm/llvm-project#6149]
|  |  |
| --- | --- |
| Bugzilla Link | [5777](https://llvm.org/bz5777) |
| Version | unspecified |
| OS | Linux |
| Attachments | [crash log](https://user-images.githubusercontent.com/92601246/143740380-dd8a51c9-00e5-42e1-a58d-c09010028f43.gz), [config.log](https://user-images.githubusercontent.com/92601246/143740382-7502a7bd-17b5-4bcf-badc-2688b40b8117.gz) |

## Extended Description 
On CentOS 4 (and RHEL4), i686 after building LLVM in release mode (ENABLE_OPTIMIZED=1), JITTests fails due to a segfault:

[edwin@localhost JIT]$ Release/JITTests
[==========] Running 17 tests from 4 test cases.
[----------] Global test environment set-up.
[----------] 1 test from JIT
[ RUN      ] JIT.GlobalInFunction
Stack dump:
0.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@F1'
Segmentation fault

I rebuilt CodeGen, Target, and ExecutionEngine with
make ENABLE_OPTIMIZED=1 OPTIMIZE_OPTION="-O2 -g", and compiled the unittest with
make ENABLE_OPTIMIZED=1 OPTIMIZE_OPTION="-O2 -g" KEEP_SYMBOLS=1 to get a backtrace in gdb:

Starting program: /home/edwin/llvm/unittests/ExecutionEngine/JIT/Release/JITTests 
[Thread debugging using libthread_db enabled]
[New Thread -1208768832 (LWP 9303)]
[==========] Running 17 tests from 4 test cases.
[----------] Global test environment set-up.
[----------] 1 test from JIT
[ RUN      ] JIT.GlobalInFunction

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread -1208768832 (LWP 9303)]
llvm::SelectionDAG::getGlobalAddress (this=0x8fe9298, GV=0x8fe9298, Offset=0, 
    isTargetGA=true, TargetFlags=Variable "TargetFlags" is not available.
)
    at /home/edwin/llvm/include/llvm/Support/Recycler.h:41
41	  static void setPrev(RecyclerStruct *t, RecyclerStruct *p) { t->Prev = p; }
Current language:  auto; currently c++
(gdb) bt
#&#8203;0  llvm::SelectionDAG::getGlobalAddress (this=0x8fe9298, GV=0x8fe9298, 
    Offset=0, isTargetGA=true, TargetFlags=Variable "TargetFlags" is not available.
)
    at /home/edwin/llvm/include/llvm/Support/Recycler.h:41
#&#8203;1  0x08389b4f in llvm::X86TargetLowering::LowerGlobalAddress (this=0x8fe9298, 
    GV=0x8fd63b4, dl={Idx = 150823860}, Offset=4294967295, DAG=@0x0)
    at /home/edwin/llvm/include/llvm/CodeGen/SelectionDAG.h:287
#&#8203;2  0xbfe4eb88 in ?? ()
#&#8203;3  0x083c3e94 in llvm::X86TargetLowering::LowerGlobalAddress (
    this=0xbfe4f518, Op={Node = 0x8fd3fd4, ResNo = 150902016}, DAG=@0x0)
    at /home/edwin/llvm/include/llvm/CodeGen/SelectionDAGNodes.h:1426
#&#8203;4  0x08fd3fd4 in ?? ()
#&#8203;5  0x083dd3d6 in llvm::X86TargetLowering::LowerOperation (this=0xbfe4f518, Op=
      {Node = 0x0, ResNo = 150902148}, DAG=@0x8bba0a0)
    at X86ISelLowering.cpp:7177
#&#8203;6  0xbfe4f828 in ?? ()
(gdb) quit

I also see lots of warnings like these during build:
include/llvm/CodeGen/JITCodeEmitter.h:172: warning: cast to pointer from integer of different size

Also in ExecutionEngineTests (although it passes) I see these warnings:
ExecutionEngineTest.cpp:106: warning: passing NULL used for non-pointer converting 3 of 'static testing::AssertionResult testing::internal::EqHelper< true>::Compare(const char*, const char*, const T1&, T2*) [with T1=int, T2=const llvm::GlobalValue]

Script started on Mon 14 Dec 2009 01:26:56 PM EET

System info:
$ uname -a
Linux localhost.localdomain 2.6.9-89.ELsmp #&#8203;1 SMP Mon Jun 22 12:32:43 EDT 2009 i686 i686 i386 GNU/Linux

$ gcc -v
Reading specs from /usr/lib/gcc/i386-redhat-linux/3.4.6/specs
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --disable-checking --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-java-awt=gtk --host=i386-redhat-linux
Thread model: posix
gcc version 3.4.6 20060404 (Red Hat 3.4.6-11)

$ g++ -v
Reading specs from /usr/lib/gcc/i386-redhat-linux/3.4.6/specs
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --disable-checking --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-java-awt=gtk --host=i386-redhat-linux
Thread model: posix
gcc version 3.4.6 20060404 (Red Hat 3.4.6-11)

$ ld -v
GNU ld version 2.15.92.0.2 20040927

Attached is config.log, and the output of JITTests after I enabled --debug in it (llvm::DebugFlag = true).

**Comment by arsenm** [comment]
Ancient build issue with ancient gcc
