### ISSUE TITLE
clang disallows having a pointer to subobject as a template argument

### ISSUE THREAD

**Issue by brevzin** [llvm/llvm-project#61500]
Short example:
```cpp
template <int const*>
constexpr int f()
{
    return 0;
}

struct X { int i; };
constexpr auto x = X{.i=1};
constexpr int xs = f<&x.i>();
```

Clang rejects (every version I've tried), saying:

> candidate template ignored: invalid explicitly-specified argument for 1st template parameter

But `&x.i` should meet all the requirements here - it is a pointer to `int const` and the object in question does have static storage duration (so it should be a permitted result of a constant expression).

**Comment by shafik** [comment]
I believe this is: https://github.com/llvm/llvm-project/issues/56695

If I modify the code to use a templated struct I receive the same diagnostic: https://godbolt.org/z/n375vaqEM

```cpp
template <int const*>
constexpr int f() {
    return 0;
}

template <int const&>
constexpr int f2() {
    return 0;
}

template <int const*> struct W{};

struct X { int i; };
constexpr X x = X{.i=1};
constexpr int xs = f<&x.i>();
W<&x.i> w;

struct Z { int i; };
constexpr Z z{};
template<const int&> struct Y { };
constexpr int ys = f2<x.i>();
Y<x.i> y;
```

**Comment by brevzin** [comment]
@shafik Yep, same issue!

Should be C++20 tho (not 2b)

**Comment by cor3ntin** [comment]
Fixed in 18
