### ISSUE TITLE
Destroying a coroutine suspended in a list-initializer forgets some destructors

### ISSUE THREAD

**Issue by Alcaro** [llvm/llvm-project#61508]
```c++
#include <coroutine>
#include <stdio.h>

struct noisy {
    noisy(int) { puts("Hello"); }
    ~noisy() { puts("Goodbye"); }
    noisy(const noisy&) = delete;
    noisy(noisy&&) = delete;
};
struct simple {
  std::coroutine_handle<void> handle;
  struct promise_type {
    simple get_return_object() { return {std::coroutine_handle<promise_type>::from_promise(*this)}; }
    void return_void() {}
    void unhandled_exception() {}
    auto initial_suspend() noexcept { return std::suspend_never{}; }
    auto final_suspend() noexcept { return std::suspend_never{}; }
  };
};
simple struct_compound_expr() {
    noisy k[] = {
        1,
        (co_await std::suspend_always{}, 2 )
    };
}
int main() {
  auto routine = struct_compound_expr();
  routine.handle.destroy();
  return 0;
}
```
Compile and run with -std=c++20. https://godbolt.org/z/83Wa6j841

Expected result: Print Hello and Goodbye the same number of times (I think 1 each would be correct)

Actual: Prints 1 Hello, zero Goodbye

Alternatively, changing counter to std::unique_ptr gives a memory leak. https://godbolt.org/z/1YTW8nbKr

Testcase reduced/modified from <https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98401#c7>. The issue reproduces with both array list-initialization (as above) and aggregate-initialization of a struct.

edit: Deleted ASan dependency

**Comment by ChuanqiXu9** [comment]
This should be duplicate with https://github.com/llvm/llvm-project/issues/63818
