### ISSUE TITLE
Where is the llvmorg-16.0.0 windows executable download?

### ISSUE THREAD

**Issue by LukeSchoen** [llvm/llvm-project#61503]
I have been using clang.exe for years and LOVE IT!
I'd love to update to the latest but I can't find the build.

The release page lists Apple, freebsd but not windows:
https://discourse.llvm.org/t/llvm-16-0-0-release/69326/1

I hope this is just a mistake, looking forward to trying it!

Thanks alot

**Comment by asl** [comment]
LLVM project relies on volunteers for release binaries. The only definite and guaranteed artefact of the release is the source tarball. This time noone produces / tested windows binaries by the time of the release. Maybe they will be available later.

**Comment by LukeSchoen** [comment]
Thanks asl!

That makes a lot of sense, glad I wasn't just being blind!

Strongly suggest talking to whoever is necessary to either list the fact that windows builds aren't available or better yet find someone who can do the build and testing and get it up there, I know alot of people who wanting a clean good winows build.

Thanks again for letting me know, have a lovely day!

**Comment by DimitryAndric** [comment]
Please be patient, usually @zmodem delivers the windows builds pretty quickly, but this is a weekend. :)

**Comment by zmodem** [comment]
I'm glad to hear that folks are using the Windows releases.

The 16.0.0 binaries are ready now:
https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.0/LLVM-16.0.0-win32.exe
https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.0/LLVM-16.0.0-win64.exe

As Dimitry guessed, I wasn't able to build them during the weekend. Apologies for the delay.
