### ISSUE TITLE
[clang-format] array initializer one per line

### ISSUE THREAD

**Issue by abdelmaged** [llvm/llvm-project#61533]
I'd like to format array initializer to be one item per line, instead of all items in one line.

Example

I want this:

```
static char *categories[] = {
  "Alpha",
  "Beta",
  "Gamma",
  "Delta",
  "Epsilon",
  "Zeta"
};
```

Not this:
```
static char *categories[] = {"Alpha", "Beta", "Gamma", "Delta", "Epsilon", "Zeta"};
```

There has been multiple question on stackoverflow with no way to achieve this:
https://stackoverflow.com/questions/69537052/clang-format-array-initializer-one-per-line
https://stackoverflow.com/questions/38058627/clang-format-array-initialisers
https://stackoverflow.com/questions/39144255/clang-format-removes-new-lines-in-array-definition-with-designators
https://stackoverflow.com/questions/75572012/clang-format-designated-initializer-one-member-per-line

**Comment by rymiel** [comment]
The intended solution is to add a trailing comma (before the `}`)

**Comment by abdelmaged** [comment]
@rymiel this does not work for this case:

```
static char *categories[] = {
    "Alpha", "Beta",    "Gamma",    "Delta", "Epsilon", "Zeta",
    "Eta",   "Theta",   "Iota",     "Kappa", "Lambda",  "Mu",
    "Nu",    "Xi",      "Omicoron", "Pi",    "Rho",     "Sigma",
    "Tau",   "Upsilon", "Phi",      "Chi",   "Psi",     "Omega",
};
```

Please reopen, it there is no other way to make them per one line.

**Comment by FishHawk** [comment]
Please reopen this issue. The trailing comma does not fix the problem. Whether the code is formatted into a single line or multiple lines is determined by the line length
