### ISSUE TITLE
Is IR after pass "mem2reg" Memory-SSA or top-level-ssa?

### ISSUE THREAD

**Issue by ash1852** [llvm/llvm-project#61532]
Hi, as the question asked in the title, I would like to know after the "mem2reg" Pass, is IR Memory-SSA or Top-Level-SSA? Thank you for your effort.

**Comment by ash1852** [comment]
> MemorySSA is an analysis pass -- effectively an overlay on top of normal SSA form. IR cannot be "in Memory-SSA form". See https://llvm.org/docs/MemorySSA.html for more information.
> 
> Mem2Reg converts certain allocas into SSA form and has no relation to MemorySSA.

so after Mem2Reg, can I say IR is top-level SSA form?

**Comment by nikic** [comment]
IR is *always* in SSA form. Mem2Reg converts some allocas/loads/stores into values (in SSA form, just like everything). It does not necessarily convert all of them.

**Comment by ash1852** [comment]
ok, so at the beginning, IR is top-level SSA form? Because the descriptions I saw in the official documents are SSA Form, given that there are multiple forms of ssa, such as top-level ssa, hashed ssa, I want to confirm that the ssa from the beginning is top-level form

**Comment by nikic** [comment]
Where did you find the term "top-level SSA form"? I don't think this is standard terminology. IR is in the "usual" SSA form without any special extensions like MemorySSA, hashed SSA, e-SSA, etc.

**Comment by ash1852** [comment]
![image](https://user-images.githubusercontent.com/87304478/226336518-8656cb70-0192-44bb-884c-ef412946c12d.png)
I saw this conception in a paper, here is link : https://www.cs.utexas.edu/~lin/papers/cgo11.pdf
