### ISSUE TITLE
Backport fix for CVTNEPS2BF16 selection

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#61548]
This works on 15 and main but fails to select on 16: https://llvm.godbolt.org/z/dzsrTxboG

@RKSimon @phoebewang Do you happen to know which commit fixed this?

**Comment by phoebewang** [comment]
Guess it's https://github.com/llvm/llvm-project/commit/96df79af029b85616ab90e73143e0e8ae89c7b46
