### ISSUE TITLE
lldb should support debuginfod client protocol to fetch debuginfo / source code

### ISSUE THREAD

**Issue by fche** [llvm/llvm-project#61547]
The llvm toolkit contains an elfutils debuginfod reimplementation for various purposes, but lacks what is perhaps its most compelling use: lldb.  Other debuggers use this technology to fetch debuginfo & source code automatically, but lldb lacks this function.

https://reviews.llvm.org/D75750 was an early draft of this effort, but it's been apprx. abandoned.

**Comment by russelltg** [comment]
Duplicate of #52732
