### ISSUE TITLE
LLDB 16 builds depend on Python 3.11 from homebrew

### ISSUE THREAD

**Issue by xusheng6** [llvm/llvm-project#61542]
It would not run for anyone who does not use homebrew, e.g., me.

Screenshot of dependent libraries of liblldb.16.0.0.dylib 

<img width="920" alt="Screenshot 2023-03-20 at 8 07 45 PM" src="https://user-images.githubusercontent.com/94503187/226336148-710592e8-53f8-4f21-adeb-d437e674d63c.png">

Same issue with LLDB 15 builds:

<img width="547" alt="Screenshot 2023-03-20 at 8 00 11 PM" src="https://user-images.githubusercontent.com/94503187/226336252-32e1cf03-b342-4084-8225-19f4eaf8a4b3.png">

**Comment by xusheng6** [comment]
@DimitryAndric

**Comment by DimitryAndric** [comment]
Note that this is a more general problem, as we already encountered something similar with libzstd: during configuration it found the Homebrew libzstd.dylib, and linked to that by default, and that dependency got into almost all llvm and clang executables. I had to switch to static linking to prevent that...

**Comment by DimitryAndric** [comment]
It turns out the `/usr/bin/python3` executable is a wrapper that checks whether Xcode or the Command Line Developer Tools are installed, and pops up an installation dialog if none of these are found. Unfortunately, Xcode and the Command Line Developer Tools each have their _own_ copy of Python3:

```text
% ls -l /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework:
total 0
lrwxr-xr-x  1 root  wheel   24 Dec 14 18:42:22 2022 Headers@ -> Versions/Current/Headers
lrwxr-xr-x  1 root  wheel   24 Dec 14 18:42:22 2022 Python3@ -> Versions/Current/Python3
lrwxr-xr-x  1 root  wheel   26 Dec 14 18:42:22 2022 Resources@ -> Versions/Current/Resources
drwxr-xr-x  5 root  wheel  160 Dec 14 18:53:33 2022 Versions/

/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework:
total 0
lrwxr-xr-x  1 root  wheel   24 Dec 16 16:15:31 2022 Headers@ -> Versions/Current/Headers
lrwxr-xr-x  1 root  wheel   24 Dec 16 16:15:31 2022 Python3@ -> Versions/Current/Python3
lrwxr-xr-x  1 root  wheel   26 Dec 16 16:15:31 2022 Resources@ -> Versions/Current/Resources
drwxr-xr-x  4 root  wheel  128 Dec 16 16:15:32 2022 Versions/
```

So I will have to choose one of these, as you cannot link to both. I think the CommandLineTools version is the most appropriate, as this is the version that can be installed with the least friction (i.e. just run `python3` on a fresh macOS, and it will prompt you to install).

This would mean that you must install the Command Line Developer Tools to be able to run lldb, but it seems reasonable to me. You cannot compile any meaningful programs without having either the full Xcode or the Command Line Developer Tools installed, as they contain system headers and link libraries.

Alternatively, I could attempt to disable Python support in lldb, or drop lldb from the installable package entirely, but that would seem far less useful. :)

**Comment by xusheng6** [comment]
Is it possible to statically link with, or bundle a Python with the build? It does not sound like a good idea to rely on a Python that is to be found on the user's system, which can have lots of variants and cause compatibility issues.

**Comment by xusheng6** [comment]
Please do not drop lldb executalbe in the build! It helps me test whether some bugs are patched in the latest release, and decide if our produce should be building with a newer version of LLDB to benefit from it.

**Comment by DimitryAndric** [comment]
I think I have found a workable solution, though it is not going to win any beauty contests: I install both the CommandLineTools and Xcode on a macOS 13 VM, rename the `Python3.framework` in `/Applications/Xcode.app/Contents/Developer/Library/Frameworks` to something else, and replace it by a symlink to `/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework`.

Then I can do a full `test-release.sh` run which results in a `liblldb.16.0.0.dylib` linked to the usual system libraries, and to `@rpath/Python3.framework/Versions/3.9/Python3`:

```text
% otool -L lib/liblldb.16.0.0.dylib
lib/liblldb.16.0.0.dylib:
	@rpath/liblldb.16.0.0.dylib (compatibility version 0.0.0, current version 16.0.0)
	/usr/lib/libcompression.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/Python3.framework/Versions/3.9/Python3 (compatibility version 3.9.0, current version 3.9.0)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libform.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libpanel.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/usr/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.3.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1953.255.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1953.255.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1228.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 60420.60.24)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.36.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

The `lldb` binary using `liblldb.16.0.0.dylib` can then start up successfullyl, with only the ﻿﻿Command Line Developer Tools installed. Note that unlike e.g. running `cc` or `python3`, it will _not_ automatically present a dialog for installing the Command Line Developer Tools, as this is a feature implemented by the `xcrun` tool.

@tstellar I'm hesitant to replace the existing `clang+llvm-16.0.0-arm64-apple-darwin22.0.tar.xz ` tarball at https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.0, do we ever do that? I think it would only be confusing for users. (We should probably have some sort of procedure for re-uploading 'bad' tarballs, either keeping the old ones or making the old URL really go away, and be replaced by a new one...)

**Comment by DimitryAndric** [comment]
@xusheng6 can you please try https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.1/clang+llvm-16.0.1-arm64-apple-darwin22.0.tar.xz, which is the 16.0.1 tarball I uploaded today? This should have a liblldb.dylib that is linked to the Command Line Developer Tools python3 framework, so it is supposed to work when those Tools are installed.

**Comment by xusheng6** [comment]
@DimitryAndric I will have a look when I am available. Busy with work these days. Sorry for the late reply

**Comment by xusheng6** [comment]
I tried and it works, thx!

**Comment by DimitryAndric** [comment]
Okay, from now on I'll use the same method for building the releases. Thanks for testing.

**Comment by DavidSpickett** [comment]
Should the canonical way to build a MacOS release be documented somewhere? Or is it going to be included in the release build script.

A lot of effort has gone into it and I wouldn't want it to be lost at some point.

**Comment by DimitryAndric** [comment]
Well, in the end I don't really do much more than invoke the `test-release.sh` script in a empty directory, but the non-explicit steps are:
* provision a macOS physical/virtual machine, consisting of:
  * installing macOS
  * installing command line tools (`xcode-select --install` etc)
  * installing Xcode (this needs either the full .xip file or an App Store login)
  * installing homebrew
  * installing build dependencies such as CMake, etc
  * following further instructions for building from e.g. https://llvm.org/docs/GettingStarted.html, https://clang.llvm.org/get_started.html,  https://lldb.llvm.org/resources/build.html#id2 etc
* Running `test-release.sh` with all the right options: `test-release.sh -release x.y.z -final triple arm64-apple-darwinXY -j N -use-ninja -configure-flags "-DLLVM_USE_STATIC_ZSTD=ON" -lldb`

If it is worth the effort to write this down in some detail, it still needs a good location in the documentation. I have no idea where that is. :)

**Comment by DavidSpickett** [comment]
Sounds like it's less what to do more what Python not to link against if you're going to distribute the build. Maybe add a way to tell if a binary is linking to the right one (`ldd lldb` ?).

Could be a section toward the end of https://lldb.llvm.org/resources/build.html#cross-compiling-lldb, there is a MacOS bit about code signing already. "Building a MacOS release of LLDB" ?. The source for the document is `lldb/docs/resources/build.rst`.
