### ISSUE TITLE
Deb packages create invalid symlink for /usr/lib/clang/16/*

### ISSUE THREAD

**Issue by fodinabor** [llvm/llvm-project#61550]
As can be seen in our [CI](https://github.com/OpenSYCL/OpenSYCL/actions/runs/4469070690/jobs/7850666861#step:3:452) LLVM deb packages only install `/usr/lib/llvm-16/lib/clang/16` but still link to the `/usr/lib/llvm-16/lib/clang/16.0.0/(include|lib)` from `/usr/lib/clang/(16|16.0.0)/(include|lib)`.
To fix this: either fix the symlinks in `/usr/lib/clang` or (re-)add a symlink from `/usr/lib/llvm-16/lib/clang/16.0.0` to `/usr/lib/llvm-16/lib/clang/16`. (or likely copy the files to `16.0.0` and symlink from `16` to `16.0.0`?)

The important bits from the CI:
```
/usr/lib/clang
├── 16
│   ├── include -> ../../llvm-16/lib/clang/16.0.0/include
│   └── lib -> ../../llvm-16/lib/clang/16.0.0/lib
└── 16.0.0
    ├── include -> ../../llvm-16/lib/clang/16.0.0/include
    └── lib -> ../../llvm-16/lib/clang/16.0.0/lib
```
But there's only
`/usr/lib/llvm-16/lib/clang/16`.

cc @sylvestre

**Comment by sylvestre** [comment]
I think it is now fixed
