### ISSUE TITLE
clang-format should add a newline at EOF if not present.

### ISSUE THREAD

**Issue by ZequanWu** [llvm/llvm-project#61551]
This is part of #56054, filed separately for the feature to just adding newline at EOF if not present.

**Comment by kiwixz** [comment]
LLVM 16 added an option for this: https://releases.llvm.org/16.0.0/tools/clang/docs/ClangFormatStyleOptions.html#insertnewlineateof.

**Comment by ZequanWu** [comment]
Thanks, I didn't realize that option exists.
