### ISSUE TITLE
Global conditional check is hoisted outside  loop and which is incorrect .

### ISSUE THREAD

**Issue by UmeshKalappa0** [llvm/llvm-project#61577]
Its bug with instcombine and jump-threading for the testcase :

https://godbolt.org/z/ejjE1xo1a

**Comment by fhahn** [comment]
As @nikic said, the transform looks correct. If `stop`'s value could change independent of the loop, you need to mark it as `volatile`

**Comment by UmeshKalappa0** [comment]
doesn't global load has the side effects across the function ? 

something like watchdog timer writes the value to "stop" say every 30 mins ?

**Comment by nikic** [comment]
Only if the load is atomic or volatile.
