### ISSUE TITLE
Spurious -Wpre-c++2b-compat warning with -std=c++2b -pedantic

### ISSUE THREAD

**Issue by timsong-cpp** [llvm/llvm-project#61582]
```cpp
struct A {
    void operator[](int, int);
};
```

with `-std=c++2b -pedantic` (https://gcc.godbolt.org/z/qnjd5YhPa):

```
<source>:2:10: warning: overloaded 'operator[]' with more than one parameter is a C++2b extension [-Wpre-c++2b-compat]
    void operator[](int, int);
         ^
1 warning generated.
```

I would not have expected `-pedantic` to warn me about constructs that are ill-formed in a previous standard.

**Comment by AaronBallman** [comment]
I looked through the rest of the C++2b precompat warnings to see if any more were also mistaken, and it seems like that's the last one. I'll get it fixed up.
