### ISSUE TITLE
Optimizing functions that compute absolute values of x

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#61613]
Test code:
```c
#include <stdlib.h>
#include <math.h>

float f1(float x)
{
    return fabsf(x);
}

float f2(float x)
{
    return sqrtf(x * x);
}

float f3(float x)
{
    return (x >= 0.0f) ? x : -x;
}

float f4(float x)
{
    if(x >= 0.0f) return x;
    else return -x;
}
```

GCC:
```asm
f1:
        fabs    s0, s0
        ret
f2:
        fmul    s0, s0, s0
        fsqrt   s0, s0
        ret
f3:
        fabs    s0, s0
        ret
f4:
        fabs    s0, s0
        ret
```

Clang:
```asm
f1:                                     // @f1
        fabs    s0, s0
        ret
f2:                                     // @f2
        fabs    s0, s0
        ret
f3:                                     // @f3
        fabs    s0, s0
        ret
f4:                                     // @f4
        fneg    s1, s0
        fcmp    s0, #0.0
        fcsel   s0, s1, s0, lt
        ret
```

https://godbolt.org/z/EercfYfnd

Interestingly, Clang generates different code for `f4` and so does GCC for `f2`.

**Comment by junaire** [comment]
Looks like an InstCombine issue? https://godbolt.org/z/Kq4PhrvGh

**Comment by MaxGraey** [comment]
At least, `f3` transformation is not valid for negative zeros. Proof:

https://alive2.llvm.org/ce/z/aeSFxr

**Comment by k-arrows** [comment]
> At least, `f3` and `f4` transformations are not valid for negative zeros. Proof:
> 
> https://alive2.llvm.org/ce/z/aeSFxr

Thank you for your explanation. I understand negative zero and positive zero are considered to be equal if we compare them with operator like `==`.

But if `-ffast-math` is enabled, GCC transforms `f4` into `fabs` but Clang does not.

**Comment by junaire** [comment]
> > At least, `f3` and `f4` transformations are not valid for negative zeros. Proof:
> > https://alive2.llvm.org/ce/z/aeSFxr
> 
> Thank you for your explanation. I understand negative zero and positive zero are considered to be equal if we compare them with operator like `==`.
> 
> But if `-ffast-math` is enabled, GCC transforms `f4` into `fabs` but Clang does not.

Yes, `-Ofast` is a must to enable this optimization. IIUC, the underlying reason is that LLVM doesn't correctly canonicalize the two forms of `select` into one. https://godbolt.org/z/5h8eWfr9d

However, I am not unsure about it. CC @rotateright @nikic for help.

**Comment by junaire** [comment]
No, we actually have transforms that can handle `ult` cases:
https://github.com/llvm/llvm-project/blob/d8efbcf9dcbb413fa3d3e66173f4630989e5588c/llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp#L2721-L2732

But for some reason, `f4` doesn't have `nsz` flag so it fails...
