### ISSUE TITLE
Backport "[analyzer] Fix crashing getSValFromInitListExpr for nested initlists"

### ISSUE THREAD

**Issue by steakhal** [llvm/llvm-project#61614]
Today I landed a crash fix: https://github.com/llvm/llvm-project/commit/558b46fde2db2215794336bbd08e411fee5240d7 ([analyzer] Fix crashing getSValFromInitListExpr for nested initlists)
This shouldn't be risky to backport to clang-16.0.1

@Xazax-hun

**Comment by Xazax-hun** [comment]
Sounds good to me
