### ISSUE TITLE
no proper documentation to understand diagnostic messages generated by clang

### ISSUE THREAD

**Issue by simideveloper** [llvm/llvm-project#61647]
the file DiagnosticASTkinds.td  at clang/include/clang/Basic does not contain any proper comments or documentation to know how it works making things difficult for the contributors.

**Comment by pogo59** [comment]
Diagnostics are defined in several different .td files; adding a description to one of them does not help anyone looking at the others. It would be better to find a common place to put this information, possibly in the web pages rather than one of the .td source files.
