### ISSUE TITLE
"crypto" no longer implies "aes" on aarch64

### ISSUE THREAD

**Issue by ebiggers** [llvm/llvm-project#61645]
With `-target aarch64-linux-gnu`, Clang 15 can compile the following code but Clang 16 cannot:

```c
#include <arm_neon.h>                                                            
                                                                                 
poly128_t __attribute__((target("crypto")))                                      
f(poly64_t a, poly64_t b)                                                        
{                                                                                
        return vmull_p64(a, b);                                                  
}                                                                                
```

Clang 16 reports:

```console
test.c:6:9: error: always_inline function 'vmull_p64' requires target feature 'aes', but would be inlined into function 'f' that is compiled without support for 'aes'
        return vmull_p64(a, b);
               ^
```

Is this an intentional breaking change?

**Comment by lenary** [comment]
I think this would be solved by https://reviews.llvm.org/D142135 by @davemgreen

**Comment by davemgreen** [comment]
Oh I had been under the impression that a `target("crypto")` attribute had never worked, so this at least wasn't worse than before. I must have been mistaken about that, although in this case the guards for pmull have also been changed to now require aes. It always worked for clang 15 even without the target attribute.
https://godbolt.org/z/YMc7zeG58 https://godbolt.org/z/56bon749M

GCC now accepts +aes for pmull too after https://inbox.sourceware.org/gcc-patches/PAXPR08MB69264E1E74BE4A433974953593C69@PAXPR08MB6926.eurprd08.prod.outlook.com/T/#t.
That is a recent patch though, likely not included in released compilers yet.

Clang should accept "+aes" (or "+aes+sha2" to be consistent with "+crypto"). The "+" syntax should generally work consistently across both compilers, although crypto is always a bit of an odd one and doesn't always work consistently. The older "aes" syntax should also work for consistency with previous releases.

**Comment by ebiggers** [comment]
That's interesting that `__attribute__((target("crypto")))` might never have actually done anything with clang!  I had it in my code anyway because gcc needed `__attribute__((target("+crypto")))`.

I understand that "crypto" is considered a mistake, since more crypto extensions were added after the original ones.  But, I would have expected alignment with gcc's behavior which seems to treat "crypto" as meaning the original crypto extensions?

**Comment by davemgreen** [comment]
It's all a bit of a mess I'm afraid. What you say is true, but when "+crypto" was originally split up into subfeatures in clang it was made to mean `"+aes+sha2"` in the base `armv8.0-a` architecture and `"+aes+sha2+sha3+sm4"` with `-march=armv8.4-a` and later. Unfortunately GCC never copied the same architecture-dependant definition and it always means `"+aes+sha2"`.  We have to figure out which one is best and standardize on it. The GCC implementation is simpler and easier to understand, but would involve changing how clang options behave to be consistent.

The fact that target("crypto") does nothing in clang is certainly a bug. I will try and push forward the patch to get it fixed.
