### ISSUE TITLE
when targeting X86 frem seems to be lowered to a call to libm fmod, but this is not clearly worded

### ISSUE THREAD

**Issue by SixthDot** [llvm/llvm-project#61653]
https://llvm.org/docs/LangRef.html#frem-instruction

>  "This is the same output as a libm ‘fmod’ function"

"this is the same output" does not mean "call libm"

**Comment by aabhinavg** [comment]
This issue is fix by the patch: https://reviews.llvm.org/D146900

**Comment by bchetioui** [comment]
@SixthDot did you encounter some problem because the implementation was using `fmod`? At first glance, this seems like an implementation detail that does not belong in the documentation---but perhaps I am missing something?

**Comment by SixthDot** [comment]
No, the context was really the documentation. The proposed fix addresses the problem.

**Comment by SixthDot** [comment]
The value added is that now it's clearer that if you need frem then you certainly need to link against libm too.

**Comment by EugeneZelenko** [comment]
@SixthDot: Patch was not merged yet.

**Comment by aabhinavg** [comment]
@EugeneZelenko  Once approved i can merge it.

**Comment by aabhinavg** [comment]
@EugeneZelenko Once the patch gets approved I can merge it.
@bchetioui waiting for your approval.

**Comment by bchetioui** [comment]
Thank you for explaining @SixthDot. This has now landed.
