### ISSUE TITLE
clang-format corrupts the code

### ISSUE THREAD

**Issue by duduarbel** [llvm/llvm-project#61654]
The following code 
```cpp
class A
{
	MARCO1 // comment
	MACRO2
public:
	int x;
	int y;
};
```
is formatted to this bad code:
```cpp
class A
{
    MARCO1 // comment
        MACRO2 public : int x;
    int y;
};
```

The `.clang-format` has only one line:
```yml
BasedOnStyle: Microsoft
```

**Comment by owenca** [comment]
You need to add `MACRO2` to [StatementMacros](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#statementmacros).

**Comment by rymiel** [comment]
I think this also shouldn't change the actual semantic of the program? (so i'm removing invalid-code-generation) But yes, if you have macros which aren't used with semicolons after them, you should let clang-format know in its configuration

**Comment by HazardyKnusperkeks** [comment]
As stated, no bug, just misconfiguration.
