### ISSUE TITLE
[InstCombine] Missing zext(shl(trunc)) fold

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#61650]
From https://reviews.llvm.org/D146637:

```ll
define i32 @src(i32 %a) {
  %trunc = trunc i32 %a to i16
  %shl = shl i16 %trunc, 8
  %ext = zext i16 %shl to i32
  ret i32 %ext
}

define i32 @tgt(i32 %a) {
  %shl = shl i32 %a, 8
  %and = and i32 %shl, 65280
  ret i32 %and
}
```

https://alive2.llvm.org/ce/z/etjn25

**Comment by kazutakahirata** [comment]
Posted a patch: https://reviews.llvm.org/D148440

**Comment by andjo403** [comment]
This fold already exist but there is a call to [shouldChangeType ](https://github.com/llvm/llvm-project/blob/91fdfec263ff2b8e88433c4294a550cabb0f2314/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp#L1202) that is depending on the data layout see https://llvm.godbolt.org/z/obW4KvxjE
