### ISSUE TITLE
Approximate result of floating-point operation with -O2

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#61658]
The following program
```
#include <iostream>
#include <limits>

int main() {
    double A = std::numeric_limits<double>::max();
    double C = -0.1;
    double V = A * C - A * C;
    std::cout << V << std::endl;
}
```
if compiled with `-O2` option, prints `-4.9896e+290` instead of `0`. Is it normal?

Online demo: https://godbolt.org/z/fqf7xaYhq

**Comment by nikic** [comment]
Does not happen with ` -ffp-contract=off`. I'll leave it to other people to determine whether that's a correct outcome for FP contraction or not.

**Comment by topperc** [comment]
Do to the default -ffp-contract=on, we constant folded this as `fma(A, C, -(A * C))`. Passing that form to the libm `fma` function also gives -4.9896e+290.

**Comment by ebavier** [comment]
Just because I haven't seen it explicitly said yet: `-4.9896e290` is the roundoff error of the multiplication of `A * C`.  The `fma(A, C, -A*C)` sequence is standard fare for multiprecision floating-point algorithms.

**Comment by nikic** [comment]
Closing this per above comments.
