### ISSUE TITLE
clang-format 16 repeatedly changes file between two versions

### ISSUE THREAD

**Issue by omartijn** [llvm/llvm-project#61675]
When I format the attached `glfw3.h` header file with the given `.clang-format` file, it keeps changing between two versions every time. It looks like it is getting confused by the comment associating the `#endif`. In one version it wants to align the comment below with it, in the other version it is aligned with the comments above the `#endif.

Note: I've changed the file extensions to `.txt` because GitHub is being obnoxious and removed the leading dot from `.clang-format` since GitHub refuses to accept hidden files apparently.
[glfw3.txt](https://github.com/llvm/llvm-project/files/11061197/glfw3.txt)
[clang-format.txt](https://github.com/llvm/llvm-project/files/11061206/clang-format.txt)

I'm using `Debian clang-format version 16.0.0 (++20230323033156+c5b23ab2a31a-1~exp1~20230323153311.61)` which was the latest as-of this morning.

```console
$ clang-format -i glfw3.h && md5sum glfw3.h
5f91766c110dc895309ce16bc33dadff  glfw3.h
$ clang-format -i glfw3.h && md5sum glfw3.h
539373658f93119012002c2a4fe57385  glfw3.h
$ clang-format -i glfw3.h && md5sum glfw3.h
5f91766c110dc895309ce16bc33dadff  glfw3.h
$ clang-format -i glfw3.h && md5sum glfw3.h
539373658f93119012002c2a4fe57385  glfw3.h
```

**Comment by owenca** [comment]
Fixed in a4c87f8.
