### ISSUE TITLE
FreeBSD lldb-server build broken

### ISSUE THREAD

**Issue by VoxSciurorum** [llvm/llvm-project#61689]
Commit 0c5cee779929f840f4f286c5894a01f583ee7b4a caused the lldb-server target to fail with undefined symbols on FreeBSD x86-64.  lldbPluginPlatformFreeBSD depends on lldbPluginPlatformPOSIX but the cmake file fails to note the dependency.  Fix attached.

[cmake.txt](https://github.com/llvm/llvm-project/files/11064452/cmake.txt)

**Comment by bulbazord** [comment]
@VoxSciurorum Thanks for reporting this issue! I've applied your fix in `e7654a7692c4f894eec136af07fe6756bef315fc` and credited you for the change. If there are further problems, please open a new issue.
