### ISSUE TITLE
Clang-format confused trailing return type

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#61700]
Problem found when upgrading from 16-RC2 to 16.0.0
````cpp
struct EXPORT_MACRO [[nodiscard]] C
{
   using U = int;
   auto f() noexcept -> void {}
   auto g() -> void {}
};
````
gets reformatted to
````cpp
struct EXPORT_MACRO [[nodiscard]] C
{
   using U = int;
   auto f() noexcept -> void {}
   auto g()->void {}
};
````
Note in function `g()` that `->` has no spaces around it while `f()` does have them.

[reproduction.zip](https://github.com/llvm/llvm-project/files/11068943/reproduction.zip) contains full reproduction for this

**Comment by JVApen** [comment]
Almost same reproduction with other effect:
````
struct EXPORT_MACRO [[nodiscard]] C
{
    C(NS::B &&b);
};
````
becomes
````
struct EXPORT_MACRO [[nodiscard]] C
{
    C(NS::B && b);
}
````
Note the missing `;` and the space before `b`.

Has this option: `RemoveSemicolon: true`, though not needed for the effect on `b`.

**Comment by owenca** [comment]
https://reviews.llvm.org/D146895
