### ISSUE TITLE
Clang-Tidy: readability-static-accessed-through-instance produces broken fixit for unnamed class

### ISSUE THREAD

**Issue by fastasturtle** [llvm/llvm-project#61736]
```cpp
struct {
    static int foo() { return 1; }
} test;

int main() {
    return test.foo(); // warning: static member accessed through instance [readability-static-accessed-through-instance]
//         ^~~~~
//         (unnamed struct at <source>:1:1)::
}
```

https://gcc.godbolt.org/z/jb9d97r3h

Fixit tries to spell out the class name, which is obviously impossible. While `foo` can be accessed using something like `decltype(test)`, maybe it's better to disable the check altogether.

**Comment by AMS21** [comment]
My attempt at fixing this: https://reviews.llvm.org/D147411
