### ISSUE TITLE
[AIX] C++ member functions in custom sections generate invalid alignments

### ISSUE THREAD

**Issue by daltenty** [llvm/llvm-project#61743]
Here's a C++ test program which generates invalid assembly when compiled for AIX:
```cpp
struct A {
        void __attribute__((section("foo"))) odd();
        void __attribute__((section("foo"))) c();
};

void A::odd() {}

void A::c() {}

int main() {
        A a;
        a.odd(); a.c();
        return 0;
}
```

```console
$ clang++ -c -fverbose-asm member.cc
Assembler:
/tmp/member-c65289.s: line 39: 1252-081 The instruction is not aligned properly.
        The instruction requires machine specific alignment.
clang-15: error: assembler command failed with exit code 1 (use -v to see invocation)
```
Looking at the assembly:
```console
$ clang++ -S -fverbose-asm  -o -  member.cc|head -n46
        .csect .text[PR],5
        .file   "member.cc","LLVM version 15.0.2"
        .csect foo[PR],5
        .globl  _ZN1A3oddEv[DS]                 # -- Begin function _ZN1A3oddEv
        .globl  ._ZN1A3oddEv
        .align  1
        .csect _ZN1A3oddEv[DS],2
        .vbyte  4, ._ZN1A3oddEv                 # @_ZN1A3oddEv
        .vbyte  4, TOC[TC0]
        .vbyte  4, 0
        .csect foo[PR],5
._ZN1A3oddEv:
# %bb.0:
        stw 3, -8(1)
        blr
L.._ZN1A3oddEv0:
        .vbyte  4, 0x00000000                   # Traceback table begin
        .byte   0x00                            # Version = 0
        .byte   0x09                            # Language = CPlusPlus
        .byte   0x20                            # -IsGlobaLinkage, -IsOutOfLineEpilogOrPrologue
                                        # +HasTraceBackTableOffset, -IsInternalProcedure
                                        # -HasControlledStorage, -IsTOCless
                                        # -IsFloatingPointPresent
                                        # -IsFloatingPointOperationLogOrAbortEnabled
        .byte   0x40                            # -IsInterruptHandler, +IsFunctionNamePresent, -IsAllocaUsed
                                        # OnConditionDirective = 0, -IsCRSaved, -IsLRSaved
        .byte   0x80                            # +IsBackChainStored, -IsFixup, NumOfFPRsSaved = 0
        .byte   0x00                            # -HasExtensionTable, -HasVectorInfo, NumOfGPRsSaved = 0
        .byte   0x01                            # NumberOfFixedParms = 1
        .byte   0x01                            # NumberOfFPParms = 0, +HasParmsOnStack
        .vbyte  4, 0x00000000                   # Parameter type = i
        .vbyte  4, L.._ZN1A3oddEv0-._ZN1A3oddEv # Function size
        .vbyte  2, 0x000b                       # Function name len = 11
        .byte   "_ZN1A3oddEv"                   # Function Name
                                        # -- End function
        .globl  _ZN1A1cEv[DS]                   # -- Begin function _ZN1A1cEv
        .globl  ._ZN1A1cEv
        .align  1
        .csect _ZN1A1cEv[DS],2
        .vbyte  4, ._ZN1A1cEv                   # @_ZN1A1cEv
        .vbyte  4, TOC[TC0]
        .vbyte  4, 0
        .csect foo[PR],5
._ZN1A1cEv:
# %bb.0:
        stw 3, -8(1)
```

It seems the odd length of the name in the traceback table following the first function pushes the location counter to a misaligned value and then the alignment value the compiler has inserted at the start of the function is two-bytes (`.align  1`) which is less than what is required by Power ISA (i.e instructions must be 4-byte aligned).

**Comment by daltenty** [comment]
Some Analysis about the above issue.

The first part, the 2-byte member function alignment seems to arise from clang's itanium ABI handling. 

The itanium C++ ABI standard representation of member function pointers (which is used by clang on AIX) encodes information about whether the function is a virtual or non-virtual function in the least-significant bit of the point (Reference: https://itanium-cxx-abi.github.io/cxx-abi/abi.html#member-function-pointers). This leads to the following requirement:

"The low bit of a function pointer to a non-static member function is never set. On most platforms, this is either always true or can be made true at little cost."

Clang's attempt to implement this requirement for targets that can follow it is:
```
  // Some C++ ABIs require 2-byte alignment for member functions, in order to
  // reserve a bit for differentiating between virtual and non-virtual member
  // functions. If the current target's C++ ABI requires this and this is a
  // member function, set its alignment accordingly.
  if (getTarget().getCXXABI().areMemberFunctionsAligned()) {
    if (F->getAlignment() < 2 && isa<CXXMethodDecl>(D))
      F->setAlignment(llvm::Align(2));
  }
```
https://github.com/llvm/llvm-project/blob/de7639ddb05e46ffd3bdbf0d562249c95c544d2b/clang/lib/CodeGen/CodeGenModule.cpp#L2149

IMHO this seems wrong, the above will force the alignment to 2-bytes on all member functions without an explicit alignment >= 2, even if targets natural function alignment was greater than this (e.g. on Power all functions are 4-byte aligned). This also assumes that aligning the function will change the observed alignment of function pointers, which isn't always true (e.g. AIX uses function descriptor objects which is what the ptr points to, ARM has thumb state bits in the LSB of the function ptr).

The second part of this issue is the custom sections. The LLVM language reference requires globals (which includes functions) with an assigned sections as-per the language ref:

"Targets and optimizers are not allowed to over-align the global if the global has an assigned section." (https://github.com/llvm/llvm-project/blob/bb6faec1818026a5b7ead29ff98511784ce2cfdd/llvm/docs/LangRef.rst#L714)

The backend will try to observe this alignment value strictly, without consideration if it meets the minimum ABI requirements, so we run into the above problem.

**Comment by daltenty** [comment]
In terms of fix directions. the clang implementation of this ABI requirement seems incorrect to me, we required only that the function alignment be **at least** 2-bytes (on targets where the function alignment affects function ptr alignment at least). We ought not to force an alignment less that what the target would naturally have for a pointer to member function.

Clang would however need some way to work out the natural function pointer alignment for the target. This information could be determined through the DataLayout (via a field for function pointer alignment added by https://reviews.llvm.org/D57335 as other parts of LLVM were making bad assumption in this space).

This information isn't setup for the Power target at the moment though, so this approach would introduce it and use it to work out the minimum member function alignment.

So this works out two two patches:

1. Add the function pointer alignment to the data layout for Power
2. Observe the function pointer alignment in clang and use it to decide if we need to apply an explicit alignment.

**Comment by stefanp-ibm** [comment]
@daltenty 
I see that the first patch has gone in. Were you planning on putting in the second patch as well?

**Comment by daltenty** [comment]
> @daltenty I see that the first patch has gone in. Were you planning on putting in the second patch as well?

Ah, thanks for the reminder. 

I put in the second patch as https://github.com/llvm/llvm-project/commit/196c144d0bc16350d2a73490e13bc9e3e82e84c0 already as well. I'll close off this issue.
