### ISSUE TITLE
Inefficient scalable vector codegen after "[SCEV] Add SCEVType to represent `vscale`."

### ISSUE THREAD

**Issue by UsmanNadeem** [llvm/llvm-project#61742]
See sample code: https://godbolt.org/z/dnPzGrTqj

The issue was bisected to patch `[SCEV] Add SCEVType to represent ``vscale``.` :
https://reviews.llvm.org/D144891 or https://github.com/llvm/llvm-project/commit/62d11b2ccaeec8abc12e07aa009c922d72fd6377

A quick look shows that the difference comes from LSR and disabling LSR gives good code again.

Before the patch we were getting 

```asm
        ld1d    { z1.d }, p0/z, [x1, x8, lsl #3]
        add     x11, x1, x10
        ld1d    { z2.d }, p0/z, [x11, #1, mul vl]
        ld1d    { z3.d }, p0/z, [x11, #2, mul vl]
        ld1d    { z4.d }, p0/z, [x11, #3, mul vl]
        ld1d    { z5.d }, p0/z, [x11, #4, mul vl]
        ...
```

Now we are seeing address calculation inside the loop:

```asm
        ld1d    { z1.d }, p0/z, [x1, x8, lsl #3]
        add     x11, x1, x10
        ld1b    { z2.b }, p1/z, [x11, x9]
        add     x12, x11, x9
        ld1b    { z3.b }, p1/z, [x12, x9]
        add     x13, x12, x9
        ld1b    { z4.b }, p1/z, [x13, x9]
        add     x11, x13, x9
        ld1b    { z5.b }, p1/z, [x11, x9]
        ...
```

**Comment by UsmanNadeem** [comment]
@nikic  @paulwalker-arm

**Comment by nikic** [comment]
The post-LSR output contains vscale GEP constant expressions, which are supposed to be forbidden since recently, so something is going very wrong here.

**Comment by UsmanNadeem** [comment]
> The post-LSR output contains vscale GEP constant expressions, which are supposed to be forbidden since recently, so something is going very wrong here.

That is the output for 16.0, The trunk has normal GEPs: `%scevgep1 = getelementptr i8, ptr %b.vector_ptr0, i64 %increment`

**Comment by paulwalker-arm** [comment]
Fixed by https://github.com/llvm/llvm-project/pull/70304
