### ISSUE TITLE
Constrained non-template function declarations in function template bodies aren't diagnosed

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#61748]
This partial GCC test compiles in Clang when it shouldn't.
```cpp
template <typename T> concept C = true;

template<typename T>
void F ()
{
  void bad () requires C<T>; // expected-error{{non-templated function cannot have a requires clause}}
}
```
Note that this modification **does** produce the expected diagnostic.
```cpp
template <typename T> concept C = true;

void F ()
{
  void bad () requires C<int>; // expected-error{{non-templated function cannot have a requires clause}}
}
```

**Comment by shafik** [comment]
Note MSVC also accepts this: https://godbolt.org/z/EGThfPKGd but I think gcc is correct: https://timsong-cpp.github.io/cppwp/n4861/dcl.decl#4

CC @erichkeane

**Comment by cpplearner** [comment]
"Templated function" is defined in [[temp.pre]/8](https://eel.is/c++draft/temp.pre#8).

**Comment by erichkeane** [comment]
> "Templated function" is defined in [[temp.pre]/8](https://eel.is/c++draft/temp.pre#8).

Ah! Thank you! That definitely looks familiar.  Its unfortunate that dcl.decl points to dcl.fct instead of temp.pre there.

**Comment by shafik** [comment]
I sent an email to see if we can get a core issue b/c this confused me as well it seems like pointing to temp.pre makes a lot more sense.

**Comment by shafik** [comment]
Your `struct S` example fits the third bullet in https://eel.is/c++draft/temp.pre#8 b/c it is a member of a templated entity although it looks edg rejects it: https://godbolt.org/z/WKKfMenqE

**Comment by erichkeane** [comment]
Ah! I'd forgotten to mark it a 'friend'.  Though i DO note that all 3 other compilers reject it if it is a non-defined friend.  So I think I have a pretty good feeling for what we should do here, and I think I've come around to the limitation in clang not being strict enough.

**Comment by erichkeane** [comment]
Patch up here: https://reviews.llvm.org/D147070

**Comment by jensmaurer** [comment]
The misleading cross-reference for "templated function" has been fixed editorially in the standard text; see cplusplus/draft#6215.
