### ISSUE TITLE
Add a logging facility to the libc tests which can serve as a replacement for std::cout

### ISSUE THREAD

**Issue by sivachandra** [llvm/llvm-project#61753]
This is one of the tasks that has to be done to address issue #61751. Essentially, we have to implement a test logger which can log success/failure messages to stdout but not use `std::cout` from the C++ standard library.

**Comment by gchatelet** [comment]
Implemented in https://reviews.llvm.org/D147231 https://github.com/llvm/llvm-project/commit/fc5ae0a7a45bdb5251f3dad3fc07047f987ca447

**Comment by gchatelet** [comment]
Actually submitted as https://github.com/llvm/llvm-project/commit/f5dcab0d894b139c2882dae617ca1ddc20a72395.
I missed a few `constexpr` only caught by gcc. And a memory leak caught by the sanitizers.
