### ISSUE TITLE
Add a new libc rule add_libc_test

### ISSUE THREAD

**Issue by sivachandra** [llvm/llvm-project#61756]
This is required to address #61751. See https://discourse.llvm.org/t/rfc-running-libc-unit-tests-as-integration-tests/69461 for more information.

The new rule should add an test target of the kind `libc.test.src.string.strlen_test`. This target by itself does not run any tests but depends on `libc.src.string.strlen_test.__unit__` and `libc.src.string.strlen_test.__hermetic__`. The `*.__unit__` target runs the test as a unit test whereas the `*.__hermetic__` target runs the test as a hermetic tests.

**Comment by michaelrj-google** [comment]
Closing as completed.
