### ISSUE TITLE
clang: __has_extension(cxx_default_function_template_args) with -std=c++98

### ISSUE THREAD

**Issue by acoplan-arm** [llvm/llvm-project#61758]
For the following C++ code compiled with `-std=c++98`:
```cpp
template<int I = 42>
int f() { return I; }
int g() { return f(); }
#if !__has_extension (cxx_default_function_template_args)
#warning oops
#endif
```
Clang accepts it with warnings:
```console
<source>:1:14: warning: default template arguments for a function template are a C++11 extension [-Wc++11-extensions]
template<int I = 42>
             ^   ~~
<source>:5:2: warning: oops [-W#warnings]
#warning oops
 ^
```
the first of which indicates that Clang supports default template arguments for function templates in C++98 mode as an extension, but the second shows that `__has_extension (cxx_default_function_template_args)` returns 0 in C++98 mode.

Perhaps `__has_extension (cxx_default_function_template_args)` should evaluate to 1 in C++98 mode?

**Comment by acoplan-arm** [comment]
There seems to be a similar situation with `cxx_defaulted_functions`:
```c++
struct S {
    S() = default;
};
#if !__has_extension (cxx_defaulted_functions)
#warning oops
#endif
```
which with `-std=c++98` gives:
```
<source>:2:11: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
    S() = default;
          ^
<source>:5:2: warning: oops [-W#warnings]
#warning oops
 ^
```
note that clang _does_ correctly evaluate `__has_extension (cxx_deleted_functions)` to 1.

**Comment by shafik** [comment]
It looks like in `Features.def` we don't define this as an extension. I don't know know the background here, maybe @AaronBallman knows or at least knows the right person to ask.

**Comment by AaronBallman** [comment]
We're missing an `EXTENSION` entry in Features.def for this (and possibly others as well). For example, we define atomics in C as a feature (https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/Features.def#L140) and as an extension (https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/Features.def#L243)
