### ISSUE TITLE
Strange multiplication operator alignment in recent clang-format

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#61785]
Hi,

We are bumping clang-format from:
`15_15~%2b%2b20220316052642%2b11a12544b5fd-1~exp1~20220316172739.191`
to:
`17_17~%2b%2b20230328053227%2b498e1506981f-1~exp1~20230328173331.583`

And we get a strange multiplicator operator alignment in the following code:

```cpp
template <typename T>
struct Foo
{
    Foo(T){}
};

template <typename T>
void foo(T x)
{
    return Foo{x * T{123}};
}
```

Leads to the following with default settings:

```cpp
template <typename T> struct Foo {
  Foo(T) {}
};

template <typename T> void foo(T x) { return Foo{x *T{123}}; }
```

Note how the `*` is no longer centered, instead attached to the `T`. I've been reading through the Release Notes and couldn't find any new setting that might affect this.

Do you know if this is expected, or can we configure it with some option?

**Comment by rymiel** [comment]
Bisected to 70de684d44135b4025d92b2b36ad387cf5ab8b5

**Comment by mydeveloperday** [comment]
couldn't `if (X * T{123]})` be equally valid?

**Comment by owenca** [comment]
Maybe we should add a `Types` option like `StatementMacros` so that `*`, `&`, and `&&` preceded by a type name don't get annotated as binary operators.

**Comment by mydeveloperday** [comment]
I think thats a great idea.

**Comment by alejandroclaro** [comment]
I have noticed the same issue in cases that looks less ambiguous, like this example:

```c++
static const std::int32_t X = 60;
static const std::int32_t Y = 60;

const ComplexType Foo::BAR(X *Y); // static const member variable.

void baz()
{
    const ComplexType bar(X * Y);

    // ...
}
```
For some reason, it only happens when the declaration is a static const member variable declaration, but no when it's a local variable.

**Comment by carlosgalvezp** [comment]
Thanks for the revert! Should I close this ticket?

**Comment by owenca** [comment]
> Maybe we should add a `Types` option like `StatementMacros` so that `*`, `&`, and `&&` preceded by a type name don't get annotated as binary operators.

See https://reviews.llvm.org/D155273.

**Comment by manuel-arguelles** [comment]
With clang-format version 17.0.2 (++20230929073205+098e653a5bed-1~exp1~20230929073318.47) the original issue is resolved but there's still seems to be an issue with global/static/anonymous namespaces:
```
const int X = 3;
const int Y = 3;

const Foo f(X * Y);
```

turns into: 
```
const int X = 3;
const int Y = 3;

const Foo f(X *Y);
```
