### ISSUE TITLE
llvm-lit config unable to extract target triple

### ISSUE THREAD

**Issue by gandhi56** [llvm/llvm-project#61782]
My machine runs on M1 Pro with host triple `arm64-apple-darwin22.3.0`. CMake config is the following:

```shell
cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_TARGETS_TO_BUILD="AMDGPU;X86" ../llvm
```

To reproduce the error:
```shell
./bin/llvm-lit -v ../clang/test/CodeGenOpenCL/builtins-fp-atomics-gfx90a.cl
```

Output:
```console
llvm-lit: /Users/gouenji56/workspace/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using clang: /Users/gouenji56/workspace/llvm-project/build/bin/clang
llvm-lit: /Users/gouenji56/workspace/llvm-project/llvm/utils/lit/lit/llvm/config.py:324: fatal: Could not turn '' into Itanium ABI triple
```

From my investigation, I found that `config.target_triple = ''` in `class LLVMConfig` which is defined in `llvm/utils/lit/lit/llvm/config.py`.

**Comment by fridtjof** [comment]
The value for target_triple originates from `build/tools/clang/test/lit.site.cfg.py`, which is generated from `clang/test/lit.site.cfg.py.in` by `configure_lit_site_cfg`, which is defined in `llvm/cmake/modules/AddLLVM.cmke`.

Its value comes from LLVM_TARGET_TRIPLE, which is an empty string here for some reason.

Also using an M1 Pro machine with host triple `arm64-apple-darwin22.4.0`.
