### ISSUE TITLE
[clang-tidy, question]: can I determine if an AST node is synthesised?

### ISSUE THREAD

**Issue by florianschanda** [llvm/llvm-project#61794]
Hi,

I am trying to write a new check that bans certain builtin functions (e.g. `__builtin_memcpy`), if they are used by the user directly. My check matches on CallExpr and I then get the name of the function called, etc.

My check basically works, but there is one very odd example where it does not.

```
preprocessed_potato.cpp:12345:7: warning: __builtin_memcpy is not an allowed builtin
class FlagMatrix
      ^
```

Barring bugs in clang, I guess there is a legitimate reason why this node was synthesised and inserted into the tree. Is there a way to figure out if such a node is "coming from source"?

I've read https://clang.llvm.org/doxygen/classclang_1_1CallExpr.html but I couldn't find anything obvious.

I am trying to get a small reproducer but I am having trouble with that as its a lot of internal code full of templates that is hard to reduce. However I was hoping it was maybe a common/obvious problem.

**Comment by EugeneZelenko** [comment]
@florianschanda: Please use https://discourse.llvm.org for questions.

**Comment by florianschanda** [comment]
Understood. Killing this ticket.
