### ISSUE TITLE
Cherry-pick fix for crash in ASTWriter / Bad construction of ConceptSpecializationExpr to 16.0.1 branch

### ISSUE THREAD

**Issue by yeswalrus** [llvm/llvm-project#61801]
Initial discovery: https://github.com/llvm/llvm-project/issues/61486
Resolved in https://reviews.llvm.org/D146678 / https://reviews.llvm.org/rG1f48a1fce23551cc24f5b598af5994f5cfc6b6d0

This has been present since at least clang 15, and was present in 16.0.0, and the fix should be cherry-picked to the clang 16.0.1 branch.

I don't appear to have permissions to add this to the milestone directly

**Comment by erichkeane** [comment]
/branch erichkeane/llvm-project/llvm-issue61801

@tstellar : I think this does what you said?

**Comment by yeswalrus** [comment]
It seems this did not actually make it into the 16.0.1 release? Can we try and make sure it's in 16.0.2?

**Comment by erichkeane** [comment]
> It seems this did not actually make it into the 16.0.1 release? Can we try and make sure it's in 16.0.2?

This ended up being an API break for libclang, so we had to do additional work.  it is still being worked on for 16.0.2.
