### ISSUE TITLE
[Flang][OpenMP] Generate reduction operation for MAX intrinsic reduction

### ISSUE THREAD

**Issue by kavitha-natarajan** [llvm/llvm-project#61808]
Flang does not generate reduction operation for OpenMP MAX intrinsic reduction when the reduction is implemented in the following way:

```f90
!$omp parallel
!$omp do reduction(max:x)
do i=1, 100
  if (y(i) .gt. x) x = y(i)
end do
!$omp end do
!$omp end parallel
```

Currently, Flang generates reduction operation for the below implementation only:

```f90
!$omp parallel
!$omp do reduction(max:x)
do i=1, 100
  x = max(y(i), x)
end do
!$omp end do
!$omp end parallel
```

Refer test case `flang/test/Lower/OpenMP/wsloop-reduction-max.f90` and update this testcase to test reduction operation generation for the above first case as well.

**Comment by tblah** [comment]
This is fixed with current flang main
