### ISSUE TITLE
Clang rejects out-of-line definition for class template specialisation when a member function template has a requires-clause

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#61809]
GCC is under the assumption that it is valid code, and I'm inclined to agree.
```cpp
template <class T> concept C = sizeof(T) == 8;
template <class T> struct A {
  template <class U> U f(U) requires C<typename T::type>; // #1
  template <class U> U f(U) requires C<T>; // #2
};

template <> template <class U> U A<int>::f(U) requires C<int> { } // OK, specializes #2
```
Clang diagnostic:
```console
error: out-of-line definition of 'f' does not match any declaration in 'A<int>'
template <> template <class U> U A<int>::f(U) requires C<int> { } // OK, specializes #2
```

**Comment by cjdb** [comment]
@erichkeane The title might be a bit misleading, but I can't seem to word it any better :(

**Comment by erichkeane** [comment]
This is a duplicate I think.  I forget who is working on it, but there is a patch up for review in Phab(that I tried to find the other day, but cannot find!) with tons of work to this part of the code.  We're waiting on richard to review.

**Comment by usx95** [comment]
You might referring to https://reviews.llvm.org/D146178

**Comment by erichkeane** [comment]
Yep, this is the one! https://reviews.llvm.org/D146178

Thank you!  I searched for that for like 20 minutes in phab the other day and couldn't for the life of me find it.
