### ISSUE TITLE
flang fails to compile omp_lib from llvm/openmp

### ISSUE THREAD

**Issue by MehdiChinoune** [llvm/llvm-project#61829]
It's very strange to see flang failing to compile the omp_lib file from llvm/openmp
https://github.com/llvm/llvm-project/blob/main/openmp/runtime/src/include/omp_lib.f90.var

I have to comment those `!DIR$` directives to make it compile.

**Comment by EugeneZelenko** [comment]
@MehdiChinoune: Please elaborate.
