### ISSUE TITLE
[x86] gfortran and fang-new have different output assemble syntax

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#61834]
* Test: https://gcc.godbolt.org/z/eMx8Ex7xG

* GFortran uses **Intel** syntax
```asm
square_:
        mov     eax, DWORD PTR [rdi]
        imul    eax, eax
        ret
```
* flang-new uses **AT&T** syntax
```asm
square_:
        movl    (%rdi), %eax
        imull   %eax, %eax
        movl    %eax, -4(%rsp)
        retq
```

**Comment by phoebewang** [comment]
For Clang, we have option `-inline-asm=[intel,att]` to choose the syntax. I know nothing about gfortran/fang-new, but I found the Godbolt provides choices for gfortran https://gcc.godbolt.org/z/G4nxbsWq1, which may mean gfortran provides a similar option as well.

**Comment by vfdff** [comment]
Thanks for  @phoebewang, so with your link  https://gcc.godbolt.org/z/G4nxbsWq1, it is more clear that **the flang-new should be improve on codegen**.
![image](https://user-images.githubusercontent.com/6094516/229001078-3e42d69f-019c-4dd8-9d40-c1603876372b.png)
