### ISSUE TITLE
Inconsistent function pointer declaration spacing on recent trunk

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#61841]
Hi,

We are bumping clang-format from:
`15_15~%2b%2b20220316052642%2b11a12544b5fd-1~exp1~20220316172739.191`
to:
`17_17~%2b%2b20230328053227%2b498e1506981f-1~exp1~20230328173331.583`

And are now getting inconsistent function pointer alignment. Example:

```cpp
using Foo = int (*)(int);
template <typename Op = int (*)(int)>
void foo();
```

Gets transformed with default settings into:

```cpp
using Foo = int (*)(int);
template <typename Op = int(*)(int)> void foo();
```
Note how the space between `int (*)` has been removed in the case of the template. I haven't found anything related to this in the Release Notes, do you know what could it be due to?

Thanks!

**Comment by rymiel** [comment]
Bisected to bb4f6c4dca98a47054117708015bb2724256ee83... my own patch, oops

I sorta expected this could be a problem, but I couldn't come up with a non-contrived example, so thank you for providing one, I will fix this soon

**Comment by carlosgalvezp** [comment]
Thank you for the quick answer! Let me know if I can help with anything :)

**Comment by mydeveloperday** [comment]
> Thank you for the quick answer! Let me know if I can help with anything :)

@carlosgalvezp keep them coming... we are reading them..

**Comment by rymiel** [comment]
Patch: https://reviews.llvm.org/D147318

**Comment by carlosgalvezp** [comment]
Damn that was fast, really appreciate your responsiveness! :)
