### ISSUE TITLE
Unclear use case of MaxEmptyLinesToKeep

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#61843]
Hi!

I notice that clang-format has added the `AlignTrailingComments` option, with sub-options `OverEmptyLines` and `MaxEmptyLinesToKeep`. I don't fully understand the purpose of `MaxEmptyLinesToKeep` if we already have `OverEmptyLines`, could this clarified? 

For consistency it would be good to also clarify that `MaxEmptyLinesToKeep` is of type `unsigned`.

Thanks!

**Comment by mydeveloperday** [comment]
`OverEmptyLines ` is how many empty lines the `AlignTrailingComments`  aligns over, `MaxEmptyLinesToKeep`  is the number of blank lines to keep, these numbers might not be the same, hence the documentation mentions the cases where OverEmptyLines  is less than MaxEmptyLinesToKeep in which case the alignment would be broken.

**Comment by mydeveloperday** [comment]
All types of all options are identified in the documentation

![image](https://user-images.githubusercontent.com/16046346/229281002-74069080-a4f4-4439-a7bc-9f06ddbf3fa7.png)

https://clang.llvm.org/docs/ClangFormatStyleOptions.html

However its type can be subject to change.

**Comment by mydeveloperday** [comment]
If you have more clarifying question feel free to reopen this issue
