### ISSUE TITLE
[clang] Incorrect Optimization On Pointer Arithmetic

### ISSUE THREAD

**Issue by dkw72n** [llvm/llvm-project#61849]
reproduce code
```cpp
class Ptr {
  int* _r;
  inline void m_set(int* p){
    _r = p + 1;
  }
  inline int* m_get(){
    return _r - 1;
  }
public:
  Ptr(int* p) { this->m_set(p); };
  inline operator bool() {
    return !!m_get();
  }
};

int main()
{
  Ptr p((int*)0);
  while(p);
  return 0;
}
```
when compile with `-O0` or `-O1`, the output returns 0 as expected.
when compile with `-O2` or higher, the output is an infinite loop;

this issue first appeared at clang 3.3, and affects all archs (those i can test with godbolt), godbolt link below:
https://godbolt.org/z/59j8GT1KG

gcc also share the same issue since gcc 9, FYI.

**Comment by nikic** [comment]
Adding a non-zero value to a null pointer (in C) or adding any value to a null pointer (in C++) is undefined behavior.
