### ISSUE TITLE
ODR vialotion in mlir-cpu-runner + libmlir_async_runtime.so

### ISSUE THREAD

**Issue by banach-space** [llvm/llvm-project#61856]
Hi,

The following `RUN` line from [async-group.mlir](https://github.com/llvm/llvm-project/blob/cf60d3f1a688671c8eb7859bf0572c403c3c0cca/mlir/test/mlir-cpu-runner/async-group.mlir#L9-L13) leads to ODR violation:

```mlir
// RUN: | mlir-cpu-runner  \
// RUN:     -e main -entry-point-result=void -O0 \
// RUN:     -shared-libs=%mlir_c_runner_utils  \
// RUN:     -shared-libs=%mlir_runner_utils  \
// RUN:     -shared-libs=%mlir_async_runtime  \
```

Specifically, on my development AArch64 machine running Linux (I doubt the platform actually matters), I see the following:
```console
$ nm libmlir_async_runtime.so | grep EnableABIBreakingChecks

000000000038cb80 B _ZN4llvm23EnableABIBreakingChecksE

$ nm mlir-cpu-runner | grep EnableABIBreakingChecks
000000000474364c B _ZN4llvm23EnableABIBreakingChecksE
```

And indeed, ASan is able to identify the invocation from `async-group.mlir` as ODR violation, see [sanitizer-x86_64-linux-fast](https://lab.llvm.org/buildbot/#/builders/5/builds/32500). 

This patch implements a workaround that helps silence ASan (there's also a bit more discussion there):
* https://reviews.llvm.org/D146935. 

However, that's not a proper solution. To me it feels that `libmlir_async_runtime.so` should be refactored to fix this, but this isn't really my area of expertise and recommendations (as well as volunteers) are welcome :)

CC @lhames @hctim 

-Andrzej

**Comment by joker-eph** [comment]
I think that this indicates that libLLVMSupport is statically linked in the two libraries.

One way to handle it could be to link this as an internal library (hide all symbols): the ` libmlir_async_runtime.so` should not need to expose more than handful of entry points?

**Comment by banach-space** [comment]
> I think that this indicates that libLLVMSupport is statically linked in the two libraries.

Yeah, that's the case:
```bash
cmake -DCMAKE_CXX_FLAGS="-Wl,--trace-symbol=_ZN4llvm23EnableABIBreakingChecksE"
ninja -v  mlir_async_runtime
/usr/bin/clang++-14 -fPIC -Wl,--trace-symbol=_ZN4llvm23EnableABIBreakingChecksE -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Werror=mismatched-tags -Werror=global-constructors -O3 -DNDEBUG  -Wl,--gdb-index -fuse-ld=lld  -Wl,-z,defs -Wl,-z,nodelete -Wl,--color-diagnostics   -Wl,--gc-sections -shared -Wl,-soname,libmlir_async_runtime.so.17git -o lib/libmlir_async_runtime.so.17git tools/mlir/lib/ExecutionEngine/CMakeFiles/mlir_async_runtime.dir/AsyncRuntime.cpp.o  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVMSupport.a  -lrt  -ldl  -lm  /usr/lib/aarch64-linux-gnu/libz.so  /usr/lib/aarch64-linux-gnu/libzstd.so  /usr/lib/aarch64-linux-gnu/libtinfo.so  lib/libLLVMDemangle.a && :
lib/libLLVMSupport.a(ABIBreak.cpp.o): definition of _ZN4llvm23EnableABIBreakingChecksE
```

> 
> One way to handle it could be to link this as an internal library (hide all symbols): the ` libmlir_async_runtime.so` should not need to expose more than handful of entry points?

So I think that this is already meant to be happening: https://github.com/llvm/llvm-project/blob/89c4acd0c1f85f7a9ada84ea068d7b708d41bfeb/mlir/lib/ExecutionEngine/CMakeLists.txt#L169

Just to confirm - this would "hide" the symbols, but there still would be multiple definition of `EnableABIBreakingChecks` in:
```bash
/ RUN: | mlir-cpu-runner  \
// RUN:     -e main -entry-point-result=void -O0 \
// RUN:     -shared-libs=%mlir_c_runner_utils  \
// RUN:     -shared-libs=%mlir_runner_utils  \
// RUN:     -shared-libs=%mlir_async_runtime 
```

**Comment by joker-eph** [comment]
> Just to confirm - this would "hide" the symbols, but there still would be multiple definition of EnableABIBreakingChecks in:

Yes, libSupport is an implementation detail of `mlir_async_runtime` I believe, we can hide a private copy in there.

**Comment by banach-space** [comment]
This took a bit of digging, but does the job:

```bash
target_link_options(mlir_async_runtime PRIVATE "-Wl,-exclude-libs,ALL")
```

I'll update https://reviews.llvm.org/D146935 accordingly. Does this make sense to you?
