### ISSUE TITLE
[clang-16 regression] Nested template friend function declaration inside template class clashes with different symbol in inline namespace

### ISSUE THREAD

**Issue by jdrouhard** [llvm/llvm-project#61851]
Reproducible on Clang 16/trunk (and 10), but not 11-15 or GCC:

```cpp
namespace A {
    inline namespace B {
        inline constexpr struct {} foo;
    }

    template <typename T>
    class Bar {
        template <typename U>
        friend void foo(U &&arg) {}
    };
}

void foobar() {
    A::Bar<int> b;
}
```

Clang 16 and trunk reject this with:
```console
<source>:9:21: error: redefinition of 'foo' as different kind of symbol
        friend void foo(U &&arg) {}
                    ^
<source>:14:17: note: in instantiation of template class 'A::Bar<int>' requested here
    A::Bar<int> b;
                ^
<source>:3:36: note: previous definition is here
        inline constexpr struct {} foo;
                                   ^
1 error generated.
Compiler returned: 1
```

Changing either `Bar` to be a non-template, or the `friend foo()` declaration to be a non-template allows it to compile without issue.

Godbolt link: https://godbolt.org/z/q38sanqMY

**Comment by shafik** [comment]
I believe clang is wrong here, simply defining the function should be ok, although calling the function may be difficult.

**Comment by shafik** [comment]
It looks like the regression is due to this change: https://reviews.llvm.org/D135370 which is commit: b62f5fb64edec7f5917a233bf0a9a30e1e4b70f0

Hopefully @troyj-gh can put in a fix, otherwise I can take a look at it

**Comment by shafik** [comment]
PR: https://reviews.llvm.org/D147762
