### ISSUE TITLE
Backport "[ARM] Handle generating SEH unwind info for t2STR_PRE/t2LDR_POST" to 16.x

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#61861]
(There's probably no rush to get this into 16.0.1 - deferring it until 16.0.2 is fine too, but I'm filing the request now anyway.)

**Comment by mstorsjo** [comment]
The backport should be amended with b206145323fafc75d82efcc7e154218e37480953 too - @tru how do I add that to the backport PR branch?

**Comment by tru** [comment]
Just the cherry pick command with both commits with space in between

**Comment by mstorsjo** [comment]
/cherry-pick c5383536cb6824391f99f8f5963fc1427dd1673f b206145323fafc75d82efcc7e154218e37480953
