### ISSUE TITLE
hello when i try to compile c++ or c with clang 15 i get error

### ISSUE THREAD

**Issue by GmosNM** [llvm/llvm-project#61864]
![image](https://user-images.githubusercontent.com/37900384/229089477-429c3148-3cc3-4159-bbf0-6ae9d0ba2216.png)

**Comment by DimitryAndric** [comment]
`libcmt.lib` is the static Microsoft C runtime library, which should normally be found under your Visual Studio installation directory. Typically, the location of these libraries is found via environment variables, and usually the environment variables are setup using a batch file shipped with Visual Studio. See https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170 for more information.

In your case, I think you need to start one of the "Tools Command Prompt for VS 2022" shortcuts that Visual Studio should have installed into your start menu.

**Comment by GmosNM** [comment]
@DimitryAndric thank you but i just used clang++ and it works now, i was using clang on a c++ codebase

**Comment by GmosNM** [comment]
@DimitryAndric sorry but it just works on a simple hello world c++ but why i try and compile a bigger project i get the same:
i did what you said :
1 
![image](https://user-images.githubusercontent.com/37900384/229371493-df0a499c-cecf-42d8-8926-cc466d74bebf.png)
and then tried to compile:
![image](https://user-images.githubusercontent.com/37900384/229371525-e601a583-aeff-40c9-b6bb-6e87770838d6.png)
with the -v:
![image](https://user-images.githubusercontent.com/37900384/229371550-b24d2f3c-4ef3-4e46-a119-8fb521a09fe7.png)

**Comment by GmosNM** [comment]
and this is the windows lib folder in vs:
![image](https://user-images.githubusercontent.com/37900384/229371663-fe669f41-96f4-42da-bd94-01a4d63a8895.png)
