### ISSUE TITLE
Running lldb.exe does nothing

### ISSUE THREAD

**Issue by Bambofy** [llvm/llvm-project#61878]
After installing LLVM using the .exe provided in the releases page, the compiler works great but when i try to run the lldb.exe it doesn't seem to work. If i use the powershell and run "lldb.exe" nothing happens, and if i try to double-click it from the windows explorer, it reports this error. "The code execution cannot proceed because python310.dll was not found. Reinstalling the program may fix this problem.".

**Comment by alvinhochun** [comment]
Basically the same as #59695 and the handful of related issues. The fix is to download "Windows embeddable package (64-bit)" from https://www.python.org/downloads/release/python-31010/ and extract it next to lldb.exe.

**Comment by Bambofy** [comment]
> Basically the same as #59695 and the handful of related issues. The fix is to download "Windows embeddable package (64-bit)" from https://www.python.org/downloads/release/python-31010/ and extract it next to lldb.exe.

Extracting the entire "windows embedded package x64" into the lldb.exe's folder resolved the problem, thanks.

**Comment by itaiferber** [comment]
Just ran into this myself — very frustrating to figure out. @alvinhochun, since you've linked a few similar issues, perhaps you're aware: is there a central issue tracking why LLDB can't use `python310.dll` from `%PATH%`?

**Comment by alvinhochun** [comment]
LLDB should be able to use `python310.dll` from PATH, that is part of the standard DLL search paths on Windows. It would not work however, if `python310.dll` on PATH is for a different architecture than the build of LLDB you want to run.

As for a central tracking issue, I am not aware of there being one yet.

**Comment by iosifzota** [comment]
I still have this issue with lldb version 20.1.8. It's a bit tricky, I only saw the error message about missing python dll after running "lldb --version".

If I run just "lldb" in terminal I get this:
[process exited with code 3221225781 (0xc0000135)]

Which is pretty confusing.
