### ISSUE TITLE
Lambda instantiation error is silently skipped as substitution failure

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#61889]
The following program
```cpp
template <class T, auto F = [](T x) { *x; }>
void foo(T) {}

void foo(...) {}

int main() {
    foo(42);
}
```
is invalid and rejected by GCC and MSVC, but Clang accepts it, selecting `foo(...)` overload. Online demo: https://gcc.godbolt.org/z/6hTjzqsoc

Related discussion: https://stackoverflow.com/q/75889477/7325599

**Comment by cor3ntin** [comment]
Fixed in trunk!
