### ISSUE TITLE
flang-16 from apt.llvm.org doesn't work at all

### ISSUE THREAD

**Issue by MehdiChinoune** [llvm/llvm-project#61887]
I tried to build this simple program
```f90
program test
  print*, "Hello"
end program
```

```console
$ flang-new-16 -flang-experimental-exec main.f90 -o main.x
/usr/bin/ld: cannot find -lFortran_main: No such file or directory
/usr/bin/ld: cannot find -lFortranRuntime: No such file or directory
/usr/bin/ld: cannot find -lFortranDecimal: No such file or directory
flang-new: error: linker command failed with exit code 1 (use -v to see invocation)
```
These libraries do not exist anywhere!

**Comment by MehdiChinoune** [comment]
These 3 libraries `Fortran_main`, `FortranRuntime` and `FortranDecimal` are runtime libraries, not development ones, should be packaged separately.

**Comment by MehdiChinoune** [comment]
I have to:
- Install libflang-16-dev
- add `-L/usr/lib/llvm-16/lib/` to LDFLAGS

**Comment by sscalpone** [comment]
@banach-space is the need to add to LDFLAGS an issue with flang-new?

**Comment by MehdiChinoune** [comment]
At least makes flang-16 depends on libflang-16-dev.

**Comment by banach-space** [comment]
> @banach-space is the need to add to LDFLAGS an issue with flang-new?

All the required search paths should be already included. However, we didn’t really envisage linking against libflang.

@MehdiChinoune , could you run `flang-new -v <other args>` and share the output?

**Comment by MehdiChinoune** [comment]
I think It was my fault, I should add `-flang-experimental-lang`.
```
$ flang-new-16 -v main.f90 -o main.x
Ubuntu flang-new version 16.0.1 (++20230328073357+42d1b276f779-1~exp1~20230328073502.65)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-16/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/lib/llvm-16/bin/flang-new" -fc1 -triple x86_64-pc-linux-gnu -emit-obj -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -pic-is-pie -target-cpu x86-64 -o /tmp/main-374a2f.o -x f95-cpp-input main.f90
 "/usr/bin/ld" -pie -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o main.x /lib/x86_64-linux-gnu/Scrt1.o /lib/x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/12/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/12 -L/usr/lib/gcc/x86_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/lib -L/usr/lib /tmp/main-374a2f.o -lFortran_main -lFortranRuntime -lFortranDecimal -lm -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/12/crtendS.o /lib/x86_64-linux-gnu/crtn.o
/usr/bin/ld: cannot find -lFortran_main: No such file or directory
/usr/bin/ld: cannot find -lFortranRuntime: No such file or directory
/usr/bin/ld: cannot find -lFortranDecimal: No such file or directory
flang-new: error: linker command failed with exit code 1 (use -v to see invocation)
$ flang-new-16 -flang-experimental-exec -v main.f90 -o main.x
Ubuntu flang-new version 16.0.1 (++20230328073357+42d1b276f779-1~exp1~20230328073502.65)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-16/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/lib/llvm-16/bin/flang-new" -fc1 -triple x86_64-pc-linux-gnu -emit-obj -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -pic-is-pie -target-cpu x86-64 -o /tmp/main-1675af.o -x f95-cpp-input main.f90
 "/usr/bin/ld" -pie -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o main.x /lib/x86_64-linux-gnu/Scrt1.o /lib/x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/12/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/12 -L/usr/lib/gcc/x86_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/lib -L/usr/lib /tmp/main-1675af.o -L/usr/lib/llvm-16/lib -lFortran_main -lFortranRuntime -lFortranDecimal -lm -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/12/crtendS.o /lib/x86_64-linux-gnu/crtn.o
```

**Comment by banach-space** [comment]
@MehdiChinoune , I assume that you meant to close this?

**Comment by MehdiChinoune** [comment]
No, flang-16 still doesn't depend on libflang-16-dev

**Comment by banach-space** [comment]
> No, flang-16 still doesn't depend on libflang-16-dev

It shouldn't. And the original issue has been resolved.

**Comment by MehdiChinoune** [comment]
> It shouldn't. And the original issue has been resolved.

Could you tell me, why?
```
$ flang-new-16 -flang-experimental-exec main.f90 -o main
/usr/bin/ld: cannot find -lFortran_main: No such file or directory
/usr/bin/ld: cannot find -lFortranRuntime: No such file or directory
/usr/bin/ld: cannot find -lFortranDecimal: No such file or directory
flang-new: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by banach-space** [comment]
I don't follow - in your earlier post you said that adding `flang-experimental-exec` fixes the issue:

> I think It was my fault, I should add `-flang-experimental-lang`.
> 
> ```
> $ flang-new-16 -v main.f90 -o main.x
> Ubuntu flang-new version 16.0.1 (++20230328073357+42d1b276f779-1~exp1~20230328073502.65)
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/lib/llvm-16/bin
> Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
> Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
> Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
> Candidate multilib: .;@m64
> Selected multilib: .;@m64
>  "/usr/lib/llvm-16/bin/flang-new" -fc1 -triple x86_64-pc-linux-gnu -emit-obj -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -pic-is-pie -target-cpu x86-64 -o /tmp/main-374a2f.o -x f95-cpp-input main.f90
>  "/usr/bin/ld" -pie -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o main.x /lib/x86_64-linux-gnu/Scrt1.o /lib/x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/12/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/12 -L/usr/lib/gcc/x86_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/lib -L/usr/lib /tmp/main-374a2f.o -lFortran_main -lFortranRuntime -lFortranDecimal -lm -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/12/crtendS.o /lib/x86_64-linux-gnu/crtn.o
> /usr/bin/ld: cannot find -lFortran_main: No such file or directory
> /usr/bin/ld: cannot find -lFortranRuntime: No such file or directory
> /usr/bin/ld: cannot find -lFortranDecimal: No such file or directory
> flang-new: error: linker command failed with exit code 1 (use -v to see invocation)
> $ flang-new-16 -flang-experimental-exec -v main.f90 -o main.x
> Ubuntu flang-new version 16.0.1 (++20230328073357+42d1b276f779-1~exp1~20230328073502.65)
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/lib/llvm-16/bin
> Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
> Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
> Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
> Candidate multilib: .;@m64
> Selected multilib: .;@m64
>  "/usr/lib/llvm-16/bin/flang-new" -fc1 -triple x86_64-pc-linux-gnu -emit-obj -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -pic-is-pie -target-cpu x86-64 -o /tmp/main-1675af.o -x f95-cpp-input main.f90
>  "/usr/bin/ld" -pie -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o main.x /lib/x86_64-linux-gnu/Scrt1.o /lib/x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/12/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/12 -L/usr/lib/gcc/x86_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/lib -L/usr/lib /tmp/main-1675af.o -L/usr/lib/llvm-16/lib -lFortran_main -lFortranRuntime -lFortranDecimal -lm -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/12/crtendS.o /lib/x86_64-linux-gnu/crtn.o
> ```

What has changed since then?

**Comment by MehdiChinoune** [comment]
Fixes the issue of building an executable without specifying libraries location.

**Comment by banach-space** [comment]
Generating executables without `-flang-experimental-exec` is not supported atm.
