### ISSUE TITLE
flang: c_long_double has a wrong value on many platforms.

### ISSUE THREAD

**Issue by MehdiChinoune** [llvm/llvm-project#61896]
`long double` is the same as `double` on many platforms MINGW/aarch64, MSVC, macOS-aarch64.
It should have value of 8 on https://github.com/llvm/llvm-project/blob/ed372d194f938b750855ad1297517d26f1102250/flang/module/iso_c_binding.f90#L56:L60
I tried to fix it, but Flang doesn't predefine many macros, there is no macros for OSs, CPUs, Platforms. There is only `__x86_64__`  (other than flang, openmp and openacc directives).

**Comment by sscalpone** [comment]
@banach-space Are there plans for flang-new to predefine more macros, perhaps aligning with clang?

**Comment by tschuett** [comment]
No, the discussion died. Here is another example: https://reviews.llvm.org/D147768

**Comment by tschuett** [comment]
For predefined macros:
* How is it going to work with cross-compile?
* Do you need the precise Windows version? 
* Does it suffice to be able to distinguish between OpenBSD and NetBSD?
* Do you need to be able to detect AVX-512 ER?

**Comment by banach-space** [comment]
@tschuett , these are good questions! I don't know the answers, but one could check what Classic Flang and GFortran do to better understand the requirements. Also, I'd ask on Discourse.

> How is it going to work with cross-compile?

I'm under the impression that that's relatively low on everyone's priority list.

**Comment by MehdiChinoune** [comment]
Please, don't reopen.

**Comment by EugeneZelenko** [comment]
@MehdiChinoune: Please elaborate.
