### ISSUE TITLE
defining struct/class code and finishing impl later in an export { } block

### ISSUE THREAD

**Issue by ar-visions** [llvm/llvm-project#61890]
```cpp
module;

export module test_mod;

export {
struct test_me {
    void test_method();
};

void test_me::test_method() { /// fatal error: cannot export 'test_method' as it is not at namespace scope [?]
    printf("test");
}
}

// this works:
module;

export module test_mod;

export struct test_me {
    void test_method();
};

void test_me::test_method() { /// works.
    printf("test");
}


// this also works:
module;

export module test_mod;

export {
struct test_me {
    void test_method();
};
}

void test_me::test_method() { /// works.
    printf("test");
}
```
version / target:
```console
clang version 17.0.0 (https://github.com/llvm/llvm-project f66b9fe5876d670b38351c9a7efd90e793f35a30)
Target: arm64-apple-darwin22.3.0
```

my issue:
...putting it all in `export { }` works on MSVC.  its declared exported above and finished inside. What namespace would it be referring to? if the `export { }` creates the namespace its certainly inside it in the error case?

**Comment by ChuanqiXu9** [comment]
> what namespace would it be referring to?

In this case it refers to the global namespace. The standard says we shouldn't export things which are not in namespace scope. I think the current behavior may not be wrong simply. Maybe MSVC is smarter in this case.

**Comment by ar-visions** [comment]
So in other words its kind of in a double export where as that namespace lookup should fall through based on it being exported at expression of struct/class?  I just trying to swap head around.

**Comment by ChuanqiXu9** [comment]
> so that namespace association should fall through based on it being exported at expression of struct/class (because it cannot be expressed at the membership level)? just trying to wrap head around.

I am not sure if I understand your question well. But the export block is a transparent context. In other words, it doesn't have semantical meaning to the process of lookups. Or you can think it is orthogonal with namespaces.

**Comment by ar-visions** [comment]
If I find where this is applied, would a PR be acceptable to fix?

**Comment by ChuanqiXu9** [comment]
> Thank you. If I find where this is applied, would a PR be acceptable to fix?

No... I know where this is applied. I mean this may not be good to be fixed... Since we don't want the users to think they can export the entities which are not at namespace scope. This is by design.
