### ISSUE TITLE
[libc++] `std::type_index::operator<=>` may call `__builtin_strcmp` twice

### ISSUE THREAD

**Issue by frederick-vs-ja** [llvm/llvm-project#61906]
When the two referenced `type_info` are not equal, the current implementation of `type_index::operator<=>` in libc++ may needed to call `__builtin_strcmp` twice (each in `type_info::operator==` and `type_info::before`).
https://github.com/llvm/llvm-project/blob/219ff07f72c4ff5ec0563678fceaa60e1bddd56d/libcxx/include/typeindex#L92-L98

IIUC whenever it's necessary to call `__builtin_strcmp` from `operator<=>`, we should just call it once and return `__builtin_strcmp(...) <=> 0`. Perhaps it would be better to add a member function to `type_info` for convenience.

**Comment by philnik777** [comment]
Looking at the code gen, the implementation looks just fine: https://godbolt.org/z/3qd76sW5E
