### ISSUE TITLE
Use PTX register for warpSize in generated IR instead of inserting constant value of 32

### ISSUE THREAD

**Issue by soconne** [llvm/llvm-project#61903]
Currently the LLVM IR generated from calls to warpSize in CUDA kernels defaults to a constant value of 32.  The comment in _clang_cuda_builtin_vars.h indicates there is no built-in to retrieve it.
https://github.com/llvm/llvm-project/blob/main/clang/lib/Headers/__clang_cuda_builtin_vars.h#L114

However ptx has a dedicated register: llvm.nvvm.read.ptx.sreg.warpsize().
https://llvm.org/docs/NVPTXUsage.html#llvm-nvvm-ptr-to-gen-intrinsics

While current NVIDIA GPU architectures default to a warpsize of 32 lanes, this may not always be the case, which may break existing compiled code.

**Comment by Artem-B** [comment]
CUDA's own headers are defining `warpSize` as a constant 32 (though it appears to be a fallback and the macro actually should be set by NVCC). If/when it becomes a different value, it will come with a new CUDA version and we will adapt the headers to match CUDA, as necessary. 

Right now I do not see any benefit of replacing it with an intrinsic which would make it an unknown (to LLVM) value and would potentially affect performance now, when there no indications that the warp size will ever actually change.

For all practical purposes, the PTX instruction is only (marginally) useful in case when one wants to compile something to PTX once and use it on different future GPUs. This is something almost never used in practice as usually the code is compiled to and executed via specific GPU instructions, for which we do know the warp size at compilation time, even if it ever becomes different in the future for some GPUs. I believe warpSize will always remain a constant in clang and CUDA headers, even if its value may change for a specific GPU.

**Comment by Artem-B** [comment]
PTX spec also treats it as a constant: https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#cooperative-thread-arrays

```
Some applications may be able to maximize performance with knowledge of the warp size, so PTX includes a run-time immediate constant, WARP_SZ, which may be used in any instruction where an immediate operand is allowed.
```

So, the comment in the clang headers is still valid. Even though we do have an intrinsic to access `WARP_SZ` value in the IR, there's no benefit of using it from clang.
