### ISSUE TITLE
A throw exception pragram was coredump after bolt optimize.

### ISSUE THREAD

**Issue by lingchengfenzi** [llvm/llvm-project#61908]
There is a demo code that was throw execption and would catch it. It would to coredump after I use llvm-bolt to optimize it. The source code is:

```cpp
#include <stdio.h>

class ExceptionA {
};

void foo() {
  int count = 0;
  while(true){
  try {
    printf("ttttt\n");
    if(count++ < 2){
      throw ExceptionA();
    }
    return;
  }
  catch(ExceptionA&){
    printf("cccc\n");
    continue;
  }
}
}

int main() {
  foo();
  return 0;
}
```

I use the command to compile it and BOLT optimized:
```shell
clang++ main.cc -pthread  -fPIC -std=libc++  -Wl,-q  -lc++abi  -std=gnu++14 -o main
llvm-bolt main -o main.bolt
./main.bolt

# after run it, it was output like:
ttttt
Segmentation fault (core dumped)
```

And it would not to coredump after BOLT optimize when the compile command like this:

```shell
clang++ main.cc -pthread  -fPIC  -Wl,-q   -o main
```

**Comment by lingchengfenzi** [comment]
Thanks for your reply. I try again by use clang15 and it works ok. Clang11 is used extensively in our projects. So can you tell me which patch fix it?

**Comment by aaupov** [comment]
I didn't track down the root cause. But now that you've mentioned that it works with clang-15, it's possible to bisect clang commits to find which patch is it.

**Comment by lingchengfenzi** [comment]
Yes, I found the patch: https://reviews.llvm.org/D113372
But it was an indirect solution to my problem, not a commit for my issue.
