### ISSUE TITLE
[clang-cl] Failing to omit ATOMIC_VAR_INIT where it works in MSVC cl

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#61925]
CC @MaskRay @zmodem 

46262cab24312c71717ca70a9d0700481aa59152 broke building the OpenMP code with Clang-CL, while it still works to build it with MSVC and in MinGW mode.

46262cab24312c71717ca70a9d0700481aa59152 got rid of use of `ATOMIC_VAR_INIT` (which in itself expands to `{x}`) by just replacing it with `x` instead.

The issue can be observed in reduced form like this:
```c++
#include <atomic>

struct kmp_base_ticket_lock {
  std::atomic_int next_ticket;
};

static kmp_base_ticket_lock metadata_lock = {
  0
};
```
If the single initializer `0` in `metadata_lock` is replaced with `ATOMIC_VAR_INIT(0)` or plain `{0}`, the issue goes away.

With Clang-CL, compiling this test snippet produces the following error:
```console
atomic-init.cpp(8,3): error: copying member subobject of type 'std::atomic_int' (aka 'atomic<int>') invokes deleted constructor
  0
  ^
/home/martin/msvc2022/vc/tools/msvc/14.30.30705/include/atomic(2176,5): note: 'atomic' has been explicitly marked deleted here
    atomic(const atomic&) = delete;
    ^
1 error generated.
```
Same thing if building with libc++ instead of MS STL. The snippet compiles correctly with MSVC and with Clang in other modes than MSVC mode.

Note that this seems to happen while compiling in the default C++14 mode. If adding `-std:c++17` the error goes away.

**Comment by zmodem** [comment]
I won't have time to look at this until next week at least.

Should we revert or insert the extra braces to unbreak it in the meantime? Where are the openmp maintainers in all this?

**Comment by mstorsjo** [comment]
> I won't have time to look at this until next week at least.
>
> Should we revert or insert the extra braces to unbreak it in the meantime?

Well it's been broken for a month already so there's probably not that big of a rush. I don't have a specific case where I need this fixed, I just try it occasionally.

> Where are the openmp maintainers in all this?

Not sure... I'm not sure if anyone of them actually ship it built with clang-cl (even though the official llvm binaries ship it in that form).

In any case, a buildbot is sorely needed, both for catching build breaks, and for running the tests. I do build it in the mingw configuration daily, and I do run tests for those builds on github actions (e.g. https://github.com/mstorsjo/llvm-mingw/actions/runs/4602747332/jobs/8136712615), but I don't have any HW to put up for buildbots.

**Comment by mstorsjo** [comment]
Ping @zmodem @MaskRay, this is the core issue exposed by https://github.com/llvm/llvm-project/commit/46262cab24312c71717ca70a9d0700481aa59152#commitcomment-106959691, which makes OpenMP fail to be built with clang-cl.

**Comment by mstorsjo** [comment]
> > Note that this seems to happen while compiling in the default C++14 mode. If adding -std:c++17 the error goes away.
> 
> Do you know why llvm-project/openmp is compiled with C++14 instead of C++17? Doesn't llvm-project require C++17 now

I think the C++17 requirement mainly is for the tooling side, the runtimes are free to use whatever (compiler-rt is mostly C, libcxx uses the latest C++2b, etc) - but yeah I don't think i'd be unreasonable to bump OpenMP to C++17 (I haven't tested if that breaks something or not).

> So it looks like a clang-cl issue...

Yeah that's what it looks like to me too, but I don't know the finer details to know what/why.

> We can install a temporary workaround, but I think we do want to get rid of `ATOMIC_VAR_INIT`.
> 
> If the issue is in `std::atomic<kmp_int32> __kmp_team_counter = 0;`, we can just remove `= 0`.

I don't think that was one of the issues we ran into here.

> If the issue is the following, we can add `{}`
> 
> ```c++
> static kmp_base_ticket_lock metadata_lock = {
>   {0}   // add {}  or omit the field if it is a trailing field
> };
> ```

Yeah this is the same as `ATOMIC_VAR_INIT` expanded it to before - this works. Does that have any forward-compat issues with the atomic classes in future C++ versions?

**Comment by zmodem** [comment]
> So it looks like a clang-cl issue

IIUC this is the issue (without any header):

```
struct AtomicInt {
    AtomicInt();
    AtomicInt(int);
    void operator=(int);

    AtomicInt(const AtomicInt&) = delete;
    void operator=(const AtomicInt&) = delete;
};

struct S {
    AtomicInt ai;
};
static S s = {0};
```

Clang rejects that in c++14 mode, allows it in c++17 mode, and MSVC seems to always allow it: https://godbolt.org/z/E57PMx47z

I'm not enough of a language lawyer to say if Clang is right or wrong here, but it's not specific to clang-cl.

**Comment by zmodem** [comment]
> That’s weird, because OpenMP still does build fine with Clang in mingw configs

I guess mingw uses a different `std::atomic<int>`?

**Comment by mstorsjo** [comment]
> > That’s weird, because OpenMP still does build fine with Clang in mingw configs
> 
> I guess mingw uses a different `std::atomic<int>`?

Right, my mingw configs use libc++, while this uses the MS STL. Is there a relevant difference in the constructors(?) between the two?

**Comment by mstorsjo** [comment]
Closing this issue, I don't think there's anything left we need to take action on here.
