### ISSUE TITLE
Cannot represent a difference across sections due to debuginfo

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#61932]
Running https://gist.github.com/nikic/6f60958ed4295f0bcd48797b5e541aba through `llc -filetype=obj` we get errors like this:

```console
<unknown>:0: error: Cannot represent a difference across sections
<unknown>:0: error: Cannot represent a difference across sections
<unknown>:0: error: Cannot represent a difference across sections
<unknown>:0: error: Cannot represent a difference across sections
```

This is related to the debug info in some way.

**Comment by nikic** [comment]
Bisected to d20e4a1d68aa8e14c4e524e4d4eeb4445acac401. cc @DianQK @dwblaikie

**Comment by jmorse** [comment]
It looks like test2 being "cold" controls this -- looking at the textual assembly, .debug_ranges is being generated thus:

    .Ldebug_ranges0:
        .quad   .Ltmp0-.Lfunc_begin1
        .quad   .Ltmp1-.Lfunc_begin1
        .quad   .Ltmp2-.Lfunc_begin1
        .quad   .Ltmp3-.Lfunc_begin1

Where the temporary symbols are in the test1 function, and .Lfunc_begin1 is the start of test2. test2 ends up in a different section to test1, so this is an illegal cross-section reference.

Exactly why this happens is pretty unclear though: if I move test2 to the start of the input file, .debug_ranges still tries to describe test1 in terms of the end of test2, so there's something in the debug-info metadata that causes the two to be connected. test1's scope appears to be deeply buried in some types that are used for the global variable in !8, which is in CU !4's retained_nodes list. However, test1 says that it belongs to CU !1. Breaking this connection at various points in the type-scope chain, or test1's CU, makes the error go away. This gives me the impression that this is a debug-info deduplication / linking error? Exactly how that translates to test1's .debug_ranges connecting to another function still isn't clear.

(The type hierarchy metadata isn't my strong point).

**Comment by DianQK** [comment]
It may be time to apply https://reviews.llvm.org/P8297 to solve various such problems. @dwblaikie 
I will address why this happened as soon as possible to decide what to do next.

**Comment by DianQK** [comment]
I probably figured out why the debug info is often inconsistent under LTO here.
We solved some issues by determining the CU based on the parent DIE. So I want to apply the P8297 patch. I have added more construct method adjustments based on P8297. But it didn't solve the issue.

> But we should still consider applying the idea of P8297 while putting the method of constructing the DIE into DwarfDebug. I had a headache switching CU debugging in `DwarfCompileUnit.cpp`.

**The core issue I found is that DISubprogram operations [usually use getUnit](https://github.com/llvm/llvm-project/blob/238a59c3f1fcc2af2cc88f4385d81e4522f54b86/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.cpp#L2235), while [its DIE uses getScope](https://github.com/llvm/llvm-project/blob/238a59c3f1fcc2af2cc88f4385d81e4522f54b86/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.cpp#L1158). Once these two are associated with different CUs, associated DIEs may use another CU.**

If we can make the associated CU for each DIE unambiguous, these kinds of problems should all go away. But what are the rules for determining who the parent DIE of a DIE is? Ignoring the unit and following the scope chain might be the way to go.

I have created a [patch](https://reviews.llvm.org/D147620) that is just working.

**Comment by nikic** [comment]
It looks like there is no consensus on the proposed patch (https://reviews.llvm.org/D147620). @dwblaikie is arguing that the debuginfo should not be considered valid in the first place. It sounds like for LLVM 17, a new debuginfo verifier check needs to be implemented and Rust's debuginfo generation adjusted to comply with the new check.

However, this regression still needs to be fixed for LLVM 16, in a way that works with the existing debuginfo format. This is a pretty critical issue, because it breaks building some Rust projects (including Firefox) with debuginfo and LTO. As such, I'd like to propose that we just revert the original change for LLVM 16 and then work on better debuginfo verification (and fixing the fallout it entails) for LLVM 17.

/branch nikic/llvm-project/revert-pr61932

**Comment by dwblaikie** [comment]
What's the behavior before the regression (which was a bug fix for incorrect ranges base addresses, I think?), though? I think it was probably also broken - though perhaps silently so (& maybe that's acceptable, if unfortunate)?

**Comment by nikic** [comment]
@dwblaikie I'm not sure about the rest of it, but at least debug_ranges used to be well-formed. Here's the diff between LLVM 15 and 16: https://llvm.godbolt.org/z/1EsKP73Y8

Though for now my primary concern is indeed just that debuginfo generation doesn't break compilation outright -- if the generated DWARF is inaccurate in some way that would be a longer term concern.

**Comment by DianQK** [comment]
Reverting the patch is fine for me. This patch can cause Rust to fail to generate object files in some cases. Also, I realized that switching CU in such a depth of logic is not a good way to go. This patch cannot handle base address adjustment for all shared DIE cases.

> After reverting, you may also get `Cannot represent a difference across sections` errors. Because the problem of DICompositeType across CU still exists. But none of this happened in practice, probably because I missed some ELF generation implementations.

We can continue to discuss a better solution in [D147620](https://reviews.llvm.org/D147620). In fact I have reverted [D136039](https://reviews.llvm.org/D136039) in [D147620](https://reviews.llvm.org/D147620) ([D58538](https://reviews.llvm.org/D58538) also).

I added a new comment to [D147620](https://reviews.llvm.org/D147620), and the discovery at 73d697c641f18c093a9d801c82f914e255c15072 makes me think that the new patch is a more suitable solution.

**Comment by nikic** [comment]
https://github.com/rust-lang/rust/pull/111167 fixes the debuginfo generation on the rustc side, in line with @dwblaikie's recommendation. Assuming that gets approved for backport there will be no need to do anything for LLVM 16.

We should still implement a verifier check on the LLVM side. There is a suspicion that this has also caused a number of other issues that were never fully understood, so we'll want to save other people the trouble :)

**Comment by dwblaikie** [comment]
> [rust-lang/rust#111167](https://github.com/rust-lang/rust/pull/111167) fixes the debuginfo generation on the rustc side, in line with @dwblaikie's recommendation. Assuming that gets approved for backport there will be no need to do anything for LLVM 16.

*thumbs up*

> We should still implement a verifier check on the LLVM side. There is a suspicion that this has also caused a number of other issues that were never fully understood, so we'll want to save other people the trouble :)

Yeah... would be good.  @DianQK any chance you'd be up for trying that? (a verifier check that checks inlined subroutines and definition subprograms and checks that they refer to a declaration, never directly to their enclosing class?)

**Comment by DianQK** [comment]
I can try it out in my free time. This verifier check should be helpful. This issue has existed for a long time in Rust and Swift.

**Comment by dwblaikie** [comment]
Hmm do you have examples of the problem in Swift? Are they going to change to add function declarations like Rust has changed now? (@adrian-prantl @JDevlieghere )

**Comment by DianQK** [comment]
I have submitted a validation patch: https://reviews.llvm.org/D152095.
