### ISSUE TITLE
Doc: version numbers are not readable in “Clang-Format Style Options”

### ISSUE THREAD

**Issue by edgar-bonet** [llvm/llvm-project#61934]
Here is a screenshot of [ClangFormatStyleOptions.html][1], taken with Firefox 111.0.1 on Ubuntu 22.04:

---

## ![page screenshot](https://user-images.githubusercontent.com/7680786/229846524-41bad67a-cf83-4462-9677-a2538d8e585a.png)

This does not affect all version badges: versions such as “clang-format 11” are displayed properly. It appears the cause of this behavior is this inline style directive at line 10 of [ClangFormatStyleOptions.rst][2]:

```css
width: 120px;
```

Changing `with` to `min-width` fixes the problem.

[1]: https://clang.llvm.org/docs/ClangFormatStyleOptions.html
[2]: ../blob/main/clang/docs/ClangFormatStyleOptions.rst

**Comment by xgupta** [comment]
I can confirm the issue and also fix,  @edgar-bonet you may upload a patch review following this - https://llvm.org/docs/Phabricator.html#requesting-a-review-via-the-web-interface
