### ISSUE TITLE
[AArch64] Dllimport ignored on function calls in some contexts with globalisel

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#61941]
It looks like AArch64 code generation ignores/loses the `dllimport` aspect of function calls in some contexts. CC @efriedma-quic 

```c++
extern "C" __declspec(dllimport) void myFunc(void);

void call(void) {
  try { 
    myFunc();
  } catch (int) {
  } 
}
```

```console
$ clang -target aarch64-windows-gnu dllimp.cpp -S -o - | grep myFunc
        bl      myFunc
```
Even if `myFunc` is declared `dllimport`, it gets referenced as a direct function call to the symbol `myFunc`, instead of indirect via `__imp_myFunc`. This seems to be an issue with Global Isel which gets used by default in `-O0` mode; if adding `-O2` or `-mllvm -fast-isel`, it generates the expected pattern:
```console
$ clang -target aarch64-windows-gnu dllimp.cpp -mllvm -fast-isel -S -o - | grep myFunc
        adrp    x8, __imp_myFunc 
        ldr     x8, [x8, :lo12:__imp_myFunc]
```
The `try`/`catch` structure is essential here - for a plain function call without being wrapped in that, it ends up generating the right call too. If compiled targeting `aarch64-windows-msvc`, it also generates the correct reference to `__imp_myFunc`.

It seems like Global Isel bails out in all the cases where it generates the correct reference to `__imp_myFunc`; if adding `-mllvm -global-isel-abort=1`, it errors out with `fatal error: error in backend: unable to translate instruction: call (in function: _Z4callv)` (targeting `aarch64-windows-gnu`, without the `try`/`catch`) or `fatal error: error in backend: unable to translate instruction: invoke (in function: ?call@@YAXXZ)` (targeting `aarch64-windows-msvc`); this indicates that the code generation skips using Global Isel on these functions normally.

So with that context, it seems like the logic that chooses to bail out on `dllimport` function calls fails to recognize it and proceeds with Global Isel, in the case of `aarch64-windows-gnu` wrapped in `try`/`catch`.

**Comment by efriedma-quic** [comment]
I think globalisel might just be missing the code that decides how to emit a reference to a function?

**Comment by mstorsjo** [comment]
> I think globalisel might just be missing the code that decides how to emit a reference to a function?

Yes, globalisel can't generate the dllimport function calls. But the point is that we've got explicit checks in globalisel, looking for dllimport attributes and deciding to bail out of globalisel for function calls with that attribute - see https://github.com/llvm/llvm-project/blob/llvmorg-17-init/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp#L2404-L2408. The question is why this piece of code happens to slip through and generate code with globalisel, despite the dllimport on the function call.

**Comment by mstorsjo** [comment]
A fix suggestion for this is posted at https://github.com/llvm/llvm-project/pull/65864.

**Comment by mstorsjo** [comment]
This was fixed by https://github.com/llvm/llvm-project/pull/65864.
