### ISSUE TITLE
Clean up check-specific HeaderFileExtensions and ImplementationFileExtensions

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#61947]
They have been deprecated in clang-tidy 17, let's remove them completely in clang-tidy 19.

**Comment by LecrisUT** [comment]
Aren't these options being introduced in clang-tidy 17?

**Comment by EugeneZelenko** [comment]
@LecrisUT: This depends on check. Local option in many checks were added early than 17.

**Comment by carlosgalvezp** [comment]
Yes, we have introduced *global* options, replacing the check-specific options of the same name. Those are deprecated and will be removed - users should switch to the global options

**Comment by LecrisUT** [comment]
Oh, so this is about moving these options from the checks to the global option in `.clang-tidy`

**Comment by carlosgalvezp** [comment]
Yes. The options already exist globally, but for backwards compatibility we need to still keep them available locally for every check for at least 2 releases. This ticket is a reminder to remove the deprecated local options 2 releases from now.
