### ISSUE TITLE
Correct way to set up clang-tidy with CMake and Visual Studio/MSVC?

### ISSUE THREAD

**Issue by dantamont** [llvm/llvm-project#61994]
Hi all, [I have tracked down a few threads](https://gitlab.kitware.com/cmake/cmake/-/issues/20512) online that seem to imply that something like this should work using Visual Studio with CMake. 

```
find_program(
      CLANG_TIDY_COMMAND
      NAMES
         clang-tidy
      NO_CACHE
)
cmake
      set(MY_CXX_CLANG_TIDY "${CLANG_TIDY_COMMAND};--extra-arg-before=--driver-mode=cl;--extra-arg=--std=c++17;--format-style=file" CACHE INTERNAL "")

set_target_properties(${TARGET_NAME} 
    PROPERTIES 
        CXX_CLANG_TIDY "${MY_CXX_CLANG_TIDY}"

```

However, the above setup isn't working for me.  I'm getting a bunch of clang-diagnostic errors, even though my code compiles and runs just fine when Clang-Tidy is disabled. I've also tried the command with no additional flags at all, and it gives me the same result.

```console
Error	G13DA7946	use of undeclared identifier 'value' [clang-diagnostic-error]	
Error	G13DA7946	use of undeclared identifier 'value' [clang-diagnostic-error]	
Error	G13DA7946	use of undeclared identifier 'value' [clang-diagnostic-error]	
Error	G13DA7946	use of undeclared identifier 'value' [clang-diagnostic-error]	
Error	G13DA7946	use of undeclared identifier 'value' [clang-diagnostic-error]	
```

Any ideas on where I can start poking around to diagnose what is going on?

**Comment by AaronBallman** [comment]
That looks to be executing clang-tidy. `[clang-diagnostic-error]` is emitted by clang-tidy when reporting errors that come out of clang itself, rather than tidy. So it seems like something else is causing you problems (perhaps a difference in command line options between the clang-tidy execution and the regular compiler execution?).

**Comment by dantamont** [comment]
@AaronBallman Thanks for this insight, how could I go about investigating something like that? In my experience on other platforms, `clang-tidy` has been essentially plug-and-play with CMake.

**Comment by AaronBallman** [comment]
I think the first thing I would check is whether executing `clang-cl` (instead of `cl.exe` that comes with MSVC) to see if Clang issues the same error. If that's the case, then it's possible that clang and cl disagree about the code. If that's the case, then we'd have to dig into the actual code to determine which behavior is correct.

**Comment by dantamont** [comment]
Thanks Aaron, I'll look into it. I also noticed that I forgot to include the following CMake command that finds clang-tidy:

```
find_program(
      CLANG_TIDY_COMMAND
      NAMES
         clang-tidy
      NO_CACHE
)
```

Does that seem above board to you?

**Comment by AaronBallman** [comment]
That looks correct to me, and that seems to be finding a reasonable clang-tidy installation location.

**Comment by dantamont** [comment]
That's frustrating, I would just expect this to work out of the box.

**Comment by AaronBallman** [comment]
There's not enough information to figure out what the issue is. We'd need to see the source code that's getting diagnosed by clang-tidy, but currently it looks like clang-tidy *is* integrated into Visual Studio fine. Have you tried my suggestion of testing with clang-cl directly? Have you verified you're passing the same flags to clang-tidy as you are to cl? (e.g., you can definitely run into issues if you pass `-std=c++17` to clang-tidy but pass `/std:c++latest` to cl)

**Comment by dantamont** [comment]
Fair enough! I've generated a `compile_commands.json` , and pulled the representative output for one of the files:

```
{
  "directory": "C:/Users/me/Documents/Projects/my-project/builds/debug-msvc-64",
  "command": "C:\\PROGRA~1\\MICROS~2\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1435~1.322\\bin\\Hostx64\\x64\\cl.exe  /nologo /TP -DDEBUG_MODE -DDEVELOP_MODE -DLINALG_USE_EIGEN -DQT_DLL -DQT_OPENGL_LIB -DWIN32_LEAN_AND_MEAN -DWIN64 -DWITH_SDL2 -D_CRT_SECURE_NO_WARNINGS -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_FORTRESS_TEST_DIR=\\\"C:/Users/me/Documents/Projects/my-project/path_to_my_test_project\\\" -D_SOLUTION_DIR=\\\"C:/Users/me/Documents/Projects/my-project/path_to_my_test_project/../../../apps/myapp\\\" -D_UNICODE -IC:\\Users\\me\\Documents\\Projects\\my-project\\foundations\\foundations\\include -IC:\\Users\\me\\AppData\\Local\\Programs\\Python\\Python311\\include -IC:\\Users\\me\\Documents\\Projects\\my-project\\extern\\eigen\\include -IC:\\Users\\me\\Documents\\Projects\\my-project\\extern\\json\\_deps\\include -external:IC:\\Users\\me\\Documents\\Projects\\my-project\\extern\\googletest\\_deps\\googletest\\include -external:IC:\\Users\\me\\Documents\\Projects\\my-project\\extern\\googletest\\_deps\\googletest -external:W0 /permissive- /Zc:preprocessor /EHsc /Zi /Ob0 /Od /RTC1 -MDd /MP /bigobj /utf-8 /Zc:__cplusplus /wd4577 /wd4467 /wd26812 /wd26495 -std:c++17 /Fofoundations\\foundations\\tests\\CMakeFiles\\foundations_tests.dir\\main.cpp.obj /FdTARGET_COMPILE_PDB /FS -c C:\\Users\\me\\Documents\\Projects\\my-project\\foundations\\foundations\\tests\\main.cpp",
  "file": "C:\\Users\\me\\Documents\\Projects\\my-project\\foundations\\foundations\\tests\\main.cpp"
}
```

I am not sure if there is a better way to see what gets passed into `cl`, but I'm hoping this is helpful. Is there a way to see what exactly is getting passed into clang-tidy as well?

**Comment by dantamont** [comment]
Solved this out. Turns out that C++17 is being recognized, but it seems like clang-tidy needs `clang` to successfully compile the code in order to work properly. Clang seems to be more restrictive in terms of what it allows in regards to the language standard, so I had to modify some things that MSVC found acceptable but clang didn't . Long story short, cross-compilation is tricky.

**Comment by AaronBallman** [comment]
> Solved this out. Turns out that C++17 is being recognized, but it seems like clang-tidy needs `clang` to successfully compile the code in order to work properly. Clang seems to be more restrictive in terms of what it allows in regards to the language standard, so I had to modify some things that MSVC found acceptable but clang didn't . Long story short, cross-compilation is tricky.

Sorry for not making this more clear earlier -- but yes, clang-tidy uses clang to generate the information it needs for clang-tidy's checks to work, so diagnostics from clang are always emitted by clang-tidy. So this situation comes up from time to time. I'm glad you got it resolved!

**Comment by eljonny** [comment]
@dograt I came across this trying to figure out what was going on with my project and clang-tidy not running.

From your last post I noticed there was confusion over the parameter/argument format... MS has updated the parameters to at least MSBuild and CL [to now accept both / and - versions](https://learn.microsoft.com/en-us/cpp/build/reference/compiler-options?view=msvc-170).

I found that CMake wasn't generating compile_commands.json, which is what the build system running clang-tidy uses as the basis for calling clang-tidy... so it made sense why it wasn't working. Upon reading [the docs for the variable that enables generation of this file](https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html), the generation of the compile commands db file is not supported by the Visual Studio generators (only Ninja and Unix Makefile), and decided to switch to Ninja for these Windows/MSVC builds I was trying to get working, which was quite a process, but was successful. If anyone else is running into issues running clang-tidy with CMake and the Visual Studio integrations, and MSVC, I hope this can help.

Here were the basic steps I had to go through to get it working:
* Change the CMake Generator from Visual Studio (MSBuild) to Ninja
* Ran into [this issue](https://developercommunity.visualstudio.com/t/Unable-to-build-using-clang-cl-CMake-a/1670695) and [this issue](https://stackoverflow.com/questions/47581784/building-a-x86-application-with-cmake-ninja-and-clang-on-x64-windows) with compiling the project through Ninja and MSVC
* Added the following files from [this repo](https://github.com/MarkSchofield/WindowsToolchain), they are MIT Licensed, to my CMake build as toolchain files in my configuration presets in CMakePresets.json, which fixed the first issue:
  * Windows.MSVC.toolchain.cmake
  * Windows.Kits.cmake
  * Windows.Clang.toolchain.cmake
  * VSWhere.cmake
* Fixed the second issue by adding the -m32 clang-cl compilation flag and the /machine:x86 linker flag to relevant configuration presets
* Removed the modernize-use-nullptr and hicpp-use-nullptr checks in my .clang-tidy configuration file, there's a bug in the VS 2022 Clang/LLVM builds that causes clang-tidy to crash when those checks are specified (see [here](https://developercommunity.visualstudio.com/t/clang-tidy-terminates-with-Exception-Cod/10822069?pageSize=15&sort=active&openOnly=false&closedOnly=false&topics=repos) and [here](https://github.com/llvm/llvm-project/issues/53778))

After going through these steps I was able to run the Ninja builds generated through my CMake Presets and run clang-tidy successfully.

It's in my personal project [here](https://github.com/eljonny/TestCPP) that I'm working on this if anyone needs to check it out for reference.
