### ISSUE TITLE
issue in libfuzzer's RunOne function w.r.t fork-mode fuzzing

### ISSUE THREAD

**Issue by boofish** [llvm/llvm-project#61990]
Hi, I recently analyzed the fork mode of libfuzzer and found a logic error in the `Runone` function.
The basic idea is: the shortened seed needs to be kept. Otherwise, we will lose some newfound interesting seeds under the fork mode.

Specifically, in the `RunOne` function of file `FuzzerLoop.cpp`, the code

```cpp
  if (II && FoundUniqFeaturesOfII &&
      II->DataFlowTraceForFocusFunction.empty() &&
      FoundUniqFeaturesOfII == II->UniqFeatureSet.size() &&
      II->U.size() > Size) {
    auto OldFeaturesFile = Sha1ToString(II->Sha1);
    Corpus.Replace(II, {Data, Data + Size}, TimeOfUnit);
    RenameFeatureSetFile(Options.FeaturesDir, OldFeaturesFile,
                         Sha1ToString(II->Sha1));
    return true;
```

should be updated as follows (by adding `WriteToOutputCorpus({Data, Data + Size});`):

```diff
if (II && FoundUniqFeaturesOfII &&
      II->DataFlowTraceForFocusFunction.empty() &&
      FoundUniqFeaturesOfII == II->UniqFeatureSet.size() &&
      II->U.size() > Size) {
    auto OldFeaturesFile = Sha1ToString(II->Sha1);
    Corpus.Replace(II, {Data, Data + Size}, TimeOfUnit);
+   WriteToOutputCorpus({Data, Data + Size}); 
    RenameFeatureSetFile(Options.FeaturesDir, OldFeaturesFile,
                         Sha1ToString(II->Sha1));
    return true;
```

**Comment by boofish** [comment]
I have carefully tested this.  One can prepare a simple harness and check the content under the directory `/tmp/libFuzzerTemp.FuzzWithForkxxxx.dir`. Meanwhile, you are supposed to disable the function `RmDirRecursive` and `RemoveFile`, otherwise, the `/tmp/libFuzzerTemp.FuzzWithForkxxxx.dir` directory will not keep these seeds.

**Comment by xgupta** [comment]
Hi @boofish,

The issue description and solution sound correct, You may upload the patch for review -  https://llvm.org/docs/Phabricator.html#requesting-a-review-via-the-web-interface.

**Comment by Dongmuliang** [comment]
Hi @xgupta. I have uploaded the patch, but I am not sure it is OK because I am new to this process. Could you please help to give a check? The link is https://reviews.llvm.org/D147930

**Comment by boofish** [comment]
Hi @xgupta. I have uploaded the patch, but I am not sure whether it is OK because I am new to this process. Could you please help to give me a check? The link is https://reviews.llvm.org/D147930.

**Comment by xgupta** [comment]
Thanks, @boofish for uploading the patch it looks good, but I have added two more reviewers who know libfuzzer code better and can give a proper review.

**Comment by boofish** [comment]
This issue was actually caused by my mistake in customizing the libfuzzer, and it is not an issue of libfuzzer itself. I am very very sorry for taking your time and any  any inconvenience I may have caused.
