### ISSUE TITLE
Compile error section type conflict

### ISSUE THREAD

**Issue by drhaozhong** [llvm/llvm-project#61996]
The code is as follows:

```c
int cpu_ (void *attr) {}
const unsigned long _1 __attribute__((section("__"))) = (unsigned long)&cpu_ ;
const unsigned long _group __attribute__((section("__"))) = 0;
```

GCC accepts the code, but clang rejects it:

```console
ode0.c.cpp:1:24: warning: non-void function does not return a value [-Wreturn-type]
    int cpu_ (void *attr) {}
                           ^
```

GCC <4.6 also rejects this code. It is fixed in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=31490

**Comment by shafik** [comment]
The diagnostic is correct you have a value returning function that does not return a value: https://godbolt.org/z/PrxdvKvK6

but this is a warning, not gcc always warns on this w/ `-Wall` flag. 

I may be missing something, if you can provide a godbolt link with a compile failure that would be helpful.

**Comment by xgupta** [comment]
Yes, given test case is passing fine with clang also.
