### ISSUE TITLE
assert.h: duplicate text 'be able to'

### ISSUE THREAD

**Issue by rillig** [llvm/llvm-project#61999]

**Comment by EugeneZelenko** [comment]
@rillig: Please elaborate. What is file path?

**Comment by rillig** [comment]
There's only a single file named `assert.h` in the whole tree.

**Comment by michaelrj-google** [comment]
Fixed with https://reviews.llvm.org/rGd92b58525951

**Comment by rillig** [comment]
Thanks, could you perhaps replace "to capable" with "to be capable"?
I guess the changes to the `assert` macro were accidental, at least they are not mentioned in the commit message.

**Comment by michaelrj-google** [comment]
Done. 
The assert macro changes were caused by clang-format.
