### ISSUE TITLE
-Xlinker /implib:../myDir/myLib.lib      clang++.exe  parsed incorrect in '../' or './' symbols of path

### ISSUE THREAD

**Issue by Khalyutin** [llvm/llvm-project#61997]
clang version 16.0.0 and 15.0.5, win10 AMD64  and win11 arm on Paralels  in mac M1, CMake bild of wxWidgets-3.2.2.1

command  wirh key: 
  -Xlinker /implib:../lib/clang_x64_lib/wxrc.lib
abort wit error:
   lld-link: error: could not open 'C:\TOOLSET\msys64\implib;..\lib\clang_x64_lib\wxrc.lib': no such file or directory

but wirh key: 
  -Xlinker /implib:wxrc.lib
or 
  -Xlinker /implib:D:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build/base/lib/clang_x64_lib/wxrc.lib
run suseful

ERROR-COMMAND:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --progress-dir=D:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX executable ../lib/clang_x64_lib/wxrc.exe"
	cd D:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build/base/utils && C:/TOOLSET/LLVM/bin/clang++.exe -v -fuse-ld=lld-link -nostartfiles -nostdlib -Wall -Xclang -flto-visibility-public-std -g -O0 -gno-column-info                   -D_DEBUG -Xclang -flto-visibility-public-std -D_MT -Xclang --dependent-lib=libcmtd -Xlinker /subsystem:console @CMakeFiles/wxrc.dir/objects1.rsp -o ../lib/clang_x64_lib/wxrc.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:../lib/clang_x64_lib/wxrc.lib -Xlinker /pdb:D:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build/base/lib/clang_x64_lib/wxrc.pdb -Xlinker /version:0.0  @CMakeFiles/wxrc.dir/linkLibs.rsp 
ERROR-RESULT:

[main] Building folder: wxWidgets-3.2.2.1 
[build] Starting build
[proc] Executing command: C:\TOOLSET\CMake\bin\cmake.EXE --build d:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build --config Debug --target all -j 18 --
[build] [  2%] Built target wxzlib
[build] [  5%] Built target wxregex
[build] [  6%] Built target wxexpat
[build] [ 11%] Built target wxjpeg
[build] [ 26%] Built target wxscintilla
[build] [ 30%] Built target wxtiff
[build] [ 33%] Built target wxpng
[build] [ 45%] Built target wxbase
[build] [ 46%] Built target wxxml
[build] [ 48%] Built target wxnet
[build] [ 48%] Linking CXX executable ../lib/clang_x64_lib/wxrc.exe
[build] clang version 16.0.0
[build] Target: x86_64-pc-windows-msvc
[build] Thread model: posix
[build] InstalledDir: C:\TOOLSET\LLVM\bin
[build]  "C:\\TOOLSET\\LLVM\\bin\\lld-link" -out:../lib/clang_x64_lib/wxrc.exe "-libpath:C:\\TOOLSET\\msVisualStudio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\lib\\x64" "-libpath:C:\\TOOLSET\\msVisualStudio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\atlmfc\\lib\\x64" "-libpath:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\ucrt\\x64" "-libpath:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\um\\x64" "-libpath:C:\\TOOLSET\\LLVM\\lib\\clang\\16\\lib\\windows" -libpath:C:/TOOLSET/LLVM/bin/lib -nologo -debug /subsystem:console CMakeFiles/wxrc.dir/__/__/__/utils/wxrc/wxrc.cpp.obj /MANIFEST:EMBED "C:\\TOOLSET\\msys64\\implib;..\\lib\\clang_x64_lib\\wxrc.lib" /pdb:D:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build/base/lib/clang_x64_lib/wxrc.pdb /version:0.0 ../lib/clang_x64_lib/libwxbase32ud_xml.lib ../lib/clang_x64_lib/libwxbase32ud.lib ../lib/clang_x64_lib/wxzlibd.lib ../lib/clang_x64_lib/wxregexud.lib kernel32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib winmm.lib shell32.lib shlwapi.lib comctl32.lib ole32.lib oleaut32.lib uuid.lib rpcrt4.lib advapi32.lib version.lib ws2_32.lib wininet.lib oleacc.lib uxtheme.lib ../lib/clang_x64_lib/wxexpatd.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib oldnames.lib
[build] lld-link: error: could not open 'C:\TOOLSET\msys64\implib;..\lib\clang_x64_lib\wxrc.lib': no such file or directory
[build] clang++: error: linker command failed with exit code 1 (use -v to see invocation)
[build] make[2]: *** [base/utils/CMakeFiles/wxrc.dir/build.make:104: base/lib/clang_x64_lib/wxrc.exe] Error 1
[build] make[1]: *** [CMakeFiles/Makefile2:1152: base/utils/CMakeFiles/wxrc.dir/all] Error 2
[build] make[1]: *** Waiting for unfinished jobs....
[build] [ 84%] Built target wxcore
[build] make: *** [Makefile:136: all] Error 2
[proc] The command: C:\TOOLSET\CMake\bin\cmake.EXE --build d:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build --config Debug --target all -j 18 -- exited with code: 2
[build] Build finished with exit code 2

SUSEFUL-COMMAND
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --progress-dir=D:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX executable ../lib/clang_x64_lib/wxrc.exe"
	cd D:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build/base/utils && C:/TOOLSET/LLVM/bin/clang++.exe -v -fuse-ld=lld-link -nostartfiles -nostdlib -Wall -Xclang -flto-visibility-public-std -g -O0 -gno-column-info                   -D_DEBUG -Xclang -flto-visibility-public-std -D_MT -Xclang --dependent-lib=libcmtd -Xlinker /subsystem:console @CMakeFiles/wxrc.dir/objects1.rsp -o ../lib/clang_x64_lib/wxrc.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:D:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build/base/lib/clang_x64_lib/wxrc.lib -Xlinker /pdb:D:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build/base/lib/clang_x64_lib/wxrc.pdb -Xlinker /version:0.0  @CMakeFiles/wxrc.dir/linkLibs.rsp 

SUSEFUL-RESULT:
[main] Building folder: wxWidgets-3.2.2.1 
[build] Starting build
[proc] Executing command: C:\TOOLSET\CMake\bin\cmake.EXE --build d:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build --config Debug --target all -j 18 --
[build] [  2%] Built target wxzlib
[build] [  5%] Built target wxregex
[build] [  6%] Built target wxexpat
[build] [ 11%] Built target wxjpeg
[build] [ 26%] Built target wxscintilla
[build] [ 30%] Built target wxtiff
[build] [ 33%] Built target wxpng
[build] [ 45%] Built target wxbase
[build] [ 46%] Built target wxxml
[build] [ 48%] Built target wxnet
[build] [ 48%] Linking CXX executable ../lib/clang_x64_lib/wxrc.exe
[build] clang version 16.0.0
[build] Target: x86_64-pc-windows-msvc
[build] Thread model: posix
[build] InstalledDir: C:\TOOLSET\LLVM\bin
[build]  "C:\\TOOLSET\\LLVM\\bin\\lld-link" -out:../lib/clang_x64_lib/wxrc.exe "-libpath:C:\\TOOLSET\\msVisualStudio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\lib\\x64" "-libpath:C:\\TOOLSET\\msVisualStudio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\atlmfc\\lib\\x64" "-libpath:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\ucrt\\x64" "-libpath:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\um\\x64" "-libpath:C:\\TOOLSET\\LLVM\\lib\\clang\\16\\lib\\windows" -libpath:C:/TOOLSET/LLVM/bin/lib -nologo -debug /subsystem:console CMakeFiles/wxrc.dir/__/__/__/utils/wxrc/wxrc.cpp.obj /MANIFEST:EMBED /implib:D:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build/base/lib/clang_x64_lib/wxrc.lib /pdb:D:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build/base/lib/clang_x64_lib/wxrc.pdb /version:0.0 ../lib/clang_x64_lib/libwxbase32ud_xml.lib ../lib/clang_x64_lib/libwxbase32ud.lib ../lib/clang_x64_lib/wxzlibd.lib ../lib/clang_x64_lib/wxregexud.lib kernel32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib winmm.lib shell32.lib shlwapi.lib comctl32.lib ole32.lib oleaut32.lib uuid.lib rpcrt4.lib advapi32.lib version.lib ws2_32.lib wininet.lib oleacc.lib uxtheme.lib ../lib/clang_x64_lib/wxexpatd.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib oldnames.lib
[build] [ 48%] Built target wxrc
[build] [ 84%] Built target wxcore
[build] [ 84%] Linking CXX static library ../../lib/clang_x64_lib/libwxmsw32ud_adv.lib
[build] [ 84%] Linking CXX static library ../../lib/clang_x64_lib/libwxmsw32ud_gl.lib
[build] [ 84%] Linking CXX static library ../../lib/clang_x64_lib/libwxmsw32ud_qa.lib
[build] [ 84%] Linking CXX static library ../../lib/clang_x64_lib/libwxmsw32ud_stc.lib
[build] [ 84%] Linking CXX static library ../../lib/clang_x64_lib/libwxmsw32ud_media.lib
[build] [ 84%] Linking CXX static library ../../lib/clang_x64_lib/libwxmsw32ud_webview.lib
[build] [ 84%] Built target wxadv
[build] [ 84%] Linking CXX static library ../../lib/clang_x64_lib/libwxmsw32ud_propgrid.lib
[build] [ 84%] Linking CXX static library ../../lib/clang_x64_lib/libwxmsw32ud_aui.lib
[build] [ 84%] Linking CXX static library ../../lib/clang_x64_lib/libwxmsw32ud_ribbon.lib
[build] [ 84%] Built target wxgl
[build] [ 84%] Built target wxqa
[build] [ 84%] Built target wxstc
[build] [ 84%] Built target wxmedia
[build] [ 85%] Built target wxwebview
[build] [ 86%] Built target wxpropgrid
[build] [ 87%] Built target wxaui
[build] [ 87%] Linking CXX static library ../../lib/clang_x64_lib/libwxmsw32ud_html.lib
[build] [ 88%] Built target wxribbon
[build] [ 91%] Built target wxhtml
[build] [ 91%] Linking CXX static library ../../lib/clang_x64_lib/libwxmsw32ud_richtext.lib
[build] [ 93%] Built target wxrichtext
[build] [ 93%] Linking CXX static library ../../lib/clang_x64_lib/libwxmsw32ud_xrc.lib
[build] [100%] Built target wxxrc
[build] Build finished with exit code 0

**Comment by Khalyutin** [comment]
sorry, but i'm do not understand  "@llvm/issue-subscribers-clang-driver", please  elaborate if it possible

**Comment by alvinhochun** [comment]
I noticed that you are building with msys2, I presume from the other issue referencing this issue that this is with "Unix Makefiles" using msys2 bash? Then the issue you see might be caused by the automatic path conversion of msys2: https://www.msys2.org/docs/filesystem-paths/

Try setting the environment variable `MSYS2_ARG_CONV_EXCL=/implib:`. If this fixes it then it is not an issue with clang.

**Comment by Khalyutin** [comment]
Ok.  Setting the environment variable  
 MSYS2_ARG_CONV_EXCL=/implib:  
is  fixed problem.
 Thank you  :)
