### ISSUE TITLE
[clang][clang-cl][x86]In Windows 32-bit, the program generated using assembly language cannot run properly.

### ISSUE THREAD

**Issue by romanholidaypancakes** [llvm/llvm-project#62010]
1. `test.cpp`
```c++
#include "stdio.h"
#include <windows.h>


int main() {
    printf("hello world");
    MessageBoxW(0, 0, L"hello world", 0);
    return 0;
}
```

2. generate assembly
```cmd
clang-cl -m32 test.cpp /clang:-S
```
3. generating programs from assembler file
```cmd
clang-cl user32.lib -m32 test.asm -o test32.exe
```
4. When running `test32.exe`, it crashes upon calling `MessageBoxW`, indicating a failure to properly relocate imported functions. However, the same command runs successfully on the 64-bit version of the program.

**Comment by alvinhochun** [comment]
The generated assembly is

```asm
	call	dword ptr [__imp__MessageBoxW@16]
```

When compiling from the source to binary directly, this is the disassembly:

```asm
007d103f ff1510417e00    call    dword ptr [test62010+0x14110 (007e4110)]
```

When compiling from the assembly, this is what I got instead:

```asm
00b8103f e8cc300100      call    test62010_b+0x14110 (00b94110)
```

Looks like LLVM may be doing something odd with Intel asm syntax: https://godbolt.org/z/YWvrn75YG

**Comment by alvinhochun** [comment]
https://reviews.llvm.org/D149579

**Comment by alvinhochun** [comment]
Should be fixed in trunk.
