### ISSUE TITLE
miscompilation - "Illegal instruction" with exception handling in nested functions

### ISSUE THREAD

**Issue by bigbio2002** [llvm/llvm-project#62025]
The resulting executable from compiling this sample code (from C++ for Dummies, ch. 25) crashes. The output is supposed to be

```console
Constructing object a
Constructing object b
Constructing object c
Constructing object d
Destructing object d
Destructing object c
Destructing object b
Int catch
Destructing object a
```

but instead terminates with

```console
...
Destructing object b
Int catch
Illegal instruction (core dumped)
```

The code is as follows; I'm unsure what exactly is causing it to crash, but the code is very minimal as-is.

```cpp
#include <cstdio>
#include <cstdlib>
#include <iostream>

using namespace std;

class Obj
{
public:
	Obj(char c)
	{
		label = c;
		cout << "Constructing object " << label << endl;
	}
	~Obj()
	{
		cout << "Destructing object " << label << endl;
	}

protected:
	char label;
};

void f1();
void f2();
int f3()
{
	Obj a('a');
	try
	{
		Obj b('b');
		f1();
	}
	catch(float f)
	{
		cout << "Float catch" << endl;
	}
	catch(int i)
	{
		cout << "Int catch" << endl;
	}
	catch(...)
	{
		cout << string("Generic catch") << endl;
	}
}

int main(int nNumberofArgs, char* pszArgs[])
{
	f3();
	// wait until user is ready before terminating program
	// to allow the user to see the program results

	//system("PAUSE");
	return 0;
}

void f1()
{
	try
	{
		Obj c('c');
		f2();
	}
	catch(string msg)
	{
		cout << "String catch" << endl;
	}
}
void f2()
{
	Obj d('d');
	throw 10;
}
```
    

The crash occurs when compiling with Clang++ 10 and 11 as tested on Debian and Termux. It compiles and runs as expected when using G++.

**Comment by shafik** [comment]
I can't reproduce on trunk: https://godbolt.org/z/55qjKK9Wb

If you can reproduce on godbolt that would be helpful.

**Comment by bigbio2002** [comment]
Whoops, forgot to add, compiled with

`clang++ -std=c++98 CascadingException.cpp -o CascadingException-clang++`

No optimizations, though I do recall it still erred (albeit differently) when compiled with -O2 also.

**Comment by bigbio2002** [comment]
On Godbolt, the last line output was `Int catch` (consistent with my observations), with the program returning code `132` upon exit.

**Comment by efriedma-quic** [comment]
There's a warning "warning: non-void function does not return a value".  And if you use -fsanitize=undefined, you'll get an equivalent diagnostic at runtime.  I think this is working as intended.

Maybe we could consider whether there's some way to make this more obvious, like adjusting the text of the diagnostic, or turning on certain sanitizers by default at -O0.  But that seems like a discussion for https://discourse.llvm.org.
