### ISSUE TITLE
Bad replacement of `vpmaddwd` + `vpaddd` with `vpdpwssd`.

### ISSUE THREAD

**Issue by TheBlackPlague** [llvm/llvm-project#62026]
See the following instructions:
```asm
vpminsw ymm3,ymm0,YMMWORD PTR [rcx+0x20]
vpmaxsw ymm3,ymm3,ymm1
vpmaddwd ymm3,ymm3,YMMWORD PTR [r8+0x20]
vpaddd ymm2,ymm2,ymm3
```

It reads a `YMMWORD` from the address, calculates the minimum against `ymm0`, then stores it in `ymm3`. Then, it calculates the maximum between `ymm3` and `ymm1` and stores the result in `ymm3`. Furthermore, it multiplies `ymm3` with a `YMMWORD` from another address, and adds the adjacent pairs, storing the result in `ymm3` (at this point, the register is storing 8x `int32` instead of 16x `int16`). Then, it vertically adds `ymm2` and `ymm3`, storing the result in `ymm2`. 

This is a very simple part of a neural network forward propagation. Please take a look at the [uiCA uops code analyzer](https://bit.ly/3ZUJUd5) for the above instructions. The requirement of the above assembly is `AVX2`.

Now, Clang (LLVM 16.0) replaces the above assembly with the following assembly on machines that support the `AVX-VNNI` instruction set:
```asm
vpminsw ymm3,ymm0,YMMWORD PTR [rcx+0x20]
vpmaxsw ymm3,ymm3,ymm1
vpdpwssd ymm2,ymm3,YMMWORD PTR [r8+0x20]
```
It effectively leverages the `vpdpwssd` instruction, part of the `AVX-VNNI` instruction set, that fuses the operation done by `vpmaddwd` and `vpaddd`, thus replacing them. 

Furthermore, the [Intel Intrinsics Guide](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html) marks the instruction with a latency of 5, reciprocal throughput of 0.5 (same as the `vpmaddwd` instruction). However, since the non-fused version also requires the `vpaddd` instruction, which has a latency of 1 and a reciprocal throughput of 0.33, the fused instruction is theoretically supposed to finish first (have better throughput). This means it is a good replacement... right?

**It is not a good replacement!** See the [uiCA uops code analyzer](https://bit.ly/43hpSw8) for this version. In a non-expensive loop, this replacement slows the code down by 100% (taking effectively double the time). What can be done about this?

**Comment by TheBlackPlague** [comment]
It seems LLVM-mca on the `uiCA` site, notices that the first assembly performs better. This begs the question of why in `clang` it is ignoring its own knowledge.

**Comment by asl** [comment]
LLVM does not do any optimizations on the assembler level. Will you be able to attach an original reproducer?

**Comment by TheBlackPlague** [comment]
> LLVM does not do any optimizations on the assembler level. Will you be able to attach an original reproducer?

Yes. Please see the project: https://github.com/TheBlackPlague/Cerebrum

Compile it with first the `-march=native` argument if your machine has `avx-vnni` and then the `-mavx2` argument. It'll show a great speed difference, moreover the assembly will show different instruction being used.

**Comment by junaire** [comment]
Can you try to make a smaller reproducer?

**Comment by TheBlackPlague** [comment]
> Can you try to make a smaller reproducer?

That project itself is quite small. Not sure what you mean? If you compile the `BenchmarkRunner.cpp` file, it only compiles the one method which is facing the issue.

**Comment by RKSimon** [comment]
https://godbolt.org/z/Y149En1vq (search for ActivateFlattenAndForward)

This shows the use of vpdpwssd instead of vpmaddwd+vaddd - but we need to decide whether we want to avoid the fold in general or just for certain targets.

**Comment by TheBlackPlague** [comment]
> https://godbolt.org/z/Y149En1vq (search for ActivateFlattenAndForward)
> 
> This shows the use of vpdpwssd instead of vpmaddwd+vaddd - but we need to decide whether we want to avoid the fold in general or just for certain targets.

As the developer of the library, I wish that the users may utilize the `-march=native` argument rather than having to specify the architecture. Would you happen to know what I can do right now?

**Comment by phoebewang** [comment]
Maybe `-mno-avxvnni/-mno-avx512vnni`? We may need a tuning flag in compiler cc @LuoYuanke

**Comment by topperc** [comment]
> Maybe `-mno-avxvnni/-mno-avx512vnni`? We may need a tuning flag in compiler cc @LuoYuanke 

It's probably profitable to use vpdpwssd in straight line code.

In the loop case it prevents the  vpdpsswd from starting until the vpdpsswd from the previous iteration finishes.

With a separate multiply instruction, each loop iteration can starts its multiply independently. Only the 1 cycle add needs to wait.

Would moving the fold to MachineCombiner understand this?

**Comment by TheBlackPlague** [comment]
> > Maybe `-mno-avxvnni/-mno-avx512vnni`? We may need a tuning flag in compiler cc @LuoYuanke
> 
> It's probably profitable to use vpdpwssd in straight line code.
> 
> In the loop case it prevents the vpdpsswd from starting until the vpdpsswd from the previous iteration finishes.
> 
> With a separate multiply instruction, each loop iteration can starts its multiply independently. Only the 1 cycle add needs to wait.
> 
> Would moving the fold to MachineCombiner understand this?

Yes, that's the consensus my friend and I reached as well. We believed that the `vpdpwssd` instruction was hogging the register, so the next iteration's operation also has to wait. Whereas, in the case of a `vpaddd`, the next `vpmaddwd` instruction can be executed, and only the `vpaddd` instruction has to wait (which will likely be done by then, given the latency and reciprocal throughput).

**Comment by LuoYuanke** [comment]
Thanks Craig and @TheBlackPlague, I'll take a look at it.

**Comment by LuoYuanke** [comment]
Candidate patch https://reviews.llvm.org/D148980.
