### ISSUE TITLE
[clang-format] SortIncludes documentation contains contradiction in its description

### ISSUE THREAD

**Issue by michael-g-matthews** [llvm/llvm-project#62033]
The style option SortIncludes contains a contradiction between its initial description and the list of possible values.

Currently the description incorrectly states: 

> If `CaseInsensitive`, includes are sorted in an ASCIIbetical or case insensitive fashion. If `CaseSensitive`, includes are sorted in an alphabetical or case sensitive fashion

And the possible values section correctly states: 

> `SI_CaseSensitive` (in configuration: `CaseSensitive`) Includes are sorted in an ASCIIbetical or case sensitive fashion.
> `SI_CaseInsensitive` (in configuration: `CaseInsensitive`) Includes are sorted in an alphabetical or case insensitive fashion

I suggest to shorten the initial description to read: 

> Controls if and how clang-format will sort `#includes`.  ~~If `Never`, includes are never sorted. If `CaseInsensitive`, includes are sorted in an ASCIIbetical or case insensitive fashion. If `CaseSensitive`, includes are sorted in an alphabetical or case sensitive fashion.~~

This removes the contradiction and ensures there is only a singular explanation for how this style option works.

**Comment by owenca** [comment]
https://reviews.llvm.org/D147894
