### ISSUE TITLE
"inline function not defined" when compiling as a module

### ISSUE THREAD

**Issue by tchaikov** [llvm/llvm-project#62043]
A minimal reproducer looks like:

```c++
module;

export module foo;

template<typename T>
inline void func(T) noexcept;

template<>
inline void func<unsigned>(unsigned) noexcept
{}
```

the compile options are `-std=c++20 -Wall -Wextra`. tested with Clang 16 and Clang trunk at the time of writing. both of them emit error like:
```console
<source>:6:13: error: inline function not defined
inline void func(T) noexcept;
            ^
1 error generated.
```

this source file compiles fine if module related statements are removed:

```c++
template<typename T>
inline void func(T) noexcept;

template<>
inline void func<unsigned>(unsigned) noexcept
{}
```

also, both source files (with module and without module) compile fine with GCC, and `-std=c++20 -Wall -Wextra -fmodules-ts` options.

see https://godbolt.org/z/ehEGhMTcr

**Comment by ChuanqiXu9** [comment]
This is by design. See http://eel.is/c++draft/dcl.inline#7. So the behavior of GCC may be too relax here.

**Comment by tchaikov** [comment]
thanks Chanqi! Sorry for the noise.

**Comment by tchaikov** [comment]
@ChuanqiXu9 hi Chuanqi, sorry for coming back to this issue. after a second thought. i think GCC's behavior does comply  to the standard.

in the standard you quoted:

> The `inline` specifier shall be applied only to the declaration of a variable or function[.](http://eel.is/c++draft/dcl.inline#1.sentence-1)
> ...
> If an inline function or variable that is attached to a named module is declared in a definition domain, it shall be defined in that domain[.](http://eel.is/c++draft/dcl.inline#7.sentence-1)

and per the related definition in standard:

> A [definition domain](https://eel.is/c++draft/basic.def.odr#def:definition_domain) is a [private-module-fragment](https://eel.is/c++draft/module.private.frag#nt:private-module-fragment) or the portion of a translation unit excluding its [private-module-fragment](https://eel.is/c++draft/module.private.frag#nt:private-module-fragment) (if any)[.](https://eel.is/c++draft/basic.def.odr#12.sentence-1)
> A definition of an inline function or variable shall be reachable from the end of every definition domain in which it is odr-used outside of a discarded statement[.](https://eel.is/c++draft/basic.def.odr#12.sentence-2)
> 
see https://eel.is/c++draft/basic.def.odr#12

when it comes to my reproducer,
```c++
module;

export module foo;

template<typename T>
inline void func(T) noexcept;

template<>
inline void func<unsigned>(unsigned) noexcept
{}
```
it does not have a private module fragment, but it is "a portion of a translation unit excluding its private module fragment". so per the definition in $basic.def.odr.12, it is a definition domain. where
```c+
template<typename T>
inline void func(T) noexcept;
```
should be considered as a valid declaration. as its definition is reachable in this definition domain. actually it is located couple lines below, right after the declaration.

**Comment by ChuanqiXu9** [comment]
But

```
template<>
inline void func<unsigned>(unsigned) noexcept
{}
```

is not a definition but a specialization for the above declaration, right? For example, this will be accepted: https://godbolt.org/z/TjxTWzWGv

**Comment by ChuanqiXu9** [comment]
If you have special use case, I'll suggest something like: https://godbolt.org/z/xznvozrej

**Comment by tchaikov** [comment]
@ChuangqiXu9 thank you for your prompt reply!

i see. i mistook the specialization for the definition of `func()`. in other words, in my reproducer, `func()` itself is never defined! no matter how it is specialized for what type constraints.

so, just to be clear, if we really want to "declare" a template function with `inline` specifier, we would have to define it with, even an malformed body.

thank you for you suggestion. i think we don't have a strong requirement for the `inline` specifier, just wanted to get to the bottom of the problem, and to understand if this is really an issue.
