### ISSUE TITLE
[clang-tidy] add a check to report invalid float to int cast

### ISSUE THREAD

**Issue by HerrCai0907** [llvm/llvm-project#62052]
Is it meaningful to add a new check or integrate into some other check, to check casting a float value to integer without checking bound or already out of limitation 

```c++
auto Abc = static_cast<unsigned>(-10.0);
```
This code causes undefined behavior. (in AArch64  is 0 and in x86 is -10)

**Comment by royjacobson** [comment]
If the value is known in advance, you can declare your variable as `constexpr` to catch this behavior.

At runtime, you could use the ubsan sanitizer: `-fsanitize=undefined`.
