### ISSUE TITLE
[libc++][format] Should `operator<<(thread::id)` care about fmtflags in C++23?

### ISSUE THREAD

**Issue by JMazurkiewicz** [llvm/llvm-project#62073]
Repro:

```c++
#include <cassert>
#include <format>
#include <sstream>
#include <thread>

using namespace std;

int main() {
  auto id = this_thread::get_id();
  const auto s1 = format("{}", id);
  ostringstream stream;
  stream << id;
  const auto s2 = stream.str(); // This is "text representation".
  assert(s2 == s1);             // Ok.

  stream.str("");
  stream << hex << id;
  const auto s3 =
      stream.str(); // Should this be the same "text representation"?
  assert(s3 == s1); // Currently, it is not.
}
```

Build:

```console
PS D:\libcxx-playground> clang -std=c++2b -fexperimental-library -Iinclude\c++\v1 -llib\c++ "-llib\windows\clang_rt.builtins-x86_64" .\test.cpp
PS D:\libcxx-playground> .\a.exe
Assertion failed: s3 == s1, file .\test.cpp, line 20
```

The question is: should `operator<<(thread::id)` even care about fmtflags? It seems to me that since P2693R1 (partially implemented in https://github.com/llvm/llvm-project/commit/88622aabf10764cc32d546f448076d25b13e94cd) the text representation is not longer "unspecified" and should always be the same, no matter what the fmtflags/locale/precision are.

CC: @mordante

**Comment by mordante** [comment]
This is an interesting question since in this example the output of `operator<<` is not identical either. I haven't checked, but I'm quite sure that was a requirement before this change.  I will look into this.

**Comment by mordante** [comment]
Based on the wording prior to P2693R1 this requirement was true for `operator<<` too. I had a quick look at all major implementations and I expect them all the have the same issue. I will test further at another time.

**Comment by mordante** [comment]
https://reviews.llvm.org/D153336

**Comment by mordante** [comment]
This has been merged https://github.com/llvm/llvm-project/commit/1c1edd1b5d00daae2efdfbc5754a9fae77597dd4
