### ISSUE TITLE
CFG + ehcont + dyn TLS = crashing output

### ISSUE THREAD

**Issue by namazso** [llvm/llvm-project#62075]
Repro:

```cpp
#include <cstdio>

class Z {
  void* volatile p;

public:
  Z() {
    p = nullptr;
  }
};
thread_local Z g_z;

int main() {
	puts("Hello world!");
	return 0;
}
```

```cmd
> clang-cl.exe -m64 /guard:cf /guard:ehcont -- test.cpp
> .\test.exe
> echo %errorlevel%
-1073740791
```

The function `__tls_init` is not in the appropriate table, as this fails:

![image](https://user-images.githubusercontent.com/8676443/231281616-9d8f4e46-d540-4168-946f-3912bec46088.png)

**Comment by jarodrig** [comment]
Looks fixed by [https://reviews.llvm.org/rG2f0a1699eab7c00a64312e7f87e0d85a2e9b9e6e](url)

**Comment by namazso** [comment]
Correct, this was fixed by that change, as the root cause was building without CF guard (as the later `/guard` overrode it), but linking with it enabled.
