### ISSUE TITLE
[libc++][format][chrono] Subsecond part of `duration` is not correctly formatted

### ISSUE THREAD

**Issue by frederick-vs-ja** [llvm/llvm-project#62082]
Example
```C++
#include <chrono>
#include <cstdint>
#include <format>
#include <iostream>

int main()
{
    std::cout << std::format("{0:%M:%S} {0}\n", std::chrono::duration<int, std::ratio<101, 103>>{40});
    std::cout << std::format("{0:%M:%S} {0}\n", std::chrono::duration<int, std::ratio<1, 1024>>{1511});
}
```

Current output  ([Godbolt link](https://godbolt.org/z/PcPd8j1PW)):
```
00:39.000023 40[101/103]s
00:01.0000000487 1511[1/1024]s
```

Expected output:
```
00:39.223300 40[101/103]s
00:01.4755859375 1511[1/1024]s
```

It seems that we should convert (via `duration_cast`) `__fraction` to `precision` before writing its `count()`.
https://github.com/llvm/llvm-project/blob/9d4df97ff0ef459316cdb55f17eaea9fe9b1c1d5/libcxx/include/__chrono/formatter.h#L87

https://github.com/llvm/llvm-project/blob/9d4df97ff0ef459316cdb55f17eaea9fe9b1c1d5/libcxx/include/__chrono/formatter.h#L101-L109

**Comment by mordante** [comment]
https://reviews.llvm.org/D149868 should fix this.

**Comment by mordante** [comment]
The author of the previous fix seems to be MIA, instead I created https://reviews.llvm.org/D154851

**Comment by mordante** [comment]
The patch has landed.
