### ISSUE TITLE
Clang ignores optnone when translating math functions

### ISSUE THREAD

**Issue by andykaylor** [llvm/llvm-project#62098]
When I compile a C file with fast math enabled (using either `-ffast-math` or `-ffp-model=fast`, for example) Clang does not respect attributes (`optnone`) or pragmas (`float_control(precise, on)`) that should locally prevent the substitution of intrinsics for math library calls which set `errno`. In the case of `sqrt`, this also leads to the generation of `sqrt` instructions (such as `sqrtsd` on x86-based targets) rather than calls to the `sqrt` function.

Here is an example: https://godbolt.org/z/P35sEbnr5

**Comment by topperc** [comment]
-ffast-math implies -fno-math-errno. That might be the only option that matters here.

**Comment by andykaylor** [comment]
I see that adding __attribute__((no_builtin)) does prevent the call to the intrinsic. However, I would expect __attribute__((optnone)) to override the -ffast-math command-line option. At the very least, #pragma float_control(precise, on) should, and it does not.

**Comment by andykaylor** [comment]
Curiously, with #pragma float_control(precise, on) clang does not set fast-math flags on normal fp operations, but it does set it on the function call if I also add __attribute__((no_builtin)).

https://godbolt.org/z/bs7aY83Yq

**Comment by zahiraam** [comment]
> I see that adding `__attribute__((no_builtin))` does prevent the call to the intrinsic. However, I would expect `__attribute__((optnone))` to override the -ffast-math command-line option. At the very least, `#pragma float_control(precise, on)` should, and it does not.

It looks like __attribute__((optnone)) doesn't do that: https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaDeclAttr.cpp#L4912
But the pragma seems to override fast-math: https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaAttr.cpp#L564

**Comment by AaronBallman** [comment]
> When I compile a C file with fast math enabled (using either `-ffast-math` or `-ffp-model=fast`, for example) Clang does not respect attributes (`optnone`) or pragmas (`float_control(precise, on)`) that should locally prevent the substitution of intrinsics for math library calls which set `errno`. In the case of `sqrt`, this also leads to the generation of `sqrt` instructions (such as `sqrtsd` on x86-based targets) rather than calls to the `sqrt` function.

I'm not certain I understand the relationship between setting a precise float control mode and math errno. If the user says they want precise math, they're talking about the precision of the operations; whether errno is set or not is not relevant to the precision of the results, right? So I'd imagine setting a precise float control mode would disable some parts of fast math related to precision, but I'd like to understand better why it should also change math errno behavior at the same time.

**Comment by zahiraam** [comment]
Fixed in https://reviews.llvm.org/D151834
