### ISSUE TITLE
[clang-tidy] Crash in clang::ASTContext::getTypeInfo after initializing an array with a value of unknown type

### ISSUE THREAD

**Issue by alexhenrie** [llvm/llvm-project#62097]
Clang-Tidy crashes while processing [nsembed.c](https://gitlab.winehq.org/wine/wine/-/blob/master/dlls/mshtml/nsembed.c) from Wine. This is the smallest example I could make that reproduces the crash:

```c
undefined1 scalar;

int array1[] = {scalar};

struct {
    int array2[sizeof(array1)];
};
```

Clang-Tidy only crashes on this code about 50% of the time, so if it works for you, try it several times.

```console
$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 15.0.7
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: skylake
```

[backtrace.txt](https://github.com/llvm/llvm-project/files/11213660/backtrace.txt)

**Comment by alexhenrie** [comment]
https://godbolt.org/ doesn't seem to have a problem.

**Comment by carlosgalvezp** [comment]
Can reproduce the minimal example problem on 15.0.7, but no longer on 16.0.1. Closing as fixed.
