### ISSUE TITLE
CXXUnresolvedConstructExpr has invalid source locations and causes Clang coverage crash when visiting it.

### ISSUE THREAD

**Issue by ZequanWu** [llvm/llvm-project#62105]
Repro example:
```cpp
namespace std { template <typename> class initializer_list {}; }

template <typename> struct T {
  T(std::initializer_list<int>, int = int());
  bool b;
};

template <typename> struct S1 {
  static void foo() {
    class C;
    0 ? T<C>{} : T<C>{};
    0 ? 1 : 2;
  }
};

void bar() {
  S1<int>::foo();
}
```
Command:
```shell
clang++ -fprofile-instr-generate -fcoverage-mapping -std=c++20 -c -o a.o a.cpp
```

It's due to the visited expression not having valid source locations, which is dropped intentionally here: https://github.com/llvm/llvm-project/blob/llvmorg-16.0.1/clang/lib/Sema/SemaExprCXX.cpp#L1536

https://reviews.llvm.org/D147073 added a workaround for that so Clang only crash on assertion build. The real is to make sure the expression has valid source locations.

**Comment by zmodem** [comment]
Shouldn't we keep this open? Clang still asserts on this code, right?

**Comment by AaronBallman** [comment]
No, this was fixed in b0e61de7075942ef5ac8af9ca1ec918317f62152 -- we stopped dropping the source locations with: https://github.com/llvm/llvm-project/commit/b0e61de7075942ef5ac8af9ca1ec918317f62152#diff-1420e9cbc74252d1c2e98a97f80d3741bb4a44e8469d326ba3aa337260ee9800L1525

**Comment by zmodem** [comment]
Nice! Sorry for the noise.

**Comment by AaronBallman** [comment]
No worries, thank you for double-checking it was valid to close!
