### ISSUE TITLE
[C++20] [Modules] Compilation failure std module without magic comment

### ISSUE THREAD

**Issue by mordante** [llvm/llvm-project#62112]
@AaronBallman @ChuanqiXu9 I was testing with #61446. Using `-Wno-reserved-module-identifier` fixes the reserved module name diagnostic. But it fails to build a module without the magic comment `# 1 __FILE__ 1 3`

Tested with the nightly Clang 17 (20230412031217+76e407084330-1~exp1~20230412151227.862)

```
# 1 __FILE__ 1 3
// -*- C++ -*-

module;
#include <latch>

export module std:latch;
export namespace std {
  using std::latch;
} // namespace std
```

This compiles using the following command
`clang++-17 -std=c++2b -stdlib=libc++ --precompile -Wno-reserved-module-identifier -o /tmp/latch.o latch.cppm`

After removing the first line compilation fails 
```
latch.cppm:5:1: error: export declaration can only be used within a module purview
export namespace std {
^
latch.cppm:1:1: error: missing 'module' declaration at end of global module fragment introduced here
module;
```

Renaming the module to `latch` fixes compilation.

**Comment by ChuanqiXu9** [comment]
Oh, sorry for the oversight. I committed directly since this change is trivial.

**Comment by mordante** [comment]
Thanks for the quick fix I tested the change and I can now build libc++ modules without the `# 1 __FILE__ 1 3` line :-)
