### ISSUE TITLE
[MLIR] `--view-op-graph` doesn't handle graph regions (backedges)

### ISSUE THREAD

**Issue by mortbopet** [llvm/llvm-project#62128]
As a trivial example, consider the following:

```mlir
module {
  %add = arith.addi %c0, %c1 : index
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
}
```

renders the following .dot graph: `mlir-opt --view-op-graph`:
```dot
digraph G {
  compound = true;
  subgraph cluster_1 {
    v2 [label = " ", shape = plain];
    label = "builtin.module : ())\n";
    subgraph cluster_3 {
      v4 [label = " ", shape = plain];
      label = "";
      v5 [label = "arith.addi : (index))\n", shape = ellipse];
      v6 [label = "arith.constant : (index))\n\nvalue: 0 : index", shape = ellipse];
      v7 [label = "arith.constant : (index))\n\nvalue: 1 : index", shape = ellipse];
    }
  }
  v0 -> v5 [label = "0", style = solid];
  v0 -> v5 [label = "1", style = solid];
}
```

![image](https://user-images.githubusercontent.com/16338943/232007115-bdf6b9a2-a656-4981-8135-ab796483eb7b.png)

I suspect the only required change to the `view-op-graph` pass will be to do a pre-pass on all ops in a region, assign node names to them, and _then_ iterate and emit the operations.

**Comment by VMois** [comment]
Hi. I want to try and work on this issue. I was able to compile MLIR and reproduce your graph. It is my first time working with MLIR. As I understood, you want to link both constants to `addi` operation for this particular example. And in a general sense, create all op nodes before processing them so even backlinks can be connected back.

I managed to do this but I would like someone to take a look at whatever solution is correct/makes sense. Diff is below:

```diff
diff --git a/mlir/lib/Transforms/ViewOpGraph.cpp b/mlir/lib/Transforms/ViewOpGraph.cpp
index 4598b56a901d..4a37436c2a81 100644
--- a/mlir/lib/Transforms/ViewOpGraph.cpp
+++ b/mlir/lib/Transforms/ViewOpGraph.cpp
@@ -253,6 +253,12 @@ private:
     emitClusterStmt([&]() {
       for (BlockArgument &blockArg : block.getArguments())
         valueToNode[blockArg] = emitNodeStmt(getLabel(blockArg));
+
+      for (Operation &op : block) {
+        Node node = emitNodeStmt(getLabel(&op));
+        for (Value result : op.getResults())
+          valueToNode[result] = node;
+      }

       // Emit a node for each operation.
       std::optional<Node> prevNode;
@@ -279,7 +285,7 @@ private:
           },
           getLabel(op));
     } else {
-      node = emitNodeStmt(getLabel(op));
+      node = valueToNode[op->getResult(0)];
     }

     // Insert data flow edges originating from each operand.
@@ -291,9 +297,6 @@ private:
                      kLineStyleDataFlow);
     }

-    for (Value result : op->getResults())
-      valueToNode[result] = node;
-
     return node;
   }
```

```
digraph G {
  compound = true;
  subgraph cluster_1 {
    v2 [label = " ", shape = plain];
    label = "builtin.module : ())\n";
    subgraph cluster_3 {
      v4 [label = " ", shape = plain];
      label = "";
      v5 [label = "arith.addi : (index))\n", shape = ellipse];
      v6 [label = "arith.constant : (index))\n\nvalue: 0 : index", shape = ellipse];
      v7 [label = "arith.constant : (index))\n\nvalue: 1 : index", shape = ellipse];
    }
  }
  v6 -> v5 [label = "0", style = solid];
  v7 -> v5 [label = "1", style = solid];
}
```

One comment:
- I am not sure if `node = valueToNode[op->getResult(0)];` is reliable. What If the operation doesn't have a result? Is it possible?

I would appreciate comments and guidance. Thank you.

**Comment by manasvi-26** [comment]
Hi @VMois are you still actively working on this? If not, I'd like to take this up.

**Comment by VMois** [comment]
> Hi @VMois are you still actively working on this? If not, I'd like to take this up.

Hi. I am not. I got stuck with a problem as far as I remember. Feel free to take the issue over. I would be happy to see your solution and learn from it.

**Comment by manasvi-26** [comment]
Sure, sharing your branch would be very helpful, if it's not much of a problem. Thanks a lot!
@mortbopet can you please assign me to this?

**Comment by VMois** [comment]
@manasvi-26 here is the PR with the changes I had - https://github.com/VMois/llvm-project/pull/1.

**Comment by agentcooper** [comment]
There seems to be a simple solution using topological sorting for each block: https://github.com/llvm/llvm-project/issues/62128.
