### ISSUE TITLE
[LV] assume_safety option for pragma loop vectorize

### ISSUE THREAD

**Issue by erickq** [llvm/llvm-project#62126]
I've had some problems with the assume_safety option for pragma loop vectorize recently, and I think the llvm implementation is inconsistent with the meaning of the option.

This option is `#pragma clang loop vectorize(assume_safety)`，According to https://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20150608/130619.html，Specifying #pragma clang loop vectorize(assume_safety) on a loop adds the mem.parallel_loop_access metadata to each load/store operation in the loop. This metadata tells loop access analysis (LAA) to skip memory dependency checking.

I read the llvm code, the analyzeLoop function of LoopAccessAnalysis.cpp, and if IsAnnotatedParallel is true, many checks are skipped, such as runtime pointer bounds checks.
![image](https://user-images.githubusercontent.com/12108571/231974298-ecd7ae85-8c70-4397-ab84-8c02e1d2e440.png)
![image](https://user-images.githubusercontent.com/12108571/231974349-fa51a36c-580f-4ba5-9079-e0321e36414d.png)

Is this part of the code implemented incorrectly?

**Comment by fhahn** [comment]
Both of the below 

> This metadata tells loop access analysis (LAA) to skip memory dependency checking.

Yep

> I read the llvm code, the analyzeLoop function of LoopAccessAnalysis.cpp, and if IsAnnotatedParallel is true, many checks are skipped, such as runtime pointer bounds checks.

Yep, but that is a consequence of the metadata telling the optimizer that the accesses in the loop are safe for parallelization, so there's no need for further analysis.

Granted, it looks like neither `assume_safety` nor `mem.parallel_loop_access ` look documented, so it is difficult to definitely say how exactly they should behave, so the current behavior in the code is the best we got I think.

**Comment by erickq** [comment]
Thank you for your reply. I would like to ask again, if #pragma clang loop vectorize(assume_safety) exists in the source code, then it means skip memory dependency checking, does it mean out-of-bounds access also need not be considered?

**Comment by erickq** [comment]
@fhahn thanks

**Comment by fhahn** [comment]
> Thank you for your reply. I would like to ask again, if #pragma clang loop vectorize(assume_safety) exists in the source code, then it means skip memory dependency checking, does it mean out-of-bounds access also need not be considered?

LoopAccessAnalysis doesn't check for out-of-bounds accesses; it needs to compute the bounds of accesses in the loop (lowest and highest address) so it can emit runtime checks to see if accesses alias. But as the metadata guarantees that there are no dependencies, that's not needed.

**Comment by erickq** [comment]
Thank you@fhahn. So when the source code exists #pragma clang loop vectorize(assume_safety), the compiler is required to ensure that vectorization does not occur out-of-bounds access. Is my understanding right?

**Comment by fhahn** [comment]
> Thank you @fhahn . So when the source code exists #pragma clang loop vectorize(assume_safety), the compiler is required to ensure that vectorization does not occur out-of-bounds access. Is my understanding right?

I might be misunderstanding what you mean exactly here, but the vectorizer never checks if there's an out-of-bound access (regardless of ` vectorize(assume_safety)`); the vectorized code would only have an out-of-bound access if the source code already had one. As I said earlier, LoopAccessAnalysis doesn't check for out-of-bound accesses; it only needs to compute pointer bounds if it emits a runtime check.
