### ISSUE TITLE
[docs] libomp design document not found

### ISSUE THREAD

**Issue by colluca** [llvm/llvm-project#62143]
Documentation refers to an early design document at these lines:
https://github.com/llvm/llvm-project/blame/main/openmp/docs/design/Runtimes.rst#L19-L21

However, when navigating to the linked URL a 404 not found error is encountered.

**Comment by colluca** [comment]
That would be useful indeed, also as a hint on where to find the documentation sources and the README describing how to build them.

**Comment by jhuber6** [comment]
https://openmp.llvm.org/design/Runtimes.html points to the file on github now.
