### ISSUE TITLE
Compiling lldb-16.0.1 fails 

### ISSUE THREAD

**Issue by dilyanpalauzov** [llvm/llvm-project#62146]
Compiling LLDB in LLVM 16.0.1 fails with this error:

```console
$ ninja -j1 -v
[1/7] : && /usr/bin/c++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-stringop-truncation -O3 -DNDEBUG -Wl,-rpath-link,/src/llvm-project-16.0.1.src/build/./lib  -Wl,--gc-sections tools/lldb/tools/lldb-instr/CMakeFiles/lldb-instr.dir/Instrument.cpp.o -o bin/lldb-instr  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libclangCodeGen.so.16  lib/libclangTooling.so.16  lib/libclangFrontend.so.16  lib/libclangSerialization.so.16  lib/libclangAST.so.16  lib/libclangRewrite.so.16  lib/libclangLex.so.16  lib/libclangBasic.so.16  -Wl,-rpath-link,/src/llvm-project-16.0.1.src/build/lib && :
FAILED: bin/lldb-instr
: && /usr/bin/c++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-stringop-truncation -O3 -DNDEBUG -Wl,-rpath-link,/src/llvm-project-16.0.1.src/build/./lib  -Wl,--gc-sections tools/lldb/tools/lldb-instr/CMakeFiles/lldb-instr.dir/Instrument.cpp.o -o bin/lldb-instr  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libclangCodeGen.so.16  lib/libclangTooling.so.16  lib/libclangFrontend.so.16  lib/libclangSerialization.so.16  lib/libclangAST.so.16  lib/libclangRewrite.so.16  lib/libclangLex.so.16  lib/libclangBasic.so.16  -Wl,-rpath-link,/src/llvm-project-16.0.1.src/build/lib && :                                                              /usr/bin/ld: tools/lldb/tools/lldb-instr/CMakeFiles/lldb-instr.dir/Instrument.cpp.o: undefined reference to symbol '_ZN4llvm11raw_ostream5writeEPKcm'                /usr/bin/ld: /src/llvm-project-16.0.1.src/build/./lib/libLLVMSupport.so.16: error adding symbols: DSO missing from command line                                      collect2: error: ld returned 1 exit status                                                                                                                           ninja: build stopped: subcommand failed.
$
```

All other components (subprojects) I have selected, do compile.  Likewise in 16.0.0.  In 15.0.7 there was, I think, no such problem.

**Comment by yuffon** [comment]
> Compiling LLDB in LLVM 16.0.1 fails with this error:
> 
> ```
> $ ninja -j1 -v
> [1/7] : && /usr/bin/c++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-stringop-truncation -O3 -DNDEBUG -Wl,-rpath-link,/src/llvm-project-16.0.1.src/build/./lib  -Wl,--gc-sections tools/lldb/tools/lldb-instr/CMakeFiles/lldb-instr.dir/Instrument.cpp.o -o bin/lldb-instr  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libclangCodeGen.so.16  lib/libclangTooling.so.16  lib/libclangFrontend.so.16  lib/libclangSerialization.so.16  lib/libclangAST.so.16  lib/libclangRewrite.so.16  lib/libclangLex.so.16  lib/libclangBasic.so.16  -Wl,-rpath-link,/src/llvm-project-16.0.1.src/build/lib && :
> FAILED: bin/lldb-instr
> : && /usr/bin/c++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-stringop-truncation -O3 -DNDEBUG -Wl,-rpath-link,/src/llvm-project-16.0.1.src/build/./lib  -Wl,--gc-sections tools/lldb/tools/lldb-instr/CMakeFiles/lldb-instr.dir/Instrument.cpp.o -o bin/lldb-instr  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libclangCodeGen.so.16  lib/libclangTooling.so.16  lib/libclangFrontend.so.16  lib/libclangSerialization.so.16  lib/libclangAST.so.16  lib/libclangRewrite.so.16  lib/libclangLex.so.16  lib/libclangBasic.so.16  -Wl,-rpath-link,/src/llvm-project-16.0.1.src/build/lib && :                                                              /usr/bin/ld: tools/lldb/tools/lldb-instr/CMakeFiles/lldb-instr.dir/Instrument.cpp.o: undefined reference to symbol '_ZN4llvm11raw_ostream5writeEPKcm'                /usr/bin/ld: /src/llvm-project-16.0.1.src/build/./lib/libLLVMSupport.so.16: error adding symbols: DSO missing from command line                                      collect2: error: ld returned 1 exit status                                                                                                                           ninja: build stopped: subcommand failed.
> $
> ```
> 
> All other components (subprojects) I have selected, do compile. Likewise in 16.0.0. In 15.0.7 there was, I think, no such problem.

I met the same problem. How do you resolve this?

**Comment by dilyanpalauzov** [comment]
With 18.1.1 this seems to work.

The workaround was to remove `lldb` from `LLVM_ENABLE_PROJECTS`.
