### ISSUE TITLE
[AArch64] unimplemented reg-to-reg copy: Q2 = COPY Z0

### ISSUE THREAD

**Issue by MattPD** [llvm/llvm-project#62151]
It appears new--likely introduced between April 4 and April 5 (see below for the information on the commits used to reproduce and Compiler Explorer links).

Source code:
```c
typedef struct {
  int j, k;
} box_type;

int sink;
box_type ba, bb, bc;

void build_interpolation() {
  int fineBox_j = bc.j, fineBox_k = bc.k;
  int coarseBox_j = fineBox_j * bb.j / ba.j;
  int coarseBox_k = fineBox_k * bb.k / ba.k;
  int coarseBoxID = coarseBox_j + coarseBox_k * bb.j;
  sink = coarseBoxID;
}
```

ICE:
```
# *** IR Dump Before Post-RA pseudo instruction expansion pass (postrapseudos) ***:
# Machine code for function build_interpolation: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues

bb.0.entry:
  renamable $x8 = ADRP target-flags(aarch64-page) @bc
  renamable $d0 = LDRDui killed renamable $x8, target-flags(aarch64-pageoff, aarch64-nc) @bc :: (dereferenceable load (s64) from @bc, !tbaa !5)
  renamable $x8 = ADRP target-flags(aarch64-page) @bb
  renamable $d1 = LDRDui killed renamable $x8, target-flags(aarch64-pageoff, aarch64-nc) @bb :: (dereferenceable load (s64) from @bb, !tbaa !5)
  renamable $d0 = nsw MULv2i32 renamable $d1, killed renamable $d0, implicit-def $z0
  renamable $x8 = ADRP target-flags(aarch64-page) @ba
  renamable $d2 = LDRDui killed renamable $x8, target-flags(aarch64-pageoff, aarch64-nc) @ba, implicit-def $z2 :: (dereferenceable load (s64) from @ba, !tbaa !5)
  renamable $p0 = PTRUE_S 2
  renamable $z0 = SDIV_ZPZZ_UNDEF_S killed renamable $p0, killed renamable $z0, killed renamable $z2
  renamable $q2 = COPY renamable $z0
  renamable $d0 = MLAv2i32_indexed renamable $d0(tied-def 0), killed renamable $d1, killed renamable $q2, 1, implicit killed $z0, implicit-def $z0
  renamable $x8 = ADRP target-flags(aarch64-page) @sink
  STRSui renamable $s0, killed renamable $x8, target-flags(aarch64-pageoff, aarch64-nc) @sink, implicit killed $z0 :: (store (s32) into @sink, !tbaa !5)
  RET_ReallyLR

# End machine code for function build_interpolation.

Machine Function
********** EXPANDING POST-RA PSEUDO INSTRS **********
********** Function: build_interpolation
real copy:   renamable $q2 = COPY renamable $z0
Q2 = COPY Z0
unimplemented reg-to-reg copy
UNREACHABLE executed at /root/llvm-project/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp:3811!
```

I've been able to reproduce on Compiler Explorer. Note that at the moment of writing Compiler Explorer's x86-64 trunk build is _newer_ than AArch64 trunk build; we can compile using `--target=aarch64--` (which then allows to use AArch64 targets via `-mcpu=a64fx` as well).

This is interesting, as it also seems to point that the change happened between these two commits, i.e., between April 4 and April 5:

ICE already present: https://aarch64.godbolt.org/z/q7hr1acnT
Clang version 17.0.0 (https://github.com/llvm/llvm-project.git 39c0602414d4b0efb1e4749b0e9fdd7974026bf7)
https://github.com/llvm/llvm-project/commit/39c0602414d4b0efb1e4749b0e9fdd7974026bf7
2023-04-05

Still no ICE: https://aarch64.godbolt.org/z/3PhPbjqPr
Clang version 17.0.0 (https://github.com/llvm/llvm-project.git 5b461d5ec172d21029da492064704fe3da6f8bab)
https://github.com/llvm/llvm-project/commit/5b461d5ec172d21029da492064704fe3da6f8bab
2023-04-04

**Comment by davemgreen** [comment]
It should not be generating a copy from Z to V. It is probably some function like AArch64DAGToDAGISel::tryMLAV64LaneV128 using an incorrect type from an EXTRACT_SUBVECTOR.

**Comment by MattPD** [comment]
Thank you, subscribed to the patch in question! Out of curiosity, may I ask how have you located the issue to be in  tryMLAV64LaneV128 (for my own edification?) :-)
