### ISSUE TITLE
[C++20][modules] Failure to specialize templated variables

### ISSUE THREAD

**Issue by mordante** [llvm/llvm-project#62158]
Tested with `clang version 17.0.0 (++20230414071729+999a8b8ce927-1~exp1~20230414071839.627)`

I originally ran into this issue while working on the `std` module in libc++. There we have tests that specialize `std::enable_borrowed_range` for user defined types. This is a reduced example.

I first suspected this issue had something to do with the `inline namespace __1`, but that seems not to be the case. It would be nice when the fix would be tested with an `inline namespace` too.

Using the following 3 files
`header.h`
```cpp
namespace lib /*::inline __1*/ {
template <class>
inline constexpr bool test = false;
} // namespace lib
```
`lib.cppm`
```cpp
module;
#include "header.h"
export module lib;

export namespace lib {
using lib::test;
} // namespace lib
```
`main.cpp`
```cpp
#ifdef HEADER
#include "header.h"
#else
import lib;
#endif

struct foo {};

template <>
inline constexpr bool lib::test<foo> = true;

static_assert(lib::test<foo>);
```
Building with the following command succeeds
```shell
clang++-17 -std=c++20 -DHEADER -fsyntax-only main.cpp
```

Building with the following commands
```shell
clang++-17 -std=c++20 --precompile lib.cppm
clang++-17 -std=c++20 -fsyntax-only -fprebuilt-module-path=. main.cpp
```
fails
```console
main.cpp:11:28: error: no member named 'test' in namespace 'lib'
inline constexpr bool lib::test<foo> = true;
                      ~~~~~^
1 error generated.

```
A work-around it to specialize the variable inside the namespace like
```cpp
namespace lib {
template <>
inline constexpr bool test<foo> = true;
}
```

**Comment by ChuanqiXu9** [comment]
This looks like not a modules problem. I registered https://github.com/llvm/llvm-project/issues/62174 and let's track the problem there.

**Comment by mordante** [comment]
There might be more issues in this area in Clang, but this example works headers and clang-modules and fails with C++20 modules. 
The libc++ code that showed this issue has been available for multiple releases. So at least part of the issue is C++20 modules specific.

**Comment by ChuanqiXu9** [comment]
> 

Yeah, from the user's perspective, this is indeed related to C++20 modules. But from the compiler's (internal) view (see the above link for details), this is not a modules problem indeed.
