### ISSUE TITLE
[Clang] Allows multiple initializers for a union when using designated initializers in C++

### ISSUE THREAD

**Issue by shafik** [llvm/llvm-project#62156]
Given the following, see godbolt: https://godbolt.org/z/TjxE3PhfK

```cpp
union U {
   int x;
   float y;
};

void f() {
   U u{.x=2,.y=1};
}
```

We produce the following diagnostic:

```console
<source>:7:13: warning: initializer overrides prior initialization of this subobject [-Winitializer-overrides]
   U u{.x=2,.y=1};
            ^~~~
<source>:7:11: note: previous initialization is here
   U u{.x=2,.y=1};
          ^
1 warning generated.
Compiler returned: 0
```

This should be ill-formed and should be a hard error.

It looks like we allow this as an extension if we look at `SemaInit.cpp` and see `diagnoseInitOverride(...)` we see the following:

```cpp
  // Overriding an initializer via a designator is valid with C99 designated
    // initializers, but ill-formed with C++20 designated initializers.
    unsigned DiagID = SemaRef.getLangOpts().CPlusPlus
                          ? diag::ext_initializer_overrides
                          : diag::warn_initializer_overrides;

```

I wonder if for unions in C++ we should make this a hard error.

I believe [dcl.init.aggr p20](https://eel.is/c++draft/dcl.init.aggr#20) is the correct reference:

> When a union is initialized with an initializer list, there shall not be more than one explicitly initialized element[.](https://eel.is/c++draft/dcl.init.aggr#20.sentence-1)

**Comment by shafik** [comment]
CC @zygoloid @AaronBallman

**Comment by zygoloid** [comment]
Clang has always accepted C designated initializer syntax as an extension in C++. When implementing the C++20 designated initialization support, my intent was that all code we'd previously accepted as an extension would still be accepted as an extension -- changing that would in some sense be removing an extension, which seems like something we should have a high bar and a strong reason for doing. But I certainly didn't do a case analysis to look for places where we might be able to meet such a bar. There are four conforming options that we'd normally pick between for each case:

1) `Extension`: Accept it silently by default, warn under `-pedantic`, reject under `-pedantic-errors`.
2) `ExtWarn`: Accept it with a warning by default, reject under `-pedantic-errors`.
3) `ExtWarn, DefaultError`: Reject it by default, allow it with `-Wno-something`.
4) `Error`: Just reject, remove the extension entirely.

Right now, I think these warnings are generally using (2). I think going to (3) would be fine for cases that are hazardous or strongly suggestive of a bug and we don't expect to show up in the wild much, and case (4) seems reasonable for situations that are actively broken / unimplemented / unimplementable, or where the extension is not conforming for some reason.

This case, where one union member is overridden by another one, seems like changing to (3) might be reasonable. And when the overridden field has a non-trivial destructor, I think switching to (4) would be reasonable:

```
union U {
   std::string x;
   float y;
};

void f() {
  // Currently accepted, but leaks a string -- pretty clearly broken.
  new U{.x="some long string requiring heap allocation",.y=1};
}
```

In the more benign cases, like nested designators or reordering of designators (analogous to constructor mem-initializer lists), I think (2) is probably the best tradeoff, in terms of not breaking existing code and allowing C code to be more easily ported to C++.

**Comment by shafik** [comment]
PR: https://reviews.llvm.org/D149694
