### ISSUE TITLE
[clang-tidy] performance-noexcept-move-constructor should also flag missing `noexcept` on swap functions and default constructors

### ISSUE THREAD

**Issue by sweemer** [llvm/llvm-project#62154]
According to C++ Core Guideline [F.6](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-noexcept):

> Destructors, swap functions, move operations, and default constructors should never throw. See also [C.44](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-default00).
> 
> Enforcement
> - Flag functions that are not noexcept, yet cannot throw.
> - Flag throwing swap, move, destructors, and default constructors.

However it looks like the performance-noexcept-move-constructor check only flags missing `noexcept` on move constructors and move assignment operators. It would be good if this check could also flag missing `noexcept` on swap functions and default constructors for consistency with the guideline.

**Comment by AMS21** [comment]
The default constructor and destructor case should be fairly easy to implement. Since we have the `ExceptionSpecAnalyzer` in clang-tidy.
Not sure if we wan't to flag every function called `swap`. Probably only the once who follow a pattern like this:
```cpp
void swap(A, A)
```
or
```cpp
struct A {
void swap(A);
};
```

We would also need to rename the check to something like `performance-noexcept-special-functions`. Since we're handling more than just move constructors.

Will give this a shot once I find time this week.

**Comment by sweemer** [comment]
Thanks! Just to clarify a couple points, which you probably know already:

- Destructors are generally `noexcept` except when explicitly declared as `noexcept(false)` or inheriting from a class with a destructor declared as `noexcept(false)`. Even though I didn't mention destructors in my original issue description, I agree it makes sense to flag throwing destructors as suggested by the core guidelines.
- Generally we would expect the arguments to swap functions to be passed by non-const lvalue reference. Otherwise I agree that those two swap function signatures are the right ones to check. (Perhaps flagging a swap function taking anything other than a non-const lvalue reference can one day be implemented as a separate check).

**Comment by carlosgalvezp** [comment]
Please also note that the check you mention is not in the cppcoreguidelines module, so users shouldn't expect that it conforms to the Cpp Core Guidelines (it was not created with those guidelines in mind).

That said I agree with extending the check functionality (possibly renaming it), as well as create an alias to it in the cppcoreguidelines module.

**Comment by sweemer** [comment]
Thanks!
