### ISSUE TITLE
[optimization] clang remove the infinite loop and leave unreachable

### ISSUE THREAD

**Issue by HerrCai0907** [llvm/llvm-project#62159]
If I want to compile this file with `clang main.cpp -O1` and run `a.out`, I will got `zsh: trace trap  ./a.out`
```c++
// main.cpp
int main() {
  while (true) {
  }
}
```
Is it reasonable?

The IR looks like
```
define noundef i32 @main() local_unnamed_addr #0 {
  unreachable
}
```

**Comment by shafik** [comment]
C++ assumes must progress of loop w/o side effects, so this is undefined behavior.

I discussed some of the less desirable outcomes of optimizations around this here on discourse: https://discourse.llvm.org/t/can-we-keep-must-progress-optimizations-around-infinite-loop-in-c-while-avoiding-some-surprising-behavior/69205?u=shafik
