### ISSUE TITLE
[GlobalOpt] Excessive compile time after memset related change

### ISSUE THREAD

**Issue by wolfy1961** [llvm/llvm-project#62191]
After f65c88c42fdd0e46d16fe31737e6627c56de77c3 we're seeing a lot of time spent in GlobalOpt with the following C++ code, when compiled with `clang -c -O3`:
```c
#if defined(LONGER)
#define ELTYPE B
#else
#define ELTYPE A
#endif

unsigned int getIndex();

struct A
{
  A() : m_p(nullptr) { }
  void* m_p;
};

struct B
{
  A m_a;
};

ELTYPE Entries[2097151] = {};

static ELTYPE GetElement( )
{
  return Entries[getIndex()];
}
```

With `-ftime-report` I'm seeing about 3 seconds spent in GlobalOpt on a linux box, and with `-DLONGER` the time in GlobalOpt seems to triple. A real-world example from one of our licensees sees compile time going from 4 seconds to over 200, all due to GlobalOpt.

**Comment by thesamesam** [comment]
Added for https://github.com/llvm/llvm-project/issues/55859. cc @nikic
