### ISSUE TITLE
Backport "[flang] Complex numbers in function arguments on Windows" to 16.x

### ISSUE THREAD

**Issue by mmuetzel** [llvm/llvm-project#62218]
See https://reviews.llvm.org/D147768

**Comment by mstorsjo** [comment]
You need to write the cherry-pick command in a separate comment post after the initial issue description. And you need to add the issue to the 16.x milestone.

**Comment by mmuetzel** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/774703ec08f62d702d40e1f97cd35ae5f732c544

**Comment by mmuetzel** [comment]
I don't have the privileges to add a milestone for this issue.

**Comment by mstorsjo** [comment]
Oh, apparently it does process commands in the initial post these days too - that didn’t use to be the case. Anyway, let’s retry:

/cherry-pick 774703ec08f62d702d40e1f97cd35ae5f732c544
