### ISSUE TITLE
`libclang-common-16-dev` incorrect symlinks

### ISSUE THREAD

**Issue by vient** [llvm/llvm-project#62217]
Hi, symlinks in `/usr/lib/clang/16` point to `16.0.2` directories:
```
/usr/lib/clang/16/include: broken symbolic link to ../../llvm-16/lib/clang/16.0.2/include
```
but there is no such folder. 

libclang-common-16-dev creates `/usr/lib/llvm-16/lib/clang/16/include` instead so I guess symlinks in `/usr/lib/clang/16` should be to `../../llvm-16/lib/clang/16/...`

**Comment by EugeneZelenko** [comment]
@vient: Could you please elaborate?

**Comment by vient** [comment]
I've looked at my old issues, and closed this one since clang-16 is no longer supported.
