### ISSUE TITLE
Forward-declared consteval function is rejected for use in a template parameter's default value

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#62224]
GCC test: `g++.dg/cpp2a/consteval-defarg3.C`
```c++
consteval int foober();

int g(int = foober());
struct A { int i = foober(); };
template <int i = foober()> struct B { };
struct C
{
  consteval C(int = foober()) { }
};
int h(C = C());

consteval int foober() { return 42; }

int main() {
  A a;
  B<> b;
  g();
  h();
}
```
Diagnostic:
```console
<source>:5:19: error: non-type template argument is not a constant expression
template <int i = foober()> struct B { };
                  ^~~~~~~~
<source>:5:19: note: undefined function 'foober' cannot be used in a constant expression
<source>:1:15: note: declared here
consteval int foober();
              ^
<source>:16:3: error: too few template arguments for class template 'B'
  B<> b;
  ^
<source>:5:36: note: template is declared here
template <int i = foober()> struct B { };
~~~~~~~~~~~~~~~~~~~~~~~~~~~        ^
```

Repro: https://godbolt.org/z/dPPE5TTnr

**Comment by shafik** [comment]
This is [DR2631](https://github.com/cplusplus/papers/issues/1312) I think this is on @cor3ntin list but maybe not.

**Comment by shafik** [comment]
On second thought, maybe it is not DR2631: https://godbolt.org/z/5fr9PEW99

```cpp
constexpr int g();
consteval int f() {
  return g();
}

int k(int x = f()) {  // error: constexpr evaluation of undefined function g
  return x;
}

constexpr int g() {
  return 42;
}

int main() {
  return k();
}
```

Although it looks related.

**Comment by cor3ntin** [comment]
@shafik at a glance, it looks like CWG2631 - I apparently forgot to implement the case where the default argument appartain to a template parameter. I'll try to put it on my infinite plate. 

Thanks for reporting that @cjdb

**Comment by Fznamznon** [comment]
@cor3ntin , if you don't have enough time for this bug ATM and don't mind, I can take a look.

**Comment by cor3ntin** [comment]
@Fznamznon If you have time sure, that sounds great! Thanks

**Comment by Fznamznon** [comment]
Clang evaluates and checks constant expression in default non-type template argument once it is met by parser, gcc seems to be doing that only if the default value is required. The illustrating example https://godbolt.org/z/vKofvWees
I was able to make clang do the same and the test doesn't error out anymore.
I've noticed there is some amount of work done in https://reviews.llvm.org/D136554 to make std::source_location::current have the value of location where default argument was required. So, Is my understanding correct that something like:
```
#include <source_location>

template <int sl = std::source_location::current().line()> struct SLS {
  static const int get = sl;
};

static_assert(SLS<>::get == __LINE__);
static_assert(SLS<>::get == __LINE__);
}
```
Compile fine? gcc doesn't compile this. https://godbolt.org/z/3o3974fjT

CC @AaronBallman @cor3ntin

**Comment by cor3ntin** [comment]
> @Fznamznon I think GCC is correct here. http://eel.is/c++draft/support.srcloc.class#support.srcloc.cons-2 does not mention template default argument at all.

It may be worth confirming with WG21 though.

**Comment by Fznamznon** [comment]
Posted https://reviews.llvm.org/D150108
