### ISSUE TITLE
Miscompilation of `x / umax(Pow2 << X, 1)` on LLVM15/LLVM16

### ISSUE THREAD

**Issue by goldsteinn** [llvm/llvm-project#62221]
This came up with investigating / patching PR62175

The following snippet:
```ll
declare i8 @llvm.umax.i8(i8, i8)
define i8 @udiv_fail_shl_overflow(i8 %x, i8 %y) {
  %shl = shl i8 2, %y
  %min = call i8 @llvm.umax.i8(i8 %shl, i8 1)
  %mul = udiv i8 %x, %min
  ret i8 %mul
}
```

Gets miscompiled on LLVM 15/LLVM 16: https://godbolt.org/z/ehen9hz6G
to
```ll
 %1 = add i8 %y, 1
  %mul1 = lshr i8 %x, %1
  ret i8 %mul1
```
which is not equivilent: https://alive2.llvm.org/ce/z/Yy7h57

because the `shl i8 2, %y` can overflow.

In the original IR, that would just mean dividing by `1` so returning `%x`.
In the generated IR that means `lshr` by `8` which returns `poison`.

This was fixed on trunc with:  https://reviews.llvm.org/D148609

but the `AssumeNonZero` piece of the the patch needs to be backported
to LLVM 15/LLVM 16.

**Comment by nikic** [comment]
> @nikic issue. I know how to do normal backports, but since the patch needs to be modified, how do I specify the commit to be backported?

This is done by pushing the commit to a branch on your llvm-project fork and then running `/branch goldsteinn/llvm-project/BRANCH_NAME`.
