### ISSUE TITLE
clang: Construction of subobject of member 'Y' of union with active member 'X' is not allowed in a constant expression

### ISSUE THREAD

**Issue by alexkaratarakis** [llvm/llvm-project#62225]
Min repro:
```cpp
#include <memory>

union MyUnion
{
    char dummy_{};
    int data_[50];
};

constexpr int test()
{
    MyUnion my_union{};
    std::construct_at(my_union.data_ + 1, 999);
    return 5;
}

int main()
{
    static_assert(test() > 0);
}
```

`clang` rejects the above code with:
```
<source>:19:19: error: static assertion expression is not an integral constant expression
    static_assert(test() > 0);
                  ^~~~~~~~~~
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/14.0.0/../../../../include/c++/14.0.0/bits/stl_construct.h:97:14: note: construction of subobject of member 'data_' of union with active member 'dummy_' is not allowed in a constant expression
    { return ::new((void*)__location) _Tp(std::forward<_Args>(__args)...); }
             ^
<source>:12:5: note: in call to 'construct_at(&my_union.data_[1], 999)'
    std::construct_at(my_union.data_ + 1, 999);
    ^
<source>:19:19: note: in call to 'test()'
    static_assert(test() > 0);
                  ^
1 error generated.
```

However, `gcc` and `msvc` accept the above code.

Demo: https://godbolt.org/z/EYvsWdbsr

(came up in constexpr vector discussion [here](https://old.reddit.com/r/cpp/comments/12l7z40/conceptual_implementation_for_a_constexprfriendly/))

**Comment by shafik** [comment]
I believe clang is correct here based on [expr.const p6](https://eel.is/c++draft/expr.const#6) which I believe means if `data_` was the current active member of the union this would be ok.

Also see: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102286 

and [DR 2469](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2469)

This was recently discussed on the core reflector and the one comment there also seemed to lean in that direction: https://lists.isocpp.org/core/2023/03/14050.php

CC @zygoloid @hubert-reinterpretcast

**Comment by suranapranay** [comment]
why does this work?
https://godbolt.org/z/KnGdvz9va


```
#include <memory>

union MyUnion
{
    char dummy_{};
    int data_[50];
};

constexpr int test()
{
    MyUnion my_union{};
    my_union.data_[1] = 999;
    std::construct_at(my_union.data_ + 1, 999);
    return 5;
}

int main()
{
    static_assert(test() > 0);
}

```

**Comment by shafik** [comment]
Yes, because the assignment started the lifetime of the member, see [class.union.general p5](https://eel.is/c++draft/class.union#general-5)

**Comment by tbaederr** [comment]
So this can be closed?

**Comment by alexkaratarakis** [comment]
Thank you for the responses! Closing as it appears clang has the correct behavior.
It seems gcc already has a bug for this, and I filed a bug for msvc: https://developercommunity.visualstudio.com/t/msvc-allows-accessing-non-active-member/10342864
