### ISSUE TITLE
explicit instantiation declaration makes explicit specialization fail

### ISSUE THREAD

**Issue by lhmouse** [llvm/llvm-project#62233]
https://gcc.godbolt.org/z/b8MxYT449

```c++
template<class T> class X {
public:
   static T v;
   static void f(T);
};

// vvvvvvvv
#ifndef NO_EXTERN_TEMPLATE
  extern template class X<const char*>;
  extern template class X<float>;
#endif
// ^^^^^^^^

template class X<const char*>;
template class X<float>;

template<class T> T X<T>::v = 0;
template<class T> void X<T>::f(T arg) { v = arg; }

template<> const char* X<const char*>::v = "Hello";
template<> void X<float>::f(float arg) { v = arg * 2; }
```

With the explicit instantiation declaration, Clang gets stumbled by this:

```console
<source>:20:40: error: explicit specialization of 'v' after instantiation
template<> const char* X<const char*>::v = "Hello";
                                       ^
```

but before investigation, I would like to know whether this piece of code is valid.

**Comment by erichkeane** [comment]
So the quote from temp.expl.spec I think does much of the lifting here: doing anything that causes an instantiation which doesn't have the explicit specialization reachable (that is, either 'after' it, or only in a different TU/etc), is ill-formed, no diagnostic required.

This also allows us to instantiate the template whenever we'd like, as soon as we see it (like we sometimes do), or wait until 1st use (like we also sometimes do!), or just defer it to the end of the translation unit (which we ALSO sometimes do!).  I believe we end up being more aggressive in the 1st two categories than other compilers due to some design decisions that were made before I joined the project.

**Comment by zyn0217** [comment]
Thank you for your explanation and it's my first time to hear such anecdote on templates. :)

**Comment by erichkeane** [comment]
I don't believe that is legal, for the same reason.  Those are still explicit specializations.

**Comment by lhmouse** [comment]
Let's quote that paragraph, sentence by sentence:

Given
```c++
template<class T> struct X {
   static void f(T);
};

extern template class X<float>;   // [1]
template class X<float>;   // [2]

template<> void X<float>::f(float arg) { }   //  [3]   error: explicit specialization of 'f' after instantiation
```

> [temp.expl.spec] 7 If a template, a member template or a member of a class template is explicitly specialized, ...

This applies

> ... a declaration of that specialization shall be reachable from every use of that specialization that would cause an implicit instantiation to take place, ...

There is an implicit instantiation declaration [1] and an implicit instantiation definition [2]. The template is not used otherwise. So no implicit instantiation can take place.

> ... in every translation unit in which such a use occurs; no diagnostic is required[.](https://eel.is/c++draft/temp.expl.spec#7.sentence-1) If the program does not provide a definition for an explicit specialization and either the specialization is used in a way that would cause an implicit instantiation  ...

This does not apply.

> ... to take place or the member is a virtual member function,  ...

Not either. The function is static and not virtual.

> the program is ill-formed, no diagnostic required[.](https://eel.is/c++draft/temp.expl.spec#7.sentence-2) An implicit instantiation is never generated for an explicit specialization that is declared but not defined[.](https://eel.is/c++draft/temp.expl.spec#7.sentence-3)

**Comment by erichkeane** [comment]
It is my understanding from having looked into this in the past, and having discussed it with Core wording experts, that our implementation strategy is explicitly permitted by the standard.  Feel free to peruse Ch13 (https://eel.is/c++draft/#temp) to convince yourself of that.

**Comment by lhmouse** [comment]
Thanks for your opinion.

It's probably bad to specialize things this way. There should be more standard and less error-prone solutions.
