### ISSUE TITLE
[InstCombine] Failure to fold bswap(and(x,bswap(y)) -> and(bswap(x),y)

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#62236]
https://alive2.llvm.org/ce/z/FbY8Cu

```ll
declare i16 @llvm.bswap.i16(i16)

define i16 @src(i16 %x, i16 %y) {
  %yy = tail call i16 @llvm.bswap.i16(i16 %y)
  %and = and i16 %x, %yy
  %res = tail call i16 @llvm.bswap.i16(i16 %and)
  ret i16 %res
}
define i16 @tgt(i16 %x, i16 %y) {
  %xx = tail call i16 @llvm.bswap.i16(i16 %x)
  %and = and i16 %xx, %y
  ret i16 %and
}
```

If the inner bswap has oneuse, then we can push the outer bswap through the bitlogic op and reduce the number of bswaps, this is probably true for bitreverse as well.

```ll
----------------------------------------
define i16 @src(i16 %x, i16 %y) {
%0:
  %yy = bswap i16 %y
  %and = and i16 %x, %yy
  %res = bswap i16 %and
  ret i16 %res
}
=>
define i16 @tgt(i16 %x, i16 %y) {
%0:
  %xx = bswap i16 %x
  %and = and i16 %xx, %y
  ret i16 %and
}
Transformation seems to be correct!
```

**Comment by austin880625** [comment]
Hi, I'd like to try to work on this issue. I've reproduced it and am digging into existing InstCombine implementation. Will update my progress here in one week

**Comment by austin880625** [comment]
Proposed patch:
[https://reviews.llvm.org/D149577](https://reviews.llvm.org/D149577)

**Comment by austin880625** [comment]
Separated test and implementation, the patch for implementation is [D149699](https://reviews.llvm.org/D149699)

**Comment by RKSimon** [comment]
Bitreverse candidate patch: https://reviews.llvm.org/D151246

**Comment by RKSimon** [comment]
> Bitreverse candidate patch: https://reviews.llvm.org/D151246

Committed at 68c5d46b6ec46c59afa052d2b2945ca7b22f58d6

Thank you!
