### ISSUE TITLE
who implements C23 <stdbit.h> and <stdckdint.h>?

### ISSUE THREAD

**Issue by enh-google** [llvm/llvm-project#62248]
Are these like `<stdnoreturn.h>`, or like `<stdio.h>`? I don't care, but it would be silly for me to add them to bionic if Clang will just provide its own anyway :-)

(the Clang `<tgmath.h>` in particular makes me think this might be one you'd rather do yourselves?)

**Comment by AaronBallman** [comment]
I think `<stdchkdint.h>` will likely come from the C standard library, but I can see `<stdbit.h>` going either way (it's part of the freestanding requirements, but we're leaning more and more towards the user having to supply their own freestanding-compatible libc so that our headers basically only provide macros.

CC @jyknight @zygoloid @efriedma-quic @rjmccall for further opinions

**Comment by enh-google** [comment]
> I think <stdchkdint.h> will likely come from the C standard library, but I can see <stdbit.h> going either way

did you mean that, or did you mean the opposite? <stdckdint.h> is macro-only, whereas <stdbit.h> says "It is unspecified whether any generic function declared in <stdbit.h> is a macro or an identifier declared with external linkage".

tbh, i think these are only useful as macros, because the whole point is that they're all just builtins that hopefully resolve to a single instruction. which is why it seems like maybe the _compilers_ (who own the builtins) should own the headers too?

(i'm happy to contribute headers --- i'm interested in reducing duplication, not specifically about getting out of doing work myself :-) )

**Comment by efriedma-quic** [comment]
stdbit.h can't really be implemented as just a header because it's legal to take the address of some of the functions.  (I mean, maybe you could do something tricky to make the implementations linkonce, but I don't think we want to.)

**Comment by MaskRay** [comment]
(other C vendors) @DimitryAndric  @richfelker

**Comment by enh-google** [comment]
> stdbit.h can't really be implemented as just a header because it's legal to take the address of some of the functions

doesn't the part of the standard i quoted above explicitly give us the latitude to _not_ have them be real functions? "It is unspecified whether any generic function declared in <stdbit.h> is a macro or an identifier declared with external linkage."

**Comment by efriedma-quic** [comment]
The standard says it's "unspecified whether any *generic* function declared in <stdbit.h> [...]".  Note the word "generic"; I'm pretty sure the rule is only supposed to apply to the type-generic functions, and the non-generic functions follow the ordinary rules for standard library functions.

**Comment by AaronBallman** [comment]
> The standard says it's "unspecified whether any _generic_ function declared in <stdbit.h> [...]". Note the word "generic"; I'm pretty sure the rule is only supposed to apply to the type-generic functions, and the non-generic functions follow the ordinary rules for standard library functions.

Oh shoot, you're right Eli (sorry for waffling). The allowances in 7.1.4 don't save us (they're what obligate us to make the non-generic APIs be real functions at the end of the day).

**Comment by pirama-arumuga-nainar** [comment]
The consensus, IIUC, is that clang will provide `<stdckdint.h>` and the C standard library should provide `<stdbit.h>`.  @ZijunZhaoCCK is working on adding `stdckdint.h`.

**Comment by AaronBallman** [comment]
I agree, that's the consensus here. And thank you to @ZijunZhaoCCK for looking into adding `stdckdint.h`!

**Comment by remexre** [comment]
I can file this as a new issue if necessary, but I think putting `stdbit.h` solely in the libc's hands might not be the best decision given that the functions need to work on the `unsigned _BitInt(N)` types too -- I don't think there's a great way to support that with `_Generic` alone.

**Comment by enh-google** [comment]
> I can file this as a new issue if necessary, but I think putting `stdbit.h` solely in the libc's hands might not be the best decision given that the functions need to work on the `unsigned _BitInt(N)` types too -- I don't think there's a great way to support that with `_Generic` alone.

yeah, i feel like `<stdbit.h>` is somewhere between "useless" and "actively harmful" without the compiler providing a corresponding builtin for each function. (sure, there are microcontrollers where you're missing instructions, but on regular cpus the whole point of `<stdbit.h>` is that everything should just be one or two instructions. a developer is better off using `__builtin_clz()` or whatever until/unless clang has builtins for `stdc_bit_whatever()`.)

i keep coming back to this as Android's libc maintainer (i could have really used bit_ceil() the the other day!), but i worry i'd be making things worse if i do anything here.

(though i suppose i can at least try to write them in terms of builtins clang _does_ have, i note that gcc added all the `<stdbit.h>` builtins already.)

**Comment by AaronBallman** [comment]
> > I can file this as a new issue if necessary, but I think putting `stdbit.h` solely in the libc's hands might not be the best decision given that the functions need to work on the `unsigned _BitInt(N)` types too -- I don't think there's a great way to support that with `_Generic` alone.
> 
> yeah, i feel like `<stdbit.h>` is somewhere between "useless" and "actively harmful" without the compiler providing a corresponding builtin for each function. (sure, there are microcontrollers where you're missing instructions, but on regular cpus the whole point of `<stdbit.h>` is that everything should just be one or two instructions. a developer is better off using `__builtin_clz()` or whatever until/unless clang has builtins for `stdc_bit_whatever()`.)
> 
> i keep coming back to this as Android's libc maintainer (i could have really used bit_ceil() the the other day!), but i worry i'd be making things worse if i do anything here.
> 
> (though i suppose i can at least try to write them in terms of builtins clang _does_ have, i note that gcc added all the `<stdbit.h>` builtins already.)

The compiler will almost certainly provide builtins for these functions, but that's not the same as being responsible for implementing the header. e.g., we have `__builtin_strlen` because we want to be able to constant evaluate such calls even in C where there is no such thing as a `constexpr` function. The same is true for the interfaces in `stdbit.h`.

This issue was about whether Clang should vend `stdbit.h` the same way we vend `stddef.h`. We're basically saying that the compiler should not be responsible for providing the header file itself.

**Comment by enh-google** [comment]
> The compiler will almost certainly provide builtins for these functions, but that's not the same as being responsible for implementing the header. e.g., we have __builtin_strlen because we want to be able to constant evaluate such calls even in C where there is no such thing as a constexpr function. The same is true for the interfaces in stdbit.h.

my point was perhaps a bit specific to how we do things in Android's libc. basically, "if there's a builtin, the header will use that directly [rather than relying on the compiler to rewrite a library call (a) because that's historically been spotty and (b) because there's a documentation benefit to making it super clear that the caller is getting a bargain ... most users aren't going to read the headers, sure, but an order of magnitude fewer users are also going to read the llvm source!]". what do we do in all the cases where the standard requires a function? something like:
```
// foo.h
#define bar(x) __builtin_bar(x)

// foo.cpp
#include <foo.h>
int (bar)(x) { return bar(x); }
```
i haven't looked at anything but their header, but i think this is what glibc has done for their <stdbit.h> implementation too.

so my original question was really "if we assume [because we know it to be true] that clang is 'the' compiler for more than one libc, should clang [unlike gcc, which has only glibc to worry about] have the <stdbit.h> that does all the preprocessor nonsense so that all the Android and Apple and FreeBSD and whoever else i'm forgetting doesn't have to duplicate it themselves?".

even just Android and iOS using the exact same bits [pun intended] would be a Good Thing for users (read: app developers). that kind of "my code works the same on both platforms i deploy it to" thing was the main reason why app developers were excited to have Android and iOS both using llvm in the first place.

(and although i'd only originally thought of the "shouldn't this be in llvm?" argument in terms of "dealing with _new_ builtins and specific clang version tests etc", i now realize that if there's going to be a time where clang _doesn't_ have specific builtins and expects users to hack together something out of _existing_ builtins ... that's actually a stronger argument for "one true implementation" upstream.)

**Comment by richfelker** [comment]
FWIW, on the musl side of things we generally don't use compiler-provided headers, taking the BSD approach where they are *after* the main include directory (e.g. `/usr/include`) rather than before it so that headers which are purely for machine-specific intrinsics or whatever else is entirely in the compiler's domain can still be reached but so that clashing things in the standard header namespace don't get picked up first.

If a header defines any types that can also be obtained from other places, like `size_t` or `intN_t`, and it's not allowed to just include some other header implicitly to get those, then there's no question. We need to provide it.

If llvm provides a default one, though, that won't hurt; it just won't get used (once we've added C23 stuff).

I'm not sure if we'll add any explicit macros using compiler builtins or just leave it to the compiler to do its own transformation to use builtins if it wants to.

**Comment by efriedma-quic** [comment]
The issue still is, as noted before, that there are symbols defined in stdbit.h which must be implemented inside libc.  If clang provides a header that declares `unsigned stdc_bit_width_us(unsigned short value);` without a definition, users are going to get mysterious link errors, and possibly other weird behavior depending on how the libc normally declares functions.

**Comment by richfelker** [comment]
While it's possible that users/applications are doing very wrong things nowadays, the norm is that you do link tests, not compile tests, to check for availability of new/optional/extension external functions.

However, in the case of C23 functionality, it seems plausible that you should be able to determine availability via the version macros the headers define. In which case, yes, it seems problematic for the compiler to ship one if the libc doesn't actually have the functions.

**Comment by enh-google** [comment]
> The issue still is, as noted before, that there are symbols defined in stdbit.h which must be implemented inside libc. If clang provides a header that declares `unsigned stdc_bit_width_us(unsigned short value);` without a definition, users are going to get mysterious link errors, and possibly other weird behavior depending on how the libc normally declares functions.

give it a name that makes it clear that it's an implementation detail and let the host libc #include it? (or not, for libcs like musl that want to do everything themselves.)

**Comment by efriedma-quic** [comment]
I'd be fine with adding features to clang to help make implementing stdbit.h easier.  Exactly what form that takes, I'm not sure.  If we add builtins, I'm not sure a header on top of that would be that useful.
