### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by starbugs-qurong** [llvm/llvm-project#62257]
Consider the following example:

```c
#include <stdio.h> 
float b1965kvgK6 = 0.6;
long O9058791 = 5085280;
short B8G5eG6kc = 482;
short q0L715IF3 = 701;
int efBS4s70TM( int e77wKxjnxd, long IoT7Sf0) {
	int CUloE53tcount = 0;
	if (b1965kvgK6>0) {
		long ZF75974J = (IoT7Sf0 / (((((IoT7Sf0 == 0) ? 1 : (IoT7Sf0)) == 0) ? 1 : (((IoT7Sf0 == 0) ? 1 : (IoT7Sf0))))));
		int j4W8hb6 = e77wKxjnxd+1;
		if (e77wKxjnxd) {
			double eNfqr8I41 = --b1965kvgK6;
			int x3eH122Md = ((323) % (((((B8G5eG6kc == 0) ? 1 : (B8G5eG6kc)) == 0) ? 1 : (((B8G5eG6kc == 0) ? 1 : (B8G5eG6kc))))));
			double K122boHM6e = ((++b1965kvgK6) / (((((b1965kvgK6 == 0) ? 1 : (b1965kvgK6)) == 0) ? 1 : (((b1965kvgK6 == 0) ? 1 : (b1965kvgK6))))));
			int w9wY881T1Ccount = 0;
			do {
				w9wY881T1Ccount = w9wY881T1Ccount + 1;
				int zB3ijw3T = e77wKxjnxd++;
				if (((((((B8G5eG6kc++)) % (((((B8G5eG6kc == 0) ? 1 : (B8G5eG6kc)) == 0) ? 1 : (((B8G5eG6kc == 0) ? 1 : (B8G5eG6kc))))))) / (((((x3eH122Md == 0) ? 1 : (x3eH122Md)) == 0) ? 1 : (((x3eH122Md == 0) ? 1 : (x3eH122Md))))))) != (((B8G5eG6kc*(B8G5eG6kc))))) {
					int gYBZII74Ta = ((((((--B8G5eG6kc))) + ((--B8G5eG6kc)))) / (((((x3eH122Md == 0) ? 1 : (x3eH122Md)) == 0) ? 1 : (((x3eH122Md == 0) ? 1 : (x3eH122Md))))));
					if (e77wKxjnxd) {
						int h01BQX3count = 0;
						do {
							h01BQX3count = h01BQX3count + 1;
							int dX6oH9Wcount = 0;
							do {
								dX6oH9Wcount = dX6oH9Wcount + 1;
								if (((((4457.3))*(((3943.3)*(0.11))))) > (--b1965kvgK6)) {
									int q30KFlscount = 0;
									do {
										q30KFlscount = q30KFlscount + 1;
										int l84QBOKcount = 0;
										do {
											l84QBOKcount = l84QBOKcount + 1;
											if (l84QBOKcount > 2) {
												break;
											}
											long m1t45q94e7 = IoT7Sf0 % ZF75974J;
											ZF75974J ^= 9185431;
											IoT7Sf0 >>= 5663379;
										} while (IoT7Sf0);
									} while (q30KFlscount<3);
								}
								int C510EWgcount = 0;
								do {
									C510EWgcount = C510EWgcount + 1;
									if (C510EWgcount > 2) {
										break;
									}
									double A993mMi = b1965kvgK6++;
									IoT7Sf0 <<= --IoT7Sf0;
									long b2p3Nka = --ZF75974J;
								} while (!(e77wKxjnxd));
							} while (dX6oH9Wcount<3);
						} while (h01BQX3count<3);
					}
				}
			} while (w9wY881T1Ccount<3);
		}
	}
	return  (-B8G5eG6kc);
}
int main() {
	int L7KFimX4TC = 2227;
	long S6381FdD58 = 4247430;
	int Uk4W7C7I = efBS4s70TM( L7KFimX4TC,S6381FdD58);
	printf("%d\n", Uk4W7C7I);
	printf("%d\n", L7KFimX4TC);
	printf("%d\n", S6381FdD58);
	return 0;
}
```

This will print the following content on GCC 9.4.0:
```console
-479
2227
4247430
```
exception happens when using Clang 17:
```console
Floating point exception (core dumped)
```

The related files can be found in https://github.com/starbugs-qurong/c-compiler-test/tree/main/clang

**Comment by starbugs-qurong** [comment]
I think it is a optimization problem. I have reduced the program as follows. I compiled this program by "clang -O2 test.c -o test_clang" under clang17.0.0, clang1515.0.7 in Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-148-generic x86_64), and run it by "./test_clang", there is a infinite loop in the optimized code and it will timeout when I run it. However, it will run successfully in clang17, clang15 without O2. Also, if I change the file extension test.c to test.cpp, it will run successfully in clang17, clang15 with O2.  In clang 14.0.0, It can run successfully regardless of whether the optimization option O2 is enabled or not.
#include <stdio.h> 
int main() {
	int con = 1;
	int a = 2;
	do {
		int b = 2;
		do {
		} while (b--);
		con >>= 32;
	} while (con&a--);
	printf("%d\n", con);
	return 0;
}

After observing the compiled content, it was found that it contained a loop：
main:                                   # @main
	.cfi_startproc
# %bb.0:
	movl	$-2, %eax
	.p2align	4, 0x90
.LBB0_1:                                # =>This Inner Loop Header: Depth=1
	incl	%eax
	jmp	.LBB0_1
.Lfunc_end0:
	.size	main, .Lfunc_end0-main
	.cfi_endproc
                                        # -- End function
Although the right shift operation exceeding 32 in line 9 is a undefined behavior, the loop generated after optimization should be a bug.

**Comment by starbugs-qurong** [comment]
I think it is a optimization problem. I have reduced the program as follows. I compiled this program by "clang -O2 test.c -o test_clang" under clang17.0.0, clang1515.0.7 in Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-148-generic x86_64), and run it by "./test_clang", there is a infinite loop in the optimized code and it will timeout when I run it. However, it will run successfully in clang17, clang15 without O2. Also, if I change the file extension test.c to test.cpp, it will run successfully in clang17, clang15 with O2.  In clang 14.0.0, It can run successfully regardless of whether the optimization option O2 is enabled or not.

```c
int main() {
	int con = 1;
	int a = 2;
	do {
		int b = 2;
		do {
		} while (b--);
		con >>= 32;
	} while (con&a--);
	printf("%d\n", con);
	return 0;
}
```


After observing the compiled content, it was found that it contained a loop：
```
main:                                   # @main
	.cfi_startproc
\# %bb.0:
	movl	$-2, %eax
	.p2align	4, 0x90
.LBB0_1:                                # =>This Inner Loop Header: Depth=1
	incl	%eax
	jmp	.LBB0_1
.Lfunc_end0:
	.size	main, .Lfunc_end0-main
	.cfi_endproc
                                        \# -- End function
```
Although the right shift operation exceeding 32 in line 9 is a undefined behavior, the loop generated after optimization should be a bug.

**Comment by DimitryAndric** [comment]
I can understand what you want the compiler to do, but undefined behavior is undefined behavior, and in that case the compiler is technically allowed to do *anything*, including dropping parts of the program that have become irrelevant or unreachable after the undefined behavior.

Just change `con` to a 64 bit type (usually `long` is enough, or better use `int64_t`), then you are allowed to shift it by 32 bits. Otherwise, you cannot assume anything about the resulting output.
