### ISSUE TITLE
[OSX][TargetLibraryInfo] strrchr is replaced to non-existed memrchr

### ISSUE THREAD

**Issue by kpdev** [llvm/llvm-project#62254]
On Mac OSX (macOS version 12.4, sdk version 12.1) llvm can replace call to `strrchr()` with call to `memrchr()` when string length is known at compile time. This results in link error, because `memrchr` is not present in `libSystem`. It is needed to disable this optimization in `TargetLibraryInfo` for affected OSX versions.

**Comment by kpdev** [comment]
Can I help to solve it somehow? Maybe some additional info is needed? @badger200 @EugeneZelenko

**Comment by mohd-akram** [comment]
Any update on merging [this](https://reviews.llvm.org/D155168)? This issue is in LLVM 15 and 16, and is breaking packages that use `strrchr` on macOS. Hopefully it can be fixed before LLVM 17.

**Comment by Endilll** [comment]
@mohd-akram I'd say if you want to get this into 17, you have to nag reviewers hard enough to get it reviewed and landed during the upcoming week.

**Comment by mohd-akram** [comment]
This was fixed in a7a6ef3b809100a1e7724443afe94d020d4c956b, but it's still not in LLVM 17 as of 17.0.6.

**Comment by mohd-akram** [comment]
@tru Maybe this can be cherry-picked for 17?

**Comment by Endilll** [comment]
@mohd-akram Commit you referenced landed ≈3 weeks after 17 cut-off, so it didn't make it into the first 17 release. No one put effort to cherry-pick it into subsequent 17 releases, so it didn't make it into 17.0.6 either. We are close to 18 cut-off now, and this commit will make it in there.
