### ISSUE TITLE
Implement JITLink 64-bit PowerPC support and an ELF/ppc64{le} backend

### ISSUE THREAD

**Issue by lhames** [llvm/llvm-project#62253]
We want JITLink to support ppc64{le} (e.g. for https://root.cern).

I've posted a review for a skeleton ppc64{le} JITLink backend at https://reviews.llvm.org/D148192. We can use this issue for discussion on the broader effort.

**Comment by bzEq** [comment]
Thanks for the initial patch. I am wondering how is ROOT using JITLink? IIUC, ROOT uses cling and cling requires JITLink.

**Comment by lhames** [comment]
Hi @bzEq. Yep. The full path is ROOT uses Cling, Cling uses ORC, ORC uses JITLink. :)

**Comment by bzEq** [comment]
JITLink ppc64{le} backend is generally usable now, I'll close this issue.
