### ISSUE TITLE
[clang] crash when meeting template friend function

### ISSUE THREAD

**Issue by HerrCai0907** [llvm/llvm-project#62265]
```c++
template <class T> int Foo(T X);
template <int N, int B, int C> struct Thief {
  template <class T> friend int Foo(T X) { 
    return B; 
  }
};
template struct Thief<1,2,3>;
int main() {
  Foo(1.0);
}
```
https://godbolt.org/z/vEGdvhc3q

**Comment by HerrCai0907** [comment]
I have done some work for it. The issue is in 
clang/lib/Sema/SemaTemplateInstantiateDecl.cpp Line 5065
```c++
    MultiLevelTemplateArgumentList TemplateArgs = getTemplateInstantiationArgs(
        Function, /*Final=*/false, nullptr, false, PatternDecl);
```
`TemplateArgs` in here is `[[T]]`. But it should be `[[N, B, C], [T]]`

**Comment by shafik** [comment]
Confirmed, feels like something that @erichkeane @alexander-shaposhnikov might know about

**Comment by erichkeane** [comment]
https://reviews.llvm.org/D146178 alters that a bit, but I could definitely believe we have another bug in there.  The getTemplateInstantiationArgs function is still a 'work in progress' these days (its being pushed to do things it never had to do before, particularly with concepts), but it looks like this is friend related (which is a little surprising).

Perhaps we're just quitting too early on collecting args on inline-defined-friends like this,

**Comment by HerrCai0907** [comment]
> but it looks like this is friend related.

Yeah, for inline friend, it does not consider the template in outsider RecordDecl.
But I don't find a solution to get it from FunctionDecl's context. I need a `ClassTemplateSpecializationDecl` to get the template arg list but I can only get a `CXXRecord` or `ClassTemplateDecl`.

**Comment by erichkeane** [comment]
So you SHOULD have been able to get it from the lexicalDeclContext, but it appears that isn't set correctly.  So you'll have to fix that FIRST.

I see that the `FunctionDecl` is created in `SemaTemplateInstantiateDecl.cpp` ~2138 and ~2160 seems to not be doing the right thing here.  For some reason, `Owner` isn't the right value I think, so some debugging will be needed there.
