### ISSUE TITLE
[InstCombine] Missing fold for (a | ~b) ? 0 : a

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#62263]
https://alive2.llvm.org/ce/z/Cpdcgr
```llvm
define i32 @src(i32 %0, i32 %1) {
%2:
  %3 = xor i32 %1, 4294967295
  %4 = or i32 %3, %0
  %5 = icmp eq i32 %4, 0
  %6 = select i1 %5, i32 %0, i32 0
  ret i32 %6
}
=>
define i32 @tgt(i32 %0, i32 %1) {
%2:
  ret i32 0
}
Transformation seems to be correct!
```

Original source code:
https://godbolt.org/z/9szsEa733
```c
int foo(int a, int b)
{
    return (a | ~b) ? 0 : a;
}

int bar(int a, int b)
{
    return 0;
}
```

**Comment by floatshadow** [comment]
It seems gcc will optimize it into `xor  %eax,%eax`, but failed to recognize this similar pattern with vector type version.
https://godbolt.org/z/hxbqhad7q

clang also miss the optimization for ` return (a | b) ? 0 : a;`
https://alive2.llvm.org/ce/z/XTmRx6

**Comment by floatshadow** [comment]
If we have mutiple ORs like `(a | b | c | d) ? 0 : a`. It's quite reasonable to expect we can optimize it to 0 as well.
In simple cases, `visitOr` will invoke `reassociateForUses` . The later would reassociate ORs and expose `a` to the outermost as `a` has the mutiple uses ( (A op B) op C --> (B op C) op A). 
But if C has mutiple uses, this transform would not reassicate, see https://godbolt.org/z/eYG9cqvne. (GCC still find this pattern and simply ret 0).

**Comment by vfdff** [comment]
Don't address the recusive issue according the discussion on D148986
