### ISSUE TITLE
Clang rejects out-of-line function definition with concept-auto return type

### ISSUE THREAD

**Issue by danakj** [llvm/llvm-project#62272]
Clang 16 accepted the code, GCC and MSVC accept the code, but Clang HEAD does not.

https://godbolt.org/z/j67W4EYjo

```cpp
template <class A, class B>
concept Concept = true;

template <class B>
struct IteratorBase {
    Concept<B> auto func();
};

template <class B>
Concept<B> auto IteratorBase<B>::func() {}
```
```console
<source>:10:34: error: return type of out-of-line definition of 'IteratorBase::func' differs from that in the declaration
Concept<B> auto IteratorBase<B>::func() {}
~~~~~~~~~~~~~~~                  ^
<source>:6:21: note: previous declaration is here
    Concept<B> auto func();
    ~~~~~~~~~~~~~~~ ^
1 error generated.
```

**Comment by shafik** [comment]
CC @erichkeane @alexander-shaposhnikov this looks like it changed recently, so likely related to some of your recent work.

**Comment by danakj** [comment]
I'm trying to bisect but it's pretty late and it's slow going. So I will leave status here.

a1786a7224d067ca1a7ccbd721e3dec7f10266dd  bad
7df3c71b508b65284483225685f1ba19777f2bbb  good

In this range I see
```
commit 3524a9f84a0a1a106aa649a775066ba4d9e8ae0d
Author: Richard Smith <richard@metafoo.co.uk>
Date:   Thu Mar 30 13:08:22 2023 -0700

    Retain constraints in the canonical form of an auto type.

    This is necessary in order for type equality checking, for example
    across redeclarations, to require constraints to match. This is also a
    prerequisite for including the constraints in manglings.

    In passing, fix a bug where TemplateArgument::Profile would produce the
    same profile for two structurally different template names, which caused
    this change to re-expose the crash previously addressed by D133072,
    which it turns out had not quite addressed all problematic cases.
```

Which sounds possibly related. Nothing else stood out at a glance. @zygoloid

**Comment by erichkeane** [comment]
https://reviews.llvm.org/D146178 is currently working on this, which I hope will be committed soon.  Double-attn @alexander-shaposhnikov so he can ensure it is fixed as well (or at least, to know about it for a followup).

**Comment by danakj** [comment]
Just leaving a note that this remains broken on HEAD, when I synced today.

**Comment by danakj** [comment]
cc: @cjdb

**Comment by cjdb** [comment]
I've further reduced this to having been introduced by the changes to ASTContext.cpp.

**Comment by danakj** [comment]
Thank you!
