### ISSUE TITLE
Clang crashes on "saddsat" while compiling for armv5te/armv6 thumb

### ISSUE THREAD

**Issue by ilyakurdyukov** [llvm/llvm-project#62273]
On this code:
```c
void test(signed char *p, signed char add) {
	int a = *p + add;
	if (a > 127) a = 127;
	if (a < -128) a = -128;
	*p = a;
}
```
You can check in the [Compiler Explorer](https://godbolt.org/z/P5r3frM36), select the latest "armv8-a clang" (because armv7-a is not updated in CE), with these options: `-m32 -O2 -march=armv5te -mthumb`

Reproducible in the latest `android-ndk-r25c` (clang version 14.0.7).

This issue has been present since Сlang 10! `-march=armv6` is also affected.

**Comment by davemgreen** [comment]
There is a mismatch between clang adding +dsp and armv6/armv5te + thumb being thumb1-only. 15d28212632d550d437b8812c53a0e1f38aa4591 fixes this by limiting the generation of ssat nodes to Thumb2+dsp, like the instruction patterns.

**Comment by ilyakurdyukov** [comment]
Thanks! Your explanation of the problem also helped me find a workaround for older versions of Clang: `-mcpu=+nodsp`.
