### ISSUE TITLE
bolt does not respect CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by sirspudd** [llvm/llvm-project#62303]
I am currently packaging a prefixed version of LLVM/Clang, and while most subprojects respect the install prefix, BOLT assets are provisioned outside of it. (which results in me simply excluding BOLT from the package)

**Comment by sirspudd** [comment]
`└─[0] <git:(master aae3b30✈) > pacman -Ql clang-prefixed-release | grep 16.0.2 | wc -l
5715`

**Comment by ptr1337** [comment]
Can confirm the issue. The only way fixing this in a ugly way is something like this:
https://github.com/CachyOS/CachyOS-PKGBUILDS/blob/master/llvm-git/llvm-git/PKGBUILD#L163

But this is really ugly...

**Comment by aaupov** [comment]
Please check if the issue is addressed by 9e6e3375f12e5e61dd2e371d94c263e3862f58a1

**Comment by sirspudd** [comment]
@aaupov Hola, yes, that appears to fix the issue entirely, thank you

**Comment by ptr1337** [comment]
@aaupov 

Could the above fix get backported to llvm 16?

**Comment by aaupov** [comment]
> @aaupov
> 
> Could the above fix get backported to llvm 16?

Nah, I think we're out of the backporting window (it's not a security-critical fix), and the fix made it to LLVM 17. Closing.
