### ISSUE TITLE
[mlir][TosaToLinalg] miss encoding parameter when build tensor.empty in TosaToLinalg Pass

### ISSUE THREAD

**Issue by Sinclair-Dee** [llvm/llvm-project#62304]
When TOSA' ElementOp lowered to linalg, we first build tensor.empty. The current code is as follows:
```cpp
  for (auto result : results) {
    auto resultTy = result.getType().template cast<ShapedType>();
    emptyTensors.push_back(rewriter.create<tensor::EmptyOp>(
        loc, resultTy.getShape(), resultTy.getElementType(), filteredDims));
    opResultTypes.push_back(result.getType());
  }
```
However, the "Encoding" info in RankTensorType seems to be ignored.
Insofar as I can see, the `result`(tosa elementOp's result) here is definitely the RankTensorType, matching the type constraints in tensor.empty's Def.

So, maybe this snippet could be changed to：
```cpp
  for (auto result : results) {
    RankedTensorType rankedType = result.getType().dyn_cast<RankedTensorType>();
    emptyTensors.push_back(rewriter.create<tensor::EmptyOp>(loc, rankedType, filteredDims));
    opResultTypes.push_back(result.getType());
  }
```

**In rare cases, the encoding parameter may be needed  to pass some important information.**

**Comment by rikhuijzer** [comment]
Patch submitted at https://reviews.llvm.org/D152171.
