### ISSUE TITLE
[X86] Attempt to narrow CMP nodes if it will avoid using imm32

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#62312]
As mentioned on https://reviews.llvm.org/D148594, instructions such as:
```s
cmpl $65535, %eax # imm = 0xFFFF
```
where we know that the upper bits are zero, might be more efficiently encoded as:
```s
cmpw $-1, %ax
```
Making use of the implicit i8 sign extension etc.

This might be easier to deal with after DAG - either in isel patterns or X86ISelDAGToDAG, we probably don't need a pass for it (where we wouldn't have the necessary value tracking).

**Comment by goldsteinn** [comment]
Possible patch: https://reviews.llvm.org/D149027
phoebe helped me fix the bug.

**Comment by RKSimon** [comment]
Abandoning this - its almost impossible to make this consistently worthwhile
