### ISSUE TITLE
[clang-tidy] bugprone-assert-side-effect no longer warns since warnings on system macros are disabled

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#62314]
I noticed that `bugprone-assert-side-effect` no longer warns when using real-world `assert` coming from `cassert` - this is because warnings on system macros are disabled globally.

The reason why this was not caught in our tests is because the fake `assert` is defined in the same file as the test, instead of being included as a system header (which is what happens in the real world). Moving the assert code to a separate system header included in the test via `-isystem` makes the test fail due to unmatched `CHECK-MESSAGES` lines.

**Comment by PiotrZSL** [comment]
Fix were here: https://reviews.llvm.org/D147081
But you didn't want it...  Fell free to extract & commit it.

**Comment by carlosgalvezp** [comment]
> But you didn't want it
This is a strong, non-constructive accusation. The LLVM development guidelines are very clear, and multiple reviewers have already expressed that reviewing your patches. If you disagree with the guidelines, feel free to voice your concerns on Discourse. Phabricator is not the right forum for that, and it wastes time and energies from reviewers, leading to delays in patches getting merged.

**Comment by carlosgalvezp** [comment]
Broken down here: https://reviews.llvm.org/D150071
