### ISSUE TITLE
clang-cl/lld-link .def files ordinals don't work at all

### ISSUE THREAD

**Issue by Jimbopython** [llvm/llvm-project#62329]
When using Clang-CL/LLD-Link with a def file for a shared DLL, the ordinals placed in the def file have no impact at all.

1. The exported functions in the resulting DLL are always in the same order, ignoring the sequence specified in the def file
2. With MSVC, the numbers don't have to be ongoing. There can be spaces between the ordinals.

Visual Studio 2022
MSVC: 17.5.4
LLVM 15.0.1/16.0.1

Example:
CMake:
```cmake
cmake_minimum_required(VERSION 3.15)
project(foobar C)

set(CMAKE_C_STANDARD 11)

add_library(foobar SHARED lib.c lib.def)
```

`lib.h`:
```h
__declspec(dllexport) void foo(void);
__declspec(dllexport) void bar(void);
```

`lib.c`:
```c
#include "lib.h"
#include <stdio.h>

void foo(void) {
    printf("Foo!\n");
}
void bar(void) {
    printf("Bar!\n");
}
```

`lib.def`:
```def
EXPORTS
foo @2
bar @4
```

The result from dumpbin with MSVC native is:
```
2    0 00001010 foo
4    1 00001020 bar
```

The result from dumpbin with Clang-CL/LLD-Link is:
```
1    0 00001000 foo
2    1 00001010 bar
```

**Comment by Jimbopython** [comment]
Hi aganea,

I have a scenario with a dynamically linked library with a public interface, but proprietary, non-public backend. The .dll was built with msvc and distributed for some years. As this is a c api, the user of the api can just exchange the library without recompiling (even with different compilers). As the compilers are using the ordinals, when linking the users .exe (seems to be only the case, when they are set in the def file, otherwise the function names are used), the symbols are mixed up and the wrong functions are called or the program crashes.

For an example, compile the library (with def file) with MSVC/link.exe. Afterwards, compile a simple example with MSVC/link.exe:
```
#include "lib.h"

int main () {
    foo();
    return 0;
}
```
"Foo!" will be printed.

Now compile the lib with clang-cl/lld-link (with def file) and exchange the dll beneath the exe.
When you execute the .exe, "Bar!" will be printed, as it has ordinal number 2.

So I have this somewhat aged C API, that has the ordinals in the def file, but I want to switch the compiler/linker to llvm, as it has better performance, but this bug prevents me from being able to use the linker.

**Comment by aganea** [comment]
Please see https://reviews.llvm.org/D149611 - let me know if that fits your usage.

**Comment by Jimbopython** [comment]
The code/tests look promising. Unfortunately it seems like it does not build yet, so i won't be able to test it (yet).
