### ISSUE TITLE
False/unsuppressible positive from UBSAN alignment check on _mm256_broadcast_sd

### ISSUE THREAD

**Issue by AndyEakins** [llvm/llvm-project#62325]
I'm currently unable to run some code using `_mm256_broadcast_sd` with `-fsanitize=undefined`. The ubsan checks include 8 byte alignment which isn't consistent with other intrinsics (e.g. `_mm_load_sd`) and `__attribute__((no_sanitize("undefined")))` disables the other ubsan checks but leaves the failing alignment check.

[Example in Compiler Explorer](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:11,positionColumn:2,positionLineNumber:11,selectionStartColumn:2,selectionStartLineNumber:11,startColumn:2,startLineNumber:11),source:'%23include+%3Ccstdio%3E%0A%23include+%3Cx86intrin.h%3E%0A%23include+%3Ccstdint%3E%0A%0A__attribute__((no_sanitize(%22undefined%22)))+int+main(int+argc,+char**+argv)%0A%7B%0A%09alignas(32)+uint8_t+test%5B32%5D+%3D+%7B1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8%7D%3B%0A%09__m256+x+%3D+_mm256_broadcast_sd(reinterpret_cast%3Cconst+double*%3E(%26test%5B1%5D))%3B%0A%09printf(%22%25d%5Cn%22,+_mm_extract_epi32(_mm_castps_si128(_mm256_castps256_ps128(x)),+0))%3B%0A%09return+0%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:38.008755681595,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang1600,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-mavx+-fsanitize%3Dundefined',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+clang+16.0.0+(Editor+%231)',t:'0')),k:36.12402399490434,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gcc+12.2',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+clang+16.0.0+(Compiler+%231)',t:'0')),k:25.867220323500653,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

**Comment by wolfy1961** [comment]
It's worth noting that the intrinsic `_mm256_broadcast_sd` is implemented as
```
_mm256_broadcast_sd(double const *__a)
{
  double __d = *__a;
  return __extension__ (__m256d)(__v4df){ __d, __d, __d, __d };
}
```
so ubsan may well be within its right to generate alignment-trapping code for the dereference of `__a`. 

Looking at `_mm_load_sd`
```
static __inline__ __m128d __attribute__((__always_inline__, __nodebug__, __target__("sse2"), __min_vector_width__(128)))
_mm_load_sd(double const *__dp)
{
  struct __mm_load_sd_struct {
    double __u;
  } __attribute__((__packed__, __may_alias__));
  double __u = ((const struct __mm_load_sd_struct*)__dp)->__u;
  return __extension__ (__m128d){ __u, 0 };
}
```
the dereference of the parameter `__dp` does not happen before it's cast to a pointer to a packed struct, so there would not be a need to generate alignment trapping instrumentation?

Perhaps not suppressing the UB instrumentation is the only issue here.

**Comment by AndyEakins** [comment]
I think the lack of a structure similar to _mm_load_sd_struct in the definition of _mm256_broadcast_sd is also an issue

**Comment by RKSimon** [comment]
Adjusting the intrinsics in the avxintrin.h header is probably the best way forward - _mm_broadcast_ss/_mm256_broadcast_ss/_mm256_broadcast_sd all need addressing - either with the struct wrapper trick or we call _mm_load_ss/_mm_load_sd and broadcast the result. 

For reference, _mm_loaddup_pd (which calls _mm_load1_pd) already does this
