### ISSUE TITLE
Incorrect Output in Canonicalize Transformation for clamp_float_is_noop Unit Test in canonicalize.mlir

### ISSUE THREAD

**Issue by wyanzhao** [llvm/llvm-project#62341]
I found an issue with the canonicalize transformation in the LLVM MLIR project, specifically in the `clamp_float_is_noop` unit test within `llvm-project/mlir/test/Dialect/Tosa/canonicalize.mlir`.

Input code:
```mlir
// CHECK-LABEL: @clamp_float_is_noop
func.func @clamp_float_is_noop(%arg0: tensor<4xf32>) -> tensor<4xf32> {
  // CHECK: return %arg0
  // CHECK-NOT: "tosa.clamp"
  %0 = "tosa.clamp"(%arg0) {min_int = -128 : i64, max_int = 127 : i64, min_fp = -3.40282347E+38 : f32, max_fp = 3.40282347E+38 : f32} :  (tensor<4xf32>) -> tensor<4xf32>
  return %0 : tensor<4xf32>
}
```
Output code after running `mlir-opt -canonicalize="test-convergence"`:
```mlir
func.func @clamp_float_is_noop(%arg0: tensor<4xf32>) -> tensor<4xf32> {
  return %arg0 : tensor<4xf32>
}
```

The issue arises when the input tensor `arg0` has the following values:
```mlir
arg0 (tensor<4xf32>): (dim: 4) (0) -> -Inf, (1) -> -Inf, (2) -> -Inf, (3) -> -Inf
```

In this case, the original code outputs `-3.40282347E+38`, while the canonicalized code outputs `-Inf`. These two values are not equivalent, indicating that the canonicalize transformation produced an incorrect result for special values.

**Comment by rikhuijzer** [comment]
Well spotted! Seems like a bug to me. I've submitted a patch at https://reviews.llvm.org/D152123.
