### ISSUE TITLE
Allocatable automatic deallocation

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#62354]
See Fortran 2018 standard: "9.7.3.2 Deallocation of allocatable variables" point 2:

When the execution of a procedure is terminated by execution of a RETURN or END statement, an unsaved
allocatable local variable of the procedure retains its allocation and definition status if it is a function result or a
subobject thereof; otherwise, if it is allocated it will be deallocated.

This is currently not implemented and does not have a TODO. This causes:
- memory leaks in program relying on this feature.
- lack of type finalization for allocatable that require it.

This should be implemented in ConvertVariable.cpp here: https://github.com/llvm/llvm-project/blob/658595d031f726047f6c1a19efefc5e3d265416a/flang/lib/Lower/ConvertVariable.cpp#L791, in a similar way to what is done for local objects that require finalization (see the code below `if needEndFinalization`), except deallocation must be added to the function context cleanups.

**Comment by kiranchandramohan** [comment]
@jeanPerier is anyone working on this?

**Comment by clementval** [comment]
I'm not aware of anyone working on this at the moment.

**Comment by kiranchandramohan** [comment]
Thanks @clementval.

**Comment by jeanPerier** [comment]
Implemented in https://github.com/llvm/llvm-project/pull/67036
