### ISSUE TITLE
[AMDGPU] Invalid removal of convergence on atomic store

### ISSUE THREAD

**Issue by jhuber6** [llvm/llvm-project#62386]
The GPU backend relies on convergent attributes to prevent optimizations that change dependencies on control flow. In this example, we wish to acquire a lock on a per-wavefront basis https://godbolt.org/z/W1vE15G8v. The control flow is important here, when run with two threads on the GPU, the expected masking behavior would be the following:
```
mask 01: open(); close();
mask 10: open(); close();
```
Which should be legal as the operations within a wave are executed in lock-step according to their mask. However, the optimizer will sink the call to `close()` to a common branch, changing the control flow:
```
mask 01: open();
mask 10: open();
mask 11: close();
```
This will then deadlock because we have two `open()` calls that mutually depend on each other.

This occurs when we remove the `convergent` attribute on the `close()` call, as shown in https://godbolt.org/z/oKoz7oE7a in the IR. To solve this problem we will most likely require the convergence tokens as discussed in https://discourse.llvm.org/t/rfc-introduce-convergence-control-intrinsics/69613/3.

**Comment by arsenm** [comment]
I don't know if atomics should be treated as convergent operations or not, but my initial reaction is that they shouldn't be. A contextless atomic doesn't necessarily imply it's being used in a barrier-like way where all lanes need to execute it

**Comment by jhuber6** [comment]
What might also work is if there's a way to say "convergent, no really I mean it". Since right now we put it on the `close()` function manually and then it gets incorrectly removed by the optimizer.

**Comment by nhaehnle** [comment]
That's a nice example, thank you.

With my Khronos/Vulkan-colored glasses on, I'd say that the source code is incorrect because it relies on forward progress guarantees that aren't there, and the way to fix it is to insert a subgroup(=wave)-scope control barrier between the two if-statements to enforce an ordering of operations across invocations(=threads).

And pragmatically, that seems to do the right thing: https://godbolt.org/z/6Md4czPhc

**Comment by jhuber6** [comment]
> With my Khronos/Vulkan-colored glasses on, I'd say that the source code is incorrect because it relies on forward progress guarantees that aren't there, and the way to fix it is to insert a subgroup(=wave)-scope control barrier between the two if-statements to enforce an ordering of operations across invocations(=threads).

I'm not sure if this is really concerned with forward progress since this deadlock occurs with a single wavefront active. Sure, that one wavefront could never get scheduled, but that would mean giving up running anything on the GPU because it may never actually execute.

Generally, the idea is that if we have enough "locks" to cover the maximum number of CUs, we should be able to ensure that at least one wavefront can make forward progress as they get swapped in and out. But, I could be totally wrong about that. I haven't found any definitive answers on this front.

> And pragmatically, that seems to do the right thing: https://godbolt.org/z/6Md4czPhc

So, this problem occurred when trying to implement a complicated RPC mechanism for GPU-to-CPU function called (e.g. printf). I believe the wavefront barrier is a no-op, so this is most likely just thwarting the optimizer by calling something with side effects. Another hack I found that worked was to mark the `close()` function to be `noinline` and `nomerge` so it can't be sunk.

**Comment by nhaehnle** [comment]
It is about forward progress between threads within a wave/subgroup. LLVM is **not** a wave-level lock-step execution IR. It is a thread-level IR where the threads happen to be mapped into waves.

There is no guarantee in the abstract machine model of LLVM IR that all threads of a wave will make forward progress. There is (at best) the guarantee that at least one thread of each wave will make forward progress.

It so happens that with your original program the implementation chose a sequencing that is unlucky:

* First, odd-numbered threads make progress and acquire the lock
* Then, odd-numbered threads stop making progress
* In order to satisfy the "at least one thread of the wave makes progress" rule, even-numbered threads keep making progress indefinitely. It's just that this progress consists of uselessly spinning in the loop. (The execution of atomic operations is forward progress in the formal sense.)

The wave barrier is indeed the conceptually correct fix:

* No matter what the implementation chooses to do, even-numbered threads cannot make progress beyond the barrier until odd-numbered threads have reached it as well.
* Therefore, the only way for the implementation to satisfy the "at least one thread of the wave must make progress" rule is to have odd-numbered threads making progress until they also reach the wave barrier. In order to reach the wave barrier, the odd-numbered threads will release the lock
* After the barrier, the ordering between threads no longer matters

> I believe the wavefront barrier is a no-op, so this is most likely just thwarting the optimizer by calling something with side effects.

The wave barrier intrinsic is arguably expressed with overly conservative attributes because it's not quite clear how its meaning should be mapped onto existing LLVM IR attributes, but it is semantically exactly what you want.

**Comment by nhaehnle** [comment]
Addendum: While the wave barrier whose addition I suggested fixes your forward progress issue, your implementation of `open` and `close` is still a bit on wobbly feet in terms of memory model.

Technically:

* The `open` operation needs a wave control barrier, likely with acquire memory semantics, after the atomic `or`. De facto, the readfirstlane ends up playing this role.
* The `close` operation needs a wave control barrier with release memory semantics before the atomic `store`.

I don't think the lack of these operations is a problem in practice in today's implementation, and our modeling of wave-level barriers in LLVM IR is lacking anyway. But if you look at e.g. Vulkan or OpenCL memory models, this becomes clear.

**Comment by jhuber6** [comment]
> It is about forward progress between threads within a wave/subgroup. LLVM is not a wave-level lock-step execution IR. It is a thread-level IR where the threads happen to be mapped into waves.

Ah, this makes sense. I was thinking of the *hardware's* forward progress guarantees. So in my mind the `open` and `close` sequence was perfectly legal on the hardware level.

> The wave barrier intrinsic is arguably expressed with overly conservative attributes because it's not quite clear how its meaning should be mapped onto existing LLVM IR attributes, but it is semantically exactly what you want.

You're right, putting the `__builtin_amdgcn_wave_barrier()` in the `close()` function pretty much gets what I want. Though I'm not sure if `AMDGPU` has the concept of a non-uniform wavefront barrier like post-Volta Nvidia architectures. As far as I know the backend reduces it to a no-op, but the presence of the barrier prevents it from thinking that the atomic store is not convergent, thus fixing our probleml.

> Addendum: While the wave barrier whose addition I suggested fixes your forward progress issue, your implementation of open and close is still a bit on wobbly feet in terms of memory model.

This is something I don't understand well about atomics currently, I'd appreciate if you could elaborate more. I figured since it's only a single item we're coordinating on, and the execution model guarantees that we  cannot actually overlap these operations, a relaxed atomic would be fine. Maybe that assumption breaks down in Nvidia hardware?

**Comment by jhuber6** [comment]
> `llvm.amdgcn.wave.barrier` is a non-uniform wavefront barrier in the same sense that `llvm.amdgcn.ballot` is a non-uniform ballot.
> 
> They don't have explicit lanemask arguments, but that's a bit of an orthogonal point.

That's true, it's not like the Volta architecture where the hardware mask can differ from the true mask. So it should always be able to read it internally if the implementation requires it.

> You still need the wave barrier between the `if` statements, by the way. They serve different purposes:
> 
>     * The wave barrier in `close` before the atomic store establishes happens-before relations in the memory model across different threads of the wave
> 
>     * The wave barrier between the `if` statements "steers" forward progress in the direction you need

The problem is that we cannot control the `if` statement because it comes from user code. So that's a bit of an unsolvable problem is we cannot guard the open / close semantics with wave syncs alone.

> It's hard to make definite statements without more context, but I'm going to assume that this code is supposed to implement a fairly standard spinlock. Spinlocks need `acquire` semantics on the lock and `release` semantic on the unlock. This is true for GPUs in the same way and for the same reasons that it is true on CPUs. The point is to guard against concurrent access from other threads (in this case, other waves) to the data protected by the spinlock.

Ah, yes I forgot about that part. I used a lot of relaxed atomics because those are the only ones support at system scope on Nvidia, but since this lock is device memory it should be correct. Thanks for the info.

**Comment by jhuber6** [comment]
Yeah, the NVPTX backend doesn't support atomic stores with release https://godbolt.org/z/jhW85vhcP.

**Comment by nhaehnle** [comment]
> > You still need the wave barrier between the `if` statements, by the way. They serve different purposes:
> > ```
> > * The wave barrier in `close` before the atomic store establishes happens-before relations in the memory model across different threads of the wave
> > 
> > * The wave barrier between the `if` statements "steers" forward progress in the direction you need
> > ```
> 
> The problem is that we cannot control the `if` statement because it comes from user code. So that's a bit of an unsolvable problem is we cannot guard the open / close semantics with wave syncs alone.

Indeed, that seems a bit of an unsolvable problem. Thanks, I learned something new :)

I took a note of this problem, and I'll try to remember to let you know if I can think of something.

**Comment by ssahasra** [comment]
> In this example, we wish to acquire a lock on a per-wavefront basis https://godbolt.org/z/W1vE15G8v. The control flow is important here, when run with two threads on the GPU

Separately from the lack of forward progress guarantees, I am not sure if the program is correct even in terms of a general memory model. 

```
  if (__builtin_amdgcn_workitem_id_x() % 2 == 1) {
    open();
    close();
  }
```
In this fragment, the expectation is that only one thread in the wave successfully acquires the lock, and only that thread in the whole universe later releases the lock. But the implementation of close() simply stores a zero, which means all active threads release the lock although only one acquired it. After one of these threads releases, some thread in some other wave might have acquired it again, and additional stores from the current wave will incorrectly release it. 

This needs a dependence between the open() and close(). The call to open() should return a lane ID, and the call to close() should check the current thread against this lane ID before doing the atomic store. Something like:

```
static void __attribute__((noinline, convergent)) close(int holderID) {
   if (holderID == get_my_lane_id())
     __atomic_store_n(&lock, 0, __ATOMIC_RELAXED);
}
```
This fixes a bug in the program, but does not help in preventing the optimization from moving the call to close(), which can only be ensured with a proper forward progress guarantee.

**Comment by jhuber6** [comment]
The solution that seems to work in practice is to use the wavefront level sync @nhaehnle suggested along with ensuring that the same mask that opened the lock closes it. Currently we have all threads write to the lock, but only a single thread will have a value that claims / releases it. See the implementation at https://github.com/llvm/llvm-project/blob/main/libc/src/__support/RPC/rpc.h#L215 which this demonstration was reduced from.

I'm going to go ahead and close this issue since it may not entirely be a bug as @arsenm has said.
