### ISSUE TITLE
<type_traits> use of `__is_convertible` identifier incompatible with GCC 13

### ISSUE THREAD

**Issue by frobtech** [llvm/llvm-project#62396]
In GCC 13, `__is_convertible` is a built-in, but `__is_convertible_to` is not.
libc++ uses `__is_convertible_to` when available, but its fallback implementation without the built-in declares a `struct __is_convertible` as part of its implementation. This makes GCC 13's parser get quite unhappy since it thinks `__is_convertible` can only be the built-in and not a struct tag, apparently.

**Comment by frobtech** [comment]
https://reviews.llvm.org/D149313

**Comment by shafik** [comment]
It looks like the PR landed, can this be closed?
