### ISSUE TITLE
[clang-format] [16.0.0] CompactNamespaces: true deindents the scope contents after namespaces end

### ISSUE THREAD

**Issue by petr-polezhaev** [llvm/llvm-project#62425]
```cpp
namespace a::b {
	int value;
}

void foo()
{
	int some_code = 0;
}

void bar()
{
	if (condition()) {
		print("something");
	}
}
```
but (with `CompactNamespaces: true`, `NamespaceIndentation: All`)
```cpp
namespace a { namespace b {
	int value;
}}

void foo()
{
int some_code = 0;
}

void bar()
{
if (condition()) {
	print("something");
}
}
```

Same happens after any combination of multiple nested namespaces, most notably with anonymous namespaces
```cpp
namespace a::b { namespace {
	int value;
}}

void foo()
{
int some_code = 0;
}

void bar()
{
if (condition()) {
	print("something");
}
}
```

each nested namespace compacted de-indents following contents by one level
```cpp
namespace a { namespace b { namespace {
	int value;
}}}

void foo()
{
int some_code = 0;
}

void bar()
{
if (condition()) {
print("something");
}
}
```

With `CompactNamespaces: false` everything is fine
```cpp
namespace a {
	namespace b {
		namespace {
			int value;
		}
	}
}

void foo()
{
	int some_code = 0;
}

void bar()
{
	if (condition()) {
		print("something");
	}
}
```

Checked on:
- `clang-format version 16.0.0`
- `clang-format version 16.0.2 (https://github.com/llvm/llvm-project.git 18ddebe1a1a9bde349441631365f0472e9693520)`

**Comment by rymiel** [comment]
This has already been fixed by 7ba91016c6ad4cb8f82ed154753ddeeb524f9a64. This fix isn't a part of any release yet, but it will be a part of version 17.
