### ISSUE TITLE
std::uniform_real_distribution allows initializing with non-floating-point types

### ISSUE THREAD

**Issue by ngzhian** [llvm/llvm-project#62433]
Probably missing a static assert somewhere:
https://github.com/llvm/llvm-project/blob/main/libcxx/include/__random/uniform_real_distribution.h#L28

Like in https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/random.h#L1781

**Comment by philnik777** [comment]
Where exactly does the standard forbid instantiation `uniform_real_distribution` with a non-floating-point type?

**Comment by ngzhian** [comment]
You're right, it doesn't forbid, though it is undefined behavior, so maybe ubsan can warn about it? https://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution "The result type generated by the generator. The effect is undefined if this is not one of float, double, or long double."

**Comment by philnik777** [comment]
Maybe more general: http://eel.is/c++draft/rand.req.genl should be enforced by adding correspinding `static_assert`s.

**Comment by SpinSpinSugar** [comment]
Hi, I'd like to take this issue on

**Comment by NhatNguyen1810** [comment]
Hi I would like to work on this if this can be assigned to me.

**Comment by NhatNguyen1810** [comment]
@philnik777 phil
I can't create a new patch on Phabricator. It says `New revision creation is disabled. Please use GitHub Pull Requests instead.` Is the process now entirely on Github ?

**Comment by EugeneZelenko** [comment]
@NhatNguyen1810: Yes, you need to create pull request on GitHub.

**Comment by ldionne** [comment]
@NhatNguyen1810 @pranav10903 It looks like we've got two PRs fixing this? https://github.com/llvm/llvm-project/pull/70564 and https://github.com/llvm/llvm-project/pull/70485. Or are they fixing different things?

**Comment by Pranav10903** [comment]
> @NhatNguyen1810 @pranav10903 It looks like we've got two PRs fixing this? https://github.com/llvm/llvm-project/pull/70564 and https://github.com/llvm/llvm-project/pull/70485. Or are they fixing different things?

Hi, you are correct there were two PRs fixing this, since @NhatNguyen1810 has made more progress I have closed my PR since it had much more work to be done before being merged.
