### ISSUE TITLE
LLVM fails to remove bounds check if value is guaranteed to be less than value smaller than length.

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [llvm/llvm-project#62441]
I tried this code:

```c++
#include <cstdint>
#include <vector>

int get_idx_half(
    const std::size_t idx,
    const std::vector<int>& __restrict__ nums
) {
    if (idx >= nums.size() / 2){
        return 0;
    }
    // Bounds check here is not optimized.
    return nums.at(idx);
}

int get_idx_full(
    const std::size_t idx,
    const std::vector<int>& __restrict__ nums
) {
    if (idx >= nums.size()){
        return 0;
    }
    // Bounds check here is eliminated.
    return nums.at(idx);
}
```
This code generates this machine code:

```asm
get_idx_half(unsigned long, std::vector<int, std::allocator<int> > const&):   # @get_idx_half(unsigned long, std::vector<int, std::allocator<int> > const&)
        push    rax
        mov     rcx, rdi
        mov     rdi, qword ptr [rsi]
        mov     rdx, qword ptr [rsi + 8]
        sub     rdx, rdi
        sar     rdx, 2
        mov     rsi, rdx
        shr     rsi
        xor     eax, eax
        cmp     rsi, rcx
        jbe     .LBB0_3
        cmp     rdx, rcx
        jbe     .LBB0_4
        mov     eax, dword ptr [rdi + 4*rcx]
.LBB0_3:
        pop     rcx
        ret
.LBB0_4:
        lea     rdi, [rip + .L.str]
        mov     rsi, rcx
        xor     eax, eax
        call    std::__throw_out_of_range_fmt(char const*, ...)@PLT
get_idx_full(unsigned long, std::vector<int, std::allocator<int> > const&):   # @get_idx_full(unsigned long, std::vector<int, std::allocator<int> > const&)
        mov     rcx, qword ptr [rsi]
        mov     rdx, qword ptr [rsi + 8]
        sub     rdx, rcx
        sar     rdx, 2
        xor     eax, eax
        cmp     rdx, rdi
        jbe     .LBB1_2
        mov     eax, dword ptr [rcx + 4*rdi]
.LBB1_2:
        ret
.L.str:
        .asciz  "vector::_M_range_check: __n (which is %zu) >= this->size() (which is %zu)"
```

In the second function, bounds check at `nums.at(idx)` is eliminated. However, it is not eliminated in first function despite the fact that `idx` is limited to half of length which is guaranteed to be in valid range for indices of vector.

[godbolt link](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:39,endLineNumber:22,positionColumn:39,positionLineNumber:22,selectionStartColumn:39,selectionStartLineNumber:22,startColumn:39,startLineNumber:22),source:'%23include+%3Ccstdint%3E%0A%23include+%3Cvector%3E%0A%0Aint+get_idx_half(%0A++++const+std::size_t+idx,%0A++++const+std::vector%3Cint%3E%26+__restrict__+nums%0A)+%7B%0A++++if+(idx+%3E%3D+nums.size()+/+2)%7B%0A++++++++return+0%3B%0A++++%7D%0A++++//+Bounds+check+here+is+not+optimized.%0A++++return+nums.at(idx)%3B%0A%7D%0A%0Aint+get_idx_full(%0A++++const+std::size_t+idx,%0A++++const+std::vector%3Cint%3E%26+__restrict__+nums%0A)+%7B%0A++++if+(idx+%3E%3D+nums.size())%7B%0A++++++++return+0%3B%0A++++%7D%0A++++//+Bounds+check+here+is+eliminated.%0A++++return+nums.at(idx)%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:49.40438871473354,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang1600,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-O3+-std%3Dc%2B%2B20',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+clang+16.0.0+(Editor+%231)',t:'0')),k:50.595611285266465,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

**Comment by floatshadow** [comment]
I think it is similar to https://github.com/llvm/llvm-project/issues/61393 @nikic.
When the pass pipeline reaches `isImpliedCondICmps` (in simplifyICmpInst), the full case will find LHS and RHS shared the operands and do the fold, but the half case will not.

I'm not sure whether it is the problem, but it looks like we cannot some transform on icmp before simplify

**Comment by caojoshua** [comment]
Submitted fix for review https://reviews.llvm.org/D151541

**Comment by caojoshua** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/cb9f1aaddac0ce6bf9386309e33e104ba3f9359c. See https://godbolt.org/z/jaocbn83K.

Note that the patch only can eliminate the bounds check when dividing by a power of 2. If dividing by 3 or some unknown, we still can't remove the bounds checks. See the same godbolt link above for an example. I'll create a separate patch for that.
