### ISSUE TITLE
clang-cl -march=armv8-a doesn't generate a dmb for InterlockedExchangeAdd

### ISSUE THREAD

**Issue by mcfi** [llvm/llvm-project#62445]
Compile the following code using `clang-cl /O2 -march=armv8-a /FA`
```c
#include <windows.h>
#include <intrin.h>

void foo(void)
{
    volatile LONG i = 0;
    InterlockedExchangeAdd(&i, 1);
}
```
the following code will be generated:
```asm
foo:                                    // @foo
.seh_proc foo
// %bb.0:
    sub sp, sp, #32
    str x30, [sp, #16]                  // 8-byte Folded Spill
    adrp    x9, __security_cookie
    add x8, sp, #4
    ldr x9, [x9, :lo12:__security_cookie]
    str x9, [sp, #8]
    str wzr, [sp, #4]
.LBB0_1:                                // =>This Inner Loop Header: Depth=1
    ldaxr   w9, [x8]
    add w9, w9, #1
    stlxr   w10, w9, [x8]
    cbnz    w10, .LBB0_1
```
Note that no `dmb` instruction was added behind the `cbnz` instruction. For comparison, please see MSVC code gen on [CompilerExplorer](https://godbolt.org/z/xbqervP6M). Also, the documented behavior of [InterlockedExchangeAdd](https://learn.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-interlockedexchangeadd) clearly states that:
> This function generates a full memory barrier (or fence) to ensure that memory operations are completed in order.

There are also other Interlocked* APIs without Acquire/Release/_nf suffices. All of them by default should generate a full fence.

**Comment by efriedma-quic** [comment]
This should work correctly in clang 16 or later.  (c9821abfc023fba684c8ef8589c49cba8083f579)
