### ISSUE TITLE
llvm 16 version still not pushed to AUR?

### ISSUE THREAD

**Issue by d2rgaming-9000** [llvm/llvm-project#62457]
As the title says, when I update and install 'pacman -Syyu llvm', I get an older version of '15.0...', despite having my package manager up to date, and version 16 may still not be pushed to AUR.

Also check the official ARCH packages here:

https://archlinux.org/packages/extra/x86_64/llvm/

I wish it would be pushed in the repo and updated. o/

**Comment by asl** [comment]
@d2rgaming-9000 I would suggest you to report issue to archlinux as LLVM project does not build / provide these packages. The link you provided contains the name of the maintainer @foutrelis

**Comment by thesamesam** [comment]
Not something we can act on, unfortunately.
