### ISSUE TITLE
Kernel 6.3 won't boot compiled with CC="clang" KCFLAGS="-march=bdver4"

### ISSUE THREAD

**Issue by goverp** [llvm/llvm-project#62464]
This may be too far over the bleeding edge!  I've been compiling the Linux kernel with Clang and `KCFLAGS="-march=bdver4"` and `LTO=thin` since the kernel started included LTO as a config setting, using the standard sources from kernel.org or Git.  That said, as far as the kernel people are concerned, this is unsupported.  I'm happy if you say "not supported here either", but I'm reporting it in case it's of interest.  The simple bypass of removing the `KCFLAGS` override cures the problem - the resulting kernel boots (from GRUB2, on a UEFI system), and my Gentoo system comes up as normal.

It was working OK up to kernel 6.2.11, but on 6.3, it boots to a blank screen, dead keyboard, no flashing lights, no logs, no terminal output, and as far as I can tell no dumps.  The bypass above proves it is not a framebuffer issue.

I'm cross-compiling from a desktop (Zen3 cpu) using Clang v15.0.7, for an AMD A9-9420 Radeon R5 in my laptop.  The kernel config says "Processor family (Opteron/Athlon64/Hammer/K8)", and has no experimental patches or expert settings.  It's not using the EFI stub.

FWIW, I compile kernel 6.3 for the above desktop, using `KCFLAGS="-march=native"`, and that boots and runs fine.

**Comment by RKSimon** [comment]
That isn't much to go on :| Can you try some alternative archs that /should/ work on a bdver4 (e.g. bdver1/2/3, I think even znver1 could work).

**Comment by goverp** [comment]
On Thursday, 28 September 2023 17:33:18 BST Simon Pilgrim wrote:
> That isn't much to go on :| Can you try some alternative archs that /should/
> work on a bdver4 (e.g. bdver1/2/3, I think even znver1 could work).

My bad, my script specified "-mtune=bdver4", where it should have been
"-march=bdver4".  I'm amazed I got away with it for so long!

Sorry to have bothered you.
