### ISSUE TITLE
DeclPrinter: Missing semicolon in output of defaulted/deleted methods

### ISSUE THREAD

**Issue by strimo378** [llvm/llvm-project#62473]
The following code

```c
struct Foo {
	Foo() = delete;
	~Foo() = default;

    void x() __attribute__((alias("X")));
};
```

is printed as

```c
struct Foo {
  Foo() = delete
  ~Foo() = default
  void x() __attribute__((alias("X")))
};
```

using `clang -Xclang -ast-print ...` see https://godbolt.org/z/Y45YdneMe

In `DeclPrinter::VisitDeclContext` the terminator of a `FunctionDecl` is decided by

```cpp
    else if (auto FD = dyn_cast<FunctionDecl>(*D)) {
      if (FD->isThisDeclarationADefinition())
        Terminator = nullptr;
      else
        Terminator = ";";
```

The code is wrong for `FunctionDecl` that are a definition without having a body as written.

I suggest to change it to

```cpp
    else if (auto FD = dyn_cast<FunctionDecl>(*D)) {
      if (FD->doesThisDeclarationHaveABody() && !FD->isDefaulted())
        Terminator = nullptr;
      else
        Terminator = ";";
```

`FD->isDefaulted()` is necessary because explicitly defaulted methods have a body inside the AST.

**Comment by infdahai** [comment]
Let's try this.

**Comment by wusatosi** [comment]
Hi, I am interested in taking this issue, how do I assign it to myself?

**Comment by BabaYaga1221** [comment]
Hi, I am interested in issue, assign to me. @nikic

**Comment by wusatosi** [comment]
> Hi, I am interested in issue, assign to me. @nikic

Hi, I am currently working on the issue and I think I am almost ready. To avoid duplicate work, it maybe best for us to find another issue for you :) . I will let you know when I submit the patch and maybe we can look over it together!

**Comment by BabaYaga1221** [comment]
Sure... If find any other issues, let me know. @wusatosi

**Comment by strimo378** [comment]
I am also interested in looking at the patch.

**Comment by strimo378** [comment]
https://reviews.llvm.org/D156533
