### ISSUE TITLE
operator<=> not defined for __wrap_iter

### ISSUE THREAD

**Issue by ojrosten** [llvm/llvm-project#62486]
While it is possible to use three way comparison for iterators coming from e.g. std::array, this does not work for e.g. std::vector. 

The culprit appears to be that oeprator<=> is not defined for the iterator wrapper used in the latter.

https://godbolt.org/z/fMdYvvz5Y

**Comment by long5hot** [comment]
Can work on this issue?

**Comment by mordante** [comment]
@Long5hot are you still working on a patch for this issue?

**Comment by Long5hot** [comment]
had to move on other things, so could not able to focus on this issue..

**Comment by mordante** [comment]
> had to move on other things, so could not able to focus on this issue..

No problem, thanks for the feedback.
