### ISSUE TITLE
Documentation flaws in Builtin Dialect of MLIR

### ISSUE THREAD

**Issue by Stevengre** [llvm/llvm-project#62489]
# The flaws in https://mlir.llvm.org/docs/Dialects/Builtin/

## 1. bool-literal
is not defined

## 2. FusedLoc
Example misses a "]"

## 3.  fused-location
The correct definition may like:
```BNF
fused-location ::= `fused` fusion-metadata? `[` location (`,` location)* `]`
```

## 4. builtin.module
The correct definition may like:
```BNF
operation ::= `module` (string-attribute)?  (`attributes` dictionary-attribute)? {operation*}
```
ps: there is no explanation of "builtin.module" and "module"

## 5. builtin.unrealized_conversion_cast
The correct definition may like:
```BNF
operation ::= `unrealized_conversion_cast` (value-id-list `:` type-list-no-parens)? `to` type-list-no-parens (dictionary-attribute)?
```

## 6. FunctionType
The correct definition may like:
```BNF
function-result-type ::= type-list-parens | non-function-type
function-type ::= type-list-parens `->` function-result-type
```
Furthermore, there is no definition of "non-function-type"

## 7. MemRefType
The correct definition may like:
```BNF
memref-type ::= `memref` `<` ((dimension `x`)+|`*`)? type
                (`,` layout-specification)? (`,` memory-space)? `>`
layout-specification ::= attribute-value
memory-space ::= attribute-value
```

## 8. NoneType
does not have a syntax.

## 9. attr-data
no definition, the  correct definition may like?
```BNF
attr-data ::= string-literal
```

## 10. resource-handle
no definition, the  correct definition may like?
```BNF
resource-handle ::= value-use
```

## 11. shaped-type
no definition, the  correct definition may like?
```BNF
shaped-type ::= tensor-type | vector-type
```

## 12. shaped-type
no definition, the  correct definition may like?
```BNF
shaped-type ::= tensor-type | vector-type
```

## 13. integer-set
no definition, the correct definition may in the Affine Dialect?

## 14. affine-map
no definition, the correct definition may in the Affine Dialect?

## 15. OpaqueLoc
no definition, meaning that the syntax is non-deterministic?

## 16. The information in Builtin Dialect is not sufficient to figure out the core/meta dialects of the MLIR, like Affine?
Is a dialect relationship diagram necessary?

**Comment by Stevengre** [comment]
Where can I find the sub-file in the Builtin.md, like [include "Dialects/BuiltinAttributes.md"]?

**Comment by joker-eph** [comment]
I think it'll be generated out of `mlir/include/mlir/IR/BuiltinAttributes.td`

**Comment by Stevengre** [comment]
Thank you for letting me know. It may be difficult for me to optimize the generator.

**Comment by joker-eph** [comment]
I'm not sure what you mean, the content to modify is in the `.td` file isn't it?

**Comment by Stevengre** [comment]
I'm sorry for the confusion. Because I think the problem I've listed here may be caused by a problem with the generator that generates md from td.

**Comment by Stevengre** [comment]
Sorry, do I just need to modify the description?

**Comment by joker-eph** [comment]
Yes.

The .td file is used to generate both the C++ code (the MLIR implementation) but also the documentation, by using the summary and description fields as-is and extracting other pieces of information that are used to generate the C++.
