### ISSUE TITLE
clang targeting C99 pedantic brace initialization on POD

### ISSUE THREAD

**Issue by mu578** [llvm/llvm-project#62496]
I have noticed I am allowed to write such initialization "int x = {0};" (works for any POD types) is that legal? I didn't find any obvious references covering that case in ISO/IEC 9899:1999 only unions and structs are covered ; so is that a "clang feature" to allow it?

**Comment by shafik** [comment]
I believe that would be covered by [6.7.8 Initialization p11](https://port70.net/~nsz/c/c99/n1256.html#6.7.8p11) which says:

> The initializer for a scalar shall be a single expression, `optionally enclosed in braces.`  ...

CC @AaronBallman

**Comment by AaronBallman** [comment]
> I believe that would be covered by [6.7.8 Initialization p11](https://port70.net/~nsz/c/c99/n1256.html#6.7.8p11) which says:
> 
> > The initializer for a scalar shall be a single expression, `optionally enclosed in braces.`  ...
> 
> CC @AaronBallman

Correct, this is valid C99 per what's cited here. I was curious about C89, but the same wording exists there as well.

(I think we can now close this issue, unless there are other concerns?)

**Comment by mu578** [comment]
To sum up:
- per revision it is legal and well stated.
- is that portable? I'll keep an open optimistic view.

**Comment by AaronBallman** [comment]
> To sum up:
> 
> * per revision and missed ; it is legal and well stated.
> * is that portable? I'll keep an open optimistic view.

It should be quite portable: https://godbolt.org/z/7ErMPx4eP (ICC isn't green because it emits a deprecation warning for the compiler, cc65 seems to want to warn on the construct but still accepts it).

> @AaronBallman this is indeed very helpful to me ; first time in decades, I encountered that case in plain C, you learn everyday, where I needed to initialize a tmp accum variable according to a "dynamic type" within a macro staying away from an unportable typeof usage.

FWIW, `typeof` was standardized in C23, so that won't be non-portable for long!

**Comment by mu578** [comment]
//MY life no care begin

`was standardized in C23, so that won't be non-portable for long!` don't let me started on that one ; it is been years of arguments with `hippie camp` ; to know I despise `typeof_unequal` it made me go over the top it was even `sanctified`, I don't understand why they are not consistent in using _Keywords like introduced in c11.

// MY life no care end
