### ISSUE TITLE
Missed optimization for C ? BSWAP(X) : 0

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#62514]
```c
unsigned select_bswap(bool c, unsigned x)
{
  return c ? __builtin_bswap32(x) : 0;
  // but this form is optimized:
  // return x ? __builtin_bswap32(x) : 0;
} // cttz, ctlz, ...
```

Current `-O3`:
```asm
select_bswap(unsigned int, unsigned int):                     # @select_bswap(unsigned int, unsigned int)
        mov     eax, esi
        test    edi, edi
        bswap   eax
        cmove   eax, edi
        ret
```

We can fully drop extra `select` / `cmove` as `bswap` of 0 is 0, so:

```asm
select_bswap(unsigned int, unsigned int):
        mov     eax, esi
        bswap   eax
        ret
```

https://godbolt.org/z/8MbaqefW3

**Comment by nikic** [comment]
This seems obviously incorrect: https://alive2.llvm.org/ce/z/AWMLZQ Maybe I'm misunderstanding what you're suggesting here. Can you please provide a working alive2 proof?

**Comment by davidbolvansky** [comment]
Right, indeed, and in this case gcc has a bug, as it emits:

select_bswap(bool, unsigned int):
        mov     eax, esi
        bswap   eax
        ret

**Comment by pinskia** [comment]
Just FYI, the GCC bug report on this is https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109702 which was noticed a day before this LLVM bug report was filed.
