### ISSUE TITLE
[clang] Invalid 32bit pointer (-fms-extensions __ptr32 __uptr) on non-Windows platforms

### ISSUE THREAD

**Issue by d-mozulyov** [llvm/llvm-project#62538]
### Problem
32-bit pointer does not work correctly on non-Windows platforms. See the [Godbolt listing](https://godbolt.org/z/PfncW85xG).

![screen_small](https://user-images.githubusercontent.com/10961593/236072539-ebcddc5f-a026-4c22-82ef-416b076a379e.png)

### Sample
```cpp
int param_std(int* foo) {
    int temp = *foo;
    *foo = 1;
    return temp;
}

int param_ptr32(int* __ptr32 __uptr bar) {
    int temp = *bar;
    *bar = 2;
    return temp;
}

int emulate_ptr32(unsigned baz) {
    unsigned long long baz64 = baz;
    int* bazptr = (int*)baz64;
    int temp = *bazptr;
    *bazptr = 3;
    return temp;
}

struct Qux {
    int* __ptr32 __uptr value;
};

int struct_ptr32(Qux& qux) {
    int temp = *qux.value;
    *qux.value = 4;
    return temp;
}
```
### Conclusions
The `param_ptr32` disassembler must be equal to `emulate_ptr32`, like `struct_ptr32`, and different from `param_std`. Based on the [Godbolt listing](https://godbolt.org/z/PfncW85xG), the MSVC and Clang for Windows target (x86_64-windows-gnu) compilers do just that. But on non-Windows platforms, Clang may not do the important conversion from a 32-bit pointer to a 64-bit one. I have localized this behavior in two cases. First, if the pointer appears as a function argument (`param_ptr32`). Second, if it is a member of a small structure that is passed as an argument (change `Qux& qux` to `Qux qux`).

**Comment by EugeneZelenko** [comment]
@d-mozulyov: Please elaborate.

**Comment by d-mozulyov** [comment]
@EugeneZelenko 

It looks like a 32 bit pointer to POSIX x64 works. The difference is in the ABI - on POSIX x64 the 32-bit pointer-argument is already unpacked.

https://godbolt.org/z/WvosqdW96

![image](https://github.com/llvm/llvm-project/assets/10961593/112a39fb-b339-42e0-b2d5-1c39e51589bc)

**Comment by d-mozulyov** [comment]
@EugeneZelenko 

But on ARM 64 still not working: https://github.com/llvm/llvm-project/issues/62536
