### ISSUE TITLE
[clang-tidy] SystemHeaders cannot be specified in config file on global level

### ISSUE THREAD

**Issue by PiotrZSL** [llvm/llvm-project#62547]
Problem:
```
SystemHeaders: true
^~~~~~~~~~~~~
Error: invalid configuration specified.
Invalid argument

```

This is because SystemHeaders is not listed in `MappingTraits<ClangTidyOptions>`.
Misleading documentation entry were introduced by this change: https://reviews.llvm.org/D141144

Option A)
- Implement support for SystemHeaders (may change some behavior for some checks that use getOptionForFile)
- Most probably wouldn't do any visible harm
Option B)
- Remove entry from documentation.

Issue found by "Beafantles" on discord.

**Comment by carlosgalvezp** [comment]
Thanks for reporting, I will have a look!

**Comment by carlosgalvezp** [comment]
Fix here: https://reviews.llvm.org/D149899

**Comment by carlosgalvezp** [comment]
Closed via https://github.com/llvm/llvm-project/commit/26f476286fbcb5cde51176abb2d3c6c0986bc410
