### ISSUE TITLE
Backport d30b187f7d44f06eccb77394019ba1b942bd9132 into 16.x

### ISSUE THREAD

**Issue by wusatosi** [llvm/llvm-project#62557]
For GitHub Actions, `set-output` is going to be deprecated at [end of may](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
d30b187f7d44f06eccb77394019ba1b942bd9132 fixes use of `set-output` in `libclang ABI Tests`, but it did not got included in release/16.x branch.
Consider it may break actions on the [still active branch](https://github.com/llvm/llvm-project/actions/runs/4864199300) soon, can we backport d30b187f7d44f06eccb77394019ba1b942bd9132 into 16.x?

**Comment by boomanaiden154** [comment]
Closing as not planned given 16.x is not supported currently.
