### ISSUE TITLE
[clang-format] Break options for all types of lists

### ISSUE THREAD

**Issue by Stadly** [llvm/llvm-project#62566]
Breaking lists before comma gives (in my opinion) a very readable and maintainable syntax. Clang-Format currently supports this for inheritance lists and member initializer lists:

```c++
// Inheritance list
class MyClass
: Foo
, SomeOtherClass
, Bar
{
  int m_Id;
  bool m_Condition;
};

// Member initializer list
MyClass::MyClass()
: Foo{3}
, SomeOtherClass{4, true}
, Bar{}
, m_Id{0}
, m_Condition{false}
{};
```

Clang-Format currently does not have break options for parameter lists, argument lists, enumerator lists, or initializer lists.

We have a large code base (≈ 1.9 million lines) that breaks lists before comma instead of after comma. This is the major issue preventing us from adopting Clang-Format.

Is this something you would consider supporting? If approved, I would be glad to help out implementing it. I've done some investigation, and it seems that we would just need a couple of new style options:

- `BreakParameters`
- `BreakArguments`
- `BreakEnums`
- `BreakInitializationList`

They would all behave similarly to [`BreakInheritanceList`](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#breakinheritancelist) and [`BreakConstructorInitializers`](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#breakconstructorinitializers). I don't think that they would conflict with any existing style options.

Here is an example of formatting that would be supported with the new style options:

```c++
// Parameter list
void MyFunc
( int a_par
, double something_more
, int input_par
, bool foo
);

// Argument list
MyFunc
( a_par
, something_more
, input_par
, foo
);

// Enumerator list
enum class MyEnum
{ FirstItem
, SomeOtherItem
, Thing
, Baz
};

// Initializer list
std::vector<int> MyVector
{ 1
, 1000
, 300000
, -2
, 12345678
, 9999
};

```

**Comment by owenca** [comment]
Please see https://clang.llvm.org/docs/ClangFormatStyleOptions.html#adding-additional-style-options.

**Comment by Stadly** [comment]
Thanks. We are around 60 developers, but not all are working on our C++ code base, so we currently have less than "dozens of contributors" on the project in question. The other two conditions we can satisfy. Does that mean such a patch would be rejected?

I envision full consistency when styling lists. So that not only breaking, but also alignment, indentation, and packing can be set consistently for all types of lists. This would simplify both the code base, documentation and configuration, making Clang-Format both more flexible and easier to maintain.

My thinking is to create nested configuration flags for each list type. An example for member initializer lists (could also be called constructor initializer lists if we want to):
```
MemberInitializerList:
  Align: boolean
  Break: BeforeColon/BeforeComma/AfterColon/AfterComma
  IndentWidth: unsigned
  Pack: Never/BinPack/CurrentLine/NextLine/NextLineOnly
```

- `Align` provides alignment similar to `AlignAfterOpenBracket: Align` for functions.
- `Break` replaces `BreakConstructorInitializers`
- `IndentWidth` replaces `ConstructorInitializerIndentWidth`
- `Pack` replaces `PackConstructorInitializers`, with the additional option `AfterComma`

We would have similar nested configuration flags for the other lists types. For example parameter lists:
```
ParameterList:
  Align: boolean
  Break: BeforeParens/BeforeComma/AfterParens/AfterComma
  IndentWidth: unsigned
  Pack: Never/BinPack/CurrentLine/NextLine/NextLineOnly
```

- `Align` and `Break` together replaces `AlignAfterOpenBracket`, but provides greater flexibility
- `Pack: BinPack` replaces `BinPackParameters`
- `Pack: NextLine` replaces `AllowAllParametersOfDeclarationOnNextLine`

Such a change would lead to improvements in all areas:
- Documentation and configuration:
  - Get rid of inconsistencies like
    - `ConstructorInitializerIndentWidth` also applies to inheritance lists
    - `BinPackParameters: true` for parameter lists, but `PackConstructorInitializers: BinPack` for member initializer lists
    - `BreakInheritanceList` has option `AfterComma`, while `BreakConstructorInitializers` doesn't
    - `OfDeclaration` is part of the name `AllowAllParametersOfDeclarationOnNextLine` but not `BinPackParameters`
  - No more searching around for the style options applicable for a list type; all the options are grouped as nested configurations
  - No more wondering which style options are supported for a list type; they all support the same set of options (with tiny variations like `BeforeColon` vs `BeforeParens`)
- Implementation
  - The implementation can be generic and not need separate handling for each list type. By looking at the context it is in, the appropriate set of style options can be loaded, and then the algorithm can be agnostic to which type of list it is working on.
- Maintenance and future enhancements
  - Adding a new feature to one of the list types would add it to all list types
  - Fixing a bug in one of the list types would fix it for all list types

The change would deprecate the following style options:
- `AlignAfterOpenBracket`
- `AllowAllArgumentsOnNextLine`
- `AllowAllParametersOfDeclarationOnNextLine`
- `AllowShortEnumsOnASingleLine`
- `BinPackArguments`
- `BinPackParameters`
- `BracedInitializerIndentWidth`
- `BreakConstructorInitializers`
- `BreakInheritanceList`
- `ConstructorInitializerIndentWidth`
- `PackConstructorInitializers`

It might also be possible to deprecate these options:
- `BreakArrays`
- `ObjCBinPackProtocolList`

We might have to update `ExperimentalAutoDetectBinPacking` to work with the new style options.

What do you think?

**Comment by Stadly** [comment]
This would also cover #62549.

**Comment by Stadly** [comment]
Closing this, in favor of #62676.
