### ISSUE TITLE
Another miscompilation in LoopStrengthReduce

### ISSUE THREAD

**Issue by d-makogon** [llvm/llvm-project#62563]
Repro: https://godbolt.org/z/ddYvP4jv7

After LSR `@foo` is called with incorrect argument value.
In the initial function loop `bb3` takes backedge 37 times.
After the loop the values that are used to compute the `foo` argument are the following:
```ll
%phi = 10
%phi4 = 0 + 37 * 4 = 148
%add = 10 - 3 = 7
%trunc = %add = 7
%call = umax %trunc, 10 = 10
%add5 = 10 - 4 = 6
%add6 = 148 + 4 = 152
%icmp = 6 u< 7 = true

%add8 = %add6 + %call = 162
```
So the `foo` argument value is 162.
In the code after LSR `foo` is called with argument equal to `159`:
```ll
%tmp1 = trunc i64 159 to i32
call void @foo(i32 %tmp1)
```
Alive2 was unable to prove incorrectness of transformations.

**Comment by d-makogon** [comment]
Fix on review - https://reviews.llvm.org/D151796.
The cause of miscompilation is described on a reduced test is described there also.

**Comment by nikic** [comment]
This has been fixed by various patches to check SCEV normalization round-trip.
