### ISSUE TITLE
Please backport d9683a70fef4 into 16.0.X

### ISSUE THREAD

**Issue by frasercrmck** [llvm/llvm-project#62564]
This is admittedly preemptive but given our downstream makes heavy use of RISC-V vector code, I think cherry-picking d9683a70fef would be prudent given it's fixing a known codegen issue.

The code it's fixing made it into LLVM 16 as db3f3243bb85253eaf0e483452fdbfd5baf7ffd1.

CC @asb, @topperc @bubba

**Comment by asb** [comment]
/cherry-pick d9683a70fef48cfaee2c83147a3b26f4f90162a2

Let's see if it cherry-picks. Thanks!

**Comment by frasercrmck** [comment]
Ach, sorry about that - it looks like we'll have to regenerate the checks. I'll see if I've time next week.

**Comment by bubba** [comment]
This patch was false alarm and was causing regressions, the original code was correct. Shouldn't need to backport it.
