### ISSUE TITLE
Clang accepts invalid program involving decltype(classtype::memberfunction) when used with concepts

### ISSUE THREAD

**Issue by ranaanoop** [llvm/llvm-project#62585]
The following invalid program is accepted by Clang trunk. https://godbolt.org/z/Ma67TTs5e

```cpp
#include <iostream>
#include <type_traits> 
#include <concepts>
template < typename T >
concept test = std::same_as <decltype(T::func), int(int) >;
struct D
{
    int func(int);
};
int main()
{ 
    std::cout << test<D>;      
}
```
Note `decltype` on a non-static member function is not allowed and so it should be ill-formed.

**Comment by shafik** [comment]
I believe this is ill-formed no diagnostic required, while this failed b/c it is ill-formed there are no values that can satisfy the concept, I believe. 

CC @erichkeane 

It is helpful with these type of bug reports to cite a reference to why you believe this should be ill-formed. Either a stackoverflow post, a bug report or something else.

**Comment by ranaanoop** [comment]
@shafik Also, the following is rejected by clang and gcc but accepted by msvc: https://godbolt.org/z/W6d5EnvWf

```
#include <iostream>
#include <type_traits> 
#include <concepts>
struct A{
    static constexpr int value = 0;
};
template < typename T >
concept test = std::same_as <T::value, int(int) >;  
struct D
{
    int func(int);
};
int main()
{ 
    std::cout << test<D>;   //clang rejects this but msvc accepts it
} 
```

**Comment by ranaanoop** [comment]
> I believe this is ill-formed no diagnostic required, while this failed b/c it is ill-formed there are no values that can satisfy the concept, I believe.

I think that the `constraint-expression` on the rhs of a concept be a valid c++ expression. Which in both of the cases above is not. So ill-formed(but a diagnostic should be generated).

**Comment by cpplearner** [comment]
[[temp.constr.atomic]](https://eel.is/c++draft/temp.constr.atomic#3):
> To determine if an atomic constraint is satisfied, the parameter mapping and template arguments are first substituted into its expression. If substitution results in an invalid type or expression, the constraint is not satisfied.

This seems to mean that an invalid type or expression does not make the program ill-formed, but only makes the constraint expression evaluate to `false`.

**Comment by ranaanoop** [comment]
@cpplearner Looks like **ill-formed no diagnostic required** as per [temp.constr.normal#1.4].

> The normal form of a concept-id C<A1, A2, ..., An> is the normal form of the constraint-expression
of C, after substituting A1, A2, ..., An for C’s respective template parameters in the parameter
mappings in each atomic constraint. **If any such substitution results in an invalid type or expression,
the program is ill-formed; no diagnostic is required**.

**Comment by ranaanoop** [comment]
@shafik Upon reading more on this, seems this is well-formed as explained in this [post](https://stackoverflow.com/a/76192179).

**Comment by shafik** [comment]
> If no satisfaction check can succeed, then [[temp.res.general]/(6.2)](https://eel.is/c++draft/temp.res.general#6.2) applies. But IIUC `decltype(T::func)` could be a valid type if `T::func` is a static member function.

Ah yes, I missed this case. So yes, this means it is well-formed.
