### ISSUE TITLE
What means “custom object file section” in LLVM？

### ISSUE THREAD

**Issue by Shawdox** [llvm/llvm-project#62580]
Hi, I'm a beginner in LLVM and recently I feel confusing about a function llvm::GlobalObject->hasSection().
The LLVM document [Check](https://llvm.org/doxygen/namespacellvm_1_1Check.html) says :"if this global has a custom object file section." I want to know what is a "custom object file section" in LLVM?
Respect.

**Comment by efriedma-quic** [comment]
This sort of question is usually better asked on Discourse (https://discourse.llvm.org)

Explicit sections are described at https://llvm.org/docs/LangRef.html#global-variables
