### ISSUE TITLE
static lambda call operator is not convertible to function pointer on win32

### ISSUE THREAD

**Issue by faisalv** [llvm/llvm-project#62594]
This code does not work with clang compiled with msvc.
```cpp  
  auto lstatic = []()  static  { return 0;  };
  int (*f2)(void) = lstatic; 
```
I am working on a quick patch to fix it (the wrong calling convention `CC_X86ThisCall` is getting assigned in spite of the `static`).

**Comment by AaronBallman** [comment]
It took me a moment to spot it, but this is a 32-bit only issue: https://godbolt.org/z/P5zddjE43

**Comment by faisalv** [comment]
https://reviews.llvm.org/D150075

**Comment by cor3ntin** [comment]
Fixed in Clang 18
