### ISSUE TITLE
[clang, trunk, c++11] Clang rejects NTTP defaulted value invoking static constexpr member function within class

### ISSUE THREAD

**Issue by CalebAdrianXYZ** [llvm/llvm-project#62596]
Given the following C++11 code: 
```cpp
// minimal reproducible example, oversimplified code
struct foo {
    static constexpr bool bar() {
        return true;
    }

    template<bool B = bar()> // <-- clang has issue with this
    static constexpr bool baz() {
        return true;
    }
};
static_assert(foo::baz(), "");
```

GCC, MSVC, ICC, and NVC++ all compile this code successfully, but Clang (trunk) produces the following diagnostic output:

```console
<source>:7:23: error: non-type template argument is not a constant expression
    template<bool B = bar()> // <-- clang has issue with this
                      ^~~~~
<source>:7:23: note: undefined function 'bar' cannot be used in a constant expression
<source>:3:27: note: declared here
    static constexpr bool bar() {
                          ^
<source>:12:15: error: no matching function for call to 'baz'
static_assert(foo::baz(), "");
              ^~~~~~~~
2 errors generated.
Compiler returned: 1
```

Corresponding CE link: https://godbolt.org/z/4Md1b5o8r

**Comment by shafik** [comment]
@cor3ntin is this https://github.com/llvm/llvm-project/issues/62462

**Comment by tbaederr** [comment]
In https://github.com/llvm/llvm-project/blob/231ef2104d15c306f0e362db649cf241ac575d09/clang/lib/AST/ExprConstant.cpp#L7802-L7808 both `Body` and `Definition` are `nullptr`, so the following `CheckConstexprFunction` diagnoses.

I don't know enough about the parsing here, are the bodies of static member functions only available later?

**Comment by cor3ntin** [comment]
> @cor3ntin is this #62462

Nope, but it might be https://github.com/llvm/llvm-project/issues/62224 
Ie, we may be able to evaluate the argument too soon,
That or we don't do late parsing of template default arguments, which certainly would be surprising

**Comment by Fznamznon** [comment]
That feels similar to https://github.com/llvm/llvm-project/issues/62224, although `bar()` is defined at the point we should be parsing `baz()`. Let me take a look.

**Comment by Fznamznon** [comment]
https://reviews.llvm.org/D150108 that I was originally intending for https://github.com/llvm/llvm-project/issues/62224 helps here as well.
