### ISSUE TITLE
Linux package for LLVM 17 fails with missing "libomp.so.5"

### ISSUE THREAD

**Issue by lerno** [llvm/llvm-project#62622]
Installing from https://apt.llvm.org/focal main, package `1:17~++20230505052917+8bd02e5aefa8-1~exp1~20230505173022.623` works as of 2023-05-06.
By 2023-05-07 and version `1:17~++20230507052936+70218f6f83fe-1~exp1~20230507173044.625` things are failing: 

```console
CMake Error at /usr/lib/llvm-17/lib/cmake/llvm/LLVMExports.cmake:1827 (message):
  The imported target "omp" references the file

     "/usr/lib/llvm-17/lib/libomp.so.5"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/llvm-17/lib/cmake/llvm/LLVMExports.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/llvm-17/cmake/LLVMConfig.cmake:366 (include)
-- Configuring incomplete, errors occurred!
  CMakeLists.txt:109 (find_package)
```

**Comment by shiltian** [comment]
I suspect my previous patch https://reviews.llvm.org/D149617 might cause the issue. How was that version built?

**Comment by lerno** [comment]
Are you asking me or someone else @shiltian

**Comment by shiltian** [comment]
I guess whoever built `1:17~++20230507052936+70218f6f83fe-1~exp1~20230507173044.625`.

**Comment by glennvl** [comment]
In get the exact same issue when trying to build include-what-you-use against clang 17 nightly.

**Comment by lerno** [comment]
Any updates to this? I thought I'd try it out today and I noted that the CMake file is still broken.

**Comment by shiltian** [comment]
I did try on my local machine but cannot reproduce it then I was diverted. I'll give it another shot tonight.

**Comment by sylvestre** [comment]
I have been able to reproduce it and I think i fixed it 
I still don't like my workaround but i don't know if there is a better solution.
https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/commit/ec5a6356858ed9398e549165f73acb4c3b15b6a2

@shiltian if you have a better way, don't hesitate
I restarted the jobs

**Comment by shiltian** [comment]
I still cannot reproduce the issue. I can find the correct `libomp.so` in `LLVMExports-release.cmake`:
```
# Import target "omp" for configuration "Release"
set_property(TARGET omp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(omp PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libomp.so"
  IMPORTED_SONAME_RELEASE "libomp.so"
  )
```
Not sure how the report has `libomp.so.5` and where the 5 is from.

**Comment by lerno** [comment]
@shiltian this is the relevant part of the CI running on github:

```
      - uses: actions/checkout@v3
      - name: Install common deps
        run: |
          sudo apt-get install zlib1g zlib1g-dev python3 ninja-build curl

      - name: Install Clang ${{matrix.llvm_version}}
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          if [[ "${{matrix.llvm_version}}" < 17 ]]; then
            sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-${{matrix.llvm_version}} main"
          else
            sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal main"
          fi
          sudo apt-get update
          sudo apt-get install -y clang-${{matrix.llvm_version}} llvm-${{matrix.llvm_version}} llvm-${{matrix.llvm_version}}-dev lld-${{matrix.llvm_version}} liblld-${{matrix.llvm_version}}-dev
          sudo apt-get install -y libmlir-${{matrix.llvm_version}} libmlir-${{matrix.llvm_version}}-dev mlir-${{matrix.llvm_version}}-tools 
          sudo apt-get install -y libpolly-${{matrix.llvm_version}}-dev
      - name: CMake
        run: |
          cmake -B build \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
                -DCMAKE_C_COMPILER=clang-${{matrix.llvm_version}} \
                -DCMAKE_CXX_COMPILER=clang++-${{matrix.llvm_version}} \
                -DCMAKE_LINKER=lld-link-${{matrix.llvm_version}} \
                -DCMAKE_OBJCOPY=llvm-objcopy-${{matrix.llvm_version}} \
                -DCMAKE_STRIP=llvm-strip-${{matrix.llvm_version}} \
                -DCMAKE_DLLTOOL=llvm-dlltool-${{matrix.llvm_version}} \
                -DC3_LLVM_VERSION=${{matrix.llvm_version}}
          cmake --build build
```
As this only happens on LLVM 17, it's from `deb http://apt.llvm.org/focal/ llvm-toolchain-focal main`

The project doesn't use OpenMP nor is the problem there, it fails when loading `LLVMExports.cmake` itself, as this one is assuming `libomp.so` is needed to compile *anything* related to LLVM. *IF* that was the case, then presumably installing llvm-17-dev and related should pull that dependency as well. I am *not* expecting `libomp.so.5` to be necessary to download unless I actually use it.

Note that this is a seemingly perpetual problem with the CMake script: it keeps happening that suddenly random dependencies on (for the actual compiled product) unused libraries appears. The workaround is always to add more and more dependencies just to keep the CMake script happy, rather than actually using them.
