### ISSUE TITLE
[Aarch64] Unoptimized code generation when vectorizing the loop containing `zext`(v16i8 -> v16i32) and `llvm.abs` instruction

### ISSUE THREAD

**Issue by quic-eikansh** [llvm/llvm-project#62620]
LLVM v16.0.0 generates unoptimized code for the given IR compared to LLVM v15.0.0 for AArch64 architecture. The regression starts after patch [D120571](https://reviews.llvm.org/D120571) .

In this [Godbolt link](https://godbolt.org/z/6MKzP7fjs) it can be seen that a `v16i8` is zero extended to `v16i32` using `zext`. The two zero extended `v16i32` vectors are then used with `sub` and the result is then fed to `llvm.abs`.

So, the pattern is:
1. Two zero extended vectors (`v16i8` -> `v16i32`).  
2. `sub` operation on the vectors.  
3. Taking `llvm.abs` of the result in step 2.  

With llc 15.0.0 it generates `uabdl` and `uabal2` instruction for the pattern which is optimal. But with llc 16.0.0 it generates bunch of `tbl` and `sabd` instructions which results in suboptimal assembly.

Similarly, we get optimal code without the patch [D120571](https://reviews.llvm.org/D120571) when in the step 2 of the above pattern `sub` is replaced by `add`, `mul` or `shl`.

### Reduced LLVM IR
```ll
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

define dso_local i32 @test(i8* %p1, i8* %p2, i32 %lx, i32 %h) {
entry:
  %cmp258 = icmp sgt i32 %h, 0
  br i1 %cmp258, label %for.body.lr.ph, label %for.end

for.body.lr.ph:                                   ; preds = %entry
  %idx.ext = sext i32 %lx to i64
  br label %for.body

for.body:                                         ; preds = %for.body.lr.ph, %for.body
  %s0 = phi i32 [ 0, %for.body.lr.ph ], [ %op.rdx, %for.body ]
  %j.0261 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %p1.addr.0260 = phi i8* [ %p1, %for.body.lr.ph ], [ %add.ptr, %for.body ]
  %p2.addr.0259 = phi i8* [ %p2, %for.body.lr.ph ], [ %add.ptr172, %for.body ]
  %0 = bitcast i8* %p1.addr.0260 to <16 x i8>*
  %1 = load <16 x i8>, <16 x i8>* %0
  %2 = zext <16 x i8> %1 to <16 x i32>
  %3 = bitcast i8* %p2.addr.0259 to <16 x i8>*
  %4 = load <16 x i8>, <16 x i8>* %3
  %5 = zext <16 x i8> %4 to <16 x i32>
  %6 = sub nsw <16 x i32> %2, %5
  %7 = tail call <16 x i32> @llvm.abs.v16i32(<16 x i32> %6, i1 true)
  %8 = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> %7)
  %op.rdx = add i32 %8, %s0
  %add.ptr = getelementptr inbounds i8, i8* %p1.addr.0260, i64 %idx.ext
  %add.ptr172 = getelementptr inbounds i8, i8* %p2.addr.0259, i64 %idx.ext
  %inc = add nuw nsw i32 %j.0261, 1
  %exitcond.not = icmp eq i32 %inc, %h
  br i1 %exitcond.not, label %for.end, label %for.body

for.end:                                          ; preds = %for.body, %entry
  %s1 = phi i32 [ 0, %entry ], [ %op.rdx, %for.body ]
  ret i32 %s1
}

declare <16 x i32> @llvm.abs.v16i32(<16 x i32>, i1 immarg) 

declare i32 @llvm.vector.reduce.add.v16i32(<16 x i32>) 
```

**Comment by v01dXYZ** [comment]
Try to use `llvm.abs.v16i8` directly instead of `zext 16xi8 to 16xi32`.

https://godbolt.org/z/Eehej76G9

**Comment by quic-eikansh** [comment]
@efriedma-quic

**Comment by fhahn** [comment]
Proposed patch: https://reviews.llvm.org/D150482

**Comment by v01dXYZ** [comment]
Hello,
As I wish to understand a little bit more the `AArch64` backend, I'll try to document all the aspects of this MR.

## Generic Instruction, AArch64 Instruction and Pattern Candidates

Let's first point out there is a generic instruction for absolute difference (unsigned or signed):  `ABDU`

* https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/CodeGen/ISDOpcodes.h
* https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/Target/TargetSelectionDAG.td

That means naturally there is a dag pattern for the match `machine-generic -> AArch64`:
https://github.com/llvm/llvm-project/blob/f2677afe91592673663d24a63706c3218c477c1c/llvm/lib/Target/AArch64/AArch64InstrInfo.td#L754-L755

There are other patterns (candidate A) 

https://github.com/llvm/llvm-project/blob/f2677afe91592673663d24a63706c3218c477c1c/llvm/lib/Target/AArch64/AArch64InstrInfo.td#L4584-L4614

But those patterns don't seem to fit as they output an 128b register from a 64b register. So we have to look at somewhere else.

There is a better candidate (candidate B):

https://github.com/llvm/llvm-project/blob/07028acacfd2b5dd6633814db690e5de8e37b40d/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp#L15543-L15558

Another pattern which is implemented at the generic DagCompiler (candidate C):

https://github.com/llvm/llvm-project/blob/9e932e08a8300f3366ace04ba8fda4946db406b9/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp#L10697-L10701

This rewriting rule essentially allows to elevate the zext after the absolute difference computation:

```
(abs (sub (zext $a) (zext $b))) -> (zext (abdu $a $b))
```

Thus if the zext is itself used by a truncate, it would be eligible for elimination.

In our case the candidate B is the dag combiner which is applied if we compile the provided example. 

Thus, we need to understand why this pattern is destroyed.

## `zext -> shuffle` destroying the pattern

If we debug the transforms, we can clearly see it is the `codegenprepare` that destroys the patterns, which is absolutely expected when looking at the patch responsible of the regression.

First, let's point out it only occurs if a loop is detected.
The smallest example that triggers the faulty behaviour:

``` llvm
target triple = "aarch64-unknown-linux-gnu"

define i32 @faulty(<16 x i8> %p0, <16 x i8> %p1) {
entry:
  br label %entry.0

entry.0: 
  %p0.extended = zext <16 x i8> %p0 to <16 x i32>
  %p1.extended = zext <16 x i8> %p1 to <16 x i32>

  %sub = sub <16 x i32> %p0.extended, %p1.extended
  %abs = call <16 x i32> @llvm.abs.v16i32(<16 x i32> %sub, i1 true)
  %red = call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> %abs)

  %b = add i1 1, 0

  br i1 %b, label %entry.0, label %end

end:
  ret i32 %red; <16 x i8> %abs.trunc; %abs.plus.one
}

declare <16 x i32> @llvm.abs.v16i32(<16 x i32>, i1 immarg) 
declare i32 @llvm.vector.reduce.add.v16i32(<16 x i32>) 
```

The solution of the patch is to add new checks to not perform the `zext -> shuffle` for the case of an extension `i8 -> i16` and `i8 -> i32`. I have to document the behaviour of `getInstrCastCost` and `isWideningInstruction`, as don't understand yet completely their purposes.

## (not really important) Remarks about the patch

* strange comparison (or maybe it's a trick on precedence)
  https://github.com/llvm/llvm-project/blob/db1d72b155c65df26980f6113cb5961c3c706a81/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp#L1897

* not used set variable
  https://github.com/llvm/llvm-project/blob/27a80fc946186257899bce5256951b4e35b7e8c3/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp#L14664
