### ISSUE TITLE
Clang fails to parse initializer list inside template arguments

### ISSUE THREAD

**Issue by ilya-biryukov** [llvm/llvm-project#62637]
```cpp
struct X {int a;};

template <X> int foo();
void test() {
    foo<{1}>(); // <- Clang errors with 'expected expression'
}
```
This is allowed by C++20 and supported by GCC and MSVC, see [godbolt](https://gcc.godbolt.org/z/5d93qnWjh).

**Comment by shafik** [comment]
I believe this is: https://github.com/llvm/llvm-project/issues/58434

Which comes down to [DR 2450](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2450)

Reflector discussion here: https://lists.isocpp.org/core/2019/01/5391.php

This is on the list of core issues to look at although it is a bit down the list right now, so we might not get to it before Varna. 

CC @zygoloid

**Comment by cor3ntin** [comment]
Agreed, we can close that as duplicate
