### ISSUE TITLE
[ARMv7]: Outline atomics emitted even when mno-outline-atomics specified

### ISSUE THREAD

**Issue by lukeg101** [llvm/llvm-project#62655]
Consider the following code (https://godbolt.org/z/hfszaG7e5):
```
// Test body
void P0 () {
  atomic_fetch_add_explicit(x,1,memory_order_seq_cst);
  int64_t r0 = atomic_load_explicit(y,memory_order_seq_cst);
  *P0_r0 = r0;
}

void P1 () {
  atomic_exchange_explicit(y,1,memory_order_seq_cst);
  int64_t r0 = atomic_load_explicit(x,memory_order_seq_cst);
  *P1_r0 = r0;
}
```
When compiled to target armv7 with `-O3 -pthread -std=c11 -mno-outline-atomics`, function calls are emitted for `atomic_load`/`fetch_add`,`exchange`

**Comment by Wilco1** [comment]
32-bit LLVM defaults to the ancient arm7tdmi which supports no atomics at all (hence the calls to a runtime library like libatomic). So you need -march=armv7-a as that is what 32-bit distros use as their minimum. Note outline atomics are only supported on AArch64.

**Comment by lukeg101** [comment]
Ah fair, that's good to document at least :)
