### ISSUE TITLE
LLVM 17 regression: bswap not vectorized

### ISSUE THREAD

**Issue by chfast** [llvm/llvm-project#62659]
The recent builds of LLVM/clang 17 stopped vectorizing `@llvm.bswap.i64` into `@llvm.bswap.v2i64` in builds for x86-64.

https://godbolt.org/z/e1cxshza7

**Comment by efriedma-quic** [comment]
This is a cost model issue; it vectorizes with -slp-threshold=-3.

**Comment by RKSimon** [comment]
This is down to atom/silvermont pshufb costs being so bad (and costs are based on worse case) - but we can add additional special cases to avoid this.

**Comment by chfast** [comment]
Any option to move this forward?

**Comment by chfast** [comment]
Thank you.
