### ISSUE TITLE
[mlir] [documentation] [bug] Redundant curly braces

### ISSUE THREAD

**Issue by Jerry-Ge** [llvm/llvm-project#62666]
On this page: https://mlir.llvm.org/docs/Traits/

Search the text `The following signature of fold will be called if it is implemented and the op has a single result.`

The two code blocks below each has 1 redundant curly braces.
<img width="887" alt="Screenshot 2023-05-11 at 1 21 44 PM" src="https://github.com/llvm/llvm-project/assets/24451859/38633b04-283a-467a-bdc3-9ed2c49d9b6d">

**Comment by Jerry-Ge** [comment]
cool, i will push a patch to fix this.

**Comment by joker-eph** [comment]
Thanks for fixing this!

> [Run the test suite](https://llvm.org/docs/TestingGuide.html#unit-and-regression-tests) locally.
> 3.1) Remember that the subdirectories under test/ create fine-grained testing targets, so you can
> e.g. use make check-clang-ast to only run Clang's AST tests.

Just to clarify: this step is irrelevant for the documentation fix.

**Comment by Jerry-Ge** [comment]
patch pushed: https://reviews.llvm.org/D150487
