### ISSUE TITLE
How to get started 

### ISSUE THREAD

**Issue by NhatNguyen1810** [llvm/llvm-project#62673]
Hi, I am new to this project. Can anyone give me instruction how to get started with the clang frontend (lexer, parser, grammar definition of C, ....) ? And how it is passed to llvm to process the backend. Any input is greatly apprecitaed. Thanks!

**Comment by asl** [comment]
Hello

Such sort of questions would be better suitable for LLVM Discourse: https://discourse.llvm.org/
