### ISSUE TITLE
[mlir] Use of MLIR Properties slows compilation

### ISSUE THREAD

**Issue by psteinfeld** [llvm/llvm-project#62687]
Starting with patch https://reviews.llvm.org/D148298, compilation times for some Fortran benchmarks slowed significantly.  Here's a small Fortran test case that illustrates the problem:
```f90
Program slow
  Integer, Parameter :: x(2,4,6,8,10,12) = &
    Reshape( [ (i,i=1,46080) ], [ 2,4,6,8,10,12 ] )
End Program
```
If I run the `bbc` tool on this program with the `-emit-fir` option, compilation stops after the initial creation of the FIR code.  If I run this command on a compiler produced with and without the patch listed above, I get almost identical results.  Here's the command line I used:
```shell
time bbc -emit-fir slow.f90
```

On the other hand, if I run the `bbc` tool without the `emit-fir` option, the bbc tool runs all of the optimization passes.  In this case, the execution time is almost twice as slow.  Here's the command line I used:
```shell
time bbc slow.f90
```

I also noted that the optimized and unoptimized MLIR produced is identical.

**Comment by joker-eph** [comment]
I've been trying to build flang on my MacBook, but clang is quite unhappy with it right now. So many files (like `flang/lib/Lower/ConvertExpr.cpp`) are taking > 5min to compile (this a M2 MacBook Pro!), is there a known issue here?

**Comment by joker-eph** [comment]
This is fixing it: https://reviews.llvm.org/D150540 (and making it slightly faster than before actually)

**Comment by psteinfeld** [comment]
> I've been trying to build flang on my MacBook, but clang is quite unhappy with it right now. So many files (like `flang/lib/Lower/ConvertExpr.cpp`) are taking > 5min to compile (this a M2 MacBook Pro!), is there a known issue here?

I have an M2 MacBook Pro with 64G of RAM.  I can build all of flang from scratch in a little over 17 minutes.
