### ISSUE TITLE
[VE] Implement isIntDivCheap hook if div by constant optimization from D150333 is not desired

### ISSUE THREAD

**Issue by topperc** [llvm/llvm-project#62682]
D150333 enabled div by constant for some scalar types. I'm not sure if this is desired for VE or not. It can be disabled by returning true from the `isIntDivCheap` hook.

CC @jam7 

I don't see a label for VE backend.

**Comment by kaz7** [comment]
Thank you mentionning that.  Is is also desired for VE too.
