### ISSUE TITLE
32 bit arm Mach-O targets are broken

### ISSUE THREAD

**Issue by OldWorldOrdr** [llvm/llvm-project#62691]
`<apple linker> -arch armv7 -platform_version ios 10.0 10.0 -syslibroot /path/to/sdk -o a.out -lSystem test.o`
this works with no issues.
doing the same but with `ld64.lld` as linker produces this error
```console
ld64.lld: error: VANILLA relocation must be extern at offset -1191182322 of __TEXT,__text in hello.o
ld64.lld: error: VANILLA relocation has width 1 bytes, but must be 0 bytes at offset -1191182322 of __TEXT,__text in hello.o
ld64.lld: error: VANILLA relocation must be extern at offset -1325400056 of __TEXT,__text in hello.o
ld64.lld: error: VANILLA relocation has width 1 bytes, but must be 0 bytes at offset -1325400056 of __TEXT,__text in hello.o
ld64.lld: error: VANILLA relocation must be extern at offset -1459617782 of __TEXT,__text in hello.o
ld64.lld: error: VANILLA relocation has width 1 bytes, but must be 0 bytes at offset -1459617782 of __TEXT,__text in hello.o
ld64.lld: error: VANILLA relocation must be extern at offset -1593835520 of __TEXT,__text in hello.o
ld64.lld: error: VANILLA relocation has width 1 bytes, but must be 0 bytes at offset -1593835520 of __TEXT,__text in hello.o
```

**Comment by thevinster** [comment]
armv7 architectures aren't supported for ld64.lld and will most likely not be supported as there isn't a sufficient need to given that Apple is moving towards arm64. I would suggest building for that architecture or if that's not possible, continue using the apple linker.

**Comment by OldWorldOrdr** [comment]
actually this is still a bug because there should be a better error telling the user 32 bit arm isn't supported instead of whatever I got, so users don't mistake it for a bug.
