### ISSUE TITLE
Compiling a C program using Clang for the RISC-V architecture and simulating it using Spike causes segmentation fault

### ISSUE THREAD

**Issue by eric900115** [llvm/llvm-project#62709]
I compiled a C program using Clang for the RISC-V architecture and simulated it using Spike. However, this resulted in a segmentation fault.

To be more specific, the segmentation fault occurs when the `-mrvv-vector-bits=128` option is added during compilation. 

Note: the `-mrvv-vector-bits` option was released just two weeks ago in this commit: https://github.com/llvm/llvm-project/commit/42e79d9771f96110c7f51ee5f39a76517ae44234.

The failing case (`test.c`):
```c
#include <stdio.h>
#include <time.h>
#include <riscv_vector.h>
#include <string.h>

int main(){
  short a __attribute__((__vector_size__(8)));
  short b __attribute__((__vector_size__(8)));
  short c __attribute__((__vector_size__(8)));

  for(int i = 0; i < (sizeof(a) / sizeof(a[0])); i++){
    c[i] = a[i] * b[i];
  }

  for(int j = 0; j < (sizeof(c) / sizeof(c[0])); j++){
    printf("%hd\n", c[j]);
  }
}
```
The compile command was:
```shell
/mnt/c/llvm-project/install/bin/clang-17  --target=riscv64-unknown-elf --sysroot=/opt/riscv/riscv64-unknown-elf --gcc-toolchain=/opt/riscv -march=rv64gcv1_zfh_zvfh0p1 -menable-experimental-extensions -mrvv-vector-bits=128 -O1 -v -g test.c -o test.elf
```

Simulating using spike:
```shell
/opt/riscv/bin/spike /opt/riscv/riscv64-unknown-elf/bin/pk test.elf
```

The result of simulation:
```console
bbl loader
0
0
0
0
z  0000000000000000 ra 0000000000000000 sp 0000003ffffffb50 gp 000000000001f120
tp 0000000000000000 t0 00000000000102ee t1 ffffffffffffffff t2 0000000000000000
s0 0000000000000000 s1 0000000000000000 a0 0000000000000000 a1 000000000001f930
a2 0000000000000002 a3 0000000000000002 a4 0000000000000001 a5 0000000000000000
a6 0000000000000001 a7 0000000000000040 s2 0000000000000000 s3 0000000000000000
s4 0000000000000000 s5 0000000000000000 s6 0000000000000000 s7 0000000000000000
s8 0000000000000000 s9 0000000000000000 sA 0000000000000000 sB 0000000000000000
t3 0000000000000064 t4 0000000000000000 t5 0000000000000000 t6 0000000000000000
pc 0000000000000000 va/inst 0000000000000000 sr 8000000200006620
User fetch segfault @ 0x0000000000000000
make: *** [Makefile:32: run] Error 255
```

**Comment by topperc** [comment]
The -mrvv-vector-bits has existed for longer than two weeks. It was added in 089bfedfb828c2675f3cc57d6ecac1a87ca243a1. 42e79d9771f96110c7f51ee5f39a76517ae44234 only added a new feature that uses the option.

One of the older behaviors is to allow the compiler to assume what value the `vlenb` CSR contains. This is used to simplify stack frame code as seen from the diff here https://godbolt.org/z/hn7YKdsKE. The compiler assumes `vlenb` is 16.

Was your build of spike also configured to use 128 bit vectors?

**Comment by eric900115** [comment]
Thanks @topperc .
It works when changing the command from ```/opt/riscv/bin/spike /opt/riscv/riscv64-unknown-elf/bin/pk test.elf``` into ```/opt/riscv/bin/spike --isa=RV64GCV_zfh_zvfh --varch=vlen:128,elen:64 /opt/riscv/riscv64-unknown-elf/bin/pk test.elf```
