### ISSUE TITLE
[RISCV][Bug] Test-suite Bug report 

### ISSUE THREAD

**Issue by karouzakisp** [llvm/llvm-project#62708]
Hello,
When I try to build the benchmarks of the test-suite 
I get the following.

 MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.c.o 
/home/ubuntu/test-suite/build/tools/timeit --summary MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.c.o.time /home/ubuntu/llvm-project/build/bin/clang -DNDEBUG  -O3   -w -Werror=date-time -save-stats=obj -fcommon -D__USE_LARGEFILE64 -D_FILE_OFFSET_BITS=64 -save-stats=obj -MD -MT MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.c.o -MF MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.c.o.d -o MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.c.o -c /home/ubuntu/test-suite/MultiSource/Applications/JM/lencod/macroblock.c
fatal error: error in backend: Cannot select: 0x5555853fca78: i64 = RISCVISD::FSLW 0x555584f06818, 0x55558560ab60, Constant:i64<1>
  0x555584f06818: i64,ch = CopyFromReg 0x55558516fb28, Register:i64 %136
    0x555585605aa8: i64 = Register %136
  0x55558560ab60: i64,ch = CopyFromReg 0x55558516fb28, Register:i64 %137
    0x555585602220: i64 = Register %137
  0x555584f06678: i64 = Constant<1>
In function: writeCoeff4x4_CAVLC
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /home/ubuntu/llvm-project/build/bin/clang -DNDEBUG -O3 -w -Werror=date-time -save-stats=obj -fcommon -D__USE_LARGEFILE64 -D_FILE_OFFSET_BITS=64 -save-stats=obj -MD -MT MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.c.o -MF MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.c.o.d -o MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.c.o -c /home/ubuntu/test-suite/MultiSource/Applications/JM/lencod/macroblock.c
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/home/ubuntu/test-suite/MultiSource/Applications/JM/lencod/macroblock.c'.
4.	Running pass 'RISCV DAG->DAG Pattern Instruction Selection' on function '@writeCoeff4x4_CAVLC'
#0 0x00007fffac00d420 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
clang-15: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 15.0.6
Target: riscv64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/ubuntu/llvm-project/build/bin
clang-15: note: diagnostic msg: 

********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-15: note: diagnostic msg: /tmp/macroblock-8815c2.c
clang-15: note: diagnostic msg: /tmp/macroblock-8815c2.sh
clang-15: note: diagnostic msg:

**Comment by karouzakisp** [comment]
``# Crash reproducer for clang version 15.0.6
# Driver args: "-D" "NDEBUG" "-O3" "-w" "-Werror=date-time" "-save-stats=obj" "-fcommon" "-D" "__USE_LARGEFILE64" "-D" "_FILE_OFFSET_BITS=64" "-save-stats=obj" "-MD" "-MT" "MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.c.o" "-MF" "MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.c.o.d" "-o" "MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.c.o" "-c" "/home/ubuntu/test-suite/MultiSource/Applications/JM/lencod/macroblock.c"
# Original command:  "/home/ubuntu/llvm-project/build/bin/clang-15" "-cc1" "-triple" "riscv64-unknown-linux-gnu" "-emit-obj" "--mrelax-relocations" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "macroblock.c" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=none" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-target-feature" "+m" "-target-feature" "+a" "-target-feature" "+f" "-target-feature" "+d" "-target-feature" "+c" "-target-feature" "+relax" "-target-feature" "-save-restore" "-target-abi" "lp64d" "-msmall-data-limit" "8" "-mllvm" "-treat-scalable-fixed-error-as-warning" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=/home/ubuntu/test-suite/build" "-resource-dir" "/home/ubuntu/llvm-project/build/lib/clang/15.0.6" "-dependency-file" "MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.c.o.d" "-MT" "MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.c.o" "-sys-header-deps" "-D" "NDEBUG" "-D" "__USE_LARGEFILE64" "-D" "_FILE_OFFSET_BITS=64" "-internal-isystem" "/home/ubuntu/llvm-project/build/lib/clang/15.0.6/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/lib/gcc/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/include" "-internal-externc-isystem" "/usr/include/riscv64-linux-gnu" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-O3" "-Werror=date-time" "-w" "-fdebug-compilation-dir=/home/ubuntu/test-suite/build" "-ferror-limit" "19" "-fno-signed-char" "-fgnuc-version=4.2.1" "-fcommon" "-vectorize-loops" "-vectorize-slp" "-stats-file=MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.stats" "-faddrsig" "-o" "MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.c.o" "-x" "c" "/home/ubuntu/test-suite/MultiSource/Applications/JM/lencod/macroblock.c"
 "/home/ubuntu/llvm-project/build/bin/clang-15" "-cc1" "-triple" "riscv64-unknown-linux-gnu" "-emit-obj" "--mrelax-relocations" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "macroblock.c" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=none" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-target-feature" "+m" "-target-feature" "+a" "-target-feature" "+f" "-target-feature" "+d" "-target-feature" "+c" "-target-feature" "+relax" "-target-feature" "-save-restore" "-target-abi" "lp64d" "-msmall-data-limit" "8" "-mllvm" "-treat-scalable-fixed-error-as-warning" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=/home/ubuntu/test-suite/build" "-sys-header-deps" "-D" "NDEBUG" "-D" "__USE_LARGEFILE64" "-D" "_FILE_OFFSET_BITS=64" "-O3" "-Werror=date-time" "-w" "-fdebug-compilation-dir=/home/ubuntu/test-suite/build" "-ferror-limit" "19" "-fno-signed-char" "-fgnuc-version=4.2.1" "-fcommon" "-vectorize-loops" "-vectorize-slp" "-stats-file=MultiSource/Applications/JM/lencod/CMakeFiles/lencod.dir/macroblock.stats" "-faddrsig" "-x" "c" "macroblock-8815c2.c"
``

**Comment by EugeneZelenko** [comment]
Could you please try 16 or `main` branch?

**Comment by karouzakisp** [comment]
I want to add the macroblock files but I cannot find an option

**Comment by karouzakisp** [comment]
> 

You mean llvm version 16.0.0?

**Comment by EugeneZelenko** [comment]
Yes, but there are several patch releases since 16.0.0 already.

**Comment by karouzakisp** [comment]
I have added many commits on my own. And I am building inside qemu to emulate RISCV thus build takes 1-2 days. Is it possible to locate the fix for this or I should just move all of my commits to the llvm 16.0.*

**Comment by topperc** [comment]
RISCVISD::FSLW was only supposed to be used for the Zbt extension that was never ratified. I don't see any -march or -mcpu on your command line that would have enabled that. I'll take a look at the llvm 15 code base and see if I see anything.

**Comment by karouzakisp** [comment]
I have enabled only theadba,theadbb, theadbs in the RISCV.td file around line 500 to test them.

**Comment by topperc** [comment]
The only two places that I see that generate RISCVISD::FSLW is in `RISCVTargetLowering::ReplaceNodeResults` and `getRISCVWOpcodeByIntr`.

The code in `RISCVTargetLowering::ReplaceNodeResults` should only be enabled if ISD::FSHL is set to Custom by this code

```
  if (Subtarget.hasStdExtZbt()) {
    setOperationAction({ISD::FSHL, ISD::FSHR}, XLenVT, Custom);
    setOperationAction(ISD::SELECT, XLenVT, Legal);

    if (Subtarget.is64Bit())
      setOperationAction({ISD::FSHL, ISD::FSHR}, MVT::i32, Custom);
```

The code in `getRISCVWOpcodeByIntr` should only be used to legalize a `llvm.riscv.fshl` intrinsic.

**Comment by karouzakisp** [comment]
I was trying to implement srriw (Perform a cyclic right shift on word operand) for theadbb
But I could not generate the instruction.
``
    if (Subtarget.hasStdExtBb()  ){
      setOperationAction({ISD::FSHL, ISD::FSHR}, XLenVT, Custom);
      if (Subtarget.is64Bit()){
        setOperationAction({ISD::FSHL, ISD::FSHR}, MVT::i32, Custom);
      }
    }
``
Because the llvm langref says that for llvm.fshl If the first 2 arguments are identical, this is equivalent to a rotate left operation. This did not work either, but I forgot to remove them. 

Thanks for the help I appreciate it.
