### ISSUE TITLE
Question: DWARF DIE for declarations

### ISSUE THREAD

**Issue by mf-RDP** [llvm/llvm-project#62718]
Hi everyone,

Question: For an inhouse project, I need to modify LLVM / Clang so that DWARF is emitted for declarations (without function body), like DLL, external Imports. 

A DwarfDIE Subprogram shall be emitted, reflecting function parameters and return value.

Any hint where I should start implementing this? `\LLVM\llvm\lib\DebugInfo\DWARF\DWARFContext.cpp`?

Many Thanks

Edit: My latter 'research' shows I'm better off in `\LLVM\llvm\lib\CodeGen\AsmPrinter`. However, I'm grateful for any further advices.

**Comment by asl** [comment]
Please use llvm Discourse (https://discourse.llvm.org/) for these kind of questions
