### ISSUE TITLE
clang frontend command failed with exit code 70

### ISSUE THREAD

**Issue by rogeriosouzamoraes** [llvm/llvm-project#62720]
Greetings,

the attached documents reports Clang v16.0.3 crash on RHEL 8 machine.

[build.log](https://github.com/llvm/llvm-project/files/11480684/build.log)
[smSerialization-bd422b.cpp.txt](https://github.com/llvm/llvm-project/files/11480718/smSerialization-bd422b.cpp.txt)
[smSerialization-bd422b.sh.txt](https://github.com/llvm/llvm-project/files/11480719/smSerialization-bd422b.sh.txt)

Regards,
Rogerio

**Comment by Endilll** [comment]
Appears to be fixed in Clang 17: https://godbolt.org/z/qnG675z8c
Reduced by C-Reduce:
```cpp
class smArchive {
  int m_bufptr;
  smArchive &operator>>(unsigned &);
};
smArchive &smArchive::operator>>(unsigned &i) {
  int ii;
  unsigned char *s = (unsigned char *)1 + m_bufptr;
  ii = *s << 24;
  ii |= *--s << 16;
  ii |= *--s << 8;
  ii |= *--s;
  i = ii;
  return *this;
}
```
