### ISSUE TITLE
Marking relocatable file  header with  ELFOSABI_GNU  is not correct .

### ISSUE THREAD

**Issue by UmeshKalappa0** [llvm/llvm-project#62732]
Hi all,
When we have `llvm.used` built-ins emitted like https://godbolt.org/z/Kc9j44xev

the built-in assembler generates the relocatable object file by setting `e_ident[EI_OSABI]` to `ELF::ELFOSABI_GNU` at which is incorrect with design assumption that made in https://reviews.llvm.org/D95749.

So we need to fix the setting `EI_OSABI` like stated in  https://reviews.llvm.org/D95749.

**Comment by Endilll** [comment]
> When we have llvm.used built-ins emitted like https://godbolt.org/z/Kc9j44xev

I don't see `llvm.used` built-ins there.
