### ISSUE TITLE
Backport c7b291a63f5cabea47e1b4b13e7091e3e37dadb1 to release/16.x

### ISSUE THREAD

**Issue by androm3da** [llvm/llvm-project#62740]
@issue-subscribers-backend-hexagon

/cherry-pick c7b291a63f5cabea47e1b4b13e7091e3e37dadb1

**Comment by androm3da** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/c7b291a63f5cabea47e1b4b13e7091e3e37dadb1

**Comment by androm3da** [comment]
@tstellar who should review this PR?  The backend owner?  @kparzysz-quic can you approve this cherry-pick to 16.0.0?

**Comment by tstellar** [comment]
A review from @kparzysz-quic would be fine.
