### ISSUE TITLE
llvm-config.h header file is missing in the include\Config folder.

### ISSUE THREAD

**Issue by PavelKotov1** [llvm/llvm-project#62757]
Hello, dear friends!
I am having a problem in LLVM 16.02:
`llvm-config.h` header file is missing in the `include\Config` folder. 
There is `llvm-config.h.cmake` file present, but I am very new to CMake and cannot figure out how to produce `llvm-config.h` using the command from the previous post by Leon-Zhang [on Oct 21, 2022].
Could somebody be so nice and kind and explain how to produce the needed header by giving me detailed possibly step by step instructions.
With kind regards, Pavel Kotov.

**Comment by asl** [comment]
Please refer to https://llvm.org/docs/GettingStarted.html for installation guide. `llvm-config.h` is produced from `llvm-config.h.cmake` template during the compilation step

**Comment by PavelKotov1** [comment]
llvm-config.h is produced from llvm-config.h.cmake template during the compilation step
Well, it does not look like it it...
