### ISSUE TITLE
[clang] a bug of simple C code "z = z + 101;" was compiled to wrong llvm-ir instruction "  %a = add i32 %a, 5"

### ISSUE THREAD

**Issue by shawn-xc** [llvm/llvm-project#62758]
```c
int test(int a, int b) {
    int z = 0;
    z = a | b >> 1;
    z = z + 101;
    z = z | 100;
    z = z - (b >> 1);
    z = z & 100;
    return z;
}
```
the above c code is very simple, compile with clang:
```bash
clang -O2 -emit-llvm toy.c -S -o toy.ll --target=riscv32
```
the toy.ll shows below:
```c
; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i32 @test(i32 noundef %a, i32 noundef %b) local_unnamed_addr #0 {
entry:
  %shr = ashr i32 %b, 1
  %or = or i32 %shr, %a
  %add = add i32 %or, 5
  %or1 = or i32 %add, 100
  %sub = sub i32 %or1, %shr
  %and = and i32 %sub, 100
  ret i32 %and
}
```

` %add = add i32 %or, 5` is a mistake context, clang treats a integer number `101` as a binary number `0b101`。 `5` should be corrected to `101`。

**Comment by topperc** [comment]
I don't believe that clang is interpreting 101 as a binary number. I'll see what it's actually doing.

**Comment by topperc** [comment]
Alive2 says that the code is equivalent https://alive2.llvm.org/ce/z/UyKgsq

**Comment by shawn-xc** [comment]
> Alive2 says that the code is equivalent https://alive2.llvm.org/ce/z/UyKgsq

I tried in compiler explorer: https://godbolt.org/z/7c7h1h8ff

**Comment by topperc** [comment]
> > Alive2 says that the code is equivalent https://alive2.llvm.org/ce/z/UyKgsq
> 
> I tried in compiler explorer, gcc is ok, clang is wrong. https://godbolt.org/z/7c7h1h8ff

Do you have a set of inputs that produce the wrong result?

**Comment by shawn-xc** [comment]
> > > Alive2 says that the code is equivalent https://alive2.llvm.org/ce/z/UyKgsq
> > 
> > 
> > I tried in compiler explorer, gcc is ok, clang is wrong. https://godbolt.org/z/7c7h1h8ff
> 
> Do you have a set of inputs that produce the wrong result?

I build a random c test framwork for RISCV instrunction , this is a unepected and lucky discovery.

**Comment by topperc** [comment]
> 

101 is 0b01100101. I believe clang has done an analysis and determined that bits 5 and 6 don't affect the result and has changed them to 0.

**Comment by topperc** [comment]
Here's a reduced example that shows the same 5 https://godbolt.org/z/Kandqv47E

The And with 100 guarantees that only bits 6,5, and 2 from the subtract affect the result.
That means only bits 6:0 of the subtract inputs affect the result. Anything in bits 31:7 of the subtract inputs can only affect bits 31:7 of the subtract result.
The Or guarantees bits 6, 5, and 2 of its result are set.
Becuase of the Or and the And only bits 4, 3, 1, and 0 of the add result matter to the output. Those bits can only be affected by bits 4:0 of the add inputs.
Therefore it is safe to change 0b01100101 to 0b00000101.

**Comment by topperc** [comment]
I don't believe this is a bug. Alive2 shows the IR to be equivalent.

**Comment by shawn-xc** [comment]
> Here's a reduced example that shows the same 5 https://godbolt.org/z/Kandqv47E
> 
> The And with 100 guarantees that only bits 6,5, and 2 from the subtract affect the result. That means only bits 6:0 of the subtract inputs affect the result. Anything in bits 31:7 of the subtract inputs can only affect bits 31:7 of the subtract result. The Or guarantees bits 6, 5, and 2 of its result are set. Because of the Or and the And only bits 4, 3, 1, and 0 of the add result matter to the output. Those bits can only be affected by bits 4:0 of the add inputs. Therefore it is safe to change 0b01100101 to 0b00000101.

you are right, thanks very much
