### ISSUE TITLE
[Atomic operations] atomic min and max have signed and unsigned operations while others don't

### ISSUE THREAD

**Issue by mylovemyfun** [llvm/llvm-project#62761]
In CGAtomic.cpp, why only atomic min and atomic max distinguish unsigned types but others don't? 
![image](https://github.com/llvm/llvm-project/assets/33219568/12d0e0dd-df26-456c-8f85-0abe8f25be88)

**Comment by topperc** [comment]
LLVM assumes twos complement representation for integers. Addition of twos complement values is the same as unsigned addition and subtraction so there's no need to distinquish.

**Comment by tbaederr** [comment]
Ask questions on Discourse please.
