### ISSUE TITLE
clang built mpfr test failure on s390x

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#62760]
The mpfr_compat test in the mpfr test suite fails on s390x when mpfr is built with clang.  This was working with clang-16, and I've bisected the failure down to 531e06668bf84f6d5f85b15c5d2ff6418165a4c4.

**Comment by nikic** [comment]
The issue is that I failed to use `getNonEmpty()` for the `abs` range, which means that for the degenerate case of non-poison abs on i1 we return an empty range instead of a full range.
