### ISSUE TITLE
[ASTImporter] Missing implementation for CXXRewrittenBinaryOperator

### ISSUE THREAD

**Issue by sztomi** [llvm/llvm-project#62770]
When running CTU-analysis on a C++23 codebase, the analyzer fails when encountering this node type. (cc @balazske - at EuroLLVM I was asked to tag you in these issues, hope you don't mind the ping).

**Comment by balazske** [comment]
I have created a patch to import the CXXRewrittenBinaryOperator node:
https://reviews.llvm.org/D153424
