### ISSUE TITLE
[ASTImporter] Missing implementation for ConvertVectorExpr

### ISSUE THREAD

**Issue by sztomi** [llvm/llvm-project#62773]
When running CTU-analysis on a C++23 codebase, the analyzer fails when encountering this node type. (cc @balazske - at EuroLLVM I was asked to tag you in these issues, hope you don't mind the ping).

**Comment by danix800** [comment]
Fixed by df21f9fc037329ae05ff4640d9172364bb9ef6ed

https://reviews.llvm.org/D157249
