### ISSUE TITLE
Redundant check of pointer when operator delete is called

### ISSUE THREAD

**Issue by hiraditya** [llvm/llvm-project#62783]
Testcase:

```cpp
void if_delete(char *p) {
    if (p) {
        delete(p);
    }
}
```

$ clang++ -O3 -fno-exceptions

```asm
if_delete(char*):                         # @if_delete(char*)
        test    rdi, rdi
        jne     operator delete(void*)@PLT                      # TAILCALL
        ret
```

I've opened a similar issue opened with gcc a while back: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87628

As per: https://en.cppreference.com/w/cpp/memory/new/operator_delete

> In all cases, if ptr is a null pointer, the standard library deallocation functions do nothing. If the pointer passed to the standard library deallocation function was not obtained from the corresponding standard library allocation function, the behavior is undefined.

**Comment by dcci** [comment]
This transformation is incorrect. See: https://reviews.llvm.org/D79378 and https://github.com/llvm/llvm-project/issues/33929

**Comment by hiraditya** [comment]
I'm wondering if we can remove the check with `-fassume-sane-operator-new`?
