### ISSUE TITLE
LLVM/Clang does not optimize division by a power of 2 correctly on rv64gc

### ISSUE THREAD

**Issue by ryao** [llvm/llvm-project#62781]
```
int main (int argc, char ** argv)
{
	return (argc / 4);
}
```

At -O2, that compiles to:

```
main:                                   # @main
        slli    a1, a0, 1
        srli    a1, a1, 62
        add     a0, a0, a1
        sraiw   a0, a0, 2
        ret
```

https://gcc.godbolt.org/z/Eza9Kv6dT

If you manually change it to use a bit shift, we get the optimal solution:

```
main:                                   # @main
        srai    a0, a0, 2
        ret
```

**Comment by topperc** [comment]
Arithmetic shift right is not the same as division for signed numbers.

Consider -1 divided by 4. Division should return 0. Arithmetic shift right would give -1.

**Comment by topperc** [comment]
The code is correct.

**Comment by topperc** [comment]
The code is correct.

**Comment by ryao** [comment]
@topperc This would be why I hate making minimal test cases by hand for issues that I find in LLVM's output. Every time I do, a subtle difference causes the issue to not be shown.

Here is what prompted me to file this issue:

https://gcc.godbolt.org/z/dYbWfGzdP
https://gcc.godbolt.org/z/EvndaPnhh

Everything is the same except for line 124 in the C code. LLVM generates 3 extra instructions for division by 4 versus bit shift right by 2.

**Comment by topperc** [comment]
> @topperc This would be why I hate making minimal test cases by hand for issues that I find in LLVM's output. Every time I do, a subtle difference causes the issue to not be shown by the minimal test case. However, if I do not do this, people are likely to ask me to make a minimal test case. :/
> 
> Here is what prompted me to file this issue:
> 
> https://gcc.godbolt.org/z/dYbWfGzdP https://gcc.godbolt.org/z/EvndaPnhh
> 
> Everything is the same except for line 124 in the C code. LLVM generates 3 extra instructions for division by 4 versus bit shift right by 2. The type is uint32_t, so signed-ness is not an issue.

It's a division after a subtraction of two pointers. The type of the pointers doesn't matter. The result of a pointer subtract is ptrdiff_t which is a signed type.

**Comment by jrtc27** [comment]
That's still division of a signed (ptrdiff_t) value? You'd have to have done value analysis to prove that the value is positive. Casting the dividend to size_t will also give you more efficient code generation.

**Comment by jrtc27** [comment]
Without looking at whether it matters in this case, both of your proposed optimisations neglect the upper bits of the register. Presumably the source is using a 32-bit unsigned integer as an index into an array of 32-bit integers, and thus must be zero-extended from 32 to 64 bits before being scaled by 4 for the access.

**Comment by jrtc27** [comment]
Ok, in this case the values involved are all obviously non-negative so transforming it would be legal. Seems we're a bit aggressive with using sign-extending instructions here, which presumably then thwarts our ability to generate good code?

**Comment by topperc** [comment]
> Ok, in this case the values involved are all obviously non-negative so transforming it would be legal. Seems we're a bit aggressive with using sign-extending instructions here, which presumably then thwarts our ability to generate good code?

I don't think we have enough visibility in SelectionDAG to see that `nelems` is greater than 2. So we can't rediscover that the subtract of -1 won't go below 0. Maybe if IR had `sub nuw X, 1` instead of `add nsw X, -1`. The nsw is useless for this and there's no flag for an add that is equivalent to the nuw on the sub form.
