### ISSUE TITLE
amdgpu-arch linking failure due to llibhsa dependency on libstdc++ from gcc >=12

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#62784]
libhsa packaged in ROCm 5.4.3 and 5.5.0 on machines with SLES15 SP4 depends on libstdc++ from GCC 12 https://github.com/RadeonOpenCompute/ROCm/issues/2084
It forced me to build LLVM using GCC 12 which is is a too strict requirement. Otherwise, I got
```console
/usr/bin/ld: /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1.8.50500: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/clang/tools/amdgpu-arch/CMakeFiles/amdgpu-arch.dir/build.make:106: bin/amdgpu-arch] Error 1
```
Consider
```cmake
find_package(hsa-runtime64 QUIET 1.2.0 HINTS ${CMAKE_INSTALL_PREFIX} PATHS /opt/rocm)
```
this is likely to be found and I cannot use `DYNAMIC_HSA` to workaround the issue.
Unless libhsa aggressively use new C++ features which is quite unlikely, it should not be built using GCC 12 but a much more conservative choice like GCC 9.
On the LLVM side, we need to test linking before using the library.

**Comment by ye-luo** [comment]
If there is no clear benefit of directly linking libhsa. Let us keep only dynamical loading case. @jhuber6 Could you put up a patch?

**Comment by jhuber6** [comment]
> If there is no clear benefit of directly linking libhsa. Let us keep only dynamical loading case. @jhuber6 Could you put up a patch?

Sure, give me some time and I'll put one up.
