### ISSUE TITLE
[Regression] Clang stopped adding Build ID information

### ISSUE THREAD

**Issue by billionai** [llvm/llvm-project#62795]
Using this small example program:

```c
int main() {
    unsigned long x = 0x00007fffffffe8f8;
    unsigned long *addr = &x;
        return 0;
}
```

compiling it with Clang 15 and Clang 16 and attempting to print the Build ID I get the following output:

```console
$ clang-15 -g t.c -o with
$ readelf -a with | grep "Build ID"
readelf: with: Warning: Gap in build notes detected from 0x401047 to 0x401054
    Build ID: aabbd3a932308269de34b952bc64ec135a55c6c8
readelf: with: Warning: Gap in build notes detected from 0x401021 to 0x401045
$ clang-16 -g t.c -o without
$ readelf -a without | grep "Build ID"
readelf: without: Warning: Gap in build notes detected from 0x1041 to 0x1065
```

Without it, GDB cant find the correct separate debug information to read from.

**Comment by DimitryAndric** [comment]
Usually, the `.note.gnu.build-id` section is added by the linker, not the compiler. I suspect that your clang-15 invocation uses GNU ld, which adds a build id by default, and your clang-16 invocation uses lld, which does not add a build id by default.

Can you figure out which linker is invoked in each of your test cases? It would help if you added `-v` to the clang invocations.

That said, if you add `-Wl,--build-id` it should always add a build id, even when different linkers are used.

**Comment by billionai** [comment]
I just checked and both are using ld. I think the difference is because clang-15 was installed by the fedora package manager, while 16 and 17 were compiled and installed by hand, so I think fedora changed the default flags and I assumed it was clang default. I think this one is a dud, sorry for the noise

**Comment by DimitryAndric** [comment]
Fedora/RHEL (via @tstellar) do indeed patch something in their clang packages to explicitly enable build-id: https://bugzilla.redhat.com/show_bug.cgi?id=1432403

I'm unsure why "stock" clang doesn't do this, but I assume it was by design.

**Comment by tstellar** [comment]
There is a CMake option called ENABLE_LINKER_BUILD_ID that is disabled by default, but we enable for Fedora/RHEL.
