### ISSUE TITLE
[MLIR] Reverse traversal of def-use chains

### ISSUE THREAD

**Issue by Riphiphip** [llvm/llvm-project#62797]
I am attempting to write an analysis for a dialect I am working on, but have hit a bit of a snag. The algorithm I am implementing is based on def-use chain traversal from user to producer, where almost all the producing Ops in the dialect have more than 1 result, and the ordering of said results is semantically very important. After trying a few different things and reading through ["Understanding the IR structure"](https://mlir.llvm.org/docs/Tutorials/UnderstandingTheIRStructure/#traversing-the-def-use-chains) it seems like def-use traversal when going in the use-def direction only provides information on which Op defined the value, but the index of the result is nowhere to be found. 

Am I missing something or is this actually the case?

**Comment by joker-eph** [comment]
When you have a `Value`, it can be either an `OpResult` or a `BlockArgument`. You can `dyn_cast` to check. If it is an `OpResult` then `getDefiningOperation` returns the `Operation*`, but also you have access to `getResultNumber()` which is the index of the result in the list of results for the Operation.

(closing assuming this answers)

**Comment by Riphiphip** [comment]
It does indeed. Thank you!
