### ISSUE TITLE
The output type of atomic operation function is unsigned regardless of whether the input parameter is signed or unsigned

### ISSUE THREAD

**Issue by mylovemyfun** [llvm/llvm-project#62793]
source code 1:
Builtin atomic add operation function with int input type
```c
__sync_fetch_and_sub_8(int,  int);
```
I got the assembly bundle code:
```asm
{
.reg    .s32 temp;
neg.s32     temp, %r5;
atom.global.add.u32     %r6, [%r1], %r5;
}
```
The return value is parsed to an unsigned 32-bit width type.

source code 2:
Builtin atomic add operation function with long input type
```c
__sync_fetch_and_sub_8(long, long);
```
The assembly bundle code:
```asm
{
.reg    .s64 temp;
neg.s64     temp, %rd2;
atom.global.add.u64     %rd3, [%r1], temp;
}
```
The return value is also parsed to an unsigned 64-bit width type.

Assume there is an atomic operation function, the return value of it is a binary complementary code with a value of 1111 1111. If this return value is parsed as signed value, the origin code would be 1000 0001 and the true value would be -1 (decimal). But if this return value is parsed as unsigned value, the origin code would be itself 1111 1111 and the true value would be 255 (decimal). Two results are different.

The other atomic operations don't distinguish type as well, like atomic `sub`,  `or`,  `xor`, and `and`. 
Can someone please explain why complier doesn't distinguish signed and unsigned return type for atomic operation funcitons? Wouldn't that go wrong?

**Comment by arsenm** [comment]
Typed values don't really exist. The signed-ness is a matter of the interpretation; the type is attached to the instruction. There's no difference in the actual binary result for any of these operations.
