### ISSUE TITLE
`hash_value(TypeID id)` produces collisions 

### ISSUE THREAD

**Issue by makslevental** [llvm/llvm-project#62792]
Drop this somewhere (like [here](https://github.com/llvm/llvm-project/blob/9602c7a0817f34fb4d01194119fe4b75c00ea5ed/mlir/unittests/IR/TypeTest.cpp#L66))

```cpp
TEST(Type, TypeIDComparison) {
  MLIRContext ctx;
  ctx.loadDialect<FakeDialect>();

#define FORALL_CONCRETETYPES(_)                                                \
  _(BFloat16Type)                                                              \
  _(ComplexType)                                                               \
  _(Float8E4M3B11FNUZType)                                                     \
  _(Float8E4M3FNType)                                                          \
  _(Float8E4M3FNUZType)                                                        \
  _(Float8E5M2Type)                                                            \
  _(Float8E5M2FNUZType)                                                        \
  _(Float16Type)                                                               \
  _(Float32Type)                                                               \
  _(Float64Type)                                                               \
  _(FunctionType)                                                              \
  _(IndexType)                                                                 \
  _(IntegerType)                                                               \
  _(MemRefType)                                                                \
  _(NoneType)                                                                  \
  _(OpaqueType)                                                                \
  _(RankedTensorType)                                                          \
  _(TupleType)                                                                 \
  _(UnrankedMemRefType)                                                        \
  _(UnrankedTensorType)                                                        \
  _(VectorType)

#define DECLARETYPEID(TYPE) TypeID TYPE##ID = TypeID::get<TYPE>();
  FORALL_CONCRETETYPES(DECLARETYPEID)
#undef DECLARETYPEID

  typedef struct {
    TypeID typeID;
    char typeName[100];
  } typeIDTuple;

  typeIDTuple typeIDTuples[] = {
#define DECLARETYPEID(TYPE) {TYPE##ID, #TYPE},
      FORALL_CONCRETETYPES(DECLARETYPEID)
#undef DECLARETYPEID
  };

  bool equalError = false;
  bool hashError = false;
  for (int i = 0; i < sizeof(typeIDTuples) / sizeof(typeIDTuples[0]); ++i) {
    for (int j = i + 1; j < sizeof(typeIDTuples) / sizeof(typeIDTuples[0]);
         ++j) {
      typeIDTuple type1 = typeIDTuples[i];
      typeIDTuple type2 = typeIDTuples[j];
      if (type1.typeID == type2.typeID) {
        fprintf(stderr, "ERROR: Expected type id %s to be unequal type id %s\n",
                type1.typeName, type2.typeName);
        equalError = true;
      }
      if (hash_value(type1.typeID) == hash_value(type2.typeID)) {
        fprintf(stderr,
                "ERROR: Expected hash of type id %s to be unequal hash type id "
                "%s\n",
                type1.typeName, type2.typeName);
        hashError = true;
      }
    }
  }
  EXPECT_FALSE(equalError);
  EXPECT_FALSE(hashError);
}

```

and you will see something like 

```
ERROR: Expected hash of type id BFloat16Type to be unequal hash type id ComplexType 
ERROR: Expected hash of type id Float8E4M3B11FNUZType to be unequal hash type id Float8E4M3FNType 
ERROR: Expected hash of type id Float8E4M3FNUZType to be unequal hash type id Float8E5M2Type 
ERROR: Expected hash of type id Float8E5M2FNUZType to be unequal hash type id Float16Type 
ERROR: Expected hash of type id Float32Type to equal hash be unequal id Float64Type 
```

The reason is [`hash_value(TypeID id)`](https://github.com/llvm/llvm-project/blob/b7f93c28096fc8503e4d2d80c43ee2c0ccce480f/mlir/include/mlir/Support/TypeID.h#L150) calls [`DenseMapInfo<const TypeID::Storage *>::getHashValue(id.storage)`](https://github.com/llvm/llvm-project/blob/77f38e1325a251623ec39a0d9ffa718e80436f94/llvm/include/llvm/ADT/DenseMapInfo.h#L83) which is the original implementation from ~[2007](https://discord.com/channels/@me/1101296426488700948/1108607430717345812). Well the problem isn't that it's the original implementation but maybe that it makes certain assumptions ([possibly something about malloc returning 16 byte aligned address groups](https://stackoverflow.com/questions/70692795/why-is-malloc-16-byte-aligned) - shoutout @rkayaith for connecting this to the `>> 4`).

Anyway besides the problem of collisions being an issue for people who want to feed some other map with these keys (e.g., Python maps), it's possible that such collisions lead to poor performance (since poorly distributed keys means `DenseMap` is spending a lot of time looking for empty slots). I played around with some alternatives (e.g., murmur hash from [here](http://zimbry.blogspot.com/2011/09/better-bit-mixing-improving-on.html)) as well as doing what [`DenseMapInfo<...>`](https://github.com/llvm/llvm-project/blob/2bb43d72d91cdc269fd756725a5f187dcb48b038/llvm/include/llvm/ADT/DenseMapInfo.h#L155) for other integer types i.e., 

swapping

```cpp
DenseMapInfo<const TypeID::Storage *>::getHashValue(id.storage);
```

for

```cpp
DenseMapInfo<uintptr_t>::getHashValue((uintptr_t)id.storage);
```

They all resolve the collision issue but I'm not sure what to propose since 

1. hashing isn't anywhere near my forte 
2. this potentially affects lots of downstream users.

@rkayaith proposed benchmarking a couple of choices against IREE tests and I'll come back tomorrow with those numbers.

**Comment by jpienaar** [comment]
Note that hash producing the same values isn't unexpected. For a unique key TypeID should be used.

**Comment by lattner** [comment]
Right, I assume @makslevental is pointing out that a better hash would cause fewer collisions and thus better compile time performance.

**Comment by makslevental** [comment]
> Right, I assume @makslevental is pointing out that a better hash would cause fewer collisions and thus better compile time performance.

Kind of you to give me the benefit of the doubt! 

In fact I was confused about the point of a non-unique hash value vis-a-vis e.g. [`mlirTypeIDHashValue`](https://github.com/llvm/llvm-project/blob/525b45fa595fefa339ab552e6e71c22e15cf95c6/mlir/include/mlir-c/Support.h#L156), which superficially (at least to my prior, naive, eyes) reads like its result can be passed to a python map but returns a non-unique. 

I believe I have unconfused myself by speaking with @jpienaar and @rkayaith and looking at the implementation of [`DenseMapBase::LookupBucketFor`](https://github.com/llvm/llvm-project/blob/525b45fa595fefa339ab552e6e71c22e15cf95c6/llvm/include/llvm/ADT/DenseMap.h#L635) (and by quickly retaking my undergrad DS&A class) - i.e., if you're consuming some API that claims to return a hash value then you should always assume there can be collisions because perfect hash functions for reference types aren't possible. 

But then it occurs to me that the actual TypeIDs themselves *are a perfect hash function* - they're unique and the set of them is finite/fixed at compile time. And in fact we could compute at compile time a *minimal* perfect hash function? E.g., using one of the options listed [here](https://github.com/Kronuz/constexpr-phf)?

**Comment by joker-eph** [comment]
> But then it occurs to me that the actual TypeIDs themselves are a perfect hash function - they're unique and the set of them is finite/fixed at compile time. 

They are unique, but not fixed at compile time: IRDL for example injects new entity with dynamic TypeID.
Even if the number was fixed, TypeID is really just a pointer like any other, the only thing "special" compared to other pointers is that many instances are addresses of static objects, which are align(8) and not align(16).
It seems to me that to compute a perfect hash function, you would need to know the runtime address of all the possible TypeID objects in the binary.... at compile time.

**Comment by makslevental** [comment]
> They are unique, but not fixed at compile time: IRDL for example injects new entity with dynamic TypeID.

Yes, this is a serious kink. I need to think about whether it's possible to handle both somehow.

> you would need to know the runtime address of all the possible TypeID objects in the binary.... at compile time.

Yes I think that's true but I also think it might be possible: https://stackoverflow.com/questions/50489239/gather-addresses-of-all-static-c-strings-at-compile-time/50710495#50710495. One unknown is how this will play with different translation units? But the important question is whether it's worth it - I plan to investigate and come back with numbers!

**Comment by joker-eph** [comment]
Even without IRDL, there the link you sent rely on global registry and static global constructors, which we don’t have in MLIR right now (and aren’t straightforward in terms of cross platform portability)

**Comment by makslevental** [comment]
Just because I said I would (and negative results are important too): I did implement a perfect hash function using a [linker trick](https://github.com/makslevental/linker_hax) and timed it using `check-mlir`. After acconting for `lit`'s scheduling (i.e. you need to use `--order=lexical`), there was no difference. Maybe I'll pick it back up with some particularly pathological cases (large graphs produced by torch-mlir or IREE?) but for now I'm closing. Thanks all for the discussion.
