### ISSUE TITLE
how to use lldb to print derived object directly from base object pointer

### ISSUE THREAD

**Issue by mttbx** [llvm/llvm-project#62805]
In gdb, I can achieve this using cmd like:
```
set p obj on
set p vtbl on
```

**Comment by jimingham** [comment]
lldb doesn't have an affordance to print the vtable of C++ objects.  It's been requested on occasion but not to the level that would motivate someone to implement that feature yet.

lldb calls the "full type" of a derived object (as opposed to the type it has statically in the current frame) the "dynamic" value.  By default, lldb always prints the full dynamic type in the results of `expr`, `frame var` etc.  There are both options to this command that turn off dynamic value printing, and settings you can use to turn this off globally.  But you shouldn't have to do anything to see the dynamic value, that's the default.

The one difference between lldb & gdb is that lldb uses the clang front-end to parse expressions, and that doesn't allow use to evaluate subexpressions to determine their "dynamic type" mid-parse.  So within an expression objects will have their static not their dynamic types.  You have to use casting to get the dynamic value.

Jim

**Comment by mttbx** [comment]
@jimingham  I want to print vector element in lldb, and I get the error:
```
(lldb) p vec
error: expression failed to parse:
error: Couldn't lookup symbols:
  std::vector<std::shared_ptr<mz::xxx>, std::allocator<std::shared_ptr<mz::xxx>>>::operator[](unsigned long)
```
