### ISSUE TITLE
Revert GCC DSE work-around from release/16.x

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#62809]
There were some patches merged into the release/16.x branch to work around a build issue with gcc+lto.  There is some disagreement now if this is the correct fix, so I propose we revert these changes from the release/16.x branch:

ae42196bc493ffe877a7e3dff8be32035dea4d07
21f3dfbc26736e4299c154e67065652f48279047
d5cce0a7781bfbb9322a2e9625c7f88253801148
57262bbd32c35eb05bac34e39a751abc0466b9da

@MaskRay @thesamesam @jhuber6

**Comment by thesamesam** [comment]
Fine with me, thank you! Let's give it more time to bake on trunk given some of the (unexpected) reported issues.
