### ISSUE TITLE
[mlir] Property storage makes parsing a file with many attributes go OOM

### ISSUE THREAD

**Issue by matthiaskramm** [llvm/llvm-project#62800]
We have a .mlir that contains a function with a huge number of arguments (~300k args, so the function has attributes like `arg272506`).

While this is arguably a silly thing to have (this is part of a stress test, but as far as I can tell, it stems from a real model), it does break MLIR after the introduction of properties. Memory consumption goes beyond 100Gb just for parsing the file.

As far as I can tell, this is what happens:

(a) `OperationParser` calls `OpBuilder::create` which calls `Operation::create`.
(b) `Operation::create` calls `Operation::setAttrs` with the (huge) attribute dictionary
(c) `Operation::setAttrs` discovers that we have properties storage and decides that it has to set the attributes one by one, since any of them might be an inherent attribute.
(d) `Operation::setAttr` is called individually for each of the 300k attributes, likely uniquing the (partial) `NamedAttrLists` in the process.
(e) We run out of memory.

I'm not sure what the best fix is here. Maybe `Operation::setAttr` needs to check the name of each inherent attribute against `newAttrs` to see if there's overlap, and if there isn't, it can still fall back to `attrs = newAttrs`?

**Comment by joker-eph** [comment]
I am missing something here: you have 300k function arguments, but you don't have 300k attributes attached to the function right? 
(attributes attached to the arguments themselves are stored in an array attribute attached a single attribute to the function)

Basically I don't follow this part:

> ~300k args, so the function has properties like arg272506

What is arg272506 here and how does it relate to the properties?

Last question: are you parsing a func.func op or a custom one? Can you provide the reproducer (with an empty function body).

**Comment by matthiaskramm** [comment]
> I am missing something here: you have 300k function arguments, but you don't have 300k attributes attached to the function right?

I was wondering about that too. But turns out that's really what's going on. These are not argument attributes, these are custom attributes added by the framework, and they're attached directly to the function.

> What is arg272506 here and how does it relate to the properties?

Oops, typo, should be "attribute". Corrected that in the above comment.

> Last question: are you parsing a func.func op or a custom one?

This is a "normal" func.func, except for the framework-specific attributes.

Simplified reproducer at http://www.quiss.org/files/large.mlir.gz
