### ISSUE TITLE
lldb couldn't lookup symbols

### ISSUE THREAD

**Issue by mttbx** [llvm/llvm-project#62819]
This is the code.
```c++
// clang++ -o main main.c

#include <vector>

int main()
{
  std::vector<int> x = {1, 2, 3};
  // x[0] = 3;
  return 0;
}
```

If I comment out `x[0] = 3;`, I can't use `p x[0]` in lldb. The error is:
```console
error: expression failed to parse:
error: Couldn't lookup symbols:
  std::vector<int, std::allocator<int>>::operator[](unsigned long)

```

**Comment by Michael137** [comment]
That's because you're using the expression evaluator (`p`, which in older versions of lldb is an alias for `expression`) to get the element, which requires debug-info for the operator to be present.

If you use `frame variable` (`var` for short), it should work fine:

```
(lldb) v x[0] 
(int) x[0] = 1
```

**Comment by mttbx** [comment]
@Michael137 Thank you, but I can't debug this using your method:
```
#include <vector>
#include <memory>

using namespace std;

struct A{
  vector<int> val;
};

int main()
{
  
  shared_ptr<A> x = make_shared<A>();
  x->val.resize(3);
  return 0;
}
```
Here's the error:
```
(lldb) p x->val[0]
error: expression failed to parse:
error: Couldn't lookup symbols:
  std::vector<int, std::allocator<int>>::operator[](unsigned long)
(lldb) v x->val[0]
error: Failed to dereference sythetic value
```

**Comment by Michael137** [comment]
Which version of lldb are you using? It works for me on top-of-tree on macOS:
```
(lldb) expr x->val[0]                                                                                     
error: expression failed to parse:
error: Couldn't lookup symbols:
  __ZNSt3__16vectorIiNS_9allocatorIiEEEixB6v15006Em
(lldb) v x->val[0]
(int) x->val[0] = 0
(lldb) settings set target.import-std-module true                                                         
(lldb) expr x->val[0]                                                                                     
(value_type) $0 = 0
```

**Comment by mttbx** [comment]
clang version 16.0.3
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64

**Comment by mttbx** [comment]
This is a different issue, I opened a new issue and close this one.
#62825
