### ISSUE TITLE
Backport fix for unexpected warning after 3b6f7e4

### ISSUE THREAD

**Issue by phoebewang** [llvm/llvm-project#62831]
/cherry-pick 3d7903f100 a4f366dcd8

3b6f7e4 introduced unexpected warnings due to missing `A->claim()`. Porting the revert and reland patch.

**Comment by phoebewang** [comment]
@tstellar Sorry, I need to cancel this request. What action should I take? Close it directly or run a command?

**Comment by tstellar** [comment]
@phoebewang You can just remove the project and milestone from the issue.
