### ISSUE TITLE
[C++20] [Modules] `-fmodule-file` vanishes when building module stub objects

### ISSUE THREAD

**Issue by aaronmondal** [llvm/llvm-project#62843]
Flags like `-fmodule-file=A:part=part.pcm` vanish when we are building the object file from the precompiled BMI.

```bash
echo "export module A;" > a.cppm

clang++ a.cppm -v -std=c++20 \
    --precompile -o a.pcm

clang++ a.pcm -v -std=c++20 -c \
    -o a.interface.o \
    -fmodule-file=nonexistent=ThisDoesntShowOnTheCommandLine.pcm
```

This means that all such compilations trigger `-Wread-modules-implicitly` when an interface depends on some other module.

cc @ChuanqiXu9

**Comment by ChuanqiXu9** [comment]
I don't understand the issue for the reproducer. Why do we add `-fmodule-file=nonexistent=ThisDoesntShowOnTheCommandLine.pcm`?

> This means that all such compilations trigger -Wread-modules-implicitly when an interface depends on some other module.

If the interface depends on other modules, we should add the corresponding `-fmodule=<module-name>=<path-to-BMI>`. This should be what we discussed. Do I miss anything?

**Comment by aaronmondal** [comment]
@ChuanqiXu9 Sorry my example was misleading.

> If the interface depends on other modules, we should add the corresponding -fmodule=<module-name>=<path-to-BMI>. This should be what we discussed. Do I miss anything?

This is the intended behavior, but the `pcm -> object` compilation seems to ignore `-fmodule-file`. The following triggers `-Wread-modules-implicitly`:

```bash
echo "export module A:partition;" > a-partition.cppm

clang++ a-partition.cppm -v -std=c++20 \
    --precompile -o a-partition.pcm

printf '
export module A;

import :partition;
' > a.cppm

clang++ a.cppm -v -std=c++20 \
    -fmodule-file=A:partition=a-partition.pcm \
    --precompile -o a.pcm

# -fmodule-file is ignored.
clang++ a.pcm -v -std=c++20 -c \
    -fmodule-file=A:partition=a-partition.pcm \
    -o a.interface.o
```

**Comment by ChuanqiXu9** [comment]
Do you mean when you run the following line:

```
# -fmodule-file is ignored.
clang++ a.pcm -v -std=c++20 -c \
    -fmodule-file=A:partition=a-partition.pcm \
    -o a.interface.o
```

you can still see the warning even if the option `-fmodule-file` is specified?

Then this should be a true bug.
