### ISSUE TITLE
[MLIR] Sparse Tensor documentation format was broken

### ISSUE THREAD

**Issue by Avimitin** [llvm/llvm-project#62851]
The documentation for the operation `sparse_tensor.pack` has an [additional code block marker](https://github.com/llvm/llvm-project/blob/896fbe68fff8b206b56de151519d86b0700368d4/mlir/include/mlir/Dialect/SparseTensor/IR/SparseTensorOps.td#L96), and this breaks the following code documentation for the `sparse_tensor.push_back` operation.

The below image is how it looks like now:

![image](https://github.com/llvm/llvm-project/assets/30021675/ecec3dab-885a-472d-adf5-c57b2cf58476)

**Comment by Avimitin** [comment]
https://reviews.llvm.org/D151058

**Comment by PeimingLiu** [comment]
Thanks for reporting! Should be fixed by https://reviews.llvm.org/D151114

**Comment by Avimitin** [comment]
Yes, it’s been fixed.
