### ISSUE TITLE
[clang] Reference to 'int[1]' cannot bind to 'int[]'

### ISSUE THREAD

**Issue by usx95** [llvm/llvm-project#62863]
GCC test: `g++.dg/cpp2a/paren-init29.C`
Related: [P0388R4](https://wg21.link/p0388r4)
```cpp
int (&&r)[3] = static_cast<int[3]>(42);
int (&&r2)[1] = static_cast<int[]>(42); // clang errors: reference to type 'int[1]' could not bind to an rvalue of type 'int[]'
int main ()
{
  if (r[0] != 42 || r[1] != 0 || r[2] != 0)
    __builtin_abort ();
  if (r2[0] != 42 || sizeof (r2) != sizeof (int))
    __builtin_abort ();
}
```
https://godbolt.org/z/bKrT3oW8f

**Comment by cor3ntin** [comment]
@Fznamznon This still fails (not sure if intended)

**Comment by Fznamznon** [comment]
I think the fix was never merged, so the fail is expected.

**Comment by AaronBallman** [comment]
> I think the fix was never merged, so the fail is expected.

It'd be nice to get that fix landed; I think it was held up on some libc++ stuff, but we had a way forward for it?

**Comment by Fznamznon** [comment]
It was https://github.com/llvm/llvm-project/issues/64250 that was blocking, however the comments to it say that it is a bug in the patch itself. I'll take a look a bit more.

**Comment by Fznamznon** [comment]
I posted a PR including the changes mentioned in https://github.com/llvm/llvm-project/issues/64250 , so libc++ test case from there doesn't fail anymore.
