### ISSUE TITLE
[RISCV] clang16.0.x miscompiles half-float multiply-add

### ISSUE THREAD

**Issue by sherylll** [llvm/llvm-project#62881]
For the following code I expect Clang to generate the instruction `fmadd.h`, but Clang 16 generates `fmadd.s` instead:
```c
_Float16 fmadd_h(_Float16 x, _Float16 y, _Float16 z)
{
    return x + y * z;
}
```
**Clang 16.0.x**:
Compiler flag: `-march=rv32imfzfh -O2`
```asm
fmadd_h(_Float16, _Float16, _Float16):              # @fmadd_h(_Float16, _Float16, _Float16)
        fcvt.s.h        ft0, fa0
        fcvt.s.h        ft1, fa1
        fcvt.s.h        ft2, fa2
        fmadd.s ft0, ft1, ft2, ft0
        fcvt.h.s        fa0, ft0
        ret
```
**Clang 15.0.x/trunk**:
```asm
fmadd_h(_Float16, _Float16, _Float16):              # @fmadd_h(_Float16, _Float16, _Float16)
        fmadd.h fa0, fa1, fa2, fa0
        ret
```

**Comment by topperc** [comment]
This appears to be working correctly on trunk.

**Comment by sherylll** [comment]
Yes using Compiler Explorer it looks fine on trunk: https://godbolt.org/z/PMWo7cKWd
I can reproduce this problem in clang 16.0.0/16.0.3.

**Comment by topperc** [comment]
My best guess it was fixed by https://reviews.llvm.org/D145071

cc: @asb

**Comment by asb** [comment]
Yes, that change almost certainly fixed it. I'm not sure I'd characterise the previous version as a "miscompile" - it's more that Clang support for zfh was incomplete in that it didn't disable the default half->float promotion when zfh was enabled.

**Comment by sherylll** [comment]
Got it, thanks a lot!
