### ISSUE TITLE
Segmentation fault when llvm-bolt compiles aarch64 binary on x86_64/aarch64 cpu

### ISSUE THREAD

**Issue by jt387** [llvm/llvm-project#62883]
Hi all, I want to use BOLT to optimize performance of AArch64 binary, I have installed LLVM on x86_64 and AArch64 Ubuntu. When I try to execute the command on x86_84 machine:
```shell
llvm-bolt demo3 -instrument -o demo3-instrument
```
I get the segmentation fault as below:
```console
BOLT-INFO: Target architecture: aarch64
BOLT-INFO: BOLT version: 2713781b0cdc1af647048ec97d40101664673dee
BOLT-INFO: first alloc address is 0x400000
BOLT-INFO: creating new program header table at address 0x600000, offset 0x200000
BOLT-WARNING: debug info will be stripped from the binary. Use -update-debug-sections to keep it.
BOLT-INFO: enabling relocation mode
BOLT-INFO: forcing -jump-tables=move for instrumentation
BOLT-INFO: disabling -align-macro-fusion on non-x86 platform
BOLT-INFO: number of removed linker-inserted veneers: 0
BOLT-INFO: 0 out of 16 functions in the binary (0.0%) have non-empty execution profile
BOLT-INFO: UCE removed 0 blocks and 0 bytes of code.
BOLT-INFO: Starting stub-insertion pass
BOLT-INFO: Inserted 0 stubs in the hot area and 0 stubs in the cold area. Shared 0 times, iterated 1 times.
 #0 0x00007fc339baacaf llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/root/jiangtao_workspace/soft/build/bin/../lib/libLLVMSupport.so.17git+0x1cbcaf)
 #1 0x00007fc339ba83d4 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007fc3396300c0 (/lib/x86_64-linux-gnu/libc.so.6+0x430c0)
 #3 0x00007fc336a7f620 llvm::bolt::InstrumentationRuntimeLibrary::emitBinary(llvm::bolt::BinaryContext&, llvm::MCStreamer&) (/root/jiangtao_workspace/soft/build/bin/../lib/../lib/libLLVMBOLTRuntimeLibs.so.17git+0x8620)
 #4 0x00007fc3366c8022 llvm::bolt::emitBinaryContext(llvm::MCStreamer&, llvm::bolt::BinaryContext&, llvm::StringRef) (/root/jiangtao_workspace/soft/build/bin/../lib/../lib/libLLVMBOLTCore.so.17git+0x6f022)
 #5 0x00007fc33a75a7c0 llvm::bolt::RewriteInstance::emitAndLink() (/root/jiangtao_workspace/soft/build/bin/../lib/libLLVMBOLTRewrite.so.17git+0xe97c0)
 #6 0x00007fc33a76134f llvm::bolt::RewriteInstance::run() (/root/jiangtao_workspace/soft/build/bin/../lib/libLLVMBOLTRewrite.so.17git+0xf034f)
 #7 0x0000561181032cfe main (llvm-bolt+0x3cfe)
 #8 0x00007fc3396110b3 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b3)
 #9 0x00005611810341fe _start (llvm-bolt+0x51fe)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: llvm-bolt demo3 -instrument -o demo3-instrument
Segmentation fault (core dumped)
```

And I try it on AArch64 machine, get the same error:
```console
BOLT-INFO: Target architecture: aarch64
BOLT-INFO: BOLT version: <unknown>
BOLT-INFO: first alloc address is 0x400000
BOLT-INFO: creating new program header table at address 0x600000, offset 0x200000
BOLT-WARNING: debug info will be stripped from the binary. Use -update-debug-sections to keep it.
BOLT-INFO: enabling relocation mode
BOLT-INFO: forcing -jump-tables=move for instrumentation
BOLT-INFO: disabling -align-macro-fusion on non-x86 platform
BOLT-INFO: number of removed linker-inserted veneers: 0
BOLT-INFO: 0 out of 16 functions in the binary (0.0%) have non-empty execution profile
BOLT-INFO: UCE removed 0 blocks and 0 bytes of code.
BOLT-INFO: Starting stub-insertion pass
BOLT-INFO: Inserted 0 stubs in the hot area and 0 stubs in the cold area. Shared 0 times, iterated 1 times.
 #0 0x0000ffff81c944f0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/local/bin/../lib/libLLVMSupport.so.16+0x1c44f0)
 #1 0x0000ffff81c92638 llvm::sys::RunSignalHandlers() (/usr/local/bin/../lib/libLLVMSupport.so.16+0x1c2638)
 #2 0x0000ffff81c927d4 SignalHandler(int) Signals.cpp:0:0
 #3 0x0000ffff839e97c0 (linux-vdso.so.1+0x7c0)
 #4 0x0000ffff7ef11e6c llvm::bolt::InstrumentationRuntimeLibrary::emitBinary(llvm::bolt::BinaryContext&, llvm::MCStreamer&) (/usr/local/bin/../lib/../lib/libLLVMBOLTRuntimeLibs.so.16+0x6e6c)
 #5 0x0000ffff7eb6c0e0 llvm::bolt::emitBinaryContext(llvm::MCStreamer&, llvm::bolt::BinaryContext&, llvm::StringRef) (/usr/local/bin/../lib/../lib/libLLVMBOLTCore.so.16+0x640e0)
 #6 0x0000ffff8295f3d0 llvm::bolt::RewriteInstance::emitAndLink() (/usr/local/bin/../lib/libLLVMBOLTRewrite.so.16+0xd33d0)
 #7 0x0000ffff829645e8 llvm::bolt::RewriteInstance::run() (/usr/local/bin/../lib/libLLVMBOLTRewrite.so.16+0xd85e8)
 #8 0x0000aaaabeb03860 main (/usr/local/bin/llvm-bolt+0x3860)
 #9 0x0000ffff8177ed50 __libc_start_main /build/glibc-70LW9c/glibc-2.31/csu/../csu/libc-start.c:342:3
#10 0x0000aaaabeb04844 _start (/usr/local/bin/llvm-bolt+0x4844)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: llvm-bolt demo3 -instrument -o demo3-instrument
Segmentation fault (core dumped)
```

Any suggestion will be appreciated, thanks! LLVM version: 16.0.4

**Comment by jt387** [comment]
the x86_64 environment info:
gcc:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 

llvm-bolt:
LLVM (http://llvm.org/):
  LLVM version 17.0.0git
  Optimized build with assertions.
BOLT revision 2713781b0cdc1af647048ec97d40101664673dee

  Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_32 - AArch64 (little endian ILP32)
    aarch64_be - AArch64 (big endian)
    arm64      - ARM64 (little endian)
    arm64_32   - ARM64 (little endian ILP32)
    x86        - 32-bit X86: Pentium-Pro and above
    x86-64     - 64-bit X86: EM64T and AMD64


the aarch64 environment info:
gcc:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/9/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

llvm-bolt:
LLVM (http://llvm.org/):
  LLVM version 16.0.4
  Optimized build with assertions.
BOLT revision <unknown>

  Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_32 - AArch64 (little endian ILP32)
    aarch64_be - AArch64 (big endian)
    arm64      - ARM64 (little endian)
    arm64_32   - ARM64 (little endian ILP32)
    x86        - 32-bit X86: Pentium-Pro and above
    x86-64     - 64-bit X86: EM64T and AMD64

**Comment by jt387** [comment]
[demo.txt](https://github.com/llvm/llvm-project/files/11550139/demo.txt)
github doesn't support to upload the aarch64 binary file type, so i modify the filename extension, and i have checked that using demo.txt can reproduce the segment fault

**Comment by aaupov** [comment]
Hi @jt387,

Instrumentation for aarch64 is not supported yet – @ElvinaYakubova is working on it. We'll need to emit an error instead of crashing in the meantime.

**Comment by jt387** [comment]
Great! Thanks a lot! @aaupov @ElvinaYakubova

**Comment by sfc-gh-sgiesecke** [comment]
> I'll start upstreaming of aarch64 instrumentation next week

@ElvinaYakubova Can you provide a reference to what you're referring to here? Did this go into LLVM 17?

**Comment by ElvinaYakubova** [comment]
> > I'll start upstreaming of aarch64 instrumentation next week
> 
> @ElvinaYakubova Can you provide a reference to what you're referring to here? Did this go into LLVM 17?

It is already present in the upstream version [here](https://github.com/llvm/llvm-project/commit/6e4c230525fb66ddf4310c53bb621b5ccc579444) and [here](https://github.com/llvm/llvm-project/commit/87e9c42495aa4d290b04fa2866ec0e627a54842a), but as I can see it is not included in LLVM 17 release

**Comment by yota9** [comment]
Closing the issue as done due to instrumentation availability.
