### ISSUE TITLE
Extend bugprone-unused-return-value to all functions with specific return types.

### ISSUE THREAD

**Issue by royjacobson** [llvm/llvm-project#62884]
Return types like `std::expected`, `std::error_code`, `boost::system::error_code`, `absl::Status` etc indicate an error might happen. It would be nice to have a way to force people into handling those return values (or at least explicitly ignore them).

Abseil declares `absl::Status` as a `[[nodiscard]]` class which achieves the same goal, but it seems nearly impossible to get existing STL classes to opt in to this extension.

Rust has the `unused_must_use` diagnostic for this coding style.

**Comment by chaitanyav** [comment]
@royjacobson i will look into this

**Comment by royjacobson** [comment]
@chaitanyav amazing, thanks for taking this up and completing this so quickly!

![image](https://github.com/llvm/llvm-project/assets/5706313/a7b1b031-a931-47be-9cf2-b317b3aa14d4)

**Comment by chaitanyav** [comment]
@royjacobson  @PiotrZSL @EugeneZelenko  thank you
