### ISSUE TITLE
What is the minimum iOS version supported by clang?

### ISSUE THREAD

**Issue by hiraditya** [llvm/llvm-project#62896]
clang has `-mios-version-min` flag that is used to support apps for a particular iOS version. But it is unclear which minimum iOS version a given clang version would support.

e.g.,
```
clang -target aarch64-ios -mios-version-min=2.0  -c test.c
```
doesn't error out.

**Comment by shafik** [comment]
CC @Bigcheese @ldionne

**Comment by hiraditya** [comment]
As Apple deprecate older iOS version, i'd expect clang to reflect something similar.

**Comment by keith** [comment]
It's possible that clang still supports producing valid binaries, assuming they don't rely on the SDK, although I agree I don't think that's a super practical concern.
