### ISSUE TITLE
clang-format poor spacing with braces initializer

### ISSUE THREAD

**Issue by cmcqueen** [llvm/llvm-project#62904]
`test.c` containing:
```c
static const CMD_HANDLER_T command_handlers[] =
{
    {   "a",            HandleA             },
    {   "bb",           HandleBB            },
    {   "ccc",          HandleCCC           },
    {   NULL,           NULL                },
};
```

Command:

```shell
clang-format -style="{ SpacesInParentheses: true, AlignArrayOfStructures: Left }" test.c > test.out.c
```

Result:

```c
static const CMD_HANDLER_T command_handlers[] = {
    {"a",    HandleA  },
    { "bb",  HandleBB },
    { "ccc", HandleCCC},
    { NULL,  NULL     },
};
```

Anomalous things:

* For the first row only, there is no space between the opening brace and the first value.
* For the row with the widest last value, there is no space between the last value and the closing brace.

I have tested this with Clang-Format v13.0.1, v15.0.7 and v16.0.0, with the same results.

**Comment by kajusK** [comment]
Same issue here, is there any progress on this? It's pretty annoying...

**Comment by kadler** [comment]
I've also run in to this bug while migrating an old project to git and cleaning up its formatting.

**Comment by EugeneZelenko** [comment]
Could you please try 17 or `main` branch?

**Comment by ptc-tgamper** [comment]
Still happens on 17.0.6
