### ISSUE TITLE
[correlated-propagation] miscompile of sext into zext

### ISSUE THREAD

**Issue by ericliuu** [llvm/llvm-project#62901]
The following IR is miscompiled by the CorrelatedValuePropagation pass:
```llvm
define i64 @src(i32 %a) {
  %is_a_nonnegative = icmp sgt i32 %a, 1
  %narrow = select i1 %is_a_nonnegative, i32 %a, i32 0
  %max = sext i32 %narrow to i64
  ret i64 %max
}
```
After running the IR through opt with `-passes="correlated-propagation"`, the sext instruction is replaced with zext:
```llvm
define i64 @tgt(i32 %a) {
  %is_a_nonnegative = icmp sgt i32 %a, 1
  %narrow = select i1 %is_a_nonnegative, i32 %a, i32 0
  %max = zext i32 %narrow to i64
  ret i64 %max
}
```
Unfortunately, passing in undef can cause a value mismatch. An example of this is provided here: https://alive2.llvm.org/ce/z/NGqk4Y

**Comment by luxufan** [comment]
Candidate patch: https://reviews.llvm.org/D151295
