### ISSUE TITLE
[MLIR] Project compiled using `gcc` links incorrectly to `mlir` compiled with `clang` causing invalid memory access.

### ISSUE THREAD

**Issue by Jezurko** [llvm/llvm-project#62918]
### Description:
```hpp
/// Parse a type list.
ParseResult parseTypeList(SmallVectorImpl<Type> &result) {
  return parseCommaSeparatedList(
      [&]() { return parseType(result.emplace_back()); });
}
```

(in `mlir/include/mlir/IR/OpImplementation.h:1153`)
Passing the lambda to the `parseCommaSeparatedList` function causes a runtime issue when `mlir` compiled with Clang is linked to a project (such as VAST - https://github.com/trailofbits/vast) compiled using GCC.
The issue is that each compiler has a different order in which it stores `lambda-capture` attributes in memory. While `clang` stores the `result` reference first and `this` pointer second:

```
(lldb) print callable
((unnamed struct)) $3 = {
  __result = 0x00007fffffff2350
  __this = 0x00007fffffff30d0
}
```

GCC does it the other way round:

```
(lldb) print lambda
warning: `this' is not accessible (substituting 0). Couldn't load 'this' because its value couldn't be evaluated
((unnamed class)) $1 = {
  this = 0x00007fffffff30b0
  result = 0x00007fffffff2330
}
```

Because the file `OpImplementation.h` is included into the project it is compiled using GCC and therefore generates the `lambda-capture` the second way. But calling the lambda (from inside `llvm::function_ref`) uses Clang compiled body of the lambda function (because it is inlined) that expects the reverse order. (What we believe happens is that the linker throws away the GCC compiled body because there already is one in the linked library). This causes the `.emplace_back()` to be called on the wrong object  (`this` instead of `result`) and an invalid access to memory leading to a crash.

What we believe might resolve the issue is using a virtual function in `parseCommaSeparatedList` instead of the `function_ref` argument.

### Steps to reproduce:
This bug can be observed using the packages from the LLVM APT repository (`clang-16` `clang-tools-16` `libclang-common-16-dev` `libclang-16-dev` `libllvm16` `libmlir-16-dev` `mlir-16-tools` `llvm-16` `llvm-16-dev` `libclang-rt-16-dev`) and compiling VAST (https://github.com/trailofbits/vast/tree/gcc-build) using GCC*. Then running `vast-opt` on a simple input such as
```mlir
module attributes {dlti.dl_spec = #dlti.dl_spec<#dlti.dl_entry<!hl.int, 32 : i32>>} {
  hl.func external @minus (%arg0: !hl.lvalue<!hl.int>, %arg1: !hl.lvalue<!hl.int>) {
    %0 = hl.var "res" : !hl.lvalue<!hl.int> = {
      %1 = hl.ref %arg0 : !hl.lvalue<!hl.int>
      %2 = hl.implicit_cast %1 LValueToRValue : !hl.lvalue<!hl.int> -> !hl.int
      %3 = hl.ref %arg1 : !hl.lvalue<!hl.int>
      %4 = hl.implicit_cast %3 LValueToRValue : !hl.lvalue<!hl.int> -> !hl.int
      %5 = hl.sub %2, %4 : (!hl.int, !hl.int) -> !hl.int
      hl.value.yield %5 : !hl.int
    }
    hl.return
  }
}
```
by calling `builds/ninja-multi-default/tools/vast-opt/Debug/vast-opt <input-file>` (it is also possible to pipe in the input).

It might be more beneficial to use a debug build of `mlir` for observing though.

### Observing the bug:
```console
$ lldb -- vast-opt <input-file>
breakpoint set -f HighLevel.cpp.inc -l 5684
run
step
```
Now we are in the lambda initialization:
```
(lldb) print this
(CustomOpAsmParser *) $1 = 0x00007fffffff30b0
(lldb) print &result
(llvm::SmallVectorImpl<mlir::Type> *) $2 = 0x00007fffffff2330
```
if we now `step` into the call of the lambda and print the pointers again we can see the values are "swapped":
```
(lldb) print this
(mlir::AsmParser *) $4 = 0x00007fffffff2330
(lldb) print &result
(llvm::SmallVectorImpl<mlir::Type> *) $5 = 0x00007fffffff30b0
```

### Additional notes:
The lambda mangles to `_ZN4llvm12function_refIFN4mlir11ParseResultEvEE11callback_fnIZNS1_9AsmParser13parseTypeListERNS_15SmallVectorImplINS1_4TypeEEEEUlvE_EES2_l`.

The memory layout stays the same (`lambda-capture` is `const`). Probably the easiest way to observe this is by printing the memory at the address of the `callable` variable in the `function_ref` constructor and then printing the memory at the runtime address of the capture in the lambda call.

*On Ubuntu run in the root of the repository (at  the moment the `master` branch will not compile with GCC):
```console
$ git clone https://github.com/trailofbits/vast.git
$ git checkout gcc-build
$ export CC=gcc
$ export CXX=g++
$ cmake --preset ninja-multi-default --toolchain ./cmake/lld.toolchain.cmake -DCMAKE_PREFIX_PATH=<path to llvm & mlir config>
$ cmake --build --preset ninja-deb
```

**Comment by Jezurko** [comment]
We also believe that passing the lambda with capture to the `function_ref` might be UB as `function_ref` creates a pointer to the lambda. In the [standard](https://github.com/cplusplus/draft/releases/tag/n4917) the section about creating a pointer to a lambda function (7.5.5.2 expr.prim.lambda.closure; paragraphs 8 and 9) specifically mentions only cases with no _lambda-capture_.

**Comment by joker-eph** [comment]
For this last message, as far as I can tell, the part of the standard you're talking about is for converting the lambda to a function pointer, whereas `llvm::function_ref` is taking a reference to the lambda object (we capture the address of the lambda object itself).

For the original bug, I'm concerned about the potential reach here: while we can work-around this just for this particular case, I would be interested to have a clear support story for the pattern that can fail.
Is this clang-gcc incompatibility known and documented already? Is this a defect in clang?

**Comment by Jezurko** [comment]
> For this last message, as far as I can tell, the part of the standard you're talking about is for converting the lambda to a function pointer, whereas `llvm::function_ref` is taking a reference to the lambda object (we capture the address of the lambda object itself).

Ah, you are probably right. My fault :) Thanks for explaining. At first I thought that it might have been the source of the incompatibility, so that's why I wanted to share it.

> For the original bug, I'm concerned about the potential reach here: while we can work-around this just for this particular case, I would be interested to have a clear support story for the pattern that can fail. 

As in better/clearer/smaller example where this occurs?

> Is this clang-gcc incompatibility known and documented already?

I don't know about any other case or mention of this incompatibility. We had to track this down manually analyzing the assembly code and memory contents. I also briefly tried to look for it after discovering the cause but I haven't found anything (although I'm not sure if I went for the correct keywords in my search inputs).

> Is this a defect in clang?

I don't know. From what I know/have discovered so far I don't think it's exactly a defect in either compiler but rather a very unfortunate situation. But I might be completely wrong on this.

**Comment by joker-eph** [comment]
> As in better/clearer/smaller example where this occurs?

No I mean that this seems like a pretty bad failure mode: we have potentially many latent bugs like this and I would be looking for a principled solution to defend against this (clang-tidy checks for example). 

I just posted https://discourse.llvm.org/t/gcc-abi-compatibility-lambda-captures/70850

**Comment by rkayaith** [comment]
Some previous discussion about this: https://discourse.llvm.org/t/mlir-and-the-c-abi/62578

**Comment by joker-eph** [comment]
Fascinating, seems like last communication was pointing at a gcc bug? https://github.com/itanium-cxx-abi/cxx-abi/issues/141
