### ISSUE TITLE
clang-format: Indenting of #else in nested #if/#elif/#else

### ISSUE THREAD

**Issue by ljungholm** [llvm/llvm-project#62917]
Two potential issues when formatting the first sample below with clang-format:
- The code in the #else and #elif is formatted even when it is not the active choice where as code in `#if 0` is not formatted. Is it expected that the inactive parts of #if/#elif/#else and #if/#else are formatted or not?
- The indent level in the second #else is wrong.

Using clang-format version 15.0.7.

**First Sample**
Formatting:
```c
int myFunction(int x) {
#if 1
#if 1
while(x != 0) {
#else
while (x == 0) {
#endif
#if 0
int y;
return y;
#elif
int x;
return x;
#else
int z;
return z;
#endif
}
}
```
Gives me:
```c
int myFunction(int x) {
#if 1
#if 1
    while (x != 0) {
#else
    while (x == 0) {
#endif
#if 0
int y;
return y;
#elif 1
        int x;
        return x;
#else
    int z;
    return z;
#endif
    }
#endif
}
```
**Second Sample**
Adding an #elif in the first nested #if makes the indent in the #else in second nested #if correct:
```c
int myFunction(int x) {
#if 1
#if 1
while (x != 0) {
#elif 0
while (x > 0) {
#else
while (x == 0) {
#endif
#if 0
int y;
return y;
#elif 1
int x;
return x;
#else
int z;
return z;
#endif
}
#endif
}
```
Gives:
```c
int myFunction(int x) {
#if 1
#if 1
    while (x != 0) {
#elif 0
    while (x > 0) {
#else
    while (x == 0) {
#endif
#if 0
int y;
return y;
#elif 1
        int x;
        return x;
#else
        int z;
        return z;
#endif
    }
#endif
}
```

**Comment by owenca** [comment]
> * The code in the #else and #elif is formatted even when it is not the active choice where as code in `#if 0` is not formatted. Is it expected that the inactive parts of #if/#elif/#else and #if/#else are formatted or not?

Only code in `#if 0` is skipped.

> * The indent level in the second #else is wrong.

Fixed in a4c87f8.
