### ISSUE TITLE
clang-tidy check bugprone-swapped-arguments only reports some swapped function calls

### ISSUE THREAD

**Issue by cat38275** [llvm/llvm-project#62926]
Testing under Windows 10 with LLVM version 16.0.4
I have the source code file, called `code_test.cpp` and the full file is:

```cpp
void paramsIntAndFloat(int nFirst, float fSecond) { }
void paramsFloatAndShort(float fFirst, short nSecond) { }
void foo(int, double) { }

static void checkSwappedArguments()
{
	float fArgument = 32.9f;
	short nArgument = 12;
	paramsIntAndFloat(fArgument, 2);
	paramsIntAndFloat(83.746, nArgument);
	paramsFloatAndShort(nArgument, 29.7);
	paramsFloatAndShort(81, 29.7);
	paramsIntAndFloat(2.0, 4);
	foo(2.0, 4);
}
```
I run the Clang-Tidy command:

```shell
clang-tidy code_test.cpp -checks=-*,bugprone-swapped-arguments --
```

and I get the output:

```console
5 warnings generated.
c:\src\code_test.cpp:9:2: warning: argument with implicit conversion from 'int' to 'float' followed by argument converted from 'float' to 'int', potentially swapped arguments. [bugprone-swapped-arguments]
        paramsIntAndFloat(fArgument, 2);
        ^                 ~~~~~~~~~  ~
                          2          fArgument
c:\src\code_test.cpp:14:2: warning: argument with implicit conversion from 'int' to 'double' followed by argument converted from 'double' to 'int', potentially swapped arguments. [bugprone-swapped-arguments]
        foo(2.0, 4);
        ^   ~~~  ~
            4    2.0
Suppressed 3 warnings (3 with check filters).
```

since the final function call `foo(2.0, 4)` is being picked up, the function call one line above `paramsIntAndFloat(2.0, 4)` definitely should be picked up.  As far as I can tell all 6 function calls should be picked up, rather than just 2 of them.

I had exactly the same results in Clang-Tidy version 15.0.6

**Comment by PiotrZSL** [comment]
Problem is that check is very strict with types compare and match only equal types.
So when you got function that will have argument short and float, and you call it with double and int, it won't catch an issue.

Similar issue could happen when you got function with int and char, and call it with short and int, simply because short != char, then it wont match. When it comes to integer it may not be so... obvious, but for float/integer swap it should be.

**Comment by cat38275** [comment]
Thank you for explaining, this actually makes a lot of sense.  Would it be possible for this to be explained in the documentation at:

https://clang.llvm.org/extra/clang-tidy/checks/bugprone/swapped-arguments.html

I am assuming this is the correct place to look for this information, but the page doesn't offer any details at all, so I was guessing a bit at how this should work.

**Comment by PiotrZSL** [comment]
Sure, actually I want to add support for these.

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D151495
