### ISSUE TITLE
[MLIR] bytecode reader silently fails on zero-width integer attribute

### ISSUE THREAD

**Issue by dtzSiFive** [llvm/llvm-project#62920]
Recently our tools cannot read bytecode for our IR, with strange behavior of:
1) No error message, just silently exits (!)
2) Tools built against recent MLIR and recent mlir-opt itself silently exit this way, but same bytecode can be read using mlir-opt from few weeks ago (or our tools built against such MLIR).
3) Bytecode built from working version are also rejected by newer-MLIR tools.

I've tracked this down to what I believe is the problem: zero-width integer attributes get parsed as a null attribute (?).  Putting together an example using builtin dialects demonstrates the same behavior.

Input ("test.mlir"):

```
module attributes { foo.asdf = 0 : i0 } { }
```

`mlir-opt test.mlir -emit-bytecode | mlir-opt` silently fails, tested using commit 334e377 .

This works with MLIR from around a month ago, I believe introduced in this range: 797594a0438f2c6188e9bb3a382f041d3addcd0d..334e3776d (but appears issue introduced no earlier than `836786a`, sorry for lack of more narrow/accurate commit window).

The NULL attribute claim is from stepping through this in a debugger, looking here (but not sure where problem itself occurs): https://github.com/llvm/llvm-project/blob/fb2c98a929aa65603e9d984307a41325e577e9d3/mlir/lib/Bytecode/Reader/BytecodeReader.cpp#L778 (impl pointer is null, etc.).

**Comment by joker-eph** [comment]
Fixing in https://reviews.llvm.org/D151372

**Comment by dtzSiFive** [comment]
Awesome, thanks!
