### ISSUE TITLE
Clang issue in CTAD

### ISSUE THREAD

**Issue by walge-laine** [llvm/llvm-project#62925]
Clang fails to compile [cppreference example code](https://en.cppreference.com/w/cpp/container/map/deduction_guides). See [Compiler Explorer](https://godbolt.org/z/vYG5PxE5T).

**Comment by shafik** [comment]
Code in question:

```cpp
#include <map>

int main() {
   std::map m1 = {std::pair{"foo", 2}, {"bar", 3}}; // guide #2
   std::map m2(m1.begin(), m1.end()); // guide #1
}
```
