### ISSUE TITLE
Example from C++ standard is rejected as part of constant expression

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#62944]
[OK example](https://timsong-cpp.github.io/cppwp/n4868/class.mem.general#25) from C++ standard is rejected by Clang if it is evaluated as constant expression:
```cpp
struct T1 { int a, b; };
struct T2 { int c; double d; };
union U { T1 t1; T2 t2; };

constexpr int f() {
  U u = { { 1, 2 } };   // active member is t1
  return u.t2.c;        // OK, as if u.t1.a were nominated
}

constexpr int x = f();
```
with the error:
```
read of member 't2' of union with active member 't1' is not allowed in a constant expression
```
Other compilers reject it as well (https://gcc.godbolt.org/z/YTds3Grd5), but since Clang is typically most standard conforming, I decided to ask you first.

Related discussion: https://stackoverflow.com/q/76323477/7325599

**Comment by shafik** [comment]
Yes, they have a common initial sequence but this does not change the active member and therefore is not allowed in a constant expression context, see [expr.const p10](http://eel.is/c++draft/expr.const#5.10):

> an lvalue-to-rvalue conversion that is applied to a glvalue that refers to a non-active member of a union or a subobject thereof;

The example you quote came in via [p0137r1](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0137r1.html) which left that rule in place.

**Comment by cor3ntin** [comment]
I agree with @shafik - Clang and other implementations are correct, I think we can close this
