### ISSUE TITLE
[LV] First order reccurences is incorrectly eliminated

### ISSUE THREAD

**Issue by ebrevnov** [llvm/llvm-project#62954]
There is a regression caused by:

```txt
commit 02369b75fdd7b5fc5d9b47f1b60587c225918511
Author: Florian Hahn <flo@fhahn.com>
Date:   Mon Apr 17 12:30:52 2023 +0100

    [VPlan] Mark recurrence recipes as not having side-effects.
```

While I don't have a short test to share I will try to describe the problem.  Here is the VPlan for the problematic case before `VPlanTransforms::removeDeadRecipes()` call:

```
<x1> vector loop: {
  vector.body:
    EMIT vp<%2> = CANONICAL-INDUCTION
    FIRST-ORDER-RECURRENCE-PHI ir<%106> = phi ir<%.promoted>, ir<%111>
    WIDEN-INDUCTION %indvars.iv = phi 4, %indvars.iv.next, ir<2>
    vp<%5>    = DERIVED-IV ir<4> + vp<%2> * ir<2>
    vp<%6>    = SCALAR-STEPS vp<%5>, ir<2>
    REPLICATE ir<%107> = or vp<%6>, ir<1>
    REPLICATE ir<%108> = getelementptr ir<%74>, ir<%107>
    INTERLEAVE-GROUP with factor 2 at %109, ir<%108>
      ir<%109> = load from index 0
    WIDEN ir<%110> = fadd ir<%75>, ir<%109>
    REPLICATE store ir<%110>, ir<%108>
    WIDEN ir<%111> = sub ir<0>, ir<%indvars.iv>
    EMIT vp<%13> = first-order splice ir<%106> ir<%111>
    EMIT vp<%14> = VF * UF +(nuw)  vp<%2>
    EMIT branch-on-count  vp<%14> vp<%0>
  No successors
}
Successor(s): middle.block

middle.block:
No successors
}
```

As you can see there are a `FIRST-ORDER-RECURRENCE-PHI` recipe and `first-order splice` instruction. Both are deleted by `VPlanTransforms::removeDeadRecipes()` as there are no uses of `first-order splice` instruction (after the change).  This is incorrect because there is an implicit use of `FIRST-ORDER-RECURRENCE-PHI` in `fixFixedOrderRecurrence` which fixes resume value for scalar epilogue.

PS: It doesn't seem to be correct to prevent deletion by marking `FIRST-ORDER-RECURRENCE-PHI` as side effecting... but turning implicit use to explicit doesn't seem to be easy?

**Comment by fhahn** [comment]
@ebrevnov thanks for raising the issue. Do you have a reproducer you could share? Live-outs should be added to avoid the recipes being removed, I will need to check why this is not happening in this case.

**Comment by ebrevnov** [comment]
[reduced3.txt](https://github.com/llvm/llvm-project/files/11624346/reduced3.txt)

**Comment by ebrevnov** [comment]
@fhahn it looks like it will take a while to fix the issue... can we consider reverting the problematic change until we have a solution?

**Comment by fhahn** [comment]
@ebrevnov reverted for now, I also included some details of the issue in the commit message, thanks!

**Comment by ebrevnov** [comment]
Thanks!
