### ISSUE TITLE
clang-format: Add config option to allow function parameters to be displayed on separate lines

### ISSUE THREAD

**Issue by ameerj** [llvm/llvm-project#62963]
For AMD's PAL library, the [style guidelines](https://github.com/GPUOpen-Drivers/pal/blob/dev/doc/process/palCodingStandards.md#formatting-and-commenting) require each parameter in a function definition to occupy a separate line.

For example:
```c++
void SomeFunction(
    int param)
{
}

void SomeOtherFunction(
    int  param,
    bool cond)
{
}
```

There does not seem to be any configuration for clang-format to achieve this style.

**Comment by EugeneZelenko** [comment]
It'll be great to also have option which allows function declaration/definition to be in single line if it fits in `ColumnLimit`, and break otherwise.
