### ISSUE TITLE
[clang-doc] `bool` types in C++ sources get output as `_Bool`

### ISSUE THREAD

**Issue by NekkoDroid** [llvm/llvm-project#62970]
When using `clang-doc` on C++ sources that make use of `bool` they get output as `_Bool` in the yaml and markdown formats.

Input:
`static bool ProcessEvents()`

Output
`static _Bool ProcessEvents()`

**Comment by BotellaA** [comment]
Is there a way to control this bool output?

**Comment by EwgenijGawrilow-TomTom** [comment]
The same bug affects the XML output.
