### ISSUE TITLE
Wrong link target in the documentation

### ISSUE THREAD

**Issue by sedymrak** [llvm/llvm-project#62990]
In the [LDDB documentation](https://lldb.llvm.org/use/variable.html#type-format) you have the following sentence:

"The `--format` (which you can shorten to -f) option accepts a [format name](https://lldb.llvm.org/use/formatting.html)."

I believe that the link points to a wrong place.

I guess that you want it to point to the table that precedes the [Type summary](https://lldb.llvm.org/use/variable.html#type-summary) section.

**Comment by eddiep24** [comment]
Working on it.

**Comment by eddiep24** [comment]
Awaiting review https://reviews.llvm.org/D151668

**Comment by sedymrak** [comment]
Thank you!

(I have learned something new. Before submitting the bug report, I have tried to fix this by using `:ref:` instruction, which is mentioned in the ReStructured Text documentation. However, after rendering the modified page, the link still did not work.)

**Comment by DavidSpickett** [comment]
Fixed by the commit linked above, thanks @eddiep24 !
