### ISSUE TITLE
master build on Ubuntu 18.04 fails in examples/Kaleidoscope

### ISSUE THREAD

**Issue by ananthdurbha** [llvm/llvm-project#63]
FAILED: examples/Kaleidoscope/BuildingAJIT/Chapter2/CMakeFiles/BuildingAJIT-Ch2.dir/toy.cpp.o 
/usr/bin/c++  -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iexamples/Kaleidoscope/BuildingAJIT/Chapter2 -I/home/ananth.durbha/Tools/llvm-project/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2 -Iinclude -I/home/ananth.durbha/Tools/llvm-project/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -g    -fno-exceptions -fno-rtti -std=c++14 -MD -MT examples/Kaleidoscope/BuildingAJIT/Chapter2/CMakeFiles/BuildingAJIT-Ch2.dir/toy.cpp.o -MF examples/Kaleidoscope/BuildingAJIT/Chapter2/CMakeFiles/BuildingAJIT-Ch2.dir/toy.cpp.o.d -o examples/Kaleidoscope/BuildingAJIT/Chapter2/CMakeFiles/BuildingAJIT-Ch2.dir/toy.cpp.o -c /home/ananth.durbha/Tools/llvm-project/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/toy.cpp
In file included from /home/ananth.durbha/Tools/llvm-project/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/toy.cpp:15:0:
/home/ananth.durbha/Tools/llvm-project/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h: In static member function ‘static llvm::Expected<llvm::orc::ThreadSafeModule> llvm::orc::KaleidoscopeJIT::optimizeModule(llvm::orc::ThreadSafeModule, const llvm::orc::MaterializationResponsibility&)’:
/home/ananth.durbha/Tools/llvm-project/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h:108:12: error: could not convert ‘TSM’ from ‘llvm::orc::ThreadSafeModule’ to ‘llvm::Expected<llvm::orc::ThreadSafeModule>’
     return TSM;
            ^~~

**Comment by lhames** [comment]
This should be fixed by 064e7d1df17dcd7f82215c258e2793aa1f8ed760.

**Comment by ananthdurbha** [comment]
verified it resolved. thanks
