### ISSUE TITLE
Clang assertion failure in paren init in new expression

### ISSUE THREAD

**Issue by usx95** [llvm/llvm-project#63008]
GCC: `g++.dg/cpp2a/paren-init20.C`

```cpp
struct A {
    int a;
    int b;
};

void foo() {
    auto z = new A(0, {0});
}
```
https://godbolt.org/z/W6aMaE8fo

**Comment by shafik** [comment]
This looks like a relatively recent regression I wonder if @alanzhao1 recent changes might be involved.

**Comment by alanzhao1** [comment]
Candidate patch: https://reviews.llvm.org/D151763

**Comment by alanzhao1** [comment]
Reopening so this can be backported to 16.x
