### ISSUE TITLE
X86 backend crashed with assertion `Do not know how to soft promote this operator's operand!` for bf16 constants

### ISSUE THREAD

**Issue by joker-eph** [llvm/llvm-project#63017]
```console
SoftPromoteHalfOperand Op #1: t7: v32bf16 = insert_vector_elt t5, t3, Constant:i64<1>

Do not know how to soft promote this operator's operand!
UNREACHABLE executed at llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp:2940!
```

Repro with
```shell
bin/llc -mtriple=x86_64-unknown-linux-gnu   -mcpu="znver4"
```

```ll
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"
declare <32 x bfloat> @llvm.masked.load.v32bf16.p0(ptr nocapture, i32 immarg, <32 x i1>, <32 x bfloat>)

define void @dump_vec() {
  %1 = call <32 x bfloat> @llvm.masked.load.v32bf16.p0(ptr poison, i32 2, <32 x i1> poison, <32 x bfloat> <bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80, bfloat 0xRBF80>)
  ret void
}
```

**Comment by phoebewang** [comment]
Thanks for reporting it. I'll take a look.

**Comment by phoebewang** [comment]
Candidate patch: https://reviews.llvm.org/D151778

**Comment by joker-eph** [comment]
@phoebewang I have the same crash with a slight different case:

```
SoftPromoteHalfOperand Op #1: t11: v32bf16 = insert_vector_elt t9, t7, Constant:i64<1>

Do not know how to soft promote this operator's operand!
UNREACHABLE executed at llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp:3015!
```

Let me know if you need more info?

**Comment by RKSimon** [comment]
@phoebewang A similar crash occurs when the D152928 wip patch is applied and we run `ninja check-llvm-codegen-x86`

**Comment by phoebewang** [comment]
> @phoebewang I have the same crash with a slight different case:
> 
> ```
> SoftPromoteHalfOperand Op #1: t11: v32bf16 = insert_vector_elt t9, t7, Constant:i64<1>
> 
> Do not know how to soft promote this operator's operand!
> UNREACHABLE executed at llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp:3015!
> ```
> 
> Let me know if you need more info?

No idea if I forgot to verify it with this case or it's new regression caused by latter patches. Anyway, it can be fixed by https://reviews.llvm.org/D155952
If you still see the same crash, please provide the new reproducer. Thanks!

**Comment by phoebewang** [comment]
> @phoebewang A similar crash occurs when the D152928 wip patch is applied and we run `ninja check-llvm-codegen-x86`

Thanks @RKSimon , but I failed to apply D152928 in my local. Would you mind to have a try with [D155952](https://reviews.llvm.org/D155952) ?

**Comment by phoebewang** [comment]
> > @phoebewang A similar crash occurs when the D152928 wip patch is applied and we run `ninja check-llvm-codegen-x86`
> 
> Thanks @RKSimon , but I failed to apply D152928 in my local. Would you mind to have a try with [D155952](https://reviews.llvm.org/D155952) ?

I can build it locally now, will try it myself.

**Comment by phoebewang** [comment]
> > > @phoebewang A similar crash occurs when the D152928 wip patch is applied and we run `ninja check-llvm-codegen-x86`
> > 
> > 
> > Thanks @RKSimon , but I failed to apply D152928 in my local. Would you mind to have a try with [D155952](https://reviews.llvm.org/D155952) ?
> 
> I can build it locally now, will try it myself.

[D155961](https://reviews.llvm.org/D155961) will solve it ✌️
