### ISSUE TITLE
Invalid optimization around loops

### ISSUE THREAD

**Issue by Nilstrieb** [llvm/llvm-project#63019]
come from https://github.com/rust-lang/rust/issues/112061

alive2 complains about an optimization in the LLVM IR: https://alive2.llvm.org/ce/z/fyzhJ3

The code is quite big and I have made attempts to minimize it, but I didn't quite figure out the tooling, so I'm not sure whether my not very good minimizations would be useful. Everything can be found on https://github.com/Nilstrieb/rlo-issue-112061 if desired.

The program prints `11` on O0/O1 and `22` on O2.

This small helper must be linked in to run the program:
```c
#include <stdio.h>
#include <stdint.h>

void print_var(uint8_t x) {
    printf("%d", x);
}

void fn12_rs();

int main() {
    fn12_rs();
}
```

I can't say for sure that the IR emitted by rustc is free of UB, but I suspect that this is the case. The code is really sensitive to small changes and rustc's constant propagation pass actually masks the miscompilation and has to be disabled.

@cbeuw suggested running LLVM built with ASan because they were facing crashes on similar input (#63013), but it did not show any issues.

**Comment by efriedma-quic** [comment]
You might want to try using opt-bisect-limit (https://llvm.org/docs/OptBisect.html) to reduce this.

**Comment by nikic** [comment]
Fixes a pretty serious miscompile, so we may consider this for backport, though the timing is a bit unfortunate.

/cherry-pick 4d64ffa94170eadd79954e2a5f13d1f1d16e9e2c 97f0e7b06e6b76fd85fb81b8c12eba2255ff1742
