### ISSUE TITLE
`lli` crashes on input containing UB even with `-force-interpreter`

### ISSUE THREAD

**Issue by Nilstrieb** [llvm/llvm-project#63015]
```llvm
define i32 @main() #0 {
  %1 = load volatile i32, ptr null, align 4
  ret i32 0
}
```
```console
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: lli test.ll -force-interpreter
 #0 0x00007fbfe9a8f242 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/nix/store/5z3s7ar2k045d1igx5kv5g7wpfcwql4n-llvm-16.0.1-lib/lib/libLLVM-16.so+0x10be242)
 #1 0x00007fbfe9a8cb74 SignalHandler(int) (/nix/store/5z3s7ar2k045d1igx5kv5g7wpfcwql4n-llvm-16.0.1-lib/lib/libLLVM-16.so+0x10bbb74)
 #2 0x00007fbfe84f5bf0 __restore_rt (/nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6+0x3dbf0)
 #3 0x00007fbfe8260000 
 #4 0x00007fbfebf46373 llvm::orc::runAsMain(int (*)(int, char**), llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::optional<llvm::StringRef>) (/nix/store/5z3s7ar2k045d1igx5kv5g7wpfcwql4n-llvm-16.0.1-lib/lib/libLLVM-16.so+0x3575373)
 #5 0x00000000004274d1 runOrcJIT(char const*) (/nix/store/l7nlr0cnb39mh4hy5yywn81c4qr07b0v-llvm-16.0.1/bin/lli+0x4274d1)
 #6 0x00000000004145f2 main (/nix/store/l7nlr0cnb39mh4hy5yywn81c4qr07b0v-llvm-16.0.1/bin/lli+0x4145f2)
 #7 0x00007fbfe84e124e __libc_start_call_main (/nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6+0x2924e)
 #8 0x00007fbfe84e1309 __libc_start_main@GLIBC_2.2.5 (/nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6+0x29309)
 #9 0x0000000000416ba5 _start (/nix/store/l7nlr0cnb39mh4hy5yywn81c4qr07b0v-llvm-16.0.1/bin/lli+0x416ba5)
fish: Job 1, 'lli test.ll -force-interpreter' terminated by signal SIGSEGV (Address boundary error)
```
(on x86-64 NixOS, lli 16.0.1)

I also tried this
```llvm
define i32 @main() {
    unreachable
}
```
```console
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: lli aa.ll -force-interpreter
#0 0x0000ffffa996ac40 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib/aarch64-linux-gnu/libLLVM-14.so.1+0xe3ac40)
#1 0x0000ffffa9968c40 llvm::sys::RunSignalHandlers() (/lib/aarch64-linux-gnu/libLLVM-14.so.1+0xe38c40)
#2 0x0000ffffa996b200 (/lib/aarch64-linux-gnu/libLLVM-14.so.1+0xe3b200)
#3 0x0000ffffaed6f7dc (linux-vdso.so.1+0x7dc)
#4 0x0000ffffaed69000 
fish: Job 1, 'lli aa.ll -force-interpreter' terminated by signal SIGILL (Illegal instruction)
```
(on AArch64 Ubuntu, LLVM 14)

I'm not sure whether `lli` is supposed to deal with input containing UB, but at least with `-force-interpreter` i wouldn't expect it to crash. The crash message also tells me to report a bug, so I did that.

**Comment by lhames** [comment]
Hi @Nilstrieb!

The underlying ExecutionEngine (whether the interpreter or the JIT) is effectively running the given code. If the code contains UB then the behavior of the tool will be undefined too. That means that you can expect the same kinds of crashes and misbehavior that you'd get if you compiled the program ahead of time.

I think that detecting / reporting UB in `lli` is a low priority for now -- this is the first bug of this kind that has been filed. If we start seeing more reports of this then there are a couple of things that we could do to improve the situation:

(1) Teach the crash reporter to check whether the crashing frame is in JIT'd or non-JIT'd code, and adjust the error message appropriately. E.g. "Crash detected in JIT'd code" vs "Please file a bug" (for crashes in the LLVM libraries). This would work for the JIT, but not the interpreter.

(2) Support use of the sanitizers, including UBSan, with `lli` where compiler-rt is available. This would be a neat feature, but would require manual intervention on the part of the user so it's probably not a great solution to this particular bug.

(3) Harden the interpreter against certain kinds of UB. E.g. in the specific case of a nullptr dereference or unreachable we could detect and report the error. For general UB though I think the implementation and runtime cost of this approach would be prohibitive, and it would only work for the interpreter, not for the JIT.

For now I'm going to close this as not planned, but if you're interested in looking into any of the approaches above we can re-open it.

**Comment by Nilstrieb** [comment]
Thanks for the quick response! That makes sense. I think it would at least be nice to mention it in the docs for lli, that seems like a low hanging fruit and I did look there before opening this issue.
