### ISSUE TITLE
[coroutines] Compiler incorrectly caches thread_local address across suspend-points in some scenarios

### ISSUE THREAD

**Issue by fpoliakov** [llvm/llvm-project#63022]
The compiler (still) caches the thread_local variable addresses across the suspend points.
[A supposed fix](https://reviews.llvm.org/D135550) (which followed the discussion [here](https://discourse.llvm.org/t/rfc-unify-memory-effect-attributes/65579)) landed, and it indeed fixes many of the original issues. Another relevant closed issue on Github is [here](https://github.com/llvm/llvm-project/issues/47179).

However, it seems that the issue persists and in some cases TLS behavior isn't preserved, with some other parts (likely loop optimizer?..) messing up with the fix, still resulting in TLS variable address being cached.
Here is the example link showing the issue: https://godbolt.org/z/cz3PPqrcW

cc @ChuanqiXu9 as the implementer of the original fix, maybe you have any thoughts on it?.. Thanks for your work on the issue!

**Comment by ChuanqiXu9** [comment]
There are several optimizations in the compiler will perform the merging. And my previous fix was to disable the optimizations case by case. So the current issue is an oversight that I didn't catch. I sent https://reviews.llvm.org/D151774 for this. Hope we can fix the problem fundamentally in time. Thanks for reporting this.
