### ISSUE TITLE
"[SCCP] Don't mark edges feasible when resolving undefs" combined with function inline lead to segment fault 

### ISSUE THREAD

**Issue by godmiaozi** [llvm/llvm-project#63023]
we have demo.c as following
```C
#include <stdio.h>

int g_print = 1;

void dump_list()
{                                                                                                                                                                                           unsigned int type;

    type = 1<<11;

    if ((g_print & (1 << type)) != 0) {
        printf("need log type=%d\n", type);
    }
}

int main()
{
    printf("before main\n");
    dump_list();

    printf("after main\n");
    return 0;
}
```
command
```bash
./bin/clang -O2 demo.c -o demo
 ./demo
before main
before main
Segmentation fault (core dumped)
``` 
according to the C programming language specification https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1124.pdf
`If the value of the right operand is negative or is
greater than or equal to the width of the promoted left operand, the behavior is undefined`

"1 << 2048" will lead to undefined behavior.
previously this code actually works fine. i have figured out that this "segment fault" is introduced by this commit 1f88d804083a8a1b68df1e6677920e38ab2a6b40(from @nikic)
before this commit the output would be 
```bash
./bin/clang -O2 demo.c -o demo
 ./demo
before main
after main
```
i have taken a quick glance at this modification https://reviews.llvm.org/D126962, it looks like if we have an undef if branch, all the successor of that if branch will be marked as invalid and replaced with unreachable instruction(all the successors actually are eliminated)
i do know that we should not depend on undef behavior, but this modification actually break some old code which used to work "fine", i have the following question
* is that actually what we want? what is the motivation behind?( to simplify the CFG?)
* even we have such undef behavior detected, currently the compiler does not complain any warnings, is it possible to add some warnings to tell the user that we have problematic code here

**Comment by godmiaozi** [comment]
even without function inliner, we still can create some problematic code like
```
#include <stdio.h>

int g_print = 1;

void dump_list()
{                                                                                                                                                                                           unsigned int type;

    type = 1<<11;
    printf("hello\n");
    if ((g_print & (1 << type)) != 0) {
        printf("need log type=%d\n", type);
    }
}

int main()
{
    printf("before main\n");
    dump_list();

    printf("after main\n");
    return 0;
}
```
with command 
```bash
./bin/clang -O2 demo.c -o demo -fno-inline
./demo
```
this will lead to infinite loop
```
hello
before main
hello
before main
hello
before main
hello
before main
hello
before main
hello
before main
hello
before main
hello
before main
hello
before main
```

**Comment by efriedma-quic** [comment]
LLVM optimizations are working as intended: the notion of "undefined behavior" is necessary to allow precisely defining the semantics of LLVM IR.  And branching on poison is undefined.

For the specific behavior of falling through to another function, there's some discussion of preventing that; see https://discourse.llvm.org/t/zero-length-function-pointer-equality/55984 .

We currently have the following options for detecting this sort of issue:

- The clang static analyzer
- UBSan (-fsanitize=undefined)

A warning integrated into normal compilation might be possible, but it's tricky to produce warnings of similar quality to those the static analyzer produces without significantly impacting the performance of the compiler, particularly in more complex cases.
