### ISSUE TITLE
objdump 14.0.3 incorrect disassembly of msr <register, #immediate

### ISSUE THREAD

**Issue by fozog** [llvm/llvm-project#63037]
The opcode "9f 41 00 d5"   is disassembled as  "msr     S0_0_C4_C1_4, xzr" while it should be "msr PAN, #0x1"

See https://developer.arm.com/documentation/ddi0602/2022-12/Base-Instructions/MSR--immediate---Move-immediate-value-to-Special-Register-?lang=en

GNU version properly disassembles the opcode.

I assume this is a problem for all msr <reg>, #imm instructions

How to reproduce:

//create a file msr_imm.s
.text
    msr pan, #1

//compile it with gcc -c msr_imm.s
// disassemble with gnu-objdump -d msr_imm.o -> gives correct disassembly
// disassemble with llvm-objdump -d msr_imm.o -> gives incorrect disassembly

**Comment by EugeneZelenko** [comment]
Could you please try 16 or `main` branch?

**Comment by EugeneZelenko** [comment]
Only 16 is currently maintained.
