### ISSUE TITLE
clang-format 16 doesn't respect BreakAfterAttributes option for constructors

### ISSUE THREAD

**Issue by calcmogul** [llvm/llvm-project#63046]
When the `BreakAfterAttributes` option in clang-format 16 is set to `Always`, it introduces a newline after attributes for member functions, but not for constructors. It seems like it should break after attributes for constructors as well.

Example input in a file called Test.cpp:
```cpp
class Test {
public:
  [[deprecated]] Test(int);

  [[deprecated("msg")]] Test(double);

  [[deprecated]] void Func1();

  [[deprecated("msg")]] void Func2();
};
```

Command:
```bash
clang-format --style="{BreakAfterAttributes: Always}" Test.cpp
```

Expected output:
```cpp
class Test {
public:
  [[deprecated]]
  Test(int);

  [[deprecated("msg")]]
  Test(double);

  [[deprecated]]
  void Func1();

  [[deprecated("msg")]]
  void Func2();
};
```

Actual output:
```cpp
class Test {
public:
  [[deprecated]] Test(int);

  [[deprecated("msg")]] Test(double);

  [[deprecated]]
  void Func1();

  [[deprecated("msg")]]
  void Func2();
};
```

**Comment by calcmogul** [comment]
Here's the commit the option was added in:
https://github.com/llvm/llvm-project/commit/a28f0747c2f3728bd8a6f64f7c8ba80b4e0cda9f

`True if breaking after last attribute group in function return type.` implies that the attribute breaking is tied to the return type, but constructors don't have return types.

**Comment by owenca** [comment]
https://reviews.llvm.org/D157963
