### ISSUE TITLE
clang issue while trying to run clad

### ISSUE THREAD

**Issue by ishaanamahajan** [llvm/llvm-project#63041]
I am trying to use clad, a  C++ library for auto-diff. When I try compile my code using clang, I get the following error - 
![Screenshot from 2023-05-31 17-21-04](https://github.com/llvm/llvm-project/assets/73236968/46e57d97-c60d-4da3-887f-0123c695ced0)

**Comment by EugeneZelenko** [comment]
Could you please try 16 or `main` branch?

**Comment by Endilll** [comment]
Author hasn't got back to us.

**Comment by vgvassilev** [comment]
@ishaanamahajan can you move that issue to the clad repository?

**Comment by ishaanamahajan** [comment]
Will do, sorry for the silence!
