### ISSUE TITLE
[clang code-gen] #pragma FENV_ACCESS leaking across template declarations/definitions

### ISSUE THREAD

**Issue by nicolerabjohn** [llvm/llvm-project#63063]
We have encountered an assertion being hit in codegen relating to `FENV_ACCESS`:

```console
Assertion failed: (CGF.CurFuncDecl == nullptr || CGF.Builder.getIsFPConstrained() || isa<CXXConstructorDecl>(CGF.CurFuncDecl) || isa<CXXDestructorDecl>(CGF.CurFuncDecl) || (NewExceptionBehavior == llvm::fp::ebIgnore && NewRoundingBehavior == llvm::RoundingMode::NearestTiesToEven)) && "FPConstrained should be enabled on entire function", file  clang/lib/CodeGen/CodeGenFunction.cpp, line 163, void clang::CodeGen::CodeGenFunction::CGFPOptionsRAII::ConstructorHelper(clang::FPOptions)()
```

This is reproducible with: 

```cpp
template <class> struct a {
  a(int, char);
  void b() { c() ?: 0; }
  bool c();
};
#pragma STDC FENV_ACCESS ON
void d() {
  a<char> e(1, 'j');
  e.b();
}
```

Basically, as it stands, it looks like when a template is declared under the scope of this pragma being set to one value, and then instantiated under the scope of this pragma being set to another, the value of the pragma at instantiation is taking precedence, which can cause this assertion as well as undefined behaviour when you flip the values. For example, 

```cpp
#pragma STDC FENV_ACCESS ON
template <typename>
int b() {
  int x;
  if ((float)0xFFFFFFFF != (float)0x100000000) {
    x = 1;
  }
  return x;
}
#pragma STDC FENV_ACCESS OFF
int f() { return b<void>(); }
```

exposes the same issue without the assertion being tripped. With `Wuninitialized` on, this shows as "uninitialized". As the definition is under the scope of this pragma being turned on, `FENV_ACCESS` should have the rounding mode set to dynamic, which would lead this expected warning to be "sometimes uninitialized". This proves that the pragma being set above the instantiation is taking precedence rather than the pragma above the definition being preserved. 

FYI @hubert-reinterpretcast

**Comment by hubert-reinterpretcast** [comment]
> #pragma STDC FENV_ACCESS ON
> template <typename>
> int b() {
>   int x;
>   if ((float)0xFFFFFFFF != (float)0x100000000) {
>     x = 1;
>   }
>   return x;
> }
> #pragma STDC FENV_ACCESS OFF
> int f() { return b<void>(); }

It isn't just the warning. As https://godbolt.org/z/xoTa7zWeM shows, the possibility that the rounding mode causes the comparison to fail is reflected in the generated code.

**Comment by hubert-reinterpretcast** [comment]
> Basically, as it stands, it looks like when a template is declared under the scope of this pragma being set to one value, and then instantiated under the scope of this pragma being set to another, the value of the pragma at instantiation is taking precedence

I think it is more accurate to say that the value of the pragma at instantiation is used for some purposes but not others. 

For example, with
```
#include <float.h>
#pragma STDC FENV_ACCESS ON
template <class> float b(float x) { return (float)(x*FLT_MAX)/FLT_MAX; }
#pragma STDC FENV_ACCESS OFF
void d(float x) { b<char>(x); }
```
we see the `FENV_ACCESS ON` being respected: https://godbolt.org/z/7aEEKnqxP

**Comment by rjmccall** [comment]
There's more complexity, but it's consistent with my diagnosis; it just means that some of our representations preserve information separately from the original context while others rely on the pragmas being set.

**Comment by spavloff** [comment]
https://github.com/llvm/llvm-project/issues/64605#issuecomment-1675816150 describes the possible mechanism of the leaking.

**Comment by hubert-reinterpretcast** [comment]
Resolved by https://github.com/llvm/llvm-project/commit/fde5924dcc69fe814085482df259b8cfee236f2c.
