### ISSUE TITLE
[InstCombine] Unsound transform introducing `fshr`: Value mismatch

### ISSUE THREAD

**Issue by fhahn** [llvm/llvm-project#63064]
Running `llvm/test/Transforms/PhaseOrdering/rotate.ll` through Alive2 (with `opt-alive.sh`) shows that InstCombine performs an unsound transformation, after which there is a value mismatch

Reproducer IR for just running Instcombine:

```ll
define i32 @rotl(i32 %a, i32 %b) {
entry:
  %cmp = icmp eq i32 %b, 0
  %sub = sub i32 32, %b
  %shr = lshr i32 %a, %sub
  %shl = shl i32 %a, %b
  %or = or i32 %shr, %shl
  %cond = select i1 %cmp, i32 %a, i32 %or
  ret i32 %cond
}
```

Alive2 Report:

```console
define i32 @rotl(i32 %a, i32 %b) {
%entry:
  %cmp = icmp eq i32 %b, 0
  %sub = sub i32 32, %b
  %shr = lshr i32 %a, %sub
  %shl = shl i32 %a, %b
  %or = or i32 %shr, %shl
  %cond = select i1 %cmp, i32 %a, i32 %or
  ret i32 %cond
}
=>
define i32 @rotl(i32 %a, i32 %b) {
%entry:
  %cond = fshr i32 %a, i32 %a, i32 %b
  ret i32 %cond
}
Transformation doesn't verify! (unsound)
ERROR: Value mismatch

Example:
i32 %a = #x40000000 (1073741824)
i32 %b = #x00000011 (17)

Source:
i1 %cmp = #x0 (0)
i32 %sub = #x0000000f (15)
i32 %shr = #x00008000 (32768)
i32 %shl = #x00000000 (0)
i32 %or = #x00008000 (32768)
i32 %cond = #x00008000 (32768)

Target:
i32 %cond = #x00002000 (8192)
Source value: #x00008000 (32768)
Target value: #x00002000 (8192)
```

**Comment by nikic** [comment]
If I run your example through InstCombine I get a fshl, not fshr: https://llvm.godbolt.org/z/e3dEn9bzd And this is the correct result.

**Comment by nikic** [comment]
@fhahn Ping regarding my previous comment. Could you provide an alive2 link that shows the miscompile?

**Comment by fhahn** [comment]
Hmm, I am not sure what is going on here exactly. When I run the example from https://alive2.llvm.org/ce/z/piJBKr through a locally built `alive-tv`, I get the verification failure above (`fshl` is somehow turned into `fshr`). So this doesn't look like an LLVM bug. 

@nunoplopes do you by any chance have any idea what could cause the difference for a locally built `alive-tv` (using current `master`/ ec5fb3609a63e50ba59d25cf87a9965fa8771d4a)?

**Comment by nunoplopes** [comment]
I assume you mean you only give the `@src` function and let alive-tv run the optimizer by itself?
I tried that with a fresh build and it works fine (i.e., gives the fshl).

This is sounding like a stale build, maybe? Perhaps the id of the intrinsics changed and it's confusing Alive?
Could you try with a fresh build of LLVM + Alive?
(that's the only theory that occured to me)

**Comment by nunoplopes** [comment]
I've just compiled fresh LLVM + Alive2 and I can't repro the issue, sorry.
I get:
```llvm
$ ./alive-tv file.ll

----------------------------------------
define i32 @src(i32 %a, i32 %b) {
%entry:
  %cmp = icmp eq i32 %b, 0
  %sub = sub i32 32, %b
  %shr = lshr i32 %a, %sub
  %shl = shl i32 %a, %b
  %or = or i32 %shr, %shl
  %cond = select i1 %cmp, i32 %a, i32 %or
  ret i32 %cond
}
=>
define i32 @tgt(i32 %a, i32 %b) {
%entry:
  %cond = fshl i32 %a, i32 %a, i32 %b
  ret i32 %cond
}
Transformation seems to be correct!
```

**Comment by nikic** [comment]
Going to close this as not an issue on the LLVM side.
