### ISSUE TITLE
incorrect code action for bugprone-implicit-widening-of-multiplication-result

### ISSUE THREAD

**Issue by scu319hy** [llvm/llvm-project#63070]
I[13:16:13.005] clangd version 16.0.4
I[13:16:13.005] Features: windows

// before fix
```cpp
size_t abc = 128*1024;
```

// fixed
```cpp
size_t abc = static_cast<size_t>(128*)1024;
```

**Comment by HighCommander4** [comment]
cc @LebedevRI as the checker's author. It looks like the source ranges associated with the `FixItHint` are off

**Comment by scu319hy** [comment]
> Can't seem to replicate the issue [here](https://godbolt.org/z/GeE4aKe3e) or locally with clang-tidy 16.0.5. Could you maybe provide a bit more context and check if the issue still happens with the latest version from git?

try this
```bash
clang-tidy main.cpp --export-fixes=fix.yaml
clang-apply-replacements ./
```

**Comment by AMS21** [comment]
Ah yes, with that I was able to reproduce it. It seems that `clang-tidy` refuses to apply overlapping fixits while `clang-apply-replacements` will.

**Comment by AMS21** [comment]
So my best guess is that this [line](https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clang-tidy/bugprone/ImplicitWideningOfMultiplicationResultCheck.cpp#LL106C11-L106C11) is not quite correct.
