### ISSUE TITLE
[mlir] tblgen no member named 'getValue' in 'mlir::OptionalParseResult'

### ISSUE THREAD

**Issue by tschuett** [llvm/llvm-project#63072]
https://github.com/llvm/llvm-project/blob/fb447e7e7c8bbad71032e732b7436fbf7097dd90/mlir/tools/mlir-tblgen/AttrOrTypeDefGen.cpp#L738

```console
: error: no member named 'getValue' in 'mlir::OptionalParseResult'
      if (::mlir::succeeded(parseResult.getValue()))
```

Thanks and follow up issue :-(

**Comment by tschuett** [comment]
I believe this:
https://github.com/llvm/llvm-project/blob/06bb94832d0d9c23b9b4c735007700057aecb93b/mlir/tools/mlir-tblgen/AttrOrTypeDefGen.cpp#L740
should `mlir::Type()`.

**Comment by joker-eph** [comment]
Thanks! Fixed in a6a7a1bae4e99f2a25f6c01ddc40c5c3b37b71f9

**Comment by J-MR-T** [comment]
> https://github.com/llvm/llvm-project/blob/fb447e7e7c8bbad71032e732b7436fbf7097dd90/mlir/tools/mlir-tblgen/AttrOrTypeDefGen.cpp#L738
> 
> ```
> : error: no member named 'getValue' in 'mlir::OptionalParseResult'
>       if (::mlir::succeeded(parseResult.getValue()))
> ```
> 
> Thanks and follow up issue :-(

I have the same issue, when trying to make my dialect extensible (let `isExtensible = 1`).

Manually going in the tblgen-generated `.inc` file and changing the line

```cpp
if (::mlir::succeeded(parseResult.getValue()))
```

to

```cpp
if (::mlir::succeeded(parseResult.value()))
```

solves the issue. Could somebody with commit privileges change this [here](https://github.com/llvm/llvm-project/blob/8a58f0d370b004ec0c8f4af003da6b370f17ff44/mlir/tools/mlir-tblgen/AttrOrTypeDefGen.cpp#L766), @joker-eph perhaps? I don't know the proper process for contributing to LLVM and currently haven't got the time to figure it out. Also, I think a more thorough test of extensible dialects (`TestDialect` doesn't seem to catch this issue) to prevent this from happening again might be good, but I fully understand that's a bit much to ask.

**Comment by joker-eph** [comment]
>  Also, I think a more thorough test of extensible dialects (TestDialect doesn't seem to catch this issue) to prevent this from happening again might be good, 

The TestDialect is extensible, but unfortunately this particular combination also requires `  let useDefaultTypePrinterParser = 1;` and the test dialect has `  let useDefaultTypePrinterParser = 0;`...

**Comment by joker-eph** [comment]
@J-MR-T if you can confirm that d151aa4a0fa26a795466f2171ef9aa29a4e9f131 fixes your issue?

**Comment by J-MR-T** [comment]
> @J-MR-T if you can confirm that [87a1421](https://github.com/llvm/llvm-project/commit/87a14216cd4058154fe59a4031e6fb962ebf0462) fixes your issue?

I'm rebuilding now, thanks for looking at this so quickly! Will update you here asap.

**Comment by J-MR-T** [comment]
Because of another breaking change my project doesn't build completely (my last rebuild was only 12 days ago, sometimes this development pace is a bit exhausting ^^), but the MLIR dialect library does build with `let isExtensible = 1`, so I believe this fixed it. Thank you again :).
