### ISSUE TITLE
ARM Clang: underoptimization: expected vfma.f16, actual vcvtb-vfma.f32-vcvtb

### ISSUE THREAD

**Issue by pmor13** [llvm/llvm-project#63090]
This code:
```
__fp16 mul(__fp16 x, __fp16 y, __fp16 z)
{
    return x * y + z;
}
```
compiled as:
```
clang -O3 -mfpu=fp-armv8 -march=armv8.2-a+fp16
```
produces the following assembler code:
```
mul:
        vmov.f16        s0, r2
        vmov.f16        s2, r1
        vcvtb.f32.f16   s0, s0
        vmov.f16        s4, r0
        vcvtb.f32.f16   s2, s2
        vcvtb.f32.f16   s4, s4
        vfma.f32        s0, s4, s2
        vcvtb.f16.f32   s0, s0
        vmov    r0, s0
        bx      lr
```
Here we see `vcvtb-vfma.f32-vcvtb` while a single `vfma.f16` is expected.

Demo: https://godbolt.org/z/K9hj6GE8d.

**Comment by davemgreen** [comment]
To my understanding - This is how __fp16 is defined, it will convert to float to perform any arithmetic operations. The original __fp16 type was defined as a storage type.

If you use _Float16 instead then you get native operations: https://godbolt.org/z/98sjKMMhr.

See https://clang.llvm.org/docs/LanguageExtensions.html#half-precision-floating-point

**Comment by pmor13** [comment]
@davemgreen Thanks!

Extra: the (documentation)[https://developer.arm.com/documentation/100067/0612/Other-Compiler-specific-Features/Half-precision-floating-point-data-types] says (emphasis added):
> The **IEEE 754-2008 __fp16 data type**, defined in the Arm C Language Extensions.

Searching `__fp16` in IEEE 754-2008 produces nothing.

**Comment by pmor13** [comment]
@davemgreen I am lost. The documentation from your links says (empassis added):
> `__fp16` is supported on all targets. The special semantics of this type mean that **no arithmetic is ever performed directly on `__fp16` values**

This code:
```__fp16 mul(__fp16 x, __fp16 y)
{
    return x * y;
}
```
compiled as `clang -O3 -march=armv8.2-a+fp16 -S` produces this assembler code:
```
mul:
        vmov.f16        s0, r1
        vmov.f16        s2, r0
        vmul.f16        s0, s2, s0
        vmov    r0, s0
        bx      lr
```
Demo: https://godbolt.org/z/aodM7Wv9W.

Here we see `vmul.f16`, which is "arithmetic is ever performed directly on `__fp16` values". Hence, the actual clang behavior contradicts with the documentation.

Or do I miss something?

**Comment by davemgreen** [comment]
By adding -O0 to the godbolt link you can see that clang is emitting fptrunc(fmul(fpext, fpext)). https://godbolt.org/z/z5nfz6fqG

But there is a part of instcombine that then removes the fptrunc/fpext as an optimization, as it believes them to be equivalent without the extends: https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp#L1687

(Which I believe is a valid transform, even if it would take some time for alive to prove it: https://alive2.llvm.org/ce/z/sYocB-)

**Comment by pmor13** [comment]
@davemgreen 
> as it believes them to be equivalent without the extends
As I recall, `half->float->op->float->half` does not always produce the same result as `half->op->half`. The difference in result may be +/-1 (last) bit. Hence, _why_ it believes them to be equivalent without the extends?

**Comment by pmor13** [comment]
@davemgreen Re: "fmul between f16 and f32 should be OK": indeed, thanks! Yesterday I retested add / sub / mul / div: w/ and w/o promotion / demotion to `float` and all of these are OK. Due to "one year passed since my last experience with FP" I've confused the things.
