### ISSUE TITLE
[InstSimplify] (a ^ b) ? (~a) ^ b : a ^ (~b)

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#63104]
Test code:
```c
int foo(int a, int b)
{
    return (a ^ b) ? (~a) ^ b : a ^ (~b) ;
}

```

Clang 15.0.0 (and Gcc trunk)
```asm
foo(int, int):                               # @foo(int, int)
        mov     eax, edi
        xor     eax, esi
        not     eax
        ret
```

Clang 16.0.0 (and Clang trunk)
```asm
foo(int, int):                               # @foo(int, int)
        mov     ecx, edi
        xor     ecx, esi
        cmp     edi, esi
        not     ecx
        mov     eax, -1
        cmovne  eax, ecx
        ret
```

https://godbolt.org/z/qdhKnj3af

**Comment by dc03** [comment]
I'd like to fix this, but I'm not sure where I should look. It appears that the newer clang is converting `a ^ (~b)` into `0 ^ (-1)` (which then gets folded into `-1`), possibly because it is able to prove that `a ^ b` being false means that `a` and `b` are equal. The older clang appears to be converting `a ^ (~b)` as well as `(~a) ^ b` into `~(a ^ b)`, then coalescing them leading to the codegen you see.

**Comment by dc03** [comment]
> This probably needs a generalization of simplifyWithOpReplaced to look at more than one instruction.

@nikic: Not entirely sure where this plays in. Stepping through the code, the transformation comes from [here](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Analysis/InstructionSimplify.cpp#L766): `a ^ ~b` gets turned into `a ^ (b ^ -1)` which then gets reassociated by `SimplifyAssociativeOrCommutative` [here](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp#L491) to be `(a ^ b) ^ -1`, where `a ^ b` then gets transformed by `simplifyByDomEq` into `0`. I don't see `simplifyWithOpReplaced` in the call stack at any point.

**Comment by nikic** [comment]
@dc03 The optimization regression comes from making use of dominating conditions in icmp simplification. However, we don't want to avoid that and instead make sure that the new IR can still be simplified. simplifyWithOpReplaced() is the transform that handles this kind of pattern.

**Comment by vfdff** [comment]
The regression between **llvm 15** and **llvm 16** , https://gcc.godbolt.org/z/Goq9ETh67

**Comment by vfdff** [comment]
maybe this is the simplify case **https://alive2.llvm.org/ce/z/TGgJTq** , show that the simplifyWithOpReplaced need look at more than one instruction.
