### ISSUE TITLE
Bounds check is not eliminated `ssize` vs `size`

### ISSUE THREAD

**Issue by Kojoley** [llvm/llvm-project#63126]
```cpp
#define _GLIBCXX_ASSERTIONS
#include <vector>

void foo(std::vector<double> &vec)
{
   auto count = ssize(vec);
   for (decltype(count) i = 0; i < count; ++i)
     vec[i] += 1;
}
```
`-mllvm -enable-constraint-elimination` does not help.
With `size` instead of `ssize` bounds check is eliminated.
https://godbolt.org/z/f5Gn9eKrc

**Comment by fhahn** [comment]
To catch this in constraint-elimination, we need to use the info that the phi node will always be signed positive (due to the increment not wrapping). Looking.

**Comment by fhahn** [comment]
Put up PR (#72879) to solve this in Constraintelimination, but this is now also handled by IndVarSimplify
