### ISSUE TITLE
Bounds check is not eliminated `i != count` vs `i < count`

### ISSUE THREAD

**Issue by Kojoley** [llvm/llvm-project#63125]
```cpp
#define _GLIBCXX_ASSERTIONS
#include <vector>

void foo(std::vector<double> &vec)
{
   auto count = size(vec);
   for (decltype(count) i = 0; i != count; ++i)
     vec[i] += 1;
}
```
`-mllvm -enable-constraint-elimination` does not help.
With `i < count` bounds check is eliminated.
https://godbolt.org/z/s6Gbsqvor

**Comment by fhahn** [comment]
Working on a patch to ConstraintElimination to handle this.

**Comment by fhahn** [comment]
Patch for the pointer induction case is here: https://reviews.llvm.org/D152730 

I will share a follow-on patch for the integer case soon.

**Comment by nikic** [comment]
It looks like IndVars does usually handle this, but in this case fails because the "trip count is not zero" condition ends up being expressed as a pointer comparison:
```
  %0 = load ptr, ptr %_M_finish.i.i, align 8
  %1 = load ptr, ptr %vec, align 8
  %sub.ptr.lhs.cast.i.i = ptrtoint ptr %0 to i64
  %sub.ptr.rhs.cast.i.i = ptrtoint ptr %1 to i64
  %sub.ptr.sub.i.i = sub i64 %sub.ptr.lhs.cast.i.i, %sub.ptr.rhs.cast.i.i
  %sub.ptr.div.i.i = ashr i64 %sub.ptr.sub.i.i, 3
  %cmp.not10 = icmp eq ptr %0, %1
  br i1 %cmp.not10, label %for.cond.cleanup, label %for.body
```
If this were
```
  %cmp.not10 = icmp eq i64 %sub.ptr.div.i.i, 0
```
it would work.

**Comment by fhahn** [comment]
Restructured https://reviews.llvm.org/D152730 so the motivating case can be handled in combination with  https://reviews.llvm.org/D158776


Also see #64881

**Comment by fhahn** [comment]
This should be fixed now! Please keep filing issues for any cases LLVM is still not able to simplify.
