### ISSUE TITLE
Possible wrong-code on -O2 and above (affecting LLVM 12.0.1 downward versions)

### ISSUE THREAD

**Issue by haoxintu** [llvm/llvm-project#63121]
Hi, the following code makes LLVM 12.0.1 downward versions behave differently. It might be an issue in LLVM's optimization, can you take a look, please?

```
#include <stdint.h>
#include <stdio.h>
int8_t a = 0, j=0, b=0;
int ids = 0;
void __attribute__((noinline)) marker_1() {
    printf(" b%db ", 1);
    ids ++;
}
int8_t *c(uint32_t, uint16_t);
void d();
int16_t e(uint8_t, int8_t *, uint32_t);
uint32_t f() {
  int8_t g[1][10] = {0,0,0,0,0,0,0,0,0,0};
  d();
  c(g[0][2], g[0][8]);
  return 0;
}
int8_t *c(uint32_t h, uint16_t i) {
  marker_1();
  return &b;
}
void d() {
  int m = 0;
  for (; m <= 5; m++)
    e(0, &a, 0);
}
int16_t e(uint8_t k, int8_t *l, uint32_t o) {
  for (; j;)
  n:;
    goto n;
}
int main() { 
    f(); 
    printf("%d\n", ids); 
}
```
$clang-trunk -w -O2 test.c ; ./a.out
(output nothing)
$clang-12.0.1 -w -O2 test.c ; ./a.out
 b1b 1
$clang-12.0.1 -w -O1 test.c ; ./a.out
(hang)

$clang-trunk -v
clang version 16.0.0 (https://github.com/llvm/llvm-project bf6f82a9df6a1693a5399039dcadd7fc00dab65e)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/haoxin/haoxin-data/compilers/llvm-project/build/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/lib/cuda, version 

Code on GodBolt: https://godbolt.org/z/Wsh6Thd5v

Thanks,
Haoxin

**Comment by efriedma-quic** [comment]
I think your program has an infinite loop.  We treat infinite loops as undefined behavior by default; pass -fno-finite-loops to override that.

**Comment by haoxintu** [comment]
> I think your program has an infinite loop. We treat infinite loops as undefined behavior by default; pass -fno-finite-loops to override that.

Hi @efriedma-quic, thanks for your feedback. I can understand the infinite loops are undefined behaviors in C11. But as for C99, is it should not be treated as undefined? LLVM still removes it under C99: https://godbolt.org/z/356dz4qK7

Please also kindly check the relevant discussion on the GCC side: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94392

Thanks,
Haoxin

**Comment by haoxintu** [comment]
Another case has the same issue that LLVM removes the infinite loop in C99:

```
#include <stdint.h>
#include <stdio.h>
uint64_t a, f, d;
int32_t b;
int ids = 0;
int32_t *c[][1][1] = {{{0}}};
int32_t ***e;
void __attribute__((noinline)) marker_1() { printf(" b%db ", 1); ids++;}
int16_t g(int16_t, int32_t **const *, uint8_t, int16_t);
int16_t h(int32_t ***, uint64_t, int8_t, int32_t *, int32_t **);
int32_t *i(uint16_t, uint32_t, int64_t);
int32_t *j(int32_t **, uint16_t);
int16_t k() {
  int16_t l = 0;
  int32_t *m = &b;
  g(h(0, 0, d, m, &c[0][0][0]), e, b, a);
  marker_1();
  return l;
}
int16_t g(int16_t n, int32_t **const *a, uint8_t o, int16_t p) {
  i(n, b, 0);
  return o;
}
int16_t h(int32_t ***b, uint64_t q, int8_t r, int32_t *s, int32_t **t) {
  return q;
}
int32_t *i(uint16_t u, uint32_t v, int64_t w) {
  uint16_t x = f;
  j(0, x);
  return 0;
}
int32_t *j(int32_t **y, uint16_t z) {
  int32_t aa = 5;
ab:
  aa ^= 1;
  if (aa)
    goto ab;
  return 0;
}
int main() { k(); printf("%d\n", ids);}

```

**Comment by efriedma-quic** [comment]
> LLVM still removes it under C99: https://godbolt.org/z/356dz4qK7

That's using clang 11.  If I change it to use a newer compiler, it appears to work as expected.

**Comment by haoxintu** [comment]
> > LLVM still removes it under C99: https://godbolt.org/z/356dz4qK7
> 
> That's using clang 11. If I change it to use a newer compiler, it appears to work as expected.

Yeah, I know. I mean can it be an issue on Clang 11? Or we don't have a plan to fix it on Clang-11 because the version is relatively old? Thanks.

**Comment by efriedma-quic** [comment]
We don't do patch releases for releases older than the latest release, so we don't track issues on old releases.

**Comment by haoxintu** [comment]
> We don't do patch releases for releases older than the latest release, so we don't track issues on old releases.

Well noted. Thanks again for your time and help.
