### ISSUE TITLE
Backport GCC 13 `__is_convertible` fix (484e64f7e7b2c0494d7b2dbfdd528bcd707ee652) to 16.x

### ISSUE THREAD

**Issue by thesamesam** [llvm/llvm-project#63133]
Please consider backporting 484e64f7e7b2c0494d7b2dbfdd528bcd707ee652 to fix `__is_convertible` in libcxx headers with GCC 13. We hit this downstream in Gentoo at https://bugs.gentoo.org/907895 and FreeBSD seems to have as well.

This is for https://github.com/llvm/llvm-project/issues/62396.

/cherry-pick 484e64f7e7b2c0494d7b2dbfdd528bcd707ee652

**Comment by philnik777** [comment]
I don't think it makes sense to backport this. There are other incompatibilities with GCC13 which haven't been resolved yet, so this won't actually fix much.

**Comment by thesamesam** [comment]
If so, that's alright then. We did end up having two reports (in the same day) in Gentoo for this and there's already been one dupe filed in LLVM though. Could you point me to the other bugs so I can keep an eye on them and direct folks to them?

**Comment by philnik777** [comment]
I don't think there are any bugs filed, but D151387 is currently the blocking patch. I'll try to work on it soon, so we can fix any other problems.

**Comment by philnik777** [comment]
Closing this, since there is nothing to backport to anymore. (Sorry, I didn't have time to get GCC 13 fixed yet. I hope to get it done for LLVM17.)

**Comment by hypdeb** [comment]
Is there a matrix of which compiler can be used to compile which version of LLVM and its sub-projects ? I've tried with GCC 11 and it didn't work, now with 13 I could compile clang, but cannot compile libc++.
