### ISSUE TITLE
improve diagnostic for * vs & confusion

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#6313]
|  |  |
| --- | --- |
| Bugzilla Link | [5941](https://llvm.org/bz5941) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor,@jryans |

## Extended Description 
Consider:

class A;
void f0(A *a);
void f1(A &a);
void f2(A *a) {
  f1(a);
}
void f3(A &a) {
  f0(a);
}

We produce:
t.cc:7:3: error: no matching function for call to 'f1'
  f1(a);
  ^~
t.cc:4:6: note: candidate function
void f1(A &a);
     ^
t.cc:11:3: error: no matching function for call to 'f0'
  f0(a);
  ^~
t.cc:3:6: note: candidate function
void f0(A *a);
     ^

In addition to producing a better error message for this common issue, it would be really nice to produce a fixit that ass a & or *.

This is AKA rdar://7113438

**Comment by arsenm** [comment]
Linked patch was committed
