### ISSUE TITLE
clang-format option InsertNewlineAtEOF does not add newline

### ISSUE THREAD

**Issue by jasonfsmitty** [llvm/llvm-project#63150]
On Fedora 36, running a local build from source of LLVM 16.0.4

The clang format option `InsertNewlineAtEOF : true` is not being applied, instead the newline is being removed:

```
[smithj1]$ /opt/llvm-16.0.4/bin/clang-format --version
clang-format version 16.0.4
[smithj1]$ printf "namespace aaa {}\n\n"
namespace aaa {}

[smithj1]$ printf "namespace aaa {}\n\n" | /opt/llvm-16.0.4/bin/clang-format --style="{ InsertNewlineAtEOF : true }"
namespace aaa {}
[smithj1]$ printf "namespace aaa {}\n\n" | /opt/llvm-16.0.4/bin/clang-format --style="{ InsertNewlineAtEOF : false }"
namespace aaa {}
[smithj1]$
```

This also happens in our codebase, where we leverage .clang-format files to auto-format sections of our repo:

```
[smithj1]$ grep NewlineAtEOF .clang-format 
InsertNewlineAtEOF: true
[smithj1]$ cat test.cpp 
#include <iostream>

int main(int argc, char* argv[])
{
	std::cout << "Hello World" << std::endl;
	return 0;
}

[smithj1]$ /opt/llvm-16.0.4/bin/clang-format --style=file -Werror test.cpp 
#include <iostream>

int main(int argc, char* argv[])
{
	std::cout << "Hello World" << std::endl;
	return 0;
}
[smithj1]$
```

One counter-point that I can't explain, is that clang-format _does_ format properly when using plugins in VS Code and vim.

For vim, I'm using the [vim-clang-format](https://github.com/rhysd/vim-clang-format) plugin, with the following in `.vimrc`:

```
let g:clang_format#command = "/opt/llvm-16.0.4/bin/clang-format"
let g:clang_format#auto_format = 1
let g:clang_format#detect_style_file = 1
let g:clang_format#auto_filetypes = [ "c", "cpp" ]
let g:clang_format#enable_fallback_style = 0
```

If I open a file and save it with vim, it formats the file correctly including adding the newline at EOF.

**Comment by owenca** [comment]
> On Fedora 36, running a local build from source of LLVM 16.0.4
> 
> The clang format option `InsertNewlineAtEOF : true` is not being applied, instead the newline is being removed:
> 
> ```
> [smithj1]$ /opt/llvm-16.0.4/bin/clang-format --version
> clang-format version 16.0.4
> [smithj1]$ printf "namespace aaa {}\n\n"
> namespace aaa {}
> 
> [smithj1]$ printf "namespace aaa {}\n\n" | /opt/llvm-16.0.4/bin/clang-format --style="{ InsertNewlineAtEOF : true }"
> namespace aaa {}
> [smithj1]$ printf "namespace aaa {}\n\n" | /opt/llvm-16.0.4/bin/clang-format --style="{ InsertNewlineAtEOF : false }"
> namespace aaa {}
> [smithj1]$
> ```

[InsertNewlineAtEOF](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#insertnewlineateof) inserts a newline only if the input doesn't end with one:
```
$ printf "namespace aaa {}"
namespace aaa {}$ printf "namespace aaa {}" | clang-format -style='{InsertNewlineAtEOF: true}'
namespace aaa {}
$ printf "namespace aaa {}\n"
namespace aaa {}
$ printf "namespace aaa {}\n" | clang-format -style='{InsertNewlineAtEOF: true}'
namespace aaa {}
$ 
```
It seems that clang-format always removes empty lines at the end of the input. Please file another issue if you believe it shouldn't.

**Comment by owenca** [comment]
https://reviews.llvm.org/D152305
