### ISSUE TITLE
Clang frontend C++ crash when using automatic variables directly in `noexcept` of generic lambda

### ISSUE THREAD

**Issue by MitalAshok** [llvm/llvm-project#63167]
Compiler explorer link: https://godbolt.org/z/74bErMhEs

Compiling this crashes the compiler:

```c++
// clang++ -std=c++20 -fsyntax-only
struct true_type { constexpr operator bool() const { return true; } };

constexpr auto f() {
    true_type i;
    return [=](auto) noexcept(i) -> bool {
        return true;
    };
}

// static_assert(f()(0));
static_assert(requires { { f()(0) }; });  // Or any use in an unevaluated context, like `static_assert(decltype(f()(0))(true))`
```

Some notes:

 * Uncommenting the first `static_assert` makes this work.
 * Removing the trailing return type `-> bool` also makes this work
 * Without the capture-default `[=]`, this doesn't compile complaining that "`i` can't be implicitly captured" even though `i` isn't odr-used
 * Making it a non-generic lambda (e.g., replacing the `auto` with `int`) removes the need for `[=]` and causes this not to crash.

**Comment by shafik** [comment]
Confirmed: 

Assertion:

```console
```

**Comment by shafik** [comment]
looks fixed in trunk: https://godbolt.org/z/7q7Gdx5a8
