### ISSUE TITLE
Add qsort_r/s to llvm-libc

### ISSUE THREAD

**Issue by PiJoules** [llvm/llvm-project#63171]
It would be nice if these were shipped alongside qsort. Projects like boringssl which has a lot of different types of comparator functions could use this to avoid function type mismatches for comparator functions whose arguments aren't specifically `const void *`.

**Comment by michaelrj-google** [comment]
I'm going to add `qsort_r` since we don't have the `_s` runtime constraint handler set up yet.

**Comment by michaelrj-google** [comment]
This patch will add qsort_r: https://reviews.llvm.org/D152467

**Comment by michaelrj-google** [comment]
With https://reviews.llvm.org/D152467 landed, qsort_r has been added.
