### ISSUE TITLE
requires-claused ignored on lambda closures appearing in templated functions

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#63181]
[GCC test `concepts-lambda19` compiles when it shouldn't](https://godbolt.org/z/cjaKdKTcY).
```cpp
// PR c++/103706
// RUN: %clang_cc1 -std=c++20 -fsyntax-only -verify %s

template<class T> concept C = __is_same(T, int);

template<class... Ts> void f() {
  ([]() requires C<Ts> { return Ts(); }(), ...); // this expands to C<char> for the second one, which is false
}

template void f<int, int, int>();
template void f<int, int, char>();
```

Note that this also happens with
```cpp
int main()
{
  f<int, int, char>();
}
```

**Comment by cor3ntin** [comment]
I've reduced it further to

```cpp
template<class T> void f() {
  ([]() requires false { }());
}

template void f<int>();
```

We seem to ignore the requires-clause because the lambda is not generic, even if per [temp.pre], the closure is a templated entity.

**Comment by cor3ntin** [comment]
I track it down to something which I think is a core issue - https://github.com/cplusplus/CWG/issues/351 
It think I can fix it without waiting for core though.

**Comment by cor3ntin** [comment]
Fix https://reviews.llvm.org/D154368
