### ISSUE TITLE
clang bug openmp num_threads() if(false)

### ISSUE THREAD

**Issue by jakub-homola** [llvm/llvm-project#63197]
Hello,

I am having an issue when using OpenMP with Clang. Using the `num_threads(3)` and `if(false)` clauses somehow propagates the number of threads to the next parallel region.

The reproducer code (below) contains only 4 parallel regions, in which a single thread prints the number of threads running in the parallel region. The second parallel region uses the `num_threads(3)` and `if(false)` clauses.

As you can see in the output of the program (below), the first parallel region is correctly launched with 64 threads (`AAA 64`). The second parallel region uses the `num_threads(3)` and `if(false)` clauses, and is launched with only a single thread (`BBB 1`), which is expected because of the `if(false)`. The following parallel region should be again launched with 64 threads, but as you can see, it is launched with only 3 threads (`CCC 3`), which is weird. The last parallel region is then correctly launched with 64 threads (`DDD 64`).

If I remove the `if(false)` clause, the program works as expected.

If I use e.g. `num_threads(32)` on CCC parallel region, it is launched as expected with 32 threads - the program works as expected.

Using G++, the program works as expected.

I am almost certain this is a bug, and I would appreciate if it was fixed.

I was primarily testing with Clang version 13.0.1 on a CentOS 7 machine, with Clang 16.0.0 on Ubuntu 18.04 I observe the same weird behavior. If you need more details, please ask.

Thanks,

Jakub

-----

The reproducer code:
```cpp
#include <cstdio>
#include <omp.h>

int main()
{
    #pragma omp parallel
    #pragma omp single
    {
        printf("AAA %2d\n", omp_get_num_threads());
    }

    #pragma omp parallel num_threads(3) if(false)
    #pragma omp single
    {
        printf("BBB %2d\n", omp_get_num_threads());
    }

    #pragma omp parallel
    #pragma omp single
    {
        printf("CCC %2d\n", omp_get_num_threads());
    }

    #pragma omp parallel
    #pragma omp single
    {
        printf("DDD %2d\n", omp_get_num_threads());
    }

    return 0;
}
```

Compile with:
```shell
clang++ -g -fopenmp source.cpp -o program.x
```

Expected output:
```console
AAA 64
BBB  1
CCC 64
DDD 64
```

Observed output:
```console
AAA 64
BBB  1
CCC  3
DDD 64
```

**Comment by jakub-homola** [comment]
I realized this issue actually is not related to nested openmp and also appears with simple parallel region, so I edited the original post and the title to reflect that (and make it simpler).

**Comment by shiltian** [comment]
I can consistently observe this issue.
