### ISSUE TITLE
[clang/c++ bug] Clang fails to compare simple struct values

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#63201]
Testcase:
```cpp
struct Pt {
        float x;
        float y;
};

bool e(const Pt &pt) {
        return pt == Pt{1.f, 1.f}; // fails: error: invalid operands to binary expression ('const Pt' and 'Pt')
        //return pt == (const Pt)Pt{1.f, 1.f}; // fails: error: invalid operands to binary expression ('const Pt' and 'const Pt')
}
```

Both above lines fail.

A simple structure value should be comparable using the default `operator==` that should be auto-generated for `Pt`.

Clang 15.0.7
Clang 16.0.4
FreeBSD 13.2

**Comment by shafik** [comment]
Note this fails for gcc/MSVC as well: https://godbolt.org/z/jq8r7xhEx

We don't get a default `operator==` implicitly but in C++20 we can default it:

```cpp
bool operator==(const Pt&) const = default;
```

godbolt example: https://godbolt.org/z/nzjas9636
