### ISSUE TITLE
ninja -C build check-llvm fails in Kaleidoscope tests

### ISSUE THREAD

**Issue by Philius** [llvm/llvm-project#63204]
Operating system: Debian Bookworm AMD64
Memory: 16 GB
Swap: 33.554428 GB

I ran CMake as follows:
```shell
cmake -S llvm -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_BUILD_EXAMPLES=1 -DLLVM_PARALLEL_LINK_JOBS=1 -DLLVM_PARALLEL_COMPILE_JOBS=16
```

Then
```shell
ninja -C build check-llvm
```

It fails:
```console
********************
Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
********************
Failed Tests (4):
  LLVM :: Examples/Kaleidoscope/Chapter4.test
  LLVM :: Examples/Kaleidoscope/Chapter5.test
  LLVM :: Examples/Kaleidoscope/Chapter6.test
  LLVM :: Examples/Kaleidoscope/Chapter7.test
```
So it's either a problem with the tests or the programs.
There's no point looking deeper until someone else can reproduce these results.

**Comment by nikic** [comment]
Some time ago @weliveindetail tracked this down to `-fno-lifetime-dse` getting enabled. There is a patch to fix this at https://reviews.llvm.org/D107087.

**Comment by Philius** [comment]
But I'm not using MSVC - I'm in g++ land.
Let me know when a patch arrives in master.

**Comment by nikic** [comment]
Yes, the issue now also exists with GCC.

It may make sense to disable the kaleidoscope tests by default until this is fixed.

**Comment by Philius** [comment]
The kaleidoscope tests wrap the kaleidoscope programs.
At least on my system, the programs fail with a segfault.
I didn't (directly) enable the kaleidoscope tests, I enabled building the examples, which apparently enabled the tests.

**Comment by weliveindetail** [comment]
Should be fixed on mainline with 9ce06411994e9bcaa98c219c7dc34c2824353a81 @Philius does it work for you now?

**Comment by Philius** [comment]
I did a `git pull --rebase`, then a `git reset --hard HEAD` then the steps above.
Here's what I eventually got:
```
[4013/4014] Running the LLVM regression tests

Testing Time: 356.16s
  Skipped          :    15
  Unsupported      :   731
  Passed           : 53555
  Expectedly Failed:   164
```
Running `build/bin/Kaleidoscope-Ch4` presents "ready>" so no segfault.
Looks like it's fixed!

**Comment by nikic** [comment]
Thanks for confirming!
