### ISSUE TITLE
Absolute build paths appear when pretty printing the name of template function with lambda parameter

### ISSUE THREAD

**Issue by dankm** [llvm/llvm-project#63219]
When expanding `__PRETTY_FUNCTION__` (or any use of pretty printing of a function name, `std::source_location` for example), and a lambda appears in a template parameter for a template the real path to the file containing the lambda appears in the output.

This is similar to #62192.

```console
$ cat /tmp/lambdatest.cc
#include <iostream>

template<typename f>
void lambdatest(f&& cb) {
std::cout << __PRETTY_FUNCTION__ << std::endl;
}

int main() {
std::cout << __PRETTY_FUNCTION__ << std::endl;

auto lt = []() -> auto {
return __PRETTY_FUNCTION__;
};

std::cout << lt() << std::endl;
lambdatest(lt);

return 0;
}
$ clang++ -ffile-prefix-map=/tmp=/foo -o lambdatest /tmp/lambdatest.cc
$ ./lambdatest
int main()
auto main()::(anonymous class)::operator()() const
void lambdatest(f &&) [f = (lambda at /tmp/lambdatest.cc:11:13) &]
```
expected:
```console
int main()
auto main()::(anonymous class)::operator()() const
void lambdatest(f &&) [f = (lambda at /foo/lambdatest.cc:11:13) &]
```

**Comment by dankm** [comment]
@kraj I noticed this with meta-clang building cmake.

**Comment by dankm** [comment]
I have a work-in-progress fix at https://github.com/dankm/llvm-project/tree/template-remapping, that seems to fix it. I'll add release notes, a unit test (more-or-less) the one above, and submit a real review.

**Comment by kraj** [comment]
> @kraj I noticed this with meta-clang building cmake.

I have seen it too with some packages.

**Comment by dankm** [comment]
I've added a phabricator review: https://reviews.llvm.org/D152570
