### ISSUE TITLE
MSVC permits type aliases in elaborated-type-specifier

### ISSUE THREAD

**Issue by RIscRIpt** [llvm/llvm-project#63217]
As far as I can understand (draft of) C++ standard, [elaborated-type-specifier](https://eel.is/c++draft/dcl.type.elab#nt:elaborated-type-specifier) prohibits usage of type aliases:
> If the [identifier](https://eel.is/c++draft/lex.name#nt:identifier) or [simple-template-id](https://eel.is/c++draft/temp.names#nt:simple-template-id) resolves to a [typedef-name](https://eel.is/c++draft/dcl.typedef#nt:typedef-name) ([[dcl.typedef]](https://eel.is/c++draft/dcl.typedef), [[temp.names]](https://eel.is/c++draft/temp.names)), the [elaborated-type-specifier](https://eel.is/c++draft/dcl.type.elab#nt:elaborated-type-specifier) is ill-formed[.](https://eel.is/c++draft/dcl.type.elab#5.sentence-3)

So the following code is ill-formed:
```cpp
struct X {};
struct Y {
    using Z = X;
    friend struct Z;
    friend class Z;
    struct Z;
    class Z;
    enum Z;
};
```

However, MSVC accepts it 🤷‍♂️. Compiler explorer example: ([link](https://godbolt.org/z/vjWd1cn6K))

Context: Boost 1.68 has the following code, which cannot be compiled using `clang-cl`
```cpp
#if defined(BOOST_MSVC)
/*===========================================================================*/
#define BOOST_BIMAP_MAP_VIEW_BASE_FRIEND(TYPE,TAG,BIMAP)                      \
    typedef ::boost::bimaps::detail::map_view_base<                           \
        TYPE<TAG,BIMAP>,TAG,BIMAP > friend_map_view_base;                     \
    friend class friend_map_view_base;
/*===========================================================================*/
#else
/*===========================================================================*/
#define BOOST_BIMAP_MAP_VIEW_BASE_FRIEND(TYPE,TAG,BIMAP)                      \
    friend class ::boost::bimaps::detail::map_view_base<                      \
        TYPE<TAG,BIMAP>,TAG,BIMAP >;
/*===========================================================================*/
#endif
```

Upstream bug-report to MSVC team: https://developercommunity.visualstudio.com/t/elaborated-type-specifier-permits-type-a/10388512
Related issue: #29595

---

I suppose supporting ridiculous code with different tags is unacceptable even in MSVC-compatible mode:
```cpp
    friend class Z;
    struct Z;
    class Z;
    enum Z;
```

However... Is it okay for MSVC-compatible mode to support syntax, which _seems_ valid:
```cpp
struct X {};
struct Y {
    using Z = X;
    friend struct Z;
};
```

**Comment by shafik** [comment]
Unfortunately it looks like gcc/MSVC are inconsistent here, see: https://github.com/llvm/llvm-project/issues/41470

In the templated case they do the opposite that they do in this case. I would say this is an MSVC bug and we would not want to support this.

CC @AaronBallman for second opinion

**Comment by AaronBallman** [comment]
Yeah, everyone does something different here, but it seems that only Clang is following the language rule strictly: https://godbolt.org/z/oo8rzd54d Given the landscape of implementations, I think Clang's behavior is the most defensible, especially given that all compilers accept the well-formed version of the code (so it should be possible for boost to correct the friend declaration).

I can't find any documentation for GCC or MSVC that suggest they intend to support this; if some exists though, that would be compelling.

**Comment by RIscRIpt** [comment]
Well, even Microsoft docs [mention](https://learn.microsoft.com/en-us/cpp/cpp/friend-cpp) this case:
> Use friend F to declare a typedef as friend:
> ```cpp
>    class Foo {};
>    typedef Foo F;
>
>    class G
>    {
>        friend F; // OK
>        friend class F; // Error C2371 -- redefinition
>    };
> ```

https://godbolt.org/z/xKa8j5Y5o however, the bug appears (and error disappears), when we move `typedef` into the `class`: https://godbolt.org/z/E4xEs3Kzb

> I would say this is an MSVC bug and we would not want to support this.

Sounds reasonable.

Closing.
