### ISSUE TITLE
v_mad_u64_u32 patterns do not import in globalisel 

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#63216]
```console
Included from /home/matt/src/llvm-project/llvm/lib/Target/AMDGPU/AMDGPU.td:1908:
Included from /home/matt/src/llvm-project/llvm/lib/Target/AMDGPU/SIInstrInfo.td:2972:
Included from /home/matt/src/llvm-project/llvm/lib/Target/AMDGPU/SIInstructions.td:28:
Included from /home/matt/src/llvm-project/llvm/lib/Target/AMDGPU/VOPInstructions.td:1485:
/home/matt/src/llvm-project/llvm/lib/Target/AMDGPU/VOP3Instructions.td:661:3: warning: Skipped pattern: Could not infer class for EXTRACT_SUBREG operand #0
  def : GCNPat <
  ^
Included from /home/matt/src/llvm-project/llvm/lib/Target/AMDGPU/AMDGPU.td:1908:
Included from /home/matt/src/llvm-project/llvm/lib/Target/AMDGPU/SIInstrInfo.td:2972:
Included from /home/matt/src/llvm-project/llvm/lib/Target/AMDGPU/SIInstructions.td:28:
Included from /home/matt/src/llvm-project/llvm/lib/Target/AMDGPU/VOPInstructions.td:1485:
/home/matt/src/llvm-project/llvm/lib/Target/AMDGPU/VOP3Instructions.td:682:10: note: instantiated from multiclass
  defm : IMAD32_Pats<V_MAD_U64_U32_e64>;
         ^
```

I'm assuming GlobalISel emitter is getting confused by the 2 outputs on the `v_mad_u64_u32`, and the extract type should just infer it from the first result.

Additionally the combiner needs to implement the reassociation from f02510e432e2c452e85a2b7450a8588d0f3c526a

**Comment by Pierre-vh** [comment]
@bjope Is it okay if I pick up https://reviews.llvm.org/D86617 or can you restart a PR for it? I believe it'd be needed for this.

**Comment by Pierre-vh** [comment]
@arsenm f02510e432e2c452e85a2b7450a8588d0f3c526a does not exist, do you remember what this was referring to?

**Comment by arsenm** [comment]
> @arsenm f02510e432e2c452e85a2b7450a8588d0f3c526a does not exist, do you remember what this was referring to?

Maybe c01f284fbbf4c93c65b1f92fb8b3d263afb796c0?

**Comment by bjope** [comment]
> @bjope Is it okay if I pick up https://reviews.llvm.org/D86617 or can you restart a PR for it? I believe it'd be needed for this.

Sure, I can create a PR for it (or I can just push it if it looks ok). Tthe phabricator review has been ongoing for 3.5 years so I hope it will be worth the effort to open a new review :-)

**Comment by Pierre-vh** [comment]
There were some changes to GISel infrastructure so I think a PR is needed but I'll review it ASAP :)

**Comment by bjope** [comment]
> There were some changes to GISel infrastructure so I think a PR is needed but I'll review it ASAP :)

Here it is https://github.com/llvm/llvm-project/pull/81130
(I just rebased it and pushed for review, so I did not really verify check-all result before I pushed it for review.. I need to rebuild first to see if there are any new test cases that are impacted)
