### ISSUE TITLE
Unknown pragmas not ignored with -Wunknown-pragmas

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#6323]
|  |  |
| --- | --- |
| Bugzilla Link | [5951](https://llvm.org/bz5951) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @chandlerc |

## Extended Description 
$ cat test.c
#pragma GCC diagnostic ignored "-Wvla"
$ ./Debug/bin/clang  -Wunknown-pragmas test.c
test.c:1:32: warning: unknown warning group '-Wvla', ignored [-Wunknown-pragmas]
#pragma GCC diagnostic ignored "-Wvla"
                               ^
1 diagnostic generated.

**Comment by philnik777** [comment]
This seems to be a misunderstanding. Adding `-Wno-unknown-pragmas` should suppress the warning, not `-Wunknown-pragmas (and it does, at least in Clang 3.4 and trunk with a new flag: https://godbolt.org/z/Kzqhr8dEd)`
