### ISSUE TITLE
clang: error: unsupported option '-mharden-sls=' for target 'x86_64-unknown-linux-gnu' when using CMAKE and Meson 

### ISSUE THREAD

**Issue by ms178** [llvm/llvm-project#63237]
As of clang version 17.0.0 (25d9fde22e609f8637f720220810429745707b76), I now see the error message when using `-marhden-sls=none` in my Cflags in various projects that use either CMAKE or Meson as their build system. I haven't seen the same error when compiling the Linux Kernel though. This seems to be a very recent change in behavior as in a previous build from yesterday, I didn't change the way to build LLVM drastically either (for more build details, see: https://github.com/ms178/archpkgbuilds/blob/main/toolchain-experimental/llvm-bolt-scripts-master/build_stage2-prof-use-lto.bash).

For reference, I haven't seen this with (2150231652ff9f951a8c6381d7ad772cb1badb03) or (c8be70132de95281f73f0493480236cbbf703002).

CMAKE: 3.27.0.rc1.28.g3b0a90968e
Meson: 1.1.0.r147.d28d4ac4e

I haven't specified a target triplet in my LLVM build script and assume that the default (host) is used.

CPU: Intel Haswell-EP

**Comment by tbaederr** [comment]
I haven't bisected this, but it might just be https://github.com/llvm/llvm-project/commit/5548843d692a92a7840f14002debc3cebcb3cdc3, CC @MaskRay
