### ISSUE TITLE
MLIR examples MyExtensionCh2 and MyExtensionCh3 got included in nightly apt release of llvm

### ISSUE THREAD

**Issue by jackalcooper** [llvm/llvm-project#63260]
## relevant error messages
```console
CMake Error at /usr/lib/llvm-17/lib/cmake/mlir/MLIRTargets.cmake:2101 (message):
  The imported target "MyExtensionCh2" references the file

     "/usr/lib/llvm-17/lib/libMyExtensionCh2.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/llvm-17/lib/cmake/mlir/MLIRTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/llvm-17/lib/cmake/mlir/MLIRConfig.cmake:37 (include)
```

**Comment by ftynse** [comment]
Can we get more info: what is the desired behavior? what is the actual behavior? how this can be reproduced?

**Comment by jackalcooper** [comment]
@ftynse sorry I should have post the info
## what is the desired behavior? 
a downstream project's cmake should include MLIR installed with llvm apt nightly release with no problem
## what is the actual behavior? 
downstream project's cmake is trying to find MyExtensionCh2 and MyExtensionCh3 but the "/usr/lib/llvm-17/lib/libMyExtensionCh2.a" file is absent
## how this can be reproduced?
1. install MLIR with LLVM Debian/Ubuntu nightly packages from https://apt.llvm.org
```
apt update \
    && apt install -y --allow-downgrades --allow-change-held-packages --no-install-recommends \
    python3-pip ccache ninja-build \
    wget lsb-release software-properties-common gnupg && \
    wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    ./llvm.sh 17 && \
    apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends \
    libmlir-17-dev mlir-17-tools && \
    python3 -m pip install cmake=="3.26"
```
2. build a standalone MLIR project according to this example: https://github.com/llvm/llvm-project/tree/main/mlir/examples/standalone , and with cmake flags to use the nightly release installed by apt
```
  -DLLVM_DIR=/usr/lib/llvm-17/lib/cmake/llvm \
  -DMLIR_DIR=/usr/lib/llvm-17/lib/cmake/mlir \
```

**Comment by joker-eph** [comment]
I don't know about this, I looked at this every other years and always have to dig in deep and figure out.

**Comment by ftynse** [comment]
Let's try with f17b137f778d174f8629ef6c77f3efa58da7f659, which follows what we do for test libraries. It will probably get picked up in the next nightly.

**Comment by jackalcooper** [comment]
Just tested. The nightly build of 20230618 still has this issue.

**Comment by jackalcooper** [comment]
there is a `add_toy_chapter` which calls `add_llvm_example` in toy examples
https://github.com/llvm/llvm-project/blob/0eb0fecbc544a0416b70f4450a38dfb27c9b5b9a/mlir/examples/toy/CMakeLists.txt#LL6C3-L6C36

**Comment by ftynse** [comment]
> Just tested. The nightly build of 20230618 still has this issue.

Thanks for checking.

> there is a add_toy_chapter which calls add_llvm_example in toy examples
https://github.com/llvm/llvm-project/blob/0eb0fecbc544a0416b70f4450a38dfb27c9b5b9a/mlir/examples/toy/CMakeLists.txt#LL6C3-L6C36

So do the rules for `mlir-transform-opt`, but there are also libraries which toy doesn't have. And it is important for the transform tutorial to showcase proper library usage.

**Comment by ftynse** [comment]
Let's try with e2b19ef6ac7e5635699730ff561e7f24775704c9.

**Comment by jackalcooper** [comment]
it works!
