### ISSUE TITLE
Undeserved -Wctad-maybe-unsupported warnings on std::lock_guard, std::scoped_lock

### ISSUE THREAD

**Issue by N-Dekker** [llvm/llvm-project#63288]
The warning `-Wctad-maybe-unsupported` could certainly be helpful to avoid accidental uses of CTAD on a template that _may not intend to support class template argument deduction_  However, `std::lock_guard` and `std::scoped_lock` are actually _motivating examples_ for the introduction of the language feature with C++17. Looking at [p0091r3 - Template argument deduction for class templates (Rev. 6)](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0091r3.html), by Mike Spertus, Faisal Vali, and Richard Smith, 2016-06-24.

Example (tried using Clang 16.0.0 at https://godbolt.org/z/oMW4MbY4M):

```cpp
#include <mutex>
#include <shared_mutex>

std::shared_lock<std::shared_timed_mutex> r1;
std::shared_timed_mutex mut_;

auto lock = std::scoped_lock(mut_, r1); // Gets a "may not intend to support CTAD" warning!
```

Output:

```console
warning: 'scoped_lock' may not intend to support class template argument deduction [-Wctad-maybe-unsupported]
```

`std::lock_guard` and `std::scoped_lock` are obviously intended to support CTAD, so the warning is undeserved in this case. Could `-Wctad-maybe-unsupported` possibly skip `std::lock_guard` and `std::scoped_lock` somehow? Or could those two templates possibly be marked "intended for CTAD"?

**Comment by shafik** [comment]
Looks like this was the PR that implemented this: https://reviews.llvm.org/D56731

maybe @EricWF or @zygoloid might have a better response on this issue

**Comment by dwblaikie** [comment]
The place(s) to fix this would either be:
1) Having the compiler have an explicit list of types that the warning doesn't apply to (annoying to maintain) - or possibly allow-listing everything in the `std` namespace
2) fixing this in the standard library by adding explicit deduction guides where intended (no, it wouldn't be valid/good for user source code to add these themselves)

As for an attribute V explicit guides - as with most warnings, nicer when the suppression mechanism uses the existing language rather than adding new attributes/mechanisms.

**Comment by N-Dekker** [comment]
Thanks for your reply, @dwblaikie 

>  or possibly allow-listing everything in the `std` namespace

Well, looking at [Beware CTAD on reverse_iterator](https://quuxplusone.github.io/blog/2022/08/02/reverse-iterator-ctad/) by Arthur O’Dwyer, `std::reverse_iterator` should certainly _not_ be on the allow-list.

> As for an attribute V explicit guides - as with most warnings, nicer when the suppression mechanism uses the existing language rather than adding new attributes/mechanisms.

Personally I don't really find a guide like `MyTemplate(allow_ctad_t)->MyTemplate<void>` very nice, but I guess I have to get used to it, if that's the official way to specify that that my class template allows argument deduction. The pain could still be slightly mitigating by standardizing the `allow_ctad_t` type though.

Anyway, for now I think it would help already if `std::lock_guard` and `std::scoped_lock` would get those guides.

**Comment by poyaoc97** [comment]
I have a working `-Wctad-copy-not-wrap` as described above and can upload it to Phab once I add tests. I think this is very helpful to the `std::reverse_iterator` case without being too noisy to the average library users.

**Comment by poyaoc97** [comment]
A potential fix awaiting review: https://reviews.llvm.org/D155475

**Comment by N-Dekker** [comment]
@poyaoc97 Thank you very much, Po-yao! Cool! Honestly I haven't yet formed my opinion on when _in general_ CTAD may or may not deserve a warning. But at least the `std::reverse_iterator` case described by [Beware CTAD on reverse_iterator](https://quuxplusone.github.io/blog/2022/08/02/reverse-iterator-ctad/) deserves a warning, whereas CTAD should be entirely warning-free when using `std::lock_guard` or `std::scoped_lock`, even when all compiler warnings are enabled.

I hope your fix will resolve the issue! 👍

**Comment by N-Dekker** [comment]
@poyaoc97 Hi Po-yao, I realize now, CTAD isn't _just_ causing confusion when the copy or move constructor may be selected. I just encountered the following inconsistency between compilers:

```
#include <array>

template <typename T, unsigned N = 1>
class MyArray
{
public:
  explicit MyArray(T) = delete;
  explicit MyArray(const std::array<T, N>&);
};

int main()
{
  const std::array stdArray{1, 2};
  MyArray a{ stdArray }; // Template argument deduction seems compiler dependent!!!
}
```

MSVC (v19.35) appears to like it, deducing `T = int` and `N = 2` (as I originally intended), whereas GCC 13.2 deduces `T = std::array<int, 2>` and `N = 1`! I guess one of the compilers is wrong, but which one?  https://godbolt.org/z/Mh5vW9Eq3

@quuxplusone Arthur, did you already encounter a case like this?

**Comment by zygoloid** [comment]
@N-Dekker That difference actually has nothing to do with CTAD. Here's a reduced example:
```c++
template<int N> struct X {};
template<typename T> void F(T) = delete; // #1
template<unsigned N = 1> void F(const X<N>&); // #2

void G(const X<2> x) { F(x); }
```
What's happening here is that `N` in `#2` is non-deducible [because it has a different type from the corresponding parameter of the template](http://eel.is/c++draft/temp#deduct.type-20.sentence-1). MSVC is wrong to accept your example and this reduced one; in order to fix the original example, you should change the template parameter `N` of `MyArray` to have type `std::size_t`, to match `std::array`.

**Comment by N-Dekker** [comment]
@zygoloid Thanks Richard, very clear!

**Comment by N-Dekker** [comment]
> Sounds like this can be closed, right?

@shafik Will the warning `-Wctad-maybe-unsupported` then no longer appear on std::lock_guard, std::scoped_lock?

**Comment by poyaoc97** [comment]
Changing the meaning of `-Wctad-maybe-unsupported` may upset and disrupt its users. It actually implements [the Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#CTAD).

I propose `-Wctad-selects-copy` (thanks @Quuxplusone for the name), [Phabricator link](https://reviews.llvm.org/D155475), which warns only if the copy deduction candidate is selected (resulting in a copy not wrap) AND there is direct-initialization happening (copy-initialization hints copy not wrap). Such warnings can be suppressed by adding an explicit deduction guide only if the class template is in a system header.

Basically, `-Wctad-selects-copy` tries to catch this case: https://eel.is/c++draft/expr.type.conv#2.sentence-3 and tries _**not to get in the way of CTAD lovers**_.

On the `std::lock_guard` and `std::scoped_lock` use case, the copy deduction candidate would not be selected, and hence not warned by `-Wctad-selects-copy`.

Example code:
```c++
template <typename T> struct CTAD {
  explicit CTAD(T) {}
  CTAD() = default;
};

CTAD(void) -> CTAD<void>; // suppress -Wctad-selects-copy ONLY IF the class template is in a system header
                          // not useful otherwise

CTAD c1(42);          // OK, copy deduction candidate not selected
CTAD c2 = c1;         // OK, copy-initialization
CTAD c3{CTAD<int>()}; // warns, direct-initialization
auto c4 = CTAD(c1);   // warns, the result object of the initializer expression is direct-initialized
auto c5 = CTAD<CTAD<int>>(c1); // wrapping, might be what the two previous lines actually want
```
Output:
```
ctad.cpp:10:6: warning: move-constructing not wrapping a 'CTAD<int>', use copy-list-initialization to suppress this warning [-Wctad-selects-copy]
   10 | CTAD c3{CTAD<int>()}; // warns, direct-initialization
      |      ^~~~~~~~~~~~~~~
ctad.cpp:11:11: warning: copy-constructing not wrapping a 'CTAD<int>', use copy-initialization to suppress this warning [-Wctad-selects-copy]
   11 | auto c4 = CTAD(c1);   // warns, the result object of the initializer expression is direct-initialized
      |           ^~~~~~~~
2 warnings generated.
```
How does everyone think of this new warning, especially the heuristic?
I feel that the wording of the warning might need some more work tho.

**Comment by N-Dekker** [comment]
Thanks very much for elaborating on this issue @poyaoc97. 

> Changing the meaning of `-Wctad-maybe-unsupported` may upset and disrupt its users.

I understand, but then, wasn't CTAD really meant to support `std::lock_guard` and `std::scoped_lock` in the first place? As it appears that CTAD support must be made explicit by adding a deduction guide, also according to [the Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#CTAD), shouldn't `std::lock_guard` and `std::scoped_lock` just have such an explicit deduction guide?

**Comment by N-Dekker** [comment]
> How does everyone think of this new warning, especially the heuristic?

I must say I'm impressed, the heuristic looks very clever to me. 👍 

With respect to the wording, I hesitate about the word "wrapping".  The `explicit CTAD(T)` constructor may not always _wrap_, right? If you stick with the word "wrapping", you might consider putting "not wrapping" between parentheses, like _warning: move-constructing (not wrapping) a 'CTAD<int>'_

My two cents.

**Comment by N-Dekker** [comment]
> Such warnings can be suppressed by adding an explicit deduction guide only if the class template is in a system header.

@poyaoc97 Do I understand correctly that the expression `std::array{ values... }` will remain _warning-free_ with [your proposal](https://reviews.llvm.org/D155475), even when `values...` expands to a single `std::array<T, N>` instance?

Example (https://godbolt.org/z/WK4Pefsn4):
```
#include <array>

template <typename... T>
constexpr auto Count(T... values)
{
  return std::array{ values... }.size();
}

static_assert(Count(1, 2, 3) == 3);
static_assert(Count(std::array<int, 42>{}) == 42);
```

Even though I actually just wrote [such code](https://github.com/InsightSoftwareConsortium/ITK/commit/89d3c3c0158806ab44a33d3c76b436537864398e) myself, I think a `-Wctad-selects-copy` warning would very much make sense in such a case.

**Comment by poyaoc97** [comment]
Yes, the warning doesn't fire in this case.

IIUC, a copy deduction candidate is always implicit, so the existence of an explicit guide is somewhat irrelevant to copy deduction candidate being selected. I would be more than happy to remove the ability to suppress by adding a guide if that's what you want.

The new output after the removal:
```
ctad.cpp:6:10: warning: copy-constructing (not wrapping) a 'std::array<int, 42>', use copy-list-initialization to suppress this warning [-Wctad-selects-copy]
    6 |   return std::array{ values... }.size();
      |          ^~~~~~~~~~~~~~~~~~~~~~~
ctad.cpp:10:15: note: in instantiation of function template specialization 'Count<std::array<int, 42>>' requested here
   10 | static_assert(Count(std::array<int, 42>{}) == 42);
      |               ^
1 warning generated.
```
The warning can still be silenced with:
```c++
#include <array>

template <typename... T>
constexpr auto Count(T... values)
{
  std::array _ = { values... };
  return _.size();
}

static_assert(Count(1, 2, 3) == 3);
static_assert(Count(std::array<int, 42>{}) == 42);
```

**Comment by N-Dekker** [comment]
> I would be more than happy to remove the ability to suppress by adding a guide if that's what you want.

@poyaoc97 Thanks, I think it makes sense for `-Wctad-selects-copy` to ignore the existence of a guide.  `-Wctad-maybe-unsupported` already checks the existence of a guide, so it would make the two warnings complementary, which seems OK to me.

I would like if `-Wctad-selects-copy` could treat templates from a system header and templates from a non-system header equally. That's what you're suggesting, right?
