### ISSUE TITLE
[Flang] Feature request: character array expression temp with dynamic length

### ISSUE THREAD

**Issue by ceseo** [llvm/llvm-project#63319]
Building SPEC CPU 2017 (628.pop2_s) using the current `main` fails with

```
../llvm/flang/lib/Lower/ConvertExpr.cpp:4450: not yet implemented: character array expression temp with dynamic length
```

Is there a plan to add this feature in the near future? Or is there anyone currently working on it?

**Comment by kiranchandramohan** [comment]
This issue is covered in https://github.com/llvm/llvm-project/issues/58374. From what I remember HLFIR will fix this. Not sure whether this has changed.
In general, we have a board for spec-2017 (https://github.com/orgs/llvm/projects/8).

**Comment by ceseo** [comment]
Sorry, I didn't see that. I'll close it.
