### ISSUE TITLE
Enable GNU inline semantics selectively in C99 mode

### ISSUE THREAD

**Issue by DougGregor** [llvm/llvm-project#6332]
|  |  |
| --- | --- |
| Bugzilla Link | [5960](https://llvm.org/bz5960) |
| Version | trunk |
| OS | other |
| CC | @davidchisnall,@efriedma-quic,@ismail |

## Extended Description 
Per David Chisnall's comments in PR 3989, some platforms have glibc headers that expect GNU inline semantics even in C99 mode, which causes linking problems when building with Clang. 

Implementing -fgnu89-inline works around part of the problem (and is probably a good idea in general), but that's a big hammer: we really want only those functions defined in the glibc headers to get GNU inline semantics.

**Comment by philnik777** [comment]
I don't think this will be implemented anymore if it hasn't already, since this only affects glibcs that are over 15 years old.
