### ISSUE TITLE
[clang-format] "clang-format off" gets ignored for preprocessor directives in main branch (llvm 17)

### ISSUE THREAD

**Issue by Sedeniono** [llvm/llvm-project#63379]
Consider
```C++
// clang-format off
#if 0
        #if SHOULD_STAY_INDENTED
 #endif
#endif
// clang-format on
```
The `.clang-format` file contains a single line:
```yml
BasedOnStyle: LLVM
```
Formatting the whole file with Clang 16, the formatting of the preprocessor directives is not changed. However, using the current main branch (LLVM 17; specifically b7287a82d33b6cd1760ac7e399ba92ae52057b5d), Clang-Format does format the `#if SHOULD_STAY_INDENTED` and the `#endif` (the indent gets removed).
This happens even with the bugfix from #62892.

I could bisect it to a4c87f8ccaccc76fd7d1c6c2e639ca84b9ec7794 (#61498). Differential revision: https://reviews.llvm.org/D150057
Maybe @owenca?

I noticed the above regression while looking at the example from https://github.com/llvm/llvm-project/issues/57117, and managed to reduce it to the above.

**Comment by owenca** [comment]
https://reviews.llvm.org/D153243
