### ISSUE TITLE
[Clang] error "in-class initializer for static data member is not a constant expression" where gcc compiles fine

### ISSUE THREAD

**Issue by n1tay** [llvm/llvm-project#63387]
When trying to compile the following code I receive the following compilation error on Clang, but it compiles fine on GCC. 
As far as I understand this should compile
```console
in-class initializer for static data member is not a constant expression
```

```cpp
#include <cmath>
#include <iostream>

template <typename t1, typename t2>
inline constexpr int add(t1 a, t2 b)
{return a + b;}

constexpr int foo(int value)
{
	return (int)std::pow(2, 7);
}

template < size_t num>
class testClass
{
public:
	static const constinit size_t number = foo(num);
};

struct PrincipleData
{
	testClass<6> orders;
};

int main(){
    PrincipleData data;
    std::cout << decltype(data.orders)::number << std::endl;
}
```

[Compiler explorer link of the code](https://godbolt.org/z/nb4K6xfzd)

**Comment by Fznamznon** [comment]
I think clang is right here. Even though `foo` is declared with `constexpr` its invocation is not a constant expression because it calls `std::pow` which is not a `constexpr function. https://eel.is/c++draft/expr.const#5.3

MSVC agrees with a bit more explanation - https://godbolt.org/z/hE7q4qv5f .

**Comment by n1tay** [comment]
I see. 
Checking cppReference i see pow is indeed not constexpr. 
I know at this point it isn't a clang related questions, but when i check my ```pow``` implementation on my machine it is constexpr: 

Taken from ```/usr/include/c++/12.2.1/cmath```

```  template<typename _Tp, typename _Up>
    inline _GLIBCXX_CONSTEXPR
    typename __gnu_cxx::__promote_2<_Tp, _Up>::__type
    pow(_Tp __x, _Up __y)
    {
      typedef typename __gnu_cxx::__promote_2<_Tp, _Up>::__type __type;
      return pow(__type(__x), __type(__y));
    }

```

where ```_GLIBCXX_CONSTEXPR``` is defined to be "constexpr"  in ```/usr/niclude/c++/x86_64-pc-linux-gnu/bits/c++config.h```
```
#  define _GLIBCXX_CONSTEXPR constexpr
```

**Comment by shafik** [comment]
This is a known non-conforming issue for gcc see [Is gcc considering builtins of non-constant expression functions to be constant expressions](https://stackoverflow.com/a/27906899/1708801)
