### ISSUE TITLE
is clang-format supposed to ?

### ISSUE THREAD

**Issue by cartu38** [llvm/llvm-project#63398]
Hello,
Very naïve question I apologize for.
I guess I know the answer but just to get confirmation from community about `clang-format` capabilities.

```
my Func();
if (myFunc() = = 0)

```
Is `clang-format` expected to get rid of extra spaces:

- The one between `my` & `Func()`
- The one between `=` & `=`

Thanks in advance

**Comment by gedare** [comment]
`clang-format` does not fix syntax errors so that code compiles for you.

**Comment by cartu38** [comment]
Ok Thanks. Confirms my first guess.
