### ISSUE TITLE
Missing ubuntu binaries starting with release 16.0.5

### ISSUE THREAD

**Issue by serban-nicusor-toptal** [llvm/llvm-project#63402]
Hello!

I meant to ask if  `clang+llvm-16.0.4-x86_64-linux-gnu-ubuntu-22.04.tar.xz`  will be re-uploaded or dropped for the newer releases?

Saw that the last two runs failed for Ubuntu:
- https://github.com/llvm/llvm-project/actions/runs/5263010337
- https://github.com/llvm/llvm-project/actions/runs/5156377829

Thanks!

**Comment by asl** [comment]
The binaries are produced by volunteers, so they may or may not present in the binary releases depending on the particular person's availability.

If necessary, consider compiling by yourself from the sources or use apt.llvm.org

**Comment by serban-nicusor-toptal** [comment]
Thanks @asl !
