### ISSUE TITLE
Multiple issues with -ferror-limit

### ISSUE THREAD

**Issue by pmor13** [llvm/llvm-project#63403]
https://clang.llvm.org/docs/UsersManual.html says:
> -ferror-limit=123
> Stop emitting diagnostics after 123 errors have been produced. The default is 20, and the error limit can be disabled with -ferror-limit=0.

Issue 1: Contradiction with the manual:
```console
$ echo "int_ x; int x=0.5;" | clang -xc - -ferror-limit=1
<stdin>:1:1: error: unknown type name 'int_'; did you mean 'int'?
int_ x; int x=0.5;
^~~~
int
<stdin>:1:15: warning: implicit conversion from 'double' to 'int' changes value from 0.5 to 0 [-Wliteral-conversion]
int_ x; int x=0.5;
            ~ ^~~
1 warning and 1 error generated.
```
Here we see that despite of `-ferror-limit=1` diagnostic `warning: implicit conversion ...` was emitted. This contradicts with the manual.

Issue 2: Confusion with the wording `Stop emitting diagnostics after 123 errors have been produced`.

Multiple interpretations possible:
- Clang just stops emitting diagnostics _while continuing compiling the code_
- Clang stops emitting diagnostics _and aborts immediately_
Which one is correct?

Here is the simple test:
```console
$ (echo "int_ x;" ; for i in {1..5000000}; do echo "int x$i;"; done) | clang -xc - -ferror-limit=1 -c
<stdin>:1:1: error: unknown type name 'int_'; did you mean 'int'?
int_ x;
^~~~
int
```
Because of the delay after the error was emitted, I see that Clang just stops emitting diagnostics while continuing compiling the code. Is that correct? Is it possible to _immediately_ abort Clang after the "123 errors have been produced"? How?

Issue 3: why the triggering condition for `-ferror-limit` is "exceeded" rather than "reached"? Should it be "reached"? Will it be useful to implement "reached" (perhaps as `-ferror-limit-reached`)?

Issue 4: `man clang | grep error-limit` produces nothing. Very unexpected.

**Comment by MaskRay** [comment]
Issue 1: It's not contradiction. Warnings are not counted for `-ferror-limit=`. The documentation is not accurate, though.

Issue 2: I don't think it is an issue. Clang keeps parsing the code. Use `-Wfatal-errors` to exit immediately.
```
% echo "x;x;x;" | clang -xc - -ferror-limit=1
<stdin>:1:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
x;x;x;
^
int
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 errors generated.
% echo "x;x;x;" | clang -xc - -ferror-limit=1 -Wfatal-errors
<stdin>:1:1: fatal error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
x;x;x;
^
int
1 error generated.
```

Issue 3: I think the behavior just follows GCC.
