### ISSUE TITLE
[libcxx] vector.insert() code will core dump in std=c++11

### ISSUE THREAD

**Issue by joyhou-hw** [llvm/llvm-project#63400]
The following code in std=c++11 will core dump in the insert() call with using libc++ libs.   while c++14 is OK. 

initializer_list  is supported in the C++11, is this something wrong in the code ?
test in  llvm 15.0.4.
```
#include <vector>
template < class Allocator >
int test_it(){
    bool rv= true;
    using obj_type = std::vector< bool, Allocator >   ;
    typename obj_type::iterator  v0 ;
    typename obj_type::const_iterator  cv0 = v0 ;
    std::initializer_list < bool > v1= {0};
    obj_type obj;
    typename obj_type::iterator x =   obj.insert ( cv0, v1 );
    return rv;
}

int main () {
  int w = test_it< std::allocator<bool> >() ;
  return w;
}

```

**Comment by shafik** [comment]
I can reproduce this on trunk: https://godbolt.org/z/vMehbj71o

w/ libc++ it crashes at runtime but otherwise is ok.

**Comment by philnik777** [comment]
In C++11 the iterator doesn't have to be null-initialized. You have to initialize the iterator properly for it to work.
