### ISSUE TITLE
[NVPTX] Instruction selection failures for NVPTXISD::LoadV2 in presence of different source destination types

### ISSUE THREAD

**Issue by nirvedhmeshram** [llvm/llvm-project#63436]
In this LLVM IR
```ll
define void @foo(ptr noalias readonly align 16 %0, ptr noalias readonly align 16 %1) {
%3 = getelementptr half, ptr %0, i64 0
%4 = load <8 x half>, ptr %3, align 16
%5 = fpext <8 x half> %4 to <8 x float>
store <8 x float> %5, ptr %1, align 16
ret void
}

!nvvm.annotations = !{!0}

!0 = !{ptr @foo, !"kernel", i32 1}
```
running with `bin/llc < ~/test.ll -march=nvptx -mcpu=sm_80 --debug` will get the following failure
https://gist.github.com/nirvedhmeshram/59912f126126f00a22920b770c330782

However, if you remove the nvvm.annotation this will work as it makes a `LDV_f32_v2_ari`, so my first question is, is it by design that we dont want to use this code for addrspace 1? 
https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp#L1071-L1085

because then its hitting this part 
https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp#L1599-L1622
which is not meant to handle the `NVPTXISD::LoadV` nodes so we can extend its handling if that is the right thing to do?

**Comment by nirvedhmeshram** [comment]
Hi @Artem-B , I see you actively contributing to the nvptx, please let me know if you can help with this?

**Comment by Artem-B** [comment]
This is certainly unexpected. 

On top of that there's something odd going on. The load gets split into: 4xf32, 2xf32, f16, f16, which is a rather odd arrangement.

```
  t41: f32,f32,f32,f32,ch = NVPTXISD::LoadV4<(load (s64) from %ir.4, align 16, addrspace 1)> t0, t10, undef:i32, Constant:i32<1>
    t68: i32 = add t10, Constant:i32<12>
  t72: f16,ch = load<(load (s16) from %ir.4 + 12, align 4, basealign 16, addrspace 1)> t0, t68, undef:i32
    t65: i32 = add t10, Constant:i32<14>
  t70: f16,ch = load<(load (s16) from %ir.4 + 14, basealign 16, addrspace 1)> t0, t65, undef:i32
    t21: i32 = add nuw t10, Constant:i32<8>
  t37: f32,f32,ch = NVPTXISD::LoadV2<(load (s32) from %ir.4 + 8, align 8, basealign 16, addrspace 1)> t0, t21, undef:i32, Constant:i32<1>
```

**Comment by nirvedhmeshram** [comment]
right, ideally we would want just two loadV4 loads

**Comment by Artem-B** [comment]
Looks like `tryLDGLDU` needs to know whether the load we're doing is an extending load, but the op we're lowering is a target node which no longer has this info. Makes me wonder why we didn't run into this issue before.

Non-kernels work, because they operate on generic pointers, so we never get into `tryLDGLDU`.

I'm not sure yet what's the best way to address the problem.

> However, if you remove the nvvm.annotation this will work as it makes a LDV_f32_v2_ari, so my first question is, is it by design that we dont want to use this code for addrspace 1?

To answer your question -- using ldg/ldu is an optimization which is only applicable for pointers in the global address space. We can infer it for the kernel pointer arguments, but not for regular functions.

**Comment by nirvedhmeshram** [comment]
>  but the op we're lowering is a target node which no longer has this info
So in `NVPTXISD::LoadV2<(load (s32) from %ir.4 + 8, align 8, basealign 16, addrspace 1)> t0, t21, undef:i32, Constant:i32<1>`
wouldnt this part `load (s32) from %ir.4 + 8, align 8, basealign 16, addrspace 1)` be carrying the extending node information? and then we can do something like this to get that information
https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp#L1039-L1041

**Comment by Artem-B** [comment]
https://reviews.llvm.org/D153477 should make things work.
Sub-optimal vector splitting + explicit conversion is still there, but the code should work and ptxas will probably generate similar SASS to what it generates for non-kernels.

**Comment by Artem-B** [comment]
Reproducer: https://godbolt.org/z/nzsd16MrP

**Comment by nirvedhmeshram** [comment]
HI @Artem-B was wondering if we will be able to land the patch soon, we have downstream applications blocked on it that we would like to cleanly support. Thanks.

**Comment by Artem-B** [comment]
The patch still needs to be reviewed. I'll land it once it's stamped.
