### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Ashutosh-Londhe** [llvm/llvm-project#63434]
I am getting following error while running Make
```console
llvm-project/openmp/libomptarget/plugins/cuda/src/rtl.cpp:1453:30: error: ‘CU_DEVICE_ATTRIBUTE_COOPERATIVE_LAUNCH’ was not declared in this scope; did you mean ‘CU_DEVICE_ATTRIBUTE_COMPUTE_MODE’?
 1453 |                     &TmpInt, CU_DEVICE_ATTRIBUTE_COOPERATIVE_LAUNCH, Device),
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              CU_DEVICE_ATTRIBUTE_COMPUTE_MODE
[ 51%] Building CXX object lib/DWP/CMakeFiles/LLVMDWP.dir/DWPError.cpp.o
[ 51%] Building CXX object lib/DebugInfo/LogicalView/CMakeFiles/LLVMDebugInfoLogicalView.dir/Core/LVRange.cpp.o
[ 51%] Building CXX object lib/DebugInfo/LogicalView/CMakeFiles/LLVMDebugInfoLogicalView.dir/Core/LVReader.cpp.o
[ 51%] Linking CXX shared library ../../../../../lib/libomptarget.rtl.x86_64.so
[ 51%] Building CXX object lib/DebugInfo/LogicalView/CMakeFiles/LLVMDebugInfoLogicalView.dir/Core/LVScope.cpp.o
[ 51%] Building CXX object lib/DebugInfo/LogicalView/CMakeFiles/LLVMDebugInfoLogicalView.dir/Core/LVSort.cpp.o
[ 51%] Linking CXX static library ../../libLLVMRuntimeDyld.a
[ 51%] Built target LLVMRuntimeDyld
[ 51%] Built target omptarget.rtl.x86_64
[ 51%] Building CXX object tools/llvm-nm/CMakeFiles/llvm-nm.dir/llvm-nm.cpp.o
make[2]: *** [projects/openmp/libomptarget/plugins/cuda/CMakeFiles/omptarget.rtl.cuda.dir/build.make:76: projects/openmp/libomptarget/plugins/cuda/CMakeFiles/omptarget.rtl.cuda.dir/src/rtl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:22380: projects/openmp/libomptarget/plugins/cuda/CMakeFiles/omptarget.rtl.cuda.dir/all] Error 2
```

used following options in CMake

```shell
git clone https://github.com/llvm/llvm-project.git

cd llvm-project

mkdir build
cd build

cmake  -DCMAKE_BUILD_TYPE=Release -DCLANG_OPENMP_NVPTX_DEFAULT_ARCH=sm_60 -DLIBOMPTARGET_NVPTX_COMPUTE_CAPABILITIES=60 -DLLVM_TARGETS_TO_BUILD="X86;NVPTX" -DLLVM_ENABLE_PROJECTS="clang;openmp" ../llvm/

make -j
```

using GCC 9.3.0, Python 3.9 and CMake 3.20

**Comment by shiltian** [comment]
The issue has been fixed in 88e66fa60ae5 I believe.

**Comment by jhuber6** [comment]
What version of LLVM are you trying to build? As @shiltian said that should be fixed upstream for quite some time. I would recommend building off of the `main` branch if possible for offloading. Some notes as well,

`CLANG_OPENMP_NVPTX_DEFAULT_ARCH` This was removed in the 16.0 release, `clang` will not attempt to infer the default option at compile time via the `nvptx-arch` tool.

`LIBOMPTARGET_NVPTX_COMPUTE_CAPABILITIES` This was renamed to `LIBOMPTARGET_DEVICE_ARCHITECTURES` and accepts a list of GPU architectures, e.g. `sm_60;gfx908` if you want both `sm_60` support and `gfx908` support. It default to all supported architectures if not set (as it would be if you used the old version).

**Comment by Ashutosh-Londhe** [comment]
Hi  @jhuber6 
I will use the following branch now instead of main
https://github.com/llvm/llvm-project/tree/release/14.x

`cmake -DCMAKE_INSTALL_PREFIX=<path to install> -DCMAKE_BUILD_TYPE=Release -DLIBOMPTARGET_DEVICE_ARCHITECTURES=sm_60 -DLLVM_TARGETS_TO_BUILD="X86;NVPTX" -DLLVM_ENABLE_PROJECTS="clang;openmp" ../llvm/`

Does this looks ok now??

**Comment by jhuber6** [comment]
> Hi @jhuber6 I will use the following branch now instead of main https://github.com/llvm/llvm-project/tree/release/14.x
> 
> `cmake -DCMAKE_INSTALL_PREFIX=<path to install> -DCMAKE_BUILD_TYPE=Release -DLIBOMPTARGET_DEVICE_ARCHITECTURES=sm_60 -DLLVM_TARGETS_TO_BUILD="X86;NVPTX" -DLLVM_ENABLE_PROJECTS="clang;openmp" ../llvm/`
> 
> Does this looks ok now??

No, those changes were made in the `16.x` branch so they won't work with `14.x`. I recommend using a newer branch for offloading, is there a specific reason you want such an old version of LLVM?

**Comment by Ashutosh-Londhe** [comment]
Sure @jhuber6 I will use 16.x branch then
i wanted to use the 14.x as i am also working on code translator based in python which uses clang library and required 14.x lib files
but i think i will keep that asides
otherwise cmake is ok??

**Comment by jhuber6** [comment]
> Sure @jhuber6 I will use 16.x branch then i wanted to use the 14.x as i am also working on code translator based in python which uses clang library and required 14.x lib files but i think i will keep that asides otherwise cmake is ok??

Actually sorry I just double checked, the `-DLIBOMPTARGET_DEVICE_ARCHITECTURES=sm_60` portion landed just after the `16.0` fork and was not back-ported. So that one should stay the same with the `LIBOMPTARGET_NVPTX_COMPUTE_CAPABILITIES` method. Sorry about that.

**Comment by Ashutosh-Londhe** [comment]
Sure @jhuber6 i will use 16.x and `LIBOMPTARGET_NVPTX_COMPUTE_CAPABILITIES`

**Comment by jhuber6** [comment]
Cool, let me know if you have any more problems. Otherwise, we can close this issue.

**Comment by Ashutosh-Londhe** [comment]
Hi @jhuber6 

I am still getting same error with `release/16.x` branch also

`llvm-project/openmp/libomptarget/plugins/cuda/src/rtl.cpp: In member function ‘void {anonymous}::DeviceRTLTy::printDeviceInfo(int32_t)’:
/ext-home/asl/install/clang/llvm-project/openmp/libomptarget/plugins/cuda/src/rtl.cpp:1449:30: error: ‘CU_DEVICE_ATTRIBUTE_COOPERATIVE_LAUNCH’ was not declared in this scope; did you mean ‘CU_DEVICE_ATTRIBUTE_COMPUTE_MODE’?
 1449 |                     &TmpInt, CU_DEVICE_ATTRIBUTE_COOPERATIVE_LAUNCH, Device),
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              CU_DEVICE_ATTRIBUTE_COMPUTE_MODE
[ 53%] Building CXX object projects/openmp/libomptarget/plugins/amdgpu/CMakeFiles/omptarget.rtl.amdgpu.dir/src/rtl.cpp.o
[ 53%] Building CXX object lib/ObjectYAML/CMakeFiles/LLVMObjectYAML.dir/XCOFFYAML.cpp.o
[ 53%] Building CXX object lib/ExecutionEngine/JITLink/CMakeFiles/LLVMJITLink.dir/ELF_loongarch.cpp.o
[ 53%] Building CXX object lib/ObjectYAML/CMakeFiles/LLVMObjectYAML.dir/YAML.cpp.o
[ 53%] Linking CXX executable ../../../../../bin/llvm-omp-device-info
[ 53%] Built target llvm-omp-device-info
make[2]: *** [projects/openmp/libomptarget/plugins/cuda/CMakeFiles/omptarget.rtl.cuda.dir/build.make:76: projects/openmp/libomptarget/plugins/cuda/CMakeFiles/omptarget.rtl.cuda.dir/src/rtl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:21900: projects/openmp/libomptarget/plugins/cuda/CMakeFiles/omptarget.rtl.cuda.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....`

`cmake -DCMAKE_INSTALL_PREFIX=/ext-home/asl/install/clang/install -DCMAKE_BUILD_TYPE=Release -DCLANG_OPENMP_NVPTX_DEFAULT_ARCH=sm_60 -DLIBOMPTARGET_NVPTX_COMPUTE_CAPABILITIES=60 -DLLVM_TARGETS_TO_BUILD="X86;NVPTX" -DLLVM_ENABLE_PROJECTS="clang;openmp" ../llvm/`

**Comment by jhuber6** [comment]
> 

That definition is most definitely in the `16.x` branch, see https://github.com/llvm/llvm-project/blob/release/16.x/openmp/libomptarget/plugins/cuda/dynamic_cuda/cuda.h#L154. Did you try a clean build in CMake? Alternatively you could install CUDA to prevent needing to fallback to the dynamically loaded version which includes this.

**Comment by Ashutosh-Londhe** [comment]
Yes @jhuber6  I done the make clean before doing cmake again
I have cuda/toolkit-10.2.89 available on system i am installing this i think i will try with this

**Comment by Ashutosh-Londhe** [comment]
Hi @jhuber6 
I am able to install now after loading cuda modules
we can close the issue now
