### ISSUE TITLE
[MLIR] possible bug report

### ISSUE THREAD

**Issue by HahaLan97** [llvm/llvm-project#63432]
Hi, dear developers of MLIR. I've been trying to build my own dialect and I'm using `ElementAttrInterface` in the file `include/mlir/IR/BuiltinAttributeInterfaces.td`. But when I build my own dialect, I always got an error like
```
no viable conversion from ::mlir::Type to ::mlir::ShapedType
```
and I think it may because the method definition from the line 180:
```
InterfaceMethod<[{
      Returns the shaped type of the elements attribute.
    }], "::mlir::ShapedType", "getShapedType", (ins), [{}], /*defaultImplementation=*/[{
        return $_attr.getType();
    }]>
```
I've tried to add a cast function behind and now the error is gone. Could you maybe please take a look at it?

**Comment by rikhuijzer** [comment]
Could you give a reproducible example or more information on how you used `ElementAttrInterface` in your code?
