### ISSUE TITLE
Cleanup -march flag in aosp after clang driver has those defaults.

### ISSUE THREAD

**Issue by appujee** [llvm/llvm-project#63444]
e.g., [-march](https://android.googlesource.com/platform/build/soong/+/master/cc/config/riscv64_device.go#32) flag has zbb but clang driver also enables zbb by default after https://reviews.llvm.org/D152729 has landed.

**Comment by xgupta** [comment]
Why you have opened this issue here if you want to modify AOSP.

**Comment by asl** [comment]
please reopen the issue with refined description if you'd think that there is LLVM problem somewhere

**Comment by appujee** [comment]
sorry for the confusion, I intended to create this ticket in another github project.
