### ISSUE TITLE
[BOLT] PERF2BOLT fails at stage 3 using the LBR sampling method

### ISSUE THREAD

**Issue by ms178** [llvm/llvm-project#63456]
@aaupov Also seen with LLVM-17 (7c2604ca196c3ba0247509c0fde350e23f0cccb0) is the following issue when using the LBR sampling method for BOLT profile gathering (which uses the [build_stage3-bolt.bash](https://github.com/ms178/archpkgbuilds/blob/main/toolchain-experimental/llvm-bolt-scripts-master/build_stage3-bolt.bash) script in my repo). As all was fine in LLVM snapshots from last week, I suspect either an issue on my system or the newly locally introduced usage of `-mllvm -enable-dfa-jump-thread` during stage 2 or during stage 3 training could lead to this. As the script automatically handles the re-naming of the binary etc., I cannot explain why I get the error message at the end.

```console
RF2BOLT-WARNING: unable to find base address of the binary when memory mapped at 0x557be99dd000 using file offset 0x21dd000. Ignoring profile data for this mapping
PERF2BOLT-WARNING: unable to find base address of the binary when memory mapped at 0x55cee37dd000 using file offset 0x21dd000. Ignoring profile data for this mapping
PERF2BOLT-WARNING: unable to find base address of the binary when memory mapped at 0x5573551dd000 using file offset 0x21dd000. Ignoring profile data for this mapping
PERF2BOLT-WARNING: unable to find base address of the binary when memory mapped at 0x561af2bdd000 using file offset 0x21dd000. Ignoring profile data for this mapping
PERF2BOLT-WARNING: unable to find base address of the binary when memory mapped at 0x55acf17dd000 using file offset 0x21dd000. Ignoring profile data for this mapping
PERF2BOLT-WARNING: unable to find base address of the binary when memory mapped at 0x559cc33dd000 using file offset 0x21dd000. Ignoring profile data for this mapping
PERF2BOLT-WARNING: unable to find base address of the binary when memory mapped at 0x556f1cbdd000 using file offset 0x21dd000. Ignoring profile data for this mapping
PERF2BOLT-WARNING: unable to find base address of the binary when memory mapped at 0x55ea9abdd000 using file offset 0x21dd000. Ignoring profile data for this mapping
PERF2BOLT-WARNING: unable to find base address of the binary when memory mapped at 0x55a6549dd000 using file offset 0x21dd000. Ignoring profile data for this mapping
PERF2BOLT-WARNING: unable to find base address of the binary when memory mapped at 0x55c7d69dd000 using file offset 0x21dd000. Ignoring profile data for this mapping
PERF2BOLT-WARNING: unable to find base address of the binary when memory mapped at 0x561b1f3dd000 using file offset 0x21dd000. Ignoring profile data for this mapping
[snipping dozens of similar lines]
PERF2BOLT-ERROR: could not find a profile matching binary "/home/marcus/toolchain/llvm/stage2-prof-use-lto/install/bin/clang-17". Profile for the following binary name(s) is available:
  bash
  clang-17
  clang-tblgen
  cmake
  git
  ld-linux-x86-64.so.2
  libbrotlicommon.so.1.0.9
  libbrotlidec.so.1.0.9
  libbrotlienc.so.1.0.9
  libbz2.so.1.0.8
  libc.so.6
  libcom_err.so.2.1
  libcrypto.so.3
  libcurl.so.4.8.0
  libffi.so.8.1.2
  libgcc_s.so.1
  libgmp.so.10.4.1
  libgnutls.so.30.35.0
  libgssapi_krb5.so.2.2
  libhogweed.so.6.8
  libicuuc.so.72.1
  libidn2.so.0.3.8
  libjsoncpp.so.25
  libk5crypto.so.3.1
  libkeyutils.so.1.10
  libkrb5.so.3.3
  libkrb5support.so.0.1
  liblzma.so.5.4.3
  libm.so.6
  libncursesw.so.6.4
  libnettle.so.8.8
  libnghttp2.so.14.24.2
  libp11-kit.so.0.3.0
  libpcre2-8.so.0.11.2
  libpsl.so.5.3.4
  libreadline.so.8.2
  libresolv.so.2
  librhash.so.0
  librtmp.so.1
  libssh2.so.1.0.1
  libssl.so.3
  libstdc++.so.6.0.32
  libtasn1.so.6.6.3
  libunistring.so.5.0.0
  libuv.so.1.0.0
  libxml2.so.2.10.4
  libz.so.1.2.13.zlib-ng
  libzstd.so.1.5.5
  lld
  llvm-ar
  llvm-min-tblgen
  llvm-tblgen
  ninja
Please rename the input binary.
```

**Comment by aaupov** [comment]
Can you please share which previous snapshot worked for you? I introduced an NFCI change two weeks ago which might be related: 5acac7db6e71db66d87987eaf5c91315d73ca086

**Comment by ms178** [comment]
@aaupov The last known working revision was (15a16ef8e06e5da382d135bc5074068ed14be6d6) from June 12th (I keep the stats of each of my BOLT builds for comparison).
[LLVM-17-BOLT-230612_stats.txt](https://github.com/llvm/llvm-project/files/11846338/LLVM-17-BOLT-230612_stats.txt)

**Comment by aaupov** [comment]
Thanks for checking. I'm not sure why would perf2bolt fail to match the binary as a result of an extra `-mllvm` flag. I'll try to repro the issue using your script.

**Comment by ms178** [comment]
Just for reference, I am posting the scripts needed here (unfortunately without the llvm17.profdata which is bigger than the allowed file size for attachements here but I hope the issue also reproduces with one of your own):

[setup_llvm_repo.bash.txt](https://github.com/llvm/llvm-project/files/11855485/setup_llvm_repo.bash.txt)
[build_stage1.bash.txt](https://github.com/llvm/llvm-project/files/11855465/build_stage1.bash.txt)
[build_stage2-prof-use-lto.bash.txt](https://github.com/llvm/llvm-project/files/11855482/build_stage2-prof-use-lto.bash.txt)
[build_stage3-bolt.bash.txt](https://github.com/llvm/llvm-project/files/11855484/build_stage3-bolt.bash.txt)

**Comment by ms178** [comment]
Trying to re-produce this issue on the weekend revealed an issue with my local perl package that highly likely caused this issue. Closing for now.
