### ISSUE TITLE
Invalid "Substitution into constraint expression resulted in a non-constant expression" error from clang-16 on

### ISSUE THREAD

**Issue by fiesh** [llvm/llvm-project#63465]
The following C++20 code results in the above mentioned error:

```cpp
template <typename, int a, int b> struct c {
  template <typename... d>
  c(d...)
    requires(sizeof...(d) == a * b);
};
template <typename e, int a> struct f : c<e, a, 1> {
  using c<e, a, 1>::c;
};
void g(c<double, 2, 1> h) { f<double, 2>(h, 0); }
```

It works with `clang-15` as well as other compilers and started failing with `clang-16`.

**Comment by shafik** [comment]
Looks like this works on trunk: https://godbolt.org/z/nqnrannnv

CC @erichkeane

**Comment by erichkeane** [comment]
yeah, we ended up fixing quite a few of these lately, so I'm not surprised this is a dupe of a previous report (or was fixed 'along the way').
