### ISSUE TITLE
[clang-tidy] readability-const-return-type conflicts with cert-dcl21-cpp for postfix operators

### ISSUE THREAD

**Issue by ecorm** [llvm/llvm-project#63464]
[`cert-dcl21-cpp`](https://clang.llvm.org/extra/clang-tidy/checks/cert/dcl21-cpp.html) wants postfix increment/decrement operators to return a `const` value, because otherwise:

> any modifications made to the resulting object from calling operator++(int) would be modifying a temporary object

But [`readability-const-return-type`](https://clang.llvm.org/extra/clang-tidy/checks/readability/const-return-type.html) prohibits returning `const`value types, because

> Such use of _const_ is usually superfluous, and can prevent valuable compiler optimizations.

The `readability-const-return-type` check should be relaxed for postfix increment/decrement operators, because avoiding bugs should take precedence over a minor readability warning.

Example program:

```c++
struct Foo
{
    int value = 0;
};

struct Bar
{
    // warning: overloaded 'operator++' returns a non-constant object
    // instead of a constant object type [cert-dcl21-cpp]
    Bar operator++(int)
    {
        auto temp = *this;
        ++foo.value;
        return temp;
    }

    Foo foo;
};

struct Baz
{
    // warning: return type 'const Baz' is 'const'-qualified at the top
    // level, which may reduce code readability without improving const
    // correctness [readability-const-return-type]
    const Baz operator++(int)
    {
        auto temp = *this;
        ++foo.value;
        return temp;
    }

    Foo foo;
};

int main()
{
    Bar bar;
    bar++;
    Baz baz;
    baz++;
    return 0;
}
```

Godbolt demo: https://godbolt.org/z/E64zeKvzr

**Comment by PiotrZSL** [comment]
cert-dcl21-cpp is deprecated and will be removed in Clang-tidy 19 as it’s no longer part of the CERT standard.
Just do not enable it. Check readability-const-return-type is more correct here, there is no point to have there const, this impact move semantic and there is nothing wrong with changing temporary type.
Like: `auto x = ++(bar++);` this code is correct.

**Comment by ecorm** [comment]
Thanks for letting me know about `cert-dcl21-cpp`. I will remove that check from my project and adjust my code accordingly.

Is there a list or discussion somewhere of other check that are similarly deprecated?

**Comment by PiotrZSL** [comment]
i think that the only one, you can find some information about future changes to clang-tidy in release notes https://clang.llvm.org/extra/ReleaseNotes.html.
