### ISSUE TITLE
CodeGen doesn't produce muladd despite -ffp-contract=fast

### ISSUE THREAD

**Issue by c0d1f1ed** [llvm/llvm-project#63476]
The culprit is in `clang/include/clang/Basic/LangOptions.h`:
```C++
  bool allowFPContractWithinStatement() const {
    return getFPContractMode() == LangOptions::FPM_On;
  }
```
This should instead be:
```C++
  bool allowFPContractWithinStatement() const {
    return getFPContractMode() != LangOptions::FPM_Off;
  }
```
Since we also have `FPM_Fast` and `FPM_FastHonorPragmas`.

This might also be the root cause of #61024.

**Comment by topperc** [comment]
-ffp-contract=fast defers all folding to the backend by marking the `fmul` and `fadd` with the `contract` fast math flag. This is intentional.

**Comment by c0d1f1ed** [comment]
Thanks for pointing that out! Is it documented anywhere or clarified with code comments? I was suprised to find `tryEmitFMulAdd()` not act according to the description of the `FPM_*` flags.

**Comment by arsenm** [comment]
fp-contract=fast = fmul contract + fadd contract. fp-contract=on = fmuladd
