### ISSUE TITLE
compiler-rt: __aarch64_*_sync functions not available

### ISSUE THREAD

**Issue by emaste** [llvm/llvm-project#63483]
Attempting to build FreeBSD with GCC 12 and in-tree compiler-rt 16 fails with:

```console
/usr/local/bin/aarch64-unknown-freebsd13.1-ld: heimbase.pico: in function `_heim_create_type':
/tmp/cirrus-ci-build/crypto/heimdal/base/heimbase.c:281: undefined reference to `__aarch64_ldadd4_sync'
/usr/local/bin/aarch64-unknown-freebsd13.1-ld: heimbase.pico: in function `heim_retain':
/tmp/cirrus-ci-build/crypto/heimdal/base/heimbase.c:97: undefined reference to `__aarch64_ldadd4_sync'
/usr/local/bin/aarch64-unknown-freebsd13.1-ld: heimbase.pico: in function `heim_release':
/tmp/cirrus-ci-build/crypto/heimdal/base/heimbase.c:120: undefined reference to `__aarch64_ldadd4_sync'
collect2: error: ld returned 1 exit status
```

**Comment by jrtc27** [comment]
@sebpop LLVM's implementation is an adaptation of GCC's, relicensed by Linaro. Given you authored https://github.com/gcc-mirror/gcc/commit/bc25483c055d62f94f8c289f80843dda3c4a6ff4 to add them to GCC, would you be willing to relicense it as Apache-2.0 WITH LLVM-exception for inclusion within compiler-rt, please? If so I'm happy to pick up getting it through Phab.

**Comment by sebpop** [comment]
Yes, please adapt the code from my patch https://github.com/gcc-mirror/gcc/commit/bc25483c055d62f94f8c289f80843dda3c4a6ff4 to compiler-rt and please use an appropriate license for that.  Thank you.
