### ISSUE TITLE
[flang] [mlir] Why is `-mmlir --math-runtime=precise` not enabled by default when the optimization level is -O2?

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#63498]
This issue is not a bug report, just a question.  My question is, why is `-mmlir --math-runtime=precise` not enabled by default when the optimization level is `-O2`?

Here's the background to this question. 

I checked if Flang-new passes the Netlib LAPACK tests. In LAPACK's Makefile, the optimization level of the Fortran compiler is `-O2`, and if you use this as it is, you can run the test as follows.

```console
$ diff make.inc.example make.inc
9c9
< CC = clang
---
> CC = gcc
20,21c20,21
< FC = flang-new
< FFLAGS = -O2
---
> FC = gfortran
> FFLAGS = -O2 -frecursive
23c23
< FFLAGS_NOOPT = -O0
---
> FFLAGS_NOOPT = -O0 -frecursive
46c46
< #TIMER = INT_ETIME
---
> TIMER = INT_ETIME
50c50
< TIMER = INT_CPU_TIME
---
> #TIMER = INT_CPU_TIME
$ make
```

I used LAPACK 3.11.0 and got the following result:

```console
                        -->   LAPACK TESTING SUMMARY  <--
                Processing LAPACK Testing output found in the TESTING directory
SUMMARY                 nb test run     numerical error         other error
================        ===========     =================       ================
REAL                    1327023         0       (0.000%)        0       (0.000%)
DOUBLE PRECISION        1327845         0       (0.000%)        0       (0.000%)
COMPLEX                 282008          27027   (9.584%)        1855    (0.658%)
COMPLEX16               282791          27170   (9.608%)        1856    (0.656%)

--> ALL PRECISIONS      3219667         54197   (1.683%)        3711    (0.115%)
```

You can see errors in COMPLEX and COMPLEX16 tests. Then, after I enabled `-mmlir --math-runtime=precise`, I ran the test again as follows and got the following result:
```console
$ diff make.inc.example make.inc
9c9
< CC = gcc
---
> CC = clang
20,21c20,21
< FC = gfortran
< FFLAGS = -O2 -frecursive
---
> FC = flang-new
> FFLAGS = -O2 -mmlir --math-runtime=precise
23c23
< FFLAGS_NOOPT = -O0 -frecursive
---
> FFLAGS_NOOPT = -O0
46c46
< TIMER = INT_ETIME
---
> #TIMER = INT_ETIME
50c50
< #TIMER = INT_CPU_TIME
---
> TIMER = INT_CPU_TIME
$ make
```

```console
                        -->   LAPACK TESTING SUMMARY  <--
                Processing LAPACK Testing output found in the TESTING directory
SUMMARY                 nb test run     numerical error         other error
================        ===========     =================       ================
REAL                    1327023         0       (0.000%)        0       (0.000%)
DOUBLE PRECISION        1327845         0       (0.000%)        0       (0.000%)
COMPLEX                 786775          0       (0.000%)        0       (0.000%)
COMPLEX16               787842          0       (0.000%)        0       (0.000%)

--> ALL PRECISIONS      4229485         0       (0.000%)        0       (0.000%)
```

As you can see, in this case, no errors were observed at all.

Personally, I don't like the default state where it gives errors in tests of very famous apps like LAPACK. Also in my opinion, if the optimization level is `-O2`, it is desirable to turn off optimizations that cause numerical errors. I think that's why LAPACK's Makefile also specifies `-O2` instead of `-Ofast`.

This is a matter of policy and may not be an issue that I should insist on further. However, I would like to know if some decisions have already been made in Flang community. I have noticed that the simillar issue (https://github.com/llvm/llvm-project/issues/58799) is still open.

**Comment by kiranchandramohan** [comment]
Thanks for the question. The MLIR complex dialect lowerings are not as precise as the Math dialect lowerings, possibly due to low investment in that area. We have recently seen in our experiments that the precision of Complex Dialect conversion to Standard (arith, math) is low. We cannot use the Complex Dialect to Libm conversion due to ABI issues. Given this situation, I think we should disable the lowering to MLIR Complex dialect unless the `-fapprox-func` is specified (as suggested by @vzakhari).

**Comment by k-arrows** [comment]
Thank you for the clarification. Your explanation makes sense to me. I think the problem I mentioned in this issue is almost the same as the original issue, but I hope I can contribute to the discussion in some way by using LAPACK as an example. I will close this issue because now I know what I wanted to know, but I hope that the discussion on this matter will move forward.

**Comment by kiranchandramohan** [comment]
I will make the change this week.
