### ISSUE TITLE
Missing llabs() builtin function

### ISSUE THREAD

**Issue by DamjanJovanovic** [llvm/llvm-project#63493]
On FreeBSD we cannot compile Wine's unit tests with Clang because the `llabs()` builtin function is missing:

```console
lld-link: error: undefined symbol: __declspec(dllimport) _llabs
```

This issue was already reported in 2011 and was closed invalid :cry:, but it is a real bug: https://github.com/llvm/llvm-project/issues/9928

FreeBSD Bugzilla issue: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=271373

**Comment by efriedma-quic** [comment]
Testcase?

**Comment by arsenm** [comment]
> Testcase?

I assume this is the noted testcase in #9928, which seems to be trying to locally redefine llabs. 

```
long long a = -1;
long long llabs (long long);
void abort (void);
int
main()
{
if (llabs (a) != 1)
abort ();
return 0;
}
long long llabs (long long b)
{
abort ();
}
```

The testcase is undefined, so this is a bug in the original program

**Comment by DamjanJovanovic** [comment]
Here's a testcase:

llabs.c:
```
void _start()
{
    long long n = 0;
    n = llabs(n);
}
```

$ gcc12 llabs.c -o llabs -nostdlib
builds
$ clang15 llabs.c -o llabs -nostdlib
ld: error: undefined symbol: llabs

**Comment by aokblast** [comment]
When I am building the world, I suffer from the following error:

```
ld: error: duplicate symbol: hexdump
>>> defined at sanitizer_common_interceptors.inc:10361 (/usr/src/contrib/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_common_interceptors.inc:10361)
>>>            asan_interceptors.o:(__interceptor_hexdump) in archive /usr/obj/usr/src/amd64.amd64/tmp/usr/lib/clang/16/lib/freebsd/libclang_rt.asan-x86_64.a
>>> defined at mpsutil.c:166 (/usr/src/usr.sbin/mpsutil/mpsutil.c:166)
>>>            mpsutil.o:(.text+0x1350)
```

I think hexdump is not the libc function thus it would't disable asan in the build-tool stage then finally cause this error. 

I try to build mpsutil manually without asan, however, there are more libraries define their own hexdump and cause same error. Thus I think it is not a good workaround. Currently, I don't have any idea now, maybe we should erase hexdump interception in asan?

**Comment by tbaederr** [comment]
> The testcase is undefined, so this is a bug in the original program

So we should close this issue, too?

**Comment by aokblast** [comment]
Oops, I comment on the wrong issue. Sorry!

**Comment by DamjanJovanovic** [comment]
Changing code which calls llabs() to call __builtin_llabs() instead, fixes the issue.

So what is the problem? Is some header file missing this?
#define llabs(a,b) __builtin_llabs(a,b)

**Comment by zygoloid** [comment]
> ```
> void _start()
> {
>     long long n = 0;
>     n = llabs(n);
> }
> ```

Clang 18 onwards produces a binary for this testcase that doesn't reference `llabs` even at `-O0`. Earlier versions only replace `llabs` with the builtin when optimizing (at `-O1` and above). While I don't think it's reasonable to rely on this behavior, especially at `-O0`, this should at least work with recent versions of Clang, or if you enable optimizations when building this test.

**Comment by DamjanJovanovic** [comment]
You're right, my test case (compiling Wine's unit tests) passes with Clang 18, with only 1 remaining error for the round() function, which should be reported in a different issue.

Thank you so much!

Closing.
