### ISSUE TITLE
[SelectionDAG] Infinite loop when canonicalizing ABDU nodes with constants

### ISSUE THREAD

**Issue by Benjins** [llvm/llvm-project#63491]
The following IR shows a reduced repro: trying to compile it with `llc` will cause SelectionDAG to get into an infinite loop

```llvm
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

define <1 x i64> @do_stuff() {
  %1 = tail call <8 x i8> @llvm.aarch64.neon.umax.v8i8(<8 x i8> zeroinitializer, <8 x i8> <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>)
  %2 = tail call <8 x i8> @llvm.aarch64.neon.uabd.v8i8(<8 x i8> %1, <8 x i8> <i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1>)
  %3 = zext <8 x i8> %2 to <8 x i16>
  %4 = bitcast <8 x i16> %3 to <4 x i32>
  %5 = shufflevector <4 x i32> %4, <4 x i32> zeroinitializer, <2 x i32> <i32 0, i32 1>
  %6 = shufflevector <8 x i8> %2, <8 x i8> zeroinitializer, <16 x i32> <i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %7 = bitcast <16 x i8> %6 to <2 x i64>
  %8 = shufflevector <2 x i64> %7, <2 x i64> zeroinitializer, <1 x i32> zeroinitializer
  %9 = tail call <1 x i64> @llvm.aarch64.neon.saddlp.v1i64.v2i32(<2 x i32> %5)
  %10 = or <1 x i64> %8, %9
  ret <1 x i64> %10
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <8 x i8> @llvm.aarch64.neon.umax.v8i8(<8 x i8>, <8 x i8>) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <8 x i8> @llvm.aarch64.neon.uabd.v8i8(<8 x i8>, <8 x i8>) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <1 x i64> @llvm.aarch64.neon.saddlp.v1i64.v2i32(<2 x i32>) #0

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(none) }
```

During post-legalize combine, we have this DAG:
```
SelectionDAG has 19 nodes:
    t51: v8i8 = BUILD_VECTOR Constant:i32<255>, Constant:i32<255>, Constant:i32<255>, Constant:i32<255>, Constant:i32<255>, Constant:i32<255>, Constant:i32<255>, Constant:i32<255>
    t52: v8i8 = AArch64ISD::MOVI Constant:i32<1>
  t39: v8i8 = abdu t51, t52
    t0: ch,glue = EntryToken
          t46: v16i8 = insert_subvector undef:v16i8, t39, Constant:i64<0>
        t47: v8i8 = AArch64ISD::DUPLANE8 t46, Constant:i64<0>
      t35: v1i64 = bitcast t47
            t11: v8i16 = zero_extend t39
          t37: v4i16 = extract_subvector t11, Constant:i64<0>
        t38: v2i32 = bitcast t37
      t43: v1i64 = AArch64ISD::SADDLP t38
    t30: v1i64 = or t35, t43
  t32: ch,glue = CopyToReg t0, Register:v1i64 $d0, t30
  t33: ch = AArch64ISD::RET_GLUE t32, Register:v1i64 $d0, t32:1
```
We try to combine `t11: v8i16 = zero_extend t39`, which hits `performExtendCombine`, which will eventually call into `canonicalizeCommutativeBinop` for the `abdu` node:
https://github.com/llvm/llvm-project/blob/67e05d380c2253319c22451d340e2e3c2043b6d8/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp#L6281-L6284

This swaps the two operands to move the `BUILD_VECTOR` to the right-hand side:
```
t54: v8i8 = abdu t52, t51
t55: v8i16 = zero_extend t54
```

We then try to combine this new node, `t54`. `DAGCombiner::combine()` doesn't manage to combine it with other operations, so it falls through to this code that tries to replace it with an existing commutation:
https://github.com/llvm/llvm-project/blob/67e05d380c2253319c22451d340e2e3c2043b6d8/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp#L2079-L2089

But because that checks `isa<ConstantSDNode>(N0)` instead of `isConstantIntBuildVectorOrConstantInt`, it doesn't realise that it's already had its constant canonicalized to the RHS, and so we replace the new `abdu` with the old, uncanonicalised `abdu`. After that replacement and pruning dead nodes, we get back to where we started:
```
SelectionDAG has 19 nodes:
    t51: v8i8 = BUILD_VECTOR Constant:i32<255>, Constant:i32<255>, Constant:i32<255>, Constant:i32<255>, Constant:i32<255>, Constant:i32<255>, Constant:i32<255>, Constant:i32<255>
    t52: v8i8 = AArch64ISD::MOVI Constant:i32<1>
  t39: v8i8 = abdu t51, t52
    t0: ch,glue = EntryToken
          t46: v16i8 = insert_subvector undef:v16i8, t39, Constant:i64<0>
        t47: v8i8 = AArch64ISD::DUPLANE8 t46, Constant:i64<0>
      t35: v1i64 = bitcast t47
            t55: v8i16 = zero_extend t39
          t37: v4i16 = extract_subvector t55, Constant:i64<0>
        t38: v2i32 = bitcast t37
      t43: v1i64 = AArch64ISD::SADDLP t38
    t30: v1i64 = or t35, t43
  t32: ch,glue = CopyToReg t0, Register:v1i64 $d0, t30
  t33: ch = AArch64ISD::RET_GLUE t32, Register:v1i64 $d0, t32:1
```
And we will continue to do these in a loop

A bisect showed that this started happening in 120ce83660dea7e70abe1c8f9408f39fe2502f8d, which marked `ABDU` as commutative. However, I think this was just exposing a pre-existing issue. I think the underlying cause is `DAGCombiner::combine` uses `isa<ConstantSDNode>()` instead of `isConstantIntBuildVectorOrConstantInt()` like is used in `SelectionDAG::getNode`/`SelectionDAG::canonicalizeCommutativeBinop`, which would have been changed in commit 4f8fdf78279f0cb298dc0dc215ee56b0342235ee

I have verified that this still repros on the latest trunk, 5f8e4315979c266f3610f89d11a48bd43809533d

For priority/triage purposes: this was not found in manually-written code, but was hit by a fuzzer to test SIMD codegen

**Comment by davemgreen** [comment]
^ Thanks
