### ISSUE TITLE
LV /home reports full after extending on Arch VM

### ISSUE THREAD

**Issue by maletinmarko** [llvm/llvm-project#63501]
Hi everyone,

I really need help with this one. 
I have an Arch VM configured for doing some programming projects, and this was the first time i configured it with LVM.
By mistake, I put only 20GB for my /home partition, and at some point I had to extend it.
I did extend it, both in the VirtualBox, and after that extended the partition, but it still shows as full. Now please check the following outputs.

Here is the output from "lsblk -e7"
````
NAME                  MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda                     8:0    0  100G  0 disk 
├─sda1                  8:1    0  500M  0 part 
└─sda2                  8:2    0 99.5G  0 part 
  ├─volgroup0-lv_root 254:0    0   30G  0 lvm  /var/lib/snapd/snap
  │                                            /
  └─volgroup0-lv_home 254:1    0 69.5G  0 lvm  /home
sr0                    11:0    1  1.8G  0 rom  
````

The size reports as 69.5, which is correct, the new extended size.
However check this, this is the result of "df -h":
```
Filesystem                     Size  Used Avail Use% Mounted on
dev                            3.8G     0  3.8G   0% /dev
run                            3.8G  1.2M  3.8G   1% /run
/dev/mapper/volgroup0-lv_root   30G   18G   11G  62% /
/dev/mapper/volgroup0-lv_home   20G   19G  3.8M 100% /home
Downloads                      821G  440G  382G  54% /home/marko/Shared
tmpfs                          774M   88K  774M   1% /run/user/1000
```
Still the old size, and reports as full.
Furthermore, "df -i":
```
Filesystem                     Inodes   IUsed   IFree IUse% Mounted on
dev                            987526     617  986909    1% /dev
run                            990107     875  989232    1% /run
/dev/mapper/volgroup0-lv_root 1966080  375888 1590192   20% /
/dev/mapper/volgroup0-lv_home 1278608  170641 1107967   14% /home
Downloads                        1000 -999000 1000000     - /home/marko/Shared
tmpfs                          198021      91  197930    1% /run/user/1000
```

Any help would be greatly appreciated!

**Comment by Endilll** [comment]
Here we work on LLVM compiler infrastructure, not on Logical Volume Manager.
You should try asking on https://bugs.archlinux.org/ and https://bugzilla.kernel.org/
