### ISSUE TITLE
lld is NOT a drop-in replacement for ld under Linux

### ISSUE THREAD

**Issue by wgianopoulos** [llvm/llvm-project#63504]
You claim this is drop-in replacement for ld. but your documentation says it does not respect the LD_LIBRAY_PATH env variable.
In my opinion you either need to respect that variable or stop saying it is a drop-in replacement.
To not support LD_LIBRARY_PATH and claim to be a drop-in replacement is false advertising.

**Comment by wgianopoulos** [comment]
Worse yet on a redhat based Linux distro where /us5/lib64 is the default library search location it seems to ignore that and only looking in /usr/lib and ignore the matching files there because of wrong architecture and then never looks at the OS provided default location of /usr/lib64   this all seemed to work with clang-15

**Comment by thesamesam** [comment]
`LD_LIBRARY_PATH` is consulted at _runtime_ by the **dynamic** runtime loader, not the linker.
