### ISSUE TITLE
[Flang] Output this message (IEEE arithmetic exceptions signaled: INEXACT) when STOP statement exists

### ISSUE THREAD

**Issue by ohno-fj** [llvm/llvm-project#63513]
```
Version of flang-new : 17.0.0(f6c8a8e9cb7d8b8abb382b52c88fb287a6f27a2b)
```

When the test program is executed, the following message is output.
```
  IEEE arithmetic exceptions signaled: INEXACT
```
If `STOP` statement in the test program is deleted, the above message is not output.

The following are the test program, results of Flang-new, Gfortran and ifort compilation and execution.

d12_6.f90:
```fortran
program D12
  integer::N=75
  real(kind=8),parameter::A=1.6
  write (6,*) A**N
  stop
end program D12
```

```
$ flang-new -flang-experimental-exec d12_6.f95; ./a.out
 A**N =  2.0370382529008532E+15
Fortran STOP
IEEE arithmetic exceptions signaled: INEXACT
$
```

```
$ gfortran d12_6.f95; ./a.out
 A**N =    2037038252900853.2
$
```

```
$ cp -p d12_6.f95 d12_6.f90
$ ifort d12_6.f90; ./a.out
 A**N =   2.037038252900849E+015
$
```

**Comment by luporl** [comment]
The issue still happens when the test program is built with `flang-new -flang-experimental-hlfir`.

**Comment by klausler** [comment]
This behavior is required by Fortran 2018 subclause 11.4 paragraph 3.  Use `QUIET=.true.` on the STOP statement to suppress the output, or set `NO_STOP_MESSAGE=1` in the execution environment.
