### ISSUE TITLE
Source code .zip file download as corrupt

### ISSUE THREAD

**Issue by CompSciDude1** [llvm/llvm-project#63511]
I tried to download the 16.0.6 source code as .zip.  I try to open it in Windows and I get this:

<img width="419" alt="image" src="https://github.com/llvm/llvm-project/assets/95832278/4005f6c9-7960-4d54-8b26-17e00e901b2e">

It opens in 7-zip, but it does not extract successfully.  It shows me the following errors:

Data error : llvm-project-llvmorg-16.0.6\llvm\test\CodeGen\AMDGPU\GlobalISel\regbankselect-atomicrmw-umin.mir.

Also, trying to Extract here with 7-zip produces another error:

path\to\llvm-project-llvmorg-16.0.6.zip
Unexpected end of data

**Comment by asl** [comment]
This zip file is autogenerated by GitHub, not by LLVM project. I would suggest you to report issue there. Likely there is something in the middle, e.g. an antivirus, that might intervene with the extraction process

**Comment by CompSciDude1** [comment]
I think it may have had something to do with my internet connection.  I was on wireless when i encountered the problem.  i switched to wired and it downloaded fine.
