### ISSUE TITLE
The lldb python SBDebugger.GetSetting() function is not accessible

### ISSUE THREAD

**Issue by eanyanwu** [llvm/llvm-project#63538]
I can't seem to make use of [this](https://lldb.llvm.org/python_api/lldb.SBDebugger.html#lldb.SBDebugger.GetSetting) function :/

Am I doing something wrong?

```
(lldb) script
Python Interactive Interpreter. To exit, type 'quit()', 'exit()' or Ctrl-D.
>>> lldb.debugger.GetSetting("term-width")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'SBDebugger' object has no attribute 'GetSetting'
```

Version info (though, now that I am looking I don't actually know where I can find what the latest version is) 
```console
> lldb --version
lldb version 15.0.7
```

**Comment by bulbazord** [comment]
Just built lldb from top-of-tree LLVM and I was not able to reproduce this.

```
(lldb) version
lldb version 18.0.0git (git@github.com:llvm/llvm-project.git revision 1684c65bc997a8ce0ecf96a493784fe39def75de)
  clang revision 1684c65bc997a8ce0ecf96a493784fe39def75de
  llvm revision 1684c65bc997a8ce0ecf96a493784fe39def75de
(lldb) script
Python Interactive Interpreter. To exit, type 'quit()', 'exit()' or Ctrl-D.
>>> lldb.debugger.GetSetting("term-width")
80
```
Could you try again with a more recent release of LLDB? 15.0.7 has been out for over a year and we can no longer update that version.

**Comment by eanyanwu** [comment]
😅  thanks for taking the time to look into this. I am way past this right now. Will close the issue
