### ISSUE TITLE
Possible libc++ issue in 16.0.6 static build, MacOS Monterey

### ISSUE THREAD

**Issue by cblc** [llvm/llvm-project#63557]
macOS Monterey 12.6, Xcode 14.0.1, LLVM 16.0.6 (desired build: all libs static, and everything universal x86_64 + Arm64)

First of all, I'd like to know if you believe the build I got is good for production use, or if the errors that appeared suggest to rebuild again.

After many tries adjusting settings as trial and error until I got the least errors I could with `make check-all`, I've finally built LLVM 16.0.6 with all the libs static, as universal x86_64 + Arm64, in several steps:

In the first build, the executables still depended on the dynamic libc++ provided by Apple, and I got just two failures from `make check-all`, which made feel very optimistic:

```console
Failed Tests (2):
  libomp :: barrier/omp_barrier.c
  llvm-libc++-static.cfg.in :: std/input.output/iostream.objects/init.pass.cpp


Testing Time: 4470.88s
  Skipped          :    47
  Unsupported      : 20114
  Passed           : 80255
  Expectedly Failed:   176
  Failed           :     2
```

Then I performed a second build, with exactly the same settings, but using the compilers from the previous step. This time the resulting compilers had libc++ statically linked, and they no longer depended on the Apple libc++:

```console
$ otool -L clang-16
clang-16:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)

$ file clang-16 
clang-16: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64Mach-O 64-bit executable x86_64] [arm64]
clang-16 (for architecture x86_64):	Mach-O 64-bit executable x86_64
clang-16 (for architecture arm64):	Mach-O 64-bit executable arm64
```

But unfortunately, I got errors that didn't appear in the first step (the two errors from step 1 also happened again):

```console
Failed Tests (15):
  ThreadSanitizer-x86_64 :: Darwin/libcxx-call-once.mm
  ThreadSanitizer-x86_64 :: cxa_guard_acquire.cpp
  ThreadSanitizer-x86_64 :: static_init2.cpp
  ThreadSanitizer-x86_64 :: static_init4.cpp
  UBSan-AddressSanitizer-x86_64 :: TestCases/TypeCheck/vptr-non-unique-typeinfo.cpp
  UBSan-AddressSanitizer-x86_64 :: TestCases/TypeCheck/vptr-virtual-base-construction.cpp
  UBSan-AddressSanitizer-x86_64 :: TestCases/TypeCheck/vptr.cpp
  UBSan-Standalone-x86_64 :: TestCases/TypeCheck/vptr-non-unique-typeinfo.cpp
  UBSan-Standalone-x86_64 :: TestCases/TypeCheck/vptr-virtual-base-construction.cpp
  UBSan-Standalone-x86_64 :: TestCases/TypeCheck/vptr.cpp
  UBSan-ThreadSanitizer-x86_64 :: TestCases/TypeCheck/vptr-non-unique-typeinfo.cpp
  UBSan-ThreadSanitizer-x86_64 :: TestCases/TypeCheck/vptr-virtual-base-construction.cpp
  UBSan-ThreadSanitizer-x86_64 :: TestCases/TypeCheck/vptr.cpp
  libomp :: barrier/omp_barrier.c
  llvm-libc++-static.cfg.in :: std/input.output/iostream.objects/init.pass.cpp


Testing Time: 3642.22s
  Skipped          :    47
  Unsupported      : 18923
  Passed           : 78461
  Expectedly Failed:   151
  Failed           :    15
```

Given that the only difference between the used clang in the step 1 and in the step 2 is that the former one was built with Xcode and was linked to the Apple libc++, while the later was built with Clang 16.0.6 with the LLVM 16.0.6 libc++ statically linked on them, I'm suspecting that perhaps that error related to libc++ (`std/input.output/iostream.objects/init.pass.cpp`) might be an issue. Its log is:

```console
# command stderr:
Assertion failed: (std::memcmp(check.cerr_mem_dump, (char const*)&std::cerr, sizeof(std::cerr)) == 0), function main, file init.pass.cpp, line 88.

error: command failed with exit status: 250
```

While the log for the OpenMP error (`barrier/omp_barrier.c`) is:

```console
# command stderr:
OMP: Error #111: Memory allocation failed.

error: command failed with exit status: -6
```

I can provide the full and detailed build log if necessary, as well as the log for the new errors that appeared in step 2.

The settings I used for the build are as follows (same settings for both steps):

```shell
cmake -G "Unix Makefiles" -DSANITIZER_MIN_OSX_VERSION=12.0 -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DRUNTIMES_CMAKE_ARGS="-DSANITIZER_MIN_OSX_VERSION=12.0;-DCMAKE_OSX_DEPLOYMENT_TARGET=12.0;-DCMAKE_OSX_ARCHITECTURES=arm64|x86_64;-DCMAKE_VERBOSE_MAKEFILE=ON" -DCMAKE_BUILD_TYPE=Release -DLIBCXX_ENABLE_SHARED=OFF -DLIBCXX_ENABLE_STATIC=ON -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON -DLIBCXXABI_ENABLE_STATIC_UNWINDER=ON -DLIBCXXABI_ENABLE_SHARED=OFF -DLIBUNWIND_ENABLE_SHARED=OFF -DLIBCXX_STATICALLY_LINK_ABI_IN_STATIC_LIBRARY=ON -DLIBCXXABI_STATICALLY_LINK_UNWINDER_IN_STATIC_LIBRARY=ON -DLIBOMP_ENABLE_SHARED=FALSE -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_PATH -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_SHARED_LIBS=OFF -DLIBCLANG_BUILD_STATIC=ON -DLLVM_ENABLE_ZSTD=OFF -DLLVM_TARGETS_TO_BUILD="AArch64;ARM;X86" -DLLVM_ENABLE_PROJECTS="clang;compiler-rt;openmp" -DLLVM_ENABLE_RUNTIMES=all ../src/llvm-project-16.0.6.src/llvm
```

And yes, the `SANITIZER_MIN_OSX_VERSION` option is necessary, together with a previous `export MACOSX_DEPLOYMENT_TARGET=12.0`, because if you don't do both of them, then the CMake log has a warning in the lines of "12.6 too new, using 10.10 deployment target instead" (I type from memory, not copy-paste), which seems inoffensive but however triggers a lot of sanitizer `make check-all` errors later because of mismatched linked objects.

If you think the settings can be improved tell me, but keep in mind that wish a static build and universal x86_64 + Arm64.

Also, if you feel my build is "good enough" for production use, I'd be happy to know about it too.

**Comment by ldionne** [comment]
I'm going to close this for the time being to keep our issues list tidy, but please reopen if you have additional information to provide.
