### ISSUE TITLE
Support for func calls with SVE fixed length vector argument

### ISSUE THREAD

**Issue by v01dXYZ** [llvm/llvm-project#63583]
Hello,

What is the current support of function calls with fixed length vector arguments when SVE is used for fixed length vectors (`AArch64TargetLowering::useSVEForFixedLengthVectorVT`) ?

It doesn't seem supported at all, as the calling convention tablegen file seems to only mention 128b vector types.

Related to #63025

labels: `backend:aarch64` `sve`

**Comment by v01dXYZ** [comment]
Are github issues the right way to ask question ? Is there a better channel for that ?

**Comment by EugeneZelenko** [comment]
https://discourse.llvm.org is better place for questions.

**Comment by v01dXYZ** [comment]
Closing as lack of reaction within one week.
