### ISSUE TITLE
[AVR] llvm-mc produces wrong instructions for RJMP

### ISSUE THREAD

**Issue by 257m** [llvm/llvm-project#63609]
I am running the command to turn a file of avr assembly into an object
```shell
llvm-mc -filetype=obj -arch=avr -mcpu=atmeg328p all.s
```

Here is the assembly file:
```asm
.text
.set __tmp_reg__, 0
.set __zero_reg__, 1
.set __SREG__, 63
.set __SP_H__, 62
.set __SP_L__, 61
    .file   "llvm-link"
    .globl  main                            ; -- Begin function main
    .p2align    1
    .type   main,@function
main:                                   ; @main
; %bb.0:
    ldi r24, -1
.LBB0_1:                                ; =>This Inner Loop Header: Depth=1
    out 4, r24
    out 5, r1
    rjmp    .LBB0_1
.Lfunc_end0:
    .size   main, .Lfunc_end0-main
                                        ; -- End function
```

The problem is instead of producing `rjmp -4` as expected it produces `rjmp +0`. This is a obvious bug because it would just create an infinite loop.

Here is the `objdump all.o`
```objdump
obj/all.o:      file format elf32-avr

Disassembly of section .text:

00000000 <main>:
       0: 8f ef         ldi     r24, 0xff
       2: 84 b9         out     0x4, r24
       4: 15 b8         out     0x5, r1
       6: 00 c0         rjmp    .+0
```

6: should be `04 c8` not `00 c0`. When I pass the assembly to avra (without the Clang directives) it produces the correct hex.

**Comment by 257m** [comment]
Maybe this isn't a issue with rjmp specifically but rather resolving labels? Because I replaced the .LBB0_1 with -6 and it ran fine

**Comment by benshi001** [comment]
I guess you might be a bit confused. The `llvm-mc` only produces a relocatable ELF, in which the destination of `RJMP` has not been filled. You have to do a further link step, then you will get your expected result.

Here are my steps,

```
llvm-mc -filetype=obj -arch=avr -mcpu=atmega328p all.s -o all.o
avr-ld all.o -o all.elf
avr-objdump -d all.elf
```

Then you will see the `RJMP` is correct. As follow
```
00000000 <main>:
   0:	8f ef       	ldi	r24, 0xFF	; 255
   2:	84 b9       	out	0x04, r24	; 4
   4:	15 b8       	out	0x05, r1	; 5
   6:	fd cf       	rjmp	.-6      	; 0x2 <__zero_reg__+0x1>
```

**Comment by benshi001** [comment]
I suggest you also compile your program with avr-gcc

```
avr-gcc all.s -o all.elf
avr-objdump -d all.elf
```

You can see avr-gcc produces the same result as llvm does.
