### ISSUE TITLE
Miscompilation in LoopVectorizer

### ISSUE THREAD

**Issue by d-makogon** [llvm/llvm-project#63602]
Repro: https://godbolt.org/z/6MxeMx97G

The source IR is for the following code:
```cpp
int i = 1;
while ((i += 3) < 383) {
  arr[i] = 1;
  arr[i - 1] &= 1;
  arr[i] += 1;
}
```
The `arr` is filled with zeroes initially.
The program just stores `2` in each third element of the array starting from the index `4`.
After the vectorizer pass however the part of the loop that is processed in the vector loop is filled with just ones.

The issue in the vector loop is the following:
First we load the elements for which we need to do the addition of `1` (corresponding to the line `arr[i] += 1`) into `%strided.vec3`.
Then we store the ones into each third index: `store i32 1, ptr %21, align 4`;   `store i32 1, ptr %22, align 4`;   `...`.
And then we do the addition of `1` to the **previously loaded** vector of values: `%54 = add <8 x i32> %strided.vec3, <i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1>`, and after that we perform the stores: 
```ll
%55 = extractelement <8 x i32> %54, i32 0
store i32 %55, ptr %21, align 4
```
```ll
%56 = extractelement <8 x i32> %54, i32 1
store i32 %56, ptr %22, align 4
```
...
So the issue is that the `+1` is done for the values that are loaded from the memory before the stores of `1`. So we end up storing `0+1=1` in each third index starting from 4.

**Comment by fhahn** [comment]
Looks like an mis-compile related to creating an invalid interleave group. Let me take a look.

**Comment by d-makogon** [comment]
Thanks @fhahn! I've done some investigation too, here's what I found out.
In the source IR the memory accesses are in the following order:
```
load  A[i + 4]  (1)
store A[i + 3]  (2)
load  A[i + 2]  (3)
store A[i + 2]  (4)
load  A[i + 3]  (5)
store A[i + 3]  (6)
```

The InterleavedAccessInfo traverses those in a bottom-up order. When analyzing (5) it checks whether we can reorder the access with the ones that precede it. We can reorder (5) and (3), so IAI creates a new group (3), (5). Then, it stops at (2) because we can't reorder (5) and (2). After that, it analyzes (3). It checks whether we can reoder (3) and (2), then (3) and (1). And yes, we can reorder those. And so it adds (1) into the group of (2), which is already created. And this is the issue. Here we get a load group (5), (3), (1) even though we can't reorder (5) and (1) as there's (2) between them.
I guess to avoid that we'd need to somehow prohibit adding new accesses into a group if we encounter an access that can't reordered with another access in the group. What do you think?

**Comment by fhahn** [comment]
It looks like the code to analyze interleaving is missing handling for load groups when detecting a conflicting load-store pair. I put up  https://reviews.llvm.org/D154309 as proposed fix.

**Comment by fhahn** [comment]
@d-makogon I am curious how you found that issue. Did you by any chance catch this using auto-generated tests or by investigating a mis-compile in some project?

**Comment by fhahn** [comment]
Thanks @d-makogon
