### ISSUE TITLE
[REGRESSION][COROUTINES] infinite loop in addMustTailToCoroResumes

### ISSUE THREAD

**Issue by avikivity** [llvm/llvm-project#63639]
Compiling the attached preprocessed source file, perf tells me there's an infinite loop:

```
  99.90%  clang-17  [.] addMustTailToCoroResumes
```

Command line: /home/avi/clang.bin/bin/clang++  -x c++ -Werror=unused-result -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -DSEASTAR_API_LEVEL=7 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_DEBUG -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_TYPE_ERASE_MORE -DFMT_SHARED -I/usr/include/p11-kit-1 -ffile-prefix-map=/home/avi/scylla=. -march=westmere -DDEBUG -DSANITIZE -DDEBUG_LSA_SANITIZER -DSCYLLA_ENABLE_ERROR_INJECTION -Og -DSCYLLA_BUILD_MODE=debug -g -gz -iquote. -iquote build/debug/gen --std=gnu++20 -ffile-prefix-map=/home/avi/scylla=. -march=westmere -DBOOST_TEST_DYN_LINK -DNOMINMAX -DNOMINMAX -fvisibility=hidden -Wall -Werror -Wno-mismatched-tags -Wno-tautological-compare -Wno-c++11-narrowing -Wno-ignored-attributes -Wno-overloaded-virtual -Wno-unused-command-line-argument -Wno-unsupported-friend -Wno-delete-non-abstract-non-virtual-dtor -Wno-braced-scalar-init -Wno-implicit-int-float-conversion -Wno-delete-abstract-non-virtual-dtor -Wno-psabi -Wno-narrowing -Wno-nonnull -Wno-uninitialized -Wno-error=deprecated-declarations -DXXH_PRIVATE_API -DSEASTAR_TESTING_MAIN -DFMT_DEPRECATED_OSTREAM -c -o /dev/null multishard.i

[repro.zip](https://github.com/llvm/llvm-project/files/11929499/repro.zip)

**Comment by avikivity** [comment]
Bisected to:

commit 0a7ff0960e33b6b27961afa5cbb7dd9eb4f1a283
Author: Chuanqi Xu <yedeng.yd@linux.alibaba.com>
Date:   Fri Jun 30 13:59:39 2023 +0800

    [Coroutines] Don't transform cmpinst prematurely in simplifyTerminatorLeadingToRet
    
    Previously, we would try to transform cmpinst in
    simplifyTerminatorLeadingToRet if we found it was a constant. However,
    this is incorrect.
    
    Since the resolved constants in simplifyTerminatorLeadingToRet are not
    truely constants. They are basically constants along cerntain code
    paths.
    
    In this way, it is clearly incorrect to transform the compare
    instruction to a constant.
    
    It will cause confusing miscompilations. This patch tries to fix this.

cc: @ChuanqiXu9

**Comment by ChuanqiXu9** [comment]
Thanks for reporting this : )
