### ISSUE TITLE
wrong code with clang-trunk, still worked with clang-16.0

### ISSUE THREAD

**Issue by m9710797** [llvm/llvm-project#63634]
I managed to reduce the testcase to:
https://godbolt.org/z/8T7h1Pb8M

As far as I can tell, there's no undefined behavior in this testcase.
Both clang-16 and gcc-13 produce the code that I was expecting.
But clang-trunk produces different (wrong?) x86 code.

**Comment by fhahn** [comment]
Looks like an X86 backend specific issue. The IR after optimizations is the same for both clang-16 and current `main` AFAICT.

**Comment by m9710797** [comment]
This seems to be fixed. Thanks.
At least with today's version of "x86-64 clang (assertions trunk)" on compiler explorer it works fine.

**Comment by fhahn** [comment]
Great, thanks for confirming. Closing.
