### ISSUE TITLE
[doc] incorrect build instructions for libcxx

### ISSUE THREAD

**Issue by greg7mdp** [llvm/llvm-project#63643]
In the [build instructions for libcxx, bootstrapping build](https://libcxx.llvm.org//BuildingLibcxx.html#bootstrapping-build), an incorrect definition is provided: 

`-DLLVM_RUNTIME_TARGETS="<target-triple>"`

which triggers the following error:

```
CMake Error at cmake/modules/LLVMExternalProjectUtils.cmake:147 (add_custom_target):
  add_custom_target called with target name containing a "<".  This character
  is not allowed.
Call Stack (most recent call first):
  runtimes/CMakeLists.txt:337 (llvm_ExternalProject_Add)
  runtimes/CMakeLists.txt:440 (runtime_register_target)
```

I believe it should be something like:

`-DLLVM_RUNTIME_TARGETS="libcxx;libcxxabi;libunwind" `

**Comment by philnik777** [comment]
You are supposed to replace `<target-triple>` with your target triple, e.g. `x86_64-linux-gnu`.
