### ISSUE TITLE
Error: use of undeclared identifier '__builtin_fabsq'` when a newer GCC 13.1.1 snapshot is installed with -fgnuc-version=6.5.0

### ISSUE THREAD

**Issue by ms178** [llvm/llvm-project#63642]
With a recent GCC 13.1.1 snapshot installed from 2023-06-24, I see build errors with Clang-17 (c1dc914a8ca240650d7411d25c75ad7e2a5974e9) with several projects that used to work fine before, e.g. when compiling mold-git, I now see :

```
In file included from <built-in>:1:
In file included from /tmp/makepkg/mold-git/src/build/CMakeFiles/mold.dir/cmake_pch.hxx:5:
In file included from /tmp/makepkg/mold-git/src/mold/elf/mold.h:3:
In file included from /tmp/makepkg/mold-git/src/mold/elf/elf.h:5:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/ostream:40:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/ios:44:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/bits/ios_base.h:41:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/bits/locale_classes.h:40:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/string:54:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/bits/basic_string.h:4097:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/ext/string_conversions.h:43:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/cstdlib:81:
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/bits/std_abs.h:142:12: error: use of undeclared identifier '__builtin_fabsq'
  142 |     return __builtin_fabsf128(__x);
      |            ^
/usr/include/bits/floatn.h:101:31: note: expanded from macro '__builtin_fabsf128'
  101 | #   define __builtin_fabsf128 __builtin_fabsq
      |                               ^

```

This used to work just fine with earlier GCC 13.1.1 and LLVM-17 snapshots. I cannot tell if it is actually a GCC or LLVM/Clang problem.

CPU: Intel Haswell-EP

**Comment by ms178** [comment]
This issue might also come from a more recent Glibc snapshot, as I re-build the whole GCC toolchain from time to time, for some context I came across https://patchwork.ozlabs.org/project/glibc/patch/20220404205805.701759-1-adhemerval.zanella@linaro.org/#2869317 while researching the issue.

**Comment by shafik** [comment]
CC @AaronBallman

**Comment by AaronBallman** [comment]
I think this is a glibc issue in floatn.h -- Clang does not currently implement `__builtin_fabsq` but does implement `__builtin_fabsf128`.

**Comment by ms178** [comment]
@fweimer-rh CC you for awareness, do you agree with Aaron?

**Comment by ms178** [comment]
Would be great if that could be backported to the glibc 2.37 branch.

**Comment by ms178** [comment]
If I remember correctly the Mandriva folks use this "hack" to work around software with bad compiler detection logic to make use of newer and more efficient compiler features for Clang. I don't know if upstream developers care to support that properly though, if not I will close this and am thanking for your work regardless.

**Comment by ms178** [comment]
FWIW, Mandriva now carries adapted patches for GLIBC that workaround this issue, see: https://github.com/OpenMandrivaAssociation/glibc/commit/03368b31db4f887a3ea27d48ece0ea2891abbef9#diff-739d4586c16502a81f16a367b7f9ff00f898edf75ff20786fb5a99395083d3e0

**Comment by ms178** [comment]
Closing in favor of keeping track of this in https://github.com/llvm/llvm-project/issues/97335
