### ISSUE TITLE
__is_trivially_equality_comparable gives wrong answer when arrays are involved

### ISSUE THREAD

**Issue by AMP999** [llvm/llvm-project#63656]
https://godbolt.org/z/T6TEavreh

    struct S {
      std::string a[1];
      bool operator==(const S&) const = default;
    };
    static_assert(__is_trivially_equality_comparable(S)); // oops!

The symptom is that `std::equal` and `std::ranges::equal` produce wrong answers for arrays of `S`.
The root cause is that Clang's (relatively new) builtin `__is_trivially_equality_comparable` incorrectly produces true for `S` when it should produce false. I think `QualType::isTriviallyEqualityComparableType` needs to be updated to check array-element subobjects, as well as member subobjects.

(This is the same issue as #63192, but for a different kind of subobject.)

Thanks to @Quuxplusone for finding this bug

**Comment by philnik777** [comment]
I'll try to get to it on the weekend.
