### ISSUE TITLE
[lldb-vscode] should provide a full Debugger Console

### ISSUE THREAD

**Issue by nolange** [llvm/llvm-project#63654]
Using this Extension will only allow to evaluate expressions, but not the full set of debugger commands (eg. `image list`).

Compare that to [CodeLLDB](https://github.com/vadimcn/codelldb) which offers a full console and even command completion.

**Comment by DavidSpickett** [comment]
You may want to look at https://discourse.llvm.org/t/rfc-lldb-vscode-evaluate-repl-behavior-and-improvements/71667 which seems to address this.

**Comment by DavidSpickett** [comment]
Perhaps you can give some feedback on the thread there, I will post a link to this issue there in any case. (I don't personally work on lldb-vscode)
