### ISSUE TITLE
-fno-hip-fp32-correctly-rounded-divide-sqrt not producing expected fpmath metadata

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#63653]
https://godbolt.org/z/q5v799sYd

I'm not seeing !fpmath metadata when using the flag. It does change the linked OCLC control lib, so I think the driver flag is just not correctly wired up to the codegen flag.

**Comment by yxsamliu** [comment]
seems to be a clang driver bug. fix by https://reviews.llvm.org/D154385
