### ISSUE TITLE
[lldb-vscode] Instructions for vscode seems outdated

### ISSUE THREAD

**Issue by nolange** [llvm/llvm-project#63655]
The steps in the [Readme](https://github.com/llvm/llvm-project/tree/main/lldb/tools/lldb-vscode) wont lead to a working extension, there seems to be substantial difference in current vscode versions. Seems to be required to add an entry to `extensions.json` aswell.

``` json
{
    "identifier": {
        "id": "llvm.lldb-vscode"
    },
    "version": "0.1.0",
    "location": {
        "$mid": 1,
        "fsPath": "/home/lano/.vscode-oss/extensions/llvm.lldb-vscode-0.1.0",
        "path": "/home/lano/.vscode-oss/extensions/llvm.lldb-vscode-0.1.0",
        "scheme": "file"
    },
    "relativeLocation": "llvm.lldb-vscode-0.1.0",
    "metadata": {
        "installedTimestamp": 1688396120102
    }
}
```

I only manages to install the tool by building my own `vsix` with a simple shell script calling the system installed `lldb-vscode` tool.

**Comment by michael-jabbour-sonarsource** [comment]
According to microsoft/vscode#178667, using the command `Developer: Install Extension from Location` is preferred over creating directories manually inside `~/.vscode/extensions`.

This created the `"llvm.lldb-vscode"` entry in `extensions.json` for me.

**Comment by walter-erquinigo** [comment]
@DavidSpickett , Michaels' reference is right. Tbh I haven't installed lldb-vscode manually in at least two years, so I'm not surprised that things have changed. I'll send a PR updating the README. 
Thanks!
