### ISSUE TITLE
[WebAssembly] assert in WebAssemblyAsmPrinter::getOrCreateWasmSymbol (thru Emscripten tot)

### ISSUE THREAD

**Issue by aardappel** [llvm/llvm-project#63657]
Relevant part of stack trace:

```
#10 0x00007f75d24c59f7 llvm::WebAssemblyAsmPrinter::getOrCreateWasmSymbol(llvm::StringRef) WebAssemblyAsmPrinter.cpp:0:0
#11 0x00007f75d24c5def llvm::WebAssemblyAsmPrinter::emitDecls(llvm::Module const&) WebAssemblyAsmPrinter.cpp:0:0
#12 0x00007f75d24c8a97 llvm::WebAssemblyAsmPrinter::emitConstantPool() WebAssemblyAsmPrinter.cpp:0:0
#13 0x00007f75d0c6065c llvm::AsmPrinter::emitFunctionHeader() (/home/runner/emsdk/upstream/bin/../lib/libLLVM-17git.so+0x276b65c)
#14 0x00007f75d0c6341d llvm::AsmPrinter::emitFunctionBody() (/home/runner/emsdk/upstream/bin/../lib/libLLVM-17git.so+0x276e41d)
#15 0x00007f75d24c946b llvm::WebAssemblyAsmPrinter::runOnMachineFunction(llvm::MachineFunction&) WebAssemblyAsmPrinter.cpp:0:0
```

Full log: https://github.com/aardappel/lobster/actions/runs/5447367026/jobs/9909273184

This is with Emscripten `tot` as of today:

```
        git clone --depth 1 https://github.com/emscripten-core/emsdk.git $HOME/emsdk
        $HOME/emsdk/emsdk update-tags
        $HOME/emsdk/emsdk install tot
        $HOME/emsdk/emsdk activate tot
```

I don't have a small repro, sorry. You'd need https://github.com/aardappel/lobster/commit/c632eb77e2f8d6c3df4b67ce17b71067fdc0fd4c and build with the same steps as https://github.com/aardappel/lobster/blob/c632eb77e2f8d6c3df4b67ce17b71067fdc0fd4c/.github/workflows/build.yml#L116-L151

The function that it's unhappy with is `stbi_flip_vertically_on_write` which comes from https://github.com/nothings/stb/blob/master/stb_image.h which may allow a smaller repro.

Given the stack trace I would not be surprised if it turns out I originally caused the bug ;)

**Comment by dschuff** [comment]
I think this the other relevant bit from the log:
```
unexpected runtime library name: frexpf
UNREACHABLE executed at /b/s/w/ir/cache/builder/emscripten-releases/llvm-project/llvm/lib/Target/WebAssembly/WebAssemblyRuntimeLibcallSignatures.cpp:897!
```

This looks very similar to a problem I recently fixed in https://reviews.llvm.org/D152385, and indeed it looks like an  llvm.frexp family of intrinsics is new. Probably the minimal fix would be to add the libcall signatures like we did before, although I don't know enough about the libcalls themselves to know if maybe we should also write some kind of direct lowering for wasm.

**Comment by sbc100** [comment]
The fact that this didn't show up in any of out testing on the emscripten side is surprising, and shows a hole in our testing.

**Comment by dschuff** [comment]
For a workaround, it looks like https://github.com/llvm/llvm-project/commit/003b58f65bdd5d9c7d0c1b355566c9ef430c0e7d was landed on June 28, so I suspect any emscripten from before then should work.

**Comment by aardappel** [comment]
Using `latest` on my CI for now as latest tagged release is indeed from before that change, which fixes it for the moment.
