### ISSUE TITLE
[LINALG] Vectorization pass crashes when extract op have empty indices

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/llvm-project#63688]
Hi, during the `tensor::ExtractOp` vectorization the pass crashes here https://github.com/llvm/llvm-project/blob/07630da36a31596594a1ba3b9f000dc57d5382f3/mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp#L748 when the extractOp has no indices. Probably, we need to insert a check for when the `extractOp.getIndices()` are empty, after this: https://github.com/llvm/llvm-project/blob/07630da36a31596594a1ba3b9f000dc57d5382f3/mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp#L745-L746
 ```
  if (extractOp.getIndices().empty())
    return failure();
```

**Comment by banach-space** [comment]
Hi @vivekkhandelwal1 , thanks for reporting! Do you have a reproducer?

-Andrzej

**Comment by vivekkhandelwal1** [comment]
> Please check https://reviews.llvm.org/D154518 and see whether that fixes the issue for you.

So, using this patch it's not crashing but it throws another error. I'm using openxla/iree for compiling the IR generated from the Torch-MLIR. Now, I get the following error:
```
error: 'memref.alloca' op expected no unbounded stack allocations                                                                                                                               
    %expanded_749 = tensor.expand_shape %4 [[0], [1, 2, 3]] : tensor<1x?xi1> into tensor<1x1x1x?xi1>       
```

**Comment by banach-space** [comment]
I won't be able to help without a reproducer, sorry. And if this requires IREE then I suggest moving this issue to https://github.com/openxla/iree/issues. I strongly suspect though that this can be reproduced with `mlir-opt` ;-)

**Comment by banach-space** [comment]
@vivekkhandelwal1 This got auto-magically closed after I merged my patch. Please re-open if you feel that this issue hasn't been resolved :)

**Comment by vivekkhandelwal1** [comment]
> @vivekkhandelwal1 This got auto-magically closed after I merged my patch. Please re-open if you feel that this issue hasn't been resolved :)

Sure, I will do that.
