### ISSUE TITLE
llvm-mca, if scheduling model of awas graviton processor is available?

### ISSUE THREAD

**Issue by xshen053** [llvm/llvm-project#63694]
Hey, I am using llvm-mca tool, it's a powerful tool, I really love it!

From the doc, it says

`The tool currently works for processors with a backend for which there is a scheduling model available in LLVM.`

So could anyone tell me if scheduling model of aws graviton processor is available?

AWS Graviton processor is based on arm64

**Comment by asl** [comment]
Graviton is based on Neoverse cores that have scheduling models in LLVM
