### ISSUE TITLE
llvm-mca, resource question

### ISSUE THREAD

**Issue by xshen053** [llvm/llvm-project#63698]
Hi, I am using the llvm-mca tool and I ran it on m1 processor and graviton processor where I get different available resource results. Could I ask where can I get information of these resouces? I am analyzing some perfomance bottleneck, so I want to know more info about these resources. But currently I don't know what these resources unit refer to, where could I get information? Thank you!! 
```
Resources:
M1
[0.0] - CyUnitB
[0.1] - CyUnitB
[1]   - CyUnitBR
[2.0] - CyUnitFloatDiv
[2.1] - CyUnitFloatDiv
[3.0] - CyUnitI
[3.1] - CyUnitI
[3.2] - CyUnitI
[3.3] - CyUnitI
[4]   - CyUnitID
[5]   - CyUnitIM
[6.0] - CyUnitIS
[6.1] - CyUnitIS
[7]   - CyUnitIntDiv
[8.0] - CyUnitLS
[8.1] - CyUnitLS
[9.0] - CyUnitV
[9.1] - CyUnitV
[9.2] - CyUnitV
[10]  - CyUnitVC
[11]  - CyUnitVD
[12.0] - CyUnitVM
[12.1] - CyUnitVM
```
```
Graviton 3
Resources:
[0]   - A57UnitB
[1.0] - A57UnitI
[1.1] - A57UnitI
[2]   - A57UnitL
[3]   - A57UnitM
[4]   - A57UnitS
[5]   - A57UnitW
[6]   - A57UnitX
```

**Comment by mshockwave** [comment]
M1 (they're using Apple A7 "Cyclone"'s scheduling model): https://github.com/llvm/llvm-project/blob/9c4aa85ec18833a25141d1563f579ef9099d6eb9/llvm/lib/Target/AArch64/AArch64SchedCyclone.td#L28

Graviton 3 (they're using Cortex-A57's scheduling model): https://github.com/llvm/llvm-project/blob/9c4aa85ec18833a25141d1563f579ef9099d6eb9/llvm/lib/Target/AArch64/AArch64SchedA57.td#L41

**Comment by xshen053** [comment]
Thank you for your reply! I wnat to do some profiling on m1, but if M1 is using A7 Cyclone model, will it cause some inaccuracy?

**Comment by mshockwave** [comment]
> Thank you for your reply! I wnat to do some profiling on m1, but if M1 is using A7 Cyclone model, will it cause some inaccuracy?

Unfortunately, the exact instruction latencies are usually proprietary. So only the hardware vendor knows the impact of using Cyclone's scheduling model for M1.

**Comment by asl** [comment]
I would suggest to move to LLVM Discourse if there are no issues to be reported.
