### ISSUE TITLE
Mutable subobject is usable in a constant expression

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#63695]
This program
```
struct S {
    mutable int i = 2;
};

auto f = []{
    constexpr S s;
    s.i = 3;
    return s.i;
};

static_assert( f() == 3 );
```
is rejected by GCC, following the word of C++20 standard: https://timsong-cpp.github.io/cppwp/n4861/expr.const#4.8

But Clang accepts this program. Online demo: https://gcc.godbolt.org/z/T9vPKrGnv

Could you please verify whether it is correct?

**Comment by efriedma-quic** [comment]
That rule you're citing doesn't apply here.  From the same section, an expression is a core constant expression if it evaluates "a non-volatile glvalue of literal type that refers to a non-volatile object whose lifetime began within the evaluation of E."

I don't see any other rule that would forbid this construct.  MSVC agrees this is well-defined.

**Comment by shafik** [comment]
This looks like a gcc bug to me: https://gcc.godbolt.org/z/9csbhs3dc 

Please file a gcc bug report.
