### ISSUE TITLE
SimplifyCFGPass regression in LLVM 16: generates division by zero despite of check for divisor != 0

### ISSUE THREAD

**Issue by anbe42** [llvm/llvm-project#63696]
The following code compiles fine, but running it fails with a floating point exception when compiled with clang++-16 -O1, while it passes with clang++-15 (x86_64, no -march flag used):
```
__attribute__((noinline))
auto f (float x)
{
    if (x != 0.0f)
    {
        return 1.0f + (1.0f / x);
    }
    else
    {
        return 1.0f;
    }
}

#include <cfenv>

auto main () -> int
{
    feenableexcept(FE_DIVBYZERO);
    const auto a = f(8);
    const auto b = f(0);

    return a + b;
}
```
A successful run should exit with 2

The emitted assembly for function f somehow misses the branch.

Checking with `-opt-bisect-limit` pinpoints the miscompilation to SimplifyCFGPass

Tested with Debian llvm-16 (1:16.0.6-3), also reproducible on godbolt:
https://godbolt.org/z/vqc7498co

**Comment by nikic** [comment]
If you want to use a non-default FP environment, you need to put `#pragma STDC FENV_ACCESS ON` at the top of your program, or specify one of the relevant FP control options documented at https://clang.llvm.org/docs/UsersManual.html#controlling-floating-point-behavior, such as `-ffp-model=strict`.
