### ISSUE TITLE
Assertion `Val == MO.getImm() && "Add/sub immediate out of range!"' with high stack alignment on arm64 windows

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#63701]
Testcase:

```cpp
void g(void*);
void f() { _Alignas(8192) int x[1 << 26]; g(x); }
```

```console
llvm/lib/Target/AArch64/MCTargetDesc/AArch64InstPrinter.cpp:1206: void llvm::AArch64InstPrinter::printAddSubImm(const llvm::MCInst *, unsigned int, const llvm::MCSubtargetInfo &, llvm::raw_ostream &): Assertion `Val == MO.getImm() && "Add/sub immediate out of range!"' failed.
```

Looks like an invalid `ADDXri` instruction.

CC @mstorsjo

**Comment by mstorsjo** [comment]
Hmm, I can't seem to reproduce this? I tried with e.g. this command:
```
$ clang -target aarch64-windows-msvc -c repro.c -O2
```
This tested with a recent build from git main, from 16e61eb0c4d333fd589f94ddf40a37602d3eae93.

**Comment by mstorsjo** [comment]
> Hmm, I can't seem to reproduce this? I tried with e.g. this command:
> 
> ```
> $ clang -target aarch64-windows-msvc -c repro.c -O2
> ```
> 
> This tested with a recent build from git main, from [16e61eb](https://github.com/llvm/llvm-project/commit/16e61eb0c4d333fd589f94ddf40a37602d3eae93).

Nevermind, I tried with `-S` and I can reproduce it (irrespective of whether `-O2` is set or not).

**Comment by mstorsjo** [comment]
Posted an initial fix attempt at https://reviews.llvm.org/D155447.
