### ISSUE TITLE
Unused libcxx CMake option `LIBCXX_DISABLE_MACRO_CONFLICT_WARNINGS`

### ISSUE THREAD

**Issue by Gadal** [llvm/llvm-project#63703]
The CMake options `LIBCXX_DISABLE_MACRO_CONFLICT_WARNINGS` appears to be unused:

https://github.com/llvm/llvm-project/blob/c951960e65961d19cfca9996bf8ab96155805256/libcxx/CMakeLists.txt#L287

**Comment by philnik777** [comment]
`LIBCXX_ENABLE_PEDANTIC` and `_LIBCPP_ENABLE_WERROR` are used. Not sure why you think they aren't.

**Comment by Gadal** [comment]
I overlooked their use further down in the file. I've updated the ticket.

Sorry for the churn, should've be more careful about updating a ticket marked 'confirmed'.
