### ISSUE TITLE
LLVM/clang-cl 16.0.6 emitting "packed single" instructions reading and using potentially uninitialized memory

### ISSUE THREAD

**Issue by MarcKamradt** [llvm/llvm-project#63708]
We are using Visual Studio 2022 and clang-cl with an external installation of LLVM to generate an x64 executable.

After switching from 15.0.7 to any of the 16.0.x version we encounter multiple miscompilations in the release builds of our project.

I have narrowed a case down to a pretty small test project which is attached. It shows that the generated code uses "packed single" instructions instead of the expected "scalar single" instructions. These SIMD instructions read beyond the actual data involved in the calculation, which can be uninitialized or even unallocated memory. In the test project I forced that data to be NaNs so when stepping through the assembly code it can be observed that those NaNs are read into SIMD registers and then used in math operations, which in turn can raise floating point exceptions - which is exactly what is happening in our application.

Here is a snippet of the source:

```
[...]

// method of class SmoothedValue
float nextValue ()
{
    current += ( target - current ) * lerpValue;
    return current;
}

[...]

// using the class
const float dry = m_dry.nextValue ();
const float wet = m_wet.nextValue ();

[...]
```

And here is a snippet of the resulting assembly code:

```
movups      xmm0,xmmword ptr [rcx+4Ch]  // <-- READS DATA BEYOND THE LAST FLOAT OF THE CLASS
movups      xmm1,xmmword ptr [rcx+48h]  
movss       xmm2,dword ptr [rcx+30h]  
movss       xmm3,dword ptr [rcx+34h]  
movss       xmm4,dword ptr [rcx+38h]  
movlhps     xmm4,xmm0  
shufps      xmm4,xmm0,0E2h              // also: why override xmm4 which has just been written to?
movlhps     xmm3,xmm1  
shufps      xmm3,xmm1,0E2h  
subps       xmm4,xmm3  
movups      xmm0,xmmword ptr [rcx+44h]  
movlhps     xmm2,xmm0  
shufps      xmm2,xmm0,0E2h  
mulps       xmm2,xmm4                   // <-- POTENTIALLY USE NANS FOR MATH OPERATIONS
addps       xmm2,xmm3  

```

The Visual Studio 2022 project:

[TestClang16.zip](https://github.com/llvm/llvm-project/files/11965947/TestClang16.zip)

**Comment by efriedma-quic** [comment]
Are you using `/fp:strict` ?

**Comment by reFX-Mike** [comment]
I'm confused. The code being generated is wrong. It reads from adjacent memory, so what does this have to do with floating-point exception registers?

**Comment by efriedma-quic** [comment]
I thought the reason you filed the issue is that you're seeing floating-point exceptions?  If we're reading past the end of a variable, that's a different issue.

**Comment by reFX-Mike** [comment]
The issue is that it reads from adjacent memory, thus reading random garbage from memory. Now any math operation on those values becomes a potential exception. Both things need to be corrected. It also generates an additional instruction that is unneeded.

**Comment by efriedma-quic** [comment]
If you don't pass /fp:strict, it isn't considered a bug if clang generates floating-point exceptions.  Floating-point exceptions can be generated by operations on uninitialized memory in certain circumstances.  For example, with SLP vectorization.

If clang is accessing memory that isn't allocated, that's a bug, but it's not clear that's what's happening from you description.

**Comment by reFX-Mike** [comment]
So the solution then is to disable all floating point exceptions before running code that has been compiled with /fp:fast? Because this is not a stand-alone program, but a .dll loading by another program. We would need to make sure that at all entry points we disable fp-exceptions and then upon return restore the old state (whatever that may have been).

This seems extremely weird to me, especially given that the generated code here is completely unecessary. It provides neither a performance nor correctness benefit to emit the correct, scalar, instructions. Nothing is gained by this "optmization", but less correct code is generated that breaks our code.

**Comment by efriedma-quic** [comment]
> So the solution then is to disable all floating point exceptions before running code that has been compiled with /fp:fast? Because this is not a stand-alone program, but a .dll loading by another program. We would need to make sure that at all entry points we disable fp-exceptions and then upon return restore the old state (whatever that may have been).

Normally, you shouldn't call arbitrary code with FP traps enabled... but if you're dealing with code that does, then yes.

--------------

In terms of code quality, I'm pretty sure the generated code is trying to do SLP vectorization. Not sure how accurate the cost modeling is in this particular case, but in general it's a worthwhile optimization.

**Comment by reFX-Mike** [comment]
This is for audio plugins (VST2, VST3, AU, AAX) for a wide range of hosts. We have zero control over who calls our code. There are various entry points into our code for various purposes (getting the next block of data, setting parameters, retrieving display strings, etc.)

Is there a way to safely disable this optimization when specifically using scalar operations? It doesn't make any sense to us that the compiler would even emit packed instructions when it's impossible to benefit from them. In this specific case, the current value depends on the previous value, and there is only the one, so what benefit can this possibly provide? It can only cause errors/exceptions, but there is no gain to be had. At all.

Are there any flags we can use to prevent this, but still get the wider benefit of optimizations?

**Comment by efriedma-quic** [comment]
You can try disabling vectorization here; maybe `/clang:-fno-slp-vectorize`?  But that doesn't solve the general issue.

There isn't currently any support for a mode that allows FP reassociation, but not triggering FP exceptions.  I can sort of see why you'd want it, but I'm not sure how we'd formally define it, and there isn't currently any support for a mode like that. Historically, there wasn't any support at all for `/fp:strict`, so optimizations around it are relatively immature.
