### ISSUE TITLE
msan broken on non-glibc systems by dladdr1 interceptor

### ISSUE THREAD

**Issue by brooksdavis** [llvm/llvm-project#63719]
The dladdr1 interceptor added in 015dabd7672f936cdb5bdcad20fe80b17f05c9ca is compiled unconditionally, but dladdr1 appears to be glibc specific. As such msan is broken on FreeBSD and presumably other BSDs and musl based Linux systems.

**Comment by thurstond** [comment]
The change was reverted (https://reviews.llvm.org/rG74369923a909daa8a95fc5f5d065e5b5b5d01feb), and then relanded with `#if SANITIZER_GLIBC` guards: https://reviews.llvm.org/D154272?id=539195
