### ISSUE TITLE
[mlir][spirv] Support index to spir-v dialect conversion

### ISSUE THREAD

**Issue by kuhar** [llvm/llvm-project#63713]
Right now MLIR seems to only support index to llvm conversion. We should also support it on the spirv lowering path.

There's already one related user request / bug report on Discourse: https://discourse.llvm.org/t/need-help-in-better-understanding-scf-to-spir-v-lowering/71639:

```mlir
func.func @forward() {
    %c0 = arith.constant 0 : index
    %c32 = arith.constant 32 : index
    %c1 = arith.constant 1 : index
    scf.for %arg2 = %c0 to %c32 step %c1 {
        %1 = index.add %arg2, %arg2
    }
    return
}
```

**Comment by inbelic** [comment]
Hej, I was curious if this could be an appropriate good first issue? Having a helping hand from the `IndexToLLVM` implementation, I think I could be able to tackle it. Of course, only if kuhar or hsnbrg haven't claimed it :)

**Comment by kuhar** [comment]
Hi @inbelic, sure thing! Feel free to reach out if you need some help with getting started or run into some issues. Happy to answer any questions, via github/email or a video call.

**Comment by inbelic** [comment]
Awesome, will do!
