### ISSUE TITLE
[llvm-mca], AArch64SchedNeoverseN1 scheduling model question

### ISSUE THREAD

**Issue by xshen053** [llvm/llvm-project#63718]
https://github.com/llvm/llvm-project/blob/a4a26374aa11d48ac6bf65c78c2aaf8f16414287/llvm/lib/Target/AArch64/AArch64SchedNeoverseN1.td

according to the file here, these are all the resources (10 resources)
```
def N1UnitB  : ProcResource<1>;  // Branch
def N1UnitS  : ProcResource<2>;  // Integer single cycle 0/1
def N1UnitM  : ProcResource<1>;  // Integer multicycle
def N1UnitL  : ProcResource<2>;  // Load/Store 0/1
def N1UnitD  : ProcResource<2>;  // Store data 0/1
def N1UnitV0 : ProcResource<1>;  // FP/ASIMD 0
def N1UnitV1 : ProcResource<1>;  // FP/ASIMD 1
```
but according to the arm offical guide
<img width="909" alt="image" src="https://github.com/llvm/llvm-project/assets/97472036/e12edfc8-c493-4fbe-ba03-4035b1a7ea6a">
there are only 8 resources

**Comment by asl** [comment]
So what's the issue? For the questions consider asking on LLVM Discourse

**Comment by xshen053** [comment]
> So what's the issue? For the questions consider asking on LLVM Discourse

This is an issue. I think AArch64SchedNeoverseN1 scheduling model is wrong

**Comment by asl** [comment]
> This is an issue. I think AArch64SchedNeoverseN1 scheduling model is wrong

Ok. Please reopen with concrete example what is wrong and how. Note that this is a model it should not copy the guide verbatim.
