### ISSUE TITLE
Unknown MLIR error "training is not supported for now"

### ISSUE THREAD

**Issue by clw5710** [llvm/llvm-project#63714]
I am using a tool called [ScaleHLS ](https://github.com/hanchenye/scalehls) which translates PyTorch models to HLS C++ code for later FPGA implementation. I am posting here because it uses MLIR. I've been particularly interested in using this tool for trained models, however each time a trained model is used I get an "operand does not dominate this use" error (occurs for my models and models provided in ScaleHLS samples). Interestingly, untrained models run fine. 

Most likely this is a ScaleHLS bug, however I am looking for some clarity on the following error from the MLIR output:
`%75 = linalg.conv_2d_nchw_fchw {dilations = dense<1> : vector<2xi64>, strides = cf.assert %3, "training is not supported for now"`

This came from trying to run the following pretrained resnet18 model:
```
import sys 
import torch 
import torchvision.models as models 

import os 
import torch_mlir 

resnet18 = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
resnet18.train(False)

module = torch_mlir.compile(resnet18, torch.ones(1,3,32,32), output_type=torch_mlir.OutputType.LINALG_ON_TENSORS)

print(module)
```

Does this mean that the linalg dialect does not currently support trained PyTorch model lowering?

**Comment by joker-eph** [comment]
This is not an MLIR question, and not a linalg question (training vs inference does not make any difference when you get to linalg). This is instead a question for torch-mlir specifically, please ask there: https://github.com/llvm/torch-mlir
