### ISSUE TITLE
[clang-format] No space between the case and the expression if C-style cast is used

### ISSUE THREAD

**Issue by Frenzy-Alex** [llvm/llvm-project#63720]
Hi,

Found this small mistake today: there is a missing space between the 'case' and the expression if C-style cast is used.

```
struct FullId {
    explicit constexpr FullId( uint8_t in_group, uint8_t in_id ) : group( in_group ),  id( in_id ) {}
  
    explicit constexpr operator uint16_t() const { return group << 8 | id; }

    uint8_t group;
    uint8_t id;
};

constexpr FullId FullId_A = FullId( 0, 0 );
constexpr FullId FullId_B = FullId( 0, 1 );

void someFunc( FullId in_fullId ) {
    switch( (uint16_t)in_fullId ) {
        case(uint16_t)FullId_A: break; // <- should be space between case and expression: case (uint16_t)...
        default: break;
    }
}
```

I'm using integrated clang-format in CLion (2023.1.3).
Built-in clangd version: 17.0.0
LLVM revision: 22d98280dd8ee70064899eefb973a1c020605874

I'm attaching clang-format.txt if needed.
[clang-format.txt](https://github.com/llvm/llvm-project/files/11973340/clang-format.txt)

**Comment by owenca** [comment]
This is because `SpaceBeforeParens` is set to `Never` in the attached configuration file.
