### ISSUE TITLE
[BOLT]relocation error

### ISSUE THREAD

**Issue by lifengxiang1025** [llvm/llvm-project#63730]
When I run my binary optimized by bolt, my binary crashed. It crashed in:
`0x000000002180dd59 <+25>:	mov    -0x2180dd60(%rip),%rdx        # 0x0`
This line attempt to give one typeinfo address to rdx. The rdx is 3rd parameter of dynamic_cast. In origin binary, this line's src address point to .got and can transfer right address to rdx through .got. I don't know why bolt change the relocation address to 0. Is there some suggestion to help me debug? 
I compile my binary by clang1101. Bolt is created in llvm16.

**Comment by aaupov** [comment]
How did you produce the input binary? Did you add `-Wl,--emit-relocs`?
Please add BOLT command line and log.

**Comment by lifengxiang1025** [comment]
@aaupov 

> How did you produce the input binary? Did you add -Wl,--emit-relocs?
Yes, I can find .rela.text section.

> Please add BOLT command line and log.
I follow BOLT's README and BOLT command is `-data=perf.fdata -reorder-blocks=ext-tsp -reorder-functions=hfsort -split-functions -split-all-cold -split-eh -dyno-stats -update-debug-sections`

BOLT log:
`BOLT-INFO: Target architecture: x86_64
BOLT-INFO: BOLT version: fce3e75e01babe38576b1519dab5f752955525f9
BOLT-INFO: first alloc address is 0x200000
BOLT-INFO: creating new program header table at address 0x21000000, offset 0x20e00000
BOLT-INFO: enabling relocation mode
BOLT-INFO: enabling lite mode
BOLT-WARNING: Failed to analyze 29249 relocations
BOLT-INFO: pre-processing profile using branch profile reader
BOLT-INFO: forcing -jump-tables=move as PIC jump table was detected in function _ZN11army_knife27Context8add_dataIJRA14_KcRSt10shared_ptrISt6vectorIbSaIbEEEEEEvDpOT_
BOLT-INFO: 13105 out of 474619 functions in the binary (2.8%) have non-empty execution profile
BOLT-INFO: 66 functions with profile could not be optimized
BOLT-INFO: profile for 1 objects was ignored
BOLT-INFO: the input contains 17783 (dynamic count : 43803) opportunities for macro-fusion optimization. Will fix instances on a hot path.
BOLT-INFO: 926725 instructions were shortened
BOLT-INFO: removed 28500 empty blocks
BOLT-INFO: merged 456 duplicate CFG edges
BOLT-INFO: removed 3 'repz' prefixes with estimated execution count of 1 times.
BOLT-INFO: basic block reordering modified layout of 10599 functions (80.88% of profiled, 2.23% of total)
BOLT-INFO: UCE removed 0 blocks and 0 bytes of code.
BOLT-INFO: splitting separates 5873624 hot bytes from 41059550 cold bytes (12.51% of split functions is hot).
BOLT-INFO: 1146 Functions were reordered by LoopInversionPass
BOLT-INFO: program-wide dynostats after all optimizations before SCTC and FOP:

             4270375 : executed forward branches
              927028 : taken forward branches
              907599 : executed backward branches
              497632 : taken backward branches
              441769 : executed unconditional branches
             1368763 : all function calls
              328885 : indirect calls
              263705 : PLT calls
            43421490 : executed instructions
            11039054 : executed load instructions
             8110837 : executed store instructions
               20673 : taken jump table branches
                   0 : taken unknown indirect branches
             5619743 : total branches
             1866429 : taken branches
             3753314 : non-taken conditional branches
             1424660 : taken conditional branches
             5177974 : all conditional branches

             4245892 : executed forward branches (-0.6%)
              202064 : taken forward branches (-78.2%)
              932040 : executed backward branches (+2.7%)
              456808 : taken backward branches (-8.2%)
              203620 : executed unconditional branches (-53.9%)
             1368763 : all function calls (=)
              328885 : indirect calls (=)
              263705 : PLT calls (=)
            43051384 : executed instructions (-0.9%)
            11039054 : executed load instructions (=)
             8110837 : executed store instructions (=)
               20673 : taken jump table branches (=)
                   0 : taken unknown indirect branches (=)
             5381552 : total branches (-4.2%)
              862492 : taken branches (-53.8%)
             4519060 : non-taken conditional branches (+20.4%)
              658872 : taken conditional branches (-53.8%)
             5177932 : all conditional branches (-0.0%)

BOLT-INFO: SCTC: patched 42 tail calls (42 forward) tail calls (0 backward) from a total of 42 while removing 0 double jumps and removing 36 basic blocks totalling 180 bytes of code. CTCs total execution count is 624850 and the number of times CTCs are taken is 5599.
BOLT-INFO: setting _end to 0x266e4d18
BOLT-INFO: setting _end to 0x266e4d18
BOLT-INFO: setting __hot_start to 0x21200000
BOLT-INFO: setting __hot_end to 0x2188345f
BOLT-INFO: patched build-id (flipped last bit)
`

**Comment by lifengxiang1025** [comment]
My bin can run when I use llvm14'BOLT. I found llvm14'BOLT doesn't support "-split-functions". So I remove "-split-functions" and I found my bin also can run in llvm16'BOLT.
By the way, I print BOLT's debug log and I found in llvm14's BOLT it emits "BOLT-DEBUG: not creating PC-relative relocation at xxx for xx" about the typeinfo symbol where coredump. Llvm16'BOLT doesn't emit.

**Comment by lifengxiang1025** [comment]
It's ok after redoing BOLT's procedure. Maybe I do some wrong things when I first use BOLT.
