### ISSUE TITLE
Improve cppcoreguidelines-avoid-const-or-ref-data-members for uncopyable/immovable types

### ISSUE THREAD

**Issue by Ashimaru** [llvm/llvm-project#63733]
Currently types like:

class A
{
A(const A&) = delete;
A& operator=(const A&) = delete;
A(A&&) = delete;
A& operator=(A&&) = delete;

int& i;
const std::string str;
};

Will be marked in clang-tidy as problematic by this check.
[C.12](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-constref) explicitly states that this rule applies only to types that are copyable/movable.

**Comment by carlosgalvezp** [comment]
https://reviews.llvm.org/D155625
