### ISSUE TITLE
Program is miscompile with '-O1' option

### ISSUE THREAD

**Issue by Yvan-xy** [llvm/llvm-project#63739]
My clang version is:
```
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

And I compiled the following program with `clang -O1 -o a a.cpp`:

```c++
#include <mutex>
#include <string>
#include <thread>
#include <iostream>

std::mutex l;

void f(std::size_t id) {
  while (true) {
    {
      std::lock_guard<std::mutex> guard(l);
      std::cout << "thread " << id << " acquired\n";
    }
  }
}


int main() {
  for (std::size_t i = 0; i < 256; i++) {
    std::thread t(f, i);
    t.detach();
  }

  while(1);
}
```

The program would keep running the `for` loop rather than stop when `i == 256`.
![Screen Shot 2023-07-07 at 15 28 57](https://github.com/llvm/llvm-project/assets/25425110/0c784e6d-cf4d-4d22-8e82-5b0272a69ede)

I suppose that, without special treatment for `while(1)`, the exit on the control flow graph (CFG) will not post-dominant the preceding nodes. As a result, passes that rely on post-dominators for optimization will not work correctly.

**Comment by Yvan-xy** [comment]
I wish to pick up this issue if it is confirmed. Thanks. :)

**Comment by nikic** [comment]
`while(1);` is undefined behavior in C++, use `-fno-finite-loops`.
