### ISSUE TITLE
The practical use of clangd for C/C++ projects can be extremely difficult.

### ISSUE THREAD

**Issue by bruce-the-terrible** [llvm/llvm-project#63754]
When developing C/C++ projects, users usually start by loading uncompilable and poorly organized code. Users want to read and modify this code on vim or neovim, working with clangd. But clangd does not support jumping between files without compile_command.json, so there is nothing the user can do.
So, clangd needs a tool to create a file like compile_command.json to make vim or neovim jump between files.
Previously ctags and cscope were able to provide this capability by creating a database. However, the jumping functionality was poorly implemented.

**Comment by HighCommander4** [comment]
Do you have a suggestion for how to improve this situation?

**Comment by bruce-the-terrible** [comment]
I have write a script  below
sounds like a bad idea ,but it works

base on xmake



```
#!/bin/zsh
#for mac .
#usage ./gen_compile_commands.sh projectname
filename="xmake.lua"
rm -rf $filename
rm -rf compile_command.json
touch $filename
touch .git
echo "set_project(\"$1\")" >> $filename
echo "set_xmakever(\"2.7.9\")" >> $filename
echo "set_version(\"1.0.0\")" >> $filename
echo "  target(\"$1\")" >> $filename
echo "      set_kind(\"binary\")" >> $filename
echo "      set_targetdir(\"./build\")" >> $filename
echo "      add_files(\"./**.c\")" >> $filename
echo "      add_files(\"./**.s\")" >> $filename
#echo "      add_files(\"./**.cpp\")" >> $filename
#echo "      add_files(\"./**.cxx\")" >> $filename
find . -name "*.h" -o -name "*.hpp" -o -name "*.hxx" |\
    xargs -o dirname |sort|uniq|\
    while read dir_name ;do 
        echo "      add_includedirs(\"$dir_name\")";
    done >> $filename
xmake project -k compile_commands
```

> Do you have a suggestion for how to improve this situation?

**Comment by HighCommander4** [comment]
Thanks. If I understand correctly, your script combines the following two features:

 1. Determine the list of files to index (the list of files for which to add entries to `compile_commands.json`) by recursively enumerating the files in the workspace directory, and choosing each file that looks like a C++ source file based on its extension. We have https://github.com/clangd/clangd/issues/340 on file for this (see also related discussion thread https://github.com/clangd/clangd/discussions/955).
 2. Determine the compile flags to use for the files (specifically `-I` flags) heuristically by searching the workspace directory for subdirectories that contain header files, which then become include paths. This and related heuristics have been suggested in https://github.com/clangd/clangd/issues/304, https://github.com/clangd/clangd/issues/349, and https://github.com/clangd/clangd/issues/458.

I'm going to close this as I believe the suggestion here is covered by the existing issues linked above.
