### ISSUE TITLE
`<ratio>`: The `std::ratio` meta arithmetic can accept non-`std::ratio`

### ISSUE THREAD

**Issue by hewillk** [llvm/llvm-project#63753]
[[ratio.general]](https://eel.is/c++draft/ratio.general): "If a template parameter is named R1 or R2, and the template argument is not a specialization of the ratio template, the program is ill-formed."

Only MSVC-STL triggers the static assertion for the following test:

```cpp
#include <ratio>

struct Ratio { constexpr static double num = 0, den = 1; };
static_assert(std::ratio_equal<Ratio, std::ratio<0, 5>>());

```
https://godbolt.org/z/MhazY5ecn

**Comment by Shanchax** [comment]
Is anyone working on this issue ? I'd like to try my hands on it ( I am beginner in the LLVM community , any help and guidance would be apreciated)

**Comment by mordante** [comment]
Since the issue is new, I don't expect anybody to have started on it. Best join us in the #libcxx channel on LLVM Discord. We have [documentation](https://libcxx.llvm.org/) and [Contribution information](https://libcxx.llvm.org/Contributing.html).

**Comment by mordante** [comment]
@Shanchax are you still working on this issue?
