### ISSUE TITLE
Wrong code at -O3 on x86_64-linux_gnu (latent issue in DSEPass since clang-9)

### ISSUE THREAD

**Issue by shao-hua-li** [llvm/llvm-project#63764]
This looks like a long latent issue since clang-9. Clang at -O3 produces wrong code on the following code. `opt-bisect-limit` suggests that the issue might be in `DSEPass`. 

Compiler explorer: https://godbolt.org/z/YqG6YMefq

```console
% cat a.c
int printf(const char *, ...);
long a;
char b;
int c, e;
int *d = &c;
static int f;
int main() {
  {
    int g = e = f = 1;
    for (; f >= 0; f--) {
      char h[4];
      for (; g < 4; g++)
        h[e - 1 + g] = 5;
      a = 0;
      for (; a <= 0; a++) {
        char *i = &b;
        for (; g < 7; g++)
          ;
        *i = *d = h[3];
      }
    }
  }
  printf("%d\n", b);
}
%
% clang-tk -O0 a.c && ./a.out
5
% clang-tk -O3 a.c && ./a.out
0
%
% clang-tk -v
clang version 17.0.0 (https://github.com/llvm/llvm-project.git 99074aafc31593c9935da483edab1333d6ce5a5b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /zdata/shaoli/compilers/ccbuilder-compilers
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
%
```

**Comment by nikic** [comment]
Produces use of uninitialized value under msan: https://godbolt.org/z/Yvbz1croe

**Comment by shao-hua-li** [comment]
I think this is a MSan bug since there is no use-of-uninitialized-value in this program. If you use clang-15, 14, and 13 with `-fsanitize=memory`, the program would exit normally. https://godbolt.org/z/3bnnj8fMP

CompCert also says that this is a valid program https://godbolt.org/z/3bnnj8fMP

**Comment by nikic** [comment]
The `f` loop makes two iteration. On the second iteration, `g` is already 7, so the first g loop is not entered and nothing is written to `h`. Then the a loop will read `h[3]`, which is an uninitialized value. Am I missing something here?

**Comment by shao-hua-li** [comment]
You're right. `h[3]` is indeed uninitialized. I'll try to report this issue to CompCert. Thanks for the diagnosis!

**Comment by shao-hua-li** [comment]
You're right. `h[3]` is indeed uninitialized. I'll try to report this issue to CompCert. Thanks for the diagnosis!
