### ISSUE TITLE
Unable to replicate clang optimization pipeline using opt with LLVM 16

### ISSUE THREAD

**Issue by lucasreis1** [llvm/llvm-project#63788]
I've been experimenting with optimization via Clang as I'm in need of a custom optimization pipeline for IR. I figured that I would start by replicating `clang -O3` using opt and remove passes I don't need. 

A few quick tests showed me that for a specific application, Clang produced a binary that is 10% faster than when using opt. I've tried mimicking everything Clang does up until codegen except for optimizations, which I apply at opt. The result is still the same.

Here's a summary of my pipeline:

```
clang -c -emit-llvm -O3 a.cpp
clang -c -emit-llvm -O3 b.cpp
clang -c -emit-llvm -O3 c.cpp
llvm-link a.bc b.bc c.bc -o from_clang.bc
```

```
clang -Xclang -mframe-pointer=all -Xclang -vectorize-loops -Xclang vectorize-slp  -Xclang -disableO0-optnone -c -emit-llvm a.bc
opt a.bc -passes="default<O3>" -o a.bc
clang -Xclang -mframe-pointer=all -Xclang -vectorize-loops -Xclang vectorize-slp  -Xclang -disableO0-optnone -c -emit-llvm b.cpp
opt b.bc -passes="default<O3>" -o b.bc
clang -Xclang -mframe-pointer=all -Xclang -vectorize-loops -Xclang vectorize-slp  -Xclang -disableO0-optnone -c -emit-llvm c.cpp
opt c.bc -passes="default<O3>" -o c.bc

llvm-link a.bc b.bc c.bc -o from_opt.bc
```

When generating binaries, `from_clang.bc` was 10% faster than `from_opt.bc`.

To my understanding, [Clang's optimization pipeline](https://github.com/llvm/llvm-project/blob/release/16.x/clang/lib/CodeGen/BackendUtil.cpp#L992C1-L992C1) is [identical to opt's](https://github.com/llvm/llvm-project/blob/release/16.x/llvm/lib/Passes/PassBuilder.cpp#L1207) when running the new pass manager.

So, is there anything I'm missing here? How come the results are so different between these two binaries with alleged identical optimization pipelines?

**Comment by topperc** [comment]
-disableO0-optnone is not sufficient to make an optimizable IR file from clang. TBAA metadata is also not emitted with -O0. Not sure if there is anything else.

A better recipe might be `-O3 -disable-llvm-passes`

**Comment by lucasreis1** [comment]
A week of source code reading and I had no idea the driver was able to receive this option. Thank you, worked like a charm!
