### ISSUE TITLE
[Clang] concept template parameters not resolving properly for out-of-line definitions

### ISSUE THREAD

**Issue by glaba** [llvm/llvm-project#63785]
```
template <typename T, typename U>
concept Concept = true;

template <typename T>
struct Class {
    template <Concept<Class> U>
    void do_thing(U&);
};

template <typename T>
template <Concept<Class<T>> U>
void Class<T>::do_thing(U&) {}
```
fails with the error
```
<source>:20:16: error: out-of-line definition of 'do_thing' does not match any declaration in 'Class<T>'
void Class<T>::do_thing(U&) {}
               ^~~~~~~~
1 error generated.
ASM generation compiler returned: 1
<source>:20:16: error: out-of-line definition of 'do_thing' does not match any declaration in 'Class<T>'
void Class<T>::do_thing(U&) {}
               ^~~~~~~~
```
This succeeds in GCC 13, and I expect it to be valid. Specifying `Class<T>` (although unnecessary as far as I know) in the original declaration also does not work.

**Comment by shafik** [comment]
MSVC also rejects this: https://godbolt.org/z/TnWsovEEn

I believe this falls afoul of [temp.over.link p7](https://timsong-cpp.github.io/cppwp/temp.over.link#7):

>If the validity or meaning of the program depends on whether two constructs are equivalent, and they are functionally equivalent but not equivalent, the program is ill-formed, no diagnostic required. ...

So everyone is correct here. 

Using `Class<T>` in the declaration and all accept it: https://godbolt.org/z/vTK93vMnj

**Comment by glaba** [comment]
My apologies, `Class<T>` didn't work in Clang 16.0.0 but does work in trunk, closing.
