### ISSUE TITLE
Devops Blazor LLVM ERROR: out of memory allocation failed

### ISSUE THREAD

**Issue by ketelsb** [llvm/llvm-project#63781]
Error when buidling blazor app using AOT Compilation on a devops pipeline

stack trace

C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CB66E4B0 (0x000001E7A6430000 0x00007FFB24BB1DDA 0x0000000000000000 0x0000683F2381A031) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CC6464C1 (0x0000000000000201 0x00007FF7CB66E523 0x0000000000000100 0x0000000000000000) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CC6466AA (0x000001E78BDF0F18 0x000001E7A310F1B8 0x000001E8088AD640 0x0000000000000002) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CC64498B (0x000001E800000000 0x0000000000000000 0x0000000000000000 0x00007FFB24BBB57D) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CB94C3F5 (0x000001E700000000 0x000001E7A63044A0 0x0000000000000000 0x000001E7A6300000) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CB91987D (0x000001E7B01768F0 0x00007FF700000000 0x00007FF7CED83BF9 0x0000000000000011) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CB3063E7 (0x0000683F2381BBE1 0x000001E7A64D5260 0x000001E7EB6591D0 0x0000000000000009) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CB30DFF3 (0x00000000CE624100 0x00007FF7CB95030D 0x00007FF7CED6D885 0x000001E700000000) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CB306B5E (0x0000008737F8BD08 0x0000008700000000 0x000001E7A647B380 0x00007FFB24BBA8C1) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CC2B37EA (0x000001E7A647D2A0 0x0000000000000000 0x000001E7A64302E8 0x00007FFB24BB4DC9) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CC5B67FE (0x000001E7A64CAB00 0x00007FFB24BBA8C1 0x000001E7A64872A0 0x0000683F2381C7D1) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CC4FBD3B (0x2D7069720000001E 0x00007FF700000000 0x000000000000000A 0x0000683F2381C561) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CB7FFFED (0x0000000000000000 0x0000000000000000 0x0000008737F8D0A8 0x00007FF7CEF42FD0) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CB8A1B9B (0x0000000000000000 0x0000000000000000 0x000001E7A64C38B0 0x00007FF7CE5F2F9C) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CB1082FC (0x000001E7A6300000 0x0000000000000000 0x0000000000000010 0x0000000000000000) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CB1050DC (0x00007FFB24D14090 0x00007FFB2252EC34 0x0000000000000004 0x0000008737F8DA28) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CC2C7186 (0x000001E7A64BFD60 0x0000008737F8DA28 0x0000008737F8DA28 0x000001E7A6486F00) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CB66987D (0x0000000000008002 0x0000000000000034 0x0000008737F8DA88 0x00007FF7CEF43430) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CC2C6FB5 (0x0000000000000000 0x000001E700000000 0x000001E7A64855E4 0x00007FF7CE6032CC) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CB7B5EC3 (0x000001E7A6300000 0x000001E700000000 0x0000000000000050 0x00007FF700000000) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CB7B65B5 (0x000001E7A6486B70 0x7FFFFFFFFFFFFFFF 0x0000000000000011 0x0000000000000001) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CB7D5C73 (0x00000000000000E0 0x0000000000000000 0x00000000000000E0 0x000001E7A648B4C0) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CB1048BA (0x0000000000000000 0x00007FF7CE5DCA11 0x0000000000000000 0x0000000000000000) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FF7CE5DC998 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FFB235A4DE0 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x10 bytes(s) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : 0x00007FFB24C1E44B (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : clang++: error: clang frontend command failed due to signal (use -v to see invocation) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : clang version 15.0.0 (https://github.com/llvm/llvm-project d58cc0839ee5935e649dbbc18c898a8e4bcd6724) [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : Target: wasm32-unknown-emscripten [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : Thread model: posix [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : InstalledDir: C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.12.Sdk.win-x64\7.0.8\tools\bin [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : clang++: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs. [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.8\Sdk\WasmApp.Native.targets(348,5): error : emcc: error: 'C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.12.Sdk.win-x64\7.0.8\tools\bin\clang++.exe -target wasm32-unknown-emscripten -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=12 -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.12.Cache.win-x64\7.0.8\tools\emscripten\cache\sysroot -Xclang -iwithsysroot/include\compat -O2 -v -c D:\a\1\s\BandManager.Ui.BlazorApp\obj\Release\net7.0\wasm\for-publish\Plotly.Blazor.dll.bc -o C:\Users\VssAdministrator\AppData\Local\Temp\tmp8F05.tmp' failed (returned 1) [took 155.33s] [D:\a\1\s\BandManager.Ui.BlazorApp\BandManager.Ui.BlazorApp.csproj]
  [83/155] BandManager.Ui.BlazorApp.dll.bc -> BandManager.Ui.BlazorApp.dll.o [took 118.98s]
##[error]Error: The process 'C:\hostedtoolcache\windows\dotnet\dotnet.exe' failed with exit code 1

**Comment by asl** [comment]
Consider reporting issues with Microsoft-provided tools to vendor issue tracker with steps to reproduce
