### ISSUE TITLE
Can't build crtbegin.c on s390x & arm64 for wasm32

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#63799]
Recent regression on s390x & arm64:

```
cd /build/source/build-wasm/compiler-rt-wasm32 && /build/source/build-llvm/tools/clang/stage2-bins/bin/clang -O2 -DNDEBUG -g1 -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 --target=wasm32-unknown-unknown -fno-lto -std=c11 -DEH_USE_FRAME_REGISTRY -fPIC -Wno-pedantic --target=wasm32-unknown-unknown -o /build/source/build-wasm/compiler-rt-wasm32/lib/wasi/clang_rt.crtbegin-wasm32.o -c /build/source/compiler-rt/lib/builtins/crtbegin.c
/build/source/compiler-rt/lib/builtins/crtbegin.c:77:2: error: "crtbegin without .init_fini array unimplemented for this architecture"
   77 | #error "crtbegin without .init_fini array unimplemented for this architecture"
      |  ^
/build/source/compiler-rt/lib/builtins/crtbegin.c:134:2: error: "crtbegin without .init_fini array unimplemented for this architecture"
  134 | #error "crtbegin without .init_fini array unimplemented for this architecture"
      |  ^
2 errors generated.
```

Log:
https://llvm-jenkins.debian.net/job/llvm-toolchain-bionic-binaries/architecture=s390x,distribution=bionic,label=s390x/1153/console

Seems to be caused by:
https://reviews.llvm.org/D153989

@petrhosek rings a bell?

**Comment by petrhosek** [comment]
Thanks for the heads up, I have reverted the change while I'm investigating this.

**Comment by petrhosek** [comment]
It looks like https://llvm-jenkins.debian.net/job/llvm-toolchain-bionic-binaries/architecture=s390x,distribution=bionic,label=s390x/ doesn't set `CMAKE_SYSTEM_NAME` when building for wasm32, so the `CMAKE_SYSTEM_NAME` will be inferred as `Linux` causing this branch to be taken: https://github.com/llvm/llvm-project/blob/dae9d1b52469daca88a968e7b99a26420aef657c/compiler-rt/cmake/builtin-config-ix.cmake#L228
Would it be possible to set `CMAKE_SYSTEM_NAME` to either `WASI` or `Generic` when targeting wasm32?

The title also mentions s390x and arm64 but I don't see those in the log you linked. Do you have a link to the build failures for those architectures? I expect it's going to be the same issue but I want to double check.

**Comment by petrhosek** [comment]
I only see the `wasm32-unknown-unknown` target failing in that log, do you have another example?

**Comment by sylvestre** [comment]
sorry, s390 and arm64 are the host machines. The target is wasm32

Configuration is here:
https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/commits/snapshot/debian/rules

**Comment by petrhosek** [comment]
Thanks, I think we need to set `-DCMAKE_SYSTEM_NAME=Generic` at https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/blob/snapshot/debian/rules#L798-L821. Is that a change you can make or do you want me to send a merge request?

**Comment by sylvestre** [comment]
don't bother, thanks :)
I will try

**Comment by petrhosek** [comment]
This appears to be resolved.
