### ISSUE TITLE
deque is missing safe libc++ hardening checks

### ISSUE THREAD

**Issue by danakj** [llvm/llvm-project#63809]
https://libcxx.llvm.org/UsingLibcxx.html#enabling-the-safe-libc-mode

vector's `operator[]` uses `_LIBCPP_ASSERT_UNCATEGORIZED`: https://github.com/llvm/llvm-project/blob/7b64d761098fdbb426b27ca58a9dc8f31917dcba/libcxx/include/vector#L1534C5-L1534C33

deque's `operator[]` just reads OOB without an assert: https://github.com/llvm/llvm-project/blob/7b64d761098fdbb426b27ca58a9dc8f31917dcba/libcxx/include/deque#L1645-L1661

Same for [`deque::front()`](https://github.com/llvm/llvm-project/blob/7b64d761098fdbb426b27ca58a9dc8f31917dcba/libcxx/include/deque#L1699) and other methods that return a reference.

**Comment by philnik777** [comment]
This is a duplicate of #20888.

**Comment by danakj** [comment]
Hm is it? That bug is about debug mode, which AIUI is separate from the hardening asserts?

**Comment by philnik777** [comment]
Oh sorry. I thought you were referencing a debug assert.

**Comment by mmdriley** [comment]
Thanks for reopening! Can you also please remove the `duplicate` label?

**Comment by davidben** [comment]
Uploaded https://github.com/llvm/llvm-project/pull/79397 which should fix this.
