### ISSUE TITLE
destructors not always properly run when a coroutine is suspended and then destroyed

### ISSUE THREAD

**Issue by zygoloid** [llvm/llvm-project#63818]
[Example](https://godbolt.org/z/zezvTqY8v):

```c++
#include <coroutine>
#include <iostream>

struct coroutine {
  struct promise_type;
  std::coroutine_handle<promise_type> handle;
  ~coroutine() { handle.destroy(); }
};

struct coroutine::promise_type {
  coroutine get_return_object() {
    return {std::coroutine_handle<promise_type>::from_promise(*this)};
  }
  std::suspend_never initial_suspend() noexcept { return {}; }
  std::suspend_never final_suspend() noexcept { return {}; }
  void return_void() {}
  void unhandled_exception() {}
};

struct Printy {
  Printy(const char *name) : name(name) { std::cout << "Printy(" << name << ")\n"; }
  Printy(const Printy&) = delete;
  ~Printy() { std::cout << "~Printy(" << name << ")\n"; }
  const char *name;
};

int main() {
  [] -> coroutine {
    Printy a("a");
    Printy arr[] = {
      Printy("b"), Printy("c"),
      (co_await std::suspend_always{}, Printy("d")),
      Printy("e")
    };
  }();
}
```

When the coroutine is destroyed after being suspended, `a` is destroyed, but `arr[0]` and `arr[1]` are not. Clang does not in general properly create cleanups for non-exceptional control flow that occurs in the middle of an expression / an initializer. At least array initialization is missing cleanups here, but it'd be worth checking through all exception-only cleanups because most of them are probably incorrect. It looks like there are 15 places where we currently push an EH-only cleanup:

```
CGCall.cpp:      pushFullExprCleanup<DestroyUnpassedArg>(EHCleanup, Slot.getAddress(),
CGClass.cpp:    CGF.EHStack.pushCleanup<CallBaseDtor>(EHCleanup, BaseClassDecl,
CGClass.cpp:    EHStack.pushCleanup<CallDelegatingCtorDtor>(EHCleanup,
CGCoroutine.cpp:    EHStack.pushCleanup<CallCoroEnd>(EHCleanup);
CGDecl.cpp:  pushDestroy(EHCleanup, addr, type, getDestroyer(dtorKind), true);
CGDecl.cpp:  pushFullExprCleanup<IrregularPartialArrayDestroy>(EHCleanup,
CGDecl.cpp:  pushFullExprCleanup<RegularPartialArrayDestroy>(EHCleanup,
CGException.cpp:  pushFullExprCleanup<FreeException>(EHCleanup, addr.getPointer());
CGExprAgg.cpp:        CGF.pushDestroy(EHCleanup, LV.getAddress(CGF), CurField->getType(),
CGExprAgg.cpp:        CGF.pushDestroy(EHCleanup, LV.getAddress(CGF), field->getType(),
CGExprCXX.cpp:      .pushCleanupWithExtra<DirectCleanup>(EHCleanup,
CGExprCXX.cpp:    .pushCleanupWithExtra<ConditionalCleanup>(EHCleanup,
ItaniumCXXABI.cpp:    CGF.EHStack.pushCleanup<CallGuardAbort>(EHCleanup, guard);
MicrosoftCXXABI.cpp:    CGF.EHStack.pushCleanup<ResetGuardBit>(EHCleanup, GuardAddr, GuardNum);
MicrosoftCXXABI.cpp:    CGF.EHStack.pushCleanup<CallInitThreadAbort>(EHCleanup, GuardAddr);
```

This bug is not new with coroutines; the same thing happens with statement expressions:

```c++
int main() {
  Printy arr[] = { Printy("a"), ({ return 0; Printy("b"); }) };
}
```

... never destroys `arr[0]`. But it seems more pressing now that it's reachable from standard C++20 code.

**Comment by yuxuanchen1997** [comment]
For those who are reading this, this issue has nothing to do with the less common comma operator syntax shown in the example. If you have a `PrintyAwaiter` here in the much more common scenario you exhibit the same bug: `~Printy("b")` is not run. 
```
task test() {
  Printy a("a");
  Printies p{
    Printy("b"),
    co_await PrintyAwaiter("c"),
    Printy("d"),
  };
  co_return;
}
```

Also, yes, aggregate initialize is also list initialize. Confirmed to have the same bug.

**Comment by yuxuanchen1997** [comment]
`CodeGenFunction::EmitBranchThroughCleanup` ignores cleanups that are not `Normal`. Simply changing the `pushDestroy` to push a `NormalAndEHCleanup` here doesn't seem to work. It calls more destructors than it should.

**Comment by usx95** [comment]
Interestingly, this is not the case with temporaries associated with function calls
```cpp
coroutine foo() {
    Printy a("a");
    // bar(Printy("b"), co_await Awaiter{}); // Fine.

    // (Printy("b"), co_await Awaiter{}); // Fine.

    Printies p{
        Printy("b"), // Leak.
        co_await Awaiter{},
    };
    co_return;
}
```
https://godbolt.org/z/sz6dP8GGP

**Comment by alanzhao1** [comment]
I took a quick stab at this. The following diff resolves the example in the description that doesn't have a coroutine:

```
diff --git a/clang/lib/CodeGen/CGDecl.cpp b/clang/lib/CodeGen/CGDecl.cpp
index a5da0aa2965a..7c961ef91e6d 100644
--- a/clang/lib/CodeGen/CGDecl.cpp
+++ b/clang/lib/CodeGen/CGDecl.cpp
@@ -2423,7 +2423,7 @@ void CodeGenFunction::pushIrregularPartialArrayCleanup(llvm::Value *arrayBegin,
                                                        QualType elementType,
                                                        CharUnits elementAlign,
                                                        Destroyer *destroyer) {
-  pushFullExprCleanup<IrregularPartialArrayDestroy>(EHCleanup,
+  pushFullExprCleanup<IrregularPartialArrayDestroy>(NormalAndEHCleanup,
                                                     arrayBegin, arrayEndPointer,
                                                     elementType, elementAlign,
                                                     destroyer);
```

Output:
```
Printy(a)
~Printy(a)
```

But that diff causes the example with the coroutine to segfault:

```
Printy(a)
Printy(b)
Printy(c)
[1]    1813892 segmentation fault  /tmp/coroutine-dtor-maybefixed
```

**Comment by usx95** [comment]
Yeah I noticed. In the following example, GCC only creates `b` and `c` only after the final resumption in the array expr and not in the lexical order.
```cpp
    Printies p2{Printy("b"),  // Leak.
                co_await Awaiter{"a1"}, Printy("c"), co_await Awaiter{"a2"}};
```
Clang:
```
Printy(b)
Coroutine suspended
Coroutine resumed:
Printy(a1)
Printy(c)
Coroutine suspended
Coroutine resumed:
Printy(a2)
~Printy(a2)
~Printy(c)
~Printy(a1)
~Printy(b)
Coroutine destroyed
```

GCC:
```
Coroutine suspended
Coroutine resumed:
Coroutine suspended
Coroutine resumed:
Printy(b)
Printy(a1)
Printy(c)
Printy(a2)
~Printy(a2)
~Printy(c)
~Printy(a1)
~Printy(b)
Coroutine destroyed
```

**Comment by usx95** [comment]
I think now I understand the root cause and why simply changing the cleanup type would not solve the issue.
This is because of the lifetime extension of temporaries in list-init, braced-init, and backing arrays.

```cpp
struct Printies { const Printy &a; };

int main() {
    Printies p1(Printy("a")); // dangling.
    std::cout << "p1 ctor completed\n";
    Printies p2{Printy("b")}; // lifetime extended to p2.
    std::cout << "p2 ctor completed\n";
    Printy arr[] = {Printy("c"), Printy("d")}; // lifetimes extended to arr.
    std::cout << "arr[] ctor completed\n";
    return 0;
}
```
produces (clang is correct here)
```
Printy(a)
~Printy(a)
p1 ctor completed
Printy(b)
p2 ctor completed
Printy(c)
Printy(d)
arr[] ctor completed
~Printy(d) <-------- Lifetime extended
~Printy(c) <-------- Lifetime extended
~Printy(b) <-------- Lifetime extended
```

In the above example, the lifetime of temporary `Printy("b")` is extended to `p2`, i.e., it is destroyed when `p2` is destroyed. If we have control flow in such expressions (through coroutine suspensions or statement expressions), we would miss to cleanup the temporary because we would not want to destroy `p2` since it is not yet constructed.

**Comment by ChuanqiXu9** [comment]
Thanks to the analysis of @usx95 

There is another example not relevant with arrays: https://godbolt.org/z/4rnTj53qf. The key point here is that the construction is interrupted  but not by exceptions.

**Comment by usx95** [comment]
I do not understand the non-array example. It does not have temporaries whose missed dtor.
Moreover this is not the case with parenthesised-init and only braced-init (because of the lifetime ext) https://godbolt.org/z/GEo3fd89T.

We do not have this problem with such control-flow with exceptions (https://godbolt.org/z/T9scoehev).
We should target performing the same cleanups atleast in coroutine::`destroy` (if not something generic to solve return in stmt expr as well).

**Comment by ChuanqiXu9** [comment]
> I do not understand the non-array example. It does not have temporaries whose missed dtor. Moreover this is not the case with parenthesised-init and only braced-init (because of the lifetime ext) https://godbolt.org/z/GEo3fd89T.

Oh, yeah, you're correct. Sorry for misleading : (

**Comment by usx95** [comment]
Sent out partial resolution : https://github.com/llvm/llvm-project/pull/80698

List initialisation still has missing cleanups.

**Comment by usx95** [comment]
(previous change had to be reverted)

**Comment by Alcaro** [comment]
For those wondering, the revert is https://github.com/llvm/llvm-project/pull/88884 (which also reverts https://github.com/llvm/llvm-project/issues/88478 )

**Comment by usx95** [comment]
Updated PR: https://github.com/llvm/llvm-project/pull/89154

**Comment by usx95** [comment]
Thanks for pointing out. This does seem like another blocker for stmt-expr but is not effecting  to **C++20 coroutines**. So let's keep this bug as closed and fixed.
