### ISSUE TITLE
GlobalISel AMDGPU infinite loop related to G_ADD reassociation

### ISSUE THREAD

**Issue by jayfoad** [llvm/llvm-project#63849]
After this commit:
```
commit 3a80bdb3169192361a6113397d9967a880de44bd (HEAD)
Author: Amara Emerson <amara@apple.com>
Date:   Mon Jul 10 00:25:49 2023 -0700

    [GlobalISel] Remove an erroneous oneuse check in the G_ADD reassociation combine.
    
    This check was unnecessary/incorrect, it was already being done by the target
    hook default implementation, and the one in the matcher was checking for a
    completely different thing. This change:
     1) Removes the check and updates affected tests which now do some more reassociations.
     2) Modifies the AMDGPU hooks which were stubbed with "return true" to also do the oneuse
        check. Not sure why I didn't do this the first time.
```
I get an infinite loop on this test case:
```
$ cat r.ll
define i32 @_amdgpu_cs_main(i32 %arg, <4 x i32> %arg1) {
bb:
  %i = insertelement <4 x i32> %arg1, i32 0, i64 0
  %i2 = icmp eq <4 x i32> %i, zeroinitializer
  %i3 = select <4 x i1> %i2, <4 x i32> <i32 1, i32 1, i32 1, i32 1>, <4 x i32> zeroinitializer
  %i4 = extractelement <4 x i32> %i3, i64 0
  %i5 = add i32 %arg, 1
  %i6 = add i32 %i5, %i4
  ret i32 %i6
}
$ ~/llvm-release/bin/llc -march=amdgcn -mcpu=gfx1100 -o /dev/null -global-isel r.ll
<hangs>
```

**Comment by aemerson** [comment]
I think the triggering issue is that AMDGPUPostLegalizerCombiner isn't using a CSE MachineIRBuilder, so it generates constant-foldable G_ADDs.
Step 1:
```
bb.1.bb:
  liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4
  %0:_(s32) = COPY $vgpr0
  %13:_(s32) = G_CONSTANT i32 1
  %51:_(s32) = G_ADD %0:_, %13:_
  %16:_(s32) = G_ADD %51:_, %13:_
  $vgpr0 = COPY %16:_(s32)
  SI_RETURN implicit $vgpr0
```

We then do the reassociation on `%16`, which generates:
```
bb.1.bb:
  liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4
  %0:_(s32) = COPY $vgpr0
  %13:_(s32) = G_CONSTANT i32 1
  %51:_(s32) = G_ADD %0:_, %13:_
  %52:_(s32) = G_ADD %13:_, %13:_
  %16:_(s32) = G_ADD %0:_, %52:_
  $vgpr0 = COPY %16:_(s32)
  SI_RETURN implicit $vgpr0
```

and then we re-try the reassociation match on `%16` again, and this successfully matches, leaving us with even more:
```
bb.1.bb:
  liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4
  %0:_(s32) = COPY $vgpr0
  %13:_(s32) = G_CONSTANT i32 1
  %51:_(s32) = G_ADD %0:_, %13:_
  %52:_(s32) = G_ADD %13:_, %13:_
  %53:_(s32) = G_ADD %13:_, %0:_
  %16:_(s32) = G_ADD %53:_, %13:_
  $vgpr0 = COPY %16:_(s32)
  SI_RETURN implicit $vgpr0
```

So I think constant folding combines need to run in between to simplify the output. According to Combine.td they're specified after the re-associations. However, even if we reschedule them to run before, the combiner adds newly created instructions to the end of the worklist, so it seems it still doesn't simplify it in time.

**Comment by aemerson** [comment]
Correction: the issue with the worklist is that new or mutated instructions are both added to the end (and we pop off the end too). The constant fold-able G_ADD is pushed first, then the new G_ADD that uses it. We pop off the end so we still process the new G_ADD before the constant-foldable one 🙃

In the near term I think we can just work around this by checking for this non-constant-folded input in the reassoc combine, but it's not ideal.

**Comment by jayfoad** [comment]
> In the near term I think we can just work around this by checking for this non-constant-folded input in the reassoc combine, but it's not ideal.

This is my attempt at that: https://reviews.llvm.org/D155284

**Comment by arsenm** [comment]
I would not expect constant fold and CSE to be mandatory

**Comment by aemerson** [comment]
> I would not expect constant fold and CSE to be mandatory

Yes agreed, the combine should be stable in the absence of simplifications.

However, is there a reason AMDGPU doesn't use the CSE MIRBuilder there?

**Comment by jayfoad** [comment]
> However, is there a reason AMDGPU doesn't use the CSE MIRBuilder there?

I don't think so. We just haven't found it necessary to enable it yet.
