### ISSUE TITLE
Error: unterminated attribute group using llvm-as

### ISSUE THREAD

**Issue by clw5710** [llvm/llvm-project#63850]
I am trying to use LLVM assembler to translate a human-readable LLVM assembly language file to LLVM bitcode. I am using LLVM 10.0. When I run the command `llvm-as 04_llvm.ll` I get `error:unterminated attribute group attributes #0 = { nocallback nofree nounwind willreturn memory(argmem: readwrite) }`. I can post the full code but it's 800 lines. 

What could be causing this issue?

Thank you

**Comment by EugeneZelenko** [comment]
Could you please try 16 or `main` branch?

**Comment by clw5710** [comment]
I'm not sure what you mean could you elaborate? I'm using an ubuntu 20.04 system by the way.

**Comment by EugeneZelenko** [comment]
I mean LLVM version. 10 is too old.

**Comment by clw5710** [comment]
I don't understand why I don't have version 16 I followed the Getting Started instructions: 
```
git clone https://github.com/llvm/llvm-project.git
cmake -S llvm -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
```
Shouldn't this get the latest version?
What am I doing wrong?

**Comment by arsenm** [comment]
Your old tool is trying to parse new attributes (and new attribute syntax) it doesn't recognize and failing. There is no backwards compatibility for  text IR. There is only forward compatibility for bitcode reading. You need to use llvm tools at least as new as the new memory attribute

**Comment by arsenm** [comment]
> Shouldn't this get the latest version?

Yes, are you actually running the build or do you have some old version in your path? Why do you think you are using llvm-10? --version should work for most of the tools

**Comment by clw5710** [comment]
Okay I uninstalled llvm completely in case it was using an old version. I reinstalled using: 
```
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
sudo ./llvm.sh all
```

The stable version in the script is 16. After running I can't get any version to display using llvm-config --version
