### ISSUE TITLE
[SimplifyCFG] Switch not fully optimized

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#63876]
https://alive2.llvm.org/ce/z/vAWi88
```llvm
define i8 @src(i8 noundef %arg) {
start:
  switch i8 %arg, label %unreachable [
    i8 0, label %case012
    i8 1, label %case1
    i8 2, label %case2
    i8 3, label %end
  ]

unreachable:
  unreachable

case1:
  br label %case012

case2:
  br label %case012

case012:
  %phi1 = phi i8 [ 3, %case2 ], [ 2, %case1 ], [ 1, %start ]
  br label %end

end:
  %phi2 = phi i8 [ %phi1, %case012 ], [ 4, %start ]
  ret i8 %phi2
}
```
We should combine this into a single phi, resulting in something like this:
```llvm
define i8 @tgt(i8 noundef %arg) {
start:
  switch i8 %arg, label %unreachable [
    i8 0, label %end
    i8 1, label %case1
    i8 2, label %case2
    i8 3, label %case3
  ]

unreachable:
  unreachable

case1:
  br label %end

case2:
  br label %end

case3:
  br label %end

end:
  %phi = phi i8 [ 4, %case3 ], [ 3, %case2 ], [ 2, %case1 ], [ 1, %start ]
  ret i8 %phi
}
```
At which point it is subject to lookup table optimization and converted into "add 1".

**Comment by XChy** [comment]
A possible [Solution](https://reviews.llvm.org/D155940) here.

**Comment by XChy** [comment]
I agree with your idea of merging phis. However, here I found that lookup optimization doesn't fold the latter IR for the reason that "i8 is not type legal for lookup table" on my x86_64 machine. Actually, it's unfoldable for i32, i64, too. But I think such "LinearMapKind" lookup table should be machine-independent, which may be a bug? What's your opinion here.

**Comment by XChy** [comment]
#67275 resolves it.
