### ISSUE TITLE
[clang-format] 15.0 FixNamespaceComment does not add comment in case of single lambda

### ISSUE THREAD

**Issue by gotnone** [llvm/llvm-project#63882]
The error seems to occur when a namespace surrounds a single named lambda, regardless of the contents of the lambda.

````
namespace foo {
auto bar = [] {
int should;
int trigger;
int namespace;
int comment;
};
}

````

I would expect to see `} // namespace foo`, but the result with --style=LLVM is:
````
namespace foo {
auto bar = [] {
  int should;
  int trigger;
  int namespace;
  int comment;
};
}

````
It appears that this is being tagged as a short namespace.

**Comment by EugeneZelenko** [comment]
Could you please try 16 or `main` branch?

**Comment by gotnone** [comment]
I don't have 16 available, but https://clang-format-configurator.site/ indicates that it is still broken on 16.0.4

**Comment by gotnone** [comment]
Still seems broken on 16.0.5.
````
$ clang-format --version
clang-format version 16.0.5
````


````
namespace foo {
auto bar = [] {
  int should;
  int trigger;
  int namespace;
  int comment;
};
}
````

**Comment by owenca** [comment]
https://reviews.llvm.org/D157244
