### ISSUE TITLE
_LIBCPP_ENABLE_CXX20_REMOVED_ALLOCATOR_MEMBERS causes bad diagnostics

### ISSUE THREAD

**Issue by smeenai** [llvm/llvm-project#63900]
I'm upgrading Meta's Android codebase to C++20, and I'm building with `-D_LIBCPP_ENABLE_CXX20_REMOVED_ALLOCATOR_MEMBERS` globally to ease the initial transition. That somehow causes incomplete backtraces in some diagnostics. See https://godbolt.org/z/TMKWrzd59 as an example, where the error message has no reference to the actual problematic `emplace_back` call, whereas either building with `-std=c++17` (https://godbolt.org/z/1oq4q4Pb8) or removing `-D_LIBCPP_ENABLE_CXX20_REMOVED_ALLOCATOR_MEMBERS` (https://godbolt.org/z/6v3f7aKor) gives the expected full error.

Can we improve this? I expect it's not uncommon to use `-D_LIBCPP_ENABLE_CXX20_REMOVED_ALLOCATOR_MEMBERS` and other definitions during the C++20 upgrade process, and there are certain errors that are exposed only when building with C++20 (e.g. https://godbolt.org/z/cEMvdrca8), so this issue makes it much harder to figure out the cause of those errors.

**Comment by philnik777** [comment]
This looks to me like a clang issue, not a libc++ one. We don't control what diagnostics are issued (except for attributes which influence it).

**Comment by smeenai** [comment]
Fair enough, but the issue arising specifically with `_LIBCPP_ENABLE_CXX20_REMOVED_ALLOCATOR_MEMBERS` made me think it might be something that libc++ could control to an extent.

**Comment by philnik777** [comment]
> Fair enough, but the issue arising specifically with `_LIBCPP_ENABLE_CXX20_REMOVED_ALLOCATOR_MEMBERS` made me think it might be something that libc++ could control to an extent.

Possibly. For that reason I didn't declare it purely a clang diagnostic issue, but I don't think it's worth it to try to find out how to rewrite libc++ to fix it. Although that would probably result in a nice reproducer for the clang folks, so maybe it is. Anyways, if you (or anyone else) wants to investigate improving the diagnostic, feel free to. I just don't expect any of the regular libc++ folks to work on this. Fixing this in clang would also improve the diagnostics for everything, not just libc++ specifically.
