### ISSUE TITLE
llvm problem "dotnet publish --configuration Release"

### ISSUE THREAD

**Issue by testirme** [llvm/llvm-project#63907]
dotnet publish --configuration Release
MSBuild version 17.6.8+c70978d4d for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Test -> D:\Test\bin\Release\net7.0\browser-wasm\Test.dll
  Optimizing assemblies for size. This process might take a while.
  Test -> D:\Test\bin\Release\net7.0\browser-wasm\publish\
  Test -> D:\Test\bin\Release\net7.0\browser-wasm\Test.dll
  Test -> D:\Test\bin\Release\net7.0\browser-wasm\publish\
  Compiling native assets with emcc with -Oz. This may take a while ...
  Linking for initial memory $(EmccInitialHeapSize)=16777216 bytes. Set this msbuild property to change the value.
  Linking with emcc with -O2. This may take a while ...
   "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.12.Sdk.win-x64\7.0.9\tools\bin\wasm-ld.exe" -o D
  :\Test\obj\Release\net7.0\browser-wasm\wasm\for-publish\dotnet.wasm --allow-undefined --allow-undefined D:\Test\obj\R
  elease\net7.0\browser-wasm\wasm\for-publish\pinvoke.o D:\Test\obj\Release\net7.0\browser-wasm\wasm\for-publish\driver
  .o D:\Test\obj\Release\net7.0\browser-wasm\wasm\for-publish\corebindings.o "C:\Program Files\dotnet\packs\Microsoft.N
  ETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libicudata.a" "C:\Program Files\dotnet\packs\
  Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libicui18n.a" "C:\Program Files\do
  tnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libicuuc.a" "C:\Program
   Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libmono-compon
  ent-debugger-stub-static.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runt
  imes\browser-wasm\native\libmono-component-diagnostics_tracing-stub-static.a" "C:\Program Files\dotnet\packs\Microsof
  t.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libmono-component-hot_reload-stub-static.a
  " "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\l
  ibmono-ee-interp.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\bro
  wser-wasm\native\libmono-icall-table.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-was
  m\7.0.9\runtimes\browser-wasm\native\libmono-ilgen.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mo
  no.browser-wasm\7.0.9\runtimes\browser-wasm\native\libmono-profiler-aot.a" "C:\Program Files\dotnet\packs\Microsoft.N
  ETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libmono-wasm-eh-js.a" "C:\Program Files\dotne
  t\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libmonosgen-2.0.a" "C:\Pro
  gram Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libSystem.
  IO.Compression.Native.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtime
  s\browser-wasm\native\libSystem.Native.a" "-LC:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.12.Ca
  che.win-x64\7.0.9\tools\emscripten\cache\sysroot\lib\wasm32-emscripten" -lGL -lal -lhtml5 -lstubs -lnoexit -lc -ldlma
  lloc -lcompiler_rt -lc++ -lc++abi -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cx
  x-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --export-if-defined=malloc --expor
  t-if-defined=memalign --export-if-defined=memset --export-if-defined=htons --export-if-defined=ntohs --export-if-defi
  ned=free --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export=stackSave --export=stackRestor
  e --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=malloc --export=free --export=__c
  xa_is_pointer_type --export=__cxa_can_catch --export=setThrew --export=ntohs --export=htons --export=__dl_seterr --ex
  port=htonl --export=emscripten_builtin_memalign --export-table -z stack-size=5242880 --initial-memory=16777216 --no-e
  ntry --max-memory=2147483648 --global-base=1024
  PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
  Stack dump:
  0.    Program arguments: "C:\\Program Files\\dotnet\\packs\\Microsoft.NET.Runtime.Emscripten.3.1.12.Sdk.win-x64\\7.0.
  9\\tools\\bin\\wasm-ld.exe" -o D:\\Test\\obj\\Release\\net7.0\\browser-wasm\\wasm\\for-publish\\dotnet.wasm --allow-u
  ndefined --allow-undefined D:\\Test\\obj\\Release\\net7.0\\browser-wasm\\wasm\\for-publish\\pinvoke.o D:\\Test\\obj\\
  Release\\net7.0\\browser-wasm\\wasm\\for-publish\\driver.o D:\\Test\\obj\\Release\\net7.0\\browser-wasm\\wasm\\for-pu
  blish\\corebindings.o "C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\\7.0.9\\runt
  imes\\browser-wasm\\native\\libicudata.a" "C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Runtime.Mono.brows
  er-wasm\\7.0.9\\runtimes\\browser-wasm\\native\\libicui18n.a" "C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.Ap
  p.Runtime.Mono.browser-wasm\\7.0.9\\runtimes\\browser-wasm\\native\\libicuuc.a" "C:\\Program Files\\dotnet\\packs\\Mi
  crosoft.NETCore.App.Runtime.Mono.browser-wasm\\7.0.9\\runtimes\\browser-wasm\\native\\libmono-component-debugger-stub
  -static.a" "C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\\7.0.9\\runtimes\\brows
  er-wasm\\native\\libmono-component-diagnostics_tracing-stub-static.a" "C:\\Program Files\\dotnet\\packs\\Microsoft.NE
  TCore.App.Runtime.Mono.browser-wasm\\7.0.9\\runtimes\\browser-wasm\\native\\libmono-component-hot_reload-stub-static.
  a" "C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\\7.0.9\\runtimes\\browser-wasm\
  \native\\libmono-ee-interp.a" "C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\\7.0
  .9\\runtimes\\browser-wasm\\native\\libmono-icall-table.a" "C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.R
  untime.Mono.browser-wasm\\7.0.9\\runtimes\\browser-wasm\\native\\libmono-ilgen.a" "C:\\Program Files\\dotnet\\packs\\
  Microsoft.NETCore.App.Runtime.Mono.browser-wasm\\7.0.9\\runtimes\\browser-wasm\\native\\libmono-profiler-aot.a" "C:\\
  Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\\7.0.9\\runtimes\\browser-wasm\\native\
  \libmono-wasm-eh-js.a" "C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\\7.0.9\\run
  times\\browser-wasm\\native\\libmonosgen-2.0.a" "C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Runtime.Mono
  .browser-wasm\\7.0.9\\runtimes\\browser-wasm\\native\\libSystem.IO.Compression.Native.a" "C:\\Program Files\\dotnet\\
  packs\\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\\7.0.9\\runtimes\\browser-wasm\\native\\libSystem.Native.a" "-
  LC:\\Program Files\\dotnet\\packs\\Microsoft.NET.Runtime.Emscripten.3.1.12.Cache.win-x64\\7.0.9\\tools\\emscripten\\c
  ache\\sysroot\\lib\\wasm32-emscripten" -lGL -lal -lhtml5 -lstubs -lnoexit -lc -ldlmalloc -lcompiler_rt -lc++ -lc++abi
   -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscr
  ipten-sjlj -mllvm -disable-lsr --import-undefined --export-if-defined=malloc --export-if-defined=memalign --export-if
  -defined=memset --export-if-defined=htons --export-if-defined=ntohs --export-if-defined=free --export-if-defined=__st
  art_em_asm --export-if-defined=__stop_em_asm --export=stackSave --export=stackRestore --export=stackAlloc --export=__
  wasm_call_ctors --export=__errno_location --export=malloc --export=free --export=__cxa_is_pointer_type --export=__cxa
  _can_catch --export=setThrew --export=ntohs --export=htons --export=__dl_seterr --export=htonl --export=emscripten_bu
  iltin_memalign --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=2147483648 --gl
  obal-base=1024
  #0 0x00007ff751062c98 C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.12.Sdk.win-x64\7.0.9\tools\b
  in\wasm-ld.exe 0x32c98 C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.12.Sdk.win-x64\7.0.9\tools\
  bin\wasm-ld.exe 0x32c6f
  #1 0x00007ff751062c98 C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.12.Sdk.win-x64\7.0.9\tools\b
  in\wasm-ld.exe 0x362e8 C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.12.Sdk.win-x64\7.0.9\tools\
  bin\wasm-ld.exe 0x1f3d
  #2 0x00007ff751062c98 C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.12.Sdk.win-x64\7.0.9\tools\b
  in\wasm-ld.exe 0x1329 C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.12.Sdk.win-x64\7.0.9\tools\b
  in\wasm-ld.exe 0x2059ed8
  #3 0x00007ff751062c98 (C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.12.Sdk.win-x64\7.0.9\tools\
  bin\wasm-ld.exe+0x32c98)
  #4 0x00007ff751062c6f (C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.12.Sdk.win-x64\7.0.9\tools\
  bin\wasm-ld.exe+0x32c6f)
  0x00007FF751062C98 (0x000000008EC02200 0x00007FF753077937 0x000000008EC02200 0x0000000000000000)
  0x00007FF751062C6F (0x0000000000000003 0x00007FF700000000 0x0000000000000248 0x000000B08778ED01)
  0x00007FF7510662E8 (0x0000027E8EBFFF76 0x0000027E8EBFFFF7 0x0000027E8EC0007F 0x0000027E8EC00105)
  0x00007FF751031F3D (0x0000027E8EBD5000 0x0000000000000011 0x0000027E8EBD5000 0x0000000000000000)
  0x00007FF751031329 (0x0000000000000000 0x00007FF753089F51 0x0000000000000000 0x0000000000000000)
  0x00007FF753089ED8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
  0x00007FF99BB426AD (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk
  () + 0x1D bytes(s)
  0x00007FF99CECAA68 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart(
  ) + 0x28 bytes(s)
emcc : error : '"C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.12.Sdk.win-x64\7.0.9\tools\bin\wasm
-ld.exe" -o D:\Test\obj\Release\net7.0\browser-wasm\wasm\for-publish\dotnet.wasm --allow-undefined --allow-undefined D:
\Test\obj\Release\net7.0\browser-wasm\wasm\for-publish\pinvoke.o D:\Test\obj\Release\net7.0\browser-wasm\wasm\for-publi
sh\driver.o D:\Test\obj\Release\net7.0\browser-wasm\wasm\for-publish\corebindings.o "C:\Program Files\dotnet\packs\Micr
osoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libicudata.a" "C:\Program Files\dotnet\p
acks\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libicui18n.a" "C:\Program Files
\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libicuuc.a" "C:\Progra
m Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libmono-compone
nt-debugger-stub-static.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtime
s\browser-wasm\native\libmono-component-diagnostics_tracing-stub-static.a" "C:\Program Files\dotnet\packs\Microsoft.NET
Core.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libmono-component-hot_reload-stub-static.a" "C:\P
rogram Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libmono-ee
-interp.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\n
ative\libmono-icall-table.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runti
mes\browser-wasm\native\libmono-ilgen.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm
\7.0.9\runtimes\browser-wasm\native\libmono-profiler-aot.a" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtim
e.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libmono-wasm-eh-js.a" "C:\Program Files\dotnet\packs\Microsoft.N
ETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libmonosgen-2.0.a" "C:\Program Files\dotnet\pac
ks\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\libSystem.IO.Compression.Native.a
" "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\browser-wasm\native\lib
System.Native.a" "-LC:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.12.Cache.win-x64\7.0.9\tools\ems
cripten\cache\sysroot\lib\wasm32-emscripten" -lGL -lal -lhtml5 -lstubs -lnoexit -lc -ldlmalloc -lcompiler_rt -lc++ -lc+
+abi -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-ems
cripten-sjlj -mllvm -disable-lsr --import-undefined --export-if-defined=malloc --export-if-defined=memalign --export-if
-defined=memset --export-if-defined=htons --export-if-defined=ntohs --export-if-defined=free --export-if-defined=__star
t_em_asm --export-if-defined=__stop_em_asm --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm
_call_ctors --export=__errno_location --export=malloc --export=free --export=__cxa_is_pointer_type --export=__cxa_can_c
atch --export=setThrew --export=ntohs --export=htons --export=__dl_seterr --export=htonl --export=emscripten_builtin_me
malign --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=2147483648 --global-base=
1024' failed (returned 3221225477) [D:\Test\Test.csproj]
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.9\Sdk\WasmApp.Native.targets(423,5): error MSB3
073: The command "emcc "@C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.9\runtimes\b
rowser-wasm\native\src\emcc-default.rsp" "@C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-was
m\7.0.9\runtimes\browser-wasm\native\src\emcc-link.rsp" "@D:\Test\obj\Release\net7.0\browser-wasm\wasm\for-publish\emcc
-link.rsp"" exited with code 1. [D:\Test\Test.csproj]

**Comment by Naville** [comment]
I think this issue should be submitted to your compiler-vendor (aka Microsoft)?

**Comment by testirme** [comment]
Thanks
