### ISSUE TITLE
LLVM install error: Unable to find command despite executables existing

### ISSUE THREAD

**Issue by clw5710** [llvm/llvm-project#63915]
I'm trying to install LLVM on an Ubuntu 20.04 VM but I'm running into issues. Here are the steps I've followed according to the [instructions][1]: 
1. `git clone --depth 1 https://github.com/llvm/llvm-project.git`
2. `cd llvm-project`
3. `cmake -S llvm -B build -G Ninja -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_BUILD_TYPE=Release`
4. `ninja -C build check-llvm`

I see a build folder with bin executable that contains the llvm commands I want to use, but anytime I run a command it says "Command not found". I don't understand what the issue is. 

This is probably a simple issue but I've been struggling for too long.

  [1]: https://llvm.org/docs/GettingStarted.html#getting-the-source-code-and-building-llvm

**Comment by asl** [comment]
@clw5710 which of these step does produce an error message?

**Comment by clw5710** [comment]
None of these steps in particular. When I run one of the llvm commands is when I get the error "command not found". For example, if I run llvm-configure --version I get the error " "llvm-configure" command is not found"

**Comment by asl** [comment]
Well, there is no llvm-provided tool named `llvm-configure`. If you're talking about `llvm-config`, then it is located in `bin` sub-directory. So, you'd need either to add the `bin` directory to `PATH` or use full path, e.g. `<full_path_to_llvm_build_dir>/bin/llvm-config`
