### ISSUE TITLE
[AIX][toc-data] Miscompile when accessing tocdata variable at non-zero offset

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [llvm/llvm-project#63927]
Consider:
```cpp
unsigned int x = 0x0D002A00;
int main(void) { return 0xff & (x >> 8); }
```

The following IR, generated using the above C program, generates incorrect assembly for AIX out of `llc`:
```ll
@x = local_unnamed_addr global i32 218114560, align 4 #0

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(read, argmem: none, inaccessiblemem: none)
define i32 @main() local_unnamed_addr #1 {
entry:
  %0 = load i32, ptr @x, align 4
  %shr = lshr i32 %0, 8
  %and = and i32 %shr, 255
  ret i32 %and
}

attributes #0 = { "toc-data" }
```

In particular, the value loaded is byte value for the most significant byte (not the second least significant byte):
```
$ llc \
<<<$'@x = local_unnamed_addr global i32 218114560, align 4 #0\n\n; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(read, argmem: none, inaccessiblemem: none)\ndefine i32 @main() local_unnamed_addr #1 {\nentry:\n  %0 = load i32, ptr @x, align 4\n  %shr = lshr i32 %0, 8\n  %and = and i32 %shr, 255\n  ret i32 %and\n}\n\nattributes #0 = { "toc-data" }' \
-mtriple=powerpc-ibm-aix - -o - | grep -C2 lbz
.main:
# %bb.0:                                # %entry
        lbz 3, x[TD](2)
        blr
L..main0:
```

**Comment by hubert-reinterpretcast** [comment]
For reference, the following is okay (with the small code model):
```
        lbz 3, x[TD](2)+3
```

Apparently, applying the offset this way is not okay with the large code model.

**Comment by mandlebug** [comment]
Thanks Hubert. I've posted https://reviews.llvm.org/D155957 as an initial fix. It's not ideal in that it ends up disabling the peephole when the offset is non-zero on the consuming load/store for now. I tried a more general fix but I'm too fuzzy on all the ELF nodes other then the ADDItocHa/ADDItocL this affects and will need more time/testing before attempting that change.

**Comment by hubert-reinterpretcast** [comment]
> It's not ideal in that it ends up disabling the peephole when the offset is non-zero on the consuming load/store for now. I tried a more general fix but I'm too fuzzy on all the ELF nodes other then the ADDItocHa/ADDItocL this affects and will need more time/testing before attempting that change.

@amy-kwan, perhaps you have more information from your work on the follow-up patch to https://reviews.llvm.org/D155600 for optimizing `-maix-small-local-exec-tls` with non-zero load/store offsets? Would it make sense to extend the scope of that patch to cover toc-data too?
