### ISSUE TITLE
[FunctionAttrs] Recursive calls can have different effects

### ISSUE THREAD

**Issue by jdoerfert** [llvm/llvm-project#63936]
Function Attrs assumes recursive calls (or any call in the SCC) has the same effect as the SCC (at most). This is not true:

https://godbolt.org/z/fjj3r9v7q
```ll
@G = global i32 0

define void @bar(ptr %p) {
  %pval = load ptr, ptr %p
  call void @bar(ptr %pval)
  store i32 0, ptr @G
  ret void
}
```
The function itself, w/o the recursive call, only loads argument memory and writes global memory. The recursive call however, reads non-argument memory, at least in my understanding of `argmemonly/argmem`.

Tag (@nikic @fhahn @aeubanks)

**Comment by nikic** [comment]
Interesting case! I agree that this shouldn't be argmemonly.

**Comment by nikic** [comment]
Candidate patch: https://reviews.llvm.org/D155956
