### ISSUE TITLE
[clang][tooling] regression: clang tools no longer accept already-preprocessed input

### ISSUE THREAD

**Issue by stephenrkell** [llvm/llvm-project#63941]
Until some time a couple of years ago, a `ClangTool` happily accepted already-preprocessed source (e.g. `.i` or `.ii` files) as input. I'm finding this is no longer the case but it looks like this is not intentional.

Here are some steps to reproduce.

Build a simple `ClangTool`, e.g. using the libTooling documentation's example (https://clang.llvm.org/docs/LibTooling.html). Currently it is necessary to modify that example since it was broken by D94420 and the fix in D152771 has not yet landed; the following code should work.

```
$ cat >test.cc <<EOF
// Declares clang::SyntaxOnlyAction.
#include "clang/Frontend/FrontendActions.h"
#include "clang/Tooling/CommonOptionsParser.h"
#include "clang/Tooling/Tooling.h"
// Declares llvm::cl::extrahelp.
#include "llvm/Support/CommandLine.h"

using namespace clang::tooling;
using namespace llvm;

// Apply a custom category to all command-line options so that they are the
// only ones displayed.
static cl::OptionCategory MyToolCategory("my-tool options");

int main(int argc, const char **argv) {
  // CommonOptionsParser::create will parse arguments and create a
  // CompilationDatabase.
  auto ExpectedParser = CommonOptionsParser::create(argc, argv, MyToolCategory);
  if (!ExpectedParser) {
    // Fail gracefully for unsupported options.
    llvm::errs() << ExpectedParser.takeError();
    return 1;
  }
  CommonOptionsParser &OptionsParser = ExpectedParser.get();
  ClangTool Tool(OptionsParser.getCompilations(),
                 OptionsParser.getSourcePathList());
  return Tool.run(newFrontendActionFactory<clang::SyntaxOnlyAction>().get());
}
EOF
```

Build it, e.g. as follows assuming a recent build is installed to `/usr/local/lib` (better ways may be possible!).

```
$ c++ -fno-rtti -fno-exceptions -o test test.cc \
`llvm-config --cxxflags` \
-Wl,-\( /usr/local/lib/libclang*17* -Wl,-\) \
`llvm-config --libs`
```

Run it on some already-preprocessed code; it claims there is not "exactly one compiler job" in the command line, even though there obviously is.

```
$ echo 'int main(void) { return 0; }' > true.i
$ ./test true.i -- clang -c
error: unable to handle compilation, expected exactly one compiler job in ' "/usr/local/src/bug-report-20230718/clang-tool" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-fsyntax-only" "-disable-free" "-clear-ast-before-backend" "-main-file-name" "true.i" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=/usr/local/src/bug-report-20230718" "-resource-dir" "/usr/local/src/lib/clang/17" "-fdebug-compilation-dir=/usr/local/src/bug-report-20230718" "-ferror-limit" "19" "-fgnuc-version=4.2.1" "-fcolor-diagnostics" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "cpp-output" "/usr/local/src/bug-report-20230718/true.i"; '
```

The problem is D105695 "Accept Clang invocations with multiple jobs", which tries to identify a single compilation job in the compiler command line. Unfortunately it does not recognise jobs that take already-preprocessed source as input, because it uses `clang::driver::types::isSrcFile` which explicitly excludes already-preprocessed files.

https://clang.llvm.org/doxygen/namespaceclang_1_1driver_1_1types.html#a9402144812ad57ff7ea95a716818da96

The problem is that not all files needing compilation, or that might be input to a `ClangTool`, are "source" files in the sense of also needing preprocessing. The obvious fix is to replace `IsSrcFile` with a test for files needing compilation, not just "source" files. I don't see a neat way to do this using the definitions in `types.h`... but my quick fix does the following.

```
diff --git a/clang/lib/Tooling/Tooling.cpp b/clang/lib/Tooling/Tooling.cpp
index 5242134097da..00c0c4297bd9 100644
--- a/clang/lib/Tooling/Tooling.cpp
+++ b/clang/lib/Tooling/Tooling.cpp
@@ -138,7 +138,10 @@ getCC1Arguments(DiagnosticsEngine *Diagnostics,
   };
 
   auto IsSrcFile = [](const driver::InputInfo &II) {
-    return isSrcFile(II.getType());
+    return isSrcFile(II.getType())
+        || II.getType() == driver::types::TY_PP_CXX
+        || II.getType() == driver::types::TY_PP_C
+        || II.getType() == driver::types::TY_PP_ObjC;
   };
 
   llvm::SmallVector<const driver::Command *, 1> CC1Jobs;

```

**Comment by jryans** [comment]
Potential fix up for review: https://reviews.llvm.org/D157011

**Comment by stephenrkell** [comment]
@jryans Thanks! This is great.
