### ISSUE TITLE
[clang-format] RemoveSemicolon eats semicolon after catch benchmark

### ISSUE THREAD

**Issue by HazardyKnusperkeks** [llvm/llvm-project#63950]
``` c++
BENCHMARK("Foo") {
  return 0;
};
```
with `RemoveSemicolon` eats the latter.

It's markes as `FunctionLBrace`:
```
AnnotatedTokens(L=0, P=0, T=5, C=0):
 M=0 C=0 T=Unknown S=1 F=0 B=0 BK=0 P=0 Name=identifier L=9 PPK=2 FakeLParens= FakeRParens=0 II=0xdfaa560 Text='BENCHMARK'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=23 Name=l_paren L=10 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='('
 M=0 C=1 T=Unknown S=0 F=0 B=0 BK=0 P=140 Name=string_literal L=15 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='"Foo"'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=43 Name=r_paren L=16 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text=')'
 M=0 C=0 T=FunctionLBrace S=1 F=0 B=0 BK=1 P=23 Name=l_brace L=18 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='{'
```

But it actually is a lambda: https://github.com/catchorg/Catch2/blob/6e79e682b726f524310d55dec8ddac4e9c52fb5f/src/catch2/benchmark/catch_benchmark.hpp#L124
Of course clang-format can't know that, should we add something like a `LambdaMacro`?

@owenca or do you see any other way?

**Comment by rymiel** [comment]
`Macros: ["BENCHMARK(x)=[](x)"]` Should do the trick, right?

By the way, I tried `BENCHMARK(x)=[]` which produces debug output `At token: "Foo"` even when `--debug` isn't provided.
I also tried `BENCHMARK=[]` which seemed to permanently freeze the tool. I guess these are separate issues.
CC @r4nt

**Comment by HazardyKnusperkeks** [comment]
> `Macros: ["BENCHMARK(x)=[](x)"]` Should do the trick, right?
> 
> By the way, I tried `BENCHMARK(x)=[]` which produces debug output `At token: "Foo"` even when `--debug` isn't provided. I also tried `BENCHMARK=[]` which seemed to permanently freeze the tool. I guess these are separate issues. CC @r4nt

See I wasn't involved in that review, and my current `.clang-format` does not contain it yet, I didn't look into the documentation.
I'll try it.

**Comment by HazardyKnusperkeks** [comment]
At least in code `Macros.push_back("BENCHMARK(x)=[]()");` does the trick.

**Comment by HazardyKnusperkeks** [comment]
For the debug output see: https://reviews.llvm.org/D156228

**Comment by owenca** [comment]
> But it actually is a lambda: https://github.com/catchorg/Catch2/blob/6e79e682b726f524310d55dec8ddac4e9c52fb5f/src/catch2/benchmark/catch_benchmark.hpp#L124 Of course clang-format can't know that, should we add something like a `LambdaMacro`?
> 
> @owenca or do you see any other way?

It's actually an incomplete `if` statement with a lambda header as its body. Fortunately, it seems that the `Macros` option can handle it.
