### ISSUE TITLE
[mlir][vector][llvm] Improve LLVM lowering of fmin/fmax reductions

### ISSUE THREAD

**Issue by dcaballe** [llvm/llvm-project#63969]
We currently generate llvm [`reduce_fmin`/`reduce_fmax`](https://github.com/llvm/llvm-project/blob/75d71800aa384ee58663d892c325572f5588df2a/mlir/lib/Conversion/VectorToLLVM/ConvertVectorToLLVM.cpp#L601C1-L601C1) intrinsics whose semantics don't match the NaN handling of [`arith.fmin`/`arith.fmax`](https://mlir.llvm.org/docs/Dialects/ArithOps/#arithminf-arithminfop) operations in MLIR. We should generate llvm `reduce_fminimum`/`reduce_fmaximum` intrinsics instead, which have been recently added to LLVM.

**Comment by unterumarmung** [comment]
https://reviews.llvm.org/D155869
https://reviews.llvm.org/D155877
