### ISSUE TITLE
MachO UUID dependency on `compute_thread_count` makes reproducing builds harder

### ISSUE THREAD

**Issue by PieroV** [llvm/llvm-project#63961]
We run builds on normalized containers to provide reproducible builds.
However, after updating from Clang 14.0.4 to Clang 16.0.4, we started not being able to reproduce builds anymore.
The build is still deterministic, if ran on the same machine multiple times, but it leads to different results when run in machines with different hardware. The binaries only differ on the UUID.
I think the problem is that `Writer::writeUuid()` has a dependency on `parallel::strategy.compute_thread_count()`.

We cross compile everything from Debian containers, in a LLVM we build ourselves by following Mozilla's build scripts.

Even an almost empty C file leads to the same result:

```C
int main() {}
```

```bash
clang -isysroot .../MacOSX13.3.sdk -target x86_64-apple-darwin -B .../cctools/bin -isysroot .../MacOSX13.3.sdk -fuse-ld=lld main.c
```

```
sha256sum a.out
3812ad038467550193e511fc201185d3e5ce2cac57142c8e0f8bb844c5493e3c  a.out # My machine, 16 threads
2dbca6391b414bc06af85d4a2a019b4616846b0cb7f57c3d39a359f3996b59b3  a.out # Build server, 64 threads
```

Stripping the UUID with Apple's strip (`llvm-strip` does not to support this feature), makes the files the same:

```
x86_64-apple-darwin-strip -ur -no_uuid a.out
sha256sum a.out
2e2ac0a89be330b80751bae739f481c173485b0b6825108b9ed17e2e87c368b9  a.out
```

**Comment by PieroV** [comment]
I've ran a build with a patched `lld` to use a hardcoded value and it solved my problems.
If this solution can work for you, I can open a PR.
Otherwise, implementing `-no_uuid` on `lld` would also work for me (but that would be much more difficult for me to do :smile:).

**Comment by keith** [comment]
@PieroV can you test with https://github.com/llvm/llvm-project/commit/2090d66b2376f3041d8a696fcaf94266188e6e96? It wasn't intended for this but might also change the behavior here

**Comment by oontvoo** [comment]
Perhaps instead of `-no_uuid`, we can support generating a uuid that
doesn't depend on the cores/threads count of the host

**Comment by keith** [comment]
I just tested with that commit and the issue still exists

**Comment by keith** [comment]
I opened https://reviews.llvm.org/D155733 for discussion

**Comment by keith** [comment]
I implemented `-no_uuid` as well here: https://reviews.llvm.org/D155735

**Comment by keith** [comment]
https://reviews.llvm.org/D155761

**Comment by PieroV** [comment]
Thank you very much for the quick fix!
