### ISSUE TITLE
[clang] Diagnostics falsely says that no viable `operator<=>` was found instead of `operator==` for a defaulted, implicitly deleted `operator==`

### ISSUE THREAD

**Issue by AMP999** [llvm/llvm-project#63960]
https://godbolt.org/z/cMKE3o1aG

```c++
struct C {
    friend std::strong_ordering operator<=>(const C&, const C&);
};
struct S {
    C c;
    bool operator==(const S&) const = default; //obscure warning
};
```

When defaulting an `operator==`, if there’s no viable `operator==` for a member, the compiler complains that the defaulted `operator==` is implicitly deleted "`because there is no viable three-way comparison function for member 'c'`", but we are actually looking for an equality operator in the member, not a three-way comparison operator.

**Comment by shafik** [comment]
CC @royjacobson
