### ISSUE TITLE
Clang cannot determine constant expressions through the `requires`-clause

### ISSUE THREAD

**Issue by hewillk** [llvm/llvm-project#63972]
Not sure if this has been reported yet. Clang rejects the second `static_assert`:

```cpp
template<int N>
struct S {
  constexpr auto size() { return N; }
};

template<int N>
void test(S<N> s) {
  static_assert( (s.size() != 0) ); // ok
  static_assert(requires { typename S< (s.size() != 0) >; }); // not ok
}

int main() {
  test(S<3>{});
}
```
https://godbolt.org/z/sGqKWMPqY

**Comment by unterumarmung** [comment]
Well, `s` is not a constant expression, so why `s.size()` would be?

**Comment by tbaederr** [comment]
The expression is:
```
RequiresExpr 0x6210000981a0 '_Bool' unsatisfied
`-TypeRequirement 0x621000098180 unsatisfied
```

so the problem seems to happen _before_ the expression is evaluated.

**Comment by usx95** [comment]
Another example:
```cpp
template <int N>
struct S {
    constexpr int foo() { return 2; }
};

void bar(S<1> s) {
    static_assert(requires { typename S<s.foo()>; });
}
```
https://godbolt.org/z/z551on98j
fails with a different error: `<source>:7:41: error: reference to local variable 's' declared in enclosing function 'bar'`

**Comment by zyn0217** [comment]
Both OP's example and the reduced one now compile on trunk. Closing.
