### ISSUE TITLE
clang++ is not able to compile a simple test program. /usr/bin/ld: cannot find -lstdc++: No such file or directory

### ISSUE THREAD

**Issue by pal-stdr** [llvm/llvm-project#63988]
My aim is to build mlir. I have cloned the 16.x version of llvm-project. I am getting the following error again and again.

```
....
....
Check for working CXX compiler: /home/<username>/installed-programs/clang-and-llvm/bin/clang++ - broken
CMake Error at /home/<username>/installed-programs/cmake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:60 (message):
  The C++ compiler

    "/home/<username>/installed-programs/clang-and-llvm/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:
.........
........
.......
    /usr/bin/ld: cannot find -lstdc++: No such file or directory
    clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
```
What I understood from my error is, **linker cant find `libstdc++.so` in the `$LD_LIBRARY_PATH`**. So then I searched for the the path (i.e. `/usr/lib/gcc/x86_64-linux-gnu/11`) and put it there like `export LD_LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/11${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}`. But no luck.

Right now I am using 
- downloaded the prebuilt `clang` binaries for 16.0.0 version.
- ubuntu server 22.04
- gcc-11.3.0

And following command is returning me this
```
/sbin/ldconfig -p | grep stdc++
	libstdc++.so.6 (libc6,x86-64) => /lib/x86_64-linux-gnu/libstdc++.so.6
```

And following is the `cmake` configuration

```
cmake   \
    -G Ninja    \
    -S ../llvm  \
    -B .    \
    -DCMAKE_BUILD_TYPE=Release      \
    -DCMAKE_INSTALL_PREFIX=../installation  \
    -DCLANG_BOOTSTRAP_PASSTHROUGH="CMAKE_INSTALL_PREFIX;CMAKE_VERBOSE_MAKEFILE"     \
    -DLLVM_ENABLE_ASSERTIONS=ON     \
    -DLLVM_ENABLE_PROJECTS="clang;lldb;mlir" \
    -DLLVM_USE_LINKER=lld   \
    -DCMAKE_C_COMPILER=clang    \
    -DCMAKE_CXX_COMPILER=clang++    \
    -DLLVM_TARGETS_TO_BUILD="Native;NVPTX"   \
    -DLLVM_CACHE_BUILD=ON   \
    -DLLVM_USE_SANITIZER="Address;Undefined"    \
    -DMLIR_INCLUDE_INTEGRATION_TESTS=ON    \
    -DLLVM_BUILD_EXAMPLE=ON    \
    -DLLVM_BUILD_TESTS=OFF    \
    -DLLVM_INCLUDE_TESTS=OFF
```

Searched a lot in the internet. Found similar problems. Some of them are talking about adding the path which already I tried. Some of them tells removing the `gcc` completely and reinstalling it again, which I can't. Because then it shows me the warning that it will remove nvidia drivers, vbox from my machine.

What can I do now?

**Comment by poyaoc97** [comment]
I don’t think the compiler driver cares about LD_LIBRARY_PATH regarding finding the required libraries. Try —gcc-install-dir instead or —sysroot. https://github.com/llvm/llvm-project/issues/57570#issuecomment-1287299027

**Comment by pal-stdr** [comment]
Hello @poyaoc97 
Thanks a lot for the reply.

Yes you are correct. I have checked the default library search path for the `clang++` binary
```
$ clang++ -v
clang version 16.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/pallab.sutradhar/installed-programs/clang-and-llvm/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
```
Considering the point that I am using prebuilt `clang++` binary, is there any way to update the search path to the `clang++`? Or is there any way to use multiple library search path for `clang++`?
If I want to do so, do I have to build `clang` binaries by myself?
Thanks in advance!

**Comment by poyaoc97** [comment]
I did a search in the Clang codebase and found this CMake option: `GCC_INSTALL_PREFIX`, also described in the 4th point under the section On Unix-like Systems at [Clang website](https://clang.llvm.org/get_started.html). Note that this flag is ignored if `--sysroot` is specified.

[This link might also be of interest.](https://unix.stackexchange.com/questions/22926/where-do-executables-look-for-shared-objects-at-runtime)

Let me know if that helps, if so whether this issue can be closed.

**Comment by pal-stdr** [comment]
Finally I found where is the problem. `libstdc++.so` is missing in the last `gcc` version's lib path `/usr/lib/gcc/x86_64-linux-gnu/12`. And this file was missing there because in the OS, there was no `g++` of version `12`. I had to install it, and the problem is gone.

Let me write that in details, if anybody other than me face the same problem.

I have two `gcc` versions in the machine, `gcc-11` & `gcc-12`
Since I'm using prebuilt `clang` of version `16.0.0`, It was searching for `libstdc++.so` in the highest `gcc` lib path `/usr/lib/gcc/x86_64-linux-gnu/12`. How can you check it for your own machine?

```
$ clang++ -v
clang version 16.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/<username>/installed-programs/clang-and-llvm/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
....
```

But that `libstdc++.so` file is missing there.

Then I installed the `g++` using
```
sudo apt-get install g++-12

```

And now the `libstdc++.so` is there in the `/usr/lib/gcc/x86_64-linux-gnu/12`. Problem solved.

And I also want to add the symptom of similar problem as error message telling you `libstdc++ version must be at least 7.1`. Because after a while I was trying to solve this issue, I was getting this error message too. Then I have double checked the version of `/usr/lib/gcc/x86_64-linux-gnu/12/libstdc++.so` using following command and found it is of version 6.

```
$ readelf -d /usr/lib/gcc/x86_64-linux-gnu/12/libstdc++.so | grep SONAME

 0x000000000000000e (SONAME)             Library soname: [libstdc++.so.6]
```

It means, LLVM 16.0.0 has nothing to do with `.... must be at least 7.1`. It perfectly builds with version 6 of `libstdc++.so.6`.

Hope all this helps. Special thanks to @poyaoc97 for helping me with this issue.
