### ISSUE TITLE
Add ghc calling convention to clang

### ISSUE THREAD

**Issue by chfast** [llvm/llvm-project#63987]

**Comment by chfast** [comment]
There is the discussion about it: https://discourse.llvm.org/t/rfc-exposing-ghccc-calling-convention-as-preserve-none-to-clang/74233.

**Comment by chfast** [comment]
The `[[clang::preserve_none]]` calling convention has been added to clang.

**Comment by brandtbucher** [comment]
Can we reopen this for AArch64 support?

**Comment by antangelo** [comment]
I've created #87423 to track AArch64 support. I am interested in working on it.
