### ISSUE TITLE
HIP compilation fails from undeclared identifier

### ISSUE THREAD

**Issue by markdewing** [llvm/llvm-project#63981]
On a recent mainline build, a HIP program including a thrust file fails with an error about an undeclared identifier:
```
/opt/rocm-5.4.3/include/hip/amd_detail/amd_hip_fp16.h:1520:21: error: use of undeclared identifier '__llvm_amdgcn_rcp_f16'
 1520 |                     __llvm_amdgcn_rcp_f16(static_cast<__half_raw>(x).data)};
      |                     ^
/opt/rocm-5.4.3/include/hip/amd_detail/amd_hip_fp16.h:1623:47: error: use of undeclared identifier '__llvm_amdgcn_rcp_2f16'
 1623 |             __half2 h2rcp(__half2 x) { return __llvm_amdgcn_rcp_2f16(x); }
      |                                               ^

```

The reproducer (the problem is in hip_f16.h, which gets included from thrust):
```
#include "hip/hip_fp16.h"
//#include "thrust/sort.h"

int main()
{
}

```

Compile line: `clang++ -x hip -I /opt/rocm-5.4.3/include hip_test.cpp`

The test uses rocm 5.4.3, but it also reproduces with rocm 5.5.0.

This affects mainline builds.  I don't know when it started, but a mainline build from May does not show this issue.

**Comment by arsenm** [comment]
These ugly intrinsic wrappers were removed from the HIP headers, so you're somehow mixing and matching new compiler and old headers

**Comment by markdewing** [comment]
This is the top of the 'git log' for LLVM, and it was a fresh check-out and build.
```
commit 3d1f89c2e37c4cf9017842a7d04ae07a5e096d08 (HEAD -> main, origin/main, origin/HEAD)
Author: John Harrison <harjohn@google.com>
Date:   Thu Jul 13 15:50:06 2023 -0700
```

```
[frontier]$ clang++ -x hip --offload-arch=gfx90a -I /opt/rocm-5.5.1/include hip_test.cpp 
In file included from hip_test.cpp:2:
In file included from /opt/rocm-5.5.1/include/hip/hip_fp16.h:29:
/opt/rocm-5.5.1/include/hip/amd_detail/amd_hip_fp16.h:1572:21: error: use of undeclared identifier '__llvm_amdgcn_rcp_f16'
 1572 |                     __llvm_amdgcn_rcp_f16(static_cast<__half_raw>(x).data)};
      |                     ^
/opt/rocm-5.5.1/include/hip/amd_detail/amd_hip_fp16.h:1675:47: error: use of undeclared identifier '__llvm_amdgcn_rcp_2f16'
 1675 |             __half2 h2rcp(__half2 x) { return __llvm_amdgcn_rcp_2f16(x); }
      |                                               ^
2 errors generated when compiling for gfx90a.
```

I can reproduce on a second machine as well.

**Comment by arsenm** [comment]
> This is the top of the 'git log' for LLVM, and it was a fresh check-out and build.

The old headers I'm referring to are the /opt/rocm/ HIP headers, not the clang provided builtin headers. I'm not sure how well new clang targeting old rocm is supposed to work.

__llvm_amdgcn_rcp_f16/__llvm_amdgcn_rcp_2f16 were removed from the clang provided builtin headers, and used in /opt/rocm-5.5.1/include/hip/hip_fp16.h. Tip of tree HIP uses the proper __builtin calls in this header

**Comment by markdewing** [comment]
Does this mean the building LLVM for AMDGPU has to be tightly coupled to the current ROCm?  Is the most current release (5.6.0) sufficient, or does it have to be from git?

**Comment by markdewing** [comment]
To track the changes my own understanding:

The commit in HIP that changed these functions is https://github.com/ROCm-Developer-Tools/hipamd/commit/36f929bb42a252533a61f1e275de6565bfbaa7ae

And the commit in LLVM that removed these functions is https://github.com/llvm/llvm-project/commit/f407a7399575a6821940973c54754d42e72dd9ce

**Comment by yxsamliu** [comment]
We do have users that use trunk clang with older ROCm and we try to maintain backward compatibility for a few releases. We have a buildbot which uses old ROCm and trunk clang to compile and test HIP programs so that major breakage can be detected. In this case, it only happens when you use #include "hip/hip_fp16.h", therefore it is missed.

We could add back the removed declarations with the deprecated attribute. After that, we can add a test to llvm-test-suite to capture this.

**Comment by arsenm** [comment]
https://reviews.llvm.org/D155982 brought back the ones that are breaking here, leaving the rest that deleted as removed
