### ISSUE TITLE
[AMDGPU] Crash in backend while attempting to codegen builtin memcpy

### ISSUE THREAD

**Issue by jhuber6** [llvm/llvm-project#63986]
The following LLVM-IR crashes with `llc -O3`. The problem is most likely due to the null argument that gets passed to memcpy. See https://godbolt.org/z/svov8z58j for the reduced reproducer.

**Comment by arsenm** [comment]
Interesting that this only happens with -O3, and not the default -O2

**Comment by arsenm** [comment]
Somehow an and with constant inputs reached SIFoldOperands:
  %0:sreg_32 = S_MOV_B32 32
  %15:sreg_32 = S_MOV_B32 15
  %16:sreg_32 = S_AND_B32 %0:sreg_32, killed %15:sreg_32, implicit-def $scc


The and gets constant folded and deleted, not accounting for the used implicit-def. So this can't be deleted if the physreg def is used, but also this and probably shouldn't have reached here in the first place

**Comment by jhuber6** [comment]
Yeah I had a thought that using `llvm-reduce` was going too far but I was unable to find a way to crash on anything else. This occurred in the `libc` test suite when attempting to replace the `inline_memcpy` that simply does a trivial loop with `__builtin_memcpy`.

**Comment by jhuber6** [comment]
> I have a patch for the failure. I blame the bad optimization on the expansion emitting urem x, 16 which would have been cleaned up by InstCombine if we were to run it after this point (we wouldn't). The expansion should probably try to avoid emitting this so late

Okay, I can try applying the builtin memcpy again once that lands and see if it fails somewhere earlier. Might've been something unrelated from an already broken module since it was tough to reduce.

**Comment by arsenm** [comment]
My patch is complicated by the fact that it breaks ~34 GlobalISel tests. This is mostly because GlobalISel doesn't bother setting dead flags in most situations. Additionally, we're also missing out on constant folding in RegBankSelect since it's not using CSEMIRBuilder

**Comment by arsenm** [comment]
https://reviews.llvm.org/D156526 didn't help very much with the failures, probably need to patch the generated selectors too
