### ISSUE TITLE
apt.llvm.org/llvm.sh suddenly stopped to support Ubuntu 22.04.2 Jammy

### ISSUE THREAD

**Issue by XVilka** [llvm/llvm-project#63998]
```
Run wget https://apt.llvm.org/llvm.sh -O /tmp/llvm-install.sh; chmod +x /tmp/llvm-install.sh; sudo /tmp/llvm-install.sh 15
--2023-07-21 07:[4](https://github.com/rizinorg/rizin/actions/runs/5619531219/job/15227851275#step:4:5)4:44--  https://apt.llvm.org/llvm.sh
Resolving apt.llvm.org (apt.llvm.org)... 1[5](https://github.com/rizinorg/rizin/actions/runs/5619531219/job/15227851275#step:4:6)1.101.42.49, 2a04:4e42:a::5[6](https://github.com/rizinorg/rizin/actions/runs/5619531219/job/15227851275#step:4:7)1
Connecting to apt.llvm.org (apt.llvm.org)|151.101.42.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5363 (5.2K) [application/octet-stream]
Saving to: ‘/tmp/llvm-install.sh’

     0K .....                                                 100% 12.1M=0s

2023-0[7](https://github.com/rizinorg/rizin/actions/runs/5619531219/job/15227851275#step:4:8)-21 07:44:44 (12.1 MB/s) - ‘/tmp/llvm-install.sh’ saved [5363/5363]

+ CURRENT_LLVM_STABLE=16
+ BASE_URL=http://apt.llvm.org
+ needed_binaries=(lsb_release wget add-apt-repository gpg)
+ missing_binaries=()
+ for binary in "${needed_binaries[@]}"
+ which lsb_release
+ for binary in "${needed_binaries[@]}"
+ which wget
+ for binary in "${needed_binaries[@]}"
+ which add-apt-repository
+ for binary in "${needed_binaries[@]}"
+ which gpg
+ [[ 0 -gt 0 ]]
+ LLVM_VERSION=16
+ ALL=0
++ lsb_release -is
+ DISTRO=Ubuntu
++ lsb_release -sr
+ VERSION=22.04
+ UBUNTU_CODENAME=
+ CODENAME_FROM_ARGUMENTS=
+ source /etc/os-release
++ PRETTY_NAME='Ubuntu 22.04.2 LTS'
++ NAME=Ubuntu
++ VERSION_ID=22.04
++ VERSION='22.04.2 LTS (Jammy Jellyfish)'
++ VERSION_CODENAME=jammy
++ ID=ubuntu
++ ID_LIKE=debian
++ HOME_URL=https://www.ubuntu.com/
++ SUPPORT_URL=https://help.ubuntu.com/
++ BUG_REPORT_URL=https://bugs.launchpad.net/ubuntu/
++ PRIVACY_POLICY_URL=https://www.ubuntu.com/legal/terms-and-policies/privacy-policy
++ UBUNTU_CODENAME=jammy
+ DISTRO=ubuntu
+ case ${DISTRO} in
+ [[ -n jammy ]]
+ CODENAME=jammy
+ [[ -n jammy ]]
+ LINKNAME=-jammy
+ '[' 1 -ge 1 ']'
+ '[' 1 '!=' - ']'
+ '[' 15 '!=' all ']'
+ LLVM_VERSION=15
+ OPTIND=2
+ '[' 1 -ge 2 ']'
+ getopts :hm:n: arg
+ [[ 0 -ne 0 ]]
+ declare -A LLVM_VERSION_PATTERNS
+ LLVM_VERSION_PATTERNS[[9](https://github.com/rizinorg/rizin/actions/runs/5619531219/job/15227851275#step:4:10)]=-9
+ LLVM_VERSION_PATTERNS[[10](https://github.com/rizinorg/rizin/actions/runs/5619531219/job/15227851275#step:4:11)]=-10
+ LLVM_VERSION_PATTERNS[[11](https://github.com/rizinorg/rizin/actions/runs/5619531219/job/15227851275#step:4:12)]=-11
+ LLVM_VERSION_PATTERNS[[12](https://github.com/rizinorg/rizin/actions/runs/5619531219/job/15227851275#step:4:13)]=-12
+ LLVM_VERSION_PATTERNS[[13](https://github.com/rizinorg/rizin/actions/runs/5619531219/job/15227851275#step:4:14)]=-13
+ LLVM_VERSION_PATTERNS[[14](https://github.com/rizinorg/rizin/actions/runs/5619531219/job/15227851275#step:4:15)]=-14
+ LLVM_VERSION_PATTERNS[[15](https://github.com/rizinorg/rizin/actions/runs/5619531219/job/15227851275#step:4:16)]=-15
+ LLVM_VERSION_PATTERNS[[16](https://github.com/rizinorg/rizin/actions/runs/5619531219/job/15227851275#step:4:17)]=-16
+ LLVM_VERSION_PATTERNS[17]=
+ '[' '!' _ ']'
+ LLVM_VERSION_STRING=-15
+ [[ -n jammy ]]
+ REPO_NAME='deb http://apt.llvm.org//jammy/  llvm-toolchain-jammy-15 main'
+ wget -q --method=HEAD http://apt.llvm.org/jammy
Distribution 'ubuntu' in version '[22](https://github.com/rizinorg/rizin/actions/runs/5619531219/job/15227851275#step:4:23).04.2 LTS (Jammy Jellyfish)' is not supported by this script.
+ [[ -n '' ]]
+ echo 'Distribution '\''ubuntu'\'' in version '\''22.04.2 LTS (Jammy Jellyfish)'\'' is not supported by this script.'
+ exit 2
```

**Comment by nokutu** [comment]
And when doing `apt update` I get:

```
Err:16 https://apt.llvm.org/jammy llvm-toolchain-jammy-14 Release                                                                               
  404  Not Found [IP: 199.232.194.49 443]
```

**Comment by sysuhuang** [comment]
It seems that we meet same problem, spending me the whole afternoon.


+ CURRENT_LLVM_STABLE=16
+ BASE_URL=http://apt.llvm.org
+ needed_binaries=(lsb_release wget add-apt-repository gpg)
+ missing_binaries=()
+ for binary in "${needed_binaries[@]}"
+ which lsb_release
+ for binary in "${needed_binaries[@]}"
+ which wget
+ for binary in "${needed_binaries[@]}"
+ which add-apt-repository
+ for binary in "${needed_binaries[@]}"
+ which gpg
+ [[ 0 -gt 0 ]]
+ LLVM_VERSION=16
+ ALL=0
++ lsb_release -is
+ DISTRO=Ubuntu
++ lsb_release -sr
+ VERSION=22.04
+ UBUNTU_CODENAME=
+ CODENAME_FROM_ARGUMENTS=
+ source /etc/os-release
++ PRETTY_NAME='Ubuntu 22.04.2 LTS'
++ NAME=Ubuntu
++ VERSION_ID=22.04
++ VERSION='22.04.2 LTS (Jammy Jellyfish)'
++ VERSION_CODENAME=jammy
++ ID=ubuntu
++ ID_LIKE=debian
++ HOME_URL=https://www.ubuntu.com/
++ SUPPORT_URL=https://help.ubuntu.com/
++ BUG_REPORT_URL=https://bugs.launchpad.net/ubuntu/
++ PRIVACY_POLICY_URL=https://www.ubuntu.com/legal/terms-and-policies/privacy-policy
++ UBUNTU_CODENAME=jammy
+ DISTRO=ubuntu
+ case ${DISTRO} in
+ [[ -n jammy ]]
+ CODENAME=jammy
+ [[ -n jammy ]]
+ LINKNAME=-jammy
+ '[' 1 -ge 1 ']'
+ '[' 1 '!=' - ']'
+ '[' 16 '!=' all ']'
+ LLVM_VERSION=16
+ OPTIND=2
+ '[' 1 -ge 2 ']'
+ getopts :hm:n: arg
+ [[ 0 -ne 0 ]]
+ declare -A LLVM_VERSION_PATTERNS
+ LLVM_VERSION_PATTERNS[9]=-9
+ LLVM_VERSION_PATTERNS[10]=-10
+ LLVM_VERSION_PATTERNS[11]=-11
+ LLVM_VERSION_PATTERNS[12]=-12
+ LLVM_VERSION_PATTERNS[13]=-13
+ LLVM_VERSION_PATTERNS[14]=-14
+ LLVM_VERSION_PATTERNS[15]=-15
+ LLVM_VERSION_PATTERNS[16]=-16
+ LLVM_VERSION_PATTERNS[17]=
+ '[' '!' _ ']'
+ LLVM_VERSION_STRING=-16
+ [[ -n jammy ]]
+ REPO_NAME='deb http://apt.llvm.org/jammy/  llvm-toolchain-jammy-16 main'
+ wget -q --method=HEAD http://apt.llvm.org/jammy
+ [[ -n '' ]]
+ echo 'Distribution '\''ubuntu'\'' in version '\''22.04.2 LTS (Jammy Jellyfish)'\'' is not supported by this script.'
Distribution 'ubuntu' in version '22.04.2 LTS (Jammy Jellyfish)' is not supported by this script.
+ exit 2

**Comment by glebov-andrey** [comment]
Looks like it's back up

**Comment by nunoplopes** [comment]
It's back up. thanks.

**Comment by pmor13** [comment]
@glebov-andrey @nunoplopes What does it mean "it's back up"? I have exactly the same problem (`22.04.2 LTS (Jammy Jellyfish)'\'' is not supported by this script`). How to fix it? How to install LLVM 17 (for example) on 22.04.2 LTS (Jammy Jellyfish) in 2024?

**Comment by glebov-andrey** [comment]
@pmor13 I think at the time they were doing maintenance after which it came back up. BTW it seems to work at least for jammy/16 right now.

**Comment by pmor13** [comment]
@glebov-andrey Hm, do you know whether it is possible to install LLVM 17 (for example) without rebuilding it from sources on 22.04.2 LTS (Jammy Jellyfish)? If yes, then how?

**Comment by glebov-andrey** [comment]
@pmor13 Just use apt.llvm.org - the old versions are still there - just specify the right version when adding the apt repo.

**Comment by pmor13** [comment]
@glebov-andrey Thanks for the help. I've installed LLVM 17 manually by downloading `https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz` and then by extraction of its contents via `tar xf`.
