### ISSUE TITLE
[clang-tidy]: `cppcoreguidelines-owning-memory` cannot cope with returning objects of subclasses

### ISSUE THREAD

**Issue by qqiangwu** [llvm/llvm-project#63994]
```C++
struct A {
    virtual ~A() = default;
};

struct B : public A {};

A* foo(int x)
{
    return new B;
}
```

The above code will pass clang-tidy  `cppcoreguidelines-owning-memory` check. It is caused by

![image](https://github.com/llvm/llvm-project/assets/2892107/404a863a-f1e7-45ef-bbf3-f9b27cc33706)

Adding an ignoringParenImpCasts fix the problem

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D156031
