### ISSUE TITLE
[Reassociate] Missed optimization of expression of addition

### ISSUE THREAD

**Issue by ZY546** [llvm/llvm-project#63997]
Test code: https://godbolt.org/z/3v5sbe3Ej
```c++
int test()
{
    int a,b,c,d,e,f,g;
    cin>>a>>b>>c>>d>>g;
    e=a+b+c;  
    f=d+b+c;  //can be replaced with the value at line 5
    cout<<e<<f;
    return 0;
}
```

IR at -O1:
```
  %0 = load i32, ptr %a, align 4
  %1 = load i32, ptr %b, align 4
  %2 = load i32, ptr %c, align 4
  %add = add i32 %2, %1
  %add5 = add i32 %add, %0
  %3 = load i32, ptr %d, align 4
  %add6 = add i32 %2, %1
  %add7 = add i32 %add6, %3
```

We can easily notice that `b+c` at line 6 in the test code can be replaced with the value at line 5, but the intermediate code generated by LLVM at the optimization level of O1 does not.
I noticed that under the optimization level of O1, `ReassociatePass` changed the order of addition calculation in a+b+c in an attempt to optimize, but the final generated ir only changed the order of addition calculation, whether it missed the value substitution step.
In addition, if we perform the `EarlyCSEPass` after the `ReassociatePass`, then this missed optimization can be done without changing the optimization level.

**Comment by qcolombet** [comment]
Yes, the IR is not as nice as it could be at the end of the `O1` pipeline, but I'd argue this is on purpose.

`O2` has the nicer LLVM IR at the end of the LLVM IR passes, but all in all, I don't think having the same output for O1 is worth it.
If we go down the road of making `O1` better, then we'll likely end up with `O2`.

Also, as far as I can tell, the CSE still happens during ISel, and the final assembly is the same as `O2` in this particular case.

@ZY546 what were you after when you filed this issue?
`O1` is by design missing some optimizations.

**Comment by ZY546** [comment]
In my understanding, `O2` is better than `O1` because more optimizations are done. But in fact, more execution of `EarlyCSEPass` at the end of `O1` can get better optimization effect, and `EarlyCSEPass` itself is within the optimization range of `O1`, it is only a matter of execution times. If so, perhaps this optimization is within the scope of `O1`'s responsibility?

**Comment by qcolombet** [comment]
> In my understanding, `O2` is better than `O1` because more optimizations are done. But in fact, more execution of `EarlyCSEPass` at the end of `O1` can get better optimization effect, and `EarlyCSEPass` itself is within the optimization range of `O1`, it is only a matter of execution times. If so, perhaps this optimization is within the scope of `O1`'s responsibility?

Maybe.
The documentation of the scope of O1 is rather vague.
Personally I don't think it is worth it, but if someone wants to add that, sure!

**Comment by ZY546** [comment]
> > In my understanding, `O2` is better than `O1` because more optimizations are done. But in fact, more execution of `EarlyCSEPass` at the end of `O1` can get better optimization effect, and `EarlyCSEPass` itself is within the optimization range of `O1`, it is only a matter of execution times. If so, perhaps this optimization is within the scope of `O1`'s responsibility?
> 
> Maybe. The documentation of the scope of O1 is rather vague. Personally I don't think it is worth it, but if someone wants to add that, sure!

Ok, thank you very much!

**Comment by nikic** [comment]
We certainly shouldn't change the O1 pipeline in response to fuzzer findings. If you have real-world motivation for this, we can discuss it, but as is I don't think there is value in keeping this open.
