### ISSUE TITLE
llvm.amdgcn.inverse.ballot should not be convergent

### ISSUE THREAD

**Issue by nhaehnle** [llvm/llvm-project#64015]
We missed this when we added the intrinsic. `llvm.amdgcn.inverse.ballot` is semantically really just `((arg >> lane_id) & 1) != 0`, so there is cross-lane communication.

cc @arsenm @jayfoad @OutOfCache @sameerds

**Comment by OutOfCache** [comment]
Do we only need to remove the `IntrConvergent` from the intrinsic definition or is there more to it?

**Comment by jdoerfert** [comment]
> Do we only need to remove the `IntrConvergent` from the intrinsic definition or is there more to it?

That should do it.

**Comment by nhaehnle** [comment]
There may be some tests that need updating, but yeah, everything else should be fine.

**Comment by OutOfCache** [comment]
I submitted a patch for review: https://reviews.llvm.org/D156088

**Comment by arsenm** [comment]
Patch was committed 93dc66a289b0136a468c55ac6590516ba3299375
