### ISSUE TITLE
16.0.0 KMSAN handles function param/retval shadow state incorrectly

### ISSUE THREAD

**Issue by markjdb** [llvm/llvm-project#64019]
I encountered this problem in FreeBSD's implementation of KMSAN after updating from LLVM 15 to 16, but I believe the same problem is demonstrated with the examples on godbolt below. It may apply to MSAN as well.

Consider the following function:

```
#include <sys/types.h>

void *mymemcpy(void *dst, const void *src, size_t sz)
{
    char *dstp;
    const char *srcp;
    size_t i;

    srcp = src;
    dstp = dst;
    for (i = 0; i < sz; i++)
        dstp[i] = srcp[i];
    return dst;
}
```

I would expected the generated asm to do at least two things: 1) verify that shadow state for `sz` is 0, 2) copy the shadow state for param `dst` to the retval shadow area in TLS. With 15.0.0 I can see both of these things, and with 16.0.0 (and LLVM trunk) I see neither.

LLVM 16.0.0: https://godbolt.org/z/zvc6Mb5dh
LLVM 15.0.0: https://godbolt.org/z/zxPd3aYh1

At the beginning of the function we load a pointer to the MSAN TLS state (via `__msan_get_context_state()`) and save it on the stack. LLVM 15 immediate loads the value at offset 0x10 of the TLS, which corresponds to the shadow state for `sz`, and effectively jumps to a `__msan_warning()` call if the value is non-zero, so 1) appears to be satisfied. For 2), the asm does this before returning

```
movq    -128(%rbp), %rax  # load TLS pointer
movq    -88(%rbp), %rcx # fetch saved shadow state for `dst`
movq    %rcx, 800(%rax) # 800 is the offset of retval shadow state
...
retq
```

With LLVM 16, the generated code is much shorter, but it doesn't appear to inspect the param shadow state at all, and it unconditionally sets retval shadow state to 0:

```
movq    -80(%rbp), %rax # load TLS pointer
movq    $0, 800(%rax) # 800 is the offset of retval shadow state
```

Isn't LLVM 16's behaviour simply wrong? Are some additional compiler flags needed?

**Comment by markjdb** [comment]
@vitalybuka since you've done some work on MSAN, I wonder if you could comment on the reported behaviour. I'm happy to bisect, but it would take some time and I'd like some confirmation that this is a real problem.

**Comment by vitalybuka** [comment]
That's intended behavior.
Msan will insert checks on mymemcpy caller side, so sz is always initialized, or caller will report an error.
