### ISSUE TITLE
llvm.amdgcn.endpgm should be convergent

### ISSUE THREAD

**Issue by nhaehnle** [llvm/llvm-project#64013]
As the title says: since s_endpgm is a wave-wide operation, it should really be marked `convergent`.

cc @arsenm @jayfoad

**Comment by jayfoad** [comment]
No objection, but I don't understand what effect this would have.

**Comment by jayfoad** [comment]
cc @sameerds

**Comment by ssahasra** [comment]
> No objection, but I don't understand what effect this would have, or what the exact definition of "convergent" is for things that don't return a result.

It's not really about the result. "convergent" is about whether the set of threads executing it needs to be preserved. A major chunk of that is about not changing the control dependences.

**Comment by jayfoad** [comment]
Is this a practical problem or a theoretical one? Since s_endpgm is already marked as HasSideEffects I can't imagine that the compiler would actually try to move it across non-uniform control flow.

**Comment by nhaehnle** [comment]
It is theoretical. I noticed it while skimming intrinsics definitions.

**Comment by arsenm** [comment]
> > No objection, but I don't understand what effect this would have, or what the exact definition of "convergent" is for things that don't return a result.
> 
> It's not really about the result. "convergent" is about whether the set of threads executing it needs to be preserved. A major chunk of that is about not changing the control dependences.

But the set of threads doesn't really need to be preserved. It has the same effect if any thread hits it. There's no meaningful communication between them

**Comment by nhaehnle** [comment]
> > > No objection, but I don't understand what effect this would have, or what the exact definition of "convergent" is for things that don't return a result.
> > 
> > 
> > It's not really about the result. "convergent" is about whether the set of threads executing it needs to be preserved. A major chunk of that is about not changing the control dependences.
> 
> But the set of threads doesn't really need to be preserved. It has the same effect if any thread hits it. There's no meaningful communication between them

I disagree. Consider:
```
  if (divergent_condition) {
    buffer[threadId] = 0;
  } else {
    buffer[threadId] = 1;
  }
  __builtin_endpgm();
```
Presumably we have an implicit guarantee that both assignments will execute. That means be can't hoist the endpgm into the branches like this:
```
  if (divergent_condition) {
    buffer[threadId] = 0;
  __builtin_endpgm();
  } else {
    buffer[threadId] = 1;
  __builtin_endpgm();
  }
```

**Comment by sameerds** [comment]
This is sneaky (to me, at least). I would expect that a function that has side effects should not be hoisted into a condition at all. But here it is being hoisted into both sides of the condition, so from a single-threaded point of view, the compiler is allowed to do this. Right? Perhaps in practice the compiler won't, but the "convergent" attribute will properly disallow this.
