### ISSUE TITLE
Static analyzer HTML output has incorrect links to "note" diagnostics

### ISSUE THREAD

**Issue by nicolas17** [llvm/llvm-project#64054]
When the clang static analyzer outputs HTML reports, there is a "Bug Summary" section at the top, which has in-page anchor links to the diagnostics in the source file below. When the checker generates "notes" with `BugReport.addNote`, this section has links to every note in the report.

However, these links are off by one. The first link doesn't work, the second link points at the first note, the third link points at the second note, etc.

To reproduce:
```cpp
struct A {
  int *iptr;
  int a;
  int b;
  int *c;
  int *d;

  A (int *iptr) : iptr(iptr) {}
};

void f() {
  A a(0);
}
```
```
clang --analyze --analyzer-output html -Xanalyzer -analyzer-checker=optin.cplusplus.UninitializedObject test-notes.cpp
```

The output HTML has links to `#EndPath`, `#Note0`, `#Note1`, `#Note2`, `#Note3` (generated by `HTMLDiagnostics::FinalizeHTML`), but the notes themselves have `id="Note1"`, `id="Note2"`, `id="Note3"`, `id="Note4"` (generated by `RewriteFile` and `HandlePiece`).

It looks like `FinalizeHTML` generates the links in incremental order from 0, but `RewriteFile` is iterating over the notes in *reverse* order and starts at n (not n-1).

**Comment by nicolas17** [comment]
Now I see that path-sensitive diagnostic elements start at `id="Path1"`, so probably note IDs should also start at 1. Maybe:
```diff
diff --git a/clang/lib/StaticAnalyzer/Core/HTMLDiagnostics.cpp b/clang/lib/StaticAnalyzer/Core/HTMLDiagnostics.cpp
index 0fe0c93dc016..f91a51cc5f8f 100644
--- a/clang/lib/StaticAnalyzer/Core/HTMLDiagnostics.cpp
+++ b/clang/lib/StaticAnalyzer/Core/HTMLDiagnostics.cpp
@@ -592,11 +592,11 @@ void HTMLDiagnostics::FinalizeHTML(const PathDiagnostic& D, Rewriter &R,
             P->getLocation().asLocation().getExpansionLineNumber();
         int ColumnNumber =
             P->getLocation().asLocation().getExpansionColumnNumber();
+        ++NumExtraPieces;
         os << "<tr><td class=\"rowname\">Note:</td><td>"
            << "<a href=\"#Note" << NumExtraPieces << "\">line "
            << LineNumber << ", column " << ColumnNumber << "</a><br />"
            << P->getString() << "</td></tr>";
-        ++NumExtraPieces;
       }
     }
 
```

**Comment by gruuprasad** [comment]
@EugeneZelenko @nicolas17 I would like to fix this. Please assign this to me.
