### ISSUE TITLE
[libc++] std::assume_aligned should diagnose insufficiently aligned pointers during constant evaluation

### ISSUE THREAD

**Issue by philnik777** [llvm/llvm-project#64078]
Clang allows `__builtin_assume_aligned` to be used inside a constant expression. So while we can't return the pointer returned from `__builtin_assume_aligned`, we can still call it to diagnose insufficiently aligned pointers during constant evaluation. https://godbolt.org/z/GPGjrGM9K

**Comment by jiahzhang** [comment]
Hi, I'd like to work on this if it hasn't been taken yet. This is my first LLVM/compilers task (aside from basic stuff I did in grad school) so do you recommend somewhere in the codebase I could start with looking at?

**Comment by philnik777** [comment]
> Hi, I'd like to work on this if it hasn't been taken yet. This is my first LLVM/compilers task (aside from basic stuff I did in grad school) so do you recommend somewhere in the codebase I could start with looking at?

This isn't really a compiler task in case your are after one of those. This is purely a libc++ improvement. If you want to take a shot anyways, you can look at the implementation in `libcxx/include/__memory/assume_aligned.h`.

**Comment by jiahzhang** [comment]
> > Hi, I'd like to work on this if it hasn't been taken yet. This is my first LLVM/compilers task (aside from basic stuff I did in grad school) so do you recommend somewhere in the codebase I could start with looking at?
> 
> This isn't really a compiler task in case your are after one of those. This is purely a libc++ improvement. If you want to take a shot anyways, you can look at the implementation in `libcxx/include/__memory/assume_aligned.h`.

Yeah that's fine, I'm mainly interested in getting more familiar with the codebase for now.

**Comment by jiahzhang** [comment]
Do you know what's an acceptable timeline to work on an issue? Had some things come up IRL so might not get to this until a week later.

**Comment by mordante** [comment]
Thanks for working on this!
This is not urgent so feel free to take your time.

**Comment by jiahzhang** [comment]
Sorry, could you un-assign me? At this point, I'm so busy with other things I don't know when I'll have time to work on this issue. Unfortunate situation, but if someone else wants to work on it, I don't want to hold them up.

**Comment by philnik777** [comment]
> Hi, I'd like to work on this! I'm new to llvm and would like to familiarise myself with the codebase so I can provide further contributions along the line? Is this a good way to get started with it?

Sure, it's a way to start. LLVM is big, so depending on what you want to do this could be a good fit.

**Comment by Rajveer100** [comment]
@philnik777 
Could you briefly describe the issue in a comprehensive manner to be sure to what exactly we are dealing here with?

Presuming this is the function definition:

```C++
void * __builtin_assume_aligned (const void *exp, size_t align, ...)
```

From what I have understood, this is used as an `assumption` (not sure about its `strictness`) suggesting that `align` bytes are aligned for the `exp`, although this returns a `void*`, which means we would have to type `cast` it (as you did in the `godbolt`).

Essentially you want the appropriate `diagnosis` to occur for `misaligned` cases, considering we have sufficient information (`void*`?) without actually having the returned `pointer`?

**Comment by philnik777** [comment]
You can't cast the pointer back before C++23: https://godbolt.org/z/zKK6an97K, so we can't simply implement `assume_aligned` as
```c++
template <size_t N, class T>
constexpr T* assume_aligned(T* ptr) {
  return static_cast<T*>(__builtin_assume_alinged(ptr, N));
}
```
But nothing prevents us from calling `__builtin_assume_aligned` and then discard the return value to still get diagnostics during constant evaluation in case the pointer is underaligned.

**Comment by Rajveer100** [comment]
You mean to say, this issue aims to `improve` the existing diagnostic to cover older versions (<C++23), which it currently doesn't?

**Comment by Rajveer100** [comment]
@philnik777 
> But nothing prevents us from calling __builtin_assume_aligned and then discard the return value to still get diagnostics during constant evaluation in case the pointer is underaligned.

If we `discard` the `return value`, we would want to change the `return type` of this function as well right, or do you mean to return something else like a temporary value, since `casting` pointer isn't possible in older versions of C++, also what `minimum version` are we targeting here to support, currently what I see in the `#if` block is `>= 20`?
