### ISSUE TITLE
tlbilxlpid -> error: invalid instruction

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#64080]
via https://lore.kernel.org/llvm/202307211945.TSPcyOhh-lkp@intel.com/

it looks like:

```c
void foo(void) {
    asm volatile("tlbilxlpid");
}
```
produces:
```
<source>:2:18: error: invalid instruction
    asm volatile("tlbilxlpid");
                 ^
<inline asm>:1:2: note: instantiated into assembly here
        tlbilxlpid
        ^~~~~~~~~~
```
for `--target=powerpc-linux-gnu`.  I wonder if clang is missing support for this instruction (or perhaps it's an alias to something that clang does understand).

cc @nemanjai @nemanja-ibm

**Comment by MaskRay** [comment]
It looks like `tlbilxlpid` is an alias for `tlbilx 0, 0, 0`, which is present in Power ISA v2.07, but not in Power ISA v3.x.

**Comment by nemanjai** [comment]
Yes, the PowerISA has removed the Book E as of v3.0. @nickdesaulniers can you comment on where this is coming from? We don't have this implemented but if it is needed, we can go ahead with https://reviews.llvm.org/D156204.

**Comment by ecnelises** [comment]
Landed as https://github.com/llvm/llvm-project/commit/53648ac1d0c953ae6d008864dd2eddb437a92468

Should we backport it to 17.x?

**Comment by nickdesaulniers** [comment]
Yes, please. We can work around this in the kernel using `.inst` assembler directives for older versions of clang, but having it sooner would allow us to drop the workaround sooner.

**Comment by nickdesaulniers** [comment]
oh no, is `.inst` aarch64-only? :(

**Comment by nickdesaulniers** [comment]
Thanks @ecnelises !
