### ISSUE TITLE
clang-cl: error: unable to make temporary file: no such file or directory,and there are no error-related messages or hints？Why?

### ISSUE THREAD

**Issue by LuWei6896** [llvm/llvm-project#64096]
Clang 9.0， OS:win32
Stack dump:
0.      Program arguments: ../../third_party/llvm-build/Release+Asserts/bin\clang-cl.exe -cc1 -triple i386-pc-windows-msvc19.11.0 -emit-obj -mincremental-linker-compatible -disable-free -disable-llvm-verifier -discard-value-names -main-file-name audio_dtln.cc -mrelocation-model static -mthread-model posix -fmerge-all-constants -mdisable-fp-elim -relaxed-aliasing -fmath-errno -masm-verbose -mconstructor-aliases -target-cpu pentium4 -mllvm -x86-asm-syntax=intel -D_MT -D_DLL --dependent-lib=msvcrt --dependent-lib=oldnames --show-includes -stack-protector 2 -fms-volatile -fdiagnostics-format msvc -cfguard -dwarf-column-info -momit-leaf-frame-pointer -ffunction-sections -fdata-sections -coverage-notes-file D:\audio-videos-rpo\repositories\push_webrtc\webrtc_vrv_win\src\out\Release\audio_dtln.gcno -nostdsysteminc -resource-dir ../../third_party/llvm-build/Release+Asserts\lib\clang\9.0.0 -D USE_AURA=1 -D NO_TCMALLOC -D FULL_SAFE_BROWSING -D SAFE_BROWSING_CSD -D SAFE_BROWSING_DB_LOCAL -D CHROMIUM_BUILD -D CR_CLANG_REVISION="361212-67510fac-3" -D _HAS_NODISCARD -D _HAS_EXCEPTIONS=0 -D __STD_C -D _CRT_RAND_S -D _CRT_SECURE_NO_DEPRECATE -D _SCL_SECURE_NO_DEPRECATE -D _ATL_NO_OPENGL -D _WINDOWS -D CERT_CHAIN_PARA_HAS_EXTRA_FIELDS -D PSAPI_VERSION=2 -D WIN32 -D _SECURE_ATL -D _USING_V110_SDK71_ -D WINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -D WIN32_LEAN_AND_MEAN -D NOMINMAX -D _UNICODE -D UNICODE -D NTDDI_VERSION=NTDDI_WIN10_RS2 -D _WIN32_WINNT=0x0A00 -D WINVER=0x0A00 -D NDEBUG -D NVALGRIND -D DYNAMIC_ANNOTATIONS_ENABLED=0 -D WEBRTC_ENABLE_PROTOBUF=1 -D WEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE -D RTC_ENABLE_VP9 -D HAVE_SCTP -D WEBRTC_USE_H264 -D WEBRTC_LIBRARY_IMPL -D WEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -D WEBRTC_WIN -D ABSL_ALLOCATOR_NOTHROW=1 -I ../.. -I gen -I ../../third_party/mylibs/mylibs/eigen3 -I ../../third_party/mylibs/mylibs/onnxruntime/include -I ../../third_party/abseil-cpp -D __DATE__= -D __TIME__= -D __TIMESTAMP__= -internal-isystem ../../third_party/llvm-build/Release+Asserts\lib\clang\9.0.0\include -internal-isystem C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\ATLMFC\include -internal-isystem C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include -internal-isystem C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -internal-isystem C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -internal-isystem C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -internal-isystem C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -internal-isystem C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -Os -Wno-builtin-macro-redefined -WCL4 -Wimplicit-fallthrough -Wthread-safety -Wextra-semi -Wno-unused-parameter -Wno-deprecated-declarations -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-ignored-pragma-optimize -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -Wglobal-constructors -Wc++11-narrowing -Wimplicit-fallthrough -Wthread-safety -Winconsistent-missing-override -Wundef -Wno-invalid-offsetof -Wunused-lambda-capture -fdeprecated-macro -fdebug-compilation-dir D:\audio-videos-rpo\repositories\push_webrtc\webrtc_vrv_win\src\out\Release -ferror-limit 39 -fmessage-length 0 -fno-use-cxa-atexit -fms-extensions -fms-compatibility -fms-compatibility-version=19.11 -std=c++14 -fdelayed-template-parsing -finline-functions -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -fcxx-exceptions -v -ftime-trace -mllvm -instcombine-lower-dbg-declare=0 -o obj/modules/audio_processing/audio_processing_c/audio_dtln.obj -x c++ ../../modules/audio_processing/vrv_disnoise/audio_dtln.cc -fcomplete-member-pointers -faddrsig
1.      <eof> parser at end of file
2.      Per-file LLVM IR generation
 #0 0x00007ff625d2e0cc (D:\audio-videos-rpo\repositories\push_webrtc\webrtc_vrv_win\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0xc8e0cc)
 #1 0x00007ff626273caf (D:\audio-videos-rpo\repositories\push_webrtc\webrtc_vrv_win\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x11d3caf)
 #2 0x00007ff62626bf51 (D:\audio-videos-rpo\repositories\push_webrtc\webrtc_vrv_win\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x11cbf51)
 #3 0x00007ff6277f8155 (D:\audio-videos-rpo\repositories\push_webrtc\webrtc_vrv_win\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x2758155)
 #4 0x00007ff6277f63da (D:\audio-videos-rpo\repositories\push_webrtc\webrtc_vrv_win\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x27563da)
 #5 0x00007ff6266e924c (D:\audio-videos-rpo\repositories\push_webrtc\webrtc_vrv_win\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x164924c)
 #6 0x00007ff626c03943 (D:\audio-videos-rpo\repositories\push_webrtc\webrtc_vrv_win\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1b63943)
 #7 0x00007ff62669e8ae (D:\audio-videos-rpo\repositories\push_webrtc\webrtc_vrv_win\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x15fe8ae)
 #8 0x00007ff62668a9f7 (D:\audio-videos-rpo\repositories\push_webrtc\webrtc_vrv_win\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x15ea9f7)
 #9 0x00007ff626710b89 (D:\audio-videos-rpo\repositories\push_webrtc\webrtc_vrv_win\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1670b89)
#10 0x00007ff6250a6b32 (D:\audio-videos-rpo\repositories\push_webrtc\webrtc_vrv_win\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x6b32)
#11 0x00007ff6250a3fca (D:\audio-videos-rpo\repositories\push_webrtc\webrtc_vrv_win\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x3fca)
#12 0x00007ff627840ea0 (D:\audio-videos-rpo\repositories\push_webrtc\webrtc_vrv_win\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x27a0ea0)
#13 0x00007ffeb83884d4 (C:\Windows\System32\KERNEL32.DLL+0x84d4)
#14 0x00007ffeb87b1791 (C:\Windows\SYSTEM32\ntdll.dll+0x51791)
clang-cl: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 9.0.0 (trunk 357692)
Target: i386-pc-windows-msvc
Thread model: posix
InstalledDir: ../../third_party/llvm-build/Release+Asserts/bin
clang-cl: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-cl: error: unable to make temporary file: no such file or directory
clang-cl: note: diagnostic msg: Error generating preprocessed source(s).
[93/2767] CXX obj/modules/audio_processing/aec/aec_core/aec_core.obj
ninja: build stopped: subcommand failed

**Comment by efriedma-quic** [comment]
Questions are usually better directed to https://discourse.llvm.org

"No such file or directory" is a translation of the C ENOENT; when the code tried to create the file in your temporary directory, it failed.  Probably you've done something weird to your "TMP" environment variable.  (See https://github.com/llvm/llvm-project/blob/b530eeea5e7697d58af2adac66c8b86c79e649bb/llvm/lib/Support/Windows/Path.inc#L1469C6-L1469C27 for the code that computes your temp directory.)
