### ISSUE TITLE
Adding a custom attribute called 'fragile function'

### ISSUE THREAD

**Issue by M-S-Raghavendra** [llvm/llvm-project#64110]
Consider the following data as input:

struct FragileCluster {
   llvm::DebugLoc start;
   llvm::DebugLoc end;
};

struct FragileCluster[] = { ... };
Create a custom LLVM attribute, named IsFragile.

Iterate over each control flow graph in the program, comparing the basic block source locations against the above input. If the location of any basic block overlaps with any of the source ranges provided in the above input, mark the associated function (i.e. the function containing the basic block) with the above custom attribute.
Display all functions that are marked with the custom attribute IsFragile in a formatted table. Include the full signature of the function in the display, including the parameter names, types and the return type. Also display the size of the function (in number of lines of code) and the name of the source file that contains the function definition.

**Comment by Endilll** [comment]
What's the use case for this? Checking for ABI breaks?

**Comment by M-S-Raghavendra** [comment]
Issue is resolved
