### ISSUE TITLE
[Flang][Application=BigDFT] Error in Fortran parsing/preprocessor when compiling with OpenMP enabled

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#64128]
A parse/preprocessor error was observed while compiling Fortran code containing an include directive in a subroutine.

**Source**
`ab.f90`
```f90
subroutine simple()
  implicit none
  !$ include 'inc.f90'
end subroutine simple
```
`inc.f90`
```f90
print *, "Hello"
```

**Error**
```console
flang-new  ab.f90  -fopenmp
error: Could not parse ab.f90
./ab.f90:3:14: error: expected '('
    !$ include 'inc.f90'
               ^
./ab.f90:3:6: in the context: statement function definition
    !$ include 'inc.f90'
       ^
./ab.f90:3:6: in the context: declaration construct
    !$ include 'inc.f90'
       ^
./ab.f90:2:3: in the context: specification part
    implicit none
    ^
./ab.f90:1:1: in the context: SUBROUTINE subprogram
  subroutine simple()
  ^
```

Note: This was observed while compiling BigDFT (https://bigdft.org/?i=1, https://gitlab.com/l_sim/bigdft-suite/-/blame/devel/futile/dicts/callbacks.f90#L71)

**Comment by klausler** [comment]
I suspect that this is a standard Fortran INCLUDE line that has been commented out, but with an added `$` that is tricking the prescanner into retaining the comment as a directive.  Which shouldn't happen; the prescanner should ignore any "directive" that doesn't start with a registered sentinel ("dir", "acc", &c.).

**Comment by klausler** [comment]
Fix is in test; if you need it this week, let me know and I'll expedite it.

**Comment by kiranchandramohan** [comment]
Thanks @klausler. This is not urgent.

**Comment by klausler** [comment]
https://reviews.llvm.org/D156759
