### ISSUE TITLE
[OpenMP] Unused external variables are emitted when declared on the target

### ISSUE THREAD

**Issue by jhuber6** [llvm/llvm-project#64133]
The following code snippet will cause the external variable `a` to be emitted in the IR even though it is not used. See also the godbolt link, https://godbolt.org/z/M5MsrnbnM.
```c
extern int a;
#pragma omp declare target to(a) device_type(host)

int main() { return 0; }
```
The standard semantics maintain that unused extern variables will not be emitted. This is important for linking as linking in a static library that defines `a` will be extracted even though it's unused.

**Comment by h-vetinari** [comment]
I think this issue needs to be reopened an then use the `/cherry-pick` syntax for https://github.com/llvm/llvm-project/commit/141c4e7a9403fed46d84c7f0429295bd28c89368

**Comment by EugeneZelenko** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/141c4e7a9403fed46d84c7f0429295bd28c89368
