### ISSUE TITLE
Backport 48feef277a24b1b9c0ff33267a91e70d9584012e to LLVM 17 release branch.

### ISSUE THREAD

**Issue by cjacek** [llvm/llvm-project#64131]
/cherry-pick 48feef277a24b1b9c0ff33267a91e70d9584012e

**Comment by DavidSpickett** [comment]
I've confirmed that this fixes failures seen on Linaro's Windows on Arm lldb bot on `main` recently.

Before: https://lab.llvm.org/buildbot/#/builders/219/builds/4408
After: https://lab.llvm.org/buildbot/#/builders/219/builds/4409
