### ISSUE TITLE
Lamdba body SFINAE in requires-expression

### ISSUE THREAD

**Issue by ecatmur** [llvm/llvm-project#64138]
Per CWG 2672 https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2672 it is intended that substitution failure within the body of a lambda inside a requires-expression is a hard error:

```c++
template <class T>
  void f(T) requires requires { []() { T::invalid; } (); };
void f(...);
int main() { f(0); } // should be ill-formed, similarly to http://eel.is/c++draft/temp.deduct.general#example-7
```

clang accepts the above calling `f(...)`; gcc rejects. IMO it would be better to follow gcc here and also reject, even if that is not the normative wording.

**Comment by shafik** [comment]
It seems from the discussion on [2023/02/13902](https://lists.isocpp.org/core/2023/02/13902.php) that folks agree. 

So I will confirm this bug.

@zygoloid any comments on the best way to fix this?

**Comment by zygoloid** [comment]
See `Sema::isSFINAEContext()`, where we're currently careful to only treat lambdas as being outside the immediate context within explicit and deduced template argument substitution. Instead, they should always be non-immediate context, so:

```diff
-    SawLambdaSubstitution = true;
+    return std::nullopt;
```

... plus removing the dead code.
