### ISSUE TITLE
[clang-format] version 17 trips up on templated base class uniform initialization.

### ISSUE THREAD

**Issue by joeatodd** [llvm/llvm-project#64134]
Running `clang-format test.cpp` (i.e. default style rules) with version 17 on the following reproducer:

``` c++
template <int Dim>
struct Base{};

template <int Dim>
struct Derived : public Base<Dim>{

  Derived() : Base<Dim>{} {
    // Derived ctor impl
  }
};
```
produces:

``` c++
template <int Dim> struct Base {};

template <int Dim> struct Derived : public Base<Dim> {

  Derived() : Base<Dim> {}
  {
    // Derived ctor impl
  }
};
```
 but it ought to produce:

``` c++
template <int Dim> struct Base {};

template <int Dim> struct Derived : public Base<Dim> {

  Derived() : Base<Dim>{} {
    // Derived ctor impl
  }
};
```
Version 16 produces this correct output.

I played around with this reproducer a little. I think its the combination of the `<Dim>` template argument and the `{}` uniform initialization of the derived class which is confusing `clang-format`. Removing the former or replacing the latter with `()` produces expected output.

Both the versions mentioned here are from the downstream DPC++ project:
Working: `clang-format version 17.0.0 (https://github.com/intel/llvm.git 21ca00fb1cc5408b2428e3c386aa5137ed551fdb)`
Broken: `clang-format version 16.0.0 (https://github.com/intel/llvm.git 751acf357ed192a2f9de5171ccdf4a69510cff37)`

**Comment by rymiel** [comment]
I've bisected this to 6dcde658b2380d7ca1451ea5d1099af3e294ea16

**Comment by galenelias** [comment]
I've submitted a fix for review here: https://reviews.llvm.org/D156705

Sorry for the regression!

**Comment by tru** [comment]
/cherry-pick 0a6c271

@owenca for next time - you need to specify the sha or multiple sha's with the command.

**Comment by owenca** [comment]
> /cherry-pick 0a6c271
> 
> @owenca for next time - you need to specify the sha or multiple sha's with the command.

Oops! Thanks for pointing out. Fixed above.
