### ISSUE TITLE
[OpenMP][Docs] `make docs-openmp-html` Fails 

### ISSUE THREAD

**Issue by AntonRydahl** [llvm/llvm-project#64168]
I have been trying to improve the OpenMP documentation and found that it was not possible to build the OpenMP documentation with Sphinx due to syntax errors in `openmp/docs/design/Runtimes.rst`. However, I have fixed the syntax errors in the following patch https://reviews.llvm.org/D156470.

**Comment by jhuber6** [comment]
Thanks for looking into this. I think there's warnings as well that I never got around to fixing, I think the default is for warnings as errors so those need to be cleaned up.

**Comment by AntonRydahl** [comment]
Oh, are there more errors in the OpenMP documentation? I could fix them as well.

**Comment by AntonRydahl** [comment]
[This commit](https://github.com/llvm/llvm-project/commit/b880552dc1aef33402d084f07f6bf93b6a0b08e0) fixed the issue. 😄
