### ISSUE TITLE
[clang][ASTImporter] Decls within declcontext not in lexical order

### ISSUE THREAD

**Issue by danix800** [llvm/llvm-project#64165]
Revision https://reviews.llvm.org/D154764 is still not complete. An extra reordering is needed for lexical order of all imported decls within a record. The final algorithm could be summarized as the following:

1. Import all fields that'll be part of the layout;
1. Sort these fields to ensure correct layout;
1. Import everything else;
1. Final re-ordering by lexical order.

**Comment by EugeneZelenko** [comment]
@danix800: Could you please elaborate?

**Comment by danix800** [comment]
See https://reviews.llvm.org/D156093.

I expected more comments on this but no one actually cared so I decided to close it.
