### ISSUE TITLE
hexagon-unknown-linux-musl: library paths ignored

### ISSUE THREAD

**Issue by androm3da** [llvm/llvm-project#64175]
`clang` will ignore library paths specified by `-L` when using `hexagon-unknown-linux-musl`.

        $ ./bin/clang --target=hexagon-unknown-linux-musl  -o tprog tprog.o -L/tmp -###
        ...
        clang: warning: argument unused during compilation: '-L/tmp' [-Wunused-command-line-argument]
         "/local/mnt/workspace/install/clang-latest/bin/ld.lld" "-z" "relro" "-o" "tprog" "-dynamic-linker=/lib/ld-musl-hexagon.so.1" "/usr/lib/crt1.o" "-L/usr/lib" "tprog.o" "-lclang_rt.builtins-hexagon" "-lc"

**Comment by androm3da** [comment]
@kparzysz-quic can you approve cherry-picking the fix for this bug in 96832a6bf7e0e7f1e8d634d38c44a1b32d512923 to `release/17.x`?

**Comment by kparzysz-quic** [comment]
Approved.
