### ISSUE TITLE
Experimental constexpr interpreter drops notes

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#64195]
I noticed a new surprise that can be reproduced here: https://godbolt.org/z/KaWGbx9M5

Basically, given this code and passing -Wvla:
```
void vla(bool b) {
  static_assert(!noexcept(static_cast<int(*)[b ? throw : 42]>(0)), "");
}
```
in the current interpreter, this would issue notes about why this is a VLA, but the new interpreter doesn't emit those notes.

**Comment by tbaederr** [comment]
This has been fixed in the meantime, as the godbolt link above shows.
