### ISSUE TITLE
clang-tidy segfaults on bugprone-unchecked-optional-access - observable from llvmorg-16.x.x to current main

### ISSUE THREAD

**Issue by combinatorylogic** [llvm/llvm-project#64201]
Code to reproduce (as `clang-tidy test.cpp`):

```C++
#include <optional>

auto computeSomeStuff(double arg1) -> double;

class C1 {
  void estimateWhatever() const;
};

struct S1 {
  double a;
  double b;
};
  
auto C1::estimateWhatever() const -> void {
  for (int i = 0; i<1; i++) {
    std::optional<std::pair<S1, int>> result{};
    /*
      Do something forgetful.
     */
    auto& [cTf, errorcore] = *result;
    cTf.b = computeSomeStuff(cTf.a);
  }
}
```

With the following in `.clang-tidy`:

```
Checks: '
                        bugprone-*
        '
```

Cause of segfault:

attempt to cast `ScalarStorageLocation` to `AggregateStorageLocation`.

Proposed fix:

test if `Loc->getKind() != StorageLocation::Kind::Aggregate` and just return nullptr if so.

[clang-bug-aggregatestoragelocation.tar.gz](https://github.com/llvm/llvm-project/files/12195811/clang-bug-aggregatestoragelocation.tar.gz)

**Comment by 5chmidti** [comment]
It looks like this was fixed, see: https://godbolt.org/z/1froEWxzc (added missing `<tuple>` include).
