### ISSUE TITLE
Backport AIX codegen fix that affects thinLTO on AIX.

### ISSUE THREAD

**Issue by w2yehia** [llvm/llvm-project#64214]
/cherry-pick https://github.com/llvm/llvm-project/commit/9d4e8c09f493280acc7637d904bdc84abc11fdc3

Fixes a thinLTO SPEC2017 failure. Affects on AIX codegen only.

**Comment by tru** [comment]
@MaskRay @daltenty  should this be backported to the release branch?

**Comment by daltenty** [comment]
> @MaskRay @daltenty should this be backported to the release branch?

I think so, without this fix some programs using thinLTO will run into link failures when using LLVM17 on AIX.
