### ISSUE TITLE
release/17.x: Fix LLVM_VERSION_SUFFIX 

### ISSUE THREAD

**Issue by h-vetinari** [llvm/llvm-project#64225]
At least llvm still sets the `git` suffix; previous rc's had removed that, c.f.
https://github.com/llvm/llvm-project/blob/llvmorg-16.0.0-rc1/llvm/CMakeLists.txt#L27-L29
https://github.com/llvm/llvm-project/blob/llvmorg-15.0.0-rc1/llvm/CMakeLists.txt#L27-L29
https://github.com/llvm/llvm-project/blob/llvmorg-14.0.0-rc1/llvm/CMakeLists.txt#L22-L24

AFAICT, it should just be removed as soon as the branch is created, c.f. https://github.com/llvm/llvm-project/commit/0604154e006e88e9e7f82d8ee5fd076bda206613

CC @tru

**Comment by tru** [comment]
Obviously a miss from my side. I will fix for rc2 and add to the checklist since I missed it!

**Comment by tru** [comment]
Fixed in the release branch. Thanks for noticing!

**Comment by h-vetinari** [comment]
@tru, I see that you now set this to `-rc1` instead of removing it completely (as was done previously). That would be OK I guess if it actually matched the rc version, but now rc2 still has `-rc1` in there.

My preference would be to remove the suffix completely in the release branch (less work for you too), because that suffix will show up in all kinds of versioned artefacts, and I need to be able to control that for our packaging (which is intentionally very nitpicky about version separation). The easiest is if it's not there anymore at all, but if that's off the table, then perhaps consider `rc` without a number. Barring that, the number there must match the tag, otherwise it's broken.

PS. The `git` suffix on `main` does not have a hyphen. It's perhaps better to leave out the hyphen for `rc` (or `rcX`) as well than introduce a new pattern.

**Comment by h-vetinari** [comment]
I can open a new issue, but I'd prefer if this one could be reopened please. :)

**Comment by h-vetinari** [comment]
Thanks a lot @EugeneZelenko 🙏 

PS. It's incredible how on top of things you are on the issue tracker, huge thanks for that!

**Comment by h-vetinari** [comment]
@tru, not sure if this bubbled through your mailbox full of notifications. Do we really need the `-rcX` prefix? More details in the comment further up.

**Comment by tru** [comment]
Hi! Yeah the situation is definitely worse because I messed it up twice. This hasn't been a problem before, but maybe a good solution is to just call it `rc` as you suggest. I think that's probably good enough?

**Comment by tru** [comment]
I think you mean suffix :) But yeah maybe it's overkill. Let's do it like this for now, thanks for the suggestion!
