### ISSUE TITLE
[Clang] Wrong help text for `--offload-host-device` flag

### ISSUE THREAD

**Issue by AntonRydahl** [llvm/llvm-project#64243]
I have been making an overview of offloading related flags, and I stumbled upon the help text for `--offload-host-device`. I am pretty sure that the help text is wrong. It says
```bash
$ clang --help
  --offload-host-device   Only compile for the offloading host.
```
, but at the same time the flag `--offload-host-device` is an alias of `--cuda-compile-host-device` as far as I can see from `clang/include/clang/Driver/Options.td:2883`:
```C++
def cuda_compile_host_device : Flag<["--"], "cuda-compile-host-device">, Alias<offload_host_device>,
  HelpText<"Compile CUDA code for both host and device (default). Has no "
  "effect on non-CUDA compilations.">;
```
May I correct the help text to `Compile the code for both host and device` or something like that?

**Comment by danix800** [comment]
Good catch! It's `host` + `device` obviously.

**Comment by AntonRydahl** [comment]
Thanks! I have prepared a patch on Phabricator: [https://reviews.llvm.org/D156641](https://reviews.llvm.org/D156641)
