### ISSUE TITLE
Clang MIPS: float register constraints for inline asm deviate from gcc

### ISSUE THREAD

**Issue by shravanrn** [llvm/llvm-project#64241]
clang and gcc seem to have different behavior of floating point constraints for inline asm targetting MIPS. Consider this simple example

```c
// gcc compiles this but clang does not
void read_float(float* p) {
    float result = *p;
    __asm__("" ::"r"(result));
}
```
The following code compiles fine on gcc when targeting MIPS, but clang gives a compile error `couldn't allocate input reg for constraint 'r'`

Clang requires the register constraint here to be `"f"` not `"r"`. However applying an `"f"` constraint, causes gcc to fail compilation with the error `error: impossible constraint in 'asm'` while clang compiles the code fine. 

```c
// clang compiles this but gcc does not
void read_float(float* p) {
    float result = *p;
    __asm__("" ::"f"(result));
}
```

Here is a simple demo of the issue: https://godbolt.org/z/WGWxd3ejo
Test with "mips gcc 13.1.0" and "mips clang 16.0.0"

(This bug was discovered as part of the wasm2c project https://github.com/WebAssembly/wabt/issues/2266)

**Comment by pinskia** [comment]
Note the `f` constraint works with GCC if enable hard float (that is `-mhard-float` option). I think the godbolt's mips gcc defaults to soft-float (`--with-float=soft` on the configure line).

**Comment by brad0** [comment]
cc @wzssyqa

**Comment by wzssyqa** [comment]
Should we consider it as a bug of gcc or clang ;)
I think that we should support "f" for soft float, and map it to "r".

**Comment by pinskia** [comment]
> Should we consider it as a bug of gcc or clang ;) I think that we should support "f" for soft float, and map it to "r".
It is not a bug in either, just the default configure options for GCC vs clang on godbolt.  GCC defaults to soft-float while clang defaults to hard float.

Note with -msoft-float on clang, it is rejected too. Though there is an internal compiler error and that is definitely a bug.

**Comment by wzssyqa** [comment]
Ohh, I know.  Let me have a try.

**Comment by wzssyqa** [comment]
This PR fixes half of this problem: no-ICE if f is used for soft-float.

We also need to support r for soft-float.

**Comment by wzssyqa** [comment]
https://github.com/llvm/llvm-project/pull/79116

can solve the whole of problem now.
