### ISSUE TITLE
Typo in ocaml binding?

### ISSUE THREAD

**Issue by KihongHeo** [llvm/llvm-project#64254]
Hi, 

It seems that `LLVMDITypeGetLine` should be `LLVMDITypeGetFlags`?

https://github.com/llvm/llvm-project/blob/c1c86f9eae73786bcdacddaab248817c4f176935/llvm/bindings/ocaml/debuginfo/debuginfo_ocaml.c#L839-L842

**Comment by nikic** [comment]
cc @alan-j-hu

**Comment by alan-j-hu** [comment]
https://reviews.llvm.org/D157812

**Comment by alan-j-hu** [comment]
Do you want this to be backported onto the LLVM 17 branch? It looks like the bug has existed since LLVM 15.
