### ISSUE TITLE
llvm 17.0.0-rc1: building flang fails with missing HLFIR .h.inc files

### ISSUE THREAD

**Issue by martin-frbg** [llvm/llvm-project#64268]
Trying to build RC1 on Ubuntu 22 with `cmake -S llvm -B build -G "Unix Makefiles" -DLLVM_ENABLE_PROJECTS="clang;flang;openmp;lld" -DCMAKE_BUILD_TYPE=Release , the build fails when it reaches flang/lib/Optimizer/HLFIR , as several .h.inc files are missing from flang/include/flang/Optimizer/HLFIR/ - at leastHLFIREnums.h.inc , HLFIRDialects.h.inc and HLFIRTypes.h.inc. Providing empty files for each allows the build to proceed to the next such error - I assume these are supposed to be generated somewhere but have found no indication of this actually being attempted.

**Comment by clementval** [comment]
These are tablegen generated file.

**Comment by martin-frbg** [comment]
Anything I can do to track this down ? When I crawl down into the build/flang/.../HFLIR folder and execute `make` there, or alternatively run `make -f tools/flang/include/flang/Optimizer/HFLIR/CMakeFiles/HFLIROPSIncGen.dir/build.make` from the build directory it claims there is nothing to be done (and I do not see tablegen featuring in the respective files either). Other parts of the build tree had their .h.inc files created correctly, including various files starting with `FIR` in tools/flang/include/flang/Optimizer/Dialect, and Passes.h.inc in flang/Optimizer/Transforms

**Comment by clementval** [comment]
Do you have a more complete error? It mainly depends which file including `HLFIRDialect.h` triggers this. It might be a missing dependency somewhere.

**Comment by martin-frbg** [comment]
Well, the visible effect is just files like flang/lib/Optimizer/Transforms/SimplifyIntrinsics.cpp failing to compile as they use a header (like HLFIRDialect.h in this case) that wants to include one of those unavailable .h.inc files.

I (only) see HLFIROpsIncgen listed under DEPENDS in flang/lib/Optimizer/Support/CMakeLists.txt

**Comment by clementval** [comment]
Can you try adding `HLFIROpsIncGen` in the `DEPENDS` section of `flang/lib/Optimizer/Transforms/CMakeLists.txt`? It should solve the issue.

**Comment by martin-frbg** [comment]
Thanks, this appears to have helped the build to progress further, though it now terminates with a different error elsewhere in the flang subtree - claiming "hlfirDialect is not a member of hlfir" when processing line 31 of InitFIR.h (in function void fir::support::registerNonCodegenDialects(mlir::DialectRegistry&) for flang/lib/Optimizer/Support/InitFIR.cpp that wants to include it. (But this is from an attempt to continue the broken build - maybe I need to throw away the build subtree and start over - which may take a few hours on this VM, and it is close to midnight locally so I may not be able to report results until some 6 to 8 hours later)

**Comment by clementval** [comment]
Yeah you might want to have a fresh build. I'll submit a patch for the first problem.

**Comment by clementval** [comment]
https://reviews.llvm.org/D156751

**Comment by martin-frbg** [comment]
Thanks, new build is currently at 9 percent so will take some time before I can provide an update

**Comment by martin-frbg** [comment]
Unfortunately that new error about wrong class definitions in InitFIR.h prevails with a clean build - should I continue here, or create a new ticket ? Relevant tail of build log attached, starts with
```
In file included from /home/lan/llvm-project-llvmorg-17.0.0-rc1/flang/lib/Optimizer/Support/InitFIR.cpp:9:
/home/lan/llvm-project-llvmorg-17.0.0-rc1/flang/include/flang/Optimizer/Support/InitFIR.h: In function ‘void fir::support::registerNonCodegenDialects(mlir::DialectRegistry&)’:
/home/lan/llvm-project-llvmorg-17.0.0-rc1/flang/include/flang/Optimizer/Support/InitFIR.h:31:54: error: ‘hlfirDialect’ is not a member of ‘hlfir’
   31 |   mlir::affine::AffineDialect, FIROpsDialect, hlfir::hlfirDialect,             \
      |                                                      ^~~~~~~~~~~~
/home/lan/llvm-project-llvmorg-17.0.0-rc1/flang/include/flang/Optimizer/Support/InitFIR.h:31:54: note: in definition of macro ‘FLANG_NONCODEGEN_DIALECT_LIST’

```
[builderror_issue64268.txt](https://github.com/llvm/llvm-project/files/12226409/builderror_issue64268.txt)

**Comment by clementval** [comment]
Unfortunately I cannot reproduce this. Can you share your configuration (compiler version / cmake flags) and your output?

**Comment by martin-frbg** [comment]
gcc 11.4, binutils 2.38, cmake options as in the initial message - `cmake -S llvm -B build -G "Unix Makefiles" -DLLVM_ENABLE_PROJECTS="clang;flang;openmp;lld" -DCMAKE_BUILD_TYPE=Release`

**Comment by clementval** [comment]
Can you share the output of your build?

**Comment by martin-frbg** [comment]
Sorry, output as in - what ? Full build log (I already posted the part with the error messages, but would need to redo the build to capture all messages), tarball of everything under "build", contents of InitFIR.h (but IIRC it is static, not generated, and does not include any of the .h.inc files generated at build time) ?

**Comment by clementval** [comment]
The console output of your build (build log). There are missing pieces in what you posted so it is hard to know where your problem shows up.

**Comment by clementval** [comment]
I'm just trying to help and a more complete log would be helpful.

**Comment by clementval** [comment]
`flang/lib/Optimizer/Support/CMakeLists.txt` has `HLFIROpsIncGen` as a dependency so there should be something else.

**Comment by martin-frbg** [comment]
Here's the output of cmake's configure step, in case that is good for anything - 
[cmakelog.txt](https://github.com/llvm/llvm-project/files/12232888/cmakelog.txt)
The full build (saving the console output this time) is going to take several hours again.

**Comment by martin-frbg** [comment]
The VM crashed overnight, so no progress yet. But might well be an unrelated hardware or operating system issue...

**Comment by martin-frbg** [comment]
repeated the build after fixing the vm configuration - the build problem persists
[buildlog_issue64268.txt](https://github.com/llvm/llvm-project/files/12244417/buildlog_issue64268.txt)
I'm also test-building on another, non-virtualized machine (though that one only has gcc 9.3 at present), but that build will take at least another hour to get to the flang part.

**Comment by clementval** [comment]
What do you have in `./tools/flang/include/flang/Optimizer/HLFIR/HLFIRDialect.h.inc`?

**Comment by martin-frbg** [comment]
[HLFIRDialect.h.inc.txt](https://github.com/llvm/llvm-project/files/12244936/HLFIRDialect.h.inc.txt)

**Comment by clementval** [comment]
This looks perfectly fine and `hlfirDialect` is indeed in `hlfir`. Are you building with multiple worker (make -j)?

**Comment by martin-frbg** [comment]
Not sure what `cmake --build` defaults to, but the vm has two cores assigned to it, so probably yes. And te vm appens to have llvm-16.0.0 installed, so I can try that next

**Comment by clementval** [comment]
This kind of problems are hard to track unless we can reproduce them. You can also try with the same command than specified here: https://github.com/llvm/llvm-project/blob/main/flang/docs/GettingStarted.md or see how we build various configuration with our buildbots here - https://lab.llvm.org/buildbot/#/builders?tags=%2Bflang

**Comment by martin-frbg** [comment]
btw restarting the build after the error exit does not help, so it is unlikely to be caused by one `make` subprocess trying to use a file that the other has not yet created

**Comment by martin-frbg** [comment]
Hmm. The build on the other machine has now progressed beyond the (seemingly) problematic file, despite using identical sources. So probably something to do with the vm, unstable clock source or whatever, or a bug in its gcc. I'll let the clang build run overnight, but it is looking like a very specific (if elusive) local installation problem rather than a defect in the RC now.

**Comment by clementval** [comment]
Thanks for trying. At least we found one missing dependency so far.

**Comment by martin-frbg** [comment]
So the vm appears to be cursed - the build with clang16 failed on the same file, claiming there was no member named hlfirDialect in namespace hlfir. The md5 checksums of all generated .h.inc files under tools/flang/include/flang/Optimizer/HLFIR match those of the successful build on the other computer. A `make -j 1` at this point is unable to recover (and I note this is still gmake 4.3, not 4.4 with its more aggressive parallelization). 
Guess at this point it is best to nail the .vdi to the wall and close this issue ?

**Comment by clementval** [comment]
Yeah that would be hard to figure out what is going on since we cannot reproduce that on another machine. Please close the issue if the initial problem is addressed and feel free to open a new one if something else comes.

**Comment by martin-frbg** [comment]
Problem persists with RC2 as the patch apparently has not made it to the release/17.x branch yet

**Comment by h-vetinari** [comment]
@martin-frbg, could you reopen this issue? Then it can be used for tracking the backport

**Comment by martin-frbg** [comment]
Can do, was unsure about the customs of this project (and was asked to close if the problem was addressed)

**Comment by h-vetinari** [comment]
@clementval @EugeneZelenko
Could someone set the milestone please? :)
