### ISSUE TITLE
backport dcb28244faa88cb566a852533790bcac75daaa0ft 

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#64260]
/cherry-pick https://github.com/llvm/llvm-project/commit/dcb28244faa88cb566a852533790bcac75daaa0f

This fixes a issue where clangd doesn't respect IWYU keep/export pragma for standard headers.

**Comment by firewave** [comment]
@hokein You need to set the `LLVM 17.0.X Release` milestone for this ticket.

**Comment by EugeneZelenko** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/dcb28244faa88cb566a852533790bcac75daaa0f
