### ISSUE TITLE
backport 171868dc2cd60c6e3eaeb3861b18ba0e22461291 to LLVM17

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#64261]
/cherry-pick https://github.com/llvm/llvm-project/commit/171868dc2cd60c6e3eaeb3861b18ba0e22461291

This fixes some unused-include false positives for std::range symbols

**Comment by firewave** [comment]
@hokein You need to set the `LLVM 17.0.X Release` milestone for this ticket.

**Comment by EugeneZelenko** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/171868dc2cd60c6e3eaeb3861b18ba0e22461291
