### ISSUE TITLE
lldb python wrapper fails to build in windows release packaging: Assertion failed: Getattr(n, "sym:name"), file Modules/lang.cxx, line 1657

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#64279]
LLDB is failing to build in Windows release packaging for llvm-17.0.0-rc1, see see https://discourse.llvm.org/t/llvm-17-0-0-rc1-tagged/72404/3

To reproduce, in a VS 2019 cmd prompt, at `llvmorg-18-init`:

```
cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="lldb;clang" ../llvm && ninja lldb
...
[705/4571] Building LLDB Python wrapper
FAILED: tools/lldb/bindings/python/LLDBWrapPython.cpp tools/lldb/bindings/python/lldb.py
cmd.exe /C "cd /D C:\src\llvm-project\build.bar\tools\lldb\bindings\python && C:\src\swigwin-3.0.8\swig.exe -c++ -w361,362 -features autodoc -IC:/src/llvm-project/lldb/include -IC:/src/llvm-project/lldb/bindings -IC:/src/llvm-project/lldb/bindings/python -c++ -threads -python -py3 -outdir C:/src/llvm-project/build.bar/tools/lldb/bindings/python -o C:/src/llvm-project/build.bar/tools/lldb/bindings/python/LLDBWrapPython.cpp C:/src/llvm-project/lldb/bindings/python/python.swig"
C:\src\llvm-project\lldb\include\lldb\API\SBCommandReturnObject.h(119) : Warning 509: Overloaded method lldb::SBCommandReturnObject::PutCString(char const *) effectively ignored,
C:\src\llvm-project\lldb\include\lldb\API\SBCommandReturnObject.h(119) : Warning 509: as it is shadowed by lldb::SBCommandReturnObject::PutCString(char const *,int).
Assertion failed: Getattr(n, "sym:name"), file Modules/lang.cxx, line 1657
```

The same command succeeds at `llvmorg-17-init`.

**Comment by zmodem** [comment]
Bisection points to 662548c82683bd8657a3179afee693c4965a3dfd "[lldb] Replace SB swig interfaces with API headers"

**Comment by bulbazord** [comment]
> Bisection points to [662548c](https://github.com/llvm/llvm-project/commit/662548c82683bd8657a3179afee693c4965a3dfd) "[lldb] Replace SB swig interfaces with API headers"

I authored this commit on February 16th, 2023. It's unfortunate that it's still causing issues to this day, but I suppose that's life. Unfortunately I don't have access to a windows machine to be able to reproduce this myself. But it looks like the actual tool that is asserting here is `swig`, as `Modules/lang.cxx` is definitely a part of that project. LLDB itself disallows swig versions `3.0.9` and `3.0.10` from being used, it's possible that `3.0.8` has similar issues that we're unaware of. One recommendation I have is to try building with a newer version of swig. I would recommend 4.0 or newer if possible.

**Comment by zmodem** [comment]
That's for the quick reply! Upgrading to Swig 4.1.1 seems to have made it work. I'll update the comment in the build script.

**Comment by JDevlieghere** [comment]
> Maybe we should have check for the Swig version in the CMake scripts?

We do, but our current minimum requirement is 3. I created a patch to bump it to 4: https://reviews.llvm.org/D156804
