### ISSUE TITLE
clang option -export-dynamic parse to -e xport-dynamic error

### ISSUE THREAD

**Issue by hstk30** [llvm/llvm-project#64297]
https://godbolt.org/z/jsTch9cqq

Compile command `clang -export-dynamic test.c` simply, but have a warning :

```
clang: warning: argument unused during compilation: '-e xport-dynamic' [-Wunused-command-line-argument]
```

It seem clang split option `-export-dynamic` into `-e     xport-dynamic`. 
It's dangerous if  `-e   xport-dynamic`  is sent to `ld`, because of `-e`  means 

```
-e ADDRESS, --entry ADDRESS Set start address
```

I don't think it's reasonable to split option `-export-dynamic` into `-e     xport-dynamic`.

I can't find the code that split the option, if someone knows , just tell me.

**Comment by tbaederr** [comment]
See also: https://github.com/llvm/llvm-project/issues/58347

**Comment by EugeneZelenko** [comment]
@hstk30: Could you please elaborate?
