### ISSUE TITLE
Sending files from Linux lldb to Windows lldb-server doesn't work

### ISSUE THREAD

**Issue by yshui** [llvm/llvm-project#64313]
The server replies with a `F-1,16`, and `lldb` reacts with reporting "error: invalid argument".

This is because lldb-server uses `_wsopen_s` to open files on Windows. `_wsopen_s` rejects `mode` arguments that contain anything other than `_S_IREAD | _S_IWRITE`.

**Comment by DavidSpickett** [comment]
Thanks for the report and the diagnosis. Can you show how to reproduce this? It's probably very simple but just so we're on the same page. Also if you have links to the docs for `_wsopen_s` that would be great.

Though Linux -> Windows is not something we test on the buildbots we'd be happy to fix this if it's pretty obviously wrong which it sounds like it is.

**Comment by DavidSpickett** [comment]
Patch by @yshui https://reviews.llvm.org/D156817.

**Comment by mstorsjo** [comment]
I guess this should be trivial enough to cherry-pick.

/cherry-pick 9a4b3fdb82327e808213070fd157be3c557b8b9d
