### ISSUE TITLE
[flang] [OpenMP] Compilation Error (from NPB 3.4.2-MZ-OMP)

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#64344]
I observed compilation errors when building NPB 3.4.2-MZ-OMP with flang-new. Here is the minimal reproducer:
```console
$ cat mz.f90
module mz_data

   integer t_last
   parameter (t_last = 15)

end module mz_data

program test

   use mz_data

   integer i
   double precision tsum(t_last), trecs(t_last), tming(t_last), tmaxg(t_last)

   do i=1, t_last
      !$omp atomic
      tsum(i) = tsum(i) + trecs(i)
      !$omp atomic
      tming(i) = min(tming(i), trecs(i))
      !$omp atomic
      tmaxg(i) = max(tmaxg(i), trecs(i))
   end do

end program
```

Gfortran:
```console
$ gfortran -fopenmp -Wall -Wextra mz.f90
$
```

Flang:
```console
$ flang-new -fopenmp mz.f90
error: Semantic errors in mz.f90
./mz.f90:19:18: error: Atomic update variable 'tming(i)' not found in the argument list of intrinsic procedure
        tming(i) = min(tming(i), trecs(i))
                   ^^^^^^^^^^^^^^^^^^^^^^^
./mz.f90:21:18: error: Atomic update variable 'tmaxg(i)' not found in the argument list of intrinsic procedure
        tmaxg(i) = max(tmaxg(i), trecs(i))
                   ^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by kawashima-fj** [comment]
The minimal reproducer is:

```fortran
subroutine foo()
    integer :: x(1), y
    !$omp atomic update
    x(1) = max(x(1), y)
end
```

```console
$ flang-new -fopenmp test.f90                                                                                                                                                                                                                                        
error: Semantic errors in test.f90
./test.f90:4:12: error: Atomic update variable 'x(1)' not found in the argument list of intrinsic procedure
      x(1) = max(x(1), y)
             ^^^^^^^^^^^^
```

If you replace the array subobject `x(1)` with a normal scalar variable `x`, it can be compiled (at least to FIR).

```fortran
subroutine foo()
    integer :: x, y
    !$omp atomic update
    x = max(x, y)
end
```

According to OpenMP 5.2 spec:

4.3.1.3 OpenMP Atomic Structured Blocks

> An *update-atomic* structured block is *update-statement*, an update statement that has one of the following forms:
> *x* = *x* *operator* *expr*
> *x* = *expr* *operator* *x*
> *x* = *intrinsic-procedure-name* (*x*, *expr-list*)
> *x* = *intrinsic-procedure-name* (*expr-list*, *x*)

> *x*, *v*, *d* and *e* (as applicable) are scalar variables of intrinsic type.

> *expr-list* is a comma-separated, non-empty list of scalar expressions.

> *intrinsic-procedure-name* is one of `MAX`, `MIN`, `IAND`, `IOR`, or `IEOR`.

1.2.6 Data Terminology

> **scalar variable**  
> For C/C++, a scalar variable, as defined by the base language.  
> For Fortran, a scalar variable with intrinsic type, as defined by the base language, excluding character type.

According to Fortran 2018 spec:

3 Terms and definitions

> **scalar**  
> data entity that can be represented by a single value of the type and that is not an array (9.5)

> **variable**
> data entity that can be defined and redefined during execution of a program

I don't know an array subobject `x(1)` is a *scalar variable* or not.

FWIW, using an *operator* instead of an intrinsic results in "not yet implemented".

```fortran
subroutine foo()
    integer :: x(1), y
    !$omp atomic update
    x(1) = x(1) + y
end
```

```console
$ flang-new -fopenmp test3.f90
error: loc("/home/user/test3.f90":1:1): /home/user/src/llvm-main/flang/lib/Lower/OpenMP.cpp:2333: not yet implemented: Array references as atomic update variable
LLVM ERROR: aborting
```

**Comment by k-arrows** [comment]
I will close this issue because compiling the original NPB3.4.2-MZ-OMP source code now results in the following TODO message:
```txt
flang/lib/Lower/DirectivesCommon.h:217: not yet implemented: Array references as atomic update variable
```
