### ISSUE TITLE
clang 16.0.1: Following program crashes dumping core on Ubuntu 18.04/Linux 4.15 (and on Wandbox.com)

### ISSUE THREAD

**Issue by shankarswamy** [llvm/llvm-project#64348]
```
#include <iostream>

int main([[maybe_unused]] int argc, [[maybe_unused]] char* argv[]) {

    int i = 100, &r = i;

    std::cout << r << std::endl;
       
    return 0;
}
```

// wandbox.com permalink: https://wandbox.org/permlink/VJraWzOGw3HAZXPr

**Comment by DimitryAndric** [comment]
Looks like something is wrong with your runtime environment, as the program runs completely fine for me. I tried on a recent version of FreeBSD, and a recent version of Ubuntu.

An indication that something is not well with the Wandbox environment is the message:

```
prog.cc:4:5: warning: stack frame size (72057594037927928) exceeds limit (4294967295) in 'main' [-Wframe-larger-than]
```

Since 72057594037927928 is hex 0xfffffffffffff8, it looks a lot like there is some uninitialized memory in the version of clang hosted on Wandbox? Which version of clang are they using, and how do they build it?

**Comment by shankarswamy** [comment]
I used the following script - this is the stock script I have for building clang - as far as I can recall I did not make changes to it; it was a while ago; (I welcome improvements to the script you may have - in case you do):
```
touch ../buildTimes.txt
echo "cmake times: " >> ../buildTimes.txt && echo "" >> ../buildTimes.txt
date >> ../buildTimes.txt && echo "" >> ../buildTimes.txt
cmake -DLLVM_ENABLE_PROJECTS="clang;libcxx;libcxxabi" \
   -DCMAKE_INSTALL_PREFIX=/opt/llvmclang/clang9.0.1 \
   -DLLVM_PARALLEL_LINK_JOBS=1 \
   -DCMAKE_BUILD_TYPE=Release \
   -DCMAKE_C_COMPILER=clang \
   -DCMAKE_CXX_COMPILER=clang++ \
   -DLLVM_ENABLE_FFI=ON \
   -DBUILD_SHARED_LIBS=ON \
   -DLLVM_ENABLE_RTTI=ON \
   -DLLVM_TARGETS_TO_BUILD="host" \
   -DLLVM_BUILD_TESTS=ON \
   -G "Unix Makefiles" \
   ../llvm
echo "" >> ../buildTimes.txt
echo "compile times: " >> ../buildTimes.txt && echo "" >> ../buildTimes.txt
date >> ../buildTimes.txt && make && date >> ../buildTimes.txt
echo "" >> ../buildTimes.txt
echo >> "make check-cxx times:" >> ../buildTimes.txt && echo "" >> ../buildTimes.txt
date >> ../buildTimes.txt && make check-cxx && date >> ../buildTimes.txt
echo "" >> ../buildTimes.txt
echo "make check-clang time: " >> ../buildTimes.txt && echo "" >> ../buildTimes.txt
time >> ../buildTimes.txt && make check-clang && time >> ../buildTimes.txt
echo "" >> ../buildTimes.txt

make check-clang
sudo make install
make check-cxx
sudo make install-cxx install-cxxabi
```
I don not know how they do it over at wandbox. I get the same with my Ubuntu system; but it runs fine on 14.0.6 on my system as well as on wandbox.com.  **The problem is with 16.0.1 only**, both at Wandbox and on our systems.

**Comment by shankarswamy** [comment]
@DimitryAndric seems correct.  We installed latest updates to Ubuntu system and rebuilt clang.  The issue seems to have resolved itself.

Thank you @DimitryAndric, for your quick attention.

We are closing the issue from our end.
