### ISSUE TITLE
-Wconversions warnings in libc code

### ISSUE THREAD

**Issue by frobtech** [llvm/llvm-project#64358]
https://reviews.llvm.org/D156630 enables `-Wconversion -Wno-sign-conversion` for compiling libc code. This today results in quite a few new warnings.  There are a few common patterns with the Linux syscall wrapper functions and errno propagation where some helper inlines to handle those patterns are probably worthwhile. In other places just explicit `static_cast<...>` should be used to express the explicit intent to shorten, but in some of those places the shortening might not actually be intended and the warnings are pointing to real changes that should be made. 

A couple of the cases are in math code that Tue should probably look at.

**Comment by michaelrj-google** [comment]
The first patch to fix this has landed, I'll work on the floating point warnings next.

**Comment by michaelrj-google** [comment]
This patch fixes the remaining warnings (https://reviews.llvm.org/D157449), your patch should be safe to land now.
