### ISSUE TITLE
`assert` inside OpenMPTarget region leads to link errors

### ISSUE THREAD

**Issue by rgayatri23** [llvm/llvm-project#64360]
Using `assert` inside a `target` region gave me the following link errors:

Compiler version - 18 (last night's build)
Hardware - NVIDIA A100

```shell
ptxas /tmp/ft_example_vector-95448c.s, line 3411; error   : Type of argument does not match formal parameter '__assert_fail_param_2'
ptxas /tmp/ft_example_vector-95448c.s, line 3411; error   : Alignment of argument does not match formal parameter '__assert_fail_param_2'
ptxas /tmp/ft_example_vector-95448c.s, line 3411; error   : Type of argument does not match formal parameter '__assert_fail_param_3'
ptxas /tmp/ft_example_vector-95448c.s, line 3411; error   : Alignment of argument does not match formal parameter '__assert_fail_param_3'
ptxas /tmp/ft_example_vector-95448c.s, line 3411; error   : Call has wrong number of parameters
ptxas /tmp/ft_example_vector-95448c.s, line 3441; error   : Type of argument does not match formal parameter '__assert_fail_param_2'
ptxas /tmp/ft_example_vector-95448c.s, line 3441; error   : Alignment of argument does not match formal parameter '__assert_fail_param_2'
ptxas /tmp/ft_example_vector-95448c.s, line 3441; error   : Type of argument does not match formal parameter '__assert_fail_param_3'
ptxas /tmp/ft_example_vector-95448c.s, line 3441; error   : Alignment of argument does not match formal parameter '__assert_fail_param_3'
ptxas /tmp/ft_example_vector-95448c.s, line 3441; error   : Call has wrong number of parameters
ptxas /tmp/ft_example_vector-95448c.s, line 5015; error   : Type of argument does not match formal parameter '__assert_fail_param_2'
ptxas /tmp/ft_example_vector-95448c.s, line 5015; error   : Alignment of argument does not match formal parameter '__assert_fail_param_2'
ptxas /tmp/ft_example_vector-95448c.s, line 5015; error   : Type of argument does not match formal parameter '__assert_fail_param_3'
ptxas /tmp/ft_example_vector-95448c.s, line 5015; error   : Alignment of argument does not match formal parameter '__assert_fail_param_3'
ptxas /tmp/ft_example_vector-95448c.s, line 5015; error   : Call has wrong number of parameters
ptxas fatal   : Ptx assembly aborted due to errors
clang++: error: ptxas command failed with exit code 255 (use -v to see invocation)
clang version 18.0.0 (https://github.com/llvm/llvm-project.git de7fa3ab9a4ed05e7e4ef05b0919db52383969c5)
```

**Comment by jhuber6** [comment]
Could you provide a simple reproducer? When I check a simple example I see the call to `__assert_fail` we expect the assert macro to expand to https://godbolt.org/z/xfjee5rbe.

**Comment by rgayatri23** [comment]
This is what I get when I run the same code on A100

```shell
rgayatri@perlmutter:login40:/pscratch/sd/r/rgayatri/clang> /usr/bin/cat test-assert.c
#include <stdio.h>
#include <assert.h>
#include <omp.h>

int main() {
    int x = 1;
    #pragma omp target
    { assert(x); }
}

rgayatri@perlmutter:login40:/pscratch/sd/r/rgayatri/clang> clang test-assert.c -fopenmp -fopenmp-targets=nvptx64 -o test-assert.ex                    
ptxas /tmp/test-assert-bd5b3d.s, line 180; error   : Type of argument does not match formal parameter '__assert_fail_param_2'
ptxas /tmp/test-assert-bd5b3d.s, line 180; error   : Alignment of argument does not match formal parameter '__assert_fail_param_2'
ptxas /tmp/test-assert-bd5b3d.s, line 180; error   : Type of argument does not match formal parameter '__assert_fail_param_3'
ptxas /tmp/test-assert-bd5b3d.s, line 180; error   : Alignment of argument does not match formal parameter '__assert_fail_param_3'
ptxas /tmp/test-assert-bd5b3d.s, line 180; error   : Call has wrong number of parameters
ptxas fatal   : Ptx assembly aborted due to errors
clang: error: ptxas command failed with exit code 255 (use -v to see invocation)
clang version 17.0.0 (https://github.com/llvm/llvm-project.git fcf0d0ba9c051ea7042490147148f67f0ea9a1b3)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /global/common/software/nersc/pe/llvm/17/bin
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/test-assert-0d5598.c
clang: note: diagnostic msg: /tmp/test-assert-343ed1.c
clang: note: diagnostic msg: /tmp/test-assert-0d5598.sh
clang: note: diagnostic msg:

********************
```

**Comment by rgayatri23** [comment]
> This is what I get when I run the same code on A100
> 
> ```shell
> rgayatri@perlmutter:login40:/pscratch/sd/r/rgayatri/clang> /usr/bin/cat test-assert.c
> #include <stdio.h>
> #include <assert.h>
> #include <omp.h>
> 
> int main() {
>     int x = 1;
>     #pragma omp target
>     { assert(x); }
> }
> 
> rgayatri@perlmutter:login40:/pscratch/sd/r/rgayatri/clang> clang test-assert.c -fopenmp -fopenmp-targets=nvptx64 -o test-assert.ex                    
> ptxas /tmp/test-assert-bd5b3d.s, line 180; error   : Type of argument does not match formal parameter '__assert_fail_param_2'
> ptxas /tmp/test-assert-bd5b3d.s, line 180; error   : Alignment of argument does not match formal parameter '__assert_fail_param_2'
> ptxas /tmp/test-assert-bd5b3d.s, line 180; error   : Type of argument does not match formal parameter '__assert_fail_param_3'
> ptxas /tmp/test-assert-bd5b3d.s, line 180; error   : Alignment of argument does not match formal parameter '__assert_fail_param_3'
> ptxas /tmp/test-assert-bd5b3d.s, line 180; error   : Call has wrong number of parameters
> ptxas fatal   : Ptx assembly aborted due to errors
> clang: error: ptxas command failed with exit code 255 (use -v to see invocation)
> clang version 17.0.0 (https://github.com/llvm/llvm-project.git fcf0d0ba9c051ea7042490147148f67f0ea9a1b3)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> InstalledDir: /global/common/software/nersc/pe/llvm/17/bin
> clang: note: diagnostic msg:
> ********************
> 
> PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
> Preprocessed source(s) and associated run script(s) are located at:
> clang: note: diagnostic msg: /tmp/test-assert-0d5598.c
> clang: note: diagnostic msg: /tmp/test-assert-343ed1.c
> clang: note: diagnostic msg: /tmp/test-assert-0d5598.sh
> clang: note: diagnostic msg:
> 
> ********************
> ```

I can reproduce the same error with the current thunk from yesterday.

**Comment by jdoerfert** [comment]
I think I broke this. Will check tomorrow.
