### ISSUE TITLE
Fail to compile a requires-clause for a class method, which checks invocation of another method of the same class.

### ISSUE THREAD

**Issue by andrewerf** [llvm/llvm-project#64373]
Here is the SO post related to this issue: https://stackoverflow.com/q/76820396/8254899

The issue occurs when compiling the following code:
```cpp
#include <type_traits>
#include <ranges>
#include <vector>

struct MyClass
{
    void g( int ) {}
    void g( char ) {}

    template <std::ranges::input_range Rng>
        requires requires ( MyClass cls, const std::ranges::range_value_t<Rng>& val )
        {
            { cls.g( val ) };
        }
    void f( Rng&& rng ) {}
};

int main()
{
    MyClass cls;
    cls.g( 10 );
    cls.g( 'a' );
    cls.f( std::vector<int>{ 10, 15 } );
}
```
Clang does not compile this program, although other compilers (MSVC and GCC) work as expected. Here is the error produced by Clang:
```
<source>:13:18: error: member access into incomplete type 'MyClass'
   13 |             { cls.g( val ) };
      |                  ^
<source>:5:8: note: definition of 'MyClass' is not complete until the closing '}'
    5 | struct MyClass
      |        ^
<source>:23:9: error: no matching member function for call to 'f'
   23 |     cls.f( std::vector<int>{ 10, 15 } );
      |     ~~~~^
<source>:15:10: note: candidate template ignored: constraints not satisfied [with Rng = std::vector<int>]
   15 |     void f( Rng&& rng ) {}
      |          ^
<source>:11:18: note: because substituted constraint expression is ill-formed: constraint depends on a previously diagnosed expression
   11 |         requires requires ( MyClass cls, const std::ranges::range_value_t<Rng>& val )
      |                  ^
2 errors generated.
Compiler returned: 1
```

So basically, Clang demands a type in requires-clause to be complete. Moreover, if we change our example slightly, so that `MyClass::f` is never called:
```cpp
#include <type_traits>
#include <ranges>
#include <vector>

struct MyClass
{
    void g( int ) {}
    void g( char ) {}

    template <std::ranges::input_range Rng>
        requires requires ( MyClass cls, const std::ranges::range_value_t<Rng>& val )
        {
            { cls.g( val ) };
        }
    void f( Rng&& rng ) {}
};

int main()
{
    MyClass cls;
    cls.g( 10 );
    cls.g( 'a' );
    //cls.f( std::vector<int>{ 10, 15 } );
}
```
clang would anyway complain about incompleteness and fail compilation!
```
<source>:13:18: error: member access into incomplete type 'MyClass'
   13 |             { cls.g( val ) };
      |                  ^
<source>:5:8: note: definition of 'MyClass' is not complete until the closing '}'
    5 | struct MyClass
      |        ^
1 error generated.
Compiler returned: 1
```

The last code snippet is available in Godbolt for the ease of reproduction: https://godbolt.org/z/f7G5PxfKv.

**Expected behavior**: compilation is consistent with other compilers, both programs are accepted.
**Actual behavior**: clang fails to compile both programs.

**Comment by shafik** [comment]
@zygoloid I think this is another case where clang eagerly evaluates but I am not sure.

**Comment by zygoloid** [comment]
This case looks ill-formed to me. Code in requires-clauses and requires-expressions still has to satisfy the usual rules for dependent code appearing in a template -- we're not allowed to substitute eagerly into code in requires-clauses, but we're still allowed, and expected, to check them in the same way as we would for code appearing in any other templated context. In particular this code runs afoul of https://eel.is/c++draft/temp.res#general-6.7; see our general commentary on that here: https://clang.llvm.org/compatibility.html#undep_incomplete.

Generally, this kind of issue can be avoided by passing the incomplete class as a template parameter, for example by defining a named constraint:

```c++
template<typename Rng, typename Cls> concept C =
    std::ranges::input_range<Rng> &&
    requires ( Cls cls, const std::ranges::range_value_t<Rng>& val ) {
        { cls.g( val ) };
    };

struct MyClass
{
    void g( int ) {}
    void g( char ) {}

    template <C<MyClass> Rng>
    void f( Rng&& rng ) {}
};
```

... or via a default template argument:

```c++
    template <std::ranges::input_range Rng, typename Cls = MyClass>
        requires requires ( Cls cls, const std::ranges::range_value_t<Rng>& val )
        {
            { cls.g( val ) };
        }
    void f( Rng&& rng ) {}
```

**Comment by andrewerf** [comment]
Thanks for the reply!
Unfortunately, I think I do not really get at which point a term becomes _dependent_ in your argument.

According to https://eel.is/c++draft/temp.res#temp.dep.expr-1 in general, and https://eel.is/c++draft/temp.res#general-example-2 in particular, `cls.g( val )` seem dependent to me, since it contains a dependent term `val`.
Example 2 from the link above:
```cpp
void f(char);

template<class T> void g(T t) {
  f(1);             // f(char)
  f(T(1));          // dependent
  f(t);             // dependent
  dd++;             // not dependent; error: declaration for dd not found
}
```

**Comment by zygoloid** [comment]
Yes, `cls.g(val)` is dependent. But that doesn't matter -- `cls.g` is ill-formed in that position because the type of `cls` is incomplete. Because the expression is invalid in a way that doesn't depend on a template parameter, compilers are permitted to reject it.
