### ISSUE TITLE
Can Kaleidscope `ForExpr` handle more than two statements?

### ISSUE THREAD

**Issue by ouliuquan** [llvm/llvm-project#64381]
```
extern putchard(char);
def printstar(n)
  for i = 1, i < n, 1.0 in
    putchard(4);
    putchard(5);

# print 100 '*' characters
printstar(3);
```
If it have more than two statements, should it add more judgments, so that it can complete the processing at one time?
Code in line[5. Kaleidoscope: Extending the Language: Control Flow]( https://github.com/llvm/llvm-project/blob/c7cacb2f6efe07fa4a1129bb7e2389312670b84a/llvm/examples/Kaleidoscope/Chapter5/toy.cpp#L403)

**Comment by NoumanAmir657** [comment]
In chapter 6, you can user defined variables which let you have more than one statement in the for-loop. In chapter 5, it only allows one line in the for-loop.

**Comment by ouliuquan** [comment]
> 

Thank you for you help, I will close the issue soon.
@NoumanAmir657  And may I ask you for more question about the Kaleidscope? That question has bothered me for a long time without an answer, and I have been struggling to find an answer. https://github.com/llvm/llvm-project/issues/63651
