### ISSUE TITLE
compiler-rt: sanitizers do not intercept __isoc23_* functions added in Glibc-2.38

### ISSUE THREAD

**Issue by xry111** [llvm/llvm-project#64388]
This causes various test failures on systems using Glibc-2.38:

Failed Tests (15):

	    AddressSanitizer-Unit :: ./Asan-x86_64-calls-Dynamic-Test/AddressSanitizer/AtoiAndFriendsOOBTest
	    AddressSanitizer-Unit :: ./Asan-x86_64-calls-Dynamic-Test/AddressSanitizer/StrtolOOBTest
	    AddressSanitizer-Unit :: ./Asan-x86_64-calls-Dynamic-Test/AddressSanitizer/StrtollOOBTest
	    AddressSanitizer-Unit :: ./Asan-x86_64-calls-Test/AddressSanitizer/AtoiAndFriendsOOBTest
	    AddressSanitizer-Unit :: ./Asan-x86_64-calls-Test/AddressSanitizer/StrtolOOBTest
	    AddressSanitizer-Unit :: ./Asan-x86_64-calls-Test/AddressSanitizer/StrtollOOBTest
	    AddressSanitizer-Unit :: ./Asan-x86_64-inline-Dynamic-Test/AddressSanitizer/AtoiAndFriendsOOBTest
	    AddressSanitizer-Unit :: ./Asan-x86_64-inline-Dynamic-Test/AddressSanitizer/StrtolOOBTest
	    AddressSanitizer-Unit :: ./Asan-x86_64-inline-Dynamic-Test/AddressSanitizer/StrtollOOBTest
	    AddressSanitizer-Unit :: ./Asan-x86_64-inline-Test/AddressSanitizer/AtoiAndFriendsOOBTest
	    AddressSanitizer-Unit :: ./Asan-x86_64-inline-Test/AddressSanitizer/StrtolOOBTest
	    AddressSanitizer-Unit :: ./Asan-x86_64-inline-Test/AddressSanitizer/StrtollOOBTest
	    AddressSanitizer-x86_64-linux :: TestCases/Linux/interception_malloc_test.cpp
	    AddressSanitizer-x86_64-linux-dynamic :: TestCases/Linux/interception_malloc_test.cpp
	    MemorySanitizer-X86_64 :: scanf-allocate.cpp

**Comment by thesamesam** [comment]
See also https://github.com/llvm/llvm-project/issues/64946.

**Comment by MaskRay** [comment]
Patch: https://reviews.llvm.org/D158943 `[sanitizer] Intercept glibc 2.38 __isoc23_* functions`

**Comment by mstorsjo** [comment]
/cherry-pick 8033231240f223dc7c718d1d27ece2dbcc8057c6 ad7e2501000da2494860f06a306dfe8c08cc07c3 277fc9475fb89c0b80d4237dbc8d698a55203c0d

**Comment by MaskRay** [comment]
Add a FreeBSD build fix for msan:

/cherry-pick 8033231240f223dc7c718d1d27ece2dbcc8057c6 ad7e2501000da2494860f06a306dfe8c08cc07c3 277fc9475fb89c0b80d4237dbc8d698a55203c0d 692344d87357ded619d216b265a9375f4326d8fb

**Comment by MaskRay** [comment]
Two compiler-rt tests use `-std=c23` that the release/17.x clang doesn't support. Here is a fix:

/branch MaskRay/llvm-project/17.x-san-test
