### ISSUE TITLE
[libcxx] Pretty printers for gdb fail on std::vector

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#64398]
Printing colourData in this code:

include <string>
```
static std::string colourData [] {
        std::string("x"),
        std::string("y")
};

int main() {
}
```

fails:

Breakpoint 1, main () at ss.cpp:12
12      }
(gdb) p colourData
$1 = {Python Exception <class 'gdb.error'>: There is no member or method named __short_mask.
, Python Exception <class 'gdb.error'>: There is no member or method named __short_mask.
}

FreeBSD 13.2
Python-3.9

gdb bug report: https://sourceware.org/bugzilla/show_bug.cgi?id=30556

**Comment by philnik777** [comment]
This seems to be a problem with your distribution. The trunk pretty printer doesn't use `__short_mask` anymore. Are you maybe building from trunk and are using the system-provided pretty printer?

**Comment by yurivict** [comment]
> Are you maybe building from trunk and are using the system-provided pretty printer?

The old libcxx snapshot used in the FreeBSD port caused this problem.
