### ISSUE TITLE
[Flang] Corrupt module error

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#64391]
A corrupt module error is observed while using a module containing an array initialization for an array with non-default lowerbound.

**Source**
$ cat m.f90
``` 
module m
  integer,parameter :: MASKS(0:5) = (/ 1, 2, 3, 4, 5, 6 /)
end module
```
$ cat s.f90 
```
subroutine s
use m
end subroutine
```
**Error**
$ flang-new -c m.f90 
$ flang-new -c s.f90 
```
error: Semantic errors in s.f90
./s.f90:2:5: error: Cannot read module file for module 'm': Module file is corrupt: ./m.mod
  use m
      ^
```

Note: Error was observed while compiling https://github.com/MCSclimate/MCT

**Comment by klausler** [comment]
Already have a fix for this one, it's coming with my next testing batch.

**Comment by klausler** [comment]
https://reviews.llvm.org/D157330
