### ISSUE TITLE
[BOLT] Release Notes for LLVM 17

### ISSUE THREAD

**Issue by aaupov** [llvm/llvm-project#64393]
/branch aaupov/llvm-project/main

**Comment by tru** [comment]
/branch aaupov/llvm-project/main

(unfortunately the branch commands has to be in a comment)

**Comment by tru** [comment]
Huh - it seems like maybe there is a bug in the action if the branch name is `main`?

**Comment by tru** [comment]
/branch tru/llvm-project/bolt_notes

(forgot to push the branch)

**Comment by tru** [comment]
Merged in 4bf07e1365e1
