### ISSUE TITLE
[aarch64] BigEndian with SVE crash at bitcast dag select 

### ISSUE THREAD

**Issue by joyhou-hw** [llvm/llvm-project#64406]
case as:  https://godbolt.org/z/j8s19Ksqq

will crash with aarch64_be and sve O2 case:
`fatal error: error in backend: Cannot select: 0xcfe5100: nxv4i32 = bitcast 0xd0053d0, example.cpp:15:24`

I found a commit reletad this. 
https://reviews.llvm.org/D79352

How could fix this?

**Comment by paulwalker-arm** [comment]
Candidate fix: https://reviews.llvm.org/D157406
