### ISSUE TITLE
[LLVM] ExecutionUnit/JITLink build error.

### ISSUE THREAD

**Issue by carlo-bramini** [llvm/llvm-project#64418]
While compiling llvm-project for making the packages, which seems to use more strict options, I got this error:

```
/home/carlo/packages/llvm/llvm-18.0.0git-1.x86_64/src/llvm-project/llvm/lib/ExecutionEngine/JITLink/aarch32.cpp: In function ‘bool llvm::jitlink::aarch32::writeRegister(llvm::jitlink::aarch32::WritableThumbRelocation&, llvm::jitlink::aarch32::HalfWords)’:
/home/carlo/packages/llvm/llvm-18.0.0git-1.x86_64/src/llvm-project/llvm/lib/ExecutionEngine/JITLink/aarch32.cpp:182:1: error: no return statement in function returning non-void [-Werror=return-type]
  182 | }
      | ^
ninja: build stopped: subcommand failed.
```

The cause of the error is evident, since `writeRegister()` is declared for returning a `bool`:
https://github.com/llvm/llvm-project/blob/5ba906327b0178b7635baa89710eb2967db1aa18/llvm/lib/ExecutionEngine/JITLink/aarch32.cpp#L176
but at the end of the function, it does not return any value.
In my opinion, this may be a copy-paste error and replacing `bool` with `void` just solves the issue.
Both current head and branch-17.x are affected by this mistake.

**Comment by lhames** [comment]
@carlo-bramini Thanks for catching this. I've changed the return type to void in dce179396e7e.

@weliveindetail -- does that fix look right to you?

**Comment by weliveindetail** [comment]
As noted in the ticket above, we missed to backport this to the 17.x release branch. Is it still worth doing?
