### ISSUE TITLE
[LLD][PowerPC] Fix "unrecognized instruction for IE to LE R_PPC64_TLS" for PowerPC targets

### ISSUE THREAD

**Issue by amy-kwan** [llvm/llvm-project#64424]
As a result of https://reviews.llvm.org/D153645, there is a failure when linking an msan libcxx test during `check-runtimes`:
```
$ cd /home/amyk/lldtest-mainbranch/runtimes/runtimes-bins/compiler-rt/lib/msan/tests && /home/amyk/lldtest-mainbranch/./bin/clang++ MSAN_INST_TEST_OBJECTS.msan_test.cpp.powerpc64le-with-call.o MSAN_INST_TEST_OBJECTS.msan_test_main.cpp.powerpc64le-with-call.o MSAN_INST_GTEST.gtest-all.cc.powerpc64le-with-call.o /home/amyk/lldtest-mainbranch/runtimes/runtimes-bins/compiler-rt/lib/msan/tests/../libcxx_msan_powerpc64le/lib//libc++.a /home/amyk/lldtest-mainbranch/runtimes/runtimes-bins/compiler-rt/lib/msan/tests/../libcxx_msan_powerpc64le/lib//libc++abi.a -o /home/amyk/lldtest-mainbranch/runtimes/runtimes-bins/compiler-rt/lib/msan/tests/./Msan-powerpc64le-with-call-Test -Wl,--color-diagnostics -nostdlib++ -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta -fsanitize=memory -ldl -m64 -fno-function-sections -m64 -fno-function-sections
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
ld.lld: error: unrecognized instruction for IE to LE R_PPC64_TLS
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

This issue occurs on both LLVM 17.0.0 rc1 and `main`.
A patch to fix this issue will follow.

**Comment by amy-kwan** [comment]
Currently working on a fix, so this issue will be assigned to me.

**Comment by nemanjai** [comment]
Is this because new instructions were added for TLS loads/stores?

**Comment by amy-kwan** [comment]
> Is this because new instructions were added for TLS loads/stores?

Yeah, the issue occurs because I am introducing more X-Form loads/stores that I can produce `tryTLSXFormLoad`/`tryTLSXFormStore` in `PPCISelDAGToDAG.cpp` in https://reviews.llvm.org/rG11b71ade51e0d1f90f1c68a7552a11f7e85eace1, and they are not accounted for in LLD.

I believe they need to be handled in LLD because `relaxTlsIeToLe()` will try to relax initial-exec to local-exec sequences if possible, and the types of load/stores that are handled are specifically implemented inside `lld/ELF/Arch/PPC64.cpp`. 

I did not catch this before as I realized I did not build libc++, which is where the test is coming from.

**Comment by nemanjai** [comment]
If the fix is going to take a while and this is blocking the libc++ build, perhaps it is better to temporarily pull the patch until a complete fix is available.

**Comment by MaskRay** [comment]
> If the fix is going to take a while and this is blocking the libc++ build, perhaps it is better to temporarily pull the patch until a complete fix is available.

Removing https://reviews.llvm.org/D153645 for just https://github.com/llvm/llvm-project/tree/release/17.x LGTM, to not cause compatibility issues with lld TLS optimization.

**Comment by tru** [comment]
Are we still targetting a fix for 17.X?

**Comment by amy-kwan** [comment]
I forgot to link the patch back here, but I have https://reviews.llvm.org/D158197 up for review.

**Comment by amy-kwan** [comment]
> Are we still targetting a fix for 17.X?

@tru Yes, to answer the question explicitly, I believe we are still targeting a fix for 17.x with the patch I have up: https://reviews.llvm.org/D158197

**Comment by amy-kwan** [comment]
Reopening issue to cherry-pick the fix into `release/17.x`:
/cherry-pick 698b45aa902de4d30c798e8d6bd080c8e31bade8
