### ISSUE TITLE
Bootstrapping clang release/17.x fails to build -  ‘clang/Driver/Options.inc’ file not found

### ISSUE THREAD

**Issue by jroelofs** [llvm/llvm-project#64432]
When bootstrapping clang, the stage 2 builds appear to sometimes fail due to a missing table gen file.
```
llvm-project/clang/include/clang/Driver/Options.h:49:10: fatal error: 'clang/Driver/Options.inc' file not found
   49 | #include "clang/Driver/Options.inc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

This seems to happen during stage 2 builds.

rdar://113401138

**Comment by jroelofs** [comment]
@EugeneZelenko so I get it right next time: why not `release:fixed-in-main`?

**Comment by EugeneZelenko** [comment]
@jroelofs: I didn't remove this label intentionally. Probably we edited labels at the same time, so GitHub was confused.
