### ISSUE TITLE
unsupported option '-mwindows' for target 'aarch64-w64-mingw32'

### ISSUE THREAD

**Issue by brechtsanders** [llvm/llvm-project#64464]
When doing a native build of NSPR 4.35 on Windows on Arm using [LLVM 17.0.0 RC1](https://github.com/mstorsjo/llvm-mingw/releases/tag/20230730) I got the error `unsupported option '-mwindows' for target 'aarch64-w64-mingw32'`.

However when building for MinGW-w64 the `-mwindows` is normally supported (at least I know it is for GCC).

Full output:
```console
make -C config export
make[1]: Entering directory '/r/winlibs_llvm17rc1/11064.nspr/nspr-4.35/nspr/config'
/d/Prog/winlibs_llvm17rc1/llvm-mingw-20230730-ucrt-aarch64/bin/clang.exe -mwindows -o now.o -c     -Wno-int-conversion -pthread -g   -UNDEBUG -DDEBUG_brecht -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DDEBUG=1 -DXP_PC=1 -DWIN32=1 -DWINNT=1 -D_ARM64_=1 -DHAVE_STRERROR=1 -DFORCE_PR_LOG   now.c
clang-17: error: unsupported option '-mwindows' for target 'aarch64-w64-mingw32'
make[1]: *** [../config/rules.mk:450: now.o] Error 1
make[1]: Leaving directory '/r/winlibs_llvm17rc1/11064.nspr/nspr-4.35/nspr/config'
make: *** [config/rules.mk:163: export] Error 2
```

**Comment by alvinhochun** [comment]
I am guessing this is because `-mwindows`/`-mconsole` are only used when it needs to invoke the linker: https://github.com/llvm/llvm-project/blob/f108c6cdc1d0cd60f7d50cdb61ed6307258e5f14/clang/lib/Driver/ToolChains/MinGW.cpp#L141-L150, so it's only when clang needs to invoke the linker that it actually consume these arguments. Your clang invocation has `-c`, which means no linking. `-mwindows`/`-mconsole` are flagged as TargetSpecific:
https://github.com/llvm/llvm-project/blob/f108c6cdc1d0cd60f7d50cdb61ed6307258e5f14/clang/include/clang/Driver/Options.td#L4259-L4262, which means if they are not consumed they will cause clang to report an error: https://github.com/llvm/llvm-project/blob/f108c6cdc1d0cd60f7d50cdb61ed6307258e5f14/clang/lib/Driver/Driver.cpp#L4963-L4964

We could somehow ignore these arguments when no linking is needed, but does it even make sense to pass them when not linking the final binary? Also I don't think this issue is specific to aarch64 at all.

CC @mstorsjo

**Comment by brechtsanders** [comment]
I see your point.

Ignoring these arguments would improve GCC compatibility.

The alternative is to have all projects fixed that use it in the wrong place (like NSPR), which could be several projects since GCC never gave an error.

Or is there a flag that can be used to build these projects to only treat it as a warning?

**Comment by mstorsjo** [comment]
Indeed, this is nothing aarch64 specific (even if that error message makes it sound so).

The options are, as noted, not relevant at all while compiling. I haven't run into a case so far where projects are doing this, but apparently there are some cases. Anyway, having it as a hard error is quite uncomfortable, especially as GCC doesn't warn about it at all. It's possible to silence the error with `-Qunused-arguments` though.

We had a similar situation a couple months ago; `-mthreads` used to give the warning `clang: warning: argument unused during compilation: '-mthreads' [-Wunused-command-line-argument]`, but the flag was changed into a target-specific flag like this one, which made it a hard error. See #63282, and the fix in https://github.com/llvm/llvm-project/commit/a79995ca6004082774a87f7a58ab6be5343364b7#diff-d20fe017578b739909633091655da0c15848a81a4b26a5091b667876d08545f4. There, @MaskRay added a mechanism for lowering the level of fatality of this option from hard error to a simple warning about the flag being unused. So we could add similar handling of `-mwindows` and `-mconsole` as we did for `-mthreads`.

A patch that does the same for `-mwindows` and `-mconsole`, as for `-mthreads`, should certainly be welcome.

**Comment by brechtsanders** [comment]
Sorry, I haven't been able to come up with a patch myself (yet).

But while building gobject-introspection-1.78.1 on Windows on ARM (aarch64) I get an error about invalid `-mdll` linker flag:
```raw
clang-17: error: unsupported option '-mdll' for target 'aarch64-w64-mingw32'
```

This seems to be a similar issue.

So if a patch is made it should address the issue for:
- `-mwindows`
- `-mconsole`
- `-mdll`

**Comment by Anutrix** [comment]
I get this when building Godot for Windows on x64:
```
clang-17: error: unsupported option '-mwindows' for target 'x86_64-w64-mingw32'
```
So this is not just for aarch64. I used the version from https://github.com/mstorsjo/llvm-mingw though.

**Comment by mstorsjo** [comment]
I've got a fix suggestion up in #67891.

**Comment by jakirkham** [comment]
Seeing the same issue except with MSVC ( https://github.com/llvm/llvm-project/issues/69964 )

**Comment by Molier** [comment]
i have the same issue at the moment: 
```clang-19: error: unsupported option '-mlong-double-64' for target 'aarch64-w64-windows-gnu'```
while trying to install numpy/scipy using llvm 19.1.0 
I was using the linaro build https://discourse.llvm.org/t/llvm-19-x-release-third-party-binaries/80374/10 but trying to build source myself now
