### ISSUE TITLE
Using atomic operations creates multiple, distinct function declarations

### ISSUE THREAD

**Issue by DougGregor** [llvm/llvm-project#6447]
|  |  |
| --- | --- |
| Bugzilla Link | [6075](https://llvm.org/bz6075) |
| Version | trunk |
| OS | All |

## Extended Description 
As reported here:

  http://lists.cs.uiuc.edu/pipermail/cfe-dev/2010-January/007506.html

The following code creates two `FunctionDecls` for `__sync_fetch_and_add`, which do *not* share a canonical declaration:
```cpp
  void foo() {
   int i;
   __sync_fetch_and_add(&i, 1);
   __sync_fetch_and_add(&i, 1);
  }
```
We should probably just create one `FunctionDecl`, or at the very least be careful to link the `FunctionDecls` together.

**Comment by zwuis** [comment]
Doesn't reproduce since Clang 3.2.
Godbolt: <https://godbolt.org/z/YcbhW9b61>
