### ISSUE TITLE
Patch for Phabricator is out-of-date

### ISSUE THREAD

**Issue by yichi170** [llvm/llvm-project#64470]
As the title mentioned, the patch for Phabricator is out-of-date and cannot directly apply to the https://github.com/phacility/arcanist

The patch is here: https://github.com/llvm/llvm-project/blob/main/llvm/utils/phabricator/0001-Fix-PHP-8.1-incompatibility-with-arc-patch-D-12345.patch

**Comment by Endilll** [comment]
CC @nickdesaulniers as author of aforementioned patch

**Comment by nickdesaulniers** [comment]
out of date? Did arcanist come out of archival status?

Anyways, LLVM is moving to github for code reviews; I'm not going to maintain arcanist support.

**Comment by joker-eph** [comment]
The commits in arcanist are about php8 compatibility, so it is likely that the LLVM patch isn't needed anymore.
