### ISSUE TITLE
LLVM 16 might require Macos 11.3 as minimum version

### ISSUE THREAD

**Issue by gbaraldi** [llvm/llvm-project#64492]
This is a very specific case but we in julia cross compile llvm from linux to macos, so we target specific sdks. Be that as it may, the AMDGPU target builds a tie from a tuple and that hits https://github.com/simdjson/simdjson/issues/578. Which was fixed by https://github.com/llvm/llvm-project/commit/a0839b14df6de99fe29bee7cdfff182d50de665d which seems to be only in macos 11.3 (according to the wikipedia page that's when they moved to LLVM 13)

**Comment by jayfoad** [comment]
> the AMDGPU target builds a tie from a tuple

Which line of code does this?

**Comment by gbaraldi** [comment]
Oh it seems you fixed this on LLVM 17 with https://github.com/llvm/llvm-project/commit/735cb7b1f84a36049ea187fecdd281c6e93600bb but the line was https://github.com/llvm/llvm-project/blob/7cbf1a2591520c2491aa35339f227775f4d3adf6/llvm/lib/Target/AMDGPU/AsmParser/AMDGPUAsmParser.cpp#L5488

But I guess it didn't get ported to LLVM 16

**Comment by arsenm** [comment]
https://discourse.llvm.org/t/16-0-6-release/71344 says there will be no more 16.x releases so not sure what you expect here

**Comment by gbaraldi** [comment]
I guess I was hoping it could be back ported. I wasn't aware that 16.0.6 was the last 16.x release so I'm not sure theres any course of action then.

**Comment by arsenm** [comment]
This is fixed in 17 and there aren't going to be any more 16 releases
