### ISSUE TITLE
Backport f70e83af7a708a22fdde8c644ac5810223090cd4

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [llvm/llvm-project#64497]
/cherry-pick [e82cc56](https://github.com/llvm/llvm-project-release-prs/commit/e82cc564bca3988a5f5c6ac1dd331123a98b6eeb)

This fixes a build issue in clang 17 when building with a recent glibc but old kernel headers. See #64456

**Comment by EugeneZelenko** [comment]
/cherry-pick [e82cc56](https://github.com/llvm/llvm-project-release-prs/commit/e82cc564bca3988a5f5c6ac1dd331123a98b6eeb)

**Comment by Romain-Geissler-1A** [comment]
Ah it seems I tried to cherry-pick the wrong commit. I will try again.

**Comment by Romain-Geissler-1A** [comment]
Closing, as it was pushed in branch 17 via https://github.com/llvm/llvm-project/commit/e69c715c39f05ed2d9ceedaf71feeb61e0c142ef

**Comment by EugeneZelenko** [comment]
Duplicate of #64456.
