### ISSUE TITLE
Question about optimization attributes

### ISSUE THREAD

**Issue by kelbon** [llvm/llvm-project#64507]

**Comment by kelbon** [comment]
For simple cases i can 'preload' values and mark them 'const', but it may be pessimization in many cases and dont work for huge objects like std::vector

**Comment by kelbon** [comment]
May be [[clang::normal_function]], [[clang::local]] or ))) [[clang::kind]] ))) to mark functions, which may change only global state or their arguments which are not 'const X*/&' ?.. They are not pure, because i want to call them and they can produce different values each time with same arguments, but they predictable change state of programm

**Comment by arsenm** [comment]
I think this corresponds to argmemonly in the IR, not sure if there's a source level equivalent
