### ISSUE TITLE
[LTO] [MinGW] Use of thread locals from different translation unit broken with LTO

### ISSUE THREAD

**Issue by amyspark** [llvm/llvm-project#64513]
Hi all,

This is to report that if both `-flto` and `-fopenmp` are enabled for a target, and it makes use of a static library that contains a symbol exported by `#pragma openmp threadprivate(...)`, linking will fail with the following error:

```
FAILED: subprojects/pixman-0.42.2/test/region-test.exe
"cc"  -o subprojects/pixman-0.42.2/test/region-test.exe subprojects/pixman-0.42.2/test/region-test.exe.p/region-test.c.obj "-flto" "-Wl,--start-group" "subprojects\pixman-0.42.2\test\libtestutils.a" "subprojects\pixman-0.42.2\pixman\libpixman-1.a" "subprojects\pixman-0.42.2\pixman\libpixman-mmx.a" "subprojects\pixman-0.42.2\pixman\libpixman-sse2.a" "subprojects\pixman-0.42.2\pixman\libpixman-ssse3.a" "-pthread" "-fopenmp" "-fopenmp" "-lm" "D:/msys64/clang64/bin/../lib/libpng16.dll.a" "-Wl,--subsystem,console" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32" "-Wl,--end-group"
ld.lld: error: undefined symbol: thread-local initialization routine for prng_state
>>> referenced by ../subprojects/pixman-0.42.2/test/region-test.c
>>>               subprojects/pixman-0.42.2/test/region-test.exe.p/region-test.c.obj

ld.lld: error: undefined symbol: thread-local initialization routine for prng_state_data
>>> referenced by ../subprojects/pixman-0.42.2/test/region-test.c
>>>               subprojects/pixman-0.42.2/test/region-test.exe.p/region-test.c.obj
cc: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

Linking with `-flto=thin`, as well as building with GCC + `-flto`, both result in a working build.

To reproduce, please download https://www.cairographics.org/releases/pixman-0.42.2.tar.gz, unpack it, and then perform:

```
cd pixman-0.42.2
meson setup build -Ddefault_library=static -Db_lto=true -Dbackend_max_links=1
meson compile -C build
```

clang version 16.0.5
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:/msys64/clang64/bin

**Comment by amyspark** [comment]
Minimal repro case is attached here: https://github.com/amyspark/llvm-bug-64513.git

Just configure with CMake and set `-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS="-flto -fopenmp" -DCMAKE_CXX_FLAGS="-flto -fopenmp"`.

**Comment by mstorsjo** [comment]
I was made aware of another issue with symptoms very similar to this one. That case is reproducible with an even smaller example, and it's not related to OpenMP, but general TLS and LTO. It's reproducible with the following files:

- `main.cpp`
```c++
#include "thread.h"

int main(int argc, char* argv[]) {
    Thread t;
    return t.get_caller_id();
}
```
- `thread.h`
```c++
lass Thread {
private:
    static thread_local int caller_id;

public:
    static int get_caller_id() {
        return caller_id;
    }
};
```
- `thread.cpp`
```c++
#include "thread.h"

thread_local int Thread::caller_id = 0;
```

It's reproducible with the following build commands:
```console
$ clang -target x86_64-w64-mingw32 -flto -c thread.cpp -o thread.o
$ clang -target x86_64-w64-mingw32 -flto -c main.cpp -o main.o
$ clang -target x86_64-w64-mingw32 main.o thread.o -o main.exe
ld.lld: error: undefined symbol: thread-local initialization routine for Thread::caller_id
>>> referenced by main.cpp
>>>               main.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mstorsjo** [comment]
> Linking with `-flto=thin`, as well as building with GCC + `-flto`, both result in a working build.

FWIW, my testcase above reproduces the same issue both with `-flto` and `-flto=thin`.

**Comment by mstorsjo** [comment]
I posted a potential fix for this issue at https://github.com/llvm/llvm-project/pull/70430.
