### ISSUE TITLE
Missed transform: `umin/umax/smin/smax` on `i1` to `and/or`

### ISSUE THREAD

**Issue by Kmeakin** [llvm/llvm-project#64537]
`umin(i1, i1) => and`: https://alive2.llvm.org/ce/z/tRp7VK
`umax(i1, i1) => or`: https://alive2.llvm.org/ce/z/7nS6Wp

`smin(i1, i1) => or`: https://alive2.llvm.org/ce/z/XXfBSk
`smax(i1, i1) => and`: https://alive2.llvm.org/ce/z/N9fqT2

**Comment by elhewaty** [comment]
@RKSimon I think I fixed it, how can I test the changes?
how can I know where `make check-llvm` fails exactly?

**Comment by RKSimon** [comment]
Try `make check-llvm-transforms` - but its likely you will need to add additional tests inside llvm-project/llvm/test/Transforms/InstCombine/

**Comment by overlorde** [comment]
hi @elhewaty any update of the patch?

**Comment by Qi-Hu** [comment]
Hi @elhewaty, are you still working on this issue? If you don't mind, I'd like to take over. I wrote this patch as a practice: https://reviews.llvm.org/D158915.

**Comment by elhewaty** [comment]
@RKSimon I am sorry, but I had some social problems the past few weeks.
I will find some other issues as this one is solved already.
I appreciate your help.

**Comment by Qi-Hu** [comment]
The patch has been landed: [1a65cd3fcf58](https://reviews.llvm.org/rG1a65cd3fcf5828ecd36fd336de7689ff7a0218a4). This issue can be closed.
