### ISSUE TITLE
missing optimisations: combining conditions

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [llvm/llvm-project#64531]
Two functions:

```
bool tst1(int a0, int a1, int b0, int b1) {
  return (a0 > a1) || (a0 == a1 && b0 < b1);
}

bool tst2(int a0, int a1, int b0, int b1) {
  return (a0 > a1) | (a0 == a1 && b0 < b1);
}
```

Produce different assembly https://godbolt.org/z/jfEW5Y4nx

I think it should be the same assembly.

**Comment by overlorde** [comment]
I would like to work on that. I'm new contributing  to llvm, would like to start with that issue. I have studied about peephole optimizations and instcombine pass, and ways to add optimizations.

**Comment by nikic** [comment]
The difference here is exactly what was written in the source code: In one case there is short-circuiting and in the other there isn't. Whether the second form is faster or slower will depend on the branch probability.

I don't think there is anything to do here, at least with the information given in the issue report.

**Comment by overlorde** [comment]
thanks
