### ISSUE TITLE
[libc++] std::rotl and std::rotr have the wrong signature

### ISSUE THREAD

**Issue by derekmauro** [llvm/llvm-project#64544]
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0553r3.html
https://en.cppreference.com/w/cpp/numeric/rotl
https://en.cppreference.com/w/cpp/numeric/rotr

According to all documentation I see, the second argument to `std::rotl` and `std::rotr` should be `int`, and defines the behavior when the argument is negative. However, `libc++` uses `unsigned int`:

https://github.com/llvm/llvm-project/blob/211c9752c8200fbb3ff7be1f6aa98037901758ce/libcxx/include/__bit/rotate.h#L37
https://github.com/llvm/llvm-project/blob/211c9752c8200fbb3ff7be1f6aa98037901758ce/libcxx/include/__bit/rotate.h#L45

**Comment by DKay7** [comment]
Hi! 

I think I'm gonna take it.
