### ISSUE TITLE
How do I link ELF files from lld-link.exe?

### ISSUE THREAD

**Issue by BenHut1** [llvm/llvm-project#64548]
I'm using lld-link.exe, the Windows version of lld linker. I'm using NASM to assemble ELF object files from assembly code, and am trying to use lld-link.exe to link those into ELF executable files. Unfortunately when I use the command line "lld-link.exe test.o" (where "test.o" is the name of the ELF object file), it says "lld-link: error: test.o: unknown file type". Is the Windows version of lld-link only capable of handling COFF files? Because I need a way to compile on Windows software that will then be run on Linux. Linux is a complicated OS to use even during normal use, and using it as a development environment is even more complex. So I'm doing all my development in Windows. Even if Windows can't run Linux software, software development tools that run in Windows should certainly be able to generate Linux executables. As it is NASM for Windows already is capable of generating numerous types of object files, including both COFF an ELF. I'm now just trying to find a linker that will run in Windows that will take an ELF object file as input, and output an ELF executable file. Is this possible with lld-link.exe? There's lots of command line switches it has available. Do I just need to use one of those switches? Or do I need to abandon the Windows version of lld-link altogether?

**Comment by BertalanD** [comment]
You can run `ld.lld`, the ELF version of the LLD linker on Windows.

**Comment by efriedma-quic** [comment]
To add, there is no flag to make lld-link produce ELF because nobody needs that behavior; software that targets ELF expects to pass POSIX-style linker flags, so you can just use ld.lld.

ld.lld on Windows works exactly the same way it does on Linux.
