### ISSUE TITLE
Clang does not know, that noop_coroutine is noop

### ISSUE THREAD

**Issue by kelbon** [llvm/llvm-project#64542]
```C++
#include <coroutine>

void foo() {
    std::coroutine_handle<void> h = std::noop_coroutine();
    h();
}
```
https://godbolt.org/z/o8zKsfrbn

As i understand its just lack of attributes on inner function pointers

**Comment by ChuanqiXu9** [comment]
hmmm I don't understand your problem. Could you elaborate?

**Comment by ChuanqiXu9** [comment]
Do you mean we should optimize the call away? While it may be possible for the specific example, it is impossible for real world examples, since we don't know if a coroutine_handle refers to a noop_coroutine statically.

**Comment by kelbon** [comment]
> Do you mean we should optimize the call away? While it may be possible for the specific example, it is impossible for real world examples, since we don't know if a coroutine_handle refers to a noop_coroutine statically.

I want optimization in this case and in, for example:

```C++
struct [[nodiscard("co_await it!")]] transfer_control_to {
  std::coroutine_handle<void> who_waits;

  bool await_ready() const noexcept {
    assert(who_waits != nullptr);
    return false;
  }
  std::coroutine_handle<void> await_suspend(std::coroutine_handle<void>) noexcept {
    return who_waits;  // symmetric transfer here
  }
  static constexpr void await_resume() noexcept {
  }
};
auto final_suspend () {
  if (abc)
     return transfer_control_to(owner);
  else
     return transfer_control_to(std::noop_coroutine());
}

```

Another example: i have recursive generator and it has 'owner' handle, which is by default 'std::noop_coroutine()', i pass control to it in final suspend.

In simple non-recursive use case compiler can statically see, that i never change 'owner' handle after setting it to 'std::noop_coroutine()' and it can help to remove useless code + remove allocation.
Now its just black box for compiler and it breaks all possible allocation removes (may be this call will store 'handle' in some place and change 'handle' in generator, so it will dont die here).. etc

**Comment by ChuanqiXu9** [comment]
For the simple case, clang are able to make it with libc++ thanks to the way we implement noop_coroutine: https://godbolt.org/z/MEdbxezrs.

But for the cases you give, it is hard.

For the first case, I won't say it is theoretically impossible. But it is pretty hard and it beyond the scope of coroutines specific coroutines and it requires other optimizations to get involved in, which don't like the specific language semantics.

For the second case, I am not sure if I understand it correctly, maybe it is worth to give it a try with libc++.

I don't mind to leave the issue opening. But I just want to mention that the progress to optimize it to the degree you want may be pretty pretty slow.

**Comment by kelbon** [comment]
> Also it needs to understand the value of abc at compile time.

i imagine it like 'reversing' condition after inline

before:
```C++
auto value = [] {
   if (abc) return owner;
   else     return std::noop_coroutine();
};
goto value.handle;
```
after
```C++
if (abc) goto owner;
else     /* noop */;
```

About second - i will try with libc++, thank

**Comment by ChuanqiXu9** [comment]
> > Also it needs to understand the value of abc at compile time.
> 
> i imagine it like 'reversing' condition after inline
> 
> before:
> 
> ```c++
> auto value = [] {
>    if (abc) return owner;
>    else     return std::noop_coroutine();
> };
> goto value.handle;
> ```
> 
> after
> 
> ```c++
> if (abc) goto owner;
> else     /* noop */;
> ```
> 

Yeah, but the code generated by the middle end is more complex and at least in my imagination, the optimizer may not be able to do it. But you can give it a try with libc++ too.

**Comment by ChuanqiXu9** [comment]
@kelbon is there an update? And I prefer to close this since there may not be too many things we can do for the wanted case.

**Comment by kelbon** [comment]
> @kelbon is there an update? And I prefer to close this since there may not be too many things we can do for the wanted case.

Yes, i have tried and compiler cannot optimizie allocations in simplest possilbe case(
https://godbolt.org/z/hbMTE4ff3
May be i will change implementation... I dont know

**Comment by kelbon** [comment]
> @kelbon is there an update? And I prefer to close this since there may not be too many things we can do for the wanted case.

.
