### ISSUE TITLE
[libc++] [Modules] Introduce std.experimental module

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#64552]
Now we've already have std module and we will have std.compat module as planned.

But we still have things not covered by C++20 modules in libc++, the experimental things. It is not mentioned in the paper since the experimental things are beyond the scope of the specification. But I feel it may be consistent to provide std.experimental.

Feel free to close this if it is not wanted.

**Comment by kelbon** [comment]
It also feels consistant to support impost std in C++20... MSVC implementors told me they were going to do it, it would be nice to do this on all implementations

**Comment by mordante** [comment]
I'm not sure whether an `std.experimental` module is  useful. But let's see what the what the response on the reflector is.

@kelbon interesting to hear. This is the first time I hear that. Is there a public statement you can share? When other implementations will make `std` available C++20 I wouldn't mind to consider it too.

**Comment by davidstone** [comment]
Given that all of the experimental stuff is already in namespace
std::experimental (right?), what advantage does module std.experimental
give us over just exporting experimental things from module std? std.compat
exists explicitly for things not in namespace std.

**Comment by kelbon** [comment]
> I'm not sure whether an `std.experimental` module is useful. But let's see what the what the response on the reflector is.
> 
> @kelbon interesting to hear. This is the first time I hear that. Is there a public statement you can share? When other implementations will make `std` available C++20 I wouldn't mind to consider it too.

sorry i cant find it now, it was on reddit and one of msvc devs write it

**Comment by ChuanqiXu9** [comment]
> It also feels consistant to support impost std in C++20... MSVC implementors told me they were going to do it, it would be nice to do this on all implementations

It looks like an extension to support std module in C++20. I am not sure how libc++ devs think about it. But I like the idea as a user.

> Given that all of the experimental stuff is already in namespace
std::experimental (right?), what advantage does module std.experimental
give us over just exporting experimental things from module std? std.compat
exists explicitly for things not in namespace std.

My personal thought is that std module is defined by the WG21. So that it may be not consistent with the specification if we export experimental things in std module. Also as a user, I'll feel surprised that I can use experimental things by importing std module.

**Comment by mordante** [comment]
> > I'm not sure whether an `std.experimental` module is useful. But let's see what the what the response on the reflector is.
> > @kelbon interesting to hear. This is the first time I hear that. Is there a public statement you can share? When other implementations will make `std` available C++20 I wouldn't mind to consider it too.
> 
> sorry i cant find it now, it was on reddit and one of msvc devs wrote it

Then I'll ask them about it.



> > It also feels consistant to support impost std in C++20... MSVC implementors told me they were going to do it, it would be nice to do this on all implementations
> 
> It looks like an extension to support std module in C++20. I am not sure how libc++ devs think about it. But I like the idea as a user.

Nowadays we're hesitant with backporting features. In the past is caused us some issues when implementing new features. For example, making `to_chars` `constexpr` removed the feature from C++11. The other issue is that it does not help to write portable code, when only one standard library supports it. If the other standard libraries are willing to support this it solves the portability issue. For modules I don't see a large backwards compatibility issue.
That's my point of view, obviously this needs to be discussed with the other libc++ developers.
 
> > Given that all of the experimental stuff is already in namespace
> > std::experimental (right?), what advantage does module std.experimental
> > give us over just exporting experimental things from module std? std.compat
> > exists explicitly for things not in namespace std.
> 
> My personal thought is that std module is defined by the WG21. So that it may be not consistent with the specification if we export experimental things in std module. Also as a user, I'll feel surprised that I can use experimental things by importing std module.

This means we currently should export named declarations from TSs in the `std` module according to the Standard. Do I understand you correctly?

**Comment by mordante** [comment]
@kelbon I've asked and that resulted in https://github.com/microsoft/STL/issues/3945. We, the libc++ developers are discussing this at the moment.

**Comment by kelbon** [comment]
> @kelbon I've asked and that resulted in [microsoft/STL#3945](https://github.com/microsoft/STL/issues/3945). We, the libc++ developers are discussing this at the moment.

Nice to hear! This will probably speed up real-world usage of modules by several years.

**Comment by mordante** [comment]
For now I'll close this. I don't see a strong motivation to add elements in the `std::experimental` namespace to a module.

We currently don't have a lot in the experimental namespace and it seems WG21 is not really pursuing TSes anymore. (I can understand why.) I also don't expect people to start to work on not implemented TSes any time soon in libc++. When that happens we might reevaluate. (SIMD is active but it is also on track for C++26.)
