### ISSUE TITLE
Port AtomicExpand pass to new pass manager

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#64559]

**Comment by DKay7** [comment]
Hi!

I think I'm gonna take it. Could you provide me with some steps to start with? Thanks.

**Comment by arsenm** [comment]
This one is best to just follow an example. This pass is probably most similar to llvm/lib/CodeGen/TypePromotion.cpp, which was ported in 615333bc09c42cdac4d69ea171e610cdcb06e803.

The method for getting analyses changed, so most of these involved refactoring to split the actual implementation into a helper class with a new (e.g. TypePromotionPass, with a run() implementation) and old pass manager entry point class (TypePromotionLegacy with runOnFunction and getAnalysisUsage)

**Comment by kzhuravl** [comment]
@DKay7, are you still planning to work on this issue?

**Comment by DKay7** [comment]
@kzhuravl yes, I'm on it. I was a little busy so it take a bit much more time.

**Comment by tapan0007** [comment]
Hi, I would love to work on it if it's not completed or in progress.

**Comment by DKay7** [comment]
> Hi, I would love to work on it if it's not completed or in progress.

Well, I've already started, but I haven't done much, so you can take it.

**Comment by kzhuravl** [comment]
Thanks @tapan0007!

**Comment by Ris-Bali** [comment]
Hey @tapan0007 are u still working on this?

**Comment by tapan0007** [comment]
Hi, yes I am still working on it. Planning to submit the patch in a day or two.
