### ISSUE TITLE
Missed transform: `(a & !b) ? a : b` into `a | b`

### ISSUE THREAD

**Issue by Kmeakin** [llvm/llvm-project#64558]
[godbolt](https://godbolt.org/z/az9bY9YPP), [alive](https://alive2.llvm.org/ce/z/seurTh)

```c
#include <stdbool.h>

bool src(bool a, bool b) { return (a & !b) ? a : b; }
bool tgt(bool a, bool b) { return a | b; }
```

```llvm
define i1 @src(i1 %0, i1 %1){
  %3 = xor i1 %1, true
  %4 = and i1 %3, %0
  %5 = select i1 %4, i1 %0, i1 %1
  ret i1 %5
}

define i1 @tgt(i1 %0, i1 %1){
  %3 = or i1 %0, %1
  ret i1 %3
}
```

Note that the x864-64 backend is able to optimise `src` into `tgt`, but AArch64 and RISCV are not, so there is probably a missind DAG combine too

**Comment by dtcxzyw** [comment]
Candidate patch: https://reviews.llvm.org/D158983
