### ISSUE TITLE
[clang] Accepting invalid C++ code with multiple designated initializers for a union

### ISSUE THREAD

**Issue by Eisenwave** [llvm/llvm-project#64557]
## Code to Reproduce
This is an excerpt from [[dcl.init.aggr] p13](https://eel.is/c++draft/dcl.init.aggr#example-13) (with a redundant `union` for C compatibility):
```cpp
union u { int a; const char* b; };
union u g = { .a = 1, .b = "asdf" };  // error
```
## Actual Output
In C and C++ mode, the produced warning is: (https://godbolt.org/z/7z5Ed58qc)
```
<source>:2:23: warning: initializer overrides prior initialization of this subobject [-Winitializer-overrides]
union u g = { .a = 1, .b = "asdf" };  // error
                      ^~~~~~~~~~~
<source>:2:20: note: previous initialization is here
union u g = { .a = 1, .b = "asdf" };  // error
                   ^
```
## Expected Output
I assume that this code is allowed in C99. However, in C++ mode, such code is disallowed:

> When a union is initialized with an initializer list, there shall not be more than one explicitly initialized element.

\- [[dcl.init.aggr] p20](https://eel.is/c++draft/dcl.init.aggr#20)

## Suggested Fix
Disallow this code entirely in C++ mode, or emit an additional warning which informs the user that they are using C99 extensions.

**Comment by Eisenwave** [comment]
Nvm fixed on trunk.

**Comment by shafik** [comment]
I fixed this relatively recently: https://github.com/llvm/llvm-project/issues/62156
