### ISSUE TITLE
Port AMDGPURewriteUndefForPHI to new pass manager

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#64561]

**Comment by saichatla** [comment]
Hi,
I would like to take this issue. But I am quite new to LLVM and have done some reading but I would like some pointers before getting started. Thanks!

**Comment by arsenm** [comment]
> Hi, I would like to take this issue. But I am quite new to LLVM and have done some reading but I would like some pointers before getting started. Thanks!

Just going to repeat my comment from here: https://github.com/llvm/llvm-project/issues/64559#issuecomment-1677199921

The only real difference is this one is target specific and AMDGPUCodeGenPreparePass::run is similar

**Comment by kzhuravl** [comment]
@saichatla, are you still planning to work on this issue?

**Comment by kzhuravl** [comment]
Assigning to @jwanggit86 since I have not hard back.

**Comment by jwanggit86** [comment]
Working on it.

**Comment by jwanggit86** [comment]
Code has been merged upstream. Pull request: [66008](https://github.com/llvm/llvm-project/pull/66008 ).
