### ISSUE TITLE
GlobalISelEmitter misses dead flags on scalar zext pattern

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#64565]
This test case doesn't set the dead flag on the implicit-def `$scc`

```console
# llc -run-pass=instruction-select -mtriple=amdgcn-amd-amdpal -mcpu=fiji < %s
---
name:            s_zext_s16_to_s32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $sgpr0, $sgpr1, $sgpr2

    %0:sgpr(s32) = COPY $sgpr0
    %1:sgpr(s16) = G_TRUNC %0
    %2:sgpr(s32) = G_ZEXT %1
    $sgpr0 = COPY %2
    SI_RETURN_TO_EPILOG implicit $sgpr0

...
```
This pattern appears in the test failures with the patch for #63986 is applied

**Comment by Pierre-vh** [comment]
Ah, I think I see it.
When `MutateOpcode` is used, the implicit defs are added. When BuildMI is used, the implicit defs are not added because it assumes they're added automatically. I'll check if we can make them explicit.

**Comment by Pierre-vh** [comment]
https://reviews.llvm.org/D157515
