### ISSUE TITLE
Port CodeGenPrepare to new pass manager

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#64560]

**Comment by Krishna-13-cyber** [comment]
Hi,
I would like to take up this task, I am referring to the same resources given to 64559.

**Comment by Krishna-13-cyber** [comment]
Yes @hhkit , I am on it!

**Comment by nickleus27** [comment]
Hi @Krishna-13-cyber.  I have not seen any activity on this issue or in the PR #68530 in a while, and I was wondering if you were still working on this issue? If not, I would like to give it a try.

**Comment by nickleus27** [comment]
I would like to work on this issue if no one is actively working on it. @arsenm could you assign this issue to me? After looking over commit 615333b as an example I think I have an idea of what needs to be done:

1. create new file `CodeGenPrepare.h`
2. create a `run` function in `CodeGenPrepare` class (renamed to `CodeGenPrepareImpl`)
3. create a helper class in `CodeGenPrepare.cpp` called `CodeGenPrepareLegacy` that has `FunctionPass` as the base class. In this class have `runOnFunction` call `CodeGenPrepareImpl::run`
4. Update all function names etc
5. Update all test files etc

Am I understanding this correctly? If so am I missing anything? Any info or resources would be appreciated.

**Comment by arsenm** [comment]
There's some in-progress work in #68530

**Comment by nickleus27** [comment]
@arsenm Is it okay to work on this issue if there is in-progress work in #68530? If so, is it okay to open a new PR?
