### ISSUE TITLE
[LLD] Stride mismatch when using EHcont, also not set in GuardFlags

### ISSUE THREAD

**Issue by namazso** [llvm/llvm-project#64570]
The EHcont table uses the same stride as the CF table. These tables can have a stride, which is marked in GuardFlags, [see MSDN](https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#the-load-configuration-structure-image-only):

> Mask for the subfield that contains the stride of Control Flow Guard function table entries (that is, the additional count of bytes per table entry).

These are mismatched. LLD unconditionally leaves the stride at 0, however it writes the EHcont table with a stride of 1 (notice the true): 

https://github.com/llvm/llvm-project/blob/8ab62da18d47fa0ce6aef9da50cca34a26ea775c/lld/COFF/Writer.cpp#L1799

this results in tha only every fifth EHcont entry actually works:

![image](https://github.com/llvm/llvm-project/assets/8676443/5f6736a2-3e92-452d-95a5-e9d8278a8e6b)

**Comment by namazso** [comment]
The solution would be either getting rid of the stride, or adding it to the cf table too.

**Comment by namazso** [comment]
Simply removing the `true` seems to fix it:

![image](https://github.com/llvm/llvm-project/assets/8676443/4262984e-2114-472a-a547-0d14d8e54ead)


I verified that the extra byte is

- always set to 0 by clang
- ignored by Windows

I assume someone just looked at a Windows binary, which has a stride of `1` because XFG contents in the CF table require that extra byte, and as a sideeffect the EHcont table also has the same stride.

**Comment by namazso** [comment]
/cherry-pick e335c78ec2848e24b10e32e015a84347c69c8130 f11f90d5f4ebfab2b44bf3c98b2d2162acf81e2c

**Comment by EugeneZelenko** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/e335c78ec2848e24b10e32e015a84347c69c8130 https://github.com/llvm/llvm-project/commit/f11f90d5f4ebfab2b44bf3c98b2d2162acf81e2c
