### ISSUE TITLE
Failure to fold comparison implication in and chain

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#64583]
Consider the following two functions:
```cpp
bool foo(int a, int b, int c)
{
    return ((a < b) && (b < c)) && (a < c);
}

bool bar(int a, int b, int c)
{
    return (a < b) && (b < c);
}
```

Clang performs three comparison instructions in `foo`, while GCC performs only two comparison instructions in both `foo` and `bar`.

Godbolt:
https://godbolt.org/z/485TMGbGv

**Comment by nikic** [comment]
Missing transform: https://alive2.llvm.org/ce/z/KswM8y

ConstraintElim current doesn't handle implication from multiple conditions in `and`. cc @fhahn 

Worth noting that the transform doesn't actually verify if undef values are allowed.

**Comment by Kmeakin** [comment]
Some more examples in https://github.com/llvm/llvm-project/issues/57506

**Comment by k-arrows** [comment]
> Some more examples in #57506

Thanks for letting me know this. This issue of mine is just a duplicate of　your original issue. I will close this issue.
