### ISSUE TITLE
add check which generates parameter comment fix-its in calls with easily swappable parameters

### ISSUE THREAD

**Issue by firewave** [llvm/llvm-project#64618]
Similar to `bugprone-easily-swappable-parameters` but to help with the call site in case the API cannot be changed.

```cpp
void cb(int in, int out, int swap);

void f()
{
    cb(0, 1, 0);
    cb(/*in*/ 0, /*out*/ 1, /*swap*/ 0);
}
```

Some IDEs offers that information as inline hints.

**Comment by tbaederr** [comment]
And this is about clang-tidy? Or something else?

**Comment by PiotrZSL** [comment]
There is actually check that does that, it's called bugprone-argument-comment.
https://clang.llvm.org/extra/clang-tidy/checks/bugprone/argument-comment.html

```
-checks=-*,bugprone-argument-comment --config="{CheckOptions: {bugprone-argument-comment.CommentIntegerLiterals: true}}"

-checks=-*,bugprone-argument-comment --config="{CheckOptions: {bugprone-argument-comment.CommentIntegerLiterals: true}}"
[<source>:5:8: warning: argument comment missing for literal argument 'in' [bugprone-argument-comment]](javascript:;)
    5 |     cb(0, 1, 0);
      |        ^
      |        /*in=*/
[<source>:5:11: warning: argument comment missing for literal argument 'out' [bugprone-argument-comment]](javascript:;)
    5 |     cb(0, 1, 0);
      |           ^
      |           /*out=*/
[<source>:5:14: warning: argument comment missing for literal argument 'swap' [bugprone-argument-comment]](javascript:;)
    5 |     cb(0, 1, 0);
      |              ^
      |              /*swap=*/
3 warnings generated.
```

https://godbolt.org/z/f8xMxPer7

**Comment by PiotrZSL** [comment]
"check does nothing unless it is configured."
By default it only validate if names are correct.

Is this check sufficient for you ?

**Comment by firewave** [comment]
> "check does nothing unless it is configured."
> By default it only validate if names are correct.

Missed that, too. Sorry about that.

> Is this check sufficient for you ?

Obviously, yes. Closing.
