### ISSUE TITLE
CMake build file generation fails: Cross compile lldb-server for armv7

### ISSUE THREAD

**Issue by dprogm** [llvm/llvm-project#64616]
**Goal:** Compile `lldb-server` for an armv7 target machine according to [this guide](https://lldb.llvm.org/resources/build.html#cross-compiling-lldb).

**Steps to reproduce:**

**(1)** Build `llvm-tblgen` and `clang-tblgen` for the host platform

```bash
cd llvm-project
mkdir host_build && cd host_build
cmake -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_BUILD_TYPE=Release -G Ninja ../llvm
ninja clang-tblgen llvm-tblgen
```

**(2)** Configure `lldb` for the target platform (also had to add `clang` and `-DLLDB_INCLUDE_TESTS=0`)

```bash
cd llvm-project
mkdir target_build && cd target_build
cmake -DLLVM_ENABLE_PROJECTS="clang;lldb" \
-DCMAKE_BUILD_TYPE=Release \ 
-DCMAKE_CROSSCOMPILING=1 \ 
-DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc \ 
-DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ \ 
-DLLVM_HOST_TRIPLE=armv7-unknown-linux-gnueabihf \
-DLLVM_TABLEGEN=../host_build/bin/llvm-tblgen \ 
-DCLANG_TABLEGEN=../host_build/bin/clang-tblgen \ 
-DLLDB_ENABLE_PYTHON=0 \
-DLLDB_ENABLE_LIBEDIT=0 \
-DLLDB_ENABLE_CURSES=0 \
-DLLDB_INCLUDE_TESTS=0 \
-G Ninja ../llvm
```

**CMake throws the error:**

```bash
  "llvm-tblgen" of type EXECUTABLE
    depends on "LLVMCodeGenTypes" (weak)
    depends on "LLVMTableGenGlobalISel" (weak)
    depends on "intrinsics_gen" (strong)
  "LLVMTableGenGlobalISel" of type STATIC_LIBRARY
    depends on "LLVMCodeGenTypes" (weak)
    depends on "vt_gen" (strong)
  "vt_gen" of type UTILITY
    depends on "llvm-tblgen" (strong)
  "intrinsics_gen" of type UTILITY
    depends on "llvm-tblgen" (strong)
  "LLVMCodeGenTypes" of type STATIC_LIBRARY
    depends on "vt_gen" (strong)
```

Also tried to set `-DBUILD_SHARED_LIBS=OFF`, but nothing changed. Compilation for the host platform works as expected.

**Comment by DavidSpickett** [comment]
I do a similar thing regularly for X86 -> AArch64, but our commands do differ slightly. Can you tell us what commit of llvm-project you're using?

**Comment by dprogm** [comment]
I was building from something around f36e909da03767c317eaa5ded9abbf3214299ff5 but I have no access right now to check it. I will try to reproduce it on my machine at home.

**Comment by DavidSpickett** [comment]
Ok so very very recent, that's enough to go on. I'll try to reproduce it myself next week.

**Comment by dprogm** [comment]
Okay, thank you. I was able to reproduce it with:
```bash
arm-linux-gnueabihf-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
at 2fb4bfa5ba972bf074bea8a89590171979055a41

**Comment by DavidSpickett** [comment]
Well I have some differences from your setup, and can't test the linked commit right now but I expect it would be fine with what I use.

I use this script to configure:
```
set -ex

cd /work/open_source/lldb-cross-compile/build-cross

BUILD_TYPE=Debug
LLDB_TARGET_ARCH=AArch64
LLDB_HOST_TRIPLE=aarch64-unknown-linux-gnu
C_COMPILER=$LLDB_HOST_TRIPLE-gcc
CXX_COMPILER=$LLDB_HOST_TRIPLE-g++
LLVM_SRC_DIR=/work/open_source/lldb-cross-compile/llvm-project/llvm
LLVM_HOST_BUILD_DIR=/work/open_source/lldb-cross-compile/build-host/

cmake -G Ninja \
  -DCMAKE_SYSTEM_NAME=Linux \
  -DCMAKE_SYSTEM_PROCESSOR=AArch64 \
  -DCMAKE_C_COMPILER=$C_COMPILER \
  -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
  -DCMAKE_C_COMPILER_LAUNCHER=ccache \
  -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
  -DLLVM_NATIVE_TOOL_DIR=$LLVM_HOST_BUILD_DIR/bin \
  -DLLVM_HOST_TRIPLE=$LLDB_HOST_TRIPLE \
  -DLLVM_TARGETS_TO_BUILD=$LLDB_TARGET_ARCH \
  -DCMAKE_IGNORE_PATH=/usr/lib/$BUILD_ENV_TRIPLE \
  -DLLVM_ENABLE_PROJECTS="clang;lldb" \
  -DCMAKE_LIBRARY_ARCHITECTURE=$LLDB_HOST_TRIPLE \
  -DLLDB_TEST_COMPILER=$(which $LLDB_HOST_TRIPLE-gcc) \
  -DLLDB_EXPORT_ALL_SYMBOLS=ON \
  -DLLVM_ENABLE_ASSERTIONS=On \
  -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
  -DLLDB_ENABLE_PYTHON=OFF \
  -DLLDB_ENABLE_LIBEDIT=OFF \
  -DLLDB_ENABLE_CURSES=OFF \
  -DLLVM_PARALLEL_LINK_JOBS=4 \
  -DLLVM_USE_LINKER=lld \
  $LLVM_SRC_DIR
```
And my host build was just `ninja` so it includes everything. I don't think that should matter though. `DLLVM_NATIVE_TOOL_DIR` stands out as something that might help, if these dependencies are also host tools, I couldn't work out what they were exactly.

If you want to substitute in the armv7 equivalents and try that, I'd be interested to know if it works. I think it's time I went through that page and modernised the cmake options, though I don't immediately see why they wouldn't work.

**Comment by dprogm** [comment]
I was trying to use the command you provided and applied the following steps:

1) Building the whole clang project for the host platfrm didn't help
2) Adding `DLLVM_NATIVE_TOOL_DIR` didn't help
3) Adding the following flags didn't help
    * `-DCMAKE_SYSTEM_PROCESSOR=armv7`
    * `-DLLVM_TARGETS_TO_BUILD=armv7` **(*)**
    * `-DCMAKE_LIBRARY_ARCHITECTURE=armv7-unknown-linux-gnueabihf `
    * `-DLLDB_EXPORT_ALL_SYMBOLS=ON`
    * `-DLLVM_ENABLE_ASSERTIONS=ON`

**(*) throws:**
```bash
CMake Error at CMakeLists.txt:929 (message):
  The target `armv7' is experimental and must be passed via
  LLVM_EXPERIMENTAL_TARGETS_TO_BUILD.
```
Therefore used `-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=armv7` instead, which throws:
```bash
CMake Error at lib/Target/CMakeLists.txt:36 (add_subdirectory):
  add_subdirectory given source "armv7" which is not an existing directory.
```
Therefore used `-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=ARM` instead, which throws the initial error.

Maybe armv7 is not supported?

**Comment by dprogm** [comment]
**Update:** switched to release `llvmorg-16.0.6`

Here build file generation succeeds with the commands provided in https://github.com/llvm/llvm-project/issues/64616#issue-1846738375 but compilation fails. It tries to use `lldb-tblgen` from the target build which obviously fails on the host platform. Therefore added lldb for the host build and compile lldb-tblgen, then passing it in the target build via `-DLLDB_TABLEGEN=../host_build/bin/lldb-tblgen` seems to work.

**BUT:** Then it's not able to link the executable for armv7 because:
```bash
/usr/lib/x86_64-linux-gnu/libxml2.so: file not recognized: file format not recognized
```
So it is using some host dependency.

**Comment by dprogm** [comment]
**Update:** After setting `-DLLDB_ENABLE_LIBXML2=OFF` it successfully compiles! Not sure if `-DLLVM_ENABLE_LIBXML2=OFF` is also necessary.

**Summary:**
* There are some more flags necessary to cross-compile `lldb-server` 
* There is possibly a regression that causes build file generation to fail

**Comment by DavidSpickett** [comment]
> Maybe armv7 is not supported?

This Arm's quirky naming schemes. In llvm, 32 bit Arm aka Armv7 or Armv8 32 bit (aka AArch32) is called ARM (see llvm/lib/target/ARM). So you want `=ARM`. The error message is misleading because it assumes anything not recognised for enable targets must be an experimental target, when most of the time it's a typo.

> Here build file generation succeeds with the commands provided in https://github.com/llvm/llvm-project/issues/64616#issue-1846738375 but compilation fails. It tries to use lldb-tblgen from the target build which obviously fails on the host platform.

`LLVM_NATIVE_TOOL_DIR` is supposed to help this situation by providing one setting for all the host tools. This is probably one bit where me having built lldb in the host build helped my config work.

> Update: After setting -DLLDB_ENABLE_LIBXML2=OFF it successfully compiles! Not sure if -DLLVM_ENABLE_LIBXML2=OFF is also necessary. But I guess it is possible to set some paths to point to the correct cross-compiled libraries.

I'd guess that the autodetection for libXML found the host's libXML instead. I'm surprised my setup isn't doing that, but maybe it's just a tiny bit more isolated so it can't find the files.

**Comment by DavidSpickett** [comment]
> CMake Error at CMakeLists.txt:929 (message):
>  The target `armv7' is experimental and must be passed via
>  LLVM_EXPERIMENTAL_TARGETS_TO_BUILD.

https://reviews.llvm.org/D157844 to improve this situation.

**Comment by dprogm** [comment]
> This Arm's quirky naming schemes. In llvm, 32 bit Arm aka Armv7 or Armv8 32 bit (aka AArch32) is called ARM (see llvm/lib/target/ARM). So you want `=ARM`. The error message is misleading because it assumes anything not recognised for enable targets must be an experimental target, when most of the time it's a typo.

Thanks for clarification. This is what I was assuming after looking into the sources and set it to `=ARM`.

For now it is working for me with an official release, but the issues (at least not being able to build it) mentioned in https://github.com/llvm/llvm-project/issues/64616#issuecomment-1676380257 remain I guess.

**Comment by DavidSpickett** [comment]
I've put up https://reviews.llvm.org/D158085 which has the "recommended" way of cross compiling (by me and CMake itself). I've tested that for X86 -> AArch64 builds.

If you could read that new version, try the commands out if you can and tell me if that A: works for you and B: would have been helpful to you if they were there in the first place. For example, are there any missing details that would be worth mentioning, etc.

Commenting on Phabricator is great, but otherwise here is fine. Then I'll apply your feedback to the patch.

**Comment by dprogm** [comment]
@DavidSpickett Thanks, I will check if the recommended way is working for armv7 as well and give feedback.

**Comment by dprogm** [comment]
@DavidSpickett The recommended way is working fine for armv7.
But it is only properly working when applying the following arguments:
*  You have to add clang to the projects, e.g. `-DLLVM_ENABLE_PROJECTS="lldb;clang"`. This is something I would not expect if I just want to compile `lldb-server`
* Maybe add a note about `-DLLDB_INCLUDE_TESTS=0` because without it is complaining about `LLDB test compiler not specified.  Tests will not run.`
* Maybe add a note that also the host version of `lldb-tblgen` is required for cross compilation
* Maybe add a note about disabling libraries not available for the cross platform, e.g. `-DLLVM_ENABLE_LIBXML2=OFF`

But in general it is working fine. :wink: Thanks

**Comment by DavidSpickett** [comment]
I did think about putting the whole command there not just the additions, saves people reading the whole doc doesn't it.

Good suggestions, yeah maybe some are covered if we want to be super specific, but people shouldn't have to pour over it with a fine tooth comb. I'll be updating the patch.

**Comment by dprogm** [comment]
**There is one typo in my comment:** Instead of `-DLLVM_ENABLE_LIBXML2=OFF` it must be `-DLLDB_ENABLE_LIBXML2=OFF`
Also note that when using latest commit it is not necessary anymore to build `lldb-tblgen` separately because it is apparently built automatically, I was seeing this line when cross compiling:
`Building native lldb-tblgen..`
This was not the case in release 16.

**Comment by DavidSpickett** [comment]
Something is trying to be helpful but sneaky about it.

I'll check it out once I've got the first set of documentation updates in.

**Comment by DavidSpickett** [comment]
I've integrated your suggestions into the new docs. I'm going to commit them as is and then...

> I was seeing this line when cross compiling: Building native lldb-tblgen..

Yeah if I leave out the native tools setting it appears that we'll build a native set of tools for you to use in the cross build. I'll see how this works and simplify the docs even more if we can.

**Comment by DavidSpickett** [comment]
The linked commit fixes the documentation and includes your feedback, thanks again for the report.

The instructions are not as simple as they could be, so I'll be making some more updates later. What you have now is fine though no need to change.
