### ISSUE TITLE
Missing diagnostic for non-standard layout types in `offsetof`

### ISSUE THREAD

**Issue by Endilll** [llvm/llvm-project#64619]
Consider the following example (https://godbolt.org/z/o77v1nad9):
```cpp
struct X1 { int a; };
struct X2 { int b; };
struct Y : X1, X2 {};

static_assert(__builtin_offsetof(Y, b) == 4);
static_assert(offsetof(Y, b) == 4);

static_assert(!std::is_standard_layout_v<Y>, "");
```
Only GCC warns that non-standard layout type is passed to `offsetof`, which is [conditionally-supported](http://eel.is/c++draft/support.types.layout#1.sentence-2).
```
<source>:8:34: warning: 'offsetof' within non-standard-layout type 'Y' is conditionally-supported [-Winvalid-offsetof]
    8 | static_assert(__builtin_offsetof(Y, b) == 4);
      |               ~~~~~~~~~~~~~~~~~~~^~~~~
In file included from /opt/compiler-explorer/gcc-trunk-20230811/include/c++/14.0.0/cstddef:50,
                 from <source>:1:
<source>:9:24: warning: 'offsetof' within non-standard-layout type 'Y' is conditionally-supported [-Winvalid-offsetof]
    9 | static_assert(offsetof(Y, b) == 4);
      |                        ^
```
GCC issues it by default, whereas Clang, MSVC, and EDG doesn't even in pedantic modes (or `/W4`).

I'm not sure what the solution should be, but I feel like there is a problem to solve.

**Comment by Endilll** [comment]
CC @AaronBallman 
This might be a good first issue, depending on how we're going to resolve this.

**Comment by cor3ntin** [comment]
We only warn in evaluated context. I don't know if that make sense https://godbolt.org/z/MGTWofPxY
Maybe we don't want to use `DiagRuntimeBehavior` here

**Comment by AaronBallman** [comment]
> We only warn in evaluated context. I don't know if that make sense https://godbolt.org/z/MGTWofPxY Maybe we don't want to use `DiagRuntimeBehavior` here

It's been this way since it was added in 882211c1da17254908e6b36d6e5d4e425f224347 in 2010. That said, I'm not certain why this should be issued only when evaluated at runtime. My *guess* is that it's a runtime diagnostic because the offset is expected to be used at runtime to offset into some memory buffer; so if you never reach that code, the fact that it's conditionally supported doesn't matter. But I'm not certain if that's an accurate guess -- I could not find a code review to see if this was explicitly discussed.

**Comment by cor3ntin** [comment]
I can see that reasoning be problematic, for example:

```void f() {
   constexpr auto idx = offsetof(nontrivial, foo); 
   loose_a_limb(idx);
}```

**Comment by AaronBallman** [comment]
Yeah, basically 2010 predates thinking about `constexpr` too much, so this might have made more sense then and less sense now.

**Comment by kasuga-fj** [comment]
Thank you
