### ISSUE TITLE
Miscompile with attributor-light and dse

### ISSUE THREAD

**Issue by bevin-hansson** [llvm/llvm-project#64613]
In the following case, running `attributor-light` followed by `dse` results in a miscompilation:
```
define dso_local ptr @fun(ptr noundef %p) {
entry:
  %p.addr = alloca ptr, align 1
  store ptr %p, ptr %p.addr, align 1
  %0 = load ptr, ptr %p.addr, align 1
  ret ptr %0
}

define dso_local i16 @test_it() {
entry:
  %x = alloca i16, align 1
  %p = alloca ptr, align 1
  call void @llvm.lifetime.start.p0(i64 2, ptr %x)
  store i16 42, ptr %x, align 1
  call void @llvm.lifetime.start.p0(i64 2, ptr %p)
  %call = call ptr @fun(ptr noundef %x)
  store ptr %call, ptr %p, align 1
  %0 = load ptr, ptr %p, align 1
  %1 = load i16, ptr %0, align 1
  %cmp = icmp eq i16 %1, 42
  %conv = zext i1 %cmp to i16
  call void @llvm.lifetime.end.p0(i64 2, ptr %p)
  call void @llvm.lifetime.end.p0(i64 2, ptr %x)
  ret i16 %conv
}

declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)

declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)
```
Executing `opt -passes='attributor-light,function(dse)' repr.ll` produces an IR where the `store i16 42` is eliminated, but the store is not dead.

**Comment by nikic** [comment]
attributor-light infers that the argument of `@fun` is nocapture, which is incorrect (it is returned).

cc @fhahn @jdoerfert

**Comment by bjope** [comment]
Adding some more info:
IIUC, what happens is that attributor is deriving `nocapture `for `%p` in `@fun`.

Normally opt would reduce  `@fun` to just return `%p`, eliminating the copying via stack. But if the pointer is returned, then it outlives the function and thus it is captured given by the LangRef statement "Given a function call and a pointer that is passed as an argument or stored in the memory before the call, a pointer is captured by the call if it makes a copy of any part of the pointer that outlives the call.".

So I guess that somehow the attributor isn't realizing that the pointer is loaded back from the stack and being returned.

**Comment by jdoerfert** [comment]
Attributor knows it is returned:
```
; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef ptr @fun(ptr nofree noundef readnone returned %p) #0 {
```
But light does not:
```
; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local ptr @fun(ptr nocapture nofree noundef %p) #0 {
```
Checking now. Probably an implicit assumption about the AAs we run.
