### ISSUE TITLE
CTAD for Aggregates with Elements of Array Type of Known Array Size Fails Without Brace Elision

### ISSUE THREAD

**Issue by freaknbigpanda** [llvm/llvm-project#64625]
This feature landed here: https://reviews.llvm.org/D139837

Clang failure example: https://godbolt.org/z/YjWx3ohxK
Note that this example compiles with brace elision: https://godbolt.org/z/avadhafTY
GCC compiles the example as expected: https://godbolt.org/z/5d3PehGo3

Please see the following document: http://wg21.link/P2082R1 section 3.2 "Allow brace elision if array size is known" for more information

**Comment by shafik** [comment]
CC @yuanfang-chen
