### ISSUE TITLE
[MLIR][Python Bindings] No `.owner` for empty result

### ISSUE THREAD

**Issue by zzzDavid** [llvm/llvm-project#64630]
In MLIR Python binding, if an operation has empty results list, the empty result list has not `.owner` object. For example:
```
linalg_copy = linalg.copy(in, outs=[...], loc=loc, ip=ip)
```
`linalg_copy` is an empty `OpResultList`, and it does not have access to its `.owner` object, so there is no way to access the created operation through its results.

@makslevental

**Comment by makslevental** [comment]
https://github.com/llvm/llvm-project/commit/6e4ea4eeba50d99e822015e42aba22b2c5a880ca fixes
