### ISSUE TITLE
[remark] the pass-analysis result inconsistent with the input source

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#64637]
* test: https://gcc.godbolt.org/z/YrKnWcG3h
```
void foo (int *restrict y, int *restrict x, int *restrict indices, int n) {
  for (int k = 0; k < 10; k++) {
    #pragma loop distribute(enable)
    for (int i = 0; i < n; i++) {
      y[i + k * M] = y[i + k* M] + 1;
      y[i + k * (M+1)] = indices[i] + 2;
    }
  }
}
```
* As you see, I already add **#pragma loop distribute(enable)** in the input source, but the **-Rpass-analysis** still report that 
**\<source>:8:24: remark: loop not vectorized: unsafe dependent memory operations in loop. Use #pragma loop distribute(enable) to allow loop distribution to attempt to isolate the offending operations into a separate loop**

**Comment by fhahn** [comment]
It looks like this is a case where the remark/debug output of the remark could be improved. It would need to check if the loop-distribute metadata is already attached to the loop and not mention it if it is.

Should be straight-forward to change in case anybody is interested in tackling this. The remark is emitted here: https://github.com/llvm/llvm-project/blob/main/llvm/lib/Analysis/LoopAccessAnalysis.cpp#L2465

**Comment by vfdff** [comment]
Thanks for your suggestion, I add a  candidate MR: https://reviews.llvm.org/D158856
