### ISSUE TITLE
C++20 std::move(ss).str() first copies and then delete the original string instead of moving it

### ISSUE THREAD

**Issue by AMP999** [llvm/llvm-project#64644]
https://godbolt.org/z/44Ke34fGz
```cpp
std::stringstream ss("a very long string that exceeds the small string optimization buffer length");
const char *p = ss.view().data();
std::string s = std::move(ss).str();
assert(s.data() == p); // shouldn't be a second allocation
```
In C++20 and later, moving-out-of `ss` should move the string, not make a fresh copy.

**Comment by AMP999** [comment]
Fixed by https://reviews.llvm.org/D157776

**Comment by PeterSommerlad** [comment]
As the author of P0408 I strongly support the view of the issue author. While not 100% mandated, since a copy is also a move, copying instead of moving is a very bad QOI of str()&&

**Comment by philnik777** [comment]
> As the author of P0408 I strongly support the view of the issue author. While not 100% mandated, since a copy is also a move, copying instead of moving is a very bad QOI of str()&&

The discussion we're having isn't about whether this is a good idea to implement. I think we all agree that it is. The question is whether this should be classified as mandatory behaviour or not. IIUC you agree that this is not mandated. In that case we should classify the tests for this as libc++-specific, since any other tests have should pass on every conforming implementation.

**Comment by PeterSommerlad** [comment]
I rechecked the standard text, and taking [container.reqmts] p.16, and the fact that basic_string is a contiguous/sequence container to [basic.string.general] the "A basic_string<charT, traits, Allocator> object move constructed from the basic_- stringbuf’s underlying character sequence in buf" guarantees that it is O(1). So a copy taking place is actually a bug.

**Comment by AMP999** [comment]
Fixed by https://github.com/llvm/llvm-project/pull/67294
