### ISSUE TITLE
[libc++] `__throw_bad_function_call` should be opaque

### ISSUE THREAD

**Issue by Eisenwave** [llvm/llvm-project#64662]
https://github.com/llvm/llvm-project/blob/a7d80c50aa9121bff08d59ab4c4d7210dd2400f9/libcxx/include/__functional/function.h#L75-L83

This function should ideally be made opaque and marked `cold` and `noinline`, since throwing exceptions is meant to be expensive and unusual anyway. Having the definition visible results in every TU compiling its own constructor, destructor, RTTI, etc. of `std::bad_function`, and compiling its own definition of `__throw_bad_function_call`.

The [libstdc++ counterpart](https://github.com/gcc-mirror/gcc/blob/25be11e982c76200fabb375c8c63eff8c6856980/libstdc%2B%2B-v3/include/bits/functexcept.h#L114C10-L114C10) is marked `cold`, and is opaque.
```cpp
  void
  __throw_bad_function_call() __attribute__((__noreturn__,__cold__));
  ```

**Comment by philnik777** [comment]
Do you have any example where `__throw_bad_function_call()` is inlined? I can't get clang to inline it: https://godbolt.org/z/63aq1YbYx

**Comment by Eisenwave** [comment]
> Do you have any example where `__throw_bad_function_call()` is inlined?

Actually I don't, though the motivating example is this: https://godbolt.org/z/3e8zG967T. Upon closer inspection, the problem is merely that `std::bad_function_call` with its vtable, destructor, etc. is emitted into every TU. Since all those symbols are weak, the linker should figure it out in the end.

However, it's still a downgrade in compilation speed, however small, if the definition of `__throw_bad_function_call()` is visible and needs to get compiled by every TU, instead of just being somewhere in libc++.

**Comment by philnik777** [comment]
I don't think it's worth it to move `__throw_bad_function_alloc()` for that into the dylib. These are just a few lines of code, and moving it doesn't even help with the weak symbols from `bad_function_call`. The `bad_function_call` symbols aren't weak anymore in the unstable ABI: https://godbolt.org/z/MebWa7h9P
