### ISSUE TITLE
OpenMP parallel reduction gives wrong result with clang on Windows

### ISSUE THREAD

**Issue by annop-w** [llvm/llvm-project#64693]
Compiling this program with clang++ -fopenmp -O3 prints wrong result for some number of OMP_NUM_THREADS.
```
#include <iostream>
int main () {
        double sum = 0.0;
#pragma omp parallel for default(none) reduction(+:sum)
        for (int i = 0; i < 1000; ++i) {
                sum += 1.0;
        }
        std::cout << sum << std::endl;
        return 0;
}
```

```
# clang++ --version
clang version 16.0.0
Target: aarch64-pc-windows-msvc
Thread model: posix
```

**Comment by shiltian** [comment]
What are those `OMP_NUM_THREADS` numbers when the results are wrong?

**Comment by annop-w** [comment]
Hmm, I'm no longer able to reproduce this error.

**Comment by shiltian** [comment]
> Hmm, I'm no longer able to reproduce this error.

Okay. I'll close this issue for now. Feel free to reopen it if the issue appears again.
