### ISSUE TITLE
build the executable file with --fsanitize=memtag failed 

### ISSUE THREAD

**Issue by zintown** [llvm/llvm-project#64692]
I used clang to compile programs with memtag sanitizer on Arm v8.9-a fvp with MTE hardware mechanism enabled.
Compiling and linking the target file failed, but the two steps of compiling and linking can generate the target file
`clang++-17 --target=aarch64-linux -march=armv8.5-a+memtag  -fsanitize=memtag-stack,memtag-heap 2.cpp -O0` failed with this output:
`clang++-17: error: unsupported option '-fsanitize=memtag*' for target 'aarch64-unknown-linux'`
But if I try to make middle object file instead of final executable file by the command `clang++-17 --target=aarch64-linux -march=armv8.5-a+memtag  -fsanitize=memtag-stack,memtag-heap -c 2.cpp -O0`, and link it with `clang++-17 -o 2 2.o -fuse-ld=lld`.
the build process is successful.
Is there a problem with target checking in Clang, or I misused the memtag sanitizer option?

**Comment by MaskRay** [comment]
Right now `-fsanitize=memtag` is only supported for Android. https://source.android.com/docs/security/test/memory-safety/arm-mte I think after more extensive experience we will get it on regular Linux:)

**Comment by red-avalanche** [comment]
@vitalybuka Is the memtag feature in such a state that we can look into bringing this to Linux targets? Do you know what it would take to get it working on Linux?

**Comment by DavidSpickett** [comment]
Since https://github.com/llvm/llvm-project/commit/ebd62d652c4a6537ad0dbdb37f449e8cdf821ffb, the compile command now works:
```
$ ./bin/clang --target=aarch64-linux-gnu -march=armv8.5-a+memtag -fsanitize=memtag-stack,memtag-heap /tmp/test.cpp -O0 -fuse-ld=lld -o /tmp/test.o
```
And I do see MTE instructions and annotations in there, which suggests that it is "supported" to some extent.

However the commit says:
> With these generic flags, the linker will emit only the dynamic array tags specified in the **"Memtag ABI Extension to ELF"**, but no Android-specific memtag note.

Which does not necessarily mean Linux is supported. @EliaGeretto is it correct to say that there are still no plans for Linux support at this time? (at least from your perspective)

**Comment by EliaGeretto** [comment]
> Since [ebd62d6](https://github.com/llvm/llvm-project/commit/ebd62d652c4a6537ad0dbdb37f449e8cdf821ffb), the compile command now works:
> 
> ```
> $ ./bin/clang --target=aarch64-linux-gnu -march=armv8.5-a+memtag -fsanitize=memtag-stack,memtag-heap /tmp/test.cpp -O0 -fuse-ld=lld -o /tmp/test.o
> ```
> 
> And I do see MTE instructions and annotations in there, which suggests that it is "supported" to some extent.
> 
> However the commit says:
> 
> > With these generic flags, the linker will emit only the dynamic array tags specified in the **"Memtag ABI Extension to ELF"**, but no Android-specific memtag note.
> 
> Which does not necessarily mean Linux is supported. [@EliaGeretto](https://github.com/EliaGeretto) is it correct to say that there are still no plans for Linux support at this time? (at least from your perspective)

Hi, sorry for the late reply, I missed the notification. I am working on this for bare metal at the moment, so I haven't looked into Linux support. However, when compiling for Linux, the implementation follows the [Memtag ABI extension for ELF by ARM](https://github.com/ARM-software/abi-aa/blob/main/memtagabielf64/memtagabielf64.rst). This is currently in alpha state, but the compiler side should work correctly. For Linux support, I assume what is currently missing is support in the loader. The ELF emitted by clang should already be fine.

**Comment by EliaGeretto** [comment]
> > Do you know what it would take to get it working on Linux?
> 
> Discussion is ongoing related to the Memtag ABI and the [SYSV](https://github.com/ARM-software/abi-aa/issues/382) parts of that we need for Linux.

Ah, I see changes have already been requested. Thanks for linking this.

**Comment by DavidSpickett** [comment]
> I am working on this for bare metal at the moment, so I haven't looked into Linux support.

Thanks. Our main worry was that you had a whole scheme implemented and we didn't want to end up with multiple standards.

Feel free to get involved anyway if you have requests.
