### ISSUE TITLE
[clang cfg] BinaryOperators built in wrong order for CFG

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#6469]
|  |  |
| --- | --- |
| Bugzilla Link | [6097](https://llvm.org/bz6097) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @tkremenek |

## Extended Description 
$ cat t5.c
int foo1();
int foo2();
int main() {
  return foo1() + foo2();
}
mrs $ clang -cc1 -analyze -cfg-dump -fexceptions  t5.c

 [ B4 (ENTRY) ]
    Predecessors (0):
    Successors (1): B3

 [ B1 ]
      1: return [B2.1] + [B3.1];
    Predecessors (1): B2
    Successors (1): B0

 [ B2 ]
      1: foo1()
    Predecessors (1): B3
    Successors (2): B1 B0

 [ B3 ]
      1: foo2()
    Predecessors (1): B4
    Successors (2): B2 B0

 [ B0 (EXIT) ]
    Predecessors (3): B1 B2 B3
    Successors (0):
$ clang -S t5.c
$ grep foo t5.s
	callq	_foo1
	callq	_foo2

Order should be B4 -> B2 -> B3 -> B1.

**Comment by JOE1994** [comment]
With Clang trunk (`056d62be38c5db3d8332ac300c4ff29214126697`),
`clang -cc1 -analyze -analyzer-checker=debug.DumpCFG  -fexceptions t5.c` outputs the following:

```
int main()
 [B2 (ENTRY)]
   Succs (1): B1

 [B1]
   1: foo1
   2: [B1.1] (ImplicitCastExpr, FunctionToPointerDecay, int (*)())
   3: [B1.2]()
   4: foo2
   5: [B1.4] (ImplicitCastExpr, FunctionToPointerDecay, int (*)())
   6: [B1.5]()
   7: [B1.3] + [B1.6]
   8: return [B1.7];
   Preds (1): B2
   Succs (1): B0

 [B0 (EXIT)]
   Preds (1): B1
```

In `[B1]`, call to `foo1` appears first, and then the call to `foo2` follows
(LHS of `+` operator evaluated first).
