### ISSUE TITLE
[clang-format] Segmentation fault when formatting nested namespaces

### ISSUE THREAD

**Issue by d0nc1h0t** [llvm/llvm-project#64701]
When formatting this part of the code:
```
namespace ns1 { namespace ns2 { namespace ns3 {

void func_in_ns() {
    int res{ 0 };
// block for debug mode
#ifndef NDEBUG

#endif
}

}}}
```

with the following style settings:
```
---
Language:        Cpp
BasedOnStyle:  LLVM

CompactNamespaces: true
NamespaceIndentation: Inner
```
clang-format crashes with an error segmentation fault. As I found out, this is due to the overflow of the Level value for the comment line.  Overflow occurs in line 393 of the file clang/lib/Format/UnwrappedLineFormatter.cpp:
```
    ...
            if (!(*CompactedLine)->InPPDirective)
              (*CompactedLine)->Level -= OutdentBy;
    ...
```
OutdentBy turns out to be greater than the value (*CompactedLine)->Level, which causes an overflow.
I see the following way to solve the problem:
```
    ...
            if (!(*CompactedLine)->InPPDirective)
              (*CompactedLine)->Level -= std:min(OutdentBy, (*CompactedLine)->Level);
    ...
```

**Comment by owenca** [comment]
> OutdentBy turns out to be greater than the value (*CompactedLine)->Level, which causes an overflow. I see the following way to solve the problem:
> 
> ```
>     ...
>             if (!(*CompactedLine)->InPPDirective)
>               (*CompactedLine)->Level -= std:min(OutdentBy, (*CompactedLine)->Level);
>     ...
> ```

This seems to work. Can you submit a patch at https://reviews.llvm.org?

Tagging @rymiel.

**Comment by d0nc1h0t** [comment]
Submit [patch D158363](https://reviews.llvm.org/D158363).
