### ISSUE TITLE
LLVM17: Missing release note

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#64709]
When testing LLVM17-RC2, I got the following warning on an external library (compiled using clang-cl with c++17):
````
error: 'dllimport' attribute only applies to functions, variables, classes, and Objective-C interfaces [-Werror,-Wignored-attributes]
````
The code:
````
#define EXPORT_OPENTELEMETRYLIB __declspec(dllimport)
using MeterDeleter = EXPORT_OPENTELEMETRYLIB void (*)(IMeter* ptr);
````
Reading through the release notes (https://github.com/llvm/llvm-project/blob/release/17.x/clang/docs/ReleaseNotes.rst), I don't see any mention of changes to this warning becoming more strict. It does mention:

- > __declspec attributes can now be used together with the using keyword. Before the attributes on __declspec was ignored, while now it will be forwarded to the point where the alias is used.
   - Seems to imply this is allowed at more places instead of less
- > Fixed a bug where attribute annotations on type specifiers (enums, classes, structs, unions, and scoped enums) were not properly ignored, resulting in misleading warning messages. Now, such attribute annotations are correctly ignored. (https://github.com/llvm/llvm-project/issues/61660)
   - Linked to the same working, though also seems to imply it is reported less instead of more

**Comment by tru** [comment]
@rnk @zmodem is this this something we should fix for 17.x?

**Comment by tru** [comment]
Oh yeah - I reviewed way too many issues this morning. The title even refers to fixing the release note. Sorry about the noise. 

@AaronBallman, since you did the change and the original release note, what do you think?

**Comment by AaronBallman** [comment]
I think fixing up the release note is the correct approach. Maybe something along the lines of "Note, some incorrect uses of __declspec on a using declaration were being silently ignored and will now be appropriately diagnosed as ignoring the attribute." ?

**Comment by zmodem** [comment]
> Maybe something along the lines of "Note, some incorrect uses of __declspec on a using declaration were being silently ignored and will now be appropriately diagnosed as ignoring the attribute." ?

sgtm!

**Comment by tru** [comment]
Can someone submit a fix for the release notes?
