### ISSUE TITLE
[RISC-V] Unexpected registers in extended inline asm

### ISSUE THREAD

**Issue by lekcyjna123** [llvm/llvm-project#64700]
Hi,

I currently play around with kernels to test my RISC-V processor and I have found an behaviour which is unexpected for me. I have created small code sample:

```c
int main()
{
  unsigned int LEN = 4;
  unsigned int tab[] = {0,1,2,3};
  unsigned int buf1, buf2;
//  buf1 = 14;
  asm volatile (
                "add %[buf1], %[buf2], %[tab] \n\t"
                "addi %[buf2], %[LEN], 0 \n"
                : [buf1] "+r" (buf1),
                  [buf2] "+r" (buf2)
                : [LEN]"r"(LEN),
                  [tab]"r"(tab)
                : );
  return 0;
}
```

If I create an variable without any initialisation and use it as "+r" output register with this uninitialised variable. A correct code is generated if I use clang without optimisations:
```asm
        add     a2, a1, a4
        mv      a1, a3
```

But If I use a flag for optimisations (e.g. -O2) the same registers are allocated for `buf1` `LEN` and `buf2` `tab`:
```asm
        add     a0, a1, a1
        mv      a1, a0
```

If I initialise buf* variables before inline assembly then everything is fine also with optimisations. Of course my inline assembly is buggy because I have specified that I use `buf1` and `buf2` as an input, while I don't do that, but using gcc this code compile correctly (via https://godbolt.org/z/er8PjY6xc).

So I would like to ask:
- Is the difference with gcc expected?
- Is there a possibility to warn about such issues?

**Comment by topperc** [comment]
> That's expected behavior for LLVM, register allocator will ignore the `+` or `&` constraint _IF_ the operand is undef (uninitialized) value, and GCC will respect those constraint even the value is uninitialized, anyway `-Wuninitialized`/`-Werror=uninitialized` is your friend :)

-Wunitialized doesn't warn for this test case. Even -Weverything has no warning for the unitialized variables.

**Comment by topperc** [comment]
If you change `buf1` to an output only and initialize `buf2` you'll still get `buf1` and `tab` assigned to the same register. You need to also tell the compiler that `buf1` is written before all inputs are read by putting an `&` in the buf1 constraint string.

LIke this
```
  __asm volatile (
                "add %[buf1], %[buf2], %[tab] \n\t"
                "addi %[buf2], %[LEN], 0 \n"
                : [buf1] "=&r" (buf1),
                  [buf2] "+r" (buf2)
                : [LEN]"r"(LEN),
                  [tab]"r"(tab)
                : );
```

**Comment by kito-cheng** [comment]
Ooops, I tried gcc and it give me warning, but seems like i forgot to check clang :P

**Comment by lekcyjna123** [comment]
> That's expected behavior for LLVM

Thanks for confirmation and support!
