### ISSUE TITLE
Clang hangs up for an obscure though valid function declaration

### ISSUE THREAD

**Issue by tstanisl** [llvm/llvm-project#64713]
The compilation of the C code below hangs forever for clang's version >= 15. See [godbolt](https://godbolt.org/z/89rh5Ydae).

```
typeof(int(int)) x;
```

The code is equivalent to:

```
int x(int);
```

When compiled in C23 mode (`-std=c2x`) where `typeof` is a keyword then a following error message is produced.

```
error: expected function body after function declarator
```

The error message is incorrect because AFAIK the code is strictly compliant to C23 standard.

**Comment by shafik** [comment]
With new clang versions this code also hangs even with `-std=c2x` : https://godbolt.org/z/Pb78W8aa6

Note, gcc accepts. 

CC @AaronBallman

**Comment by AaronBallman** [comment]
Hmm, trying again as the automated process didn't seem to kick off...

/cherry-pick: https://github.com/llvm/llvm-project/commit/7b8f5f7df71c48b281163e88054c84c06364023d

**Comment by danix800** [comment]
Haha wrong magic word: there's an extra colon after `/cherry-pick`!

**Comment by EugeneZelenko** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/7b8f5f7df71c48b281163e88054c84c06364023d

**Comment by AaronBallman** [comment]
> Haha wrong magic word: there's an extra colon after `/cherry-pick`!

Oh I hadn't noticed that snuck in, thank you -- great catch!
