### ISSUE TITLE
[libc++] `std::ranges::clamp` violates [alg.clamp]p5

### ISSUE THREAD

**Issue by Fulgen301** [llvm/llvm-project#64717]
[alg.clamp]p5 mandates the complexity requirements for `std::ranges::clamp` to be at most two comparisons and three applications of the projection. libc++ however applies the projection four times. [See godbolt.](https://godbolt.org/z/cE1WGcY1j)

https://github.com/llvm/llvm-project/blob/5ed62c7bc99a979261d34e41aaca9581577674bf/libcxx/include/__algorithm/ranges_clamp.h#L40-L43

**Comment by pandaninjas** [comment]
Could I get this issue assigned to me?

**Comment by ldionne** [comment]
Done! Please don't hesitate to reach out on Discord if you have questions. Also note that the steps above related to Phabricator are outdated, we now use Github PRs for everything :-)
