### ISSUE TITLE
Backport ce658829c9ebd23066f4f0aa5dc686350e5f9ba4 to 17.0 

### ISSUE THREAD

**Issue by mandlebug** [llvm/llvm-project#64716]
Based on a comment on https://reviews.llvm.org/D155957, revert the patch and cleanup the existing code for the PPC64 toc-pseudo peepholes before adding to it.

**Comment by nikic** [comment]
/cherry-pick ce658829c9ebd23066f4f0aa5dc686350e5f9ba4 cef56b9318e37e9c47fd356c76c9da522bc8c122

**Comment by mandlebug** [comment]
abandoning in favour of https://github.com/llvm/llvm-project/issues/64869

**Comment by mandlebug** [comment]
nvm, I see @nikic already updated this PR. I'll close the new one instead.
