### ISSUE TITLE
[AST] Question about ADL lookup & structural equivalence of produced templates

### ISSUE THREAD

**Issue by danix800** [llvm/llvm-project#64725]
1. Without overloaded `operator+`:
```c
template <class T, T v>
struct integral_constant { static constexpr const T value = v; };

template <int N>
constexpr const int a = integral_constant<int,  N>::value + 1;
```
produces plain `BinaryOperator +` for `a`:
```c
  VarTemplateDecl 0x5622692efab0 <line:13:1, line:14:61> col:21 a
  |-NonTypeTemplateParmDecl 0x5622692c1780 <line:13:11, col:15> col:15 referenced 'int' depth 0 index 0 N
  `-VarDecl 0x5622692c1810 <line:14:1, col:61> col:21 a 'const int' constexpr cinit
    `-BinaryOperator 0x5622692efd28 <col:25, col:61> '<dependent type>' '+'
      |-DependentScopeDeclRefExpr 0x5622692efcd0 <col:25, col:53> '<dependent type>' lvalue
      `-IntegerLiteral 0x5622692efd08 <col:61> 'int' 1
```
2. With overloaded `operator+`:
```c
template <class T> class A {};

template <class T> A<T> operator+(int N, const A<T> &X) { return A<T>(); }

template <class T, T v>
struct integral_constant { static constexpr const T value = v; };

template <int N>
constexpr const int a = integral_constant<int,  N>::value + 1;
```
produces overloaded `CXXOperatorCallExpr +` for `a`:
```c
  VarTemplateDecl 0x560e6a7e6ee8 <line:8:1, line:9:61> col:21 a
  |-NonTypeTemplateParmDecl 0x560e6a7e6df0 <line:8:11, col:15> col:15 referenced 'int' depth 0 index 0 N
  `-VarDecl 0x560e6a7e6e80 <line:9:1, col:61> col:21 a 'const int' constexpr cinit
    `-CXXOperatorCallExpr 0x560e6a7e7190 <col:25, col:61> '<dependent type>' '+'
      |-UnresolvedLookupExpr 0x560e6a7e7148 <col:59> '<overloaded function type>' lvalue (ADL) = 'operator+' 0x560e6a7b83c8
      |-DependentScopeDeclRefExpr 0x560e6a7e70f0 <col:25, col:53> '<dependent type>' lvalue
      `-IntegerLiteral 0x560e6a7e7128 <col:61> 'int' 1
```

Current ASTStructuralEquivalence.cpp implementation considers the two variable templates of `a` as inequivalent.
So I'm wondering which part could be the problem.
1. Is this overload resolution correct? If not then what's the correct one? Otherwise,
2. Should these two variable templates be considered as equivalent? If true, then then equivalence algorithm might
    need improved in this case.

**Comment by danix800** [comment]
https://github.com/llvm/llvm-project/blob/66bb7521625826cab6fcc24662c053deee1ef90c/llvm/include/llvm/Support/PointerLikeTypeTraits.h#L29C7-L32

**Comment by danix800** [comment]
@AaronBallman @balazske WDYT?

**Comment by AaronBallman** [comment]
I've not verified this by looking at the standard, but I believe the overload set is correct to include the `operator+` because of ADL (even though the overload is never chosen), but that `a` in both examples are structurally equivalent. However, I don't have the time at the moment to chase this down definitively, so CC @hubert-reinterpretcast @erichkeane @cor3ntin @tahonermann for additional opinions.

**Comment by cor3ntin** [comment]
> Is this overload resolution correct? If not then what's the correct one? Otherwise,

Yes (there could be a specialization of `a` of type `A`), so the call can't be resolved until specialization on `N`.

> Should these two variable templates be considered as equivalent? 

I don't think so, there exist specializations for which ODR might be violated, i think te standard would consider them 
_[functionally equivalent](http://eel.is/c++draft/temp.over.link#def:functionally_equivalent,expressions)_. Note sure though, but Hubert sure will be able to correct me!

**Comment by cor3ntin** [comment]
> But `a` only takes non-type template parameter, so neither type `A` nor object of type `A` (no viable conversion from
> `A` to `int` in this case) could be used to specialize `a`.

True, if you specialize a, you'd specialize the initializer. Bad example indeed.
But you could specialize something else, consider 

```cpp

template <class T> class A {};

template <class T> A<T> operator+(int N, const A<T> &X) { return A<T>(); }

template <class T, T v>
struct integral_constant { static constexpr const T value = v; };

template <>
struct integral_constant<int, 0> { static constexpr const A<int> value {}; };

template <int N>
constexpr const int a = integral_constant<int,  N>::value + 1;

```

For `N  = 0`, ` integral_constant<int,  N>::value`, is `A`,  `operator+` cannot be the built-in operator (and indeed there is no
operator that would make that valid)

**Comment by danix800** [comment]
@cor3ntin Thanks for the example, a valid one could be:
```c
template <typename T> struct A {
  static constexpr const T v = 10;
};

template <typename T> constexpr int operator+(int N, A<T> X) {
  return N + X.v;
}

template <class T, T v>
struct integral_constant { static constexpr const T value = v; };

template <>
struct integral_constant<int, 0> { constexpr const static A<int> value {}; };

template <int N>
constexpr const int a = 1 + integral_constant<int,  N>::value;

constexpr const int b = a<0>;

static_assert(b == 11, "integral_constant<int, 0> specialization");
// static_assert(b == 1, "built-in +");
```
