### ISSUE TITLE
GlobalISel needs fdiv 1 / sqrt(x) to rsq combine

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#64743]
Need port of equivalent in https://reviews.llvm.org/D158099

**Comment by Ris-Bali** [comment]
I would like to work on this.

**Comment by arsenm** [comment]
@Pierre-vh do the tablegen combiners provide a way to check and preserve fast math flags?

**Comment by Pierre-vh** [comment]
No, not currently unfortunately. I haven't seen many (if any?) combines use that so I haven't thought about it yet.

If you can write up a small example of a combine that needs to check & preserve/output fast math flags I can add it to the to-do list, but I have no ETA on when I can take a look

**Comment by arsenm** [comment]
The rsq formation requires contract flags on both inputs:

```
---
name:            rsq_f16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr0

    %0:_(s32) = COPY $vgpr0
    %x:_(s16) = G_TRUNC %0:_(s32)
    %sqrt:_(s16) = contract G_FSQRT %x
    %one:_(s16) = G_FCONSTANT half 1.0
    %rsq:_(s16) = contract G_FDIV %one, %sqrt
    %ext:_(s32) = G_ANYEXT %rsq:_(s16)
    $vgpr0 = COPY %ext

...

---
name:            neg_rsq_f16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr0

    %0:_(s32) = COPY $vgpr0
    %x:_(s16) = G_TRUNC %0:_(s32)
    %sqrt:_(s16) = contract G_FSQRT %x
    %neg_one:_(s16) = G_FCONSTANT half -1.0
    %rsq:_(s16) = contract G_FDIV %neg_one, %sqrt
    %ext:_(s32) = G_ANYEXT %rsq:_(s16)
    $vgpr0 = COPY %ext

...

---
name:            rsq_f16_multi_use
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr0

    %0:_(s32) = COPY $vgpr0
    %x:_(s16) = G_TRUNC %0:_(s32)
    %sqrt:_(s16) = contract G_FSQRT %x
    %one:_(s16) = G_FCONSTANT half 1.0
    %rsq:_(s16) = contract G_FDIV %one, %sqrt
    %ext:_(s32) = G_ANYEXT %rsq:_(s16)
    $vgpr0 = COPY %ext
    S_ENDPGM 0, implicit %sqrt

...

```

**Comment by Pierre-vh** [comment]
Add MIFlags matching to combiner: https://reviews.llvm.org/D159111

**Comment by nickleus27** [comment]
@Ris-Bali are you still actively working on this issue? If not, I am interested to work on this issue.

**Comment by Ris-Bali** [comment]
No I am not working on this currently please go ahead and take a stab at this

**Comment by nickleus27** [comment]
I have read through the comments and through commit [D158099](https://reviews.llvm.org/D158099). It seems to me I need to create a function `performRsqCombine()` in file SIILowering.cpp. I am hoping that more context can be given to what is expected or steps needed to complete this patch?

**Comment by Pierre-vh** [comment]
> I have read through the comments and through commit [D158099](https://reviews.llvm.org/D158099). It seems to me I need to create a function `performRsqCombine()` in file SIILowering.cpp. I am hoping that more context can be given to what is expected or steps needed to complete this patch?

No, you'd add something to `Combine.td` if the combine has to be generic (@arsenm ?) or `AMDGPUCombine.td` (create a new combine rule and add it to the list of combines at the end of the file), then you need to implement a match/apply function for this and write some tests
