### ISSUE TITLE
[flang][hlfir] OpenMP LIT tests

### ISSUE THREAD

**Issue by vzakhari** [llvm/llvm-project#64746]
Part of https://discourse.llvm.org/t/rfc-enabling-the-hlfir-lowering-by-default/72778:
* Update `flang/test/Lower/OpenMP` to work with HLFIR lowering.

- [x] atomic-capture.f90 (@NimishMishra Please move to HLFIR flow with your atomic update patch)
- [x] atomic-read.f90
- [x] atomic-update.f90 (@NimishMishra Please move to HLFIR flow with your atomic update patch)
- [x] atomic-write.f90
- [x] copyin.f90
- [x] declare-target-implicit-tarop-cap.f90 (@skatrak Working on this)
- [x] default-clause.f90 (@harishch4 Working on this)
- [x] firstprivate-commonblock.f90
- [x] function-filtering-2.f90 (@skatrak Working on this)
- [x] function-filtering.f90 (@skatrak Working on this)
- [x] host-ir-flag.f90
- [x] omp-target-early-outlining.f90 (@TIFitis to remove this test as part of IsolatedFromAbove changes)
- [x] parallel-firstprivate-clause-scalar.f90
- [x] parallel-lastprivate-clause-scalar.f90
- [x] parallel-private-clause-fixes.f90
- [x] parallel-private-clause.f90 (@harishch4 Working on this)
- [x] parallel-reduction-add.f90
- [x] parallel-sections.f90
- [x] parallel-wsloop-firstpriv.f90
- [x] parallel-wsloop.f90
- [x] parallel.f90
- [x] private-commonblock.f90
- [x] single.f90
- [x] target.f90
- [x] task.f90 (@harishch4 Working on this)
- [x] threadprivate-char-array-chararray.f90 (@harishch4 Working on this)
- [x] threadprivate-commonblock.f90 (@harishch4 Working on this)
- [x] threadprivate-integer-different-kinds.f90 (@harishch4 Working on this)
- [x] threadprivate-non-global.f90 (@harishch4 Working on this)
- [x] threadprivate-pointer-allocatable.f90 (@harishch4 Working on this)
- [x] threadprivate-real-logical-complex-derivedtype.f90 (@harishch4 Working on this)
- [x] threadprivate-use-association-2.f90
- [x] threadprivate-use-association.f90 (@chandankds Working on this)
- [x] unstructured.f90 
- [x] wsloop.f90

**Comment by kiranchandramohan** [comment]
This is complete now. Thanks to everyone who participated.
