### ISSUE TITLE
[flang][hlfir] No regressions on OpenMP suites

### ISSUE THREAD

**Issue by vzakhari** [llvm/llvm-project#64752]
Part of https://discourse.llvm.org/t/rfc-enabling-the-hlfir-lowering-by-default/72778:
* @kiranchandramohan: No regressions with:
- [x] gfortran-testsuite (i.e. https://github.com/llvm/llvm-test-suite/blob/main/Fortran/gfortran/regression/gomp/appendix-a/DisabledFilesHLFIR.cmake and https://github.com/llvm/llvm-test-suite/blob/main/Fortran/gfortran/regression/gomp/DisabledFilesHLFIR.cmake are empty)
- [x] NPB
- [x] spec-2017 speed
- [x] spec-omp-2012
- [x] SNAP

**Comment by kiranchandramohan** [comment]
Regressions over FIR lowering.
spec-2017 speed : wrf fails during compilation, bwaves fails at runtime.

**Comment by kiranchandramohan** [comment]
No regressions seen in any of these benchmarks/benchmark suites.
