### ISSUE TITLE
[flang][hlfir] No regressions on OpenMP 1.1 features

### ISSUE THREAD

**Issue by vzakhari** [llvm/llvm-project#64751]
Part of https://discourse.llvm.org/t/rfc-enabling-the-hlfir-lowering-by-default/72778:
* @kiranchandramohan: all OpenMP 1.1 [features](https://docs.google.com/spreadsheets/d/1FvHPuSkGbl4mQZRAwCIndvQx9dQboffiD-xD0oqxgU0/edit#gid=1866244102) to continue to work after the switch. Currently there are issues with reduction, atomic, threadprivate support for common blocks.

**Comment by kiranchandramohan** [comment]
All the known issues are fixed. Remaining issues will be fixed while porting the LIT tests.
