### ISSUE TITLE
[OpenRadioss] openmp implicit none scope issue

### ISSUE THREAD

**Issue by varnj** [llvm/llvm-project#64760]
In the openmp pragma default(none) if the size of the loop is passed as a function argument, the compilation fails as it can not detect n. For gcc (8.5) and icc this succeds to compile but for aocc it fails. I am providing a sample test case to replicate the issue. 
The workaround for this is to put this variable in shared as this is just a read only, this requires source code change for open source codes. gcc and icc both succeed on the compilation.
[radioss.zip](https://github.com/llvm/llvm-project/files/12366989/radioss.zip)

**Comment by shiltian** [comment]
The OpenMP v5.2 Sec. 5.4.1 (actually it doesn't have to be v5.2):
> If data-sharing-attribute is none, the data-sharing attribute is not implicitly determined.
Here the outer parallel region has `default(none)`, which means the data-sharing attributes of all variables captured inside the parallel region have to be set *explicitly*. However, in the code, only `local_residual`, `v1v`, and `v2v` have been set. `n` is not. Clang's behavior completely compiles with the spec.
