### ISSUE TITLE
clang with no-pic should use local-exec tls model for risc-v

### ISSUE THREAD

**Issue by Temperature-block** [llvm/llvm-project#64766]
a.c
```
extern __thread int ThreadVar;
int _start(void)
{
 return ThreadVar;
}
```

b.c
`__thread int ThreadVar = 123;
`

when we compile and link using -fno-pic
shouldn't it default to using Local-exec instead of initial-exec
from my limited understanding non-pic code uses absolutes and indirection through GOT is not necessary
instead we end up with objdump containing GOT indirection to access tls variable 
```
0000000000010170 <_start>:
 10170: 00002517 auipc a0,0x2
 10174: ea853503 ld a0,-344(a0) # 12018 <_GLOBAL_OFFSET_TABLE_+0x8>
 10178: 9512 add a0,a0,tp
 1017a: 4108 lw a0,0(a0)
 1017c: 8082 ret

```
if we do explicitly ask clang to use local exec (-ftls-model)
we end up having expected behavior o/p
```
0000000000010158 <_start>:
 10158: 00022503 lw a0,0(tp) # 0 <ThreadVar>
 1015c: 8082 ret
```

when no-pic is used above code should emit local exec relocations
```
OFFSET           TYPE              VALUE
0000000000000008 R_RISCV_TPREL_HI20  ThreadVar
0000000000000008 R_RISCV_RELAX     *ABS*
000000000000000c R_RISCV_TPREL_ADD  ThreadVar
000000000000000c R_RISCV_RELAX     *ABS*
0000000000000010 R_RISCV_TPREL_LO12_I  ThreadVar
0000000000000010 R_RISCV_RELAX     *ABS*
```
instead, we end up using initial exec 
OFFSET           TYPE              VALUE
```
0000000000000008 R_RISCV_TLS_GOT_HI20  ThreadVar
000000000000000c R_RISCV_PCREL_LO12_I  .Lpcrel_hi0
000000000000000c R_RISCV_RELAX     *ABS*
```

**Comment by jrtc27** [comment]
No it shouldn’t. Every architecture is like this, and I explained to you on Discord why it is this way; namely, just because you pass -fno-PIC doesn’t mean that you’re not linking against a shared library which provides that symbol.
