### ISSUE TITLE
Create team for sanitizers

### ISSUE THREAD

**Issue by fmayer** [llvm/llvm-project#64785]
(See https://lists.llvm.org/pipermail/llvm-dev/2022-January/154537.html)

Probably easier than one per sanitizer. That includes the following labels:

* compiler-rt:hwasan 
* compiler-rt:asan 
* compiler-rt:ubsan 
* compiler-rt:tsan
* compiler-rt:msan
* compiler-rt:lsan

**Comment by asl** [comment]
@fmayer These days you can subscribe to the labels on GitHib. Will it be enough?

**Comment by fmayer** [comment]
I am not sure I understand. Are you saying I can subscribe to a label myself? How? I couldn't find out how.

**Comment by asl** [comment]
Hope this helps:

<img width="643" alt="Screenshot 2023-08-17 at 17 14 57" src="https://github.com/llvm/llvm-project/assets/67392/1a109787-a4d1-4c12-b0ac-f309a58be357">
