### ISSUE TITLE
Backport UBSan compiler crash fix to 17.0

### ISSUE THREAD

**Issue by usama54321** [llvm/llvm-project#64784]
In https://reviews.llvm.org/D157445, a fix was made for a compiler crash while generating code for the function sanitizer. I am requesting to backport this to 17.0

**Comment by EugeneZelenko** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/9afc57dcb2e5cd36ca1ddf0fee3efa958bfd4c2a https://github.com/llvm/llvm-project/commit/bb5f64a6fc059fcf81b4b9ffe035f5063956ddd8
