### ISSUE TITLE
Revert Clang support for FatLTO

### ISSUE THREAD

**Issue by ilovepi** [llvm/llvm-project#64780]
FatLTO support for linkers hasn't landed, and we want to avoid giving users the idea that 17.x release will include support. see https://reviews.llvm.org/D152973#4594597 for more details.

/branch ilovepi/llvm-project/revert-clang-fatlto-support

**Comment by nikic** [comment]
/branch ilovepi/llvm-project/revert-clang-fatlto-support

(Currently doesn't work in the issue description, only comments)

**Comment by nikic** [comment]
Another try, looks like there was some kind of special character in the name (?)

/branch ilovepi/llvm-project/revert-clang-fatlto-support
