### ISSUE TITLE
[apt.llvm.org] Add riscv64 architecture

### ISSUE THREAD

**Issue by maflcko** [llvm/llvm-project#64795]
Similar to `s390x`, it would be good to add the `riscv64` architecture. This means the script can be used on the upcoming Debian 13, which plans to "ship trixie with riscv64 support" [1]

cc @sylvestre

[1] https://lists.debian.org/debian-devel-announce/2023/06/msg00001.html

**Comment by sylvestre** [comment]
apt.llvm.org isn't linked to debian's arch.
To support riscv64, i need access to some hardware to be able to run it. (arm & ibm are giving me access to some servers)
if someone can provide that, my email is sylvestre@debian.org

**Comment by sylvestre** [comment]
it would require a bunch of customization for this arch - very different from other archs. Not sure I want to go that path

**Comment by mr-c** [comment]
@sylvestre If you enable https://github.com/apps/rise-risc-v-runners from https://riscv-runners.riseproject.dev/ then I'll send a PR

**Comment by sylvestre** [comment]
sorry, apt.llvm.org isn't running on github actions
