### ISSUE TITLE
Is it expected that --relocatable-pch accepts relative isysroot and tries to match source paths against it?

### ISSUE THREAD

**Issue by vient** [llvm/llvm-project#64807]
As title asks. I am not sure if it is expected or not. I stumbled into it while trying to use ccache with base_dir when creating relocatable header - ccache changed `isysroot` argument from absolute path to `.`, then Clang promptly failed to match any sources against it.

```
clang-16 -isysroot ${PWD} --relocatable-pch -x c++-header pch.h -o pch1.pch
clang-16 -isysroot . --relocatable-pch -x c++-header pch.h -o pch2.pch
```
will produce different results (pch.h is an empty file).

As I saw in produced PCH files, source paths are not canonized, they may contain `..` parts for example. From this I take that `isysroot` should not be canonized as well but I'm not sure.

CCache issue https://github.com/ccache/ccache/issues/1322

**Comment by MaskRay** [comment]
This behavior is intended. Clang does not resolve `.` to `$PWD`.  An analogy is `-ffile-prefix-map=.=xxx`/`-fdebug-prefix-map=.=xxx`. 

```
-ffile-prefix-map=.=xxx  // does not normalize
-ffile-prefix-map=$PWD=xxx
```
