### ISSUE TITLE
[clang-format] Adding colon after // clang-format off does not work as documented

### ISSUE THREAD

**Issue by fsahmad** [llvm/llvm-project#64817]
According to the clang-format documentation section [Disabling Formatting on a Piece of Code](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#disabling-formatting-on-a-piece-of-code) it should be possible to add an explanatory message using a colon `:` after `// clang-format off`.

This isn't working as expected, the `// clang-format off` gets ignored once you append a colon:

For example:

```c++
int formatted_code;
// clang-format off
    void    unformatted_code  ;
// clang-format on
void formatted_code_again;

// clang-format off : Explanation
    void    unformatted_code  ;
// clang-format on

// clang-format off: Explanation
    void    unformatted_code  ;
// clang-format on
```

I tested this code with various versions of clang-format, ranging from 8.0.1 to 16.0.6 and the last two sections get formatted resulting in this:

```c++
int formatted_code;
// clang-format off
    void    unformatted_code  ;
// clang-format on
void formatted_code_again;

// clang-format off : Explanation
void unformatted_code;
// clang-format on

// clang-format off: Explanation
void unformatted_code;
// clang-format on
```

**Comment by owenca** [comment]
The support for the colon (which must immediately follow the `on` or `off`) was added in version 17.
