### ISSUE TITLE
[FLANG] Flaky test "FAIL: Flang::underscoring.f90"

### ISSUE THREAD

**Issue by jdoerfert** [llvm/llvm-project#64822]
Fails very frequently:
https://lab.llvm.org/buildbot/#/builders/21/builds/78624
https://lab.llvm.org/buildbot/#/builders/21/builds/78621
https://lab.llvm.org/buildbot/#/builders/21/builds/78607
https://lab.llvm.org/buildbot/#/builders/21/builds/78606
https://lab.llvm.org/buildbot/#/builders/21/builds/78599

**Comment by kkwli** [comment]
Fixed in https://reviews.llvm.org/D158187

**Comment by EugeneZelenko** [comment]
@kkwli: Fix was not committed yet.

**Comment by kkwli** [comment]
Commit: https://github.com/llvm/llvm-project/commit/bfe390cf9aa61c2d8487c79fc0fa87cc17014313
