### ISSUE TITLE
[M68k] RTE instruction missing

### ISSUE THREAD

**Issue by thankfulmachine** [llvm/llvm-project#64833]
The `rte` instruction is missing and is not emitted in `__attribute__((interrupt))` functions.

**Comment by thankfulmachine** [comment]
CC @mshockwave

**Comment by thankfulmachine** [comment]
@mshockwave What is the meaning of the interrupt attribute argument in `handleM68kInterruptAttr`? It's not the exception vector number is it?

**Comment by mshockwave** [comment]
> The `rte` instruction is missing and is not emitted in `__attribute__((interrupt))` functions.

Right, we should fix this.

> @mshockwave What is the meaning of the interrupt attribute argument in `handleM68kInterruptAttr`? It's not the exception vector number is it?

It was meant to be the exception vector number but the implementation is fundamental broken: right now we do nothing on these handlers but making an alias symbol for them indicating its vector number. What I think a better solution would be putting each handler in a separate section.
Please let me know if you know how other compilers lower interrupt handlers for m68k. (M68k GCC's implementation for interrupt handler is also broken)

**Comment by thankfulmachine** [comment]
Gotcha, ok, I'll file a separate issue for the exception vector table. There are slots 2 through 255. I'll add some further information there.
