### ISSUE TITLE
Dependent member function name is resolved incorrectly

### ISSUE THREAD

**Issue by Endilll** [llvm/llvm-project#64841]
Consider the following one-liner:
https://github.com/llvm/llvm-project/blob/fa2b038cadf17d08014e5fb75c47b5024860953e/llvm/include/llvm/ADT/PointerIntPair.h#L94

`Info::getPointer` is incorrectly resolved to be the function defined in this very line.
It's observable by jumping to definition (jumps to the same line), and by asking for information about `Info::getPointer` symbol:
```
instance-method getPointer
→ PointerTy

// In PointerIntPair<PointerTy, IntBits, IntType, PtrTraits, Info>
public: PointerTy getPointer() const
```

Function is actually defined 100 lines below, in `PointerIntPairInfo`: https://github.com/llvm/llvm-project/blob/fa2b038cadf17d08014e5fb75c47b5024860953e/llvm/include/llvm/ADT/PointerIntPair.h#L190-L193

I'm using VS Code with clangd extension, if that matters.

**Comment by Endilll** [comment]
To be clear, `detail::PunnedPointer`  has an `operator intptr_t()`: https://github.com/llvm/llvm-project/blob/fa2b038cadf17d08014e5fb75c47b5024860953e/llvm/include/llvm/ADT/PointerIntPair.h#L45

**Comment by Endilll** [comment]
Given that it's a dependent context, ideally I'd like clangd to list candidate implementations for me to pick from, ranking them by popularity, or at the very least give up and not mislead me.

**Comment by HighCommander4** [comment]
Minimized testcase:

```c++
struct PointerIntPairInfo {
  static void *getPointer(void *Value);
};

template <typename Info = PointerIntPairInfo>
struct PointerIntPair {
  void *Value;
  void *getPointer() const { return Info::getPointer(Value); }
};
```

**Comment by HighCommander4** [comment]
So my first thought was that this is one of our textual heuristics (`findNearbyIdentifier` or `locateSymbolTextually`) acting up, but nope: our AST-based logic itself is returning this incorrect result! :scream_cat:

**Comment by HighCommander4** [comment]
I think what's happening here is that `HeuristicResolver::resolveMemberExpr()` is being too promiscuous: if it fails to find the member [in the qualifier's scope](https://searchfox.org/llvm/rev/adaae6a7c1ae74188111200eed9b64cac77d096f/clang-tools-extra/clangd/HeuristicResolver.cpp#133-140), it... ignores the qualifier and tries looking up the member in the current scope, which is incorrect in general.

**Comment by HighCommander4** [comment]
I tried just returning early if we have a qualifier and couldn't find anything in the qualifier's scope, expecting that some testcases will break, but nothing did. So that's seems like a good enough fix for now.

**Comment by HighCommander4** [comment]
Proposed fix: https://reviews.llvm.org/D158873

**Comment by HighCommander4** [comment]
After the fix, the behaviour is that AST-based resolution produces no results and we fall back on our textual heuristics.

On the minimized testcase, the textual heuristics offer both `PointerIntPair::getPointer` (the incorrect result), and `PointerIntPairInfo::getPointer` (the intended result).

This could be improved further (e.g. for calls, we could do arity-based filtering on the textual results), but I'm going to leave that to future issues and consider the original bug here fixed.

**Comment by HighCommander4** [comment]
> On the minimized testcase, the textual heuristics offer both `PointerIntPair::getPointer` (the incorrect result), and `PointerIntPairInfo::getPointer` (the intended result).

(I don't have a local opt build handy to try the updated behaviour on the original testcase in the LLVM source, but the result is presumably similar, except that perhaps some additional functions named `getPointer` found in the index may be offered as well.)

**Comment by HighCommander4** [comment]
> > On the minimized testcase, the textual heuristics offer both `PointerIntPair::getPointer` (the incorrect result), and `PointerIntPairInfo::getPointer` (the intended result).
> 
> (I don't have a local opt build handy to try the updated behaviour on the original testcase in the LLVM source, but the result is presumably similar, except that perhaps some additional functions named `getPointer` found in the index may be offered as well.)

For completeness, I did check the behaviour on the original testcase. What actually happens is that the textual heuristic finds more than 5 candidate functions named `getPointer` in the index, and we [bail](https://searchfox.org/llvm/rev/b63c6e585d8662b67b38988f0cd38a0bd6e0d38a/clang-tools-extra/clangd/XRefs.cpp#627-633) and return no results.
