### ISSUE TITLE
[Infrastructure] ABI tester flaky for release builds

### ISSUE THREAD

**Issue by tru** [llvm/llvm-project#64852]
Almost half of the PR's filed for the release fails in the abi tester right now, it's a little scary to not have that test working when we pass 17.0.0-final. See logs here for example: https://github.com/llvm/llvm-project-release-prs/actions/runs/5879937279/job/15947702167?pr=595

It seems like @tstellar is out right now, @nikic / @kwk do you know anything about how that abi tester works or why it seems broken?

**Comment by kwk** [comment]
@tru I'm back from 2 weeks of Sick leave today. I hope I can find something out.

**Comment by tstellar** [comment]
It looks like it was broken by this commit: d30b187f7d44f06eccb77394019ba1b942bd9132 which moved from v1 of the download-artifact action to v3.  I think we want to try to stick with the v3 version, so I'll try to change our workflow file to work with the latest version.

**Comment by tru** [comment]
Thanks!!!

**Comment by kwk** [comment]
> It looks like it was broken by this commit: [d30b187](https://github.com/llvm/llvm-project/commit/d30b187f7d44f06eccb77394019ba1b942bd9132) which moved from v1 of the download-artifact action to v3. I think we want to try to stick with the v3 version, so I'll try to change our workflow file to work with the latest version.

This looks like the proper documentation point for what you found out: https://github.com/actions/download-artifact#compatibility-between-v1-and-v2v3
