### ISSUE TITLE
[libc++] `__assign_view` is declared noexcept but may throw on failing allocation

### ISSUE THREAD

**Issue by tobias-fire** [llvm/llvm-project#64858]
The function `__assign_view` is declared `noexcept`: 
https://github.com/llvm/llvm-project/blob/main/libcxx/include/__filesystem/path.h#L1072C1-L1076

However, it calls `std::basic_string<char>::basic_string<char>(std::string_view)` which is not declared `noexcept` and may throw when the allocation of memory for the new string fails. This results in a `std::terminate()` call. 

The function should not be declared `noexcept`.

**Comment by Ris-Bali** [comment]
I would like to take this

**Comment by Ris-Bali** [comment]
Patch link : https://reviews.llvm.org/D158826
