### ISSUE TITLE
Comparison of add of extended booleans not folded to xor

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#64859]
I was looking at [some code that tried to compute a sort of enum scheme by adding booleans, and comparing to constant values which failed to form nice boolean code](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/46939af92ad91238c878a82aad2220822073ffa1/ocml/src/powF_base.h#L64). This is really just an xor.

https://alive2.llvm.org/ce/z/RSnV-d

```
define i1 @src(i1 %arg, i1 %arg1) {
bb:
  %i = zext i1 %arg to i32
  %i2 = zext i1 %arg1 to i32
  %i3 = add nuw nsw i32 %i2, %i
  %i4 = icmp eq i32 %i3, 1
  ret i1 %i4
}

define i1 @tgt(i1 %arg, i1 %arg1) {
bb:
  %xor = xor i1 %arg, %arg1
  ret i1 %xor
}

```

**Comment by elhewaty** [comment]
Can I fix this? But I will need some help, as I am not familiar with LLVM system yet

**Comment by elhewaty** [comment]
`%i4 = icmp eq i32 %i3, 1`
what if the `1` were `0`?

**Comment by dc03** [comment]
> `%i4 = icmp eq i32 %i3, 1` what if the `1` were `0`?

That would be equivalent to `not(or(x, y))`: https://alive2.llvm.org/ce/z/8z7Q4G

**Comment by elhewaty** [comment]
so the `xor` case holds for `eq` and `1` only

**Comment by dc03** [comment]
> so the `xor` case holds for `eq` and `1` only

Yes, if you sketch out the truth table for this function you will see it is equivalent to the table for an xor, and with 0 it is equivalent to the table for a nor.

**Comment by elhewaty** [comment]
So we need to create a new function `foldICmpAddExtI1` and handle all our cases? or do we have something like this already?

**Comment by dc03** [comment]
I think `foldICmpAddConstant` may be what you're looking for: https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp#L2898

**Comment by elhewaty** [comment]
@arsenm Here is a candidate patch : https://reviews.llvm.org/D159464

**Comment by elhewaty** [comment]
Can you please review the patch again.

**Comment by elhewaty** [comment]
ping

**Comment by elhewaty** [comment]
@arsenm @nikic @goldsteinn Here's a candidate pull: https://github.com/llvm/llvm-project/pull/67895
