### ISSUE TITLE
Backport the disable of gather/scatter in auto-vectorisation to 17.0

### ISSUE THREAD

**Issue by phoebewang** [llvm/llvm-project#64853]
/cherry-pick https://github.com/llvm/llvm-project/commit/993bdb047c90

**Comment by mgorny** [comment]
This introduced a regression in rc3. I've filed #64921 to backport the followup fix.

**Comment by phoebewang** [comment]
> This introduced a regression in rc3. I've filed #64921 to backport the followup fix.

Thanks @mgorny !
