### ISSUE TITLE
[AMDGPU] Clang -cc1as does not recognize the `#exclude` flag

### ISSUE THREAD

**Issue by jhuber6** [llvm/llvm-project#64862]
Some sections in the ELF are emitted with the `SHF_EXCLUDE` section flag. One case where this sometimes shows up is with the `.linker-options` section that is sometimes emitted. If this is passed to `clang -cc1as` it will return an error on an unrecognized flag. Consider the following test input

```asm
	.text
	.p2alignl 6, 3214868480
	.fill 48, 4, 3214868480
	.section	".linker-options",#exclude
	.section	".note.GNU-stack"
	.amdgcn_target "amdgcn-amd-amdhsa--gfx1030"
	.amdgpu_metadata
---
amdhsa.kernels:  []
amdhsa.target:   amdgcn-amd-amdhsa--gfx1030
amdhsa.version:
  - 1
  - 1
...

	.end_amdgpu_metadata

```

If we compile this file with clang, we will see the following error.
```
 $ clang test.s --target=amdgcn-amd-amdhsa -mcpu=gfx1030
 test.s:4:30: error: unknown flag
        .section        ".linker-options",#exclude
                                           ^
```

**Comment by MaskRay** [comment]
I'm surprised that AMDGPU uses Sun-style section attributes `.section	".linker-options",#exclude` ...

You can use GNU-style `.section	".linker-options","e"`.

In gas, `#exclude` is only supported for Sparc. I cannot find any reference whether Solaris assembler really supports `#exclude` for other architectures...

**Comment by jhuber6** [comment]
> I'm surprised that AMDGPU uses Sun-style section attributes `.section ".linker-options",#exclude` ...
> 
> You can use GNU-style `.section ".linker-options","e"`.
> 
> In gas, `#exclude` is only supported for Sparc. LLVM integrated assembler probably shouldn't support it at all... or at least restrict it to Solaris. Hmm, I cannot find any reference whether Solaris assembler really supports `#exclude` for other architectures...

I'm not sure what the original decision making process was for selecting SUN, but it's definitely deliberate. See, https://github.com/llvm/llvm-project/blob/0e4a38018a7228d93d72a31d9fae6855f866dded/llvm/lib/Target/AMDGPU/MCTargetDesc/AMDGPUMCAsmInfo.cpp#L34. Why do we need prior art to decide if this flag should be supported? It's clearly already being emitted that way, so we should be able to parse it.

**Comment by arsenm** [comment]
> I'm not sure what the original decision making process was for selecting SUN, but it's definitely deliberate. See,
> 

I wouldn't call copy paste from another target 'deliberate'
