### ISSUE TITLE
Backport 2 revert commits to 17.0 

### ISSUE THREAD

**Issue by mandlebug** [llvm/llvm-project#64869]
Based on a comment on https://reviews.llvm.org/D155957, revert the 2 recent patches and cleanup the existing code for the PPC64 toc-pseudo peepholes before adding to it.

**Comment by mandlebug** [comment]
https://github.com/llvm/llvm-project/issues/64716 was updated just before opening this issue. I'll keep that one opened and close this one instead.

**Comment by nikic** [comment]
These were already backported in https://github.com/llvm/llvm-project/issues/64716, not sure why this got reopened.
