### ISSUE TITLE
Clang fail to compiles where GCC succeed, Error: initializer element is not a compile-time constant

### ISSUE THREAD

**Issue by TechScribe-Deaf** [llvm/llvm-project#64874]
Hello, I came across this bug when I was working on optimizing my software to move from static initialization to compile time constants and I came across a bug that appears only in Clang, but not in GCC. GCC is able to compile the following code just fine and produced expected output and behavior:

```c
#include <stdio.h>

typedef struct { int field; } DataType;
const DataType val = (DataType){ .field = 1 };
const DataType array[1] = { val };

int main(int argc, const char* argv[argc])
{
        printf("%i\n", array[0].field);
        return 0;
}
```

I am unsure if this is on Clang-side of the compilation or if this is actually on LLVM-side of the compilation. Here the following error output:

```
[techscribe@SecureDev Tests]$ clang test.c
test.c:5:29: error: initializer element is not a compile-time constant
const DataType array[1] = { val };
                            ^~~
1 error generated.
```

**Comment by TechScribe-Deaf** [comment]
Distro: Arch Linux, Last Update: Today
Clang Version: 15.0.7 (Provided by Pacman package manager)
Linux Version: 6.4.11
LLVM Version: 15.0.7-3 (Provided by Pacman package manager)

**Comment by EugeneZelenko** [comment]
Could you please try 17 Release Candidate or `main` branch? https://godbolt.org should be helpful.

**Comment by ms178** [comment]
This seems to fail on Clang 15 and 16 but not on trunk with assertions any longer: https://godbolt.org/z/rr5TTq6Mb

**Comment by TechScribe-Deaf** [comment]
I am building the compiler 17.0.0rc2 currently and will report back once I successfully build newer version of compiler.

**Comment by TechScribe-Deaf** [comment]
Ok, it seems to be fixed in Clang-17 for this issue. Thank you everyone for checking into this.
