### ISSUE TITLE
clang: My fight for HALO : results and ideas

### ISSUE THREAD

**Issue by kelbon** [llvm/llvm-project#64906]
Some time ago, I set out to write at least an efficient generator in C++20, the main problem, as expected, frame allocation

Therefore, for several iterations, I was looking for the guarantees missing for the compiler for optimizations 
 (https://github.com/llvm/llvm-project/issues/64542
https://github.com/llvm/llvm-project/issues/64507)

in the end, I managed to make sure that the allocations are optimized, as I expected, it was enough just to let the compiler know that calling the resume function does not change local variables and fields

The problem is that this feature does not exist either at the language level or at the level of its implementation.

I ended up having to do something like this:

[commit link](https://github.com/kelbon/kelcoro/commit/2e97bf410d14b39ec8db3325ddabc1aaff66d801)

See effect here:
https://godbolt.org/z/f39TxvGas (removing '-DDAO' flag enables 'assume' and removes allocations + enables other optimizations)

```C++
void some_method() {
    const auto* const address_before = X.address();
    handle.resume();
    const auto* const address_after = X.address();
    assume(address_before == address_after);
}
```
There are many problems:
1. invoking any function is a side effect, which will break 'assume'
2. it will not work for any non trivial object, std::string for example (operator== is an side effect)
3. debug overhead (and possibly release too in case of coroutines, because local variables == more stack to allocate and it will not be optimized on this stage)
4. it is really magic, that it is working, because it is not obvious for compiler what i really want to say
5. i cant declare a function with such properties, only boiler plate on call-site

So, first idea: we need an attribute to explicitly say, that function do not changes something. Examples:
local variables, fields of class where method exist, function inputs (const X& for example, which is really do not changed in 99.99% cases) or concrete names

So:

```C++
void some_method() {
    handle.resume();
    [[clang::assume_unchanged(X)]];  // assumes its unchanged since 'some_method' start
}
void println(forward_range_with_const_begin auto&& rng [[clang::assume_unchanged]]);

void log() [[clang::assume_unchanged(__locals, __fields)]];

```
Etc etc, its just pseudocode, but its really usefull in many cases, i think there are maybe more cases for this attribute then for 'assume' 'pure' and 'const' together

### Another problem:
 For some reason compiler thinks its good idea to create coroutine frame not as 'union' of all states which must be saved on suspend points, but as tuple of them. 
 https://godbolt.org/z/r3T6eM4fc

```C++

// instead of reusing allocated memory size grows

dd::generator<int> g() {
    co_yield 1;
}
// size - 112
dd::generator<int> g1 () {
    co_yield dd::elements_of(g());
}
// size - 168
dd::generator<int> g2 () {
    co_yield dd::elements_of(g());
    co_yield dd::elements_of(g());
}
// size - 224
dd::generator<int> g3 () {
    co_yield dd::elements_of(g());
    co_yield dd::elements_of(g());
    co_yield dd::elements_of(g());
}

```

Some of this problems as i understand must be resolved on language level: for example, allow 'consteval' on functions used on 'runtime' values (atleast for static functions)

Because now this code will be ill-formed when used:

```C++
struct awaiter {
  static consteval bool await_ready() { return true; }
...
};

```
Such information on front-end may be very usefull for removing 'never suspend' points
And no way to say 'await_suspend always returns false, so its never suspend really'

And last one: clang 16 bug https://godbolt.org/z/P85b7c3he

**Comment by asl** [comment]
I would suggest you to post your thoughts & questions to[ LLVM Discourse](https://discourse.llvm.org/) and submit bugs / issues separately.
