### ISSUE TITLE
accesstime (atime) does not work reliably on MacOs

### ISSUE THREAD

**Issue by hiraditya** [llvm/llvm-project#64908]
`ninja check-llvm-tools-llvm-objcopy` sometimes passes and sometimes fails on `llvm-project/llvm/test/tools/llvm-objcopy/ELF/strip-preserve-atime.test`

I ran the test manually and it behaves weird many times. Even if `touch -at` works correctly, by the time next command runs the access time changes under the hood.

```console
macbookpro:stage2  touch -a -t 199505050555.55 /Users/g/llvm-toolchain/out/stage2/test/tools/llvm-objcopy/ELF/Output/strip-preserve-atime.test.tmp-input.dwo
macbookpro:stage2  ls -lu /Users/g/llvm-toolchain/out/stage2/test/tools/llvm-objcopy/ELF/Output/strip-preserve-atime.test.tmp-input.dwo
-rw-r--r--  1  primarygroup  3568 May  5  1995 /Users/g/llvm-toolchain/out/stage2/test/tools/llvm-objcopy/ELF/Output/strip-preserve-atime.test.tmp-input.dwo
macbookpro:stage2  /Users/g/llvm-toolchain/out/stage2/bin/llvm-objcopy -p --split-dwo=/Users/g/llvm-toolchain/out/stage2/test/tools/llvm-objcopy/ELF/Output/strip-preserve-atime.test.tmp-dwo /Users/g/llvm-toolchain/out/stage2/test/tools/llvm-objcopy/ELF/Output/strip-preserve-atime.test.tmp-input.dwo /Users/g/llvm-toolchain/out/stage2/test/tools/llvm-objcopy/ELF/Output/strip-preserve-atime.test.tmp-nondwo
macbookpro:stage2  ls -lu /Users/g/llvm-toolchain/out/stage2/test/tools/llvm-objcopy/ELF/Output/strip-preserve-atime.test.tmp-dwo /Users/g/llvm-toolchain/out/stage2/test/tools/llvm-objcopy/ELF/Output/strip-preserve-atime.test.tmp-input.dwo /Users/g/llvm-toolchain/out/stage2/test/tools/llvm-objcopy/ELF/Output/strip-preserve-atime.test.tmp-nondwo
-rw-r--r--  1  primarygroup   904 Aug 22 15:31 /Users/g/llvm-toolchain/out/stage2/test/tools/llvm-objcopy/ELF/Output/strip-preserve-atime.test.tmp-dwo
-rw-r--r--  1  primarygroup  3568 Aug 22 15:31 /Users/g/llvm-toolchain/out/stage2/test/tools/llvm-objcopy/ELF/Output/strip-preserve-atime.test.tmp-input.dwo
-rw-r--r--  1  primarygroup  2880 Aug 22 15:31 /Users/g/llvm-toolchain/out/stage2/test/tools/llvm-objcopy/ELF/Output/strip-preserve-atime.test.tmp-nondwo
macbookpro:stage2  
```

**Comment by hiraditya** [comment]
I guess the fix here is to disable this test on darwin?

**Comment by hiraditya** [comment]
Disabling the test for darwin: https://reviews.llvm.org/D158560

**Comment by bogner** [comment]
This test is largely unchanged since it's introduction in 2018 and I've never seen it fail, so I'm not really convinced that the claim that atime doesn't work reliably on macOS is accurate. Is there maybe something more specific about your setup that could explain this?

**Comment by hiraditya** [comment]
I'm using Mac M1 machine and it fails during local testing.

**Comment by bogner** [comment]
Okay... I am also on a Mac M1 machine and it doesn't fail. I've been running LLVM tests frequently on various different macs since before these tests were introduced and I've never seen these tests fail. I don't think it makes sense to disable this test for darwin unless the issue you're running into is understood (or if there's evidence that it's widespread)

**Comment by hiraditya** [comment]
can't reproduce it reliably. closing it.
