### ISSUE TITLE
Cherry-pick fixes for clang/test/Driver/x86-no-gather-no-scatter.cpp

### ISSUE THREAD

**Issue by nathanchance** [llvm/llvm-project#64903]
993bdb047c90e9b85fb91578349a9faf4f6a853d was applied to `release/17.x` as de0f8c265cef662a6acc6d09823d1d461a1bc8b9 but the fixes for `clang/test/Driver/x86-no-gather-no-scatter.cpp` were not applied (b7cf9bbfde5e623e16fe8669e18aa34cbb3afafa, 547ee1c81fceaabcb7064ed525f11f9e94083f56). Without the first fix, `check-clang` fails for `llvmorg-17.0.0-rc3` on an arm64 machine. I can verify the cherry-pick fixes the issue. While I have not verified the macOS failure/fix, I see no reason to believe that it would not be present in `llvmorg-17.0.0-rc3`.

/cherry-pick b7cf9bbfde5e623e16fe8669e18aa34cbb3afafa 547ee1c81fceaabcb7064ed525f11f9e94083f56

**Comment by h-vetinari** [comment]
According to the discussion in https://github.com/llvm/llvm-project-release-prs/pull/629, this looks like it's done? I'm commenting because this is the only issue in the board that has "Status: Done" while still being open.

**Comment by tru** [comment]
Correct this is done. It was just missed with all the different changes to this patch.
