### ISSUE TITLE
Move the bug tracker back to the Bugzilla

### ISSUE THREAD

**Issue by KOLANICH** [llvm/llvm-project#64911]
>LLVM Bugzilla is read-only and represents the historical archive of all LLVM issues filled before November 26, 2021. Use github to submit LLVM bugs

GitHub is going to force all its users to use 2FA:

> GitHub users are now required to enable two-factor authentication as an additional security measure. Your activity on GitHub includes you in this requirement. You will need to enable two-factor authentication on your account before October 06, 2023, or be restricted from account actions.

Some users don't benefit from using 2FA and only get additional unnecessary risks because of it. It is unethical and power-abusing behaviour GitHub side to demand it, and some users would prefer not to use GitHub and not to have its account.

It may make sense to move the bug tracker back to the Bugzilla.

**Comment by EugeneZelenko** [comment]
What about planned migration from Phabricator to GitHub?

**Comment by DimitryAndric** [comment]
I think at this point, the llvm project is fully married to GitHub, and simply said, if you cannot use GitHub (for whatever reason), you cannot contribute to this project. That is the consequence of the choice made some time ago to move most (or even all) project hosting out of llvm's ownership.

**Comment by KOLANICH** [comment]
And of course a more sane approach is not to marry at all.

**Comment by llvm-beanz** [comment]
We are not going to do this.
