### ISSUE TITLE
[clang-tidy] cppcoreguidelines-avoid-reference-coroutine-parameters false positives on lamdbas

### ISSUE THREAD

**Issue by rockwotj** [llvm/llvm-project#64915]
Reproducer: https://godbolt.org/z/68xKvTWff
Check: https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/avoid-reference-coroutine-parameters.html

Right now the reference coroutine parameter check is too over aggressive in that lambda function parameters that are not coroutines are also checked and reported.

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D158665
