### ISSUE TITLE
LLVM 17 release notes do not discuss removal of `llvm/Transforms/IPO/PassManagerBuilder.h`

### ISSUE THREAD

**Issue by elliottslaughter** [llvm/llvm-project#64912]
In LLVM 17.0.0-rc3, `llvm/Transforms/IPO/PassManagerBuilder.h` is entirely gone, and `find`/`grep` through the install directory cannot locate it. But the [release notes](https://github.com/llvm/llvm-project/blob/release/17.x/llvm/docs/ReleaseNotes.rst) do not discuss it at all.

Since it's a pretty big piece of machinery it seems like it would be nice to mention it and point to alternatives?

**Comment by tru** [comment]
@nikic @aeubanks can we get a note for this?

**Comment by elliottslaughter** [comment]
Just a small update: I found this note in the LLVM release notes:

> The legacy optimization pipeline has been removed.

That seems to be consistent with what I reported above. Therefore, strictly speaking, there is a mention of this in the release notes. However, this is such a large removal that I think it would be nice to say more, and especially (if possible) to point to any instructions on what the replacement should be and how to use it. This is doubly true because I had not been getting deprecation warnings on early versions of LLVM (e.g., I don't think I ever saw a warning about this in LLVM 16), so users may be caught unaware and may not know what to do when the headers simply go missing.

**Comment by rxguy** [comment]
This is affecting the building of Mesa.

See [FTBFS: after switching to llvm 17.0.0~rc3 from llvm 16.0.6](https://gitlab.freedesktop.org/mesa/mesa/-/issues/9734)

**Comment by lorn10** [comment]
Yeah and the final fix is probably [Mesa MR 24879](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/24879) "clover/llvm: move to modern pass manager". :+1: 

But unfortunately this new feature introduces some flaws in clover. Whatever, we will see if those will get fixed or not but the building problem of Mesa with LLVM 17 should be with that MR definitely resolved.

**Comment by aeubanks** [comment]
Sorry I've been busy, I'll try to find some time to write up migration instructions. Trying to figure out how to submit a patch to the 17 release branch given that main didn't have any release notes for this.

**Comment by tru** [comment]
I wrote some guidance here: https://discourse.llvm.org/t/llvm-17-x-release-notes-update/72292?u=tobiashieta

**Comment by tru** [comment]
Thanks for the fix @aeubanks !
