### ISSUE TITLE
Readability check to suggest replacement of conditional statement with std::min/std::max

### ISSUE THREAD

**Issue by EugeneZelenko** [llvm/llvm-project#64914]
It'll be great to add a readability check to suggest the replacement of conditional statements with `std::min/std::max`. For example:

```cpp
if (value1 < value2)
  value1 = value2; // value1 = std::max(value1, value2);
if (value2 < value1)
  value1 = value2; // value1 = std::min(value1, value2);
```

`value2` may be expression, number, etc.

See also PyLint's [consider-using-min-builtin](https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/consider-using-min-builtin.html) and [consider-using-max-builtin](https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/consider-using-max-builtin.html).

**Comment by PiotrZSL** [comment]
But code like this:
```
if (value1 < value2)
  value = value2;
else
  value = value1;
```

could be replaced.... with min/max,
same as:
```
value = (value1 < value2) ? value1 : value2;
```

**Comment by carlosgalvezp** [comment]
Readability checks should not be concerned about performance though.
