### ISSUE TITLE
RecursiveASTVisitor (RAV) fails to visit the initializer of a bitfield

### ISSUE THREAD

**Issue by smcpeak** [llvm/llvm-project#64916]
For this example:

```c++
struct S {
  int x : 8 = 123;
};
```

`RecursiveASTVisitor` will visit the `8` but not the `123`.

This is observed when using Clang+LLVM-16.0.0 and when using a trunk source build from 2023-07-14.

The following diff is sufficient to fix the bug in my testing:

```diff
--- clang/AST/RecursiveASTVisitor.h.orig
+++ clang/AST/RecursiveASTVisitor.h
@@ -2124,7 +2124,7 @@
   TRY_TO(TraverseDeclaratorHelper(D));
   if (D->isBitField())
     TRY_TO(TraverseStmt(D->getBitWidth()));
-  else if (D->hasInClassInitializer())
+  if (D->hasInClassInitializer())
     TRY_TO(TraverseStmt(D->getInClassInitializer()));
 })

```

although I would think an automated test should be added as well.

I believe the problem was introduced in commit 6b8e3c02ca44f when the possibility of initialized bitfields was added, but the logic in `RecursiveASTVisitor` was not updated.

(To be clear, I'm not volunteering to fix this issue, I'm just reporting it.)

**Comment by NoumanAmir657** [comment]
I want to work on this issue. How can I be assinged it?

**Comment by NoumanAmir657** [comment]
patch: https://reviews.llvm.org/D158616

**Comment by NoumanAmir657** [comment]
@smcpeak can you tell what test you used to differentiate?

**Comment by smcpeak** [comment]
I did not use any of the tests in the clang repo.  I'm working on my own tool that uses clang as a library, and in particular uses `RecursiveASTVisitor` (RAV) to explore the AST.  In that context, I noticed that it failed to traverse the initializer expression.  If you just want to see it misbehave, make a tool that uses RAV and prints out every `Expr` node.  But I don't know if that would be a good basis for a clang automated test (my guess is there's an existing RAV test that can be adapted).

**Comment by NoumanAmir657** [comment]
> I did not use any of the tests in the clang repo.  I'm working on my own tool that uses clang as a library, and in particular uses `RecursiveASTVisitor` (RAV) to explore the AST.  In that context, I noticed that it failed to traverse the initializer expression.  If you just want to see it misbehave, make a tool that uses RAV and prints out every `Expr` node.  But I don't know if that would be a good basis for a clang automated test (my guess is there's an existing RAV test that can be adapted).
> 

Okay. Thanks for the info.

**Comment by NoumanAmir657** [comment]
@smcpeak doing an AST dump should show the difference. Right?
Not saying that it should be used as a test but the AST dump should be different for before and after fix. Right?

**Comment by smcpeak** [comment]
No, the text dump produced by `clang -Xclang -ast-dump -fsyntax-only` won't show a difference, because that is produced by `ASTNodeTraverser`, not `RecursiveASTVisitor`, and `ASTNodeTraverser` already gets this case right.  (See issue #64820 for another example of how they differ.)

**Comment by xgupta** [comment]
I think this is fixed in trunk, I checked with below test case on release/17.x and test case is passing with suggested fix but not without. 

But in trunk suggested fix is not required and it passes.
```
//===- unittest/Tooling/RecursiveASTVisitorTests/BitfieldInitializer.cpp -===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "TestVisitor.h"
#include <string>

using namespace clang;

namespace {

// Check to ensure that bitfield initializers are visited.
class BitfieldInitializerVisitor : public ExpectedLocationVisitor<BitfieldInitializerVisitor> {
public:
  bool VisitIntegerLiteral(IntegerLiteral *IL) {
    Match(std::to_string(IL->getValue().getSExtValue()), IL->getLocation());
    return true;
  }
};

TEST(RecursiveASTVisitor, BitfieldInitializerIsVisited) {
  BitfieldInitializerVisitor Visitor;
  Visitor.ExpectMatch("123", 2, 15); 
  EXPECT_TRUE(Visitor.runOver(
    "struct S {\n"
    "  int x : 8 = 123;\n"
    "};\n"));
}

} // end anonymous namespace
```

**Comment by smcpeak** [comment]
@xgupta Which trunk commit did you test when finding that it appears to be fixed?

**Comment by xgupta** [comment]
> @xgupta Which trunk commit did you test when finding that it appears to be fixed?

I see, it was a mistake in reading the failed test case result, I see the latest main branch built the test case and thought it also ran it so abort the `ninja check-clang` when regression tests started but later realized that the unit test case ran later and then result cames.

So now I completed the `ninja clang-check` to verify suggested change is required to fix the issue.
