### ISSUE TITLE
[llvm-rc] Wrong Clang executable picked after commit 8c6a0c8

### ISSUE THREAD

**Issue by kleisauke** [llvm/llvm-project#64927]
After commit 8c6a0c8bf50bca6c3a0c4de1b84f21466ee31655 (cherry-picked in LLVM 17.0.0-rc3) the wrong Clang executable is selected in llvm-rc when using this directory format:
```console
$ cat /data/mxe/usr/bin/x86_64-w64-mingw32.static-windres
#!/bin/sh
exec "/data/mxe/usr/x86_64-w64-mingw32.static/bin/x86_64-w64-mingw32-windres" "$@"
$ tree /data/mxe/usr -L 3 --dirsfirst
├── bin
│   └── x86_64-w64-mingw32.static-windres
├── x86_64-w64-mingw32.static
│   └── bin
│        ├── clang-target-wrapper.sh
│        ├── x86_64-w64-mingw32-clang -> clang-target-wrapper.sh
│        └── x86_64-w64-mingw32-windres -> /data/mxe/usr/x86_64-pc-linux-gnu/bin/llvm-windres
└── x86_64-pc-linux-gnu
    └── bin
        ├── clang -> clang-17
        ├── clang-17
        ├── llvm-rc
        └── llvm-windres -> llvm-rc

```

With LLVM 17.0.0-rc3 it picks the non-sysroot aware `/data/mxe/usr/x86_64-pc-linux-gnu/bin/clang-17` instead of `/data/mxe/usr/x86_64-w64-mingw32.static/bin/x86_64-w64-mingw32-clang`, which is unexpected.
```
access("/proc/self/exe", F_OK)          = 0
readlink("/proc/self/exe", "/data/mxe/usr/x86_64-pc-linux-gn"..., 4096) = 45
lstat("/data", {st_mode=S_IFDIR|0755, st_size=12288, ...}) = 0
lstat("/data/mxe", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/data/mxe/usr", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/data/mxe/usr/x86_64-pc-linux-gnu", {st_mode=S_IFDIR|0755, st_size=99, ...}) = 0
lstat("/data/mxe/usr/x86_64-pc-linux-gnu/bin", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/data/mxe/usr/x86_64-pc-linux-gnu/bin/llvm-rc", {st_mode=S_IFREG|0755, st_size=759536, ...}) = 0
access("/data/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32-clang", R_OK|X_OK) = -1 ENOENT (No such file or directory)
access("/data/mxe/usr/x86_64-pc-linux-gnu/bin/clang-17", R_OK|X_OK) = 0
stat("/data/mxe/usr/x86_64-pc-linux-gnu/bin/clang-17", {st_mode=S_IFREG|0755, st_size=128354312, ...}) = 0
access("/data/mxe/usr/x86_64-pc-linux-gnu/bin/clang-17", F_OK) = 0
```

/cc @mstorsjo

**Comment by mstorsjo** [comment]
Hmm, this is unfortunate - although that commit only made the code do what it was originally meant to do.

The current (and previous even if it didn't work out right) logic is this:
- Look for `<triple>-clang`, `clang-<version>`, `clang`, `clang-cl` in the same directory as the `llvm-windres`/`llvm-rc` executable
- Look for `clang` and `clang-cl` anywhere in `$PATH`

Before that commit, I guess it used whatever base path that was set in `argv[0]` by the caller, instead of the actual executable directory. But in that case, the path `Parent` in the code (used as base directory for the first round of searches) would have been `/data/mxe/usr/x86_64-w64-mingw32/bin` - and based on your explanation, there's no `<triple>-clang` there, so I don't see how it ever could have found `/data/mxe/usr/bin/x86_64-w64-mingw32-clang`.

I'm wondering what the best way would be, to extend the search logic to cope with your case. I'm pretty convinced that we should be looking in the directory of the actual executable (otherwise we won't find a clang executable that is colocated with the llvm-rc executable in a nondefault directory), but should we look in `dirname(argv[0])` as well in addition to it?

That wound be something like this, in pseudocode:
```
MainExecPath = llvm::sys::fs::getMainExecutable();
SearchPaths.push_back(dirname(MainExecPath));
Argv0Path = dirname(argv[0]);
if (Argv0Path)
    SearchPaths.push_back(Argv0Path);
for (name : {"<triple>-clang", "clang-<version>", "clang", "clang-cl"}) {
  for (path : SearchPaths) {
    if (found(path/name))
      return path/name;
}
for (name : {"clang", "clang-cl"}) {
    if (path = foundInPath(name))
      return path;
}
```

Alternatively, I guess we could look for `<triple>-clang` in `$PATH` as well, if that would help finding it in your case? That would be a quite straightforward addition. (That would at least allow you to inject the right directory into `$PATH` in the 2-line shellscript that execs `llvm-windres` I guess?)

**Comment by mstorsjo** [comment]
> > But in that case, the path `Parent` in the code (used as base directory for the first round of searches) would have been `/data/mxe/usr/x86_64-w64-mingw32/bin` - and based on your explanation, there's no `<triple>-clang` there, so I don't see how it ever could have found `/data/mxe/usr/bin/x86_64-w64-mingw32-clang`.
> 
> Ah, you're right. I updated my initial post.

Thanks, that makes it clearer!

> > I'm wondering what the best way would be, to extend the search logic to cope with your case. I'm pretty convinced that we should be looking in the directory of the actual executable (otherwise we won't find a clang executable that is colocated with the llvm-rc executable in a nondefault directory), but should we look in `dirname(argv[0])` as well in addition to it?
> 
> I'm not sure what is the best way to deal with this. For now, I could resolve this by creating a hard link (instead of a symbolic link) with `/data/mxe/usr/x86_64-pc-linux-gnu/bin/llvm-windres` as source and `/data/mxe/usr/x86_64-w64-mingw32.static/bin/x86_64-w64-mingw32-windres` as target. This ensures `/proc/self/exe` would not resolve to `/data/mxe/x86_64-pc-linux-gnu/llvm-rc`.

Hmm, I guess that works, although it's a bit clunky - I'm personally not really a fan of hardlinks, as they're quite hard to deal with wrt packing/unpacking/moving around.

A different way of working around it, would be to explicitly point out the preprocessor tool in your wrapper shell script. This is a bit nonobvious though. There's an option `--preprocessor` that you can use to point out what to execute - but with this option, you don't specify just the tool, but the tool and a bunch of the default arguments as well. See https://github.com/llvm/llvm-project/blob/llvmorg-17.0.0-rc3/llvm/test/tools/llvm-rc/windres-preproc.test#L8 and https://github.com/llvm/llvm-project/blob/llvmorg-17.0.0-rc3/llvm/tools/llvm-rc/llvm-rc.cpp#L256-L258. So for your case, you could do `--preprocessor "/path/to/x86_64-w64-mingw32-clang -E -xc -DRC_INVOKED"`.

This option is a bit controversial though, as it changed behaviour in GNU windres a couple years ago. The option was documented to behave this way, and practically did that too. But at one point, they changed both the documentation and the implementation to make the option just specify the tool executable and nothing else - without regards for users who might have been using it according to the old documentation. llvm-windres still tracks the old behaviour though. (ffmpeg used to be using the option according to the old behaviour.) So for user code, I would recommend against using the option as it does behave inconsistently across tools. But for your case where you're fairly tightly tied to llvm-windres, it might be fine. (If we ever decide to change llvm-windres to follow suit wrt the behaviour change, you'd need to change your wrapper accordingly at that point.)

**Comment by kleisauke** [comment]
Thinking about this further, this could be easily resolved by doing:
```diff
--- a/data/mxe/usr/bin/x86_64-w64-mingw32.static-windres
+++ b/data/mxe/usr/bin/x86_64-w64-mingw32.static-windres
@@ -1,2 +1,2 @@
 #!/bin/sh
-exec "/data/mxe/usr/x86_64-w64-mingw32.static/bin/x86_64-w64-mingw32-windres" "$@"
+exec "/data/mxe/usr/x86_64-w64-mingw32.static/bin/x86_64-w64-mingw32-windres" --preprocessor-arg="--sysroot=/data/mxe/usr/x86_64-w64-mingw32.static" "$@"
```
(see e.g. commit https://github.com/libvips/build-win64-mxe/commit/ab58016a76c611f75494348982f241b5c1eb9345)

This ensures that clang is aware of the sysroot and is able to find the MinGW-w64 headers (such as `winver.h`).

I'll close, it's probably more reliable to depend on `readlink("/proc/self/exe", exe_path, sizeof(exe_path))` than `argv[0]`, as you said.

**Comment by mstorsjo** [comment]
> Thinking about this further, this could be easily resolved by doing:
> 
> ```diff
> --- a/data/mxe/usr/bin/x86_64-w64-mingw32.static-windres
> +++ b/data/mxe/usr/bin/x86_64-w64-mingw32.static-windres
> @@ -1,2 +1,2 @@
>  #!/bin/sh
> -exec "/data/mxe/usr/x86_64-w64-mingw32.static/bin/x86_64-w64-mingw32-windres" "$@"
> +exec "/data/mxe/usr/x86_64-w64-mingw32.static/bin/x86_64-w64-mingw32-windres" --preprocessor-arg="--sysroot=/data/mxe/usr/x86_64-w64-mingw32.static" "$@"
> ```
> 
> (see e.g. commit [libvips/build-win64-mxe@ab58016](https://github.com/libvips/build-win64-mxe/commit/ab58016a76c611f75494348982f241b5c1eb9345))
> 
> This ensures that clang is aware of the sysroot and is able to find the MinGW-w64 headers (such as `winver.h`).

Oh, indeed, that's both clearer and simpler than using `--preprocessor`.
 
> I'll close, it's probably more reliable to depend on `readlink("/proc/self/exe", exe_path, sizeof(exe_path))` than `argv[0]`, as you said.

Thanks for reporting in any case!

**Comment by mstorsjo** [comment]
FYI, someone else also ran into a regression from the same - in https://reviews.llvm.org/D158901 there's a patch implementing the same fix strategy that I outlined above, which is likely to make it into 17.0.0.
