### ISSUE TITLE
[C++] Side effect get removed if the return type of a unary operator is `std::nullptr_t`

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#64923]
This comes from https://github.com/llvm/llvm-project/issues/58459 but I find it is not related to coroutines after I reduce it.

Reproducer: https://godbolt.org/z/TGefxv5e5

From the generated code, we can see the call to `DoAnotherThing()` is elided incorrectly.

And if we change the return type of `operator++`, we can find the problem is gone: https://godbolt.org/z/TGefxv5e5

While I tagged `codegen`, I feel like this is a frontend issue.

CC people since I know not so many people subscribed to the `c++` tag: @AaronBallman @cor3ntin @Endilll @erichkeane

**Comment by jacobsa** [comment]
Thanks for reducing! Here is a [corrected link](https://godbolt.org/z/9bEfzPafo) for what I think you meant about changing the return type (your post currently has the same link twice).

**Comment by tbaederr** [comment]
Most likely a problem in the constant interpreter, since this works with `-fexperimental-new-constant-interpreter`: https://godbolt.org/z/had1nPz1j

**Comment by cor3ntin** [comment]
We don't bother evaluating either side of the expression when we know the type is nullptr_t
https://github.com/llvm/llvm-project/blob/main/clang/lib/AST/ExprConstant.cpp#L13307-L13313

Fix shortly, i just need to write a test!

**Comment by cor3ntin** [comment]
https://reviews.llvm.org/D158601

**Comment by jacobsa** [comment]
Thank you for the quick fix!
