### ISSUE TITLE
Model conversion failed

### ISSUE THREAD

**Issue by xiangyun-hz** [llvm/llvm-project#64924]
模型转换过程中
===group_idx: 104move tensor op_168_0_Add_f32 from timestep 1 to timestep 7merge timestep 2 to timestep 1
merge timestep 3 to timestep 2
merge timestep 3 to timestep 2
merge timestep 3 to timestep 2
==---------------------------==
Run GroupDataMoveOverlapPass : 
    Overlap data move between two layer group
==---------------------------==
tpuc-opt: ../lib/Backend/BM168x/BM168x.cpp:225: static void tpu_mlir::backend::BM168x::fix_shape(tensor_spec_t&, const std::vector<long int, std::allocator<long int> >&): Assertion `new_num == old_num' failed.

**Comment by DimitryAndric** [comment]
(Translation provided by Google Translate, please correct any mistakes)
> During model conversion

**Comment by dtcxzyw** [comment]
Please create an issue in the repo [sophgo/tpu-mlir](https://github.com/sophgo/tpu-mlir).
