### ISSUE TITLE
Compilation hangs in `TargetLowering::SimplifySetCC`

### ISSUE THREAD

**Issue by chfast** [llvm/llvm-project#64935]
```llvm
target triple = "riscv32"

define i1 @f() {
  %B25 = shl i64 4294967296, -9223372036854775808
  %B13 = sub i64 -1, -9223372036854775808
  %C8 = icmp ugt i64 %B13, %B25
  %B5 = sub i64 0, 4294967296
  ret i1 %C8
}
```
https://godbolt.org/z/1n9PKa1ov

When compiling for riscv32 with llc the SDAG hits an infinite loop in `TargetLowering::SimplifySetCC` at [`llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:5098`](https://github.com/llvm/llvm-project/blob/71a7192d6927b422c224f5d231300774cb02348a/llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp#L5098).

**Comment by dtcxzyw** [comment]
Candidate patch: https://reviews.llvm.org/D158654
