### ISSUE TITLE
An exception occurred when the program started

### ISSUE THREAD

**Issue by jackie-weiwei** [llvm/llvm-project#64932]
When I use LLDB to debug the program, the program throws the following exception when it is just started:

LdrInitShimEngineDynamic (@LdrInitShimEngineDynamic:596)

Exception has occurred: Exception
Exception 0x4000001f encountered at address 0x77511bb2

My environment is windows10, vscode, LLVM-16.0.0-win32,

launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "clang++.exe - Build and debug active file",
            "type": "lldb",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopOnEntry": false,
            "cwd": "${workspaceFolder}",
            "preLaunchTask": "C/C++: clang++.exe build active file",
            "suppressMultipleSessionWarning": false,
            "expressions": "native"
        }
    ]
}

tasks.json:
{
    "tasks": [
        {
            "type": "shell",
            "label": "C/C++: clang++.exe build active file",
            "command": "C:\\Program Files (x86)\\LLVM\\bin\\clang++.exe",
            "args": [
                "-g",
                "main.cpp",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger.",
        }
    ],
    "version": "2.0.0"
}

@LdrInitShimEngineDynamic:

77511B85: C9                         leave  
77511B86: C3                         retl   
77511B87: 6A 0C                      pushl  $0xc
77511B89: 68 30 CE 56 77             pushl  $0x7756ce30  ; imm = 0x7756CE30 
77511B8E: E8 21 62 FD FF             calll  0x774e7db4  ; EtwpGetCpuSpeed + 20
77511B93: 6A 00                      pushl  $0x0
77511B95: 6A 01                      pushl  $0x1
77511B97: 8D 45 E7                   leal   -0x19(%ebp), %eax
77511B9A: 50                         pushl  %eax
77511B9B: 6A 11                      pushl  $0x11
77511B9D: 6A FE                      pushl  $-0x2
77511B9F: E8 FC 10 FC FF             calll  0x774d2ca0  ; NtQueryInformationThread
77511BA4: 85 C0                      testl  %eax, %eax
77511BA6: 78 1B                      js     0x77511bc3  ; <+1779>
77511BA8: 80 7D E7 00                cmpb   $0x0, -0x19(%ebp)
77511BAC: 75 15                      jne    0x77511bc3  ; <+1779>
77511BAE: 83 65 FC 00                andl   $0x0, -0x4(%ebp)
77511BB2: CC                         int3   
### _**77511BB3: EB 07                      jmp    0x77511bbc  ; <+1772>**  //exception stop this line_
77511BB5: 33 C0                      xorl   %eax, %eax
77511BB7: 40                         incl   %eax
77511BB8: C3                         retl   
77511BB9: 8B 65 E8                   movl   -0x18(%ebp), %esp
77511BBC: C7 45 FC FE FF FF FF       movl   $0xfffffffe, -0x4(%ebp)  ; imm = 0xFFFFFFFE 
77511BC3: 8B 4D F0                   movl   -0x10(%ebp), %ecx
77511BC6: 64 89 0D 00 00 00 00       movl   %ecx, %fs:0x0
77511BCD: 59                         popl   %ecx
77511BCE: 5F                         popl   %edi
77511BCF: 5E                         popl   %esi
77511BD0: 5B                         popl   %ebx
77511BD1: C9                         leave  
77511BD2: C3                         retl   
77511BD3: 64 A1 30 00 00 00          movl   %fs:0x30, %eax
77511BD9: 33 C9                      xorl   %ecx, %ecx
77511BDB: 89 0D B4 67 58 77          movl   %ecx, 0x775867b4
77511BE1: 89 0D B8 67 58 77          movl   %ecx, 0x775867b8
77511BE7: 88 08                      movb   %cl, (%eax)

**I tried LLVM-16.0.0-win64 without this problem, but when debugging with LLVM-16.0.0-win64, press the F10 key, it will jump to the assembly code, I don’t know why this happens, how can I solve it？ Thank you very much!!!**

**Comment by DavidSpickett** [comment]
> I tried LLVM-16.0.0-win64 without this problem

Looking for LdrInitShimEngineDynamic online, a few places talk about it coming up when using a 32 bit GDB to debug a 64 bit process. So switching to the 64 bit build of lldb is the right idea here.

> press the F10 key, it will jump to the assembly code

Going by vscode's default keybinds, this is "Step Over". This is going to need debug information to know where each line of the source begins and ends, so missing debug information is the likely problem. Without it, stepping to the next assembly instruction is very likely our fallback.

In general, it is a good idea to try debugging outside of vscode, using just lldb, and see if that works. Can you try that?

It may be that the application needs to be built with debug mode, or the right format of debug information that lldb can read.

**Comment by jackie-weiwei** [comment]
Hi, I tried the following:
1. When using 32-bit LLVM to compile and generate 32-bit program debugging, LdrInitShimEngineDynamic exception will appear;
2. Compile with 32-bit LLVM to generate 64-bit program debugging without any problem
3. Using 64-bit LLVM to compile and generate 32-bit program debugging will cause LdrInitShimEngineDynamic exception;
4. Compile with 64-bit LLVM to generate 64-bit program debugging without any problem;

But I don't know why the 32-bit target program has LdrInitShimEngineDynamic exception?

**Comment by DavidSpickett** [comment]
I see https://github.com/vadimcn/codelldb/issues/751 suggests that `stopOnEntry` is set but you have it disabled so it's not that.

`0x4000001f` is `STATUS_WX86_BREAKPOINT` which I understand to be the status code sent from a process running under 32 bit emulation on a 64 bit system. LLDB does reference this value in a few places so at least at one point someone tried to make it work, even if it doesn't today.

Are you able to continue from that point? LLDB may report the exception but that doesn't always mean you can't carry on.

It is likely that 32 bit -> 32 bit debugging is not regularly tested (and not on a 32 bit system) and 64 bit -> 32 bit debugging even less so.

If you have the time to make a simple reproducer that involves only a simple program and lldb itself, then someone may find the time to investigate.

In the meantime if you can, I'd pick a configuration that does work and stick to it. Or you could try GDB, which seems to handle this exception type too. Indeed, if the same happens with GDB, that could be useful to know.
