### ISSUE TITLE
[UBSan] Runtime Executable Only violation hit when checking the function pointer on an execute-only target.

### ISSUE THREAD

**Issue by MaggieYingYi** [llvm/llvm-project#64931]
An execute-only target disallows data access to code sections.

The commit [rG279a4d](https://reviews.llvm.org/rG279a4d0d67c874e80c171666822f2fabdd6fa926) causes the generated code to read text section data which is not allowed on an execute-only target.

When enabling the function sanitizer (`-fsanitize=function`), UBSan function signatures and type hashes are emitted within the function's prologue data to check the function type. This results in the non-execute access and a runtime error.

**Comment by MaggieYingYi** [comment]
[D158614](https://reviews.llvm.org/D158614) is created for code review.

**Comment by MaskRay** [comment]
/cherry-pick 9ef536a12ea65a2b9e2511936327c7b621af38fb d26dd681f9726ed7d43d7c0bdd8ee3cb2db69a2b 39f6a31eaa665b1a01305346092ed69f4b9f940a c7dce0283b5b502dacd47eb1488342a31f4ed35a

**Comment by MaskRay** [comment]
`release/17.x` does not contain `-###` exit code change in clang/lib/Driver (https://reviews.llvm.org/D156363).

Here is a modified fix:

/branch MaskRay/llvm-project/17.x-mexecute-only

**Comment by tru** [comment]
I merged your branch manually @MaskRay
