### ISSUE TITLE
[RISCV] Fix assertion failure when zcmp extension is enabled.

### ISSUE THREAD

**Issue by garvitgupta08** [llvm/llvm-project#64947]
Before accessing "getOpcode" thorugh machine instruction, check if the iterator
has reached the end of Machine basic block otherwise we will crash at the
assertion !NodePtr->isKnownSentinel().

The above assertion is hit in "Prologue/Epilogue Insertion & Frame Finalization
pass".

Differential - https://reviews.llvm.org/D158256

**Comment by garvitgupta08** [comment]
@topperc @anmolparalkar-nxp  can you add this to release milestone so that cherrypick can be successful. It seems I do not have access to do it.

**Comment by EugeneZelenko** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/fdef7952cbc26fd31d0d92a4f14dde58bc461fe9
