### ISSUE TITLE
scanf format attribute type confusion with char/bool

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#64987]
The scanf format attribute currently issues no diagnostics when confusing a `bool` value and a `char` specifier, though GCC does diagnose. Consider:
```
void foo(void) {
    bool b;
    scanf("%hhi", &b);
}
```
https://godbolt.org/z/jrcKzPb9r

Clang emits no diagnostic in this case, while GCC emits `format '%hhi' expects argument of type 'signed char *', but argument 2 has type '_Bool *'`

Perhaps Clang should diagnose similar to GCC?

**Comment by AaronBallman** [comment]
Many thanks to @apple-fcloutier for spotting this issue during the review of https://reviews.llvm.org/D158318#4615285.

**Comment by apple-fcloutier** [comment]
Also, I thought about it yesterday evening and I've convinced myself that it really shouldn't be allowed. This can easily store a value other than 0 or 1 in the `bool`'s storage unit, which we've observed to lead to security issues through memory corruption not so long ago. (I don't think that it's a terribly high-priority thing to fix, but I wanted to communicate that I now think there's a clear answer to whether it should be done.)

**Comment by AaronBallman** [comment]
I agree, I think we should diagnose this by default.

**Comment by Fznamznon** [comment]
https://reviews.llvm.org/D159279
