### ISSUE TITLE
Merge "[llvm-exegesis] Use mmap2 when mmap is unavailable to fix riscv32 build" into release/17.x

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#64994]
/cherry-pick 01a92f06f23585f15b3e83b7c378d0df2d91e06b

This fixes build failures for some newer 32-bit architectures of Linux like riscv32 where mmap2 is defined while mmap isn't.

@kraj @boomanaiden154 @legrosbuffle

**Comment by kraj** [comment]
> /cherry-pick [01a92f0](https://github.com/llvm/llvm-project/commit/01a92f06f23585f15b3e83b7c378d0df2d91e06b)
> 
> This fixes build failures for some newer 32-bit architectures of Linux like riscv32 where mmap2 is defined while mmap isn't.
> 
> @kraj @boomanaiden154 @legrosbuffle

thanks. This  fixes 17.x branch builds for rv32
