### ISSUE TITLE
clang-tidy-diff.py should exit with a failure code when there are errors

### ISSUE THREAD

**Issue by FlashSheridan** [llvm/llvm-project#65000]
Similarly to #28002 for clang-tidy, clang-tidy-diff.py should have an option to exit with a failure code when there are errors; this would make our GitHub Action much simpler.  Even with WarningsAsErrors set, I get “1 warning treated as error” but a 0 return code; even in quiet mode there some output even if there are no warnings, which would complicate the workaround I was contemplating.

**Comment by PiotrZSL** [comment]
https://reviews.llvm.org/D158929
If someone could test it, it would be nice.
