### ISSUE TITLE
[clang-format] `AlignOperands: false` Still aligns the stream operator

### ISSUE THREAD

**Issue by AidanWelch** [llvm/llvm-project#65008]
Expected:
```cpp
std::cout << 1 << 1 << 1 << 1 << 1 << 1 <<
    1 << 1 << 1 << 1 << 1 << 1;
```
Result:
```cpp
std::cout << 1 << 1 << 1 << 1 << 1 << 1
          << 1 << 1 << 1 << 1 << 1 << 1;
```
[This has persisted for over 7 years](https://stackoverflow.com/questions/38699555/clang-format-stream-output)

**Comment by PiotrZSL** [comment]
This has nothing to do with clang-tidy.

**Comment by AidanWelch** [comment]
> This has nothing to do with clang-tidy.

Oh sorry that was a typo I thought I had written clang-format

**Comment by owenca** [comment]
Duplicate of #67897

**Comment by AidanWelch** [comment]
Isn't that issue a duplicate of this rather than the other way around?

**Comment by owenca** [comment]
They are duplicate of each other, but I left the other open because it got more info and referenced two more issues.
