### ISSUE TITLE
Live AND erased after cmpxchg + branch on RISC-V

### ISSUE THREAD

**Issue by MaxHearnden** [llvm/llvm-project#65025]
on llvm 16.0.6 run `llc --march riscv64 --mattr=+a -O3 test.ll`
test.ll
```
define ptr @cmpxchg_masked_and_branch1(ptr %ptr, i8 signext %cmp, i8 signext %val) nounwind {

do_cmpxchg:
  %0 = cmpxchg ptr %ptr, i8 %cmp, i8 %val seq_cst seq_cst
  %1 = extractvalue { i8, i1 } %0, 1
  %2 = select i1 %1, ptr %ptr, ptr null
  br i1 %1, label %returnptr, label %exit
returnptr:
  ret ptr %2
exit:
  ret ptr null
}
```
repeat with the branch and labels removed to see the missing AND.
This was introduced in https://github.com/llvm/llvm-project/commit/ce381281940fb6a9cc2fa1a16fa36bf0911f43f1

**Comment by topperc** [comment]
Candidate patch https://reviews.llvm.org/D158962
