### ISSUE TITLE
Backport  #64460 for LLVM 17.x:  LLVM ERROR: Cannot select: t391: v16f32 = fp_extend t442 where t442: v16bf16 #64460

### ISSUE THREAD

**Issue by joker-eph** [llvm/llvm-project#65032]
See #64460

**Comment by joker-eph** [comment]
Actually, this is fixing the crash, but likely mis-compiling now, not sure if it is ready to back port.

**Comment by phoebewang** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/6688701497ea8e562b769bdb154a40f4a1099abb

**Comment by joker-eph** [comment]
Test is passing at HEAD on my machine, so your sequence of patches is fixing it! Thanks @phoebewang
