### ISSUE TITLE
[aarch64][bug] Different results of big and little endian's loop vectorize testcase on clang-15.x

### ISSUE THREAD

**Issue by Jolyon0202** [llvm/llvm-project#65058]
Here is our testcast:

```
unsigned char bitmap;
unsigned segNum;

#define MIN(a, b) ((a) <= (b) ? (a) : (b))
__attribute__((noinline)) void tf(unsigned char segnum) {
  segNum = segnum;
  unsigned char seg = MIN(segNum, 4);
  for (unsigned int i = 0; i < seg; i++) {
    bitmap |= (unsigned char)(1UL << i);
  }
}

int main() {
  tf(0);
  printf("tf(0) bitmap: 0x%x\n", bitmap);
  tf(1);
  printf("tf(1) bitmap: 0x%x\n", bitmap);
  tf(2);
  printf("tf(2) bitmap: 0x%x\n", bitmap);
  tf(3);
  printf("tf(3) bitmap: 0x%x\n", bitmap);
  tf(4);
  printf("tf(4) bitmap: 0x%x\n", bitmap);
  tf(5);
  printf("tf(5) bitmap: 0x%x\n", bitmap);
  return 0;
}
```

$clang test.cpp -O2 --target=aarch64-linux-gnu -march=armv8-a && a.out

tf(0) bitmap: 0x0
tf(1) bitmap: 0x1
tf(2) bitmap: 0x3
tf(3) bitmap: 0x7
tf(4) bitmap: 0xf
tf(5) bitmap: 0xf

$clang test.cpp -O2 --target=aarch64_be-linux-gnu -march=armv8-a && a.out

tf(0) bitmap: 0x0
tf(1) bitmap: 0x0
tf(2) bitmap: 0x0
tf(3) bitmap: 0x0
tf(4) bitmap: 0x0
tf(5) bitmap: 0x0

The truck llvm does not have this bug, because have different loop vectorize optimization of tf function.  But the bug is still in CodeGen.   Look at here: https://godbolt.org/z/PEd5PqTs9

The key point looks like the two REV32, if we remove and we get right result. 
Or the uzp1 , we replace to uzp2 it's also right.

15.x produce a trunc instruction in IR, and then get trunc and bitcast instruction in SelectionDAG, and then Codegen get XTN and REV32. But little endian is : trunc -> trun + bitcast -> XTN.

The different Instruction Selection 
BE: def : Pat<(v4i16 (bitconvert (v2i32 FPR64:$src))), (v4i16 (REV32v4i16 FPR64:$src))>;
LE: def : Pat<(v4i16 (bitconvert (v2i32 FPR64:$src))), (v4i16 FPR64:$src)>;
Look at this commit: https://github.com/llvm/llvm-project/commit/30e0e11eb4d9157e8abeea3f0f9027a00617f2bb

**Comment by EugeneZelenko** [comment]
Could you please try 17 Release Candidate or `main` branch? https://godbolt.org should be helpful.

**Comment by joyhou-hw** [comment]
this ir could reproduce the issue..
https://godbolt.org/z/evncG3oGr

for big-endian there is one more rev32 inst  or maybe  use uzp2 inst is correct.

**Comment by Jolyon0202** [comment]
> Could you please try 17 Release Candidate or `main` branch? https://godbolt.org should be helpful.

17 Release Candidate or main branch could reproduce this issue. Look at @joyhou-hw

**Comment by Jolyon0202** [comment]
The issue is related to bigendian Neon. Look at here :https://llvm.org/docs/BigEndianNEON.html
And we have produce rev instruction for bitcast instruction [https://github.com/llvm/llvm-project/commit/30e0e11eb4d9157e8abeea3f0f9027a00617f2bb]
But it's redundant in this case.

.LBB0_2:                                // =>This Inner Loop Header: Depth=1
        ushl    v6.2d, v4.2d, v3.2d
        add     x8, x8, #4
        ushl    v7.2d, v4.2d, v1.2d
        cmp     x11, x8
        xtn     v6.2s, v6.2d
        xtn     v7.2s, v7.2d
        rev32   v6.4h, v6.4h    // redundant
        rev32   v7.4h, v7.4h   //  redundant
        add     v1.2d, v1.2d, v5.2d
        add     v3.2d, v3.2d, v5.2d
        uzp1    v7.4h, v6.4h, v7.4h
        fmov    d6, d0

**Comment by Jolyon0202** [comment]
Any suggestions are welcome
