### ISSUE TITLE
[format]  Code segments without semicolons or brackets will be merged into the next line of code after formatting

### ISSUE THREAD

**Issue by hyc9335** [llvm/llvm-project#65060]
in file TokenAnalyzer.cpp 

void TokenAnalyzer::consumeUnwrappedLine(const UnwrappedLine &TheLine) {
  assert(!UnwrappedLines.empty());
  UnwrappedLines.back().push_back(TheLine);
}

The code segment is parsed into 5 lines of statements. Is there any way to parse this sentence“static int a = 1” into a single line, which is more reasonable 

**static int a = 1**
class A {
public:
    int b = 1;
};

after formatting

**static int a = 1 class A {**
public:
    int b = 1;
};

**Comment by rymiel** [comment]
I don't think clang-format has any guarantees about formatting code that is already invalid. What are you trying to achieve?

**Comment by rymiel** [comment]
Feel free to re-open if you have a justification
