### ISSUE TITLE
[libc++][hardening] Make it possible to mix and match different hardening modes across different TUs

### ISSUE THREAD

**Issue by var-const** [llvm/llvm-project#65101]
It should be possible, for example, to configure the library to be built in the hardened mode and configure a particular TU to use the debug mode, and vice versa (see https://reviews.llvm.org/D158823#inline-1538863). This needs to be thoroughly tested.

**Comment by ldionne** [comment]
I think this is addressed by https://github.com/llvm/llvm-project/pull/70575
