### ISSUE TITLE
fuchsia-statically-constructed-objects has invalid sample code

### ISSUE THREAD

**Issue by adambadura** [llvm/llvm-project#65118]
There are some errors in the sample code of `fuchsia-statically-constructed-objects` - it seems all `C` objects are badly written: the first one uses a non-`constexpr` constructor, the second one uses non-existing constructor, and the third one misses variable name.

I also tired opening the link provided below the listing:

>  https://fuchsia.googlesource.com/zircon/+/master/docs/cxx.md

but it shows

> PERMISSION_DENIED: The caller does not have permission

for me... - it seems #62334 may be referring to the same problem regarding the link.

Finally, perhaps it would be nice if all listings would be augmented with Compiler Explorer link demonstrating the check on that sample. (Of course, this would not work with our own checks, sadly.)

BTW, isn't this check "obsolete" with `constinit` in C++20? (Of course, provided someone can use it.)

**Comment by PiotrZSL** [comment]
Link were already corrected by 6b95787acc5b2628a3d544c70cb0727a1975150d.
Yes, this check can be deprecated by `constinit`, if someone uses `constinit`, but then you may need check to force usage of constinit for all global variables.
Compiler Explorer won't be used, documentation shouldn't base on external tools, and some checks on purpose have pseudo-code in documentation.
As for issue with example, I'm correcting it now.
