### ISSUE TITLE
LLD --save-temps ELF object file output does not set e_flags the same as for the final link

### ISSUE THREAD

**Issue by ilovepi** [llvm/llvm-project#65146]
While investigating #65090, using `--save-temps` I was surprised that the e_flags in the `lto.o` file were not the same as those in the final linked binary. This makes using tools like `llvm-objdump` hard to use without passing several other flags. I'm not sure if this is related to RISC-V target features or if this is an existing problem that goes beyond RISC-V.

CC: @MaskRay Is this a known issue? Is there a workaround?

**Comment by MaskRay** [comment]
This isn't an lld/ELF issue. It's the LTO target-abi target-features problem that is tracked elsewhere

https://github.com/llvm/llvm-project/issues/50591
https://github.com/llvm/llvm-project/issues/59350

**Comment by MaskRay** [comment]
Closing as we have other, more canonical places for discussion, but I'll keep this in mind:)
