### ISSUE TITLE
[mlir][spirv] Add patterns to convert `spirv.IAddCarry` to `spirv.IAdd`

### ISSUE THREAD

**Issue by kuhar** [llvm/llvm-project#65154]
This is for WebGPU where extended arithmetic is not supported yet.

Related past issue for extended multiplication: https://github.com/llvm/llvm-project/issues/59563

**Comment by inbelic** [comment]
Had the chance to take a look this evening. Was able to follow from the previous implementation to create a pull request for a fix :)
