### ISSUE TITLE
Error while lexing identifier if it contains an escaped newline followed by a Unicode character

### ISSUE THREAD

**Issue by mattmanj17** [llvm/llvm-project#65156]
Minimal test case

```
int main(void) {
    int a\
ス = 42;
    return aス;
}
```

Godbolt example of failed compilation in clang 16
https://godbolt.org/z/TsMrbKqT6

Godbolt example of successful compilation with GCC 13.2
https://godbolt.org/z/hrzqcPKnn

Based on some debugging, I think we are looking at the '\\\\' in tryConsumeIdentifierUTF8Char, downstream of LexIdentifierContinue.
Perhaps that function needs to take a Size argument like tryConsumeIdentifierUCN does, so that it can correctly decode the Unicode char after the escaped newline.

**Comment by danix800** [comment]
See https://gcc.gnu.org/onlinedocs/gcc/Escaped-Newlines.html

**Comment by mattmanj17** [comment]
@danix800 

What part in particular on that page is relevant to the case I posted?

**Comment by danix800** [comment]
The GCC extension is not relevant to this issue.

This seems to be a bug.

**Comment by shafik** [comment]
CC @cor3ntin

**Comment by cor3ntin** [comment]
@shafik https://reviews.llvm.org/D159345 :)
