### ISSUE TITLE
Build failure with MSVC 2019

### ISSUE THREAD

**Issue by CarlosAlbertoEnciso** [llvm/llvm-project#65157]
Using the latest TOT, building LLDB fails on Windows when using MSVC.

```
Error	C2065 '__PRETTY_FUNCTION__': undeclared identifier
llvm-project\lldb\source\Plugins\DynamicLoader\POSIX-DYLD\DYLDRendezvous.cpp	335
llvm-project\lldb\source\Plugins\DynamicLoader\POSIX-DYLD\DYLDRendezvous.cpp	375
```
`LLDB_LOG(log, "{0} action = {1}", __PRETTY_FUNCTION__, ActionToCStr(action));`

**Comment by CarlosAlbertoEnciso** [comment]
I think the identifier `__PRETTY_FUNCTION__` should be replaced with `LLVM_PRETTY_FUNCTION`

`LLDB_LOG(log, "{0} action = {1}", __PRETTY_FUNCTION__, ActionToCStr(action));`

**Comment by DavidSpickett** [comment]
I went ahead and fixed it, thanks for the report!

**Comment by DavidSpickett** [comment]
Turns out we're actually missing an msvc builder for lldb. https://lab.llvm.org/buildbot/#/builders?tags=%2Blldb

We do build on Windows on Arm, but using clang-cl.

**Comment by CarlosAlbertoEnciso** [comment]
Happy to help.
