### ISSUE TITLE
[X86] `uitofp` gets scalarized in x86 backend for `half`

### ISSUE THREAD

**Issue by Max191** [llvm/llvm-project#65150]
Converting `<64 x i4> -> <64 x half>` results in scalarization of the operation:

`llc example.ll -mtriple=x86_64-pc-linux`
```ll
define <64 x half> @main() {
    %int4_p = alloca <64 x i4>
    %int4 = load <64 x i4>, <64 x i4>* %int4_p
    %fp16 = uitofp <64 x i4> %int4 to <64 x half>
    ret <64 x half> %fp16
}
```

When doing this for `<64 x i4> -> <64 x float>`, it does not get scalarized:
```ll
define <64 x float> @main_float() {
    %int4_p = alloca <64 x i4>
    %int4 = load <64 x i4>, <64 x i4>* %int4_p
    %fp16 = uitofp <64 x i4> %int4 to <64 x float>
    ret <64 x float> %fp16
}
```

**Comment by phoebewang** [comment]
Scalarization is correct. We don't have vector arithmetic instructions for `half` type until AVX512FP16.
You can get the vectorized code when you specify `-mattr=avx512fp16`
