### ISSUE TITLE
Clan-Tidy not excluding system headers

### ISSUE THREAD

**Issue by FaiqueAli** [llvm/llvm-project#65175]
Hi everyone,
I am trying to analyze a project on Ubuntu using `clang-tidy` version 

```
Ubuntu LLVM version 14.0.0

  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: tigerlake
```

but I am getting a lot of errors from system header files.
I have created a `compile_command.json` file and also added the path of system header files in `compile_command.json`  file to ignore system headers. 
Similarly, I used the` //NOLINT` option and still got errors from the system header files.

I executed  `clang-tidy -checks='cppcoreguidelines'   -header-filter=.* -p path/compile_commands.json   src/*.cpp`
here is the output of the command [clang-tidy-output.txt](https://github.com/llvm/llvm-project/files/12499889/clang-tidy-output.txt)

looking for help to resolve the issue.
Thanks :)

**Comment by EugeneZelenko** [comment]
Could you please try 17 Release Candidate or `main` branch?

**Comment by PiotrZSL** [comment]
You got compiler errors:
```
error: too many errors emitted, stopping now [clang-diagnostic-error]
error: unsupported option '-V gcc_ntoaarch64le' [clang-diagnostic-error]
/home/sayedf/qnx710/target/qnx7/usr/include/signal.h:79:2: error: unknown type name 'sigset_t' [clang-diagnostic-error]
```
Errors will be always displayed regardless of system headers settings.
System headers filter work only for warnings.

Clang-tidy require input file to actually compile to perform analise. AST tree need to be constructor and that cannot be done if some types are missing.

Fix compile errors, verify using clang itself.
Verify if system headers are included with -isystem.

Nothing to fix here on Clang-tidy side.

**Comment by FaiqueAli** [comment]
Hi,
Thanks for replying and sorry for the late rep.

> You got compiler errors:
> 
> ```
> error: too many errors emitted, stopping now [clang-diagnostic-error]
> error: unsupported option '-V gcc_ntoaarch64le' [clang-diagnostic-error]
> /home/sayedf/qnx710/target/qnx7/usr/include/signal.h:79:2: error: unknown type name 'sigset_t' [clang-diagnostic-error]
> ```
> 
> Errors will be always displayed regardless of system headers settings. System headers filter work only for warnings.
> 
> Clang-tidy require input file to actually compile to perform analise. AST tree need to be constructor and that cannot be done if some types are missing.
> 
> Fix compile errors, verify using clang itself. Verify if system headers are included with -isystem.
> 
> Nothing to fix here on Clang-tidy side.


So the code is being compiled successfully (`make -j8 all `) without `clang-tidy`, please have a look at [this](https://github.com/llvm/llvm-project/files/12537194/compile.txt) attachment.


> Could you please try 17 Release Candidate or `main` branch?


I have installed clang-tidy-17 in my Ubuntu using `sudo apt install clang-tidy-17` and still getting the same header diagnostic issue with the command below

`clang-tidy-17 -checks='cppcoreguidelines'   -header-filter=.* -p path/compile_commands.json   src/*.cpp`
 
All the errors are being pointed out toward system headers as shown below, 

```
/home/sayedf/qnx710/target/qnx7/usr/include/sys/siginfo.h:568:6: error: unknown type name 'clock_t' [clang-diagnostic-error]
  568 |                                         clock_t                 __utime;
```

please have a look at the [output](https://github.com/llvm/llvm-project/files/12537258/clang-tidy-17-output.txt) of `clang-tidy-17`

**Comment by carlosgalvezp** [comment]
I see you are analyzing code that depends on QNX headers. It's likely clang-tidy (or clang for that matter) have issues with those, since they are platform-specific. Can you post the `compile_commands.json` file?

**Comment by FaiqueAli** [comment]
Yes, I am using QNX compiler and here is the compile_command.json [file](https://github.com/llvm/llvm-project/files/12542568/compile_commands.txt),
Please have a look :)

**Comment by carlosgalvezp** [comment]
Thanks for sharing!

- First, I see this:
 ```
       "-I/home/sayedf/qnx710/target/qnx7/usr/include",
```
You should include via `-isystem` instead of `-I` to ensure it's treated as a system header.

- You are probably missing more `-isystem` lines to QNX include folders. Clang/clang-tidy complains it can't find `clock_t`, because it's probably defined only in a QNX-specific header. Since you haven't added an include path to it, clang-tidy picks the x86 system headers, which don't define that type.

**Comment by FaiqueAli** [comment]
Thank you @carlosgalvezp for the information.

Do you mean `-I/home/sayedf/qnx710/target/qnx7/usr/include` defined in the `compile_command.json` file?

Since this file is being generated by `Bear` it would be difficult to manually correct the number of lines in the file each time, but for the rectification, I will now try to replace `-I` with `-isystem`.
should this correction only go to the system header files path in `compile_command.json` file or I should replace all the occurrences of `-I` with `-isystem`?

Do you also mean to try to replace `-isystem`  with `--sysroot /home/sayedf/qnx710/target/qnx7` in the `compile_command.json` file or pass this as a `clang-tidy` command argument?

thanks and looking forward to the clarification :)

**Comment by carlosgalvezp** [comment]
> Do you mean -I/home/sayedf/qnx710/target/qnx7/usr/include defined in the compile_command.json file?
Yes

>should replace all the occurrences of -I with -isystem
No, that will essentially make clang-tidy ignore **all** warnings :) It should be added only to system libraries and 3rd-party libraries, not to your own libraries.

I meant try to replace:
```
-I/home/sayedf/qnx710/target/qnx7/usr/include
```
With:
```
--sysroot /home/sayedf/qnx710/target/qnx7
```

**Comment by FaiqueAli** [comment]
Great

So I will now get a list of header files only using `qcc -E -v -` and replace it with `--sysroot` and let see the outcome :)

**Comment by carlosgalvezp** [comment]
To clarify, you should try either of the options, not both. I.e. 

**Option 1**

Get a complete list of headers via `qcc -E -v -`, and add them via `-isystem` to the compilation command.

**Option 2**

Do  not add any include of the form `qnx710/target/qnx7`, and instead pass `--sysroot /home/sayedf/qnx710/target/qnx7

**Comment by FaiqueAli** [comment]
So with 

**Option-1**

compile_command.json [file](https://github.com/llvm/llvm-project/files/12547366/compile-command.txt)

bash command:
`clang-tidy-17 -checks='cppcoreguidelines'   -header-filter=.* -p .   src/*.cpp`

output:
![image](https://github.com/llvm/llvm-project/assets/15321863/d9c82726-b891-4d67-a049-4c5d08db9abe)



**Option-2**

bash command:
`clang-tidy-17 -checks='cppcoreguidelines'   -header-filter=.* -p .   src/*.cpp --sysroot /home/sayedf/qnx710/target/qnx7`

No change in the Compile_command.json [file](https://github.com/llvm/llvm-project/files/12547418/compile-command.txt)

Output:
![image](https://github.com/llvm/llvm-project/assets/15321863/3c146db5-93a0-42f8-ad56-6fbf4b0baef7)

**Comment by carlosgalvezp** [comment]
For Option 1, I don't see in your `compile_commands` that you added the `-isystem` lines to the QNX include directories?

For Option 2, I believe you need to pass it either via `--extra-arg` or simply after a `--`, like this:

```
clang-tidy-17 <args> -- --sysroot /home/...
                     ^^
```

**Comment by FaiqueAli** [comment]
With 
**Option-2**
![image](https://github.com/llvm/llvm-project/assets/15321863/9dbc9c47-7b3b-4b1b-9d53-dd2d8333cc5f)

could you please let me know if I wanted to ignore more than one folder what would be the command argument?

for  **Option-1**
Really I did not understand what you meant by `QNX include directories` in `compile_command.json` file

**Comment by FaiqueAli** [comment]
So when I replace all the occurrences of `-I/home/sayedf/qnx710/target/qnx7/usr/include` with `--sysroot /home/sayedf/qnx710/target/qnx7` in `compile_command.json` file, it complains for `--sysroot` unsupported option.

![image](https://github.com/llvm/llvm-project/assets/15321863/d3c0663a-841a-46c8-b044-ebac63053867)

**Comment by carlosgalvezp** [comment]
Sorry, I should have been more specific, use `--sysroot=/home/sayedf/qnx710/target/qnx7`. Alternatively, pass this to clang-tidy: `--extra-arg=--sysroot=/home/sayedf/qnx710/target/qnx7`.

It seems however that you are passing `--sysroot=/home/sayedf/qnx710/target/qnx7/signal.h` - this is not correct and should be removed.

> Really I did not understand what you meant by QNX include directories in compile_command.json file

I mean to add the following to `compile_command.json` for each file:

```
"-isystem",
"<path1>",
"-isystem",
"<path2>",
...
```
Where each of `<pathN>` is the path that you get in the include directory search list when running `qcc -E -v -`.

**Comment by FaiqueAli** [comment]
I have tried both ways and both generated the same error list.

But I would like to prefer the command line argument way like I tried and got [this](https://github.com/llvm/llvm-project/files/12559737/clang-tidy-result.txt) result.

my command is `clang-tidy-17 -checks='cppcoreguidelines'   -header-filter=.* -p .   src/*.cpp --extra-arg=--sysroot /home/sayedf/qnx710/target/qnx7`

![image](https://github.com/llvm/llvm-project/assets/15321863/8beadd5e-fdcd-45ca-9450-6a04383074aa)

On the other hand with **option-2**


the command is `clang-tidy-17 -checks='cppcoreguidelines'   -header-filter=.* -p .   src/*.cpp`

with [ouptut](https://github.com/llvm/llvm-project/files/12559773/clang-tidy-result-am.txt) and here is the
[compile_commad..json](https://github.com/llvm/llvm-project/files/12559787/compile-command.txt)

![image](https://github.com/llvm/llvm-project/assets/15321863/7573eb4e-2a25-4ceb-80cb-d1fbe1fb6462)

**Comment by carlosgalvezp** [comment]
About Option 1, please use the exact command I posted - the `=` is important:

```
--extra-arg=--sysroot=/home/sayedf/qnx710/target/qnx7
                     ^
```

If it still doesn't work, it requires some more thorough troubleshooting. Unfortunately I have limited availability and won't be able to spend more time on the issue.

Running clang-tidy on a QNX build is not officially supported, so it requires ad-hoc work and deep understanding of the entire build system at hand to get it to work (if that's even possible). 

Best of luck!

**Comment by FaiqueAli** [comment]
> /home/...

Thanks for your response,
I also tried your suggestion but unfortunately, it doesn't work. 
here is the latest try

`clang-tidy-17 -checks='cppcoreguidelines'   -header-filter=.* -p .   src/*.cpp --  --extra-arg=--sysroot=/home/say
edf/qnx710/target/qnx7`

and output of the command is [output](https://github.com/llvm/llvm-project/files/12574304/sacn-result00.txt).

I appreciate your time and effort on this issue, Could you please recommend someone who can help or any guidance as a starting point to understand compatibility of the clang-tidy compiler with QNX header files?

**Comment by carlosgalvezp** [comment]
`--extra--arg` is a `clang-tidy` argument, therefore it should be passed before the `--` (you don't need `--` at all anymore):

```
clang-tidy-17 -checks='cppcoreguidelines'   -header-filter=.* -p .  --extra-arg=--sysroot=/home/sayedf/qnx710/target/qnx7 src/*.cpp 
```

Unfortunately I'm not aware if anyone else is working with QNX that could help. Perhaps someone on Discord?

**Comment by FaiqueAli** [comment]
@PiotrZSL could you please open this issue, or provide any direction for the fix ??

**Comment by PiotrZSL** [comment]
@FaiqueAli Simple question, does code compiles with Clang ? If not, then fix first clang compilation before trying clang-tidy.
As for "Clang-Tidy not excluding system headers", it is excluding warnings, not errors. Errors should be corrected by user.
You may need to specify --target manually, or --gcc-toolchain, or --sysroot=, or even define some missing defines on your own.
And as carlosgalvezp said, system headers need to actually included as system ones to warnings (like clang-diagnostic-pragma-pack) be discarded.

**Comment by carlosgalvezp** [comment]
I don't think it makes sense to re-open the issue, there is no issue with clang-tidy, simply there is an issue with your build setup. Perhaps a more suitable place to discuss your specific use case would be on Discourse instead.
