### ISSUE TITLE
clang "cannot select" when using wasm table builtins and -fPIC

### ISSUE THREAD

**Issue by hoodmane** [llvm/llvm-project#65191]
## Example:
Source file:
```c
static __externref_t table[0];

__externref_t test_builtin_wasm_table_get() {
  return __builtin_wasm_table_get(table, 0);
}
```
Compiling as follows works:
```
clang -c -target wasm32 -mreference-types builtins-table.c
```
but if I add `-fPIC`, it says:
```
fatal error: error in backend: Cannot select: intrinsic %llvm.wasm.table.get.externref
```

## Bad/good IR

The IR looks as follows:
```llvm
@table = internal addrspace(1) global [0 x ptr addrspace(10)] zeroinitializer, align 1

; Function Attrs: noinline nounwind optnone
define hidden ptr addrspace(10) @test_builtin_wasm_table_get() #0 {
entry:
  %0 = call ptr addrspace(10) @llvm.wasm.table.get.externref(ptr addrspace(1) @table, i32 0)
  ret ptr addrspace(10) %0
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(read)
declare ptr addrspace(10) @llvm.wasm.table.get.externref(ptr addrspace(1), i32) #1
```
If I change `@table = internal addrspace(1)` to `@table = local_unnamed_addr addrspace(1)` it seems to fix the problem.

@pmatos

**Comment by hoodmane** [comment]
Actually, even with `local_unnamed_addr` it still doesn't work quite as desired with `-fPIC`, since it generates relocations of type `R_WASM_GLOBAL_INDEX_LEB` instead of type `R_WASM_TABLE_NUMBER_LEB` and so linking does not work. But it moves the problem a bit later.

**Comment by pmatos** [comment]
Hi. I am currently on holidays until Sept 11. If nobody looks at this until then, I will upon my return.

**Comment by pmatos** [comment]
Hi, I can reproduce the problem and will work on a fix.

**Comment by sbc100** [comment]
Under `-fPIC` (i.e. dynamic linking) the `__table_base` symbol is the linker-created global which represents the offset into the `__indirect_function_table` at which the current DLL's static function addresses are stored.    Its similar to `__memory_base` for the static data section.   It should only be used when the address of function is taken and it should only refer to `__indirect_function_table`.

**Comment by pmatos** [comment]
> Looks like we just need another branch in that if/else to handle table symbols. When that code was written there were only two types of symbols: function symbols and data symbols.

Thanks. It seems like the issue is straightforward given tables cannot be export/imported but it will become more complicated when we can have two modules sharing a table.

**Comment by pmatos** [comment]
@hoodmane I submitted a PR attempting to fix this. Let me know if it solves the problem you were seeing. Apologies for the delay on the fix.

**Comment by hoodmane** [comment]
Thanks so much for fixing this @pmatos!
