### ISSUE TITLE
"Could not find a matching team" error in pre-commit CI of some github PRs

### ISSUE THREAD

**Issue by cor3ntin** [llvm/llvm-project#65207]
Some CI jobs, for example https://buildkite.com/llvm-project/github-pull-requests/builds/122 (triggered from https://github.com/llvm/llvm-project/pull/65193), do not get triggered properly be github PRs with a "Could not find a matching team that includes both pipelines each having a minimum "Build" access level" error

**Comment by metaflow** [comment]
@cor3ntin I think that you've correctly identified the issue:  https://forum.buildkite.community/t/could-not-find-a-matching-team-that-includes-both-pipelines/1182/3 

- /github-pull-requests pipeline only had team "libcxx"
- /clang-ci only had team "everyone"

so if user was not registered in buildkite then "team matching" rules would not allow build on clang ci from PR.
I have updated github PR pipeline so should be good. Please confirm!

**Comment by metaflow** [comment]
note to self: capture this behavior in doc for .ci

**Comment by cor3ntin** [comment]
@metaflow is there a good way to test? This PR seems to have been created after your change and still exhibit the bug
https://github.com/llvm/llvm-project/pull/65214

**Comment by metaflow** [comment]
sure, I will try to create a PR under another account tomorrow to see if it
works.

**Comment by metaflow** [comment]
Seems to be fixed now.
