### ISSUE TITLE
Unclear documentation of modernize-use-equals-delete

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#65221]
The docs of "modernize-use-equals-delete" don't quite explain what the purpose of the check is. What problem is it solving? Why is the new code preferred over the old code? Any references that one can read about it?

The closest I can find is a C++ Core Guideline that says that one should not mark a function as private in order to delete it - the modern way is to move the function to  *public* and mark it as deleted. 

However modernize-use-equals-delete does not do that - it doesn't move the deleted function from private to public, which is a bit confusing.

**Comment by PiotrZSL** [comment]
This check is trying to find private methods without implementation that could be marked as deleted instead of depending on linker error, thats a main prupose of check.
As for private->public, both clang and gcc provide proper warnings, that function is deleted, so there is no need to do that.
I think thats an old assumption when some compilers could see function as private, and didn't provide warning that it were deleted.

**Comment by carlosgalvezp** [comment]
Thanks for the clarification! It would be great to update the docs with that content, maybe I'll do that and try out the new PR workflow :) 

I found the C++ Core Guideline I mentioned before:
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c81-use-delete-when-you-want-to-disable-default-behavior-without-wanting-an-alternative

> Note that deleted functions should be public.

But perhaps it's not the scope of the check to do this.

**Comment by carlosgalvezp** [comment]
> But perhaps it's not the scope of the check to do this.

Ah, it actually does warn about that too. In that case I believe the examples need update as well.

```
struct PrivateDeleted {
private:
  PrivateDeleted(const PrivateDeleted &) = delete;
  // CHECK-MESSAGES: :[[@LINE-1]]:3: warning: deleted member function should be public [modernize-use-equals-delete]
};
```

**Comment by carlosgalvezp** [comment]
A bit unrelated, but do we know why the check is limited only to special member functions? Wouldn't we want it to be applied to **any** function?

**Comment by PiotrZSL** [comment]
> A bit unrelated, but do we know why the check is limited only to special member functions? Wouldn't we want it to be applied to **any** function?

It's safer that way, it's common for bigger classes to split implementation functions into multiple transaction units, in that way check would report lot of false positives, but special member functions are usually defined in same TU. And in the past this approach were used mainly for constructors, copy operators.

**Comment by carlosgalvezp** [comment]
> in that way check would report lot of false positives

Hmm it shouldn't, because it's only active in a TU that implements *all* member functions. I see the historical use only for special member functions, but I think it should be fairly easy to generalize without risking FPs. Food for thought!

**Comment by PiotrZSL** [comment]
"all member functions" that are not speciall functions, but if we enable this for all functions then this rule would need to be removed, or it would never trigger. Thats why I would say: lets don't change how this check works, it's fine...

But if you ask about private -> public, that thing is currently not restricted only to special member functions.
