### ISSUE TITLE
mnt/host/source/src/third_party/llvm-project%2098f5a340975bc00197c57e39eb4ca26e2da0e8a2

### ISSUE THREAD

**Issue by UnhackHER** [llvm/llvm-project#65236]
Is anyone able to help me understand this log

[debug_vboot_noisy.log](https://github.com/llvm/llvm-project/files/12507691/debug_vboot_noisy.log)

Running /usr/bin/dev_debug_vboot 
+ date
Sun Sep  3 13:15:55 MST 2023
# DEV_DEBUG_FORCE=()
# OPT_CLEANUP=(yes)
# OPT_BIOS=()
# OPT_FORCE=()
# OPT_IMAGE=()
# OPT_KERNEL=()
# FLAG_SAVE_LOG_FILE=(yes)
+ crossystem --all
arch                    = x86                            # [RO/str] Platform architecture
backup_nvram_request    = (error)                        # [RW/int] Backup the nvram somewhere at the next boot. Cleared on success.
battery_cutoff_request  = (error)                        # [RW/int] Cut off battery and shutdown on next boot
block_devmode           = (error)                        # [RW/int] Block all use of developer mode
board_id                = (error)                        # [RO/int] Board hardware revision number
clear_tpm_owner_done    = (error)                        # [RW/int] Clear TPM owner done
clear_tpm_owner_request = (error)                        # [RW/int] Clear TPM owner on next boot
cros_debug              = 0                              # [RO/int] OS should allow debug features
dbg_reset               = (error)                        # [RW/int] Debug reset mode request
debug_build             = 0                              # [RO/int] OS image built for debug features
dev_boot_altfw          = (error)                        # [RW/int] Enable developer mode alternate bootloader
dev_boot_signed_only    = (error)                        # [RW/int] Enable developer mode boot only from official kernels
dev_boot_usb            = (error)                        # [RW/int] Enable developer mode boot from external disk (USB/SD)
dev_default_boot        = unknown                        # [RW/str] Default boot from disk, altfw or usb
dev_enable_udc          = (error)                        # [RW/int] Enable USB Device Controller
devsw_boot              = (error)                        # [RO/int] Developer switch position at boot
devsw_cur               = (error)                        # [RO/int] Developer switch current position
diagnostic_request      = (error)                        # [RW/int] Request diagnostic rom run on next boot
disable_dev_request     = (error)                        # [RW/int] Disable virtual dev-mode on next boot
ecfw_act                = (error)                        # [RO/str] Active EC firmware
post_ec_sync_delay      = (error)                        # [RW/int] Short delay after EC software sync (persistent, writable, eve only)
fw_prev_result          = unknown                        # [RO/str] Firmware result of previous boot
fw_prev_tried           = B                              # [RO/str] Firmware tried on previous boot (A or B)
fw_result               = unknown                        # [RW/str] Firmware result this boot
fw_tried                = B                              # [RO/str] Firmware tried this boot (A or B)
fw_try_count            = (error)                        # [RW/int] Number of times to try fw_try_next
fw_try_next             = B                              # [RW/str] Firmware to try next (A or B)
fw_vboot2               = (error)                        # [RO/int] 1 if firmware was selected by vboot2 or 0 otherwise
fwb_tries               = (error)                        # [RW/int] Try firmware B count
fwid                    = (error)                        # [RO/str] Active firmware ID
fwupdate_tries          = 0                              # [RW/int] Times to try OS firmware update (inside kern_nv)
hwid                    = REVEN-ANAE A6A-A7I             # [RO/str] Hardware ID
inside_vm               = 0                              # [RO/int] Running in a VM?
kern_nv                 = (error)                        # [RO/int] Non-volatile field for kernel use
kernel_max_rollforward  = (error)                        # [RW/int] Max kernel version to store into TPM
kernkey_vfy             = (error)                        # [RO/str] Type of verification done on kernel keyblock
loc_idx                 = (error)                        # [RW/int] Localization index for firmware screens
mainfw_act              = (error)                        # [RO/str] Active main firmware
mainfw_type             = nonchrome                      # [RO/str] Active main firmware type
minios_priority         = B                              # [RW/str] miniOS image to try fFallback to WPSW_BOOT (-1), which may be invalid
irst (A or B)
nvram_cleared           = (error)                        # [RW/int] Have NV settings been lost?  Write 0 to clear
display_request         = (error)                        # [RW/int] Should we initialize the display at boot?
phase_enforcement       = (error)                        # [RO/int] Board should have full security settings applied
recovery_reason         = (error)                        # [RO/int] Recovery mode reason for current boot
recovery_request        = (error)                        # [RW/int] Recovery mode request
recovery_subcode        = (error)                        # [RW/int] Recovery reason subcode
recoverysw_boot         = (error)                        # [RO/int] Recovery switch position at boot
recoverysw_cur          = (error)                        # [RO/int] Recovery switch current position
recoverysw_ec_boot      = (error)                        # [RO/int] Recovery switch position at EC boot
ro_fwid                 = (error)                        # [RO/str] Read-only firmware ID
tpm_attack              = (error)                        # [RW/int] TPM was interrupted since this flag was cleared
tpm_fwver               = (error)                        # [RO/int] Firmware version stored in TPM
tpm_kernver             = (error)                        # [RO/int] Kernel version stored in TPM
tpm_rebooted            = (error)                        # [RO/int] TPM requesting repeated reboot
tried_fwb               = (error)                        # [RO/int] Tried firmware B before A this boot
try_ro_sync             = (error)                        # [RO/int] try read only software sync
vdat_flags              = (error)                        # [RO/int] Flags from VbSharedData
vdat_lfdebug            = (error)                        # [RO/str] LoadFirmware() debug data (not in print-all)
wipeout_request         = (error)                        # [RW/int] Firmware requested factory reset (wipeout)
wpsw_cur                = (error)                        # [RO/int] Firmware write protect hardware switch current position
+ rootdev -s
/dev/sda3
+ ls -aCF /root
./  ../  .force_update_firmware
+ ls -aCF /mnt/stateful_partition
./   encrypted/       encrypted.key  home/	  unencrypted/
../  encrypted.block  etc/	     lost+found/  var_overlay/
+ cgpt show /dev/sda
       start        size    part  contents
           0           1          PMBR (Boot GUID: A222493A-7E81-6840-AB16-3884DB26F968)
           1           1          Pri GPT header
           2          32          Pri GPT table
    17010688   959762432       1  Label: "STATE"
                                  Type: Linux data
                                  UUID: BDFDC1D9-A482-FA4F-833D-81CD35AD702E
    16879616      131072       2  Label: "KERN-A"
                                  Type: ChromeOS kernel
                                  UUID: 625D75FC-C5CB-2F44-969D-E056BFEBEBAE
                                  Attr: priority=2 tries=0 successful=1 error_counter=0 
     8622080     8257536       3  Label: "ROOT-A"
                                  Type: ChromeOS rootfs
                                  UUID: 18134A0D-3365-BA42-9777-1EE8B4D8CF40
     8491008      131072       4  Label: "KERN-B"
                                  Type: ChromeOS kernel
                                  UUID: 43FC5FD0-A036-714E-8177-90048D7D980F
                                  Attr: priority=1 tries=0 successful=1 error_counter=0 
      233472     8257536       5  Label: "ROOT-B"
                                  Type: ChromeOS rootfs
                                  UUID: 64CBB358-7F50-DA4F-86CF-8B0B2366442E
          65           1       6  Label: "KERN-C"
                                  Type: ChromeOS kernel
                                  UUID: AA87544C-C89C-6840-94F9-8DD43E40217E
                                  Attr: priority=0 tries=15 successful=0 error_counter=0 
          66           1       7  Label: "ROOT-C"
                                  Type: ChromeOS rootfs
                                  UUID: E2FD4938-EDE6-BA42-93D0-7BAE2BB8E049
       69632       32768       8  Label: "OEM"
                                  Type: Linux data
                                  UUID: 69BAA272-44B6-2149-9249-FE32D8277328
          67           1       9  Label: "reserved"
                                  Type: ChromeOS reserved
                                  UUID: 8E5D124A-05AC-7549-8995-ADC6314749C3
          68           1      10  Label: "reserved"
                                  Type: ChromeOS reserved
                                  UUID: EF9E8F55-20E5-FC44-8051-1F61B88D1EE6
          64           1      11  Label: "RWFW"
                                  Type: ChromeOS firmware
                                  UUID: BD872E78-4693-654E-972E-6B7D7EEF9AA4
      102400      131072      12  Label: "EFI-SYSTEM"
                                  Type: EFI System Partition
                                  UUID: A222493A-7E81-6840-AB16-3884DB26F968
                                  Attr: legacy_boot=1 
   976773135          32          Sec GPT table
   976773167           1          Sec GPT header
+ flashrom -V -p host --wp-status
flashrom 1.4.0-devel on Linux 5.15.124-20255-g6fec128ef5b0 (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Calibrating delay loop... OK.
flashrom was built with LLVM Clang 17.0.0 (/mnt/host/source/src/third_party/llvm-project 98f5a340975bc00197c57e39eb4ca26e2da0e8a2), little endian
Command line (4 args): flashrom -V -p host --wp-status
Acquiring lock (timeout=180 sec)...
Opened file lock "/run/lock/firmware_utility_lock"
Lock acquired.
Initializing host programmer
cros_host_alias_init(): Redirecting dispatch -> internal_init().
/sys/class/mtd/mtd0 does not exist
ERROR: Could not get I/O privileges (Operation not permitted).
Your kernel may prevent access based on security policies.
Issue a 'dmesg | grep flashrom' for further information
Error: Programmer initialization failed.
# Extracting BIOS components...
+ flashrom -p host -r /dev/null -iGBB:GBB -iFMAP:FMAP -iVBLOCK_A:VBLOCK_A -iVBLOCK_B:VBLOCK_B -iFW_MAIN_A:FW_MAIN_A -iFW_MAIN_B:FW_MAIN_B
flashrom 1.4.0-devel on Linux 5.15.124-20255-g6fec128ef5b0 (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Calibrating delay loop... OK.
ERROR: Could not get I/O privileges (Operation not permitted).
Your kernel may prevent access based on security policies.
Issue a 'dmesg | grep flashrom' for further information
Error: Programmer initialization failed.
# Couldn't read individual components. Read the whole thing...
+ flashrom -p host -r bios.rom
flashrom 1.4.0-devel on Linux 5.15.124-20255-g6fec128ef5b0 (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Calibrating delay loop... OK.
ERROR: Could not get I/O privileges (Operation not permitted).
Your kernel may prevent access based on security policies.
Issue a 'dmesg | grep flashrom' for further information
Error: Programmer initialization failed.
+ERROR: Can't read BIOS at all. Giving up.

**Comment by asl** [comment]
This is unrelated to LLVM. You'd better ask at https://flashrom.org/
