### ISSUE TITLE
CUDA __popc and __popcll parameter have wrong signedness

### ISSUE THREAD

**Issue by DDoSolitary** [llvm/llvm-project#65250]
According to [CUDA doc](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__INTRINSIC__INT.html#group__CUDA__MATH__INTRINSIC__INT_1g43c9c7d2b9ebf202ff1ef5769989be46), `__popc` and `__popcll` accept unsigned arguments

```cuda
 __device__ ​ int __popc ( unsigned int  x );
 __device__ ​ int __popcll ( unsigned long long int x );
```

but Clang's version is signed

https://github.com/llvm/llvm-project/blob/6098d7d5f6533edb1b873107ddc1acde23b9235b/clang/lib/Headers/__clang_cuda_device_functions.h#L505-L506

While this is mostly harmless, it causes a lot of "narrowing conversion from unsigned to signed is implementation defined" warnings when I was trying to check existing CUDA code with clang-tidy.

**Comment by Artem-B** [comment]
Should be fixed by https://github.com/llvm/llvm-project/commit/2a702eca3efa066e3a470cd3b17082a05e118c91
