### ISSUE TITLE
[AArch64] ldapur/stlur are not recognized

### ISSUE THREAD

**Issue by EgorBo** [llvm/llvm-project#65284]
It seems that LLVM has a missing opportunity to optimize acquire/release loads/stores with RCPC2's instructions (namely, `ldapur`/`stlur`) which support imm offsets, e.g.:
```cpp
#include <atomic>

class MyClass
{
public:
    std::atomic<int> a1; 
    std::atomic<int> a2;

    void SetA2() { a2.store(42, std::memory_order_release); }
    int GetA2() { return a2.load(std::memory_order_acquire); }
};

void Test_set(MyClass* p)
{
    p->SetA2();
}

int Test_get(MyClass* p)
{ 
    return p->GetA2();
}
```
Current machine code for `Test*` functions:
```asm
Test_set(MyClass*):
        add     x8, x0, #4
        mov     w9, #42
        stlr    w9, [x8]
        ret

Test_get(MyClass*):
        add     x8, x0, #4
        ldapr   w0, [x8]
        ret
```
Expected code on arm64 v8.4+ (feat_rcpc2):
```asm
Test_set(MyClass*):
        mov     w9, #42
        stlur   w9, [x0, #4]
        ret

Test_get(MyClass*):
        ldapur  w0, [x0, #4]
        ret
```

https://godbolt.org/z/h4neohx7r

**Comment by antoniofrighetto** [comment]
Preliminary pattern match (https://github.com/antoniofrighetto/llvm-project/commit/002605cee90d7848c890af8a7dfc1d4ee63ea8b1) should work fine, yet, it seems like SelectionDAGISel keeps favouring `stlr` when the offset is valid as a scaled immediate. Specifically, the DAG for the equivalent 16bit store is the following:
```
SelectionDAG has 8 nodes:
  t0: ch,glue = EntryToken
        t2: i64,ch = CopyFromReg t0, Register:i64 %0
      t4: i64 = add nuw t2, Constant:i64<2>
    t9: ch = AtomicStore<(store release (s16) into %ir.a2.i)> t0, Constant:i32<42>, t4
  t7: ch = RET_ReallyLR t9
```
Whereas the generated sequence that guides the instruction selection looks as follows:
```
/*362091*/     OPC_CheckPredicate, 35, // Predicate_atomic_store_16
/*362093*/     OPC_CheckPredicate, 93, // Predicate_anonymous_12977
/*362095*/     OPC_CheckPatternPredicate, 59, // (Subtarget->hasRCPC_IMMO())
/*362097*/     OPC_CheckComplexPat, /*CP*/53, /*#*/2, // SelectAddrModeUnscaled16:$ #3 #4
/*362100*/     OPC_EmitMergeInputChains1_0,
/*362101*/     OPC_MorphNodeTo0, TARGET_VAL(AArch64::STLURHi), 0|OPFL_Chain|OPFL_MemRefs,
```
We enter `AArch64DAGToDAGISel::SelectAddrModeUnscaled` when analyzing `OPC_CheckComplexPat`. It seems that when ifdef'ing out the following, the emission of the RCPC instructions work correctly. Though, I doubt that's the appropriate fix, and likely missing something. @davemgreen, kindly have any suggestion? (cc/ @arsenm too).

https://github.com/llvm/llvm-project/blob/0a1aa6cda2758b0926a95f87d39ffefb1cb90200/llvm/lib/Target/AArch64/AArch64ISelDAGToDAG.cpp#L1133-L1136

**Comment by antoniofrighetto** [comment]
I think we shouldn't need check for being a scaled immediate anymore.

**Comment by antoniofrighetto** [comment]
Candidate PR #67879.

**Comment by antoniofrighetto** [comment]
Thanks for reporting, closing this as landed in https://github.com/llvm/llvm-project/commit/9fe5700611de180c2b5cfc0422eaebe1d027a826.
