### ISSUE TITLE
<format>: Is `std::format(L"{}", "test")` well-formed?

### ISSUE THREAD

**Issue by hewillk** [llvm/llvm-project#65290]
Stumbled upon the following code only accepted by libc++:

```cpp
#include <format>

int main() {
  auto s = std::format(L"{}", "test");
}
```
https://godbolt.org/z/aeWfjWxrn

Not sure if this involves LWG or is just a bug. I'm not a format guy so feel free to correct me.

**Comment by cpplearner** [comment]
See [LWG 3944](https://wg21.link/lwg3944)

**Comment by mordante** [comment]
The code is indeed well-formed in C++23 and ill-formed in C++20. I agree it's odd and I filed the LWG issue @cpplearner linked. I'll close this issue since libc++ is correct. Once LWG issue is accepted it will be fixed in libc++.
