### ISSUE TITLE
llvmbot removes manually-added labels on PRs

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#65345]
For example, I manually added the `libc++` label when I created https://github.com/llvm/llvm-project/pull/65344, but then llvmbot removed it immediately after.

<img width="663" alt="Screenshot 2023-09-05 at 12 08 52 PM" src="https://github.com/llvm/llvm-project/assets/700834/dec7322c-565a-4b8e-bbf8-b973085591bc">

**Comment by cor3ntin** [comment]
This might be slightly tricky, I think i need to update to https://github.com/actions/labeler/releases/tag/v5.0.0-alpha.1 and of course the whole config format changed.

In the meantime, the bot only run on PR creation so if you add labels  after the bot run, they are preserved.

**Comment by cor3ntin** [comment]
Simpler Fix https://github.com/llvm/llvm-project/pull/65395
