### ISSUE TITLE
Mailing lists are not handling comments well

### ISSUE THREAD

**Issue by pogo59** [llvm/llvm-project#65382]
When a new issue gets posted, I see an email to llvm-bugs. When a new clang PR gets posted, I see an email to cfe-commits. And so on. That's all fine.

When a _reply_ is posted to an issue, or a _comment_ posted on a PR, however, I'm seeing the email sent "To: llvm/llvm-project" llvm-project@noreply.github.com. This makes issue comments and PR comments hard to filter. Is there a way to improve this?

**Comment by asl** [comment]
@pogo59 I believe the latter notifications are sent directly from GitHub if you're watching the issue. The llvm-bugs / cfe-commits thing are our custom catch-all notifications sent from dedicated actions.

**Comment by pogo59** [comment]
Thanks @asl so I will have to revise my filters. It does look like github distinguishes these on the subject line, with "(PR #nnnn)" and "(Issue #nnnn)" tags, so maybe it won't be too bad.

**Comment by pogo59** [comment]
Attempting to close as not planned.
