### ISSUE TITLE
clang for ARM produces char values larger than 8bit when assigned from float

### ISSUE THREAD

**Issue by Stenzel** [llvm/llvm-project#65446]
This only happens with optimizations, without optimizations all is fine.
This affects also functions that are inlined and take a char argument, a value exceeding the range of char, signed or unsigned, is passed as parameter. 

See below the minimal program to reproduce. 

Compile and run on M1 mac:

clang -O2 minimal.cpp -o minimal
./minimal                       
u:0x173C44

Compile & run without optimization:

clang minimal.cpp -o minimal
./minimal                       
u:0x44

Fault also shows in godbolt:
https://godbolt.org/z/ovMYv7qY6

[minimal.cpp.zip](https://github.com/llvm/llvm-project/files/12534450/minimal.cpp.zip)

**Comment by topperc** [comment]
Casting a floating point value to an integer when the floating point value is outside the range of the integer type is undefined behavior. The compiler is optimizing based on this.

Passing `-fno-strict-float-cast-overflow` will force the compiler to saturate the value.

**Comment by Stenzel** [comment]
That might be true, but still having a char with a value of e.g. 0x173C44 is a flaw, especially if such a char value is passed to an innocent function that expect a char to have a value representable by eight bits. UB is no excuse for assigning a value outside the range of the data type.

**Comment by Stenzel** [comment]
just to be clear, here an example of a function expecting an unsigned char but called with a value exceeding the range of a 8 bits, this should not happen. Prints `char value: 0x173C44` when compiled with clang on ARM with optimisations.
 
```
#include <stdio.h>

void func(unsigned char c)
{
	printf("char value: 0x%02X\n",c);
}

int main(int argc, char *argv[])
{
	float a = argc * 1234;
	
	func(a * a);
	
	return 0;
}
```

**Comment by jroelofs** [comment]
> UB is no excuse for assigning a value outside the range of the data type.

Once a program invokes undefined behavior, all bets are off as to how it behaves.

In this case, it's relevant to note that `printf` can't actually print `char` arguments directly, and instead because it is vararg, `c` is implicitly zero-extended to `unsigned`. Optimizations are assuming that those upper bits are always zero, but that assumption is being violated by the UB, so you get weird optimization-dependent and hard-to-predict results.

**Comment by Stenzel** [comment]
So the assumption that a function that takes a char argument can expect this argument to be in the range of a char is wrong? Like the `func(char c)` function posted above? I think the UB argument is stretched a bit too far to justify this.

**Comment by jroelofs** [comment]
Darwin's calling convention on aarch64 expects `c` (8-bits) to be passed zero-extended in `w0` (32-bits). The caller computes `a * a` (float) and puts the result in `w0` (32-bits), which behaves correctly for all cases that do not have UB (i.e. when `argc` is 0). If that multiplication exceeds the range of `char`, then the cast is UB, and you get *absolutely no* guarantees on how the program behaves.

It's not that the assumption is wrong; it's that the assumption has been violated. Subtle, but important difference.

Recommended reading: https://blog.regehr.org/archives/213 (see also parts [2](https://blog.regehr.org/archives/226), and [3](https://blog.regehr.org/archives/232))

Also strongly recommend trying out the sanitizers: `-fsanitize=undefined,address`

**Comment by Stenzel** [comment]
So an unsigned char is not under all circumstances guaranteed to be in the range 0...255, right?

**Comment by jroelofs** [comment]
There are no guarantees when UB happens.

**Comment by Stenzel** [comment]
A compiler that passes char arguments that exceed 8-bit values to functions is simply not trustworthy, but I'll leave it at that.

**Comment by Stenzel** [comment]
Tried with different -fsanitize options, this is very helpful, thanks.

So the compiler uses fcvtzs for the conversion, knows this is unliekly to always have a 8bit result but marks the result internally as being 8bit-ish anyway and passes this on to whatever function. Compiler might be right, but this feels a bit passive-aggressive overuse of UB as excuse.

Personal takeaway is not to use char arguments but int and mask away some bits. 

Could you point me to documentation for such UB? I could not find this online.
Is assignment from int to char also UB?

**Comment by topperc** [comment]
Relevant text from C++ standard. The value in your case doesn't fit in char so the behavior is undefined.

7.3.10 Floating-integral conversions [conv.fpint] 1 A prvalue of a floating-point type can be converted to a prvalue of an integer type. The conversion truncates; that is, the fractional part is discarded. The behavior is undefined if the truncated value cannot be represented in the destination type. [Note: If the destination type is bool, see 7.3.14. —end note]

**Comment by jroelofs** [comment]
Here's some links to that same section, in case you're curious and want to explore: https://eel.is/c++draft/conv.fpint#1 https://eel.is/c++draft/
