### ISSUE TITLE
Let big shift return poison lead to diff result for O0 and O2

### ISSUE THREAD

**Issue by hstk30** [llvm/llvm-project#65459]
https://godbolt.org/z/9W71xdhnq

```
#include<stdio.h>

int main() {
        unsigned long long xM0;
        unsigned long long xM1;

        xM0 = ( 4294967295ULL );
        xM1 = ( ( 1ULL + 1ULL ) );
        xM0 >>= ( xM1 + 4294967295ULL );

        printf("%llu\n", xM0);
        return 0;
}
```

`4294967295ULL = 0xffffffff`

`xM1 + 4294967295ULL = 4294967297ULL = 0x100000001`

and in x86-64 `shr` or arm `lsr` , the 

> is a register holding a shift value to apply to the value in Rm. Only the least significant byte is used.

`64 = 2 ^ 6` , so `0x100000001 => 0x1`， 
and the right output should be `4294967295 >> 1 = 2147483647`.

And when apply `O2`, the output is `140735712106328`.

Ahead, the diff `O0` and `O2` caused by `EarlyCSEPass` for `ConstantFold`, see below:

https://github.com/llvm/llvm-project/blob/b027ce0ab93060bc6cb79d5402d21520e8b93fb7/llvm/lib/IR/ConstantFold.cpp#L1102C1-L1105C75

-- 

Can we fix it by trunc the `C2` to the width value bits like arm assemble’ behavior?

**Comment by fhahn** [comment]
This is an issue in the source code. The shift amount in the source is too big, causing undefined behavior. This can be caught using undefined-behavior sanitizer: https://godbolt.org/z/edjs997bT

From the optimizer perspective, things are working as expected and the input source code would need fixing to remove the undefined behavior.
