### ISSUE TITLE
Missing file when compiling libcxx

### ISSUE THREAD

**Issue by xishijie** [llvm/llvm-project#65453]
When compiling libcxx, these files were missing. Upon checking, it was found that these files were not included in the source code package. The error message is as follows

CMake Error at CMakeLists.txt:49 (include):
  include could not find requested file:

    HandleCompilerRT

-- Using libc++ testing configuration: /root/Open_Source/libcxx-16.0.0.src/test/configs/llvm-libc++-shared.cfg.in
CMake Error at cmake/config-ix.cmake:3 (include):
  include could not find requested file:

    LLVMCheckCompilerLinkerFlag
Call Stack (most recent call first):
  CMakeLists.txt:472 (include)

CMake Error at cmake/config-ix.cmake:15 (llvm_check_compiler_linker_flag):
  Unknown CMake command "llvm_check_compiler_linker_flag".
Call Stack (most recent call first):
  CMakeLists.txt:472 (include)

**Comment by ldionne** [comment]
Can you please describe how you're configuring your build of the library? Do you have the full monorepo available when building libc++?

I suspect you used the source package provided with the LLVM release for libcxx only, and that is (confusingly enough) not meant to be used to build the library. To build the library, you need a full checkout of the monorepo.

**Comment by mordante** [comment]
Since we lack the required information I'm closing this. I'll reopen it when the information has been provided.
