### ISSUE TITLE
SIMD code causes segfault in LLI, runs fine native on linux/x86

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#6545]
|  |  |
| --- | --- |
| Bugzilla Link | [6173](https://llvm.org/bz6173) |
| Version | trunk |
| OS | Linux |
| Attachments | [Test case .ll](https://user-images.githubusercontent.com/60944935/143740602-3d3adf7d-1de4-4f77-901e-a3e95189b162.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@lattner |

## Extended Description 

I was experimenting with LLVM by hand writing .ll files. I was hacking with arrays of SIMD vectors when I stumbled into a bug that causes LLI to segfault but the code runs fine when I make a native executable.

$ llvm-as testcase.ll
$ lli testcase.bc 
Stack dump:
0.	Program arguments: ../oss/llvm/build/bin/lli testcase.bc 
Segmentation fault
$ llvm-ld -native -o testcase testcase.bc
$ ./testcase # runs fine

I also tried an older version of LLI, which did not segfault like the one from LLVM trunk (r94421). The old, working lli version is:
Low Level Virtual Machine (http://llvm.org/):
  llvm version 2.5 (Debian 2.5-0ubuntu1)
  Optimized build with assertions.
  Built Mar  6 2009(17:11:47).

**Comment by arsenm** [comment]
I see no crash today
