### ISSUE TITLE
Clang cannot use _Atomic qualified integer type as controlling expression in switch statement

### ISSUE THREAD

**Issue by Christian-Gibbons** [llvm/llvm-project#65557]
Clang cannot use _Atomic qualified integer type as controlling expression in switch statement.
Minimal example program that will fail to compile:
```c
#include <stdatomic.h>
#include <stdio.h>
#include <stdlib.h>

int main(void) {
    _Atomic int x = 0;
    switch(x) {
        default:
            break;
    }
    return EXIT_SUCCESS;
}
```
Building with Clang 16.0.6 results in build error with following message:
```
main.c:7:5: error: statement requires expression of integer type ('_Atomic(int)' invalid)
    switch(x) {
    ^      ~
```

**Comment by tbaederr** [comment]
Also broken in trunk: https://godbolt.org/z/oaTxcG59e

**Comment by cor3ntin** [comment]
@to268 @AaronBallman

**Comment by to268** [comment]
It looks like on Godbolt that we have never supported this.
But it seems that it's a bug rather than a restriction in the C standard.
I need to look more about it, since the handling of the `_Atomic` qualifier is somewhat strange.

**Comment by to268** [comment]
The C standard requires an integral type for a controlling expression in a switch statement, but I have written a fix for this at https://reviews.llvm.org/D159522.

**Comment by AaronBallman** [comment]
> The C standard requires an integral type for a controlling expression in a switch statement, but I have written a fix for this at https://reviews.llvm.org/D159522.

FYI: the controlling expression has to be of integer type, but the primary expression `x` (in the original example) is in a context that will undergo lvalue conversion (C23 6.3.2.1p2) and that conversion will strip off the atomic qualification and leave an integer type. So by the time we're checking the switch condition, we should have already lost the atomic type and only be seeing the integer type.

**Comment by to268** [comment]
So this is valid in the C23 standard, good to know!
