### ISSUE TITLE
VLA / VLS  options for RVV auto-vectorization seems not work

### ISSUE THREAD

**Issue by punkyc** [llvm/llvm-project#65600]
I tried some examples in [Auto-Vectorization in LLVM](https://llvm.org/docs/Vectorizers.html)  and I found using `VLA / VLS `  options for RVV auto-vectorization, the assembly code generated didn't change. Does it normal for LLVM? or I miss something? 

I use: 

- `-march=rv64gcv -mllvm --riscv-v-vector-bits-min=256` for generating VLS code
- `-march=rv64gcv -mllvm --scalable-vectorization=on`  for generating VLA code

you can see https://godbolt.org/z/7YqWxnTzh.

**Comment by preames** [comment]
You're using compiler internal options which are not supported.  Please use the public clang driver flags.

Use zvlNb in the architecture string to see the minimum VLEN value.  Note that the minimum defaults to 128 (from the V spec).  Your example would be:
`-march=rv64gcv_zvl256b`

Note that this is *NOT* VLS.  This is VLA with a minimum bound on the VLEN.

To convert that to a VLS config, add `-mrvv-vector-bits=zvl `to the clang command line.

**Comment by topperc** [comment]
@preames `-mrvv-vector-bits=zvl` won't use the VLS vectorizer path will it?

**Comment by preames** [comment]
> @preames `-mrvv-vector-bits=zvl` won't use the VLS vectorizer path will it?
It sets the exact vector length, and we cost everything based on that.  The code may still reference scalable types, but it is VLS in the sense it may not run correctly on anything with a different VLEN.   If you want to disable the scalable path, you can use the internal  -mllvm --scalable-vectorization=off if you really want to, but that's not a supported configuration and is mostly useful for bug reduction.
