### ISSUE TITLE
libc++ makes wrong assumptions in std::pair constructor

### ISSUE THREAD

**Issue by grisumbras** [llvm/llvm-project#65620]
With latest libc++ this code doesn't compile in clang with  `-std=c++23`.

```c++
#include <type_traits>
#include <utility>

struct kvp {
  kvp() = default;
  explicit kvp(std::pair<int, int> const& p);
};

namespace std {

template <>
struct tuple_size<kvp> : std::integral_constant<std::size_t, 2> {};

template <>
struct tuple_element<0, kvp> {
  using type = int;
};

template <>
struct tuple_element<1, kvp> {
  using type = int;
};

} // namespace std


static_assert(std::is_nothrow_move_constructible<kvp>::value);
```

As far as I can tell, when checking wether `kvp` is nothrow move constructible, the compiler tries instantiating this `std::pair` constructor( https://github.com/llvm/llvm-project/blob/main/libcxx/include/__utility/pair.h#L286-L291 ).
That in turn tries to compile this code (https://github.com/llvm/llvm-project/blob/main/libcxx/include/__utility/pair.h#L279-L282), which assumes that `std::tuple_size<T>::value == 2` means that `std::get<0>(T)` and `std::get<1>(T)` will work.

For context, in the original code this type had `get` overloads in its own namespace, but not in namespace `std`.

**Comment by ldionne** [comment]
From https://github.com/llvm/llvm-project/issues/65907#issuecomment-1712927090 by @huixie90 , the fix seems pretty simple. @huixie90 Do you want to take this?

**Comment by ldionne** [comment]
I think this is an obvious candidate for cherry-picking back to LLVM 17. We will miss 17.0.0, but we should still cherry-pick to `release/17.x` in order to make 17.0.1. Thanks for reporting this issue (and sorry for introducing it)!
