### ISSUE TITLE
Clang incorrectly rejects consteval destructors in C++20 

### ISSUE THREAD

**Issue by groundswellaudio** [llvm/llvm-project#65665]
MRE : 

```cpp
struct A {
  consteval ~A() {}
};
```

Produces the error `destructor cannot be declared consteval`

Relevant part of the standard (11.4.7, destructors) : 

> Each [decl-specifier](https://eel.is/c++draft/dcl.spec.general#nt:decl-specifier) of the [decl-specifier-seq](https://eel.is/c++draft/dcl.spec.general#nt:decl-specifier-seq) of a prospective destructor declaration (if any) shall be friend, inline, virtual, constexpr, or consteval[.](https://eel.is/c++draft/class.dtor#1.sentence-3)

**Comment by cor3ntin** [comment]
https://eel.is/c++draft/dcl.constexpr#2.sentence-3

[dcl.constexpr]/p2
> A destructor, an allocation function, or a deallocation function shall not be declared with the consteval specifier[.](https://eel.is/c++draft/dcl.constexpr#2.sentence-3)

And it doesn't really make sense for a destructor to be immediate, especially, if eg, the constructor was not.

**Comment by cor3ntin** [comment]
https://github.com/cplusplus/CWG/issues/420

**Comment by groundswellaudio** [comment]
Indeed, my bad. Working out an implementation I can see there is a bit more to it than I thought.
