### ISSUE TITLE
github-actions bot always add "new issue" label

### ISSUE THREAD

**Issue by EugeneZelenko** [llvm/llvm-project#65701]
github-actions bot always add "new issue" label even if some label(s) were added during issue creation. See #65700 and this issue as example.

**Comment by tru** [comment]
We are using https://github.com/github/issue-labeler/ for adding labels to new issues, After a glance at that action it doesn't seem like there is a way to configure it as you would like. Maybe we could file an issue for issue-labeler to support this?

**Comment by EugeneZelenko** [comment]
At least this is old behavior until ~ yesterday.

**Comment by Endilll** [comment]
I guess it was caused by #65309
CC @cor3ntin

**Comment by cor3ntin** [comment]
> We are using https://github.com/github/issue-labeler/ for adding labels to new issues, After a glance at that action it doesn't seem like there is a way to configure it as you would like. Maybe we could file an issue for issue-labeler to support this?

We could easily fork the github action to do that, i guess we need to:
  - only add 'new issue' when we don't add other label
  - not add labels automatically at all if labels are already set

Looking at their implementation that can be done quickly. The main question would be where do we host the fork?

**Comment by tru** [comment]
> > We are using https://github.com/github/issue-labeler/ for adding labels to new issues, After a glance at that action it doesn't seem like there is a way to configure it as you would like. Maybe we could file an issue for issue-labeler to support this?
> 
> We could easily fork the github action to do that, i guess we need to:
> 
> * only add 'new issue' when we don't add other label
> * not add labels automatically at all if labels are already set
> 
> Looking at their implementation that can be done quickly. The main question would be where do we host the fork?

We already have llvm/actions repo. So it would fit there maybe?
