### ISSUE TITLE
Teach bugpoint to drop operand bundles/values from operand bundles

### ISSUE THREAD

**Issue by arpilipe** [llvm/llvm-project#65710]
We should teach bugpoint to drop whole operand bundles as well as individual operands from operand bundles.

**Comment by nikic** [comment]
Why are you using bugpoint rather than llvm-reduce? bugpoint isn't really maintained anymore at this point...

**Comment by arpilipe** [comment]
I see llvm-reduce already has some functionality for reducing operand bundles. We will give llvm-reduce a try.

I'm closing this issue and will create a new one for llvm-reduce if we find some functionality missing.
