### ISSUE TITLE
Incorrect value of requires expression involving discarded value

### ISSUE THREAD

**Issue by cor3ntin** [llvm/llvm-project#65846]
https://godbolt.org/z/63bf61Esd

```cpp
template <typename T>
bool foo(T x) {
    (int(*)[((void)x, 1)])nullptr; // valid

    return requires {
            (int(*)[((void)x, 1)])nullptr; // clangs returns false
    };
}
bool b = foo(0);
```

When foo a function, `b` is true, if it's a template, `b` becomes false.

replacing `((void)x, 1)` by `1` makes `b` true. but `(void)b` is a discarded value expression so `((void)x, 1)` is a valid constant.
clang is also happy with that expression outside of requires expressions, included in constant evaluated and unevaluated context

**Comment by shafik** [comment]
Interesting to note, changing all to `constexpr` gets everyone to agree: https://godbolt.org/z/eofsrE4r5

**Comment by cor3ntin** [comment]
@shafik 

If `(int(*)[((void)x, 1)])nullptr; ` is a valid expression, which I believe it is, and which all compilers accept, then a requires expression checking that expression should be satisfied.
The other thing I'd expect is for the templateness of foo to have no effect on the return value.

Even in your constexpr example, both gcc and clang think the expression is valid, but not when in a requires clause.

**Comment by shafik** [comment]
Yeah, I don't see what is going on but I wonder if we are missing something.

CC @hubert-reinterpretcast @zygoloid

**Comment by zyn0217** [comment]
@cor3ntin I think we now match GCC's behavior? https://godbolt.org/z/P8Mde8EGz
Can you confirm if we should close it? thanks!
