### ISSUE TITLE
[Support] Add KnownBits::computeForSubBorrow

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#65893]
Add the sibling to KnownBits::computeForAddCarry:

- [ ] Actual KnownBits implementation is a wrapper to the internal computeForAddCarry, similar to KnownBits::computeForAddCarry, with minor bit twiddling/swapping.
- [ ] Add a SubBorrowExhaustive unit test to KnownBitsTest.cpp
- [ ] Hook up the USUBO/SSUBO/USUBO_CARRY/SSUBO_CARRY/SUBC cases in SelectionDAG::computeKnownBits to make use of it (similar to the ADD variants already do), with suitable testing.

**Comment by christiankissig** [comment]
@RKSimon I'd like to take a stab.

**Comment by christiankissig** [comment]
PR https://github.com/llvm/llvm-project/pull/67788 @RKSimon

**Comment by dlumma** [comment]
@christiankissig assigning this ticket to you since it looks like the work is done.
