### ISSUE TITLE
Empty fold `and` expression yields a no-op instead of a forever running loop

### ISSUE THREAD

**Issue by kl31tz** [llvm/llvm-project#65892]
Hello (first time opening an issue),

Empty fold `and` expression yields a no-op instead of a forever running loop when used as the condition.

The  [standard](https://en.cppreference.com/w/cpp/language/fold#Explanation) states:
When a unary fold is used with a pack expansion of length zero, only the following operators are allowed:
1) Logical AND (&&). The value for the empty pack is **true**
...

Yet in the following example, gcc produces the correct while (true) code but clang reduces `foo` to a no-op. Both successfully evaluate `static_assert(((I, false) and ...));` to true, suprisingly.
``` C++
#include <tuple>
#include <utility>

template <auto... I>
void bar(std::index_sequence<I...>) {
    static_assert(((I, false) and ...));
    while (((I, false) and ...));
}

void foo() {
    bar(std::make_index_sequence<0>{});
}
```

[https://godbolt.org/z/off37csva](https://godbolt.org/z/off37csva)

hope the example helps, and that I haven't made any mistake opening this case !

**Comment by cor3ntin** [comment]
This is the backend removing an infinite loop, look at what happens at `-O0` : https://godbolt.org/z/YYM4MsEbE
Another way to observe that is to do something in the loop https://godbolt.org/z/n9sMzM8ed 

You certainly would not be surprised by this behavior!

( @jfbastien !)

**Comment by kl31tz** [comment]
I did not know the backend removed empty infinite loops, that explains it. I still find suprising that it would compile 
``` C++
int main() {
    while (true);
}
```
to a no-op

**Comment by jbadwaik** [comment]
If you really want an infinite loop without doing anything,  you can call `std::this_thread::sleep_for` function like here: https://godbolt.org/z/bovK3GPvx

**Comment by shafik** [comment]
see: https://github.com/llvm/llvm-project/issues/60637

the more general issue is being tracked on: https://github.com/llvm/llvm-project/issues/48943
