### ISSUE TITLE
[clang-format] incorrect formatting with `&` qualifier and requires clause with multi-arg template

### ISSUE THREAD

**Issue by danakj** [llvm/llvm-project#65904]
The first one has no `&` qualifier and is formatted correct.

The second one adds `&` and clang-format gets confused, I don't think it's aware this is a function anymore.
```cpp
struct S {
    template <class... Args>
    constexpr void f()
        requires(true && C<true, Args...>)
    {
        return;
    }

    template <class... Args>
        constexpr void f() & requires(true && C<true, Args...>) { return; }
};
```

The `const` and `const&` qualifiers are parsed correctly. `&&` is also incorrect.

```cpp
struct S {
    template <class... Args>
    constexpr void f() const
        requires(true && C<true, Args...>)
    {
        return;
    }

    template <class... Args>
    constexpr void f() const&
        requires(true && C<true, Args...>)
    {
        return;
    }

    template <class... Args>
        constexpr void f() && requires(true && C<true, Args...>) { return; }
};
```

https://godbolt.org/z/qKTWec96e

**Comment by danakj** [comment]
It does very wrong things with whatever comes after as well:

```cpp
struct S {
    template <class... Args>
        constexpr void f() && requires(true && C<true, Args...>) { return; }

        private : int i;
};
```

**Comment by rymiel** [comment]
It seems that for this bug to show up, you need both the parentheses after the `requires` keyword and also a comma (i.e. the one in the angle brackets), like so:
`void f() & requires(C<true, true>)`
Investigating

**Comment by danakj** [comment]
That was fast, thank you =)
