### ISSUE TITLE
How to find ForOp arg's preOp in MLIR

### ISSUE THREAD

**Issue by lovelybean** [llvm/llvm-project#65943]
![image](https://github.com/llvm/llvm-project/assets/6638300/4c1c8d67-74b3-4564-9254-1eaa724358b1)

i can get loadOp, now i want find %arg11 PreOp(%39 = tt.addptr) in ForOp

i try to use %arg11.getDefiningOp(),but this func return NULL

try to use getBackwardSlice(%arg11), this func return ForOp's all arg PreOp

how to get %arg11 PreOp, can anyone help me

**Comment by joker-eph** [comment]
In general we handle question and support on https://discourse.llvm.org ; GitHub issues is to track bugs and missing features.

Here you need `sci::ForOp::getOpOperandForRegionIterArg()`, you may find useful to look at `DimOfIterArgFolder` as an example of using this API: https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/SCF/Transforms/LoopCanonicalization.cpp#L103
