### ISSUE TITLE
[clang/c++/coroutines] `-Wunused-parameter` not working with coroutines.

### ISSUE THREAD

**Issue by no-more-secrets** [llvm/llvm-project#65971]
Given some coroutine return type `task<T>`, the following:
```cpp
task<int> foo( int a ) {
  co_return 42;
}
```
when compiled with `-Wunused-parameter`, will not warn that `a` is unused.  I suspect that it is because `a` is used during setup of the coroutine frame/promise... but I think most users would not expect that to count as "used."

**Actual behavior**: no warning.
**Expected behavior**: `warning: unused parameter 'a' [-Wunused-parameter]` (when that warning is enabled)

Note that GCC _does_ warn in this scenario.  In my coroutine-heavy code base I am thus forced to compile with GCC to find all of my unused parameters.

**Comment by ChuanqiXu9** [comment]
>  I suspect that it is because a is used during setup of the coroutine frame/promise... but I think most users would not expect that to count as "used."

Yeah. The wording is:

[When a coroutine is invoked, after initializing its parameters ([[expr.call]](http://eel.is/c++draft/expr.call)), a copy is created for each coroutine parameter[.](http://eel.is/c++draft/dcl.fct.def.coroutine#13.sentence-1)](http://eel.is/c++draft/dcl.fct.def.coroutine)
