### ISSUE TITLE
Pointer comparisons in constexpr functions having an unspecified value.

### ISSUE THREAD

**Issue by warp-10** [llvm/llvm-project#66018]
The real situation is rather complex, but similar to the following:

```c++
template< typename TargetPtr_t, typename SourcePtr_t, typename Count_t >
inline constexpr auto MyCopyTo(
    TargetPtr_t pTarget,
    SourcePtr_t pSource,
    Count_t count )
{
  // Error: Comparison has unspecified value.
  if( pTarget <= pSource )
  {
    while( count-- ){ *pTarget++ = *pSource++; }
    return pTarget;
  }
  else
  {
    pTarget += count;
    pSource += count;
    auto pTargetEnd = pTarget;
    while( count-- ){ *--pTarget = *--pSource; }
    return pTargetEnd;
  }
}

constexpr int Test()
{
    int u[]{1,2,3,4,5,6,7,8};
    int v[sizeof(u)/sizeof(u[0])]{};
    MyCopyTo( v, u,sizeof(u)/sizeof(u[0]));
    return 0;
}

int main( int argc, char **argv )
{
    constexpr auto v = Test();
    return v;
}
```

The behavior of things like "MyCopyTo" are well-defined. In this case, the comparison is required for correct behavior where it is being used with overlapping ranges of data.

There is no reasonable workaround. This requires having to re-write calls to things like "MyCopyTo" by either using pointers into a single aggregate array (not always possible), or replacing the calls themselves with for loops.

I don't target gcc, though its behavior is the same here. I consider this to be a mis-compilation in either case.

MSVS cl.exe does not report errors.

EDIT: I should point out that the functions in questions were, for the most part, written to assume random access iterators and not just raw pointers.

**Comment by shafik** [comment]
So what gcc and clang are complaining about: https://godbolt.org/z/5T8vjGY76

is that unless your pointers point to the same array or a subobject then the comparison is unspecified per [expr.rel p4](https://eel.is/c++draft/expr.rel#4) 

and this is not allowed in a constant expression per [expr.const p5](https://eel.is/c++draft/expr.const#5.24)

So both gcc and clang are correct this is not valid.

**Comment by warp-10** [comment]
Assign virtual addresses in declaration order?
This isn't a hard problem to solve, and enforcing this "correct" behavior makes a large number of otherwise valid coding practices inapplicable.

**Comment by AaronBallman** [comment]
I believe `std::less_equal()` is intended to do what you need: https://en.cppreference.com/w/cpp/utility/functional/less_equal so I'm not certain this is a core DR so much as a library issue (AIUI, STL implementers are not honoring the [standard requirements](https://eel.is/c++draft/comparisons#general-2) and that's why you get this: https://godbolt.org/z/xxnjsWfhj)
