### ISSUE TITLE
[clang-tidy] how to tell the difference at preprocessor time between clang-tidy and llvm

### ISSUE THREAD

**Issue by finchky** [llvm/llvm-project#66022]
I need to be able to exclude certain includes and sections of code when using clang-tidy but not when compiling with LLVM. It seems that both clang-tidy and LLVM define `__clang__` and `__llvm__` which is how I usually differentiate LLVM from GCC.

What preprocessor check can I do to handle this?

**Comment by PiotrZSL** [comment]
None buildin.
But you can add --extra-arg=-D__CLANG_TIDY__  to clang-tidy command line or add ExtraArgs variable to clang-tidy config file.

**Comment by finchky** [comment]
That works. Thanks, just wanted to check if there was something built in
