### ISSUE TITLE
[flang][hlfir] Support PowerPC intrinsics with HLFIR lowering

### ISSUE THREAD

**Issue by vzakhari** [llvm/llvm-project#66030]
Part of https://discourse.llvm.org/t/rfc-enabling-the-hlfir-lowering-by-default/72778:
* Make sure `flang/test/Lower/PowerPC` tests work with HLFIR lowering.

Hi @DanielCChen, @jeanPerier told me that you are working on supporting PowerPC intrinsics/vector types with HLFIR lowering.  Please post any updates as you see fit.  Basically, this issue is here to make sure we do not turn on HLFIR lowering by default before this is resolved.

**Comment by DanielCChen** [comment]
This is done under https://github.com/llvm/llvm-project/pull/66547
