### ISSUE TITLE
Backport "[lli] Make sure the exported __chkstk functions are included when exporting them" to 17.x

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#66049]
This fixes a build break in the mingw32 (32 bit gcc based) environment in msys2, CC @mmuetzel.

/cherry-pick 4bba12f7226228221d1fa4bad7732e25647ecb87

**Comment by mmuetzel** [comment]
Thank you for the backport request.

I agree that it would be nice to have this fixed in LLVM 17. 👍
