### ISSUE TITLE
[clang][vectorize] -O2 vectorize will get wrong result

### ISSUE THREAD

**Issue by MLsheng** [llvm/llvm-project#66163]
clang: 15.0.4 arm64be
#### demo.c

```
#include <stdio.h>
#define N 32
int a[N]={0};
int b[N]={0,0,1,0,
          0,0,1,0,
          0,0,1,0,
          0,0,1,0,
          0,0,1,0,
          0,0,1,0,
          0,0,1,0,
          0,0,1,0};
int k[N];

int main () {
    for (int i = 0; i < N/4; i++) {
        k[4*i] = a[4*i] < b[4*i] ? 1 : 0;
        k[4*i+1] = a[4*i+1] < b[4*i+1] ? 1 : 0;
        k[4*i+2] = a[4*i+2] < b[4*i+2] ? 1 : 0;
        k[4*i+3] = a[4*i+3] < b[4*i+3] ? 1 : 0;
    }

    for (int i = 0; i < N/4; i++) {
        printf("%d, %d, %d, %d\n",k[4*i],k[4*i+1],k[4*i+2],k[4*i+3]);
    }
    return 0;
}
```

#### compile command

```
clang demo.c -o demo.exe -static -O2
```

#### output

wrong：

```
1, 0, 1, 0
1, 0, 1, 0
1, 0, 1, 0
1, 0, 1, 0
1, 0, 1, 0
1, 0, 1, 0
1, 0, 1, 0
1, 0, 1, 0
```
It's a vectorize problem : with`-fno-vectorize` option，get result right

```
0, 0, 1, 0
0, 0, 1, 0
0, 0, 1, 0
0, 0, 1, 0
0, 0, 1, 0
0, 0, 1, 0
0, 0, 1, 0
0, 0, 1, 0
```

through  `-mllvm -opt-bisect-limit=` command can locate the pass that caused the error is `InstCombinePass`

**Comment by MLsheng** [comment]
> Does this issue still exist in Clang 17?

yes,it still exist.

**Comment by MLsheng** [comment]
Does anyone have ideas on this issue?

**Comment by nikic** [comment]
I don't have an arm64be system to debug this. Can you provide the IR before/after the problematic InstCombine pass you found with opt-bisect-limit?

I'm also not clear on why this is tagged as "slp vectorize". The vectorization here seems to be performed by the loop vectorizer? https://clang.godbolt.org/z/sz3z7sP9G

**Comment by MLsheng** [comment]
> I don't have an arm64be system to debug this. Can you provide the IR before/after the problematic InstCombine pass you found with opt-bisect-limit?
> 
> I'm also not clear on why this is tagged as "slp vectorize". The vectorization here seems to be performed by the loop vectorizer? https://clang.godbolt.org/z/sz3z7sP9G

the InstCombine pass https://godbolt.org/z/a69jq74d6

**Comment by nikic** [comment]
Thanks. I don't see anything wrong on the IR level. The vectorization seems unnecessarily convoluted to me, but all the shuffles work out in the end. So I think this is probably a backend miscompile related to shufflevectors.

I also just saw activity on https://github.com/llvm/llvm-project/issues/65884 which looks possibly related (also shufflevector on arm64be).
