### ISSUE TITLE
How can I disable the ext from i16 to i32 in Clang? When can Clang generate @llvm.sadd.with.overflow.i16?

### ISSUE THREAD

**Issue by zhping8080** [llvm/llvm-project#66170]
I find that when two i16 numbers or i8 numbers are added, it will be extended to i32.  Even if I choose to compile it with '-fsanitize=undefined'. So, How can generate the intrinsic 'call @llvm.sadd.with.overflow.i16' ? Additional, how can I find the implementation of llvm.sadd.with.overflow.* in LLVM source code? It's a bit challenging for newbies. Thanks!
<img width="305" alt="image" src="https://github.com/llvm/llvm-project/assets/39987919/8fa47e70-7ba9-46ee-bf34-f52eaf9aebe9">

**Comment by topperc** [comment]
You can use __builtin_add_overflow. See https://godbolt.org/z/6qsPqaWz3 for example.

llvm.sadd.with.overflow is converted to ISD::SADDO in SelectionDAG. How it is handled after that is target specific.

**Comment by zhping8080** [comment]
Thank you very much!
