### ISSUE TITLE
Feedback needed for CWG GitHub Issue 422 on [basic.start.main]

### ISSUE THREAD

**Issue by Eisenwave** [llvm/llvm-project#66186]
See https://github.com/cplusplus/CWG/issues/422.

In short, it is currently unclear what constitutes "use" of the `main` function and clang implements this very aggressively. It is the only compiler which flags `decltype(main)`.

My suggested solution for the issue in [[basic.start.main] p3](https://eel.is/c++draft/basic.start.main#3) is
```diff
 The function main shall not be
-used
+odr-used
 within the program.
```
This would invalidate the current behavior because `decltype(main)` is not odr-use.

Is there a strong reason for clang to flag `decltype(main)` or is the suggested solution acceptable?

An alternative has also been suggested which clang already implements, but which may be unnecessarily strict:
```diff
-The function main shall not be used within the program.
+An expression shall not name ([basic.def.odr]) the function main in the global scope.
```

**Comment by cor3ntin** [comment]
> Is there a strong reason for clang to flag decltype(main) or is the suggested solution acceptable?
Is there a strong reason not to?

Clang is perfectly happy for `main` to be used and called from within the program, so the warning only exists for conformance.
And while there would be no technical challenges tweaking when the warning is emitted in the lines of what you propose, in the absence of user-facing motivation, this is likely to end up on [the pile](https://clang.llvm.org/cxx_dr_status.html)  (ie, there are other ways to express `decltype(main)` :smile: )!

**Comment by shafik** [comment]
> > Is there a strong reason for clang to flag decltype(main) or is the suggested solution acceptable?
> > Is there a strong reason not to?
> 
> Clang is perfectly happy for `main` to be used and called from within the program, so the warning only exists for conformance. And while there would be no technical challenges tweaking when the warning is emitted in the lines of what you propose, in the absence of user-facing motivation, this is likely to end up on [the pile](https://clang.llvm.org/cxx_dr_status.html) !

clang diagnoses this if we use `-pedantic`: https://godbolt.org/z/r4xGzePvb

I agree though I don't see a compelling case here. So I guess we will see this in core eventually and see where it goes from there.

**Comment by cor3ntin** [comment]
I'm assuming we answered the question
