### ISSUE TITLE
Missing decorations for builtin library functions

### ISSUE THREAD

**Issue by OfekShilon** [llvm/llvm-project#66236]
The library function `cos` redirects to `__builtin_cos`. It, and many others, could be treated as `__attribute__((const))` but aren't. Optimizations are missed as a result.

toy example:

```c
void whateva();
void pureFunc(double d) __attribute__((pure));

void fun(double d) {
    pureFunc(d);      // call eliminated in EarlyCSEPass
    __builtin_cos(d); // call never eliminated

    whateva();
}
```

https://godbolt.org/z/KP88hnxoP

**Comment by Endilll** [comment]
> It, and many others, could be treated as __attribute__((const))

I wonder if this holds against various floating point environment shenanigans.

**Comment by philnik777** [comment]
`cos` can set `errno`, so it's not `const`. If you disable math errno everything gets optimized as expected: https://godbolt.org/z/a3zvc1qWY
