### ISSUE TITLE
Add f32.nearest and f64.nearest intrinsics to BuiltinsWebAssembly.def

### ISSUE THREAD

**Issue by loxcel** [llvm/llvm-project#66290]
We've identified which CLANG/GCC intrinsics correspond to most -- but not all -- WASM numeric instructions from section 2.4.1 of

https://webassembly.github.io/spec/core/_download/WebAssembly.pdf

![wasm-numerics](https://github.com/llvm/llvm-project/assets/40441828/6c1a473a-0fc8-4334-884c-78b51fa4c51f)

Some example include

       Intrinsic          WASM instruction
--------------------      ----------------
__builtin_clz()           i32.clz
__builtin_clzll()         i64.clz
__builtin_popcount()      i32.popcnt
__builtin_sqrt()          f64.sqrt

(We verified these intrinsics emit these WASM instructions by disassembling the wasm file produced from invocation of these intrinsics.)

Oddly, some WASM instructions like min & max appear to have no intrinsic equivalent, but instead are accessed through builtins documented by BuiltinsWebAssembly.def:

__builtin_wasm_min_f32()  f32.min
__builtin_wasm_max_f64()  f64.max

Unfortunately, we cannot identify if there's an intrinsic or WASM builtin that corresponds to these WASM instructions:

????                      f32.nearest
????                      f64.nearest

Now, BuiltinsWebAssembly.def defines "nearest" for the SIMD versions of WASM's nearest instruction:

TARGET_BUILTIN(__builtin_wasm_nearest_f32x4, "V4fV4f", "nc", "simd128")
TARGET_BUILTIN(__builtin_wasm_nearest_f64x2, "V2dV2d", "nc", "simd128")

However, BuiltinsWebAssembly.def doesn't include definitions for its scalar versions:

TARGET_BUILTIN(__builtin_wasm_nearest_f32, ... ???
TARGET_BUILTIN(__builtin_wasm_nearest_f64, ... ???

My request is for a maintainer to
a. add intrinsics to CLANG/GCC, or
2. supplement BuiltinsWebAssembly.def

so that we can directly invoke WASM f32.nearest and f64.nearest from C++.

Thanks

Kevin

**Comment by aheejin** [comment]
LLVM has `llvm.nearbyint.*` Intrinsic: https://llvm.org/docs/LangRef.html#llvm-nearbyint-intrinsic
Does this work for you?

**Comment by aheejin** [comment]
LLVM has `llvm.nearbyint.*` intrinsics, which are lowered down to `f32/64.nearest`: https://llvm.org/docs/LangRef.html#llvm-nearbyint-intrinsic

And this can be used by these builtins: https://github.com/llvm/llvm-project/blob/5ba239fe2a338ca6dc293a2dd9ea0758f25c738e/clang/include/clang/Basic/Builtins.def#L332-L333
Tests for those builtins: https://github.com/llvm/llvm-project/blob/5ba239fe2a338ca6dc293a2dd9ea0758f25c738e/clang/test/CodeGen/builtins.c#L390-L394

**Comment by loxcel** [comment]
Heejin,

*LLVM has llvm.nearbyint.* intrinsics, which are lowered down to
f32/64.nearest*


If llvm.nearbyint emits Webassembly's f32.nearest and f64.nearest instructions,
well, you've answered my question. And thank you for that !

However, a small note of concern about the association you mentioned:

Webassembly's f32.nearest and f64.nearest has this behavior
f64.nearest(1.5) = 2
f64.nearest(2.5) = 2

That is, if the number to be rounded lies between two integers, nearest
*always* rounds to the even integer.

LLVM nearbyint rounds to the even integer -- only if the current rounding
mode is set accordingly.

So, semantically, the assocation above is almost but not entirely correct.

One further question: what intrinsic must appear in the C++ source file in
order for the compiler to emit WASM f64.nearest or f32.nearest instructions
?

Thank you

Kevin

**Comment by aheejin** [comment]
> However, a small note of concern about the association you mentioned:
>
> Webassembly's f32.nearest and f64.nearest has this behavior
> f64.nearest(1.5) = 2
> f64.nearest(2.5) = 2
>
> That is, if the number to be rounded lies between two integers, nearest
> *always* rounds to the even integer.
>
> LLVM nearbyint rounds to the even integer -- only if the current rounding
> mode is set accordingly.
>
> So, semantically, the assocation above is almost but not entirely correct.

There are other rounding intrinsics/builtins as well. For example, `llvm.roundeven.*` intrinsics seem to what you said: https://llvm.org/docs/LangRef.html#llvm-roundeven-intrinsic
Usage: https://github.com/llvm/llvm-project/blob/5ba239fe2a338ca6dc293a2dd9ea0758f25c738e/clang/test/CodeGen/builtins.c#L408-L412

> One further question: what intrinsic must appear in the C++ source file in
> order for the compiler to emit WASM f64.nearest or f32.nearest instructions?

I'm not sure if I understand. If you are asking for how to use them actually in C, I linked snippets from https://github.com/llvm/llvm-project/blob/main/clang/test/CodeGen/builtins.c above: Usage: https://github.com/llvm/llvm-project/blob/5ba239fe2a338ca6dc293a2dd9ea0758f25c738e/clang/test/CodeGen/builtins.c#L408-L412

**Comment by aheejin** [comment]
Did I solve your problem? I will close it for now. Please reopen if you have any remaining questions.

**Comment by loxcel** [comment]
Heejin,

*Did I solve your problem?*


Yes, you did!

I used wasm2wat to verify that Clang C++, when invoked with --target=wasm32,
emitted these WASM mnemonics:

  Clang C++ Intrinsic     WASM mnemonic
-----------------------   -------------
 __builtin_nearbyint()    f64.nearest
 __builtin_nearbyintf()   f32.nearest


Thanks much for your prompt followup and helpful guidance.


--
Thank you


*Kevin Macdonald*
Partner | Loxcel Geomatics
www.loxcel.com
