### ISSUE TITLE
clang -fborland-extensions

### ISSUE THREAD

**Issue by stslam** [llvm/llvm-project#66342]
I'm so sorry. But where is the "__property" extension, when use clang -fborland-extensions?

**Comment by AaronBallman** [comment]
No need to apologize, it's a great question! We don't currently implement all Borland (or Embarcadero) extensions under the `-fborland-extensions` flag, only some of them. We don't yet support `__property`. If this is a feature you're looking for Clang to support, please reopen the issue and let us know a bit more about your use case.
