### ISSUE TITLE
[X86] X86FoldTablesEmitter - add support for AVX512 BroadcastFoldTables

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#66360]
X86InstrFoldTables.cpp still contains the (partial) manually generated fold tables for AVX512 broadcast folds, we should be able to generate these like regular memory folds.

It might be necessary to add support for TB_BCAST_SH fp16 folds as well as an additional task

**Comment by phoebewang** [comment]
cc @KanRobert @yubingex007-a11y

**Comment by KanRobert** [comment]
Sorry. It seems my classification rules for mails is so ridiculous that I missed lots of notifications.... I will take a look at it.
