### ISSUE TITLE
[AMDGPU] Print `wait_exp:0` for VINTERP and `wait_vdst:0` for LDSDIR

### ISSUE THREAD

**Issue by DadSchoorse** [llvm/llvm-project#66383]
Currently, the disassembler outputs

```
v_interp_p10_f32 v11, v6, v0, v6                                                  ; CD00000B 041A0106
```

instead of 

```
v_interp_p10_f32 v11, v6, v0, v6 wait_exp:0                                       ; CD00000B 041A0106
```

This hides that the instruction will wait for the exp counter, which can be misleading. LDSDIR's `wait_vdst`  has a similar issue.

**Comment by perlfu** [comment]
Yes, I am inclined to agree its more obvious what is happening if zero counters are always output for these.
See #66610
