### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Javier32** [llvm/llvm-project#66440]
@DESKTOP-MRMEL1R:~$ modular install mojo
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: modular install mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  modular   0x00007fc389a76567
1  modular   0x00007fc389a7421e
2  modular   0x00007fc389a76c2f
3  libc.so.6 0x00007fc388f82520
4  modular   0x00007fc38aa884a7
5  modular   0x00007fc38aa87f85
6  modular   0x00007fc38aa891d5
7  modular   0x00007fc389e5958d
8  modular   0x00007fc389e4ff90
9  modular   0x00007fc389a327b4
10 modular   0x00007fc389a30fe0
11 libc.so.6 0x00007fc388f69d90
12 libc.so.6 0x00007fc388f69e40 __libc_start_main + 128
13 modular   0x00007fc389a3068e
Illegal instruction (core dumped) 

Edition	Windows 10 Pro
Version	22H2
OS build	19045.3448
Experience	Windows Feature Experience Pack 1000.19044.1000.0
Processor	Intel(R) Core(TM)2 Quad CPU    Q9550  @ 2.83GHz   2.83 GHz
Installed RAM	6.00 GB
System type	64-bit operating system, x64-based processor

**Comment by asl** [comment]
Consider reporting Mojo-related issues to Mojo bugracker.
