### ISSUE TITLE
[MLIR] /lib/WindowsManifest/CMakeLists.txt can't detect updated XCode SDK after XCode Update 

### ISSUE THREAD

**Issue by kris-gaudel** [llvm/llvm-project#66526]
Problem:
- Trying to install MLIR from https://mlir.llvm.org/getting_started/, but using "Unix Makefiles" for build instead of Ninja
- CMake generate step fails due to 
`Imported target "ZLIB::ZLIB" includes non-existent path
"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include"`
- Recently updated my version of XCode, so path in CMake file should be `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk`

<img width="819" alt="image" src="https://github.com/llvm/llvm-project/assets/68076186/2c947d9f-7914-447f-bd7e-954cd1ff290b">

Notes:
- LLVM was installed using Unix Makefiles
- My command:
`cmake -G "Unix Makefiles" ../llvm    -DLLVM_ENABLE_PROJECTS=mlir    -DLLVM_BUILD_EXAMPLES=ON    -DLLVM_TARGETS_TO_BUILD="Native;NVPTX;AMDGPU"    -DCMAKE_BUILD_TYPE=Release    -DLLVM_ENABLE_ASSERTIONS=ON`

Attempted Solution
- Tried adding the flag 
`DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk` (still same result as image)

**Comment by kris-gaudel** [comment]
OS: macOS Ventura 13.5.2
xcode-select version 2397

**Comment by kris-gaudel** [comment]
Update: Not a fix per say, but building LLVM with Ninja then MLIR seems to have no issues

**Comment by joker-eph** [comment]
Did you start from an empty clean build dir or was it an existing build directory previous configured with CMake and then you upgraded Xcode and tried to continue using it?

**Comment by kris-gaudel** [comment]
It was an existing build

**Comment by joker-eph** [comment]
OK, then I think it is likely not something we can guarantee or do something about I think: it likely that CMake machinery isn't resilient to a change in the toolchain under the hood.
