### ISSUE TITLE
Not finding clang.dll

### ISSUE THREAD

**Issue by supuram** [llvm/llvm-project#66608]
Could not find clang.dll, llvm-link, llvm-config in  [LLVM-16.0.0-win64.exe](https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.0/LLVM-16.0.0-win64.exe)

**Comment by DimitryAndric** [comment]
@zmodem is our usual Windows packager. For reference, the builds for Windows are done with https://github.com/llvm/llvm-project/blob/main/llvm/utils/release/build_llvm_release.bat, so if you can parse that, it might give a clue as to why those binaries are not included.

**Comment by zmodem** [comment]
The package does include libclang.dll (in the bin/ dir), but apart from that the Windows installer is focused on shipping LLVM as a toolchain: clang, lld, etc. It does not ship LLVM as a library, and does not include LLVM developer tools like llvm-link. See also #53052 and #51192.
