### ISSUE TITLE
Incorrect code gen on array of linked lists with optimizer

### ISSUE THREAD

**Issue by jarro2783** [llvm/llvm-project#66607]
This came up trying to compile the basic example from boost intrusive sets here https://www.boost.org/doc/libs/1_82_0/doc/html/intrusive/unordered_set_unordered_multiset.html, using boost 1.78.0.

A minimal reproducer is this:
```
extern "C" void printf(...);

struct MyList {
    MyList() {
        next = this;
    }

    bool empty() {
        return next == this;
    }

    MyList *next;
};

int main() {
    MyList list[100];

    int empty = 0;
    int non_empty = 0;

    for (auto& l : list) {
        if (l.empty()) {
            ++empty;
        } else {
            ++non_empty;
        }
    }

    printf("%d %d", empty, non_empty);
}
```

This fails on Clang >= 15, and works fine on Clang 14. Compile with -O2 and run the binary to see incorrect behaviour. The code is creating an array of linked lists, which are all constructed to point their next node to themselves, so essentially it is an array whose elements are their own address. The `empty` function checks that this invariant is maintained, which it is not for every second element, so the output I get is
```
50 50
```

The expected output is
```
100 0
```
which I get with -O0 or -O1, and also Clang 14 with all levels of optimisation.

I bisected the optimisation passes and found that the first failing pass is
```
BISECT: running pass (188) LoopVectorizePass on main
```

**Comment by DimitryAndric** [comment]
I don't see the problem here with clang 17.0.0 rc4:

```
$ clang++ -v
FreeBSD clang version 17.0.0 (https://github.com/llvm/llvm-project.git llvmorg-17.0.0-rc4-10-g0176e8729ea4)
Target: x86_64-unknown-freebsd15.0
Thread model: posix
InstalledDir: /usr/bin

$ clang++ -O2 -fsanitize=undefined pr66607-1.cpp -o pr66607-1

$ ./pr66607-1
100 0
```

So maybe this got fixed somewhere along the way?

**Comment by DimitryAndric** [comment]
The problem got introduced in 702d5de4380b1e1554e5b90863093c3a57f76f70 (by @nikic) which enabled opaque pointers by default, and which ended up in 15.0.0 release.

It got fixed in 962c306a11d0a21c884c12e18825b8a41ba1bd7d (by @fhahn) for #61396, so this is a duplicate.

**Comment by jarro2783** [comment]
Can the fix be backported into a 15.x release?

**Comment by nikic** [comment]
No, LLVM 15.x is no longer maintained by upstream. However, you could ask your Linux distro for a backport.

**Comment by DimitryAndric** [comment]
The fix did get merged into 16.x so if you can use clang 16 you should be good. If that is difficult, or the code cannot be changed, you could try using `-Xclang -no-opaque-pointers` as suggested in the 15.x release notes, to disable opaque pointers, which should mask the bug.

**Comment by jarro2783** [comment]
We are building this ourselves, and we can't use Clang 16 because Cuda doesn't support it yet. But we can use that option instead. Thanks for your fast response.
