### ISSUE TITLE
[loopreroll] Is there a clear schedule for looprerollpass to repair?

### ISSUE THREAD

**Issue by erickq** [llvm/llvm-project#66615]
As mentioned by https://reviews.llvm.org/D150684, there seems to be interest in loopreroll related bugfixes. Is there a specific schedule?

**Comment by erickq** [comment]
@efriedma-quic

**Comment by nikic** [comment]
The LoopReroll pass has been removed by https://github.com/llvm/llvm-project/pull/80972. At this point, reintroducing the pass will require a from scratch re-review.
