### ISSUE TITLE
Code removal in the presence of Undefined Behavior

### ISSUE THREAD

**Issue by yuffon** [llvm/llvm-project#66623]
I find that clang would eliminate some code with bugs.

The following main.c file contains a simple div by 0 bug.
```
int main() {
    int a = 0;
    a = a / a;
    printf("%d\n", a);
    return 0;
}
```
```clang -O1 main.c -o main``` or above (```O2, O3```) would produce a binary without bug. The output from printf is also a random number. 
Only ```clang -O0``` get a binary with a bug.

My environment is:
Ubuntu 18.04
LLVM 14.0.6

**Comment by boomanaiden154** [comment]
This is undefined behavior according to the C standard and thus the compiler is free to do whatever it wants, in this case just eliminating the constant `a` (and the subsequent division) entirely. The value that you're seeing should be whatever ends up in the register that `printf` takes it's second argument from.

The C standard says the following in section 6.5.5 about division/modulo operations being undefined when done with zero:
> The result of the / operator is the quotient from the division of the first operand by the
second; the result of the % operator is the remainder. In both operations, if the value of
the second operand is zero, the behavior is undefined.
