### ISSUE TITLE
Inline assembly causing crashes in llc and Clang

### ISSUE THREAD

**Issue by boomanaiden154** [llvm/llvm-project#66624]
I'm seeing some weird behavior with inline assembly from some bitcode taken from the Linux kernel. For example, the following minified test case is taken directly a tip-of-tree kernel ([this file](https://github.com/torvalds/linux/blob/9cf26c8968b358bb14cc078f8153300a493613d4/drivers/gpu/drm/nouveau/dispnv50/ovly507e.c)) and compiled with a tip of tree `clang`:

```llvm
; ModuleID = 'bugpoint-reduced-simplified.bc'
source_filename = "drivers/gpu/drm/nouveau/dispnv50/ovly507e.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

module asm ".weak __kcfi_typeid_base507c_ntfy_reset"
module asm ".set __kcfi_typeid_base507c_ntfy_reset, 505546111"
module asm ".weak __kcfi_typeid_base507c_ntfy_set"
module asm ".set __kcfi_typeid_base507c_ntfy_set, 924527716"
module asm ".weak __kcfi_typeid_base507c_ntfy_clr"
module asm ".set __kcfi_typeid_base507c_ntfy_clr, 2186127539"
module asm ".weak __kcfi_typeid_base507c_ntfy_wait_begun"
module asm ".set __kcfi_typeid_base507c_ntfy_wait_begun, 3421798255"
module asm ".weak __kcfi_typeid_base507c_image_clr"
module asm ".set __kcfi_typeid_base507c_image_clr, 2186127539"
module asm ".weak __kcfi_typeid_base507c_update"
module asm ".set __kcfi_typeid_base507c_update, 575022393"

@.src = external dso_local unnamed_addr constant [44 x i8], align 1

define dso_local void @ovly507e_image_set() #0 align 64 !kcfi_type !7 {
entry:
  br i1 poison, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  ret void

if.end:                                           ; preds = %entry
  call void asm sideeffect "1:\09.byte 0x0f, 0x0b\0A.pushsection __bug_table,\22aw\22\0A2:\09.long 1b - .\09# bug_entry::bug_addr\0A\09.long ${0:c} - .\09# bug_entry::file\0A\09.word ${1:c}\09# bug_entry::line\0A\09.word ${2:c}\09# bug_entry::flags\0A\09.org 2b+${3:c}\0A.popsection\0A998:\0A\09.pushsection .discard.reachable\0A\09.long 998b - .\0A\09.popsection\0A\09", "i,i,i,i,~{dirflag},~{fpsr},~{flags}"(ptr @.src, i32 71, i32 poison, i64 12) #5
  unreachable
}

attributes #0 = { "zero-call-used-regs"="used-gpr" }
!7 = !{i32 924527716}
```

`llc` crashes with the following error message:
```shell
error: invalid operand for inline asm constraint 'i'
```

`clang` crashes with the same error message at `-O0`, but doesn't at higher optimization levels, presumably because the branch on poison gets optimized away so there's no inline asm causing issues anymore.

`clang` on the original non-minified example ends up hitting the following assertion however:
```shelll
clang: /llvm-project/clang/lib/Basic/SourceManager.cpp:868: clang::FileID clang::SourceManager::getFileIDLoaded(clang::SourceLocation::UIntTy) const: Assertion `0 && "Invalid SLocOffset or bad function choice"' failed.
```

I haven't investigated throughly, but I don't think this is a case of incorrect code as I'm seeing this in quite a few places in the Linux kernel.

Also noting here that I'm gathering the bitcode by embedding it using `-Xclang -fembed-bitcode=all` to collect bitcode directly after the frontend.

I need to do some more investigation but figured I would post something here.

CC: @nickdesaulniers as this touches the kernel + inline asm.

**Comment by nickdesaulniers** [comment]
> the following minified test case
> error: invalid operand for inline asm constraint 'i'

Did your minifier put `poison` as the operand to the inline asm? `i` means an immediate value, so while the error is not helpful at identifying which `i` constraint of the 4 is invalid, I suspect that's the issue.

> clang crashes with the same error message at -O0

The Linux kernel cannot be compiled at `-O0`.  Interview question: write C code (with GNU C extensions) that compiles at `-O2` but not `-O0`.  Answer: this pattern:

```c
static inline void foo (int x) {
  asm(""::"i"(x));
}
```
if `foo` is not inlined into its caller, x is not a compile time integer constant expression.

> I haven't investigated throughly, but I don't think this is a case of incorrect code as I'm seeing this in quite a few places in the Linux kernel.

No (it's due to the above pattern); well yes, it's sad that the kernel no longer compiles at `-O0`, but that ship has long sailed.  Too late to stop that train now.

> Also noting here that I'm gathering the bitcode by embedding it using -Xclang -fembed-bitcode=all to collect bitcode directly after the frontend.

Cool, what are you trying to do?

Closing this issue as I don't see a bug here, but let's continue this discussion in the thread.

**Comment by boomanaiden154** [comment]
> Did your minifier put `poison` as the operand to the inline asm? `i` means an immediate value, so while the error is not helpful at identifying which `i` constraint of the 4 is invalid, I suspect that's the issue.

I just used `bugpoint` over the bitcode with the `-run-llc` flag, so that's fairly likely and would make a lot of sense.

> The Linux kernel cannot be compiled at `-O0`.

Ah! That would make sense. I did not realize that and naively assumed that everything would compile just fine at `-O0`.

> Cool, what are you trying to do?

I'm doing some analysis over a large set of LLVM-IR (which includes the Linux kernel) and was trying to measure code size at `-O0`.

> Closing this issue as I don't see a bug here, but let's continue this discussion in the thread.

Given that the kernel doesn't compile at `-O0` due to the pattern you mentioned, my original thought of this being a bug was mistaken. Thank you very much for your insight here and sorry for the noise!
