### ISSUE TITLE
[qoi] "warning: no newline at end of file" prints blank lines due to fixit

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#6664]
|  |  |
| --- | --- |
| Bugzilla Link | [6292](https://llvm.org/bz6292) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
--
```
ddunbar@giles:tmp$ printf "int x;" | clang -fsyntax-only -x c -
ddunbar@giles:tmp$ 
```
--

**Comment by philnik777** [comment]
Closing, since I don't really see anything to improve here.
