### ISSUE TITLE
[AMDGPU] Alloca is not properly promoted

### ISSUE THREAD

**Issue by shiltian** [llvm/llvm-project#66669]
To reproduce this issue, both LLVM and OpenMP (with target offloading at least for AMDGPU) need to be built.

The reproducer is in LLVM repo.
```
$ clang -fopenmp --offload-arch=gfx90a llvm-project/openmp/libomptarget/test/offloading/bug51982.c -O1 -fopenmp-target-jit -o bug51982
$ ./bug51982
```
At this moment the test should not fail. Extract the attachment ([as-puzzle.tar.gz](https://github.com/llvm/llvm-project/files/12651295/as-puzzle.tar.gz)) and there are four files: `good.ll`, `good.s`, `bad.ll`, and ``bad.s``. As their names suggest, "good" means the IR can pass the test, while "bad" means the IR causes the test failure. The only difference between the two IRs is, the bad version has an extra AS cast, and then the corresponding store to the original generic pointer is replaced with a store with the right AS. The two `.s` files correspond to the IRs.

In order to reproduce the runtime memory access fault, we don't need to rebuilt the reproducer.
```
$ llc -O1 -march=amdgcn -mcpu=gfx90a --filetype=obj good.ll -o good.o
$ export LIBOMPTARGET_JIT_REPLACEMENT_OBJECT="good.o"
$ ./bug51982
```
The test should pass as well. Now we compile the bad version.
```
$ llc -O1 -march=amdgcn -mcpu=gfx90a --filetype=obj bad.ll -o bad.o
$ export LIBOMPTARGET_JIT_REPLACEMENT_OBJECT="bad.o"
$ ./bug51982
```
Now you are supposed to see the memory access fault error that crashes the program.

**Comment by shiltian** [comment]
ping

**Comment by Pierre-vh** [comment]
I looked at logs and ISA diff and the only difference is that we use a buffer_store in the bad case (and there is a null pointer check).

It looks like before calling, the pointers are all casted to the generic AS, and then it crashes when casted back to the private AS (5) and we emit a `buffer_store`. When not casted back, we use a `flat_store`.
Note that there are other stores already using a `flat_store`. Bad code is on the right, good one on the left:

![image](https://github.com/llvm/llvm-project/assets/29600849/a7df4c87-98b8-4c74-9efd-d33a1bdb8a25)

Where does the code come from? Did the frontend emit the additional addrspacecast? I'm not convinced the compiler is doing something wrong yet.

Maybe @jayfoad or @nhaehnle have other ideas?

**Comment by jayfoad** [comment]
> Bad code is on the right, good one on the left:

Are you sure? bad.ll stores to addrspace(5) which should generate the buffer_store (using the scratch descriptor).

Anyway I don't see any evidence that the backend is doing anything wrong.

**Comment by Pierre-vh** [comment]
> > Bad code is on the right, good one on the left:
> 
> Are you sure? bad.ll stores to addrspace(5) which should generate the buffer_store (using the scratch descriptor).
> 
> Anyway I don't see any evidence that the backend is doing anything wrong.

Ah yeah my bad, `bad.s` is on the left, `good.s` is on the right.

**Comment by shiltian** [comment]
I have a middle end patch (which has been reverted due to this issue) that can deduce AS and add corresponding cast to pointer operand of store and load instruction. As the two IRs show here, the only difference here is just the AS cast of one pointer, which is indeed in that AS. With this AS, a memory access fault occurs at runtime.

**Comment by jayfoad** [comment]
This looks like a bug in the AMDGPUPromoteAlloca pass. First your pass runs, which adds code in __kmpc_for_static_init_4u that "knows" that this pointer is really in addrspace(5). Then AMDGPUPromoteAlloca "promotes" the original alloca (addrspace 5) to a global variable (addrspace 3). It really should not do this unless it can prove that all accesses to the pointer can be safely updated.

**Comment by shiltian** [comment]
@jayfoad I ran the pass `amdgpu-promote-alloca` manually on the two IRs. The output IRs are same.

**Comment by shiltian** [comment]
Interestingly, `-O3` can make the test pass but `-O1` can't.

**Comment by shiltian** [comment]
The root cause is, in `amdgpu-codegenprepare`, we change those pointers from AS 5 to AS 3 mistakenly, but we never update the uses in the callee.

**Comment by shiltian** [comment]
> The call use is supposed to count as an address capture which we check for.

Does this mean AS cast should be counted as capture? If so, the IR is UB because the argument attribute says no capture but in reality it is.

**Comment by arsenm** [comment]
> Does this mean AS cast should be counted as capture? If so, the IR is UB because the argument attribute says no capture but in reality it is.

No. We want something that's almost nocapture, but doesn't exist. Ideally we would have some similar attribute about whether the address space is significant. Failing that, I think the is-captured utility function could have a parameter to ignore no capture callsites

**Comment by jayfoad** [comment]
"Capturing" seems to be entirely the wrong concept here. Why do we use PointerMayBeCaptured in the AddrSpaceCast case, instead of using the same worklist processing that we use for everything else?

**Comment by shiltian** [comment]
> "Capturing" seems to be entirely the wrong concept here. Why do we use PointerMayBeCaptured in the AddrSpaceCast case, instead of using the same worklist processing that we use for everything else?

We already did here. The problem is we did a partial promotion. It drops the use as a pointer that might be captured. However, since here we have a nocapture attribute on the function argument, it passes the check.
