### ISSUE TITLE
`(a == 0) & (((short)a) >= 0)` is not always optimized to just `a == 0`

### ISSUE THREAD

**Issue by pinskia** [llvm/llvm-project#66733]
Take:
```
int f(int a)
{
        short b = a;
        _Bool t = a == 0;
        _Bool t1 = b >= 0;
        return t & t1;
}
void f0(int a, int *b)
{
        *b= f(a) != 0;
}
void f01(int a, int *b)
{
        _Bool c = f(a);
        *b= c;
}
void f01_(int a, _Bool *b)
{
        _Bool c = f(a);
        *b= c;
}
_Bool f00(int a)
{
        return f(a);
}
void f00_(int a, _Bool *b)
{
        _Bool c = f00(a);
        *b= c;
}
_Bool f1(int a)
{
        _Bool t = a == 0;
        short t1 = a;
        _Bool t2 = t1 >= 0;
        return t & t2;
}
```
`f`, `f00` and `f1` should all produce the same optimized code of just `a == 0;` While `f0`, `f01`, `f01_` and `f00_` all should produce `*b = a == 0;` But currently `f`, `f0`, f01` all still have the short comparison `>=` being included.

I am filing this because the way LLVM is acting here seems like `((short)a) < 0` is being transformed too early to `(a >> 15) & 1` and then never going back sometimes. This happens on x86_64, aarch64, riscv and BPF targets.

**Comment by XChy** [comment]
Reduced and [alive2](https://alive2.llvm.org/ce/z/pjKVt7).

**Comment by marcauberer** [comment]
I would like to work on this

**Comment by marcauberer** [comment]
We can generalize it even further to [Alive2](https://alive2.llvm.org/ce/z/898qfc).

**Comment by nikic** [comment]
This will probably get fixed by https://github.com/llvm/llvm-project/pull/66740.

**Comment by marcauberer** [comment]
Alright, let's wait for the change to be merged then ...
