### ISSUE TITLE
[Flang] Compilation error of operations on arrays of different shapes

### ISSUE THREAD

**Issue by ohno-fj** [llvm/llvm-project#66735]
```
Version of flang-new : 18.0.0(c07062a2e9bf9aa1211b958f6bb4c5746139c180)
```

Operations on arrays of different shapes result in a compilation error.

The following are the test program, Flang-new, Gfortran and ifort compilation result.

snfmi113_7.f90:
```fortran
program main
  real a(10,10),b(10)
  a=1
  b=2
  call sub(a,b)
  print *,'pass'
contains
  subroutine sub(a,b)
    real a(:,:),b(:),c(10)
    c=sin(b)+shape(a)
    write(6,*) "c = ", c
  end subroutine sub
end program main
```

```
$ flang-new snfmi113_7.f90
error: Semantic errors in snfmi113_7.f90
./snfmi113_7.f90:10:5: error: Dimension 1 of left-hand side has extent 1000, but right-hand side has extent 2
      c=sin(b)+shape(a)
      ^
$
```

```
$ gfortran snfmi113_7.f90
$
```

```
$ ifort snfmi113_7.f90
$
```

**Comment by klausler** [comment]
The SHAPE of a rank-2 array has two elements.  This allows the compiler to deduce the extent of the right-hand side expression of the assignment statement.  The extent doesn't match the size of the left-hand side variable, hence the error.

**Comment by ivan-pi** [comment]
It's scary that gfortran and ifx don't err out, even when warnings and runtime checks are turned on...

**Comment by klausler** [comment]
Closing this bug report as no change to f18 is required.
