### ISSUE TITLE
wasm-ld discards elem segments

### ISSUE THREAD

**Issue by camilstaps** [llvm/llvm-project#66752]
It seems that `wasm-ld` sometimes discards `elem` segments which are needed when references to functions are made. With the following files:

```wat
;; llvm-table.wat
(module
	(import "llvm-table-a" "populate" (func $populate))

	(table $table (export "table") 1 funcref)

	(func $main
		(call $populate)
		(call_indirect $table (i32.const 0))
	)
)

;; llvm-table-a.wat
(module
	(import "llvm-table" "table" (table $table 1 funcref))

	(elem func $f)
	(func $f)

	(func $populate
		(table.set $table (i32.const 0) (ref.func $f))
	)
)
```

the `elem` segment is required for `ref.func` in llvm-table-a to work. However, running:

```
wat2wasm -r --enable-multi-memory llvm-table.wat
wat2wasm -r --enable-multi-memory llvm-table-a.wat
wasm-ld-17 --no-entry --export=main --import-table llvm-table.wasm llvm-table-a.wasm -o llvm-table.linked.wasm
```

results in a linked file where the `elem` segment has been removed:

```
$ wasm2wat llvm-table.linked.wasm 
llvm-table.linked.wasm:000006a: error: function 1 is not declared in any elem sections
```
```wat
;; wasm2wat --no-check llvm-table.linked.wasm
(module
  (type (;0;) (func))
  (func $main (type 0)
    call $populate
    i32.const 0
    call_indirect (type 0))
  (func $f (type 0))
  (func $populate (type 0)
    i32.const 0
    ref.func $f
    table.set 0)
  (table (;0;) 1 funcref)
  (memory (;0;) 2)
  (global $__stack_pointer (mut i32) (i32.const 66560))
  (export "memory" (memory 0))
  (export "main" (func $main))
  (export "table" (table 0)))
```

Is this intentional? Maybe I'm misunderstanding how to share a `table` over multiple files?

**Comment by sbc100** [comment]
IIUC this is just something that nobody has tried to do before and wasm-ld doesn't yet support. 

Currently I think we only write element segment for the synthetic `__indirect_function_table`: https://github.com/llvm/llvm-project/blob/84c899b2350f95ab4d1a335158363d2c112029ba/lld/wasm/SyntheticSections.cpp#L560-L612

For other, user-defined, tables I guess one logical approach would be concatenate all the input element segment while effectively relocating each element?   If you would like to work on that I imagine it would be fairly small patch.  But bear in mind that are you on the current edge of what is supported here so there are likely more issues lurking.

**Comment by sbc100** [comment]
Yes, elem segments for `__indirect_function_table` are completely synthetic and created by the linker at link time based on the relocations used in the output file.   i.e. the contents of the table are set based on which functions are address taken.

What we probably can/should in your case is treat `ref.func $f` as "address taken" and include $f in the able in this case.

Right now we only look at the relocations in `call_indirect`.

**Comment by sbc100** [comment]
BTW I would not use `wat2wasm -r` to create inputs for wasm-ld as it has very limited ability to create relocation data.  Instead, for these types of low level object creation i would recomment using the `.s` format and compiling with `llvm-mc`

**Comment by sbc100** [comment]
Having just tried to use `.s` here I noticed that llvm doesn't yet support the `ref.func` instruction in the assembly format so that would be the first thing to add i think.

**Comment by camilstaps** [comment]
@sbc100 I was entirely unaware of `llvm-mc`'s capability to read Wasm text format, thanks! Is this format (or the interface to generate it) stable and/or documented? I have not been able to find anything. I know of course about the Wasm ops themselves, and I assume that `.text` and `.file` are common LLVM annotations, but `.tabletype` (and `.functype`?) are probably Wasm-specific and I have not seen them in other tools.

Experimenting with this format I found out I can do `i32.const f` to get a table index for a function reference. That is not as flexible as `ref.func`, but probably suffices for my use case. For my latest example, for reference:

```txt
	.text
	.tabletype	__indirect_function_table, funcref
	.section	.text.f,"",@
	.globl	f
	.type	f,@function
f:
	.functype	f () -> ()
	end_function
	.section	.text.main,"",@
	.globl	main
	.type	main,@function
main:
	.functype	main () -> ()
	i32.const	f
	call_indirect () -> ()
	end_function
```

Let me know if you want me to close the issue if it indeed turns out that no work needs to be done for my use case.

**Comment by sbc100** [comment]
The `.s` format used by llvm is only really used in llvm and its designed to mirror other common asm formats.  I don't think its documented anywhere, I normally just refer to the test cases.

Yes I think we can close this issue.   We could open another one for "ref.func is not implemented", although perhaps we should wait until somebody asks for it.
