### ISSUE TITLE
[SLP] Assertion failure after D159205

### ISSUE THREAD

**Issue by vzakhari** [llvm/llvm-project#66795]
Flang triggers an assertion after https://reviews.llvm.org/D159205 (5bab59d) on `CPU2006/416.gamess`.

Reduced test case: [reduced.ll.gz](https://github.com/llvm/llvm-project/files/12665101/reduced.ll.gz)

Compilation command: `opt -O2 -vectorize-slp reduced.ll -S`
```
opt: .../llvm/lib/IR/Value.cpp:507: void llvm::Value::doRAUW(llvm::Value *, llvm::Value::ReplaceMetadataUses): Assertion `!conta
ins(New, this) && "this->replaceAllUsesWith(expr(this)) is NOT valid!"' failed.
```

The test passes when I revert the commit.

**Comment by alexey-bataev** [comment]
Fixed in 7db87a66b0206af027724fc1704e5e5ce7772a45
