### ISSUE TITLE
[Clang] Clang fails to escalate a plain `constexpr` function to an immediate function in some cases

### ISSUE THREAD

**Issue by frederick-vs-ja** [llvm/llvm-project#66849]
The following code snippets are rejected by Clang, while they're accepted if `constexpr` is manually replaced with `consteval` ([demo 1](https://godbolt.org/z/den69Ej5a), [demo 2](https://godbolt.org/z/x1jMbhKo1)).

```C++
consteval int next(int n)
{
    return n + 1;
}

constexpr bool test()
{
    int x = 42;
    int y = next(x);
    (void) y;
    return true;
}

static_assert(test());
```

```C++
consteval int *new_ints(unsigned int n)
{
    return new int[n];
}

consteval void delete_ints(int* p)
{
    delete[] p;
}

constexpr bool new_and_delete() // compiles if `constexpr` is manually replaced with `consteval`
{
    auto p = new_ints(42);
    delete_ints(p);
    return true;
}

static_assert(new_and_delete());
```

IIUC `next(x)`, `new_ints(42)` and `delete_ints(p)` are immediate-escalating expressions, and the outer functions `test` and `new_and_delete` are immediate-escalating functions, so the outer functions should be escalated to immediate functions and the examples (along with the original example in #66324) should be well-formed.

CC @cor3ntin.

**Comment by cor3ntin** [comment]
Per http://eel.is/c++draft/expr.const#17,

> An immediate-escalating function is
>  - the call operator of a lambda that is not declared with the consteval specifier,
> - a defaulted special member function that is not declared with the consteval specifier, or
> - a function that results from the instantiation of a templated entity defined with the constexpr specifier.

Specifically, the last bullet. Neither `test`, nor `new_and_delete` are templated entity so they don't get to be escalated.

So I believe Clang is correct here. Does that make sense to you?

**Comment by frederick-vs-ja** [comment]
@cor3ntin Oh, thanks for interpretation. I'm sorry for misreading the specification.

I've verified that adding `template<class = void>` works, so Clang is likely correct now.
