### ISSUE TITLE
Regression in clang-format-17 or clang-format-18?

### ISSUE THREAD

**Issue by prj-** [llvm/llvm-project#66857]
```
$ cat 16.cxx 
typedef struct _n_PetscLogHandlerHot {
  PetscLogHandler handler;
  PetscErrorCode (*eventBegin)(PetscLogHandler, PetscLogEvent, PetscObject, PetscObject, PetscObject, PetscObject);
  PetscErrorCode (*eventEnd)(PetscLogHandler, PetscLogEvent, PetscObject, PetscObject, PetscObject, PetscObject);
  PetscErrorCode (*eventSync)(PetscLogHandler, PetscLogEvent, MPI_Comm);
  PetscErrorCode (*objectCreate)(PetscLogHandler, PetscObject);
  PetscErrorCode (*objectDestroy)(PetscLogHandler, PetscObject);
} PetscLogHandlerHot;
$ clang-format --version
clang-format version 17.0.1
$ clang-format --style=file:clang-format.txt 16.cxx | tee 17.cxx
typedef struct _n_PetscLogHandlerHot {
  PetscLogHandler handler;
  PetscErrorCode  (*eventBegin)(PetscLogHandler, PetscLogEvent, PetscObject, PetscObject, PetscObject, PetscObject);
  PetscErrorCode  (*eventEnd)(PetscLogHandler, PetscLogEvent, PetscObject, PetscObject, PetscObject, PetscObject);
  PetscErrorCode  (*eventSync)(PetscLogHandler, PetscLogEvent, MPI_Comm);
  PetscErrorCode  (*objectCreate)(PetscLogHandler, PetscObject);
  PetscErrorCode  (*objectDestroy)(PetscLogHandler, PetscObject);
} PetscLogHandlerHot;
$ clang-format-18 --version
Debian clang-format version 18.0.0 (++20230918111206+08d2ea372ff6-1~exp1~20230918111321.1580)
$ clang-format-18 --style=file:clang-format.txt 17.cxx | tee 18.cxx
typedef struct _n_PetscLogHandlerHot {
  PetscLogHandler handler;
  PetscErrorCode (*eventBegin)(PetscLogHandler, PetscLogEvent, PetscObject, PetscObject, PetscObject, PetscObject);
  PetscErrorCode (*eventEnd)(PetscLogHandler, PetscLogEvent, PetscObject, PetscObject, PetscObject, PetscObject);
  PetscErrorCode (*eventSync)(PetscLogHandler, PetscLogEvent, MPI_Comm);
  PetscErrorCode (*objectCreate)(PetscLogHandler, PetscObject);
  PetscErrorCode (*objectDestroy)(PetscLogHandler, PetscObject);
} PetscLogHandlerHot;
```
Which one is correct? Version 17 or version 18? [clang-format.txt](https://github.com/llvm/llvm-project/files/12668673/clang-format.txt)

**Comment by owenca** [comment]
> Which one is correct? Version 17 or version 18?

Version 17 is correct.

**Comment by prj-** [comment]
@owenca, you said initially that version 17.0.1 was right. The formatting was the same until very recently, but with version 17.0.4 (it was the same up until 17.0.3), it changed again. Could you please clarify this for me?

**Comment by owenca** [comment]
We reverted aligning function pointers in 17.0.4 because it caused a regression in 17.x. (See #68079.) So 16, 17.0.4, and 18 are "correct" now.

Do you have any preference whether function pointers are aligned with other consecutive declarations?

**Comment by prj-** [comment]
I don't really care, but again, you said initially that it was a regression in everything but 17.0.1, but if I understand you correctly, it was in fact not a regression? So, is this good once and for all now? This is triggering massive white space changes in our code base, which is not desirable, so it would be good to know whether the behavior will be changed a fourth time or not anytime soon.

**Comment by owenca** [comment]
> I don't really care, but again, you said initially that it was a regression in everything but 17.0.1, but if I understand you correctly, it was in fact not a regression?

When did I ever say that "it was a regression in everything but 17.0.1"??

> > Which one is correct? Version 17 or version 18?
> 
> Version 17 is correct.

You asked which of the two versions were correct, and I gave you the one deemed to be "correct" at the time.

> So, is this good once and for all now?

It depends on what you mean by "good". If you mean the future minor and major releases will not cause your codebase to be reformatted at all, then it will probably never be "good". For one thing, we fix bugs and thus change how code is formatted. We also add features people want. Both of which may introduce new bugs and trigger regressions.

**Comment by prj-** [comment]
My phrasing was wrong. Since you said that 17.0.1 was correct, I thought that there was: a) a bug prior to version 17, b) a regression in version 18. But it looks like I'm reading too much between the lines.

> We also add features people want

Fine, since this change back and forth does not seem to be a bug or a regression, how do we control this feature so that there is no further change? `function pointer` does not return anything in https://clang.llvm.org/docs/ClangFormatStyleOptions.html.

**Comment by owenca** [comment]
> Fine, since this change back and forth does not seem to be a bug or a regression, how do we control this feature so that there is no further change?

See https://github.com/llvm/llvm-project/issues/68079#issuecomment-1771875958. We'll see if it makes sense to add aligning function pointers as a suboption, but you probably want to turn off `AlignConsecutiveDeclarations` until the issue is settled.

**Comment by prj-** [comment]
> but you probably want to turn off AlignConsecutiveDeclarations until the issue is settled.

Such as change is triggering a whopping diff with `2384 files changed, 53965 insertions(+), 53965 deletions(-)`... Anyway, we have chosen to stick with clang-format version 16 for the time being, sadly. Thank you for the explanation.

**Comment by owenca** [comment]
I think you can go with 17.0.4 (or 17.0.5 which is scheduled to be released within 2 weeks).
