### ISSUE TITLE
clang-format CMakeCXXCompilerId.cpp takes 38 minutes with "QualifierAlignment: Left"

### ISSUE THREAD

**Issue by anordal** [llvm/llvm-project#66907]
Create a CMake hello-world project and (accidentally) format the build directory:

```
> time clang-format -i build/CMakeFiles/3.27.2/CompilerIdCXX/CMakeCXXCompilerId.cpp
Executed in    3.46 secs
> echo "QualifierAlignment: Left" > .clang-format
> time clang-format -i build/CMakeFiles/3.27.2/CompilerIdCXX/CMakeCXXCompilerId.cpp
Executed in   38.36 mins
```

clang-format version 16.0.6

**Comment by mydeveloperday** [comment]
How big is the file and what is in it?

**Comment by anordal** [comment]
Oh, less than 1000 lines of mostly preprocessor macros. Here is how to recreate it:

```bash
mkdir true
cd true
echo 'int main(){}' > main.cpp
printf 'project(true)\nadd_executable(true main.cpp)' > CMakeLists.txt
cmake -G Ninja -B build
```

Now, there should be a file at `build/CMakeFiles/*/CompilerIdCXX/CMakeCXXCompilerId.cpp`.

**Comment by mydeveloperday** [comment]
Could you try the same with 17, some changes landed recently to improve the speed

**Comment by anordal** [comment]
Nice, clang-format 17 now finishes within 10s on my laptop (a slower machine). Problem solved.

The speedup numbers are pretty great too: Clang-format 17 is 400 times faster than 16 and 15, and `QualifierAlignment: Left` is only 3/2 times as slow, instead of 600 times.

Thanks for the speedup!
