### ISSUE TITLE
[Linker][Opt] opt delete the `main` func of llvm ir

### ISSUE THREAD

**Issue by LRY89757** [llvm/llvm-project#66917]
```llvm
define internal i32 @func() {
  ; Function body
  br label %b
b:
  unreachable
}

define linkonce_odr void @main() {
entry:
  %call = call i32 @func()
  ret void
}
```

It will delete the `main` func and then the linker can't find the main  symbol

**Comment by zygoloid** [comment]
This is working as intended: `linkonce_odr` is a discardable linkage type (from the LangRef: "Unreferenced `linkonce` globals are allowed to be discarded.").
