### ISSUE TITLE
[clang-format] Formatting regression in 17.0.0 introduces spacing around arrow operator in macros

### ISSUE THREAD

**Issue by sfc-gh-mheimel** [llvm/llvm-project#66923]
It seems that there is a formatting regression in 17.0.0 that affects the spacing of the arrow operator in macros containing assignments. Here's a minimal example (with an empty clang format config) to reproduce the issue:
```c++
$ cat test.cpp
#define P(ptr) auto p = (ptr)->p
```

In version 16, this is correctly formatted:
```c++
$ clang-format-16 test.cpp
#define P(ptr) auto p = (ptr)->p
$ clang-format-16 --version
clang-format version 16.0.0
```

With version 17, clang-format (incorrectly) wants to add spacing around the arrow operator:
```c++
$ clang-format-17 test.cpp
#define P(ptr) auto p = (ptr) -> p
$ clang-format-17 --version
clang-format version 17.0.0
```

Interestingly, the behavior is switched when the macro is removed:
```c++
$ cat test.cpp
auto p = (ptr)->p;
$ clang-format-17 test.cpp
auto p = (ptr)->p;
$ clang-format-16 test.cpp
auto p = (ptr) -> p;
```

**Comment by rymiel** [comment]
This was regressed by c70e360b355ad30a7dd299435aae0324c5033b3f (I take the blame)
This looks a lot like https://github.com/llvm/llvm-project/issues/61469, except inside of macros
I guess fixing both this issue and https://github.com/llvm/llvm-project/issues/47664 at the same time will take a more sophisticated heuristic..?

**Comment by rymiel** [comment]
@owenca should I revert c70e360b355ad30a7dd299435aae0324c5033b3f for the 17 release branch?

**Comment by owenca** [comment]
@rymiel I wasn't sure if we should revert it, but it doesn't matter now. :)

**Comment by rymiel** [comment]
Thank you for doing what I couldn't!
