### ISSUE TITLE
Flang not respecting `-module` flag

### ISSUE THREAD

**Issue by h-vetinari** [llvm/llvm-project#66969]
While [trying](https://github.com/conda-forge/scipy-feedstock/pull/252) to get flang working on a project that uses the meson build system, we ran into:

```
[133/1628] Compiling Fortran object scipy/special/libamos.a.p/amos_dgamln.f.obj
FAILED: scipy/special/libamos.a.p/amos_dgamln.f.obj 
"flang-new" "-Iscipy\special\libamos.a.p" "-Iscipy\special" "-I..\scipy\special" "-fcolor-diagnostics" "-DNDEBUG" "-D_FILE_OFFSET_BITS=64" "-O3" "-module" "scipy\special\libamos.a.p" -MD -MQ scipy/special/libamos.a.p/amos_dgamln.f.obj -MF "scipy\special\libamos.a.p\amos_dgamln.f.obj.d" -o scipy/special/libamos.a.p/amos_dgamln.f.obj "-c" ../scipy/special/amos/dgamln.f
flang-new: error: unknown argument: '-module'

flang-new: warning: scipy\special\libamos.a.p: 'linker' input unused
```
This is because `-module` is apparently so common in Fortran compilers, that it's the [baseline](https://github.com/mesonbuild/meson/blob/1.2.1/mesonbuild/compilers/fortran.py#L94-L95) assumption for how meson constructs its commandline invocations for most Fortran compilers (it's worth noting that this method gets overridden for several compilers, though notably, meson for classic flang defaults to `-module`).

It seems this assumption matches parts of flang's documentation (which do indicate `-module` support)...
https://github.com/llvm/llvm-project/blob/2147e9e09f83042defdace45eb73580e1f0f5c28/flang/docs/ModFiles.md?plain=1#L106-L121

... but not [others](https://flang.llvm.org/docs/FlangCommandLineReference.html#cmdoption-flang-module-dir-dir), which say:
> -module-dir\<dir>, -J\<arg>
> 
> This option specifies where to put .mod files for compiled modules. It is also added to the list of directories to be searched by an USE statement. The default is the current directory.

I'm not sure if this was an oversight in the recent option-refactor. It's certainly conceivable to teach meson that (llvm-)flang needs `-module-dir` instead of `-module`. However, it's at least surprising (given the documentation divergence), so I thought I'd raise this.

CC @banach-space

**Comment by banach-space** [comment]
Hi @h-vetinari , sorry for the delay. You will find the relevant discussion here: https://lists.llvm.org/pipermail/flang-dev/2020-November/000597.html

`flang-new` supports `-module-dir` and `-J`. Perhaps you could use the latter? That would be compatible with GNU.

**Comment by h-vetinari** [comment]
Ok, thanks for the context and confirming that this is intentional. Closing
