### ISSUE TITLE
How to compile a c++ header file to LLVM IR?

### ISSUE THREAD

**Issue by vifird** [llvm/llvm-project#67]
Useful to generate c++ functions to IR, those will used in modules those created by IRBuilder:[https://stackoverflow.com/questions/24728901/clang-compiling-a-c-header-to-llvm-ir-bitcode](https://stackoverflow.com/questions/24728901/clang-compiling-a-c-header-to-llvm-ir-bitcode)

**Comment by tstellar** [comment]
This type of comment is probably better suited for IRC or discord.  Issues are for reporting bugs.
