### ISSUE TITLE
[x86] clang is suboptimal for `-1 * !!x` since clang 15.0.0

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#67008]
Consider the following:
https://godbolt.org/z/EYn7Eb4bd
```cpp
int f(int x) {
  return -1 * !!x;
}
```

Clang 14.0.0 and GCC:
```asm
f(int):                                  # @f(int)
        neg     edi
        sbb     eax, eax
        ret
```

From Clang 15.0.0:
```asm
f(int):                                  # @f(int)
        xor     eax, eax
        neg     edi
        sbb     eax, eax
        ret
```

**Comment by RKSimon** [comment]
IR:
```
define i32 @f(i32 noundef %x) {
  %tobool = icmp ne i32 %x, 0
  %conv.neg = sext i1 %tobool to i32
  ret i32 %conv.neg
}
```
Its to break a false dependency on Intel cpus - specifying an AMD cpu should give you optimal code:
```
llc -mcpu=btver2
f:                                      # @f
        neg     edi
        sbb     eax, eax
        ret
```

**Comment by k-arrows** [comment]
> Its to break a false dependency on Intel cpus - specifying an AMD cpu should give you optimal code:

Yes, I get optimal code with `-march=btver2`.
https://godbolt.org/z/WMWMEehv3

Does that mean this is not a problem? I still don't understand what "a false dependency on Intel cpus" means in this context.

**Comment by RKSimon** [comment]
```asm
        xor     eax, eax
        neg     edi
        sbb     eax, eax
        ret
```
Some Intel CPUs don't realize that the SBB just relies on the flag result from the NEG and doesn't actually use the old EAX value (its self-subtracting itself) - which can cause a stall if the EAX is still being computed in an earlier out-of-order computation. By adding the XOR, all modern x86 cpus recognise that the EAX value is now zero and breaks the dependency on any previous value it had.

**Comment by k-arrows** [comment]
Thank you very much for the explanation. I will close this issue.
