### ISSUE TITLE
C++20 std::midpoint is non-conformant

### ISSUE THREAD

**Issue by bregma** [llvm/llvm-project#67046]
The second (pointer) overload of `std::midpoint()` fails to compile when used explicitly. This is a failure to accept valid code according to ISO/IEC 14882:2020 25.10.16/4 [numeric.ops.midpoint].  See https://godbolt.org/z/MxdanhvEE

Example:
```
#include <numeric>

template<typename T>
  T* mp(T* b, T*e) {
    return std::midpoint<T>(b, e);
  }

int main() {
    char a[2];
    char* p = mp(a, a+2);
}
```
gives the following compilation errors.
```
<source>:5:12: error: no matching function for call to 'midpoint'
    5 |     return std::midpoint<T>(b, e);
      |            ^~~~~~~~~~~~~~~~
<source>:10:15: note: in instantiation of function template specialization 'mp<char>' requested here
   10 |     char* p = mp(a, a+2);
      |               ^
/opt/compiler-explorer/clang-17.0.1/bin/../include/c++/v1/__numeric/midpoint.h:40:1: note: candidate function template not viable: no known conversion from 'char *' to 'char' for 1st argument; dereference the argument with *
   40 | midpoint(_Tp __a, _Tp __b) noexcept
      | ^        ~~~~~~~
/opt/compiler-explorer/clang-17.0.1/bin/../include/c++/v1/__numeric/midpoint.h:61:1: note: candidate template ignored: requirement 'is_pointer_v<char>' was not satisfied [with _TPtr = char]
   61 | midpoint(_TPtr __a, _TPtr __b) noexcept
      | ^
/opt/compiler-explorer/clang-17.0.1/bin/../include/c++/v1/__numeric/midpoint.h:78:1: note: candidate template ignored: requirement 'is_floating_point_v<char>' was not satisfied [with _Fp = char]
   78 | midpoint(_Fp __a, _Fp __b) noexcept
      | ^
1 error generated.
Compiler returned: 1
```
The following patch resolves the error.
```
57c57,58
< enable_if_t<is_object_v<remove_pointer_t<_TPtr>>
---
> enable_if_t<is_pointer_v<_TPtr>
>              && is_object_v<remove_pointer_t<_TPtr>>
59,60c60,61
<              && (sizeof(remove_pointer_t<_TPtr>) > 0), _TPtr*>
< midpoint(_TPtr* __a, _TPtr* __b) noexcept
---
>              && (sizeof(remove_pointer_t<_TPtr>) > 0), _TPtr>
> midpoint(_TPtr __a, _TPtr __b) noexcept
```

**Comment by shafik** [comment]
It looks this works if we use `libstdc++`: https://godbolt.org/z/1o1Y588re

**Comment by jmintb** [comment]
Can I have a go at this? :)

**Comment by ldionne** [comment]
> Can I have a go at this? :)

Yes, absolutely! Assigning to you.

**Comment by SanjayMarreddi** [comment]
Hi @jmintb, Could you please let us if you are currently working on this? If not, I would be happy to look into it and contribute. Thanks!

**Comment by SanjayMarreddi** [comment]
@ldionne Sure, I will work on it, Thanks!

**Comment by mordante** [comment]
Thanks for your patch! In the standard, the section names `[numeric.ops.midpoint]` are often the best reference, the numbers change quite often. The commonly used place to look for the wording is http://eel.is/c++draft/numeric.ops.midpoint. (This is not the official Standard.)

**Comment by SanjayMarreddi** [comment]
Thanks for the information @mordante! I'm traveling tomorrow, so I will continue with this PR later in the week.

**Comment by SanjayMarreddi** [comment]
Hi @mordante, I have rebased my local branch with the recent changes on the upstream. I am unable to replicate ( **without my changes as well** ) the above error related to midpoint now :) 

I am following the below steps to reproduce:

### Step 1: 
```
# `run.sh` to quickly build, install and test from scratch.
rm -rf build
mkdir build
cmake -G Ninja -S runtimes -B build -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind"  -DCMAKE_INSTALL_PREFIX="/usr/local/opensource/" 
ninja -C build cxx cxxabi unwind 
ninja -C build install-cxx install-cxxabi install-unwind
sudo libcxx/utils/libcxx-lit build/ -sv libcxx/test/libcxx/numerics
```
- As we expect the step 1 is successful.
-  Please note the DCMAKE_INSTALL_PREFIX as I am on macOS.

### Step 2: 
```
      clang++ -nostdinc++ -nostdlib++           \
          -isystem /usr/local/opensource/include/c++/v1 \
          -L /usr/local/opensource/lib                  \
          -Wl,-rpath,/usr/local/opensource/lib          \
          -lc++                             \
          ../Notes/midpoint_test.cc --std=c++20
```
- Testing by following [this](https://libcxx.llvm.org/UsingLibcxx.html#using-a-custom-built-libc)
- The `midpoint_test.cc` contains the code by the author of the issue. We expect to see the error pointed above. But I am not able to see the error anymore. 

**Can you please look into it and let me know what I am missing?**
