### ISSUE TITLE
miscompile of store to element of <i1 x N>

### ISSUE THREAD

**Issue by zygoloid** [llvm/llvm-project#67060]
LLVM is optimizing a store to an element of an `<i1 x N>` into an `i1` store, which then gets lowered to a byte store, clobbering adjacent vector elements.

[Testcae](https://godbolt.org/z/dPeKErroY):

```c++
typedef __attribute__((ext_vector_type(32))) bool v32bool;

v32bool v32b;

void set() {
    v32b[0] = true;
}
```

is lowered by Clang to

```llvm
@v32b = dso_local global i32 0, align 4

define dso_local void @set()() {
entry:
  %0 = load i32, ptr @v32b, align 4
  %1 = bitcast i32 %0 to <32 x i1>
  %vecins = insertelement <32 x i1> %1, i1 true, i32 0
  %2 = bitcast <32 x i1> %vecins to i32
  store i32 %2, ptr @v32b, align 4
  ret void
}
```

and then incorrectly optimized into

```llvm
define dso_local void @set()() local_unnamed_addr {
entry:
  store i1 true, ptr @v32b, align 4
  ret void
}
```

The transform would be correct if the vector elements were byte-aligned, but is not correct in this case.

**Comment by zygoloid** [comment]
Storing to `v32b[1]` gives this, which doesn't look like it should be valid IR to me:
```llvm
  store i1 %b, ptr getelementptr inbounds (<32 x i1>, ptr @v32b, i64 0, i64 1), align 1
```
(This is forming a non-byte-aligned pointer...)

**Comment by nikic** [comment]
Problematic pass is VectorCombine: https://llvm.godbolt.org/z/s6KcEqTcv Doesn't deal with non-byte-sized types correctly.
