### ISSUE TITLE
[X86] `i8` -> `half` vector conversion is scalarized

### ISSUE THREAD

**Issue by dcaballe** [llvm/llvm-project#67080]
The following vector conversion seems to be scalarized when compiled for AVX-512: 

```llvm
define <64 x half> @test(<64 x i8> %int8) {
    %fp16 = uitofp <64 x i8> %int8 to <64 x half>
    ret <64 x half> %fp16
}
```
`llc test.ll -mcpu=cascadelake`

```asm
    vpmovzxbw	%ymm0, %zmm1	vextracti32x4	$3, %zmm1, %xmm4
	vpextrw	$7, %xmm4, %eax
	vcvtsi2ss	%eax, %xmm2, %xmm2
	vcvtps2ph	$4, %xmm2, %xmm2
	vmovd	%xmm2, %eax
	vpinsrw	$0, %eax, %xmm0, %xmm5
	vpextrw	$6, %xmm4, %eax
	vcvtsi2ss	%eax, %xmm3, %xmm2
	vcvtps2ph	$4, %xmm2, %xmm2
	vmovd	%xmm2, %eax
	vpinsrw	$0, %eax, %xmm0, %xmm6
	vextracti32x4	$2, %zmm1, %xmm3
	vpextrw	$7, %xmm3, %eax
	vcvtsi2ss	%eax, %xmm7, %xmm2
	vcvtps2ph	$4, %xmm2, %xmm2
	vmovd	%xmm2, %eax
	vpinsrw	$0, %eax, %xmm0, %xmm7
    ....
```

Interesting enough, the `float` -> `half` vector conversion seems to be supported:
```llvm
define <64 x half> @test(<64 x float> %int8) {
    %fp16 = fptrunc <64 x float> %int8 to <64 x half>
    ret <64 x half> %fp16
}
```
```asm
	vcvtps2ph	$4, %zmm0, %ymm0
	vcvtps2ph	$4, %zmm1, %ymm1
	vinsertf64x4	$1, %ymm1, %zmm0, %zmm0
	vcvtps2ph	$4, %zmm2, %ymm1
	vcvtps2ph	$4, %zmm3, %ymm2
	vinsertf64x4	$1, %ymm2, %zmm1, %zmm1
	retq
```

So probably the intermediate `i8` -> `float` step in the conversion is where the implementation gap is.

**Comment by goldsteinn** [comment]
Also for `i16` -> `half`: https://godbolt.org/z/rPo118Y5Y

**Comment by goldsteinn** [comment]
The issue occurs during legalization, so probably just missing a few lines.

**Comment by Bug-CS** [comment]
This might work..
; Convert <64 x float> to <64 x half>
define <64 x half> @floatToHalf(<64 x float> %float) {
    %fp16 = fptrunc <64 x float> %float to <64 x half>
    ret <64 x half> %fp16
}

; Convert <64 x i8> to <64 x float>
define <64 x float> @int8ToFloat(<64 x i8> %int8) {
    %fp32 = uitofp <64 x i8> %int8 to <64 x float>
    ret <64 x float> %fp32
}

**Comment by dcaballe** [comment]
Kindly pinging this issue to see if there is anybody with the right expertise that can help with this. Thanks in advance :)

**Comment by qcolombet** [comment]
I took a stab at this.
See attached [tentative patch](https://github.com/llvm/llvm-project/files/13207814/x86-isel.patch).

Essentially, I avoided to go through the `i16` type in `xitofp` conversions when `i16` is not supported natively in conversions (which if I'm not mistaken only exists with AVX512).

I didn't actually look at the assembly diffs closely and the check may be too coarse grain/have unexpected side-effects. I.e., the patch may need polishing and the first thing to do to land this would be to go through the assembly diff from the lit test (see the patch) and check that there are no perf regression.

@dcaballe could you give the patch a try and report back if it does what you want?
Then we'll decide whether it makes sense to productize it.

**Comment by dcaballe** [comment]
Thanks, Quentin! I can confirm this improves my workload by 40% overall.
This is the IR I see for one of the instances:

```
# %18 = arith.sitofp %17 : i8 to f16
    vpmovsxbd  %xmm0,%zmm0
    vcvtdq2ps  %zmm0,%zmm0
    vcvtps2ph  $0x4,%zmm0,%ymm0                                                                                                                                                                    
# %19 = arith.mulf %in, %18 : f16
    vcvtph2ps  (%rax,%r15,2),%zmm1
    vcvtph2ps  %ymm0,%zmm0
    vmulps     %zmm0,%zmm1,%zmm0
    vcvtps2ph  $0x4,%zmm0,%ymm0
```

It looks like we are converting the i8 operand from i8 -> f32 -> f16 -> f32. I guess the f32 -> f16 -> f32 part is done to get the right rounding from f16 before the f32 computation?

**Comment by qcolombet** [comment]
> I can confirm this improves my workload by 40% overall.

Nice! I guess that means I need to spend more time to actually land that thing :).

>  I guess the f32 -> f16 -> f32 part is done to get the right rounding from f16 before the f32 computation?

Yes, that's correct.

I haven't tried it, but if you set the fast math flag on both your original instructions, the intermediate rounding step might get eliminated.
