### ISSUE TITLE
How to generate the content of “module @patterns” and "module @ir " in "mlir/test/Rewrite/pdl-bytecode.mlir" file?

### ISSUE THREAD

**Issue by zhengqianisme** [llvm/llvm-project#67101]
I want to generate a similar additional test demo ，like the file "mlir/test/Rewrite/pdl-bytecode.mlir". But i donot know how to generate it. thanks!

**Comment by joker-eph** [comment]
You probably gonna have more success asking on Discourse, we issue GitHub issues for tracking bugs and features
