### ISSUE TITLE
Clang attr emitter tablegen target should guard optional arguments 

### ISSUE THREAD

**Issue by steakhal** [llvm/llvm-project#67156]
I noticed a crash for the following valid code when using the `-ast-print` flag:
https://godbolt.org/z/78xYbEosb
```C++
void *top() __attribute__((assume_aligned(__alignof__(unsigned long long))));
```

The AST looks like this:
```
TranslationUnitDecl
`-FunctionDecl <line:1:1, col:76> col:7 top 'void *()'
  `-AssumeAlignedAttr <col:28, col:74>
    |-UnaryExprOrTypeTraitExpr <col:43, col:73> 'unsigned long' __alignof 'unsigned long long'
    `-<<<NULL>>>
```

Notice the last NULL node.

In the clang/include/clang/Basic/Attr.td, we can see that `AssumeAligned` is defined like this:
```
def AssumeAligned : InheritableAttr {
  let Spellings = [GCC<"assume_aligned">];
  let Subjects = SubjectList<[ObjCMethod, Function]>;
  let Args = [ExprArgument<"Alignment">, ExprArgument<"Offset", 1>];
  let Documentation = [AssumeAlignedDocs];
}
```

Notice the `ExprArgument<"Offset", 1>`, where `1` denotes that this argument is optional, thus might be null.
There are a couple other attributes where we set this flag, but they are really rare.
I found only `CUDALaunchBounds`, `AMDGPUWavesPerEU` and `AssumeAligned`.

Apparently, inside clang/utils/TableGen/ClangAttrEmitter.cpp:`ExprArgument::writeValue`, we emit code that doesn't guard optional arguments before visiting them:
```C++
void writeValue(raw_ostream &OS) const override {
  OS << "\";\n";
  OS << "    get" << getUpperName()
     << "()->printPretty(OS, nullptr, Policy);\n";
  OS << "    OS << \"";
}
```

It should have guarded the call to `printPretty()` to make sure the pointer is valid.
I suspect, that other emit functions suffer from this issue.

This is present on clang-16, and on trunk as of now.

**Comment by steakhal** [comment]
@strimo378 I think you proposed some patches in the area. You might know who would be interested in this bug. Feel free to retitle the issue if it would bring more visibility.

**Comment by strimo378** [comment]
@steakhal Yes, I worked on ast-print but avoided working on attribute printing so far. It looks that you are already on a very good way with your pull request!
