### ISSUE TITLE
clang should produce warning on duplicate enumeration values

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#6715]
|  |  |
| --- | --- |
| Bugzilla Link | [6343](https://llvm.org/bz6343) |
| Version | 2.6 |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @Quuxplusone,@belkadan,@tkremenek,@Weverything |

## Extended Description 
While this code is valid, it can produce unintended bugs.

enum foo
{
	KD_OK = 0,
	KD_ERR = -1,
	KD_foo ,
	KD_bar
};

The code here was intended to make KD_ERR equal to -1, but not to have KD_OK and KD_foo both equal to 0.

**Comment by Quuxplusone** [comment]
https://godbolt.org/z/c7e3cEn7q `-Wduplicate-enum` is not enabled via `-Wall -Wextra`, but it does exist and does detect this issue.
