### ISSUE TITLE
[clang] Crash when mangling variadic concept after 4b163e343c

### ISSUE THREAD

**Issue by BertalanD** [llvm/llvm-project#67244]
Compiling the following code results in an assertion failure on trunk (f1128f3782363ca26e0bdf9323a0d16570dcfba0):

```c++
template<typename T, typename... Ts>
constexpr bool IsOneOf = true;

template<typename T, typename... Ts>
concept OneOf = IsOneOf<T, Ts...>;

template<OneOf<int, bool> T>
void frobnicate(T val) {}

void test() { frobnicate(1); }
```

```console
Assertion failed: (getExpandedPackSize(Param) && "failed to form pack argument for parameter pack"), function getArgInfo, file ItaniumMangle.cpp, line 5797.
```

The crash goes away when `-fclang-abi-compat=17` is specified, so this regression likely comes from 4b163e343c. @zygoloid 

~~It looks like Compiler Explorer's Clang trunk build does not include this commit as of now, so I can't share a link to a live reproducer. But only the `-std=c++20` argument should be necessary to get it to appear.~~ The issue can be seen on the "assertions trunk" builds:

https://godbolt.org/z/n8vqehhfj

**Comment by shafik** [comment]
godbolt should build trunk nightly, maybe you were not using the assertions build of trunk, I can reproduce on godbolt: https://godbolt.org/z/KdrjYv543
