### ISSUE TITLE
Wrong code at -O2 on x86_64-linux_gnu since ddfee6d (recent regression)

### ISSUE THREAD

**Issue by shao-hua-li** [llvm/llvm-project#67287]
Clang at -O2 produced the wrong code.

Bisected to ddfee6d0b6979fc6e61fa5ac7424096c358746fb, which was committed by @goldsteinn 

Compiler explorer: https://godbolt.org/z/rhfGPe4x5

```console
% cat a.c
int printf(const char *, ...);
long a, b, i;
char c, f;
int d;
short e;
int *g = &d;
unsigned h;
char j[1];
int main() {
  short *k = &e;
  for (; *g;)
    ;
  for (; c <= 30; c++) {
    if (b > 4)
      i = a;
    else
      i = b;
    (int)i + 6 || (*k = j != &f);
    *g ^= h;
  }
  printf("%d\n", e);
}
%
% clang a.c -O0 && ./a.out
0
% clang a.c -O2 && ./a.out
1
%
```

**Comment by RKSimon** [comment]
@goldsteinn Any luck with this?

**Comment by goldsteinn** [comment]
So the diff w/ and w/o the change is:
```
<     1263:	66 0f db c8          	pand   %xmm0,%xmm1
<     1267:	66 0f 76 0d b1 0d 00 	pcmpeqd 0xdb1(%rip),%xmm1        # 2020 <_IO_stdin_used+0x20>
<     126e:	00 
<     126f:	41 b8 03 00 00 00    	mov    $0x3,%r8d
<     1275:	45 85 c0             	test   %r8d,%r8d
<     1278:	41 0f 95 c0          	setne  %r8b
<     127c:	66 0f 7f 4c 24 10    	movdqa %xmm1,0x10(%rsp)
<     1282:	44 0a 44 24 10       	or     0x10(%rsp),%r8b
<     1287:	44 0a 44 24 18       	or     0x18(%rsp),%r8b
<     128c:	66 0f 6e 0d d0 2d 00 	movd   0x2dd0(%rip),%xmm1        # 4064 <h>
<     1293:	00 
<     1294:	66 0f 70 d9 50       	pshufd $0x50,%xmm1,%xmm3
<     1299:	66 0f ef c9          	pxor   %xmm1,%xmm1
<     129d:	41 89 f9             	mov    %edi,%r9d
<     12a0:	66 0f ef d2          	pxor   %xmm2,%xmm2
<     12a4:	eb 18                	jmp    12be <main+0x17e>
<     12a6:	66 2e 0f 1f 84 00 00 	cs nopw 0x0(%rax,%rax,1)
<     12ad:	00 00 00 
---
<     1263:	66 0f db c8          	pand   %xmm0,%xmm1
<     1267:	66 0f 76 0d b1 0d 00 	pcmpeqd 0xdb1(%rip),%xmm1        # 2020 <_IO_stdin_used+0x20>
<     126e:	00 
>     126f:	66 0f 70 d1 b1       	pshufd $0xb1,%xmm1,%xmm2
>     1274:	66 0f db d1          	pand   %xmm1,%xmm2
>     1278:	66 44 0f 50 c2       	movmskpd %xmm2,%r8d
>     127d:	45 85 c0             	test   %r8d,%r8d
>     1280:	41 0f 95 c0          	setne  %r8b
>     1284:	0f 29 54 24 10       	movaps %xmm2,0x10(%rsp)
>     1289:	44 0a 44 24 10       	or     0x10(%rsp),%r8b
>     128e:	44 0a 44 24 18       	or     0x18(%rsp),%r8b
>     1293:	66 0f 6e 0d c9 2d 00 	movd   0x2dc9(%rip),%xmm1        # 4064 <h>
>     129a:	00 
>     129b:	66 0f 70 d9 50       	pshufd $0x50,%xmm1,%xmm3
>     12a0:	66 0f ef c9          	pxor   %xmm1,%xmm1
>     12a4:	41 89 f9             	mov    %edi,%r9d
>     12a7:	66 0f ef d2          	pxor   %xmm2,%xmm2
>     12ab:	eb 11                	jmp    12be <main+0x17e>
>     12ad:	0f 1f 00             	nopl   (%rax)
```

I think the issue is some bug related to the fact that its a 32-bit compare (`pcmpeqb`) then used for a 64-bit mask (`movmskpd`) and the use is demanding partial elements. so we know something like 32-bit element 0 is constant, then have a bug where we constant propagate that to a 64-bit element 0 usage.
If we only run the code when `DemandedElts` covers the entire vec there is no bug.

Looking for where this might be.

**Comment by RKSimon** [comment]
```
<     1267:	66 0f 76 0d b1 0d 00 	pcmpeqd 0xdb1(%rip),%xmm1        # 2020 <_IO_stdin_used+0x20>
<     126e:	00 
>     126f:	66 0f 70 d1 b1       	pshufd $0xb1,%xmm1,%xmm2
>     1274:	66 0f db d1          	pand   %xmm1,%xmm2
>     1278:	66 44 0f 50 c2       	movmskpd %xmm2,%r8d
```
This is a icmp_eq <2 x i64> pattern for a pre-SSE41 target, so that's why the movmskpd is there - not sure that helps.

**Comment by goldsteinn** [comment]
> ```
> <     1267:	66 0f 76 0d b1 0d 00 	pcmpeqd 0xdb1(%rip),%xmm1        # 2020 <_IO_stdin_used+0x20>
> <     126e:	00 
> >     126f:	66 0f 70 d1 b1       	pshufd $0xb1,%xmm1,%xmm2
> >     1274:	66 0f db d1          	pand   %xmm1,%xmm2
> >     1278:	66 44 0f 50 c2       	movmskpd %xmm2,%r8d
> ```
> 
> This is a icmp_eq <2 x i64> pattern for a pre-SSE41 target, so that's why the movmskpd is there - not sure that helps.

In DAG its:
```
t90: v4i32 = vector_shuffle<0,5,2,7> t89, t88
t118: v4i32 = bitcast t36
```

I'm thinking the issue is either in the bitcast/shuffle logic that scale/de-scale `DemandedElts`, but haven't found it yet.
Although this being a 64-bit compare doesn't really make sense either. The `0xb1` shuffle mask of 64-bit compare mask is a nop...

**Comment by goldsteinn** [comment]
I think the fundemental issue comes from the following snippet:
```
t77: i32 = X86ISD::MOVMSK t123
  t123: v2i64 = bitcast t122
    t122: v4i32 = and t119, t121
      t119: v4i32 = X86ISD::PCMPEQ t90, t118
        t90: v4i32 = vector_shuffle<0,5,2,7> t89, t88
          t89: v4i32 = bitcast t117
            t117: v2i64 = X86ISD::CMOV t93, t92, TargetConstant:i8<13>, t114:1
              t93: v2i64 = BUILD_VECTOR t2, t2
                t2: i64,ch = CopyFromReg t0, Register:i64 %2
                  t0: ch,glue = EntryToken
              t92: v2i64 = BUILD_VECTOR t26, t26
                t26: i64,ch = load<(dereferenceable load (s64) from @a, !alias.scope !16)> t0, GlobalAddress:i64<ptr @a> 0, undef:i64
              t114: i64,i32 = X86ISD::SUB t2, Constant:i64<5>
          t88: v4i32 = BUILD_VECTOR Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>
        t118: v4i32 = bitcast t36
          t36: v2i64 = BUILD_VECTOR Constant:i64<4294967290>, Constant:i64<4294967290>
      t121: v4i32 = vector_shuffle<1,0,3,2> t119, undef:v4i32
t123: v2i64 = bitcast t122
```

We end up with a `DemandedElts` of `0xa` when collecting `t118` which I'm fairly certain should be `0x5`. I'm still not sure where exactly this goes wrong, however...

**Comment by goldsteinn** [comment]
> I think the fundemental issue comes from the following snippet:
> 
> ```
> t77: i32 = X86ISD::MOVMSK t123
>   t123: v2i64 = bitcast t122
>     t122: v4i32 = and t119, t121
>       t119: v4i32 = X86ISD::PCMPEQ t90, t118
>         t90: v4i32 = vector_shuffle<0,5,2,7> t89, t88
>           t89: v4i32 = bitcast t117
>             t117: v2i64 = X86ISD::CMOV t93, t92, TargetConstant:i8<13>, t114:1
>               t93: v2i64 = BUILD_VECTOR t2, t2
>                 t2: i64,ch = CopyFromReg t0, Register:i64 %2
>                   t0: ch,glue = EntryToken
>               t92: v2i64 = BUILD_VECTOR t26, t26
>                 t26: i64,ch = load<(dereferenceable load (s64) from @a, !alias.scope !16)> t0, GlobalAddress:i64<ptr @a> 0, undef:i64
>               t114: i64,i32 = X86ISD::SUB t2, Constant:i64<5>
>           t88: v4i32 = BUILD_VECTOR Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>
>         t118: v4i32 = bitcast t36
>           t36: v2i64 = BUILD_VECTOR Constant:i64<4294967290>, Constant:i64<4294967290>
>       t121: v4i32 = vector_shuffle<1,0,3,2> t119, undef:v4i32
> t123: v2i64 = bitcast t122
> ```
> 
> We end up with a `DemandedElts` of `0xa` when collecting `t118` which I'm fairly certain should be `0x5`. I'm still not sure where exactly this goes wrong, however...

Edit: Nevermind, that works out correctly. AFAICT it all checks out on the `DemandedElts` front.

**Comment by RKSimon** [comment]
Could it be the CMOV? It might be assuming a scalar valuetype someplace.

**Comment by goldsteinn** [comment]
> Could it be the CMOV? It might be assuming a scalar valuetype someplace.

@RKSimon I think I found the issue. LMK What you think.

So in `computeKnownBits` for `BITCAST` when we do small-elements -> large-elements I think we don't lose information. For example:

```
t123: v2i64 = bitcast t122                          (DemandedElts = 0x3)
  t122: v4i32 = and t119, t121                    (DemandedElts = 0x5) <- !!! This is what I think leads to the bug !!!
    t119: v4i32 = <<Unknown Node #581>> t90, t118
      t90: v4i32 = vector_shuffle<0,5,2,7> t89, t88
        t89: v4i32 = bitcast t117
          t117: v2i64 = <<Unknown Node #467>> t93, t92, TargetConstant:i8<13>, t114:1
            t93: v2i64 = BUILD_VECTOR t2, t2
              t2: i64,ch = CopyFromReg t0, Register:i64 %2
                t0: ch,glue = EntryToken
            t92: v2i64 = BUILD_VECTOR t26, t26
              t26: i64,ch = load<(dereferenceable load (s64) from @a, !alias.scope <0x5646f622c458>)> t0, GlobalAddress:i64<ptr @a> 0, undef:i64
            t114: i64,i32 = <<Unknown Node #589>> t2, Constant:i64<5>
        t88: v4i32 = BUILD_VECTOR Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>
      t118: v4i32 = bitcast t36
        t36: v2i64 = BUILD_VECTOR Constant:i64<4294967290>, Constant:i64<4294967290>
    t121: v4i32 = vector_shuffle<1,0,3,2> t119, undef:v4i32
```
I'm pretty sure we just need to straight up make the `0xf`.

**Comment by RKSimon** [comment]
Is APInt scaleBitMask being used correctly? Sorry, I can't get to a laptop right now to check myself.

**Comment by goldsteinn** [comment]
> Is APInt scaleBitMask being used correctly? Sorry, I can't get to a laptop right now to check myself.

Its not being used. Its some weird code:

```
    // Bitcast 'small element' vector to 'large element' scalar/vector.
    if ((BitWidth % SubBitWidth) == 0) {
      assert(N0.getValueType().isVector() && "Expected bitcast from vector");

      // Collect known bits for the (larger) output by collecting the known
      // bits from each set of sub elements and shift these into place.
      // We need to separately call computeKnownBits for each set of
      // sub elements as the knownbits for each is likely to be different.
      unsigned SubScale = BitWidth / SubBitWidth;
      APInt SubDemandedElts(NumElts * SubScale, 0);
      for (unsigned i = 0; i != NumElts; ++i)
        if (DemandedElts[i])
          SubDemandedElts.setBit(i * SubScale);

      for (unsigned i = 0; i != SubScale; ++i) {
        Known2 = computeKnownBits(N0, SubDemandedElts.shl(i),
                         Depth + 1);
        unsigned Shifts = IsLE ? i : SubScale - 1 - i;
        Known.insertBits(Known2, SubBitWidth * Shifts);
      }
    }

```

That is both inefficient (multiple calls to `computeknownbits`) and I think incorrect in its assumption.

**Comment by goldsteinn** [comment]
> > Is APInt scaleBitMask being used correctly? Sorry, I can't get to a laptop right now to check myself.
> 
> Its not being used. Its some weird code:
> 
> ```
>     // Bitcast 'small element' vector to 'large element' scalar/vector.
>     if ((BitWidth % SubBitWidth) == 0) {
>       assert(N0.getValueType().isVector() && "Expected bitcast from vector");
> 
>       // Collect known bits for the (larger) output by collecting the known
>       // bits from each set of sub elements and shift these into place.
>       // We need to separately call computeKnownBits for each set of
>       // sub elements as the knownbits for each is likely to be different.
>       unsigned SubScale = BitWidth / SubBitWidth;
>       APInt SubDemandedElts(NumElts * SubScale, 0);
>       for (unsigned i = 0; i != NumElts; ++i)
>         if (DemandedElts[i])
>           SubDemandedElts.setBit(i * SubScale);
> 
>       for (unsigned i = 0; i != SubScale; ++i) {
>         Known2 = computeKnownBits(N0, SubDemandedElts.shl(i),
>                          Depth + 1);
>         unsigned Shifts = IsLE ? i : SubScale - 1 - i;
>         Known.insertBits(Known2, SubBitWidth * Shifts);
>       }
>     }
> ```
> 
> That is both inefficient (multiple calls to `computeknownbits`) and I think incorrect in its assumption.

Alas, yet again I am wrong. I (think) this should actually be okay.

**Comment by goldsteinn** [comment]
Okay, its a subtle bug, but the issue is:
```
  // MOVMSK(SHUFFLE(X,u)) -> MOVMSK(X) iff every element is referenced.
  SmallVector<int, 32> ShuffleMask;
  SmallVector<SDValue, 2> ShuffleInputs;
  if (NumElts <= CmpBits &&
      getTargetShuffleInputs(peekThroughBitcasts(Vec), ShuffleInputs,
                             ShuffleMask, DAG) &&
      ShuffleInputs.size() == 1 && !isAnyZeroOrUndef(ShuffleMask) &&
      ShuffleInputs[0].getValueSizeInBits() == VecVT.getSizeInBits()) {
    unsigned NumShuffleElts = ShuffleMask.size();
    APInt DemandedElts = APInt::getZero(NumShuffleElts);
    for (int M : ShuffleMask) {
      assert(0 <= M && M < (int)NumShuffleElts && "Bad unary shuffle index");
      DemandedElts.setBit(M);
    }
    if (DemandedElts.isAllOnes()) {
      SDLoc DL(EFLAGS);
      SDValue Result = DAG.getBitcast(VecVT, ShuffleInputs[0]);
      Result = DAG.getNode(X86ISD::MOVMSK, DL, MVT::i32, Result);
      Result =
          DAG.getZExtOrTrunc(Result, DL, EFLAGS.getOperand(0).getValueType());
      return DAG.getNode(X86ISD::CMP, DL, MVT::i32, Result,
                         EFLAGS.getOperand(1));
    }
  }
```

Which will determine that all the bits are demanded, whereas `simplifyDemandedBitsForTargetNode` is smart enough to realize only the upper bits are needed.

So the code above makes us remove the shuffle which leaves the known compares in the high bits which causes the support for computing knownbits to mess up the result.

Truthfully, i'd want to just remove the `peekThroughBitcast` logic here.

**Comment by goldsteinn** [comment]
Fix is up at: https://github.com/llvm/llvm-project/pull/68369

**Comment by goldsteinn** [comment]
Pushed: https://github.com/llvm/llvm-project/commit/1684c65bc997a8ce0ecf96a493784fe39def75de

**Comment by goldsteinn** [comment]
Do we need to backport this?

**Comment by goldsteinn** [comment]
(I assume this needs to be backported), note this also needs to be backported to 16 (I believe we also maintain prior release number).

**Comment by goldsteinn** [comment]
How do backports work now that we do GH? Do you know @RKSimon

**Comment by RKSimon** [comment]
If its regressed for multiple versions I'm not sure if we're still accepting cherry-picks, and that'd only be for 16.x of course. @tru @kbeyls ?

**Comment by tru** [comment]
We are not doing any more 16.x releases unless there are exceptional circumstances. cc @tstellar

**Comment by tru** [comment]
But we can definitely backport it for 17.x. The process for that is the same, set the milestone and issue the cherry-pick <sha> comment.

**Comment by goldsteinn** [comment]
/cherry-pick 65a576e27be814bd23f39b31a8074e9850b0fe26 1684c65bc997a8ce0ecf96a493784fe39def75de
