### ISSUE TITLE
Improve source-location information for DeclarationNames

### ISSUE THREAD

**Issue by DougGregor** [llvm/llvm-project#6729]
|  |  |
| --- | --- |
| Bugzilla Link | [6357](https://llvm.org/bz6357) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
We need a DeclarationNameLoc (or something like it) to store complete source-location information for non-identifier names, e.g., the locations of the '+' token in

  operator +

the precise type source information for

  operator const T *

and for

  ~Foo

etc. This is important for source fidelity, good diagnostics during instantiation, and to implement all of the nonsense in C++ [basic.lookup.classref] with looking into different scopes for the same name, then rectifying the results. The current FirstQualifierInScope hack doesn't capture all of the information we need in a form that works through template instantiation.

**Comment by philnik777** [comment]
I'm not sure I understand the request here. https://godbolt.org/z/Pns83n3eW suggests that the `+` has always been tracked. @AaronBallman do you know what is requested here?

**Comment by AaronBallman** [comment]
I believe the request is for code like:
```
struct S {
  S operator+(int);
};
```
We have a `DeclarationName` which tracks what kind of name `operator+` is and we can use `DeclarationNameLoc` to determine where the `+` is in the name: https://github.com/llvm/llvm-project/blob/87c5a3e203ae3643bc13c9a13917b92a657f4358/clang/include/clang/AST/DeclarationName.h#L678

I believe this can be closed as completed.
