### ISSUE TITLE
Add tests for scalable vectors in bufferize-invalid.mlir

### ISSUE THREAD

**Issue by banach-space** [llvm/llvm-project#67336]
PRs:
* https://github.com/llvm/llvm-project/pull/102361

Note, we agreed that this is sufficient to cover:
* bufferize-invalid.mlir
* one-shot-bufferize.mlir
* bufferize.mlir

**Comment by joker-eph** [comment]
There is no description here, can you file it?

**Comment by joker-eph** [comment]
This probably shouldn't be an issue actually.

**Comment by banach-space** [comment]
It's not an issue, it's a task from this board: https://github.com/orgs/llvm/projects/23/views/1. 

I was trying to find a way not to turn these into tasks, but no luck so far.

**Comment by joker-eph** [comment]
But this one is the only one that was converted to an issue, the others aren't.

**Comment by banach-space** [comment]
There's little point in creating additional 52 "empty" issues :)

Unless I figure out something better, I'll probably suggest that folks turn these into issues once they are ready to work on them.

Would you suggest something else instead?
