### ISSUE TITLE
[X86] Failure to commute PCMPGT(C, X) -> NOT(PCMPGT(X,C-1))

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#67347]
https://rust.godbolt.org/z/1c7b14rxj

It should be profitable to commute PCMPGT operands if the LHS is constant, permitting folding on the RHS and then flip the result if its feeding a SELECT/BLEND node which can then commute the select operands.

**Comment by goldsteinn** [comment]
Why is this profitable? Or in cases where `C-1` is cheap to materialize?

**Comment by RKSimon** [comment]
It will fold, saving a register (which is why I noticed it, trying to prevent spills).

**Comment by RKSimon** [comment]
You missed the last part of my description: " if its feeding a SELECT/BLEND node which can then commute the select operands."

I'm taking a look at this in the background, but I think just a missing fold from IsNOT.

**Comment by RKSimon** [comment]
OK, cleaning up the patch now

Alive2: https://alive2.llvm.org/ce/z/LxcPqm
