### ISSUE TITLE
cmake is garbage

### ISSUE THREAD

**Issue by AnonymousRonin** [llvm/llvm-project#67399]
every project I try building I get error after error with cmake saying it doesn't recognize the command in it's own CMakelists.txt file.  Can we move on from this horribly buggy program, it doesn't even install binaries where it's directed, clearly has no idea what a directory actually is and forces people to completely rewrite the cmakelist file in order to work.  LLVM can keep their shit, I'm done battling cmake.

**Comment by aemerson** [comment]
Have you tried turning it off and on again?
