### ISSUE TITLE
Clang frontend C++ crash with variadic templates in function args

### ISSUE THREAD

**Issue by brutalsavage** [llvm/llvm-project#67395]
To quickly reproduce: https://gcc.godbolt.org/z/E6ceGq5eP (assertion-trunk)

```cpp
#include <concepts>

template <typename... T>
void f1(bool B = (std::integral<T> ||...)) {
}
```

Compiling the above valid code crashes clang `clang++ -x c++ --std=c++20 `, crashes locally using clang-17.0 (a10019a), also on trunk with assertion (see godbolt link). Furthermore, GCC compiles the above code without any issue (see godbolt link)

**Comment by shafik** [comment]
Removed need for header: https://gcc.godbolt.org/z/oGnvae7KK

```cpp
template <typename T>
concept C = true;

template <typename... T>
void f1(bool B = (C<T> || ...)) {
}
```

**Comment by shafik** [comment]
When I dump the `CXXFoldExpr`, we have this:

```console
CXXFoldExpr 0x10f873d08 '<dependent type>'
|-<<<NULL>>>
|-ConceptSpecializationExpr 0x10f873ce0 '_Bool' Concept 0x10f873a78 'C'
| |-ImplicitConceptSpecializationDecl 0x10f873c28 
| | `-TemplateArgument type 'type-parameter-0-0'
| |   `-TemplateTypeParmType 0x10f873b20 'type-parameter-0-0' dependent contains_unexpanded_pack depth 0 index 0 pack
| `-TemplateArgument type 'T'
|   `-TemplateTypeParmType 0x10f873b50 'T' dependent contains_unexpanded_pack depth 0 index 0 pack
|     `-TemplateTypeParm 0x10f873ac8 'T'
`-<<<NULL>>>
```

but here:

https://github.com/llvm/llvm-project/blob/ebfea261e6a28e0ba33f437476202a25212b2d34/clang/lib/Sema/SemaDeclCXX.cpp#L86-L89

we iterate over the children as if they can not be `NULL` which from what it looks like looking at other visitors that is not a correct assumption.

**Comment by shafik** [comment]
Simplified to not required concepts:

```cpp
template <typename>
bool f();

template <typename... T>
void g(bool = (f<T>() || ...));
```
