### ISSUE TITLE
Using the MLIR python interface

### ISSUE THREAD

**Issue by HendrikKlug-synthara** [llvm/llvm-project#67414]
Hello I'm trying to get started with the MLIR Python bindings, following [this](https://mlir.llvm.org/docs/Bindings/Python/) tutorial, but I couldn't get past the venv setup since the path for the following command does not exists:

`export PYTHONPATH=$(cd build && pwd)/tools/mlir/python_packages/mlir_core`

running `python -c "from mlir import ir"` gives me this;
```shell
ImportError: cannot import name 'ir' from 'mlir' (~/.venv/mlirdev/lib/python3.11/site-packages/mlir/__init__.py)

```

`python -c "import mlir"` runs fine.

**Comment by joker-eph** [comment]
You should probably ask on Discourse, GitHub issues are used for bugs and features tracking.
