### ISSUE TITLE
[libc++] `std::begin()` overload for arrays is not `noexcept`

### ISSUE THREAD

**Issue by bregma** [llvm/llvm-project#67471]
According to ISO/IEC 14882:2020 23.7/4 [iterator.range] the overload of `std::begin()` for arrays should have the signature
```
template<class T, size_t N> constexpr T* begin(T (&array)[N]) noexcept;
```
but in libc++ it's
```
template <class _Tp, size_t _Np>
_LIBCPP_INLINE_VISIBILITY _LIBCPP_CONSTEXPR_SINCE_CXX14
_Tp*
begin(_Tp (&__array)[_Np])
{
    return __array;
}
```

**Comment by ldionne** [comment]
I've got a patch locally, I'm just waiting to ship #67496 before I upload it for review (stacked reviews in GH aren't great).
