### ISSUE TITLE
abi-compare workflow broken

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#67651]
The abi-compare workflow always fails with (e.g. https://github.com/llvm/llvm-project-release-prs/actions/runs/6335589443/job/17208905860?pr=712):
```
ERROR: can't access 'build-baseline/*.abi'
```

cc @tru @tstellar

**Comment by tstellar** [comment]
I think it needs the same fix that we did for the libclang abi check: 99fb0af80d16b0ff886f032441392219e1cac452
