### ISSUE TITLE
Release windows prebuilt binaries without installer

### ISSUE THREAD

**Issue by kammce** [llvm/llvm-project#67672]
Would the llvm project be able to release the windows prebuilt binaries outside of an installer .exe file? This is helpful for packaging it with other projects or in cases where a user does not want to make the executables available globally on a system. Please correct me if I'm wrong and there is a prebuilt version somewhere. All I can find is the `LLVM-<version>-win64.exe`

**Comment by DimitryAndric** [comment]
Note: you can install 7-Zip from https://www.7-zip.org/, and use that to extract the installer. (It is an LZMA compressed NSIS installer.)  Binaries are in `bin`, libraries in `lib`, etc.

**Comment by kammce** [comment]
Oh that's interesting. I'll give that a try with `xz` and see how it goes.

**Comment by kammce** [comment]
So the xz program didn't work, but the command line 7zip command did. Thank you @DimitryAndric, I'll consider this closed.
