### ISSUE TITLE
AMDGPU: support folding 64-bit immediates

### ISSUE THREAD

**Issue by jayfoad** [llvm/llvm-project#67781]
SIFoldOperands should support folding 64-bit immediates into literal operands.

Before GFX10 this was rarely a problem because most 64-bit instructions are VOP3 only and VOP3 did not allow a literal operand. One exception is V_FMAC_F64 on gfx90a+. Here's an example where we generate `v_fmac_f64_e32 v[0:1], s[4:5], v[2:3]` which could be folded to `v_fmac_f64_e32 v[0:1], 0x41200000, v[2:3]`: https://godbolt.org/z/EMTjfj6jb

On GFX10+ VOP3 can take a literal operand, so there are lots of 64-bit instructions that could be folded.

**Comment by rampitec** [comment]
I can see 3 parts of the problem:

1. We are only storing high 32 bits of an fp64 literal in the operand. If we continue that way it creates 3 sorts of problems: 1) every time we adding such immediate to an instruction we need to modify its value 2) in case if we ever unfold it from an instruction we need to convert it back, or its correct value will be lost 3) in case if we ever do any constant folding we need to do the same conversion. An obvious fix for that is to keep full fp64 value in an operand and instead adjust code emitter to handle it.
2. Folding itself, this shall be fairly trivial if we solve the next one.
3. We need something to fold, and this may be problematic. It should start with a move immediate selection, but we do not have 64-bit immediate moves with non-zero high 32 bits. We could use S_MOV_B64_IMM_PSEUDO/V_MOV_B64_PSEUDO instead, although it may pessimize resulting code if a literal is not folded. One solution could be to only select it this way if a value is used in an fp64 context later which may be tricky.

**Comment by rampitec** [comment]
1) is done: https://reviews.llvm.org/rGab6c3d50345f

**Comment by rampitec** [comment]
Maybe we need to bite the bullet and make REG_SEQUENCE foldable?

**Comment by jayfoad** [comment]
> 3 is still problematic. A universal selection is bad because we are missing on individual subreg optimizations (I have tried).

I was hoping that we could do the "universal selection" (i.e. always select B64 immediate moves) and then work through all the problems. But I have not actually tried it.

> Maybe we need to bite the bullet and make REG_SEQUENCE foldable?

What would that involve? You mean make SIFoldOperands fold it? What would it fold to?

**Comment by rampitec** [comment]
I have tried the universal selection. This looks really bad, I still have this branch somewhere around. For the REG_SEQUENCE, I thought to make it foldable in all places we do the folding: si-fold-operands, shrink, peephole, whatever else. A helper gathering a constant from a REG_SEQUENCE made of moves of constants. The worst thing with the universal selection is when we actually cannot fold it, we then ending with something we cannot encode. I see this can be fixed, but the result is less optimal than what we have now.

**Comment by rampitec** [comment]
There were several patches in between, but 3) is addressed by https://github.com/llvm/llvm-project/pull/70395
This would the final commit to implement this, not saying it can be further improved.

**Comment by rampitec** [comment]
In particular it could be improved for v2i32 and v2f32, but this is really extra. The code to do it is just ~20 lines though + test.

**Comment by jayfoad** [comment]
Thanks!
