### ISSUE TITLE
[GNU Extension] DragonEgg does not support __force_align_arg_pointer__

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#6779]
|  |  |
| --- | --- |
| Bugzilla Link | [6407](https://llvm.org/bz6407) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
This is an extension of llvm/llvm-project#5626 , only this bug deals with DragonEgg instead of clang.

Like LLVM-GCC, the standard GCC frontend fully recognizes the force_align_arg_pointer attribute. However, DragonEgg (to the best of my knowledge) does not handle this attribute.

The necessary backend support is there. It just needs to be hooked up.

**Comment by asl** [comment]
Dragonegg is obsolete
