### ISSUE TITLE
Confused about downloads

### ISSUE THREAD

**Issue by lavyadrian** [llvm/llvm-project#67832]
After trying for hours to get clang through packaging systems, I gave up because my system is running an NVIDIA card and their drivers are notoriously touchy about downgrading your version of gcc and its dev libraries on linux, which is aptitude's best solution to the problem. Now, I'm looking to download pre-built binaries from github but doesn't  know which one of clang 17 to get.
Please help if at all possible. Thank you.
edit: In the download page of clang 17, I don't know which one to get. My box is running linux on a 64 bit AMD CPU.

**Comment by Endilll** [comment]
You mentioned aptitude, so I can suggest you taking a look at apt.llvm.org

**Comment by lavyadrian** [comment]
> You mentioned aptitude, so I can suggest you taking a look at https://apt.llvm.org

Yeah been there done the inatll script and manually adding the repos, no luck :( . Its the version of gcc on my system it doesn't like.

**Comment by lavyadrian** [comment]
OK i used google and none of the download options seems to be for me except the source ones, which I am not willing to undertake. I guess clang is over for now.
