### ISSUE TITLE
Why llvm doesn't provide va_list definition?

### ISSUE THREAD

**Issue by mttbx** [llvm/llvm-project#67877]
I want to implement variable arguments function. I noticed that llvm didn't provide va_list type. And the definition of va_list is related to abi, arith and operating system. Why is that? And why llvm doesn't implement it?

**Comment by DimitryAndric** [comment]
These are defined in clang, see https://github.com/llvm/llvm-project/blob/main/clang/lib/Headers/stdarg.h . Obviously you could argue that these might belong in the llvm subdirectory, but they have always been where they are now :)

**Comment by mttbx** [comment]
I've noticed that. I just don't want to depend on clang. I think to make the function complete, it may be better to put these code in llvm.
