### ISSUE TITLE
[InstCombine] `!a == (a < 0)` is not optimized

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#67916]
Consider the following functions:
```cpp
int foo(int a)
{
   return !a == (a > 0);
}

int bar(int a)
{
   return (a < 0);
}

int baz(int a)
{
   return !a == (a < 0);
}

int qux(int a)
{
   return (a > 0);
}
```

Both Clang and GCC can optimize `foo` to `bar`. GCC can also optimize `baz` to `qux`, but Clang cannot.
https://godbolt.org/z/exvTE8Gn7
https://alive2.llvm.org/ce/z/LGvASc

**Comment by XChy** [comment]
The fold `zext(icmp (A, xxx)) == shr(A, BW - 1)` => `trunc(not(xor(zext(icmp), shl)))` would be a more convenient way to optimize it.
[alive-tv](https://alive2.llvm.org/ce/z/t7UXuG)
