### ISSUE TITLE
Out of Line Definition Error for Constrained Function of Template Class

### ISSUE THREAD

**Issue by matekelemen** [llvm/llvm-project#67926]
Very similar to #62003, except the constraint has an extra template parameter, which is passed from the class' member type.

FYI @alexander-shaposhnikov. [Example on godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:16,positionColumn:1,positionLineNumber:16,selectionStartColumn:1,selectionStartLineNumber:16,startColumn:1,startLineNumber:16),source:'%0A%0Atemplate+%3Ctypename+A,+typename+T%3E%0Aconcept+constraint+%3D+true%3B%0A++++%0Atemplate+%3Ctypename+T%3E%0Astruct+Foo+%7B%0A++++struct+Bar+%7B%7D%3B%0A++++template+%3Cconstraint%3CBar%3E+U%3E%0A++++++++void+baz+(U+baz)%3B%0A%7D%3B%0A++++%0Atemplate+%3Ctypename+T%3E%0Atemplate+%3Cconstraint%3Ctypename+Foo%3CT%3E::Bar%3E+U%3E%0Avoid+Foo%3CT%3E::baz+(U+baz)+%7B%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:52.47813411078717,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:clang_trunk,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-std%3Dc%2B%2B20',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+clang+(trunk)+(Editor+%231)',t:'0')),header:(),k:44.584286803966435,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gcc+12.2',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+clang+(trunk)+(Compiler+%231)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:47.52186588921283,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).

```cpp
template <typename A, typename T>
concept constraint = true;
    
template <typename T>
struct Foo {
    struct Bar {};
    template <constraint<Bar> U>
        void baz (U baz);
};
    
template <typename T>
template <constraint<typename Foo<T>::Bar> U>
void Foo<T>::baz (U baz) {}
```
```
error: out-of-line definition of 'baz' does not match any declaration in 'Foo<T>'
   15 | void Foo<T>::baz (U baz) {}
      |              ^~~
```

**Comment by matekelemen** [comment]
By the way, it doesn't even have to be a member type, the instantiated class `Foo` fails too:
```cpp
template <typename A, typename T>
concept constraint = true;
    
template <typename T>
struct Foo {
    struct Bar {};
    template <constraint<Foo> U>
        void baz (U baz);
};
    
template <typename T>
template <constraint<Foo<T>> U>
void Foo<T>::baz (U baz) {}
```

Type aliases are rejected as well:
```cpp
template <typename A, typename T>
concept constraint = true;
    
template <typename T>
struct Foo {
    using Bar = int;
    template <constraint<Bar> U>
        void baz (U baz);
};
    
template <typename T>
template <constraint<typename Foo<T>::Bar> U>
void Foo<T>::baz (U baz) {}
```

However, if the type is explicitly provided in the out-of-line constraint, it's accepted:
```cpp
template <typename A, typename T>
concept constraint = true;
    
template <typename T>
struct Foo {
    using Bar = int;
    template <constraint<Bar> U>
        void baz (U baz);
};
    
template <typename T>
template <constraint<int> U> // <== this works
void Foo<T>::baz (U baz) {}
```

**Comment by shafik** [comment]
It does indeed look similar CC @erichkeane

**Comment by erichkeane** [comment]
I think this ends up being one I did a bit of triage on last week that I don't seem to be able to find.

**Comment by BenBrock** [comment]
At first glance this seems to be the same issue I've run into with Clang having difficulty compiling parts of libstdc++'s ranges implementation ([example](https://godbolt.org/z/58xevYWhz)).

**Comment by matekelemen** [comment]
> At first glance this seems to be the same issue I've run into with Clang having difficulty compiling parts of libstdc++'s ranges implementation ([example](https://godbolt.org/z/58xevYWhz)).

@BenBrock I think that's a different issue. [Here](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxBIAHKQADqgKhE4MHt6%2BekkpjgJBIeEsUTFc8XaYDmlCBEzEBBk%2Bfly2mPZ5DDV1BAVhkdFxtrX1jVktCsM9wX3FA2UAlLaoXsTI7BwEmCwJBpsA1CYAzG4EAJ4JjKyYewAqR9gmGgCCaAxrCQR7rxPETNPoB0OABE9gRiF5MEcrM9Hk9Nttdtcjidzpc2HsAHRYm4Ke6w17vT4MAQAL2iqEBII0gLcexSZNQVCxGIgOPmUNhnLMhywNBCewAYgAlACS2FCQIA%2BjdsABZZQBJ4yyUACWwTxB8J2TH2yLOF2Y6OZOPue2ImAAjl48OaFHsINTkXS8AymVjWQp5uyYc8tYiafq0dc7ocHs8fl4HILUKhOQB2aFPPbJwWi8VSmXyxXKtUa2EpvZUYh4VxfAwKO0WOocmFxoE1p6w4ViiXSuUKpXYVXq%2BvPZDlyt1A4Jkx1huw4KfFh/BgQb2NkfPAsCmPIyem3GHCzJgD0O5pR3rwL2ITWFbqp1BFOAjGiOuuBAQ1yLJYYAKw/bqOrS%2BZTVeIa6CBum6JqOvZPBwiy0JwACsvB%2BBwWikKgnBuNY1h0ssqxItyPCkAQmiQYsADWIAwRo%2BicJI8GEchnC8AoIAUQRiGQaQcCwDAiAoKg2x0NE5CUGgfH0DEwBcIcZikFgABueBrAAaiWADuADyBqcHhNC0JsxCMRAES0REwQXppvDGcwxCnKpETaJULF4cJbCCKpDC0KctFYBEXjAG4Yi0Ix3C8Fg05GOIrHSTa9l4DJmCBUhmCqJUXibGZ5CCG0tG0HgES/FZHhYLRYJ4CwZmLFQBjAAoSmYGpGlBTIggiGI7BSI18hKGotG6FJBhGCg6GWPoOWMZAiyoB8aSBQAtBM6CHqYljWNyvCoLFxDFlgo1zq07RpC4b6jM0pCBNMRQlNkySpAIR2XbkaS9Odcy7dFAhdCMnhNHoFRVG9kyPf0pRDN0t3jP9Z2AxIiwKFhaxQ5RHBwaQCFIShHB7KosQAGzTVjkh7MAyDIHsEkYmY9q4IQJAHLh8y8CxWheqQpHkQj1GkKVhyHBiXO83z/NY8jtFowxTH4YRiwcdxwkJPxZAUBAMtyygfXAJKYJeAwxHSZgcmKSp6mMGl2m6fphkRRZpkNZbVk2XZDhpU5jAEK57meZg3m%2Bf5gV4SFhjAOFSH4OaVSxfFvCJclqUNZOmURdluUXgV6xIcVpVBeVlXVQb9VabIzXiG1/CCIoKjqBFugtKrA1LUNCfbeNk0CDNc0LYNFgrch62bXF8DQ20r1%2BBArigydb4A7MQM5Nd6SfWMiRXR0E8XeMA%2B/Z0kyjz9HTvVMhSQ2DINz8dEzdMvczQ7DrVQbBNERWjGPY7j%2BOfkY9oa1r8wU/gRDEDThxcDpuLViTMnxMCwDEHa0EODs05tzfmCDeaCxRqteitgxYMzYlLCASBlgEASClQSiteKy1EqEK4nBMY4zxmWf279wSfwjj/EgeB0B6GLsIUQhdpAcNLl1CuehlK/ASGVBGSMUF0Q4KpFKBDPiMkftQl%2Bqt6Ga2Il/CAHgRLRH/oA%2BmEsb4wN4HAnmiCEFC3vmgxizF9HMzIhRaBhw76ozQZgpm0CzBONQRwPRIDFjrRSM4SQQA)'s the smallest repro I could come up with:
```cpp
template <typename T>
concept constrained = true;

template <typename ...Ts>
concept nonzero = 0 < sizeof...(Ts);

#define FRIEND_TEMPLATE_HEAD template <typename ...Ts> requires (0 < sizeof...(Ts))

template <typename T>
struct Foo
{
    FRIEND_TEMPLATE_HEAD
    friend class Bar;
};

FRIEND_TEMPLATE_HEAD
class Bar {};

int main()
{
    Foo<int> s;  // <== necessary to generate the friend declaration
    Bar<int> ss;
}
```

Clang happily accepts it if the constraint on `FRIEND_TEMPLATE_HEAD` is changed from `requires (0 < sizeof...(Ts))` to `requires nonzero<Ts...>`, which is logically identical. [Modified example](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIM6SuADJ4DJgAcj4ARpjEElykAA6oCoRODB7evv5JKWkCIWGRLDFxXAl2mA7pQgRMxASZPn4BldUCtfUEhRHRsfG2dQ1N2a1D3aG9Jf3lAJS2qF7EyOwcBJgsiQbrANQmAMxuBACeiYysmDsAKgfYJhoAgmgMK4kEO88KBMRMk%2Bh7%2BwAIjtvl5MAcrI97g91pttpcDkdTuc2DsAHQYq4KW7Q56vd4MAQAL1iqABwI0ALcO1SJNQVAxaIgWNmEOh7LM%2BywNDCOwAYgAlACS2HCgIA%2BldsABZZRBB5S8UACWwD2BsK2TF2iJOZ2YqMZWNuO2ImAAjl48KaFDtCQwScRUIisYycVDHhr4VTdSjLjd9ndHl9iF4HPzUE6oQB2SEPHbx/nC0USqWy%2BWKlVq6EJnZUYh4VwfAwKG0Weps6OAisPaGCkViyUyuUK7DK1VVx7IYul%2Bp7GMmKNV/ax6Ghd4sX4MCCs6OxnN8iOIsfG7HD%2BMAenXVIOQ%2BBYRWJfqxxBZOAjFiWsuBAQlzzBYY/ywXfqWvS2YTZeIS8EK9XI8H0IcPMtCcAArLwfgcFopCoJwbjWNYNKLMsCKcjwpAEJoQHzAA1iAoEaPonCSBBWEwZwvAKCAhGYVBQGkHAsAwIgKCoJsdCxOQlBoOx9BxMAXD7AEWAAG54CsABqBYAO4APJ6pw6E0LQ6zEFREBRGRUShEeim8NpzDEMcslRNoVS0ehPFsIIskMLQxxkVgUReMAbhiLQVHcLwWATkY4h0aQ%2BCmtUImYJ50GYKoVReOsenkIImAgQFtB4FEPxGR4WBkd8eAsHp8xUAYwAKFJmByQpXkyIIIhiOwUhVfIShqGRugBAYRgoAhlj6KlVGQPMqBvOknkALRfOgO6mJY1icrwqChcQ%2BZYH1062Il5npC4D4jH4CTBJMxSlHoySpI4Ag7cdeRnQwPSHTMa32NdnTDJ4zR6G0T3jLdfRlIMXQXRUX0HT9EjzAoyErKDREcOBpCQdBsEcDsqgABwAGwjWjkg7MAyDIDsglomYOwQLghAkHsaGzLwtFaLMuH4YRSUkaQeX7PsaLs1z3M82jcNkYjlHURhWHzIxLE8YkHFkBQECS9LKDtcA4qggwOGBZgYmSTJ8mMHFymqepmkBQZumVabRkmWZDhxVZjAELZ9mOZgzmue5nnoT5hjAP50FBRtoXhbwkXRbFlVjolZEpWlR6Zas0E5XlXkFUVJU6xVSmyDV4j1fwgiKCo6gBboCRK5103ddHK0DUNAijeNk1dRYs0wQtS1hfAYPre0fgQK4AOBA%2B33TL9J35Bkr3ZAkY/XcPR0VN3n3/ZPu0PRtHRA0UIOA8vWSr18XRzzMYMQ3VwFgaRAWI8j6OY9jz5GCTqs4bMJNk0QxCU/sXDUyLdH06QG8TAsBxFWszXgbMOY82gVzPm8M5oUVsMLWm9FxYQCQIsAgiQYpcTlmxKWfFwgXE4KjDGWMizeyfiGNWv9MD4A/ngdAeg87CFEDnaQLCC7NWLnoaSPxEj5WhrDeB5EOCyRitg949Ib5kPvkrKhXgaEkw8LxWIX8f401FufDgLNIGcxgdA/mV9EFURolo0geECLQ32JfBGiCUEAKSmYWxCCOCaP/vMBaqRnCSCAA%3D):
```cpp
template <typename T>
concept constrained = true;

template <typename ...Ts>
concept nonzero = 0 < sizeof...(Ts);

#define FRIEND_TEMPLATE_HEAD template <typename ...Ts> requires nonzero<Ts...>

template <typename T>
struct Foo
{
    FRIEND_TEMPLATE_HEAD
    friend class Bar;
};

FRIEND_TEMPLATE_HEAD
class Bar {};

int main()
{
    Foo<int> s;  // <== necessary to generate the friend declaration
    Bar<int> ss;
}
```

**Comment by BenBrock** [comment]
Ah, thanks for minimizing! I will create a separate issue.

**Comment by BenBrock** [comment]
Actually, I believe this is the same issue as #61763, so I added a comment there.

**Comment by erichkeane** [comment]
#56482 I think is pretty related too... we have a couple of these now that are all really similar.
