### ISSUE TITLE
Dollar sign ('$') can not be encoded as a UCN inside an identifier

### ISSUE THREAD

**Issue by mattmanj17** [llvm/llvm-project#67943]
Dollar signs are supported in identifiers as an extension,  
but dollar signs encoded with a UCN do not work in identifiers.  

For example, the file...  
`gcc/testsuite/gcc.dg/ucnid-5.c`  
...from the gcc test suite, does not compile.

Here is the contents of that file:

```
/* { dg-do run } */
/* { dg-skip-if "No dollar in identifiers" { avr-*-* powerpc-ibm-aix* } } */
/* { dg-options "-std=c99 -fdollars-in-identifiers -g" } */
void abort (void);

int a$b(void) { return 1; }

int main (void)
{
  
  if (a\u0024b() != 1)
    abort ();
  
  return 0;
}
```

Godbolt link of it not compiling in clang 17.0.1  
https://godbolt.org/z/TGdd9PoYx

Godbolt links for it compiling in gcc (and a previous clang version)  
GCC 13.2 https://godbolt.org/z/TGdd9PoYx  
clang 16 https://godbolt.org/z/xWfvKqvxz

Neither the C or C++ standards forbid using a UCN to encode '$'.  
As far as I can tell they just forbid control chars, surrogates,   
and chars in the 'basic character set', which does not include '$'.

**Comment by shafik** [comment]
CC @cor3ntin @AaronBallman @tahonermann

**Comment by cor3ntin** [comment]
Both C and C++ added `$` to the basic character set, and with that we removed the ability to form `$` with an UCN
https://reviews.llvm.org/D153621
http://eel.is/c++draft/tab:lex.charset.basic

**Comment by mattmanj17** [comment]
@cor3ntin ah, the standard has been updated. Thank you for the clarification. Honestly, I think it is better for those chars to be in the basic char set, so I am glad this was changed. Sorry for the noise.

**Comment by cor3ntin** [comment]
@mattmanj17 Thanks for the question!
