### ISSUE TITLE
 [C++17][clang:Frontend] Clang can't deduce the correct deduction guide.

### ISSUE THREAD

**Issue by HoBoIs** [llvm/llvm-project#67959]
If there are two auto generated deduction guides from a templated and a non templated constructor we should choose the guide generated from the non-templated constructor. But clang can't deduce which one should we use. (gcc can)

https://godbolt.org/z/ee3e9qG78

**Comment by shafik** [comment]
It is helpful to include reasonably sized code snippets so readers can understand the issue report in once place:

```cpp
template<class T>
struct A
{
    A(T, T, int);  //#1
 
    template<class U>
    A(int, T, U);  //#2
};                 
 
A x(1, 2, 3); // Should choose #1

```

This looks like overload resolution to me from [over.match.best.general p2.13](http://eel.is/c++draft/over.match.best.general#2.13).

**Comment by HoBoIs** [comment]
You have to deduce the template parameter of A (to int) from the deduction guides generated from the constructors. The rule http://eel.is/c++draft/over.match.best.general#2.13 Says that the we have to use guide generated from the first constructor, but calng claims the deduction is ambigous.
