### ISSUE TITLE
Crash when compiling tensorflow using Clang-16

### ISSUE THREAD

**Issue by JohnRTitor** [llvm/llvm-project#67967]
I was trying to build Tensorflow as per the guide on [their website](https://www.tensorflow.org/install/source).
Everything went all until I ran `bazel build --config=opt -k //tensorflow/tools/pip_package:build_pip_package`.
I used the following compiler optimisation flags
```
-msse4.1 -msse4.2 -mavx -mavx2 -mavx512f -mavx512vnni -mavx512bf16 -mfma -msse3
```
[Bazel Crash Log.txt](https://github.com/llvm/llvm-project/files/12782030/Bazel.Crash.Log.txt)

TensorFlow version: r2.14

**Comment by JohnRTitor** [comment]
[conv_ops_half-34c71c.sh.txt](https://github.com/llvm/llvm-project/files/12782087/conv_ops_half-34c71c.sh.txt)
The required file is posted as txt since github does not allow .sh attachments.

**Comment by RKSimon** [comment]
Using individual AVX512 ISA features is always going to be tricky - please can you try adding -mavx512vl -mavx512bw? 

Alternatively try "-march=x86-64-v4 -mavx512vnni -mavx512bf16" - to start with an avx512 base definition, and enable vnni/bf16 on top of it

**Comment by JohnRTitor** [comment]
> [conv_ops_half-34c71c.sh.txt](https://github.com/llvm/llvm-project/files/12782087/conv_ops_half-34c71c.sh.txt) The required file is posted as txt since github does not allow .sh attachments.

https://mega.nz/file/GmBmBCgY#9wrlu5AVgxXy12UXMto8h1jlBOzh-FnYQT_yGuaxGIo

if anyone wants to take a look at the source file. Turns out its too big for GitHub :P

**Comment by JohnRTitor** [comment]
Successfully compiled using `-march=native -mavx512vnni -mavx512bf16`.

Running `python3 -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"`

Outputs:-
```
2023-10-02 20:35:00.817437: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
tf.Tensor(-579.91486, shape=(), dtype=float32)
```

It does not beg to enable msee, mavx, ... CPU instructions anymore. Looks like they are enabled automatically with marc=native.
