### ISSUE TITLE
The behavior of `__builtin_assume`

### ISSUE THREAD

**Issue by YangChenyuan** [llvm/llvm-project#67970]
Hi, I am not sure about the behavior of `__builtin_assume`.

I have this file with a wrong `__builtin_assume` that `A != 10` (actually `A` is 10)
```cpp
#include <iostream>

int main(){
    int A = 10;
    int B = 0;

    int C = A + B;
    std::cout << C << std::endl;
    __builtin_assume(A != 10);
    return C;
}
```

When I compile this file with ` clang++ -O3 file.cpp -o exx` and execute `exx`, its output will be 

```
10
10
[1]  segmentation fault  ./exx
```

I am curious whether such behavior is expected and why there are two `10` are printed.

Thanks in advance

**Comment by dtcxzyw** [comment]
Godbolt: https://godbolt.org/z/6xGYW1PvT
`A != 10` evaluates to `false`, and the following code will be considered unreachable. The behavior after `__builtin_assume(A != 10)` is undefined.
