### ISSUE TITLE
Clang CI running for MLIR-only changes

### ISSUE THREAD

**Issue by ftynse** [llvm/llvm-project#67989]
I’ve noticed that Clang CI was triggered by my two recent changes that only touch files under mlir/.

[[mlir] run buffer deallocation in transform tutorial by ftynse · Pull Request #67978 · llvm/llvm-project · GitHub](https://github.com/llvm/llvm-project/pull/67978) ([Github pull requests #5258](https://buildkite.com/llvm-project/github-pull-requests/builds/5258)),
[[mlir] reword error message on unloaded dialect by ftynse · Pull Request #67980 · llvm/llvm-project · GitHub](https://github.com/llvm/llvm-project/pull/67980) ( https://buildkite.com/llvm-project/github-pull-requests/builds/5260 ).
This doesn’t look desirable for either clang or mlir.

**Comment by joker-eph** [comment]
@metaflow : can you describe the flow? I tried to figure but couldn't...

**Comment by joker-eph** [comment]
Actually found this which like have solved it: https://github.com/llvm/llvm-project/commit/ec9d80ec43f5761a34c4a785c67d9e7d21ec8bda
