### ISSUE TITLE
Did llvm support ARM based platform analysis? Where could I download the compiler supporting ARM?

### ISSUE THREAD

**Issue by boofish** [llvm/llvm-project#68]
Hi, I want to do some analysis based on ARM architecture, but I do not find the tools used to generated ARM platform IR, could anyone give me help? Thanks.

**Comment by TNorthover** [comment]
You have to go out of your way to produce a version of LLVM that won't compile for ARM.

On Linux you should just be able to run "clang -target armv7-linux-gnueabihf -emit-llvm -S -o - file.c" to produce the ARM IR. It'll be using the x86 headers though, which you might want to fix by installing an ARM sysroot eventually.

On macOS, you could run "clang -arch armv7k -emit-llvm -S -o - file.c" instead. That will already be using appropriate headers (for the watch).

**Comment by WaterDemo** [comment]
Wow,  that is what I want, thank you :)

**Comment by boofish** [comment]
Wow, that is what I want, Thank you!
