### ISSUE TITLE
[HLSL] Document HLSL resource IR representation and lowering

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#68006]
We need a documented plan for how we're handling resource lowering from HLSL to DXIL. This should include details about how we represent HLSL resources in clang, how they appear in LLVM IR, and how we lower those to metadata and operations in DXIL.

My approach to this plan is to leverage TargetExtType in LLVM in order to simplify the ad-hoc metadata based approach we have so far.

This will replace the stubbed out docs at https://clang.llvm.org/docs/HLSL/HLSLIRReference.html that mention `@uavs` metadata but don't have any detail about what information is captured there, and don't mention the other resource types at all.

### Acceptance Criteria

- clang's [HLSLIRReference](https://clang.llvm.org/docs/HLSL/HLSLIRReference.html) should be updated to reflect the TargetExtType approach
- clang's [ResourceTypes](https://clang.llvm.org/docs/HLSL/ResourceTypes.html) should discuss how resources are lowered.
- A new [DXILResources](https://llvm.org/docs/DirectX/DXILResources.html) document should describe how resources work in LLVM IR
- This document should describe **all** resource types
- designs should consider SPIR-V where possible

**Comment by bogner** [comment]
#90553 covers the basics and buffer types in particular, but we need to keep this open for other resource types (cbuffer, sampler, textures) and for fleshing out the set of operations.

**Comment by damyanp** [comment]
(HLSL priority set to low since the basics are here, but this issue covers everything else)

**Comment by bogner** [comment]
I'm not sure this issue has much value on its own at this point. As we implement the other resource types we should just consider documenting as we go part of the work.
