### ISSUE TITLE
i1 arguments do not work with amdgpu_cs

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#68087]
```
; RUN: llc -march=amdgcn -mcpu=gfx900 < %s
define amdgpu_cs void @main(i1 %i83) {
bb:
  ret void
}

```

LLVM ERROR: unable to allocate function argument #0

**Comment by nhaehnle** [comment]
The prize question is of course going to be: assuming we haven't run out of registers, should those be lowered as 32-bit VGPR or as wavesize SGPR bitmask. I think the latter would be better.

**Comment by nickleus27** [comment]
I am interested in working on this. Please assign to me.

**Comment by nickleus27** [comment]
Do we want to promote i1 to MVT i16 for the arg type?

**Comment by arsenm** [comment]
> Do we want to promote i1 to MVT i16 for the arg type?

Promote to i32 (not really a difference there, there aren't really 16-bit registers)
