### ISSUE TITLE
[lldb][Expression] Printing union with self-referencing member field crashes lldb

### ISSUE THREAD

**Issue by Michael137** [llvm/llvm-project#68135]
```
//struct Attrs // << this works                 
union Attrs // << this crashes                  
{                                                                  
    static const Attrs regular;                 
};                                                                 
                                                                   
const Attrs Attrs::regular{};
                                                                   
int main() {                                                       
    Attrs d;                                    
    return 0;                                                      
}                                                                  
```

```
clang++ main.cpp -g -O0 -std=c++2a
./bin/lldb a.out -o "br se -p return -X main" -o run -o "frame var d"
```
(on llvm.org lldb build at commit `0bfaed8c612705cfa8c5382d26d8089a0a26386b`)

This will infinitely recurse in `ASTContext::getASTRecordLayout`. Possibly the same crash as:
* https://github.com/llvm/llvm-project/issues/43604
* https://github.com/llvm/llvm-project/issues/63667
* https://github.com/llvm/llvm-project/issues/64628
* https://github.com/llvm/llvm-project/issues/66335

**Comment by Michael137** [comment]
Oh looks like for unions we're mistakenly adding an `unnamed` padding `FieldDecl` in `DWARFASTParserClang::ParseSingleMember`. This confuse the `RecordLayoutBuilder` because the `Attrs` type now claims to have a `FieldDecl` when it actually doesn't; `regular` should be a `VarDecl` (at least that's what it is when dumping the actual clang AST of this file).

**Comment by Michael137** [comment]
```
// Handle static members, which is any member that doesn't have a bit or a  
// byte member offset.                                                      
if (attrs.member_byte_offset == UINT32_MAX &&                               
    attrs.data_bit_offset == UINT64_MAX) {                                  
  Type *var_type = die.ResolveTypeUID(die: attrs.encoding_form.Reference());
```

This is what we do for structures that have static members. But this doesn't happen for unions.

Because of this:
```
MemberAttributes::MemberAttributes(const DWARFDIE &die,                         
                                   const DWARFDIE &parent_die,                  
                                   ModuleSP module_sp) {                        
  member_byte_offset = (parent_die.Tag() == DW_TAG_union_type) ? 0 : UINT32_MAX;
```

**Comment by Michael137** [comment]
That logic was added in: https://github.com/llvm/llvm-project/commit/aaae5f87af8945cdeac81e86429a303954473a88

```
[DWARFASTParserClang] Start with member offset of 0 for members of union types.

Summary:
GCC does not emit DW_AT_data_member_location for members of a union.
Starting with a 0 value for member locations helps is reading union types
in such cases.
```

**Comment by Michael137** [comment]
We could naively change that condition to determine static data members to:
```
if ((attrs.member_byte_offset == UINT32_MAX || (attrs.member_byte_offset == 0 && tag == DW_TAG_union))
     &&                               
    attrs.data_bit_offset == UINT64_MAX) {        
```

but maybe further reading of the DWARF standard could help simplify some of this

**Comment by Michael137** [comment]
So it looks like the change in https://github.com/llvm/llvm-project/commit/aaae5f87af8945cdeac81e86429a303954473a88 directly conflicts with the change in https://github.com/llvm/llvm-project/issues/55040.

The latter makes it so we always check the presence of `member_byte_offset` to determine whether we have a static data member. Whereas the latter unconditionally adds a non-sentinel default `member_byte_offset` to all union data members.

The effect of this is that we will never be able to detect that a union has static data members correctly.

From both commit descriptions it sounds like both changes were done to support GCC (it neither emits `DW_AT_external` for static data members nor does it apparently "emit DW_AT_data_member_location for members of a union").

To not break either of these I'm inclined to only set a default `DW_AT_data_member_location` for union members that are not marked `DW_AT_external`. I think that would fix clang behaviour while preserving GCC behaviour (albeit wrong).

Something like:
```
diff --git a/lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp b/lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp
index aa45076bf2f7..bb78756d36e2 100644
--- a/lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp
+++ b/lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp
@@ -6,6 +6,7 @@
 //
 //===----------------------------------------------------------------------===//
 
+#include <climits>
 #include <cstdlib>
 
 #include "DWARFASTParser.h"
@@ -2494,7 +2495,7 @@ struct MemberAttributes {
   DWARFFormValue encoding_form;
   /// Indicates the byte offset of the word from the base address of the
   /// structure.
-  uint32_t member_byte_offset;
+  uint32_t member_byte_offset = UINT32_MAX;
   bool is_artificial = false;
 };
 
@@ -2668,8 +2669,7 @@ DiscriminantValue &VariantPart::discriminant() { return this->_discriminant; }
 MemberAttributes::MemberAttributes(const DWARFDIE &die,
                                    const DWARFDIE &parent_die,
                                    ModuleSP module_sp) {
-  member_byte_offset = (parent_die.Tag() == DW_TAG_union_type) ? 0 : UINT32_MAX;
-
+  bool is_external = false;
   DWARFAttributes attributes = die.GetAttributes();
   for (size_t i = 0; i < attributes.Size(); ++i) {
     const dw_attr_t attr = attributes.AttributeAtIndex(i);
@@ -2697,6 +2697,9 @@ MemberAttributes::MemberAttributes(const DWARFDIE &die,
       case DW_AT_data_bit_offset:
         data_bit_offset = form_value.Unsigned();
         break;
+      case DW_AT_declaration:
+        is_external = form_value.Boolean();
+        break;
       case DW_AT_data_member_location:
         if (form_value.BlockData()) {
           Value initialValue(0);
@@ -2735,6 +2738,15 @@ MemberAttributes::MemberAttributes(const DWARFDIE &die,
     }
   }
 
+  // GCC doesn't emit a DW_AT_data_member_location for members
+  // of a union, so default initialize it here. However, don't
+  // set it for static-data members (i.e., a non-defining declarations).
+  if (member_byte_offset == UINT32_MAX
+      && parent_die.Tag() == DW_TAG_union_type
+      && !is_external) {
+    member_byte_offset = 0;
+  }
+
```

Although I still don't like this because we are using two different heuristics to determine existence of non-static data members.

@clayborg @jingham Any preference on what to do here? Looks like GCC still isn't attaching `DW_AT_data_member_location` to non-static union members (whereas clang does).

CC @dwblaikie @adrian-prantl because DWARF

**Comment by Michael137** [comment]
As an aside, do we need to emit the `DW_AT_data_member_location` for unions in clang at all? If they are all going to be 0 anyway?

**Comment by Michael137** [comment]
Should clang be emitting static data members as `DW_TAG_variable` instead of `DW_TAG_member`? Some parts of the DWARF spec seem to suggest so:
```
If the variable entry represents the defining declaration for a C++ static data member of a structure, class or union, the entry has a DW_AT_specification attribute, whose value is a reference to the debugging information entry representing the declaration of this data member. The referenced entry also has the tag DW_TAG_variable and will be a child of some class, structure or union type entry.
```
(from DWARFv5 Chapter 4.1)

That would make it much easier to differentiate static vs non-static members

**Comment by Michael137** [comment]
So to summarise:
1. Can we avoid default initialising `member_byte_offset` for union members?
2. We should make clang emit `DW_TAG_variable` for static data members in DWARFv5 and make LLDB understand this

**Comment by adrian-prantl** [comment]
> Should clang emit DW_TAG_variable for static data members in DWARFv5 and make LLDB understand this?

If the spec says so, I think that's an easy yes. You might need to make the behavior adjustable for some debugger tunings (though I'd argue the default should emit standards-conformant DWARF).

**Comment by adrian-prantl** [comment]
@CC @dwblaikie

**Comment by dwblaikie** [comment]
Summary is, if I'm reading this right:

* LLDB used to detect static members by the presence of `DW_AT_external`, but that's not correct/portable, you could have non-external static members if they were members of a non-linkage class, such as a class in an anonymous namespace
* LLDB then started using the presence of `DW_AT_data_member_offset` to differentiate static and non-static member variables
* LLDB also started assuming members of a union have a `DW_AT_data_member_offset` of zero, because GCC emits union non-static members without a `DW_AT_data_member_offset` (since they'd all be zero anyway) - unclear if that's to-spec or not? *shrug*
* That broke static-member detection inside unions because all the members got an implicit `DW_AT_data_member_offset`

So we're discussing changing teh way clang emits static members to use `DW_TAG_variable` instead of `DW_TAG_member` to make it less ambiguous/solve the above issues "once and for all" *fingers crossed*

And you've tagged me as a heads up that we might be/are going to go in this direction/check I'm cool with it - yeah, sounds good to me. Doing things more clearly, and if that happens to be "more like GCC" I'm generally for it - they're still the bigger fish in the DWARF sea, and it's usually a safe direction to head unless there's extenuating circumstances.

At least our internal use ships pretty close to LLDB, so we don't have a particular need for some clang mode that's deeply backwards compatible (the inverse is somewhat true - be good if LLDB didn't just totally give up on doing some of the old heuristics - still able to debug old binaries as best it can, which seems like it wouldn't be too expensive/problematic to maintain for a while at least) & this shouldn't present a GDB compatibility issue, since it'll be closer to what GCC produces anyway.

**Comment by Michael137** [comment]
> Summary is, if I'm reading this right:
> 
> * LLDB used to detect static members by the presence of `DW_AT_external`, but that's not correct/portable, you could have non-external static members if they were members of a non-linkage class, such as a class in an anonymous namespace
> * LLDB then started using the presence of `DW_AT_data_member_offset` to differentiate static and non-static member variables
> * LLDB also started assuming members of a union have a `DW_AT_data_member_offset` of zero, because GCC emits union non-static members without a `DW_AT_data_member_offset` (since they'd all be zero anyway) - unclear if that's to-spec or not? _shrug_
> * That broke static-member detection inside unions because all the members got an implicit `DW_AT_data_member_offset`
> 
> So we're discussing changing teh way clang emits static members to use `DW_TAG_variable` instead of `DW_TAG_member` to make it less ambiguous/solve the above issues "once and for all" _fingers crossed_
> 
> And you've tagged me as a heads up that we might be/are going to go in this direction/check I'm cool with it - yeah, sounds good to me. Doing things more clearly, and if that happens to be "more like GCC" I'm generally for it - they're still the bigger fish in the DWARF sea, and it's usually a safe direction to head unless there's extenuating circumstances.
> 
> At least our internal use ships pretty close to LLDB, so we don't have a particular need for some clang mode that's deeply backwards compatible (the inverse is somewhat true - be good if LLDB didn't just totally give up on doing some of the old heuristics - still able to debug old binaries as best it can, which seems like it wouldn't be too expensive/problematic to maintain for a while at least) & this shouldn't present a GDB compatibility issue, since it'll be closer to what GCC produces anyway.

Yup! those are exactly the issues

Alright sounds like we'll resolve this by simply implementing the DWARFv5 "`DW_TAG_variable` for static data members" feature. LLDB should mostly work out of the box with that.

To avoid crashing on older DWARF i think we could add a best effort attempt to detect the cases where we might have a static data member in a union and do the right thing. E.g., by adding back the check for `DW_AT_external`.

**Comment by Michael137** [comment]
Proposed solution to handle pre-DWARFv5 here: https://github.com/llvm/llvm-project/pull/68300
