### ISSUE TITLE
[clang-tidy] :bug: `std::vector(size, value)` in `modernize-return-braced-init-list `

### ISSUE THREAD

**Issue by ax3l** [llvm/llvm-project#68159]
## Description

The `clang-tidy` pass `modernize-return-braced-init-list` complains about constructors of `std::vector` that are not initializers lists.

In particular, the constructor
```C++
vector( size_type count,
                 const T& value,
                 const Allocator& alloc = Allocator() );
```
should be ignored.

## Versions Affected

Bug seen with LLVM 14.

## Reproducer
```C++
#include <vector>

std::vector<double>
foo()
{
    return std::vector<double>(4, 5);  // {5, 5, 5, 5}

}
```
https://en.cppreference.com/w/cpp/container/vector/vector

## X-Ref

https://github.com/ECP-WarpX/WarpX/pull/4338

## Keywords

- clang-tidy
- clang-tools-extra

**Comment by 5chmidti** [comment]
Just confirming that the current trunk version is affected as well: https://godbolt.org/z/xcen5GojE
