### ISSUE TITLE
__FLT128_DIG__ should not be defined if _Float128 does not exist.

### ISSUE THREAD

**Issue by trcrsired** [llvm/llvm-project#68168]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111687

This breaks GCC libstdc++ @pranavk

**Comment by pranavk** [comment]
Thanks for reporting. Let me take a look. Will keep you posted.

**Comment by tbaederr** [comment]
This is the same as https://github.com/llvm/llvm-project/issues/68138 I guess.

**Comment by pranavk** [comment]
I have reverted the commit for now in https://github.com/llvm/llvm-project/commit/7d21086d0ca4a680e96e0f4cd3e2597ebe027a48 while I work on fixing the issue.
