### ISSUE TITLE
LLVM 18 cannot read llvm-ir produced by rustc 1.72.1

### ISSUE THREAD

**Issue by glandium** [llvm/llvm-project#68281]
This is a regression from 625113402f9febd4d8c907a342ea09a3c0982ba8.

05b86a8fea23865e4a437efa9cb4f6844ccbf50e addressed a part of the regression. For instance, this:
```
  call void @llvm.dbg.value(metadata i64 or (i64 zext (i32 ptrtoint (ptr @anon.436463c58f189989edb51bc04335cb6d.21 to i32) to i64), i64 shl (i64 zext (i32 trunc (i64 lshr (i64 ptrtoint (ptr @anon.436463c58f189989edb51bc04335cb6d.21 to i64), i64 32) to i32) to i64), i64 32)), metadata !4453, metadata !DIExpression(DW_OP_LLVM_fragment, 64, 64)), !dbg !4493
```
used to cause an error but doesn't anymore with that fix.

What still causes an error, though, is e.g.:
```
  call void @llvm.dbg.value(metadata ptr inttoptr (i64 or (i64 zext (i32 ptrtoint (ptr @anon.202156da7d09c46fe0b29195d5b08186.240 to i32) to i64), i64 shl (i64 zext (i32 trunc (i64 lshr (i64 ptrtoint (ptr @anon.202156da7d09c46fe0b29195d5b08186.240 to i64), i64 32) to i32) to i64), i64 32)) to ptr), metadata !14853, metadata !DIExpression(DW_OP_LLVM_fragment, 0, 64)), !dbg !14944
```

from this object file: https://drive.google.com/file/d/17fb-_f363yRFibtkJjRQ5qihnAuOPbdc/view?usp=sharing

Cc: @nikic

**Comment by nikic** [comment]
Reduced input: https://gist.github.com/nikic/e2a95cbbc2d9d21b1bea4912147fce75

The fact that the same constant expression is used by metadata in both functions seems to be relevant. Possibly in that case the metadata gets encoded globally rather than per-function :/

**Comment by nikic** [comment]
Okay, I think I'm going to approach this from the other direction: Pretend that the constant has been deleted, which means the ValueAsMetadata reference will be replaced with UndefValue.

**Comment by glandium** [comment]
FYI, there is no remaining error building Firefox with cross-language LTO after https://github.com/llvm/llvm-project/commit/236228f43d018ebf11697610fe6504c167ed6ac8
