### ISSUE TITLE
Conversion of _Float16 for variadic functions doesn't seem to work

### ISSUE THREAD

**Issue by sh1boot** [llvm/llvm-project#68338]
Converting `_Float16` to `double` to pass to a regular function looks fine, but doing the conversion for a variadic function (like `printf()` does not work.

That is to say, the instruction to convert the bit pattern from 16-bit to 64-bit is omitted when passing the register as a variadic argument, but that same operation _does_ happen when passing the value to a function expecting a double.

`__fp16` gets converted to `double` just fine in both cases.

https://godbolt.org/z/r5o7djxbd

Observed on RISC-V and aarch64.

**Comment by kito-cheng** [comment]
That's defined and expected behaviours for _Float16 type, which defined in ISO/IEC TS 18661-3  IIRC

**Comment by sh1boot** [comment]
That checks out, and is even explained in the part of the manual I read to try to understand the difference (`__fp16` is promoted to float, so it will then be promoted to double).

So the real bug is just the lack of a printf format string warning.  Not this.
