### ISSUE TITLE
[clang-format] documentation Clang-Format Style Options stale link

### ISSUE THREAD

**Issue by cwhii** [llvm/llvm-project#68334]
[Clang-Format Style Options](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) stale link:

[Linux Kernel style](https://www.kernel.org/doc/Documentation/CodingStyle) displays 

> This file has moved to process/coding-style.rst

**Comment by owenca** [comment]
Fixed in 8902f12e61aa.
