### ISSUE TITLE
[clang-format] RemoveParentheses should not touch macros

### ISSUE THREAD

**Issue by HazardyKnusperkeks** [llvm/llvm-project#68354]
Catch2's `REQUIRE` (and stuff) need parentheses around `&&` otherwise they hit an static assert. So we need to not touch `REQUIRE((a && b));`. In general I think it is a good idea to not touch macros at all.

Now how to deal with that. Add an option to declare macros which shouldn't be touched? Use `TT_ForEachMacro` etc.? We have [some](https://github.com/llvm/llvm-project/blob/7a46baa465c49db84b7b5f8fa9ab847ec1da3ce4/clang/lib/Format/UnwrappedLineParser.cpp#L3872-L3874) [heuristics](https://github.com/llvm/llvm-project/blob/7a46baa465c49db84b7b5f8fa9ab847ec1da3ce4/clang/lib/Format/TokenAnnotator.cpp#L2107) to detect macros.
That could be put in a `IsMacro` function.

What do you think @owenca @mydeveloperday @rymiel ?

I'm willing to work on it, but you can also take on it, just asking for the way to go here.

**Comment by mydeveloperday** [comment]
Does it come down to the fact the macro doesn't itself put all its arguments in ()?

**Comment by HazardyKnusperkeks** [comment]
> > Catch2's `REQUIRE` (and stuff) need parentheses around `&&` otherwise they hit an static assert. So we need to not touch `REQUIRE((a && b));`.
> 
> clang-format is usually turned off for test cases, right? And we have `DisableFormat` for that. Or can you use `// clang-format off`? Also, `RemoveParentheses` is opt-in, so you can turn it off as the last choice?

Where does this data come from? I format my tests. clang-format does format its tests.
Of course I could disable formatting, or only the `RemoveParentheses` option, but that's not what I want.

> > In general I think it is a good idea to not touch macros at all.
> 
> If we have code like `if (Foo((cond1 || cond2)))`, why _in general_ wouldn't we want the redundant parentheses removed if `Foo` is a macro?

Because we don't know what the macro does with its input.
```c++
#define SQUARE(x) x * x

auto result = SQUARE((a + b));
```
Will change the meaning.

> Does it come down to the fact the macro doesn't itself put all its arguments in ()?
In my example above: Yes. For Catch2, I have no idea what, how or why exactly they do it, but that's not the point. It is 3rd party code which I shouldn't be needed to change.

> IMO we should keep most (if not all) non-whitespace changing options simple. They are already kind of fragile because of the lack of semantic information. We should avoid piling on them unless absolutely necessary.

The core message I support, but I don't see that this applies here.

If you want to close it as "wont do", I'm fine with that and deactivate the feature altogether.

**Comment by owenca** [comment]
> > clang-format is usually turned off for test cases, right? And we have `DisableFormat` for that. Or can you use `// clang-format off`? Also, `RemoveParentheses` is opt-in, so you can turn it off as the last choice?
> 
> Where does this data come from? I format my tests. clang-format does format its tests. Of course I could disable formatting, or only the `RemoveParentheses` option, but that's not what I want.

I got the impression from the fact that the .clang-format files in the following directories have clang-format disabled:
clang-tools-extra/test
clang-tools-extra/pseudo/test
clang-tools-extra/include-cleaner/test
clang/test
llvm/test

> ```c++
> #define SQUARE(x) x * x
> 
> auto result = SQUARE((a + b));
> ```
> 
> Will change the meaning.

But that's really a programmer error because the parameters in macro definitions should be wrapped in parens, e.g.:
```
#define SQUARE(x) ((x) * (x))`
auto result = SQUARE(a + b);
```

> > It is 3rd party code which I shouldn't be needed to change.
Is it usual to format 3rd party code?

> If you want to close it as "wont do", I'm fine with that and deactivate the feature altogether.

I would be very reluctant to make `RemoveParentheses` work differently with macros even though it seems easy to do. I went some trouble to make it work for the seemingly quite rare `decltype(auto)` case just because that's part of the language standard. :)

What do you think, @mydeveloperday and @rymiel ?

**Comment by owenca** [comment]
@HazardyKnusperkeks, one way to solve the problem is to use the `Macros` option:
```
$ cat test.cpp
#define SQUARE(x) x * x
auto result = SQUARE((a + b));
REQUIRE((a && b));
$ cat .clang-format
Macros:
- REQUIRE(x)=decltype(x)
- SQUARE(x)=decltype(x)
RemoveParentheses: ReturnStatement
$ clang-format -version
clang-format version 17.0.1
$ clang-format test.cpp
#define SQUARE(x) x *x
auto result = SQUARE((a + b));
REQUIRE((a && b));
$ 
```

**Comment by HazardyKnusperkeks** [comment]
> @HazardyKnusperkeks, one way to solve the problem is to use the `Macros` option:
> 
> ```
> $ cat test.cpp
> #define SQUARE(x) x * x
> auto result = SQUARE((a + b));
> REQUIRE((a && b));
> $ cat .clang-format
> Macros:
> - REQUIRE(x)=decltype(x)
> - SQUARE(x)=decltype(x)
> RemoveParentheses: ReturnStatement
> $ clang-format -version
> clang-format version 17.0.1
> $ clang-format test.cpp
> #define SQUARE(x) x *x
> auto result = SQUARE((a + b));
> REQUIRE((a && b));
> $ 
> ```

Thanks for that suggestion. I withdraw the issue and don't use `RemoveParentheses`.
