### ISSUE TITLE
[flang][runtime][omp2012] Wrong output while reading namelists

### ISSUE THREAD

**Issue by NimishMishra** [llvm/llvm-project#68383]
LLVM flang produces incorrect output while attempting to read to a namelist. Consider the following reproducer:

```
      program main
        type array_t
          integer   ::  n = 0   
          real      ::  a = 0.  
          real      ::  b = 0. 
        end type array_t

        type(array_t),save :: array_inp(1000)
        character*20  ::  name_inp = ''    
        namelist  /params/                         &
                 array_inp,                        &
                 name_inp

         open(UNIT=10,FILE="input",STATUS='OLD')
         read(10,NML=params)
         close(10)
         print *, name_inp
      end program
```

For the input file named `input` having contents:

```
&params
  array_inp =
   22784,  6.00,  12.00,
    4864,  8.00,  16.00,
  name_inp = 'my-name',
/
```

Compiled with `flang-new -g <filename>.f90` and run with `./a.out`, _empty_ newline is observed. As opposed, compiling with `gfortran -g <filename>.f90` and running with `./a.out`, correct output _my-name_ is observed.

**Comment by klausler** [comment]
Already fixed, probably by https://github.com/llvm/llvm-project/pull/66831.
