### ISSUE TITLE
Remove the workaround for gcc.90538?

### ISSUE THREAD

**Issue by Chandlerooo** [llvm/llvm-project#68407]
I notice a workaround for gcc.90538 in AsmPrinter.cpp introduced by commit https://github.com/M680x0/M680x0-mono-repo/commit/6cd232056c3cdaf5e9eb85ede8e42d0db97f0f71: 
https://github.com/llvm/llvm-project/blob/488a62f86e4f1260a2b4667b177679a6eac643c4/mlir/lib/IR/AsmPrinter.cpp#L2432-L2456
This bug has been marked as fixed: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90538. Shall it be removed?

**Comment by rikhuijzer** [comment]
I just saw that gcc 7 is still being used in https://reviews.llvm.org/D154940. This version was released in 2019 according to https://gcc.gnu.org/releases.html, and apparently still being used.

**Comment by joker-eph** [comment]
We support gcc7.4 right now I believe.
