### ISSUE TITLE
libc++ disagrees with libstd++ on constexpr std::string construction legality

### ISSUE THREAD

**Issue by pkasting** [llvm/llvm-project#68434]
The following code compiles with libstd++, but not libc++:
```
#include <iostream>
#include <string>

struct S {
  std::string s_;
};

constexpr S s{"Test"};

int main() {
  std::cout << s.s_;
  return 0;
}
```

Online repro: https://godbolt.org/z/fjdnrPceh

It seems like either this is legal or it isn't. I'm not well-versed in the minutiae of constexpr std::strings in C++20, but my layman's impression is that this ought to work, so libstdc++ is correct and libc++ is wrong?

**Comment by aeubanks** [comment]
See https://github.com/llvm/llvm-project/pull/66576

**Comment by pkasting** [comment]
Ah. I see that when I increase the length of the string, libstdc++ starts to fail too. That's really unfortunate; I wish both failed in this case :(. Looks like ldionne was proposing some kind of diagnostic in this case; I would appreciate that, so we don't accidentally rely on escaping constexpr strings to runtime in Chrome.
