### ISSUE TITLE
readability-avoid-const-params-in-decls has a misleading source location

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#68492]
`int square(int const num);` has the source location `1:12`, which is the start of the type. While the command-line diagnostic shows squiggly lines underneath the `const`, editors are tricked into putting squigglies under `int`, which leads some programmers to think that there's something wrong with the type.

`int square(const int num)` renders correctly, so I suspect that the current logic is making an assumption about the placement of `const`.

[Here's an example on Compiler Explorer.](https://godbolt.org/z/z56Pz75jM)

**Comment by PiotrZSL** [comment]
Issue is reported for an parameter, and it point to begin of the parameter.
As the check is already finding a 'const' token location then that location could be used, but I thing that this check may break when we have something like this: "int square(Type<const int> const num);"

**Comment by oyiekeallen** [comment]
Interested in picking this up if it is still up for grabs

**Comment by PiotrZSL** [comment]
> Interested in picking this up if it is still up for grabs

The just assign your self and give it a try.
Cheapest fix is to use location provided from a found token, to make it work token need to be found before diagnostic is constructed and then location of token can be used to construct diagnostic, some minor refactoring will be needed. And probably such fix will be sufficient.
