### ISSUE TITLE
Missing links to release notes on https://releases.llvm.org/

### ISSUE THREAD

**Issue by PiotrZSL** [llvm/llvm-project#68493]
No link to for example clang extra documentation for 17.0.2.
Link https://releases.llvm.org/17.0.2/tools/clang/tools/extra/docs/ReleaseNotes.html is dead.
where link https://releases.llvm.org/17.0.1/tools/clang/tools/extra/docs/ReleaseNotes.html is working.

Other thing is that when for older branches we got links to 16.0.1, 16.0.2, here we got only 17.0.2.

**Comment by PiotrZSL** [comment]
@tru Could you check this ?
17.0.2 is also missing from an Download page.

**Comment by tru** [comment]
We usually don't upload docs for the minor versions, at least, I have never done that. I can update the Download page, but no promises when. It requires a lot of manual annoying work, and I am busy with other things.

**Comment by PiotrZSL** [comment]
For 17.0.1 would be sufficient, as this is first one. Simply looks like documentation exists but links to it are missing.

**Comment by tru** [comment]
Oh I see what you are saying now. Yeah I must have messed up when editing the site the last time since I do it manually. Let me see if I can fix it.

**Comment by tru** [comment]
Fixed now check https://releases.llvm.org/?1 (adding the ?1 just to bust the cache).

**Comment by PiotrZSL** [comment]
Sweet, now https://releases.llvm.org/download.html
17.0.2 is missing from that page (but i'm not sure if this page is used)

**Comment by tru** [comment]
Hm wonder if anyone care about that page, maybe we could just remove it or redirect it.

**Comment by PiotrZSL** [comment]
download.html it's not so important for me, main release page were. I thing we can close this issue now.
