### ISSUE TITLE
Simplification for `(A ==/!= B) &/| (((cast)A) CMP C)`

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#68514]
Example:
https://godbolt.org/z/Pr8T7xsMz
```c
bool f(int a)
{
    bool t = a == 0;
    short t1 = a;
    bool t2 = t1 >= 3;
    return t & t2;
}

bool g(int b)
{
    bool t = b == 3;
    short t1 = b;
    bool t2 = t1 >= 3;
    return t | t2;
}
```

The example above is taken from the following:
https://github.com/gcc-mirror/gcc/blob/master/gcc/testsuite/gcc.dg/tree-ssa/cmpbit-6.c
https://github.com/gcc-mirror/gcc/blob/master/gcc/testsuite/gcc.dg/tree-ssa/cmpbit-7.c

**Comment by dtcxzyw** [comment]
Alive2: https://alive2.llvm.org/ce/z/6EVKhN

**Comment by dtcxzyw** [comment]
Should be fixed by https://github.com/llvm/llvm-project/pull/70335.
