### ISSUE TITLE
zero extending i1 to i32 on x86

### ISSUE THREAD

**Issue by cooperp** [llvm/llvm-project#6851]
|  |  |
| --- | --- |
| Bugzilla Link | [6479](https://llvm.org/bz6479) |
| Version | trunk |
| OS | Windows NT |
| Blocks | llvm/llvm-bugzilla-archive#26299  |
| Attachments | [intermediate test file](https://user-images.githubusercontent.com/599599/143740852-58117ca8-de5b-42ba-9e8c-c6271657f69f.gz) |
| CC | @RKSimon,@sunfishcode |

## Extended Description 

```llvm
target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-f80:32:32-n8:16:32"
target triple = "i386-pc-cygwin"

define zeroext i32 @_Z1fv(i1 %b, i8 %c, i1 %d, i1 %e) {
entry:
  br i1 %b, label %bb, label %bb1

bb:                                               ; preds = %entry
  %first = zext i1 %d to i32                          ; <i32> [#uses=1]
  br label %bb2

bb1:                                              ; preds = %entry
  %second = zext i1 %e to i32                          ; <i32> [#uses=1]
  br label %bb2

bb2:                                              ; preds = %bb1, %bb
  %p = phi i32 [ %first, %bb ], [ %second, %bb1 ]         ; <i32> [#uses=1]
  br label %return

return:                                           ; preds = %bb2
  ret i32 %p
}
```

This curently generates a redundant zero extension as 

```asm
movzbl	%al, %eax
andl	$1, %eax
```

which can just be 

```
andl	$1, %eax
```

I've written a new pattern for X86InstrInfo.td which removes the unused mov but i wasn't sure where in that file to put it so i'm not attaching it as a patch

def : Pat<(i32 (and (i32 (anyext GR8 :$src)), (i32 1))),
          (AND32ri (SUBREG_TO_REG (i32 0), GR8:$src, x86_subreg_8bit), 1)>;

Can someone please verify if i've done the right thing here.  I get the right result which is always a good start.  Also, i've only seen this case (mask with 1) be output, but would it be better to match any constant in the 1-255 range here, and if it is worth it, could someone please tell me how that would be written.

**Comment by chfast** [comment]
I cannot reproduce it in any of `llc` versions starting from 3.2. https://godbolt.org/z/a3vnse4bx
