### ISSUE TITLE
Detect obfuscation of reinterpret_cast

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#68532]
Hi!

This is a check request / enhancement request of an existing check. 

Today, we have the check `cppcoreguidelines-pro-type-reinterpret-cast` to warn about usages of `reinterpret_cast`. What people end up doing to work around the warning is changing this code:

```
float y = *reinterpret_cast<float*>(&x);
```

Into:

```
float y = *static_cast<float*>(static_cast<void*>(&x));
```

However, both expressions are equivalent, as per [the Standard](https://eel.is/c++draft/expr.reinterpret.cast#7).

We would therefore like to flag this case as well. One could argue that obfuscating the code is more dangerous than having the explicit `reinterpret_cast` in the first place, because it's easier to miss in code review and search for afterwards.

So, to check for this case, I believe it could be done in 2 ways:

- Add a `readability` check that tells the user to replace the obfuscated code with an explicit `reinterpret_cast`, or:
- Extend the `cppcoreguidelines-pro-type-reinterpret-cast` check to cover this case as well (potentially opt-in via configuration).

What do you think?

**Comment by PiotrZSL** [comment]
Agree, other problem with casting to void* is: https://godbolt.org/z/9v1658ehM
```
struct A
{
    int a;
};

struct B
{
    int b;
};

struct C : A, B {};

int main()
{
    C c{};
    c.b = 10;
    c.a = 11;

    B& b = *static_cast<B*>(static_cast<void*>(&c));
    std::cout << "C.b is " << b.b;

    return 0;
}
```
```
Program returned: 0
C.b is 11
```

So maybe something like this:
bugprone-casting-through-void or readability-simplify-casting
