### ISSUE TITLE
[clang] [Modules] Add warning for including header in module purview

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#68615]
Given the following code

```cpp
export module a;

#include <new>
```

When compiling with `-std=c++26 -stdlib=libc++ -Weverything`

all that we get as output is

```console
In file included from <source>:3:
/opt/compiler-explorer/clang-assertions-trunk-20231009/bin/../include/c++/v1/new:217:66: error: declaration of 'operator new' in module a follows declaration in the global module
  217 | _LIBCPP_NODISCARD_AFTER_CXX17 _LIBCPP_OVERRIDABLE_FUNC_VIS void* operator new(std::size_t __sz) _THROW_BAD_ALLOC;
      |                                                                  ^
note: previous declaration is here
/opt/compiler-explorer/clang-assertions-trunk-20231009/bin/../include/c++/v1/new:219:36: error: declaration of 'operator delete' in module a follows declaration in the global module
  219 | _LIBCPP_OVERRIDABLE_FUNC_VIS void  operator delete(void* __p) _NOEXCEPT;
      |                                    ^
note: previous declaration is here
/opt/compiler-explorer/clang-assertions-trunk-20231009/bin/../include/c++/v1/new:225:66: error: declaration of 'operator new[]' in module a follows declaration in the global module
  225 | _LIBCPP_NODISCARD_AFTER_CXX17 _LIBCPP_OVERRIDABLE_FUNC_VIS void* operator new[](std::size_t __sz) _THROW_BAD_ALLOC;
      |                                                                  ^
note: previous declaration is here
/opt/compiler-explorer/clang-assertions-trunk-20231009/bin/../include/c++/v1/new:227:36: error: declaration of 'operator delete[]' in module a follows declaration in the global module
  227 | _LIBCPP_OVERRIDABLE_FUNC_VIS void  operator delete[](void* __p) _NOEXCEPT;
      |                                    ^
note: previous declaration is here
/opt/compiler-explorer/clang-assertions-trunk-20231009/bin/../include/c++/v1/new:234:66: error: declaration of 'operator new' in module a follows declaration in the global module
  234 | _LIBCPP_NODISCARD_AFTER_CXX17 _LIBCPP_OVERRIDABLE_FUNC_VIS void* operator new(std::size_t __sz, std::align_val_t) _THROW_BAD_ALLOC;
      |                                                                  ^
note: previous declaration is here
/opt/compiler-explorer/clang-assertions-trunk-20231009/bin/../include/c++/v1/new:236:36: error: declaration of 'operator delete' in module a follows declaration in the global module
  236 | _LIBCPP_OVERRIDABLE_FUNC_VIS void  operator delete(void* __p, std::align_val_t) _NOEXCEPT;
      |                                    ^
note: previous declaration is here
/opt/compiler-explorer/clang-assertions-trunk-20231009/bin/../include/c++/v1/new:242:66: error: declaration of 'operator new[]' in module a follows declaration in the global module
  242 | _LIBCPP_NODISCARD_AFTER_CXX17 _LIBCPP_OVERRIDABLE_FUNC_VIS void* operator new[](std::size_t __sz, std::align_val_t) _THROW_BAD_ALLOC;
      |                                                                  ^
note: previous declaration is here
/opt/compiler-explorer/clang-assertions-trunk-20231009/bin/../include/c++/v1/new:244:36: error: declaration of 'operator delete[]' in module a follows declaration in the global module
  244 | _LIBCPP_OVERRIDABLE_FUNC_VIS void  operator delete[](void* __p, std::align_val_t) _NOEXCEPT;
      |                                    ^
note: previous declaration is here
8 errors generated.
Compiler returned: 1
```

This is not obvious to users what they did wrong. The issue here is that the `#include` is in the module purview. It would be nice to have a general warning saying "Don't include there, type `module; #include <whatever>` instead.

**Comment by ChuanqiXu9** [comment]
I feel like this is not so do-able thing. One the one hand, `#include` is not a thing in the semantic analysis. It belongs to the preprocessor. So it means we need to implement this warning in the preprocessor if we really want to do this. On the other hand, `#include` may happen in the module purview in a proper way. One use case is to define the enums. For example, we  did this: https://github.com/llvm/llvm-project/blob/b5dffd4957dfb58c73e168a3d9b6967f03b23a6c/clang/include/clang/AST/ASTContext.h#L1116-L1136

Also there is another practice to modularize a library:

```
// header.h
#ifndef USE_MODULES
#include "..."
#endif

EXPORT class A {...};

other declarations....

// a.cppm
module;
#define USE_MODULES
#define EXPORT export
#include "..."
export module a;
#include "header.h"
...
```

So it looks not good to prevent including in the module purview.

**Comment by koplas** [comment]
MSVC emits a warning for this: [C5244](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-by-compiler-version?view=msvc-170#warnings-introduced-in-visual-studio-2022-version-170-compiler-version-1930)

**Comment by ChuanqiXu9** [comment]
> MSVC emits a warning for this: [C5244](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-by-compiler-version?view=msvc-170#warnings-introduced-in-visual-studio-2022-version-170-compiler-version-1930)

Got it. but that still can't work for the use cases I mentioned above... a hard decision to make ...

**Comment by iains** [comment]
+1 to @ChuanqiXu9, this seems like a very hard warning to get right (i.e. avoid many false-positives).  It is certainly not obvious how the pre-processor would differentiate headers that are intended to be GMF from ones that are intended to be part of the named module.

I suppose we could warn only for a known set (i.e. the std lib).

**Comment by ChuanqiXu9** [comment]
> +1 to @ChuanqiXu9, this seems like a very hard warning to get right (i.e. avoid many false-positives). It is certainly not obvious how the pre-processor would differentiate headers that are intended to be GMF from ones that are intended to be part of the named module.
> 
> I suppose we could warn only for a known set (i.e. the std lib).

Good idea. Sent https://github.com/llvm/llvm-project/pull/69555. Here I treat the headers within angles as the system headers. I think the judgement may make sense.
