### ISSUE TITLE
Some code was removed by mistake

### ISSUE THREAD

**Issue by GengQi-mthreads** [llvm/llvm-project#68655]
This is a normal .cpp code.

```c++
// struct6.cpp
struct S1 {
  long long a;
  long long b;
};

void inline copyMem(S1 *dst, S1 *src) {
  unsigned *d = reinterpret_cast<unsigned *>(dst);
  unsigned *s = reinterpret_cast<unsigned *>(src);

  for (int i = 0; i < sizeof(S1) / sizeof(unsigned); i++) {
    *d = *s;
    d++;
    s++;
  }
}

void math(S1 *dst, int *srcA, int idx_t) {

  S1 zero[4];
  for (int i = 0; i < 4; i++) {
    zero[i].a = i + idx_t;
    zero[i].b = i * idx_t;
  }

  copyMem(&dst[idx_t], &zero[srcA[idx_t]]);
}
```

clang++ struct6.cpp -O2 -S -emit-llvm

```
; ModuleID = 'struct6.cpp'
source_filename = "struct6.cpp"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: mustprogress nofree nosync nounwind memory(argmem: readwrite) uwtable
define dso_local void @_Z4mathP2S1Pii(ptr nocapture noundef writeonly %0, ptr nocapture noundef readonly %1, i32 noundef %2) local_unnamed_addr #0 {
  ret void
}

attributes #0 = { mustprogress nofree nosync nounwind memory(argmem: readwrite) uwtable "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{!"clang version 16.0.0"}
```

All the code was removed, but that doesn't seem to make reasonable sense.

**Comment by shafik** [comment]
You are invoking undefined behavior by violating strict aliasing rule, see: https://godbolt.org/z/E48sf7bTa

where we compare clang w/ `-fno-strict-aliasing` and with `-fstrict-aliasing` with the first option clang allows strict aliasing violations and does not remove the code.

In particular these lines:

```cpp
  unsigned *d = reinterpret_cast<unsigned *>(dst);
  unsigned *s = reinterpret_cast<unsigned *>(src);
```

As per [basic.lval p11](https://eel.is/c++draft/basic.lval#11) only *char*, *unsigned char* and *std::byte* are allowed to alias any other type.

We can see this in action if we modify your code to use *unsigned char* as opposed to *unsigned int*: https://godbolt.org/z/1oM4x5jPh

and then we see that your code is not optimized away.

**Comment by GengQi-mthreads** [comment]
> You are invoking undefined behavior by violating strict aliasing rule, see: https://godbolt.org/z/E48sf7bTa
> 
> where we compare clang w/ `-fno-strict-aliasing` and with `-fstrict-aliasing` with the first option clang allows strict aliasing violations and does not remove the code.
> 
> In particular these lines:
> 
> ```c++
>   unsigned *d = reinterpret_cast<unsigned *>(dst);
>   unsigned *s = reinterpret_cast<unsigned *>(src);
> ```
> 
> As per [basic.lval p11](https://eel.is/c++draft/basic.lval#11) only _char_, _unsigned char_ and _std::byte_ are allowed to alias any other type.
> 
> We can see this in action if we modify your code to use _unsigned char_ as opposed to _unsigned int_: https://godbolt.org/z/1oM4x5jPh
> 
> and then we see that your code is not optimized away.

Thank you very much for your answer, I totally got it!

**Comment by HerrCai0907** [comment]
@shafik Can it be diagnosed somehow? Do you think where is the best position to implement diagnose, clang-tidy or clang?

**Comment by shafik** [comment]
> @shafik Can it be diagnosed somehow? Do you think where is the best position to implement diagnose, clang-tidy or clang?

Diagnosing strict aliasing violations is hard! I think @fhahn has picked up the TySan (Type Sanitizer) work which was supposed to cover this area but I don't know how that is progressing.
