### ISSUE TITLE
[InstructionSimplify] InstructionSimplify error deleted `phi`

### ISSUE THREAD

**Issue by DianQK** [llvm/llvm-project#68683]
I tried this IR:

```llvm
define i32 @src(i1 %c0, i1 %c1, i32 %v1) {
start:
  br i1 %c0, label %bb0, label %bb1

bb0:
  br label %bb1

bb1:
  %x = phi i32 [ %v1, %bb0 ], [ undef, %start ]
  br i1 %c1, label %bb0, label %bb2

bb2:
  ret i32 %x
}
```

`phi` should not be deleted by InstructionSimplify.

alive2: https://alive2.llvm.org/ce/z/LNXeGp

**Comment by nikic** [comment]
I don't think this is related to CVP? This is InstSimplify behavior.

This poison-propagation hole (and a number of similar ones) has been left intentionally until the "poison on uninit load" semantics come into effect. Though it's possible that the relatively wide use of noundef nowadays allows us to fix this independently. We'd have to evaluate codegen impact.

**Comment by DianQK** [comment]
> I don't think this is related to CVP? This is InstSimplify behavior.

Yes. The problem is in the https://github.com/llvm/llvm-project/blob/a5686c2b5541c58c9a1dd760761c369124546f78/llvm/lib/Analysis/InstructionSimplify.cpp#L5284.

> This poison-propagation hole (and a number of similar ones) has been left intentionally until the "poison on uninit load" semantics come into effect. Though it's possible that the relatively wide use of noundef nowadays allows us to fix this independently. We'd have to evaluate codegen impact.

I tried some changes, but that broke a lot of test cases.

**Comment by dtcxzyw** [comment]
> It looks like this is a rather large change/impact.

I agree. This has a huge impact on Rust applications due to the lack of `noundef` on arguments/retvals.
