### ISSUE TITLE
Crash with modules and `constexpr` destructor

### ISSUE THREAD

**Issue by hahnjo** [llvm/llvm-project#68702]
The following is a heavily reduced test case of `<vector>` in libstdc++ 13.2.0:
```c++
// RUN: rm -rf %t
// RUN: mkdir %t
// RUN: split-file %s %t

// RUN: %clang_cc1 -std=c++20 -emit-obj -fmodules -fimplicit-module-maps -fmodules-cache-path=%t %t/main.cpp -o %t/main.o

//--- V.h
#ifndef V_H
#define V_H

class A {
public:
  constexpr A() { }
  constexpr ~A() { }
};

template <typename T>
class V {
public:
  V() = default;

  constexpr V(int n, const A& a = A()) {}
};

#endif

//--- inst1.h
#include "V.h"

static void inst1() {
  V<int> v;
}

//--- inst2.h
#include "V.h"

static void inst2() {
  V<int> v(100);
}

//--- module.modulemap
module "M" {
  export *
  module "V.h" {
    export *
    header "V.h"
  }
  module "inst1.h" {
    export *
    header "inst1.h"
  }
}

module "inst2.h" {
  export *
  header "inst2.h"
}

//--- main.cpp
#include "V.h"
#include "inst2.h"

static void m() {
  static V<int> v(100);
}
```

It crashes with
```
Unhandled cleanup; missing full expression marker?
UNREACHABLE executed at clang/lib/AST/ExprConstant.cpp:15617!
```

**Comment by hahnjo** [comment]
From the surface, this looks similar to https://github.com/llvm/llvm-project/issues/57788 and https://github.com/llvm/llvm-project/issues/62462 which were fixed by https://github.com/llvm/llvm-project/commit/9857caf9d14f70767035d821313045b56dbe3b10. @cor3ntin maybe you have an idea what could still be going wrong?

**Comment by hahnjo** [comment]
Looking again, I noticed that this is a different `llvm_unreachable` than https://github.com/llvm/llvm-project/issues/62462, and it seems applying the same approach as commit 9857caf9d14f70767035d821313045b56dbe3b10 to `Expr::EvaluateAsInitializer` fixes the crash:
```diff
diff --git a/clang/lib/AST/ExprConstant.cpp b/clang/lib/AST/ExprConstant.cpp
index e5539dedec02..a97e7bd81408 100644
--- a/clang/lib/AST/ExprConstant.cpp
+++ b/clang/lib/AST/ExprConstant.cpp
@@ -15604,10 +15604,13 @@ bool Expr::EvaluateAsInitializer(APValue &Value, const ASTContext &Ctx,
     LValue LVal;
     LVal.set(VD);
 
-    if (!EvaluateInPlace(Value, Info, LVal, this,
-                         /*AllowNonLiteralTypes=*/true) ||
-        EStatus.HasSideEffects)
-      return false;
+    {
+      FullExpressionRAII Scope(Info);
+      if (!EvaluateInPlace(Value, Info, LVal, this,
+                           /*AllowNonLiteralTypes=*/true) ||
+          EStatus.HasSideEffects)
+        return false;
+    }
 
     // At this point, any lifetime-extended temporaries are completely
     // initialized.
```

Does this change make sense? NB I have no idea what `FullExpressionRAII` does...

**Comment by shafik** [comment]
Yeah, it seems like it is always going to be a full-expression and so that would make sense, wdyt @cor3ntin

**Comment by hahnjo** [comment]
I opened https://github.com/llvm/llvm-project/pull/69076 with the test and the fix described in https://github.com/llvm/llvm-project/issues/68702#issuecomment-1761615196. I'd still be curious why this problem only happens with a very specific setup involving modules, and whether this points to a hidden problem underneath...
