### ISSUE TITLE
CUDA code compile error for asm code: expected ')'

### ISSUE THREAD

**Issue by zhiweij1** [llvm/llvm-project#68773]
```
inline __device__ float4 hmma_fp32(const uint2& a, unsigned int b)
{
    float4 c;
    float  zero = 0.f;
    asm volatile("mma.sync.aligned.m16n8k8.row.col.f32.f16.f16.f32 \n"
                 "    {%0, %1, %2, %3}, \n"
                 "    {%4, %5}, \n"
                 "    {%6}, \n"
                 "    {%7, %7, %7, %7}; \n"

                 : "=f"(c.x), "=f"(c.y), "=f"(c.z), "=f"(c.w)
                 : "r"(a.x) "r"(a.y), "r"(b), "f"(zero));
    return c;
}
```
https://godbolt.org/z/jxd483a8j

This code can be built by nvcc: https://godbolt.org/z/34Gaoz9r6

The original code comes from https://github.com/NVIDIA/FasterTransformer/blob/afdf9a9eb86f15363c0249117d166d6b45dbb371/src/fastertransformer/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.hpp#L636

It seems that nvcc does not depend on the `,` for separation.
Below code also can be built:
```
inline __device__ float4 hmma_fp32(const uint2& a, unsigned int b)
{
    float4 c;
    float  zero = 0.f;
    asm volatile("mma.sync.aligned.m16n8k8.row.col.f32.f16.f16.f32 \n"
                 "    {%0, %1, %2, %3}, \n"
                 "    {%4, %5}, \n"
                 "    {%6}, \n"
                 "    {%7, %7, %7, %7}; \n"

                 : "=f"(c.x) "=f"(c.y) "=f"(c.z) "=f"(c.w)
                 : "r"(a.x) "r"(a.y) "r"(b) "f"(zero));
    return c;
}
```
https://godbolt.org/z/eqqveTqTx

**Comment by Artem-B** [comment]
Clang is absolutely correct to complain in this case. Inline asm arguments must be separated by commas. Adding the missing commans makes the code compile with both clang and NVCC: https://godbolt.org/z/ojKqb15v5

NVCC not diagnosing it is a bug in NVCC, IMO.
