### ISSUE TITLE
[LICMPass] Runtime issues caused by LICMpass optimization

### ISSUE THREAD

**Issue by Veyena** [llvm/llvm-project#68776]
case:
[test-code.txt](https://github.com/llvm/llvm-project/files/12866820/test-code.txt)
Commands：clang -O2 test-code.c && ./a.out 10    VS   clang -O0 test-code.c && ./a.out 10
result：
![image](https://github.com/llvm/llvm-project/assets/43949371/92d5633e-77c5-4df2-9c8b-055a1238a10f)

**Comment by Veyena** [comment]
IR informations obtained through '-opt-bisect-limit' option:
before run LICMpass: 
[184-test-code.txt](https://github.com/llvm/llvm-project/files/12866920/184-test-code.txt)
after run LICMpass:
[185-test-code.txt](https://github.com/llvm/llvm-project/files/12866927/185-test-code.txt)

**Comment by nikic** [comment]
Infinite loops without side effects are undefined behavior in C. Use `-fno-finite-loops` to make them well-defined.

**Comment by Veyena** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
我已经收到您的邮件，会尽快给您回复。

**Comment by Veyena** [comment]
> Infinite loops without side effects are undefined behavior in C. Use `-fno-finite-loops` to make them well-defined.

after add option '-fno-finite-loops' ,the result is:
![image](https://github.com/llvm/llvm-project/assets/43949371/718a5922-8566-4c48-8a50-8f7564f72ac8)

And if I changed the case to this:
[test-code2.txt](https://github.com/llvm/llvm-project/files/12876192/test-code2.txt)

commands changed to :clang -O2 test-code2.c && ./a.out 1 VS clang -O0 test-code2.c && ./a.out 1
the result is also different:
![image](https://github.com/llvm/llvm-project/assets/43949371/4e9363cf-e8c1-45ec-92ce-06f1c036ffac)

**Comment by nikic** [comment]
Sorry, I didn't look carefully enough at your example. The issue is even more severe, because you are reading a non-atomic variable from a signal handler.

**Comment by Veyena** [comment]
> Sorry, I didn't look carefully enough at your example. The issue is even more severe, because you are reading a non-atomic variable from a signal handler.

Yes, so in LICM, promoteLoopAccessesToScalars function should consider the non-atomic variable readed from a signal handler.

**Comment by nikic** [comment]
@XingYuShuai No, your code is not well-defined. You can only read lock-free atomic or volatile sig_atomic_t from a signal handler.

**Comment by XingYuShuai** [comment]
> @XingYuShuai No, your code is not well-defined. You can only read lock-free atomic or volatile sig_atomic_t from a signal handler.

If the Run_Index is volatile or atomic , the StoreSafety in LICM.cpp would not be seted to StoreSafe. 
![image](https://github.com/llvm/llvm-project/assets/43949371/b4fc72c7-8e1e-476e-a525-571fa38995cf)
