### ISSUE TITLE
[clang] character '$' cannot be specified by a universal character name

### ISSUE THREAD

**Issue by LittleMeepo** [llvm/llvm-project#68782]
`clang test.c -std=c99 -fdollars-in-identifiers`

```
void abort (void);
int a$b(void) { return 1; }
int main (void)
{
  if (a\u0024b() != 1)
    abort ();

  return 0;
}
```

error:
```
<source>:8:8: error: character '$' cannot be specified by a universal character name
    8 |   if (a\u0024b() != 1)
      |        ^
<source>:8:7: error: use of undeclared identifier 'a'
    8 |   if (a\u0024b() != 1)
      |       ^
<source>:8:8: error: expected ')'
    8 |   if (a\u0024b() != 1)
      |        ^
<source>:8:6: note: to match this '('
    8 |   if (a\u0024b() != 1)
      |      ^
3 errors generated.
Compiler returned: 1
```

while llvm-16 can compile this code successfully.

url: https://godbolt.org/z/aPYE5KE77

**Comment by wangpc-pp** [comment]
I think this patch (https://reviews.llvm.org/D153621) is related. It seems to be by design?

**Comment by shafik** [comment]
CC @cor3ntin I feel like we have seen this recently but I can't find the issue

**Comment by cor3ntin** [comment]
Yup - this is https://github.com/llvm/llvm-project/issues/67943 
This change is intended, as both C and C++ added $ to the basic character set
