### ISSUE TITLE
ERROR: Failed building wheel for scikit-learn

### ISSUE THREAD

**Issue by Wilson-BR** [llvm/llvm-project#68785]
arm-linux-androideabi-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -march=armv7-a -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r25c-api-24-v2/sysroot/usr/lib -march=armv7-a -Wl,--fix-cortex-a8 -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -march=armv7-a -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r25c-api-24-v2/sysroot/usr/lib -lpython3.11 build/temp.linux-armv7l-cpython-311/sklearn/cluster/_k_means_elkan.o -L/data/data/com.termux/files/usr/lib -Lbuild/temp.linux-armv7l-cpython-311 -lm -lpython3.11 -llibsvm-skl -lliblinear-skl -o build/lib.linux-armv7l-cpython-311/sklearn/cluster/_k_means_elkan.cpython-311.so -fopenmp
      PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
      clang: error: unable to execute command: Bus error
      clang: error: linker command failed due to signal (use -v to see invocation)
      error: command '/data/data/com.termux/files/usr/bin/arm-linux-androideabi-clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
Failed to build scikit-learn
ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects

**Comment by dtcxzyw** [comment]
It seems like the crash happened in the downstream linker (typically `GNU ld`) due to I/O error/memory error. It is likely not a problem of Clang/LLVM. Can you reproduce this problem on another machine?

**Comment by Wilson-BR** [comment]
I haven't tried it on another machine. Somehow I managed to install it.
I had problems with little space, and I lacked libraries. I resolved each difficulty, unfortunately I didn't write down the steps I used in my case.
The last commands I used were these:
pip3 cache purge
pip3 install scikit-learn --no-build-isolation
And it was able to install.

**Comment by Wilson-BR** [comment]
I haven't tried it on another machine. Somehow I managed to install it.
I had problems with little space, and I lacked libraries. I resolved each difficulty, unfortunately I didn't write down the steps I used in my case.
The last commands I used were these:
pip3 cache purge
pip3 install scikit-learn --no-build-isolation
And it was able to install.
