### ISSUE TITLE
Why are releases of clang+llvm not consistently created for different architectures

### ISSUE THREAD

**Issue by ceastman-r7** [llvm/llvm-project#68804]
for instance 17.0.2 only has a tgz for x86_64 ubuntu 22 but 17.0.1 has no tgz for the same operating system.

release 17.0.2 has:
clang+llvm-17.0.2-aarch64-linux-gnu.tar.xz
clang+llvm-17.0.2-amd64-pc-solaris2.11.tar.xz
clang+llvm-17.0.2-armv7a-linux-gnueabihf.tar.gz
clang+llvm-17.0.2-powerpc64-ibm-aix-7.2.tar.xz
clang+llvm-17.0.2-powerpc64le-linux-rhel-8.8.tar.xz
clang+llvm-17.0.2-sparc64-unknown-linux-gnu.tar.xz
clang+llvm-17.0.2-sparcv9-sun-solaris2.11.tar.xz
clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04.tar.xz

release 17.0.1 has:
clang+llvm-17.0.1-aarch64-linux-gnu.tar.xz
clang+llvm-17.0.1-amd64-pc-solaris2.11.tar.xz
clang+llvm-17.0.1-arm64-apple-darwin22.0.tar.xz
clang+llvm-17.0.1-armv7a-linux-gnueabihf.tar.gz
clang+llvm-17.0.1-final_powerpc64-ibm-aix-7.2.tar.xz
clang+llvm-17.0.1-powerpc64le-linux-rhel-8.8.tar.xz
clang+llvm-17.0.1-sparc64-unknown-linux-gnu.tar.xz)
clang+llvm-17.0.1-sparcv9-sun-solaris2.11.tar.xz

release 16.06 has no x86_64 only the following
clang+llvm-16.0.6-aarch64-linux-gnu.tar.xz
clang+llvm-16.0.6-powerpc64le-linux-rhel-8.7.tar.xz

**Comment by tbaederr** [comment]
Because they are built by volunteers

**Comment by ceastman-r7** [comment]
its not an automated build system?

**Comment by asl** [comment]
The only official release are sources. Everything else is done by volunteers (especially on non-standard architectures).

Some things (were possible) are automated, e.g. APT repo
