### ISSUE TITLE
Regression: no longer generating `vdpbf16ps` with `m32bcst` RHS

### ISSUE THREAD

**Issue by bjacob** [llvm/llvm-project#68810]
This is a regression in the performance of the generated code, losing a peephole optimization to target a useful target instruction. Compiler Explorer: https://godbolt.org/z/xsGGsov5W

Summary:

AVX-512 has multiply-accumulate instructions with broadcasted-scalar memory-operand variant for the RHS operand ("m32bcst"). These aren't 1:1 reflected in intrinsics, instead the expectation is that the compiler will turn a sequence of intrinsics (broadcast RHS, then vector-to-vector FMA) into this instruction. This issue is about that peephole optimization no longer happening.

This is a follow-up to recently-fixed Issue #68117 which was about a compiler crash on the same source code. Now that it's fixed, we can test again, but this limits the ability to narrow the regression window on this issue.

Summary:

Clang version | result
--- | ---
Clang 15 | Generates optimal code
Clang 16 | Compiler crash (#68117).
Clang 17 | Compiler crash (#68117).
Clang 18 (trunk after #68117 fixed) | Generates sub-optimal code.

Testcase (see it in Compiler Explorer: https://godbolt.org/z/xsGGsov5W)

```c
#include <immintrin.h>
#include <stdint.h>

static __m512bh bitcast_16xf32_to_32xbf16(__m512 a) {
  return *(const __m512bh*)(&a);
}

__m512 iree_mm512_dpbf16_ps_broadcast_rhs(
    __m512 acc, __m512bh lhs, const uint16_t* rhs) {
  return _mm512_dpbf16_ps(acc, lhs,
                          bitcast_16xf32_to_32xbf16(_mm512_set1_ps(
                              *(const float*)rhs)));
}
```

Compile with these flags: `-O2 -mavx512f -mavx512bf16`

Sub-optimal result with current trunk (Clang 18):

```asm
iree_mm512_dpbf16_ps_broadcast_rhs:     # @iree_mm512_dpbf16_ps_broadcast_rhs
        vbroadcastss    zmm2, dword ptr [rdi]
        vdpbf16ps       zmm0, zmm1, zmm2
        ret
```

Optimal result with Clang 15:

```asm
iree_mm512_dpbf16_ps_broadcast_rhs:     # @iree_mm512_dpbf16_ps_broadcast_rhs
        vdpbf16ps       zmm0, zmm1, dword ptr [rdi]{1to16}
        ret
```

@RKSimon @alexey-bataev

**Comment by RKSimon** [comment]
@phoebewang How are vdpbf16ps broadcast folds supposed to work?

The intel docs suggests they are 32-bit broadcasts of 2 x bf16 pairs - is that the correct interpretation?
```
EVEX.512.F3.0F38.W0 52 /r
VDPBF16PS zmm1{k1}{z}, zmm2, zmm3/m512/m32bcst
```

But the tablegen has this:
```
  defm mb: AVX512_maskable_3src<opc, MRMSrcMem, _, (outs _.RC:$dst),
                  (ins src_v.RC:$src2, f32mem:$src3),
                  OpcodeStr,
                  !strconcat("${src3}", _.BroadcastStr,", $src2"),
                  !strconcat("$src2, ${src3}", _.BroadcastStr),
                  (_.VT (OpNode _.RC:$src1, src_v.RC:$src2,
                  (src_v.VT (src_v.BroadcastLdFrag addr:$src3))))>,
                  EVEX_B, EVEX_4V, Sched<[sched.Folded, sched.ReadAfterFold]>;
```
Add src_v is from avx512vl_bf16_info

**Comment by phoebewang** [comment]
Seem incorrect. It's changed by https://github.com/llvm/llvm-project/commit/bc1819389fb47
Where I changed
```
@@ -12902,7 +12945,7 @@ multiclass avx512_dpbf16ps_rm<bits<8> opc, string OpcodeStr, SDNode OpNode,
                                Sched<[sched.Folded, sched.ReadAfterFold]>;

   defm mb: AVX512_maskable_3src<opc, MRMSrcMem, _, (outs _.RC:$dst),
-                  (ins src_v.RC:$src2, src_v.ScalarMemOp:$src3),
+                  (ins src_v.RC:$src2, f32mem:$src3),
                   OpcodeStr,
                   !strconcat("${src3}", _.BroadcastStr,", $src2"),
                   !strconcat("$src2, ${src3}", _.BroadcastStr),
@@ -12930,7 +12973,7 @@ multiclass avx512_dpbf16ps_sizes<bits<8> opc, string OpcodeStr, SDNode OpNode,

 let ExeDomain = SSEPackedSingle in
 defm VDPBF16PS : avx512_dpbf16ps_sizes<0x52, "vdpbf16ps", X86dpbf16ps, SchedWriteFMA,
-                                       avx512vl_f32_info, avx512vl_i32_info,
+                                       avx512vl_f32_info, avx512vl_bf16_info,
                                        HasBF16>, T8XS, EVEX_CD8<32, CD8VF>;
```
`avx512vl_i32_info` into `avx512vl_bf16_info`.
I thought it makes more sense to represent in `N x bf16`, though it's actually `M x 2 x bf16`. I didn't notice it will make the broadcast patten invalid.
Maybe it's not proper to change it back to `i32` because we have upgraded it once. Is it possible to update the pattern to achieve it?

**Comment by RKSimon** [comment]
Yes, we might need to drop the pattern and just handle it in X86InstrInfo::foldMemoryOperandCustom, and maybe llvm::lookupBroadcastFoldTable?

**Comment by AngryLoki** [comment]
@bjacob , was the issue fixed? At this moment your testcase link https://godbolt.org/z/xsGGsov5W produces the same result for Clang trunk (i. e. no vbroadcastss).

**Comment by RKSimon** [comment]
@KanRobert - do you have any suggestions on how best to handle this in the fold tables please?

**Comment by phoebewang** [comment]
Doesn't the trunk handle it correctly already? I'm not sure which patch solves it though.

**Comment by RKSimon** [comment]
> @KanRobert - do you have any suggestions on how best to handle this in the fold tables please?

Sorry - this looks to have been fixed in trunk already, as long as we have test coverage I expect this can be closed

**Comment by KanRobert** [comment]
> Doesn't the trunk handle it correctly already? I'm not sure which patch solves it though.

I think it's solved by https://github.com/llvm/llvm-project/pull/79761. Before https://github.com/llvm/llvm-project/commit/bc1819389fb47 the broadcast variant should be generated by pattern instead of peephole optimization.

**Comment by KanRobert** [comment]
> @KanRobert - do you have any suggestions on how best to handle this in the fold tables please?


> @KanRobert - do you have any suggestions on how best to handle this in the fold tables please?
In the fold tables, the corresponding entry is `{X86::VDPBF16PSZr, X86::VDPBF16PSZmb, TB_BCAST_SS}`, no special handling there and just treat it as a `f32`.

**Comment by bjacob** [comment]
Thanks, all!
