### ISSUE TITLE
pacg Instructin instrumentation with llvm back-end (llc)

### ISSUE THREAD

**Issue by Tomal-kuet** [llvm/llvm-project#68831]
I am trying to instrument **pacg** instruction with llvm back-end with the following code:
```
MIB = BuildMI(MBB, MI, DL, TII.get(ARM::t2PACG)).addReg(ARM::R1).addReg(ARM::R0).addReg(ARM::R2)
    .add(predOps(ARMCC::AL)).setMIFlag(MachineInstr::NoFlags);
```
From, the ARMInstrThumb2.td file the definition for **pacg** is:
```
// PACBTI
let Predicates = [IsThumb2, HasV8_1MMainline, HasPACBTI] in {
def t2PACG : V8_1MI<(outs rGPR:$Rd),
                    (ins pred:$p, GPRnopc:$Rn, GPRnopc:$Rm),
                    AddrModeNone, NoItinerary, "pacg${p}", "$Rd, $Rn, $Rm", "", []> {
  bits<4> Rd;
  bits<4> Rn;
  bits<4> Rm;
  let Inst{31-20} = 0b111110110110;
  let Inst{19-16} = Rn;
  let Inst{15-12} = 0b1111;
  let Inst{11-8}  = Rd;
  let Inst{7-4}   = 0b0000;
  let Inst{3-0}   = Rm;
}
```
I get the following error:
```
llc: ../llvm-project/llvm/include/llvm/MC/MCInst.h:81: int64_t llvm::MCOperand::getImm() const: Assertion `isImm() && "This is not an immediate"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: llc -march=arm -mcpu=cortex-m85 out.ll -o outm_pass.s
1.	Running pass 'Function Pass Manager' on module 'out.ll'.
2.	Running pass 'ARM Assembly Printer' on function '@factorial'
```
The **pacg** instruction of ARMv8.1-M works with three general-purpose registers, why the ARM Assembly Printer pass is asserting for immediate?
I also printed the textual assembly from LLVM IR which shows as: `t2PACG $r1, $r0, $r2, 14, $noreg`
I guess there is something wrong with the parameters of BuildMI, please suggest to me your valuable thoughts. Thank you.

**Comment by vhscampos** [comment]
@Tomal-kuet can you try with the predicate being the first input operand? I.e.:
`MIB = BuildMI(MBB, MI, DL, TII.get(ARM::t2PACG)).addReg(ARM::R1)..add(predOps(ARMCC::AL))addReg(ARM::R0).addReg(ARM::R2).setMIFlag(MachineInstr::NoFlags);`

In the instruction's definition, the predicate operand does not come last.
