### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by david-c-coder** [llvm/llvm-project#68864]
it seems that clang does not allow to define variable after switch() case:
 
                case ID_QueryButton:
                    ;  //add an empty statement here to fix the problem.
                    int i = 0;  //It seems that clang does not allow to define variable after case:

**Comment by ecnelises** [comment]
This is not a bug. See https://stackoverflow.com/a/19830820

Another approach is to add scope with braces:

```c
case D_QueryButton: {
  int i = 0;
  // ...
}
```

**Comment by david-c-coder** [comment]
> This is not a bug. See https://stackoverflow.com/a/19830820
> 
> Another approach is to add scope with braces:
> 
> ```c
> case D_QueryButton: {
>   int i = 0;
>   // ...
> }
> ```
Thank you very much!
