### ISSUE TITLE
NTTP references in requires clauses

### ISSUE THREAD

**Issue by cor3ntin** [llvm/llvm-project#68885]
Clang rejects this code

```cpp
#include <concepts> 
template <decltype(auto) a>
struct S {
    static constexpr int i = 42;
};

template <decltype(auto) a>
requires true
struct S<a> {
    static constexpr int i = 0;
};

static constexpr int a = 0;

void test() {
    static_assert(S<a>::i == 0);  // Ok
    static_assert(S<(a)>::i == 0); // Fails
}

```

https://godbolt.org/z/hsb4c5WE3 

Clang picks the primary template when a NTTP is a reference type, even if there is a more constrained specialization.
Other compiler accept this code.

**Comment by cor3ntin** [comment]
@erichkeane Maybe you would have an idea

**Comment by cor3ntin** [comment]
I spent some time looking at this but I'm stuck.
I found this other related bug, which is an ill-formed program clang fails to diagnose https://godbolt.org/z/G8nWKfsPK 

```
template <decltype(auto) a>
struct S {
    static constexpr int i = 42;
};

template <decltype(auto) a>
struct S<a> {
    static constexpr int i = 0;
};```


The issue is there are places where we are trying to deduce the type of `a` where we should not.
Weaving whether we are checking a partial specialization or not through SemaTemplateDeduction may be how we fix this but this seems rather involved.

ideas welcomed.

**Comment by erichkeane** [comment]
Instead of 'weaving', perhaps some level of RAII object storing the state?  Alternatively, do we have access to the Decl yet?  If so, you could always see if it is a `ClassTemplatePartialSpecializationDecl`.  There is perhaps similar work in the calls to `isAtLeastAsSpecializedAs`/`getMoreSpecialized` that you might be able to use?  

Also, there is `TemplateDeductionFlags` that might be of interest?

**Comment by cor3ntin** [comment]
```cpp
template <decltype(auto) a>
constexpr int i = 42;

template <decltype(auto) a> requires true
constexpr int i<a> = 1;
                            ^-  becomes   DeclRef(test), type int

static constexpr int test = 0;
 i<(test)>;

```

Given this example, `(test)` ends up being substituted by `0` in `ConvertDeducedTemplateArgument`.
This is because we drop all reference-ness information from the `DeclRefExpr` created for deduced argument of the partial specialization.

We should probably create a `SubstNonTypeTemplateParmExpr` for the partial specialization argument (as afaik, this is the only way to recover a reference to a NTTP during deduction for the partial specialization argument), but I have so far been unable to do so.

Subsequently, `FinishTemplateArgumentDeduction` fails because we try to check that the literal 0 is the same argument as the `test` value decl.

I've spent a few days lost into the `DeduceTemplateArguments` maze, I would really appreciate some guidance here, because I seem stuck!

@erichkeane @zygoloid
