### ISSUE TITLE
[MLIR] `createOrFold`-created ops has null block when accessing folder

### ISSUE THREAD

**Issue by mortbopet** [llvm/llvm-project#68884]
Submitting as an issue, since this seems like a bug to me;

When an operation is created through `createOrFold`, the operation will
1. first be created
2. attempted folded
3. inserted into the block

https://github.com/llvm/llvm-project/blob/f89b7a9ee205acbd6c180cc56ea5a74f8602d269/mlir/include/mlir/IR/Builders.h#L515-L518

One may have a folder which also looks at the `mlir::Block`s where e.g. the operands of the newly created operation resides, and compare this wrt. the `mlir::Block` that the newly created operation resides in. This - to me - shouldn't violate any existing constraints (e.g. IsolatedFromAbove, local transformation, ...) since we're just looking across blocks.   

However, this may result in a folder not applying, seeing as, in step 2, when an op is created through `createOrFold`, the `block` of an op is still a `nullptr` when the fold method is run - given that the `block` pointer of an op is updated in step 3, after folding failed.

Another hypothetical issue along the lines of this is if a folder for some reason has the op block iterator as load bearing (e.g. relative position wrt. other ops); this, as well, is not assigned until after the op is inserted.

Solutions could be that , `createOrFold` pre-emptively assign the `block` pointer the op in-between step 1 and 2 (wouldn't fix the block iterator issue) or that we "fully" create an operation (e.g. insert it into the block) before applying the folder method (which then may remove it from the block again).

**Comment by mortbopet** [comment]
CC for visibility @joker-eph @River707 @teqdruid.

**Comment by joker-eph** [comment]
> Solutions could be that , createOrFold pre-emptively assign the block pointer the op in-between step 1 and 2

This would be breaking some invariants (having a parent without being inserted?) which has me concerned.

> or that we "fully" create an operation (e.g. insert it into the block) before applying the folder method (which then may remove it from the block again).

Seems more reasonable, do you want to try a patch for this?

**Comment by mortbopet** [comment]
> > or that we "fully" create an operation (e.g. insert it into the block) before applying the folder method (which then may remove it from the block again).

> Seems more reasonable, do you want to try a patch for this?

I can do that. My main concern with that, however, would be pushback from the (presumed) very fact of why this change was introduced in the first place - as an optimization. But obviously, correctness must come first.

**Comment by mortbopet** [comment]
Hacking, away:

To facilitate this change, it's required to:
1. Properly insert the operation into the block (i.e. use the `create` call in the OpBuilder).
2. Due to the above, properly erase the operation from the builder - which in turn requires the Listener to also be capable of notifying that operations have been removed (i.e. moving `notifyOperationRemoved` up from [`RewriterBase::Listener`](https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/IR/PatternMatch.h#L427) to [`OpBuilder::Listener`](https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/IR/Builders.h#L295)).
3. ... and as an extension of that, OpBuilder needs proper operation erasure support in general, i.e. moving or reimplementing [`RewriterBase::eraseOp`](https://github.com/llvm/llvm-project/blob/main/mlir/lib/IR/PatternMatch.cpp#L306) in OpBuilder.

2 and 3 may be contentious since they break with the notion that an OpBuilder and its associated classes are strictly used for constructing ops.

If we still want that to be the case, then I don't see a way for `OpBuilder` to implement `createOrFold` since it'll all of these "proper" operation deletion capabilities; in other words, `createOrFold` could be moved to `RewriterBase` which already does operation erasure.

AFAICT, there's roughly a 50/50 split in upstream MLIR and [CIRCT](https://github.com/llvm/circt) wrt. whether `createOrFold` is used with a `PatternRewriter` or an `OpBuilder`. I'd personally be in favor of keeping it in `RewriterBase` to maintain the strict notion that `OpBuilder` always only creates ops, and never deletes, and refactor accordingly.

**Comment by joker-eph** [comment]
How is op creation tracked right now?

**Comment by joker-eph** [comment]
What about:

```
    // Create the operation without using 'create' as we don't want to
    // notify about the insertion yet.
    OperationState state(location,
                         getCheckRegisteredInfo<OpTy>(location.getContext()));
    OpTy::build(*this, state, std::forward<Args>(args)...);
    Operation *op = Operation::create(state);
    if (block)
      block->getOperations().insert(insertPoint, op);

    // Fold the operation. If successful destroy it, otherwise notify about the insertion.
    if (succeeded(tryFold(op, results)))
      op->erase();
    else
      listener->notifyOperationInserted(op);
```

**Comment by mortbopet** [comment]
Yea, this was exactly the thing that dawned upon my after a while...
