### ISSUE TITLE
C++20 reversed operator== not properly suppressed by operator!= in namespace

### ISSUE THREAD

**Issue by jyknight** [llvm/llvm-project#68901]
```cpp
namespace N {
  struct A {};
  bool operator==(A, int);
  bool operator!=(A, int);
}
bool a = 0 == N::A();
```

This should fail to compile, because the existence of `operator!=` should suppress the reversed `operator==(int, A)`. However, on Clang it does not.

Moving `bool a` within the namespace does make it correctly fail to compile, which suggests that name lookup for the operator!= is not being done in the correct scope.

@usx95

**Comment by usx95** [comment]
Same issue but this errors instead:

```cpp
namespace A {
struct Derived {};
struct Base : Derived {};

bool operator==(Derived& a, Base& b);
bool operator!=(Derived& a, Base& b);
}  // namespace A

void foo() {
    A::Base a, b;
    (void)(a == b);
}
```
https://godbolt.org/z/xvEjrEYre
