### ISSUE TITLE
clang/lib/Sema/SemaChecking.cpp:6050:39: warning: Logical disjunction always evaluates to true

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#68958]
Static analyser cppcheck says:

trunk/clang/lib/Sema/SemaChecking.cpp:6050:39: warning: Logical disjunction always evaluates to true: ArgExtValue >= 0 || ArgExtValue <= 7. [incorrectLogicOperator]

Source code is

    assert((ArgExtValue >= TileRegLow || ArgExtValue <= TileRegHigh) &&
           "Incorrect tile register num.");

**Comment by dtcxzyw** [comment]
`ArgExtValue >= 0 || ArgExtValue <= 7` always evaluates to true. The static analyzer is right.
I think the correct assertion should be:
```
assert((ArgExtValue >= TileRegLow && ArgExtValue <= TileRegHigh) &&
       "Incorrect tile register num.");
```

**Comment by dcb314** [comment]
Why has this bug report been closed ? Has the fix already gone in ?

**Comment by dtcxzyw** [comment]
Apologize for my misunderstanding. I will fix it soon.

**Comment by dtcxzyw** [comment]
Fixed. Nice catch!
