### ISSUE TITLE
[runtime] Incorrect output with -ffast-math

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#68976]
* test: ~/test » cat test.cpp
```
#include <array>
#include <cmath>
#include <limits>
#include <cstdio>
 
int main()
{
    std::array<double, 4> vals;
    std::fill(vals.begin(), vals.end(), 0.0f);
    vals.back() = std::numeric_limits<double>::infinity();
    printf("vals.back(): %f\n", vals.back());
}
```

* output with newest llvm commit **434b8a3080**:
```
~/test » ~/llvm-project-upstream/build/bin/clang test.cpp -O3 -std=c++17 &&  ./a.out
vals.back(): inf
------------------------------------------------------------
~/test » ~/llvm-project-upstream/build/bin/clang test.cpp -O3 -std=c++17 -ffast-math  &&  ./a.out
vals.back(): 0.000000    --- unexpected result
------------------------------------------------------------
~/test » g++  test.cpp -O3 -std=c++17 -ffast-math &&  ./a.out
vals.back(): inf
```

**Comment by dtcxzyw** [comment]
I cannot reproduce this issue with the trunk version of Clang on my x86-64 machine (revision: 7755cdf03d2f2dce652398ada012377186c292d3).
Godbolt: https://godbolt.org/z/z7rrzdz7z

BTW, the flag `-ffast-math` implies `-ffinite-math-only`, which assumes arguments and results are not NaNs or +-Inf.
See also https://clang.llvm.org/docs/UsersManual.html#cmdoption-ffast-math.

**Comment by vfdff** [comment]
> I cannot reproduce this issue with the trunk version of Clang on my x86-64 machine (revision: [7755cdf](https://github.com/llvm/llvm-project/commit/7755cdf03d2f2dce652398ada012377186c292d3)). Godbolt: https://godbolt.org/z/z7rrzdz7z
> 
> BTW, the flag `-ffast-math` implies `-ffinite-math-only`, which assumes arguments and results are not NaNs or +-Inf. See also https://clang.llvm.org/docs/UsersManual.html#cmdoption-ffast-math.

thanks @dtcxzyw, so it is a UB behavior, I'll close it

**Comment by arsenm** [comment]
The patch that triggered the behavior was reverted, so that's why you don't see it. It should probably be resubmitted although it does look surprising
