### ISSUE TITLE
clang/lib/Format/WhitespaceManager.cpp:1426:sanity check in wrong place ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#69047]
Static analyser cppcheck says:

clang/lib/Format/WhitespaceManager.cpp:1426:23: style: Array index 'j' is used before limits check. [arrayIndexThenCheck]

Source code is

       while (Changes[j].Tok != NextNonComment && j < End)
          ++j;

Suggest move sanity check to before use.

**Comment by owenca** [comment]
Looks like a false alarm to me: `j` is initialized to `i`, which is already limit-checked.

**Comment by dcb314** [comment]
The issue is style, not performance. 

Sanity checking after use may well work in this case, but it is bad style.
