### ISSUE TITLE
Clang-format leaves an extra newline between member initializations in the constructor initialization list.

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#69051]
with
```
class MyClass {
private:
  int member1;
  double member2;

public:
  MyClass(int m1, double m2)
      : member1(m1),

        member2(m2) {}
};

```

With
```
$ clang-format foo.cpp
```
it returns the same thing, but I think it should generate:
```
  MyClass(int m1, double m2)
      : member1(m1),
        member2(m2) {}
};
```

**Comment by owenca** [comment]
You need to set `MaxEmptyLinesToKeep` to 0.

**Comment by sylvestre** [comment]
`MaxEmptyLinesToKeep: 0` reformats way more things

**Comment by owenca** [comment]
clang-format determines if empty lines are intentional by `MaxEmptyLinesToKeep`, so the user has to delete unwanted empty lines below the limit.
