### ISSUE TITLE
Simplification for `(~a & b) && ~a`

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#69050]
GCC outputs the same sequence of instructions for the following two functions. Clang doesn't simplify the function `foo`. The transformation from `foo` to `bar` can be proved.
```cpp
int foo(int a, int b)
{
   return (~a & b) && ~a;
}

int bar(int a, int b)
{
   return (~a & b) && b;
}
```

Godbolt: https://godbolt.org/z/1cfP7Y5x6
Alive2: https://alive2.llvm.org/ce/z/HDJVkD

**Comment by dtcxzyw** [comment]
I guess it will be fixed by further improvement of #69840 by handling more complicated expressions than binops.
