### ISSUE TITLE
`<algorithm>`: `ranges::find_if_not`'s help lambda should return `bool`

### ISSUE THREAD

**Issue by hewillk** [llvm/llvm-project#69074]
https://github.com/llvm/llvm-project/blob/8dd3bc18081657fee2352cf5b1c6abacb18fcc84/libcxx/include/__algorithm/ranges_find_if_not.h#L46-L51

The lambda here should specify the return type as `bool`, such as `[&](auto&& __e) -> bool` because the type that satisfies _`boolean-testable`_ does not necessarily have to be `bool`:

```cpp
#include <algorithm>

const struct Boolean {
  Boolean() = default;
  Boolean(Boolean&&) = delete;
  operator bool() const;
  const Boolean& operator!() const;
} boolean;

#ifdef __clang__
static_assert(std::__boolean_testable<Boolean>);
#endif

int main() {
  // libc++ rejects
  auto it = std::ranges::find_if_not(" ", [&](char) -> auto& { return boolean; });
}
```
https://godbolt.org/z/4M15cvarx

**Comment by philnik777** [comment]
Did you encounter this in real code?

**Comment by hewillk** [comment]
> Did you encounter this in real code?

No, just like I have never encountered an iterator that overloads the comma operator in real life.
This example is highly artificial.

**Comment by ldionne** [comment]
I suspect @philnik777 was asking out of curiosity. I agree this is kinda pedantic but it's worth fixing.

**Comment by hewillk** [comment]
> I suspect @philnik777 was asking out of curiosity. I agree this is kinda pedantic but it's worth fixing.

I believe there are helper lambdas like this in libc++, such as `ranges::max` ([demo](https://godbolt.org/z/fexMa5e54)). 
Should we open a specific issue to address these issues or do we need to open a new one each time?

**Comment by ldionne** [comment]
I think we could/should tackle all of them via this issue and https://github.com/llvm/llvm-project/pull/69378.

Can you think of a good way to find all of them? I guess we need to look at all the ranges algorithms that take a predicate, since they all expect the predicate to return a `boolean-testable`?

**Comment by hewillk** [comment]
> I think we could/should tackle all of them via this issue and #69378.
> 
> Can you think of a good way to find all of them? I guess we need to look at all the ranges algorithms that take a predicate, since they all expect the predicate to return a `boolean-testable`?

Sadly that seems to be the case. 
I think this situation *mostly* occurs when creating a helper lambda in the form of `[&](auto&& lhs, auto&& rhs) { return some-boolean-expression; }`.
In addition to `<algorithm>`, we may also need to check whether there is such a lambda in `<ranges>` as range adaptors can also accept predicate and `sentinel_for` and `random_access_iterator` both imply `boolean-testable`.

**Comment by ldionne** [comment]
> Sadly that seems to be the case. I think this situation _mostly_ occurs when creating a helper lambda in the form of [`[&](auto&& lhs, auto&& rhs) { return some-boolean-expression; }`](https://github.com/llvm/llvm-project/blob/5557d983412c2e8cdffaf855463098f7771f6499/libcxx/include/__algorithm/make_projected.h#L99).

I was looking at what we do in `__make_projected` and I *think* it is conforming. Mandated RVO kicks in and it's really as-if we used

```
std::invoke(__comp,
            std::invoke(__proj1, std::forward<decltype(__lhs)>(__lhs)),
            std::invoke(__proj2, std::forward<decltype(__rhs)>(__rhs)))
```

directly in the calling algorithm. Are you able to find a case where e.g. `ranges::set_difference` fails with a conforming `boolean-testable`?

**Comment by ldionne** [comment]
> I think this situation _mostly_ occurs when creating a helper lambda in the form of [`[&](auto&& lhs, auto&& rhs) { return some-boolean-expression; }`](https://github.com/llvm/llvm-project/blob/5557d983412c2e8cdffaf855463098f7771f6499/libcxx/include/__algorithm/make_projected.h#L99).

Are you sure that isn't valid? I think mandatory RVO kicks in and we end up never calling a constructor here in

```
return std::invoke(__comp,
                   std::invoke(__proj1, std::forward<decltype(__lhs)>(__lhs)),
                   std::invoke(__proj2, std::forward<decltype(__rhs)>(__rhs)));
```

Are you able to come up with a conforming call to e.g. `std::ranges::set_difference` with a custom boolean-testable that makes us fail?

I did a full survey of everything in `<ranges>` and `<algorithm>` and I think we're in the clear, except the following headers which contain patterns like the above (we need to determine whether that's conforming):

```
libcxx/include/__algorithm/ranges_max_element.h
libcxx/include/__algorithm/ranges_max.h
libcxx/include/__algorithm/ranges_remove_copy.h
libcxx/include/__algorithm/ranges_remove.h
libcxx/include/__algorithm/ranges_replace_copy.h
libcxx/include/__algorithm/ranges_replace.h
```

**Comment by hewillk** [comment]
> Are you able to find a case where e.g. ranges::set_difference fails with a conforming boolean-testable?

Yes, I can find it. https://godbolt.org/z/sPzo6o565

**Comment by hewillk** [comment]
> we may also need to check whether there is such a lambda in <ranges> as range adaptors can also accept predicate and sentinel_for and random_access_iterator both imply boolean-testable.

The following test is the `sentinel_for` part I am referring to, using `ranges::uninitialized_copy` as an example: https://godbolt.org/z/ndxGd48hT

**Comment by ldionne** [comment]
@hewillk I just updated https://github.com/llvm/llvm-project/pull/69378. I think that version of the patch should handle everything. Would you like to take a look?

**Comment by hewillk** [comment]
> @hewillk I just updated #69378. I think that version of the patch should handle everything. Would you like to take a look?

LGTM. Thanks.
