### ISSUE TITLE
[libc++] `ranges::copy(join_view, out)` isn't constexpr

### ISSUE THREAD

**Issue by philnik777** [llvm/llvm-project#69083]
```c++
#include <algorithm>
#include <ranges>
#include <vector>

constexpr auto test(std::vector<std::vector<int>> v, int* out) {
  std::ranges::copy(v | std::views::join, out);
}

static_assert([] {
  int a[4] = {};
  test({{1, 2}, {3, 4}}, a);
  return true;
}());
```

Is rejected by libc++ because the `_CopySegment` helper isn't `constexpr`.

**Comment by Rajveer100** [comment]
@philnik777 
Hey, I am actually new to contributing to LLVM, can you give a head start on this to get me going!
For more info about me, please checkout my GitHub profile and other projects!

I have gone through the initial guidelines and setup and have done the basic clone and build steps, though, I am not exactly sure to how we can debug and reproduce issues, it is similar to the way contributing works for swift?

**Comment by philnik777** [comment]
You have to add `-fexperimental-library` to get `views::join`. Then you should get an error about a function not being `constexpr`.

**Comment by Rajveer100** [comment]
Makes sense, also I presume LLVM has now potentially migrated to GitHub?

**Comment by philnik777** [comment]
Yes, you can open a PR against this repo now.

**Comment by Rajveer100** [comment]
Ok, I added the `main` function, fixed.

**Comment by Rajveer100** [comment]
Well, now I reproduced the issue using:

`clang++ -stdlib=libc++ -fexperimental-library debug.cpp -o debug`

**Comment by Rajveer100** [comment]
Well, the `main` function wasn't the issue, I passed `-stdlib=libc++`, and now I get this:

```Shell
clang++ -fexperimental-library -stdlib=libc++ debug.cpp -o debug


debug.cpp:5:1: error: unknown type name 'constexpr'
constexpr auto test(std::vector<std::vector<int>> v, int* out) {
^
debug.cpp:5:48: error: a space is required between consecutive right angle brackets (use '> >')
constexpr auto test(std::vector<std::vector<int>> v, int* out) {
                                               ^~
                                               > >
debug.cpp:5:11: error: illegal storage class on function
constexpr auto test(std::vector<std::vector<int>> v, int* out) {
          ^
debug.cpp:6:8: error: no member named 'ranges' in namespace 'std'
  std::ranges::copy(v | std::views::join, out);
  ~~~~~^
debug.cpp:6:30: error: no member named 'views' in namespace 'std'
  std::ranges::copy(v | std::views::join, out);
                        ~~~~~^
debug.cpp:9:15: error: expected expression
static_assert([] {
              ^
debug.cpp:13:3: error: expected unqualified-id
}());
  ^
7 errors generated.
```

**Comment by Rajveer100** [comment]
> Linker Command Failed:
> 
> 
> 
> ```C++
> 
> clang++ -std=c++20 -fexperimental-library debug.cpp -o debug
> 
> ld: warning: ignoring file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libc++experimental.a[arm64e][3](format.cpp.o)': found architecture 'arm64e', required architecture 'arm64'
> 
> ld: warning: ignoring file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libc++experimental.a[arm64e][2](memory_resource.cpp.o)': found architecture 'arm64e', required architecture 'arm64'
> 
> ld: Undefined symbols:
> 
>   _main, referenced from:
> 
>       <initial-undefines>
> 
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> ```
> 
> 
> 
> PS: Adding `main` function fixed it.

@philnik777 
In my case the `code snippet` is successfully compiling, am I missing anything here?

**Comment by philnik777** [comment]
Are you compiling against your system library or against trunk libc++? And what code did you use exactly?

**Comment by Rajveer100** [comment]
This is the command I used:

```Shell
clang++ -std=c++20 -fexperimental-library debug.cpp -o debug
```

Since I had no issues with compilation, I thought maybe I am not using the `libc++` specific to `llvm` and probably the default system `clang config` might be getting triggered. 

Was digging through [setup](https://llvm.org/docs/GettingStarted.html#getting-started-with-llvm), I probably haven't configured `llvm` correctly as mentioned this way:

```Shell
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=<type> -DCMAKE_INSTALL_PREFIX=/install/path
```

**Comment by philnik777** [comment]
Did you build the clang version yourself? Also, you might have to add `-stdlib=libc++` depending on which system you're on.

**Comment by philnik777** [comment]
Then you're testing the system libc++ and not the trunk one. This is probably a regression.

**Comment by Rajveer100** [comment]
How do I test the regression?

**Comment by philnik777** [comment]
You'll have to use a trunk libc++. You can see the regression [here](https://godbolt.org/z/x6rx5rf74). See https://libcxx.llvm.org/BuildingLibcxx.html#id3 for how to build libc++.

**Comment by Rajveer100** [comment]
> Warning
If your operating system already provides libc++, it is important to be careful not to replace it. Replacing your system’s libc++ installation could render it non-functional. Use the CMake option CMAKE_INSTALL_PREFIX to select a safe place to install libc++.

What's the right way to avoid any such issues?

**Comment by Rajveer100** [comment]
For now I have created a directory `trunk-build` in `llvm-project/` and have done the installation successfully, although few `tests` had failed for `#Test` command in the instructions, hope that isn't an issue.

**Comment by Rajveer100** [comment]
Command:

```Shell
clang++ -std=c++20 -fexperimental-library -DCMAKE_CXX_COMPILER=$HOME/Desktop/llvm/llvm-project/trunk-build/include/c++ debug.cpp -o debug
```

Still compiles successfully, no errors.

**Comment by ldionne** [comment]
The easiest way to get started with a build + test of the library would be to do something like:

```
./libcxx/utils/ci/run-buildbot generic-cxx23
```

This will build the library and run the tests in C++23 mode. Then you can add some tests for `copy` / `join_view`, run `ninja -C build/generic-cxx23 check-cxx` and see those tests failing. Then you can fix the issue and run it again, it should pass.

**Comment by Rajveer100** [comment]
So installation of `libc++` `trunk-build` (the new directory that I created) was not needed?

Also, once I make the changes, can I just target a particular `test` file associated with my change rather than running all `tests`?

**Comment by ldionne** [comment]
> Once I make the changes, can I just target a particular `test` file associated with my change rather than running all `tests`?

Yes! See https://libcxx.llvm.org/TestingLibcxx.html#usage.

**Comment by mordante** [comment]
@philnik777 I see some commit for this issue. Has it been fixed?

**Comment by philnik777** [comment]
Yes.
