### ISSUE TITLE
Simplification Comparison (Clang9 vs Clang trunk)

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#69091]
Consider the following function:
```cpp
bool foo(int a, int b)
{
   return (a + 1) || (a * b + b);
}
```
Clang9 (and GCC) can simplify `foo`, but Clang trunk cannot.
https://godbolt.org/z/nTj67b956

**Comment by dtcxzyw** [comment]
I guess it will be fixed by further improvement of #69840 by handling more complicated expressions instead of binops.
