### ISSUE TITLE
[clangd] "Find all references" reports an off-by-one-line location

### ISSUE THREAD

**Issue by Endilll** [llvm/llvm-project#69166]
When searching for all references of `clang::TypeAlignment` declared in `Type.h`, clangd reported wrong location for the (sole) result from `SemaType.cpp`. In the following snippet, `sizeof(LocInf` is highlighted as a result of the search instead of `TypeAlignment`:
https://github.com/llvm/llvm-project/blob/5857fec27fe8ee5a48a2ee48a4d79a9e39b0332b/clang/lib/Sema/SemaType.cpp#L6687-L6688

I'm using VS Code 1.83.0 with clangd extension version 0.1.24.

**Comment by HighCommander4** [comment]
This is usually a symptom of clangd's index being slightly out of date.

Does restarting clangd fix it?

**Comment by Endilll** [comment]
It indeed helps. Thank you!
