### ISSUE TITLE
[llvm-debuginfo-analyzer] Add support for WebAssembly binary format.

### ISSUE THREAD

**Issue by CarlosAlbertoEnciso** [llvm/llvm-project#69181]
Extracted from [llvm/tools/llvm-debuginfo-analyzer/README.txt](https://github.com/llvm/llvm-project/blob/main/llvm/tools/llvm-debuginfo-analyzer/README.txt)
https://github.com/llvm/llvm-project/issues/57040#issuecomment-1211336680

Add support for `WebAssembly` binary format.

**Comment by dschuff** [comment]
@llvm/issue-subscribers-backend-webassembly
