### ISSUE TITLE
[bugpoint] Add option for external diff script

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#693]
|  |  |
| --- | --- |
| Bugzilla Link | [321](https://llvm.org/bz321) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lattner |

## Extended Description 
Too often we want to debug programs whose output is not on stdout, but in a
file, or, worse, in multiple files. The current incarnation of bugpoint is not
suitable for debugging such programs, which, unfortunately, makes it useless for
debugging miscompilation in SPEC benchmarks.

Proposed solution (after discussion with Chris and Brian) is to teach bugpoint
to use an external diff script to diff results of program runs (instead of
diffing stdout and a single "correct output" file), and rely on its exit code to
judge whether a program did what it was supposed to do.

**Comment by arsenm** [comment]
bugpoint has had custom scripts for ages you can diff whatever you want in. Also llvm-reduce only works that way
