### ISSUE TITLE
[Flang] Stop using deprecated typed pointers

### ISSUE THREAD

**Issue by Dinistro** [llvm/llvm-project#69303]
LLVM fully dropped typed pointer support a while ago, but the Flang LLVM dialect lowering still generates typed pointers. This works, because MLIR's LLVM dialect supports typed and opaque pointers and just removes the types when exporting to LLVM IR.

Sadly, supporting both pointer kinds complicates a lot of logic in the dialect, including it's lowering. Thus, @zero9178 pushed on this in February 2023 and switched most (if not all) lowerings to opaque pointers (some revisions were linked bellow). If I'm not mistaken, he even attempted to migrate Flang as well, but apparently non-trivial changes will be necessary to succeed with this.

I'm mainly creating this issue because I wasn't able to find any discussion on this and because this change is long overdue.

Some revisions that moved lowerings to opaque pointers:
https://reviews.llvm.org/D143583
https://reviews.llvm.org/D143608
https://reviews.llvm.org/D143661
https://reviews.llvm.org/D143582
https://reviews.llvm.org/D143853
https://reviews.llvm.org/D143855

**Comment by jeanPerier** [comment]
Hi @Dinistro, thanks for opening the discussion here. Was there any draft patches of @zero9178 attempt to modify FIR lowering to LLVM dialect, or do you know what turned out to be non-trivial? It would help as a starting point.

**Comment by zero9178** [comment]
> Hi @Dinistro, thanks for opening the discussion here. Was there any draft patches of @zero9178 attempt to modify FIR lowering to LLVM dialect, or do you know what turned out to be non-trivial? It would help as a starting point.

Hello @jeanPerier! Thank you for your response. I did not post any draft patches back then as I sadly failed to find the time to get it on a good shape. I recently got access back to the computer where I stored them and have uploaded the last state here: https://gist.github.com/zero9178/670c8f7c0ae2d443ea7b22e40d0180b2
Note that these are back from February so unlikely to still apply cleanly and in need of a rebase.

I looked through the history again and the part that was non-trivial to me as an outsider was the lowering of `fir.dispatch` here: https://github.com/llvm/llvm-project/blob/16bd0fe56c386de0bed33e3a29d6a4c5c6dc009e/flang/lib/Optimizer/CodeGen/CodeGen.cpp#L1034-L1056
Using opaque pointers requires the type to be loaded to be passed as parameter and not deduced from the pointer element type and it was not obvious to me through the large type hierachy in Flang + the different kinds of type conversions what the various element types in the `load` and GEP ops should be.
Besides that I don't remember having any other issues besides getting stuck on the code there.

I wrote a detailed guide how to switch to opaque pointers here https://discourse.llvm.org/t/psa-in-tree-conversion-passes-can-now-be-used-with-llvm-opaque-pointers-please-switch-your-downstream-projects/68738 in case it helps.

**Comment by jeanPerier** [comment]
Thanks very much for this very detailed answer and guide! I will try to get that rolling.

**Comment by jeanPerier** [comment]
I created to https://github.com/llvm/llvm-project/pull/69692 to update flang to use opaque pointers. However, I cannot merge it until OpenMP MLIR dialect is updated to not rely on llvm dialect type pointers.  OpenMP codegen to LLVM gets some of its input from lowered FIR operations in the Fortran flow.

Here is an example where OpenMP relies on typed pointer in MLIR directory: https://github.com/llvm/llvm-project/blob/54881c9225e612830a9e78574a805309b516627b/mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp#L1542. I think this at least impact the map info lowering to LLVM.

@TIFitis or @kiranchandramohan, can I ask you to take on the task in the OpenMP dialect directory?

**Comment by kiranchandramohan** [comment]
@Dinistro @zero9178 @gysit Will code that depends on the element type not work anymore with opaque pointers? The code above in OpenMP Translation is used to get the size of the pointee of what previously would have been something like llvm.ptr<i32>, llvm.ptr<f32>, !llvm.ptr<array<1024 x i32>> etc.

**Comment by Dinistro** [comment]
> @Dinistro @zero9178 @gysit Will code that depends on the element type not work anymore with opaque pointers? The code above in OpenMP Translation is used to get the size of the pointee of what previously would have been something like `llvm.ptr<i32>`, `llvm.ptr<f32>`,`!llvm.ptr<array<1024 x i32>>` etc.

Opaque pointer have no longer any kind of element type. Instead, the operations that work on them are supposed to encode the types (or the size of the pointee), if this information is required at any point. In the above linked example, you will require `TypeAttr`s on all the operations that were using this function.

**Comment by kiranchandramohan** [comment]
Would carrying the `element_type` as a `TypeAttr` as @zero9178 did for other operations (https://reviews.llvm.org/D143582) be a reasonable solution for this?

https://github.com/llvm/llvm-project/blob/1c27899e24381a0231003b1aae9c436e78174109/mlir/include/mlir/Dialect/OpenMP/OpenMPOps.td#L1605

**Comment by Dinistro** [comment]
> Would carrying the `element_type` as a `TypeAttr` as @zero9178 did for other operations (https://reviews.llvm.org/D143582) be a reasonable solution for this?
> 
> https://github.com/llvm/llvm-project/blob/1c27899e24381a0231003b1aae9c436e78174109/mlir/include/mlir/Dialect/OpenMP/OpenMPOps.td#L1605

That should usually work, I assume. Sadly, Phabricator is not reachable, so I cannot check the revision you linked.

**Comment by kiranchandramohan** [comment]
The github commit is https://github.com/llvm/llvm-project/commit/81767f52f49339be2c78fc9bf831856b9f57e2f0.

**Comment by Dinistro** [comment]
Yeah, this strategy should work. Thanks for the link 😄

**Comment by TIFitis** [comment]
> I created to #69692 to update flang to use opaque pointers. However, I cannot merge it until OpenMP MLIR dialect is updated to not rely on llvm dialect type pointers. OpenMP codegen to LLVM gets some of its input from lowered FIR operations in the Fortran flow.
> 
> Here is an example where OpenMP relies on typed pointer in MLIR directory:
> 
> https://github.com/llvm/llvm-project/blob/54881c9225e612830a9e78574a805309b516627b/mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp#L1542
> 
> . I think this at least impact the map info lowering to LLVM.
> @TIFitis or @kiranchandramohan, can I ask you to take on the task in the OpenMP dialect directory?

I think @agozillon patch #68689 aims to use boundsOp for finding array_sizes. Perhaps he can integrate this change into this patch.

**Comment by kiranchandramohan** [comment]
> I think @agozillon patch #68689 aims to use boundsOp for finding array_sizes. Perhaps he can integrate this change into his patch.

What about basic pointer types? When I had a quick look at that patch, it seemed to still include code like the following.
```
  if (auto ptrTy = llvm::dyn_cast_if_present<LLVM::LLVMPointerType>(type)) {
    underlyingTypeSzInBits = dl.getTypeSizeInBits(ptrTy.getElementType());
```

**Comment by agozillon** [comment]
Yes that patch still depends on non-opaque pointers to get the element type size. I'm unsure how we'd go about getting the underlying type if we use opaque pointers. I suppose we'd have to dig it up from instructions, is how I'd assume it's intended to work after reading the documentation on it for LLVM?

**Comment by agozillon** [comment]
> Yes that patch still depends on non-opaque pointers to get the element type size. I'm unsure how we'd go about getting the underlying type if we use opaque pointers. I suppose we'd have to dig it up from instructions, is how I'd assume it's intended to work after reading the documentation on it for LLVM?

An alternative might also be to add a field to map_info to carry the underlying type, but not sure if that's preferable, although I imagine simpler. I'm a little unfamiliar with opaque pointers, so any pointers (no pun intended) would be appreciated.

**Comment by kiranchandramohan** [comment]
I am working on a patch to add a field to `map_info`.

**Comment by agozillon** [comment]
> I am working on a patch to add a field to `map_info`.

That would be very appreciated, I think this is likely the easiest and quickest way to make the transition, and if we wish to do it an alternative way in the future (e.g. finding it from LLVM-IR instructions as the documentation seems to hint at) we can make the move to that more gradually.

**Comment by kiranchandramohan** [comment]
> > I am working on a patch to add a field to `map_info`.
> 
> That would be very appreciated, I think this is likely the easiest and quickest way to make the transition, and if we wish to do it an alternative way in the future (e.g. finding it from LLVM-IR instructions as the documentation seems to hint at) we can make the move to that more gradually (or perhaps as mentioned above encoding it into the map_info is the right method of doing so in MLIR) .

Yes, this (https://github.com/llvm/llvm-project/issues/69303#issuecomment-1772502053) is what we agreed in the conversation above.

**Comment by TIFitis** [comment]
We can use getPointerDereferenceableBytes to get the Size for an llvm::Value in this case the BasePtr.

How does the AllocaInst for the mapOp calculate the size? We should just be able to use that size as is here.

**Comment by TIFitis** [comment]
> An alternative might also be to add a field to map_info to carry the underlying type, but not sure if that's preferable, although I imagine simpler. I'm a little unfamiliar with opaque pointers, so any pointers (no pun intended) would be appreciated.

I think we should explore other ways of getting this information first, if possible. Besides it's the `size` we are after and not the `type` itself. We already have a `boundsOp` to calculate the size, now we are also adding a `type` field to do the same. I personally don't like this brute force way of cramming information into the `mapInfo` for things that we might be able to infer from the context or other instructions/operations. But this is only my personal preference.

**Comment by kiranchandramohan** [comment]
> > An alternative might also be to add a field to map_info to carry the underlying type, but not sure if that's preferable, although I imagine simpler. I'm a little unfamiliar with opaque pointers, so any pointers (no pun intended) would be appreciated.
> 
> I think we should explore other ways of getting this information first, if possible. Besides it's the `size` we are after and not the `type` itself. We already have a `boundsOp` to calculate the size, now we are also adding a `type` field to do the same. I personally don't like this brute force way of cramming information into the `mapInfo` for things that we might be able to infer from the context or other instructions/operations. But this is only my personal preference.

This fix is to unblock the FIR fixes to enable opaque pointers in MLIR. Once we are done with that we can review and probably find a better way to minimize any information duplication.

**Comment by clementval** [comment]
> > An alternative might also be to add a field to map_info to carry the underlying type, but not sure if that's preferable, although I imagine simpler. I'm a little unfamiliar with opaque pointers, so any pointers (no pun intended) would be appreciated.
> 
> I think we should explore other ways of getting this information first, if possible. Besides it's the `size` we are after and not the `type` itself. We already have a `boundsOp` to calculate the size, now we are also adding a `type` field to do the same. I personally don't like this brute force way of cramming information into the `mapInfo` for things that we might be able to infer from the context or other instructions/operations. But this is only my personal preference.

You will only have boundsOps for arrays. Any other types will not produce any bounds ops.

**Comment by Dinistro** [comment]
This was fixed in https://github.com/llvm/llvm-project/pull/69692
Thanks everyone for working on this 😄
