### ISSUE TITLE
[CI] Increase the commit depth for code_formatter

### ISSUE THREAD

**Issue by zyn0217** [llvm/llvm-project#69311]
Currently, we're using 100 as the limit for the fetch depth in our code_formatter action.

https://github.com/llvm/llvm-project/blob/f0601c7569c6e2001b180136e1b699f577fd5c06/.github/workflows/pr-code-format.yml#L15-L20

If I understand correctly, this performs a comparison operation against the contributor's forked branch with only 100 commits from the top of the main branch. This implies that the contributor should keep the forked branch at most 100 commits behind the main before submitting a PR, in order to properly trigger the CI.

I'd argue that this is not a reasonable number: Given that we're likely to reach this number in about *one day* now, is it possible to increase the limit to a number that covers a longer time period, for example, a month? It is not always cheap for people to rebase their branches and rebuild all the stuff locally.

CC @tru and @HighCommander4 (See the [comment](https://github.com/llvm/llvm-project/pull/69153#issuecomment-1765907464) here.)

**Comment by tru** [comment]
I agree, ultimately I would like to see if we can remove this bit completely and calculate the diff via the GitHub api instead. But I haven't had time to work on this yet.

**Comment by HerrCai0907** [comment]
Could it possible to use pull_request instead of pull_request_target. Then we can compare with main branch directly.

> This event (pull_request_target) runs in the context of the base of the pull request, rather than in the context of the merge commit, as the pull_request event does.

**Comment by tru** [comment]
> Could it possible to use pull_request instead of pull_request_target. Then we can compare with main branch directly.

But then we don't have permission to write comments on the PR.

**Comment by HerrCai0907** [comment]
> But then we don't have permission to write comments on the PR.

I am not sure with permission setup in llvm, but in my own project, it works.
I use thollander/actions-comment-pull-request@v2, maybe can help you.

comments on the PR should be a common permission because everyone can do it. It is unbelievable that CI runner cannot.

**Comment by tru** [comment]
It doesn't work with forks. I did quite a bit of testing on this, but if you can find a better solution I am happy to see it!

**Comment by HerrCai0907** [comment]
Is it due to the permission of token? I run this python script in my host with my personal full permission token. It can modify the comment (e.g. https://github.com/llvm/llvm-project/pull/69465).
<img width="839" alt="image" src="https://github.com/llvm/llvm-project/assets/77575210/e616e2be-b945-40c2-bed8-ca2fd6392041">

**Comment by zyn0217** [comment]
This should have been mitigated by #70946 and would have been addressed by @boomanaiden154 once the proper fix #69766 got relanded.

**Comment by boomanaiden154** [comment]
This should be fixed by https://github.com/llvm/llvm-project/pull/72020. Will keep an eye on things and make sure it actually does.
