### ISSUE TITLE
CMakeLists using dep commands

### ISSUE THREAD

**Issue by AnonymousRonin** [llvm/llvm-project#69317]
So far I have not had a successful build.  Is there a more updated repository somewhere?

**Comment by dtcxzyw** [comment]
Please clarify your issue title and provide error messages during the building of LLVM.

**Comment by dtcxzyw** [comment]
Could you please provide the build commands to reproduce this? These errors are strange to me.

**Comment by AnonymousRonin** [comment]
They're are the CMakeLists that are sourced for llvm-project, libclc and SPIRV-tools.  What I am trying to do is figure out what to replace all the apparent deprecated commands with.  The documentation is not very clear. Specidically /llvm-project/llvm/docs, and of course libclc and SPIRV.  Is it incumbant upon me to update those lists?  I'm not familiar with all the proper syntax for each version so I'm counting on those being properly coded and updated.

**Comment by dtcxzyw** [comment]
Sorry, I am not sure what you mean.
If you failed to build LLVM or other projects in the LLVM mono repo, please provide build commands to reproduce the failure.
If you want to improve CMakeLists (e.g., "modernize cmake"), other folks familiar with the LLVM build system may help.

**Comment by eli-schwartz** [comment]
> Could you please provide the build commands to reproduce this? These errors are strange to me.

See for example #67399 -- I suspect the underlying cause of the errors is more complicated than it originally appears.
