### ISSUE TITLE
[clang-format] Incorrect formatting for annotated constrained functions

### ISSUE THREAD

**Issue by usx95** [llvm/llvm-project#69325]
clang-format's output:
```cpp
#define ANNOTATE(A) [[clang::annotate(A)]]
template <typename Message>
    requires(true)
ANNOTATE(
    "Loooooooooooooooooooooooooooooooooooooooooooooooooooong message"
    "Loooooooooooooooooooooooooooooooooooooooooooooooooooong message"
    "message") void foo(){};
```
Expected formatting:
```cpp
#define ANNOTATE(A) [[clang::annotate(A)]]
template <typename Message>
    requires(true)
ANNOTATE(
    "Loooooooooooooooooooooooooooooooooooooooooooooooooooong message"
    "Loooooooooooooooooooooooooooooooooooooooooooooooooooong message"
    "message") 
void foo(){};
```

removing the requires clause fixes the formatting (moved `void foo()` to the next line).

**Comment by usx95** [comment]
+CC @rymiel @HazardyKnusperkeks

**Comment by HazardyKnusperkeks** [comment]
I'll take a look what's the difference. In the meantime maybe https://clang.llvm.org/docs/ClangFormatStyleOptions.html#macros could help you.

**Comment by owenca** [comment]
The clang-format settings below would work:
```
BreakAfterAttributes: Always
Macros:
- ANNOTATE(x)=[[a(x)]]
```

**Comment by usx95** [comment]
I think the problem is that we do not want to "always" have a break (for example, when the annotation is small enough).

The problem is that the existence of a requires clause removes the line break, which looks unexpected.

**Comment by HazardyKnusperkeks** [comment]
I'd say we have two issues here. One is that it is handled differently with the requires clause. But the bigger issue would be that `foo` is misannotated in both cases:
```
 M=0 C=1 T=Unknown S=1 F=0 B=0 BK=0 P=23 Name=void L=120 PPK=2 FakeLParens= FakeRParens=0 II=0x559e1e3dbcb0 Text='void'
 M=0 C=0 T=TrailingAnnotation S=1 F=0 B=0 BK=0 P=23 Name=identifier L=124 PPK=2 FakeLParens= FakeRParens=0 II=0x559e1e4205e0 Text='foo'
```
I'll try to fix the second issue, and then we'll see if the first is still around.

**Comment by HazardyKnusperkeks** [comment]
If you declare your `ANNOTATE` as `AttributeMacros` both variants have no line break before `void`, but after that. ;)

**Comment by owenca** [comment]
> I think the problem is that we do not want to "always" have a break (for example, when the annotation is small enough).

Then setting it to `Leave` would work, right?

**Comment by HazardyKnusperkeks** [comment]
So I actually corrected the first issue. The second issue will be tracked it #70603.
