### ISSUE TITLE
Pass manager doesn't call releaseMemory between BasicCallGraph runs

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#6932]
|  |  |
| --- | --- |
| Bugzilla Link | [6560](https://llvm.org/bz6560) |
| Version | trunk |
| OS | All |
| Attachments | [testcase .ll](https://user-images.githubusercontent.com/60944935/143740910-19079323-aed5-4128-8c42-02ebef612529.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @jryans,@sunfishcode |

## Extended Description 

$ opt -globalsmodref-aa -loopsimplify -argpromotion -adce value_handle.bc -disable-output
While deleting: i8 ({ i8*, i32, i32, i32, i8*, i32, i32, i32, i8*, i8* (i8*, i32, i32)*, void (i8*, i8*)*, i8* }*)* %
An asserting value handle still pointed to this value!

**Comment by gwelymernans** [comment]
This no longer appears to be happening with either the old or new pass manager. If this pops up again, please file a new bug.
