### ISSUE TITLE
[InstructionSimplify] The result of icmp should be false.

### ISSUE THREAD

**Issue by DianQK** [llvm/llvm-project#69333]
I tried this IR:

```llvm
define i1 @src(i32 %X, i32 %Y, i32 %Z) {
  %A = lshr i32 %X, %Y
  %B = or i32 %X, %Z
  %C = icmp ult i32 %B, %A
  ret i1 %C
}
```

InstructionSimplify should infer that `%C` is false.
Alive2: https://alive2.llvm.org/ce/z/HvK2Ps

**Comment by topperc** [comment]
This looks overly reduced. alive2 also says that it can be optimized to `ret i1 true` or `ret i1 undef`.

**Comment by DianQK** [comment]
> This looks overly reduced. alive2 also says that it can be optimized to `ret i1 true` or `ret i1 undef`.

Thanks for the reminder, I've updated it.

**Comment by DianQK** [comment]
We expect #69471 to address such issues.
