### ISSUE TITLE
[mlir][sparse] Sparsification pass crash

### ISSUE THREAD

**Issue by saananth** [llvm/llvm-project#69395]
I'm seeing the sparsification pass crash on this example. HEAD is at 8e2bd05c4e8 and ```mlir-opt -sparsification``` will reproduce this behavior. If I return a constant say %c1 from the absent region, the pass goes through. The original intent is to return the value at %arg0[i] from the absent region.

```
#map = affine_map<(d0) -> (d0)>
#SV = #sparse_tensor.encoding<{ map = (d0) -> (d0 : compressed) }>
  
func.func @assign(%arg0: tensor<?xi64, #SV>, %arg1: i64, %arg2: index, %arg3: tensor<?xi64, #SV>) -> tensor<?xi64, #SV> {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : i64
    %dim = tensor.dim %arg0, %c0 : tensor<?xi64, #SV>
    %0 = tensor.empty(%dim) : tensor<?xi64, #SV>
    %1 = linalg.generic {
      indexing_maps = [#map, #map, #map], 
      iterator_types = ["parallel"]} 
      ins(%arg3, %arg0 : tensor<?xi64, #SV>, tensor<?xi64, #SV>) 
      outs(%0 : tensor<?xi64, #SV>) {
    ^bb0(%in: i64, %in_0: i64, %out: i64):
      %2 = sparse_tensor.unary %in : i64 to i64
       present = {
      ^bb0(%arg4: i64):        
        sparse_tensor.yield %arg1 : i64
      }
       absent = {
        sparse_tensor.yield %in_0 : i64
      }
      linalg.yield %2 : i64
    } -> tensor<?xi64, #SV>
    return %1 : tensor<?xi64, #SV>
  }
```

**Comment by aartbik** [comment]
In debug mode, example hits assert

`assert.h assertion failed at third_party/llvm/llvm-project/mlir/include/mlir/IR/Matchers.h:402 in bool mlir::matchPattern(Value, const Pattern &) [Pattern = mlir::detail::constant_op_binder<mlir::Attribute>]: value`

looking into this...

**Comment by aartbik** [comment]
The problem, indeed, is that the absent region cannot contain arbitrary expressions from the linalg (such as the sparse vector element), since that would require a lookup to materialize the value (there is no co-iteration on absent regions). But this should be enforced in verification, so I will add that.
