### ISSUE TITLE
InstCombine generates "fabs" calls from "And" pattern that is not correct in OpenCL

### ISSUE THREAD

**Issue by rjodinchr** [llvm/llvm-project#69464]
Since llvm/llvm-project@5c0da5839de1 instcombine transform pattern masking the MSB with a call to fabs.

While this might be correct in C, it is not in OpenCL. Math operations are allowed to flush denormalized numbers to zero in OpenCL. Thus what should be just masking the MSB starts to change much more data.

This is an issue in libclc as those implementations are using this pattern and rely on the fact that only the MSB is masked. Using fabs instead breaks conformance on platforms where fabs flushes denormalized numbers to zero.

**Comment by RKSimon** [comment]
CC @arsenm

**Comment by arsenm** [comment]
> Using fabs instead breaks conformance on platforms where fabs flushes denormalized numbers to zero.

These platforms have incorrectly implemented the fabs intrinsic. By definition fabs, fneg and copysign only change the sign bit. Any canonicalization effects is a codegen bug

**Comment by arsenm** [comment]
> Math operations are allowed to flush denormalized numbers to zero in OpenCL. 

The sign operators do not count as true math operations. The OpenCL operation table reports 0ulp as the requirement for fabs, which implies a denormal can never be flushed

**Comment by rjodinchr** [comment]
I don't agree

>7.2. INF, NaN and Denormalized Numbers
INF and NaNs must be supported. Support for signaling NaNs is not required.
Support for denormalized numbers with single precision floating-point is optional. Denormalized
single precision floating-point numbers passed as input or produced as the output of single
precision floating-point operations such as add, sub, mul, divide, and the functions defined in math
functions, common functions, and geometric functions may be flushed to zero.
https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_C.html#inf-nan-and-denormalized-numbers

Then if you go in the math functions [list](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_C.html#math-functions), you'll find `fabs`.

Translating `fabs` to a bitmask feels legal, but not the opposite in OpenCL I would say.

@alan-baker, @kpet how do you understand the OpenCL specification?

**Comment by rjodinchr** [comment]
Looking closely at https://github.com/llvm/llvm-project/commit/5c0da5839de1, it feels like you are trying to match the following pattern:
```
bitcast float to i32
and  2147483647
bitcast i32 to float
=>
fabs
```
But what the code is really doing is:
```
bitcast float to i32
and  2147483647
=> 
fabs
bitcast float to i32
```
So in the initial pattern we get:
```
bitcast float to i32
and  2147483647
bitcast i32 to float
=>
fabs
bitcast float to i32
bitcast i32 to float
```
Then llvm squash the 2 bitcasts so it feels right.
But for a patten like we have in libclc, it does not work as the bitcast to fp after the bitwiseand does not exist, but https://github.com/llvm/llvm-project/commit/5c0da5839de1 is in fact not looking for it.

**Comment by arsenm** [comment]
Denorms "could be" flushed is also the not the same as "must be". Assuming the spec allows fabs to flush (which I wouldn't agree with, I think the denormal handling is extremely underspecified in OpenCL), it does not mandate flushing. Lowering as a non-flushing operation is correct. Lowering of llvm.fabs.f32 to a flushing operation is incorrect. I think no matter how you want to look at this, there's a codegen/lowering bug in some backends
