### ISSUE TITLE
<algorithm>: `__is_callable` checks whether the callable can be called with rvalue

### ISSUE THREAD

**Issue by hewillk** [llvm/llvm-project#69554]
https://github.com/llvm/llvm-project/blob/a574242f196dd0afaa2c591d6cc5716fd67bc738/libcxx/include/__type_traits/is_callable.h#L22-L29

Some std algorithms check whether callable is an ordinary function through `__is_callable`. However, according to its above definition, this seems to only check whether callable can be called with an rvalue, which seems to be an oversight.

```cpp
#include <algorithm>

struct Cmp {
  bool operator()(int, int) const &;
  bool operator()(int, int) && = delete;
};

int main() {
  return std::minmax({42, 0, -42}, Cmp{}).first;
}
```
https://godbolt.org/z/8a45rPdqo

**Comment by hewillk** [comment]
> The `__is_callable` is only there to avoid users passing pointer-to-member-functions or similar things. What you've got there is UB AFAICT. We could extend `__is_callable`, but I don't really see that it'll catch a lot of bugs.

Do you mean that passing a functor with only `const`-lvalue qualifier call operator to the standard algorithm is UB?

**Comment by philnik777** [comment]
> > The `__is_callable` is only there to avoid users passing pointer-to-member-functions or similar things. What you've got there is UB AFAICT. We could extend `__is_callable`, but I don't really see that it'll catch a lot of bugs.
> 
> Do you mean that passing a functor with only `const`-lvalue qualifier call operator to the standard algorithm is UB?

No. I mean that having different behaviour depending on qualifiers is UB. If you don't explicitly delete the overload everything is fine: https://godbolt.org/z/PYM3zcfbe

**Comment by ldionne** [comment]
IMO this is clearly a bug. It seems like we want to check e.g. `__is_callable<_Compare&, decltype(*__first), decltype(*__first)>::value` instead of `__is_callable<_Compare, decltype(*__first), decltype(*__first)>::value`. After all, what we call in algorithms is always a lvalue:

```
template <class _ForwardIterator, class _Compare>
pair<_ForwardIterator, _ForwardIterator>
minmax_element(_ForwardIterator __first, _ForwardIterator __last, _Compare __comp) {
  // __comp is passed as a lvalue
  // ...
}
```

Does that make sense?

**Comment by philnik777** [comment]
@ldionne I'm not convinced it is. In 99.9% of cases it won't make any difference at all, and in the few cases where it does I think we want to diagnose it, since it's almost certainly user error.

**Comment by NhatNguyen1810** [comment]
If this is actually deemed an issue, I would like to take this.

**Comment by ldionne** [comment]
@philnik777 We are calling the comparator as `__comp(args...)` aka passing a lvalue, but we are checking whether `_Compare{}(args...)` would be well-formed. I think what would make sense is to check this instead:

```
static_assert(__is_callable<_Compare&, decltype(*__first), decltype(*__first)>::value);
static_assert(__is_callable<_Compare const&, decltype(*__first), decltype(*__first)>::value);
```

That way, we make sure that the comparator is callable both as a const and a non-const lvalue, which is equivalent to the following two declarations:

```
template <class _ForwardIterator, class _Compare>
pair<_ForwardIterator, _ForwardIterator>
minmax_element(_ForwardIterator __first, _ForwardIterator __last, _Compare __comp) {
  // ...
}

template <class _ForwardIterator, class _Compare>
pair<_ForwardIterator, _ForwardIterator>
minmax_element(_ForwardIterator __first, _ForwardIterator __last, _Compare const __comp) {
  // ...
}
```

Both of which should be valid implementations. If the user passes something that fails this check, then I would argue that the user is in the wrong. But checking that we can call the comparator on a prvalue seems like trying way too hard to make user's lives difficult. I can imagine some valid use cases for making one's call operator `&&`-qualified to avoid it being called on a temporary, and in practice that's not something we need in the classic algorithms.

**Comment by ldionne** [comment]
@NhatNguyen1810 I'll review a patch if you make one, thanks for jumping on this!

**Comment by NhatNguyen1810** [comment]
@ldionne ion
If possible, can you provide a summary list of steps which need to be done? I went through the comments above but I don't really get what I am supposed to do.

**Comment by ldionne** [comment]
> @ldionne
> If possible, can you provide a summary list of steps which need to be done? I went through the comments above but I don't really get what I am supposed to do.

We have a bunch of places in the code where we currently do something like this:

```
static_assert(__is_callable<_Compare, decltype(*__first), const _Tp&>::value,
                "The comparator has to be callable");
```

Instead, we should change those places to

```
static_assert(__is_callable<_Compare&, decltype(*__first), const _Tp&>::value,
                "The comparator has to be callable");
static_assert(__is_callable<_Compare const&, decltype(*__first), const _Tp&>::value,
                "The comparator has to be const-callable");
```

And we should add a test with a comparator like

```
struct Cmp {
  bool operator()(int, int) const &;
  bool operator()(int, int) && = delete;
};
```

for those algorithms to make sure that we don't fail to compile anymore.

**Comment by hewillk** [comment]
> We have a bunch of places in the code where we currently do something like this:
> 
> ```
> static_assert(__is_callable<_Compare, decltype(*__first), const _Tp&>::value,
>                 "The comparator has to be callable");
> ```
> 
> Instead, we should change those places to
> 
> ```
> static_assert(__is_callable<_Compare&, decltype(*__first), const _Tp&>::value,
>                 "The comparator has to be callable");
> static_assert(__is_callable<_Compare const&, decltype(*__first), const _Tp&>::value,
>                 "The comparator has to be const-callable");
> ```

Can we just simply change the template parameter of `__is_callable_helper` to lvalue?
  
```cpp
 template <class _Func, class... _Args> 
 struct __is_callable : decltype(std::__is_callable_helper<_Func&, _Args...>(0)) {}
```

**Comment by ldionne** [comment]
We could, but then we're not catching if `_Func const&` isn't callable.  Also, `__is_callable` is probably not the right name for the trait anymore, since we're arbitrarily adding `&` to the type. IMO we should strive to keep `__is_callable` as close as possible to a general-purpose type trait.

**Comment by ldionne** [comment]
Upon revisiting this, I think we'll break too much code if we start pedantically checking for const-callable. We should simply fix the lvalue vs rvalue callable issue we have here. I'll update #73451 with that in mind.

**Comment by ldionne** [comment]
https://github.com/llvm/llvm-project/commit/8d151f804ff43aaed1edf810bb2a07607b8bba14 was reverted, re-opening.
