### ISSUE TITLE
[PPC] clang support for -mregnames

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#69631]
gcc has `-mregnames` to print `r31` rather than `31`.  I think this helps readability. Probably something `PPCAsmPrinter` or `PPCInstPrinter` could implement

**Comment by nickdesaulniers** [comment]
ah, PPCInstPrinter has `ppc-asm-full-reg-names`; perhaps we could add an alias to that which matches GCC (or just change the internal flag, or wire that up to clang somehow).

**Comment by brad0** [comment]
> gcc has `-mregnames` to print `r31` rather than `31`. I think this helps readability. Probably something `PPCAsmPrinter` or `PPCInstPrinter` could implement

It would be nice to have support for this. Looking at the last few ports in the OpenBSD ports tree not using Clang to build I noticed CompCert wants this feature for PowerPC.

**Comment by stefanp-ibm** [comment]
As far as I know I don't think that we can alias `ppc-asm-full-reg-names` directly from the clang front end. However, I think we can create a SubtargetFeature that is controlled by `-mregnames / -mno-regnames`.

**Comment by stefanp-ibm** [comment]
I have a patch up for this here: https://github.com/llvm/llvm-project/pull/70255

**Comment by nickdesaulniers** [comment]
thanks for the fix!

https://github.com/llvm/llvm-project/commit/423ad04c67b7fbe7c6a6b4e0591bff40844c6027

fixed in clang-18
