### ISSUE TITLE
Clang++ broken std::filesystem

### ISSUE THREAD

**Issue by boludoz** [llvm/llvm-project#69678]
```
#include <filesystem>
#include <iostream>
#include <string>
#include <windows.h>
#include <fstream>
#include <codecvt>

typedef unsigned int u32;

#ifdef _WIN32
static std::wstring CPToUTF16(u32 code_page, std::string_view input) {
    const auto size =
        MultiByteToWideChar(code_page, 0, input.data(), static_cast<int>(input.size()), nullptr, 0);

    if (size == 0) {
        return {};
    }

    std::wstring output(size, L'\0');

    if (size != MultiByteToWideChar(code_page, 0, input.data(), static_cast<int>(input.size()),
                                    &output[0], static_cast<int>(output.size()))) {
        output.clear();
    }

    return output;
}

std::string UTF16ToUTF8(std::wstring_view input) {
    const auto size = WideCharToMultiByte(CP_UTF8, 0, input.data(), static_cast<int>(input.size()),
                                          nullptr, 0, nullptr, nullptr);
    if (size == 0) {
        return {};
    }

    std::string output(size, '\0');

    if (size != WideCharToMultiByte(CP_UTF8, 0, input.data(), static_cast<int>(input.size()),
                                    &output[0], static_cast<int>(output.size()), nullptr,
                                    nullptr)) {
        output.clear();
    }

    return output;
}

std::wstring UTF8ToUTF16W(std::string_view input) {
    return CPToUTF16(CP_UTF8, input);
}

#endif

int main() {
    // console UTF-8
    SetConsoleOutputCP(CP_UTF8);
    SetConsoleCP(CP_UTF8);

    // create file
    std::filesystem::path p{L"♻️.txt", std::filesystem::path::native_format}; // Explicit UTF-16 encoding
    std::filesystem::path evaluatep = {L"hello" / p};
    std::wstring evaluate = evaluatep.wstring();

    std::wcout << L"Bad wstring -> " << evaluate; // Explicit UTF-16 encoding

    std::cout << std::endl;

    std::cout << "String OK -> " << UTF16ToUTF8(evaluate) << std::endl; // Explicit UTF-8 codified
    
    std::cout << "Bad string -> " << evaluatep.string(); // Bad filesystem string() conversion

    std::cout << std::endl;

}
```
![image](https://github.com/llvm/llvm-project/assets/11653030/abad8498-fd5f-4cec-a78c-8bb85b659f78)
the programs stucks

Version:
`
clang version 15.0.1
Target: x86_64-pc-windows-msvc
Thread model: posix`

Multiplataform friendly code:
```
#include <filesystem>
#include <iostream>
#include <string>
#include <fstream>
#include <codecvt>

#ifdef _WIN32
#include <windows.h>
#endif

static std::wstring CPToUTF16(std::string_view input) {
    std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> converter;
    return converter.from_bytes(input.data(), input.data() + input.size());
}

std::string UTF16ToUTF8(std::wstring_view input) {
    std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> converter;
    return converter.to_bytes(input.data(), input.data() + input.size());
}

std::wstring UTF8ToUTF16W(std::string_view input) {
    std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> converter;
    return converter.from_bytes(input.data(), input.data() + input.size());
}

int main() {
#if defined(_WIN32)
    SetConsoleOutputCP(CP_UTF8);
#endif

    // create file
    std::filesystem::path p{L"♻️.txt"}; // Explicit UTF-16 encoding
    std::filesystem::path evaluatep = {L"hello" / p};
    std::wstring evaluate = evaluatep.wstring();
    try {
        std::wcout << L"Bad wstring -> " << evaluate; // Explicit UTF-16 encoding

        std::cout << std::endl;

        std::cout << "String OK -> " << UTF16ToUTF8(evaluate) << std::endl; // Explicit UTF-8 codified
        
        std::cout << "Bad string -> " << evaluatep.string(); // Bad filesystem string() conversion

        std::cout << std::endl;

        std::cout << std::endl;
    } catch (std::exception& e) {
        std::cout << e.what() << std::endl;
    }

}
```

Compiled in wsl:
`root@PC:/mnt/c/Users/franc/OneDrive/Escritorio/Nueva carpeta (3)# clang++ main.cpp -o test.elf --std=c++20 -lstdc++fs -stdlib=libstdc++`

(Try catch error captured):
![image](https://github.com/llvm/llvm-project/assets/11653030/f72f7bd8-f749-43f0-b545-e70033bbe020)

Version:
`Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin`

**Comment by boludoz** [comment]
clang version 15.0.1
Target: x86_64-pc-windows-msvc
Thread model: posix

**Comment by asl** [comment]
> clang version 15.0.1 Target: x86_64-pc-windows-msvc Thread model: posix

Is this still the issue with the latest clang?

**Comment by EugeneZelenko** [comment]
@boludoz: Which STL implementation do you use? https://godbolt.org should be helpful to try different STL implementations and Clang versions.

**Comment by boludoz** [comment]
I don't know, what I know is that it also fails when I use the MSVC native compiler but in a different way, the .string() function correctly decodes the wstring to a string (bad string), but it breaks "String OK". Honestly the C++ codec support is pretty bad and deprecated, I think that's the problem. It is necessary to solve the codec problem natively and without external dependencies, I really don't know how this works internally. For the code to work correctly, at least the last two strings must be displayed correctly.

**Comment by boludoz** [comment]
`PS C:\Users\franc\OneDrive\Escritorio\Nueva carpeta (3)> clang main.cpp -o main.exe -std=c++20
PS C:\Users\franc\OneDrive\Escritorio\Nueva carpeta (3)> ./main
Bad wstring -> hello\
String OK -> hello\♻️.txt
Bad string -> unknown error`

**Comment by boludoz** [comment]
More test 
![image](https://github.com/llvm/llvm-project/assets/11653030/5ca4343d-c316-4d9c-8aac-6ccf3f1ff31f)

**Comment by boludoz** [comment]
![image](https://github.com/llvm/llvm-project/assets/11653030/9a0a56f4-6157-413a-ab56-28008ad99259)

**Comment by boludoz** [comment]
![image](https://github.com/llvm/llvm-project/assets/11653030/8a7d068f-0dcb-4d6e-b45e-dac493f1827a)
that's ok

**Comment by EugeneZelenko** [comment]
@boludoz: Links to GodBolt are enough. You could also combine multiple builds in same session there.

**Comment by boludoz** [comment]
![image](https://github.com/llvm/llvm-project/assets/11653030/94cc41bc-3d4a-4a96-bd44-3613ab28daa0)

**Comment by wasin-ironsoftware** [comment]
@boludoz question asides, how do you able to execute msvc on godbolt? There is no such option as compiler list. Thanks!

**Comment by haxpor** [comment]
@boludoz question asides, how do you able to execute msvc on godbolt? There is no such option as compiler list. Thanks!

**Comment by boludoz** [comment]
> @boludoz question asides, how do you able to execute msvc on godbolt? There is no such option as compiler list. Thanks!

I tested that on my computer.

**Comment by boludoz** [comment]
Freshly baked test on my other PC with Clang 17:
```
clang version 17.0.2
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

Using:
```
    // console UTF-8
    std::setlocale(LC_CTYPE, ".UTF8");
    SetConsoleOutputCP(CP_UTF8);
    SetConsoleCP(CP_UTF8);

```
![image](https://github.com/llvm/llvm-project/assets/11653030/a3111636-4890-4895-9685-9b7680002888)

I congratulate all of you, you have better support than the official Windows compiler without being official.

**Comment by boludoz** [comment]
Soon I will do a test trying to write files. It strikes me that this works, however the conversion from UTF-8 and UTF-16 and vice versa is broken, something is not going to work here.

**Comment by boludoz** [comment]
Sorry, it's not a clang problem, it's a Windows console problem, congratulations, this works as it should.

**Comment by boludoz** [comment]
Remember:
`   std::setlocale(LC_CTYPE, ".UTF8");
    SetConsoleOutputCP(CP_UTF8);
    SetConsoleCP(CP_UTF8);
`
