### ISSUE TITLE
[AArch64] compile crash on "Call operand has unhandled type"

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#69694]
* test:  https://gcc.godbolt.org/z/1fsW7cjG9

* report error:  `clang -march=armv8.3-a+sve -O3 -S reduced.ll`
```
AArch64ISelLowering.cpp:7014: 
void analyzeCallOperands(const llvm::AArch64TargetLowering&, const llvm::AArch64Subtarget*, const llvm::TargetLowering::CallLoweringInfo&, llvm::CCState&): 
Assertion `!Res && "Call operand has unhandled type"' failed
```

**Comment by dtcxzyw** [comment]
The original Godbolt link is broken.
Godbolt: https://godbolt.org/z/bo339Wjrh

**Comment by vfdff** [comment]
Thanks for your update, and here is a more simple case reduced by `llvm-reduce`, https://godbolt.org/z/n66zcKMbc

**Comment by vfdff** [comment]
maybe fixed by https://github.com/llvm/llvm-project/pull/70034

**Comment by vfdff** [comment]
Thanks for the great helping @paulwalker-arm
