### ISSUE TITLE
Problems with float_control pragma stack in Clang 17.x

### ISSUE THREAD

**Issue by tru** [llvm/llvm-project#69717]
When working on integrating Clang 17 in our engine we noticed that we were getting some errors when we used `#pragma float_control`, specifically the last `pop` resulted in the following error:

```
pipeline\packages\graphics\GraphicCore\src\graphic\tools\meshtools.cpp(2362,9): error: #pragma float_control(pop, ...) failed: stack empty [-Werror,-Wignored-pragmas]
 2362 | #pragma float_control(pop)
      |         ^
1 error generated.
```

I first thought this was a new warning so I dumped the preprocessed files to see if there was an "imbalance", here is the result:

```
16:#pragma float_control(precise, on, push)
76314:#pragma float_control( push )
76341:#pragma float_control( pop )
306286:#pragma float_control(precise, off, push)
306297:#pragma float_control(pop)
306392:#pragma float_control(precise, off, push)
306403:#pragma float_control(pop)
744987:#pragma float_control(pop)
```

As you see they are balanced. 

I added some debug information in `Sema::ActOnPragmaFloatControl` and noticed that the stack gets randomly reset between calls:

```
float_control(push|set)
stack: 1
float_control(push)
stack: 1
float_control(pop)
stack: 0
float_control(push|set)
stack: 1
float_control(pop)
stack: 0
float_control(push|set)
stack: 1
float_control(pop)
stack: 0
float_control(pop)
```

I noticed that there were some changes by @spavloff in Clang 17 around these and then traced down the following two commits:

https://github.com/llvm/llvm-project/commit/0baf85c331090fbe2d2b42214ed0664d55feb0b5
https://github.com/llvm/llvm-project/commit/2e903709de003dc6ae980197f4a0850a158dd9b8

If I revert these two the stack is behaving as **I** expect it to behave.

I have tried to make a smaller reproducer, but there is probably something missing because just doing several push/pops nested in a single C++ with some headers doesn't reproduce the problem. So it's probably down to something I am missing with the set of patches.

So I need to understand if this is something wrong with our code or a bug in clang.

I have tested both 17.0.3 and HEAD with the same issues.

**Comment by tru** [comment]
I have finally figured out a minimal reproducer:

The trick is that if you have `constexpr template` it will reset the float_control settings and remove the stack. It works if the `constexpr` is removed. This happens also when you include `chrono` from MSVC STL which is where I figured out that it was happening.

```
float y();
float z();

#pragma float_control(precise, on, push)

template<typename T>
constexpr T multi(T x, T y){
    return x * y;
}

int multi_i(int x, int y)
{
    return multi<int>(x, y);
}

#pragma float_control(precise, off, push)

class ON {
  float w = 2 + y() * z();
};
ON on;

#pragma float_control(pop)

#pragma float_control(pop)
```

**Comment by spavloff** [comment]
@tru, thank you for the test, it greatly simplified analysis. Possible fix is in https://github.com/llvm/llvm-project/pull/70646.

**Comment by tru** [comment]
Re-opening to handle the backporting.

**Comment by spavloff** [comment]
Sorry, one more commit is also required: https://github.com/llvm/llvm-project/commit/5fdb70be7b0a1340a7ebdeb94ab073e466fc4aa6

**Comment by tru** [comment]
/cherry-pick f6f625f4c6c3cbeb8cf6b889cdafc848dd4cb117 93ae26331592f41bf2b1d10b048743d80c468385 5fdb70b
