### ISSUE TITLE
How to turn off memcpy and memset warnings in clang-tidy?

### ISSUE THREAD

**Issue by fefe17** [llvm/llvm-project#69728]
clang-tidy keeps giving me warnings that I should be using memset_s instead of memset.

> note: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11

If you look closely and carefully you will find that memset takes a length argument and does boundary checking with it. The warning is at least misleading and could even be said to be factually wrong.

Furthermore, the current glibc release does not have memset_s, and rightfully so, because Annex K is optional.

Please give me a config file where I can remove these warnings from clang-tidy globally.

**Comment by dtcxzyw** [comment]
https://clang.llvm.org/docs/analyzer/checkers.html#security-insecureapi-deprecatedorunsafebufferhandling-c may help.

**Comment by fefe17** [comment]
Did you have anything particular in mind that I should do with that?

If I could put it in ~/.clang-tidy.ignore and clang-tidy would stop warning me about it, then it would help.

**Comment by dtcxzyw** [comment]
Just add the following lines to your `.clang-tidy`:
> Checks: -clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling

**Comment by fefe17** [comment]
That did not work. But now that I know there is a ~/.clang-tidy file, I found this syntax that worked for me:

Checks: "-clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling"

Thanks for your help!

**Comment by Mario-Klebsch** [comment]
I stumbled upon warnings, that "Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11"

memset is invoked with sizeof() for the 1st argument as 3rd argument. memset_s() hat two size parameters. So what is the benefit of passing the same value twice?

I asked CoPilot and  Claude Sonnet-4.6 dists these 'advantages' of memset_d:
* Defined in C11 Annex K
* **Guaranteed NOT to be optimized away** — this is its primary reason to exist
* Validates parameters:
  * dest == NULL → constraint handler
  * count > destsz → constraint handler and still fills destsz bytes
clang.tidy complained on memset invocations where &local_variable was given as 1st parameter, and sizeof(type_of_local_varaible) was given as 3rd parameter.
So dest cannot be NULL, and count cannot be > destsz, so why complain?
