### ISSUE TITLE
LoopVectorize Miscompilation with Aliases in clang 15+

### ISSUE THREAD

**Issue by yuxuanchen1997** [llvm/llvm-project#69744]
We believe there is a problem in LoopAccessAnalysis or LoopVectorize that caused the following code snippet to produce wrong result.

Compiler command 
```
clang -Xclang -target-cpu -Xclang haswell -Xclang -tune-cpu -Xclang skylake -O2 repro.c
```

repro.c
```c
#include <stdio.h>
#include <stdlib.h>

typedef struct {
  unsigned long long ref_count;
} MyObject;

static int mycount(MyObject** arr) {
  MyObject** old_arr = arr;
  while (*arr++)
    ;
  return (int)(arr - old_arr) - 1;
}

void my_inplace_repeat(MyObject** arr, int times) {
  int orig_elem_count = mycount(arr);
  int pos = orig_elem_count;
  for (int i = 1; i < times; i++) {
    for (int j = 0; j < orig_elem_count; j++) {
      MyObject* obj = arr[j];
      obj->ref_count++;
      arr[pos++] = obj;
    }
  }
  arr[pos] = 0; // NULL terminated list
}

MyObject* obj_alloc() {
  printf("allocating\n");
  MyObject* ret = malloc(sizeof(MyObject));
  ret->ref_count = 1;
  return ret;
}

int main() {
  MyObject** arr = malloc(sizeof(MyObject*) * 1000);
  arr[0] = obj_alloc();
  arr[1] = 0;

  my_inplace_repeat(arr, 4);
  my_inplace_repeat(arr, 2);

  int count = mycount(arr);
  printf("count = %d\n", count);
  for (int i = 0; i < count; i++) {
    if (arr[i]->ref_count != count) {
      printf("BUG: ref_count should be %d, but %llu was found.\n", count,
      arr[i]->ref_count); return 1;
    }
  }
  return 0;
} 
```

Compiler Explorer: https://godbolt.org/z/9Er6n81PT

This issue repros on LLVM 15 onwards.

The vectorization happened in the inner loop of `my_inplace_repeat`. Somehow Vectorization saw this `obj->ref_count++` as safe to vectorize while `obj` might be an alias from the previous iteration. This code snippet deliberately created aliases in the array argument to `my_inplace_repeat`.

**Comment by yuxuanchen1997** [comment]
I am not particularly convinced that MemoryDepChecker is checking that obj in the loop statement `MyObject* obj = arr[j];` can alias one another. I don't see runtime checks being generated for this array of pointers either. (However, they are generated for `arr[j]` and `arr[pos]`)

@fhahn, I saw that you worked on runtime checks and wondering if I can get some pointers here. Do you think runtime checks should be generated for this function? I don't quite get the intricacies in the pass yet so would appreciate some explanations on how to look at this issue.

**Comment by fhahn** [comment]
Thanks, let me take a look

**Comment by yuxuanchen1997** [comment]
@fhahn 

I thought that this might be helpful: because that I have a small repro it's not too difficult to run a local bisect. Bisect pointed to 20d798bd47ec5191de1b2a8a031da06a04e612e1.

**Comment by fhahn** [comment]
Ok this looks unrelated to #69909 and 20d798bd47ec5191de1b2a8a031da06a04e612e1 which only exposes the issue for that particular case. Preparing a fix.
