### ISSUE TITLE
A problem of the LLDB version

### ISSUE THREAD

**Issue by Thrrreeee** [llvm/llvm-project#69850]
My LLVM version is 18.0.0git, but I cannot understand why my LLDB version is 10.0.0!
Is it possible that the Aarch64 version of LLVM cannot yet support the latest version of LLDB?
![image](https://github.com/llvm/llvm-project/assets/72311224/6d20bcae-c1b3-40b6-a7d1-ef812fcac0ab)
How can I upgrade the LLDB, or how to deal with this problem, if I want a newer LLDB.

**Comment by dtcxzyw** [comment]
`sudo apt install lldb-18` may help if you are using `apt-get`.

**Comment by Thrrreeee** [comment]
> `sudo apt install lldb-18` may help if you are using `apt-get`.

I cannot perform 'sudo' operations due to permission issues.
LLDB isn't built simultaneously with LLVM? In theory, their versions should be in sync. So, is it possible that a higher version of LLDB doesn't support Aarch64?

**Comment by dtcxzyw** [comment]
> > `sudo apt install lldb-18` may help if you are using `apt-get`.
> 
> I cannot perform 'sudo' operations due to permission issues. LLDB isn't built simultaneously with LLVM? In theory, their versions should be in sync. So, is it possible that a higher version of LLDB doesn't support Aarch64?

The snapshot version of lldb is available for [AArch64](https://apt.llvm.org/jammy/dists/llvm-toolchain-jammy/main/binary-arm64/). 
If you want to build `lldb` locally, please pass `-DLLVM_ENABLE_PROJECTS="lldb"` to `cmake`.
See also https://llvm.org/docs/CMake.html#frequently-used-llvm-related-variables.

**Comment by Thrrreeee** [comment]
> > > `sudo apt install lldb-18` may help if you are using `apt-get`.
> > 
> > 
> > I cannot perform 'sudo' operations due to permission issues. LLDB isn't built simultaneously with LLVM? In theory, their versions should be in sync. So, is it possible that a higher version of LLDB doesn't support Aarch64?
> 
> The snapshot version of lldb is available for [AArch64](https://apt.llvm.org/jammy/dists/llvm-toolchain-jammy/main/binary-arm64/). If you want to build `lldb` locally, please pass `-DLLVM_ENABLE_PROJECTS="lldb"` to `cmake`. See also https://llvm.org/docs/CMake.html#frequently-used-llvm-related-variables.

thank you for your suggestion, I will have a try.
