### ISSUE TITLE
Optimization for `powi(x, y) * x`

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#69862]
Consider the following:
```cpp
#include <cmath>

double f1(double x)
{
    return pow(x, 3) * pow(x, 1);
}

double f2(double x)
{
    return pow(x, 4);
}
```

(X86) https://godbolt.org/z/nd3ME13Po
(ARM) https://godbolt.org/z/z5vjnPhrK

On X86, if `-Ofast` is specified, GCC just calculates `x * x * x * x` for `f1` with two `mulsd`, but Clang performs `mulsd` three times. There is no such difference on ARM.

**Comment by dtcxzyw** [comment]
https://github.com/llvm/llvm-project/blob/a63dc79d113915048c932eca7732838206898e9a/llvm/lib/Transforms/InstCombine/InstCombineMulDivRem.cpp#L708-L717
`powi(X, Y) * X --> powi(X, Y + 1)` also works.
@vfdff I guess you are interested in this optimization :)

**Comment by vfdff** [comment]
* **related IR test**: https://gcc.godbolt.org/z/rMK1884Yh
```
define double @f1(double noundef %x) {
  %p1 = tail call fast double @llvm.powi.f64.i32(double %x, i32 3)
  %mul = fmul fast double %p1, %x
  ret double %mul
}

declare double @llvm.powi.f64.i32(double, i32)
```

* **arm64**: clang --target=aarch64  -march=armv8.3-a+sve  -O3 -Ofast
```
f1: // @f1
  fmul d1, d0, d0
  fmul d1, d0, d1
  fmul d0, d1, d0
  ret
```
