### ISSUE TITLE
[CVP] Missed opportunity to do slt to ult conversion

### ISSUE THREAD

**Issue by vladimirradosavljevic** [llvm/llvm-project#69928]
For the following [example](https://godbolt.org/z/1PePcKve7), CVP is not converting `slt` to `ult`:
```
define i64 @test_select(i64 %arg, i64 %arg1) {
entry:
  %cmp1 = icmp ult i64 %arg, 64424509440
  %and = and i64 %arg1, 4294967295
  %cmp2 = icmp slt i64 %arg, %and
  %select = select i1 %cmp1, i1 %cmp2, i1 false
  br i1 %select, label %good, label %bad

bad:
  ret i64 1

good:
  ret i64 0
}
```
[Proof](https://alive2.llvm.org/ce/z/cq7ydm) that this transformation is valid.
On the other hand, it is [able](https://godbolt.org/z/44eq4o5vv) to convert it if there are 2 BBs and no select instruction.

**Comment by XChy** [comment]
CVP leverages only `getConstantRange(Value *V, Instruction *CxtI, bool UndefAllowed)` to flip signedness predicate, based on **def** level.
Here is a possible solution. We could get the range in **use** level. But I'm not sure it's profitable.
If it has no much impact on compile-time, I may post a pr to solve it.

**Comment by vladimirradosavljevic** [comment]
> CVP leverages only `getConstantRange(Value *V, Instruction *CxtI, bool UndefAllowed)` to flip signedness predicate, based on **def** level. Here is a possible solution. We could get the range in **use** level. But I'm not sure it's profitable. If it has no much impact on compile-time, I may post a pr to solve it.

Thanks for working on this!
I saw in you patch that you are using `noundef` for arguments in tests, and without that, transformation is not working. Do you know why is that so?

**Comment by XChy** [comment]
> I saw in you patch that you are using `noundef` for arguments in tests, and without that, transformation is not working. Do you know why is that so?

`getConstantRangeAtUse` requires `noundef`. There is the comment:
```C++
// If the value is undef, a different value may be chosen in
// the select condition and at use.
if (!isGuaranteedNotToBeUndefOrPoison(SI->getCondition(), AC))
        break;
```
Some at-use transforms may be unsafe with undef values. I think it may be OK in this issue, but LVI Analysis does not provide such option.
