### ISSUE TITLE
Clang 16.0.1.1: Binding: Python For Curosr with kind `CursorKind.BINARY_OPERATOR`  the spelling method of Cursor Class issue

### ISSUE THREAD

**Issue by Romisajad** [llvm/llvm-project#70019]
When the cursor is pointing to any Binary Operator for example like ( + or = ).
The spelling property of the Cursor class is not working.
It is not returning the Operator. As you can see in the following screenshots that i have tried to printout the cursor.spelling but for that it returns nothing and the numbers are the location line number.
I have provided the code and the output of the problem.
![img](https://github.com/llvm/llvm-project/assets/25686045/7a1dc9fb-99d8-4e2c-bf20-3fee9e5f84c5)
![img1](https://github.com/llvm/llvm-project/assets/25686045/3128ce6c-2af1-4f90-ae34-802f1f90247e)

**Comment by derekdai** [comment]
@Romisajad with clang 17, there are `clang_getBinaryOperatorKindSpelling`, `clang_getCursorBinaryOperatorKind`, `getUnaryOperatorKindSpelling` and `getCursorUnaryOperatorKind` to get binary and unary operators.

**Comment by Romisajad** [comment]
@derekdai These functions are in C++ clang library not in python binding of clang library.

**Comment by derekdai** [comment]
> @derekdai These functions are in C++ clang library not in python binding of clang library.

Oh, I see. I didn't realize clang had an official Python binding. I thought this issue was reported to help develop the binding. My mistake.

**Comment by DeinAlptraum** [comment]
BinaryOperators have proper support in the bindings since #98489 
@Endilll same thing as the other issue, can you close this?
