### ISSUE TITLE
[mlir][tensor] Purpose of the `dest` operand is unclear

### ISSUE THREAD

**Issue by rikhuijzer** [llvm/llvm-project#70030]
Multiple tensor operations have an operand `dest`, but it's not so clear from the documentation of `tensor.pack` and `tensor.unpack` what the purpose of that operand is. The ops don't describe the operand apart from a description of its type. My assumption is that `dest` is mutated by the op because, for example, `tensor.insert` [states](https://mlir.llvm.org/docs/Dialects/TensorOps/#tensorinsert-tensorinsertop):

> The `tensor.insert` op inserts a scalar into a ranked tensor `dest` as specified by the operation’s indices.

That means that `dest` is mutated? This matches some tests that I see where the `dest` variable is returned.

If that's true, then there seems to be a bug with the canonicalizers. They don't assume the operands to be mutated. For example:

`mlir-opt -canonicalize` on the following code

```mlir
func.func @main(%dest : tensor<8x16x8x32xf32>) -> tensor<8x16x8x32xf32> {
  %cst = arith.constant dense<1.000000e-01> : tensor<64x128xf32>
  %0 = tensor.pack %cst outer_dims_perm = [1, 0] inner_dims_pos = [0, 1]
    inner_tiles = [8, 32] into %dest : tensor<64x128xf32> -> tensor<8x16x8x32xf32>
  return %dest : tensor<8x16x8x32xf32>
}
```

returns

```mlir
func.func @main(%arg0: tensor<8x16x8x32xf32>) -> tensor<8x16x8x32xf32> {
  return %arg0 : tensor<8x16x8x32xf32>
}
```
and for 
```mlir
func.func @main(%t: tensor<?xf32>, %idx: index, %f: f32) -> (tensor<?xf32>)
{
  %0 = tensor.insert %f into %t[%idx] : tensor<?xf32>
  return %t : tensor<?xf32>
}
```
it returns
```mlir
func.func @main(%arg0: tensor<?xf32>, %arg1: index, %arg2: f32) -> tensor<?xf32> {
  return %arg0 : tensor<?xf32>
}
```

**Comment by ubfx** [comment]
> That means that `dest` is mutated?

Tensors are never mutated. In your example `%0 = tensor.insert %f into %t[%idx] : tensor<?xf32>`, the Op makes a copy of the entire tensor `%t`, into which it inserts `%f` at the index `%idx`. That mutated copy is returned as `%0`.
After the Op is done, you have `%t`, which is unchanged, and you have `%0`, which is the same as `%t`, except at the index `%idx`. This is why, if you return `%t` from the function, the Op will be canonicalized away.

**Comment by ubfx** [comment]
Maybe we should add a sentence to the tensor dialect's description which explains the `dest` argument for `DestinationStyleOp`s (which would cover `insert`, `insert_slice`, `pack` and `unpack`)?:
"The TensorOps implementing `DestinationStyleOpInterface` have an input tensor argument `dest` which is used to encode information for bufferization."
And then link to https://mlir.llvm.org/docs/Bufferization/#destination-passing-style

**Comment by joker-eph** [comment]
> The tensor.insert op inserts a scalar into a ranked tensor dest as specified by the operation’s indices.

But on the very next line it says "It returns a copy of dest with the indexed position updated to the value of scalar"...


> "The TensorOps implementing DestinationStyleOpInterface have an input tensor argument dest which is used to encode information for bufferization."

These particular ops stands without the notion of bufferization or DestinationStyleOpInterface though, it's not like the `outs` of linalg which can be quite confusing.
Even ignoring bufferization, it follows well known patterns from LLVM: https://llvm.org/docs/LangRef.html#insertelement-instruction and https://llvm.org/docs/LangRef.html#insertvalue-instruction 


Feel free to send a PR to improve the doc though, to begin with reminding at the very beginning of the Tensor Dialect doc that `tensor` is an immutable object.

**Comment by rikhuijzer** [comment]
I keep trying to apply high level language knowledge to MLIR, but this is not a high level language!

Thanks again both for the explanation! I appreciate it and will try to open a PR soon.

**Comment by joker-eph** [comment]
>  I keep trying to apply high level language knowledge to MLIR, but this is not a high level language!

Actually there are high-level language which are functional and you'll find similar patterns, so I'd say that this pattern here is higher-level than what you may be used to actually :)
