### ISSUE TITLE
[HLSL] implement `asin` intrinsic

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#70080]
Implement HLSL `asin` intrinsic:

https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-asin

part of this proposal: https://discourse.llvm.org/t/rfc-all-the-math-intrinsics/78294

Four parts:
1. [x]   DXIL backend change
2. [x]  SPIRV backend change
3. [x]  HLSL frontend change
4. [x] Constraint intrinsic change

**Comment by farzonl** [comment]
resolved by https://github.com/llvm/llvm-project/pull/98949
