### ISSUE TITLE
[HLSL] implement `cosh` intrinsic

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#70084]
Implement HLSL `cosh` intrinsic:

https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-cosh

part of this proposal: https://discourse.llvm.org/t/rfc-all-the-math-intrinsics/78294

Four parts:
1. [x]  DXIL backend change
2. [x] SPIRV backend change
3. [x] HLSL frontend change
4. [x] Constraint intrinsic change

**Comment by farzonl** [comment]
resolved by https://github.com/llvm/llvm-project/pull/98949
