### ISSUE TITLE
[HLSL] implement `tan` intrinsic

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#70082]
Implement HLSL `tan` intrinsic:

https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-tan

**Comment by farzonl** [comment]
@llvm-beanz Can I have this one assigned to me?

**Comment by EugeneZelenko** [comment]
@farzonl: Just create pull request and mention it on this page.
