### ISSUE TITLE
Implement the `atan2` HLSL Function

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#70096]
Note atan2 has been identified as a potential generic llvm intrinsic:
Investigation: https://github.com/llvm/llvm-project/issues/87367's 
RFC: https://discourse.llvm.org/t/rfc-all-the-math-intrinsics/78294

- [x] Implement `atan2` clang builtin,
- [x] Link `atan2` clang builtin with `hlsl_intrinsics.h`
- [x] Add sema checks for `atan2` to `CheckHLSLBuiltinFunctionCall` in `SemaChecking.cpp`
- [x] Add codegen for `atan2` to `EmitHLSLBuiltinExpr` in `CGBuiltin.cpp`
- [x] Add codegen tests to `clang/test/CodeGenHLSL/builtins/atan2.hlsl`
- [ ] Add sema tests to `clang/test/SemaHLSL/BuiltIns/atan2-errors.hlsl`
- [ ]  ~Create the `int_atan2` intrinsic in `Intrinsics.td`~
- [ ] ~Create the `int_dx_atan2` intrinsic in `IntrinsicsDirectX.td`~
- [x] Create the `DXILOpMapping` of `int_atan2` to  `17` in `DXIL.td`
- [x] Create the  `atan2.ll` and `atan2_errors.ll` tests in `llvm/test/CodeGen/DirectX/`
- [ ] ~Create the `int_spv_atan2` intrinsic in `IntrinsicsSPIRV.td`~
- [ ] ~In SPIRVInstructionSelector.cpp create the `atan2` lowering and map  it to `int_spv_atan2` in `SPIRVInstructionSelector::selectIntrinsic`.~
- [x] In SPIRVInstructionSelector.cpp: `SPIRVInstructionSelector::spvSelect` Add
```cpp
  case TargetOpcode::G_FATAN2:
    return selectExtInst(ResVReg, ResType, I, CL::atan2, GL::Atan2);
```
- [ ] Create SPIR-V backend test case in `llvm/test/CodeGen/SPIRV/hlsl-intrinsics/atan2.ll`

## DirectX

| DXIL Opcode | DXIL OpName | Shader Model | Shader Stages |
| ----------- | ----------- | ------------ | ------------- |
| 17 | Atan | 6.0 | () |

## SPIR-V

# Atan2:

## Description:
**Atan2**  
  
Arc tangent. Result is an angle, in radians, whose tangent is *y* / *x*.
The signs of *x* and *y* are used to determine what quadrant the angle
is in. The range of result values is \[-π, π\] . Result is undefined if
*x* and *y* are both 0.  
  
The operand *x* and *y* must be a scalar or vector whose component type
is 16-bit or 32-bit floating-point.  
  
*Result Type* and the type of all operands must be the same type.
Results are computed per component.

<table>
<colgroup>
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
</colgroup>
<thead>
<tr>
<th>Number</th>
<th>Operand 1</th>
<th>Operand 2</th>
<th>Operand 3</th>
<th>Operand 4</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tableblock halign-left valign-top"><p>25</p></td>
<td
class="tableblock halign-left valign-top"><p><em>&lt;id&gt;</em><br />
<em>y</em></p></td>
<td
class="tableblock halign-left valign-top"><p><em>&lt;id&gt;</em><br />
<em>x</em></p></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>

### Example 1
```hlsl
//dxc atan2_test.hlsl -T lib_6_8  -enable-16bit-types -spirv -fspv-target-env=universal1.5 -fcgl -O0

export float4 fn(float4 p1, float4 p2) {
    return atan2(p1, p2);
}
```
## HLSL:

Returns the arctangent of two values (x,y).

| *ret* atan2(*y*, *x*) |
|-----------------------|

 

## Parameters

| Item                                                   | Description                    |
|--------------------------------------------------------|--------------------------------|
| <span id="y"></span><span id="Y"></span>*y*<br/> | \[in\] The y value.<br/> |
| <span id="x"></span><span id="X"></span>*x*<br/> | \[in\] The x value.<br/> |

 

## Return Value

The arctangent of (y,x).

## Remarks

The signs of the *x* and *y* parameters are used to determine the quadrant of the return values within the range of -π to π. The **atan2** HLSL intrinsic function is well-defined for every point other than the origin, even if *y* equals 0 and *x* does not equal 0.

## Type Description

| Name  | [**Template Type**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md)                                                  | [**Component Type**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md) | Size                           |
|-------|----------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------|--------------------------------|
| *y*   | same as input *x*                                                                                              | [**float**](/windows/desktop/WinProg/windows-data-types)                        | same dimension(s) as input *x* |
| *x*   | [**scalar**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md), **vector**, or **matrix** | [**float**](/windows/desktop/WinProg/windows-data-types)                        | any                            |
| *ret* | same as input *x*                                                                                              | [**float**](/windows/desktop/WinProg/windows-data-types)                        | same dimension(s) as input *x* |

 

## Minimum Shader Model

This function is supported in the following shader models.

| Shader Model                                                                       | Supported |
|------------------------------------------------------------------------------------|-----------|
| [Shader Model 2 (DirectX HLSL)](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-sm2.md) and higher shader models | yes       |
| [Shader Model 1 (DirectX HLSL)](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-sm1.md)                          | vs\_1\_1  |

 

## Requirements

| Requirement | Value |
|-------------------|--------------------------------------------------------------------------------------------|
| Header<br/> | <dl> <dt>Corecrt\_math.h</dt> </dl> |

## See also

<dl> <dt>

[**Intrinsic Functions (DirectX HLSL)**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md)
</dt> </dl>

**Comment by tex3d** [comment]
I can take this one.
