### ISSUE TITLE
Implement the `asuint` HLSL Function

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#70097]
- [ ] Implement `asuint` clang builtin,
- [ ] Link `asuint` clang builtin with `hlsl_intrinsics.h`
- [ ] Add sema checks for `asuint` to `CheckHLSLBuiltinFunctionCall` in `SemaChecking.cpp`
- [ ] Add codegen for `asuint` to `EmitHLSLBuiltinExpr` in `CGBuiltin.cpp`
- [ ] Add codegen tests to `clang/test/CodeGenHLSL/builtins/asuint.hlsl`
- [ ] Add sema tests to `clang/test/SemaHLSL/BuiltIns/asuint-errors.hlsl`

## DirectX

There were no DXIL opcodes found for  most `asuint` cases. There is an opcode for the three arg case:
| DXIL Opcode | DXIL OpName | Shader Model | Shader Stages | Description |
| ----------- | ----------- | ------------ | ------------- |------------- |
| 102 | SplitDouble| 6.0 | () | splits a double into low and high parts

## SPIR-V

There is no support for `asuint` when targeting SPIR-V.

### Example 1
```hlsl
//dxc asuint_test.hlsl -T lib_6_8 -enable-16bit-types -O0

export uint4 fn(double4 p1, uint4 p2, uint4 p3) {
    asuint(p1, p2, p3);
    return p3;
}
```

 ### Example 2
```hlsl
//dxc asuint_1_test.hlsl -T lib_6_8 -enable-16bit-types -O0

export uint4 fn(float p1) {
    return asuint(p1);
}
```
 ### Example 3
```hlsl
//dxc asuint_2_test.hlsl -T lib_6_8 -enable-16bit-types -O0

export uint4 fn(uint p1) {
    return asuint(p1);
}
```
 ### Example 4
```hlsl
//dxc asuint_3_test.hlsl -T lib_6_8 -enable-16bit-types -O0

export uint4 fn(int p1) {
    return asuint(p1);
}
```
## HLSL:

Interprets the bit pattern of *x* as an unsigned integer.

| ret asuint(*x*) |
|-----------------|

 

## Parameters

| Item                                                   | Description                        |
|--------------------------------------------------------|------------------------------------|
| <span id="x"></span><span id="X"></span>*x*<br/> | \[in\] The input value.<br/> |

 

## Return Value

The input interpreted as an unsigned integer.

## Type Description

| Name  | [**Template Type**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md)                                                  | [**Component Type**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md)                 | Size                           |
|-------|----------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------|--------------------------------|
| *x*   | [**scalar**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md), **vector**, or **matrix** | [**float**](/windows/desktop/WinProg/windows-data-types), [**int**](/windows/desktop/WinProg/windows-data-types) | any                            |
| *ret* | same as input *x*                                                                                              | [**uint**](/windows/desktop/WinProg/windows-data-types)                                         | same dimension(s) as input *x* |

 

## Minimum Shader Model

This function is supported in the following shader models.

| Shader Model                                                        | Supported |
|---------------------------------------------------------------------|-----------|
| [Shader Model 4](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-sm4.md) and higher shader models | yes       |
| [Shader Model 3 (DirectX HLSL)](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-sm3.md)           | no        |
| [Shader Model 2 (DirectX HLSL)](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-sm2.md)           | no        |
| [Shader Model 1 (DirectX HLSL)](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-sm1.md)           | no        |

 

## See also

<dl> <dt>

[**Intrinsic Functions (DirectX HLSL)**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md)
</dt> </dl>

**Comment by joaosaffran** [comment]
I can work on it
