### ISSUE TITLE
Implement the `asfloat` HLSL Function

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#70098]
- [ ] Link `asfloat` clang builtin (__builtin_bit_cast) with `hlsl_intrinsics.h``
- [ ] Add codegen tests to `clang/test/CodeGenHLSL/builtins/asfloat.hlsl`
- [ ] Add sema tests to `clang/test/SemaHLSL/BuiltIns/asfloat-errors.hlsl`

## DirectX

There were no DXIL opcodes found for `asfloat`.

### Example 1
```hlsl
//dxc asfloat_test.hlsl -T lib_6_8  -enable-16bit-types -spirv -fspv-target-env=universal1.5 -fcgl -O0

export float4 fn(float p1) {
    return asfloat(p1);
}
```
 ### Example 2
```hlsl
//dxc asfloat_1_test.hlsl -T lib_6_8 -enable-16bit-types -O0

export float4 fn(uint p1) {
    return asfloat(p1);
}
```
 ### Example 3
```hlsl
//dxc asfloat_2_test.hlsl -T lib_6_8 -enable-16bit-types -O0

export float4 fn(int p1) {
    return asfloat(p1);
}
```
## HLSL:

Interprets the bit pattern of *x* as a floating-point number.

| ret asfloat(*x*) |
|------------------|

 

## Parameters

| Item                                                   | Description                        |
|--------------------------------------------------------|------------------------------------|
| <span id="x"></span><span id="X"></span>*x*<br/> | \[in\] The input value.<br/> |

 

## Return Value

The input interpreted as a floating-point number.

## Type Description

| Name  | [**Template Type**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md)                                                  | [**Component Type**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md)                                                         | Size                           |
|-------|----------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------|--------------------------------|
| *x*   | [**scalar**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md), **vector**, or **matrix** | [**float**](/windows/desktop/WinProg/windows-data-types), [**int**](/windows/desktop/WinProg/windows-data-types), [**uint**](/windows/desktop/WinProg/windows-data-types) | any                            |
| *ret* | same as input *x*                                                                                              | [**float**](/windows/desktop/WinProg/windows-data-types)                                                                                | same dimension(s) as input *x* |

 

## Function Overloads

<dl> `float&lt;x&gt; asfloat(float&lt;x&gt; value);`  
`float&lt;x&gt; asfloat(int&lt;x&gt; value);`  
`float&lt;x&gt; asfloat(uint&lt;x&gt; value);`  
</dl>

## Minimum Shader Model

This function is supported in the following shader models.

| Shader Model                                                        | Supported |
|---------------------------------------------------------------------|-----------|
| [Shader Model 4](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-sm4.md) and higher shader models | yes       |
| [Shader Model 3 (DirectX HLSL)](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-sm3.md)           | no        |
| [Shader Model 2 (DirectX HLSL)](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-sm2.md)           | no        |
| [Shader Model 1 (DirectX HLSL)](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-sm1.md)           | no        |

 

## Remarks

Older compilers incorrectly allowed `asfloat(bool)`, but note that bool inputs are not supported.

## See also

<dl> <dt>

[**Intrinsic Functions (DirectX HLSL)**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md)
</dt> </dl>

**Comment by farzonl** [comment]
@damyanp This one is already refined, but we should prioritize getting it assigned out. This is used in DirectML shader [PixelPacking_Velocity.hlsli:28](https://github.com/microsoft/DirectXTK/blob/eb729567bb4efa9582b097b64635027399ec3b51/Src/Shaders/PixelPacking_Velocity.hlsli#L28) and [PixelPacking_Velocity.hlsli:41](https://github.com/microsoft/DirectXTK/blob/eb729567bb4efa9582b097b64635027399ec3b51/Src/Shaders/PixelPacking_Velocity.hlsli#L41)

**Comment by joaosaffran** [comment]
I can work on this

**Comment by joaosaffran** [comment]
This is currently awaiting changes on #107292 to be merged, such is introducing `bit_cast` implementation for HLSL, which is required for this changes.
