### ISSUE TITLE
[HLSL] implement `WaveGetLaneIndex` intrinsic

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#70105]
Implement HLSL `WaveGetLaneIndex` intrinsic:

https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/WaveGetLaneIndex

AC:
* The intrinsic is implemented and lowered to LLVM-IR
* Tests are implemented to validate that the IR is generated correctly

**Comment by damyanp** [comment]
Marking re-estimate this. Since this was originally refined, we have a different approach to implementing intrinsics and the way we've been estimating intrinsics has changed quite a bit.
