### ISSUE TITLE
Implement the `WaveReadLaneAt` HLSL Function

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#70104]
- [ ] Implement `WaveReadLaneAt` clang builtin,
- [ ] Link `WaveReadLaneAt` clang builtin with `hlsl_intrinsics.h`
- [ ] Add sema checks for `WaveReadLaneAt` to `CheckHLSLBuiltinFunctionCall` in `SemaChecking.cpp`
- [ ] Add codegen for `WaveReadLaneAt` to `EmitHLSLBuiltinExpr` in `CGBuiltin.cpp`
- [ ] Add codegen tests to `clang/test/CodeGenHLSL/builtins/WaveReadLaneAt.hlsl`
- [ ] Add sema tests to `clang/test/SemaHLSL/BuiltIns/WaveReadLaneAt-errors.hlsl`
- [ ] Create the `int_dx_WaveReadLaneAt` intrinsic in `IntrinsicsDirectX.td`
- [ ] Create the `DXILOpMapping` of `int_dx_WaveReadLaneAt` to  `117` in `DXIL.td`
- [ ] Create the  `WaveReadLaneAt.ll` and `WaveReadLaneAt_errors.ll` tests in `llvm/test/CodeGen/DirectX/`
- [ ] Create the `int_spv_WaveReadLaneAt` intrinsic in `IntrinsicsSPIRV.td`
- [ ] In SPIRVInstructionSelector.cpp create the `WaveReadLaneAt` lowering and map  it to `int_spv_WaveReadLaneAt` in `SPIRVInstructionSelector::selectIntrinsic`.
- [ ] Create SPIR-V backend test case in `llvm/test/CodeGen/SPIRV/hlsl-intrinsics/WaveReadLaneAt.ll`

## DirectX

| DXIL Opcode | DXIL OpName | Shader Model | Shader Stages |
| ----------- | ----------- | ------------ | ------------- |
| 117 | WaveReadLaneAt | 6.0 | ('library', 'compute', 'amplification', 'mesh', 'pixel', 'vertex', 'hull', 'domain', 'geometry', 'raygeneration', 'intersection', 'anyhit', 'closesthit', 'miss', 'callable', 'node') |

## SPIR-V

# [OpGroupNonUniformShuffle](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpGroupNonUniformShuffle):

## Description:
  
Result is the *Value* of the [invocation](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Invocation) identified by the
id *Id*.  
  
*Result Type* must be a scalar or vector of [*floating-point
type*](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Floating), [*integer type*](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Integer), or [*Boolean
type*](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Boolean).  
  
*Execution* is a [*Scope*](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Scope_-id-) that identifies the group of
invocations affected by this command.  
  
The type of *Value* must be the same as *Result Type*.  
  
*Id* must be a scalar of [*integer type*](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Integer), whose *Signedness*
operand is 0.  
  
The resulting value is undefined if *Id* is an inactive invocation, or
is greater than or equal to the size of the group.

[Capability](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Capability):  
**GroupNonUniformShuffle**  
  
[Missing before](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Unified) **version 1.3**.

<table style="width:100%;">
<colgroup>
<col style="width: 14%" />
<col style="width: 14%" />
<col style="width: 14%" />
<col style="width: 14%" />
<col style="width: 14%" />
<col style="width: 14%" />
<col style="width: 14%" />
</colgroup>
<thead>
<tr>
<th>Word Count</th>
<th>Opcode</th>
<th>Results</th>
<th>Operands</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td class="tableblock halign-left valign-top"><p>6</p></td>
<td class="tableblock halign-left valign-top"><p>345</p></td>
<td
class="tableblock halign-left valign-top"><p><em>&lt;id&gt;</em><br />
<em>Result Type</em></p></td>
<td class="tableblock halign-left valign-top"><p><a
href="#ResultId"><em>Result &lt;id&gt;</em></a></p></td>
<td class="tableblock halign-left valign-top"><p><a
href="#Scope_-id-"><em>Scope &lt;id&gt;</em></a><br />
<em>Execution</em></p></td>
<td
class="tableblock halign-left valign-top"><p><em>&lt;id&gt;</em><br />
<em>Value</em></p></td>
<td
class="tableblock halign-left valign-top"><p><em>&lt;id&gt;</em><br />
<em>Id</em></p></td>
</tr>
</tbody>
</table>

### Example 1
```hlsl
//dxc WaveReadLaneAt_test.hlsl -T lib_6_8 -E fn -enable-16bit-types -spirv -fspv-target-env=universal1.5 -fcgl -O0

export float4 fn(float4 p1, uint p2) {
    return WaveReadLaneAt(p1, p2);
}
```
## HLSL:

Returns the value of the expression for the given lane index within the specified wave.

## Syntax

``` syntax
<type> WaveReadLaneAt(
   <type> expr,
   uint laneIndex
);
```

## Parameters

<dl> <dt>

*expr* 
</dt> <dd>

The expression to evaluate.

</dd> <dt>

*laneIndex* 
</dt> <dd>

The index of the lane for which the *expr* result will be returned.

</dd> </dl>

## Return value

The resulting value is the result of *expr*. It will be uniform if *laneIndex* is uniform.

## Remarks

If *laneIndex* is uniform, then this is effectively a broadcast operation; otherwise, it's a shuffle operation.

The result is undefined on a helper lane, or if the lane referred to by *laneIndex* is inactive or a helper lane.

This function is supported from shader model 6.0 in all shader stages.

## See also

* [Overview of Shader Model 6](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/hlsl-shader-model-6-0-features-for-direct3d-12.md)
* [Shader Model 6](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/shader-model-6-0.md)

**Comment by inbelic** [comment]
Taking a look into this.

**Comment by damyanp** [comment]
Marking re-estimate this. Since this was originally refined, we have a different approach to implementing intrinsics and the way we've been estimating intrinsics has changed quite a bit.
