### ISSUE TITLE
Implement the `GroupMemoryBarrierWithGroupSync` HLSL Function

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#70103]
AC:
* The intrinsic is implemented
* Tests validate that it is lowered to LLVM-IR
* Tests validate that control forms are not hoisted out of control flow
** Maps to the correct construct

- [ ] Implement `GroupMemoryBarrierWithGroupSync` clang builtin,
- [ ] Link `GroupMemoryBarrierWithGroupSync` clang builtin with `hlsl_intrinsics.h`
- [ ] Add sema checks for `GroupMemoryBarrierWithGroupSync` to `CheckHLSLBuiltinFunctionCall` in `SemaChecking.cpp`
- [ ] Add codegen for `GroupMemoryBarrierWithGroupSync` to `EmitHLSLBuiltinExpr` in `CGBuiltin.cpp`
- [ ] Add codegen tests to `clang/test/CodeGenHLSL/builtins/GroupMemoryBarrierWithGroupSync.hlsl`
- [ ] Add sema tests to `clang/test/SemaHLSL/BuiltIns/GroupMemoryBarrierWithGroupSync-errors.hlsl`
- [ ] Create the `int_dx_GroupMemoryBarrierWithGroupSync` intrinsic in `IntrinsicsDirectX.td`
- [ ] Create the `DXILOpMapping` of `int_dx_GroupMemoryBarrierWithGroupSync` to  `80` in `DXIL.td`
- [ ] Create the  `GroupMemoryBarrierWithGroupSync.ll` and `GroupMemoryBarrierWithGroupSync_errors.ll` tests in `llvm/test/CodeGen/DirectX/`
- [ ] Create the `int_spv_GroupMemoryBarrierWithGroupSync` intrinsic in `IntrinsicsSPIRV.td`
- [ ] In SPIRVInstructionSelector.cpp create the `GroupMemoryBarrierWithGroupSync` lowering and map  it to `int_spv_GroupMemoryBarrierWithGroupSync` in `SPIRVInstructionSelector::selectIntrinsic`.
- [ ] Create SPIR-V backend test case in `llvm/test/CodeGen/SPIRV/hlsl-intrinsics/GroupMemoryBarrierWithGroupSync.ll`

## DirectX

| DXIL Opcode | DXIL OpName | Shader Model | Shader Stages |
| ----------- | ----------- | ------------ | ------------- |
| 80 | Barrier | 6.0 | () |

## SPIR-V

# [OpControlBarrier](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpControlBarrier):

## Description:
  
Wait for all active invocations within the specified
[*Scope*](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Scope_-id-) to reach the current point of execution.  
  
All active [invocations](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Invocation) within *Execution* scope reach
this point of execution before any invocation proceeds beyond it.  
  
When *Execution* is **Workgroup** or larger, behavior is undefined
unless all invocations within *Execution* execute the same dynamic
instance of this instruction.  
  
If *Semantics* is not **None**, this instruction also serves as an
[**OpMemoryBarrier**](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpMemoryBarrier) instruction, and also performs
and adheres to the description and semantics of an **OpMemoryBarrier**
instruction with the same *Memory* and *Semantics* operands. This allows
atomically specifying both a control barrier and a memory barrier (that
is, without needing two instructions). If *Semantics* is **None**,
*Memory* is ignored.  
  
Before **version 1.3**, it is only valid to use this instruction with
**TessellationControl**, **GLCompute**, or **Kernel** [execution
models](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Execution_Model). There is no such restriction starting with
**version 1.3**.  
  
If used with the **TessellationControl** [execution
model](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Execution_Model), it also implicitly synchronizes the **Output**
[Storage Class](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Storage_Class): Writes to **Output** variables
performed by any invocation executed prior to a **OpControlBarrier** are
visible to any other invocation proceeding beyond that
**OpControlBarrier**.

<table>
<colgroup>
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
</colgroup>
<thead>
<tr>
<th>Word Count</th>
<th>Opcode</th>
<th>Results</th>
<th>Operands</th>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td class="tableblock halign-left valign-top"><p>4</p></td>
<td class="tableblock halign-left valign-top"><p>224</p></td>
<td class="tableblock halign-left valign-top"><p><a
href="#Scope_-id-"><em>Scope &lt;id&gt;</em></a><br />
<em>Execution</em></p></td>
<td class="tableblock halign-left valign-top"><p><a
href="#Scope_-id-"><em>Scope &lt;id&gt;</em></a><br />
<em>Memory</em></p></td>
<td class="tableblock halign-left valign-top"><p><a
href="#Memory_Semantics_-id-"><em>Memory Semantics
&lt;id&gt;</em></a><br />
<em>Semantics</em></p></td>
</tr>
</tbody>
</table>

### Example 1
```hlsl
//dxc GroupMemoryBarrierWithGroupSync_test.hlsl -T lib_6_8  -enable-16bit-types -spirv -fspv-target-env=universal1.5 -fcgl -O0

export void fn() {
    return GroupMemoryBarrierWithGroupSync();
}
```
## HLSL:

Blocks execution of all threads in a group until all group shared accesses have been completed and all threads in the group have reached this call.

## Syntax

``` syntax
void GroupMemoryBarrierWithGroupSync(void);
```

## Parameters

This function has no parameters.

## Return value

This function does not return a value.

## Remarks

The behavior of calls to this function that are within diverging branches of a thread group are undefined.

### Minimum Shader Model

This function is supported in the following shader models.

| Shader Model                                                                | Supported |
|-----------------------------------------------------------------------------|-----------|
| [Shader Model 5](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/d3d11-graphics-reference-sm5.md) and higher shader models | yes       |

 

This function is supported in the following types of shaders:

| Vertex | Hull | Domain | Geometry | Pixel | Compute |
|--------|------|--------|----------|-------|---------|
|        |      |        |          |       | x       |

 

## See also

<dl> <dt>

[Intrinsic Functions](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md)
</dt> <dt>

[Shader Model 5](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/d3d11-graphics-reference-sm5.md)
</dt> </dl>

**Comment by damyanp** [comment]
Marking re-estimate this. Since this was originally refined, we have a different approach to implementing intrinsics and the way we've been estimating intrinsics has changed quite a bit.

**Comment by adam-yang** [comment]
I'll be working on this.
