### ISSUE TITLE
[HLSL] MS-style `for` and `while` statement `unroll` attribute

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#70114]
HLSL `for` and `while` loops support Microsoft-syntax attributes. For Phase 1 we need to support parsing the `unroll` attribute:

https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-for
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-while

AC:
Investigate if we can implement the `unroll` attribute via the clang `loophint` attribute
if there are differences then additional work items will be created for later phases

**Comment by damyanp** [comment]
@llvm-beanz  - checking here - the title seems to suggest that this involves actually implementing `[unroll]`, but the AC suggests it is more of an investigation?

**Comment by llvm-beanz** [comment]
That's probably poor issue writing on my part. The AC should really be "this feature should work and be tested".

My hope is that this can just be implemented in terms of the existing loop hint support, and I wanted to track that since I probably won't be the person to actually do this work. I haven't had time to investigate further to verify that the existing mechanisms will handle our needs so it is possible this task is bigger than I suspect.

**Comment by farzonl** [comment]
dxc examples: 
- for loop: https://hlsl.godbolt.org/z/8EK6Pa139
- while loop:  https://hlsl.godbolt.org/z/ebr5MvEcK
- do while: https://hlsl.godbolt.org/z/be8cedoTs
