### ISSUE TITLE
ambiguous deduction for template arguments  with std::monostate

### ISSUE THREAD

**Issue by makotokato** [llvm/llvm-project#70162]
```c++
#include <utility>
#include <variant>

template <class T> struct Ok {
  T inner;
  Ok(T &&i) : inner(std::move(i)) {}
  template <typename X = T, typename = typename std::enable_if<
                                std::is_trivially_copyable<X>::value>::type>
  Ok(T i) : inner(i) {}
  Ok() = default;
};

int main() {
  auto a = Ok(std::monostate());
  return 0;
}
```

When building this C++ source, clang throws the following error.  I test on "Debian clang version 16.0.6 (15)" and "17.0.1" on godbolt.org. gcc 13.2 works well.

```
main.cpp:14:12: error: ambiguous deduction for template arguments of 'Ok'
  auto a = Ok(std::monostate());
           ^
main.cpp:6:3: note: candidate function [with T = std::monostate]
  Ok(T &&i) : inner(std::move(i)) {}
  ^
main.cpp:9:3: note: candidate function [with T = std::monostate, X = std::monostate, $2 = void]
  Ok(T i) : inner(i) {}
  ^
```

**Comment by shafik** [comment]
Looks like this is fixed in trunk: https://godbolt.org/z/eeb6Gc6ja

Not sure what fixed this though.

CC @cor3ntin @AaronBallman

**Comment by Manishearth** [comment]
Also worth knowing if there is a way to design code ike this that avoids this bug, even if it is considered a bug. The reduced case in the issue ultimately comes from this barebones result type: https://github.com/rust-diplomat/diplomat/blob/main/tool/src/cpp/runtime.hpp
