### ISSUE TITLE
[C++20] [Modules] Is it a real ODR violation to have non-inline template forward decl followed with inline template decl?

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#70173]
Reproducer:

```
// RUN: rm -rf %t
// RUN: split-file %s %t
// RUN: cd %t
//
// RUN: %clang_cc1 -std=c++20 %t/bar.cppm -emit-module-interface -o %t/bar.pcm
// RUN: %clang_cc1 -std=c++20 %t/foo.cppm -emit-module-interface -o %t/foo.pcm \
// RUN:     -fmodule-file=bar=%t/bar.pcm
// RUN: %clang_cc1 -std=c++20 %t/main.cc -fsyntax-only -verify -fprebuilt-module-path=%t

//--- bar.cppm
module;
#include "templfwd.h"
export module bar;
export using sss::isspace;

//--- foo.cppm
module;
#include "templdecl.h"
export module foo;
import bar;
export using sss::isspace;

//--- main.cc
// expected-no-diagnostics
import foo;
#include "templdecl.h"
int main(void)
{
}

//--- templdecl.h
#ifndef _TEMPDECL_H
#define _TEMPDECL_H
#include "templfwd.h"
namespace sss
{
  template <typename T>
  inline void
  isspace() { return; }
}
#endif

//--- templfwd.h
#ifndef _TEMPFWD_H
#define _TEMPFWD_H
namespace sss
{
  template <typename T>
  void isspace();
}
#endif
```

This was an issue report that I received internally. And it is confusing and I feel it is worth to share it. (I feel github issues is good since others who got confused too can reach this by searching).

The reproducer above was reproduced from the implementation of `isspace()` from locale librarries of libstdc++. The diagnostic message in `main.cc` is "inline declaration of 'isspace' follows non-inline definition".  This was confusing since it looks like a compiler bug. However,  http://eel.is/c++draft/dcl.inline#5 says clearly that it is an ill-formed program. And according to http://eel.is/c++draft/localization, it is the problem of libstdc++ to mark the definition of isspace as `inline`. Since it is not comforming with the standard.

So the behavior of the compiler may be correct.

**Comment by dwblaikie** [comment]
I mean, I get the same failure in a non-modular case, so it sounds like probably this isn't OK?
```
$ cat simple.cpp
template<typename T>
void isspace() { return; }
template<typename T>
inline void isspace();
$ clang-tot -std=c++20 simple.cpp -fsyntax-only
simple.cpp:4:13: error: inline declaration of 'isspace' follows non-inline definition
    4 | inline void isspace();
      |             ^
simple.cpp:2:6: note: previous definition is here
    2 | void isspace() { return; }
      |      ^
1 error generated.
```

**Comment by dwblaikie** [comment]
I guess in this case maybe the bug is that something thinks the "previous definition" is non-inline, when it is inline?

**Comment by ChuanqiXu9** [comment]
> I mean, I get the same failure in a non-modular case, so it sounds like probably this isn't OK?
> 
> ```
> $ cat simple.cpp
> template<typename T>
> void isspace() { return; }
> template<typename T>
> inline void isspace();
> $ clang-tot -std=c++20 simple.cpp -fsyntax-only
> simple.cpp:4:13: error: inline declaration of 'isspace' follows non-inline definition
>     4 | inline void isspace();
>       |             ^
> simple.cpp:2:6: note: previous definition is here
>     2 | void isspace() { return; }
>       |      ^
> 1 error generated.
> ```

According to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66995, it looks like the behavior of clang is correct
