### ISSUE TITLE
Flang's documentation build is broken

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#70199]
https://lab.llvm.org/buildbot/#/builders/89/builds/50248/steps/5/logs/stdio

Flang's documentation broke when we had to update to myst to stop using a deprecated package, but new issues have been steadily cropping up since then as well. This also impacts the public documentation:

May 2023: https://web.archive.org/web/20230528023511/https://flang.llvm.org/docs/FlangCommandLineReference.html
Today: https://flang.llvm.org/docs/FlangCommandLineReference.html

**Comment by asl** [comment]
Tagging @llvm/issue-subscribers-flang-frontend as it seems that `flang` label is not watched

**Comment by kiranchandramohan** [comment]
@pmccormick are you looking into this issue? Please let me know if you need help.

**Comment by h-vetinari** [comment]
FWIW, I had [flagged](https://discourse.llvm.org/t/flang-homepage-is-broken/73603) this a couple of weeks ago already. The documentation is unfortunately lagging quite a bit behind the fast-paced compiler efforts (another example: #62310). I'd hope the flang stakeholders can allocate some dedicated time to documentation eventually...
