### ISSUE TITLE
[clang] not supporting floating point type as non-type template argument

### ISSUE THREAD

**Issue by yxsamliu** [llvm/llvm-project#70214]
The following code compiles with gcc trunk but fails with clang trunk:

```c++
#include <stdio.h>
template <float f>
void func_template()
{
    printf("\nValue: %f\n", f);
}

void test()
{
    func_template<1.f>();
}
```

https://godbolt.org/z/hv9K35oPK

It seem this should be allowed for c++20 

https://en.cppreference.com/w/cpp/language/template_parameters#Non-type_template_parameter

The issue was first reported at https://github.com/ROCm-Developer-Tools/HIP/issues/3338

**Comment by shafik** [comment]
It looks like this change was brought in by [p1907r1](https://wg21.link/p1907r1) and according the [clang status page](https://clang.llvm.org/cxx_status.html) it is only partially implemented.

**Comment by shafik** [comment]
Related: https://github.com/llvm/llvm-project/issues/56695

**Comment by cor3ntin** [comment]
https://reviews.llvm.org/D140996 has been inactive for a while. We should find someone to push that through the finish line @AaronBallman @zygoloid

**Comment by cor3ntin** [comment]
Fixed in Clang 18
