### ISSUE TITLE
libc++, find(char*, char*, int) does not optimize to memchr 

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [llvm/llvm-project#70238]
Seems like this case was missed in recent changes. For int constants it seems important~ish, like  find 0.
https://godbolt.org/z/3r68MxWrc

Issue was found by @pdimov

**Comment by philnik777** [comment]
Kind-of unrelated, but we're also missing the optimization for `signed char` and `char`: https://godbolt.org/z/5Yv6fWrcc
