### ISSUE TITLE
`-march=rv64gc -munaligned-access` should define `__riscv_misaligned_fast`

### ISSUE THREAD

**Issue by sh1boot** [llvm/llvm-project#70275]
`-munaligned-access` enables optimisations involving un-aligned loads and stores on RISC-V, but it does not signal this via the preprocessor, which I think it's supposed to?: https://github.com/riscv-non-isa/riscv-c-api-doc/blob/master/riscv-c-api.md

The following comes up empty:

    clang-18 --target=riscv64 -march=rv64gc -munaligned-access -dM -E -xc /dev/null | grep riscv_unaligned

Diff in godbolt doesn't reveal anything: https://godbolt.org/z/sb6rnvP4n

But recent GCC does define `__riscv_misaligned_fast` or `__riscv_misaligned_slow` depending on its configuration: https://godbolt.org/z/YEc4nb3Kf

**Comment by topperc** [comment]
There's a patch under review here https://github.com/llvm/llvm-project/pull/65756

**Comment by dtcxzyw** [comment]
Closed as #65756 has been merged. Now clang defines `__riscv_misaligned_fast` with `-munaligned-access` or `-mno-strict-align`.
