### ISSUE TITLE
Arm count leading sign should be trivial to implement with count leading zero

### ISSUE THREAD

**Issue by Validark** [llvm/llvm-project#70277]
This code should give me a count-leading-sign operation on arm:

```zig
export fn cls(x: u64) u64 {
    return @clz(if ((x >> 63) == 1) ~x else x);
}
```

At the moment, I get:

```asm
cls:
        eor     x8, x0, x0, asr #63
        clz     x0, x8
        ret
```

[Godbolt link](https://zig.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:3,lang:zig,selection:(endColumn:2,endLineNumber:3,positionColumn:2,positionLineNumber:3,selectionStartColumn:2,selectionStartLineNumber:3,startColumn:2,startLineNumber:3),source:'export+fn+cls(x:+u64)+u64+%7B%0A++++return+@clz(if+((x+%3E%3E+63)+%3D%3D+1)+~x+else+x)%3B%0A%7D'),l:'5',n:'0',o:'Zig+source+%233',t:'0')),header:(),k:75.37473958716589,l:'4',m:33.494883413858304,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:ztrunk,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:2,lang:zig,libs:!(),options:'-O+ReleaseFast+-target+aarch64-linux+-mcpu%3Dapple_latest',overrides:!(),selection:(endColumn:12,endLineNumber:4,positionColumn:12,positionLineNumber:4,selectionStartColumn:12,selectionStartLineNumber:4,startColumn:12,startLineNumber:4),source:3),l:'5',n:'0',o:'+zig+trunk+(Editor+%233)',t:'0')),l:'4',m:66.50511658614172,n:'0',o:'',s:0,t:'0')),k:100.00000000000001,l:'3',n:'0',o:'',t:'0')),version:4)

**Comment by topperc** [comment]
These are the patterns AARch64 has implemented for this

```
def : Pat<(ctlz (or (shl (xor (sra GPR32:$Rn, (i64 31)), GPR32:$Rn), (i64 1)),   
                (i32 1))),                                                       
          (CLSWr GPR32:$Rn)>;                                                    
def : Pat<(ctlz (or (shl (xor (sra GPR64:$Rn, (i64 63)), GPR64:$Rn), (i64 1)),   
                (i64 1))),                                                       
          (CLSXr GPR64:$Rn)>;
```

**Comment by topperc** [comment]
I'm not an ARM instruction expert at all.

gcc seems to use cls for __builtin_clrsb. Which I think means the instruction counts the number of redundant or extract sign bits. The number of bits after the MSB that are the same as the MSB. That's different than your pattern.

Unfortunately, it also appears clang misses using cls for __builtin_clrsb. https://godbolt.org/z/dW8v6EEE5

**Comment by Validark** [comment]
> gcc seems to use cls for __builtin_clrsb. Which I think means the instruction counts the number of redundant or extract sign bits. The number of bits after the MSB that are the same as the MSB. That's different than your pattern.

Isn't that what my code does? If the top bit is 1, it counts the leading 1's, if the top bit is 0, it counts the leading 0's.
