### ISSUE TITLE
[libcxx] a question about: true ? std::declval<_Tp>() : std::declval<_Up>()

### ISSUE THREAD

**Issue by alanguo1234** [llvm/llvm-project#70295]
Hi 
   a little curious at common_type.h, it have below code:
template <class _Tp, class _Up>
struct __common_type2_imp<_Tp, _Up, __void_t<decltype(true ? std::declval<_Tp>() : std::declval<_Up>())> > {

typedef _LIBCPP_NODEBUG __decay_t<decltype(true ? std::declval<_Tp>() : std::declval<_Up>())> type;
};

why not directly use  std::declval<_Tp>() , thanks

**Comment by frederick-vs-ja** [comment]
`std::declval<_Tp>()` and `std::declval<_Up>()` may be of different type and we need to calculate their common type.

E.g., when `_Tp` is `char` and `_Up` is `unsigned char`, the result type should be `int` (on most platforms).

See also [this page](https://en.cppreference.com/w/cpp/types/common_type).

**Comment by alanguo1234** [comment]
decltype(true ? std::declval<_Tp>() : std::declval<_Up>())， the condition is true ,why not directly use decltype(std::declval<_Tp>())

**Comment by philnik777** [comment]
As @frederick-vs-ja explained, we care about the type, not the value. `decltype(true ? std::declval<_Tp>() : std::declval<_Up>())` can be a type that is neither `_Tp` nor `_Up`.
