### ISSUE TITLE
Missed optimization opportunity in (z >= 0) && (x >= y + z) && (x >= y);

### ISSUE THREAD

**Issue by krtab** [llvm/llvm-project#70374]
Hi!

I'm not too familiar LLVM. I was investigating this rustc issue https://github.com/rust-lang/rust/issues/82801 and I realized that in the following Rust code, the last (x >= y) check is not optimized away:

```rust
#![feature(unchecked_math)]

#[no_mangle]
pub unsafe fn foo(x: u32, y : u32, z: u32) -> bool {
    (x >= y.unchecked_add(z)) && (x >= y)
}
```

I wrote what I believe is an equivalent C code, using the fact that overflow is UB on signed integers

```C
bool foo(int x, int y, int z) {
    return (z >= 0) && (x >= y + z) && (x >= y);
}
```

but using clang trunk I get

```asm
foo:                                    # @foo
        test    edx, edx
        setns   cl
        add     edx, esi
        cmp     edx, edi
        setle   dl
        cmp     edi, esi
        setge   al
        and     al, cl
        and     al, dl
        ret
```

whereas GCC properly removes the last comparison

```asm
foo:
        xor     eax, eax
        test    edx, edx
        js      .L1
        add     edx, esi
        cmp     edx, edi
        setle   al
.L1:
        ret
```

edit:

Weirdly enough, the code below is well optimized by clang 17 but **not** by goldbot's clang trunk version, so there is a possible regression.

```C
bool foo(int x, int y, int z) {
    if (z >= 0) if (x >= y + z) return (x >= y);
    return (z >= 0) && (x >= y + z) && (x >= y);
}
```

**Comment by dtcxzyw** [comment]
https://alive2.llvm.org/ce/z/v5GPts

**Comment by pinskia** [comment]
I noticed GCC does not optimize the case where `s/&&/&` is done, filed https://gcc.gnu.org/bugzilla/show_bug.cgi?id=112386 for that.

**Comment by krtab** [comment]
Thanks @dtcxzyw !
