### ISSUE TITLE
undefined behavior sanitizer check for `bsr `

### ISSUE THREAD

**Issue by wheatman** [llvm/llvm-project#70370]
the following code has undefined behavior
```
static inline long bsr_long(long word) {
  long result;
  __asm__("bsrq %1, %0" : "=r"(result) : "r"(word));
  return static_cast<long>(result);
}


int main() {
    return bsr_long(0);
}
```

https://godbolt.org/z/39rfj6ceM

since `bsr` is undefined for 0 input

It would be nice if a check could be added for this.

**Comment by MaskRay** [comment]
When src==0, ZF bit is set to 1 while dest is undefined. So the use case is valid...

Clang parses inline asm to know whether the instruction is parsed correctly, but doesn't do much with it.
Verifying whether instructions are used likely in an expected way seems out of its business...
