### ISSUE TITLE
Question: the option name "-fgpu-exclude-wrong-side-overloads" is confusing

### ISSUE THREAD

**Issue by zhiweij1** [llvm/llvm-project#70397]
```
  // [CUDA] HD->H or HD->D calls are technically not allowed by CUDA but
  // are accepted by both clang and NVCC. However, during a particular
  // compilation mode only one call variant is viable. We need to
  // exclude non-viable overload candidates from consideration based
  // only on their host/device attributes. Specifically, if one
  // candidate call is WrongSide and the other is SameSide, we ignore
  // the WrongSide candidate.
  // We only need to remove wrong-sided candidates here if
  // -fgpu-exclude-wrong-side-overloads is off. When
  // -fgpu-exclude-wrong-side-overloads is on, all candidates are compared
  // uniformly in isBetterOverloadCandidate.
  if (S.getLangOpts().CUDA && !S.getLangOpts().GPUExcludeWrongSideOverloads) {
    const FunctionDecl *Caller = S.getCurFunctionDecl(/*AllowLambda=*/true);
```
https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaOverload.cpp#L10597-L10609

The option name is "gpu-exclude-wrong-side-overloads", but the comment said candidates need to be removed only when it is off.
And the condition in the below if-stmt also check if the option is off.

It seems that the option name is incorrect, should it be "gpu-include-wrong-side-overloads" ?

**Comment by Artem-B** [comment]
acb6f80d96b74af3ec515bb9811d213abb406c31 has more details. I do not recall all the details and I don't think I ever seen the option used in practice.

@yxsamliu may be the right person to talk to.

**Comment by yxsamliu** [comment]
The review https://reviews.llvm.org/D80450 has a better explanation about the name of the option:

How about -fgpu-exclude-wrong-side-overloads? Since what this patch does is always excluding wrong side overloads whereas previously only excluding wrong side overloads if there are same side overloads.

**Comment by zhiweij1** [comment]
Thank for @yxsamliu 's explanation. I will close this issue.
