### ISSUE TITLE
compiler abort (flang-new 18.0.0)

### ISSUE THREAD

**Issue by mfvalin** [llvm/llvm-project#70463]
```
subroutine example_027
  use ISO_C_BINDING
  implicit none
  type, BIND(C) :: demo
    integer(C_INT64_T) :: i64
  end type
  interface
    function demo_init(d) result(r) bind(C, name='init_demo')
      import :: demo
      type(demo), intent(IN), value :: d
      type(demo) :: r
    end
  end interface
  type(demo) :: d
  d = demo_init(d)
end

```
compiling with
`flang-new -flang-experimental-polymorphism -flang-experimental-hlfir -c `
produces a compiler crash
[report.txt](https://github.com/llvm/llvm-project/files/13190399/report.txt)
[bug-745257.sh](https://github.com/llvm/llvm-project/files/13190679/bug-745257.sh.txt)
[bug-745257](https://github.com/llvm/llvm-project/files/13190680/bug-745257.txt)

**Comment by DavidSpickett** [comment]
https://github.com/llvm/llvm-project/pull/83285 removed the `-flang-experimental-polymorphism` flang and now that feature is enabled by default.

The example no longer crashes the compiler. flang 19 will be the first fixed version.
