### ISSUE TITLE
[fast-math] Is it more reasonable to check whether the function attribute has the `unsafe-fp-math` flag or whether a single IR has the fast-math attribute?

### ISSUE THREAD

**Issue by erickq** [llvm/llvm-project#70533]
I recently ran into a problem in my work. I added fast-math when compiling a source program. When I did an optimization, I didn't know whether to check the function attribute or the LLVM ir flag.

For example, in the preceding IR, I want to optimize the `llvm.fmuladd.f64` intrinsic. The `unsafe-fp-math` flag exists in the attribute function. My question is, is this IR wrong? Because fast-math is enabled in the compiler, `llvm.fmuladd.f64` must contain fast-related attributes.

![image](https://github.com/llvm/llvm-project/assets/12108571/69381faa-8027-4094-a31c-5d405af7dd2d)

**Comment by erickq** [comment]
Can someone help me with this? Thank you very much.

**Comment by arsenm** [comment]
Use the flags whenever possible. We've been trying to move away from the fast math attributes for many years
