### ISSUE TITLE
[libc++] __cpp_lib_ranges is defined without all views being available

### ISSUE THREAD

**Issue by philnik777** [llvm/llvm-project#70557]
We've but `views::join` behind `_LIBCPP_ENABLE_EXPERIMENTAL`, but we didn't put `__cpp_lib_ranges` behind `_LIBCPP_ENABLE_EXPERIMENTAL`.

**Comment by changkhothuychung** [comment]
I am not sure how difficult this can be, but if there is some instruction I would like to take this one.

**Comment by ldionne** [comment]
I would suggest closing this without any resolution -- we're about to take `join_view` out of experimental state with https://github.com/llvm/llvm-project/pull/66033.

**Comment by frederick-vs-ja** [comment]
Maybe related: `__cpp_lib_ranges` is currently defined as `202207L` but `std::range_adaptor_closure` is not yet implemented.

**Comment by h-2** [comment]
> Maybe related: `__cpp_lib_ranges` is currently defined as `202207L` but `std::ranges::range_adaptor_closure` is not yet implemented.

I have just run into this 😭 

I previously had:
```cpp
#if defined(__cpp_lib_ranges) && __cpp_lib_ranges >= 202202L
template <typename T>
using range_adaptor_closure = std::ranges::range_adaptor_closure<T>;
#elif defined(__GLIBCXX__)
template <typename T>
    requires(std::is_class_v<T> && std::same_as<T, std::remove_cv_t<T>>)
struct range_adaptor_closure : std::ranges::views::__adaptor::_RangeAdaptorClosure
{};
#elif defined(_LIBCPP_VERSION)
template <typename T>
using range_adaptor_closure = std::__range_adaptor_closure<T>;
#else
#    error "Requires modern standard library or older libstdc++ or libc++."
#endif
```
Now, I will need to add more checks...

**Comment by philnik777** [comment]
Closing, since join_view isn't experimental anymore.
