### ISSUE TITLE
Mojo failed to install on Ubuntu 22.04.3 

### ISSUE THREAD

**Issue by diylocals** [llvm/llvm-project#70558]
sudo apt-get update && \
sudo apt-get install modular && \
modular clean && \
modular install mojo
Hit:1 http://za.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://za.archive.ubuntu.com/ubuntu jammy-updates InRelease          
Hit:3 http://za.archive.ubuntu.com/ubuntu jammy-backports InRelease            
Get:4 https://dl.modular.com/public/installer/deb/ubuntu jammy InRelease [5,076 B]
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Fetched 5,076 B in 1s (3,480 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
modular is already the newest version (0.2.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: modular clean
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  modular   0x000055e60e916d47
1  modular   0x000055e60e9149fe
2  modular   0x000055e60e91740f
3  libc.so.6 0x00007f5951642520
4  modular   0x000055e60fa6c490
5  modular   0x000055e60fa6c7bb
6  modular   0x000055e60ecf7885
7  modular   0x000055e60e8d893a
8  libc.so.6 0x00007f5951629d90
9  libc.so.6 0x00007f5951629e40 __libc_start_main + 128
10 modular   0x000055e60e8d86ee
Illegal instruction (core dumped)

**Comment by diylocals** [comment]
Hi everyone. Was in the process of installing Mojo, but this failed. Please let me know if you've had similar issues and if there are any fixes.

**Comment by DimitryAndric** [comment]
Not sure if Mojo is an llvm-project sub-project? But it might be using llvm components, and has not updated the bug submission URL. In any case, without a reproducer or a backtrace it will probably be impossible to debug this issue.

**Comment by diylocals** [comment]
For info, Mojo is a new programming language created by Modular. Never done a backtrace but checking out how to do this.

**Comment by asl** [comment]
Please report Mojo issues to appropriate issue tracker.
