### ISSUE TITLE
[C++20] [Modules] Clang didn't generate the virtual table to the unit containing the key function 

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#70585]
Reproducer:

```
// layer1.cppm
export module foo:layer1;
struct Fruit {
    virtual ~Fruit() = default;
    virtual void eval() = 0;
};
struct Banana : public Fruit {
    Banana() {}
    void eval() override;
};

// layer2.cppm
export module foo:layer2;
import :layer1;
export void layer2_fun() {
    Banana *b = new Banana();
    b->eval();
}
void Banana::eval() {
}
```

Compiler layer2.cppm with:

```
clang++ -std=c++20 layer1.cppm --precompile -o foo-layer1.pcm
clang++ -std=c++20 layer2.cppm -fprebuilt-module-path=. -S -emit-llvm -o -
```

Then we can't see anything about the definition of virtual table. This violates the [itanium ABI 5.2.3](https://itanium-cxx-abi.github.io/cxx-abi/abi.html#vague-vtable):

> The virtual table for a class is emitted in the same object containing the definition of its key function, i.e. the first non-pure virtual function that is not inline at the point of class definition.

**Comment by iains** [comment]
I seem to recall we fixed a key function issue not too long ago - is this problem present on earlier branches?

**Comment by ChuanqiXu9** [comment]
> I seem to recall we fixed a key function issue not too long ago - is this problem present on earlier branches?

No, I tested on trunk. 

The problem we fixed were about we generate the vtables in too many units to produce duplicated symbols.

But the problem is about we didn't generate the vtable in the targeted unit so that we met undefined symbol.

I am trying to look at it. Probably an oversight.

**Comment by ChuanqiXu9** [comment]
I took a simple look at the problem and the cause may be a mismatch.

Currently, (maybe there are other paths), when we're generating the constructor of the record decl, we will try to emit the vtable for the record decl if the record decl is a dynamic class. 

However, in this example, the constructor won't be generated when we compile `layer2.cppm`, then here is the problem.

One solution may be, checking if the current emitting function is a key function and if yes, try to generate the vtable.

**Comment by rnikander** [comment]
FYI, when I create a similar thing in the old style, with just `.cc` and `.o` files, I see things like this:

```console
% nm layer1_b.o | llvm-cxxfilt | grep vtable 
00000000000000a0 S vtable for Fruit
                 U vtable for Banana
                 U vtable for __cxxabiv1::__class_type_info
% nm layer2_b.o | llvm-cxxfilt | grep vtable
0000000000000d68 S vtable for Banana
                 U vtable for __cxxabiv1::__class_type_info
                 U vtable for __cxxabiv1::__si_class_type_info
```

It's seems it's emitting the vtables in one `.o` files and resolving undefined `U` vtable for Banana later during linking.

**Comment by davidstone** [comment]
Is the concept of a key function necessary with modules? Would anything bad happen if the virtual table were emitted in the object file for the module that defines the class?

**Comment by ChuanqiXu9** [comment]
> Is the concept of a key function necessary with modules? Would anything bad happen if the virtual table were emitted in the object file for the module that defines the class?

Otherwise we're violating the Itanium ABI, which seems not good.

**Comment by dwblaikie** [comment]
(I'd want to do/have done similar things with debug info for Clang Header Modules, `-fmodules-debuginfo` that homes DWARF type definitions to the modular object file - this makes even more sense in a C++ standard modules world where object files are required to be generated from modules)

**Comment by ChuanqiXu9** [comment]
I filed https://github.com/itanium-cxx-abi/cxx-abi/issues/170. Let's discuss the ABI related issue there.

**Comment by ChuanqiXu9** [comment]
Sent https://github.com/llvm/llvm-project/pull/75912

**Comment by ChuanqiXu9** [comment]
Reopen due we reverted  https://github.com/llvm/llvm-project/pull/75912

**Comment by ChuanqiXu9** [comment]
I add this to the document to provide a method to workaround: https://clang.llvm.org/docs/StandardCPlusPlusModules.html#missing-vtables-for-classes-attached-to-modules

Hope this helps.

**Comment by h-vetinari** [comment]
Since the xref easily gets lost in a closed PR, noting that #75912 apparently didn't take care of the windows ABI, so a future attempt should also take into account not regressing #97447

**Comment by ChuanqiXu9** [comment]
Yeah, the current blocking issue is that we're waiting the response from MSVC's devs.

**Comment by ChuanqiXu9** [comment]
I got the response from MSVC dev: it looks like MSVC will always generate the virtual table on need in the COMDAT section no matter if modules are involved or not.

**Comment by ChuanqiXu9** [comment]
Close since https://github.com/llvm/llvm-project/pull/102287 is landed.
