### ISSUE TITLE
clang is suboptimal for `~(b >> a) ^ (c >> a)` where b and c are specific constants

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#70582]
Example:
```cpp
int f(int a)
{
  return ~(2 >> a) ^ (5 >> a);
}

int g(int a)
{
  return ~(7 >> a);
}
```
https://godbolt.org/z/bh8YdMeYY

**Comment by dtcxzyw** [comment]
We have transformed `xor (ashr X, Z), (ashr Y, Z)` into `ashr (xor X, Y), Z`. I guess interpreting `lshr (nneg X), Z` as `ashr (nneg X), Z` will fix this.
Alive2: https://alive2.llvm.org/ce/z/SUwAKr

**Comment by pinskia** [comment]
Insteresting that in the GCC bug report about `~(CST >> X)` not being transformed into `(~CST) >> X` 
It was mentioned that LLVM does that transformation. I wonder why it is not being done here.

Reference: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96688

**Comment by pinskia** [comment]
Oh I see the issue lsr vs asr.
Anyways I found things GCC does not handle because it does not convert ashr to lshr.
And a testcase which LLVM does not handle either due to the ashr vs lshr that is similar to this one:
```
int f(int a, unsigned b, int c)
{
  b &= 0xffff;
  return (c >> a) ^ (b >> a);
}
```
