### ISSUE TITLE
 How can I verify if my LLVM JIT is a debug version?

### ISSUE THREAD

**Issue by Thrrreeee** [llvm/llvm-project#70588]
I'm currently trying to debug LLVM ORCJIT, but I'm facing issues with the debugging process. I suspect it might be related to the version of ORCJIT I have installed, such as whether it is a debug version.
So,  how can I verify if my LLVM JIT is a debug version?

**Comment by lhames** [comment]
Hi @Thrrreeee. The library distributor should indicate whether the library was built with debug info. One way to check would be to inspect the library for debug info sections (e.g. using the `llvm-dwarfdump` tool).
