### ISSUE TITLE
[HLSL] Consolidate Buffer and SRV handling in CGHLSLRuntime resource annotation

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#70685]
The logic for annotating resources is split in two, which makes it tricky to add handling for UAVs and samplers. We should consolidate the logic to work uniformly on a global/decl pair regardless of the type of resource.

Considerations:
Template handling
SRV / cbuffer considerations

AC:
The annotating resources are unified into a single codepath
Test coverage is updated to reflect all possible scenarios

**Comment by davidcook-msft** [comment]
Per @llvm-beanz this is foundational for resource handling / parsing and should be done correctly early in the process.

**Comment by bogner** [comment]
After https://github.com/llvm/llvm-project/pull/75674 some of the really awkward parts of the current design go away, so this may end up being less urgent / not necessary after all

**Comment by damyanp** [comment]
@bogner  says this isn't worth tracking any more.
