### ISSUE TITLE
[DirectX][HLSL] Remove `parseSourceType` from DXILResource

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#70686]
Currently, CGHLSLRuntime/HLSLResource insert a stringify'd type into metadata for the backend to interpret as a resource type and fill out fields such as ROV, Shape, and element type. These need to be handled in the frontend and instead pass the interpreted values to the backend in the metadata.

AC:
Metadata in LLVM internals doesn't need any parsing to translate into meaningful DXIL constructs
All resource attributes are handled natively within LLVM

**Comment by davidcook-msft** [comment]
@bogner can you please update this AC with a list of affected areas?
