### ISSUE TITLE
[LLVM 17][libc++] Cherry-pick the fix for std::expected UB related to the has-value flag

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#70708]
We should cherry-pick this PR (https://github.com/llvm/llvm-project/pull/68733) which fixed this issue (https://github.com/llvm/llvm-project/issues/68552). Doing this is not an ABI break (unlike the follow-up https://github.com/llvm/llvm-project/pull/69673 which is an ABI break, and we're still undecided about this one).

I think it makes sense to make the present fix regardless of what we end up doing for the tail-padding issue (the ABI breaking one).

**Comment by nikic** [comment]
/branch ldionne/llvm-project/review/cherry-pick-has-value-fix-LLVM-17
