### ISSUE TITLE
Attribute plugins are broken

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#70702]
The changes in https://github.com/llvm/llvm-project/commit/0faee97a924adec76d5c7cd680c289ced51e6b5a accidentally broke attribute plugins (for which we have no test coverage, so the author had no way to know that this breakage happened!).

The issue comes from the changes to ParsedAttr.cpp:
```
bool ParsedAttr::existsInTarget(const TargetInfo &Target) const {
  return getInfo().existsInTarget(Target) &&
         getInfo().spellingExistsInTarget(Target,
                                          getAttributeSpellingListIndex());
}
```
the call to `getAttributeSpellingListIndex()` is reaching an unreachable that is generated here: https://github.com/llvm/llvm-project/blob/89564f0b69ac935dc3b865e4d627f3a0610b4abd/clang/utils/TableGen/ClangAttrEmitter.cpp#L3637

**Comment by amykhuang** [comment]
I made a pr for this, but I haven't tested it because I don't know how to make a plugin. https://github.com/llvm/llvm-project/pull/70877

**Comment by wanders** [comment]
This should be closed, right?

PR is merged. And attribute plugins seems to work fine on trunk.
