### ISSUE TITLE
[mlir][spirv] Add missing folding for scalar/vector SPIR-V ops

### ISSUE THREAD

**Issue by inbelic** [llvm/llvm-project#70704]
It has been noted that we are missing the fold definitions for various basic scalar/vector SPIR-V ops. As a result, many of these operations are not folded away in the IR and it is required to use other tools to do so, eg: spirv-opt. We are motivated to do so as it would allow for the IR to be more readable, particularly when we have transformed/lowered from another dialect into SPIR-V and are generating new operations that have the potential to be folded away.

**Comment by inbelic** [comment]
I have begun work on this and will add a draft PR in the next couple days.

@kuhar I will ping you here to follow along and to request that you assign me to the issue as well, thanks.

**Comment by kuhar** [comment]
I think this has been completed, I'm not aware of any missing folds / canon rules
