### ISSUE TITLE
[libc++][CI] Give fast jobs a higher execution priority in BuildKite

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#70719]
According to https://buildkite.com/docs/pipelines/managing-priorities, it is possible to assign a priority to CI jobs. We should probably bump the priority of our fast 5-6 first jobs so they run before the rest of the pipeline -- that would reduce the turnaround time on patches.

Assigning to Eric since this came up during a meeting we had together.

**Comment by mordante** [comment]
Is this bug report still relevant now we mostly moved to GitHub?

**Comment by ldionne** [comment]
No, I don't think it's relevant. Thanks for the heads up.
