### ISSUE TITLE
[clang][StaticAnalyzer] no option to re-analyse functions which are already analysed in a different context

### ISSUE THREAD

**Issue by kalaskow** [llvm/llvm-project#70711]
Hello,

let's imagine we have a library with the following code:

```cpp
int foo(int index) {
    int tab[100];
    if (index < -1000 || index > 1000)
        return tab[index];
    return tab[index-200];
}

int foo2() {
    return foo(205);
}
```
We don't have an access to all callers of this library. Because of this we would like to make its code bullet proof. We run:
```
clang -cc1 -analyze library.cpp -analyzer-checker=alpha.security.ArrayBoundV2
```
Unfortunately, it won't warn about the obvious out of bound access because it first analyzed `root->foo2->foo` which correcly accessed `tab` array and it didn't pick up on `root->foo` path. 

I found out that it is controlled by `shouldSkipFunction` function defined in `clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp`:
```cpp
static bool shouldSkipFunction(const Decl *D,
                               const SetOfConstDecls &Visited,
                               const SetOfConstDecls &VisitedAsTopLevel) {
  if (VisitedAsTopLevel.count(D))
    return true;
...
  // Otherwise, if we visited the function before, do not reanalyze it.
  return Visited.count(D);
}
```

In order to enable analyzing `root->foo` path I changed it to:

```cpp
  return false;
}
```
and rerunning `clang -cc1 -analyze library.cpp -analyzer-checker=alpha.security.ArrayBoundV2` gives:
```
library.cpp:4:16: warning: Out of bound memory access (access exceeds upper limit of memory block) [alpha.security.ArrayBoundV2]
        return tab[index];
               ^~~~~~~~~~
librarycpp:4:16: warning: Out of bound memory access (accessed memory precedes memory block) [alpha.security.ArrayBoundV2]
        return tab[index];
```

My question is: do you think it is a good idea to add an option to clang frontend to control this behavior? If it is can it be added?

**Comment by Snape3058** [comment]
IMO, that is not a problem according to the checking strategy of CSA.
However, it is also a good suggestion to add such an option if it is really required by users.

If the code cannot be executed, we will not check and report problems in that to avoid possible false positives,
as in most cases, those codes are on infeasible paths.
Developers may also add the defense conditions to avoid unknown mysteries or just to satisfy the coding style rules.
And they do not want any complaints about the problems triggered by those "impossible" paths.
(Although in this case, it is an obvious bug)

Besides, the current exploration strategy also helps to improve analysis efficiency, as there can be more redundant checks if the function is analyzed again as an entry.
And this may also lead to redundant reports on one bug triggered from different entries.

> Unfortunately, it won't warn about the obvious out of bound access because it first analyzed root->foo2->foo which correcly accessed tab array and it didn't pick up on root->foo path.

If there is such a caller of `foo2` or `foo` in the code base, this problem can be reported during cross-TU analysis with some symbolic inputs.
Again, if all callers provide a concrete input that cannot satisfy the gate-defense checks, we will not report this obvious bug either for the same reason of avoiding false positives.

More opinions from other teammates?

**Comment by steakhal** [comment]
> My question is: do you think it is a good idea to add an option to clang frontend to control this behavior? If it is can it be added?

You can already configure this by setting `-analyzer-inlining-mode=all`, see it live [here](https://godbolt.org/z/oP7ofro7z).

The default behavior is on purpose, to make analysis slightly more efficient by not reanalyzing the same functions assuming that the context they were used already is representative (and can be reused).

Was the flag sufficient for your question @kalaskow?

**Comment by kalaskow** [comment]
@steakhal Thank you! It fulfils my requirements: csa analyzes both paths with this option. 
I am sorry for bothering you. I couldn't have found that option and even browsing clang source code didn't help.

**Comment by steakhal** [comment]
> @steakhal Thank you! It fulfils my requirements: csa analyzes both paths with this option.
> I am sorry for bothering you. I couldn't have found that option and even browsing clang source code didn't help.

No worries. Let us know if you have other questions!
