### ISSUE TITLE
[libc++][CI] Reshuffle the Buildkite steps

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#70720]
We could reshuffle the order of our BuildKite jobs to make sure we have the highest value ones first. We could also create more groups to compartmentalize the build more and avoid wasting resources when a job fails.

@EricWF created the amazing https://efcs.us/public/libcxx/cistats.html visualization (WIP!) which should allow doing this rebalancing.

**Comment by asl** [comment]
> to make sure we have the highest value ones first

Does this mean that newer jobs will also take a priority? Won't this potentially make older jobs run forever if the builders are not fast enough?

**Comment by metaflow** [comment]
oh that dashboard is neat @EricWF , how to do you store / fetch the data? I was thinking recently that it would be great to have a open SQL-like point to query builds and results but have not thought it through...

**Comment by ldionne** [comment]
> > to make sure we have the highest value ones first
> 
> Does this mean that newer jobs will also take a priority? Won't this potentially make older jobs run forever if the builders are not fast enough?

They are fast enough though. They catch up at lower traffic hours like night time or early morning. So in practice, I expect that this will allow more relevant results when doing fast iteration on reviews when they are "hot" and being actively updated by authors (which is when that matters), and then we can generally let them chill for one night or so and all the lower-signal CI checks will complete overnight. We'll then generally merge the next day.

This is already what happens but the difference is that lower value checks from other PRs that were started before will run before the high value checks in a PR you might have just created, causing you to be at the end of the queue.

**Comment by ldionne** [comment]
Closing -- our CI infrastructure is working quite well and I'm not certain what reorganization we were thinking about back then, but I don't think any of this is an absolute must.
