### ISSUE TITLE
Reducing switch range on powers of two

### ISSUE THREAD

**Issue by DKay7** [llvm/llvm-project#70756]
I recently found `FIXME`: https://github.com/llvm/llvm-project/blob/b0e00ca6a605b88e83129c8c6be4e177f93cbfea/llvm/lib/Transforms/Utils/SimplifyCFG.cpp#L6795-L6797

I decided to implement it. My Idea was, as described in FIXME, to check if switch contains only powers of two, and if so, to replace each key with `countl_zero(key)`. When I'm almost done, I ran into a problem that I also need to change the switch `condition`  to `countl_zero(condition)`. I tried to find some simple and fast algorithm to count leading zeros in runtime, but all algorithms are too slow or too complex. Should I try to implement something complicated at all, or is this optimization not worth it?

My current approach looks like that:
```c++
  SmallVector<int64_t,4> Values;
  for (const auto &Case : SI->cases())
    Values.push_back(Case.getCaseValue()->getValue().getSExtValue());
  
  if (!IsSwitchOfPowersOfTwo(Values))
    return false;


  Builder.SetInsertPoint(SI);
  auto *Ty = cast<IntegerType>(SI->getCondition()->getType());
  
  SI->replaceUsesOfWith(SI->getCondition(), /* TODO: count leading zeros of SI->getCondition() */);
  
  for (auto Case : SI->cases()) {
    auto OrigValue = Case.getCaseValue()->getValue();
    Case.setValue(
        cast<ConstantInt>(ConstantInt::get(Ty, OrigValue.countl_zero())));
  }

```

**Comment by dtcxzyw** [comment]
You should emit a call to `@llvm.ctlz.*` intrinsic.
See also https://llvm.org/docs/LangRef.html#llvm-ctlz-intrinsic.

BTW, I guess `TLI->isCtlzFast/isCheapToSpeculateCtlz` may help if you want to avoid introducing slow ctlz implementation on targets without native support for ctlz (e.g., RISC-V without zbb).

**Comment by DKay7** [comment]
I ran into another problem, which is that we need to convert the "condition" correctly in order to redirect all "non-powers of two" to the default case. I solved this with the following bitwise transformation:

```
a = condition & (condition - 1)
condition |= a >> count_trailing_zeros(a)
new_condition = count_trailing_zeros(condition)
```
The idea of transformations is to make the number of finite zeros equal to 0 if the "condition" is not a power of two, and otherwise not to change this number.
So, in the first two lines, the least significant bit is assigned the value 1 if the "condition" is not a power of two.

My question is: isn't it too slow for such optimization, even if we only perform it on systems with built-in support for @llvm.cttz?

**Comment by dtcxzyw** [comment]
> I ran into another problem, which is that we need to convert the `condition` correctly in order to redirect all non-powers of two to the default case. I solved this with the following bitwise transformation:
> 
> ```
> a = condition & (condition - 1)
> condition |= a >> count_trailing_zeros(a)
> new_condition = count_trailing_zeros(condition)
> ```
> 
> The idea of transformations is to make the number of trailing zeros equal to 0 if the "condition" is not a power of two (since zero case is forbidden in this optimization), and otherwise not to change this number. So, in the first two lines, the least significant bit is assigned the value 1 if the "condition" is not a power of two.
> 
> My question is: isn't it too slow for such optimization, even if we only perform it on systems with built-in support for @llvm.cttz? And if so, do you have any ideas how to do it faster?
> 
> **Upd:**
> 
> I have come up with another solution that seems to me faster:
> 
> ```
> a = condition & (condition - 1)
> condition |= (a == 0)
> new_condition = count_trailing_zeros(condition)
> ```
> 
> But the question remains open.

IMHO, I recommend using `ctpop(x) == 1` if the backend allows.  If you have concerns about the cost of handling default cases, you can start with handling switches that with unreachable default cases.
```
bool HasDefault =
      !isa<UnreachableInst>(SI->getDefaultDest()->getFirstNonPHIOrDbg());
  if (HasDefault)
    return false;

// Handle switches with power-of-2 case values
...
```

**Comment by DKay7** [comment]
I believe I need help with failed test: 
https://github.com/llvm/llvm-project/blob/801c78d5b474c2319aa8ead44db7ba8cacac4714/llvm/test/CodeGen/AArch64/switch-unreachable-default.ll#L77-L80

Proposed optimization doesn't check range for value not fall through the jump table. It's just reduce switch range and only for switches with unreachable default case. Should I add range-check anyway?
