### ISSUE TITLE
[LLVM][DebugInfo] Strengthen DI metadata verifiers

### ISSUE THREAD

**Issue by Dinistro** [llvm/llvm-project#70787]
I recently ran into a crash caused by invalid debug metadata. Instead of throwing a verifier issue, the following reduced example explodes in the ASMPrinter. After building clang in Debug mode, I realized that the `baseType` field of the `DICompositeType` is mandatory (at least when it's an array type). While the debug mode triggers an assertion instead of running into a SegFault, it is not directly clear what pass produced the faulty debug metadata.

**I suggest that we try to strengthen the verifiers to catch more invalid DI metadata**, considering that this can be produced by many different frontends. In my case, there is a bug in MLIR, that only manifests this late in the pipeline.

Example (invalid due to lacking a `baseType` field on the `DICompositeType`): 
```
define i32 @func(ptr %0) #0 !dbg !3 {
  call void @llvm.dbg.value(metadata ptr %0, metadata !6, metadata !DIExpression()), !dbg !22
  ret i32 0
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare void @llvm.dbg.value(metadata, metadata, metadata) #1

attributes #0 = { "function-instrument"="xray-always" }
attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C11, file: !2, producer: "clang", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
!2 = !DIFile(filename: "file.c", directory: "/")
!3 = distinct !DISubprogram(name: "func", scope: !2, file: !2, line: 46, type: !4, scopeLine: 48, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !1)
!4 = distinct !DISubroutineType(types: !5)
!5 = !{}
!6 = !DILocalVariable(name: "op", arg: 5, scope: !3, file: !2, line: 47, type: !19)
!19 = !DICompositeType(tag: DW_TAG_array_type, size: 2624, elements: !20)
!20 = !{!21}
!21 = !DISubrange(count: 41)
!22 = !DILocation(line: 0, scope: !3)
```

**Comment by jmorse** [comment]
Many thanks for the report and the reduced reproducer; I think that makes perfect sense, #70803 adds such a filter and adds the reproducer as a test for it. Much appreciated!
