### ISSUE TITLE
A request to Apple to open-source the Metal Shading Language compiler and add it to this LLVM repository

### ISSUE THREAD

**Issue by ContingencyOfTautologicalContradictions** [llvm/llvm-project#70851]
With the addition of new GPU features to the M3 chipset, more developers will lead themselves into the decision of developing products for the Apple platforms.

Hence, i think it's the right time to open-source the Metal frontend compiler toolchain, so that these near-future developers are conscious of what is going on exactly at their compiler, and even contribute hand-to-hand with Apple at making the frontend better for the users of Metal.

**Comment by Arhoc** [comment]
Hi @ContingencyOfTautologicalContradictions,

I agree that open-sourcing the Metal frontend compiler toolchain would be a great way to encourage more developers to develop products for Apple platforms. It would also give developers more visibility into how the compiler works and allow them to contribute to its improvement.

I understand that there are some concerns about open-sourcing the compiler, such as the potential for security vulnerabilities and the loss of control over the compiler's development. However, I believe that the benefits of open-sourcing the compiler outweigh the risks.

With love, Barack Hussein Obama II.

**Comment by asl** [comment]
Please submit Apple-related things to Apple. This request is unrelated to LLVM.

**Comment by ContingencyOfTautologicalContradictions** [comment]
> Please submit Apple-related things to Apple. This request is unrelated to LLVM.

How so? This directly influences the LLVM repository and its sub-projects

**Comment by ContingencyOfTautologicalContradictions** [comment]
Also Apple is the original founder of the LLVM project, and one of the main contributors. This is the right place
