### ISSUE TITLE
[libc++] Use a __bounded_iter flavor in std::array

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#70864]
Just like we do for `std::string_view` and `std::span`. But we can hardcode the size information in the iterator type, leading to 2 pointers instead of needing 3 pointers like `__bounded_iter`.

**Comment by philnik777** [comment]
We could also make it a single pointer and a counter. That would allow us to have a smaller fancy pointer or even bit-pack the count into the lower bits for small N.

**Comment by ldionne** [comment]
For information this will be blocked on https://github.com/llvm/llvm-project/pull/74482.
