### ISSUE TITLE
[x86_64] llc -O1 mishandles zeroext/signext argument attribute

### ISSUE THREAD

**Issue by oakrc** [llvm/llvm-project#70860]
[Demo (zeroext) on Compiler Explorer](https://godbolt.org/z/PWf5nnv63)
[Demo (signext) on Compiler Explorer](https://godbolt.org/z/MjheTsv8b)

The following C code compiles (clang -O0) to the (reduced) IR below.
```c
#include <stdint.h>
int32_t  func(uint8_t  p_3) { 
    return p_3;
}
```
Reduced IR:
```llvm
define i32 @func(i8 zeroext %0) {
  %2 = alloca i8, align 1
  store i8 %0, ptr %2, align 1
  %3 = load i8, ptr %2, align 1
  %4 = zext i8 %3 to i32
  ret i32 %4
}
```
llc -O0 properly handles zeroext (and the zext instruction):
```asm
func:                                   # @func
        mov     al, dil
        mov     byte ptr [rsp - 1], al
        movzx   eax, byte ptr [rsp - 1]
        ret
```
Yet llc -O1 seems to only do the zero-extension half-way:
```asm
func:                                   # @func
        mov     eax, edi
        mov     byte ptr [rsp - 1], al
        ret
```
Interestingly, this issue goes away if the `zeroext` attribute is removed.

The same issue appears for signext as well.

**Comment by oakrc** [comment]
I'm not familiar with AArch64 but it seems like this issue applies to AArch64 as well? [Compiler Explorer](https://godbolt.org/z/E66e3GYMq).

**Comment by oakrc** [comment]
CC @DataCorrupted

**Comment by phoebewang** [comment]
This is not an issue. The [zeroext](https://llvm.org/docs/LangRef.html#parameter-attributes) attribute is used by target’s ABI, which indicates whether the value in the register has been zero extended by caller or callee respectively.

In this case, `zeroext` indicates the upper bits in already zero, so we don't need to zero it again.
