### ISSUE TITLE
awkward diagnostics on undeclared identifier in argument list

### ISSUE THREAD

**Issue by sunfishcode** [llvm/llvm-project#7086]
|  |  |
| --- | --- |
| Bugzilla Link | [6714](https://llvm.org/bz6714) |
| Version | trunk |
| OS | All |
| CC | @zygoloid |

## Extended Description 
Testcase (one line):

void foo(SmallVectorImpl<int> &) {}

Clang++ output:

b.cc:1:6: error: variable has incomplete type 'void'
void foo(SmallVectorImpl<int> &) {}
     ^
b.cc:1:10: error: use of undeclared identifier 'SmallVectorImpl'
void foo(SmallVectorImpl<int> &) {}
         ^
b.cc:1:33: error: invalid token after top level declarator
void foo(SmallVectorImpl<int> &) {}
                                ^
                                ;

The second error is legit; the first and third are puzzling.

**Comment by Quuxplusone** [comment]
Since Clang 3.2, the story has been much better:
```
<source>:1:10: error: unknown type name 'SmallVectorImpl'
void foo(SmallVectorImpl &) {}
         ^
```
