### ISSUE TITLE
Static analyzer throws constraints in the subsequent ExplodedNode on a branch. Is it a bug?

### ISSUE THREAD

**Issue by jackniu1234** [llvm/llvm-project#70892]
I' m now trying to understand the ExplodedGraph of clang static analyzer using debug.ViewExplodedGraph checker and I hope to select some ExplodedNode to achieve the effect of function summary. However, I found CSA sometimes throws constraints in the subsequent ExplodedNode on a branch, which makes it impossible to just use one ExplodedNode without considering the previous nodes.

Here are two simple examples with similar code. The example 1 throwed constraints while example 2 didn't.

Code of example 1:
```c
#include <stdio.h>

int main() {
    int a;
    scanf("%d", &a);

    if (a > 10) {
        a = a + 1;
    }
    else {
        a = a + 2;
    }
    return a;
}
```
The ExplodedGraph like this:
![](https://github.com/jackniu1234/ExplodedGraph-Issue/blob/main/right.png)

Here are two simple examples with similar code. The example 1 throwed constraints while example 2 didn't.

Code of example 1:
```c
int rand();
int main() {
    int a = 2;

    if (rand() > 10) {
        a = a + 1;
    }
    else {
        a = a+ 2;
    }
    return 0;
}
```

The ExplodedGraph like this:
![](https://github.com/jackniu1234/ExplodedGraph-Issue/blob/main/wrong.png)

I'm wondering if it is a bug. If not, why?

**Comment by jackniu1234** [comment]
It seems that the photos don't display. Here are two links:
https://github.com/jackniu1234/ExplodedGraph-Issue/blob/main/right.png
https://github.com/jackniu1234/ExplodedGraph-Issue/blob/main/wrong.png

**Comment by Snape3058** [comment]
@jackniu1234 two example 1s with one right and one wrong links.
Can you reestablish the relation between example codes and exploded graphs?

If I got it correctly, the `scanf` one is the right one; whereas the `rand` one is the wrong one.
I dumped the program state with the two examples before returning, where the `scanf` one preserves the constraints and the `rand` one does not.

If so, it is simple to explain. It is a feature.

CSA will purge the symbols that will not be used in the future, together with the constraints on the symbol, and notify checkers to determine whether to remove the information recorded for the symbol or extend the lifetime of the symbol for future uses with the checker.

The return value of `rand` is only used in the `if` stmt for the branching, which will not be used later.
Hence, after it is used, the symbol and information related to it are removed.

To prevent CSA engine from removing the symbols and constraints, you can add the analyzer option `-analyzer-purge=none`.
However, doing this will increase the memory consumption.

If this answers your question, please close this issue.
