### ISSUE TITLE
clang cannot simplify `(a gt/lt b) != (a le/ge b)` where b is a specific constant

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#70928]
Example:
https://godbolt.org/z/7PMr8vc98
```cpp
bool foo(int a)
{
   return (a > 5) != (a <= 5);
}

bool bar(int a)
{
   return (a < 5) != (a >= 5);
}
```

When checking this simplification with alive2, is it okay to try to represent an integer that is 1 greater than or 1 less than a certain integer using `add` or `sub` as follows?
https://alive2.llvm.org/ce/z/iddeDw

**Comment by dtcxzyw** [comment]
I guess https://github.com/llvm/llvm-project/pull/69840 may help. I will take a look later.
