### ISSUE TITLE
Example of an optimization failure for a function that implies `abs`

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#70939]
Consider the following two functions.
https://godbolt.org/z/sn7qahaa9
```c
#define MAX(a, b) ((a) > (b) ? (a) : (b)) 

int foo(int a)
{
    if(a < 0)
      a = MAX (-a, 0);
    else
      a = MAX (a, 0);
    return a;
}

int bar(int a)
{
    return MAX((a < 0 ? -a : a), 0);
}
```

Here, `foo` should be the same as `bar`.

Alive2:
https://alive2.llvm.org/ce/z/a_4kdi

FYI (original GCC bugzilla issue)
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=112324

**Comment by artem** [comment]
This seems to be fixed in the current main branch

**Comment by k-arrows** [comment]
> This seems to be fixed in the current main branch

Confirmed. I will close this issue. Thanks for the notice!
