### ISSUE TITLE
LSR takes over 1 second on 583 line testcase

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#7099]
|  |  |
| --- | --- |
| Bugzilla Link | [6727](https://llvm.org/bz6727) |
| Version | 1.0 |
| OS | All |
| CC | @sunfishcode |

## Extended Description 
test/CodeGen/PowerPC/tango.net.ftp.FtpClient.ll is taking forever to run, and is all time in lsr.

This looks like Bug 4534 has either come back or is not fixed.  I'm disabling the test until the compile time is improved.

**Comment by arsenm** [comment]
Mentioned testcase doesn't exist now but compiles quickly

[resurrected-test.ll.txt](https://github.com/llvm/llvm-project/files/12296568/resurrected-test.ll.txt)
