### ISSUE TITLE
[Flang][test-suite] gfortran-regression-compile-regression__contiguous tests failing

### ISSUE THREAD

**Issue by ceseo** [llvm/llvm-project#71007]
The following tests are failing after [this commit](https://github.com/llvm/llvm-project/commit/91917387648f5638058f7f9391f144b8858c4975):

[flang] Accept CONTIGUOUS attribute when redundant (https://github.com/llvm/llvm-project/pull/70853)

```
FAIL: test-suite::gfortran-regression-compile-regression__contiguous_6_f90.test
FAIL: test-suite::gfortran-regression-compile-regression__contiguous_9_f90.test
FAIL: test-suite::gfortran-regression-compile-regression__pr95503_f90.test
```

See buildbots for logs (i.e. https://lab.llvm.org/buildbot/#/builders/179/builds/8288)

**Comment by klausler** [comment]
Will adjust the test suite.

**Comment by klausler** [comment]
Tests fixed!
