### ISSUE TITLE
Nvim-dap lldb-vscode terminate called without an active exception

### ISSUE THREAD

**Issue by jasuramme** [llvm/llvm-project#71017]
Expected:
Dap debug to work
Observed:
lldb-vscode exits and in log I see:
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
[dap.log](https://github.com/llvm/llvm-project/files/13234391/dap.log)

Reproduce steps:

1. Running nvim-dap with the following config:

local dap = require('dap')
dap.adapters.lldb = {
  type = 'executable',
  command = '/usr/bin/lldb-vscode', -- adjust as needed, must be absolute path
  name = 'lldb'
}

local dap = require('dap')
dap.configurations.cpp = {
  {
    name = 'Launch',
    type = 'lldb',
    request = 'launch',
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
    cwd = vim.fn.getcwd(),
    stopOnEntry = true,
    args = {},
 },
}

2. g++ ./main.cpp -g
3. nvim
4. :e main.cpp
5. :lua require'dap'.continue()
Path to executable: /mnt/sda5/workspace/nvim-training/bug/a.out
6. :lua require'dap'.continue()

Project and configs are in the attachment below
[files.zip](https://github.com/llvm/llvm-project/files/13234400/files.zip)

System info:
Nvim version: 
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1697887905

Nvim-dap version: (commit) 79dbc70

lldb version: 16.0.6 installed via pacman (archlinux pkg version: 16.0.6-1)

Operating system: Arch Linux  Linux kernel 6.5.9-arch2-1              
Shell: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
CPU: Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz, 1 sockets, 2 cores, 4 threads
GPU: Intel Corporation HD Graphics 620 (rev 07), 256M RAM

**Comment by EugeneZelenko** [comment]
Could you please try 17 or `main` branch?

**Comment by jasuramme** [comment]
Thanks Eugene, 
I actually tried to build it with archlinux makepkg without success. Please give me some time. If any problems, I will probably run it in the Ubuntu container

**Comment by jasuramme** [comment]
@EugeneZelenko 

Sorry if that's a dumb question. I'm having build errors in lldb even with main branch. Can you please suggest what to do?

[  0%] Building CXX object tools/argdumper/CMakeFiles/lldb-argdumper.dir/argdumper.cpp.o
[  0%] Linking CXX executable ../../bin/lldb-argdumper
[  0%] Built target lldb-argdumper
[  0%] Building LLDB Python wrapper
/home/jasuramme/sandbox/llvm/llvm-project/lldb/include/lldb/API/SBCommandReturnObject.h:119: Warning 509: Overloaded method lldb::SBCommandReturnObject::PutCString(char const *) effectively ignored,
/home/jasuramme/sandbox/llvm/llvm-project/lldb/include/lldb/API/SBCommandReturnObject.h:119: Warning 509: as it is shadowed by lldb::SBCommandReturnObject::PutCString(char const *,int).
[  0%] Built target swig_wrapper_python
[  0%] Generating ../../bin/lldb-python
[  0%] Built target lldb-python-wrapper
[  0%] Building LLDB Lua wrapper
/home/jasuramme/sandbox/llvm/llvm-project/lldb/include/lldb/API/SBCommandReturnObject.h:119: Warning 509: Overloaded method lldb::SBCommandReturnObject::PutCString(char const *) effectively ignored,
/home/jasuramme/sandbox/llvm/llvm-project/lldb/include/lldb/API/SBCommandReturnObject.h:119: Warning 509: as it is shadowed by lldb::SBCommandReturnObject::PutCString(char const *,int).
[  0%] Built target swig_wrapper_lua
[  0%] Generating VCSVersion.inc
[  0%] Building CXX object source/Version/CMakeFiles/lldbVersion.dir/Version.cpp.o
[  0%] Linking CXX static library ../../lib/liblldbVersion.a
[  0%] Built target lldbVersion
[  0%] Built target intrinsics_gen
[  0%] Built target clang-tablegen-targets
[  0%] Building CXX object utils/TableGen/CMakeFiles/obj.lldb-tblgen.dir/LLDBOptionDefEmitter.cpp.o
/home/jasuramme/sandbox/llvm/llvm-project/lldb/utils/TableGen/LLDBOptionDefEmitter.cpp: In function ‘void lldb_private::EmitOptionDefs(llvm::RecordKeeper&, llvm::raw_ostream&)’:
/home/jasuramme/sandbox/llvm/llvm-project/lldb/utils/TableGen/LLDBOptionDefEmitter.cpp:174:23: error: too many arguments to function ‘void llvm::emitSourceFileHeader(StringRef, raw_ostream&)’
  174 |   emitSourceFileHeader("Options for LLDB command line commands.", OS, Records);
      |   ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/jasuramme/sandbox/llvm/llvm-project/lldb/utils/TableGen/LLDBOptionDefEmitter.cpp:19:
/usr/include/llvm/TableGen/TableGenBackend.h:23:6: note: declared here
   23 | void emitSourceFileHeader(StringRef Desc, raw_ostream &OS);
      |      ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [utils/TableGen/CMakeFiles/obj.lldb-tblgen.dir/build.make:76: utils/TableGen/CMakeFiles/obj.lldb-tblgen.dir/LLDBOptionDefEmitter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5893: utils/TableGen/CMakeFiles/obj.lldb-tblgen.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by bulbazord** [comment]
@jasuramme There is documentation on how to build LLDB. Did you take a look at that? https://lldb.llvm.org/resources/build.html

**Comment by jasuramme** [comment]
Thanks @bulbazord. I've finally built it.
It is workin with main branch...
