### ISSUE TITLE
How to solve the error "Unknown argument: '-fno-lifetime-dse'"

### ISSUE THREAD

**Issue by Thrrreeee** [llvm/llvm-project#71156]
Unknown argument: '-fno-lifetime-dse'
![image](https://github.com/llvm/llvm-project/assets/72311224/60377d75-545d-4ded-aa29-d56f209b23fd)

**Comment by tbaederr** [comment]
That's a GCC flag, just don't pass it to clang/or use a gcc that supports the flag?

**Comment by fhahn** [comment]
I'm closing this for now, as this is just a flag not supported by Clang.
