### ISSUE TITLE
Unity WebGL Build Failed

### ISSUE THREAD

**Issue by KERPENTER** [llvm/llvm-project#71167]
I try to compile a WebGL project with the Unity 2022.3.12f1 and get these 3 error messages attached in here.
[error3.txt](https://github.com/llvm/llvm-project/files/13248961/error3.txt)
[error1.txt](https://github.com/llvm/llvm-project/files/13248962/error1.txt)
[error2.txt](https://github.com/llvm/llvm-project/files/13248963/error2.txt)

What I am suppose to do ?

**Comment by fhahn** [comment]
It looks like you are using a Clang shipped by Unity? Can you reproduce the error with open source clang (e.g. via https://clang.godbolt.org)? If not, there is not much we can do here and it would be best to raise the issue with Unity.

**Comment by fhahn** [comment]
I'm closing this for now, please let us know if this reproduces with open source LLVM and we can re-open the issue once it is actionable.
