### ISSUE TITLE
Non-main changes are sent to llvm-commits

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#71185]
It looks like changes to spr-managed branches currently send emails to llvm-commits, which they probably shouldn't. An example is https://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20231030/1235264.html.

@joker-eph fyi

**Comment by joker-eph** [comment]
I noticed when the email was sent and forwarded to @tstellar  and Anton, I don't know where is the code that handle the mailing-list?

**Comment by nikic** [comment]
The code is in https://github.com/llvm/llvm-admin/blob/main/AWS/Lambda/PREmailer/pr_emailer.py.

**Comment by joker-eph** [comment]
Thanks! That seems like the right repo, but I suspect the code the commit mailing list is https://github.com/llvm/llvm-admin/blob/main/AWS/Lambda/CommitEmailer/commit_emailer.py#L131C19-L131C19 instead?

**Comment by joker-eph** [comment]
There is a branch detection here: https://github.com/llvm/llvm-admin/blob/main/AWS/Lambda/CommitEmailer/commit_emailer.py#L178-L179

But it is confusing to me because 1) it should match anything that isn't "master" and so all the commits to "main" should be filtered and 2) it should have fired on my PR...

**Comment by tstellar** [comment]
I discovered that the code in the repo does not match what is deployed, so I've update the repo now.  I'm still not sure why it is failing though.  I need a more recent commit to look at, because the webhook log only goes back so far.

**Comment by nikic** [comment]
It looks like this problem still exists, I keep getting "[𝘀𝗽𝗿] changes introduced through rebase" mails from @jroelofs.

**Comment by jroelofs** [comment]
oh, hey, @AaronBallman was just asking me about those...

**Comment by jroelofs** [comment]
@tstellar here's one: https://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20231127/522266.html

**Comment by jroelofs** [comment]
I'm not sure how to test that ^
