### ISSUE TITLE
[clang][AST] `NULL` node for function template body with `-target x86_64-pc-win32` pre c++20

### ISSUE THREAD

**Issue by 5chmidti** [llvm/llvm-project#71203]
This bug was found during #70559.

Repro case:
```c++
template <typename T>
void f() {}
```
Clang creates valid ASTs for this snippet with:
- `-target x86_64-pc-win32 -std=c++20`
- `-std=c++17` (linux)
- `-std=c++20` (linux)

But not with:
- `-target x86_64-pc-win32 -std=c++17`
- `-target x86_64-pc-win32 -std=c++14`
- `-target x86_64-pc-win32 -std=c++11`

https://godbolt.org/z/9v98vnbsx

```
TranslationUnitDecl
`-FunctionTemplateDecl <line:1:1, line:2:11> col:6 f
  |-TemplateTypeParmDecl <line:1:11, col:20> col:20 typename depth 0 index 0 T
  `-FunctionDecl <line:2:1, col:11> col:6 f 'void ()'
    `-CompoundStmt <col:10, col:11>
```
vs
```
TranslationUnitDecl
`-FunctionTemplateDecl <line:1:1, line:2:8> col:6 f
  |-TemplateTypeParmDecl <line:1:11, col:20> col:20 typename depth 0 index 0 T
  `-FunctionDecl <line:2:1, col:8> col:6 f 'void ()'
    `-<<<NULL>>>
```

**Comment by koplas** [comment]
Relevant info:
- [How do you access the body of a template function in the AST?](https://discourse.llvm.org/t/how-do-you-access-the-body-of-a-template-function-in-the-ast/61829)
- #69431

**Comment by 5chmidti** [comment]
Thanks. I'm going to close this issue. As far as I can tell, this is expected behavior: the change for C++20 was due to MSVC changing the default for C++20, and the pre C++20 behavior is to use the delayed template parsing. Clang simply mirrors this behavior, from what I can tell. I'll figure something out for my CI failure.
