### ISSUE TITLE
clang is suboptimal for `(a % b) lt/ge (b-1)` where b is a power of 2

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#71280]
Example-1 (b=512, "less than")
https://godbolt.org/z/Tdc6onb6e
https://alive2.llvm.org/ce/z/wvSEvC
```cpp
int foo(int a)
{
   return (a % 512) < 511;
}

int bar(int a)
{
   return (a & -2147483137) != 511;
}
```

Example-2 (b=8, "greater than or equal to")
https://godbolt.org/z/cxdveoT1n
https://alive2.llvm.org/ce/z/sm3xs5
```cpp
int baz(int a)
{
   return (a % 8) >= 7;
}

int qux(int a)
{
   return (a & -2147483641) == 7;
}
```

**Comment by elhewaty** [comment]
I will  work on this.

**Comment by elhewaty** [comment]
I think it needs to be fixed for all types: https://godbolt.org/z/z8r76q451

**Comment by RKSimon** [comment]
> @RKSimon for the X86_64 generated code here: https://godbolt.org/z/sTrsj1aW4, is it better to use `-2147483641` instead of `-121`?

-121 is better as it can be represented with a 8-bit (sign extended) constant encoding: https://godbolt.org/z/esG3r7773
