### ISSUE TITLE
Missed optimization: add+add instead of lea

### ISSUE THREAD

**Issue by dvyukov** [llvm/llvm-project#71306]
The code is:
```
void* alloc(long* base, long cl) {
	long header = base[cl];
	const long ptr_mask = ((1l << 56) - 1);
	if ((header & ptr_mask) == 0)
		return slowmalloc();
	void* ptr = (void*)(header & ptr_mask);
	void* next = *(void**)ptr;
	base[cl] = (long)next | (header & ~ptr_mask) + (1l << 56);
	return ptr;
}
```

clang 17.0.1 produces the following x86 code:
```
 movabs $0xffffffffffffff,%rcx
 ...
 add    %rdx,%rcx
 inc    %rcx
```

The add+inc sequence could be `lea 1(%rdx, %rcx), %rcx`, which is 1 instruction and 1 byte less.

https://godbolt.org/z/Yxehv3xWf

**Comment by dvyukov** [comment]
cc @david-xl

**Comment by topperc** [comment]
On some Intel CPUs a 3 source LEA is only available on 1 execution port and takes 3 cycles. The 2 instruction sequence could be faster on those CPUs.

**Comment by dvyukov** [comment]
Interesting. Is it the case for widespread recent CPUs? Is it subject to -mtune tuning?
Grepping a  random binary for such patterns, I see that clang emits such instructions a lot:
https://gist.github.com/dvyukov/663b85470279fcf69f89a52265b7f6e1

**Comment by topperc** [comment]
> Interesting. Is it the case for widespread recent CPUs? Is it subject to -mtune tuning? Grepping a random binary for such patterns, I see that clang emits such instructions a lot: https://gist.github.com/dvyukov/663b85470279fcf69f89a52265b7f6e1

I believe the 3 cycle 3 source LEA was on Intel CPUs starting with SandyBridge. It was improved in Ice Lake.

It is subject -mtune. I think this is the backend tuning flag for it.

```
def TuningSlow3OpsLEA : SubtargetFeature<"slow-3ops-lea", "Slow3OpsLEA", "true", 
                                   "LEA instruction with 3 ops or certain registers is slow">;
```

**Comment by RKSimon** [comment]
We should probably consider allowing fast lea on later x86-64-v* variants: https://godbolt.org/z/d4nWPEjP8

**Comment by dvyukov** [comment]
> def TuningSlow3OpsLEA : SubtargetFeature<"slow-3ops-lea", "Slow3OpsLEA", "true", 
>                                    "LEA instruction with 3 ops or certain registers is slow">;

If I am reading the code correctly, it only applies to LEA with RBP/R13 as base register:
https://github.com/llvm/llvm-project/blob/19bfe08c7f5ffcac97a050ce3edaf91bc9ff68bd/llvm/lib/Target/X86/X86FixupLEAs.cpp#L328-L341

**Comment by topperc** [comment]
> > def TuningSlow3OpsLEA : SubtargetFeature<"slow-3ops-lea", "Slow3OpsLEA", "true",
> > "LEA instruction with 3 ops or certain registers is slow">;
> 
> If I am reading the code correctly, it only applies to LEA with RBP/R13 as base register:
> 
> https://github.com/llvm/llvm-project/blob/19bfe08c7f5ffcac97a050ce3edaf91bc9ff68bd/llvm/lib/Target/X86/X86FixupLEAs.cpp#L328-L341

I think that code is because RBP/R13 as base is inefficient if the index register is used even when displacement isn't needed. This is due to an encoding restriction that requires a explicit 0 displacement byte to be used when the base is RBP. So the hardware considers it a 3 source LEA even though the displacement is 0.

**Comment by topperc** [comment]
Relevant text from Intel Optimization Manual section 3.5.1.2 here https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html#inpage-nav-5


 For LEA instructions with three source operands and some specific situations, instruction latency has increased to 3 cycles, and must dispatch via port 1:
— LEA that has all three source operands: base, index, and offset.
— LEA that uses base and index registers where the base is EBP, RBP, or R13.
— LEA that uses RIP relative addressing mode.
— LEA that uses 16-bit addressing mode.

**Comment by david-xl** [comment]
A late comment (I somehow missed the notification).

Agner's instruction table also confirms the 3 cycle latency of 3 component LEA on *lakes prior to icelake. It was regression introduced in Sandybridge.  

On Zen3 and Zen3, the latency of 3 address LEA is 2 cycles.
