### ISSUE TITLE
Poor diagnostic with missing type name in constructor parameter

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7131]
|  |  |
| --- | --- |
| Bugzilla Link | [6759](https://llvm.org/bz6759) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
The following example will compile in g++ but not in clang++:
```c++
#include <stdio.h>

/* If you uncomment the forward declaration, then this compiles OK
   (but g++ does not require the forward declaration):
*/
// class FooImpl;

class Foo_connection {
    private:
        friend class FooImpl;
        Foo_connection(FooImpl&);
};


int main() {
  int i = 1;
  printf("%d \n",++i);
}
```
-----
clang++     testcase.cc   -o testcase
```c++
testcase.cc:9:31: error: expected ')'
        Foo_connection(FooImpl&);
                              ^
```

**Comment by philnik777** [comment]
Looks like this got fixed in clang 3.1: https://godbolt.org/z/3dan7aqoP
