### ISSUE TITLE
Possible bug in `convert-vector-to-scf`

### ISSUE THREAD

**Issue by srcarroll** [llvm/llvm-project#71326]
There appears to be a bug in the `convert-vector-to-scf` where converting certain `vector.transfer_read` ops causes an invalid `memref.load` op to be created.  Maybe the input IR that causes this is incompatible with the pass, but I think a proper error check should be done rather than let the implementation create an invalid op.

Example IR:

```
#map1 = affine_map<(d0, d1, d2, d3) -> (d0, 0, 0, d3)>
#map2 = affine_map<(d0, d1, d2, d3, d4) -> (d0, 0, 0, d3)>
func.func @main(%subview:  memref<1x1x1x?xi32, strided<[17, 17, 17, 1], offset: ?>>, %c0 : index, %c0_i32 : i32, %2: vector<1x32xi1>) -> vector<1x1x1x32xi32> {
    %3 = vector.transfer_read %subview[%c0, %c0, %c0, %c0], %c0_i32, %2 {in_bounds = [true, true, true, true], permutation_map = #map1} : memref<1x1x1x?xi32, strided<[17, 17, 17, 1], offset: ?>>, vector<1x1x1x32xi32>
    return %3 : vector<1x1x1x32xi32>
}
```

Applying `mlir-opt --convert-vector-to-scf` to this IR yields the following error
```
transfer-read.mlir:4:10: error: 'memref.load' op incorrect number of indices for load
    %3 = vector.transfer_read %subview[%c0, %c0, %c0, %c0], %c0_i32, %2 {in_bounds = [true, true, true, true], permutation_map = #map1} : memref<1x1x1x?xi32, strided<[17, 17, 17, 1], offset: ?>>, vector<1x1x1x32xi32>
         ^
transfer-read.mlir:4:10: note: see current operation: %8 = "memref.load"(%4, %0, %0) <{nontemporal = false}> : (memref<1xvector<32xi1>>, index, index) -> vector<32xi1>
```

Note that the IR gets successfully transformed with the `full-unroll` option turned on.  Applying `mlir-opt ---convert-vector-to-scf=full-unroll` yields

```
  func.func @main(%arg0: memref<1x1x1x?xi32, strided<[17, 17, 17, 1], offset: ?>>, %arg1: index, %arg2: i32, %arg3: vector<1x32xi1>) -> vector<1x1x1x32xi32> {
    %0 = vector.splat %arg2 : vector<1x1x1x32xi32>
    %1 = vector.extract %arg3[0] : vector<1x32xi1>
    %2 = vector.transfer_read %arg0[%arg1, %arg1, %arg1, %arg1], %arg2, %1 {in_bounds = [true]} : memref<1x1x1x?xi32, strided<[17, 17, 17, 1], offset: ?>>, vector<32xi32>
    %3 = vector.insert %2, %0 [0, 0, 0] : vector<32xi32> into vector<1x1x1x32xi32>
    return %3 : vector<1x1x1x32xi32>
  }
  ```
  
  This makes me believe that it should also work without the option, since in this case all the leading dims are size `1` and thus any loops that get generated would be trivial single iteration loops that would canonicalize away.  Which, as far as I can tell, would  be exactly what the unrolled version would generate.

**Comment by rikhuijzer** [comment]
> but I think a proper error check should be done rather than let the implementation create an invalid op.

Yes you're right. `mlir-opt` should either throw a verifier error or succeed, but not crash in the middle of a pass. It might be fixed by #75519.

**Comment by srcarroll** [comment]
Thanks for the fix!

**Comment by EugeneZelenko** [comment]
Not merged yet.

**Comment by rikhuijzer** [comment]
Yes. https://github.com/llvm/llvm-project/pull/75519 had to be reverted because an integration test failed. After simplifying that test a bit, this failed after merging https://github.com/llvm/llvm-project/pull/75519:
```mlir
func.func @add_arrays_of_scalable_vectors(%a: memref<1x2x?xf32>, %b: memref<1x2x?xf32>) -> vector<1x2x[4]xf32> {
  %c0 = arith.constant 0 : index
  %c2 = arith.constant 2 : index
  %c3 = arith.constant 2 : index
  %cst = arith.constant 0.000000e+00 : f32
  %dim_a = memref.dim %a, %c2 : memref<1x2x?xf32>
  %mask_a = vector.create_mask %c2, %c3, %dim_a : vector<1x2x[4]xi1>
  %vector_a = vector.transfer_read %a[%c0, %c0, %c0], %cst, %mask_a {in_bounds = [true, true, true]} : memref<1x2x?xf32>, vector<1x2x[4]xf32>
  return %vector_a : vector<1x2x[4]xf32>
}
```

I'm working on it, but haven't figured it out yet.
