### ISSUE TITLE
[C++20][Modules] Cannot export a declaration within a linkage-specification

### ISSUE THREAD

**Issue by cpplearner** [llvm/llvm-project#71347]
Clang rejects the following module unit:

```c++
export module mod;

extern "C++" {
    export void f();
}
```

(https://godbolt.org/z/dPYhGW7ah)

The error message is:

```
<source>:4:5: error: export declaration can only be used within a module purview
    4 |     export void f();
      |     ^
```

I think the declaration of `f` should be considered to be within the *purview* of module `mod`, even though it is *attached to* the global module.

Note that GCC and MSVC accept the above module unit.

Also note that clang seems to permit `export extern "C++" { void f(); }`.

**Comment by ChuanqiXu9** [comment]
Good catch. Sorry for misreading the wordings of module purview.
