### ISSUE TITLE
[Flang][OpenMP]Incorrect execution result when reduction-identifier(+) is used in REDUCTION clause

### ISSUE THREAD

**Issue by ohno-fj** [llvm/llvm-project#71370]
```
Version of flang-new : 18.0.0(1c876ff5155c4feeb2b2885eb3e6abda17c4b7f4)
```

Using `reduction-identifier(+)` in `REDUCTION` clause results in incorrect execution.  
The program is executed on 1 thread and expects a value of 11 for a.

The following are the test program, Flang-new, Gfortran and ifort compilation result.

ompds111_2.f90:
```fortran
program main
  integer :: a
  call OMP_SET_NUM_THREADS(1)
  a=1
!$omp parallel reduction(+:a)
  a=10
!$omp end parallel
  print *,a
end program main
```

```
$ flang-new ompds111_2.f90 -fopenmp; ./a.out
 10
$
```

```
$ gfortran ompds111_2.f90 -fopenmp; ./a.out
          11
$
```

```
$ ifort ompds111_2.f90 -qopenmp; ./a.out
          11
$
```

**Comment by kiranchandramohan** [comment]
We are reviewing reduction, specifically to handle cases like this.  https://discourse.llvm.org/t/rfc-openmp-reduction-support/3367/10

**Comment by ohno-fj** [comment]
Thank you for your comments on the development status.

**Comment by kiranchandramohan** [comment]
This is fixed (possibly by https://github.com/llvm/llvm-project/pull/79308)
