### ISSUE TITLE
Is DataLayout::getAlignment for TargetExtType unreachable?

### ISSUE THREAD

**Issue by pmatos** [llvm/llvm-project#71388]
It looks as though the switch case:

```
case Type::TargetExtTyID: {
    Type *LayoutTy = cast<TargetExtType>(Ty)->getLayoutType();
    return getAlignment(LayoutTy, abi_or_pref);
  }
```

in `DataLayout.cpp::getAlignment` is unreachable due to the initial assert:
`assert(Ty->isSized() && "Cannot getTypeInfo() on a type that is unsized!");`.

Type::isSized() has the following case which returns false for TargetExtTyID:
```
    if (getTypeID() != StructTyID && getTypeID() != ArrayTyID &&
        !isVectorTy() && getTypeID() != TargetExtTyID)
      return false;
```

Do we need to improve the check in isSized with for example:

```
if (getTypeID() == TargetExtTyID)
  return getLayoutType()->isSized();
```
?

**Comment by nikic** [comment]
> Type::isSized() has the following case which returns false for TargetExtTyID:

I think you read this the wrong way around? This is an early-exit if the type is *not* TargetExt. The actual handling for TargetExt types is in isSizedDerivedType().

**Comment by pmatos** [comment]
> > Type::isSized() has the following case which returns false for TargetExtTyID:
> 
> I think you read this the wrong way around? This is an early-exit if the type is _not_ TargetExt. The actual handling for TargetExt types is in isSizedDerivedType().

I read it several times to confirm I was correct before creating the issue but only after you pointed out it's an early exit I noticed my error. 🤦🏼 

My apologies. Closing.
