### ISSUE TITLE
Example of `expr1 ? expr2 : expr3` that consists only of inequality expressions and cannot be simplified by clang

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#71383]
Consider the following functions.
https://godbolt.org/z/98EoarhzM
```cpp
// expr1 ? expr2 : expr3 --> expr1
int foo1(int a)
{
   return (a < 5) ? (a < 7) : (a < 3);
}

// expr1 ? expr2 : expr3 --> expr2
int foo2(int a)
{
   return (a < 7) ? (a < 3) : (a < 5);
}

// expr1 ? expr2 : expr3 --> expr3
int foo3(int a)
{
   return (a < 3) ? (a < 5) : (a < 7);
}
```

GCC can simplify these functions. If you rewrite these functions in if-else form as shown below, clang can simplify those.
https://godbolt.org/z/oxjWThe74
```cpp
int bar1(int a)
{
   if(a < 5) return (a < 7);
   else return (a < 3);
}

int bar2(int a)
{
   if(a < 7) return (a < 3);
   else return (a < 5);
}

int bar3(int a)
{
   if(a < 3) return (a < 5);
   else return (a < 7);
}
```

**Comment by junaire** [comment]
This kind of missed optimization is really interesting IMO. 

Looking at the IR pipeline, the if variant got simplified via EarlyCSE pass

![image](https://github.com/llvm/llvm-project/assets/77525145/ecef8922-782c-45e5-9e13-274b6eef8499)

But for the ternary conditional variant, the IR canonicalized to one basic block consists of some `cmp` and `select` instructions:
```llvm
define dso_local noundef i32 @foo1(int)(i32 noundef %a) {
entry:
  %cmp = icmp slt i32 %a, 5
  %cmp1 = icmp slt i32 %a, 7
  %cmp2 = icmp slt i32 %a, 3
  %cond = select i1 %cmp, i1 %cmp1, i1 %cmp2
  %conv = zext i1 %cond to i32
  ret i32 %conv
}
```
So EarlyCSE doesn't work anymore...

**Comment by XChy** [comment]
Such transform could be placed at InstCombine or CVP. And infer the fact based on ConstantRange,

**Comment by antoniofrighetto** [comment]
@nikic, could such an optimization take place in CorrelatedValuePropagation?

**Comment by k-arrows** [comment]
This has been fixed on trunk:
https://godbolt.org/z/s1Kd4vMYK

I will close this issue.
