### ISSUE TITLE
`<iterator>`: `common_iterator`'s data member is public

### ISSUE THREAD

**Issue by hewillk** [llvm/llvm-project#71498]
https://github.com/llvm/llvm-project/blob/a700a520f86e8e667acfe95d8e71b9813120f35b/libcxx/include/__iterator/common_iterator.h#L66-L67

..which shouldn't.

```cpp
#include <iterator>

int main() {
  std::common_iterator<int*, const int*> it;
  return it.__hold_.index();
}
```

**Comment by ldionne** [comment]
We're technically allowed to make the member public -- this doesn't make us non-conforming. But I agree it would be nice to make it private. I think that will require a bit of work though cause we access it from a few places internally.

**Comment by Rajveer100** [comment]
@ldionne 
The issue itself seems clear, if I understand correctly we don't want unnecessary `public` access for `members` of a `class/structure` that can be `accessed/modified` in some other context.

So my intuition would be to make it `private`, then we can potentially create an `accessor` and `mutator` method with a `public/protected` access specifier for internal use? What do you suggest?

**Comment by philnik777** [comment]
I think adding accessor functions would just move the problem. Users aren't allowed to spell any of the names anyways. I think we should just befriend the symbols that access the internal data currently.

**Comment by Rajveer100** [comment]
Ahh yes, much better.

**Comment by Rajveer100** [comment]
For testing, I believe we need to do a `llvm test check` to ensure the files that are accessing it are fixed, or are there any other `places` as well that I must look for?

**Comment by Rajveer100** [comment]
@philnik777 
I did a `git grep` to look for places where `__hold_` is used, although I didn't seem to find any place apart from the `common_iterator.h` file where it's declared in the class. 

Am I doing any mistake for the lookup?

**Comment by Rajveer100** [comment]
@ldionne 
Could you highlight the places where the `public member` is being used?
