### ISSUE TITLE
_LIBCPP_DEBUG_STRICT_WEAK_ORDERING_CHECK should be made part of some hardening modes

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#71496]
I believe that `_LIBCPP_DEBUG_STRICT_WEAK_ORDERING_CHECK` should be made part of some of the hardening modes. It is likely only suitable for the debug mode, although this ties into whether we allow complexity changes made by hardening modes.

**Comment by danlark1** [comment]
Given we check only for first 100 elements, it does not technically change the complexity of the algorithm

**Comment by ldionne** [comment]
Yeah, I think we want to make it part of the debug mode.

**Comment by tstellar** [comment]
Do we still need to backport a fix for this one?

**Comment by ldionne** [comment]
We're good, 8938bc0ad0651f8d481cca2b2b98345d34b3aabe is on `release/18.x`. I tagged these issues with the milestone *before* the branch to indicate that we wanted to merge those in time for the release.
