### ISSUE TITLE
clangd incorrecly says 'header is unused'

### ISSUE THREAD

**Issue by kelbon** [llvm/llvm-project#71529]
Recently updated to llvm17 ~~(to get import std, but it is not yet available as i understand)~~ and If header used only in macro, then 

![image](https://github.com/llvm/llvm-project/assets/58717435/71fabff7-7821-4ebf-b19e-24ccb48112dd)

While i use it:
```cpp
#define $lock(... /* mtx or sequence of mtxs */) \
  ::std::scoped_lock UNIQUE_NAME {          \
    __VA_ARGS__                                  \
  }
struct my_mtx_t {};
void foo(...) {
  $lock(mtx, other.mtx);
}
```
Its pretty common, for example in llvm itself:

// file abc.def
```cpp
A(a)
A(b)
A(c)
```
And in file bcd.hpp

```cpp
#define A(name) use_header(name)
#include "abc.def"
```

P.S. when import std will be available?) I saw commit implementing it dated 9 Sep, but llvm17 do not contain it yet

**Comment by kelbon** [comment]
Same issue when used by compiler (coroutine, initializer list, operator <=>)

Example:
```cpp
#include <compare>
namespace kage {
struct ABC {
  auto operator<=>(const ABC&) const = default;
};

```

**Comment by kadircet** [comment]
Hi @kelbon, unfortunately difficulties around analyzing macro bodies is a general short-coming of clang-tooling, as those are merely tokens without any semantic information.

So the current workaround is to add `// IWYU pragma: keep` next to `<mutex>` and other headers that might are used in macro bodies.

As for `<compare>` that's a separate issue, please file another bug for that one, as these two are completely unrelated issues.
