### ISSUE TITLE
[Flang] Feature request/Discussion: Preprocessor/Prescanner callbacks

### ISSUE THREAD

**Issue by tarcisiofischer** [llvm/llvm-project#71554]
Hello!

I am working on a project called [Codevis](https://invent.kde.org/sdk/codevis), which is able to read C and C++ source code and extract a database representation from it, which is used (among other things) to be visualized in a graph-like structure in a Qt-based application. I am currently running some experiments to read Fortran code on Codevis, and I am using flang to do that.

I am already able to access the Fortran AST and walk around it and extract what we call the "logical representation" of the code. As for a first try, been quite easy, and I must say I really like how things are done in flang :)

The other representation on Codevis, which is the "physical representation" is not related to the data structures, but in relation to the files and inclusions. Basically, for each file, I need to get all `INCLUDE` and persist that file `a.f` depends on `b.f` given that include.
I have been able to hack the code to make it work, by adding a callback inside the Fortran  preprocessor. More specifically, around here:
https://github.com/llvm/llvm-project/blob/75d6795e420274346b14aca8b6bd49bfe6030eeb/flang/lib/Parser/prescan.cpp#L896

My current hack is something like this:
```
  const SourceFile *included{
      allSources_.Open(path, error, std::move(prependPath))};
  if (!included) {
    Say(provenance, "INCLUDE: %s"_err_en_US, error.str());
  } else if (included->bytes() > 0) {
    ProvenanceRange includeLineRange{
        provenance, static_cast<std::size_t>(p - nextLine_)};
    ProvenanceRange fileRange{
        allSources_.AddIncludedFile(*included, includeLineRange)};
    Prescanner{*this}.set_encoding(included->encoding()).Prescan(fileRange);

    if (onFortranInclude) {
        (*onFortranInclude)(included->path());
    }
  }
```

Which is, of course, not ideal, but it works for a first experiment.
I would like to start a conversation in the direction of making ways of intercepting the preprocessor and the prescanner in such a way that I'd have access to those things without having to hack it.

Question 1: Would this be something that LLVM/Flang community would be interested in?
Question 2: Would you be open to start a conversation regarding how to proper design the solution, perhaps having clang's `PPCallback`s as an example to be followed?

If you need further information please let me know.

**Comment by klausler** [comment]
All the information that you need should already be available in the source provenance data structures, including source inclusion via `INCLUDE` and `#include` as well as preprocessor macro replacement.  Take a look at flang/include/flang/Parser/provenance.h.

**Comment by tarcisiofischer** [comment]
@klausler thank you! In my first read I thought they'd only have (start, stop) pairs of each file and raw textual replacement in source and target files (for includes). I'll take another look tomorrow. Hopefully this will be enough.

I'll keep this updated and possibly close this :)

**Comment by tarcisiofischer** [comment]
After trying a bit with provenances, I managed to make _something_ work, but I still feel like the prescan and preprocessor in Flang aren't currently designed to expose data... Maybe it is just my impression, or maybe I am still using it wrong.

This is my current basic idea to extract source files, assuming I have `EXACT_INCLUDE_LOC`:

```
auto showSourceFileFrom = [&allSources](Provenance const& p) {
    auto srcFile = allSources.GetSourceFile(p);
    if (srcFile == nullptr) {
        return; // Doesn't have associated source file
    }
    std::cout << "++ Source file: " << srcFile->path() << "\n";
};
```

[GetSourceFile](https://github.com/llvm/llvm-project/blob/main/flang/lib/Parser/provenance.cpp#L315-L337) takes a `Provenance` as parameter and uses the private `origin` map to return (if valid) the source file to that region.
Assuming this is the way to go, the issue is then to find a reasonable way to get the locations:

```
auto interval = *allSources.GetFirstFileProvenance();
auto currProvenance = interval.start();
while (allSources.IsValid(currProvenance)) {
    std::cout << "+ Provenance: " << currProvenance.offset() << "\n";
    showSourceFileFrom(interval.start());
    interval = interval.NextAfter();
    currProvenance = interval.start();
}
```

This is the output for a toy project:
```
+ Provenance: 4
++ Source file: ./helloworld.f
+ Provenance: 807
++ Source file: ./other.f
+ Provenance: 808
++ Source file: ./other.f
+ Provenance: 809
++ Source file: ./other.f
+ Provenance: 810
++ Source file: ./other.f
(...)
+ Provenance: 896
++ Source file: ./other.f
+ Provenance: 897
++ Source file: ./other.f
+ Provenance: 898
+ Provenance: 899
+ Provenance: 900
(...)
+ Provenance: 961
+ Provenance: 962
+ Provenance: 963
```

Which I found a bit bizarre (I didn't debug to check why the `other.f` isn't in a contigous interval) - I'm assuming I'm either using it wrong or it's a bug, but I wouldn't expect this to be the expected result tbh...

Anyway, I still feel like if we had callbacks directly in the preprocessor and/or prescanner I'd have more control over the things, instead of relying on the data structures that are built from the cooked sources... But if this is not something desirable for Flang, I'd still suggest more public members to extract data from the preprocessor and prescanner, if that makes sense? For instance, I'd be happy to have direct access to the [MapToOrigin](https://github.com/llvm/llvm-project/blob/main/flang/lib/Parser/provenance.cpp#L439-L453) method, also to have access to the `Inclusion`, `Macro` and `CompilerInsertion` structs.

Would that make sense?

**Comment by klausler** [comment]
If you dump the provenance map, you'll find out what's in there.

Callbacks into the prescanner wouldn't be in the right place.  Its job is to build the AllCookedSources, which persists in the drivers throughout compilation.

**Comment by klausler** [comment]
No, I'm not suggesting that you parse the dump!  Just that you could find out from the dump output why the provenance range seem discontiguous.

**Comment by tarcisiofischer** [comment]
AH! Ok. Sorry I misunderstood :) Will debug a bit tomorrow.

I have an idea, though. I'm using the `interval.NextAfter()`, which doesn't take context into account, so it just implements "give me the next thing after the current one" ([See here](https://github.com/llvm/llvm-project/blob/5aa934e2af8727852dec0ec1cfa0cba05d858f70/flang/include/flang/Common/interval.h#L101)) - which is not what I want (I would require it to return `{start_ + size_, <nextSize>}`, but not possible without contextual information).

I couldn't find any better way of retrieving the correct "next item in the list", as most of them is private in the preprocessor currently (sadly), which is why I'm insisting in improving something in the direction of exposing more this data to the consumer (me, using Flang as a Library).

Hope this makes sense.

**Comment by tarcisiofischer** [comment]
I am closing this due to (my own) inactivity. Thank you all for the help with this. Will open a new issue if this is ever needed again :)

**Comment by EugeneZelenko** [comment]
@tarcisiofischer: I could just reopen this one.
