### ISSUE TITLE
Supports viewing class member variables in lambda when using the vs debugger

### ISSUE THREAD

**Issue by GkvJwa** [llvm/llvm-project#71562]
I use clang to compile the following code on windows

```
#include <stdio.h>

class foo {
 public:
  void fun() {
    auto f = [=] {
      int c = a;
      int d = b;
      printf("%d %d\n", c, d);
    };
    f();
  }

 private:
  int a = 1;
  int b = 2;
};

int main() {
  foo f;
  f.fun();
  return 0;
}
```

If during debugging, the execution reaches the breakpoint inside the lambda function.
```
breakpoint at:
      int c = a;
      int d = b;
```
When my mouse is located on member variable a, there is no way to display the value of variable a.
Then I checked the assembly and the recognition support for this pointer, it shows this may only be used inside a nonstatic member function
![unnamed](https://github.com/llvm/llvm-project/assets/22285132/8f124719-11ce-434a-bbd5-f1efa81b024a)

It looks like the same code cannot be compiled with by msvc. Can display the class structure normally, similarly, when I move the mouse over a variable, I can see the value of the variable.

---
So, I asked the relevant personnel at Microsoft for advice on this problem.
After they were able to reproduce it, they told me that the debugger could identify the lambda by whether it could find "__this"
```
IDiaSym.findChildren(SymTagData, L"__this", ...)
```

---
Then I used llvm-pdbutil to view this detail
```
msvc:
  0x3B17 | LF_FIELDLIST [size = 112, hash = 0x3D8EB]
          - LF_ONEMETHOD [name = `operator()`]
            type = 0x3B0D, vftable offset = -1, attrs = public
          - LF_METHOD [name = `<lambda_1>`, # overloads = 2, overload list = 0x3B12]
          - LF_MEMBER [name = `__this`, Type = 0x3B08, offset = 0, attrs = private]
          - LF_ONEMETHOD [name = `operator=`]
            type = 0x3B16, vftable offset = -1, attrs = public
          - LF_ONEMETHOD [name = `__autoclassinit2`]
            type = 0x3B0E, vftable offset = -1, attrs = public compiler-generated
  0x3B18 | LF_CLASS [size = 96, hash = 0xFC7A] `foo::fun::__l2::<lambda_1>`
clang:
   0x1009 | LF_FIELDLIST [size = 20, hash = 0x11D9]
            - LF_MEMBER [name = `this`, Type = 0x1008, offset = 0, attrs = private]
   0x100A | LF_CLASS [size = 80, hash = 0x2636D] `foo::fun::<lambda_1>`
            unique name: `.?AV<lambda_1>@?0??fun@foo@@QEAAXXZ@`
            vtable: <no type>, base list: <no type>, field list: 0x1009
            options: has ctor / dtor | has unique name | scoped, sizeof 8
   0x100B | LF_CLASS [size = 80, hash = 0x2DD4A] `foo::fun::<lambda_1>`
            unique name: `.?AV<lambda_1>@?0??fun@foo@@QEAAXXZ@`
```
The pdb file compiled by msvc does have "__this" symbol, but clang does not

After that, I debugged the code for llvm to generate pdb, and simply replaced the information with "__this" when constructing DataMemberRecord. Recompile, it work

Of course, my patch may not be good

**Comment by dwblaikie** [comment]
@zmodem

**Comment by zmodem** [comment]
+ @ZequanWu who has looked into codeview issues before.

**Comment by ZequanWu** [comment]
I found that lldb also can not get the value of a and b inside the lambda, showing that they are undefined identifiers. I guess it's missing this functionality. Filed at https://github.com/llvm/llvm-project/issues/71837
