### ISSUE TITLE
[C++20] [Modules] Record BMI Hash which is consistent if the interfaces doesn't change

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#71618]
The motivating example comes from https://github.com/llvm/llvm-project/issues/70569.

For example,

```C++
// a.cppm
export module a;
export int a() {
    return 43;
}

// use.cc
import a;
int use() {
    return a();
}
```

After we change the implementation of `a()` from `return 43;` to `return 44;`, we can avoid recompiling use.cc to use.o  since the interface doesn't change.
This is pretty helpful to improve the user's experience by avoiding unnecessary recompilations as much as possible.

**Comment by dwblaikie** [comment]
(might be worth linking to the discourse thread from here so we don't duplicate the discussion)

**Comment by ChuanqiXu9** [comment]
Good idea. We've discussed the ideas here: https://discourse.llvm.org/t/rfc-c-20-modules-introduce-thin-bmi-and-decls-hash/74755

**Comment by ChuanqiXu9** [comment]
This is somehow covered by https://github.com/llvm/llvm-project/pull/86912 with `-fexperimental-modules-reduced-bmi`. 

Now for the example with reduced BMI:

```
//--- A.cppm
export module A;
export int funcA() {
    return 43;
}

//--- A.v1.cppm
export module A;

export int funcA() {
    return 43;
}

//--- B.cppm
export module B;
import A;

export int funcB() {
    return funcA();
}

//--- C.cppm
export module C;
import B;

...
```

Now although B will almost always get changed if module A changes,  but the BMI of B won't change if it doesn't affect the interface. Then we can avoid the recompilation of C.

Note that the original idea that avoid changing the BMI of `A` is considered not good now since we think the source location is significant. 

Then I'd like to close the issue since we may not record and read a BMI hash but generate the same BMI directly.

**Comment by ChuanqiXu9** [comment]
With https://github.com/llvm/llvm-project/pull/92511 landed, I think we can close this.
