### ISSUE TITLE
clang: better diagnostic for member function declaration typo

### ISSUE THREAD

**Issue by edwintorok** [llvm/llvm-project#7165]
|  |  |
| --- | --- |
| Bugzilla Link | [6793](https://llvm.org/bz6793) |
| Version | unspecified |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Testcase:
class A {
  int foo();
};
int A::foo();
{
  return 4;
}

clang++ outputs:
x.cpp:4:8: error: out-of-line declaration of a member must be a definition
int A::foo();
    ~~~^
x.cpp:5:1: error: expected unqualified-id
{
^
2 diagnostics generated.

It'd be better if it'd recognize the ';' typo (or rather copy-pasto), and give a better hint at whats wrong.

It could recognize ';' followed by '{' as a typo.

**Comment by Quuxplusone** [comment]
Duplicate of #10473
