### ISSUE TITLE
"is not a structural type" should be a substitution failure

### ISSUE THREAD

**Issue by ecatmur** [llvm/llvm-project#71684]
On CE trunk 20231108 18.0.0 (https://github.com/llvm/llvm-project.git fb07d9cc096f4a0c2473dee064c427edc2a83157):
```c++
template<auto> struct test {};
template<class T> concept structural = requires { []<T x>(test<x>) {}; };
class C { int i; };
static_assert(not structural<C>);
```
(reduced from https://stackoverflow.com/a/68856187/567292)

fails with hard error:
```
<source>:2:56: error: type 'C' of non-type template parameter is not a structural type
    2 | template<class T> concept structural = requires { []<T x>(test<x>) {}; };
      |                                                        ^
<source>:2:51: note: while substituting into a lambda expression here
    2 | template<class T> concept structural = requires { []<T x>(test<x>) {}; };
      |                                                   ^
<source>:2:51: note: in instantiation of requirement here
    2 | template<class T> concept structural = requires { []<T x>(test<x>) {}; };
      |                                                   ^~~~~~~~~~~~~~~~~~~
<source>:2:40: note: while substituting template arguments into constraint expression here
    2 | template<class T> concept structural = requires { []<T x>(test<x>) {}; };
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:4:19: note: while checking the satisfaction of concept 'structural<C>' requested here
    4 | static_assert(not structural<C>);
      |                   ^~~~~~~~~~~~~
<source>:3:15: note: 'C' is not a structural type because it has a non-static data member that is not public
    3 | class C { int i; };
      |               ^
1 error generated.
Compiler returned: 1
```

Previously (13.0.0 through 17.0.1) this was a substitution failure, which I think it should be.

**Comment by zyn0217** [comment]
I think this is https://github.com/llvm/llvm-project/issues/64138.

**Comment by zyn0217** [comment]
Sorry, I closed the issue too quickly: As CWG2672 says, it is that

> Substituting into the **body** of a lambda-expression is never in the immediate context of substitution into the lambda-expression

which, seems not to cover the substitution for the parameter part of a lambda expression.

@zygoloid Do you think we should regard the non-body parts for a lambda as SFINAE context?

**Comment by zyn0217** [comment]
Friendly ping @cor3ntin and @zygoloid. Also cc @AaronBallman for help.

**Comment by zygoloid** [comment]
Here's the resolution of CWG2672, which is in the middle of being merged into the standard right now: https://github.com/cplusplus/draft/pull/6684/commits/389a869d86d7425341637eb4221c329d7f7d244e

Seems pretty clear that it's only the body of the lambda that's outside the immediate context, so SFINAE should apply here.

**Comment by zygoloid** [comment]
> Another question is, shall we update [the examples](https://eel.is/c++draft/temp.deduct.general#example-7) for [temp.deduct]p9 as well?

Filed an editorial issue to fix the example and hopefully move the wording somewhere more central: https://github.com/cplusplus/draft/issues/6718

**Comment by zyn0217** [comment]
Thank you Richard for clarification (and editorial fixes). Filed #75001 for it.
