### ISSUE TITLE
[FMV] Unhelpful diagnostics when a multi-versioned `target_version("default")` definition comes first

### ISSUE THREAD

**Issue by jroelofs** [llvm/llvm-project#71698]
The error message you get when specifying a `target_version("default")` as the first definition is really unhelpful. We should either:
  *  explicitly forbid that and improve the diagnostics such that they explain exactly what went wrong
  *   or (preferably) fix Sema and allow these to come in any order.

AFAICT, the ACLE doesn't place restrictions on the order that these may occur in: https://github.com/ARM-software/acle/blob/main/main/acle.md#function-multi-versioning

```
__attribute__((target_version("default")))
int callee() {
  return 0;
}

__attribute__((target_version("simd")))
int callee() {
  return 1;
}
```

```
example.c:6:16: warning: attribute declaration must precede definition [-Wignored-attributes]
    6 | __attribute__((target_version("simd")))
      |                ^
example.c:2:5: note: previous definition is here
    2 | int callee() {
      |     ^
example.c:7:5: error: redefinition of 'callee'
    7 | int callee() {
      |     ^
example.c:2:5: note: previous definition is here
    2 | int callee() {
      |     ^
1 warning and 1 error generated.
```

**Comment by jroelofs** [comment]
cc: @ilinpv

**Comment by ilinpv** [comment]
Thank you for trying function multi versioning (FMV) and feedback! From current Sema point of view function with `target_version("default")` or no attribute considered as definition. Attributes must precede definion, so `__attribute__((target_version("simd")))` ignored and we got two definitions of `callee` function -> redefinition error.
We are working on FMV semantic clarification, FMV specification is in beta state and open to changes. Could you elaborate on "any order" semantic proposal, what would you consider as function definition and what semantic relaxations needed?

**Comment by jroelofs** [comment]
I'm not sure. I was only thinking of it from the user perspective.
