### ISSUE TITLE
clang-tidy: llvm-header-guard adds absolute path to header guard

### ISSUE THREAD

**Issue by vadymchan** [llvm/llvm-project#71732]
I encountered an issue with the `llvm-header-guard` check when running Clang-Tidy through the Visual Studio extension - Clang Power Tools. It refactors header guards using absolute paths:
```cpp
#ifndef C:_USERS_VADYM_SOURCE_REPOS_PET_PROJECT_MATH_LIBRARY_SRC_LIB_OPTIONS_OPTIONS_H
#define C:_USERS_VADYM_SOURCE_REPOS_PET_PROJECT_MATH_LIBRARY_SRC_LIB_OPTIONS_OPTIONS_H
```
This behavior isn't ideal. I'm looking for a guard style that reflects the project structure, such as:
```cpp
#ifndef MATH_LIBRARY_OPTIONS_H
#define MATH_LIBRARY_OPTIONS_H
```
, where MATH_LIBRARY_ is project name and OPTIONS_H is file name (it's in ideal case, but at least the header guard should be file name - OPTIONS_H). Is there a way to customize `llvm-header-guard` to generate project-based, rather than absolute path-based, guards?

**Comment by HerrCai0907** [comment]
`llvm-header-guard` is designed only for llvm-projects and you can find lots of hard code path in this check, for example 
```c++
  // We don't want _INCLUDE_ in our guards.
  size_t PosInclude = Guard.rfind("include/");
  if (PosInclude != StringRef::npos)
    Guard = Guard.substr(PosInclude + std::strlen("include/"));

  // For clang we drop the _TOOLS_.
  size_t PosToolsClang = Guard.rfind("tools/clang/");
  if (PosToolsClang != StringRef::npos)
    Guard = Guard.substr(PosToolsClang + std::strlen("tools/"));

  // Unlike LLVM svn, LLVM git monorepo is named llvm-project, so we replace
  // "/llvm-project/" with the canonical "/llvm/".
  const static StringRef LLVMProject = "/llvm-project/";
  size_t PosLLVMProject = Guard.rfind(std::string(LLVMProject));
  if (PosLLVMProject != StringRef::npos)
    Guard = Guard.replace(PosLLVMProject, LLVMProject.size(), "/llvm/");

  // The remainder is LLVM_FULL_PATH_TO_HEADER_H
  size_t PosLLVM = Guard.rfind("llvm/");
  if (PosLLVM != StringRef::npos)
    Guard = Guard.substr(PosLLVM);
```
That means it may be not suitable for the other project.

**Comment by chao-mu** [comment]
This would be incredibly useful. Is there a similar rule that does the same thing but is not LLVM project specific?
