### ISSUE TITLE
[NEON] Wrong return type of NEON intrinsic vqrshrunh_n_s16 in arm_neon.h

### ISSUE THREAD

**Issue by yyctw** [llvm/llvm-project#71751]
The NEON intrinsics `vqrshrunh_n_s16`, `vqrshruns_n_s32`, and `vqrshrund_n_s64` have the wrong return type in `arm_neon.h` in CLANG++-15. According to the ARM documentation https://developer.arm.com/architectures/instruction-sets/intrinsics/vqrshrunh_n_s16, these functions should return `uint8`, `uint16`, and `uint32`, respectively. However, in the header file `llvm-15/lib/clang/15.0.7/include/arm_neon.h`, the return value of these functions is of int type.

Reproduce problem: https://godbolt.org/z/5ebrG1MW1
CLANG version: 
```
Debian clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
Thank you for your reading.

**Comment by EugeneZelenko** [comment]
Looks like `main` has same problem: https://godbolt.org/z/WKPrj3acn
