### ISSUE TITLE
[NEON] Wrong result of NEON intrinsic `vld2q_dup_p16` with the `-march=armv7-a` flag in CLANG-15.

### ISSUE THREAD

**Issue by yyctw** [llvm/llvm-project#71763]
According to the ARM documentation https://developer.arm.com/architectures/instruction-sets/intrinsics/vld2q_dup_p16, `vld2q_dup_p16` loads a 2-element structure from memory and replicates the structure to all the lanes of the two SIMD&FP registers. 
The expected result should be as follows:
```
poly16_t a[2] = {1, 3};
poly16x8x2_t r = vld2q_dup_p16(a);
// The value of r {1, 1, 1, 1, 1, 1, 1, 1,
//                 3, 3, 3, 3, 3, 3, 3, 3}
```
However, the result of `vld2q_dup_p8` with the flags `-march=armv7-a` and `-mfpu=neon` in CLANG-15 is as follows:
```
poly16_t a[2] = {1, 3};
poly16x8x2_t r = vld2q_dup_p16(a);
// The value of r {3, 3, 3, 3, 1, 1, 1, 1,
//                 0, 0, 0, 0, 3, 3, 3, 3}
```
This issue also occurs in `vld2q_dup_p8`.

Reproduce problem: https://godbolt.org/z/6ETT3rjKo
CLANG version:
```
Debian clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
Thank you for your reading.

**Comment by EugeneZelenko** [comment]
@yyctw: Please always try to test latest release (only supported) and main.

**Comment by yyctw** [comment]
> @yyctw: Please always try to test latest release (only supported) and main.

Thank you for the reminder. This is the result after the change: https://godbolt.org/z/bP4d18YMh

**Comment by davemgreen** [comment]
I think this is an example of it going wrong: https://godbolt.org/z/hevqGKfqj

The VLD2DUPq16EvenPseudo/VLD2DUPq16OddPseudo pseudos don't look well defined, there is no register dependency between them.

**Comment by AlfieRichardsArm** [comment]
Fix proposed: https://github.com/llvm/llvm-project/pull/79287

**Comment by AlfieRichardsArm** [comment]
@yyctw This should now be fixed in llvm main, and should be included in the next release. Thank you for the bug report.
