### ISSUE TITLE
the readability-identifier-naming.FunctionCase can not incompatible with 'camelBack' and 'CamelCase'

### ISSUE THREAD

**Issue by DUAN-SS** [llvm/llvm-project#71777]
There are many cases where QT functions are used in projects involving QT，However，the function naming style of QT is camelBack，and many people's habit is to use large humps for function names. So, I hope there is a way to support both large and small humps simultaneously.

**Comment by PiotrZSL** [comment]
You could try to set some case, and setup IgnoreRegexp to other case. You can find them in check source code.

**Comment by DUAN-SS** [comment]
thanks,i got it.
