### ISSUE TITLE
[InstCombine] Missed optimization for (a ^ -1) < -a

### ISSUE THREAD

**Issue by vladimirradosavljevic** [llvm/llvm-project#71789]
This could be optimized to a simple `a != 0`.
[Missed example](https://godbolt.org/z/jjhTWYfzr) and [proof](https://alive2.llvm.org/ce/z/I38PD4).

**Comment by pinskia** [comment]
What is interesting is GCC is able to catch this to do optimizing it first to:
```
  _2 = -a_4(D);
  _7 = .ADD_OVERFLOW (a_4(D), _2);
  _8 = IMAGPART_EXPR <_7>;
```

That is  GCC is able to optimize `__builtin_add_overflow(a, -a, &tmp)` into `(tmp = 0, a != 0)`.

**Comment by XChy** [comment]
LLVM(trunk) folds it now.
