### ISSUE TITLE
Question about how to attach the thread of the process that JIT compile LLVM IR when debug?

### ISSUE THREAD

**Issue by Thrrreeee** [llvm/llvm-project#71796]
When we debug the JIT program, the JIT should create a new thread specifically for compilation operations when compiling LLVM IR. But my current sample compilation speed is very fast, and I cannot find the thread information in time. Is there any way to discover threads or set breakpoints to debug?
JIT process happens between these two lines of code.
https://github.com/llvm/llvm-project/blob/main/llvm/examples/OrcV2Examples/LLJITDumpObjects/LLJITDumpObjects.cpp
![image](https://github.com/llvm/llvm-project/assets/72311224/e54dd39c-dc7a-4d80-86e7-b1415f341882)

**Comment by lhames** [comment]
HI @Thrrreeee. I don't think this is a JIT question, but a debugger one.

The example in question runs all code on the main thread. The best way to debug it would be to launch the application under the debugger:

```
% ninja LLJITDumpObjects
[2/2] Linking CXX executable bin/LLJITDumpObjects
% lldb ./bin/LLJITDumpObjects 
(lldb) target create "./bin/LLJITDumpObjects"
Current executable set to './bin/LLJITDumpObjects' (x86_64).
(lldb) b main
Breakpoint 1: where = LLJITDumpObjects`main + 48 at LLJITDumpObjects.cpp:38:12, address = 0x0000000100004cb0
(lldb) run
Process 14492 launched: './bin/LLJITDumpObjects' (x86_64)
Process 14492 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x0000000100004cb0 LLJITDumpObjects`main(argc=1, argv=0x00007ff7bfeff4e0) at LLJITDumpObjects.cpp:38:12
   35  
   36   int main(int argc, char *argv[]) {
   37     // Initialize LLVM.
-> 38     InitLLVM X(argc, argv);
   39  
   40     InitializeNativeTarget();
   41     InitializeNativeTargetAsmPrinter();
Target 0: (LLJITDumpObjects) stopped.
(lldb) 
```
