### ISSUE TITLE
How can I get GlobalVariable from DIGlobalVariable?

### ISSUE THREAD

**Issue by ash1852** [llvm/llvm-project#71794]
like title says, I recently is upgrade my tool to be compatable with llvm-15(used be compatable with llvm-3.6.2). In llvm-3.6.2 I can get GlobalVariable by using api DIGlobalVariable::getGlobal, whose codes have been shown below, but in llvm-15.0.0 it was removed. How can I get GlobalVariable from DIGlobalVariable? Can i just cast the forth operand of DIGlobalVariable to GlobalVaribale like that in llvm-3.6..2?
![image](https://github.com/llvm/llvm-project/assets/87304478/4c41a925-e0b0-4856-a002-ddc2517fbf58)
thanks in advance for helping.

**Comment by jmorse** [comment]
I believe the connections between Values and Metadata were significantly restructured at some point in the past -- possibly after clang 3.6, but I'm not sure.

As far as I'm aware, there's no direct connection from DIGlobalVariable to the actual GlobalVariable nowadays, you would instead have to enumerate the globals in a module and examine whether they had that DIGlobalVariable attached to them.

**Comment by ash1852** [comment]
ok thanks for you help, if I  enumerate the globals, use getDebugInfo to get a vector of DIGlobalVariableExpression. I'm confused about which DIGlobalVariableExpression should i use to get info like file, source-location...

**Comment by jmorse** [comment]
I think you'll need to fetch the DIGlobalVariableExpression, then if you need the source information use `getVariable` to extract the DIGlobalVariable that it connects to.

**Comment by ash1852** [comment]
> I think you'll need to fetch the DIGlobalVariableExpression, then if you need the source information use `getVariable` to extract the DIGlobalVariable that it connects to.

thank you, but there are more than one DIGlobalVariableExpression connected to a GlobalVariable, which DIGlobalVariableExpression should i use to get debug info? 
![image](https://github.com/llvm/llvm-project/assets/87304478/55a66a7c-ee92-49a4-80e3-81f8b6a006fe)

**Comment by ash1852** [comment]
Is there usually only one DIGlobalVariableExpression for a global variable? and when is there more than one?

**Comment by jmorse** [comment]
I've never seen a Value with more than one debug-metadata-attachment, and I don't know how it'd be printed in textual IR. I'm slightly surprised that there's the facility to get more than one! It's very likely safe to assume that there's only ever zero or one of them.

**Comment by ash1852** [comment]
ok, thank you very much!
