### ISSUE TITLE
Simplification Comparison for `(a | b) ? (a ^ b) : (a & b)` etc. (Clang13 vs Clang trunk)

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#71792]
Consider the following six functions.
https://godbolt.org/z/cTsd43jhh
```cpp
bool test1(bool a, bool b)
{
    return (a | b) ? (a ^ b) : (a & b);
}

bool test2(bool a, bool b)
{
    return (a | b) ? (a & b) : (a ^ b);
}

bool test3(bool a, bool b)
{
    return (a & b) ? (a | b) : (a ^ b);
}

bool test4(bool a, bool b)
{
    return (a & b) ? (a ^ b) : (a | b);
}

bool test5(bool a, bool b)
{
    return (a ^ b) ? (a | b) : (a & b);
}

bool test6(bool a, bool b)
{
    return (a ^ b) ? (a & b) : (a | b);
}
```

Clang13 can simplify four of these, `test1`, `test2`, `test3` and `test4`, while Clang trunk cannot. Neither Clang13 nor Clang trunk can simplify `test5` and `test6`.

**Comment by k-arrows** [comment]
Sorry, maybe I should have made a comparison with Clang14.
https://godbolt.org/z/ec1TbovGb

**Comment by ParkHanbum** [comment]
different 

```
// trunk
Breakpoint 9, llvm::InstCombinerImpl::visitOr (this=0x7fffffffba50, I=...) at /home/m/llvm-trunk/llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp:3561
3561      if (Instruction *CastedOr = foldCastedBitwiseLogic(I))
(gdb) p I.dump()
   %or = or i32 %conv, %conv3
```

```
// 14.0.6
Breakpoint 16, llvm::InstCombinerImpl::visitOr (this=0x7fffffffbe00, I=...) at /home/m/llvm-project/llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp:2931
2931        return CastedOr;
(gdb) p CastedOr->dump()
  <badref> = zext i1 %or1 to i32
$38 = void
```


This patch is probably causing this issue.

https://github.com/llvm/llvm-project/commit/f0071d43e4d30a0bc224020abb52fa77054d2520

if this issue not need fix fast, I can try to fix this. 
would you allow to me?

**Comment by ParkHanbum** [comment]
maybe this patch causes this.

https://github.com/llvm/llvm-project/commit/f0071d43e4d30a0bc224020abb52fa77054d2520](https://github.com/llvm/llvm-project/commit/f0071d43e4d30a0bc224020abb52fa77054d2520)

But to me, the patch seems to have a clear purpose. There is a possibility that it can be solved by removing it, but it is questionable whether this is a desirable direction.

**Comment by ParkHanbum** [comment]
I looked a little further.
The commit causing the problem has neither content nor purpose described, so it is difficult to determine why the commit was written.

As I said before, removing this commit can solve the problem.
I would appreciate it if you could let me know whether you want to use this commit or not.

**Comment by ParkHanbum** [comment]
Unlike the cause of the issue, the way to solve it has become more complicated. reason is that LLVM has decided to no longer allow casting after operation if operator has two casted operand.

maybe this can solved one of followed way.
1. Add WellKnown bit operation in gvn pass
2. Add to `select (icmp eq), true, false` in InstCombine pass


first, assume that we got the ir like below
```
  %a = zext i1 %x to i32
  %b = zext i1 %y to i32
  %or = or i32 %a, %b
  %or0 = icmp eq i32 %or, 0
  br i1 %or0, label %cond.true, label %cond.false

cond.true:                                        ; preds = %entry
  %xor7 = xor i32 %a, %b
  br label %cond.end

cond.false:                                       ; preds = %entry
  %and6 = and i32 %a, %b
  br label %cond.end

cond.end:                                         ; preds = %cond.false, %cond.true
  %cond.in = phi i32 [ %xor7, %cond.true ], [ %and6, %cond.false ]
  %r = icmp eq i32 %cond.in, 0
  ret i1 %r
}
```

It will change as follows
```
  %a = zext i1 %x to i32
  %b = zext i1 %y to i32
  %or = or i32 %b, %a
  %or0 = icmp eq i32 %or, 0
  %xor7 = xor i32 %b, %a
  %and6 = and i32 %b, %a
  %cond.in = select i1 %or0, i32 %xor7, i32 %and6
  %r = icmp eq i32 %cond.in, 0
  ret i1 %r
```

we already know (X&B=0) when (X^Y)=0
so, we can transform first ir like this:
```
  %cond.in = phi i32 [ 0, %cond.true ], [ %and6, %cond.false ]
```
even if you change just this, the results will change. 

```
  %and61 = and i1 %x, %y
  %0 = xor i1 %and61, true
  ret i1 %0
```

and apply same logic to `select` also has same result
```
  %cond = select i1 %tobool4.not, i32 0, i32 %xor
```

```
  %tobool131 = xor i1 %a, %b
  ret i1 %tobool131
```

as this way. this issue could be solved. IMO
