### ISSUE TITLE
ld.lld: error: undefined symbol: std::__glibcxx_assert_fail(char const*, int, char const*, char const*)

### ISSUE THREAD

**Issue by Cerberios** [llvm/llvm-project#71805]
Hello there!
Please I need help with some error - see below.
I want to use LLVM_CLANG for PGO, but unable to compile.
---Configuration---
cmake -G Ninja ${TOPLEV}/llvm-project/llvm -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_PROJECTS="clang;lld;polly;bolt;openmp" -DCMAKE_BUILD_TYPE=Release -DLLVM_BUILD_LLVM_DYLIB=ON -DBUILD_SHARED_LIBS=ON -DLLVM_DYLIB_EXPORT_ALL=ON -DLLVM_PARALLEL_COMPILE_JOBS=4 -DLLVM_PARALLEL_LINK_JOBS=2 -DLLVM_INCLUDE_TESTS=OFF -DLLVM_BUILD_DOCS=OFF -DLLVM_BUILD_EXAMPLES=OFF -DCMAKE_C_COMPILER_LAUNCHER="ccache" -DCMAKE_CXX_COMPILER_LAUNCHER="ccache" -DCMAKE_C_COMPILER=$CPATH/clang -DCMAKE_CXX_COMPILER=$CPATH/clang++ -DCMAKE_RANLIB=$CPATH/llvm-ranlib -DCMAKE_AR=$CPATH/llvm-ar -DLLVM_USE_LINKER=lld -DLLVM_ENABLE_RTTI=ON -DLLVM_ENABLE_EH=ON -DCOMPILER_RT_BUILD_SANITIZERS=ON -DCOMPILER_RT_BUILD_XRAY=ON -DCOMPILER_RT_BUILD_LIBFUZZER=ON -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_RUNTIMES="compiler-rt" -DLLVM_ENABLE_LTO=Thin -DCMAKE_CXX_FLAGS='-D_GLIBCXX_ASSERTIONS' -DCMAKE_CXX_FLAGS_RELEASE="-fopenmp -pipe -march=native -mtune=ivybridge -mllvm -vp-counters-per-site=2 -Wno-backend-plugin -fprofile-instr-use=${TOPLEV}/llvm-build/stage2-prof-gen/profiles/clang.profdata" -DCMAKE_C_FLAGS_RELEASE="-pipe -march=native -mtune=ivybridge -mllvm -vp-counters-per-site=2 -Wno-backend-plugin -fprofile-instr-use=${TOPLEV}/llvm-build/stage2-prof-gen/profiles/clang.profdata" -DCMAKE_INSTALL_PREFIX=${TOPLEV}/llvm-build/stage2-prof-use-lto/install
---

I am not a developer at all, please, help to fix this error. Thanks

[1972/4788] Linking C shared library lib/libomp.so
FAILED: lib/libomp.so
: && /usr/local/sources/llvm-pgo-lto/llvm-build/stage1/install/bin/clang -fPIC -fPIC -fno-semantic-interposition -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-comment -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -flto=thin -Wall -Wcast-qual -Wformat-pedantic -Wimplicit-fallthrough -Wsign-compare -Wno-enum-constexpr-conversion -Wno-extra -Wno-pedantic -pipe -march=native -mtune=ivybridge -mllvm -vp-counters-per-site=2 -Wno-backend-plugin -fprofile-instr-use=/usr/local/sources/llvm-pgo-lto/llvm-build/stage2-prof-gen/profiles/clang.profdata  -Wl,-q -Wl,-z,defs -Wl,-z,nodelete -fuse-ld=lld -Wl,--color-diagnostics -flto=thin -Wl,--thinlto-cache-dir=/usr/local/sources/llvm-pgo-lto/llvm-build/stage4-ready-prof-use-lto/lto.cache  -Wl,--as-needed -Wl,--version-script=/usr/local/sources/llvm-pgo-lto/llvm-project/openmp/runtime/src/exports_so.txt -static-libgcc -Wl,-z,noexecstack -shared -Wl,-soname,libomp.so -o lib/libomp.so projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_alloc.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_atomic.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_csupport.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_debug.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_itt.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_environment.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_error.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_global.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_i18n.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_io.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_runtime.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_settings.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_str.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_tasking.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_threadprivate.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_utility.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_barrier.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_wait_release.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_affinity.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_dispatch.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_lock.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_sched.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_collapse.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/z_Linux_util.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/thirdparty/ittnotify/ittnotify_static.cpp.o projects/openmp/ru
ntime/src/CMakeFiles/omp.dir/kmp_taskdeps.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_cancel.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_ftn_cdecl.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_ftn_extra.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/kmp_version.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/ompt-general.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/ompd-specific.cpp.o projects/openmp/runtime/src/CMakeFiles/omp.dir/z_Linux_asm.S.o  -lm  -ldl && cd /usr/local/sources/llvm-pgo-lto/llvm-build/stage4-ready-prof-use-lto/lib && /usr/bin/cmake -E create_symlink libomp.so libgomp.so && /usr/bin/cmake -E create_symlink libomp.so libiomp5.so
clang: warning: argument unused during compilation: '-mllvm -vp-counters-per-site=2' [-Wunused-command-line-argument]

### ld.lld: error: undefined symbol: std::__glibcxx_assert_fail(char const*, int, char const*, char const*)

>>> referenced by kmp_cancel.cpp
>>>               /usr/local/sources/llvm-pgo-lto/llvm-build/stage4-ready-prof-use-lto/lto.cache/llvmcache-608C62EF786A38CD94ABCF0B9604437B9F418DA7:(__kmpc_cancel)
>>> referenced by kmp_cancel.cpp
>>>               /usr/local/sources/llvm-pgo-lto/llvm-build/stage4-ready-prof-use-lto/lto.cache/llvmcache-608C62EF786A38CD94ABCF0B9604437B9F418DA7:(__kmpc_cancel)
>>> referenced by kmp_cancel.cpp
>>>               /usr/local/sources/llvm-pgo-lto/llvm-build/stage4-ready-prof-use-lto/lto.cache/llvmcache-608C62EF786A38CD94ABCF0B9604437B9F418DA7:(__kmpc_cancel_barrier)
>>> referenced 387 more times

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by shiltian** [comment]
We will use #73248 to track.
