### ISSUE TITLE
And then there's this.

### ISSUE THREAD

**Issue by AnonymousRonin** [llvm/llvm-project#71813]
So here's the entire build file, keep in mind I added the min. version because 90% of the cmakelists files don't have it, despite it being required.  So a required line of text is left out to begin with.  Now see below.

make_minimum_required(VERSION 3.27)

add_llvm_utility(FileCheck
  FileCheck.cpp
  )

target_link_libraries(FileCheck PRIVATE LLVMFileCheck LLVMSupport)

********************
CMake Error at CMakeLists.txt:1 (add_llvm_utility):
  Unknown CMake command "add_llvm_utility".   

4 lines of code and you can't even get that correct?  Not to mention I added the line that was left out.  But I suppose I'm the a**hole for bringing it up.  Which is commonly referred to as "calling you out."  This, this isn't a mistake, or an oversight.  This is "I simply don't give a rip" lazy ass coding.  If I sucked this bad at my job I'd be fired.  

Maybe if it's not too much trouble you could update some of this.

**Comment by cyndyishida** [comment]
@AnonymousRonin When filing issues or otherwise contributing to LLVM, adhere to the [Code of Conduct](https://llvm.org/docs/CodeOfConduct.html). It is required in all LLVM spaces. Please follow up by emailing [conduct@llvm.org](mailto:conduct%40llvm.org) within a 7-day period.
