### ISSUE TITLE
clang does not implement `__assume__` attribute, fails libstdc++ build

### ISSUE THREAD

**Issue by trofi** [llvm/llvm-project#71858]
`gcc` implements `__assume__` attribute as: https://gcc.gnu.org/onlinedocs/gcc/Statement-Attributes.html, quoting the example:

```c
int
foo (int x, int y)
{
  __attribute__((assume(x == 42)));
  __attribute__((assume(++y == 43)));
  return x + y;
}
```

`clang-16` fails to build it as:

```
$ clang -c a.c
a.c:4:18: error: 'assume' attribute cannot be applied to a statement
  __attribute__((assume(x == 42)));
                 ^                ~
a.c:5:18: error: 'assume' attribute cannot be applied to a statement
  __attribute__((assume(++y == 43)));
                 ^                  ~
2 errors generated.
```

Recently `gcc` started using it in `libstdc++` https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=e39b3e02c27bd7 as

```c++
    void
    _M_assume_normalized() const
    {
      unsigned int __ofst = _M_offset;
      __attribute__ ((__assume__ (__ofst < unsigned(_S_word_bit))));
    }
```

and `clang++` now fails to parse `<vector>` from `libstdc++`.

Is there a change `clang` would support this style of `__assume__` attribute or at least skipped it in stead of producing build failure?

**Comment by trofi** [comment]
Meanwhile filed https://gcc.gnu.org/PR112467 on `gcc` side to consider using this style of the attribute only for `gcc`.

**Comment by pinskia** [comment]
Note GCC's assume attribute is the same as C++23 assume standard attribute.

**Comment by shafik** [comment]
CC @erichkeane @AaronBallman

**Comment by erichkeane** [comment]
@AaronBallman is particularly opinionated about attribute `assume` so he should set our policy here.  If it is ok with him, I'd be ok reviewing a statement `assume` attribute.

**Comment by AaronBallman** [comment]
> @AaronBallman is particularly opinionated about attribute `assume` so he should set our policy here. If it is ok with him, I'd be ok reviewing a statement `assume` attribute.

We had a Discourse thread on this, and my thoughts at the time were: https://discourse.llvm.org/t/llvm-assume-blocks-optimization/71609/23 -- my thinking really hasn't changed all that much since then. I think we need LLVM changes before we can effectively implement the attribute and so we should report `0` for `__has_cpp_attribute(assume)` until we're ready to support the attribute.
