### ISSUE TITLE
[AArch64] Missing legalization for G_IS_FPCLASS

### ISSUE THREAD

**Issue by topperc** [llvm/llvm-project#71889]
Saw this opcode while auditing RISC-V fallbacks and noticed AArch64 doesn't legalize it either.

cc: @aemerson

**Comment by arsenm** [comment]
Unrelated but not all the lowering optimization strategies for fpclass were ported from the DAG

**Comment by tschuett** [comment]
[X86](https://reviews.llvm.org/D121296) legalizes it.

**Comment by tschuett** [comment]
Fixed in https://github.com/llvm/llvm-project/pull/72796
