### ISSUE TITLE
declaration conflicts with abs

### ISSUE THREAD

**Issue by Master-Chi** [llvm/llvm-project#71896]
Dear, community
    I am running into a problem when compiling opencv2 using clang+llvm-15.0.6-x86_64-linux-gnu-ubuntu-18.04. The error message showed a conflict in the declaration of the abs function in complex and cmath. However, I don't know how to solve this problem as it seems that both are in the std namespace.

```console
In file included from /home/temp/algorithm-libs/mi_v1.0.0-qsee/src/opencv2/core/src/algorithm.cpp:43:
In file included from /home/temp/algorithm-libs/mi_v1.0.0-qsee/src/opencv2/core/src/precomp.hpp:48:
In file included from /home/temp/algorithm-libs/mi_v1.0.0-qsee/src/opencv2/core/include/opencv2/core/core.hpp:56:
/home/temp/toolchains/clang/bin/../include/c++/v1/complex:854:1: error: declaration conflicts with target of using declaration already in scope0m
abs(const complex<_Tp>& __c)
^
/home/temp/toolchains/clang/bin/../include/c++/v1/cmath:339:1: note: target of using declaration
using ::abs _LIBCPP_USING_IF_EXISTS;
^
/home/temp/toolchains/clang/bin/../include/c++/v1/cmath:339:9: note: using declaration
using ::abs _LIBCPP_USING_IF_EXISTS;
^
In file included from /home/temp/algorithm-libs/mi_v1.0.0-qsee/src/opencv2/core/src/algorithm.cpp:43:
In file included from /home/temp/algorithm-libs/mi_v1.0.0-qsee/src/opencv2/core/src/precomp.hpp:48:
In file included from /home/temp/algorithm-libs/mi_v1.0.0-qsee/src/opencv2/core/include/opencv2/core/core.hpp:56:
/home/temp/toolchains/clang/bin/../include/c++/v1/complex:911:16: error: reference to unresolved using declaration
return abs(__c.real());
^
/home/temp/toolchains/clang/bin/../include/c++/v1/cmath:339:1: note: using declaration annotated with 'using_if_exists' here
using ::abs _LIBCPP_USING_IF_EXISTS;
^
```

Look forward to your reply
BRs

**Comment by EugeneZelenko** [comment]
Could you please try 17 or `main` branch?

**Comment by Master-Chi** [comment]
Sir, 
i updated my env and tried clang+llvm-17.0.4-x86_64-linux-gnu-ubuntu-22.04 which got me into a new trouble.

`In file included from /home/temp/algorithm-libs/mi_v1.0.0-qsee/src/opencv2/core/src/algorithm.cpp:43:
In file included from /home/temp/algorithm-libs/mi_v1.0.0-qsee/src/opencv2/core/src/precomp.hpp:48:
In file included from /home/temp/algorithm-libs/mi_v1.0.0-qsee/src/opencv2/core/include/opencv2/core/core.hpp:53:
In file included from /home/rencong/workspace/TA_SDK/sdk/mitee_sdk/toolchains/clang/bin/../include/c++/v1/algorithm:1751:
In file included from /home/rencong/workspace/TA_SDK/sdk/mitee_sdk/toolchains/clang/bin/../include/c++/v1/__algorithm/copy.h:12:
In file included from /home/rencong/workspace/TA_SDK/sdk/mitee_sdk/toolchains/clang/bin/../include/c++/v1/__algorithm/copy_move_common.h:18:
In file included from /home/rencong/workspace/TA_SDK/sdk/mitee_sdk/toolchains/clang/bin/../include/c++/v1/__string/constexpr_c_functions.h:14:
In file included from /home/rencong/workspace/TA_SDK/sdk/mitee_sdk/toolchains/clang/bin/../include/c++/v1/__memory/construct_at.h:23:
In file included from /home/rencong/workspace/TA_SDK/sdk/mitee_sdk/toolchains/clang/bin/../include/c++/v1/new:99:
/home/rencong/workspace/TA_SDK/sdk/mitee_sdk/toolchains/clang/bin/../include/c++/v1/cstdlib:90:5: error: <cstdlib> tried including <stdlib.h> but didn't find libc++'s <stdlib.h> header.
                                                                                                  This usually means that your header search paths are not configured properly.
                                                                                                  The header search paths should contain the C++ Standard Library headers before
                                                                                                  any C Standard Library, and you are probably using compiler flags that make that
                                                                                                  not be the case.
                                                                                                  error <cstdlib> tried including <stdlib.h> but didn't find libc++'s <stdlib.h> header. \`

Look forward to your reply
BRs

**Comment by ldionne** [comment]
I think the error message tells you what's wrong here:

```
error: <cstdlib> tried including <stdlib.h> but didn't find libc++'s <stdlib.h> header.
This usually means that your header search paths are not configured properly.
The header search paths should contain the C++ Standard Library headers before
any C Standard Library, and you are probably using compiler flags that make that
not be the case. error <cstdlib> tried including <stdlib.h> but didn't find libc++'s <stdlib.h> header. 
```

You should check your compiler flags, it looks like you're passing include paths in the wrong order.

Tentatively closing since this is a user issue, but we can keep discussing here if you need additional help. I don't think there's anything to fix on our side though.

**Comment by anutosh491** [comment]
cc @ldionne 

Hi, I'm somewhat new to llvm and I'm facing similar issues like the one above. After a thorough attempt I haven't been able to address it. Could you please educate me on how I could be fixing the above error and what am I doing wrongly. Thanks

**Comment by ldionne** [comment]
Try running your compiler with `-v`, it will print the header search paths it's trying in order. You can also use `--trace-includes` to figure out how you end up including a specific header.

The normal order of include paths would be:

1. The C++ Standard Library (`something/include/c++/v1`) -- this should contain libc++ headers, you can check for e.g. `__config`
2. Clang builtin headers (`something/clang/<version>/include`) -- that directory should contain weird headers like `xmmintrin.h`
3. The C Standard Library (`sysroot/usr/include`) -- this should contain your usual C headers like `stdlib.h`

When you include `<stdlib.h>` from your C++ file, it will start by hitting `stdlib.h` provided in (1), then `#include_next` into (2) if there's one (I don't remember), and then `#include_next` into (3). Right now you probably have (3) appearing before (1) and we're complaining about that.
