### ISSUE TITLE
__builtin_classify_type (0uwb)

### ISSUE THREAD

**Issue by jakubjelinek** [llvm/llvm-project#71911]
GCC 14 added code 18 for _BitInt types (signed or unsigned) from __builtin_classify_type, while clang returns -1.  The new code
would be better so that one can distinguish _BitInt types in C macros from other integral types.

Note, GCC 14 also extended the builtin, so that it either accepts (unfortunately for historical reasons promoted) expression,
but also a type, in which case it can get also return values for unpromoted types.  E.g.
__builtin_classify_type (typeof (expr)) or __builtin_classify_type (int).  In C++ one can use templates, but in C _Generic only allows
distinguishing stuff for known types, but in case of _BitInt types can only do so for a particular width and not for say all unsigned _BitInts of any width.

**Comment by jakubjelinek** [comment]
@AaronBallman

**Comment by tbaederr** [comment]
> Note, GCC 14 also extended the builtin, so that it either accepts (unfortunately for historical reasons promoted) expression,
> but also a type, in which case it can get also return values for unpromoted types. E.g.
> __builtin_classify_type (typeof (expr)) or __builtin_classify_type (int). In C++ one can use templates, but in C _Generic only allows
> distinguishing stuff for known types, but in case of _BitInt types can only do so for a particular width and not for say all unsigned _BitInts of any width.

The relevant commit for these changes is https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=53d834a7fae3afffebb45a2d66908f705773a7fc, in case anyone wants to tackle that.

**Comment by jakubjelinek** [comment]
Also GCC was changed today to return __builtin_classify_type () == 19 for vector types.

**Comment by AaronBallman** [comment]
`_BitInt` classification was updated in ea316625d1c984d63610a580b138c800115bfd86

> Also GCC was changed today to return __builtin_classify_type () == 19 for vector types.

Clang also returns 19 for vector types: https://godbolt.org/z/r3EsYKfdG

Closing this issue as completed.
