### ISSUE TITLE
[LLVM-dwp] About llvm-dwp optimized implementation: when the section reaches the 4GB limit, stop packaging and immediately generate the .dwp file

### ISSUE THREAD

**Issue by Labman-001** [llvm/llvm-project#71910]
When 'ContinueOnCuIndexOverflow' enables without this modification, the forcibly generated '.dwp' won't be recognized by Debugger correctly.
<img width="657" alt="image" src="https://github.com/llvm/llvm-project/assets/150100070/31732775-2548-453a-a47a-fa04c6d05fe9">
When llvm-dwp enables option 'ContinueOnCuIndexOverflow' and recognize the overflow problem , it will stop packing and generate '.dwp' at one. 
<img width="625" alt="image" src="https://github.com/llvm/llvm-project/assets/150100070/77d6be24-262b-4f4c-afc0-9a6c49e133c7">

PR: https://github.com/llvm/llvm-project/pull/71902/files

**Comment by Labman-001** [comment]
And here is my launched PR 
https://github.com/llvm/llvm-project/pull/71902 
@dwblaikie

**Comment by dwblaikie** [comment]
(you don't need to file an issue first before a PR - and probably easier not to do both at the same time - it risks fragmenting the discussion. I think I'll keep the discussion on the PR if possible)
