### ISSUE TITLE
clang assertion when compiling reinterpret_cast<float3>(float4_var)

### ISSUE THREAD

**Issue by bixia1** [llvm/llvm-project#7194]
|  |  |
| --- | --- |
| Bugzilla Link | [6822](https://llvm.org/bz6822) |
| Version | trunk |
| OS | Windows XP |
| CC | @zygoloid |

## Extended Description 
float3 and float4 are defined by the test case below.
Clang seems to believe that BitWidth(float3) = 4 * BitWidth(float) while LLVM Core VectorType::getBitWidth(float3) returns 3 * BitWidth(float). This discrepancy causes the assertion error. Where are you doing to fix this, Clang or LLVM Core?
Thanks for your attention to this bug!

command line:
================
clang -emit-llvm -ObjC++ -S vector03.c

error message:
================
Assertion failed: castIsValid(getOpcode(), S, Ty) && "Illegal BitCast", file ... llvm\lib\VMCore\Instructions.cpp, line 2732

test case:
================
typedef float float4 __attribute__((ext_vector_type(4)));
typedef float float3 __attribute__((ext_vector_type(3)));
//typedef float float2 __attribute__((ext_vector_type(2)));

typedef struct _mystruct {
    float3 field1;
    float field2;
    float field3;
    float field4;
    float field5;
} mystruct;

float3 foo() {
  float3 vec3;
  float4 vec4;
  vec4 = sizeof(mystruct);
  vec3 = reinterpret_cast<float3>(vec4);

  return vec3;
}

**Comment by gwelymernans** [comment]
We don't assert here, but reject it with an error message:

```
pr.cc:17:10: error: reinterpret_cast from vector 'float4' (vector of 4 'float' values) to vector 'float3' (vector of 3 'float' values) of different size
  vec3 = reinterpret_cast<float3>(vec4);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Please open another issue if you encounter this bug again.
