### ISSUE TITLE
packaging: No i386 packages for clang-16 on https://apt.llvm.org - bookworm

### ISSUE THREAD

**Issue by mtwebster** [llvm/llvm-project#71946]
Only three architectures are published here (amd64, arm64, s390):
https://apt.llvm.org/bookworm/pool/main/l/llvm-toolchain-16/

Both 15 and 17 are fine.

Thanks!

**Comment by asl** [comment]
Tagging @sylvestre

**Comment by sylvestre** [comment]
i restarted the build with i386, let's see it works

**Comment by sylvestre** [comment]
I think it is fixed
