### ISSUE TITLE
[llvm][docs] directory wrong

### ISSUE THREAD

**Issue by cyk2018** [llvm/llvm-project#71941]
It seems the directory is wrong in part [Developing LLVM passes out of source](https://github.com/llvm/llvm-project/blob/main/llvm/docs/CMake.rst#id31) . There is no Transform directory but Transforms directory

**Comment by alekuz01** [comment]
Hi,

fix required in two places: 

'''
llvm/docs/CMake.rst:1121:#. Copying ``<pass name>`` folder into ``<LLVM root>/lib/Transform`` directory.
llvm/docs/CMake.rst:1124:   ``<LLVM root>/lib/Transform/CMakeLists.txt``.
'''

**Comment by alekuz01** [comment]
Fix is merged.
