### ISSUE TITLE
Missing access control check for injected-class-names used as template-names

### ISSUE THREAD

**Issue by DougGregor** [llvm/llvm-project#7197]
|  |  |
| --- | --- |
| Bugzilla Link | [6825](https://llvm.org/bz6825) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@hubert-reinterpretcast |

## Extended Description 
We aren't performing access control for injected-class-names that are used as template names, e.g.,

terfin:clang dgregor$ cat t3.C
template <class T> struct Base { }; 

template<typename T> class Between : private Base<T> { };

template <class T> struct Derived : private Between<int>, private Between<char> {
  Base<double> d;
};

Derived<double> dd;
terfin:clang dgregor$ clang++ -fsyntax-only t3.C
terfin:clang dgregor$ eccp -A t3.C
"t3.C", line 6: error: type "Base<T>::Base [with T=int]" (declared at line 1)
          is inaccessible
    Base<double> d;
    ^
          detected during instantiation of class "Derived<T> [with T=double]"
                    at line 9

1 error detected in the compilation of "t3.C".

The solution is not trivial, because we are performing some ambiguity resolution (per C++ [temp.local]p4) when the injected-class-names are mapped to class templates, so we will need to hold on to all of the paths to each of the injected-class-names; some of those paths may not be accessible while others are.

GCC doesn't diagnose this example, nor does EDG in non-strict mode, so it's not critical.

**Comment by wheatman** [comment]
This was fixed between 8.0.1 and 9.0.0
https://godbolt.org/z/3vojEsqrh

code 
```
template <class T> struct Base { }; 

template<typename T> class Between : private Base<T> { };

template <class T> struct Derived : private Between<int>, private Between<char> {
  Base<double> d;
};

Derived<double> dd;
```

new error
```
<source>:6:3: error: 'Base' is a private member of 'Base<int>'
  Base<double> d;
  ^
<source>:3:38: note: constrained by private inheritance here
template<typename T> class Between : private Base<T> { };
                                     ^~~~~~~~~~~~~~~
<source>:1:27: note: member is declared here
template <class T> struct Base { }; 
                          ^
1 error generated.
Compiler returned: 1
```
