### ISSUE TITLE
`clang` 17 chokes on empty input file

### ISSUE THREAD

**Issue by DDvO** [llvm/llvm-project#72023]
I came across this while trying to work around an OpenSSL build issue by pretending (using `touch`) that some `.o` file was produced.
The issue can be reproduced as simply as this: 
 ```
$ touch empty_file && clang empty_file 
clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)

$ clang --version
Homebrew clang version 17.0.4
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
```

**Comment by thevinster** [comment]
Was this ever working before? I'm not so sure if this is a supported use case at all since you're not specifying any file extension. Trying this with Apple's linker (ld64 from Xcode 15) also reports the same issue, so I'm not so sure what the bug here is.

**Comment by DDvO** [comment]
> Was this ever working before?

I did not try with earlier versions.

> I'm not so sure if this is a supported use case at all

Of course, an empty input file usually is not very useful ;-)
Yet it raises stability concerns if a software crashes on any (invalid) input.
At least any fuzzing tool will not like this, for good reason.

**Comment by BertalanD** [comment]
Thanks for the report! I did a little investigation: it looks like a bug in Apple's linker (specifically, `ld_new`/`ld_prime`, which was introduced in the latest Xcode release).

- Using the system linker provided by Xcode, Clang defaults to (and resolves to `ld_new` nowadays):
  ```console
  ❯ build/bin/clang empty_file
  clang: error: unable to execute command: Segmentation fault: 11
  clang: error: linker command failed due to signal (use -v to see invocation)

  ```

- Using the system linker provided by Xcode, explicitly overriding it to use the old linker:
  ```console
  ❯ build/bin/clang empty_file -Wl,-ld_classic
  ld: file too small (length=0) file 'empty_file' for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  ```

- Using `ld64.lld`:
  ```console
  ❯ build/bin/clang empty_file -fuse-ld=$(pwd)/build/bin/ld64.lld
  ld64.lld: error: empty_file: unhandled file type
  ld64.lld: error: undefined symbol: main
  >>> referenced by the entry point
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  ```

None of these error messages are great, but it looks like only Apple's new linker exhibits the described behavior.  That is a completely separate software project, whose development we don't have any influence over. The best course of action would be to file a bug report via the [Feedback Assistant](https://feedbackassistant.apple.com).

I'm closing this issue as it doesn't seem related to LLVM's code, but feel free to reopen if there is something we could do better.

**Comment by DDvO** [comment]
Thank you @BertalanD for your investigation!

Interesting to learn that not clang itself crashes on such input but the new linker by Apple.
Certainly it would not be worth adding a workaround to prevent this at LLVM side.

I would not have filed this issue here if this had been clear from the error output.
Would be good if the error message `unable to execute command` mentioned the actual binary having a problem,
both for users and LLVM developers like you investigating such issues.
