### ISSUE TITLE
8.0.0/docs/ReleaseNotes

### ISSUE THREAD

**Issue by mamiao** [llvm/llvm-project#72041]
hi,

https://releases.llvm.org/8.0.0/docs/ReleaseNotes.html
I just want to see some info about 8.0.0 but this link gives me 404. Could you please help me to fix that or give me another link which is also fine.

Thanks

**Comment by brad0** [comment]
We're nowhere near the 8.0 release. There are no complete release notes written. What are you trying to find?

**Comment by brad0** [comment]
Something happened to the releases.llvm.org setup and I think it's redirected to somewhere else at the moment.

You can find release notes for 8 from the 8 branch. If you look under each respective projects docs/ dir for ReleaseNotes.rst.

https://github.com/llvm/llvm-project/blob/release/8.x/llvm/docs/ReleaseNotes.rst
https://github.com/llvm/llvm-project/blob/release/8.x/clang/docs/ReleaseNotes.rst

**Comment by asl** [comment]
This was fixed.
