### ISSUE TITLE
clang-tidy: warning on passing by value beyond size

### ISSUE THREAD

**Issue by lamarrr** [llvm/llvm-project#72044]
often passing by value beyond a certain-size is not good performance-wise. typically beyond the register size. is there a clang-tidy warning that enables this? if not, do you think it is worth adding? if so I'd like to implement it

**Comment by firewave** [comment]
There's several checks which detect this within various contexts:
[performance-for-range-copy](https://clang.llvm.org/extra/clang-tidy/checks/performance/for-range-copy.html)
[performance-unnecessary-copy-initialization](https://clang.llvm.org/extra/clang-tidy/checks/performance/unnecessary-copy-initialization.html)
[performance-unnecessary-value-param](https://clang.llvm.org/extra/clang-tidy/checks/performance/unnecessary-value-param.html)

There's no configuration for a size threshold though. And I think the warnings only apply to C++ code.

**Comment by firewave** [comment]
There's also a feature request about a different case where there is a potential unnecessary/unintended by-value usage: #25256.

**Comment by lamarrr** [comment]
alright, thanks!
