### ISSUE TITLE
back-port: Add RV64 constraint to SRLIW

### ISSUE THREAD

**Issue by SchmErik** [llvm/llvm-project#72155]
Hello, I am trying to get [this](https://github.com/llvm/llvm-project/pull/69416) back ported because it fixes [this codegen issue on rv32im targets](https://github.com/llvm/llvm-project/issues/69408). We found the issue on Rust version 1.70 and beyond. 

I'm new to llvm in general including the llvm release and backport process and would like to backport this commit. On our first attempt of the back porting, we created a PR by [commenting on the PR that solved our issue](https://github.com/llvm/llvm-project/pull/69416#issuecomment-1800191964) which created [this PR](https://github.com/llvm/llvm-project-release-prs/pull/767). After reading [this](https://llvm.org/docs/GitHub.html#backporting-fixes-to-the-release-branches) more carefully, I think the cherry pick comment should have been written on a github issue rather than a PR so I've open this issue to track the back porting of this commit.

Again, I'm new to this process so please feel free to let me know if I am missing any info or if there's anything I can do to push the process along. Thanks in advance!

**Comment by SchmErik** [comment]
/cherry-pick [f48dab5](https://github.com/llvm/llvm-project/commit/f48dab523784252448dbd42e72f0048ee0463368)

**Comment by topperc** [comment]
/cherry-pick [f48dab5](https://github.com/llvm/llvm-project/commit/f48dab523784252448dbd42e72f0048ee0463368)

**Comment by SchmErik** [comment]
@topperc is it possible to backport this to llvm 16 in addition to 17? Codegen for rv32 is broken for this instruction on 16...

**Comment by EugeneZelenko** [comment]
@SchmErik: Only most recent release is maintained.

**Comment by SchmErik** [comment]
> @SchmErik: Only most recent release is maintained.

Thanks for your response! I'm glad I asked! The reason why I asked was because rust versions that depend on llvm 16 are broken for rv32im so I will take it up with rust maintainers. @nikic I think you're involved in rust's llvm integration. I'll create a separate issue in rust-lang for this but let me know if there's someone else that I should tag!

**Comment by nikic** [comment]
@SchmErik All currently supported Rust versions use LLVM 17, not LLVM 16.
