### ISSUE TITLE
Cannot build llvm-libc against Ubuntu 14.04

### ISSUE THREAD

**Issue by petrhosek** [llvm/llvm-project#72151]
I tried building llvm-libc in the overlay mode against Ubuntu 14.04 based sysroot but I ran into two issues:

1. [libc/src/sys/random/getrandom.h](https://github.com/llvm/llvm-project/blob/877226f01fb75d7989acfdcd5a86754f16fe5365/libc/src/sys/random/getrandom.h#L12) includes `sys/random.h` but this header doesn't (yet) exist in Ubuntu 14.04.
2. [libc/src/sys/stat/linux/kernel_statx.h](https://github.com/llvm/llvm-project/blob/dc298fecb79608e6628bd730ece42a6a77197a3c/libc/src/sys/stat/linux/kernel_statx.h#L76) unconditionally uses `SYS_statx` but this value isn't defined because `__NR_statx` isn't defined on Ubuntu 14.04 (which is used in [libc/config/linux/syscall_numbers.h.inc](https://github.com/llvm/llvm-project/blob/main/libc/config/linux/syscall_numbers.h.inc#L2074)).

**Comment by michaelrj-google** [comment]
This should be fixed by #72318, please reopen if it isn't.
