### ISSUE TITLE
regression? clang-tidy modernize-use-using does not work for typedef in a function

### ISSUE THREAD

**Issue by e-kwsm** [llvm/llvm-project#72179]
Prepare `/tmp/a.cpp`
```cpp
void f() {
  typedef int foo;
}
```
and `/tmp/compile_commands.json`
```json
[ { "directory": "/tmp", "command": "clang++ -std=c++11 -c -o a.o a.cpp", "file": "a.cpp", "output": "a.o" } ]
```

clang-tidy version 14.0.6 on Debian Bookworm points out the `typedef` as expected:
```console
$ clang-tidy --checks='-*,modernize-use-using' a.cpp
1 warning generated.
/tmp/a.cpp:2:3: warning: use 'using' instead of 'typedef' [modernize-use-using]
  typedef int foo;
  ^~~~~~~~~~~~~~~
  using foo = int
```
while 16.0.6 on EndeavourOS does not; the latter works for `typedef`s in other scopes&mdash;global, in a namespace, and in a struct.

**Comment by EugeneZelenko** [comment]
Could you please try 17 or `main` branch? https://godbolt.org should be helpful.

**Comment by e-kwsm** [comment]
Reproduced with the trunk (18.0.0git): <https://godbolt.org/z/Wh61v37Wv>

**Comment by e-kwsm** [comment]
clang-tidy fe94ae83ecf356fd2d63b7cd15f37aaafdbc14ef still has the issue.
