### ISSUE TITLE
Sema::isSimpleTypeSpecifier should return true for `_Bool` from C99 onwards

### ISSUE THREAD

**Issue by carlos4242** [llvm/llvm-project#72203]
Relates to an existing FIXME in code: https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaDecl.cpp#L131

--

As discussed in https://discourse.llvm.org/t/should-issimpletypespecifier-return-true-for-bool/74873, this would be a handy little addition for some use cases (for example in Swift, which uses it in the clang importer).

I have prepared a patch already and will raise a PR after I've raised this issue, to aid in tracking, and to avoid someone duplicating the work in future.

**Comment by shafik** [comment]
CC @AaronBallman
