### ISSUE TITLE
clang is suboptimal for `-a * (-a * a)`

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#72259]
Consider the following two functions.
https://godbolt.org/z/Taza3zT3G
```cpp
int foo(int a) {
    return -a * (-a * a);
}

int bar(int a) {
    return (-a * -a) * a;
}
```

I expect the following output for both functions.
```llvm
        mov     eax, edi
        imul    eax, edi
        imul    eax, edi
        ret
```

But interestingly, the output of Clang is better than that of GCC for the following function.
https://godbolt.org/z/17qvs9xcd
```cpp
int foo1(int a, int b, int c) {
    return -a * (-b * c);
}
```

**Comment by pinskia** [comment]
Note GCC only optimizes this at the RTL level and not the gimple level, filed  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113189 to optimize it at the gimple level too.
