### ISSUE TITLE
Cherry-pick libc++ sized deallocation fix

### ISSUE THREAD

**Issue by ilya-biryukov** [llvm/llvm-project#72255]
This fixes the use of `make_shared` for arrays (C++20) with `-fsized-deallocation`. This should be relatively common for those who use C++20.

/cherrypick f722db02d359e29ca001b78197ee1a275f8c3d7c

**Comment by ilya-biryukov** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/f722db02d359e29ca001b78197ee1a275f8c3d7c

**Comment by ilya-biryukov** [comment]
(I hope I am doing it right, it is my first time using this automation)

**Comment by ldionne** [comment]
Approved for cherry-picking.
