### ISSUE TITLE
Clang accepts a source file with no declarations

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7225]
|  |  |
| --- | --- |
| Bugzilla Link | [6853](https://llvm.org/bz6853) |
| Version | unspecified |
| OS | NetBSD |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
in pedantic errors mode; this is not permitted by the C90 and C99 standards.

**Comment by AaronBallman** [comment]
This was resolved in Clang 3.2: https://gcc.godbolt.org/z/abss4549h
