### ISSUE TITLE
[CUDA][HIP] file-scope device variable not allowed with trivial ctor

### ISSUE THREAD

**Issue by yxsamliu** [llvm/llvm-project#72261]
`struct A {
  A() {}
  ~A() {}
  int x;
};

__device__ A x;`

the above code is allowed with nvcc but not cuda-clang.

https://godbolt.org/z/jjMG3zTd3

https://godbolt.org/z/74Ed1WvGn

nvcc allows it not because it makes the ctor A::A() implicitly host device (this can be seen by defining A x in device function), but because it does not check host/device availability for file-scope device var.

I think it makes sense to make trivial ctor/dtor implicitly host device.

@Artem-B

**Comment by Artem-B** [comment]
> I think it makes sense to make trivial ctor/dtor implicitly host device.
SGTM.

**Comment by Artem-B** [comment]
@yxsamliu The patch is causing compilation issues: https://github.com/llvm/llvm-project/pull/72394#issuecomment-1817768149
