### ISSUE TITLE
[mlir][pass] how can i know the pass effect ? like find the different dialect between after pass and before

### ISSUE THREAD

**Issue by LiuYang328** [llvm/llvm-project#72342]
for example 

-convert-arith-to-llvm  :  convert arith dialect to llvm dialect 

but how can i know -convert-linalg-to-loops ? 
how can i find in the source code in mlir lib?

**Comment by joker-eph** [comment]
We use issue tracking for bugs and feature request. If you need help please use discourse forums: https://discourse.llvm.org/c/mlir/31

I also invite you to be much more descriptive about your question, the title of the issue and what you wrote as question in the description don't seem to line up very clearly to me.
