### ISSUE TITLE
[mlir][gpu] Reduce operations diverged from vector combining kinds

### ISSUE THREAD

**Issue by kuhar** [llvm/llvm-project#72354]
The gpu dialect provides a number of available reduction kinds (`gpu::AllReduceOperation`) available in ops, `gpu.all_reduce` and `gpu.subgroup_reduce`. Currently, these reduction kinds are: add, and, max, min, mul, or, xor.

The `min` and `max` reductions are ambiguous for integer (e.g., signed min != unsinged min) and float types (NaN handling). I think these should be aligned with vector reduction kinds that resolve these ambiguities:
> add/mul/**minsi/minui/maxsi/maxui**/and/or/xor for integers,
> and add/mul/**minf/maxf/minimumf/maximumf** for floats.

Because the gpu dialect does not depend on the vector dialect, the most practical choice would be to copy over the min/max kinds from the vector dialect.

Have I missed something?

**Comment by kuhar** [comment]
One other difference is that vector reductions can also have fast math flags (https://github.com/llvm/llvm-project/pull/66905), which are absent from gpu reductions.

cc: @antiagainst @nicolasvasilache @unterumarmung @dcaballe @joker-eph

**Comment by nicolasvasilache** [comment]
Makes sense to me, is there a way to write these in one common place and just include them in the proper Tablegen file?

**Comment by antiagainst** [comment]
Maybe put in a new `include/mlir/Dialect/Utils/ReductionCombinerUtils.td` file or something?

**Comment by kuhar** [comment]
> Makes sense to me, is there a way to write these in one common place and just include them in the proper Tablegen file?

> Maybe put in a new `include/mlir/Dialect/Utils/ReductionCombinerUtils.td` file or something?

Yeah this also makes sense, but I'd rather do it in two stages: (1) update gpu reductions, (2) introduce a common definition.

**Comment by antiagainst** [comment]
Sequencing sounds good to me!

**Comment by dcaballe** [comment]
> Makes sense to me, is there a way to write these in one common place and just include them in the proper Tablegen file?

+ 1 to having a common place.

I think I saw another replication of this recently but I can't remember... Perhaps on the SVE/SME side? (@c-rhodes, @MacDue)?

**Comment by kuhar** [comment]
I found one more enum like that in NVVM:
```c++
namespace NVVM {
// NVVM redux kind
enum class ReduxKind : uint32_t {
  ADD = 1,
  AND = 2,
  MAX = 3,
  MIN = 4,
  OR = 5,
  UMAX = 6,
  UMIN = 7,
  XOR = 8,
};
```

**Comment by c-rhodes** [comment]
> > Makes sense to me, is there a way to write these in one common place and just include them in the proper Tablegen file?
> 
>     * 1 to having a common place.
> 
> 
> I think I saw another replication of this recently but I can't remember... Perhaps on the SVE/SME side? (@c-rhodes, @MacDue)?

@MacDue added one to ArmSME for outerproducts recently in #69604:
https://github.com/llvm/llvm-project/blob/f8986dfce2dbe040ad41e017e3b87abb60138df8/mlir/include/mlir/Dialect/ArmSME/IR/ArmSMEOps.td#L130-L143

but it only supports add/sub.

**Comment by grypp** [comment]
> I found one more enum like that in NVVM:
> 
> ```c++
> 
> namespace NVVM {
> 
> // NVVM redux kind
> 
> enum class ReduxKind : uint32_t {
> 
>   ADD = 1,
> 
>   AND = 2,
> 
>   MAX = 3,
> 
>   MIN = 4,
> 
>   OR = 5,
> 
>   UMAX = 6,
> 
>   UMIN = 7,
> 
>   XOR = 8,
> 
> };
> 
> ```
> 
> 
> 
> although I do not intend to touch this one, as it seems backend-specific.

This enum keeps the supported reduction types for 'redux' instruction in PTX. You're right this backend specific, I think let's keep it this as it is.

**Comment by kuhar** [comment]
Another alternative would be to make the gpu dialect use the enums/attributes from the vector dialect, similar to how we use arith fast math flags in the vector dialect. But this introduces a new dependency on the vector dialect (currently the GPU dialect depends only on arith).

**Comment by kuhar** [comment]
This is done modulo sharing the attributes across dialects. I don't know how to make this happen and am not planning any further work here, so I'm going to close this issue.
