### ISSUE TITLE
[BOLT] exceptions catch lead to segv when binary compile with no-pie

### ISSUE THREAD

**Issue by zct** [llvm/llvm-project#72363]
clang++ version :16

bolt --version output:

>   LLVM version 16.0.0. DEBUG build with assertions. BOLT revision 08d094a0e457360ad8b94b017d2dc277e697ca76

 
reproduce demo

```
int Foo() { throw 42; }

int main() {
  try {
    return Foo();
  } catch (...) {
    return 0;
  }
}
```

when compile with -no-pie，after bolt optimization, it SIGSEGV when run the main.bolted. here is the build script:

>  clang++ main.cc -g -Wl,--emit-relocs -stdlib=libc++  -lc++abi -pthread -no-pie -o main
>  llvm-bolt  ./main -o main.bolted

Since programs compiled after llvm15 are compile with pie by default, here if I remove the no-pie option, the Bolt-optimized program will run without SEGV errors. 

I would like to know what caused the no-pie program SEGV. Thank you for your reply

**Comment by zct** [comment]
If libc++ is replaced by libstdc++, the optimized program will not suffer segv errors
```
clang++ main.cc -g -Wl,--emit-relocs -stdlib=libstdc++-pthread -no-pie -o main
llvm-bolt ./main -o main.bolted
```

**Comment by maksfb** [comment]
`libc++`/`libc++abi` has the following adjustment that adds wrong `lpStart`value to the exception handler address: https://github.com/llvm/llvm-project/blob/a9cc6fc28078de3e0391b477505c2d3d84f52e4b/libcxxabi/src/cxa_personality.cpp#L713

The real value of `lpStart` is 0, but the code sets it to the function start here: https://github.com/llvm/llvm-project/blob/a9cc6fc28078de3e0391b477505c2d3d84f52e4b/libcxxabi/src/cxa_personality.cpp#L665-L666

`libgcc` doesn't have this problem.

Unlike BOLT, compiler omits `lpStart`. The reason we use different `lpStart` from the compiler is related to the way we split code and described in detail here: https://github.com/llvm/llvm-project/blob/337f0ededc2201bf1c367dfe6c96177772571105/bolt/lib/Core/BinaryEmitter.cpp#L968-L974

**Comment by zct** [comment]
Thanks for your detailed analysis, it seems to be a bug in the libc++abi;
Are there any temporary fixes in the libc++abi or bolt code that our local development environment can bypass

**Comment by maksfb** [comment]
If you can rebuild libc++abi with #72727, exceptions will work.

**Comment by zct** [comment]
thanks , it works for me
