### ISSUE TITLE
[FR] clang-tidy check for implicit inline

### ISSUE THREAD

**Issue by FalcoGer** [llvm/llvm-project#72397]
The [`inline` keyword](https://en.cppreference.com/w/cpp/language/inline) is widely misunderstood. On top of that there are many instances where inline is implicit. I think it's therefore best to eliminate the `inline` keyword from code where possible.

I propose a checker that checks if the `inline` keyword may be required in the context that it is in and propose a fix to remove it where it isn't.

```c++
template <typename T> inline T f()
//                    ~~~~~~
//                    ^ Templated functions behave like inline functions.
{
    return T{};
}

template <> inline double f<double>() = delete;
//          ~~~~~~
//          ^ Deleted functions are implicitly inline

inline int g(float a) // May be OK, no diagnostic.
{
    return static_cast<int>(a - 5.F);
}

  inline int g(double) = delete;
//~~~~~~
//^ Deleted functions are implicitly inline

class C
{
  public:
    inline C& operator=(const C&) = delete;
//  ~~~~~~
//  ^ Deleted functions are implicitly inline.
    inline int Get42() const { return 42; }
//  ~~~~~~
//  ^ Functions defined inside the class are implicitly inline
    static constexpr inline int C_STATIC = 42;
//                   ~~~~~~
//                   ^ constexpr static members are implicitly inline 
};

constexpr inline int Get42() { return 42; }
//        ~~~~~~
//        ^ Constexpr functions are implicitly inline

static constexpr inline int NAMESPACE_STATIC = 42; // OK, constexpr static namespace scope variables are not implicitly inline

```

**Comment by firewave** [comment]
+1 Thanks for the research.

I was about to dig into this as well since JetBrains Rider/Clion Nova has an inspection which suggests to remove redundant `inline` specifiers and I was suspicious about some of the warnings.

Here's a few more cases off the top my head which need to be determined if it is necessary:
```
static inline int fn0(int i)
{
    return i - 1;
}

static constexpr inline int fn1(int i)
{
    return i - 1;
}

namespace
{
    inline int fn2(int i)
    {
        return i - 1;
    }

    constexpr inline int fn3(int i)
    {
        return i - 1;
    }
}

namespace ns
{
    inline int fn4(int i)
    {
        return i - 1;
    }

    constexpr inline int fn5(int i)
    {
        return i - 1;
    }
}
```

Rider suggests it is redundant in all cases but `fn4()` but I am not sure about that

There was page where you could post code and it would add all the stuff which is usually implicit. That would helpful in this case.

**Comment by FalcoGer** [comment]
> +1 Thanks for the research.

I would prefer if someone with more experience looked over this again though. I'm not an expert.

**Comment by firewave** [comment]
Found it: https://cppinsights.io/s/81025a0e

**Comment by firewave** [comment]
Here's all the cases combined: https://cppinsights.io/s/bbfcd25f.

**Comment by FalcoGer** [comment]
In the template case it's not implicit, but it's redundant.
As far as I can tell it doesn't do anything.

**Comment by firewave** [comment]
> In the template case it's not implicit, but it's redundant.

Those seem like important semantics to remember when a check is implemented.

**Comment by felix642** [comment]
I would be interested to work on this check unless someone else has already started.

**Comment by PiotrZSL** [comment]
Possible name: readability-redundant-inline-specifier

I had it done like this, but this does not cover all cases. Once you finish your check I will be finally able to remove my custom one.
```
- A function defined entirely inside a class/struct/union definition, whether it's a member function or a non-member friend function, is implicitly an inline function.
- A function declared constexpr is implicitly an inline function.
- A deleted function is implicitly an inline function: its (deleted) definition can appear in more than one translation unit.

void ReadabilityRedundantInlineSpecifierCheck::registerMatchers(MatchFinder *Finder) {
  Finder->addMatcher(functionDecl(unless(isExpansionInSystemHeader()),
                                  unless(isImplicit()),
                                  isInline(),
                                  anyOf(isConstexpr(),
                                        isDeleted(),
                                        allOf(isDefinition(),
                                              hasAncestor(recordDecl())))
   ).bind("fun"), this);
}

void ReadabilityRedundantInlineSpecifierCheck::check(const MatchFinder::MatchResult &Result) {
  const auto *MatchedDecl = Result.Nodes.getNodeAs<FunctionDecl>("fun");
  diag(MatchedDecl->getLocation(), "function %0 is already implicitly inlined, no need to inline explicitly")
      << MatchedDecl;
}

```

**Comment by firewave** [comment]
I filed a ticket with Rider about some of the warnings they produce being overzealous: https://youtrack.jetbrains.com/issue/CPP-36142.

In the discussion it came up there might be a difference of `inline` being "implicit" or "redundant". Maybe that is something to consider for this proposed check at all.

**Comment by firewave** [comment]
An argument for considering possibly differentiating "implicit" ones is #75234 which adds some explicit usage `ìnline` in the LLVM code base.

**Comment by ldionne** [comment]
Personally, I think writing `inline` explicitly on non-template free functions is a good thing, and the fact that `constexpr` implies `inline` is a mis-feature. Indeed, it means that you start having ODR violations if you take such a function and remove `constexpr` from it (e.g. a refactoring or the implementation changes). This just sounds really brittle, and I prefer annotating free functions that must be ODR-deduped as `inline` explicitly. This is just my preference and this is what we've been doing in libc++, but this is by no means the absolute truth.

**Comment by FalcoGer** [comment]
@PiotrZSL the quick fix deletes the redundant inline, but at least for me on nvim, it leaves a double space/a leading space. The quick fix should probably also delete the trailing whitespace.

This might need more consideration if it's a newline with a preceding keyword, but I'm sure there already is some code that does this correctly.

**Comment by felix642** [comment]
> @PiotrZSL the quick fix deletes the redundant inline, but at least for me on nvim, it leaves a double space/a leading space. The quick fix should probably also delete the trailing whitespace.
> 
> This might need more consideration if it's a newline with a preceding keyword, but I'm sure there already is some code that does this correctly.

@FalcoGer Clang-tidy is not responsible for the file's formatting. The trick that is used is to run `clang-format` on the lines around the fix to properly format the code. When running clang-tidy you can use the flag `--format-style` to let clang-tidy know how to format the lines that have been changed. 

I do not know exactly how the integration of clang-tidy works through neovim, but I assume that you should be able to do something similar.

https://clang.llvm.org/extra/clang-tidy/

**Comment by PiotrZSL** [comment]
@FalcoGer If after removal code still compiles, then everything is fine. Specially that this is first check release. We can deal with double spaces in next release. Main purpose of check is to detect such places of code, "fixing" is an bonus.

**Comment by felix642** [comment]
@chfast Yes, Clang will add an attribute if you use the inline keyword on a function.

This is the reason why this check has a parameter `StrictMode`. By default, this parameter is set to `false`, meaning that the check will only flag the inline specifier if it is already implicitly added by the compiler. This means that removing the inline specifier will not impact the generated assembly.

Only if you set the parameter to `true` will you notice some changes in the generated assembly. This is because the check will flag the `inline` keyword if the function/variable already has internal linkage, even if the compiler does not implicitly add the specifier.
