### ISSUE TITLE
Exceeding maximum file name length.

### ISSUE THREAD

**Issue by DrTodd13** [llvm/llvm-project#72453]
The code in include/llvm/Analysis/DOTGraphTraitsPass.h will exceed most normal file system's maximum filename length of 255 if, e.g., the function's name is that length.

**Comment by shahidiqbal13** [comment]
Hi @DrTodd13 ,
I would like to work on this , how to assign this ticket since **"Assignees"** button is not clickable at my side. Can you please help me to assign it

**Comment by DrTodd13** [comment]
@shahidiqbal13 Hi.  Github won't let me assign someone either.  It seems you need collaborator privileges on the repo in order to assign people.  Maybe an admin will see your comment and do the assignment but I suspect that if you just start working on this and solve it and make a PR that it will be fine.

**Comment by shahidiqbal13** [comment]
Hi Todd,

Thanks for your reply, I'm getting some git setup issue , seems I'm setting
same git configuration for work and personal git config on same machine i.e
on office's laptop, once I resolve it , will contribute

--Shahid

**Comment by shahidiqbal13** [comment]
Hi @dtcxzyw ,
Thanks for assigning it. I have already raised for review, pls review it, it seems ok, and we can merge as well. Here is the raised link https://github.com/llvm/llvm-project/pull/72654 , even you can add reviewers so that we could close it soon.

And I cannot assign any ticket to myself, Can you please tell me what to configure my side so that in future I could assign more tickets to myself.
Thanks
Shahid Iqbal

**Comment by dtcxzyw** [comment]
> And I cannot assign any ticket to myself, Can you please tell me what to configure my side so that in future I could assign more tickets to myself.

Only members of LLVM team can assign issues to someone.
See also https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access.
Welcome to the LLVM project!

**Comment by shahidiqbal13** [comment]
@EugeneZelenko / @dtcxzyw Can you pls add reviewers so that we could proceed and merge
--Shahid

**Comment by shahidiqbal13** [comment]
@EugeneZelenko @DrTodd13 @dtcxzyw who will approve the changes so that it could merge or if any further changes are required then please let me know to do

**Comment by shahidiqbal13** [comment]
Changes have been merged , https://github.com/llvm/llvm-project/pull/72654
