### ISSUE TITLE
Failed to dynamic_cast when compile with `-fvisibility=hidden -stdlib=libc++`

### ISSUE THREAD

**Issue by timxx** [llvm/llvm-project#72464]
It's very simple case:

Write two abstract classes in shared library, used the shared library in main program,  use `dynamic_cast` to cast the abstract class, it fails.

sdk.so
```C++

// sdk.h
#pragma once

#define SDK_EXPORT __attribute__((visibility("default")))

class ISDK {
public:
  virtual ~ISDK() {}
  virtual void foo() const = 0;
};

class ISDKV2 : public ISDK {
public:
  virtual void bar() = 0;
};

SDK_EXPORT ISDK *create_sdk();

// sdk.cpp

#include "sdk.h"
#include <iostream>

class SDKV2Impl : public ISDKV2 {
public:
  void foo() const { std::cout << "foo\n"; }
  void bar() { std::cout << "bar\n"; }
};

ISDK *create_sdk() { return new SDKV2Impl(); }
```

demo (links with sdk.so)
``` C++
#include "sdk.h"

#include <memory>

int main(int argc, char **argv) {
  std::unique_ptr<ISDK> sdk(create_sdk());
  ISDKV2 *v2 = dynamic_cast<ISDKV2 *>(sdk.get());
  if (v2) {
    v2->bar();
  } else {
    sdk->foo();
  }

  return 0;
}
```

In above example, it should prints `bar` but `foo` instead.

It's strange when removed the `-stdlib=libc++` flags, it works just fine. (GCC also works as expected).

If I add the `SDK_EXPORT` to the two abstract classes, it also works (or just use `-fvisibility-ms-compat` instead), but I don't want this way, it exports too many unwanted symbols (the vtable and typeinfo)

[bug.zip](https://github.com/llvm/llvm-project/files/13371442/bug.zip)
Extract the `bug.zip`, run with `cmake -DCMAKE_CXX_COMPILER=clang++` , build and run to reproduce the problem.

**Comment by philnik777** [comment]
If you want to do dynamic casting you have to export the symbols required for it. There is no way around that. Even if libstdc++ happens to do the thing you want in this case, there is no guarantee that it'll work in other cases. This is just a latent bug in your code.

**Comment by timxx** [comment]
But without symbol export for abstract class, the dynamic_cast also works for msvc :(

**Comment by timxx** [comment]
> If you want to do dynamic casting you have to export the symbols required for it. There is no way around that. Even if libstdc++ happens to do the thing you want in this case, there is no guarantee that it'll work in other cases. This is just a latent bug in your code.

But without symbol export for abstract class, the dynamic_cast also works for msvc :(

**Comment by philnik777** [comment]
I have no idea how things work on windows w.r.t. symbol visibility, so I don't know if that comparison makes any sense. I wouldn't be surprised if MSVC just makes the RTTI and vtable always available.

**Comment by ldionne** [comment]
Like @philnik777 said, `dynamic_cast` uses the typeinfo to do its work, so if you have duplicate definitions of the type information for a type (because it doesn't get deduplicated by the linker because you didn't export it), then the behavior you're seeing is expected. Other implementations are free to always do e.g. a typeid name comparison (which is likely what's happening with libstdc++), but that has downsides too (for example two unrelated classes with the same name will compare equal).

**Comment by timxx** [comment]
I found that use `-DLIBCXXABI_ENABLE_FORGIVING_DYNAMIC_CAST=ON` option to compile the libc++abi, it solves the problem.
