### ISSUE TITLE
[libc++abi] Incorrect adjustment of landing pad when LPStart is set to zero

### ISSUE THREAD

**Issue by maksfb** [llvm/llvm-project#72582]
When `LPStart` is set to 0, runtime should use the absolute value of the landing pad field while executing exception-handling code.

However, in `libc++abi` the following adjustment is done to `LPStart` here: https://github.com/llvm/llvm-project/blob/a9cc6fc28078de3e0391b477505c2d3d84f52e4b/libcxxabi/src/cxa_personality.cpp#L665-L666
and later this value is used to calculate the landing pad: https://github.com/llvm/llvm-project/blob/a9cc6fc28078de3e0391b477505c2d3d84f52e4b/libcxxabi/src/cxa_personality.cpp#L713
causing a control transfer to invalid address / landing pad.

Note that semantically omitting `LPStart` by using `DW_EH_PE_omit` encoding should be different from explicitly setting `LPStart` to zero.

Non-PIE binaries optimized by BOLT can fail when run with `libc++abi`: #72363

**Comment by ldionne** [comment]
Thanks for the report! It looks like this requires a specific setup to reproduce or we might have seen this happen in the wild before. I think providing a self-contained reproducer would go a long way to make it more likely that someone in the community is able to pick this up!

**Comment by maksfb** [comment]
#72363 has the reproducer. `llvm-bolt` can be built as part of LLVM if it's not available on your system. Any version will do.

In terms of why you don't see it in the wild: unlike the compiler, BOLT can place landing pads in different sections for better code separation based on profile data.

**Comment by zct** [comment]
Thanks for your detailed analysis, it seems to be a bug in the libc++abi;
Are there any temporary fixes in the libc++abi or bolt code that our local development environment can bypass
