### ISSUE TITLE
Improvement for relative load on x86

### ISSUE THREAD

**Issue by PiJoules** [llvm/llvm-project#72590]
LLVM will compile the following IR:

```
declare void @extern_func()

define void @foo(ptr noundef %a) local_unnamed_addr {
entry:
  %vtable = load ptr, ptr %a
  %func_ptr  = tail call ptr @llvm.load.relative.i32(ptr %vtable, i32 0)
  tail call void %func_ptr(ptr %a)
  tail call void @extern_func()
  ret void
}

declare ptr @llvm.load.relative.i32(ptr, i32)
```

into this
```
foo: 
        pushq   %rax
        movq    (%rdi), %rax
        movslq  (%rax), %rcx
        addq    %rax, %rcx
        callq   *%rcx
        popq    %rax
        jmp     extern_func@PLT                 # TAILCALL
```

These instructions
```
        addq    %rax, %rcx
        callq   *%rcx
```
can be simplified into
```
call *(%rax,%rcx)`
```
which saves 2 bytes per relative call. This particular pattern is seen for every virtual call with the relative vtables ABI for x86, so we can save roughly 2 bytes per callsite if we can teach llvm to lower to these instructions.

Note this isn't specific to the `llvm.load.relative` intrinsic. This intrinsic gets lowered to a `load + GEP`:
```
define void @foo(ptr noundef %a) local_unnamed_addr {
entry:
  %vtable = load ptr, ptr %a, align 8
  %0 = getelementptr i8, ptr %vtable, i32 0
  %1 = load i32, ptr %0, align 4
  %2 = getelementptr i8, ptr %vtable, i32 %1
  tail call void %2(ptr %a)
  tail call void @extern_func()
  ret void
}
```
but this still produces the same asm.

**Comment by topperc** [comment]
I think `call *(%rax,%rcx)` does a load from the address pointed to by %rax+%rcx and then address returned by that load? That's different than `call *%rcx` which just calls the address in %rcx.

**Comment by PiJoules** [comment]
> I think `call *(%rax,%rcx)` does a load from the address pointed to by %rax+%rcx and then calls the address returned by that load. That's different than `call *%rcx` which just calls the address in %rcx.

Ah, yeah you're right. Misunderstood the syntax.
