### ISSUE TITLE
[clang-tidy][this is a question]

### ISSUE THREAD

**Issue by DUAN-SS** [llvm/llvm-project#72608]
I want to omit checking some files by using.clang-tidy, but I can't seem to do that. Have you skipped checking some files or folders by configuring.clang-tidy now?

**Comment by mzyKi** [comment]
maybe you can edit .clang-tidy file to specify checkers like exclude files 'Checks: '-*'

**Comment by DUAN-SS** [comment]
I think 'check:'-*' is just for check list，if it is you, how would you configure this file?

**Comment by mzyKi** [comment]
Maybe you can describe your request clearly.I think you just want to analyze one project.
For example,this project has A,B,C,D folders.And you don't want to analyze files in D folder.
You can edit .clang-tidy file in D folder.
```file
Checks: '-*
```
But, I don't know the way you use clang-tidy.All above is my guess.

**Comment by DUAN-SS** [comment]
Thank you for your answer. Let me describe what I think. Let's say I have folders A,B,C and D, but I want to be able to configure.clang-tidy not to check one or some files in folder A.

**Comment by PiotrZSL** [comment]
If you using run-clang-tidy then most probably you may need to manually remove those files from .compile_commands.json.
If you using CMake, then I think you can do that somewhere there, by for example moving those files to separate library and then excluding that library.
You can also pass list of folder and files to run-clang-tidy and just omit those files.

**Comment by DUAN-SS** [comment]
These methods are feasible, but this is not very convenient, I would prefer to use the.clang-tidy file to solve this problem

**Comment by PiotrZSL** [comment]
Not possible. As .clang-tidy is generic config that work for entire folder, and if you do not put any checks there, then clang-tidy will fail.

**Comment by PiotrZSL** [comment]
What you could probably also do is simply wrap clang-tidy into some script, and do some checking in script.

**Comment by DUAN-SS** [comment]
The scripted approach is feasible

**Comment by DUAN-SS** [comment]
Can the -line-filter out some file checks?

**Comment by PiotrZSL** [comment]
--line-filter will filter issues from a file, not a files.
In that case file still will be checked.
If you cant just to filter issues, then you could use line-filter, or header-filter or even put //NOLINTBEGIN, //NOLINTEND into file

**Comment by DUAN-SS** [comment]
Well, thank you very much for your answer.
