### ISSUE TITLE
readability-container-size-empty improperly converts `c.size() < 0` to `c.empty()`

### ISSUE THREAD

**Issue by r-barnes** [llvm/llvm-project#72619]
Some objects can have a `size()` which returns negative values and also have an `empty()` method.

In this case, `size() < 0` is not the same thing as `empty()`.

Currently `readability-container-size-empty` converts `x.size() < 0` to `x.empty()` - this has caused some real problems for us was an unexpected behaviour that isn't made explicit in either the documentation or the code itself.

**Comment by chrchr-github** [comment]
~~~c++
using size_type = int;
//using size_type = unsigned;
struct S {
    bool empty() const;
    size_type size() const;
};

void f(const S& s) {
    if (s.size() < 0) {}
}
~~~
https://godbolt.org/z/8f9TKjo8r
The warning appears also for an unsigned type, where replacement with `empty()` is a bug.
