### ISSUE TITLE
`a <= abs(a)` is always true

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#72653]
Alive2 Proof: https://alive2.llvm.org/ce/z/XD9--h
Original program: https://godbolt.org/z/aT8v6G8e9

**Comment by k-arrows** [comment]
Other missed optimizations on `abs`
1. `abs(a) == a` --> `(a >= 0)`
2. `abs(a) == -a` --> `(a <= 0)`

Alive2 Proof: https://alive2.llvm.org/ce/z/UaEEkb
Original program: https://godbolt.org/z/3897dn6fT

**Comment by pinskia** [comment]
I filed the GCC bug report for the full set of comparisons:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=112626
