### ISSUE TITLE
mlir::DataLayout usage of unsigned is too small for applications with huge arrays

### ISSUE THREAD

**Issue by jeanPerier** [llvm/llvm-project#72678]
LLVM uses `llvm::TypeSize` which wraps a `uint64_t` in `llvm::DataLayout` ([here](https://github.com/llvm/llvm-project/blob/764c3afd43128f7ccddb070953c330b340ebe811/llvm/include/llvm/IR/DataLayout.h#L629)), but `mlir::DataLayout` uses `unsigned` ([here](https://github.com/llvm/llvm-project/blob/2310066faab21996a52513c5475552f0e28f0624/mlir/include/mlir/Interfaces/DataLayoutInterfaces.h#L37)).

This is problematic for the change request by llvm to flang to stop generating GEP to compute type size in constants (https://github.com/llvm/llvm-project/issues/71507).

Fortran sometimes has huge arrays with static size, and the size of some llvm.array types do not fit on an unsigned, so moving from GEP to using `mlir::DataLayout` causes bug with such programs.

Here is an example of bugs that can occur in MLIR transformation with big arrays (it is not what we are hitting with flang, but this is a simple MLIR illustration using only the LLVM dialect):

```
llvm.func @test_byval(%ptr : !llvm.ptr) {
  llvm.call @with_byval_arg(%ptr) : (!llvm.ptr) -> ()
  llvm.return
}

llvm.func @with_byval_arg(%ptr : !llvm.ptr { llvm.byval = !llvm.array<1000 x array<1000 x array <500 x i32>>> }) {
  llvm.return
}
``` 

Is translated by `mlir-opt -inline` to the following program where only `389 387 264` bytes are copied from an `!llvm.array<1000 x array<1000 x array <500 x i32>>>` instead of `2000 000 000` bytes:

```
llvm.func @test_byval(%arg0: !llvm.ptr) {
    %0 = llvm.mlir.constant(389387264 : i64) : i64
    %1 = llvm.mlir.constant(1 : i64) : i64
    %2 = llvm.alloca %1 x !llvm.array<1000 x array<1000 x array<500 x i32>>> {alignment = 4 : i64} : (i64) -> !llvm.ptr
    "llvm.intr.memcpy"(%2, %arg0, %0) <{isVolatile = false}> : (!llvm.ptr, !llvm.ptr, i64) -> ()
    llvm.return
  }
```

**Comment by ftynse** [comment]
#72874  updates the data layout and fixes the specific reported case, but wouldn't be sufficient for a case that actually overflows `unsigned` in the result. I suspect inlining may be using `unsigned` somewhere for size.

**Comment by ftynse** [comment]
#72878 is a proper fix.
