### ISSUE TITLE
[clang-cl] C++23 triggers pre C++17 warnings

### ISSUE THREAD

**Issue by tiagomacarios** [llvm/llvm-project#72716]
The following code when compiled in C++23 with clang-cl will trigger pre C++17 errors:
`using a = void(*)()noexcept;`

https://godbolt.org/z/3bxbb3n6x
```
<source>(1,20): error: exception specifications are not allowed in type aliases
    1 | using a = void(*)()noexcept;
      |      
```

I am seeing this error for the following diagnostics:
err_incompatible_exception_specs
warn_incompatible_exception_specs

**Comment by cor3ntin** [comment]
The driver does not recognize /std:C++23
https://godbolt.org/z/bzj6s8Gcq
