### ISSUE TITLE
Crash When Attempting to Install Packages on HPCC Environment

### ISSUE THREAD

**Issue by novalex98** [llvm/llvm-project#72731]
Hello,

I am attempting to install packages on the Hyak HPCC system (https://hyak.uw.edu/). 

Some packages installed successfully, but when it got to SimpleUnPack there was a crash, and a dump was produced (first attachment).
[JuliaPackageInstallCrashDump.txt](https://github.com/llvm/llvm-project/files/13398596/JuliaPackageInstallCrashDump.txt)

I searched online and found that i the past people have solved this problem by using JuliaUp to install Julia instead of installing it directly https://discourse.julialang.org/t/having-trouble-installing-differentialequations-jl/105217/5 

I tried this, and while Julia was installed successfully, this time no packages could be installed and the same dump was produced (second attachment). 
[JuliaPackageInstallCrashDump_2.txt](https://github.com/llvm/llvm-project/files/13398600/JuliaPackageInstallCrashDump_2.txt)

Please help me fix this problem. Happy to provide any additional information.

**Comment by asl** [comment]
Please report Julia issues to their bugtracker

**Comment by Keno** [comment]
For completeness, output here directing the user to file an issue here was from `lld`, not julia (though julia was invoking lld). Regardless, we'll take the investigation over on our issue tracker and move things back here should it turn out to in fact be an lld issue.
