### ISSUE TITLE
Wrong indentation after clang-format when it exists a label after if

### ISSUE THREAD

**Issue by Freed-Wu** [llvm/llvm-project#72739]
```c
#include <err.h>
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char *argv[]) {
  if (argc > 2)
    goto usage;
  if (argc < 2)
usage:
    errx(EXIT_FAILURE, "parse error");
  return EXIT_SUCCESS;
}
```

when I `clang-format test.c`, it will be

```c
#include <err.h>
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char *argv[]) {
  if (argc > 2)
    goto usage;
  if (argc < 2)
  usage:
    errx(EXIT_FAILURE, "parse error");
  return EXIT_SUCCESS;
}
```

It result in a waring:

> test.c:10 [clang-tidy readability-misleading-indentation] Warning Misleading indentation: statement is indented too deeply

**Comment by owenca** [comment]
Please use `IndentGotoLabels: false` if you don't want clang-format to indent `goto` labels.

**Comment by owenca** [comment]
@PiotrZSL Can the clang-tidy warning be suppressed?

**Comment by Freed-Wu** [comment]
It is weird because:

```c
#include <err.h>
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char *argv[]) {
label:
  if (argc > 2)
    goto usage;
  if (argc < 2)
usage:
    errx(EXIT_FAILURE, "parse error");
  return EXIT_SUCCESS;
}
```

After `clang-format`, `label:` will not be indented, `usage:` will be indented and result in this weird warning. What is the reason?

**Comment by owenca** [comment]
The default indentation for goto labels is the enclosing scope, so this is not a clang-format issue. IMO, clang-tidy should not warn because goto labels are not statements.

**Comment by PiotrZSL** [comment]
> @PiotrZSL Can the clang-tidy warning be suppressed?

//NOLINT(readability-misleading-indentation)

**Comment by PiotrZSL** [comment]
And duplicate of #68823
