### ISSUE TITLE
[clang] libc++ lib dir not added to search dirs in Debian distributions

### ISSUE THREAD

**Issue by jdoubleu** [llvm/llvm-project#72753]
_NOTE: This might only apply to the binaries included in the Debian apt packages._

When installing clang (17) through the Debian apt packages, clang picks GCC's `libstdc++` by default. One can manually add `-stdlib=libc++` to link against LLVM's `libc++`. Some newer C++ (23) features [require the `-fexperimental-library` flag](https://libcxx.llvm.org/UsingLibcxx.html#enabling-experimental-c-library-features).

However, clang fails to build (link) any programs linking again `libc++` and using `-fexperimental-library` , because it cannot find `libc++experimental`. That is because clang doesn't include the lib dir of `libc++`, which is at `/usr/lib/llvm-17/lib` (provided by the `libc++-17-dev` apt package).
```sh
$ dpkg -L libc++-17-dev | grep c++experimental
/usr/lib/llvm-17/lib/libc++experimental.a

$ clang++-17 -print-search-dirs
programs: =/usr/bin:/usr/lib/llvm-17/bin:/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/bin
libraries: =/usr/lib/llvm-17/lib/clang/17:/usr/bin/../lib/gcc/x86_64-linux-gnu/12:/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../lib64:/lib/x86_64-linux-gnu:/lib/../lib64:/usr/lib/x86_64-linux-gnu:/usr/lib/../lib64:/lib:/usr/lib
```

Try to run the following commands to build the C++ program:
```sh
$ cat <<CXX > test.cpp
#include <iostream>
#include <format>

int main()
{
        std::cout << std::format("Hello C++23\n");
}
CXX

$ clang++-17 -std=c++2b -stdlib=libc++ -fexperimental-library -v test.cpp
Debian clang version 17.0.4 (++20231031083102+309d55140c46-1~exp1~20231031083155.63)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/lib/llvm-17/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all -dumpdir a- -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -v -fcoverage-compilation-dir=/mnt/c/Users/jdoubleu/Downloads -resource-dir /usr/lib/llvm-17/lib/clang/17 -internal-isystem /usr/lib/llvm-17/bin/../include/c++/v1 -internal-isystem /usr/lib/llvm-17/lib/clang/17/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++2b -fdeprecated-macro -fdebug-compilation-dir=/mnt/c/Users/jdoubleu/Downloads -fexperimental-library -ferror-limit 19 -fgnuc-version=4.2.1 -fno-implicit-modules -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/test-84b580.o -x c++ test.cpp
clang -cc1 version 17.0.4 based upon LLVM 17.0.4 default target x86_64-pc-linux-gnu
ignoring nonexistent directory "/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/llvm-17/bin/../include/c++/v1
 /usr/lib/llvm-17/lib/clang/17/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
 "/usr/bin/ld" -pie --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out /lib/x86_64-linux-gnu/Scrt1.o /lib/x86_64-linux-gnu/crti.o /usr/bin/../lib/gcc/x86_64-linux-gnu/12/crtbeginS.o -L/usr/bin/../lib/gcc/x86_64-linux-gnu/12 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/lib -L/usr/lib /tmp/test-84b580.o -lc++ -lc++experimental -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/bin/../lib/gcc/x86_64-linux-gnu/12/crtendS.o /lib/x86_64-linux-gnu/crtn.o
/usr/bin/ld: cannot find -lc++experimental: No such file or directory
clang++-17: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Workaround
In order to fix the build, I'd have to manually provide the `-L/usr/lib/llvm-17/lib` option.

I think that path should be included by default, shouldn't it?

**Comment by ldionne** [comment]
@jdoubleu Can you let us know where Clang is finding `libc++.so` on your system? My expectation is that `libc++experimental.a` and `libc++.so` would be in the same directory.

**Comment by ldionne** [comment]
I *think* this is the apt package being set up incorrectly. @tstellar @tru Do you know who maintains the LLVM apt packages? Do we have any special logic for creating symlinks as above for `libc++.so`? If we do, I think we need to add the same for `libc++experimental.a`.

**Comment by jdoubleu** [comment]
I'm not sure if it's sustainable to just add symlinks to a few selected libraries, because then you might forget to add future libs as well?

Possible missing _links_ to libs in `/usr/lib/llvm-17/lib/`:
```
libc++experimental.a
libLTO.so
libRemarks.so
libunwind.a
libunwind.so
```

**Comment by tru** [comment]
Cc @sylvestre

**Comment by ldionne** [comment]
Actually, where do you get your unwinder from? IIUC you're not using `libunwind.so` shipped by LLVM then?

**Comment by jdoubleu** [comment]
Should have checked before; `libunwind` is also a symlink and provided by the `libunwind-17-dev` package. The other libs mentioned above aren't, though. I'm not sure if they're even required for a "normal" build or during runtime.

**Comment by sylvestre** [comment]
yeah, I will fix it

**Comment by ldionne** [comment]
Just out of curiosity, where does this need to be fixed? I'd love to understand where this lives in case reports like this one happen in the future.

**Comment by sylvestre** [comment]
@ldionne here: https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/
it uses branches

It should be fixed by this one:
 https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/commit/4e522af7c850c49aa9122405fa7d8159d11da94f 


For some reason, with clang-16 -v, i see `-L/usr/lib/llvm-16/bin/../lib` in:

 "/usr/bin/ld" -pie --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out /lib/x86_64-linux-gnu/Scrt1.o /lib/x86_64-linux-gnu/crti.o /usr/bin/../lib/gcc/x86_64-linux-gnu/13/crtbeginS.o -L/usr/bin/../lib/gcc/x86_64-linux-gnu/13 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 **-L/usr/lib/llvm-16/bin/../lib** -L/lib -L/usr/lib /tmp/test-b0dcaf.o -lc++ -lc++experimental -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/bin/../lib/gcc/x86_64-linux-gnu/13/crtendS.o /lib/x86_64-linux-gnu/crtn.o


but it isn't added automatically with clang-17. Not sure why it isn't anymore

**Comment by ldionne** [comment]
Thank you! I guess this can be closed then?

**Comment by sylvestre** [comment]
well, it didn't build yet :)

**Comment by doko42** [comment]
I don't think this is the correct solution. I opened
https://github.com/llvm/llvm-project/issues/73244

this seems to be an unplanned change to the driver, dropping the -L option.
