### ISSUE TITLE
One value has two types

### ISSUE THREAD

**Issue by kelbon** [llvm/llvm-project#72752]
https://godbolt.org/z/Yh3aEb8Kh

I know, there are standard issue with type of 'j' in lambda, but current behavior is completelly incorrect

```cpp


#include <type_traits>

int main()
{
  int i, &j = i;
  [=]
  {
    static_assert(std::is_same_v<decltype(j), int&>
     && std::is_same_v<decltype((((j)))),const int&>);
  }();
}

```

**Comment by DimitryAndric** [comment]
Any particular reason for the obfuscation with multiple parentheses in `decltype((((j))))` ? If I remove that, you get the expected static assertion, e.g. with clang (and libc++) 17.0.5:

```
$ clang++ -std=c++17 -c pr72752.cpp
pr72752.cpp:9:9: error: static assertion failed due to requirement 'std::is_same_v<int &, const int &>'
    9 |      && std::is_same_v<decltype(j),const int&>);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

So it seems adding at least one pair of superfluous parentheses makes the static assertion go away. There is definitely something fishy going on there...

**Comment by kelbon** [comment]
> So it seems adding at least one pair of superfluous parentheses makes the static assertion go away. There is definitely something fishy going on there...

decltype for values and expressions are not same, () creates a expression from value, but how it can add 'const'?

**Comment by cpplearner** [comment]
But the expression `j` really is const within the lambda.

```c++
#include <type_traits>

int main()
{
  int i, &j = i;
  [=]
  {
    j = 1; // error: cannot assign to a variable captured by copy in a non-mutable lambda
  }();
}
```

**Comment by kelbon** [comment]
> But the expression `j` really is const within the lambda.
> 
> ```c++
> #include <type_traits>
> 
> int main()
> {
>   int i, &j = i;
>   [=]
>   {
>     j = 1; // error: cannot assign to a variable captured by copy in a non-mutable lambda
>   }();
> }
> ```

Then why
1. decltype(j) == int&
2. Its just incorrect behavior on standard layer, reference is not part of lambda, 
```cpp
struct X {
int& ref;
};
...
const X x{i);
x.ref = 10; // works

```
3. gcc thinks its mutable(its correct)

**Comment by cor3ntin** [comment]
This is the expected behavior 
https://eel.is/c++draft/expr.prim.id#unqual-example-1

`decltype(j)` denotes an id-expression in an unevaluated context and will therefore refer to the not-captured `j` variable - which is not const.
`decltype((j))` is the type of the expression `(j)`  _inside the lambda_ - and because the lambda is constm this will be const tool.

I know it's slightly confusing, but it is conforming.
