### ISSUE TITLE
[mlir] Should `getAttributeNames` crash or return a `nullptr` when a dialect is not loaded

### ISSUE THREAD

**Issue by rikhuijzer** [llvm/llvm-project#72900]
This came up during https://github.com/llvm/llvm-project/pull/72801. There `getAttributeNames()` returned an empty list of attribute names for `FuncOp` when the `func` dialect was not loaded even though `FuncOp` has multiple attributes (and, hence, attribute names). Maybe it would be better to crash in such a situation or return a `nullptr` so that clients can easily see why calls to `getAttributeNames()` or functions which depend on that (e.g., `getFunctionTypeAttrName`) fail?

**Comment by joker-eph** [comment]
I don't quite follow, here is the implementation:

```
class FuncOp : public ::mlir::Op<FuncOp, ::mlir::OpTrait::OneRegion, ::mlir::OpTrait::ZeroResults, ::mlir::OpTrait::ZeroSuccessors, ::mlir::OpTrait::ZeroOperands, ::mlir::OpTrait::OpInvariants, ::mlir::BytecodeOpInterface::Trait, ::mlir::OpTrait::AffineScope, ::mlir::OpTrait::AutomaticAllocationScope, ::mlir::SymbolOpInterface::Trait, ::mlir::CallableOpInterface::Trait, ::mlir::FunctionOpInterface::Trait, ::mlir::OpTrait::IsIsolatedFromAbove, ::mlir::OpAsmOpInterface::Trait> {
public:
  using Op::Op;
  using Op::print;
  using Adaptor = FuncOpAdaptor;
  template <typename RangeT>
  using GenericAdaptor = FuncOpGenericAdaptor<RangeT>;
  using FoldAdaptor = GenericAdaptor<::llvm::ArrayRef<::mlir::Attribute>>;
  using Properties = FoldAdaptor::Properties;

  static ::llvm::ArrayRef<::llvm::StringRef> getAttributeNames() {
    static ::llvm::StringRef attrNames[] = {::llvm::StringRef("arg_attrs"), ::llvm::StringRef("function_type"), ::llvm::StringRef("res_attrs"), ::llvm::StringRef("sym_name"), ::llvm::StringRef("sym_visibility")};
    return ::llvm::ArrayRef(attrNames);
  }
```

**Comment by rikhuijzer** [comment]
You're right. `getAttributeNames()` is not the problem in general. What I meant to say was that `getFunctionTypeAttrName()` and other attribute name functions can crash when a dialect is not registered.

Specifically, there are multiple _get attribute name_ functions created by `mlir-tblgen` in `mlir/tools/mlir-tblgen/OpDefinitionsGen.cpp`:

```cpp
  // Generate the <attr>AttrName methods, that expose the attribute names to
  // users.
  const char *attrNameMethodBody = "  return getAttributeNameForIndex({0});";
  for (auto [index, attr] :
       llvm::enumerate(llvm::make_first_range(attributes))) {
    std::string name = op.getGetterName(attr);
    std::string methodName = name + "AttrName";

    // Generate the non-static variant.
    {
      auto *method = opClass.addInlineMethod("::mlir::StringAttr", methodName);
      ERROR_IF_PRUNED(method, methodName, op);
      method->body() << llvm::formatv(attrNameMethodBody, index);
    }

    // Generate the static variant.
    {
      auto *method = opClass.addStaticInlineMethod(
          "::mlir::StringAttr", methodName,
          MethodParameter("::mlir::OperationName", "name"));
      ERROR_IF_PRUNED(method, methodName, op);
      method->body() << llvm::formatv(attrNameMethodBody,
                                      "name, " + Twine(index));
    }
  }
```

For people unfamiliar with this, these generated functions allow accessing the attributes for an operation. For example, `FuncOp` defines the following `arguments` in `mlir/include/mlir/Dialect/Func/IR/FuncOps.td`:

```td
  let arguments = (ins SymbolNameAttr:$sym_name,
                       TypeAttrOf<FunctionType>:$function_type,
                       OptionalAttr<StrAttr>:$sym_visibility,
                       OptionalAttr<DictArrayAttr>:$arg_attrs,
                       OptionalAttr<DictArrayAttr>:$res_attrs);
```

So, `getFunctionTypeAttrName()` returns an "function_type" as a `StringAttr` and note that `StringAttr` contains a `MLIRContext` object.

This is used in many places throughout the MLIR codebase and in multiple `mlir/examples`. Usually in the following form, like used inside `mlir/lib/Dialect/Func/IR/FuncOps.cpp`:

```cpp
state.addAttribute(getFunctionTypeAttrName(state.name), TypeAttr::get(type));
```

where `state.name` is an `OperationName`. An `OperationName` provides access to the attribute names via

```cpp
    ArrayRef<StringAttr> getAttributeNames() const { return attributeNames; }
```
in `mlir/include/mlir/IR/OperationSupport.h`.

However, if I'm not mistaken then `attributeNames` can be an empty list here when a operation is not registered.

This is what is called by the generated functions. From `tools/mlir/include/mlir/Dialect/Func/IR/FuncOps.h.inc`.

```h
  ::mlir::StringAttr getFunctionTypeAttrName() {
    return getAttributeNameForIndex(1);
  }

  static ::mlir::StringAttr getFunctionTypeAttrName(::mlir::OperationName name) {
    return getAttributeNameForIndex(name, 1);
  }
```

So, during `FuncOp::build` we have to call the latter of these two since we can only access static functions at that point. This `getAttributeNameForIndex(name, 1)` will call one of the functions that is generated in `mlir/tools/mlir-tblgen/OpDefinitionsGen.cpp`:

```cpp
  // Emit the getAttributeNameForIndex methods.
  {
    auto *method = opClass.addInlineMethod<Method::Private>(
        "::mlir::StringAttr", "getAttributeNameForIndex",
        MethodParameter("unsigned", "index"));
    ERROR_IF_PRUNED(method, "getAttributeNameForIndex", op);
    method->body()
        << "  return getAttributeNameForIndex((*this)->getName(), index);";
  }
  {
    auto *method = opClass.addStaticInlineMethod<Method::Private>(
        "::mlir::StringAttr", "getAttributeNameForIndex",
        MethodParameter("::mlir::OperationName", "name"),
        MethodParameter("unsigned", "index"));
    ERROR_IF_PRUNED(method, "getAttributeNameForIndex", op);

    if (attributes.empty()) {
      method->body() << "  return {};";
    } else {
      const char *const getAttrName = R"(
  assert(index < {0} && "invalid attribute index");
  assert(name.getStringRef() == getOperationName() && "invalid operation name");
  assert(name.isRegistered() && "Operation isn't registered, missing a "
        "dependent dialect loading?");
  return name.getAttributeNames()[index];
)";
      method->body() << formatv(getAttrName, attributes.size());
    }
  }
```
which generated the following in `tools/mlir/include/mlir/Dialect/Func/IR/FuncOps.h.inc`:

```h
  static ::mlir::StringAttr getAttributeNameForIndex(::mlir::OperationName name, unsigned index) {
    assert(index < 5 && "invalid attribute index");
    assert(name.getStringRef() == getOperationName() && "invalid operation name");
    assert(name.isRegistered() && "Operation isn't registered, missing a "
          "dependent dialect loading?");
    return name.getAttributeNames()[index];
  }
```

And this is where the program crashed in https://github.com/llvm/llvm-project/issues/71281 with 
```
Assertion `Index < Length && "Invalid index!"' failed.
```
which points to the fact that `name.getAttributeNames()` was empty in `return name.getAttributeNames()[index];`

In https://github.com/llvm/llvm-project/pull/72801 @matthias-springer wondered whether there is a better fix for this than to assert `name.isRegistered()` inside `getAttributeNameForIndex`. The assertion `name.isRegistered()` already clarifies crashes on
```cpp
state.addAttribute(getFunctionTypeAttrName(state.name), TypeAttr::get(type));
```
which something that clients will use, but maybe there is an even better place for the assertion.

**Comment by joker-eph** [comment]
I don't see the point of trying to "fix this" here: the FuncOp creation will assert just later. Here we ended up crashing before the creation of the op, because this particular method tried to use the `getFunctionTypeAttrName()` function during construction. But we'd have hit a runtime failure shortly after (with a clear error message).
