### ISSUE TITLE
[lldb] Assertion Crash when evaluating structures with bases with non-natural alignment

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#72913]
A small source code:

```
#include <coroutine>
#include <cstddef>


struct alignas(std::max_align_t) promise_base {
 int count = 0;
};

struct task{
  struct promise_type : promise_base {
    task get_return_object() { return std::coroutine_handle<promise_type>::from_promise(*this); }
    std::suspend_always initial_suspend() { return {}; }
    std::suspend_always final_suspend() noexcept { return {}; }
    void return_void() noexcept {}
    void unhandled_exception() noexcept {}
    
    int b;
  };

  void resume() noexcept {
    handle.resume();
  }

  task(std::coroutine_handle<promise_type> hdl) : handle(hdl) {}
  ~task() {
    if (handle)
      handle.destroy();
  }

  std::coroutine_handle<> handle;
};

 task coro_task(int v) {
  int a = v;
  __builtin_debugtrap();
  co_return;
}

int main() {
  auto k = coro_task(1);
  k.resume();
  return 0;
}
```

Reproduce steps:

```
$ ./bin/clang++ -std=c++20 -g /tmp/t.cpp -o /tmp/debugging-example
$ ./bin/lldb --one-line "run" --one-line "expr __promise" /tmp/debugging-example    
```

We hit an assertion, stack trace:

```
assert.h assertion failed at llvm-project/clang/lib/CodeGen/CGRecordLayoutBuilder.cpp:754 in void (anonymous namespace)::CGRecordLowering::clipTailPadding(): Prior->Kind == MemberInfo::Field && "Only storage fields have tail padding!"
*** Check failure stack trace: ***
    @   absl::log_internal::LogMessage::SendToLog()
    @   absl::log_internal::LogMessage::Flush()
    @   absl::log_internal::LogMessageFatal::~LogMessageFatal()
    @   __assert_fail
    @   (anonymous namespace)::CGRecordLowering::lower()
    @   clang::CodeGen::CodeGenTypes::ComputeRecordLayout()
    @   clang::CodeGen::CodeGenTypes::ConvertRecordDeclType()
    @   clang::CodeGen::CodeGenTypes::ConvertType()
    @   clang::CodeGen::CodeGenTypes::ConvertTypeForMem()
    @   clang::CodeGen::CodeGenFunction::EmitLoadOfReference()
    @   clang::CodeGen::CodeGenFunction::EmitLoadOfReferenceLValue()
    @   clang::CodeGen::CodeGenFunction::EmitDeclRefLValue()
    @   clang::CodeGen::CodeGenFunction::EmitLValueHelper()
    @   clang::CodeGen::CodeGenFunction::EmitLValue()
    @   (anonymous namespace)::ScalarExprEmitter::VisitUnaryAddrOf()
    @   clang::StmtVisitorBase<>::Visit()
    @   clang::CodeGen::CodeGenFunction::EmitScalarExpr()
    @   clang::CodeGen::CodeGenFunction::EmitScalarInit()
    @   clang::CodeGen::CodeGenFunction::EmitCXXGlobalVarDeclInit()
    @   (anonymous namespace)::ItaniumCXXABI::EmitGuardedInit()
    @   clang::CodeGen::CodeGenFunction::AddInitializerToStaticVarDecl()
    @   clang::CodeGen::CodeGenFunction::EmitStaticVarDecl()
    @   clang::CodeGen::CodeGenFunction::EmitDecl()
    @   clang::CodeGen::CodeGenFunction::EmitDeclStmt()
    @   clang::CodeGen::CodeGenFunction::EmitSimpleStmt()
    @   clang::CodeGen::CodeGenFunction::EmitStmt()
    @   clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope()
    @   clang::CodeGen::CodeGenFunction::GenerateCode()
    @   clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition()
    @   clang::CodeGen::CodeGenModule::EmitGlobalDefinition()
    @   clang::CodeGen::CodeGenModule::EmitGlobal()
    @   clang::CodeGen::CodeGenModule::EmitTopLevelDecl()
    @   (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl()
    @   lldb_private::ASTResultSynthesizer::HandleTopLevelDecl()
    @   clang::ParseAST()
    @   lldb_private::ClangExpressionParser::ParseInternal()
    @   lldb_private::ClangUserExpression::TryParse()
    @   lldb_private::ClangUserExpression::Parse()
    @   lldb_private::UserExpression::Evaluate()
    @   lldb_private::Target::EvaluateExpression()
    @   lldb_private::CommandObjectExpression::EvaluateExpression()
    @   lldb_private::CommandObjectExpression::DoExecute()
    @   lldb_private::CommandObjectRaw::Execute()
    @   lldb_private::CommandInterpreter::HandleCommand()
    @   lldb_private::CommandInterpreter::IOHandlerInputComplete()
    @   lldb_private::IOHandlerEditline::Run()
    @   lldb_private::Debugger::RunIOHandlers()
    @   lldb_private::CommandInterpreter::RunCommandInterpreter()
    @   lldb::SBDebugger::RunCommandInterpreter()
    @   Driver::MainLoop()
    @   main
    @   __libc_start_main
    @   _start
PLEASE submit a bug report to http://go/llvm-crash-bug and include the crash backtrace.
Stack dump:
0.      Program arguments: llvm/llvm-project/lldb/lldb /tmp/debugging-example --one-line run --one-line "expr __promise" /tmp/debugging-example
1.      HandleCommand(command = "expr __promise")
2.      <eof> parser at end of file
3.      <lldb wrapper prefix>:43:1: Generating code for declaration '$__lldb_expr'
```

**Comment by vogelsgesang** [comment]
#58397 is probably related. The pretty printer in lldb assumes that the promise is at a fixed offset of 16, as mandated by the ABI. But afaik, clang does not follow the ABI when generating code, yet

**Comment by Michael137** [comment]
FWIW, this crashes for me even without the `alignas`. It reminds me of what could happen if we didn't skip the artificial ptr member when parsing DWARF

**Comment by Michael137** [comment]
Doesn't seem coroutine related.

This also crashes:
```
struct alignas(std::max_align_t) promise_base {
    int count = 0;                             
};                                             
                                               
struct promise_type : promise_base {           
    int b;                                     
};                                             
                                               
int main() {                                   
    promise_type p;                            
    __builtin_debugtrap();  // expr p                
    return 0;                                  
}                                            
```

So it seems LLDB doesn't handle evaluating structures with bases that have manually-specified alignment

**Comment by hokein** [comment]
Thanks for the helpful comments. @vogelsgesang, @Michael137 

Yes, this is irrelevant to coroutines (removed the wrong label).

I think it is unlikely a bug in clang's codeGen backend. My hypothesis is that the alignment information is somehow messed up when lldb builds the AST node `RecordDecl`. I will take a further look.

**Comment by Michael137** [comment]
Clang attaches `DW_AT_alignment` to `bar` in my example, but LLDB doesn't ever actually use this. The fix is probably to parse said attribute and make sure we bubble it up to `ExternalASTSource::layoutRecordType` when the `ItaniumRecordLayoutBuilder` asks for it. We may have to attach `clang::AlignedAttr` to the decl we create for `bar`, but not sure

**Comment by hokein** [comment]
Confirmed that the layout of the `RecordDecl bar` built in the lldb is wrong. The layout dump is
```
 0 | struct bar
 0 |   int count
   | [sizeof=8, dsize=8, align=4,
   |  nvsize=8, nvalign=4]
```

while a correct one emitted by clang is 

```
  0 | struct bar
  0 |   int count
    | [sizeof=8, dsize=4, align=8,
    |  nvsize=4, nvalign=8]
```

> Clang attaches DW_AT_alignment to bar in my example, but LLDB doesn't ever actually use this. The fix is probably to parse said attribute and make sure we bubble it up to ExternalASTSource::layoutRecordType when the ItaniumRecordLayoutBuilder asks for it. We may have to also attach clang::AlignedAttr to the decl we create for bar, but not sure

Thanks! This makes sense, will try to prepare a fix.

**Comment by Michael137** [comment]
Something I noticed that makes this trickier is that `RecordDecl::isTrivial()` returns `true` for `bar` when using LLDBs AST. Whereas with clang it's actually `false`. This is important for `mustSkipTailPadding`, to determine whether to round up the size to alignment or not. So that's a separate bug that needs fixing first

**Comment by Michael137** [comment]
> Something I noticed that makes this trickier is that `RecordDecl::isTrivial()` returns `true` for `bar` when using LLDBs AST. Whereas with clang it's actually `false` (which is correct because `bar` has a default member initialiser, making the default constructor non-trivial).

Don't actually see a good way of fixing this with the current DWARF output. We need to set the `FieldDecl::StorageKind` to `ICIS_CopyInit`, which LLDB can't know because it's not spelled out in DWARF anywhere. So we'd have to come up with some way to get that info into DWARF first.

**Comment by hokein** [comment]
> Something I noticed that makes this trickier is that RecordDecl::isTrivial() returns true for bar when using LLDBs AST. Whereas with clang it's actually false (which is correct because bar has a default member initialiser, making the default constructor non-trivial). This is important for mustSkipTailPadding, to determine whether to round up the size to alignment or not. So that's a separate bug that needs fixing first

Good catch! I didn't pay attention to other fields. This looks like two separate bugs in lldb, they don't have a hard dependency. Fixing the original alignment issue can still make some cases work, which is better than current situation.
  
> Don't actually see a good way of fixing this with the current DWARF output. We need to set the FieldDecl::StorageKind to ICIS_CopyInit, which LLDB can't know because it's not spelled out in DWARF anywhere. So we'd have to come up with some way to get that info into DWARF first. Couldn't find an existing attribute that's supposed to give us that info

Thanks for taking a look at this. Since we're mostly interested in whether a `RecordDecl` is trivial, is there an `trivial-like` attribute for `DW_TAG_structure_type` tag? I didn't find any related attribute from a quick search. If none of these attribute exist, would it be possible to implement an extension?

**Comment by Michael137** [comment]
> Good catch! I didn't pay attention to other fields. This looks like two separate bugs in lldb, they don't have a hard dependency. Fixing the original alignment issue can still make some cases work, which is better than current situation.

Agreed. Fixing the alignment problem might be tricky because LLDB authoritatively tells clang about all the field/base offsets (see `ExternalASTSource::layoutRecordType`). So if a base class has a stricter alignment than the derived class, we'd have to make sure we reflect that in the layout calculations.

> > Don't actually see a good way of fixing this with the current DWARF output. We need to set the FieldDecl::StorageKind to ICIS_CopyInit, which LLDB can't know because it's not spelled out in DWARF anywhere. So we'd have to come up with some way to get that info into DWARF first. Couldn't find an existing attribute that's supposed to give us that info
> 
> Thanks for taking a look at this. Since we're mostly interested in whether a `RecordDecl` is trivial, is there an `trivial-like` attribute for `DW_TAG_structure_type` tag? I didn't find any related attribute from a quick search. If none of these attribute exist, would it be possible to implement an extension?

Perhaps @dwblaikie @adrian-prantl are aware attributes/past DWARF proposals that represent this. If motivation is compelling enough an attribute would be easy to add

**Comment by hokein** [comment]
> Fixing the alignment problem might be tricky because LLDB authoritatively tells clang about all the field/base offsets (see ExternalASTSource::layoutRecordType). So if a base class has a stricter alignment than the derived class, we'd have to make sure we reflect that in the layout calculations.

Yea, the alignment issue is trickier if we consider all inheritance (base/virtual base) cases. I don't think we would like to re-implement the layout calculation in LLDB. 
One approach I think of is that we can emit `DW_AT_alignment` attribute for the derived classes (in your above case, that's `foo`)  -- when clang emits debug information, we should know the exact alignment. What do you think?

**Comment by hokein** [comment]
> > > Don't actually see a good way of fixing this with the current DWARF output. We need to set the FieldDecl::StorageKind to ICIS_CopyInit, which LLDB can't know because it's not spelled out in DWARF anywhere. So we'd have to come up with some way to get that info into DWARF first. Couldn't find an existing attribute that's supposed to give us that info
> >
> > Thanks for taking a look at this. Since we're mostly interested in whether a RecordDecl is trivial, is there an trivial-like attribute for DW_TAG_structure_type tag? I didn't find any related attribute from a quick search. If none of these attribute exist, would it be possible to implement an extension?
> 
> Perhaps @dwblaikie @adrian-prantl are aware attributes/past DWARF proposals that represent this. If motivation is compelling enough, such attribute would be easy to add

This appears to be an implementation issue specific to lldb, not sure gdb will encounter similar issues. If it is lldb-specific, it may not be meaningful to add new attributes to DWARF.

**Comment by Michael137** [comment]
> Thanks for taking a look at this. Since we're mostly interested in whether a `RecordDecl` is trivial, is there an `trivial-like` attribute for `DW_TAG_structure_type` tag? I didn't find any related attribute from a quick search. If none of these attribute exist, would it be possible to implement an extension?

Also, I don't think marking the structure as `trivial` would be enough, because `RecordDecl::isTrivial` actually checks `hasTrivialDefaultConstructor` (which could either be implicit or declared). So I think the most obvious way would be an attribute on DW_TAG_structure_type that would tell us that we have default constructor. But maybe there are cleverer ways of deducing this

**Comment by hokein** [comment]
> > Yeah, the alignment issue is trickier if we consider all inheritance (base/virtual base) cases. I don't think we would like to re-implement the layout calculation in LLDB. One approach I think of is that we can emit DW_AT_alignment attribute for the derived classes (in your above case, that's foo) -- when clang emits debug information, we should know the exact alignment. What do you think?
> 
> I think that would make sense

After taking a closer look, this is a regression caused by the https://reviews.llvm.org/D24426. After that change, clang emits `align` in the debug info only when the `alignment` attr is explicit (`alignas()`, `_Alignas()`, `__attribute(aligned (N))` etc). However, the "transitive" case is not covered, e.g.

```
// !11 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "base", file: !7, line: 3, size: 64, align: 64, flags: DIFlagTypePassByValue, elements: !12, identifier: "_ZTS4base")
class alias(8) base {};

// !8 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "derived", file: !7, line: 5, size: 64, flags: DIFlagTypePassByValue, elements: !9, identifier: "_ZTS7derived")
class derived : base {};
```

I guess the motivation of  https://reviews.llvm.org/D24426 is to reduce the debug info size. One fix is to tweak the `getTypeAlignIfRequired`-family functions in `CGDebugInfo.cpp` to include missing cases (for the inheritance case here, we could traverse all base class decl, and see whether any of them is `isAlignRequired`), but it feels brittle. cc @dblaikie, @rnk who reviewed the patch.

**Comment by Michael137** [comment]
> > > Yeah, the alignment issue is trickier if we consider all inheritance (base/virtual base) cases. I don't think we would like to re-implement the layout calculation in LLDB. One approach I think of is that we can emit DW_AT_alignment attribute for the derived classes (in your above case, that's foo) -- when clang emits debug information, we should know the exact alignment. What do you think?
> > 
> > 
> > I think that would make sense
> 
> After taking a closer look, this is a regression caused by the https://reviews.llvm.org/D24426. After that change, clang emits `align` in the debug info only when the `alignment` attr is explicit (`alignas()`, `_Alignas()`, `__attribute(aligned (N))` etc). However, the "transitive" case is not covered, e.g.
> 
> ```
> // !11 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "base", file: !7, line: 3, size: 64, align: 64, flags: DIFlagTypePassByValue, elements: !12, identifier: "_ZTS4base")
> class alias(8) base {};
> 
> // !8 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "derived", file: !7, line: 5, size: 64, flags: DIFlagTypePassByValue, elements: !9, identifier: "_ZTS7derived")
> class derived : base {};
> ```
> 
> I guess the motivation of https://reviews.llvm.org/D24426 is to reduce the debug info size. One fix is to tweak the `getTypeAlignIfRequired`-family functions in `CGDebugInfo.cpp` to include missing cases (for the inheritance case here, we could traverse all base class decl, and see whether any of them is `isAlignRequired`), but it feels brittle. cc @dblaikie, @rnk who reviewed the patch.

FWIW, GCC does do this "alignment propagation" and attaches `DW_AT_alignment` to the derived class too

**Comment by hokein** [comment]
> > > > Yeah, the alignment issue is trickier if we consider all inheritance (base/virtual base) cases. I don't think we would like to re-implement the layout calculation in LLDB. One approach I think of is that we can emit DW_AT_alignment attribute for the derived classes (in your above case, that's foo) -- when clang emits debug information, we should know the exact alignment. What do you think?
> > > 
> > > 
> > > I think that would make sense
> > 
> > 
> > After taking a closer look, this is a regression caused by the https://reviews.llvm.org/D24426. After that change, clang emits `align` in the debug info only when the `alignment` attr is explicit (`alignas()`, `_Alignas()`, `__attribute(aligned (N))` etc). However, the "transitive" case is not covered, e.g.
> > ```
> > // !11 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "base", file: !7, line: 3, size: 64, align: 64, flags: DIFlagTypePassByValue, elements: !12, identifier: "_ZTS4base")
> > class alias(8) base {};
> > 
> > // !8 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "derived", file: !7, line: 5, size: 64, flags: DIFlagTypePassByValue, elements: !9, identifier: "_ZTS7derived")
> > class derived : base {};
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I guess the motivation of https://reviews.llvm.org/D24426 is to reduce the debug info size. One fix is to tweak the `getTypeAlignIfRequired`-family functions in `CGDebugInfo.cpp` to include missing cases (for the inheritance case here, we could traverse all base class decl, and see whether any of them is `isAlignRequired`), but it feels brittle. cc @dblaikie, @rnk who reviewed the patch.
> 
> FWIW, GCC does do this "alignment propagation" and attaches `DW_AT_alignment` to the derived class too: https://godbolt.org/z/j5MWdWYaf

Thanks for the confirmation.

I split it out in https://github.com/llvm/llvm-project/issues/73623 for better tracking. Let's make this thread focus on the issue where `DW_AT_alignment` is not used in lldb.

**Comment by hokein** [comment]
I think we can close this issue now, we have fixed the issue where lldb doesn't respect the `DW_AT_alignment` attribute . 

The other two issues are tracking separately in #https://github.com/llvm/llvm-project/issues/73623, https://github.com/llvm/llvm-project/issues/73563.
