### ISSUE TITLE
[libc++] atomic_unsigned_lock_free is usually signed

### ISSUE THREAD

**Issue by fghzxm** [llvm/llvm-project#72968]
In __atomic/aliases.h, `atomic_unsigned_lock_free` is defined as

https://github.com/llvm/llvm-project/blob/9a09c737a052dc0e2b8c15a969d16cff7ea0c133/libcxx/include/__atomic/aliases.h#L111

where `__libcpp_unsigned_lock_free` is defined as

https://github.com/llvm/llvm-project/blob/9a09c737a052dc0e2b8c15a969d16cff7ea0c133/libcxx/include/__atomic/aliases.h#L91-L107

where `__cxx_contention_t` is defined in __atomic/contention_t.h as

https://github.com/llvm/llvm-project/blob/9a09c737a052dc0e2b8c15a969d16cff7ea0c133/libcxx/include/__atomic/contention_t.h#L22-L26

Therefore, if `_LIBCPP_CONTENTION_LOCK_FREE` is true and at least one of `ATOMIC_{LLONG,INT,SHORT,CHAR}_LOCK_FREE` equals 2 (which is the case for most targets), `__libcpp_unsigned_lock_free` will be one of `int32_t` and `int64_t`, both of which are signed.

**Comment by ldionne** [comment]
Thanks for the report. Confirmed.

**Comment by ldionne** [comment]
Thanks for the analysis of the issue BTW, this made it easier to dig into.
