### ISSUE TITLE
For v8i8 operand, occur fatal error: error in backend: Do not know how to split this operator's operand!

### ISSUE THREAD

**Issue by mrxia1216** [llvm/llvm-project#72972]
In amdgcn architecture, I add a new instruction and builtin function, but when i exec "RUN: %clang_cc1 -triple amdgcn-amd-amdhsa -target-cpu gfx9xx  -S -o - %s", occur below error
![image](https://github.com/llvm/llvm-project/assets/11022951/587d6987-76cd-4375-8930-cae2f16f6da8)

SplitVectorOperand Op #1: t66: v4i32 = llvm.amdgcn.mmac.i32.16x16x32i8 TargetConstant:i64<1978>, t54, t63, t64
fatal error: error in backend: Do not know how to split this operator's operand!

IR:
```llvm
; ModuleID = '/public/home/xiayf/llvm-project-dev-for-test/clang/test/CodeGenOpenCL/builtins-amdgcn-mmac-gfx928.cl'
source_filename = "/public/home/xiayf/llvm-project-dev-for-test/clang/test/CodeGenOpenCL/builtins-amdgcn-mmac-gfx928.cl"
target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7"
target triple = "amdgcn-amd-amdhsa"

; Function Attrs: argmemonly convergent mustprogress nofree norecurse nounwind willreturn writeonly
define dso_local void @test_mmac_i32_16x16x32i8(ptr addrspace(1) nocapture noundef writeonly %out, <8 x i8> noundef %a, <8 x i8> noundef %b, <4 x i32> noundef %c) local_unnamed_addr #0 {
entry:
  %0 = tail call <4 x i32> @llvm.amdgcn.mmac.i32.16x16x32i8(<8 x i8> %a, <8 x i8> %b, <4 x i32> %c)
  store <4 x i32> %0, ptr addrspace(1) %out, align 16, !tbaa !3
  ret void
}

; Function Attrs: convergent mustprogress nofree nounwind readnone willreturn
declare <4 x i32> @llvm.amdgcn.mmac.i32.16x16x32i8(<8 x i8>, <8 x i8>, <4 x i32>) #1

attributes #0 = { argmemonly convergent mustprogress nofree norecurse nounwind willreturn writeonly "frame-pointer"="none" "min-legal-vector-width"="128" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx928" "target-features"="+16-bit-insts,+ci-insts,+dl-insts,+dot1-insts,+dot2-insts,+dot7-insts,+dpp,+flat-address-space,+gfx8-insts,+gfx9-insts,+gfx928-insts,+mmop-insts,+mmop2-insts,+s-memrealtime,+s-memtime-inst" }
attributes #1 = { convergent mustprogress nofree nounwind readnone willreturn }

!llvm.module.flags = !{!0}
!opencl.ocl.version = !{!1}
!llvm.ident = !{!2}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 1, i32 2}
!2 = !{!"clang version 15.0.0 (/public/home/xiayf/llvm-project-dev-for-test/clang 63c8eaf5f746ac66737b4a78d7cba2393ce58516)"}
!3 = !{!4, !4, i64 0}
!4 = !{!"omnipotent char", !5, i64 0}
!5 = !{!"Simple C/C++ TBAA"}
```

**Comment by mrxia1216** [comment]
@nikic

**Comment by nikic** [comment]
Please provide the input IR triggering the crash.

**Comment by mrxia1216** [comment]
> Please provide the input IR triggering the crash.

when generate asm，would occur this error

**Comment by arsenm** [comment]
This is one of the possible failure modes when you attempt to codegen an intrinsic on a subtarget that doesn't support the underlying instruction. We do not try to emulate intrinsics on other targets, and we do not really try to properly diagnose this in the backend. The frontend usually is enforcing subtarget restrictions

**Comment by mrxia1216** [comment]
> This is one of the possible failure modes when you attempt to codegen an intrinsic on a subtarget that doesn't support the underlying instruction. We do not try to emulate intrinsics on other targets, and we do not really try to properly diagnose this in the backend. The frontend usually is enforcing subtarget restrictions

Hello, I meet this error for DAGTypeLegalizer::SplitVectorOperand when NodeType is INTRINSIC_WO_CHAIN and type of params is v8i8

**Comment by mrxia1216** [comment]
> > Hello, I meet this error for DAGTypeLegalizer::SplitVectorOperand when NodeType is INTRINSIC_WO_CHAIN and type of params is v8i8
> 
> This is what happens for target intrinsics that use types that aren't legal for the target. You either should avoid defining intrinsics with illegal types, or need to add a register class for v8i8.
> 
> What is gfx928 and what is llvm.amdgcn.mmac? I don't see these defined.

Thanks, And how to add a register class for v8i8?

**Comment by arsenm** [comment]
> > > Hello, I meet this error for DAGTypeLegalizer::SplitVectorOperand when NodeType is INTRINSIC_WO_CHAIN and type of params is v8i8
> > 
> > 
> > This is what happens for target intrinsics that use types that aren't legal for the target. You either should avoid defining intrinsics with illegal types, or need to add a register class for v8i8.
> > What is gfx928 and what is llvm.amdgcn.mmac? I don't see these defined.
> 
> Thanks, And how to add a register class for v8i8?

addRegisterClass call in the constructor, but that would also introduce a lot of legalization work to fully cover this unnaturally legal type. I would avoid doing that. I would either change the function signature to use the bitcast equivalent v2i32, or hack the node to <2 x i32> in ReplaceNodeResults.

**Comment by mrxia1216** [comment]
> addRegisterClass call in the constructor, but that would also introduce a lot of legalization work to fully cover this unnaturally legal type. I would avoid doing that. I would either change the function signature to use the bitcast equivalent v2i32, or hack the node to <2 x i32> in ReplaceNodeResults.

OK, Thanks
