### ISSUE TITLE
[MLIR] Feature request: translate from LLVM Dialect to LLVMIR using the C API

### ISSUE THREAD

**Issue by edg-l** [llvm/llvm-project#73008]
I tried to search for a method to convert programatically using the C API MLIR code to LLVMIR and my conclusion is, you can't, because its missing the method `mlir::translateModuleToLLVMIR` (https://mlir.llvm.org/doxygen/classmlir_1_1LLVM_1_1ModuleTranslation.html#ac7e657a04e78a09ffd38c2f6cde6b905)

Are there plans to add this funcionality to the C API?

**Comment by joker-eph** [comment]
Feel free to submit a patch if you need the feature. It's unlikely that it'll happen until someone needs it. MLIR is driven by the needs of the contributors mainly: https://mlir.llvm.org/getting_started/Faq/#why-is-small-feature-not-available-in-mlir

**Comment by edg-l** [comment]
> Feel free to submit a patch if you need the feature. It's unlikely that it'll happen until someone needs it. MLIR is driven by the needs of the contributors mainly: https://mlir.llvm.org/getting_started/Faq/#why-is-small-feature-not-available-in-mlir

I'll try to do it then!

**Comment by vitalybuka** [comment]
The patch was reverted fea023b129190edeb503dbe947034f925bbda666

**Comment by vitalybuka** [comment]
The patch was re-landed with leak fix https://github.com/llvm/llvm-project/commit/7fb89bfb0f93d5cfe3cf661253bbb2e2ef19359a
