### ISSUE TITLE
-fasm-blocks: __asm { call fptr } does not use RIP-relative addressing

### ISSUE THREAD

**Issue by dmiller423** [llvm/llvm-project#73033]
``
clang version 17.0.4
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\dev\llvm\bin``

Target is a simple static library,  contents: two functions one __weak_symbol __attribute__((naked)) containing assembly in intel format that calls a static global address in the same file (set by the second function).

The generated objects are not position independent code, using R_X86_64_32S for relocations of the functions containing asm blocks declared as weak.

tested TARGET list `{ x86_64-pc-freebsd12-elf, x86_64-pc-unknown-elf, x86_64-pc-linux-gnu }`

--
reproduction:
``
clang-17.0.4 --target=%TARGET% --sysroot=C:/tc_sysroot/%TARGET%/  -fPIC -fPIE -fasm-blocks -MD -MT syscalls.c.o -MF syscalls.c.o.d -o syscalls.c.o -c syscalls.c
``

objects relocations were tested via readelf and custom tooling,  all cases produce:

``> readelf -r syscalls.c.o``
```
Relocation section '.rela.text' at offset 0x120 contains 2 entries:
    Offset             Info             Type               Symbol's Value  Symbol's Name + Addend
000000000000000f  0000000300000002 R_X86_64_PC32          0000000000000000 .bss - 4
000000000000002f  000000030000000b R_X86_64_32S           0000000000000000 .bss + 0
```

rebuilding the same file/params with a previous version (clang-15.0.7):

``> readelf -r syscalls.c.o``
```
Relocation section '.rela.text' at offset 0x128 contains 2 entries:
    Offset             Info             Type               Symbol's Value  Symbol's Name + Addend
000000000000000f  0000000300000002 R_X86_64_PC32          0000000000000000 .bss - 4
000000000000002e  0000000300000002 R_X86_64_PC32          0000000000000000 .bss - 4
```

source:

```c
#include <stdint.h>
#include <sys/types.h>

static uint64_t syscall_addr = 0;

int syscalls_init(uint64_t addr) {
    syscall_addr = addr;
    return 0;
}

__weak_symbol 
__attribute__((naked)) 
ssize_t read(int fd, void* buf, size_t nbytes)  {
    __asm {
            push rbp
            mov rbp, rsp
            mov eax, 3
            mov r10, rcx
            call syscall_addr
            pop rbp
            ret
    }
}
```

**Comment by efriedma-quic** [comment]
Related to https://reviews.llvm.org/D151863?  CC @MaskRay @KanRobert @akshaykhadse

**Comment by MaskRay** [comment]
Adding back `BaseReg = BaseReg ? BaseReg : 1;` will produce `callq   *syscall_addr(%rip)` instead of `callq   *syscall_addr`. But that would break the case fixed by https://reviews.llvm.org/D151863
