### ISSUE TITLE
[analyzer] Turn NodeBuilderContext into a class

### ISSUE THREAD

**Issue by gz83** [llvm/llvm-project#73088]
`
// TODO: Turn into a class.
struct NodeBuilderContext {
  const CoreEngine &Eng;
  const CFGBlock *Block;
  const LocationContext *LC;

  NodeBuilderContext(const CoreEngine &E, const CFGBlock *B,
                     const LocationContext *L)
      : Eng(E), Block(B), LC(L) {
    assert(B);
  }

  NodeBuilderContext(const CoreEngine &E, const CFGBlock *B, ExplodedNode *N)
      : NodeBuilderContext(E, B, N->getLocationContext()) {}

  /// Return the CFGBlock associated with this builder.
  const CFGBlock *getBlock() const { return Block; }

  /// Returns the number of times the current basic block has been
  /// visited on the exploded graph path.
  unsigned blockCount() const {
    return Eng.WList->getBlockCounter().getNumVisited(
                    LC->getStackFrame(),
                    Block->getBlockID());
  }
};`

Consider implementing this TODO

**Comment by diego-est** [comment]
Hello, I would like to contribute to this issue. Can it be assigned to me?

**Comment by EugeneZelenko** [comment]
@diego-est: Just create pull request and mention it on this page.

**Comment by diego-est** [comment]
Here is the pull request that I opened with the necessary changes: #84638

**Comment by diego-est** [comment]
I think this issue can now be closed?

**Comment by gz83** [comment]
Good job
