### ISSUE TITLE
xcode use SanitizerCoverage with flag -fsanitize-coverage-allowlist,but does not work.How can i solve this problem?

### ISSUE THREAD

**Issue by MrChocolate** [llvm/llvm-project#73098]

**Comment by MrChocolate** [comment]
亲，您的邮件我已收到会尽快给你回复···好人一生平安

**Comment by MrChocolate** [comment]
> Could you please describe your problem in detail?

I want to use allowlist file like flow code `fun:*homePageOutputEvent*` to allow this function。however，every function is allowed。just like not add the allowlist。

this is the document says：
`# Enable instrumentation for a whole folder
src:bar/*
# Enable instrumentation for a specific source file
src:foo/a.cpp
# Enable instrumentation for all functions in those files
fun:*`

**Comment by dtcxzyw** [comment]
cc @MaskRay

**Comment by MaskRay** [comment]
See `llvm/lib/Transforms/Instrumentation/SanitizerCoverage.cpp`, by default most functions are instrumented. You likely don't use an ignore list to skip certain files/functions.
