### ISSUE TITLE
Error emit when I change the ld of gcc-linaro-6.5.0-2018.12-x86_64_aarch64-linux-gnu to ld.lld

### ISSUE THREAD

**Issue by playboy0007** [llvm/llvm-project#73129]
![img_v3_0256_e2157e10-cef9-4c17-9a9d-7d8e34d2ba4g](https://github.com/llvm/llvm-project/assets/36851506/c1b72948-4572-4c05-ad33-3cc900edd942)

**Comment by EugeneZelenko** [comment]
@playboy0007: Please provide reproducer.

**Comment by playboy0007** [comment]
> @llvm/issue-subscribers-lld-elf
> 
> Author: None (playboy0007)
> 



> @playboy0007: Please provide reproducer.

what's you mean of reproducer?

**Comment by EugeneZelenko** [comment]
@playboy0007: Set of input files necessary to reproduce crash.
