### ISSUE TITLE
[flang] Missing semantic error for procedure pointer target that is not known to be a procedure  

### ISSUE THREAD

**Issue by jeanPerier** [llvm/llvm-project#73215]
The following program is accepted by flang, while all other compilers reject it:

```
  procedure(real), pointer :: p
  p => x
end
```

(Flang implicitly resolves `x` to be a procedure).

Failing tests in the llvm-test-suite:

https://github.com/llvm/llvm-test-suite/blob/main/Fortran/gfortran/regression/proc_ptr_46.f90
https://github.com/llvm/llvm-test-suite/blob/main/Fortran/gfortran/regression/proc_ptr_37.f90

**Comment by pklausler** [comment]
This behavior is intentional, as I could find no constraint out requirement from the standard being violated, and the interpretation is unambiguous.

**Comment by klausler** [comment]
Assigned back to Jean, who can respond to my comment or close the bug.
