### ISSUE TITLE
[17 Regression] clang++ fails to link, when installed in a non-standard location

### ISSUE THREAD

**Issue by doko42** [llvm/llvm-project#73244]
seen with 17.0.5, works with 16.0.6. clang++ linkage fails, when installed in a non-standard location.

clang++-17 -std=c++14 -stdlib=libc++ foo.cpp -lc++experimental -o o
/usr/bin/ld: cannot find -lc++experimental: No such file or directory

when calling with -v, and looking at the invocation of the linker, the link command varies:

@@ -17,7 +17,6 @@
 -L/lib/../lib64
 -L/usr/lib/x86_64-linux-gnu
 -L/usr/lib/../lib64
--L/usr/lib/llvm-16/bin/../lib
 -L/lib
 -L/usr/lib
 foo.o

the installation prefix is /usr/lib/llvm-1[67].  LLVM 17 doesn't emit the -L\<prefix\>/bin/../lib flag anymore. This works with 16 and older versions.

**Comment by sylvestre** [comment]
I think it is now fixed
