### ISSUE TITLE
Execute_command_line intrinsic

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#73318]
Add support for the execute_command_line intrinsic

Standard: Fortran 2008 and later

Usage: CALL EXECUTE_COMMAND_LINE(COMMAND [, WAIT, EXITSTAT, CMDSTAT, CMDMSG ])

Arguments:
```
COMMAND	Shall be a default CHARACTER scalar.
WAIT	(Optional) Shall be a default LOGICAL scalar.
EXITSTAT	(Optional) Shall be an INTEGER of the default kind.
CMDSTAT	(Optional) Shall be an INTEGER of the default kind.
CMDMSG	(Optional) Shall be an CHARACTER scalar of the default kind.
```

Example:
```
program test_exec
integer :: i

call execute_command_line ("external_prog.exe", exitstat=i)
print *, "Exit status of external_prog.exe was ", i

call execute_command_line ("reindex_files.exe", wait=.false.)
print *, "Now reindexing files in the background" 
end program test_exec
```

Other References
-> Jeff Hammond has a partial implementation in https://github.com/jeffhammond/llvm-project/tree/jeffhammond-execute_command_line.
-> Section 16.9.73 in https://j3-fortran.org/doc/year/18/18-007r1.pdf
-> Classic Flang implementation is https://github.com/flang-compiler/flang/blob/2693fbaff2a67ccb64d8e6800e8d63cfc8180a4f/runtime/flang/rdst.c#L2802
-> https://gcc.gnu.org/onlinedocs/gcc-13.2.0/gfortran/EXECUTE_005fCOMMAND_005fLINE.html

Testing
Please test extensively using your tests and also tests from the following.
https://github.com/llvm/llvm-test-suite/blob/main/Fortran/gfortran/regression/execute_command_line_1.f90
https://github.com/llvm/llvm-test-suite/blob/main/Fortran/gfortran/regression/execute_command_line_2.f90
https://github.com/llvm/llvm-test-suite/blob/main/Fortran/gfortran/regression/execute_command_line_3.f90

**Comment by kiranchandramohan** [comment]
https://github.com/yi-wu-arm is working on this.

**Comment by yi-wu-arm** [comment]
under review: pr https://github.com/llvm/llvm-project/pull/74077

**Comment by jeffhammond** [comment]
https://github.com/llvm/llvm-project/pull/74077 was merged.  Should this be closed?

**Comment by tblah** [comment]
Closing. Thanks for working on this @yi-wu-arm, and for pointing out the issue @jeffhammond
