### ISSUE TITLE
`((cst << x) & 1)` --> `x == 0` when cst is odd

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#73384]
Test case:
https://godbolt.org/z/15x6fe7vr
```cpp
int f3(int c)
{
  return ((3 << c) & 1);
}
```

See Also: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96669

**Comment by ParkHanbum** [comment]
hello. I have sent two issues to PR and would like to take on these issues. 
reason I'm telling you this is because the two PRs I sent were not accepted. 
maybe I something wrong.
