### ISSUE TITLE
llvmbot still tells people to submit to Phab

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#73400]
See the message attached to #73399 

> 6) Submit the patch to [Phabricator](https://reviews.llvm.org/).
>    6.1) Detailed instructions can be found [here](https://llvm.org/docs/Phabricator.html#requesting-a-review-via-the-web-interface)

**Comment by SimplyDanny** [comment]
This has already been addressed in #65914 awaiting review. Perhaps you can jump in for cross checking.

**Comment by JOE1994** [comment]
Closing as duplicate of #65890
