### ISSUE TITLE
Incorrect default target triple on windows

### ISSUE THREAD

**Issue by Weldify** [llvm/llvm-project#73401]
I'm using Windows, I compiled LLVM using clang/clang++ as the compiler and lld as the linker (following building with cmake).
When calling `llvm::sys::getDefaultTargetTriple()`, it returns just `x86_64`. This caused me a huge deal of trouble when it came to outputting object files and linking them. I decided to try and manually set the target triple to `x86_64-gnu-windows` and now everything works as expected.

**Comment by tru** [comment]
@Weldify I think we need some more details here, what version of LLVM did you build and what was the flags you used? You mention the triple `x86_64-gnu-windows` which I am pretty sure is not a valid triple, if you want to target mingw it should be `x86_64-pc-windows-gnu` if you want to target "native" windows toolchain it should be `x86_64-pc-windows-msvc`.

**Comment by Weldify** [comment]
I think this issue is invalid. If I remember correctly the actual problem was that LLVM couldn't figure out my target triple automatically, so I had to set it manually and failed. Eventually I did succeed and everything worked fine. Apologies for not keeping this issue up to date.
