### ISSUE TITLE
[LIBC++]: Transitive include

### ISSUE THREAD

**Issue by Pawday** [llvm/llvm-project#73450]
### [Clang 17.0.2](https://github.com/llvm/llvm-project/tree/b2417f51dbbd7435eb3aaf203de24de6754da50e)

```c++
#include <format>

int main()
{
    std::array<int, 5> test_array{};
}
```

Compiles on  [libc++](https://github.com/llvm/llvm-project/tree/b2417f51dbbd7435eb3aaf203de24de6754da50e)

Error on gcc 13.2.1

```sh
clang -H TransitiveArray.cpp
```
```
. /usr/lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/format
.. /usr/lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/requires_hosted.h
... /usr/lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/x86_64-pc-linux-gnu/bits/c++config.h
.... /usr/lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/x86_64-pc-linux-gnu/bits/os_defines.h
..... /usr/include/features.h
...... /usr/include/features-time64.h
....... /usr/include/bits/wordsize.h
....... /usr/include/bits/timesize.h
........ /usr/include/bits/wordsize.h
...... /usr/include/stdc-predef.h
...... /usr/include/sys/cdefs.h
....... /usr/include/bits/wordsize.h
....... /usr/include/bits/long-double.h
...... /usr/include/gnu/stubs.h
....... /usr/include/gnu/stubs-64.h
.... /usr/lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/x86_64-pc-linux-gnu/bits/cpu_defines.h
.... /usr/lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/pstl/pstl_config.h
TransitiveArray.cpp:5:10: error: no member named 'array' in namespace 'std'
    5 |     std::array<int, 5> test_array{};
      |     ~~~~~^
TransitiveArray.cpp:5:19: error: expected '(' for function-style cast or type construction
    5 |     std::array<int, 5> test_array{};
      |                ~~~^
TransitiveArray.cpp:5:24: error: use of undeclared identifier 'test_array'
    5 |     std::array<int, 5> test_array{};
      |                        ^
3 errors generated.
```

It seems the problem is [here](https://github.com/llvm/llvm-project/blob/b2417f51dbbd7435eb3aaf203de24de6754da50e/libcxx/include/__format/formatter_integral.h#L26-L29)

**Comment by philnik777** [comment]
Implementations are free to include other parts of the library. Every implementation does this for some symbols. You can use IWYU or similar tools to avoid relying on transitive includes.

**Comment by ldionne** [comment]
I agree -- this is basically impossible to solve on the libc++ side. If you are worried about depending on non-portable transitive includes, you should use IWYU or Clang modules, which really help with finding these kinds of issues.

**Comment by philnik777** [comment]
Yes. If we use `std::array` as an implementation detail or it's part of the interface we have to include it. Whether we include `<array>` or `<__whatever/array.h>` doesn't make a difference. `_LIBCPP_REMOVE_TRANSITIVE_INCLUDES` is just to avoid including a bunch of stuff we don't actually use.

**Comment by mordante** [comment]
We indeed use `std::array` as an implementation detail in `std::format`. So it's impossible to "fix" this in libc++ unless we change our implementation. IWYU is the proper fix.
