### ISSUE TITLE
Function should call copy constructor if return is a lvalue expr and move constructor is not available. 

### ISSUE THREAD

**Issue by changkhothuychung** [llvm/llvm-project#73453]
Is this example considered a bug? https://godbolt.org/z/TETeK9n5c

**Comment by rilysh** [comment]
You've marked the function `= delete` which according to C++11 restricts copying. It's quite the opposite of `= default` where you're setting a default state of copying.

You can, however, use a rvalue, only if it's necessary.
```cpp
auto&& b = a;
return b;
```

**Comment by shafik** [comment]
Example program, simplified: https://godbolt.org/z/fvxz5Mvjq

```cpp
struct A {
    A(){}
    ~A(){}
    A(const A&){}
    A(A&&) = delete; 
};

A f(){
    A a; 
    return a; 
}

int main(){
    f(); 
}
```

This falls afoul of [dcl.fct.def.delete p2](https://eel.is/c++draft/dcl.fct.def.delete#2) which says:

> A program that refers to a deleted function implicitly or explicitly, other than to declare it, is ill-formed[.](https://eel.is/c++draft/dcl.fct.def.delete#2.sentence-1)
