### ISSUE TITLE
[LLD] corrupt input file: version definition index 0 for symbol g_aucPatchArea is out of bounds

### ISSUE THREAD

**Issue by CoTinker** [llvm/llvm-project#73473]
```
$ ld.lld -o lsw_test idcs_stub.c.o libidcs_stubs.so

ld.lld: error: corrupt input file: version definition index 0 for symbol g_aucPatchArea is out of bounds
>>> defined in libidcs_stubs.so

ld.lld: error: corrupt input file: version definition index 0 for symbol g_aucPatchDataArea is out of bounds
>>> defined in libidcs_stubs.so

ld.lld: error: corrupt input file: version definition index 0 for symbol writeout_fn_list is out of bounds
>>> defined in libidcs_stubs.so

ld.lld: error: corrupt input file: version definition index 0 for symbol m_test is out of bounds
>>> defined in libidcs_stubs.so

ld.lld: error: corrupt input file: version definition index 0 for symbol reset_fn_list is out of bounds
>>> defined in libidcs_stubs.so
```
libidcs_stubs.so --> libglobal_stubs.so --> vos.o

$ readelf -sW **vos.o** | grep g_aucPatchArea

```
173: 00001000 0x80000 OBJECT  GLOBAL DEFAULT  COM g_aucPatchArea
```

$ readelf -sW **libglobal_stubs.so** | grep g_aucPatchArea

```
557: 00036000 524288 OBJECT GLOBAL DEFAULT    25 g_aucPatchArea
450: 00036000 524288 OBJECT GLOBAL DEFAULT    25 g_aucPatchArea
```

$ readelf -sW **libidcs_stubs.so** | grep g_aucPatchArea

```
2431: 005f1000 524288 OBJECT GLOBAL DEFAULT    26 g_aucPatchArea
27650: 005f1000 524288 OBJECT GLOBAL DEFAULT    26 g_aucPatchArea
```
I find that the ver of symbol g_aucPatchArea is VER_NDX_LOCAL.
https://github.com/llvm/llvm-project/blob/6c462fe2112c83b2682ffa3e7b0a70c33ea4ca7e/lld/ELF/InputFiles.cpp#L1530-L1541

**Comment by MaskRay** [comment]
> I find that the ver of symbol g_aucPatchArea is VER_NDX_LOCAL.

This indicates that the input is invalid and lld correctly rejects the input.

If the symbol is a COMMON symbol in the relocatable object file, you'll need a GNU ld newer than 2019-11 (https://sourceware.org/bugzilla/show_bug.cgi?id=25236).
