### ISSUE TITLE
How can I get precise pointee type and what is Address is for?

### ISSUE THREAD

**Issue by ash1852** [llvm/llvm-project#73510]
I'm using llvm to implement some tranformation on IR, so there are some creation for AllocInst. If I create a AllocInst with element type **A**, I thought the type of created AllocInst should be pointer type of **A**, but it was not. The created AllocInst's type is a pointer type but its pointee type is null thus causing null dereference.
![image](https://github.com/llvm/llvm-project/assets/87304478/282db3b9-459a-4df7-af58-a8d2ddf2c668)
and after check the source code, i found the type of the AllocInst is set by using **PointerType \*PointerType::get(Type \*EltTy, unsigned AddressSpace)**
![image](https://github.com/llvm/llvm-project/assets/87304478/dbc8ca88-27ec-4129-8d06-c869beebe1bf)
since AddressSpace==0, CImpl->PointerTypes[EltTy] was returned.
I've search for what AddressSpace is for but still did'nt get it. Can you explain it Or just help me to get a precise pointee type of pointer type?
thank you very much.

**Comment by JOE1994** [comment]
>  If I create a AllocInst with element type A, I thought the type of created AllocInst should be pointer type of A, but it was not. The created AllocInst's type is a pointer type but its pointee type is null thus causing null dereference.

LLVM uses opaque pointers (please see https://llvm.org/docs/OpaquePointers.html for context),
meaning that pointers themselves no longer have an associated pointee type.
With opaque pointers, users of a pointer decide what type of value to read from it.

Yes, type of `AllocaInst` is a pointer type. `AllocaInst` does have a method `AllocaInst::getAllocatedType` that returns the originally allocated pointee type of the `AllocaInst`.
