### ISSUE TITLE
clang-format-diff.py --help always references clang-format-diff.py even when aliased

### ISSUE THREAD

**Issue by serge-sans-paille** [llvm/llvm-project#73635]
reproducer:

```sh
$ clang-format-diff.py --help | head -n 10 | tail -n2
  git diff -U0 --no-color --relative HEAD^ | clang-format-diff.py -p1 -i
  svn diff --diff-cmd=diff -x-U0 | clang-format-diff.py -i
```

everything looks fine, the help references `clang-format-diff.py`. But if we create an alias

```sh
$ ln -s `which clang-format-diff.py` cfd
$ PATH=$PWD:$PATH cfd  --help | head -n 10 | tail -n2
  git diff -U0 --no-color --relative HEAD^ | clang-format-diff.py -p1 -i
  svn diff --diff-cmd=diff -x-U0 | clang-format-diff.py -i
```
we still get a reference to the aliased command, which doesn't help, e.g. when copy-pasting. This happens under Fedora where `clang-format-diff.py` is just renamed into `clang-format-diff`

**Comment by owenca** [comment]
Fixed in ced0f28a35b8a14759e6bd9418e8c8a7c35775c8.
