### ISSUE TITLE
DW_AT_decl_file issue with -gdwarf-5 and -fdebug-prefix-map

### ISSUE THREAD

**Issue by myxoid** [llvm/llvm-project#73652]
I've noticed a difference in Clang between DWARF 4 and DWARF 5. This only occurs with `-fdebug-prefix-map` as far as I can tell, so it may be a bug in that code path. GCC has a slightly different bug.

The issue is that `DW_AT_decl_file` attributes (sometimes) have the implicit `DW_AT_comp_dir` explicitly prepended. This leads to confusion with the output from tools such as `llvm-dwarfdump` that (very unhelpfully) also prepend the implicit prefix. More significantly, it breaks tools (like libabigail, for example) that expect

source file name = compilation directory + "/" + declaration file name

Beware! `llvm-dwarfdump` prepends `DW_AT_comp_dir`, always `("p")` in the below example (but `grep`ed out).

Anything with `"p/p"` in the displayed path is wrong. For Clang, that's the cases of compiling either `x.c` or `z/x.c` in `/tmp` and stripping off the prefix `"/tm"`.

```
/tmp$ head x.c z/x.c 
==> x.c <==
int x;

==> z/x.c <==
int x;
/tmp$ for f in x z/x; do for g in 4 5; do for c in gcc-11 gcc-12 gcc-13 clang-13 clang-14 clang-15 clang-16; do
  $c -gdwarf-$g -fdebug-prefix-map=/tm= -c $f.c -o $f.o
  echo -n "$f $g $c"; llvm-dwarfdump $f.o | grep DW_AT_decl_file
done; done; done
x 4 gcc-11                DW_AT_decl_file	("p/x.c")
x 4 gcc-12                DW_AT_decl_file	("p/x.c")
x 4 gcc-13                DW_AT_decl_file	("p/x.c")
x 4 clang-13                DW_AT_decl_file	("p/x.c")
x 4 clang-14                DW_AT_decl_file	("p/x.c")
x 4 clang-15                DW_AT_decl_file	("p/x.c")
x 4 clang-16                DW_AT_decl_file	("p/x.c")
x 5 gcc-11                DW_AT_decl_file	("p/p/x.c")
x 5 gcc-12                DW_AT_decl_file	("p/p/x.c")
x 5 gcc-13                DW_AT_decl_file	("p/p/x.c")
x 5 clang-13                DW_AT_decl_file	("p/p/x.c")
x 5 clang-14                DW_AT_decl_file	("p/p/x.c")
x 5 clang-15                DW_AT_decl_file	("p/p/x.c")
x 5 clang-16                DW_AT_decl_file	("p/p/x.c")
z/x 4 gcc-11                DW_AT_decl_file	("p/z/x.c")
z/x 4 gcc-12                DW_AT_decl_file	("p/z/x.c")
z/x 4 gcc-13                DW_AT_decl_file	("p/z/x.c")
z/x 4 clang-13                DW_AT_decl_file	("p/z/x.c")
z/x 4 clang-14                DW_AT_decl_file	("p/z/x.c")
z/x 4 clang-15                DW_AT_decl_file	("p/z/x.c")
z/x 4 clang-16                DW_AT_decl_file	("p/z/x.c")
z/x 5 gcc-11                DW_AT_decl_file	("p/z/x.c")
z/x 5 gcc-12                DW_AT_decl_file	("p/z/x.c")
z/x 5 gcc-13                DW_AT_decl_file	("p/z/x.c")
z/x 5 clang-13                DW_AT_decl_file	("p/p/z/x.c")
z/x 5 clang-14                DW_AT_decl_file	("p/p/z/x.c")
z/x 5 clang-15                DW_AT_decl_file	("p/p/z/x.c")
z/x 5 clang-16                DW_AT_decl_file	("p/p/z/x.c")
```

FTR

```
$ clang-16 -v
Debian clang version 16.0.6 (11)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/13
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/13
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
```

**Comment by dwblaikie** [comment]
Hmm, at least at a glance I'm not reproducing this behavior/missing something in the reproduction:
Taking the `x 5 clang-16                DW_AT_decl_file	("p/p/x.c")` example:
```
$ clang-15 -gdwarf-5 -fdebug-prefix-map=/tm= -c x.c -o x.o;  echo -n "x 5 clang-15"; llvm-dwarfdump x.o | grep DW_AT_decl_file
x 5 clang-15                DW_AT_decl_file     ("p/x.c")
$ clang-tot -gdwarf-5 -fdebug-prefix-map=/tm= -c x.c -o x.o;  echo -n "x 5 clang-tot"; llvm-dwarfdump x.o | grep DW_AT_decl_file
x 5 clang-tot                DW_AT_decl_file    ("p/x.c")
```

And the line table looks reasonable, says a directory "p" with a file "x.c" in it. The full output of the matrix of tests for me (well, with the GCC and clang versions I have on hand):
```
$ for f in x z/x; do for g in 4 5; do for c in gcc-11 gcc-12 gcc-13 clang-13 clang-14 clang-15 clang-tot; do $c -gdwarf-$g -fdebug-prefix-map=/tm= -c $f.c -o $f.o; echo -n "$f $g $c"; llvm-dwarfdump $f.o | grep DW_AT_decl_file; done; done; done
x 4 gcc-11                DW_AT_decl_file       ("p/x.c")
x 4 gcc-12                DW_AT_decl_file       ("p/x.c")
x 4 gcc-13                DW_AT_decl_file       ("p/x.c")
x 4 clang-13                DW_AT_decl_file     ("p/x.c")
x 4 clang-14                DW_AT_decl_file     ("p/x.c")
x 4 clang-15                DW_AT_decl_file     ("p/x.c")
x 4 clang-tot                DW_AT_decl_file    ("p/x.c")
x 5 gcc-11                DW_AT_decl_file       ("p/x.c")
x 5 gcc-12                DW_AT_decl_file       ("p/x.c")
x 5 gcc-13                DW_AT_decl_file       ("p/x.c")
x 5 clang-13                DW_AT_decl_file     ("p/x.c")
x 5 clang-14                DW_AT_decl_file     ("p/x.c")
x 5 clang-15                DW_AT_decl_file     ("p/x.c")
x 5 clang-tot                DW_AT_decl_file    ("p/x.c")
z/x 4 gcc-11                DW_AT_decl_file     ("p/z/x.c")
z/x 4 gcc-12                DW_AT_decl_file     ("p/z/x.c")
z/x 4 gcc-13                DW_AT_decl_file     ("p/z/x.c")
z/x 4 clang-13                DW_AT_decl_file   ("p/z/x.c")
z/x 4 clang-14                DW_AT_decl_file   ("p/z/x.c")
z/x 4 clang-15                DW_AT_decl_file   ("p/z/x.c")
z/x 4 clang-tot                DW_AT_decl_file  ("p/z/x.c")
z/x 5 gcc-11                DW_AT_decl_file     ("p/z/x.c")
z/x 5 gcc-12                DW_AT_decl_file     ("p/z/x.c")
z/x 5 gcc-13                DW_AT_decl_file     ("p/z/x.c")
z/x 5 clang-13                DW_AT_decl_file   ("p/z/x.c")
z/x 5 clang-14                DW_AT_decl_file   ("p/z/x.c")
z/x 5 clang-15                DW_AT_decl_file   ("p/z/x.c")
z/x 5 clang-tot                DW_AT_decl_file  ("p/z/x.c")
```

**Comment by myxoid** [comment]
Great. So this isn't a minimal test case of the actual problem we've run into.

This is a bug in `llvm-dwarfdump-13` and `-14`, at least. Versions 9, 10, 15 and 16 are OK. There was a different bug in versions 9 and 10 (see below). Also, the plain `dwarfdump` I have on my machine has the same bug as versions 13 and 14.

It's very annoying that there isn't a DWARF dumper that can be trusted.

|CU|DWARF|compiler|tables|llvm-dwarfdump|reported attribute|
|-|-|-|-|-|-|
|x.c|4|*|no directories<br>file 1 = "x.c"|*|p/x.c|
|z/x.c|4|*|directory "z"<br>file 1 = "x.c" in dir 1|*|p/z/x.c|
|x.c|5|Clang 13, 14, 15, 16|dir 0 = "p"<br>file 0 = "x.c" in dir 0|9, 10, 15, 16|p/x.c|
|x.c|5|Clang 13, 14, 15, 16|dir 0 = "p"<br>file 0 = "x.c" in dir 0|13, 14|p/p/x.c|
|x.c|5|GCC 11, 12, 13|dir 0 = "p"<br>file 0 = "x.c" in dir 0<br>file 1 = "x.c" in dir 0|9, 10, 15, 16|p/x.c|
|x.c|5|GCC 11, 12, 13|dir 0 = "p"<br>file 0 = "x.c" in dir 0<br>file 1 = "x.c" in dir 0|13, 14|p/p/x.c|
|z/x.c|5|Clang 13, 14, 15, 16|dir 0 = "p"<br>file 0 = "z/x.c" in dir 0|9, 10, 15, 16|p/z/x.c|
|z/x.c|5|Clang 13, 14, 15, 16|dir 0 = "p"<br>file 0 = "z/x.c" in dir 0|13, 14|p/p/z/x.c|
|z/x.c|5|GCC 11, 12, 13|dir 0 = "p"<br>dir 1 = "z"<br>file 0 = "x.c" in dir 1<br>file 1 = "x.c" in dir 1|9, 10|z/x.c|
|z/x.c|5|GCC 11, 12, 13|dir 0 = "p"<br>dir 1 = "z"<br>file 0 = "x.c" in dir 1<br>file 1 = "x.c" in dir 1|13, 14, 15, 16|p/z/x.c|

I'll see if I can reproduce the original issue, starting from scratch.
