### ISSUE TITLE
`vector<int*const>` fails to build with an error in C++20 mode

### ISSUE THREAD

**Issue by ilya-biryukov** [llvm/llvm-project#73664]
This code should technically be allowed per C++20 standard (`int *const` meets the requirement of [MoveInsertable](https://en.cppreference.com/w/cpp/named_req/MoveInsertable) and [Erasable](https://en.cppreference.com/w/cpp/named_req/Erasable)):
```cpp
#include <vector>

int main() {
    std::vector<int* const> foo;
    foo.push_back(nullptr);
}
```

However, when I build with `clang++ -std=c++20` using libc++ from close to head, I get a compiler error:
```
../include/c++/v1/__algorithm/move.h:42:17: error: cannot assign to return value because function 'operator*' returns a const value
   42 |       *__result = _IterOps<_AlgPolicy>::__iter_move(__first);
...
<source>:5:9: note: in instantiation of member function 'std::vector<const int *const>::push_back' requested here
    5 |     foo.push_back(nullptr);

```

Compiling with `-std=c++17` produces no errors. I believe this is somehow related to allocators, because specifying `-D_LIBCPP_ENABLE_CXX20_REMOVED_ALLOCATOR_MEMBERS` and `-D_LIBCPP_ENABLE_CXX20_REMOVED_ALLOCATOR_VOID_SPECIALIZATION` with `-std=c++20` makes this code compile again.

See [godbolt](https://gcc.godbolt.org/z/4rfx7nqzM) too.

**Comment by ldionne** [comment]
I don't think this is valid, because `std::allocator<T const>` isn't guaranteed to work by the standard and you're using that implicitly. We currently have a non-standard "extension" that we've been trying to remove that makes this work in some cases, but it shouldn't. See a54d028895c91da356a4aaf30e27a5a5b90dd313.
