### ISSUE TITLE
`AllowedPad` option for `optin.performance.Padding` static analyzer check is not documented

### ISSUE THREAD

**Issue by firewave** [llvm/llvm-project#73675]
The `optin.performance.Padding` check has the option `AllowedPad` which allows to set a threshold for the warning to be reported:
https://github.com/llvm/llvm-project/blob/21361bb8605fd26a06312d80b9fb20a8b41c58ed/clang/include/clang/StaticAnalyzer/Checkers/Checkers.td#L894-L900

But there is no mention of the option in the documentation:
https://clang.llvm.org/docs/analyzer/checkers.html#optin-performance-padding

I guess there's several more undocumented options.

And in case they are documented it is done rather awkward:
https://clang.llvm.org/docs/analyzer/checkers.html#core-bitwiseshift-c-c

**Comment by firewave** [comment]
On a side note - it appears it is not possible to specify this option in clang-tidy, but this is already tracked in #48437.

**Comment by steakhal** [comment]
@NagyDonat You might be also interested in this, as you are using the docs of CSA.

**Comment by komalverma04** [comment]
I will work on it.
