### ISSUE TITLE
[libc++] Add a static_assert for the Mandates in extents for char

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#73715]
> @crtrott Can you follow-up on adding a `static_assert` for the mandate? We should do this sooner rather than later since it'll prevent people from starting to rely on this.

_Originally posted by @ldionne in https://github.com/llvm/llvm-project/issues/73535#issuecomment-1828427296_

As explained by Stephan,

[N4964](https://wg21.link/N4964) [mdspan.extents.overview]/1.1 says:

```c++
template<class IndexType, size_t... Extents>
class extents {
[...]
```

Mandates:

`IndexType` is a signed or unsigned integer type [...]

This famously excludes char.

[basic.fundamental]/1, /2, /7:
> There are five standard signed integer types: "signed char", "short int", "int", "long int", and "long long int". [...] The standard and extended signed integer types are collectively called signed integer types.
> For each of the standard signed integer types, there exists a corresponding (but different) standard unsigned integer type: "unsigned char", "unsigned short int", "unsigned int", "unsigned long int", and "unsigned long long int". [...] The standard and extended unsigned integer types are collectively called unsigned integer types.
> Type char is a distinct type that has an implementation-defined choice of "signed char" or "unsigned char" as its underlying type.

**Comment by crtrott** [comment]
Will do, sorry I didn't get to it yet.

**Comment by ldionne** [comment]
No worries, just filing an issue so it doesn't get lost.

**Comment by frederick-vs-ja** [comment]
#78086 provided the exact utility (`__libcpp_integer`) to diagnose this.
