### ISSUE TITLE
[RISCV] Remove setting the Value of the MemOperand to null in RISCVTargetLowering::LowerFormalArguments

### ISSUE THREAD

**Issue by michaelmaitland** [llvm/llvm-project#73735]
It is unclear why the following code exists in `RISCVTargetLowering::LowerFormalArguments`:

```
cast<StoreSDNode>(Store.getNode())
->getMemOperand()
->setValue((Value *)nullptr);
```

It is being introduced into GISel in https://github.com/llvm/llvm-project/pull/73064/ for parity reasons.

@asb could you provide some context on why it was originally needed? Can it be removed in both SDAG and GISel?

**Comment by topperc** [comment]
The only other target that does this is Mips. But I couldn't figure out why they did it either. There is nothing in the commit history that explains it.

**Comment by topperc** [comment]
I've rewritten the code to create a single frame object for all GPRs in 3c5b42acd3e2022da40f6e4b50f5035279b8b93a. That's what ARM and AArch64 do. I'm hoping thats enough to fix any concern about having the MachinePointerInfo tracking the location. So I've removed the setValue(nullptr)
