### ISSUE TITLE
fix suggestion for -Wreorder

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7379]
|  |  |
| --- | --- |
| Bugzilla Link | [7007](https://llvm.org/bz7007) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
In the case that clang gives some -Wreorder warning like this:

In file included from /Users/az/Programmierung/openlierox/src/gusanos/gui/detail/gss.cpp:12:
GUI/detail/gss-grammar.h.re:249:23: warning: field 'begin' will be initialized after field 'marker' [-Wreorder]
TGrammar() : cur(-1), begin(0), marker(0), buffer(0), curp(0), limit(0), line(1), syncTokens(false), ...
                      ^

It would be nice if it also automatically outputs the code which would fix this. In case you have several such warnings for a single constructor (because the order is completely wrong), it's annoying to fix it by hand.

**Comment by philnik777** [comment]
This got fixed in Clang 13: https://godbolt.org/z/4EGzr5WTz
