### ISSUE TITLE
Changing borrowed range status of test class does not change outcome of test (std::ranges::transform_view)

### ISSUE THREAD

**Issue by hawkinsw** [llvm/llvm-project#73800]
In the CTAD tests for `std::ranges::transform_view`, changing whether the `BorrowedRange` test class is a actually borrowed does not seem to change the outcome of the tests. In other words, if I remove the `enable_borrowed_range` on lines 37 and 38 [1], the test still seems to pass. I am _sure_ that I am missing something, but would love to be educated on what that is!

Once I understand the problem, I would absolutely *love* to help fix it! 

[1] https://github.com/llvm/llvm-project/blob/9b192596ded4982ea360e70f723f9d05dc456ec0/libcxx/test/std/ranges/range.adaptors/range.transform/ctad.compile.pass.cpp#L37

> Note: This situation appears to happen for the `site::ranges::join_view`, too, but I haven't confirmed that locally.

**Comment by ldionne** [comment]
If you remove `enable_borrowed_range`, then you're left with a normal range i.e. the same as the struct just above:

```c++
struct Range {
  int *begin() const;
  int *end() const;
};
```

We expect this to work too. I haven't checked whether exercising coverage for borrowed ranges is extremely useful in that CTAD test, but it probably doesn't hurt.

**Comment by ldionne** [comment]
IOW -- I think we can either do nothing or convince ourselves that coverage for borrowed ranges is useless in that test, and then remove that bit.

**Comment by hawkinsw** [comment]
That is *exactly* what I thought from reading the test -- IOW, when I was reading the standard, I saw no reason to have that check in there (i.e., I saw nothing that would change the behavior [e.g., okay, now I am just seeing how many levels of parenthesis-like grouping things I have in one sentence]). :-)

**Comment by ldionne** [comment]
If you care strongly about it, feel free to submit a patch but please make sure to justify the removal by explaining why it's not necessary from the standard. IMO it doesn't hurt to leave it there as additional coverage but I'm mostly neutral.

**Comment by ldionne** [comment]
No worries, thanks for checking. Tentatively closing since this was a question and it's been answered, and IIUC there's no additional action item.
