### ISSUE TITLE
Error on precompiling AOT

### ISSUE THREAD

**Issue by evertefeuille** [llvm/llvm-project#73843]
Severity	Code	Description	Project	File	Line	Suppression State	Priority
Error		Precompiling failed for C:\Donnees\Projets\WorkInstruction.Maui\WorkInstruction.Maui\obj\Release\net8.0-android\android-arm\linked\Telerik.Documents.Flow.dll with exit code 1.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: "C:\\\\Program Files\\\\dotnet\\\\packs\\\\Microsoft.Android.Sdk.Windows\\\\34.0.43\\\\tools\\\\binutils\\\\bin\\\\llvm-mc.exe" --arch=arm --triple=arm-linux-gnu --assemble --filetype=obj --mattr=+armv7-a,+vfp3 -o=obj\\\\Release\\\\net8.0-android\\\\android-arm\\\\Telerik.Documents.Flow.dll.tmp\\\\temp.s.o obj\\\\Release\\\\net8.0-android\\\\android-arm\\\\Telerik.Documents.Flow.dll.tmp\\\\temp.s
Exception Code: 0xC0000005
0x00007FF63DB361A0, C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\binutils\bin\llvm-mc.exe(0x00007FF63D910000) + 0x2261A0 byte(s)
0x00007FF63DB38A3D, C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\binutils\bin\llvm-mc.exe(0x00007FF63D910000) + 0x228A3D byte(s)
0x00007FF63D9209A1, C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\binutils\bin\llvm-mc.exe(0x00007FF63D910000) + 0x109A1 byte(s)
0x00007FF63DB3D6F1, C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\binutils\bin\llvm-mc.exe(0x00007FF63D910000) + 0x22D6F1 byte(s)
0x00007FF63DB3A1FF, C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\binutils\bin\llvm-mc.exe(0x00007FF63D910000) + 0x22A1FF byte(s)
0x00007FF63DB51AEE, C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\binutils\bin\llvm-mc.exe(0x00007FF63D910000) + 0x241AEE byte(s)
0x00007FF63DB3DB2B, C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\binutils\bin\llvm-mc.exe(0x00007FF63D910000) + 0x22DB2B byte(s)
0x00007FF63D918935, C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\binutils\bin\llvm-mc.exe(0x00007FF63D910000) + 0x8935 byte(s)
0x00007FF63D91BCF7, C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\binutils\bin\llvm-mc.exe(0x00007FF63D910000) + 0xBCF7 byte(s)
0x00007FF63DBB8A10, C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\binutils\bin\llvm-mc.exe(0x00007FF63D910000) + 0x2A8A10 byte(s)
0x00007FFA2962257D, C:\WINDOWS\System32\KERNEL32.DLL(0x00007FFA29610000) + 0x1257D byte(s), BaseThreadInitThunk() + 0x1D byte(s)
0x00007FFA2B44AA58, C:\WINDOWS\SYSTEM32\ntdll.dll(0x00007FFA2B3F0000) + 0x5AA58 byte(s), RtlUserThreadStart() + 0x28 byte(s)
Running: "C:\\Program Files\\dotnet\\packs\\Microsoft.Android.Sdk.Windows\\34.0.43\\tools\\binutils\\bin\\llvm-mc.exe" --arch=arm --triple=arm-linux-gnu --assemble --filetype=obj --mattr=+armv7-a,+vfp3 -o=obj\Release\net8.0-android\android-arm\Telerik.Documents.Flow.dll.tmp\temp.s.o obj\Release\net8.0-android\android-arm\Telerik.Documents.Flow.dll.tmp\temp.s
AOT of image C:\Donnees\Projets\WorkInstruction.Maui\WorkInstruction.Maui\obj\Release\net8.0-android\android-arm\linked\Telerik.Documents.Flow.dll failed.
Mono Ahead of Time compiler - compiling assembly C:\Donnees\Projets\WorkInstruction.Maui\WorkInstruction.Maui\obj\Release\net8.0-android\android-arm\linked\Telerik.Documents.Flow.dll
AOTID 1B45F37E-F830-C4FC-9771-FCB43DA8BBFA
Using profile data file 'C:\Users\ericv\.nuget\packages\microsoft.maui.controls.build.tasks\8.0.3\buildTransitive\netstandard2.0\maui.aotprofile'
Using profile data file 'C:\Users\ericv\.nuget\packages\microsoft.maui.controls.build.tasks\8.0.3\buildTransitive\netstandard2.0\maui-blazor.aotprofile'
Added 0 methods from profile.
Added 0 methods from profile.
Compiled: 600/600
Executing the native assembler: "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\binutils\bin\arm-linux-androideabi-as"   -mfpu=vfp3 -o obj\Release\net8.0-android\android-arm\Telerik.Documents.Flow.dll.tmp\temp.s.o obj\Release\net8.0-android\android-arm\Telerik.Documents.Flow.dll.tmp\temp.s	WorkInstruction.Maui	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\targets\Microsoft.Android.Sdk.Aot.targets	109		Normal

**Comment by asl** [comment]
Please provide a reproducer. You might also want to submit this issue to Mono bugtracker at first

**Comment by evertefeuille** [comment]
All works well this morning, i don't know why. You can close this issue.

Thanks.
