### ISSUE TITLE
[libc++][test] Streaming out floating-point `sys_time` and `local_time` is bogus

### ISSUE THREAD

**Issue by StephanTLavavej** [llvm/llvm-project#73849]
[N4964](https://isocpp.org/files/papers/N4964.pdf) \[time.clock.system.nonmembers\]/1:

> ```cpp
> template<class charT, class traits, class Duration>
>   basic_ostream<charT, traits>&
>     operator<<(basic_ostream<charT, traits>& os, const sys_time<Duration>& tp);
> ```
> *Constraints:* `treat_as_floating_point_v<typename Duration::rep>` is `false`, and `Duration{1} < days{1}` is `true`.

forbids:

https://github.com/llvm/llvm-project/blob/002c54a2e6cced2eb9d79608afee5fb36dcc5b98/libcxx/test/std/time/time.clock/time.clock.system/ostream.pass.cpp#L93-L98
https://github.com/llvm/llvm-project/blob/002c54a2e6cced2eb9d79608afee5fb36dcc5b98/libcxx/test/std/time/time.clock/time.clock.system/ostream.pass.cpp#L131-L136

---

And \[time.clock.local\]/2:

> ```cpp
> template<class charT, class traits, class Duration>
>   basic_ostream<charT, traits>&
>     operator<<(basic_ostream<charT, traits>& os, const local_time<Duration>& lt);
> ```
> *Effects:* `os << sys_time<Duration>{lt.time_since_epoch()};`

forbids:

https://github.com/llvm/llvm-project/blob/002c54a2e6cced2eb9d79608afee5fb36dcc5b98/libcxx/test/std/time/time.clock/time.clock.local/ostream.pass.cpp#L93-L98
https://github.com/llvm/llvm-project/blob/002c54a2e6cced2eb9d79608afee5fb36dcc5b98/libcxx/test/std/time/time.clock/time.clock.local/ostream.pass.cpp#L132-L137

**Comment by mordante** [comment]
Thanks! I had a look and it seems I didn't implement the required constraint. So it's not just the test suite, the implementation has issues too.
