### ISSUE TITLE
[InstCombine] Missing optimization : fold `mul (phi a, b), (phi b, a)` to `mul a, b`

### ISSUE THREAD

**Issue by XChy** [llvm/llvm-project#73905]
Similar to #73904

Alive2 proof: https://alive2.llvm.org/ce/z/RDGBSJ
Missed example: https://godbolt.org/z/9qK8G8o16

### Description:
```llvm
define i8 @src(i1 %c, i8 %a, i8 %b)  {
entry:
  br i1 %c, label %then, label %end
then:
  call void @dummy()
  br label %end
end:
  %phi1 = phi i8 [%a, %entry], [%b, %then]
  %phi2 = phi i8 [%b, %entry], [%a, %then]
  %mul = mul i8 %phi1, %phi2
  ret i8 %mul
}
```
can be folded to:
```llvm
define i8 @tgt(i1 %c, i8 %a, i8 %b) {
entry:
  br i1 %c, label %then, label %end
then:
  call void @dummy()
  br label %end
end:
  %mul = mul i8 %a, %b
  ret i8 %mul
}
```

### Real-world motivation

This snippet of IR is derived from [src/redis/evict.c](https://github.com/redis/redis/blob/unstable/src/evict.c) (after O3 pipeline).
The example above is a reduced version. If you're interested in the original suboptimal IR and optimal IR, see also:

**Let me know if you can confirm that it's an optimization opportunity, thanks.**

**Comment by nikic** [comment]
Nice find! Also applies to other commutative operators.

**Comment by sun-jacobi** [comment]
@XChy  @nikic  Hi, can I work on this issue?

**Comment by sun-jacobi** [comment]
By @nikic 

This optimization should also work for phi nodes with more than 2 incoming values.
Alive2 proof: https://alive2.llvm.org/ce/z/2P8gq-
