### ISSUE TITLE
[InstCombine] Missing optimization: fold `mul (select a, b), (select b, a)` to `mul a, b`

### ISSUE THREAD

**Issue by XChy** [llvm/llvm-project#73904]
Alive2 proof: https://alive2.llvm.org/ce/z/kQGt-z

### Description:

```llvm
define i8 @src(i1 %c, i8 %a, i8 %b) {
  %.sink = select i1 %c, i8 %a, i8 %b
  %add.sink = select i1 %c, i8 %b, i8 %a
  %mul4 = mul i8 %add.sink, %.sink
  ret i8 %mul4
}
```
can be folded to:
```llvm
define i8 @tgt(i1 %c, i8 %a, i8 %b) {
  %mul = mul i8 %a, %b
  ret i8 %mul
}
```
Similarly, for any commutative binary operator like `add`, it's correct too.

### Real-world motivation

This snippet of IR is derived from [redis/src/evict.c](https://github.com/redis/redis/blob/unstable/src/evict.c) (after O3 pipeline).
The example above is a reduced version. If you're interested in the original suboptimal IR and optimal IR, see also:https://godbolt.org/z/v5G3hvs87

**Let me know if you can confirm that it's an optimization opportunity, thanks.**

**Comment by snikitav** [comment]
May I take this one?

**Comment by snikitav** [comment]
@dtcxzyw PTAL #74953
