### ISSUE TITLE
[OpenMP] link omp error when build with clang

### ISSUE THREAD

**Issue by Abbyyan** [llvm/llvm-project#73912]
I'm building clang with code verision [17.0.4](https://github.com/llvm/llvm-project/releases/tag/llvmorg-17.0.4) on centos7. The cmake command is as follows
```
cmake -DLLVM_ENABLE_PROJECTS="clang;openmp;clang-tools-extra;lld" -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi"  -DCMAKE_C_COMPILER=$prefix/gcc7/bin/gcc -DCMAKE_CXX_COMPILER=$prefix/gcc7/bin/g++  -DCMAKE_C_FLAGS=-L$prefix/gcc7/lib64 -DCMAKE_CXX_FLAGS=-L$prefix/gcc7/lib64 -DCMAKE_CXX_LINK_FLAGS="-L$prefix/gcc7/lib64 -Wl,-rpath,$prefix/gcc7/lib64" -DGCC_INSTALL_PREFIX=$prefix/gcc7 -DCMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX=$prefix/clang17.0.4 -G "Unix Makefiles" ../llvm
```
but it cored in the link process, the erros msg is 
```
/bin/ld:../common/PluginInterface/CMakeFiles/PluginInterface.dir/PluginInterface.cpp.o:relocationRX8664PC32againstprotectedsymbol _tyt_rtl_data_submit_async' can not be used when making a shared object 
```
![image](https://github.com/llvm/llvm-project/assets/12140508/b53577c9-2951-4cde-b822-075d923f09b2)
Seems like somethings wrong with openmp. Is there any suggestions or debug method i can do please? Hope for your help, thanks a lot.

**Comment by DimitryAndric** [comment]
Is there any particular reason for using CentOS 7? I would recommend trying a newer version, such as CentOS 9 (or Rocky Linux 9), which has much more up-to-date development tools.

**Comment by shiltian** [comment]
@MaskRay is this an existing issue in older version of `ld`?

**Comment by MaskRay** [comment]
This GNU ld error is likely due to not-well-handled protected symbols in binutils.

    __attribute__((visibility("protected"))) void *foo() {
      return (void *)foo;
    }

    // gcc -fpic -shared -fuse-ld=bfd
    relocation R_X86_64_PC32 against protected symbol `foo' can not be used when making a shared object

I have fixed GNU ld's aarch64 and x86 port in 2022, e.g. https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=d19a265487eda186b6977d9d15648cda9fad3298

**Comment by shiltian** [comment]
Based on @MaskRay this is unlikely an OpenMP issue. Close it for now.
