### ISSUE TITLE
memset doesn't initialize the padding bytes of float3

### ISSUE THREAD

**Issue by ahatanak** [llvm/llvm-project#74001]
$ cat test.c
```c
#include <string.h>

typedef __attribute__((__ext_vector_type__(3))) float float3;

float3 make_float3(float x, float y, float z) {
  float3 r;
  memset(&r, 0, sizeof(float3));
  r.x = x;
  r.y = y;
  r.z = z;
  return r;
}
```
The size of float3 is 16-bytes and the padding bytes should be set to zero, but they aren't.

$ clang -S -o -  test.c -Os -emit-llvm
```ll
define <3 x float> @make_float3(float noundef %0, float noundef %1, float noundef %2) local_unnamed_addr #0 {
  %4 = insertelement <3 x float> undef, float %0, i64 0
  %5 = insertelement <3 x float> %4, float %1, i64 1
  %6 = insertelement <3 x float> %5, float %2, i64 2
  ret <3 x float> %6
}
```

This makes it impossible to compare buffers of float3 objects byte-wise.

**Comment by ahatanak** [comment]
The problem is that a byte-wise comparison like `memcmp` cannot be used to compare two buffers of `float3` because `sizeof(float3)` is 16 and `make_float3` doesn't initialize the padding bytes (i.e., the last 4 bytes). AFAIK, there's no easy way to initialize the padding bytes. 

For example, the following code doesn't work if the `float3` elements are initialized using `make_float3` because the padding bytes contain garbage.

```
float3 array0[16], array1[16];

int compare_float3() {
  return memcmp(array0, array1, sizeof(float3) * 16);
}
```

Compare that to the following struct, which is also 16 bytes and has three float fields:

```
typedef struct __attribute__((aligned(16))) {
  float x, y, z;
} S;

S make_S(float x, float y, float z) {
  S r;
  memset(&r, 0, sizeof(S));
  r.x = x;
  r.y = y;
  r.z = z;
  return r;
} 
```

The padding bytes are zero-initialized in that case.

```
define i128 @make_S(float noundef %0, float noundef %1, float noundef %2) local_unnamed_addr #3 {
  %4 = bitcast float %0 to i32
  %5 = bitcast float %1 to i32
  %6 = bitcast float %2 to i32
  %7 = zext i32 %6 to i128
  %8 = shl nuw nsw i128 %7, 64
  %9 = zext i32 %5 to i128
  %10 = shl nuw nsw i128 %9, 32
  %11 = or i128 %8, %10
  %12 = zext i32 %4 to i128
  %13 = or i128 %11, %12
  ret i128 %13
}
```

**Comment by nikic** [comment]
> The problem is that a byte-wise comparison like `memcmp` cannot be used to compare two buffers of `float3` because `sizeof(float3)` is 16 and `make_float3` doesn't initialize the padding bytes (i.e., the last 4 bytes). AFAIK, there's no easy way to initialize the padding bytes.

You cannot compare structures that have padding with memcmp.

Just to be clear, if you do a memset that includes the padding, that will set the padding as well. But if you then perform a by value copy (as you do by returning it), then that will obviously not copy the padding.
