### ISSUE TITLE
LiveOutRegInfo doesn't handle PHI's: Redundant "andl $1, %eax"

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7408]
|  |  |
| --- | --- |
| Bugzilla Link | [7036](https://llvm.org/bz7036) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @sunfishcode |

## Extended Description 
[Linux/amd64, LLVM r100854]

LLVM seems to like adding a redundant "andl $1, %eax" instruction in the code generated (via clang) for the C code:

------------------------------------------------------------

extern int f();
int test(int a) { return a && f(); }

------------------------------------------------------------

define i32 @&#8203;test(i32 %a) nounwind {
entry:
  %tobool = icmp eq i32 %a, 0                     ; <i1> [#uses=1]
  br i1 %tobool, label %land.end, label %land.rhs

land.rhs:                                         ; preds = %entry
  %call = tail call i32 (...)* @&#8203;f() nounwind      ; <i32> [#uses=1]
  %tobool1 = icmp ne i32 %call, 0                 ; <i1> [#uses=1]
  br label %land.end

land.end:                                         ; preds = %entry, %land.rhs
  %0 = phi i1 [ false, %entry ], [ %tobool1, %land.rhs ] ; <i1> [#uses=1]
  %land.ext = zext i1 %0 to i32                   ; <i32> [#uses=1]
  ret i32 %land.ext
}

------------------------------------------------------------

test:
.Leh_func_begin1:
        pushq   %rbp
.Ltmp0:
        movq    %rsp, %rbp
.Ltmp1:
        testl   %edi, %edi
        jne     .LBB1_2
        xorb    %al, %al
        jmp     .LBB1_3
.LBB1_2:
        xorb    %al, %al
        callq   f
        testl   %eax, %eax
        setne   %al
.LBB1_3:
        movzbl  %al, %eax
        andl    $1, %eax
        popq    %rbp
        ret

------------------------------------------------------------

**Comment by arsenm** [comment]
No andl $1 here:

```
	.type	test,@function
test:                                   # @test
# %bb.0:                                # %entry
	testl	%edi, %edi
	je	.LBB0_1
# %bb.2:                                # %land.rhs
	pushq	%rax
	callq	f@PLT
	testl	%eax, %eax
	setne	%al
	addq	$8, %rsp
	movzbl	%al, %eax
	retq
.LBB0_1:
	xorl	%eax, %eax
	movzbl	%al, %eax
	retq
.Lfunc_end0:
	.size	test, .Lfunc_end0-test
                                        # -- End function
	.section	".note.GNU-stack","",@progbits

```
