### ISSUE TITLE
Suboptimal code generation around `__builtin_clz`

### ISSUE THREAD

**Issue by amotzop** [llvm/llvm-project#74101]
You can use `__builtin_clz` to calculate the integer part of `log2(integer)` as `ilog(num) = 31 - __builtin_clz(num)` which produces a single `bsr` instruction (on x86-64).
However, if you add 1 to the result it uses a `xor` and `add` instructions after the `bsr` instead of just using a single `add` or `inc` instruction ([godbolt](https://godbolt.org/z/xavKh5n9T) example, [quick-bench](https://quick-bench.com/q/NduZQs_oSySAldBvjlfhsmjZqII) comparison) .
(This is just one example, but it seems to be also true for other arithmetic operations)

I think this comes from the IR representing `__builtin_clz` as an "atomic" operation, but in reality it's expanded into two instructions.

**Comment by SchrodingerZhu** [comment]
The thing happens as following:
```c++
unsigned int ilog2_plus_1(unsigned int num) {
    return 31  - __builtin_clz(num) + 1;
}
```
constant folded into:
```c++
unsigned int ilog2_plus_1(unsigned int num) {
    return 32  - __builtin_clz(num) ;
}
```

**Comment by amotzop** [comment]
It doesn't seem to be fixed (I'm looking at compiler explorer with the `clang (trunk)`, which should be new enough)

**Comment by RKSimon** [comment]
godbolt can take a few days to update to trunk latest - check the hash if you can? else try again on Monday. I'll see if I can confirm the fix locally when I'm back at my desktop machine.

**Comment by RKSimon** [comment]
@amotzop https://gcc.godbolt.org/z/hnqM34oz1 - this seems to show that its been fixed - please can you confirm?
