### ISSUE TITLE
Analyzer should honor __attribute__((const))

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7417]
|  |  |
| --- | --- |
| Bugzilla Link | [7045](https://llvm.org/bz7045) |
| Version | unspecified |
| OS | All |
| Attachments | [Minimal test case](https://user-images.githubusercontent.com/60944935/143741279-176eea14-ba67-474d-8775-a00d663288e6.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Hi,

clang static analyzer should honor __attribute__((const)) - see the attached test case.
tested with ANALYZER BUILD: checker-240 (2010-04-11 10:44:34)

Attaching a minimal test case. The real case (from which the test case is derived) had "strcmp" as the "const" function. Since in string.h, strcmp is not tagged as "const", this raises another and separate problem and that is tagging all "const" functions accordingly (using the macro __pure2, like I have seen), so that the proposed functionality becomes usable.

Attribute "pure" might also be worth looking at, but I am not sure it's OK to do the same thing with it as I proposed with "const".

**Comment by JOE1994** [comment]
With `Clang 17.0.1`, false positive error is no longer emitted by static analyzer:

* https://godbolt.org/z/4nh1TGxsh
