### ISSUE TITLE
[flang] flang-new: error: unknown argument: '-fprofile-generate'

### ISSUE THREAD

**Issue by foxtran** [llvm/llvm-project#74208]
I have tried to build Fortran application with Profile-Guided Optimization (PGO).
I used the following command:
```
flang-new test.f90 -c -fprofile-generate -g
```

Unfortunately, compilation was failed with the following message:
```
flang-new: error: unknown argument: '-fprofile-generate'
```

Used version:
```
flang-new --version
flang-new version 18.0.0 (https://github.com/llvm/llvm-project.git 9584f5834499e6093797d4a28fde209f927ea556)
```

**Comment by EugeneZelenko** [comment]
@foxtran: Could you please elaborate?

**Comment by foxtran** [comment]
@EugeneZelenko, see #74216
