### ISSUE TITLE
[LICM] TSVC s113: not vectorized because LICM doesn't work

### ISSUE THREAD

**Issue by yus3710-fj** [llvm/llvm-project#74262]
Flang can't vectorize the loop in `s113` of [TSVC](https://www.netlib.org/benchmark/vectors) while Clang can vectorize the loop written in C.

```fortran
! Fortran version
      do 1 nl = 1,ntimes
      do 10 i = 2,n
        a(i) = a(1) + b(i)
   10 continue
      call dummy(ld,n,a,b,c,d,e,aa,bb,cc,1.)
   1  continue
```

```c
// C version
for (int nl = 0; nl < ntimes; nl++) {
  for (int i = 1; i < n; i++) {
    a[i] = a[0] + b[i];
  }
  dummy(a, b, c, d, e, aa, bb, cc, 0.);
}
```

```console
$ flang-new -v -Ofast s113.f -S -Rpass=licm\|vector -falias-analysis
flang-new version 18.0.0 (https://github.com/llvm/llvm-project.git 1c1227846425883a3d39ff56700660236a97152c)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /path/to/install/bin
Found candidate GCC installation: /path/to/lib/gcc/aarch64-unknown-linux-gnu/11.2.0
Selected GCC installation: /path/to/lib/gcc/aarch64-unknown-linux-gnu/11.2.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/path/to/install/bin/flang-new" -fc1 -triple aarch64-unknown-linux-gnu -S -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -pic-is-pie -ffast-math -target-cpu generic -target-feature +neon -target-feature +v8a -fstack-arrays -fversion-loops-for-stride -falias-analysis -Rpass=vector -O3 -o s113.s -x f95-cpp-input s113.f
$ clang -Ofast s113.c -Rpass=licm\|vector
/path/to/s113.c:16:11: remark: hoisting load [-Rpass=licm]
   16 |                         a[i] = a[0] + b[i];
      |                                ^
/path/to/s113.c:15:3: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
   15 |                 for (int i = 1; i < LEN; i++) {
      |                 ^
```

It can be reproduced with the following C code which is the same program as the above C code essentially.

```c
// C version
for (int nl = 0; nl < ntimes; nl++) {
  for (int i = 2; i <= n; i++) {
    a[i-1] = a[0] + b[i-1];
  }
  dummy(a, b, c, d, e, aa, bb, cc, 0.);
}
```

Actually, Flang generates LLVM IR like this C code.

LICM is necessary for vectorization because LoopAccessAnalysis can't analyze `a[0]` correctly.
It seems that LICM doesn't work due to the linear expression in indices of arrays.

**Comment by yus3710-fj** [comment]
Thank you for the information.
This issue isn't resolved even if `-falias-analysis` is enabled.

At the moment, I think this is the issue of alias analysis in LLVM itself, not the way alias information is passed from Flang to LLVM.

**Comment by tblah** [comment]
Thank you for confirming

**Comment by yus3710-fj** [comment]
One reason is that the offset value of GEP gets wrong if there is a negative value in a binary operation.

Here is the IR of the loop:

```llvm
for.body4:                                        ; preds = %for.cond1
  %0 = load float, ptr @a, align 16, !dbg !30, !tbaa !31
  %sub = add nsw i32 %i.0, -1, !dbg !35
  %idxprom = sext i32 %sub to i64, !dbg !36
  %arrayidx = getelementptr inbounds [32000 x float], ptr @b, i64 0, i64 %idxprom, !dbg !36
  %1 = load float, ptr %arrayidx, align 4, !dbg !36, !tbaa !31
  %add = fadd float %0, %1, !dbg !37
  %arrayidx7 = getelementptr inbounds [32000 x float], ptr @a, i64 0, i64 %idxprom, !dbg !38
  store float %add, ptr %arrayidx7, align 4, !dbg !39, !tbaa !31
  %inc = add nuw nsw i32 %i.0, 1, !dbg !40
  br label %for.cond1, !dbg !16, !llvm.loop !41
```

BasicAliasAnalysis is invoked in the LICM pass to check whether `a[i-1]` and `a[0]` alias each other, and the offset of GEP is calculated.
`i-1` must be represented as `LinearExpression` but `-1` can't be represented as `APInt` because `APInt` can only represent unsigned values.
As a result, the offset of GEP isn't calculated correctly.

https://github.com/llvm/llvm-project/blob/db78c30ba772af1466bb0d0c1d376c8e642ee4a9/llvm/lib/Analysis/BasicAliasAnalysis.cpp#L371-L373

There seems to be another problem because LICM doesn't work even though `add nsw i32 %i.0, -1` is changed into `sub nsw i32 %i.0, 1`.

**Comment by yus3710-fj** [comment]
BasicAliasAnalysis is invoked in the LICM pass to check whether `a[i-1]` and `a[0]` alias each other.
But BasicAA doesn't have the information of loops, so the access range of `a[i-1]` isn't calculated correctly.

https://github.com/llvm/llvm-project/blob/6615581526f62a00833b2d60cc31f7f12497b5ff/llvm/lib/Analysis/BasicAliasAnalysis.cpp#L1221-L1226

According to BasicAA, the range of `a[i-1]` is `[-4,8589934588)` and that of `a[0]` is `[0,4)` so they are overlapping.
This is wrong because the true range of `a[i-1]` is `[4,8589934588)`.

**Comment by yus3710-fj** [comment]
Hello, @fhahn and @nikic.
I found you commented on some issues about LICM, so please let me ask you for your advices.

I have no idea what I should fix to resolve this issue, so please let me clarify whether I should fix BasicAA at first.
I'd like to know whether the above behavior of BasicAA is what it's expected.
I'm not sure BasicAA should handle with analysis for indices of arrays. IIUC, alias analysis is used to determine whether two different variables can point the same memory location, that is alias analysis doesn't have to handle with indices of the same array.
If so, I can say I should fix LICM or LAA to resolve this issue.

**Comment by nikic** [comment]
In principle, improving BasicAA to determine that these don't alias would be the right fix. We *might* be willing to accept some crude range analysis for simple recurrences, if it is reasonably simple and has no impact on compile-time.

**Comment by yus3710-fj** [comment]
Thank you for your helpful comment.
I started to consider fixing `computeConstantRange` which is called from BasicAA. If the change makes an influence on some other passes calling it, I'll consider another fix.

**Comment by yus3710-fj** [comment]
There seems to be another solution (loop canonicalization + `inbounds` on GEP).

**Comment by Leporacanthicus** [comment]
> The loop is vectorized without LICM by #92307.

Does that mean this can be closed, or is there still work needed for this ticket?

**Comment by yus3710-fj** [comment]
LICM doesn't work yet, but it would be a separate issue. So, I closed this issue.
Thank you for your comment.
