### ISSUE TITLE
[InstCombine] Missing optimzation: fold `(b + ~a) > 0` to `a - b ＜ -1`

### ISSUE THREAD

**Issue by XChy** [llvm/llvm-project#74302]
Alive2 proof: https://alive2.llvm.org/ce/z/VSii3o

### Description:
```llvm
define i1 @src(i32 %a, i32 %b) {
entry:
  %i10 = xor i32 %a, -1
  %sub2.le = add i32 %b, %i10
  %cmp = icmp sgt i32 %sub2.le, 0
  ret i1 %cmp
}
```
could be folded to:
```llvm
define i1 @src(i32 %a, i32 %b) {
entry:
  %notsub = sub i32 %a, %b
  %cmp = icmp slt i32 %notsub, 4294967295
  ret i1 %cmp
}
```

### Real-world motivation

This snippet of IR is derived from [redis/src/cluster.c@restoreCommand](https://github.com/redis/redis/blob/8a4ccb01b3ea3072eae6ef3e513b0b24b11a85ae/src/cluster.c#L197) (after O3 pipeline).
The example above is a reduced version. If you're interested in the original suboptimal IR and optimal IR, see also:https://godbolt.org/z/Tz8sEfYEb

**Let me know if you can confirm that it's an optimization opportunity, thanks.**

**Comment by nikic** [comment]
Sounds like a generalization of this family of folds https://github.com/llvm/llvm-project/blob/853682cc19e26964383af9e834215fae5966b140/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp#L7040-L7066 to use isFreeToInvert() -- to avoid infinite loops, under a ConsumesOp condition.

**Comment by pinskia** [comment]
Note there might be an undefinedness though. Try `b == 0` and `a == INT_MIN` before we would get `0+INT_MAX` which is defined but then afterwards you would get `0 - INT_MIN` which would be undefined. I am not 100% sure about LLVM's IR to know if sub/add has wrapping or signed integer overflow behavior to know if this would be valid though.

**Comment by XChy** [comment]
> I am not 100% sure about LLVM's IR to know if sub/add has wrapping or signed integer overflow behavior to know if this would be valid though.

LLVM uses `nuw` and `nsw` flags to constraint whether one operation can have unsigned/signed wrapping.
As for your example, I'm afraid that the correct form is `INT_MIN - 0` but not `0 - INT_MIN`. The fold here is `(b + ~a) > 0` to `a - b ＜ -1`. Thus, I think it's a valid fold with alive2 proof.
