### ISSUE TITLE
[clang-format]: Feature Request: AlignConsecutiveDeclarations option to ignore function prototypes

### ISSUE THREAD

**Issue by bradh352** [llvm/llvm-project#74320]
We recently started using clang-format in the c-ares project: https://github.com/c-ares/c-ares/blob/main/.clang-format

We have "AlignConsecutiveDeclarations" enabled, which yields nicely formatted variable declarations.  However, since we have a coding style requirement of 80 columns, function prototype alignment actually appears to cause more harm than good from a readability standpoint.  Due to the line limit restrictions, the formatting is inconsistent at best, aligning some parameter members and not others. 

Our feature request would be a flag to disable function prototypes from this alignment option.

**Comment by huiskes** [comment]
I would like to second this request. Based on the documentation you would also not expect the alignment of function parameter declarations in the first place.

**Comment by bradh352** [comment]
just checking in on this request :)
