### ISSUE TITLE
[clang] non-system clang compiler couldn't use/find system compiler-rt

### ISSUE THREAD

**Issue by MehdiChinoune** [llvm/llvm-project#74363]
When building a clang compiler with `-DCLANG_DEFAULT_RTLIB=compiler-rt` It finds the system compiler-rt and links against it, but after installation it couldn't use/find the system compiler-rt and wants a compiler-rt that exist in its installation path.
```
ld: error: could not open 'C:/_/B/src/build-CLANG64-instrument/lib/clang/17/lib/windows/libclang_rt.builtins-x86_64.a': No such file or directory
```
This doesn't happen with both libc++ and libunwind when clang configured to use them (`-DCLANG_DEFAULT_UNWINDLIB=libunwind -DCLANG_DEFAULT_CXX_STDLIB=libc++`), So something wrong with compiler-rt searching method.
Why does clang link and use any system libgcc/gcc_eh library, but requires compiler-rt to be installed in the same path.

I think the issue comes from
https://github.com/llvm/llvm-project/blob/6886a52d6dbefff77f33de12ff85d654e2557f81/clang/lib/Driver/ToolChain.cpp#L660
and
https://github.com/llvm/llvm-project/blob/6886a52d6dbefff77f33de12ff85d654e2557f81/clang/lib/Driver/ToolChain.cpp#L670
because It uses `llvm::sys::path` to search in.

**Comment by EugeneZelenko** [comment]
@MehdiChinoune: Please elaborate.
