### ISSUE TITLE
Issue with running loop-flatten pass

### ISSUE THREAD

**Issue by cxjiang-bk** [llvm/llvm-project#74393]
Hi there! I have trouble running the loop-flatten pass. I tried to run that pass using `opt -passes="loop-flatten ./<InputFile> -S -o ./<OutputFile>"` and my c++ test file is 
int array[1024];

int foo() { 
    int b = 0;
    for(int i = 0; i<1024; i++){
        for(int j = 0; j<1024; j++){
            b += array[i+j];
        }
    }
    return b; 
},
I compile it using clang and the command is `clang -O1 -S -emit-llvm -Xclang -disable-O0-optnone -fno-discard-value-names ./input.c -o ./input.ll`. But after I check the output file, it seems that it didn't do the flatten job. Is there anything wrong with my invoke method? Or am I missing some prerequisite passes? Thanks!

**Comment by ParkHanbum** [comment]
try this command
`opt --passes='loop(loop-flatten),verify' -verify-loop-info -verify-dom-info -verify-scev test.ll `

you can find usage of loop-flatten pass from `llvm/test/Transforms/loop-flatten.ll`. it is common that writing usage for pass to top of test .ll file.

**Comment by cxjiang-bk** [comment]
Thanks a lot! That really helps me out.
