### ISSUE TITLE
clang-offload-bundler-zlib.c test behaves inconsistently in multistage ppc test bots

### ISSUE THREAD

**Issue by eddyz87** [llvm/llvm-project#74472]
Hello,

While working on unrelated changes I noticed that test case `./clang/test/Driver/clang-offload-bundler-zlib.c` (and `...-zstd.c` variant)  might randomly fail when run by `ppc64le-lld-multistage-test` builder. For example, [here](https://lab.llvm.org/buildbot/#/builders/36/builds/40317) is a test run that fail after my commit, however the run immediately following it did not fail.

There are multiple instances of such behavior for  `ppc64le-lld-multistage-test` and `clang-ppc64le-linux-multistage` builders:
- https://lab.llvm.org/buildbot/#/builders/36/builds/40413
- https://lab.llvm.org/buildbot/#/builders/36/builds/40425
- https://lab.llvm.org/buildbot/#/builders/121/builds/37027
- https://lab.llvm.org/buildbot/#/builders/121/builds/37033

Did not find examples for other builders, although the search was not exhaustive.
@gkistanova advised me to create this issue and assign it to test owner (@yxsamliu).

**Comment by yxsamliu** [comment]
Thanks for reporting the issue. I will fix it.
