### ISSUE TITLE
-rpath-link argument not quoted/escaped in AddLLVM.cmake

### ISSUE THREAD

**Issue by slyjain** [llvm/llvm-project#74802]
i did the following to setup llvm project on my linux os:
 git clone https://github.com/llvm/llvm-project.git
cmake -S llvm -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
cmake --build build and when i did this command i got error:FAILED: bin/llvm-min-tblgen
: && /usr/bin/c++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG -Wl,-rpath-link,/home/sly/gsoc projects/llvm-project-main/build/./lib -Wl,--gc-sections utils/TableGen/CMakeFiles/obj.LLVMTableGenCommon.dir/Attributes.cpp.o utils/TableGen/CMakeFiles/obj.LLVMTableGenCommon.dir/CodeGenIntrinsics.cpp.o utils/TableGen/CMakeFiles/obj.LLVMTableGenCommon.dir/DirectiveEmitter.cpp.o utils/TableGen/CMakeFiles/obj.LLVMTableGenCommon.dir/IntrinsicEmitter.cpp.o utils/TableGen/CMakeFiles/obj.LLVMTableGenCommon.dir/RISCVTargetDefEmitter.cpp.o utils/TableGen/CMakeFiles/obj.LLVMTableGenCommon.dir/SDNodeProperties.cpp.o utils/TableGen/CMakeFiles/obj.LLVMTableGenCommon.dir/VTEmitter.cpp.o utils/TableGen/CMakeFiles/llvm-min-tblgen.dir/TableGen.cpp.o -o bin/llvm-min-tblgen -Wl,-rpath,"\$ORIGIN/../lib" lib/libLLVMSupport.a lib/libLLVMTableGen.a lib/libLLVMSupport.a -lrt -ldl -lm lib/libLLVMDemangle.a && :
/usr/bin/ld: cannot find projects/llvm-project-main/build/./lib: No such file or directory
collect2: error: ld returned 1 exit status
[239/3542] Building CXX object lib/Deb...DebugInfoCodeView.dir/EnumTables.cpp.o
ninja: build stopped: subcommand failed.

**Comment by jrtc27** [comment]
As discussed on Discord, this is due to "/home/sly/gsoc projects/llvm-project-main" having a space in it; the code to construct the command line arguments does not suitably escape/quote the path.
