### ISSUE TITLE
How to solve this problem about EmuTlsVar!

### ISSUE THREAD

**Issue by Thrrreeee** [llvm/llvm-project#74968]
When I use ORC JIT  to compile a simple bitcode file of LLVM IR, I face with a problem such as follow.
How can I solve it? In my opinion, It maybe relate to initial option?
![image](https://github.com/llvm/llvm-project/assets/72311224/ee299a1b-3b41-402f-8bf3-7003b93941a4)

**Comment by lhames** [comment]
@Thrrreeee Some more information would be helpful:
* What does the failing bitcode?
* What LLVM version? (looks like it might be the main branch -- what's the latest commit?)
* What architecture are you testing on?

I'd also suggest copying and pasting text from error logs and diagnostics, rather than using screen-grabs, since logs are searchable.

**Comment by Thrrreeee** [comment]
> @Thrrreeee Some more information would be helpful:
> 
> * What does the failing bitcode?
The Bitcode is about how to solve with maze, from source code, it’s not related with thread programming.
> * What LLVM version? (looks like it might be the main branch -- what's the latest commit?)
yes, the version is 18.0.0, and it is the main branch, But I do not remember the latest commit!
> * What architecture are you testing on?
I test it in X86 architecture!
> 
> I'd also suggest copying and pasting text from error logs and diagnostics, rather than using screen-grabs, since logs are searchable.
Thanks for your suggestion, I will pay attention to it.
In my opinion, it may related with initial option?I read a issue (https://discourse.llvm.org/t/how-to-use-thread-local-storage-with-orc-jit/57630) in LLVM Discourse, from your answer LLVM didn’t support TLS when you replied that issue.And I try to compile my example with -femulate-tls, but it can’t solve my problem.

**Comment by lhames** [comment]
> > What does the failing bitcode?
> The Bitcode is about how to solve with maze, from source code, it’s not related with thread programming.

The bitcode will contain constructs that trigger the SelectionDAG error that you're seeing. It is very useful to attach.

> > What LLVM version? (looks like it might be the main branch -- what's the latest commit?)
> yes, the version is 18.0.0, and it is the main branch, But I do not remember the latest commit!

You can get this using the `git log` command.

**Comment by Thrrreeee** [comment]
I also see your [blog](https://discourse.llvm.org/t/orc-jit-weekly-2-coff-comdat-constants-and-emulated-tls/54286),TLS seems to be related to thread local symbol. This error occurred during the initial phase`J->(initialize(J->getMainJITDylib()))`
