### ISSUE TITLE
Handling of memset intrinsic never folds the DSNode

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7496]
|  |  |
| --- | --- |
| Bugzilla Link | [7124](https://llvm.org/bz7124) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The local pass of DSA, when handling the memset intrinsic, does not fold the DSNode of the pointer pointing to the written memory.  Instead, it only marks it as modified.

Instead, it should fold the DSNode unless:

1) The value being written to the memory is zero.
2) The member types within the DSNode can all take zero (this is true for integers and pointers; I'm not sure about floating point types).

**Comment by arsenm** [comment]
Don't think "DSA" exists anymore
