### ISSUE TITLE
Unable to compile the code since clang 16 with -std=c++2b

### ISSUE THREAD

**Issue by 666melkor666** [llvm/llvm-project#74963]
The following code does not compile since clang 16 with c++23 standard. Everything is fine if c++20 is used.

```c++
#include <memory>

struct A
{
    inline static std::unique_ptr<A> test_;
};

int main()
{
    return 0;
}
```

Compiler output
```
In file included from <source>:1:
In file included from /opt/compiler-explorer/clang-16.0.0/bin/../include/c++/v1/memory:898:
In file included from /opt/compiler-explorer/clang-16.0.0/bin/../include/c++/v1/__memory/shared_ptr.h:31:
/opt/compiler-explorer/clang-16.0.0/bin/../include/c++/v1/__memory/unique_ptr.h:63:19: error: invalid application of 'sizeof' to an incomplete type 'A'
    static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");
                  ^~~~~~~~~~~
/opt/compiler-explorer/clang-16.0.0/bin/../include/c++/v1/__memory/unique_ptr.h:297:7: note: in instantiation of member function 'std::default_delete<A>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
/opt/compiler-explorer/clang-16.0.0/bin/../include/c++/v1/__memory/unique_ptr.h:263:75: note: in instantiation of member function 'std::unique_ptr<A>::reset' requested here
  _LIBCPP_INLINE_VISIBILITY _LIBCPP_CONSTEXPR_SINCE_CXX23 ~unique_ptr() { reset(); }
                                                                          ^
<source>:5:38: note: in instantiation of member function 'std::unique_ptr<A>::~unique_ptr' requested here
    inline static std::unique_ptr<A> test_;
                                     ^
<source>:3:8: note: definition of 'A' is not complete until the closing '}'
struct A
       ^
1 error generated.
```

**Comment by 5chmidti** [comment]
Clang does not compile this code from clang 15 onwards: https://godbolt.org/z/oWrY3fznE

**Comment by 666melkor666** [comment]
Interesting observation. This error only happens with constexpr unique_ptr. Once constexpr goes away, either by lowering the standard to c++20 or by using an older GCC toolchain, everything works fine.

**Comment by shafik** [comment]
Also see: https://github.com/llvm/llvm-project/issues/59966

**Comment by shafik** [comment]
CC @erichkeane @zygoloid @cor3ntin

**Comment by zygoloid** [comment]
The `unique_ptr` destructor becomes `constexpr` in C++23, so gets instantiated more eagerly -- at the point of first reference rather than at end of TU. `unique_ptr` destruction doesn't support incomplete types.

**Comment by cor3ntin** [comment]
@jwakely @ldionne do you think this should be a LWG issue?

**Comment by zygoloid** [comment]
I think the code was never valid -- there was always a point of instantiation of the destructor at the point of declaration of the variable. But both clang and gcc prefer the later point of instantiation when it's an option, so you used to get away with it. Unless we also change the core language rules to make code like this actually valid, it doesn't make sense to me for the library rules to try to accommodate it.
