### ISSUE TITLE
missed optimization: redundant store is not optimized away

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#74975]
Test case from gcc testsuite (See https://github.com/gcc-mirror/gcc/blob/master/gcc/testsuite/gcc.dg/tree-ssa/ssa-dom-dse-1.c):
```cpp
int x;
void foo(void) {
  if (x == 0)
    x = 0;
}
void bar(int i) {
  if (x == i)
    x = i;
}
```
https://godbolt.org/z/r6Eohr7oj

**Comment by changkhothuychung** [comment]
For the code generation of gcc, is this a bug? it looks like funciton `bar` should generate code that tries to assign `i` to `x`.

**Comment by BK1603** [comment]
>For the code generation of gcc, is this a bug? it looks like funciton bar should generate code that tries to assign i to x.

Can you please explain why?
Isn't function bar a noop store?

**Comment by changkhothuychung** [comment]
> > For the code generation of gcc, is this a bug? it looks like funciton bar should generate code that tries to assign i to x.
> 
> Can you please explain why? Isn't function bar a noop store?

Ah I am so sorry I did not read the code carefully, I was wrong. `x` is global variable so it will be 0 when the program starts.

**Comment by BK1603** [comment]
I feel bar in itself is a redundant store because it is trying to store a value that is already stored in x. (The if condition ensures that x == i, and then stores x = i and if the condition is false it does nothing.) (Same goes for foo it just compares specifically to 0 instead of a variable)

**Comment by BK1603** [comment]
I'd like to work on this, but I'm not sure if this is a "noop store" since the code explicitly states:
```  
  /// \returns true if \p Def is a no-op store, either because it
  /// directly stores back a loaded value or stores zero to a calloced object.
```
Which sounds like a store of the form `a = x; x = a;` (or zero being stored to a calloced object)

I wonder if it would belong to a some sort of conditional branch optimization where in we are executing instructions in a block that ensure that the conditions to the entry of the block are true?

**Comment by artem** [comment]
Related issue: #74975

**Comment by artem** [comment]
Related issue: #63419

**Comment by k-arrows** [comment]
> Related issue: #63419

Thanks for letting me know this. This issue of mine seems just a duplicate of your issue. I will close this issue.
