### ISSUE TITLE
 Error in the copyfmt function of cout and cerr

### ISSUE THREAD

**Issue by W-50243** [llvm/llvm-project#75025]
Some errors occur when I run the following program：

>  cout.copyfmt(cerr);
    cout<<1<<endl;

It failed and output `Segmentation fault` on llvm15, but it works successfully on llvm 14.  [https://godbolt.org/z/qEn15bq9Y](https://godbolt.org/z/qEn15bq9Y). The copyfmt function does not change from llvm14 to llvm15. Did cout and cerr change? Or has something else changed?

**Comment by dtcxzyw** [comment]
It also fails with gcc. https://godbolt.org/z/j67ds154r
I don't think it is a LLVM-related problem.

**Comment by W-50243** [comment]
> It also fails with gcc. https://godbolt.org/z/j67ds154r I don't think it is a LLVM-related problem.

But it's also successful below the gcc12 version:[https://godbolt.org/z/M3xWe9ads](https://godbolt.org/z/M3xWe9ads)
This makes me feel strange.

**Comment by W-50243** [comment]
I think I understand why this is happening. It fails because `copyfmt` binds cerr's output stream to cout. Cerr's `tie()` is defined as `std::__1::cout `in the c++20 and above standards. When the program ends, the system checks whether tie() of the output stream is empty. Obviously, tie of cout is assigned a value that is not empty. As a result, a program error occurs.

**Comment by W-50243** [comment]
This does not occur if the copied output stream is cleared.
[https://godbolt.org/z/qox88q76r](https://godbolt.org/z/qox88q76r)
