### ISSUE TITLE
Missing optimization: fold `max(b, a + 1)` to `b` when `a < b`

### ISSUE THREAD

**Issue by XChy** [llvm/llvm-project#75155]
Alive2 proof: https://alive2.llvm.org/ce/z/V82mt-

### Description:

```c
long src(long a, long b) {
    if(a < b){
        return max(b, a + 1);
    }else{
        return 0;
    }
}
```
can be folded to:
```c
long tgt(long a, long b) {
    if(a < b){
        return b;
    }else{
        return 0;
    }
}
```
Similarly, it also applies to other cases like `a > b`, `min(b, a + 1)` and so on.

### Real-world motivation

This snippet of IR is derived from [redis/src/db.c@readGetKeys](https://github.com/redis/redis/blob/c85a9b7896b9727709b71fed414bf8a117436d71/src/db.c#L2899C14-L2899C14) (after O3 pipeline).
The example above is a reduced version. If you're interested in the original suboptimal IR and optimal IR, see also:https://godbolt.org/z/YaEYnedYW

**Let me know if you can confirm that it's an optimization opportunity, thanks.**

**Comment by nikic** [comment]
I don't think the subtraction is really relevant here. We can optimize the max away regardless of how it is used: https://alive2.llvm.org/ce/z/V82mt-
