### ISSUE TITLE
Running `clang++` with any arguments takes 10 seconds first time after macOs load

### ISSUE THREAD

**Issue by real-mikhail** [llvm/llvm-project#75179]
Hi,

We've encountered the problem that calling any clang++ command after system start (macOS) takes 10 seconds while any command afterwards will not have such issue. Even calling `clang++ --version` takes those 10 seconds:
```
> time clang++ --version

Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Users/UserName/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang++ --version  0.01s user 0.03s system 0% cpu **9.973 total**
```

Clang is installed as a part of Xcode.
Information about system:
```
MacBook Pro 2022
Chip: Apple M2
OS: macOS Ventura 13.3.1 (22E261)
Xcode: 14.3.1
Build version 14E300c
```

Processor is ARM-based but Clang executable is also ARM-based so it should not be caused by Rosetta translation.

**Comment by apple-fcloutier** [comment]
It's important to say that `/usr/bin/clang` is not clang on Apple systems, it's a program that finds clang in the currently-selected toolchain and executes it. You can get the path of the clang that will be executed by using `xcrun --find clang`, and you can execute this clang directly if you wish.

**Comment by DimitryAndric** [comment]
I don't think there is anything the llvm project can do here. Apple's notarization implementation is outside our control.
