### ISSUE TITLE
How to generate docs of MLIR Dialect Ops ?

### ISSUE THREAD

**Issue by godfather991** [llvm/llvm-project#75236]
- I found that the docs in mlir/docs/Dialects are not complete, missing the Op definitions
- then I try to build the docs with `-DMLIR_INCLUDE_DOCS=ON` and `make mlir-doc`
- I was told that the doc were generated
  <img width="424" alt="截屏2023-12-13 03 00 52" src="https://github.com/llvm/llvm-project/assets/58773907/145a599d-f04a-4dcb-8e89-a9c5cea1bc08">
- however, **I can't actually find where it is.**

**Comment by joker-eph** [comment]
I usually use the `find` command: can you try `find * | grep Linalg0ps.md` for example?

**Comment by godfather991** [comment]
<img width="331" alt="截屏2023-12-13 09 51 41" src="https://github.com/llvm/llvm-project/assets/58773907/6280889c-7bc7-4c73-ac22-3657f398ae1f">
I tried this command in the `llvm-project` directory, and found nothing

**Comment by godfather991** [comment]
<img width="428" alt="截屏2023-12-13 09 54 54" src="https://github.com/llvm/llvm-project/assets/58773907/28d29f95-dcce-4bbb-a27f-f1a2e7b34d70">

Thanks for your help !
