### ISSUE TITLE
stage2 and stag3 of clang are not identical

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7527]
|  |  |
| --- | --- |
| Bugzilla Link | [7155](https://llvm.org/bz7155) |
| Version | trunk |
| OS | Linux |
| Attachments | [Bootstrap clang from gcc](https://user-images.githubusercontent.com/60944935/143741345-ad775082-35ff-48ae-91da-a3b903e57664.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
I am bootstapping clang, and in theory stage2 and stage should be identical binaries (at least on linux).

Binaries are different for the last 3 weeks here (Fedora 12, 32bit, bootstrapping from gcc-4.4.3). I am compiling out of source using cmake.

[elcuco@pinky ~/src/llvm] ls -l bootstrap-stage-{2,3}/bin/clang
-rwxrwxr-x. 1 elcuco elcuco 24576970 2010-05-17 20:14 bootstrap-stage-2/bin/clang
-rwxrwxr-x. 1 elcuco elcuco 24580575 2010-05-17 20:35 bootstrap-stage-3/bin/clang

I attach here the build script I used, just save it under the root of your llvm checkout, and it will create 3 new directories, + bootstrap.log file with all the build log. not tested on mac, but I assume it will work as well.

**Comment by arsenm** [comment]
Old build issue
