### ISSUE TITLE
[AVR] - How to get things working on MacOS

### ISSUE THREAD

**Issue by fracturedsoftware** [llvm/llvm-project#75313]
Hi
Is there any up to date documentation on how to compile llvm for AVR ? I, and many others if you google around, are have a lot of difficulty getting things to work. 

I am using a recent MacOS. I managed to download the latest llvm using the following commands and everything seemed to work fine:

```
% git clone https://github.com/llvm/llvm-project.git /opt/llvm-project
% cd /opt/llvm-project/llvm
% mkdir build && cd build
% cmake -G "Unix Makefiles" -DLLVM_TARGETS_TO_BUILD="AVR" -DCMAKE_INSTALL_PREFIX=/opt/llvm-project/llvm/bin -DCMAKE_BUILD_TYPE=Release /opt/llvm-project/llvm
% cmake --build .
% cmake --build . --target install
```
However I soon ran into problems compiling a very simple 'Hello World' program:
```
% clang --target=avr -mmcu=atmega328 main.c -o main.elf
```
Where I got the error 'error: unable to create target: 'No available targets are compatible with triple "avr"'

I did:
```
% clang  -print-targets
Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_32 - AArch64 (little endian ILP32)
    aarch64_be - AArch64 (big endian)
    arm        - ARM
    arm64      - ARM64 (little endian)
    arm64_32   - ARM64 (little endian ILP32)
    armeb      - ARM (big endian)
    thumb      - Thumb
    thumbeb    - Thumb (big endian)
    x86        - 32-bit X86: Pentium-Pro and above
    x86-64     - 64-bit X86: EM64T and AMD64
```
And AVR is no where in that list. Can anyone explain what I am doing wrong?

Thanks

**Comment by asl** [comment]
> And AVR is no where in that list. Can anyone explain what I am doing wrong?

You are likely running system clang that is available from XCode, not the one you've just built

**Comment by fracturedsoftware** [comment]
That could be it.

Unfortunately running:
```
/opt/llvm-project/llvm/bin/clang  --version
```
gives me a no such file or directory.

**Comment by asl** [comment]
> That could be it.
> 
> Unfortunately running:
> 
> ```
> /opt/llvm-project/llvm/bin/clang  --version
> ```
> 
> gives me a no such file or directory.

Looks like you only built LLVM and not clang.

**Comment by fracturedsoftware** [comment]
Indeed. Unfortunately this gets back to my original issue - there is no documentation on how someone new to the project would actually get started.

**Comment by asl** [comment]
> Indeed. Unfortunately this gets back to my original issue - there is no documentation on how someone new to the project would actually get started.

I believe this is covered by https://llvm.org/docs/GettingStarted.html#getting-the-source-code-and-building-llvm that mentions:
```
Some common options:

-DLLVM_ENABLE_PROJECTS='...' — semicolon-separated list of the LLVM subprojects you’d like to additionally build. Can include any of: clang, clang-tools-extra, lldb, lld, polly, or cross-project-tests.
```

Plus this: https://llvm.org/docs/GettingStarted.html#common-problems

**Comment by benshi001** [comment]
my steps

```
1. cmake -DCMAKE_INSTALL_PREFIX=/tmp/llvm-build/ -DCMAKE_BUILD_TYPE=Release -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_ENABLE_PROJECTS="clang;lld;" -DLLVM_TARGETS_TO_BUILD="X86;AVR;" -DLLVM_BUILD_LLVM_DYLIB=On -DCMAKE_C_FLAGS="-O3" -DCMAKE_CXX_FLAGS="-O3" -DLLVM_OPTIMIZED_TABLEGEN=On ../llvm
2. make -j40
3. make install 
```

Then I got clang for AVR at `/tmp/llvm-build/bin/clang`

**Comment by fracturedsoftware** [comment]
Ok - thank you. I have now managed to compile clang and 
```
% clang -print-targets
```
gives me:

  Registered Targets:
    avr - Atmel AVR Microcontroller

However I've now hit another snag. Compiling an empty main.c
```
int main(void){
    return 1;
}
```
Gives me what seems to be an almost empty file. Converting it to a hex file with:
```
% avr-objcopy -O ihex  main.elf  main.hex
```
Or ( I've discovered ) 
```
% % /opt/llvm-project/llvm/bin/bin/llvm-objcopy -O ihex main.elf main.hex
```
Gives me a 1 line hex file that is all zeros with a checksum at the end.

I also compiled a slightly more complicated main.c file and got what seems to be an identical .elf file.

I get 2 warnings:

clang: warning: no avr-libc installation can be found on the system, cannot link standard libraries
clang: warning: standard library not linked and so no interrupt vector table or compiler runtime routines will be linked

Would this be the cause of the empty hex file and if so how would I go about adding avr-libc so that clang can recognise it? I would definitely have it on my system as I have avr-gcc

Thanks for any help.

**Comment by benshi001** [comment]
You need to use `--sysroot` to specify your GCC installation, see examples in

https://github.com/llvm/llvm-project/blob/main/clang/test/Driver/avr-toolchain.c

**Comment by benshi001** [comment]
For example, if your avr-gcc's full path is `/opt/local/avr-tools/bin/avr-gcc`, then you need to do `clang xx.c --target=avr -mmcu=atmega328 --sysroot=/opt/local/avr-tools`.

**Comment by benshi001** [comment]
Actually clang-avr has not new bug revealed, so just close this issue. 

Please send me emails or comment on this thread for further questions.

**Comment by fracturedsoftware** [comment]
I tried a quite few things but never actually got clang to find avr-libc so I think I’ll wait until there is more documentation and users. Part of the problem is that even if I got that to work, I have no idea if there aren't further hoops to jump through before everything works. Thanks for your help.
