### ISSUE TITLE
Implement the `select` HLSL Function

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#75377]
HLSL 2021 introduced the `select` intrinsic as a replacement for the ternary operator on vector types.

The `select` intrinsic has the following approximate forms:
```c++
template<typename T, int Sz>
void select(vector<bool, Sz> Conds, vector<T, Sz> TrueVals, vector<T, Sz> FalseVals) {
  vector<T, Sz> Result;
  for (int I = 0; I < Sz; ++I) {
    if (Conds[I])
      Result[I] = TrueVals[I];
    else
      Result[I] = FalseVals[I];
  }
  return Result;
}

template<typename T>
void select(bool Cond, T TrueVal, T FalseVal) {
  if (T)
    return TrueVal;
  return FalseVal;
}
```

The vector case can lower to a shufflevector mask:
```c++
template<typename T, int Sz>
void select(vector<bool, Sz> Conds, vector<T, Sz> TrueVals, vector<T, Sz> FalseVals) {
  vector<int, Sz> Mask;
  for (int I = 0; I < Sz; ++I) {
    Mask[I] = I;
    if (!Conds[I])
      Mask[I] += Sz;
  }
  return __builtin_shufflevector(TrueVals, FalseVals, Mask);
}
```

**Acceptance Criteria**
Implementation of the select intrinsic in the HLSL builtin headers and corresponding lowering to LLVM IR with appropriate test coverage.

- [ ] Implement `select` clang builtin,
- [ ] Link `select` clang builtin with `hlsl_intrinsics.h`
- [ ] Add sema checks for `select` to `CheckHLSLBuiltinFunctionCall` in `SemaChecking.cpp`
- [ ] Add codegen for `select` to `EmitHLSLBuiltinExpr` in `CGBuiltin.cpp`
- [ ] Add codegen tests to `clang/test/CodeGenHLSL/builtins/select.hlsl`
- [ ] Add sema tests to `clang/test/SemaHLSL/BuiltIns/select-errors.hlsl`
- [ ] Create the `int_spv_select` intrinsic in `IntrinsicsSPIRV.td`
- [ ] In SPIRVInstructionSelector.cpp create the `select` lowering and map  it to `int_spv_select` in `SPIRVInstructionSelector::selectIntrinsic`.
- [ ] Create SPIR-V backend test case in `llvm/test/CodeGen/SPIRV/hlsl-intrinsics/select.ll`

## DirectX

There were no DXIL opcodes found for `select`.

## SPIR-V

# [OpSelect](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpSelect):

## Description:
  
Select between two objects. Before **version 1.4**, results are only
computed per component.  
  
Before **version 1.4**, *Result Type* must be a pointer, scalar, or
vector. Starting with **version 1.4**, *Result Type* can additionally be
a [composite](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#CompositeType) type other than a vector.  
  
The types of *Object 1* and *Object 2* must be the same as *Result
Type*.  
  
*Condition* must be a scalar or vector of [*Boolean type*](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Boolean).  
  
If *Condition* is a scalar and **true**, the result is *Object 1*. If
*Condition* is a scalar and **false**, the result is *Object 2*.  
  
If *Condition* is a vector, *Result Type* must be a vector with the same
number of components as *Condition* and the result is a mix of *Object
1* and *Object 2*: If a component of *Condition* is **true**, the
corresponding component in the result is taken from *Object 1*,
otherwise it is taken from *Object 2*.

<table style="width:100%;">
<colgroup>
<col style="width: 14%" />
<col style="width: 14%" />
<col style="width: 14%" />
<col style="width: 14%" />
<col style="width: 14%" />
<col style="width: 14%" />
<col style="width: 14%" />
</colgroup>
<thead>
<tr>
<th>Word Count</th>
<th>Opcode</th>
<th>Results</th>
<th>Operands</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td class="tableblock halign-left valign-top"><p>6</p></td>
<td class="tableblock halign-left valign-top"><p>169</p></td>
<td
class="tableblock halign-left valign-top"><p><em>&lt;id&gt;</em><br />
<em>Result Type</em></p></td>
<td class="tableblock halign-left valign-top"><p><a
href="#ResultId"><em>Result &lt;id&gt;</em></a></p></td>
<td
class="tableblock halign-left valign-top"><p><em>&lt;id&gt;</em><br />
<em>Condition</em></p></td>
<td
class="tableblock halign-left valign-top"><p><em>&lt;id&gt;</em><br />
<em>Object 1</em></p></td>
<td
class="tableblock halign-left valign-top"><p><em>&lt;id&gt;</em><br />
<em>Object 2</em></p></td>
</tr>
</tbody>
</table>

### Example 1
```hlsl
//dxc select_test.hlsl -T lib_6_8 -E fn -enable-16bit-types -spirv -fspv-target-env=universal1.5 -fcgl -O0

export float4 fn(bool4 p1, float4 p2, float4 p3) {
    return select(p1, p2, p3);
}
```
 ### Example 2
```hlsl
//dxc select_1_test.hlsl -T lib_6_8 -E fn -enable-16bit-types -spirv -fspv-target-env=universal1.5 -fcgl -O0

export float4 fn(bool p1, float4 p2, float4 p3) {
    return select(p1, p2, p3);
}
```
## Syntax

```syntax
any<> select(bool<> cond, any<> t, any<> f);
```

```syntax
any_sampler select(bool cond, any_sampler t, any_sampler f);
```

## Type Description

| Name  | [**Template Type**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-data-types.md)| [**Component Type**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-data-types.md) | Size |
|-------|--------------------------------------------------------------------|----------------------------------------------------------------------|------|
| *ret* | [**scalar**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-scalar.md), [**vector**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-vector.md), or [**matrix**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-matrix.md) | **bool**, [**float**](../WinProg/windows-data-types), or [**int**](../WinProg/windows-data-types) | any |
| *cond* | [**scalar**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-scalar.md), [**vector**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-vector.md), or [**matrix**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-matrix.md) | **bool** | any |
| *t* | [**scalar**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-scalar.md), [**vector**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-vector.md), or [**matrix**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-matrix.md) | **bool**, [**float**](../WinProg/windows-data-types), or [**int**](../WinProg/windows-data-types) | any |
| *f* | [**scalar**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-scalar.md), [**vector**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-vector.md), or [**matrix**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-matrix.md) | **bool**, [**float**](../WinProg/windows-data-types), or [**int**](../WinProg/windows-data-types) | any |
## Type Description

| Name  | [**Template Type**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-data-types.md)| [**Component Type**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-data-types.md) | Size |
|-------|--------------------------------------------------------------------|----------------------------------------------------------------------|------|
| *ret* | [**scalar**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-scalar.md) | [**float**](../WinProg/windows-data-types), [**int**](../WinProg/windows-data-types), or [**uint**](../WinProg/windows-data-types) | 1 |
| *cond* | [**scalar**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-scalar.md) | **bool** | 1 |
| *t* | [**scalar**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-scalar.md) | [**float**](../WinProg/windows-data-types), [**int**](../WinProg/windows-data-types), or [**uint**](../WinProg/windows-data-types) | 1 |
| *f* | [**scalar**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-scalar.md) | [**float**](../WinProg/windows-data-types), [**int**](../WinProg/windows-data-types), or [**uint**](../WinProg/windows-data-types) | 1 |

## Minimum Shader Model

This function is supported in the following shader models.
|Shader Model |	Supported|
|-------------|----------|
|HLSL 2021 and higher shader models | yes |

## Remarks

In HLSL 2021 `int3 Z = select(X, 1, 0);` is a replacement for
```hlsl
int3 X = {1, 1, 1};
int3 Z = X ? 1 : 0;
```

## See also

- [**Intrinsic Functions (DirectX HLSL)**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/../direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md)
- **See [HLSL 2021 Logical operation short-circuiting for scalars](https://github.com/microsoft/DirectXShaderCompiler/wiki/HLSL-2021#logical-operation-short-circuiting-for-scalars)**

**Comment by spall** [comment]
looking at this
