### ISSUE TITLE
[clang-format] Attribute forces a function to break into multiple lines.

### ISSUE THREAD

**Issue by XDeme** [llvm/llvm-project#75399]
Placing an attributes one line above a function forces the function to break into multiple lines.
```cpp
[[maybe_unused]] 
void foo() { return; }
```
Formats to this:
```cpp
[[maybe_unused]]
void foo() {
  return;
}
```

Using `AllowShortFunctionsOnASingleLine: All` and `ColumnLimit: 100` doesn't change the formatting.

**Comment by owenca** [comment]
You need to set `BreakAfterAttributes` to `Never`. Otherwise, the default `Always` which breaks after the attributes will in effect have broken the function into multiple lines because the attributes are part of the function.

**Comment by XDeme** [comment]
Ok, I thought the option was meant to break only after the attribute.
