### ISSUE TITLE
Why arm_acle.h not contains  co-processor intrinsics?

### ISSUE THREAD

**Issue by hstk30-hw** [llvm/llvm-project#75424]
I'm handling some dejagnu test cases. I see the clang arm_acle.h not contains co-processor intrinsics like `__arm_cdp`, `__arm_ldc` ...
, but accutally has `__builtin_arm_xxx` corresponding. 

So I put the definition to the arm_acle.h zealously, hope it will work.
But it fail with error: 

> argument to '__builtin_arm_mrrc2' must be a constant integer

Is clang arm_acle.h have to use `__builtin_arm_xx` instead of `__arm_xx` for co-processor intrinsics?

The definition is like :

```
 static __inline uint64_t __attribute__((__always_inline__, __nodebug__))
 __arm_mrrc2(const unsigned int __coproc, const unsigned int __opc1,
             const unsigned int __CRm) {
   return __builtin_arm_mrrc2(__coproc, __opc1, __CRm);
 }
```

**Comment by hstk30-hw** [comment]
@kongy @rengolin

**Comment by topperc** [comment]
I think you need to make it a macro to avoid the error. I can't speak to any ARM specifics. I've just implemented a lot of X86 intrinsics over the years.
