### ISSUE TITLE
[LLDB] no member named 'id' in namespace '$__lldb_local_vars'

### ISSUE THREAD

**Issue by wingfiring** [llvm/llvm-project#75443]
## Description:
If a vaiable named "id", it can't be referenced by command `p` or `expr`, and the error message was
```
error: expression failed to parse:
error: <lldb wrapper prefix>:45:31: no member named 'id' in namespace '$__lldb_local_vars'
    using $__lldb_local_vars::id;
          ~~~~~~~~~~~~~~~~~~~~^
warning: <user expression 1>:1:1: declaration does not declare anything
id
^~
```
### Environment
lldb version: lldb-1400.0.38.17
Apple clang version 14.0.0 (clang-1400.0.29.202)
OS: MacOS 12.6.7 (21G651)
Processor: 3.3 GHz Quad-Core Intel Core i5 

## Reproduce steps
With code
```C++
int main(int argc, char**){
    int i = argc;
    int id = argc;
    return i - id ;
}
```
build command:
`clang++  a.cpp -g`

Steps:
```
$lldb ./a.out
(lldb) b main
(lldb) r aaa
(lldb) n
(lldb) n
(lldb) p i
(int) $0 = 2
(lldb) p id
error: expression failed to parse:
error: <lldb wrapper prefix>:45:31: no member named 'id' in namespace '$__lldb_local_vars'
    using $__lldb_local_vars::id;
          ~~~~~~~~~~~~~~~~~~~~^
warning: <user expression 1>:1:1: declaration does not declare anything
id
^~

```

**Comment by Michael137** [comment]
Yup, and the same is true for `Class`. This is determined [here](https://github.com/llvm/llvm-project/blob/726830f8932d210dd0b8e9d43908e8ad10086b6f/lldb/source/Plugins/ExpressionParser/Clang/ClangASTSource.cpp#L561-L576):
```
bool ClangASTSource::IgnoreName(const ConstString name,
                                bool ignore_all_dollar_names) {
  static const ConstString id_name("id");
  static const ConstString Class_name("Class");
```

This was first introduced in `46198ff8249c28d396b01083ed7d109c8bd5229e`:
```
Updated LLVM/Clang to pull in a fix for Objective-C
interfaces.  This allows us to pull in Objective-C
method types on demand, which is also now implemented.

Also added a minor fix to prevent multiple-definition
errors for "Class" and "id".
```

It's unfortunate that this also affects non-Objective-C expressions.

This is only true for the expression evaluator though, so `v id` should work fine. In more recent versions of LLDB `p` is aliased to `dwim-print`, which would've run `v id`.

**Comment by dlongnecke-cray** [comment]
I'm experiencing this issue as well. Really impeding some of my work because I cannot evaluate expressions:

```
p id.parentSymbolId(context)
error: expression failed to parse:
error: <lldb wrapper prefix>:46:27: no member named 'id' in namespace '$__lldb_local_vars'
using $__lldb_local_vars::id;
      ~~~~~~~~~~~~~~~~~~~~^
error: <user expression 0>:1:3: cannot use dot operator on a type
id.parentSymbolId(context)
```

I'm using `lldb version 16.0.6`.

**Comment by Michael137** [comment]
@clayborg do you remember why this special `IgnoreName` for `id` and `Class` was necessary back when it was introduced in `46198ff8249c28d396b01083ed7d109c8bd5229e`? The test-suite passes for me on Darwin without that logic. It'd be unfortunate if we couldn't evaluate these names in pure C++ code
