### ISSUE TITLE
Release builds dynamically linked to missing libtinfo.so.5

### ISSUE THREAD

**Issue by rbtcollins** [llvm/llvm-project#75490]
Possibly related to #17276.

E.g. https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.6/clang+llvm-15.0.6-x86_64-linux-gnu-ubuntu-18.04.tar.xz

This library is [not present by default](https://packages.ubuntu.com/search?keywords=libtinfo) on current Ubuntu systems, even though it was present in the past.

I'm not sure what the right answer is here:
 - document the non-current libraries users (e.g. Bazel toolchains, nix recipes, actual people) have to install to use clang
 - build clang in a more hermetic fashion, with no dynamic dependencies outside those LSB mandates
 - [piss off the one person in Google again](https://reviews.llvm.org/D42274#1076895).
 - something else

**Comment by photex** [comment]
I think Ubuntu 18.04 reached EOL a year ago. Could it maybe be time to bump these builds to 20.04 as well?

Whether or not that happens, the fact that these binaries can't just be run as they are is still surprising after all this time and it's bitten me once again when trying to setup a Bazel toolchain that uses it. I mean, by definition people *can't* create a hermetic toolchains based on official releases unless they happen to be using 18.04 right?
