### ISSUE TITLE
UB in XCOFF after #72532

### ISSUE THREAD

**Issue by vitalybuka** [llvm/llvm-project#75520]
@stephenpeckham There is UB shifting negative value https://lab.llvm.org/buildbot/#/builders/85/builds/20910

I recovered bots with 36477f7562c0f951bcfe3df5ae7a566e6e462dd1, but I don't know if negatives are expected there.

So please double check.

**Comment by chenzheng1030** [comment]
> but I don't know if negatives are expected there

The negative imms are expected. The patch introduces ths UB is https://github.com/llvm/llvm-project/pull/72532. 
Your fix https://github.com/llvm/llvm-project/commit/36477f7562c0f951bcfe3df5ae7a566e6e462dd1 should be good.
