### ISSUE TITLE
Allows looser exception specification in overriding function

### ISSUE THREAD

**Issue by be579e8c-b74b-475b-a126-3b8cefdd833c** [llvm/llvm-project#7553]
|  |  |
| --- | --- |
| Bugzilla Link | [7181](https://llvm.org/bz7181) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Clang does not correctly check that overriders' exception specifications are at most as loose as their base class functions. 

struct eB { };
struct eD : eB { };

struct A {
  virtual void fx() throw(eB*) { }
};

struct B : A {
  virtual void fx() throw(eD const*) { }
};

I expected this code to be rejeced, because "eD const*" is not allowed by A::fx but allowed by "B::fx".

**Comment by gwelymernans** [comment]
I think we do better here:

```
pr.cc:9:16: error: exception specification of overriding function is more lax than base version
  virtual void fx() throw(eD const*) { }
               ^
pr.cc:5:16: note: overridden virtual function is here
  virtual void fx() throw(eB*) { }
               ^
1 error generated.
```

I'm going to mark this as closed. If you have another example where we're failing, please open another issue.
