### ISSUE TITLE
another OOB InsertElement -> OOB store

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#75557]
this is like https://github.com/llvm/llvm-project/issues/74248 and again affects all backends that I tried

```llvm
define void @insertelt_v8i64_store(ptr %0, i32 %1) {
  %3 = load <8 x i64>, ptr %0, align 64
  %4 = insertelement <8 x i64> %3, i64 -1, i32 %1
  store <8 x i64> %4, ptr %0, align 64
  ret void
}
```
becomes:
```
insertelt_v8i64_store: 
	mov	x8, #-1                         // =0xffffffffffffffff
	str	x8, [x0, w1, uxtw #3]
	ret
```

cc @nunoplopes @tanmaytirpankar

**Comment by topperc** [comment]
It's the exact same bug. 7e3aeee3bf515f5922b564d3a850ab9f933a32dd silently merged out my patch

CC @vitalybuka

**Comment by vitalybuka** [comment]
Oh, I am so sorry, that was not my intention.
Looking at https://github.com/llvm/llvm-project/pull/74172 it was somehow introduced with 038d0f7 as rebase.
It never happened to me before, but I use SPR for less them a month.

**Comment by vitalybuka** [comment]
It exactly dropped one patch. I re-committed it as-is.

I looked through my commits from Aug, and I see nothing like that anywhere else.
Not sure if that was the tool bug or the user error.

Sorry again.
