### ISSUE TITLE
[libc++][test] `support.limits.general/.version.compile.pass.cpp` is malformed

### ISSUE THREAD

**Issue by StephanTLavavej** [llvm/llvm-project#75577]
This file's name and contents are bogus:

https://github.com/llvm/llvm-project/blob/966416b9e8e315494d586c5f0e88516e22135698/libcxx/test/std/language.support/support.limits/support.limits.general/.version.compile.pass.cpp#L9-L24

I suspect that `lit` is skipping this because it doesn't recognize the filename, which is why neither llvm/llvm-project nor microsoft/STL noticed this. However, MSVC's internal test harness is far less enlightened and tried to run everything, which brought this to my attention.

@mordante This appears to have been introduced by #72421.

**Comment by mordante** [comment]
I had a look and I guess it's due to some FTM didn't specified the affected headers so I left them empty.
(Look at what is merged in the WP is on my TODO list.)

**Comment by frederick-vs-ja** [comment]
IIUC the contents should moved into `format.version.compile.pass.cpp` and `numeric.version.compile.pass.cpp`.

**Comment by mordante** [comment]
> IIUC the contents should moved into `format.version.compile.pass.cpp` and `numeric.version.compile.pass.cpp`.

That's indeed what has been done in the PR's for the Standard. The papers in question didn't mention the affected headers.
