### ISSUE TITLE
[OpenMP] Performance degradation from devices reorganization

### ISSUE THREAD

**Issue by dhruvachak** [llvm/llvm-project#75677]
@ronlieb  collected some performance numbers using versions of the upstream compiler that show degradations after the devices reorganization. It appears that https://github.com/llvm/llvm-project/pull/74397 is one of the patches causing the degradation. Currently, all available devices on a system are being initialized eagerly. Previously, only devices that were being used by an application would be initialized.

These are the llvm-project before/after commits used for comparison.

Before SHA: bb0f162b
After SHA: 77c40ea3

SPEChpc 2021 benchmark 505.lbm degraded 10% when using 8 MPI ranks on a system with 8 AMD GPUs. The configuration tested is the default setting without the env-var ROCR_VISIBLE_DEVICES set.

**Comment by jdoerfert** [comment]
@dhruvachak Could you please provide a profile (LIBOMPTARGET_PROFILE) for the issue? We (= @fel-cab) tried to replicate it and it does not show up on our end. We saw a ~10% slowdown between Oct 23 and 30, maybe that is what you are seeing?

**Comment by doru1004** [comment]
Thanks for trying to replicate it. What system did you try it on? With how many GPUs?

**Comment by fel-cab** [comment]
We are running on Frontier. 1 Node, 8 GPUs

**Comment by doru1004** [comment]
Did you run it with 8 MPI processed?

**Comment by doru1004** [comment]
And you don't have something which silently sets the ROCR_VISIBLE_DEVICES right?

**Comment by fel-cab** [comment]
Not that I know. I've been running SPEChpc weekly, with LLVM weekly build on Frontier for about a year. I have not use ROCR_VISIBLE_DEVICES. It is the first time I hear of this

**Comment by jdoerfert** [comment]
The profile will include the time we spend in deviceInit, so it will be easy to see.
If you generate the profile for both versions (before and after), we can probably pinpoint where it spends extra time, if any.

**Comment by fel-cab** [comment]
Sound good.

**Comment by doru1004** [comment]
We saw the degradation on PCIe interconnects. Maybe that's why you're not seeing the performance degradation on your side?

**Comment by jdoerfert** [comment]
> We saw the degradation on PCIe interconnects. That's why you're not seeing the performance degradation on your side.

Can you please share a profile w/ and w/o this patch (or your proposed PR)?
LIBOMPTARGET_PROFILE is sufficient.

**Comment by doru1004** [comment]
> Can you please share a profile w/ and w/o this patch (or your proposed PR)?
> LIBOMPTARGET_PROFILE is sufficient.

I don't have any more details than the overall numbers. Slight improvements with my PR on 8GPU PCIe.

**Comment by jdoerfert** [comment]
The profile system is literally builtin, just run it with the env var set to a file name and share the results. We can then see where the extra time is spend.

**Comment by doru1004** [comment]
I'm not sure why oversubscription should be a problem here. The issue should only concern the initial runtime setup time no?

**Comment by jdoerfert** [comment]
> I'm not sure why oversubscription should be a problem here. The issue should only concern the initial runtime setup time no?

In that case, the profile will clearly show that part. Let's simply take a look.

**Comment by jdoerfert** [comment]
<img width="1310" alt="Screenshot 2024-01-09 at 11 11 48 AM" src="https://github.com/llvm/llvm-project/assets/6248191/7ae1060d-c508-4871-b74b-514adc72b987">
Here is a screenshot from a system with 8 PCI connected MI250X cards.
The upper one is initializing all 8 eagerly, the lower one initializes only a single one.
As before, initialization takes ~10ms per device, thus 80ms vs 10ms.
Is the slowdown you see ~70ms long or do you experience something else?

**Comment by jdoerfert** [comment]
@dhruvachak  Can we close this?

**Comment by dhruvachak** [comment]
Yes, not sure whether this is reproducible any more.
