### ISSUE TITLE
[HLSL] Add diagnostics for Buffers/RWBuffers with invalid element types

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#75676]
There's a specific closed set of types that are valid as element types for TypedBuffer types, which includes int/uint of sizes 16/32/64, half, float, and double. If someone writes `RWBuffer<MyCustomType>` we should reject it and give the user a nice diagnostic.

AC:
* A spec is created to dictate the validation behavior 
* Type validation happens prior to code generation
* Tests written to validate failure on mixed types

**Comment by davidcook-msft** [comment]
Moved to low as this currently does not happen and the DXIL validator will catch it, but we would rather catch it prior to the validator

**Comment by bogner** [comment]
We could arguably implement this simply by decorating the resource classes with an appropriate concept (something along the lines of https://godbolt.org/z/Y3sezEe36)
