### ISSUE TITLE
xf_float does not exist 

### ISSUE THREAD

**Issue by trcrsired** [llvm/llvm-project#75680]
triple: aarch64-linux-android24
cross compiling compiler-rt
/home/cqwrteur/Projects/myllvm/llvm-project/compiler-rt/lib/builtins/fixxfti.c:27:34: error: unknown type name 'xf_float'; did you mean 'tf_float'?
   27 | COMPILER_RT_ABI ti_int __fixxfti(xf_float a) {
      |                                  ^~~~~~~~
      |                                  tf_float
/home/cqwrteur/Projects/myllvm/llvm-project/compiler-rt/lib/builtins/int_types.h:199:21: note: 'tf_float' declared here
  199 | typedef long double tf_float;
      |                     ^
/home/cqwrteur/Projects/myllvm/llvm-project/compiler-rt/lib/builtins/fixxfti.c:30:3: error: unknown type name 'xf_bits'; did you mean 'tf_bits'?
   30 |   xf_bits fb;
      |   ^~~~~~~
      |   tf_bits
/home/cqwrteur/Projects/myllvm/llvm-project/compiler-rt/lib/builtins/int_types.h:214:3: note: 'tf_bits' declared here
  214 | } tf_bits;
      |   ^
2 errors generated.

**Comment by EugeneZelenko** [comment]
@trcrsired: Could you please elaborate?
