### ISSUE TITLE
clang is suboptimal for `(a ^ b) & (~a ^ b)` where b is a specific constant

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#75692]
Example:
```cpp
int foo(int a) { return (a ^ 4) & (~a ^ 4); }
```

https://godbolt.org/z/n3KP7sTbb

**Comment by dtcxzyw** [comment]
Alive2: https://alive2.llvm.org/ce/z/F-53GD

**Comment by ChipsSpectre** [comment]
@dtcxzyw Could you assign me?

After fixing an issue in the frontend (https://github.com/llvm/llvm-project/issues/73559) I am keen on learning about llvm's optimizer.

**Comment by ChipsSpectre** [comment]
As far as I understand it, llvm seems to optimize code in a series of Transforms realized in `Pass`es.

instcombine' handles to optimization of logical expressions, it seems that the implementation in _llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp_ is used for that.

@dtcxzyw Would it be ok to place a patch here?

**Comment by ParkHanbum** [comment]
maybe this issue could similar of this 
https://github.com/llvm/llvm-project/issues/57532

**Comment by ParkHanbum** [comment]
I think this issue can be defined into "comparing LHS between RHS has common variable and it affect result". 

as I know, LLVM hasn't support API for represent between two expression has common variable. 

even when it can be determined like example ("x < ~x").
so, I think maybe this kind of formula need to support.

if I had mis-understand or mis-known, please let me know. 
I'm just beginner of LLVM  

:smile:

**Comment by pinskia** [comment]
Note GCC handles this only on the RTL Level, I filed https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113072 for handling it on the gimple level too.

**Comment by pinskia** [comment]
Note this applies to `|` instead of `&` too:
```
int foo1(int a, int b)
{
        return  (a ^ 4) | (~a ^ 4);
}
```

This should be optimized to `-1`.

**Comment by ChipsSpectre** [comment]
@ParkHanbum Thank you for mentioning your related issue. 

It seems the current optimization for instruction combination does not handle the aspect that constants in _nested_ subexpressions may be used to simplify the overall expression.

@pinskia Could you reference the code section in GCC which fixes this issue? It would be interesting to see how GCC handles this situation.

**Comment by XChy** [comment]
@ChipsSpectre. InstCombine folds `~a ^ b` to `a ^ ~b` when `b` is a constant. We can simply catch `(a ^ c1) & (a ^ c2)` with pattern matching and fold it to 0 when `c1 == ~c2`. For `|`, it's similar.

**Comment by ChipsSpectre** [comment]
The following code tries to catch `(a ^ c1) & (a ^ c2)`. Unfortunately, the example from the title does not match.
```
if (match(Op0, m_c_Xor(m_Value(A), m_Value(B))) &&
    match(Op1, m_c_Xor(m_Not(m_Specific(A)), m_Specific(B)))
) {      
  return replaceInstUsesWith(I, Constant::getNullValue(Op0->getType()));
}
```

The code is inserted in InstCombineAndOrXor.cpp, function visitAnd(), line 2556
and is visited by the debugger during compilation of the aforementioned example.

@XChy Can you see a problem in this code? Does it use the correct matching functions?

**Comment by XChy** [comment]
@ChipsSpectre , your code matches `(a ^ b) & (~a ^ b)` but not `(a ^ c1) & (a ^ c2)` I suggest, where c1 and c2 are constants. We need to match `(a ^ c1) & (a ^ c2)` and fold it to 0 if the constant value of c1 equals to that of inverted c2.
