### ISSUE TITLE
Can't take the address of a statement expression result

### ISSUE THREAD

**Issue by aalmkainzi** [llvm/llvm-project#75705]
For example:

```C
int arr[5] = {1, 2, 3, 4, 5};

#define M() \
({ \
    arr[0]; \
})

int main()
{
    int *ptr = &M();
}
```

the above code doesn't compile with Clang, but compiles with GCC.

Tested with clang 17.0.1

**Comment by shafik** [comment]
Duplicate of: https://github.com/llvm/llvm-project/issues/58361
