### ISSUE TITLE
dereferencing a null pointer in a constant expression

### ISSUE THREAD

**Issue by twoscomplement** [llvm/llvm-project#75716]
Should it be possible to dereference a null pointer in a C++20 constant expression?

Consider this c++20 code:

```
struct T {
  constexpr bool isNull() {
    return !this;
  }
};
static_assert(((T*)nullptr)->isNull());

constexpr T* t = nullptr;
static_assert((*t).isNull());
```

I would expect this to not compile due to the dereferencing of a null pointer in a constant expression.

With reference to https://godbolt.org/z/q53rz5d69

clang-17.0.1 produces errors and warning, by default.

By default, gcc-13.2 compiles without warning. -Wall yields a -Wnonnull warning.

msvc 19.38 compiles without warning.

Potentially relevant context:
[Accessing static data members via null pointer](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2748)
[Implicit undefined behavior when dereferencing pointers](https://cplusplus.github.io/CWG/issues/2823.html)

I have submitted the same question for gcc: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113047

**Comment by shafik** [comment]
Given the resolution of the two defect reports you cited clang is correct here. This is undefined behavior and should be rejected as ill-formed in a constant expression context.
