### ISSUE TITLE
[ci] [clang-format] code block wrapping around emoji

### ISSUE THREAD

**Issue by SchrodingerZhu** [llvm/llvm-project#75725]
<img width="852" alt="image" src="https://github.com/llvm/llvm-project/assets/20108837/053acd34-efd5-434e-9a99-0ca398d20c8b">

I suppose the feedback for corrected format should not be wrapped into a code area?

**Comment by DavidSpickett** [comment]
It was due to the way the string was written in the Python file, I fixed this in https://github.com/llvm/llvm-project/commit/428660cfb986dd0a59cd2a16972c5f7109080522.
