### ISSUE TITLE
How does ORCJIT deal with symbols during compilation? What  is the difference between C and C++?

### ISSUE THREAD

**Issue by Thrrreeee** [llvm/llvm-project#75734]
When I try to compile LLVM IR that was compiled from a C++ file, I find that the first time that ORCJIT looks up TLS variables is during the `J->initialize()` phase. However, for a C file, the same operation is performed during the` J->lookup('main') `step, which follows the initialization phase. 
I know that compilers use different methods to compile C and C++ files, because C++ supports overriding but C does not. Therefore, when a compiler deals with symbols from C++, it needs to use mangling methods to ensure that each symbol is unique. So is it maybe caused by this? I cannot understand what the ORCJIT does when it is initialized, especially for symbols.

**Comment by lhames** [comment]
Hi @Thrrreeee. Can you please provide the LLVM version number that you're using, and some example IR that demonstrates the issue that you're seeing?

ORC is agnostic regarding input languages. C++ mangles symbol names to support overloading and templates, but to ORC all symbol names are just strings*.

The `LLJIT::initialize` operation does not initialize ORC, but is responsible for running any static initializers in the input object files. E.g. static constructors in C++ code. To do this it will issue a lookup for any "initializer symbol" in object files that have been added to the JIT. These initializer symbols may in turn depend on TLS variables, in which case the corresponding symbols will be looked up during the initialization process. There is no difference between C and C++ here, except that initializers are rare in C (special syntax is required to use them), but common in C++.

* Side note: ORC does know about linker-level mangling, but this is a relatively simple operation that is distinct from language-level mangling. On Linux linker-level mangling is a no-op. On Darwin it just involves putting an `_` out the front of symbol names.

**Comment by Thrrreeee** [comment]
Hi @lhames .Thank you for your answer that is very useful for me.
I have uploaded my example IR and the source code to my [GitHub repository](https://github.com/Thrrreeee/jit-test). you can try it. The [breakpoint](https://github.com/llvm/llvm-project/blob/fc715e4cd942612a091097339841733757b53824/llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp#L9849) is aimed to know what the difference is between C and C++.
I am looking forward to your reply.

**Comment by lhames** [comment]
Hi @Thrrreeee. The distinction is simply the presence / absence of initializers.

In C++ there are static initializers (see https://github.com/Thrrreeee/jit-test/blob/f334b80ad9e5da2babfb6be1e2c1aa1bd46fc0a3/tls-cpp.ll#L22), so when you call `LLJIT::initialize` we must link the object. As part of linking we will hit your breakpoint, but that's always true.

In C there are no static initializers so we do not link your object until you lookup main.

**Comment by Thrrreeee** [comment]
@lhames. Thanks for your reply, I have understood this process!
