### ISSUE TITLE
Error Building compiler-rt on windows Cannot find source file: asan_lock.h

### ISSUE THREAD

**Issue by nizmogtr** [llvm/llvm-project#75736]
CMake Error at cmake/Modules/AddCompilerRT.cmake:75 (add_library):
  Cannot find source file:

    asan_lock.h
Call Stack (most recent call first):
  lib/asan/CMakeLists.txt:134 (add_compiler_rt_object_libraries)

CMake Error at cmake/Modules/AddCompilerRT.cmake:75 (add_library):
  No SOURCES given to target: RTAsan_dynamic.x86_64
Call Stack (most recent call first):
  lib/asan/CMakeLists.txt:134 (add_compiler_rt_object_libraries)

CMake Error at cmake/Modules/AddCompilerRT.cmake:75 (add_library):
  No SOURCES given to target: RTAsan.x86_64
Call Stack (most recent call first):
  lib/asan/CMakeLists.txt:143 (add_compiler_rt_object_libraries)

CMake Error at cmake/Modules/AddCompilerRT.cmake:75 (add_library):
  No SOURCES given to target: RTAsan_cxx.x86_64
Call Stack (most recent call first):
  lib/asan/CMakeLists.txt:149 (add_compiler_rt_object_libraries)

CMake Error at cmake/Modules/AddCompilerRT.cmake:75 (add_library):
  No SOURCES given to target: RTAsan_static.x86_64
Call Stack (most recent call first):
  lib/asan/CMakeLists.txt:155 (add_compiler_rt_object_libraries)

CMake Error at cmake/Modules/AddCompilerRT.cmake:75 (add_library):
  No SOURCES given to target: RTAsan_preinit.x86_64
Call Stack (most recent call first):
  lib/asan/CMakeLists.txt:161 (add_compiler_rt_object_libraries)

CMake Error at cmake/Modules/AddCompilerRT.cmake:361 (add_library):
  No SOURCES given to target: clang_rt.asan_static-x86_64
Call Stack (most recent call first):
  lib/asan/CMakeLists.txt:242 (add_compiler_rt_runtime)

CMake Error at cmake/Modules/AddCompilerRT.cmake:361 (add_library):
  No SOURCES given to target: clang_rt.asan-preinit-x86_64
Call Stack (most recent call first):
  lib/asan/CMakeLists.txt:250 (add_compiler_rt_runtime)

CMake Generate step failed.  Build files cannot be regenerated correctly

**Comment by DavidSpickett** [comment]
Likely caused by https://github.com/llvm/llvm-project/commit/12ed2c90a105f29b9b2f6056d936f47534d31624.

`asan_lock.h` was reduced to 0 bytes some years ago but not actually removed. I think it can just be removed from the CMake config, though I am not sure why it took 2 weeks for someone to find it given we have bots covering this stuff.

**Comment by DavidSpickett** [comment]
Please re-open if that didn't fix the issue for you. I wonder if you are using a version of CMake that is more strict about these things, which is good if so.

For future reference the two builders I checked were:
https://lab.llvm.org/buildbot/#/builders/120
https://lab.llvm.org/buildbot/#/builders/127

Though the Windows on Arm builder does not enable santitizers and some other components.
