### ISSUE TITLE
clang crashes when performing initialization on invalid code. 

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#75781]
clang crashes on the the following invalid code:

```
template <class T, typename U>
struct A {  T a; U b;};

template<typename K>
struct A<int, int> { int a; K b;};

void s() {
  A<int, int> a{1, 2};
}
```

https://godbolt.org/z/vEh15cEzz

**Comment by shafik** [comment]
This looks like a regression from clang-16: https://godbolt.org/z/5szPKWdnc

The change that brought in the assert was: 632dd6a4ca003

CC @yuanfang-chen

**Comment by shafik** [comment]
Duplicate of: https://github.com/llvm/llvm-project/issues/67173
