### ISSUE TITLE
Readability check to detect `return` from a `void` function

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#75788]
Hi!

We recently came across this type of code and realized that some tool should have caught it:

```cpp
void foo()
{}

void bar()
{
    return foo();
}
```

Turns out no warning in clang or clang-tidy catches this. Maybe we could have a clang-tidy `readability` check for it?

**Comment by philnik777** [comment]
This seems to me like a clang-tidy check, since this is basically formatting and seems to be somewhat opinionated.

**Comment by PiotrZSL** [comment]
To be honest I don't see any issue here.
Lets take even code like this:

```
void f1();

void f2() {
    return f1();
}

void f3(bool b) {
    if (b) return f1();
    return f2();
}
```

f3 would need to be changed into:
```

void f3(bool b) {
    if (b) {
        f1();
        return;
   }
    f2();
}
```

and that's longer.

**Comment by SimplyDanny** [comment]
I think the intention of such a check would be to avoid confusions when at the end of a longer function body an expression is returned even though the function's return type is `void`. Just `return;` always reminds the reader about the expected return type while `return g();` implies something else.

Although the rewritten code may be longer, it is likely to be clearer and less ambiguous.

**Comment by SimplyDanny** [comment]
A new check called `readability-avoid-return-with-void-value` has just been merged.
