### ISSUE TITLE
[DirectX] Support cbuffer layout

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#75833]
Handle the SM 5.1 cbuffer load layout when lowering loads from hlsl.cbufs. See https://reviews.llvm.org/D132986 for one approach to this.

This does not include packoffset, which is covered by #57914.

**Comment by davidcook-msft** [comment]
Issue to be re-assessed

**Comment by bogner** [comment]
This issue was created to follow up on https://reviews.llvm.org/D132986, which was never reviewed. However, basically everything in that change was committed as part of https://reviews.llvm.org/D136031 so this task doesn't seem terribly meaningful or relevant. Closing.
