### ISSUE TITLE
MachO/flat-namespace-dysyms.s test fails on llvm-x86_64-debian-dylib buildbot

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#75850]
This test is failing, because the string dylib appears in the build path, so it's causing the ` --implicit-check-not=dylib ` check to fail.

https://lab.llvm.org/buildbot/#/builders/196/builds/41575

**Comment by smeenai** [comment]
I pushed c77c3663dbea as a short-term fix.

**Comment by tstellar** [comment]
@smeenai Thank you very much.
