### ISSUE TITLE
[clang] clang sometimes parses std::vector as int

### ISSUE THREAD

**Issue by ibequa** [llvm/llvm-project#76045]
I'm using clang to build an AST tree of my C++ header files. When checking a type spelling from a Cursor (say, FIELD_DECL) in some header files, clang returns int instead of expected std::vector, although all the #includes seems to be there.
It seems that this problem reproduces randomly, what could be the cause of it?

**Comment by shafik** [comment]
CC @AaronBallman @erichkeane

**Comment by shafik** [comment]
Do you have a minimal test case? That can be helpful to understand the problem better.

**Comment by ibequa** [comment]
I have found that the problem generally reproduces with class default template arguments. If not provided explicitly in my code: say, for example, std::vector<int, std::allocator<int>>, sometimes clang parses the type as int.

**Comment by erichCompSci** [comment]
Hello, I couldn't believe this was posted yesterday as I was experiencing the exact same issue.  In some of the files I parsed with libclang++ some of the std::vectors would show up as int.  However, after this post and trying to create a "simple" scenario, I discovered that an include error in one of my include headers (i.e I fat fingered the -captial i flag and therefore the include header "could not be found") was causing some of my files to not correctly pick up the std::vector.  I fixed the include bug and then my std::vectors started showing up again.  

I don't know if this is your problem, but I'm posting here because clang kind of continues on and the included file with the header in it didn't feel like it should have impacted the other includes in the header, but it looks like it did.

**Comment by ibequa** [comment]
Providing the default template argument explicitly like std::vector<int, std::allocator<int>> seems to fix the problem. How could that happen?

**Comment by gmelon** [comment]
The same error seems to be happening now.
Is there any progress?

**Comment by erichCompSci** [comment]
Hi, this happens when your clang includes do not include the std libs correctly.  Sometimes you have to pass -I (capital I) to the std lib location directly in the call to clang.  When clang can not identify a struct definition of doesn't error out, it assumes int and moves on.

**Comment by AaronBallman** [comment]
@erichCompSci's explanation is correct -- this is expected behavior for error recovery purposes.

**Comment by gmelon** [comment]
> Hi, this happens when your clang includes do not include the std libs correctly. Sometimes you have to pass -I (capital I) to the std lib location directly in the call to clang. When clang can not identify a struct definition of doesn't error out, it assumes int and moves on.

@erichCompSci, Thank you for your response.

I believe I provided the -I option correctly. I also confirmed that all the necessary headers like string, vector, and memory are present in the folder. However, while types like std::shared_ptr are parsed correctly, types like std::string and std::vector are not. Is there a known solution for this issue as well?

**Comment by AaronBallman** [comment]
What errors are you getting when parsing? It sounds like there's still some sort of issue with includes if part of the STL compiles correctly for you and part does not.

**Comment by boluo250** [comment]
i solved it .
when run program.export env.
export CPLUS_INCLUDE_PATH=/home/slave/CodeAnalysis/llvm-project-llvmorg-15.0.4/build/lib/clang/15.0.4/include:$CPLUS_INCLUDE_PATH

**Comment by Kir1n** [comment]
Did you solve this problem, it also happened to me? I used clang_getDiagnostic to get error message and found clang can't include my head file currently, if it tells you "a.hpp" file not found, you should use -I to include where the head file locates before using clang_parseTranslationUnit.
It seems like the expansion of template is last things of unit building, if you can't include file currently, it just stopped and considered all unfinished template is "int". I know little of that, hope someone can tell me more.
