### ISSUE TITLE
missed optimization: Optimization based on the first of the two conditions

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#76043]
Test case from gcc testsuite:
https://github.com/gcc-mirror/gcc/blob/master/gcc/testsuite/gcc.dg/tree-ssa/phi-opt-11.c
```cpp
int f(int a, int b, int c)
{
  if (a == 0 && b > c)
   return 0;
 return a;
}

int g(int a, int b, int c)
{
  if (a == 42 && b > c)
   return 42;
 return a;
}

int h(int a, int b, int c, int d)
{
  if (a == d && b > c)
   return d;
 return a;
}
```
https://godbolt.org/z/hd8Pb116n

Any of these functions can be optimized to a function which returns `a`. I feel like there may be a duplicate of this issue.

**Comment by nikic** [comment]
Can probably be solved by supporting and/or of conditions for the simplifySelectWithICmpEq() fold.

**Comment by sun-jacobi** [comment]
Hi @nikic @k-arrows  Can I work on this issue ?

**Comment by sun-jacobi** [comment]
Alive2 proof:  https://alive2.llvm.org/ce/z/JeADtD

**Comment by k-arrows** [comment]
> Can I work on this issue ?

Of course you can. There’s no need to rush.
