### ISSUE TITLE
[mlir][spirv] Support function argument decorations

### ISSUE THREAD

**Issue by kuhar** [llvm/llvm-project#76106]
We need to support function argument decorations in `spirv.func` to allow for some pointer types. For example, the spec requires the following:

> If an OpFunctionParameter is a pointer (or array of pointers) in PhysicalStorageBuffer [storage class](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_physical_storage_buffer.html#Storage_Class), then the function parameter must be decorated with exactly one of Aliased or Restrict.

> If an OpFunctionParameter is a pointer (or array of pointers) and its pointee type is a pointer in PhysicalStorageBuffer [storage class](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_physical_storage_buffer.html#Storage_Class), then the function parameter must be decorated with exactly one of AliasedPointer or RestrictPointer.

Note that this is already supported with the `spirv.Variable` op using the following syntax:
```mlir
    %3 = spirv.Variable {aliased_pointer} :
      !spirv.ptr<!spirv.ptr<f32, PhysicalStorageBuffer>, Function>
```

**Comment by sott0n** [comment]
Hi, I'm new to the SPIRV dialect, so I'd like to work on this issue.

**Comment by kuhar** [comment]
> Hi, I'm new to the SPIRV dialect, so I'd like to work on this issue.

Sure @sott0n, feel free to ping me if you need any pointers.

**Comment by kuhar** [comment]
A good starting point would be `llvm-project/mlir/test/Dialect/SPIRV/IR/target-and-abi.mlir` -- we already support some argument attributes like:
```mlir
func.func @interface_var(
    %arg0 : f32 {spirv.interface_var_abi = #spirv.interface_var_abi<(0, 1), Uniform>}
) { return }
```

so what we need to do is to enable the same thing for decoration attributes and make sure we serialize them as `OpDecorate` over `OpFunctionParameter`. The following IR be accepted by `mlir-opt` 
```mlir
spirv.module PhysicalStorageBuffer64 GLSL450 requires #spirv.vce<v1.3,
    [Shader, PhysicalStorageBufferAddresses], [SPV_KHR_physical_storage_buffer]> {

  spirv.func @access(%arg0 : !spirv.ptr<!spirv.struct<(f32)>, PhysicalStorageBuffer> { spirv.decoration = #spirv.decoration<Aliased>}) -> f32 "None" {
    %idx = spirv.Constant 0 : i32
    %result = spirv.AccessChain %arg0[%idx] : !spirv.ptr<!spirv.struct<(f32)>, PhysicalStorageBuffer>, i32
    %ptr = spirv.Load "PhysicalStorageBuffer" %result : f32
    spirv.ReturnValue %ptr : f32
  }
}
```

and pass validation with:
```shell
bin/mlir-translate --no-implicit-module --serialize-spirv test.mlir  -o test.spv
spirv-val test.spv
```

**Comment by sott0n** [comment]
I'm working on https://github.com/llvm/llvm-project/pull/76353

I have completed support for function argument decoration and am now working on implementing serialization to facilitate passing spirv-val.

**Comment by sott0n** [comment]
I've finished implementing the serializer and deserializer. However, spirv-val is causing an error with the OpLoad. The SPIR-V dialect needs to support Memory Operands with any operations.

SPIR-V's error:
```
spirv-val test.spv
error: line 19: Memory accesses with PhysicalStorageBuffer must use Aligned.
  %12 = OpLoad %float %11
```

This PR supported the decoration for the function's parameters (`OpDecorate %6 Aliased`), but we have to implement the Memory Operands with the OpLoad to pass validation.

```
spirv-dis test.spv                                                                                            
; SPIR-V
; Version: 1.3
; Generator: Khronos; 22
; Bound: 13
; Schema: 0
               OpCapability Shader
               OpCapability PhysicalStorageBufferAddresses
               OpExtension "SPV_KHR_physical_storage_buffer"
               OpMemoryModel PhysicalStorageBuffer64 GLSL450
               OpName %access "access"
               OpDecorate %_struct_4 Block
               OpDecorate %6 Aliased
      %float = OpTypeFloat 32
  %_struct_4 = OpTypeStruct %float
%_ptr_PhysicalStorageBuffer__struct_4 = OpTypePointer PhysicalStorageBuffer %_struct_4
          %1 = OpTypeFunction %float %_ptr_PhysicalStorageBuffer__struct_4
       %uint = OpTypeInt 32 0
     %uint_0 = OpConstant %uint 0
%_ptr_PhysicalStorageBuffer_float = OpTypePointer PhysicalStorageBuffer %float
     %access = OpFunction %float None %1
          %6 = OpFunctionParameter %_ptr_PhysicalStorageBuffer__struct_4
          %7 = OpLabel
         %11 = OpAccessChain %_ptr_PhysicalStorageBuffer_float %6 %uint_0
         %12 = OpLoad %float %11
               OpReturnValue %12
```

**Comment by kuhar** [comment]
> This PR supported the decoration for the function's parameters (`OpDecorate %6 Aliased`), but not yet implemented the `Aligned` in the OpLoad when the operand is the physical buffer pointer.

Good point, I think it's just a bug in my example though, isn't it? The input mlir should have been:
```mlir
%ptr = spirv.Load "PhysicalStorageBuffer" %result  ["Aligned", 4] : f32
```

**Comment by sott0n** [comment]
Yes, I think it's correct. I'd like to work on this issue.
