### ISSUE TITLE
'aka' text can make diagnostic unreadable

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7610]
|  |  |
| --- | --- |
| Bugzilla Link | [7238](https://llvm.org/bz7238) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @chandlerc,@lattner,@DougGregor |

## Extended Description 
For example, I got:

.../file.cc:100:46: error: no viable conversion from 'iterator' (aka 'dense_hashtable_iterator<std::pair<basic_string<char, std::char_traits<char>, std::allocator<char> > const, int>, basic_string<char, std::char_traits<char>, std::allocator<char> >, __gnu_cxx::hash<basic_string<char, std::char_traits<char>, std::allocator<char> > >, dense_hash_map<basic_string<char, std::char_traits<char>, std::allocator<char> >, int, __gnu_cxx::hash<basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<basic_string<char, std::char_traits<char>, std::allocator<char> > >, libc_allocator_with_realloc<std::pair<basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::SelectKey, dense_hash_map<basic_string<char, std::char_traits<char>, std::allocator<char> >, int, __gnu_cxx::hash<basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<basic_string<char, std::char_traits<char>, std::allocator<char> > >, libc_allocator_with_realloc<std::pair<basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::SetKey, std::equal_to<basic_string<char, std::char_traits<char>, std::allocator<char> > >, libc_allocator_with_realloc<std::pair<basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >') to 'hash_map<string, int>::const_iterator' (aka '_Hashtable_const_iterator<std::pair<basic_string<char, std::char_traits<char>, std::allocator<char> > const, int>, basic_string<char, std::char_traits<char>, std::allocator<char> >, __gnu_cxx::hash<basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> >, std::equal_to<basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<int> >')
             it = item->diagnostics.begin(), end = item->diagnostics.end();
                                             ^     ~~~~~~~~~~~~~~~~~~~~~~~

Unfortunately, I don't have a good suggestion for deciding when to omit the aka text.

**Comment by philnik777** [comment]
This has been improved by adding `[[clang::preferred_name]]`. This isn't a general solution, but I don't think a general solution is possible in this case. I think this can be closed, since there is no reproducer for the specific case.
