### ISSUE TITLE
[Reassociate] Missing optimization: fold `div(v, a) * b + rem(v, a)` to `div(v, a) * (b - a) + v`

### ISSUE THREAD

**Issue by XChy** [llvm/llvm-project#76128]
Alive2 proof: https://alive2.llvm.org/ce/z/7SnGmc

### Description:

```llvm
define i32 @src(i32 noundef %val) {
entry:
  %div = udiv i32 %val, 10
  %shl = shl i32 %div, 4
  %rem = urem i32 %val, 10
  %add = or disjoint i32 %shl, %rem
  ret i32 %add
}
```
can be folded to:
```llvm
define i32 @tgt(i32 noundef %val) {
entry:
  %div = udiv i32 %val, 10
  %reass.mul = mul nuw i32 %div, 6
  %i = add i32 %reass.mul, %val
  ret i32 %i
}
```
This is a simple example. `or disjoint` can be replaced with `add nsw nuw`, `shl 4` can be replaced with equivalent `mul 16`, and constants here can be replaced with other simple constants: https://alive2.llvm.org/ce/z/qmYLyJ
I don't replace constants with arguments because I haven't figure out completetly what condition is needed for this fold yet.

### Real-world motivation

This snippet of IR is derived from [linux/lib/bcd.c](https://github.com/torvalds/linux/blob/master/lib/bcd.c#L11C17-L11C17) (after O3 pipeline).
The example above is a reduced version. If you're interested in the original suboptimal IR and optimal IR, see also:https://godbolt.org/z/hra9qYbY7

**Let me know if you can confirm that it's an optimization opportunity, thanks.**

**Comment by dtcxzyw** [comment]
We should teach `ReassociatePass` to treat a `disjoint or` as an `add`.
Alive2: https://alive2.llvm.org/ce/z/GmcPV9

**Comment by XChy** [comment]
This fold is true for both sdiv/srem and udiv/sdiv when there are no nowrap flags: https://alive2.llvm.org/ce/z/JX_UVs

**Comment by dtcxzyw** [comment]
> We should teach `ReassociatePass` to treat a `disjoint or` as an `add`. Alive2: https://alive2.llvm.org/ce/z/GmcPV9

Sorry, `DivRemPairPass` runs after `ReassociatePass` in the optimization pipeline. I am planning to do this in `InstCombine`.

**Comment by XChy** [comment]
> > We should teach `ReassociatePass` to treat a `disjoint or` as an `add`. Alive2: https://alive2.llvm.org/ce/z/GmcPV9
> 
> Sorry, `DivRemPairPass` runs after `ReassociatePass` in the optimization pipeline. I am planning to do this in `InstCombine`.

Oh, I think this fold is related to the machine specific expansion, see also: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113071. It is profitable more probably when `DivRemPairPass` expands `rem`.

**Comment by dtcxzyw** [comment]
> > > We should teach `ReassociatePass` to treat a `disjoint or` as an `add`. Alive2: https://alive2.llvm.org/ce/z/GmcPV9
> > 
> > 
> > Sorry, `DivRemPairPass` runs after `ReassociatePass` in the optimization pipeline. I am planning to do this in `InstCombine`.
> 
> Oh, I think this fold is related to the machine specific expansion, see also: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113105. It is profitable more probably when `DivRemPairPass` expands `rem`.

I think `TTI.hasDivRemOp` will address this problem.

**Comment by dtcxzyw** [comment]
> > > > We should teach `ReassociatePass` to treat a `disjoint or` as an `add`. Alive2: https://alive2.llvm.org/ce/z/GmcPV9
> > > 
> > > 
> > > Sorry, `DivRemPairPass` runs after `ReassociatePass` in the optimization pipeline. I am planning to do this in `InstCombine`.
> > 
> > 
> > Oh, I think this fold is related to the machine specific expansion, see also: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113105. It is profitable more probably when `DivRemPairPass` expands `rem`.
> 
> I think `TTI.hasDivRemOp` will address this problem.

https://github.com/llvm/llvm-project/blob/5841140e38c94f3d2b29354f67e70803d88ce174/llvm/include/llvm/Transforms/InstCombine/InstCombiner.h#L48-L51
TargetTransformInfo is not allowed to be used for target-independent transform in InstCombine.
