### ISSUE TITLE
Clang version confusion in build

### ISSUE THREAD

**Issue by pogo59** [llvm/llvm-project#76154]
It looks like the built executable has a version suffix that doesn't match reality.
```
~/projects/scratch$ clang --version
clang version 18.0.0git (https://github.com/llvm/llvm-project.git 591fc4f5242adf2f4d2dbd301c21be578b9b9278)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/probinson/projects/llvm-org/build/main-ll/bin
~/projects/scratch$ ll clang
lrwxrwxrwx 1 probinson rd 8 Dec 21 00:24 /home/probinson/projects/llvm-org/build/main-ll/bin/clang -> clang-15*
```
18 != 15 last I checked.

@tstellar @tru

**Comment by tru** [comment]
Seems odd. Maybe some stale file somewhere? I never seen this before. Does it do the same if you delete `CMakeCache.txt`?

**Comment by tstellar** [comment]
I've seen this before, there is some bug in the build system that causes this.
