### ISSUE TITLE
Clang++ not detecting ambiguous templates

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7623]
|  |  |
| --- | --- |
| Bugzilla Link | [7251](https://llvm.org/bz7251) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@efriedma-quic |

## Extended Description 
The following is accepted by clang++, but rejected by g++ and icpc as an ambiguous reference as both 'int a' and 'template<T> a' are in the global namespace.

namespace A {
template<typename T> struct a { };
}

using namespace A;
int a;

/* a<int> should be an ambiguous reference */
a<int> b;

clang++ -v
clang version 2.0 (trunk 103456)
Target: x86_64-apple-darwin10
Thread model: posix

**Comment by Endilll** [comment]
Fixed as of Clang 3.0.
https://godbolt.org/z/7En361Ezv
