### ISSUE TITLE
[X86] Matching bit test and bit set patterns appear not to work

### ISSUE THREAD

**Issue by Bryce-MW** [llvm/llvm-project#76265]
I've been profiling some code that uses a large array of bits to test if a 32 bit value has been seen before or not. I noticed that neither Clang nor GCC compiles my bit testing and setting code as I expect. Clang produces better code overall (yay!) including here.

For the test, it compiles to a mov from memory and a BT even though the load should be able to be folded into the BT. I didn't look too far into the why for that. Based on a quick look at uops.info, it could be that doing the BT from memory is slower. Here's a [quick example](https://godbolt.org/z/e8vqq1545). What I find more interesting is the set.

The set doesn't get converted to a BTS at all. [Here's that example](https://godbolt.org/z/Wvo9nWMGv). As far as I can tell, this is supposed to happen. I've never looked at backend code before but it seems like [this section](https://github.com/llvm/llvm-project/blob/52b7045fbb70571e09c0ad3be7bd3f0c1acccffa/llvm/lib/Target/X86/X86InstrCompiler.td#L1906-L1930) should be detecting this pattern. It seems like there is also [some code](https://github.com/llvm/llvm-project/blob/04c473bea3e0f135432698fcaafab52e1fe1b5ec/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp#L719-L746) to make sure that a load isn't folded in too early. In this case, it's a RMW so I would expect the load/store to be folded at some point even if the replacement is made.

Both of these have the same result if you and the bit index by 63 which is expected and the replacement should be able to see through that as well.

Interestingly enough, Intel defines intrinsics for these, `_bittest64` and `_bittestandset64`. Clang accepts these with `-fms-extensions` for some reason and produces inline assembly in the IR output. There are some _interesting_ consequences of this and of  trying to do it with inline assembly yourself but that's for another issue.

**Comment by topperc** [comment]
As you found on uops.info BT, BTS, BTC, BTR from memory are all slow. The definition of those instructions allow indices larger than the register size to adjust the address. This is implemented in microcode on Intel CPUs using extra uops to extract the high bits of the index and add them into the address. I think its 11 uops which I think is more uops that the separate instructions. Because of this we avoid using them.

For the set case, the load+or+store pattern matches before the BTS pattern in X86InstrCompiler.td gets checked.

**Comment by Bryce-MW** [comment]
Thanks for the explanation! I seems that I did not read the manual carefully enough. It's too bad that even in the exact case that these instructions seem meant for (using an array of bits), it takes more uops (and latency / throughput) to use these instructions than doing the shifts and masks yourself.
