### ISSUE TITLE
`bugprone-implicit-widening-of-multiplication-result` should suggest suffix instead of cast if using literals

### ISSUE THREAD

**Issue by felix642** [llvm/llvm-project#76313]
Currently the check `bugprone-implicit-widening-of-multiplication-result` will suggest to add `static_cast` to multiplication if the result is stored into a wider type. 

The check should instead suggest to add the proper suffix if the operation contains `literals` rather than variables.
So the following code:
```
uint64_t fn()
{
    return 1024 * 1024;
}
```

Shoud look like this after applying the suggested fix:
```
uint64_t fn()
{
    return 1024LU * 1024;
}
```

This should be configurable to keep the option to add `static_cast` if this is the preferred method in a codebase.

godbolt: https://godbolt.org/z/Pc1K1563s

**Comment by PeterFeicht** [comment]
That may or may not work depending on bitness. `intptr_t` could be `long` or `long long`, for example.

**Comment by felix642** [comment]
You're right, I didn't think of this at the time.
The proposed method is not portable and might not work if the code is compiled for different machines.
Since we already have a solution that works for all cases, I think it would be wiser to close this issue and not implement it. 

Thank you for your input @PeterFeicht
