### ISSUE TITLE
clang trunk does not compile overloaded member functions with ref-qualifier

### ISSUE THREAD

**Issue by forworldm** [llvm/llvm-project#76358]
```c++
struct C {
    template<int> void f() && {}
    template<typename T> void f() const {}
};
```
```
<source>:3:31: error: cannot overload a member function without a ref-qualifier with a member function with ref-qualifier '&&'
    3 |     template<typename T> void f() const {}
      |                               ^
<source>:2:24: note: previous declaration is here
    2 |     template<int> void f() && {}
      |                        ^
1 error generated.
Compiler returned: 1
```

see https://godbolt.org/z/Kv83s6oY3

**Comment by DimitryAndric** [comment]
This regressed as a side effect of `llvmorg-18-init-07480-g`af4751738db ("[C++] Implement "Deducing this" (P0847R7)") by @cor3ntin (cc @AaronBallman).

I think it should still accept the construction used here? It always worked in the past, and appears to break even compilation of older llvm versions!

**Comment by DimitryAndric** [comment]
Specifically, it seems to be caused by the moving of the block in `IsOverloadOrOverrideImpl` at https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaOverload.cpp#L1346, that has:

```c++
// If the function is a class member, its signature includes the
// cv-qualifiers (if any) and ref-qualifier (if any) on the function itself.
```

and emits `err_ref_qualifier_overload` in this case. The block used to be in `Sema::IsOverload()` and was subtly changed, I guess.

**Comment by cor3ntin** [comment]
We should probably check the template parameter list before the check of signature as two functions with different template head are not overloads

**Comment by DimitryAndric** [comment]
How problematic is it to temporarily revert af4751738db89a142a8880c782d12d4201b222a8, until this problem can be fixed? I'm encountering the `cannot overload a member function without a ref-qualifier with a member function with ref-qualifier '&&'` error in quite a few packages, for example SciPy (from https://scipy.org/).

**Comment by cor3ntin** [comment]
Pretty problematic and disruptive given the fix should be easy... I'll get on it...

**Comment by DimitryAndric** [comment]
Thanks, that seems to work fine!
