### ISSUE TITLE
[RISCV]Do you plan to add CodeGen of RV32E and ilp32e ABIs?

### ISSUE THREAD

**Issue by iiiyours** [llvm/llvm-project#76430]

**Comment by wangpc-pp** [comment]
Yes, I'm going to.

Previously, the LLVM community is migrating form Phabricator to Github PR but I think we have made some progresses before migration (though [the Phabricator server is inaccessible](https://discourse.llvm.org/t/cant-access-https-reviews-llvm-org/75905) now).

I will continue to push it after majority of the community are back from Christmas and New Year holidays.

**Comment by athei** [comment]
Meaning you will open a PR here with the patch that is now lost due to the Phabricator shutdown?

**Comment by wangpc-pp** [comment]
I have already created a PR: https://github.com/llvm/llvm-project/pull/76777
I hope that we can make more progresses and land it ASAP. :-)

**Comment by wangpc-pp** [comment]
Close as we have committed https://github.com/llvm/llvm-project/commit/3ac9fe69f70a2b3541266daedbaaa7dc9c007a2a.
