### ISSUE TITLE
RecursiveASTVisitor should visit TypeLoc instead of Type

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7650]
|  |  |
| --- | --- |
| Bugzilla Link | [7278](https://llvm.org/bz7278) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
TypeLoc contains more information than Type (e.g. the source location where a type is used).  This information is useful to many kinds of AST visitors.  We should switch RecursiveASTVisitor to visit TypeLocs instead.

**Comment by Endilll** [comment]
CC @AaronBallman

**Comment by AaronBallman** [comment]
It visits both `QualType` and `TypeLoc`: https://github.com/llvm/llvm-project/blob/299d710e3d83e1f1867ed208b1d959603fd2cb41/clang/include/clang/AST/RecursiveASTVisitor.h#L222 -- which one you use depends on your usage scenario. I'm closing this as completed, however, if you had something else in mind, feel free to reopen the issue with more information.
