### ISSUE TITLE
[C++20] [Modules] Clang produce incorrect linkage if we export things in language linkage

### ISSUE THREAD

**Issue by JohelEGP** [llvm/llvm-project#76526]
A _linkage-specification_ is a _name-declaration_
and has a terminal `extern` _unevaluated-string_ _name-declaration_.
An _export-declaration_ isn't a _name-declaration_,
but Clang accepts one after a _linkage-specification_.

GCC diagnoses it: <https://compiler-explorer.com/z/nozWPbxbG>.
But Clang accepts it with an unexpected result: <https://compiler-explorer.com/z/eefn3sWMs>.

Note that if the `export` comes before the `extern`, both accept.
GCC: <https://compiler-explorer.com/z/Y3zn6EEKK>.
Clang: <https://compiler-explorer.com/z/zb5qhxYEa>.

```C++
module;
#include <iostream>
export module module_utility;
extern "C" __attribute__ ((visibility ("default")))
export void utility() {
  std::cout << "Hello from utility!" << std::endl;
}
```

**Comment by shafik** [comment]
CC @ChuanqiXu9

**Comment by ChuanqiXu9** [comment]
There are questions:
(1) Is it valid to export things from language linkage? From https://godbolt.org/z/hnx3KToKc it looks like both GCC and clang accept it. (I don't know how to invoke msvc for modules in godbolt.) And I remember I checked the wording. There is no saying that we can't export things from language linkage.
(2) If the answer of (1) is yes, then the question becomes why the result is not good.

**Comment by JohelEGP** [comment]
We can't use the IDE tree feature of Compiler Explorer with MSVC: <https://github.com/compiler-explorer/compiler-explorer/discussions/2763#discussioncomment-1393814>.

>  (2) If the answer of (1) is yes, then the question becomes why the result is not good.

The result is good.
But if you put the `export` after the language linkage,
that's not valid grammar and Clang should reject just like GCC,
rather than accept and give an unexpected answer.

**Comment by ChuanqiXu9** [comment]
> But if you put the `export` after the language linkage, that's not valid grammar and Clang should reject just like GCC, rather than accept and give an unexpected answer.

Yeah, this is my first question. It looks like GCC will accept it in my example. And I need to figure why it is allowed or not from the standard wording.

**Comment by JohelEGP** [comment]
Well, in the case of a block, at least it's valid grammar.

**Comment by JohelEGP** [comment]
I remember that _name-declaration_ was introduced to avoid `export` on declarations without a name.
A _linkage-specification_ is a _name-declaration_, so we can `export` it.
If a single `export extern "C" ...` is valid,
it makes sense that `extern "C" { export ...; }` also would.

**Comment by ChuanqiXu9** [comment]
So `extern "C" { export ...; }` is valid  but `extern "C" export ...` is not? This is pretty odd to me. I need to investigate more on that...

**Comment by JohelEGP** [comment]
Turns out I was wrong.
An _export-declaration_ is a _special-declaration_ which is a _declaration_.

**Comment by ChuanqiXu9** [comment]
So the problem becomes why the code generated by clang give unexpected result.

**Comment by ChuanqiXu9** [comment]
I take a quick look at this. The reason seems straightforward but not so easy to find the place to fix it.

The reason why the code generated by:

```
extern "C" __attribute__ ((visibility("default"))) 
export void func() {}
```

have incorrect visibility is that the compiler think the attribute is set to the export decl instead of the function decl incorrectly. In another word, both of the following case can work:

```
export extern "C" __attribute__ ((visibility("default")))  void func() {}
```
or 

```
extern "C" 
export __attribute__ ((visibility("default")))  void func() {}
```

since the attribute is set on the function decl now.

**Comment by ChuanqiXu9** [comment]
However, when I double check the wordings I find the definition of `export-decl` doesn't contain attributes-seq: http://eel.is/c++draft/module.interface#nt:export-declaration.
And all other declarations which can be decorated by attributes defines the attributes-seq in their definitions, like http://eel.is/c++draft/dcl.pre#nt:nodeclspec-function-declaration,
http://eel.is/c++draft/dcl.fct.def.general#nt:function-definition, http://eel.is/c++draft/dcl.spec.general#nt:decl-specifier-seq, http://eel.is/c++draft/dcl.pre#nt:simple-declaration,
http://eel.is/c++draft/namespace.def.general#nt:named-namespace-definition

So if I read correctly, the current behavior of the clang compiler is good. Maybe it will be better to emit a warning in such cases.

I'll close the issue as not-planned. Feel free to ask for reopening this issue if you have different opinions.
