### ISSUE TITLE
[Flang] Support multiple spaces in compiler directives

### ISSUE THREAD

**Issue by eschnett** [llvm/llvm-project#76537]
I am using Flang 17.0.6, built via MacPorts on macOS. I find that the directive
```
!dir$ ignore_tkr(tkr) buf
```
cannot have multiple spaces between the `!dir$` and the `ignore` tokens, this leads to a confused error `error: expected end of statement`.

It would be nice if this was supported. The Fortran language supports arbitrary amounts of white space where a single white space is allowed, and it would be nice if that was also possible in this directive.

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/76541

**Comment by klausler** [comment]
Fix has been merged into llvm-project/main.
