### ISSUE TITLE
clang is suboptimal for `log(pow(x, y))` with fast-math

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#76549]
Test case:
https://godbolt.org/z/1fvYPxY37
```c
#include<math.h>

double test1(double x) { 
  return log(pow(x, -3)); 
}

double test2(double x) { 
  return -3 * log(x); 
}
```

My expectation is that the output of `test1` will be the same as `test2`.

**Comment by tanmaysachan** [comment]
@EugeneZelenko Could I be assigned this issue? I'm adding a function to `InstCombineMulDivRem.cpp` (since that's where other opts relating to pow and exp live) and adding a test for it.
