### ISSUE TITLE
[clang][ARM] -O1 vectorize will get wrong result

### ISSUE THREAD

**Issue by CoTinker** [llvm/llvm-project#76556]
demo.c

```
#include<stdio.h>
#include<arm_neon.h>

typedef unsigned int __uint32_t;
typedef float float32_t;
typedef __attribute__((neon_vector_type(2))) uint32_t uint32x2_t;
typedef __attribute__((neon_vector_type(2))) float32_t float32x2_t;
uint32x2_t vector_res_uint32x2;
float32x2_t vector_float32x2;

static uint32_t result_uint32x2[2];
uint32_t expected_uint32x2 [] = { 0x0, 0x5 };


int main()
{
	vector_float32x2 = __extension__ ({ 
		float32x2_t __ret; 
		float32_t __s0 = -15.3f; 
		float32x2_t __s1 = vector_float32x2; 
		__ret = (float32x2_t) __builtin_neon_vset_lane_f32(__s0, (float32x2_t)__s1, 0); 
		__ret; 
	});
    vector_float32x2 = __extension__ ({
		float32x2_t __ret;
		float32_t __s0 = 5.3f;
		float32x2_t __s1 = vector_float32x2;
		__ret = (float32x2_t) __builtin_neon_vset_lane_f32(__s0, (float32x2_t)__s1, 1);
		__ret; 
	});
   
    // printf("%f %f\n", vector_float32x2[0], vector_float32x2[1]);
	vector_res_uint32x2 = vcvt_u32_f32(vector_float32x2);
	__extension__ ({ 
    	uint32x2_t __s1 = vector_res_uint32x2;
		__builtin_neon_vst1_v(result_uint32x2, (int8x8_t)__s1, 18); 
	}); 
    printf("%u %u\n", result_uint32x2[0], result_uint32x2[1]);
}
```
compile command:
right result:
```
% clang demo.c -static -lm -o test  -O0 -march=armv8-a
% ./test
0 5
```

wrong result:
```
% clang demo.c -static -lm -o test  -O1 -march=armv8-a
% ./test
5 5
```

I find the optimize pass that cause this problem is `InlinerPass`
https://godbolt.org/z/dfqPjT7WK

**Comment by fhahn** [comment]
It looks like you are trying to convert a float to an integer that doesn't fit into the target type (-15.3 cannot be converted to an unsigned int). This is an issue in the input source code

Before inlining `  %call = call fastcc <2 x i32> @vcvt_u32_f32(<2 x float> noundef <float 0xC02E9999A0000000, float 0x4015333340000000>)
`

it looks like at least one of them cannot be converted and produces poison: https://alive2.llvm.org/ce/z/UadnY_

**Comment by CoTinker** [comment]
With 32 lines of code commented out, the optimization generates the `vcvt.u32.f32` neon instruction, which converts negative floating point numbers to zeros. Is llvm wrong to produce poison for negative floating point optimizations?
