### ISSUE TITLE
 Building bug in clang arm64 cc1: error: unknown value 'cortex-a77.cortex-a55' for '-mcpu' 

### ISSUE THREAD

**Issue by AlirezaParsi** [llvm/llvm-project#76570]
when i try to build my kernel with clang arm64 (native build)(version=16 , 17 and 18) i got this error :
`
cc1: error: unknown value 'cortex-a77.cortex-a55' for '-mcpu'
cc1: note: valid arguments are: cortex-a34 cortex-a35 cortex-a53 cortex-a57 cortex-a72 cortex-a73 thunderx thunderxt88p1 thunderxt88 octeontx octeontx81 octeontx83 thunderxt81 thunderxt83 ampere1 ampere1a emag xgene1 falkor qdf24xx exynos-m1 phecda thunderx2t99p1 vulcan thunderx2t99 cortex-a55 cortex-a75 cortex-a76 cortex-a76ae cortex-a77 cortex-a78 cortex-a78ae cortex-a78c cortex-a65 cortex-a65ae cortex-x1 cortex-x1c ares neoverse-n1 neoverse-e1 octeontx2 octeontx2t98 octeontx2t96 octeontx2t93 octeontx2f95 octeontx2f95n octeontx2f95mm a64fx tsv110 thunderx3t110 zeus neoverse-v1 neoverse-512tvb saphira cortex-a57.cortex-a53 cortex-a72.cortex-a53 cortex-a73.cortex-a35 cortex-a73.cortex-a53 cortex-a75.cortex-a55 cortex-a76.cortex-a55 cortex-r82 cortex-a510 cortex-a710 cortex-a715 cortex-x2 cortex-x3 neoverse-n2 demeter neoverse-v2 generic; did you mean 'cortex-a75.cortex-a55'?`

i dont have this problem with x86 clang toolchain (16-18) also my build script is like this :

   1   │ #/bin/bash
   2   │ export ARCH=arm64
   3   │ export SUBARCH=ARM64
   4   │ export KBUILD_BUILD_HOST=Ubuntu
   5   │ export KBUILD_BUILD_USER="Aliza"
   6   │ #export CFLAGS=-march=native
   7   │ make O=./out mrproper vendor/alioth_defconfig cc=clang
   8   │ make O=./out -j$(nproc --all) cc=clang

im sure this is clang bug not my kernel and my method because i build 4 different kernels with this clang and this method.

![image](https://github.com/llvm/llvm-project/assets/29276037/b15a8cb1-72c4-41ec-a60e-875ef9a0db22)

os info :
![image](https://github.com/llvm/llvm-project/assets/29276037/b7ed4a9c-b547-483e-a5a0-5728c6d7fea7)
installing mode : chroot on phone
more detail : 

Ubuntu clang version 16.0.6 (15)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Ubuntu clang version 17.0.6 (++20231208085918+6009708b4367-1~exp1~20231208090013.44)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Ubuntu clang version 18.0.0 (++20231228083416+9e439a353918-1~exp1~20231228203527.218)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by MaskRay** [comment]
Both -mcpu=cortex-a55 and -mcpu=cortex-a77 are good, but -mcpu=cortex-a77.cortex-a55 is invalid. Your kernel configuration may have a bug.

**Comment by AlirezaParsi** [comment]
> Both -mcpu=cortex-a55 and -mcpu=cortex-a77 are good, but -mcpu=cortex-a77.cortex-a55 is invalid. Your kernel configuration may have a bug.

by the way with google clang and other clangs(not arm64) i xan build it with no problems
