### ISSUE TITLE
clang is suboptimal for `x / sqrt(y / z)` with fast-math

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#76605]
Test case:
https://godbolt.org/z/joGE9G4KM
```c
#include<math.h>

double test_sqrt1(double x, double y, double z) { 
  return x / sqrt(y / z); 
}

double test_sqrt2(double x, double y, double z) { 
  return x * sqrt(z / y); 
}
```

My expectation is that the output of `test_sqrt1` will be the same as `test_sqrt2`. The same transformatin is true not only for `sqrt` but also for `cbrt`.

**Comment by zjaffal** [comment]
looking into this, 
For this I guess the assumption is that both the first and second div have the following are true? 
- hasAllowReassoc
- hasAllowReciprocal

**Comment by k-arrows** [comment]
The patch was reverted by https://github.com/llvm/llvm-project/commit/f022aaf4e722eae9d0feaf7715a5d8960f4d017b.

**Comment by dtcxzyw** [comment]
> The patch was reverted by [f022aaf](https://github.com/llvm/llvm-project/commit/f022aaf4e722eae9d0feaf7715a5d8960f4d017b).

cc @arsenm

**Comment by zjaffal** [comment]
fix https://github.com/llvm/llvm-project/pull/81970

**Comment by k-arrows** [comment]
The fix has been merged. I will close this issue.
