### ISSUE TITLE
[InstCombine] Missed optimization: fold `other_cond && (a s> -1) && a s< b` to `other_cond && a u< b` when `b` is a specific constant

### ISSUE THREAD

**Issue by XChy** [llvm/llvm-project#76623]
Alive2 proof: https://alive2.llvm.org/ce/z/DT9eDZ

### Motivating example:

```llvm
define i1 @src(i32 %a, i1 %other_cond) {
entry:                                      
  %cmp1 = icmp sgt i32 %a, -1
  %or.cond = select i1 %other_cond, i1 %cmp1, i1 false
  %cmp2 = icmp slt i32 %a, 10086
  %ret = select i1 %or.cond, i1 %cmp2, i1 false
  ret i1 %ret
}
```
can be folded to:
```llvm
define i1 @tgt(i32 %a, i1 %other_cond) {
entry:                                      
  %or.cond = icmp ult i32 %a, 10086
  %ret = select i1 %other_cond, i1 %or.cond, i1 false
  ret i1 %ret
}
```
However, it folds if we replace the logical `and` with a bitwise `and`. I thought that Reassociate should be to blame, but [godbolt](https://godbolt.org/z/fY5vPx951) told me that similar fold for bitwise `and` is handled by InstCombine. Therefore, I tag InstCombine here.

### Real-world motivation

This snippet of IR is derived from [qemu/net/util.c@net_parse_macaddr](https://github.com/qemu/qemu/blob/7425b6277f12e82952cede1f531bfc689bf77fb1/net/util.c) (after O3 pipeline).
The example above is a reduced version. If you're interested in the original suboptimal IR and optimal IR, see also:https://godbolt.org/z/Ea8GGxKba

**Let me know if you can confirm that it's an optimization opportunity, thanks.**

**Comment by dtcxzyw** [comment]
It would be fixed by #76621 if we know that `select (icmp sgt i32 %a, -1), (icmp slt i32 %a, 10086), false` can be simplified into `icmp ult i32 %a, 10086`.

**Comment by nikic** [comment]
For cases with a bitwise outer operation, this is handled by https://github.com/llvm/llvm-project/blob/2c2de4b20ef6792e8bf437b02fbb94e3c20bdaff/llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp#L2565. We're missing handling for the case of a logical outer operation, I believe.

**Comment by XChy** [comment]
I think this issue can be handled easier. Note that:
`(A && B) && C --> A && (B & C)` if "C is poison" implies "B is poison": https://alive2.llvm.org/ce/z/JCR3XC
I realized this after I handicrafted a bunch of proofs on this...

**Comment by XChy** [comment]
I will try to file a simple solution for it. Though I also have one much complex patch.
