### ISSUE TITLE
Sometimes the 'aka' type is better than the user's typedef.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7662]
|  |  |
| --- | --- |
| Bugzilla Link | [7290](https://llvm.org/bz7290) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @Quuxplusone,@DougGregor |

## Extended Description 
For example:

$ cat test.cc
```c++
template<typename T> struct identity { typedef T type; };
template <typename T>
T max(T lhs, typename identity<T>::type rhs);

void Use() {
  max(3, "Oops");
}
```
$ ./clang++ -fsyntax-only test.cc
```
test.cc:6:3: error: no matching function for call to 'max'
  max(3, "Oops");
  ^~~
test.cc:3:3: note: candidate function [with T = int] not viable: no known conversion from 'char const [5]' to 'typename identity<int>::type' (aka 'int') for 2nd argument
T max(T lhs, typename identity<T>::type rhs);
  ^
1 error generated.
```
$ 

We might guess this based on the 'aka' type being shorter, but that won't always be right. I suspect it'll be useful to have an attribute to let the user tell clang which type to present.

**Comment by philnik777** [comment]
I'm also a bit confused what the problem here is. It seems to me like a really good option to show both versions, allowing the user to see both. Closing for now. If there is any more information we can reopen this.
