### ISSUE TITLE
[ValueTracking] Remove SPF support from `computeKnownBitsFromOperator` breaks Windows build

### ISSUE THREAD

**Issue by ChipsSpectre** [llvm/llvm-project#76639]
The windows build at 20:42 was running (in spite of some test errors): [BuildKite](https://buildkite.com/llvm-project/github-pull-requests/builds/25584#018cbc40-0b80-4045-8d9c-6efc31ae1d27)

However, the windows build began to fail at 20:45 [BuildKite](https://buildkite.com/llvm-project/github-pull-requests/builds/25585#018cbc42-72cc-4679-95df-84bb08de1027).

@dtcxzyw Could you check whether your contribution [**ValueTracking] Remove SPF support from computeKnownBitsFromOperator** [Link to Commit](https://github.com/llvm/llvm-project/commit/2c2de4b20ef6792e8bf437b02fbb94e3c20bdaff) might have had an influence on the build on Windows?

**Comment by dtcxzyw** [comment]
Thank you for reporting this!
I don't think it is related to my commit. Probably it is a MLIR issue.
