### ISSUE TITLE
[instcombine] fold cmp of max/min with different sign

### ISSUE THREAD

**Issue by sftlbcn** [llvm/llvm-project#76672]
https://godbolt.org/z/6dEKsTW8K
cvp makes the cmp unsigned

```
inline int m(int x, int y) { return x > y ? x : y; }

bool src(int a) { return m(a, 0) > 1; }

bool tgt(int a) { return a > 1; }
```

@dtcxzyw follow up to 44e5afdb91b92dedfbd3100a3e73dab27de1c9cf

**Comment by sftlbcn** [comment]
thanks @dtcxzyw
probably not worth handling unsigned min/max with signed cmp?

**Comment by dtcxzyw** [comment]
> thanks @dtcxzyw probably not worth handling unsigned min/max with signed cmp?

I will double check the pattern.

**Comment by dtcxzyw** [comment]
> thanks @dtcxzyw probably not worth handling unsigned min/max with signed cmp?

I don't see any benefit of handling this pattern in my benchmark. If you find it exists in some real-world applications, please feel free to reopen this issue :)

Thank you!
