### ISSUE TITLE
Miscompile with opt -passes="constraint-elimination"

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#76713]
llvm commit: 5842dfe34d89
Reproduce with: ```opt -passes="constraint-elimination" bbi-90501.ll -S -o -```
[bbi-90501.ll.gz](https://github.com/llvm/llvm-project/files/13810077/bbi-90501.ll.gz)

There are two nested loops in the input that should finish and then we should end up at
```
bb.2:                                             ; preds = %bb.1
  ret i16 0
```
but with constraint-elimination the condition in bb.5 is changed to
```
  %i10 = or i1 true, %i9
  br i1 %i10, label %bb.7, label %bb.6
```
so we will go to
```
bb.7:                                             ; preds = %bb.5
  ret i16 1
```
instead.

**Comment by mikaelholmen** [comment]
This starts happening with e6a1657fa30c747f4412fc47f567660ebe861a9e
```
[ConstraintElim] Add A < B if A is an increasing phi for A != B.
```
@fhahn : any idea what's up?

**Comment by fhahn** [comment]
Looks like an issue with `sub` decomposition with negative constants, preparing a fix.

**Comment by mikaelholmen** [comment]
Thanks for the quick fix! I've verified it solves the problem I saw.

**Comment by fhahn** [comment]
@mikaelholmen thanks for the reproducer!

**Comment by fhahn** [comment]
(appreciated as always, thanks for your extensive testing)
