### ISSUE TITLE
[PowerPC][RISCV] Attribute 'signext' applied to incompatible type!

### ISSUE THREAD

**Issue by ahatanak** [llvm/llvm-project#76773]
$ cat test.c
```
typedef union foo {
  int i;
} foo_t __attribute__((transparent_union));

void test(foo_t a) {
}
```

$ clang -target powerpc64le-linux -S -o - -emit-llvm test.c
Attribute 'signext' applied to incompatible type!
ptr @test
fatal error: error in backend: Broken module found, compilation aborted!

**Comment by chenzheng1030** [comment]
This is really a front end issue.

```
clang t.c -S -emit-llvm -fno-verify-intermediate-code
```

```
%union.foo = type { i32 }

; Function Attrs: noinline nounwind optnone uwtable
define dso_local void @test(%union.foo noundef signext %a.coerce) #0 {
entry:
  %a = alloca %union.foo, align 4
  store %union.foo %a.coerce, ptr %a, align 4
  ret void
}
```

signext is added to type `%union.foo` which is not allowed.

**Comment by chenzheng1030** [comment]
The crash also happens on riscv64. But it is ok on 64 bit targets like aarch64, x86_64. And the good IR is like:
```
%union.foo = type { i32 }

define dso_local void @test(i32 %0) #0 !dbg !8 {
  %2 = alloca %union.foo, align 4
  %3 = getelementptr inbounds %union.foo, ptr %2, i32 0, i32 0
  store i32 %0, ptr %3, align 4
  call void @llvm.dbg.declare(metadata ptr %2, metadata !18, metadata !DIExpression()), !dbg !19
  ret void, !dbg !20
}

declare void @llvm.dbg.declare(metadata, metadata, metadata) #1
```

**Comment by lei137** [comment]
PR to fix codegen for PowerPC: https://github.com/llvm/llvm-project/pull/101738

**Comment by lei137** [comment]
PR to fix RISCV+: https://github.com/llvm/llvm-project/pull/104816

**Comment by DTeachs** [comment]
Should this be backported to 19.x alongside the PowerPC one?

**Comment by lei137** [comment]
They fix different backends and are not dependent of each other so I don't think it has to be.  
However if we can if it's needed.  @ahatanak?
