### ISSUE TITLE
In NAMELIST output editing, leading blank is missing.

### ISSUE THREAD

**Issue by harishch4** [llvm/llvm-project#76798]
The first character written in a NAMELIST i/o record must be a blank. The words in the Standard are "**Except for continuation of delimited character sequences, each output record begins with a blank character to provide carriage control when the record is printed**" (F95) and **"Except for new records created by explicit formatting within a defined output procedure or by continuation of delimited character sequences, each output record begins with a blank character.**" (F2023).

The **_gfortran_** & **_llvm-flang_** compilers do not put a blank. The **_Intel compiler_** does put a blank for external units but misses the blank for internal units.

```
Program test_namelist_blank
  Integer :: i,j
  Character(300) ::s
  Namelist /nml1/i,j

  i = 99
  j = 42
  Write (s,NML=nml1)
  Write (*,'("Internal ",A)') Merge('ok ','bug',s(1:1)==' ')
  Write (*,NML=nml1)
End Program test_namelist_blank
```

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/76846

**Comment by klausler** [comment]
Fix has been merged into llvm-project/main.
