### ISSUE TITLE
ExplodedNode*, clang::ExplodedNodeSet&, bool): Assertion `0' failed. 0  clang 0x0924aa58

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7687]
|  |  |
| --- | --- |
| Bugzilla Link | [7315](https://llvm.org/bz7315) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @tkremenek |

## Extended Description 
Cast kind 10 not handled.
clang: GRExprEngine.cpp:2398: void clang::GRExprEngine::VisitCast(clang::CastExpr*, clang::Expr*, clang::ExplodedNode*, clang::ExplodedNodeSet&, bool): Assertion `0' failed.
0  clang 0x0924aa58
Stack dump:
0.      Program arguments: /usr/local/bin/clang -cc1 -triple i386-pc-linux-gnu -analyze -disable-free -main-file-name get_macs.cpp -analyzer-store=region -analyzer-opt-analyze-nested-blocks -analyzer-check-dead-stores -analyzer-check-objc-mem -analyzer-eagerly-assume -analyzer-check-objc-methodsigs -analyzer-check-objc-unused-ivars -analyzer-output plist -w -mrelocation-model static -mdisable-fp-elim -mconstructor-aliases -target-cpu pentium4 -resource-dir /usr/local/lib/clang/2.0 -ferror-limit 19 -fmessage-length 207 -fexceptions -fgnu-runtime -fdiagnostics-show-option -fcolor-diagnostics -o get_macs.plist -x c++ get_macs.cpp
1.      <eof> parser at end of file
2.      get_macs.cpp:37:10 <Spelling=/usr/local/lib/clang/2.0/include/stddef.h:43:14>: Error evaluating statement
3.      get_macs.cpp:37:10 <Spelling=/usr/local/lib/clang/2.0/include/stddef.h:43:14>: Error evaluating statement
4.      get_macs.cpp:37:10 <Spelling=/usr/local/lib/clang/2.0/include/stddef.h:43:14>: Error evaluating statement
clang: error: clang frontend command failed due to signal 6 (use -v to see invocation)

**Comment by Endilll** [comment]
I was able to reproduce it locally with Clang 2.7 with assertions. It appears to be fixed in Clang 2.8.
The same flags trigger a different assertion on Compiler Explorer, which appears to be fixed in Clang 2.8 as well: https://cexplorer.testlabs.pro/z/P668Mn
