### ISSUE TITLE
[llvm-exegesis] --num-repetitions is inconsistent with its name

### ISSUE THREAD

**Issue by boomanaiden154** [llvm/llvm-project#76890]
Currently, the `--num-repetitions` flag in `llvm-exegesis` specifies the minimum number of instructions that should be executed rather than the number of repetitions of the snippe that should be run. This doesn't create confusion when benchmarking individual instructions, but does create confusion when the user is benchmarking a snippet as the number of repetitions is not equal to the number of instructions anymore. It seems like this flag was left over from before `llvm-exegesis` could execute snippets.

It seems like this flag should be renamed to something like `--min-instructions` to avoid user confusion. This would be a breaking change, but would be a clean breaking change that does not silently fail anywhere.

@legrosbuffle - Thoughts on renaming this?

**Comment by legrosbuffle** [comment]
Yes, I think that's a reasonable change. I don'k know what the LLVM policy w.r.t. these kinds of breaking flag changes is though. Since llvm-exegesis is mostly an internal dev tool, I'd be in favor of the breakage given that it will explicitly fail.
