### ISSUE TITLE
[x86_64][clang] Empty structure argument are ignored in function variable arguments.

### ISSUE THREAD

**Issue by CoTinker** [llvm/llvm-project#77036]
demo
```
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

extern void *memset (void *__s, int __c, size_t __n);
struct S14 { 
    union{}a; 
};

struct S14 s14;

void check14va (int z, ...) { 
	struct S14 arg, *p; 
	va_list ap; 
    __builtin_va_start(ap, z); 
    arg = __builtin_va_arg(ap, struct S14); 
    double va = __builtin_va_arg(ap, long double);
    printf("%f\n", va);
    if (va != 2.0L) 
        printf("Fail\n"); 
    __builtin_va_end(ap); 
}

int main() {
    memset (&s14, '\0', sizeof(s14));
    check14va(2, s14, 2.0L);
    return 0;
}
```
clang output:
```
0.000000
Fail
```
gcc output:
```
2.000000
```
https://godbolt.org/z/6ErKWPq15

llvm IR
```
define dso_local noundef i32 @main() {
entry:
  %retval = alloca i32, align 4
  %agg.tmp = alloca %struct.S14, align 1
  store i32 0, ptr %retval, align 4
  call void @llvm.memset.p0.i64(ptr align 1 @s14, i8 0, i64 1, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr align 1 %agg.tmp, ptr align 1 @s14, i64 1, i1 false)
  call void (i32, ...) @check14va(int, ...)(i32 noundef 2, x86_fp80 noundef 0xK40008000000000000000)
  ret i32 0
}
```
I find that clang ignore the empty structure argument `s14`. As a result, the subsequent running result does not meet the expectation.

https://github.com/llvm/llvm-project/blob/597086c60959dd5b3c032552e8b42dd1d053f233/clang/lib/CodeGen/Targets/X86.cpp#L2698-L2701

**Comment by shafik** [comment]
Looks like in C we get the expected behavior: https://godbolt.org/z/ddr7oTbKK

**Comment by cor3ntin** [comment]
Interestingly GCC used to have a similar bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60336

**Comment by CoTinker** [comment]
> Interestingly GCC used to have a similar bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60336

the ABI of gcc and clang are different, It seems that gcc not ignore the empty structure.

**Comment by AaronBallman** [comment]
I think this is a Clang bug. CC @hjl-tools @FreddyLeaf @phoebewang for a second opinion
