### ISSUE TITLE
[SPIR-V] Remove Linkage capability when targeting Vulkan

### ISSUE THREAD

**Issue by sudonatalie** [llvm/llvm-project#77117]
The test `llvm/test/CodeGen/SPIRV/empty-logical.ll` includes a CHECK for `OpCapability Linkage` which should not be present in an empty compute shader targeting Vulkan. We should fix this and add a test that runs `spirv-val` with a Vulkan1.2 SPIR-V target environment which should catch this issue.

**Comment by Keenuts** [comment]
I believe this is working as expected:
 - this is not an empty compute shader, but an empty shader with no entrypoint nor function.
 - a test has an empty compute shader: `capability-Shader.ll` and does not generate the Linkage capability.
 
 This scenario was not possible with DXC, as DXC failed to compile an empty file. The linkage here is to match the DXC behavior when using the `lib_` shader model, which is the only one I know of that allows not defining any entrypoint.

**Comment by sudonatalie** [comment]
Ah, got it, thanks for the clarification!
