### ISSUE TITLE
[mlir][spirv] Retain nontemporal information when converting memref load/store

### ISSUE THREAD

**Issue by antiagainst** [llvm/llvm-project#77156]
At the moment when we convert `memref.load`/`memref.store` we ignore the `nontemporal` attribute there. We should fix this to carry it to the `spirv.Load`/`spirv.Store` memory operands. And also make sure (de)serialization recognizes it.

**Comment by antiagainst** [comment]
@kuhar FYI

**Comment by kuhar** [comment]
@antiagainst Since you marked this as 'good first issue', can you add a repro IR and mlir-opt invocation that shows where the nontemporal annotation get lost? I think this should make it much easier for newcomers to get started.

**Comment by antiagainst** [comment]
Right. Here is an input IR:

```mlir
module attributes {
  spirv.target_env = #spirv.target_env<
    #spirv.vce<v1.0, [Shader], [SPV_KHR_storage_buffer_storage_class]>, #spirv.resource_limits<>>
} {

func.func @load_nontemporal(%arg0: memref<f32, #spirv.storage_class<StorageBuffer>>) {
  %0 = memref.load %arg0[] {nontemporal = true} : memref<f32, #spirv.storage_class<StorageBuffer>>
  memref.store %0, %arg0[] {nontemporal = true} : memref<f32, #spirv.storage_class<StorageBuffer>>
  return
}

}
```
With `mlir-opt -convert-memref-to-spirv` it should give:

```mlir
spirv.Load "StorageBuffer" ... ["Nontemporal"] ..
spirv.Store "StorageBuffer" ... ["Nontemporal"] ...
```

For 
```mlir
spirv.module Logical GLSL450 requires #spirv.vce<v1.0, [Shader], []> {
  // CHECK-LABEL: spirv.func @load_store_memory_operands
  spirv.func @load_store_memory_operands(%arg0 : !spirv.ptr<f32, Input>, %arg1 : !spirv.ptr<f32, Output>) "None" {
    %1 = spirv.Load "Input" %arg0 ["Nontemporal|Volatile|Aligned", 4]: f32
    spirv.Store "Output" %arg1, %1 ["Nontemporal|Volatile|Aligned", 4]: f32
    spirv.Return
  }
}
```
with `mlir-translate -no-implicit-module -test-spirv-roundtrip`, it should get the same IR. (It should be the case at of right now; but need to update test to reflect it.)

**Comment by mvvsmk** [comment]
Hey I am new to MLIR, could you assign me this issue and I can begin hacking on it :)

**Comment by ranjanmangla1** [comment]
Hey @mvvsmk  , Are you still working on it? I am new to LLVM & MLIR would love to take this issue!

**Comment by EugeneZelenko** [comment]
@ranjanmangla1: Just create pull request and mention it on this page.

**Comment by mvvsmk** [comment]
> Hey @mvvsmk  , Are you still working on it? I am new to LLVM & MLIR would love to take this issue! 

Hey @ranjanmangla1 I am working on it, will create a PR soon :)

**Comment by antiagainst** [comment]
@ranjanmangla1 if you are interested, there are other issues that we can certainly use your help, please see https://github.com/llvm/llvm-project/issues?q=is%3Aopen+is%3Aissue+label%3Amlir%3Aspirv especially those ones with "good first issue" label. :)

**Comment by mvvsmk** [comment]
Hey @antiagainst I am bit confused could you help me out a bit, this is what I have done so far
- [x] Read up on MLIR these two blogs were very helpful other than the MLIR docs:
- [What is MLIR and on SPIRV](https://www.lei.chat/posts/compilers-and-irs-llvm-ir-spirv-and-mlir/#infrastructurization) I am not sure but I think it is by you only XD. 
- [How to write a MLIR Pass](https://jeremykun.com/2023/08/10/mlir-writing-our-first-pass/#:~:text=tutorial-opt%20and%20project%20organization,to%20LLVM%20to%20machine%20code)
- [x] built and tested mlir
- [x] tested the IR you gave here using mlir-opt , and observed the changes.

My main Doubts are what is this issue regarding ? 
1. is it about writing a MLIR pass (lowering pass) ? In that case as I understand it I would have to see what I need to do in mlir/lib/MemRefToSPIRV
2. or is the lowering already implimented and I have to write tests to check that .

I didn't understand what you ment by this in your message, could you expand on what you ment by it?

>For
> spirv.module Logical GLSL450 requires #spirv.vce<v1.0, [Shader], []> {
  // CHECK-LABEL: spirv.func @load_store_memory_operands
  spirv.func @load_store_memory_operands(%arg0 : !spirv.ptr<f32, Input>, %arg1 : !spirv.ptr<f32, Output>) "None" {
    %1 = spirv.Load "Input" %arg0 ["Nontemporal|Volatile|Aligned", 4]: f32
    spirv.Store "Output" %arg1, %1 ["Nontemporal|Volatile|Aligned", 4]: f32
    spirv.Return
  }
}
> with mlir-translate -no-implicit-module -test-spirv-roundtrip, it should get the same IR. (It should be the case at of right now; but need to update test to reflect it.)

**Comment by antiagainst** [comment]
> is it about writing a MLIR pass (lowering pass) ? In that case as I understand it I would have to see what I need to do in mlir/lib/MemRefToSPIRV or is the lowering already implimented and I have to write tests to check that .

We don't need to write a pass for this given that we already have the [pass structure](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Conversion/MemRefToSPIRV/MemRefToSPIRVPass.cpp) in the `MemRefToSPIRV` directory. There are patterns actually to covert `memref.load`/`memref.store` (see [code here](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Conversion/MemRefToSPIRV/MemRefToSPIRV.cpp#L438-L684)); we just need to update them to consider the nontemporal attribute. You can search the codebase to see how to read an attribute on an op, and then how to create an attribute when building another op. Just need to check whether the input load/store has nontemporal attribute and carry it over to the new spirv op.

> I didn't understand what you ment by this in your message, could you expand on what you ment by it?

It's lit testing. You can find lots of such examples in the codebase (files with .mlir suffix). The top line with `// RUN:` prefix is a command line option to run. It typically invokes the `mlir-opt` binary which you compiled from MLIR source code over the given source file (represented as `%s` in the command) and then checks certain strings in the output via `FileCheck`. You can read about lit testing [here](https://llvm.org/docs/CommandGuide/lit.html) and FileCheck [here](https://llvm.org/docs/CommandGuide/FileCheck.html). 

So what you need to do is actually just put the above mlir test snippet in the file [here](https://github.com/llvm/llvm-project/blob/main/mlir/test/Conversion/MemRefToSPIRV/memref-to-spirv.mlir). Or actually, you can modifiy existing tests to add nontemporal attribute to the `memref.load` and `memref.store` ops there. And make sure have corresponding `// CHECK:` lines for them to check the output.
