### ISSUE TITLE
Handle `f(-x)=f(x)` for even functions and `f(-x)=-f(x)` for odd functions

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#77220]
Currently, Clang handles this for trigonometric functions (`sin`, `cos`, and `tan`). 
https://godbolt.org/z/eharx1Gn4

However, for example, Clang doesn't currently handle this for the error function (`erf`).
https://godbolt.org/z/33W9Eharo
```c
#include<math.h>

double test_erf1(double x)
{
   return -erf(-x);
}

double test_erf2(double x)
{
   return erf(x);
}
``` 

There are many other functions we have to check, but I think the following GCC test is helpful.
https://github.com/gcc-mirror/gcc/blob/master/gcc/testsuite/gcc.dg/torture/builtin-symmetric-1.c

**Comment by Krishna-13-cyber** [comment]
Oh seems its taken, I duplicated this one :(
