### ISSUE TITLE
Bad recovery from "redefinition of 'x' with a different type"

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7723]
|  |  |
| --- | --- |
| Bugzilla Link | [7351](https://llvm.org/bz7351) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @chandlerc,@DougGregor,@zygoloid |

## Extended Description 
When we find a redefinition of a name with a new type, we should recover by hiding the old variable and proceeding with the name bound to the new type. That is, in the following example, the last 2 diagnostics shouldn't happen.

$ cat test2.cc
```c++
int foo(int *ids_begin, int *ids_end) {
    for (int *id = ids_begin; id != ids_end; ++id) {
        int id = *id;
        if (id != 7)
            return id;
    }
    return 0;
}
```
$ ./clang++ -fsyntax-only test2.cc
```
test2.cc:3:13: error: redefinition of 'id' with a different type
        int id = *id;
            ^
test2.cc:2:15: note: previous definition is here
    for (int *id = ids_begin; id != ids_end; ++id) {
              ^
test2.cc:4:16: warning: comparison between pointer and integer ('int *' and 'int')
        if (id != 7)
            ~~ ^  ~
test2.cc:5:20: error: cannot initialize return object of type 'int' with an lvalue of type 'int *'
            return id;
                   ^~
1 warning and 2 errors generated.
```

**Comment by philnik777** [comment]
Fixed in Clang 3.0: https://godbolt.org/z/48f4nbfG5
