### ISSUE TITLE
[lld][ELF] OVERLAY: support optional start address and LMA

### ISSUE THREAD

**Issue by Yunzezhu94** [llvm/llvm-project#77265]
When I try to run binutils ld test with lld to figure out difference between gnu ld and lld, I found lld reports error:
```
error:  overlay-size.t:27: malformed number: :
>>>   OVERLAY : 
>>>           ^
```
where the linker script is
```
MEMORY
{
  TEXTMEM (ARX) : ORIGIN = 0x10000, LENGTH = 32K
  DATAMEM (AW)  : ORIGIN = 0x20000, LENGTH = 32K
  LOADMEM (AW)  : ORIGIN = 0x30000, LENGTH = 32K
}

/* Map should be:

           SIZE    VMA    LMA
   .bss1     10  20000  20000
   .bss2     30  20000  20010
   .bss3     20  20000  20040
   .mbss    230  20030  20060

   .mtext    20  10000  30000
   .text1    80  10020  30020
   .text2    40  10020  300a0
   .text3    20  10020  300e0

   .data1    30  20260  30100
   .data2    40  20260  30130
   .data3    50  20260  30170  */

SECTIONS
{
  OVERLAY : 
    {
      .bss1 { *(.bss1) }
      .bss2 { *(.bss2) }
      .bss3 { *(.bss3) }
    } > DATAMEM

  end_of_bss_overlays = . ;
    
  .mtext : { *(.mtext) } > TEXTMEM AT > LOADMEM

  .mbss : AT (__load_stop_bss3)
    {
      *(.mbss)
      . += 0x200;
    } > DATAMEM

  OVERLAY :
    {
      .text1 { *(.text1) }
      .text2 { *(.text2) }
      .text3 { *(.text3) }
    } > TEXTMEM AT > LOADMEM

  end_of_text_overlays = . ;

  OVERLAY :
    {
      .data1 { *(.data1) }
      .data2 { *(.data2) }
      .data3 { *(.data3) }
    } > DATAMEM AT > LOADMEM

  end_of_data_overlays = . ;
  
  . = 0x8000;
  /DISCARD/ : { *(.reginfo) *(.MIPS.abiflags) }
}
```
and the source file is
```
	.section .bss1, "aw", "nobits"
	.space 0x10
	.section .bss2, "aw", "nobits"
	.space 0x30
	.section .bss3, "aw", "nobits"
	.space 0x20

	.section .text1, "ax", "progbits"
	.space 0x80
	.section .text2, "ax", "progbits"
	.space 0x40
	.section .text3, "ax", "progbits"
	.space 0x20

	.section .data1, "aw", "progbits"
	.space 0x30
	.section .data2, "aw", "progbits"
	.space 0x40
	.section .data3, "aw", "progbits"
	.space 0x50

	.section .mtext, "ax", "progbits"
	.space 0x20
	.section .mbss, "aw", "nobits"
	.space 0x30
```
It looks lld treats symbol : as a tok, and this issue is similar with this : [https://discourse.llvm.org/t/memory-command-region-name-syntax/75145](https://discourse.llvm.org/t/memory-command-region-name-syntax/75145)
which lld treats string as Expr and split in function tokenizeExpr.

**Comment by MaskRay** [comment]
Our `OVERLAY` support (for https://github.com/llvm/llvm-project/issues/36116) is rudimentary and requires `start` and `AT` in `OVERLAY [start] : [NOCROSSREFS] [AT ( ldaddr )]`. We don't have more code to provide a better diagnostic.

I'll play with GNU ld to try removing the `start` and `AT(laddr)` requirement.

**Comment by MaskRay** [comment]
Created https://github.com/llvm/llvm-project/pull/77272 ("[ELF] OVERLAY: support optional start address and LMA"), which also fixes two other minor issues.

**Comment by Yunzezhu94** [comment]
> Our `OVERLAY` support (for #36116) is rudimentary and requires `start` and `AT` in `OVERLAY [start] : [NOCROSSREFS] [AT ( ldaddr )]`. We don't have more code to provide a better diagnostic.
> 
> I'll play with GNU ld to try removing the `start` and `AT(laddr)` requirement.
> 
> I am not a user of this niche feature, so it will be helpful if you can elaborate on why you need this feature.

Thanks for your reply. I'm just exploring differences and incompatibilities between lld and gnu ld, and found this issue which may relate to region name error I met earlier.
Since these two are different issues, I post another issue for the region name one: [https://github.com/llvm/llvm-project/issues/77286](https://github.com/llvm/llvm-project/issues/77286)
