### ISSUE TITLE
[ConstraintElim] GCC-C-execute-950704-1.test failed

### ISSUE THREAD

**Issue by jerryzj** [llvm/llvm-project#77290]
The `ConstraintEliminationPass` seems to be buggy in handling `long long`

Reduced test case

```
#include <stdlib.h>
int a;
int b(long long c, long long d) {
  long long e = c + d;
  if (c >= 0)
    return e;
  else if (d > 0 || e < 0)
    return e;
  a = 1;
  return 0;
}
int main() {
  b(0x8000000000000000LL, 0x8000000000000000LL);
  if (!a)
    abort();
}
```

The test case passed under `O1` but failed since `O2`. Using LLVM `opt-bisect`, I located that the test started failing after running `ConstraintEliminationPass` with a bisect limit set to 40.

**Comment by fhahn** [comment]
The test case has UB (signed integer overflow) https://godbolt.org/z/GYKEYeP6c

**Comment by fhahn** [comment]
d10245e73a71cee2beb737863ffe8f146f4d47e0 already added `fwrapv` to the test, please update your clone of `llvm-test-suite`

**Comment by jerryzj** [comment]
Got it, thanks.
