### ISSUE TITLE
[flang] llvm-flang error seen with Cray pointers and allocatable arrays

### ISSUE THREAD

**Issue by dpalermo** [llvm/llvm-project#77330]
LLVM flang does not accept assumed-size in the array spec for Cray pointers.  The reproducer has two forms that produce identical errors:

```
program test_crayptr
  implicit none
  pointer(ivar,var)
  real*8 var(*) !works with gfortran, but not accepted by flang-new
  !pointer(ivar,var(*)) !alternative equivalent statement pair
  !real*8 var
  real*8, allocatable :: location(:)
  integer i

  allocate(location(10))
  ivar = loc(location)
  do i=1,10
    var(i) = i
  enddo
  write(*,*) location

end program test_crayptr
```

Info on Cray pointers https://docs.oracle.com/cd/E19957-01/805-4941/z40000a54ba7/index.html 

Error:

>> flang-new pointer_program.f90
error: Semantic errors in pointer_program.f90
./pointer_program.f90:4:10: error: Implied-shape array 'var' must be a named constant or a dummy argument
    real*8 var(*) !works with gfortran, but not accepted by flang-new
           ^^^

Program output from gfortran:
>> gfortran pointer_program.f90 -fcray-pointer
>> ./a.out
   1.0000000000000000        2.0000000000000000        3.0000000000000000        4.0000000000000000        5.0000000000000000        6.0000000000000000        7.0000000000000000        8.0000000000000000        9.0000000000000000        10.000000000000000

**Comment by kkwli** [comment]
`var` is an assumed-size array, it should be a dummy argument.

**Comment by dpalermo** [comment]
From:  https://docs.oracle.com/cd/E19957-01/805-4941/z40000a54ba7/index.html

"If pointee_name is an array declarator, it must be explicit shape, (constant or nonconstant bounds), or **`assumed-size`**."

Which seems to mean assumed-size arrays are supported in a non-dummy context.

**Comment by mjklemm** [comment]
> From: https://docs.oracle.com/cd/E19957-01/805-4941/z40000a54ba7/index.html
> 
> "If pointee_name is an array declarator, it must be explicit shape, (constant or nonconstant bounds), or **`assumed-size`**."
> 
> Which seems to mean assumed-size arrays are supported in a non-dummy context.

I'm too young to actually have used this myself, but I read the Cray Pointer documentation of various compilers that not only the Cray Pointer syntax was an extension to Fortran proper, but also the additional usage of assumed-size arrays in the context of Cray Pointers.

**Comment by klausler** [comment]
This is a bug.

**Comment by mjklemm** [comment]
> This is a bug.

Thanks for confirming!

**Comment by klausler** [comment]
But it has nothing to do with allocatables.

**Comment by kkwli** [comment]
> This is a bug.

Oh, I didn't know that flang supports assumed-size array in the main program. Thanks.

**Comment by klausler** [comment]
> > This is a bug.
> 
> Oh, I didn't know that flang supports assumed-size array in the main program. Thanks.

It should do so in the case of an Cray pointer.

**Comment by mjklemm** [comment]
> Oh, I didn't know that flang supports assumed-size array in the main program. Thanks.

And as non-dummy variables in routines:

```Fortran
program bug
    real, dimension(*) :: pointee
    pointer (ptr, pointee)
end program bug

subroutine bug2()
    real, dimension(*) :: pointee
    pointer (ptr, pointee)
end subroutine bug2
```

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/77381

**Comment by dpalermo** [comment]
We've tried out the fix in https://github.com/llvm/llvm-project/pull/77381 and got a bit further before hitting another instance of the same semantic check.  Below is a small reproducer:

$ flang-new  test_crayptr.f90 -o test_crayptr
error: Semantic errors in test_crayptr.f90
./test_crayptr.f90:3:16: error: Assumed-size array 'var' must be a dummy argument
       integer*8 var(2,*) !works with gfortran, but not accepted by flang-new
                 ^^^

```
program test_crayptr
     implicit none
     integer*8 var(2,*) !works with gfortran, but not accepted by flang-new
     pointer(ivar,var)
     integer*8, allocatable :: location(:,:)
     integer i,j

     allocate(location(2,5))
     ivar = loc(location)
     do j=1,2
     do i=1,5
       var(j,i) = i
     enddo
     enddo
     write(*,*) location

end program test_crayptr
```

**Comment by mjklemm** [comment]
This test case enumerates all possible dimensions.  Let me know if you want me to turn this into a LIT test and create a PR against https://github.com/klausler/llvm-project/tree/bug77330.

```Fortran
subroutine cp1(n)
    integer :: n
    real :: array(*)
    pointer (ptr, array)
end subroutine

subroutine cp2(n)
    integer :: n
    real :: array(n,*)
    pointer (ptr, array)
end subroutine

subroutine cp3(n)
    integer :: n
    real :: array(n,n,*)
    pointer (ptr, array)
end subroutine

subroutine cp4(n)
    integer :: n
    real :: array(n,n,n,*)
    pointer (ptr, array)
end subroutine

subroutine cp5(n)
    integer :: n
    real :: array(n,n,n,n,*)
    pointer (ptr, array)
end subroutine

subroutine cp6(n)
    integer :: n
    real :: array(n,n,n,n,n,*)
    pointer (ptr, array)
end subroutine

subroutine cp7(n)
    integer :: n
    real :: array(n,n,n,n,n,n,*)
    pointer (ptr, array)
end subroutine

subroutine cp8(n)
    integer :: n
    real :: array(n,n,n,n,n,n,n,*)
    pointer (ptr, array)
end subroutine

subroutine cp9(n)
    integer :: n
    real :: array(n,n,n,n,n,n,n,n,*)
    pointer (ptr, array)
end subroutine

subroutine cp10(n)
    integer :: n
    real :: array(n,n,n,n,n,n,n,n,n,*)
    pointer (ptr, array)
end subroutine

subroutine cp11(n)
    integer :: n
    real :: array(n,n,n,n,n,n,n,n,n,n,*)
    pointer (ptr, array)
end subroutine

subroutine cp12(n)
    integer :: n
    real :: array(n,n,n,n,n,n,n,n,n,n,n,*)
    pointer (ptr, array)
end subroutine

subroutine cp13(n)
    integer :: n
    real :: array(n,n,n,n,n,n,n,n,n,n,n,n,*)
    pointer (ptr, array)
end subroutine

subroutine cp14(n)
    integer :: n
    real :: array(n,n,n,n,n,n,n,n,n,n,n,n,n,*)
    pointer (ptr, array)
end subroutine

subroutine cp15(n)
    integer :: n
    real :: array(n,n,n,n,n,n,n,n,n,n,n,n,n,n,*)
    pointer (ptr, array)
end subroutine
```

**Comment by mjklemm** [comment]
We have tested this downstream and it looks good now.  Thanks!

**Comment by klausler** [comment]
Patch has been merged into llvm-project/main.

**Comment by klausler** [comment]
Reassigning to Jean at his request.

**Comment by jeanPerier** [comment]
Removing bogus cray pointee stack allocation in lowering here: https://github.com/llvm/llvm-project/pull/79156

**Comment by EugeneZelenko** [comment]
Not merged yet.

**Comment by jeanPerier** [comment]
[Fix](https://github.com/llvm/llvm-project/pull/79156) for the bogus stack allocation was merged a while ago.
