### ISSUE TITLE
Anything that includes stdio.h fails

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7738]
|  |  |
| --- | --- |
| Bugzilla Link | [7366](https://llvm.org/bz7366) |
| Version | trunk |
| OS | Linux |
| Attachments | [gdb where output](https://user-images.githubusercontent.com/60944935/143741482-4c3a2da7-974a-47ac-a407-b699e175a8de.gz), [.i file](https://user-images.githubusercontent.com/60944935/143741483-0a10a330-21d4-42d6-96bf-b9d962200660.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Using the TIP a check in sometime last week causes a crash on any file that includes stdio.h and has a function in it

#include <stdio.h>
void blah() {} 

scan-build -k gcc -c foo.c

See attached gdb.out

**Comment by arsenm** [comment]
Can't reproduce
