### ISSUE TITLE
[mlir][arith] Integer overflow flags support in `arith` dialect

### ISSUE THREAD

**Issue by Hardcode84** [llvm/llvm-project#77392]
This is tracking issue for integer overflow flags support in `arith` dialect

Tasks:
- [x] Overflow flags enum and attribute support in `arith` ops (https://github.com/llvm/llvm-project/pull/77211)
- [x] Overflow flags, canonicalization for `SHL` in `arith` (https://github.com/llvm/llvm-project/pull/79828)
- [x] LLVM dialect lowering (https://github.com/llvm/llvm-project/pull/77211)
- [x] SPIR-V dialect lowering (https://github.com/llvm/llvm-project/pull/77714)
- [x] Overflow flags support in `arith` canonicalizations (https://github.com/llvm/llvm-project/pull/91646)
- [x] Overflow flags support in integer range analysis (https://github.com/llvm/llvm-project/pull/92642)

**Comment by yi-wu-arm** [comment]
Once it has been merge (https://github.com/llvm/llvm-project/pull/77211)
- [ ] Overflow flags, canonicalization for `SHL` in`arith`
