### ISSUE TITLE
[libc] fix -Wshorten-64-to-32 for 32b arm mmap

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#77395]
https://github.com/llvm/llvm-project/pull/77350 was an attempted fix that didn't work.  Filing a TODO to track a quick workaround to get the build bot green, until we can fix this properly.

**Comment by nickdesaulniers** [comment]
/usr/include/arm-linux-gnueabihf/sys/mman.h on the 32b arm buildbot has:
```c
#ifndef __off_t_defined
# ifndef __USE_FILE_OFFSET64
typedef __off_t off_t;
# else
typedef __off64_t off_t;
# endif
# define __off_t_defined
#endif
```
and preprocessing libc/src/sys/mman/linux/mmap.cpp I see:
```c
# 26 "/usr/include/arm-linux-gnueabihf/sys/mman.h" 2 3 4
typedef __off64_t off_t;
```
so that's where the 64b off_t is coming from.

**Comment by nickdesaulniers** [comment]
We have a libc/include/llvm-libc-types/off_t.h, should libc/src/sys/mman/mmap.h be explicitly including that rather than <sys/mman.h>?

**Comment by nickdesaulniers** [comment]
I see `_LARGEFILE_SOURCE` getting defined when building this TU, but...I only see that being added to the compile options in
llvm/cmake/modules/HandleLLVMOptions.cmake, and llvm/cmake/config-ix.cmake.

That's not polluting our build flags, is it?

Otherwise, perhaps we need to provide an implementation of the syscall that accepts a `long long` for that param.

**Comment by nickdesaulniers** [comment]
https://github.com/llvm/llvm-project/blob/408dce82016463dcb5026b2ddfc62174970a88e9/llvm/cmake/modules/HandleLLVMOptions.cmake#L446-L450 is leaking into our build rules, which is what's forcing `off_t` to be 64b on 32b targets.  I suspect we may want to avoid that, but need to think more about the implications of disabling that.

I suspect it may be a question of (do we want to match the platform's ABI vs do our own ABI).

**Comment by EugeneZelenko** [comment]
Patch was reverted.

**Comment by nickdesaulniers** [comment]
https://github.com/llvm/llvm-project/pull/78307 will resolve this finally.
