### ISSUE TITLE
[RISC-V][BOLT] Does BOLT support `vsetvli` instruction?

### ISSUE THREAD

**Issue by Caroline-zou** [llvm/llvm-project#77423]
I encountered a warning said 'unable to disassemble instruction at offset 0xa', and I used llvm-objdump to disassemble the executable binary file and found that the instruction is `vsetvl t2, t0, t1` .However, other rvv can be disassembled by BOLT. It makes me confused.

BOLT-WARNING: unable to disassemble instruction at offset 0xc (address 0x11190) in function main

the disassembly code:
```
./testcases/vset:       file format elf64-littleriscv

Disassembly of section .text:

0000000000011184 <main>:
   11184: 93 02 00 02   li      t0, 32
   11188: 13 03 00 10   li      t1, 256
   11190: d7 f3 62 80   vsetvl  t2, t0, t1
```

**Comment by aaupov** [comment]
@mtvec – does that ring any bells for you? Perhaps a missing mtune flag in ELF?

**Comment by mtvec** [comment]
Strange, we use the [input object's features](https://github.com/llvm/llvm-project/blob/b788692fa5b6ed79ea2c85ee464353cca30d867a/bolt/lib/Core/BinaryContext.cpp#L133) so I'd expect this to work. Is it possible to share the ELF file @Caroline-zou?

**Comment by Caroline-zou** [comment]
Thank you for the reply and I'm sorry for taking so long to get back to you.
I spent a some time trying to figure out the problem by myself, and I found that BOLT can't recognize rvv instructions. Because of this, BOLT won't build BinaryBasicBlock for the instruction. (The warning says it can't disassemble vsetvi because it's the first instruction it can't disassemble)
The link below shares the testcase I used, the upper disassembly is the simplified version.
[rvv-test](https://drive.google.com/file/d/17fOxA-Rgo-DNj5v3l1vLKGhDYtunkfzV/view?usp=drive_link)

**Comment by Caroline-zou** [comment]
> Strange, we use the [input object's features](https://github.com/llvm/llvm-project/blob/b788692fa5b6ed79ea2c85ee464353cca30d867a/bolt/lib/Core/BinaryContext.cpp#L133) so I'd expect this to work. Is it possible to share the ELF file @Caroline-zou?

Thanks for the reply. Now the problem is gone. And I realized this is due to I didn't update the code in my machine, while the older version of BOLT didn't include '+v' in the FeaturesStr.
