### ISSUE TITLE
(a < 2 and b < 2) should be optimized to (a | b) < 2

### ISSUE THREAD

**Issue by Validark** [llvm/llvm-project#77432]
Update: This logic gets optimized properly in C, but not Zig. Maybe this has to do with the LLVM bitcode that Zig produces?

https://zig.godbolt.org/z/6GTxKMvoP

---

Currently, this code gets emitted naïvely:

```zig
export fn foo(a: u32, b: u32) bool {
    return a < 2 and b < 2;
}
```

This can be optimized to:

```zig
export fn foo(a: u32, b: u32) bool {
    return (a | b) < 2;
}
```

---

Reasoning: since `a` and `b` must be 0 and/or 1 for the condition to be true, then the bitwise OR of these must also be 0 or 1 for the condition to be true. 2 could be substituted for other powers of 2, and would be applicable for any amount of numbers being checked with an AND between them.

E.g. `(a < 8 and b < 8 and c < 8 and d < 8)` -> `(a | b | c | d) < 8`

**Comment by nikic** [comment]
How do you make zig print LLVM IR? I need the equivalent of `-emit-llvm` in Clang or `--emit=llvm-ir` in rustc.

I expect the problem is that zig fails to set the `noundef` attribute on the function arguments.

**Comment by Validark** [comment]
I did `zig build-exe -h | grep llvm` and got the following output, hopefully one of these is what you are looking for?
```
  -femit-llvm-ir[=path]     Produce a .ll file with optimized LLVM IR (requires LLVM extensions)
  -fno-emit-llvm-ir         (default) Do not produce a .ll file with optimized LLVM IR
  -femit-llvm-bc[=path]     Produce an optimized LLVM module as a .bc file (requires LLVM extensions)
  -fno-emit-llvm-bc         (default) Do not produce an optimized LLVM module as a .bc file
  -fllvm                    Force using LLVM as the codegen backend
  -fno-llvm                 Prevent using LLVM as the codegen backend
  -flibllvm                 Force using the LLVM API in the codegen backend
  -fno-libllvm              Prevent using the LLVM API in the codegen backend
  --verbose-llvm-ir[=path]     Enable compiler debug output for unoptimized LLVM IR
  --verbose-llvm-bc=[path]     Enable compiler debug output for unoptimized LLVM BC
  --verbose-llvm-cpu-features  Enable compiler debug output for LLVM CPU features
```

**Comment by dtcxzyw** [comment]
> How do you make zig print LLVM IR? I need the equivalent of `-emit-llvm` in Clang or `--emit=llvm-ir` in rustc.
> 
> I expect the problem is that zig fails to set the `noundef` attribute on the function arguments.

LLVM IR:
```
define dso_local zeroext i1 @foo(i32 %0, i32 %1) local_unnamed_addr {
Entry:
  %2 = icmp ult i32 %0, 2
  %3 = icmp ult i32 %1, 2
  %4 = select i1 %2, i1 %3, i1 false
  ret i1 %4
}

define dso_local zeroext i1 @bar(i32 %0, i32 %1) local_unnamed_addr {
Entry:
  %2 = or i32 %1, %0
  %3 = icmp ult i32 %2, 2
  ret i1 %3
}
```
Zig should set `noundef` attributes on arguments. Then we can turn the `logical and` into a `bitwise and`.
