### ISSUE TITLE
[C++20] coroutine miscompilation if the constructors get marked with `[[gnu::pure]]`

### ISSUE THREAD

**Issue by kelbon** [llvm/llvm-project#77482]
I have generator coroutine, I just added [[gnu::pure]] for my constructor

```cpp
struct A {
  B* ptr;

  [[gnu::pure]] A(B& b) : ptr(std::addressof(b)) {}

};

```
This provokes segfault on this code:

```cpp
dd::generator<int> foo() {
    co_yield 0;
}
int main() {
    for (int i : foo())
      ;
}
```

I had minimized code and in minimized example there is link between [[always_inline]] on await suspend and this segfault (yes i know how clang coroutines work, but i feel that problem not here or not only here)

So, here minimized code:

https://godbolt.org/z/Eadnefe1v

I tried to understand what happens and where exactly bug, but its strange

Locally reproduces even without [[always_inline]] (clang 17 (not clang-cl) windows 11)

May be inline in final awaiter await suspend (its interesting when final_awaiter is promise itself), may be in combination, may be its really just [[pure]] attribute forces compiler to 'forget' to call constructor and initialize memory

Full code:

https://godbolt.org/z/3b1xx11Yh

(segfault locally)

P.S. note, that bug produced even without optimizations

**Comment by kelbon** [comment]
As i understand gcc thinks no constructor can be 'pure', which is not intuitive, but clang even doesn't say anything. Why? May be emit warnings like gcc does?

https://godbolt.org/z/PdMzbaaG8

**Comment by pinskia** [comment]
From https://gcc.gnu.org/onlinedocs/gcc-13.2.0/gcc/Common-Function-Attributes.html#index-pure-function-attribute : 
```
The pure attribute prohibits a function from modifying the state of the program that is observable by means other than inspecting the function’s return value. However, functions declared with the pure attribute can safely read any non-volatile objects, and modify the value of objects in a way that does not affect their return value or the observable state of the program.
```

So even without the warning, pure functions cannot write to memory that affect obserable state, that means writing to the implicit this argument ...

**Comment by kelbon** [comment]
> From https://gcc.gnu.org/onlinedocs/gcc-13.2.0/gcc/Common-Function-Attributes.html#index-pure-function-attribute :
> 
> ```
> The pure attribute prohibits a function from modifying the state of the program that is observable by means other than inspecting the function’s return value. However, functions declared with the pure attribute can safely read any non-volatile objects, and modify the value of objects in a way that does not affect their return value or the observable state of the program.
> ```
> 
> So even without the warning, pure functions cannot write to memory that affect obserable state, that means writing to the implicit this argument ...

Its not logic, if so, it must be hard error to mark constructor as 'pure'. Ofcourse if i mark constructor as 'pure' i mean "dont change anything and just create value" so i may change memory under pointer to uninited memory, but nothing else


```cpp
struct A { ... };

[[gnu::pure]] A A_constructor(...args) {
  return A(args...);
}
```

If i can do it, then why compiler cannot handle it itself

**Comment by ChuanqiXu9** [comment]
> > From https://gcc.gnu.org/onlinedocs/gcc-13.2.0/gcc/Common-Function-Attributes.html#index-pure-function-attribute :
> > ```
> > The pure attribute prohibits a function from modifying the state of the program that is observable by means other than inspecting the function’s return value. However, functions declared with the pure attribute can safely read any non-volatile objects, and modify the value of objects in a way that does not affect their return value or the observable state of the program.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So even without the warning, pure functions cannot write to memory that affect obserable state, that means writing to the implicit this argument ...
> 
> Its not logic, if so, it must be hard error to mark constructor as 'pure'. Ofcourse if i mark constructor as 'pure' i mean "dont change anything and just create value" so i may change memory under pointer to uninited memory, but nothing else
> 
> ```c++
> struct A { ... };
> 
> [[gnu::pure]] A A_constructor(...args) {
>   return A(args...);
> }
> ```
> 
> If i can do it, then why compiler cannot handle it itself

Compiler doesn't work that way. `[[gnu::pure]]` is an optimization hint to compilers. Compiler won't check it generally. For example: https://godbolt.org/z/YrMTdv97Y.  You can get the same feeling about `noexcept`. It is accepted to throw exceptions in an function marked with `noexcept`. But it is just UB if that happens.

**Comment by kelbon** [comment]
> > > From https://gcc.gnu.org/onlinedocs/gcc-13.2.0/gcc/Common-Function-Attributes.html#index-pure-function-attribute :
> > > ```
> > > The pure attribute prohibits a function from modifying the state of the program that is observable by means other than inspecting the function’s return value. However, functions declared with the pure attribute can safely read any non-volatile objects, and modify the value of objects in a way that does not affect their return value or the observable state of the program.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So even without the warning, pure functions cannot write to memory that affect obserable state, that means writing to the implicit this argument ...
> > 
> > 
> > Its not logic, if so, it must be hard error to mark constructor as 'pure'. Ofcourse if i mark constructor as 'pure' i mean "dont change anything and just create value" so i may change memory under pointer to uninited memory, but nothing else
> > ```c++
> > struct A { ... };
> > 
> > [[gnu::pure]] A A_constructor(...args) {
> >   return A(args...);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If i can do it, then why compiler cannot handle it itself
> 
> Compiler doesn't work that way. `[[gnu::pure]]` is an optimization hint to compilers. Compiler won't check it generally. For example: https://godbolt.org/z/YrMTdv97Y. You can get the same feeling about `noexcept`. It is accepted to throw exceptions in an function marked with `noexcept`. But it is just UB if that happens.

[[pure]] means assume i dont change anything, ofcourse it will be ub if i change global variable.

But  if i mark constructor as [[pure]], then compiler must handle it as special case of [[pure]] or emit error

**Comment by ChuanqiXu9** [comment]
> > > > From https://gcc.gnu.org/onlinedocs/gcc-13.2.0/gcc/Common-Function-Attributes.html#index-pure-function-attribute :
> > > > ```
> > > > The pure attribute prohibits a function from modifying the state of the program that is observable by means other than inspecting the function’s return value. However, functions declared with the pure attribute can safely read any non-volatile objects, and modify the value of objects in a way that does not affect their return value or the observable state of the program.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > So even without the warning, pure functions cannot write to memory that affect obserable state, that means writing to the implicit this argument ...
> > > 
> > > 
> > > Its not logic, if so, it must be hard error to mark constructor as 'pure'. Ofcourse if i mark constructor as 'pure' i mean "dont change anything and just create value" so i may change memory under pointer to uninited memory, but nothing else
> > > ```c++
> > > struct A { ... };
> > > 
> > > [[gnu::pure]] A A_constructor(...args) {
> > >   return A(args...);
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > If i can do it, then why compiler cannot handle it itself
> > 
> > 
> > Compiler doesn't work that way. `[[gnu::pure]]` is an optimization hint to compilers. Compiler won't check it generally. For example: https://godbolt.org/z/YrMTdv97Y. You can get the same feeling about `noexcept`. It is accepted to throw exceptions in an function marked with `noexcept`. But it is just UB if that happens.
> 
> [[pure]] means assume i dont change anything, ofcourse it will be ub if i change global variable.
> 
> But if i mark constructor as [[pure]], then compiler must handle it as special case of [[pure]] or emit error

But the output parameters are not special too: https://godbolt.org/z/96zq93vTj. While it might be an improvement to emit an error, I think the current behavior is consistent.

> 
> P.S. if you throw exception from noexcept function std::terminate called
