### ISSUE TITLE
Multiple bots are broken after #76471

### ISSUE THREAD

**Issue by vitalybuka** [llvm/llvm-project#77546]
PR #76471 breaks windows
https://lab.llvm.org/buildbot/#/builders/127/builds/60635

#77508 is not enough
https://lab.llvm.org/buildbot/#/builders/127/builds/60651

**Comment by vitalybuka** [comment]
There is also
https://lab.llvm.org/buildbot/#/builders/238/builds/7395
which includes this patch

**Comment by vitalybuka** [comment]
And 
https://lab.llvm.org/buildbot/#/builders/85/builds/21462

**Comment by vitalybuka** [comment]
Also https://lab.llvm.org/buildbot/#/builders/74/builds/24843

**Comment by qiongsiwu** [comment]
@vitalybuka thanks for tracking the failures! I will take a look!

**Comment by qiongsiwu** [comment]
https://github.com/llvm/llvm-project/pull/77831 fixes the bootstrap failures.

**Comment by qiongsiwu** [comment]
https://github.com/llvm/llvm-project/pull/78285 posted to reland #76471.

**Comment by qiongsiwu** [comment]
#78285 has landed. Monitoring buildbot.

**Comment by qiongsiwu** [comment]
Windows sanitizer build succeeded https://lab.llvm.org/buildbot/#/builders/127/builds/61230.

**Comment by qiongsiwu** [comment]
Bootstrap looks fine as well https://lab.llvm.org/buildbot/#/builders/236/builds/8917. The only failing test case is failing for https://lab.llvm.org/buildbot/#/builders/236/builds/8916 as well.

**Comment by qiongsiwu** [comment]
https://lab.llvm.org/buildbot/#/builders/168/builds/18218 is successful as well.
