### ISSUE TITLE
CTAD for aggregates fails for inner template class

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#77599]
The following code is compiled for gcc and msvc, but clang fails to [compile](https://godbolt.org/z/P1jzvfWx1):

```
template<typename T>
struct Foo {
  template<typename X>
  struct Inner {
    T t;
    X x;
  };
};

void s() {
  Foo<int>::Inner i{1, 2}; // fails 
  Foo<int>::Inner i2 = {1, 2}; // fails
}
```

**Comment by shafik** [comment]
I believe this should work, @antangelo did some work in this area recently.

**Comment by antangelo** [comment]
On initial inspection it seems we aren't calling `DeclareImplicitDeductionGuideFromInitList` on the nested class. The ClassTemplateDecl used in the path that calls this function is the empty one from Foo's instantiation, so I suspect the solution is to find and use the template pattern here instead as is now done for the general case.

**Comment by hokein** [comment]
Thanks. 

> On initial inspection it seems we aren't calling DeclareImplicitDeductionGuideFromInitList on the nested class. 

This looks like the reason. If I add an explicit constructor `Inner(T, X);`, the error is gone.
