### ISSUE TITLE
[D131929] Resolve warnings for Wimplicit-float-conversion, Wmacro-redefined, Wzero-as-null-pointer-constant, Wsign-conversion

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#77626]
This issue tracks picking up https://reviews.llvm.org/D131929 from the Phabricator archive.

**Comment by mordante** [comment]
I had a look at the patch and I no longer feel like pursuing it. If we want to do it again in the future it would be easier to create a new patch.
