### ISSUE TITLE
[mlir][spirv] Replace hardcoded attribute strings with op methods

### ISSUE THREAD

**Issue by antiagainst** [llvm/llvm-project#77627]
Due to historical reasons we have quite some hardcoded strings for attribute names used in parser/printer and serializer/deserializer. Now in ODS we actually generate op methods for getting the names of attributes. It's better to replace the hardcoded strings for consistency. Specicially:

- [ ] Replace parser/printer attribute strings [here](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/SPIRV/IR/SPIRVParsingUtils.h#L23-L50). For example, `branch_weights` can be replaced with `getBranchWeightsAttrName().strref()`.
- [x] Check and replace such patterns in serializer too, e.g., [here](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Target/SPIRV/Serialization/SerializeOps.cpp#L701-L743). Need to check all the files in serializer library. But don't need to change the autogenerated ones given those are consistent for sure due to autogen.
- [x] Do the same for deserializer.

**Comment by haanhvu** [comment]
I'll work on this

**Comment by spurjhattam2207** [comment]
.take-issue

**Comment by anishrajeev** [comment]
I am new to LLVM and am just trying to familiarize myself with the codebase, I started taking a look at this issue to dip my feet in the water and was wondering where I could read more about ODS generating op methods, specifically where I could access those generated getter methods for the attribute names? Thanks!

**Comment by antiagainst** [comment]
> I am new to LLVM and am just trying to familiarize myself with the codebase, I started taking a look at this issue to dip my feet in the water and was wondering where I could read more about ODS generating op methods, specifically where I could access those generated getter methods for the attribute names? Thanks!

The TableGen backend for op definition that takes in .td files to generate .inc files is in [this directory](https://github.com/llvm/llvm-project/tree/main/mlir/lib/TableGen). It might be hard to read directly there given the string concatenation. Typically the .inc files are generated to a path matching the source .td files. For example, you can find .inc files for SPIR-V dialect in `<build-dir>/tools/mlir/include/mlir/Dialect/SPIRV/IR`.

**Comment by NNhanptnk** [comment]
I am also new to LLVM and would like to dive into this issue as well. Thank you for the information.

**Comment by SahilPatidar** [comment]
Hello @antiagainst,

I'm considering a series of replacements throughout the serialization codebase, such as changing op->getAttr("alignment") to op->getAlignmentAttr() in serialization.

Are there any specific considerations or modifications you recommend for these replacements?
Your feedback is appreciated.

**Comment by tw-ilson** [comment]
So, we need to get the OperationName inline, is that currently possible? Op::getFooAttrName requires the OperationName in order to validate it. Example:
```
  static ::mlir::StringAttr getAttributeNameForIndex(::mlir::OperationName name, unsigned index) {
    assert(index < 4 && "invalid attribute index");
    assert(name.getStringRef() == getOperationName() && "invalid operation name");
    assert(name.isRegistered() && "Operation isn't registered, missing a "
          "dependent dialect loading?");
    return name.getAttributeNames()[index];
  }
```
Question is, correct me if I'm wrong, how can we get that odsOpName from the Adapter at (parser, etc) compile time?

**Comment by SahilPatidar** [comment]
@antiagainst @kuhar,
Please let me know if there is anything wrong in my [commit](https://github.com/llvm/llvm-project/commit/ef27289180d53377c3a9def44f9cbae22f9ff29a)

**Comment by antiagainst** [comment]
> @antiagainst @kuhar, Please let me know if there is anything wrong in my [commit](https://github.com/llvm/llvm-project/commit/ef27289180d53377c3a9def44f9cbae22f9ff29a)

Hi sorry for the late reply. What you have in the above commit looks good to me!

**Comment by tw-ilson** [comment]
Hi @antiagainst,
I have made some changes throughout the parsing code as you directed:
((https://github.com/tw-ilson/llvm-project/commit/c794f24655d131fb698a7cf2310b1f50259b7d16#diff-8d05b7e17af37e334c7676ca9e1affd75fcf10351ce85d201027aa298bf04918))

note that the following attribute/operand names are not generated via ODS:
```
inline constexpr char kClusterSize[] = "cluster_size"; // no ODS generation
inline constexpr char kControl[] = "control"; // no ODS generation
inline constexpr char kFnNameAttrName[] = "fn"; // no ODS generation
inline constexpr char kSpecIdAttrName[] = "spec_id"; // no ODS generation
```
Also, I remove this assertion from the Op definitions in order to use the static methods in one place (parseSourceMemoryAccessAttributes), which might be objectionable:
`  // assert(name.getStringRef() == getOperationName() && "invalid operation name");`

Let me know what you think
- Tom Wilson

**Comment by antiagainst** [comment]
> note that the following attribute names are not generated via ODS

Yeah some attributes not generated by ODS is fine.

> Also, I remove this assertion from the Op definitions in order to use the static methods in one place (parseSourceMemoryAccessAttributes), which might be objectionable:
> ` // assert(name.getStringRef() == getOperationName() && "invalid operation name");`

This shouldn't be necessary? should avoid touching this part and revert the changes in `parseSourceMemoryAccessAttributes`.

**Comment by SahilPatidar** [comment]
@antiagainst,
I have completed some work on the Serializer and Deserializer codebase. Could you please review it?

Thank you,

**Comment by tw-ilson** [comment]
>> Also, I remove this assertion from the Op definitions in order to use the static methods in one place (parseSourceMemoryAccessAttributes), which might be objectionable:
 // assert(name.getStringRef() == getOperationName() && "invalid operation name");

> This shouldn't be necessary? should avoid touching this part and revert the changes in `parseSourceMemoryAccessAttributes`.

My mistake, it's not just parseSourceMemoryAccessAttributes, but all places in the parser where the exact type of Operation is opaque, which is most places. We can check against the state's OperationName, but that will add a bunch of logic:
```
StringAttr executionScopeAttrName(OperationName &name) {
  TypeID id = name.getTypeID();
  if (id == TypeIDResolver<ControlBarrierOp>::resolveTypeID()) {
    return ControlBarrierOp::getExecutionScopeAttrName(name);
  } else 
  if (id == TypeIDResolver<GroupUMaxOp>::resolveTypeID()) {
    return GroupUMaxOp::getExecutionScopeAttrName(name);
  }
  //etc for each permutation
}
```
@SahilPatidar thoughts?

**Comment by antiagainst** [comment]
Reopen given this is not done entirely.

**Comment by tw-ilson** [comment]
@antiagainst 
I replaced all instances of the hardcoded attr names in the parser, and I was able to add back the assertion that I had previously removed.

**Comment by antiagainst** [comment]
> @antiagainst I replaced all instances of the hardcoded attr names in the parser, and I was able to add back the assertion that I had previously removed.

Nice, thanks for the contribution, @tw-ilson!
