### ISSUE TITLE
[D156032] Implement CWG2137 (list-initialization from objects of the same type)

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#77638]
This issue tracks picking up https://reviews.llvm.org/D156032 from the Phabricator archive, or dropping it in case it has already landed. I want to make sure nothing gets lost.

**Comment by cor3ntin** [comment]
@MitalAshok Are you still working on that? If so could you create a PR on Github? (Phabricator fell over)
Thanks a lot
