### ISSUE TITLE
Implement ABI tag support in LLDB

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#77639]
This issue tracks picking up the following reviews from the Phabricator archives:
- https://reviews.llvm.org/D131330 [llvm][Demangle] Add getter for FunctionEncoding::Attrs
- https://reviews.llvm.org/D131331 [llvm] lldb abi_tag support 1/3 - Add equality comparison API to itanium_demangle::Node
- https://reviews.llvm.org/D131333 [lldb] abi_tag support 2/3 - Make FindBestAlternateFunctionMangledName local to the C++ language plugin
- https://reviews.llvm.org/D131335 [lldb] abi_tag support 3/3 - Use mangle tree API to determine approximate mangled matches

If that work has already happened elsewhere, please feel free to close this. I just want to make sure these patches don't simply get dropped due to the Phabricator transition, since they were in the libc++ review queue.

**Comment by Michael137** [comment]
Ah apologies for not closing those reviews

We fixed this in LLDB in https://reviews.llvm.org/D131974

**Comment by ldionne** [comment]
Ah, I see! No worries, I just wanted to make sure this wasn't dropped. Thanks!
