### ISSUE TITLE
[D121213] [libc++] Enable modernize-use-equals-delete

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#77644]
This issue tracks picking up https://reviews.llvm.org/D121213 from the Phabricator archive. It looks like it was ready to go, so probably easy to rebase and re-upload here.

**Comment by philnik777** [comment]
This is now #93293.

**Comment by EugeneZelenko** [comment]
Not merged yet.

**Comment by philnik777** [comment]
> Not merged yet.

Yes, but this issue is about tracking what has to be moved from phab to GH, which has been done now. Not whether it's been finally merged.
