### ISSUE TITLE
LLVM/Clang currently lack support for Apple's visionOS ("xros" platform in triples)

### ISSUE THREAD

**Issue by allevato** [llvm/llvm-project#77674]
With Apple having released Xcode 15.2 GM this week, it would benefit folks who build other language tooling with LLVM/Clang using this repository to have support for the `xros` operating system in target triples (and whatever similar logic is needed in Clang to support `XROS.platform` and `XRSimulator.platform`).

Currently only Xcode's compilers support it, so any attempt to build tools with llvm/llvm-project that need to process `xros` triples fail unless support for the OS is manually patched in.

**Comment by tkremenek** [comment]
On the Apple side we are actively working on this, and hope to have patches up soon.

**Comment by andrewrk** [comment]
Why is it called "xros" in the triple?

**Comment by Rexicon226** [comment]
> Why is it called "xros" in the triple?

This was the internal initial development name given to it, before being changed to visionOS "last minute" iirc.

**Comment by cyndyishida** [comment]
Initial support is up for review at: https://github.com/llvm/llvm-project/pull/77707 
We're working on follow-up patches and can close out this issue once those are merged.

**Comment by allevato** [comment]
Thank you @cyndyishida !

**Comment by JDevlieghere** [comment]
Cyndy landed the Mach-O support (https://github.com/llvm/llvm-project/pull/78373) and I've merged support for visionos in the clang driver (https://github.com/llvm/llvm-project/pull/78392) and lldb (https://github.com/llvm/llvm-project/pull/78389). I believe this covers the platform so I'm going to mark this as resolved.

**Comment by arielttt0** [comment]
does the lld linker support linking of xros aswell? because when i try for example enter: lld -arch arm64 -platform_version xros 1.0.0 1.0 i get "malformed platform: xros"

**Comment by cyndyishida** [comment]
> does the lld linker support linking of xros aswell? because when i try for example enter: lld -arch arm64 -platform_version xros 1.0.0 1.0 i get "malformed platform: xros"

Looks like it was added about 3 weeks ago. https://github.com/llvm/llvm-project/pull/83031 If you're seeing issues on TOT, please file an additional issue.
