### ISSUE TITLE
[flang] list-directed WRITE of zero-length CHARACTER fails to print leading blank

### ISSUE THREAD

**Issue by kiranktp** [llvm/llvm-project#77736]
Leading blank is missing
	
Here is a small reproducer:

		Program test_listdirected_zerolength
		  Print *,'' ! a leading blank must be present in output
		End Program Test_listdirected_zerolength

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/77835

**Comment by klausler** [comment]
Fix has been merged into llvm-project/main.
