### ISSUE TITLE
Miscompile of dav1d on ppc64le

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#77748]
The checkasm test of https://code.videolan.org/videolan/dav1d fails on ppc64le when built with `meson --build-type=plain`.

The issue bisects to 1a2e77cf9e11dbf56b5720c607313a566eebb16e, which presumably just exposes the issue.

Using opt-bisect-limit and debug-counter=instcombine-visit-count we can narrow this down to an InstCombine transform. However, I believe the transform itself is correct (it just converts some extractelement/insertelement into a shufflevector) and this just exposes an issue in the backend.

The before.ll and after.ll in https://gist.github.com/nikic/b4c015523bcd22ea159d183c0648deea are before and after the transform.

The llc output for these two files is before.s and after.s in https://gist.github.com/nikic/ea9909b8216726762c8f2f277abc8006. (I've run `llc` with `opt-bisect-limit=0` to mostly isolate isel only.)

The difference is in two vperms and corresponding constant pool shuffle indices.

**Comment by nikic** [comment]
I suspect this vector shuffle combine is the culprit:
```
Combining: t289: v16i8 = vector_shuffle<11,17,12,19,13,21,14,23,15,25,u,27,u,29,u,31> t19, t243
Creating new node: t290: v16i8 = vector_shuffle<11,27,12,28,13,29,14,30,15,31,u,15,u,15,u,15> t19, t243
 ... into: t290: v16i8 = vector_shuffle<11,27,12,28,13,29,14,30,15,31,u,15,u,15,u,15> t19, t243
```
t243 is a zero vector here. The way the final u,27,u,29,u,31 indices get converted to u,15,u,15,u,15 looks incorrect to me.

This also looks like exactly the kind of pattern the the custom PPC DAG combine in combineVectorShuffle() handles, so this seems like a plausible cause.

**Comment by nikic** [comment]
Yeah, that combine doesn't handle undef indices correctly. What happens here is that we have undef indices -1 which get adjusted to -1+16 and that's how we end up using 15.

**Comment by nemanjai** [comment]
It seems that 263f1b2f5 handled the `undef` in the splat source, but not the other source. This should fix the problem:
```
diff --git a/llvm/lib/Target/PowerPC/PPCISelLowering.cpp b/llvm/lib/Target/PowerPC/PPCISelLowering.cpp
index 5e0c2d6..30916ec 100644
--- a/llvm/lib/Target/PowerPC/PPCISelLowering.cpp
+++ b/llvm/lib/Target/PowerPC/PPCISelLowering.cpp
@@ -15431,7 +15431,9 @@ SDValue PPCTargetLowering::combineVectorShuffle(ShuffleVectorSDNode *SVN,
       for (int i = 1, e = Mask.size(); i < e; i += 2) {
         if (ShuffV[i] < 0)
           continue;
-        ShuffV[i] = (ShuffV[i - 1] + NumElts);
+        int PrevIdx = ShuffV[i - 1];
+        // If the element from the LHS is undef, pick first element from splat.
+        ShuffV[i] = NumElts + (PrevIdx > 0 ? PrevIdx : 0);
       }
     // Example (odd elements from first vector):
     // vector_shuffle<16,0,17,1,18,2,19,3,20,4,21,5,22,6,23,7> t1, <zero>
@@ -15439,7 +15441,9 @@ SDValue PPCTargetLowering::combineVectorShuffle(ShuffleVectorSDNode *SVN,
       for (int i = 0, e = Mask.size(); i < e; i += 2) {
         if (ShuffV[i] < 0)
           continue;
-        ShuffV[i] = (ShuffV[i + 1] + NumElts);
+        int NextIdx = ShuffV[i + 1];
+        // If the element from the LHS is undef, pick first element from splat.
+        ShuffV[i] = NumElts + (NextIdx > 0 ? NextIdx : 0);
       }
   } else {
     // Example (even elements from first vector):
```

**Comment by nemanjai** [comment]
@stefanp-ibm FYI

**Comment by stefanp-ibm** [comment]
Thank you @nemanjai !
I'll try out the sample code you have there. I see there are also a couple of test cases. I will make those part of the fix.
