### ISSUE TITLE
[libc++] does not define  __cpp_lib_format

### ISSUE THREAD

**Issue by h-2** [llvm/llvm-project#77773]
https://github.com/llvm/llvm-project/commit/dff62f5251f26db856124526ae1b335ddc1e892c

states that

>  Some ``std::formatter`` specializations are not yet available since the class used in the specialization has not been implemented in libc++. This prevents the feature-test macro to be set.

Which specializations are that? I think it is unfortunate that the header is available for a while, but conforming code that relies on the macro cannot use it. Furthermore, `__cpp_lib_format_ranges` and `__cpp_lib_format_uchar` are set, which is weird, because they are features that build on `__cpp_lib_format` so implementations might even think that checking one of the former is sufficient, even though in this situation it is not?

**Comment by frederick-vs-ja** [comment]
Currently both `__cpp_lib_format` and `__cpp_lib_chrono` are blocked by missing `chrono` types. See https://github.com/llvm/llvm-project/issues/73953#issuecomment-1837472408.

**Comment by h-2** [comment]
Ah, that is unfortunate...

**Comment by mordante** [comment]
`__cpp_lib_format` requires the chrono formatters to be available. 3 papers set the macro to the same initial value. `__cpp_lib_format_ranges` and `__cpp_lib_format_uchar` are defined separately. I don't have a timeline but this is high on the top of my priority list for LLVM-19. (LLVM-18 will branch in later this month.)

**Comment by pawsaw** [comment]
@mordante Could you give us a status update? I'm working with `Homebrew clang version 18.1.6` and the corresponding libc++. Does this version suppose to have this `__cpp_lib_format` macro defined? According to my experiments, it does not.

**Comment by frederick-vs-ja** [comment]
> Edit: Ok, I misunderstood your comment. So, this will be fixed with LLVM-19 and not backported to LLVM-18, correct?

It's unlikely for libc++ to complete C++20 `chrono` types in LLVM19, so perhaps you need to wait a bit longer while.

**Comment by mordante** [comment]
cppreference is not the authoritative source for the status, https://libcxx.llvm.org/Status/Cxx20.html is the authoritative source. (Still I try to keep the status up-to-date on the parts I work on.)

I disagree with @frederick-vs-ja. I think it might be possible to get all chrono parts required for the initial version of `__cpp_lib_format` done before LLVM-19 is branched. But not all chrono parts for the chrono FTM. The latter would require parsing support, which will not be done before LLVM-19.

So it might be possible to get it in before LLVM-19, but it will be tight. It will not be backported to LLVM-18.

**Comment by pawsaw** [comment]
Thank you.

**Comment by mordante** [comment]
We've decided to define the macro regardless whether the missing `chrono` parts are done before LLVM 19. See https://github.com/llvm/llvm-project/pull/98275.
