### ISSUE TITLE
Problem installing Mojo on Lenovo G550 Ubuntu latest

### ISSUE THREAD

**Issue by dwhire** [llvm/llvm-project#77777]
0.	Program arguments: modular install mojo
 #0 0x0000559bafd10867 (/usr/bin/modular+0x53e867)
 #1 0x0000559bafd0e51e (/usr/bin/modular+0x53c51e)
 #2 0x0000559bafd10f2f (/usr/bin/modular+0x53ef2f)
 #3 0x00007f1e5d842910 (/lib/x86_64-linux-gnu/libc.so.6+0x42910)
 #4 0x0000559bb0f6c970 (/usr/bin/modular+0x179a970)
 #5 0x0000559bb0f6ccbb (/usr/bin/modular+0x179acbb)
 #6 0x0000559bb0157ce4 (/usr/bin/modular+0x985ce4)
 #7 0x0000559bafcd1d9a (/usr/bin/modular+0x4ffd9a)
 #8 0x00007f1e5d8280d0 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
 #9 0x00007f1e5d828189 call_init ./csu/../csu/libc-start.c:128:20
#10 0x00007f1e5d828189 __libc_start_main ./csu/../csu/libc-start.c:347:5
#11 0x0000559bafcd16be (/usr/bin/modular+0x4ff6be)
Illegal instruction (core dumped)

**Comment by fhahn** [comment]
This is the issue tracker for the upstream llvm-project, but it looks like the crash is Modular/Mojo related, which is not part of upstream llvm-project. Please raise the issue directly with Modular/Mojo.
