### ISSUE TITLE
LIT should print which RUN command failed

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#77869]
LIT currently prints all the commands, but doesn't identify which line failed. This can be problematic when there are several similar lines.

Two alternatives come to mind:

1. LIT prints only the commands that were run instead of all of them (thus the last line will be the failed command).
2. LIT singles out the failed command in addition to printing out all the commands (preferably just before the output).

**Comment by MaskRay** [comment]
@jdenny-ornl

**Comment by vinayakdsci** [comment]
Hello, can this issue be assigned to me?
I would love to work on it.

**Comment by jdenny-ornl** [comment]
> LIT currently prints all the commands, but doesn't identify which line failed. This can be problematic when there are several similar lines.

Can you please post an example?  Please identify the test case or test suite as there are custom lit formats that might affect the output.

> Two alternatives come to mind:
> 
>     1. LIT prints only the commands that were run instead of all of them (thus the last line will be the failed command).

For the test suites I normally use, that's already what happens.

**Comment by Atousa** [comment]
@EugeneZelenko Are you working on this issue? If not I am going to work on it.

**Comment by Sh0g0-1758** [comment]
@cjdb, I am not sure what you mean here. From what I understand, the `llvm-lit -v` command does exactly what this issue aims to resolve. Please clarify the issue with an example. 

this is from llvm-lit --help : 

>   -v, --verbose         For failed tests, show all output. For example, each command is printed before it is executed, so the last printed command is the one that
                        failed.

**Comment by cjdb** [comment]
This isn't my experience with `lit -sv`. When I run it, I get a listing for all of the `RUN` commands in the file.

**Comment by cjdb** [comment]
Ah, it looks like I was using an older version of `lit`. Upgrading to LLVM 18's gives the desired output.
