### ISSUE TITLE
optimize the GetStart tutorial

### ISSUE THREAD

**Issue by cyk2018** [llvm/llvm-project#77863]
When I was compiling the debug-version LLVM following [this page](https://llvm.org/docs/GettingStarted.html#getting-started-with-the-llvm-system) . My generator is Ninja and my memory is 16Gi. The first try fail with "collect2: fatal error: ld terminated with signal 9" , It seems my memory capacity is low, so I change to a server whose memory is 32G. However, the second try is fail. When I search on the Internet, It seems I can add the capacity of my swap disk or reduce the thread of my task. I think if we can add some details in our tutorial. 
Thank you.

**Comment by asl** [comment]
The ways to reduce memory consumption is discussed on the bottom of the same page: https://llvm.org/docs/GettingStarted.html#common-problems

**Comment by cyk2018** [comment]
Sorry, I ignore this part. When I search in Chinese, I only find the measure to change the swap disk. Maybe I can write a blog about this. Thank you!
