### ISSUE TITLE
Malformed MC/DC Coverage record on certain expressions

### ISSUE THREAD

**Issue by chapuni** [llvm/llvm-project#77873]
Reproducible case (https://godbolt.org/z/4vd8jczzz)
```
int foo(int a, int b, int c, int d, int e) {
    return (a || (b && c) || d || e);
}
```

The emission crashes llvm-cov with generated profdata.
`assert(!TestVectors[Idx].empty() && "Test Vector doesn't exist.");`

```
  Decision,File 0, 2:13 -> 2:36 = M:0, C:5
  Branch,File 0, 2:13 -> 2:14 = (#0 - #5), #5 [1,0,4] 
  Branch,File 0, 2:19 -> 2:20 = #6, (#5 - #6) [4,5,3] 
  Branch,File 0, 2:24 -> 2:25 = #7, (#6 - #7) [5,0,3] 
  Branch,File 0, 2:30 -> 2:31 = (#3 - #4), #4 [3,0,0] 
  Branch,File 0, 2:35 -> 2:36 = (#1 - #2), #2 [2,0,0] 
```

The chain is terminated at ID=3 and ID=2 is an orphan. `[3,0,2]` is expected.

**Comment by evodius96** [comment]
PR posted here: https://github.com/llvm/llvm-project/pull/78202

I did a slight refactor that allowed me to better encapsulate the code.  This also fixes your first reported issue with the FileID not being passed.

**Comment by chapuni** [comment]
Yet another problematic case:
`((a && (b || c) || (d && e)) && f)`

It will be fixed as well! In progress.

```
  Decision,File 0, 2:13 -> 2:45 = M:0, C:6
  Branch,File 0, 2:14 -> 2:15 = #4, (#0 - #4) [1,4,3] 
  Branch,File 0, 2:20 -> 2:21 = (#4 - #5), #5 [4,2,5] 
  Branch,File 0, 2:25 -> 2:26 = (#5 - #6), #6 [5,2,3] 
  Branch,File 0, 2:32 -> 2:33 = #7, (#3 - #7) [3,6,0] 
  Branch,File 0, 2:37 -> 2:38 = #8, (#7 - #8) [6,0,0] 
  Branch,File 0, 2:44 -> 2:45 = #2, (#1 - #2) [2,0,0] 
```

**Comment by chapuni** [comment]
Fixed, thanks @evodius96 !
