### ISSUE TITLE
[clang] Union of a non-literal type and a literal type should be literal

### ISSUE THREAD

**Issue by groundswellaudio** [llvm/llvm-project#77924]
Clang fails to compile this code : 

https://godbolt.org/z/qvxGcPx6x

```cpp
struct A {
    A();
};

template <class T>
struct opt
{
    union Data {
        
        constexpr Data() : x{} {}
        constexpr ~Data() {}

        char x;
        T data;
    };

    constexpr opt() : data{} {}
    constexpr ~opt() { if (engaged) data.data.~T(); }

    Data data;
    bool engaged = false;
};

consteval void foo()
{
    opt<A> a;
}

int main()
{
    foo();
}
```

With the error `non-literal type 'opt<A>' cannot be used in a constant expression` (in C++23, in C++20 the message is slightly different). `opt<A>` is not considered a literal type because of the implementation of CXXRecordDecl::isLiteral : 
https://github.com/llvm/llvm-project/blob/ae5d63924a6214154194c286a13c6ae74d31c086/clang/include/clang/AST/DeclCXX.h#L1457

which does not take into account that the CXXRecordDecl in question might be an union, in which case the type is literal if at least one of its member is literal. Perhaps the meaning of the bitfield `hasNonLiteralTypeFieldsOrBases` should change when the Decl is an union? since it does not seems to serve any other purposes than to detect whether the type is literal or not. 

(this causes problem with the constexpr-isation of `std::format` which i'm currently working on)

**Comment by cor3ntin** [comment]
Relevant wording: https://eel.is/c++draft/basic.types.general#10.5.3.2

**Comment by cor3ntin** [comment]
> (this causes problem with the constexpr-isation of std::format which i'm currently working on)

This is all the motivation I needed to fix that. As it turns out, it was a couple of C++ defect reports that we did not implement.
