### ISSUE TITLE
[libc++] Libc++ release notes for LLVM 17 are not accessible

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#77955]
The link to the libc++ 17 release notes present in https://releases.llvm.org points to https://releases.llvm.org/17.0.1/projects/libcxx/docs/ReleaseNotes.html. Instead, it should point to https://releases.llvm.org/17.0.1/projects/libcxx/docs/ReleaseNotes/17.html.

**Comment by ldionne** [comment]
@tru @tstellar Do you folks have an idea what needs to change here?

**Comment by tstellar** [comment]
@ldionne The llvm/www-releases repository is where you can adjust the links if you want.
