### ISSUE TITLE
missed-optimization: sum of two signed values greater than x is always greater than x

### ISSUE THREAD

**Issue by gooncreeper** [llvm/llvm-project#77969]
writing titles is harder than code
```C
int unopt(int x, int y, int z) {
    return x > y && z > y && (x + z) > y;
}

int opt(int x, int y, int z) {
    return x > y && z > y;
}
```

**Comment by gooncreeper** [comment]
I suppose we could also add an inverse can for less than and subtraction.

**Comment by gooncreeper** [comment]
Additionally multiplication for greater than, and division for less than.

**Comment by dtcxzyw** [comment]
> writing titles is harder than code
> 
> ```c
> int unopt(int x, int y, int z) {
>     return x > y && z > y && (x + z) > y;
> }
> 
> int opt(int x, int y, int z) {
>     return x > y && z > y;
> }
> ```

This optimization is incorrect:
```
x = -1073741760
y = -1073741824
z = -1073741823
x > y = true
z > y = true
x + z = -2147483583
x + z < y = false
```
Alive2: https://alive2.llvm.org/ce/z/2Qcm4F
