### ISSUE TITLE
When dummy argument "wait" of intrinsic "execute_command_line" is not present, it's treated as ".false."

### ISSUE THREAD

**Issue by psteinfeld** [llvm/llvm-project#77984]
Here's a program that shows the problem:
```
program bug
  call inner("echo hello")
contains
  subroutine inner(cmd, wait, exitstatarg, cmdstatarg, cmdmsgarg)
    character(10) :: cmd
    logical, optional :: wait
    integer, optional :: exitstatarg, cmdstatarg
    character(128), optional :: cmdmsgarg
    integer :: localvar
    call execute_command_line(cmd, wait, exitstatarg, localvar, cmdmsgarg)
  end subroutine
end
```

@yi-wu-arm, please take note.
When I compile and executes this program, it behaves as if the `wait` argument has the value `.false.`.  It's supposed to act as if the value is `.true.`.

**Comment by yi-wu-arm** [comment]
Taking a look

**Comment by yi-wu-arm** [comment]
This is caused by `isStaticallyPresent(wait)` will return true when the value is optional, a patch fixing this will come up soon.
