### ISSUE TITLE
[c++20][modules] '#pragma once' doesn't work with files included in global module fragment

### ISSUE THREAD

**Issue by jdrouhard** [llvm/llvm-project#77995]
This isn't quite the same reproducer as #38554 or #58532 and the issue still exists in 17.0.6.

When using `#pragma once`, included files in the global module fragment hide the visibility of everything declared in them when the module is imported before a normal `#include`. This error disappears (and the example works) if _either_ the `#pragma once`s are turned into normal include guards, _or_ the `import c;` and `#include "a.hpp"` are swapped in the importing translation unit (d.cpp).

```cpp
// a.hpp
#pragma once
using a = int;
```

```cpp
// b.hpp
#pragma once
a b;
```

```cpp
// c.cpp
module;
#include "b.hpp"
export module c;
```

```
// d.cpp
import c;
#include "a.hpp"
a d;
```

compile with:
```
clang++ -std=c++20 -x c++-module -fmodule-output=c.pcm -o c.o -c ./c.cpp
clang++ -std=c++20 -fmodule-file=c=c.pcm -c -o d.o d.cpp
```

error:
```
d.cpp:4:1: error: missing '#include "a.hpp"'; 'a' must be declared before it is used
    4 | a d;
      | ^
/.../a.hpp:2:7: note: declaration here is not visible
    2 | using a = int;
      |       ^
1 error generated.
```

**Comment by ChuanqiXu9** [comment]
Indeed. The behavior comes from clang header modules. We shouldn't encode the information in C++20 Named modules.
