### ISSUE TITLE
#78023 is revert

### ISSUE THREAD

**Issue by vitalybuka** [llvm/llvm-project#78024]
Breaking https://lab.llvm.org/buildbot/#/builders/236/builds/8673

**Comment by vitalybuka** [comment]
I believe the issue is that truncation will change results e.g. here
A1 =     0xff000000
A2 = 0xff00000000
````
define i1 @test4_icmp_with_var_mismatched_type(i32 %A1, i64 %A2) {
; CHECK-LABEL: @test4_icmp_with_var_mismatched_type(
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[A2:%.*]] to i32
; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[TMP1]], [[A1:%.*]]
; CHECK-NEXT:    ret i1 [[C]]
;
  %B1 = inttoptr i32 %A1 to ptr
  %B2 = inttoptr i64 %A2 to ptr
  %C = icmp ugt ptr %B1, %B2
  ret i1 %C
}
````

**Comment by dtcxzyw** [comment]
> I believe the issue is that truncation will change results e.g. here A1 = 0xff000000 A2 = 0xff00000000
> 
> ```
> define i1 @test4_icmp_with_var_mismatched_type(i32 %A1, i64 %A2) {
> ; CHECK-LABEL: @test4_icmp_with_var_mismatched_type(
> ; CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[A2:%.*]] to i32
> ; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[TMP1]], [[A1:%.*]]
> ; CHECK-NEXT:    ret i1 [[C]]
> ;
>   %B1 = inttoptr i32 %A1 to ptr
>   %B2 = inttoptr i64 %A2 to ptr
>   %C = icmp ugt ptr %B1, %B2
>   ret i1 %C
> }
> ```

It is correct because the bit width of pointer is 32 in the test...
