### ISSUE TITLE
[instcombine] fold icmp eq/ne (min a, b), (max a, b) to icmp eq/ne a, b

### ISSUE THREAD

**Issue by sftlbcn** [llvm/llvm-project#78038]
also symmetric selects/phi

```
----------------------------------------
define i1 @src(i32 %a, i32 %b) {
#0:
  %max = umax i32 %a, %b
  %min = umin i32 %a, %b
  %res = icmp eq i32 %min, %max
  ret i1 %res
}
=>
define i1 @tgt(i32 %a, i32 %b) {
#0:
  %res = icmp eq i32 %a, %b
  ret i1 %res
}
Transformation seems to be correct!
```
@dtcxzyw extension to 0ce193708cb682f3ad742ad909d8a5346a505ac7

**Comment by pinskia** [comment]
Note the rest of the comparisons:

`MIN (a, b) <= MAX (a, b)` should be simplified down to true.
`MIN (a, b) > MAX (a, b)` should be simplified down to false.

`MIN (a, b) < MAX (a, b)` should be simplified down to `a != b`
`MIN (a, b) >= MAX (a, b)` should be simplified down to `a == b`

Assuming the same signedness of MIN/MAX and the comparison.

**Comment by dtcxzyw** [comment]
> Note the rest of the comparisons:
> 
> `MIN (a, b) <= MAX (a, b)` should be simplified down to true. `MIN (a, b) > MAX (a, b)` should be simplified down to false.
> 
> `MIN (a, b) < MAX (a, b)` should be simplified down to `a != b` `MIN (a, b) >= MAX (a, b)` should be simplified down to `a == b`
> 
> Assuming the same signedness of MIN/MAX and the comparison.

Please file a separate issue for these simplifications.

**Comment by dtcxzyw** [comment]
> Note the rest of the comparisons:
> 
> `MIN (a, b) <= MAX (a, b)` should be simplified down to true. `MIN (a, b) > MAX (a, b)` should be simplified down to false.
> 
> `MIN (a, b) < MAX (a, b)` should be simplified down to `a != b` `MIN (a, b) >= MAX (a, b)` should be simplified down to `a == b`
> 
> Assuming the same signedness of MIN/MAX and the comparison.

IIRC they have been handled by ConstraintElimination.
