### ISSUE TITLE
C++ Backend doesn't handle blockaddress

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7804]
|  |  |
| --- | --- |
| Bugzilla Link | [7432](https://llvm.org/bz7432) |
| Version | 1.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie |

## Extended Description 
Summary:
When compiling C code with dynamic gotos and asking llvm2cpp to show library calls, it dies from a "Bad constant" error.

Steps to reproduce:
1. Go to http://llvm.org/demo/index.cgi
2. Enter a program that has dynamic gotos:

#include <time.h>

int main() {
    void* array[] = {&&foo, &&bar};
    goto *array[time(NULL) % 2];
    foo: return 1;
    bar: return 2;
    return 0;
}

3. Check "Show LLVM C++ API Code"
4. Click "Compile Source Code"

Expected results:
It should display the appropriate API calls to generate such instructions.

Actual Results:
llvm2cpp dies because of a "Bad Constant" error, even though the compiler managed to make valid LLVM bytecode out of the C code.

**Comment by arsenm** [comment]
cpp backend is gone
