### ISSUE TITLE
[Flang] Segmentation fault on ISHFTC test (gfortran.dg/ishftc_optional_size_1.f90)

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#78089]
Here is the reproducer, which is reduced from https://github.com/gcc-mirror/gcc/blob/master/gcc/testsuite/gfortran.dg/ishftc_optional_size_1.f90.
```console
$ cat test.f90
module m
  implicit none
contains

  elemental function ishftc1_ref (i, shift, size_) result(r)
    integer(1), intent(in)           :: i
    integer,    intent(in)           :: shift
    integer(1), intent(in), optional :: size_
    integer(1)                       :: r
    r = ishftc (i, shift=shift, size=size_)
  end

  elemental function ishftc1_val (i, shift, size_) result(r)
    integer(1), intent(in)           :: i
    integer,    intent(in)           :: shift
    integer(1), value,      optional :: size_
    integer(1)                       :: r
    r = ishftc (i, shift=shift, size=size_)
  end
end module m

program p
  use m
  implicit none
  integer    :: shift = 1
  integer(1) :: i1 = 127
  integer(1) :: expect1

  expect1 = -2_1
  if (ishftc      (i1, shift) /= expect1) stop 4
  if (ishftc1_ref (i1, shift) /= expect1) stop 5
  if (ishftc1_val (i1, shift) /= expect1) stop 6

end program p
```

I tested this on x86_64 as follows:
```console
$ flang-new test.f90
$ ./a.out
Segmentation fault
```

**Comment by JumpMasterJJ** [comment]
I have found similar  issues #87046 with `max/min` , and the reasons for their errors seem to be same.

**Comment by hakostra** [comment]
Seems to be solved in most recent main:

$ flang-new flang-issue-78089.f90 
$ ./a.out 
$ echo $?
0
$ flang-new --version
flang-new version 20.0.0git (https://github.com/llvm/llvm-project.git cd634f57c10dedbe4f908889dece2c4460b702c9)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/llvm/llvm-project/install/bin

**Comment by k-arrows** [comment]
Thank you for your posting the result with recent main branch flang-new. I will close this issue.
