### ISSUE TITLE
[SelectionDAG] Miscompilation of nested shuffles of partially-undef splat values

### ISSUE THREAD

**Issue by Benjins** [llvm/llvm-project#78109]
Recently, there seems to have been a regression in SelectionDAG involving nested shuffles of splat optimisation interacting with partially `undef` elements

The following is a minimal repro (comparing trunk with 17.0.1): https://godbolt.org/z/jajGr53r3 
```llvm
define <4 x i32> @do_stuff() {
  ; <0, 0, 7, 7>
  %shuffle.1 = shufflevector <4 x i32> <i32 7, i32 7, i32 0, i32 7>, <4 x i32> zeroinitializer, <4 x i32> <i32 2, i32 2, i32 1, i32 1>

  ; <0, 0, 3, 7>
  %shift = lshr <4 x i32> %shuffle.1, <i32 0, i32 0, i32 1, i32 0>

  ; <3, 3, 0, 0>
  %shuffle.2 = shufflevector <4 x i32> %shift, <4 x i32> zeroinitializer, <4 x i32> <i32 2, i32 2, i32 0, i32 0>

  ; <0, 1, 0, 1>
  %shuffle.3 = shufflevector <4 x i32> %shuffle.2, <4 x i32> <i32 1, i32 1, i32 1, i32 1>, <4 x i32> <i32 2, i32 6, i32 3, i32 7>
  ret <4 x i32> %shuffle.3
}
```

Apologies that it's not super-minimal: pretty much all of this is trying to coax SelectionDAG into the right state to trigger the repro

The crux of the issue seems to be in `combineShuffleOfSplatVal`:

The input DAG at that point:
```
SelectionDAG has 15 nodes:
    t0: ch,glue = EntryToken
          t21: v4i32 = BUILD_VECTOR Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>
          t18: v4i32 = BUILD_VECTOR Constant:i32<0>, undef:i32, undef:i32, undef:i32
        t9: v4i32 = srl t21, t18
      t22: v4i32 = vector_shuffle<u,u,0,0> t9, undef:v4i32
      t11: v4i32 = BUILD_VECTOR Constant:i32<1>, Constant:i32<1>, Constant:i32<1>, Constant:i32<1>
    t12: v4i32 = vector_shuffle<2,5,3,7> t22, t11
  t15: ch,glue = CopyToReg t0, Register:v4i32 $xmm0, t12
  t16: ch = X86ISD::RET_GLUE t15, TargetConstant:i32<0>, Register:v4i32 $xmm0, t15:1
```

which then gets transformed to:
```
SelectionDAG has 13 nodes:
    t0: ch,glue = EntryToken
        t21: v4i32 = BUILD_VECTOR Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>
        t18: v4i32 = BUILD_VECTOR Constant:i32<0>, undef:i32, undef:i32, undef:i32
      t9: v4i32 = srl t21, t18
      t11: v4i32 = BUILD_VECTOR Constant:i32<1>, Constant:i32<1>, Constant:i32<1>, Constant:i32<1>
    t12: v4i32 = vector_shuffle<2,5,3,7> t9, t11  ; <<<<< changed
  t15: ch,glue = CopyToReg t0, Register:v4i32 $xmm0, t12
  t16: ch = X86ISD::RET_GLUE t15, TargetConstant:i32<0>, Register:v4i32 $xmm0, t15:1
```

A bisect shows that this started with faecc736e2ac3cd8c77bebf41b1ed2e2d8cb575f, with the following change to `isSplatValue`:
https://github.com/llvm/llvm-project/blob/7f1d757fb40f06cc1c6b134d770987b340286996/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp#L2884-L2888

What's happening is that `t9` is now considered a splat, so since `t22` is a shuffle of it, `t22` is replaced with `t9` directly in `t12`. However, this leads to undefs in elements where there were none previously, and that leads to us outputting a different value.

From debugging, it looks like it may be interacting with this code in `combineShuffleOfSplatVal`: it does not pass in an explicit `DemandedElts`, so it implicitly demands all elements. This means that it `isSplatValue` thinks there are no undef elements, and it returns true even if `AllowUndefs` is false
https://github.com/llvm/llvm-project/blob/7f1d757fb40f06cc1c6b134d770987b340286996/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp#L25100-L25104

I have confirmed that this still repros on the latest trunk, 850f713e80426f1706c0d3dad143c330ca872d5d

For priority/triage purposes: this was found with a fuzzer meant to test SIMD codegen, it was not in manually-written code

**Comment by RKSimon** [comment]
I'm going to revert faecc736e2ac3cd8c77bebf41b1ed2e2d8cb575f - the issue we're having is that computeKnownBits sees the `lshr zeroinitializer, %a` and determines that the result can be zero (so says its a splat), but then the lshr gets further simplified to `lshr zeroinitializer, undef` and gets folded to undef. Without forcing the fold to zero immediately `combineShuffleOfSplatVal` can't rely on it staying a splat zero value.
