### ISSUE TITLE
Clangd 'Kinds' information incorrect

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#78156]
On https://clangd.llvm.org/features#kinds it is stated that the LSP Name of 'InactiveCode' is 'inactiveCode' 
In the code (https://github.com/llvm/llvm-project/blob/baba0a4cb43181a78881fce683e3a5016daa8ce6/clang-tools-extra/clangd/SemanticHighlighting.cpp#L1473) this is not mapped on 'inactiveCode', it is mapped on 'comment'.

**Comment by HighCommander4** [comment]
Thanks for the report. cc @daiyousei-qz 

Would you like to submit a PR to fix it? The relevant code is at https://github.com/llvm/clangd-www/blob/main/features.md.

**Comment by roife** [comment]
It seems that this issue has been inactive for a while. Considering that the documentation on the webpage may cause confusion for LSP-clients developers, I have submitted a PR to correct the 'LSP Name' on the webpage.
