### ISSUE TITLE
[DSE] Wrong code introduced by DeadStoreElimination when moving a store through another store to the same memory location

### ISSUE THREAD

**Issue by adamszilagyi** [llvm/llvm-project#78154]
The wrong code was discovered in the following example:

https://godbolt.org/z/c65nxKhjY

With O1 the result is the correct `39058` value, but for O2, O3, Ofast, Oz DSE kicks in and the result becomes `0`

The changes made by DSE can be seen here: https://godbolt.org/z/3jGxM5PEn
DSE moves up the `store i16 -26478, ptr @g_127, align 2` store and merge it with `store i32 20, ptr @g_127, align 4` since these two stores refer to the same memory location and one overwrites the other value, but the problem is that when iterating through the in-between instruction to check if any of them potentially modifies the same memory location, the alias analysis somehow can not deduce that the `%0 = load volatile ptr, ptr @g_543, align 4` instruction refers to the same memory location so the store removing is not safe in this example, but DSE does it anyway and `@g_543` will be set to `0` by `store i32 0, ptr %0, align 4` hence the wrong `0` result at the end. The two global variables declaration in question is

```.C
union U1 {
   uint16_t  f0;
   int32_t  f1;
   uint32_t  f2;
   signed f3 : 29;
};

static union U1 g_127 = {0x2045};
static int32_t * volatile g_543 = &g_127.f1;
```
Im not sure if this is an UB, but i think the store merging should not be possible in this situation.

**Comment by nikic** [comment]
I can't be bothered to look into this in detail given the unreduced test case, but this has all the hallmarks of strict aliasing violation (works with `-fno-strict-aliasing` and takes an address of a union member).
