### ISSUE TITLE
[libcxxabi] HAS_THREAD_LOCAL is not defined by cmake

### ISSUE THREAD

**Issue by 12101111** [llvm/llvm-project#78207]
`libcxxabi/src/cxa_exception_storage.cpp` contain a check for `HAS_THREAD_LOCAL`, but the flags is set by `compiler-rt/lib/fuzzer/CMakeLists.txt`. This cmake script is not used in normal build of libcxxabi.

Maybe it should be replaced by `__has_feature(cxx_thread_local)`?

See also: https://reviews.llvm.org/D155278

**Comment by ldionne** [comment]
CC @kalle-llvm @mstorsjo 

Do you folks know if `thread_local` is available everywhere? It's technically required for C++11 conformance, so I'd expect it to be available on all platforms when threads are enabled?

**Comment by kalle-llvm** [comment]
> Do you folks know if `thread_local` is available everywhere?

@ldionne Can't say about other platforms but it's available on `mingw`. I've been using libc++ with `HAS_THREAD_LOCAL` for several months without problems.
