### ISSUE TITLE
libcxx tz unknown path to the IANA Time Zone Database 

### ISSUE THREAD

**Issue by trcrsired** [llvm/llvm-project#78218]
/home/cqwrteur/Projects/myllvm/llvm-project/libcxx/src/tz.cpp:48:4: error: "unknown path to the IANA Time Zone Database"
   48 | #  error "unknown path to the IANA Time Zone Database"
      |    ^

This macro is only available on linux, causing wasi to fail

**Comment by JonChesterfield** [comment]
Can work around with the cmake `-D LIBCXX_ENABLE_TIME_ZONE_DATABASE=OFF`.

I'm not sure that should be necessary, the cmake is guarded with

```
if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
  set(ENABLE_TIME_ZONE_DATABASE_DEFAULT ON)
else()
  set(ENABLE_TIME_ZONE_DATABASE_DEFAULT OFF)
endif()
```

though it looks like cmake in my case believes it's building Linux and WASI at the same time, so I'm setting the database off flag.

**Comment by mordante** [comment]
I'm not familiar with wasi. Does it provide time zone information. If so it would be nice to get a patch to add support for it.

**Comment by ldionne** [comment]
Closing as inactive and since wasi is not officially supported (e.g. we don't have CI for it). Please reopen for additional discussion.
