### ISSUE TITLE
Support fno-plt like gcc

### ISSUE THREAD

**Issue by hstk30-hw** [llvm/llvm-project#78275]
Hi, I see https://reviews.llvm.org/D39079 add the support for `fno-plt` in frontend. But has no affect on asm code.

https://discourse.llvm.org/t/bug-fno-plt-has-no-effect/57986

If I want to support `fno-plt` in clang like gcc, Where should I start?

**Comment by hstk30-hw** [comment]
CC @tmsri @MaskRay

**Comment by tmsri** [comment]
Sorry, it's been a while.  Trying to understand what you want to achieve here,  Is it that you have a PLT call in inline asm that you want to avoid with -fno-plt?

**Comment by hstk30-hw** [comment]
I want to achieve  you proposed in gcc https://gcc.gnu.org/legacy-ml/gcc-patches/2015-05/msg00001.html @tmsri 

https://godbolt.org/z/Yeor6TTeE

For now, the `fno-plt` in clang seem just add `NonLazyBind` attribute to the function, seem not affect in the downstream.

**Comment by MaskRay** [comment]
mips has `-mno-plt`. Some arches such as x86/aarch64 have `-fno-plt`. in Clang, `-fno-plt` is only implemented for x86. I can add the AArch64 support.

I have some notes on https://maskray.me/blog/2021-09-19-all-about-procedure-linkage-table#fno-plt . `-fno-plt` is significantly worse on RISC architectures.

**Comment by wzssyqa** [comment]
gcc support -mplt only for TARGET_ABSOLUTE_ABICALLS.

#define TARGET_ABSOLUTE_ABICALLS        \
  (TARGET_ABICALLS                      \
   && !TARGET_SHARED                    \
   && TARGET_EXPLICIT_RELOCS            \
   && !ABI_HAS_64BIT_SYMBOLS)

I think that it makes no sense to support it on LLVM.

**Comment by MaskRay** [comment]
> gcc support -mplt only for TARGET_ABSOLUTE_ABICALLS.
> 
> #define TARGET_ABSOLUTE_ABICALLS (TARGET_ABICALLS && !TARGET_SHARED && TARGET_EXPLICIT_RELOCS && !ABI_HAS_64BIT_SYMBOLS)
> 
> For normal PIC ELFs, all of them are no-plt.
> 
> I think that it makes no sense to support it on LLVM.

mips's situation is different. `-mno-plt` is generally the default expect certain `-fno-pic` cases that default to `-mplt` (most o32/n32 and  n64 `-msym32`).

For most other architectures (probably all supported by LLVM), `-fplt` is the default and having `-fno-plt` could be interesting in some cases. The calls will be similar to `__dllspec(dllimport)` and can have an interesting trade-off for C library functions when dynamically linked.

**Comment by Kojoley** [comment]
> Some arches such as x86/aarch64 have `-fno-plt`. in Clang, `-fno-plt` is only implemented for x86.

It doesn't seem to be implemented for 32bit x86 and x86 GlobalISel.

https://godbolt.org/z/aa6jqraPY
```c
void bar(void);

void foo(void)
{
    bar();
}
```
```asm
; clang -m32 -O3 -fpic -fno-plt
foo():                                # @foo()
        push    ebx
        sub     esp, 8
        call    .L0$pb
.L0$pb:
        pop     ebx
.Ltmp0:
        add     ebx, offset _GLOBAL_OFFSET_TABLE_+(.Ltmp0-.L0$pb)
        call    bar()@PLT
        add     esp, 8
        pop     ebx
        ret

; gcc -m32 -O3 -fpic -fno-plt
foo():
        call    __x86.get_pc_thunk.ax
        add     eax, OFFSET FLAT:_GLOBAL_OFFSET_TABLE_
        jmp     [DWORD PTR _Z3barv@GOT[eax]]
__x86.get_pc_thunk.ax:
        mov     eax, DWORD PTR [esp]
        ret
```
```
clang -O3 -fpic -fno-plt -mllvm -global-isel
fatal error: error in backend: cannot select: %0:gr64(p0) = G_GLOBAL_VALUE @_Z3barv (in function: _Z3foov)
clang -m32 -O3 -fpic -fno-plt -mllvm -global-isel
fatal error: error in backend: cannot select: %0:gr32(p0) = G_GLOBAL_VALUE @_Z3barv (in function: _Z3foov)
```

**Comment by hstk30-hw** [comment]
> `-fno-plt` is significantly worse on RISC architectures due to a longer code sequence.

I test it in AArch64, gets 1.x% improvement, and branch-miss is down. 
In AArch64 use 3 Instructions compare with 1 instruction in X86. 
Branch-prediction is still the key :)

Thx @MaskRay
