### ISSUE TITLE
link error when compiling coroutine code.

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#78290]
See https://godbolt.org/z/5nvhqhsz9 for a minimal testcase.

The following code is compiled with gcc, but clang emits a link error (`in function Foo::CoroutineBody(): <source>:60: undefined reference to CoroutinePromise<void>::CoroutinePromise<Foo&>(Foo&)`) when linking to a binary. We seem to miss a symbol.

```cpp
#include <coroutine>

template <typename Final>
class Gen;

template <typename Final>
class CoroutinePromise final {
 public:
  template <typename... Args>
  explicit CoroutinePromise(Args&&... args) {}

  Gen<Final> get_return_object() { return Gen<Final>(my_handle()); }

  std::coroutine_handle<CoroutinePromise> my_handle() {
    return std::coroutine_handle<CoroutinePromise>::from_promise(*this);
  }
  void unhandled_exception() {}
  void return_void() {}

  template <typename U>
  auto await_transform(Gen<U> gen) {
    struct Awaitable {
      bool await_ready() { return false; }
      std::coroutine_handle<> await_suspend(
          const std::coroutine_handle<> handle_in) {
        return handle_in;
      }
      decltype(auto) await_resume() {}
    };
    return Awaitable();
  }

  std::suspend_always initial_suspend() { return {}; }
  std::suspend_always final_suspend() noexcept { return {}; }
};


template <typename Final>
class Gen final {
 public:
  using final_result_type = Final;
  using promise_type =CoroutinePromise<Final>;
  explicit Gen(const std::coroutine_handle<promise_type> handle)
      : handle_(handle) {}

  std::coroutine_handle<promise_type> handle_;  
};

class Foo  {
 public:
  Gen<void> TestBody2() {
    auto s =  [&]() -> Gen<void> { co_await this->CoroutineBody(); }();
    return s;
  }
 private:
  Gen<void> CoroutineBody();
};

Gen<void> Foo::CoroutineBody() {
  if constexpr (0) // remove it make clang compile.
    co_return;
}

int main() {
  return 0;
}
```

**Comment by usx95** [comment]
Interestingly, turning `TestBody2` into a coroutine also makes it work.
```
    Gen<void> TestBody2() {
        auto s = [&]() -> Gen<void> { co_await this->CoroutineBody(); }();
        co_return co_await s;
    }
```

**Comment by hokein** [comment]
Reduced a bit more:

```
#include <coroutine>

class Gen;

class Promise {
 public:
  explicit  Promise() {}
  template <typename Arg>
  explicit Promise(const Arg& args) {}


  Gen get_return_object();

  std::coroutine_handle<Promise> my_handle() {
    return std::coroutine_handle<Promise>::from_promise(*this);
  }

  void unhandled_exception() {}
  void return_void() {}

  std::suspend_always initial_suspend() { return {}; }
  std::suspend_always final_suspend() noexcept { return {}; }
};

class Gen final {
 public:
  using promise_type =Promise;
  explicit Gen(const std::coroutine_handle<promise_type> handle)
      : handle_(handle) {}

  std::coroutine_handle<promise_type> handle_;  
};

Gen Promise::get_return_object() { return Gen(my_handle()); }

class Foo  {
 private:
  Gen f();
};

Gen Foo::f() {
  if constexpr (0) // removing it makes clang compile.
    co_return;
}

int main() {
  return 0;
}
```

The template constructor of `Promise` is:

```
FunctionTemplateDecl 0x55cbcff5cbd0 <line:11:3, line:12:38> col:12 Promise
| |-TemplateTypeParmDecl 0x55cbcff5c940 <line:11:13, col:22> col:22 referenced typename depth 0 index 0 Arg
| |-CXXConstructorDecl 0x55cbcff5cb18 <line:12:3, col:38> col:12 Promise 'void (const Arg &)' implicit-inline
| | |-ParmVarDecl 0x55cbcff5ca28 <col:20, col:31> col:31 args 'const Arg &'
| | `-CompoundStmt 0x55cbcff5d6c8 <col:37, col:38>
| `-CXXConstructorDecl 0x55cbcff623e8 <col:3, col:38> col:12 referenced Promise 'void (const Foo &)' implicit_instantiation implicit-inline
|   |-TemplateArgument type 'Foo'
|   | `-RecordType 0x55cbcff60d90 'Foo'
|   |   `-CXXRecord 0x55cbcff60ce8 'Foo'
|   `-ParmVarDecl 0x55cbcff622d8 <col:20, col:31> col:31 args 'const Foo &'
```

We somehow miss the function body for the template specialization `void (const Foo &)`this causes the undefined symbol error during linking. (Removing the `constexpr 0` branch will bring the function body back).

**Comment by usx95** [comment]
Reduced more: Without use of member coroutines
https://godbolt.org/z/hfEzKEhGd

```cpp
#include <coroutine>

class Gen {
   public:
    class promise_type {
       public:
        template <typename... Args>
        explicit promise_type(Args&&... args) {}

        Gen get_return_object() { return {}; }

        void unhandled_exception() {}
        void return_void() {}
        std::suspend_always await_transform(Gen gen) { return {}; }

        std::suspend_always initial_suspend() { return {}; }
        std::suspend_always final_suspend() noexcept { return {}; }
    };
};

Gen CoroutineBody() {
    if constexpr (0)  // remove it make clang compile.
        co_await Gen{};
    co_await Gen{};
}

int main() { return 0; }
```
As noticed earlier, `CXXConstructorDecl` for `promise_type` is marked as `referenced` instead of `used` and does not have the body attached.

**Comment by usx95** [comment]
This happens because the promise object is built when we see the first coroutine statement which is present in `ExpressionEvaluationContext::DiscardedStatement` context due to `if constexpr (0)`. This makes clang believe that the promise constructor is only odr-used and not really.

I think the solution can be the coroutine body should be built in a separate context irrespective of the context of the first coroutine statement.

**Comment by ChuanqiXu9** [comment]
> I think the solution can be the coroutine body should be built independently in a separate context irrespective of the context of the first coroutine statement.

I didn't understand this fully. What is the meaning of the context here?

**Comment by usx95** [comment]
I am referring to the expression evaluation context. This is set to `DiscardStatement` [here](https://github.com/llvm/llvm-project/blob/main/clang/lib/Parse/ParseStmt.cpp#L1593). The promise object built in `ActOnCoroutineBodyStart` ([source](https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaCoroutine.cpp#L773)) is under the same context.
This sets the `OdrUseContext` for the promise object constructor to be `OdrUseContext::FormallyOdrUsed` instead of correct `OdrUseContext::Used`
(used [here](https://github.com/llvm/llvm-project/blob/51e3d2f73d8f3f5c70f0c1b6b73f62ec9c680cb4/clang/lib/Sema/SemaExpr.cpp#L18887))

**Comment by ChuanqiXu9** [comment]
> I am referring to the expression evaluation context. This is set to `DiscardStatement` [here](https://github.com/llvm/llvm-project/blob/main/clang/lib/Parse/ParseStmt.cpp#L1593). The promise object built in `ActOnCoroutineBodyStart` ([source](https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaCoroutine.cpp#L773)) is under the same context. This sets the `OdrUseContext` for the promise object constructor to be `OdrUseContext::FormallyOdrUsed` instead of correct `OdrUseContext::Used` (used [here](https://github.com/llvm/llvm-project/blob/51e3d2f73d8f3f5c70f0c1b6b73f62ec9c680cb4/clang/lib/Sema/SemaExpr.cpp#L18887))

Thanks. Got it. The proposed solution sounds proper.
