### ISSUE TITLE
[Flang] Pointer deallocation for zero-size target with STAT specifier causes runtime segfault at –O0.

### ISSUE THREAD

**Issue by harishch4** [llvm/llvm-project#78391]
Deallocation of zero-sized pointer target with STAT= specifier causes a runtime segmentation fault and error termination.
The GNU compiler also crashes at runtime but the Intel compiler ifx returns 173 through STAT=.

**Sample.f90**
```
Program test_zero_size_pointer
    Implicit None
    Integer :: istatus
    Integer, Pointer :: xx(:),yy(:)

    Allocate(xx(0))
    yy => xx(4:3)
    Print *,size(yy),associated(yy)
    Deallocate(yy,STAT=istatus);Print *,"yy",istatus
    Deallocate(xx,STAT=istatus);Print *,"xx",istatus

    Call s(0,4,3)
Contains
    Subroutine s(sz,lo,hi)
        Integer, Intent(In):: sz,lo,hi

        Allocate(xx(sz))    
        yy => xx(lo:hi)
        Print *,size(yy),associated(yy)
        Deallocate(yy,STAT=istatus);Print *,"yy",istatus
        Deallocate(xx,STAT=istatus);Print *,"xx",istatus
    End Subroutine
End Program     
```
**ifx output:**

```
           0 T
 yy         173
 xx           0
           0 T
 yy         173
 xx           0
```

**llvm-flang output:**

```
 0 T
free(): invalid pointer
Aborted (core dumped)

```

**Comment by kargl** [comment]
> Deallocation of zero-sized pointer target with STAT= specifier causes a runtime segmentation fault and error termination. The GNU compiler also crashes at runtime but the Intel compiler ifx returns 173 through STAT=.

Works for me with gfortran.

% gfortran13 -o z a.f90 && ./z
           0 T
 yy           0
 xx           0
           0 T
 yy           0
 xx           0
% gfcx -o z a.f90 && ./z
           0 T
 yy           0
 xx           0
           0 T
 yy           0
 xx           0

If you find a bug with gfortran, please report it at fortran@gcc.gnu.org or
through GCC's bugzilla portal.  Thanks.

**Comment by klausler** [comment]
gfortran isn't really passing that test either, since the stat= value for `yy` is zero.

**Comment by kargl** [comment]
> gfortran isn't really passing that test either, since the stat= value for `yy` is zero.

Haven't looked at conformance issues, but setting `stat=` to zero is a far cry from `The GNU compiler also crashes at runtime ...`

**Comment by harishch4** [comment]
> > gfortran isn't really passing that test either, since the stat= value for `yy` is zero.
> 
> Haven't looked at conformance issues, but setting `stat=` to zero is a far cry from _"The GNU compiler also crashes at runtime ..."_

gfortran does crash at runtime. Kindly check [here](https://godbolt.org/z/xb943Pqae).

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/78612

**Comment by klausler** [comment]
Patch has been merged into llvm-project/main.
