### ISSUE TITLE
clang c++ missing diagnostic for function parameter with array of unknown bound

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#7840]
|  |  |
| --- | --- |
| Bugzilla Link | [7468](https://llvm.org/bz7468) |
| Version | unspecified |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Testcase:
bool f(int (*)[]);

**Comment by cor3ntin** [comment]
I believe this is correct code, which all implementations accept
http://eel.is/c++draft/dcl.fct#5.sentence-3 
http://eel.is/c++draft/dcl.array#7

Feel free to reopen if you disagree!

**Comment by efriedma-quic** [comment]
I don't see how the bits you're pointing to are relevant; the argument in the testcase is a pointer to an array, not an array.

When I filed this, the standard said "if the type of a parameter includes a type of the form 'pointer to array of unknown bound of T' or 'reference to array of unknown bound of T,' the program is ill-formed."  It looks like the standard has changed here.

I think the missing diagnostic is still relevant for old standard modes?  Not sure why/when this language got dropped.

**Comment by cor3ntin** [comment]
Found the specific change https://cplusplus.github.io/CWG/issues/393.html
Applied as a DR (ie in all language modes) in 2014.

**Comment by efriedma-quic** [comment]
In that case, I guess we don't need to do anything
