### ISSUE TITLE
[dsymutil] Extremely slow generate dSYM files after the commit D158124  

### ISSUE THREAD

**Issue by conowen** [llvm/llvm-project#78411]
We have found that after the commit https://reviews.llvm.org/D158124 , the time for dsymutil to generate dSYM files in our project has increased from 10 minutes to 45 minutes. Upon inspecting the logs, we noticed an unusually high number of warnings related to "could not find object file symbol for symbol".

This commit was made to support a new feature in Xcode 15, adding support for mergeable libraries. While debugging the LLVM source code, we discovered that the increased time consumption is due to a key code change. 

 <img width="1963" alt="image" src="https://github.com/llvm/llvm-project/assets/1595163/5f331899-7ced-40d1-a9d4-51afc1e96a34">

If the MachODebugMapParser::switchToNewDebugMapObject method encounters a branch where the object cannot be loaded, it simply returns without calling the resetParserState method. This leads to an excessive execution of unnecessary logic in the subsequent handleStabSymbolTableEntry method, while the CurrentObjectAddresses still holds the information of the previous object, and the current object has already moved on to the next one. Before the D158124 commit, entering the MachODebugMapParser::switchToNewDebugMapObject method would directly invoke the resetParserState method. This way, if a branch occurs where the object cannot be loaded, the guard statement in the handleStabSymbolTableEntry method would return early, avoiding the execution of subsequent unnecessary logic.

**Comment by Wooork** [comment]
> > We encountered the same issue after upgrading to Xcode 15.2. In previous Xcode 14, the phase took about 30 seconds, while in Xcode 15.2, it takes more than 10 minutes.`Generating xx.dSYM`
> > After some investigation, we found that this fix was not merged into the branches related to Swift 5.9 (or related to Xcode 15.x). We also tested with Xcode 15.3, and this issue remains unresolved. ~We built the `dsymutil` with the source from the tag `swift-6.0-DEVELOPMENT-SNAPSHOT-2024-04-17-a` which contains this fix, and the time taken dropped to around 50 seconds. Therefore, the issue is fixed~. (Modified: Built with the source from turns out not problem too, and I found that the built 's version is while the one from Xcode 15.2 is , after more searching I found this post: [Xcode ships LLVM 15 but Swift builds LLVM 16 - Development / Compiler - Swift Forums](https://forums.swift.org/t/xcode-ships-llvm-15-but-swift-builds-llvm-16/67377/3). This makes me more confused and helpless.)`` dsymutil``swift-5.9.2-RELEASE``dsymutil``LLVM 16.0.0``LLVM 15.0.0 ``
> > So, my question is, will this fix be included in later Xcode 15.x releases? It might not be the right place to ask this question, as I didn't find any clues about the arrangement of issues for future Xcode releases. Any information or suggestions would be appreciated. Thank you in advance.
> 
> 你好 请问这个问题目前你是怎么解决或者绕过的呢？

Fix the warnings leading to this issue. You can locate the problematic codes by searching "unable to open object file" in the build log.

**Comment by Coder-Star** [comment]
> > > We encountered the same issue after upgrading to Xcode 15.2. In previous Xcode 14, the phase took about 30 seconds, while in Xcode 15.2, it takes more than 10 minutes.`Generating xx.dSYM`
> > > After some investigation, we found that this fix was not merged into the branches related to Swift 5.9 (or related to Xcode 15.x). We also tested with Xcode 15.3, and this issue remains unresolved. ~We built the `dsymutil` with the source from the tag `swift-6.0-DEVELOPMENT-SNAPSHOT-2024-04-17-a` which contains this fix, and the time taken dropped to around 50 seconds. Therefore, the issue is fixed~. (Modified: Built with the source from turns out not problem too, and I found that the built 's version is while the one from Xcode 15.2 is , after more searching I found this post: [Xcode ships LLVM 15 but Swift builds LLVM 16 - Development / Compiler - Swift Forums](https://forums.swift.org/t/xcode-ships-llvm-15-but-swift-builds-llvm-16/67377/3). This makes me more confused and helpless.)` dsymutil`swift-5.9.2-RELEASE`dsymutil`LLVM 16.0.0`LLVM 15.0.0 `
> > > So, my question is, will this fix be included in later Xcode 15.x releases? It might not be the right place to ask this question, as I didn't find any clues about the arrangement of issues for future Xcode releases. Any information or suggestions would be appreciated. Thank you in advance.
> > 
> > 
> > 你好 请问这个问题目前你是怎么解决或者绕过的呢？
> 
> @Coder-Star Fix the warnings leading to this issue. You can locate the problematic codes by searching "unable to open object file" in the build log.

Sorry, I don't quite understand. What I would like to ask is whether you have already used your own built dsymutils in the production environment? If so, which llvm tag is being used?

**Comment by Wooork** [comment]
> > > > We encountered the same issue after upgrading to Xcode 15.2. In previous Xcode 14, the phase took about 30 seconds, while in Xcode 15.2, it takes more than 10 minutes.`Generating xx.dSYM`
> > > > After some investigation, we found that this fix was not merged into the branches related to Swift 5.9 (or related to Xcode 15.x). We also tested with Xcode 15.3, and this issue remains unresolved. ~We built the `dsymutil` with the source from the tag `swift-6.0-DEVELOPMENT-SNAPSHOT-2024-04-17-a` which contains this fix, and the time taken dropped to around 50 seconds. Therefore, the issue is fixed~. (Modified: Built with the source from turns out not problem too, and I found that the built 's version is while the one from Xcode 15.2 is , after more searching I found this post: [Xcode ships LLVM 15 but Swift builds LLVM 16 - Development / Compiler - Swift Forums](https://forums.swift.org/t/xcode-ships-llvm-15-but-swift-builds-llvm-16/67377/3). This makes me more confused and helpless.)` dsymutil`swift-5.9.2-RELEASE`dsymutil`LLVM 16.0.0`LLVM 15.0.0 `
> > > > So, my question is, will this fix be included in later Xcode 15.x releases? It might not be the right place to ask this question, as I didn't find any clues about the arrangement of issues for future Xcode releases. Any information or suggestions would be appreciated. Thank you in advance.
> > > 
> > > 
> > > 你好 请问这个问题目前你是怎么解决或者绕过的呢？
> > 
> > 
> > @Coder-Star Fix the warnings leading to this issue. You can locate the problematic codes by searching "unable to open object file" in the build log.
> 
> Sorry, I don't quite understand. What I would like to ask is whether you have already used your own built dsymutils in the production environment? If so, which llvm tag is being used?

@Coder-Star No, we just fix the warnings in our codebase since conowen has already provided the reason quoted below: 

> If the MachODebugMapParser::switchToNewDebugMapObject method encounters a branch where the object cannot be loaded, it simply returns without calling the resetParserState method.

and this means, no such branches, no issues.

**Comment by Coder-Star** [comment]
> > > > > We encountered the same issue after upgrading to Xcode 15.2. In previous Xcode 14, the phase took about 30 seconds, while in Xcode 15.2, it takes more than 10 minutes.`Generating xx.dSYM`
> > > > > After some investigation, we found that this fix was not merged into the branches related to Swift 5.9 (or related to Xcode 15.x). We also tested with Xcode 15.3, and this issue remains unresolved. ~We built the `dsymutil` with the source from the tag `swift-6.0-DEVELOPMENT-SNAPSHOT-2024-04-17-a` which contains this fix, and the time taken dropped to around 50 seconds. Therefore, the issue is fixed~. (Modified: Built with the source from turns out not problem too, and I found that the built 's version is while the one from Xcode 15.2 is , after more searching I found this post: [Xcode ships LLVM 15 but Swift builds LLVM 16 - Development / Compiler - Swift Forums](https://forums.swift.org/t/xcode-ships-llvm-15-but-swift-builds-llvm-16/67377/3). This makes me more confused and helpless.)` dsymutil`swift-5.9.2-RELEASE`dsymutil`LLVM 16.0.0`LLVM 15.0.0 `
> > > > > So, my question is, will this fix be included in later Xcode 15.x releases? It might not be the right place to ask this question, as I didn't find any clues about the arrangement of issues for future Xcode releases. Any information or suggestions would be appreciated. Thank you in advance.
> > > > 
> > > > 
> > > > 你好 请问这个问题目前你是怎么解决或者绕过的呢？
> > > 
> > > 
> > > @Coder-Star Fix the warnings leading to this issue. You can locate the problematic codes by searching "unable to open object file" in the build log.
> > 
> > 
> > Sorry, I don't quite understand. What I would like to ask is whether you have already used your own built dsymutils in the production environment? If so, which llvm tag is being used?
> 
> @Coder-Star No, we just fix the warnings in our codebase since conowen has already provided the reason quoted below:
> 
> > If the MachODebugMapParser::switchToNewDebugMapObject method encounters a branch where the object cannot be loaded, it simply returns without calling the resetParserState method.
> 
> and this means, no such branches, no issues.

ok I understand. Thank you
