### ISSUE TITLE
checker-242 confused by 2x2 array initializer

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7846]
|  |  |
| --- | --- |
| Bugzilla Link | [7474](https://llvm.org/bz7474) |
| Version | trunk |
| OS | MacOS X |
| Attachments | [Test case](https://user-images.githubusercontent.com/60944935/143741568-b85b9b22-9376-4338-ae83-e328e06eb121.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @gribozavr |

## Extended Description 

Compiling the attached test case yields an incorrect diagnostic, as far as I can see:

/Volumes/Space/Shared/bungi/Downloads/checker-242/bin/clang  --analyze circle_center.m  

circle_center.m:26:37: warning: The right operand of '*' is a garbage value
    double determinantN1 = N1[0][0] * N1[1][1] - N1[1][0] * N1[0][1];
                                    ^ ~~~~~~~~

The N1, N2 and N3 variables are 2x2 arrays of doubles with all four elements initialized. Here it is saying that N1[1][1] is garbage, but it was initialized.

**Comment by arsenm** [comment]
Last comment says fixed
