### ISSUE TITLE
Return type warning for `lookupExtensionByID` in release build

### ISSUE THREAD

**Issue by SchrodingerZhu** [llvm/llvm-project#78488]
https://github.com/llvm/llvm-project/blob/0c6dc80531ed332e346934019095ad9518f465f3/llvm/lib/TargetParser/AArch64TargetParser.cpp#L156

```
/home/schrodingerzy/Documents/llvm/llvm-project/llvm/lib/TargetParser/AArch64TargetParser.cpp:157:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
```

**Comment by JOE1994** [comment]
Seems to have been addressed by https://github.com/llvm/llvm-project/commit/b647a34c9f4ef1527c4641eaa51a771ce81a1fe7
