### ISSUE TITLE
Assertion `(NumParams == FTy->getNumParams() || (FTy->isVarArg() && NumParams > FTy->getNumParams())) && "Calling a function with bad signature!"'

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7850]
|  |  |
| --- | --- |
| Bugzilla Link | [7478](https://llvm.org/bz7478) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 
llvm-gcc raises an internal compiler error on the following (ugly, but nonetheless considered valid by gcc) test case:

typedef void (*fnptr)(int,int *);
void foo( fnptr fn )
{
  (*( (void (*)()) fn))(4, 5, 2, fn);
}

On the other hand, the following does work correctly:

typedef void (*fnptr)(int,int *);
void foo( fnptr fn )
{
  (*( (void (*)(int,int,int,void*)) fn))(4, 5, 2, fn);
}

It looks like gcc emits an explicit MODIFY_EXPR in the tree for the second case, but not for the first, so EmitCALL_EXPR receives an uncast fn, leading to the assertion failure above when it tries to construct the Call.

I'm not sure what the correct fix is here - possibly the Builder needs to check for function/arg agreement and insert a cast if necessary?

This is reproduceable with (at least) 2.6 and 2.7 and trunk, and on Linux, Solaris + OS X

**Comment by gwelymernans** [comment]
This doesn't crash in Clang. I'm going to close this out. If you find another ICE, please open a fresh issue.
