### ISSUE TITLE
Stack dump bug

### ISSUE THREAD

**Issue by 7Zon2** [llvm/llvm-project#78524]
I apologize in advance that my example is large, but I could not reproduce it in a smaller size. I tried to pass arguments using a nested lambda function to a require constraint but got an error. I also wrote a definition directive that switches between a concept and a lambda function (equally constrained), and got different results.

https://godbolt.org/z/41zfjdoTs

**Comment by shafik** [comment]
Related: https://github.com/llvm/llvm-project/issues/72557

**Comment by shafik** [comment]
Reduced but still one library include: https://godbolt.org/z/qGE9f31KG

```cpp
#include <functional>

template<typename...Lambdas>
struct overloaded : Lambdas... {
    using Lambdas::operator()...;
};

template<typename...Lambdas>
overloaded(Lambdas...) -> overloaded<Lambdas...>;


void f() {
    std::tuple t{int{},int{}};

 
std::invoke(
    overloaded{ [](){},
    []<typename T> requires requires(T&& obj){    
        std::apply([](auto...){} , obj);
    }(T&&) {}}, t );
}
```

I tried doing a real brain dead replacement for `invoke` but that did not work so someone needs to do a reduction to remove that requirement.

**Comment by ilovepi** [comment]
you can use `-gen-reproducer=always` to generate a reproducer and script. https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-gen-reproducer

That will get you a preprocessed file + script.

**Comment by vient** [comment]
> Reduced but still one library include: https://godbolt.org/z/qGE9f31KG

Interesting that trunk and 16.0.0 crash but 17.0.1 does not. 17.0.6 on my machine also crashes though.

Reduced with 17.0.6 based on `clang::TemplateArgument::isPackExpansion` presence in output to https://godbolt.org/z/7WMeh4rTc
Guess someone smarter will be able to reduce it further manually, this one was obtained from cvise + some manual tinkering.

**Comment by vient** [comment]
Managed to get this beauty with the help of assertions trunk https://godbolt.org/z/PKP991anT
May not be exactly related to original problem though.

**Comment by shafik** [comment]
Reduced code that matches the OP's original example backtrace:

```cpp
template<typename a>
a b;

template<typename a>
auto c(b<a>);

template<typename a, typename... b>
struct d {
    decltype(a()(c<b>...)) c;
};

template<typename a, typename b>
d<a, b> g(a, b);

struct e {};

void f() {
    g(
        []<typename a>
        requires requires { [](auto...) {}; }(a)
        {},
        e{}
    );
}

```
