### ISSUE TITLE
C++: Checker/PathSensitive/CheckerVisitor.h:41 Assertion `false && "Unsupport statement."' failed

### ISSUE THREAD

**Issue by edwintorok** [llvm/llvm-project#7852]
|  |  |
| --- | --- |
| Bugzilla Link | [7480](https://llvm.org/bz7480) |
| Version | trunk |
| OS | Linux |
| Attachments | [clang_crash_0bfkhe.ii](https://user-images.githubusercontent.com/92601246/143741573-2687f0c1-72c2-4793-aeaa-69494da4338f.gz) |

## Extended Description 

This happens when running the analyzer on RE2 (code.google.com/p/re2).

clang_crash_0bfkhe.ii.info.txt:
Crash
-cc1 -DIBOutlet=__attribute__((iboutlet)) -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -main-file-name stringpiece.cc -mrelocation-model static -mdisable-fp-elim -mconstructor-aliases -munwind-tables -target-cpu x86-64 -resource-dir /home/edwin/llvm-git/obj/Release/lib/clang/2.0 -D NDEBUG -I . -Wno-sign-compare -ferror-limit 19 -fmessage-length 0 -fexceptions -fgnu-runtime -fdiagnostics-show-option -x c++ util/stringpiece.cc
Linux debian 2.6.34-00179-gdebb980 #&#8203;60 SMP PREEMPT Sat May 29 20:03:06 EEST 2010 x86_64 GNU/Linux
Using built-in specs.
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.4.4-5' --with-bugurl=file:///usr/share/doc/gcc-4.4/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --enable-shared --enable-multiarch --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.4 --program-suffix=-4.4 --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-objc-gc --with-arch-32=i486 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.4.4 (Debian 4.4.4-5)

clang_crash_0bfkhe.ii.stderr.txt:
clang++: /home/edwin/llvm-git/clang/lib/Checker/../../include/clang/Checker/PathSensitive/CheckerVisitor.h:41: void clang::CheckerVisitor<ImplClass>::PreVisit(clang::CheckerContext&, const clang::Stmt*) [with ImplClass = <unnamed>::AdjustedReturnValueChecker]: Assertion `false && "Unsupport statement."' failed.
0  clang++         0x00000000012f972f
1  clang++         0x00000000012fa26a
2  libpthread.so.0 0x0000003f5dc0ef60
3  libc.so.6       0x0000003f5d032175 gsignal + 53
4  libc.so.6       0x0000003f5d034f80 abort + 384
5  libc.so.6       0x0000003f5d02b2b1 __assert_fail + 241
6  clang++         0x000000000095d39c
7  clang++         0x00000000008d941f
8  clang++         0x00000000008e79c1
9  clang++         0x00000000008ded48
10 clang++         0x00000000008e3a50
11 clang++         0x00000000008df349
12 clang++         0x00000000008e9216
13 clang++         0x00000000008d6013
14 clang++         0x00000000008d6a20
15 clang++         0x000000000086033e
16 clang++         0x000000000085f8f9
17 clang++         0x000000000085fcf8
18 clang++         0x000000000066a56f
19 clang++         0x000000000042524d
20 clang++         0x0000000000409075
21 clang++         0x000000000040fa25 main + 2629
22 libc.so.6       0x0000003f5d01ec4d __libc_start_main + 253
23 clang++         0x0000000000407129
Stack dump:
0.      Program arguments: /home/edwin/llvm-git/obj/Release/bin/clang++ -cc1 -DIBOutlet=__attribute__((iboutlet)) -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -main-file-name stringpiece.cc -mrelocation-model static -mdisable-fp-elim -mconstructor-aliases -munwind-tables -target-cpu x86-64 -resource-dir /home/edwin/llvm-git/obj/Release/lib/clang/2.0 -D NDEBUG -I . -Wno-sign-compare -ferror-limit 19 -fmessage-length 0 -fexceptions -fgnu-runtime -fdiagnostics-show-option -x c++ util/stringpiece.cc -analyze -analyzer-display-progress -analyzer-eagerly-assume -analyzer-opt-analyze-nested-blocks -analyzer-check-objc-mem -analyzer-check-security-syntactic -analyzer-check-dead-stores -analyzer-check-objc-unused-ivars -analyzer-check-objc-methodsigs -analyzer-store=region -analyzer-constraints=range -analyzer-output=html -o /tmp/scan-build-2010-06-24-1 
1.      <eof> parser at end of file
2.      util/stringpiece.cc:43:22: Error evaluating statement
3.      util/stringpiece.cc:43:22: Error evaluating statement
4.      util/stringpiece.cc:43:28: Error evaluating statement

**Comment by Endilll** [comment]
Appears to be fixed in Clang 2.8: https://cexplorer.testlabs.pro/z/GW4dPf
