### ISSUE TITLE
Using `std::format` with `float` or `double` based `std::chrono::time_point` causes `error: invalid operands to binary expression`

### ISSUE THREAD

**Issue by HirthammerAllTerra** [llvm/llvm-project#78555]
Consider the following code snippet:

~~~ cpp
using Representation = double;
using Duration       = std::chrono::duration<Representation>;
using Clock          = std::chrono::system_clock;
using TimePoint      = std::chrono::time_point<Clock, Duration>;

TimePoint tp = {};

std::string time_string = std::format("{:%d.%m.%Y %H:%M:%S}", tp);
~~~

This results in the compile error:

~~~
error: invalid operands to binary expression ('basic_ostringstream<char>' and 'const std::chrono::time_point<std::chrono::system_clock, std::chrono::duration<double>>')
                  __os << __t;
                  ~~~~ ^  ~~~
~~~

If you change the type def `Representation` to an integer or unsigned integer type, the code compiles.

System Info:

~~~
OS: Ubuntu 22.04 LTS
Clang-Version: 15.0.7
~~~

Here is a link with the code that produces the error at [Compiler Explorer](https://godbolt.org/z/4nqP6jn4c). The error is still present in the newest available Clang version (17.0.1) at Compiler explorer.

**Comment by jwakely** [comment]
This is a [bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113500) in libstdc++ headers, not Clang. This should be closed.

You need to be aware that Clang on Compiler Explorer uses libstdc++ unless you use `-stdlib=libc++`

**Comment by HirthammerAllTerra** [comment]
> This is a [bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113500) in libstdc++ headers, not Clang. This should be closed.
> 
> You need to be aware that Clang on Compiler Explorer uses libstdc++ unless you use `-stdlib=libc++`

Thanks for clarifying this. I wasn't aware of it. For anybody who is

**Comment by jwakely** [comment]
https://github.com/compiler-explorer/compiler-explorer/issues/3682 has a good explanation.

**Comment by mordante** [comment]
Thanks @jwakely
