### ISSUE TITLE
[BDCE] Missed optimization: simplify demanded bits on multi-use instructions

### ISSUE THREAD

**Issue by XChy** [llvm/llvm-project#78596]
Alive2 proof: https://alive2.llvm.org/ce/z/8qHKuR

### Motivating example

```llvm
define void @src(i1 %c, i64 %a, i64 %b) #0 {
entry:
  %and1 = and i64 %a, 24 ; mask 0001 1000
  %and2 = and i64 %b, 25 ; mask 0001 1001
  %s = select i1 %c, i64 %and1, i64 %and2
  %ret1 = and i64 %s, 8    ; demanded bits: 0000 1000
  %ret2 = and i64 %s, 16   ; demanded bits: 0001 0000
  call void @use(i64 %ret1)
  call void @use(i64 %ret2)
  ret void
}
```

can be simplified to:

```llvm
define void @tgt(i1 %c, i64 %a, i64 %b) #0 {
entry:
  %s = select i1 %c, i64 %a, i64 %b
  %ret1 = and i64 %s, 8
  %ret2 = and i64 %s, 16
  call void @use(i64 %ret1)
  call void @use(i64 %ret2)
  ret void
}
```

Until now, InstCombine doesn't support simplifying multi-use instructions based on demanded bits and only computes their KnownBits. However, that's common in the scenarios like doing bitwise operations in loops.

### Real-world motivation

This snippet of IR is derived from [qemu/hw/virtio/vhost-shadow-virtqueue.c@vhost_svq_valid_features](https://github.com/qemu/qemu/blob/7425b6277f12e82952cede1f531bfc689bf77fb1/hw/virtio/vhost-shadow-virtqueue.c#L27) (after O3 pipeline).
The example above is a reduced version. If you're interested in the original suboptimal IR and optimal IR, see also:https://godbolt.org/z/6rsvv4q61

**Let me know if you can confirm that it's an optimization opportunity, thanks.**

**Comment by nikic** [comment]
It's not possible to do this in InstCombine, but it should be possible to handle this in BDCE.

**Comment by antoniofrighetto** [comment]
@XChy, can take a look at it over the weekend if you wish.

**Comment by XChy** [comment]
> @XChy, can take a look at it over the weekend if you wish.

Sure! Thanks for looking into it.
