### ISSUE TITLE
[flang] MOD 7x performance regression

### ISSUE THREAD

**Issue by vzakhari** [llvm/llvm-project#78641]
Polyhedron/ac slowed down by 3.7x after https://github.com/llvm/llvm-project/pull/77167
`_FortranAModReal8` itself slowed down by 7.4x

I wonder if it can use the previous approach for not so different `a` and `p`.

**Comment by vzakhari** [comment]
Another observation is that in the `ac` benchmark both values seem to be integers.

**Comment by klausler** [comment]
Can you give me a link to the exact call site in the source that you believe is passing integer arguments?

**Comment by vzakhari** [comment]
There is a single call site in file `ac.f90`:
```
      REAL FUNCTION GGL(Ds)

!     +     D1,
      DOUBLE PRECISION Ds , d2
!      DATA D1/2147483648.D0/
      DATA d2/2147483647.D0/
      Ds = DMOD(16807.D0*Ds,d2)
!     Generate U(0,1] distributed random numbers:
      GGL = Ds/d2

      CONTINUE
      END
```
