### ISSUE TITLE
The return value of `column()` obtained from `std::source_location::current()` should be documented

### ISSUE THREAD

**Issue by frederick-vs-ja** [llvm/llvm-project#78657]
Per standard requirements ([N4868 [source.srcloc.cons]/1.1](https://timsong-cpp.github.io/cppwp/n4868/support.srcloc.cons#1.1), [N4868 [support.srcloc.obs]/2](https://timsong-cpp.github.io/cppwp/n4868/support.srcloc.obs#2)), the return value of `column()` obtained from `std::source_location::current()` is implementation-defined and thus should be documented.

Currently, `__builtin_COLUMN` and `__builtin_source_location` are mentioned in [this page](https://clang.llvm.org/docs/LanguageExtensions.html#source-location-builtins), but their values are not well-documented.

Documentations of implementations would be helpful when one wants use `column()`, as there's implementation divergence (can be found in [this test file in MSVC STL](https://github.com/microsoft/STL/blob/0cb9eb45b5d13015a28670a47b6c9760038d3e66/tests/std/tests/P1208R6_source_location/test.cpp)).

**Comment by komalverma04** [comment]
I will work on it today.

**Comment by GeorgeKA** [comment]
Hello. No one appears to be assigned or working on this. Can it be assigned to me?

**Comment by GeorgeKA** [comment]
Hi @cor3ntin & @frederick-vs-ja  . Checking if this is an issue that's still active. I'd be happy to work on it if so.
