### ISSUE TITLE
[libc] Unit tests fail to build in fullbuild due to undefined symbols

### ISSUE THREAD

**Issue by SchrodingerZhu** [llvm/llvm-project#78743]
![image](https://github.com/llvm/llvm-project/assets/20108837/56faf8c3-b88f-4a07-9f98-9e138a5c1005)

Unit test objects are seeking for `_Unwind_Resume`.

**Comment by SchrodingerZhu** [comment]
This seems to be a clang bug since it is inside runtime build. `-fno-exception` and `-fno-unwind-tables` are specified, there should be no dependency to libunwind if I understand it correctly. cc @michaelrj-google

**Comment by michaelrj-google** [comment]
The actual library shouldn't have any dependency on libunwind or any other C++ runtime components, I would guess that the tests would be similar but the limitations on them aren't as strict.
