### ISSUE TITLE
clang-format wrongly removes a space after "delete &&"

### ISSUE THREAD

**Issue by Julien-Elie** [llvm/llvm-project#78789]
When a variable is named `delete` in C code, a space is removed in `&&` conditions (but not in `||` conditions):

```
int delete = 0;
int num = 0;

if (delete &&num) {
  delete = 1;
}

if (!delete &&num) {
  delete = 1;
}
if (delete || num) {
  delete = 1;
}
```

Tested with clang-format 16.0.6.

Could it be fixed?  Maybe other special variables like `delete` are also impacted.

**Comment by rymiel** [comment]
Most likely related to https://github.com/llvm/llvm-project/issues/43678

**Comment by Julien-Elie** [comment]
Many thanks for having taken into account the report, and already provided a fix!
