### ISSUE TITLE
[flang] Failed substitution with preprocessor

### ISSUE THREAD

**Issue by bcornille** [llvm/llvm-project#78797]
### Issue:
flang does not substitute a preprocessor variable in a snake case Fortran variable. In order to get substitution some codes use continuation lines so that the preprocessor variable can be inserted in-between underscores in code. flang appears to concatenate continuation lines prior to applying the preprocessor substitutions so the substitution does not occur.

#### main.F90
```Fortran
program main
  implicit none
#define LETTER b
  integer, parameter :: a_&
    &LETTER&
    &_c = 1
  write(*,*) a_b_c
end program main
```
#### compilation:
```shell
>> flang-new -c main.F90
error: Semantic errors in main.F90
./main.F90:8:14: error: No explicit type declared for 'a_b_c'
    write(*,*) a_b_c
               ^^^^^
```
#### preprocessed source:
```
>> flang-new -E main.F90
#line "./main.F90" 1
      program main
      implicit none
      integer, parameter :: a_LETTER_c = 1
      write(*,*) a_b_c
      end program main
```
#### GNU behavior:
```
>> gfortran -E main.F90
# 1 "main.F90"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "main.F90"
program main
  implicit none
  integer, parameter :: a_&
    &b&
    &_c = 1
  write(*,*) a_b_c
end program main
```

**Comment by klausler** [comment]
That's indeed how it works in f18; continuation lines are combined prior to macro substitution, so that macro references can span multiple lines.

**Comment by bcornille** [comment]
So I guess due to that design decision there is no way to get macro substitution in the middle of a variable as demonstrated by the example code, correct? A macro function would probably need to be used instead to construct the composite name.

**Comment by klausler** [comment]
Token pasting with `##` works.  In fixed-form code, just use spaces between the parts of the name.

**Comment by klausler** [comment]
I'm looking into tweaking the interaction between continuation line joining and preprocessing a little to accommodate this case.  In short, I may be able to allow the pp-tokens that constitute a macro reference to span multiple continuation lines, but not the individual identifier tokens themselves.

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/78868

**Comment by klausler** [comment]
Patch has been merged into llvm-project/main.

**Comment by bcornille** [comment]
I have encountered some patterns that are not addressed by this fix.
```fortran
program main
  implicit none
#define LETTER b
  integer, parameter :: a_&
    &LETTER&
    &_c = 1
  write(*,*) a_b_c
contains
subroutine test_&
&LETTER&
&(input)
  integer :: input
end subroutine test_&
&LETTER
end program main
```
output:
```shell
>> flang-new -E main.F90
#line "./main.F90" 1
      program main
      implicit none

      integer, parameter :: a_b_c = 1


      write(*,*) a_b_c
      contains
      subroutine test_LETTER(input)


      integer :: input
      end subroutine test_LETTER

      end program main
```
Please advise whether these can be accommodated or whether code changes should be considered instead.

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/79628

**Comment by EugeneZelenko** [comment]
Not merged yet.

**Comment by klausler** [comment]
Fix merged.

**Comment by bcornille** [comment]
Hi Peter,

Apologies, but I have one more edge case.
In this case there is a space between the token and the continuation symbol prior to the subroutine arguments.
```Fortran
program main
  implicit none
#define LETTER b
  integer, parameter :: a_&
    &LETTER&
    &_c = 1
  write(*,*) a_b_c
contains
subroutine test_&
&LETTER &
&(input)
  integer :: input
end subroutine test_&
&LETTER
end program main
```
Let me know if this additional space is for some reason problematic with respect to being valid source code and I will advise changes in the original application.

gfortran for reference:
```shell
>> gfortran -E test.F90
# 1 "test.F90"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "test.F90"
program main
  implicit none

  integer, parameter :: a_&
    &b&
    &_c = 1
  write(*,*) a_b_c
contains
subroutine test_&
&b &
&(input)
  integer :: input
end subroutine test_&
&b
end program main
```
