### ISSUE TITLE
clang is sometimes suboptimal for `copysign(x, y)` when the sign of y is known

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#78825]
Test case:
https://godbolt.org/z/6hjYTvjW8
```c
#include <math.h>

float f(float x)
{    
     return copysignf(1.0f, x * x); 
}

float g(float x) 
{ 
     return (x > 0.0f) ? copysignf(1.0f, x) : 1.0f; 
}
```

If `-ffast-math` is specified, clang can optimize `f`.

**Comment by topperc** [comment]
If `x` is -nan, `x * x` isn't guaranteed positive is it?

**Comment by k-arrows** [comment]
> If `x` is -nan, `x * x` isn't guaranteed positive is it?

OK, this may account for the current behavior. I will close this issue.
