### ISSUE TITLE
clang-format option AfterPlacementOperator should be a boolean

### ISSUE THREAD

**Issue by owenca** [llvm/llvm-project#78892]
IMO, we don't need the `Leave` value for `AfterPlacementOperator`. @mydeveloperday @HazardyKnusperkeks @rymiel @omarahmed1111 what do you think?

**Comment by HazardyKnusperkeks** [comment]
One does never really **need** a `Leave`. But I someone even asked for a leave style to adapt the formatting options one by one. And from that perspective I'm in favor of `Leave` options, although I'll most likely never use one myself.

**Comment by owenca** [comment]
A `Leave` value is needed for some options (e.g. `BreakAfterAttributes`) but not options like `AfterPlacementOperator` IMO. Why would we want to support inconsistency in the formatted code irt whether to have a space between the new/delete keyword and the opening parenthesis?

Also,  only `AfterPlacementOperator` is an `enum` in `SpaceBeforeParensOptions`. Everything else is a `bool`. So I think we should change `AfterPlacementOperator` to a boolean for simplicity and consistency.

**Comment by HazardyKnusperkeks** [comment]
If you want to convert, that should happen before the LLVM 18 release, after that I'd say we can't remove the `Leave` option anymore.

**Comment by owenca** [comment]
@tstellar can this be merged before rc2? We need to get the fix into the very first official release of 18.x.
