### ISSUE TITLE
`a + b - abs(a - b)` --> `2 * MIN(a, b)`, and `a + b + abs(a - b)` --> `2 * MAX(a, b)`

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#78891]
Alive2 Proof: https://alive2.llvm.org/ce/z/6Es_iH
Godbolt: https://godbolt.org/z/W7GGKd3jo
```c
#include <stdlib.h>

#define MIN(i, j) (((i) < (j)) ? (i) : (j))
#define MAX(i, j) (((i) > (j)) ? (i) : (j))

int src1(int a, int b)
{
    return a + b - abs(a - b);
}

int tgt1(int a, int b)
{
    return 2 * MIN(a, b);
}

int src2(int a, int b)
{
    return a + b + abs(a - b);
}

int tgt2(int a, int b)
{
    return 2 * MAX(a, b);
}
```

At least from my point of view, no real-world motivation exists here. So this issue may be more of a theoretical confirmation than a benefit to this simplification.

**Comment by nikic** [comment]
I'll just go ahead and close this. If there is no real-world motivation, we should not implement this pattern.
