### ISSUE TITLE
The `opt -passname` syntax for the new pass manager is not supported 

### ISSUE THREAD

**Issue by LukeLIN-web** [llvm/llvm-project#78902]
https://llvm.org/docs/WritingAnLLVMPass.html   

->  [Running a pass with opt](https://llvm.org/docs/WritingAnLLVMPass.html#id9)  

The previous steps seem good.

I run 
```
opt -load lib/LLVMHello.so -hello -time-passes < hello.bc > /dev/null
```

But it shows 

```
The `opt -passname` syntax for the new pass manager is not supported, please use `opt -passes=<pipeline>` (or the `-p` alias for a more concise version).
See https://llvm.org/docs/NewPassManager.html#invoking-opt for more details on the pass pipeline syntax.
``` 

I tried 
```
./bin/opt -load ./lib/LLVMHello.dylib -passes=helloworld < hello.bc > /dev/null
```

But the output only has `main`, doesn't have `Hello`. Why it is not the pass we defined in `lib/Transforms/Hello/Hello.cpp `?

**Comment by dtcxzyw** [comment]
See also https://llvm.org/docs/WritingAnLLVMNewPMPass.html for writing an LLVM pass under the new pass manager.

If you want to load a plugin in opt, use `-load-pass-plugin=path/to/plugin.so` instead.

References:
+ https://llvm.org/docs/NewPassManager.html#inserting-passes-into-default-pipelines
+ https://github.com/dtcxzyw/fsubfuscator/blob/main/opt-fsub.sh.in

**Comment by LukeLIN-web** [comment]
> See also https://llvm.org/docs/WritingAnLLVMNewPMPass.html for writing an LLVM pass under the new pass manager.
> 
> If you want to load a plugin in opt, use `-load-pass-plugin=path/to/plugin.so` instead.
> 
> References:
> 
> * https://llvm.org/docs/NewPassManager.html#inserting-passes-into-default-pipelines
> * https://github.com/dtcxzyw/fsubfuscator/blob/main/opt-fsub.sh.in

Thank you for your reply. I learned from https://llvm.org/docs/WritingAnLLVMNewPMPass.html
