### ISSUE TITLE
[flang] legacy extension of kind selector does not work properly

### ISSUE THREAD

**Issue by foxtran** [llvm/llvm-project#78927]
In the following example (`test.f`):
```fortran
      subroutine test(r8heap, i8heap, scrsize)
      integer*4 i8heap(*)
      real*8 r8heap(scrsize)
      end
```
flang says:
```
$ flang-new test.f
error: Could not scan test.f
./test.f:3:28: error: Unmatched ')'
        real*8 r8heap(scrsize)
                             ^
```

I had similar issues with `integer*4 i8heap(*)` but I could not reproduce it. I suppose it has the same reason like with `real*8 r8heap(scrsize)`.

Used version:
```
bin/flang-new --version
flang-new version 18.0.0git (https://github.com/llvm/llvm-project.git 5518a9d7673bfe55b4110bea049140316d032fbf)
```

**Comment by klausler** [comment]
The `8H` is probably being mistaken for the beginning of a Hollerith literal.

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/79029

**Comment by klausler** [comment]
Fix has been merged into llvm-project/main.
