### ISSUE TITLE
[Flang][OpenMP] Incorrect execution result of a do-variable defined as shared in parallel construct

### ISSUE THREAD

**Issue by ohno-fj** [llvm/llvm-project#78938]
```
Version of flang-new : 18.0.0(0fe86f9c518fb1296bba8d66ce495f9dfff2c435)

```

A `do-variable` defined as `shared` in `parallel` construct  has an incorrect value after executing `parallel` construct.  
A `do-variable` is executing by `private`, not `shared`.

The following are the test program, Flang-new, Gfortran and ifort compilation/execution result.

snggz567_22.f90:
```fortran
subroutine s1
  ip=100
  ip2=-100
!$omp parallel shared(ip) private(ip2)
  DO ip = 0, 1
  END DO
  DO ip2 = 0, 1
  END DO
!$omp end parallel
  print *,'ip  shared  :',ip
  print *,'ip2 private :',ip2
end subroutine s1

program main
  call s1
end program main
```

```
$ export OMP_NUM_THREADS=2; flang-new -fopenmp snggz567_22.f90; ./a.out
 ip  shared  : 100
 ip2 private : -100
$
```

```
$ export OMP_NUM_THREADS=2; gfortran -fopenmp snggz567_22.f90; ./a.out
 ip  shared  :           2
 ip2 private :        -100
$
```

```
$ export OMP_NUM_THREADS=2; ifort -qopenmp snggz567_22.f90; ./a.out
 ip  shared  :           2
 ip2 private :        -100
$
```

**Comment by mjklemm** [comment]
The code is non-confirming OpenMP code.  There is a race condition on the `ip` variable.

**Comment by luporl** [comment]
Even removing the race condition, there is still an issue with flang, as the program below still prints `ip  shared  : 100`.

```f90
subroutine s1
  ip=100
!$omp parallel shared(ip)
!$omp single
  DO ip = 0, 1
  END DO
!$omp end single
!$omp end parallel
  print *,'ip  shared  :',ip
end subroutine s1

program main
  call s1
end program main
```

It seems the problem is that flang is treating `ip` as predetermined, even with the `shared` clause which seems to be allowed by OpenMP 5.2 5.1.1 in this case:

> Loop iteration variables of loops that are not associated with any OpenMP directive may be listed in data-sharing attribute clauses on the surrounding teams, parallel or task generating construct, and on enclosed constructs, subject to other restrictions.
