### ISSUE TITLE
llc crashes on functions with union as an argument

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7911]
|  |  |
| --- | --- |
| Bugzilla Link | [7539](https://llvm.org/bz7539) |
| Version | 2.7 |
| OS | Linux |
| Attachments | [Simplified test case which crashes llc](https://user-images.githubusercontent.com/60944935/143741616-82ca9923-5b07-4f62-a2cc-8431ecf59558.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 

Any function I try with a union as an argument seems to compile OK until it gets to llc, and then I get an error "UNREACHABLE executed!" An example (bitcode attached):

target triple = "i386-pc-linux-gnu"

define void @&#8203;union_fail(union { i32 } %x) nounwind readnone {
entry:
  ret void
}

Note that it's fine if you pass a pointer to a union, just not a union object, struct containing a union, etc. With --march=x86:

UNREACHABLE executed!
0  libLLVM-2.7.so.1 0x017e4698
Stack dump:
0.	Program arguments: llc bugpoint-reduced-simplified.ll 
1.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@union_fail'
Aborted

I tried a number of architectures, and they all crash on different passes, but with the same error. For example, --march=arm:

UNREACHABLE executed!
0  libLLVM-2.7.so.1 0x018a7698
Stack dump:
0.	Program arguments: llc --march=arm bugpoint-reduced-simplified.ll 
1.	Running pass 'ARM Instruction Selection' on function '@union_fail'
Aborted

This affects all architectures, so I have filed it under Common Code Generator Code.

Running Ubuntu 10.04, using the version of LLVM that came with Ubuntu 10.04 (llvm 2.7-0ubuntu1).

**Comment by arsenm** [comment]
IR unions no longer exist
