### ISSUE TITLE
Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.

### ISSUE THREAD

**Issue by JonPsson1** [llvm/llvm-project#79193]
clang -cc1 -triple s390x-ibm-linux -S -target-cpu arch13 -O3 -vectorize-slp -mllvm -slp-optimize-identity-hor-reduction-ops=false -o /dev/null tc_slp.ll

#9 0x000002aa036c0d2e llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes()

[tc_slp.tar.gz](https://github.com/llvm/llvm-project/files/14028848/tc_slp.tar.gz)

@alexey-bataev

**Comment by alexey-bataev** [comment]
Fixed in bb3e0d7fc34899f22cbaea311982098bae3de061
