### ISSUE TITLE
Poolalloc should support 64-bit allocation sizes

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7920]
|  |  |
| --- | --- |
| Bugzilla Link | [7548](https://llvm.org/bz7548) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Currently, the automatic pool allocation transform and run-time assume that the sizes of objects can be represented in 32 bits.  However, what it should probably do is assume that the object length and pointer size are identical.  This would allow it to handle large allocations on 64-bit systems.

**Comment by arsenm** [comment]
I can't find any trace of this in current sources, I'm not sure it made the jump to the monorepo:

https://github.com/llvm-mirror/poolalloc/tree/master
