### ISSUE TITLE
x86-64 -O0 -g tests crash

### ISSUE THREAD

**Issue by 1ba3d143-a64b-4671-82b2-0b31cfb91709** [llvm/llvm-project#7921]
|  |  |
| --- | --- |
| Bugzilla Link | [7549](https://llvm.org/bz7549) |
| Version | trunk |
| OS | All |

## Extended Description 
These tests crash when built with -O0 -g on x86-64, Darwin PIC:

External/SPEC/CINT2000/176_gcc/176_gcc [LLC, LLC compile]
MultiSource/Applications/JM/lencod/lencod [LLC, LLC compile]
SingleSource/Benchmarks/Shootout-C++/except [LLC, LLC compile]
SingleSource/Regression/C++/EH/ctor_dtor_count [LLC, LLC compile]
SingleSource/UnitTests/ObjC/exceptions [LLC, LLC compile]

TEST Output/exceptions.llc FAILED: process terminated by signal (exit status 134)!
TEST Output/ctor_dtor_count.llc FAILED: process terminated by signal (exit status 134)!
TEST Output/except.llc FAILED: process terminated by signal (exit status 134)!
TEST Output/lencod.llc FAILED: process terminated by signal (exit status 139)!
TEST ../176.gcc.llc FAILED: process terminated by signal (exit status 139)!

Exit status 134 = SIGABRT = abort(3) call
Exit status 139 = SIGSEGV = segmentation violation

**Comment by chfast** [comment]
This issue looks incomplete to me. Are these tests even a part of LLVM?

**Comment by arsenm** [comment]
> This issue looks incomplete to me. Are these tests even a part of LLVM?

Yes, they're just not in the main repo.

There's no way these are still broken at this point
