### ISSUE TITLE
Problem with '==' and vectors

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#7925]
|  |  |
| --- | --- |
| Bugzilla Link | [7553](https://llvm.org/bz7553) |
| Version | trunk |
| OS | Windows XP |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The code:
```c
void func()
{
	static vector float v1;
	static vector float v2;
	if (v1 == v2)
		return;
}
```
The error:

>clang -cc1 -triple=ppu-unknown-lv2 -faltivec vecindex.cpp
```
vecindex.cpp:5:6: error: value of type 'int  __attribute__((ext_vector_type(4)))' is not contextually convertible to 'bool'
        if (v1 == v2)
            ^~~~~~~~
1 error generated.
```

**Comment by philnik777** [comment]
Not sure which compiler this was broken on, but the oldest compiler I could get to do something accepts this code: https://godbolt.org/z/EY6WE3WdM

**Comment by Endilll** [comment]
This issue was filed between 2.7 and 2.8 releases. Looks like altivec support has to be explicitly enabled during clang compilation back then: https://godbolt.org/z/hh179z6hc
I wonder if altivec was experimental back then.
