### ISSUE TITLE
Backport cfddb59 to release/18.x

### ISSUE THREAD

**Issue by mariusz-sikora-at-amd** [llvm/llvm-project#79277]
/cherry-pick cfddb59

This is one of the features which we missed to merged before branching 18.x.
Would it be possible to include these in llvm 18 ?

**Comment by nikic** [comment]
The commit you referenced does not exist.

**Comment by jayfoad** [comment]
Yes it does! It is cfddb59be2124f7ec615f48a2d0395c6fdb1bb56.

**Comment by nikic** [comment]
Weird, GitHub is not able to find that commit when using the truncated hash.

/cherry-pick cfddb59be2124f7ec615f48a2d0395c6fdb1bb56

**Comment by tstellar** [comment]
Merged: 2d759eff89d3e8c95caaa3b82a6c567cc42a560b
