### ISSUE TITLE
Backport 33ecef9812e2c9bfadef035b8e34a949acae2abc to release/18.x

### ISSUE THREAD

**Issue by KanRobert** [llvm/llvm-project#79279]
This can address buildbot failures:

https://logs.chromium.org/logs/fuchsia/buildbucket/cr-buildbucket/8758116827299910209/+/u/build/ninja/stdout

CC @phoebewang @RKSimon @gulfemsavrun

commit: 33ecef9812e2c9bfadef035b8e34a949acae2abc
PR: https://github.com/llvm/llvm-project/pull/79245

**Comment by tstellar** [comment]
Merged: 453ff4b7333d4cfef8593fdf54de831d32321e44
