### ISSUE TITLE
Warn for missing braces around indented statements

### ISSUE THREAD

**Issue by belkadan** [llvm/llvm-project#7927]
|  |  |
| --- | --- |
| Bugzilla Link | [7555](https://llvm.org/bz7555) |
| Version | unspecified |
| OS | All |
| CC | @akyrtzi,@tkremenek,@nico,@zygoloid,@seanm,@tobiasgrosser |

## Extended Description 
Might be a dream, but Clang should have a warning for this sort of code:
```c++
if (!valid(str))
  log("Invalid input: %s", str);
  return NULL;
return process(str);
```
The "return NULL" line is clearly supposed to be part of the consequent block.

A fixit would be nice but not always correct, since maybe a user just forgot to dedent in some cases.

**Comment by philnik777** [comment]
Clang 10 added `-Wmisleading-indentation` for this: https://godbolt.org/z/f4eEEv5rz
