### ISSUE TITLE
Backport 7fdf608 to release/18.x

### ISSUE THREAD

**Issue by mbrkusanin** [llvm/llvm-project#79293]
/cherry-pick 7fdf608cefa0d9051eb3146ee19c3750e237c799

This feature took a bit longer then expected in review, so it was not merged in time.
Would it be possible to include it in llvm 18? It is one of the last pieces of AMDGPU GFX12 subtarget.

PR: https://github.com/llvm/llvm-project/pull/77795

**Comment by mbrkusanin** [comment]
In order to avoid conflict with https://github.com/llvm/llvm-project/commit/149ed9d2c58095f87745f8696ef96b5076c91fca it might be easier to port both, but we do not strictly need it.

**Comment by tstellar** [comment]
Merged: ed48280f8e9dd0fc2a21c3ee24c8db3fe12702f8
