### ISSUE TITLE
clang++ crash with -std=gnu++20 -O1

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#79350]
foundBugs $ /home/dcb38/llvm/results/bin/clang++ -c -w -std=gnu++20 bug2.cc
foundBugs $ /home/dcb38/llvm/results/bin/clang++ -c -w -std=gnu++20 -O1 bug2.cc
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
...
foundBugs $ /home/dcb38/llvm/results/bin/clang++ -v
clang version 18.0.0git (https://github.com/llvm/llvm-project.git bc82cfb38d83f1afeb2c290aa472c2e2e88919cb)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/dcb38/llvm/results/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/13
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/13
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
Found HIP installation: /usr/local, version 5.5.30202
foundBugs $

**Comment by EugeneZelenko** [comment]
@dcb314: Please provide reproducer.

**Comment by dcb314** [comment]
[bug2.cc.gz](https://github.com/llvm/llvm-project/files/14042797/bug2.cc.gz)

Sorry. I am new to this. Is the attached file what you want ?

**Comment by EugeneZelenko** [comment]
Attached file or link to https://godbolt.org.

**Comment by dcb314** [comment]
[bug2-a2b265.sh.gz](https://github.com/llvm/llvm-project/files/14043187/bug2-a2b265.sh.gz)

I think this attached file should be the reproducer.

**Comment by dcb314** [comment]
I've just done a build of clang, and it seems to be fixed in the latest version.
Git hash 3b8539c9dc0bc38ebea903e038257ed4328f290b.
