### ISSUE TITLE
[libc] Investigate the correct value for `MB_LEN_MAX` in `limits.h` header

### ISSUE THREAD

**Issue by lntue** [llvm/llvm-project#79358]
clang: MB_LEN_MAX = 1 - https://github.com/llvm/llvm-project/blob/main/clang/lib/Headers/limits.h#L64
glibc: MB_LEN_MAX = 16 - https://github.com/bminor/glibc/blob/master/include/limits.h#L32
musl: MB_LEN_MAX = 4 - https://git.musl-libc.org/cgit/musl/tree/include/limits.h#n35

**Comment by jhuber6** [comment]
The docs say it's the maximum number of bytes for a wide character accross all locales. Given that we will only support the default locale, I think that's just `4` like Musl?
