### ISSUE TITLE
Problems with release issue workflow

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#79362]
Quoting from https://github.com/llvm/llvm-project/pull/79310 to keep track of these:

> The one remaining problem now is that apparently comments posted by the github-actions bot don't trigger new actions, so the /branch comment gets ignored if it's posted by the cherry-pick workflow. Ideally we would just directly create the pull request in the cherry-pick workflow -- I don't think there's a good reason to have the intermediate /branch comment at all.

And:

> Another issue is that we get duplicate command executions if cherry-pick is part of the issue description and an issue subscriber comment gets posted. We can add `<!--IGNORE-->` to the start of the subscriber comments to avoid this.

**Comment by tstellar** [comment]
The reason we had the branch command was so that if we needed to resolve a conflict locally we could create the pull request off of a branch rather than a cherry-pick.  Maybe since users can create a pull request directly now, we don't need this?

**Comment by nikic** [comment]
> The reason we had the branch command was so that if we needed to resolve a conflict locally we could create the pull request off of a branch rather than a cherry-pick. Maybe since users can create a pull request directly now, we don't need this?

Yes, I don't think we need the branch command anymore.

**Comment by nikic** [comment]
Another big issue I noticed is that the generated PRs are not compatible with squash merge:

 * If there are multiple cherry-picks in a PR, we would end up squashing all commits together. This is generally not desirable for cherry-picks.
 * The current PR title and description are dummies, and they are what would get picked for the commit message, unless you manually edit in the original.

We should enable the rebase merge option to allow merging these easily (as well as other cases where rebase is preferable).

Failing that, we at least need to improve the generated PR title/description, so at least single commit cases could be merged via UI. For multi commit cases, a release manager would be forced to manually merge the PR using the simultaneous force push method.

**Comment by tstellar** [comment]
The other problem with squash and merge is that the user who created the pull request is considered the commit author when it is merged.  So all the PRs created by our automation will create commits with `41898282+github-actions[bot]@users.noreply.github.com` or `llvmbot <llvmbot@llvm.org` as the author.

**Comment by nikic** [comment]
@tstellar Good point. In that case even better PR descriptions etc won't help. The only options I see that don't require manual merges for everything, is to enable the rebase option on github, or to implement our own (`/rebase-merge` command or so).

**Comment by nikic** [comment]
It looks like using "github-actions bot" also fails to trigger most PR workflow. E.g. https://github.com/llvm/llvm-project/pull/79548 only has the buildkite job, while my manual PR at https://github.com/llvm/llvm-project/pull/79560 runs all the usual jobs (not sure if we want all of them, but probably at least some...)

So I guess at least the PR needs to be opened by llvmbot.

**Comment by nikic** [comment]
Issues have long since been resolved, closing.
