### ISSUE TITLE
[TableGen] `TableGen/address-space-patfrags.td ` failed when `LLVM_REVERSE_ITERATION=On`

### ISSUE THREAD

**Issue by wangpc-pp** [llvm/llvm-project#79420]
This is reported by @ilovepi in https://github.com/llvm/llvm-project/pull/77763.

**Comment by nikic** [comment]
Manually opened PR at https://github.com/llvm/llvm-project/pull/79595.

**Comment by tstellar** [comment]
Merged: 62877e375c8e18371a86218b5d7c4d8d242b05e1
