### ISSUE TITLE
[RISCV] Backport TableGen-based  macro fusion changes

### ISSUE THREAD

**Issue by wangpc-pp** [llvm/llvm-project#79425]
/cherry-pick 664a0faac464708fc061d12e5cd492fcbfea979a 3fdb431b636975f2062b1931158aa4dfce6a3ff1

Backport these changes into LLVM 18 so that we will have a released baseline that supports TableGen-based macro fusion.

**Comment by nikic** [comment]
PR manually opened at https://github.com/llvm/llvm-project/pull/79560.

**Comment by tstellar** [comment]
Merged: d9e26c223bdb124e1e83b73d87d7a545925fda90 7cfa0c1b7c82135ee5de1555c72d9629e5556c69
