### ISSUE TITLE
Should Milestones be like `LLVM 18.1.X Release` now?

### ISSUE THREAD

**Issue by wangpc-pp** [llvm/llvm-project#79426]
We have changed the scheme of version number:
* https://discourse.llvm.org/t/rfc-name-the-first-release-from-a-branch-n-1-0-instead-of-n-0-0/75384
* https://discourse.llvm.org/t/llvm-18-release-schedule/76175

**Comment by tstellar** [comment]
I've changed the milestone name to `LLVM 18.X Release`.

**Comment by nikic** [comment]
Note that when changing the milestone name, it's also necessary to update the workflow in https://github.com/orgs/llvm/projects/3/workflows/8740058. I've done that now.

(By the way, do we also want to add PRs with the milestone to the project? Currently we only add issues.)

**Comment by tstellar** [comment]
> (By the way, do we also want to add PRs with the milestone to the project? Currently we only add issues.)

Yes, we do.
