### ISSUE TITLE
Backport 70fc9703788e8965813c5b677a85cb84b66671b6 to release/18.x

### ISSUE THREAD

**Issue by jayfoad** [llvm/llvm-project#79451]
This is #79120, a prerequisite of #79325, which is one of very few remaining pieces required to get functional AMDGPU GFX12 support in the 18.x release.

**Comment by nikic** [comment]
@jayfoad See https://github.com/llvm/llvm-project/issues/79362. The branch command posted by the github-actions bot currently gets ignored.

**Comment by tstellar** [comment]
Merged: 27654471cc7acfca733c104e2ec24f882cfc6132
