### ISSUE TITLE
Merge lld/ELF's RISC-V TLSDESC into release/18.x

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#79507]
Ensure that linker support (https://github.com/llvm/llvm-project/pull/79239) is in place before more vendors enable TLSDESC for RISC-V.

/cherry-pick ccb99f221422b8de5e1ae04d3427f15878f7cd93 849951f8759171cb6c74d3ccbcf154506fc1f0ae 1117fdd7c16873eb389e988c6a39ad922bae0fd0

@ilovepi

**Comment by tstellar** [comment]
Merged: e2521eaa1aac43b3216378d529096f08ac98cf14 3d02473ac538f542fb76c4aff0fb6504398c3f15 e9d99e51834e2bf0b39c23a60f2dba5539edd17b
