### ISSUE TITLE
`-Wunused` fails to realize copy initialization might have side effects

### ISSUE THREAD

**Issue by cor3ntin** [llvm/llvm-project#79518]
Compiling with `-Wunused-variable`, we expect no warning to be emitted (constructor calls might have side effects), yet a warning is emitted for `s2`

```cpp
struct S {
    S(int);
};

int main() {
    S s(0); // no warning
    S s2 = 0; // unused
    S s3{0}; // no warning
}
```

https://godbolt.org/z/6zzfE9c4a

**Comment by shafik** [comment]
I believe this line:

https://github.com/llvm/llvm-project/blob/3c9f34c12450345c6eb524e47cf79664271e4260/clang/lib/Sema/SemaDecl.cpp#L2096

should be:

```cpp
const auto *Construct = dyn_cast<CXXConstructExpr>(Init->IgnoreImpCasts());
```

**Comment by AMS21** [comment]
Sounds interesting. Will take a look :)

**Comment by R-yannn** [comment]
Hi, 
I am new to LLVM and would like to contribute. 
can someone assign this issue to me?

**Comment by EugeneZelenko** [comment]
@R-yannn: Just create pull request and mention it on this page.

**Comment by vinayakdsci** [comment]
Hello, I have been able to solve this issue, but it seems that the tests in warn-unused-variables.cpp have been written for older than C++-20 standards. Consequently, while they pass for -std=c++20, they are failing for all other standards.

How should I fix that?

Thanks!

**Comment by Endilll** [comment]
Related: GCC still diagnoses examples above with `-Wunused-but-set-variable`. 
We don't: https://godbolt.org/z/crzY9YEd5

**Comment by vinayakdsci** [comment]
So should I add a commit to enforce this behavior too?

**Comment by cor3ntin** [comment]
> So should I add a commit to enforce this behavior too?

No, both compilers have the same bug, funnily enough https://godbolt.org/z/1sYKcKxrT

**Comment by vinayakdsci** [comment]
So the correct behavior is that neither -Wunused-variable and -Wunused-but-set-variable should emit warning in this case?
The PR fixes that, then!

Thanks!
