### ISSUE TITLE
LLVM ERROR: Broken module found, compilation aborted!

### ISSUE THREAD

**Issue by xqjcool1** [llvm/llvm-project#79537]
inlinable function call in a function with debug info must have a !dbg location
  call void @__tsan_read8(i8* %11)
LLVM ERROR: Broken module found, compilation aborted!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ld.lld -m elf_x86_64 -mllvm -import-instr-limit=5 -z noexecstack -r -o vmlinux.o -T .tmp_initcalls.lds --whole-archive vmlinux.a --no-whole-archive --start-group --end-group
 #0 0x0000562a0e03fc60 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x0000562a0e03d52e SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f640abf2fd0 (/lib/x86_64-linux-gnu/libc.so.6+0x3bfd0)
 #3 0x00007f640ac41d3c (/lib/x86_64-linux-gnu/libc.so.6+0x8ad3c)
 #4 0x00007f640abf2f32 raise (/lib/x86_64-linux-gnu/libc.so.6+0x3bf32)
 #5 0x00007f640abdd472 abort (/lib/x86_64-linux-gnu/libc.so.6+0x26472)
 #6 0x0000562a0dfccc79 llvm::report_fatal_error(llvm::Twine const&, bool) (/fwebdev4/bin/lld+0x5a3c79)
 #7 0x0000562a0dfccdb8 (/fwebdev4/bin/lld+0x5a3db8)
 #8 0x0000562a10391558 (/fwebdev4/bin/lld+0x2968558)
 #9 0x0000562a0ec839b7 runNewPMPasses(llvm::lto::Config const&, llvm::Module&, llvm::TargetMachine*, unsigned int, bool, llvm::ModuleSummaryIndex*, llvm::ModuleSummaryIndex const*) LTOBackend.cpp:0:0
#10 0x0000562a0ec8695c llvm::lto::opt(llvm::lto::Config const&, llvm::TargetMachine*, unsigned int, llvm::Module&, bool, llvm::ModuleSummaryIndex*, llvm::ModuleSummaryIndex const*, std::vector<unsigned char, std::allocator<unsigned char> > const&) (/fwebdev4/bin/lld+0x125d95c)
#11 0x0000562a0ec87cee llvm::lto::backend(llvm::lto::Config const&, std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream> > > (unsigned int)>, unsigned int, llvm::Module&, llvm::ModuleSummaryIndex&) (/fwebdev4/bin/lld+0x125ecee)
#12 0x0000562a0ec7aebe llvm::lto::LTO::runRegularLTO(std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream> > > (unsigned int)>) (/fwebdev4/bin/lld+0x1251ebe)
#13 0x0000562a0ec7b545 llvm::lto::LTO::run(std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream> > > (unsigned int)>, std::function<llvm::Expected<std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream> > > (unsigned int)> > (unsigned int, llvm::StringRef)>) (/fwebdev4/bin/lld+0x1252545)
#14 0x0000562a0e1da174 lld::elf::BitcodeCompiler::compile() (/fwebdev4/bin/lld+0x7b1174)
#15 0x0000562a0e14c05f void lld::elf::LinkerDriver::compileBitcodeFiles<llvm::object::ELFType<(llvm::support::endianness)1, true> >(bool) (/fwebdev4/bin/lld+0x72305f)
#16 0x0000562a0e161d8f lld::elf::LinkerDriver::link(llvm::opt::InputArgList&) (/fwebdev4/bin/lld+0x738d8f)
#17 0x0000562a0e164940 lld::elf::LinkerDriver::linkerMain(llvm::ArrayRef<char const*>) (/fwebdev4/bin/lld+0x73b940)
#18 0x0000562a0e165539 lld::elf::link(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, bool, bool) (/fwebdev4/bin/lld+0x73c539)
#19 0x0000562a0dfb01cd lldMain(int, char const**, llvm::raw_ostream&, llvm::raw_ostream&, bool) lld.cpp:0:0
#20 0x0000562a0df38ecc main (/fwebdev4/bin/lld+0x50fecc)
#21 0x00007f640abde1ca (/lib/x86_64-linux-gnu/libc.so.6+0x271ca)
#22 0x00007f640abde285 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x27285)
#23 0x0000562a0dfaf31a _start (/fwebdev4/bin/lld+0x58631a)

**Comment by EugeneZelenko** [comment]
@xqjcool1: Could you please provide reproducer?

**Comment by nathanchance** [comment]
I suspect this issue is resolved with https://github.com/llvm/llvm-project/commit/47bdea3f7eb4bb70288e69635d73807c5d03dacc in LLVM 15.0.0.

**Comment by nikic** [comment]
Closing this as no reproducer or actionable information has been provided.
