### ISSUE TITLE
Merge "[llvm] [cmake] Include httplib in LLVMConfig.cmake" into release/18.x

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#79547]
/cherry-pick 3c9f34c12450345c6eb524e47cf79664271e4260

This fixes a standalone lldb build problem after #70996

@mgorny @thesamesam  @kevinfrei

**Comment by tstellar** [comment]
Merged: 2c3214135ffa8e3f9ab61d12521637532126f368
