### ISSUE TITLE
Add support for distributed ThinLTO options to `wasm-ld` driver

### ISSUE THREAD

**Issue by trybka** [llvm/llvm-project#79604]
The Wasm Driver for LLD seems to be missing options related to distributed ThinLTO.

https://gist.github.com/MaskRay/24f4e2eed208b9d8b0a3752575a665d4#distributed-thinlto may be a good reference.

We are looking to add ThinLTO support to Bazel / Emscripten. `wasm-ld` appears to be missing flags related specifically to _distributed_ ThinLTO. These flags appear to be used for e.g. mapping index files to objects. 

See https://reviews.llvm.org/D46034 for an example of some options added to the ELF driver.

Similarly, https://reviews.llvm.org/D64461 and https://reviews.llvm.org/D64542 have implementations for COFF.

The set of flags that we expect are:

```
--thinlto-index-only=
--thinlto-emit-imports-files
--thinlto-prefix-replace=
```
Also missing but not sure if related:
```
--obj-path=
```

+cc: @sbc100 @walkingeyerobot @googlewalt

**Comment by sbc100** [comment]
Seems like a reasonable request to me.   That flags, and their implementation will likely match exactly the ELF linker.

The hard part will likely be writing the tests (or porting the ELF tests) for each flag.

**Comment by sbc100** [comment]
@walkingeyerobot @trybka this has now be fixed and will be part of the next emscripten release 3.1.73
