### ISSUE TITLE
clang/lib/Format/WhitespaceManager.cpp:1472: Sanity check after use ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#79685]
Static analyser cppcheck says:

clang/lib/Format/WhitespaceManager.cpp:1472:23: style: Array index 'j' is used before limits check. [arrayIndexThenCheck]

Source code is

       while (Changes[j].Tok != NextNonComment && j < End)

Sanity check before use would be more usual.

**Comment by dcb314** [comment]
I thought this looked familiar. On checking my records, I notice I have reported
this one in the past and nothing got done.

So it looks like a waste of time to report it again. Sorry.

**Comment by owenca** [comment]
Duplicate of #69047.
