### ISSUE TITLE
[clang] Cannot use private templated static member function inside templated using alias with decltype

### ISSUE THREAD

**Issue by christiandaley** [llvm/llvm-project#79682]
https://godbolt.org/z/7hP3dqE5e

gcc and msvc both compile this code. Removing the template from the function f allows the code to compile with clang.

**Comment by cor3ntin** [comment]
@Endilll didn't you look at something similar recently?

**Comment by ilya-biryukov** [comment]
This works in trunk, but not in Clang 18, see https://godbolt.org/z/MYhq46rjE
