### ISSUE TITLE
clang/lib/Sema/SemaChecking.cpp: 4 * Redundant conditions ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#79686]
Static analyser cppcheck says:

trunk/clang/lib/Sema/SemaChecking.cpp:17188:35: style: Redundant condition: EvalOK. '!EvalOK || (EvalOK && !EvalResult)' is equivalent to '!EvalOK || !EvalResult' [redundantCondition]
trunk/clang/lib/Sema/SemaChecking.cpp:17272:41: style: Redundant condition: EvalOK. '!EvalOK || (EvalOK && !EvalResult)' is equivalent to '!EvalOK || !EvalResult' [redundantCondition]
trunk/clang/lib/Sema/SemaChecking.cpp:17220:35: style: Redundant condition: EvalOK. '!EvalOK || (EvalOK && EvalResult)' is equivalent to '!EvalOK || EvalResult' [redundantCondition]
trunk/clang/lib/Sema/SemaChecking.cpp:17271:40: style: Redundant condition: EvalOK. '!EvalOK || (EvalOK && EvalResult)' is equivalent to '!EvalOK || EvalResult' [redundantCondition]

Source code for the first one is:

    bool ShouldVisitRHS = !EvalOK || (EvalOK && !EvalResult);

**Comment by Rageking8** [comment]
I would like to take this issue.
