### ISSUE TITLE
compiler-rt/lib/profile/InstrProfilingFile.c:680:7: error: Resource leak

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#79708]
Source code is

    if (CurrentFileOffset % PageSize != 0) {
      PROF_ERR("Continuous counter sync mode is enabled, but raw profile is not"
               "page-aligned. CurrentFileOffset = %" PRIu64 ", pagesz = %u.\n",
               (uint64_t)CurrentFileOffset, PageSize);
      return;
    }
    if (writeProfileWithFileObject(Filename, File) != 0) {
      fclose(File);
      return;
    }

If it's worth calling fclose in the second if, then it is worthwhile in the first.

**Comment by devnexen** [comment]
Thanks @dcb314 for reporting
