### ISSUE TITLE
[AArch64] Error when assembling call to function named `ror`

### ISSUE THREAD

**Issue by zyedidia** [llvm/llvm-project#79729]
The following AArch64 assembly file fails to compile with Clang even though it is valid:

```
ror:
    ret

foo:
    bl ror
```

```
$ clang -c test.s
test.s:5:11: error: expected #imm after shift specifier
    bl ror
          ^
$ gcc -c test.s
$ # no error
```

`ror` or any other aarch64 shift operation should be a valid function/label name. Tested with the latest version of LLVM.

**Comment by pinskia** [comment]
You can also reproduce it with a C testcase with just `-c -save-temps` too:
```
int ror(void);
int f()
{
        return ror();
}
```
