### ISSUE TITLE
[InstCombine] Loss of `addrspace` attribute when canonicalizing `getelementptr` instruction

### ISSUE THREAD

**Issue by Nirhar** [llvm/llvm-project#79735]
Hi @nikic !

I see that you landed a patch ([Link](https://github.com/llvm/llvm-project/commit/90ba33099cbb17e7c159e9ebc5a512037db99d6d)) that standardizes the source pointer type of Geps to i8 type. However I noticed that instructions of the type:
```
%gep = getelementptr ptr addrspace(1), ptr %ptr, i64 42
```
get modifiied to 
```
%gep = getelementptr i8, ptr %ptr, i64 42
```

thereby losing the addrspace(1) attribute. Is this the intended behaviour of this patch(which I believe should not be)?

**Comment by nikic** [comment]
getelementptr does not have an addrspace attribute. `ptr addrspace(1)` is just the source element type here, which is only used to determine the stride of the GEP. In your example, it looks like `ptr addrspace(1)` is defined to have size 1.
