### ISSUE TITLE
`#include <iostream>` makes it impossible to use `pipe` as a variable name

### ISSUE THREAD

**Issue by hewillk** [llvm/llvm-project#79782]
```cpp
#include <iostream>

int pipe;
```
https://godbolt.org/z/fqPhTzq1E
The latest libc++ rejects the above code with:

> ```
> <source>:3:5: error: redefinition of 'pipe' as different kind of symbol
>     3 | int pipe;
>       |     ^
> /usr/include/unistd.h:437:12: note: previous definition is here
>   437 | extern int pipe (int __pipedes[2]) __THROW __wur;
>       |            ^
> 1 error generated.
> ```
Note that Clang-17's libc++, libc++, and MSVC-STL accept it.

**Comment by frederick-vs-ja** [comment]
> Mainly curious where did you spot this? The issue is due to including `unistd.h` which is needed for `isatty`. I'm surprised it's not an issue for libstdc++, I'm sure they use `isatty` too (https://cplusplus.github.io/LWG/issue4044).

libstd++ only includes `<unistd.h>` in a separately compiled source file in order to avoid name conflict.
https://github.com/gcc-mirror/gcc/blob/f22a7ae8a96f7e5e330b12bd5045424619aa4926/libstdc%2B%2B-v3/src/c%2B%2B23/print.cc

**Comment by hewillk** [comment]
> Mainly curious where did you spot this?
I had a small piece of code that defined a namespace named `pipe`, and then suddenly found that it could not be compiled in clang-trunk.

**Comment by mordante** [comment]
Thanks for the info. I'm testing a patch now once approved I'll request to cherry-pick it to the LLVM-18 release branch.
