### ISSUE TITLE
[libc++][test] `array/size_and_alignment.compile.pass.cpp` includes non-Standard `<__type_traits/datasizeof.h>`

### ISSUE THREAD

**Issue by StephanTLavavej** [llvm/llvm-project#79783]
Found while using MSVC's STL with libc++'s test suite.

This `libcxx/test/std/` test should be portable, but it's including a non-Standard header:

https://github.com/llvm/llvm-project/blob/86b3f8518f21532297e0aad0c6aea95c66389fc9/libcxx/test/std/containers/sequences/array/size_and_alignment.compile.pass.cpp#L25

I'm not sure if this test should be changed to be portable, or moved to the implementation-specific `libcxx/test/libcxx/` given this comment:

https://github.com/llvm/llvm-project/blob/86b3f8518f21532297e0aad0c6aea95c66389fc9/libcxx/test/std/containers/sequences/array/size_and_alignment.compile.pass.cpp#L14-L15

**Comment by frederick-vs-ja** [comment]
IIUC this file is testing non-portable implementation details. But I think most tested properties are expected to be provided by all implementations.
