### ISSUE TITLE
[LoopVectorize] Refine runtime memory check costs when there is an outer loop

### ISSUE THREAD

**Issue by david-arm** [llvm/llvm-project#79800]
We would like to backport https://github.com/llvm/llvm-project/pull/76034 to fix a major performance regression when using PGO to build certain applications/benchmarks. Specifically, it fixes a 25% regression in the SPEC2017 x264 benchmark.

**Comment by tstellar** [comment]
Merged: bdaf16d59f4a64529371cbe056245f6cc035d7cf
