### ISSUE TITLE
clang-tidy check cppcoreguidelines-special-member-functions falsely demands all members when only destructor virtual and default

### ISSUE THREAD

**Issue by FalcoGer** [llvm/llvm-project#79826]
[C21 of CppCoreGuidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-five) states in the first good example, that it is acceptable to define a destructor as defaulted and not any other member function, if the only purpose is to make it virtual.

> Example, good
> When a destructor needs to be declared just to make it virtual, it can be defined as defaulted.

However clang-tidy marks the example provided as missing special member functions.

```c++
class AbstractBase {
//    ^~~~~~~~~~~~
//    Class 'AbstractBase' defines a default destructor but does not define a copy constructor,
//    a copy assignment operator, a move constructor or a move assignment operator
//    (clang-tidy cppcoreguidelines-special-member-functions)

public:
    virtual void Foo() = 0;  // at least one abstract method to make the class abstract
    virtual ~AbstractBase() = default;
    // ...
};
```

The warning should be emitted only if the destructor is not defaulted and virtual or if another special member that is not a constructor is declared.

**Comment by PiotrZSL** [comment]
```
Enforcement (Simple) A class should have a declaration (even a =delete one) for either all or none of the copy/move/destructor functions.
```

Check got `AllowSoleDefaultDtor` option to control this behaviour.
