### ISSUE TITLE
Please backport '[sanitizer] Handle Gentoo's libstdc++ path' (e8f882f83acf30d9b4da8846bd26314139660430) to 18.x

### ISSUE THREAD

**Issue by thesamesam** [llvm/llvm-project#79838]
Please backport '[sanitizer] Handle Gentoo's libstdc++ path' (e8f882f83acf30d9b4da8846bd26314139660430) to 18.x.

It's a small sanitizer runtime + test fix for Gentoo.

**Comment by tstellar** [comment]
@vitalybuka What do you think about backporting this?

**Comment by vitalybuka** [comment]
> @vitalybuka What do you think about backporting this?

LGTM.
Should be safe.

**Comment by thesamesam** [comment]
Done.
