### ISSUE TITLE
[clang-format] No space between between `)` and `{` at constructor/destructor when there is a semicolon at the end.

### ISSUE THREAD

**Issue by CDAlexanderW** [llvm/llvm-project#79834]
### Environment
The tested v18 clang-format executable was built from latest source of 15.01.2024.

Setting in `.clang-format` is:
```
Language: Cpp
```

### Problem
No space between between `)` and `{` at constructor/destructor when there is a semicolon at the end. A member function seems to work by adding the space, due to the fix #72733 in version 18.
```
class A {
  A(){};
  void b() {};
};
```
When adding something (in that case `int i;`) into the implementation, it seems to work for the constructor:
```
class A {
  ~A() { int i; };
  void s() { int i; };
};
```
It looks like #58251 mentions clang-format "cannot determine {} as an empty function".

For our case maybe a fix of #79833 would also workaround this in case you automatically let the semicolons removed. I don't know if they are related in some way, so I tried to split them into separate issues.

**Comment by j2kun** [comment]
Would it be possible to get this cherry-picked into the next patch release of llvm-18? It doesn't appear to have made it into llvm-18.1.2, even though the commit was merged before it was released.

**Comment by owenca** [comment]
I've added #82097 to the LLVM 18 Release milestone.

**Comment by j2kun** [comment]
Thank you!
