### ISSUE TITLE
[BOLT] Deleted some specific instructions within the function, but the size of the function remains unchanged

### ISSUE THREAD

**Issue by killerloura** [llvm/llvm-project#79857]
I added a codesize optimization in bolt, which removed some instructions. I expected it to optimize code size, but it didn't work. It seems like the function is being refilled with some unused data.
The function called by "call" is generated by my optimization pass using `createInjectedBinaryFunction` .

<img width="761" alt="image" src="https://github.com/llvm/llvm-project/assets/81171521/531b8a7e-73a8-4311-82a8-dc051bcf9c0d">

 Interestingly, it worked when I replaced a "call" with "nop".

![](https://global.discourse-cdn.com/business4/uploads/llvm/original/3X/a/2/a2805f60c69a176ee69c393d97fddb81a4587afc.png)

 There is source code.

![image](https://github.com/llvm/llvm-project/assets/81171521/98899bf0-9ab6-48ef-b253-d0522cc32d94)

It appears that the address of <__libc_csu_init> are exactly the same as in the source code.

**Comment by EugeneZelenko** [comment]
@killerloura: Could you please elaborate?

**Comment by killerloura** [comment]
Sorry, there were some problem with the image insertion earlier. Do you understand what I mean now? Is there anything else I need to add

**Comment by maksfb** [comment]
In the first picture, these are alignment nops starting at 0x800120. How are you invoking BOLT? It can rewrite code in-place or place it into a new segment.

**Comment by killerloura** [comment]
@maksfb When I run BOLT, I only use the -o option, as in the command bolt xxx.out -o xxx-bolt.out.

By the way, there is source code.

<img width="694" alt="image" src="https://github.com/llvm/llvm-project/assets/81171521/f5e5ab62-44fa-4a80-b4d9-fd12bd4b6532">


It appears that the address of <__libc_csu_init> are exactly the same as in the source code.

**Comment by maksfb** [comment]
By default, we try to align functions at the cache line boundary and use up to 32 bytes for this. You can control this behavior with `--align-functions` and `--align-functions-max-bytes` options. E.g., try `--align-functions=2`.

**Comment by killerloura** [comment]
@maksfb Thank you! It works !!
