### ISSUE TITLE
clang/lib/Frontend/TextDiagnostic.cpp:1254: suspicious loop ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#79964]
Static analyser cppcheck says:

clang/lib/Frontend/TextDiagnostic.cpp:1254:40: error: When I==Spelling.size(), Spelling[I] is out of bounds. [stlOutOfBounds]

Source code is

    for (unsigned I = 0; I <= Spelling.size(); ++I) {
      // This line is done.
      if (isVerticalWhitespace(Spelling[I]) || I == Spelling.size()) {

The for loop line looks like it executes once too many times. Maybe better code

    for (unsigned I = 0; I < Spelling.size(); ++I) {

**Comment by tbaederr** [comment]
I think the operands to the `||` in

```c++
  if (isVerticalWhitespace(Spelling[I]) || I == Spelling.size())
```
should be switched instead.
