### ISSUE TITLE
[schedule] issue the load instructions in more higher priority

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#79987]
* test: https://gcc.godbolt.org/z/f858x63zc
```
void foo1(dComplex* __restrict__ bb, bool flag) {
    aa->real = bb->real; aa->imag = bb->imag;
    if (flag) 
    {
        *aa = aa->conj();
    }
}
```

* llvm: the real part of bb (**bb->real**) is always loaded, so expect the **ldr     d1, [x0]** can be issue more early because **the load instruction has a large latency**, especially cache miss, in generally.
```
foo1(dComplex*, bool):                     // @foo1(dComplex*, bool)
        ldr     d0, [x0, #8]
        tst     w1, #0x1
        adrp    x8, aa
        ldr     x8, [x8, :lo12:aa]
        fneg    d1, d0
        fcsel   d0, d1, d0, ne
        ldr     d1, [x0]              -- Used immediately after the load bb->real
        stp     d1, d0, [x8]
        ret
```

**Comment by vfdff** [comment]
* a small reduced case: https://gcc.godbolt.org/z/YTcWcrWez

**Comment by harviniriawan** [comment]
looping @davemgreen for this

**Comment by davemgreen** [comment]
Thanks - It looks like a mixture of the A510 scheduling model having lower latencies on loads (the scheduling models always use a optimistic L1 cache-hit latency), the critical path causing the scheduling of the load after the fcsel, the register allocator assigning the same register and so finally the load-store optimizer cannot combine the two loads into a ldp.

In looking at the software optimization guides, the latency of a FCSEL is slightly higher than it should be. I can write a quick patch for that in the morning which seems to at least help the simple case.

**Comment by vfdff** [comment]
Thanks @davemgreen , I check that https://github.com/llvm/llvm-project/pull/80178 fixes this issue

**Comment by davemgreen** [comment]
Nice, that for checking. I hadn't tested all case.
