### ISSUE TITLE
libc/src/stdio/scanf_core/float_converter.cpp: 2 * sanity check in wrong place ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#79988]
Static analyser cppcheck says

1.

libc/src/stdio/scanf_core/float_converter.cpp:60:44: style: Array index 'inf_index' is used before limits check. [arrayIndexThenCheck]

Source code is

    for (; to_lower(cur_char) == inf_string[inf_index] &&
           inf_index < sizeof(inf_string) && out_str.length() < max_width;
         ++inf_index) {

Suggest move sanity check to before use.

2.

ibc/src/stdio/scanf_core/float_converter.cpp:83:44: style: Array index 'nan_index' is used before limits check. [arrayIndexThenCheck]

Duplicate.

**Comment by michaelrj-google** [comment]
Thanks for finding this and filing an issue, I've created a patch to fix it: https://github.com/llvm/llvm-project/pull/80083.
