### ISSUE TITLE
Backport "Fix analyzer crash on 'StructuralValue'"

### ISSUE THREAD

**Issue by steakhal** [llvm/llvm-project#79992]
This patch fixes 2 crashes (null-pointer dereferences), that are now hit after #78041.
Those crashes are tracked in issue #79575, and fix was already committed to llvm/main as ef67f63fa5f950f4056b5783e92e137342805d74.

**Comment by bolshakov-a** [comment]
Thank you!

**Comment by steakhal** [comment]
The fix was merged to release/18.x as https://github.com/llvm/llvm-project/commit/0eb163cc2717b99f83aa4304628b19291f9ffe53
