### ISSUE TITLE
`static const` variable in Clang header causes multiple definition error

### ISSUE THREAD

**Issue by disog** [llvm/llvm-project#80043]
This [line](https://github.com/llvm/llvm-project/blob/69cb99f9cb2e8757ad2c09b87fc96d5bff73c490/clang/include/clang/AST/DeclTemplate.h#L1715) is causing multiple definition of `clang::TemplateTemplateParmDecl::getDefaultArgument() const::NoneLoc` when compiling with GCC 13.2.0.

**Comment by shafik** [comment]
As far I can tell this is not an ODR violation: https://eel.is/c++draft/dcl.inline#6

> Note 3: An inline function or variable with external or module linkage can be defined in multiple translation units ([basic.def.odr]), but is one entity with one address. A type or static variable defined in the body of such a function is therefore a single entity. — end note

So I believe gcc is not correct here.

**Comment by erichkeane** [comment]
> As far I can tell this is not an ODR violation: https://eel.is/c++draft/dcl.inline#6
> 
> > Note 3: An inline function or variable with external or module linkage can be defined in multiple translation units ([basic.def.odr]), but is one entity with one address. A type or static variable defined in the body of such a function is therefore a single entity. — end note
> 
> So I believe gcc is not correct here.

I've been unable to create a minimal repro in any way.  The version on Godbolt of 13.2 seems to not reproduce this.  @disog : can you provide more details on what you did to discover this/reproduce this?  Are there buildbots you've seen this on, or just locally?

If the latter, can you provide --version dumps (or equivalent) for your whole toolchain?

**Comment by pinskia** [comment]
I also tried to reproduce this with GCC trunk:
t.h:
```
struct s
{
  const int &a() const {
    static const int b = 1;
    return b;
  }
};

int f(const int &);
```
t.cc:
```
#include "t.h"

int main()
{
  s a;
  f(a.a());
}
```
t1.cc:
```
#include "t.h"

int f(const int &b)
{
  s a;
  return a.a() + b;
}
```

And I don't get multiple definition error. With `-fno-weak`, GCC gives a warning too.
I can only think this is non-elf based GCC where weak/comdat implemention is not working correctly.

**Comment by disog** [comment]
Thanks for your quick feedback, and I'm sorry for not giving enough context. What I'm trying to do is develop a Clang plugin.

On Linux I was able to compile and link my plugin against the clang-cpp shared library. On Windows, I have a rather peculiar environment: MSYS2 + UCRT64 + GCC.

In the latter case, linking against the shared library (plus LLVMSupport) is ok. But linking with the Clang static libraries (clangFrontend) gives this error.

In both cases, I'm using CMake to find the libraries and include directories.

I'll see if I can devise a small reproducible test.

**Comment by pinskia** [comment]
GCC targetting mingw (PE/coff) definitely has issues especially when it comes to vague linkage (comdat) and most folks who work on the mingw port are just volunteers and NOT get paid to work on it. So if you find an issue please report it to https://gcc.gnu.org/bugs/ but note it might not get fixed any time soon.

**Comment by disog** [comment]
I'm closing this issue, since it must be on the GCC side and I can't reproduce with a small enough sample.

For the record, here is the compilation log:
```
C:\WINDOWS\system32\cmd.exe /C "cd . && C:\tools\msys64\ucrt64\bin\g++.exe -O3 -DNDEBUG   -shared -o <redacted>.dll -Wl,--major-image-version,0,--minor-image-version,0 CMakeFiles/<redacted>.dir/src/<redacted>.cpp.obj  C:/tools/msys64/ucrt64/lib/libclangFrontend.a  C:/tools/msys64/ucrt64/lib/libclangDriver.a  -lversion  C:/tools/msys64/ucrt64/lib/libclangParse.a  C:/tools/msys64/ucrt64/lib/libclangSerialization.a  C:/tools/msys64/ucrt64/lib/libclangSema.a  C:/tools/msys64/ucrt64/lib/libclangEdit.a  C:/tools/msys64/ucrt64/lib/libclangAnalysis.a  C:/tools/msys64/ucrt64/lib/libclangASTMatchers.a  C:/tools/msys64/ucrt64/lib/libclangAST.a  C:/tools/msys64/ucrt64/lib/libclangLex.a  C:/tools/msys64/ucrt64/lib/libclangBasic.a  C:/tools/msys64/ucrt64/lib/libclangSupport.a  C:/tools/msys64/ucrt64/lib/libLLVM-17.dll.a  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/tools/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tools/msys64/ucrt64/lib/libclangFrontend.a(ASTConsumers.cpp.obj):(.bss$_ZZNK5clang24TemplateTemplateParmDecl18getDefaultArgumentEvE7NoneLoc[_ZZNK5clang24TemplateTemplateParmDecl18getDefaultArgumentEvE7NoneLoc]+0x0): multiple definition of `clang::TemplateTemplateParmDecl::getDefaultArgument() const::NoneLoc'; CMakeFiles/<redacted>.dir/src/<redacted>.cpp.obj:<redacted>.cpp:(.data$_ZZNK5clang24TemplateTemplateParmDecl18getDefaultArgumentEvE7NoneLoc[_ZZNK5clang24TemplateTemplateParmDecl18getDefaultArgumentEvE7NoneLoc]+0x0): first defined here
C:/tools/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tools/msys64/ucrt64/lib/libclangFrontend.a(ASTConsumers.cpp.obj):(.bss$_ZGVZNK5clang24TemplateTemplateParmDecl18getDefaultArgumentEvE7NoneLoc[_ZGVZNK5clang24TemplateTemplateParmDecl18getDefaultArgumentEvE7NoneLoc]+0x0): multiple definition of `guard variable for clang::TemplateTemplateParmDecl::getDefaultArgument() const::NoneLoc'; CMakeFiles/<redacted>.dir/src/<redacted>.cpp.obj:<redacted>.cpp:(.data$_ZGVZNK5clang24TemplateTemplateParmDecl18getDefaultArgumentEvE7NoneLoc[_ZGVZNK5clang24TemplateTemplateParmDecl18getDefaultArgumentEvE7NoneLoc]+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
