### ISSUE TITLE
[HLSL] Implement clang_elementwise_builtin_alias

### ISSUE THREAD

**Issue by bob80905** [llvm/llvm-project#80048]
There is an RFC on the llvm discussion board here that discusses implementing an elementwise alias:
https://discourse.llvm.org/t/rfc-elementwise-attribute-in-clang-front-end/76342/14
This alias will enable a user to define functions arbitrarily, and create an alias for an elementwise version of the function, and output a vector of outputs.
The purpose is to get around the llvm community's hesitation to implement the tan intrinsic. This alias can allow users to define tan on their own terms, and then users can use elementwise versions of tan in their code. It will also set the stage for easy substitution whenever the llvm community agrees on how to lower tan (whether that be creating an intrinsic, or using libcalls).

Blocks:
* tan
* atan
* cos
* acos
* ...

AC: 
* When an hlsl developer is able to use this alias to create any arbitrary function, and give the function a vector of inputs, and the function produces a correct vector of outputs, the alias has been implemented correctly.
* Existing HLSL library functions in hlsl.h have been updated to use the new attribute

**Comment by bogner** [comment]
As I [commented on #86175](https://github.com/llvm/llvm-project/pull/86175#issuecomment-2025933904) I think from the experiments we've run we aren't gaining enough from doing this to justify the complexity. We should consider this closed and move on.
