### ISSUE TITLE
Backport '[clang] static operators should evaluate object argument (reland)' to release/18.x

### ISSUE THREAD

**Issue by SuperSodaSea** [llvm/llvm-project#80041]
Please backport '[clang] static operators should evaluate object argument' ~~(#68485, 30155fc0ef4fbdce2d79434aaae8d58b2fabb20a)~~ (#80108, ee01a2c3996f9647f3158f5acdb921a6ede94dc1) to 18.x.

CC @cor3ntin, @AaronBallman

**Comment by SuperSodaSea** [comment]
Manual backport at #80109.

**Comment by tstellar** [comment]
PR has been created, we will track the status there.
