### ISSUE TITLE
[AIX] support builtin_cpu_support

### ISSUE THREAD

**Issue by diggerlin** [llvm/llvm-project#80042]
Lowering of intrinsic `__builtin_cpu_is` and `__builtin_cpu_support`  into AIX platform-specific code.

The runtime external variable `_system_configuration` in `/usr/include/sys/systemcfg.h` provides all
 the information needed for functions `__builtin_cpu_is()` and `__builtin_cpu_support()`.

**Comment by nemanjai** [comment]
It is not clear what the proposed code generation is. Is the plan to simply emit a reference to an external symbol that provides the information? If so, is there any safety if the binary is executed on a system that doesn't provide this definition in the library?

**Comment by diggerlin** [comment]
> If so, is there any safety if the binary is executed on a system that doesn't provide this definition in the library?

I got response from AIX kernel develop as 
 `_system_configuration` structure is placed in special memory which we call as low memory .. it is technically kernel memory, but user space programs are also allowed readonly access to that
  but this low memory is very premium .. now thsi sysconfig struct has reached to a such a size that no more low memory can be spared
  
  when we add new features not supported in  `_system_configuration`, we have to use  getsystemcfg() directly for new features
  
  `getsystemcfg()` is an exported API in libc.a, no need to install anything.  `libc.a` is there by default on any AIX OS
:thx:
1

**Comment by chenzheng1030** [comment]
Seems we are done for this issue? @diggerlin

**Comment by diggerlin** [comment]
yes, the PR 
[Implement a subset of builtin_cpu_supports() features](https://github.com/llvm/llvm-project/pull/82809#top)  is merged
