### ISSUE TITLE
Backport a couple of fixes for concepts to Clang 18

### ISSUE THREAD

**Issue by zyn0217** [llvm/llvm-project#80114]
/cherry-pick 6e6c506f3caeafc25925b811b9cd205e2e213dd6
/cherry-pick 04d20b17050203e07394b4f9ee61b5affe2d5347
/cherry-pick ab70ac605e784c630122b27c5971fde68e80bd1b

**Comment by zyn0217** [comment]
Sorry, I forget the backport workflow:

/cherry-pick https://github.com/llvm/llvm-project/commit/6e6c506f3caeafc25925b811b9cd205e2e213dd6
/cherry-pick https://github.com/llvm/llvm-project/commit/04d20b17050203e07394b4f9ee61b5affe2d5347
/cherry-pick https://github.com/llvm/llvm-project/commit/ab70ac605e784c630122b27c5971fde68e80bd1b

**Comment by zyn0217** [comment]
Sigh, I think I have to send three separate PRs now..

**Comment by h-vetinari** [comment]
> Sorry, I forget the backport workflow:

You [can](https://discourse.llvm.org/t/release-18-x-branch-has-been-created/76480/3?u=h-vetinari) now directly open a PR against `release/18.x`, with all three commits if you wan.
