### ISSUE TITLE
BUG: `openmp/cmake/HandleOpenMPOptions.cmake` uses CMake function `append` without defining it

### ISSUE THREAD

**Issue by h-vetinari** [llvm/llvm-project#80117]
While [building](https://github.com/conda-forge/openmp-feedstock/pull/113) openmp 18.1.0-rc1 on windows, I get:
```
CMake Error at cmake/HandleOpenMPOptions.cmake:47 (append):
  Unknown CMake command "append".
```

This is due to https://github.com/llvm/llvm-project/blame/release/18.x/openmp/cmake/HandleOpenMPOptions.cmake using `append` since https://github.com/llvm/llvm-project/commit/15fdc7646ca24506ccb6a59861da8f3b52ab031c, but not defining it -- in contrast to `append_if` which explicitly duplicates the definition from [`HandleLLVMOptions.cmake`](https://github.com/llvm/llvm-project/blob/release/18.x/llvm/cmake/modules/HandleLLVMOptions.cmake):
https://github.com/llvm/llvm-project/blob/400a02bb281ba0de79211ab53d931e44dd76733f/openmp/cmake/HandleOpenMPOptions.cmake#L1-L10

I don't know why this file does not (or cannot) do `include(HandleLLVMOptions)`, but if that's not an option, then it needs to similarly vendor the definition of `append`.

CC @aganea

**Comment by aganea** [comment]
Thanks for the report, I will take a look today.

**Comment by aganea** [comment]
Could you also please explain what cmake version are you using and the arguments used to build LLVM?

**Comment by h-vetinari** [comment]
> Could you also please explain what cmake version are you using and the arguments used to build LLVM?

We use the newest available CMake (3.28.2) and the main build invocation is:
```
cd clang
mkdir build
cd build

cmake -G "Ninja" ^
    -DCMAKE_BUILD_TYPE="Release" ^
    -DCMAKE_PREFIX_PATH=%LIBRARY_PREFIX% ^
    -DCMAKE_INSTALL_PREFIX:PATH=%LIBRARY_PREFIX% ^
    -DCLANG_FORCE_MATCHING_LIBCLANG_SOVERSION=OFF ^
    -DCLANG_INCLUDE_TESTS=OFF ^
    -DCLANG_INCLUDE_DOCS=OFF ^
    -DLLVM_INCLUDE_TESTS=OFF ^
    -DLLVM_INCLUDE_DOCS=OFF ^
    -DLLVM_ENABLE_LIBXML2=FORCE_ON ^
    -DLLVM_ENABLE_ZLIB=FORCE_ON ^
    -DLLVM_ENABLE_ZSTD=FORCE_ON ^
    -DPython3_EXECUTABLE=%BUILD_PREFIX%\python ^
    ..
```
The truth is slightly more [complicated](https://github.com/conda-forge/clangdev-feedstock/blob/main/recipe/bld.bat) (for various reasons incl. CI limitations, we build LLVM component-wise; originally that was done with the subproject tarballs, now we ensure that just `./clang` and `./cmake` are in the source directory). Most importantly, we build against an already-built llvm library that lives in `%LIBRARY_PREFIX%`.

**Comment by h-vetinari** [comment]
> Thanks for the report, I will take a look today.

Thank you for the quick response! 🙏

**Comment by jhuber6** [comment]
IIRC the reason we can't just `include(LLVM)` is because we somewhat support a standalone usage. I.e. you can just get `openmp` and build it through CMake if you have an LLVM installation somewhere on your system.

**Comment by h-vetinari** [comment]
> IIRC the reason we can't just `include(LLVM)` is because we somewhat support a standalone usage. I.e. you can just get `openmp` and build it through CMake if you have an LLVM installation somewhere on your system.

I mean, the waters have muddied on this substantially in recent years, c.f. [here](https://discourse.llvm.org/t/rfc-stand-alone-build-support/61291) and [here](https://discourse.llvm.org/t/building-llvm-out-of-per-subproject-tar-balls-still-is-not-working/72829). My understanding of the former is that using `/cmake` is allowed in `/openmp`, and not in conflict with the standalone builds. CC @tstellar as RFC author.

I _do_ care about building openmp "standalone", but I don't mind if I need to provide the corresponding CMake sources alongside (this has been the status quo for several other subprojects as well).

**Comment by shiltian** [comment]
Even so, host OpenMP still supports standalone build w/o LLVM. That's why we are pretty careful about adding dependencies for `libomp`. `libomptarget` is completely a LLVM library, which is beyond the scope here.

**Comment by aganea** [comment]
@h-vetinari Can you check please if https://github.com/llvm/llvm-project/pull/80174 fixes the issue?

**Comment by h-vetinari** [comment]
Thanks a lot @aganea! Tested the state of this patch on top of the `release/18.x` branch, and it works! 🙏

**Comment by tstellar** [comment]
PR has been created, we will track the status there.
