### ISSUE TITLE
bolt/lib/Target/X86/X86MCPlusBuilder.cpp:2200: Suspicious if condition ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#80111]
Static analyser cppcheck says:

bolt/lib/Target/X86/X86MCPlusBuilder.cpp:2200:48: style: Same expression 'MO->BaseRegNum!=X86::RIP' found multiple times in chain of '&&' operators. [duplicateExpression]

Source code is

          if (!MO->DispExpr && MO->ScaleImm == 1 &&
              MO->BaseRegNum != X86::RIP && MO->BaseRegNum != X86::RBP &&
              MO->BaseRegNum != X86::NoRegister &&
              MO->IndexRegNum == X86::NoRegister &&
              MO->SegRegNum == X86::NoRegister && MO->BaseRegNum != X86::RIP) {

This could be the case of a simple duplicate which should be deleted, or it
could be something more complex like something else needs to be tested instead.

**Comment by maksfb** [comment]
Thank you for reporting.
