### ISSUE TITLE
Simple condition fusion which works on scalars should work with vectors too

### ISSUE THREAD

**Issue by Validark** [llvm/llvm-project#80122]
If you have a function like this:

```zig
fn scalar(a: u64, b: u64) bool {
    return 0 == a and 0 == b;
}
```

LLVM will optimize it to `0 == (a | b)`:

```asm
scalar:
        or      rdi, rsi
        sete    al
        ret
```

Unfortunately, this seems not to be the case for vectors.

```zig
fn vec_unoptimized(vec1: Chunk, vec2: Chunk) bool {
    return 0 == std.simd.countTrues(vec1 > @as(Chunk, @splat(0))) and
           0 == std.simd.countTrues(vec2 > @as(Chunk, @splat(0)));
}
```

This x86-64 assembly is given:

```asm
vec_unoptimized:
        vptest  ymm0, ymm0
        je      .LBB0_3
        xor     eax, eax
        vzeroupper
        ret
.LBB0_3:
        vptest  ymm1, ymm1
        sete    al
        vzeroupper
        ret
```

I'd much rather have:

```asm
vec_optimized:
        vpor    ymm0, ymm1, ymm0
        vptest  ymm0, ymm0
        sete    al
        vzeroupper
        ret
```

[Godbolt link](https://zig.godbolt.org/z/aoKTcTW9h)

**Comment by Validark** [comment]
Interesting discovery: when the CPU target is set to `znver4`, the `vec_unoptimized` function is optimized the same as `vec_optimized`. However, it will not do the optimization for `znver3`.

**Comment by RKSimon** [comment]
@Validark Do you know how std.simd.countTrues is implemented internally? Could it be that zig is aware znver4 has avx512 which has predicate mask types that help with this?

**Comment by Validark** [comment]
> @Validark Do you know how std.simd.countTrues is implemented internally? Could it be that zig is aware znver4 has avx512 which has predicate mask types that help with this?

https://github.com/ziglang/zig/blob/788a0409af15d5823e0e96652ffb71458f78f820/lib/std/simd.zig#L320

```zig
pub fn countTrues(vec: anytype) VectorCount(@TypeOf(vec)) {
    const len = vectorLength(@TypeOf(vec));
    const CountIntType = VectorCount(@TypeOf(vec));

    const all_ones: @Vector(len, CountIntType) = @splat(1);
    const all_zeroes: @Vector(len, CountIntType) = @splat(0);

    const one_if_true = @select(CountIntType, vec, all_ones, all_zeroes);
    return @reduce(.Add, one_if_true);
}
```

**Comment by RKSimon** [comment]
C++ Version for easier triage (sorry I'm not very good with zig): https://gcc.godbolt.org/z/1ETTfG4Wf

**Comment by RKSimon** [comment]
Its happening in SimplifyCFG so probably a cost decision: https://gcc.godbolt.org/z/ozajY8jcT

**Comment by RKSimon** [comment]
This is due to x86 icmp costs not accounting for the lower costs when one of the operands is constant (especially if zero) - and poorly handling of the "extra cost" of some icmp predicates depending upon CostKind - the changes are trivial, but I need to update a lot of the cost model tests first as we have a lot of incomplete tests that only use undef/constant operands.
