### ISSUE TITLE
[libc] Do not include system header `errno.h` in `libc_errno.h` header.

### ISSUE THREAD

**Issue by lntue** [llvm/llvm-project#80172]
Separate just the definition of errno numbers in include/llvm-libc-macros/* and only include that instead of the system header in `libc_errno.h`

**Comment by nickdesaulniers** [comment]
Looking at the sources of the linux kernel, FWICT, the values here don't appear to be architecturally dependent.

That said, it looks like glibc may have different values for
- `ECANCELED`
- `EOWNERDEAD`
- `ENOTRECOVERABLE`
- `ERFKILL`
- `EHWPOISON`
for:
- mips
- alpha
- sparc
- hppa (parisc?)

(Hurd also has significantly different values, so perhaps the above only applies for linux).

(LLVM itself only supports mips and sparc (poorly) from the above list)  cc @frobtech 

---

Right now `ninja libc-lint` is spewing instances of `llvmlibc-restrict-system-libc-headers` over including `<errno.h>` in libc/src/errno/libc_errno.h, but I suspect we need some way of having a different set of values for errno (if fuchsia has different values than Linux).
