### ISSUE TITLE
[DirectX] DXIL Container Support for SM 6.8 additions

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#80175]
SM 6.8 added changes to the PSV0 structures:

https://github.com/microsoft/hlsl-specs/blob/main/proposals/0012-psv0-entry-name.md

We should implement this support in the Object, ObjectYAML, and MC libraries to enable SM 6.8 code generation.

The existing tests for PSV data serialization and deserialization are here:
https://github.com/llvm/llvm-project/tree/main/llvm/test/ObjectYAML/DXContainer

**Comment by coopp** [comment]
There was an endian byte swap issue with this change that caused a failure on ppc runs.  This commit reverted the original change: https://github.com/llvm/llvm-project/pull/86211
