### ISSUE TITLE
[HLSL] Codegen support for `WaveActiveCountBits`

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#80176]
### Description
A stub function and builtin declaration have been added for `WaveActiveCountBits` to enable building out availability attribute support. The CodeGen is not complete, so we need to fill that support out.

### Acceptance Criteria
Completed lowering of `WaveActiveCountBits` to DirectX-backend intrinsics.

**Comment by damyanp** [comment]
Marking re-estimate this. Since this was originally refined, we have a different approach to implementing intrinsics and the way we've been estimating intrinsics has changed quite a bit.

Also, this issue isn't linked up like the other intrinsics issues.
