### ISSUE TITLE
LLDB is unable to correctly read variable information

### ISSUE THREAD

**Issue by IOVOVHS** [llvm/llvm-project#80248]
a simple bug.there is a warning given by lldb when printing a variable.The error message indicates that this is a compiler issue about dwarf, but gdb can read the information.After comparing the compilation results of gcc and clang, it can be determined that the issue is with lldb.

```
struct S1 {
   unsigned f0 : 23;
   volatile unsigned f1 : 29;
   unsigned f2 : 14;
};

struct S2 {
   unsigned int  f0;
   unsigned long  f1;
   const unsigned f2 : 5;
   struct S1  f3;
};

union U8 {
   const volatile unsigned long  f0;
   volatile signed f1 : 20;
   signed f2 : 1;
   volatile char f3;
   int  f4;
};
int main(){
    static union U8 g_1029 = {1UL};
    static struct S2 g_736[8] = {{18446744073709551610UL,5UL,3,{2178,4611,117}},{18446744073709551615UL,0xE9A8DB06606C1D1CLL,0,{425,20808,63}},{18446744073709551610UL,5UL,3,{2178,4611,117}},{18446744073709551610UL,5UL,3,{2178,4611,117}},{18446744073709551615UL,0xE9A8DB06606C1D1CLL,0,{425,20808,63}},{18446744073709551610UL,5UL,3,{2178,4611,117}},{18446744073709551610UL,5UL,3,{2178,4611,117}},{18446744073709551615UL,0xE9A8DB06606C1D1CLL,0,{425,20808,63}}};
    static struct S2 *g_735 = &g_736[4];
    struct S2 **l_3281 = &g_735;
    static union U8 g_995 = {1UL};
    union U8 *l_2889 = &g_995;
}
```
### lldb command
```
b 28
run
p *l_2889
```
### platform
Ubuntu 20.04

Then the lldb gives the follwing message:
warning: (x86_64) /home/hzw/experiment/bug/testBug/testBug1/bug1 0x7fffffff000000ee: DW_TAG_member bitfield named "f2" has invalid bit offset (0x00000000) member will be ignored. Please file a bug against the compiler and include the preprocessed output for /home/hzw/experiment/bug/testBug/testBug1/bug1.c
(U8) $0 = (f0 = 1, f1 = 1, f3 = '\x01', f4 = 1)

**Comment by Michael137** [comment]
Which version of lldb are you using? This didn't reproduce for me on top-of-tree (`08c0eb183a9ca2983d20f5a5f366df44f199d287`) on Darwin.

**Comment by IOVOVHS** [comment]
I used the sudo command to install lldb, version 10.0.0.

**Comment by Michael137** [comment]
That's quite an old version of LLDB. Could you try with a more recent version? (e.g., lldb-17)

**Comment by Michael137** [comment]
Thanks for confirming!
