### ISSUE TITLE
Wasm: Functions forcefully marked export by linker

### ISSUE THREAD

**Issue by ryandurkoske** [llvm/llvm-project#80258]
Steps:
- Generate a relocatable wasm object file using wat2wasm
- Link the object in with the rest of a C program with wasm-ld

Issue:
All the functions defined in the object file are forcefully marked as exports.  

I'm excited that _it just works_, except for this particular annoyance. Marking the extern declaration with hidden visibility does not make a difference.

Reproduce:

I know its not an issue on wabt's part.  Here is the disassembly of the relocatable obj file generated by wat2wasm:

```
(module
  (type (;0;) (func (param i32)))
  (import "env" "memory" (memory (;0;) 2 65536 shared))
  (func $mtx_lock (type 0) (param i32)
    ...instructions...)
  (func $mtx_unlock (type 0) (param i32)
    ...instructions...)
  (@custom "linking" "\02\08\1b\02\00\00\00\08mtx_lock\00\00\01\0amtx_unlock"))
```

Here is my extern declaration of the functions in a header file:
```
__attribute__((visibility("hidden"))) extern void mtx_lock(mtx_t* mut_ptr);
__attribute__((visibility("hidden"))) extern void mtx_unlock(mtx_t* mutex_ptr);
```

Clang C Source compiler flags: (clang version 17.0.6)
```
-std=c17 -target wasm32 -flto
-Wall -g -O3 
-nostdlib -fvisibility=hidden
-mbulk-memory -msimd128 -matomics -mmutable-globals 

```
wasm-ld flags: (LLD version 17.0.6)
```
--export-dynamic --unresolved-symbols=report-all --import-memory --error-limit=0 --stack-first --gc-sections 
-O3 --shared-memory --max-memory=4294967296 -zstack-size=65536
```

For further clarity, heres the undesirable result from the disassembly of the wasm linker output:
```
...function definitions...
...more exports...
 (export "mtx_lock" (func $mtx_lock))
 (export "mtx_unlock" (func $mtx_unlock))
... data ...
... @custom data ...
```

This is the reverse behavior of a similar issue with llvm-ar generated archive files.  The linker or the archiver is stripping the visibility off of C declared/defined functions.

**Comment by sbc100** [comment]
This is likely a bug in was2wasm and not an llvm bug.

Presumably the problem only occurs when you pass `--export-dynamic`?  If so that means that wat2wasm is not marking those symbols as hidden.    The `hidden` attribute applies to the definition of the symbol which is lives the was2wasm output file and not in the C/C++ source code that references it

**Comment by ryandurkoske** [comment]
@sbc100 ope! I misread the documentation. Safe to say I should simply not use dynamic exports with clang default hidden visibility when I'm mixing in with WAT. I should instead rely on the default behavior and the export_name attribute. First time that approach has come to bite, it was so convenient, oh well. Thanks for the help.

Should I file a bug with wabt? It seems it may just be my fault, given it's not the wat relocatable's responsibility to add implicit hidden tags to everything not marked as exported. Yet for the sake of knowing, does the wasm object abi define a hidden symbol? I've read over the annotations proposal and can't seem to find an @hidden symbol to use in case I did want to stick with dynamic exports.

Quick unrelated question, in an assembly file if I want to mark a wasm global as exported I can use the .weak directive.

**Comment by sbc100** [comment]
Hidden symbols are marks as such in the symbol table of the object file.  I don't think wabt knows how to make symbols are hidden though.   I would not recommend using wabt for this purpose but instead use llvm asm format.

Regarding the assembly format, you can set symbols as hidden using the `.hidden` attribute.    Anything non-hidden global symbols will be exported if you link with `--export-dynamic`.  If you don't link with `--export-dynamic` then only symbols exported using `--export` to the the `.export_name` attribute will be exported.

The asm format is not well documented no.  I would advise looking in `lld/test/wasm` for examples.
