### ISSUE TITLE
[clang] incorrect merging of UsingShadowDecl

### ISSUE THREAD

**Issue by mizvekov** [llvm/llvm-project#80252]
When merging imported modules, equivalent UsingShadowDecls from the TU and from the module would not be merged, resulting in them becoming different entities, instead of redeclarations.

A simple reproducer would be:

`foo.h`
```
namespace baz {
  using foo = char;
  using baz::foo;
}
```

`A.cppm`
```
module;
#include "foo.h"
export module A;
```

`B.cpp`
```
#include "foo.h"
import A;
// Since modules are loaded lazily, force loading by performing a lookup.
using xxx = baz::foo;
```

Building this with:
`-cc1 -std=c++20 -emit-module-interface -o A.pcm A.cppm`
`-cc1 -std=c++20 -fmodule-file=A=A.pcm -fsyntax-only -ast-dump-all -ast-dump-filter baz C.cpp`

This would result in the following AST:
```
NamespaceDecl ... baz
|-...
`-UsingShadowDecl 0x2563bdbe448 ... imported in A.<global> hidden implicit TypeAlias ... 'foo'

...

NamespaceDecl ... baz
|-...
`-UsingShadowDecl 0x2563bdbe1a0 ... implicit TypeAlias ... 'foo'
```

The first UsingShadowDecl should have been a redeclaration of the second one.

You would expect:
```
NamespaceDecl ... baz
|- ....
`-UsingShadowDecl 0x1b63f707b58 prev 0x1b63f7078b0 ... imported in A.<global> hidden implicit TypeAlias ... 'foo'

...

NamespaceDecl ... baz
|- ....
`-UsingShadowDecl 0x1b63f7078b0 ... implicit TypeAlias ... 'foo'
````

This was originally reduced from this example that manifested itself as an ODR violation in the global module fragment:
`foo.h`
```
namespace baz {
  using foo = char;
  using baz::foo;
}
```

`bar.h`
```
class bar {
  bar(baz::foo);
};
```

`A.cppm`
```
module;
#include "foo.h"
export module A;
```

`B.cppm`
```
module;
#include "foo.h"
#include "bar.h"
export module B;
```

`C.cpp`
```
#include "foo.h"
import A;

#include "bar.h"
import B;

// Since modules are loaded lazily, force loading them by performing a lookup.
using xxx = bar;
```

And this compilation would result in an ODR false positive, where the definitions for the bar constructor don't match due to different parameters. This failure stopped happening when we merged the patch to disable the GMF ODR check.

This had been further reduced from a similar example with pure inclusion of libc++ headers, on MSVC platform. `s/foo.h/stddef.h` `s/bar.h/locale`

**Comment by mizvekov** [comment]
FYI @ChuanqiXu9

**Comment by shafik** [comment]
FYI since you are filing this issue to track your progress, you can self-add the "confirmed" label.
