### ISSUE TITLE
Declaration-or-expression ambiguity resolution picks incorrectly for complicated expressions

### ISSUE THREAD

**Issue by DougGregor** [llvm/llvm-project#8027]
|  |  |
| --- | --- |
| Bugzilla Link | [7655](https://llvm.org/bz7655) |
| Version | trunk |
| OS | All |
| CC | @akyrtzi,@DougGregor |

## Extended Description 
Given this insane code:

```cpp
struct X { 
  template<typename T> X(T);
  X(int, int);

  X operator()(int, int) const;
};

template<typename T, typename U> struct Y { };

X *x;
void f() {
  int y = 0;
  X (*x)(int(y), int(y)) = Y<int, float>(), ++y;
}
```

Clang, like gcc, determines that the second statement in "x" is a declaration, when in fact it's an expression. The problem is that we don't fully parse the initializer after the '=' to determine whether what follows the ',' is another declarator or not.

**Comment by shafik** [comment]
It is not obvious what the bug is here and implementations are pretty consistent that this invalid: https://godbolt.org/z/hv9K4dxTM

Also the test indicated does not seem to exist anymore.
