### ISSUE TITLE
[coverage] crash with ExprWithCleanups in `if constexpr`

### ISSUE THREAD

**Issue by hanickadot** [llvm/llvm-project#80285]
Clang `main` and `18` crashes with this code: (`-fprofile-instr-generate -fcoverage-mapping -std=c++17`)

```c++
struct false_value {
	constexpr operator bool() {
		return false;
	}
};

void foo()
{
	if constexpr (false_value{}) { };
}
```

https://godbolt.org/z/833ej19rP

It's a bug in my recent change https://github.com/llvm/llvm-project/pull/78033 ... writing patch now, this is so it's visible.

**Comment by mjklemm** [comment]
Hey folks, this was completely unintentional that GitHub closed this issue.  I maintain a private fork for stuff that I do not feel ready for prime time yet and I had pushed to that fork.  How can I prevent this stuff from happening in the future?  Does anyone know?  And, apologies again!
