### ISSUE TITLE
DSCallGraph Missing Functions

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8050]
|  |  |
| --- | --- |
| Bugzilla Link | [7678](https://llvm.org/bz7678) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
When running fluidanimate from PARSEC and water from SPLASH-2, the getFunctionCalls() is missing entries for some callees.  These callees are not well-known external functions, but rather seemingly arbitrary functions which exist in the same .bc file.

**Comment by arsenm** [comment]
Last comment asks if it's fixed, I also don't think DSCallGraph exists anymore
