### ISSUE TITLE
fixit hints don't obey access control

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#8052]
|  |  |
| --- | --- |
| Bugzilla Link | [7680](https://llvm.org/bz7680) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor |

## Extended Description 
I accidentally called the getWidth() member of APInt instead of getBitWidth() and got this:

CGExprCXX.cpp:445:18: error: no member named 'getWidth' in 'llvm::APInt'; did you mean 'BitWidth'?
    NEC.zext(NEC.getWidth()*2);
                 ^~~~~~~~
                 BitWidth
In file included from CGExprCXX.cpp:14:
In file included from /Users/sabre/llvm/tools/clang/lib/CodeGen/CodeGenFunction.h:17:
In file included from /Users/sabre/llvm/tools/clang/lib/CodeGen/../../include/clang/AST/Type.h:25:
In file included from /Users/sabre/llvm/include/llvm/ADT/APSInt.h:18:
/Users/sabre/llvm/include/llvm/ADT/APInt.h:73:12: note: 'BitWidth' declared here
  unsigned BitWidth;      ///< The number of bits in this APInt.
           ^
CGExprCXX.cpp:445:18: error: 'BitWidth' is a private member of 'llvm::APInt'
    NEC.zext(NEC.getWidth()*2);
                 ^

In file included from CGExprCXX.cpp:14:
In file included from /Users/sabre/llvm/tools/clang/lib/CodeGen/CodeGenFunction.h:17:
In file included from /Users/sabre/llvm/tools/clang/lib/CodeGen/../../include/clang/AST/Type.h:25:
In file included from /Users/sabre/llvm/include/llvm/ADT/APSInt.h:18:
/Users/sabre/llvm/include/llvm/ADT/APInt.h:73:12: note: declared private here
  unsigned BitWidth;      ///< The number of bits in this APInt.
           ^
CGExprCXX.cpp:445:26: error: called object type 'unsigned int' is not a function or function pointer
    NEC.zext(NEC.getWidth()*2);
             ~~~~~~~~~~~~^


This sucks for two reasons: it suggested a field when I'm calling a function, and it suggested a private member that I definitely couldn't call.

**Comment by philnik777** [comment]
I guess something like
```c++
struct S {
private:
  int value;
};

int func(S* s) {
  return s->valu();
}
```
is meant. This has been fixed in Clang 3.6: https://godbolt.org/z/n7Mr4Mrqq
