### ISSUE TITLE
llvm/test/CodeGen/WebAssembly/immediates.ll: passes for mips now

### ISSUE THREAD

**Issue by wzssyqa** [llvm/llvm-project#80533]
So an 'unexpected pass' is reported.

**Comment by dschuff** [comment]
That's easy to fix, but I don't know who should review this. Do you? Are there MIPS builders that might break if we land this? Do you know who runs them?

**Comment by wzssyqa** [comment]
Currently, there is no active mips official maintainer.
I am trying to fix some MIPS bugs, and I wish that I can do something for LLVM MIPS Port, maybe in future.
