### ISSUE TITLE
llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp:1649: condition is always true ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#80557]
Static analyser cppcheck says:

llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp:1649:32: warning: Logical disjunction always evaluates to true: InstDisp < 32768 || InstDisp >= -32768. [incorrectLogicOperator]

Source code is

    assert(((InstDisp < 32768) ||
            (InstDisp >= -32768)) &&
               "Expecting the instruction displacement for local-exec TLS "
               "variables to be between [-32768, 32768)!");

Perhaps intended code might be

    assert(((InstDisp < -32768) ||
            (InstDisp >= 32768)) &&
               "Expecting the instruction displacement for local-exec TLS "
               "variables to be between [-32768, 32768)!");

**Comment by Disservin** [comment]
should be `(InstDisp >= -32768 && InstDisp < 32768)` ?

**Comment by amy-kwan** [comment]
@dcb314 Thank you for reporting this, and @bzEq thank you for fixing this!
