### ISSUE TITLE
Reasoning about the poorly-defined behavior of function attributes across TUs

### ISSUE THREAD

**Issue by ryandurkoske** [llvm/llvm-project#80568]
Attributes attached to a function declaration, in a TU separate from the definition, don't do anything.  They don't throw no-unused-attribute errors either.  An error or warning not being thrown even with -Wall is a bug, likely occurring because attribute usage is statically checked and assumes the definition exists in the TU somewhere.  By mistake of the programmer or by his intention, it should not be assumed by the compiler that the declaration always has a definition in its TU.

A better language to reason about this behavior:

I suppose 3 categories for different types of attributes: caller attributes; definitional attributes; and link-time attributes. We segregate them based on when/where the attribute's consequence takes affect.  Naked is a great example of a compile-time, definitional attribute. always_inline is a caller's attribute (might be link time might be compile time. shouldnt matter.), and visibility or dllexport is a link time attribute.

Why this all matters:

 Suppose you're working with a general x64 asm library that you decide to integrate into a Clang C project.  You'd need a header of function declarations to define the ABI to call the functions from your C code.  Some of the function declarations are marked always_inline, and that should seemingly work because its a callers attribute.  Will it? No, it does not work.  All attributes of a function declaration are dropped unless its TU can see the definition.

Suppose your C wants to directly dllexport an asm function, you shouldn't need to be forced to modify someone elses asm library.  C should be powerful enough, s.t the dllexport attribute should just work when attached to the function declaration in the header.  The consequence of the attribute is not processed until link-time, anyway.  Attributes should be accumulated during unknown symbol resolution, and link-time attributes' consequences can be processed after all symbol resolution.  It wouldn't be difficult to implement such behavior.  All it requires is storing the attributes in the symbol table for all unknown symbols during compilation.  

Do I think we should change this undocumented behavior of attributes across TUs? No, for the sake of backwards compatibility.  We should add a new keywork like `__linker_attribute__` or something prettier, you get it.  This way, attributes that cannot possibly be linker attributes can throw errors.  Naked attribute, for example, cannot be a link time attribute because it would modify the function body at compile time.

Caller-time function attributes should not need to be marked as `__linker_attribute__` to work, because it wont apply to the definition across the TU.  Its effect is local to its TU.  It should work by default.  At this point, maybe by introducing another keyword so that errors can be more easily enforced.  `__caller_attribute__((noinline))`.

Its tough to reason about which category `optnone` would fall into.  Let's talk about that.  I believe it could be definitional or caller's, depending on where the definition is and what attribute keyword you use.

Regardless of whether or not you see a need for this, it should be documented somewhere, or at a bare minimum throw a no-unused-attributes error.  The attributes are dropped silently.

**Comment by ryandurkoske** [comment]
push*

**Comment by Sirraide** [comment]
> Attributes attached to a function declaration, in a TU separate from the definition, don't do anything.

That’s not entirely true; it depends on the attribute. For instance `[[nodiscard]]` is usually only attached to the declaration and will cause a warning to be emitted if a call to the function is discarded irrespective of whether it’s defined in the same TU as the caller or not.

> Some of the function declarations are marked always_inline

You could make a case that if a function is marked `always_inline`, and it’s called from a function in a TU where its definition is not visible, then we should warn that it may not be inlined. GCC even errors if that happens, so it might make sense to do that. On the other hand, LTO might still make it possible to inline the function even if it is defined elsewhere—I suppose we could at least warn if LTO is disabled?

> Suppose your C wants to directly dllexport an asm function

I’m candidly not sure if that makes sense; shouldn’t the exporting be handled in assembly if you’re writing the function in assembly?

What I’m gathering is that you’re proposing a change in how attributes are handled. I’m not convinced this is necessary, and this sounds substantial enough to where it should probably also be handled via an RFC; if you want to continue pursuing this, I would probably recommend making a post on [Discourse](https://discourse.llvm.org) and see what people think about it.

I’m going to open an issue wrt `always_inline`, if there isn’t already one; I think it makes sense to at least consider warning about that.

**Comment by Sirraide** [comment]
Looks like there already is an issue about this: #42862

**Comment by ryandurkoske** [comment]
@Sirraide My dllexport generalization was a bit careless. What I'm really working with is webassembly WAT file mixing with C  using wasm-ld linker with export-dynamic and default visibility hidden. It's a nice setup because it gives automatic naming to any exports by just setting the visibility to default. 

The big issue is that an object file compiled from WAT will not have the default visibility of hidden. The "don't export" decorator must be in some other file outside of the WAT files because of language limitations. It's up to C and wasm-ld to do it, but there is no way to do it in clang either because no C or header file will ever be in the same TU as the WAT file. So when using WAT files and the convenient export-dynamic+default hidden setup, it's impossible to avoid exporting all WAT defined functions. (LTO or not)

The fix is to just use explicit exports, and if you do want to export a WAT function you can wrap it and hope it inlines, but if clang wants to be the c compiler homebase of wasm that it is, we should do something about this limitation. 

It's not just about wasm though, it's highlighting the underlying holistic issue with attributes. When attempting to set function visibility from another TU, it's not intuitive that it won't work. The issue is how overloaded with responsibility the keyword "attribute" is. It's nice how simple it is, being a single word to remember, but lacking structure and doesn't represent what goes on under the hood much. Wasm would greatly benefit from more rigid and powerful decorators, and I'm sure compiler contributors would appreciate well-defined attribute categories as well.

Thanks for the response and a pointer on where to go further. Do you think my radical change has more merit now? I don't want to waste people's time or embarrass myself in a mailing list haha.

**Comment by Sirraide** [comment]
> When attempting to set function visibility from another TU, it's not intuitive that it won't work.

Admittedly, `visibility` is bit different from other attributes; I don’t think attributes in general really suffer too much from this problem (unless I’m missing something obvious here); it’s mostly just a few like that one and maybe `always_inline`, from what I can tell.

> Thanks for the response and a pointer on where to go further. Do you think my radical change has more merit now? I don't want to waste people's time or embarrass myself in a mailing list haha.

Attributes are already a fairly complicated system, so I don’t think a large-scale refactor is something we really need at the moment (at least I haven’t heard of any present major dissatisfaction with how they’re handled internally or anything like that).

I’d say that it’d make more sense to mention specifically that and how your problem is WASM-related. I’m not familiar enough with WASM to know how people normally deal with the issue you appear to be running into, but if you open another issue (or start a discussion on Discourse if you already have an idea for a fix or something like that) and focus on the WASM part, I think it’d be easier to get somewhere from that.

**Comment by Sirraide** [comment]
> mention specifically that and how your problem is WASM-related

(and maybe include some code examples if possible, because your initial post at least is pretty abstract)
