### ISSUE TITLE
AST improperly conflates decls for out-of-line inline template methods.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8060]
|  |  |
| --- | --- |
| Bugzilla Link | [7688](https://llvm.org/bz7688) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Here's an example program that illustrates the problem:
---
template<typename T> struct Foo { inline Foo(); };
template<typename T> Foo<T>::Foo() { }
struct Bar { inline Bar(); };
Bar::Bar() { }

int main() {
  Foo<int> foo;
  Bar bar;
  return 0;
}
---

I ran this program through RecursiveASTVisitor, with a callback for VisitCXXConstructExpr().  I then looked at decl = expr->getConstructor().

For the Bar constructor call, the decl looked just like I'd expect:
---
(gdb) print PrintableLoc(decl->getLocation())
$6 = "devtools/maintenance/include_what_you_use/sample.cc:4:6"
(gdb) print decl
$7 = (clang::CXXConstructorDecl *) 0x136ee80
(gdb) print decl->getFirstDeclaration()
$8 = (clang::CXXConstructorDecl *) 0x136ebe0
(gdb) print decl->getMostRecentDeclaration()
$9 = (clang::CXXConstructorDecl *) 0x136ee80
(gdb) 
---
There are two decls, and the canonical decl is the one with the definition.

For the Foo<int> constructor call, there's only one decl:
---
(gdb) print PrintableLoc(decl->getLocation())
$1 = "devtools/maintenance/include_what_you_use/sample.cc:1:42"
(gdb) print decl
$2 = (clang::CXXConstructorDecl *) 0x1371100
(gdb) print decl->getFirstDeclaration()
$3 = (clang::CXXConstructorDecl *) 0x1371100
(gdb) print decl->getMostRecentDeclaration()
$4 = (clang::CXXConstructorDecl *) 0x1371100
(gdb) print decl->isThisDeclarationADefinition()
$5 = true
---
Note that even though the decl is pointing to the declaration inside the class, which has no definition, it still says the declaration has a definition.  Also, it only reports one declaration, not two.  I don't see any way at all to get at the declaration at line 2.  I'm not even sure it's in the AST anywhere.

I'd expect to see two decls for the template case, just like for the non-template class, to have the decl with the definition be the canonical one returned by expr->getConstructor(), and to have isThisDeclarationADefinition() return correct results for each of the decls.

**Comment by rnk** [comment]
This seems obsolete, I don't think we are going to change behavior here.
