### ISSUE TITLE
[LICM] Missed optimization due to missing alignment information

### ISSUE THREAD

**Issue by lucic71** [llvm/llvm-project#80616]
LICM cannot hoist a load instruction if the align attribute is missing from the pointer, see `%0 = load ptr, ptr %this, align 8 ` below.

```llvm
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define i1 @_ZN1A3fooEii(ptr dereferenceable(8) %this, i1 %exitcond.not) { ;<-- align attribute is missing
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.body, %entry
  %indvars.iv = phi i64 [ %indvars.iv.next4, %while.body ], [ 0, %entry ]
  br i1 %exitcond.not, label %cleanup, label %while.body

while.body:                                       ; preds = %while.cond
  %indvars.iv.next4 = add i64 %indvars.iv, 1
  %0 = load ptr, ptr %this, align 8 ; <-- instruction that is not hoisted
  %1 = load i32, ptr %0, align 4
  %cmp2 = icmp eq i32 %1, 0
  br i1 %cmp2, label %cleanup, label %while.cond

cleanup:                                          ; preds = %while.body, %while.cond
  %cmp = icmp slt i64 %indvars.iv, 0
  ret i1 %cmp
}
```

If we add the align attribute to the pointer as follows: `define i1 @_ZN1A3fooEii(ptr align 8 dereferenceable(8) %this, i1 %exitcond.not) {` the load instruction is successfully hoisted to entry. See https://godbolt.org/z/PKzxMWonG, on the left are the IRs with and without align and on the right are the results of -O2.

This happens because in isAligned, this condition will fail as BA, i.e. the alignment of the pointer, which is 1, is less than Alignment, i.e. the alignment of the load instruction, which is 8:
https://github.com/llvm/llvm-project/blob/900e7cbfdee09c94d022e4dae923b3c7827f95e3/llvm/lib/Analysis/Loads.cpp#L32

However for architectures such as x86 this is not optimal because unaligned loads are allowed. To prove this we can do the following experiment: we compare the assembly output of the hoisted version when the alignment of the load is 8 and when the alignment of the load is 1. This will result in no difference between the two versions, see https://godbolt.org/z/MqPTb5ch7 

The same case can be done for all architectures that support unaligned loads.

cc: @nunoplopes

**Comment by dtcxzyw** [comment]
Could you please provide the corresponding C code? IIRC clang adds the `align` attribute for `this` pointer.
https://github.com/llvm/llvm-project/blob/4b34558f43121df9b863ff2492f74fb2e65a5af1/clang/lib/CodeGen/CGCall.cpp#L2647-L2683

**Comment by lucic71** [comment]
@dtcxzyw you're right that Clang adds the `align` attribute for `this` pointer. We are experimenting with a Clang version that does not add `align`.

However this is not a `this`-specific issue, any load on pointers that miss alignment information suffers from this behavior.

**Comment by nikic** [comment]
> you're right that Clang adds the align attribute for this pointer. We are experimenting with a Clang version that does not add align.

Why?

We could indeed lower the load alignment when hoisting, but I don't think the situation "pointer with dereferenceability information but no alignment information" is something we're interested in right now, because getting the former without the latter would be very unusual.

**Comment by dtcxzyw** [comment]
Feel free to reopen this issue if you find other optimization opportunities due to the lack of alignment information.
