### ISSUE TITLE
 [llvm-cov] Implementation of RFC adding a -sourcesFile flag

### ISSUE THREAD

**Issue by farzonl** [llvm/llvm-project#80645]
RFC: https://discourse.llvm.org/t/rfc-llvm-cov-adding-a-sourcesfile-flag/76783/1

On Windows there is a character limit for commands via the terminal so we can’t use llvm-cov’s -sources flag.

The solution to this is to use a file instead and iterate over the paths in that file

**Comment by EugeneZelenko** [comment]
@farzonl: Could you please elaborate?

**Comment by farzonl** [comment]
Yeah the RFC feedback was to use a response file. So the ticket as written isn't necessary anymore.
