### ISSUE TITLE
[libc] Support C23 binary notation in `sprintf`

### ISSUE THREAD

**Issue by SchrodingerZhu** [llvm/llvm-project#80727]
see https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2612.pdf

**Comment by michaelrj-google** [comment]
This should be fairly straightforward if you'd like to implement it. 

You'll need to add the new format in the int converter (here: https://github.com/llvm/llvm-project/blob/main/libc/src/stdio/printf_core/int_converter.h#L32) based on `IntegerToString<Bin>` (here: https://github.com/llvm/llvm-project/blob/main/libc/src/__support/integer_to_string.h#L156).

You'll also need to add `b` and `B` as conversion name options in the main converter switch statement (here: https://github.com/llvm/llvm-project/blob/main/libc/src/stdio/printf_core/converter.cpp#L55) and in the parser (here: https://github.com/llvm/llvm-project/blob/main/libc/src/stdio/printf_core/parser.h#L156 and here: https://github.com/llvm/llvm-project/blob/main/libc/src/stdio/printf_core/parser.h#L481)

**Comment by agentcooper** [comment]
Ah, I didn't notice that @Rajveer100 already sent a PR for this. Although it seems that our implementations are somewhat different.

**Comment by michaelrj-google** [comment]
I've looked over both patches and @agentcooper's looks more complete so I put my review there. Feel free to collaborate on finishing this. There's a libc channel in the LLVM discord which is a good place to chat about libc.

**Comment by Rajveer100** [comment]
Absolutely, no worries! I would love to learn from the changes!
