### ISSUE TITLE
[llvm] Support for ARM64EC in LLVM 18

### ISSUE THREAD

**Issue by dpaoliello** [llvm/llvm-project#80752]
This is a meta-issue to gather any fixes made to the `main` branch to enable backporting to the v18 release branch to enable support for ARM64EC in LLVM 18.

More information about ARM64EC: <https://learn.microsoft.com/en-us/windows/arm/arm64ec>

**Comment by dpaoliello** [comment]
/cherry-pick c761b4a5e4cc003a2c850898e1dc67d2637cfb0c 8f070144e3711ad0e5556eaebc72069c0d869342

**Comment by tstellar** [comment]
PR has been created, we will track the status there.
