### ISSUE TITLE
Feature-request: inline llvm

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8077]
|  |  |
| --- | --- |
| Bugzilla Link | [7705](https://llvm.org/bz7705) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Hi!

Currently it is possible to integrate inline assembly into the C(++)-code. Well, there is an unsupported but really nice assembly language: LLVM IR. I think it would be really usefull to allow integration of this language, esppecially for special LLVM-features being normally unavailable in C++, e.g. for custom trampolines or synchronization stuff…

Regards
Jonathan

**Comment by arsenm** [comment]
This isn't a good idea, the text IR isn't supposed to be stable. There's close to no chance this will ever be implemented
