### ISSUE TITLE
flang/lib/Semantics/data-to-inits.cpp:523:Suspicious condition

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#80807]
Static analyser cppcheck says:

flang/lib/Semantics/data-to-inits.cpp:523:13: warning: Suspicious condition. The result of find() is an iterator, but it is not properly checked. [stlIfFind]

Source code is

        if (std::find_if(
                directs.begin(), directs.end(), [](const Symbol &component) {
                  return !IsAllocatable(component) &&
                      HasDeclarationInitializer(component);
                })) {

Checking for != 0 looks wrong because != last should be IMHO tested for.

**Comment by chrchr-github** [comment]
Looks like the iterator allows conversion to `bool`. This doesn't compile:
~~~c++
void f(const std::vector<int>& v) {
    if (std::find(v.begin(), v.end(), 0)) {}
}
~~~

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/82790
