### ISSUE TITLE
[C++23] [Modules] Compile error: different definitions in different modules

### ISSUE THREAD

**Issue by JinHai-CN** [llvm/llvm-project#80800]
Hi guys, Our [project](https://github.com/infiniflow/infinity) is using c++20 and applied modules feature. But when we compile it with c++23, we get the following error. 

![1707198156578.png](https://github.com/llvm/llvm-project/assets/33142505/f04649de-bac7-438a-a555-77ae5b6c083a)

Is there a problem with the STL I'm wrapping or something else?

Clang: Ubuntu clang version 18.1.0 (++20240203081317+140ad18e1ea2-1~exp1~20240203201335.24)

**Comment by dwblaikie** [comment]
Can't seem to load the image - and generally a copy/paste of the text is more usable for everyone than a screenshot. If you could include the copy/pasted text, that'd be handy, thanks!

**Comment by ChuanqiXu9** [comment]
While I can't see the image either, I guess this is related to https://github.com/llvm/llvm-project/pull/79959 (You can read the document to get the rationale). For verifying, you can either compile a clang from source in trunk or wait for the next RC of clang18 in the next week.

**Comment by JinHai-CN** [comment]
> Can't seem to load the image - and generally a copy/paste of the text is more usable for everyone than a screenshot. If you could include the copy/pasted text, that'd be handy, thanks!

No problem. At first, I plan to paste the text, which is not readable from my view. So I give the screen shot. OK, I will give the error text.

**Comment by JinHai-CN** [comment]
> While I can't see the image either, I guess this is related to #79959 (You can read the document to get the rationale). For verifying, you can either compile a clang from source in trunk or wait for the next RC of clang18 in the next week.

Ok, I will wait for the next clang-18 RC and come back to your guys.

**Comment by ChuanqiXu9** [comment]
> > Can't seem to load the image - and generally a copy/paste of the text is more usable for everyone than a screenshot. If you could include the copy/pasted text, that'd be handy, thanks!
> 
> No problem. At first, I plan to paste the text, which is not readable from my view. So I give the screen shot. OK, I will give the error text.

It is still images. I'll suggest to copy the text directly next time.

> > While I can't see the image either, I guess this is related to #79959 (You can read the document to get the rationale). For verifying, you can either compile a clang from source in trunk or wait for the next RC of clang18 in the next week.
> 
> Ok, I will wait for the next clang-18 RC.

I just saw the patch is included in the new clang-18 RC: https://github.com/llvm/llvm-project/commits/llvmorg-18.1.0-rc2/

**Comment by JinHai-CN** [comment]
> > > Can't seem to load the image - and generally a copy/paste of the text is more usable for everyone than a screenshot. If you could include the copy/pasted text, that'd be handy, thanks!
> > 
> > 
> > No problem. At first, I plan to paste the text, which is not readable from my view. So I give the screen shot. OK, I will give the error text.
> 
> It is still images. I'll suggest to copy the text directly next time.
> 
> > > While I can't see the image either, I guess this is related to #79959 (You can read the document to get the rationale). For verifying, you can either compile a clang from source in trunk or wait for the next RC of clang18 in the next week.
> > 
> > 
> > Ok, I will wait for the next clang-18 RC.
> 
> I just saw the patch is included in the new clang-18 RC: https://github.com/llvm/llvm-project/commits/llvmorg-18.1.0-rc2/

Yes, it is fixed.
