### ISSUE TITLE
tools/llvm-readtapi/stubify-simple.test fails when it is disallowed to write into the input directory

### ISSUE THREAD

**Issue by ilya-biryukov** [llvm/llvm-project#80868]
We have noticed our tests don't pass with https://github.com/llvm/llvm-project/commit/7189219ec9fc768f159917052b4b5998d077c39f internally.
We have a stricter setup in which we don't allow to write into arbitrary files during test execution.

It turns out that `stubify-simple.test` actually writes into `.tbd` file during its execution and gets "permission denied" error in our setup.

This happens because it uses a path of the `InterfaceFile` to figure out the output path and it can be empty in some cases.
In particular, if I `assert(!IF->getPath().empty())` to [this line](https://github.com/llvm/llvm-project/blob/7189219ec9fc768f159917052b4b5998d077c39f/llvm/tools/llvm-readtapi/llvm-readtapi.cpp#L204), the test fails upstream as well.

@cyndyishida could you please take a look?

**Comment by cyndyishida** [comment]
@ilya-biryukov Thank you for reporting. IIUC, by 

> we don't allow to write into arbitrary files during test execution

Do you mean that tools cannot write to locations outside of the test directory path? If so, I believe https://github.com/llvm/llvm-project/pull/80875 should indeed address this issue. Want to make sure because it is expected that the tool writes new files in general.

**Comment by ilya-biryukov** [comment]
> @ilya-biryukov Thank you for reporting. IIUC, by
> 
> > we don't allow to write into arbitrary files during test execution
> 
> Do you mean that tools cannot write to locations outside of the test directory path? If so, I believe #80875 should indeed address this issue. Want to make sure because it is expected that the tool writes new `.tbd` files in general.

Thanks for the fix! Yes, I think this should fix it.

In our setup the `%t` expansion inside `lit` is writable, but working directory where the test runs isn't (hence writing `$PWD/.tbd` which was attempted wasn't working).
