### ISSUE TITLE
PassManager deficiency wrt AnalysisGroups

### ISSUE THREAD

**Issue by asl** [llvm/llvm-project#8092]
|  |  |
| --- | --- |
| Bugzilla Link | [7720](https://llvm.org/bz7720) |
| Version | trunk |
| OS | All |
| CC | @sunfishcode |

## Extended Description 
Consider the following simple patch:
diff --git a/include/llvm/Support/StandardPasses.h b/include/llvm/Support/StandardPasses.h
index b97ad29..3f3d970 100644
--- a/include/llvm/Support/StandardPasses.h
+++ b/include/llvm/Support/StandardPasses.h
@@ -129,6 +129,8 @@ namespace llvm {
     PM->add(createCFGSimplificationPass());     // Merge & remove BBs
     PM->add(createReassociatePass());           // Reassociate expressions
     PM->add(createLoopRotatePass());            // Rotate Loop
+    if (OptimizationLevel > 2)
+      PM->add(createGlobalsModRefPass());
     PM->add(createLICMPass());                  // Hoist loop invariants
     PM->add(createLoopUnswitchPass(OptimizeSize || OptimizationLevel < 3));
     PM->add(createInstructionCombiningPass());  

I'm seeing completely different behavior when createStandardModulePasses() is called from opt and from llvm-gcc.

When running opt -O3 is run there are calls to GlobalsModRegAA::alias(), but nothing from llvm-gcc -O3. The pass itself initializes fine in both cases.

**Comment by arsenm** [comment]
Analysis groups don't exist anymore?
