### ISSUE TITLE
[C] error: unexpected token in argument list (target datalayout)

### ISSUE THREAD

**Issue by alejandro-colomar** [llvm/llvm-project#80929]
When trying to compile with Clang some library that I'm writing, I get this error:

```
$ make .tmp/a2i/a2i.c.o CC=clang --debug=print
CC (cpp)	.tmp/a2i/a2i.c.i
clang -I./include  -I.tmp  -O3 -std=gnu11 -flto -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement -Wno-attributes -Wno-nullability-completeness -Wno-unknown-attributes -Wno-unknown-pragmas -Wno-unused-command-line-argument          -E -o .tmp/a2i/a2i.c.i          .tmp/a2i/a2i.c
CC		.tmp/a2i/a2i.c.s
clang -I./include  -I.tmp  -O3 -std=gnu11 -flto -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement -Wno-attributes -Wno-nullability-completeness -Wno-unknown-attributes -Wno-unknown-pragmas -Wno-unused-command-line-argument          -S -o .tmp/a2i/a2i.c.s          .tmp/a2i/a2i.c
CC (as)		.tmp/a2i/a2i.c.o
clang -I./include  -I.tmp  -O3 -std=gnu11 -flto -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement -Wno-attributes -Wno-nullability-completeness -Wno-unknown-attributes -Wno-unknown-pragmas -Wno-unused-command-line-argument          -c -o .tmp/a2i/a2i.c.o            .tmp/a2i/a2i.c.s
.tmp/a2i/a2i.c.s:1:14: error: missing expression
; ModuleID = '.tmp/a2i/a2i.c'
             ^
.tmp/a2i/a2i.c.s:3:19: error: unexpected token in argument list
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
                  ^
.tmp/a2i/a2i.c.s:4:15: error: unexpected token in argument list
target triple = "x86_64-pc-linux-gnu"
              ^
.tmp/a2i/a2i.c.s:6:17: error: unexpected token in argument list
; Function Attrs: inlinehint nounwind uwtable
                ^
.tmp/a2i/a2i.c.s:7:18: error: unexpected token in argument list
define dso_local i32 @a2shh(ptr noalias nocapture noundef writeonly %0, ptr noundef %1, ptr noalias noundef %2, i32 noundef %3, i8 noundef signext %4, i8 noundef signext %5) local_unnamed_addr #0 {
                 ^
```

Is it maybe due to some CFLAGS?  I wouldn't suspect of the code, but can share it if you want to see it.

Cc: @thesamesam

**Comment by alejandro-colomar** [comment]
Indeed, here's a trivial reproducer:

```sh
$ ls
foo.c  foo.h
```
```c
alx@debian:~/tmp$ head *
==> foo.c <==
#include <foo.h>

==> foo.h <==
#include <stddef.h>
```
```
```sh
alx@debian:~/tmp$ clang-17 -I. -O3 -std=gnu11 -flto -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement -Wno-attributes -Wno-nullability-completeness -Wno-unknown-attributes -Wno-unknown-pragmas -Wno-unused-command-line-argument          -E -o foo.c.i          foo.c
alx@debian:~/tmp$ clang-17 -I. -O3 -std=gnu11 -flto -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement -Wno-attributes -Wno-nullability-completeness -Wno-unknown-attributes -Wno-unknown-pragmas -Wno-unused-command-line-argument          -S -o foo.c.s          foo.c
```
```c
alx@debian:~/tmp$ clang-17 -I. -O3 -std=gnu11 -flto -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement -Wno-attributes -Wno-nullability-completeness -Wno-unknown-attributes -Wno-unknown-pragmas -Wno-unused-command-line-argument          -c -o foo.c.o          foo.c.s
foo.c.s:1:14: error: missing expression
; ModuleID = 'foo.c'
             ^
foo.c.s:3:19: error: unexpected token in argument list
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
                  ^
foo.c.s:4:15: error: unexpected token in argument list
target triple = "x86_64-pc-linux-gnu"
              ^
foo.c.s:6:1: error: unexpected token at start of statement
!llvm.module.flags = !{!0, !1, !2, !3, !4, !5}
^
foo.c.s:7:1: error: unexpected token at start of statement
!llvm.ident = !{!6}
^
foo.c.s:9:1: error: unexpected token at start of statement
!0 = !{i32 1, !"wchar_size", i32 4}
^
foo.c.s:10:1: error: unexpected token at start of statement
!1 = !{i32 8, !"PIC Level", i32 2}
^
foo.c.s:11:1: error: unexpected token at start of statement
!2 = !{i32 7, !"PIE Level", i32 2}
^
foo.c.s:12:1: error: unexpected token at start of statement
!3 = !{i32 7, !"uwtable", i32 2}
^
foo.c.s:13:1: error: unexpected token at start of statement
!4 = !{i32 1, !"ThinLTO", i32 0}
^
foo.c.s:14:1: error: unexpected token at start of statement
!5 = !{i32 1, !"EnableSplitLTOUnit", i32 1}
^
foo.c.s:15:1: error: unexpected token at start of statement
!6 = !{!"Debian clang version 17.0.6 (5)"}
^
foo.c.s:17:1: error: unexpected token at start of statement
^0 = module: (path: "", hash: (0, 0, 0, 0, 0))
^
foo.c.s:18:1: error: unexpected token at start of statement
^1 = flags: 8
^
foo.c.s:19:1: error: unexpected token at start of statement
^2 = blockcount: 0
^
```

**Comment by alejandro-colomar** [comment]
And a smaller one:  just an empty file.

```sh
alx@debian:~/tmp$ ls
foo.c
alx@debian:~/tmp$ cat foo.c 
alx@debian:~/tmp$ clang-17 -I. -O3 -std=gnu11 -flto -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement -Wno-attributes -Wno-nullability-completeness -Wno-unknown-attributes -Wno-unknown-pragmas -Wno-unused-command-line-argument          -S -o foo.c.s          foo.c
```
```sh
alx@debian:~/tmp$ clang-17 -I. -O3 -std=gnu11 -flto -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement -Wno-attributes -Wno-nullability-completeness -Wno-unknown-attributes -Wno-unknown-pragmas -Wno-unused-command-line-argument          -c -o foo.c.o          foo.c.s
foo.c.s:1:14: error: missing expression
; ModuleID = 'foo.c'
             ^
foo.c.s:3:19: error: unexpected token in argument list
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
                  ^
foo.c.s:4:15: error: unexpected token in argument list
target triple = "x86_64-pc-linux-gnu"
              ^
foo.c.s:6:1: error: unexpected token at start of statement
!llvm.module.flags = !{!0, !1, !2, !3, !4, !5}
^
foo.c.s:7:1: error: unexpected token at start of statement
!llvm.ident = !{!6}
^
foo.c.s:9:1: error: unexpected token at start of statement
!0 = !{i32 1, !"wchar_size", i32 4}
^
foo.c.s:10:1: error: unexpected token at start of statement
!1 = !{i32 8, !"PIC Level", i32 2}
^
foo.c.s:11:1: error: unexpected token at start of statement
!2 = !{i32 7, !"PIE Level", i32 2}
^
foo.c.s:12:1: error: unexpected token at start of statement
!3 = !{i32 7, !"uwtable", i32 2}
^
foo.c.s:13:1: error: unexpected token at start of statement
!4 = !{i32 1, !"ThinLTO", i32 0}
^
foo.c.s:14:1: error: unexpected token at start of statement
!5 = !{i32 1, !"EnableSplitLTOUnit", i32 1}
^
foo.c.s:15:1: error: unexpected token at start of statement
!6 = !{!"Debian clang version 17.0.6 (5)"}
^
foo.c.s:17:1: error: unexpected token at start of statement
^0 = module: (path: "", hash: (0, 0, 0, 0, 0))
^
foo.c.s:18:1: error: unexpected token at start of statement
^1 = flags: 8
^
foo.c.s:19:1: error: unexpected token at start of statement
^2 = blockcount: 0
^
```

**Comment by alejandro-colomar** [comment]
And this reduces the flags to just `-flto`:

```sh
alx@debian:~/tmp$ ls
foo.c
alx@debian:~/tmp$ cat foo.c 
alx@debian:~/tmp$ clang-17 -flto -S -o foo.c.s foo.c
alx@debian:~/tmp$ clang-17 -flto -c -o foo.c.o foo.c.s
foo.c.s:1:14: error: missing expression
; ModuleID = 'foo.c'
             ^
foo.c.s:3:19: error: unexpected token in argument list
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
                  ^
foo.c.s:4:15: error: unexpected token in argument list
target triple = "x86_64-pc-linux-gnu"
              ^
foo.c.s:6:1: error: unexpected token at start of statement
!llvm.module.flags = !{!0, !1, !2, !3, !4, !5, !6}
^
foo.c.s:7:1: error: unexpected token at start of statement
!llvm.ident = !{!7}
^
foo.c.s:9:1: error: unexpected token at start of statement
!0 = !{i32 1, !"wchar_size", i32 4}
^
foo.c.s:10:1: error: unexpected token at start of statement
!1 = !{i32 8, !"PIC Level", i32 2}
^
foo.c.s:11:1: error: unexpected token at start of statement
!2 = !{i32 7, !"PIE Level", i32 2}
^
foo.c.s:12:1: error: unexpected token at start of statement
!3 = !{i32 7, !"uwtable", i32 2}
^
foo.c.s:13:1: error: unexpected token at start of statement
!4 = !{i32 7, !"frame-pointer", i32 2}
^
foo.c.s:14:1: error: unexpected token at start of statement
!5 = !{i32 1, !"ThinLTO", i32 0}
^
foo.c.s:15:1: error: unexpected token at start of statement
!6 = !{i32 1, !"EnableSplitLTOUnit", i32 1}
^
foo.c.s:16:1: error: unexpected token at start of statement
!7 = !{!"Debian clang version 17.0.6 (5)"}
^
foo.c.s:18:1: error: unexpected token at start of statement
^0 = module: (path: "", hash: (0, 0, 0, 0, 0))
^
foo.c.s:19:1: error: unexpected token at start of statement
^1 = flags: 8
^
foo.c.s:20:1: error: unexpected token at start of statement
^2 = blockcount: 0
^
```

**Comment by alejandro-colomar** [comment]
Already broken in `clang-14`, the oldest Clang I have available:

```sh
$ clang-14 -flto -c -o foo.c.o foo.c.s
foo.c.s:1:14: error: missing expression
; ModuleID = 'foo.c'
             ^
foo.c.s:3:19: error: unexpected token in argument list
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
                  ^
foo.c.s:4:15: error: unexpected token in argument list
target triple = "x86_64-pc-linux-gnu"
              ^
foo.c.s:6:1: error: unexpected token at start of statement
!llvm.module.flags = !{!0, !1, !2, !3, !4}
^
foo.c.s:7:1: error: unexpected token at start of statement
!llvm.ident = !{!5}
^
foo.c.s:9:1: error: unexpected token at start of statement
!0 = !{i32 1, !"wchar_size", i32 4}
^
foo.c.s:10:1: error: unexpected token at start of statement
!1 = !{i32 7, !"PIC Level", i32 2}
^
foo.c.s:11:1: error: unexpected token at start of statement
!2 = !{i32 7, !"PIE Level", i32 2}
^
foo.c.s:12:1: error: unexpected token at start of statement
!3 = !{i32 7, !"uwtable", i32 1}
^
foo.c.s:13:1: error: unexpected token at start of statement
!4 = !{i32 7, !"frame-pointer", i32 2}
^
foo.c.s:14:1: error: unexpected token at start of statement
!5 = !{!"Debian clang version 14.0.6"}
^
```

**Comment by thesamesam** [comment]
What you're seeing is IR. Why are you splitting `foo.c.s` like that?

With `-c`, you're telling Clang it can't link. With LTO, there is no "real" (machinn code) object file produced yet, because that's done at link-time. You've forbidden it from linking (turning it into e.g. x86 machine code) and you've used LTO which means the output is IR.

**Comment by alejandro-colomar** [comment]
@thesamesam 

> What you're seeing is IR.

Can you link to something I can read?  I never heard of "IR".  :)

> Why are you splitting `foo.c.s` like that?

So that I can inspect the assembly code.  Some times it's interesting to see what the compiler is producing from my code.

I also produce foo.c.i preprocessed files (these are interesting for debugging).

When building with -flto it's unreadable, but if I disable -flto, I can see something.  Producing the intermediate files always makes it easy to do that when needed.

> 
> With `-c`, you're telling Clang it can't link. With LTO, there is no "real" (machine code) object file produced yet, because that's done at link-time. You've forbidden it from linking (turning it into e.g. x86 machine code) and you've used LTO which means the output is IR.

Yep, but is anything wrong in that?  I think I should pass -flto to all the intermediate steps in the build pipeline until I link.  Of course you could do it without intermediate steps, but then you can't inspect them when you need that.

**Comment by thesamesam** [comment]
> @thesamesam
> 
> > What you're seeing is IR.
> 
> Can you link to something I can read? I never heard of "IR". What do those letters mean? :) Is it this? [llvm.github.io/clangir](https://llvm.github.io/clangir/)

https://en.wikipedia.org/wiki/Intermediate_representation
> 
> > Why are you splitting `foo.c.s` like that?
> 
> So that I can inspect the assembly code. Some times it's interesting to see what the compiler is producing from my code.
> 
> I also produce foo.c.i preprocessed files (these are interesting for debugging).
> 
> When building with -flto it's unreadable, but if I disable -flto, I can see something. Producing the intermediate files always makes it easy to do that when needed.

I think `-ffat-lto-objects` could help if I understand your aim right.

> 
> > With `-c`, you're telling Clang it can't link. With LTO, there is no "real" (machine code) object file produced yet, because that's done at link-time. You've forbidden it from linking (turning it into e.g. x86 machine code) and you've used LTO which means the output is IR.
> 
> Yep, but is anything wrong in that? I think I should pass -flto to all the intermediate steps in the build pipeline until I link (that's how I've always done it with GCC). Of course you could do it without intermediate steps, but then you can't inspect them when you need that.

I am not sure this is a reasonable thing to expect. The machine code simply does not exist until LTO is done, and it's no longer at the level of individual TUs.

**Comment by eli-schwartz** [comment]
> So that I can inspect the assembly code. Some times it's interesting to see what the compiler is producing from my code.
> 
> I also produce foo.c.i preprocessed files (these are interesting for debugging).

This feels like a bit of a bizarre thing to want to do at all.

I mean, if you're going to dump the debug contents otherwise known as preprocessed files and "whatever asm this particular bugfix release of the compiler happens to emit" then...

... as you point out, this is "interesting" and "interesting for debugging".

But given that it is not actually intended for usefulness as part of the build system of a project, I'm afraid I don't at all understand why you'd instruct the Makefile rules to emit this instead of producing the expected files that are suitable for compilation of a project in a non-debugging context. Particularly when it turns out that due to a flawed understanding of the role which compilers serve within a project, this causes the project to fatally bug out when `-flto` happens to show up inside of the user's `$CFLAGS`. (No, you should not be using LTO as part of emitting debug dumps of compiler internals. This is *extremely* counter-productive. The whole point of LTO is to optimize object code across TUs, this is ***diametrically opposed*** to inspecting the compiler generated asm that happens before object code.)

Either do one or the other, please, but do not emit the assembly code as part of a production build system workflow.

**Comment by alejandro-colomar** [comment]
@thesamesam

> I think `-ffat-lto-objects` could help if I understand your aim right.

Exactly.  It helps with both of my aims: see readable assembly output in the .s files, and fix build errors by using -flto with intermediate files with Clang.  Thanks!
<http://www.alejandro-colomar.es/src/alx/alx/lib/liba2i.git/commit/?id=b2975c3063d820b9ba2b91bffbdc3ecbfd97e300>

> > Yep, but is anything wrong in that? I think I should pass -flto to all the intermediate steps in the build pipeline until I link (that's how I've always done it with GCC). Of course you could do it without intermediate steps, but then you can't inspect them when you need that.
> 
> I am not sure this is a reasonable thing to expect. The machine code simply does not exist until LTO is done, and it's no longer at the level of individual TUs.
> 
> Some of this is perhaps complicated by the fact that Clang has an integrated assembler too. There might be some flag to try suppress that (besides `-S` which you tried), but I dunno.

-ffat-lto-objects fixes all the problems, it seems.  :)

Have a lovely day!
Alex

**Comment by alejandro-colomar** [comment]
@eli-schwartz 

> This feels like a bit of a bizarre thing to want to do at all.
> 
> I mean, if you're going to dump the debug contents otherwise known as preprocessed files and "whatever asm this particular bugfix release of the compiler happens to emit" then...
> 
> ... as you point out, this is "interesting" and "interesting for debugging".
> 
> But given that it is not actually intended for usefulness as part of the build system of a project, I'm afraid I don't at all understand why you'd instruct the Makefile rules to emit this instead of producing the expected files that are suitable for compilation of a project in a non-debugging context. Particularly when it turns out that due to a flawed understanding of the role which compilers serve within a project, this causes the project to fatally bug out when `-flto` happens to show up inside of the user's `$CFLAGS`. (No, you should not be using LTO as part of emitting debug dumps of compiler internals. This is _extremely_ counter-productive. The whole point of LTO is to optimize object code across TUs, this is _**diametrically opposed**_ to inspecting the compiler generated asm that happens before object code.)
> 
> Either do one or the other, please, but do not emit the assembly code as part of a production build system workflow.

I don't have separate debug builds and production builds.  I debug on the (optimized) production builds directly, which makes the debug more reliable (even if it's more uncomfortable to some --not me--).

Have a lovely day!
Alex

**Comment by eli-schwartz** [comment]
> I don't have separate debug builds and production builds. I debug on the (optimized) production builds directly, which makes the debug more reliable

This is a false way of looking at it.

You are not debugging on the optimized production builds.

You are putting debug builds into production.

>  (even if it's more uncomfortable to some --not me--).

I hope that this project isn't intended for use by other people, but this line makes me very nervous.

**Comment by alejandro-colomar** [comment]
> > I don't have separate debug builds and production builds. I debug on the (optimized) production builds directly, which makes the debug more reliable
> 
> This is a false way of looking at it.
> 
> You are not debugging on the optimized production builds.
> 
> You are putting debug builds into production.

If those debug builds are optimized (`-O3 -flto -ffat-lto-objects`), I don't see why I shouldn't consider them production builds.  See CFLAGS:

```mk
alx@debian:~/src/alx/liba2i/main$ make nothing -p | grep ^CFLAGS.:=
CFLAGS := -O3 -std=gnu11 -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement -Wno-attributes -Wno-nullability-completeness -Wno-unknown-attributes -Wno-unknown-pragmas -Wno-unused-command-line-argument -fanalyzer -flto -ffat-lto-objects 
alx@debian:~/src/alx/liba2i/main$ make nothing -p CC=clang | grep ^CFLAGS.:=
CFLAGS := -O3 -std=gnu11 -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement -Wno-attributes -Wno-nullability-completeness -Wno-unknown-attributes -Wno-unknown-pragmas -Wno-unused-command-line-argument -Weverything -Wno-c++98-compat -Wno-empty-translation-unit -Wno-extra-semi-stmt -Wno-gnu-auto-type -Wno-gnu-line-marker -Wno-gnu-statement-expression -Wno-language-extension-token -Wno-nullability-completeness -Wno-nullability-extension -Wno-pre-c2x-compat -Wno-unknown-warning-option -Wno-unused-macros 
alx@debian:~/src/alx/liba2i/main$ make nothing -p CC=clang-18 | grep ^CFLAGS.:=
CFLAGS := -O3 -std=gnu11 -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement -Wno-attributes -Wno-nullability-completeness -Wno-unknown-attributes -Wno-unknown-pragmas -Wno-unused-command-line-argument -Weverything -Wno-c++98-compat -Wno-empty-translation-unit -Wno-extra-semi-stmt -Wno-gnu-auto-type -Wno-gnu-line-marker -Wno-gnu-statement-expression -Wno-language-extension-token -Wno-nullability-completeness -Wno-nullability-extension -Wno-pre-c2x-compat -Wno-unknown-warning-option -Wno-unused-macros -flto -ffat-lto-objects
```

With those CFLAGS, even if I'm staging the builds, GCC and Clang (>= 18) should be optimizing as much as is possible.  More so since all functions are defined as (C99) inline functions, so translation units are less important.

> 
> > (even if it's more uncomfortable to some --not me--).
> 
> I hope that this project isn't intended for use by other people, but this line makes me very nervous.

Well, it only means I don't use gdb(1) usually, but rather insert printf(3) statements in the right places, or similar debugging techniques that don't need a special build.  I hope that's not something to worry about.

The project is intended for use by other people.

Cheers,
Alex

**Comment by eli-schwartz** [comment]
[](url)

> If those debug builds are optimized (`-O3 -flto -ffat-lto-objects`), I don't see why I shouldn't consider them production builds. See CFLAGS:

I'm not referring the generation of gdb debuginfo when I refer to "debug builds". I'm referring to the frustration and inconsistency and inclusion of byzantine compiler misuse by circumventing and working around the healthy and robust use of the compiler as its developers expect, for the sake of emitting exploratory internal dumps of compiler state during builds intended to be sent into production, which have the side effect of breaking standard builds.

> Well, it only means I don't use gdb(1) usually, but rather insert printf(3) statements in the right places, or similar debugging techniques that don't need a special build. I hope that's not something to worry about. It was just hypothetical.
> 
> The project is intended for use by other people.

To be clear, my concern is that if it's intended for use by other people, those other people are going to be extremely frustrated by even the simple act of attempting to run `make && make install` because even that isn't going to work correctly.

(Which is not to say that I think gdb users are going to be happy. And you really, really, really should consider the difficulties imposed on people who are trying to debug projects that use your software)

I see that I was right to be concerned.

**Comment by eli-schwartz** [comment]
> Exactly. It helps with both of my aims: see readable assembly output in the .s files, and fix build errors by using -flto with intermediate files with Clang. Thanks!
> http://www.alejandro-colomar.es/src/alx/alx/lib/liba2i.git/commit/?id=b2975c3063d820b9ba2b91bffbdc3ecbfd97e300

I'm looking at this link and from a quick glance I am getting *very* nervous about reliability and usability.

**Comment by alejandro-colomar** [comment]
> > If those debug builds are optimized (`-O3 -flto -ffat-lto-objects`), I don't see why I shouldn't consider them production builds. See CFLAGS:
> 
> I'm not referring the generation of gdb debuginfo when I refer to "debug builds". I'm referring to the frustration and inconsistency and inclusion of byzantine compiler misuse by circumventing and working around the healthy and robust use of the compiler as its developers expect, for the sake of emitting exploratory internal dumps of compiler state during builds intended to be sent into production, which have the side effect of breaking standard builds.

Hmmm, I see a way to please both.  I could generate those files, but then don't use them, and do the actual compilation directly from the source code.  That's what I already do with precompiled headers, which I build just for making sure that the headers are self-contained but then don't use those precompiled headers at all.

> > Well, it only means I don't use gdb(1) usually, but rather insert printf(3) statements in the right places, or similar debugging techniques that don't need a special build. I hope that's not something to worry about. It was just hypothetical.
> > The project is intended for use by other people.
> 
> To be clear, my concern is that if it's intended for use by other people, those other people are going to be extremely frustrated by even the simple act of attempting to run `make && make install` because even that isn't going to work correctly.

That's working, AFAICS.  I've made it work with all GCCs, and now with all Clangs that I have available.

> (Which is not to say that I think gdb users are going to be happy. And you really, really, really should consider the difficulties imposed on people who are trying to debug projects that use your software)

I'm not used to gdb(1), so I prefer if a gdb(1) user reports a bug that they can't do X, and suggest a compiler flag to do that X, and then I can patch the build system.  I just don't support them because I don't know exactly what they want, not just because I don't want to help.  :)

> 
> I see that I was right to be concerned.

Thanks!  I'll be addressing some of those in a moment.

**Comment by alejandro-colomar** [comment]
> > Exactly. It helps with both of my aims: see readable assembly output in the .s files, and fix build errors by using -flto with intermediate files with Clang. Thanks!
> > http://www.alejandro-colomar.es/src/alx/alx/lib/liba2i.git/commit/?id=b2975c3063d820b9ba2b91bffbdc3ecbfd97e300
> 
> I'm looking at this link and from a quick glance I am getting _very_ nervous about reliability and usability.

I hope these will calm your nerves:
<http://www.alejandro-colomar.es/src/alx/alx/lib/liba2i.git/commit/?id=57272f44597783a2eb7b6357befc4aebd5f471e6>
<http://www.alejandro-colomar.es/src/alx/alx/lib/liba2i.git/commit/?id=214ac2a389450626e457cea8781f0119df1ae851>
